### ISSUE TITLE
io.Reader make by bytes.NewBuffer() is inefficiency in io.Copy()

### ISSUE THREAD

**Issue by heidawei** [golang/go#10009]
io.Reader make by  bytes.NewBuffer() is inefficiency in io.Copy() (in my test the server's QPS is 3000), but io.Reader come from http req.body(it is a io.Reader object) is efficient in io.Copy() (the server's QPS is 8000). in my test the []byte convert to io.Reader object, then copy to a io.Writer object.when i test this io.Writer like this: 
w.Write(payload[:])
the w is a io.Writer object, the efficiency is same with the io.Reader make by  bytes.NewBuffer().
who can tell me how to deal this?

**Comment by bradfitz** [comment]
Let's bring this to the golang-nuts@ mailing list and consider reopening here when there's something more concrete to go on.
