### ISSUE TITLE
cmd/godoc: document what godoc can do

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#10005]
Over the last couple of months I've learned that godoc does alot of usefull stuf, however I can't really find any good documentation for all the godoc capabilities in a single place.

For example the documenting of examples for godoc are documented in the testing package: http://golang.org/pkg/testing/#hdr-Examples. However I wouldn't look there for examples in documenting my code.

A single document with alle the capabilities of the godoc tool would be really usefull.

**Comment by rsc** [comment]
Maybe there should be a wiki page or a blog post about godoc.

**Comment by Thomasdezeeuw** [comment]
Now that the blog about examples is up at http://blog.golang.org/examples. I think this can be closed, unless you guys wanted to do more about it?
