### ISSUE TITLE
Deduce GOROOT for custom location of prebuilt go

### ISSUE THREAD

**Issue by krnowak** [golang/go#10012]
Shouldn't prebuilt go's GOROOT be deduced upon go binary's path instead of being hardcoded to /usr/local/go or c:\Go (unless GOROOT env var is specified of course)? Something like following:
```go
func getGoRootForPrebuilt() string {
	binDir := filepath.Dir(os.Args[0])
	if filepath.IsAbs(binDir) {
		return filepath.Clean(filepath.Join(binDir, ".."))
	}

	wd, err := os.Getwd()
	if err != nil {
		return defaultPrebuiltGoRoot()
	}
	return filepath.Clean(filepath.Join(wd, binDir, ".."))
}
```

**Comment by minux** [comment]
This has been proposed before but rejected. The reason was that a command
should not change behavior based on where it live.

**Comment by krnowak** [comment]
Well, I was rather thinking that this thing would be applied only for prebuilts which are easiest to install locally instead of system-wide. I don't know if such use is the most common one, though.

So kind of counter-argument for no-behavior-change-on-location-change would be users are changing the behavior for custom installs anyway. The GOROOT deduction would Do The Right Thing for both default installs (`/usr/local/go` or `C:\go`) and custom installs (anywhere else).

**Comment by minux** [comment]
One idea is that we change the GOROOT of the installed bin/go by relinking
cmd/go with -ldflags -X runtime.defaultGoroot "the correct goroot".

Relinking cmd/go only requires our 6l, so it should be OK to do during
installation, esp. for windows and Darwin where we can have custom steps
after copying the files.

/cc @adg do you think it's worth doing?

**Comment by nightlyone** [comment]
Doesn't relinking invalidate checksums of those binary files? So I wouldn't recommend it for official releases. But for roll-your-own go compiler compiled from source, that should be useful.

**Comment by minux** [comment]
You check checksum before installation, and the installer will relink
cmd/go automatically. That won't affect the checksum. In fact, you cannot
check the checksum after installation.

**Comment by nightlyone** [comment]
The idea is, to verify if something tempered with my binary. e.g. for forensics or security auditing. That's why I only talked about not doing that in releases.

**Comment by minux** [comment]
On Feb 26, 2015 2:40 PM, "Ingo Oeser" <notifications@github.com> wrote:
> The idea is, to verify if something tempered with my binary. e.g. for
forensics or security auditing. That's why I only talked about not doing
that in releases.

I believe the go linker in internal linking mode is fully deterministic now
so every time you link the program, the result is the same. I'm talking
about binary releases with installers, so I don't there is an issue with
file fingerprinting for security audit.

(And normally you do the initial checksum after the installation, so the
fact that installer modifies the file for the GOROOT shouldn't affect that.)

**Comment by adg** [comment]
Seems like a lot of trouble to avoid setting an environment variable, and
since they'll be setting GOPATH anyway they might as well set GOROOT.
