### ISSUE TITLE
Segmentation Fault during build

### ISSUE THREAD

**Issue by tgrosinger** [golang/go#10016]
**What version of Go are you using (go version)?**

    go version go1.4.1 linux/amd64

**What operating system and processor architecture are you using?**

Ubuntu 14.04.1

**What did you do?**

```go
package models

type Struct1 struct {
    Struct2
    irrelevant string
}

type Struct2 struct {
    Struct1
    irrelevant int
}
```

**What did you expect to see?**

An error message or warning during build

**What did you see instead?**

Full use of available memory and CPU for a few seconds, followed by:

```
$ go build -v
go build mypackage/models: /usr/local/go/pkg/tool/linux_amd64/6g: signal: segmentation fault (core dumped)
```

**Comment by minux** [comment]
Use Go 1.4.2. It has been fixed.

**Comment by tgrosinger** [comment]
@minux Will do, thank you.
