### ISSUE TITLE
cmd/go: support fossil in 'go get'

### ISSUE THREAD

**Issue by gour** [golang/go#10010]
Fossil (http://fossil-scm.org) is very nice version control system which, imho, is designed very much in the spirit of Go langauge itself being very powerful, but still much more **simple** to use in comparison with e.g. Git. Moreover, it does things a little bit different - e.g. keeping the whole repo in _single_ (sqlite3 database) file and not in flat database like e.g. '.git' and is very simple to handle repositories and it includes wiki, tickets system etc...we can sayn 'github in a box'. :-)

However, some things are done differently and Fossil therefore requires two steps to clone and checkout the repo:
1. fossil clone someURL repo.fossil
2. fossil open repo.fossil

However,  I consider that it would be very nice feature for Golang's ecosystem to have official support for working with Fossil DVCS which is very attractive to users preferring to have simple & powerful tool deliberately leaving out some features in order to keep things simple.

Sincerely,
Gour

**Comment by rsc** [comment]
go get is for downloading code over the network.
Are there common fossil hosting services like GitHub is for Git?

**Comment by gour** [comment]
> Are there common fossil hosting services like GitHub is for Git?

There is e.g. [Chisel](http://chiselapp.com/), but the point with Fossil is that it's kind of [github-in-a-box](http://fossil-scm.org/index.html/doc/trunk/www/fossil-v-git.wiki) so one can use any cheap shared hosting and [host](http://fossil-scm.org/index.html/doc/trunk/www/selfhost.wiki) Fossil repos as long as one can access URL via HTTP(S)/SSH.

**Comment by rsc** [comment]
Too late for Go 1.5. If you'd like to send fossil support for Go 1.6 (so that <meta> tags mentioning fossil work, without any hard-coded special cases for hosting), that is perfectly fine with me.

**Comment by gour** [comment]
I'm just in process of fully migrating to Git - Fossil is nice, but most of the development is simply happening within Git world so one has to be pragmatic to survive. ;)

**Comment by rbucker** [comment]
There are quite a few devs using fossil. That fossil is not supported is a shame. It has a number of strong an unique features... So here is my +1.

Just as a point of interest... since fossil is a single encapsulated executable that uses SQLite as it's storage engine It's ideally deployed in a docker container.

**Comment by gour** [comment]
Let me say that now I'm still interested for Fossil support in Go...

**Comment by davecheney** [comment]
I'd you would like to take a crack at it, the code for this lives in the
golang.org/x/tool/vcs (from memory) package.

Each vcs supported is represented as an instance of a common data structure
representing common operations.

Good luck.

Dave

**Comment by minux** [comment]
Update: it's in https://godoc.org/golang.org/x/tools/go/vcs,
and there is an slightly edited copy of vcs.go in cmd/go/vcs.go.

If you want to add fossil support to the go command, please
be sure to propose changes to both packages (and send the
CLs soon, before the Nov 1st code freeze date.)

**Comment by gour** [comment]
> Update: it's in https://godoc.org/golang.org/x/tools/go/vcs, and there is an slightly edited copy of vcs.go in cmd/go/vcs.go.

I was looking at docs and wonder if Go's vcs framework is flexible-enough to support Fossil, iow. Git, Mercurial and Subversion do function similarly in a sense that one clones/checkouts repo in a certain dir and that's it.

Otoh, with Fossil the situation a bit different and it requires 2 steps:

``` 
fossil clone URL repo.fossil 
fossil open repo,fossil (in some dir)
```

iow., the repo itself is fully contained in a single repo.fossil file which is actually Sqlite3 database, while checkout and/or working directoriy are in a another dir which is 'connected' with the repo file itself.

Any thought?

**Comment by minux** [comment]
How about combine the clone and open operations into
CreateCmd?

**Comment by timoteoponce** [comment]
+1 for this!!

**Comment by ksshannon** [comment]
I've started working on this, but there are two issues that are holding me up:

- The diff between x/tools/go/vcs and cmd/go/vcs prohibit fossil from being added to the x/ version.  At some point a `chdir` internal flag was added, and fossil required a similar internal flag.  I had to add a `mkdir` internal flag.

- The other is related to #10322, because fossil uses a single file.  All the IsDir() checks had to be handled as a special case for fossil, or removed.  If those checks are removed for all VCS, this change will be slightly easier.

**Comment by gour** [comment]
I've settled on using/learning Go and Fossil is my preferred DVCS, so wonder what is the status of this feature?

**Comment by ksshannon** [comment]
@gour I've got rudimentary support working, but I still need to handle some inconsistencies with tags and branches.  I haven't worked on it for a while, but I'll try to finish it up and submit a CL.

**Comment by gour** [comment]
@ksshannon 
>  I haven't worked on it for a while, but I'll try to finish it up and submit a CL.

Thanks a lot for your work on it!! Both Go and Fossil are great piece of software, so it would be terrific to make them play together. ;)
