### ISSUE TITLE
build: linux-arm-qemu lacks Go 1.4 and gcc

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10018]
The `linux-arm-qemu` environment lacks both Go 1.4 (which isn't tragic: we can push it to the buildlet on start-up, as we do for half the buildlets), but also lacks gcc (which means we can't build Go 1.4.2 to begin with to push it, and we presumably can't run certain cgo tests)

```
ante:cmd $ time gomote run linux-arm-qemu go/src/all.bash
##### Building Go bootstrap tool.
cmd/dist        
ERROR: Cannot find /go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /go1.4/bin/go: No such file or directory
Error running run: exit status 1
                
real    0m4.053s
user    0m0.060s
sys     0m0.019s
ante:cmd $ time gomote rm linux-arm-qemu  .
        
real    0m2.400s
user    0m0.053s
sys     0m0.011s

ante:cmd $  gomote puttar -gorev=883bc6ed0ea8 linux-arm-qemu
ante:cmd $ time gomote run linux-arm-qemu src/make.bash
# Building C bootstrap tool.
cmd/dist
/tmp/buildlet-scatch917031135/src/make.bash: line 132: gcc: command not found
Error running run: exit status 127

real    0m1.644s
user    0m0.088s
sys     0m0.000s
ante:cmd $ 
```

/cc @saljam

**Comment by saljam** [comment]
Ah, I thought we're just running the tests on them (I had forgotten about cgo). I'll add them both.

**Comment by bradfitz** [comment]
@saljam, note that if we put Go 1.4.x in the ARM filesystem (probably a good idea to speed things up), we need minimum Go 1.4.2, which contains critical 32-bit fixes. Hopefully we don't have to update it too often.

**Comment by bradfitz** [comment]
Or I could use the binaries from http://dave.cheney.net/unofficial-arm-tarballs for now instead, and we can run with CGO disabled.

But which ARM variant is this qemu emulating?  ARMv5, v6, v7?

**Comment by saljam** [comment]
Doesn't GOOS=linux GOARCH=arm ./make.bash on x86 cross compile the toolchain? Any reason not to use that to build Go 1.4?

**Comment by saljam** [comment]
It's ARMv7 (vexpress)

**Comment by bradfitz** [comment]
I prepared a Go 1.4 tarball for it but even removing all the unnecessary parts (test, testdata, api, doc, blog, misc, etc), extracting it adds 2 minutes and 20 seconds (!) to the `gomote push` time:

```
ante:cmd $ gomote push linux-arm-qemu2
2015/02/26 14:49:41 installing go1.4
2015/02/26 14:52:02 Remote doesn't have "doc/progs/json5.go"
...
```

**Comment by saljam** [comment]
Fair enough! CL incoming.

**Comment by bradfitz** [comment]
And gcc is still required, even to run make.bash currently: 

```
ante:cmd $ time gomote run linux-arm-qemu2 go/src/make.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /tmp/buildlet-scatch177488625/go1.4.
bootstrap/internal/obj
bootstrap/internal/asm
bootstrap/internal/obj/arm
bootstrap/5a
bootstrap/internal/gc
bootstrap/5g
bootstrap/internal/obj/x86
bootstrap/6a
bootstrap/6g
bootstrap/internal/obj/i386
bootstrap/8a
bootstrap/8g
bootstrap/internal/obj/ppc64
bootstrap/9a
bootstrap/9g
bootstrap/asm/internal/arch
bootstrap/asm/internal/flags
bootstrap/asm/internal/lex
bootstrap/asm/internal/asm
bootstrap/asm

##### Building compilers and go_bootstrap for host, linux/arm.
lib9
go tool dist: FAILED: gcc -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -fno-common -ggdb -pipe -Wuninitialized -O2 -fmessage-length=0 -c -I /tmp/buildlet-scatch177488625/go/include -DPLAN9PORT -I /tmp/buildlet-scatch177488625/go/src/lib9 -o /tmp/go-tool-dist-699532928/_exits.o /tmp/buildlet-scatch177488625/go/src/lib9/_exits.c
Error running run: exit status 2

real    2m27.928s
user    0m0.092s
sys     0m0.005s
```

**Comment by saljam** [comment]
https://go-review.googlesource.com/6172

**Comment by saljam** [comment]
With that patch `make.bash` runs fine, but `run.bash` fails to find the go binary. `gomote run go/bin/go` suggests that it's in fact there. Is that normal? Or should PATH have been set by gomote somehow?

    s@instance-1:~$ gomote -project airy-shuttle run linux-arm-qemu go/src/run.bash
    /tmp/buildlet-scatch703261494/go/src/run.bash: line 8: go: command not found
    ##### Building packages and commands.
    /tmp/buildlet-scatch703261494/go/src/run.bash: line 41: go: command not found
    Error running run: exit status 127
