### ISSUE TITLE
build: permission problems with distro-provided go and -installsuffix

### ISSUE THREAD

**Issue by krnowak** [golang/go#10011]
With go 1.4 a developer has to use also an -installsuffix option if they want to have a static build (as told in #9344). Passing -installsuffix results in a directory creation in GOROOT/pkg with that suffix, so static std library can be stored there (I believe). The problem is that using this option is not possible with go provided by a distro (unless developer is a root, which is unlikely), because GOROOT is usually something like /usr/lib/golang.

Calling `go get -a -tags netgo -ldflags -w -installsuffix nocgo <project>` produces following error:
`go install runtime: mkdir /usr/lib/golang/pkg/linux_amd64_nocgo/: permission denied`

Not sure if that is fixable, but maybe specifying a GOPKG env var would be a viable option/workaround? GOPKG env var would be for GOROOT/pkg like GOBIN is now for GOROOT/bin. Then the invocation would look like this:
`GOPKG="$HOME/some/dir" go get -a -tags netgo -ldflags -w -installsuffix nocgo <project>`

What do you think?

**Comment by minux** [comment]
You can't use "go install" (or "go get" without -d).

The -installsuffix trick only works with "go build".

**Comment by adg** [comment]
The situation is pretty easy to resolve; the user can just install a user-owned version of Go and work from that. I'm hesitant to add more configuration and make the build process more complex.
