### ISSUE TITLE
playground: 

### ISSUE THREAD

**Issue by carbocation** [golang/go#10013]
Version: Using playground as of 2015/02/26.
Architecture: (the architecture of the official playground at http://play.golang.org/ )
What did you do: Created a ticker to delay execution til a time in the future.
What happened: If the ticker was set to delay until 2015, the ticker returned immediately. If the ticker was set to delay until 2014 or 2016, it waited (as expected).
What was expected: If the ticker was set to delay until 2015, it should have waited, just as it did for 2014 or 2016.

To see the 2015 example which incorrectly returns immediately, please see here: http://play.golang.org/p/31OF29CrAp

To see the 2014 and 2016 examples, respectively, please see here http://play.golang.org/p/xEXr5CODE8 or here http://play.golang.org/p/Lxk9ivcB_q

I have not been able to reproduce this locally, so it seems to be an issue with the playground code (perhaps the Javascript?) rather than with go itself.

**Comment by bradfitz** [comment]
Click "About" in the playground to learn more about the playground environment.  And see http://blog.golang.org/playground
