### ISSUE TITLE
go/format: repeated import remains if there is a blank line between them

### ISSUE THREAD

**Issue by marcotmarcot** [golang/go#10025]
For instance, goimports transforms [1] into [2], but keep [3] as it is.

1:
```
package main

import (
       "fmt"
       "fmt"
)

func main() {
     fmt.Print("Hello world!")
}
```

2:
```
package main

import (
       "fmt"
}

func main() {
     fmt.Print("Hello world!")
}
```

3:
```
package main

import (
       "fmt"

       "fmt"
}

func main() {
     fmt.Print("Hello world!")
}
```

**Comment by josharian** [comment]
Thanks for the report. I think that this is working as intended. Within a run of non-space-separated imports, go/format and goimports both sort and deduplicate. They do no sorting (and consequently no deduplication) across groups or blank lines. This leaves some amount of control to decide how to organize your imports. This is particularly important with magic imports such as used by cgo. If we were to rearrange all imports at will, that would prevent third parties from implementing a tool such as cgo, which would be a pity.

**Comment by marcotmarcot** [comment]
Thanks for the comment.
