### ISSUE TITLE
community, collaboration: Go's official maintainers and library / web framework authors

### ISSUE THREAD

**Issue by redstrike** [golang/go#10021]
Coming from the land of PHP, I have seen a lot of efforts from the community to fix / improve / push the development of its. Those efforts also lead to the tightly collaboration between language's designers / maintainers and lib / framework authors for future releases.

Some PHP community's "notable efforts":
http://www.php-fig.org/
http://www.phptherightway.com/
https://packagist.org/
https://getcomposer.org/
https://thephpleague.com/

Fortunately, Golang was started as a very modern and well-[designed/backed/advocated] programming language. But after trying a lot of web frameworks (last month), it seems that we are lacking well-defined standard or the "right" way to solve some common problems (web development? deployment?). Day by day, I have to seek for the "fragmented" knowledges which are shared by a lot of Gophers (thanks to their efforts). It's very time consuming and painful for those who aren't living near any Golang's "hotspot" communities like me.

**I wonder is there any collaboration between Go's offficial maintainers and the library/framework authors? If you have been doing, it's very exciting to know.**

As an advocate of Go, I hope for a future that I could do anything with it on the server-side without considering about other languages and it's easier for those who don't have a solid Computer Science background to entry. In my point of view, there are many tasks/problems that beginners shouldn't try to solve themself, or there are many problems that we can solve without the overhead of understanding "how's the very complex things at the low-level works".

**Anyway, if you don't see this as an issue of Go, just ignores it. Maybe, it's just my own problems :D**

**Comment by adg** [comment]
You might want to check out gokit.io. It's scope is a bit wider than just
web development. Several Go team members are involved with that effort.

**Comment by adg** [comment]
(FWIW, such discussions belong on the [golang-nuts](https://groups.google.com/group/golang-nuts) mailing list.)
