### ISSUE TITLE
database/sql/driver: DefaultParameterConverter does not handle reflect.String

### ISSUE THREAD

**Issue by tpng** [golang/go#10020]
Currently inside http://golang.org/src/database/sql/driver/types.go#L230 (switch rv.Kind()), case reflect.String is not handled.
As a result, type like the following can not be scanned without implementing the Valuer interface.
```
type Test string
func (t Test) Value() (driver.Value, error) {
    return driver.String.ConvertValue(c)
}
```
Is it possible to add reflect.String case to the DefaultParameterConverter so the clients of the sql library does not need to implement the Valuer interface themselves?

**Comment by bradfitz** [comment]
I'd rather not go down that road and add more. I think it does enough as it is.

**Comment by theory** [comment]
Gotta say, I think that adding String would be a big help, making it easier to transparently use a whole lotta types without any further work.
