### ISSUE TITLE
crypto/tls: handshake failure with secure.quantserve.com

### ISSUE THREAD

**Issue by martende** [golang/go#10039]
Code produces:
2015/02/28 23:47:34 Get https://secure.quantserve.com/quant.js: remote error: handshake failure
but all browsers open it.
```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	res, err := http.Get("https://secure.quantserve.com/quant.js")
	if err != nil {
		log.Fatal(err)
	}
	robots, err := ioutil.ReadAll(res.Body)
	res.Body.Close()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", robots)
}
```

**Comment by titanous** [comment]
This is not a bug in `net/http`. `crypto/tls` does not support `TLS_RSA_WITH_RC4_128_MD5` which is the only cipher suite that [secure.quantserve.com supports](https://www.ssllabs.com/ssltest/analyze.html?d=secure.quantserve.com&s=70.42.160.24&latest).
