### ISSUE TITLE
mobile/app: app.State is nil in package init

### ISSUE THREAD

**Issue by rakyll** [golang/go#10031]
My Android application panics with the following error message, if I try to access app.State from a package's init.

```
E/Go      (18104): panic: interface conversion: interface is nil, not interface { AndroidContext() unsafe.Pointer; JavaVM() unsafe.Pointer }
E/Go      (18104): goroutine 1 [running]:
E/Go      (18104): golang.org/x/mobile/audio/al.init·1()
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/audio/al/al_android.go:245 +0x50
E/Go      (18104): golang.org/x/mobile/audio/al.init()
E/Go      (18104): 	golang.org/x/mobile/audio/al/_obj/_cgo_import.go:1 +0x3ac
E/Go      (18104): main.init()
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/example/basic/main.go:119 +0x70
E/Go      (18104): goroutine 17 [syscall, locked to thread]:
E/Go      (18104): runtime.goexit()
E/Go      (18104): 	/Users/jbd/pkg/gomobile/android-ndk-r10d/gomobile-init-619773321/go/src/runtime/asm_arm.s:1347 +0x4
E/Go      (18104): goroutine 4 [runnable]:
E/Go      (18104): golang.org/x/mobile/app.lineLog(0x93c081d0, 0x6)
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:41
E/Go      (18104): created by golang.org/x/mobile/app.init·1
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:69 +0x108
E/Go      (18104): goroutine 5 [runnable]:
E/Go      (18104): golang.org/x/mobile/app.lineLog(0x93c081e0, 0x4)
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:41
E/Go      (18104): created by golang.org/x/mobile/app.init·1
E/Go      (18104): 	/Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:76 +0x194
```

The package causes the panic does the following:

```go
func init() {
	state := app.State.(interface {
		JavaVM() unsafe.Pointer
		AndroidContext() unsafe.Pointer
	})
	// ...
}
```

**Comment by hyangah** [comment]
// State is global application-specific state.
// ...
// State is not valid until Run has been called.
var State interface{}


2015-02-27 14:38 GMT-05:00 Burcu Dogan <notifications@github.com>:

> My Android application panics with the following error message, if I try
> to access app.State from a package's init.
>
> E/Go      (18104): panic: interface conversion: interface is nil, not interface { AndroidContext() unsafe.Pointer; JavaVM() unsafe.Pointer }
> E/Go      (18104): goroutine 1 [running]:
> E/Go      (18104): golang.org/x/mobile/audio/al.init·1()
> E/Go <http://golang.org/x/mobile/audio/al.init%C2%B71()%0AE/Go>      (18104):  /Users/jbd/src/golang.org/x/mobile/audio/al/al_android.go:245 +0x50
> E/Go      (18104): golang.org/x/mobile/audio/al.init()
> E/Go <http://golang.org/x/mobile/audio/al.init()E/Go>      (18104):  golang.org/x/mobile/audio/al/_obj/_cgo_import.go:1 +0x3ac
> E/Go      (18104): main.init()
> E/Go      (18104):  /Users/jbd/src/golang.org/x/mobile/example/basic/main.go:119 +0x70
> E/Go      (18104): goroutine 17 [syscall, locked to thread]:
> E/Go      (18104): runtime.goexit()
> E/Go      (18104):  /Users/jbd/pkg/gomobile/android-ndk-r10d/gomobile-init-619773321/go/src/runtime/asm_arm.s:1347 +0x4
> E/Go      (18104): goroutine 4 [runnable]:
> E/Go      (18104): golang.org/x/mobile/app.lineLog(0x93c081d0, 0x6)
> E/Go      (18104):  /Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:41
> E/Go <http://golang.org/x/mobile/app/stdio_android.go:41E/Go>      (18104): created by golang.org/x/mobile/app.init·1
> E/Go <http://golang.org/x/mobile/app.init%C2%B71%0AE/Go>      (18104):  /Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:69 +0x108
> E/Go      (18104): goroutine 5 [runnable]:
> E/Go      (18104): golang.org/x/mobile/app.lineLog(0x93c081e0, 0x4)
> E/Go      (18104):  /Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:41
> E/Go <http://golang.org/x/mobile/app/stdio_android.go:41E/Go>      (18104): created by golang.org/x/mobile/app.init·1
> E/Go <http://golang.org/x/mobile/app.init%C2%B71%0AE/Go>      (18104):  /Users/jbd/src/golang.org/x/mobile/app/stdio_android.go:76 +0x194
>
> The package causes the panic does the following:
>
> func init() {
>     state := app.State.(interface {
>         JavaVM() unsafe.Pointer
>         AndroidContext() unsafe.Pointer
>     })
>     // ...
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/10031>.
>



-- 
__

**Comment by rakyll** [comment]
But we know about the current VM and the application context on JNI_Onload. We don't have to wait for app.Run to set the State.

**Comment by crawshaw** [comment]
We do in Java. I intended State to eventually provide access to some equivalent context on the iOS side, where the initialization order is reversed: Go is the entry point, init runs, then main starts and it is not until app.Run that we initialize UIKit.

The other less important but relevant thought I had on this is packages should work hard to minimize the init work they do in apps. Apps should start fast. I suspect initialization of almost all packages (including audio) should go into an internal sync.Once on first use.

**Comment by rakyll** [comment]
We can keep documenting that the State will be available after app.Run but can set the State resolver earlier and use these values internally if the init is fast enough and not affecting the startup performance. It is an internal implementation detail. If you fear that it will be abused by the users, I'm fine with doing to a sync.Once for the initialization of the audio package.

**Comment by rakyll** [comment]
In favor of accessing app.State after Run is invoked, I am closing the issue.
