### ISSUE TITLE
cmd/api: additional file causes spurious API change

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10032]
$ go run $GOROOT/src/cmd/api/run.go

Everything is fine.

$ touch $GOROOT/src/os/junk_arm
$ go run $GOROOT/src/cmd/api/run.go

exit status 1 with:

-pkg os (linux-arm), const O_SYNC = 1052672
-pkg os (linux-arm-cgo), const O_SYNC = 1052672

The only necessary feature of the file is that it has _arm in its name. No contents, no .go suffix.

/cc @bradfitz

**Comment by iwdgo** [comment]
Incidentally verified while working on api tool. Issue does not reproduce on tip
```
>gotip version
go version devel go1.20-e870de9936 Tue Dec 27 21:10:04 2022 +0000 windows/amd64
```
An empty file `junk_arm` or `junk_windows` is ignored as a `.go` file with package name as:
```
$GOPATH\golang\go\src\os>type junk_windows.go
package os

```
Testing API changes is now done using `go test` like:
```
$GOPATH\golang\go\src\cmd\api>gotip test -v -check
=== RUN   TestGolden
    api_test.go:60: skipping with -check set
--- SKIP: TestGolden (0.00s)
=== RUN   TestCompareAPI
--- PASS: TestCompareAPI (0.00s)
=== RUN   TestSkipInternal
--- PASS: TestSkipInternal (0.00s)
=== RUN   TestIssue21181
    api_test.go:216: skipping with -check set
--- SKIP: TestIssue21181 (0.05s)
=== RUN   TestIssue29837
    api_test.go:232: skipping with -check set
--- SKIP: TestIssue29837 (0.00s)
=== RUN   TestIssue41358
    api_test.go:246: skipping with -check set
--- SKIP: TestIssue41358 (0.00s)
=== RUN   TestCheck
--- PASS: TestCheck (83.63s)
PASS
ok      cmd/api 145.240s

```
