### ISSUE TITLE
runtime: TestGdbPython failing on linux/amd64

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#10033]
Not quite sure what's going on here. It works fine on the builders.

##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/daniel/src/go/.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/internal/asm
bootstrap/internal/obj/arm
bootstrap/internal/gc
bootstrap/internal/obj/x86
bootstrap/internal/obj/i386
bootstrap/5a
bootstrap/8a
bootstrap/6a
bootstrap/internal/obj/ppc64
bootstrap/asm/internal/lex
bootstrap/9a
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/5g
bootstrap/6g
bootstrap/8g
bootstrap/9g

##### Building compilers and go_bootstrap for host, linux/amd64.
lib9
libbio
liblink
cmd/ld
cmd/6l
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
internal/syscall/windows
os
reflect
fmt
encoding
encoding/binary
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go

##### Building packages and commands for linux/amd64.
cmd/internal/obj
archive/tar
compress/flate
hash
hash/crc32
compress/bzip2
compress/lzw
hash/adler32
container/list
archive/zip
compress/gzip
compress/zlib
container/ring
crypto
crypto/subtle
math/rand
crypto/cipher
cmd/internal/asm
cmd/internal/obj/arm
crypto/aes
crypto/des
math/big
crypto/sha512
crypto/hmac
crypto/md5
internal/syscall
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/pem
debug/dwarf
text/tabwriter
go/printer
cmd/5a
debug/elf
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
debug/macho
debug/pe
crypto/rsa
database/sql/driver
crypto/ecdsa
crypto/x509/pkix
database/sql
cmd/cgo
debug/gosym
debug/plan9obj
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
encoding/xml
mime
mime/quotedprintable
net/http/internal
go/format
hash/crc64
hash/fnv
html
html/template
image/color
image
image/color/palette
index/suffixarray
image/draw
image/jpeg
image/png
runtime/cgo
image/gif
internal/mime
internal/trace
math/cmplx
runtime/pprof
net
os/user
runtime/debug
runtime/race
testing
testing/iotest
testing/quick
text/scanner
cmd/internal/gc
cmd/internal/obj/x86
cmd/internal/obj/i386
cmd/8a
cmd/6a
cmd/internal/obj/ppc64
cmd/internal/goobj
cmd/internal/rsc.io/arm/armasm
crypto/x509
net/textproto
log/syslog
mime/multipart
net/mail
crypto/tls
cmd/9a
cmd/internal/rsc.io/x86/x86asm
cmd/asm/internal/arch
cmd/internal/objfile
net/http
net/smtp
cmd/asm/internal/flags
cmd/addr2line
cmd/asm/internal/lex
cmd/asm/internal/asm
cmd/dist
cmd/asm
expvar
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/fcgi
net/http/httputil
net/http/pprof
net/rpc
cmd/fix
cmd/go
net/rpc/jsonrpc
cmd/gofmt
cmd/link
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof/internal/profile
cmd/5g
cmd/6g
cmd/8g
cmd/9g
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/trace
cmd/yacc
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof

##### Testing packages.
ok  	archive/tar	0.006s
ok  	archive/zip	0.333s
ok  	bufio	0.051s
ok  	bytes	0.055s
ok  	compress/bzip2	0.045s
ok  	compress/flate	0.375s
ok  	compress/gzip	0.008s
ok  	compress/lzw	0.053s
ok  	compress/zlib	0.741s
ok  	container/heap	0.005s
ok  	container/list	0.019s
ok  	container/ring	0.009s
?   	crypto	[no test files]
ok  	crypto/aes	0.026s
ok  	crypto/cipher	0.002s
ok  	crypto/des	0.006s
ok  	crypto/dsa	0.004s
ok  	crypto/ecdsa	0.023s
ok  	crypto/elliptic	0.027s
ok  	crypto/hmac	0.002s
ok  	crypto/md5	0.003s
ok  	crypto/rand	0.016s
ok  	crypto/rc4	0.065s
ok  	crypto/rsa	0.091s
ok  	crypto/sha1	0.002s
ok  	crypto/sha256	0.003s
ok  	crypto/sha512	0.003s
ok  	crypto/subtle	0.004s
ok  	crypto/tls	0.640s
ok  	crypto/x509	0.511s
?   	crypto/x509/pkix	[no test files]
ok  	database/sql	0.022s
ok  	database/sql/driver	0.004s
ok  	debug/dwarf	0.006s
ok  	debug/elf	0.014s
ok  	debug/gosym	0.278s
ok  	debug/macho	0.014s
ok  	debug/pe	0.010s
ok  	debug/plan9obj	0.007s
?   	encoding	[no test files]
ok  	encoding/ascii85	0.013s
ok  	encoding/asn1	0.003s
ok  	encoding/base32	0.005s
ok  	encoding/base64	0.003s
ok  	encoding/binary	0.010s
ok  	encoding/csv	0.002s
ok  	encoding/gob	0.028s
ok  	encoding/hex	0.002s
ok  	encoding/json	0.107s
ok  	encoding/pem	0.002s
ok  	encoding/xml	0.007s
ok  	errors	0.009s
ok  	expvar	0.003s
ok  	flag	0.004s
ok  	fmt	0.027s
ok  	go/ast	0.003s
ok  	go/build	0.064s
ok  	go/doc	0.032s
ok  	go/format	0.008s
ok  	go/parser	0.020s
ok  	go/printer	0.222s
ok  	go/scanner	0.003s
ok  	go/token	0.021s
?   	hash	[no test files]
ok  	hash/adler32	0.005s
ok  	hash/crc32	0.002s
ok  	hash/crc64	0.002s
ok  	hash/fnv	0.002s
ok  	html	0.004s
ok  	html/template	0.024s
ok  	image	0.100s
ok  	image/color	0.012s
?   	image/color/palette	[no test files]
ok  	image/draw	0.055s
ok  	image/gif	0.037s
ok  	image/jpeg	0.109s
ok  	image/png	0.029s
ok  	index/suffixarray	0.013s
?   	internal/mime	[no test files]
?   	internal/syscall	[no test files]
?   	internal/trace	[no test files]
ok  	io	0.017s
ok  	io/ioutil	0.002s
ok  	log	0.003s
ok  	log/syslog	2.025s
ok  	math	0.005s
ok  	math/big	0.227s
ok  	math/cmplx	0.002s
ok  	math/rand	0.169s
ok  	mime	0.008s
ok  	mime/multipart	0.070s
ok  	mime/quotedprintable	0.101s
ok  	net	2.374s
ok  	net/http	3.819s
ok  	net/http/cgi	0.210s
ok  	net/http/cookiejar	0.004s
ok  	net/http/fcgi	0.003s
ok  	net/http/httptest	0.043s
ok  	net/http/httputil	0.007s
ok  	net/http/internal	0.003s
?   	net/http/pprof	[no test files]
ok  	net/mail	0.005s
ok  	net/rpc	0.008s
ok  	net/rpc/jsonrpc	0.005s
ok  	net/smtp	0.022s
ok  	net/textproto	0.003s
ok  	net/url	0.004s
ok  	os	0.233s
ok  	os/exec	0.115s
ok  	os/signal	3.330s
ok  	os/user	0.003s
ok  	path	0.002s
ok  	path/filepath	0.010s
ok  	reflect	0.060s
ok  	regexp	0.070s
ok  	regexp/syntax	0.358s
--- FAIL: TestGdbPython (0.31s)
	runtime-gdb_test.go:107: print mapvar failed: $1 = map[string]string = {[<error reading variable: Address 0xb85 out of bounds>] = <error reading variable: Address 0xb85 out of bounds>, [<error reading variable: Address 0x3 out of bounds>] = <error reading variable: Address 0x3 out of bounds>}
FAIL
FAIL	runtime	10.465s
?   	runtime/cgo	[no test files]
ok  	runtime/debug	0.008s
ok  	runtime/pprof	6.897s
?   	runtime/race	[no test files]
ok  	sort	0.098s
ok  	strconv	0.184s
ok  	strings	0.069s
ok  	sync	0.090s
ok  	sync/atomic	0.151s
ok  	syscall	0.004s
ok  	testing	2.476s
?   	testing/iotest	[no test files]
ok  	testing/quick	0.018s
ok  	text/scanner	0.003s
ok  	text/tabwriter	0.003s
ok  	text/template	0.088s
ok  	text/template/parse	0.007s
ok  	time	2.420s
ok  	unicode	0.020s
ok  	unicode/utf16	0.010s
ok  	unicode/utf8	0.006s
?   	unsafe	[no test files]
?   	cmd/5a	[no test files]
?   	cmd/5g	[no test files]
?   	cmd/6a	[no test files]
?   	cmd/6g	[no test files]
?   	cmd/8a	[no test files]
?   	cmd/8g	[no test files]
?   	cmd/9a	[no test files]
?   	cmd/9g	[no test files]
ok  	cmd/addr2line	0.458s
?   	cmd/asm	[no test files]
?   	cmd/asm/internal/arch	[no test files]
ok  	cmd/asm/internal/asm	0.016s
?   	cmd/asm/internal/flags	[no test files]
ok  	cmd/asm/internal/lex	0.002s
?   	cmd/cgo	[no test files]
?   	cmd/dist	[no test files]
ok  	cmd/fix	0.009s
ok  	cmd/go	0.006s
ok  	cmd/gofmt	0.031s
?   	cmd/internal/asm	[no test files]
?   	cmd/internal/gc	[no test files]
ok  	cmd/internal/goobj	0.008s
?   	cmd/internal/obj	[no test files]
?   	cmd/internal/obj/arm	[no test files]
?   	cmd/internal/obj/i386	[no test files]
?   	cmd/internal/obj/ppc64	[no test files]
?   	cmd/internal/obj/x86	[no test files]
?   	cmd/internal/objfile	[no test files]
ok  	cmd/internal/rsc.io/arm/armasm	0.007s
ok  	cmd/internal/rsc.io/x86/x86asm	0.159s
ok  	cmd/link	0.013s
ok  	cmd/nm	0.466s
ok  	cmd/objdump	1.111s
ok  	cmd/pack	1.760s
?   	cmd/pprof	[no test files]
?   	cmd/pprof/internal/commands	[no test files]
?   	cmd/pprof/internal/driver	[no test files]
?   	cmd/pprof/internal/fetch	[no test files]
?   	cmd/pprof/internal/plugin	[no test files]
?   	cmd/pprof/internal/profile	[no test files]
?   	cmd/pprof/internal/report	[no test files]
?   	cmd/pprof/internal/svg	[no test files]
?   	cmd/pprof/internal/symbolizer	[no test files]
?   	cmd/pprof/internal/symbolz	[no test files]
?   	cmd/pprof/internal/tempfile	[no test files]
?   	cmd/trace	[no test files]
?   	cmd/yacc	[no test files]
all.bash: exit 1

GDB version:
GNU gdb (GDB) Fedora 7.5.1-42.fc18

Go revision:
2adc3bd6ef84aa8b3d730f5d0d96a30427f2ecc2

**Comment by bradfitz** [comment]
The builders might have a different (or no) version of gdb.

**Comment by aclements** [comment]
@DanielMorsing, is this still a problem for you?

**Comment by DanielMorsing** [comment]
I've lost access to the machine where this was an issue on and can't reproduce on my current one.

I'm fine with marking this as resolved.
