### ISSUE TITLE
go not as smart about log.Panicf() as it is about panic()

### ISSUE THREAD

**Issue by ellisonch** [golang/go#10037]
Go is quite happy with the following program:
```.go
package main

import "fmt"
// import "log"

func foo(x int) int {
	if x == 0 {
		return 0
	}
	// log.Panicf("Not yet handling case %d", x)
	panic(fmt.Sprintf("Not yet handling case %d", x))
}

func main() {
	foo(0)
}
```
It understands that panic() is a "NoReturn" function, and so it eliminates `foo()`'s responsibility of returning an int in that case.  It compiles and runs.  However, if you swap the `panic()` with the `log.Panicf()` line (and of course swap the imports), go now complains:
```
.\panic.go:12: missing return at end of function
```
It seems that something needs to inform the compiler that `log.Panicf()` (and other similar functions) are also NoReturn.

$ go version
go version go1.4.1 windows/amd64

**Comment by bradfitz** [comment]
This is working as defined by the spec: http://golang.org/ref/spec#Terminating_statements

**Comment by ellisonch** [comment]
Where should I post issues about the spec?  It seems like having the concept of NoReturn would be a nice extension of the terminating statement idea.

**Comment by bradfitz** [comment]
Generally language change requests are first discussed at https://groups.google.com/forum/#!forum/golang-nuts
