### ISSUE TITLE
Wrong error message on compilation for empty body function

### ISSUE THREAD

**Issue by creack** [golang/go#10030]
Consider the following code: (http://play.golang.org/p/gvh848iNNI)

```go
package main

func test()

func main() {
}
```

Expected message: `missing function body`
Actual: `missing function body%!(EXTRA *gc.Node=&{<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> 47 false 0 0 0 0 false 0 0 0 0 0 false false 0 false 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 false 3 0 0x208729ce0 0x20872d600 0x20872d800 <nil> <nil> <nil> <nil> <nil> <nil> <nil> 0 <nil> {0 {0 0 <nil> <nil> <nil> <nil>}} <nil> <nil> <nil> <nil> <nil> 0 <nil> <nil> <nil> <nil> <nil> <nil> 0 <nil> <nil> <nil> <nil> <nil> 0 <nil> 0 0 3 3 -1000000000 0 0 0 0 0 <nil>})`

Go version: `go version devel +d68f52a Fri Feb 27 09:19:47 2015 +0000 darwin/amd64`

**Comment by andlabs** [comment]
[This bug was present in the old C version of the compiler as well, but overlooked.](https://github.com/golang/go/blob/883bc6ed0ea815293fe6309d66f967ea60630e87/src/cmd/gc/pgen.c#L182)

**Comment by sbinet** [comment]
tentatively: https://golang.org/cl/6263
