### ISSUE TITLE
cmd/go: easier cross compilation

### ISSUE THREAD

**Issue by davecheney** [golang/go#10049]
Currently cross compilation requires the user to build their native toolchain (`all.bash`) then rebuild their toolchain (`env GOOS=... GOARCH=... make.bash --no-clean`). 

This is problematic for a number of reasons, most notably, we guide people towards the binary releases of Go which prevent this recompilation step because the binary releases are not owned by the user.

With the advent of the rewrite of the compilers, users of 1.5 will have all the compilers as part of the binary installer. The only remaining issue is they will not have copies of `textflag.h` and `funcdata.h` in `$GOROOT/pkg/$GOOS_$GOARCH`.

It turns out that the contents of these two files do not change from architecture to architecture so as long as one copy of them exists in `$GOROOT`, all targets can reference them.

**Comment by minux** [comment]
SGTM.

**Comment by robpike** [comment]
SGTM
