### ISSUE TITLE
gofmt breaks channel syntax

### ISSUE THREAD

**Issue by bgeron** [golang/go#10040]
In Go 1.4.1, `gofmt` reformats `chan <-chan int` to `chan<- chan int`. The two are different in the AST, and indeed `gofmt` can break working source; see http://play.golang.org/p/L9xzobGwob for an example.

I'm using Ubuntu amd64. It is reproducible on my machine and in the Playground as follows:

1. Run. This succeeds.
2. Format. This succeeds.
3. Run. This fails.

**Comment by minux** [comment]
This is working as intended.

chan <-chan int is parsed as "chan<- (chan int)", so if you want "chan
(<-chan int)",
you have to use parenthesis.

http://golang.org/ref/spec#Channel_types
...
The <- operator associates with the leftmost chan possible
...

**Comment by bgeron** [comment]
Ah, I think I got confused by my own example. Apologies!
