### ISSUE TITLE
crypto/tls: add TLS_RSA_WITH_RC4_128_MD5?

### ISSUE THREAD

**Issue by volth** [golang/go#10044]
See #10039

**Comment by titanous** [comment]
RC4 was prohibited in [RFC 7465](https://tools.ietf.org/html/rfc7465), I think leaving it unimplemented is fine and recommended.

**Comment by volth** [comment]
That's legacy, but still in use on the servers.
As an alternative to implement it in the client we could scan the Internet, find all those servers and warn the responsible persons about the RFC prohibition.

**Comment by rsc** [comment]
@agl for policy. I'm pretty skeptical about dropping all the RC4 suites but I'm also perfectly fine with continuing to not support the combination of RC4+MD5.

**Comment by rsc** [comment]
Edited title. The original title said that "TLS_RSA_WITH_RC4_128_MD5 is the only cipher suite that some websites (e.g. secure.quantserve.com) support."

**Comment by minux** [comment]
secure.quantserve.com does support AES now.

TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA

**Comment by rsc** [comment]
Sounds like there's now no reason to do this.
