### ISSUE TITLE
"malformed pe file" then try use compiled package in windows

### ISSUE THREAD

**Issue by Loafter** [golang/go#10046]
I have strange error.
i try compile bridge packet for c++ cals in golang.

package gdcmgobr
/*
#cgo CPPFLAGS: -I"C:/GDCM/include/gdcm-2.4"
#cgo LDFLAGS: -L"C:/GDCM/lib" -lgdcmMSFF -lgdcmMEXD -lsocketxx -lgdcmMSFF -lgdcmjpeg8 -lgdcmjpeg12 -lgdcmjpeg16 -lgdcmopenjpeg -lgdcmDICT -lgdcmIOD -lgdcmexpat -lgdcmDSED -lgdcmCommon -lgdcmzlib -lWs2_32
*/
import "C"

packet compile and install fine. command "go install" produce nice gdcmgobr.a file
import "dtools/gdcmgobr" work fine.
when i try build exe. i get this error:
C:\Users\Alex\go\pkg\windows_amd64/dtools/gdcmgobr.a(gdcmgobr_wrap.o): malformed pe file: _cgo_topofstack: invalid symbol binding 105

gcc version 4.9.2 (x86_64-win32-seh-rev1, Built by MinGW-W64 project)
go version go1.4.2 windows/amd64

build enviroment:
GOROOT=c:\go
#GOBIN=
GOARCH=amd64
GOOS=windows
CGO_ENABLED=1

PATH=%GOROOT%\bin;%PATH%;
LITEIDE_GDB=gdb64
LITEIDE_MAKE=mingw32-make
LITEIDE_TERM=%COMSPEC%
LITEIDE_TERMARGS=
LITEIDE_EXEC=%COMSPEC%
LITEIDE_EXECOPT=/C

**Comment by minux** [comment]
The ultimate solution: #4069.

**Comment by ianlancetaylor** [comment]
For the record, symbol binding 105 indicates a weak external symbol.  That said, closing as a dup.  The only real fix for this is to fix #4069.

**Comment by Loafter** [comment]
so how i can fix this?
I see many sugest in discution but i can't see any solve

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't know of a workaround.

**Comment by loint** [comment]
@Loafter I have a same problem with you. how did you solve it ?

**Comment by minux** [comment]
Wait for Go 1.5 is one way. #4069 has been fixed in Go 1.5.
