### ISSUE TITLE
gccgo: fails to compile ambiguous type switch

### ISSUE THREAD

**Issue by h4ck3rm1k3** [golang/go#10047]
```
package test;

func clr(q interface{}) {
	switch x := q.(type) {
	case *x:
		return
	}
```
occurs in : https://github.com/cznic/ql/blob/master/btree.go
reported here : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65272

**Comment by paranoiacblack** [comment]
I can fix this, but it seems like you'd be better off not naming variables and types the same thing. The code you reference is confusing and it took me awhile to realize the `x` you expect `*x` to refer to is some struct type and not the variable `x` you declare for the scope of the switch statement. Unless there's something special I'm missing about that type switch.

**Comment by griesemer** [comment]
This is valid code and thus a gccgo bug:

Per http://golang.org/ref/spec#Switch_statements:

"The TypeSwitchGuard may include a short variable declaration. When that form is used, the variable is declared at the beginning of the implicit block in each clause."

The x mentioned in the short variable declaration is not yet in scope in case *x, and thus *x refers to the type x declared in an outer scope.

While valid code, this is clearly not not the most readable way of writing this as it's definitively confusing at first.

**Comment by h4ck3rm1k3** [comment]
I assumed it is a gccgo bug, the switch based on explicit types works, so I think that it is just not inferring the type properly.
