### ISSUE TITLE
builder: darwin/arm lldb needs to pass SIGSEGV

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10043]
The darwin/arm builder runs programs via lldb. (It is the only way to remotely dial the device running the binary.) The debugger likes to intercept signals that Go needs for normal operation. For example, there is a hidden panic inside the html/template tests that jams lldb. The obvious command does not work:

process handle SIGSEGV --stop false --pass true --notify false

It looks like passing on these signals may not be supported yet:

http://lists.cs.uiuc.edu/pipermail/lldb-dev/2013-July/002009.html

**Comment by minux** [comment]
could we simply supply a stream of "continue" command to
lldb?

or make lldb do "continue" upon reception of the SIGSEGV
signal (gdb can do "catch signal SIGSEGV", and then we
can define command to be executed when SIGSEGV is
received.)

**Comment by crawshaw** [comment]
I tried that manually. Giving lldb a continue instruction does not seem to work. (Even several times.)

**Comment by crawshaw** [comment]
LLDB engineer says its a long standing OS X bug and recommends we work around it:

https://llvm.org/bugs/show_bug.cgi?id=22868
