### ISSUE TITLE
mobile: distribute OpenAL library and header files from dl.google.com

### ISSUE THREAD

**Issue by rakyll** [golang/go#10057]
As discussed on [CL/6240](https://go-review.googlesource.com/#/c/6240/), we should distribute a prebuilt OpenAL shared library for Android. Due to licensing issues, we may want to include the OpenAL header files to the distribution archive.

The archive should contain libopenal.so that could be built by following the instructions on http://repo.or.cz/w/openal-soft.git/blob/HEAD:/XCompile-Android.txt

**Comment by rakyll** [comment]
@hyangah or @crawshaw, do you want to own this issue?

**Comment by crawshaw** [comment]
The process is easy enough to do, you just have to switch to our internal system.

But before that, we need a script somewhere in the mobile repository that does the build and packages up the tarball (along with the license file, and anything required to meet the license).

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/6720.
