### ISSUE TITLE
Memory allocation for a map of map

### ISSUE THREAD

**Issue by mDomingues** [golang/go#10053]
I was implementing an algorithm that uses a map of maps (e.g. map[int]map[string][]int ) but when trying to assign a slice of integers to key value I got an error message about assigning entry to nil map.
Sample code for better understanding:

data := make(map[int]map[string][]int)
...
   for id, each := range data {
         values, okToInsert := ready()
         if oktoInsert {
           newID := id + 5
          // Tag A
            data[newID]["db"] = values    // Error raised
        } 
}

To overcome this error I had to put a verification, in Tag A,  for the availability of the key map like:
if _, ok := data[newID]; !ok {
     data[newID] = make(map[string][]int)
} 

Why can't 'make' ensure this allocation ?

Thank you guys

**Comment by dvyukov** [comment]
You want outer make to allocate inner maps for what set of keys?

**Comment by ianlancetaylor** [comment]
Go doesn't work this way.  The zero value for a map can not be used directly; you have to run make first.  This is not going to change.
