### ISSUE TITLE
cmd/internal/ld: use cmd/internal/obj for constant definitions

### ISSUE THREAD

**Issue by 4ad** [golang/go#10055]
`cmd/internal/ld/link.go` contains the lower half of `cmd/internal/obj/link.go`. This makes 6l fail in mysterious ways when cmd/internal/obj/link.go is modified without modifying cmd/internal/ld/link.go as well. There is no mechanism to keep them in sync.

**Comment by rsc** [comment]
It is fine to drop the constants from ld and make code refer to obj, for the constants only. I think Michael Hudson-Doyle was talking about doing that but not sure.

**Comment by mwhudson** [comment]
Yes I still intend to do that, hopefully early next week my time.  Won't be
offended if someone beats me to it.

**Comment by mdempsky** [comment]
@rsc At golang.org/cl/9660, you describe golang.org/cl/9112 as unfortunate, which seems contradictory to your above comments from March 20.  Can you please elaborate?

In case the CL description wasn't clear, the only constants that were converted from package ld to package obj were the ones removed from cmd/internal/ld/link.go.  See: https://go-review.googlesource.com/#/c/9112/3/src/cmd/internal/ld/link.go

Re-reviewing the CL, the "LSym.type", "Reloc.type", and "Auto.name" constants (which make up about 2/3rd of the CL) are all serialized into object files, so it seems undesirable to allow the compiler and linker values to diverge.

Converting ld.HistVersion to obj.HistVersion perhaps was unnecessary, but that's easily fixed: there was only one use of ld.HistVersion that was converted.

Converting ld.Hlinux, etc. to obj.Hlinux (~1/3rd of the CL) was arguably unnecessary too, but it seems unlikely that we'd intentionally want the compilers and linkers to support divergent sets of GOOS values.
