### ISSUE TITLE
Golang  thread issue

### ISSUE THREAD

**Issue by moypray** [golang/go#10051]
When I wrote a "hello world" program, only two line:

  fmt.Println("xx")
  time.Sleep(1000*time.Second)

And then go build,  run the program, i found that it will create 2 more threads (3 threads in all).

I wonder if there is a way to stop creating other threads?

Actually, in linux environment, if more threads are created, we can not use unshare(CLONE_NEWUSER) syscall.

**Comment by dvyukov** [comment]
> I wonder if there is a way to stop creating other threads?

No, there is no way.

> can not use unshare(CLONE_NEWUSER) syscall.

Why?

**Comment by ianlancetaylor** [comment]
Go programs are always multi-threaded.  unshare(CLONE_NEWUSER) is defined to only work if the program is not multi-threaded.  I don't see any way to call it in a Go program.  You will have to write a wrapper, perhaps using the /usr/bin/unshare command.

See also #1954.

**Comment by minux** [comment]
If you want to use unshare, one way is to call it inside a constructor
where the process is still single threaded.

/*
__attribute__((constructor)) void enter_ns(void) {
    // call unshare here
}
*/
import "C"

**Comment by moypray** [comment]
@minux  thanks for your reply.  
And may I use flag package in this function , just like " flag.NArg()" and  "flag.Arg(1)"  ??

If no, how to handle argument of the program in this early phase?

**Comment by minux** [comment]
in the constructor, you can't call any Go functions as the Go runtime
hasn't been
initialized yet.

as a workaround, open /proc/self/cmdline and parse the command line
arguments.

**Comment by moypray** [comment]
@minux thanks a lot.
