### ISSUE TITLE
x/mobile/app: events get delayed after resizing the window on X11

### ISSUE THREAD

**Issue by db47h** [golang/go#10054]
Steps to reproduce:

- run the basic example
- move the triangle around -> no delay
- resize the window
- move the triangle around -> the triangle will move after a delay (which looks equal to the amount of time spent resizing the window)

**Comment by crawshaw** [comment]
@db47h is this still happening? @nigeltao made some significant event model changes that may have fixed this.

**Comment by db47h** [comment]
I had put this on hold while keeping an eye on the undergoing changes ;) I'll check this asap and will get back to you.

**Comment by db47h** [comment]
Yes, it's now working correctly (compiled with Go 1.4 but I guess it does not matter on desktop).

**Comment by crawshaw** [comment]
Thanks for checking.
