### ISSUE TITLE
syscall: undefined: syscall.Syscall9 on darwin/amd64

### ISSUE THREAD

**Issue by mikioh** [golang/go#10068]
An external package using syscall.Syscall9 cannot build on darwin/amd64. The build simply fails with a linker error "undefined: syscall.Syscall9." Both darwin/386 and darwin/arm are fine.

**Comment by minux** [comment]
note that Darwin/arm's Syscall9 is actually Syscall7.

**Comment by mikioh** [comment]
I filed #10073 for darwin/arm.
