### ISSUE TITLE
build: read build tags from an environment variable

### ISSUE THREAD

**Issue by Manbeardo** [golang/go#10063]
When using a toolkit that needs to use build tags (such as appengine), several tools in golang.org/x/tools/cmd become useless (godoc, gorename, etc.) become useless because they don't take build tags as arguments and ignore all of your source files.

If build's defaultContext() read build tags from an environment variable (e.g. $GOTAGS), all of these tools would support projects that use build tags. This is much cleaner and easier to deal with than adding a -tags option to every one of these commands.

**Comment by bradfitz** [comment]
Whenever new environment comes up, there's always a lot of pushback. Go isn't very fond of them in general.

Also, that means all tools need to decide precedence or merging between explicit flags and the environment.

I think the proper fix is adding flags to tools where it's lacking.

**Comment by davecheney** [comment]
Russ also suggested that he was thinking about refactoring cmd/go into some
reusabl pieces. Hopefully if this were to happen it would allow tool
writers to consume a single way of talking about go packages and source
files which might make this problem less of an issue.
