### ISSUE TITLE
mobile: go initialization fails missing _rt0_arm_linux1

### ISSUE THREAD

**Issue by rakyll** [golang/go#10067]
I'm building the basic example with the tip version of gomobile and Go.

gomobile install golang.org/x/mobile/example/basic # and run the app

```
W/linker  (17106): libbasic.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
F/Go      (17106): missing _rt0_arm_linux1
F/libc    (17106): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 17123 (Thread-1471)
I/libc    (17106): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
I/Zygote  (  199): Process 17106 exited due to signal (11)
I/ActivityManager(  755): Process com.example.basic (pid 17106) has died
I/ActivityManager(  755): Start proc 17124:com.example.basic/u0a129 for activity com.example.basic/android.app.NativeActivity
```

**Comment by crawshaw** [comment]
What revision of Go?

Can you nm your .so file (with arm-linux-androideabi-nm) and see if the symbol is there, and what state it is in? The actual symbol is still in the runtime, so at a guess the symbol is in some unreachable state due to a recent linker change.

**Comment by rakyll** [comment]
```
go version
go version devel +0153137 Tue Mar 3 20:34:07 2015 +0000 darwin/amd64

arm-linux-androideabi-nm lib/armeabi/libbasic.so | grep _rt0_arm_linux1
000cdb58 t _rt0_arm_linux1
00292558 b _rt0_arm_linux1
```

**Comment by minux** [comment]
So _rt0_arm_linux1 is not exported.

**Comment by crawshaw** [comment]
Right, the lower case t and b mean the symbol is local. Until very recently it was exported (and nm showed an upper case T and B).

**Comment by crawshaw** [comment]
//go:cgo_export_dynamic _rt0_arm_linux1 is just where it has always been in os_android_arm.go.

I'm tempted to try git bisect to find which CL broke this, but my workspace is a mess with darwin/arm. Does someone else want to take it? If not, I'll probably get to this tomorrow afternoon.

**Comment by minux** [comment]
I will take a look today.

**Comment by minux** [comment]
The problem is that in go.o, the symbol is GLOBAL with HIDDEN visibility:
  1279: 00045360    16 FUNC    GLOBAL HIDDEN     1 _rt0_arm_linux1

**Comment by rakyll** [comment]
I can confirm that gomobile apk builds are running properly now. Thanks @minux.
