### ISSUE TITLE
build: test in all.bash that android/arm shared libraries work

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10070]
Looks like android builds are broken because the entry point for the shared library is no longer exported: #10067. Worryingly, no test failed on the dashboard. It would be nice to have some minimal (no mobile repository dependency) test that these .so files are good in all.bash.

**Comment by bradfitz** [comment]
run.bash is about to be nuked in a few seconds here. Will be in dist test instead.

**Comment by crawshaw** [comment]
Design sketch:

Compile a small C program with gcc from the Android NDK. (It is already on the builder, we use gcc as the external linker.) It looks something like:

int main(int argc, char** argv) {
        if (!dlopen(argv[1], RTLD_LAZY|RTLD_GLOBAL)) {
                printf("android_test_harness: dlopen %s failed\n", argv[1]);
               return 1;
        }

        int (*_rt0_arm_linux1)(int argc, char** argv);
        _rt0_arm_linux1 = (int (*)(int, char**))dlsym(RTLD_DEFAULT, "_rt0_arm_linux1");
        if (!_rt0_arm_linux1) {
               printf("android_test_harness: %s missing _rt0_arm_linux1", argv[1]);
               return 1;
        }
        _rt0_arm_linux1(argc, x.argv); // Go program starts.
        return 0;
}

The test sends the binary of this along with the lib.so of a little hello world to the android device with adb push, and then runs

adb shell android_test_harness lib.so

and looks for a magic string printed by the small Go program. If that works, everything else is up to the code in the mobile repository.

**Comment by minux** [comment]
We can create a test for linux/arm too: we just need to test //go:cgo_export_dynamic
is correctly exporting the symbol.

**Comment by crawshaw** [comment]
As discussed, I believe this can look a lot like the c-archive test I just added:

https://go-review.googlesource.com/#/c/8897/

I believe linux/amd64 is as a point where such a test should work, so it's a nice place to prototype without worrying about exec scripts.
