### ISSUE TITLE
Time Zero MarshalJSON / UnmarshalJSON produces a different object

### ISSUE THREAD

**Issue by simon3z** [golang/go#10089]
It seems that marshaling and unmarshaling a zero time produces an object that is different from the original:

    func TestMarshalUnmarshalJSON(t *testing.T) {
            var expected, parsed Time

            body, err := expected.MarshalJSON()
            if err != nil {
                    t.Errorf("json.Marshal error = %v", err)
            }

            err = parsed.UnmarshalJSON(body)
            if err != nil {
                    t.Errorf("json.Unmarshal error = %v", err)
            }

            if !reflect.DeepEqual(expected, parsed) {
                    t.Errorf("json error, expected = %#v, parsed = %#v", expected, parsed)
            }
    }

    --- FAIL: TestMarshalUnmarshalJSON (0.00 seconds)
            time_test.go:807: json error, expected = time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}, parsed = time.Time{sec:0, nsec:0x0, loc:(*time.Location)(0x6cd2a0)}

**Comment by minux** [comment]
Parsing a time will get a non-zero location. This is working as intended. You shouldn't use == to compare time.Time's.

**Comment by simon3z** [comment]
@minux then this looks like a DeepEqual bug

**Comment by minux** [comment]
No. DeepEqual is documented to use ==.

**Comment by simon3z** [comment]
@minux exactly, but as you said, it shouldn't if that's not the way to compare Time

**Comment by cespare** [comment]
@simon3z wrong conclusion.

* `DeepEqual` uses `==`
* `time.Time`s should not be compared with `Equal`, not `==`
* These both cannot change because of the Go 1 compatibility promise
* Therefore `DeepEqual` should not be used if the structures you're comparing contain `time.Time`s

If you need a `DeepEqual` that knows about `time.Time`s, you will need to write it.

**Comment by simon3z** [comment]
@cespare probably a better design would be something like:

    type compare func(a1, a2 interface{}) int

    DeepCompare(a1, a2 interface{}, fn compare)

do you think it could be something I could write/include in the reflect package?

**Comment by cespare** [comment]
@simon3z Better deep comparison is interesting, but let's take this to the golang-nuts mailing list.

**Comment by rjeczalik** [comment]
@simon3z If you really care about comparing times directly (part of larger struct), you can get away by keeping times in the same timezone (like http://play.golang.org/p/GhvxWMgk-x), but it just workarounds the fact they should be compared with http://golang.org/pkg/time/#Time.Equal.
