### ISSUE TITLE
build/cmd/builder: don't rely on fast-forwards for updating local git repo

### ISSUE THREAD

**Issue by adg** [golang/go#10085]
The builder does a "git pull" to update its local copy of the go repo, but that might fail if the repo is force-pushed to fix a bad merge (as happened recently).

Instead it should do something like `git fetch && git reset --hard origin/master`.

cc @bradfitz

**Comment by bradfitz** [comment]
Mostly irrelevant these days. Almost all builders use the new-style builder which doesn't run "git" at all.

But still applies to people who run the old builders.
