### ISSUE TITLE
cmd/internal/gc: static initialization for function variables

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10081]
Currently, this file:

    package bug
    func f() {}
    var g = f

requires a dynamic initializer to assign g.  This seems unnecessary though, because the compiler has already statically allocated the (empty) function closure for f, so g could just be statically initialized to point to that closure.

**Comment by jnjackins** [comment]
I think gopherbot forgot to close this issue.

**Comment by minux** [comment]
FTR, the syntax used in that revision is not recognized by github.
