### ISSUE TITLE
x/build/builders: GCE builders rebuilding Go 1.4 stdlib

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10093]
Looking at builder output from the builders for OpenBSD (e.g., http://build.golang.org/log/17dc0b960c3584cd864234107690de0ceca8ade1) and FreeBSD (e.g., http://build.golang.org/log/7c05e6bebd2e58ae1cdc6ee7ccccea1707e4ca65) you can see that when building the bootstrap toolchain, packages from the Go 1.4 stdlib are being rebuilt too.  Probably not slowing things down terribly, but would be better if they didn't need to.

By comparison, Linux (e.g., http://build.golang.org/log/f049cba51bdf31fda8fd7df29b9ec31e5be530b7) only builds the bootstrap/* packages/commands.

**Comment by bradfitz** [comment]
/cc @adg 

Some modtime issue?

**Comment by bradfitz** [comment]
And/or ntpd issue?

**Comment by minux** [comment]
Probably not related to system time (ntpd) though. The go command
only cares about relative order of modification timestamp on the package
binaries and their sources.

**Comment by adg** [comment]
Since we upload both 1.4 and the revision under test to the buildlet concurrently, and for some reason their modtimes are set to time.Now—which is odd, because the times ARE set in the tarball.

**Comment by adg** [comment]
Hmm, actually I looked at the official distros that set the modtime. @bradtfitz would have created the openbsd 1.4 tarball using a buildlet, and so it won't have any modtimes. That's the problem.

**Comment by bradfitz** [comment]
Just checked openbsd, freebsd, both 386 and amd64 of each, and I no longer see this.

They all look like:

```
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /tmp/workdir/go1.4.
bootstrap/internal/dwarf
bootstrap/internal/sys
bootstrap/asm/internal/flags
bootstrap/internal/obj
bootstrap/internal/bio
bootstrap/compile/internal/big
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/mips
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/s390x
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/compile/internal/syntax
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/compile/internal/ssa
bootstrap/internal/gcprog
bootstrap/link/internal/ld
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/mips64
bootstrap/link/internal/ppc64
bootstrap/link/internal/s390x
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/gc
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/mips64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/s390x
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, freebsd/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
encoding
errors
internal/race
...
```

Closing unless people see otherwise.
