### ISSUE TITLE
doc: update asm.html for 1.5

### ISSUE THREAD

**Issue by robpike** [golang/go#10096]
The 1.5 assembler is mostly compatible with the old one, but there are differences. Make sure that the document is accurate in time for the 1.5 release.

A full manual would be nice but is not urgent.

**Comment by crawshaw** [comment]
It would be nice to mention quirks of ppc64 and arm64. For example, a frame size of $-8 seems to mean don't save LR, similar to $-4 on arm.

**Comment by minux** [comment]
The following text is merged from #10932.

missing pieces:
1. more textflags (`NEEDCTXT`, `LOCAL`)
2. no more reference to C source code in compiler/linker (e.g. `$GOROOT/src/cmd/8l/8.out.h`)
3. need docs for ppc64/ppc64le and arm64 specific problems

needs update:
1. "Some of the assemblers enforce this convention, rejecting plain 0(FP) and 8(FP). " I believe cmd/asm enforces this now, so it should be changed to "all assemblers enforce this convention".

There are probably others things that need update.

**Comment by ALTree** [comment]
At the beginning:

> The assembler is based on the input to the Plan 9 assemblers, which is documented in detail on the Plan 9 site. 

The link to the Plan 9 site is broken (http://plan9.bell-labs.com/sys/doc/asm.html)

**Comment by robpike** [comment]
Yes, the plan9.bell-labs.com site is down. I doubt this is a permanent condition.

**Comment by robpike** [comment]
Now done.
