### ISSUE TITLE
gccgo: cannot be used to bootstrap go 1.5

### ISSUE THREAD

**Issue by h4ck3rm1k3** [golang/go#10092]
There is a strange bug when you run the go command from this source tree compiled with gccgo 4.9

Using gccgo-5 
gccgo-5 (Debian 5-20150226-1) 5.0.0 20150226 (experimental) [trunk revision 220999]

compile like this 
```
gccgo-5  -g -o go6 cmd/go/main.go cmd/go/build.go cmd/go/clean.go cmd/go/context.go cmd/go/discovery.go cmd/go/doc.go cmd/go/env.go cmd/go/fix.go cmd/go/fmt.go cmd/go/generate.go cmd/go/get.go cmd/go/go11.go cmd/go/help.go cmd/go/http.go cmd/go/list.go cmd/go/pkg.go cmd/go/run.go cmd/go/signal.go cmd/go/signal_unix.go cmd/go/testflag.go cmd/go/test.go cmd/go/testgo.go cmd/go/tool.go cmd/go/vcs.go cmd/go/version.go cmd/go/vet.go cmd/go/cc.go
```

ln -s ~/experiments/go/src/go6 ~/go1.4/bin/go

run then like this
```
export GOROOT=~/experiments/go/
export GOPATH=~/experiments/go/
./all.bash 
```

errors out with 

```
import cycle not allowed
package cmd/dist
	imports bytes
	imports errors
	imports runtime
	imports unsafe
	imports runtime
```

**Comment by h4ck3rm1k3** [comment]
When I link then the source code to  the ~/go1.4/src we get a different error

    ln -s ~/experiments/go/ . ~/go1.4/

and then
build the dist outside the system.
cp dist.6 cmd/dist/dist 

```
mdupont@mdupont-Aspire-7750G:~/go1.4/src$ bash ./all.bash 
##### Building Go bootstrap tool.
cmd/dist
WORK=/tmp/go-build179595840

##### Building Go toolchain using /mnt/data/home/mdupont/go1.4.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/internal/gc
bootstrap/internal/obj/arm
bootstrap/internal/ld
bootstrap/internal/obj/x86
bootstrap/internal/obj/ppc64
bootstrap/asm/internal/lex
bootstrap/internal/asm
# bootstrap/asm/internal/lex
../../../../go1.4/pkg/bootstrap/src/bootstrap/asm/internal/lex/tokenizer.go:43:3: error: reference to undefined field or method 'IsIdentRune'
  s.IsIdentRune = isIdentRune
   ^
bootstrap/old5a
bootstrap/old9a
# bootstrap/internal/gc
../../../../go1.4/pkg/bootstrap/src/bootstrap/internal/gc/reg.go:224:2: error: missing statement after label
  memcase:
  ^
bootstrap/asm/internal/arch
bootstrap/old6a
bootstrap/old8a
bootstrap/5l
bootstrap/6l
bootstrap/8l
bootstrap/9l
go tool dist: FAILED: /mnt/data/home/mdupont/go1.4/bin/go install -v bootstrap/...

```

So you turn off the deleting of the dist tool and build it manually.

**Comment by h4ck3rm1k3** [comment]
see my branch here  with the make file
https://github.com/h4ck3rm1k3/google-go/commit/cc2b9429120e2bd7408553be60d10fd67a2247de

cpu info did not build, skipped it
https://github.com/h4ck3rm1k3/google-go/commit/c282bd68b42254a2ac33aab4203c4a8060c186ed#diff-08b793eecf5656817d57c70701b1c45cL490

turn off the build of dist 
https://github.com/h4ck3rm1k3/google-go/commit/c282bd68b42254a2ac33aab4203c4a8060c186ed#diff-0bd01a098860e0bfe2917d0ee12e7575L120

**Comment by ianlancetaylor** [comment]
I think the "import cycle not allowed" problem happens when gccgo sees packages that have the same name as packages in GOROOT.  Because gccgo has no GOROOT, it gets confused and thinks those packages are the ones in GOROOT.  That is, if GOPATH has a time package, gccgo thinks that is the package it is supposed to use for import "time", even though really it will use the standard time package.  This doesn't happen with the gc compiler because it sees the GOROOT time package and knows that one will be used first.  Since gccgo has no GOROOT, this does not happen.

The way that the go tool handles GOROOT needs to change when using gccgo.

**Comment by h4ck3rm1k3** [comment]
Yes, that is right. The problem with the cycle was resolved when I
symlinked in the code into the goroot

On Fri, Mar 13, 2015 at 5:25 PM, Ian Lance Taylor <notifications@github.com>
wrote:

> I think the "import cycle not allowed" problem happens when gccgo sees
> packages that have the same name as packages in GOROOT. Because gccgo has
> no GOROOT, it gets confused and thinks those packages are the ones in
> GOROOT. That is, if GOPATH has a time package, gccgo thinks that is the
> package it is supposed to use for import "time", even though really it will
> use the standard time package. This doesn't happen with the gc compiler
> because it sees the GOROOT time package and knows that one will be used
> first. Since gccgo has no GOROOT, this does not happen.
>
> The way that the go tool handles GOROOT needs to change when using gccgo.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/10092#issuecomment-79483750>.
>



-- 
James Michael DuPont
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by mwhudson** [comment]
I'm not sure what is going on with this bug, but if I use the go-5 binary that comes with the gccgo-5 package on vivid (as in "mkdir -p ~/gccgo_for_bootstrap/bin; ln -s /usr/bin/go-5 ~/gccgo_for_bootstrap/bin/go; GOROOT_BOOTSTRAP=~/gccgo_for_bootstrap ./make.bash") then the only issues that prevent it working are the assembly files in the cmd/dist directory.

**Comment by mwhudson** [comment]
See linked branch for a fix for that; with this applied, the bootstrap completes for me.

**Comment by h4ck3rm1k3** [comment]
Great news, will check it out.

**Comment by davecheney** [comment]
https://go-review.googlesource.com/8809

Please test

**Comment by minux** [comment]
Note that you don't need to make a GOROOT directory structure.

If you installed gccgo to /usr/local, then setting
GOROOT_BOOTSTRAP=/usr/local
should do.

**Comment by h4ck3rm1k3** [comment]
I have been able to do this now. 

setting these environmental variables
export GOTOOLDIR=${HOME}/install/bin
export GCCGO=${HOME}/install/bin/gccgo
export LD_LIBRARY_PATH=${HOME}/install/lib64
export PATH=${PATH}:${HOME}/install/bin
export GOROOT_BOOTSTRAP=${HOME}/go

can run ./make.bash to produce a go binary.

thanks for your help, I learned a lot in this long process.

mike

**Comment by davecheney** [comment]
You don't need anything but GOROOT_BOOTSTRAP and LD_LIBRARY_PATH.

**Comment by h4ck3rm1k3** [comment]
The go cmd does not find my compiler.  I do not have root and it is not installed. Without the PATH I get this :
```
builddist.sh: line 4: gccgo: command not found
```
Without setting the GCCGO, I get 
```
run: /home/h4ck3rm1k3/go/pkg/bootstrap /home/h4ck3rm1k3/go/bin/go install bootstrap/...
go build bootstrap/internal/gc/big: : fork/exec : no such file or directory
```

I added a -n build to the dist too and that  show this : 
```
cd /home/h4ck3rm1k3/go/pkg/bootstrap/src/bootstrap/old9a
"" -I $WORK -I /home/h4ck3rm1k3/go/pkg/bootstrap/pkg/gccgo_linux_ppc64le -c -g -fgo-relative-import-path=_/home/h4ck3rm1k3/go\
/pkg/bootstrap/src/bootstrap/old9a -o $WORK/bootstrap/old9a/_obj/_go_.o ./lex.go ./y.go
ar cru $WORK/bootstrap/libold9a.a $WORK/bootstrap/old9a/_obj/_go_.o
```
It does not find the compiler. 

So the flags that I absolutly need for my building of gccgo from source and installing it in my homedir are :
```
export GCCGO=${HOME}/install/bin/gccgo
export LD_LIBRARY_PATH=${HOME}/install/lib64
export PATH=${PATH}:${HOME}/go/bin:${HOME}/install/bin
export GOROOT_BOOTSTRAP=${HOME}/go
```

BTW, If I run the compilation again with the new go, I get :
```
go tool: no such tool "9g"
```

**Comment by davecheney** [comment]
What is builddist.sh, is it part of Go.

I think the issue you are having is unrelated to this bug.

**Comment by h4ck3rm1k3** [comment]
The builddist.sh is my script, oh i see. Let me checkout the master branch again. 
On origin/master 47515e01167268ca2b844e9b13cd47f7c2a613d8

```
export LD_LIBRARY_PATH=${HOME}/install/lib64
export PATH=${PATH}:${HOME}/go/bin:${HOME}/install/bin
export GOROOT_BOOTSTRAP=${HOME}/go
```

bash make.bash 
```
##### Building Go bootstrap tool.
cmd/dist
# cmd/dist
fork/exec /usr/local/bin/gcc: no such file or directory
```

The compiler is not installed in usr/local/bin that is why i needed to compile dist with my script

my builddist script is just the output from the go build command cleaned up.
https://github.com/h4ck3rm1k3/go/blob/bootstrap-v2/src/builddist.sh

**Comment by davecheney** [comment]
Your GOROOT_BOOTSTRAP is wrong, it should point to the same value as  your passed to gcc's ./configure --prefix

**Comment by h4ck3rm1k3** [comment]
I have the same problem there.
```
+ export GOROOT=/home/h4ck3rm1k3/go
+ GOROOT=/home/h4ck3rm1k3/go
+ GOROOT_BOOTSTRAP=/home/h4ck3rm1k3/install
+ '[' '!' -x /home/h4ck3rm1k3/install/bin/go ']'
+ rm -f cmd/dist/dist
+ GOROOT=/home/h4ck3rm1k3/install
+ GOOS=
+ GOARCH=
+ /home/h4ck3rm1k3/install/bin/go build -o cmd/dist/dist ./cmd/dist
# _/home/h4ck3rm1k3/go/src/cmd/dist
fork/exec /usr/local/bin/gcc: no such file or directory
```
I am going to try and rebuild the compiler cleanly again.

**Comment by minux** [comment]
Perhaps you didn't set the correct --prefix when configuring gccgo.

**Comment by h4ck3rm1k3** [comment]
It was a problem with the prefix, yes, I thought I fixed it but did not clean the previous build correctly. 

    cd build
    ../configure --prefix=/home/h4ck3rm1k3/install/ --enable-languages=go

and then the bootstrap build works out of the box.

this works! thank you everyone for your patience in helping me learn this amazing new system.

mike
