### ISSUE TITLE
crypto/tls: server accepts RC4 by default

### ISSUE THREAD

**Issue by anacrolix** [golang/go#10094]
An SSL scan of my Go server with TLS enabled reports

```This server accepts the RC4 cipher, which is weak. Grade capped to B.```

I wonder if perhaps this one shouldn't be in the default set of cipher suites?

**Comment by minux** [comment]
Last time I checked, RC4 is still included in server cipher suite
of nearly all major websites.

**Comment by titanous** [comment]
RC4 is prohibited by [RFC 7465](https://tools.ietf.org/html/rfc7465) and should not be used.

**Comment by adg** [comment]
cc @agl

**Comment by agl** [comment]
https://go-review.googlesource.com/#/c/7647

**Comment by anacrolix** [comment]
Cheers!
