### ISSUE TITLE
x/mobile/audio: free resources and unload the external libraries on destroy

### ISSUE THREAD

**Issue by rakyll** [golang/go#10099]
The audio package should be able to free dlclose to unload the OpenAL library on Android when application is about to be destroyed.

On other platforms, it should free the virtual device and the created source and buffers.

Since there are no "shutdown" hooks we can listen on the desktop environments, we may provide a package level Destroy function to do the cleaning.

**Comment by nightlyone** [comment]
Does OpenAL use `__attribute__((destructor)` functions? If not every resource used by the process is destroyed on process teardown anyway.

Could you elaborate on the reasons to do it more cleanly?

**Comment by rakyll** [comment]
A disclaimer first: this is an experiment.

We have little changes of unloading OpenAL without crashing the process. My justification for this experiment is the lifecycle of the native code in an Android app. Android never destroys the running apps unless it requires more resources (CPU, memory, etc). It has a lightweight footprint if your application doesn't contain any external native dependencies. 

The case for native code is different. It's been loaded once on launch and unloaded iff Android destroys the app. We need to measure OpenAL's impact on the battery life before devoting any time to this issue.

**Comment by nightlyone** [comment]
Thank you for making the use case much clearer!

**Comment by rakyll** [comment]
Closing, because unloading is not necessary and we're likely to crash the process if we try.
