### ISSUE TITLE
Golang debian package installed by apt-get

### ISSUE THREAD

**Issue by krngrvr09** [golang/go#10095]
Golang debian package installed by ``sudo apt-get install golang`` installes version 1.1.2, whereas the current version is 1.4.2.

Can anybody confirm this, and if it is really the case can you please update the repository?

thanks.

**Comment by ianlancetaylor** [comment]
We don't have any control over the Debian repositories.  You need to bring this up with the Debian maintainers.

Also I think it matters which version of Debian you are using.  You didn't mention that.

**Comment by ALTree** [comment]
Jessie (testing)  has 1.3.3 and it's currently frozen, so even if you wait for the next Stable release you'll get 1.3. Not even Sid (unstable) has 1.4 at the moment. 

You can get the latest binary on golang.org, it works just fine on debian.

**Comment by alecthegeek** [comment]
If you want to automate the process of installing from the tar balls here is a fragment of script I originally wrote for the Raspberry Pi. Just use the appropriate URL to get the correct tarball.

 wget -O - https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | sudo tar -xzC /usr/local -f -

  echo '# Setup for golang' |sudo tee /etc/profile.d/golang.sh
  echo 'PATH=$PATH:/usr/local/go/bin'|sudo tee -a /etc/profile.d/golang.sh

  source /etc/profile.d/golang.sh

We  could really do with a tarball called 'latest' so it does not need to be changed.

**Comment by nightlyone** [comment]
An inoffical ubuntu package (so called PPA) is at https://launchpad.net/~evarlast/+archive/ubuntu/golang1.4

Currently debian sid is frozen, so nothing can be added there either.
If you want to follow the progress, watch https://tracker.debian.org/pkg/golang

**Comment by PistachioPony** [comment]
I wrote this gist for beginners to help them put golang from the binary distribution onto their AWS EC2 
https://gist.github.com/PistachioPony/06c3ca4a3310b8f46596

**Comment by davecheney** [comment]
Please do not comment on closed issues. If there is a bug, raise a new issue, otherwise, please use the golang-nuts mailing list.

**Comment by PistachioPony** [comment]
Oh I'm sorry, since I landed on that page looking for answers I thought it
would help someone to have a link to what helped me!

Apologies,
Maria
