### ISSUE TITLE
runtime: hashmap fatal error: evacuation not done in time

### ISSUE THREAD

**Issue by blackbeans** [golang/go#10101]
goversion:  go1.4.2 linux/amd64
my benchmark  crashes with below fatal error ,is this a bug ?

fatal error: evacuation not done in time

goroutine 299 [running]:
runtime.throw(0xa67392)
	/usr/lib/golang/src/pkg/runtime/panic.c:520 +0x69 fp=0x7fae386eaac0 sp=0x7fae386eaaa8
hash_grow(0x701f00, 0xc20800f380)
	/usr/lib/golang/src/pkg/runtime/hashmap.goc:333 +0x3a fp=0x7fae386eaaf0 sp=0x7fae386eaac0
hash_insert(0x701f00, 0xc20800f380, 0x7fae386eabfc, 0x7fae386eac08)
	/usr/lib/golang/src/pkg/runtime/hashmap.goc:534 +0x3cd fp=0x7fae386eab88 sp=0x7fae386eaaf0
runtime.mapassign1(0x701f00, 0xc20800f380, 0x7fae386eabfc, 0x7fae386eac08)
	/usr/lib/golang/src/pkg/runtime/hashmap.goc:933 +0x46 fp=0x7fae386eabb8 sp=0x7fae386eab88
kiteq/remoting/client.(*RemotingClient).Write(0xc2082a4540, 0x11000007cd, 0xc209c21680, 0x252, 0x280, 0x0, 0x0, 0x0, 0x0)
	/home/zc/go-proj/src/kiteq/remoting/client/remoting_client.go:206 +0x127 fp=0x7fae386eac28 sp=0x7fae386eabb8

code at  line 206  : 
<code>
func (self *RemotingClient) Write(packet protocol.Packet) (chan interface{}, error) {

	tid, future := self.fillOpaque(&packet)
	self.lock.Lock()
	defer self.lock.Unlock()

        delete(holder, tid)

  206:  holder[tid] = future
	return future, self.remoteSession.Write(packet)
}
</code>

**Comment by minux** [comment]
Please try again with the latest version of Go 1.4.2.

**Comment by minux** [comment]
Note: although you might think you're using 1.4.2, the
stack trace is showing frames from runtime/hashmap.goc,
which doesn't exist in Go 1.4.x.

Also, Go 1.4 doesn't has pkg directory anymore.

**Comment by blackbeans** [comment]
thx ,i clean my project ,and try rebuild it

**Comment by rsc** [comment]
Assuming this went away when you started using Go 1.4.
