### ISSUE TITLE
Select on closed channels -> MAJOR delay

### ISSUE THREAD

**Issue by Matthias-Schwarz** [golang/go#10103]
go version go1.4.1 linux/amd64
    (Debian)

When a select statement contains multiple channels and one of them is closed, it takes around 40ms per select on my machine (up from instantaneous on open channel).

Code sample:
http://play.golang.org/p/bMzpu2achx
The example works fine, until you uncomment the line close(test).
Then it fails with "process took too long, Program exited."

    t := time.Now()
    test := make(chan string)
    //close(test)	//UNCOMMENT FOR FAILURE
    i := 0
	for {
		select {
		case <-test:
		case <-ticker.C:
		fmt.Println(i, ": ", time.Since(t))
		t = time.Now()
		i++
		if(i == 10){
			return
		}
		}
	}

**Comment by bradfitz** [comment]
You're spinning. A closed channel is always available for read so its case in select is always readable.
