### ISSUE TITLE
runtime/cgo: cgo is broken on freebsd/arm

### ISSUE THREAD

**Issue by davecheney** [golang/go#10119]
```
root@pandaboard:~/go/src # ../bin/go env
ld-elf.so.1: assert failed: /usr/src/libexec/rtld-elf/rtld_lock.c:233
^C^C^C^C^C^C^Z
Abort (core dumped)
```

**Comment by ianlancetaylor** [comment]
Anybody have an SSH-accessible FreeBSD ARM system, or simple directions for how to run one in an emulator?

**Comment by rsc** [comment]
Dave got me access to one. I confirmed that cgo still breaks at tip. Trying to git bisect it to narrow down. ARM systems are so slow that even O(log n) takes a long time.
