### ISSUE TITLE
x/review/git-codereview: can't update CL

### ISSUE THREAD

**Issue by 4ad** [golang/go#10115]
```
: iridium:objdump; git10
deaff58 cmd/objdump: disable TestDisasm.* on arm64 (Aram Hăvărneanu)
83de6fb os/signal, hash/crc32: add arm64 build tags (Aram Hăvărneanu)
5062413 test: fix nosplit test, and disable nilptr3 test on arm64 (Aram Hăvărneanu)
a1c7606 reflect: add support for GOARCH=arm64 (Aram Hăvărneanu)
7acac93 sync/atomic: add support for GOARCH=arm64 (Aram Hăvărneanu)
aebe012 math, math/big: add support for GOARCH=arm64 (Aram Hăvărneanu)
4430bdf syscall: add support for GOARCH=arm64 (Aram Hăvărneanu)
aaf583c runtime: add support for GOARCH=arm64 (Aram Hăvărneanu)
16a950a cmd/dist: add suport for GOARCH=arm64 (Aram Hăvărneanu)
b974414 cmd/cgo: add support for GOARCH=arm64 (Aram Hăvărneanu)
: iridium:objdump; git mail deaff58
[...]          
remote: (W) No changes between prior commit ffcc30e and new commit 4430bdf        
To https://go.googlesource.com/go
 ! [remote rejected] HEAD -> refs/for/master (no changes made)
error: failed to push some refs to 'https://go.googlesource.com/go'
(running: git push -q origin HEAD:refs/for/master)
git-codereview: exit status 1
: iridium:objdump; 
```

Except that the error message is not true, the current code _is not_ the one in gerrit. Gerrit CL is stale and I can't update.

**Comment by minux** [comment]
it seems that git-codereview push each commit separately?
have you tried to bypass git-codereview and push directly?

git push origin HEAD:refs/for/master

should update the CLs.

**Comment by 4ad** [comment]
Yes, I tried to bypass it, same error.

	iridium:go$ git push origin HEAD:refs/for/master
	Counting objects: 71, done.
	Delta compression using up to 4 threads.
	Compressing objects: 100% (23/23), done.
	Writing objects: 100% (23/23), 2.76 KiB | 0 bytes/s, done.
	Total 23 (delta 15), reused 0 (delta 0)
	remote: Resolving deltas: 100% (15/15)
	remote: Processing changes: refs: 1, done    
	remote: (W) No changes between prior commit ffcc30e and new commit 4430bdf
	To https://go.googlesource.com/go
	 ! [remote rejected] HEAD -> refs/for/master (no changes made)
	error: failed to push some refs to 'https://go.googlesource.com/go'
	iridium:go$

**Comment by minux** [comment]
Is your branch available somewhere? I want to take a look.

**Comment by 4ad** [comment]
https://github.com/4ad/go/tree/merge.arm64

**Comment by ysmolsky** [comment]
That branch is  not accessible anymore. Thus it cannot be reproduced anymore. @4ad feel free to reopen if this is still relevant for you.
