### ISSUE TITLE
build: darwin/arm64 port

### ISSUE THREAD

**Issue by minux** [golang/go#10116]
The port (https://github.com/minux/goios/tree/ios64) is fully working,
but the code is based on an older version of the linux/arm64 port.

I will upstream the port after linux/arm64 port is in and #10107 is fixed.

@crawshaw, we will need to setup a builder for it too.

**Comment by crawshaw** [comment]
I'll get a builder running today.

**Comment by crawshaw** [comment]
A darwin/arm64 builder is on my desk. It's currently sharing hardware with the darwin/arm builder, but I hope to resolve that this week. (Our collection of Mac Minis is on the way.)
