### ISSUE TITLE
net/http: Custom Error handlers

### ISSUE THREAD

**Issue by mattfarina** [golang/go#10123]
In the `http` package `Error` displays just an error message. When building a web application you will often want to have style error pages matching the site or application. In order to get this with Go you need to implement your own `Error` handling along with any code that calls it.

For example, if you want custom error pages (including 404 not found pages) and want to serve files you need to bypass the built in file server and re-implement much of it to change the error page handling.

It would be far simpler to allow the `Error` to provide a default but be capable of being replaced.

**Comment by adg** [comment]
It's hard to get excited about this.

Something like this?
```
var ErrorHandler func(w http.ResponseWriter, error string, code int) = func(w ResponseWriter, error string, code int) {
    w.Header().Set("Content-Type", "text/plain; charset=utf-8")
    w.WriteHeader(code)
    fmt.Fprintln(w, error)
}

func Error(w ResponseWriter, error string, code int) {
    ErrorHandleR(w, error, code)
}
```
Seems a bit gross TBH. I don't know that we want to add yet another hook.

**Comment by rsc** [comment]
It so easy to write your own functions.

**Comment by mattfarina** [comment]
@rsc how would one write an error handler for the not found case and use that in the built-in file server instead of the `NotFound` response? Something so I wouldn't need https://github.com/Masterminds/go-fileserver

**Comment by bradfitz** [comment]
Give `ServeContent` or whatever a `ResponseWriter` which intercepts the 404/403/500/etc and writes its own message.

**Comment by mattfarina** [comment]
@bradfitz that's an interesting take I had not thought of. It should work.

My issue with it is that it's not a good separation of concerns. It's a hack to work around this limitation. Something that's responsible with content now needs to look for certain types of responses and override the output to something custom.

It would be nice to have a clean solution.

**Comment by alecthomas** [comment]
There's also [this](https://golang.org/src/net/http/server.go?s=1893:2975#L1451) and [this](https://golang.org/src/net/http/server.go?s=1893:2975#L1437) that seem to bypass the `ResponseWriter` altogether.
