### ISSUE TITLE
time: Timer with zero Duration seems to have a moment of delay

### ISSUE THREAD

**Issue by binary132** [golang/go#10124]
http://play.golang.org/p/9saBM6ph-9

There seems to be a small delay incurred when Timer starts.  Note the "`sync`" workaround in `notBroken`.  This behavior was noticed on `go1.2.1 linux/amd64` and is repeatable on play.golang.org and `go1.4.1 linux/amd64`.

The following program outputs:

```text
This is the undesired behavior.

This is the desired select.
```

```go
package main

import "time"

func main() {
	broken()
	println()
	notBroken()
}

func broken() {
	t := time.NewTimer(0 * time.Second)

	select {
	case _ = <-t.C:
		println("This is the desired select.")
	default:
		println("This is the undesired behavior.")
	}
}

func notBroken() {
	t := time.NewTimer(0 * time.Second)

	sync := time.NewTimer(0 * time.Second)
	_ = <-sync.C

	select {
	case _ = <-t.C:
		println("This is the desired select.")
	default:
		println("This does not get selected.")
	}
}
```

**Comment by minux** [comment]
The behavior you expect is essentially a race between your select goroutine
and the timer goroutine.

Working as expected.

**Comment by dvyukov** [comment]
time package timers fire after "at least the duration d":
http://golang.org/pkg/time/#Sleep
We don't special case zero duration as it looks pointless.
