### ISSUE TITLE
x/tools/go/ssa: bad code generation for struct declaration and assignment

### ISSUE THREAD

**Issue by elliott5** [golang/go#10127]
Issue discovered in http://golang.org/src/compress/flate/inflate.go
when testing that package in https://github.com/tardisgo/tardisgo
using go version go1.4.2 darwin/amd64

Program demonstrating error: [reset.go](https://github.com/tardisgo/tardisgo-samples/blob/master/errors/reset/reset.go)

```
$ go run reset.go
good
good
good
$ ssadump -run reset.go
good
good
panic: runtime error: invalid memory address or nil pointer dereference
```

Offending code generated:
```
func (f *decompressor) ResetBad() { // abridged from the orginal version in the compress/flate package
	*f = decompressor{
		hist: f.hist,
	}
}

/* SSA:
# Name: (*main.decompressor).ResetBad
# Package: main
# Location: reset.go:60:24
# Locals:
#   0:	t0 decompressor
func (f *decompressor) ResetBad():
0:                                                                entry P:0 S:0
	t0 = local decompressor ()                                *decompressor
	t1 = *t0                                                   decompressor
	*f = t1
	t2 = &f.hist [#9]                                         **[32768]byte
	t3 = &f.hist [#9]                                         **[32768]byte
	t4 = *t3                                                   *[32768]byte
	*t2 = t4
	return
*/
```
The problem is that *f is overwritten and then used to fetch a field value.
Using a temporary variable in Go fixes the problem, see the ResetOK method.

**Comment by alandonovan** [comment]
Hi Elliot, thanks for reporting this bug.  I understand what's wrong.  The fix is rather involved so I may not get to it today.

**Comment by elliott5** [comment]
No problem Alan, thank you for looking at it so promptly.
 
I've programmed round that particular instance of the problem; and as the problem probably only occurs in a very unusual set of circumstances, while I wait for your fix I can look out for those circumstances if I hit an inexplicable error again. 

It's a tribute to the quality your SSA code that I've got 60+ standard library packages [passing their tests](https://github.com/tardisgo/tardisgo/blob/master/STDPKGSTATUS.md) so far and this is the first bug I've found.

**Comment by alandonovan** [comment]
Fix pending.
https://go-review.googlesource.com/#/c/7533/2
Let me know if patching it does not solve your problem.

**Comment by elliott5** [comment]
Thank you for fixing this so quickly Alan, the patch does solve my problem; both in the small test case and for tardisgo/haxe running the compress/flate tests.

**Comment by elliott5** [comment]
This issue is fixed in the revised x/tools/go/ssa so I'm closing the issue. Thank you again for dealing with it so quickly.
