### ISSUE TITLE
cmd/gc: error message regression when trying to "go" anything which is not a function call

### ISSUE THREAD

**Issue by johto** [golang/go#10121]
For example:

```
package main

func main() {
	c := make(chan int)
	go func() {
		select {
			case foo := <-c:
				bar := 1
		}
	}
}
```

Produces `./foo.go:10: syntax error near 1` when built using commit 9f9d66d3b66d1d23fd5578f30b2fa084e4f83902.  1.4.2 correctly reports `./foo.go:10: syntax error: argument to go/defer must be function call`.

**Comment by mwhudson** [comment]
I think this is #9968

**Comment by minux** [comment]
yes.
