### ISSUE TITLE
main(.text):*****: not defined error then link lib in windows

### ISSUE THREAD

**Issue by Loafter** [golang/go#10128]
# "main(.text):*****: not defined" error then link lib in windows
i use this config
go version go1.4.2 windows/amd64

GOROOT=c:\go
#GOBIN=
GOARCH=amd64
GOOS=windows
GO_ENABLED=1
PATH=C:\mingw64\bin;%GOROOT%\bin;%PATH%;
LITEIDE_GDB=gdb64
LITEIDE_MAKE=mingw32-make
LITEIDE_TERM=%COMSPEC%
LITEIDE_TERMARGS=
LITEIDE_EXEC=%COMSPEC%
LITEIDE_EXECOPT=/C

the i try compile and use this cgo dirrective 

// #cgo CPPFLAGS: -I"C:/GDCM/include/gdcm-2.4"
// #cgo LDFLAGS: -L"C:/GDCM/lib" -lgdcmgetopt -lgdcmcharls -lgdcmMSFF -lgdcmMEXD -lsocketxx -lgdcmMSFF -lgdcmjpeg8 -lgdcmjpeg12 -lgdcmjpeg16 -lgdcmopenjpeg -lgdcmDICT -lgdcmIOD -lgdcmexpat -lgdcmDSED -lgdcmCommon -lgdcmzlib -lWs2_32
// #include "gdcmgobr.h"

i'v get this error:
.....
main(.text): _ZN4gdcm6System18GetLastSystemErrorEv: not defined
main(.text): _ZN4gdcm5Trace14GetDebugStreamEv: not defined
main(.text): undefined: _ZN4gdcm25CompositeNetworkFunctions5CEchoEPKctS2_S2_
main(.text): undefined: _ZNK4gdcm7DataSet8GetDEEndEv
.....
how to fix this??

**Comment by slimsag** [comment]
Probably related: #4069

**Comment by minux** [comment]
fixing #4069 should fix this.
