### ISSUE TITLE
cmd/go: make get send fallback http request earlier than the 30s it takes for https to time out

### ISSUE THREAD

**Issue by cespare** [golang/go#10120]
Right now `go get` makes a meta tag request using https first; if this hangs forever, the request times out after 30 seconds before trying the http fallback.

This means that a package served from a vanity domain where https requests are dropped can take a long time to install. See this golang-nuts thread for more context:

https://groups.google.com/d/msg/golang-nuts/ixF0h1YYCoQ/9wfBu4deaM0J

@dsymonds suggests that `go get` could kick off the http fallback request after 5s instead of waiting for the full 30s timeout.

**Comment by adg** [comment]
Related to #9637

**Comment by rsc** [comment]
It will be https only in Go 1.5, so this is obsolete.
