### ISSUE TITLE
path/filepath: need to document that Clean replaces each slash with filepath.Separator.

### ISSUE THREAD

**Issue by hyangah** [golang/go#10122]
The current implementation of filepath.Clean calls filepath.FromSlash at the end. As a result, 
filepath.Join("a", "b/c") in Windows returns `a\b\c`, which is a bit surprising. 
Can I rely on this behavior of Clean? If so, we need to mention it in documentation.

**Comment by minux** [comment]
I think that's implicit because it's path/filepath.Clean, not path.Clean,
so the path will be using the canonical path separator of the platform.

**Comment by hyangah** [comment]
So I assume this is the intended behavior that will not change in the future.
Obviously three of us got confused (https://go-review.googlesource.com/7161) and I'd like this to be  mentioned explicitly.

**Comment by minux** [comment]
Adding explicit docs SGTM.

Or we can add some docs in the package docs. Right now it just says
"Package filepath implements utility routines for manipulating filename
paths in a way compatible with the target operating system-defined file
paths."

Perhaps we should expand on that, and say that all result returned will
contain OS-specific path separator no matter what the input uses on
platforms that accepts both '/' and '\\'.

**Comment by alexbrainman** [comment]
I have no objection to extra documentation. Not sure about others. I suggest you send a change with whatever words you think appropriate, and we'll see what happens. Thank you.

Alex

**Comment by adg** [comment]
Yup definitely needs docs
