### ISSUE TITLE
encoding/json: Better Json decoding

### ISSUE THREAD

**Issue by h4ck3rm1k3** [golang/go#10134]
I have made a patch for debugging two things:
1. if a field could not get mapped into the object
2. if the type could not get cast, what field name it is. this required more pumbing to route the key field name to the right spot. 
https://github.com/h4ck3rm1k3/google-go/commit/3befeea4f59745624af7ae18d1119ee175871df2

**Comment by mikioh** [comment]
Please take a look at http://golang.org/doc/contribute.html.

**Comment by h4ck3rm1k3** [comment]
roger that. will do a review, but need time for that.

**Comment by minux** [comment]
Please remember to discuss new features first, before sending the review.

**Comment by ianlancetaylor** [comment]
Nothing to do here, so closing the issue.  If you want to make a specific feature request, I think that would be clearer if you open a new issue.

**Comment by davecheney** [comment]
I am sorry but we cannot accept pull requests.

Please read http://golang.org/doc/contribute.html for instructions on how
to propose a change.

**Comment by h4ck3rm1k3** [comment]
There is something to do. @ianlancetaylor the bug report is : 
1. field name not reported on type error, this is really time consuming to find out what field is failing.
2. no error message of skipped fields. 
those are the things that I tried to fix. So I would like to leave this a bug report if you agree.

**Comment by h4ck3rm1k3** [comment]
>> Please remember to discuss new features first, before sending the review.
I sent this item to the mailing list and this is the discussion. The
problem is that json decode is lacking any useful feedback in an error
condition.

On Wed, Mar 11, 2015 at 8:41 AM, Minux Ma <notifications@github.com> wrote:

> Please remember to discuss new features first, before sending the review.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/10134#issuecomment-78264259>.
>



-- 
James Michael DuPont
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by ianlancetaylor** [comment]
@h4ck3rm1k3 Please open a new issue describing the actual problem.  Thanks.
