### ISSUE TITLE
doc: Contribution guidelines should specify git origin

### ISSUE THREAD

**Issue by anacrolix** [golang/go#10130]
The contribution guidelines don't mention that git origin should be https://go.googlesource.com/go.

git-codereview: git origin must be a Gerrit host, not GitHub: https://github.com/golang/go.git

**Comment by parkr** [comment]
That's because that document assumes (and states so) that you have followed the installation instructions here: https://golang.org/doc/install/source

**Comment by adg** [comment]
I'm loath to add more instructions to a page that people already complain is too verbose.
