### ISSUE TITLE
runtime: deadly signal received on foreign threads does not crash the process

### ISSUE THREAD

**Issue by minux** [golang/go#10139]
Instead, our sigtramp will simply return without modifying the ucontext, and
then the faulty code will trigger the same fault again, .....

http://play.golang.org/p/L1WXDwUFTf
```
package main
/*
#include <signal.h>
#include <pthread.h>
#include <stdio.h>

static void *thread1(void *p) {
        (void)p;
        printf("0\n");
        int *q = NULL;
        printf("1\n");
        printf("*nil=%d\n", *q);
        return NULL;
}
void test5337() {
        setbuf(stdout, NULL);
        pthread_t tid;
        pthread_create(&tid, 0, thread1, NULL);
        //pthread_join(tid, 0);
        printf("2\n");
}
*/
import "C"
import "time"

func main() {
        C.test5337()
        time.Sleep(5 * time.Second)
        println("DONE")
}
```

If you run the program, I'd expect to see something like SIGSEGV received
on foreign thread, and then the process should exit (crash).

However, what you will actually see is that the process will print DONE
after 5 seconds and exit normally. But if you run the program under gdb,
you will see that thread is triggering SIGSEGV again and again.

**Comment by rsc** [comment]
Looks like maybe we just need to handle SIG_DFL either in sigfwd or before calling sigfwd.
