### ISSUE TITLE
range & go: pass a pointer to an element of array leads to a different behavior with/out go

### ISSUE THREAD

**Issue by noxiouz** [golang/go#10132]
I met a strange behavior while passing elements of array by pointer to a function. It looks like a bug.
You can find example here:
http://play.golang.org/p/e0dDpyCYCG
```go
package main

import (
	"fmt"
	"sync"
)

var wg sync.WaitGroup

type Item struct {
	name string
}

func (i *Item) Name() string {
	defer wg.Done()
	return i.name
}

func Go(t *Item) {
	fmt.Println(t.Name())
}

func main() {
	f := make([]Item, 0)
	f = append(f, Item{"1"})
	f = append(f, Item{"2"})
	f = append(f, Item{"3"})
	for _, v := range f {
		wg.Add(1)
		go Go(&v)
	}
	wg.Wait()
```
This example prints 
```
3
3
3
```
It doesn't look like an expected behavior.
Moreover this example (http://play.golang.org/p/KY4jEgtgGn) (exactly the same, but without ```go```)
```go
package main

import (
	"fmt"
	"sync"
)

var wg sync.WaitGroup

type Item struct {
	name string
}

func (i *Item) Name() string {
	defer wg.Done()
	return i.name
}

func Go(t *Item) {
	fmt.Println(t.Name())
}

func main() {
	f := make([]Item, 0)
	f = append(f, Item{"1"})
	f = append(f, Item{"2"})
	f = append(f, Item{"3"})
	for _, v := range f {
		wg.Add(1)
		Go(&v)
	}
	wg.Wait()
}

```
prints
```
1
2
3
```
I checked it on *1.3.3*, *1.4.1*, *1.4.2*

**Comment by minux** [comment]
http://golang.org/doc/faq#closures_and_goroutines

**Comment by dvyukov** [comment]
Run the program with race detector (go build/test/run -race)

**Comment by noxiouz** [comment]
What a shame =) Sorry for that. Thanks!

**Comment by FrankReh** [comment]
You are passing an address to a variable to a goroutine but you let the
value at that address change before the goroutines are potentially run.

The idiomatic way of getting the behavior you want is to create a local
variable within the loop, set it equal to your 'v', and then pass the
address of _that_ local.  You will get a new local allocated from the heap
in each iteration this way, and you should get the 1,2,3 output.
