### ISSUE TITLE
image/jpeg: Unable to decode valid JPEG image

### ISSUE THREAD

**Issue by pranavraja** [golang/go#10133]
`go version go1.4 darwin/amd64`

Attempted to use `image.Decode` on the below image:

![attached image](https://cloud.githubusercontent.com/assets/1480813/6595540/69cdfa12-c83f-11e4-9b2b-cc2a093bf79a.jpg)

Expected the image to decode successfully (it displays in a browser)

Actual result:
`unsupported JPEG feature: luma/chroma downsample ratio`

**Comment by minux** [comment]
has been fixed at tip.
