### ISSUE TITLE
Please provided deb package or apt repository for ubuntu/debian

### ISSUE THREAD

**Issue by netroby** [golang/go#10146]
Please provided deb package or apt repository for ubuntu/debian
It will help us from download golang use our hands.

**Comment by adg** [comment]
It's up to the distro maintainers or volunteers to provide such packages.

For a solution, try godeb: http://blog.labix.org/2013/06/15/in-flight-deb-packages-of-go

**Comment by netroby** [comment]
Do you know oracle provide deb/rpm package and repository for users. because it really helpful to us.

**Comment by netroby** [comment]
Be friendly with users, then users love you. Do you want more and more user using golang?

**Comment by adg** [comment]
Installation on Linux is this simple:
```
$ wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
$ sudo tar -C /usr/local -xzf go1.4.2.linux-amd64.tar.gz
```
(And add `/usr/local/go` to your `PATH` and set `GOPATH`.)

Installing Java is more complicated.

**Comment by adg** [comment]
If we had the resources to produce packages for Debian and Ubuntu we would, but we don't. Even a Canonical (the people behind Ubuntu) employee found it difficult to maintain such packages.

**Comment by netroby** [comment]
Thanks.
1. thanks you provided us the way to easier install golang. 
2. sorry to hear that you have no enough resources to do that
3. would you please put this guide on your download document or page. it will help us to get things done

**Comment by minux** [comment]
It's in the docs. https://golang.org/doc/install

**Comment by adg** [comment]
It's definitely true that our download and installation pages could be
better integrated. I'm working on a fix for this.

**Comment by adg** [comment]
See issue #10147
