### ISSUE TITLE
I found a fatal panic of golang

### ISSUE THREAD

**Issue by needkane** [golang/go#10145]
I found a fatal panic of golang,but i don't know how to contribute my code
The official document  so bad.
git clone https://go.googlesource.com/image
But i can't found document(jpeg),in go source code pkg/image/jpeg  is exis

**Comment by ianlancetaylor** [comment]
If you want us to fix something, you need to tell us precisely what you did, precisely what happened, and what you expected to happen instead.

**Comment by minux** [comment]
@needkane if you prefer to use Chinese, you can ask on the golang-china
mailing list. https://groups.google.com/forum/#!aboutgroup/golang-china
golang-china@googlegroups.com.

If what you found is indeed a bug in Go, I can help you file a proper issue.

**Comment by mikioh** [comment]
Perhaps, you need to run `git clone https://go.googlesource.com/go' instead.  The URL https://go.googlesource.com/image designates the supplementary image libraries, and it doesn't contain jpeg package.

**Comment by mikioh** [comment]
Merged into #10154.
