### ISSUE TITLE
go/types: don't skip checking of RangeStmt.Body because of errors in loop vars

### ISSUE THREAD

**Issue by alandonovan** [golang/go#10148]
Type checking doesn't enter the body of the third loop because the range operand has the wrong type and the var y was declared with := not assigned with =.  It should probably try harder; e.g., declare the variable y with type Invalid.  (See also Google internal bug #19639588.)

package main

func main() {
        for y := range "" {
                _ = "" + 1  // type error => body was type-checked
        }
        for range 1 {
                _ = "" + 1 // type error => body was type-checked
        }
        for y := range 1 {
                _ = "" + 1       // no type error => body not type-checked
        }
}

**Comment by griesemer** [comment]
This issue was closed by https://github.com/golang/tools/commit/e4a1c78f0f69fbde8bb74f5e9f4adb037a68d753 .
