### ISSUE TITLE
x/tools/go/vcs: package could provide an id of current working index

### ISSUE THREAD

**Issue by krnowak** [golang/go#10159]
Something like:

``` golang
rr, _ := vcs.RepoRootForImportPath("github.com/golang/go", false)
fmt.Println("Current working change id:", rr.Cmd.GetId())
```

The `GetId()` function prototype could be `func (v *Cmd) GetId() (string, error)` and getting an id means:
1. `git` - `git rev-parse HEAD`
2. `hg` - `hg id -i`
3. `bzr` - `bzr revno`
4. `svn` - `svnversion`

The subversion here is an odd man out, which might be troublesome as the code in `vcs` package assumes that a command stored in `Cmd` member can provide all info.

My use case is creating container images from given project, so the created image could have a vcs info in its (JSON) metadata, for example `git: 66199afb25487fd75bf870c72bc3cea33d95f89e`

**Comment by dmitshur** [comment]
Thanks for the report. This package has been deprecated in #57051 and won't receive further development, so closing this as not planned.
