### ISSUE TITLE
cmd/dist: bootstrapping is sequential

### ISSUE THREAD

**Issue by 4ad** [golang/go#10157]
The "Building compilers and go_bootstrap" step is compiling packages sequentially (there is parallelism in running the assemblers over the .s files in a package, but packages are build one at a time). This is causing bootstrapping to be slow, especially on machines with large number of cores.

On my ARM64, which is an 8-core machine, the cmd/dist step takes *5 times* longer than `go install std cmd`.

**Comment by rsc** [comment]
Simplicity wins here, I'm afraid.
From what you've described, go install std cmd is very fast.
That doesn't make cmd/dist too slow.
