### ISSUE TITLE
missing description for content in side download package

### ISSUE THREAD

**Issue by shrimpywu** [golang/go#10160]
the package we download, e.g https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz

contains several folder and files. some of the are very self describable, e.g "test", "src", "doc"
but some folder are kind of not sure what it does, e.g "include", "lib", "misc", "api"  

will be good in the read me file, add another section to describe what each folder do and why we need them.

**Comment by minux** [comment]
all those directories are pretty standard, except perhaps api, which lists
api additions for each go major version, and is used to make sure no
api changes ever occur.

**Comment by davecheney** [comment]
I just checked and the api directory contains a README file which explains
its purpose.

https://github.com/golang/go/blob/master/api/README

**Comment by minux** [comment]
Yeah, and include and lib/time also includes a README.
misc doesn't, but that's just a miscellaneous directory and
hardly need explanation.

**Comment by shrimpywu** [comment]
thanks for everyone`s reply, i am trying to find out what are the minimum set of file for go environment. most of the folder does self exlained themself, but folder like "lib" and "include" still confused me, see blow:

- .git
for git repo, self explained

- api
[README](https://github.com/golang/go/blob/master/api/README) says it is data for API checker, does it mean is for testing? why not under test folder?

- bin
  go binary, where go.exe are, self explained

- blog
article for Go Blog? not related to code i believe!?

- doc
documentation folder, self explained

- include
README says it is for GC, so i believe it is important, must keep

- lib
there is a "time" folder under it, by itself it is data for timezone, so does go depends on it in runtime?

- misc
i believe it is not contains any code that go would depends in runtime ?

- src
self explained

- test
self explained

**Comment by minux** [comment]
On Fri, Mar 13, 2015 at 6:07 PM, shrimpywu <notifications@github.com> wrote:

> thanks for everyone`s reply, i am trying to find out what are the minimum
> set of file for go environment. most of the folder does self exlained
> themself, but folder like "lib" and "include" still confused me, see blow:
>
If you want a minimum go distribution, take a look at
https://github.com/adg/gostrip

lib/time is needed on windows, plan9 and testing the time package.
lib/codereivew is not needed, this is gone starting from Go 1.5.

include is only needed if you need to rebuild the C part of the Go
toolchain, and
this directory is gone starting from Go 1.5.

**Comment by shrimpywu** [comment]
ah thank you for introduce "gostrip" to me and the explanation. 
i am able to execut "gostrip", but confused by the output. maybe a question to @adg ?

there is no bin folder anymore
from [installation instruction](https://golang.org/doc/install), i will need to have a "GOROOT" environment variable and add "$GOROOT/bin" to path. 


```
gostrip>go build main.go
gostrip>main.exe go1.4.2
Cloning into 'go1.4.2'...
remote: Sending approximately 61.82 MiB ...
remote: Counting objects: 6285, done
remote: Finding sources: 100% (1267/1267)
remote: Total 203078 (delta 167112), reused 202852 (delta 167112)
Receiving objects: 100% (203078/203078), 59.90 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (167490/167490), done.
Checking connectivity... done.
Checking out files: 100% (4454/4454), done.
building go: fork/exec ./make.bash: %1 is not a valid Win32 application.
```

![image](https://cloud.githubusercontent.com/assets/10192626/6648587/e94c4294-c998-11e4-989c-b03b3766707e.png)

**Comment by shrimpywu** [comment]
i removed my previous comment, 
seems like gostrip is only work on linux environment,

since i am seeing below error when running it. 
@adg , is there any build file for windows environment?

- building go: fork/exec ./make.bash: %1 is not a valid Win32 application.

**Comment by davecheney** [comment]
make.bat

**Comment by shrimpywu** [comment]
thank you everyone for your kind help!

hit a few bumps but finally have gostrip working for me:

- take me a few minutes to realize i need to update "/" to be "\\" in windows
- somehow "gostrip" not able to remove".git" folder, need to remove it from code and manually delete it

new to Go, but i will try to send a PR to "gosstrip" to add platform awareness, so that the next guy to run it will be easier!
