### ISSUE TITLE
cmd/go: suggest add $GOPACKAGEPATH for generate

### ISSUE THREAD

**Issue by chai2010** [golang/go#10172]
Go generate sets several variables: $GOARCH/$GOOS/$GOFILE/$GOPACKAGE .

When we fork a gopkg, we need fix the old import path to current import path.
Like this: 

	//go:generate go run cmd/fixpath/fixpath.go -old=github.com/yuin/gopher-lua -new=github.com/chai2010/lua

Suggest add $GOPACKAGEPATH for import path.

https://github.com/chai2010/lua/blob/master/generate.go#L7

**Comment by adg** [comment]
What would `$GOPACKAGEPATH` be set to in your example?

Using a go generate rule to rewrite import paths seems pretty strange. Can you provide more context?

**Comment by chai2010** [comment]
When i fork a gopkg, like `github.com/yuin/gopher-lua`,
the origin gopkg's base import path is `github.com/yuin/gopher-lua`.

Some sub package (like `gopher-lua/ast`) still use `github.com/yuin/gopher-lua/ast` import path.
I can't build the new fork on new import path(on `github.com/chai2010/lua`).

I need to use `go run fixpath.go -old-path=github.com/yuin/gopher-lua -new-path=github.com/chai2010/lua`
to fix the import path.

When use the `go generate` to invoke the fixpath tool (to current import path),
i hope use $GOPACKAGEPATH instead of the `github.com/chai2010/lua`.

	//go:generate go run cmd/fixpath/fixpath.go -old=... -new=$GOPACKAGEPATH

**Comment by rsc** [comment]
@robpike

I'm not convinced this is a proper use of go generate, nor that we want to keep throwing in environment variables.

**Comment by robpike** [comment]
I agree with Russ. Closing.
