### ISSUE TITLE
runtime: garbage collector found invalid heap pointer *(0x1a737ea0+0x0)=0x30 s=nil

### ISSUE THREAD

**Issue by trygo** [golang/go#10175]
runtime: garbage collector found invalid heap pointer *(0x1a737ea0+0x0)=0x30 s=nil
runtime: found *(0x2edc55f0+0x8) = 0x1a737ea0+0x0

see #9872

**Comment by RLH** [comment]
Any chance you have the stacks? Was this one a 386 machine, or on Windows
perhaps?
Thanks in advance.

**Comment by trygo** [comment]
system is windows 7,  go is  1.4.2

**Comment by RLH** [comment]
Thanks, I'll assume this is a 64 bit machine so we can rule out
https://github.com/golang/go/issues/9872. The GC is seeing the value 0x30
that it has been told is a pointer and it is not.  This could well be
related to  https://github.com/golang/go/issues/9125 in which case could
you make sure that the 0x30 is not being returned from Windows and
incorrectly typed as a pointer.

**Comment by rsc** [comment]
Can you make this happen again?
We need the full stack trace for the garbage collector reporting the crash in order to make any progress at all here. Ideally I'd like to see the stacks of all the goroutines in the dump.

If you can get that information, please file a new bug. Thanks.
