### ISSUE TITLE
go/build: custom import path checking convention not documented

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#10177]
The Go custom import path checking convention [1, 2] does
not seem to be documented anywhere in the standard docs.

Perhaps go/build is a reasonable place to document this, being
the definitive place where the other comment-based conventions
are documented AFAIK.

[1] https://golang.org/doc/go1.4#canonicalimports
[2] https://docs.google.com/document/d/1jVFkZTcYbNLaTxXD9OcGfn7vYv5hWtPx9--lTx1gPMs

**Comment by minux** [comment]
It's documented in http://golang.org/cmd/go/#hdr-Import_path_checking

**Comment by rogpeppe** [comment]
Thanks! Perhaps it could be documented in go/build as well. What do you think?

**Comment by minux** [comment]
It's briefly mentioned in http://golang.org/pkg/go/build/#ImportMode,
what do your propose to add more docs for this feature in go/build?

**Comment by rogpeppe** [comment]
I would add it as part of the overview.

**Comment by rsc** [comment]
Import comments are really the go command's job.
go/build knows next to nothing about them, except for the ImportMode bit that Minux pointed out.
I think the docs in cmd/go are sufficient.
