### ISSUE TITLE
debug/macho: Invalid index reference in macho file Dysyms.IndirectSyms

### ISSUE THREAD

**Issue by gcmurphy** [golang/go#10178]
I may be misunderstanding the expected usage of debug/macho but I'm encountering the following and it doesn't seem correct to me. 

The godoc for the macho package has this definition: 

```
 type Dysymtab struct {
        LoadBytes
        DysymtabCmd
        IndirectSyms []uint32 // indices into Symtab.Syms
}
``` 

So I would expect given the c program: 
```
#include <stdio.h>
int main(void){
    puts("Hello World");
}

/*
$ gcc foo.c -o foo
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
*/
```

And reading the symbols using the following go code: 

```
package main

import (
    "debug/macho"
    "fmt"
    "os"
)

func main(){

    for _, path := range os.Args[1:] {

        file, err := macho.Open(path)
        if err != nil {
            fmt.Printf("error: could not open macho file: %v - %v\n", path, err)
            os.Exit(1)
        }
        defer file.Close()

        fmt.Printf("Dysymtab for %v\n", path)
        for _, index := range file.Dysymtab.IndirectSyms {
            if index < uint32(len(file.Symtab.Syms)) {
                fmt.Println(file.Symtab.Syms[index].Name)
            } else {
                fmt.Printf("wtf? >>>>>> %v, max = %v\n", index, len(file.Symtab.Syms))
            }
        }

    }
}
```

To not see this in the output: 

```
$ go run testcase.go a.out  | grep wtf
wtf? >>>>>> 1073741824, max = 4
```

This looks suspect to me. Although I may be using the library incorrectly.

**Comment by gcmurphy** [comment]
Sorry the version of go I'm using is - 

$ go version
go version go1.4.1 darwin/amd64

**Comment by minux** [comment]
I don't think there is anything wrong.

run "otool -Iv a.out" and note that there is an absolute symbol.

$ otool -Iv a.out
a.out:
Indirect symbols for (__TEXT,__stubs) 1 entries
address            index name
0x0000000100000f44     2 _puts
Indirect symbols for (__DATA,__nl_symbol_ptr) 2 entries
address            index name
0x0000000100001000     3 dyld_stub_binder
0x0000000100001008 ABSOLUTE
Indirect symbols for (__DATA,__la_symbol_ptr) 1 entries
address            index name
0x0000000100001010     2 _puts

$ go run issue10178.go a.out
Dysymtab for a.out
_puts
dyld_stub_binder
wtf? >>>>>> 1073741824, max = 4
_puts

**Comment by minux** [comment]
Just FYI, in /usr/include/mach-o/loader.h, we have
```
#define INDIRECT_SYMBOL_ABS     0x40000000
```
And sure enough 0x40000000 == 1073741824.

**Comment by gcmurphy** [comment]
Thanks.
