### ISSUE TITLE
cmd/link: missing docs

### ISSUE THREAD

**Issue by minux** [golang/go#10179]
In Go 1.4, we have https://golang.org/cmd/ld, which is the overall docs for the linkers,
after the c2go transition, we no longer have that page.
And https://tip.golang.org/cmd/internal/ld/ shows the package document, not the
command document. And https://tip.golang.org/cmd/6l doesn't show anything.

We should decide whether we want to release the old linkers, or just replace them with
cmd/link. And restore the docs if we still release the old linkers.

(I think we should release the old linkers, just in case there are some unknown problems
with the new linker.)

@rsc, what's your plan for the new linker?

**Comment by slimsag** [comment]
If the old linker is released, would bugs like #4069 (if fixed) appear in
1.5? Sorry if I've misunderstood something.

**Comment by minux** [comment]
Issue 4069 will be fixed, I have the CLs under review.

**Comment by rsc** [comment]
https://tip.golang.org/cmd/link/ works.
