### ISSUE TITLE
net: Dial connects successfully to unreachable host

### ISSUE THREAD

**Issue by brennerm** [golang/go#10186]
What does 'go version' print?
```bash
go version go1.4.2 darwin/amd64
```

What steps reproduce the problem?
http://play.golang.org/p/3Xm-GLcohL

What happened?
returned error is nil when dial any non-existent address.

What should have happened instead?
the error should not be nil.

Please provide any additional information below.
- [exact same issue](https://github.com/golang/go/issues/8276) which is already closed
- running on MacOSX 10.10.2

**Comment by ianlancetaylor** [comment]
I can not recreate the problem on GNU/Linux with either tip or Go 1.4.

Can anybody else recreate it on OS X?

**Comment by mrekucci** [comment]
Also, I can not reproduce the problem on my Mac OS X 10.10.2.

**Comment by brennerm** [comment]
Any further information needed from my side?

**Comment by mikioh** [comment]
> exact same issue which is already closed

Not ture.

> conn, err := net.Dial("ip4:1", UNREACHABLE_HOST)

Please revisit what you are trying to do for which protocol and its transport characteristic.

**Comment by mikioh** [comment]
PS: If you need a bit handy ICMP stuff, see http://godoc.org/golang.org/x/net/icmp.
PPS: ICMP is pretty raw stuff, specifying destination address on transmission/source address on reception by connect sysscall via Dial API is insufficient to control message exchange.

**Comment by brennerm** [comment]
Ok thanks for your support, guys.
