### ISSUE TITLE
runtime: merge slice and sliceStruct

### ISSUE THREAD

**Issue by josharian** [golang/go#10188]
The c-to-Go transition left behind a `slice` type and `sliceStruct` type in the runtime, with slightly different definitions:

```go
type slice struct {
    array *byte
    len   uint
    cap   uint
}

type sliceStruct struct {
    array unsafe.Pointer
    len   int
    cap   int
}
```

As far as I can tell, these can be collapsed, and `sliceStruct` is the preferred definition. Is this correct?

**Comment by josharian** [comment]
@randall77

**Comment by randall77** [comment]
Yes, the latter is more correct using unsafe.Pointer instead of *byte.  We could call it the former, though.

**Comment by rsc** [comment]
sgtm
