### ISSUE TITLE
cmd/cover: when a panic occurs cover still marks the whole basic block covered

### ISSUE THREAD

**Issue by taruti** [golang/go#10185]
The code coverage tool marks whole basic blocks as being covered when a statement in the middle panics. This can be quite confusing when the panics are converted to errors elsewhere with recover.

```
...
panic("...")
somecode // This is marked as covered.
```

A whole example example repo can be found in https://github.com/taruti/coverpanicbug and be triggered with "go test -cover" which falsely claims 100% coverage.

Go version 1.4.1 linux/amd64 and tools repo revision 22067118645556995c55964f3e5c82470e0b0c9f.

**Comment by robpike** [comment]
Fixed by https://go-review.googlesource.com/8140
