### ISSUE TITLE
cmd/go: Warn users getting dependencies from code.google.com

### ISSUE THREAD

**Issue by ImJasonH** [golang/go#10193]
Google Code is [shutting down](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html), and when it does, users who import from `code.google.com` will no longer have those dependencies resolve.

There are a lot of things we could try to mitigate this breakage, and it won't happen for a while, but I think it may make sense to at least print a warning to users when running `go get`.

**Comment by dsymonds** [comment]
Wacky idea: Print a warning in `go build` (and friends) too. Lots of people have packages already checked out, so won't benefit from a `go get` warning alone.

**Comment by mattn** [comment]
If you want to check your package is depend on `code.google.com`, see https://github.com/mattn/check-code-google-com

**Comment by uhoh-itsmaciek** [comment]
What's the status here? It looks like the tool warns for some things but not others, and, e.g., oracle is just left broken on the old site:

```ruby
maciek@mothra:~$ go get code.google.com/p/go.tools/cmd/oracle
# code.google.com/p/go.tools/cmd/oracle
../../../.gvm/pkgsets/go1.4/global/src/code.google.com/p/go.tools/cmd/oracle/main.go:166: too many arguments to conversion to oracle.Query: oracle.Query(args, mode, *posFlag, ptalog, &build.Default, *reflectFlag)
```

while godoc is nicer:

```
maciek@mothra:~$ go get code.google.com/p/go.tools/cmd/godoc
can't load package: the code.google.com/p/go.tools/cmd/godoc command has moved; use golang.org/x/tools/cmd/godoc instead.
```

Is that a server-side warning? In any case, it'd be great to provide warning; this would have saved me a few minutes tonight.

**Comment by ianlancetaylor** [comment]
I don't think we should warn on go build.  People with vendored code.google.com packages are fine as long as they don't update.

The bit about whether a package has moved is up to the package owner.
