### ISSUE TITLE
doc: a description of "go tool tour" command is missed

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#10198]
Neither `http://golang.org/doc/cmd` nor `http://golang.org/cmd/` mentions `tour` sub command.  But `go tool tour` works for go 1.4.2

**Comment by minux** [comment]
The go tool tour only works for the binary distribution releases downloaded
from https://golang.org/dl/

It won't work if you installed tour using go get.

**Comment by yaojingguo** [comment]
I am talking about  the binary distribution release. The `go tool tour` contained in the binary distribution release works. But a description is missed in the docs which are contained in the binary distribution release.

**Comment by rsc** [comment]
Well, we should document it somewhere. ☺

**Comment by rsc** [comment]
ping @adg?
