### ISSUE TITLE
cmd/internal/obj/x86: automatically fix CMPL argument order

### ISSUE THREAD

**Issue by josharian** [golang/go#10199]
CL 7697 caused doasm failures on 386:

```
runtime/append_test.go:1: doasm: notfound ft=2 tt=20 00112 (runtime/iface_test.go:207)  CMPL    $0, BX 2 20
```

I worked around the problem by reversing the order of the arguments during walk (CL 7810), but that's not the right fix. CMPL is symmetric, so liblink should gracefully generate CMPL BX, $0 instead.

**Comment by randall77** [comment]
CMPL is symmetric only if you're using EQ/NE on the result.

I think liblink is right, x86 can only compare with a constant in one direction.  Try compiling this with gcc (as a .s file):
	cmpq	$0, %rax
	cmpq	%rax, $0
The second one fails.  at&t ordering syntax is weird, I can't be sure if that second one corresponds to your error.  In any case, maybe something upstream of liblink needs to make sure the order is correct, and if not swap the order and the sense of all the LT/LE/GT/GE that use it?

**Comment by josharian** [comment]
Umm, right, thanks. `Brrev` already knows how to swap comparison order. It looks like the right place for this fix might be `bgen`, in `8g/cgen.go`. Russ has said that he's going to make a lot of this code portable soon, so now might not be the right time to touch it. The workaround is ugly, but it works for now.

**Comment by minux** [comment]
Yes, I agree liblink is correct. On ARM, CMP also can only take immediate
in one argument (the first).

**Comment by rsc** [comment]
It cannot be automatically fixed.

There is only one position the constant can go in, and if you swap them it screws up later comparisons. The calling code must be careful to put the constant in the right place, and that's all we can do.
