### ISSUE TITLE
builder: android/arm is flaky

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10206]
```
--- FAIL: TestPipeLookPathLeak (0.69s)
	exec_test.go:247: leaked 50 fds; want ~0; have:
		COMMAND     PID       USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
		init          1       root  exe       ???                ???       ???        ??? /proc/1/exe (readlink: Permission denied)
		init          1       root root       ???                ???       ???        ??? /proc/1/root (readlink: Permission denied)
		init          1       root  FDS                                                   /proc/1/fd/ (opendir: Permission denied)
		.             2       root  exe       ???                ???       ???        ??? /proc/2/exe (readlink: Permission denied)
		.             2       root root       ???                ???       ???        ??? /proc/2/root (readlink: Permission denied)
		.             2       root  FDS                                                   /proc/2/fd/ (opendir: Permission denied)
...
FAIL	os/exec	22.053s
```

**Comment by crawshaw** [comment]
Rather unsatisfactorily, I rebooted the android device. The os/exec test passes in 2.2s now (instead of 22s). It is also failing to fail on TestPipeLookPathLeak.

As the test itself includes a time.Sleep loop, I suspect the device simply became slow enough to make the test flaky.

It's not clear why the device became flaky. It was a couple of months since a reboot, but top showed no active processes and ps didn't reveal any cruft. None of the temporary directories appeared to be full. 

Keeping the issue open for now just in case some evidence appears.

**Comment by hyangah** [comment]
I believe this is because the lsof command on Android ignores the -p option (used to select only info on a specified pid). The test simply compares the line count of the lsof output at the beginning and end of the test and if they differ, it assumes fd leaks.

**Comment by minux** [comment]
Yeah, I verified on Android 5, stock lsof doesn't seem to take any argument
at all,
and it will always dump open files for all processes.
