### ISSUE TITLE
You can't always return a function call with the same return arity

### ISSUE THREAD

**Issue by chipaca** [golang/go#10200]
This works:

    func g() int {
            return 0
    }

    func f() int {
            return g()
    }

and this works:

    func g() (int, error) {
            return 0, nil
    }

    func f() (int, error) {
            return g()
    }

but this doesn't work:

    func g() {
            return
    }

    func f() {
            return g()
    }

and I found it surprising.

**Comment by cespare** [comment]
This is covered by [the spec](https://golang.org/ref/spec#Return_statements):

> In a function without a result type, a "return" statement must not specify any result values.

I suppose the bit below that about making a single call to a multi-valued function could be more explicit that such a function must return 1 or more values, but I'm not sure that's even needed.

**Comment by minux** [comment]
Yes, it's covered by the spec.

**Comment by chipaca** [comment]
Sorry, perhaps I wasn't clear. I didn't mean that it wasn't behaving as designed; I'm pointing out that the behaviour as designed seems to be inconsistent.

**Comment by minux** [comment]
It is consistent. Because there is no such thing as void in Go,
so you can't return something that is "nothing" (unlike in C,
where there is void, you can return f(); if f and the current func
both return void.

**Comment by chipaca** [comment]
Again, my apologies, perhaps I'm missing something that is obvious to you.

The way I see it, functions in go return 0 or more values. If they return 1 or more values, you can return what they return from a function that returns the same number of values. If they return 0, you can't. That's inconsistent, it's a silly special case that you need to remember. I don't understand what returning void or not has to do with it.

**Comment by ALTree** [comment]
IMO is quite a stretch to consider "return nothing" a special case of "return something".

**Comment by chipaca** [comment]
I'm not sure if you're agreeing or disagreeing with me, but in either case, it's not "return nothing" vs "return something"; it's "return 0 things", "return 1 things", "return 2 things", etc.

**Comment by ALTree** [comment]
I understand that if you look at this from the "0, 1, 2, .." perspective then the "return 0 things" seems to be a special case of "return N things". 

What I'm saying is that it's a stretch to consider the "return nothing" case as a "return 0 things" just so you can group it with all the others (return 1, etc..). "return nothing" is fundamentally different from all the other things you are grouping it with. That's why IMO is not a "silly special case". You can "return nothing" or "return something". Those are very different things.

That's why I personally don't find the current behaviour strange or inconsistent.

**Comment by ianlancetaylor** [comment]
I think we actually discussed that at some point, but I've forgotten what the conclusion was.  @griesemer do you remember?

**Comment by adg** [comment]
Seems to me that allowing

```
func f() {
  return g()
}
```

when both `g` and `f` function have no return values is, at the very least,
bad for readability. It looks like something is being returned when it is
not.

**Comment by griesemer** [comment]
I also think we discussed this before, but I would have to dig it up.

@chipaca You are right that one _could_ define parameter and return statement handling as you suggest, and just perhaps, in a strictly mathematical sense, it may be more consistent. But once you go that route, a lot of additional questions need to be answered (or perhaps would follow by implication). For instance:

If f is a function taking 0 arguments, and g returns no values, f(g()) should probably be permitted as well. What about f(g(), g())? Not so obvious. There's still a notion of "arity", and it may require special rules, too. It is not obvious that it makes the language more consistent or simpler, or better for that matter. And it is likely to cause a whole lot of confusion for less mathematically inclined programmers.

https://code.google.com/p/virgil/ is a programming language which allows this, I believe. There's a notion of a "void" type (at least there used to be), which is used to designate the absence of parameters and results. Consequently, functions that have a void parameter list accept a function call that returns a void result, and presumably this also applies to returns. One may even be able to declare void variables and then assign results of void functions. The author of virgil claims (personal communication) that this "fell out" naturally from the implementation. This may well be true, but it's not clear, as @adg already mentioned, that this is for the benefit of readability.

At the end of the day this is a design decision that has to be made, pretty early in the design of a language, and in Go we simply have not gone this route.

**Comment by chipaca** [comment]
Thank you @griesemer; that helped me understand why it's treated differently in the spec.
