### ISSUE TITLE
crypto/tls: add support for Certificate Transparency TLS extension

### ISSUE THREAD

**Issue by titanous** [golang/go#10201]
I'd like to be able to serve SCTs via the TLS extension with `crypto/tls`, similar to how the `Certificate` struct supports an `OCSPStaple`. I'm happy to put it together and submit a CL if the feature would be accepted.

/cc @agl

**Comment by rsc** [comment]
Adam, does this sound reasonable to you? Thanks.

**Comment by agl** [comment]
Yes, this is reasonable and very similar to OCSP stapling that's currently supported.

**Comment by titanous** [comment]
https://go-review.googlesource.com/8988
