### ISSUE TITLE
cmd/9g: reactivate componentgen

### ISSUE THREAD

**Issue by davecheney** [golang/go#10203]
b96026324480 moved `compenentgen` into `cmd/internal/gc` for all architectures. It looks like this unified `componentgen` produces broken code for arm64.

For the moment `componentgen` has been disabled in `cmd/7g`, this bug is tracking its reactivation.

**Comment by minux** [comment]
It's also disabled in cmd/9g.

**Comment by minux** [comment]
cmd/9g is also fixed. http://tip.golang.org/src/cmd/9g/ggen.go#L403
