### ISSUE TITLE
x/mobile/gl: Suggestions/questions that arose while adding WebGL backend.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#10218]
Hi @crawshaw,

Based on your proposal in https://github.com/google/gxui/issues/49#issuecomment-84324901 to try adding a WebGL backend to `x/mobile/gl`, I've been playing on a branch with making that happen.

Overall, it's going really well, and most things were a natural fit. I got it to work rendering a basic triangle with these imports:

```Go
package main

import (
	"encoding/binary"
	"errors"
	"fmt"

	"github.com/go-gl/mathgl/mgl32"
	glfw "github.com/shurcooL/goglfw"
	"golang.org/x/mobile/f32"
	"golang.org/x/mobile/gl"
)
```

![image](https://cloud.githubusercontent.com/assets/1924134/6774928/08aa2e18-d0e6-11e4-9c84-b5c20ef7257f.png)

Along the way, I found some issues with the existing interface of `x/mobile/gl` and I was wondering what your thoughts on making changes are.

First, a summary of my proposed changes, and below is a detailed rationale:

```diff
BufferData(target, usage, src) -> BufferData(target, src, usage)

GenBuffer -> CreateBuffer
GenFramebuffer -> CreateFramebuffer
GenRenderbuffer -> CreateRenderbuffer
GenTexture -> CreateTexture

// Maybe?
GetShaderi -> GetShaderParameteri
GetProgrami -> GetProgramParameteri

// Even more maybe?
+func GetShaderParameterb(s Shader, pname Enum) bool
+func GetProgramParameterb(p Program, pname Enum) bool
```

### 1. `func BufferData(target Enum, usage Enum, src []byte)` parameter order.

The order of `usage` and `src` seems to be swapped compared to OpenGL ES spec:

http://www.khronos.org/opengles/sdk/docs/man3/html/glBufferData.xhtml

```
void glBufferData(GLenum target,
                  GLsizeiptr size,
                  const GLvoid * data,
                  GLenum usage);
```

It is also swapped compared to WebGL spec:

```
void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
void bufferData(GLenum target, ArrayBufferView data, GLenum usage);
void bufferData(GLenum target, ArrayBuffer? data, GLenum usage);
```

Notably, `usage` should come last.

I suggest swapping the order:

```Go
func BufferData(target Enum, src []byte, usage Enum)
```

### 2. When need to invent new names, consider WebGL names instead of own.

The `x/mobile/gl` package offers a higher level API that slightly deviates from the OpenGL ES spec. It comes up with new function names in a few cases where no equivalent func exists in OpenGL ES spec. For example:

http://www.khronos.org/opengles/sdk/docs/man3/html/glGenBuffers.xhtml

`void glGenBuffers(GLsizei n, GLuint * buffers)`

`func GenBuffer() Buffer`

`glGenBuffer` always creates a single buffer, while the OpenGL ES spec's `glGenBuffers` takes a parameter `n`.

[WebGL spec](https://www.khronos.org/registry/webgl/specs/1.0.2/) does not have `glGenBuffers` either, but instead it provides:

`WebGLBuffer? createBuffer();`

Which is exactly the same signature, just different name. I suggest using `func CreateBuffer() Buffer` to match WebGL spec name.

It is more consistent with other OpenGL names like `glCreateProgram` and `glCreateShader`.

Similarly:

```
GenFramebuffer -> CreateFramebuffer
GenRenderbuffer -> CreateRenderbuffer
GenTexture -> CreateTexture
```

Another such case is something I'm less sure about, but I'll mention it.

`x/mobile/gl` has `GetShaderi` and `GetProgrami`. Those do not exist in OpenGL ES, it only has the `GetShaderiv` and `GetProgramiv` variants that accept multiple entries and use pointers.

WebGL does not have `GetShaderiv` and `GetProgramiv`, but instead it has:

```
any getShaderParameter(WebGLShader? shader, GLenum pname);
any getProgramParameter(WebGLProgram? program, GLenum pname);
```

Which is the same signature, just different name.

So, if you want to be more consistent with WebGL spec here, I would recommend renaming:

```
GetShaderi -> GetShaderParameteri
GetProgrami -> GetProgramParameteri
```

(And possibly offer the boolean variants `GetShaderParameterb` and `GetProgramParameterb`...)

Reason why I think it's better to reuse existing WebGL names rather invent own ones is (when signatures match), when inventing own, everyone has to find and learn it. But when reusing WebGL names, people porting/looking at existing WebGL code, which I imagine is a lot of code in the wild, will have an easier time porting/understanding Go code that uses `x/mobile/gl` package.

Thoughts?

/cc @ajhager @slimsag @neelance

**Comment by crawshaw** [comment]
I never decided when to freeze the method signatures of the gl package. It definitely should be frozen by the time Go 1.5 comes out. But I suppose it is still safe to change some, as long as nothing breaks silently.

- BufferData change looks good.
- s/Gen/Create/ is OK. Create is a better word.
- I'm not really interested enough in exactly matching WebGL to change Get{Shader,Program}i to Get{Shader,Program}Parameteri. Seems unnecessarily wordy, and the names are clear enough.

If you'd like to send CLs for the first two, please do. Update any call references to them in the mobile repo please.

**Comment by shurcooL** [comment]
Okay, sounds good, I'll do that. Would you want this CL separately from adding WebGL or is fine to do everything in one?

Another issue I've noticed in the internal [`glBoolean`](https://github.com/golang/mobile/blob/6ed9b243b17195bbfcddc0c6d63c3610e840e962/gl/types_common.go#L82-L87) helper.

```Go
func glBoolean(b bool) C.GLboolean {
	if b {
		return 0
	}
	return 1
}
```

Its logic seems to return the opposite of what it should. Is that unintentional?

If so, I'll fix that too, and probably use the `TRUE` and `FALSE` consts.

**Comment by crawshaw** [comment]
Separate please. Any idea that's logically separable should be a separate CL.

I don't know what happened to glBoolean. That looks entirely wrong. Strangely, it's used a bunch, so I don't know how anything works.

**Comment by shurcooL** [comment]
> I don't know what happened to glBoolean. That looks entirely wrong. Strangely, it's used a bunch, so I don't know how anything works.

Yeah, I was surprised to find that too.

It was causing issues for my existing GL code (that previously worked) when I did `gl.VertexAttribPointer` and needed to set `normalized` to `true`.

**Comment by shurcooL** [comment]
@crawshaw, I've submitted a CL at https://go-review.googlesource.com/8000, please take a look.

**Comment by shurcooL** [comment]
I've found another inconsistency:

```Go
func DrawElements(mode, ty Enum, offset, count int)
```

That parameter order deviates from both OpenGL ES and WebGL specs:

https://www.khronos.org/opengles/sdk/docs/man3/html/glDrawElements.xhtml

Can we change it to have same parameter order?

```Go
func DrawElements(mode Enum, count int, ty Enum, offset int)
```

**Comment by crawshaw** [comment]
Go for it.

**Comment by shurcooL** [comment]
Another issue.

Uniforms (and attributes) have concept of a _Uniform Location_, as well as _index_. The WebGL spec defines a typ `WebGLUniformLocation` to represent Uniform Location, and uses `GLuint` for the index.

Consider `glGetUniformLocation`:

```
WebGLUniformLocation? getUniformLocation(WebGLProgram? program, DOMString name)
```

The current equivalent `x/mobile/gl` API is:

```Go
// GetUniformLocation returns the location of uniform variable.
//
// http://www.khronos.org/opengles/sdk/docs/man3/html/glGetUniformLocation.xhtml
func GetUniformLocation(p Program, name string) Uniform
```

Which is fine (although I would've preferred the name `UniformLocation` rather than deviating from the spec).

But another func excepts an index of the uniform, not Uniform Location as its parameter:

```
WebGLActiveInfo? getActiveAttrib(WebGLProgram? program, GLuint index);
WebGLActiveInfo? getActiveUniform(WebGLProgram? program, GLuint index);
```

Yet the `x/mobile/gl` API expects a Uniform Location type instead of an index:

```
// GetActiveUniform returns details about an active uniform variable.
//
// http://www.khronos.org/opengles/sdk/docs/man3/html/glGetActiveUniform.xhtml
func GetActiveUniform(p Program, u Uniform) (name string, size int, ty Enum)
```

This makes `GetActiveUniform` really awkward to use, because there is no way to get/create the `Uniform` type.

The typical usage of `GetActiveUniform` makes sense when the parameter, correctly, is an index:

```Go
uniformCount := gl.GetProgrami(program, gl.ACTIVE_UNIFORMS)
for index := 0; index < uniformCount; index++ {
	name, size, ty := gl.GetActiveUniform(program, index)
	...
}
```

As things are, I need to try to create a `Uniform` type by doing `gl.Uniform{Value: int32(i)}`, which is awkward and not cross-platform compatible.

On desktop both Uniform Location and index are internally just integers, so it can be done, but that's going around the type system instead of using it correctly. The problem is that in WebGL, the Uniform Location is actually a JavaScript Object, while uniform index is an integer, so it can't work.

I highly recommend following the spec and using the type system correctly here. `GetActiveUniform` and `GetActiveAttrib` should accept an index as their 2nd parameter, not location type.

Would that change be amenable to you?
