### ISSUE TITLE
go/scanner: bug? if scan.Init with Mode(0) 

### ISSUE THREAD

**Issue by achun** [golang/go#10213]
when scan.Init with Mode(0)  and a comment in source such as

```
a=1
// last comment
```
or 

```
func x() {
// last comment
}
```

The lit of Scan results with the comment.

see http://play.golang.org/p/vsfNZGf3Pv

**Comment by griesemer** [comment]
Yes, indeed. The lit should be empty in this case. Thanks for reporting.

**Comment by achun** [comment]
@griesemer 

additional  http://play.golang.org/p/2-s6ZqIzhe
