### ISSUE TITLE
test: Test for Issue 9110 Fails with GOMAXPROCS > 1

### ISSUE THREAD

**Issue by BlackGriffen** [golang/go#10216]
On the master branch as of March 22, 2015, running the all.bash compile script fails when running the test for Issue 9110 if GOMAXPROCS is set to any value greater than 1. The test succeeds when GOMAXPROCS=1, or when GOMAXPROCS isn't set.

This is true on Mac OS 10.10, with bootstrap as Go 1.4.1 or 1.4.2. 

Error output with GOMAXPROCS=8:
```
##### ../test
# go run run.go -- fixedbugs/issue9110.go
incorrect output
BUG: object leak: 0 -> 360 -> 483

FAIL	fixedbugs/issue9110.go	0.829s
       36.38 real       189.74 user        39.03 sys
2015/03/22 18:23:14 Failed: exit status 1
```

**Comment by BlackGriffen** [comment]
Link to the issue that lead to the test: https://github.com/golang/go/issues/9110

**Comment by minux** [comment]
I think that test is defined with GOMAXPROCS=1 in mind.
Generally, don't set GOMAXPROCS for tests in $GOROOT/test.

**Comment by BlackGriffen** [comment]
I have GOMAXPROCS set in my .profile. If the test requires a specific value for GOMAXPROCS, it should copy the current value into a temporary variable (if it's set), set the value it needs, then return the environment variables to the state they were in before the test.

**Comment by minux** [comment]
set GOMAXPROCS in .profile is not recommend, and will actually make certain
programs slower than usual.

Just don't set GOMAXPROCS when running all.bash (or run.bash).

**Comment by bradfitz** [comment]
@minux, that's not a great answer. all.bash should still pass with any GOMAXPROCS set. If the test depends on X, it should setup X or skip or worst case: fail with a good message. But it shouldn't just mysteriously fail.

**Comment by BlackGriffen** [comment]
I just submitted a patch that addresses this issue on Unix systems by tweaking all.bash.

https://github.com/golang/go/compare/master...BlackGriffen:patch-1
