### ISSUE TITLE
cmd/go: add -pkgdir for redirecting installed artifacts

### ISSUE THREAD

**Issue by thockin** [golang/go#10210]
We build static binaries: `CGO_ENABLED=0 go install -x -installsuffix cgo <pkg>`

For some users, we get an error: `go install runtime: mkdir /usr/lib/google-golang/pkg/linux_amd64_cgo/:
permission denied`

As per email with Ian, this can be fixed by making the user run `sudo CGO_ENABLED=0 go install -a -installsuffix cgo std`, but this is unsatisfying.  If go can't install to the global dir, perhaps it should try to install somewhere private to my environment?

**Comment by rsc** [comment]
I plan to add a -pkgdir flag that will be usable when building alternate configurations, so that the standard library can be rebuilt and saved even if it cannot be installed in the standard place.

**Comment by thockin** [comment]
That sounds workable, thanks.
