### ISSUE TITLE
go/parser: valid conversion using a map type literal is rejected

### ISSUE THREAD

**Issue by cznic** [golang/go#10211]
This code ([playgound](http://play.golang.org/p/vpu_eiSfj4))

```go
package main

type t map[int]int

func main() {
	t := map[int]int{}
	map[int]int(t)[1] = 2
	println("ok")
}
```

compiles and runs ok, but clicking `Format` fails because go/parser reports

`7:2: expected statement, found 'map' (and 1 more errors)`.

**Comment by minux** [comment]
Already fixed on tip.
