### ISSUE TITLE
cmd/go: add -tags to go vet

### ISSUE THREAD

**Issue by c4milo** [golang/go#10228]
> What version of Go are you using (go version)? 

1.4.2

> What operating system and processor architecture are you using?

OS X 

> What did you do?

I just ran `go vet -x` on my package

> What did you expect to see?

I'm expecting to see 3 files being checked.

$ go vet -x
/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64/vet **account.go account_test.go postgres.go**

> What did you see instead?

Only 2 files being checked.

![](https://cldup.com/cUbekRUZRQ.png)

**Comment by ianlancetaylor** [comment]
Your subject line suggests that you are using build tags.  Please give us a complete example that we can use to recreate the problem.  Thanks.

(Looks like issue #4906 but that was meant to be fixed.)

**Comment by c4milo** [comment]
# File A
```go
package main

import "fmt"

func main() {
  fmt.Println("I don't do nothing")
}
```

# File B with build tag

```go
// +build mytag

package main

import "fmt"

func ButWhy() {
	fmt.Printf("but why?")
}
```

# go vet output: 

![](https://cldup.com/gElZP31k_3.png)

# Expected output

```shell
$ go vet -x
/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64/vet a.go b.go
```

**Comment by robpike** [comment]
It's honoring the build tags, so it's not really a bug. But it should accept a -tags argument, like go build.
Will fix the subject of this issue to match.

**Comment by rsc** [comment]
-tags is one of the 'build flags' but we don't want all of them.

**Comment by c4milo** [comment]
:dancer: Thank you @robpike!
