### ISSUE TITLE
net/url: inaccurate documentation for method URL.String

### ISSUE THREAD

**Issue by bmatsuo** [golang/go#10227]
go version: 1.4.2

problem: The [godoc](http://golang.org/pkg/net/url/#URL.String) for URL.String in "net/url" does not accurately describe the method's behavior when the Opaque field is set.

>     scheme:opaque
>     scheme://userinfo@host/path?query#fragment
> If u.Opaque is non-empty, String uses the first form; otherwise it uses the second form.

The following playground link demonstrates a `*url.URL` which does not fall into these categories.

http://play.golang.org/p/SPGP5eSieA

The documentation states that the snippet should print "https://example.com/foo". But they observed string is "https://example.com/foo?bar=baz#qux"

**Comment by minux** [comment]
I've sent https://golang.org/cl/7974
