### ISSUE TITLE
spec: clarify legal types of operands of x==y

### ISSUE THREAD

**Issue by adonovan** [golang/go#10229]
The spec describes Comparability as a dynamic property of values, which makes sense because of the rule for interface comparisons, which may panic at run-time.

The == operator is said to "apply to operands that are comparable", but obviously a compiler cannot know whether the operands are comparable in general.  In the special case where the operand type has no comparable values (i.e., slice, map, func, and aggregates thereof), the compiler is capable of rejecting the comparison, but the spec wording neither requires nor forbids this check.

Given than all implementations apply some variation of this check, the intent is clear enough.  We should make the spec explicitly require it, so that a program such as this one
  var m map[int]int
  _ = m == m
is unambiguously illegal.

**Comment by cznic** [comment]
> The == operator is said to "apply to operands that are comparable", but obviously a compiler cannot know whether the operands are comparable in general.

I fail to see the "obviously a compiler cannot know whether the operands are comparable in general." in this part of the [specs](http://golang.org/ref/spec#Comparison_operators):

> - Boolean values are comparable. Two boolean values are equal if they are either both true or both false.
> - Integer values are comparable and ordered, in the usual way.
> - Floating point values are comparable and ordered, as defined by the IEEE-754 standard.
> - Complex values are comparable. Two complex values u and v are equal if both real(u) == real(v) and imag(u) == imag(v).
> - String values are comparable and ordered, lexically byte-wise.
> - Pointer values are comparable. Two pointer values are equal if they point to the same variable or if both have value nil. Pointers to distinct zero-size variables may or may not be equal.
> - Channel values are comparable. Two channel values are equal if they were created by the same call to make or if both have value nil.
> - Interface values are comparable. Two interface values are equal if they have identical dynamic types and equal dynamic values or if both have value nil.
> - A value x of non-interface type X and a value t of interface type T are comparable when values of type X are comparable and X implements T. They are equal if t's dynamic type is identical to X and t's dynamic value is equal to x.
> - Struct values are comparable if all their fields are comparable. Two struct values are equal if their corresponding non-blank fields are equal.
> - Array values are comparable if values of the array element type are comparable. Two array values are equal if their corresponding elements are equal.
> 
> A comparison of two interface values with identical dynamic types causes a run-time panic if values of that type are not comparable. This behavior applies not only to direct interface value comparisons but also when comparing arrays of interface values or structs with interface-valued fields.
> 
> Slice, map, and function values are not comparable. However, as a special case, a slice, map, or function value may be compared to the predeclared identifier nil. Comparison of pointer, channel, and interface values to nil is also allowed and follows from the general rules above.

The above enumeration of what is comparable is constructing a set of comparable things, ie. what's not listed as comparable is not comparable and thus the compiler knows what is and what is not comparable in every case where the types are statically known to it, AFAICT. What cases are not covered by the above? Dynamic types comparison is defined above as well so the only other case where the compiler does not know statically the types is when things and/or the types of things are not defined at all, but such program is not valid. (Declarations and scope: _Every identifier in a program must be declared._)
> ...so that a program such as this one
> var m map[int]int
> _ = m == m
> is unambiguously illegal.

This is explicitly an unambiguously specified in the last paragraph quoted from the specs above (_Slice, map, and function values are not comparable._).

**Comment by adonovan** [comment]
You're right.  (The repetition of the word "values" and the dynamic nature of the interface case fooled me into thinking that in the interface case, comparability was a dynamic property, but it's not.  What's dynamic is panicking vs not panicking.)

Carry on...
