### ISSUE TITLE
runtime/pprof: test fails on windows/amd64 builder

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#10231]
From recent

http://build.golang.org/log/dfb6e28b125b9068674f188c0658155d89c924fb

and

http://build.golang.org/log/fdda4a9013bdf75c2747da2c9613e9cc7d4f3c5b

exit status 2147483651
FAIL	runtime/pprof	8.979s

2147483651 is 0x80000003 (STATUS_BREAKPOINT)

Alex

**Comment by minux** [comment]
Could you reproduce it? I can't imagine how we can could hit a breakpoint
in runtime/pprof test.

Perhaps we should add -test.v to cmd/dist/test.go and see if we can capture
more output.

**Comment by alexbrainman** [comment]
No I cannot reproduce it here.

Alex

**Comment by alexbrainman** [comment]
another similar failure

http://build.golang.org/log/ce3ee7d8cfb046035d479c8f8de2777febdeb783

exit status -1073741571
FAIL	runtime/pprof	9.195s

but with different exit code of

-1073741571 is 0xC00000FD (STATUS_STACK_OVERFLOW)

Alex

**Comment by alexbrainman** [comment]
Sorry but my previous message failure was from windows/386.

**Comment by mattn** [comment]
At the first, signal handling doesn't work?

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"time"
)

func main() {
	c := make(chan os.Signal, 10)
	signal.Notify(c)
	select {
	case s := <-c:
		log.Println("catch!")
		if s != os.Interrupt {
			log.Fatalf("Wrong signal received: got %q, want %q\n", s, os.Interrupt)
		}
	case <-time.After(3 * time.Second):
		log.Fatalf("Timeout waiting for Ctrl+Break\n")
	}
}
```
```
go build
ctrlbreak
```
And type CTRL-BREAK or CTRL-C, But `catch!` doesn't appear.

**Comment by alexbrainman** [comment]
@mattn wrong issue?

Alex

**Comment by mattn** [comment]
Hmm, strange.

os1_windows.go
```
func ctrlhandler1(_type uint32) uint32 {
	var s uint32

	switch _type {
	case _CTRL_C_EVENT, _CTRL_BREAK_EVENT:
		s = _SIGINT
	default:
		return 0
	}

	if sigsend(s) {
		println(1) // ADD PRINTLN HERE
		return 1
	}
	exit(2) // SIGINT, SIGTERM, etc
	return 0
}
```
When added `println` in above, it works fine. But not, it doesn't work correctly.

**Comment by mattn** [comment]
Sorry moved my comments into #10215

**Comment by alexbrainman** [comment]
It has been a while since I seen this issue. Closing for now.

Alex
