### ISSUE TITLE
x/sys/unix: missing support for linux/arm64

### ISSUE THREAD

**Issue by minux** [golang/go#10238]

**Comment by frobware** [comment]
Given that the port was recently merged I was curious as to what "missing support" means. Is this cgo related?

**Comment by bradfitz** [comment]
@frobware, this is for the x/sys repo (see the github Label on the right).

It's at https://github.com/golang/sys/tree/master/unix

**Comment by minux** [comment]
Let's keep this issue only about linux/arm64.
The linux/arm issue is different. linux/arm only lacks Syscall9 and a few constants,
whereas unix doesn't support linux/arm64 at all.

**Comment by larzconwell** [comment]
x/sys/unix supports linux/arm64 as of CL 10038, so this can be closed @minux.
