### ISSUE TITLE
website: wrong links

### ISSUE THREAD

**Issue by djhworld** [golang/go#10236]
Hi there,

I've found a few 404s on golang.org, mostly on some old blog posts and release notes so probably not an issue.

Not sure if anyone wants them fixed, but here you go

* http://blog.golang.org/organizing-go-code links to http://golang.org/src/cmd/godoc/
  * *"Godoc is nearly 6000 lines over 16 files"*
* https://golang.org/doc/go1.4 links to https://golang.org/pkg/crypo/tls/
  * *"through the new CertificateForName function of the Config struct."*
  * Small typo in "crypo" on the "Config" link.
* https://golang.org/doc/devel/release.html links to https://golang.org/pkg/exp/gui/
  * *"The GUI-related code from exp/draw is now located in the exp/gui package."*
  * Looks like this package no longer exists, admittedly this is from 2011 so things will have changed since then
* https://golang.org/doc/devel/weekly.html links to http://golang.org/doc/devel/roadmap.html
  * *"There is now a public road map, in the repository and online"*
  * This page stopped being updated in 2012, so probably doesn't need to be fixed
* https://golang.org/doc/devel/release.html links to https://golang.org/pkg/old/template/
  * *"The original template package is still available as old/template. The old/template package is deprecated and will be removed."*
  * Evidently this happened so doesn't need to be fixed!

**Comment by minux** [comment]
doc/go1.4.html has just been fixed.

I'm not sure if we want to fix older release docs. we probably want to
update
the blog post though.

**Comment by Thomasdezeeuw** [comment]
Found another broken link, just above http://golang.org/pkg/math/#MaxFloat32 it links to http://oeis.org/Axxxxxx, which returns a 404.

**Comment by dominikh** [comment]
The oeis link is not broken, it means for you to fill in the `xxxxx` with the numeric IDs from the comments. For example: http://oeis.org/A002193 for math.Sqrt2

**Comment by Thomasdezeeuw** [comment]
I see, in that case it could do with some explanation.
