### ISSUE TITLE
doc: answer "Why isn't x is the standard library?"

### ISSUE THREAD

**Issue by josharian** [golang/go#10246]
This question comes up a lot. It'd be nice to have a canonical answer or set of answers that we can just link to. I don't know whether it belongs in the FAQ or the contributing page or the wiki. Probably the latter.

I don't think I'm the right person to write the first draft, although I'm happy to add to it. @bradfitz, maybe?

**Comment by bradfitz** [comment]
Yes! I want this. I'll propose a first draft and let Rob et al polish words.
