### ISSUE TITLE
go/ast: incorrect docs for Inspect

### ISSUE THREAD

**Issue by achun** [golang/go#10243]
I am not good in Engilsh.

The documents of ast.Inspect says:

```
If f returns true, Inspect invokes f  for all the non-nil children of node, recursively.
```

see the play http://play.golang.org/p/HID53LSwv_

**Comment by minux** [comment]
f could indeed receive nil nodes, it's used to signal that one level has
completed. See the docs of Walk for details.

I think the docs of Inspect should mirror that of Walk.

/cc @griesemer

**Comment by griesemer** [comment]
https://go-review.googlesource.com/8382
