### ISSUE TITLE
net: Add MarshalText and UnmarshalText to HardwareAddr

### ISSUE THREAD

**Issue by krolaw** [golang/go#10244]
When backing up routing config to JSON, discovered IP worked correctly, but HardwareAddr did not.  
I think adding MarshalText and UnmarshalText to HardwareAddr will make it more consistent with IP.

Thanks.

**Comment by mikioh** [comment]
It's easy to make own marshaler and unmarshaler stuff, and please do so.

IIRC, there's no standardized canonical form of textual representation even for IEEE stuff such as MAC-48/64, EUI-48/64. If you need to choose a format for your application, perhaps this RFC, https://tools.ietf.org/html/rfc7043, would be a help; I mean "two-digit hexadecimal numbers separated by hyphens."
