### ISSUE TITLE
MurmurHash3 & CityHash non-cryptographic hash functions

### ISSUE THREAD

**Issue by baijum** [golang/go#10245]
MurmurHash3 & CityHash are non-cryptographic hash functions suitable for general hash-based lookup.   These hash functions would be a good addition to the standard library.

May be Spooky also can be considered:
http://burtleburtle.net/bob/hash/spooky.html

More info:
http://en.wikipedia.org/wiki/MurmurHash
http://en.wikipedia.org/wiki/CityHash

http://google-opensource.blogspot.in/2011/04/introducing-cityhash.html
https://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed
https://stackoverflow.com/questions/11899616/murmurhash-what-is-it/11901654#11901654
http://research.neustar.biz/2012/02/02/choosing-a-good-hash-function-part-3/

**Comment by baijum** [comment]
Looks like there are few more:

* https://131002.net/siphash/
* https://code.google.com/p/farmhash/

**Comment by bradfitz** [comment]
Unless one of these is required by TLS, it is our intention to not expand the standard library unnecessarily. These can be fetched using "go get" and several of these already are.

**Comment by baijum** [comment]
@bradfitz These hash functions are "non-cryptographic" so it won't be useful for TLS.  In fact, there are 4 packages in Go standard library not used by any cryptographic package.

See the bottom of this page:
http://golang.org/pkg/hash/

FWIW, Rust standard library has only one (compared to 4 in Go), that is siphash:
http://doc.rust-lang.org/1.0.0-alpha.2/std/hash/struct.SipHasher.html
https://github.com/rust-lang/rust/blob/master/src/libcore/hash/sip.rs

**Comment by baijum** [comment]
Python also adopts Siphash, this PEP (final) has a good comparison with others:
https://www.python.org/dev/peps/pep-0456/

**Comment by bradfitz** [comment]
I know what these are. What other languages include in their standard libraries has no bearing here. My previous statement stands. You can use "go get". See:

http://godoc.org/?q=murmur
http://godoc.org/?q=cityhash
http://godoc.org/?q=farmhash
http://godoc.org/?q=siphash
etc.
