### ISSUE TITLE
spec: clarify that """ is an invalid token

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10248]
It seems that the Go spec (as of March 20, 2015) allow `"""` as a string literal, but gc and go/scanner (and I would imagine gccgo) do not treat is as such.

The relevant production rules are:

    interpreted_string_lit = `"` { unicode_value | byte_value } `"` .
    unicode_value    = unicode_char | little_u_value | big_u_value | escaped_char .
    unicode_char   = /* an arbitrary Unicode code point except newline */ .

So since unicode_char can match `"` and tokens are "the longest sequence of characters that form a valid token", it seems that `"""` is a potential match.  However, there's also descriptive text to consider.

Rune literals mention "Within the quotes, any character may appear except single quote and newline." so `'''` is invalid.

Raw string literals mention "Raw string literals are character sequences between back quotes ``` `` ```. Within the quotes, any character is legal except back quote." so ```` ``` ```` is invalid.

But interpreted string literals only mention "The text between the quotes, which may not contain newlines, forms the value of the literal, with backslash escapes interpreted as they are in rune literals (except that `\'` is illegal and `\"` is legal), with the same restrictions." which as far as I can tell does *not* forbid unescaped double quotes.

It seems like the text should be modified to say something like "which may not contain newlines *or unescaped double quotes*".

Arguably the rule literal text quoted above should also be amended to clarify that single quotes are allowed in escape sequences, otherwise it seems to forbid `'\''`.  I can sorta see how the wording is meant to suggest that any single character can appear except for those two restrictions, but I think that could be worded more clearly.

**Comment by griesemer** [comment]
Non-urgent.

**Comment by mdempsky** [comment]
Agreed as non-urgent.  Just needed to report as a pedant. :)

A somewhat related super-pedantic issue would be that `"/*foo*/"` should arguably parse as `" "`, because the Go spec says comments don't nest, but not that they can't occur within string literals.

Just for comparison, the C spec explicitly states "Except within a character constant, a string literal, or a comment," for limiting when comment sequences can occur.

Also for comparison, in Java the handling of `\uXXXX` Unicode escape sequences is the very first pass, and oblivious to tokenization rules.  So while `'\\n'` is an invalid character literal, `'\u005cn'` is first converted to `'\n'` which *is* valid.  (You can similarly even start end-of-line comments with `\u002f\u002f`.)  So there's *some* precedent for having translation passes before (and thus oblivious to) tokenization.
