### ISSUE TITLE
go: go 1.4.2 core dump on redhat enterprise 5.6 x86_64

### ISSUE THREAD

**Issue by bigwhite** [golang/go#10255]
go version: 
go1.4.2.linux-amd64.tar.gz

enviroment:

 Linux 2.6.18-238.el5 #1 SMP Sun Dec 19 14:22:44 EST 2010 x86_64 x86_64 x86_64 GNU/Linux

when run "go version" or any associated go command, it core dumps.  gdb output as below:

 gdb .bin/go/bin/go core.31613 
GNU gdb (GDB) Red Hat Enterprise Linux (7.0.1-32.el5)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home1/baim/.bin/go/bin/go...
warning: Loadable segment ".tbss" outside of ELF segments
done.
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff7d481000
Core was generated by `go'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fff7d481767 in ?? ()
(gdb) bt
#0  0x00007fff7d481767 in ?? ()
#1  0x00000000004a8a2c in runtime.nanotime () at /usr/local/go/src/runtime/sys_linux_amd64.s:147
#2  0x000000000049b519 in MHeap_FreeSpanLocked () at /usr/local/go/src/runtime/mheap.c:552
#3  0x000000000049afe8 in MHeap_Grow () at /usr/local/go/src/runtime/mheap.c:420
#4  0x000000000049ad25 in MHeap_AllocSpanLocked () at /usr/local/go/src/runtime/mheap.c:298
#5  0x000000000049a581 in mheap_alloc () at /usr/local/go/src/runtime/mheap.c:190
#6  0x000000000049a7d6 in runtime.MHeap_Alloc () at /usr/local/go/src/runtime/mheap.c:240
#7  0x00000000004948cb in MCentral_Grow () at /usr/local/go/src/runtime/mcentral.c:197
#8  0x00000000004943d7 in runtime.MCentral_CacheSpan () at /usr/local/go/src/runtime/mcentral.c:85
#9  0x00000000004940c0 in runtime.MCache_Refill () at /usr/local/go/src/runtime/mcache.c:90
#10 0x0000000000493c57 in runtime.mcacheRefill_m () at /usr/local/go/src/runtime/malloc.c:368
#11 0x0000000000490cba in runtime.onM () at /usr/local/go/src/runtime/asm_amd64.s:273
#12 0x0000000000478d69 in runtime.mallocgc (size=288, typ=0x857800, flags=0, ~r3=0x2adc00000000) at /usr/local/go/src/runtime/malloc.go:178
#13 0x0000000000478fb9 in runtime.newobject (typ=0x857800, ~r1=0x2adc5d20a000) at /usr/local/go/src/runtime/malloc.go:353
#14 0x000000000048094a in runtime.newG (~r0=0x49363a) at /usr/local/go/src/runtime/proc.go:233
#15 0x000000000049f61f in allocg () at /usr/local/go/src/runtime/proc.c:925
#16 0x00000000004a211f in runtime.malg () at /usr/local/go/src/runtime/proc.c:2106
#17 0x000000000049cbe7 in runtime.mpreinit () at /usr/local/go/src/runtime/os_linux.c:219
#18 0x000000000049e0a9 in mcommoninit () at /usr/local/go/src/runtime/proc.c:201
#19 0x000000000049dda5 in runtime.schedinit () at /usr/local/go/src/runtime/proc.c:138
#20 0x0000000000490ab6 in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:95
#21 0x0000000000000001 in ?? ()
#22 0x00007fff7d4152a8 in ?? ()
#23 0x0000000000000001 in ?? ()
#24 0x00007fff7d4152a8 in ?? ()
#25 0x0000000000000000 in ?? ()
(gdb) quit

**Comment by davecheney** [comment]
I am sorry but Go has never supported RHEL5.

**Comment by minux** [comment]
Please upgrade your kernel.

There is a certain range of 2.6.18 kernel that has a broken VDSO.

For example,  2.6.18-238.19.1.el5 doesn't have this problem.
