### ISSUE TITLE
cmd/pprof: select browser for web output more intelligently

### ISSUE THREAD

**Issue by jonhoo** [golang/go#10259]
When asking pprof for output using `web`, it [currently](https://github.com/golang/go/blob/c9d0c812142be1c8f224012f24d111ba46ccdc10/src/cmd/pprof/internal/commands/commands.go#L84) selects browsers using an in-order traversal of the list '"chrome", "google-chrome", "firefox"'. On each platform, it also tries a platform-specific file opener (`xdg-open` on *nix) if all the list of browsers all fail to execute.

This behavior is non-intuitive, as users' browser preferences are not respect if they have one of those browsers installed, but use another browser by default (this is particularly common for web developers). Instead, only the platform-specific opener should be used, and only in the case where it fails should fallbacks be attempted.

**Comment by nightlyone** [comment]
Yes, I agree that the defaults are in the wrong order. The platform-specific file openers should be first and the opinionated fallbacks should come later.

The fix is simple:
```diff
diff --git a/src/cmd/pprof/internal/commands/commands.go b/src/cmd/pprof/internal/commands/commands.go
index 51397a3..2c5e2d0 100644
--- a/src/cmd/pprof/internal/commands/commands.go
+++ b/src/cmd/pprof/internal/commands/commands.go
@@ -82,7 +82,8 @@ func PProf(c Completer, interactive **bool, svgpan **string) Commands {
 // browsers returns a list of commands to attempt for web visualization
 // on the current platform
 func browsers() []string {
-       cmds := []string{"chrome", "google-chrome", "firefox"}
+       var cmds []string
+
        switch runtime.GOOS {
        case "darwin":
                cmds = append(cmds, "/usr/bin/open")
@@ -91,7 +92,7 @@ func browsers() []string {
        default:
                cmds = append(cmds, "xdg-open")
        }
-       return cmds
+       return append(cmds, "chrome", "google-chrome", "firefox")
 }
```

Any other opinions? If ok, I will send a CL.

**Comment by jonhoo** [comment]
I suspect the fallbacks will never be used in this case (well, unless the OS opener does not exist). We could potentially get rid of them altogether?

**Comment by nightlyone** [comment]
I would keep them, since I don't know how dragonfly or plan9 implements that.

**Comment by jonhoo** [comment]
Wouldn't a preferred fallback to `$BROWSER` be better for those OSes?

**Comment by nightlyone** [comment]
I honestly don't know, so I suggested the minimal fix.

**Comment by jonhoo** [comment]
My guess for best order of operations would be ["os-specific opener", `$BROWSER` if set, "chrome", "google-chrome", "chromium" "firefox"].

The fallback list also has other problems like the "google-chrome" binary sometimes being called "google-chrome-stable", beta versions of browsers are never used, Opera and Safari aren't mentioned, etc., but those are second-order concerns.
