### ISSUE TITLE
intrusive container types (requires offsetof() in callee)

### ISSUE THREAD

**Issue by shawnl** [golang/go#10251]
Go's type system makes it impossible generic binary search trees with the tree metadata embedded in a struct[1], rather than having the tree metadata have a pointer that points to datamembers.

I imagine the compiler could detect the import, and then fix up these types and pointer to point to the parent struct, rather than the metadata withing the data struct. The point is that the pacakge that imports "tree/redblack" shouldn't need unsafe.

tree/redblack: https://github.com/shawnl/go/commit/801830189158eb9e97fb7d41a58670fb7277f357

[1] https://github.com/torvalds/linux/blob/master/include/linux/rbtree.h

**Comment by tv42** [comment]
Actually not true: https://godoc.org/github.com/tv42/intrusive

Probably a better approach is a container library that knows your data type, e.g. https://godoc.org/github.com/cznic/b with code generation.

I wouldn't hold my breath waiting for compiler magic.

**Comment by shawnl** [comment]
the first is an atrocious hack, and the second I am aware of, but its not generic

The simplest compiler magic would be to be able to assert that an object is being passed as a struct member (pointer to), and to get a pointer to the parent struct, but then there is the problem of type checking.

Plenty of people seem aware of this problem enough that this bug should stay open.

**Comment by shawnl** [comment]
This is actually a very generic problem for the compiler, but proposing a language syntax change to implement is something I don't really want to do.

**Comment by minux** [comment]
I don't understand what are you asking about.

To discuss how to implement high performance data structures in Go,
please use the golang-nuts mailing list. Thanks.

**Comment by shawnl** [comment]
We want to implement an type of interface that can interact with the type of the struct that contains that type (or interface), without the parent struct being explicitely passed, or our type having to hardcode the type of the parent struct. @minux the linux kernel headed I linked to explains the method

**Comment by shawnl** [comment]
https://github.com/torvalds/linux/blob/master/Documentation/rbtree.txt#L47

**Comment by ianlancetaylor** [comment]
Use the reflect package.

Please take this discussion to the golang-nuts mailing list.  If you can pin down a specific request, then open a new issue.  Thanks.

**Comment by minux** [comment]
I know the concept of intrusive data structure. But I still don't know what
are you requesting.

If you are suggesting a language change, please discuss on golang-nuts
mailing list first.
