### ISSUE TITLE
cmd/cover: internal error: overlapping blocks for func in for clause

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10269]
I am on commit c754be8979a6f3dab7b9e595077745a2087b7c02.

Add the following file:

$ cat src/cmd/internal/obj/arm64/arm64_test.go
```go
package arm64
import "testing"
func TestTest(t *testing.T) {} 
```

Then:
```
$ go test -c -cover cmd/internal/obj/arm64
cover: internal error: block 60 overlaps block 62
	src/cmd/internal/obj/arm64/obj7.go:#8196,#8260 src/cmd/internal/obj/arm64/obj7.go:#8237,#8256
```

**Comment by robpike** [comment]
This has nothing to do with the added file, it's just that the file is the first test file, so it's the first to trigger a coverage rewrite.

Here is a self-contained example:

% cat x.go
package x

func x() {
	for ; ; (func() { i++ })() {
	}
}
% go tool cover -mode=set x.go > /dev/null
cover: internal error: block 0 overlaps block 1
	x.go:#20,#50 x.go:#39,#46
%

**Comment by robpike** [comment]
The contents of the added file above is irrelevant. Its only purpose, being the first test file in the directory, is to trigger the coverage rewrite.

Here is a self-contained simple example of the problem

% cat x.go
package x

func x() {
 for ; ; (func() {})() {
 }
}
% go tool cover -mode=set x.go > /dev/null
cover: internal error: block 0 overlaps block 1
	x.go:#20,#45 x.go:#39,#41
%

**Comment by robpike** [comment]
closed by https://go-review.googlesource.com/8284
