### ISSUE TITLE
net/url url.URL should parse the port number and store it separately

### ISSUE THREAD

**Issue by foresmac** [golang/go#10262]
The port number from a URL should not be left tacked on the end of the host when parsing a URL into a `url.URL` struct. Instead, the port number should be pulled out and added to a `url.URL.Port` field. Leaving the port in a parsed hostname invariably leaves developers calling `strings.Split(url.URL.Host, ":")[0]` repeatedly to get the hostname.

**Comment by foresmac** [comment]
For instance:
```
http://www.example.com:4000/example/path?page=42
```

Should parse to:
```go
url.URL{"http", "", nil, "www.example.com", 4000, "/example/path", "page=42", ""}
```

**Comment by minux** [comment]
First of all, port is part of the host in RFC 2616.
And more importantly, this is a backward incompatible change, so
even if we want to add a `Port` field to `net/url.URL`, we can't.

**Comment by foresmac** [comment]
Fair enough.
