### ISSUE TITLE
x/crypto/ssh: handshake failed: ssh: no common algorithms with MACs hmac-sha2-256,hmac-sha2-512

### ISSUE THREAD

**Issue by roman-yepishev** [golang/go#10274]
go version go1.4.2 darwin/amd64

With OpenSSH server configured to accept:
```
MACs hmac-sha2-256,hmac-sha2-512,hmac-ripemd160
```

Go ssh client fails with:
```
ssh: handshake failed: ssh: no common algorithms
```

The server side logs that client simply does not support anything but hmac-sha1 and hmac-sha1-96:

```
fatal: no matching mac found: client hmac-sha1,hmac-sha1-96
server hmac-sha2-256,hmac-sha2-512,hmac-ripemd160
```

Which is indeed true: https://github.com/golang/crypto/blob/c57d4a71915a248dbad846d60825145062b4c18e/ssh/mac.go#L46
```
var macModes = map[string]*macMode{
	"hmac-sha1": {20, func(key []byte) hash.Hash {
		return hmac.New(sha1.New, key)
	}},
	"hmac-sha1-96": {20, func(key []byte) hash.Hash {
		return truncatingMAC{12, hmac.New(sha1.New, key)}
	}},
}
```

It would be great if the SSH client supported hmac-sha2 family of MACs.

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by dluchinienoc** [comment]
I spent a few minutes looking through the code and don't see any obvious reason this wouldn't work:

```
var macModes = map[string]*macMode{
	"hmac-sha2-512": {64, func(key []byte) hash.Hash {
		return hmac.New(sha512.New, key)
	}},
	"hmac-sha2-256": {32, func(key []byte) hash.Hash {
		return hmac.New(sha256.New, key)
	}},
	"hmac-ripemd160": {20, func(key []byte) hash.Hash {
		return hmac.New(ripemd160.New, key)
	}},
	"hmac-sha1": {20, func(key []byte) hash.Hash {
		return hmac.New(sha1.New, key)
	}},
	"hmac-sha1-96": {20, func(key []byte) hash.Hash {
		return truncatingMAC{12, hmac.New(sha1.New, key)}
	}}
}
```

**Comment by datianshi** [comment]
@dluchinienoc @ianlancetaylor  I met this issue too, hope this can be fixed in the repo

Besides @dluchinienoc change. Also need to change on the https://github.com/golang/crypto/blob/master/ssh/common.go#L55
To add corresponding algorithm string, tested and worked

Surprised golang does not do pull request :(

Cheers

**Comment by ianlancetaylor** [comment]
We don't do pull requests but we accept contributions through the process described at http://golang.org/doc/contribute.html .

**Comment by datianshi** [comment]
@agl  Can you review? 

https://go-review.googlesource.com/#/c/8353/   ^^

**Comment by dluchinienoc** [comment]
While it won't affect our use case specifically, MACs in common.go are specified in order or preference, so it might be best to prefer the new (stronger) MACs by ordering them before the SHA1 MACs:
```
"hmac-sha2-512", "hmac-sha2-256", "hmac-sha1", "hmac-sha1-96"
```

**Comment by allomov** [comment]
I had the same problem with openSSH. To solve it currently, I needed to add `hmac-sha1` to `MACs` in `/etc/ssh/sshd_config` and restart sshd.

**Comment by denji** [comment]
$ go version
go version go1.5rc1 darwin/amd64

> panic: Failed to dial: ssh: handshake failed: ssh: no common algorithms

OpenSSH work perfectry:

    debug1: kex: server->client aes128-cbc hmac-sha1 none
    debug1: kex: client->server aes128-cbc hmac-sha1 none

SSH Client CISCO:
```go
package main

import (
	"flag"
	"fmt"

	//"github.com/ScriptRock/crypto/ssh"
	"golang.org/x/crypto/ssh"
)

var (
	USER = flag.String("user", os.Getenv("USER"), "ssh username")
	HOST = flag.String("host", "cisco86.drekstop.dev", "ssh server hostname")
	PORT = flag.Int("port", 22, "ssh server port")
	PASS = flag.String("pass", os.Getenv("SSH_PWD"), "ssh password")
)

func init() { flag.Parse() }

func main() {
	//ssh.Config
	Ciphers: []string{"aes128-cbc", "hmac-sha1", "none"},

	sshConfig := &ssh.ClientConfig{
		User: *USER,
		Auth: []ssh.AuthMethod{ssh.Password(*PASS)},
		//	HostKeyAlgorithms: []string{ssh.KeyAlgoRSA, ssh.KeyAlgoDSA},
	}

	addr := fmt.Sprintf("%s:%d", *HOST, *PORT)
	client, err := ssh.Dial("tcp", addr, sshConfig)
	if err != nil {
		panic("Failed to dial: " + err.Error())
	}

	session, err := client.NewSession()
	if err != nil {
		client.Close()
		panic("Failed to create session: " + err.Error())
	}

	out, err := session.CombinedOutput("show ssh")
	if err != nil {
		panic("Failed to run: " + err.Error())
	}
	fmt.Println(string(out))

	// Close connection
	client.Close()
}
```

**Comment by davecheney** [comment]
@denji this issue is closed. Please raise a new issue.
