### ISSUE TITLE
mime: TestExtensionsByTypeMultiple broken on windows

### ISSUE THREAD

**Issue by cookieo9** [golang/go#10278]
On my windows machine (Windows 8.1 64-bit), the TestExtensionsByTypeMultiple test breaks consistently with the following error at tip:
```
--- FAIL: TestExtensionsByTypeMultiple (0.00s)
        type_test.go:76: ExtensionsByType("text/html") = [.htm .html .shtml]; want [.htm .html]
```
This is likely the result of the MIME types map being made using data from the registry, and my system having an extra entry for text/html that the test wasn't expecting.

I did not add the entry manually myself, so it's either a default for my version of the OS (compared to the builder's) or an addition made by a program I installed. Either case, the test should be probably be made more robust, or ignore the registry's mime-entries during testing.

**Comment by bradfitz** [comment]
Thanks.

These tests need to be more insulated. They're testing too many unrelated things at once. The types_test.go tests are mixing testing the various functions and also testing parsing the OS-specific text files. Those need to be separate tests, and tests like `TestExtensionsByTypeMultiple` need to be testing just those functions on static data baked into the tests and not let OS-specific differences creep in.

**Comment by bradfitz** [comment]
I sent: https://go-review.googlesource.com/8213
