### ISSUE TITLE
gccgo: cannot convert user-defined type whose underlying type is uintptr to unsafe.Pointer

### ISSUE THREAD

**Issue by h4ck3rm1k3** [golang/go#10284]
This example from the go core runtime , trying to compile with 

```
unsafe_pointer.go:13:21: error: invalid type conversion (cannot use type gclinkptr as type unsafe.Pointer)
  x := unsafe.Pointer(v)
```

```
package main
import	"unsafe"
import	"fmt"
type gclinkptr uintptr
type mspan struct {
        freelist gclinkptr // list of free objects                                                                                                                
}

func main() {
	var a mspan 
	var s *mspan
	s = &a
        v := s.freelist
        x := unsafe.Pointer(v)
	fmt.Println(x)
}
```

See code here on play :
http://play.golang.org/p/HkMAa-VU0x

**Comment by h4ck3rm1k3** [comment]
see a mention of something similar https://github.com/conformal/gotk3/issues/58#issuecomment-44138029

**Comment by h4ck3rm1k3** [comment]
strange, this works
it looks like the type is not begin resolved.
```
package main
import"unsafe"
import"fmt"
type mspan struct {
        freelist uintptr // list of free objects                                                                                                                  
}
func main() {
        var a mspan
        var s *mspan
        s = &a
        v := s.freelist
        x := unsafe.Pointer(v)
        fmt.Println(x)
}
```

**Comment by minux** [comment]
gccgo implements the conversion to unsafe.Pointer wrong (or based on a
previous version of the spec?)
The spec says: "Any pointer or value of underlying type uintptr can be
converted to a Pointer type and vice versa." however, gccgo only allows
conversion to unsafe.Pointer if the type is uintptr.

Simple reproduction:
package f
import "unsafe"
type T uintptr
var x unsafe.Pointer = unsafe.Pointer(T(0))

**Comment by ianlancetaylor** [comment]
Fixed on tip.
