### ISSUE TITLE
net/http: serveContent should 500 instead of 404 on error

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10283]
http's `fs.go` contains:

```
        f, err := fs.Open(name)
        if err != nil {
                // TODO expose actual error?                                                                                                                                                
                NotFound(w, r)
                return
        }
        defer f.Close()

        d, err1 := f.Stat()
        if err1 != nil {
                // TODO expose actual error?                                                                                                                                                
                NotFound(w, r)
                return
        }
```

This bug is about those TODOs.

We should send a 500 instead of a 404. Sending the actual error text is probably too risky (might contain sensitive information). Instead, we could just log it.

**Comment by asergeyev** [comment]
Brad it's not quite correct, if error is permission-related, the web-servers normally give 403. Non-existing files return 404. 

I can imagine there should be errors that should result in 500 but normally two above should handle most of the cases (*CGI, proxying and SSI are usual suspects for 500)

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/9200
