### ISSUE TITLE
all.bat: fails when %TEMP% has non-latin characters in Windows environment.

### ISSUE THREAD

**Issue by gegogi** [golang/go#10287]
In Windows environment, the test procedure of all.bat fails when %TEMP% path has non-latin characters. This is usually the case when people have their Windows account name in their native language.

**Comment by bradfitz** [comment]
This bug reports lacks information.

Which version of Go?
Which version of Windows?
How does it fail?

**Comment by gegogi** [comment]
Version of go source: 1.4.2
Version of Windows: Windows 8.1 64 bit ( Language: Korean )
Failure type:
The first test fails with 'path xxx not found' like message.
The error message is broken at the non-Latin word part.
Because of this error, I changed my Windows user name and
I cannot provide the precise error message at this time.
I will follow up with the reproduced message later.

**Comment by minux** [comment]
Dup of #3754.

Should be fixed by Go 1.5 where the toolchain is written in Go itself,
which doesn't have the bug.
