### ISSUE TITLE
time.Format invalid data

### ISSUE THREAD

**Issue by LukeMauldin** [golang/go#10297]
The program https://play.golang.org/p/RJP1ytiDi8 outputs `08:00 -0456`.  I don't understand how it returns `-0456` for a time zone offset.  Looks like a bug to me.

**Comment by minux** [comment]
Timezone depends on the date, according to 2015b version of tzdata:
# Zone  NAME            GMTOFF  RULES   FORMAT  [UNTIL]
Zone America/New_York   -4:56:02 -      LMT     1883 Nov 18 12:03:58
                        -5:00   US      E%sT    1920
                        -5:00   NYC     E%sT    1942
                        -5:00   US      E%sT    1946
                        -5:00   NYC     E%sT    1967
                        -5:00   US      E%sT

New York uses a -4:56:02 local mean time before 1883 Nov 18, in your
example, the date (Jan 1st 0000) is way earlier than year 1883.

It's working as intended.
