### ISSUE TITLE
encoding/base64: Decode input errors are vague

### ISSUE THREAD

**Issue by epelc** [golang/go#10290]
`encoding/base64` decoder input errors are very vague. They only give you a character number while if you look at the code there are comments stating the true reason for each error. Also perhaps if you don't want to return more specific errors you could add the character that was invalid instead of just the number.

Example from http://golang.org/src/encoding/base64/base64.go
![image](https://cloud.githubusercontent.com/assets/5204642/6899621/c402eb98-d6cf-11e4-8da6-37faffc4f851.png)

You end up with an error message like the following
```
illegal base64 data at input byte 76
```
But it'd be a lot nicer if we knew why it was illegal.

Please let me know if I should put this on the forums. The issue guidelines don't say anything about requests/suggestions for improvements.

**Comment by bradfitz** [comment]
Sorry, I don't think we can fix this at this point as a result of https://golang.org/doc/go1compat

And the CorruptInputError underlying type is just an int64, so there's no place to add extra information.

**Comment by epelc** [comment]
@bradfitz Thanks I forgot about go1 compatibility. Are you guys keeping track of these types of things for go2 anywhere?

**Comment by bradfitz** [comment]
Just added the `go2` label to this bug.
