### ISSUE TITLE
defer/recover statement unable to alter return values

### ISSUE THREAD

**Issue by nhorman** [golang/go#10299]
go's defer and recover actions don't operate as expected.  The example here:
https://golang.org/doc/effective_go.html

```
// Compile returns a parsed representation of the regular expression.
func Compile(str string) (regexp *Regexp, err error) {
    regexp = new(Regexp)
    // doParse will panic if there is a parse error.
    defer func() {
        if e := recover(); e != nil {
            regexp = nil    // Clear return value.
            err = e.(Error) // Will re-panic if not a parse error.
        }
    }()
    return regexp.doParse(str), nil
}
```

When the above code executes, regexp is set to nil inside the defer function, but the value returned from Compile is non-nil.  Its as if changes made in the deferred function are discarded.

Note, the above is the example from the documentation that I based my test case on.  I used the above example to write the lock testing code below, which is where I actually found this issue:

```
func isLocked(m *sync.Mutex) (locked bool) {
     locked = true

     defer func() {
          if r := recover(); r != nil {
                glog.Infof("Mutex is unlocked\n")
                locked = false
           }
      }()

      m.Unlock()
      if (locked == false) {
          glog.Infof("Mutex is locked\n")
           m.Lock()
       }

      return
}
```

I understand the above code is racy, but I'm limiting its use to a single thread for the purposes of testing the code.  In this code, if I call m.Unlock() on an already unlocked mutex I see both the "Mutex is unlocked" and the "Mutex is locked" message in series.  This indicates that the assignment of locked to false is being discarded on exit from the deferred function, and callers will only ever see a return code of true from this.  That seems to be in conflict with the documentation, and just plain broken, as the deferred function clearly has visibility to the locked variable, but writes are silently discarded.

**Comment by ianlancetaylor** [comment]
Please provide a standalone test case, ideally on play.golang.org, that shows the problem.

**Comment by Wessie** [comment]
This does not seem to be a `defer`/`recover` problem, but rather a `sync.Mutex` bug (or documentation problem). 

As it is right now the mutex will become locked before panicking, a subsequent call to `Unlock` will then unlock it again. While the panic for unlocking an unlocked mutex is documented, the behavior seen here is not.

See this [playground](http://play.golang.org/p/wTGL6-C8et) for an example, and the [source](http://golang.org/src/sync/mutex.go?s=2137:2183#L89) for the details.

**Comment by cespare** [comment]
If a `sync.Mutex` has decided that it has been misused enough to issue a runtime panic, all bets are off at that point and the mutex should no longer be used. (I think the same is true for `sync.WaitGroup` if the counter goes negative.) Maybe a documentation change to specify that such values should not be reused after panic would be good.

I think you would need to implement your own mutex if you want a trylock.

**Comment by ianlancetaylor** [comment]
@Wessie you seem to be talking about a completely different problem than the one that @nhorman described when opening this issue.  I don't think that what you are describing is a bug.

**Comment by ianlancetaylor** [comment]
Oh, OK, I see the connection now, sorry.

If the problem is that unlocking an unlocked mutext, and then continue to use it, yields unpredictable behaviour of the mutex, then I don't think this is a bug.

**Comment by minux** [comment]
@nhorman, I've created a playground snippet based on your
code example.
http://play.golang.org/p/qOlnQiY2CC

I think there is some misunderstanding about the semantics
of panic/recover here.

When a function panics, no matter whether the panic is recovered
or not, the function will not continue to execute, so no matter
what happens, the body of the if block will not be reached.

It's working as intended.

Regarding the double unlock issue, I agree with others' opinion
that this is simply invalid usage and the behavior is undefined.
No docs change is necessary.
