### ISSUE TITLE
website: missing FreeBSD 1.4.2 binary release

### ISSUE THREAD

**Issue by tpng** [golang/go#10293]
As stated by Andrew in the [1.4.2 announce post](https://groups.google.com/forum/#!topic/golang-announce/JT1jOsxZ2Ow), the binary release should be available a few days after the 1.4.2 release.
Did we just forget to include it at a later time or are there any issues blocking the binary release?

**Comment by bradfitz** [comment]
No, I think Andrew just got busy, forgot, and then he left on a 6 week vacation.

**Comment by andrewaustin** [comment]
There is still no 1.4.2 FreeBSD release available at https://golang.org/dl/, but there is a 1.4.3 FreeBSD release (as well as 1.5 and 1.5.1). Perhaps this should be closed?
