### ISSUE TITLE
spec: Interface method specifiers

### ISSUE THREAD

**Issue by aubble** [golang/go#10291]
The spec says this: https://golang.org/ref/spec#MethodSpec

An interface type specifies a method set called its interface. A variable of interface type can store a value of any type with a method set that is any superset of the interface. Such a type is said to implement the interface. The value of an uninitialized variable of interface type is nil.

InterfaceType      = "interface" "{" { MethodSpec ";" } "}" .
MethodSpec         = MethodName Signature | InterfaceTypeName .
MethodName         = identifier .
InterfaceTypeName  = TypeName .

Shouldn't the MethodSpec be equal to (MethodName Signature) | InterfaceTypeName?

Because that implies that you can have a MethodName next to a InterfaceTypeName and it will be valid? But having the parentheses means that those are grouped together, thus you either get InterfaceTypeName or MethodName + Signature.

**Comment by griesemer** [comment]
Per http://golang.org/ref/spec#Notation, in EBNF the "or" operator "|" binds less strong than its Alternatives. So:

MethodSpec = MethodName Signature | InterfaceTypeName .

is the same as:

MethodSpec = (MethodName Signature) | InterfaceTypeName .

Or in other words, parentheses are not needed in this case.
