### ISSUE TITLE
build: linux/arm64 broken

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10302]
The linux/arm64 port has been broken since March 20. Now that I have access to hardware, here is a minimal reproduction:

```
package main
    
func main() {    
        text := "abc"
        s := &s{text}
        println(text[2] == s.text[2])
}

type s struct {
        text string
}
```

On linux/arm64 (tip f8fd5502ecdb), bootstrapped with 11dba2ec2d8f, this prints false.

/cc @davecheney @4ad @rsc

**Comment by 4ad** [comment]
This is issue 10253.

**Comment by 4ad** [comment]
Not sure how to merge issues, should I close this one?
