### ISSUE TITLE
cmd/go: package names are printed to stderr instead of stdout on build

### ISSUE THREAD

**Issue by joegrasse** [golang/go#10309]
When passing the -v flag to the go build command, package names are printed to stderr instead of stdout.

Offending code line.
https://github.com/golang/go/blob/9d0239771a2ddd77be0ba64c2782e1328a378190/src/cmd/go/build.go#L845

**Comment by ianlancetaylor** [comment]
Printing -v output to stderr makes it work well when any errors occur during compilation, or when using -x.  Why is this a bug?

**Comment by joegrasse** [comment]
I see what you are saying. When compiling multiple packages, if a package has a compilation error you would like to know which package it is for. However, I believe this is already handled, because if you do ```go build``` and there is an error you will see the following output.
```
E:\gowork\src\github.com\joegrasse\passtest>go build
# github.com/joegrasse/passtest
.\passtest.go:26: syntax error: unexpected }
```
Notice the package name printed once vs the package name printed twice below with the -v flag.
```
E:\gowork\src\github.com\joegrasse\passtest>go build -v
github.com/joegrasse/passtest
# github.com/joegrasse/passtest
.\passtest.go:26: syntax error: unexpected }
```

My issue is when there are no "true" errors you still have output to stderr with the -v option. Which in turn leads to issue GoClipse/goclipse#119.

**Comment by ianlancetaylor** [comment]
I agree that the error message tells you which package failed, but it's still convenient to not have strange interleaving in the output.  Plus, -x.

I don't understand why goclipse is passing -v at all.  This doesn't seem like a strong reason to change the way the go tool works.

**Comment by joegrasse** [comment]
I guess I would ask why -x is sent to stderr as well. Why not stdout for that, since it is information and not errors?

**Comment by ianlancetaylor** [comment]
OK, forget -x.  We can agree that -x and -v should use the same rule.

It's still convenient to not have strange interleaving in the output.

I don't see the fact that goclipse decides to pass -v as a compelling reason to change how the tool behaves, because I don't know a reason why goclipse should do that.

**Comment by robpike** [comment]
Working as intended. Diagnostic output goes to stderr; that's what stderr is for.
