### ISSUE TITLE
cmd/dist: default timeout value is too short for weaker CPUs to compute and pass all std tests.

### ISSUE THREAD

**Issue by mortdeus** [golang/go#10314]
I have encountered an issue where ./all.bash returns a status indicating the build has failed to pass runtime/map_test.go because the test spends more than 2 mins executing code within testsCurrentReadsAfterGrowth() func on my Intel Atom n455e CPU. (1.67 GHz 64-bit single core cpu w/ 2 hyperthreads, no AES, 1GB DDR3, very lightweight Arch operating system with the latest kernel from the official Arch repo.). 

I am currently testing to see if changing the default timeout from 2 mins to 5 mins will give my CPU enough time to finish the heavy computation.

**Comment by mortdeus** [comment]
Yeah, setting it higher worked. It took dist test 147 seconds to run the tests found in the runtime pkg on my system.

**Comment by mikioh** [comment]
Please open a separate issue if you think TestConcurrentReadsAfterGrowth{,Reflect} in runtime/map_test.go need some fix.
