### ISSUE TITLE
gccgo fails on PPC crosscompilation with cgo

### ISSUE THREAD

**Issue by samm-git** [golang/go#10315]
I am trying to use gccgo5 for the cross-compilation. After successfully resolved issues in the #10310 i am able to build ppc projects for the PPC on the amd64 machine. Only broken part is CGO cross compilation for the GO/C source code. I think that problem is in incorrect dwarf parsing, but not sure yet. 

To enable it i set CGO_ENABLED=1 and CC/CXX to the correct cross-compiler binaries.
Below is an illustration, I am using [hello-cgo](https://github.com/kyleconroy/hello-cgo):

```
builder@5dc5de8d9844:~/hello-cgo$ go build -x
WORK=/tmp/go-build093303459
mkdir -p $WORK/_/opt/turris/hello-cgo/_obj/
cd /opt/turris/hello-cgo
CGO_LDFLAGS="-g" "-O2" /opt/turris/x-tools/x86_64-turris-linux-gnu/libexec/gcc/x86_64-turris-linux-gnu/5.0.0/cgo -objdir $WORK/_/opt/turris/hello-cgo/_obj/ -gccgo -- -I $WORK/_/opt/turris/hello-cgo/_obj/ hello.go
# _/opt/turris/hello-cgo
./hello.go:10:2: call of non-function C.hello
```
I also tried to run cgo directly, using `go tool cgo hello.go`. It fails with the same message and leaves `_obj/_cgo_.o` file which looks like correct ppc binary. According to the code it looks like object compiles correctly, but later cgo binary fails to find corresponding DWARF records and fail. I also created gist with `-debug-gcc` output: https://gist.github.com/samm-git/cc580ad8af5f7941977b

 Could you please help me with this issue, or at least point to the right direction?

**Comment by mwhudson** [comment]
It's there already https://gcc.gnu.org/viewcvs/gcc/trunk/libgo/go/debug/elf/file.go?revision=221698&view=markup#l535 (the mirror you linked to seems to be ~3 weeks out of date)

**Comment by samm-git** [comment]
Thank you! Sorry, already found it. Works fine with the latest snaphot.
