### ISSUE TITLE
x/build: missing trybot build log

### ISSUE THREAD

**Issue by josharian** [golang/go#10311]
trybot run: http://farmer.golang.org/try?commit=238dee09

The build log for the openbsd-386-gce56 failure yields a 404. The url looks correct.

**Comment by bradfitz** [comment]
I don't understand.

That tryrun is over, so the status URL has expired.  But the failure log is not a 404.

If I look at the comment it posted to

https://go-review.googlesource.com/#/c/7593/

I see:

> This change failed on openbsd-386-gce56:
> See https://storage.googleapis.com/go-build-log/238dee09/openbsd-386-gce56_701746e8.log

And that URL works.

What do you want me to do here?

**Comment by josharian** [comment]
Drat. The status URL expiring has foiled my lazily written bug report.

> This change failed on openbsd-386-gce56:
> See https://storage.googleapis.com/go-build-log/238dee09/openbsd-386-gce56_701746e8.log
> And that URL works.

The farmer.golang.org page had build log link url of the form http://farmer.golang.org/logs?name=plan9-386-gcepartial&rev=fb4b46738cfc0adf4e02781c25603ca16764cdbf&st=0xc208cf1860. That was the URL that was broken.

Given that all the evidence is gone, I guess I'll close this until it happens again.

**Comment by bradfitz** [comment]
I suppose the more general bug here is that any coordinator URL should either work or redirect somewhere useful.

We could just write out the state to GCS when done (named the same as the URL) and if the state isn't in memory, redirect to the GCS text file URL.

/cc @crawshaw

**Comment by bradfitz** [comment]
Closing in favor of broader #13076
