### ISSUE TITLE
golang.org: example times out on homepage

### ISSUE THREAD

**Issue by gumgl** [golang/go#10317]
One of the examples on the http://golang.org/ homepage times out.

![golang-bug](https://cloud.githubusercontent.com/assets/4989587/6968491/4a2f2986-d935-11e4-9181-29d40ac3c4a5.png)
Initially posted to [golang-nuts](https://groups.google.com/forum/#!topic/golang-nuts/uHZQ28VhRLA).

**Comment by cespare** [comment]
Perhaps without segmented stacks the example is too costly for the playground environment?

In any case, that example should be modified to remove the reference to segmented stacks.

**Comment by rsc** [comment]
Bad cached result. Fixed.

**Comment by minux** [comment]
Also note that Go tip, that program no longer
mentions segmented stacks.

http://tip.golang.org/doc/play/peano.go
