### ISSUE TITLE
x/build: leave farmer page for successful runs

### ISSUE THREAD

**Issue by josharian** [golang/go#10313]
CL 7360 started trybot run http://farmer.golang.org/try?commit=26677cd2. That farmer page was present for a while but now (30 minutes later) says "TryBot result not found (already done, invalid, or not yet discovered from Gerrit). Check Gerrit for results.". I presume that this is because the trybots were happy(?). I'd rather leave up a page that says that.

**Comment by bradfitz** [comment]
The coordinator is stateless. It keeps some state in memory, but only a rolling window for the past N builds as a debug/curiosity mechanism. If it crashes or is restarted, it regains its state from Gerrit and build.golang.org. I'm not sure how such a feature would be implemented.

The /try?commit=... URL is for people bored and interactively watching their try runs. The state gets stored back in Gerrit as a comment and -1/+1 vote as the TryBot-Success label.

I suppose I could make unknown things just redirect back to the issue on Gerrit?

Suggestions?

**Comment by josharian** [comment]
> interactively watching their try runs.

This was me.

> I suppose I could make unknown things just redirect back to the issue on Gerrit?

SGTM

**Comment by bradfitz** [comment]
Nowadays we have all the history uploaded to datastore so on that URL (http://farmer.golang.org/try?commit=26677cd2) we could look up `26677cd2` and at least say "That passed, here's the Gerrit link."

/cc @toothrot

**Comment by dmitshur** [comment]
It looks like there's agreement to do even better and keep entire logs accessible in issue #34119. I'll close this 2015 issue in favor of that one. (@toothrot has already linked it there, so we can find it easily.)
