### ISSUE TITLE
image/draw: test crashes on linux/arm64

### ISSUE THREAD

**Issue by mikioh** [golang/go#10325]
https://go.googlesource.com/go/+/33448d963caf0d66f042e738fe733c66796742b2 enables to build on linux/arm64, and so we are able to see this issue.
```
ok  	image	0.488s
ok  	image/color	0.055s
?   	image/color/palette	[no test files]
signal: segmentation fault (core dumped)
FAIL	image/draw	0.395s
ok  	image/gif	0.163s
?   	image/internal/imageutil	[no test files]
ok  	image/jpeg	0.556s
ok  	image/png	0.137s
```
See http://build.golang.org/log/7ceea9275e0c0b5fa62c4971612475023e24f225.

**Comment by josharian** [comment]
Dup of #10304?

**Comment by mikioh** [comment]
Yup, thanks.
