### ISSUE TITLE
runtime: refresh MemStats for new GC

### ISSUE THREAD

**Issue by aclements** [golang/go#10323]
We need to change how we update some of the fields of memstats to reflect the new state of the world with the concurrent collector. At least pause_total_ns, pause_ns, and pause_end are no longer quite right.

(We don't have to fix this right now. I'm filing an issue just so we don't lose track of it.)

@RLH

**Comment by mkobetic** [comment]
There seems to be something seriously wrong with the MemStat.PastEnd values on Linux. On MacOSX they seem to be the same precision and semantics as MemStat.LastGC, but on Linux they seem to be nanosecond precision but not in epoch time, but since the host started. If I run http://play.golang.org/p/9xM4uvMs6m on linux I get this result:
```
$ ./test
1428348851168577701 2015-04-06 19:34:11.168577701 +0000 UTC
1649614797954478 1970-01-20 02:13:34.797954478 +0000 UTC
1649614798059819 1970-01-20 02:13:34.798059819 +0000 UTC
$ uname -a
Linux ... 3.18.8-031808-generic #201502271935 SMP Sat Feb 28 00:36:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.4.2 linux/amd64
$ uptime
 19:34:58 up 19 days,  2:14,  1 user,  load average: 3.79, 2.90, 2.40
```

**Comment by rsc** [comment]
@aclements worth looking at soon?

**Comment by rsc** [comment]
Updating the subject. In addition to stats that are flat wrong, we need to revise MemStats as needed to expose the information we want people to be able to extract from running programs in use cases like monitoring of GC performance. At the least I think we'd want some running totals and the overall % GC usage reported by the GODEBUG=gctrace=1 mode.

**Comment by aclements** [comment]
@mkobetic, I assume you mean PauseEnd. It looks like that was true in Go 1.4, so this isn't a new bug, but it is a bug. On Linux we use CLOCK_MONOTONIC for that field, which is where the funny number it coming from (on Darwin we use gettimeofday). We should use gettimeofday for both LastGC and PauseEnd. I'll send a CL.

**Comment by mkobetic** [comment]
Yes I meant PauseEnd, sorry about the typo.

**Comment by aclements** [comment]
> In addition to stats that are flat wrong, we need to revise MemStats as needed to expose the information we want people to be able to extract from running programs in use cases like monitoring of GC performance.

Do we want to take this opportunity to make MemStats more flexible? Any public field we add may lock us in or force us to synthesize less than meaningful values when the memory manager's design changes in the future. There's a tension between exposing more information for better performance debugging and exposing as little as possible lest we violate compatibility in the future. Compatibility aside, ideally we would expose enough information to reconstruct the gctrace line programmatically.

I can imagine various more flexible APIs that would let a caller dynamically detect what information is available. It could be interface-based, map-based, or even reflection-based.

**Comment by nightlyone** [comment]
Another option could be to exempt such internal information explicitly from the Go1 contract, because it simply exposes too much internal detail. Otherwise it might converge to report misleading data after more radical GC changes.

As a developer I prefer breaking on compile over misleading at runtime.
