### ISSUE TITLE
iostest.bash: don't restart phones by default

### ISSUE THREAD

**Issue by josharian** [golang/go#10333]
It's delightful that `iostest.bash` wraps up everything needed to run `all.bash` on an iOS device. I was rather unpleasantly surprised, though, when the first thing it did was restart my phone.

Perhaps this is needed for dedicated builders, but for personal devices and manual runs, it's not super friendly and certainly unexpected. I'd suggest controlling this by an environment variable or some such.

**Comment by crawshaw** [comment]
Seems reasonable. Are there any environment variables to tell us we are running under the builder? If so it could be conditioned on it.

**Comment by minux** [comment]
no, there is no environment variable for builders, and I believe
that's a good thing. We don't want tests to do things differently
just because it's running on the builders.

For this case, however, perhaps we should add a command line
flag to iostest.bash. Our builder infrastructure should be able to
pass a flag.

**Comment by crawshaw** [comment]
SGTM. We already have to set a flag to tell the builder to use "./iostest.bash". We can ask it to use "./iostest.bash -restart" instead.

**Comment by josharian** [comment]
I'd like to fix this, but I can't find the relevant builder code. Is it not in golang.org/x/build, or am I blind?

**Comment by crawshaw** [comment]
There's no code to fix. Right now the builder is run with a flag telling it to use iostest.bash. I can add -restart to that if you change iostest.bash

One day I will have OS X buildlets, then there will be code to change. But right now I'm distracted by work that needs to be completed before the 1.5 freeze.

**Comment by josharian** [comment]
That explains it. :) CL soon.
