### ISSUE TITLE
encoding/json: unnecessary allocation in (*scanner).error

### ISSUE THREAD

**Issue by toffaletti** [golang/go#10335]
I've got a long running process where `pprof --alloc_objects` reported this:
```
11288877697 of 18066163372 total (62.49%)
Dropped 1073 nodes (cum <= 90330816)
Showing top 40 nodes out of 301 (cum >= 135464561)
      flat  flat%   sum%        cum   cum%
 861225002  4.77%  4.77% 1518495517  8.41%  encoding/json.(*scanner).error
 561339051  3.11%  7.87%  561339051  3.11%  reflect.Value.MapIndex
 554128561  3.07% 10.94%  554128561  3.07%  reflect.New
 479534186  2.65% 13.60%  479534186  2.65%  strconv.quoteWith
```

The `encoding/json.(*scanner).error` surprised me and I went digging thinking the process was handling lots of invalid JSON. What I think is going on is the scanner allocates several temporary objects for every JSON value even when the JSON is valid just in case the input stream ends on the next step.

`stateEndTop ` is calling `(*scanner).error` which does:

```
s.err = &SyntaxError{"invalid character " + quoteChar(c) + " " + context, s.bytes}
```

and `quoteChar` does:

```
s := strconv.Quote(string(c))
return "'" + s[1:len(s)-1] + "'"
```

I made a really nasty hack to get rid of the allocations in the common case. I present it in shame:

```
+var commaErr = &SyntaxError{"invalid character ',' after top-level value", 0}
+var braceErr = &SyntaxError{"invalid character '}' after top-level value", 0}
+var brackErr = &SyntaxError{"invalid character ']' after top-level value", 0}
+
 // error records an error and switches to the error state.
 func (s *scanner) error(c int, context string) int {
    s.step = stateError
+   if context == "after top-level value" && s.bytes == 0 {
+       switch c {
+       // special cases - common avoid allocation
+       case ',':
+           s.err = commaErr
+           return scanError
+       case '}':
+           s.err = braceErr
+           return scanError
+       case ']':
+           s.err = brackErr
+           return scanError
+       }
+   }
    s.err = &SyntaxError{"invalid character " + quoteChar(c) + " " + context, s.bytes}
    return scanError
 }
```

**Comment by josharian** [comment]
Thanks! A few things:

* We can't accept patches via issues. To contribute code, please see golang.org/doc/contribute.html
* It seems like a better fix might just be to store `c` in the scanner in case it is needed.
* Are there any benchmarks that cover this code? What is the impact on them, running with `-benchmem`? You'll want to use [benchcmp](https://godoc.org/golang.org/x/tools/cmd/benchcmp) to compare them.

**Comment by toffaletti** [comment]
Thanks, I don't think that code is fit for contribution though. I will provide a benchmark to reproduce the issue as soon as I can isolate it.

**Comment by toffaletti** [comment]
The benchmark is pretty trivial, but reproducing the allocations seems to require unmarshalling into a struct. I wasn't able to reproduce using an empty interface.

I went to http://www.json.org/example.html got a large sample of a JSON object, pasted it into https://mholt.github.io/json-to-go/ to generate a struct. Then the benchmark is simply:

```
func BenchmarkJSON(b *testing.B) {
    var o Autogenerated
    for n := 0; n < b.N; n++ {
        for i := 0; i < 1000; i++ {
            err := json.Unmarshal([]byte(testJSON), &o)
            if err != nil {
                b.Fatal(err)
            }
        }
    }
}
```

```
$ benchcmp old.txt new.txt 
benchmark         old ns/op     new ns/op     delta
BenchmarkJSON     133828654     137355079     +2.64%

benchmark         old allocs     new allocs     delta
BenchmarkJSON     161100         63083          -60.84%

benchmark         old bytes     new bytes     delta
BenchmarkJSON     6981457       5524665       -20.87%
```

I wish I had more time to work on this and properly contribute a fix, but I unfortunately don't. Apologies, this is the best I can do right now.

**Comment by josharian** [comment]
No worries, and thanks, this is useful as-is.

**Comment by josharian** [comment]
Here's a smaller, self-contained benchmark for whoever looks at this. (Not me.) The newline in the byte slice is important.

```go
func BenchmarkIssue10335(b *testing.B) {
	b.ReportAllocs()
	var s struct{}
	j := []byte(`{"a":{
}}`)
	for n := 0; n < b.N; n++ {
		if err := Unmarshal(j, &s); err != nil {
			b.Fatal(err)
		}
	}
}
```

With the hack above:

```
benchmark               old ns/op     new ns/op     delta
BenchmarkIssue10335     1744          1028          -41.06%

benchmark               old allocs     new allocs     delta
BenchmarkIssue10335     10             4              -60.00%

benchmark               old bytes     new bytes     delta
BenchmarkIssue10335     432           288           -33.33%
```

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/8401

**Comment by potocnyj** [comment]
FWIW, I did a little experimentation with this yesterday and found that this input should also showcase the problem:

```
[]byte(`{"a":{ }}`)`
```

The newline in the input isn't the significant part, it's the fact that the two closing braces have no whitespace between them.

**Comment by josharian** [comment]
Thanks, @potocnyj. You're right. To reproduce, you need both whitespace (newline or space as you have it) as well as the two closing braces next to each other.

**Comment by bradfitz** [comment]
I retracted my change.

**Comment by peterwald** [comment]
@josharian 
Pushed a fix: https://go-review.googlesource.com/#/c/9074/
