### ISSUE TITLE
spec: bounded type selectors

### ISSUE THREAD

**Issue by aubble** [golang/go#10341]
Spec (https://golang.org/ref/spec#Method_declarations): "The receiver is specified via an extra parameter section preceeding the method name. That parameter section must declare a single parameter, the receiver. Its type must be of the form T or \*T (possibly using parentheses) where T is a type name. The type denoted by T is called the receiver base type; it must not be a pointer or interface type and it must be declared in the same package as the method. **The method is said to be bound to the base type and the method name is visible only within selectors for that type.**"

It says for that type, whereas according to http://golang.org/ref/spec#Selectors, it is also visible within pointers to the receiver base type. This is true whether the method has a pointer or a value receiver.  It's being misleading, unless selectors on both `T` and `*T` values are considered selectors for `T`, which should be stated more clearly if it's the case. If it isn't the case, then the spec is incorrect and needs to be fixed.

**Comment by aubble** [comment]
@griesemer if this gets merged, do I get my name in the contributors file or do I have to be one to submit the actual code?

**Comment by griesemer** [comment]
@aubble No, unless you sign the CLA for legal reasons and submit a change, you're not going to be in the contributors file.

You're indirectly referred to through the issue that's mentioned in that change. I'm happy to mention your name/e-mail address in the change as the person who found the issue if you like. But again, you probably should sign the CLA so that there's no legal issue we the Go team using your e-mail address and name. Thanks.

**Comment by aubble** [comment]
@griesemer alright I signed it, my name is Anmol Sethi and my email is anmol@aubble.com. thanks :D

**Comment by griesemer** [comment]
Would you like me to mention your e-mail address explicitly in the commit
message? (This will make it visible to the public).

Otherwise I'm just going to say:

"Inconsistency identified by Anmol Sethi (aubble@github)."

- gri

**Comment by aubble** [comment]
@griesemer well I mean it will be public anyway in the contributors file so its fine. explicit is okk

**Comment by griesemer** [comment]
done. I will submit once prior pending spec changes are ok'ed.
- gri

**Comment by aubble** [comment]
sweet now I have something to tell my grandchildren.
