### ISSUE TITLE
builder: linux-arm64-canonical flaky

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10346]
Several recent linux/arm64 runs have failed with

```
##### ../test
Build complete, duration 2h0m0.001763s. Result: error: timed out after 2h0m0s
```

Each of the failures is during "../test". I tried one of the failing revisions, ```5242d2cef42c``` on the arm64 machine I have access to and 4/4 runs were successful:

```
##### ../test
695.65user 30.81system 2:04.53elapsed 583%CPU (0avgtext+0avgdata 755568maxresident)k
0inputs+1436256outputs (0major+7795389minor)pagefaults 0swaps

##### ../test
687.16user 30.66system 2:04.03elapsed 578%CPU (0avgtext+0avgdata 768040maxresident)k
0inputs+1436176outputs (0major+7814195minor)pagefaults 0swaps

##### ../test
696.69user 30.89system 2:04.21elapsed 585%CPU (0avgtext+0avgdata 745240maxresident)k
0inputs+1436240outputs (0major+7800480minor)pagefaults 0swaps

##### ../test
685.67user 31.66system 2:02.67elapsed 584%CPU (0avgtext+0avgdata 776032maxresident)k
0inputs+1436192outputs (0major+7813546minor)pagefaults 0swaps
```

Other times are very similar between linux-arm64-canonical and the test machine I have (../test/bench/shootout ~50s, ../../doc/codewalk ~9s, runtime ~47s), so I don't think we are anywhere near the 2 hour timeout. There is something specific about that machine I cannot replicate.

/cc @4ad @minux

**Comment by 4ad** [comment]
The machine uses a buggy kernel. The remedy is to upgrade the kernel. Because we don't really "own" the machine, we can't do that.

The real solution is to have builder 100% dedicated to the Go project that we can administer as we like.

**Comment by davecheney** [comment]
Yes, what Aram said. I'll open a ticket to the th machine rebooted.

For context this kernel leaks unkillble test/64bit processes.

**Comment by davecheney** [comment]
The kernel on the affected machine has been upgraded.
