### ISSUE TITLE
tools/oracle: referrers "failed to scan import graph for workspace"

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10347]
Trying to get referrers for os.Pipe in src/os/exec/exec.go:L467:

```
Package "github.com/crawshaw/sprite/ui": /Users/crawshaw/src/github.com/crawshaw/sprite/ui/label.go:2:2: expected 'package', found 'EOF'.
Package "golang.org/x/talks/2014/gotham-context": found packages after (after.go) and before (before.go) in /Users/crawshaw/src/golang.org/x/talks/2014/gotham-context.
oracle: failed to scan import graph for workspace.
```

The errors are real, but none of the packages being considered have a dependency on it. I would expect oracle to try its best to show me referrers. In this case, what I actually wanted to see was other uses of os.Pipe() in the package I'm in, which oracle can do long before scanning other parts of my GOPATH.

**Comment by crawshaw** [comment]
In fact, my full GOPATH is apparently an extremely expensive load thanks to lots of cgo use. After fixing those errors it took 2 minutes for my laptop to produce the next error. This is not the sort of work oracle should be doing just to determine if an exported symbol is referenced in a package:

```
vim-go: /Users/crawshaw/Dropbox/src/github.com/go-gl/glfw/v3.0/glfw/clipboard.go:4:10: fatal error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
```

**Comment by alandonovan** [comment]
Now that the non-SSA/PTA queries are robust to type errors, I think the best thing to do is simply disable cgo preprocessing for these queries.  It'll make loading a lot faster (and more robust) when the dependencies use cgo, at some minor loss in precision at those parts of the program.

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/#/c/8493/

**Comment by alandonovan** [comment]
There are two bugs in this issue.  The second was fixed by the CL above. 
The first will be fixed by this change: https://go-review.googlesource.com/#/c/8498/
