### ISSUE TITLE
spec: bounded types

### ISSUE THREAD

**Issue by aubble** [golang/go#10340]
"The receiver is specified via an extra parameter section preceeding the method name. That parameter section must declare a single parameter, the receiver. Its type must be of the form T or *T (possibly using parentheses) where T is a type name. The type denoted by T is called the receiver base type; it must not be a pointer or interface type and it must be declared in the same package as the method. The method is said to be bound to the base type and the method name is visible only within selectors for that type." 

"func (p *Point) Length() float64 {
return math.Sqrt(p.x * p.x + p.y * p.y)
}

func (p *Point) Scale(factor float64) {

p.x *= factor
p.y *= factor
}
bind the methods Length and Scale, with receiver type *Point, to the base type Point."

Golang spec says this for https://golang.org/ref/spec#Receiver I'm confused on that it says that the methods are bound to the Point type? Shouldn't it be binded to *Point and not Point? Because the method set of Point is only methods declared with receiver Point, not *Point and therefore it is bounded. Yes you can call the function with a variable of type Point and not *Point, but thats syntactical sugar no? Its not like its actually part of the methods spec of Point? Only *Point? So why is it "bounded" to Point? It also says this "method name is visible only within selectors for that type." But for this its not, its only visible to *Point, not Point?

**Comment by stevenblenkinsop** [comment]
The problematic part of the spec specifically is where it says "the method name is visible only within selectors for [the receiver base type]". The method name is also visible within selectors for *pointers to* the receiver base type. This is true whether the method has a pointer or a value receiver. And them there's method promotion, which I'm not sure how it fits with the language used here.

**Comment by aubble** [comment]
Sorry, just had woken up. But you're right, thats the exact part that I find confusing.

**Comment by griesemer** [comment]
It could perhaps say:

... the method name is visible only within selectors _with_ that base type.

i.e., if the type is a pointer type *T, its base type would be T. But it's all a slippery slope. There's always a balance between making the spec reasonably clear vs "litigation-proof". The latter it is not.

**Comment by stevenblenkinsop** [comment]
Certainly the goal of the spec isn't to be infinitely precise. In the area of method dispatch, though, there's a lot of different concepts involved that don't really interact cleanly. Fixing the language around it isn't so much about making the spec more precise as it is about making it easier for people to make the right connections between the different parts.

**Comment by griesemer** [comment]
see #10341
