### ISSUE TITLE
Go test not including file named darwin.go

### ISSUE THREAD

**Issue by darraghjones** [golang/go#10351]
c:\Users\darragh\Documents\gocode\src\robbie>go version
go version go1.3.3 windows/amd64

When I run go test, it's complaining about Darwin being undefined:

````
c:\Users\darragh\Documents\gocode\src\robbie>go test
# robbie
.\robbie_test.go:60: undefined: Darwin
FAIL    robbie [build failed]
````

However it is defined in a file named darwin.go
If I rename darwin.go to d.go (or anything else) it works:

````
c:\Users\darragh\Documents\gocode\src\robbie>ren darwin.go d.go

c:\Users\darragh\Documents\gocode\src\robbie>go test
0xc082000430
PASS
ok      robbie  0.030s
````

**Comment by dominikh** [comment]
Update to Go 1.4 or later. Before Go 1.4, "darwin.go" would be treated identically to "foo_darwin.go", which is a build constraint on darwin, as described in http://golang.org/pkg/go/build/

**Comment by minux** [comment]
Yeah, there is behavior change in Go 1.4.

See http://golang.org/doc/go1.4#filenames

**Comment by darraghjones** [comment]
Thanks for the info.
