### ISSUE TITLE
mobile: android/arm build broken

### ISSUE THREAD

**Issue by hyangah** [golang/go#10358]
missing symbols _rt0_arm_android_lib

https://groups.google.com/forum/#!topic/golang-nuts/OSi2lPlF4O0

/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/toolexec /Users/mhawkins/src/go/pkg/tool/darwin_amd64/5l -o /var/folders/9s/_chc2vkd5l3d7251t9sflgk5759k1h/T/gomobile-bind-work-343039510/android/src/main/jniLibs/armeabi-v7a/libgojni.so -L $WORK -L /Users/mhawkins/Library/go/pkg/android_arm -extld=/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/arm-linux-androideabi-gcc -shared $WORK/command-line-arguments.a
# command-line-arguments
_rt0_arm_android_lib.ptr: _rt0_arm_android_lib: not defined
_rt0_arm_android_lib.ptr: undefined: _rt0_arm_android_lib
exit status 2

@crawshaw Probably related to https://go-review.googlesource.com/#/c/7692 and friends CLs?

**Comment by crawshaw** [comment]
Yes, it looks like cl/7692. I believe cl/8457 will eventually fix this, but there are some sticking points in that. I'll try to prepare an intermediate CL to fix the build.

**Comment by crawshaw** [comment]
(It's also a little distressing that we don't have tests for this, I'll try to get to that soon.)
