### ISSUE TITLE
silent failure of jpeg decoding

### ISSUE THREAD

**Issue by mtaran-google** [golang/go#10357]
* What version of Go are you using (go version)? go1.4.2 darwin/amd64
* What operating system and processor architecture are you using? Mac OS X 64-bit Intel
* What did you do?
    * Open [this jpeg](https://cloud.githubusercontent.com/assets/5050719/7009610/591bcca6-dc50-11e4-9b5d-36cef0c52b86.jpg) with `image/jpeg` (it was produced by a scanner, and it renders fine in browsers, Preview, etc.)
* What did you expect to see?
    * I expected Go to decode the image properly (i.e. white with black text).
* What did you see instead?
    * It decoded the image as a black rectangle, **with `err == nil`**

Repro locally with [this](http://play.golang.org/p/bdw6GKYuEU), though not on the playground.

**Comment by bradfitz** [comment]
Please try with Go tip. @nigeltao piped ~all the JPEGs on the Internet through image/jpeg and fixed a number of bugs recently.

**Comment by mtaran-google** [comment]
It worked at head of master! Are these fixes scheduled for release in 1.4.3 or will it only make it into 1.5?

**Comment by minux** [comment]
They will only be in Go 1.5.

**Comment by mtaran-google** [comment]
:'(

**Comment by bradfitz** [comment]
I'm not sure why that's sad. If this is affecting your work at Google, please mail the internal list for help and we can make sure tip image/jpeg is available to you immediately.
