### ISSUE TITLE
golang.org/x/tools/go/loader variable use checks should match the go tool's checks, but do not

### ISSUE THREAD

**Issue by glycerine** [golang/go#10354]
see https://github.com/mailgun/godebug/issues/14

**Comment by ianlancetaylor** [comment]
I'm pretty sure this is a dup of #8560.  Closing as dup.  If you want to reopen, please attach a test case here rather than pointing to a separate bug with several different comments and test cases.  Thanks.

**Comment by glycerine** [comment]
#8560 discusses the types library, but not the loader library, and it appears that they have different behavior. Consistent with @adonovan 's comments on  #8560, loader should be consistent too.

test case:

minimal test case small.go:
~~~
package main

func takeClosure(f func(i interface{})) {
}

func main() {
    var touchedInClosure string
    takeClosure(func(i interface{}) {
        switch i.(type) {
        case string:
            touchedInClosure = "I have been written to!"
        }
    })
}
~~~

Minimal loader program loader.go:
~~~
package main

import (
    "fmt"

    "golang.org/x/tools/go/loader"
)

func main() {
    var conf loader.Config
    conf.CreateFromFilenames("main", "small.go")
    _, err := conf.Load()
    fmt.Println(err)
}
~~~
results on small.go
~~~
$ go run loader.go
small.go:7:6: touchedInClosure declared but not used
couldn't load packages due to errors: main
~~~

**Comment by glycerine** [comment]
I don't seem to be able to re-open this myself, but please do if you concur that the issue is distinct and valid.

**Comment by glycerine** [comment]
opened https://github.com/golang/go/issues/10356 as a replacement. this ticket can stay closed.

**Comment by ianlancetaylor** [comment]
I would have reopened this one, but since you started a new one that is fine too.
