### ISSUE TITLE
cmd/cover: Add flag to select browser for go tool cover -html

### ISSUE THREAD

**Issue by ChimeraCoder** [golang/go#10365]
Currently, `go tool cover-html=coverage.out` appears to use `xdg-open` on Linux, which doesn't always select the right browser. Even if the `$BROWSER` environment variable is set, the cover tool doesn't always select the right browser. 

Figuring out the right browser to open is tricky, and even `xdg-open` doesn't always get this right. It'd therefore be helpful if the cover tool either accepts a flag to specify the browser, and/or perhaps use the `$BROWSER` environment variable if defined.

(This is related to #10259 in that the fix is probably the same, but it affects the coverage tool too.)

**Comment by robpike** [comment]
Seems to me the place to fix this is in xdg-open. I don't want our tools to have more configuration to support broken operating systems.

**Comment by cespare** [comment]
Note that in this case, `xdg-open` is not even picking a working browser for @ChimeraCoder, rendering `cover -html` unusable. (From discussion on IRC.)

**Comment by robpike** [comment]
Regardless, I think it's wrong to build os-specific hacks into every tool that wants to talk to a browser (or any other tool) when that is the os's responsibility. I can think of many ways to fix this that do not involve changing the cover tool.

**Comment by dherbst** [comment]
You can use the flag `-o` to Write out an HTML file instead of launching a web browser and then use the web browser to open the file.
	
`go tool cover -html=c.out -o coverage.html`

**Comment by ChimeraCoder** [comment]
@dherbst Thanks, this is a good workaround.
