### ISSUE TITLE
Question: why "go get" will trigger "go install sync and strconv" 

### ISSUE THREAD

**Issue by shrimpy** [golang/go#10367]
apologize in advance if this is not the right place to ask question.

* What version of Go are you using (go version)?

[go 1.4.2](https://storage.googleapis.com/golang/go1.4.2.windows-amd64.zip)

* What operating system and processor architecture are you using?
Windows server 2012 amd64
Windows 8.1 amd64

* What did you do?
try to resolve dependencies for this [file](https://github.com/shrimpy/gotry/blob/master/gotry.go)

1) download go 1.4.2 package in windows 8.1 machine
2) unzip the package, remove ".git, blog, doc and test" folders and zip the rest
3) login to windows server 2012 machine as administrator, upload package and config GOROOT global environment variable
4) login to windows server 2012 machine with different credential (not administrator), navigate to "src" folder and perform "go get gotry"

````
%gopath%
    |
    \--src
          |
          \--gotry
                  |
                  \-gotry.go
````

* What did you expect to see?
go will download all the dependencies and install to gopath

* What did you see instead?
go also try to perform write access to GOROOT, seeing below error (still able to build and run app)

````
go install sync: open D:\Program Files (x86)\go\1.4.2\pkg\windows_amd64\sync.a: Access is denied.
go install strconv: open D:\Program Files (x86)\go\1.4.2\pkg\windows_amd64\strconv.a: Access is denied.
````

#### Question:
1, why perform "go get" will trigger "go install sync and strconv"?
2. app seems still runs fine, what are the potential impact from above access denied error?

**Comment by minux** [comment]
It's because somehow the timestamp of the installed *.a become
older than the package sources. Check your installation procedure
if it preserves file timestamps.

PS: the issue tracker is for reporting bugs, please ask questions
on the golang-nuts mailing list. Thanks.
