### ISSUE TITLE
cmd/goimports: Running goimports removes an import path that should be preserved

### ISSUE THREAD

**Issue by jbuberel** [golang/go#10363]
The origin of this issue is a related bug filed under the LiteIde project:
https://github.com/visualfc/liteide/issues/278

In that issue, the user claims that running of the goimports tool on their working code results in an import path for github.com/stathat/go being removed incorrectly.

While the github.com/stathat/go packages does violate two conventions (it uses /go/ in the import path, and the name of the package does not match the name of the containing directory), the code works and appears to be technically correct.

To reproduce:
```
$ cd /Users/jbuberel
$ mkdir gi
$ export GOPATH=/Users/jbuberel/gi
$ echo $GOPATH
/Users/jbuberel/gi
$ go get golang.org/x/tools/cmd/goimports
$ ls -la ~/bin/goimports 
-rwxr-xr-x  1 jbuberel  eng  4947056 Apr  7 11:18 /Users/jbuberel/bin/goimports
$ mkdir src/myprogram
$ touch src/myprogram/mymain.go
```
**[ create source file mymain.go with these contents: ]**
```
package main

import (
    "fmt"
    "github.com/stathat/go"
    "golang.org/x/tools/present"
)

func main() {
    fmt.Println("Hello World")
    err := stathat.PostEZValue("test", "test", 1)
    if err != nil {
      fmt.Printf("Error: %v\n", err)
    }

    link := present.Link{
      Label: "Foobar",
    }

    fmt.Printf("L: %v\n", link.Label)
}
```
**[ now run the program, expecting it to fail ]**
```
$ go run src/myprogram/mymain.go 
src/myprogram/mymain.go:5:5: cannot find package "github.com/stathat/go" in any of:
	/usr/local/go/src/github.com/stathat/go (from $GOROOT)
	/Users/jbuberel/gi/src/github.com/stathat/go (from $GOPATH)
```
**[ manually goget stathat/go and tools/present and run the app ]**
```
$ go get github.com/stathat/go golang.org/x/tools/present
$ go run src/myprogram/mymain.go 
Hello World
L: Foobar
```
**[ forcibly remove stathat/go and tools/present ]**
```
$ rm -rf src/github.com/ src/golang.org/
$ go run src/myprogram/mymain.go 
src/myprogram/mymain.go:5:5: cannot find package "github.com/stathat/go" in any of:
	/usr/local/go/src/github.com/stathat/go (from $GOROOT)
	/Users/jbuberel/gi/src/github.com/stathat/go (from $GOPATH)
src/myprogram/mymain.go:6:5: cannot find package "golang.org/x/tools/present" in any of:
	/usr/local/go/src/golang.org/x/tools/present (from $GOROOT)
	/Users/jbuberel/gi/src/golang.org/x/tools/present (from $GOPATH)
```
**[ run goimports on the source, see that stathat/go import statement is removed, while tools/present was retained ]**
```
$ ~/bin/goimports src/myprogram/mymain.go 
package main

import (
	"fmt"

	"golang.org/x/tools/present"
)

func main() {
	fmt.Println("Hello World")
	err := stathat.PostEZValue("test", "test", 1)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	link := present.Link{
		Label: "Foobar",
	}

	fmt.Printf("L: %v\n", link.Label)
}
$ 
```

**Comment by bradfitz** [comment]
This would have worked if you hadn't done the "forcibly remove stathat/go" step.

Without the stathat files on disk in your GOPATH, goimports doesn't know what `stathat` before `stathat.PostEZValue` means, nor what `github.com/stathat/go` means.

The `present` import lives because goimports uses the heuristic that package name == directory name probably. But that heuristic fails for stathat. So if you want to do that, don't randomly delete things from your GOPATH.

Closing until there's something fixable. Feel free to re-open if I missed something.
