### ISSUE TITLE
cmd/pprof: SVG profile uses javascript from cyberz.org

### ISSUE THREAD

**Issue by alicebob** [golang/go#10375]
The .svg profile as generated by pprof's `web` command includes some Javascript from https://www.cyberz.org/projects/SVGPan/SVGPan.js

the file is linked here: https://github.com/golang/go/blob/5f8423844463b3b77588e46ea57f44d8b69a1564/src/cmd/pprof/internal/driver/driver.go#L628

I found it surprising to find pprof's SVG has external dependencies. Not just because of tracking reasons (I don't think cyberz.org need to know about my pprof usage), but also because it doesn't always work (e.g. working on a train).

Would it be possible to just include the javascript code verbatim in the .SVG, or otherwise to not include the external link by default?

**Comment by dr2chase** [comment]
I note that the referenced code has a claimed-to-be-BSD license -- source/binary use and redistribution allowed with attribution and NO-WARRANTY.

**Comment by rsc** [comment]
The old Perl pprof (in Go 1.3) copied this code directly into the generated SVG.
The port to Go erred by trying to avoid this duplication and use a link.
The Go version of pprof will be updated to do what the Perl pprof did.

Thank you for the report.

**Comment by alicebob** [comment]
Looks great. Thanks!
