### ISSUE TITLE
cmd/link: internal linking support for arm64

### ISSUE THREAD

**Issue by minux** [golang/go#10373]
when we have race detector support on arm64, we should have this.

**Comment by bradfitz** [comment]
When fixed, reenable test in https://go-review.googlesource.com/#/c/29360/2/src/cmd/dist/test.go

**Comment by williamweixiao** [comment]
We are investigating whether to enable internal linking for ARM64 but it seems that the real problem is race detector for ARM64 according to Minux's description. Could you please give me more information about the background?

**Comment by ianlancetaylor** [comment]
I think that @Minux meant is that in order to properly implement the race detector on ARM64, internal linking needs to be working.  Internal linking does not depend on the race detector.  It's the other way around.

**Comment by williamweixiao** [comment]
Thanks for the clarification!
So for ARM64, we have at least following work to do:
1) enable internal linking (mainly cgo internal linking, right?)
2) implement race detector based on fully enabled link

**Comment by williamweixiao** [comment]
I'm a little confused after glancing at link source code. I find that there is actually some basic support for ARM64 already. So I have 3 basic questions:
1. What's the advantage of internal link comparing to external link (i.e. invoking gcc to do link)?
2. Why internal link can work for race detector while external link can't?
3. Which parts are missing for ARM64? Just more relocation types?

**Comment by ianlancetaylor** [comment]
> What's the advantage of internal link comparing to external link (i.e. invoking gcc to do link)?

People can build Go programs without having to have a C compiler installed.

> Why internal link can work for race detector while external link can't?

Well, now that you ask that, I'm not sure.  Maybe I'm misunderstanding this.  @minux ?

> Which parts are missing for ARM64? Just more relocation types?

Probably, but possibly also support for generating required linker stubs.

**Comment by vielmetti** [comment]
This issue has been open for a while as unplanned, but it came up again in the context of https://github.com/bazelbuild/rules_go/pull/1574 where Bazel needs explicit instructions to invoke a linker to support building Go on arm64.

**Comment by williamweixiao** [comment]
Yes, we have finished a prototype development internally and will submit it in the next cycle.

**Comment by thanm** [comment]
Is there more to do here, or can this bug be closed out?

**Comment by cherrymui** [comment]
Yeah, I think this can be closed. Internal linking is supported on almost all our supported ARM64 ports, except windows/arm64. I don't think their is a strong need for internal linking on windows/arm64, and if necessary it can be its own issue.
