### ISSUE TITLE
cmd/cover: mishandles go: comments

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10378]
Running with current tip.
syscall/syscall_linux_amd64.go mistransformed from:

```
package syscall
const _SYS_dup = SYS_DUP2
func Getpagesize() int { return 4096 }
//go:noescape
func gettimeofday(tv *Timeval) (err Errno)
```

to:

```
package syscall
const _SYS_dup = SYS_DUP2
func Getpagesize() int  { GoCover_140.Count[
//go:noescape
0] = 1; return 4096 }
func gettimeofday(tv *Timeval) (err Errno)
```

Reproduce by running (on linux/amd64):

```
$ go test -c -cover syscall
# syscall
/tmp/go-build072163369/syscall/_test/_obj_test/syscall_linux_amd64.go:12: can only use //go:noescape with external func implementations
```

**Comment by robpike** [comment]
Infeasible. We need a way to manage comments in the AST. The current API of go/ast does not provide the hooks.

**Comment by dvyukov** [comment]
Let's keep it open with milestone Unplanned. This renders coverage unusable for important use cases.
@griesemer

**Comment by dvyukov** [comment]
I have to patch my syscall package to use coverage.
Probably we need to lang the change to syscall package (it merely reorders lines) in the context of this issue.

**Comment by dvyukov** [comment]
@griesemer Robert, isn't it go/printer bug? The comments are attached to function declaration, why it inserts comments in the middle of other statements?

**Comment by griesemer** [comment]
@dvyukov Some comments are attached, some are not. In general, the AST support for comments is not ideal. Comments inside functions are not attached at all. There's complex code in the printer that merges comments and code by comparing position information.

I haven't looked at the specifics of this problem. A generally correct solution (for all comments) is very difficult with the current AST. Maintaining function (and general declaration comments) should be doable. There's also the ast.CommentMap which may work for this problem.

The long-term solution is a new AST where all comments are attached to nodes.
