### ISSUE TITLE
Execute the following code lead to deadlock, could it be a BUG

### ISSUE THREAD

**Issue by wukehong** [golang/go#10376]
package main

import(
	"fmt"
)

func main(){
	cPop := make(chan int, 1)
	cPush := make(chan int, 1)
	cCache := make(chan int, 100)
	go func() {
		n := <-cPop
		fmt.Printf("Pop:%v\n", n)
	}()
	go func() {
		n := 1
		cPush <- n
		fmt.Printf("Push:%v\n", n)
	}()
	select {
	case cPop <- <-cPush:
		fmt.Printf("cPop <- <- cPush")
	case cPop <- <-cCache:
		fmt.Printf("cPop <- <- cCache")
	case cCache <- <-cPush:
		fmt.Printf("cCache <- <- cPush")
	}
}

**Comment by bradfitz** [comment]
Please stop opening duplicate issues. Use the mailing list to learn Go.
