### ISSUE TITLE
net/rpc: docs do not say that published type must be exported

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10379]
Looking at:
http://golang.org/pkg/net/rpc/
There are no mentions that a published type (type of object passed to Register) must be exported. There are only several mentions that _methods_ must be exported.

However, when I try to register a non-exported type, it fails with:
2015/04/08 18:06:45 rpc.Register: type driver is not exported

I guess it is a documentation issue.

**Comment by robpike** [comment]
The very first sentence of the package comment reads

	Package rpc provides access to the exported methods of an object across a
	network or other I/O connection.

**Comment by robpike** [comment]
Moreover,

**Comment by robpike** [comment]
Ah, I see the distinction. Will fix.
