### ISSUE TITLE
I found a bug of golang, return a deadlock errors when run the following code

### ISSUE THREAD

**Issue by wukehong** [golang/go#10371]
package main

import(
	"fmt"
)

func main(){
	c1 := make(chan int)
	c2 := make(chan int)
	go func(){
		c2<-1
	}()
	c1<- <- c2
	fmt.Println("Hello World")
}

//fatal error: all goroutines are asleep - deadlock!

**Comment by davecheney** [comment]
This is not a bug, the send to `c1` blocks because `c1` is unbuffered and there is no other goroutine waiting to read from `c1`.

**Comment by wukehong** [comment]
thanks

**Comment by bradfitz** [comment]
In the future, please use the golang-nuts@googlegroups.com mailing list for questions about Go when learning the language.
