### ISSUE TITLE
go/types: std lib tests don't consider +build tags

### ISSUE THREAD

**Issue by griesemer** [golang/go#10370]
Some of the std lib tests (e.g. solaris-amd64) are failing because +build tags are ignored. The tests should consider the build tags in place for the test binary (because it depends on gcimporter which sees the files as built by gc for the current platform).

**Comment by griesemer** [comment]
This is not super-important. Could be delayed to 1.7 or later w/o much repercussions.

**Comment by minux** [comment]
could we also consider exclude $GOROOT/src/*.go?
I usually place short repro files there when fixing bugs
because it's the most convenient place to place
test files. (see also https://golang.org/cl/14769 for a
similar issue wrt to go/build-ignored directories.)

**Comment by griesemer** [comment]
We already exclude files in `$GOROOT/src`. And go/importer (go/internal/gcimporter) is using go/build. I don't believe this is still a valid issue. Closing.

**Comment by griesemer** [comment]
I closed this prematurely. The issue is that go/types/stdlib_test.go's testTestDir function doesn't consider build tags I believe.
