### ISSUE TITLE
cmd/asm: document conditional jumps and branches

### ISSUE THREAD

**Issue by josharian** [golang/go#10385]
cmd/old6a and cmd/old8a document the conditional jumps, e.g.:

```
	{"JOS", LTYPER, x86.AJOS},  /* overflow set (OF = 1) */
	{"JO", LTYPER, x86.AJOS},   /* alternate */
	{"JOC", LTYPER, x86.AJOC},  /* overflow clear (OF = 0) */
	// lots more...
```

Let's bring that documentation with us to the new assembler, and cover the other platforms as well.

**Comment by josharian** [comment]
Let's also add docs to ARM.

It might also be helpful to pull in some of @minux's commentary from https://groups.google.com/forum/#!topic/golang-dev/MieNQcSAQNk about the carry flags, or link to it.

**Comment by robpike** [comment]
X86 is done, I believe.

"Add docs to ARM" is a fine thing to ask for, but what docs, and where? Also, putting this in the source for the assembler seems  like a poor choice.

Please explain what you want documented or close the issue.

**Comment by josharian** [comment]
I'll add docs next time I need them.
