### ISSUE TITLE
gofmt strange formatting of the last line within (long?) struct initialization

### ISSUE THREAD

**Issue by wojtek-t** [golang/go#10392]
gofmt is suggesting the following formatting of struct:

    kcfg := KubeletConfig{
 		Address:                        s.Address,	
 		AllowPrivileged:                s.AllowPrivileged,s.AllowPrivileged,
 		HostNetworkSources:             hostNetworkSources,
 		HostnameOverride:               s.HostnameOverride,
 		RootDirectory:                  s.RootDirectory,
 		ConfigFile:                     s.Config,
 		ManifestURL:                    s.ManifestURL,
 		FileCheckFrequency:             s.FileCheckFrequency,
 		HTTPCheckFrequency:             s.HTTPCheckFrequency,
 		PodInfraContainerImage:         s.PodInfraContainerImage,
 		SyncFrequency:                  s.SyncFrequency,
 		RegistryPullQPS:                s.RegistryPullQPS,
 		RegistryBurst:                  s.RegistryBurst,
 		MinimumGCAge:                   s.MinimumGCAge,
 		MaxPerPodContainerCount:        s.MaxPerPodContainerCount,
 		MaxContainerCount:              s.MaxContainerCount,
 		ClusterDomain:                  s.ClusterDomain,
 		ClusterDNS:                     s.ClusterDNS,
 		Runonce:                        s.RunOnce,
 		Port:                           s.Port,
 		ReadOnlyPort:                   s.ReadOnlyPort,
 		CadvisorInterface:              cadvisorInterface,
 		EnableServer:                   s.EnableServer,
 		EnableDebuggingHandlers:        s.EnableDebuggingHandlers,
 		DockerClient:                   dockertools.ConnectToDockerOrDie(s.DockerEndpoint),
 		KubeClient:                     client,
 		MasterServiceNamespace:         s.MasterServiceNamespace,
 		VolumePlugins:                  ProbeVolumePlugins(),
 		NetworkPlugins:                 ProbeNetworkPlugins(),
 		NetworkPluginName:              s.NetworkPluginName,
 		StreamingConnectionIdleTimeout: s.StreamingConnectionIdleTimeout,
 		TLSOptions:                     tlsOptions,
 		ImageGCPolicy:                  imageGCPolicy,imageGCPolicy,
 		Cloud:                          cloud,
		NodeStatusUpdateFrequency: s.NodeStatusUpdateFrequency,
 	}

The last line (NodeStatusUpdateFrequency) formatting seems pretty strange.

For the reference see:
https://github.com/GoogleCloudPlatform/kubernetes/pull/6620

cc @fgrzadkowski @gmarek @jszczepkowski

**Comment by josharian** [comment]
I think that this is working as intended--when there are significant length differences between subseqeuent fields, gofmt doesn't attempt to align them. You can boil this frog slowly, but not quickly:

```go
package main

var a = A{
	Long:                             1,
	LongLong:                         1,
	LongLongLong:                     1,
	LongLongLongLong:                 1,
	LongLongLongLongLong:             1,
	LongLongLongLongLongLong:         1,
	LongLongLongLongLongLongLong:     1,
	LongLongLongLongLongLongLongLong: 1,
	Short: 1,
	LongLongLongLongLongLongLongLongLong: 3,
}
```

Leaving for @griesemer to confirm, though.

**Comment by griesemer** [comment]
This is working as intended.

If the ratio between previous entry length and current entry length passes a certain threshold, the "alignment block" is broken. The reason is that we don't a very long list of mostly short entries be dominated by the formatting of a single long entry (which may be on the "next page" on the screen). This is an admittedly simple heuristic, and probably could be improved, but it works mostly ok.

Something to work on for version 2 of gofmt.
