### ISSUE TITLE
x/net/html/charset: Unclear license on w3c testdata

### ISSUE THREAD

**Issue by bz2** [golang/go#10398]
The README in html/charset/testdata states the tests come from the W3C but does not specify under which license go is reusing them, this makes redistribution in debian/ubuntu problematic.

Per:
<http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html>
We can just add a statement that the test files are licenced under the 3-clause BSD option.

Also, the link needs updating, the current is a 404 as it lacks /repository in the path.

So, README should be amended to something like:

"""
Test cases from:
<http://www.w3.org/International/tests/repository/html5/the-input-byte-stream/results-basics>

All *.html files copyright W3C and the following licence applies:
<http://www.w3.org/Consortium/Legal/2008/03-bsd-license.html>
"""

**Comment by ianlancetaylor** [comment]
http://golang.org/cl/8978
