### ISSUE TITLE
cmd/cover: undefined: unsafe.GoCover_700 in unsafe.GoCover_700.Count

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10408]
```
$ go test -run=none -coverpkg=std index/suffixarray
```
fails with:
```
_testmain.go:2037: undefined: unsafe.GoCover_700 in unsafe.GoCover_700.Count
_testmain.go:2037: undefined: unsafe.GoCover_700 in unsafe.GoCover_700.Pos
_testmain.go:2037: undefined: unsafe.GoCover_700 in unsafe.GoCover_700.NumStmt
```

**Comment by robpike** [comment]
A much faster version:

go test -coverpkg unsafe reflect

The problem is that code like this is generated in testmain.go:

	coverRegisterFile("unsafe/unsafe.go", _cover143.GoCover_700.Count[:], _cover143.GoCover_700.Pos[:], _cover143.GoCover_700.NumStmt[:])

Something needs to tell go test that there is no unsafe package being built even if we ask for it.
