### ISSUE TITLE
Package time : add 1 month can sometimes add 2 months

### ISSUE THREAD

**Issue by eclivus** [golang/go#10401]
Hello,

This might not e related to Go itself, but I noticed that when incrementing a date month by month go sometimes leaps a month.

```go
package main

import "fmt"
import "time"

func main() {
		date := time.Date(2013,time.January,31,23,59,59,0,time.UTC)
		fmt.Println(date.String())
		date = date.AddDate(0,1,0)
		fmt.Println(date.String())
}
```
Output:
2013-01-31 23:59:59 +0000 UTC
2013-03-03 23:59:59 +0000 UTC

Go version: go1.4.2 linux/amd64
System: Ubuntu 14.04.1
https://play.golang.org/p/5msN0bykp8

**Comment by robpike** [comment]
Working as intended. There is no February 31, so what happens here is reasonable. The behavior is even documented in the comment for AddDate - using almost exactly this example!

**Comment by minux** [comment]
What do you expect otherwise? 2013, 2, 31?
That's not valid date, so it's normalized to 20130303.

Working as intended.
