### ISSUE TITLE
gccgo: carriage returns in raw strings are not discarded

### ISSUE THREAD

**Issue by minux** [golang/go#10407]
```
// runoutput

package main
import "fmt"
func main() {
    fmt.Println("package main\nfunc main() { if `a\rb\r\nc` != \"ab\\nc\" { panic(42) }}")
}
```

According to the spec, http://tip.golang.org/ref/spec#String_literals,
The value of a raw string literal is the string composed of the uninterpreted (implicitly UTF-8-encoded) characters between the quotes; in particular, backslashes have no special meaning and the string may contain newlines. Carriage return characters ('\r') inside raw string literals are discarded from the raw string value.

Both gc and go/types conform to the spec.

**Comment by ianlancetaylor** [comment]
Fixed on tip by http://golang.org/cl/221660043 .
