### ISSUE TITLE
website: wrong version tag in install from source docs

### ISSUE THREAD

**Issue by aybabtme** [golang/go#10419]
The instructions at http://golang.org/doc/install/source, under "Fetch the repository", say to checkout `go1.4.1`. This should be `go1.4.2`.

**Comment by minux** [comment]
it should probably say release-branch.go1.4 instead.

unfortunately, we generally don't do doc changes to the releases branches.
(only fixes for critical bugs that cannot be worked around are ported
to release branch.)

**Comment by ianlancetaylor** [comment]
I don't think this is going to be fixed at this point.

CC @adg in the hopes of finding out why it happened last time and how to avoid it next time.
