### ISSUE TITLE
doc: ternary operator FAQ section's example code

### ISSUE THREAD

**Issue by pravj** [golang/go#10425]
The [section there](https://github.com/golang/go/blob/f3de21767e1ea12e9ec30fc1e9a1b60dfc6cb440/doc/go_faq.html#L1460-L1474) explains that how can you simulate a ternary operator's work in Go. It encourages to use:

```go
if expr {
    n = trueVal
} else {
    n = falseVal
}
```

But I think we should keep less code and use this block instead as we're working with assignments only.

```go
n = falseVal
if expr {
    n = trueVal
}
```

I'm saying this because the *golint tool* gives this error when you have *return* statements in such *if-else* blocks.
```
if block ends with a return statement, so drop this else and outdent its block
```

Please correct me if I'm wrong here.

**Comment by davecheney** [comment]
Feel free to send a change (not a PR), http://golang.org/doc/contribute.html

**Comment by cznic** [comment]
@pravj 

The 2nd version (w/o the else clause) is semantically different when the evaluation of `falseVal` has side effects. That's why IMO the current version (with the else clause) is a better example - it has exactly the same semantics as the C construct it replaces.

**Comment by pravj** [comment]
Hi @cznic,

Yes, you're right that the one I suggested has different semantic meaning than the original one.
But, in that case we should consider using *expressions* inside the blocks instead of *statements*.

Consider this tiny example relating to a single iteration of the [Collatz conjecture](http://en.wikipedia.org/wiki/Collatz_conjecture).

> global variable declaration

```go
n := 5
```
> original snippet

```go
if (n%2 == 0) {
    n = n/2
} else {
    n = 3*n + 1
}
```

> suggested snippet

```go
n = 3*n + 1
if (n%2 == 0) {
    n = n/2
}
```

Here, the *original snippet* yields correct result(16) instead of my *suggested snippet*'s result(8).
This proves that right you are, both the blocks have different semantic meanings.

But there is a significant difference here, as in the original block, all the code doing is assigning a value to variable *n*, the result will be same if we go for the small block I suggested.

So, I think we should use *expressions* in the blocks. Inside the if-else, *trueVal* and *falseVal* sounds like some pre-calculated values, which doesn't respect the definition of ternary operator.

It should be something like:

```go
if expr {
    trueExpr
} else {
    falseExpr
}
```

Again, correct me please If I'm wrong.

**Comment by robpike** [comment]
Fine as is. It's a trivial example for a trivial problem.
