### ISSUE TITLE
COMODO certifification got x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by SunRunAway** [golang/go#10421]
What version of Go are you using (go version)?
go1.4.2 

    What operating system and processor architecture are you using?
darwin/amd64

    What did you do?
run this program,
```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	url := "https://catchchat.catchchatchina.com/"
	_, err := http.Head(url)
	if err != nil {
		fmt.Println(err)
	}
}
```

    What did you expect to see?

do not print the error. This url can be opened in browsers.

    What did you see instead?

```
[sunrunaway:~/Code/go/bin]$ go run ~/Code/gotmp/httpget.go                                                    (master) 
Head https://catchchat.catchchatchina.com/: x509: certificate signed by unknown authority
```

**Comment by linniksa** [comment]
You can add certificates of "COMODO RSA Domain Validation Secure Server CA" to your certififcate serverd from server, also see full report at https://www.ssllabs.com/ssltest/analyze.html?d=catchchat.catchchatchina.com

**Comment by SunRunAway** [comment]
@linniksa Thanks.
