### ISSUE TITLE
net/http: flaky TestIdleConnChannelLeak

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10427]
Flaky test seen on `linux-amd64` at rev `947b6a7ec8e0`

http://build.golang.org/log/ba81501397a2cf312dfcf83b4d32bfcbdc2fd03d
```
ok  	mime/quotedprintable	0.195s
ok  	net	2.532s
--- FAIL: TestIdleConnChannelLeak (0.00s)
	transport_test.go:1843: ForDisableKeepAlives = false, map size = 1; want 0
FAIL
FAIL	net/http	4.595s
ok  	net/http/cgi	0.333s
ok  	net/http/cookiejar	0.012s
```

**Comment by crawshaw** [comment]
This same error is happening frequently on the android-arm builder since I cleaned out its TMPDIR:

http://build.golang.org/log/b01531046245aead11b3269a2d601883b12f65c0

**Comment by bradfitz** [comment]
I've been unable to reproduce this. I've also read the code and can't see how it might occur.

There have been a number of fixes recently in the transport code, so hopefully one of those fixes also got this.

Please re-open if you see this again.

**Comment by crawshaw** [comment]
This appeared again this morning on linux-386, rev 3ca20218c126:

http://build.golang.org/log/9787432466e57bea66b3084a69f8a81a10603642

I still have no way to reliably reproduce it.
