### ISSUE TITLE
x/mobile/cmd/gomobile: build unsigned

### ISSUE THREAD

**Issue by rakyll** [golang/go#10439]
gomobile should have an option to build unsigned apks. This is an alternative solution to the previously proposed idea on https://github.com/golang/go/issues/10090, but being able to output unsigned apks or apps and delegating the signing to external tooling for prod builds is a more feasible solution.

**Comment by rakyll** [comment]
cc/ @crawshaw @hyangah

**Comment by hyangah** [comment]
is it difficult to resign signed apk/ipa?
If unsigned apk/ipa are simply zip files, this will be simple to implement.

gomobile build -unsigned 
and show examples on how to sign.

**Comment by crawshaw** [comment]
Apparently the process to resign an .apk is ```zip -d app.apk META-INF/*``` and then follow the usual signing process.

**Comment by rakyll** [comment]
The process required to resign an IPA is similar. See https://gist.github.com/mediabounds/1367348. What about suggesting resigning as the blessed way to make prod builds and document it?

**Comment by rakyll** [comment]
Closing, it is obsolete now. We can suggest resigning rather than building unsigned APKs.
