### ISSUE TITLE
transform http response headers to lowercase

### ISSUE THREAD

**Issue by nodegin** [golang/go#10438]
go version go1.2.1 linux/amd64
what i expect to see is:
`Content-Type` -> `content-type`
`Set-Cookie` -> `set-cookie`
`X-Xss-Protection` -> `x-xss-protection`

this fulfill spdy specification and looks more pretty.

**Comment by minux** [comment]
The current http package has nothing to do with spdy, so
why should it fullfit spydy specification?

The current mixed case header naming is consistent with
http RFCs.

The headers are used in a map, so given Go 1 API guarantee,
we can't change them anyway.
