### ISSUE TITLE
crypto/x509: Support MD5 signatures for certificates

### ISSUE THREAD

**Issue by gonzojive** [golang/go#10436]
x509.Certificate.CheckSignature does not support MD5 signatures.  Is this intentional?  If so, a comment should be added in the source and/or docs.  If not, then please add support for MD5 signatures.

Code pointer: https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L621

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by mvanotti** [comment]
I think this is a duplicate of issue #10431
