### ISSUE TITLE
fmt.Println(1 << 31) panics on playground

### ISSUE THREAD

**Issue by gaal** [golang/go#10437]
http://play.golang.org/p/XRZe_kcHav
http://play.golang.org/p/s9SX9Wd-PY

"constant 2147483648 overflows int"

Why doesn't the compiler pick a wider type, then?

**Comment by mdempsky** [comment]
This is working as intended.  The Go spec says that the default type for integer constant expressions is "int", which on the Go playground is a 32-bit type and is unable to exactly represent the constant 1<<31.  The compiler isn't picking a wider type because the spec doesn't allow it to.
