### ISSUE TITLE
os: TestProgWideChdir fails on OS X 10.10

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10435]
```
--- FAIL: TestProgWideChdir (0.00s)
	os_test.go:1089: Getwd returned "/private/var/folders/2g/gfk3yj9d4318d1x3j8jgkjjw0000gn/T/test083221789" want "/var/folders/2g/gfk3yj9d4318d1x3j8jgkjjw0000gn/T/test083221789"
```

TMPDIR is set to a path under /var/folders by default, and it looks like OS X 10.10 moved /var with a symlink:

```lrwxr-xr-x@  1 root  wheel    11 Oct  9  2014 var -> private/var```

The builders do not show this error, presumably because they are running an older version of OS X. The new buildlet (still under construction) should let us run older versions of OS X under a VM, so hopefully we can test for this in the future.

Reported by Marco on golang-nuts.

**Comment by davecheney** [comment]
Ahh, and we only have 10.6 builders running on the dashboard at the moment.

**Comment by 0intro** [comment]
Mikio Hara proposed CL 8842 to fix this issue.

**Comment by crawshaw** [comment]
Thanks, I was writing the same CL.

**Comment by mikioh** [comment]
Fixed by https://go.googlesource.com/go/+/3cbe7ea7e9de8547699537e78b76cfbc119e485d.

**Comment by marcopeereboom** [comment]
Verified.  Thanks.
