### ISSUE TITLE
go get  golang.org/x/tools/cmd/vet is broken

### ISSUE THREAD

**Issue by jfrazelle** [golang/go#10446]
Hey so sorry if this is not the correct place for this. I tried IRC first but apparently its actually in the code, this was updated to only work with tip. And now its kinda messing up our CI :(
whomp whomp 
```
Unrecognized import path "go/exact" (print.go:13:2)
Unrecognized import path "go/importer" (types.go:11:2)
Unrecognized import path "go/types" (main.go:18:2)
```

**Comment by minux** [comment]
/cc @griesemer @robpike

I brought up such possibility during the review of CL 8767.
I think we should revert that CL and make a copy of modified cmd/vet into
the std repo.

Right now, even Go 1.4 users will no longer be able to install cmd/vet from
the tools
repo.

**Comment by jfrazelle** [comment]
I can change our so we checkout the sha before that was merged of tools,
might help if you all tag that sha as 1.4 or something for other people

On Monday, April 13, 2015, Minux Ma <notifications@github.com> wrote:

> /cc @griesemer @robpike
>
> I brought up such possibility during the review of CL 8767.
> I think we should revert that CL and make a copy of modified cmd/vet into
> the std repo.
>
> Right now, even Go 1.4 users will no longer be able to install cmd/vet from
> the tools
> repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/10446#issuecomment-92553009>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by harshavardhana** [comment]
Can see the issue as well ..

**Comment by griesemer** [comment]
Should be fixed now. Apologies. There was no intent to submit this in the first place; I blame a Fri night keyboarding malfunction...

Please verify and let me know. Thanks.

**Comment by jfrazelle** [comment]
LGTM thanks

**Comment by ahmetalpbalkan** [comment]
thanks <3

**Comment by laike9m** [comment]
New to Go, does this mean I don't need to install `cmd/vet` if I'm using Go 1.4+?

**Comment by ianlancetaylor** [comment]
@laike9m Please use the mailing list (golang-nuts@googlegroups.com) to ask questions.  Please don't ask questions on closed issues.  Thanks.

The answer to your question is that for Go 1.4 you still need to go install golang.org/x/tools/cmd/vet.  For Go 1.5 this may not be necessary.
