### ISSUE TITLE
The term "assignment operator" in the Language Specification?

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#10452]
In the Language Specification, section "Arithmetic operators", there is the following line:

Strings can be concatenated using the + operator or the += assignment operator:

I think "the += assignment operator" should read "the += assignment operation", because += is not a operator.

**Comment by griesemer** [comment]
Per the spec: "There are four classes: identifiers, keywords, operators and delimiters, and literals."

+= must be an operator (it's not an identifier, keyword, literal, or delimiter)
