### ISSUE TITLE
os: package os should not depend on cgo for darwin/arm

### ISSUE THREAD

**Issue by josharian** [golang/go#10455]
```bash
$ go test go/build
--- FAIL: TestDependencies (5.80s)
	deps_test.go:426: darwin/arm/cgo=false unexpected dependency: os imports [C]
	deps_test.go:426: darwin/arm/cgo=true unexpected dependency: os imports [C]
FAIL
FAIL	go/build	5.943s
$ go test -short go/build
ok  	go/build	0.089s
```

/cc @minux @crawshaw

**Comment by minux** [comment]
Do you know what package that os depends on uses cgo?
even when cgo is disabled?

$ GOOS=darwin GOARCH=arm go list -f '{{.Deps}}' os
[errors io runtime sync sync/atomic syscall time unsafe]
$ CGO_ENABLED=1 GOOS=darwin GOARCH=arm go list -f '{{.Deps}}' os
[errors io runtime runtime/cgo sync sync/atomic syscall time unsafe]

**Comment by josharian** [comment]
I don't know. But IIRC, darwin/arm needed cgo to function correctly. There's a line in misc/ios/README about `import "_ runtime/cgo"`. Maybe that got fixed somewhere by faking the C import, which has broken this test in turn? I'd need to dig.

**Comment by minux** [comment]
OK, I know the cause.

https://golang.org/cl/6460 adds cgo dependency to package os to query the
temporary directory.

perhaps we should do that in runtime/cgo.

**Comment by crawshaw** [comment]
The data structure holding the environment variables is owned by the syscall package. I suppose linker tricks can be used to work around the test.

There are many options, but I'm not sure what the right solution is.
