### ISSUE TITLE
x/mobile/geom: concurrent modification to Width, Height global vars

### ISSUE THREAD

**Issue by nigeltao** [golang/go#10461]
geom.Width and geom.Height look like they're meant to be initialized once and not mutated afterwards, since they're plain global variables without any locking.

However, x/mobile/app and in particular loop_android.go updates these global vars when e.g. the phone rotates.

There is no clear line between the UI goroutine and the others. Should we protect each value or should we restrict them being accessible from the UI goroutine? This is a design question and requires discussion.

**Comment by nigeltao** [comment]
Adding @rakyll @crawshaw @hyangah for x/mobile expertise.

**Comment by slimsag** [comment]
I would imagine that they are not intended to be accessed except in the UI goroutine (i.e. `Draw` callbacks etc), much as `x/mobile/gl` cannot be used except in that goroutine.

**Comment by crawshaw** [comment]
There is a goroutine, locked to an OS thread, that is both responsible for updating geom.{Width, Height} and calling app.Draw. So there is no data race at the moment as long as width and height are only used from the Draw function (which is also the only safe place to use GL).

This however, it not a particularly goroutine-friendly design, and I'm open to alternatives.

**Comment by crawshaw** [comment]
My current thinking on this is that these values should be folded into the ```app``` package. Stored in a type like:

```
type Config struct {
        Width geom.Pt
        Height geom.Pt
        PixelsPerPt float32
        Orientation Orientation
}
```

With a package function, ```func State() Config``` and a field of the ```Callbacks``` struct: ```State: func(Config)```.

But I'm not going to think about this again until after the Go 1.5 freeze. Then I'll prototype it in some apps and if it works, send out a CL. I believe there's some other Issue opened somewhere about app configuration updates, this would cover that too.

**Comment by rakyll** [comment]
I like the idea of passing the current state to a callback. As an improvement, making the state available on each callback would be more user-friendly.

``` go
Start func(c Config)
Stop func(c Config)
Draw func(c Config)
Touch func(c Config, e event.Touch)
```

https://github.com/golang/go/issues/10442 lists a number of other configuration related properties. We might provide a few of them as a part of Config if querying them are not costly.

Related to https://github.com/golang/go/issues/10442 and https://github.com/golang/go/issues/10327.
