### ISSUE TITLE
cmd/go: darwin/arm defaults to -p 1 for testing, which unnecessarily slows down building

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10477]
We set -p 1 by default for darwin/arm, because it's impossible to run more than one test at a time on the iOS device (each test is packaged as an app for execution).

https://github.com/golang/go/blob/master/src/cmd/go/build.go#L137

As a result, stdlib builds also happen one package at a time on the host, which can be a bit frustrating when you're looking for a compiler error.

Just for this I don't think it's worth complicating the go command to separate the notions of parallelism, but if some other changes happen to its work scheduling, parallel darwin/arm builds would be nice to have.

**Comment by minux** [comment]
I think the correct way is to leave -p as is and serialize the running of
tests on android/ios in cmd/go/test.go.

see http://tip.golang.org/src/cmd/go/test.go#L473 for how it could
be done.
