### ISSUE TITLE
Docs: update incorrect syntax-wiki link in golang.org/pkg/regexp/

### ISSUE THREAD

**Issue by harikb** [golang/go#10471]
The first link in the Overview section of  http://golang.org/pkg/regexp/ , points to http://code.google.com/p/re2/wiki/Syntax , which doesn't take you the equivalent replacement in github.

It should at least be corrected to https://github.com/google/re2/wiki/Syntax or to the following http://golang.org/pkg/regexp/syntax/ . In the IRC chat I was told the later is a better/accurate description of the syntax. There is a godoc command listed below which probably gives the same output. However, it is good to have a syntax accessible from the online docs.

Thanks

**Comment by bradfitz** [comment]
Already fixed on tip (http://tip.golang.org/pkg/regexp/) in fc9a234d (dup of #10224)
