### ISSUE TITLE
mime/quotedprintable: return a *Reader, not *io.Reader

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10472]
http://tip.golang.org/pkg/mime/quotedprintable/ is a new package for Go 1.5

It adds two function:

func NewWriter(w io.Writer) *Writer
func NewReader(r io.Reader) io.Reader

Before we lock this API down, we should change NewReader to also return a concrete type, so we have a place to put future options & methods, just like *Writer.  Otherwise we're locked in. (we've been here before)

/cc @alexcesaro

**Comment by alexcesaro** [comment]
Right, I will do it today.

There is also a very small bug in the Reader., error messages are sometimes a bit imprecise. See [this test](https://github.com/alexcesaro/qpbench/blob/master/qpbench_test.go#L28).
Currently is the output of the [current code](http://tip.golang.org/src/mime/quotedprintable/reader.go?#L74) and [mime/qp](https://github.com/alexcesaro/qp/blob/master/qp.go#L107) is the output of a slightly different algorithm I had done. The code is longer but is a bit faster:
CurrentDecode      100000         19591 ns/op        4273 B/op           4 allocs/op
NewDecode           100000         15850 ns/op        4289 B/op           4 allocs/op

Do you think that is worth doing another CL on the reader?

**Comment by bradfitz** [comment]
If I read your comment correctly, you mention three issues:

1. Changing return from io.Reader to *Reader
2. Better error messages
3. Better performance

I think all three can be separate CLs. But number 1 is most important and should happen first.
