### ISSUE TITLE
Possible to return detailed error through RPC?

### ISSUE THREAD

**Issue by psfung** [golang/go#10488]
*Effective Go* writes "Callers that care about the precise error details can use a type switch or a type assertion to look for specific errors and extract details", but it is not the case for RPC. I tried to modify the example in RPC doc:

```go
type DivideError struct {
	Divisor int
}

func (divideError *DivideError) Error() string {
	return fmt.Sprintf("divide by %d", divideError.Divisor)
}

func (t *Arith) Divide(args *Args, quo *Quotient) error {
	if args.B == 0 {
		return &DivideError{Divisor: 0}
	}
	...
}
```

The error returned by Client.Call() is of type rpc.ServerError that carries the error string returned by DivideError.Error(). It would be perfect if the DivideError instance itself is returned.

**Comment by ianlancetaylor** [comment]
This is not really an issue, it's more of a question.  It might be possible to formulate this into an issue, but as it stands it is too vague.  Please ask questions on the golang-nuts mailing list, not in the issue tracker.  Thanks.

The answer to your question is http://golang.org/pkg/encoding/gob/#Register .

**Comment by psfung** [comment]
Thanks Ian. This is a suggestion to change the behaviour of RPC; rather than a question. Anyway, I will discuss this issue in golang-nuts.

gob.Register is not the answer. There is no problem in the codec of DivideError struct. The problem lies in the RPC layer which captures the error string only but does not transmit the DivideError instance.
