### ISSUE TITLE
runtime: panic when calling runtime.Callers after div by zero on linux/arm

### ISSUE THREAD

**Issue by inconshreveable** [golang/go#10486]
```go
package main

import (
    "path/filepath"
    "runtime"
)

func divZero() int {
    defer func() {
        if p := recover(); p != nil {
            var pcs [512]uintptr
            runtime.Callers(2, pcs[:])
        }   
    }() 
    a, b := 1, 0
    return a / b
}

func main() {
    divZero()
    filepath.ToSlash(runtime.GOROOT())
}
```

Expected output: none, program should exit successfully

Observed output:
```go
pi@raspberrypi ~ $ go run t.go
runtime: g1: leftover defer argp=0x1031b7a0 pc=0x10c3c
	defer 0x10336100 argp=0x1031b7a0 pc=0x10c3c
	defer 0x10336000 argp=0x1031b7c4 pc=0x1fde4
fatal error: traceback has leftover defers

runtime stack:
runtime.gothrow(0x87198, 0x1d)
	/usr/local/go/src/runtime/panic.go:503 +0x84
runtime.gentraceback(0x10cdc, 0x1031b734, 0x41cd4, 0x103000a0, 0x0, 0x0, 0x7fffffff, 0x7ec1e7b0, 0x7ec1e7b8, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:445 +0x6bc
copystack(0x103000a0, 0x1000)
	/usr/local/go/src/runtime/stack.c:623 +0xfc
runtime.newstack()
	/usr/local/go/src/runtime/stack.c:789 +0x444
runtime.morestack()
	/usr/local/go/src/runtime/asm_arm.s:319 +0x4c

goroutine 1 [stack growth]:
main.func·001()
	/Users/aes/t.go:9 fp=0x1031b734 sp=0x1031b734
runtime.call16(0x8bc64, 0x1033611c, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_arm.s:406 +0x70 fp=0x1031b748 sp=0x1031b734
runtime.gopanic(0x74290, 0x1030a020)
	/usr/local/go/src/runtime/panic.go:387 +0x3b4 fp=0x1031b780 sp=0x1031b748
runtime.panicdivide()
	/usr/local/go/src/runtime/panic.go:24 +0x54 fp=0x1031b794 sp=0x1031b780
main.divZero(0x0)
	/Users/aes/t.go:16 +0x74 fp=0x1031b7a4 sp=0x1031b794
main.main()
	/Users/aes/t.go:20 +0x1c fp=0x1031b7c0 sp=0x1031b7a4
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0x108 fp=0x1031b7e4 sp=0x1031b7c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1322 +0x4 fp=0x1031b7e4 sp=0x1031b7e4

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1322 +0x4
```

This is a minimal test case whittled down from a larger application.

Note the following:
- I have only tested on Linux/ARM GOARM=6. The actual hardware platform tested on was a Raspberry Pi  2 Model B.
- This problem manifests both from native compilation on linux/arm and darwin/amd64 -> linux/arm cross compilation.
- Changing `var pcs [512]uintptr` to `var pcs [256]uintptr` results in successful execution.
- Removing the call to `filepath.ToSlash(runtime.GOROOT())` results in successful execution.

**Comment by randall77** [comment]
Looks like somehow _div is not leaving the stack in a good state when cleaning up and calling panicdivide.  I don't understand the arm assembly enough to understand how this is supposed to work.  ARM guys?

@davecheney @minux

**Comment by randall77** [comment]
BTW this is 1.4.2, not tip.

Just a thought, it looks like the _div callsite pushes 2 words before calling _div.  I don't understand why it needs to do that.  I made a change in 1.4 that removed a lot of these 2 (or for arm, 3) word pushes/pops for defers and go statements.  Maybe traceback doesn't understand this 2-word pad?  Maybe the pcsp map no longer contains the sp delta for this _div callsite?

Maybe we can just get rid of the 2-word push/pop?  I don't see what its purpose is.

**Comment by minux** [comment]
Keith, see http://golang.org/src/runtime/vlop_arm.s#L179 for the explanation

If we only concern about Go code, we can reserve two register for ODIV/OMOD
and treat them like DUFFCOPY. But assembly code also uses DIV/MOD, and
that's why we currently resort to the liblink trickery.

**Comment by josharian** [comment]
Related:

https://github.com/golang/go/issues/6681

Here's a fix that Russ implemented and then rolled back:

https://github.com/golang/go/commit/b0db472ea29a9f8283888e0cb5f7545f86dbc32c

And the issue to revive that fix:

https://github.com/golang/go/issues/6699

**Comment by rsc** [comment]
I think we can bring back CL https://golang.org/cl/19810043.
They are not used from NOSPLIT code, and there is no longer C code,
and the Go compiler does the magic multiply on all systems.

Anyone want to try?

**Comment by rsc** [comment]
I have this working. Will send out once current arm build breakage is gone.
