### ISSUE TITLE
x/mobile/cmd/gobind: byte slices are not listed as supported types

### ISSUE THREAD

**Issue by rakyll** [golang/go#10481]
Originally reported by @hellais.

gobind help doesn't list byte arrays as the supported types in following section.

```
All exported symbols in the package must have types that are supported.
Supported types include:
 	- Signed integer and floating point types.
 	- String and boolean types.
	...
```

cc/ @crawshaw @hyangah

**Comment by hellais** [comment]
There appear to be [unit tests for them](https://github.com/golang/mobile/blob/master/bind/java/testpkg/testpkg.go#L109), so they are most probably supported.

**Comment by hyangah** [comment]
Thanks for the report. It's fixed long time ago, but I forgot to update the doc.

**Comment by hyangah** [comment]
https://go-review.googlesource.com/8986
