### ISSUE TITLE
website: contributing docs don't mention git cloning

### ISSUE THREAD

**Issue by rakyll** [golang/go#10480]
Our contributing page [1] or CONTRIBUTING files such as [2] doesn't mention the git cloning step. We need to list where to clone the main repo and the sub-repos.

[1] https://golang.org/doc/contribute.html
[2] https://github.com/golang/go/blob/master/CONTRIBUTING.md

**Comment by bradfitz** [comment]
The contributing page says "It assumes you have followed the installation instructions" which is a link to how to do the git clone etc.

**Comment by rakyll** [comment]
Installation instructions are focused on the main repo. Every time a contributor opens a PR against a sub-repo, we are giving them a link to the contribute.html even though it explains nothing about opening a CL against a sub-repo.

**Comment by rasky** [comment]
Current version of CONTRIBUTING.md just refers to the guide, and the guide now includes the cloning step.
