### ISSUE TITLE
tour: Advances to next page when switching tabs with control-PageDown

### ISSUE THREAD

**Issue by tv42** [golang/go#10499]
If I go to http://tour.golang.org/welcome/1 with Chrome 42.0.2311.68 on linux and hit control-PageDown control-PageUp to toggle tabs, the url has changed to http://tour.golang.org/list or http://tour.golang.org/welcome/1 (depending on direction of tab switch and whether I use the mouse or keyboard to return back to original tab).

Others have confirmed Chromium 41 does this, Firefox doesn't.

**Comment by thraxil** [comment]
FWIW, Chrome 62.0.3202.94 on Linux no longer shows this behavior.

**Comment by Deleplace** [comment]
Not reproduced today in Chrome 63 and Firefox 57 (Linux).

**Comment by davecheney** [comment]
Thanks for confirming.
