### ISSUE TITLE
x/tools/cmd/godoc: ExampleABC functions not matching a suffix rule are not displayed

### ISSUE THREAD

**Issue by alandonovan** [golang/go#10494]
When viewing examples in godoc, a function called ExampleABC that doesn't match any of the suffix patterns described here

  http://golang.org/pkg/testing/#hdr-Examples

is silently excluded.  I would have expected it to be associated with the package.

The -ex flag makes no difference.

You can see an example in the x/tools repo, if you sync to 9c57c19a58835b00c0e3e283952087842242e49b and look at golang.org/x/tools/go/loader.  The follow-up change, 41d9a0e7b2d60d52ef1caf232b081c16af220b44, renames the examples to make them visible.

**Comment by agnivade** [comment]
This seems to be intended functionality - 

```go
name := stripExampleSuffix(e.Name)
if name == "" || globals[name] {
	examples = append(examples, e)
} else if c.Verbose {
	log.Printf("skipping example 'Example%s' because '%s' is not a known function or type", e.Name, e.Name)
}
```

https://github.com/golang/tools/blob/master/godoc/server.go#L434

It strips the suffix and checks whether it matches with a global name or not. Do we want to remove it ?

**Comment by seankhliao** [comment]
let's close as working as intended.
