### ISSUE TITLE
x/mobile/cmd/gomobile: remove reference to old5a in init

### ISSUE THREAD

**Issue by hyangah** [golang/go#10496]
gomobile uses -toolexec build flag to invoke toolchains for android. 
As a side-effect, it ends up using old tools 

 cd /usr/local/google/home/hakim/golang/gopaths/ws4/src/golang.org/x/mobile/app/internal/callfn
 /usr/local/google/home/hakim/golang/gopaths/ws4/pkg/gomobile/android-ndk-r10d/arm/bin/toolexec /usr/local/google/home/hakim/golang/goroots/newgo/go/pkg/tool/linux_amd64/old5a -o $WORK/golang.org/x/mobile/app/internal/callfn/_obj/callfn_arm.5.new -trimpath $WORK -I $WORK/golang.org/x/mobile/app/internal/callfn/_obj/ -I /usr/local/google/home/hakim/golang/goroots/newgo/go/pkg/include -D GOOS_android -D GOARCH_arm ./callfn_arm.s
 pack r $WORK/golang.org/x/mobile/app/internal/callfn.a  $WORK/golang.org/x/mobile/app/internal/callfn/_obj/callfn_arm.5 # internal
 mkdir -p $WORK/golang.org/x/mobile/gl/_obj/

(see https://github.com/golang/go/blob/master/src/cmd/go/build.go#L1909)

An easy option is to make gomobile's toolexec command rewrite the build command to use asm if old5a is requested.

**Comment by hyangah** [comment]
revert https://go-review.googlesource.com/9034 when #10510 is fixed and old*a tools are deleted before release.

**Comment by crawshaw** [comment]
Fixed by golang/mobile@743b9bf.
