### ISSUE TITLE
cmd/internal/gc, cmd/internal/ld: use new flag argument syntax

### ISSUE THREAD

**Issue by rsc** [golang/go#10505]
The usage messages for the flags in gc and ld are using the old
flag argument syntax from my C library - "arg: description using arg".
They need to be updated to the Go 1.5 flag package's syntax - "description using `arg`".

**Comment by rsc** [comment]
The backquotes were lost in the CL that was submitted. Needs to be redone.

**Comment by minux** [comment]
Fixed by https://golang.org/cl/9652.
