### ISSUE TITLE
x/tools/cmd/gomvpkg: should also rewrite package name in external tests

### ISSUE THREAD

**Issue by minux** [golang/go#10507]
By external test, I mean `package pkgname_test`

the pkgname part should also be updated to the new package name, otherwise
go build/install will complain.

BTW, external tests also tend to use dot import to import the package under
test, even though we don't support fixing dot imports now, ideally we should
support this special case.

One test case is to move golang.org/x/tools/types to golang.org/x/tools/gotypes.

**Comment by minux** [comment]
I understand refactor/rename can't generally support dot imports, but
I think supporting dot import in context of moving package import paths
should be straightforward. Or am I missing anything?

**Comment by davidrjenni** [comment]
I came up with a change, which should fixes the issue.
Given the command `gomvpkg -from foo -to bar`, the following files:

```
// $GOPATH/src/foo/foo.go
package foo
type T int
```

```
// $GOPATH/src/foo/foo_test.go
package foo_test
import "foo"
var _ foo.T
```

```
// $GOPATH/src/baz/baz_test.go
package baz_test
import "foo"
var _ foo.T
```

are now rewritten to

```
// $GOPATH/src/bar/bar.go
package bar
type T int
```

```
// $GOPATH/src/bar/bar_test.go
package bar_test
import "bar"
var _ bar.T
```

```
// $GOPATH/src/baz/baz_test.go
package baz_test
import "bar"
var _ bar.T
```

Can I send the change for further review?

**Comment by ianlancetaylor** [comment]
@davidrjenni Please contribute changes using the process described at https://golang.org/doc/contribute.html .  Thanks.

**Comment by davidrjenni** [comment]
I sent a CL: https://golang.org/cl/12637

**Comment by davidrjenni** [comment]
This was fixed in https://github.com/golang/tools/commit/20d85c34f38c8b82369f050814228f2af29b5dc0.
I guess the issue can be closed.
