### ISSUE TITLE
net/http: possible to lose CancelRequest between getConn and roundTrip

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10511]
As noted by @DanielMorsing, it's possible to lose a Transport.CancelRequest between dialing the conn and roundTrip.

There exists a small window where the cancel request is still:

```
        t.setReqCanceler(req, func() { close(cancelc) })
```

... but we've already dialed, but we haven't yet entered roundTrip and its:

        pc.t.setReqCanceler(req.Request, pc.cancelRequest)

**Comment by DanielMorsing** [comment]
https://go-review.googlesource.com/#/c/9181/
