### ISSUE TITLE
spec: odd sentence about non-constant shift expressions

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10514]
Within the [Operators section](http://tip.golang.org/ref/spec#Operators), the Go spec says:

> If the left operand of a non-constant shift expression is an untyped constant, the type of the constant is what it would be if the shift expression were replaced by its left operand alone.

My understanding (e.g., from the [Constants section](http://tip.golang.org/ref/spec#Constants)) is that constants are either typed or untyped, but not both.  Also, untyped constants have a *default* type, but otherwise it seems an oxymoron to refer to "the type of the [untyped] constant".

I suspect the sentence instead means to refer to what sort of type the constant is to be *converted* to.  Something like:

> If the left operand of a non-constant shift expression is an untyped constant, the constant is converted to the same type as it would be if the shift expression were replaced by the constant alone.

**Comment by griesemer** [comment]
Fair point.
