### ISSUE TITLE
runtime/pprof: "signal" test failures

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10519]
runtime/pprof is failing with unhelpful "signal: blah" error messages on a lot of builders.  For some reason we're not getting any further details though.  E.g., which runtime/pprof test is failing or a sigpanic stack trace.

linux/386 ("signal: segmentation fault"):

http://build.golang.org/log/07ee563d20864714eacb0e7307b474f7442008d7
http://build.golang.org/log/9ec79d102626ec6e8fc3fd392380bc0b520f35f4

linux/amd64 ("signal: segmentation fault"):

http://build.golang.org/log/10ef18cb3cd066f886ae1e8a8402f506a3cdb119
http://build.golang.org/log/1f5252c1bfda6d36b3dd5f1145cb702e075244b6
http://build.golang.org/log/59217a106b0b2382b49fec6f3519ed8336a971a9
http://build.golang.org/log/7b6a1ea33b8328df1effa7c793cebe137db2bf92
http://build.golang.org/log/d9507dafead6918ad32bcfeb8755f1fa78556911
http://build.golang.org/log/f2c7f09283cbba3767f0494a7be2a33a0e53132a

linux/arm64 ("signal: segmentation fault (core dumped)"):

http://build.golang.org/log/581d4aa6c33932de2ed35c4be71f1cd351ac4525
http://build.golang.org/log/881f201ecb2c30677f09e7ea9c2f3c3c44dfbde7
http://build.golang.org/log/90143ce9b0f68fc8e7b62f5ca26404b13ab033e1
http://build.golang.org/log/e2606ffaac1b253d21cd788ce0a2c561edf4d61e
http://build.golang.org/log/f93c432aa050385a27afc0227df3b96c101fcf96

netbsd/386 ("signal: killed"):

http://build.golang.org/log/93432c69d4ebf598a862589ab9283eff5b66373a

**Comment by rsc** [comment]
The message is the exit status being reported by the go command. The test binary seems to be exiting due to the signal, without handling it itself. 

Are there more recent instances of this?

**Comment by mdempsky** [comment]
All of the Google search results for [site:build.golang.org "signal: segmentation fault"](https://www.google.com/search?q=site%3Abuild.golang.org%20%22signal%3A%20segmentation%20fault%22) appear to be from April.  Looks like this isn't a problem anymore.
