### ISSUE TITLE
mime package missing an entry for .svg files

### ISSUE THREAD

**Issue by lavalamp** [golang/go#10513]
http://golang.org/src/mime/type.go#L26

I can send a PR if it'll be accepted.

```
".svg": "image/svg+xml",
```

**Comment by bradfitz** [comment]
Already fixed in 21e47d831

Btw, we don't use Github Pull Requests. For future contributions, see https://golang.org/doc/contribute.html

**Comment by lavalamp** [comment]
Thanks for the speedy response!
