### ISSUE TITLE
x/mobile: deprecate docker-based build, promote gomobile.

### ISSUE THREAD

**Issue by hyangah** [golang/go#10523]
Update examples to use gomobile; make sure it works on Linux, Mac OS X, Windows.
Update build instruction in README.md.

cc: @rakyll @crawshaw

**Comment by rakyll** [comment]
I was waiting for the freeze to suggest it. Once the code freeze for 1.5 happens, we can update the build instructions and start promoting the samples.

**Comment by crawshaw** [comment]
No need to wait for the freeze. I'm short on hours to review while I focus on the main repository, and if you have any features that need to go into it prioritize those, but otherwise no need to wait.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/mobile/commit/a849359c3b9391509b6aaf309d139c2beea3f10a.
