### ISSUE TITLE
os: OpenFile can not set mode 

### ISSUE THREAD

**Issue by galric** [golang/go#10521]
```go
var mode os.FileMode = 0666
os.OpenFile("g2", os.O_WRONLY|os.O_TRUNC|os.O_CREATE, mode)
```
create file with mode
-rw-rw-r-- 1 admin admin        0 Apr 21 18:25 g2

not
-rw-rw-rw- 1 admin admin        0 Apr 21 18:24 g2

miss w

At go version go1.4.1 linux/amd64

**Comment by mattn** [comment]
Probably, your `umask` is 0022.
http://man7.org/linux/man-pages/man2/open.2.html
```
The effective permissions are modified by the process's umask in the usual way: The permissions of the created file are (mode & ~umask).
```

**Comment by galric** [comment]
Thank you, you are right
