### ISSUE TITLE
reflect: ArrayOf GC prog uses too much memory

### ISSUE THREAD

**Issue by rsc** [golang/go#10524]
This program takes 11 GB of memory. It should use a tiny fixed amount. It's not possible to fix right now, because GC programs are disabled, but when we re-enable them, we should make this work too. This must be fixed for Go 1.5, or else we should unexport reflect.ArrayOf (new since Go 1.4).

	package main
	
	import (
		"fmt"
		"reflect"
		"runtime"
	)
	
	func main() {
		var m1, m2 runtime.MemStats
		runtime.ReadMemStats(&m1)
		reflect.ArrayOf(1e9, reflect.TypeOf((*byte)(nil)))
		runtime.ReadMemStats(&m2)
		fmt.Printf("%d\n", m2.Sys-m1.Sys)
	}

**Comment by sbinet** [comment]
I am willing to work on this (it's fun to decipher GC internals).
my WIP is over there: https://github.com/sbinet/golang-go/commit/dd775467934261602dc822c1204c8c980f6e46c9

but I would need some more hand holding, I am afraid.

I started to look at runtime/mbitmaps and cmd/internal/gc/reflect.go... (`gengcprog1`, `proggenarray` `proggendata`, `proggenarrayend` and `genemit` seem to be the general areas where one should look at, but I don't see quite clearly how they would translate into `reflect.progGC` framework)
