### ISSUE TITLE
runtime: consider raising 64-bit heap size

### ISSUE THREAD

**Issue by rsc** [golang/go#10536]
It's been brought up on the mailing list (citation needed) that some people want to run Go with heaps beyond the default limit (128 GB today).

Perhaps we should revise the limit at each Go release according to some metric. One possible metric would be to make sure that Go can address all the memory available on the largest VM you can rent from Amazon or from Google.

**Comment by ianlancetaylor** [comment]
See issue #10460 .

**Comment by minux** [comment]
I think adjusting MaxMem automatically on ulimit -v setting is more useful,
and it will also help the problem in the other direction (Go processes use
so much VM that os/exec fails: see
https://github.com/golang/go/issues/5838#issuecomment-71224796)

**Comment by rsc** [comment]
Duplicate of #10460.
