### ISSUE TITLE
net: Interface.Flags always 0 on Windows 8

### ISSUE THREAD

**Issue by ffoebel** [golang/go#10530]
Go version: 1.4

The following code works on Windows 7:
```go
package main
import "fmt"
import "net"
func main() {
    ifs, _ := net.Interfaces()
    for _, i := range ifs {
        fmt.Println(i.Flags)
    }
}
```
Tried both "run as administrator" and "compatibility mode" to see whether this was a side effect but never saw any flags when running on Windows 8.

**Comment by mattn** [comment]
it is fixed in 2015/02/10.
https://go-review.googlesource.com/#/c/3024/

**Comment by mikioh** [comment]
Duplicate of #5395.

**Comment by oliveagle** [comment]
same here.  on windows 2012 R2
go 1.4.2

**Comment by mattn** [comment]
The fixes is applied to the tip on repo. So go1.4.2 doesn't have the fix.
