### ISSUE TITLE
runtime: does not traceback goroutine in systemstack

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10546]
Run the following program:
```
package main

func main() {
	for {
		_ = make([]byte, 1<<20)
	}
}
```
and kill it with SIGABRT. Most of the it crashes as follows. I.e. stack of the main goroutine is not unwound.
```
SIGABRT: abort
PC=0x447b71 m=0

goroutine 0 [idle]:
runtime.futex(0x4af628, 0x0, 0x0, 0x0, 0x0, 0x4af140, 0x0, 0x0, 0x4077dd, 0x4af628, ...)
	?:0 +0x21 fp=0x7fff603b11b8 sp=0x7fff603b11b0
runtime.futexsleep(0x4af628, 0x0, 0xffffffffffffffff)
	src/runtime/os1_linux.go:40 +0x53 fp=0x7fff603b1200 sp=0x7fff603b11b8
runtime.notesleep(0x4af628)
	src/runtime/lock_futex.go:142 +0xad fp=0x7fff603b1228 sp=0x7fff603b1200
runtime.stopm()
	src/runtime/proc1.go:1059 +0x127 fp=0x7fff603b1250 sp=0x7fff603b1228
runtime.exitsyscall0(0xc208000a00)
	src/runtime/proc1.go:2017 +0x16e fp=0x7fff603b1278 sp=0x7fff603b1250
runtime.mcall(0x7fff603b12a0)
	src/runtime/asm_amd64.s:204 +0x5e fp=0x7fff603b1288 sp=0x7fff603b1278

goroutine 1 [running]:
	goroutine running on other thread; stack unavailable
```

The main goroutine is actually at this point:
```
goroutine 1 [running]:
runtime.systemstack_switch()
	src/runtime/asm_amd64.s:216 fp=0xc20802dde0 sp=0xc20802ddd8
runtime.mallocgc(0x100000, 0x4516a0, 0x1, 0xc209254000)
	src/runtime/malloc.go:632 +0x8d9 fp=0xc20802deb0 sp=0xc20802dde0
runtime.newarray(0x4516a0, 0x100000, 0xc209354000)
	src/runtime/malloc.go:742 +0xce fp=0xc20802def0 sp=0xc20802deb0
runtime.makeslice(0x44ea00, 0x100000, 0x100000, 0x0, 0x0, 0x0)
	src/runtime/slice.go:32 +0x16c fp=0xc20802df40 sp=0xc20802def0
main.main()
	crash.go:5 +0x3c fp=0xc20802df90 sp=0xc20802df40
```

This makes it very hard to debug hanging programs. The stack must be unwound.

We leave g in running status during systemstack. This is probably part of the problem. Another part is why the goroutine does not return from systemstack during freezetheworld.

**Comment by randall77** [comment]
freezetheworld can't force a return from the system stack.  The signal handler runs on the same M as the user code, so the user code can't make any forward progress.

A simple fix to this problem is to print the stack if the G's M is identical to the caller's M.  The G can't be running, and crucially modifying its stack, if that is the case. (Unless of course the two Gs are identical, but we already skip printing in that case.)

**Comment by dvyukov** [comment]
I still got "goroutine running on other thread; stack unavailable" 2 times out of 6.

**Comment by spolk01** [comment]
Was just about to post.

SIGQUIT: quit
PC=0x4484b1

goroutine 0 [idle]:
runtime.futex(0x11941b8, 0x0, 0x0, 0x0, 0x0, 0x1193020, 0x1, 0x41604f, 0x41626e, 0x11941b8, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:277 +0x21
runtime.futexsleep(0x11941b8, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.c:49 +0x47
runtime.notesleep(0x11941b8)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xae
stopm()
	/usr/local/go/src/runtime/proc.c:1178 +0x119
findrunnable(0xc208012900)
	/usr/local/go/src/runtime/proc.c:1487 +0x562
schedule()
	/usr/local/go/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc2091b4480)
	/usr/local/go/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x43eb94)
	/usr/local/go/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [chan receive, 10175 minutes]:
main.main()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:269 +0x264d

goroutine 17 [syscall, 10175 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 19 [syscall, 10175 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 20 [select]:
github.com/bitly/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc2090f6b40)
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:84 +0x142
created by github.com/bitly/go-hostpool.NewEpsilonGreedy
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:65 +0x3a3

goroutine 8 [chan receive]:
packetbeat/outputs.(*PublisherType).UpdateTopologyPeriodically(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:166 +0x69
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:299 +0x15ff

goroutine 6 [IO wait, 8816 minutes]:
net.(*pollDesc).Wait(0xc2091b0060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2091b0060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2091b0000, 0xc2091b2000, 0x1000, 0x1000, 0x0, 0x7fc232dd8a20, 0xc208f35f08)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804c338, 0xc2091b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc230589218, 0xc20804c338, 0xc2091ae058, 0xc2091b2000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc209172180, 0xc2091b2000, 0x1000, 0x1000, 0xc208012900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2091a2240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2091a2240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2091ae000)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7 [select, 8816 minutes]:
net/http.(*persistConn).writeLoop(0xc2091ae000)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 9 [chan receive, 8816 minutes]:
packetbeat/outputs.(*PublisherType).publishFromQueue(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:66 +0x5e
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:303 +0x165f

goroutine 10 [chan receive]:
packetbeat/procs.(*Process).RefreshPids(0xc209170690)
	/home/vagrant/src/packetbeat/procs/procs.go:132 +0xc9
created by packetbeat/procs.NewProcess
	/home/vagrant/src/packetbeat/procs/procs.go:125 +0x11d

goroutine 11 [chan receive, 10175 minutes]:
packetbeat/protos/thrift.(*Thrift).publishTransactions(0xc20805d5c0)
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:1006 +0x63
created by packetbeat/protos/thrift.(*Thrift).Init
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:244 +0x139

goroutine 12 [runnable]:
packetbeat/protos/mysql.read_lstring(0xc2095fde04, 0x16f, 0x16f, 0x138, 0xc2095fdf3c, 0x0, 0x37, 0x138, 0x416001, 0x0, ...)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:727
packetbeat/protos/mysql.(*Mysql).parseMysqlResponse(0xc2090efe60, 0xc2095fde04, 0x16f, 0x16f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:662 +0x72a
packetbeat/protos/mysql.(*Mysql).receivedMysqlResponse(0xc2090efe60, 0xc209404780)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:552 +0x728
packetbeat/protos/mysql.handleMysql(0xc2090efe60, 0xc209404780, 0xc209f37740, 0xc2092bb300, 0xc2095fde04, 0x16f, 0x16f)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:461 +0x165
packetbeat/protos/mysql.(*Mysql).Parse(0xc2090efe60, 0xc20a504b40, 0xc209f37740, 0xc20802fe00, 0xa52c00, 0xc208ba7a40, 0x0, 0x0)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:422 +0x4ff
packetbeat/protos/tcp.(*TcpStream).AddPacket(0xc209f37720, 0xc20a504b40, 0xc2091ee2c0, 0x0)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:79 +0x341
packetbeat/protos/tcp.FollowTcp(0xc2091ee2c0, 0xc20a504b40)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:162 +0xb47
packetbeat/protos/tcp.(*DecoderStruct).DecodePacketData(0xc2091ee000, 0xc2095fddc0, 0x1b3, 0x1b3, 0xc20947df80)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:328 +0x47d
packetbeat/inputs/sniffer.(*SnifferSetup).Run(0xc20804e690, 0x0, 0x0)
	/home/vagrant/src/packetbeat/inputs/sniffer/sniffer.go:315 +0xc35
main.func·002(0x0, 0x7fc230587858, 0xc20804e690)
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:243 +0x45
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:249 +0x22d9

goroutine 13 [chan receive, 10175 minutes]:
main.func·003()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:256 +0x3f
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:259 +0x256f

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc209443810)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc20a0c2fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a0c2fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a0c2f50, 0xc2095de000, 0x1000, 0x1000, 0x0, 0x7fc232dd8a20, 0xc208f3d800)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209a70930, 0xc2095de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc230589218, 0xc209a70930, 0xc209443868, 0xc2095de000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2095dc0c0, 0xc2095de000, 0x1000, 0x1000, 0xc208012900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20a0f43c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20a0f43c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc209443810)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

rax     0xca
rbx     0x11941b8
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x11941b8
rsi     0x0
rbp     0x1
rsp     0x7fffec0f5be8
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x6
r13     0xa
r14     0xecd2495ae
r15     0x18
rip     0x4484b1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
