### ISSUE TITLE
encoding/json behaves incorrectly on nested structs

### ISSUE THREAD

**Issue by zombor** [golang/go#10551]
Example here: https://play.golang.org/p/lozTmQr8pR

I'd expect all three outputs to be sane json. There should be no errors here.

**Comment by minux** [comment]
I think it's a misuse of json.RawMessage.

what do you expect the output to be for the first marshal call?
{"tasks":[{"creds":null}]} is not the correct answer.

**Comment by zombor** [comment]
Can you explain why? I'd expect similar output to `[]byte`: https://play.golang.org/p/krJb2ZhRVD

**Comment by minux** [comment]
The content of RawMessage is the raw json data,
so it's impossible for a RawMessage to be nil or []byte{}.

Think how you can parse a valid json into a RawMessage
so that it's nil or []byte{}.

**Comment by zombor** [comment]
Then why does the last example run fine? There should be some consistency, at the very least.

```go
json.Marshal(json.RawMessage(nil))
```

Outputs `"null"`

**Comment by minux** [comment]
That's because the MarshalJSON method of json.RawMessage
is defined on a pointer receiver, so if you pass a json.RawMessage
to Marshal, it will be treated the same as a []byte and not as
a RawMessage.

https://play.golang.org/p/_253EEfKke
