### ISSUE TITLE
test: fixedbugs/issue5162.go failing on netbsd/386

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10550]
netbsd/386 is consistently failing.  Often it's because of runtime/pprof flaking, but occasionally runtime/pprof actually passes, and then netbsd/386 instead fails because of fixedbugs/issue5162.go.  E.g., see http://build.golang.org/log/5cd606e7c570ce7e74602bf62b09956f4a4b2eed

    ##### ../test
    # go run run.go -- fixedbugs/issue5162.go
    exit status 1
    go build command-line-arguments: /tmp/gobuilder/netbsd-386-minux-1ccc577b8a34/go/pkg/tool/netbsd_386/8g: signal: killed
    
    FAIL	fixedbugs/issue5162.go	79.542s

It looks like that test generates a 16000 line .go file, which it then tries to run.  But it seems that 8g is dying with "signal: killed" for some reason.  I don't see any reason why Go would be purposefully sending SIGKILL to 8g in this test.

Someone with access to a netbsd/386 machine (@minux?), please try running:

    go run $GOROOT/test/fixedbugs/issue5162.go > bug.go
    go tool 8g bug.go

**Comment by ianlancetaylor** [comment]
If it's getting a SIGKILL it's probably being killed by the kernel for using too much memory.

**Comment by minux** [comment]
It's using way too much memory (~700MB) for that builder (which only has
256MB physical RAM).

we should try moving the NetBSD builders onto GCE soon.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by josharian** [comment]
This might not even be happening any more, after Russ's work to shrink Nodes. Unfortunately, the netbsd/386 builder on build.golang.org is broken for some other reason, so I can't check.

**Comment by minux** [comment]
the netbsd/386 builder has some runaway compile processes that
has eat up the cpu. Somehow the tests are leaking cmd/compile
processes.

I've restarted the builder so hope it will get better.

**Comment by alexbrainman** [comment]
Good to see you back @minux.

Alex

**Comment by minux** [comment]
Yeah, I'm back! Thanks.

The test is not failing anymore after Russ' work shrinking the Nodes.
Closing.
