### ISSUE TITLE
Why I cannot go get ?

### ISSUE THREAD

**Issue by acekingke** [golang/go#10553]
o get code.google.com/p/rog-go/exp/cmd/godef                      
package code.google.com/p/rog-go/exp/cmd/godef: Get https://code.google.com/p/rog-go/source/checkout?repo=: dial tcp 216.58.221.206:443: i/o timeout
# But 
I ping the code.google.com , ping is well:
216.58.221.206: icmp_seq=1 ttl=41 time=111.370 ms
64 bytes from 216.58.221.206: icmp_seq=2 ttl=41 time=113.357 ms
64 bytes from 216.58.221.206: icmp_seq=3 ttl=41 time=116.161 ms
64 bytes from 216.58.221.206: icmp_seq=4 ttl=41 time=111.960 ms
64 bytes from 216.58.221.206: icmp_seq=5 ttl=41 time=111.187 ms
## Can you help me?

**Comment by minux** [comment]
Please check if you can access https://code.google.com
(note the https scheme, not http)

**Comment by minux** [comment]
Please ask questions like this on the golang-nuts mailing list.
The issue tracker is for bugs. Thanks.
