### ISSUE TITLE
x/tools/cmd/stringer: index out of range in generated code

### ISSUE THREAD

**Issue by ncw** [golang/go#10563]
Save this code to `stringerbug/main.go`

```go
package main

import "fmt"

type Blob uint8

//go:generate stringer -type=Blob -output stringer.go
const (
	A Blob = iota
	B
	C
)

func main() {
	fmt.Printf("Blob(255) = %s", Blob(255).String())
}
```

Run

```
go generate
go run
./stringerbug
```

This produces the following panic

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.Blob.String(0x54d3ff, 0x0, 0x0)
	/home/ncw/Go/stringerbug/stringer.go:15 +0x1b6
main.main()
	/home/ncw/Go/stringerbug/main.go:15 +0x2b
```

The offending code being that generated by stringer

```go
func (i Blob) String() string {
	if i+1 >= Blob(len(_Blob_index)) {
		return fmt.Sprintf("Blob(%d)", i)
	}
	return _Blob_name[_Blob_index[i]:_Blob_index[i+1]]
}
```

Unfortunately adding 1 to i in the above has caused the integer to wrap.  Rewriting to

```go
func (i Blob) String() string {
	if i >= Blob(len(_Blob_index)-1) {
		return fmt.Sprintf("Blob(%d)", i)
	}
	return _Blob_name[_Blob_index[i]:_Blob_index[i+1]]
}
```

Should fix it.

**Comment by ncw** [comment]
I'm attempting to make a CL to fix...

**Comment by ncw** [comment]
Proposed fix here: https://go-review.googlesource.com/9255

**Comment by enormouspenguin** [comment]
I can see that this issue had already been [fixed](https://go.googlesource.com/tools/+/97e67f4f65bd17a63beb92f1e824f662aba1721a). But yesterday, although I did a fresh `go get golang.org/x/tools/cmd/stringer`, I still experience this same issue. Why does it still persist? Does anyone care enough to apply the fix to the main repo?
