### ISSUE TITLE
runtime/race: TestRaceRange is not always detected as a race

### ISSUE THREAD

**Issue by rsc** [golang/go#10589]
It seems to me that TestRaceRange should always be detected as a race. The code is:

	func TestRaceRange(t *testing.T) {
		const N = 2
		var a [N]int
		var x, y int
		done := make(chan bool, N)
		for i, v := range a {
			go func(i int) {
				// we don't want a write-vs-write race
				// so there is no array b here
				if i == 0 {
					x = v
				} else {
					y = v
				}
				done <- true
			}(i)
		}
		for i := 0; i < N; i++ {
			<-done
		}
	}

The actual execution is

	v = a[0]
	go func() { x = v }()
	v = a[1]
	go func() { y = v }()

and the race is between the x = v and the v = a[1].

When Austin tweaked the goroutine scheduler behavior, the race detector stopped detecting this race. Adding a Gosched brought the detection of the race back, but it seems like it should be detected even without a Gosched.

@aclements

**Comment by dvyukov** [comment]
This is a bug in race runtime. Fixed upstream:
http://llvm.org/viewvc/llvm-project?view=revision&revision=236008
Need to update race runtime, which is difficult until #8653 is resolved.

**Comment by aclements** [comment]
@dvyukov, it looks like #8653 is unresolved and has milestone Unreleased. Should we bump this issue to Unreleased?

**Comment by rsc** [comment]
It would be nice to bring in a new copy of the race runtime for Go 1.6, whether or not #8653 is fixed.

**Comment by dvyukov** [comment]
We need to resolve #8653. The project will benefit is not only me can rebuild the runtime. And even for me it is painful currently. I don't access to any windows nor darwin machines after the move.
Do we have all 4 OSes in the new infrastructure?
@bradfitz can you help me with this? I can work out the scripts, but there were issues like something is missing on the machines, or unclear how to do something.

**Comment by bradfitz** [comment]
I can answer concrete questions about the build system & gomote, but not "why doesn't the race detector build with gomote?".
