### ISSUE TITLE
cmd/8g: panic when cross-compiling from amd64

### ISSUE THREAD

**Issue by josharian** [golang/go#10580]
Grab the program from #10194. Attempt to reproduce.

Result:

```bash
$ go 10194.go 
# command-line-arguments
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x26 pc=0xacf12]

goroutine 1 [running]:
cmd/internal/ld.stkcheck(0x208b0fac0, 0x1, 0x208816700)
	src/cmd/internal/ld/lib.go:1413 +0x102
cmd/internal/ld.stkcheck(0x208b0eac0, 0x0, 0x0)
	src/cmd/internal/ld/lib.go:1463 +0x3f6
cmd/internal/ld.dostkcheck()
	src/cmd/internal/ld/lib.go:1381 +0x28b
cmd/internal/ld.Ldmain()
	src/cmd/internal/ld/pobj.go:221 +0x1a63
main.main()
	src/cmd/8l/obj.go:44 +0x20
```

This appears to have been introduced by some of the linker changes.

/cc @mwhudson @ianlancetaylor

**Comment by minux** [comment]
I couldn't reproduce this with latest 8g.
The program in #10194 runs fine on both linux/386 and darwin/386.

**Comment by mattn** [comment]
FYI, I couldn't this on windows/386. `go build` and `go run` both.

**Comment by josharian** [comment]
I can still reproduce with current tip (4a3e000a48fdfe4cbcfe8970db9c1ebec9c4b89d). And I can reproduce with hello world; this has nothing to do with #10194, sorry.

It appears to have to do with cross-compilation.

I'm using a darwin/amd64 machine. I run make.bash, then `GOARCH=386 go build ~/helloworld.go`:

```bash
$ GOARCH=386 go build -x ~/helloworld.go 
WORK=/var/folders/jw/xrvq7wz95p5bwvjyx9yc2npm390cfb/T/go-build895654364
mkdir -p $WORK/command-line-arguments/_obj/
cd /Users/jbleechersnyder
./src/go/pkg/tool/darwin_amd64/8g -o $WORK/command-line-arguments.a -trimpath $WORK -p main -complete -D _/Users/jbleechersnyder -I $WORK -pack ./helloworld.go
cd .
/Users/jbleechersnyder/src/go/pkg/tool/darwin_amd64/8l -o helloworld -L $WORK -extld=clang -buildmode=exe $WORK/command-line-arguments.a
# command-line-arguments
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x26 pc=0xacfe2]

goroutine 1 [running]:
cmd/internal/ld.stkcheck(0x208ab4320, 0x1, 0x208812620)
	/Users/jbleechersnyder/src/go/src/cmd/internal/ld/lib.go:1413 +0x102
cmd/internal/ld.stkcheck(0x208ac29c0, 0x0, 0x0)
	/Users/jbleechersnyder/src/go/src/cmd/internal/ld/lib.go:1463 +0x3f6
cmd/internal/ld.dostkcheck()
	/Users/jbleechersnyder/src/go/src/cmd/internal/ld/lib.go:1381 +0x28b
cmd/internal/ld.Ldmain()
	/Users/jbleechersnyder/src/go/src/cmd/internal/ld/pobj.go:221 +0x1a63
main.main()
	/Users/jbleechersnyder/src/go/src/cmd/8l/obj.go:44 +0x20
```

**Comment by josharian** [comment]
Yep. If I build make.bash with `GOHOSTARCH=386 GOARCH=386 ./make.bash`, then I can't reproduce.

**Comment by minux** [comment]
But my toolchain is built with GOHOSTARCH=amd64, and I still can't
reproduce.

**Comment by josharian** [comment]
@minux are you just compiling, or linking too? The crash is from the linker. I went overboard and wrote a long test for this in CL 9396. On my machine, that CL reproduces the problem. The trybots are all failing with a different error, alas--e.g. https://storage.googleapis.com/go-build-log/5fd61e6c/linux-amd64_2b23d376.log.

**Comment by minux** [comment]
I'm using GOARCH=386 go run issue10194.go. No crash.

**Comment by mwhudson** [comment]
@josharian I think all that failure is saying is that GOOS=darwin GOARCH=arm GOARM=5 is unsupported (seems GOARM=6 is the same).  Fixing that finds all sorts of other failures (e.g. "GO386=xxx go tool 8g" panic()s, I don't think solaris/386 is supported, dragonfly/386 definitely isn't supported, ...) but I didn't reproduce the reported failure.

Did you mention me because of the comment "TODO(mwhudson): actually think about this."? Apologies for the vague comment but all I did was disable some code when -linkshared or -buildmode=shared is passed. I don't think that's the cause.

**Comment by josharian** [comment]
@minux I swear I'm not crazy. I've made my test CL way less aggro, and it reproduces locally still, but my trybot reproductions have been foiled by the build breakage from CL 9224. I'll keep trying.

@mwhudson I mentioned you because the line containing the crash said things about dynamic linking. Sorry if it was a false alarm.

**Comment by josharian** [comment]
I can't reproduce on another machine or the trybots. Something is wrong locally. I don't know what, but that's my problem. :)
