### ISSUE TITLE
cmd/gc: stack split check does not follow static branch prediction rules of modern CPUs

### ISSUE THREAD

**Issue by davecheney** [golang/go#10587]
Abstract:
```
On Mon, Apr 27, 2015 at 4:20 PM, Dave Cheney <da...@cheney.net> wrote: 
> Possibly, that is how the JVM does it, but the stack check prolog is also 
> used for preemption (sort of like a safe point), and in general usage the 
> stack check is predictable by the cpu, so effectively free. 

In fact current stack split check is against static branch prediction 
rules of modern CPUs (i.e. "forward branch is not taken"). 
```

Full discussion: https://groups.google.com/d/msg/golang-nuts/DbmqfDlAR0U/elFowQ_z_UsJ

**Comment by ianlancetaylor** [comment]
In other words, instead of

        hello.go:3      0x400c00        64488b0c25f8ffffff      FS MOVQ FS:0xfffffff8, CX
        hello.go:3      0x400c09        483b6110                CMPQ 0x10(CX), SP
        hello.go:3      0x400c0d        7707                    JA 0x400c16
        hello.go:3      0x400c0f        e8fcc70400              CALL runtime.morestack_noctxt(SB)
        hello.go:3      0x400c14        ebea                    JMP main.main(SB)
        hello.go:3      0x400c16        4883ec78                SUBQ $0x78, SP

we should generate

MOVQ FS:0xfffffff8, CX
CMPQ 0x10(CX), SP
JBE <label at end of function>
SUBQ $0x78, SP
...
RET
<label at end of function>:
CALL runtime.morestack_noctxt(SB)
JMP main.main(SB)

**Comment by josharian** [comment]
https://go-review.googlesource.com/#/c/10367/ does amd64.

**Comment by josharian** [comment]
This doesn't appear to apply to arm. The arm prologue doesn't have a forward branch. Instead, it uses conditional instructions. My crude attempt at optimizing the arm prologue by focusing on the fast path was a failure. See CL 10497. Other suggestions welcomed.
