### ISSUE TITLE
Promoted type T gives access to *T receiver.

### ISSUE THREAD

**Issue by egor7** [golang/go#10581]
Hi,
I've faced the following misunderstanding. The ref/spec says that:
> Given a struct type S and a type named T, promoted methods are included in the method set of the struct as follows:
> * If S contains an anonymous field T, the method sets of S and *S both include promoted methods with receiver T. The method set of *S also includes promoted methods with receiver *T.

So I expect to get an error accessing promoted method of S with anonymouse field T with the receiver *T:  [see playground] (https://play.golang.org/p/7BPil8G9Jp)
But it compiles well and gives the correct answer instead of an error.

**Comment by rjeczalik** [comment]
@egor7 Works as expected, the example calls (*S).Val() and not (S).Val(), since it's not l-value. The lack of promotion you can observe with:

https://play.golang.org/p/miJ8-tJWzn

**Comment by dominikh** [comment]
That isn't caused by S's method set (c.f. https://play.golang.org/p/HdLASR62Js), but by syntactic sugar:

> If x is addressable and &x's method set contains m, x.m() is shorthand for (&x).m()

https://golang.org/ref/spec#Calls

(c.f. https://play.golang.org/p/gxZ8nKOeC-)

**Comment by egor7** [comment]
Thanks.
