### ISSUE TITLE
net/http: requests with empty paths redirect instead of 200

### ISSUE THREAD

**Issue by jmhodges** [golang/go#10586]
Requests to "http://example.com" (no trailing slash) always redirect to "http://example.com/" even if there is a "/" handler available. Other servers will match the lack of path with the "/" handler as expected.

**Comment by bradfitz** [comment]
More info please.

It's unclear whether you mean your browser doing this (in which case it's not even a redirect), or ServeMux, etc. And if ServeMux, with or without hostnames in the pattern.

**Comment by jmhodges** [comment]
The browsers and curl are doing it. It happens with both hostnames and no hostname in the pattern. I have a patch to propose.

**Comment by bradfitz** [comment]
I still don't understand so I'm curious to see your patch.

**Comment by jmhodges** [comment]
Posted

**Comment by jmhodges** [comment]
This is a problem in using NewRequest in the tests, not here. Confirmation I thought I had done was not done. Sorry for the noise.

**Comment by bradfitz** [comment]
There's an open documentation bug for that already.
