### ISSUE TITLE
x/mobile: gomobile bind cannot build sqlite package

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10584]
From Matt Hawkins via golang-nuts:

```
$ gomobile bind
# github.com/mattn/go-sqlite3
/Users/mhawkins/Library/go/pkg/gomobile/android-ndk-r10d/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
collect2: error: ld returned 1 exit status
gomobile: exit status 2
```

**Comment by hyangah** [comment]
fyi. on android, -lpthread is not necessary and linked automatically. http://mobilepearls.com/labs/native-android-api/ndk/docs/STABLE-APIS.html

**Comment by minux** [comment]
The lpthread comes from go-sqlite3:

https://github.com/mattn/go-sqlite3/commit/308067797b0fcce4ca06362580dc6db77c1bfeda
