### ISSUE TITLE
x/sys/unix: missing Fallocate constants

### ISSUE THREAD

**Issue by spakin** [golang/go#10599]
I'd like to use the `Fallocate` function from `golang.org/x/sys/unix` but found that it's missing the `FALLOC_FL_*` constants from `/usr/include/linux/falloc.h`.  I believe the following patch to `golang.org/x/sys/unix/mkerrors.sh` should address the issue:

``` diff
--- golang.org/x/sys/unix/mkerrors.sh.ORIG      2015-04-28 15:43:03.195157047 -0600
+++ golang.org/x/sys/unix/mkerrors.sh   2015-04-28 15:41:41.207778564 -0600
@@ -102,6 +102,7 @@
 #include <sys/types.h>
 #include <sys/time.h>
 #include <sys/socket.h>
+#include <linux/falloc.h>
 #include <linux/if.h>
 #include <linux/if_arp.h>
 #include <linux/if_ether.h>
@@ -272,6 +273,7 @@
                $2 ~ /^IN_/ ||
                $2 ~ /^LOCK_(SH|EX|NB|UN)$/ ||
                $2 ~ /^(AF|SOCK|SO|SOL|IPPROTO|IP|IPV6|ICMP6|TCP|EVFILT|NOTE|EV|SHUT|PROT|MAP|PACKET|MSG|SCM|MCL|DT|MADV|PR)_/ ||
+                $2 ~ /^FALLOC_/ ||
                $2 == "ICMPV6_FILTER" ||
                $2 == "SOMAXCONN" ||
                $2 == "NAME_MAX" ||
```

Thanks,
— Scott

**Comment by maxime1986** [comment]
This issue is still present in latest source.
Does the proposed patch have some error ?
Can you (go commiter) give us some feedback ?

**Comment by ALTree** [comment]
Usually patches sent to the issue tracker are not looked at; patches should be sent via gerrit, see [contribuing - code review](https://golang.org/doc/contribute.html#Code_review).

**Comment by grzegorz-zur** [comment]
I looked at similar issues #15114 and #16816 on fadvise syscall constants. As far as I understand, the fix would be to manually add the constants in the go.googlesource.com/sys project instead of changing mkerrors.sh script. Is it correct?

**Comment by ianlancetaylor** [comment]
No, it would be better to change the relevant script.

**Comment by tchernomax** [comment]
I just submitted the patch to gerrit:
https://go-review.googlesource.com/#/c/36336/

(by the way: the contribution procedure to golang is a pain in the ass)
