### ISSUE TITLE
testing: align -v output

### ISSUE THREAD

**Issue by mdwhatcott** [golang/go#10594]
The go test output might be easier to read if it test function names were aligned, much like gofmt treats struct definitions. Here's what it normally looks like:

```
=== RUN TestGroupContextListings
--- PASS: TestGroupContextListings (0.00s)
=== RUN TestIdentifyCompletedTasks
--- FAIL: TestIdentifyCompletedTasks (0.00s)
=== RUN TestIdentifyStalledProjects
--- PASS: TestIdentifyStalledProjects (0.00s)
=== RUN TestIdentifyFinishedProjects
--- PASS: TestIdentifyFinishedProjects (0.00s)
FAIL
exit status 1
FAIL	github.com/blahblah/blah	0.004s
```

Here's how a tiny bit of formatting could improve things:

```
=== RUN   TestGroupContextListings
--- PASS: TestGroupContextListings (0.00s)
=== RUN   TestIdentifyCompletedTasks
--- FAIL: TestIdentifyCompletedTasks (0.00s)
=== RUN   TestIdentifyStalledProjects
--- PASS: TestIdentifyStalledProjects (0.00s)
=== RUN   TestIdentifyFinishedProjects
--- PASS: TestIdentifyFinishedProjects (0.00s)
FAIL
exit status 1
FAIL	github.com/blahblah/blah	0.004s
```

**Comment by robpike** [comment]
All that would be needed for those using a fixed-width font would be to add two spaces after "RUN". I am a little bothered by the inconsistency of "RUN" vs "PASS:", the latter having a colon, but it's inconsistent in having the time as well.

In the likely event no one depends on the particular format, this issue is trivial. After all, it's -v output.

**Comment by mdwhatcott** [comment]
I'm unsure of the status of this issue (I'm new to the workflow here). The issue was closed, but I don't think the idea was rejected (?). @robpike, is there something I should do to move this forward?

**Comment by josharian** [comment]
Given that @robpike added this to the Go1.5 milestone, and given his comment, I think that it was closed by accident. Re-opening.

If we're repainting sheds, we could reduce the noise levels while we're at it and remove those pesky inconsistent colons:

```bash
=== RUN   TestGroupContextListings
    PASS  TestGroupContextListings (0.00s)
=== RUN   TestIdentifyCompletedTasks
    FAIL  TestIdentifyCompletedTasks (0.00s)
=== RUN   TestIdentifyStalledProjects
    PASS  TestIdentifyStalledProjects (0.00s)
=== RUN   TestIdentifyFinishedProjects
    PASS  TestIdentifyFinishedProjects (0.00s)
FAIL
```

I thought briefly that the hyphens might be to help keep things roughly aligned for those using variable-width fonts, but hyphens have different width than equal signs anyway. If we want that, an en dash will be much closer:

```bash
=== RUN   TestGroupContextListings
––– PASS  TestGroupContextListings (0.00s)
=== RUN   TestIdentifyCompletedTasks
––– FAIL  TestIdentifyCompletedTasks (0.00s)
=== RUN   TestIdentifyStalledProjects
––– PASS  TestIdentifyStalledProjects (0.00s)
=== RUN   TestIdentifyFinishedProjects
––– PASS  TestIdentifyFinishedProjects (0.00s)
FAIL
```

**Comment by mdwhatcott** [comment]
Thanks @josharian for re-opening and for adding your thoughts. I like where you're taking it.

**Comment by robpike** [comment]
Not sure why I closed it. I didn't mean to: I plan to fix it.

I'm not going with em dashes. Since it's about alignment, the assumption is fixed width fonts and ASCII characters or it all comes apart.

**Comment by mdwhatcott** [comment]
Thanks @robpike.

**Comment by dchapes** [comment]
@josharian the "---" might be there to help separate that from `t.Log` output, or perhaps to make it easier to distinguish from the final PASS/FAIL or somesuch.

I.e. consider fuller output:

    === RUN TestA
    --- PASS: TestA (0.00s)
    === RUN TestB
    --- PASS: TestB (0.00s)
            b_test.go:25: some log message
            b_test.go:26: and another
    PASS

I've see some multi-line t.Log messages use "\n\t…" to line up so it'd be nice to not change the leading tab used for those.
