### ISSUE TITLE
playground: even if the process took too long, the existing output should still be sent to the browser

### ISSUE THREAD

**Issue by minux** [golang/go#10590]
Otherwise this interesting snippet won't work anymore.
http://play.golang.org/p/Ko42TepMsN

It used to show an animation, and after a few seconds stop with
"process took too long".

Now all it shows is "process took too long".

**Comment by ysmolsky** [comment]
Is this something still needed? It can be done, just was curious about the relevancy of this.

**Comment by ysmolsky** [comment]
@dmitshur, this ticket can be closed after the deployment.

**Comment by dmitshur** [comment]
Deployed, thank you Yury!

The original link seems to be cached and producing same result as before, but if you make a trivial change (add a space) and run, it works:

https://play.golang.org/p/gk5_ztX95m7
