### ISSUE TITLE
cmd/link: -B has no effect when linking externally

### ISSUE THREAD

**Issue by mwhudson** [golang/go#10607]
All notes, including the build id if passed, are not written when -linkmode=external.

I don't really know if this is a problem as I don't know what uses -B is used for but it confused me for a while.

**Comment by ianlancetaylor** [comment]
We should translate -B into -Wl,--build-id when invoking the external linker.

I think I don't notice this because on Ubuntu the external linker defaults to -Wl,--build-id anyhow.

**Comment by mwhudson** [comment]
We could also write the buildid note ourselves and pass -Wl,--build-id=none.

**Comment by rsc** [comment]
If we translate -B note into -Wl,--build-id, then we lose the note that was requested. It seems to me we should write the buildid note ourselves and pass -Wl,--build-id=none.

Ian, Michael, thoughts? I'm happy to write the CL.

**Comment by mwhudson** [comment]
I filed this bug because I found the behaviour confusing rather than preventing me doing anything. It would be nice to have it fixed and your proposal makes a lot of sense, but I don't know if it's worth doing for 1.5.

**Comment by ianlancetaylor** [comment]
We should translate "-B 0xabcdef" into "-Wl,--build-id=0xabcdef".  The format of the value is identical, which is not a coincidence.
