### ISSUE TITLE
build: reverse buildlet failed to clean up removed file in $GOROOT?

### ISSUE THREAD

**Issue by minux** [golang/go#10604]
After https://golang.org/cl/9461 is submitted, the new darwin/amd64 builder
starts to fail with multiple declaration erros, which doesn't make sense, as one
of the conflicting file is removed by that CL.

http://build.golang.org/log/fd15555a76804eb108e9458bbc253a7b6ebba7b3

/cc @crawshaw @bradfitz

**Comment by mikioh** [comment]
git log --stat --follow src/net/external_test.go says:
```
src/net/{dialgoogle_test.go => external_test.go} | 0
1 file changed, 0 insertions(+), 0 deletions(-)
```

**Comment by minux** [comment]
Yeah, I know. I think your commit is correct. Something is wrong with
that builder.

**Comment by minux** [comment]
Fixed by https://golang.org/cl/9458.
