### ISSUE TITLE
mime/multipart: two boundaries can't have the same prefix

### ISSUE THREAD

**Issue by kgilonne** [golang/go#10616]
Hello,
I encounter difficulties to parse a MIME file, due to 2 boundaries:.

Content-Type: multipart/related; boundary="----=_NextPart_eedf1356402a50765728c12998413837"
Content-Type: multipart/alternative; boundary="----=_NextPart_eedf1356402a50765728c12998413837_alt"

It throws the error: "unexpected EOF"
And finally, after several test, I have found that it's because the first is the prefix of the second and mime/multipart package which looking for boundaries with bytes.Index(...) (multipart.go l.174).

**Comment by bradfitz** [comment]
Do you have the complete input file, or a minimal repro? What generated it?

Is this a multipart document embedded in a multipart part?

I can imagine what the bug might be, but I'd still like to have a repro case. It would save me time trying to generate it.

**Comment by kgilonne** [comment]
MIME-Version: 1.0
X-Mailer: PHP/5.4.25
Content-Type: multipart/related; boundary="----=_NextPart_4c2fbafd7ec4c8bf08034fe724b608d9"

------=_NextPart_4c2fbafd7ec4c8bf08034fe724b608d9
Content-Type: multipart/alternative; boundary="----=_NextPart_4c2fbafd7ec4c8bf08034fe724b608d9_alt"

------=_NextPart_4c2fbafd7ec4c8bf08034fe724b608d9_alt
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.

------=_NextPart_4c2fbafd7ec4c8bf08034fe724b608d9_alt
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
<body>
Long Body
</body>
</html>

**Comment by bradfitz** [comment]
Thanks.

**Comment by kgilonne** [comment]
This fix works for me:
https://play.golang.org/p/p4-qqQLEW5

At the line 36,
I check if the nlDashBoundary found is terminated by a '\n'
else if the dashBoundaryDash is found.

I'm not sure if this works for all the case.

**Comment by rsc** [comment]
Too late for Go 1.5.

**Comment by bradfitz** [comment]
@rsc, I have a fix for this at https://go-review.googlesource.com/11811 and it'd still be nice to get into Go 1.5 since this isn't some hypothetically fuzzer case, but generated by a real client library, and this is our fault.
