### ISSUE TITLE
container/list: list.go, Are these places can do little optimization

### ISSUE THREAD

**Issue by chanxuehong** [golang/go#10625]
https://github.com/golang/go/blob/master/src/container/list/list.go#L185
https://github.com/golang/go/blob/master/src/container/list/list.go#L194

For MoveBefore, if e == mark.prev, we can do nothing, 
MoveAfter also a reason

If I remember correctly, MoveBefore originally had such pr, also accepted, but not now how, and who can give me a reply

```Go
// MoveBefore moves element e to its new position before mark.
// If e or mark is not an element of l, or e == mark, the list is not modified.
func (l *List) MoveBefore(e, mark *Element) {
	if e.list != l || mark.list != l  || e == mark || e == mark.prev{
		return
	}
	l.insert(l.remove(e), mark.prev)
}

// MoveAfter moves element e to its new position after mark.
// If e or mark is not an element of l, or e == mark, the list is not modified.
func (l *List) MoveAfter(e, mark *Element) {
	if e.list != l || mark.list != l || e == mark || e == mark.next {
		return
	}
	l.insert(l.remove(e), mark)
}
```

**Comment by bradfitz** [comment]
This is better discussed on the golang-dev@ mailing list.  But unless there's a bug or major performance problem, we're unlikely to accept any changes to this code. This code is effectively frozen.
