### ISSUE TITLE
cmd/go: "go test -i" rebuilds unrelated packages

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#10627]
Why changing one file in runtime makes "go test -i" rebuild fmt package (and others). Perhaps I am dreaming, but I don't think "go test -i" used to do that:

```
# pwd
/root/go/root/src/runtime
# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
# go test -i -v
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
bytes
math
syscall
time
os
strconv
reflect
fmt
sort
flag
strings
path/filepath
io/ioutil
math/cmplx
math/rand
os/exec
regexp/syntax
regexp
runtime/debug
bufio
text/tabwriter
runtime/pprof
testing
net/url
text/template/parse
text/template
# go test -i -v
# touch stack1.go
# go test -i -v
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
bytes
math
syscall
time
os
strconv
reflect
fmt
sort
flag
strings
path/filepath
io/ioutil
math/cmplx
math/rand
os/exec
regexp/syntax
regexp
runtime/debug
bufio
text/tabwriter
runtime/pprof
testing
net/url
text/template/parse
text/template
#
```

Alex

**Comment by minux** [comment]
I those those packages are the imported by the testing package.

**Comment by alexbrainman** [comment]
Did you mean "these packages are imported by the testing package"? But why changing runtime package make testing package out of date and in need of rebuild?

Alex

**Comment by minux** [comment]
Everything relies on the runtime package, and "go test -i" means installing
everything
needed to test this package, so modifying runtime will cause every package
needed
by the runtime tests to reinstall.

**Comment by alexbrainman** [comment]
I have made it up. Probably, because the "go test -i" is much slower now. Sorry.

Alex
