### ISSUE TITLE
cmd/5g: test/bench/shootout/nbody.go produces incorrect results with arm soft float

### ISSUE THREAD

**Issue by davecheney** [golang/go#10629]
The `../test/bench/shootout/nbody.go` test produces incorrect results when compiled on linux/arm with soft float

```
dfc@debian:~/go/test/bench/shootout$ gcc -O2 nbody.c -lm
dfc@debian:~/go/test/bench/shootout$ ./a.out -n 50000000
-0.169075164
-0.169075164
dfc@debian:~/go/test/bench/shootout$ go run nbody.go
-0.169075164
0.902556904
```

**Comment by josharian** [comment]
Have you git bisected? Based on the comment in #10641, I wonder whether this was introduced by converting math.Sqrt into a hardware instruction (CL 8356).

**Comment by josharian** [comment]
Closing this in favor of #10641, since that has more detail.
