### ISSUE TITLE
encoding/binary: can Read []byte in struct directly but cant Read whole struct 

### ISSUE THREAD

**Issue by analogic** [golang/go#10633]
Hi
i have this code (simplified):

```
type Section4 struct {
    LocalUse []byte
}

func readSection4(f *os.File, len uint32) (section Section4, err error) {   
   section.LocalUse = make([]byte, len)

   // this will work OK
    err = binary.Read(f, binary.BigEndian, &section.LocalUse)

    // this will end with ERROR: binary.Read: invalid type []uint8
    err = binary.Read(f, binary.BigEndian, &section)
}
```

**Comment by ianlancetaylor** [comment]
This is behaving as documented.  "Data must be a pointer to a fixed-size value or a slice of fixed-size values."  Passing &section.LocalUse is a pointer to a slice of fixed-size values.  Passing &section is not a pointer to a fixed-size value, because the struct contains a slice.
