### ISSUE TITLE
x/mobile/audio/al: current context gets GCed causing playback to stop unexpectedly

### ISSUE THREAD

**Issue by TheDasc** [golang/go#10636]
reproduced with go 1.4.2 amd64 on linux/ubuntu amd64
following code reproduces the issue (uncomment the line for correct behaviour)
since there are no more references to context after setting it as current, GC may remove it, triggering its finalizer which calls context.Destroy() thus stopping playback
this affects x/mobile/audio as a consequence

```
package main

import (
	"fmt"
	"golang.org/x/mobile/audio/al"
	"math"
)

func main() {
	samplesPerSecond := int64(44100)
	frequency := int64(1500)

	device := al.Open("")
	context := device.CreateContext(nil)
	al.MakeContextCurrent(context)

	buffers := al.GenBuffers(1)
	bytes := make([]byte, 100000)
	FillBufferMono8(bytes, samplesPerSecond, frequency)
	buffers[0].BufferData(uint32(0x1100), bytes, int32(samplesPerSecond))

	sources := al.GenSources(1)
	sources[0].QueueBuffers(buffers)
	al.PlaySources(sources[0])

	waiter := make(chan int)
	<-waiter
	fmt.Println("you won't see this")

	al.DeleteSources(sources[0])
	al.DeleteBuffers(buffers)
	//context.Destroy() // Uncomment this line
	device.Close()
}

func FillBufferMono8(buffer []byte, samplesPerSecond int64, frequency int64) {
	bufferLength := len(buffer)
	for i := int64(0); i < int64(bufferLength); i++ {
		sampleIndex := i
		sinResult := math.Sin(math.Pi * 2 * (float64(sampleIndex%samplesPerSecond) / float64(samplesPerSecond)) * float64(frequency))
		sample := byte(255 * 0.5 * (1.0 + sinResult))
		buffer[i] = sample
	}
}
```

discussion [here](https://groups.google.com/forum/#!topic/golang-nuts/_VsXoDoWR5s)

**Comment by rakyll** [comment]
I will be pinning the current context to avoid the unwanted collection.

This issue is not reproducible on Mac OSX. The finalizer is invoked, but Destroy doesn't destroy the context since it is still in use. The Open AL specification says it's illegal to call alcDestroyContext if the given context is current. So, the Linux implementation seems to be buggy for destroying the current context.

Additionally, it became clear that the Context finalizer should do some additional job to set the current context to NULL, otherwise the current context is not destroyed on some platforms and we leak.

**Comment by RLH** [comment]
One should not rely on the finalizer to execute in a timely fashion.
Furthermore finalizers are expensive for the GC to maintain and they fire
at non-deterministic times. They should be a mechanism of last resort.

**Comment by rakyll** [comment]
Mailed a CL to remove the finalizer, see https://go-review.googlesource.com/#/c/9519/.

**Comment by TheDasc** [comment]
I think that CL makes x/mobile/audio player leak the OpenAL context, it looks like there is no context.Destroy() call inside x/mobile/audio

**Comment by rakyll** [comment]
Please keep the convo on the CL.

The audio package will not have a package-level Destroy, but will count the current players and will auto destroy the context and the device if there are no more players around. It's a TODO for now, leaking a single context and device instance is not fatal nor wasting much resources. These packages are still work-in-progress, so keep an eye on what TODOs are saying please.
