### ISSUE TITLE
x/tools/cmd/vet: detect simple parallel goroutine race conditions

### ISSUE THREAD

**Issue by tve** [golang/go#10647]
A trap I commonly fall into is to parallelize a loop by doing something like:
```
for i := ... {
  ...
  go func() {
    <some use of i>
  }
}
```
A similar example is:
```
for i, v := range ... {
  go func() {
   <some use of i or v>
  }
}
```
It would be awesome if go vet would catch these simple problems. There is a more general case where the body of the goroutine refers to other variables from the environment but that can't be reliably detected using static analysis. However, I would expect that the simple checks against use of the index variables will flag many of the problematic situations.
Thanks!

**Comment by mdempsky** [comment]
I would love this.  Those exact patterns bite me all the time.

**Comment by mdempsky** [comment]
Wait, isn't this what https://github.com/golang/tools/blob/master/cmd/vet/rangeloop.go checks for?

**Comment by robpike** [comment]
I believe this particular check is already installed in vet. If you disagree, or have another common error that it could detect, please reopen the issue.
