### ISSUE TITLE
gccgo: internal compilation error adding constant strings with type conversions

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#10642]
This simple file causes an internal error when compiled with gccgo.

package p

const (
	S1 = "a" + S2
	S2 = string("b")
)

go1: internal compiler error: in insert, at go/gofrontend/gogo.cc:7888
0x655984 Statement_inserter::insert(Statement*)
	../../gccgo3/gcc/go/gofrontend/gogo.cc:7888
0x6168e3 Binary_expression::do_flatten(Gogo*, Named_object*, Statement_inserter*)
	../../gccgo3/gcc/go/gofrontend/expressions.cc:5126
0x6465d3 Expression::flatten(Gogo*, Named_object*, Statement_inserter*)
	../../gccgo3/gcc/go/gofrontend/expressions.h:803
0x6465d3 Flatten::expression(Expression**)
	../../gccgo3/gcc/go/gofrontend/gogo.cc:3866
0x61858d Expression::traverse(Expression**, Traverse*)
	../../gccgo3/gcc/go/gofrontend/expressions.cc:43
0x64c571 Named_constant::traverse_expression(Traverse*)
	../../gccgo3/gcc/go/gofrontend/gogo.cc:6538
0x64c571 Bindings::traverse(Traverse*, bool)
	../../gccgo3/gcc/go/gofrontend/gogo.cc:7486
0x64c731 Gogo::traverse(Traverse*)
	../../gccgo3/gcc/go/gofrontend/gogo.cc:2491
0x64c98f Gogo::flatten()
	../../gccgo3/gcc/go/gofrontend/gogo.cc:3900
0x64619b go_parse_input_files(char const**, unsigned int, bool, bool)
	../../gccgo3/gcc/go/gofrontend/go.cc:139
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by minux** [comment]
Fixed by golang.org/cl/237960043.

**Comment by ianlancetaylor** [comment]
This is now fixed.
