### ISSUE TITLE
runtime/cgo: exc_server is not public API for the iOS ports

### ISSUE THREAD

**Issue by minux** [golang/go#10646]
I received a complaint that Go app failed app store check.
(see https://bitbucket.org/minux/goios/issue/7/cannot-build-for-arm64)

```
Error: iTunes Store operation failed. Your app contains non-public API usage. This app references non-public symbols ... exc_server.
```

Instead of forcing the user to use the lldb build tag, we should make the builder
use another build tag.

/cc @crawshaw

**Comment by crawshaw** [comment]
Thanks, I didn't realize it was not public.

As it only matters when running via lldb, and lldb is usually a test, I suggest we only enable it by default when building tests.

**Comment by scosman** [comment]
Thanks @minux & @crawshaw !

**Comment by crawshaw** [comment]
@scosman if you are building an app with Go, I would enjoy trying it out. If it's public, please send a note when you launch it.

**Comment by scosman** [comment]
@crawshaw evaluating it for now. @jamesshoebox is the expert, he'll probably release our test app.

**Comment by jamesshoebox** [comment]
It works! Here's a demo app I threw together: https://github.com/jamesshoebox/GoIOSDemo

**Comment by crawshaw** [comment]
I realize this is not the right forum for this discussion, but as I don't have your email addresses:

If you are looking into adding Go to an iOS app, you may want to consider the new -buildmode=c-archive that is in tip. You create a package main with an empty func main() {}, then cgo //export any functions you want to call from Objective-C. Then: ```go build -buildmode=c-archive yourpkg``` to produce a .a file you can drop into Xcode.

There will be more documentation about this as we get gobind working for iOS.
