### ISSUE TITLE
encoding/json: marshal does not obey omitempty for empty structures

### ISSUE THREAD

**Issue by crawford** [golang/go#10648]
Continuing from #9585...

> A struct value cannot be 'empty'

Why can't a struct value be empty? My understanding is that the purpose of "omitempty" is to avoid marshalling information that is implicitly understood (e.g. if a value is not set, then it should be the zero value). Given this understanding (which may be flawed; please correct me if I am wrong), it would make sense to compare each field value with the output of [reflect.Zero](http://golang.org/pkg/reflect/#Zero) (since this is the value that Go will create) and use this comparison as the basis for [isEmptyValue](http://golang.org/src/encoding/json/encode.go?s=9105:9654#L280).

Given the following type declaration:

```go
type MyType struct {
    Field struct {
        SubField int `json:"subfield,omitempty"`
    } `json:"field,omitempty"`
}
```

I would expect `MyType{}` to json.Marshal into `{}` because there is no extra data needed to reconstruct this object. Instead, it marshals to `{"field":{}}`, even though this doesn't actually encode any more information. (http://play.golang.org/p/xZP2gafHY9)

I would expect that either:
 - [isEmptyValue](http://golang.org/src/encoding/json/encode.go?s=9105:9654#L280) uses [reflect.Zero](http://golang.org/pkg/reflect/#Zero) to do the comparison
 - [isEmptyValue](http://golang.org/src/encoding/json/encode.go?s=9105:9654#L280) recursively checks to see if the member fields are empty (if the object is a struct)

**Comment by bradfitz** [comment]
This bites me with time.Time{} values often. Camlistore has its own time.Time alias, just so we can do JSON differently.

**Comment by joeshaw** [comment]
See also #4357, which may be a dup.

This bites me often too, I'm highly motivated to fix this for 1.6 if no one else takes it on first.

**Comment by rsc** [comment]
FWIW, `struct{}` is an empty struct. A zero struct is not the same thing.

**Comment by crawford** [comment]
What is the difference?

**Comment by crawford** [comment]
Oh nevermind, I understand what you are getting at. Yes, when I said "empty struct", I actually intended "zero struct".

**Comment by rsc** [comment]
Not for 1.7, and I think we should leave omitempty completely alone. I've been thinking about going along with "omitzero" but there are other things to think about there.

**Comment by crawford** [comment]
@rsc yeah, I've been thinking about this as well (for whatever reason I seem to write a lot of Go-JSON interfaces) and I'm not sure that Go can adequately represent the JSON data. I'm of the opinion that Go would need algebraic types. Using another tag like "omitzero" would allow the programmer to direct the marshaller to do an appropriate conversion though. So I guess I'm also in favor of not changing "omitempty". Feel free to close.

**Comment by dionb** [comment]
I am having the same issue with encoding/xml. I like the omitzero idea.

**Comment by adg** [comment]
This is more or less the same issue as #11939. Let's focus discussion there.
