### ISSUE TITLE
cmd/6g: trimpath no longer understands /proc/self/cwd

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10657]
The semantics of -trimpath have changed slightly.

```
package main

import "runtime"

func main() {
        _, p, _, _ := runtime.Caller(1)
        println(p)
}
```

With Go 1.4:

```
$ PWD=/proc/self/cwd/../crawshaw go tool 6g -trimpath /proc/self/cwd/../crawshaw junk.go 
$ go tool 6l junk.6
$ ./6.out 
junk.go
```

With tip:

```
$ PWD=/proc/self/cwd/../crawshaw go tool 6g -trimpath /proc/self/cwd/../crawshaw junk.go 
$ go tool 6l junk.6
$ ./6.out 
/proc/self/crawshaw/junk.go
```

I admit this is an obscure and non-obvious feature. I'm reporting this because it breaks an existing custom build tool. And the new behavior doesn't really make sense.

**Comment by mdempsky** [comment]
I think the issue you're running into is that line history path entries are now cleaned with filepath.Clean (added in 86154654), but the -trimpath flag is not.  So in your example, "/proc/self/cwd/.../crawshaw/junk.go" is cleaned to "/proc/self/crawshaw/junk.go" which doesn't match your -trimpath.

**Comment by crawshaw** [comment]
I believe the basic problem in the new code is:

```
package main

import (
        "fmt"
        "os"
        "path/filepath"
)

func main() {
        wd, _ := os.Getwd()
        fmt.Println(wd)
        fmt.Println(filepath.Join(wd, "afile"))
}
```

Produces:

```
$ PWD=/proc/self/cwd/../crawshaw ./main
/proc/self/cwd/../crawshaw
/proc/self/crawshaw/afile
```

I don't know if os.Getwd should be doing something friendlier here, but at this point I'm not really sure there's anything wrong with the compiler's behavior.

**Comment by ianlancetaylor** [comment]
I think the compiler is acting reasonably for reasonable inputs.  I don't think there is any need to change anything here.
