### ISSUE TITLE
time.Now() not accurate

### ISSUE THREAD

**Issue by kgao** [golang/go#10663]
Context: /flowcontrol/10

Today is Friday, May 1st 2015...
It output wrong time use go's time package.

----------
import (
	"fmt"
	"time"
)

func main() {
	today := time.Now().Weekday()
	fmt.Println("When's Today?", today)
        t := time.Now()
	fmt.Println("What's the time now?", t)
}

----------
When's Today? Tuesday
What's the time now? 2009-11-10 23:00:00 +0000 UTC

**Comment by davecheney** [comment]
I'm assuming you ran this program in the Go playground.

http://play.golang.org/p/_s5f33sTaH

The time in the playground is fixed, it is always the date and time of the Go announcement. 

In future, this question is best directed to the mailing list, the issue tracker is for bugs.

**Comment by kingjolab** [comment]
time.Now()
is not accurate, when I write it to mongodb.
and when I compare with python time.now() function,

**Comment by davecheney** [comment]
@kingjolab 

The time in the playground is fixed, it is always the date and time of the Go announcement.

In future, this question is best directed to the mailing list, the issue tracker is for bugs.
