### ISSUE TITLE
clang builder fails in testshared

### ISSUE THREAD

**Issue by randall77** [golang/go#10660]
Looks like the testshared test fails if we're using clang as the C compiler.

../misc/cgo/testshared
/tmp/go-build283730525/libruntime,runtime-cgo,sync-atomic.so
/tmp/buildlet-scatch050922484/go/pkg/tool/linux_amd64/6l: running gcc failed: exec: "gcc": executable file not found in $PATH

Full transcript here:
http://build.golang.org/log/957d63f308db34a3b77010d748739f9459c8c024

**Comment by davecheney** [comment]
https://go-review.googlesource.com/#/c/9526/
