### ISSUE TITLE
tour: typo on /methods/8

### ISSUE THREAD

**Issue by diegoberaldin** [golang/go#10667]
Context: /methods/8

Describe your feedback here, including code if necessary

Unless it is an intended pun - which I don't get unfortunately :joy: - there is a typo in the second line of the lesson explanation: "similar" is misspelt as "simliar".

**Comment by robpike** [comment]
How do I assign this to campoy (github user name) campoy@golang.org (mail address)? The assignee box won't accept either.

**Comment by adg** [comment]
Minux has fixed it. Added @campoy to the go-approvers list, so he can now be an assignee.
