### ISSUE TITLE
cmd/goimports: flag for only importing standard lib

### ISSUE THREAD

**Issue by tpng** [golang/go#10679]
Is it possible to add a flag for goimports to only work on the stdlib? (i.e. ignoring GOPATH)

Reasons:
1. parsing GOPATH on a spinning hard disk with a large src size (e.g 1G) takes a long time
2. if you are importing 3rd party lib, you are probably adding the imports yourself at the beginning

In my opinion, the cost of parsing GOPATH is not worth the benefit for some users, so adding a flag to goimports can improve their productivity. (e.g. avoid freezing the editor on save)

**Comment by bradfitz** [comment]
Sorry, goimports doesn't take flags. You can just not set a GOPATH. Or we should fix any performance problems. The answer isn't flags, though.

**Comment by tpng** [comment]
Thanks, that make sense. We should fix the root cause instead.

Until that happens, workaround for only importing stdlib (unset GOPATH for goimports):

1.  make the following change to ```golang.org/x/tools/imports/fix.go``` in GOPATH
    ```
@@ -190,6 +190,7 @@
 	 	pkgIndex.Unlock()
 
 	 	var wg sync.WaitGroup
+	build.Default.GOPATH = ""
 	 	for _, path := range build.Default.SrcDirs() {
 		 	fsgate.enter()
 		 	f, err := os.Open(path)
    ```
2.  ```go install golang.org/x/tools/cmd/goimports```

**Comment by minux** [comment]
By "not set a GOPATH", Brad means that you unset GOPATH before invoking
goimports.
This doesn't require changes to the goimports source code, just you
editor's hook.

**Comment by tpng** [comment]
Yes, if it is possible unset GOPATH only for goimports on Windows I would like to do that instead, any way to do it?
