### ISSUE TITLE
doc/install/source: installing from HEAD shouldn't be labelled optional

### ISSUE THREAD

**Issue by rakyll** [golang/go#10670]
gomobile requires 1.5 and we would like to give a reference to the installation guide [1] from http://godoc.org/golang.org/x/mobile/cmd/gomobile, but the "Optional" mark right next to the section entitled as "Switch to the master branch" will confuse those who are following the steps.

Isn't it possible to make this mark less bold by removing it from the title and mentioning that the master branch is the current development branch in the paragraph underneath the title?

An alternative would be a separate guide that explains how to install Go from the tip.

cc/ @adg @hyangah 

[1] http://tip.golang.org/doc/install/source

**Comment by minux** [comment]
That shouldn't be a problem after Go 1.5 is released, right?
Could gomobile just recommand the binary release distributions?

Or gomobile could download and build tip by its own if the current
Go version is not sufficient.

**Comment by rakyll** [comment]
> That shouldn't be a problem after Go 1.5 is released, right?

True.

> Could gomobile just recommand the binary release distributions?

Could you extend your proposal here? I don't truly understand what's your suggestion but gomobile requires 1.5 to be built and run. So, it can't tell anything to the user if user doesn't have 1.5 already.

> Or gomobile could download and build tip by its own if the current Go version is not sufficient

It would require us shipping binaries for each host platform. Much work and it will be useless once 1.5 is released.

**Comment by minux** [comment]
I mean, gomobile, as a command, doesn't require Go 1.5 features
to build, right?

at gomobile init time, if it detects that the user doesn't have Go 1.5
or higher, it can download go tip and compile. Relying the user to
compile Go 1.5 for gomobile is probably too much work, esp. the
targeted audience is mobile app developer, not necessarily a user
that follows Go development itself closely.

It can also detect if Go 1.5 is released, and if it's, offer the user a
way to use prebuilt binary distributions from https://golang.org/dl.

**Comment by rakyll** [comment]
`gomobile bind` requires 1.5, therefore gomobile as a command requires 1.5 to build. We can do some arrangements but I am not sure it's worthy to follow this path.

On the other hand, for cross compilation we need the Go source at the gomobile init stage. For a newcomer, it is too much work to checkout the source (note that some distributions don't distribute the source), get the gomobile command and run gomobile init. Should init do it all for itself? Maybe.

cc/ @crawshaw

**Comment by minux** [comment]
OK, perhaps we should separate gomobile bind from gomobile (use build tag?)
so that users of Go 1.4 can build gomobile, but won't have the gobind
functionality.

gomobile init should rebuild itslef after building Go 1.5.

Alternatively, just document that gomobile requires Go 1.5, and if you
don't know
how to install Go 1.5 now, just wait for 3 months for the official release.

**Comment by crawshaw** [comment]
Let's not overdo this. The gomobile tool needs Go 1.5. For now people need to build from source.

It's OK to just say "you need to build from source" and let them work it out. If they can't, they should wait for the Go 1.5 release. We don't need to change the tool.

**Comment by rakyll** [comment]
Giving this another thought, I can easily say that the current gomobile instructions to build Go 1.5 are good enough. We don't need to depend on /doc/install/source. Bothering the installation guide to match our temporary needs is not reasonable. I am closing this issue.
