### ISSUE TITLE
misc/ios: document ideviceinfo

### ISSUE THREAD

**Issue by rakyll** [golang/go#10672]
detect.go shells out to a command named ideviceinfo. It's not clear how to install this binary and where it comes from. Document the installation steps or give a link to an equivalent doc.

**Comment by minux** [comment]
It's from libimobiledevice.

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/9688/.

**Comment by rakyll** [comment]
Closed via 032811e2ab7359819ddf9df40c06a1d5d673ba6d.
