### ISSUE TITLE
runtime: GOGC=0 should override heap minimum

### ISSUE THREAD

**Issue by rsc** [golang/go#10681]
GOGC=0 means basically GC after every allocation. It's very useful for debugging. It is effectively disabled for small heaps due to the heapminimum (4MB). We should override the heapminimum when GOGC=0 - you only set that when you really want lots of GCs.

@RLH @aclements

**Comment by RLH** [comment]
This is going to be fixed by setting minimum heap size to GOGC/100 * 4Mbytes.
