### ISSUE TITLE
cmd/internal/gc: offer a way to show the compiler panic

### ISSUE THREAD

**Issue by minux** [golang/go#10683]
Right now cmd/internal/gc/lex.go has an unconditional `defer hidePanic()`
to hide all the panics, I think there should be a way to show the panic to
aid in debugging.

**Comment by rsc** [comment]
It doesn't hide all panics. It hides panics after the compiler has printed error messages.
If you want to disable the recover when -d panic=1, that's fine. Not blocking the release.
