### ISSUE TITLE
crypto/x509: test is sometimes very slow

### ISSUE THREAD

**Issue by rsc** [golang/go#10692]
On my OS X laptop, during go test -a -short std, crypto/x509 sometimes completes in a second or two; other times it takes 17+ seconds. There doesn't seem to be an in-between. Investigate once fewer fires are burning.

**Comment by FiloSottile** [comment]
Can't reproduce with `for i in $(seq 100); do go test -short crypto/x509; done`. Close?

**Comment by bradfitz** [comment]
@FiloSottile, on a Mac? Macs often have low ulimits. But yeah, we can close. It's been awhile.

**Comment by FiloSottile** [comment]
Yep on my Mac. `for i in $(seq 100); do go test -a -short std | grep '\tcrypto/x509\t'; done` is also 1-2s even with thermal throttling, closing.

**Comment by FiloSottile** [comment]
OTOH that command triggered a kernel panic after a few iterations. Something about `com.apple.filesystems.apfs`, `com.apple.kec.corecrypto` and `link`. Exciting.

I'm reproducing it another day.
