### ISSUE TITLE
Accessing nil Func's Entry results in crash 

### ISSUE THREAD

**Issue by jcajka** [golang/go#10696]
This small program:

```go
package main

import "runtime"
import "fmt"
import "os"
import "strconv"

func main() {
    if len(os.Args) > 0 {
        i, _ := strconv.ParseInt( os.Args[0], 0, 64)
        pc := uintptr(i)
        fmt.Printf("%x",pc)
        fn := runtime.FuncForPC(pc)
        fmt.Print(fn,"\n\nName: ")
        fmt.Print(fn.Name(),"\n\nEntry: ")
        fmt.Print(fn.Entry(),"\n\n")
    }
}
```

crashes with:

```
[root@localhost ~]# ./test2 
0<nil>

Name: 

Entry: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4157f5]

goroutine 1 [running]:
main.main()
	/root/test2.go:16 +0x3c1

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:90
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/lib/golang/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/lib/golang/src/runtime/malloc.go:712
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
```

I would expected same behavior of Entry(crashes) and Name(returns nil), ie. if fn is nil, both should crash or return nil. Is this expected ? 

PS: docker relies on nil return in case of Name access. 
See https://bugzilla.redhat.com/show_bug.cgi?id=1212472#c4 or https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66016 

Please advise.

Thanks,
Jakub

**Comment by cznic** [comment]
The name of the binary is parsed instead of its argument, but he ParseInt error, which could hint on that, is ignored. Finaly, the FuncForPC return value is used without being sanity checked.

http://play.golang.org/p/7KFba3toPU

Please ask for coding help using the mailing list, thank you.

**Comment by jcajka** [comment]
Please, note that is intentional, as is one way how to bypass compile time checks and get invalid function (pointer). Also it doesn't explain different behavior(or at least this difference should be documented).

**Comment by rjeczalik** [comment]
@jcajka Your test case can be reduced to:

```go
package main

import "runtime"

func main() {
	runtime.FuncForPC(uintptr(0)).Entry()
}
```

And yes, as @cznic said, it's invalid.

**Comment by jcajka** [comment]
Grrr..., I have pasted wrong reproducer... Sorry... But still nil.Name() should probably rise panic too, and not just fail gracefully.

**Comment by bradfitz** [comment]
> But still nil.Name() should probably rise panic too,
> and not just fail gracefully.

Regardless of whether that's a good idea, that would be a change in behavior from previous Go releases, which the Go 1 compatibility contract would frown upon.

I'm closing this bug. If this is a change from previous Go releases or buggy, we can reopen.

**Comment by bradfitz** [comment]
Or, wait, what is your bug report? Is it that gc and gccgo differ in behavior here? If so, that might be a legitimate concern. Please state so clearly, though... it's too easy to miss that buried in a bug reported linked from here.

/cc @ianlancetaylor for gccgo/libgo.

**Comment by ianlancetaylor** [comment]
I have fixed gccgo so that runtime.Func.Name does not crash when Func is nil (see http://gcc.gnu.org/PR66016).

We clearly aren't going to change the behaviour going forward.  For one thing, as you point out, changing it would break Docker, and we certainly aren't going to do that in the pursuit of an abstract consistency.

I think the only open question is whether we should change runtime.Func.Entry to not crash when Func is nil, for consistency with Name.  I think the relevant difference is that for Name there is an obvious value to return for a nil Func: the empty string.  For Entry we could invent an error value, such as 0, but there is no similarly obvious error value.  At least, I don't find it obvious.

So I think in the absence of some reason to change, things are OK as they are.
