### ISSUE TITLE
Non-root Unix build fails after commit 055ecb7be580 in TestSCMCredentials

### ISSUE THREAD

**Issue by siebenmann** [golang/go#10703]
If I build current git master at or after commit 055ecb7be5805e07498488c59c6f01644fdacccc, it fails:

    --- FAIL: TestSCMCredentials (0.00s)
            creds_test.go:60: WriteMsgUnix failed with write unix @-><nil>: sendmsg: operation not permitted, want EPERM

This is src/syscall/creds_test.go, which contains code that assumes a net.OpError.Err field is directly a syscall.EPERM:

    if err.(*net.OpError).Err != syscall.EPERM { .... }

This assumption is false after the commit. Now the syscall.EPERM is now wrapped up inside a SyscallError that's the result of calling os.NewSyscallError() in src/net/fd_unix.go's writeMsg().

The entire test here is conditional on os.Getuid() not being 0. I assume that the buildbots are running in some environment where os.Getuid() returns 0, which means this entire subtest in TestSCMCredentials() is being skipped. That may be a bug in itself (and there are a number of other tests that are conditional on the UID not being seen as 0).

**Comment by ALTree** [comment]
There's a pending CL for this https://go-review.googlesource.com/#/c/9714/
