### ISSUE TITLE
cmd/gc: improve "type *X has no field or method M" message when X is an interface type 

### ISSUE THREAD

**Issue by Sajmani** [golang/go#10700]
When using a new, unfamiliar package, programmers occasionally make the error of using a pointer to an interface type instead of the interface type directly:
  http://play.golang.org/p/JulyJVaOrG
The compiler reports the error:
  /tmp/sandbox956919287/main.go:8: x.Do undefined (type *ImportedFromSomewhere has no field or method Do)
While this is correct, it would be helpful to point out that *ImportedFromSomewhere is a pointer to an interface type, and better yet, that ImportedFromSomewhere has the desired method Do.

**Comment by rsc** [comment]
Just for the record (because the CL will be implemented this way), I disagree with the 'better yet'. If you're using a pointer to interface, reporting that fact is enough. That's a day 1 Go mistake, better to focus on that issue than cloud things by saying "and you were _this_ close!"
