### ISSUE TITLE
cmd/go: "go clean -i all" removes go binary

### ISSUE THREAD

**Issue by divan** [golang/go#10710]
```go clean -i all``` command deletes go binary itself, and this behavior is undocumented.

    $ go version
    go version go1.4.2 darwin/amd64

    $ go clean -i -n all | grep -A 2 "cmd/go$"
    cd /usr/local/go/src/cmd/go
    rm -f go go.exe go.test go.test.exe bootstrap bootstrap.exe build build.exe clean clean.exe context context.exe discovery discovery.exe doc doc.exe env env.exe fix fix.exe fmt fmt.exe generate generate.exe generate_test generate_test.exe get get.exe go11 go11.exe go_windows_test go_windows_test.exe help help.exe http http.exe list list.exe main main.exe match_test match_test.exe pkg pkg.exe pkg_test pkg_test.exe run run.exe signal signal.exe signal_notunix signal_notunix.exe signal_unix signal_unix.exe tag_test tag_test.exe test test.exe testflag testflag.exe testgo testgo.exe tool tool.exe vcs vcs.exe vcs_test vcs_test.exe version version.exe vet vet.exe zdefaultcc zdefaultcc.exe

**Comment by minux** [comment]
go clean -i will remove the installed binary, this is documented.

cmd/go is included in "all" packages, so go clean -i all will remove the
installed go command.

This is working as intended.

**Comment by AlekSi** [comment]
@davecheney disagrees: https://twitter.com/eth0_blog/status/595718960982728704

**Comment by minux** [comment]
I think this is consistent with the docs, introducing a special case
for the go command is going to break the consistency.

we obviously can't remove cmd/go from "all", and then the question
is why shouldn't go clean -i remove the installed binary of a package
or command included in the selected packages?

should go clean -i cmd/go be a no-op too? I doubt so.

**Comment by davecheney** [comment]
The OP was unlucky enough to have installed go from source. If they were
using the binary distro they would have seen permission errors and may have
reached for the sudo hammer, making things even worse.

I don't think go clean should touch the std lib under any circumstance.

**Comment by minux** [comment]
are you suggesting that go clean -i std cmd should be a no-op?
why are things in $GOROOT that different?

If we want to fix this, let's fix it in the correct way. Introduce
negative selectors so that one can use go clean -i all -std -cmd
to clean only GOPATHs.

**Comment by davecheney** [comment]
On 6 May 2015 9:49 am, "Minux Ma" <notifications@github.com> wrote:
>
> are you suggesting that go clean -i std cmd should be a no-op?
> why are things in $GOROOT that different?

Because in the general case, users of the language, not you and me that
compile trunk from source, they don't have permission to change $GOROOT.

>
> If we want to fix this, let's fix it in the correct way. Introduce
> negative selectors so that one can use go clean -i all -std -cmd
> to clean only GOPATHs.

I disagree, this is an issue involving data loss; adding more flags and
expecting people to use them to not loose data is not an acceptable
solution to me.

**Comment by minux** [comment]
go clean -i is a command that inherently involves data losses.

adding the GOROOT restriction it's like adding a safety measure to 'rm -rf
/*'.

**Comment by AlekSi** [comment]
> Because in the general case, users of the language, not you and me that
compile trunk from source, they don't have permission to change $GOROOT.

Well, OP used homebrew on OS X, it's quite typical.

**Comment by davecheney** [comment]
Off topic, I have no idea why go clean is even necessary.

**Comment by minux** [comment]
yeah, I have never used go clean -i myself.

I do use go clean in a directory though.

**Comment by ianlancetaylor** [comment]
Just as "go build -a" does not rebuild the standard library in a release, I don't think that "go clean -i" should remove cmd/go in a release.  There's just no way that anybody would expect that to happen.

I'm also OK with dropping the -i option to go clean, I don't know who would use that.

**Comment by AlekSi** [comment]
> I'm also OK with dropping the -i option to go clean, I don't know who would use that.

In this case (I'm original victim) I wanted to remove installed binaries from $GOPATH/bin.

**Comment by davecheney** [comment]
Why not just do rm $GOPATH/bin/* ? To me it seems wrong for the go tool to
wrap an operation that can potentially loose data, I prefer that these
things are explicit.

**Comment by minux** [comment]
I'm OK with dropping the -i option.

I don't like more special case for GOROOT (I still believe the go install -a
special case is a mistake (my alternative solution would be to ignore the
permission error if the new file is the same as the old one already there)).

I agree with Dave that removing $GOPATH/bin/* is better to be explicit
and go clean -i does much more than that.

**Comment by AlekSi** [comment]
Two reasons:
1) Same command will work on both Windows and Unix.
2) I wanted to remove only binaries corresponding to Go packages in $GOPATH – there is other stuff in `bin`.

**Comment by minux** [comment]
go to the GOPATH and run go clean -i ./... there.

In retrospect, both go install -a all and go clean -i all problems are
because there isn't a selector for all of GOPATHs. If we don't like the
negative selector idea, we can introduce a selector for all packages
under GOPATHs.

**Comment by AlekSi** [comment]
> go to the GOPATH and run go clean -i ./... there.

The only downside is that command should be run at $GOPATH, not some $GOPATH subdirectory.

**Comment by minux** [comment]
I sent a CL (9780) for the "gopath" selector. Let's see what happens.

If it's accepted, then the solution for this problem is quite nice:
go clean -i gopath

And reinstalling GOPATH packages after upgrading Go is also simpler:
go install -a gopath

The only downside is that if there is a gopath package, then the meaning
of go install gopath is changed silently.

**Comment by rsc** [comment]
I tend to agree with Minux. The command says delete everything. It did. CL 9780 may end up with something useful, but it's not going to change what go clean -i all does.
