### ISSUE TITLE
cmd/go: unable to test a package if it's import path is main

### ISSUE THREAD

**Issue by martinellison** [golang/go#10738]
It seems that ~~calling a package~~ *using a directory* `main` has special (bad) effects. Please document this in the documentation ~~for the package statement~~.

You also might want to issue a warning if anyone tries to ~~define a package~~ *use a folder* called `main`.

*Corrected to reflect minux' comment below.*

**Comment by minux** [comment]
What bad effects are you talking about?

the main package is where the Go program starts execution, it's documented
in the spec:
http://golang.org/ref/spec#Program_execution

**Comment by martinellison** [comment]
Sorry, I've checked further. The problem is actually having a directory called main. I had naively assumed that with one package per directory, one should call the directory the same name as the package it contains. Apparently, this does not work for package main. (So what minux says is correct, but there is still a problem; I have updated the original post).

**Comment by adg** [comment]
What are the "bad effects"?

**Comment by martinellison** [comment]
1. When I try go test main I get: /tmp/go-build550118144/main/_test/_testmain.go:9: cannot import "main" and FAIL    main [build failed]
2. When I try godoc main (1) godoc treats main as a command not a package and (2) godoc does not doument my funcs and vars (even if they are Public).

See https://groups.google.com/forum/#!topic/golang-nuts/ubYw0OQXLvA

**Comment by minux** [comment]
The problem is that the test driver (_testmain.go) needs to import the
package
and if the import path is "main", gc will refuse to import it.

The reason is simple, the packages in Go program must have unique import
paths, but as the main package must have the import path "main", you can't
import another "main" package.

This is working as intended.

**Comment by martinellison** [comment]
ok, but this should be documented so other newbies do not make the same
mistake.

Regards,
Martin
