### ISSUE TITLE
cmd/doc: omit symbol list for docs about command

### ISSUE THREAD

**Issue by rsc** [golang/go#10733]
You can't import cover the first two lines of this output and the block at the end should be omitted. Perhaps if -u were given it would make sense to show them? 

	g% go doc cover
	package main // import "cmd/cover"
	
	Cover is a program for analyzing the coverage profiles generated by 'go test
	-coverprofile=cover.out'.
	
	Cover is also used by 'go test -cover' to rewrite the source code with
	annotations to track which parts of each function are executed. It operates on
	one Go source file at a time, computing approximate basic block information by
	studying the source. It is thus more portable than binary-rewriting coverage
	tools, but also a little less capable. For instance, it does not probe inside &&
	and || expressions, and can be mildly confused by single statements with
	multiple function literals.
	
	For usage information, please see:
	
		go help testflag
		go tool cover -help
	
	func ParseProfiles(fileName string) ([]*Profile, error)
	type Block struct { ... }
	type Boundary struct { ... }
	type File struct { ... }
	type FuncExtent struct { ... }
	type FuncVisitor struct { ... }
	type Profile struct { ... }
	type ProfileBlock struct { ... }
	g%

**Comment by robpike** [comment]
You can't import it (well, a test could) but it can be helpful to know where the source comes from. That's a question I want the answer to quite often.

I'd rather leave it.

**Comment by robpike** [comment]
Will consider the suggestion for -u and the exported symbols, although it makes the specification of what the command does more complicated.
