### ISSUE TITLE
text/scanner: Can't properly detect EOF from os.Stdin

### ISSUE THREAD

**Issue by jingweno** [golang/go#10735]
* What version of Go are you using (go version)?

```
$ go version
go version go1.4.2 darwin/amd64
```

* What operating system and processor architecture are you using?

OSX 64bit.

* What did you do?

I tried to use `scanner.Scanner` from `text/scanner` from `os.Stdin` and I pressed ctrl+D to send a EOF to the program. The program couldn't properly detect EOF. Reference [code](https://play.golang.org/p/IayBVrVhiT).

* What did you expect to see?

The program should stop immediately I sent the EOF (ctrl+D).

* What did you see instead?

The program hung there. Pressing ctrl+D multiple times did stop the program.

**Comment by robpike** [comment]
A second ^D works. This is always a notorious problem due to lookahead, but it would be good to fix.

**Comment by jingweno** [comment]
:+1: to the fixes
