### ISSUE TITLE
cmd/dist: build fails if gcc is not installed

### ISSUE THREAD

**Issue by davecheney** [golang/go#10731]
Building Go on a fresh linux/arm64 machine fails because gcc is not installed.

This might be confusing to new developers because we've made a lot of noise that we're moving away from C to Go in the 1.5 release.

The gcc build time dependency comes from cgo, and all linux/* platforms default to cgo enabled by default.

Should cmd/dist check to see if gcc (or $CC) is valid, and if not, disable cgo ?

/cc @adg @minux

**Comment by adg** [comment]
Most people want cgo support to be available. That means you need a C
compiler, and shouldn't be a surprise to anyone.

I don't see the problem with saying "If you don't have or want a C compiler
then disable cgo."

**Comment by davecheney** [comment]
Fair point. Currently the build pukes in the middle of the second stage compile. Do you have strong feelings on adding a check to cmd/dist that if cgo is enabled and gcc/$CC is not found, to abort earlier ?

**Comment by adg** [comment]
It sounds like a nice user friendly thing to do.

**Comment by minux** [comment]
Yeah, I think we can add that check to fail earlier and given a hint
to set CGO_ENABLED=0 if it's intended.

Note we need to check two different cases:
1. native compilation, check $CC (if non-empty) and gcc/clang in $PATH.
2. cross compilation, check $CC_FOR_TARGET (if non-empty) in $PATH.

**Comment by bradfitz** [comment]
This actually bit me today while setting up new builders. I agree we should fail earlier, and be helpful when failing would be nice.
