### ISSUE TITLE
build: fix clean.bash, clean.bat, clean.rc

### ISSUE THREAD

**Issue by minux** [golang/go#10734]
The various src/clean.{bash,bat,rc} scripts are out of date now, and apparently
nobody uses them.

(There are at least two problems in those scripts:
1. on windows, it should use 'dist env -w -p' instead of 'dist env -wp'.
2. `go clean -i std` is not sufficient anymore, it also needs `go clean -i cmd`,
but because `go clean -i cmd` will also remove the dist tool, it must be
executed last)

`git clean -d -X` does almost exactly what the clean script does, and it's pretty
safe (it only removes ignored files and directories). perhaps we can just delete
those outdated clean scripts (or change them to simply:
```
cd $(go env GOROOT)
go tool dist clean
git clean -d -X
```
)

**Comment by bradfitz** [comment]
SGTM at least

**Comment by alexbrainman** [comment]
I have never liked any batch files anyways.

Alex

**Comment by minux** [comment]
FWIW, I have never used those clean scripts.

To clean a $GOROOT, git clean is always better,
unless it's a release source tarball, but in that case,
just delete it and re-extract the tarball is safer.

I suspect the reason we have such scripts is because
hg doesn't provide a cleanup command by default
(there is a purge standard extension though) and
we used to put intermediate build files into package
source directory.

**Comment by minux** [comment]
Russ rejected this idea

"
Please leave these here. They are API for developers. If you remove them
then you break all the scripts people have that run clean.bash.
(This is not about the Go 1 compatibility guarantees, it just about not
breaking people unnecessarily.)
"

I guess I have to fix those scripts then.

**Comment by rsc** [comment]
It's fine to make these thin wrappers around dist (I thought they already were). I'm less sure about making them thin wrappers around git. The other scripts work without git being present, at least provided a VERSION file exists. We should probably keep that property.

**Comment by minux** [comment]
@rsc, please see https://golang.org/cl/9823 for the fixed clean scripts.
