### ISSUE TITLE
x/mobile/cmd/gomobile: Provide support for other instruction sets used by Android (such as x86)

### ISSUE THREAD

**Issue by timcooijmans** [golang/go#10743]
Android doesn't only run on arm-based systems but also some other architectures are commonly used, such as x86 (mostly Intel Atom, but also the simulators) arm64 (also known as aarch64) and MIPS. 

It would be great if at least x86 was supported.

**Comment by timcooijmans** [comment]
I'm having a try myself. I will post a code review in a few days.

**Comment by hyangah** [comment]
This involves more than just changing in the gomobile cmd tool. The go tool is not officially supporting android on other architectures yet - see http://build.golang.org to see the supported os+arch combination.  

Much progress had been made in shared library buildmodes support for 1.5 so I guess it will not be very hard but it will still need touching various places on the main go tree. FYI the main go tree is frozen for 1.5, and for official release, we need a builder.

**Comment by timcooijmans** [comment]
I stopped working on this because I couldn't get around some issues in the main go tree. Maybe I will have another try in the future.

**Comment by crawshaw** [comment]
Depends on #9327, which @hyangah is going to look at for Go 1.6. As you say @timcooijmans, there's a bit of subtlety there. Once #9327 is done, modifying the gomobile tool will be really easy.

Assigning to myself so I don't forget it (somehow I missed this issue when it came in), but feel free to take it again.

**Comment by timcooijmans** [comment]
Just a little update. I created support for x86 in the gomobile tool (as far as gomobile bind go's, gomobile build does only arm). https://go-review.googlesource.com/13750

As mentioned in #9327 some elements are still missing in Go to support actual working libraries.

**Comment by hyangah** [comment]
I will change gomobile to build an app for android/x86 this week.
One question is how to configure to create or not to create the fat binary.
We are thinking to extend -target flag to accept a comma-separated list of 
android/{architecture} names.

-target=android/arm or -target=android/x86 or -target=android/x86_64

and

-target=android packages for all the architectures available

WDYT?

@crawshaw

**Comment by crawshaw** [comment]
Sounds good to me.

**Comment by fernand** [comment]
Are there any blockers for supporting android/arm64?
