### ISSUE TITLE
x/review/git-codereview: mail should reject empty commits

### ISSUE THREAD

**Issue by minux** [golang/go#10753]
`git change` passes `--allow-empty` to `git commit` so that it can create a
new branch with an empty commit to work with.

However, it's also possible that the user forgets to `git add` the file, and
mail the empty commit out to Gerrit. `git mail` should check for that case
and suggest `git add` or `git chagne -a`.

/cc @adg

**Comment by robpike** [comment]
I agree. The overlap of git branch and git change is error-prone.
