### ISSUE TITLE
`go fmt` should invoke `gofmt` from the current sdk installation

### ISSUE THREAD

**Issue by zolotov** [golang/go#10755]
At https://github.com/golang/go/blob/master/src/cmd/go/fmt.go#L36 `gofmt` is invoked from PATH. So if I have several installations of Go then no matter which `go fmt` I invoke the `gofmt` from PATH will be used and it's not correct IMHO. 

Unfortunately the fix like

```
 run(stringList(filepath.Join(runtime.GOROOT(), "bin/gofmt"), "-l", "-w", relPaths(pkg.allgofiles)))
```

won't work on apt-get (has no `bin` directory) and yum (`gofmt` is placed under `bin/linux_64`) installations.

**Comment by minux** [comment]
The fix should work.
For those distributions that don't have the concept of a real GOROOT,
they have to patch the source code anyway, so we don't need to care.

**Comment by zolotov** [comment]
@minux thanks for reply, ok then, I'll make PR with the fix.
