### ISSUE TITLE
x/tools/cmd/vet: allow individual errors to be ignored/suppressed via code comments

### ISSUE THREAD

**Issue by asadovsky** [golang/go#10752]
"go vet" sometimes reports false positives. It would be nice if code could be annotated with something like "// vet:ignore" to make it so "go vet" does not report errors associated with that line of code, perhaps for a particular specified error type.

(I searched to see if this option exists, but couldn't find anything.)

**Comment by adg** [comment]
I wouldn't be very pleased to see Go programs littered with "// vet:ignore"
comments. In general we try to avoid magic comments as much as we can.

**Comment by asadovsky** [comment]
Well, it would be up to the code owner to decide whether they prefer to see go vet false positives or "// vet:ignore" comments. Right now, we don't let them choose.

**Comment by adg** [comment]
That's true, but the decisions we make at this fundamental level effect the
Go ecosystem as a whole. Code is usually read by many more people than just
its authors.

cc @rob_pike

**Comment by robpike** [comment]
Vet is advisory only. As adg said, we don't want to clutter the code with comments to adjust the output of an optional tool. We had that with lint and C, and we saw idiocies like (void)printf("hi"). No.
