### ISSUE TITLE
x/mobile/cmd/gomobile: init fails

### ISSUE THREAD

**Issue by rakyll** [golang/go#10760]
```
go version
go version devel +3a3773c Fri May 8 17:01:24 2015 +0000 darwin/amd64

gomobile init -v
gomobile: cannot get cmd/dist version: exit status 2 ()
```

**Comment by rakyll** [comment]
gomobile is built from https://github.com/golang/mobile/commit/f3d33d5ec91fcda3d56fb8a2d4ccf3c2f0a8248c.

**Comment by hyangah** [comment]
what does it say if run gomobile init -u?

2015-05-08 14:16 GMT-04:00 Burcu Dogan <notifications@github.com>:

> gomobile is built from golang/mobile@f3d33d5
> <https://github.com/golang/mobile/commit/f3d33d5ec91fcda3d56fb8a2d4ccf3c2f0a8248c>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/10760#issuecomment-100318667>.
>



-- 
__

**Comment by crawshaw** [comment]
does make.bash fix this? what does ```env | grep GO``` and ```go env``` say?

**Comment by rakyll** [comment]
```
gomobile init -u
gomobile: cannot get cmd/dist version: exit status 2 ()
```

> does make.bash fix this?

No.

```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jbd"
GORACE=""
GOROOT="/Users/jbd/go"
GOTOOLDIR="/Users/jbd/go/pkg/tool/darwin_amd64"
GOCHAR="6"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

env | grep GO
# ...
GOPATH=/Users/jbd
```

I can build dist and run `dist version` by myself if I set a GOROOT.

**Comment by crawshaw** [comment]
what was in the ... you elided?

**Comment by rakyll** [comment]
Nothing Go related, filtered out due to privacy.
