### ISSUE TITLE
path/filepath: Missing support of matching directories recursively with '**' for Glob() and Match()

### ISSUE THREAD

**Issue by cybertk** [golang/go#10766]
Like `glob` in [Ruby](http://ruby-doc.org/core-1.9.3/Dir.html#method-c-glob), it support matching directories recursively with `**`. 

```
rbfiles = File.join("**", "*.rb")
Dir.glob(rbfiles)                   #=> ["main.rb",
                                    #    "lib/song.rb",
                                    #    "lib/song/karaoke.rb"]
```

**Comment by bradfitz** [comment]
Sorry, the behavior of filepath walking is frozen.

You can find things like this outside of the standard library.
