### ISSUE TITLE
cmd/internal/ld: dwarf generation slow

### ISSUE THREAD

**Issue by mwhudson** [golang/go#10763]
I don't know if this is known or expected, but it surprised me: passing -w to 6l (to disable dwarf generation) can make it almost twice as fast (e.g. when linking the standard library into a shared library, adding -w to the command line makes the link go from ~4.5 s to ~2.2s).

**Comment by mwhudson** [comment]
(adding GOGC=off takes it down to 1.7s)

**Comment by josharian** [comment]
IIRC from a couple of weeks ago, a significant amount of the allocations in the linker occur during DWARF generation.

**Comment by bradfitz** [comment]
(Part of #10571 -- all.bash is too slow)

**Comment by mwhudson** [comment]
Staring at pprof a bit, I think the layers of IO seem to be hurting -- a stupid hack to cache the offset in the output file (d7d350081ff5156d6aac63c0092f66a562616a30) makes the link of libstd.so 25% faster! (4.41->3.31s best of 5 times).  I think it's particularly bad for external linking, but linking godoc still improves from 1.97s to 1.79s (about 9%, again best of 5). The change makes almost no difference when -w is passed to disable dwarf.

I don't know that this bug contributes especially much to the slowness of all.bash as dwarf is not produced when you run go test pkg. It does add a few seconds to the make.bash part I guess.

**Comment by bradfitz** [comment]
Your change makes pos not flush. That's probably the real win.

**Comment by mwhudson** [comment]
Ah yes, good point. CL coming up.

**Comment by thanm** [comment]
Closing out this old bug. Much has changed in linker dwarf generation since 2015.
