### ISSUE TITLE
cmd/go: run passes arguments to binary incorrectly

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10761]
```
$ cat x.go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Printf("%q\n", os.Args)
}

$ go run x.go a b "c d"
["/var/folders/n7/gw0f1vrj0m5ffgwgyzbm2fwm001w6m/T/go-build004220194/command-line-arguments/_obj/exe/x" "a" "b" "c" "d"]
```

Note that `c` and `d` are split into two arguments.

Using `go build` + `./x a b "c d"` works as expected, so the problem is with `go run` somewhere.

(noticed with @robpike and @randall77)

**Comment by odeke-em** [comment]
I don't know if this helps, but at least it was working right by ac6158828870abcbf7d9ef86c89569a2a7d7020c committed on Fri Dec 19 14:28:44 2014 -0500
![screen shot 2015-05-08 at 6 48 13 pm](https://cloud.githubusercontent.com/assets/4898263/7547845/d040a36c-f5b2-11e4-8ebc-677698b6cef9.png)

**Comment by minux** [comment]
Interesting. I can't reproduce this.

$ go run issue10761.go a b "c d"
["/var/folders/p6/9tyrs0yx74l6t96y2rsq07300000gn/T/go-build212843169/command-line-arguments/_obj/exe/issue10761"
"a" "b" "c d"]
$ go version
go version devel +82359d1 Sat May 9 02:58:50 2015 +0000 darwin/amd64

**Comment by bradfitz** [comment]
It's all my fault yet again.

My first mistake was in run.bash, fixed by https://go-review.googlesource.com/#/c/9892/.
My second mistake (the same mistake) was /home/bradfitz/bin/go (first in my $PATH for "go") which was:

```bash
$ cat ~/bin/go
#!/bin/sh
exec $GOROOT/bin/go $@
```

... which I forgot I even had.

I never knew about this bash/shell `"$@"` "feature" until today.

Sorry for the noise.
