### ISSUE TITLE
tour: Example in "Exported names" section does not compile

### ISSUE THREAD

**Issue by isameer** [golang/go#10774]
Context: /basics/3

Example in "Exported names" section does not compile. Error is:

```
# command-line-arguments
/tmp/sandbox260995202/main.go:9: cannot refer to unexported name math.pi
/tmp/sandbox260995202/main.go:9: undefined: math.pi
```

**Comment by minux** [comment]
It's working as intended, the text on the right side wants
you to change math.pi to math.Pi and try again to see
that exported names are capitalized.

"Run the code. Then rename math.pi to math.Pi and try it again."
