### ISSUE TITLE
cmd/doc: BUGS section missing

### ISSUE THREAD

**Issue by rsc** [golang/go#10781]
If I run 'doc atomic' it doesn't tell me about the caveats listed at the end of 'godoc sync/atomic' in the BUGS section.
Probably the BUGS section should appear at the end of the normal package doc in the new cmd/doc?

**Comment by robpike** [comment]
Ah, good idea. I left it out because godoc was too insistent on showing that, but now we have a breakdown that provides an obvious location for it.
