### ISSUE TITLE
runtime: program with -buildmode=c-archive hangs when c side crashes. (darwin/amd64)

### ISSUE THREAD

**Issue by hyangah** [golang/go#10783]
Expectation: the program would crash.

Observation: When c-side crashes, the program hangs indefinitely.

Reproduction:

Ran misc/cgo/testcarchive/test.bash with the following modified main.c
<pre>
diff --git a/misc/cgo/testcarchive/main.c b/misc/cgo/testcarchive/main.c
index cc3170d..2dfdbae 100644
--- a/misc/cgo/testcarchive/main.c
+++ b/misc/cgo/testcarchive/main.c
@@ -8,6 +8,11 @@
 #include "p.h"
 #include "libgo.h"
 
+void causeCrash() {
+       int *i = NULL;
+       printf("%d", *i + 10);
+}
+
 int main(void) {
        int32_t res;
 
@@ -27,6 +32,8 @@ int main(void) {
                return 2;
        }
 
+       causeCrash();
+
        CheckArgs();
 
        fprintf(stderr, "PASS\n");
</pre>

<pre>
$ lldb ./testp arg1 arg2
(lldb) target create "./testp"
Current executable set to './testp' (x86_64).
(lldb) settings set -- target.run-args  "arg1" "arg2"
(lldb) run
Process 29934 launched: './testp' (x86_64)
Process 29934 stopped
* thread #1: tid = 0x29bb8e, 0x000000010000111b testp`causeCrash + 27, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010000111b testp`causeCrash + 27
testp`causeCrash + 27:
-> 0x10000111b:  movl   (%rax), %ecx
   0x10000111d:  addl   $0xa, %ecx
   0x100001123:  movl   %ecx, %esi
   0x100001125:  movb   $0x0, %al
(lldb)  
</pre>

**Comment by ianlancetaylor** [comment]
CC @mwhudson

**Comment by mwhudson** [comment]
I'm happy to look at this but I think it's more to do with the runtime initialization stuff @spetrovic77 did?

**Comment by rsc** [comment]
Dup of #10139 I believe.
