### ISSUE TITLE
html/template: Calling Template.Execute with no top-level template panics

### ISSUE THREAD

**Issue by anacrolix** [golang/go#10786]
```
t := template.Must(template.New("").Funcs(irrelevantFuncs).ParseFiles("base.html", "notbase.html"))
t.Execute(w, data)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x418b6b4]

goroutine 1 [running]:
html/template.(*Template).escape(0xc208091f20, 0x0, 0x0)
	/Users/anacrolix/src/go/src/html/template/template.go:59 +0xe4
html/template.(*Template).Execute(0xc208091f20, 0x49a1ec8, 0xc208048010, 0x0, 0x0, 0x0, 0x0)
	/Users/anacrolix/src/go/src/html/template/template.go:75 +0x3d
```

Compare calling `t.ExecuteTemplate(w, "", data)` which gives error `html/template: "" is an incomplete template`. There should be a suitable error for `Template.Execute`, or the docs improved.

**Comment by robpike** [comment]
Please provide a complete example, avoiding files if possible.

**Comment by anacrolix** [comment]
Thanks, I've boiled it down to this: http://play.golang.org/p/EQyvlM7LYX

It doesn't occur with `text/template`, but does with `html/template`.

**Comment by syst3mw0rm** [comment]
@anacrolix what go version are you using? I'm not facing any issue on tip.

**Comment by anacrolix** [comment]
I was running go1.4. It does not happen in master. go version devel +7eec656 Wed May 20 07:54:37 2015 +0000 darwin/amd64

I have a feeling I already reported this issue once before.

**Comment by robpike** [comment]
Fixed at tip.

**Comment by avdept** [comment]
@robpike Where can i see changes?
