### ISSUE TITLE
Ordering issue with a golang heap.Interface PriorityQueue. The heap.Fix() doesn't fix the ordering as it should

### ISSUE THREAD

**Issue by achedeuzot** [golang/go#10782]
Hello,

I'm using the example provided on the `container/heap` documentation page to have a `PriorityQueue` but it doesn't work as expected. 

I have posted a detailed case on stackoverflow (link below). Is there something I'm missing or is there really a problem with the way the priority queue works ?

http://stackoverflow.com/questions/30171451/ordering-issue-with-a-golang-heap-interface-priorityqueue-the-heap-fix-doesn

Thanks !

**Comment by bradfitz** [comment]
Let's move this to the golang-nuts mailing list. Unlike many Github projects, we only use our bug tracker for bugs, and not discussion. (primarily because we started with mailing lists, so that's still our primary conversation forum)

If there's an actual bug identified, then we move it here.

**Comment by achedeuzot** [comment]
Ok, sorry for the wrong place for this.
