### ISSUE TITLE
sort: StringSlice broken?

### ISSUE THREAD

**Issue by coss** [golang/go#10792]
Maybe I'm missing something, but [StringSlice](https://github.com/golang/go/blob/master/src/sort/sort.go#L256-L261) seems broken. The documentation of [`sort.Strings`](https://golang.org/pkg/sort/#Strings) says
```
Strings sorts a slice of strings in increasing order.
```
so I would exptect that it would sort by length instead of comparing [lexically byte-wise](https://golang.org/ref/spec#Comparison_operators).

Example:
```
a := []string{"A", "Ab", "Abc", "Abcd", "Xyz", "Yz", "Z"}
b := []string{"", "Hello", "foo", "bar", "foo", "f00", "%*&^*&^&", "***"}
```

Expect:
```
a = ["A", "Z", "Ab", "Yz", "Abc", "Xyz", "Abcd"]
b = ["", "***", "bar", "foo", "foo", "f00", "Hello", "%*&^*&^&"]
```

Got:
```
a = ["A", "Ab", "Abc", "Abcd", "Xyz", "Yz", "Z"]
b = ["", "%*&^*&^&", "***", "Hello", "bar", "f00", "foo", "foo"]
```

Note that the test case just tests that the input is sorted instead of comparing it against a expected fixture.

**Comment by randall77** [comment]
Working as intended.  Increasing means lexicographically increasing here.  We might want to update the docs.

**Comment by randall77** [comment]
Actually, the docs look pretty clear.  The ordering is just < on strings.
