### ISSUE TITLE
strange behavior after setting GOMAXPROC

### ISSUE THREAD

**Issue by defia** [golang/go#10798]
hi, here's my test program:
http://play.golang.org/p/r1Wz8mdWKO

actually I was testing performance between sync.Mutex and channel.
but I acciddently found that if I set GOMAXPROCS to 2(or more), the program has totally differently behavior on different machines:

if I set GOMAXPROCS to 2 instead of 1:
on my pc with win7x64 e3-2130v3 16gddr3: uselock() runs 5 times slower while channel() basically no change.

on my friends laptop with win7x86 t7300 2gddr2ram: both functions run basically no change on speed.

on a linux x64 vps with 2x e5-2650: channel() runs about 100% slower, uselock() runs 3 times slower.

on a bananapi running linux, both functions runs about 25% faster.

all binaries are build by go 1.4.2 on my windows pc.

so why am i getting such behavior?

**Comment by bradfitz** [comment]
See https://golang.org/doc/faq#Why_GOMAXPROCS

There's work ongoing to make GOMAXPROCS>1 the default, but it probably won't happen until at least Go 1.6. For now you have to choose between 1 and >1 depending on your workload. We hope to make that decision unnecessary.

**Comment by bradfitz** [comment]
e.g. https://go.googlesource.com/go/+/c4fe503119ee517e202e81913f08b2e9940e1a72

But let's move this discussion to the golang-nuts@ mailing list.

**Comment by defia** [comment]
thanks for the reply. I knew the article in faq.
I am just curious why I get totally different result , even on similar systems .With the same change of GOMACPROCS, new powerful cpu actually slows down more, that's quite abnormal.
I will move to golang nuts later.
