### ISSUE TITLE
x/sys/plan9, x/sys/windows: Environment functions should just refer to syscall functions

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#10803]
In x/sys/unix/env_unix.go, the functions that deal with the environment just call the functions in the standard syscall package.  The same should be done for x/sys/plan9/env_plan9.go and x/sys/windows/env_windows.go.  I would just do it but I don't have the systems to test on, and as far as I know the trybots will only test the main repository, not x/sys.

**Comment by 0intro** [comment]
I'll do it once I'll be back home next week.
