### ISSUE TITLE
build: android builder failing due to lack of fs cleaning?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10806]
The android builder is failing with:

```
go_android_exec: adb shell mkdir -p /data/local/tmp/build.test-12364
go_android_exec: adb push /tmp/go-build585057401/go/build/_test/build.test /data/local/tmp/build.test-12364/build.test-12364-tmp
204 KB/s (2823632 bytes in 13.492s)
go_android_exec: adb shell cp '/data/local/tmp/build.test-12364/build.test-12364-tmp' '/data/local/tmp/build.test-12364/build.test-12364'
go_android_exec: adb shell rm '/data/local/tmp/build.test-12364/build.test-12364-tmp'
go_android_exec: adb shell export TMPDIR="/data/local/tmp/build.test-12364"; export GOROOT="/data/local/tmp/goroot"; export GOPATH="/data/local/tmp/gopath"; cd "/data/local/tmp/goroot/src/go/build"; '/data/local/tmp/build.test-12364/build.test-12364' -test.short=true -test.timeout=4m0s; echo -n exitcode=$?
--- FAIL: TestDependencies (0.56s)
	deps_test.go:482: android/arm/cgo=true unexpected dependency: go/constants imports [fmt go/token math/big strconv]
	deps_test.go:482: android/arm/cgo=true unexpected dependency: internal/mime imports [bytes encoding/base64 errors fmt io io/ioutil strconv strings unicode]
	deps_test.go:482: android/arm/cgo=true unexpected dependency: internal/syscall imports [runtime sync/atomic syscall unsafe]
	deps_test.go:489: skipping other systems
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/build.test-12364
```

But internal/mime doesn't exist anymore.

Does the Android builder not delete some files from its disk between runs?

/cc @hyangah @crawshaw

**Comment by hyangah** [comment]
Currently androidtest.bash uses "adb sync" to mirror the go source tree to the device.
adb sync saves some time but does not handle deleted files well. 

@bradfitz proposed
"after adb sync, build/push a cleaner binary & a manifest list of all expected files to the device and run the cleaner binary (using the manifest) delete all the unwanted things"

**Comment by minux** [comment]
What if we just push a zipped GOROOT (sans the pkg and bin directories) to
the
device, and unzip it there? It shouldn't take too much time as this setup
is only
done once per build.

**Comment by bradfitz** [comment]
The problem is I/O speed on the device.  The goal is to minimize writes "adb sync" first does an ls of the files on the device to figure out what it needs to write. Pushing a large zip (itself a large write) & doing all those usually-unnecessary writes would be slower.

**Comment by minux** [comment]
Does the Android builder have enough RAM?

I suggest to use a tmpfs to hold the build. 2GB RAM should be enough.
(Android builder can be rooted, so it should be easy to get a tmpfs mounted)

**Comment by rakyll** [comment]
Did you see this adb sync variant on https://github.com/google/adb-sync? It promises that deletion is working.

**Comment by minux** [comment]
Could someone with adb access to the android builder
remove $GOROOT/src/internal/mime and $GOROOT/src/go/constants
directories?

We should bring the android/arm builder back on track first and then
think about ways to fix the "adb sync" problem.

/cc @crawshaw

**Comment by crawshaw** [comment]
I deleted the goroot on the android device.

**Comment by minux** [comment]
We still need to adjust the build timeout,
1h is not enough to redo the adb sync.

**Comment by crawshaw** [comment]
The sync only takes about 5 minutes from scratch, but it turns out the script as written expects the /data/local/tmp/goroot directory to exist. I created it and will send a CL in a bit.
