### ISSUE TITLE
x/sys/unix: add GetRandom for linux

### ISSUE THREAD

**Issue by robpike** [golang/go#10822]

**Comment by syst3mw0rm** [comment]
https://go-review.googlesource.com/#/c/3014

looks like internal/syscall that doesn't apply.

**Comment by ianlancetaylor** [comment]
Let's rephrase: we should add GetRandom to x/sys/unix.

**Comment by josephlr** [comment]
Fixed by https://github.com/golang/sys/commit/76cc09b634294339fa19ec41b5f2a0b3932cea8b

**Comment by ALTree** [comment]
Closing, then.
