### ISSUE TITLE
x/sys/unix: add openbsd/arm support

### ISSUE THREAD

**Issue by robpike** [golang/go#10826]

**Comment by ianlancetaylor** [comment]
Patch to syscall package is http://golang.org/cl/4913.

**Comment by bradfitz** [comment]
What's the status of the openbsd-arm port? I notice we no longer have builders.

/cc @4a6f656c @minux @mdempsky

**Comment by mdempsky** [comment]
Sorry, no idea. I've barely used OpenBSD on ARM, much less Go's openbsd/arm port.

As for the builder, I assumed @4a6f656c was running it.
