### ISSUE TITLE
x/sys/unix: add sendfile support to solaris

### ISSUE THREAD

**Issue by robpike** [golang/go#10838]

**Comment by ianlancetaylor** [comment]
The CL for the syscall package is http://golang.org/cl/7940 .

**Comment by bradfitz** [comment]
Copying the main repo's Solaris sendfile support to the x/sys repo might be premature, since the main repo's support is broken. I disabled it in ba593d6ab861222ee03b87a6f733afac48f5a04e (see #13892)

**Comment by binarycrusader** [comment]
Issue #13892 has been resolved; this support could be added now, I will do this.
