### ISSUE TITLE
cmd/compile: constant indexing into map literals should be folded

### ISSUE THREAD

**Issue by mdempsky** [golang/go#10848]
This code from internal/syscall/unix/getrandom_linux.go:

```
package unix
import "runtime"
var randomTrap = map[string]uintptr{
        "386":     355,
        "amd64":   318,
        "arm":     384,
        "ppc64":   359,
        "ppc64le": 359,
}[runtime.GOARCH]
```

currently compiles into non-trivial chunk of code.  However, gc could instead recognize that runtime.GOARCH and all of the map literal keys are constants and that all of the value expressions are side-effect free, and fold to just the corresponding value expression.

**Comment by rsc** [comment]
Or people could not write code like that. Come on.

**Comment by mdempsky** [comment]
It looks like changing the code to:

    var randomTrap = func() uintptr {
    	switch runtime.GOARCH {
    	case "386":
    		return 355
    	case "amd64":
    		return 318
    	case "arm":
    		return 384
    	case "ppc64", "ppc64le":
    		return 359
    	default:
    		return 0
    	}
    }()

produces simpler code by taking advantage of the existing switch constant folding logic, but still needs a dynamic initializer.

Alternatively, we could just create 4 extra files and use +build rules.  (This is my preference if no one's opposed.)

**Comment by griesemer** [comment]
Is this in any way a performance issue (I can't see why)? If not, what's wrong with the switch?

**Comment by mdempsky** [comment]
Not a performance issue.  Just trying to reduce executable bloat.

Side benefit of using +build rules, it will remind porters to update this file when adding new architectures.  E.g., I just realized arm64 isn't using getrandom.

**Comment by davecheney** [comment]
@mdempsky I think this is the best approach. There are already per GOOS and GOARCH files for all permutations, and you get to make that value a constant declaration. win/win!

**Comment by rsc** [comment]
Indeed. That map thing is a terrible idiom and should not be encouraged.

**Comment by nightlyone** [comment]
One observation while teaching Go: I noticed a lot of people with python as their first and Go now as their second language write this. 

Python has no switch statement, so using map (or dict in python) seems ideomatic to them for this use case, when in fact switch is the "table to expression" ideom for those cases in Go.

Any idea where might be a good place to clear that up? Adding an example in the tour comes to mind here.

**Comment by qmuntal** [comment]
> Indeed. That map thing is a terrible idiom and should not be encouraged.

> In fact switch is the "table to expression" ideom for those cases in Go

If this is the case, apart of improving the documentation, could we add this case to `go vet` or even rewrite it using `go tool fix`? I was also using the `map` way as an idiomatic construct.

**Comment by ianlancetaylor** [comment]
I don't think this rises to the level of a vet check.

**Comment by xordspar0** [comment]
Is it in scope for a lint check?

**Comment by mdempsky** [comment]
I don't think we have any intention of optimizing indexing of map literals like this. Users should use `switch` statements instead if they want the compiler to optimize them.

(Caveat: until #34381 is implemented, switch statements are limited to binary search. But it's more likely we'll fix that than optimize this use case.)
