### ISSUE TITLE
cmd/internal/gc: ARM builders broken from optimize slice + write barrier

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10843]
d44727992771 (cmd/internal/gc: optimize slice + write barrier) broke the ARM builders.

http://build.golang.org/log/25a3d95b7f175ccf03dff342045bce622b6252e7
```
##### ../test
# go run run.go -- index0.go
exit status 2
# command-line-arguments
/tmp/988792982/tmp__.go:1056: internal compiler error: regalloc 64bit
```

/cc @minux @josharian

**Comment by minux** [comment]
A small repro:

package main

const ci64 int64 = 100014
var si []int = make([]int, 10)

func main() {
        _ = si[0:ci64]
}
