### ISSUE TITLE
time: time.Local doesn't match the timezone reported from Java on android

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#10857]
Java and Go should have matching default timezones.

log.Println("local: ", time.Local)

prints

local:  UTC

while

Log.i(TAG, "java timezone: " + java.util.TimeZone.getDefault());

prints

java timezone: libcore.util.ZoneInfo[id="Pacific/Midway",mRawOffset=-39600000,mEarliestRawOffset=-39600000,mUseDst=false,mDstSavings=3600000,transitions=4]

**Comment by hyangah** [comment]
It seems we need to look for the zoneinfo timezone db and index files in other directories on android.  e.g. /system/usr/share/zoneinfo?

**Comment by ianlancetaylor** [comment]
@hyangah you may also have a zoneinfo problem, but the problem with time.Local is most likely different.  If the TZ environment variable is not set, the time package loads /etc/localtime.  On conventional Unix systems that is a copy of the zoneinfo data for the local timezone.  On Android that file may be somewhere else, or it may not exist.

See initLocal in time/zoneinfo_unix.go.

**Comment by rakyll** [comment]
On Android, there is no /etc/localtime. The contents of /system/usr/share/zoneinfo is not similar to the other unixes, and TZ env var is not set.

All I was able to do was `getprop persist.sys.timezone`.
