### ISSUE TITLE
x/mobile/event: rename event package to touch

### ISSUE THREAD

**Issue by rakyll** [golang/go#10852]
Across the mobile repo, all of the sub-packages are named after their functionalities and export their own event types. This is not the case for the event package. The name suggests that it's a catch-all bucket containing all available events, but it actually only exports the touch event.

We should rename this package to "touch" and its event type to "Event" in order to keep the consistency.

/cc @crawshaw @hyangah

**Comment by minux** [comment]
Dup of #10444.

**Comment by rakyll** [comment]
Lost memories... Sorry for the noise.
