### ISSUE TITLE
os/user functions aren't implemented on Linux/386

### ISSUE THREAD

**Issue by fd0** [golang/go#10868]
I'm using Go 1.4.2 on Linux/amd64 and was unpleasantly surprised that the functions in the `os/user` package aren't implemented for GOARCH=386, e.g. a call to `user.

```
$ cat usertest.go
package main

import (
	"fmt"
	"os/user"
)

func main() {
	u, err := user.Current()
	fmt.Printf("current user: %#v %#v\n", u, err)
}

$ GOARCH=amd64 go run usertest.go 
current user: &user.User{Uid:"1000", Gid:"1000", Username:"fd0", Name:"Alexander Neumann", HomeDir:"/home/fd0"} <nil>

$ GOARCH=386 go run usertest.go 
current user: (*user.User)(nil) &errors.errorString{s:"user: Current not implemented on linux/386"}
```

I would expect that the functions work as advertised, it sad that there are  functions in the stdlib that (at least for me as a user) just don't work on some architectures. Is this documented somewhere and I overlooked it?

What's the reason for this?

**Comment by minux** [comment]
os/user needs cgo to function properly, but cgo is disabled
when cross compiling you need to set CGO_ENABLED=1
explicitly.

CGO_ENABLED=1 GOARCH=386 go run usertest.go

**Comment by fd0** [comment]
Thanks a lot for this clarification! (At least there is an issue here that others can find via Google).
