### ISSUE TITLE
x/net/websocket: websocket.Conn.Close leaks file descriptors if remote has disconnected

### ISSUE THREAD

**Issue by davecheney** [golang/go#10866]
In the current Conn.Close behaviour can leak file descriptors if the server has gone away before the client calls .Close
```
// Close implements the io.Closer interface.
func (ws *Conn) Close() error {
	err := ws.frameHandler.WriteClose(ws.defaultCloseStatus)
	if err != nil {
		return err
	}
	return ws.rwc.Close()
}
```
In the case that the remote side has closed the connection, WriteClose will return an error which will be returned to the caller _without_ calling `ws.rwc.Close`. As it is customary to ignore the error from an `io.Closer.Close`, and even when not, the error is treated as opaque there is no indication that Close didn't actually release the file descriptor associated with `ws.rwc`. Even if the error was handled from the caller of Close, it would typically be `io.EOF` or some operating system specific version of "connection closed unexpectedly".

/cc @bradfitz

**Comment by mikioh** [comment]
Closed by https://github.com/golang/net/commit/bb64f4dc73d4ab97978d5e1cb34515dcc570361b.
