### ISSUE TITLE
cmd/go: go help build incorrectly describes behaviour of flag -o

### ISSUE THREAD

**Issue by okdave** [golang/go#10865]
The help for go build doesn't correctly describe what the effect of `-o` has on the output file (if any). It also seems internally inconsistent.

From experimenting on the command line `-o /tmp/foo` will produce an object file when building non-main packages iff the package is somewhere in goroot or a gopath. Specifically running `go build -o /tmp/foo` at the directory:

  1. $GOROOT/src/fmt – object file created
  2. $GOPATH/src/golang.org/x/net/context – object file created
  3. /tmp/my_binary (containing `package main` main.go) – binary file created
  4. /tmp/my_pkg (contain `package foo` foo.go) – **no** file created

Further, the output of `go help build` seems to contradict itself. It first states that the results will be discarded for anything other than a single package main. The next paragraph then describes what the output file name will be for non-main packages if no other name is specified.

> When the command line specifies a single main package,
build writes the resulting executable to output.
Otherwise build compiles the packages but discards the results,
serving only as a check that the packages can be built.

> The -o flag specifies the output file name. If not specified, the
output file name depends on the arguments and derives from the name
of the package, such as p.a for package p, unless p is 'main'. If
the package is main and file names are provided, the file name
derives from the first file name mentioned, such as f1 for 'go build
f1.go f2.go'; with no files provided ('go build'), the output file
name is the base name of the containing directory.

**Comment by okdave** [comment]
I can tackle this, but I think both the docs and the build tool need tweaking. The behaviour should be:

* if no -o flag
  - if a single main package is provided, derive the output name automatically
  - otherwise, build then discard the results
* if -o flag
  - if a single package, write to the given file
  - otherwise, fail (report error)

**Comment by adg** [comment]
What you describe is the way I assumed it worked. cc @davecheney @rsc
