### ISSUE TITLE
if err != nil => ||

### ISSUE THREAD

**Issue by xulis** [golang/go#10877]
I have a suggestion
`
_,err := xxoo()
if err != nil {
return 1
}
`
=>
`
_,err := xxoo() || return 1
`

**Comment by minux** [comment]
If you're proposing language changes, please use
the golang-nuts mailing list.

PS: similar ideas have been proposed before, and
rejected. Search the mailing list archive.

**Comment by xulis** [comment]
Okay, thank you for your answer
