### ISSUE TITLE
html/template: Clone an empty template leads to runtime panic

### ISSUE THREAD

**Issue by paradoxe** [golang/go#10879]
Hi,
When executing:
~~~ go
t:= template.New("base")
c, err := t.Clone()
~~~
I get:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b78dc]
 goroutine 1 [running]:
 text/template.(*Template).Clone(0xc20806a040, 0x5516a0, 0x0, 0x0)
	/usr/local/go/src/text/template/template.go:78 +0x1cc
 html/template.(*Template).Clone(0xc20803a5a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:193 +0x20d

I admit that it is an extreme use-case. 

go version go1.4.2 linux/amd64

Many thanks

**Comment by syst3mw0rm** [comment]
https://go-review.googlesource.com/#/c/10240/
