### ISSUE TITLE
path/filepath: Glob malfunction under Windows when pattern matching is used

### ISSUE THREAD

**Issue by laszlothewiz** [golang/go#10875]
Here's a sample code to illustrate the problem which stems from a case sensitive string matching somewhere in the code:

	package main

	import (
		"fmt"
		"path/filepath"
	)

	func main() {
		a,_ := filepath.Glob("c:\\users\\*\\appdata")
		fmt.Println(a)  //this prints []
		b,_ := filepath.Glob("c:\\users\\*\\AppData")
		fmt.Println(b)  //this prints [c:\users\Default\Appdata ...]
	}

Because file and directory names in Windows are case insensitive therefore this is a bug.

Please note that before the asterisk(*) the path name does not have to match case but after the asterisk it doesn't provide any results if the case doesn't match.

**Comment by alexbrainman** [comment]
Dup of #5441?

Alex

**Comment by laszlothewiz** [comment]
Possibly. But that one is an old issue (over 2 years old) which should have been fixed a long time ago. I think we should keep this open to have more chance that this issue gets fixed.

**Comment by adg** [comment]
@laszlothewiz that's not how our process works. If you want to help get the problem fixed, you'd best update the existing issue #5441 add some more information and propose a fix (or track down @alexbrainman's old proposed fix). Keeping duplicate issues open doesn't help anyone, and FWIW all else being equal we're more likely to fix an old issue than a new one.
