### ISSUE TITLE
cmd/doc: running "go doc ./package" can take very long time

### ISSUE THREAD

**Issue by kostya-sh** [golang/go#10883]
It looks like "go doc ./package" scans GOPATH inspecting every file looking for a directory that ends with "./package". There is no such directory of course. This takes lots of time (minutes) with GOPATH that has lots of files.

"./package" is probably not the correct package specification for "go doc" but still something that users might try to execute. It would be good to fail early in this case rather then making a user wait for a long time.

**Comment by josharian** [comment]
Fixed by CL 10285.
