### ISSUE TITLE
cmd/yacc: write docs for custom error message

### ISSUE THREAD

**Issue by minux** [golang/go#10888]
And preferably, with examples.

Please also put the feature into doc/go1.5.txt.

**Comment by andrewchambers** [comment]
Russ wrote this before, there are some references, assuming this still uses the same methods  - http://research.swtch.com/yyerror

**Comment by bradfitz** [comment]
cmd/yacc no longer used and doesn't live in the main repo anymore (https://golang.org/doc/go1.8#tool_yacc), so closing this issue.

**Comment by purpleidea** [comment]
Are there any docs on how to get the custom error messages? (eg: why was this closed?) I found `yyErrorMessages` in current generated `go tool yacc` code. I was wondering if anyone has some current pointers into getting this all going. I'm looking at implementing this technique: https://research.swtch.com/yyerror -- Thanks!

**Comment by mdempsky** [comment]
I suppose it could be recategorized as x/tools/cmd/yacc instead.

You can look at go.y, before it was removed: https://github.com/golang/go/blob/f1b919574cf8022d09afdece1f76b2c2b2529004/src/cmd/compile/internal/gc/go.y

The syntax is `%error`, a sequence of tokens, a `:` character, and then the custom error string. Basically the same as the old go.errors format.

**Comment by purpleidea** [comment]
@mdempsky This was really helpful thanks!

Looking into the source code, and the generated code it seems that there's a global var: `yyErrorVerbose`, which is set to false, and which unless true prevents the display of these fancy new error messages... How does one set it to true?

It looks to be hardcoded with no flags, and sed tricks aren't very pretty. It's here: https://github.com/golang/tools/blob/master/cmd/goyacc/yacc.go#L3265 maybe the processing function has some weird trick, but I haven't read through all that code yet. It's a bit confusing at first glance.

Secondly, any chance you could give me a few more tips about writing the token sequences? In particular, given a grammar like this:

```
resource_body:
	/* end of list */
	{
		$$.fields = []*StmtResField{}
	}
|	resource_body resource_field
	{
		$$.fields = append($1.fields, $2.field)
	}
;
resource_field:
	IDENTIFIER ROCKET STRING COMMA
	{
		$$.field = &StmtResField{
			field: $1.str,
			kind: reflect.String,
			value: $3.str,
		}
	}
|	IDENTIFIER ROCKET INTEGER COMMA
	{
		$$.field = &StmtResField{
			field: $1.str,
			kind: reflect.Int64,
			value: $3.int64, // int64
		}
	}
;
```

How do you express a token list for the %error pattern that know what context it's in? For example, a missing comma. I tried a plain: `IDENTIFIER ROCKET STRING` but it generates the wrong state table entry. (I've been reading a lot of generated code :P)

Thanks in advance!
James

**Comment by purpleidea** [comment]
FYI: for future readers, by adding this:

```
func init() {
	yyErrorVerbose = true // set the global that enables showing full errors
}
```

to the file somewhere will cause the global to get set on import, and the errors will get shown.
