### ISSUE TITLE
x/tools/go/pointer: analysis not done concurrently

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#10895]
Tracing an oracle pointsto query shows that 3252ms out of 4583ms is spent doing pointer analysis and it  is done entirely in one thread. Making some of the passes in the pointer analysis run in parallel should help with this.

**Comment by adonovan** [comment]
Andersen's analysis is not easily parallelizable.  There has been some recent work by Pingali's group at UT Austin on parallel (2010) and GPU-based (2012) implementations, but the implementation complexity is fearsome.

**Comment by alandonovan** [comment]
If any speed freaks want to try to make the golang.org/x/tools/container/intset package faster, that would be a help.

**Comment by DanielMorsing** [comment]
I'm thinking there's some gains to be had here, where the constraints are generated on a single goroutine https://github.com/golang/tools/blob/master/go/pointer/gen.go#L1296

**Comment by alandonovan** [comment]
Yes, but the constraint generation is not the expensive part.
