### ISSUE TITLE
cmd/gc: memory corruption at "optimize append + write barrier"

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10897]
Starting at 8552047a32cccccc1c376e49048c5a22494b7611 (optimize append + write barrier), Camlistore's camput randomly crashes, and pretty reliably.

I haven't reduced it down to a minimal repro yet, but you can reproduce by hand with:

```
$ go get camlistore.org/dev/devcam
$ cd $GOPATH/src/camlistore.org  # assuming a single path in GOPATH
$ rm -rf tmp/build* bin/camput

$ devcam server --mini --wipe &    # and wait for it to compile and start up
$ devcam put file --filenodes /path/to/photos/*.jpg 
```

My set of photos was 630 JPEGs, ~2GB total. They don't have to be JPEGs. Files of random size (around the same size on average) and contents would work just as well.

In my experience, it crashes or fails in one of 3 ways, usually in FileWriter / span.size code, but sometimes with an assertion that the schema blob must contain either a bytesref part or blobref part.

Repeated from the email to golang-dev:

No usage of unsafe.

Go 1.4 race: no races.
Go tip race: no races.
Go 1.4: works
Go tip: 3 or so different crashes very soon after uploading between 0 and a few files
Go tip w/ GOGC=off: works

**Comment by rsc** [comment]
Reproduced locally. Thanks for the script.
