### ISSUE TITLE
9 is not prime

### ISSUE THREAD

**Issue by jameshfisher** [golang/go#10892]
Is [this](https://github.com/golang/go/blob/master/doc/go_spec.html#L2398) an inside joke? It made me twitch when I read it.

**Comment by mikioh** [comment]
See a044154a4c82af185d56ed5826d9946cd065178b.

**Comment by mikioh** [comment]
This is a duplicate of #2870.

**Comment by jameshfisher** [comment]
Haha, okay, I assume it is an inside joke, because I don't get it. :-)

**Comment by mikioh** [comment]
See http://en.wikipedia.org/wiki/Paul_Erd%C5%91s
