### ISSUE TITLE
doc: document the "Deprecated" convention

### ISSUE THREAD

**Issue by minux** [golang/go#10909]
Perhaps in effective go. Also worth mention in go1.5.html?

see https://groups.google.com/forum/#!topic/golang-dev/ya5vE0G62Z4.

**Comment by robpike** [comment]
In go1.5.html yes, in Effective Go, no.

**Comment by adg** [comment]
But go1.5.html is a changelog. We should document the convention itself
somewhere. In the godoc docs?

**Comment by robpike** [comment]
Seems like a better place. Or maybe we need a general conventions, or document conventions, document.

**Comment by minux** [comment]
I like the idea of a document conventions docs.

**Comment by shurcooL** [comment]
What is the final convention that was decided on? It's really hard to conclusively parse it out of the linked thread even after reading all comments.

**Comment by minux** [comment]
Please see https://golang.org/cl/10188 for examples.

There are three forms:
1. inlined form
type T struct {
    FieldA int32 // Deprecated: use FieldB instead.
    FieldB int64
}

2. long form 1, used with entities lacking docs
// Deprecated: T is deprecated.
type T struct {
     // Deprecated: for backward compatibility FieldC is still populated,
     // but new code should use FieldD instead.
     FieldC int32

     FieldD int64
}

3. long form 2, used for entities with docs
// Do fires the missiles.
//
// Deprecated: missiles supplies depleted. Do is a no-op now.
func Do() error

**Comment by shurcooL** [comment]
I have a question. Would it be better or not if "Deprecated:" was made mandatory to be the first word of a doc comment for a deprecated field/variable/func/method? That seems like the first thing the documentation should convey, and having it be something other than the first word means a user is possibly going to spend some time reading/learning about a new method before realizing that it's already deprecated.

Consider the 3rd example above:

```Go
// Do fires the missiles.
//
// Deprecated: missiles supplies depleted. Do is a no-op now.
func Do() error
```

A user would need to read all of "Do fires the missiles." or however long that comment is, while spending energy understanding the functionality, only then to hopefully get to the next paragraph that says it's deprecated and they should be reading about something else instead.

I had this thought on my mind and just wanted to share it.

**Comment by shurcooL** [comment]
A better real-world example where the problem is worse can be seen here:

```Go
// StringSlicePtr converts a slice of strings to a slice of pointers
// to NUL-terminated byte arrays. If any string contains a NUL byte
// this function panics instead of returning an error.
//
// Deprecated: Use SlicePtrFromStrings instead.
func StringSlicePtr(ss []string) []*byte {
```

**Comment by adg** [comment]
I don't really like the idea of putting the word "Deprecated" first. With
the current scheme, it's nice that the reason for the deprecation appears
after "Deprecated:".

But perhaps godoc should be made to hide or collapse the definitions of
deprecated functions, and to highlight the word "Deprecated" in bold and/or
red. WDYT?

**Comment by shurcooL** [comment]
> With the current scheme, it's nice that the reason for the deprecation appears
after "Deprecated:".

I agree, that should be preserved. The way I imagined it would be:

```Go
// Deprecated: Use SlicePtrFromStrings instead.
//
// StringSlicePtr converts a slice of strings to a slice of pointers
// to NUL-terminated byte arrays. If any string contains a NUL byte
// this function panics instead of returning an error.
func StringSlicePtr(ss []string) []*byte {
```

> I don't really like the idea of putting the word "Deprecated" first.

Do you still dislike it even given what I've mentioned above? If so, that's completely okay. I just wanted to mention this so that it would be considered.

> But perhaps godoc should be made to hide or collapse the definitions of
deprecated functions, and to highlight the word "Deprecated" in bold and/or
red.

Perhaps it (and many other Go editors/tools) can/should do that. But I think that's an orthogonal optional enhancement.

I realize requiring "Deprecated:" to come first will require an update to `golint` which currently checks that comments begin with "// {{.IdenitiferName}} ...".

**Comment by adg** [comment]
That does seem reasonable. I don't have strong feelings one way or another.

**Comment by rsc** [comment]
I'm sorry, but breaking the rules about how doc comments begin is off the table.

**Comment by shurcooL** [comment]
No problem, thanks for considering it!

In that case, existing tools can choose to detect deprecated methods and visually warn users about that, if they deem that to be an improvement/worth doing.

**Comment by mibk** [comment]
> But perhaps godoc should be made to hide or collapse the definitions of
> deprecated functions, and to highlight the word "Deprecated" in bold and/or
> red. WDYT?

Have you been considering emphasizing the deprecated stuff in godoc ever since? As an
alternative solution the strike-through format could be used.

**Comment by FiloSottile** [comment]
I created https://golang.org/wiki/Deprecated to have something to link to.
