### ISSUE TITLE
os: TestRemoveAllRace failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#10911]
Since May 13, the old school Plan 9 builder is intermittently failing on:

```
--- FAIL: TestRemoveAllRace (0.10s)
	os_test.go:1697: unexpected error: *os.PathError, "stat /tmp/issue008739954: stat buffer too short"
FAIL
FAIL	os	1.074s
```

http://build.golang.org/log/69b86932b8a019b1cddd72fcb23ebcaf34596803

I think the first failure appeared after changeset [6f2c0f1585e5](https://github.com/golang/go/commit/6f2c0f1585e5) (CL [9964](https://golang.org/cl/9964)).

I've not been able to reproduce this issue when running the test manually.

**Comment by bradfitz** [comment]
If this is actually due to the malloc-in-signal-handler CL, why wouldn't we see the `throw("malloc during signal")` in the crash?

/cc @rsc

**Comment by 0intro** [comment]
I don't think this issue is due to the malloc-in-signal-handler CL. It looks unrelated.
It's just that the first failure happened after this change.

This failure seems to happen every 2-7 builds, so it could be caused by an older change.
