### ISSUE TITLE
go/build: expose defaultCC

### ISSUE THREAD

**Issue by davecheney** [golang/go#10916]
`defaultCC` is written by 'cmd/dist' into `cmd/go/zdefaultcc.go` and `cmd/cgo/zdefaultcc.go`, but neither of those locations can be used because (a) they are commands (b) the value is not exported.

Could `defaultCC` be written as `DefaultCC` into `go/build` so it can be reused by other tools that need access to the C compiler that the Go install was installed with.

**Comment by minux** [comment]
Shell out to "go env CC" or "go env CXX"?

This also handles the CC/CXX environment variable.

defaultCC mechanism is bad fit for the go tool as it only handles one
platform, but I'd it to be able to handle multiple platforms.

**Comment by ianlancetaylor** [comment]
Simply adding DefaultCC is the wrong approach because in principle we want to have a different default compiler for different GOARCH/GOOS values.  Closing this out, but reopen if you want an approach different from calling "go env CC".

**Comment by davecheney** [comment]
That's fair. I'll find another way to do it.
