### ISSUE TITLE
Go get ignore global proxy settings

### ISSUE THREAD

**Issue by denghongcai** [golang/go#10915]
Go version: go1.4.1 linux/amd64
OS: Ubuntu 14.04.2

Due to some reason, I have to set proxy to use `go get`. If target repo is in github or other git repos, I just set HTTP_PROXY, HTTPS_PROXY and GIT_PROXY to make it work great. But if target repo is in golang.org/x, seems that it must fetch meta data first and use a different method to download code. For example, I always failed at: 

```
Fetching https://golang.org/x/crypto/openpgp?go-get=1
https fetch failed.
Fetching http://golang.org/x/crypto/openpgp?go-get=1
import "golang.org/x/crypto/openpgp": http/https fetch: Get http://golang.org/x/crypto/openpgp?go-get=1: dial tcp 74.125.204.141:80: i/o timeout    // The error msg shows that it uses golang builtin net package
package golang.org/x/crypto/openpgp: unrecognized import path "golang.org/x/crypto/openpgp"
```

Is there a way i missed to set  proxy for it or it just a problem? Thanks

**Comment by minux** [comment]
go get uses net/http.DefaultTransport, so setting proxies with
$HTTP_PROXY should be effective.

**Comment by denghongcai** [comment]
Yes, it's my mistake...works great now
