### ISSUE TITLE
RoundTripper behavour change

### ISSUE THREAD

**Issue by kylewolfe** [golang/go#10918]
Change in question: https://github.com/golang/go/commit/e1d9fcd267e1a827e9841dce4c91def0777a90ee#diff-91f5f51987ce03a73a7d2e8b701f84e9R142

I realize that the functionality of RoundTripper was poorly defined. I tried asking several times on the gonuts forum as well as stackoverflow as to its intention, and how it should be used. With this change however, it now breaks some functionality I had in a previous version of Go.

I unfortunately have to deal with SOAP APIs quite frequently. So I use a custom RoundTripper that parses the response body for the fault and returns a new error type specific to a soap fault. While I know this goes against what was then slightly documented (http://golang.org/pkg/net/http/#RoundTripper), I'm note sure I'm sold that this restriction of resp == nil when error != should be enforced, as it was not before.

**Comment by bradfitz** [comment]
You don't clarify which versions of Go.

Specify which version of Go you used before and in which version the behavior changed.

But I suspect you're talking about things <= Go 1.4, in which case the ship has sailed.

I'm also not just what SOAP has to do with this bug.

**Comment by bradfitz** [comment]
Yeah, that CL was almost 3 years ago and just clarified the status quo. I don't believe there's anything to do here.

**Comment by kylewolfe** [comment]
A custom SOAP RoundTripper is just my use case in which I think a response should be returnable along with an error.

Sorry for not supplying versions. I do believe you are correct. I am running go 1.4.2 and was using 1.3.x when the functionality was working.

**Comment by rogpeppe** [comment]
I would suggest that RoundTripper is too low a level for SOAP functionality.

**Comment by kylewolfe** [comment]
Ideally I would like to create a wrapper to http.Client. However there is not a Client interface in the standard library. Due to this, APIs have to request a pointer to an http.Client struct, which makes it impossible to wrap a http.Client and satisfy that dependency in third party APIs.

Are there an discussions around this, perhaps? I'd like to try to get this in to discussions for Go 2 if possible.
