### ISSUE TITLE
cmd/go: disable go get chatter about git config

### ISSUE THREAD

**Issue by rsc** [golang/go#10922]
This looks like bad debugging prints:

	g% go get -u rsc.io/benchstat
	# cd /Users/rsc/g/src/rsc.io/benchstat; git config remote.origin.url
	# cd /Users/rsc/g/src/rsc.io/benchstat; git config remote.origin.url
	g%

**Comment by dsymonds** [comment]
I can't reproduce this at tip. Near as I can tell, those lines come from src/cmd/go/vcs.go:309, but are only printed when the command fails. That'll happen if, for instance, you don't have a remote called "origin" in an existing repository.

**Comment by c9s** [comment]
Can't reproduce too. at commit 80864cf1f7804e23be215245a70d70efd1116bb4

**Comment by c9s** [comment]
I can now reproduce it, I dropped the remote from `rsc.io/benchstat` and re-run command again, it shows the same message.

```
go get -u rsc.io/benchstat
# cd /Users/c9s/src/rsc.io/benchstat; git config remote.origin.url
# cd /Users/c9s/src/rsc.io/benchstat; git pull --ff-only
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
```

**Comment by c9s** [comment]
The error message is improved in this CL: https://go-review.googlesource.com/10475

**Comment by rsc** [comment]
Fixes syntax was wrong.
