### ISSUE TITLE
text/template: t.New() doesn't save entry in t.tmpl

### ISSUE THREAD

**Issue by syst3mw0rm** [golang/go#10926]
```
package main

import (
        "fmt"
        "text/template"
)

func main() {
        t, _ := template.New("base").Parse(`{{define "foo"}}foo{{end}}`)
        fmt.Println(t.Lookup("base"))
        fmt.Println(t.Lookup("foo"))

        t.New("bar")
        fmt.Println(t.Lookup("bar"))
}
```
returns
```
&{base 0x208304000 0x20829c400  }
&{foo 0x2083040e0 0x20829c400  }
<nil>
```
on commit https://github.com/golang/go/commit/5b66e5d0d853e292c8c90512b33257c3a6e089e1

Last line of output should not be `<nil>`

**Comment by syst3mw0rm** [comment]
@robpike I've the fix ready, I'll push the CL once you merge https://go-review.googlesource.com/#/c/10240/

**Comment by robpike** [comment]
Working as intended. There is no definition yet, just a name. This is a documentation issue.
