### ISSUE TITLE
cmd/vet: doesn't warn about function literals passing Locks by value

### ISSUE THREAD

**Issue by dgryski** [golang/go#10927]
`vet` currently warns when a function is declared to take a Lock , but not for function types or if the function is a function literal.

```
<dgryski@kaepora[w] \ʕ◔ϖ◔ʔ/ > cat main.go
package main

import "sync"

var f2 func(sync.Mutex) = func(mu sync.Mutex) {}

func f(mu sync.Mutex) {}
<dgryski@kaepora[w] \ʕ◔ϖ◔ʔ/ > go vet main.go
main.go:7: f passes Lock by value: sync.Mutex
exit status 1
```

**Comment by josharian** [comment]
Good find. This is probably relatively straightforward, if you have any interest in tackling it. It probably consists of locating and extracting the relevant types and running them through lockPath. See https://github.com/golang/tools/blob/master/cmd/vet/copylock.go, https://github.com/golang/tools/blob/master/cmd/vet/testdata/copylock_func.go, and https://github.com/golang/tools/blob/master/cmd/vet/testdata/copylock_range.go.
