### ISSUE TITLE
cmd/6g: invalid type inference

### ISSUE THREAD

**Issue by zagrodzki** [golang/go#10925]
http://play.golang.org/p/LoD6rBZe8J

Expected result: "[[one] [two] [three]]"
Actual result: "[[three] [three] [three]]".

I believe this is due to incorrect type inference. I think when f is
declared in line 8, it inherits the type together with the "does not
escape" property of the "ss" argument in "prototype". The result is
that f([]string{s}) reuses the same array underlying the slice, as
seen here:

http://play.golang.org/p/VU_J0UrURA

Using explicit type or removing argument name in the prototype()
results in correct escape analysis and does not exhibit the bug:

http://play.golang.org/p/g5bHU-0KRS

gccgo does not seem to have this bug.

**Comment by bradfitz** [comment]
Thanks for the report!

/cc @rsc @dr2chase @josharian @minux

**Comment by dr2chase** [comment]
I suspect that sharing of leaves of the tree ([] string literal?) has bit us.
First interesting diff (other than missing name on prototype):
bad:
./badte.go:11::assignfromtag:: src=[]string literal, em=EscNone

good:
./badte.go:11::assignfromtag:: src=[]string literal, em=EscUnknown
./badte.go:11:[2] main escassign: .sink( class(PEXTERN) ld(-1))[NAME] = []string literal( l(11) esc(no) ld(2))[ARRAYLIT]
./badte.go:11::flows:: .sink <- []string literal

**Comment by dr2chase** [comment]
Nope, reuse of type.
Mistakes were made.

**Comment by josharian** [comment]
@dr2chase may I infer that you're on top of this? If this is due to CL 9419, we could just revert that CL.

**Comment by bradfitz** [comment]
@josharian, this is broken in both Go 1.4 and tip.

**Comment by dr2chase** [comment]
This looks like a long-standing bug.  I am working on it, there appears to be a fix that I am benchmarking and testing right now.
