### ISSUE TITLE
doc/asm: update for Go 1.5

### ISSUE THREAD

**Issue by minux** [golang/go#10932]
missing pieces:
1. more textflags (`NEEDCTXT`, `LOCAL`)
2. no more reference to C source code in compiler/linker (e.g. `$GOROOT/src/cmd/8l/8.out.h`)
3. need docs for ppc64/ppc64le and arm64 specific problems

needs update:
1. "Some of the assemblers enforce this convention, rejecting plain 0(FP) and 8(FP). " I believe cmd/asm enforces this now, so it should be changed to "all assemblers enforce this convention".

There are probably others things that need update.

**Comment by ALTree** [comment]
#10096

**Comment by minux** [comment]
Merged into #10096.
