### ISSUE TITLE
os: Stat fails on NTFS volumes with Deduplication enabled

### ISSUE THREAD

**Issue by NTmatter** [golang/go#10935]
- Go Version: go1.4.2 windows/amd64
- OS and Arch: Windows 8.1 Pro 64-bit.
- Action: <code>os.Stat("Path\to\deduped.file")</code>
- Expected Result: successfully returns (FileInfo, nil)
- Actual Result: <code>err := "readlink Path\to\deduped.file: The system cannot find the file specified."</code>

From a bit of digging, the issue is caused by NTFS Dedupe using reparse points for deduplicated files. The Windows implementation of [fileStat.Mode()](https://github.com/golang/go/blob/439b32936367c3efd0dadab48dd51202e1a510f1/src/os/types_windows.go#L42-L44) treats all reparse points as symlinks, however there are several [other cases](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365511%28v=vs.85%29.aspx) to consider, including Deduplication and Mount Points, neither of which are symlinks.

The Windows implementation of os.Readlink() already performs a [sanity check](https://github.com/golang/go/blob/439b32936367c3efd0dadab48dd51202e1a510f1/src/syscall/syscall_windows.go#L1005-L1007) to ensure that it is handling a symlink. Ideally a similar inspection could be performed in Mode(), checking for <code>IO_REPARSE_TAG_DEDUP == 0x80000013</code> and stripping the Symlink flag, allowing the file to be treated as Regular.

**Comment by alexbrainman** [comment]
@NTmatter would you like to send a fix for this? You seems to know all about these file types. See http://golang.org/doc/contribute.html for details. If not, I will fix it myself.

Alex

**Comment by NTmatter** [comment]
I can take a stab at it if you don't have enough bandwidth. It'll probably be a few days before I can get a proper dev and test environment together, depending on my workload.

**Comment by alexbrainman** [comment]
Please try to fix this. I don't know much about any of this and don't really want to learn. But happy to review your code. I can test your code if you don't have appropriate environment setup. Good new test will make our task much easier, considering I know little about the subject. Test that breaks with current tip, but PASSes once your changes are applied.

No pressure. I will do it myself, if you cannot do it. Thank you.

Alex

**Comment by NTmatter** [comment]
I've got a basic dev environment running now. Should be possible to start looking at it in the next day or two :)

**Comment by NTmatter** [comment]
Took a bit longer than expected, but a small change set is up for review at https://go-review.googlesource.com/11330/
