### ISSUE TITLE
encoding/json: Wrong marshal output on embeded structure with the custom marshaller

### ISSUE THREAD

**Issue by fzerorubigd** [golang/go#10939]
Having an embeded struct with custom marshalJSON function, make the json.Marshal to use that marshal function in the base structure. 

```go
package main

import (
	"encoding/json"
	"fmt"
)


type h0 struct {
	M []string
}

func (a h0) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.M)
}

type h1 struct {
	h0 `json:"hedaer"`
	A string
	B string
}

func main() {

	v := h1{}
	v.A = "A" 
	v.B = "B"
	v.M = append(v.M, "1", "2", "3")
	
	
	a, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(a))
}
```

Output must be : 

```json
{"hedaer":["1","2","3"],"A":"A","B":"B"}

```

But is : 

```json
["1","2","3"]
```

in playground : https://play.golang.org/p/619v_hL5hh

the reason is obvious, since the function invoked on the outer structure, but I think json library must ignore this kind of marshaller functions. 
I test this against the latest version of go (1.4.2) in linux, and also the git version of go . 
Any other information is required?

**Comment by minux** [comment]
working as intended.

you've embedded type h0 in type h1, which means
h1 also get h0's methods, which in turn means that
h0 is a a json.Marshaler, but it only marshals the
embedded h0 field.
