### ISSUE TITLE
Support multiple return from map lookup

### ISSUE THREAD

**Issue by ngreduce** [golang/go#10947]
Hello. I am new to golang, but there is a small proposal.
I don`t know how this affects other parts, may be you will help understand them.
Look at this sample of code: http://play.golang.org/p/ik8RK3p5i7

Seems like compiler doesn`t understand that should return two arguments instead of
s := m["A"] syntax.

Commented code works fine, but is a bit ugly.
Looks like backward-compatible change for me.
Thank You guys, best programming language i`ve used so long

**Comment by minux** [comment]
Please discuss language changes on the golang-nuts mailing list
first.

**Comment by ALTree** [comment]
This was discussed in the past on the mailing list, e.g. [here](https://groups.google.com/d/msg/golang-nuts/wNdPgX8Pumg/-xESRBEz6dwJ). The last post explains the design decision behind the status quo.

**Comment by ngreduce** [comment]
Thank you for privided link.
