### ISSUE TITLE
website: stylesheet glitch with Firefox

### ISSUE THREAD

**Issue by porjo** [golang/go#10961]
When viewing the golang.org website with Firefox 38 on Linux (Fedora 22) I see a grey background where there should be white. Loading the same page with Chrome on Linux displays white background.

The following screenshot shows Firefox on the left and Chrome on the right:
![go_screen](https://cloud.githubusercontent.com/assets/1296987/7823916/5665bbf6-0442-11e5-9fe8-7041d8ae364b.png)

I checked the default background color in Firefox settings and that is set to white. I haven't noticed any other style glitches with other websites so far using Firefox 38.

**Comment by philbates35** [comment]
I also have the same issue in Firefox Fedora 22 (upgraded from Fedora 21 yesterday using fedup after the stable was released). I have a feeling this is more a Fedora 22 / Firefox issue rather than specific to go, given that it's happening for me on lots of other sites as well in Firefox only.

**Comment by minux** [comment]
Cannot reproduce with Firefox 38 on both Debian and Ubuntu.

**Comment by porjo** [comment]
@philbates35 interesting. Can you give an example of another site where this is happening for you?

**Comment by porjo** [comment]
I found the cause of the issue. Under 'Preferences -> Content -> Colors' I found a checkbox called 'Use system colors'. Unchecking that has resolved the issue for me. @philbates35 can you confirm?

I guess that means golang.org does rely on a default color for background, and in this case was defaulting to grey. IMHO, it would be better to explicitly set a background color.

**Comment by minux** [comment]
godoc.org is indeed using the default background color.
I will send a patch to update it to explicit white.

**Comment by porjo** [comment]
@minux FYI, your fix has not made it to golang.org yet. How long does it normally take?

**Comment by adg** [comment]
I'll re-deploy it now.

**Comment by adg** [comment]
The fix is now deployed.
