### ISSUE TITLE
x/tools/cmd/gotype: can't find import

### ISSUE THREAD

**Issue by noonien** [golang/go#10969]
```
$ cat $GOPATH/src/x/y/y.go
package y

var Y bool = true
```
```
$ cat $GOPATH/src/x/x.go
package main

import (
	"x/y"
)

func main() {
	_ = y.Y
}
```

Executing `gotype $GOPATH/src/x/x.go` results in:

```
/home/george/.go/src/x/x.go:4:2: could not import x/y (can't find import: x/y)
/home/george/.go/src/x/x.go:8:6: undeclared name: y
```

`go run $GOPATH/src/x/x.go` produces no error.

**Comment by minux** [comment]
You need to go install x/y first.

**Comment by noonien** [comment]
I see. I figured as much from the code, however I considered it might be a bug.

Is there any particular reason for why the package has to be compiled in order to check the source code?

**Comment by minux** [comment]
please see https://github.com/golang/go/issues/10249#issuecomment-86671707
for a reason.

**Comment by noonien** [comment]
I see, that makes sense. Thanks!
