### ISSUE TITLE
cmd/compile: incorrect 'has no field or method' error

### ISSUE THREAD

**Issue by ncw** [golang/go#10977]
* What version of Go are you using (go version)?

The same problem exists on
```
go version go1.4.2 linux/amd64
go version devel +5ee5528 Thu May 28 12:04:35 2015 +0000 linux/amd64
```
* What operating system and processor architecture are you using?

Linux amd64, ubuntu 14.04

* What did you do?

```
git clone https://gist.github.com/883d01d0274dda5e32d1.git bug
cd bug
go build
```

* What did you expect to see?

No error

* What did you see instead?

```
./e.go:4: TypeType.New undefined (type *Type has no field or method New)
```

If you look in [t.go]( https://gist.github.com/ncw/883d01d0274dda5e32d1#file-t-go) you can see that method is defined.

If you concatenate [e.go](https://gist.github.com/ncw/883d01d0274dda5e32d1#file-e-go) and `t.go` and compile (remove duplicate package line) then it compiles fine.

[Here is the Gist](https://gist.github.com/ncw/883d01d0274dda5e32d1)

e.go
----

```go
package foo
 
var (
	Base = TypeType.New()
	// To trigger the problem
	//  * Need Base as argument - it is fine if you substitute with nil
	//  * Need the x, _ = form of call
	Something, _ = NewSomething(Base)
)
 
func NewSomething(t *Type) (*Type, error) {
	return nil, nil
}
```

t.go
----

```go
package foo
 
type Type struct{}
 
var TypeType *Type = &Type{}
 
func (t *Type) New() *Type {
	return &Type{}
}
```

**Comment by josharian** [comment]
This reproduces back to Go 1.2, and maybe further.

It reproduces with a single file:

```go
package foo

type T struct{}

var (
	t = T{}
	u = t.New()
)

func x(T) (int, int) { return 0, 0 }

var _, _ = x(u)

func (T) New() T { return T{} }
```

If you switch the order of the last two lines, then it compiles.

**Comment by Shugyousha** [comment]
This does work though.

``` go
package main

type T struct{}

var (
    t = T{}
    u = t.New()
)

func x(T) (int, int) { return 0, 0 }

func main() {
        var _, _ = x(u)
}

func (T) New() T { return T{} }
```
This may be expected though because the main function definition gets processed after all the other statements (does it?).
