### ISSUE TITLE
cmd/link: too many error messages when missing func main

### ISSUE THREAD

**Issue by josharian** [golang/go#10978]
With tip:

``` bash
$ echo "package main" > m.go
$ go build m.go
# command-line-arguments
runtime.main: call to external function main.main
runtime.main: main.main: not defined
runtime.main: undefined: main.main
```

With 1.4, there were at least only two; the "call to external function" didn't show up. One would be enough, maybe even one that addresses this fairly special situation head on.

Low priority.

**Comment by minux** [comment]
Do you think that the compiler should refuse to compile a package with the
import path (not just package name) without the main func?

This will catch the problem even earlier.

**Comment by josharian** [comment]
I don't know. Maybe, if -complete has been passed. (Although who writes a main function in assembly?) Or perhaps there are crazy, non-obvious uses in the dynamic linking world?

**Comment by minux** [comment]
Even for c-archive and c-shared build modes, we still require a dummy main.

**Comment by josharian** [comment]
See also #24809. The goal there, which dovetails with this issue, is to make it easier to diagnose the problem when you forget to have a `func main`.
