### ISSUE TITLE
reflect: MakeMap doesn't allow initial allocation size

### ISSUE THREAD

**Issue by dgryski** [golang/go#10985]
When using `make` to create a new map, you can pass a size for the initial allocation to prevent lots of resizes as keys are inserted.  When using reflection, this option is not available.

The reflect package should add `MakeMapSize(typ Type, size int)` to allow preallocation for maps created via reflection.

**Comment by randall77** [comment]
I did a little experiment to see if this was worth it.  The test is to allocate a map[int64]int64 and fill it with 1<<16 records.  Without reflect, it seems that preallocation saves about a factor of 2.  With reflect it saves only about 20%.  Reflect is pretty slow already, I'm not entirely convinced that this is worth the API surface.

That said, it is an easy modification.

BenchmarkRawMap        	     200	   8782041 ns/op
BenchmarkRawMapSize    	     300	   4168970 ns/op
BenchmarkReflectMap    	     100	  24216280 ns/op
BenchmarkReflectMapSize	     100	  19667848 ns/op

code here: https://go-review.googlesource.com/10510

**Comment by rsc** [comment]
I don't believe this is worth the API surface.
