### ISSUE TITLE
support: $PATH keeps resetting after terminal closed - been trying to correctly setup Go for hours now

### ISSUE THREAD

**Issue by acidflip** [golang/go#10993]
This is extremely annoying and it's made me cry numerous times.

### Information
<hr>
**Go Version:** go1.4.2 darwin/amd64
**Operating System:** Mac OS X 10.10.3
**Processor:** 2.6 GHz Intel Core i5
<br><br>
### The Problem
<hr>
So recently, I've been trying to install Go. I've been able to install it correctly with the .pkg installer ([go1.4.2.darwin-amd64-osx10.8.pkg](https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.pkg)). After that, I attempt to correctly set $GOPATH and configure my $PATH to include $GOPATH. This is were I'm having trouble.

I've been using [this video](https://www.youtube.com/watch?v=XCsL89YtqCs) to set up Go along with [this page](http://golang.org/doc/install). After following those instructions, my $GOPATH and $PATH are correctly configured. Yay!

However, if I exit out of Terminal or open a new terminal window, everything is reset. My $PATH gets reset back to before it was configured, just after the .pkg installer installed Go and my $GOPATH is reset nothing (it's blank). Basically after configuring $GOPATH and $PATH, exiting out of Terminal will revert these changes.
<br><br>
### Overall Question
<hr>
Is there anyway these can be permanently set? Because I'm new to Go and I'm getting very annoyed at this, especially since my first project is using an external package that I can't work on, test, or use if my $PATH keeps resetting itself.

P.S. Isn't it possible for the .pkg installer to just use a simple shell script to automatically set the $GOPATH and configure the users $PATH?

**Comment by adg** [comment]
What you want to do is edit the file `$HOME/.profile` and put this line at the bottom:
```
export PATH=$HOME/bin:$HOME/go/bin:$PATH
export GOPATH=/path/to/gopath
```

The pkg installer *should* add `/usr/local/bin/go` to your `PATH` by adding the file `/etc/paths.d/go`. Is there nothing there?

**Comment by acidflip** [comment]
I tried that and it solved the problem of `PATH` and `GOPATH` being reset whenever I changed Terminal windows or quit Terminal. However, after running `go install` on the `hello.go` package, it says that the command doesn't exist. Did I do something wrong?

![screenshot](https://cloud.githubusercontent.com/assets/6980221/7895626/09b350c6-0667-11e5-953d-329e429bab9b.png)

**Comment by minux** [comment]
The hello command is installed to $GOPATH/bin, so
either you also add $GOPATH/bin to your $PATH, or
you can use $GOPATH/bin/hello to invoke it.

Btw, please ask questions on the golang-nuts mailing
list (or the #go-nuts IRC channel).
