### ISSUE TITLE
cmd/go: goinstall -installsuffix={..} {package} attempts to install to $GOROOT/pkg/goos_goarch_{..}

### ISSUE THREAD

**Issue by james-lawrence** [golang/go#10998]
it looks like its trying to reinstall the runtime package with my suffix?
```
[jatone]$ $PWD
bash: /home/james-lawrence/development/gilo: Is a directory
[jatone]$ ls -lha bin/
total 8.0K
drwxr-xr-x 2 jatone jatone 4.0K May 30 07:11 .
drwxr-xr-x 5 jatone jatone 4.0K May 30 06:43 ..

[jatone]$ go env
GOARCH="amd64"
GOBIN="/home/james-lawrence/development/gilo/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/james-lawrence/development/gilo"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

[jatone]$ go install --installsuffix="abc" bitbucket.org/jatone/gilo/commands/...
go install runtime: mkdir /usr/lib/go/pkg/linux_amd64_abc/: permission denied

[jatone]$ ls -lha bin/
total 8.0K
drwxr-xr-x 2 jatone jatone 4.0K May 30 07:11 .
drwxr-xr-x 5 jatone jatone 4.0K May 30 06:43 ..

[jatone]$ go install bitbucket.org/jatone/gilo/commands/...
[jatone]$ ls -lha bin/
total 15M
drwxr-xr-x 2 jatone jatone 4.0K May 30 07:13 .
drwxr-xr-x 5 jatone jatone 4.0K May 30 06:43 ..
-rwxr-xr-x 1 jatone jatone 4.5M May 30 07:13 gilo
-rwxr-xr-x 1 jatone jatone 6.7M May 30 07:13 gilod
-rwxr-xr-x 1 jatone jatone 3.1M May 30 07:13 gilo-shim
```
go help build says:
	-installsuffix suffix
		a suffix to use in the name of the package installation directory,
		in order to keep output separate from default builds.
		If using the -race flag, the install suffix is automatically set to race
		or, if set explicitly, has _race appended to it.

unclear from that documentation that it'll recompile packages in GOROOT, I was only expecting stuff from the GOPATH environment variable to be impacted.

**Comment by ianlancetaylor** [comment]
Which version of go?

**Comment by minux** [comment]
I don't see a problem here.

go install --installsuffix="abc" bitbucket.org/jatone/gilo/commands/...
will also try to (re)installed the standard libraries (because there is
no installation of standard library with installsuffix abc). And that's
why it tries to write to $GOROOT/pkg/linux_amd64_abc.

go env showed that you have set $GOBIN, which will the location
all installed commands go.

**Comment by minux** [comment]
Basically, install suffix is a global setting, see
http://golang.org/pkg/go/build/#Context

so if set, all packages will go into a separate
directory.

**Comment by rsc** [comment]
See also #10210

**Comment by rsc** [comment]
Yes, this is how it's supposed to work. -installsuffix applies to all code, not just GOPATH.
