### ISSUE TITLE
x/crypto/ssh: support curve25519-sha256@libssh.org and diffie-hellman-group-exchange-sha256

### ISSUE THREAD

**Issue by jhogg41** [golang/go#11004]
Please add support for the following key exchange methods recommended as most secure at various places around the web:
curve25519-sha256@libssh.org
diffie-hellman-group-exchange-sha256

This is causing me grief as it is for the reporter of the following bug:
https://github.com/shazow/ssh-chat/issues/113

**Comment by jmrobles** [comment]
+1

**Comment by hanwen** [comment]
diffie-hellman-group-exchange-sha256 does a back-and-forth to establish a prime, so it is more complicated and slower.

I'll have a look to see if I can add the 25519 kex.

(If you're worried about NSA-style adversaries, ecdh-p256 is probably your safest bet for now.)
