### ISSUE TITLE
net/http/httptest: ResponseRecorder implements WriteString()

### ISSUE THREAD

**Issue by manucorporat** [golang/go#11000]
Let's say I have a `http.HandlerFunc` or a `http.Hander` I want to benchmark.
In a real world situation, this function would received an instance of `*http.response` which implements `WriteString()`. A call to `io.WriteString(w, str)` will execute `w.WriteString(str)` instead of `w.Write([]byte(str))` which save us a unnecessary allocation.

This situation is not consistent with `httptest.ResponseRecorder` because it does not implement `WriteString()`.

I propose to implement `WriteString(str)` in  `httptest.ResponseRecorder` in order to achieve more accurate benchmarks.
https://github.com/gin-gonic/go/commit/347b0c5aa60c47ac7a7fc0c0b267c8113ce2e66e

Off topic: maybe we should implement `WriteString()` in another instances of http.ResponseWriter such as: cgi.response and fcgi.response, but this is probably a different issue.

**Comment by bradfitz** [comment]
There are so many other differences. But sure. Not for Go 1.5, though, since we're in a freeze.

Send a CL after Go 1.5 is out in early August.

**Comment by manucorporat** [comment]
@bradfitz thanks for the info. keep the good work!
