### ISSUE TITLE
tour: BST

### ISSUE THREAD

**Issue by marslangoog** [golang/go#11009]
Context: /concurrency/7

I think the tutorial meant BST rather than just plain old binary tree.

**Comment by minux** [comment]
They're not binary search trees.
just plain binary trees.

(The tree.New function mentioned in the next slide
doesn't always generate a BST.)

**Comment by minux** [comment]
Update: the tree.New functions happens to
create BSTs, but that's not the point of this
exercise.

The exercise doesn't rely on the BST property,
so there is no need to mention BST here.

**Comment by marslangoog** [comment]
I assume the exercise wants users to compare the two trees element by element without sorting first?
