### ISSUE TITLE
tour: Page "range" is not clear

### ISSUE THREAD

**Issue by aviast** [golang/go#11016]
Context: /moretypes/12

There was insufficient information on the page for "range" to explain the associated code. Having not read the documentation for range I was not aware that i and v are both values returned by the range function - representing the index and value of each element of pow - and it took me a while to come to that realisation. I did not immediately realise that i and v were separated by a  comma as opposed to the semicolon I expected to see. This could be made clearer with a more verbose description.

**Comment by adg** [comment]
What about the next slide?

**Comment by aviast** [comment]
Well I generally don't move on to a subsequent slide until I've understood the current slide. That said, the next slide doesn't add much to my understanding. Both of these slides assume too much of the reader; given that it's a "Tour" it should assume nothing. The content from the Wiki (https://github.com/golang/go/wiki/Range) should be included here.

**Comment by kytrinyx** [comment]
I'll take this one.
