### ISSUE TITLE
x/net/unix: support credentials on unix sockets

### ISSUE THREAD

**Issue by rminnich** [golang/go#1101]
<pre>It would be useful to have these three functions:
func (c *UnixConn) Pid (pid int, err os.Error)

func (c *UnixConn) Uid (uid int, err os.Error)

func (c *UnixConn) Gid (gid int, err os.Error)

or even this:
func (c *UnixConn) PeerCred (pid, uid, gid int, err os.Error)

These are returned by SO_PEERCRED. This info is used just often enough
that these functions would come in
very handy.

I would submit a patch but my lawyers are still working on the CLA.

Thanks

ron</pre>

**Comment by jeffallen** [comment]
Passing fd's using SCM_RIGHTS is already supported: https://golang.org/src/syscall/syscall_unix_test.go?h=TestUnixRightsRoundtrip#L260

Passing credentials is already supported: https://golang.org/src/syscall/creds_test.go?h=TestSCMCredentials#L21

The autobind stuff is not supported but if someone needs it, they can implement it themselves with the pieces that already exist in the stdlib.

Please close this issue.

**Comment by ianlancetaylor** [comment]
@jeffallen Thanks.  Closing.
