### ISSUE TITLE
cmd/compile/ssa: panic in (*state).expr

### ISSUE THREAD

**Issue by josharian** [golang/go#11028]
Compiling this panics:

```go
package main

func f_ssa() {
	var y int
	_ = 1 / y
}
```

Given the comment in the code, this won't be surprising, but at least now we have a reproducer we can add as a test case. @randall77

**Comment by randall77** [comment]
Now generates a reasonable error:
SSA unimplemented: unhandled expr DIV

I'll close this for now.  We know DIV still needs to be implemented.
