### ISSUE TITLE
cmd/compile/ssa: panic: unexpected nil Type

### ISSUE THREAD

**Issue by josharian** [golang/go#11029]
Compiling this panics:

```go
package main

var s string

func f_ssa(x byte) byte {
	x = byte(1)
	var b byte = s[2]
	x = 2
	return b + x
}
```

I know that this is all WIP. Just filing this as I encounter them so that we can (1) shore up existing code as we go and (2) start building a suite of regression test cases.

**Comment by josharian** [comment]
This occurs because SSA treats strings as arrays, but they have a different Node structure.

@randall77, I'm happy to teach SSA about strings. Would you prefer separate ops (`StringIndex` to match `ArrayIndex`) or conditionals throughout (`if isString { ...`)?

**Comment by randall77** [comment]
I'm happy to introduce StringIndex if we need it.  Could you explain what is different about string indexing and array indexing?

**Comment by randall77** [comment]
https://go-review.googlesource.com/#/c/10449/ implements a bunch of string operations.  Anything there that might fix this?

**Comment by randall77** [comment]
This now generates a reasonable error:
SSA unimplemented: v13 = StringMake <string> v24 v25 not lowered

I think we just need an arch-indep rule for (ArrayIndex (StringMake ...) ...)

**Comment by josharian** [comment]
Still unimplemented, but this issue being open now adds nothing.
