### ISSUE TITLE
compress/bzip2 has an inconsistent interface to other compress functions

### ISSUE THREAD

**Issue by wrouesnel** [golang/go#11026]
The interface for the compress/bzip2 subpackage is currently
```
func NewReader(r io.Reader) io.Reader
```
Note it does not return any error data - in fact you can't tell if it's going to read the file until you actually try to read. Contrast to the gzip subpackage:
```
func NewReader(r io.Reader) (*Reader, error)
```

It looks from the current state of things that its not been decided which direction the compression code wants to go with its interfaces, but IMHO favoring an early error return would be better.

**Comment by bradfitz** [comment]
Unfortunately the API is frozen per the Go 1.x compatibility promise: https://golang.org/doc/go1compat
