### ISSUE TITLE
cmd/go: add support to "go get" for private bitbucket repos

### ISSUE THREAD

**Issue by petri** [golang/go#11032]
... for the syntax suggested in "go help importpath" (no ".git" suffixing the url)

I've managed to make private repos work by appending ".git" to the url. However this complicates things since the filesystem install path will now include the ".git". Also, the import statements must then have it.

There are tons of questions about this issue (or private repos in general) all over stackoverflow etc. etc. and many answers or posts give confusing or old information that makes go hard to use for newcomers. The go packaging is hard enough to grasp for newcomers as it is; combine that with these private repo issues and the result is no doubt three times as difficult.

**Comment by jimdoescode** [comment]
It would be really great to have a way of distributing internal bitbucket dependencies.

**Comment by rsc** [comment]
What exactly do you think we should do? 

Why don't private bitbucket repos work already?

**Comment by bcmills** [comment]
#27344 is a duplicate but has more detail. Consolidating into that issue.
