### ISSUE TITLE
cmd/compile: compiler crash on valid code

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11040]
Test case:

package p

var s1, s2, s3, s4 string

func F() bool {
	return s1 == s2 && ((s3 == "x") != (s4 == "x") || s3 == s4)
}

This is valid code that should compile without error.  Building this with last weeks's sources, I get:

naddr [0xc20818cdc0]
.   ANDAND u(100) l(6) tc(1) bool
.   .   EQ u(2) l(6) tc(1) bool
.   .   .   LEN u(2) a(true) l(6) tc(1) int
.   .   .   .   NAME-p.s3 u(1) a(true) l(3) x(0+0) class(PEXTERN) tc(1) used(true) string
.   .   .   LITERAL-1 u(1) a(true) x(0+0) tc(1) int
.   .   CALLFUNC u(100) l(6) tc(1) bool
.   .   .   NAME-runtime.eqstring u(1) a(true) l(2) x(0+0) class(PFUNC) tc(1) used(true) FUNC-func(string, string) bool
.   .   CALLFUNC-list
.   .   .   AS u(1) l(6) tc(1)
.   .   .   .   INDREG-SP a(true) l(6) x(0+0) tc(1) string
.   .   .   .   NAME-p.s3 u(1) a(true) l(3) x(0+0) class(PEXTERN) tc(1) used(true) string

.   .   .   AS u(1) l(6) tc(1)
.   .   .   .   INDREG-SP a(true) l(6) x(16+0) tc(1) string
.   .   .   .   LITERAL-"x" u(1) a(true) l(6) tc(1) string
../../foo1.go:6: internal compiler error: naddr: bad && 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5c8057]

goroutine 1 [running]:
cmd/compile/internal/gc.hcrash()
	/home/iant/go/src/cmd/compile/internal/gc/subr.go:105 +0x57
cmd/compile/internal/gc.Fatal(0x844e90, 0x10, 0xc20808c460, 0x2, 0x2)
	/home/iant/go/src/cmd/compile/internal/gc/subr.go:198 +0x2b4
cmd/compile/internal/gc.Naddr(0xc2081a4010, 0xc20818cdc0)
	/home/iant/go/src/cmd/compile/internal/gc/gsubr.go:311 +0x1680
cmd/compile/internal/amd64.gins(0x3036, 0xc20818cdc0, 0xc20818da40, 0x40e4fe)
	/home/iant/go/src/cmd/compile/internal/amd64/gsubr.go:629 +0x12d
cmd/compile/internal/gc.bgenx(0xc208188a00, 0x0, 0xc208199901, 0x0, 0xc20819b6c0)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:2061 +0x18d3
cmd/compile/internal/gc.Bgen(0xc208188a00, 0xc20819bc01, 0x0, 0xc20819b6c0)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:1739 +0x4e
cmd/compile/internal/gc.bgenx(0xc2081888c0, 0xc208183a40, 0xc208199501, 0x0, 0x0)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:1889 +0xe07
cmd/compile/internal/gc.Bvgen(0xc2081888c0, 0xc208183a40, 0x1)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:1751 +0x77
cmd/compile/internal/gc.bgenx(0xc208199400, 0xc208183a40, 0x7e4d01, 0x0, 0x0)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:1890 +0xe35
cmd/compile/internal/gc.Bvgen(0xc208199400, 0xc208183a40, 0xc208018701)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:1751 +0x77
cmd/compile/internal/gc.cgen_wb(0xc208199400, 0xc208183a40, 0x100)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:372 +0x270b
cmd/compile/internal/gc.Cgen(0xc208199400, 0xc208183a40)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:19 +0x37
cmd/compile/internal/gc.cgen_wb(0xc208188640, 0xc208183a40, 0x0)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:309 +0x1746
cmd/compile/internal/gc.Cgen_as_wb(0xc208183a40, 0xc208188640, 0x0)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:959 +0x16c
cmd/compile/internal/gc.Cgen_as(0xc208183a40, 0xc208188640)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:910 +0x37
cmd/compile/internal/gc.gen(0xc20818e8c0)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:860 +0x18b
cmd/compile/internal/gc.Genlist(0xc208165a40)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:219 +0x37
cmd/compile/internal/gc.cgen_ret(0xc208188500)
	/home/iant/go/src/cmd/compile/internal/gc/cgen.go:2623 +0x3e
cmd/compile/internal/gc.gen(0xc208188500)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:884 +0xfac
cmd/compile/internal/gc.Genlist(0xc208165700)
	/home/iant/go/src/cmd/compile/internal/gc/gen.go:219 +0x37
cmd/compile/internal/gc.compile(0xc2081837c0)
	/home/iant/go/src/cmd/compile/internal/gc/pgen.go:463 +0xb57
cmd/compile/internal/gc.funccompile(0xc2081837c0)
	/home/iant/go/src/cmd/compile/internal/gc/dcl.go:1474 +0x1c0
cmd/compile/internal/gc.Main()
	/home/iant/go/src/cmd/compile/internal/gc/lex.go:468 +0x1e99
cmd/compile/internal/amd64.Main()
	/home/iant/go/src/cmd/compile/internal/amd64/galign.go:127 +0x590
main.main()
	/home/iant/go/src/cmd/compile/main.go:26 +0x18c

**Comment by josharian** [comment]
Dup of #10654?

**Comment by ianlancetaylor** [comment]
Almost certainly, thanks.
