### ISSUE TITLE
defer taking an expression instead of just a function call

### ISSUE THREAD

**Issue by Xe** [golang/go#11051]
It would be nice to be able to write code such as:

```go
defer foo <- true
```

instead of code such as

```go
defer func() {
    foo <- true
}()
```

Would it be too much of a breaking change to allow defer to process a statement instead of just a function call?

**Comment by bradfitz** [comment]
This would introduce a lot of complexity and ambiguity (thus requiring complexity to specify it), so I don't see this happening.

Let's move this discussion to the golang-nuts mailing list where it can be discussed further.
