### ISSUE TITLE
bash: /usr/local/go/bin/go: No such file or directory

### ISSUE THREAD

**Issue by gingi99** [golang/go#11056]
```
probe@server1:~$ uname -a
Linux server1 3.0.6 #2 SMP Mon Jun 17 14:35:19 JST 2013 armv7l GNU/Linux
```

I downloaded GO files of the armv7l
```
probe@server1:~$ ls | grep 1.4.
go1.4.2.linux-arm~armv7-1.tar.gz
```

```
probe@server1:~$ sudo tar -C /usr/local -xzf go1.4.2.linux-arm~armv7-1.tar.gz
```

```
probe@server1:~$ go
bash: /usr/local/go/bin/go: No such file or directory
```

I already set $PATH.
```
probe@server1:~$ which go
/usr/local/go/bin/go
```

I don't know why this happens.

**Comment by davecheney** [comment]
You probably want the -multiarch version of this tarball. See the note at the top if http://dave.cheney.net/unofficial-arm-tarballs

I have to close this issue as those tarballs are not prepared or supported by the go team. Thank you for your understanding.
