### ISSUE TITLE
time: don't print nil Location as "UTC"

### ISSUE THREAD

**Issue by 178inaba** [golang/go#11059]
Hi there
The first time I'll post.

http://play.golang.org/p/TAyGLFfUUa

time.LoadLocation() If an invalid value is passed on, it is displayed in fmt.Println() "UTC".
However, actually nil so panic occurs when you use the Location.
This behavior is
https://github.com/golang/go/blob/master/src/time/zoneinfo.go#L73
Due to that it returns the UTC above.

I think this behavior had better fix.
Location I think is that we should be printed as if nil "<nil>".
Or, I think Location came back is good if it is available as UTC.
In that case,
https://github.com/golang/go/blob/master/src/time/zoneinfo_unix.go#L89
I think I should I return the UTC above.

I think this sentence because English is not good I wrote in the google translation.
I'm sorry if there is an unknown sentence.

Thank you for reading to the last.
golang love! Fun!

**Comment by 178inaba** [comment]
Oops
I was wrong.
So you have changed to an error such as the current master "can not find undef in zip file zoneinfo.zip".
https://github.com/golang/go/blob/master/src/time/zoneinfo_read.go#L342
It seems to return the Error at the location of the above-mentioned URL.

**Comment by rsc** [comment]
No thanks. See discussion on CL 14176.
