### ISSUE TITLE
cmd/go: go install to current directory does not create executable

### ISSUE THREAD

**Issue by phemmer** [golang/go#11065]
With current master, when I perform `GOBIN="$(pwd)" go install`, no resulting binary is created. This seems to be a regression from go-1.4.2, specifically as a result of 227fb11.

I use `GOBIN="$(pwd)" go install` instead of `go build` as `go build` does not update the build cache (`$GOPATH/pkg`). Thus for development, and frequent builds, `go install` is much faster.

See also #9645

**Comment by robpike** [comment]
Almost certainly a consequence of the new removal logic in go build.
