### ISSUE TITLE
Fail to build from source on Ubuntu/Linux

### ISSUE THREAD

**Issue by halton** [golang/go#11061]
I'm following the page https://golang.org/doc/install/source to build master code (227fb11)go from source on my Ubuntu 15.04, but failed on all.bash step. If I checkout go1.4.1, everything is fine.

```
$ ./all.bash 
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /home/halton/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /home/halton/go1.4/bin/go: No such file or directory
```

**Comment by davecheney** [comment]
The website contains information for building the release version of Go, Go 1.4. 

Instructions for building the development version are here, http://tip.golang.org/doc/install/source. 

Please do no use github for support questions, rather, please direct additional questions to the mailing list, golang-nuts.
