### ISSUE TITLE
tour: possible bug

### ISSUE THREAD

**Issue by komuW** [golang/go#11063]
Context: /basics/6

Hi,
I think there's a bug in this line of code:

func swap(x, y string) string, string {
	return y, x
}

 command-line-arguments
/tmp/sandbox457775645/main.go:5: syntax error: unexpected comma, expecting semicolon or newline

I think it should be:

func swap(x, y string) (string, string) {
	return y, x
}

**Comment by davecheney** [comment]
http://tour.golang.org/basics/6 looks correct to me. Which version of the tour are you looking at ?

**Comment by komuW** [comment]
Hi,

It isn't a bug. I had made the changes myself and it seems like you are doing some heavy caching, since no matter how I refreshed, my changes were still showing up instead of fetching the correct implementation from you guys.

**Comment by minux** [comment]
Use the reset button if you want to reload the code.
