### ISSUE TITLE
os/exec: add boolean to tell whether exec is implemented on this platform

### ISSUE THREAD

**Issue by robpike** [golang/go#11077]
too many tests must now ask the "does this os have exec?" question it would be nice to put it in one place, and os/exec is the obvious one.

**Comment by bradfitz** [comment]
Seems like a low-level wart in a high-level package.

It's the `os` or `syscall` package that is actually unable to do this.

I know how you feel about adding anything to `syscall`, but syscall already has:

```go
const ImplementsGetwd = true
```

... so it would be consistent to put it there.

**Comment by crawshaw** [comment]
Note that Android can exec (though the platform generally discourages it). The problem there is that all Go binaries must be linked with a linker not available on the Android platform. You have to cross compile. The result is there is no useful go command on Android, which many tests use.

iOS cannot exec at all, the sandboxd disallows it.

So the set of tests excluded on Android is a subset of the tests excluded on iOS.

**Comment by robpike** [comment]
syscall is allowed to have changes that support the core, and this is one example. but other trains are in motion.

**Comment by josharian** [comment]
Fixed by CL 10753, I think.
