### ISSUE TITLE
doc: install/source points at old tag (1.4.1)

### ISSUE THREAD

**Issue by cespare** [golang/go#11072]
I feel like I saw this issue discussed somewhere already, but now I can't find an issue or golang-dev discussion. Apologies if this is a duplicate.

The instructions at https://golang.org/doc/install/source say

> Go will install to a directory named go. Change to the directory that will be its parent and make sure the go directory does not exist. Then clone the repository and check out the latest release tag:
> 
> ```
> $ git clone https://go.googlesource.com/go
> $ cd go
> $ git checkout go1.4.1
> ```

but of course this is out of date and should be 1.4.2.

It would be even better if this could be updated automatically for new releases, or at least if there were some list of all references to be updated.

**Comment by adg** [comment]
You saw it in #10419

**Comment by adg** [comment]
We're likely to overhaul the way we release the golang.org web site in the near future.

**Comment by cespare** [comment]
OK, thanks Andrew. Also I see that it's fixed in master; just not deployed yet.

(Must have tried half a dozen Github issue searches...)
