### ISSUE TITLE
build: codesign fails with strict validation error for darwin ARM binaries

### ISSUE THREAD

**Issue by rakyll** [golang/go#11075]
codesign can't sign darwin/arm and darwin/arm64 binaries anymore and failing with "main executable failed strict validation".

codesign was able to sign these binaries before c413c45e6db73909ac506cb385b49b6b2cd90726. Any idea what might have broken the validation?

/cc @rsc @josharian 

```
/usr/bin/codesign --force --sign 816DD34A8F786FB8A37691BD9766AD0502D94EFA --entitlements /Users/jbd/Library/Developer/Xcode/DerivedData/main-fozojkbnbvggtsdrnmwqvzhmxfff/Build/Intermediates/main.build/Debug-iphoneos/main.build/main.app.xcent /Users/jbd/Library/Developer/Xcode/DerivedData/main-fozojkbnbvggtsdrnmwqvzhmxfff/Build/Products/Debug-iphoneos/main.app

/Users/jbd/Library/Developer/Xcode/DerivedData/main-fozojkbnbvggtsdrnmwqvzhmxfff/Build/Products/Debug-iphoneos/main.app: main executable failed strict validation
Command /usr/bin/codesign failed with exit code 1
```

**Comment by josharian** [comment]
I just ran some tests on my device a few hours ago, so codesigning is still working for me. And I'm pretty puzzled as to have c413c45 could have changed anything relevant. Did you pick out that commit via git bisect? How are you doing codesigning--via go_arm_exec_darwin? Grasping at straws...

**Comment by rakyll** [comment]
I am codesigning via xcodebuild, you can checkout my boilerplate project from https://github.com/rakyll/go-xcode. The tip works fine with codesigning via go_arm_exec_darwin.

I haven't picked the commit by bisect, f4b48de3ad8d9f4f2495acc7cd7d54775b0d101f is the last commit I know I was able to codesign its binaries. I saw Russ working on Mach-O layout related CLs, one of them might be breaking the validation. I don't know why it passes via go_arm_exec_darwin.

**Comment by josharian** [comment]
That commit broke the build. Maybe a broken build manifests itself as a codesign failure in the Xcode setup.

There was also another recent commit that broke the darwin/arm64 builder. It should be fixed now, although build.golang.org hasn't confirmed that yet.

If you try with tip right now, or with the last known good darwin/arm64 commit (81d5810be959), is it still broken? If both are broken, would you mind doing the git bisect thing?

**Comment by adg** [comment]
Maybe I lacked context in renaming the title, but this issue should have an appropriate prefix ("build:"?) like all the other issues.

**Comment by rakyll** [comment]
The build ID information (7b87631e8c41b7919a3a3a845b61cb7c240efff9) breaks the validation.

**Comment by josharian** [comment]
Thanks. That makes a lot more sense. Did CL 10701 help at all? Does CL 10708 (along with its predecessors) help at all?

**Comment by rakyll** [comment]
CL/10709 is fixing the issue.

**Comment by josharian** [comment]
Awesome. Thanks for running it down.
