### ISSUE TITLE
log/syslog: should use ReportEvent api on Windows

### ISSUE THREAD

**Issue by jpoirier** [golang/go#1108]
<pre>What steps will reproduce the problem?
1. run &quot;make test&quot; from src/pkg/syslog

What is the expected output? What do you see instead?
The test should pass. The test fails.</pre>

**Comment by mattn** [comment]
https://go-review.googlesource.com/#/c/2953/

**Comment by bradfitz** [comment]
It was probably a mistake to include log/syslog in the standard library instead. Let's develop this elsewhere, instead. It doesn't need to live in the standard library.
