### ISSUE TITLE
crypto/elliptic: GenerateKey does not sample secret keys uniformly

### ISSUE THREAD

**Issue by ivokub** [golang/go#11082]
While sampling secret key from the random source, the GenerateKey method reads enough bytes from the randomness source, masks excessive bits, XORs first bit with 0x42, finds the integer representation of the bytes and then multiplies the base point by the corresponding integer.

However, during the scalar multiplication, the residue of that integer divided by the base point order is implicitly taken and used while doing scalar multiplication. As the base point order does not (usually) wholly divide the possible randomness space, then some secret keys are more probable than others.

As an example, if we use P-256 and the randomness source returns either `ffbdffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632552` or `0042000000000000000000000000000000000000000000000000000000000001` (both in hex-encoded form), the returned public keys are the same.
(The code for the example is at http://play.golang.org/p/iI3AGbLm1H)

I would recommend using the approach taken by Int method in the crypto/rand package.

**Comment by rsc** [comment]
Not sure how much this matters, but not going to happen for Go 1.6 either way.
