### ISSUE TITLE
crypto/tls: better error message for X509KeyPair

### ISSUE THREAD

**Issue by taylorhughes** [golang/go#11092]
1. *What did I do?*

    ```// mixed up order of key and cert:```
    ```http.ListenAndServeTLS(..., key, cert, ...)```

2. *What happened?*

  This resulted in the following cryptic error message:

    ```crypto/tls: failed to parse certificate PEM data```

3. *What did I expect?*

  I spent about an hour debugging various PEM format possibilities before finding the mixup.

  An error message explaining that the **type of PEM block was unexpected** would have saved me some time:

    ```crypto/tls: failed to parse certificate PEM data, expected type "CERTIFICATE", got "PRIVATE KEY"```

Related issue: https://github.com/golang/go/issues/7042

**Comment by adg** [comment]
It's more that the `CERTIFICATE` block wasn't found. Assigning to @agl
