### ISSUE TITLE
cmd/compile: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sokoow** [golang/go#11101]
Got this when compiling openshift on exynos5/arm with go version devel +5ee5528 Thu May 28 12:04:35 2015 +0000 linux/arm:

hack/build-go.sh 
++ Building go targets for linux/arm: cmd/openshift
# github.com/GoogleCloudPlatform/kubernetes/third_party/forked/reflect
naddr [0x10c85740]
.   OROR u(100) l(159) tc(1) bool
.   .   NAME-reflect.autotmp_0092 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) bool
.   .   EQ-init
.   .   .   VARKILL l(159) tc(1)
.   .   .   .   NAME-reflect.autotmp_0092 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) bool

.   .   .   AS u(100) l(159) tc(1)
.   .   .   .   NAME-reflect.autotmp_0093 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) int
.   .   .   .   CALLMETH u(100) l(159) tc(1) int
.   .   .   .   .   DOTMETH u(2) l(159) tc(1) FUNC-method(reflect.Value) func() int
.   .   .   .   .   .   NAME-reflect.Value.Len u(1) a(true) l(159) x(0+0) class(PFUNC) FUNC-method(reflect.Value) func() int
.   .   .   .   CALLMETH-list
.   .   .   .   .   AS u(1) l(159) tc(1)
.   .   .   .   .   .   INDREG-R13 a(true) l(159) x(4+0) tc(1) reflect.v·2 G0 reflect.Value
.   .   .   .   .   .   NAME-reflect.v1 u(1) a(true) g(3) l(103) x(4+0) class(PPARAM) f(1) esc(s) ld(1) tc(1) used(true) reflect.Value
.   .   EQ u(100) l(159) tc(1) bool
.   .   .   NAME-reflect.autotmp_0093 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) int
.   .   .   LITERAL-0 u(1) a(true) l(159) tc(1) int
Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/third_party/forked/reflect/deep_equal.go:159: internal compiler error: naddr: bad || 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1cc960]

goroutine 1 [running]:
cmd/compile/internal/gc.hcrash()
	/root/go/src/cmd/compile/internal/gc/subr.go:105 +0x60
cmd/compile/internal/gc.Fatal(0x3cb348, 0x10, 0x10cd78f0, 0x2, 0x2)
	/root/go/src/cmd/compile/internal/gc/subr.go:198 +0x258
cmd/compile/internal/gc.Naddr(0x10fbd0e8, 0x10c85740)
	/root/go/src/cmd/compile/internal/gc/gsubr.go:385 +0x1458
cmd/compile/internal/arm.gins(0x201d, 0x10c85740, 0x10c85e00, 0x0)
	/root/go/src/cmd/compile/internal/arm/gsubr.go:665 +0xe4
cmd/compile/internal/gc.bgenx(0x10c85ec0, 0x0, 0x1, 0x0, 0x10fb5b00)
	/root/go/src/cmd/compile/internal/gc/cgen.go:1872 +0x15cc
cmd/compile/internal/gc.Bgen(0x10c85ec0, 0x10fb5c00, 0x0, 0x10fb5b00)
	/root/go/src/cmd/compile/internal/gc/cgen.go:1739 +0x44
cmd/compile/internal/gc.gen(0x10c88000)
	/root/go/src/cmd/compile/internal/gc/gen.go:901 +0xc24
cmd/compile/internal/gc.Genlist(0x10ef84e0)
	/root/go/src/cmd/compile/internal/gc/gen.go:219 +0x38
cmd/compile/internal/gc.gen(0x10c83800)
	/root/go/src/cmd/compile/internal/gc/gen.go:901 +0x1178
cmd/compile/internal/gc.Genlist(0x10f08320)
	/root/go/src/cmd/compile/internal/gc/gen.go:219 +0x38
cmd/compile/internal/gc.compile(0x10c7ca80)
	/root/go/src/cmd/compile/internal/gc/pgen.go:463 +0xb48
cmd/compile/internal/gc.funccompile(0x10c7ca80)
	/root/go/src/cmd/compile/internal/gc/dcl.go:1475 +0x1e0
cmd/compile/internal/gc.Main()
	/root/go/src/cmd/compile/internal/gc/lex.go:221 +0x21bc
cmd/compile/internal/arm.Main()
	/root/go/src/cmd/compile/internal/arm/galign.go:92 +0x540
main.main()
	/root/go/src/cmd/compile/main.go:28 +0x100
# github.com/elazarl/go-bindata-assetfs
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: AssetFile.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:74: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
	*AssetFile does not implement os.FileInfo (missing Size method)
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: AssetDirectory.Size is ambiguous
Godeps/_workspace/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:114: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
	*AssetDirectory does not implement os.FileInfo (missing Size method)
make: *** [all] Error 1

IMO this shouldn't be blowing up like that ;) Hope somebody will find this report useful

**Comment by ALTree** [comment]
I think the first one is #10654

**Comment by adg** [comment]
Try updating to a newer version of Go.

**Comment by josharian** [comment]
@adg I think that these are crashes with the tip toolchain.

**Comment by adg** [comment]
The quoted revision is 5ee5528.

**Comment by josharian** [comment]
That's still recent enough that I'd like to confirm before closing. The first one is indeed a dup of #10654. @sokoow, can you check whether the second issue still occurs? Thanks.

**Comment by sokoow** [comment]
Still same with +b39487b

Detected go version: go version devel +b39487b Tue Jun 9 09:56:10 2015 +0000 linux/arm.

hack/build-go.sh 
++ Building go targets for linux/arm: cmd/openshift
# github.com/GoogleCloudPlatform/kubernetes/third_party/forked/reflect
naddr [0x10c72cc0]
.   OROR u(100) l(159) tc(1) bool
.   .   NAME-reflect.autotmp_0092 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) bool
.   .   EQ-init
.   .   .   VARKILL l(159) tc(1)
.   .   .   .   NAME-reflect.autotmp_0092 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) bool

.   .   .   AS u(100) l(159) tc(1)
.   .   .   .   NAME-reflect.autotmp_0093 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) int
.   .   .   .   CALLMETH u(100) l(159) tc(1) int
.   .   .   .   .   DOTMETH u(2) l(159) tc(1) FUNC-method(reflect.Value) func() int
.   .   .   .   .   .   NAME-reflect.Value.Len u(1) a(true) l(159) x(0+0) class(PFUNC) FUNC-method(reflect.Value) func() int
.   .   .   .   CALLMETH-list
.   .   .   .   .   AS u(1) l(159) tc(1)
.   .   .   .   .   .   INDREG-R13 a(true) l(159) x(4+0) tc(1) reflect.v·2 reflect.Value
.   .   .   .   .   .   NAME-reflect.v1 u(1) a(true) g(3) l(103) x(4+0) class(PPARAM) f(1) esc(s) tc(1) used(true) reflect.Value
.   .   EQ u(100) l(159) tc(1) bool
.   .   .   NAME-reflect.autotmp_0093 u(1) a(true) l(159) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) int
.   .   .   LITERAL-0 u(1) a(true) l(159) tc(1) int
Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/third_party/forked/reflect/deep_equal.go:159: internal compiler error: naddr: bad || 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1d3274]

**Comment by josharian** [comment]
Thanks, @sokoow. That crash is a dup of #10654, which has an outstanding CL for it. I've confirmed that the second compilation failure no longer occurs with tip.
