### ISSUE TITLE
tour: redirect for old-style /#NNN links

### ISSUE THREAD

**Issue by mikeyhill** [golang/go#11103]
Context: https://tour.golang.org/#1

Tour is blank in both FF and Chrome on osx.  All plugins disabled (had adblock, ghostery, flash-control).  Can't seem to view this tutorial.  Let me know if you need more info.

**Comment by dominikh** [comment]
Can confirm. JS error:

```
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://tour.golang.org1/' cannot be created in a document with origin 'https://tour.golang.org'. (script.js:507)
    at Error (native)
    at vc.f.url (https://tour.golang.org/script.js:477:28)
    at Ic.$get (https://tour.golang.org/script.js:506:6)
    at Object.d [as invoke] (https://tour.golang.org/script.js:473:127)
    at https://tour.golang.org/script.js:474:298
    at c (https://tour.golang.org/script.js:471:479)
    at Object.d [as invoke] (https://tour.golang.org/script.js:472:111)
    at https://tour.golang.org/script.js:474:298
    at c (https://tour.golang.org/script.js:471:479)
    at Object.d [as invoke] (https://tour.golang.org/script.js:472:111)
```

**Comment by minux** [comment]
where did you get such a link? it's out of date.

https://tour.golang.org works correctly.

**Comment by dominikh** [comment]
I think there should be backwards-compatibility for those links. They've been used and shared for years to point to specific slides of the tour.

I understand that the numbering of slides might've changed, but then it should at least fall back gracefully, not break outright.

**Comment by mikeyhill** [comment]
https://www.bento.io/go

**Comment by adg** [comment]
@campoy we could pretty easily set up a map of old # fragments to their modern equivalents (or close enough). A blank page is bad, at least.
