### ISSUE TITLE
x/mobile/cmd/gomobile - init - GOROOT not writable, but writable

### ISSUE THREAD

**Issue by EtienneBruines** [golang/go#11125]
Running `gomobile init -v`:
```
building gomobile toolexec
gomobile: Cannot install android/arm in GOROOT.
Make GOROOT writable (possibly by becoming the super user, using sudo) and run:
	mv /home/etiennebruines/tmp/gomobile-690904600/android_arm /usr/local/src/go/pkg
```

Issuing this command [does not help](https://github.com/golang/go/issues/9854#issuecomment-110317204), but the problem I would like to address here, is:
**The target directory is writable, but the Gomobile tool does not agree.**

```
# ls -l /usr/local/src/go | grep pkg
drwxr-sr-x  8 root staff  4096 Jun  9 12:51 pkg
```

My assumption says that this is strongly related to #11124

**Comment by crawshaw** [comment]
Judging from the output of your ls, your GOROOT is only writable by root, and assuming you are running gomobile init as someone other than root, it means GOROOT is not writable.

The error has changed significantly int the current version of gomobile, as now the only time it writes to the GOROOT is with go install std, so the error you get now is from the Go tool. But ultimately you will need your GOROOT to be writable by gomobile init.
