### ISSUE TITLE
x/mobile/cmd/gomobile - init - Toolexec » Rename fails

### ISSUE THREAD

**Issue by EtienneBruines** [golang/go#11124]
I'm issuing the command `gomobile init -v`, and its response ends with:

```
Installed Go for android/arm in /home/etiennebruines/workspaces/go/pkg/gomobile/work-542832590/go
Installed commands in /home/etiennebruines/workspaces/go/pkg/gomobile/work-542832590/go/bin
building gomobile toolexec
gomobile: rename /home/etiennebruines/workspaces/go-all/pkg/gomobile/work-542832590/go/pkg/android_arm /tmp/gomobile-764944597/android_arm: invalid cross-device link
```

It's not weird for a `rename` command to fail with that error. Usually this means that the `src` and `dst` are not on the same file system (see [Stackoverflow](http://stackoverflow.com/a/24210631/3243814)). But for those that have a lot of file systems (one for root, one for `/home`, `/tmp` as tmpfs, ...), this shouldn't prevent it from initializing. 

I think the gomobile-tool should fallback to "copy to dst and delete src". I have not found a workaround just yet. 

The alternative would be to actually document this limitation and refer to the use of the `TMPDIR` environment variable (as some distributions might use `TEMP`, `TMP` or `TEMPDIR` ([Wikipedia](https://en.wikipedia.org/wiki/TMPDIR))) - but this only holds as long as we're using the [move](https://github.com/golang/mobile/blob/master/cmd/gomobile/init.go#L309-L328) function to copy to `/tmp`. 

Falling back to (potentially existing) tools such as `mv` may work on quite a lot of systems -- potentially not all, but probably all systems that are actually using the gomobile tool.

**Comment by hyangah** [comment]
fyi. crawshaw recently moved the use of toolexec and changed the way to initialize tool chains. There are still cases the move function is being used for but in most cases, I think we tried to be careful to put the src and dst under the same file system, but I may be wrong. @EtienneBruines, can you please sync the repo and run gomobile init to check if the problem went away? Many thanks.

**Comment by crawshaw** [comment]
As @hyangah wrote above, I believe this is now fixed. Please reopen the issue if it's not.
