### ISSUE TITLE
tour: nil slices, what is and isn't

### ISSUE THREAD

**Issue by objoekenobi** [golang/go#11120]
Context: /moretypes/10

package main

import "fmt"

func main() {
	var z []int
	var x []int = make([]int, 0, 0)
	
	fmt.Println(z, len(z), cap(z))
	fmt.Println(x, len(x), cap(x))
	
	if z == nil {
		fmt.Println("nil!")
	}
	if x == nil {
		fmt.Println("nil!")
	}
}

**Comment by ianlancetaylor** [comment]
I don't understand--are you reporting a bug?  If so, can you describe in more detail what you expect to happen?

If you are asking a question, please use the golang-nuts mailing list.  Thanks.

**Comment by objoekenobi** [comment]
The language behaves this way.  Didn't think to test that.
Thank you.
