### ISSUE TITLE
fmt: `%v` verb does not print nil values for maps or slices

### ISSUE THREAD

**Issue by jhftrifork** [golang/go#11139]
## Steps to reproduce

    package main
    import "fmt"
    func main() {
	    var not_inited map[string]string = nil
	    var inited     map[string]string = make(map[string]string)

	    fmt.Printf("not_inited = %v\n", not_inited)
	    fmt.Printf("inited = %v\n", inited)
    }

## Expected behavior

    $ go run foo.go
    not_inited = <nil>
    inited = map[]

## Actual behavior

    $ go run foo.go
    not_inited = map[]
    inited = map[]

## Notes

The `nil` value inhabits pointer types, function types, interface types, channel types, map types, and slice types. For all of these types, the `%v` verb should distinguish the `nil` value from all other values of the type.

Here is a larger program showing the inconsistent behavior of `%v`:

    package main
    import "fmt"
    func main() {
	    var pointer_not_inited    *string            = nil
	    var pointer_inited        *string            = (func(s string) *string { return &s; })("foo")

	    var func_not_inited       func(string)string = nil
	    var func_inited           func(string)string = func(s string) string { return s; }

	    var interface_not_inited  interface{}        = nil
	    var interface_inited      interface{}        = "foo"

	    var channel_not_inited    chan string        = nil
	    var channel_inited        chan string        = make(chan string)

	    var map_not_inited        map[string]string  = nil
	    var map_inited            map[string]string  = make(map[string]string)

	    var slice_not_inited      []string           = nil
	    var slice_inited          []string           = make([]string, 0)

	    fmt.Printf("pointer_not_inited = %v\n", pointer_not_inited)
	    fmt.Printf("pointer_inited = %v\n", pointer_inited)

	    fmt.Printf("func_not_inited = %v\n", func_not_inited)
	    fmt.Printf("func_inited = %v\n", func_inited)

	    fmt.Printf("interface_not_inited = %v\n", interface_not_inited)
	    fmt.Printf("interface_inited = %v\n", interface_inited)

	    fmt.Printf("channel_not_inited = %v\n", channel_not_inited)
	    fmt.Printf("channel_inited = %v\n", channel_inited)

	    fmt.Printf("slice_not_inited = %v\n", slice_not_inited)
	    fmt.Printf("slice_inited = %v\n", slice_inited)

	    fmt.Printf("map_not_inited = %v\n", map_not_inited)
	    fmt.Printf("map_inited = %v\n", map_inited)
    }

**Comment by cznic** [comment]
- This cannot be changed due to the Go 1 compatibility promise.
- It's possible to get the desired distinction using '%#v': http://play.golang.org/p/AIFc50tUO7

**Comment by jhftrifork** [comment]
I just looked; the `%#v` verb is better. I'll stop using `%v` from now on then.

The issue I mentioned is serious: it cost me a lot of time debugging due to my (sensible) assumption that a value was not `nil` when in fact it was. If `%v` cannot be changed, I would suggest that the documentation mark `%v` as deprecated and encourage the use of `%#v`.

**Comment by ianlancetaylor** [comment]
I'm not sure whether we can make this change or not.  Sending to Rob to decide.

**Comment by robpike** [comment]
Working as intended, with an easy workaround (%#v). Shouldn't change behavior like this.
