### ISSUE TITLE
os: on Plan 9: stat mycmd: stat buffer too short

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11132]
When I ran a version of http://golang.org/cl/10809 on the plan9 trybot, it failed with

--- FAIL: TestGoInstallCleansUpAfterGoBuild (0.61s)
	go_test.go:171: running testgo [build]
	go_test.go:171: running testgo [install]
	go_test.go:484: testgo install did not remove command binary error: stat mycmd: stat buffer too short

This is from https://storage.googleapis.com/go-build-log/0ec7ceac/plan9-386_37213075.log , though I'm not sure how long that will stick around.

The code that causes this error is simply

		if _, err := os.Stat(file); err == nil {
			t.Fatal(msg)
		} else if !os.IsNotExist(err) {
			t.Fatal(msg, "error:", err)
		}

os.Stat is returning an error that is not nil, and not IsNotExist(err), but is intead the relatively meaningless error "stat buffer too short".

I am going to modify the test to avoid the error.  Recording this issue so that the problem can be fixed.

**Comment by bradfitz** [comment]
> This is from https://storage.googleapis.com/go-build-log/0ec7ceac/plan9-386_37213075.log , though I'm not sure how long that will stick around.

Forever. It's in _storage_ (Cloud storage!) and storage is cheap. The temporary URLs now have _temporary_ in their name. They're in-process only because they stream live output. But I've filed #11141 for a better fix.

**Comment by 0intro** [comment]
Thanks for reporting. Maybe that's related to issue #10911,
were the TestRemoveAllRace started to return this error
intermittently on the old builder around May 13.
I'll investigate further.
