### ISSUE TITLE
os: RemoveAll does not work on Windows when there are filename case collisions

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11135]
The test TestCaseCollisions in cmd/go/go_test.go in http://golang.org/cl/10809 fails on Windows.  A call to os.RemoveAll of a directory fails with

remove C:\Users\WINGOP~1\AppData\Local\Temp\gotest203717703\src\example: The directory is not empty.

This directory holds subdirectories whose names are the same except for case: pkg and Pkg.

I will skip the test on Windows, but to recreate the problem, it should work to simply remove the skip.

**Comment by alexbrainman** [comment]
Skip the test. I will investigate what is going on.

FYI. You cannot remove executable file if it is still executing.

Alex

**Comment by alexbrainman** [comment]
I think it is a bug in http://golang.org/cl/10809. I commented there.

Alex

**Comment by ianlancetaylor** [comment]
Argh, thanks.
