### ISSUE TITLE
image/gif: Encode does not preserve Bounds.Min

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11149]
The following program fails:
```go
package main

import (
	"bytes"
	"fmt"
	"image/gif"
	"reflect"
)

func main() {
	data := []byte("GIF89a\n\x0000000,\x00\x000\x00\n\x00\n\x00\x80000000\x02\b\xf01u\xb9\xfdal\x05\x00;")
	img, err := gif.Decode(bytes.NewReader(data))
	if err != nil {
		panic(err)
	}
	var w bytes.Buffer
	err = gif.Encode(&w, img, nil)
	if err != nil {
		panic(err)
	}
	img1, err := gif.Decode(&w)
	if err != nil {
		panic(err)
	}
	if !reflect.DeepEqual(img.Bounds(), img1.Bounds()) {
		fmt.Printf("img0: %#v\n", img.Bounds())
		fmt.Printf("img1: %#v\n", img1.Bounds())
		panic("bounds changed")
	}
}
```
```
img0: image.Rectangle{Min:image.Point{X:0, Y:48}, Max:image.Point{X:10, Y:58}}
img1: image.Rectangle{Min:image.Point{X:0, Y:0}, Max:image.Point{X:10, Y:10}}
panic: bounds changed
```

Bounds.Min should be preserved by Encode.

go version devel +b0532a9 Mon Jun 8 05:13:15 2015 +0000 linux/amd64

**Comment by jeffallen** [comment]
Works as designed:

	// When calling Encode instead of EncodeAll, the single-frame image is
	// translated such that its top-left corner is (0, 0), so that the single
	// frame completely fills the overall GIF's bounds.

This test of a round trip through DecodeAll/EncodeAll passes:

func TestRoundtrip(t *testing.T) {
	data := []byte("GIF89a\n\x0000000,\x00\x000\x00\n\x00\n\x00\x80000000\x02\b\xf01u\xb9\xfdal\x05\x00;")
	gif, err := DecodeAll(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	var w bytes.Buffer
	err = EncodeAll(&w, gif)
	if err != nil {
		t.Fatal(err)
	}
	gif1, err := DecodeAll(&w)
	if err != nil {
		t.Fatal(err)
	}
	if len(gif.Image) != len(gif1.Image) {
		t.Fatal("wrong number of images")
	}

	if !reflect.DeepEqual(gif.Image[0].Bounds(), gif1.Image[0].Bounds()) {
		t.Fatal("bounds changed: %v -> %v", gif.Image[0].Bounds(), gif1.Image[0].Bounds())
	}
}
