### ISSUE TITLE
runtime: TestGoroutineParallelism regularly deadlocks on openbsd/arm builder

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#11143]
The TestGoroutineParallelism test regularly seems to deadlock on the openbsd/arm builder. While I'm willing for this to be shown to be due to a bug in the openbsd/arm port, I suspect that it is simply due to the port and hardware being slow and single CPU, especially given the comment:

        // If runtime triggers a forced GC during this test then it will deadlock,
        // since the goroutines can't be stopped/preempted. 

##### GOMAXPROCS=2 runtime -cpu=1,2,4
SIGQUIT: quit
PC=0x764a8

goroutine 0 [idle]:
runtime.thrsleep(0x10e06944, 0x3, 0x0, 0x0, 0x10e06944, 0x301038, 0x1, 0x1, 0x4aa01, 0x1, ...)
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/runtime/sys_openbsd_arm.s:303 +0x28

goroutine 1 [chan receive]:
testing.RunTests(0x25d918, 0x2ff5c8, 0x8e, 0x8e, 0x1)
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/testing/testing.go:564 +0x768
testing.(*M).Run(0x10d9cf7c, 0x12280)
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/testing/testing.go:493 +0x6c
main.main()
	runtime/_test/_testmain.go:864 +0x118

goroutine 82678 [chan receive]:
runtime_test.TestGoroutineParallelism(0x10d74240)
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/runtime/proc_test.go:126 +0x1bc
testing.tRunner(0x10d74240, 0x2ffa84)
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/testing/testing.go:455 +0xa8
created by testing.RunTests
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/testing/testing.go:563 +0x73c

goroutine 82679 [running]:
	goroutine running on other thread; stack unavailable
created by runtime_test.TestGoroutineParallelism
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/runtime/proc_test.go:123 +0x170

goroutine 82681 [running]:
	goroutine running on other thread; stack unavailable
created by runtime_test.TestGoroutineParallelism
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/runtime/proc_test.go:123 +0x170

goroutine 82680 [running]:
	goroutine running on other thread; stack unavailable
created by runtime_test.TestGoroutineParallelism
	/home/gopher/build/openbsd-arm-ab08f79af3d4/go/src/runtime/proc_test.go:123 +0x170

trap    0x0
error   0x0
oldmask 0x0
r0      0x4
r1      0x3
r2      0x0
r3      0x0
r4      0x10e06944
r5      0x1055d400
r6      0x0
r7      0x8e9
r8      0x10e06780
r9      0x0
r10     0x13338a80
fp      0x30104c
ip      0x5e
sp      0x10e03ed8
lr      0x39ae4
pc      0x764a8
cpsr    0x10
fault   0x0
*** Test killed with quit: ran too long (31m0s).
FAIL	runtime	1860.566s

**Comment by minux** [comment]
Could we reproduce the deadlock on AMD64 with processor affinity in place
to limit the test in one core only?

Then we can skip the test on single processor systems.
