### ISSUE TITLE
Function call with extra comma after last parameter should report syntax error.

### ISSUE THREAD

**Issue by mdimec4** [golang/go#11140]
1.)  go version
 go version go1.3.1 linux/amd64

2.) What did I do?
 To demonstrate, I have made example with syntax error in call to "add", bay placing extra comma after last parameter.
http://play.golang.org/p/eEBt9k07Yd

3.) What did I expect?
 I expected to see some sort of syntax error and failure to compile.

4.) What did I saw instead?
Example compiles and runs. Gives the correct result.

**Comment by bradfitz** [comment]
This is intentional. Let's move this discussion to the mailing list.

**Comment by minux** [comment]
Yeah, I think it is to make generating code easy: you can always write a
comma after an argument.

Anyway, we can change it right now due to Go 1 compatibility guarantee.

**Comment by mdimec4** [comment]
I know it is not a major issue, but I figured I should let you guys know what I have discovered.
Especialy because I belive this falls under the category of unspecified behaiviour, which is not coverd by Go 1 compatibility guarantee.

**Comment by griesemer** [comment]
This is very much specified behavior:

http://tip.golang.org/ref/spec#Function_types

Note the optional comma in Parameters:

```
Parameters     = "(" [ ParameterList [ "," ] ] ")" .
```

The same is true for entries in composite literals, etc. It's a pain to have to think about adding/removing trailing comma's on multi-line parameter lists or composite literals, and this is the obvious syntactic solution.

**Comment by mdimec4** [comment]
I see. Solution makes perfect sense.
Thank you.
