### ISSUE TITLE
x/sys/windows: FormatMessage can't accept a DLL handle on 64-bit systems

### ISSUE THREAD

**Issue by alanctgardner** [golang/go#11147]
1. What version of Go are you using (go version)?
go1.3.3 windows/amd64

2. What operating system and processor architecture are you using?
Windows x86-64

3. What did you do?
Try to call syscall.FormatMessage with a DLL handle.

```
var flags uint32 = syscall.FORMAT_MESSAGE_ARGUMENT_ARRAY | syscall.FORMAT_MESSAGE_IGNORE_INSERTS | syscall.FORMAT_MESSAGE_FROM_HMODULE
libpdhDll := syscall.MustLoadDLL("pdh.dll")
buffer := make([]uint16, 300)

// Have to cast Handle, which is a uintptr, to a uint32 due to the signature of FormatMessage
syscall.FormatMessage(flags, uint32(libpdhDll.Handle), <some error number>, 0, buffer, nil)
``` 

4. What did you expect to see?
FormatMessage should accept a syscall.Handle or a uintptr so the cast to uint32 doesn't have to happen.

5.What did you see instead?
FormatMessage returns an error because the truncated pointer doesn't point to a DLL.

**Comment by bradfitz** [comment]
Go 1.3.3 is old and unsupported. Please try with Go 1.4.2 or ideally Go tip and report back.

**Comment by alanctgardner** [comment]
The same issue clearly exists in master: https://github.com/golang/sys/blob/master/windows/zsyscall_windows.go#L476
https://github.com/golang/go/blob/f9ed2f75c43cb8745a1593ec3e4208c46419216a/src/syscall/zsyscall_windows.go#L243

**Comment by minux** [comment]
The syscall package is frozen, but we can fix the problem in
x/sys/windows sub-repo instead.

**Comment by alexbrainman** [comment]
My mistake. I am 386 person.

Any suggestion on what to do about syscall.FormatMessage are welcome. I cannot see what we could do besides documenting the bug.

Alex

**Comment by alexbrainman** [comment]
@alanctgardner here https://go-review.googlesource.com/11165 is the change. Will that work for you?

Alex

**Comment by alanctgardner** [comment]
Looks good @alexbrainman, thanks for the fix!
