### ISSUE TITLE
crypto/cipher can't reuse BlockMode by NewCBCDecrypter()

### ISSUE THREAD

**Issue by Terry-Mao** [golang/go#11159]
code:
http://play.golang.org/p/oZ5OwdRYLV

After cbcDecrypter.CryptBlocks, the x.iv is changed. so reuse BlockMode got a wrong decrypt text.
i saw the source code has a exported method : SetIV, but cbcEncrypter is not exported.

this means everytime i must new a cbcDecrypter object.

**Comment by alphaqiu** [comment]
http://play.golang.org/p/ORTgk0mY4j

**Comment by Terry-Mao** [comment]
@alphaqiu thks, this can fix the issue, but as a std library, this seems not so nice..

**Comment by bradfitz** [comment]
Is there a documentation problem?

**Comment by Terry-Mao** [comment]
@bradfitz 
 document don't tell us cbc blockmode must rest(SetIV), after CryptBlocks

**Comment by minux** [comment]
As already mentioned, you don't need to crypto/cipher.cbcDecrypter
to be exported. You just need to type assert the blockmode to
interface{ SetIV([]byte) }.

If you just want to reuse cbcDecrypter, then there is another solution.
Just decrypt new IV as ciphertext, and the IV will be set to the IV you
want.

**Comment by minux** [comment]
Isn't that inherent in the documentation for
crypto/cipher.BlockMode?

“A BlockMode represents a block cipher running
in a block-based mode (CBC, ECB etc).”

Different Key/IV pair correspond to different
BlockMode.

**Comment by Terry-Mao** [comment]
@minux thks, fixed
