### ISSUE TITLE
x/sys/windows/svc/mgr: TestOpenLanManServer fails

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11156]
From our builder http://build.golang.org/log/b777dbdb4f736aafe2eacbccee3c499bf7729625

--- FAIL: TestOpenLanManServer-2 (0.00s)
	mgr_test.go:23: SCM connection failed: Access is denied.
FAIL
FAIL	golang.org/x/sys/windows/svc/mgr	0.043s

I don't know what the problem is.

Alex

**Comment by alexbrainman** [comment]
@bradfitz

**Comment by bradfitz** [comment]
I don't know either. I am not a Windows person.

Make that test t.Skip if it can't get access?
Add more logging about why it doesn't have access?

**Comment by alexbrainman** [comment]
"Access is denied" means the user who executes the syscall is not authorized for that operation. Who is the user? Is he an Administrator? Is he a member of Admin group?

It would be helpful, if I can debug this. Do you have a disk image that I can spin up on GCE or some other way?

I will disable the test if nothing else. I suspect I'll have to disable all tests in that package too.

Alex

**Comment by alexbrainman** [comment]
We cannot try-bot x/sys. Can we?

Alex

**Comment by bradfitz** [comment]
You can't share disk images on GCE (I don't think? or maybe not yet?), so you'll have to recreate your own or infer the environment from the description: https://github.com/golang/build/tree/master/env/windows  I followed those instructions exactly.

You could add more logging to your failure message to say who the user is and what groups the user is in.

Trybots would work now but they're not wired up. That would actually be easy now. We should do that. (/cc @adg)
