### ISSUE TITLE
cmd/go: TestOpenLanManServer now runs as TestOpenLanManServer-2

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11157]
From our builder http://build.golang.org/log/b777dbdb4f736aafe2eacbccee3c499bf7729625

--- FAIL: TestOpenLanManServer-2 (0.00s)
	mgr_test.go:23: SCM connection failed: Access is denied.
FAIL
FAIL	golang.org/x/sys/windows/svc/mgr	0.043s

(reported as issue #11156)

Test that used to run as TestOpenLanManServer now is running as TestOpenLanManServer-2. Perhaps this is the reason for test failure (maybe not). Is that intentional change with our tests? Is that something we need to document somewhere? Perhaps something else to do here.

Alex

**Comment by bradfitz** [comment]
That's because GOMAXPROCS now equals NumCPU by default, not 1.

**Comment by alexbrainman** [comment]
I know that. I just wander how many people's tests will get broken. And if we can do anything about it.

Alex

**Comment by alexbrainman** [comment]
@bradfitz build bots are nice. I enjoyed watching @ianlancetaylor writing new test with their help yesterday. Thank you and @adg.

Alex

**Comment by alexbrainman** [comment]
Dup of #11200.
