### ISSUE TITLE
inferred type math performed before a deduced type change?

### ISSUE THREAD

**Issue by crmackay** [golang/go#11158]
using: go1.4.2 darwin/amd64

here is what I did:

```go

a := 0.5

a *= 2/3
```

and I got: `a = 0` where I expected to get `0.333333333..` or a `type mismatch` error.

This seems to also happen if you use:
` a = 2/3*a`

Here is a [go.play](http://play.golang.org/p/MXDYcRhl_U) for more examples

Thanks to some unit testing, I stumbled upon this, and to me at least it seems like an inference typing bug.

With this behavior, when using numbers of implied types in an equation, the results can be unexpected, and troublesome (at least for me).

Presumably go is inferring that 2 and 3 are `int`'s and doing integer math, and then realizing that `a` is a `float64` and doing something like `float64(2/3)`. I would have instead expected that it would convert everything to `float64` before doing any calculations: `float64(2)/float64(3)*a` or give a `type mismatch` error

The fact that it deduces and changes the type based on context makes sense. What *does not* make sense to me is that it does operations with the original inferred type, and then proceeds to change the type while preserving the result from the already completed operation.

So perhaps convert all elements of an equation to the same type before completing any operations, or just raise a type error and make the programmer be explicit.

**Comment by bradfitz** [comment]
Please move this to the golang-nuts mailing list. We only use the issue tracker for concrete bugs.
