### ISSUE TITLE
spec: wrong statement about numeric operators

### ISSUE THREAD

**Issue by robzan8** [golang/go#11166]
The spec says:
_Arithmetic operators apply to numeric values and yield a result of the **same type as the first operand**._

This seems to be in contrast with other rules that hold and don't depend on the operands' order, namely:
_if the operands of a binary operation are different kinds of untyped constants, the operation and, for non-boolean operations, the result use the kind that appears later in this list: integer, rune, floating-point, complex. For example, an untyped integer constant divided by an untyped complex constant yields an untyped complex constant._
and
_Except for shift operations, if one operand is an untyped constant and the other operand is not, the constant is converted to the type of the other operand._

For a concrete example, see http://play.golang.org/p/CrwpUYEQvo

**Comment by griesemer** [comment]
Note that this talks about "untyped" constants - they have no actual Go type (for instance, a 100 digit integer constant is an integer constant but there's no actual Go type of which it would be a member). That is, there's no rule here conflicting with typed operands because untyped constants are not typed.

There are TODOs to clarify/simplify the explanations around untyped constants and how they are involved with expressions, but as is it's not wrong.

**Comment by robzan8** [comment]
Still, if we are talking about typed values, it's required that both variables are of the same type (you get a compile time error otherwise). Nowhere else in the spec I could find something indicating that the first operand determines the type more than the second operand. If not technically wrong, the statement in question is still misleading.
(or am I missing something?)

**Comment by minux** [comment]
I think you missed the shift operations.

**Comment by robzan8** [comment]
Yeah, the shift operators have their own rule, but saying _arithmetic operators yield a result of the same type as the first operand_ (without talking specifically about shift) doesn't seem to make sense at all.

**Comment by robzan8** [comment]
Or come up with an example where the the first operand is more important than the second in determining the type of the result, I can't see that (could be a limitation of mine :)

**Comment by griesemer** [comment]
@robzan8: @minux is correct - the wording was chosen such that shift operators fit in neatly. Note that (untyped constants aside), operands of arithmetic operators must be of the same type - with the notable exception of shifts. The wording is fine.

There's always different ways to phrase this, and we are not claiming this is the best way. But as is it's correct.

Here's your example:
```
var x int
var s uint
...
result := x << s
...
```
The type of result is the type of x, not the type of s. That is, the type of the left operand is the one that's relevant.

Please drop further discussion of this here. If you have a better suggestion that doesn't conflict elsewhere in the spec, please send a change. Thanks.

**Comment by robzan8** [comment]
Oh I see that. The type of the operands must always be the same, except for shift, in which case it's determined by the first, so let's say it's always determined by the first. You can see why it can be misinterpreted, right? I'd say:
*Arithmetic operators apply to numeric values of the same type.*
Then add a few words for the shift operator. Anyway your call. And sorry if I posted back here, I'm not familiar with the procedure for sending changes :)

**Comment by griesemer** [comment]
http://tip.golang.org/ref/spec#Operators:

"For other binary operators, the operand types must be identical unless the operation involves shifts or untyped constants."

This applies to all operators, including arithmetic operators. The spec does not repeat everything all over the place just as a reminder.
