### ISSUE TITLE
cmd/go: argument "-tags" doesn't trigger rebuild even if tags are different from last build

### ISSUE THREAD

**Issue by hydroflame** [golang/go#11165]
So if you setup a project that has some file that use `-tags`
 argument. reinstalling/building will not trigger a rebuild of the library even if the `-tags` provided are different from the last build
to reproduce:
define 2 files in a package, each one with a function that returns a different value
eg.
```
// +build alice

package thebug
func Bob()bool {return true}
```
```
// +build !alice

package thebug
func Bob()bool {return false}
```
then make some simple main that simply calls this function and prints the result
then compile the library
`$ go install thebug`//should build with the `!alice` version  
`$ go run main.go    `
`false    `
`$ go install -tags alice thebug    `
`$ go run main.go      `
`false`
notice that `thebug` was not recompiled (because no files changed) the only workaround i found was to build using the `-a` flag but that's a pain when the library you're compiling import many other library.

**Comment by adg** [comment]
I think the work that @rsc is doing with content-addressable build objects will solve this issue.

**Comment by bradfitz** [comment]
This bug report doesn't include which version of Go that @hydroflame was using.

This might've already been fixed in 119daba94e225 or 7b87631e8c41b on April 20th.

**Comment by hydroflame** [comment]
`MacbookMainframe:vrep hydroflame$ go version`
`go version go1.4.2 darwin/amd64`

**Comment by adg** [comment]
Seems likely that it is fixed. Closing the issue until someone reports otherwise.

**Comment by minux** [comment]
Have you tried Go 1.5 (tip)? I think the issue has been fixed.

**Comment by oconnor663** [comment]
I just ran into this building on Debian (go1.3.3). This bug can even affect build machines that try to use a clean GOPATH, if they use `go get` to assemble it, because `go get` implicitly runs a build with no tags. I think this is severe enough that the documentation for `-tags` needs a warning about using it without `-a`.
