### ISSUE TITLE
net/internal/dns: new package

### ISSUE THREAD

**Issue by mikioh** [golang/go#11160]
There are issues related to DNS message handling in the net package. Probably having a separate package would make sense because it would be used not only for bug fixes but adding new features such as DNSSEC+EDNS0, mDNS.
- #6464
- #8516
- #9391
- #10552 (partly)
- #10622
- #10631

**Comment by bradfitz** [comment]
I agree that a new package would probably clean up the net package. I'm not sure I agree about mDNS at least, though.

**Comment by mikioh** [comment]
Merged into #16218.
