### ISSUE TITLE
'%#v' verb does not print adequate dynamic type information for numerics

### ISSUE THREAD

**Issue by jhftrifork** [golang/go#11163]
## Steps to reproduce

    package main

    import "fmt"

    func main() {
	    n1 := float32(1.3167616e+07)
	    fmt.Printf("%#v\n", n1)
    }

## Expected output

    float32(1.3167616e+07)

## Actual output

    1.3167616e+07

## Notes

An important property implied by the documentation for `%#v` is that I can copy-paste the output into a Go program to recreate that value (at least for serializable values, e.g. not functions). At least, the function should be injective.

This is not true for numerics, since the output drops the dynamic type information. When I take the actual output above and put it in a new Go program, it gets assigned a different dynamic type:

    package main

    import "fmt"
    import "reflect"

    func main() {
	    n := 1.3167616e+07  // the output of `%#v`
	    fmt.Printf("%s\n", reflect.TypeOf(n).String())
    }

which prints:

    float64

This has cost me significant debugging time. The `%#v` verb should print out everything about the value that I need to know.

**Comment by bradfitz** [comment]
You might be right, but regardless this isn't something we can change at this point. The Go 1 compatibility promise means we can't change the behavior of people's programs.

**Comment by jhftrifork** [comment]
:-(

**Comment by bradfitz** [comment]
You can use `fmt.Sprintf("%T(%v)", v, v)`
