### ISSUE TITLE
regexp: QuoteMeta does not return regexp that matches input

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11173]
The following program crashes with the panic:
```go
package main

import "regexp"

func main() {
	regexp.MustCompile(regexp.QuoteMeta("\xfe"))
}
```
```
panic: regexp: Compile("\xfe"): error parsing regexp: invalid UTF-8: `�`
```

Documentation claims that "the returned string is a regular expression matching the literal text".

go version devel +b0532a9 Mon Jun 8 05:13:15 2015 +0000 linux/amd64

**Comment by bradfitz** [comment]
Package regexp only works on UTF-8. The package docs say "All characters are UTF-8-encoded code points."
