### ISSUE TITLE
regexp: considers "\Q\E*" as valid regexp

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11187]
Regexp package successfully compiles "\Q\E*", while re2 says:
re2/re2.cc:202: Error parsing '\Q\E*': no argument for repetition operator: *

Who is right here? What is the reason for difference?

go version devel +b0532a9 Mon Jun 8 05:13:15 2015 +0000 linux/amd64

**Comment by dvyukov** [comment]
Similar case is "\\Q\\E{2}"

**Comment by rsc** [comment]
Perl and RE2 both reject `\Q\E*`, so I suppose Go should too, although I don't see how it is really different from `(?:)*`.

**Comment by rsc** [comment]
Now I see it. (?:) is a group.
