### ISSUE TITLE
net: Expose net.internetAddrList, net.lookupIPDeadline publicly

### ISSUE THREAD

**Issue by blalor** [golang/go#11183]
`internetAddrList` would be useful for looking up an IP address from a hostname without having to test if the string's already an IP address.

`lookupIPDeadline` would be useful for looking up an IP address with a specified timeout.  I'd generally like to see a way to resolve information from DNS with a timeout, without having to resort to a 3rd-party library.

**Comment by ianlancetaylor** [comment]
The net API is already far too complex and difficult to understand, so each new addition has to be clearly necessary.  Both of these operations can be done already, so it's not clear to me that it's worth adding them to the net package.  But I'm happy to hear other opinions.

(You don't need a third party library to lookup a DNS entry with a timeout, you just need a goroutine and a channel.)

**Comment by mikioh** [comment]
Closing the same as #20783.
