### ISSUE TITLE
net: Test TestLookupHost-2 failed when building

### ISSUE THREAD

**Issue by quchunguang** [golang/go#11182]
...
ok  	mime/multipart	0.128s
ok  	mime/quotedprintable	0.395s
--- FAIL: TestLookupHost-2 (0.01s)
	hosts_test.go:132: LookupHost("localhost") = [127.0.0.1 127.0.0.1], has duplicate addresses
FAIL
FAIL	net	2.072s
ok  	net/http	4.068s
...

$ go version
go version devel +202ef48 Fri Jun 12 04:33:50 2015 +0000 linux/amd64
$ uname -a
Linux kevin1 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davecheney** [comment]
Quick check, does 127.0.0.1 or localhost appear more than once in your `/etc/hosts/` file ?

**Comment by quchunguang** [comment]
Oh... Yes.
But it seems not a problem if  127.0.0.1 appear more than once in /etc/hosts/ file.

**Comment by ianlancetaylor** [comment]
It's not a real problem.  You can ignore this test failure.

The test is looking for a specific problem that can cause duplicate addresses to be returned.  If there really are duplicate addresses, the test will fail incorrectly.  Perhaps we should skip the test if testing.Short is true.
