### ISSUE TITLE
time: Minor documentation correction for pkg/time/#Time.Format

### ISSUE THREAD

**Issue by harikb** [golang/go#11190]
The documentation should mention that the example for http://golang.org/pkg/time/#Time.Format prints the same value for t.Format() and t.UTC().Format(). Reader may assume Format() always prints UTC. I think it behaves that way only because play.golang.org server runs in UTC. May be you should do one of 

1. set play.golang.org to a different timezone because UTC is so special (for the rest of the world) 
2. or document this near / inside the example.
3. or change the example to use a different timezone instead of time.Local

**Comment by ianlancetaylor** [comment]
Interesting point.  The example is clear enough, and if you run it yourself the expected thing will happen, but if you run it by clicking on the button on golang.org it will indeed always print in UTC.

I guess my vote is to expand the comment in the example to mention what happens on golang.org.

**Comment by adg** [comment]
At tip the example has been made much more complete, and I don't think it suffers from the same muddiness as the original pithy one:

http://tip.golang.org/pkg/time/#Time.Format

**Comment by robpike** [comment]
Fixed at tip.
