### ISSUE TITLE
net/http: does not verify validity of Host header

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11206]
Request parsing does not verify validity of Host header, in particular it can contain spaces.
This leads to weird possibilities like:
```go
package main

import (
	"bufio"
	"bytes"
	"os"
	"net/http"
)

func main() {
	data := []byte("GET http:/1.1 HTTP/1.1\nHost: host.com/somethingelse HTTP\n\n")
	r, err := http.ReadRequest(bufio.NewReader(bytes.NewReader(data)))
	if err != nil {
		panic(err)
	}
	r.WriteProxy(os.Stdout)
}
```
```
GET http://host.com/somethingelse HTTP/1.1 HTTP/1.1
Host: host.com/somethingelse HTTP
User-Agent: Go 1.1 package http
```
which I guess can trick some other HTTP implementation.

go version devel +a1fe3b5 Sat Jun 13 04:33:26 2015 +0000 linux/amd64

**Comment by jeffallen** [comment]
I have a fix for this, for discussion purposes. I think it's 50% likely Brad will barf all over it, but hopefully his feedback will lead me to the right fix.. :)

**Comment by fyelles** [comment]
@jeffallen, Did you notify the mailing list that you were working on this ? as mentioned in https://golang.org/doc/contribute.html > Discuss your design 

I was working on the same bug and was just ready to submit it...
It's OK because it was a small one...

**Comment by rsc** [comment]
For the record, it's not necessary to notify the mailing list when you are working on a simple bug fix. It's fine to say something on the github issue if you are worried about duplicating effort.

**Comment by rsc** [comment]
Leaving open because the CL says "We may come back and make this stricter for 1.6."
