### ISSUE TITLE
tour: Basic, exported names. Example code contain error.

### ISSUE THREAD

**Issue by Megabyteceer** [golang/go#11212]
Context: /basics/3

math.pi is undefined.
 math.Pi compiled ok. Fix please.

**Comment by griesemer** [comment]
Working as intended. Please read the prose for the example:

"Then rename math.pi to math.Pi and try it again."

**Comment by Megabyteceer** [comment]
I have no any prose in tour page. Just menu and frame with example code. Maybe my device is too old broken. : )
IPad, ios6.0, chrome.

**Comment by adg** [comment]
@Megabyteceer can you send me a screenshot of how it looks on your device?

**Comment by griesemer** [comment]
FWIW: The respective page looks fine on an iPhone S running iOS 8.3 and latest version of Chrome for iOS; and also in Safari. The prose appears above the playground frame on these small-screen devices.

**Comment by Megabyteceer** [comment]
Hi Andrew, i haven't my device with me for now, but i make sceenshot
(attached) in chrome device-emulation mode. And page look exactly same on
my device.
Here no way to scroll or scale page. And middle column with description
text is fully invisible. I didn't know that middle column is exist. It's
why i found 'math.pi' error strange.

Thank you, and sorry to bother you anyway : )

2015-06-15 3:13 GMT+05:00 Robert Griesemer <notifications@github.com>:

> FWIW: The respective page looks fine on an iPhone S running iOS 8.3 and
> latest version of Chrome for iOS; and also in Safari. The prose appears
> above the playground frame on these small-screen devices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/11212#issuecomment-111879482>.
>



-- 
Best regards!
Vasiliy Kostin.

**Comment by adg** [comment]
I don't think GitHub supports attachments. :-/

Upload it to imgur.com ?

**Comment by Megabyteceer** [comment]
Screenshot is here: http://imgur.com/3hnc7kH

**Comment by adg** [comment]
Aha! The menu is covering the entire text area, so you can't see it. If you click the menu icon in the top left it will go away. Perhaps the menu should automatically retract when a page is selected? Or perhaps it should not cover the entire text area?

cc @campoy

**Comment by Megabyteceer** [comment]
Oh, understand now : ) But really its not look like menu on device. Its show without scroll / rollup on device. Just blink. And i think it is another page with static menu is loaded.
I think auto hide after choose will be enough (and hide if menu width is > 50% of description text width only). Thank you. I already finish with tour, but maybe sombody else will not confuse like me again. : )

**Comment by adg** [comment]
Let's see what we can do. Thanks for the report.
