### ISSUE TITLE
net/rpc: Server.Accept logs an error when the Listener is closed

### ISSUE THREAD

**Issue by willfaught** [golang/go#11221]
The logging is fatal. There appears to be no way to stop a Server without the process exiting.

**Comment by bradfitz** [comment]
net/http.Server has no Accept field or method.

Did you mean to continue your discussion in #11219? This appears to be a dup.

**Comment by willfaught** [comment]
How net/http.Server got into net/rpc would be a separate bug. ;)

**Comment by bradfitz** [comment]
Oh, sorry. I saw what appeared to be two duplicate bugs come in.

I'll let @robpike deal with this one.
