### ISSUE TITLE
net: dialTCP should support cancelation

### ISSUE THREAD

**Issue by pmarks-net** [golang/go#11225]
Brad suggested that I file this bug during the [Happy Eyeballs code review](https://go-review.googlesource.com/#/c/8768).

Currently, the `dialTCP` function will block until the operation succeeds, fails, or times out.  If a dialer decides that the connection is no longer useful, it must be leaked and left to die on its own time.

Instead, there should be some cancelation mechanism (e.g. a closeable `chan struct{}`) which causes `dialTCP` to clean up its socket and return `errCanceled` immediately.  This might also be exposed via the `Dialer` interface, and for non-TCP protocols, so regular users can take advantage of it.

**Comment by mikioh** [comment]
Also please follow #11626.

**Comment by pmarks-net** [comment]
With the pending fix, is it expected that `dialTCP` will return quickly when canceled, on every platform that Go supports?

If so, then we can rewrite `dialParallel` to always wait for `dialTCP`, and not leak.

**Comment by bradfitz** [comment]
@pmarks-net, I didn't do Windows or Plan 9 yet. I wanted to see what people thought about it first before I did more.

**Comment by bradfitz** [comment]
(but yes, cleaning up `dialParallel` was a big part of the motivation)

**Comment by pmarks-net** [comment]
I don't think this can be closed until tcpsock_plan9 is also cancelable, unless it's acceptable to force `DualStack: false` on plan9.

Making `dialParallel` not leak implies waiting for `dialTCP`, which is only feasible if `dialTCP` is guaranteed to return quickly.

**Comment by bradfitz** [comment]
Plan 9 doesn't really matter. You can force DualStack to false there. Don't let Plan 9 hold anything back.
