### ISSUE TITLE
x/build/cmd/gitmirror: smarter git exporter filtering

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11224]
Add the capability for the watcher's git archive server to optionally filter out content.

Then when the coordinator is asking for the "talks" repo, it can skip the 30+ MB of binaries.

We already do this with the .gitattributes file (see https://golang.org/cl/11050 for #11199) but that's a hack. We should revert that once the coordinator knows how to ask the watcher to filter stuff.

/cc @adg @minux

**Comment by kevinburke** [comment]
I can take this one.

**Comment by kevinburke** [comment]
Thoughts on how the coordinator should ask to exclude files? 

```
GET /build.tar.gz?exclude=foo.jpg&excludeGlob=*.png
```

**Comment by kevinburke** [comment]
This might be a little tricky. If I am reading correctly the only way to exclude files from `git archive` is via a `.gitattributes` file. We could write this file based on the "ignore" values of the incoming request, but if I am reading correctly `git archive` hardcodes the `.gitattributes` filename, so we can only have one incoming request served at a time and that request has to clobber the `.gitattributes` file - you can't do like `git archive --with-attributes=/tmp/foo/.gitattributes`.

Another option would be to write the gzip file, open it with a `gzip.Reader`, and strip files out that we want to exclude before sending it over the wire.

https://git-scm.com/docs/git-archive

**Comment by bradfitz** [comment]
Closing this. Not worth the effort. We can reopen later if the need arises.
