### ISSUE TITLE
cmd/go: GOROOT not being recognized

### ISSUE THREAD

**Issue by jakirkham** [golang/go#11227]
If I run the following `go run hello.go` ( https://golang.org/doc/install ), I get the following error.

    go: cannot find GOROOT directory: /home/vagrant/miniconda/envs/goenv

This directory does exist and `go` is within `bin` below this directory. If I explicitly set `GOROOT` to that directory before running like so `GOROOT=/home/vagrant/miniconda/envs/goenv go run hello.go`, I get the expected result.

    hello, world

The only line that I could expect would cause this issue is here ( https://github.com/golang/go/blob/239ec73e66b4c4706b2261082857d5afa5c53da9/src/cmd/go/main.go#L153 ). If I run `stat` on the directory like so `stat /home/vagrant/miniconda/envs/goenv`, I get this result.

      File: `/home/vagrant/miniconda/envs/goenv'
      Size: 4096      	Blocks: 8          IO Block: 4096   directory
    Device: fd02h/64770d	Inode: 3937024     Links: 9
    Access: (0775/drwxrwxr-x)  Uid: (  500/ vagrant)   Gid: (  500/ vagrant)
    Access: 2015-06-15 23:24:57.320138356 +0000
    Modify: 2015-06-15 23:24:57.663046317 +0000
    Change: 2015-06-15 23:24:57.663046317 +0000

I have reproduced this error on Mac and Linux. Any thoughts or suggestions as to why this is happening? For the record, this my first day with `go` so assume I know nothing. :)

**Comment by davecheney** [comment]
You don't need to set GOROOT. Instead, unpack the source code to
/home/vagrant/...blah, cd into src/ then run all.bash. once that is
complete add /home/vagrant/...blah/bin to your PATH and you are done.

Sorry for the elided paths, phone

**Comment by adg** [comment]
What does `go env` print?

**Comment by jakirkham** [comment]
`go env` will make the same complaint unless I have set `GOROOT`, in which case I get the following.

    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/home/vagrant/miniconda/envs/goenv"
    GOTOOLDIR="/home/vagrant/miniconda/envs/goenv/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="1"

**Comment by jakirkham** [comment]
@davecheney, the `all.bash` sounded like a good idea, but that did not seem to go well. I got something that looked like this.

    # Building C bootstrap tool.
    cmd/dist
    go tool dist: FAILED: git rev-parse --abbrev-ref HEAD

**Comment by davecheney** [comment]
@jakirkham unless you absolutely need to build tip, I recommend sticking with the source tarball from the website to try to limit the problems you have in your environment.

**Comment by jakirkham** [comment]
Maybe this might help, how does `goroot` get set in `go/main.go`? It doesn't appear to be set anywhere. Does it get spliced in somehow?

**Comment by jakirkham** [comment]
I did indeed pick a tar ball ( http://storage.googleapis.com/golang/go1.4.2.src.tar.gz ).

**Comment by davecheney** [comment]
@jakirkham this might be a more appropriate thread for the mailing list, the issue tracker is discouraged as a general support conduit.

**Comment by jakirkham** [comment]
Ok, sorry, where should I go then?

**Comment by davecheney** [comment]
https://groups.google.com/forum/#!forum/golang-nuts

To be clear, you're welcome to raise bugs on the issue tracker, but side conversations about how GOROOT is set are best addressed in the mailing list.

**Comment by rsc** [comment]
Please try two things:

First:

	env | grep GOROOT | hexdump -C

Second:

	cat >/tmp/x.go <<EOF
	package main
	
	import (
		"fmt"
		"runtime"
	)
	
	func main() {
		fmt.Printf("GOROOT=%q\n", runtime.GOROOT())
	}
	EOF
	
	GOROOT=/home/vagrant/miniconda/envs/goenv go build /tmp/x.go
	GOROOT="" ./x

If you're using a tar file I don't understand how it is getting to the "right" GOROOT but not quite. The only thing I can think of is that you do have a GOROOT set, but it has some kind of invisible characters in it. Running the explicit GOROOT=... go run form overrides the not-quite-right GOROOT.

**Comment by jakirkham** [comment]
So, I think I have fixed what was causing this problem, but it has resulted in a new problem. As a result, I will open it in a new issue. Thanks for everyone's help.
