### ISSUE TITLE
cmd/go: go get fails when GOPATH dir is relative

### ISSUE THREAD

**Issue by techtonik** [golang/go#11234]
When I specify GOPATH as relative to current dir, the `go get` command fails.

From https://github.com/syncthing/syncthing-cli/issues/12
```
$ mkdir .go
$ GOPATH=.go go get github.com/syncthing/syncthing-cli  
# github.com/AudriusButkevicius/cli
open .go/src/github.com/AudriusButkevicius/cli/app.go: No such file or directory
...
$ go version
go version go1.2.1 linux/amd64
```

I am using Ubuntu 14.04 packaged Go. http://packages.ubuntu.com/trusty/devel/golang-go

**Comment by bradfitz** [comment]
Instead of making relative paths work, we should probably just detect relative paths and fail earlier with a nice error.

**Comment by robpike** [comment]
Relative paths are dangerous when applied globally like this. I agree it should just be diagnosed.

**Comment by davecheney** [comment]
Seconded.

**Comment by adg** [comment]
This was fixed by @broady in 239ec73e66b4c4706b2261082857d5afa5c53da9. Note that the issue reporter's go version is 1.2.1.

**Comment by techtonik** [comment]
I am +1 on detecting error case. Is it possible to backport it to stable Debian/Ubuntu?

**Comment by bradfitz** [comment]
That is a question for Debian and/or Ubuntu, but not us. We don't do their packaging, nor do we maintain very old releases.
