### ISSUE TITLE
x/build/buildlet: health check failing on Plan 9 builder

### ISSUE THREAD

**Issue by 0intro** [golang/go#11239]
Since [CL 10981](http://golang.org/cl/10981), the Plan 9 builders are failing on :

```
Installed Go for plan9/386 in /tmp/workdir/go
Installed commands in /tmp/workdir/go/bin
*** You need to bind /tmp/workdir/go/bin before /bin.
Failed to schedule "go_test:archive/tar" test after 3 tries.
```

It happens because the health check executed by the coordinator are failing.
Brad thinks the Plan 9 buildlet couldn't execute the tests in a child process
and reply to a health check at the same time.

Brad submitted [CL 11132](http://golang.org/cl/11132) to work around this issue.
It seems that no more than two health checks could fail consecutively.

**Comment by bradfitz** [comment]
Build-only things like this don't affect the release. Of course, if you find a critical bug, perhaps it can be fixed for Go 1.5, depending on what it is.

**Comment by bradfitz** [comment]
I've also tried adding runtime.GOMAXPROCS(1) to the Plan 9 buildlet, but it doesn't seem to make a difference.

**Comment by bradfitz** [comment]
Old. I'm going to close this for now and file a new bug with more details if I notice problems.
