### ISSUE TITLE
warning: unknown attribute '__gcc_struct__' ignored

### ISSUE THREAD

**Issue by jakirkham** [golang/go#11232]
I am receiving this warning `warning: unknown attribute '__gcc_struct__' ignored` when building on Mac (OS 10.9). It occurs often and ends up killing the build. Here are some of the files I am seeing this happen with.

    crypto/x509/root_cgo_darwin.go
    net/cgo_unix.go
    os/user/lookup_unix.go
    issue9026/issue9026.go
    issue8828/trivial.go

Finally, I see a test failure. I'm thinking they are related, but I don't know how.

    FAIL	_/zopt/conda/envs/_test/go/misc/cgo/test [build failed]

FWIW, I don't see this error when building on Linux (CentOS 6.3). As this version of Mac uses `clang`, I am wondering if that has something to do with the issue. Is there someway for me to suppress this build warning?

**Comment by davecheney** [comment]
Can you please post the entire build log.

**Comment by jakirkham** [comment]
Sure, I put it here ( https://gist.github.com/jakirkham/b57a2f20e54d3d7ffd1c ). However, I think that it was the `gcc` frontend that was causing this problem and just now I have gone through the build successfully by setting clang/clang++ in the environment variables `CC` and `CXX`. Though I'm guessing there is no C++ code involved here so latter is probably unnecessary.

**Comment by davecheney** [comment]
Can I suggest that you report further problems via the golang-nuts mailing list.

**Comment by jakirkham** [comment]
For this particular issue, I disagree. Build steps with most software tends to be painful and under documented (e.g. type the magic command and *everything* just works) and I say this after having a lot of build experience. I really tried to scour the web before posting this here. This issue with Mac could be better documented. Having an issue here is one step in that direction.

For language issues that I encounter as beginner, sure I will check stackoverflow/mailing list and post them to one of those places.

**Comment by rsc** [comment]
Do you have a custom gcc installed? If you have the default one shipped by Apple it should work fine. But if $CC or $GCC points at a non-default one, then it depends how non-default it is. Please run:

    $ env | grep CC
    $ which gcc
    $ gcc -v
    $ gcc -E -dM -xc /dev/null | grep clang

If env shows any other CC or GCC setting please repeat those gcc commands with the command indicated in those variables. Thanks.

**Comment by jakirkham** [comment]
I don't have CC set. `which gcc` points to the standard Apple frontend and all the other commands listed point to the standard `gcc` frontend.

However, I do have GCC to this `/usr/local/gfortran/bin/gcc` a non-standard compiler version 4.8.2 from here ( https://gcc.gnu.org/wiki/GFortranBinaries#MacOS ).

**Comment by jakirkham** [comment]
@rsc, you were correct. It turns out by setting `GCC` and `GXX` this problem was caused. I tested with them unset and also did not set `CC` or `CXX` and the problem was resolved.

**Comment by ianlancetaylor** [comment]
For the record this should not happen with tip no matter how GCC is set (see the fix for issue #10453).

@jakirkham If you were building tip rather than 1.4, please let us know.  Thanks.  (And please always do mention the version of Go in any bug report--if you did mention it, I apologize for missing it.)

**Comment by jakirkham** [comment]
@ianlancetaylor, sorry about that. Added to the issue description.
