### ISSUE TITLE
tour: possible error in description of /moretypes/14

### ISSUE THREAD

**Issue by denis-pitul** [golang/go#11231]
Context: /moretypes/14

The text hinting about functions one can use to create interesting images reads:
>The choice of image is up to you. Interesting functions include (x+y)/2, x*y, and x^y (to compute the latter function, use math.Pow). 

It seems to me that `math.Pow` does not create results as interesting as the `^`(bitwise XOR) operator.

**Comment by ALTree** [comment]
In this context, `x^y` is a way to denote exponentiation, not XOR (that's why it says you have to use math.Pow)

**Comment by ianlancetaylor** [comment]
CC @adg @campoy
