### ISSUE TITLE
doc: extract examples from tests

### ISSUE THREAD

**Issue by dericofilho** [golang/go#11248]
I suggest digging tests and extract meaningful examples from them.

If approved, I can produce a set of CLs for that.

**Comment by dericofilho** [comment]
Related issues 
https://github.com/golang/go/issues/5757 
https://github.com/golang/go/issues/11241

**Comment by ianlancetaylor** [comment]
Are you suggesting some sort of automated process?  I don't think that is a good idea.

If you are suggesting that people manually look at tests and use them to construct examples, then, sure.  I don't think we need a general issue open for that, though.

**Comment by dericofilho** [comment]
@ianlancetaylor definitely manually. I haven't even fathomed the idea of doing it automatically. 

I open this issue here, so later I would peg case by case CL and Issues into this one. But if this is done differently, I do not mind closing this and going along with whatever is the right thing.

**Comment by ianlancetaylor** [comment]
I think this topic is too general for a catch all issue to be useful.

**Comment by dericofilho** [comment]
@ianlancetaylor so what am I supposed to do?

**Comment by ianlancetaylor** [comment]
I don't understand what you are asking.

I am completely in favor of looking at tests and turning them into examples.  I think you should do that.

I just don't think that this issue is helpful.

**Comment by dericofilho** [comment]
@ianlancetaylor I apologize for not being clear. I would like to know whether opening CL with the individual changes is enough, or should I open issues for each CL I post.

**Comment by ianlancetaylor** [comment]
You can just send in a CL.  There is no need to open an issue for each CL.
