### ISSUE TITLE
tour: define int and default types

### ISSUE THREAD

**Issue by MiguelMunoz** [golang/go#11240]
Context: /basics/11

Basic types:

Page should say that int is the same as int32 (or whatever it is, if my guess is wrong).

Page should also tell us what the default types are:
v := 3.2  // v will be of type float64

**Comment by ianlancetaylor** [comment]
How are you creating these issues?  Why is the issue title not useful?

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by MiguelMunoz** [comment]
Sorry. I didn't see the place to write the title.

**Comment by minux** [comment]
The title is the default one when the user clicks
on the "report bug" button on the upper right
corner of the go tour. Perhaps we should make
it clearer that the user is supposed to change
the text in square brackets.

**Comment by campoy** [comment]
I created this:

https://go-review.googlesource.com/11731

**Comment by campoy** [comment]
Other than for the title of the bug, should we add a note concerning the size of `int`?
// @adg

**Comment by adg** [comment]
Yes.

**Comment by campoy** [comment]
Adding a clarification on the size of int, uint, and uintptr

https://go-review.googlesource.com/13135
