### ISSUE TITLE
proposal: negative value for slice index

### ISSUE THREAD

**Issue by mattn** [golang/go#11245]
hope equivalent to python's `arr[1:-1]`. for example:

```go
arr := GetItems()
fmt.Println(arr[1:len(arr)-1])
```
we need to take arr as variable. but i want
```go
part_of_arr := GetItems()[1:-1]
```

**Comment by adg** [comment]
The omission of this feature (present in Python, for example) is deliberate

When performing arithmetic on slice indices it would be unfortunate if an erroneous negative result "just worked" as a reverse index. This leads to subtle bugs.

There are readability benefits to the status quo, also. It is clear that the Go expression `s[:i]` is creating a slice of `s` that is `i` bytes long. If `i` could be negative then the reader would need more context to understand the slice expression.

This is in keeping with Go's general philosophy of avoiding subtle syntactic tricks.
