### ISSUE TITLE
x/tools/cmd/godoc: Provide a feedback link for documentation pages

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11255]
It might be useful for Go newbies if there were a feedback link on documentation pages.  Systems like PHP permit people to add comments to every doc page, and those comments sometimes expand to be useful additions.  That is problematic because it leads directly to spam, but a simpler possibility would be a direct link to the issue tracker.

Could we add something like this golang.org?  To godoc.org?  Do we want to?

**Comment by josharian** [comment]
Increased opportunities for feedback are definitely helpful. We already struggle a bit to keep questions and requests for help on the mailing list instead of the issue tracker, though, so if we do this, it'd be good to try to guide people to the right forum--suggestions for improvements here, questions there. The line is subtle, of course.

**Comment by dr2chase** [comment]
Alternately, could each topic in the online spec be annotated with links to tutorial materials, blog posts, related FAQ entries, and recommended style?  We'd want to be a little careful about ensuring that links don't get stale (perhaps we can automate that) but this might address some of the recent complaints.  I am in the newbie category myself, and it does require a bit of by-hand navigation and hopping around.

**Comment by adg** [comment]
@dr2chase's suggestion is a good one. If we were able to cross-reference our various docs then we could more aggressively cross-link them.

**Comment by adg** [comment]
FWIW we once had feedback links on all golang.org pages and the signal to
noise ratio was very, very low.

**Comment by seankhliao** [comment]
I believe pkgsite links to the original source repo (where most people have their issue trackers) now.
