### ISSUE TITLE
all: move all examples to external test packages

### ISSUE THREAD

**Issue by josharian** [golang/go#11257]
This is an extraction from #11254.

Having the package prefix in examples is clearer than omitting it. Since examples must not make use of unexported functionality anyway, it is always ok to have them in an external test package. Let's move all examples to external test packages.

If Go 1 compatibility didn't prevent it, I'd suggest that we modify the testing package to enforce this.

**Comment by josharian** [comment]
Filed https://github.com/golang/lint/issues/135 to for a lint check for this.

**Comment by adg** [comment]
I could only find one such set of examples, in package mime. CL incoming.

My command line for finding them is:

```grep '^package' $(git grep -l '^func Example') | grep -v '_test$'```
