### ISSUE TITLE
Do their packaging

### ISSUE THREAD

**Issue by techtonik** [golang/go#11253]
From https://github.com/golang/go/issues/11234#issuecomment-112792952:
> We don't do their packaging,

@bradfitz why not? If Go is covered by tests and being developed on Ubuntu/Debian, then Go developers know better what is backward compatible and what is not. I'd expect an uptodate Go version if not in http://packages.ubuntu.com/trusty/golang-go then at least in [backports](https://help.ubuntu.com/community/UbuntuBackports) as golang12-go, golang13-go etc.

As a side benefit, if Go is capable to "do their packaging", and if that could be copied by other Go software, that will pave the way for Go written software into these OS and make it more popular in Linux/Unix (as a Python replacement).

Just not to isolate this to Ubuntu/Debian, Fedora is another interesting target.

**Comment by bradfitz** [comment]
Dup of #10965
