### ISSUE TITLE
sync/atomic: atomic.Value doesn't support CompareAndSwap

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#11260]
`atomic.Value` *should* have CompareAndSwap support.

If there's interest, I'll clean up my patch and put it up for review.

**Comment by cespare** [comment]
What if you store uncomparable types in a `Value` (maps, slices, funcs, ...)?

**Comment by dvyukov** [comment]
Mutex usually works well for protecting write side of Value.

**Comment by OneOfOne** [comment]
@cespare that's a good point, I was thinking about pointers mostly, didn't think about storing values.

@dvyukov I was trying to avoid that, and it seemed logical to have CAS anyway since most languages that have `atomic.Value`-style built-in already supports CAS. (ex: [c++](http://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange) [java](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/package-summary.html))

**Comment by dvyukov** [comment]
@OneOfOne  If the only argument is that other languages have it, then I propose to not implement it.

**Comment by OneOfOne** [comment]
@dvyukov not at all, I was just giving an example.

A good usage case for it is a (doubly) linked list, and avoiding mutexes all together.

**Comment by dvyukov** [comment]
Lock-free doubly-linked lists are insanely difficult to implement and are very slow because (1) link-based data structures are slow due to indirection and (2) shared data structures with high mutation rate are slow due to cache contention. And they can be implemented with atomic.CompareAndSwapPointer.
This does not look like a very convincing use case for addition of the new API.

**Comment by OneOfOne** [comment]
I understand that, but atomic.Value is there and it exists, it has Load/Store like the other types in the atomic package, it's missing a function.

It's not an addition of a new API, it's adding a missing functionality.

**Comment by adg** [comment]
I think Dmitry is referring to the addition of this new function as "the new API".

I don't see how the new API would work with non-comparable values. It seems to invite misuse.

To risk repetition, if your use case is pointers then you should use `atomic.CompareAndSwapPointer`.

**Comment by dvyukov** [comment]
Value.Load/Store are different from CompareAndSwap/Add/Exchange:
1. They support a very well-defined use case (see examples), which is very efficient and relatively simple to code, and the one we want to promote for cases where high performance and scalability are required.
2. They are supported on all types as opposed to CompareAndSwap/Add.

**Comment by rsc** [comment]
No thanks, per conversation above.
