### ISSUE TITLE
go/internal/gccgoimporter: File.ReadAt moves underlying seek position on Plan9?

### ISSUE THREAD

**Issue by griesemer** [golang/go#11265]
https://go-review.googlesource.com/#/c/11152/ fails on Plan 9 without line 7 in https://go-review.googlesource.com/#/c/11152/7/src/go/internal/gccgoimporter/importer_test.go (and the corresponding line 7 in https://go-review.googlesource.com/#/c/11152/7/src/go/internal/gccgoimporter/gccgoinstallation_test.go).

The change was submitted with the tests disabled for Plan 9. When actually running the tests on Plan 9 (i.e., without the build tag), the failure is:

```
--- FAIL: TestGoxImporter (0.00s)
	importer_test.go:26: unrecognized magic string: "pack"
	importer_test.go:26: unrecognized magic string: "pack"
	importer_test.go:26: unrecognized magic string: "pack"
	importer_test.go:26: unrecognized magic string: "pack"
	importer_test.go:26: unrecognized magic string: "pack"
FAIL
FAIL	go/internal/gccgoimporter	0.031s
```

( https://storage.googleapis.com/go-build-log/e6448c25/plan9-386_c70f45b0.log )

Analysis:

In this specific test, the go/internal/gccgoimporter/testdata/*.gox files are read. In a first step, openExportFile (importer.go:74ff) reads the first 4 "magic" bytes using File.ReadAt (line 87). They are "v1;\n" (see e.g. testdata/pointer.gox). In a 2nd step, the closure returned by GetImporter (importer.go:142ff) reads the file's magic bytes again, this time via io.ReadSeeker.Read. It appears that the next 4 bytes "pack" are read this time, leading to the above error.

On non-Plan9 systems, this error doesn't appear. It seems that the Plan9 File.ReadAt moves the seek position, while other OSes don't.

From the documentation:

- http://golang.org/pkg/os/#File.ReadAt doesn't say anything about the seek position.
- http://golang.org/pkg/io/#ReaderAt is quite specific:
"If ReadAt is reading from an input source with a seek offset, ReadAt should not affect nor be affected by the underlying seek offset."

It would appear the File.ReadAt should follow this specification as well (and perhaps it should be documented).

**Comment by bradfitz** [comment]
I don't think we need to repeat the io.ReaderAt docs on every implementation thereof.

This is just a Plan 9 bug.

**Comment by griesemer** [comment]
It appears that https://go-review.googlesource.com/11194 makes the Plan9 test pass, confirming the hypothesis above.

**Comment by bradfitz** [comment]
Also revert https://go-review.googlesource.com/11210

**Comment by griesemer** [comment]
It's fine to revert once the bug is fixed. This is not critical and the
work-around is documented.

**Comment by 0intro** [comment]
Thanks for investigating this issue.

In my understanding, the Plan 9 [read](https://9p.io/magic/man2html/2/read) documentation says that:

```
pread(fd, buf, nbytes, offset)
```

Is equivalent to:

```
seek(fd, offset, 0)
read(fd, buf, nbytes)
```

So, it does indeed change the seek offset, which is not the behavior expected by Go.

I think the solution is to call f.seek(0, SEEK_SET) just after syscall.Pread in Go's implementation of [pread](https://github.com/golang/go/blob/cfb8b18e75/src/os/file_plan9.go#L254) on Plan 9.

What do you think?

**Comment by bradfitz** [comment]
That's not how I read those docs.  Look at the last sentence:

> Pread and Pwrite are equivalent to a seek(2) to offset followed by a read or write. By combining the operations in a single atomic call, they more closely match the 9P protocol (see intro(5)) and, more important, permit multiprocess programs to execute **multiple concurrent read and write operations on the same file descriptor without interference.**

So it seems like the normal `pread` or `io.ReaderAt` semantics.

**Comment by bradfitz** [comment]
@0intro, even if it does atomically do the seek + read but leaves the seek offset modified for other threads, that still violates Go's semantics.

In Go, one goroutine must be allowed to use an io.Reader+io.ReaderAt as a Reader while the other uses the same value as an io.ReaderAt, and neither one of them is allowed to interfere with the other goroutine.

Where is the Plan 9 source for the implementation of pread?

**Comment by 0intro** [comment]
> Where is the Plan 9 source for the implementation of pread?

Here:

https://github.com/0intro/plan9/blob/bd0c9332d5/sys/src/9/port/sysfile.c#L701

**Comment by ality** [comment]
I'm working on this in https://go-review.googlesource.com/11280

However, I now think it's a kernel bug. Awaiting feedback on 9fans.
https://marc.info/?l=9fans&m=143488356201304&w=2

**Comment by rsc** [comment]
This is a Plan 9 kernel bug.
