### ISSUE TITLE
net: Plan 9 setKeepAlivePeriod bug?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11266]
Plan 9's network code in src/net/tcpsockopt_plan9.go contains this questionable piece of code writing to the ctl file:

```
// Set keep alive period.                                                                                                                  
func setKeepAlivePeriod(fd *netFD, d time.Duration) error {
        cmd := "keepalive " + string(int64(d/time.Millisecond))
        _, e := fd.ctl.WriteAt([]byte(cmd), 0)
        return e
}
```

Is that really the Plan 9 interface? Or should be it strconv.Itoa instead?

Otherwise it's actually writing something like `"keepalive Ϩ"` if d is `1 * time.Second`.

**Comment by 0intro** [comment]
Yes, this code is incorrect. The period should be the milliseconds as a string.
This is described in the [ip(3)](http://9p.io/magic/man2html/3/ip) manual. Thanks for noticing.
