### ISSUE TITLE
cmd/link: Go referencing C + C referencing Go = duplicate symbols

### ISSUE THREAD

**Issue by shazow** [golang/go#11263]
In a recent master, combining [the two examples here](https://tip.golang.org/cmd/cgo/) will yield a duplicate symbol error on build. Either example alone works fine.

```
$ go version
go version devel +a2aaede Wed Jun 17 14:55:39 2015 +0000 darwin/amd64
```

```go
package main

// typedef int (*intFunc) ();
//
// int
// bridge_int_func(intFunc f)
// {
//		return f();
// }
//
// int fortytwo()
// {
//	    return 42;
// }
import "C"
import "fmt"

//export Hello
func Hello() {}

func main() {
	f := C.intFunc(C.fortytwo)
	fmt.Println(int(C.bridge_int_func(f)))
	// Output: 42
}
```

Including the `//export Hello` line yields this error:

```
$ go build -buildmode=c-archive
# _/Users/shazow/projects/gohttplib
duplicate symbol _bridge_int_func in:
    $WORK/_/Users/shazow/projects/gohttplib/_obj/_cgo_export.o
    $WORK/_/Users/shazow/projects/gohttplib/_obj/gohttplib.cgo2.o
duplicate symbol _fortytwo in:
    $WORK/_/Users/shazow/projects/gohttplib/_obj/_cgo_export.o
    $WORK/_/Users/shazow/projects/gohttplib/_obj/gohttplib.cgo2.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Doesn't matter if the `-buildmode=c-archive` flag is included. If the `//export Hello` line is removed, it works fine. If the inline C code is removed, it works fine.

Scenario: I'm trying to pass a callback (function pointer) from C into a Go function and I was trying to use an inline bridge function for calling it.

**Comment by ianlancetaylor** [comment]
This is documented at http://golang.org/cmd/cgo: "Using //export in a file places a restriction on the preamble: since it is copied into two different C output files, it must not contain any definitions, only declarations. Definitions must be placed in preambles in other files, or in C source files."

**Comment by shazow** [comment]
Aaah that's what that means, thank you. Let me know if you'd like a docs patch to mention the duplicate symbols consequence for clarity.

**Comment by ianlancetaylor** [comment]
I'm happy to look at a doc patch if you think you can make it more clear.  Thanks.

**Comment by shazow** [comment]
@ianlancetaylor Proposed an edit here: https://go-review.googlesource.com/#/c/11247/
