### ISSUE TITLE
cmd/asm: integer comparison is always false

### ISSUE THREAD

**Issue by tzneal** [golang/go#11278]
cmd/asm/internal/asm/parse.go:817: comparison of identifier shift < 0 is always false

shift is a uint64, and can never be negative.  The check and error is unreachable code.

```
func (p *Parser) term() uint64 {
        value := p.factor()
        for {
               
...
                case lex.RSH:
                        p.next()
                        shift := p.term()
                        if shift < 0 {
                                p.errorf("negative right shift %d", shift)
                        }

```

**Comment by rsc** [comment]
The fix should have been to change shift < 0 to int64(shift) < 0.

**Comment by rsc** [comment]
Replied to CL.

**Comment by rsc** [comment]
I believe this is finally fixed. If not, please don't make any more changes before Go 1.5 is released.

**Comment by robpike** [comment]
It is fixed.
