### ISSUE TITLE
math/big: comparison is always true

### ISSUE THREAD

**Issue by tzneal** [golang/go#11277]
cmd/compile/internal/big/natconv.go:304: comparison of identifier nbits >= 0 is always true
math/big/natconv.go:304: comparison of identifier nbits >= 0 is always true

nbits is an unsigned, and a >=0 comparison is performed against it which is always true.

```
 nbits := uint(_W) // number of unprocessed bits in w

...
   // convert digits of most-significant word (omit leading zeros)
                for nbits >= 0 && w != 0 {
                        i--
```

(see https://groups.google.com/d/msg/golang-nuts/O4k42ETtWKQ/_ajX7fz5LUEJ for more details)

**Comment by griesemer** [comment]
https://go-review.googlesource.com/#/c/11267/
