### ISSUE TITLE
encoding/json: Maybe a bug of encoding/json.

### ISSUE THREAD

**Issue by conc** [golang/go#11283]
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	// jsonDeal([]byte(`{"name":"xiaoming","course":["1111","2222"]}`))
	// jsonDeal([]byte(`{"name":"xiaoming","course":["1111"]}`))
	jsonDeal([]byte(`{"name":"xiaoming","course":[null]}`))
	// jsonDeal([]byte(`{"name":"xiaoming","course":[]}`))
	// jsonDeal([]byte(`{"name":"xiaoming","course":null}`))
}

type User struct {
	Name   string   `json:"name"`
	Course []string `json:"course"`
}

func jsonDeal(data []byte) {
	var oneUser User
	if err := json.Unmarshal(data, &oneUser); err != nil {
		panic(err)
		return
	}
	fmt.Println("==============")
	fmt.Println("oridata:", string(data))
	fmt.Println("json result:", oneUser)
	fmt.Println("course num:", len(oneUser.Course))
	return
}

I think len(oneUser.Course) should be 0,but now it is 1.

**Comment by dspezia** [comment]
I don't see why you think it is a bug. IMO, a [null] array is not the same as a [] array ...

**Comment by conc** [comment]
@dspezia ，I understand, [null]string equals [""]string.
thanks.
