### ISSUE TITLE
runtime: bad integer comparison in signal1_unix.go

### ISSUE THREAD

**Issue by tzneal** [golang/go#11281]
runtime/signal1_unix.go:192: comparison of identifier b >= 0 is always true
runtime/signal1_unix.go:196: comparison of identifier b >= 0 is always true

```
  enableSigChan = make(chan uint32)

...
                        select {
                        case sig := <-enableSigChan:
                                if b := sig - 1; b >= 0 {
                                        sigBlocked[b/32] &^= (1 << (b & 31))
                                }
                        case sig := <-disableSigChan:
                                if b := sig - 1; b >= 0 {
                                        sigBlocked[b/32] |= (1 << (b & 31))
                                }
                        }
```

**Comment by tolchz** [comment]
At first glance, it looks like sending a zero to enableSigChan or disableSigChan would cause reading outside the array.  It's protected though from the only two places its possible (sigenable/sigdisable). Both functions look up the signal in sigtable and then ignore it unless the _SigNotify bit is set.

```
var sigtable = [...]sigTabT{
	/* 0 */ {0, "SIGNONE: no trap"},
	/* 1 */ {_SigNotify + _SigKill, "SIGHUP: terminal line hangup"},
```

**Comment by rsc** [comment]
Yes, this should be rewritten to say sig > 0 or something like that.

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/16592 is for a different problem but should fix this one too.

**Comment by rsc** [comment]
CL 16592 is not going to happen for Go 1.6. Should probably still fix the tiny comparison bug.
