### ISSUE TITLE
x/mobile/audio/al: export AL_SOURCE_DISTANCE_MODEL

### ISSUE THREAD

**Issue by rakyll** [golang/go#11298]
Package al doesn't export the `AL_SOURCE_DISTANCE_MODEL ` constant from the OpenAL Soft headers. It is the only capability that can be used with al.Enable and al.Disable.

**Comment by splace** [comment]
just been trying out some ideas for higher level abstractions of this, but have found a few more basic items also not exposed;

buffer looping, AL_LOOPING
direct source pitch changes, AL_PITCH
retrieving the current buffer, AL_BUFFER

i have forked and added, these additions could be pulled, but are quite trivial, and are purely additions.

**Comment by splace** [comment]
also now notice the offset set functions are missing;
(and offset seconds was being accessed as an int, when a float has to be more useful)

inserted.....(over writting the original 3 functions in a.go)

// OffsetSeconds returns the current playback position of the source in seconds.
func (s Source) OffsetSeconds() float32 {
	return getSourcef(s, paramSecOffset)
}

// SetOffsetSeconds sets the current playback position of the source in seconds.
func (s Source) SetOffsetSeconds(sec float32){
	setSourcef(s, paramSecOffset,sec)
}

// OffsetSample returns the sample offset of the current playback position.
func (s Source) OffsetSample() int32 {
	return getSourcei(s, paramSampleOffset)
}

// SetOffsetSample sets the sample offset of the current playback position.
func (s Source) SetOffsetSample(i int32){
	setSourcei(s, paramSampleOffset,i)
}

// OffsetByte returns the byte offset of the current playback position.
func (s Source) OffsetByte() int32 {
	return getSourcei(s, paramByteOffset)
}

// SetOffsetByte sets the byte offset of the current playback position.
func (s Source) SetOffsetByte(i int32){
	setSourcei(s, paramByteOffset,i)
}

**Comment by rakyll** [comment]
@splace, let's continue the discussion at https://github.com/golang/go/issues/13912 and https://github.com/golang/go/issues/13913.

**Comment by splace** [comment]
sure. i do have some observations.
