### ISSUE TITLE
x/mobile/audio/al: support multiple contexts

### ISSUE THREAD

**Issue by rakyll** [golang/go#11299]
We have removed the support to create multiple Context instances during the debate around the finalizers. We need to bring the Context type back.

The listener is operating on the current context and it is useful to work with multiple context instances when switching between different game settings.

**Comment by nigeltao** [comment]
It's been a while since I looked at OpenAL. Can you give an example of "different game settings" and hence why we need multiple contexts?

**Comment by rakyll** [comment]
OpenAL allows you to create multiple process-wide valid context instances. Contexts need to be made current before they became the operating active context, and there could be only a single current context. What AL listener hears is the sources that have been created on the current context.

I can prepare multiple contexts and register multiple audio sources by buffering data to these sources and keep them in memory before they are used.

In a game, if I have two different screens, I can switch back and forth between different contexts just by calling al.MakeContextCurrent. This is great for latency issues that may occur if I need to prepare a new context as I switch to a new screen (which should happen in milliseconds).

I also don't support the idea of limitation the OpenAL APIs if we don't have a good reason. We limited opening multiple devices, because there are very few instances a mobile device have multiple audio devices. I think that's a fair reason, but still I am open to relax it if we failed to see a major use case.

**Comment by nigeltao** [comment]
So an OpenAL context doesn't have any explicit state or methods by itself: there's no ctx.SetFoo, or ctx.GenSource methods, or some sort of bind(ctx, src) function? Instead, 'the current context' is some sort of global state, and app code is meant to explicitly remember which of multiple contexts is 'the current context' whenever dealing with sources? Do contexts just affect sources, or do they affect buffers too? Are sources (and buffers) bound to exactly 1 context (as opposed to 1:N, M:1 or M:N)?

**Comment by rakyll** [comment]
OpenAL context doesn't have explicit state. The OpenAL programming guide explains the relationships between Context and other objects on page 7 at http://grva.lamce.coppe.ufrj.br/labcogsdk/download/extras/openal/OpenAL_Programmers_Guide.pdf.

The audio sources are bound to the context they have created on. Buffers are shared among all contexts, so they are visible process-wide.

I have also read even though OpenAL spec documents the object relationships the way above, the implementations of OpenAL are mostly broken. On Windows, I have read online reports that only a single Context can be created. Another disclaimer is that I had no time to investigate the limitations of OpenAL Soft on multiple platforms.
