### ISSUE TITLE
x/mobile/cmd/gomobile: improve the readability of runInit(cmd *command) error 

### ISSUE THREAD

**Issue by rakyll** [golang/go#11296]
`runInit(cmd *command) error` is a long block. It might be improved by being split in multiple functions or by the introduction of higher level abstractions. We might introduce a high-level build/init package out of the cmd package, in a similar fashion of `go/build` and cmd/gomobile can simply invoke the `x/mobile/build` package.

/cc @crawshaw @hyangah

**Comment by crawshaw** [comment]
I'm pretty happy with the state of the init subcommand now.
