### ISSUE TITLE
cmd/go: vendoredImportPath doesn't follow symbolic link correctly

### ISSUE THREAD

**Issue by mikioh** [golang/go#11305]
Tip fails build on some Unix variants.
```
% file /home
/home: symbolic link to usr/home

% ./all.bash
(snip)
--- FAIL: TestVendorRun (0.02s)
	go_test.go:238: running testgo [run hello.go]
	go_test.go:257: standard error:
	go_test.go:258: invalid vendoredImportPath: dir="/usr/home/x/src/cmd/go/testdata/src/vend/hello" root="/home/x/go/src/cmd/go/testdata" separator="/"
		
	go_test.go:267: go [run hello.go] failed unexpectedly: exit status 1
FAIL
```

**Comment by adg** [comment]
The Go tool doesn't observe symbolic links, generally. I thought we had an open issue about this but I can't find it.

**Comment by mikioh** [comment]
I'm not sure which distro uses this sort of layout by default. At least it happens on my FreeBSD image which is configured with default parameters of FreeBSD installer (I guess so, maybe I chose ZFS instead of UFS) as follows:
```
% cat /etc/fstab 
# Device                Mountpoint      FStype  Options         Dump    Pass#
/dev/ada0p2             none    swap    sw              0       0
fdesc                   /dev/fd fdescfs rw              0       0

% mount -p
 mount -p
zroot/ROOT/default	/			zfs	rw,noatime,nfsv4acls 	0 0
devfs			/dev			devfs	rw,multilabel 	0 0
fdescfs			/dev/fd			fdescfs	rw		0 0
zroot/tmp		/tmp			zfs	rw,nosuid,noatime,nfsv4acls 	0 0
zroot/usr/home		/usr/home		zfs	rw,noatime,nfsv4acls 	0 0
zroot/usr/ports		/usr/ports		zfs	rw,nosuid,noatime,nfsv4acls 	0 0
zroot/usr/src		/usr/src		zfs	rw,noatime,nfsv4acls 	0 0
zroot/var/crash		/var/crash		zfs	rw,noexec,nosuid,noatime,nfsv4acls 	0 0
zroot/var/log		/var/log		zfs	rw,noexec,nosuid,noatime,nfsv4acls 	0 0
zroot/var/mail		/var/mail		zfs	rw,nfsv4acls 	0 0
zroot/var/tmp		/var/tmp		zfs	rw,nosuid,noatime,nfsv4acls 	0 0
```
I have no idea how much people would be annoyed by this limitation, maybe a few?

**Comment by adg** [comment]
Yeah I've observed this symlink on FreeBSD too. 

The question is whether it is just a test failure or indicative of a limitation of the Go tool? It shouldn't be a problem to have your GOPATH inside a symlinked directory. Or, rather, if it wasn't a problem in Go 1.4 it shouldn't become a problem now.

**Comment by mikioh** [comment]
FWIW, if you are using ZFS, only thing you have to do is just;
```
# zfs set mountpoint=/home $(storagePoolName)/usr/home
```

**Comment by ebfe** [comment]
> I have no idea how much people would be annoyed by this limitation, maybe a few?

At least one. I don't think it is new, I ran into this before.

> FWIW, if you are using ZFS, only thing you have to do is just;
> zfs set mountpoint=/home $(storagePoolName)/usr/home

A less intrusive fix is to change your home directory to the path without symlink in /etc/passwd.
It's especially annoying on machines where you don't have root access, as you have to remember to do a `cd /usr/home/<me>` before using go.

**Comment by sam3000** [comment]
> I have no idea how much people would be annoyed by this limitation, maybe a few?

It's fairly common for /home to be symlinked.

Is the vendor import behaviour itself broken or is it just the test ?   If it's just the test, then I imagine this is no biggie.  If vendoring itself won't work in a symlinked path, then IMO that should be fixed.

**Comment by mikioh** [comment]
See https://groups.google.com/d/msg/golang-dev/74zjMON9glU/4lWCRDCRZg0J.

Vanilla Go 1.4 source tree doesn't have this issue. As @adg said above, someone will disable TestVendorRun before the Go 1.5 cutoff when there's no easy fix.
