### ISSUE TITLE
tour: Un-mathematical math in Sqrt exercise

### ISSUE THREAD

**Issue by tv42** [golang/go#11306]
https://tour.golang.org/flowcontrol/8

Newton's method for Sqrt is shown as

![z = z - (x**2-x)/2x](https://tour.golang.org/content/img/newton.png)

which is weird. Math does not use the same z for noting two different values, that only happens for us imperative programmers. Perhaps it should say something like

- `z_1 = z_0 ...`, with subscripts
- `z_(n+1) = z_n ...`
- `z' = z ...`

**Comment by cespare** [comment]
Perhaps

![screen_20150619194926](https://cloud.githubusercontent.com/assets/318501/8265733/6871e3ba-16bc-11e5-8773-9c58c1c635d8.png)

http://www.texpaste.com/n/qwwh2txj
