### ISSUE TITLE
net/url: url.Parse allows spaces in the host.

### ISSUE THREAD

**Issue by crhino** [golang/go#11302]
http://play.golang.org/p/LqMUDBV17m

From my understanding of [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.2.2), spaces are not allowed in the host name. Any help clarifying whether this is intended behavior or not would be great.

**Comment by bradfitz** [comment]
Related, or dup: #11206

**Comment by rsc** [comment]
Accepting space seems like a mistake. Will try to not do that and see how much complaint we get.
