### ISSUE TITLE
 x/review: git mail not sending review to golang-codereviews

### ISSUE THREAD

**Issue by andybons** [golang/go#11300]
Using git mail to send out a change, it never reached golang-codereviews@googlegroups.com but the change was created in gerrit.
```bash
$ git mail -r nigeltao@golang.org -cc dvyukov@google.com
remote: Processing changes: new: 1, done    
remote: (W) 17536d4: commit subject >65 characters; use shorter first paragraph
remote: (W) 17536d4: too many commit message lines longer than 70 characters; manually wrap lines
remote: 
remote: New Changes:
remote:   https://go-review.googlesource.com/11256 image/gif: set default loop count to 0 when application extension is not present
remote: 
```

**Comment by josharian** [comment]
I believe that there is a moderation delay for the first mail by any given contributor; that might be what is going on here.

**Comment by andybons** [comment]
Gotcha. Thanks for the info.

**Comment by andybons** [comment]
Yep see it now. Closing.

**Comment by ianlancetaylor** [comment]
I wish we didn't need that moderation delay, but without it a rather annoying number of spam postings get through.  In general it should only apply to the first CL you send out.
