### ISSUE TITLE
x/mobile/cmd/gomobile: document resigning of iOS apps

### ISSUE THREAD

**Issue by rakyll** [golang/go#11301]
gomobile build is not honoring an Info.plist in a similar fashion it honors AndroidManifest.xml files. We have two options to improve this behavior:

* gomobile build honors Info.plist at build time.
* We document the process step by step how to unsign, modify and re-sign an .app file.

cc/ @crawshaw @hyangah @minux

**Comment by crawshaw** [comment]
My plan is to revisit long-lived xcode projects after completing the gomobile bind mode. There are an enormous number of app features, we cannot support them all. Giving users an out into their own project lets them keep configuration around.

**Comment by rakyll** [comment]
I support the idea of long-lived Xcode projects. My current workflow is:

- Use command line tool to generate an Xcode project. Update the project if there exists one.
- Switch to Xcode and press cmd+R.

We can even take it further to generate an Xcode with the necessary gomobile build steps for the Debug and Release configurations.

**Comment by rakyll** [comment]
Closing the issue, long-living Xcode project is the plan.
