### ISSUE TITLE
x/mobile/cmd/gomobile: -o flag must represent an output directory

### ISSUE THREAD

**Issue by rakyll** [golang/go#11311]
gomobile build will be supporting iOS builds soon, and this change will require a significant change in the tool. The -o is used to be a filename of the final output file.

```
gomobile build -o /path/to/example.apk .
gomobile build -o /path/to/example.aar .
```

With the merge of the iOS build support, we will building both an apk and app file if the source package is a main package. So, the -o flag must represent an output directory, so the tool can output both files.

cc/ @crawshaw @hyangah

**Comment by crawshaw** [comment]
With the new -target flag I'm trialling a semantics change, so the tool only builds for one platform at a time.

That said, I'm still trying to work out what to do with the header file for gomobile bind.

**Comment by rakyll** [comment]
Obsolete due to the target flag, closing.
