### ISSUE TITLE
tour: not clear why fmt.Println(Big) fails?

### ISSUE THREAD

**Issue by cclauss** [golang/go#11314]
Context: /basics/16

Describe your feedback here, including code if necessary
Why does `fmt.Println(Big)` fail?  It would be interesting to explain that in this exercise.

**Comment by kytrinyx** [comment]
The error message explains why it fails:

```
fmt.Println(needInt(Big))
// prog.go:19: constant 1267650600228229401496703205376 overflows int
```

Is the concept of _overflow_ unclear?

**Comment by adg** [comment]
Maybe we could add a parenthetical stating the range of integers an `int` can represent?

**Comment by kytrinyx** [comment]
That would work. I'll take this one.

**Comment by kytrinyx** [comment]
Can we do this without mentioning that `int` size is implementation-specific? Or should we just write it as though the int is an int64 (if we do the former, people with less programming experience might have that _eyes glazed over *this is hard*_ response, but if we do the latter, invariably someone will submit an issue pointing out that we're wrong.

**Comment by adg** [comment]
The size of int is discussed on the [basic types slide](http://tour.golang.org/basics/11) so we don't need to get fully into detail here. Maybe just mention that `int` can store at maximum a 64-bit integer?

**Comment by kytrinyx** [comment]
Oh, good idea.

**Comment by kytrinyx** [comment]
I forgot to reference the issue in the patch. This can be closed.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/tour/commit/459d92e21d28a6d9189af4ce917c4e92803ca357.
