### ISSUE TITLE
channels: performance gap

### ISSUE THREAD

**Issue by zx48** [golang/go#11316]
Run test with N = 1,2,3,4...
```go
package main

import (
    "fmt"
    "sync"
    "time"
)

var N = 1

type T interface{}

func main() {
    var wg sync.WaitGroup
    ch := make(chan T)
    wg.Add(1)
    go func() {
        defer wg.Done()
        test(ch)
    }() 
    for i := 0; i < N; i++ {
        ch <- 1
    }   
    close(ch)
    wg.Add(1)
    go func() {
        defer wg.Done()
        test(ch)
    }() 
    wg.Wait()
}

func test(ch chan T) T { 
    t := time.Now()
    var v T 
    var ok bool
    for i := 0; i < N; i++ {
        v, ok = <-ch
    }   
    fmt.Printf("%v, closed: %v\n", time.Since(t), !ok)
    return v
}
```
N = 1:
> 705ns, closed: false
> 360ns, closed: true

N = 2:
> ***6.393µs***, closed: false
> 324ns, closed: true

N = 3: (less than N = 2. Why?)
> ***2.397µs***, closed: false
> 384ns, closed: true

N = 4:
> ***7.476µs***, closed: false
> 423ns, closed: true

N = 5: (less than N = 4 and N = 2. Why?)
> ***3.132µs***, closed: false
> 510ns, closed: true

System spec:
> Linux 4.0.4-303.fc22.x86_64
> go1.4.2 linux/amd64

**Comment by bradfitz** [comment]
I don't think this is statistically significant. You only have a couple samples.

Also, no performance work is being done on the released Go 1.4 branch anymore. Please post any interesting benchmarks about Go 1.5 to the golang-nuts@ mailing list.
