### ISSUE TITLE
runtime: test/init1.go fails intermittently

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11321]
From recent windows-amd64-gce build log http://build.golang.org/log/e0fb4cbcfe62e0846cdc4cb783c8aba4df738c32 and http://build.golang.org/log/3be209581d566e94ce852eec9ff7762e0521d7b8

```
##### ../test
# go run run.go -- init1.go
exit status 1
allocated 1000 chunks of 1048576 and used  1082630144 memory
numGC went 0 to 0
panic: init1

goroutine 1 [running]:
main.init.1()
	C:/workdir/go/test/init1.go:44 +0x3f9
main.init()
	C:/workdir/go/test/init1.go:53 +0x47
exit status 2

FAIL	init1.go	1.150s
```

Alex

**Comment by aclements** [comment]
It's not impossible for this test to fail by chance. The concurrent GC should definitely have started when it checks the memstats, but whether or not it's finished depends on timing and the stats aren't updated until it finishes. My guess is we were right on the edge before and @RLH's change to add a second mark pass (90a1996) made the concurrent mark take a little too long for this test.

It's possible we should just add a sleep in test/init1.go if the GC hasn't finished yet. That would still accomplish the original intent of checking that GC can run during init, but would make the test less flaky.

@alexbrainman, do you know if you can reproduce this? Or is it just on the dashboard? If you can reproduce it, I'd love to see the output with GODEBUG=gctrace=1,gcpacertrace=1 (plus a sleep right before the panic so the GC has a chance to say something).

**Comment by alexbrainman** [comment]
I have seen that test on dashboard. I have never seen it here. I cannot make that test fails here. Maybe you have some special instructions ...

Alex

**Comment by rsc** [comment]
Happened again on windows-386.
https://storage.googleapis.com/go-build-log/e4a40c28/windows-386-gce_91398547.log

Austin, it seems to me that no matter how bad the timing is, there are only a few MB of live data here. Mutator assists should keep the GC from bloating the allocated heap all the way to 1 GB, no? If not, I think we may have a real problem.

**Comment by rsc** [comment]
Looks the same as #11677.

**Comment by rsc** [comment]
Dup of #11677
