### ISSUE TITLE
apt-get install failed

### ISSUE THREAD

**Issue by lbpierre** [golang/go#11323]
Hello,

For a few days, I cannot install golang with: `sudo apt-get install golang -y` 
`E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/golang/golang-go_1.2.1-2ubuntu1_amd64.deb  Hash Sum mismatch`

Is there a way to fix it ? Or is there an other way to install golang ?

thanks in advance

**Comment by bradfitz** [comment]
We don't manage Debian or Ubuntu packages. I would ask on golang-nuts or some Debian mailing list.

**Comment by bradfitz** [comment]
Or Ubuntu mailing list I guess.
