### ISSUE TITLE
cmd/compile: stupid shift if right shift

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11328]
Gc rejects to compile the following program:
```go
package a
var v = 0>>1000
```
saying:
```
stupid shift: 1000
```
gotype compiles it successfully.
Compilers should agree on whether it is a valid Go program or not.

on commit af817890aa7b628234075a6cb01a3a435fb8317d

**Comment by griesemer** [comment]
Compilers may restrict the permissible precision of constants. Per the spec http://tip.golang.org/ref/spec#Constants:

"Implementation restriction: Although numeric constants have arbitrary precision in the language, a compiler may implement them using an internal representation with limited precision. ..."

That said, right shifts should never be a problem (if the shift count is >= 64 the result is either 0 or -1). Considering this a compiler bug.

**Comment by josharian** [comment]
FWIW, quoting @rsc from https://github.com/golang/go/issues/9120#issuecomment-66100059:

> I have always assumed [the restriction on channel element size] was something like the "stupid shift"
errors, where if you have that big an element size you are probably doing something
wrong. The fact that it took this long for someone to report a problem suggests he was
right.

And this report came from a fuzzer, not a real program (I presume). Given all of that, I'm switching the milestone to Unplanned. Feel free to switch back if you feel strongly.

**Comment by griesemer** [comment]
I assigned the bug to myself and gave it a Go1.5Maybe because I think it's a trivial fix. Unplanned is fine, too, but I don't think it matters.

**Comment by griesemer** [comment]
The fix for this bug is trivial: it's deleting some unnecessary code. The math/big package can handle this case just fine. See my comments on  https://golang.org/cl/13777 .
