### ISSUE TITLE
net/http: HTTPS proxies support

### ISSUE THREAD

**Issue by ailg** [golang/go#11332]
net/http supports HTTP proxies, where HTTPS is achieved with CONNECT. It would be nice to add support for HTTPS proxies (https://www.chromium.org/developers/design-documents/secure-web-proxy), where the client first establishes a TLS connection to the proxy.

http://tip.golang.org/src/net/http/transport.go?#L754

```
// Note: no support to https to the proxy yet.
```

Maybe Transport.DialTLS (http://godoc.org/net/http#Transport) could be used for that. Currently it says:

```
// DialTLS specifies an optional dial function for creating
// TLS connections for non-proxied HTTPS requests.
```

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by athirn** [comment]
would love to see this as well
