### ISSUE TITLE
bytes: do a pointer equality check in cmpbody on arm, arm64, pcc

### ISSUE THREAD

**Issue by josharian** [golang/go#11336]
`eqstr` checks for pointer equality before looping over the body. `bytes.Compare` could do the same. The obvious question is whether this is a common enough case to warrant paying the price. I'm not sure how to gather data make this determination. Perhaps by instrumenting `bytes.Compare` and running some large, real-world code?

**Comment by randall77** [comment]
bytes.Compare does this check, at least for 386 and amd64.  Maybe the other archs need it?

**Comment by josharian** [comment]
Yep, missing only on arm, arm64, and pcc (in virtue of the fact that ppc doesn't have an asm byte.Compare).

arm64 also appears to be missing a pointer equality check in eqstring.

**Comment by davecheney** [comment]
The last one is almost certainly my fault.

I'd prefer to leave this til 1.6.

**Comment by davecheney** [comment]
The only one remaining is ppc64x, which doesn't have integrated bytes.Compare yet. 

@randall77 @minux what do you want to do ? Leave this issue open, or close it and remember this optimisation when someone gets around to doing bytes.Compare on ppc64 ?

**Comment by randall77** [comment]
Let's add a comment in runtime/noasm.go:Compare that assembly versions should do this optimization.  (Or maybe we could actually do the optimization in Go?)  Then anyone implementing ppc will know to do it, starting from either from the Go source or another arch's asm source.

**Comment by davecheney** [comment]
SGTM. I'll do it this week and close the issue.

FWIW is anyone planning on doing this for 1.6 ?
