### ISSUE TITLE
net: LookupIP("127.0.0.1") does not work when CGO_ENABLED=1

### ISSUE THREAD

**Issue by neild** [golang/go#11335]
```go
package main
import (
        "fmt"
        "net"
)
func main() {
        fmt.Println(net.LookupIP("127.0.0.1"))
}
```

```
$ go version
go version go1.4.2 linux/amd64
$ go run main.go
[127.0.0.1] <nil>

$ /tmp/g/go version
go version devel +e38bcb5 Wed Jun 17 18:17:50 2015 +0000 linux/amd64
$ /tmp/g/go run main.go
[] lookup 127.0.0.1: invalid domain name

$ uname -a
Linux kinoko.mtv.corp.google.com 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The net.LookupIP docs are unclear on what it does with IPs as opposed to hostnames, but changing the behavior seems wrong.

**Comment by mikioh** [comment]
I think this is expected behavior from go1.5, and a consequence of the new feature described in 4a0ba7aa171a80fe798811a3fdc7c42b83dcda01.

**Comment by bradfitz** [comment]
@ianlancetaylor, @rsc, any opinions on this? Apparently glibc lets you do a DNS lookup on an IP address? Is that part of the net.LookupIP contract? Do we care if this behavior changes?

**Comment by rsc** [comment]
It wasn't intended but I think it's probably worth keeping.

**Comment by rsc** [comment]
That is, we should keep the 1.4 behavior.

**Comment by bradfitz** [comment]
Easy enough. I assume we can just recognize IP literals (IPv4 or IPv6) and return them immediately, without regard to the system's nsswitch.conf or resolv.conf, etc. I hope that glibc isn't doing anything fancier? @mikioh, do you know?

**Comment by ianlancetaylor** [comment]
That is what glibc's getaddrinfo function does: it calls inet_aton on the name, and, if that succeeds, returns the result.
