### ISSUE TITLE
x/mobile/cmd/gomobile: build doesn't honor -target

### ISSUE THREAD

**Issue by rakyll** [golang/go#11337]
```
$ gomobile build -target=misc .
```

builds an apk for android rather than exiting with `unknown -target, misc.` error.

cc/ @crawshaw @hyangah

**Comment by crawshaw** [comment]
As the explanation was not added to the CL description, it is:

addBuildFlags is called multiple times at initialization, so the String method returns a different pointer for the different commands. That means the pointer is from the wrong flag set for all but the last registered command, which is cmdBind.
