### ISSUE TITLE
tour: code (left side) talks about "c" but explaination (right side) talks about "ch"

### ISSUE THREAD

**Issue by cclauss** [golang/go#11351]
Context: /concurrency/3

Describe your feedback here, including code if necessary

code (left side) talks about "c" but explaination (right side) talks about "ch"

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Proposed change: https://go-review.googlesource.com/#/c/12200/

**Comment by campoy** [comment]
Change merged and deployed (will need to reset slide to see changes in code)
