### ISSUE TITLE
cmd/compile: out of fixed registers

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11352]
The following program:
```go
package a
var a, b = 0, 0-^^^^^^^^^^a
```
crashes ```go tool compile``` with:
```
tmp.go:2: internal compiler error: out of fixed registers
```
go version devel +514014c Thu Jun 18 15:54:35 2015 +0200 linux/amd64

**Comment by tolchz** [comment]
https://go-review.googlesource.com/11308/

**Comment by rsc** [comment]
CL 13110 fixed this in the dev.ssa branch. It's not worth fixing in the current code.
