### ISSUE TITLE
cmd/compile: mis-calculates a constant

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11369]
For the following program:
```go
package main
var f = 7 / "0"[0]
```
```go tool compile``` says:
```
tmp.go:2: constant 1197 overflows byte
```

Now sure where 1197 came from, but it must be 0 and the program must compile successfully.

go version devel +514014c Thu Jun 18 15:54:35 2015 +0200 linux/amd64

**Comment by tolchz** [comment]
I've looked into this a bit, and that particular value is coming from gc.Umagic:

ord("0") = 48
Umagic(48) = 171 with shift of 5
7 * 171 = 1197

In gc.walkdiv there is different logic used depending on if the divisor is a power of two or now, so depending on the character, it sometimes works:

https://play.golang.org/p/m4lGOWIADg
