### ISSUE TITLE
tour: reader.Validate doesn't check for len being different from cap

### ISSUE THREAD

**Issue by daveFNbuck** [golang/go#11360]
Context: /methods/11

When trying the Reader exercise, I initially wrote the following code:

```
func (r MyReader) Read(buf []byte) (int, error) {
	for i, _ := range(buf) {
		buf[i] = 'A'
	}
	return cap(buf), nil
}
```

I later read the Reader spec and saw that I should actually be returning `len(buf)` rather than `cap(buf)`, but the Validate function didn't detect my error.

**Comment by justalfred** [comment]
`reader.Validate` also accepts `return $AN_INTEGER, nil`, where the integer is 4 or greater.

**Comment by kytrinyx** [comment]
I can take a look at this one, @adg.

**Comment by kytrinyx** [comment]
I think I'm missing another bit of crucial app engine knowledge.

I've got the tour checked out to `$GOPATH/src/golang.org/x/tour`, and I'm running the app with `/path/to/go_appengine/dev_appserver.py .` using the 1.9.27 release of the App Engine SDK. I'm able to access the slide at http://localhost:8080/methods/11

The code on the slide imports `golang.org/x/tour/reader`. When I change the `Validate()` function to something obviously wrong (e.g. `fmt.Println("NOT OK!"); return`) and then rerun the program, I still get `"OK!"` as the output. This also happens after restarting the development app server.

I came across some very old references that mentioned that the app engine SDK wasn't aware of workspaces, but that seems to have been fixed for well over two years now (https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath).

Did something get compiled to a cache somewhere that I should be clearing out?

**Comment by minux** [comment]
I think the app engine version always uses the Go playground service at
play.golang.org, so changing the local tour packages won't work.

**Comment by adg** [comment]
@minux is right. Sorry for the confusion there! You need to run `gotour` locally to use your local tool chain for compilation.

**Comment by kytrinyx** [comment]
Thanks for clarifying. I've made an attempt at explaining this in the CONTRIBUTING.md file here: https://go-review.googlesource.com/#/c/15907 -- I'm not actually sure I've got this right, though it seems to be working for me now.

**Comment by kytrinyx** [comment]
I've sent a CL that ensures a failure if the reader returns `cap(b)` rather than `len(b)`.

If they hard-code an integer value between 1 and 1024 (per @justalfred's comment above), then the Validate function will still pass. I'm not sure if it's important to fail in this case, because the cap/len confusion seems more likely than a hard-coded integer value.

**Comment by kytrinyx** [comment]
ping @adg would you have a moment to look at this?
