### ISSUE TITLE
build with odbc package fails for linux

### ISSUE THREAD

**Issue by cadamini** [golang/go#11378]
Since I use /code.google.com/p/odbc/ my program, my build fails for linux. 

***What version of Go are you using (go version)?***
go version go1.4.2 darwin/amd64

***What operating system and processor architecture are you using?***
Mac OSX

***What did you do?***
I was able to build my app before I have inserted the odbc package (code.google.com/p/odbc). Then I added the package and installed UnixODBC and FreeTDS.
 
***What did you expect to see?***
I thought go could compile binaries for Mac, Linux and Windows independent from the packages used.

***What did you see instead?***
I encountered the error message below when executing make.

**My terminal shows:**
GOARCH=amd64 GOOS=linux goop exec go build -ldflags "-X main.VERSION `cat VERSION` -X main.BUILD_DATE `date -u +%d.%m.%Y-%H:%M:%S`" -o /Users/cadamini/GoApps/connect-client/bin/linux-amd64/connect ./main.go
'# code.google.com/p/odbc/api
.vendor/src/code.google.com/p/odbc/api/api.go:13: undefined: SQLSMALLINT
.vendor/src/code.google.com/p/odbc/api/api.go:14: undefined: SQLUSMALLINT
.vendor/src/code.google.com/p/odbc/api/api.go:15: undefined: SQLUSMALLINT

Do I see a bug or is it just a configuration issue?

**Comment by alexbrainman** [comment]
code.google.com/p/odbc package uses cgo on linux (see api/api_unix.go). You cannot cross-compile packages that use cgo.

Alex

PS: code.google.com/p/odbc package is moved now to github.com/alexbrainman/odbc.
