### ISSUE TITLE
text/template: zero template.Template no longer safe for use

### ISSUE THREAD

**Issue by rsc** [golang/go#11379]
This program worked in Go 1.4 but crashes in Go 1.5.

	package main
	
	import "text/template"
	
	func main() {
		template.Must(new(template.Template).New("main").Parse(""))
	}

It dies in Parse because the overall group was created with new(template.Template) and has a nil *common pointer. Because this worked in Go 1.4, I think we should keep it working in Go 1.5. That might mean filling in common lazily.

**Comment by rsc** [comment]
Actually, I'll take this one since it's the middle of the night for Rob.

**Comment by mwhudson** [comment]
I think this is a dup of #11226 but as this has discussion I'll close that one
