### ISSUE TITLE
cmd/cover, x/tools/cover: Remember current file in Go Cover when reloading

### ISSUE THREAD

**Issue by tgrosinger** [golang/go#11388]
**Go Version:** 1.4.2 linux/amd64
**Operating System:** Ubuntu
**What did you do:** Run GoCover and view HTML report, switch file, then refresh page
**What did you expect:** Update the report with newest version, but remain on selected file
**What did actually happened:** Updated the report with newest version, but returned to alphabetically first file.

In the HTML UI for Go Cover, remember what page the user was viewing when the page is refreshed. This is useful when builds are being run automatically and the user wants to see what has changed in the coverage report.

This was [originally a discussion](https://groups.google.com/forum/#!topic/golang-nuts/AtR50qAcG-s) I started in the Golang-Nuts forum.

**Comment by tgrosinger** [comment]
Let me know if this issue belongs elsewhere. I didn't see a separate issue tracker for the `gocover` tool

**Comment by robpike** [comment]
Assigning to @adg, who wrote the UI. If it's easy to fix, that would be fine with me, but if it requires a lot of work it wouldn't be worthwhile.

**Comment by dherbst** [comment]
This appears to be resolved with https://github.com/golang/go/commit/98abf2937e42d560f0a8ba3c9e5bd5351c5316e6 in go1.6.   Nice!
