### ISSUE TITLE
cmd/go: SSL: certificate verification failed

### ISSUE THREAD

**Issue by MarcoDeBortoli** [golang/go#11404]
I was trying to download some tools via go-plus for atom but without success so I tried to run the command manually and this is the output I'm getting:
```bash
$ go get -u golang.org/x/tools/cmd/cover
# cd .; git clone https://go.googlesource.com/tools /usr/local/opt/go/src/golang.org/x/tools
Cloning into '/usr/local/opt/go/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': SSL: certificate verification failed (result: 5)
package golang.org/x/tools/cmd/cover: exit status 128
```
It works fine on another Mac OSX with pretty much the same specs. Any ideas or pointer? Thanks a lot for your help.

**Comment by mikioh** [comment]
What happens when you run "git clone https://go.googlesource.com/tools" on the node?

**Comment by MarcoDeBortoli** [comment]
@mikioh same.

**Comment by bradfitz** [comment]
Please include information in bug reports that would be facilitate debugging. For example:

OS X version?
Go version?
Git version?
Where did you get git from? And Go from? Some packaging system?

Can you run `curl https://go.googlesource.com/tools` without an SSL warning?

**Comment by MarcoDeBortoli** [comment]
Not needed anymore. I just found the problem. I have the following entry in my `.gitconfig` because at 
work we use ithub enterprise, so I think we should call it a pebkac :(

```
[http]
    sslcainfo = /Users/marco.debortoli/.certs/enterprise.crt
    sslverify = true
```

**Comment by MarcoDeBortoli** [comment]
Sorry for opening an almost useless issue and thanks for the help.
