### ISSUE TITLE
cmd/go: scp syntax marked insecure

### ISSUE THREAD

**Issue by zombiezen** [golang/go#11401]
On go tip (751eef83e0), git remotes that are in the scp syntax (`user@server:path/to/repo.git`) are marked as insecure.  Since these use SSH, it should be marked as secure.  In inspecting the source, `ssh://` doesn't appear to be marked as secure, either.

**Comment by zombiezen** [comment]
I should note I'm working on a patch for this.

**Comment by rsc** [comment]
Fixed by CL 11514.
