### ISSUE TITLE
cmd/go: vendoredImportPath invalid on windows

### ISSUE THREAD

**Issue by chai2010** [golang/go#11409]
```
go run hello.go
invalid vendoredImportPath: dir="D:\\apps\\go\\gopkg\\src\\mydev\\hello\\a" root="d:\\apps\\go\\gopkg" separator="\\"

// dir="D:\\...", root="d:\\..."

go version
go version devel +3cab476 Sun Jun 21 03:11:01 2015 +0000 windows/amd64

go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\apps\go\gopkg
set GORACE=
set GOROOT=d:\apps\Go\gotip
set GOTOOLDIR=d:\apps\Go\gotip\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**Comment by chai2010** [comment]
This is patch will fix the issue:
https://go-review.googlesource.com/#/c/11316/

**Comment by chai2010** [comment]
```
go get github.com\chai2010\tiff
cd github.com\chai2010\tiff\testdata\issues
go run issues-10596.go

invalid vendoredImportPath: dir="C:\\go\\gopkg.stable\\src\\github.com\\chai2010\\tiff\\testdata\\issues" root="." separator="\\"
```

**Comment by pragmat1c** [comment]
Leaving this here for anyone else who comes across this issue.

I had to set this in system.env:

GO15VENDOREXPERIMENT=1

Commenting that line and saving system.env however produces this output:

C:/Go/bin/go.exe env [C:\Go\]
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\work\code\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
Command exited with code 0.

Notice that 
set GO15VENDOREXPERIMENT=1 
is still set.

You have to change the line in system.env:

GO15VENDOREXPERIMENT=0

This fixes the problem for me on Windows 10.
