### ISSUE TITLE
net: doesn't refer to the kernel state kern.ipc.soacceptqueue on FreeBSD 10 and beyond

### ISSUE THREAD

**Issue by mikioh** [golang/go#11412]
See https://lists.freebsd.org/pipermail/svn-src-head/2012-October/041326.html.

On FreeBSD 10 and beyond, kern.ipc.somaxconn is replaced with kern.ipc.acceptqueue for clarification.

**Comment by stevenh** [comment]
As there is no plans to remove the old (now hidden) sysctl I don't see any reason this should be done as it would just add clutter.

Given that I would close this, if it does get removed in the future it can be address then.
