### ISSUE TITLE
net/http: test timeouts on dashboard

### ISSUE THREAD

**Issue by aclements** [golang/go#11418]
Very recently, the dashboard has been sprinkled with test timeouts from net/http:

http://build.golang.org/log/ee751b24f32d3c3ac1b3669f53876b511c246cd9 (1045351, openbsd-amd64-gce56)
http://build.golang.org/log/be3b820d94c23442eb116333bd14867c889a7db5 (bf5e19f, linux-386-387)
http://build.golang.org/log/88373f9893aeb1272fdfae376493c06ea511c137 (895df14, linux-amd64-clang)
etc.

1045351 is the first failure and seems like a plausible cause, though the test isn't failing frequently enough to be sure it wasn't another recent net/http change.

**Comment by bradfitz** [comment]
I can reproduce on Linux with:

`$ go test -v -run=TestTransportAndServerSharedBodyRace -count=1000`

Looking.
