### ISSUE TITLE
gofmt should handle function parameter indentation properly

### ISSUE THREAD

**Issue by mattp16** [golang/go#11423]
Instead of this:

```
func DoSomething(
  arg1 string,
  arg2 int64,
  arg3 float64,
  arg4 bool) bool {
  var1 := 0
  var2 := ""
  ...
}
```

It should do this:

```
func DoSomething(
    arg1 string,
    arg2 int64,
    arg3 float64,
    arg4 bool) bool {
  var1 := 0
  var2 := ""
  ...
}
```

And yes, I know with this toy example I could just put all the arguments on one line.  But sometimes when using external type names which can be rather long, it is unavoidable.

**Comment by griesemer** [comment]
I recommend

```
func DoSomething(
	arg1 string,
	arg2 int64,
	arg3 float64,
	arg4 bool
) bool {
	var1 := 0
	var2 := ""
	...
}
```
Generally, indentation is done with tabs only. One could use two tabs in your suggestion but that seems odd (only place where indentation is changed in steps larger than 1). Using spaces is after a tab is unprecedented in gofmt.

Unfortunate.

**Comment by mattp16** [comment]
Sorry if my use of space in my examples was confusing ... that was merely trying to control how the result would show, since tabs don't always show up the same in different editors/browsers/etc.  I understand indentation is done with tabs only.  I was not suggesting using spaces instead.  I was just suggesting that function parameters to be indented more than the function body.  Why do you think that seems odd?  I believe this is very standard practice for most programming languages.  Examples:

https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Function_Declarations_and_Definitions
http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-136091.html#262

**Comment by griesemer** [comment]
I'm aware it's standard practice elsewhere. It's also standard practice to never indent with tabs - or in other words: "standard practice elsewhere" is not a compelling argument...

The formatting suggestion I offered does work and avoids the irregularity here - think of the parameter list as opening a scope: indeed, the parameters are part of the function's body scope, which is "temporarily opened", and then closed again (hence the outdent) for the result type, and the opened again (indent for body). It's very regular. It also works for named results, and it scales:

```
func DoSomething(
    arg1 string,
    arg2 int64,
    arg3 float64,
    arg4 bool,
) {
   res1 bool,
   res2 string,
   err error,
} {
    var1 := 0
    var2 := ""
    ...
}
```
By scaling I mean for instance:
```
func DoSomething(
    arg1 string,
    arg2 func(
        x int,
        y float64,
    ) bool,
    arg3 float64,
    arg4 bool,
) {
   res1 bool,
   res2 string,
   err error,
} {
    var1 := 0
    var2 := ""
    ...
}
```
Leaving closed for now.
