### ISSUE TITLE
fmt: Printf does not zero pad.

### ISSUE THREAD

**Issue by dajohi** [golang/go#11422]
The following code does not 0-pad on tip.  It does work expected with 1.4.2, see http://play.golang.org/p/A7oXWwj5s_

`$ go version`
`go version devel +a1cc84f Fri Jun 26 09:53:36 2015 +0000 openbsd/amd64`

```go
package main

import (
        "fmt"
        "math/big"
)

func main() {
        value := []byte{
                0x89, 0x6c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        }
        targetDifficulty := new(big.Int).SetBytes(value)

        fmt.Printf(" got: %064x\n", targetDifficulty.Bytes())
        fmt.Printf("want: 0000000000000000896c00000000000000000000000000000000000000000000\n")
}
```

```
 got: 896c00000000000000000000000000000000000000000000
want: 0000000000000000896c00000000000000000000000000000000000000000000
```

**Comment by griesemer** [comment]
Confusing example - there's no need to involve math/big. But you're right, tip appears to be wrong. On the playground: http://play.golang.org/p/pnJg1u_z2K:
```
package main

import "fmt"

func main() {
	fmt.Printf("%08x\n", []byte{1})
}
```
we get:
```
00000001
```
On tip we get:
```
01
```

**Comment by robpike** [comment]
Given 
	fmt.Printf("%04x\n", []byte{0xab})
	fmt.Printf("% 04x\n", []byte{0xab})
	fmt.Printf("%04x\n", []byte{0xab, 0xbc})
	fmt.Printf("% 04x\n", []byte{0xab, 0xbc})

1.4 does this:

00ab
00ab
abbc
ab bc

while tip does this:

ab
ab
abbc
ab bc


Both are wrong. The root bug is original; the change in behavior applies because of a fix at tip that, coincidentally, propagates the original bug.

I will fix.

**Comment by robpike** [comment]
I was mistaken; there has been a regression from 1.4, where the output was correct:

00ab
00ab
abbc
ab bc

At issue is whether the width and flags apply elementwise or to the whole, and the answer is: width: whole; flags, elementwise. And this must be consistent for []byte and for string when using this format.

The CL listed here restores and explains the behavior.
