### ISSUE TITLE
cmd/go: variable built-in of "go generate"

### ISSUE THREAD

**Issue by noliar** [golang/go#11438]
I think $GOARCH and $GOOS in "go generate" should depend on the environment variable first, like other go commands.

**Comment by adg** [comment]
I can confirm:

```
$ cat gen.go 
package test

//go:generate echo $GOOS
$ go generate gen.go
darwin
$ GOOS=linux go generate gen.go
darwin
```

The code in `cmd/go/generate.go` uses `runtime.GOARCH` and `runtime.GOOS` for these values. It should probably use the values from the `buildContext` global variable.
