### ISSUE TITLE
go get seems to require Hg on Windows, git not sufficient

### ISSUE THREAD

**Issue by buchs-kevin** [golang/go#11444]
Running on Win7 with latest Go installation and I have git installed. When I try to run **go get**, I get an error message saying that Mercurial is not installed. The documentation to which the error message refers indicates that git is one of the available source code control options. Here is the transcript:

> C:\Users\buchs\Documents\Programming\Go>go get code.google.com/p/go-imap/go1/imap
> go: missing Mercurial command. See http://golang.org/s/gogetcmd
> package code.google.com/p/go-imap/go1/imap: exec: "hg": executable file not found in %PATH%                                                                                     
> 
> C:\Users\buchs\Documents\Programming\Go>git                                             
> usage: git [--version] [--help] [-C <path>] [-c name=value]                             
> ...

**Comment by buchs-kevin** [comment]
Once I installed Mercurial, the *go get* command succeeded.

**Comment by Thomasdezeeuw** [comment]
That is because code.google.com/p/go-imap work with Mercurial rather then Git. So you need Mercurial (Hg) to get the source code. Go can't do without Mercurial in this case.

**Comment by buchs-kevin** [comment]
This page https://github.com/golang/go/wiki/GoGetTools is worded to suggest that having one of the tools is sufficient. It should be reworded.

**Comment by bradfitz** [comment]
Updated, not that I think it's necessary.

**Comment by buchs-kevin** [comment]
Don't you wonder who should be the judge of necessity of clarity of documentation: an experienced user who maintains the documentation or a new user who depends upon the accuracy of the information on the documentation?
