### ISSUE TITLE
cmd/go: cannot use 'go run' with code depending on TERM variable

### ISSUE THREAD

**Issue by osocurioso** [golang/go#11449]
Trying to 'go run' the demos from the github.com/nsf/termbox-go library panics because the 'dumb' terminal as set by $GOROOT/src/cmd/go/env.go is not recognized.

```
run-getenv$ uname -p -o -v -r
3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 GNU/Linux
run-getenv$ echo $TERM
xterm
run-getenv$ curl http://play.golang.org/p/miGq22cTZ_ > main.go
run-getenv$ go run main.go
dumb
run-getenv$ go build && ./run-getenv
xterm
```

I would expect 'xterm' to be output in both cases.

The override of the TERM environment variable was introduced in commit c485b5891273c62af8e2342c72edf717966d97b7 to avoid escape codes from clang. Is this still necessary?

**Comment by ericwq** [comment]
~~~go
$ uname -a
Darwin wangs-MacBook.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
$ go version
go version go1.5rc1 darwin/amd64
~~~

if you run the following simple test
~~~go
func TestTermEnv(t *testing.T) {
    fmt.Printf("%s\n",os.Getenv("TERM"))
}
~~~

the result will be: 
~~~go
$go test
dumb
~~~

**Comment by ianlancetaylor** [comment]
@ericwq This issue was about "go run".  Please open a separate issue for "go test".  It's less clear what to do for that case, if anything.  Thanks.
