### ISSUE TITLE
go/types: whence this constant value?

### ISSUE THREAD

**Issue by josharian** [golang/go#11455]
I [attempted](https://github.com/golang/lint/commit/b55059174c9f0cda51e7a12038ba79644d158bf3) and [ultimately failed](https://github.com/golang/lint/commit/4946cea8b6efd778dc31dc2dbeb919535e1b7529) to write a [lint check](https://github.com/golang/lint/issues/130) that analyzed `time.Duration` constants, to ensure that they were defined using a unit (that is, like `3 * time.Second`, not like `3e9`).

The crux of the issue was being able to identify, for a constant expression, where/how its components were defined.

For example, given:

```go
const (
  a = iota
  b
  c = b * 2
  d = c * time.Second
  e = d - 1
)
```

I'd like to be able to trace from `e` all the way back to the other expressions from which `e`'s value is derived. This might extend across files and packages. As far as I can tell, there's no reasonable way to get this information now. But this information must be available during typechecking.

This is not a high priority, and there are obviously API questions. Just putting this on the wishlist. :)

/cc @griesemer @alandonovan

**Comment by alandonovan** [comment]
On 28 June 2015 at 23:23, Josh Bleecher Snyder <notifications@github.com>
wrote:

> I attempted
> <https://github.com/golang/lint/commit/b55059174c9f0cda51e7a12038ba79644d158bf3>
> and ultimately failed
> <https://github.com/golang/lint/commit/4946cea8b6efd778dc31dc2dbeb919535e1b7529>
> to write a lint check <https://github.com/golang/lint/issues/130> that
> analyzed time.Duration constants, to ensure that they were defined using
> a unit (that is, like 3 * time.Second, not like 3e9).
>
> The crux of the issue was being able to identify, for a constant
> expression, where/how its components were defined.
>
> For example, given:
>
> const (
>   a = iota
>   b
>   c = b * 2
>   d = c * time.Second
>   e = d - 1
> )
>
> I'd like to be able to trace from e all the way back to the other
> expressions from which e's value is derived. This might extend across
> files and packages. As far as I can tell, there's no reasonable way to get
> this information now. But this information must be available during
> typechecking.
>
> This is not a high priority, and there are obviously API questions. Just
> putting this on the wishlist. :)
>

I responded on the 'ultimately failed' bug ticket, but I think the general
answer here is: the type checker API provides you with all the building
blocks you need, and it cannot provide more without (a) redundancy and (b)
sacrificing the ability to load packages without source code.

If you're still stuck next week, we can work on it together at GopherCon if
you like.

**Comment by josharian** [comment]
Thanks, that's very useful. I think I see the way forward.
