### ISSUE TITLE
net: provide mechanism to force DNS via cgo

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11450]
We should probably provide a mechanism in Go 1.5 to let users force the use of cgo/libc for DNS resolution. I'm afraid the pure Go solution will have problems for some users, and saying "modifying your nsswitch.conf or resolv.conf to be 'complicated enough'" isn't a great answer.

So, two questions:

1) should we do this?  (I think yes)
2) which mechanism? env var? build tag? (I'm undecided).

/cc @pmarks-net @mikioh @ianlancetaylor @rsc

**Comment by pmarks-net** [comment]
If we're talking about #10552, then I think an environment variable would be more useful than a compile-time option, because often the people affected will not be the application developers.

That said, it's better to ship a correct algorithm, than an incorrect one with an easy workaround.

**Comment by bradfitz** [comment]
@rsc had reservations about an environment variable. My first version of the CL used an environment variable, but it's now a build tag.

**Comment by bradfitz** [comment]
@rsc says:
> if we need an explicit environment signal, can we reuse GODEBUG instead of adding a new one? GODEBUG=netdns=1 for tracing, GODEBUG=netdns=cgo for cgo, and GODEBUG=netdns=cgo+1 for cgo and tracing?
