### ISSUE TITLE
cmd/go: bad stack in reported import failure

### ISSUE THREAD

**Issue by rsc** [golang/go#11456]
I'm seeing a lot of reports about the go command reporting a problem, in which the import stack is completely bogus. For example, #11307.

In addition to fixing the reported problems, we should figure out why the import stacks are terrible and fix them.

**Comment by jscrockett01** [comment]
Relevant comment from #11307:

Regarding the inaccurate import stacks, there is a missing stk.pop() in func download() of src/cmd/go/get.go, between lines 233-234 (go1.5beta1) corresponding to the stk.push() at line 192.  Also, the stk.push/pop pair at lines 225-227 are extraneous.

**Comment by rsc** [comment]
I fixed the problem with the stack in #11307 as part of the fix for that bug.
In the absence of another example, closing this.
