### ISSUE TITLE
cmd/pprof: add --insecure flag to fetch from https endpoints with self signed certificates

### ISSUE THREAD

**Issue by roberthbailey** [golang/go#11468]
Right now the output looks like:

```
go tool pprof https://host:port/debug/pprof/profile
Fetching profile from https://host:port/debug/pprof/profile
Please wait... (30s)
http fetch https://host:port/debug/pprof/profile: Get https://host:port/debug/pprof/profile: x509: certificate signed by unknown authority
```

It would be awesome to be able to pass a --insecure option (like when using curl) so that you don't need to add the self signed certificate to the system's trusted root certificate store to collect profiles. 

/cc @bradfitz

**Comment by calavera** [comment]
FWIW I just submitted a change to fix this issue: https://go-review.googlesource.com/20885 :smile_cat:
