### ISSUE TITLE
cmd/compile/ssa: reconsider polymorphic comparison ops

### ISSUE THREAD

**Issue by josharian** [golang/go#11467]
@dr2chase expressed concern in CL 11452 that polymorphism in the generic ops would be a source of bugs and an impediment to writing useful optimizations. Once SSA has progressed and stabilized a bit and we have more experience with it, take a second look.

**Comment by randall77** [comment]
I think this is a reasonable idea.  It leads to more redundant machine-independent rewrites, but that's not a huge deal.

The question is - are types still important in this scenario?  Can we drop them?  I'd have to think more about that one...
