### ISSUE TITLE
runtime: move delayed stack free after start-the-world

### ISSUE THREAD

**Issue by aclements** [golang/go#11465]
Currently we perform delayed stack frees during mark termination while the world is stopped. As far as I can tell, there's no reason this needs to be done with the world stopped (except possibly for statistics), so we should move it after the world is started again. It does need to be done before we start another GC cycle, so it should probably be done before releasing the worldsema.

@RLH

**Comment by RLH** [comment]
I agree this should be done but unless it shows a big improvement can it
wait for 1.6. Splay or garbage with 16 or 32G heaps would be a good place
to see if this is a win.

**Comment by aclements** [comment]
> I agree this should be done but unless it shows a big improvement can it wait for 1.6. 

Yes. It's marked Go1.6Early since it should wait for 1.6, but needs to be done before the 1.6 freeze.

**Comment by rhysh** [comment]
I have a process that when running with GOMAXPROCS=18 spends 7.5% of its CPU cycles in runtime.gcMark -> runtime.freeStackSpans. This work is not parallelized, so the wall clock time spent in runtime.freeStackSpans accounts for significantly more than 7.5% of my program's mark termination times. More details on my program are in #12967, but the gist is that it sees mark termination times well in excess of 10ms while running with 100k goroutines and 500MB of heap.
