### ISSUE TITLE
x/tools/go/present: .backdrop image feature

### ISSUE THREAD

**Issue by griesemer** [golang/go#11470]
Feature suggestion: There's already the .image mechanism to get a picture up in present. It would be nice to have an image be the backdrop for a slide.

For instance, a "command" .background which does exactly what .image does, but instead it shows the text on top of it? Then, by sizing an image large enough, it could be the backdrop of a slide.

I think that could make present a lot more powerful (though appropriate choice of backdrops one could basically get "themes", etc. yet still keep the simplicity of use).

Perhaps there's a way to choose one backdrop for all slides, or for individual slides.

**Comment by avelino** [comment]
+1

**Comment by avelino** [comment]
+1

**Comment by adg** [comment]
@avelino we don't do +1's on our issue tracker. Your enthusiasm has been noted. Thank you. :-)
