### ISSUE TITLE
net: windows TestDialTimeout flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11474]
Noticed this flake:
http://build.golang.org/log/de2ea0b431bc216003fd8762e62bbd46b3511fca

```
...
ok  	math/rand	5.305s
ok  	mime	1.365s
ok  	mime/multipart	2.470s
ok  	mime/quotedprintable	3.075s
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:82: #3: dial tcp 127.0.0.1:0: connectex: The requested address is not valid in its context.
FAIL
FAIL	net	21.902s
ok  	net/http	10.666s
ok  	net/http/cgi	6.718s
ok  	net/http/cookiejar	1.583s
...
```

/cc @alexbrainman @mikioh

**Comment by alexbrainman** [comment]
I run the test 100 times. It never breaks. The error is WSAEADDRNOTAVAIL.

Alex

**Comment by bradfitz** [comment]
Did you run all the net tests, or just that one? Maybe there are interactions with other tests in the package.

**Comment by alexbrainman** [comment]
I run "go test -short" in a loop now. No errors.

Alex

**Comment by rsc** [comment]
Closing. If it happens again, reopen.

**Comment by mikioh** [comment]
This is a duplicate of #11872.
