### ISSUE TITLE
cmd/compile/ssa: broken build due to racewalk/recover interaction

### ISSUE THREAD

**Issue by josharian** [golang/go#11471]
CL 11238 ("Handle variables correctly") broke the SSA build.

CL 11681 adds some diagnostics and extra checks for it.

The problem appears to be that, when compiling a function including a call to `recover` with the race detector enabled, `nodfp` in the call to `gorecover` does not match `nodfp` at the time that the SSA backend is invoked.

As a result, s.addr(nodfp) returns nil, but values cannot have nil args. Breakage ensues.

I don't know what the right fix is. Leaving for @randall77.

**Comment by josharian** [comment]
Maybe CL 11713 will fix this?

**Comment by josharian** [comment]
No, CL 11713 did not fix this.

**Comment by randall77** [comment]
Is this still an issue?  I suspect not.  Please reopen if you think otherwise.
