### ISSUE TITLE
x/codereview/git-codereview: rewrite "Fixes issue ..." to "Fixes ..."

### ISSUE THREAD

**Issue by josharian** [golang/go#11472]
One of the most common sources of failure to autoclose issues is contributors writing `Fixes issue #1234` instead of `Fixes #1234`, possibly due to ingrained Rietveld habits. It would be nice if GitHub recognized that phrase, but in the meantime, it'd be very easy to automatically detect and correct.

**Comment by pongad** [comment]
I'd like to work on this. Since this will be my first contribution, it might take me a while though. I'll dive the code; should I send preliminary design to golang-dev?

**Comment by ianlancetaylor** [comment]
This seems simple enough that from our point of view you don't need to send a design to golang-dev.  Of course feel free to do so if you would like advice.
