### ISSUE TITLE
doc:  golang documentation for gccgo repository incorrect

### ISSUE THREAD

**Issue by laboger** [golang/go#11486]
The golang documentation on contributing to gccgo contains the wrong repository:

http://golang.org/doc/gccgo_contribute.html#tmp_2

It has recently changed from hg to git.

**Comment by adg** [comment]
cc @iant

**Comment by mwhudson** [comment]
http://tip.golang.org/doc/gccgo_contribute.html#tmp_2 is better, is there a process for updating the docs at golang.org for this sort of thing?

**Comment by adg** [comment]
It'll be updated when Go 1.5 is released.

**Comment by laboger** [comment]
Until then there is no documentation to identify where to find the 
gofrontend repository.
