### ISSUE TITLE
runtime: No stack trace during TestRaiseException 

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11481]
My recent change 85d4d46 seems broke windows-amd64-2003kardianos builder. It fails with http://build.golang.org/log/deaefba240a4cdb9c5b650fda53570b43560cbf9
```
--- FAIL: TestRaiseException (0.52s)
	syscall_windows_test.go:507: No stack trace: 
FAIL
FAIL	runtime	44.328s
```

I cannot reproduce the problem here. This little program always prints stacktrace:
```
c:\dev\src\t>type main.go
package main

import "syscall"

func main() {
        const EXCEPTION_NONCONTINUABLE = 1
        mod := syscall.MustLoadDLL("kernel32.dll")
        proc := mod.MustFindProc("RaiseException")
        proc.Call(0xbad, EXCEPTION_NONCONTINUABLE, 0, 0)
        println("RaiseException should not return")
}

c:\dev\src\t>go run main.go
Exception 0xbad 0x76850000 0x76e28521 0x7fefd3c9e5d
PC=0x7fefd3c9e5d

syscall.Syscall6(0x7685cf10, 0x4, 0xbad, 0x1, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc082007ce0, ...)
        c:/dev/go/src/runtime/syscall_windows.go:139 +0x5c
syscall.(*Proc).Call(0xc0820045e0, 0xc082029f00, 0x4, 0x4, 0xc0820100b8, 0x0, 0x0, 0x0)
        c:/dev/go/src/syscall/dll_windows.go:136 +0x5f7
main.main()
        c:/dev/src/t/main.go:9 +0xc4
rax     0x358ad209
rbx     0xc082029da8
rcx     0x6f750
rdi     0x7fffffde000
rsi     0xc082029df0
rbp     0x0
rsp     0x6fd60
r8      0x0
r9      0x0
r10     0x46cc40
r11     0x0
r12     0x2
r13     0x4999bc
r14     0x8
r15     0x0
rip     0x7fefd3c9e5d
rflags  0x206
cs      0x33
fs      0x53
gs      0x2b
exit status 2

c:\dev\src\t>
```

It would be nice to understand what is going on. @kardianos maybe you can debug this if you have time. Thank you.

Alex

**Comment by kardianos** [comment]
I feel like I'm guessing and checking, but... If you effectively revert https://go-review.googlesource.com/#/c/8165 , that is use _AddVectoredContinueHandler on XP amd64 then this test works again. Maybe previously one of the callbacks was getting overwritten? Although that begs the question why _SetUnhandledExceptionFilter stopped working.

Note: can't do a clean revert as some of the logic has moved from os1_windows.go to signal_windows.go.

Let me know if I can help do something to try to pin the source of the failures down more. Thanks for noticing this.
-Daniel

**Comment by alexbrainman** [comment]
Thank you for trying. Like you say, I don't understand why 85d4d46 suddenly broke the test. Perhaps I will try and find pc similar to yours - 64 bit with older windows version - and try to understand myself.

Alex

**Comment by kardianos** [comment]
@alexbrainman If I modify syscall_getprocaddress I can get it to pass again. Still not a root cause. However if "c" is of type libcall and not *libcall in syscall_getprocaddress then it passes. So:
```
func syscall_getprocaddress(...) {
	// passes
	c := getg().m.syscall
	...
	cgocall(asmstdcallAddr, unsafe.Pointer(&c))


	// fails
	c := &getg().m.syscall
	...
	cgocall(asmstdcallAddr, unsafe.Pointer(c))
}
```

I'll see if I can understand more from here. Continuing to post progress, as time for this is intermittent.
-Daniel

**Comment by kardianos** [comment]
Also, if I put "print("")" anywhere in syscall_getprocaddress it will work correctly.  And by correctly, I mean the lastcontinuehandler func will be called resulting in the dump.

I think the next step would be for me to try to understand how the compiler is assembling the function and see the difference.

**Comment by alexbrainman** [comment]
> ... If you effectively revert https://go-review.googlesource.com/#/c/8165 , that is use
> _AddVectoredContinueHandler on XP amd64 then this test works again.

Do you mean this change
```
diff --git a/src/runtime/signal_windows.go b/src/runtime/signal_windows.go
index b2fce53..b1ebd77 100644
--- a/src/runtime/signal_windows.go
+++ b/src/runtime/signal_windows.go
@@ -28,7 +28,7 @@ func lastcontinuetramp()
 func initExceptionHandler() {
 	major, _ := getVersion()
 	stdcall2(_AddVectoredExceptionHandler, 1, funcPC(exceptiontramp))
-	if _AddVectoredContinueHandler == nil || unsafe.Sizeof(&_AddVectoredContinueHandler) == 4 || major < 6 {
+	if _AddVectoredContinueHandler == nil || unsafe.Sizeof(&_AddVectoredContinueHandler) == 4 {
 		// use SetUnhandledExceptionFilter for windows-386 or
 		// if VectoredContinueHandler is unavailable or
 		// if running windows-amd64 v5. V5 appears to fail to
```
makes src/all.bat pass on your computer?

> If I modify syscall_getprocaddress I can get it to pass again. Still not a root cause.
> However if "c" is of type libcall and not *libcall in syscall_getprocaddress then it passes.

I cannot explain that, but I really don't know what the problem is. When data corruption, anything is possible.

> ... if I put "print("")" anywhere in syscall_getprocaddress it will work correctly.

Same. Small changes here or there can change result a lot. We need to understand what the problem is.

> ... I think the next step would be for me to try to understand how the compiler is assembling the function and see the difference.

I have no plan. My first idea is to poke at the executable of the program above with gdb. Maybe I can see something odd. The problem with using gdb here is that the way exception handlers work changes when gdb in play - so it is hit and miss. I am still looking for a computer with windows xp 64bit on it. I have some plan about that. Hopefully I will have some soon.

Alex

**Comment by kardianos** [comment]
Yes, that change will make all.bat pass.

Agree. Feels like some lower level data corruption. It may have been the root cause of the _AddVectoredContinueHandler not working previously for all I know, as now it seems to work. That is to say, I doubt your recent change was the cause, just what tickled it again.

Lastly, we could be tickling a windows bug differently each time as it appears only on XP/2003 64-bit. I have doubts about that option, but we should hold it in mind.

I could give you access to the builder through a tunneled rdp if you'd like. Let me know and I'll send you an email with specifics.

**Comment by alexbrainman** [comment]
Thanks for the offer, but not yet. I am building small rig here, I will see if I can make the test break. I will let you know if my attempts are fruitless..

Alex

**Comment by alexbrainman** [comment]
I can reproduce this on windows xp 64 bit. Now I just need to understand why it is happening.

Alex

**Comment by alexbrainman** [comment]
@kardianos I am out of ideas. I suggest we revert  https://go-review.googlesource.com/#/c/8165 and, if it works on your builder, we forget this whole thing until it bites us next time.

What do you think?

Alex

**Comment by kardianos** [comment]
Yeah, go ahead and revert, especially to try to turn the builder green;
amd64 should be using that method anyway. My one concern is that on Windows
7 I recently ran into an issue where I was using lxn/walk and it was
crashing without a dump or trace of any kind (running tip). I'm not sure if
it is the same issue or not, but it does concern my that I didn't get a
dump of any kind. I'll see if I can get a test case for that.

**Comment by kardianos** [comment]
@alexbrainman What's the difference (on the stack or registers) between stdcall5 and stdcall1? If I put in a stdcall5 above the cgocall(...) function (it must be above that function) then it works. But that doesn't work with stdcall1.

This feels like maybe we are running out of stack or something in the cgo call... Maybe?

**Comment by kardianos** [comment]
Lastly, also in syscall_getprocaddress, if c.n is set to 5 (not 2), it also
works. Does that just push more values onto the stack?

**Comment by alexbrainman** [comment]
> ... My one concern is that on Windows
> 7 I recently ran into an issue where I was using lxn/walk and it was
> crashing without a dump or trace of any kind (running tip). I'm not sure if
> it is the same issue or not, but it does concern my that I didn't get a
> dump of any kind.

You cannot expect stack trace every time. Sometimes, if memory gets corrupted, runtime won't be able to print stack trace. It depends on the bug. lxn/walk has not been updated for a while, and Go runtime changed a bit since then.

> ... I'll see if I can get a test case for that.

Having reproducible testcase is always helpful. Except this issue ... :-)

> ... What's the difference (on the stack or registers) between stdcall5 and stdcall1?

For amd64, see runtime·asmstdcall in sys_windows_amd64.go. One major difference is that for stdcall5 we store parameters on stack as well as in registers.

> ... If I put in a stdcall5 above the cgocall(...) function (it must be above that function) then it works. But that doesn't work with stdcall1.

I don't understand you. Please try again.

> ... also in syscall_getprocaddress, if c.n is set to 5 (not 2), it also works. Does that just push more values onto the stack?

See my answer above. Are you're saying that one line change in syscall_getprocaddress fixes the problem?
Send me the diff and I will try it tonight.

Alex

**Comment by kardianos** [comment]
There are two ways to revert to the previous behavior:
```
diff --git a/src/runtime/syscall_windows.go b/src/runtime/syscall_windows.go
index 8e069cd..2d22992 100644
--- a/src/runtime/syscall_windows.go
+++ b/src/runtime/syscall_windows.go
@@ -103,6 +103,12 @@ func syscall_loadlibrary(filename *uint16) (handle, err uintptr) {
        return
 }

+var fdh uintptr
+
+func init() {
+       fdh = stdcall1(_GetStdHandle, ^uintptr(10))
+}
+
 //go:linkname syscall_getprocaddress syscall.getprocaddress
 //go:nosplit
 func syscall_getprocaddress(handle uintptr, procname *byte) (outhandle, err uintptr) {
@@ -110,6 +116,7 @@ func syscall_getprocaddress(handle uintptr, procname *byte) (outhandle, err uint
        c.fn = getGetProcAddress()
        c.n = 2
        c.args = uintptr(noescape(unsafe.Pointer(&handle)))
+       stdcall5(_WriteFile, fdh, 0, 0, 0, 0)
        cgocall(asmstdcallAddr, unsafe.Pointer(c))
        outhandle = c.r1
        if outhandle == 0 {
```

or

```
diff --git a/src/runtime/syscall_windows.go b/src/runtime/syscall_windows.go
index 8e069cd..218108d 100644
--- a/src/runtime/syscall_windows.go
+++ b/src/runtime/syscall_windows.go
@@ -108,7 +108,7 @@ func syscall_loadlibrary(filename *uint16) (handle, err uintptr) {
 func syscall_getprocaddress(handle uintptr, procname *byte) (outhandle, err uintptr) {
        c := &getg().m.syscall
        c.fn = getGetProcAddress()
-       c.n = 2
+       c.n = 5
        c.args = uintptr(noescape(unsafe.Pointer(&handle)))
        cgocall(asmstdcallAddr, unsafe.Pointer(c))
        outhandle = c.r1
```

However in both cases they cause the current exception handler to work and cause the _AddVectoredContinueHandler to stop working.

...

Has the go team published guidelines for interacting with cgo memory, especially in windows? I've heard talk of that but haven't seen anything, and I lack the understanding to derive it unfortunately.

**Comment by alexbrainman** [comment]
> There are two ways to revert to the previous behavior:

I will try your second version tonight. Are you saying it fixes your problem at current tip on your builder?

> However in both cases they cause the current exception handler to work and cause the _AddVectoredContinueHandler to stop working.

I noticed that too while debugging. I don't have explanation for that.

> ... Has the go team published guidelines for interacting with cgo memory, especially in windows? I've heard talk of that but haven't seen anything, and I lack the understanding to derive it unfortunately.

I am not sure what you're after. Generally if outside code uses Go memory, Go runtime needs to be aware of that. And it is not "cgo memory" - we don't use cgo here - function names in runtime have cgo names because windows uses some similar procedures to cgo. If you have some particular questions, I will try and answer.

Here https://go-review.googlesource.com/11888 is my proposal. Let me know if it fixes build on your builder.

Alex

**Comment by kardianos** [comment]
Yes, n =5 will fix builder at tip.

Yes, that cl will fix the builder.

**Comment by alexbrainman** [comment]
Thank you for testing.

Alex

**Comment by alexbrainman** [comment]
I can fix the test with n=5. But I am nowhere closer to the resolution here. The only good idea I have left is to step throughout Windows code with gdb or any other debugger. That should provide the explanation of what is happening here (why lastcontinuetramp, which is set by SetUnhandledExceptionFilter, is not called). But I have never done it before - not sure how big this job is. Perhaps we should leave it alone for now.

Alex

**Comment by kardianos** [comment]
Hi @alexbrainman ,

I'm fine making the builder green for now, even if we don't have a final solution.

One thing I noted was that in file sys_windows_amd64.s TEXT runtime·asmstdcall there is a fast and slow execution path. The fast path requires 3 or fewer arguments (store in registers) and a slow path (store in stack). If I raise it to say 5 or more, for the n=5 "fix" to work, I also have to raise that to ensure it takes the slow path as well.

That begin said, it doesn't matter that *that* call write to the stack, as I can preceded the call with a different syscall that takes 5 arguments that writes to the stack. But perhaps these subtle changes just mess with Windows' ability to see the callstack. Apparently if Windows can't decode the callstack, it just swallows the exception. This is also behavior that was changed in Windows 7+, thus we only see this issue with XP x64.

After reading more on windows exception handling I don't think there is go stack corruption causing this. 
Submit https://golang.org/cl/11888 and let's move on for now. Maybe don't mark this issue as fixed though.

References:
http://cbloomrants.blogspot.com/2011/11/11-09-11-weird-shite-about-exceptions.html

http://blog.paulbetts.org/index.php/2010/07/20/the-case-of-the-disappearing-onload-exception-user-mode-callback-exceptions-in-x64/

https://support.microsoft.com/en-us/kb/973460

**Comment by alexbrainman** [comment]
> The fast path requires 3 or fewer arguments (store in registers) and a slow path (store in stack).

4 or less (not 3 or fewer).

>  If I raise it to say 5 or more, for the n=5 "fix" to work, I also have to raise that to ensure it takes the slow path as well.

While trying to debug, I have removed "fast version" completely. It did not change broken test or anything else.

> But perhaps these subtle changes just mess with Windows' ability to see the callstack. Apparently if Windows can't decode the callstack, it just swallows the exception. This is also behavior that was changed in Windows 7+, thus we only see this issue with XP x64.

I agree. My current belief is that there is some subtle thing we create in our process environment that makes Windows exception handling to change dramatically - SetUnhandledExceptionFilter works and AddVectoredContinueHandler does not, or SetUnhandledExceptionFilter does not work and AddVectoredContinueHandler works. Perhaps it is something to do with the fact that we don't provide any "stack unwind" information, and Windows exception handler struggles.

I also hope that this is Windows XP 64bit only struggle.

> Maybe don't mark this issue as fixed though.

We can always open new or reopen this.

Alex

**Comment by alexbrainman** [comment]
The fact that using gdb also tickles how Windows exception handler works, makes this even more difficult to debug.

Alex

**Comment by kardianos** [comment]
@alexbrainman One link appeared to suggest windows will swallow any exception when it couldn't unwind the stack. Maybe we are intermittently triggering that check. Yeah, Windows acts differently under a debugger in this case. Agree, close, we can always reopen.
Here's to a clean build!
