### ISSUE TITLE
database/sql: confusing documentation for DefaultParameterConverter

### ISSUE THREAD

**Issue by johto** [golang/go#11489]
Hi,

In the [documentation for DefaultParameterConvert](https://golang.org/pkg/database/sql/driver/) we have this passage (emphasis mine):

DefaultParameterConverter returns the given value directly if IsValue(value).
Otherwise integer type are converted to int64, floats to float64, and **strings to
[]byte**. Other types are an error.

However, if we look at the [code](https://github.com/golang/go/blob/f11109fbc93bf2f31b5a948cc29c920b31184011/src/database/sql/driver/types.go#L180), even [all the way back to 1.0](https://github.com/golang/go/blob/08b97d4061dd75ceec1d44e4335183cd791c9306/src/pkg/database/sql/driver/types.go#L180) IsValue has returned true for `string`.  Thus, I don't see how a string could ever be converted to []byte.

Am I misreading this, or is the documentation incorrect?

**Comment by chakrit** [comment]
@johto I think that was meant to catch stuff like `type MyStr string` ?

**Comment by chakrit** [comment]
@johto http://play.golang.org/p/3jRNZpgqBV

**Comment by chakrit** [comment]
I get `[]byte` all the time whenever I have a special cased string type (such as those for enums or values that need special treatment like phone numbers or emails.)

**Comment by johto** [comment]
Oh, so it's about the *underlying type* when the type returns false for IsValue().  Can we make it explicitly say that?

**Comment by ianlancetaylor** [comment]
CC @bradfitz
