### ISSUE TITLE
tour: missing earlier exercises link

### ISSUE THREAD

**Issue by duongphuhiep** [golang/go#11495]
Context: /methods/9

The page said that
"Copy your Sqrt function from the earlier exercises and modify it to return an error value."

Please make "earlier exercises" a hyper link!
I want to do this exercises, but cannot find the "earlier exercises"

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Proposal: https://go-review.googlesource.com/12718

please review

**Comment by campoy** [comment]
Change merged and deployed
