### ISSUE TITLE
x/mobile/cmd/gomobile: fails to compile (types.TypeString)

### ISSUE THREAD

**Issue by wjarek** [golang/go#11509]
I was trying to build gomobile from the tip and go get golang.org/x/mobile/cmd/gomobile fails to compile with this error 'src/golang.org/x/mobile/bind/gengo.go:376: cannot use pkg (type *types.Package) as type types.Type in argument to types.TypeString:
*types.Package does not implement types.Type (missing Underlying method)

Looking at: 

https://github.com/golang/tools/commit/997b3545fd86c3a2d8e5fe6366174d7786e71278#diff-a3b3e01a6877f510d37ff84ed5356341L33

I see that TypeString no longer takes a *Package as expected in gengo.go.

**Comment by nwswe** [comment]
+1 im hitting this issue as well.
