### ISSUE TITLE
strconv: Quote method that uses IsGraphic not IsPrint

### ISSUE THREAD

**Issue by robpike** [golang/go#11511]
The IsPrint method is of our own design and makes sense, but it means that ideographic languages using for instance U+3000, the ideographic space, quote badly.

There should be a variant, perhaps strconv.QuoteGraphic, that offers the distinction, or perhaps a more general method that allows a func to make the definition.

**Comment by robpike** [comment]
Is %+q available for doing this from fmt?

**Comment by rsc** [comment]
Should probably be QuoteToGraphic like existing QuoteToASCII.

**Comment by robpike** [comment]
There are no suitable flags available in Printf's %q verb, so without something awful and unprecedented like a double flag %#+q, this is the best we can do.
