### ISSUE TITLE
x/net/context: flaky TestLayersTimeout on windows

### ISSUE THREAD

**Issue by mikioh** [golang/go#11512]
It sometimes fails on both windows/386 and windows/amd64 regardless of go version.

https://build.golang.org/log/441ed9b623cebefcdf96c9f3ecde1161777250bb
https://build.golang.org/log/03be465eace4fc1d48978761b1e7a7b1a0a6bb58
https://build.golang.org/log/bd1c8741979da65dd2d9f3215251d2171c9871a1
https://build.golang.org/log/8d69aab579d02c38dcf9225e942b3c3df5639e5b

**Comment by Sajmani** [comment]
Fixed in https://github.com/golang/net/commit/96feaeba77cf39602ef031d22746c121afb100a7
