### ISSUE TITLE
Remove duplicated string copy in logger?

### ISSUE THREAD

**Issue by yancl** [golang/go#11515]
Do you think `short` is necessary here for 3 times string copy?,
Maybe we could just `file = file[i+1:]` ?
I issue this because it is in the `l.mu.Lock()`:)

```
https://github.com/golang/go/blob/master/src/log/log.go#L121
	if l.flag&(Lshortfile|Llongfile) != 0 {
		if l.flag&Lshortfile != 0 {
			short := file
			for i := len(file) - 1; i > 0; i-- {
				if file[i] == '/' {
					short = file[i+1:]
					break
				}
			}
			file = short
		}
```

**Comment by bradfitz** [comment]
That's not a copy of the string. There's no performance problem here and the code is more readable currently than the proposed alternative.

See http://research.swtch.com/godata and http://blog.golang.org/go-slices-usage-and-internals
