### ISSUE TITLE
gccgo: accepts invalid UTF-8

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11527]
gcc compiles the following program, while gc and go/types reject it:
```go
package G
//line \FF:8
```
(that \FF needs to be converted to actual FF byte)
gc and go/types say:
```
go.go:2:8: illegal UTF-8 encoding
go.go:2: illegal UTF-8 sequence ff 3a
```

Compilers should agree on validity of this program.

gcc version 6.0.0 20150702 (experimental) (GCC)

**Comment by dvyukov** [comment]
@paranoiacblack

**Comment by paranoiacblack** [comment]
Is this still a problem? gc and go/types also accept the above program so it seems all compilers agree on the validity of the program.

**Comment by dvyukov** [comment]
replace \ff with actual 0xff byte
