### ISSUE TITLE
math.pi isn't exit, may be typed incorrectly.

### ISSUE THREAD

**Issue by zuozc** [golang/go#11553]
Context: /basics/3

original source code:
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.pi)
}

issue: # command-line-arguments
/tmp/sandbox679643269/main.go:9: cannot refer to unexported name math.pi
/tmp/sandbox679643269/main.go:9: undefined: math.pi

math.pi should be changed to math.Pi as you may type it incorretly.

**Comment by dominikh** [comment]
Duplicate of #10774 and working as intended. See @minux's comment on the linked issue for why.

**Comment by zuozc** [comment]
@dominikh Thanks...Not very carefully to see all detail at right side:)
