### ISSUE TITLE
image/draw:Draw is slow on Paletted images

### ISSUE THREAD

**Issue by nicks** [golang/go#11550]
I've been investigating an issue where drawing Paletted images seems much slower than other types of image conversion.

AFAIK, it's drawing the image twice?
https://github.com/golang/go/blob/f9ed2f75c43cb8745a1593ec3e4208c46419216a/src/image/draw/draw.go#L178

It executes the "fast" `drawPaletted` image, then falls into the default case, and executes the "slow" drawing path? I think there's supposed to be a `return` there?

**Comment by bradfitz** [comment]
@nigeltao?

**Comment by nigeltao** [comment]
You're absolutely right. I'll send out a fix.

**Comment by nicks** [comment]
thanks Nigel! that was quick :dash:
