### ISSUE TITLE
x/tools/go/types: treats complex constant as integer

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11564]
gotype successfully compiles the following program:
```go
package a
var e,f = f^0i,0
```
while gccgo says:
```
go.go:2:12: error: incompatible types in binary expression
```

gccgo seems to be right, because 0i is imaginary literal.

on commit 997b3545fd86c3a2d8e5fe6366174d7786e71278

**Comment by dvyukov** [comment]
@ianlancetaylor @rsc @paranoiacblack

**Comment by griesemer** [comment]
Working as intended: 0i is an untyped complex constant that can be represented accurately as an int. Both go/types and gc agree with the spec. This is a gccgo bug.

See also #11563 .
