### ISSUE TITLE
tour: [local] No way to interrupt looped exercise from GUI

### ISSUE THREAD

**Issue by tkozik** [golang/go#11562]
Context: /flowcontrol/8

Sorry if this was reported already but quick search didn't yield anything resembling this problem

Description:
I pressed "format" button during exercise execution and console part of UI returned to "idle" state but program continued to run independently in the background causing my machine to overheat. Interrupt button would be nice. I ran gotour on OS X Yosemite if this makes any difference.

Thanks for all the hard work creating this fun concise language! :+1:

**Comment by adg** [comment]
@campoy there should be a 'kill' button on the tour interface in local mode. The playground infrastructure supports it.

**Comment by campoy** [comment]
Agreed, I added this to my todo list and will take care of it after gophercon.

**Comment by campoy** [comment]
Button Kill added with https://go-review.googlesource.com/#/c/12377/2

**Comment by campoy** [comment]
This is now live on tour.golang.org
