### ISSUE TITLE
Go fails to install on Solaris

### ISSUE THREAD

**Issue by ashwgupt** [golang/go#11571]
We have been trying to install GO and then logstash-forwarder on our Solaris Zone servers from source but the make.bash script fails saying it can't fine $HOME/go1.4/bin/go folder.

I don't see any such folder in src/ folder, from where am running make.bash (or all.bash) and wondering why is the script expecting that folder to be present.

Can anyone provide any fix to it?

Will be even better if someone has got the built binaries for GO and the Forwarder for Solaris for direct use.

**Comment by bradfitz** [comment]
See https://golang.org/s/go15bootstrap and let's move discussion to the golang-nuts@ mailing list, as this is not a bug.

You'll need to find build Go 1.4 first on Solaris to build 1.5, or bootstrap the Solaris 1.5 build from Linux, etc.
