### ISSUE TITLE
go/types: allows duplicate switch cases

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11578]
go/types accepts the following program:
```go
package a
func f() {
	switch 0 {
		case 0:
		case 0:
	}
}
```
While both gc and gccgo reject it with ```duplicate case 0 in switch```.
Compilers should agree on validity of this program.

on commit 997b3545fd86c3a2d8e5fe6366174d7786e71278

**Comment by griesemer** [comment]
Note that the spec doesn't specify that this is prohibited (but it should). See also #4524.

**Comment by griesemer** [comment]
https://go-review.googlesource.com/#/c/13285/
