### ISSUE TITLE
net: IP.{IsLinkLocalUnicast,IsLinkLocalMulticast,IsGlobalUnicast} false positives

### ISSUE THREAD

**Issue by thockin** [golang/go#11585]
I found this inspecting the code to understand the test.

http://play.golang.org/p/gXdT4o45uw

It looks like those methods are assuming that any IP they get is a 16 byte slice, but as far as I know a 4 byte slice is a valid IP.

**Comment by thockin** [comment]
Also panic()s if you pass an empty slice (e.g. net.ParseIP("garbage").IsLinkLocalUnicast())

**Comment by mikioh** [comment]
It's intentional; don't call any methods on a nil value of net.IP.

**Comment by thockin** [comment]
Thanks for the fix, looks clean to me.

**Comment by mikioh** [comment]
Also IsGlobalUnicast("255.255.255.255").
