### ISSUE TITLE
x/tools/cmd/stringer: does not find constants across multiple groups

### ISSUE THREAD

**Issue by josharian** [golang/go#11582]
Given input:

```go
package a

type Num int

// Small numbers
const (
	One Num = iota
	Two
)

// Big numbers
const (
	Fourteen Num = iota
	EleventyOne
)
```

stringer generates strings only for the first group:

```go
// generated by stringer -type=Num; DO NOT EDIT

package a

import "fmt"

const _Num_name = "OneTwo"

var _Num_index = [...]uint8{0, 3, 6}

func (i Num) String() string {
	if i < 0 || i+1 >= Num(len(_Num_index)) {
		return fmt.Sprintf("Num(%d)", i)
	}
	return _Num_name[_Num_index[i]:_Num_index[i+1]]
}
```

**Comment by robpike** [comment]
Not a bug. Also, working as intended.

Stringer turns numbers into names. In your example, One and Fourteen have the same value, Fourteen.String() == "One". There would be no way to disambiguate.

Try changing Fourteen to iota+2 and you'll see stringer is working fine.

Please reopen if I have misunderstood.

**Comment by josharian** [comment]
Oh right. I'd blame coffee but I don't drink any.

A warning/failure from stringer seems like it might reasonable in this case, but not urgent; leaving closed.
