### ISSUE TITLE
go/types: can shift complex numbers

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11594]
gotype successfully compiles the following program:
```go
package a
var a = complex64(1) << 2
```
gccgo also compiles it. gc rejects it saying:
```
invalid operation: complex64(1) << 2 (shift of type complex64)
```
Spec says that lhs of shift must be an integer.

**Comment by dvyukov** [comment]
@griesemer if my reading of the spec is correct, then we also need to file a bug on gccgo.

**Comment by griesemer** [comment]
This is clearly a go/types bug.

**Comment by griesemer** [comment]
The fix is trivial (one missing predicate check). Can safely go in for 1.5 as far as I am concerned.

https://go-review.googlesource.com/#/c/12045/

(includes tests).
