### ISSUE TITLE
cmd/compile: internal compiler error: getinarg: not a func int

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11596]
gc crashes on the following program:
```go
package n
func F(interface{int}){}
func s(){F(3)}
```
```
go.go:3: internal compiler error: getinarg: not a func int
```
go version devel +71832ff Fri Jul 3 21:39:04 2015 +0000 linux/amd64

**Comment by anthonycanino1** [comment]
This looked familiar to another issue that I submitted a patch for. The change was accepted (https://go-review.googlesource.com/#/c/13747/). I double checked, and that patch also fixes this issue.

I'm not sure what the right protocol is for officially closing this out, but I'm confident this is a non-issue now.

**Comment by minux** [comment]
Confirmed fixed.
