### ISSUE TITLE
x/mobile/app: building golang.org/x/mobile/app results in error

### ISSUE THREAD

**Issue by rabarar** [golang/go#11601]
# golang.org/x/mobile/app

In file included from src/golang.org/x/mobile/app/darwin_amd64.go:16:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:82:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:14:
/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:59:10: fatal error: 'SharedFileList/SharedFileList.h' file not found
# include <SharedFileList/SharedFileList.h>

```
     ^
```

1 error generated.

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by crawshaw** [comment]
@rabarar could you please add:
- the command you ran
- revision of Go
- revision of the x/mobile repository
- version of OS X

Thanks.

**Comment by eliasnaur** [comment]
Is this still a problem? If so, please provide the information about your setup and what you did to reproduce the error.

**Comment by changkun** [comment]
I think this issue is fully outdated. The app package works today. Close.
