### ISSUE TITLE
cmd/go,cmd/trace: document the trace command

### ISSUE THREAD

**Issue by robpike** [golang/go#11605]
go help testflag does not mention the -trace flag

The output of go tool trace -help is unhelpful:

Usage of 'go tool trace':
Given a trace file produced by 'go test':
	go test -trace=trace.out pkg

Open a web browser displaying trace:
	go tool trace [flags] pkg.test trace.out

Flags:
	-http=addr: HTTP service address (e.g., ':6060')

Also, shortly after the 1.5 release, there should be a blog post about the feature.

**Comment by dvyukov** [comment]
go help testflag does mention the -trace flag
I've tried to describe -trace everywhere where cpu and memory profiles are described.

go tool trace -help is roughly the same as to tool cover -help, except that trace has fewer flags than cover.

Is there anything else to fix?

**Comment by robpike** [comment]
I think it's all good now.

**Comment by prashantv** [comment]
Is there still plans to do a blog post on the trace tool? There's not much documentation on how to read the output from `go tool trace`.

**Comment by dvyukov** [comment]
@prashantv Do you mean the generated HTMLs?
There are still plans to write the blog, not nobody is actively working on this ATM.

**Comment by prashantv** [comment]
Yes, the generated HTML / SVGs. Hope to see the blog post soon!
