### ISSUE TITLE
x/mobile/bind: Should redirect logs to logcat

### ISSUE THREAD

**Issue by jamesshoebox** [golang/go#11613]
Libraries generated with `gomobile bind` used to have stdout/stderr redirected to Android's logcat.
After https://github.com/golang/mobile/commit/81444057629c7d095df98b4bdf5916362c07a149, this is no longer the case.

The functionality is in https://github.com/golang/mobile/blob/master/app/stdio_android.go. Can this be refactored to be useful for both apps and libraries?

**Comment by ianlancetaylor** [comment]
CC @crawshaw @hyangah

**Comment by crawshaw** [comment]
Fixed in golang/mobile@960fedd17.
