### ISSUE TITLE
tour: clarify "undefined math.pi"

### ISSUE THREAD

**Issue by thewhitetulip** [golang/go#11623]
Context: /basics/3

Describe your feedback here, including code if necessary

# command-line-arguments
/tmp/sandbox634642990/main.go:9: cannot refer to unexported name math.pi
/tmp/sandbox634642990/main.go:9: undefined: math.pi

**Comment by adg** [comment]
Please read the slide. This is intentional.

**Comment by josharian** [comment]
This gets filed a lot. Perhaps we should tweak the slide; as written, it clearly loses some people.

**Comment by adg** [comment]
Yep.

**Comment by thewhitetulip** [comment]
Perhaps you can add in red highlights saying, 
>"This is not a bug"

**Comment by christopherhesse** [comment]
You could also have the original be math.Pi and then tell the user to change it to be math.pi

**Comment by sprstnd** [comment]
The slide is fine. It is teaching the user about exported names. The slide as-is is a great hands-on learning experience. After reviewing the entire page it should all make sense. I think this only trips those rushing through the tour. Maybe Bold the line 'Run the code. Then rename math.pi to math.Pi and try it again.'

**Comment by thewhitetulip** [comment]
As a person who rushed through the tour without reading the slides I agree to adding a bold statement stating that see how Go throws errors and then change it to math.Pi and run it again.

**Comment by kytrinyx** [comment]
I'll take this one.
