### ISSUE TITLE
Go 1.4.2 ldflags -s still shows the line numbers of the stack trace

### ISSUE THREAD

**Issue by FlashKnight** [golang/go#11622]
<h4>What platform did I use for test:</h4>
Microsoft Windows 7 x86 , go 1.4.2 windows x86

<h4>What code did I use for test:</h4>
    // test
    package main

    func main() {
	    panic("golang")
    }

<h4>What command did I use for complier the test program:</h4>
    go build -ldflags "-s -w" test.go

<h4>What am I expected to see :</h4>
    Should not print the line number in the stack trace.

<h4>What exactly did the complier show:</h4>
    panic: golang

    goroutine 1 [running]:
    main.main()
            D:/Users/lenovo/Desktop/test.go:5 +0x54
    ...

<h5>So... Is it designed to always shows the line numbers ?</h5>
<h5>There may be security reason that some projects may needs to hide or strip some unexpected printing messages. So I just curious :smile: </h5>

**Comment by davecheney** [comment]
-s does not strip line number information. 

-s is not tested and is not recommended as it is know to produce broken executables on multiple platforms.

**Comment by FlashKnight** [comment]
OK , I get it . I think this should be add into the golang document , as I was looking for some ideas to block the whole debugging messages
