### ISSUE TITLE
doc: Release notes 1.5: "go tool compile" - is that native only or x-compile too?

### ISSUE THREAD

**Issue by tolonuga** [golang/go#11638]
http://tip.golang.org/doc/go1.5

Compiler and tools

Independent of but encouraged by the move to Go, the names of the tools have changed. The old names 6g, 8g and so on are gone; instead there is just one binary, accessible as go tool compile, that compiles Go source into binaries suitable for the architecture and operating system specified by $GOARCH and $GOOS. Similarly, there is now one linker (go tool link) and one assembler (go tool asm). The linker was translated automatically from the old C implementation, but the assembler is a new native Go implementation discussed in more detail below.

Similar to the drop of the names 6g, 8g, and so on, the output of the compiler and assembler are now given a plain .o suffix rather than .8, .6, etc.

-> I would find it useful if you can point out: does the compiler only target the native plattform, or will "go tool compile" target all plattforms go supports or ... ? As 3 commands gets replaced with one, it is not clear what that one command can exactly do.

**Comment by robpike** [comment]
The section on the compiler says, "Its target is configured by the environment variables GOOS and GOARCH."

Seems clear enough to me.
