### ISSUE TITLE
build: satisfy API checker

### ISSUE THREAD

**Issue by glycerine** [golang/go#11636]
OSX 10.10.2 amd64, bootstrap with go1.4.2.

On building go1.5beta1 from source tarball, I get an error during the build:

~~~
~/pkg/go1.5beta1/src $ time ./all.bash
time ./all.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /Users/jason/pkg/go1.4.2/go.
bootstrap/internal/obj
bootstrap/asm/internal/flags
...
meteor-contest
pidigits
threadring
chameneosredux
        8.57 real        10.37 user         1.84 sys

##### ../test/bench/go1
testing: warning: no tests to run
PASS
ok      _/Users/jason/pkg/go1.5beta1/test/bench/go1 1.663s

##### ../test

##### API check
Error running API checker: exit status 1
Go version is "go1.5beta1", ignoring -next /Users/jason/pkg/go1.5beta1/api/next.txt
+pkg archive/zip, method (*Writer) SetOffset(int64)
+pkg bufio, method (*Reader) Discard(int) (int, error)
...
+pkg unicode, var Multani *RangeTable
+pkg unicode, var Old_Hungarian *RangeTable
+pkg unicode, var SignWriting *RangeTable
exit status 1
2015/07/08 23:03:05 Failed: exit status 1

real    7m32.789s
user    12m54.353s
sys 3m8.521s
jason@jasonsmac ~/pkg/go1.5beta1/src $ 
~~~

**Comment by tbogdala** [comment]
I also got the same error building go1.5beta1 on Ubuntu 15.04 x86_64 bootstrapping with go1.4.2 that was built from source as well.

My log also ended the same:

    +pkg unicode, var Multani *RangeTable
    +pkg unicode, var Old_Hungarian *RangeTable
    +pkg unicode, var SignWriting *RangeTable
    exit status 1
    2015/07/09 10:35:16 Failed: exit status 1

**Comment by fcourchesne** [comment]
Same here as well on go1.5beta1 using Arch Linux x86_64, kernel 4.0.7-2. Bootstrapping from go1.4.2 that was built from source.

**Comment by tbogdala** [comment]
Cloning https://go.googlesource.com/go and checking out master gave me a passing build, for what it's worth.

**Comment by tpng** [comment]
Same error running Go 1.5beta1 all.bat on Windows 386, bootstrapped from Go 1.4.2 Windows 386.
```
+pkg unicode, const Version = "8.0.0"
+pkg unicode, var Ahom *RangeTable
+pkg unicode, var Anatolian_Hieroglyphs *RangeTable
+pkg unicode, var Hatran *RangeTable
+pkg unicode, var Multani *RangeTable
+pkg unicode, var Old_Hungarian *RangeTable
+pkg unicode, var SignWriting *RangeTable
exit status 1
2015/07/10 10:53:14 Failed: exit status 1
```

**Comment by adg** [comment]
cc @bradfitz @robpike

**Comment by robpike** [comment]
Looks like the 1.5 beta has the Unicode 8 but next.text doesn't know about it. It's there at tip, so the next beta or release candidate should resolve this.
