### ISSUE TITLE
proposal: less strict rules about the syntax

### ISSUE THREAD

**Issue by ShearOfDoom** [golang/go#11632]
Currently in Go, the placement of brackets and such, is very strict. For example, the following code block works.

    func main() {
        fmt.Println("Hello world!")
    }

But, the below example doesn't.

    func main()
    {
        fmt.Println("Hello world")
    }

There are other examples of this, for example, required trailing commas, like this:

    // Compiles fine
    a := map[string]int {
        "a": 1,
        "b": 2,
        "c": 3,
    }

    // Doesn't compile
    a := map[string]int {
        "a": 1,
        "b": 2,
        "c": 3
    }

This proposal would also allow for more lenient rules on `if`/`else if`/`else` statements. For example, instead of being required to do it like this:

    if( ... ) {

    } else {

    }

One could write it like the below.

    if( ... ) {

    }
    else {
    
    }

My proposal is to change quirky features like this, and make them not required.

**Comment by adg** [comment]
What are the benefits of your proposal?

Keep in mind that `gofmt` would just revert the proposed syntax back to its original form, so the benefits would be local and  short-lived.

The benefits of the status quo are uniformity and a simpler grammar.

**Comment by adg** [comment]
Previously discussed in #416

**Comment by ianlancetaylor** [comment]
This isn't going to happen.  1) As Andrew says, it's not necessary with gofmt.  2) It leads us in the direction of Javascript's semicolon handling, which is generally considered to be a disaster.

I'm going to close this, but it could be reopened if necessary.
