### ISSUE TITLE
image/jpeg: Regression from 1.4.2: invalid JPEG format: bad RST marker

### ISSUE THREAD

**Issue by ulfnielsen** [golang/go#11650]
Decoding the attached image will return "bad RST marker" using go version devel +bd45bce Wed Jul 8 01:20:02 2015 +0000 darwin/amd64

Decoding with 1.4.2 works just fine. And I haven't seen any other jpeg decoder fall over on this one.

![icc_profile_test_image_farbkreis_120grad](https://cloud.githubusercontent.com/assets/703773/8612739/aafdd3d2-26d5-11e5-9523-6cb40bf63437.jpg)

**Comment by bradfitz** [comment]
Nigel?

**Comment by nigeltao** [comment]
Yes, I am working on a fix.
