### ISSUE TITLE
go/types: int overflow in switch expression

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11667]
gotype successfully compiles the following program:
```go
package a
func f() {
	switch 9223372036854775808 {
	}
}
```

gc rejects it with:
```
go.go:3: constant 9223372036854775808 overflows int
```

gc seems to be right.

on commit af817890aa7b628234075a6cb01a3a435fb8317d

**Comment by dvyukov** [comment]
The same happens in switch cases as well:
```go
package a
func f() {
    switch 9223372036854775808 {
    case 9223372036854775808:
    }
}
```

**Comment by griesemer** [comment]
The switch statement is actually underspecified in this respect. It does not say that the switch expression has to fit into a basic type. So technically, I believe gotype is correct. That said, I think the spec needs to be clarified as the current situation is not tenable in general. Leaving as go/types bug.
