### ISSUE TITLE
go/types: complex(0, 0i) should be permitted

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11669]
gc successfully compiles the following program:
```go
package a
var e = complex(0, 0i)
```
while gotype rejects it with:
```
invalid argument: 0i (untyped complex constant 0) must be a float32, float64, or an untyped non-complex numeric constant
```
go version devel +9b04852 Sat Jul 11 00:08:50 2015 +0000 linux/amd64

**Comment by dvyukov** [comment]
+ @griesemer for spec treatment

**Comment by griesemer** [comment]
I believe this is a go/types bug. 0i is untyped and can be represented as a float32 or float64. The spec could be clearer.

**Comment by griesemer** [comment]
Closed by mistake. Reopening.
