### ISSUE TITLE
Fmt.Printf() on float64 is not accurate

### ISSUE THREAD

**Issue by jvehent** [golang/go#11660]
The following code returns bogus results

```go
package main

import (
	"fmt"
)

var nums []float64 = []float64{
	18446744073709551616,
	18446744073709551615,
	18446744073709551613,
	18446744073709551600,
	99999999999999999,
}

func main() {
	for _, num := range nums {
		fmt.Printf("%%.0f:\t%.0f\n", num)
		fmt.Printf("%%v:\t%v\n---\n", num)
	}
}
```

output:
```
%.0f:	18446744073709551616
%v:		1.8446744073709552e+19
---
%.0f:	18446744073709551616
%v:		1.8446744073709552e+19
---
%.0f:	18446744073709551616
%v:		1.8446744073709552e+19
---
%.0f:	18446744073709551616
%v:		1.8446744073709552e+19
---
%.0f:	100000000000000000
%v:		1e+17
```
I have not identified the source of the issue yet, but these conversion errors are causing bugs in my code. Am I using `fmt` wrong or is this an issue with either the `fmt` or `strconv` packages?

**Comment by mdempsky** [comment]
18446744073709551616, 18446744073709551615, 18446744073709551613, and 18446744073709551600 are all equal after conversion to float64 due to limited precision.

**Comment by jvehent** [comment]
So the float64 has a precision of 53 bits only?

**Comment by mdempsky** [comment]
Simplifying, yes.  It's the IEEE-754 "double-precision" format: https://en.wikipedia.org/wiki/IEEE_754-1985#Double_precision
