### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile int fails with status 2

### ISSUE THREAD

**Issue by gedw99** [golang/go#11672]
Its not finding the go root dir, even though its set in the environment variables.

i am using the latest go mobile repo.

gedw99-MacBook-Pro:gomobile apple$ gomobile init
gomobile: go install std for android/arm failed: exit status 2
go: cannot find GOROOT directory: /usr/local/go

go version go1.5beta1 darwin/amd64

gedw99-MacBook-Pro:gomobile apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/Workspace/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Workspace"
GORACE=""
GOROOT="/Users/apple/go"
GOTOOLDIR="/Users/apple/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by crawshaw** [comment]
The gomobile tool is, for historical reasons, ignoring any custom GOROOT setting. Explicitly setting the GOROOT variable is strongly discouraged, so I haven't seen this before. At this point it is safe to pass it through, so I'll send a CL to do that.

However, I am a little bit surprised by the behavior of the Go 1.5 beta. Downloading the darwin/amd64 version and putting it anywhere other than /usr/local/go does not go well:

```
$ export PATH=$PATH:$HOME/go1.5beta/bin
$ go env
go: cannot find GOROOT directory: /usr/local/go
```

It's not clear to me if this should work.

**Comment by gedw99** [comment]
i have 1.4 and 1.5, depending on what i am hacking on. 
I just modify my bash profile, and point to the go folder i need.

so thats why i do it this way.

its weird that gomobile does not respect the env variables. i mean thats hte point of them and the whole go conventions all working together

**Comment by gedw99** [comment]
### GoLang 1.4.2 Paths setup ############################################

#export GOROOT=/usr/local/go1.4
#export PATH=$PATH:$GOROOT/bin
#export GOPATH=$HOME/Workspace
#export GOROOT_BOOTSTRAP=$GOROOT


### GoLang 1.5 (the tip) Paths setup ############################################
# working setup notes: http://studygolang.com/articles/2549

export GOROOT_BOOTSTRAP=$HOME/go1.4

export GOROOT=$HOME/go
export GOPATH=$HOME/Workspace
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin:$GOBIN

**Comment by crawshaw** [comment]
There were once good reasons for ignoring the user's setting of GOROOT, but those no longer apply. I'll send a CL soon.

**Comment by gedw99** [comment]
thanks
