### ISSUE TITLE
dev.ssa: opt pass doesn't correctly mark dead code

### ISSUE THREAD

**Issue by randall77** [golang/go#11676]
```go
package main

var x int

func f_ssa() {
	if true {
		return
	}
	for i := 0; i < 5; i++ {
		x = 5
	}
}
```

The loop block is dead.  The opt pass, which detects that the loop is dead, doesn't completely fix up the ssa graph, the exit block still has a phi with an argument from the dead code.  This causes deadcode to barf on it.

@josharian @bradfitz

**Comment by josharian** [comment]
Fixed by CL 12091.
