### ISSUE TITLE
x/net/publicsuffix: EffectiveTLDPlusOne() parses domains incorrectly if there is a trailing dot

### ISSUE THREAD

**Issue by bramp** [golang/go#11686]
```go
d, _ := publicsuffix.EffectiveTLDPlusOne("foo.bar.golang.org")
fmt.Printf("%s\n", d)

d, _ = publicsuffix.EffectiveTLDPlusOne("foo.bar.golang.org.")
fmt.Printf("%s\n", d)
```
prints
```
golang.org
org.
```

In the 2nd example, the domain has a trailing dot. This is valid, as it indicates this is unambiguous FQDN. I was passing output from DNS records into EffectiveTLDPlusOne when I noticed this issue.

I suggest the EffectiveTLDPlusOne ignores the trailing dot if one exists.

```bash
$ go version
go version go1.4.2 darwin/amd64
```

**Comment by crawshaw** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
FWIW, http://golang.org/pkg/net/http/cookiejar/#PublicSuffixList already says "TODO: specify which of the caller and callee is responsible for... leading and trailing dots". So, yes, it's a known issue. See also #7125. Possibly also related is issue #7122.

**Comment by bramp** [comment]
Thanks @crawshaw and @nigeltao. Sorry I didn't find the previous bug, feel free to close this as a DUP of #7125. I will strip the trailing dot myself. I had already been lowercasing the domain, but not doing a great job of canonicalising the domain otherwise.

**Comment by nigeltao** [comment]
Duplicates #7125.

(No need to apologize).
