### ISSUE TITLE
misc/cgo: testso fails when repo is not on OS volume

### ISSUE THREAD

**Issue by josharian** [golang/go#11681]
On one of my (less used) machines, I have my hard drive partitioned into multiple OS volumes and one data volume. The Go repo is on the data volume. As a result, misc/cgo/testso fails:

```
##### ../misc/cgo/testso
# command-line-arguments
/Volumes/Data/src/go/pkg/tool/darwin_amd64/link: /Volumes/Data/src/go/pkg/tool/darwin_amd64/link: rename(/var/folders/pp/0010hzld5b12h_92j5th082r0000gn/T/go-link-294538680/go.combined, main.exe) failed: rename /var/folders/pp/0010hzld5b12h_92j5th082r0000gn/T/go-link-294538680/go.combined main.exe: cross-device link
2015/07/11 21:06:03 Failed: exit status 2
```

**Comment by ianlancetaylor** [comment]
This is in Darwin-specific code introduced originally in https://go-review.googlesource.com/10284.  It calls os.Rename but needs to fall back to copying.

CC @ribrdb
