### ISSUE TITLE
release tarballs should not extract to the current working directory

### ISSUE THREAD

**Issue by gagomes** [golang/go#11688]
Release tarballs should be created with a base directory pertaining to Go, e.g go-release-1.4 or something to this extent that won't run the risk of overwriting overlaping files in the current working dir.

What actually happens when I extract the 1.4 release tarball:
```
$ tar tfz release-branch.go1.4.tar.gz
.gitattributes
.gitignore
.hgignore
.hgtags
AUTHORS
CONTRIBUTORS
LICENSE
PATENTS
README
VERSION
api/
api/README
api/except.txt
api/go1.1.txt
api/go1.2.txt
api/go1.3.txt
api/go1.4.txt
api/go1.txt
api/next.txt
doc/
(...)
```

**Comment by crawshaw** [comment]
I agree, but these archives are not under our control. These are generated by github. Please file a feature request with github support.

(The ones that we make can be found on golang.org/dl, and they have a base directory.)

**Comment by gagomes** [comment]
@crawshaw 

I'm referring to this one tarball https://go.googlesource.com/go/+archive/release-branch.go1.4.tar.gz linked from: https://go.googlesource.com/go/+/release-branch.go1.4

I understand these tarballs may be obtained from github, but they don't look like it. Also, I have just done a quick check and all the github released tarballs are correct, unlike the ones above. e.g they create a go-<tag> directory with all the contents inside.

**Comment by crawshaw** [comment]
Ah interesting, thanks for the correction.

Those tarballs are still not generated by the Go team, they come out of either gitiles or gerrit, I'm not sure which. I believe this is the particular issue: https://code.google.com/p/gitiles/issues/detail?id=3 which states "The details of the archive that produces aren't set in stone yet (e.g., I'd like to make project-revision.tar.gz prefix pathnames of its entries with project-revision/)." I suggest chiming in there.

**Comment by gagomes** [comment]
@crawshaw 

Thanks for digging into this further. I'll follow up in the issue linked above.
