### ISSUE TITLE
tour: explain evaluation order in /flowcontrol/7

### ISSUE THREAD

**Issue by soniabhishek** [golang/go#11684]
Context: /flowcontrol/7

Describe your feedback here, including code if necessary
in this example i cant understand the output in order
27 >= 20
9 20
because normal flow would be like
9
27>=20
20
because the first print statement is not generating it

**Comment by ALTree** [comment]
Both the calls to `pow` are evaluated before the call to `fmt.Println`, that why the `27 >= 20` output is the first one you see.

In generale, in `foo( baz( ), bar( ) )` both `baz( )` and `bar( )` are fully evaluated before `foo` is called, including side effects (like a `printf` call in `bar( )`).

**Comment by ALTree** [comment]
p.s. The issue tracker is for issues. For questions like this, you should write to the mailing list (https://groups.google.com/forum/#!forum/golang-nuts)

**Comment by soniabhishek** [comment]
Sorry but i wrote it as feedback to community so that this concept can be illustrated on this page itself

**Comment by rsc** [comment]
I think it's reasonable to add to that page:

	Variables declared inside an if short statement are also available inside any of the else blocks.

	(Both calls to pow are executed and return before main's call to fmt.Println begins,
	so pow's output is separated from fmt.Println's output.)

**Comment by kytrinyx** [comment]
I'll grab this one.
