### ISSUE TITLE
x/mobile/cmd/gomobile: init fails

### ISSUE THREAD

**Issue by faxal** [golang/go#11690]
gomobile init fails when trying to rename a linker which doesn't exist.

gomobile: rename /home/xxx/.go/pkg/gomobile/work-187000458/go/pkg/tool/linux_amd64/5l /home/xxx/.go/pkg/gomobile/android-ndk-r10d/arm/bin/5l: no such file or directory

Version:

    ➜  ~  go version
    go version devel +783297a Sun Jul 12 04:42:40 2015 +0000 linux/amd64
    ➜  ~  uname -a
    Linux xxx 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux
    ➜  ~ cd $GOROOT_BOOTSTRAP
    ➜  go1.4 git:(886b02d) ✗ ./bin/go version
    go version go1.4.1 linux/amd64

**Comment by crawshaw** [comment]
This looks like an old version of gomobile. Could you please run
```go get -u golang.org/x/mobile/cmd/gomobile```

**Comment by faxal** [comment]
@crawshaw is absolutely right. I had `gomobile` up to date, but `PATH` was incorrectly set and it was executing an old binary.

Thank you and sorry for wasting your time on a non issue.
