### ISSUE TITLE
net/http: Exits without error message when address in use

### ISSUE THREAD

**Issue by Jsvcycling** [golang/go#11693]
When I run a server and attach it to a port that is being used by another process, my go server immediately exits without any warning.

I'm using version 1.4.1 and it've encountered the problem on both windows/amd64 and darwin/amd64 (haven't been able to test on linux/amd64).

**Comment by bradfitz** [comment]
Don't ignore the return value. e.g.:

```go
    log.Fatal(http.ListenAndServe(":8080", handler))
```

**Comment by Jsvcycling** [comment]
Ah, forgot about that. Thanks.
