### ISSUE TITLE
tour: no coding environment is available on the page

### ISSUE THREAD

**Issue by severeone** [golang/go#11692]
Context: /concurrency/7

The page is about an exercise. Meanwhile there's nothing on the left to write the code or run it.

**Comment by snakeru** [comment]
The excercise is too big so it was split into two pages - /concurrency/7 and /concurrency/8

While this is working as intended, this might require some refactoring to make it more obvious.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Would adding a small clarification at the bottom of the page help?

https://go-review.googlesource.com/#/c/12179/1
