### ISSUE TITLE
x/mobile/gl: shapes flicker/jitter without debug.DrawFPS(c)

### ISSUE THREAD

**Issue by shazow** [golang/go#11696]
(Possibly related to #10688 somehow?)

I'm experiencing flickering/jittery-ness/screen tearing on GL rendering that doesn't use debug.DrawFPS (which strangely fixes it, not sure why). It feels like DrawFPS is somehow enabling double buffering or vsync that is otherwise not there, but I can't figure out why/how that might be the case. Sorry I'm not very experienced with OpenGL.

For example, you can reproduce it in [mobile/example/basic](https://github.com/golang/mobile/tree/master/example/basic) with these two changes:

```diff
-       gl.Uniform4f(color, 0, green, 0, 1)
+       gl.Uniform4f(color, 0, 0, 0, 1)
...
-       debug.DrawFPS(c)
```

Not sure why the color needs to be fixed in the above example to reproduce.

I originally noticed this in a [somewhat more complex spinning cube example](https://github.com/shazow/gomobile-examples) which jitters when `debug.DrawFPS(c)` is not used. Video: https://www.youtube.com/watch?v=3s68XAJ04Kk

- go version devel +71832ff Fri Jul 3 21:39:04 2015 +0000 darwin/amd64
- golang.org/x/mobile commit 7fb893ba (latest)
- Mac OSX 10.9.5 on a 13" MBP (Intel Iris GPU).

**Comment by crawshaw** [comment]
Thanks, I can reproduce this during resize on OS X with your diff. Not sure what the problem is yet. Do you see it any other time than resize?

**Comment by shazow** [comment]
@crawshaw For me, it happens even without resizing. You can see in the video with the spinning cube (I edited it into the original post).

**Comment by crawshaw** [comment]
I have a working theory, but as I'm only seeing it on resize I'm not certain. @shazow, could you please try the change in https://go-review.googlesource.com/12123? Gerrit offers some instructions in the top-right corner, something like:

git fetch https://go.googlesource.com/mobile refs/changes/23/12123/1 && git checkout FETCH_HEAD

**Comment by shazow** [comment]
Yup, that's much better! Fixes it for both cases (basic example and my spinning cube) on my machine.

**Comment by crawshaw** [comment]
Great, thank you for giving me a way to reproduce this. I'll think through whether I can improve on that CL and try to send something out tomorrow.

**Comment by shazow** [comment]
Happy to help, thanks for the superquick turnaround. Let me know if I can help with testing other solutions.
