### ISSUE TITLE
os/signal: Unable to catch SIGHUP signal multiple times

### ISSUE THREAD

**Issue by nopejpg** [golang/go#11700]
I have the following code:

```
func HandleSIGHUP() chan os.Signal {
    sig := make(chan os.Signal, 1)
    
    signal.Notify(sig, syscall.SIGHUP)
    
    return sig
}
```

I "register" the signal like so:

```
go func() {
    for {
        <-HandleSIGHUP()
    
        // do something
    }
}()
```

The problem that I'm experiencing is that I'm only able to catch one SIGHUP. For example if I send multiple `kill -SIGHUP <pid>` to the process, the "register" code only runs once. How can I get it to run every time the signal is sent?

```
$ go version
go version go1.4.2 linux/amd64
```

I also posted this here: http://stackoverflow.com/questions/31395761/handle-signal-multiple-times-in-golang

**Comment by ianlancetaylor** [comment]
It's sort of peculiar that each time through the loop you are creating and registering a new channel.  Is that really what you want to do?  Why not create just one channel, before the loop?

**Comment by nopejpg** [comment]
@ianlancetaylor I tried many ways but they all have the same result; the code above is my last latest try.

**Comment by ianlancetaylor** [comment]
I can't recreate the problem.

I ran this: http://play.golang.org/p/7FAc7wzuhK .  In a separate terminal window, I typed "kill -SIGHUP PID".  Each time I ran that comment, the program printed SIGHUP.

Please show us a complete program.

**Comment by nopejpg** [comment]
@ianlancetaylor 
Indeed; unable to reproduce. I must have something else going on here.

**Comment by nopejpg** [comment]
It's working now. I probably tried to compile and didn't pay attention of the binary getting updated.
