### ISSUE TITLE
Usage of variable after if-else scope not detected by complier

### ISSUE THREAD

**Issue by agaurav** [golang/go#11701]
**go version** : go1.4.2 darwin/amd64, Running on Mac OS X Yosemite

**Issue** : The go compiler reports `result, err` as unused in the code below
```go
		if len(tableSchema.ReplicaTags) == 0 {
			result, err := rethink.DB(rethinkdbConfig.Database).TableCreate(tableSchema.Name, rethink.TableCreateOpts{
				PrimaryKey: tableSchema.PrimaryKey,
				Durability: tableSchema.Durability,
				Shards:     tableSchema.Shards,
				DataCenter: tableSchema.Replicas,
			}).RunWrite(session)
		} else {
			result, err := rethink.DB(rethinkdbConfig.Database).TableCreate(tableSchema.Name, rethink.TableCreateOpts{
				PrimaryKey: tableSchema.PrimaryKey,
				Durability: tableSchema.Durability,
				Shards:     tableSchema.Shards,
				DataCenter: tableSchema.PrimaryReplicaTag,
			}).RunWrite(session)
		}
		if err != nil {
			fmt.Println(err.Error())
		} else {
			fmt.Println(result)
		}

```

**Compiler output**
```
setup/dbSetup.go:96: result declared and not used
setup/dbSetup.go:96: err declared and not used
setup/dbSetup.go:104: result declared and not used
setup/dbSetup.go:104: err declared and not used
```

**Expected behaviour** would be no error as they are being used in their lifetime (i.e. in this case the scope of the function)

The below code compiles in one "go" :)

```go
		if len(tableSchema.ReplicaTags) == 0 {
			result, err := rethink.DB(rethinkdbConfig.Database).TableCreate(tableSchema.Name, rethink.TableCreateOpts{
				PrimaryKey: tableSchema.PrimaryKey,
				Durability: tableSchema.Durability,
				Shards:     tableSchema.Shards,
				DataCenter: tableSchema.Replicas,
			}).RunWrite(session)
			_, _ = result, err
		} else {
			result, err := rethink.DB(rethinkdbConfig.Database).TableCreate(tableSchema.Name, rethink.TableCreateOpts{
				PrimaryKey: tableSchema.PrimaryKey,
				Durability: tableSchema.Durability,
				Shards:     tableSchema.Shards,
				DataCenter: tableSchema.PrimaryReplicaTag,
			}).RunWrite(session)
			_, _ = result, err
		}
		if err != nil {
			fmt.Println(err.Error())
		} else {
			fmt.Println(result)
		}
```

**Comment by adg** [comment]
Go is block scoped, so each `{}` block introduces its own scope.

The scopes are described in the spec: http://golang.org/ref/spec#Declarations_and_scope

**Comment by agaurav** [comment]
I get `go` is block scoped, most languages are. Scoping is for **type** and **value** deduction of variable not its usage. If we limit the usage as well, then accessing a variable declared inside an `if`, `for` block should throw an error too. 
Also, as per http://golang.org/ref/spec#Variable_declarations 
*Implementation restriction: A compiler may make it illegal to declare a variable inside a function body if the variable is never used.*

as it says: **illegal if its not used inside the function body**

I accept that parsing usage across branched scoping throughout the function body will be a pain, but that will be the ideal behaviour. Else, it will result in lot of unnecessary variable assignment here and there in heavily nested code.

**Comment by bradfitz** [comment]
Please move this to the golang-nuts@ mailing list.

**Comment by adg** [comment]
We can't change the declaration and scoping rules. http://golang.org/doc/go1compat
