### ISSUE TITLE
runtime: Stack output is inconsistent with NumGoroutine output

### ISSUE THREAD

**Issue by snakeru** [golang/go#11706]
While trying to detect goroutines leaks from my program I noticed that runtime.NumGoroutine reports much higher number of goroutines (5) than reported by runtime.Stack (1).
After some poking around I figured that there are, indeed, some system routines running in the background.

Here is the repro: http://play.golang.org/p/WowC44lsh9

A few notes:
1) This is only reproducible in go 1.5. Go 1.4 works correctly
2) The behavior of runtime.Stack() depends on the GOTRACEBACK environment variable. If it is set to "2" then runtime.Stack() outputs all 5 goroutines.
So this looks like runtime.NumGoroutine() should also depend on this environment variable to stay consistent (outputting only user-created goroutines is a feature and is very welcome).

**Comment by snakeru** [comment]
runtime.Stack outputs all stack traces if environment variable GOTRACEBACK is set to 2.
So my guess is that runtime.NumGoroutine should probably do the same.

**Comment by ianlancetaylor** [comment]
Not sure whether we should change the code or simply document it.

**Comment by nightlyone** [comment]
Documenting would suffice for Go 1.5{.x}, but for Go 1.6 it would be nice to be able to get both, number of goroutines started by the system and number of goroutines started by myself.

**Comment by rsc** [comment]
Will think more but it seems to me right now that runtime.Stack should just show system goroutines when you ask for all. We omit them from panic crashes to avoid cluttering crash output in simple programs, but if you're asking for 'all goroutines' it seems like probably you should get them all.

Either that or it should never show them, and whichever it is, NumGoroutines should match.
