### ISSUE TITLE
cmd/go: go get doesn't work with ssh

### ISSUE THREAD

**Issue by marcopeereboom** [golang/go#11713]
Looks like go get is broken again on ssh git repos.

For example:
$ go get -v -f -u -insecure ./...       
package github.com/marcopeereboom/gck: unable to parse output of git config remote.origin.url
package github.com/marcopeereboom/gck/ast: unable to parse output of git config remote.origin.url
...

$ git config remote.origin.url
git@github.com:marcopeereboom/gck.git

This also happens for ssh git repos with an explicit ssh origin: ssh://my.server.com/git/myrepo.git

https repos seem to still work fine.

$ go version
go version devel +60b7d27 Tue Jul 14 06:21:57 2015 +0000 darwin/amd64
$ git version
git version 2.3.8 (Apple Git-58)

I do see this on OpenBSD as well.

**Comment by pierrre** [comment]
duplicate #11457 ?

**Comment by adg** [comment]
Yes, it's a dupe.

**Comment by marcopeereboom** [comment]
Please do not make this a 1.5 maybe.  This is a hard requirement for a lot of people.  Our company will be forced to stick with 1.4 until it is solved.  Seriously, this is a huge deal.

**Comment by dalu** [comment]
Indeed. My platform is inoperable as of Go 1.5
