### ISSUE TITLE
net: Listen("tcp", ":123456789") works

### ISSUE THREAD

**Issue by pierrre** [golang/go#11715]
CL: https://golang.org/cl/12213

Go version: go1.4.2 linux/amd64 (same result with Go 1.5beta1)
My code:
```go
package main

import (
	"fmt"
	"net"
)

func main() {
	l, err := net.Listen("tcp", ":123456789")
	if err != nil {
		panic(err)
	}
	fmt.Println(l.Addr())
}
```
It prints: `[::]:52501` (always this port)
What I expected: it should return an error.

If I use port ":66666", it prints: `panic: listen tcp: invalid port 66666`

**Comment by jnjackins** [comment]
This will happen for any ports higher than 0xFFFFFF. dtoi fails for inputs larger than that, which causes parsePort to take a different error path.

**Comment by jnjackins** [comment]
Actually, I get a decent error message on linux as well:

```
$ uname -a
Linux mag-oprs-pmi-001.osl.basefarm.net 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
$ ./test2 
panic: listen tcp: unknown port tcp/16777215

goroutine 1 [running]:
main.main()
	/Users/jnj/tmp/test2.go:11 +0xa3
```

**Comment by jnjackins** [comment]
I mailed https://go-review.googlesource.com/#/c/12213, although I don't know if it's an acceptable fix and I'm sure it's not important for go1.5.

**Comment by jnjackins** [comment]
Oh, I've realized now that I read your message wrong from the beginning. I thought you were getting a strange error message, but you're not getting an error at all for the higher port. I actually can't reproduce that.

**Comment by mikioh** [comment]
@jnjackins,

Please open a new issue for consistent error messages. This issue needs to focus on the behavior of Listen w/ invalid arguments.
