### ISSUE TITLE
cmd/go: go get -t ignores vendor folder

### ISSUE THREAD

**Issue by azylman** [golang/go#11717]
Version of Go:
go version devel +b6ead9f Tue Jul 7 21:53:11 2015 +0000 linux/amd64

OS and architecture:
linux/amd64 (ubuntu 14.04)

What did I do:
Ran `go get -t` with vendoring turned on, expected it to only try to download test dependencies that didn't exist, like `go get`

What did I see instead:
It tried to download dependencies that already existed in the `vendor/` folder

Reproducing:

Project hierarchy (located in `$GOPATH/src/github.com/azylman/demo`):

```
main.go
main_test.go
vendor/
  example.org/
    thing/
      thing.go
```

Files:
```go
// main.go
package main

import (
	"fmt"

	"example.org/thing"
)

func main() {
	fmt.Println(thing.One, thing.Two)
}
```

```go
// main_test.go
package main

import (
	"fmt"
	"testing"

	"example.org/thing"
)

func TestNothing(t *testing.T) {
	fmt.Println(thing.One)
}
```

```go
// vendor/example.org/thing/thing.go
package thing

const (
	One = iota + 1
	Two
)
```

Output:
```shell
$ export GO15VENDOREXPERIMENT=1

$ go run main.go
1 2

$ go test
1
PASS
ok  	github.com/azylman/demo	0.006s

$ go get

$ go get -t
package example.org/thing: unrecognized import path "example.org/thing"
```

**Comment by adg** [comment]
cc @rsc

Not sure if this was fixed by a [recent change](https://go-review.googlesource.com/#/c/12192/1) (probably not).
