### ISSUE TITLE
go/types: extend StdSizes to support amd64p32

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11716]
Currently StdSizes allows to specify only MaxAlignment and WordSize, but this cannot handle one of the standard architectures -- amd64p32. It should allow to specify WordSize and PointerSize independently.

**Comment by griesemer** [comment]
StdSizes also doesn't exactly follow the gc-compiler's alignment and size computation in general. It's not meant to be a 1:1 drop-in.

What's more, the go/types API and thus StdSizes is frozen. It is easy enough to either a) write an external implementation of Sizes and provide it to go/types, or perhaps add a GCSizes type that matches the gc-behavior exactly. Either way, those approaches would solve this problem in a different way.

I'm going to close this as unfortunate.
