### ISSUE TITLE
encoding/xml: panics when trying to unmarshal a named attribute into a non-byte slice

### ISSUE THREAD

**Issue by ainar-g** [golang/go#11723]
Go versions:
- `go version devel +2e4b659 Wed Jul 15 06:04:51 2015 +0000 linux/amd64`
- `go version go1.4.2 linux/amd64`

Code: http://play.golang.org/p/ZxYJ0EFsfv.

Expected: an error, something like `unsupported type: []string`.

Got: `panic: reflect.Value.SetBytes of non-byte slice`. Same with []int or any other non-byte slice.

May be related to https://github.com/golang/go/issues/6341.

**Comment by ianlancetaylor** [comment]
I think we just need to change copyValue in encoding/xml/read.go to check the element type of the slice before calling SetBytes.

**Comment by andrestc** [comment]
Instead of panicking, running the code on http://play.golang.org/p/ZxYJ0EFsfv returns:

```
main.Foo{Type:[]string{"Bar"}}
```

Should we consider the issue fixed?

**Comment by ainar-g** [comment]
@ianlancetaylor This seems fixed. Should I close the issue? Or should someone first check, if the case is covered in tests?

**Comment by ianlancetaylor** [comment]
I think this was probably fixed by https://golang.org/cl/30946, which has test cases, so, closing.
