### ISSUE TITLE
cmd/pprof: web command works but -web flag does not

### ISSUE THREAD

**Issue by josharian** [golang/go#11729]
```bash
$ go tool pprof -web x.test cpu.prof
```

results in a 404 in my browser.

```bash
$ go tool pprof x.test cpu.prof
Entering interactive mode (type "help" for commands)
(pprof) web
(pprof) 
```

results in an svg displayed in my browser.

**Comment by ebfe** [comment]
On a side note: "web" seems a misnomer for the current implementation. It uses `xdg-open` on Linux and at least on some systems `xdg-open` doesn't launch a browser but gimp to view the svg.

**Comment by rsc** [comment]
I think the problem is that -web exits (deleting the temp file) before the browser has had a chance to open it.
