### ISSUE TITLE
cmd/go: Add go get flag to download to vendor directory

### ISSUE THREAD

**Issue by mattfarina** [golang/go#11726]
`go get` downloads into the `GOPATH`. It would be useful to have a flag that downloads the package to the new `vendor` directory.

**Comment by ianlancetaylor** [comment]
For now this is going to be the province of external vendoring tools.  Perhaps in the future it will become part of go get.

**Comment by bcmills** [comment]
`go mod vendor` downloads the dependencies of the main module into its `vendor` directory.

That's probably as close as we're going to get, although we may add an optional argument to vendor in a specific module as part of the resolution to #27227.
