### ISSUE TITLE
crypto/x509: TestSystemVerify failed on windows

### ISSUE THREAD

**Issue by chai2010** [golang/go#11730]
```
go version devel +2072fc3 Thu Jul 16 00:57:45 2015 +0000 windows/amd64

--- FAIL: TestSystemVerify (0.08s)
        verify_test.go:389: #15: No expected chain matched BR/Moip Pagamentos
S.A./MOIP,SSL Blindado EV/api.moip.com.br -> GB/COMODO CA Limited//COMODO
RSA Extended Validation Secure Server CA -> GB/COMODO CA Limited//COMODO
RSA Certification Authority

FAIL
```

**Comment by alexbrainman** [comment]
@chai2010 what is your OS? From what I understand this test fails on some windows systems and has been disabled there - see https://go-review.googlesource.com/#/c/8167/ for details. Maybe it should be disabled on your too.

Alex

**Comment by chai2010** [comment]
@alexbrainman The OS is Win7/64. I found this news for Win7: https://technet.microsoft.com/en-us/library/security/2949927.aspx

**Comment by alexbrainman** [comment]
@chai2010 I would like to know what your OS version / service pack is. Please "go get" github.com/alexbrainman/winapi and run "go test -run=GetVersion -v" and show command's output here. Thank you.

Alex

**Comment by chai2010** [comment]
```
C:\go\gopkg\src\github.com\alexbrainman\winapi>go test -run=GetVersion -v
=== RUN   TestGetVersionEx
--- PASS: TestGetVersionEx (0.00s)
        winapi_test.go:47: OSVERSIONINFOEX is {OSVersionInfoSize:284 MajorVersion:6
MinorVersion:1 BuildNumber:7601 PlatformId:2 CSDVersion:[83 101 114 118 105 99 101 3
2 80 97 99 107 32 49 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Se
rvicePackMajor:1 ServicePackMinor:0 SuiteMask:256 ProductType:1 Reserved:0}
        winapi_test.go:48: OSVERSIONINFOEX.CSDVersion is Service Pack 1
PASS
ok      github.com/alexbrainman/winapi  0.092s
```

**Comment by alexbrainman** [comment]
@chai2010 I can skip this test on your system (see https://go-review.googlesource.com/12401 for details). But that disables the test on all of our builders (and all pcs I have). So we won't know if library code is broken or not. I suggest you try and update your system instead. What do you think?

Alex

**Comment by chai2010** [comment]
@alexbrainman Thanks for your work. But i dont use this pkg. And my Win7 is auto updated.

I suggest disable the test if it can't run on some system.

**Comment by chai2010** [comment]
@alexbrainman We can use a build tag for all builers and all your pcs, just for Go team do test (not for Go user).
