### ISSUE TITLE
x/image/color/palette: Add support for CSS3 / SVG supported named colors

### ISSUE THREAD

**Issue by srinathh** [golang/go#11734]
[SVG][3] & [CSS3][2] [specify][1] named colors which are based on the original [X11 colors names][4] and are widely supported and used by web-browsers. Making them available palette package could be useful for web applications and also other image applications that want to make use of standard named colors.

We could provide in a sub-directory (eg. css3colors) under the palette package:
- named `Color` variables
- A `map[string]Color` to lookup textual representation
- A `[]Color` palette 

Happy to work on this if the direction sounds right..
 
[1]: http://www.w3.org/TR/css3-color/#svg-color
[2]: http://www.w3.org/TR/css3-color/#html4
[3]: http://www.w3.org/TR/SVG/types.html#ColorKeywords
[4]: http://www.w3.org/TR/css3-color/#X11COLORS

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
I think the best place for this is golang.org/x/image/colornames, which would contain:

var Map = map[string]color.RGBA{
  "aliceblue": color.RGBA{0xF0, 0xF8, 0xFF, 0xFF},
  etc,
}

and also maybe a sorted list of keys:

var Names = []string{
  "aliceblue",
  etc
}

It might also be nice if this map and slice was "go generated" from the definitive spec (whichever of SVG, CSS3 or X11 should be definitive), the same way that e.g. https://go.googlesource.com/net/+/master/html/atom/gen.go and https://go.googlesource.com/net/+/master/publicsuffix/gen.go scrape an HTTPS URL to generate Go code. Those particular gen.go was written before "go generate" existed. There are more modern "go generate" examples in the golang.org/x/text repo.

CC @robpike

**Comment by srinathh** [comment]
Fair enough... I'll take a look at the examples

**Comment by robpike** [comment]
SGTM much as I think these names are both too limiting and twee.

**Comment by nigeltao** [comment]
@andybalholm and @ajstarks might be interested in this.

**Comment by srinathh** [comment]
Here's what I've found about the named color specs:

- **SVG1.1:** For the time being, [this section](http://www.w3.org/TR/SVG/types.html#ColorKeywords) in the SVG 1.1 spec seems to be the definitive reference for named colors. 

- **CSS4:** If we want to be future proof, the draft CSS4 spec is definitively defining [named colors](http://drafts.csswg.org/css-color-4/#named-colors) extending beyond the SVG1.1 spec.
  
- **CSS3:** In the CSS3 spec named colors are broken into [two](http://www.w3.org/TR/css3-color/#html4) different [sections](http://www.w3.org/TR/css3-color/#svg-color) and the extended color list essentially refers to SVG 1.1 - so probably not a definitive list  

- **SVG2:** For the time being, i'm not able to find a named color spec in the draft SVG2 working group docs similar to SVG1.1. They seem to be adding flexibility in the named color spec 

- **X11: **The official reference for X11 colors in W3 docs seems to be Wikipedia, so that's probably not a good idea :-) 

I'd say that basing generation of named colors on the draft CSS4 spec will likely give us future compatibility for many years as the draft gets worked on and published. If we want to be strictly published standards driven, then we should follow SVG1.1

**Comment by ajstarks** [comment]
I've used the SVG named colors in two places:

https://github.com/ajstarks/openvg/blob/master/openvg.go
https://github.com/ajstarks/deck/blob/master/cmd/pdfdeck/colors.go

**Comment by srinathh** [comment]
Yes I saw those when I was looking for a named SVG colors library for a personal project & ended up rolling something very similar with color.RGBA - so i do think there are use cases for such. I'm almost done with a go generate based generator for this and will post for codereview soon.

**Comment by srinathh** [comment]
I have added a package golang.org/x/image/colornames which go generates an exported map of named colors from the SVG 1.1 spec at http://www.w3.org/TR/SVG/types.html

Request codereview: https://go-review.googlesource.com/13181
