### ISSUE TITLE
cmd/go: Current 'go get' fails on some usages of 'import "C"'

### ISSUE THREAD

**Issue by siebenmann** [golang/go#11738]
On the current development git tip, an attempt to do 'go get -d github.com/derekparker/delve/cmd/dlv' fails for me with the following error message:

    package github.com/derekparker/delve/cmd/dlv
        imports github.com/derekparker/delve/service
        imports github.com/derekparker/delve/service/api
        imports github.com/derekparker/delve/proc
        imports C: unrecognized import path "C"

I'm on 64-bit Fedora 22 Linux and I believe that this 'go get' is thus failing on the 'import "C"' in github.com/derekparker/delve/proc/breakpoints_linux_amd64.go. If I fetch the repo and so on by hand, I can do 'go install github.com/derekparker/delve/cmd/dlv' without problems; everything builds successfully. It's only the initial 'go get' that fails.

A run of git bisect reports that the first bad commit is af96030150217fe711eac5ee994b44705bfb6832 'cmd/go: fix go get -u handling of changing dependencies', which at least appears to be a related change.

**Comment by dmitris** [comment]
Having the same issue when trying to do: `go get -v github.com/docker/docker/...` with the Go beta version go1.5beta2:
```
$ GOPATH=/tmp/go go get -v github.com/docker/docker/...github.com/docker/docker (download)
package github.com/docker/docker/api/client
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	[$GOROOT]/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/tmp/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
import "C": import path does not begin with hostname
package github.com/docker/docker/api/server
	imports github.com/docker/docker/builder
	imports github.com/docker/docker/daemon
	imports github.com/docker/docker/pkg/graphdb
	imports code.google.com/p/gosqlite/sqlite3
	imports C: unrecognized import path "C"
```

**Comment by GeertJohan** [comment]
Having the same problem in go-gorp travis-CI build with go tip.
https://travis-ci.org/go-gorp/gorp/builds/71365357

cc @nelsam

**Comment by ricsmania** [comment]
I'm also having this problem on Windows x64. x86 seems to be working.

**Comment by ianlancetaylor** [comment]
There is a patch out for review: https://golang.org/cl/12322 .

**Comment by btracey** [comment]
We are seeing this failure in gonum. It is currently passing on Go 1.4 and failing on 1.5beta2.

Pull Request: https://github.com/gonum/lapack/pull/21 
Travis Report: https://travis-ci.org/gonum/lapack/builds/73222462
Detailed Failure message: https://travis-ci.org/gonum/lapack/jobs/73222477

**Comment by btracey** [comment]
Oh, I see. This was fixed after beta2. Sorry.
