### ISSUE TITLE
cmd/compile: autotmp_NNNN variable name in compiler error output

### ISSUE THREAD

**Issue by willfaught** [golang/go#11737]
Write code like this:

    func F(middleware interface{}) {
        switch middleware {
        case tigertonic.JSONLogged:
            [...]

and get a compiler error like this:

    $ go build
    # [...]/server
    ./middleware.go:69: invalid operation: autotmp_0210 == "github.com/rcrowley/go-tigertonic".JSONLogged (operator == not defined on func)
    ./middleware.go:73: invalid operation: autotmp_0210 == "github.com/rcrowley/go-tigertonic".Logged (operator == not defined on func)

I'm guessing auto-generated variable names aren't meant to be exposed outside the compiler?

**Comment by ianlancetaylor** [comment]
Which version of Go?

Can you please provide a small, complete, standalone example?  That will take less total time than us guessing to try to create a complete example from your code fragment.  Thanks.

**Comment by ebfe** [comment]
package main
    
    func f() {}
    
    func s(x interface{}) {
            switch x {
            case f:
            }
    }
    
    func main() {
            s(f)
    }
