### ISSUE TITLE
cmd/go: "#cgo pkg-config:" comments do not work with gccgo

### ISSUE THREAD

**Issue by mwhudson** [golang/go#11739]
I don't have a minimal example, but https://launchpadlibrarian.net/211688868/buildlog_ubuntu-wily-arm64.account-polld_0.1%2B15.04.20150410-0ubuntu2~gcc5.1_BUILDING.txt.gz is an example of this happening. http://bazaar.launchpad.net/~ubuntu-push-hackers/account-polld/trunk/view/head:/accounts/accounts.go#L20 is "#cgo pkg-config: glib-2.0 libaccounts-glib libsignon-glib" but the flags are not being passed in the link.

I don't entirely get how this is supposed to work. cgo writes the flags to a file:

```
$ cat $WORK/launchpad.net/account-polld/accounts/_obj/_cgo_flags
_CGO_LDFLAGS=-g -O2 -laccounts-glib -lsignon-glib -lgio-2.0 -lgobject-2.0 -lglib-2.0
_CGO_CFLAGS=-pthread -I/usr/include/signond -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I /tmp/go-build086811367/launchpad.net/account-polld/accounts/_obj/
```

but afaict nothing ever looks at this file. When *gccgo is false (https://github.com/golang/go/blob/master/src/cmd/cgo/out.go#L42) it also writes out //go:cgo_ldflag comments, which is how this works with the usual compiler but gccgo doesn't use those comments I think.

**Comment by ianlancetaylor** [comment]
The pkg-config flags are implemented by cmd/go, not cmd/cgo.

The code does seem to be independent of the compiler toolchain; I don't know why it's not working for gccgo.

**Comment by mwhudson** [comment]
Well, pkg-config is called by cmd/go sure, but the way the flags get used seems to be a cgo / cmd/compile / cmd/link collaboration: go calls pkg-config, passes the results to cgo as CGO_LDFLAGS in the environment, cgo writes them as cgo_ldflags comments to one of the .go files it creates, cmd/compile translates those to the "$$ // cgo" section of the .o file, which is read by cmd/link and passed to the external linker. Only the first two bits happen when using gccgo.

I don't know what a fix would look like. The go tool could somehow stuff some record of the flags into the .a of a cgo using package and look for it again when linking? Currently I don't think it actually looks into the lib$name.a files at all but I guess that could change...

**Comment by mwhudson** [comment]
Can someone assign this to me please?

**Comment by kyrofa** [comment]
I've hit this as well. Any status update?

**Comment by mwhudson** [comment]
Not really -- I definitely want to get this fixed for 1.6 but haven't started on it myself, or even thought very hard about how to fix it (the only thing I've thought is to have the go tool put the the flags into the .a file of a package using cgo and reading them out when linking)

**Comment by dobey** [comment]
Should not this have been fixed by https://codereview.appspot.com/157460043/ ? That's about a year old, so maybe something else broke?

**Comment by mwhudson** [comment]
No that fixed the worst of the problems in the area, but this one is different: pkg-config is run when the go package is compiled, but the flags must be used when the executable is *linked*, which might not be in the same invocation of the go tool.

**Comment by rsc** [comment]
This would be nice but I don't see this happening for Go 1.6.

**Comment by mwhudson** [comment]
Yeah, didn't get to this :/
