### ISSUE TITLE
proposal: return blank identifier as zero value

### ISSUE THREAD

**Issue by chai2010** [golang/go#11732]
```Go
func decodConfig(r io.Reader) (image.Config, bool) {
	if cfg, err := image.DecodConfig(r); err == nil {
		return cfg, true
	}
	return _, false // return image.Config{}, false
}
```

**Comment by cespare** [comment]
For previous discussion of this topic, see

https://groups.google.com/forum/#!topic/golang-nuts/Ii2rmcm483Q

(The first response to that proposal, from @ianlancetaylor, links to 3 previous proposals.)

**Comment by chai2010** [comment]
@cespare Thanks for your link.

**Comment by davecheney** [comment]
Based on the extended discussion in https://groups.google.com/d/msg/golang-nuts/Ii2rmcm483Q/hU6DHLzMbjIJ, I am closing this proposal. 

Please feel free to comment if you think this is premature.
