### ISSUE TITLE
 tour:undefined: math.pi

### ISSUE THREAD

**Issue by Bucca1992** [golang/go#11744]
Context: https://tour.golang.org/basics/3

package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.pi)
}

After running the program, it outputs like this:
# command-line-arguments
/tmp/sandbox237646202/main.go:9: cannot refer to unexported name math.pi
/tmp/sandbox237646202/main.go:9: undefined: math.pi

**Comment by bradfitz** [comment]
Read the page carefully before pressing Run!

Dup of #11623
