### ISSUE TITLE
x/mobile/app: config.Event delivery is not reliable (android)

### ISSUE THREAD

**Issue by hyangah** [golang/go#11741]
I slightly modified the basic app https://go-review.googlesource.com/#/c/12330/
to demonstrate this problem.

Background color is red if Width > Height.
Background color is white otherwise.

Keep rotating and touching the device. It's somewhat non-deterministic.
This prevents correct screen geometry computation.

go version devel +adb1e03 Thu Jul 16 20:56:23 2015 +0000 darwin/amd64
golang.org/x/mobile: 136fa9bb
test devices: android nexus 7 (android 4.4.4 cyanogenMod), moto X (android 4.4.4)

@crawshaw @nigeltao

**Comment by crawshaw** [comment]
The documentation is not clear on what we should be using.

Non-NativeActivity users talk about listening for onSurfaceChanged, which seems to translate into onNativeWindowResized, onNativeWindowCreated, and onNativeWindowDestroyed.

Right now we listen for onNativeWindowRedrawNeeded, which is onSurfaceRedrawNeeded.

Tomorrow I'll try to replicate the missing events, and see if switching to listening for onNativeWindowResized helps.

**Comment by crawshaw** [comment]
I put some logging into example/basic, and what I'm seeing (on a Galaxy Nexus) is reliable event delivery, but sometimes the width/height are not updated.

Also following the NativeActivity source through to the platform docs suggests onNativeWindowRedrawNeeded should be called for orientation changes, so it's a safe place to listen. Not sure yet what's wrong with querySurfaceWidthAndHeight.

**Comment by crawshaw** [comment]
onNativeWindowResized is flaky. Not a safe source of rotation events.
