### ISSUE TITLE
runtime: frame runtime.memeq untyped args 0xc28afdad00+0x19

### ISSUE THREAD

**Issue by mail2fish** [golang/go#11748]
runtime: frame runtime.memeq untyped args 0xc28afdad00+0x19
fatal error: missing stackmap

runtime stack:
runtime.throw(0x12086d1)
        /usr/local/go/src/runtime/panic.go:491 +0xad
adjustframe(0x7f44477fdcd8, 0x7f44477fdda8, 0x1)
        /usr/local/go/src/runtime/stack.c:525 +0x348
runtime.gentraceback(0x465a10, 0xc28afda1c0, 0x0, 0xc22fe185a0, 0x0, 0x0, 0x7fffffff, 0x7f44477fdd98, 0x7f44477fdda8, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:311 +0x7a8
copystack(0xc22fe185a0, 0x4000)
        /usr/local/go/src/runtime/stack.c:623 +0x177
runtime.newstack()
        /usr/local/go/src/runtime/stack.c:789 +0x575
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:324 +0x7e

======================

go version

go version go1.4.2 linux/amd64

OS: centos 7

go env 

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/centos/gopath/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by ianlancetaylor** [comment]
How can we recreate this problem?

Does it happen with Go1.5 beta2?

**Comment by mail2fish** [comment]
I don't know exactly how to reproduce it. It seem happened with a lot of go routines. 

It's  in Go 1.4.2 environment. Haven't started using Go 1.5 yet.

**Comment by mail2fish** [comment]
I don't know exactly how to reproduce it. It seem happened with a lot of go routines. 

It's  in Go 1.4.2 environment. Haven't started using Go 1.5 yet.

**Comment by ianlancetaylor** [comment]
It's going to be very hard for us to fix this without some hint as to how to reproduce it.

Does it happen consistently for some programs, or does it just happen randomly?  How often does it happen?

**Comment by mail2fish** [comment]
Thanks for your quick response. I will try to figure out how to reproduce it.

**Comment by rsc** [comment]
Was there another stack, for a goroutine, immediately after the one you quoted?
If so that might help us understand what led to the memeq.

**Comment by aclements** [comment]
@mail2fish, any luck reproducing this? Have you tried it with a Go 1.5 beta?

**Comment by rsc** [comment]
I can reproduce the specific crash with

	package main
	
	import "unsafe"
	
	type T struct {
		a [10]int
	}
	
	func main() {
		defer func() {
			recover()
			recurse(10000)
		}()
		var x, y interface{}
		var t T
		x = t
		y = t
		(*[2]uintptr)(unsafe.Pointer(&y))[1] = 0
		println(x == y)
	}
	
	func recurse(x int) {
		if x > 0 {
			recurse(x-1)
		}
		print("")
	}

I doubt this program bears much resemblance to yours, but the salient point is that there was a fault inside memeq due to a bad pointer somewhere. And then the handling of the fault went bad.

The same program works correctly in Go 1.5. So I think this is fixed.
