### ISSUE TITLE
x/tools/cmd/godoc: godoc shows initializers for unexported fields

### ISSUE THREAD

**Issue by mdempsky** [golang/go#11758]
http://tip.golang.org/pkg/go/types/#pkg-variables:

    var Typ = [...]*Basic{
        Invalid: {Invalid, 0, "invalid type"},
        [...]
    }

http://tip.golang.org/pkg/go/types/#Basic:

    type Basic struct {
        // contains filtered or unexported fields
    }

It seems somewhat inconsistent that godoc would hide unexported fields from the Basic type description, but then show the values used to initialize them within Typ.  It's not legal for users to write `types.Basic{types.Invalid, 0, "invalid type"}`.

**Comment by rsc** [comment]
In general godoc shows the initializers unmodified. It is up to the code author to put something useful there (or not). In this case if the definition of Typ should be hidden then the idiom is

	var Typ [...]*Basic = basicTypes

	var basicTypes = [...]*Basic{...}

**Comment by rsc** [comment]
That is, I don't think this is a bug in godoc.
