### ISSUE TITLE
cmd/compile: mkdotargslice: typecheck failed

### ISSUE THREAD

**Issue by TatriX** [golang/go#11750]
```go version go1.5beta2 linux/386```
Code from go1.4 release does not compile on go 1.5beta2:
```go
package main

func main() {
	fn := func(names ...string) {

	}
	func(names ...string) {
		for _, name := range names {
			fn(name)
		}
	}("one", "two")
}
```
Gives:
```
./test.go:11: ... must be last argument
./test.go:11: cannot use fn (type func(...string)) as type string in array element
./test.go:11: internal compiler error: mkdotargslice: typecheck failed
```
Expected: no errors

**Comment by dr2chase** [comment]
Bug introduced with this commit: https://go-review.googlesource.com/#/c/4050/7
Still figuring out how.

**Comment by ianlancetaylor** [comment]
This was fixed by https://golang.org/cl/12580 (there was a typo in the CL description).
