### ISSUE TITLE
allow newline before closing parenthesis in the parameter list

### ISSUE THREAD

**Issue by ibukanov** [golang/go#11751]
Currently go does not allow to move the parenthesis that closes the parameter list in the function declaration on a new line. For example, one cannot write
```
func foo(
    a SomeTextuallyLongType,
    b AnotherTextuallyLongType
) (YetAnotherTextuallyLongType,  StillAnotherTextuallyLongType) {
    firstBodyLine
```

The acceptable forms are uglier:
```
func foo(
    a SomeTextuallyLongType,
    b AnotherTextuallyLongType) (YetAnotherTextuallyLongType, StillAnotherTextuallyLongType) {
    firstBodyLine
```
or
```
func foo(
    a SomeTextuallyLongType,
    b AnotherTextuallyLongType) (
    YetAnotherTextuallyLongType, StillAnotherTextuallyLongType) {
    firstBodyLine
```

It would be nice to lift this restriction.

**Comment by nightlyone** [comment]
try shorter type names, less arguments, less results.

Use structs as arguments/results when it gets (still) ugly:
```go
type fooConfig struct {
	a SomeTextuallyLongType
	b AnotherTextuallyLongType
}

type fooResult struct {
	a YetAnotherTextuallyLongType
	b StillAnotherTextuallyLongType
}

func foo(cfg fooConfig) fooResult {
	// .. first body line
	return fooResult{}
}
```

This is much more readable and usable, because you and your users won't mix up parameter and result order all the time.

**Comment by ibukanov** [comment]
@nightlyone wrote:
>Use structs as arguments/results when it gets (still) ugly

When refactoring a body of a big function into smaller ones I do not want to complicate the call site with struct initialization and unpacking and invent names for transient structs.

**Comment by bradfitz** [comment]
You can put a comma at the end of the last parameter line:

```
func foo(
    a SomeTextuallyLongType,
    b AnotherTextuallyLongType,
) (YetAnotherTextuallyLongType,  StillAnotherTextuallyLongType) {
    firstBodyLine
```

As a bonus, it's now consistent with the line before it.

**Comment by ibukanov** [comment]
@bradfitz Thanks, that is nice. I wonder if Go gets automatic comma insertion at some point :)
