### ISSUE TITLE
Can't compile Go 1.5 beta 2 on Windows without GCC

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#11754]
1. What version of Go are you using (go version)?

  N/A, commit 2899be812046515c7d9d9d3f925c7bcfca093e8a.

2. What operating system and processor architecture are you using?

  Windows 7, 64bit.

3. What did you do?

  Ran `src/all.bat` with `CGO_ENABLED=0`.

4. What did you expect to see?

  A succesfull build.

5. What did you see instead?

```
--- FAIL: TestReturnAfterStackGrowInCallback (0.01s)
	syscall_windows_test.go:611: failed to build dll: exec: "gcc": executable file not found in %PATH% - 
FAIL
FAIL	runtime	33.659s
```

**Comment by Thomasdezeeuw** [comment]
Apparently the go tool is build succesfully, but the tests do fail.

**Comment by bradfitz** [comment]
@alexbrainman, can you look into this one?

**Comment by alexbrainman** [comment]
@Thomasdezeeuw does https://go-review.googlesource.com/12347 fixes your build?

Alex

**Comment by Thomasdezeeuw** [comment]
This fixed it, thanks.

**Comment by alexbrainman** [comment]
Thanks for checking.

Alex
