### ISSUE TITLE
net/http: ServeMux unexpectedly redirecting to add trailing slash

### ISSUE THREAD

**Issue by jehiah** [golang/go#11757]
`http.ServeMux` unexpectedly redirects to add a trailing slash if there is a route that matches with a trailing slash.

Given the following `ServeMux`, I expect that a request for `/a` would match the path rooted as `/`.

```go
http.HandleFunc("/", ...)
http.HandleFunc("/a/", ...)
```
Instead, a 301 redirect is returned redirecting to `/a/` (see http://play.golang.org/p/65Skm2I5hq).

The docs describe redirects as happening in path sanitization cases (ie: requests with `.` or `..` elements), but no mention of transparently adding slashes. The docs also describe the match as a `"rooted subtree"` so it's also unexpected that a pattern for `/a/` would affect requests that don't have that prefix (ie: w/o the trailing slash).

In researching if this situation was reported before, I found a mailing list from 2010 implying this [was expected](https://groups.google.com/d/msg/golang-nuts/P-uq-cN4tjA/Mw9Ns2no35gJ) as well as a [code comment](http://golang.org/src/net/http/server.go#L1566). If that is still the case, then i think the docs should reflect that. (though i personally consider this a bug, i could understand that for some this could be a feature).

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by jehiah** [comment]
For context I've looked at how this is handled by other http routers. It's mixed as to how default implementations behave, but generally is documented clearly with a configurable.

* [julienschmidt/httprouter](http://github.com/julienschmidt/httprouter) exposes a [RedirectTrailingSlash](http://godoc.org/github.com/julienschmidt/httprouter#Router.RedirectTrailingSlash) option and by default does do these redirects.
* [gorilla/mux](github.com/gorilla/mux) exposes a [StrictSlash](http://godoc.org/github.com/gorilla/mux#Router.StrictSlash) option and by default does not do these redirects.

**Comment by rsc** [comment]
@jehiah FWIW, the configurable here is that you register the non-slash form too and tell the ServeMux what should handle it.

**Comment by jehiah** [comment]
Thanks for the doc clarifications! much appreciated @rsc
