### ISSUE TITLE
runtime/pprof tests fail for go1.2beta2

### ISSUE THREAD

**Issue by GeertJohan** [golang/go#11756]
Compiling go1.5beta2 (cc8f5441980a8c2f9e6c8ec3222985ed488e76ba) fails with the following errors during the tests.
```
--- FAIL: TestTraceStress (1.67s)
	trace_test.go:226: failed to parse trace: bogus scanning end (offset 892575, time 28614703)
--- FAIL: TestTraceStressStartStop (0.73s)
	trace_test.go:365: failed to parse trace: EvFrequency contains invalid frequency -60703235145 at offset 0x222
--- FAIL: TestTraceFutileWakeup (0.07s)
	trace_test.go:433: failed to parse trace: g 186 is not waiting before unpark (offset 481, time 550)
FAIL
FAIL	runtime/pprof	9.153s
```

When I ran `./all.bash` a second time, it only had a single error:
```
--- FAIL: TestTraceStressStartStop (0.42s)
	trace_test.go:365: failed to parse trace: bogus scanning end (offset 108133, time 135001278)
FAIL
FAIL	runtime/pprof	9.094s
```

The third time was different also:
```
--- FAIL: TestTraceStress (1.55s)
	trace_test.go:226: failed to parse trace: g 5 is not waiting during syscall exit (offset 802828, time 368)
FAIL
FAIL	runtime/pprof	8.248s
```

go1.4 version: `go version go1.4.2 linux/amd64`
kernel version: `3.16.0-43-generic #58-Ubuntu SMP`
cpu: `i7-5820K`

There are no other errors during the build.
I'll continue to use go1.5beta2 and update this issue if I bump into trouble, but it looks like it's just `runtime/pprof` that has a problem. Please let me know when more information or tests are required.

**Comment by bradfitz** [comment]
Dup of #10512

**Comment by GeertJohan** [comment]
Whoops, sorry :cake:
