### ISSUE TITLE
api, cmd/api: exit status 1 during API check for Go1.5 beta 2

### ISSUE THREAD

**Issue by ajstarks** [golang/go#11752]
Running all.bash on Mac OS X 10.10.4 reports exit status 1 after the API check phase. (FWIW a working toolchain is built, and beta 1 had the same behavior)

##### API check
Error running API checker: exit status 1
Go version is "go1.5beta2", ignoring -next /Users/ajstarks/go/api/next.txt
+pkg archive/zip, method (*Writer) SetOffset(int64)
+pkg bufio, method (*Reader) Discard(int) (int, error)
+pkg bufio, method (ReadWriter) Discard(int) (int, error)
+pkg bytes, func LastIndexByte([]uint8, uint8) int
+pkg bytes, method (*Buffer) Cap() int
+pkg bytes, method (*Reader) Size() int64
 

....

+pkg unicode, var Hatran *RangeTable
+pkg unicode, var Multani *RangeTable
+pkg unicode, var Old_Hungarian *RangeTable
+pkg unicode, var SignWriting *RangeTable
exit status 1
2015/07/17 07:17:02 Failed: exit status 1

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/12325 out for review, thanks.

**Comment by tbogdala** [comment]
I have this problem with Linux x86_64 using a 1.4.2 from source as a boot strap. This is also the same problem I had with 1.5beta1 and is documented here:

https://github.com/golang/go/issues/11636

At the time, it was building (and testing) successfully from tip and it was expected that the next beta package would have the issue fixed.
