### ISSUE TITLE
tour: Page formatting with Firefox

### ISSUE THREAD

**Issue by rjmoses** [golang/go#11753]
Just an FYI:

The formatting of the page using Firefox 40/Windows 7 is very difficult to work with.  The center panel is clipped to the right and I have not found a way to change its size so that I can read the whole text.

Thanks

**Comment by ALTree** [comment]
> of the page

What page? tour.golang.org ?

**Comment by rjmoses** [comment]
1.  Bring up any page on the tour.  Two panels will be displayed.
2. Click the menu box to display the index for Using the Tour.
3. A slide out panel containing the index is displayed on the left side 
of the screen.
4. The slide out panel covers the right panel which has the description 
and text until the menu box is clicked a second time.
5. This makes it unnecessarily difficult to read sequential topis such 
as "Slices --> Slicing slices --> Making slices......"
6. While the center vertical divider bar can be adjusted to show more of 
the text, the test does not wrap---it is hidden behind the menu.

IMO, the biggest cause of stress, and therefore subliminal 
dissatisfaction and frustration, with many web sites is that they 
distract the user from what they are trying to do with fancy, glitzy 
display formatting.

The content and information in the Tour of Go is overall nicely 
presented, well organized, and simple to follow.  The menu could perhaps 
be designed differently so that it does not cover up the information the 
user is really interested in.

Thank you
Ralph Moses

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
This was due to silly mistake fixed with https://go-review.googlesource.com/12432

You can see the fix live at: http://campoy-test.appspot.com/welcome/1
