### ISSUE TITLE
go/internal/gccgoimporter: gccgoBuiltin{BYTE,RUNE} map to {uint8,int32} types instead of {byte,rune} aliases

### ISSUE THREAD

**Issue by mdempsky** [golang/go#11762]
In `go/internal/gccgoimporter`'s `lookupBuiltinType` function, there are these lines:

    661			gccgoBuiltinBYTE:       types.Typ[types.Byte],
    662			gccgoBuiltinRUNE:       types.Typ[types.Rune],

However, in `go/types`, `Byte` and `Rune` are defined as:

    const (
        Invalid BasicKind = iota // type is invalid

        /* ... */

        // aliases
        Byte = Uint8
        Rune = Int32
    )

so `types.Typ[types.Byte]` actually evaluates to the `*types.Basic` representing the universal `uint8` type rather than for the desired universal `byte` type.  `uint8` and `byte` are aliases and generally treated as identical, but they still have distinct `*types.Basic` representations (e.g., so they can each be printed appropriately).  Thus `gccgoBuiltinBYTE` should actually map to something like `types.UniverseByte` or `types.Universe.Lookup("byte").Type()`.

Similarly, `gccgoBuiltinRUNE` should map to either `types.UniverseRune` or `types.Universe.Lookup("rune").Type()`.

**Comment by mdempsky** [comment]
@robpike I've edited the issue description. Hopefully it's clearer now.

**Comment by griesemer** [comment]
@mdempsky Please separate the fix into a stand-alone change.
