### ISSUE TITLE
runtime: -buildmode=c-shared generated code hijack's signals from main program

### ISSUE THREAD

**Issue by GeertJohan** [golang/go#11794]
It looks like a shared object created with `-buildmode=c-shared` "hijack's" signal handling away from the main program.

I'm experimenting with Go shared objects as plugins. The main process has signal handling implemented to do graceful shutdown. However, the main program does not receive signals anymore after a Go shared object was loaded.

I would expect the main program to receive (and handle) the signals. Instead, signals are completely ignored. It requires `SIGKILL` to kill the process.

Simple code to reproduce:

main.go:
```go
package main

func init() {}

func main() {}
```

_main.c:
```c
#include <stdlib.h>
#include <stdio.h>
#include <dlfcn.h>

int main() {
	void *plugin;
	plugin = dlopen("./gopkg.so", RTLD_NOW);
	if (!plugin) {
		 exit(1);
	}
	
	while(1) {
		sleep(1);
	}
	
	return 0;
}
```

run:
```sh
go build -buildmode c-shared -o gopkg.so
gcc -o main _main.c -ldl
./main
ctrl-c
```

**Comment by GeertJohan** [comment]
I tried this with go1.5beta2 as well as the latest master at 1942e38

**Comment by ianlancetaylor** [comment]
This is clearly wrong, but I think the code is subtle enough that we won't be able to fix it for 1.5.

**Comment by GeertJohan** [comment]
It looks like cl 12503 fixes this partly. The signal isn't ignored anymore, but the original signal handler doesn't handle the signal either.

What do you mean with "code is subtle enough"?
Thanks!

**Comment by ianlancetaylor** [comment]
Why doesn't the original signal handler get the signal?  I thought this problem only arose when there was no original signal handler.  Do you have a test case?

This is exactly the kind of thing I mean when I say "the code is subtle enough."  The purpose of the CL is to fix issue #10139 which is a problem for regular Go code (not using c-shared).  If it fixes this issue too that is good, but it's not the goal of the CL.

**Comment by GeertJohan** [comment]
I'm sorry, when I wrote the issue I hadn't read up as much on signal handling as I have now.

So there are two cases I tested. The first one is when there is a custom signal handler set, the second one is when there is none set (as in the example in this issue).

It looks like the CL fixes the second case; SIGINT now causes the program to stop. It's not ignored anymore.

I don't have a good example for the first case as I'm not very experienced with C. 
In Aerospike database there is a custom signal handler that performs shutdown on SIGINT. (in [signal.c](https://github.com/aerospike/aerospike-server/blob/master/as/src/base/signal.c)) After loading a Go c-shared .so using dlopen that was built with go1.5beta2 the signal is completely ignored, I assume because the signal handler is overwritten by go. When a c-shared .so built with your CL is loaded, the program does not ignore the SIGINT, but it also doesn't fire the custom signal handler. Instead the program exits with `received signal interrupt`.

**Comment by ianlancetaylor** [comment]
@GeertJohan I can't recreate the problem.  Your original test case works with current tip, as I think we agree.  When I try, with current tip, a small modification of your original test case that registers a signal handler for SIGINT, I do see that signal handler installed by C being invoked when I type ^C on the keyboard.

Can you construct a stand-alone test case that shows the problem?

**Comment by GeertJohan** [comment]
@ianlancetaylor Yes, I'll try to do that.

**Comment by GeertJohan** [comment]
It looks like the problem has been completely solved. I can't recreate it anymore with current tip (`go version devel +eb248c4`).
Thanks @ianlancetaylor !

**Comment by ianlancetaylor** [comment]
Great, thanks for testing it.
