### ISSUE TITLE
net: document or fix DialTimeout regression

### ISSUE THREAD

**Issue by dsymonds** [golang/go#11796]
Since 0d8366e, `net.DialTimeout` appears to no longer respect timeouts shorter than 2s. That is, if I do a `net.DialTimeout("tcp", "some-addr", 500*time.Millisecond)` where "some-addr" is something that resolves quickly (with both IPv4 and IPv6 addresses) but doesn't respond to connections, `net.DialTimeout` takes a little over 1s to return.

This has changed since Go 1.4.2. I don't know whether this was an intentional change, or a regression; the former change warrants a mention in the release notes.

@pmarks-net @bradfitz @mikioh

**Comment by pmarks-net** [comment]
Could you clarify what problem you're seeing?  The 2s saneMinimum only affects how time is distributed across multiple addresses; it should not change the overall deadline.  The following example shows a short timeout working as expected:

    $ cat ~/test/dial_fail.go
    package main
    
    import (
            "net"
            "fmt"
            "time"
    )
    
    func main() {
            startTime := time.Now()
            conn, err := net.DialTimeout("tcp", "192.0.2.1:80", 123*time.Millisecond)
            fmt.Printf("%v %v\n", conn, err)
            fmt.Printf("Finished in %v\n", time.Now().Sub(startTime))
    }
    
    $ ../bin/go run ~/test/dial_fail.go
    <nil> dial tcp 192.0.2.1:80: i/o timeout
    Finished in 123.238884ms

**Comment by dsymonds** [comment]
Try dialing an address that resolves to both IPv4 and IPv6.

**Comment by pmarks-net** [comment]
Ah, I am able to reproduce a bug in the `partialDeadline` calculation.  When dialing 2 addresses with a 5 second timeout, the target deadline is recomputed for each address, instead of once at the beginning of `Dial`:

    $ ../bin/go run ~/test/dial_fail.go 
    partialDeadline=2.499999662s
    partialDeadline=4.999999028s
    <nil> dial tcp [2001:db8::1]:80: i/o timeout
    Finished in 7.500665372s

I introduced the bug between patch sets 3-4 of the code review:
https://go-review.googlesource.com/#/c/8768/3..4/src/net/dial.go

**Comment by pmarks-net** [comment]
There is actually a second, pre-existing bug: `DialTimeout(..., 5s)` will allocate 5 seconds to DNS resolution, and _another_ 5 seconds to TCP.

The fix for both is to call `d.deadline(...)` exactly once, at the beginning of `Dial`.
