### ISSUE TITLE
doc: clarify that new methods may be added to standard library types

### ISSUE THREAD

**Issue by mdempsky** [golang/go#11798]
Currently the go1compat document states that exported structs in the standard library may add new fields, but it doesn't mention that they may add new methods too.  To date, every Go release has added new methods to existing types.

For selector expressions, the risk of ambiguity from new methods is the same as for new fields.  But if a new method is added to a standard type that's embedded in a user type, it could cause that user type to no longer satisfy existing interfaces due to ambiguity, which is a risk unique to adding new methods.

**Comment by mdempsky** [comment]
It seems I misspoke somewhat: even adding new fields to a struct can cause method selection ambiguity that could affect interface satisfaction.

But methods can also be added to non-struct types (e.g., Go 1.1 added IsRegular to os.FileMode), so I think it's still worth clarifying.

**Comment by rsc** [comment]
Worth clarifying, but not a source of confusion, so it can wait.
