### ISSUE TITLE
runtime/pprof: TestTraceStress failing regularly on netbsd-386-minux

### ISSUE THREAD

**Issue by mdempsky** [golang/go#11808]
netbsd-386-minux has been consistently failing for some time, and almost all of them are due to "test timed out after 3m0s" failures while running TestTraceStress.

/cc @minux @4a6f656c

**Comment by dvyukov** [comment]
I suspect it can be caused by #11677 -- the machine can be swapping.
@minux can you please check how much memory and CPU the test consumes during that 3 minutes?

**Comment by rsc** [comment]
I suspect this is also #11677, because #11776 was.
