### ISSUE TITLE
cmd/go: go get -d gives needless and confusing error

### ISSUE THREAD

**Issue by robpike** [golang/go#11803]
% go get -d golang.org/x/mobile
package golang.org/x/mobile
    imports golang.org/x/mobile: no buildable Go source files in /Users/r/src/golang.org/x/mobile
%

I see this message often when I want to grab a repository but not yet build it. Maybe I am unusual in this respect, but the error message is unnecessary (I asked to download it, not build it) and odd (the two-line format is peculiar and the "imports" word seems irrelevant to the invocation).

**Comment by adg** [comment]
This is working as intended according to #11090.

**Comment by robpike** [comment]
That issue doesn't address the weird message, only the presence of one.

**Comment by adg** [comment]
The message is presented because you have asked the go tool to download
this package and its dependencies, but there is no package there.

Assuming that such a message should be presented (what the other issue is
about), what should it say instead?

**Comment by robpike** [comment]
Just please tell me what
"imports golang.org/x/mobile: " is doing in this message.

**Comment by ALTree** [comment]
go1.8 error message:

> package golang.org/x/mobile: no buildable Go source files in [...]/src/golang.org/x/mobile

no weird circular dependency message, so it looks like this is fixed.
