### ISSUE TITLE
x/mobile: basic demo on andorid has slight GUI race conditions bug

### ISSUE THREAD

**Issue by gedw99** [golang/go#11804]
golang.org/x/mobile/example/basic
its a UI interaction bug.

Context:
gedw99-MacBook-Pro:audio apple$ go version
go version go1.5beta2 darwin/amd64

gedw99-MacBook-Pro:audio apple$ which go
/usr/local/go/bin/go
gedw99-MacBook-Pro:audio apple$ 

Steps to reproduce:
compile for android
load apk on nexus 6
open program and it works fine.
hit home button
open program and it works fine
hit back button
open program and it shows a dithered triangle.
- it looks like 2 programs running on top of each other with a alpha transparency between them.

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by crawshaw** [comment]
Thanks for the report. On a Galaxy Nexus I see some kind of crash for open->back button->open. This is probably a recent regression (due to our lack of good integration testing for apps). I'll take a look.

**Comment by gedw99** [comment]
happy to report it. thanks for your hard work.

In relation to what you get on the Galaxy Nexus, the crash is visual or on log files ? On nexus 6 the GUI does not crash, just has this weird dithering on the triangle. i did not check the logs.
