### ISSUE TITLE
net/http: Extend to allow client certificate authentication for HTTPS?

### ISSUE THREAD

**Issue by Term1nal** [golang/go#11802]
I suggest that it might be quite nice to extend the standard library for HTTPS servers to be able to easily specify client certificates for use in authentication of connections. If this is already possible, I have not found the necessary documentation to assist in that end, but an API exposure of this sort would be quite nice!

**Comment by bradfitz** [comment]
Use make your own `*http.Client` with its own `*http.Transport` as the `RoundTripper` and set `net/http.Transport.Dial` to use `crypto/tls.Dial` with a `*tls.Config` which includes `Certificates`.

We probably won't make this any easier, as it's an uncommon request and already composeable with the pieces provided.

**Comment by Term1nal** [comment]
I'm sorry if I wasn't clear enough, but I did specify that this was for the server-side. Not client. (As in, the Go HTTPS server library being able to authenticate connecting clients).

Though after some digging it looks like it can possibly be modified [here(http://golang.org/src/net/http/server.go#L1853) where the config is specified.

Combined with some of the logic pulled from [here](https://github.com/hydrogen18/test-tls/blob/master/common.go#L35)

**Comment by bradfitz** [comment]
Sorry. Can't you just check the request.TLS field to see the cert presented?

**Comment by Term1nal** [comment]
Yeah, looks like I can. In [this](https://github.com/hydrogen18/test-tls/blob/master/common.go#L35) bit of code, however, it looks like the config is built with the client authentication in mind. I could see a function like:
```
http.ListenAndServeTLSAuth(":8080", nil, "clientcerts.pem")
```
... being something that could be useful.

**Comment by Term1nal** [comment]
Looks like this too suffices:

```
package main

import (
    "crypto/tls"
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Hello cert")
    })

    server := &http.Server{
        Addr: ":8090",
        TLSConfig: &tls.Config{
            ClientAuth: tls.RequireAndVerifyClientCert,
        },
    }

    server.ListenAndServeTLS("cert.pem", "cert.key")
}
```
