### ISSUE TITLE
io: add WriteString support to io.MultiWriter

### ISSUE THREAD

**Issue by josharian** [golang/go#11805]
No API changes necessary.

Are there any other writers in the stdlib that should have WriteString implemented as well?

**Comment by cespare** [comment]
I must be missing something. `io.MultiWriter` returns an `io.Writer`, so you'd need an interface assertion to take advantage of this, correct? Is there some `ReaderFrom`-style optimization that I'm not aware of that this would enable?

**Comment by bradfitz** [comment]
CL https://golang.org/cl/12485 mentions this issue.

**Comment by josharian** [comment]
@cespare  `io.WriteString` checks whether the `Writer` implements `WriteString`. See http://golang.org/src/io/io.go?s=9776:9831#L268.

@bradfitz that was fast. :) I thought I was going to have more time to poke around and check the rest of the writers, particular net/http's default responseWriter.

**Comment by bradfitz** [comment]
net/http's responseWriter already does WriteString.
