### ISSUE TITLE
cmd/compile: include name in "unexpected name" error message

### ISSUE THREAD

**Issue by InstanceOfMichael** [golang/go#11814]
Context: http://tour.golang.org/flowcontrol/8

```
func Sqrt(x float64) float64 {
    z := float64(1)
	
    z = z - (z^2 - x)/2z
	
    return z
}
```
I get the same results for:

```
   z = z - math.Pow(z,2) - x/2z;
```

results:
```
/tmp/sandbox898777084/main.go:10: syntax error: unexpected name, expecting semicolon or newline or }
```

Looks like I can't progress on the problem because I'm stuck on syntax.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
The syntax error is `2z`. You need an operator between the `2` and the `z`. I think what you want is `2*z`.

We could probably improve the compiler error. Maybe it could say what the unexpected name was ("z"?).

**Comment by rsc** [comment]
With Robert's new parser the error is:

    /tmp/x.go:6: syntax error: unexpected z at end of statement

Clear enough I think.
