### ISSUE TITLE
x/build: build sub-repos on darwin buildlets

### ISSUE THREAD

**Issue by adg** [golang/go#11812]
I think this might just be a flag flip in the dashboard config package.

cc @bradfitz

**Comment by bradfitz** [comment]
Yes, perhaps.

But in general I don't touch the OS X stuff because I don't have access to the buildlets, so I'm always afraid of breaking them. @crawshaw, can you email me details? I also hear the OS X machines might be spinning right now, causing tests to fail and timeout.

**Comment by crawshaw** [comment]
@bradfitz details emailed

I believe the recent report of OS X spinning is the old darwin-amd64 and darwin-386 builders, which are not on the mac minis in ATL. Only darwin-amd64_10_10 is, and it looks fine.

**Comment by rsc** [comment]
Any progress here?

**Comment by bradfitz** [comment]
Confirmed that @adg is on it.
