### ISSUE TITLE
runtime: getproccount fails on systems with large CPU masks

### ISSUE THREAD

**Issue by fweimer** [golang/go#11823]
`runtime.getproccount()` lacks a retry loop with a growing buffer.  If the kernel CPU mask exceeds the supplied size (1024 bits), `r` will be an error code, and the function will panic.

This is from a system with a CPU mask size of 4096 bits:

    panic: nil
    fatal error: panic on system stack
    runtime: panic before malloc heap initialized
    
    runtime stack:
    fatal error: gentraceback before goexitPC initialization
    runtime: panic before malloc heap initialized
    panic during panic
    
    runtime stack:
    fatal error: gentraceback before goexitPC initialization
    runtime: panic before malloc heap initialized
    stack trace unavailable

Note that the kernel CPU mask may be significantly larger than the number of threads supported by the system, depending on the CPU topology reported by the firmware to the kernel.

**Comment by rsc** [comment]
Started.
