### ISSUE TITLE
cmd/go: parallelize go get downloads

### ISSUE THREAD

**Issue by jacobsa** [golang/go#11821]
Running `go get -u` for an app with a decent number of dependencies can be extremely slow from a location with high latency to GitHub (and other code hosts, too -- it's even worse when there are redirects involved). For example, from my machine in Sydney the following command takes almost 90 seconds to download 18 repos:

```
go get -v -u -t github.com/googlecloudplatform/gcsfuse/...
```

This is in stark contrast to general use of the `go` command, which is otherwise pleasantly fast.

I notice that downloads happen serially. It seems like `go get` could benefit greatly from doing them concurrently. Are there any major obstacles to doing so?

**Comment by rsc** [comment]
The main obstacle is that you have to fetch A to find out that it imports B and C.
But we could parallelize B and C.

**Comment by nightlyone** [comment]
There are also rate-limit issues. 

e.g. common setup is to use a shared ssh session to github (sort of a connection pool via `ControlPersist yes` option) and there are only 10 concurrent connections allowed over that one (hard coded limit in openssh deamon).

So this feature would need a bunch of tuneables.

A different approach to target the increasing complexity of `go get` and vastly different usage profiles might be a git like plugin architecture for the whole vcs part.

**Comment by powerman** [comment]
Is this correct way (in case GOPATH contains exactly one element) to speedup `go get -v -t -u all`?
```sh
find $GOPATH/src -type d -name .git -printf "%h\0" |
    xargs -0 -P64 -I{} sh -c "cd {}; git pull; git submodule update"
go get -v -t all
```
I suppose it may miss some corner cases like default branch change on GitHub, but I'm not sure is `go get -u` handle such cases too.

**Comment by bcmills** [comment]
Module downloads are performed in parallel. I don't think that retrofitting `GOPATH` mode to do so would be worth the effort.
