### ISSUE TITLE
Golang ioutil.ReadAll(resp.Body) results in EOF errors which is caused by TCP window full

### ISSUE THREAD

**Issue by Bubbachuck** [golang/go#11820]
When I use http.get to download a file from website as follow:

 resp, err := http.Get(url)
        if err != nil {
                log.Fatal(err)
        }
        defer resp.Body.Close()
        io, err_read := ioutil.ReadAll(resp.Body)
        if err_read != nil {
                log.Fatal(err_read)
        }

An EOF error will happen as follow:

2015/07/22 17:31:49 Get http://xxxxxxxxxxxxxxxxxDE=1?749da030: EOF
exit status 1

I captured the packets between client and server and found tcp window full in client.
"Expert Info (Warn/Sequence): TCP transmission window is now completely full"

There will be so many tcp re-transmission happened  that the server close the connection.

Who could help to look into this issue?

**Comment by bradfitz** [comment]
This doesn't sound like a Go question. You can try asking on golang-nuts@ though and see if anybody has networking advice for you.
