### ISSUE TITLE
net: UnixListener unlinks socket files inherited via socket activation

### ISSUE THREAD

**Issue by mischief** [golang/go#11826]
docker can use systemd for socket activation. docker creates a net.UnixListener using net.FileListener on the inherited fd. naturally, upon shutdown, docker calls Close on the net.Listener.

in [unixsock_posix.go](https://github.com/golang/go/blob/master/src/net/unixsock_posix.go#L321), Close calls syscall.Unlink on the file name that was found via getsockname. this code has been there since at least 2011.

the result of this is that upon the socket-activated service (docker) restarting, the service will reconnect to the inherited file descriptor, but clients of that socket will no longer be able to reach it because the socket file in the filesystem is gone, and never recreated.

this seems to have been worked around in docker in docker/docker@053c3557b3198466ecfbe066fefdbab2a78771d5, but this affects any socket-activated go program that 'properly' Closes it's UnixListeners.

if the UnixListener was not responsible for creating the socket file, it should *not* unlink the socket file on Close.

**Comment by tv42** [comment]
This can be triggered without docker, systemd, etc by e.g. passing an FD of a listening unix domain socket to multiple children, each child using `net.FileListener` and running its own Listen+Accept loop. When the first child exits, it'll also remove the socket file, preventing new client connections.
