### ISSUE TITLE
x/sys/unix: No clean way to call `utimes(path, NULL)` or friends

### ISSUE THREAD

**Issue by tv42** [golang/go#11830]
The kernel differentiates between setting time to *now* vs setting it to some timestamp (that may be very very recent past). For example, FUSE sets a separate flag that signals this:

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=17637cbaba592076c221dc045ca78422b4af6290

This is normally achieved by passing NULL as times to utimes(2) and friends.

The Go syscall wrappers all explicitly prevent this:

```go
func Utimes(path string, tv []Timeval) (err error) {
	if len(tv) != 2 {
		return EINVAL
	}
	return utimes(path, (*[2]Timeval)(unsafe.Pointer(&tv[0])))
}
```

My use case: I wanted to write a FUSE unit test that behaves like touch, and actually causes that flag to be set. Measuring current time and passing it as argument is not good enough.

**Comment by bradfitz** [comment]
Seems like an easy enough fix. Want to send a CL?

```go
// Utimes blah blah. If tv is nil, blah. Otherwise tv must contain exactly 2 items and blah.
func Utimes(path string, tv []Timeval) (err error) {
    if tv == nil {
        return utimes(path, nil)
    }
    switch len(tv) != 2 {
        return EINVAL
    }
    return utimes(path, (*[2]Timeval)(unsafe.Pointer(&tv[0])))
}
```

**Comment by tv42** [comment]
Sorry, I'm not very thrilled about CLAs, and have not signed the Google CLA.

**Comment by ebfe** [comment]
As a workaround

    const UTIME_NOW = (1<<30)-1
    UtimesNano(path, []Timespec{{0, UTIME_NOW}, {0, UTIME_NOW}})

might work.

**Comment by tv42** [comment]
This leaves a bunch of the sister calls, and platforms other than linux, still enforcing that logic.

```
$ git grep -B 1 'len\(.*\) != 2'|grep func|grep -v Pipe
unix/syscall_bsd.go-func Utimes(path string, tv []Timeval) (err error) {
unix/syscall_bsd.go-func Futimes(fd int, tv []Timeval) (err error) {
unix/syscall_linux.go-func UtimesNano(path string, ts []Timespec) (err error) {
unix/syscall_linux.go-func UtimesNanoAt(dirfd int, path string, ts []Timespec, flags int) (err error) {
unix/syscall_linux.go-func Futimesat(dirfd int, path string, tv []Timeval) (err error) {
unix/syscall_solaris.go-func UtimesNano(path string, ts []Timespec) (err error) {
windows/syscall_windows.go-func Utimes(path string, tv []Timeval) (err error) {
windows/syscall_windows.go-func UtimesNano(path string, ts []Timespec) (err error) {
```
