### ISSUE TITLE
panic with "go help documentation | head"

### ISSUE THREAD

**Issue by jeffallen** [golang/go#11839]
$ go help documentation | head
// Copyright 2011 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT THIS FILE. GENERATED BY mkalldocs.sh.
// Edit the documentation in other files and rerun mkalldocs.sh to generate this one.

/*
Go is a tool for managing Go source code.

panic: template: top:9:47: executing "top" at <

>: write /dev/stdout: broken pipe

goroutine 1 [running]:
main.tmpl(0xb64220, 0xc82002a010, 0x6251c0, 0x1c5, 0x3dcca0, 0xc820185880)
	/Users/jeffall/go/src/cmd/go/main.go:243 +0x403
main.help(0xc82000a320, 0x1, 0x1)
	/Users/jeffall/go/src/cmd/go/main.go:292 +0x4bf
main.main()
	/Users/jeffall/go/src/cmd/go/main.go:129 +0x180

The panic() in go tool's tmpl() function does not belong there; getting an error white writing to a file descriptor is not wholly unexpected.

$ go version
go version devel +aad4fe4 Thu Jul 23 05:50:53 2015 +0000 darwin/amd64

**Comment by mdempsky** [comment]
Similar problem with godoc too:

    $ godoc runtime | head -0
    2015/07/24 10:01:01 template: package.txt:14:28: executing "package.txt" at <PACKAGE DOCUMENTATIO...>: write /dev/stdout: broken pipe
