### ISSUE TITLE
x/mobile/bind: Second string argument in Objective-C generated functions is empty

### ISSUE THREAD

**Issue by mpiannucci** [golang/go#11842]
When a function with two string arguments is generated, the Objective-C binding doesn't pass the second string correctly if the first string argument is longer than 11 characters. 

For example, with the function:
```go
func(e *ExampleStruct) TryTwoStrings(first, second string) {
    fmt.Println("First: " + first)
    fmt.Println("Second " + second)
}
```
If it is called with an instance of `ExampleStruct`
```Objective-C
[exampleStruct TryTwoStrings:@"trytwotests" second:@"test"]
```
the output is as expected:
```
First: trytwotests
Second: test
```
But if the `trytwotests`string is made longer, the output is incorrect:
```Objective-C
[exampleStruct TryTwoStrings:@"trytwotested" second:@"test"]
```
```
First: trytwotested
Second: 
```

Go version:
```
go version devel +328ff1f Mon Jul 20 23:36:13 2015 +0000 darwin/amd64
```

**Comment by crawshaw** [comment]
CC @hyangah
