### ISSUE TITLE
tour: description does not match code

### ISSUE THREAD

**Issue by bruceadowns** [golang/go#11849]
Context: https://tour.golang.org/moretypes/18

The following text should change from:
Test that a key is present with a two-value assignment:
elem, ok = m[key]

to:
Test that a key is present with a two-value assignment:
elem, ok := m[key]

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by robpike** [comment]
It's fine as is. This is a two-value assignment. elem, ok := m[key] is a declaration. Yes, the distinction can be subtle for newcomers but it is important not to confuse the terminology in this tour.

It might make sense to add some explanatory or alternate text using := but not to change this one.

**Comment by campoy** [comment]
Proposal: https://go-review.googlesource.com/#/c/12714/

**Comment by campoy** [comment]
change merged and deployed
