### ISSUE TITLE
cmd/compile: use named types for etype, op

### ISSUE THREAD

**Issue by josharian** [golang/go#11846]
This came up again in CL 12362.

Then they could have nice String methods and have type-safe usage in SSA world.

Related: Econv does not use its flag argument. Let's remove it.

**Comment by stemar94** [comment]
Does the Gobot only track CL which do not have an 'DO NOT SUBMIT' or 'DO NOT REVIEW'? 
Here is a CL https://go-review.googlesource.com/#/c/14956/
