### ISSUE TITLE
cmd/compile: 1.5 Beta 2: Compilation seems significantly slower and less efficient than 1.4

### ISSUE THREAD

**Issue by aviflax** [golang/go#11859]
> What version of Go are you using (go version)?

`go version go1.5beta2 darwin/amd64` installed via the installer downloaded from golang.org and `go version go1.4.2 darwin/amd64` installed by Homebrew (IIRC).

> What operating system and processor architecture are you using?

Mac OS X 10.10.4, amd64

> What did you do?

Compiled my program with 1.5 beta 2.

> What did you expect to see?

Compilation times that would be less than 2x those of 1.4.2.

> What did you see instead?

```
$ GOPATH=`godep path`:$GOPATH time go15 build ./...
       12.54 real        31.73 user         5.14 sys
$ GOPATH=`godep path`:$GOPATH time go15 build ./...
       12.39 real        31.76 user         5.08 sys
$ rm -Rf `godep path`/pkg/* $GOPATH/pkg/*
$ GOPATH=`godep path`:$GOPATH time go14 build ./...
        5.18 real         9.51 user         2.25 sys
$ GOPATH=`godep path`:$GOPATH time go14 build ./...
        4.66 real         9.49 user         2.12 sys
```

**Comment by ALTree** [comment]
> What did you expect to see?
> Compilation times that would be less than 2x those of 1.4.2.

Unfortunately this won't be true for go 1.5. From the [release notes](http://tip.golang.org/doc/go1.5#performance):

> Builds in Go 1.5 will be slower by a factor of about two.

So the slowdown you are seeing is expected.

**Comment by aviflax** [comment]
@ALTree I’m not good with math, but 12.39 seems like way more than double 4.66. And the CPU usage! I’m worried about my battery life!

**Comment by josharian** [comment]
@aviflax 2x is not a hard and fast number. If you were experiencing a 20x slowdown, this would be more pressing, but 2.65x is not dramatically out of range. (And yes, the slowdown is very unfortunate. I am not happy about it either.) All that said, is your program available somewhere? I doubt that there is anything safe that could be done to address it at this point in the release cycle, but if we can reproduce it, that'll help with Go 1.6 speed-up efforts.

**Comment by aviflax** [comment]
@josharian TBH, I figured. I still thought it might be helpful to report what I’m seeing. Unfortunately this is a private and proprietary program; I can’t share its source without at least an NDA and certainly not publicly. If it helps, according to [cloc](http://cloc.sourceforge.net) it has 121,123 lines of code (excluding comments and blanks) across 1,059 files. That’s including all vendored dependencies — as far as I can tell it excludes only the standard library. And I’m pretty sure all those files are included in compilation — we use Godep and I _think_ it only includes the specific packages that our program actually uses.

**Comment by josharian** [comment]
Ok, thanks. The LOC count doesn't matter as much as what the actual lines are. :) If you want to poke at it more, you can run the compiler and linker with cpu and memory profiling enabled and share your findings in case there is anything usual. However, given the slowdown level you report, I'd guess that there's nothing peculiar to your code base. I'm going to close this for now. Feel free to reopen if you have significant new info.
