### ISSUE TITLE
cmd/go: go install complains about GOBIN being set even when it's not

### ISSUE THREAD

**Issue by mdempsky** [golang/go#11851]
I was curious where executables end up when cross-compiling with "go install", so I thought I'd try it out with a random command:

    $ GOARCH=386 GOOS=openbsd go install code.google.com/p/codesearch/cmd/cgrep
    go install: cannot install cross-compiled binaries when GOBIN is set

However, this seems like an odd error message since I don't have GOBIN set:

    $ GOARCH=386 GOOS=openbsd go env
    GOARCH="386"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="openbsd"
    GOPATH="/usr/local/google/home/mdempsky/go"
    GORACE=""
    GOROOT="/usr/local/google/home/mdempsky/wd/go"
    GOTOOLDIR="/usr/local/google/home/mdempsky/wd/go/pkg/tool/linux_amd64"
    GO15VENDOREXPERIMENT=""
    CC="gcc"
    GOGCCFLAGS="-fPIC -m32 -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="0"

**Comment by ianlancetaylor** [comment]
Dup of #11778 .
