### ISSUE TITLE
using redirection symbol '<' '>' failed

### ISSUE THREAD

**Issue by liugangnhm** [golang/go#11866]
when an using exec.Cmd to fock an subprocess,with redirection like cat xxx > /tmp/xxxx ,it will always fail.

```go
cmd:=exec.Command("cat","./aaa",">","/tmp/aaa")
cmd.Start()
err:=cmd.Wait()
if err!=nil {
    t.Errorf("exit error %s", err)
}

```

wheather /tmp/aaa is exist or not, error is always "exit status 1" .
file aaa is always exist.

when i set cmd's Stderr to bytes.Buffer ,and i see  detail error:"cat: >d: no such file or directory". so i think go maybe treat '>' as a file name. 

so how should i do when i want to use redirection symbol in command

**Comment by liugangnhm** [comment]
go version: 1.4.1 linux/amd64
os version:ubuntu 14.10 amd64

**Comment by crawshaw** [comment]
The > is a feature of your shell language. To use it, you need to run your command inside a shell. Perhaps something like

```cmd := exec.Command("bash", "-c", "echo hello > /tmp/aaa")```

Be careful with this though. If you construct a string and pass it to a shell, you need to think carefully about escaping and security. For the particular example you give, you may want to consider using os.Open, os.Create, and io.Copy.

**Comment by liugangnhm** [comment]
just talk about `cat`

```go
package main

import (
	"bytes"
	"os/exec"
	"testing"
)

func TestExe1(t *testing.T) {

	out := &bytes.Buffer{}

	cmd := exec.Command("bash", "-c", "cat ./file_not_exist > /tmp/aaa")
	cmd.Stderr = out
	err := cmd.Start()
	if err != nil {
		t.Errorf("start error %s [%s]", err, out.String())
	}
	err = cmd.Wait()
	if err == nil {
		t.Errorf("exit error %s [%s]", err, out.String())
	}

	cmd = exec.Command("bash", "-c", "echo hello > /tmp/aaa")
	err = cmd.Start()
	if err != nil {
		t.Errorf("start error %s [%s]", err, out.String())
	}
	err = cmd.Wait()
	if err == nil {
		t.Errorf("exit error %s [%s]", err, out.String())
	}

	cmd = exec.Command("bash", "-c", "cat ./myself_test.go > /tmp/aaa")
	err = cmd.Start()
	if err != nil {
		t.Errorf("start error %s [%s]", err, out.String())
	}
	err = cmd.Wait()
	if err != nil {
		t.Errorf("exit error %s [%s]", err, out.String())
	}
}
```

output is 
`golang_test.go:41: exit error exit status 1 [bash: /tmp/aaa: Permission denied`

why `cat` is particular?

**Comment by ianlancetaylor** [comment]
@liugangnhm We prefer to use the issue tracker for bug reports.  Please ask questions on the golang-nuts mailing list, not on the issue tracker.  Thanks.

**Comment by liugangnhm** [comment]
all right,thanks.
