### ISSUE TITLE
cmd/cgo: ${SRCDIR} doesn't properly handle paths with spaces

### ISSUE THREAD

**Issue by jtsylve** [golang/go#11868]
Given a cgo directive like the following

```go
//#cgo CFLAGS: -I${SRCDIR}/../../include
```

I get the following error

> malformed #cgo argument: -IC:/Users/Joe Sylve/go/src/go4n6/disk/vmdk/../../include

Neither of the following seem to make much of a difference

```go
//#cgo CFLAGS: -I"${SRCDIR}/../../include"
```

```go
//#cgo CFLAGS: -I\"${SRCDIR}/../../include\"
```

Tested on go1.5beta2 on both 32 and 64 bit Windows.

**Comment by alexbrainman** [comment]
Please, provide instructions to reproduce your issue. Thank you.

Alex

**Comment by mattn** [comment]
```
C:\>mkdir "foo bar"

C:\>cd "foo bar"

C:\foo bar>type con > main.go
package main

//#cgo CFLAGS: -I${SRCDIR}/../../include
import "C"

func main() {
}
^Z

C:\foo bar>go build
can't load package: package .: c:\foo bar\main.go: malformed
#cgo argument: -IC:/foo bar/../../include
```

**Comment by mattn** [comment]
This is depend on behavior of escape arguments on unix-shell or cmd.exe.

**Comment by alexbrainman** [comment]
Thank you @mattn. This is how it works on linux too:
```
# pwd
/root/src/issue 11868
# cat main.go
package main
//#cgo CFLAGS: -I${SRCDIR}/../../include
import "C"
func main() {
}
# go build
can't load package: package issue 11868: /root/src/issue 11868/main.go: malformed #cgo argument: -I/root/src/issue 11868/../../include
#
```
It appears we don't allow space inside of #cgo line parameters. I don't know why is that. Leaving for others to explain.

Alex

**Comment by ianlancetaylor** [comment]
It's a bug.

I don't know if changing safeCgoName in go/build/build.go is sufficient, or whether we need to add quoting somewhere.

**Comment by mattn** [comment]
gcc doesn't allows `"-I/path/to directory"`. it should be `-I"/path/to directory"`. (at least, on windows)

**Comment by jtsylve** [comment]
Has there been any more thoughts on how this can be fixed?  If someone could point me in the right direction, I'd be happy to try to fix it myself.

**Comment by ianlancetaylor** [comment]
@jtsylve Thanks--I would start with my suggestion above: look at safeCgoName in go/build/build.go.  Fix that to accept spaces.  Then make sure any necessary quoting is done.

**Comment by rsc** [comment]
It is important that an attempted fix here does not allow spaces in other places. Changing safeCgoName sounds dangerous.

It does seem reasonable that ${SRCDIR}'s expansion should be properly handled even when that variable contains spaces.

**Comment by jtsylve** [comment]
The issue is more complicated than just changing `safeCgoName`, unfortunately.  In order to make it work correctly with gcc we need to allow quotes.  `splitQuoted` tends to affect this negatively.  I have yet to come up with a reasonable solution.

**Comment by jtsylve** [comment]
Under which cases is `splitQuoted` needed and when should we avoid spaces as @rsc mentioned?
