### ISSUE TITLE
go get github.com/golang/mobile/cmd/gomobile fails

### ISSUE THREAD

**Issue by zgiber** [golang/go#11867]
OS X - Go 1.5beta2, darwin, amd64

I'm getting this error instead of the usual (nothing):

> go get golang.org/x/mobile/cmd/gomobile
# golang.org/x/mobile/bind
./gengo.go:376: undefined: types.RelativeTo
./gengo.go:376: cannot use typ (type types.Type) as type *types.Package in argument to types.TypeString
./gengo.go:384: undefined: types.RelativeTo
./gengo.go:384: cannot use typ (type types.Type) as type *types.Package in argument to types.TypeString
./gengo.go:396: undefined: types.RelativeTo
./gengo.go:396: cannot use typ (type types.Type) as type *types.Package in argument to types.TypeString

Thank you.

**Comment by crawshaw** [comment]
I believe your x/tools repository is out of date. Sync that repository, possibly with go get -u, and try the build again.

**Comment by zgiber** [comment]
Indeed. Thanks!
