### ISSUE TITLE
proposal: 'go get’ tool support http or ftp directly download source file.

### ISSUE THREAD

**Issue by tomheng** [golang/go#11876]
indeed, we only need a snapshot of source code, not all commit history of the code.

now ‘go get’ just support vcs(e.g. git), all them will pull a complete repo to local disk and then checkout a new 

work copy of repo.

something i considered:

* burden of network downloading
* latest checkout work copy maybe not working(a expertise commit)

we can make ‘go get’ support directly download the source file(http or ftp) through go-import meta tag.

```
<meta name="go-import" content="github.com/golang/go file https://github.com/golang/go/releases/tag/go1.5beta2
">
```

**Comment by adg** [comment]
I don't see this proposal as compelling. There's no way to make the `-u` flag work as-is, and if we set about devising a means of making it work then we start to reinvent git. I'm going to close this as nobody else has shown interest since it was proposed.
