### ISSUE TITLE
runtime/cgo: tip fails to build on darwin/arm64

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11884]
After https://golang.org/cl/12574, the darwin arm64 builds have started failing with

runtime/cgo
# runtime/cgo
runtime/cgo/gcc_arm64.S:16:1: error: expected identifier or '('

I don't understand why that CL caused this problem.

The line in question is:

.align	2

which seems harmless enough.

Needs to be debugged by somebody with a darwin arm64 system.

CC @crawshaw @rsc

**Comment by crawshaw** [comment]
I thought I had patched and tested that CL, but it looks like I patched one client and tested another. I'll take a look.

**Comment by crawshaw** [comment]
The change is that the CFLAGS: -x objective-c in tmpdir_darwin.go means that gcc_arm64.S is now compiled with that flag:

```clangwrap.sh -I . -fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/runtime/cgo/_obj/ -g -O2 -Wall -Werror -x objective-c -o $WORK/runtime/cgo/_obj/gcc_arm64.o -c ./gcc_arm64.S```

...which doesn't work.

**Comment by crawshaw** [comment]
Fixing that problem, I recall why this code ended up in package os. We need to modify memory owned by package syscall. It appears syscall cannot call cgo (an import cycle is reported), and it appears that the cgo neither imports syscall today, nor can it handle any interesting cgo definitions or uses in its go code.

Still looking for a way out.
