### ISSUE TITLE
regexp: bug in submatch functions?

### ISSUE THREAD

**Issue by ghbutton** [golang/go#11899]
I was trying to use regexp to do some pattern matching with the or operator but I got some odd results. I have stripped out everything but the essentials to show the problem with my result.

This is my code:
```golang
package main

import "fmt"
import "regexp"

func main() {
	authRegexp := regexp.MustCompile("^token=(llll|(.+))$")
	matches := authRegexp.FindStringSubmatch("token=llll")
	fmt.Println("MATCHES", matches, len(matches))
        // MATCHES [token=llll llll ] 3
}
```

Url: http://play.golang.org/p/nLtWQQgveY

The matches array has a length of 3, when I think it should have a length of 2. The last value is an empty string. I dont understand why it does this. Is this a golang bug? How do I submit golang bugs?

**Comment by adg** [comment]
It's not a bug. You have two submatches, and the entire expression is returned as submatch 0. That's three. Here's the relevant portion of the docs:

> If 'Submatch' is present, the return value is a slice identifying the successive submatches of the expression. Submatches are matches of parenthesized subexpressions (also known as capturing groups) within the regular expression, numbered from left to right in order of opening parenthesis. Submatch 0 is the match of the entire expression, submatch 1 the match of the first parenthesized subexpression, and so on.
