### ISSUE TITLE
net/http: json decoding fails from httptest in tip, works in 1.4 and over bytes.Buffer

### ISSUE THREAD

**Issue by ThomasHabets** [golang/go#11893]
# Code
http://play.golang.org/p/DPZUao3rPB

# Should output (and does under Go 1.4)
```
Decoding with bytes.Buffer: <nil>, {"bar"}
Decoding with http stream: <nil>, {"bar"}
Decoding with http stream bouncing on bytes.Buffer: <nil>, {"bar"}
Yes, "{ \"foo\": \"bar\" }" really is "{ \"foo\": \"bar\" }"
```

# With tip(129cfa2745a3db0fd55fd13fd46da0e75b9ce7dc) outputs
```
$ go run lalatest.go
Decoding with bytes.Buffer: <nil>, {"bar"}
Decoding with http stream: EOF, {""}
Decoding with http stream bouncing on bytes.Buffer: <nil>, {"bar"}
Yes, "{ \"foo\": \"bar\" }" really is "{ \"foo\": \"bar\" }"
```

# Expected
not EOF. Doesn't matter which io.Reader it's read from, it should either be seen as valid or it shouldn't.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bradfitz** [comment]
This is a recent regression.

Trying to find where. Rev a60c536 is bad.

**Comment by bradfitz** [comment]
Rev 9c55792 is good, and rev 0cf48b4 is bad. So the break came at:
0cf48b4: encoding/json: add JSON streaming parse API

/cc @rsc

**Comment by rsc** [comment]
Fixed by CL 12726 and by CL 12740. (The release is getting closer so we double-fix things now.)
