### ISSUE TITLE
text/template: distinguish write errors from template errors

### ISSUE THREAD

**Issue by robpike** [golang/go#11898]
See https://github.com/golang/go/issues/11845

The template package is being blamed (unfairly in my opinion) for issues around SIGPIPE, but there is a fair point to be made: The template package should make it easy to distinguish errors caused by execution from errors caused by I/O. The former is a programming problem that should be fixed; the latter is just bad luck. A conscientious program (like cmd/go) could act differently in the two cases.

**Comment by bradfitz** [comment]
> The template package should make it easy to distinguish execution errors caused by execution from errors caused from I/O.

Not just the template package, though. I needed this distinction in `net/http` the other day, and I always finding myself writing little helper functions like,

```go
func isNetWriteError(err error) bool {
	switch e := err.(type) {
	case *url.Error:
		return isNetWriteError(e.Err)
        case *net.OpError:
		return e.Op == "write"
        default:
		return false
	}
}
```

Maybe we put some of those style helpers in a common package?
