### ISSUE TITLE
x/mobile/misc/androidstudio: gobind plugin fails with 'no Go tool on $PATH' error

### ISSUE THREAD

**Issue by dbaroncelli** [golang/go#11895]
I changed my exposed Go functions names, and then run again
./gomobile bind -target=android testgolibrary

but the .aar library doesn't seem to include the changes
I even tried importing the .aar file from a fresh Android project, and it still reports the old functions

I then renamed the Go package and created a new library with the new package name
./gomobile bind -target=android testgolibrary2
I imported it from the Android project and this time I would see the new functions

Using MacOS

**Comment by hyangah** [comment]
Unfortunately, I couldn't reproduce the problem. How did you import the .aar file from your android studio? If you import it using the default .aar file import option from Android Studio, it actually copies the .aar file into the module directory. Either you have to copy the output of gomobile to the module directory, or specify output directory to point to the module directory or use the plugin in https://plugins.gradle.org/plugin/org.golang.mobile.bind (warning: it's beta)

**Comment by dbaroncelli** [comment]
@hyangah it's interesting to be able to use a gradle plugin for that

there is no documentation, can you explain how it's the process when using the plugin?

many thanks

**Comment by hyangah** [comment]
https://go-review.googlesource.com/#/c/12800/ has an example.
hello/build.gradle is the relevant file. 
We plan to post more detailed instruction in wiki soon.

**Comment by dbaroncelli** [comment]
@hyangah, I am getting this error in Android Studio:
org/golang/mobile/GobindPlugin : Unsupported major.minor version 52.0

I am using MacOS, with JRE 6 and JDK 7 (as recommended by Android Studio requirements)

**Comment by hyangah** [comment]
Unintentionally used jdk8. Will upload a new version later tonight.

**Comment by dbaroncelli** [comment]
infact, I have found out that it works with JDK8

**Comment by dbaroncelli** [comment]
@hyangah, I found some other issues with the plugin:

1)
- if I run the "gobind" task from the AndroidStudio IDE, I get the error
/var/go/bin/gomobile: no Go tool on $PATH
- if instead I run from the command line:
./gradlew gobind
there are no errors and an .aar file gets created in the Android project directory with the name of the Android project, and not with the name of the Go package I specified in the build.gradle file (is it intended?)

2)
In order to be able to use the functions defined in the Go package, I then add the .aar file to the project (is this what is supposed to be done?). When I do that, a subdirectory with the same name of the .aar file (and hence the name of the Android project) gets created and the .aar file is moved from the project directory to this subdirectory.
I can now successfully access all the Go functions defined in this .aar which has been moved to such subdirectory.

3)
If I run "./gradlew gobind" again, an .aar file gets added again to the project directory, but the .arr file of the subdirectory (which is the one linked to the Android project) doesn't get updated

**Comment by hyangah** [comment]
2015-07-29 21:47 GMT-04:00 dbaroncelli <notifications@github.com>:

> @hyangah <https://github.com/hyangah>, I found some other issues with the
> plugin:
>
> 1)
>
>    - if I run the "gobind" task from the AndroidStudio IDE, I get the
>    error /var/go/bin/gomobile: no Go tool on $PATH
>
> Does your PATH param in the hello/build.gradle include the path to your go
tool?


>    - if instead I run from the command line: ./gradlew gobind there are
>    no errors and an .aar file gets created in the Android project directory
>    with the name of the Android project, and not with the name of the Go
>    package I specified in the build.gradle file (is it intended?)
>
> What is your project structure, and from what module did you import the
gobind plugin?
In the example, the 'hello' module's build.gradle imports the gobind plugin.

>
>
> 2)
> In order to be able to use the functions defined in the Go package, I then
> add the .aar file to the project (is this what is supposed to be done?).
>
When I do that, a subdirectory with the same name of the .aar file (and
> hence the name of the Android project) gets created and the .aar file is
> moved from the project directory to this subdirectory.
> I can now successfully access all the Go functions defined in this .aar
> which has been moved to such subdirectory.
>
No. If you use the gradle plugin you don't need to add .aar file. Just
delete all .aar file and replace the build.gradle of the .aar module
directory with what's similar to the
example/bind/android/hello/build.gradle.


> 3)
> If I run "./gradlew gobind" again, an .aar file gets added again to the
> project directory, but the .arr file of the subdirectory (which is the one
> linked to the Android project) doesn't get updated
>
> The gradle plugin is new (I checked it in last week) and it seems that it
needs proper documentation.

Until the documentation is available, for now, it may be easier to follow
what the gomobile package doc says - i.e. utilize Android Studio's .aar
import, and run 'gomobile bind' tool with -o option to overwrite the .aar
file **in your android studio project's aar module directory**. Sorry for
inconvenience.

—

> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/11895#issuecomment-126155757>.
>



-- 
__

**Comment by dbaroncelli** [comment]
I tried in another way, which it seems closed to what it's supposed to be. But it still found some issues.

1)
First of all, I added the .aar file to the Android project, selecting it from the GOPATH binary directory.
This correctly creates a subdirectory inside the Android project with the name of the Go package. That's what I expected, and it works!
In the module `build.gradle` I then replace this autogenerated code:
`configurations.create("default")
artifacts.add("default", file('TestGoLib.aar'))`
with this code:
https://go-review.googlesource.com/#/c/12800/4/example/bind/android/hello/build.gradle

2)
Then, I change the names of the functions of my Go library.
If I run the "gobind" task from the AndroidStudio IDE, I still get the error `/var/go/bin/gomobile: no Go tool on $PATH`
If I run from the command line: `./gradlew gobind,` the .aar in the subdirectory gets updated, but from the Java code I still get the old function names. It seems that the Java project is still referencing the old .aar file and not the new one.

**Comment by dbaroncelli** [comment]
> Does your PATH param in the hello/build.gradle include the path to your go tool?

@hyangah, yes it does and in fact the command line `./gradlew gobind` is able to create the new .aar file properly

Summarizing, I can see two issues:
1) the .aar file gets updated only with command line `./gradlew gobind` and not from the Android IDE task "gobind" (error: `/var/go/bin/gomobile: no Go tool on $PATH`)
2) even when the .arr gets properly updated, the Java project seems to still reference the old library and not the new one

**Comment by dbaroncelli** [comment]
@hyangah 
this is my module `build.gradle`, and it already allows `./gradlew gobind` to update the .aar file inside the module subdirectory

plugins {
    id "org.golang.mobile.bind" version "0.2.1"
}

gobind {
    /* The Go package path; must be under one of the GOPATH elements or
     a relative to the current directory (e.g. ../../hello) */
    pkg = "TestGoLib"

    /* Include path to your go tool and gomobile binary */
    PATH = "/var/go/bin"

    /* Specify your GOPATH */
    GOPATH = "/Users/daniele/GoDev"
}

**Comment by hyangah** [comment]
2015-07-29 22:55 GMT-04:00 dbaroncelli <notifications@github.com>:

> Does your PATH param in the hello/build.gradle include the path to your go
> tool?
>
> @hyangah <https://github.com/hyangah>, yes it does and in fact the
> command line ./gradlew gobind is able to create the new .aar file properly
>
> Summarizing, I can see two issues:
> 1) the .aar file gets updated only with command line ./gradlew gobind and
> not from the Android IDE task "gobind" (error: /var/go/bin/gomobile: no
> Go tool on $PATH)
>

That's expected. When you run ./gradlew from your terminal, it inherits all
the env vars (including $PATH) so it should work. OTOH, Android Studio
starts with the default environment - unless you launched it from terminal
where the PATH were properly set, or you did some special setup in mac
application launcher. That's the reason the gomobile gradle plugin had to
take PATH parameter as a workaround.

It seems that the environment variable was not applied correctly when
launching the gomobile command for some reason and the gomobile tool
couldn't find the /var/go/bin/go command. Strange.

I will modify the plugin to output some useful debug message  tomorrow.

> 2) even when the .arr gets properly updated, the Java project seems to
> still reference the old library and not the new one
>

That's expected. ./gradlew  gobind just produces .aar file. The following
tasks (the app module) that depend on the .aar module are those that
uncompress the .aar file.

Is it possible to share your project so I can inspect and reproduce the
problem? Thanks.

**Comment by dbaroncelli** [comment]
@hyangah I found the reason why it was not working!!!

I was setting PATH to my GOPATH/bin, which is where the binary `gomobile` gets copied when you get the gomobile package:
`go get golang.org/x/mobile/cmd/gomobile`

I didn't realize PATH was meant to be the directory where both the `gomobile` and `go` need to be

Actually, this can be quite confusing, because by default `gomobile` and `go` are in two different locations:
`gomobile` goes to `GOPATH/bin`
`go` goes to `GOROOT/bin`

I solved by setting the `build.gradle` PATH to my `GOROOT/bin` (which is the default `/usr/local/go/bin`) and copying `gomobile` to there

**Comment by hyangah** [comment]
you can put both like

/usr/local/go/bin:/var/go/bin

2015-07-29 23:54 GMT-04:00 dbaroncelli <notifications@github.com>:

> @hyangah <https://github.com/hyangah> I found the reason why it was not
> working!!!
>
> I was setting PATH to my GOPATH/bin, which is where the binary gomobile
> gets copied when you get the gomobile package:
> go get golang.org/x/mobile/cmd/gomobile
>
> I didn't realize PATH was meant to be the directory where both the
> gomobile and go need to be
>
> Actually, this can be quite confusing, because by default gomobile and go
> are in two different locations:
> gomobile goes to GOPATH/bin
> go goes to GOROOT/bin
>
> I solved by setting the build.gradle PATH to my GOROOT/bin (which is the
> default /usr/local/go/bin) and copying gomobile to there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/11895#issuecomment-126173395>.
>



-- 
__

**Comment by dbaroncelli** [comment]
@hyangah
great! everything works as expected then!
just make sure the plugin runs with JDK7, as most devs still use that

**Comment by GhongadiAdinath** [comment]
Hi, 
First of all, thanks for the good information on how to build go programs 
I tried the example mentioned in the "https://go-review.googlesource.com/#/c/12800/ "

But, getting bellow error:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/SDL/gocode/src/SDL-SRC/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'SDL-SRC'.
> No signature of method: build_4s3bi4u0rg0mg10bktcmg7ughp$_run_closure1.id() is applicable for argument types: (java.lang.String) values: [org.golang.mobile.bind]
  Possible solutions: is(java.lang.Object), is(java.lang.Object), find(), find(), find(groovy.lang.Closure), find(groovy.lang.Closure)

My build.gradle:

plugins {
    id "org.golang.mobile.bind" version "0.2.1"
}

gobind {
    /* The Go package path; must be under one of the GOPATH elements or
     a relative to the current directory (e.g. ../../hello) */
    pkg = "/home/SDL/gocode/src/SDL-SRC"

    /* GOPATH where the Go package is; check `go env` */
    GOPATH = "/home/SDL/gocode"

    /* Absolute path to the go binary */
    GO = "/usr/local/go/bin"

}

Please help to resolve above issue.

**Comment by crawshaw** [comment]
@GhongadiAdinath your issue looks unrelated to this issue. Please ask it on the list or a forum (or a group with more Android Studio experts). If you think this is a bug in the gradle plugin please file another issue. Thanks.
