### ISSUE TITLE
x/mobile/cmd/gomobile: "gomobile init" failed due to permission issue

### ISSUE THREAD

**Issue by dbaroncelli** [golang/go#11892]
on Mac OS, running "gomobile init" gives an error:

`/Users/daniele/GoDev/bin/gomobile: go install std for android/arm failed: exit status 1
go install runtime: mkdir /usr/local/go/pkg/android_arm/: permission denied`

the owner of my Go installation is root with "pkg" directory having 755 permission
if I run "gomobile init" as a non-root user, it doesn't allow to create directories
if I run "sudo gomobile init", it tells me that GOPATH is not defined for the root user

**Comment by crawshaw** [comment]
Please try go get -u. A recent change to gomobile means it should no longer try changing your GOROOT

**Comment by hyangah** [comment]
@dbaroncelli can you try what crawshaw suggested and update or close this bug? Thanks.

**Comment by dbaroncelli** [comment]
@hyangah yes, it seems fixed now
