### ISSUE TITLE
proposal: x/net/context: Context-aware HTTP helper functions.

### ISSUE THREAD

**Issue by broady** [golang/go#11904]
Proposal: add a context-aware client that is similar to/mirrors `http.Client`.

```
req, _ := http.NewRequest(...)

ctx := context.Background()
c := ctxhttp.NewClient(http.DefaultClient)

// Add the ctx parameter to Do()
resp, err := c.Do(ctx, req)
```

Should this type go into `x/net/context/ctxhttp`? The package shouldn't be called `http`, since something like this would need to be used in conjunction with `net/http`.

Is `Get()`, `Post()`, etc needed, or do we only need `Do(ctx, req)`?

**Comment by ianlancetaylor** [comment]
CC @Sajmani

**Comment by bradfitz** [comment]
I'd rather not see two types of *http.Client splitting the API ecosystem. In Go 1.5, *http.Request has a Cancel field that's the same as the Done channel's return type. I'd rather just see a helper package if anything that doesn't introduce new types. If it really has to, maybe it could introduce a new RoundTripper (but returning a RoundTripper and not its own *Transport type), but I'd rather see no new types.

**Comment by broady** [comment]
@bradfitz So, I guess just a function like `Do(httpClient, ctx, req)` then?

**Comment by bradfitz** [comment]
> So, I guess just a function like Do(httpClient, ctx, req) then?

Making a request just for GET is annoying, so probably also `GET`.

> I don't think a RoundTripper works, it goes against the intent of the context package by putting a Context into a struct.

Be sure to also file a bug against Google's internal codebase to make sure all our various `RoundTripper`s support the new Cancel field.

**Comment by adg** [comment]
If you're making a package for helpers, might as well do the full set of
helpers we have in the standard library:

func Get(url string) (resp *Response, err error)
func Head(url string) (resp *Response, err error)
func Post(url string, bodyType string, body io.Reader) (resp *Response, err
error)
func PostForm(url string, data url.Values) (resp *Response, err error)

**Comment by broady** [comment]
Not sure why Gerrit didn't link this issue, but the change that implements this is at http://golang.org/cl/12755.

I added helpers for Do/Get/Head/Post/PostForm.

The function signatures are `X(http.Client, context.Context, ...)` where `X` is Do/Get/...

**Comment by adg** [comment]
Sometimes the notifications take a little while to come through.
