### ISSUE TITLE
x/playground/sandbox: programs that produce no output never 'end'

### ISSUE THREAD

**Issue by malkia** [golang/go#11903]
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintf(os.Stdin, "hello, writer\n")
}
```

**Comment by malkia** [comment]
Yet this version works just fine:

**Comment by malkia** [comment]
package main

import (
	"fmt"
	"os"
)

func main() {
	_, err := fmt.Fprintf(os.Stdin, "hello, writer\n")
	fmt.Println(err)
}

**Comment by adg** [comment]
It seems that the JS on the client side isn't gracefully handling snippets with no output. I've sent out a fix.
