### ISSUE TITLE
regexp: failed match with triple quantifier

### ISSUE THREAD

**Issue by ibukanov** [golang/go#11905]
The following regexp `^a(/a+(#a+)*)*$` fails to match `a/a#a` when it should. Adding parenthesis around the first part `^(a)(/a+(#a+)*)*$` apparently fixes the issue and gives a match, see http://play.golang.org/p/6v0VjVNFVN .

For the background, see http://stackoverflow.com/questions/31663430/issue-with-regexp-with-nested-groups-in-golang

**Comment by cespare** [comment]
This is another onepass bug. I haven't gotten to the bottom of it yet, but I should be able to send a CL soon. (Hope that's okay even though @rsc was assigned.)
