### ISSUE TITLE
runtime: netpoll_windows.go:18: undefined: overlapped

### ISSUE THREAD

**Issue by rjeczalik** [golang/go#11908]
While cross compiling go-tip for windows/arm make.bash fails with:

```
~ $ GOOS=windows GOARCH=arm ./make.bash
(...)

##### Building packages and commands for windows/arm.
runtime
# runtime
runtime/netpoll_windows.go:18: undefined: overlapped
```
```
$ go version
go version devel +aadd84e Sat Jul 18 01:35:25 2015 +0000 darwin/amd64
```

**Comment by bradfitz** [comment]
Go doesn't support `windows/arm`. We support Windows, and we support ARM, but not that combination.

**Comment by Thomasdezeeuw** [comment]
I just ran into this issues aswell, even though I know `windows/arm` isn't supported. But I think the error message is rather confusing. Maybe there should be a check if a os/arch combination is supported before building?

**Comment by bradfitz** [comment]
Agreed. Let's move this to a new issue: #12272
