### ISSUE TITLE
encoding/json: UnmarshalJSON null behavior change broke real programs

### ISSUE THREAD

**Issue by rsc** [golang/go#11912]
Reported by Dominik Honnef on golang-dev.
Hypothetical example: http://play.golang.org/p/t6e-FEbA5j
I've asked for a real one.

Regardless of that problem, it also seems wrong that we still
allocate the structure before deciding not to call UnmarshalJSON.
So I think this change is wrong either way, and we should
probably roll it back and think harder for Go 1.6, like we are
doing for encoding/xml's name space changes.

Will wait for Dominik's reply.

**Comment by dspezia** [comment]
Another issue: https://github.com/golang/go/issues/11937
