### ISSUE TITLE
x/tools/go/ssa/interp: TestGorootTest times out when GOARCH=386

### ISSUE THREAD

**Issue by mwhudson** [golang/go#11916]
GOARCH=386 go test ./go/ssa/interp/ -v -run TestGorootTest takes a very long time -- probably it's going to hit 10 minutes and time out but I haven't waited that long yet. It's slow but not so stupidly slow when GOARCH=amd64 -- about 52s.

**Comment by davecheney** [comment]
I _think_ this is related to ssa only targeting amd64 at the moment, other arches will fall back to the original code gen, but probably with some overhead.

@josharian can probably give more information, and correct my understanding.

**Comment by mwhudson** [comment]
Hm, it seems that it works on arm64 but not armhf, so maybe there is some 64/32 bit thing going on. But the tests with GOARCH=386 and amd64 with go 1.4 (haven't tried go1.4 on armhf yet).

It hangs after "Input: encoding/ascii85" fwiw.

**Comment by rsc** [comment]
cc @adonovan

@davecheney, this is Alan Donovan's ssa, not the new ssa in the compiler.
