### ISSUE TITLE
cmd/compile: internal compiler error: out of fixed registers on 386

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#11917]
Reported by windows-386 builder building "exp" sub-repository at tip http://build.golang.org/log/5970f873c651822fe66197c29e359559ad150f03

```
windows-386-gce at 861af80458e846bc535f262cca23649e703b7885 building image at 5c9906b5359a44e978a11bec5bb6e055bfeb984d

ok  	golang.org/x/image/bmp	0.192s
ok  	golang.org/x/image/draw	1.058s
?   	golang.org/x/image/math/f32	[no test files]
?   	golang.org/x/image/math/f64	[no test files]
ok  	golang.org/x/image/riff	0.064s
# golang.org/x/image/vp8
run compiler with -v for register allocation sites
..\..\gopath\src\golang.org\x\image\vp8\partition.go:77: internal compiler error: out of fixed registers
ok  	golang.org/x/image/tiff	0.231s
?   	golang.org/x/image/tiff/lzw	[no test files]
```

Alex

**Comment by alexbrainman** [comment]
Meant to say "image" (not "exp") repo.

Alex

**Comment by bradfitz** [comment]
For #11811 (green subrepos), I recommend we just +build this package away for below Go 1.5 if it doesn't compile successfully anyway. No point testing something that's otherwise unusable.

**Comment by bradfitz** [comment]
Oh, this is all 386 even at tip. I misremembered this only being a Go 1.4 issue.

I suppose we could just say the vp8 package requires 64-bit for now, which is lame, but would get the dashboard "ok" for now and stop hiding other potential test failures.

/cc @rsc for thoughts.

**Comment by nigeltao** [comment]
FWIW, the vp8 code isn't particularly tricky Go code.

**Comment by rsc** [comment]
Not fixing the 386 compiler today. That's Keith's (long-term) job.
https://go-review.googlesource.com/12856
