### ISSUE TITLE
Marshal Fails when we define struct variables in  lower case: go version go1.4.

### ISSUE THREAD

**Issue by nzsrini** [golang/go#11926]
package main

import (
	"encoding/json"
	"fmt"
	"os"
)

func main() {

	type MilvariableStartswithUpperCase struct {
		Id  int64  `json:"id"` //sss
		Cty string `json:"firstname"`
	}

	type MilvariableStartswithLowerCase struct {
		id  int64
		cty string
	}

	upperCase := MilvariableStartswithUpperCase{1, "UpperCase"}
	lowerCase := MilvariableStartswithLowerCase{1, "Lowercase"}

	marshalsucessfull, err := json.Marshal(upperCase)
	if err != nil {
		fmt.Println("error:", err)
	}

	marshalunsucessfull, err := json.Marshal(lowerCase)
	if err != nil {
		fmt.Println("error:", err)
	}

	fmt.Println("----")
	fmt.Println("Marshal Sucess")
	os.Stdout.Write(marshalsucessfull)
	fmt.Println()
	fmt.Println("Marshal Failed.")
	os.Stdout.Write(marshalunsucessfull)

}

Out Put
Marshal Sucess
{"id":1,"firstname":"UpperCase"}
Marshal Failed.
{}____

**Comment by ianlancetaylor** [comment]
As far as I can see, this is working as expected.  The docs for encoding/json say that each exported struct field becomes a member of the object.  Non-exported fields do not.
