### ISSUE TITLE
net: no IO deadline support for Plan 9

### ISSUE THREAD

**Issue by mikioh** [golang/go#11932]
See https://github.com/golang/go/blob/master/src/net/fd_plan9.go#L210.

**Comment by bradfitz** [comment]
This is basically a dup of #7237

/cc @0intro to decide whether to keep

**Comment by 0intro** [comment]
Yes, this is the long-standing issue with network i/o cancellations.
We can't implement deadlines as long as we don't have a reliable
way to cancel network connections.

**Comment by bradfitz** [comment]
@0intro, I think https://go-review.googlesource.com/c/22144/ might've fixed a number of the I/O timeout bugs, but I didn't have time to check which ones. Can you investigate and remove some `t.Skip` calls from the `net` and `net/http` packages if possible?

**Comment by 0intro** [comment]
I've noticed some tests that could be enabled. I'll do a full review of the disabled tests,
then I'll send the changes, once CL 22144 will be submitted.

**Comment by bradfitz** [comment]
What remains here?
