### ISSUE TITLE
spec: why write to a closed channel will panic?

### ISSUE THREAD

**Issue by xbsura** [golang/go#11934]
I am using go lang on a redis proxy,finding when writing a message to closed channel,it panic,but not return a err.
why not:
err := channel <- message
if err != nil {
    // channel was closed by client,we do nothing and continue
    continue
}

all proxy client share one same backend connection and one go routine,if one client conn closed,when wring message,i want it return err but not panic.

panic is ugly ugly ugly,i have to use a member named "isClientAlive" to notify writer this channel closed,and for sync i have to use a lock,it is bad.

ugly.

**Comment by xiaokunLee** [comment]
赞！

**Comment by mikioh** [comment]
Please use https://groups.google.com/forum/#!forum/golang-nuts for discussion.

**Comment by osDanielLee** [comment]
bravoooooooooooo
