### ISSUE TITLE
cmd/release: must run api checker

### ISSUE THREAD

**Issue by rsc** [golang/go#11943]
We keep issuing releases without noticing that the API file is out of date.
We need to change cmd/release to run the api checker.
See discussion on https://go-review.googlesource.com/#/c/12769/ for example.

**Comment by rsc** [comment]
The more I think about this, the more it seems like we should run all.bash.

**Comment by adg** [comment]
I'm running a test now to see what all.bash leaves behind.

**Comment by adg** [comment]
It looks like test/bench/shootout leaves behind .o and .out/.exe files.
Sending a fix to remedy that. We should probably put a check in dist to
cause all.bash to fail if tests leave files behind in the tree, but for 1.6.
