### ISSUE TITLE
gccgo: complex accepts complex value as 2nd argument

### ISSUE THREAD

**Issue by griesemer** [golang/go#11948]
The following program:
```
package main
const x = complex(0i, 1i)
func main() {
}
```
compiles, links, and runs w/o errors:
```
$ gccgo x.go -o x && ./x
```
(version: gccgo (google-gccgo-219769) 5.0.0 20150116 (experimental))

The 2nd argument 1i is a complex constant with non-zero imaginary component, it should not be accepted.

Note that:
```
package main
const x = complex(1, 1i)
func main() {
}
```
leads to an error:
```
$ gccgo x.go -o x && ./x
x.go:2:11: error: complex arguments must have identical types
 const x = complex(1, 1i)
           ^
```
which is misleading (both arguments are untyped).

Furthermore:
```
package main
import "fmt"
const x = complex(1i, 1i)
func main() {
   fmt.Println(x)
}
```
compiles, links, and runs without error, but does not print anything (not even a newline):
```
$ gccgo x.go -o x && ./x
$
```

**Comment by paranoiacblack** [comment]
This has the same root cause as #11566. Closng this as a duplicate; the test cases here will be sucked into the test case for #11566.
