### ISSUE TITLE
cmd/compile: real and imag don't accept untyped non-complex constants as arguments

### ISSUE THREAD

**Issue by griesemer** [golang/go#11946]
```
package main
const _ = real(10.0)
```

=>

```
$ go build x.go
# command-line-arguments
./x.go:2: invalid argument 10 (type float64) for real
```

This seems inconsistent with complex(...) which accepts any untyped number as argument as long as it has no imaginary component or that component is zero. Similarly, real and float shouldn't really care about the nature of the untyped constant as long as it's a number.

gccgo accepts the above code w/o error.

Related issues: #11540, #11945.

**Comment by ALTree** [comment]
This was fixed in 829adf5047bee5a7cd746e9d6d00d09eb7ac4adb, so we can close this issue.
