### ISSUE TITLE
go/types: refers to go/constant as exact

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11949]
go/types docs:
http://tip.golang.org/pkg/go/types
periodically refer to a package ```exact```. For example:
```
Constant folding computes the exact constant value (exact.Value) for every expression
```
and:
```
type TypeAndValue struct {
    Type  Type
    Value exact.Value
    // contains filtered or unexported fields
}
```

This is very confusing. There is no package exact.
I understand this was introduced during refactoring, but the cost of confused users is higher than the cost of sed invocation.

**Comment by griesemer** [comment]
Since we're late in the release cycle I'll address the documentation (comment) issue for now.
