### ISSUE TITLE
JSON marshalling interfaces

### ISSUE THREAD

**Issue by ThePiachu** [golang/go#11951]
I recently started implementing some interfaces for my structures and I was surprised to find that the default JSON encoder appears to try encoding the interfaces as if they were variables in structures. So for example if we have:

type Foo interface{
    FooMe()
}

type Bar struct {
    Foo
    ImportantVariable string
}

The encoded JSON would look like:
{"Foo":null,"ImportantVariable":""}

Which is kind of silly, since Foo will never be anything other than null.

I think it would be useful for JSON to check if an imported variable is only an interface, not a struct or any other data structure, and ignore it completely if it is.

**Comment by bradfitz** [comment]
Here it's not null:
http://play.golang.org/p/M-G2BsyqvV

And here it's a string:
http://play.golang.org/p/XAIGQr_15b

I think this is working.

**Comment by ThePiachu** [comment]
Sorry, I meant empt interface. One way or the other, it's trying to denote there is a variable there when we only have an interface that doesn't hold any data itself.
