### ISSUE TITLE
runtime/trace: TestTraceStressStartStop fails on linux, windows sometimes

### ISSUE THREAD

**Issue by davecheney** [golang/go#11953]
```
--- FAIL: TestTraceStressStartStop (0.77s)
	trace_test.go:345: failed to parse trace: g 5 is not runnable before start (offset 445, time 250878)
FAIL
FAIL	runtime/trace	11.980s
```

Is unreliable, recent failures are

http://build.golang.org/log/58a391ca5363fd33fd4e8e86220fff2a04939645 (linux/arm64)

http://build.golang.org/log/e45ad86f06f071d19908771a74c89ac037af8479 (solaris/amd64)
```
--- FAIL: TestTrace (0.01s)
	trace_test.go:60: failed to parse trace: EvFrequency contains invalid frequency -214366821 at offset 0x12f
--- FAIL: TestTraceStressStartStop (0.10s)
	trace_test.go:345: failed to parse trace: EvFrequency contains invalid frequency -14474340013 at offset 0x3b4
FAIL
FAIL	runtime/trace	8.003s
```

**Comment by ianlancetaylor** [comment]
CC @dvyukov @rsc

**Comment by rsc** [comment]
The solaris/amd64 one is fixed by ca6f7e4.
The linux/arm64 is more worrisome. That's not supposed to happen anymore.
It's possible there is something we don't understand that isn't right still.

**Comment by davecheney** [comment]
Just saw a failure on linux/386

http://build.golang.org/log/62b62b40de512697395a90784f6ba8865b5e2a80

```
--- FAIL: TestTraceStressStartStop (0.13s)
	trace_test.go:345: failed to parse trace: g 5 is not runnable before start (offset 2104, time 6810862)
FAIL
FAIL	runtime/trace	2.097s
```

**Comment by davecheney** [comment]
And just now with darwin/amd64 

http://build.golang.org/log/2d4c33d355892176fa11d9869948c8288ca363ad

```
--- FAIL: TestTraceStressStartStop (0.03s)
	trace_test.go:345: failed to parse trace: g 5 is not runnable before start (offset 1759, time 94953)
FAIL
FAIL	runtime/trace	1.775s
```

**Comment by dvyukov** [comment]
It happens on linux/amd64 machine pretty frequently:

814 runs so far, 5 failures
--- FAIL: TestTraceStressStartStop (0.18s)
	trace_test.go:345: failed to parse trace: g 19 is not runnable before start (offset 31, time 142217)

On fde392623a18ecedd7434db1cf40e82bdd482df9 (just before "runtime/trace: record event sequence numbers explicitly") no failures in 2838 runs. So it is broken by some recent changes.

**Comment by mikioh** [comment]
And windows: http://build.golang.org/log/4dfe01b46041cdbbce4a130f91ac970784c160ac

**Comment by mikioh** [comment]
And freebsd: http://build.golang.org/log/a50b2f32d22e59a16a0943e6cd870daaf6adbeb9
