### ISSUE TITLE
x/mobile: "gomobile bind" errors are not descriptive

### ISSUE THREAD

**Issue by dbaroncelli** [golang/go#11950]
`./gomobile bind -target=android TestGoLib`

I never had issues when compiling a single file package, without referencing other packages.

For the first time I tried to add references to structs defined in other packages and I get this error, which I don't understand what it means:

./gomobile: go build -p=8 -pkgdir=/Users/daniele/GoDev/pkg/gomobile/pkg_android_arm -tags="" -buildmode=c-shared -o=/var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/gomobile-work-804429490/android/src/main/jniLibs/armeabi-v7a/libgojni.so /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/gomobile-work-804429490/androidlib/main.go failed: exit status 2
# command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running /Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/arm-linux-androideabi-gcc failed: exit status 1
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__aeabi_uidivmod'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__aeabi_uidiv'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__udivsi3'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__aeabi_unwind_cpp_pr0'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Restore_VFP_D'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Restore_VFP'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Restore_VFP_D_16_to_31'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Restore_WMMXD'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Restore_WMMXC'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of 'restore_core_regs'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_GetCFA'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_RaiseException'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_ForcedUnwind'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Resume'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Resume_or_Rethrow'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_Complete'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_DeleteException'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_VRS_Get'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_VRS_Set'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Backtrace'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_unwind_execute'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_VRS_Pop'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Save_VFP_D'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Save_VFP'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Save_VFP_D_16_to_31'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Save_WMMXD'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_Unwind_Save_WMMXC'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__restore_core_regs'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '___Unwind_RaiseException'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_RaiseException'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '___Unwind_Resume'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_Resume'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '___Unwind_Resume_or_Rethrow'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_Resume_or_Rethrow'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '___Unwind_ForcedUnwind'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_ForcedUnwind'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '___Unwind_Backtrace'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_Backtrace'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '__gnu_unwind_frame'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_GetRegionStart'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_GetLanguageSpecificData'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_GetDataRelBase'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000004.o: multiple definition of '_Unwind_GetTextRelBase'
/Users/daniele/GoDev/pkg/gomobile/android-ndk-r10e/arm/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: /var/folders/pt/ync64j011ysc_t3nvbzlk2wr0000gn/T/go-link-725920858/000000.o: previous definition here
collect2: error: ld returned 1 exit status

**Comment by eliasnaur** [comment]
This is a very old issue. Please re-open if there is still a problem with the error messages from a recent version of gomobile.
