### ISSUE TITLE
tour: Ctrl+PgUP issue, conflict with tab switching in Chrome

### ISSUE THREAD

**Issue by x2es** [golang/go#11963]
On tab switching wing Ctrl+PgUp in Chrome Playground switches pages

### Context

  * Linux Mint 17 x64
  * browser Chrome v43
  * 2+ tabs in chrome
  * first tab: https://tour.golang.org/concurrency/3

### Setps

  * open second tab
  * press Ctrl+PgUp

### Expected

  * playground page: https://tour.golang.org/concurrency/3

### Actual

  * playground page: https://tour.golang.org/concurrency/2

### Vice versa

Same bug for Ctrl+PgDown case when playgroud is second tab and switching from first tab to second

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Hi,

I'm not sure I understand this. When pressing PageUp or PageDown (no Ctrl) I get to navigate through the slides of the tour, while if use Ctrl+PageUp or Ctrl+PageDown I get to navigate through the tabs open on my navigator.

This is the expected behavior, are you seeing a different one? If so: please explain with more detail.

Thanks

**Comment by cespare** [comment]
@campoy I can repro this. If I'm on the tab before the tab with the tour and I press ctrl+PageDown to go to the next tab (the tour page), it switches tabs but additionally the tour page sees the PageDown and switches to the next slide of the tour.

For some reason it doesn't happen in Firefox; must be some difference in how events are passed through.

**Comment by campoy** [comment]
Oh, so the problem is that you navigate through the tabs but the tour also gets the event and moves to the next page!

Thanks for the explanation, I'll fix it soon :+1:

**Comment by x2es** [comment]
:+1:
