### ISSUE TITLE
spec: minor changes to examples

### ISSUE THREAD

**Issue by pto** [golang/go#11964]
Three small suggestions for the examples in the Go Specification:

In the ```TimeZone``` type, the line
```
return fmt.Sprintf("GMT+%dh", tz)
```
returns something like ```GMT+-5h```. I think it would be better to change ```+%``` to ```%+```:
```
return fmt.Sprintf("GMT%+dh", tz)
```
so the result is ```GMT-5h```.

In ```findMarker```, if a return statement were added, the loop would only check every other item in the channel, because it uses both a for/range and a channel receive operation. The example would be less confusing with just one of those. For/range hasn't been introduced yet, so that's what I would remove.

In the Selectors section, the anonymous field ```T0``` of type ```T2``` is already a pointer. So the line
```
p.M0()       // ((&(*p).T0)).M0()   M0 expects *T0 receiver, see section on Calls
```
isn't an example of a shorthand reference to an addressable value. I think the comment should be:
```
p.M0()       // ((*p).T0).M0()   M0 expects *T0 receiver
```
A shorthand example could be added:
```
t.M2()      // (&t).M2()     M2 expects *T2 receiver, see section on Calls
```

These suggestions are current as of Go 1.5 beta 3.

**Comment by griesemer** [comment]
Thanks, these are good suggestions.

The findMarker example is terrible; I'm amazed we didn't catch this earlier.
