### ISSUE TITLE
cmd/go: get does not expand env variables on Windows

### ISSUE THREAD

**Issue by chairborne** [golang/go#11962]
Title says it all. I have a directory with my code in "%USERPROFILE%". Let me call it Dev. I made a environment variable called "%DEV%" to make it easier to access the dir. %GOPATH% is "%DEV%\Go". When I use "go get" it does not expand "%DEV%" to "%USERPROFILE%\Dev" or "C:\Users\user\Dev" but downloads sources to "%USERPROFILE%\\%DEV\%".

**Comment by alexbrainman** [comment]
It does not say anywhere in go command documentation that it  will expand environment variables. Does it?

Why should "go get" command expand environment variables? Windows shell does the expansion. If you want to use that (you can create small batch file that prepares all your go environment variables), that is fine. But I don't see why go should meddle in here.

I think it is working as intended.

Alex

**Comment by chairborne** [comment]
![command_prompt_2015-08-02_00-56-31](https://cloud.githubusercontent.com/assets/12383418/9023338/6f43b9e0-38b1-11e5-804f-73b1dad59606.png)
I guess this is not okay.

Creating a "small batch file" is a workaround. cmd.exe is a workaround too, but it's easier to patch the sources than the binary.

If you do not want to fix it, do not close the issue and let somebody else view it.
