### ISSUE TITLE
dashboard: top-level view of subrepos doesn't match subrepo view

### ISSUE THREAD

**Issue by griesemer** [golang/go#11976]
The view of subrepos from the top-level page http://build.golang.org/ doesn't correspond with the first entry for a given subrepo (see e.g., http://build.golang.org/?repo=golang.org%2fx%2ftools ).

Sometimes the top-level page has a green entry, sometimes the subrepo view has a green entry for the same submit, and they don't match.

This makes it difficult to judge the status of the repos.

**Comment by ianlancetaylor** [comment]
CC @adg

**Comment by adg** [comment]
Are you sure you're looking at the right builder? The builder columns are
opportunistically populated (on the front page there are as many columns as
there are core builders, on the subrepo page only columns that have results
for that builder are shown), so they're not equivalent on each page.

Can you provide screenshots to illustrate the problem?

**Comment by griesemer** [comment]
Top-level view of subrepos against vs 1.4. Look at x/tools: green but for freebsd-386:

![screen shot 2015-08-03 at 3 25 37 pm](https://cloud.githubusercontent.com/assets/8528975/9049170/0d1b8aa6-39f4-11e5-8b7b-7d03ebcbce1d.png)

x/tools repo:

![screen shot 2015-08-03 at 3 25 56 pm](https://cloud.githubusercontent.com/assets/8528975/9049198/51d62d5e-39f4-11e5-80f2-9606e265ea3f.png)

First row is not showing, other rows are red.

Yes, the std lib revision hash is different, but why would the top-level view now show the top-most row of each sub-repo? Which one does it show?

At the very least it's confusing. I don't know how to judge whether the sub-repo is green or not.

**Comment by adg** [comment]
The front page shows two sets of data for the sub-repos. One for results
against the current Go tip, and one against the current Go release. The
first set (against tip) should match the top row of the sub-repo page.
That's what it looks like to me.

**Comment by griesemer** [comment]
@adg That explains part of the confusion: The front page makes it look as if the sub repos had detailed information being built both against tip and 1.4. But when clicking on the sub repo link (from the front page), the sup repo details page is always against tip. Suggestion: That sub-repo page should say "against tip".

Now looking at the sub-repo page against tip, the first line for x/tools is actually not fully populated (look at freebsg-amd64-gce101 column), but the front page shows an ok for that column. Shouldn't they correspond?

**Comment by adg** [comment]
The sub-repo page lists all Go commits, including ones on branches. When looking at the sub-repo page, make sure to make a note of the Go commit you want to check against (say, the latest HEAD hash), and then look for that row on the sub-repo page. (This is actually possible now that the go revisions are populated for each row.)
