### ISSUE TITLE
runtime: Version() string should be more easily discernible

### ISSUE THREAD

**Issue by griesemer** [golang/go#11972]
runtime.Version() prints something like

```
devel +226b28c Fri Jul 31 18:49:57 2015 +0000
```

at tip, and, if at a release, something like

```
go1.4.2
```

There's no easy way to determine which version is younger or older. Tests in external repos sometimes need to be able to distinguish against which version of the std lib they are running; typically they require a certain "minimal" version.

There could be a runtime.VersionNumber() that returns some form of monotonically increasing value/string; or perhaps runtime.VersionTime() could return a value that is easily converted into a time.Time. Alternatively, runtime.Version() could always start with the most recent version, followed by the current version hash if _not_ at a release. That would at least make it possible to discern against tagged releases. For instance:

```
go1.4.2
```

means we are at the tagged release 1.4.2.

```
go1.4.2 devel +226b28c Fri Jul 31 18:49:57 2015 +0000
```

would mean we are at devel +226b28c past 1.4.2, and 1.4.2 is the most recent tagged release.

Another alternative would be to have a time stamp always.

**Comment by seankhliao** [comment]
This was done in [CL 264938](https://golang.org/cl/264938)
