### ISSUE TITLE
syscall: syscall.SIGABRT not defined for Plan 9

### ISSUE THREAD

**Issue by griesemer** [golang/go#11975]
The x/tools/cmd/stress package uses it and cannot be built for Plan 9.

See e.g.: http://farmer.golang.org/temporarylogs?name=plan9-386&rev=883bc6ed0ea815293fe6309d66f967ea60630e87&st=0xc829582fc0&subName=tools&subRev=32dcbb4ccca1d39fc73d6d9707d72e31d53fa0e1

**Comment by 0intro** [comment]
I've a fix for this issue. I'll send a CL once the Go 1.6 tree will be open.

**Comment by rsc** [comment]
Do you want to send a fix?

**Comment by 0intro** [comment]
I've implemented a special "abort" note as _SigThrow, which causes
the sighandler to print a stack trace and exit.

Does it sound good to you?
