### ISSUE TITLE
x/mobile/example/audio: no sound in ios

### ISSUE THREAD

**Issue by hyangah** [golang/go#11982]
> go version
go version devel +c2db5f4 Sun Aug 2 09:34:59 2015 +0000 darwin/amd64

> gomobile version
gomobile version +f7785e6 Sun Aug 2 07:22:52 2015 -0400 (android,ios); androidSDK=

> gomobile build -target=ios

> ios-deploy --justlaunch --debug --bundle audio.app

@rakyll

**Comment by hyangah** [comment]
The gomobile version includes my local commit.
The latest commit is +99196c8

**Comment by rakyll** [comment]
I can't reproduce the bug when gomobile is inited with an older Go tip. I can't give your Go version a try because I am blocked by https://github.com/golang/go/issues/11996.

**Comment by rakyll** [comment]
Still not reproducible. Could you provide me more information by running `gomobile build -target=ios -x`? I am not sure if I am building it against the same iOS SDK version you do.

In the meanwhile, I found another bug that might be relevant.

1. Launch Audio sample.
2. Open the system wide settings bar by sliding from the bottom.
3. Resume playing the current song.
4. Return back to the Audio app, there is no sound.

It behaves normally when I switch to the Music app and resume the playback there.

Killing the app and relaunching it is the only way to get the OpenAL playback back. Could you be experiencing the same problem?

**Comment by hyangah** [comment]
I don't know what happened. It now works. Sorry for the noise.
