### ISSUE TITLE
x/mobile/gl: GetAttachedShaders panics with no shaders attached

### ISSUE THREAD

**Issue by shazow** [golang/go#11980]
When calling `gl.GetAttachedShaders(program)` on a program that has no shaders attached, an avoidable panic occurs.

```go
panic: runtime error: index out of range

goroutine 21 [running]:
golang.org/x/mobile/gl.GetAttachedShaders(0x1, 0x0, 0x0, 0x0)
	/Users/shazow/local/go1.5/src/golang.org/x/mobile/gl/gl.go:860 +0x1d0
```

We get the number of attached shaders with `shadersLen := GetProgrami(p, ATTACHED_SHADERS)` and allocate the buffer based on that number, but we never check if it's zero.

Simplest fix would be something like this:

```diff
func GetAttachedShaders(p Program) []Shader {
	shadersLen := GetProgrami(p, ATTACHED_SHADERS)
+	if shadersLen == 0 {
+		return []Shader{}
+	}
	var n C.GLsizei
	buf := make([]C.GLuint, shadersLen)
	...
```

This is on `go version devel +71832ff Fri Jul 3 21:39:04 2015 +0000 darwin/amd64` with the latest x/mobile (9865dd0).

(Happy to do a CL if that would be more convenient.)

**Comment by crawshaw** [comment]
Thanks. I'm happy to either fix a bug (especially one this clearly described) or review a CL, whichever is more convenient/fun for you.
