### ISSUE TITLE
arm64 no SYS_FORK and SYS_DUP2 syscall ??

### ISSUE THREAD

**Issue by jefby** [golang/go#11981]
Hi , recently i want to make the hyper(x86_64) work on arm64,found some error when compiling the source code,the main information like below:

```
# hyper/hypervisor/qemu
hypervisor/qemu/qemu_process.go:47: undefined: syscall.SYS_FORK
hypervisor/qemu/qemu_process.go:127: undefined: syscall.Dup2
hypervisor/qemu/qemu_process.go:128: undefined: syscall.Dup2
hypervisor/qemu/qemu_process.go:129: undefined: syscall.Dup2
```

Is go1.5beta2 not provided the syscall.Dup2 or syscall.SYS_FORK in arm64 ?? If i want to use these syscall,how to do ??

Thanks very much!

**Comment by davecheney** [comment]
Those syscalls are not supported on arm64. I don't know what the
replacement is for SYS_FORK, but the replacement for dup is, SYS_DUP3.

**Comment by davecheney** [comment]
Related, I don't know how that code is using SYS_FORK, but I'd be worried
that it was correct, forking in multi threaded programs should be performed
with extreme care.

**Comment by jefby** [comment]
@davecheney ok,Thanks very much.

**Comment by jefby** [comment]
@davecheney They uses  SYS_FORK like below
```
ret, ret2, errno := syscall.RawSyscall(syscall.SYS_FORK, 0, 0, 0)
```
and the source code is here.https://github.com/hyperhq/hyper/blob/master/hypervisor/qemu/qemu_process.go +47 line.

**Comment by davecheney** [comment]
I think that code is very dangerous.

**Comment by jefby** [comment]
@davecheney Now if i want to reimplement this feature , how to do? I'm not familiar with go language.

**Comment by davecheney** [comment]
I recommend syscall.ForkExec. Thanks for testing on arm64.

**Comment by bradfitz** [comment]
Closing, because I don't think there's anything to do here.
