### ISSUE TITLE
x/tools/crypto/ssh: handshake: deadlock if other side drops/resets connection during rekeying

### ISSUE THREAD

**Issue by a-palchikov** [golang/go#11992]
The handshakeTransport.readLoop can exit with t.cond locked and any handshakeTransport.writePacket calls will block indefinitely at t.cond.Wait().

Sorry for the confusion - this is not a duplicate of https://github.com/golang/go/issues/11882 (which solves another issue with a possible deadlock in writePacket) as I initially made a mistake of creating a single problem report for two separate issues.

**Comment by ianlancetaylor** [comment]
CC @agl @hanwen

**Comment by hanwen** [comment]
Did you want to submit a fix? If not, I can have a look. Fixing this is as easy as a adding the unlock in the right place. It would be nice to have a test, though. You could make a packetConn that drops the connection after N packets,  force rekeying after every other packets, and then let N run from 1..10.

**Comment by a-palchikov** [comment]
Sure, I'll do that.

**Comment by hanwen** [comment]
I have a CL for this, including a test that also demonstrates the other deadlocks.

**Comment by a-palchikov** [comment]
Sorry it took me longer to respond - I've been away for a few days. Thanks for putting this in!
