### ISSUE TITLE
x/mobile/misc/androidstudio: gomobile exits with non-zero status; Android Studio doesn't provide its stderr

### ISSUE THREAD

**Issue by rakyll** [golang/go#11997]
When gomobile exists with non-zero status, Android Studio console doesn't output the error messages. We should both print stdout and stderr of gomobile. See the screenshot below.

cc/ @hyangah

![android](https://cloud.githubusercontent.com/assets/108380/9043229/d4b74d60-39c8-11e5-9efc-259d6712cd37.png)

**Comment by hyangah** [comment]
Thanks for the report. Will take a look this week.

**Comment by hyangah** [comment]
From the screen shot, I could see the error message

/Users/jbd/bin/gomobile: toolchain partially installed, run 'gomobile init'.

It turned out the gobind task already outputs stdout and stderr by default.
Users can configure to print more verbose output by setting GOMOBILEFLAGS="-v -x".
