### ISSUE TITLE
x/mobile/misc/androidstudio: GOMOBILE setting is not required

### ISSUE THREAD

**Issue by rakyll** [golang/go#11998]
The gradle plugin should be able to find where the gomobile binary is with the GOPATH setting, the binary is under GOPATH/bin. We should make GOMOBILE an optional setting and use the binary under GOPATH/bin if GOMOBILE is not set.

cc/ @hyangah

**Comment by hyangah** [comment]
That is already optional. Skipping GOMOBILE should work.
Let me know if it's not working.


2015-08-03 13:43 GMT-04:00 Burcu Dogan <notifications@github.com>:

> The gradle plugin should be able to find where the gomobile binary is with
> the GOPATH setting, the binary is under GOPATH/bin. We should make GOMOBILE
> an optional setting and use the binary under GOPATH/bin if GOMOBILE is not
> set.
>
> cc/ @hyangah <https://github.com/hyangah>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/11998>.
>



-- 
__

**Comment by rakyll** [comment]
I am modifying the reference bind example to make it clear.
