### ISSUE TITLE
tour: Short definition of exported name would be helpful.

### ISSUE THREAD

**Issue by iamamosh** [golang/go#12005]
Context: https://tour.golang.org/basics/3

This page tells that exported name must start with upper character, but it does not say what the "exported name" means.   Also, "Exported identifiers" maybe more aligned with other material.  
 
This made me think "ok... I understand what it looks like, but what does this exported name do?".
 
One sentence like "exported names can be accessed from another package, while unexported names remains local".

**Comment by kytrinyx** [comment]
I'll have a go at clarifying this.
