### ISSUE TITLE
Exclude vendor from "./..."

### ISSUE THREAD

**Issue by ishbir** [golang/go#12010]
All go tools/subcommands, such as build, test, vet, fmt should exclude traversing the vendor directory when "./..." is given as the argument. Right now, one has to go through 'hacks' to get intended operation.

For example, what it is right now:
```bash
go vet ./... 2>&1 | grep -v ^vendor | grep -v '^exit status 1$'
go test ./... 2>&1 | grep -E -v '^FAIL[[:space:]]+github.com/user/repo/vendor'
```

What it should be:
```bash
go vet ./...
go test ./...
```

**Comment by bradfitz** [comment]
>All go tools/subcommands, such as build, test, vet, fmt should exclude traversing the vendor directory when "./..." is given as the argument. 

I disagree.

In any case, there are already open bugs discussing this.

**Comment by bradfitz** [comment]
Dup of #11659

**Comment by davecheney** [comment]
I agree with the OP, vendored code should be invisible to the tools, just
as if it was in another GOPATH segment.
