### ISSUE TITLE
reflect: PkgPath returns un-importable path

### ISSUE THREAD

**Issue by rgarcia** [golang/go#12019]
**What version of Go are you using (go version)?**

`go version go1.5beta3 linux/amd64`

**What operating system and processor architecture are you using?**

Ubuntu Precise 64 bit

**What did you do?**

I ran `PkgPath` on a `reflect.Type` in a vendored package: https://gist.github.com/rgarcia/f0c6507fbd1327d59bcf

(larger context: trying to solve https://github.com/golang/mock/issues/4)

**What did you expect to see?**

A path string that does not include the "vendor" component.

**What did you see instead?**

A path string that includes "vendor" (and thus cannot be used as an actual import due to ["must be imported as..."](https://github.com/golang/go/blob/226b28c85cd762f777135c102d83770fc4e6ade9/src/cmd/go/pkg.go#L546) compiler error).

**Comment by ianlancetaylor** [comment]
I think that the current behaviour is probably correct, but leaving open because I'm not entirely certain.

**Comment by rsc** [comment]
The current behavior is correct. reflect must return a globally unique identifier. It's not guaranteed that you can write a program using PkgPath directly. For vendoring, you can't. You have to remove the .../vendor/ part and you have to make sure the source you put the import in is in the right subtree.
