### ISSUE TITLE
runtime/cgo: _cgo_sys_thread_start error: implicit declaration of function

### ISSUE THREAD

**Issue by frederich** [golang/go#12029]
Windows amd64 build of go1.5beta3 fails.

```
v% all.bat
...
cmd/pack
# runtime/cgo
runtime\cgo\gcc_windows_amd64.c: In function '_cgo_sys_thread_start':
runtime\cgo\gcc_windows_amd64.c:32:2: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]
  thandle = _beginthread(threadentry, 0, ts);
  ^
cc1: all warnings being treated as errors
cmd/pprof/internal/profile
cmd/pprof/internal/tempfile
...

v% gcc --version
gcc (GCC) 4.9.2
```

**Comment by ianlancetaylor** [comment]
Any idea why _beginthread is not declared in <process.h>?  Is your GCC a cygwin or mingw32 build?

CC @alexbrainman

**Comment by ianlancetaylor** [comment]
Also, the line "cc1: all warnings being treated as errors" implies that something is passing -Werror to GCC.  Any idea where that is coming from?  As far as I can tell the Go build process does not add it.

**Comment by frederich** [comment]
Hi Ian,

I use the MSYS2 installer (https://msys2.github.io) which is a popular lightweight 64-bit POSIX environment. Bazel use it too (http://bazel.io/docs/windows.html).

I think it's a mingw-w64 gcc.

**Comment by rsc** [comment]
Hi. Windows ports of gcc vary wildly. As documented on https://github.com/golang/go/wiki/InstallFromSource#install-c-tools, building Go from source requires TDM-GCC. My understanding is that MSYS2 is the same kind of thing as Cygwin. I'm glad that works for Bazel, but Go expects to use the raw Windows libraries, not a POSIX wrapper. I don't believe we are going to support Go using POSIX wrapper utilities. Doing both is too hard, and the POSIX wrappers always eventually get in the way.
