### ISSUE TITLE
net/http: TLS handshake failure when session resumption is attempted

### ISSUE THREAD

**Issue by bgilmore** [golang/go#12024]
TLS session resumption by `net/http` `Transport` was broken by 3cf15b57f76400b22366ccd8ef5b211c72ab6a7f

Example program: http://play.golang.org/p/yNVJaXwaxM

go version go1.4.2 linux/amd64:
```
<no output>
```

go version devel +3cfc34a Tue Aug 4 21:10:58 2015 +0000 linux/amd64
```
Died on iteration 2: Get https://www.google.com/: tls: handshake did not verify certificate chain
exit status 1
```

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bgilmore** [comment]
Sent https://go-review.googlesource.com/13145, but I'm still working on a reasonable test.
