### ISSUE TITLE
cmd/compile: nilcheckelim allocates a lot

### ISSUE THREAD

**Issue by josharian** [golang/go#12021]
CL 12332 brought impressive speed-ups to the SSA nilcheckelim pass. Sadly, it significant increases the number of allocations. Let's circle around sometime later (when we're not focused on getting basic coverage and correctness) and see whether we can make that a little cheaper on the memory front.

/cc @tzneal

**Comment by dr2chase** [comment]
For "allocates a lot", are we worried about allocation count, or total size of all allocations?

**Comment by josharian** [comment]
It was the allocation count that caught my eye.
