### ISSUE TITLE
wiki: iOS example build instructions need more setup info

### ISSUE THREAD

**Issue by gedw99** [golang/go#12028]
The docs are here:
https://github.com/golang/go/wiki/Mobile

Buildng for IOS hit a few newbie roadblocks.
Building for Android is nice and simple.

The bash shell below shows what i mean.

gedw99-MacBook-Pro:example apple$ gomobile build -target=android golang.org/x/mobile/example/basic
gedw99-MacBook-Pro:example apple$ gomobile build -target=ios golang.org/x/mobile/example/basic
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/gomobile-work-025102198/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.4'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by gedw99** [comment]
environment:

gedw99-MacBook-Pro:example apple$ go version
go version go1.5beta3 darwin/amd64

**Comment by gedw99** [comment]
xcode environment:

gedw99-MacBook-Pro:example apple$ xcodebuild -showsdks
OS X SDKs:
	OS X 10.9                     	-sdk macosx10.9
	OS X 10.10                    	-sdk macosx10.10

iOS SDKs:
	iOS 8.4                       	-sdk iphoneos8.4

iOS Simulator SDKs:
	Simulator - iOS 8.4           	-sdk iphonesimulator8.4

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by crawshaw** [comment]
@gedw99 just so I can better understand your setup, if you try to run one of Xcode's default app templates on your iDevice, what happens?

**Comment by gedw99** [comment]
@crawshaw same thing in xcode :). i have been a naughty boy and not joned the apple developer program and paid my 79 euro.

the xcode 7 beta 4, does not require to have a apple developer account, so i will try that.

**Comment by gedw99** [comment]
Ok with Xcode 7 beta 4. In a test project in Xcode, I set an applie ID identity to use, but did not assign a provisioning profile.

so when i rerun the golang build for ios i get:

omobile build -target=ios golang.org/x/mobile/example/basic
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/gomobile-work-112842632/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.4'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)


---

This is to be expected, and i just need to

**Comment by gedw99** [comment]
Actually i noticed that its trying to build for IOS 8.4. For 9.0 you dont need code signing i think ( not sure ). I wonder is there is a need or way to toggle this ??

**Comment by rakyll** [comment]
Xcode 7 doesn't require you to sign the app with a signing identity. But Xcode 7 is still in beta. Until it gets out of beta, we still need to document downloading a signing identity. I will improve the docs later this week.

**Comment by gedw99** [comment]
OK. Makes sense. Thanks.
Looking forward to trying out the touch signals on ios. It's my main need at the moment.

**Comment by rakyll** [comment]
Wiki mentions it is required to obtain signing entities and downloading provisioning profiles now.

**Comment by owulveryck** [comment]
I've tried to compile the examples with ```XCode 7 beta 5```, and I ran into the same problem.
It looks like that I can compile a project within XCode (the GUI) without signing it, but there is no way to use the CLI to do te same. Therefore ```gomobile``` does not work.
I've tried to reinstall the command line tools from the DMG "Command_Line_Tools_OS_X_10.10_for_Xcode_7_beta_5" without any more success.
My understanding is that I have to wait for iOS 9 to be installed on my iPhone to enable a "developper mode". I am right ?

**Comment by shurcooL** [comment]
The Mobile wiki currently says:

> Prior to Xcode 7, you need to obtain a signing identity and download provisioning profiles in order to continue.

Xcode 7 was released today. I've downloaded it and ran into the same problem:

```
$ gomobile build -target=ios golang.org/x/mobile/example/basic
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/tw/kgz4v2kn4n7d7ryg5k_z3dk40000gn/T/gomobile-work-121840117/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

I went to Xcode, Preferences, Accounts, and added my Apple ID. Still same issue.

Then I went to View Details and pressed Create action button next to "iOS Development" of signing identities:

![image](https://cloud.githubusercontent.com/assets/1924134/9928875/e8fb9960-5cdd-11e5-85b7-3e8e1fa83a0e.png)

After that, the error became different:

```
$ gomobile build -target=ios golang.org/x/mobile/example/basic
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/tw/kgz4v2kn4n7d7ryg5k_z3dk40000gn/T/gomobile-work-329279846/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

It seems that even with Xcode 7, you still need a signing identity and provisioning profiles? Or am I missing/doing something wrong? Note, I haven't plugged in a physical iOS device yet; I was gonna try the .app bundle on simulator first.

**Comment by crawshaw** [comment]
@shurcooL moved to #12660
