### ISSUE TITLE
tour: better explanation mutation by pointers

### ISSUE THREAD

**Issue by gayanhewa** [golang/go#12034]
Context: https://tour.golang.org/methods/3

"The Scale method has no effect when v is a Vertex. Scale mutates v. When v is a value (non-pointer) type, the method sees a copy of the Vertex and cannot mutate the original value."

Change the example to : 

    v := Vertex{3, 4}
	v1 := v
	v.Scale(5)
	fmt.Println(v1,v, v.Abs())

The resulting output is much clearer : 

    {3 4} {15 20} 25

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Maybe:

```go
v := Vertex{3, 4}
fmt.Printf("Before scaling: %+v", v)
v.Scale(5)
fmt.Printf("After scaling: %+v", v)
```

What do you think, @adg?

**Comment by adg** [comment]
SGTM
