### ISSUE TITLE
Cgo: write C code in a more proper way

### ISSUE THREAD

**Issue by StEvUgnIn** [golang/go#12031]
Hello,
Just like C code is written in Go comments, an IDE implementation would bring problem for intellisense. I find the current notation ugly. From today on, I propose to implement old style Pascal comments to use C code with Cgo.
```
package cgoexample

(*
    #include <stdio.h>
    #include <stdlib.h>

    void myprint(char* s) {
        printf("%s", s);
    }
*)

import "C"
import "unsafe"

func Example() {
    cs := C.CString("Hello from stdio\n")
    C.myprint(cs)
    C.free(unsafe.Pointer(cs))
} 
```

What do you think ? I think it would be another good loan to Pascal.

**Source**
http://www.freepascal.org/docs-html/ref/refse2.html
http://www.math.uni-leipzig.de/pool/tuts/FreePascal/prog/node3.html

**Comment by davecheney** [comment]
I'm sorry we cannot change the language, including the two forms of comment's it accepts, `//`,  and `/* */`.

I feel that you can use the C style `/*` ... `*/` forms equally as well as the example you showed above. Note that C code must directly preceed the `import "C"` line, that is there must be no linebreak between the commentary and the import declaration.

**Comment by pablochacin** [comment]
I will second ANY proposal to make included C code unmistakably distinguishable from comments. 
I Personally would prefer an explicit directive like 

    inline{
         //  C code goes here
    }

**Comment by davecheney** [comment]
@pablochacin C is not part of the Go language specification. cgo is implemented entirely as a preprocessor and the go tool on top of the regular go compiler.

**Comment by StEvUgnIn** [comment]
@davecheney Why cannot Cgo pimp go language and add syntaxes. It is a preprocessor. So I don't think there could be a problem.

Using the C preprocessor in Go would be great too : 
```
{$ifdef OS}
/* Go code */
{$endif}
```

**Comment by dominikh** [comment]
Or you could just move the majority of your C code to actual `.c` files.

**Comment by StEvUgnIn** [comment]
@dominikh Does anything happens if there's a comment in a `.c` file included in Go using cgo ?

**Comment by ianlancetaylor** [comment]
@dominikh All cgo cares about is what you put in the .go file.  You can write
    // #include "foo.h"
    import "C"
and put anything you like in foo.h.  You can still reference things declared in foo.h using the C. syntax--see the cgo docs.

**Comment by dominikh** [comment]
@ianlancetaylor I assume your last comment was directed at @StEvUgnIn, not me?

**Comment by davecheney** [comment]
@StEvUgnIn et al, this issue is marked as closed. Please continue the discussion on golang-nuts. Thanks.

**Comment by ianlancetaylor** [comment]
@dominikh Yes, sorry.  Error on my part.
