### ISSUE TITLE
cmd/compile: document whether c-archive is supported on 386

### ISSUE THREAD

**Issue by sinuos** [golang/go#12048]
i use "GOARCH=386 go build -buildmode=c-archive",it shows ": no buildable Go source files in"
if use "GOARCH=386 go build -buildmode=c-shared", it shows "-buildmode=c-shared not supported on linux/386"

**Comment by bradfitz** [comment]
The error message seems to answer the question?

**Comment by sinuos** [comment]
the error message  shows "-buildmode=c-shared" not supported on linux/386, but "-buildmode=c-archive"
also not support on linux/386?

**Comment by bradfitz** [comment]
Over to @ianlancetaylor to clarify and/or fix the error message.

**Comment by ianlancetaylor** [comment]
You need to tell us more.  What files are in the directory in which you run the command?  Are there any buildable Go source files there?

**Comment by sinuos** [comment]
yes,there is Go sources file ,if i just use "go build -buildmode=c-archive" without "GOARCH=386",it can build  an archive file that can be linked into a C program

**Comment by ianlancetaylor** [comment]
I can not recreate the problem.  Can you show a small example with the exact .go files you are using?

I do see a completely different problems.  When setting GOARCH with -buildmode=c-archive, you may need to add a go build argument
    -ldflags=-linkmode=external

**Comment by sinuos** [comment]
[root@ubuntu:mytest]# tree
.
├── mytest.go
└── p
    └── p.go
this is mytest.go
package main // import "mytest"
 
import _ "mytest/p"
 
func main() {} // ignored

this is  p.go
package p //import "mytest/p"
 
import "C"

//export Foo
func Foo() int32 { return 42 }

use "GOARCH=386 go build -ldflags=-linkmode=external -buildmode=c-archive" failed

**Comment by ianlancetaylor** [comment]
Ah.  By default, cross-compilers do not enable cgo, so the go tool is ignoring p/p.go since it needs cgo.  You need to say

CGO_ENABLED=1 GOARCH=386 go build -buildmode=c-archive

**Comment by sinuos** [comment]
oh,thank you
