### ISSUE TITLE
runtime: strange panic message

### ISSUE THREAD

**Issue by bronze1man** [golang/go#12046]
I have following program.

```go
package main

type st string
func main() {
	s:=st("1")
	panic("a="+s)
}
```
http://play.golang.org/p/0DCktht8U2

I think it should not compile, but it compile and got the panic message:
```
panic: (main.st) (0x63660,0x1020a040)

goroutine 1 [running]:
main.main()
	/tmp/sandbox341206984/main.go:6 +0x100

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/src/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64p32.s:1086 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64p32.s:1086 +0x1
```

**Comment by cznic** [comment]
> I think it should not compile...

Please discuss why it should not compile, the program seems legal to me.

> ... but it compile and got the panic message:

Somewhere in the runtime the stack trace printing routine attempts to output the value panic was called with. It handles predeclared types, like eg. string, and probably some others. The argument to `panic` is converted to an `interface{}`, I think the two numbers printed are the tww items in the `interface{}` runtime `struct {*typeInfo, *value}`.

FTR: converting the argument to `string` makes the trace look more usual: http://play.golang.org/p/einqqW9zTp

**Comment by ianlancetaylor** [comment]
This is working as expected.  The panic messages is telling you the type followed by the value.  panic handles the predeclared type "string" specially, and it handles types that implement the fmt.Stringer method specially.

**Comment by bronze1man** [comment]
"why it should not compile?"
Type st should not add with string type. It looks like different types.

**Comment by ianlancetaylor** [comment]
The literal "a=" is an untyped constant.  This is not string + st, it's untyped + st.

http://golang.org/ref/spec#Constants

**Comment by bronze1man** [comment]
Thanks. I just forgot that.
