### ISSUE TITLE
all: refresh CONTRIBUTORS file before release

### ISSUE THREAD

**Issue by rsc** [golang/go#12042]
We should set up a process where CONTRIBUTORS gets updated semiautomatically.
See #10639 for the last time, which I believe was more manual.

**Comment by bradfitz** [comment]
I wrote a tool for it. But it has to run inside Google (with my credentials refreshed) to hit the CLA server.

**Comment by bradfitz** [comment]
I've added the Google-internal tool to google3/experimental/users/bradfitz/updateac/updateac.go for now so I don't lose it. We can put it somewhere better outside of experimental when it's code reviewed and we decide on a name and location. (which might prove more difficult than writing the tool)

I don't know what it takes to close this bug. I doubt we'll be able to auto-run the tool regularly, given its dependence on Google's internal CLA service.

We can at least run this again right before Go 1.6 is released.

**Comment by andygrunwald** [comment]
@bradfitz Is this tool open source or public available?

**Comment by bradfitz** [comment]
Nope. It uses a Google-internal service.

**Comment by andygrunwald** [comment]
That was fast. Thx.

**Comment by bradfitz** [comment]
I also submitted git rev 9a2d717fa9c yesterday but forgot to mention this issue.

It might be okay to close this bug now. @rsc?

**Comment by rsc** [comment]
It's kind of nice to have a bug open to remind us. I was thinking we could just move the milestone. But whatever you want to do is fine, since you run the tool.

**Comment by bradfitz** [comment]
Moving to Go 1.8. I don't expect new contributors during the deep freeze for Go 1.7.

**Comment by bradfitz** [comment]
Demoting this to Go1.8Maybe at this point. Corp policy no longer requires these A+C files (lawyers now happy with Git history? shrug), so continuing to do this mostly is just to recognize contributors with a nice URL at this point (https://golang.org/CONTRIBUTORS).

If there are new contributors during the freeze we can do this again. But https://golang.org/cl/33028 got the bulk of the Go 1.8 contributors from the first half of the cycle.

**Comment by rsc** [comment]
Yes, the CONTRIBUTORS file is basically just a nice acknowledgement. The AUTHORS file seems to me the more important one. Whether layers care or not, I'd personally feel sleazy shipping open source code that says "Copyright 2016 The Go Authors" without a public definition of who that is.

Agree that it's probably close enough for Go 1.8, but one more round near Go1.8rc1 might be good.

**Comment by bradfitz** [comment]
I'm just saying it's no longer an OSPO requirement. I agree that AUTHORS is more important. I wonder if we could update CONTRIBUTORS regularly (which can be automated outside of google, not needing the CLA's corp info) and say that people should add their name or company name to AUTHORS by hand (sending in a CL) if they care.

**Comment by rsc** [comment]
We've already had confusion when people were updating by hand. I much prefer the automated updates. Once a release cycle seems fine although I know you're the one running it.

**Comment by bradfitz** [comment]
Pending CL 34658 is probably enough for Go 1.8. I don't expect unique contributors to the project in the month between now and the release, over the holidays. Moving to Go 1.9.

**Comment by bradfitz** [comment]
Okay, caught up now for Go 1.9. Moving to Go 1.10. If there are new contributors in the freeze (unlikely) they'll be included next cycle, unless somebody remembers to re-run this.

**Comment by odeke-em** [comment]
Thank you @bradfitz for running this for Go1.10 and for the other milestones too! I'll now move the milestone to Go1.11 until we get to a point where it is automated. @broady if interested, could we perhaps in the next cycle collaborate on making some simple automation to run this right before every release?

**Comment by bradfitz** [comment]
It's already automated, but the code's inside Google because it depends on Google's internal CLA ~gRPC verification service. But then even though it's mostly automated, it still requires plenty of manual cleanup because people's git Authors & Gerrit names are often not their proper names. Determining that requires a human.

**Comment by bradfitz** [comment]
I'm going to keep this at Go1.10 for now so we do one final round before shipping, in case there are last minute new contributors.

**Comment by odeke-em** [comment]
Ahh I see, gotcha @bradfitz.

**Comment by bradfitz** [comment]
CL 86478 is the last one for Go 1.10. Moving this to Go 1.11.

**Comment by ashishgandhi** [comment]
With the recent Go release, shouldn't this have been done too? Or maybe it was and this issue wasn't linked to, in which case I apologize.

**Comment by bradfitz** [comment]
@FiloSottile said he'd do it this cycle.

@FiloSottile, this is one of the bugs we never close but just keep it alive as a reminder from release-to-release. So after rc2 (when we generally stop updating this file), then change it to Milestone Go 1.12.

**Comment by bradfitz** [comment]
I showed @FiloSottile how to use the internal tool we have for updating this today.

**Comment by rsc** [comment]
Last CL said "final for Go 1.11" so bumping to Go 1.12.

**Comment by FiloSottile** [comment]
@dmitshur The tool is at google3/go/team/updateac/updateac.go. You'll have to strip all the parts related to CLAs and AUTHORS as [we don't update that automatically anymore](https://github.com/golang/go/blob/5ec5c5741ec7d0e051667f13094f532833d41578/AUTHORS#L5-L7).

There's a sorting tool in the go tree at misc/sortac. I think we could probably merge it with the contributors tool eventually.

**Comment by dmitshur** [comment]
Second round is the last for 1.12. Moving to 1.13.

**Comment by dmitshur** [comment]
I'll do a round for Go 1.13 soon.

**Comment by odeke-em** [comment]
Hello @dmitshur, I believe in CL https://go-review.googlesource.com/c/go/+/186397/ you made the first round update about 17 days ago and in that time am not sure there have been too many new contributors. Shall we move this issue to the next milestone, Go1.14?

**Comment by odeke-em** [comment]
Actually I just re-run `updatecontrib` on my machine and it brought up some more additions but then encountered some Github API errors, so I shall defer to you for another round of updates :)

**Comment by dmitshur** [comment]
I've sent [CL 220363](https://golang.org/cl/220363) with the second, and final, round of updates for Go 1.14.

Moving this issue to the Go 1.15 milestone.

**Comment by dmitshur** [comment]
The [CONTRIBUTORS](https://tip.golang.org/CONTRIBUTORS) file was updated for the Go 1.15 release in [CL 247767](https://golang.org/cl/247767).

Moving this recurring issue to the next major release.

**Comment by cagedmantis** [comment]
The CONTRIBUTORS file was updated for the Go 1.16 release in [CL 291189](https://golang.org/cl/291189).

Moving this recurring issue to the next major release.

**Comment by cagedmantis** [comment]
The CONTRIBUTORS file was updated for the Go 1.17 release in [CL 341709](https://golang.org/cl/341709).

Moving this recurring issue to the next major release.

**Comment by dmitshur** [comment]
[CL 388394](https://go.dev/cl/388394) took care of this for Go 1.18. Moving to the next milestone.

**Comment by rsc** [comment]
Filed #53961 to delete this files, at which point we will never need to update them again and can close this issue.

**Comment by rsc** [comment]
All gone.
