### ISSUE TITLE
website: use sha256 on download page

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#12057]
Given that sha1 is effectively obsolete (at the very least officially deprecated), please consider listing the sha256 checksums on the Go download page in place of or addition to the sha1 checksums currently listed on download page.

I apologise in advance if bugs relating to the website should be filed elsewhere; it was not immediately obvious where to file them.

**Comment by ianlancetaylor** [comment]
CC @adg

**Comment by rsc** [comment]
I agree that we should replace SHA-1 in the long term, but it's still okay for this release. For Go 1.6 we should look into a different checksum.

**Comment by adg** [comment]
SHA256.

**Comment by rsc** [comment]
ping @adg, @bradfitz
