### ISSUE TITLE
cmd/go: #cgo pkg-config: add conditional --static flag to pkg-config

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#12058]
I found this case when working on Docker. Docker can be linked either statically or dynamically. For static linking, one has to specify all the libraries explicitly, including those required indirectly (i.e. by libraries that you use). For dynamic linking, one needs to specify only the libraries one uses directly. For example, when linking against libxml2 on Linux, for the case of dynamic linking you have to specify only -lxml2, while for the static linking case you have to also specify all the libraries used by libxml2 (like -lz -lm -llzma).

Fortunately, pkg-config supports this:

```
$ pkg-config --libs libxml-2.0
-lxml2 
$ pkg-config --libs --static libxml-2.0
-lxml2 -lz -llzma -lm 
```

I was expecting Go to add --static flag when the result is going to be statically linked, unfortunately it never happens. My current workaround is to do this:

```
// #cgo pkg-config: --static libxml-2.0
```

It solves my issues, but the problem with this approach is this leads to "overlinking" in the dynamic case, as described e.g. here: https://wiki.openmandriva.org/en/Overlinking_issues_in_packaging

Is it possible to implement conditionally adding --static to pkg-config invocation?

**Comment by ianlancetaylor** [comment]
It's not immediately obvious to me how we can know whether we are going to be linking statically or linking dynamically.  Are you suggesting that we look for the presence of --static in the -ldflags option?

**Comment by kolyshkin** [comment]
@ianlancetaylor That is the biggest obstacle to me as I'm not an expert, that's why I filed an issue rather than sent a pull request. I looked around for ways to tell go to produce a static binary with cgo or gccgo, and it looks like they all end up with passing -static flag.

**Comment by kolyshkin** [comment]
At the very least, it makes sense to add --static flag to pkg-config unconditionally, this will greatly improve the chances of making the build work.

**Comment by kolyshkin** [comment]
One example I just came across: gosqlite package which says 
```#cgo LDFLAGS: -lsqlite3```
If you try to build a binary with it dynamically, everything works. If you try to build it statically, it complains about missing pthread* and dlopen/dlsym/etc symbols. Let's look at pkg-config:
```
$ pkg-config --libs sqlite3
-lsqlite3  
$ pkg-config --libs --static sqlite3
-lsqlite3 -ldl -lpthread 
```
So, it's all there they way it should be. One would thing that everything that is needed to fix it would be this:
```
-#cgo LDFLAGS: -lsqlite3
+#cgo pkg-config: sqlite3
```
Unfortunately, one needs to either add --static unconditionally, or wish that cmd/go would do it for them.

**Comment by ianlancetaylor** [comment]
@kolyshkin Sorry, I didn't mean to suggest that you should fix this.  I'm trying to understand what you are suggesting.  Let me try this: when you say "Docker can be linked either statically or dynamically" what do you mean?  How does one decide to link Docker statically?  How does one decide to link it dynamically?

**Comment by kolyshkin** [comment]
@ianlancetaylor sure! Looking into Docker build scripts, it's something like this (simplified for clarity):
```go build -ldflags '-extldflags "-static"' ...```
and when using gccgo (according to [1]) this should be:
```go build -compiler gccgo --gccgoflags "-static"```

**Comment by mattn** [comment]
s/pgk-config/pkg-config/g

**Comment by kolyshkin** [comment]
Sure it would be easier just to do something like
```go build -static```
and let cmd/go construct the proper flags depending on whether cgo or gccgo or something else is used. That would also make C static linking case detection easier. But I don't know enough to propose it.

**Comment by kolyshkin** [comment]
@ianlancetaylor please let me know what do you think about this suggestion

**Comment by minux** [comment]
Why not just add a new cgo file protected by a build tag, say, static?

// file static_cgo.go

// +build static

/*
#cgo pkgconfig: --static libxml-2.0
#cgo LDFLAGS: -static
*/
import "C"

And use go build -tags static will build a static binary.

**Comment by ianlancetaylor** [comment]
@kolyshkin I don't like the idea of adding a -static option to go build.

Minux's suggestion SGTM.

I would be OK with adding a -pkgconfigflags option to go build.  This would provide a list of options that would be passed to pkg-config.

**Comment by mattn** [comment]
`pkg-config --static` is same as just adding `LDFLAGS --static` ?

http://linux.die.net/man/1/pkg-config
```
--static
Output libraries suitable for static linking. That means including any private libraries in the output. This relies on proper tagging in the .pc files, else a too large number of libraries will ordinarily be output.
```
Do you know what is `private libraries` meaning? AFAICS, they are not same.

**Comment by ianlancetaylor** [comment]
Right: the pkg-config command takes a --static option; see the man page.  I'm not sure what you mean by `LDFLAGS --static`, but that is not the same as the --static option to the pkg-config command.

The reference to private libraries is because when linking statically you need to explicitly list all the libraries you need.  Shared libraries include a list of their dependencies, so you only have to link against the main shared library.  Static libraries do not include such a list, so you need to link against all of them.

**Comment by xlab** [comment]
Adding -static to LDFLAGS will force a fully static build which is impossible on OS X. So this option shouldn't necessarily come with --static for the pkg-config.

**Comment by kolyshkin** [comment]
@mattn 
> `pkg-config --static` is same as just adding `LDFLAGS --static` ?

No, these are totally different things.

`pkg-config --libs NAME` (with or without `--static`) provides you with compiler options needed to link against NAME).

`LDFLAGS += -static` is a flag to C linker instructing it to produce a statically linked binary.

> Do you know what is private libraries meaning? AFAICS, they are not same.

In this context "private libraries" means "all the libraries that this library itself uses/needs". Let me give you an example.

If we want to build something *dynamically* with libsqlite, we add `-lsqlite` to `CFLAGS` (or `CXXFLAGS`, doesn't matter). Note we don't need to explicitly list the libraries that are used by `libsqlite` itself (such as `libdl`), as this is something that dynamic linker will care about (these dependencies are already embedded into `libsqlite.so`). We can list them explicitly, but that would lead to so-called overlinking (https://wiki.mageia.org/en/Overlinking_issues_in_packaging), so we'd rather not do that.

Now, if we want to build something *statically*, we need to list all the libraries explicitly in `CFLAGS`, including the libraries that we need, and the libraries that those libraries need.

So, for dynamic build of something with libsqlite, we need `CLFAGS += -lsqlite`, while for static build we need `CFLAGS += -lsqlite -ldl`. This is why `pkg-config` adds support for `--static` flag.

**Comment by kolyshkin** [comment]
> Why not just add a new cgo file protected by a build tag, say, static?

This sort of works for me. The only problem I see is a need to ask everyone who's using `--gccgoflags "-static"` or `--ldflags '-extldflags "-static"' to their `go build` command to also add `-tags static`. It would be great if such a tag (or any other we could use) will magically appear itself (similar to $GOOS, $GOARCH or say `cgo` tags), so we won't have to modify all the building scripts.

If the above is impossible, I guess we can close this issue.

**Comment by minux** [comment]
On Mon, Oct 5, 2015 at 5:25 PM, Kirill Kolyshkin <notifications@github.com>
wrote:

> Why not just add a new cgo file protected by a build tag, say, static?
>
> This sort of works for me. The only problem I see is a need to ask
> everyone who's using --gccgoflags "-static" or --ldflags '-extldflags
> "-static"' to theirgo buildcommand to also add-tags static. It would be
> great if such a tag (or any other we could use) will magically appear
> itself (similar to $GOOS, $GOARCH or saycgo` tags), so we won't have to
> modify all the building scripts.
>
My proposed solution doesn't require the user to pass extra -ldflags or
-gccgoflags
because it includes "#cgo LDFLAGS: -static". (there is a bug preventing
gccgo
from working correctly in this case, but that's a separate issue.)

see https://github.com/golang/go/issues/12058#issuecomment-139074739

**Comment by kolyshkin** [comment]
> My proposed solution doesn't require the user to pass extra -ldflags or -gccgoflags
> because it includes "#cgo LDFLAGS: -static".

@minux Sorry, I overlooked it. Looks like it's a good way to go!

**Comment by bcmills** [comment]
#26492 has the label Proposal-Accepted. Does that proposal subsume this one?

**Comment by kolyshkin** [comment]
> Does that proposal subsume this one?
@bcmills yes it does; so I guess this one can be closed.
