### ISSUE TITLE
doc/go1.5: -asmflags mentioned twice

### ISSUE THREAD

**Issue by joeshaw** [golang/go#12053]
In the "Go command" section:

* A new -asmflags build option sets flags to pass to the assembler. However, the -ccflags build option has been dropped; it was specific to the old, now deleted C compiler .
* A new -buildmode build option sets the build mode, described above.
* An -asmflags build option has been added to provide flags to the assembler. However, the -ccflags build option has been dropped; it was specific to the old, now deleted C compiler .

I am not sure where doc/go1.5 lives, so I didn't send a CL for it.

**Comment by ianlancetaylor** [comment]
The file in the repository is doc/go1.5.html.

**Comment by joeshaw** [comment]
How embarrassing.  I was grepping in only the `src` subdirectory.
