### ISSUE TITLE
Unable to use the generated type from wsdl

### ISSUE THREAD

**Issue by seema-emc** [golang/go#12063]
I am very new to Go and unable to find help on other sources. I am trying to create go code with standard vim25.wsdl file. It generated the go code successfully. Two structures are here..

type RetrieveServiceContentRequestType struct {
	XMLName xml.Name `xml:"urn:vim25 RetrieveServiceContentRequestType"`

	This *ManagedObjectReference `xml:"_this,omitempty"`
}

type ManagedObjectReference struct {
	XMLName xml.Name `xml:"urn:vim25 ManagedObjectReference"`

	Value string

	Type string `xml:"type,attr,omitempty"`
}

Now I am unable to assign values to RetrieveServiceContentRequestType  as follows with following error:
	client := mysoap.NewVimPortType("https://myvc/sdk", true)

	var serviceInstance = mysoap.ManagedObjectReference{
		Type:  "ServiceInstance",
		Value: "ServiceInstance",
	}
	fmt.Println(serviceInstance)
	req := mysoap.RetrieveServiceContentRequestType{
		This: &serviceInstance,
	}
	_, err:= client.RetrieveServiceContent(&req)
	

Error xml: name "_this" in tag of mysoap.RetrieveServiceContentRequestType.This
conflicts with name "ManagedObjectReference" in *mysoap.ManagedObjectReference.X
MLName

Any help would be appreciated.

**Comment by adg** [comment]
Hi. This issue tracker is for tracking bugs in the Go project. If you need help, please ask the [mailing list](https://groups.google.com/forum/#!forum/golang-nuts).
