### ISSUE TITLE
cmd/dist: test should not rebuild by default

### ISSUE THREAD

**Issue by davecheney** [golang/go#12064]
`go tool dist test -list` rebuilds the standard library

```
pi@raspberrypi ~/go/src $ go tool dist test -list 

##### Building packages and commands.
runtime
^C
```

-list won't run any tests, so it shouldn't kick of an expensive rebuild.

**Comment by bradfitz** [comment]
Perhaps. This isn't really a user-visible tool. It's just used by the test infrastructure in the build coordinator.

This is easy enough to fix but a) it would preclude listing or omitting any tests that are only known about after a build (none currently, but I'd like to omit stdlib packages from the list if they didn't have test files or test files with the right +build tags), and b) once we do this, then people will file bugs about `go tool dist test <testname>` also rebuilding probably.

I'd kinda prefer to do nothing.

**Comment by davecheney** [comment]
Counter proposal, -list enables -no-rebuild, which is what you need to pass
to make the tool do what you want.

I agree that it's an internal tool, but today I needed to use -list to
figure out the name of the test group I wanted to run. I don't think it'll
take much effort to make -list more user friendly.

**Comment by bradfitz** [comment]
That doesn't address either of my a) or b) comments.

How about just failing immediately if you use `-list` and things aren't already built. That would address both my concerns.

**Comment by davecheney** [comment]
Everything was built, passing -list wanted to build them again before it
would tell me the names of the test groups.

**Comment by bradfitz** [comment]
I am talking about the case where things are NOT built. You're discussing one specific set of cases. I'm considering all the states that the world might be in when you run said command, making sure the command does consistent things.

My counter-counter proposal was:

  *  a) (world built + `-list`) => automatically set `-no-rebuild` to true.
  *  b) (world not built + `-list`) => fail, saying you need to build first.

You want a). I am proposing that a) is only acceptable if we also do b).

**Comment by rsc** [comment]
The problem here is "rebuild by default". We should make test _not_ rebuild by default, rename the flag to -rebuild, and pass -rebuild from run.{bash,bat,rc} where we need it.

**Comment by iWdGo** [comment]
While searching for some issue, this issue can apparently be closed as no build occurs w/o specific flags.
```
go\src>go tool dist version
go1.11.4
go\src>go version
go version go1.11.4 windows/amd64
go\src>git checkout master
go\src>go tool dist test -list
go_test:archive/tar
go_test:archive/zip
...
```
Using a build.
```
go\src>cd ..
go>set GOROOT=%CD%
go>cd src
go\src>go tool dist version
devel +b8043024cf Sat Dec 22 15:07:58 2018 +0100
go\src>go tool dist test -list
go_test:archive/tar
go_test:archive/zip
...
```

**Comment by bradfitz** [comment]
@iWdGo, thanks.
