### ISSUE TITLE
doc: release notes recommend wrong version of NaCl

### ISSUE THREAD

**Issue by davecheney** [golang/go#12062]
> On NaCl, Go 1.5 requires SDK version pepper-39 or above because it now uses the get_random_bytes system call.

I believe this is incorrect. Go does not use the new `get_random_bytes` syscall, see #11961. As best I can tell NaCl requires pepper < 43

/cc @adg @rsc

**Comment by adg** [comment]
I actually don't know. Happy to amend the docs.

**Comment by davecheney** [comment]
OK, I'll send a PR. The range of usable pepper versions is quite narrow.

**Comment by randall77** [comment]
Yet more evidence that compiling to static binaries is awesome.
