### ISSUE TITLE
sync: docs say WaitGroup is a function, and that it panics

### ISSUE THREAD

**Issue by elimisteve** [golang/go#12060]
From https://tip.golang.org/doc/go1.5 --

> The WaitGroup function in package sync now diagnoses code that races a call to Add against a return from Wait. If it detects this condition, WaitGroup panics.

`WaitGroup` is a type, not a function.  In looking at the race-related code in the `WaitGroup.Add()` and `WaitGroup.Wait()` methods, I think this line in the docs is supposed to read more like:

> sync.WaitGroup's Add method now diagnoses code that races a call to Add against a return from Wait. If it detects this condition, Add panics.

**Comment by rsc** [comment]
https://go-review.googlesource.com/13324
