### ISSUE TITLE
runtime: missed write barrier with race detector

### ISSUE THREAD

**Issue by rsc** [golang/go#12068]
Reported on golang-dev by carl@stripe.com. This program, reduced from a much larger one, crashes due to GC missing objects when run under the race detector. Best suspect is missed write barrier in that mode.

	GODEBUG=gccheckmark=1 go run -race heavy.go 
	
	package main
	
	type Interface interface {
		Dummy()
	}
	
	type Thing1 struct {
		a, b *int
	}
	
	type Thing2 struct {
		Thing1
	}
	
	func (_ Thing2) Dummy() {}
	
	func NewThing1() Thing1 {
		return Thing1{new(int), new(int)}
	}
	
	func NewThing2() Interface {
		return &Thing2{NewThing1()}
	}
	
	func main() {
		for i := 0; i < 20; i++ {
			go func() {
				for {
					t := NewThing2()
					t.Dummy()
				}
			}()
		}
		<-make(chan struct{})
	}

Damian Gryski suggests perhaps the bug was introduced on github.com/golang/go/commit/8f34b25318e712a18c3847bb1cc3e8d87076c211.

**Comment by rsc** [comment]
@aclements @RLH FYI, but I don't think this is the GC's fault.

**Comment by dgryski** [comment]
A more accurate description of my git-bisect attempts is that there have been a number of commits that made this occur with increasing frequency.  Ranging from once every 20min of testing at the above commit to every 3-4 seconds with tip.  These changes tend to be at a point where the gc has been tweaked.

**Comment by rsc** [comment]
Variant that exits, for testing:

	package main
	
	type Interface interface {
		Dummy()
	}
	
	type Thing1 struct {
		a, b *int
	}
	
	type Thing2 struct {
		Thing1
	}
	
	func (_ Thing2) Dummy() {}
	
	func NewThing1() Thing1 {
		return Thing1{new(int), new(int)}
	}
	
	func NewThing2() Interface {
		return &Thing2{NewThing1()}
	}
	
	func hammer(n int, c chan int) {
		for i := 0; i < n; i++ {
			t := NewThing2()
			t.Dummy()
		}
		c <- 1
	}
	
	func main() {
		c := make(chan int)
		for i := 0; i < 20; i++ {
			go hammer(2000000, c)
		}
		for i := 0; i < 20; i++ {
			<-c
		}
	}

**Comment by rsc** [comment]
Fix in CL 13364.

**Comment by zenazn** [comment]
Thanks, @rsc!
