### ISSUE TITLE
x/tools/go/vcs: FromDir doesn't work with srcRoot = "/"

### ISSUE THREAD

**Issue by hectorj** [golang/go#12079]
``` go
_, _, err := vcs.FromDir("/whatever/", "/")
```

gives the error `directory "/whatever" is outside source root "/"`, which is incorrect

**Comment by ianlancetaylor** [comment]
CC @paranoiacblack

**Comment by hectorj** [comment]
https://go-review.googlesource.com/#/c/13422/

**Comment by dmitshur** [comment]
Thanks for the report. This package has been deprecated in #57051 and won't receive further development, so closing this as not planned.
