### ISSUE TITLE
cmd/compile: don't copy args and externs into new stack slots

### ISSUE THREAD

**Issue by josharian** [golang/go#12070]
The current regalloc and stackalloc passes copy arguments and globals onto the local stack for use. This is unnecessary; they can be loaded from their original homes as needed.

/cc @randall77

**Comment by randall77** [comment]
Yes, it is unnecessary for args.  It seems necessary for globals unless we have alias information to know otherwise.

**Comment by rsc** [comment]
Are you talking about SSA? I don't believe that the current compiler copies either into the local stack.

**Comment by randall77** [comment]
Yes, these are SSA passes.

**Comment by rsc** [comment]
Thanks. Please do make sure the args are stored back into their original homes when spilled back to the stack. Debugging the runtime and other programs I depend on the stack trace showing the actual current values of the arguments (if they've been reassigned).

**Comment by rsc** [comment]
I'm a little worried about debuggers but at this point it may be too late for Go 1.7.
@randall77, move to Go 1.8?

**Comment by randall77** [comment]
This was fixed a while ago, sorry I didn't close the issue.
If args are not modified, they can be reloaded from their original locations.
If args are modified, they are spilled back to their original locations (if they are spilled at all).
