### ISSUE TITLE
tour: clicking a particular sequence causes web page load failure

### ISSUE THREAD

**Issue by gmlewis** [golang/go#12075]
Try this sequence of events from a Chrome browser:

1. Visit tour.golang.org.
2. Click on the right arrow.
3. Click on `Ukrainian` at the bottom.
4. Click on the right arrow.
5. Click on `English` at the top.

The page shows `This webpage is not available - DNS_PROBE_FINISHED_NXDOMAIN` with the browser URL of http://tour.golang.org.

**Comment by campoy** [comment]
Fixed
