### ISSUE TITLE
x/sys/unix: Getpagesize can return wrong value for Solaris

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#12076]
Getpsagesize hardcodes the return value of 4096 for Solaris.  The default pagesize on Solaris for amd64 can actually vary:

$ pagesize -a
4096
2097152
1073741824

With that said, Solaris currently defaults to 4096 for amd64, but this could change at some future point.  And for other architectures (admittedly not yet supported by Go, but that are in development) 
the default pagesize is definitely different, for example, SPARC where the default is currently 8192 although the default may change in the near future as current SPARC systems max out at 64 Terabytes of memory:

$ pagesize -a
8192
65536
4194304
268435456
2147483648

Issue 10180 touches on this subject, but in the context of cmd/link.  A response to my inquiry on golang-dev suggested that x/sys/unix (at least) should just return whatever the POSIX interface for page size returns:

https://groups.google.com/forum/#!topic/golang-dev/ZLzxYzULzU8

As such, I'm proposing to change x/sys/unix Getpagesize to use sysconf(3C) to get the actual value (and cache it, since the value never changes after the system boots) and return that instead.

**Comment by binarycrusader** [comment]
I will provide a CL soon with a proposed change for this.

**Comment by davecheney** [comment]
> I will provide a CL soon with a proposed change for this.

Please discussion your change first.

**Comment by binarycrusader** [comment]
I linked to the discussion thread on golang-dev; was there a specific concern to be addressed?

**Comment by davecheney** [comment]
> I linked to the discussion thread on golang-dev; was there a specific concern to be addressed?

I am sorry, I thought this change was being proposed to the main repository.

**Comment by binarycrusader** [comment]
Was fixed by:

CL https://golang.org/cl/14483
