### ISSUE TITLE
cmd/go: go test stale code

### ISSUE THREAD

**Issue by Vellocet** [golang/go#12074]
I am running go 1.4.1
My os is ubuntu server 14.04

When running two different unit tests with "go test", I get unexpected results, as if it has not rebuilding packages that have changed.

This has only happened twice so far.
The first time go test complained about an import cycle that no longer existed.  After poking at the code for a bit, it suddenly starts running again.  I revert all of my changes and it continues to work fine.

The second time I had a test which json marshals a struct, one of the elements was missing in the marshaled string.  When I changed the order of the elements of the struct, the element appeared in the string.  When I reverted it, it continued to work.

I haven't been able to reproduce this bug as the code currently works fine, and only breaks temporarily.  This has also only happened with those two tests.  All of my other tests work as expected when I change the code.

**Comment by davecheney** [comment]
Without details it is hard to advise, but one common case of this stake
behaviour was deleting a file from a package. Up to go 1.4.2 this would not
cause the package to be recompiled thus letting dependant packages behave
as if the symbols in that file were still present.

A simple way to verify this is to delete $GOPATH/pkg.

Thanks

Dave

**Comment by Vellocet** [comment]
Good to know about deleting files.  Both of the structs in question were generated by a protocol buffer compiler.

**Comment by rsc** [comment]
Fairly certain this bug is fixed.
