### ISSUE TITLE
A doc mistake in 'The Go Programming Language Specification' 

### ISSUE THREAD

**Issue by angryxlt** [golang/go#12082]
The section 'Statements->Assignments' in the language specification of version go1.4.2, 
which says
'
i = 2
x = []int{3, 5, 7}
for i, x[i] = range x {  // set i, x[2] = 0, x[0]
	break
}
// after this loop, i == 0 and x == []int{3, 5, 3}
' 
, actually, after this loop, x should be []int{7,5,3}.

The URL for this page is https://golang.org/ref/spec

**Comment by ALTree** [comment]
Nope. Run it: http://play.golang.org/p/HxdePj8K-M

```
[3 5 3]
```

**Comment by robpike** [comment]
The text is correct and is making a point about order of evaluation and declaration.
