### ISSUE TITLE
tour: removing type from type conversion does not make any difference.

### ISSUE THREAD

**Issue by iamamosh** [golang/go#12080]
Context: https://tour.golang.org/basics/13
 
The statement below imply that removing the type affect the result.
 
"Try removing the float64 or int conversions in the example and see what happens. "
 
I removed them, and tested their type using these lines.
 	fmt.Println(reflect.TypeOf(f))
	fmt.Println(reflect.TypeOf(z))
 
As far as I could tell, the result were the same even after removing type.  Maybe, there was a spec chagne?

**Comment by cespare** [comment]
> Try removing the float64 or int **conversions** in the example and see what happens.

I would guess that you removed the type declaration on the left-hand sides. If you had removed the conversions, you would see the following type errors:

```
main.go:10: cannot use x * x + y * y (type int) as type float64 in argument to math.Sqrt
main.go:11: cannot use f (type float64) as type int in assignment
```

See http://play.golang.org/p/5MHPK6kMjx

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by iamamosh** [comment]
Thank you for advices.  Now I see how I should have read this... Somehow, I thought it meant implicit declaration of type when moving casted data was not allowed.  My mistake.
