### ISSUE TITLE
`gomobile bind -target=ios` errors out

### ISSUE THREAD

**Issue by reddragon** [golang/go#12085]
In various talks recently, it was mentioned that gomobile has experimental support for iOS, but I get this error when I try to do `gomobile bind`:

    > gomobile bind -target=ios bitbucket.org/reddragon/demolib
    gomobile: -target=ios not yet supported

**Comment by ianlancetaylor** [comment]
CC @crawshaw 

For general questions like "how does this work?" it's usually better to use the mailing list rather than the bug tracker.  Thanks.

**Comment by hyangah** [comment]
when did you build the gomobile tool? does 'gomobile version' command work?
If it doesn't, it's time to sync the client and rebuild the tool.

2015-08-09 16:07 GMT-04:00 Ian Lance Taylor <notifications@github.com>:

> CC @crawshaw <https://github.com/crawshaw>
>
> For general questions like "how does this work?" it's usually better to
> use the mailing list rather than the bug tracker. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/12085#issuecomment-129233519>.
>



-- 
__

**Comment by reddragon** [comment]
My apologies.

I thought `golang get` auto-updates golang packages, it does not. I was on a month old `gomobile` build. It works now. Thanks for the awesomeness. :+1:
