### ISSUE TITLE
x/tools/cmd/goimports: package clause insertion mangles comments

### ISSUE THREAD

**Issue by josharian** [golang/go#12097]
Input:

``` go
// a
// b
// c

func main() {
    fmt.Println()
}
```

gofmt fails appropriately:

```
$ gofmt x.go 
x.go:5:1: expected 'package', found 'func'
```

goimports inserts a package clause and mangles the comments:

```
$ goimports x.go 
package main // a
import "fmt"

// b
// c

func main() {
    fmt.Println()
}
```

**Comment by bradfitz** [comment]
The package main insertion is intentional. It was requested and done as a feature at Gophercon 1's hack day.

The comment mangling of course is not.

**Comment by shurcooL** [comment]
Is this the same issue or a different issue?

Given the following input:

```Go
package main

import (
	"encoding/binary"

	// Some comment.
	"fmt"
)

func main() {
	fmt.Println()
}
```

`goimports` will try to remove "encoding/binary" and result in the following invalid Go code:

```Go
package main

import

// Some comment.
"fmt"

func main() {
	fmt.Println()
}
```

If it's not the same issue, let me know, I'll delete this comment and open a new issue to track this.

**Comment by josharian** [comment]
Hard to say whether it is the same issue without looking into the fix. Good to have multiple test cases regardless.

**Comment by shurcooL** [comment]
Ok, I'll delete the comment and move this into a separate issue then. In case the same fix resolves both issues, great, otherwise they can be looked at separately.

**Comment by danicat** [comment]
Is anybody working on this issue yet? I'm looking for something to contribute and it seems like a good one to start. What's the expected output of the given example?

**Comment by shurcooL** [comment]
I think the expected output would be:

```Go
package main

import "fmt"

// a
// b
// c

func main() {
	fmt.Println()
}
```

**Comment by josharian** [comment]
Welcome! I don't think anyone is working on it.

I guess I'd expect the package and imports to be inserted at the beginning of the file, with a blank line between the imports and the first comment. But it's not obvious, so if there's a good reason to do otherwise, I'm open to it.

Messing with the AST and comment positioning can be quite fiddly, so I recommend writing all your test cases first. Feel free to ask for help if needed.

Note that the likely reviewers for this (Brad, Robert, me) are all going to be slow, for our own reasons.

**Comment by danicat** [comment]
Great! I'll start working on this issue then. There is a better channel to talk to you if I need help or should I just write it on this thread? I promise I won't bug you without exhausting all my options first :)

**Comment by josharian** [comment]
This is a good place to discuss
