### ISSUE TITLE
net/http: must not copy tls.Config

### ISSUE THREAD

**Issue by rsc** [golang/go#12099]
net/http/transport says:

		cfg := t.TLSClientConfig
		if cfg == nil || cfg.ServerName == "" {
			host := cm.tlsHost()
			if cfg == nil {
				cfg = &tls.Config{ServerName: host}
			} else {
				clone := *cfg // shallow clone
				clone.ServerName = host
				cfg = &clone
			}
		}

But that line `clone := *cfg` is copying the entire tls.Config, including the sync.Once. That's not okay.

In particular if you arrange things right, you can get the copy to be going on at about the same time something else is calling cfg.serverInitOnce.Do, and then the write during the mutex races with the read from the copy, causing the race detector to report a race (and it is a real race, too; the copy will never be unlocked and will cause a deadlock).

Reported by a race detector run in a larger Google program.

Need to fix for Go 1.5.

**Comment by robpike** [comment]
While you're there: transport_test.go:2648: possible formatting directive in Error call

**Comment by bradfitz** [comment]
Got a repro or race failure?

Is the race purely on its copy and not the Transport trying to use the Once I hope?

**Comment by rsc** [comment]
Let's leave the test format issues for a separate change. They are not critical; this one is.
Brad, I sent you more details in email.

**Comment by bradfitz** [comment]
I managed to reproduce. I'll check corp mail later. No corp or tethering on phone.

There's a similar case in ListenAndServeTLS. I have one fix but they probably both need same treatment. And a test to ensure new fields added to tls.Config still get copied in the future.

**Comment by rsc** [comment]
We should probably update the vet lock checker to look for sync.Once too. I don't quite understand what it's doing now. It looks like maybe it complains about any field with a Lock method.
