### ISSUE TITLE
fmt: x format verb for []byte fails in a recursive call to Fscanf from a scanln call in go1.5rc1

### ISSUE THREAD

**Issue by hubslave** [golang/go#12090]
Consider the following code:
```go
package main

import "fmt"

type arr [2]byte

func (x *arr) Scan(ss fmt.ScanState, verb rune) error {
	var b []byte
	_, err := fmt.Fscanf(ss, "%4x", &b)
	copy((*x)[:], b)
	return err
}

func main() {
	var x arr
	n, err := fmt.Sscanln("0123\n", &x)
	fmt.Println(n, err, x)
}
```
In go1.4.2 this prints `1 <nil> [1 35]`, but go1.5rc1 linux/amd64 gives me `1 expected newline [1 35]`, which doesn't seem right. Changing the format verb to 's' makes the error go away.

**Comment by davecheney** [comment]
@hubslave can you please provide a code sample that demonstrates the issue.

**Comment by robpike** [comment]
Nice bug, easy fix coming.
