### ISSUE TITLE
cmd/compile: GOEXPERIMENT=framepointer for darwin/arm64

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12100]
The iOS ABI calls for maintaining a valid framepointer:

https://developer.apple.com/library/ios/documentation/Xcode/Conceptual/iPhoneOSABIReference/iPhoneOSABIReference.pdf

The Xcode-integrated lldb expects this to be set, so without it debugging problems where the runtime cannot unwind the stack is difficult. We have framepointer support for amd64 in cmd/compile to use as a guide.

**Comment by williamweixiao** [comment]
hi, i'm enabling FP for arm64 and it's almost ready for linux os. But i don't have darwin os. Could you please provide me the environment for debugging it?

**Comment by eliasnaur** [comment]
Dup of #10110 ?

**Comment by ianlancetaylor** [comment]
Closing as dup.
