### ISSUE TITLE
x/build/cmd/coordinator: build key file is created as directory sometimes

### ISSUE THREAD

**Issue by adg** [golang/go#12104]
The coordinator starts the watcher in a docker container. To provide the build key to the watcher, the coordinator creates a file in /tmp/watcher.buildkey and exposes that to the docker container.

For an unknown reason, sometimes /tmp/watcher.buildkey is created as a directory instead of a file, causing the watchers to fail (they try to os.Open the directory). It's not clear to me how this is possible.

The purpose of this bug is to track down that reason.

cc @bradfitz

**Comment by bradfitz** [comment]
As of today, we no longer run the watcher in a Docker container on the same host. It now runs on Kubernetes.
