### ISSUE TITLE
net/mail: declared and not used warnings

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#12109]
I noticed this odd message while building Go 1.5 tip on Solaris:
```
...
##### Building go_bootstrap for host, solaris/amd64.
...
##### Building packages and commands for solaris/amd64.
...
# net/mail
net/mail/message.go:180: local declared and not used
net/mail/message.go:180: domain declared and not used
...
```
The related packages appears to have installed and built though, and tests ran for net/mail successfully.

**Comment by cespare** [comment]
Yeah, 1d75b40de8ecfaa947e1d61311d3a725fe4ec575 (CL 13500) introduced a bug.

/cc @dsymonds

**Comment by dsymonds** [comment]
Fix in https://go-review.googlesource.com/13510.
