### ISSUE TITLE
cmd/go: test -race -covermode=count correctly detects cover races

### ISSUE THREAD

**Issue by jmhodges** [golang/go#12118]
Looking at https://travis-ci.org/jmhodges/boulder/builds/75187815, the first DATA RACE section has

```
WARNING: DATA RACE
Read by goroutine 6:
  github.com/jmhodges/boulder/log.TestConstruction()
      /home/travis/gopath/src/github.com/jmhodges/boulder/log/audit-logger_test.go:216 +0x1f4
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 8:
  github.com/jmhodges/boulder/log.Dial()
      /home/travis/gopath/src/github.com/jmhodges/boulder/log/audit-logger_test.go:216 +0x26b
  github.com/jmhodges/boulder/log.initializeAuditLogger()
      github.com/jmhodges/boulder/log/_test/_obj_test/audit-logger.go:110 +0x217
```

Notice that both filepaths and line numbers are the same, but the functions referenced are different.

Also, the code at audit-logger_test.go:216 (not my filename choice; don't hate) is:

	audit, err := NewAuditLogger(writer, stats)

which does not deal directly log.Dial or log.initializeAuditLogger. You can find this code, currently, at https://github.com/letsencrypt/boulder/blob/2d92b1f348719ab096292308437b88ec0bb31979/log/audit-logger_test.go#L216

**Comment by jmhodges** [comment]
Note: I've not been able to get the OS X Go 1.5rc1 race detector to error locally. Only the TravisCI one that is on linux. I've not had a chance to repro on a real linux machine directly, yet.

**Comment by jmhodges** [comment]
Okay, the places I found that were obviously races in the boulder/log package have not fixed those DATA RACEs and their constructions have made it difficult to find The Real One. The attempted fixes can be found in this branch: https://github.com/jmhodges/boulder/tree/auditlogger_race/log

It's an unusual library, but one that is real and is being deployed to a production-like setting. Sorry for its weirdness.

**Comment by jmhodges** [comment]
Also, this occurs in tip on TravisCI at `go version devel +58035ec Tue Aug 11 20:46:22 2015 +0000 linux/amd64`. See https://travis-ci.org/jmhodges/boulder/builds/75205905

**Comment by aclements** [comment]
@dvyukov

**Comment by dvyukov** [comment]
You are using -covermode=count, these are races on coverage counters.
```-race -covermode=count``` combination is doomed to fail, @robpike can we produce some kind of a warning for this combination? Fail build?

**Comment by rsc** [comment]
If you ask for go test -race -covermode=count, then that's what you get. There is even a test case for this in cmd/go. Don't do that. There's no bug for Go 1.5 here.

**Comment by jmhodges** [comment]
Okay, cool. I hadn't been the one to set up the -covermode and hadn't thought about it being related.

**Comment by robpike** [comment]
This is what covermode -atomic is for.

**Comment by robpike** [comment]
Not an issue. The title even says, "correctly". :)
