### ISSUE TITLE
cmd/compile: unknown struct field error should point to key

### ISSUE THREAD

**Issue by dsymonds** [golang/go#12110]
Here's a demo program: http://play.golang.org/p/P_-S7aNsxW

The error message ("unknown S field 'baz' in struct literal") points to line 17, which has the closing brace for the value used for that unknown field. It would be much more useful to point to the "baz:" field tag on line 14.

**Comment by ALTree** [comment]
This is fixed on tip, the error now points to line 14:

```
$ gotip build test.go
# command-line-arguments
./test.go:14:6: unknown field 'baz' in struct literal of type S
```

Closing.
