### ISSUE TITLE
x/mobile/bind: byte slice parameter support without copy

### ISSUE THREAD

**Issue by hyangah** [golang/go#12113]
When a Go function or method taking a byte slice is called, the current implementation 
creates a copy of the arguments and passes it to the Go function. The implementation
was based on the assumption that the Go function is free to keep the slice for later use.
This prevents implementation like io.Read([]byte) where the parameter's content
is modified during call. Moreover, it costs an extra copy & memory which can be significant
depending on the byte slice size.

Instead, I propose to pass a slice backed by the foreign language's byte array if possible.

Users who want to keep the slice for later use have to be aware of the limitation and somehow
create a copy for now. 

More discussion on automation or tool support to detect such use cases 
(another kind of escape analysis) is welcome.

@crawshaw

**Comment by ekrivenja** [comment]
Vote to force this fix :)

**Comment by wpajqz** [comment]
Vote to force this fix :)

**Comment by hyangah** [comment]
I plan to work on this in Nov.

**Comment by diegomontoya** [comment]
:+1: For this optimization.

**Comment by crawshaw** [comment]
Please don't vote by commenting on github issues, it makes it easy to lose vital information in comments. If you think github issues need a voting mechanism, please let the github developers know.

I'll delete the votes here and this comment in a minute.

**Comment by nishant-kumbhare** [comment]
Hello,
Please help me out. 

I created a golang function with returntype array 
it is not created function with array return type, with message 
"skipped function with unsupported return type or parameter"
eg. 

my golang function is 
unc Sample() []string {

	letters := []string{"a", "b", "c", "d"}
	return letters
}

and after this i run the bind command it generate the framework and show header file with following result.
"skipped function Sample with unsupported parameter or return types"

**Comment by eliasnaur** [comment]
Gomobile does not (yet) support binding to function that takes or returns slices or arrays. If you need access to a Go slice or array from native code, use something like:

    func LetterAt(i int) string {
        return letters[i]
    }

Please use the golang-nuts discussion group for support questions in the future:

https://groups.google.com/d/forum/golang-nuts
