### ISSUE TITLE
cmd/compile/ssa: don't load/save unused values in a block

### ISSUE THREAD

**Issue by josharian** [golang/go#12119]
The currently regalloc does a silly thing--it loads all live values as it enters a block, whether or not they are used in that block, and then saves them on exit. Example:

After schedule:

```
b132: ← b5
Plain → b8
```

After regalloc:

```
b132: ← b5
v292 = LoadReg <uint32> v49 : AX
v290 = Copy <uint32> v292 : CX
v401 = StoreReg <uint32> v290
Plain → b8
```

The new regalloc is coming, just wanted to file this so that we double-check to make sure that this gets fixed by it.

/cc @randall77

**Comment by tzneal** [comment]
Close this now?

**Comment by randall77** [comment]
Yes, the new regalloc should fix this.
