### ISSUE TITLE
cmd/compile: compiler allows "-ddddp±ddd" notation for integer/float literals

### ISSUE THREAD

**Issue by dsnet** [golang/go#12126]
Using go1.5rc1.

[The following code compiles and runs](https://play.golang.org/p/cH0tN9aWba):
```go
import "fmt"

const foo = 1p10

func main() {
	fmt.Println(foo)
}
```

But if you try to run gofmt, it fails:
```
5:14: expected ';', found 'IDENT' p10
```

At first, I thought it was a gofmt bug, but it turns out that the "-ddddp±ddd" notation is [not part of the language specification](https://golang.org/ref/spec#Integer_literals). I expect the compiler to reject this if it is not part of the spec.

**Comment by dr2chase** [comment]
I thought I fixed this.  See #9036 .

**Comment by dsnet** [comment]
Ah, this is my fault. The computer I'm on at the moment has go1.4.2. The computer I usually use is running go1.5rc1.

Please close.

**Comment by dr2chase** [comment]
Always happy to fix bugs without touching code.
