### ISSUE TITLE
net: add a method to net.TCPConn, to send MSG_OOB "urgent data"

### ISSUE THREAD

**Issue by rin01** [golang/go#12121]
Usually, when a user has sent a request to a server, and the request is running from a too long time, the user can send a "cancel" command by sending an out-of-band data to the server.

The server can then immediately take the appropriate measure.

Is it possible to add a method to net.TCPConn, that would call the C function "send(..., MSG_OOB)" ?

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by mikioh** [comment]
There is #7882, but no concrete plan yet.

**Comment by mikioh** [comment]
Merged into #7882.
