### ISSUE TITLE
Crash in golang 1.4.2 on HardenedBSD 11-CURRENT/amd64

### ISSUE THREAD

**Issue by lattera** [golang/go#12123]
Go is broken on HardenedBSD currently. It appears to be from the hand-written assembly code in `src/runtime/sys_freebsd_amd64.s`. The bug can be triggered simply by attempting to compile go on HardenedBSD 11-CURRENT/amd64.

uname -a:

    laptop-dev-01[shawn]:/home/shawn/tmp/go (1) $ uname -a
    FreeBSD laptop-dev-01 11.0-CURRENT-HBSD FreeBSD 11.0-CURRENT-HBSD #44 264a80e(hardened/current/master): Wed Aug 12 16:42:41 EDT 2015     shawn@laptop-dev-01:/usr/obj/usr/src/sys/LATT-SEC  amd64

gdb backtrace:

    laptop-dev-01[shawn]:/usr/ports/lang/go $ sudo gdb ./work/go/pkg/tool/freebsd_amd64/go_bootstrap
    GNU gdb 6.1.1 [FreeBSD]
    Copyright 2004 Free Software Foundation, Inc.
    GDB is free software, covered by the GNU General Public License, and you are
    welcome to change it and/or distribute copies of it under certain conditions.
    Type "show copying" to see the conditions.
    There is absolutely no warranty for GDB.  Type "show warranty" for details.
    This GDB was configured as "amd64-marcel-freebsd"...
    (gdb) run
    Starting program: /usr/ports/lang/go/work/go/pkg/tool/freebsd_amd64/go_bootstrap 

    Program received signal SIGBUS, Bus error.
    0x00000000004a4da0 in runtime.settls () at /usr/local/go/src/runtime/sys_freebsd_amd64.s:286
    286     /usr/local/go/src/runtime/sys_freebsd_amd64.s: No such file or directory.
            in /usr/local/go/src/runtime/sys_freebsd_amd64.s
    Current language:  auto; currently minimal
    (gdb) bt
    #0  0x00000000004a4da0 in runtime.settls () at /usr/local/go/src/runtime/sys_freebsd_amd64.s:286
    #1  0x00000000008020b0 in runtime.tls0 ()
    #2  0x000000000048ce3c in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:65
    #3  0x0000000000000000 in ?? ()

**Comment by davecheney** [comment]
@lattera can you please check if this is a regression from Go 1.4.2.

**Comment by lattera** [comment]
Sure. Which prior version of golang would you like me to test?

**Comment by davecheney** [comment]
@lattera i'm really sorry, I thought this report was Go 1.5rc1 did not pass on your system. You can try 1.5rc1 if you like, but I suspect it won't pass either.

**Comment by lattera** [comment]
Gotcha. I tried with 1.4 and that didn't seem to work, either.

**Comment by lattera** [comment]
Nor did 1.3.2.

**Comment by lattera** [comment]
FWIW, vanilla FreeBSD 11-CURRENT/amd64 works fine. I wonder if it's because of our ASLR implementation.

**Comment by davecheney** [comment]
Almost certainly. To this best of my knowledge nobody has reported running
Go on your BSD variant.

**Comment by lattera** [comment]
This provides some interesting insight: https://code.google.com/p/go/issues/detail?id=7056

**Comment by lattera** [comment]
Rebuilding kernel with COMPAT_FREEBSD32 and retesting. Will have results soon.

**Comment by davecheney** [comment]
I believe that issue is fixed on 1.5,
https://github.com/golang/go/issues/7813

Please try the 1.5rc1 release and see if it improves the situation.

Thanks

Dave

**Comment by lattera** [comment]
Confirmed. Adding COMPAT_FREEBSD32 to my kernel config solves this issue. Sorry for the duplicate bug and the line noise. I'm glad to see 1.5 will switch golang over to SYSCALL.
