### ISSUE TITLE
crypto/x509: add /etc/ssl/certs to certificate directories

### ISSUE THREAD

**Issue by deafgoat** [golang/go#12139]
This will allow certificate verification from system root CAs work for distros such as SLES10/SLES11 which have certificates stored [there](https://github.com/openSUSE/ca-certificates).

Originally asked about this in https://groups.google.com/forum/#!topic/golang-nuts/lEInOWNOVxk

**Comment by rsc** [comment]
It is OK to add /etc/ssl/certs to crypto/x509/root_unix.go.
