### ISSUE TITLE
tour: restore instructions for downloading and running tour locally

### ISSUE THREAD

**Issue by Sajmani** [golang/go#12134]
Context: http://tour.golang.org/welcome/2

The second slide of the tour used to describe how to run the tour from a local Go installation.  I no longer find those instructions in any of the slides in the first module.  People are interested in doing the tour offline (e.g., on flights); we should provide instructions on how to do this.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
It looks like this was lost in the conversion from HTML to present format: 6cf2ff095922478bbac9113502c3d6227d7cee5d

We could add a slide after [welcome/2](https://tour.golang.org/welcome/2) bringing back the "Go Offline" content from earlier.

**Comment by adg** [comment]
Seems good.

**Comment by kytrinyx** [comment]
What's the process for building the tour to test changes locally? I see an `app.yaml` file, but I'm not sure what to do with it.

**Comment by adg** [comment]
To run locally:

```
$ go get golang.org/x/tour/gotour
$ gotour
```

To run the App Engine version locally, install the (Go App Engine SDK](https://cloud.google.com/appengine/downloads?hl=en) and then:

```
$ cd $GOPATH/src/golang.org/x/tour
$ $SDK_PATH/dev_appserver.py .
```

**Comment by kytrinyx** [comment]
Ah, that second bit is what I was missing. Thanks!
