### ISSUE TITLE
cmd/compile: syntax error: unexpected string literal, expecting )

### ISSUE THREAD

**Issue by limpo1989** [golang/go#12147]
go version: go version go1.5rc1 linux/amd64
source file: models/models.go
models/models.go:8: syntax error: unexpected string literal, expecting )
lsb_release -a:
LSB Version:    :core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.2 (Final)
Release:        6.2
Codename:       Final

// go 1.4.2: Compile successfully.
// go 1.5rc1: compile error on anyfile to import this package.
import "github.com/astaxie/beego" // version: 1.3.2
```golang
  1 package models
  2 
  3 import(
  4     "base"
  5     "db"
  6     "record"
  7     "operate"
  8     "github.com/astaxie/beego" 
  9 .   "logger"
 10 )
 11 
 12 func Initialize( addr string, indexs...db.IRecord ) bool {
 13 
 14     if record.Count( (&Role{}).Table(), nil ) <= 0 {
 15         pwd := base.Password()
 16 
 17         adminuser := beego.AppConfig.String("rbac_admin_user")
 18 
 19         if err := AddUser( "admin", "admin@website.com", adminuser, pwd, "init admin.", P_Admin, 2 ); err != nil {
 20             LOG_ERROR( "unable to create: %s %s", adminuser, err.Error() )
 21             return false
 22         }
 23 
 24         LOG_INFO( "************************* init ************************" )
 25         LOG_INFO( "username: %s, pwssword: %s", adminuser, pwd )
 26         LOG_INFO( "*******************************************************************" )
 27     }
 28 
 29     return operate.Initialize( addr, indexs... )
 30 }
```
go 1.4.2 Compile successfully
go 1.5rc1 Compile error
why ?

**Comment by ianlancetaylor** [comment]
I can't recreate it.  Is that the complete input file?

**Comment by wlfsky** [comment]
update your beego code from github and rebuild!

**Comment by doomsplayer** [comment]
same issue as you @ianlancetaylor

**Comment by ianlancetaylor** [comment]
@doomsplayer This issue was closed by the submitter.  If you are having a similar problem, please open a new issue with a complete test case showing the problem.
