### ISSUE TITLE
cmd/compile/internal/gc: invalid instructions generated by ssa

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#12148]
See the following programs:

http://play.golang.org/p/fh0IAG0j5k
// ./a31018.go:1: doasm: notfound ft=9 tt=13 00124 ORW     $22898193250, AX 9 13

http://play.golang.org/p/qYwLNUo5p0
// ./a31954.go:1: doasm: notfound ft=9 tt=16 00074 ORL     $-72057592695750653, R13 9 16

http://play.golang.org/p/EmrfPOKU1t
// ./a31954.go:1: doasm: notfound ft=9 tt=16 00054 XORW    $4402880119000, R8 9 16

http://play.golang.org/p/vOm7VrT2cU
// ./a6868.go:1: doasm: notfound ft=9 tt=16 00132 XORL    $648518346341351424, R14 9 16

In this case the constant is larger than the operation width. I suspect that AND* also have the same issue.

**Comment by rsc** [comment]
Already fixed, per CL 13640 discussion.
