### ISSUE TITLE
cmd/compile: add //go:noinline annotation support

### ISSUE THREAD

**Issue by josharian** [golang/go#12140]
Some compiler tests require disabling inlining for a function. That is frequently accomplishing by adding `defer func() {}()` or `switch {}` with a comment. This is fragile and awkward. Let's add `//go:noinline` support and update the existing tests.

cc @randall77

**Comment by randall77** [comment]
I'm game.  Does it mean "don't inline anything into this function" or "don't inline this function into anything else"?  I'm guessing the latter.

**Comment by josharian** [comment]
The latter. I'll send a CL at some point.

**Comment by josharian** [comment]
This is now #12312.
