### ISSUE TITLE
html/template: bad quotes in second <div>

### ISSUE THREAD

**Issue by Witcher42** [golang/go#12149]
I asked this question on [StackOverflow](http://stackoverflow.com/q/32005459/875813), but there's no answer. Someone commented this seems a framework bug, so I post it here. After asking this question, I tried in another way using pure go without gin and I got the same result.

**Basic information**
* Go version: go1.4.2 darwin/amd64
* Operating System: Mac OS X 10.10.5
* Processor Architecture: 2.5 GHz Intel Core i7

I'm working on a small Web project written based on **go** and **gin**. Here is my golang code. After running `go run test.go` we have a web server, which is listening on 8089.

**Golang test.go**

```go
package main

import "github.com/gin-gonic/gin"
import "net/http"

func main() {
    router := gin.Default()
    router.LoadHTMLGlob("templates/*")
    router.GET("/index", func(c *gin.Context) {
        c.HTML(http.StatusOK, "index.html", gin.H{
            "scheme": "http",
            "domain": "meican.loc",
        })
    })
    router.Run(":8089") // listen and serve on 0.0.0.0:8089
}
```

The html code generated in back-end should contain a template used by front-end javascript engine (Let's say Angular.js). 

So the template code is in `script` tag, just like this:

**Part of templates/index.html**

```html
<script type="text/template" charset="utf-8">
    <div data="{{.scheme}}://{{.domain}}/qr"></div>
    <div data="{{.scheme}}://{{.domain}}/qr"></div> <!-- problem here -->
</script>
```
When `{{.domain}}` is used at the second time, I got different result. I refreshed the browser and checked out the source code. Then I got this:

**Browser source code result**

```html
<script type="text/template" charset="utf-8">
    <div data="http://meican.loc/qr"></div>
    <div data="http://"meican.loc"/qr"></div>  <!-- problems here -->
</script>
```

The second `div` has 2 extra double quotes.

Why this happens? And how to resolve this problem?

**Comment by ALTree** [comment]
Hi Witcher, 

this seems to be an issue related to the gin framework, so you should write in the gin issue tracker (https://github.com/gin-gonic/gin/issues)

**Comment by Witcher42** [comment]
Hi @ALTree Thanks for the reply. But as mentioned in my first comment, I thought it's not related to gin framework.

>  After asking this question, I tried in another way using pure go without gin and I got the same result.

I'll post some code which bring out the same result without gin.

**test.go**

```go
package main

import "net/http"
import "html/template"

type Page struct {
    Scheme string
    Domain string
}

func indexHandler(w http.ResponseWriter, r *http.Request) {
    p := &Page{
        Scheme: "http",
        Domain: "meican.loc",
    }
    t, _ := template.ParseFiles("templates/index.html")
    t.Execute(w, p)
}

func main() {
    http.HandleFunc("/index", indexHandler)
    http.ListenAndServe(":8089", nil)
}
```


**templates/index.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script type="text/template" charset="utf-8">
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>  <!-- problems here -->
  </script>
</body>
</html>
```

Then run command `go run test.go`, we will get this result when visiting `http://127.0.0.1:8089/index`.

**browser source code**

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script type="text/template" charset="utf-8">
    <div data="http://meican.loc/qr"></div>
    <div data="http://"meican.loc"/qr"></div>  <!-- problems here -->
  </script>
</body>
</html>
```

The result browser source code gives a different a result after rendering the second `<div data="{{.Scheme}}://{{.Domain}}/qr"></div>`.

**Comment by robpike** [comment]
Here is a version that does not require a web server.

package main

import (
	"html/template"
	"log"
	"os"
)

type Page struct {
	Scheme string
	Domain string
}

const text = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script type="text/template" charset="utf-8">
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>  
  </script>
</body>
</html>
`

func main() {
	p := &Page{
		Scheme: "http",
		Domain: "meican.loc",
	}
	t, err := template.New("index").Parse(text)
	if err != nil {
		log.Fatal(err)
	}
	err = t.Execute(os.Stdout, p)
	if err != nil {
		log.Fatal(err)
	}
}


With text/template, the (core of the) output is

    <div data="http://meican.loc/qr"></div>
    <div data="http://meican.loc/qr"></div>  

while with html/template, it is

    <div data="http://meican.loc/qr"></div>
    <div data="http://"meican.loc"/qr"></div>  

It does indeed seem like a bug in html/template.

**Comment by fyelles** [comment]
Interestingly enough if you removed the <b><i>script</i></b> tag and replace it for example by a  <b><i>span</i></b> .
The output is as expected. (http://play.golang.org/p/Lxge_eg835)

I will take a look at it
```go
package main

import (
    "html/template"
    "log"
    "os"
)

type Page struct {
    Scheme string
    Domain string
}


const text = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <span type="text/template" charset="utf-8">
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>
    <div data="{{.Scheme}}://{{.Domain}}/qr"></div>  <!-- problems here -->
  </span>
</body>
</html>
`

func main() {
    p := &Page{
        Scheme: "http",
        Domain: "meican.loc",
    }
    t, err := template.New("index").Parse(text)
    if err != nil {
        log.Fatal(err)
    }
    err = t.Execute(os.Stdout, p)
    if err != nil {
        log.Fatal(err)
    }
}
```

**Comment by jeffallen** [comment]
@robpike Ping? You made a commit that prepared for a fix, but the fix didn't land? Can you pass me what you have so far, and can finish it up for ya.

**Comment by robpike** [comment]
@jeffallen I didn't make any commit regarding this. Not sure what you're referring to.

**Comment by ALTree** [comment]
@jeffallen: Nodir Turakulov [sent the patch](https://go-review.googlesource.com/#/c/14335/), the nickname you see on the commit it's just the name of the team member that approved and cherrypicked it.

**Comment by jeffallen** [comment]
OK, sorry to confuse. @nodirt, CL 14336 is waiting for Go 1.7, I guess?

**Comment by rsc** [comment]
There is a fix pending in CL 13446 that needs review (and in particular needs to address review comments). I will make sure this gets reviewed.
