### ISSUE TITLE
x/crypto/openpgp: new entities cannot be encrypted to by default

### ISSUE THREAD

**Issue by zenazn** [golang/go#12153]
The key returned by `openpgp.NewEntity` (https://godoc.org/golang.org/x/crypto/openpgp#NewEntity) does not express hash algorithm preferences, and by default `openpgp.Encrypt` (and perhaps others) default to using the `RIPEMD160` algorithm (https://github.com/golang/crypto/blob/173ce04bfaf66c7bb0fa9d5c0bfd93e773909dbd/openpgp/write.go#L205), which is not compiled in unless one explicitly requests it. This means that the "obvious" way to generate keys and encrypt to them fails with the largely-inscrutible error message `openpgp: invalid argument: cannot encrypt because no candidate hash functions are compiled in. (Wanted RIPEMD160 in this case.)`

There are more than a few ways around this (populating `PreferredHash` being one obvious option, and defaulting to e.g., SHA-256 being another), but this seems like an awfully sharp edge to leave lying around.

**Comment by ianlancetaylor** [comment]
CC @agl @hanwen

**Comment by SlevinT** [comment]
is there a work around for this issue? I have had problems with encrypt, after using defaults to gen keys. My assumption is that I alter the hash used in generation?

**Comment by jfrazelle** [comment]
I opened a patch with one solution for this here: https://go-review.googlesource.com/#/c/23209/ but unsure if it's too opinionated

**Comment by ProtoFly** [comment]
Has this issue been resolved?

**Comment by jfrazelle** [comment]
Not yet

On Friday, July 1, 2016, ProtoFly <notifications@github.com> wrote:

> Has this issue been resolved?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/golang/go/issues/12153#issuecomment-229983837>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABYNbFND53R0hwCAlpHaCew-i-iOcACPks5qRTmIgaJpZM4FsAME>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by ProtoFly** [comment]
My -sort of- fix was to use 
`_"golang.org/x/crypto/ripemd160"`

Alas, still unsuccessful, as the code then generates: 
  `openpgp: invalid argument: cannot encrypt to public key of type 17`

**Comment by odeke-em** [comment]
Hello @jessfraz, I see that your CL was merged in September 2016, does this mean that this issue is then resolved?

**Comment by jessfraz** [comment]
Yes

**Comment by odeke-em** [comment]
Thank you for the confirmation @jessfraz. In that case I'll close this issue. @zenazn and @ProtoFly please get the latest crypto `go get -u golang.org/x/crypto`.
