### ISSUE TITLE
x/tools/godoc: broken source links for cmd/*

### ISSUE THREAD

**Issue by josharian** [golang/go#12159]
For example, visit http://tip.golang.org/cmd/vet/whitelist/. The link for whitelist.go in package files is to http://tip.golang.org/src/vet/whitelist/whitelist.go, which is a 404. The correct link is http://tip.golang.org/src/cmd/vet/whitelist/whitelist.go. Might affect golang.org as well.

cc @adg

**Comment by robpike** [comment]
Seems to be an issue in godoc itself.
