### ISSUE TITLE
x/net/{icmp,ipv4,ipv6}: examples refer to internal iana package

### ISSUE THREAD

**Issue by dominikh** [golang/go#12163]
The NonPrivilegedPing example (`ExamplePacketConn_nonPrivilegedPing` in `example_test.go`) uses `iana.ProtocolIPv6ICMP`, where `iana` is the internal package `golang.org/x/net/internal/iana`.

It'd be helpful if examples actually worked for end users, who cannot import iana.

It'd also be nice if iana wasn't internal, as its usefulness to people is evident by its use in the example.

**Comment by mikioh** [comment]
Agreed.
