### ISSUE TITLE
misc/cgo/testcshared: cgo testp2 fails on OS X

### ISSUE THREAD

**Issue by jeffallen** [golang/go#12161]
With commit 467a2cb73ca867ccdb1dd22be220fa51b6d52491, the ../misc/cgo/testcshared test fails on MacOS 10.10.5 (14F27).

The problem is that testp2 gives random output instead of PASS. It seems like fd 10 is open and used by MacOS for something else at the time we read from it, so we get that garbage instead of the data that libgo2 is trying to send on it. When I change to fd 100, the problem goes away.

Not saying this is a real fix, just that this points to what the problem is.

```
diff --git a/misc/cgo/testcshared/main2.c b/misc/cgo/testcshared/main2.c
index 4023383..fbdbc48 100644
--- a/misc/cgo/testcshared/main2.c
+++ b/misc/cgo/testcshared/main2.c
@@ -9,7 +9,7 @@
 #include <time.h>
 #include <unistd.h>
 
-#define fd (10)
+#define fd (100)
 
 // Tests libgo2.so, which does not export any functions.
 // Read a string from the file descriptor and print it.
diff --git a/misc/cgo/testcshared/src/libgo2/libgo2.go b/misc/cgo/testcshared/src/libgo2/libgo2.go
index 6096860..6e513f0 100644
--- a/misc/cgo/testcshared/src/libgo2/libgo2.go
+++ b/misc/cgo/testcshared/src/libgo2/libgo2.go
@@ -21,7 +21,7 @@ import (
 // that the C code can also use.
 
 const (
-	fd = 10
+	fd = 100
 )
 
 func init() {
```

**Comment by rsc** [comment]
@jeffallen, commit 467a2cb was a change to register allocation in the arm64 compiler. But you are reporting a problem on OS X 10.10.5, which does not run on arm64. So perhaps you meant a different commit? I would be interested to know when it started if you can git bisect it (perhaps the bug is in 10.10.5 and any version fails, but that would be good to know too). Thanks.

**Comment by rsc** [comment]
FWIW, I don't understand why fd 10 would already be open (@ianlancetayor or @mwhudson?) but it's certainly plausible that the C library could have fd 10 open, in which case changing to fd 100 does not seem like such a bad thing.

**Comment by ianlancetaylor** [comment]
On a GNU/Linux system I would say that it is impossible for file descriptor 10 to be open (unless you are invoking all.bash/run.bash in an unusual way).  However, I have no idea what MacOS may do.  I'm fine with changing the 10 to 100 if that fixes the real problem.

**Comment by rsc** [comment]
Also, I tried to reproduce this on my OS X machine and I can't even run the test. So something is odd.

```
$ go test
2015/11/30 14:36:09 executing go install -installsuffix=5577006791947779410 -buildmode=shared runtime sync/atomic failed exit status 1:
-buildmode=shared not supported on darwin/amd64
exit status 1
FAIL	_/Users/rsc/go/misc/cgo/testshared	0.122s
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021
$
```

**Comment by mwhudson** [comment]
@rsc this is about testcshared, not testshared

**Comment by jeffallen** [comment]
I just tested and can't repro with:

$ pwd
/Users/jra/go/misc/cgo/testcshared
$ ./test.bash 
$ go version
go version devel +1dae473 Tue Dec 1 10:39:06 2015 +0000 darwin/amd64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021
