### ISSUE TITLE
dashboard: builder with GOEXPERIMENTs?

### ISSUE THREAD

**Issue by dvyukov** [golang/go#12174]
Looking at issue #12171, should we have a builder with GOEXPERIMENT=fieldtrack? Or probably GOEXPERIMENT=fieldtrack,framepointer?
@bradfitz

**Comment by dvyukov** [comment]
@bradfitz it should be easy to add a new builder now, right?

**Comment by bradfitz** [comment]
Yeah, feel free to send a CL modifying x/build/dashboard/builders.go. I'd look at the -nocgo builder as an example and copy that bit.

**Comment by rsc** [comment]
Of all the things we could use an extra builder for, fieldtrack is just about the last thing on the list. I really don't think this is worthwhile.
