### ISSUE TITLE
cmd/go: Test tool eats known flags, docs say it doesn't

### ISSUE THREAD

**Issue by jaguilar** [golang/go#12177]
This issue is related to [this discussion](https://groups.google.com/forum/#!topic/golang-nuts/7EwgSelVulM). [The docs](https://golang.org/cmd/go/#hdr-Test_packages) say:

"go test [-c] [-i] [build and test flags] [packages] [flags for test binary]

"If the test binary needs any other flags, they should be presented after the package names. The go tool treats as a flag the first argument that begins with a minus sign that it does not recognize itself; that argument *and all subsequent arguments* are passed as arguments to the test binary." (Emphasis mine.)

However, try running this command on any package that imports "github.com/golang/glog"

    go test -v pkg -logtostderr -v=2

With go1.5rc1 (go version devel +d3ffc97 Wed Jul 29 23:50:20 2015 +0000 linux/amd64):

    go test: illegal bool flag value 2

According to the docs, -v=2 should be passed down to the binary.

At a minimum, the docs should be fixed. Also, considering how common some of go test's flag names are, I think the behavior in the docs should also be implemented. However, it seems like there are probably plenty of scripts out there relying on the bad behavior. Perhaps a new directive, say "--" could be added, after which the remaining command line would actually be passed unmodified to the child binary.

**Comment by robpike** [comment]
The docs do say, "after the package names", but your example has no package names. This should work:

```
go test -v pkg -logtostderr . -v=2
```

**Comment by jaguilar** [comment]
I'm sorry, I meant the word "pkg" to be a standin for "package_name" -- whatever package you might happen to be testing. So, yes, there is a package name there. Sorry if the short name was confusing.

Your proposal does not work for me.

```
~/gocode/src/github.com/jaguilar/vt100$ go test -v -logtostderr . -v 2
go test: v flag may be set only once
run "go help test" or "go help testflag" for more information

~/gocode/src/github.com/jaguilar/vt100$ go test -v github.com/jaguilar/vt100 -logtostderr . -v 2
go test: v flag may be set only once
run "go help test" or "go help testflag" for more information
```

**Comment by jaguilar** [comment]
(Also does not work when I include the = sign in -v=2, just in case that matters.)

```
~/gocode/src/github.com/jaguilar/vt100$ go test -v -logtostderr . -v=2
go test: illegal bool flag value 2
run "go help test" or "go help testflag" for more information
```

**Comment by robpike** [comment]
Not convinced this is just a documentation issue.

**Comment by jaguilar** [comment]
Fair enough. But I don't think this has ever worked. Right now, the only way for an arg to make it into [passToTest](https://github.com/golang/go/blob/5bf1369c9ba09df6df2fbd3b8221f22b1d52d2ee/src/cmd/go/testflag.go#L117) is if testFlag() returns nil for f. I can't see any revisions where that was different, but I didn't look at all of them -- I just picked a few randomly including the initial.

The fix/feature would be to put an else [here](https://github.com/golang/go/blob/5bf1369c9ba09df6df2fbd3b8221f22b1d52d2ee/src/cmd/go/testflag.go#L100) that simply appends the flag to passToTest if inPkg. That would make the behavior conform to the doc, I think. Probably we'd want to change the name of inPkg to "startedPkg" or "seenPkg," since the current name implies that you can leave once you begin.

**Comment by jaguilar** [comment]
Just so it's clear -- would you like me to implement this, or will you, or have you not decided whether it would be desirable? I'm fine with any of these outcomes. I just want to make sure we're not both waiting for the other to take some action.

**Comment by robpike** [comment]
I'll do it.
