### ISSUE TITLE
x/review/git-codereview: complain when branch upstream is not master and does not have a dot in it

### ISSUE THREAD

**Issue by josharian** [golang/go#12170]
git-codereview attempts to put a branch prefix on CLs when they're not on master. It uses the branch upstream for this, which works until it doesn't.

There's at least one invariant we can use to detect that something has gone wrong: The upstream must be called master or have a dot in it.

cc @rsc

**Comment by 4ad** [comment]
I'm also hit by this. git-codereview is trying way, way too hard. It should do something much safer, and much simpler.

    IFF branchBranchName.Matches("^dev\.")
        addPrefix()

That's it.

> The upstream must be called master or have a dot in it.

In fact, in an ideal worls git-codereview should also not assume a `master` remote either. Remote names are arbitrary and local. However, this is too hard to fix, so I'm not bothered by it that much. (although it means I have to change the way I usually use git with other projects, just to work on Go...)

**Comment by mwhudson** [comment]
You can also just not use git-codereview (well, the hooks are nice, but I don't use it for interacting with gerrit any more).

**Comment by minux** [comment]
I think the precommit gofmt hook is still required even if you don't use
git-codereview plugin.
