### ISSUE TITLE
x/build: mac builders not logged in

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12185]
The windowless core graphics GL context created in x/mobile/exp/gl/glutil is returning kCGLBadConnection. Documentation is sparse, but the internet suggests that this error message is because the user running the tests is not logged into the graphical OS interface.

Logging the user in is possible (if the KVM is working), but how do we make it robust? Automatically log the user in?

**Comment by bradfitz** [comment]
Let's finish #9495 first, and then we get this for free, since #9495 includes making each VM log in as a user before running tests.

**Comment by bradfitz** [comment]
The new builders I'm setting up auto login on boot and run the builder, so this will be fixed soon.
