### ISSUE TITLE
x/build: linux image is missing openal

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12183]
The linux/amd64 builder fails testing x/mobile with

```
# golang.org/x/mobile/exp/audio/al
../../gopath/src/golang.org/x/mobile/exp/audio/al/al_notandroid.go:22:19: fatal error: AL/al.h: No such file or directory
```

http://build.golang.org/log/4bbb065ef9b14874e7ed52fe2034e02eff32cc53

It may be that the test should be resilient to the library being missing so that users can run go test golang.org/x/mobile/..., but we should also be testing this code on the builders, which means the linux image needs a copy of OpenAL installed.

/cc @rakyll @adg

**Comment by hyangah** [comment]
I added openal to the the list-x86-std Dockerfile but didn't perform the process to build a new image out of it https://go-review.googlesource.com/12891

**Comment by bradfitz** [comment]
In the future, don't submit Dockerfile changes until they've been tested & deployed on the staging instance.
/cc @adg

**Comment by hyangah** [comment]
I see. Sorry for submitting it without properly testing it. 
Is there a doc that I can reference for testing/staging?

**Comment by rakyll** [comment]
Should we close this issue now?

**Comment by bradfitz** [comment]
Not yet.

@evandbrown just about has Kubernetes builders working, and it's using the new Dockerfile image with these libraries, so let's wait to close this until that works.

**Comment by bradfitz** [comment]
Fixed by @eliasnaur recently in https://go-review.googlesource.com/c/build/+/164658
