### ISSUE TITLE
cmd/vet: false negative in shadow

### ISSUE THREAD

**Issue by nicot** [golang/go#12188]
Using the go tool vet -shadow command correctly reports shadowing in the following code:
```go
func correct() {
	var a int
	{
		var a int
		a = 3
		fmt.Println(a)
	}
	fmt.Println(a)
}
```

However, running the same command on this code does not report any shadowing:
```go
func broken() {
	var a int
	{
		a := 3
		fmt.Println(a)
	}
	fmt.Println(a)
}
```

 I think there is a difference between the desired behavior and the implementation of `idiomaticShortRedecl`. If the right hand side AST node is not an ast.Ident or TypeAssertExpr, the whole function should fail and return false. Right now the function returns true even when the assignment being evaluated is not an idiomatic short redeclaration as described at the top of the function. I would like to submit a patch for this, if the implementation is not behaving as desired.

**Comment by NHOrus** [comment]
I experienced this false negative:
http://play.golang.org/p/d0Ks5bCELG

But in this case, just a lot of sudden panics.
