### ISSUE TITLE
runtime: pathological heap trigger/goal behavior

### ISSUE THREAD

**Issue by aclements** [golang/go#12199]
While trying to write a good demonstration of the GC pacer, I managed to write something that drives the heap trigger and goal much too low (and sometimes drives the goal below the trigger): https://gist.github.com/aclements/fe5d9d0fdada390c2bb0

Despite this, the final heap size in each cycle is perfectly reasonable throughout the benchmark, though it's clearly slightly less controlled once the trigger and goal get out of whack.

![gctrace](https://cloud.githubusercontent.com/assets/2688315/9361536/d3de6a74-4669-11e5-85e1-efb028d244b4.png)

/cc @RLH

**Comment by aclements** [comment]
What drives the heap goal down must be poor estimation of heap_reachable, since this is really all the goal is based on. The goal first goes haywire after the long GC cycle at ~2.2s caused by a low trigger; that gives the mutator a lot of time to allocate during the cycle (in fact, you can see how much it allocates during the cycle), and all of that allocation gets subtracted from the marked heap size before computing the goal of the next cycle.

This doesn't explain why the trigger first drops so low in the cycle at 2.2s.

**Comment by rsc** [comment]
Probably too late for Go 1.6.

**Comment by aclements** [comment]
This turns out to be because heap_live was underestimating the true live heap size. In this case, it was seriously underestimating it. Since the triggering and pacing is based on heap_live, this underestimation lead to the erratic behavior. (I discovered this while debugging #13535, which turns out to be closely related.)
