### ISSUE TITLE
go get --verbose

### ISSUE THREAD

**Issue by techtonik** [golang/go#12197]
It is unclear what go is doing while trying to get LXD for development with `go get github.com/lxc/lxd`. It hangs for a lot of time and I don't know if it is network problem or just long checkout:
```
$ go version
go version go1.4.2 linux/amd64

```
What I expect at first is some command line help:
```
$ go get github.com/lxc/lxd -h
package -h: unrecognized import path "-h"
$ go get github.com/lxc/lxd --help
package --help: unrecognized import path "--help"
```
And then:
```
$ go get github.com/lxc/lxd --verbose
downloading ....
compiling ...
etc ...
```

**Comment by dominikh** [comment]
Flags go before arguments.

```
dominikh-pc ~ $ go get -h github.com/lxc/lxd
usage: get [-d] [-f] [-fix] [-t] [-u] [build flags] [packages]
[...]
```

(and of course, with -h it makes no sense to specify a package path).

Verbose also exists: `-v`

**Comment by techtonik** [comment]
@dominikh it is a convenience feature. Editing a line to insert --help before package name when you need to lookup something you've forgot is a nuisance after Python where optparse handles this gracefully.

Well, cool that `-v` exists, but you see that I was unable to use it, because well I used to add options at the end.

**Comment by epitron** [comment]
```
$ go get --help
usage: get [-d] [-f] [-fix] [-insecure] [-t] [-u] [build flags] [packages]
```

Shouldn't it list `-v` there?

**Comment by bradfitz** [comment]
This bug is closed. We don't re-use old bugs.
