### ISSUE TITLE
error in encoding/binary Read

### ISSUE THREAD

**Issue by lysevi** [golang/go#12201]
go 1.4.2 windows7 x64
```Go
package main

import(
	"fmt"
	"bytes"
	"encoding/binary"
)

type Header struct {
	IsFull        bool
}

func main(){
	a:=make([]byte,1024,1024)
	for i:=0;i<1024;i++{
		a[i]=byte(i)
	}
	var pi Header
	buf := bytes.NewReader(a)
	err := binary.Read(buf, binary.LittleEndian, &pi)
	fmt.Println(err)	
}
```

result: "binary.Read: invalid type *main.Header"

but, if o change type of Header.IsFull from bool to byte or int8 (or something else int*), then all works done

**Comment by ianlancetaylor** [comment]
This is working as expected.  The encoding/binary package, as the documentation says, "implements simple translation between numbers and byte sequences."  The type bool is not a number.
