### ISSUE TITLE
cmd/go: test failures: TestGoInstallRebuildsStalePackagesInOtherGOPATH and TestBuildDashIInstallsDependencies

### ISSUE THREAD

**Issue by pebbe** [golang/go#12205]
Installing Go from fresh source, release branch go1.5, I get:
```
--- FAIL: TestGoInstallRebuildsStalePackagesInOtherGOPATH (0.45s)
        go_test.go:251: running testgo [install p1]
        go_test.go:251: running testgo [list -f {{.Stale}} p1]
        go_test.go:266: standard output:
        go_test.go:267: false

        go_test.go:251: running testgo [list -f {{.Stale}} p2]
        go_test.go:266: standard output:
        go_test.go:267: false

        go_test.go:251: running testgo [list -f {{.Stale}} p2]
        go_test.go:266: standard output:
        go_test.go:267: false

        go_test.go:563: ./testgo list mypkg claims p2 is NOT stale, incorrectly
--- FAIL: TestBuildDashIInstallsDependencies (0.60s)
        go_test.go:251: running testgo [build -v -i x/y/bar]
        go_test.go:270: standard error:
        go_test.go:271: x/y/foo
                x/y/bar

        go_test.go:251: running testgo [build -v -i x/y/bar]
        go_test.go:270: standard error:
        go_test.go:271: x/y/bar

        go_test.go:251: running testgo [build -v -i x/y/bar]
        go_test.go:270: standard error:
        go_test.go:271: x/y/bar

        go_test.go:378: first build -i cmd did not build x/y/foo
        go_test.go:379: pattern x/y/foo not found in standard output or standard error
FAIL
FAIL    cmd/go  51.841s
```

$ for i in  -s -r -v -m -p -i -o; do uname $i; done
Linux
2.6.32-5-amd64
#1 SMP Wed Jun 17 16:09:06 UTC 2015
x86_64
unknown
unknown
GNU/Linux

On another, virtually identical machine, it installs without problems:

$ for i in  -s -r -v -m -p -i -o; do uname $i; done
Linux
2.6.32-5-amd64
#1 SMP Sat Jul 12 16:47:57 UTC 2014
x86_64
unknown
unknown
GNU/Linux

**Comment by mwhudson** [comment]
Do the systems differ in filesystem timestamp resolution? E.g. is the first one ext3, or ext4-that-was-once-ext3?

**Comment by pebbe** [comment]
The first (failures) is nfs with /tmp on ext3

The second (all ok) is all ext3

**Comment by rsc** [comment]
This looks like an error in test logic, so not something for a point release.

It looks to me like func measureTick has the test backward:

	func measureTick(path string) {
		st, err := os.Stat(path)
		if err != nil {
			// Default to one second, the most conservative value.
			mtimeTick = time.Second
			return
		}
		mtime := st.ModTime()
		t := time.Microsecond
		for mtime.Round(t).Equal(mtime) && t < time.Second {
			t *= 10
		}
		mtimeTick = t
	}

I think that "for " should be "for !", negating the first half of the conjunction. If I'm reading it correctly, the current test will decide on microsecond precision for file systems with only second precision and vice versa.

**Comment by ianlancetaylor** [comment]
I think the measureTick logic is correct.  If rounding to t gives you the same time, you don't know anything--the time might have been a multiple of t anyhow.  So you keep going.  If rounding to t gives you a different time, then you can expect that a sleep of t will give you a different time.

**Comment by rsc** [comment]
@ianlancetaylor, yes, I was clearly misreading.

I wonder if maybe the os.Stat gets cached Linux data with microsecond resolution even though NFS only stores 1-second resolution, or something like that.

**Comment by btracey** [comment]
As another point, I am seeing the exact same failure as @pebbe 

btracey@vader ~/gover/go/src $ for i in -s -r -v -m -p -i -o; do uname $i; done
Linux
3.14.14-gentoo
#1 SMP Thu Oct 2 04:23:17 MDT 2014
x86_64
AMD Opteron(tm) Processor 6172
AuthenticAMD
GNU/Linux
