### ISSUE TITLE
net: TestDialerDualStack, TestTCPServer, TestUDPServer fail on some Linux distro

### ISSUE THREAD

**Issue by pebbe** [golang/go#12206]
Installing Go from fresh source, release branch go1.5, I get:

```
--- FAIL: TestDialerDualStack (0.36s)
        dial_test.go:664: dial tcp 127.0.0.1:36185: getsockopt: connection refused
        dial_test.go:664: dial tcp 127.0.0.1:56856: getsockopt: connection refused
--- FAIL: TestTCPServer (10.01s)
        server_test.go:58: skipping tcp :0->127.0.0.1 test
        server_test.go:58: skipping tcp 0.0.0.0:0->127.0.0.1 test
        server_test.go:58: skipping tcp [::ffff:0.0.0.0]:0->127.0.0.1 test
        server_test.go:58: skipping tcp [::]:0->::1 test
        server_test.go:58: skipping tcp :0->::1 test
        server_test.go:58: skipping tcp 0.0.0.0:0->::1 test
        server_test.go:58: skipping tcp [::ffff:0.0.0.0]:0->::1 test
        server_test.go:58: skipping tcp [::]:0->127.0.0.1 test
        server_test.go:58: skipping tcp :0->127.0.0.1 test
        server_test.go:58: skipping tcp 0.0.0.0:0->127.0.0.1 test
        server_test.go:58: skipping tcp [::ffff:0.0.0.0]:0->127.0.0.1 test
        server_test.go:58: skipping tcp [::]:0->::1 test
        server_test.go:58: skipping tcp :0->::1 test
        server_test.go:58: skipping tcp 0.0.0.0:0->::1 test
        server_test.go:58: skipping tcp [::ffff:0.0.0.0]:0->::1 test
        server_test.go:58: skipping tcp [::]:0->127.0.0.1 test
        server_test.go:105: dial tcp [::1]:53560: i/o timeout
--- FAIL: TestUDPServer (30.01s)
        server_test.go:254: skipping udp :0->127.0.0.1 test
        server_test.go:254: skipping udp 0.0.0.0:0->127.0.0.1 test
        server_test.go:254: skipping udp [::ffff:0.0.0.0]:0->127.0.0.1 test
        server_test.go:254: skipping udp [::]:0->::1 test
        server_test.go:254: skipping udp :0->::1 test
        server_test.go:254: skipping udp 0.0.0.0:0->::1 test
        server_test.go:254: skipping udp [::ffff:0.0.0.0]:0->::1 test
        server_test.go:254: skipping udp [::]:0->127.0.0.1 test
        server_test.go:254: skipping udp :0->127.0.0.1 test
        server_test.go:254: skipping udp 0.0.0.0:0->127.0.0.1 test
        server_test.go:254: skipping udp [::ffff:0.0.0.0]:0->127.0.0.1 test
        server_test.go:254: skipping udp [::]:0->::1 test
        server_test.go:254: skipping udp :0->::1 test
        server_test.go:254: skipping udp 0.0.0.0:0->::1 test
        server_test.go:254: skipping udp [::ffff:0.0.0.0]:0->::1 test
        server_test.go:254: skipping udp [::]:0->127.0.0.1 test
        server_test.go:310: #18: read udp [::1]:58088: i/o timeout
        server_test.go:313: #18: read udp [::1]:42895: i/o timeout
        server_test.go:254: skipping udp4 :0->127.0.0.1 test
        server_test.go:254: skipping udp4 0.0.0.0:0->127.0.0.1 test
        server_test.go:254: skipping udp4 [::ffff:0.0.0.0]:0->127.0.0.1 test
        server_test.go:254: skipping udp6 :0->::1 test
        server_test.go:254: skipping udp6 [::]:0->::1 test
        server_test.go:310: #25: read udp6 [::1]:38590: i/o timeout
        server_test.go:313: #25: read udp6 [::1]:41566: i/o timeout
        server_test.go:310: #27: read udp [::1]:37440->[::1]:52935: i/o timeout
        server_test.go:313: #27: read udp [::1]:52935: i/o timeout
FAIL
FAIL    net     42.809s
```

$ for i in  -s -r -v -m -p -i -o; do uname $i; done
Linux
3.5.0-45-generic
#68~precise1-Ubuntu SMP Wed Dec 4 16:18:46 UTC 2013

x86_64
x86_64
x86_64
GNU/Linux

**Comment by jacobsa** [comment]
FYI, I see this on OS X 10.10.5 as well.

**Comment by rsc** [comment]
This looks most likely a problem with our testing setup, not something fundamental. If so, it should be Go1.6Early. But it would be nice to confirm.

**Comment by mikioh** [comment]
@pebbe,

The results say that all IPv6 tests using IPv6 loopback address and loopback interface fail on your node under the test. That means that the node implements and enables IPv6 node functionality, and probably some software components along L3-L2 host transmission/reception packet path inside the kernel (such as packet filter, protocol/address family translator blah blah) discards test packets.

For now I have no plan to make existing test cases more adaptive for helping such case.

@jacobsa,

Looks like mbuf stuff on latest darwin kernels sometimes requires a warmup. Please check the output of "netstat -is, netstat -s and netstat -m" when you have a fail.

**Comment by andrewshadura** [comment]
This is still valid for 1.6.1.

**Comment by bradfitz** [comment]
@andrewshadura, Go 1.6 is no longer maintained. In fact, Go 1.7 isn't either (except for security fixes), and Go 1.8 is only updated for bad bugs and security fixes.

@mikioh, can you look at this for Go 1.9?

**Comment by andrewshadura** [comment]
@bradfitz, I'm aware of that, however, we (as a Debian downstream) build a Debian package for it, and it fails because of the failing tests.

**Comment by bradfitz** [comment]
I recommend you disable the failing tests then.

**Comment by andrewshadura** [comment]
That's what I'm going to do. I just thought maybe some better solution appeared, or maybe if I rant here someone proposes one for a newer upstream version, and I can backport it :)

**Comment by mikioh** [comment]
@andrewshadura,

Can you show us the following?
- distribution name or version
- kernel version
- all configurations related to loopback interface, IP stack and socket; e.g., the output of ```sysctl -a | egrep 'ipv|netfilter|sock'```, iptables{,6},conf

**Comment by mvdan** [comment]
It looks like we sometimes still hit this on the builders: https://build.golang.org/log/c625e43f414b3e77c3261f84338948196b92a409

Though that is the ios builder, so I'm not sure if that kind of failure is expected. @bradfitz thoughts?

**Comment by bradfitz** [comment]
@mvdan, could you file a new bug for that? Flaky tests are never good.
