### ISSUE TITLE
csv ReadAll - Does not process csv file with "CR" as EOL character (without "LF")

### ISSUE THREAD

**Issue by jumpinjan** [golang/go#12207]
I have to work with CSV files that only have a carriage return in them.  The csv package Readall method considers the whole file to be one record because it only checks for "LF" (/n) and has no check for "CR" as well.

CSV files can end with just "CR" per these standards:  http://www.digitalpreservation.gov/formats/fdd/fdd000323.shtml

Thank you!

**Comment by ajstarks** [comment]
See: https://github.com/golang/go/issues/7897

**Comment by adg** [comment]
Dupe of #7897
