### ISSUE TITLE
x/playground: playground should display the version of Go in use

### ISSUE THREAD

**Issue by davecheney** [golang/go#12218]
The only way to discover the version of Go the playground supports is a program like this

http://play.golang.org/p/4WfD2XfzPt

The playground should show the version of Go in use either at the bottom of the page, or on the About dialog.

**Comment by adg** [comment]
It's non-trivial because the web front end and sandbox back end are separate.

**Comment by griesemer** [comment]
Perhaps the web front-end could run that exact program to find out? (and then it's cached, presumably).

While it's easy enough to run the program, I do think this would be useful to highlight clearly. It's a common source of confusion.

**Comment by griesemer** [comment]
Here's a cheap solution: Have a "version" button which is a link to that program http://play.golang.org/p/4WfD2XfzPt and then runs it.

**Comment by kostya-sh** [comment]
Actually this solution is already mentioned in the About text. It was fairly easy to discover.

I think Go playground should always run the latest version of Go, then displaying the version becomes unnecessary.

**Comment by adg** [comment]
"Always run the latest version of Go" is the goal, but it's not that simple unfortunately.

**Comment by adg** [comment]
@griesemer it's true, the front end could query the back end to find the version. But right now the front end is more or less stateless; I'm hesitant to add state. Will continue to ponder.

**Comment by griesemer** [comment]
@adg Having a "Version" button that simply links to http://play.golang.org/p/4WfD2XfzPt would be entirely stateless. Ideally it should also run it, but that could still be done in a stateless way I suspect.

**Comment by davecheney** [comment]
I have a counterproposal, make the front end responsible for declaring the
version.

The front end has a constant, say 1.5.0 encoded into it, which allows it to
display that version prominently, and also use it as a parameter to the
back end to specify the version of Go it wants to execute the sample.

Of the version of the back end does not match the front end, it can return
some form of error.

Thanks

Dave

**Comment by adg** [comment]
@griesemer honestly, I don't think the UI needs more buttons.

@davecheney That would mean the playground would be broken sometimes. I'd rather serve an old version of the sandbox than break the playground.

**Comment by tomheng** [comment]
@adg  

I want to submit a CL, but did not found web front playground.js in golang/playground repo.

sandbox change to response with go version, web front got it and show in html.

```
diff --git a/sandbox/sandbox.go b/sandbox/sandbox.go
index 7ea6bef..fb0c5e7 100644
--- a/sandbox/sandbox.go
+++ b/sandbox/sandbox.go
@@ -33,8 +33,9 @@ type Request struct {
 }
 
 type Response struct {
-       Errors string
-       Events []Event
+       Errors  string
+       Events  []Event
+       Version string
 }
 
 func main() {
@@ -58,6 +59,12 @@ func compileHandler(w http.ResponseWriter, r *http.Request) {
                http.Error(w, err.Error(), http.StatusInternalServerError)
                return
        }
+       version, err := exec.Command("go", "version").Output()
+       if err != nil {
+               http.Error(w, err.Error(), http.StatusInternalServerError)
+               return
+       }
+       resp.Version = string(version)
        if err := json.NewEncoder(w).Encode(resp); err != nil {
                http.Error(w, fmt.Sprintf("error encoding response: %v", err), http.StatusInternalServerError)
                return
```

**Comment by adg** [comment]
@tomheng I don't want to run a 'go version' on each invocation of a sandbox program.

**Comment by ysmolsky** [comment]
Screenshot for the CL above:
![screen shot 2018-03-04 at 00 11 20](https://user-images.githubusercontent.com/140245/36939828-adc755f0-1f40-11e8-906a-bbf923d49062.png)
