### ISSUE TITLE
cmd/compile: cap() should not be a constant?

### ISSUE THREAD

**Issue by mattn** [golang/go#12215]
See http://play.golang.org/p/XMBfL5ic0v

This mean `sizeof` in C, so we may allow to use cap as constant. But not feeling go syntax I think.

**Comment by dominikh** [comment]
> A constant value is represented by [...] or the result value of some built-in functions such as unsafe.Sizeof applied to any value, cap or len applied to some expressions[1], real and imag applied to a complex constant and complex applied to numeric constants

From https://golang.org/ref/spec#Constants. [1] is https://golang.org/ref/spec#Length_and_capacity which states

> The expression len(s) is constant if s is a string constant. The expressions len(s) and cap(s) are constants if the type of s is an array or pointer to an array and the expression s does not contain channel receives or (non-constant) function calls; in this case s is not evaluated. Otherwise, invocations of len and cap are not constant and s is evaluated.

**Comment by mattn** [comment]
I didn't know it. Thanks.
