### ISSUE TITLE
x/build/cmd/release: Cannot upgrade to go 1.5 directly through MSI package

### ISSUE THREAD

**Issue by linquize** [golang/go#12213]
I installed go 1.4.2 first.
Then I install `go1.5.windows-amd64.msi` package on Win7 x64.

It shows an error message:
```
Another version of this product is already installed.
Installation of this version cannot continue.
To configure or remove the existing version of this product,
use Add/Remove Programs on the Control Panel.
```

I expect it automatically upgrades previous version, but it does not.

**Comment by adg** [comment]
If someone can make this work, please do.

**Comment by linquize** [comment]
```
<Product ...>
...
<Upgrade ...>
  <UpgradeVersion ... />
</Upgrade>
</Product>
```

**Comment by adg** [comment]
@linquize want to implement it? I have no idea what I'm doing with the wxs stuff.

**Comment by linquize** [comment]
May be try to study from other projects
I remember the following project can upgrade from old version

https://github.com/jgm/pandoc/blob/master/windows/pandoc.wxs

**Comment by tylrmac** [comment]
I can try to tackle this. (I've been looking for something to work on and this doesn't seem to hard)

**Comment by adg** [comment]
@tylrmac please do! let me know if you need help.

**Comment by tylrmac** [comment]
@adg any tips for getting a Windows machine/VM set up for building a release build? I've never done a release build for Windows before. Already have my changes I'd like to test.

**Comment by alexbrainman** [comment]
@tylrmac

See this from https://github.com/golang/go/issues/11740#issuecomment-122143142

> you could just run releaselet.go from a directory that contains a go directory containing a compiled Go tree. (and stub out the stuff in releaselet.go that tries to do the godoc/tour stuff)

You will need a windows computer with all bits installed.

golang.org/x/build/env/windows/README describes the way Go builders are configured. You would only need appropriate bits of software installed - you can use "winstrap" program as described in README.

Alex

**Comment by tylrmac** [comment]
@alexbrainman Thanks! Have everything set up correctly now. Now to actually fix the problem...

**Comment by tylrmac** [comment]
I have it working but the solution by default removes the old version before installing a newer version. Is that desired behavior? 

It's possible to prompt the user that the installer will remove the old install but I want to double check before I get it ready for code review.

**Comment by alexbrainman** [comment]
@tylrmac I don't know what is the right choice here. I will let @adg decide.

Alex

**Comment by adg** [comment]
@tylrmac It would be great to prompt the user before deleting anything.

**Comment by tylrmac** [comment]
I have this mostly working. Having a baby in a few days so will have to put off testing until after then.

**Comment by adg** [comment]
Thanks for your efforts!

**Comment by linquize** [comment]
ping

**Comment by tylrmac** [comment]
Sorry @linquize, I have a fix but won't be able to do much with it until next week. Currently in the hospital awaiting the birth of our first child.

**Comment by oec** [comment]
@tylrmac, if you sent me what you have so far, I can pick up from there.  I have some experience with wxs from current projects...   BTW, all the best for you and your familiy, hope all went well!

**Comment by oec** [comment]
https://go-review.googlesource.com/#/c/18071/

**Comment by linquize** [comment]
Will it be included in 1.5.3?

**Comment by alexbrainman** [comment]
> Will it be included in 1.5.3?

I don't see why it wouldn't, but I don't know for sure. @adg builds msi files.

Alex

**Comment by ianlancetaylor** [comment]
I added the 1.5.3 milestone so that can be considered for 1.5.3 (if there is a 1.5.3).  I don't know whether this is appropriate or not.

**Comment by linquize** [comment]
Thx

**Comment by linquize** [comment]
In golang website,
"If you are upgrading from an older version of Go you must first remove the existing version. "
This statement is no longer valid since 1.5.3 (Windows)

**Comment by alexbrainman** [comment]
> This statement is no longer valid since 1.5.3 (Windows)

I think you're correct. I think we should change website text. Except I don't know where the source code is.

Alex

**Comment by linquize** [comment]
@tylrmac updated Windows installer package (msi)  in 1.5.3. The website text shiuld reflect this change.

**Comment by voutasaurus** [comment]
Great work @tylrmac !

@adg it would be great to tell people about this! :) (the website still says "If you are upgrading from an older version of Go you must first remove the existing version.")

**Comment by adg** [comment]
I would rather keep the text as-is, as it applies generally to all kinds of Go installation.

Further, encouraging people to uninstall before installing a new version will lead to fewer support queries in the long term.
