### ISSUE TITLE
cmd/compile: unexpected string to byte casting behavior in 1.5

### ISSUE THREAD

**Issue by groob** [golang/go#12226]
```Go
var lines = []string{"foo", "bar", "baz"}

func main() {
	for _, line := range lines {
		if len(line) == 0 ||
			[]byte(line)[0] == []byte("#")[0] {
			continue
		}
		fmt.Println(line)
	}
}
```
This snippet of code prints the strings as you would expect when compiled with 1.4, but produces no output when compiled with 1.5.
http://play.golang.org/p/hR7iVDC-Vu

Here's a slightly simpler example of the same bug:
```
        s := "foo"
        fmt.Println(len(s)==0 || []byte(s)[0]==[]byte("#")[0])
```
This results in `false` with 1.4, but `true` with 1.5.
by taruti in #golang-nuts on irc

**Comment by tsuna** [comment]
Interestingly, the problem can't be reproduced with `[]byte{...}` syntax:

```go
    s := "foo"
    fmt.Println(len(s) == 0 || []byte(s)[0] == []byte{'#'}[0])
```

This correctly prints false with 1.5.  I wonder if this is related to the compiler bug I just filed in #12225 as that problem also only occurs with byte slices created from strings.

**Comment by johto** [comment]
Also, the len() call seems to be irrelevant.  This reproduces as well:

```go
fmt.Println([]byte("0")[0] == []byte("1")[0] || false)
```

**Comment by uli-go** [comment]
Following program reproduces the bug for me on AMD64:

    package main
    
    import "fmt"
    
    func main() {
    	if []byte("foo")[0] == []byte("b")[0] {
    		fmt.Println("BUG: foo and b appear to have the same first byte")
    	} else {
    		fmt.Println("No bug: foo doesn't start with b")
    	}
    }

It seems to be an issue with the register allocator, the compiler produces CMP BL, BL for the equality operator, which is always true.

**Comment by adg** [comment]
Smells like a compiler optimizer bug to me.

**Comment by adg** [comment]
cc @rsc @josharian

**Comment by uli-go** [comment]
Correction: Statement is `CMPB BL,BL`, which will always be equal.  

go tool compile -N -S produces the same statement, so I suppose it is not the optimizer.

**Comment by e-dard** [comment]
Hi, not sure if this is relevant or not; apologies if it's noise. Did a bit of git bisect...

Test program:

```go
package main

import (
        "os"
)

func main() {
        if []byte("0")[0] == []byte("1")[0] {
                os.Exit(1)
        }
}
```

The last known good (exit status 0) commit I can see for this program is 11dba2ec2d8fcedc1da0103925c254586ef51120.

Following that the above program causes a panic:

```
# command-line-arguments
naddr [0x208d1b440]
.   INDEX u(100) l(8) tc(1) byte
.   .   CALLFUNC u(100) l(8) tc(1) ARRAY-[]byte
.   .   .   NAME-runtime.stringtoslicebyte u(1) a(true) l(2) x(0+0) class(PFUNC) tc(1) used(true) FUNC-func(*[32]byte, string) []byte
.   .   CALLFUNC-list
.   .   .   AS u(2) l(8) tc(1)
.   .   .   .   INDREG-SP a(true) l(8) x(0+0) tc(1) PTR64-*[32]byte
.   .   .   .   ADDR u(2) l(8) tc(1) PTR64-*[32]uint8
.   .   .   .   .   NAME-main.autotmp_0000 u(1) a(true) l(8) x(0+0) class(PAUTO) esc(N) tc(1) addrtaken used(true) ARRAY-[32]uint8

.   .   .   AS u(1) l(8) tc(1)
.   .   .   .   INDREG-SP a(true) l(8) x(8+0) tc(1) string
.   .   .   .   LITERAL-"0" u(1) a(true) l(8) tc(1) string
.   .   LITERAL-0 u(1) a(true) l(8) tc(1) int
../../main.go:8: internal compiler error: naddr: bad INDEX
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1cfdb0]

goroutine 1 [running]:
cmd/compile/internal/gc.hcrash()
	/tmp/go/src/cmd/compile/internal/gc/subr.go:105 +0x50
cmd/compile/internal/gc.Fatal(0x452f90, 0x10, 0x208adf360, 0x2, 0x2)
	/tmp/go/src/cmd/compile/internal/gc/subr.go:198 +0x2b1
cmd/compile/internal/gc.Naddr(0x208d32fd0, 0x208d1b440)
	/tmp/go/src/cmd/compile/internal/gc/gsubr.go:313 +0x1a5b
cmd/compile/internal/amd64.gins(0x3036, 0x208d1b440, 0x208d1b7a0, 0xfffb)
	/tmp/go/src/cmd/compile/internal/amd64/gsubr.go:629 +0x127
cmd/compile/internal/gc.bgenx(0x208d1b830, 0x0, 0x1, 0x0, 0x208c517a0)
	/tmp/go/src/cmd/compile/internal/gc/cgen.go:2061 +0x1954
cmd/compile/internal/gc.Bgen(0x208d1b830, 0x208c51800, 0x0, 0x208c517a0)
	/tmp/go/src/cmd/compile/internal/gc/cgen.go:1739 +0x47
cmd/compile/internal/gc.gen(0x208d1b8c0)
	/tmp/go/src/cmd/compile/internal/gc/gen.go:805 +0xcd4
cmd/compile/internal/gc.Genlist(0x208d01aa0)
	/tmp/go/src/cmd/compile/internal/gc/gen.go:219 +0x30
cmd/compile/internal/gc.compile(0x208d1b050)
	/tmp/go/src/cmd/compile/internal/gc/pgen.go:469 +0xc03
cmd/compile/internal/gc.funccompile(0x208d1b050)
	/tmp/go/src/cmd/compile/internal/gc/dcl.go:1480 +0x1c9
cmd/compile/internal/gc.Main()
	/tmp/go/src/cmd/compile/internal/gc/lex.go:470 +0x1ece
cmd/compile/internal/amd64.Main()
	/tmp/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/tmp/go/src/cmd/compile/main.go:26 +0x189
```

Until a44becef4a7e3af238a1546670717c78eb0069db where the behaviour changes to no panic but an exit code of `1`.

**Comment by uli-go** [comment]
This diff fixes the bug for me:

    diff --git a/src/cmd/compile/internal/gc/cgen.go b/src/cmd/compile/internal/gc/cgen.go
    index 4160ae9..b6a3e5b 100644
    --- a/src/cmd/compile/internal/gc/cgen.go
    +++ b/src/cmd/compile/internal/gc/cgen.go
    @@ -2018,11 +2018,11 @@ func bgenx(n, res *Node, wantTrue bool, likely int, to *obj.Prog) {
     		Regalloc(&n2, nr.Type, nil)
     		Cgen(nr, &n2)
     		nr = &n2
    -		Regfree(&n2)
     
     		Regalloc(&n1, nl.Type, nil)
     		Cgen(&tmp, &n1)
     		Regfree(&n1)
    +		Regfree(&n2)
     	} else {
     		var n1 Node
     		if !nl.Addable && Ctxt.Arch.Thechar == '8' {

**Comment by josharian** [comment]
Want to send a CL? That diff makes sense.

**Comment by uli-go** [comment]
I have sent the CL https://go-review.googlesource.com/#/c/13771/

(It is my first.)

**Comment by dgryski** [comment]
Should that test be an actual test in the CL instead of in the commit message?

**Comment by uli-go** [comment]
You are right. But before I can do that, I have to understand where and how to add the test. I will work on it.

**Comment by dgryski** [comment]
https://github.com/golang/go/tree/master/test/fixedbugs  ?

**Comment by uli-go** [comment]
Thanks for that. The CL includes now test/fixedbugs/issue12226.go.

**Comment by sleaze** [comment]
How many more regressions will we find in 1.5?  Only father time can say..

**Comment by tsuna** [comment]
@sleaze you wanna help fix them or you're just bitching about bugs? :)

**Comment by bradfitz** [comment]
Let's keep this civil please.

**Comment by dgryski** [comment]
Probably worth running @dvyukov's Gosmith 1.4.2 vs 1.5. Previously I think it was only run gc vs gccgo.

**Comment by myml** [comment]
package main

import "fmt"

func main() {
	if []byte("foo")[0] == []byte("b")[0] == true {
		fmt.Println([]byte("foo")[0] == []byte("b")[0])
		fmt.Println("BUG: foo and b appear to have the same first byte")
	} else {
		fmt.Println("No bug: foo doesn't start with b")
	}
}


No bug: foo doesn't start with b

**Comment by myml** [comment]
```
package main

import "fmt"

func main() {
	if []byte("foo")[0] == []byte("b")[0] == true {
		fmt.Println([]byte("foo")[0] == []byte("b")[0])
		fmt.Println("BUG: foo and b appear to have the same first byte")
	} else {
		fmt.Println("No bug: foo doesn't start with b")
	}
}
```

No bug: foo doesn't start with b

**Comment by uli-go** [comment]
@myml: The original test program is definitely buggy on 1.5. Your test is different and it probably doesn't follow the same path in the code generation for the equal operator.

**Comment by myml** [comment]
@uli-go  

```
if []byte("foo")[0] == []byte("b")[0] {} 
```
and  
```
if []byte("foo")[0] == []byte("b")[0] == true {}  
```

**Comment by uli-go** [comment]
@myml: We agree that your program is different.

**Comment by sleaze** [comment]
Why you censor my comments?

**Comment by bradfitz** [comment]
Off-topic or uncivil comments adding no technical value to the discussion may be deleted. Please keep the discussions focused. If you want to discuss something unrelated, use the golang-nuts, but keep it civil there too.

**Comment by mengzhuo** [comment]
Confirm on AMD64
I think this is an urgent bug to fix, how about release 1.5.0.1?

**Comment by rsc** [comment]
Thanks very much for the fix, @uli-go.

**Comment by sleaze** [comment]
@bradfitz Roger that, thank you for explaining!
