### ISSUE TITLE
cmd/compile: internal compiler error: treecopy Name, when using go test -race

### ISSUE THREAD

**Issue by tsuna** [golang/go#12225]
###### What version of Go are you using (go version)?
go version go1.5 darwin/amd64

###### What operating system and processor architecture are you using?
OS X 10.9.5, Intel

###### What did you do?
Run `go build -race` on this file:

```go
package foo

import "unsafe"

func ice() {
	_ = *(*int)(unsafe.Pointer(&[]byte("")[0]))
}
```
It doesn't matter what's passed to `[]byte(...)`, but it seems to matter that it be constructed from a string, not as a literal byte slice (i.e. not `[]byte{...}`).

###### What did you expect to see?
At best a proper compiler error (although I'm not sure why this could be rejected by the compiler), otherwise a runtime crash.

###### What did you see instead?
```
# command-line-arguments
treecopy [0x820b98ea0]
.   INDREG-SP a(true) l(6) x(0+0) tc(1) PTR64-*[32]byte
ice.go:6: internal compiler error: treecopy Name
```

**Comment by tsuna** [comment]
@dvyukov any known workaround to alter the code and achieve the same thing without tripping on this bug?

**Comment by dvyukov** [comment]
@tsuna This seems to work:
```go
func ice() {
	x := []byte("")
	_ = *(*int)(unsafe.Pointer(&x[0]))
}
```

**Comment by dvyukov** [comment]
git blame points to:
```
4fdd53680c0c63d10a8c9c155f6df6e3b1e08367 is the first bad commit
commit 4fdd53680c0c63d10a8c9c155f6df6e3b1e08367
Author: Russ Cox <rsc@golang.org>
Date:   Tue May 26 22:19:27 2015 -0400

    cmd/compile: move Node.Defn to Node.Name.Defn
    
    $ sizeof -p cmd/compile/internal/gc Node
    Node 256
    $
    
    Change-Id: I89ac8bbe077664aa076092bfd096947e84c0624c
    Reviewed-on: https://go-review.googlesource.com/10523
    Reviewed-by: Ian Lance Taylor <iant@golang.org>
    Reviewed-by: Josh Bleecher Snyder <josharian@gmail.com>
```
@ianlancetaylor @josharian
