### ISSUE TITLE
build: Go 1.5 bootstrap.bash fails for offical tarballs

### ISSUE THREAD

**Issue by fawick** [golang/go#12223]
The source tarball lacks `.gitignore` and `.git` so the lines

```bash
rm .gitignore
git clean -f -d
```

will fail and prevent the script from continuing. Removing the lines works, of course. Even better:

```bash
if [ -e gitignore ]; then
    rm .gitignore
fi
if [ -e .git]; then
    git clean -f -d
fi
```

**Comment by fawick** [comment]
Proposed fix at https://go-review.googlesource.com/13770

**Comment by adg** [comment]
So the go 1.5 source tarball doesn't build with a go 1.4 bootstrap tool chain? Is that what you mean?

**Comment by fawick** [comment]
Not quite. Cross-compiling a bootstrap toolchain for 1.5 fails when running bootstrap.bash from within a source tree from the offical tar.gz instead from within a local git repo working copy. I reckon it doesn't matter whether the GOROOT_BOOTSTRAP point's to 1.4 or 1.5 itself.

Here's what I did: On my linux/amd64, I had Go 1.4, downloaded the Go1.5 source tarball and tried to build a bootstrap Go 1.5 toolchain for a Raspberry Pi:

```bash
$ export GOROOT_BOOTSTRAP=$HOME/go1.4
$ tar xzf go1.5.src.tar.gz
$ cd go
$ GOOS=linux GOARCH=arm ./bootstrap.bash
#### Copying to ../../go-linux-arm-bootstrap

#### Cleaning ../../go-linux-arm-bootstrap
rm: cannot remove ‘.gitignore’: No such file or directory
```

When you uncomment the call to `rm` the next thing that will fail is `git clean`.

**Comment by davecheney** [comment]
@adg @rsc would it be possible to get this into 1.5.1 ?

The back story is I'm working on a blog post for raspberry pi folks to explain how to build Go from source (set GO_TEST_SCALE thing, set ulimit -s 1024, etc) and it would be awesome if they could generate their own bootstrap compiler from the official Go distro.
