### ISSUE TITLE
x/tools/cmd/godoc: index creation problem

### ISSUE THREAD

**Issue by jfcg** [golang/go#12224]
On my windows 7 64-bit, i got go-1.5 zip for win64 from golang.org/dl and tried (in d:\go):

godoc -write_index -index_files sind

It hangs up in indefinitely..

**Comment by jfcg** [comment]
Little cpu usage but memory usage exceeds 3 gb & increasing O_o

**Comment by jfcg** [comment]
I saw %50 cpu usage & 7 gb of ram !

**Comment by adg** [comment]
Maybe you have a massive workspace? Try unsetting GOPATH and trying again. 

Is the behavior actually different to the godoc that shipped with 1.4.2?

**Comment by jfcg** [comment]
Unsetting gopath worked, finished in a minute. 

1.4.2 used to be able to do indexing -including gopath- definitely faster with reasonable resources. There must be a regresdion.

My gopath is not particularly crowded, 25- packages, largest is possibly mgo. Gopath/src is ~30 mb

**Comment by adg** [comment]
@jfcg are you sure? what does `go list all` say?

**Comment by jfcg** [comment]
I think i discovered why :)
i had a 550 mb text file left from one of my experiments in the src tree.
That's the reason crazy index times, sorry..
