### ISSUE TITLE
tour: [Time not present in 3-rd sheet of tour]

### ISSUE THREAD

**Issue by greendee** [golang/go#12230]
Context: https://tour.golang.org/welcome/3

It prints "The time is 2009-11-10 23:00:00 +0000 UTC" in 2015 year. Check yours server time please.

**Comment by adg** [comment]
Read the page you are reporting about:

> There are limitations to the programs that can be run in the playground:
> 
> In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.
