### ISSUE TITLE
cmd/go: vendoring fail when put on $GOPATH root with Import Path Checking

### ISSUE THREAD

**Issue by kurze** [golang/go#12232]
I have an issue with vendoring when placed on $GOPATH/src/vendor and "vendored" file use Import Path Checking.
```
$GOPATH
.
└── src
    ├── main
    │   └── main.go
    └── vendor
        └── vnd.org
            └── a
                └── a.go
```
with main.go : 
```
package main

import _ "vnd.org/a"

func main() {}
```
and a.go : 
```
package a // import "vnd.org/a"
```
go build throw many errors like this : 
```
main.go:3:8: code in directory /[...]/src/vendor/vnd.org/a expects import "vnd.org/a"
```

According to the spec : "Code inside vendor/ subtrees is not subject to import path checking.". 

However import path checking is not properly disabled if the vendored package is at the root of GOPATH since the package name doesn't contain "/vendor/" but starts with "vendor/" 
The fix looks easy enough ( replace the condition in file `cmd/go/pkg.go` line 371 with `(!go15VendorExperiment || (!strings.Contains(path, "/vendor/") && !strings.HasPrefix(path, "vendor/")))` ), I can submit a pull request if necessary.

**Comment by adg** [comment]
Putting a `vendor` directory at the root of a workspace directory `$GOPATH/src` is somewhat nonsensical. There's barely a distinction between doing that and not creating the vendor directory at all.

We should probably disallow it.

**Comment by vanackere** [comment]
This bug make it impossible to locally vendor many `golang.org/x/...` packages for example. It would be nice to have this fixed in 1.5.x

**Comment by adg** [comment]
cc @davecheney

**Comment by vanackere** [comment]
I don't see anything wrong with putting a vendor directory at the root of a workspace directory (eg if the intended usage is to make use of external tools to manage this part of the code).

In this particular case, the fix looks also especially obvious and in line with the rest of the code (see `func findVendor`, in `cmd/go/pkg.go` line 639:
```go
	switch {
	case strings.Contains(path, "/vendor/"):
		return strings.LastIndex(path, "/vendor/") + 1, true
	case strings.HasPrefix(path, "vendor/"):
		return 0, true
	}
```

**Comment by mattfarina** [comment]
Can someone explain the use case for `vendor/` being right inside `$GOPTH/src`? I'm attempting to understand when one would put it there.

**Comment by pkieltyka** [comment]
yea, this sounds strange to me too.. sounds like its useful when doing $GOPATH rewriting for project workspaces...?

I personally wish for `vendor/` to have the subdirectories: `src/` and `pkg/`

**Comment by mattfarina** [comment]
@pkieltyka why have those subdirectories inside `vendor/`? The `vendor/` directory and its subdirectories live inside the other directories off the `GOPATH`, for example `pkg`.

**Comment by pkieltyka** [comment]
@mattfarina I'd like to see src/ and pkg/ in the vendor/ of my project so I could use vendor/ dependencies for development. In order to use them for development, I need the pkg/ folder so that the vendored deps won't be rebuilt each time. With vendor/pkg, I can keep doing incremental builds of my project and its deps which is essential for keeping development productive.

**Comment by mattfarina** [comment]
@pkieltyka Try going into your `vendor/` directory and running `go install ./...`. I think that prebuilds them for you. I use Glide (the package manager) and my cohort wrote something similar to this with `glide rebuild`.

**Comment by pkieltyka** [comment]
I guess `go install ./...` in `vendor/` would work, thanks

**Comment by ianlancetaylor** [comment]
Marking this as 1.5.1 so that we can make a decision on whether to include it.  I can't tell whether this is a real bug or not.  If it's a real bug, it's new in 1.5, so fixing it in 1.5.1 is not entirely out of bounds.

**Comment by pkieltyka** [comment]
lol.. all that discussion for a 1 line fix.. nice :) thanks guys
