### ISSUE TITLE
Go 1.5 build from source tarball generates two Test Phase failures...

### ISSUE THREAD

**Issue by peteArnt** [golang/go#12247]
While trying to build Go 1.5 this evening on my Raspberry Pi model 2B running Raspbian, two of the test cases failed:
 FAIL: TestCgoCallbackGC (25.29s)
and
FAIL	runtime	228.455s

After TestCgoCallbackGC reported FAIL, a large (and I mean large) amount of debug text is sent to the console.

Raspbian is actually Debian for the Raspberry Pi platform.
Results of uname -a:
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

BOOTSTRAP compiler is GO 1.42.

How serious are these?
Apologies if this has already been reported.

-Pete

**Comment by bradfitz** [comment]
Dup of #11959 and #12035
