### ISSUE TITLE
testing: documentation: testing.T.Parallel resets time

### ISSUE THREAD

**Issue by joshlf** [golang/go#12243]
The `testing` package's [`T.Parallel`](https://golang.org/pkg/testing/#T.Parallel) method resets the time of the test so  that it's as if the test starts just before the method returns. The reason for doing this is that it's likely the first call made from the testing function. This is reasonable, but I suggest that this behavior be documented. The source is [here](https://golang.org/src/testing/testing.go?s=14868:14890#L410).

**Comment by rsc** [comment]
The reason for resetting the time is that the first time t.Parallel does is block the call until all the other non-parallel tests have completed. You don't want to include those in the time.

Perhaps instead it should pause the timer, not reset it.

**Comment by synful** [comment]
That would probably be more reasonable, but would it constitute a backwards-breaking change?

**Comment by rsc** [comment]
No, I would not consider s/reset/pause/ a backwards-breaking change. Unless you have a specific scenario in mind?

**Comment by synful** [comment]
I was just thinking of any logic that relies on that functionality - technically backwards-breaking, but very unlikely to occur in practice.

**Comment by cespare** [comment]
@joshlf it's not exposed by the testing API, so the only way to rely on the test durations is if you're parsing `go test` output.

**Comment by cespare** [comment]
I sent a CL to change from resetting the timer to pausing it.

If we do the pause instead, is there any point in documenting it, or does it become sufficiently unsurprising in that case?

**Comment by joshlf** [comment]
@cespare In that case I agree that it's not an issue.

**Comment by rsc** [comment]
Fixed by CL 16989.
