### ISSUE TITLE
gofmt damages the indentation

### ISSUE THREAD

**Issue by ip** [golang/go#12257]
For example it turns this
```go
const REGEXP_WHOLE =
	// [1] Return value
	`^\s*` + REGEXP_TYPE +
	// 3+1 = [4] Function name
	`(gl\w+)\s*` +
	// [5] Argument list
	`\((` + REGEXP_ARG_LIST + `)\)\s*$`

// ...

returnType	:= submatches[1]
funcName	:= submatches[4]
argList		:= submatches[5]
```
into
```go
const REGEXP_WHOLE =
// [1] Return value
`^\s*` + REGEXP_TYPE +
	// 3+1 = [4] Function name
	`(gl\w+)\s*` +
	// [5] Argument list
	`\((` + REGEXP_ARG_LIST + `)\)\s*$`

// ...

returnType := submatches[1]
funcName := submatches[4]
argList := submatches[5]
```
Especially first case is annoying. Is it at least a way to locally disable it with comments like in other similar tools i.e. like that?
```go
// gofmt off
blablabla
// gofmt on
```

**Comment by bradfitz** [comment]
No, there's no such mechanism.

You'll have to find another way to reformat your code to make both gofmt and yourself happy.

As an aside, NAMES_LIKE_THIS should be NamesLikeThis or namesLikeThis in Go. See https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps

**Comment by ip** [comment]
@bradfitz Ok, thanks for noticing about constants.
