### ISSUE TITLE
Go with better option parser

### ISSUE THREAD

**Issue by techtonik** [golang/go#12251]
There is a problem with command line usability of `go`. From #12197:
* [ ] no long options like --help or --verbose
* [ ] -h has a strict position, e.g. `go get something -h` doesn't work, only `go get -h something`
* [ ] `go get -h` help is unreadable - lacks visual structure

There are more features that could be added to stdlib. Tools:

https://github.com/jawher/mow.cli
https://github.com/codegangsta/cli

**Comment by bradfitz** [comment]
The behavior of Go's flag package is intentional.

**Comment by techtonik** [comment]
@bradfitz it is not about changing `flag` behavior. Python also still ships with a `getopt`, but rarely who uses that.

**Comment by adg** [comment]
@techtonik as a counterpoint: in my opinion the `go` tools' command line interface is well-defined, well-documented, and consistent. I can't really relate to your criticisms, except that it is a bit different to what you might be used to.

**Comment by ianlancetaylor** [comment]
@techtonik The go standard flag package has made deliberate design choices.  Those seem unlikely to change.  At any rate, they would only change after a discussion of benefits and costs.

It is straightforward to write a different flag parsing package in Go, and to use that in your own programs.  In fact, I'm sure it has been done, e.g., http://godoc.org/code.google.com/p/getopt .

**Comment by techtonik** [comment]
@adg maybe it is just a habit developed because there is no anything else in daily practice to compare with? =)
