### ISSUE TITLE
build: setup android builder with android-L devices

### ISSUE THREAD

**Issue by hyangah** [golang/go#12258]
Some tests are not compatible with Android-L's security model.
Some tests (involving processing stderr/stdout of child processes) are confused.

Here is error messages after patching cl/12559 (for pie)

<pre>
WARNING: linker: /data/local/tmp/syslog.test-50176/syslog.test-50176 has text relocations. This is wasting memory and prevents security hardening. Please fix.
2015/08/21 13:44:14 startServer failed: listen unix /data/local/tmp/syslog.test-50176/syslogtest840502310: bind: permission denied
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/syslog.test-50176
FAIL	log/syslog	1.981s

--- FAIL: TestConnAndListener (0.00s)
	conn_test.go:29: listen unix /data/local/tmp/net.test-50439/go-nettest156564319: bind: permission denied
--- FAIL: TestCloseRead (0.00s)
	net_test.go:28: listen unix /data/local/tmp/net.test-50439/go-nettest558273769: bind: permission denied
--- FAIL: TestCloseWrite (0.00s)
	net_test.go:114: listen unix /data/local/tmp/net.test-50439/go-nettest743620916: bind: permission denied
--- FAIL: TestConnClose (0.00s)
	net_test.go:164: listen unix /data/local/tmp/net.test-50439/go-nettest612674819: bind: permission denied
--- FAIL: TestListenerClose (0.00s)
	net_test.go:205: listen unix /data/local/tmp/net.test-50439/go-nettest021369990: bind: permission denied
--- FAIL: TestPacketConnClose (0.00s)
	net_test.go:236: listen unixgram /data/local/tmp/net.test-50439/go-nettest185898029: bind: permission denied
--- FAIL: TestPacketConn (0.00s)
	packetconn_test.go:57: listen unixgram /data/local/tmp/net.test-50439/go-nettest041550039: bind: permission denied
--- FAIL: TestConnAndPacketConn (0.00s)
	packetconn_test.go:112: listen unixgram /data/local/tmp/net.test-50439/go-nettest041550039: bind: permission denied
--- FAIL: TestUnixListenerSpecificMethods (0.00s)
	protoconn_test.go:215: listen unix /data/local/tmp/net.test-50439/go-nettest385819048: bind: permission denied
--- FAIL: TestUnixConnSpecificMethods (0.00s)
	protoconn_test.go:257: dial unixgram /data/local/tmp/net.test-50439/go-nettest314342631: bind: permission denied
--- FAIL: TestUnixAndUnixpacketServer (0.00s)
	server_test.go:151: listen unix /data/local/tmp/net.test-50439/go-nettest512301857: bind: permission denied
--- FAIL: TestUnixgramServer (0.00s)
	server_test.go:341: listen unixgram /data/local/tmp/net.test-50439/go-nettest015628795: bind: permission denied
--- FAIL: TestReadUnixgramWithUnnamedSocket (0.00s)
	unix_test.go:31: listen unixgram /data/local/tmp/net.test-50439/go-nettest721342812: bind: permission denied
--- FAIL: TestUnixgramZeroBytePayload (0.00s)
	unix_test.go:77: listen unixgram /data/local/tmp/net.test-50439/go-nettest064747275: bind: permission denied
--- FAIL: TestUnixgramZeroByteBuffer (0.00s)
	unix_test.go:127: listen unixgram /data/local/tmp/net.test-50439/go-nettest691965678: bind: permission denied
--- FAIL: TestUnixgramWrite (0.00s)
	unix_test.go:225: listen unixgram /data/local/tmp/net.test-50439/go-nettest293440885: bind: permission denied
--- FAIL: TestUnixConnLocalAndRemoteNames (0.00s)
	unix_test.go:301: listen unix /data/local/tmp/net.test-50439/go-nettest721800559: bind: permission denied
--- FAIL: TestUnixgramConnLocalAndRemoteNames (0.00s)
	unix_test.go:363: listen unixgram /data/local/tmp/net.test-50439/go-nettest607627129: bind: permission denied
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/net.test-50439
FAIL	net	5.456s

--- FAIL: TestLongSymlink (0.00s)
	os_test.go:690: symlink "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", "longsymlinktestfrom" failed: symlink 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef longsymlinktestfrom: permission denied
--- FAIL: TestGetppid (0.02s)
	os_test.go:1615: Child process reports parent process id 'WARNING: linker: /data/local/tmp/os.test-50530/os.test-50530 has text relocations. This is wasting memory and prevents security hardening. Please fix.
		13739', expected '13739'
--- FAIL: TestMkdirAllWithSymlink (0.00s)
	path_test.go:196: Symlink /data/local/tmp/os.test-50530/TestMkdirAllWithSymlink-447302546/link: symlink dir /data/local/tmp/os.test-50530/TestMkdirAllWithSymlink-447302546/link: permission denied
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/os.test-50530
FAIL	os	2.132s

       ....
	exec_test.go:543: iteration 9, process B got:
		WARNING: linker: /data/local/tmp/exec.test-50565/exec.test-50565 has text relocations. This is wasting memory and prevents security hardening. Please fix.
		fd3: listener 127.0.0.1:33373
		
		want:
		fd3: listener 127.0.0.1:33373
		
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/exec.test-50565
FAIL	os/exec	2.826s

--- FAIL: TestGlobSymlink (0.00s)
	match_test.go:197: symlink /data/local/tmp/filepath.test-50618/globsymlink620110739/test1 /data/local/tmp/filepath.test-50618/globsymlink620110739/link1: permission denied
--- FAIL: TestEvalSymlinks (0.00s)
	path_test.go:796: symlink ../../ /data/local/tmp/filepath.test-50618/evalsymlink112903032/test/dir/link3: permission denied
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/filepath.test-50618
FAIL	path/filepath	0.911s

--- FAIL: TestFcntlFlock (0.08s)
	syscall_unix_test.go:98: child process: "WARNING: linker: /data/local/tmp/syscall.test-50825/syscall.test-50825 has text relocations. This is wasting memory and prevents security hardening. Please fix.\n", <nil>
--- FAIL: TestPassFD (0.10s)
	syscall_unix_test.go:166: child process: "WARNING: linker: /data/local/tmp/syscall.test-50825/syscall.test-50825 has text relocations. This is wasting memory and prevents security hardening. Please fix.\n", <nil>
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/syscall.test-50825
FAIL	syscall	1.802s

</pre>

/cc @crawshaw

**Comment by crawshaw** [comment]
This is a duplicate of #10807.

Those results don't look so bad. Unixgram will have to be disabled, but the other failures are just caused by the text relocations warning. Once the relocations are gone they should work.
