### ISSUE TITLE
encoding/asn1: support decoding BER-encoded messages (e.g. PKCS7)

### ISSUE THREAD

**Issue by dtbartle** [golang/go#12267]
There's a couple blockers to being able to parse a BER-encoded PKCS7 message:
1) Support indefinite-length encoding.
2) Support "ANY DEFINED BY".

**Comment by mikioh** [comment]
/CC @agl 

Also please take a look at #8860  and #10621.

**Comment by agl** [comment]
encoding/asn1's design hasn't worked out too well and I don't think that BER support would be suitable.

**Comment by dtbartle** [comment]
I'm aware of at least three other libraries that need to support BER encoding. Two of them ends up ~reimplementing all of asn1 (without nicer tagging/unmarshaling support), and the other tries to convert BER to DER but does it wrong. Afaict they could use golang's asn1 if it supported indefinite-length encodings. The change to implement this is relatively small, and would help reduce the proliferation of buggy implementations.

**Comment by nathany** [comment]
David, since this issue was closed, what did you end up doing for PKCS 7 and BER instead?

**Comment by dtbartle** [comment]
I ended up writing a "BER-to-DER" converter, which I'd like to open-source, but haven't had a chance to yet.
