### ISSUE TITLE
cmd/vet: false positive for build flag when it appears in a string of source code

### ISSUE THREAD

**Issue by srinathh** [golang/go#12269]
I ran into a likely false positive from `go vet` when writing a program that auto-generates  code.

[This program](http://play.golang.org/p/kJgX_8nTCa) generates a warning `+build comment must appear before package clause and be followed by a blank line`

[This equivalent program](http://play.golang.org/p/A-B8EklrHv) without the `// autogenerated by...` comment in the first line doesn't

In either case, i don't think `go vet` should be vetting contents of the string,

**Comment by robpike** [comment]
Unfortunate.

The algorithm it uses is very simple, but is fooled by this corner case. Not worth the trouble to fix.
