### ISSUE TITLE
net: how can we know whether TCPConn is active?

### ISSUE THREAD

**Issue by saturn4er** [golang/go#12265]
How can I know that server close connection with my program? Stackoverflow say that I should check it by conn.Read(&[]byte{0}). Is it Workaround?

**Comment by bradfitz** [comment]
Let's move this discussion to the golang-nuts mailing list. We only use our issue tracker for tracking bugs and outstanding TODO items.

**Comment by mikioh** [comment]
@saturn4er,

Please take a look at https://github.com/golang/go/blob/master/CONTRIBUTING.md, and please use golang-nuts instead.

> I should check it by conn.Read(&[]byte{0}). Is it Workaround?

I think it doesn't work when your socket is configured with TCP fast open protocol. In general, most simple and reliable way is just implementing own, your application-level handshake protocol.
