### ISSUE TITLE
cmd/go: document that "go get" never operates on vendor directories

### ISSUE THREAD

**Issue by jbuberel** [golang/go#12260]
In the docs here:
https://golang.org/cmd/go/#hdr-Vendor_Directories

There is a single section that mentions how the behavior of `go get` changes when the `GO15VENDOREXPERIMENT` env var is enabled:

```
When the vendor experiment is enabled, 'go get' 
checks out submodules when checking out or 
updating a git repository (see 'go help get').
```

A source of confusion and many questions (twitter, slack) results from the assumption that running `go get` with the flag enabled will place downloaded packages into a `vendor` directory, which is not the case. A sentence or two added to the documentation would help:

```
When the vendor experiment is enabled, 'go get' 
checks out submodules when checking out or 
updating a git repository (see 'go help get'). 
The storage location of downloaded packages 
does not change with the experiment enabled; 
'go get' will not place retrieved packages into a
'vendor' directory. 
```

Is it possible to update the documentation prior to the next release?

**Comment by rsc** [comment]
I think we typically avoid non-essential fixes in point releases, especially docs for an experimental feature off by default.

I did add some text to the bottom of golang.org/s/go15vendor.
