### ISSUE TITLE
cmd/dist: list all valid combinations of GOOS and GOARCH

### ISSUE THREAD

**Issue by otm** [golang/go#12270]
To easier write tooling for cross compiling it would be good to programmatically get the possible combinations of GOOS and GOARCH.

The only reference I can find is at http://golang.org/doc/install/source#environment

In addition, `go help environment`only gives examples; and`go help build` and `go help install`does not mention GOOS and GOARCH.

**Comment by bradfitz** [comment]
I've wanted this too for the Go builders.

**Comment by bradfitz** [comment]
See also my comment on https://go-review.googlesource.com/#/c/14272/ where the map of GOOS/GOARCH pairs supporting cgo is duplicated.

That could move to this internal package.

/cc @minux

**Comment by minux** [comment]
so the plan is to move go/build/syslist.go file and cgoEnabled slice into a
new toplevel internal package and also add a list of currently supported
platforms.

The problem is that cmd/dist is first build with the bootstrap compiler, and
I don't how to make that pick up our new internal package.

I have another idea:
we can make cmd/dist be the single point of truth, and generate
go/build/zcgo.go
for the go/build package.

**Comment by hirochachacha** [comment]
Hmm, I don't think the CL satisfy me.

(not tested! sorry!)
Please consider platforms: "nacl_amd64", "linux_s390"
* Both of two are supported by go (build) command and go/build package.
* gccgo support "linux_390", but gc doesn't.
* gccgo and gc doesn't support "nacl_amd64".

My point is:
* Build contexts and compiler supported contexts are different concepts.
* Compiler supported contexts are part of build contexts.
* Compiler supported contexts are different per implementations.

Maybe there are wrong assumptions, if so, please feel free to correct me.

Thank you.

hiro

**Comment by minux** [comment]
That CL is only the first step towards fixing this.
It first centralizes the information to just one place.

And note that all the entries in the cgoEnabled map
are currently supported platforms (at the time the
CL was proposed.)

**Comment by hirochachacha** [comment]
Where is plan9?

**Comment by minux** [comment]
Let me amend what I said.
The goal is to have every supported platform appear
as key in the map.

**Comment by hirochachacha** [comment]
gccgo?

**Comment by minux** [comment]
The gccgo story will be figured out by gccgo maintainers.
cmd/dist is only for gc.

And note that gc can build for any target supported, but
for gccgo you actually need to build and install a separate
gccgo for any platform you need.

**Comment by hirochachacha** [comment]
>And note that gc can build for any target supported, but for gccgo you actually need to build and install a separate gccgo for any platform you need.

Hmm, is this mean gccgo isn't able to cross compile? or need to compile libgo per platforms?

Anyway, I think runtime package is appropriate place to put compiler-dependent information.

What do you think?

Thank you.

hiro

**Comment by minux** [comment]
For example, if you have gccgo for linux/amd64 target, then it's not
possible to build Go programs for solaris/amd64 with that gccgo.
You will have to install a gccgo specific for solaris/amd64.

I don't think the runtime should contain information about supported
platforms.

For one, it's quite reasonable for gc compiled programs to want to
know which platform does gccgo support. And for a Go 1.4 compiled
program to know what platforms another Go version supports. The
property is fundamentally a property of the toolchain, so it should be
part of the toolchain, not part of the compiled programs.

**Comment by hirochachacha** [comment]
Finally, I am convinced by your suggestion. 

I still think `cgoEnabled` should be different per implementations in go/build package.
But it's a different issue.

I also suggest `cmd/api` should be updated after you reaching the goal.
```
func defaultContexts() []*build.Context {
  switch runtime.Compiler {
  case "gc":
    return xxx // import from go tool dist list
  case "gccgo":
    return []*build.Context{build.Default} // only build.Default is needed, because of your suggestion.
  } 
}
```

Thank you for your kindness responses.

hiro
