### ISSUE TITLE
fmt: Sscanf %c skips a blank in Go1.5; not in Go1.3.3, nor in C

### ISSUE THREAD

**Issue by strickyak** [golang/go#12275]
### What version of Go are you using (go version)?
I found this when upgrading from Go 1.3.3 to Go 1.5

### What operating system and processor architecture are you using?
```
GOARCH="amd64"
GOOS="linux"
```
### What did you do?
$ cat scango.go
```
package main

import "fmt"

func main() {
	var x int

	n, err := fmt.Sscanf("A", "%c", &x)
	println("n=", n, "x=", x, "err=", err)

	n, err = fmt.Sscanf(" A", "%c", &x)
	println("n=", n, "x=", x, "err=", err)

	n, err = fmt.Sscanf(" ", "%c", &x)
	println("n=", n, "x=", x, "err=", err)
}
```

### What did you expect to see?
I expected what Go 1.3.3 did:  it always gets the first character in the scanned string, either "A" or " ":
$ go run scango.go 
n= 1 x= 65 err= (0x0,0x0)
n= 1 x= 32 err= (0x0,0x0)
n= 1 x= 32 err= (0x0,0x0)

That's also what my C compiler does 
/* gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) */
$ cat scanc.c 
```
#include <stdio.h>

main() {
  char x[33];
  int n = sscanf("A", "%c", x);
  printf("n=%d <%d>\n", n, *x);
  n = sscanf(" A", "%c", x);
  printf("n=%d <%d>\n", n, *x);
  n = sscanf(" ", "%c", x);
  printf("n=%d <%d>\n", n, *x);
}
```
$ gcc scanc.c 
$ ./a.out 
n=1 <65>
n=1 <32>
n=1 <32>

### What did you see instead?
Under Go 1.5, it skips the blank, and advances to the "A" (in the second clause) or EOF (in the third clause):
$ go run scango.go 
n= 1 x= 65 err= (0x0,0x0)
n= 1 x= 65 err= (0x0,0x0)
n= 0 x= 65 err= (0x7f555757b028,0xc82000a1d0)

**Comment by robpike** [comment]
1.4 also gets a space. Arguably, it's doing what the docs say, but this new behavior, a consequence of a major internal restructuring, is clearly a change in behavior. Should perhaps be fixed. I wish instead we could just tell everyone not to use fmt.Scan*. I wish they had never been written.
