### ISSUE TITLE
bytes: API documentation of ErrTooLarge is incorrect

### ISSUE THREAD

**Issue by adonovan** [golang/go#12287]
Various comments in the API of bytes.Buffer say that failure to allocate a buffer causes ErrTooLarge to be returned.  I think they're all false, since they assume that the error caused by the call to `make` in `makeSlice` is a panic that can be recovered from using `recover`, when in fact it is a fatal error, at least in the gc implementation (though this behavior isn't prescribed by the spec).

I don't think the API as specified can be implemented without runtime magic and/or a spec change.  We should probably strike all mention of ErrTooLarge but leave the variable there with a deprecation comment.

**Comment by dominikh** [comment]
There is one instance where a recoverable panic occurs, when the argument to `make` is unrealistically huge (exceeding the allowed arena size?)

**Comment by ianlancetaylor** [comment]
On a 32-bit system you will get a recoverable panic if you call make([]byte, 0x80000000).

**Comment by rsc** [comment]
As Ian said, this seems to work as intended. It's just that on a 64-bit system there's no such thing as "too large".
