### ISSUE TITLE
x/playground: Cmd.Output example return error from playground

### ISSUE THREAD

**Issue by tomheng** [golang/go#12280]
the [Cmd.Output example](https://golang.org/pkg/os/exec/#Cmd.Output) return error now.

> 2009/11/10 23:00:00 exec: "date": executable file not found in $PATH

I did not knew if it run successfully before the playgound upgrade to go1.5.
but, it should run successfully as expected.

**Comment by adg** [comment]
It won't run in the playground because the playground can't execute processes.
