### ISSUE TITLE
x/tour: the Exercise: Slices misses the mark

### ISSUE THREAD

**Issue by rboa** [golang/go#12284]
Context: http://tour.golang.org/moretypes/14

at this point in the tutorial, we have not seen 2d arrays.  absolutely no idea of how to make them.

also from the problem description, we have no idea of what you are meaning with the function examples.

this is just far too advanced for what a newbie knows

**Comment by nsajko** [comment]
You have input and output types of a function (its type
signature), and simply need to implement one that satisfies
these given types. After that you can play with it and learn
more.

**Comment by robpike** [comment]
The text does give a huge hint. I think it's fine but I know how to do it.

**Comment by lizrice** [comment]
For me, I could only make sense of this by looking at the code for x/tour/pic to figure out where dx & dy were coming from. Got to agree, this seems quite a leap for a beginner. 

Also, the description suggests you'll get to see the image as, y'know, a picture, but it seems it just outputs it as data?

**Comment by kytrinyx** [comment]
@lizrice I'm seeing the actual image.

![pic](https://cloud.githubusercontent.com/assets/276834/10568315/8bab845a-75d3-11e5-893a-b4235e928c93.png)

**Comment by kytrinyx** [comment]
@adg I can take a look at this one.

**Comment by kytrinyx** [comment]
@adg How about adding a slide that creates a tic tac toe game before we get to the Pic exercise?

That would let us show a slice of slices in a slightly different setting. It's close enough to provide a good hint, but they'll still have to work out the looping for themselves.

http://play.golang.org/p/LnZ06-353y

**Comment by adg** [comment]
@kytrinyx I like it!

**Comment by kytrinyx** [comment]
Alright, I gave it a shot. I wasn't sure where to put it, so I added it immediately after the place where slices are introduced and described as `[]T` slice of type T.
