### ISSUE TITLE
doc: 1.5 release notes don't mention that go install removes the binary produced by go build

### ISSUE THREAD

**Issue by ainar-g** [golang/go#12288]
After [CL 10682](https://go-review.googlesource.com/#/c/10682/) go install removes the stale binary that was left by go build. This new behaviour is not documented in the [Go 1.5 Release Notes](http://tip.golang.org/doc/go1.5), which has already [caused some confusion](http://stackoverflow.com/q/32180434/1892060). This should be documented in the release notes (and other build-related documents) along with the rationale for this change.

**Comment by rsc** [comment]
Possible for 1.5.1.

**Comment by minux** [comment]
So pure docs changes are allowed in point releases?

**Comment by ianlancetaylor** [comment]
It can be argued either way but personally I think it's OK.  A doc change can address an issue that can not be worked around--if the docs are wrong people can be completely lost.  And a doc change can't introduce a new bug.
