### ISSUE TITLE
website and blog: JavaScript error on golang.org in Safari

### ISSUE THREAD

**Issue by nathany** [golang/go#12283]
When visiting golang.org in Safari (8.0.8) on OS X (10.10.5) the featured articles are not displayed. There is a JavaScript error in the console.

<img width="1107" alt="featured-articles" src="https://cloud.githubusercontent.com/assets/4566/9429597/f0364f30-4992-11e5-9301-5d3332e6553d.png">

```
[Error] TypeError: undefined is not a function (evaluating 's.startsWith(prefix)')
	personalizeInstallInstructions (godocs.js, line 251)
	(anonymous function) (godocs.js, line 311)
	k (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	ready (jquery.min.js, line 2)
	D (jquery.min.js, line 2)
```

**Comment by nathany** [comment]
"This is a new technology, part of the ECMAScript 2015 (ES6) standard." https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

https://github.com/golang/tools/blob/master/godoc/static/godocs.js

**Comment by nathany** [comment]
The following change should fix it:
```diff
-if (!s.startsWith(prefix))
+if (s.indexOf(prefix) != 0)
```
But I'm having trouble testing the change locally right now.

**Comment by nathany** [comment]
oh, i see. makestatic.go needs to run.

**Comment by nathany** [comment]
https://go-review.googlesource.com/#/c/13841/

**Comment by nathany** [comment]
The error is still present at golang.org. Would you like me to test it in Safari after it is deployed?

**Comment by adg** [comment]
It's deployed and I tested it in Safari. Thanks @nathany

**Comment by nathany** [comment]
@adg Thanks for deploying the website. 

I am still seeing this [error on the blog](http://blog.golang.org) however. I'm not sure if an additional change is required or if it's just a matter of redeploying?

**Comment by adg** [comment]
Just needs a redeploy, which will happen this week.
