### ISSUE TITLE
fmt: Printf `%d` printing functions as integers confuses newbies

### ISSUE THREAD

**Issue by tv42** [golang/go#12295]
From IRC: http://play.golang.org/p/AnMCdU2VM1

```go
	w := bufio.NewWriter(os.Stdout)
	fmt.Printf("Available: %d \n", w.Available)
```

The fix is obvious to you and me, but the fact that a fix is needed is not obvious to an unsuspecting mind.

I wonder if that could be changed to require %p (and make %v show something that doesn't look as easily confused; ideally a string that identifies it as a function), similar to the `%!d(string=Hello, playground)` handling.

**Comment by adg** [comment]
Is there a reasonable situation where someone might want to format a function pointer as a base-10 number? It would be a shame to deny that because of a rare misunderstanding. (Have you seen this come up more than once?)

**Comment by tv42** [comment]
"Reasonable" is very subjective. Right now functions behave just like pointers, which includes `%d` showing them in base-10 and `%v` as hex. That is probably what an programmer with a C background would expect, too.

I do not necessarily mean fmt behavior should change; I'm merely documenting the problems I see more than one person having. This misunderstanding may still be rare, but I've seen more than one person succumb to it; the part that especially tricks them is when they expected to see a number, and can't tell what they're seeing is a completely different kind of a number.

Perhaps there is an alternate route, e.g. via `go vet`, `golint`, etc -- though the new gophers that suffer from this don't know of these tools either! So perhaps the "right fix" is play.golang.org integration of `go vet`/`golint`?

**Comment by adg** [comment]
I don't think the fmt behavior could change, even if it was desired. A vet check for this seems natural. Perhaps this CL should be about that. (wdyt @robpike?)

There's issue #7597 about adding vet to the playground, and even some CLs to make it happen. I am due to review those soon.

**Comment by robpike** [comment]
Possibly worth catching in vet. There's little point in ever printing a function value; you can't even compare function values. But it's a pretty rare case the "newbie" argument is never compelling. A better solution might just be to teach newbies to use %T when they are confused.

**Comment by bradfitz** [comment]
This just came up here: https://go-review.googlesource.com/#/c/14031/1/src/cmd/compile/internal/gc/fmt.go

**Comment by robpike** [comment]
Yes. I think it's such an easy thing to add to vet's existing print checker that it should be done.
