### ISSUE TITLE
syscall: LoadDLL() bad error formatting on Windows

### ISSUE THREAD

**Issue by ip** [golang/go#12293]
This is a tiny issue. I use Windows 7 x64. How to reproduce:
`echo > corrupted.dll`
Create main.go:
```go
package main

import (
	"syscall"
	"fmt"
)

func main() {
	_, err := syscall.LoadDLL("./corrupted.dll")
	if err != nil {
		fmt.Println(err)
	}
}
```
It writes: `Failed to load ./corrupted.dll: %1 is not a valid Win32 application.`

Probably there are more similar errors in other places.

**Comment by alexbrainman** [comment]
Windows returns you ERROR_BAD_EXE_FORMAT. The error message for it (https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx) is "%1 is not a valid Win32 application.". So that is what Go prints.

It is unfortunate, but I don't see how we can improve this situation.

Alex

**Comment by ip** [comment]
Yes, sorry, I just wrote same program in C++ and got same output.
