### ISSUE TITLE
net: TestDialerDualStack is flaky

### ISSUE THREAD

**Issue by tzneal** [golang/go#12309]
It's been failing regularly on Windows/x64 , example at https://build.golang.org/log/6d9c92c981b5fb561f33eda94a418ee2ec05a846

    --- FAIL: TestDialerDualStack (4.91s)
	    dial_test.go:664: dial tcp 127.0.0.1:4306: i/o timeout

**Comment by mikioh** [comment]
/CC @pmarks-net 

Same as #12052,  dialClosedPort on Windows also takes a bit long time?

**Comment by rsc** [comment]
Fixed by CL 14120.
