### ISSUE TITLE
x/tools/cmd/gotype: broken for go <1.5

### ISSUE THREAD

**Issue by bwester** [golang/go#12305]
Commit [12c48ced (cmd/gotype: use std lib go/types instead of x/tools version)](https://go.googlesource.com/tools/+/12c48ced94a7752f71687ef145a83a59e9a6f846) to the "gotype" tool prevents the tool from being built on versions of go prior to 1.5. For instance:

```
$ curl https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | tar xz
$ export GOROOT=$HOME/go
$ export PATH=$PATH:$GOROOT/bin
$ export GOPATH=$HOME/gopath
$ go version
go version go1.4.2 linux/amd64
$ go get golang.org/x/tools/cmd/gotype
package golang.org/x/tools/cmd/gotype
	imports go/importer: unrecognized import path "go/importer"
package golang.org/x/tools/cmd/gotype
	imports go/types: unrecognized import path "go/types"
```

Just going by the commit, it would appear that the future of "gotype" is to use packages that have recently been included in Go's standard library.  Is this an intentional deprecation of the command for older versions?

cc: @griesemer

**Comment by griesemer** [comment]
https://go-review.googlesource.com/13899

pending review

**Comment by bwester** [comment]
Thanks for fixing this problem so quickly!

**Comment by griesemer** [comment]
Apologies for breaking it in the first place.

**Comment by griesemer** [comment]
This was fixed by https://go-review.googlesource.com/13899.
