### ISSUE TITLE
cmd/go: go get in go1.5 doesn't understand some git remote URLs

### ISSUE THREAD

**Issue by akalin** [golang/go#12313]
I get this on my repo:

```
go get -u ./...
package ...: unable to parse output of git config remote.origin.url
```

the output of `git config remote.origin.url` looks like:

`github-something:path/to/project.git`

where `github-something` is defined in my ssh-config like so:

```
Host github-something
 User git
 HostName github.com
 PasswordAuthentication no
 IdentityFile /path/to/home/.ssh/id_rsa.something
```

(I do this to manage multiple github identities with different certs.)

This worked fine in go 1.4.2.

**Comment by akalin** [comment]
A workaround is to change the remote URL to:

```
git@github-something:path/to/project.git
```

It would be nice if this weren't needed though, since it repeats the username.

**Comment by rsc** [comment]
This happens in src/cmd/go/vcs.go's gitRemoteRepo. @adg added the code to turn git's shorthand user@server:path into a proper URL ssh://user@server/path. It seems okay to me to make the same code turn server:path into ssh://server/path.

**Comment by rsc** [comment]
My fix caused #13657.
Leaving for someone who needs the fix more.

**Comment by shurcooL** [comment]
> A workaround is to change the remote URL to:
>
> ```
> git@github-something:path/to/project.git
>```
>
> It would be nice if this weren't needed though, since it repeats the username.

Another workaround is to use an easier-to-parse URL format that `url.Parse` supports instead of the SCP-like syntax:

```
ssh://github-something/path/to/project.git
```

**Comment by bcmills** [comment]
If I understand correctly, this issue does not affect module mode, since we don't try to infer origins in that mode.

**Comment by seankhliao** [comment]
Doesn't affect module mode, and GOPATH go get no longer exists.
