### ISSUE TITLE
text/template: add support for optional comment argument in {{end}} tag

### ISSUE THREAD

**Issue by bruth** [golang/go#12318]
Such as `{{end "loop"}}`. The motivation is to make it easier to read where an action ends when there are many. All *endable* actions close with a generic `{{end}}` rather than `{{endif}}` and `{{endwith}}`, it makes it difficult to read which `{{end}}` goes with what action.

**Comment by adg** [comment]
I don't think this is a substantial improvement over ``{{end}}{{/* loop */}}`.

**Comment by bruth** [comment]
Thanks, fair enough.
