### ISSUE TITLE
Go Mobile - Building librairies to use from cordova/phonegap ?

### ISSUE THREAD

**Issue by lakano** [golang/go#12314]
Hello,

I would like to known if there is an elegant solution to permit to use Go Mobile with cordova please?

I suppose we need to use Go Mobile as a SDK library, then to create a iOS plugin that use Go Mobile and permit to be used by Cordova, then the same for Android. 

But each time we add a feature in the Go Mobile core, this mean will need to adapt also iOS/Android code before using it in Cordova. 

I don't known how, but may be it's possible to create a generic plugin, that permit to call any function of the Go Mobile code, and just return an error if the function doesn't (yet) exists? 
This could be really useful, and permit to only update our Go Mobile code, and our cordova code.

Regards,

**Comment by ianlancetaylor** [comment]
Please ask questions on the mailing list.  We use the issue tracker for bug reports and TODOs.  Thanks.

I don't know the answer to your question.
