### ISSUE TITLE
go install -a always rebuilds standard library

### ISSUE THREAD

**Issue by marcopeereboom** [golang/go#12329]
I used to use the -a flag on go install a lot because I tend to update go all the time and sometimes stuff got stale.  I stopped using -a because it started rebuilding standard library which caused other interesting side effects.  Anyway, I stopped using it but I now have a real use for it and I would like to know if either the documentation is wrong or if there is a bug.

For example in one of my toy projects:
```
$ go install -v -a ./...
runtime
errors
unicode
sync/atomic
unicode/utf8
...
```
It clearly goes and rebuilds all the standard library stuff before it gets to my code.

The documentation says:
```
        -a
                force rebuilding of packages that are already up-to-date.
                In Go releases, does not apply to the standard library.
```

So which is it?

**Comment by ianlancetaylor** [comment]
The documentation is wrong.

Dup of #12203 .
