### ISSUE TITLE
time: Parse any two-digit day in any month

### ISSUE THREAD

**Issue by rsc** [golang/go#12333]
time.Parse rejects October 32, but time.Date accepts it (explicitly, in the docs).
Perhaps October 32 should be valid in time.Parse as well.

This would be an alternate approach to the inconsistency that Feb 31 is accepted. See #7268.

**Comment by xpbliss** [comment]
aa:="2015-8-2"    //or  2015-08-2, or 2015-8-02
t1, er1 := time.ParseInLocation("2006-01-02", aa, time.Local)
		if er1 != nil {
			fmt.Println("parse date wrong!")  //it will be wrong.
		}

but if the aa is "2015-08-02", it's ok.
