### ISSUE TITLE
proposal: Provide mechanism for custom x509 verification in crypto/tls

### ISSUE THREAD

**Issue by ghaskins** [golang/go#12336]
Most typical SSL/TLS interactions warrant a standard x509 validation process involving verifying a chain of x509s against a pre-established set of root CAs.  However, there are a subset of applications where this is not the desired functionality.  APIs such as OpenSSL recognize this and provide a way to override the default behavior (e.g. SSL_CTX_set_cert_verify_callback).  crypto/tls seems to lack such a feature, instead opting to invoke x509.Verify() directly.  It would be helpful to provide conceptual equivalence, perhaps by allowing a Verify function to be set on the Config.

**Comment by bradfitz** [comment]
What are the concrete use cases that Go's APIs make difficult?

We already support changing the root CAs with tls.Config.RootCAs.

The http Client already provides a DialTLS hook letting you do your own verification there.

The tls Config already provides InsecureSkipVerify to let it get out of the way and let you do your own verifications before using the connection.

I don't see how adding more mechanism enables anything new, and only serves to confuse the readers of documentation about the N different ways to do things.

**Comment by ghaskins** [comment]
Hi Brad,


1) RootCA approach: validating a self-signed certificate is generally different from the process of validating a chain of traditional PKI certs, and as far as I know, there is no value of tls.Config.RootCA that would allow the current validation routines to do the right thing.  I could try experimenting with this idea.

2) http Client approach: I am not familiar with the http subsystem to comment on whether this is a feasible suggestion.  However, I need raw sockets so it wouldn't help me if it could.  

3) InsecureSkipVerify approach: It looks like I _might_ be able to do as you suggest with tls.Conn -> ConnectionState -> PeerCertificates, but its not entirely clear how to get the tls.Conn from the tls.Dial which seems to return a net.Conn.  Any suggestions?

**Comment by ghaskins** [comment]
I figured out the deal with net.Conn vs tls.Conn, and verified that your suggestion does indeed work, as demonstrated here: https://gist.github.com/ghaskins/5f9758d7e8cb48bf1f7d

Thanks Brad!

-Greg
