### ISSUE TITLE
Parse date wrong?

### ISSUE THREAD

**Issue by xpbliss** [golang/go#12335]
aa:="2015-8-2" //or 2015-08-2, or 2015-8-02
    t1, er1 := time.ParseInLocation("2006-01-02", aa, time.Local)
    if er1 != nil {
        fmt.Println("parse date wrong!")            //it will be wrong.
    }

but if the aa is "2015-08-02", it's ok.

**Comment by adg** [comment]
"2015-8-2" is not in the format of "2006-01-02", it is "2006-1-2". So the function is working as intended.
