### ISSUE TITLE
binary doesn't installed in  $GOROOT/bin but not in $GOPATH/bin

### ISSUE THREAD

**Issue by LuoPX-15510486969** [golang/go#12334]
Here is my go env:
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GoWork
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

After running go install ,the binary istalled in in  $GOROOT/bin but not in $GOPATH/bin.The fact should be  $GOPATH/bin.so i don't know why.

**Comment by davecheney** [comment]
This is because you have set `GOBIN`, please unset `GOBIN`, in my opinion you do not need to set it.
