### ISSUE TITLE
cmd/compile: [dev.ssa] no-opt build broken

### ISSUE THREAD

**Issue by josharian** [golang/go#12347]
CL 13683 broke the no-opt (`-gcflags="-N -l"`) build. The first failure log is:

http://build.golang.org/log/51a0a72aa149162a4a96a94a432c3160310c41fb

I haven't looked into it at all.

**Comment by randall77** [comment]
Ok, that fix was somewhat of a red herring.  What's going on is this:

b1 -> b2
b2 -> b3
b3 -> b2

All of which are on the dead side of a constant branch.  b2 uses a value x from v1.  When we detect that b1 is dead during machine-independent optimization, we mark b1 as dead and remove all its values, including x.  But b2 & b3 form a loop, so they are not removed during this phase (they will be during deadcode, but that is a separate pass).  So the user of x is still around, and check complains that it has a missing arg.

**Comment by randall77** [comment]
func f_ssa(x int, p *int) {
	if false {
		y := x + 5
		for {
			*p = y
		}
	}
}
