### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by jace2005** [golang/go#12341]
Context: https://tour.golang.org/welcome/1

Hi,

When i used the following example you provided i have a strange result:

Please explain me this subtility

package main

import "fmt"

func split(sum int) (x, y int) {
	x = sum * 4 / 9
	y = sum - x
	return
}

func main() {
	fmt.Println(split(2009000123))
}

result whereas i'm expecting an error?

-61548233 2070548356

**Comment by ALTree** [comment]
`2009000123 * 4` overflows int32. On the playground `int`s are 32 bit, hence the negative value.

p.s. questions like this should be asked on the golang-nuts mailing list. The issue tracker is for bugs and proposals.

**Comment by jace2005** [comment]
thx for your quick reply.
