### ISSUE TITLE
testing: examples do not always capture stdout

### ISSUE THREAD

**Issue by alexcesaro** [golang/go#12348]
Examples do not capture stdout when os.Stdout is assigned to a variable outside the example body:

```go
// foo_test.go
package foo

import "os"

var f = os.Stdout

func Example() {
	f.WriteString("a")
	// Output:
	// a
}
```

```
$ go test
a--- FAIL: Example (0.00s)
got:

want:
a
FAIL
exit status 1
```

**Comment by minux** [comment]
I think this is reasonable limitation, f is assigned before the
testing package can replace it. If the example author does
this, then it's probably intentional to bypass the output
capture.

**Comment by ianlancetaylor** [comment]
It doesn't work, so, don't do that.  Examples are a convenience feature for documentation, not something that has to work no matter what the program does.
