### ISSUE TITLE
net/http: ReverseProxy doesn't handle nil request body...

### ISSUE THREAD

**Issue by samprakos** [golang/go#12344]
My code is paraphrased here (where rp is an httputil.NewSingleHostReverseProxy):

	req, _ := http.NewRequest("GET", myURL, nil)
	rp.ServeHTTP(w, req)

This worked in 1.4.2 but panics in 1.5 with:

goroutine 84 [running]:
net/http/httputil.(*runOnFirstRead).Read(0xc820458d40, 0xc82044bb90, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/httputil/reverseproxy.go:118 +0x83
go.(*struct { io.Reader; io.Closer }).Read(0xc820458d60, 0xc82044bb90, 0x1, 0x1, 0x0, 0x0, 0x0)
        <autogenerated>:43 +0x82
io.ReadAtLeast(0x28047d0, 0xc820458d60, 0xc82044bb90, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/io/io.go:298 +0xe6
io.ReadFull(0x28047d0, 0xc820458d60, 0xc82044bb90, 0x1, 0x1, 0xc71788, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/io/io.go:316 +0x62
net/http.newTransferWriter(0x5d80a0, 0xc8202e7960, 0xc820445490, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/transfer.go:71 +0xa99
net/http.(*Request).write(0xc8202e7960, 0xc716e8, 0xc8203adfc0, 0x0, 0xc82045cb10, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/request.go:435 +0x9ac
net/http.(*persistConn).writeLoop(0xc8203262c0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:1015 +0x27c
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.5/libexec/src/net/http/transport.go:686 +0xc9d

I changed my NewRequest code to this:  http.NewRequest("GET", meUrl, strings.NewReader("")) and it works fine.

**Comment by bradfitz** [comment]
ReverseProxy is generally used to turn incoming server requests into outgoing client requests to the proxy backend.

Server requests are guaranteed to have a non-nil body. The docs say:

```
        // For server requests the Request Body is always non-nil
        // but will return EOF immediately when no body is present.
        // The Server will close the request body. The ServeHTTP
        // Handler does not need to.
        Body io.ReadCloser
```

Still, this is easy enough to fix.

**Comment by bradfitz** [comment]
I'm tagging this as Go 1.5.1 so somebody else can decide whether to take this simple fix. Of course, there's a workaround: fork the httputil package and fix ReverseProxy in the fork.

Fix is: https://go-review.googlesource.com/13935

**Comment by samprakos** [comment]
Thanks!!  The documentation for http.NewRequest specifies that body is optional and has nil checking there.
