### ISSUE TITLE
hash: should document byte order of Hash.Sum

### ISSUE THREAD

**Issue by dsnet** [golang/go#12350]
Using ```go1.5```

The hash/* libraries [output a slice with the hash in big endian byte order](https://play.golang.org/p/UxXsVEvNNG) when the Hash.Sum([]byte) method is called. This is fine, but it should be documented.

This does not apply to crypto hashes since those hashes are long enough (and don't fit in native integer types) that nobody mistakes the byte order.

**Comment by minux** [comment]
I don't think we can change the docs for hash.Hash.Sum now
as there might be existing implementations.

Instead my CL added docs to each use of the interface to
all four hash/* packages.
