### ISSUE TITLE
x/tools/cmd/present: support multiple displays

### ISSUE THREAD

**Issue by adg** [golang/go#12355]
It's been expressed by @matryer and by others that it would be nice to have a Keynote-style multi-display support. The second display would show speaker notes and the upcoming slide.

My thoughts on how this might be implemented:

- Introduce the notion of a "session" on the present server side
- When a client loads a slide presentation, they create a websocket connection to the present server (as they do now), and that connection is tied to a specific session (this is new).
- The websocket, in addition to carrying snippets to be compiled and their results, will also carry slide navigation instructions. When the client navigates forward or back, this is communicated to the server, and the session object on the server is updated to reflect that state.
- Additional clients can connect to that session using the unique session id. Any slide navigation instructions are relayed to all connected clients, and those clients reflect that navigation in the user interface.
- Additional kinds of clients can then be implemented. One of these might be the "presenter view" which includes speaker notes (comments extracted from the slide source) and a preview of the upcoming slides.
- The default slide view would then include a shortcut key to pop open a presenter view, used in a multi-display context.

cc @robpike

**Comment by robpike** [comment]
@rsc 

I never wanted this, but I understand the desire and I believe @rsc has done something like this already.

**Comment by adg** [comment]
I don't think @rsc's is based on present at all, but I could be wrong.

**Comment by matryer** [comment]
I know a couple of people who didn't use present because they needed the notes. Shame, because there's something neat about gofmt for presentations.
