### ISSUE TITLE
error on runing in Go 1.5 release

### ISSUE THREAD

**Issue by 7belrhalmia** [golang/go#12353]
this only happen in Go 1.5 

package runtime: C source files not allowed when not using cgo or SWIG: atomic_386.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c os_linux_386.c panic.c parfor.c proc.c runtime.c signal.c signal_386.c signal_unix.c stack.c string.c sys_x86.c vlrt.c

**Comment by davecheney** [comment]
Your go 1.5 installation contains parts of Go 1.4 or you have set
GOROOT_BOOTSTRAP incorrectly.

Please try again with a clean copy of the source and if this fails report
back with the entire output of what you tried and what you saw.

Thanks

Dave
