### ISSUE TITLE
x/tour: a word about rand.Intn

### ISSUE THREAD

**Issue by Geof23** [golang/go#12370]
Context: http://tour.golang.org/basics/1

Hi -- this is a nice tutorial!

I did want to mention that I think your verbiage is a little off here:

***
Note: the environment in which these programs are executed is deterministic, so rand.Intn will always return the same number.
***

Don't you mean that it will always return the same sequence of numbers?

**Comment by Geof23** [comment]
[but I see your approach in keeping it very simple.  Perhaps you mean in this context that if you rerun the example you will always get the same number. ]

I mean that for each sequence of calls to Intn you will get the same sequence of return values.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
I'll see if I can clarify this.
