### ISSUE TITLE
tour: rand.Intn() returns the same number

### ISSUE THREAD

**Issue by santoshkushwaha** [golang/go#12371]
Context: http://127.0.0.1:3999/basics/2

Why does rand.Intn(10) return same number (in my case 1) regardless of how many times it is being executed.

**Comment by adg** [comment]
As the page says:

> Note: the environment in which these programs are executed is deterministic, so rand.Intn will always return the same number. (To see a different number, seed the number generator; see rand.Seed.)

**Comment by santoshkushwaha** [comment]
got it, thanks
visited https://gobyexample.com/random-numbers
