### ISSUE TITLE
os: IsNotExist returns false for file on non-existing \\server\share

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#12374]
This program

package main

import (
	"log"
	"os"
)

func main() {
	_, err := os.Stat(`\\no_such_server\no_such_share\no_such_file`)
	if err == nil {
		log.Fatal("stat succeeded")
	}
	if !os.IsNotExist(err) {
		log.Fatal("os.IsNotExist is false")
	}
}

fails with

2015/08/28 10:08:21 os.IsNotExist is false
exit status 1

but should succeed.

It appears windows returns ERROR_BAD_NETPATH error here, but os.IsNotExist does not check for that error.

Alex

**Comment by choleraehyq** [comment]
I can't reproduce this problem on windows 7 amd64 with go1.5 .
Can you give an example path rather than `\\no_such_server\no_such_share\no_such_file`？Thx.

**Comment by alexbrainman** [comment]
If you run program above (as is), what does it output?

Alex

**Comment by choleraehyq** [comment]
The error is not ERROR_BAD_NETPATH. It's GetFileAttributesEx.

**Comment by alexbrainman** [comment]
@choleraehyq I am not asking what the error is, I just want to know what you see on your screen. My program outputs this:
```
2015/08/28 10:08:21 os.IsNotExist is false
exit status 1
```

Do you see something completely different? Would you mind providing your screen output? you can use mouse to select required portion of your screen and clipboard to capture it. Alternatively you can press PrintScreen key to get a picture.

Alex
