### ISSUE TITLE
build: upgrade nacl builders to pepper_44 or later

### ISSUE THREAD

**Issue by davecheney** [golang/go#12379]
Closing #11961 removed the limitation keeping us on pepper_41. This issue is a reminder to upgrade the nacl builders to a more recent version of pepper

**Comment by minux** [comment]
Should we also continue to test Go at the documented minimum version of
pepper?

**Comment by davecheney** [comment]
@minux I don't think that is necessary. Go 1.5 requires pepper_41, and as long as we don't land any changes to Go 1.5 related to nacl, it shouldn't bit rot (famous last words).

I am upgrading my nacl/arm builder to pepper_44, I don't know if @bradfitz has the resources to test pepper_41 and pepper_44.

Or, we could just leave the builders on pepper_41 until further notice.

**Comment by minux** [comment]
Ideally we should test both the oldest supported version and newest
released version,
leave for @bradfitz to decide.

**Comment by davecheney** [comment]
> Ideally we should test both the oldest supported version and newest

pepper_41 is way outside of support (gulp!), that is why I wanted to get off it ASAP, SRPC was removed in pepper_42 and that is almost as ancient.

Assigning to @bradfitz to make a call.

**Comment by minux** [comment]
http://golang.org/misc/nacl/README says the nacl port requires at least
pepper_39 to work, I think we should make sure that this statement
remains correct.

**Comment by rsc** [comment]
@bradfitz, how can we go about updating the nacl builders to a newer version of nacl?

**Comment by bradfitz** [comment]
@rsc, in the pre-Kubernetes world we would update the Dockerfile for that image (https://github.com/golang/build/tree/master/env/linux-x86-nacl) and then run the steps from the notes in the Makefile to produce a new bootable GCE image from that Dockerfile: https://github.com/golang/build/blob/master/env/linux-x86-nacl/Makefile

But in the new Kubernetes-based builder world that @evandbrown has been working on (deployed for one non-trybot builder as a test right now), it's a bunch fewer steps: just updating the Dockerfile and pushing the new container image. No need to create a bootable VM image.

@evandbrown and I can work on moving the nacl builders to Kubernetes and fixing this in the process.

**Comment by evandbrown** [comment]
6cd016f adds additional NaCl builders at version 44.0.2403.157 to the Kubernetes builders. We can easily add support for other versions if necessary.

@bradfitz, you or someone with access to the symbolic-datum-552 GCP project will need to run `make prod` in `build/env/linux-x86-nacl` (and re-deploy the coordinator to the prod farmer) for this to take effect.

**Comment by bradfitz** [comment]
Thanks! I built and pushed the new Docker image but I'll wait to restart the coordinator until later tonight, when the east coast is sleeping and not running builds.

**Comment by rsc** [comment]
Sorry, changed the milestone without seeing that there were recent comments.

**Comment by bradfitz** [comment]
Hit problems with this. It basically worked, until it didn't. Debugging in #14112 (Kubernetes buildlets failing). Kubernetes-based buildlets are new so far and not widely deployed. Once stable we want to convert most builders to them.

**Comment by bradfitz** [comment]
@evandbrown confirmed that some builds succeeded on the builder's staging cluster with pepper_44 or pepper_45 (whatever we updated to), so master currently is fine with modern nacl. In light of that, removing this from the Go1.6 milestone.

We'll fix Kubernetes builders but not tied to this release..

**Comment by bradfitz** [comment]
This has been running for some time now on the prod build farm. Closing.
