### ISSUE TITLE
website: not available to Iranians

### ISSUE THREAD

**Issue by SeMeKh** [golang/go#12380]
Unfortunately golang.org is not available to Iranian users. Trying to access any resources on the domain will result in a GCE 403 page. Is this behaviour intentional?

**Comment by SeMeKh** [comment]
Please note that this includes all packages hosted on `golang.org` as well as the website itself.

**Comment by jbuberel** [comment]
@SeMeKh Thank you for the report. This is a known issue related to the hosting configuration of the *.golang.org websites. We are working on a solution. I will update this issue when updated information is available.

**Comment by jbuberel** [comment]
@SeMeKh We're sorry, but golang.org content isn't available in your country at this time due to cryptography libraries contained in the standard library.

**Comment by SeMeKh** [comment]
@jbuberel Thanks for the followup, but how does that mean golang.org should not be available in my country? AFAIK that could only mean `go` itself, due to including standard librariy, shouldn't be downloadable from Iran. That doesn't have anything to do with the docs, and the packages hosted on golang.org, right?

I'm aware of the fact that it's easier to block the whole website just to play it safe, but it'd be great if there was a way  to keep Go's ecosystem a "free" (as in freedom) one, without violating the law. Thus, I'd like to ask if it would be possible to have Google's Legal Team take a closer look at this.

**Comment by jbuberel** [comment]
@SeMeKh This is due to legal restrictions outside the control of Google. For additional details, see https://epic.org/crypto/export_controls/itar.html

**Comment by remohammadi** [comment]
@jbuberel Based on [this old advisory](http://www.pillsburylaw.com/siteFiles/Publications/E756CBA4D5A9051815D7B8FB3107CA65.pdf) I think golang isn't restricted by EAR from publishing its binaries, and event its pure cryptography libraries, to the public.
