### ISSUE TITLE
cmd/compile: Escape analysis and liveness analysis do not interact well

### ISSUE THREAD

**Issue by encryptio** [golang/go#12397]
I'm writing some recursive code, and have been very careful to avoid allocations by being very nice to the escape analysis routines. However, I have some dead code in the source for debugging, whose body does cause escaping values if used (`fmt` and `panic` in my original code). The presence of the body of the debugging code, _even though it is dead and removed by liveness analysis_ causes the escape analysis pass to consider the state to escape, forcing a heap allocation.

Here's a simplified example:

```
package recursiveescapebug

const debugMode = false

func A() int {
        b := 0
        B(&b, 5)
        return b
}

func B(state *int, recursions int) {
        switch recursions {
        case 0:
        default:
                *state++

                if debugMode {
                        // this is dead code, removed by the optimizer.
                        // however, its presence causes the compiler to consider B's state argument to escape.
                        panic(state)
                }

                B(state, recursions-1)
        }
}
```

When compiling this:

```
$ go build -gcflags='-live -m'
# _/home/username/testthing
./recursiveescapebug.go:11: leaking param: state
./recursiveescapebug.go:6: moved to heap: b
./recursiveescapebug.go:7: &b escapes to heap
./recursiveescapebug.go:7: live at call to B: &b
./recursiveescapebug.go:11: live at entry to B: state
./recursiveescapebug.go:23: live at call to B: state
```

Without the dead debug code in the source code, I see the escape analysis properly determines that state does not escape.

Happens with Go 1.5 and on a development version as of `efeeee38` on x86_64/linux, but is likely not related to versions or platforms.

**Comment by minux** [comment]
It's because escape analysis is run before DCE (dead code elimination).
