### ISSUE TITLE
net: sendfile needs -lsendfile for external linker on Solaris

### ISSUE THREAD

**Issue by mamash** [golang/go#12390]
With Go 1.5.0 on SunOS/amd64 (namely SmartOS), packages employing the external linker and net/* packages (e.g. CouchBase or github.com/mongodb/mongo-tools) will fail due to an undefined 'sendfile' symbol.
 
The following patch (from pkgsrc's package for go-1.5.0) works around the problem:

https://github.com/jsonn/pkgsrc/blob/37075a88350da1870518cdd61bd6609bbf1c16c5/lang/go/patches/patch-src_net_sendfile__solaris.go

Steps to repeat:

```
git clone https://github.com/mongodb/mongo-tools
cd mongo-tools
. ./set_gopath.sh
mkdir bin
go build -o bin/mongoimport -tags sasl mongoimport/main/mongoimport.go
```

Output:

```
# command-line-arguments
/opt/local/go/pkg/tool/solaris_amd64/link: running gcc failed: exit status 1
Undefined                       first referenced
 symbol                             in file
sendfile                            /tmp/go-link-666650609/go.o
ld: fatal: symbol referencing errors. No output written to $WORK/command-line-arguments/_obj/exe/a.out
collect2: error: ld returned 1 exit status
```

**Comment by minux** [comment]
I'm wondering if cmd/link should automatically add -lxxx
given "cgo_import_dynamic libxxx.so"?

/cc @ianlancetaylor

**Comment by 4ad** [comment]
I don't understand why we need -lsendfile, but not, say, -lsocket.

**Comment by minux** [comment]
-lsocket is in net/cgo_solaris.go, I wonder if we should add -lsendfile
there.

**Comment by 4ad** [comment]
Sounds better.

**Comment by ianlancetaylor** [comment]
@minux cgo_import_dynamic is a directive for internal linking mode.  I'm not sure it makes sense for it to affect how the external linker is used.  Passing flags to the external linker seems more a job for cgo LDFLAGS or //go:cgo_ldflag.

**Comment by mamash** [comment]
Thanks, guys, confirming the problem to be fixed.

**Comment by binarycrusader** [comment]
For the record, libsocket, libnsl, and libsendfile may be filter libraries in a future release of Solaris -- typically such libraries are merged into libc.  So this change won't cause any problems, as the filter libraries will provide the necessary symbol compatibility, but is unnecessary for future releases:

https://blogs.oracle.com/rie/entry/shared_object_filters
http://docs.oracle.com/cd/E36784_01/html/E36857/chapter4-4.html
