### ISSUE TITLE
test: unreachable code in run.go.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#12394]
On latest `master` commit, [lines 120-137](https://github.com/golang/go/blob/805e56ef474a8abfc4ec4159bea0c1fb584e67ed/test/run.go#L120-L137) of `test/run.go` are:

```Go
status := "ok  "
errStr := ""
if _, isSkip := test.err.(skipError); isSkip {
	test.err = nil
	errStr = "unexpected skip for " + path.Join(test.dir, test.gofile) + ": " + errStr
	status = "FAIL"
}
if test.err != nil {
	status = "FAIL"
	errStr = test.err.Error()
}
if status == "FAIL" {
	failed = true
}
resCount[status]++
if status == "skip" && !*verbose && !*showSkips {
	continue
}
```

As far as I can tell, line 136 containing the `continue` keyword is unreachable code. The local variable `status` is declared on line 120, and can only ever contain values of `"ok  "` and `"FAIL"` before line 135 is reached which checks for `status == "skip"` `&&`ed with other booleans, which can never be true.

I'm guessing it meant to check the action rather than status? Something seems off, and I'm sure it'll be obvious to the person who wrote/refactored this code.

**Comment by shurcooL** [comment]
Based on the commit message of https://github.com/golang/go/commit/a55a5c8df3d8ced8f0399a523dc4508af1db5904, I am guessing that this the concept of skipped tests is legacy and meant to be removed, so this could be just some left over code that wasn't cleaned up after the action header migration.

**Comment by minux** [comment]
Yes, it supposed to check action.

**Comment by shurcooL** [comment]
Dug more in history, I see that it was not unreachable code in https://github.com/golang/go/commit/de8549dfd36bc46ca9c10903dad6e504e1444a86.

But https://github.com/golang/go/commit/e7173dfdfd1c74b1d301da9b6f295ef99b9cc11c removed the only possible case where `status` was being set to `"skip"`, causing it to be unreachable.

**Comment by josharian** [comment]
Long enough ago that my memory is fuzzy, but: e7173df removed the notion of it being ok to skip tests. The now dead code is meant to handle skipped-but-okay tests, of which there are now, so I believe that the whole if statement can be removed. It looks like it was simply an incomplete cleanup on my part.

**Comment by cespare** [comment]
@josharian thanks. Sent a CL

**Comment by josharian** [comment]
Thanks for the cc. :) Be sure to list me explicitly as a reviewer on the CL if you want my input. I'm on vacation mode for the indefinite future.
