### ISSUE TITLE
spec: Declaring variable in global scope

### ISSUE THREAD

**Issue by prateekgogia42** [golang/go#12398]
While declaring a new variable in global scope we have to use the following syntax:

var dummy string =  "test string"

However, this following syntax doesn't work:

dummy := "test string"

It works fine in a functions scope, is there any particular reason for this? 
go version go1.4.2 darwin/amd64

PS: Not sure where to ask this question, so asking at this place.

**Comment by mikioh** [comment]
> PS: Not sure where to ask this question, so asking at this place.

Really? I think the first page of issue writing displays the line "Please review the guidelines for contributing to this repository." and it refers to https://github.com/golang/go/blob/master/CONTRIBUTING.md.

**Comment by prateekgogia42** [comment]
@mikioh : Sorry, should have read it. Will be more careful.
Thanks

**Comment by minux** [comment]
Please ask questions like this on the golang-nuts mailing list.
The issue tracker is only for bugs, feature requests and
proposals.
