### ISSUE TITLE
go/types: cannot import package with source code but no installed archive

### ISSUE THREAD

**Issue by kr** [golang/go#12392]
Go version 1.5

### Summary

We've run into some behavior we didn't expect from go/types importing packages. If a package `p` has been imported (by some other package) and its source code is present but not installed (that is, there is no package archive such as `$GOROOT/pkg/darwin_amd64/p.a`) then Check returns an error saying it can't find the package.

We're not sure if this is intended behavior, but we found it surprising.

cc @tessr 

We've tried to produce a minimal test case:
https://github.com/kr/gotypesrepro

### Steps to reproduce

	1. git clone https://github.com/kr/gotypesrepro $GOPATH/src/p
	2. cd $GOPATH/src/p
	3. go run try.go # fails
	4. go install p
	5. go run try.go # now it works

### Expected output

	package testdata ("testdata")
	package testdata ("testdata")

### Actual output

	testdata/import.go:3:8: could not import p (can't find import: p)
	package testdata ("testdata")

**Comment by griesemer** [comment]
This is intended behavior and has been much discussed (<proper link here>). The type checker purely type-checks a package for which the corresponding package file ASTs are provided. It doesn't know about the build environment, source code, etc. It relies on importers (go/importer) for imported packages. The currently installed importers only support gc or gccgo compiled packages. There is no "source importer" yet.

**Comment by griesemer** [comment]
Duplicate of #11415.
