### ISSUE TITLE
x/tools/cmd/godoc/: golang.org/x/arch subrepo not fully intergrated

### ISSUE THREAD

**Issue by davecheney** [golang/go#12393]
The new arch subrepo has several missing pieces

- http://golang.org/x/arch returns 404
- go get golang.org/x/arch/... fails
- arch subrepo is not tested on the build dashboard.

**Comment by minux** [comment]
The list of subrepos is in x/tools/cmd/godoc/x.go. we need to change that
and redeploy golang.org.

**Comment by adg** [comment]
This should be fixed now. The builders will pick up the new arch sub-repo in time.

**Comment by davecheney** [comment]
Excellent. Thanks Andrew.
