### ISSUE TITLE
crypto/aes: add dedicated asm version of AES-GCM for Power/ARM64

### ISSUE THREAD

**Issue by matt2909** [golang/go#12408]
Add a complimentary dedicated asm version of AES-GCM for Power/ARM64 where accelerators for those algorithms exist in a similar form to amd64,

**Comment by drbo** [comment]
This is a security issue (timing attacks)

**Comment by gaillard** [comment]
Would be very interested in this too for arm64.

**Comment by bradfitz** [comment]
@gaillard, see https://golang.org/wiki/NoMeToo

**Comment by bradfitz** [comment]
@matt2909, you probably want separate bugs for power vs. arm64. They will be fixed separately.

**Comment by matt2909** [comment]
As suggested by @bradfitz I have closed this bug and opened separate bugs for ppc64 and arm64.

arm64 bug: https://github.com/golang/go/issues/18498
ppc64 bug: https://github.com/golang/go/issues/18499
