### ISSUE TITLE
net/http/pprof - protobuf definition

### ISSUE THREAD

**Issue by piotrkowalczuk** [golang/go#12402]
Hi, im looking for `.proto` file mentioned [here](https://github.com/golang/go/blob/master/src/cmd/pprof/internal/profile/profile.go#L5). I have checked in multiple places, including c++ version.

Any hint welcome.

**Comment by ianlancetaylor** [comment]
The issue tracker is for bug reports and TODO items.  Please ask questions on the golang-nuts mailing list.  Thanks.

See cmd/pprof/README.  I don't know whether the .proto file mentioned is externally available.  I also don't know that it is not externally available--I don't know anything about it.
