### ISSUE TITLE
cmd/compile: MOV $0, r to XOR r, r rewrite is unsafe

### ISSUE THREAD

**Issue by josharian** [golang/go#12405]
liblink rewrites `MOV $0, r` to `XOR r, r`. MOV does not impact flags, but XOR does. As a result, this rewrite is not generally safe. This was the source of a bug in the SSA branch (see CL 14042 and 14043). It could also impact hand-written assembly. It is an accident of the current backend codegen that it doesn't cause bugs now.

We should remove the liblink rewrite and generate `XOR r, r` directly if/when that is desired. For example, for the existing backend, this could become part of the peephole optimizer; we can update the existing handwritten assembly.

cc @bradfitz @tzneal @randall77

**Comment by rsc** [comment]
I am not convinced. "MOV" is a pseudo-operation in the Go assembler. It is NOT just one instruction. XOR is one possible implementation of that pseudo-operation. Therefore SSA should expect that MOV can affect flags.

**Comment by randall77** [comment]
Yes, that was our fix, marking MOVx as clobbering flags.  Even though most of the time it won't.
Meta-question - how do we know what is a pseudo-op and what isn't?

**Comment by rsc** [comment]
MOV is the main one. I know that's not terribly precise. Eventually we'll have a formal statement of all this that you could just look at.

**Comment by rsc** [comment]
Anyway, sounds like this got fixed.
