### ISSUE TITLE
encoding/xml: character encoding detection should be case insensitive

### ISSUE THREAD

**Issue by cGuille** [golang/go#12417]
Hello,

- *What version of Go are you using (go version)?* **go version go1.3.3 linux/amd64**
- *What operating system and processor architecture are you using?* **Debian Wheezy (Linux 3.16.0-44-generic x86_64)**
- *What did you do?* **I ran an app which parsed a third party XML file.**
- *What did you expect to see?* **The parsing should work and the data should be extracted from the file.**
- *What did you see instead?* **An error: "xml: encoding "Utf-8" declared but Decoder.CharsetReader is nil".**

As [discussed in the Google group](https://groups.google.com/forum/#!topic/golang-nuts/8LqvhPjwQcA), I encountered an issue while parsing an XML document claiming to be `Utf-8` encoded, so neither `UTF-8` nor `utf-8` [as expected by the encoding/xml library](https://github.com/golang/go/blob/9c04d00214cb836ddcf4b7b6b0c4b4e5c11bb957/src/encoding/xml/xml.go#L583).

[This document](http://www.w3.org/TR/2008/REC-xml-20081126/) specifies that "XML processors should match character encoding names in a case-insensitive way".

I plan to propose a patch doing just that, as soon as I install the golang dev tools (it is kind of my first meeting with Go).

About the implementation, would you just write a simple comparison such as `strings.ToUpper(enc) == "UTF-8"`, or would you prefer using something like [the charset lookup function](https://godoc.org/golang.org/x/net/html/charset#Lookup)?

Thanks.

**Comment by dullgiulio** [comment]
Could you try if https://go-review.googlesource.com/14084 does what you want?

**Comment by cGuille** [comment]
I confirm it does! I have spent an entire hour building everything from go to my app into a clean docker container. :D
When I checkout the commit before yours, I reproduce my issue ; when I checkout your commit, it works fine.
