### ISSUE TITLE
cmd/compile: "invalid variable name x in type switch", where x is a name of a constant

### ISSUE THREAD

**Issue by o948** [golang/go#12413]
The following program fails to build (http://play.golang.org/p/qrVKDN_MDR):

	package main

	const x = 42

	func main() {
		switch x := interface{}(nil).(type) {
		default:
			_ = x
		}
	}

with the error message:

	prog.go:6: invalid variable name x in type switch

**Comment by ianlancetaylor** [comment]
Compiler bug rejecting a valid program.  Works with gccgo.

**Comment by anthonycanino1** [comment]
Have an idea with what is wrong: Looks like x in the type switch grabs the const x symbol during parsing, which gives it the OLITERAL op that then errors in the type switch. Looking into a fix.
