### ISSUE TITLE
cmd/doc: issues related to vendor ambiguity

### ISSUE THREAD

**Issue by rsc** [golang/go#12423]
Test case:

	go get rsc.io/pdf
	go doc pdf.Text

I get:

	$ go doc pdf.Text
	package pdf // import "rsc.io/pdf"
	
	WARNING: package source is installed in "golang.org/x/arch/vendor/rsc.io/pdf"
	type Text struct {
		Font     string  // the font used
		FontSize float64 // the font size, in points (1/72 of an inch)
		X        float64 // the X coordinate, in points, increasing left to right
		Y        float64 // the Y coordinate, in points, increasing bottom to top
		W        float64 // the width of the text, in points
		S        string  // the actual UTF-8 text
	}
	
	    A Text represents a single piece of text drawn on a page.
	$

There are three issues.

First, import comments are no-ops in vendor source trees, so the WARNING should be omitted.

Second, the import statement on the first line should probably give the full path of the selected package (golang.org/x/arch/vendor/rsc.io/pdf). Even though that's not how a source file would import it, the expanded path is what the tools like "go list" show. Perhaps to avoid confusion the line could drop the "import", so not: 

	package pdf // import "golang.org/x/arch/vendor/rsc.io/pdf"

but instead:

	package pdf // golang.org/x/arch/vendor/rsc.io/pdf

Third, there should be some kind of prioritization that depends on where in the source tree "go doc" is run. If run in $GOPATH/src/golang.org/x/arch/x86, then absolutely that package is a good resolution for "go doc pdf.Text". But outside $GOPATH/src/golang.org/x/arch, that package is not importable, so if there is non-vendored copy or a closer vendored copy, that should be preferred. In my case, plain $GOPATH/src/rsc.io/pdf should take priority over the vendored arch copy, again possibly unless run inside the arch subtree.

**Comment by robpike** [comment]
I cannot reproduce the first problem. Not sure why:

```
% go get -d rsc.io/pdf
% go doc pdf.Text
package pdf // import "rsc.io/pdf"

type Text struct {
	Font     string  // the font used
	FontSize float64 // the font size, in points (1/72 of an inch)
	X        float64 // the X coordinate, in points, increasing left to right
	Y        float64 // the Y coordinate, in points, increasing bottom to top
	W        float64 // the width of the text, in points
	S        string  // the actual UTF-8 text
}
    A Text represents a single piece of text drawn on a page.
```

The vendoring issues are very unclear to me, and I think there are a number of other issues around tooling and vendoring that need to be resolved. I see no reason this needs to be done soon, so I will downgrade to Go1.6 from Go1.6Early and remove myself as assignee.

**Comment by robpike** [comment]
The reason I can't reproduce the WARNING is that the package is not installed in a vendored directory and I don't know why it is in your situation. So there likely is an issue here, and maybe all it takes to resolve is that the WARNING be prefixed by a check that there is no "/vendor/" in the actual path.

But also: I tried an example that _is_ in a vendor directory and it works fine:

```
% pwd
/Users/r/go/src/cmd/vendor/golang.org/x/arch/x86/x86asm
% go doc
package x86asm // import "cmd/vendor/golang.org/x/arch/x86/x86asm"

Package x86asm implements decoding of x86 machine code.

const AAA ...
const PrefixImplicit Prefix = 0x8000 ...
const AL ...
var ErrInvalidMode = errors.New("invalid x86 mode in Decode") ...
func GNUSyntax(inst Inst) string
func GoSyntax(inst Inst, pc uint64, symname func(uint64) (string, uint64)) string
func IntelSyntax(inst Inst) string
func Decode(src []byte, mode int) (inst Inst, err error)
type Arg interface { ... }
type Args [4]Arg
type Imm int64
type Inst struct { ... }
type Mem struct { ... }
type Op uint32
type Prefix uint16
type Prefixes [14]Prefix
type Reg uint8
type Rel int32
```

I believe the real issue here is indeed priority, but I am not sure what the right answer is.

**Comment by rsc** [comment]
The new rules fixed the immediate problem I was running into.
