### ISSUE TITLE
x/tools/mobile: gomobile bind -target ios: should produce framework bundles with module maps (Swift compat)

### ISSUE THREAD

**Issue by DrJosh9000** [golang/go#12422]
The .framework bundle that is produced works with Objective-C off-the-bat, but is missing module information that enables use from Swift. It's relatively easy to add a modulemap that exports everything in the header, which is all that's required.

Example for frobbing a .framework to add a modulemap: https://github.com/DrJosh9000/junk/blob/master/moduleiser.go

$ go version
go version go1.5 darwin/amd64
Mac OS X 10.10.5 "Yosemite"

What I did:
$ gomobile bind -target ios -o demo.framework demo
(package demo just contains ~the simple bind example)

What I expected:
Able to drop into an Xcode Swift project and use from Swift code ("import demo").

What I got:
Dropped into Xcode project, got "no module named demo" compile error, on "import demo" line.

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by rakyll** [comment]
As far I know (not quite familiar with Swift), Swift only allows making calls to C APIs. `gomobile bind` generates headers that contains types from Foundation framework such as NString, NSError, etc. Will these headers be usable from Swift? If not, there isn't much value generating module maps.

**Comment by DrJosh9000** [comment]
I'm not familiar with Swift either, but after I put the modulemap in the framework it just worked:
// Obj-C
FOUNDATION_EXPORT NSString* GoDemoFoo(NSString* s, NSString* t);
// Swift
let bar = demo.GoDemoFoo("baz", "qux")  // bar is a String

**Comment by rakyll** [comment]
Upon the addition of the module map, once I drag and drop the framework bundle to the Xcode, my module cannot be found when I  `import hello` -- hello is the module i build from x/mobile/example/bind/hello.

Are you modifying any of the Swift compiler settings or extending the search paths?

**Comment by DrJosh9000** [comment]
No compiler settings or search paths were changed. I noticed that calling both the Xcode project and the framework the same module name (e.g. "hello") causes the module not found error. 
Past that, with Xcode 7 I'm now getting a linker error (ld: framework not found hellodemo). Haven't figured that one out yet. ¯\_(ツ)_/¯

**Comment by rakyll** [comment]
I was able to achieve the behavior in Xcode 6.3 with a slightly different modulemap file, mailed https://go-review.googlesource.com/#/c/15044/.
