### ISSUE TITLE
x/build/cmd/watcher: mirror other repos

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12433]
The last commit in https://github.com/golang/proposal is from Aug 11, while https://go.googlesource.com/proposal/ shows many more commits, the last being from Aug 31.

cc @adg

**Comment by ianlancetaylor** [comment]
CC @adg @rsc

**Comment by bradfitz** [comment]
Normally we'd just add "proposal" to x/build/app/build/dash.go which is what the watcher's syncer uses, but there might be reasons it's not declared there, since that would also make it try to build those subrepos probably.

Probably the syncer needs a special case for this code-less subrepo.

**Comment by adg** [comment]
Russ kicked the cron job, so the proposal repo is in good shape now. Renaming this issue to be about handing this task over to the builder infrastructure.

**Comment by adg** [comment]
It's not just the proposal repo. There's oauth2 and others that need to be sync'd, but they also don't appear on the dashboard. I foolishly tied the mirroring code to the repos that appear on the dashboard. :-/

Will fix.

**Comment by adg** [comment]
> I foolishly tied the mirroring code to the repos that appear on the dashboard. :-/

This isn't true anymore. The repos should be sync'd automagically now.
