### ISSUE TITLE
x/mobile: Is it support the "res" subdirectory copied into the output?

### ISSUE THREAD

**Issue by DoraemonYu** [golang/go#12430]
o(∩_∩)o Hello,everyone.
I am a new developer to use gomobile. I hope that I could get the answer here.

I build the example successfully and these can run okay.
However,when I try to change the default application icon,I get the problem.
I create the subdirectory named "res/drawable" ,put the ic_launcher.png into it.Then, modify AndroidManifest.xml :
```
<application android:label="DebugApp"  
             android:icon="@drawable/ic_launcher" >
  ...others...
</application>
```

After build, I use 7z to unzip the apk file , then found that the "res" is not copied to output.
YES,the problem is Here.

When I get help from `"gomobile build -help"`,I can saw these:
`"If the package directory contains an assets subdirectory, its contents are copied into the output."`
But,the document above is not mention the "RES" subdirectory.

After look up googing and GoDoc, I really have no idea how to include the "res" subdirectory and generate resources.arsc.
So,is anyone get the answer? Or, will the gomobile project support this in the future ?

Thank you.
Waiting for your reply.

**Comment by ianlancetaylor** [comment]
We use the issue tracker for bug reports and TODO items.  Please ask questions on the golang-nuts mailing list.  Thanks.

I don't know the answer to your question.

**Comment by DoraemonYu** [comment]
o(∩_∩)o  Okay. Thank you as well.

**Comment by DoraemonYu** [comment]
Hello everyone  :)
The topic is move to the golang-nuts,the link is follow : 
https://groups.google.com/forum/#!topic/golang-nuts/gLjPkZm-e5Q
If you are interest in this problem, join in our discussion please.
