### ISSUE TITLE
encoding/json: Inconsistent spelling of unmarshaling/unmarshalling.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#12431]
On lastest `master` commit, in [`encoding/json/decode.go`](https://github.com/golang/go/blob/9c514e149c1d986c404460121c1a5fc01ab8356c/src/encoding/json/decode.go) file, there are two variations of spelling of the same word:

```Go
var spellingOccurrences = map[string]int{
	"unmarshaling":  2,
	"unmarshalling": 1,
}
```

It can be made better by having a consistent spelling, making it easier to find out which is the canonical spelling.

**Edit:** Including test files and "marshaling"/"marshalling", the count goes to 8 and 3, respectively.

**Comment by bradfitz** [comment]
More in https://go-review.googlesource.com/c/go/+/172457
