### ISSUE TITLE
x/tools/refactor/rename: scans entire workspace when renaming internal symbol

### ISSUE THREAD

**Issue by osocurioso** [golang/go#12439]
When renaming a symbol in an internal package, gorename finds and reports buggy packages outside the internal tree:

```
$ gorename -dryrun -from '"cmd/compile/internal/gc".Node' -to Qux
While scanning Go workspace:
Package "code.google.com/p/draw2d/draw2d/curve": found packages draw2d (arc.go) and curve (cubic_float64.go) in /gopath/src/code.google.com/p/draw2d/draw2d/curve.
Package "github.com/banthar/gl/examples/glfw": found packages glfw (glfw.go) and main (main.go) in /gopath/src/github.com/banthar/gl/examples/glfw.
```

Scanning the entire workspace seems unnecessary in this case, since symbols in internal packages cannot be imported outside the internal tree.

go version:
```
go version devel +e92d0d8 Tue Sep 1 16:28:49 2015 +0000 linux/amd64
```

**Comment by alandonovan** [comment]
Because of Go's embedding mechanism, renaming symbols within internal packages can have effects that are visible to packages outside the "internal" subtree.  So, this counterintuitive scan is required.

The oracle does need to be made more robust when scanning the entire workspace, though.
