### ISSUE TITLE
dev.ssa: encoding/gob test failure

### ISSUE THREAD

**Issue by tzneal** [golang/go#12441]
I’m not sure of the best place to fix this.

This code:
```
func f_ssa(a float64, b bool) int {
        switch {
        }
        if a != 0 || b {
                return 1
        }
        return 2
}
```

generates the following:
```
...
v32     00006 (/tmp/c.go:3)     MOVQ    $0, AX
v27     00007 (/tmp/c.go:3)     MOVB    16(SP), CX
v24     00008 (/tmp/c.go:3)     MOVSD   8(SP), X0
v9      00009 (/tmp/c.go:3)     MOVQ    AX, 24(SP)
v11     00010 (/tmp/c.go:6)     MOVSD   $(0.0), X1
v16     00011 (/tmp/c.go:6)     UCOMISD X1, X0
v12     00012 (/tmp/c.go:6)     SETNE   DX
v12     00013 (/tmp/c.go:6)     SETPS   AX
v12     00014 (/tmp/c.go:6)     ORQ     AX, DX
b3      00015 (/tmp/c.go:6)     JNE     17
b3      00016 (/tmp/c.go:6)     JPC     25
...
```

Calling this with f_ssa(0, true) should return 1, but it’s returning 2.

The OR in v12 clears the parity flag, causing the JPC to be taken when it shouldn’t be.  The OR is inserted manually when generating the ssa.OpAMD64SETNEF value.

This is the second time in a week where code insertion/rewrite outside of ssa causes subtle bugs :)

@dr2chase @randall77 @josharian

**Comment by randall77** [comment]
Fixed with https://go-review.googlesource.com/#/c/14180/
