### ISSUE TITLE
time: go 1.5  time.Format layout  "5" handled as "05"

### ISSUE THREAD

**Issue by foubarre** [golang/go#12440]
go version go1.5 linux/amd64
c.f. http://play.golang.org/p/hgH-YaTDjR
formatting seconds using "5" layout prefix single digit values with "0" as if layout "05" was used

**Comment by stemar94** [comment]
I commited a fix for that:
https://go-review.googlesource.com/#/c/14171/

**Comment by stemar94** [comment]
I abandoned cl/14171, and now cl/14178 is the one waiting to get through the code-review.

**Comment by foubarre** [comment]
thanks!
do you know which go release it will go into?

**Comment by stemar94** [comment]
CC @robpike

**Comment by stemar94** [comment]
@foubarre 
It is fixed and merged, but I do not know in which release it will occur. Probably 1.6

**Comment by foubarre** [comment]
This bug is a regression compared to 1.4, if it doesn't make it to 1.5.x we'll need to either:
- wait for 1.6
- introduce the same regression in our product
- do convoluted workarounds instead of using vanilla time.Format

**Comment by stemar94** [comment]
Bug comes with
d5ef69814204f1bf8bee75bc89efcbcb33a64606
so it is indeed introduced with go1.5.
@robpike This issue needs a labeling, 1.5.2 could apply for a newly introduced bug?
@foubarre We just missed 1.5.1 and 1.5.2 would be for 31.Oct. So if you don't have the possibility to checkout go1.5.1 and fetch this single fix you have try a workaround.

**Comment by ianlancetaylor** [comment]
Our goal for point releases is to only patch critical bugs for which there is no workaround.  Unfortunately I don't think this issue rises to that level.

**Comment by stemar94** [comment]
@ianlancetaylor 
How does it normally work, if no label is set? Will these fixes be automatically added for the next 1.X release?

**Comment by ianlancetaylor** [comment]
Yes, anything committed to the tree now will be in the 1.6 release.

**Comment by foubarre** [comment]
Working on commercial software we are contractually bound to fix regressions, however mundane they might seem.
Only workaround I can think of is to copy my own version of time/format.go including the fix.
Concern with waiting on a major release to get minor regressions fixed is to run into other newly introduced regressions...  (though I understand golang project has its own concerns & constraints which may not include catering to all my specific needs ;-))

**Comment by stemar94** [comment]
https://gist.github.com/21ebfbf673ea783b9205.git
Thats all you need to change.
