### ISSUE TITLE
runtime: Windows AMD64 calling convention violation in usleep2

### ISSUE THREAD

**Issue by jstarks** [golang/go#12444]
There's a Windows calling convention violation in usleep2 in runtime/sys_windows_amd64.s.

This issue was partially fixed by #8174 runtime: not aligned stack before call into NtWaitForSingleObject in usleep2, but the fix was insufficient to satisfy Windows AMD64 calling conventions. There needs to be 32 bytes of stack space allocated by the caller in order to have home locations for four parameters (even if there are fewer than four parameters). And of course these bytes can be immediately trashed by the callee, so be careful where you store ptime and the original stack pointer. See https://msdn.microsoft.com/en-us/library/ew5tede7.aspx.

This is causing failures on checked (debug) builds of Windows where NtWaitForSingleObject copies its parameters to their home locations, causing data to get overwritten on usleep2's stack, causing an AV. There's no guarantee that Windows won't start doing this in release builds in the future; for now it's just making it difficult to test development versions of Windows while using programs written in go.

@alexbrainman

**Comment by bradfitz** [comment]
Thanks for the report, @jstarks!

**Comment by alexbrainman** [comment]
@rsc wrote that (original code). Apparently he does not make mistakes https://imgflip.com/i/gh4xs

I will have a look. Thank you.

Alex

**Comment by 4ad** [comment]
We should run a builder on a checked build of Windows.

**Comment by bradfitz** [comment]
@4ad, probably. @jstarks, how do we run a checked build of Windows? Is one available on Azure? I don't know how to do it on GCE or EC2.

**Comment by 4ad** [comment]
Checked builds of Windows are available through MSDN (so they cost big money). They can be "installed" in the cloud, but I don't know (I'm not aware of) anyone offering turn-key checked images.

Checked kernels and HALs that can be installed in retail Windows builds are available for free, but we don't buy much by using those, we're more interested in the checked build of the system libraries.

**Comment by jstarks** [comment]
I'll look into whether we can provide a chk build on Azure or perhaps the chk version of ntdll and a few other system libraries. Do you need this as a one-off, or did you want to run tests regularly on chk?

**Comment by bradfitz** [comment]
Regularly.

**Comment by alexbrainman** [comment]
@jstarks please try that https://go-review.googlesource.com/14282

Thank you.

Alex
