### ISSUE TITLE
cmd/compile: document go:systemstack comment

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#12454]
Now that the runtime has been entirely converted from C to Go, I believe we can remove the go:systemstack comment.  It follows that we can remove the Cfunc field from Lsym, remove all the uses of it, and remove the morestackc function.

I see exactly one remaining use of go:systemstack, on persistentalloc1 in runtime/malloc.go.

CC @randall77 in case you disagree.

**Comment by randall77** [comment]
I don't think we should get rid of this feature.  It is nice to annotate and check that routines that should not run on a normal Go stack don't in fact do that.  We don't have any C code that needs this checking anymore, but there is Go code (and assembly, probably) that does.  We should probably be using go:systemstack in other places, for example in all the stack copying code, signal handlers, etc.

Maybe a rename of Cfunc and morestackc is in order, though.

**Comment by ianlancetaylor** [comment]
SGTM.  I've changed this issue to call for documenting it, presumably in cmd/compile/doc.go.

**Comment by minux** [comment]
I think we can just restrict it to package runtime, and then we
don't have the need to document it (like go:nowritebarrier).

**Comment by ianlancetaylor** [comment]
That works for me too.
