### ISSUE TITLE
cmd/asm: arm assembler "illegal combination" for CMPF in Go 1.5

### ISSUE THREAD

**Issue by samuel** [golang/go#12458]
It's likely something I'm doing wrong that just happened to work previously, but some ARM assembly that 
worked fine in Go 1.4.2 (`go version go1.4.2 darwin/amd64`) is giving an error in Go 1.5 (`go version go1.5 darwin/amd64`)

The instruction `CMPF F4, F1` at https://github.com/samuel/go-dsp/blob/master/dsp/math32_arm.s#L246 produced the follow in Go 1.4.2 running `GOOS=linux GOARCH=arm GOARM=7 go build`

```
vcmpe.f32  s2, s8
vmrs       APSR_nzcv, fpscr
```

In Go 1.5 I get during compile

```
asm: illegal combination 00128 (/Users/samuel/Dropbox/Workspace/go/src/github.com/samuel/go-dsp/dsp/math32_arm.s:246)	CMPF	F4, F1; PSR NONE PSR, 11 11
```

**Comment by minux** [comment]
The problem is that cmd/internal/obj/arm only handles CMPF
instruction when the 2nd register is in Prog.Reg field, not in To,
but cmd/asm puts that into Prog.To.

Should we modify cmd/asm to add a special case or add another
rule to cmd/internal/obj/arm?

/cc @robpike

**Comment by robpike** [comment]
To me, it looks like a special case is needed in the assembler. The old 5a code explicitly put the second arg in a register, but the new one does not. This applies only to CMPF and CMPD, if I am reading the old code correctly.

**Comment by broady** [comment]
This doesn't cherry-pick cleanly into the 1.5.1 release branch.

Rob, can you take a look?
