### ISSUE TITLE
net/http: consider reusing buffers replacing io.Copy calls with io.CopyBuffer

### ISSUE THREAD

**Issue by artyom** [golang/go#12455]
As been shown in #12450 by crude patch to make io.Copy reuse its underlying 32k buffer(s) workloads intensively (ab)using net/http can see a significant reduce in GC pressure. Since changes to io.Copy has [already been proposed and rejected](https://github.com/golang/go/issues/5509), I'd like to discuss the prospect of replacing at least some of the io.Copy calls in net/http by io.CopyBuffer with reused byte slices.

The net/http uses io.Copy the most in standard library, and I believe updating it to use recently introduced io.CopyBuffer is worth doing.

```
go (master) $ find src/net/http -name \*.go -type f ! -name \*_test.go -exec cat '{}' \+ | grep -wc io.Copy
19
```

At least some of those calls are not subject to usual io.ReaderFrom/io.WriterTo optimizations.

I'm ready to implement changes in the upcoming days and propose a CL.

**Comment by bradfitz** [comment]
I don't have an opinion until I see a concrete proposal. Which io.Copy calls?

**Comment by artyom** [comment]
@bradfitz one candidate is [fallback path][1] in net/http.response.ReadFrom, another is [io.Copy used on liveSwitchReader][2] when one makes use of http.CloseNotifier — httputil.ReverseProxy would gain most benefit from this.

```
benchmark                    old ns/op     new ns/op     delta
BenchmarkCloseNotified-4     309569        273466        -11.66%

benchmark                    old allocs     new allocs     delta
BenchmarkCloseNotified-4     50             48             -4.00%

benchmark                    old bytes     new bytes     delta
BenchmarkCloseNotified-4     36006         3089          -91.42%
```

[1]: https://github.com/golang/go/blob/b733234856879fa2df787649fce6e46adf7a6663/src/net/http/server.go#L426
[2]: https://github.com/golang/go/blob/b733234856879fa2df787649fce6e46adf7a6663/src/net/http/server.go#L182

**Comment by artyom** [comment]
Ref: https://go-review.googlesource.com/14177
