### ISSUE TITLE
AUTHORS: missing Oracle

### ISSUE THREAD

**Issue by 4ad** [golang/go#12452]
The AUTHORS file seems to be missing some corporate sponsors. E.g. Oracle is not there.

Canonical also is not there, although I don't know if it should be there or not.

**Comment by ianlancetaylor** [comment]
@bradfitz did your generation of the CONTRIBUTORS file do anything for corporate AUTHORS?

**Comment by bradfitz** [comment]
My script adds corporations, if the email address in git/Gerrit maps to a corporate CLA. @4ad, which commits or email addresses in question do not have corporate attribution?

**Comment by 4ad** [comment]
> My script adds corporations, if the email address in git/Gerrit maps to a corporate CLA.

That logic is not correct, at least to my understanding.

This is from a private discussion with @rsc:

>> It is unclear whether I should use my corporate e-mail or my personal
>> e-mail for corporate changes [...]
> 
> The Go project doesn't have a preference which email address you
> use. It is fine to use your personal email for all, or vice versa.
> [...] as long as they (corporations) have completed a CLA with us
> and put your name on it, we're good. And there's no need to identify
> each CL as one copyright holder or the other.

**Comment by bradfitz** [comment]
Maybe that was true before Gerrit started enforcing the CLA.

Don't submit code to Gerrit (even for review) using your personal email address which is owned by corporations, until that corporation is in our AUTHORS files.

Which companies have you worked for which we now have to retroactively add to AUTHORS? I'll verify they have CLAs on file.

**Comment by 4ad** [comment]
FWIW, this discussion was after the move to Gerrit.

I already mentioned, Oracle.

**Comment by bradfitz** [comment]
You also mentioned Canonical. Does Canonical own any of your contributions?

**Comment by 4ad** [comment]
No, Canonical does not own any of my contributions.

However, many Canonical employees (@davecheney, @mwhudson) made significant contributions to Go. It made sense to question whether they should be there or not. I have no idea what the arrangement is there, it just seemed sensible to ask.

**Comment by bradfitz** [comment]
Can you clarify which commits or directories or topics of commits written by `Aram Hăvărneanu <*@mgk.ro>` are owned by Oracle?

**Comment by bradfitz** [comment]
Presumably stuff about the Solaris port? e.g. db8d5b7608fc (one example of many, but the only one which mentions Oracle by name in the commit message)

**Comment by binarycrusader** [comment]
```Don't submit code to Gerrit (even for review) using your personal email address which is owned by corporations, until that corporation is in our AUTHORS files.```

There is nothing about waiting until that corporation is in the AUTHORS file on the contribution guidelines page. In fact, it states that `These files will be periodically updated based on the commit logs.`: http://golang.org/doc/contribute.html

```Can you clarify which commits or directories or topics of commits written by Aram Hăvărneanu <*@mgk.ro> are owned by Oracle?```

I will let Aram confirm his own, but all of mine were submitted using an oracle.com email address and for which a CLA was in place at the time they were submitted (Gerrit won't let you upload review until CLA is in place, I know this from experience).  But to be explicit those are:

From golang/go:
```
commit 4f74de1e4d8ac8382d866d9918059144218da069
Author: Shawn Walker-Salas <shawn.walker@...>
Date:   Wed Aug 26 15:24:41 2015 -0700
cmd/go: fix Go buildid reading on Solaris

commit d9e3d16796927ae2c5721cdff855ddb07a903d78
Author: Shawn Walker-Salas <shawn.walker@...>
Date:   Thu Jul 30 13:32:55 2015 -0700
runtime, syscall: remove unused bits from Solaris implementation
```

From x/sys/unix:
```
commit 339fc2ca4bac09124d756f897fb8698e26b5a844
Date:   Thu Aug 6 19:57:13 2015 -0700
Author: Shawn Walker-Salas <shawn.walker@...>
unix: update to use direct linking on Solaris
```

**Comment by 4ad** [comment]
No good deed goes unpunished.

	a77fcb3 net: fix comment in sendFile
	b0e71f4 net: link with networking libraries when net package is in use
	92e959a syscall, net: use sendfile on Solaris
	db8d5b7 net: try to fix setKeepAlivePeriod on Solaris
	fe5ef5c runtime, syscall: link Solaris binaries directly instead of using dlopen/dlsym
	2b90c3e go/build: enable cgo by default on solaris/amd64
	2d18ab7 doc/progs: disable cgo tests that use C.Stdout on Solaris
	2230e9d misc/cgo: add various solaris build lines
	649c7b6 net: add cgo support for Solaris
	24396da os/user: small fixes for Solaris
	121489c runtime/cgo: add cgo support for solaris/amd64
	83b25d9 cmd/ld: make .rela and .rela.plt sections contiguous
	c94f1f7 runtime: always load address of libcFunc on Solaris
	e481aac cmd/6l: use .plt instead of .got on Solaris

**Comment by bradfitz** [comment]
@binarycrusader, your commits are fine (which happened right after we last ran the script for Go 1.5's release). Your commits (your email) are associated with Oracle's CLA. If I re-ran the script today, Oracle would be included in the list based on your commits. The script works.

But @4ad, how would my A+C update script ever know that Oracle owned your copyright for commits coming from your personal email address?

I'm not sure why @rsc gave you that advice, or what the context was. I will work with @adg and @ianlancetaylor and others to update the docs to make this more clear.

**Comment by 4ad** [comment]
This advice was confirmed, and repeated in a subsequent e-mail from @rsc.

> You can add [the Oracle] account using one of the menus on the left,
> and then you'll be able to log in with that email address or your
> current one (they'll be considered the same) and you should be able
> to use either in your committer lines.
