### ISSUE TITLE
tour: incorrect method name

### ISSUE THREAD

**Issue by EmRa228** [golang/go#12464]
Context: http://tour.golang.org/methods/1

incorrect method name:
func (v *Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

*** this not an Abs function.

**Comment by EmRa228** [comment]
repeat this in "http://tour.golang.org/methods/3" too.

**Comment by adg** [comment]
It absolutely is. It computes the magnitude of the vector.
