### ISSUE TITLE
tour: make test better

### ISSUE THREAD

**Issue by EmRa228** [golang/go#12463]
Context: http://tour.golang.org/moretypes/19

Hi, I used "strings.Split" instead of "strings.Fields" and it's work.
It's better to add a sentence with more spaces (like: "    hello    word    ") to avoid use "strings.Split".

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
I would imagine that it's fine that http://tour.golang.org/moretypes/19 would pass with either `strings.Fields` or `strings.Split`. The reference to `strings.Fields` is a hint only, not a requirement.

**Comment by adg** [comment]
Indeed. It should check the programmer implemented the correct thing; not that they used a specific tool to do so. Let us know if we're misinterpreting this.
