### ISSUE TITLE
math/rand: default Source safe for concurrent use

### ISSUE THREAD

**Issue by awilliams** [golang/go#12471]
The `math/rand` documentation states:
> The default Source is safe for concurrent use by multiple goroutines.

This confused me because I thought the "default Source" referred to Source returned by the NewSource function. Instead, it refers to the protected internal Source used by the top-level functions.

* [Introductory Commit](https://github.com/golang/go/commit/e97c870692aa80feabd2e22c191476220fc1281f)
* [Source](https://github.com/golang/go/blob/release-branch.go1.5/src/math/rand/rand.go#L11)

**Comment by bradfitz** [comment]
Agreed. We should clarify that the Source (internally: rngSource) returned by NewSource is not safe for concurrent use.

**Comment by minux** [comment]
I think the docs about default Source is pretty clear if you read it in
full.

```
Top-level functions, such as Float64 and Int, use a default shared Source
that produces a deterministic sequence of values each time a program is
run. Use the Seed function to initialize the default Source if different
behavior
is required for each run. The default Source is safe for concurrent use by
multiple goroutines.
```

It explicitly mentions the default Source is the one used by the top-level
functions.

Following Go documentation convention, anything not explicitly
documented for concurrency safety is not safe for concurrent use.
The NewSource doesn't say Source is safe for concurrent use, so
it's not.

**Comment by bradfitz** [comment]
True. Yeah, there's not really anything to do here.

Feel free to re-open if you disagree.
