### ISSUE TITLE
x/mobile/bind: support exported const and vars.

### ISSUE THREAD

**Issue by hyangah** [golang/go#12475]
As long as the const and var's type is currently supported types.

For variables, maybe provide getter/setter functions. (Avoiding name conflicts)

For const numeric/string and byte slice types, we can create constants in the foreign language.
For const struct/interface types, we will need getter/setter like in variables, so the actual instance remains in the go side.

Const errors seem complicated.

/cc @crawshaw

**Comment by crawshaw** [comment]
From the spec: "There are boolean constants, rune constants, integer constants, floating-point constants, complex constants, and string constants."

So no need to worry about structs, interfaces, errors. Those are all variables and can use getters and setters.

**Comment by scisci** [comment]
Just to clarify, I was hoping all of the exported constants from my library would be available in IOS/Android. I tend to do a bunch of:
```
const SomePublicConstant = "some public contant"
```
Is there another way for me to set this up so it works now?

**Comment by crawshaw** [comment]
@scisci this issue is a feature request. We will implement it soon, but it doesn't work yet.

For now, you could create a function that returns your constants: func Const(name string) string { ... }

**Comment by eliasnaur** [comment]
I believe this is fixed (a long time ago). Gomobile supports consts and vars now.
