### ISSUE TITLE
tour: Strange results with appending to slice...

### ISSUE THREAD

**Issue by PierreVannier** [golang/go#12477]
Context: https://tour.golang.org/moretypes/11

I typed the exact code in my editor and didn't get the result the go tour gives....
Here's the output on my install of Go :
```
a len=0 cap=0 []
a len=1 cap=1 [0]
a len=2 cap=2 [0 1]
a len=5 cap=6 [0 1 2 3 4]
```
Here's the go tour output with the same code :
```
a len=0 cap=0 []
a len=1 cap=2 [0]
a len=2 cap=2 [0 1]
a len=5 cap=8 [0 1 2 3 4]
```

Finally, here's the code:
```
package main

import "fmt"

func main() {
	var a []int
	printSlice("a", a)

	// append works on nil slices.
	a = append(a, 0)
	printSlice("a", a)

	// the slice grows as needed.
	a = append(a, 1)
	printSlice("a", a)

	// we can add more than one element at a time.
	a = append(a, 2, 3, 4)
	printSlice("a", a)
}

func printSlice(s string, x []int) {
	fmt.Printf("%s len=%d cap=%d %v\n",
		s, len(x), cap(x), x)
}
```

**Comment by ianlancetaylor** [comment]
This is not a bug.  The exact way that append affects the capacity of the returned slice can vary between Go releases.  The contents and length of the slice must match.  The capacity need not.

**Comment by randall77** [comment]
I believe the effect you are observing is because int is 64 bits on your local implementation and 32 bits on the tour.

**Comment by PierreVannier** [comment]
:+1:  Thanks for the feedback @ianlancetaylor and sorry for the newbie question :-)
