### ISSUE TITLE
os/signal: Notify for SIGUSR2 from the same proc inside a goroutine doesn't work

### ISSUE THREAD

**Issue by willfaught** [golang/go#12484]
A process can't use os/signal.Notify inside a goroutine to signal itself with SIGUSR2.

Works as expected (outside the goroutine):

    func main() {
    	var c = make(chan os.Signal, 1)
    	signal.Notify(c) // outside the goroutine
    
    	var done = make(chan struct{})
    	go func() {
    		fmt.Println(<-c)
    		done <- struct{}{}
    	}()
    	if err := syscall.Kill(os.Getpid(), syscall.SIGUSR2); err != nil {
    		panic(err)
    	}
    	<-done
    }

Doesn't work as expected (inside the goroutine):

    func main() {
    	var done = make(chan struct{})
    	go func() {
    		var c = make(chan os.Signal, 1)
    		signal.Notify(c) // inside the goroutine
    		
    		fmt.Println(<-c)
    		done <- struct{}{}
    	}()
    	if err := syscall.Kill(os.Getpid(), syscall.SIGUSR2); err != nil {
    		panic(err)
    	}
    	<-done
    }

Expected: Doesn't hang
Actual: Hangs

The Notify documentation doesn't say it has to be called in the main goroutine.

**Comment by stemar94** [comment]
Beware of race conditions...

```go
func main() {
    var done = make(chan struct{})
    var done2 = make(chan struct{})
    go func() {
        var c = make(chan os.Signal, 1)
        signal.Notify(c) // inside the goroutine
        done2 <- struct{}{} //signal registration
        fmt.Println(<-c)
        done <- struct{}{}
    }()
    <-done2  //wait for registration
    if err := syscall.Kill(os.Getpid(), syscall.SIGUSR2); err != nil {
        panic(err)
    }
    <-done
}
```

Marvin

**Comment by willfaught** [comment]
Ouch, didn't see it. Thanks!
