### ISSUE TITLE
appengine/aetest: lack of StronglyConsistentDatastore flag in new packages

### ISSUE THREAD

**Issue by PSG-Luna** [golang/go#12499]
The StronglyConsistentDatastore flag is no longer available in google.golang.org/appengine/aetest, while it was in appengine/aetest

This causes tests that rely on a strongly consistent datastore to fail, for us, this is pretty much every single one of our tests.

/cc @okdave, @jbuberel, @corollax

**Comment by okdave** [comment]
Fixed by golang/appengine@302bbefe9d
