### ISSUE TITLE
x/sys/windows/registry: Remove arbitrary string limit from setStringValue

### ISSUE THREAD

**Issue by folbricht** [golang/go#12493]
`setStringValue` in https://github.com/golang/sys/blob/master/windows/registry/value.go enforces a max string size of 1<<10 which is arbitrary (on some Windows versions there is no limit enforced, see https://msdn.microsoft.com/en-us/library/windows/desktop/ms724872(v=vs.85).aspx). If the string is longer than that, the current function triggers `slice bounds out of range`.

Current implementation:
```go
func (k Key) setStringValue(name string, valtype uint32, value string) error {
	v, err := syscall.UTF16FromString(value)
	if err != nil {
		return err
	}
	buf := (*[1 << 10]byte)(unsafe.Pointer(&v[0]))[:len(v)*2]
	return k.setValue(name, valtype, buf)
}
```

I propose using a byte buffer to do the `[]uint16` to `[]byte`  conversion, removing the string limit.

```go
func (k Key) setStringValue(name string, valtype uint32, value string) error {
	v, err := syscall.UTF16FromString(value)
	if err != nil {
		return err
	}
	buf := new(bytes.Buffer)
	buf.Grow(len(v)*2)
	binary.Write(buf, binary.LittleEndian, v)
	return k.setValue(name, valtype, buf.Bytes())
}
```

**Comment by ianlancetaylor** [comment]
Just change the 1 << 10 to 1 << 30.  That number doesn't matter, as long as it is larger than len(v)*2.

**Comment by alexbrainman** [comment]
Try this https://go-review.googlesource.com/14287

Alex
