### ISSUE TITLE
##### Testing packages is failing on Amazon Linux AMI release 2015.03

### ISSUE THREAD

**Issue by kamoljan** [golang/go#12495]
Here error output of `./all.bash`

...
ok  	regexp	0.220s
ok  	regexp/syntax	0.541s
panic: test timed out after 3m0s

goroutine 22546 [running]:
testing.startAlarm.func1()
	/home/kamol/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/home/kamol/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, locked to thread]:
testing.RunTests(0x6d7880, 0x7b0720, 0xa1, 0xa1, 0x5ce001)
	/home/kamol/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200fbef8, 0x4d2491)
	/home/kamol/go/src/testing/testing.go:494 +0x70
main.main()
	runtime/_test/_testmain.go:862 +0x116

goroutine 22543 [syscall]:
syscall.Syscall6(0x3d, 0x4786, 0xc82003e894, 0x0, 0xc8204902d0, 0x0, 0x0, 0xc82003e868, 0xc82003e870, 0xc82003e860)
	/home/kamol/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x4786, 0xc82003e894, 0x0, 0xc8204902d0, 0x90, 0x0, 0x0)
	/home/kamol/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
syscall.Wait4(0x4786, 0xc82003e8dc, 0x0, 0xc8204902d0, 0xc820028058, 0x0, 0x0)
	/home/kamol/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc82000e920, 0x33, 0x0, 0x0)
	/home/kamol/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc82000e920, 0x0, 0x0, 0x0)
	/home/kamol/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc82056c000, 0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:380 +0x211
os/exec.(*Cmd).Run(0xc82056c000, 0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:258 +0x64
os/exec.(*Cmd).CombinedOutput(0xc82056c000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:424 +0x310
runtime_test.executeTest(0xc820490090, 0x6db740, 0x8a, 0x0, 0x0, 0xc82003ef40, 0x2, 0x2, 0x0, 0x0)
	/home/kamol/go/src/runtime/crash_test.go:83 +0xe81
runtime_test.TestCgoExternalThreadPanic(0xc820490090)
	/home/kamol/go/src/runtime/crash_cgo_test.go:61 +0xf9
testing.tRunner(0xc820490090, 0x7b0918)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 22545 [syscall]:
syscall.Syscall(0x0, 0x4, 0xc8204bc200, 0x200, 0x0, 0x5fd, 0x4103c9)
	/home/kamol/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc8204bc200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/kamol/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x4, 0xc8204bc200, 0x200, 0x200, 0xc820021ce8, 0x0, 0x0)
	/home/kamol/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820028050, 0xc8204bc200, 0x200, 0x200, 0xc8204bc200, 0x0, 0x0)
	/home/kamol/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820028050, 0xc8204bc200, 0x200, 0x200, 0x1, 0x0, 0x0)
	/home/kamol/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc8200440e0, 0x7f6964322e40, 0xc820028050, 0x0, 0x0, 0x0)
	/home/kamol/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x7f6964322df0, 0xc8200440e0, 0x7f6964322e40, 0xc820028050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:375 +0x180
io.Copy(0x7f6964322df0, 0xc8200440e0, 0x7f6964322e40, 0xc820028050, 0xc800000001, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:232 +0x8b
os/exec.(*Cmd).Start.func1(0xc82056c000, 0xc82000e5c0)
	/home/kamol/go/src/os/exec/exec.go:340 +0x1d
created by os/exec.(*Cmd).Start
	/home/kamol/go/src/os/exec/exec.go:341 +0x96d
FAIL	runtime	180.026s
ok  	runtime/debug	0.229s
ok  	runtime/pprof	20.363s
ok  	runtime/trace	3.049s
ok  	sort	0.102s
ok  	strconv	0.425s
ok  	strings	1.439s
ok  	sync	0.798s
ok  	sync/atomic	3.000s
ok  	syscall	0.043s
ok  	testing	1.711s
ok  	testing/quick	0.049s
ok  	text/scanner	0.012s
ok  	text/tabwriter	0.229s
ok  	text/template	0.396s
ok  	text/template/parse	0.126s
ok  	time	4.270s
ok  	unicode	0.010s
ok  	unicode/utf16	0.010s
ok  	unicode/utf8	0.013s
ok  	cmd/addr2line	1.623s
ok  	cmd/api	0.257s
ok  	cmd/asm/internal/asm	0.316s
ok  	cmd/asm/internal/lex	0.118s
ok  	cmd/compile/internal/big	3.070s
ok  	cmd/cover	35.387s
ok  	cmd/doc	0.336s
ok  	cmd/fix	0.244s
panic: test timed out after 3m0s

goroutine 316 [running]:
testing.startAlarm.func1()
	/home/kamol/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/home/kamol/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0xab1640, 0xc5c660, 0x8a, 0x8a, 0x1)
	/home/kamol/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200cfee8, 0x6)
	/home/kamol/go/src/testing/testing.go:494 +0x70
cmd/go_test.TestMain(0xc8200cfee8)
	/home/kamol/go/src/cmd/go/go_test.go:94 +0x627
main.main()
	cmd/go/_test/_testmain.go:328 +0x113

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/home/kamol/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
	/home/kamol/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/kamol/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 20 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc820073d40)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc8201257c0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestFileLineInErrorMessages(0xc820073d40)
	/home/kamol/go/src/cmd/go/go_test.go:631 +0x6e
testing.tRunner(0xc820073d40, 0xc5c738)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 21 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc820073d40)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 22 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc820073dd0)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc820125900)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestProgramNameInCrashMessages(0xc820073dd0)
	/home/kamol/go/src/cmd/go/go_test.go:645 +0x63
testing.tRunner(0xc820073dd0, 0xc5c750)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 23 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc820073dd0)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 42 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc82016afc0)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017cdc0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoInstallRebuildsStalePackagesInOtherGOPATH(0xc82016afc0)
	/home/kamol/go/src/cmd/go/go_test.go:731 +0x7d
testing.tRunner(0xc82016afc0, 0xc5c7c8)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 44 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc82016b050)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017cf00)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoInstallDetectsRemovedFiles(0xc82016b050)
	/home/kamol/go/src/cmd/go/go_test.go:761 +0x63
testing.tRunner(0xc82016b050, 0xc5c7e0)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 43 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc82016afc0)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 45 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc82016b050)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 47 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc82016b170)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017d040)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoInstallDetectsRemovedFilesInPackageMain(0xc82016b170)
	/home/kamol/go/src/cmd/go/go_test.go:807 +0x63
testing.tRunner(0xc82016b170, 0xc5c810)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 48 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc82016b170)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 169 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc8204c6090)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82047fcc0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoTestWithPackageListedMultipleTimes(0xc8204c6090)
	/home/kamol/go/src/cmd/go/go_test.go:1322 +0x7a
testing.tRunner(0xc8204c6090, 0xc5cbb8)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 170 [chan receive, 1 minutes]:
testing.RunTests.func1(0xc82001aba0, 0xc8204c6090)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 202 [chan receive]:
testing.(*T).Parallel(0xc82016b950)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017d680)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestLdflagsArgumentsWithSpacesIssue3941(0xc82016b950)
	/home/kamol/go/src/cmd/go/go_test.go:1455 +0x63
testing.tRunner(0xc82016b950, 0xc5ccd8)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 203 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc82016b950)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 210 [chan receive]:
testing.(*T).Parallel(0xc8200721b0)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017dcc0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoTestDashCDashOControlsBinaryLocation(0xc8200721b0)
	/home/kamol/go/src/cmd/go/go_test.go:1486 +0x63
testing.tRunner(0xc8200721b0, 0xc5cd20)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 211 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc8200721b0)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 212 [chan receive]:
testing.(*T).Parallel(0xc820072240)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82017de00)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestGoTestDashOWritesBinary(0xc820072240)
	/home/kamol/go/src/cmd/go/go_test.go:1495 +0x63
testing.tRunner(0xc820072240, 0xc5cd38)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 213 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc820072240)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 217 [chan receive]:
testing.(*T).Parallel(0xc8200727e0)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc820124280)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestInstallWithTags(0xc8200727e0)
	/home/kamol/go/src/cmd/go/go_test.go:1525 +0x7a
testing.tRunner(0xc8200727e0, 0xc5cd68)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 219 [chan receive]:
testing.(*T).Parallel(0xc820072870)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc8201243c0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestCaseCollisions(0xc820072870)
	/home/kamol/go/src/cmd/go/go_test.go:1552 +0x6e
testing.tRunner(0xc820072870, 0xc5cd80)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 218 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc8200727e0)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 220 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc820072870)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 243 [chan receive]:
testing.(*T).Parallel(0xc8200733b0)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc8201252c0)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestCgoShowsFullPathNames(0xc8200733b0)
	/home/kamol/go/src/cmd/go/go_test.go:1798 +0x16d
testing.tRunner(0xc8200733b0, 0xc5ce88)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 244 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc8200733b0)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 245 [chan receive]:
testing.(*T).Parallel(0xc820073440)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc820125400)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestCgoHandlesWlORIGIN(0xc820073440)
	/home/kamol/go/src/cmd/go/go_test.go:1815 +0x16d
testing.tRunner(0xc820073440, 0xc5cea0)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 246 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc820073440)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 258 [chan receive]:
testing.(*T).Parallel(0xc8204c6630)
	/home/kamol/go/src/testing/testing.go:422 +0x7c
cmd/go_test.(*testgoData).parallel(0xc82008c000)
	/home/kamol/go/src/cmd/go/go_test.go:179 +0x4d8
cmd/go_test.TestBuildDashIInstallsDependencies(0xc8204c6630)
	/home/kamol/go/src/cmd/go/go_test.go:1885 +0x63
testing.tRunner(0xc8204c6630, 0xc5cf30)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 311 [syscall]:
syscall.Syscall6(0x3d, 0x4d09, 0xc82004991c, 0x0, 0xc8202e8fc0, 0x0, 0x0, 0xc8200498f0, 0xc8200498f8, 0xc8200498e8)
	/home/kamol/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x4d09, 0xc82004991c, 0x0, 0xc8202e8fc0, 0x90, 0x0, 0x0)
	/home/kamol/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
syscall.Wait4(0x4d09, 0xc820049964, 0x0, 0xc8202e8fc0, 0xc820028c58, 0x0, 0x0)
	/home/kamol/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc820355440, 0x33, 0x0, 0x0)
	/home/kamol/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc820355440, 0x0, 0x0, 0x0)
	/home/kamol/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc8204d3cc0, 0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:380 +0x211
os/exec.(*Cmd).Run(0xc8204d3cc0, 0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:258 +0x64
cmd/go_test.(*testgoData).doRun(0xc8204d3a40, 0xc8200f3e00, 0x4, 0x4, 0x0, 0x0)
	/home/kamol/go/src/cmd/go/go_test.go:264 +0x60e
cmd/go_test.(*testgoData).run(0xc8204d3a40, 0xc8200f3e00, 0x4, 0x4)
	/home/kamol/go/src/cmd/go/go_test.go:279 +0x57
cmd/go_test.TestGoTestRaceInstallCgo(0xc8202e8e10)
	/home/kamol/go/src/cmd/go/go_test.go:2184 +0x47a
testing.tRunner(0xc8202e8e10, 0xc5d140)
	/home/kamol/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:561 +0x86d

goroutine 259 [chan receive]:
testing.RunTests.func1(0xc82001aba0, 0xc8204c6630)
	/home/kamol/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/home/kamol/go/src/testing/testing.go:566 +0x90e

goroutine 315 [syscall]:
syscall.Syscall(0x0, 0x6, 0xc8201a4600, 0x200, 0x0, 0x200, 0x0)
	/home/kamol/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x6, 0xc8201a4600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/kamol/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x6, 0xc8201a4600, 0x200, 0x200, 0x40c341, 0x0, 0x0)
	/home/kamol/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820028c50, 0xc8201a4600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/kamol/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820028c50, 0xc8201a4600, 0x200, 0x200, 0x1, 0x0, 0x0)
	/home/kamol/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc8204d3b10, 0x7f12ea1fd578, 0xc820028c50, 0x0, 0x0, 0x0)
	/home/kamol/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x7f12ea1fddf0, 0xc8204d3b10, 0x7f12ea1fd578, 0xc820028c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:375 +0x180
io.Copy(0x7f12ea1fddf0, 0xc8204d3b10, 0x7f12ea1fd578, 0xc820028c50, 0x0, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:232 +0x8b
os/exec.(*Cmd).Start.func1(0xc8204d3cc0, 0xc820355140)
	/home/kamol/go/src/os/exec/exec.go:340 +0x1d
created by os/exec.(*Cmd).Start
	/home/kamol/go/src/os/exec/exec.go:341 +0x96d

goroutine 314 [syscall]:
syscall.Syscall(0x0, 0x4, 0xc820351800, 0x600, 0x0, 0x5d8, 0x0)
	/home/kamol/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc820351800, 0x600, 0x600, 0x0, 0x0, 0x0)
	/home/kamol/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x4, 0xc820351800, 0x600, 0x600, 0x40c341, 0x0, 0x0)
	/home/kamol/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820028c38, 0xc820351800, 0x600, 0x600, 0x0, 0x0, 0x0)
	/home/kamol/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820028c38, 0xc820351800, 0x600, 0x600, 0x1, 0x0, 0x0)
	/home/kamol/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc8204d3aa0, 0x7f12ea1fd578, 0xc820028c38, 0x0, 0x0, 0x0)
	/home/kamol/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0x7f12ea1fddf0, 0xc8204d3aa0, 0x7f12ea1fd578, 0xc820028c38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:375 +0x180
io.Copy(0x7f12ea1fddf0, 0xc8204d3aa0, 0x7f12ea1fd578, 0xc820028c38, 0x28, 0x0, 0x0)
	/home/kamol/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/home/kamol/go/src/os/exec/exec.go:232 +0x8b
os/exec.(*Cmd).Start.func1(0xc8204d3cc0, 0xc820355100)
	/home/kamol/go/src/os/exec/exec.go:340 +0x1d
created by os/exec.(*Cmd).Start
	/home/kamol/go/src/os/exec/exec.go:341 +0x96d
FAIL	cmd/go	186.958s
ok  	cmd/gofmt	0.136s
ok  	cmd/internal/goobj	0.009s
ok  	cmd/internal/obj	0.018s
ok  	cmd/internal/obj/x86	0.064s
ok  	cmd/internal/rsc.io/arm/armasm	0.365s
ok  	cmd/internal/rsc.io/x86/x86asm	5.769s
ok  	cmd/nm	3.422s
ok  	cmd/objdump	20.454s
ok  	cmd/pack	41.986s
ok  	cmd/pprof/internal/profile	0.011s
ok  	cmd/vet	7.727s
2015/09/04 03:21:17 Failed: exit status 1

**Comment by davecheney** [comment]
You didn't mention the Amazon instance you ran this test on. The tests take a lot of CPU, and this is something that cloud providers love to over provision.

You can try increasing the timeouts with this setting
```
env GO_TEST_TIMEOUT_SCALE=1
```
I'm going to close this issue for the moment as I don't think there is anything to be done here. Please feel free to reopen if you are unable to resolve the problem.

**Comment by kamoljan** [comment]
thank you @davecheney !

**Comment by leohotfn** [comment]
thank you @davecheney !
