### ISSUE TITLE
./all.bash cannot pass test for `syscall` on AMI

### ISSUE THREAD

**Issue by kamoljan** [golang/go#12497]
$go test syscall
    --- FAIL: TestCloneNEWUSERAndRemapNoRootDisableSetgroups (0.00s)
	exec_linux_test.go:53: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted,     output:
    FAIL
    FAIL	syscall	0.010s
    
    $ uname -a
    Linux ip-10-0-1-38 3.14.48-33.39.amzn1.x86_64 #1 SMP Tue Jul 14 23:43:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The same for `release-branch.go1.5` and `master` branch.

`strace' 

    [pid 30505] select(0, NULL, NULL, NULL, {0, 100} <unfinished ...>
    [pid 30502] write(1, "--- FAIL: TestCloneNEWUSERAndRem"..., 170--- FAIL:     TestCloneNEWUSERAndRemapNoRootDisableSetgroups (0.00s)
	exec_linux_test.go:53: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted,    output:
     <unfinished ...>
    [pid 30503] <... select resumed> )      = 0 (Timeout)

**Comment by bradfitz** [comment]
Dup of #11261 (let's discuss there)
