### ISSUE TITLE
net/mail: misleading ParseAddress error message when german umlauts in display-name

### ISSUE THREAD

**Issue by ulrichSchreiner** [golang/go#12492]
If the display-name part contains a german umlaut, the `ParseAddress` fails.
```
    s := "aä <aa.bb@cc.com>"
    m, e := mail.ParseAddress(s)
    if e != nil {
        panic(e)
    }
	fmt.Printf("%v\n",m)
```
panics with
```
panic: mail: no angle-addr
```
This happens very often with german adresses. If the display-name only contains umlauts like `"ää öö <aa.bb@cc.com>"` it panics with:
```
panic: mail: missing word in phrase: mail: invalid string
```

**Comment by stemar94** [comment]
Take a look at https://github.com/golang/go/issues/7079
ParseAddress parses according to RFC 5322, which only allows US-ASCII characters.
A possible workaround for you: Use the mail.AddressParser struct, to encode your umlauts, guess there should be some examples in the web.

**Comment by bradfitz** [comment]
Yes, only ASCII is allowed there. Perhaps we should return a more clear error message if we see any octet greater than 127 in the input.

**Comment by nightlyone** [comment]
Ok, took a stab on better error message at https://go-review.googlesource.com/14312

Any feedback on the text would be great!

**Comment by gobwas** [comment]
@ulrichSchreiner hi! Did you solved this issue? =)

**Comment by stemar94** [comment]
@gobwas take a look at my answer

**Comment by gobwas** [comment]
@stemar94 i saw your answer, thanks. There are no examples in the web. How could `mail.AddressParser` encode non ASCII chars? I think, [by the spec](https://golang.org/pkg/net/mail/#AddressParser), it should decode, not encode.

```go
m := "Иван Иванов <ivanov@example.com>"
parser := mail.AddressParser{WordDecoder: &mime.WordDecoder{}}
encodedM := HowCouldIEncodeThisToRFC5322(m) // ?
parser.Parse(m)
```

**Comment by ulrichSchreiner** [comment]
try this:
```go
    s := "aä <aa.bb@cc.com>"
    se := mime.QEncoding.Encode("utf-8", s)
    
    m, e := mail.ParseAddress(se)
    if e != nil {
        panic(e)
    }
    fmt.Printf("%v\n",m.Address)
    fmt.Printf("%v\n",m.Name)
    dec := new(mime.WordDecoder)
    decname, err := dec.Decode(m.Name+"?=")
    if err != nil {
        panic(err)
    }
    fmt.Printf("%v\n",decname)
```

**Comment by gobwas** [comment]
@ulrichSchreiner your example just not panics, but `m.Name` is still encoded like:

```go
fmt.Printf("%s %s", m.Name, m.Address) // => ivanov@example.com =?utf-8?q?=D0=98=D0=B2=D0=B0=D0=BD_=D0=98=D0=B2=D0=B0=D0=BD=D0=BE=D0=B2?=
```

**Comment by ulrichSchreiner** [comment]
if you want the name, you have to decode the name with the WordDecoder: http://play.golang.org/p/OzcpaQh9jj

**Comment by gobwas** [comment]
@ulrichSchreiner okay. I've got this. Thank you!
