### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by apaganobeleno** [golang/go#12491]
Context: https://tour.golang.org/basics/13

"Unlike in C, in Go assignment between items of different type requires an explicit conversion. Try removing the float64 or int conversions in the example and see what happens."

I did remove these and this still working, what should happen ? shoud user see some error ?
Regards!

**Comment by adg** [comment]
This code

```
	var x, y int = 3, 4
	var f float64 = math.Sqrt((x*x + y*y))
	var z int = (f)
	fmt.Println(x, y, z)
```

produces these errors:

```
prog.go:10: cannot use x * x + y * y (type int) as type float64 in argument to math.Sqrt
prog.go:11: cannot use f (type float64) as type int in assignment
```

**Comment by apaganobeleno** [comment]
@adg right, sorry, i thought tour meant `int` and `float64` on variables declaration.

**Comment by adg** [comment]
no problem!
