### ISSUE TITLE
unexpected built packages

### ISSUE THREAD

**Issue by gadumitrachioaiei** [golang/go#12506]
In go 1.5, go build with "-a" option seems to also build standard library packages. In go 1.4 it doesn't and the documentation also says that it shouldn't.
Also, with a small program that uses net/http, it builds fine without "-a" option, but with it it fails with:
undefined: http.ListenAndServe

**Comment by magical** [comment]
I believe the change to -a was intentional: https://github.com/golang/go/commit/4dab6d01f12591f256d36b32cd6480ef679458f1

**Comment by bradfitz** [comment]
Yes, it was intentional, reverting it back to the 1.3 and earlier behavior. The -a flag should no longer be needed for tags, etc. All the old bugs which forced people to use -a should be fixed.

**Comment by minux** [comment]
And the cmd/go docs has been fixed too.
The fix will be in 1.5.1 (CL 14226).
