### ISSUE TITLE
build: run all tests on some builder

### ISSUE THREAD

**Issue by josharian** [golang/go#12508]
The builders run the -short tests. However, we've seen non-short tests fail in the past. It'd be good for at least one builder somewhere on at least one arch/os to run the full suite.

cc @bradfitz

**Comment by Thomasdezeeuw** [comment]
Another possibility might be to run the "long" go test once a day/week on all the current builders. This way no extra builders are required. The downside is that when the tests fails multiple commits could be blamed and require a little extra debugging.

**Comment by bradfitz** [comment]
The majority of our builders are virtual, and very cheap. We can run more configs (like a full one) if they're useful.

**Comment by rsc** [comment]
Another option is to make some longer tests (normally disabled by -short) run anyway if they notice they are on a (any) builder. That might be better than yet another special config that we have to remember what it means.

**Comment by bradfitz** [comment]
Also, now that we shard tests, it might not even be much longer to run full tests on some of the more widely-sharded builders.

**Comment by josharian** [comment]
cc @andybons 

Unnoticed non-short test failures get noticed every few months. The latest is #24464.

**Comment by ysmolsky** [comment]
And more cases: #25367 #24436
