### ISSUE TITLE
x/mobile/exp/sensor: can't reenable sensors once disabled on Android

### ISSUE THREAD

**Issue by rakyll** [golang/go#12501]
The proxying goroutine will block on readSignal forever if all sensors are disabled on Android. Once every sensor is disabled, there is no way for other signals to be consumed by the same proxying goroutine.

**Comment by rakyll** [comment]
I would like to reuse the the existing [app looper](https://github.com/golang/mobile/blob/master/app/android.go#L368) to enable, disable and read the sensor events.

The app looper is not suffering from the indefinitely blocked case because there will be new app lifecycle events during the lifetime of an app. Reusing it sounds like a better strategy than trying to invent a preemption strategy for the sensor looper.

@crawshaw, any thoughts?

**Comment by rakyll** [comment]
Given it a second thought, trying to wake the blocked pollAll with ALooper_wake or destroying the underlying ALooper if no sensors enabled sound like a better option than coupling the sensor package with app's ALooper.

**Comment by crawshaw** [comment]
I would prefer minimizing the number of OS-specific hooks the app package needs to export, so if this can be done inside the sensor package that would be best.

**Comment by rakyll** [comment]
Rather than going for one of the complex proposals above, I decided to introduce a hard poll timeout which allowed the thread not to be blocked indefinitely and gave the poller a fair execution time.
