### ISSUE TITLE
x/mobile/cmd/gomobile: generates an .app even though build fails

### ISSUE THREAD

**Issue by rakyll** [golang/go#12505]
```
$ rm -rf example.app
$ cat main.go
package main

import (
    "fmt"
    "time"
)

func main() {
    for i := 0; i < 5000*1000; i++ {
        go func() {
            fmt.Println("hello")
            time.Sleep(time.Second)
        }()
    }

}

$ gomobile build -target=ios .
gomobile: github.com/rakyll/gom/example does not import "golang.org/x/mobile/app"

$ stat example.app
16777220 152150587 drwxr-xr-x 8 jbd (5000) 0 272 "Sep  4 15:52:31 2015" "Sep  4 15:52:05 2015" "Sep  4 15:52:05 2015" "Sep  4 15:52:04 2015" 4096 0 0 example.app
```

Expected output: The build should fail and the .app should not be generated.

**Comment by rakyll** [comment]
/cc @crawshaw @hyangah 

The same behavior applies to -target=android as well, the apk is generated even though `gomobile build` fails with:

```
gomobile: golang.org/x/mobile/example/hello does not import "golang.org/x/mobile/app"
```

I am not sure what is the intention behind the current behavior, we can always delete the intermediate app and apk files if x/mobile/app import condition fails. Currently, the error message reads as it is a warning but `gomobile build` exits with an error.

**Comment by changkun** [comment]
gomobile works as expected today, this is fully outdated. Close.
