### ISSUE TITLE
Gopherbot confuses CL and Bug numbers

### ISSUE THREAD

**Issue by nodirt** [golang/go#12500]
E.g. CL https://golang.org/cl/10483 mentions `CL 10296`, but gopherbot thought it is issue 10296, and mistakenly posted a message to #10296 that the CL mentions it.

Proposal: check only numbers prefixed with `#`, e.g. `#10296`.

Question: where is gopherbot source code?

**Comment by bradfitz** [comment]
That CL originally (https://go-review.googlesource.com/#/c/10483/1) referenced the bug with a # sign before it. I think this is working as intended.

**Comment by nodirt** [comment]
It referenced a `CL golang/go#10296`, not the bug. But the proposed solution would not fix this particular case indeed.

**Comment by bradfitz** [comment]
Yeah, that's just a bug in their syntax.
