### ISSUE TITLE
GO15VENDOREXPERIMENT does not work outside GOPATH

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#12511]
The exact same package, which imports code from its `./vendor/` folder, will correctly `go build` if placed in `$GOPATH/*`, but will fail to find the packages in `./vendor/` if placed anywhere else.

The two different behaviors are surprising.

This was turned off in b6ead9f171742cd5b519a22ecc690354b0d1ce27

**Comment by rsc** [comment]
It's not intended to work. Vendor is for fully-qualified imports (not relative ./ ones), and those only work inside $GOPATH.

**Comment by FiloSottile** [comment]
I see. Can you point me to the rationale/discussion? Because I think it can really confuse newcomers, since they won't be able to just clone a repository and run `go build` anymore. (Unless obviously there's some Makefile overriding GOPATH, but that's kind of what we want to avoid?)

**Comment by bradfitz** [comment]
Let's move discussion to a forum. See https://golang.org/wiki/Questions

**Comment by mwf** [comment]
@FiloSottile FYI you can make a softlink to anywere else and "go build" will work correctly there.
