### ISSUE TITLE
x/tools/mobile: gomobile init error

### ISSUE THREAD

**Issue by zld406504302** [golang/go#12515]
mac os 
gomobile installed,but failed when execute “gomobile init”
this's the error  “gomobile: xcrun --show-sdk-path: exit status 1”

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by RoonyH** [comment]
Facing the same. @zld406504302 would be thankful if you could say how you got pass this.

**Comment by crawshaw** [comment]
@RoonyH do you have Xcode installed, and have you opened it to accept the latest license?

I'm going to see if I can improve the error message that prints out.

**Comment by RoonyH** [comment]
@crawshaw Ah. I don't! Thanks.
