### ISSUE TITLE
tour: [confusing explanation]

### ISSUE THREAD

**Issue by VictorBarrantes** [golang/go#12517]
Context: https://tour.golang.org/basics/14

For Type inference, the explanation reads "When declaring a variable without specifying its type (using var without a type or the := syntax), the variable's type is inferred from the value on the right hand side."

This is confusing because you cannot actually use var without a type.
When you declare a variable using "var" you must specify a type, either explicitly like "var x int" or implicitly through an initial assignment like "var x = 5" but you cannot define it like "var x" (without a type) as the explanation reads.

**Comment by minux** [comment]
The explanation says its type will be "inferred from the value on the right
hand side",
which means you can't use a bare "var x" as there won't be any value on the
right
hand site to infer from.

**Comment by minux** [comment]
And "var x = 5" is using a var without a(n explicit) type, which is what the
statement is about.

**Comment by VictorBarrantes** [comment]
Sure, I know that and you know that and anyone can eventually get to that conclusion, my observation is that the explanation is confusing, specially for newcomers. Why to save in explanations and not making it very clear?, something like:
"Variables can be declared without specifying its type explicitly (using the var x = <value> syntax or the := syntax), in these cases, the variable's type is inferred from the value on the right hand side of the declaration."
Then, in the samples, use:
var i = 42        // int
j := 42           // int

"without a type" sounds like you can actually define a var "without a type". It is an initial tour, then why leading people to confusion when it can be very simple explained?

**Comment by robpike** [comment]
It seems pretty clear to me, but maybe can be improved.

When declaring a variable without specifying an explicit type (either by using the := syntax or var = expression syntax), the variable's type is inferred from the value on the right hand side.
