### ISSUE TITLE
cmd/compile: windows-386-gce build is flaky

### ISSUE THREAD

**Issue by josharian** [golang/go#12519]
For example, https://storage.googleapis.com/go-build-log/05719e3d/windows-386-gce_41de92d0.log

The master branch builder is stable.

The error message is `fatal error: runtime: cannot map pages in arena address space`, which appears to be caused by being low on memory.

cc @randall77 @tzneal

**Comment by randall77** [comment]
We're running with GOGC=off at the moment, which probably makes things (way?) worse than they would otherwise be.

**Comment by minux** [comment]
Yeah 386 windows generally uses more memory than
other 32-bit architecture or OSes.

**Comment by josharian** [comment]
The failure is during compilation, so GC is on. This is extra memory usage by the SSA compiler.

**Comment by aclements** [comment]
@josharian, is this still a problem?

**Comment by josharian** [comment]
build.golang.org says no, not still a problem.
