### ISSUE TITLE
除了init之外，是否可以添加一个前置的init

### ISSUE THREAD

**Issue by jorise7** [golang/go#12521]
我在代码test.go中引入了包a， 在a包中又引入了b
那么，init的顺序为，，   
b.init  ->   a.init  ->   main.init()

但是实际上，我很多时候需要在 b.init()  执行之前，  要初始化 包a里面的一些内容。
我该如何处理？  是否考虑下添加一个前置 init 的功能？

**Comment by bradfitz** [comment]
Please bring questions like this to a mailing list. We only use the Go bug tracker for tracking bugs, like as a discussion forum.
