### ISSUE TITLE
func 扩展方法可否外置扩展

### ISSUE THREAD

**Issue by jorise7** [golang/go#12522]
func (xyz *Xyz) Test() {
    xyz.haha
}

在包内可以为某个对象扩展方法，如楼上~~~
但是实际上有时候，我希望可以在包外，对某一个包里的对象，扩展方法
只不过在包外扩展， 只能允许访问public 对象即可，，
这样当一个包的某个对象，被扩展之后，  在任何引用它的地方，都可以使用包外扩展，这是相关方便的说。。。  实现也很简单，求实现~~~

如

func (str string) Test() string {
    return str+"hahaha"
}

**Comment by bradfitz** [comment]
I think this is a request for Ruby- or JavaScript-style monkey patching things in other packages. We won't be supporting that in Go. Go tries to make software development in the large more efficient, and monkey patching is counter to that goal.
