### ISSUE TITLE
x/mobile/f32: error transposing matrix

### ISSUE THREAD

**Issue by star-tek-mb** [golang/go#12520]
f32 mathematics gets a wrong matrix. I  compared it with __github.com/go-gl/mathgl/mgl32__:
```go
package main

import (
	"fmt"
	"math"
	m1 "github.com/go-gl/mathgl/mgl32"
	m2 "golang.org/x/mobile/exp/f32"
)

func transpose(m *m2.Mat4) {
	m[0][1], m[1][0] = m[1][0], m[0][1]
	m[0][2], m[2][0] = m[2][0], m[0][2]
	m[0][3], m[1][0] = m[3][0], m[0][3]
	m[1][3], m[3][1] = m[3][1], m[1][3]
	m[2][3], m[3][2] = m[3][2], m[2][3]
	m[1][2], m[2][1] = m[2][1], m[1][2]
}

func main() {
	p1 := m1.Perspective(math.Pi / 4.0, 4.0 / 3.0, 0.1, 100.0) 
	v1 := m1.LookAt(4, 3, 3, 0, 0, 0, 0, 1, 0)
	mat1 := p1.Mul4(v1)
	
	fmt.Println(p1)
	fmt.Println(v1)
	fmt.Println(mat1)

	p2, v2, mat2 := new(m2.Mat4), new(m2.Mat4), new(m2.Mat4)
	p2.Perspective(math.Pi / 4.0, 4.0 / 3.0, 0.1, 100.0)
	v2.LookAt(&m2.Vec3{4, 3, 3}, &m2.Vec3{0, 0, 0}, &m2.Vec3{0, 1, 0})
	mat2.Mul(p2, v2)
	
	fmt.Println(p2)
	fmt.Println(v2)
	fmt.Println(mat2)
	
	// Transposed:
	transpose(p2)
	transpose(v2)
	transpose(mat2)
	
	fmt.Println(p2)
	fmt.Println(v2)
	fmt.Println(mat2)
}
```
There are no match with a transposed and original matrix. Projection matrix is right (if it transposed). But view matrix is wrong! May be there are fix.
gomobile version +c76d5c8 Fri Sep 4 16:23:41 2015 +0000 (android); androidSDK=/home/startek/android-sdk/platforms/android-23

**Comment by nigeltao** [comment]
There is a bug in your code, not in the golang.org/x/mobile/exp/f32 package.

func transpose(m *m2.Mat4) {
    m[0][1], m[1][0] = m[1][0], m[0][1]
    m[0][2], m[2][0] = m[2][0], m[0][2]
    m[0][3], m[1][0] = m[3][0], m[0][3]  // YOUR BUG IS HERE.
    m[1][3], m[3][1] = m[3][1], m[1][3]
    m[2][3], m[3][2] = m[3][2], m[2][3]
    m[1][2], m[2][1] = m[2][1], m[1][2]
}
