### ISSUE TITLE
go not working

### ISSUE THREAD

**Issue by getpradeep9** [golang/go#12527]
$ go version
bash: /usr/local/go/bin/go: cannot execute binary file: Exec format error

**Comment by davecheney** [comment]
How did you install Go? Perhaps you installed the wrong version.

Try file /usr/local/go/bin/go

And check that it matches your operation system.

**Comment by robpike** [comment]
Incomplete problem description. Please create a new issue with a proper description of the problem.

**Comment by gyaan** [comment]
I had the same problem while executing golang program. I had installed 64-bit version of golang instead of 32-bit version. After installation of 32-bit OS version working fine.
