### ISSUE TITLE
proble go server in 1.5

### ISSUE THREAD

**Issue by 7belrhalmia** [golang/go#12526]
web server in go 1.5 don't open the web page it download it
![gifrecord_2015-09-07_033537](https://cloud.githubusercontent.com/assets/13202562/9708297/a4fedd7c-5511-11e5-84fc-801e77caa396.gif)

**Comment by davecheney** [comment]
The issue tracker is only for issues with Go. Please consult golang-nuts for assistance.

**Comment by 7belrhalmia** [comment]
@davecheney  it's an issue with go because in go 1.2 it work normally but in go 1.5 dosen't work

**Comment by adg** [comment]
If it's a regression then you must show your code.

**Comment by 7belrhalmia** [comment]
@adg  this page work fine with go1.2 but when i switch to go 1.5 it begin to do that

**Comment by davecheney** [comment]
Thank you for raising the question on golang-nuts. I am locking this issue for further comment to avoid duplication.
