### ISSUE TITLE
Go run keeps running even after I SIGKILL it

### ISSUE THREAD

**Issue by Kallikanzarid** [golang/go#12530]
I’m using `go version go1.5 darwin/amd64`.

I wrote a test program called `ghost.go`:

~~~{.go}
package main

import (
    "fmt"
    "time"
)

func main() {
    <-time.After(10 * time.Second)
    fmt.Println("I'm a ghost!")
}
~~~

I use `go run ghost.go` to run it, and then I kill the `go` process from the other terminal tab by PID: `kill -s SIGKILL 1234`. It is properly killed but after 10 seconds pass, `I’m a ghost!` appears in the terminal prompt. Help me, I think my MacBook is haunted :(

It doesn’t happen if I first build the program and then execute it. I am not running any other proccesses I know of that depend on Go, as far as I know.

UPD: basically, `go run` spawns a child process from a file in a temp directory, but doesn’t forward any signals to it, which is kinda weird

**Comment by nightlyone** [comment]
since SIGKILL cannot be caught (not even by the `go run`) it cannot be forwarded. So the behavior you see is to be expected.

**Comment by minux** [comment]
working as intended.

your SIGKILL is only sent to the "go run" process that is waiting for
the actual child process to finish.

If SIGKILL really can't kill a Go process, send a bug report to your
OS vendor. But please do verify that you've sent the signal to the
correct process first.
