### ISSUE TITLE
runtime: document signals caught and handled by the runtime

### ISSUE THREAD

**Issue by nightlyone** [golang/go#12534]
Various signals (e.g. SIGQUIT) are handled by the runtime and lead to special default actions in all Go programs.

It would be great to document these somewhere (e.g. os/signal) so people can find these magic signals and their expected/current behavior somewhere.

**Comment by mlafeldt** [comment]
Today I tried to remember the signal which causes a Go program to dump all goroutines. Even through googling it was hard to figure out that SIGQUIT is the right answer. So :+1: for adding this information to a well-known location.

**Comment by ianlancetaylor** [comment]
Good idea but I don't think os/signal is the right place for this.  Setting the package to runtime for now.

**Comment by rsc** [comment]
FWIW the argument for putting these docs in os/signal (perhaps with a forward reference from package runtime) is that os/signal's funcs change the behavior. It's easier to describe both the default and modified behaviors in one place.

**Comment by rsc** [comment]
Dup of #9896.
