### ISSUE TITLE
Possible to assign to variable named "nil", "true", and others.

### ISSUE THREAD

**Issue by momchil-atanasov** [golang/go#12535]
Hi,

It is currently possible to assign a value to a variable named `nil`, as well as other reserved types like `float32`, `int`, and others. Considering how explicit Go seems to be regarding code sanity, I am inclined to consider this a bug.

Here is an example:
http://play.golang.org/p/AgUlQ810Yi

I find the one with the overriding of `true` to be the most interesting case (thanks to @Bo0mer for pointing that one out).

Regards,
Momchil

**Comment by bradfitz** [comment]
This is by design. And it's also not something that can be changed without breaking the Go 1 compatibility promise.

**Comment by paranoiacblack** [comment]
To be clear, according the specification, on lexical elements, particularly keywords (golang.org/ref/spec#Keywords), there are a certain set of keywords that cannot be used as identifiers in Go programs. True, nil, etc are purposefully not included in that list.
