### ISSUE TITLE
cmd/go: package cmd/internal/rsc.io/x86/x86asm: ... is not using a known version control system

### ISSUE THREAD

**Issue by quchunguang** [golang/go#12532]
$ go get -u all
package cmd/internal/rsc.io/arm/armasm: directory "D:\Go\src\cmd\internal\rsc.io\arm\armasm" is not using a known version control system
package cmd/internal/rsc.io/x86/x86asm: directory "D:\Go\src\cmd\internal\rsc.io\x86\x86asm" is not using a known version control system

This message appears everytime i upgrade packages in $GOPATH on all my windows/linux PCs for some months. I do not know what it mean and how to avoid it.

**Comment by ianlancetaylor** [comment]
That error messages comes entirely from the local directories on your system.  The go command looks in the directory and tries to determine the version control system.  In your case it is failing.  Can you list all the files under D:\Go\src\cmd\internal\rsc.io\arm\armasm , including any that start with "."?  (I don't know how to do that on Windows.)

By the way, the x86asm package has moved to golang.org/x/arch, and the armasm package will follow.

**Comment by alexbrainman** [comment]
> ... Can you list all the files under D:\Go\src\cmd\internal\rsc.io\arm\armasm , including any that start with "."? (I don't know how to do that on Windows.)

You can use "dir D:\Go\src\cmd\internal\rsc.io\arm\armasm" command. For example:
```
C:\dev\go\src>dir c:\dev\go
 Volume in drive C has no label.
 Volume Serial Number is 1234-5678

 Directory of c:\dev\go

07/09/2015  12:40 PM    <DIR>          .
07/09/2015  12:40 PM    <DIR>          ..
26/06/2015  09:39 AM               347 .gitattributes
26/06/2015  09:39 AM               556 .gitignore
03/08/2015  10:27 AM    <DIR>          api
12/08/2015  11:39 AM            21,139 AUTHORS
07/09/2015  12:41 PM    <DIR>          bin
29/06/2015  09:35 AM             1,107 CONTRIBUTING.md
12/08/2015  11:39 AM            28,953 CONTRIBUTORS
04/09/2015  08:47 AM    <DIR>          doc
26/06/2015  09:39 AM             1,150 favicon.ico
26/06/2015  09:39 AM    <DIR>          lib
26/06/2015  09:39 AM             1,479 LICENSE
28/07/2015  10:03 AM    <DIR>          misc
26/06/2015  09:39 AM             1,303 PATENTS
07/09/2015  12:40 PM    <DIR>          pkg
26/06/2015  09:39 AM             1,519 README.md
26/06/2015  09:39 AM                26 robots.txt
07/09/2015  12:42 PM    <DIR>          src
07/09/2015  12:54 PM    <DIR>          test
07/09/2015  12:40 PM                44 VERSION.cache
              11 File(s)         57,623 bytes
              10 Dir(s)  656,104,385,990,656 bytes free
```

Alex

**Comment by quchunguang** [comment]
Sorry for late to reply.
Yes.That error messages comes entirely from my local directories. I checked "~/share/go1.5/src/cmd/vendor/golang.org/x/arch/arm/armasm" and there is not under any version control system as the error message said. But the "~/share/go1.5/" directory is forked from here (github.com/golang/go) directly.
This is my "~/share/go1.5/src/cmd/vendor/golang.org/x/arch/arm/armasm" directory in my ubuntu 15.04 below (Same as in my Windows),

decode.go       ext_test.go  inst.go   objdumpext_test.go  plan9x.go  testdata
decode_test.go  gnu.go       Makefile  objdump_test.go     tables.go

**Comment by ianlancetaylor** [comment]
Your original report says that "go get" was reporting an error.  You shouldn't be using "go get" on your main Go sources.  You should only be using it on your GOPATH sources.  Have you set GOPATH to the same value as `go env GOROOT`?  Don't do that.

**Comment by gertcuykens** [comment]
```
$ go env GOROOT
/usr/local/go
$ go env GOPATH
/home/gert
$ go get -u all
package cmd/internal/rsc.io/arm/armasm: directory "/usr/local/go/src/cmd/internal/rsc.io/arm/armasm" is not using a known version control system
package cmd/internal/rsc.io/x86/x86asm: directory "/usr/local/go/src/cmd/internal/rsc.io/x86/x86asm" is not using a known version control system
package golang.org/x/tools/cmd/tipgodoc: cannot find package "golang.org/x/tools/cmd/tipgodoc" in any of:
	/usr/local/go/src/golang.org/x/tools/cmd/tipgodoc (from $GOROOT)
	/home/gert/src/golang.org/x/tools/cmd/tipgodoc (from $GOPATH)
package golang.org/x/tools/refactor/lexical: cannot find package "golang.org/x/tools/refactor/lexical" in any of:
	/usr/local/go/src/golang.org/x/tools/refactor/lexical (from $GOROOT)
	/home/gert/src/golang.org/x/tools/refactor/lexical (from $GOPATH)
```

**Comment by minux** [comment]
Reproduced with tip.

$ GOPATH= go get -u all
package cmd/vendor/golang.org/x/arch/arm/armasm: directory
".../go/src/cmd/vendor/golang.org/x/arch/arm/armasm" is not using a known
version control system
package cmd/vendor/golang.org/x/arch/x86/x86asm: directory
".../go/src/cmd/vendor/golang.org/x/arch/x86/x86asm" is not using a known
version control system

**Comment by quchunguang** [comment]
@ianlancetaylor:
No. My GOROOT and GOPATH are difference.

```bashrc
export GOROOT=$HOME/share/go
export GOPATH=$HOME/share/g
export GOROOT_BOOTSTRAP=$HOME/share/go1.4
```

**Comment by adg** [comment]
It's fixed now.
