### ISSUE TITLE
cmd/doc: const block comments apear after the const block in the generated docs

### ISSUE THREAD

**Issue by kostya-sh** [golang/go#12533]
Example:

Source (comment before the const block): http://golang.org/src/crypto/x509/pem_decrypt.go?s=472:490#L13

    // Possible values for the EncryptPEMBlock encryption algorithm.
    const (
        _ PEMCipher = iota
        PEMCipherDES
    ...

Docs: http://golang.org/pkg/crypto/x509/#PEMCipher

More examples:
- http://golang.org/pkg/math/big/#RoundingMode
- http://golang.org/pkg/text/scanner/

**Comment by davecheney** [comment]
@kostya-sh all comments are presented after the block they are attached too, not just consts.

**Comment by kostya-sh** [comment]
@davecheney, it could be the way godoc works now, but I believe it is not intuitive (at least for consts). Docs for const blocks like http://golang.org/pkg/math/big/#RoundingMode clearly demonstrate it. 

> const(
    ToNearestEven RoundingMode = iota // == IEEE 754-2008 roundTiesToEven
    ToNearestAway                     // == IEEE 754-2008 roundTiesToAway
     ....
   )
The following rounding modes are supported.

The following example doesn't look right ;)

**Comment by robpike** [comment]
Working as intended. The descriptions are presented after the items.

**Comment by kostya-sh** [comment]
Should documentation for some const blocks be re-worded instead? It looks ok in the source code but not in the generated HTML. Examples:

- http://golang.org/pkg/text/scanner/ (search for 'The result of Scan')
- http://golang.org/pkg/math/big/#RoundingMode
- http://golang.org/pkg/go/types/#ChanDir
