### ISSUE TITLE
test: "go run run.go -- recover4.go" fails intermittently on arm64

### ISSUE THREAD

**Issue by mwhudson** [golang/go#12549]
The 3 failures I can currently see for linux/arm64 on the dashboard are all this.

**Comment by mwhudson** [comment]
It fails like this:

```
goroutine 1 [running]:
main.memcopy.func1(0x4820041e10)
        /home/mwh/go.arm64/test/recover4.go:32 +0x58
main.memcopy(0x7f88583005, 0xffffb, 0xffffb, 0x482007a000, 0x100000, 0x100000, 0xffffb, 0x0, 0x0)
        /home/mwh/go.arm64/test/recover4.go:39 +0xe0
main.main()
        /home/mwh/go.arm64/test/recover4.go:66 +0x2b8
```

somewhere around 0.5% of the time (47 out of 10000).

**Comment by mwhudson** [comment]
This is starting to feel like a platform bug: the test calls mmap, munmap (seen in strace output) and then accesses the munmapped memory without triggering a fault. Setting GOMAXPROCS=1 or using taskset  to nail the process to a CPU makes it pass.

I can't reproduce it with a similar C program though.

**Comment by davecheney** [comment]
Maybe that test should be pegged to run with GOMAXPROCS=1 only. Are there any POSIX guarentees that munmap in one thread will be immediately visible to another ? I doubt it, 'cos "immediate" is hard to get without explicit synchronisation.

**Comment by nightlyone** [comment]
@davecheney not sure about POSIX, but Linux says that on return of munmap the relevant cache (TLB) is flushed. s. https://www.kernel.org/doc/Documentation/cachetlb.txt and there `flush_tlb_range`

**Comment by mwhudson** [comment]
Ahh, a clue. Here's the output from a failing run of "setarch `uname -m` -R strace  -o trace3.txt -e mmap,munmap ./recover4" (the setarch disables aslr so I can diff things):

```
mmap(0x4000000000, 65536, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4000000000
munmap(0x4000000000, 65536)             = 0
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7fbf000
mmap(0x4820000000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4820000000
mmap(0x481fff0000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x481fff0000
mmap(0x4000000000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4000000000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7faf000
mmap(NULL, 1439992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7e4f000
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7e0f000
mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7d0f000
munmap(0x7fb7d8f000, 262144)            = 0
mmap(0x4820100000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4820100000
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb7d8f000
+++ exited with 2 +++
```

So the problem is that between the munmap and (presumably) the memory access to the munmapped region in memcopy, something calls asks mmap for precisely as many bytes as was munmapped, and the kernel hands back the munmapped address!

**Comment by minux** [comment]
good detective work!

**Comment by mwhudson** [comment]
Heh it failed on ppc64 too: http://build.golang.org/log/55ac422f0e539bec1aa361aca3ba5c423de0f1d3 

Presumably fixed there now too.

**Comment by davecheney** [comment]
Very interesting. All our ppc64 machines are running64 (but i have no idea
if syscall.GetPageSize tells the truth there)
