### ISSUE TITLE
x/mobile/gobind task failed: FileNotFoundException

### ISSUE THREAD

**Issue by ekrivenja** [golang/go#12543]
If project doesn't contain local.properties file, gobind always fails:

gobind FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project_name:gobind'.
> java.io.FileNotFoundException: 
> _some_path_/local.properties (No such file or directory)

Expected behavior:
ANDROID_HOME must be used as a path to Android SDK.
local.properties must be optional

**Comment by ianlancetaylor** [comment]
CC @crawshaw @hyangah
