### ISSUE TITLE
doc: clarify rules regarding corporate contributions

### ISSUE THREAD

**Issue by bradfitz** [golang/go#12542]
Witness the confusion in issue #12452 (Oracle not being listed in AUTHORS).

The contributing documentation should clarify more about how to submit corporate-owned code. (e.g. using your corporate email address in Gerrit, or if a mix of personally- and corp-owned code, making sure first that the corporate name is in the AUTHORS file first, and specifying the copyright holder per commit?).

/cc @rsc @robpike @ianlancetaylor @adg @4ad

**Comment by rsc** [comment]
I don't think we've resolved this in any way.
Anyone want to propose text?

**Comment by rsc** [comment]
Apparently not. Moving to Go 1.6.
