### ISSUE TITLE
cmd/go: `go list ...` with path checking is not vendor experiment-aware

### ISSUE THREAD

**Issue by broady** [golang/go#12547]
Test case:
```
$ export GO15VENDOREXPERIMENT=1
$ cat $GOPATH/src/a/vendor/b/pkg.go
package b // import "b"
$ go list ...
can't load package: package a/vendor/b: code in directory $GOPATH/src/a/vendor/b expects import "b"
```

**Comment by broady** [comment]
Is this a dupe of #12278?

**Comment by ianlancetaylor** [comment]
Perhaps, but at first glance I don't think so.

**Comment by rsc** [comment]
I can't reproduce this with either Go 1.5 or current dev branch, using the directions given in the initial report.

Are you still seeing this problem? With the same test case?

Thanks.

**Comment by rsc** [comment]
Closing due to lack of response.

**Comment by broady** [comment]
Can't reproduce under 1.5.2, so either my initial report was wrong or it got fixed.
