### ISSUE TITLE
cmd/dist: GOARM inference fails with arm64 kernel

### ISSUE THREAD

**Issue by mwhudson** [golang/go#12548]
This is a selfish bug report: the fastest and most reliable 32-bit arm environment I have access to is a armhf chroot on an arm64 system and currently I'm fairly sure it falls back to GOARM=5 when running ./all.bash. I think checking assuming GOARM=7 when uname -m == armv8l would be appropriate.

**Comment by bradfitz** [comment]
Sounds fine.

**Comment by minux** [comment]
Could we reconsider restoring the automatic detection feature?

CL 3973.

**Comment by bradfitz** [comment]
The build is slow enough. I don't want to see it compiling and running a program for a simple check.

Can you modify CL 3973 to make it compile those two probe functions into the dist binary itself, and then just make dist exec its own binary (argv[0]) as a child to do the probe and see whether it crashes? It would at least eliminate the extra compile and disk I/O.

**Comment by minux** [comment]
I will update CL 3973 to do the re-exec itself trick.

I didn't do it before because I was concerned that
os.Args[0] might not be pointing to the program,
and we don't have a portable way to get the current
process' executable path.

**Comment by mwhudson** [comment]
Minux's CL fixed this.
