### ISSUE TITLE
x/mobile/cmd/gomobile: build lost the "libopenal.so" file without error

### ISSUE THREAD

**Issue by DoraemonYu** [golang/go#12550]
Qucik reproduce steps
----
* Make sure go1.5 and gomobile is okay.
* Rename the directory name of "%GOPATH%\pkg\gomobile\android-ndk-r10e\openal" ( such as "00opengl"), OR delete it. 
* Build your code which import the "exp/audio". 

As the result,the output apk will not inculde the "libopenal.so" file in "xxx.apk\lib\armeabi\".
I hope in the build process, gomobile can check  whether "gomobile-openal-soft" is missing or not. if yes,then throw an exception or a clear tip.
This will help developor to know the reason. 
(Currently is builded successfully but lost the "libopenal.so".So after installed apk to device and run,it  will got a crash due to "al: cannot load libopenal.so "  )

History of this issus
---
You can find the actual usage scenario here:
https://github.com/golang/go/issues/12514
when the `gomobile init` failed to download the "gomobile-openal-soft-xxxx.tar.gz" , it will cause this issus in build process.

--------
Thank you sincerely.

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by rakyll** [comment]
There are two issues:

* `gomobile init` shouldn't succeed if it can't download the archive properly.
* We should fail `gomobile build` if libopenal.so is not found.

@crawshaw, should we consider adding checksum hash control to see if the downloaded archive's integrity is not compromised?

**Comment by crawshaw** [comment]
We have a hash: https://github.com/golang/mobile/blob/master/cmd/gomobile/hashes.go#L18

I don't see how gomobile init can succeed if it fails to download OpenAL. I suspect it did fail, but did enough work that gomobile build could run.

There seems to be a bunch of unnecessary tree walking code that if removed will present a nicer error message. I'll send a cl.

**Comment by DoraemonYu** [comment]
o(∩_∩)o Well done!
The issue is fixed. Just now, I do a regression test to make sure it , with the newest gomobile.
With the same steps, it will throw an exception message as below:
```
gomobile: open D:\Gopath\pkg\gomobile\android-ndk-r10e\openal\lib\armeabi\libopenal.so: 
The system cannot find the path specified.
```
The message is enough clear now.
Thanks everybody here.

Additionally, I noticed that an apk file is still created at the same time.
Mmm... It was an illegal zip format file, but can use 7z force to see the structure. It just include a empty size file named "AndroidManifest.xml".
Therefore,in my opinion, if gomobile could delete it incidentally when the problem happened, it may be more better, more friendly to developer. Just a small suggestion for this :)


--------
Thank you sincerely.
