### ISSUE TITLE
x/mobile/gobind: task fails on CentOS

### ISSUE THREAD

**Issue by ekrivenja** [golang/go#12555]
We have a Jenkins running on VM with CentOS:
`CentOS release 6.4 (Final) 
Kernel 2.6.32-358.14.1.el6.x86_64 on an x86_64`

I tried to install Go mobile from Jenkins job and from command prompt as root user few times.
No errors, warnings, etc. $GOPATH/pkg folder looks like contains everything initialized.

But gobind task always fails with the error:
_toolchain partially installed, run \`gomobile init\`_

run `gomobile init` once more doesn't help.

Go 1.5

**Comment by ekrivenja** [comment]
Content of $GOPATH/pkg/gomobile folder

<pre>
[root@buildserver1 workspace]# cd $GOPATH/pkg/gomobile
[root@buildserver1 gomobile]# ls -l
total 16
drwxr-xr-x  4 root root 4096 Sep  9 12:38 android-ndk-r10e
drwxr-xr-x  2 root root 4096 Sep  9 12:38 dl
drwxr-xr-x 28 root root 4096 Sep  9 12:39 pkg_android_arm
-rw-r--r--  1 root root   29 Sep  9 12:39 version
[root@buildserver1 gomobile]# head version
go version go1.5 linux/amd64
</pre>

**Comment by star-tek-mb** [comment]
Is Android SDK installed?

**Comment by ekrivenja** [comment]
Yes, it is. Android SDK path:
`/var/lib/jenkins/tools/android-sdk`

<pre>
[root@buildserver1 gomobile]# gomobile version
gomobile version +c76d5c8 Fri Sep 4 16:23:41 2015 +0000 (android); androidSDK=/var/lib/jenkins/tools/android-sdk/platforms/android-23
</pre>

**Comment by star-tek-mb** [comment]
Try do this in folder __$GOPATH/src/golang.org/x/mobile/example/bind/hello/__:
gomobile bind

**Comment by ekrivenja** [comment]
Done successfully
<pre>
[root@buildserver1 gomobile]# cd $GOPATH/src/golang.org/x/mobile/example/bind/hello/
[root@buildserver1 hello]# gomobile bind
[root@buildserver1 hello]# ls -l
total 876
-rw-r--r-- 1 root root 892421 Sep  9 15:49 hello.aar
-rw-r--r-- 1 root root    333 Sep  9 12:38 hello.go
</pre>

aar file created.

**Comment by star-tek-mb** [comment]
Close issue please

**Comment by ekrivenja** [comment]
The issue is about Gradle gobind task, not about gomobile bind command.

**Comment by star-tek-mb** [comment]
Android Studio installed? May be this help: https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-android-1.

**Comment by ekrivenja** [comment]
Just tried to run in my project folder
`gomobile bind -target=android my_package`
It works, but the Gradle task fails. On Windows machine everything is fine in Gradle too.

**Comment by hyangah** [comment]
Hi @ekrivenja 

Is the error message "toolchain partially installed, run `gomobile init`" from Android Studio?

Can you update the build.gradle file in example/bind/android/hello to increase the verbosity

   GOMOBILEFLAGS="-x -v"

and share the output error message with me?

Also, make sure the GOPATH in the file was configured correctly.

Thanks!

**Comment by ekrivenja** [comment]
Hi @hyangah,
thank you for the hint, problem solved.
It was in GOPATH, I have it defined in build.gradle with multiple paths, and used ';' as hardcoded separator. This is a reason why it worked on Windows, but failed on CentOS.
Replacing separator on File.pathSeparator solved all issues, now it works on both platforms.

@star-tek-mb, thank you for your patience.

**Comment by ekrivenja** [comment]
Not an issue.
