### ISSUE TITLE
cmd/go: TestGoTestCpuprofileLeavesBinaryBehind and TestGoTestDashOWritesBinary fail

### ISSUE THREAD

**Issue by frederich** [golang/go#12554]
The both test below fail on go1.5.1 Windows amd64.

--- FAIL: TestGoTestCpuprofileLeavesBinaryBehind (0.83s)
        go_test.go:251: running testgo [test -cpuprofile errors.prof errors]
        go_test.go:266: standard output:
        go_test.go:267: ok      errors  0.131s

        go_test.go:158: remove E:\tmp\gotest793636497: Das Verzeichnis ist nicht leer.
--- FAIL: TestGoTestDashOWritesBinary (1.21s)
        go_test.go:251: running testgo [test -o E:\tmp\gotest402419724\myerrors.test.exe errors]
        go_test.go:266: standard output:
        go_test.go:267: ok      errors  0.137s

        go_test.go:158: remove E:\tmp\gotest402419724: Das Verzeichnis ist nicht leer.
FAIL

**Comment by bradfitz** [comment]
Does `go test -short cmd/go` pass on the same machine?

**Comment by ianlancetaylor** [comment]
This is probably another instance of issue #9606 .

**Comment by frederich** [comment]
Go test pass on the same machine. 
>go test -short cmd/go
ok      cmd/go  54.011s

But sometimes all.bat fails sometimes not. I've the same suspicion like Ian.

**Comment by alexbrainman** [comment]
> But sometimes all.bat fails sometimes not.

If it comes and goes, it cannot be issue #9606 - if you had read-only files in your temp directory, they would be there all the time.

Unfortunately I cannot reproduce the issue here. But I will look for it.

Alex

**Comment by rsc** [comment]
Assuming this is #9606.
