### ISSUE TITLE
mime: Comment for (*WordDecoder).Decode is wrong

### ISSUE THREAD

**Issue by nuss-justin** [golang/go#12568]
The comment for Decode states that "If word is not a valid RFC 2047 encoded-word, word is returned unchanged.", but the implementation always returns an empty string for not RFC 2047 encoded words.

The comment should be updated to represent the actual implementation.

**Comment by bradfitz** [comment]
Or even Go 1.5.2, since it's just a doc change, @ianlancetaylor?

**Comment by ianlancetaylor** [comment]
Sure, 1.5.2 is fine with me.  I don't know anything about this code but the issue does suggest that the comment is completely wrong.

**Comment by rsc** [comment]
Not important enough for Go 1.5.2. There's too much already.

**Comment by bradfitz** [comment]
This is a doc fix.
