### ISSUE TITLE
runtime: re-organize arch-specific files

### ISSUE THREAD

**Issue by minux** [golang/go#12563]
Right now, there are a lot of arch specific files in the runtime
directory. Some of them quite small.

For example, for ppc64, all these files is ppc64 arch-specific:
arch1_ppc64.go, arch_ppc64.go, zgoarch_ppc64.go.

We can't remove zgoarch_ppc64.go and it' auto-generated
anyway. But we can combine arch1_ppc64.go and arch_ppc64.go
into one file though.

Any other ideas?

PS: This problem is brought up in https://golang.org/cl/14447.

**Comment by rsc** [comment]
Actually I guess this is just done. There will be other cleanup in the runtime but we don't need a bug open for all possible cleanup.
