### ISSUE TITLE
fmt: Sscanf , str include "

### ISSUE THREAD

**Issue by scroot** [golang/go#12564]
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {

	cmd := exec.Command(`c:\windows\system32\where.exe`, `/f`, "/t", "*.txt")
	buf, err := cmd.Output()
	if err != nil {
		fmt.Println(err)
		return
	}
	var i int
	var str string
	fmt.Sscanf(string(buf), `%d   2015/8/23      12:59:38  "%s"`, &i, &str)
	fmt.Println(i, str)
	fmt.Fprintf(os.Stdout, "%s", buf)

}

运行...

1649 C:\Windows\System32\WindowsCodecsRaw.txt"
      1649   2015/8/23      12:59:38  "C:\Windows\System32\WindowsCodecsRaw.txt"

**Comment by scroot** [comment]
system: window 10 x64 
go version:  go1.5.1 windows/amd64

**Comment by adg** [comment]
What's the issue?

**Comment by minux** [comment]
I think what the OP meant is this program:
http://play.golang.org/p/fO2iXLrGUU

fmt.Sscanf(`1649 2015/8/23 12:59:38
"C:\Windows\System32\WindowsCodecsRaw.txt"`, `%d   2015/8/23      12:59:38
 "%s"`, &i, &str)

The scanned str will contain the right double-quote character.

This is working as intended. Scanf %s will keep scanning until it encounters
any space characters.

Quote https://golang.org/pkg/fmt
...
%s and %v on strings scan a space-delimited token
...


PS: Please ask questions like this on the mailing list. If you use English,
golang-nuts, or if you prefer Chinese, golang-china.
