### ISSUE TITLE
how to set default parameter value by one function?

### ISSUE THREAD

**Issue by acrazing** [golang/go#12566]
will, I do as follow:

```
func defaultValue(d interface{}, data ...interface{}) interface{} {
    if len(data) > 0 {
        return data[0]
    }
    return d
}
```

and then I call in another function as follow

```
func line(data ...string) {
    fmt.Println(defaultValue("default", data...))
}
```
but I received an error:

```
cannot use data (type []string) as type []interface {} in argument to defaultValue
```

why can we converse `string` to `interface{}` but cannot converse `[]sting` to `[]interface{}`?

**Comment by stemar94** [comment]
Could you be more consistent in defaultParam/defaultValue/defaultString. Seems like you mixed them up quite a bit.

**Comment by acrazing** [comment]
modified

**Comment by stemar94** [comment]
Ok then here is a link to the playground with the extracted issue.
http://play.golang.org/p/iYudv5V7n3

I'm not sure, if this behavior is intended or not.
Maybe change subject to []T... not convertable to ...interface{} to get more attention.

**Comment by stemar94** [comment]
And delete all unnecessary posts I will do so as well.

**Comment by bradfitz** [comment]
Please ask questions on the golang-nuts mailing list. We only use our issue tracker for bugs. Thanks!

See http://golang.org/doc/faq#convert_slice_of_interface
