### ISSUE TITLE
cmd/go: Add -json flag to go env command

### ISSUE THREAD

**Issue by mattfarina** [golang/go#12567]
Getting the go environment is useful for tools built to compliment the local environment. Being able to parse the Go environment easily would be useful. Currently, `go env` provides a listing of the Go environment (including defaults not always available such as `$GOPATH`) and `go env [VAR]` provides the value of an individual variable.

It would be useful to get the output of `go env` as a json string as well as a listing.

**Comment by joefitzgerald** [comment]
I would also very much like this flag to be available for `go env`. Currently, in [`go-plus`](https://github.com/joefitzgerald/go-plus), I use regular expressions to parse this information - and there is variance between platforms in the output - notably between windows and other platforms.

Would something like this be acceptable as a contribution? If so, I will go ahead and make the necessary changes and submit it.

**Comment by adg** [comment]
What is the variance between platforms, and how would the `-json` flag remove that variance?

**Comment by joefitzgerald** [comment]
@adg: the variance:

* [plan9](https://github.com/golang/go/blob/b7fa4f27ba0c127512f2c4808c628efe842ff660/src/cmd/go/env.go#L94-L105)
* [windows](https://github.com/golang/go/blob/b7fa4f27ba0c127512f2c4808c628efe842ff660/src/cmd/go/env.go#L108) (e.g. `set GOARCH=amd64`) 
* [all other platforms](https://github.com/golang/go/blob/b7fa4f27ba0c127512f2c4808c628efe842ff660/src/cmd/go/env.go#L92) (e.g. `GOARCH="amd64"`)

The variance is explained by the fact that `go env` output is interpretable as a shell script (and this is a perfectly valid reason to have variance).

The rationale for JSON is that some tools (e.g. editor packages / plugins) aren't interested in shell scripts as output; they're interested in a structured format that does not vary by platform. Not unsurprisingly, the output of `go env` can be used to detect many things about a user's go installation(s) that can then minimize the amount of explicit configuration they need to do it heir tool(s) of choice.

In some respects, adding a json option will just add code to such tools (if they wish to function correctly with prior versions of go, they'll still need to handle the shell script output variant), but at least it makes future releases easier to work with.

**Comment by adg** [comment]
Seems like a reasonable feature to me. Happy to review the change.

**Comment by mattfarina** [comment]
@joefitzgerald did you want to propose the change to gerrit or shall I? I'm happy to review something if you'd like to.

**Comment by joefitzgerald** [comment]
@mattfarina It'll be a few days before I can get to this. If you have the time now, please go for it.

**Comment by haya14busa** [comment]
I'm assuming that this feature is still worth considering to implement. sent a CL.
