### ISSUE TITLE
difference between len and capacity of  a slice ?

### ISSUE THREAD

**Issue by getpradeep9** [golang/go#12565]
What is the difference between len and cap of a slice, seems both sounds same

**Comment by davecheney** [comment]
If I have a bottle with a capacity of 1 litre, but I have only filled it with 500ml of liquid, are they the same ?

This blog post may be useful http://blog.golang.org/go-slices-usage-and-internals

In future, please direct these questions to the golang-nuts mailing list, the issue tracker is only for bugs, feature requests and proposals.
