### ISSUE TITLE
net/url: parsing "localhost:8080" results in a url.URL with schema "localhost"

### ISSUE THREAD

**Issue by nodirt** [golang/go#12585]
http://play.golang.org/p/9zinaw70z8

```go
u, err := url.Parse("localhost:8080")
```

here u is `&url.URL{Scheme:"localhost", Opaque:"8080"}`
should be `&url.URL{Host:"localhost:8080"}` 

Will fix.

**Comment by bradfitz** [comment]
Not a bug. `url.Parse` parses URLs. That's not a URL. A URL starts with a scheme.

If you want to split a host and a port there is http://golang.org/pkg/net/#SplitHostPort
