### ISSUE TITLE
x/mobile: can't create TCP server on Android

### ISSUE THREAD

**Issue by hmgle** [golang/go#12584]
I try to port a TCP server to Android using gomobile. The apk always fails on:

```
l, e := net.Listen("tcp", "localhost:0")
```

**Comment by bradfitz** [comment]
This isn't a great bug report. How does it fail? With what? Does it explode, or is e != nil? If e is not nil, what is e? If it explodes, how does it explode?

/cc @crawshaw

**Comment by hmgle** [comment]
I am a beginner in Android, so I don't know how to output the err when runing this apk:

```
l, e := net.Listen("tcp", "localhost:0")
if e != nil {
	log.Fatal(e) // exit on this line, but I don't know how to show the err on Android
}
```

Can anyone tell me the correct way to debug it?

**Comment by bradfitz** [comment]
Please ask questions on the golang-nuts mailing list. We only use the bug tracker for tracking bugs.

Your apk probably just doesn't have the right permissions listed in its manifest.
