### ISSUE TITLE
cmd/compile: escape analysis miss

### ISSUE THREAD

**Issue by davecheney** [golang/go#12588]
```
package main

type A struct {
        b [3]uint64
}

func f(a A) int {
        for i, x := range &a.b { // & to avoid making a copy of a.b
                if x != 0 {
                        return 64*i + int(x)
                }
        }
        return 0
}

func main() {
        var a A
        f(a)
}
```
```
% go build -gcflags=-m escape.go
# command-line-arguments
./escape.go:7: moved to heap: a
./escape.go:8: &a.b escapes to heap
```
Why does taking the address of field of a local value cause the formal parameter to escape ?

/cc @dr2chase

**Comment by cznic** [comment]
I'd guess `int(x)` causes that. At least at some (early) stage it's not distinguished from a function call.

**Comment by dr2chase** [comment]
My guess is that we don't do the right thing for range and that escapes &a.b, and thus a nail was wanting and the kingdom falls.  I'll put it on my list for after SSA coverage is done.
