### ISSUE TITLE
url parse get different scheme

### ISSUE THREAD

**Issue by gouyang** [golang/go#12586]
The result of [1] is
```
scheme for 192.168.10.1:8080 is 
scheme for localhost:8080 is localhost
```
I'm expecting both of them should be blank.

[1] http://play.golang.org/p/IvbWs3RitP

**Comment by bradfitz** [comment]
Not a bug. url.Parse parses URLs. That's not a URL. A URL starts with a scheme.

If you want to split a host and a port there is http://golang.org/pkg/net/#SplitHostPort

**Comment by gouyang** [comment]
but why it get different result?

**Comment by adg** [comment]
Because `"localhost:8080"` is a valid URL with scheme `"localhost"`, just like `"mailto:foo@example.com"` has scheme `"mailto"`.

But in this case you don't actually want to parse these as URLs, because they're not URLs.

**Comment by gouyang** [comment]
thanks, clear now
