### ISSUE TITLE
building GOARCH=386 c-shared library using gccgo

### ISSUE THREAD

**Issue by adyuor** [golang/go#12593]
Hello,

I have been googling to figure out a way to build 32 bit x86 c-shared libraries on linux platform using gccgo. The go build command only seems to support linux/x64 architecture on go1.5 but some online articles suggest it can be done by using gccgo directly. I have tried installing gccgo and building libraries but have not been very successful in running the c-shared example showed in  http://blog.ralch.com/tutorial/golang-sharing-libraries/ (loading a c-shared lib in a c program).  I get this error "fatal error: cgo callback before cgo call". The go build command also has a dependency on libgolibbegin.so but I could not find it anywhere. Can anyone give  pointers on how to achieve this mode ?

Thanks !!

**Comment by minux** [comment]
Please ask questions on the golang-nuts mailing list.
I'm sure gophers there will be able to help.

The issue tracker is for proposals and bug reports only.
Thanks.
