### ISSUE TITLE
tour: [Use of Left and right arrow keys to go to previous and next page  ]

### ISSUE THREAD

**Issue by namangt68** [golang/go#12595]
Context: https://tour.golang.org/basics/3

It will be really user friendly if the Go tour uses left and right arrow keys to go to previous and next page. It can be easily implemented in javascript like 

```javascript

function leftArrowPressed() {
   // links to prev
}

function rightArrowPressed() {
   // links to next
}

document.onkeydown = function(evt) {
    evt = evt || window.event;
    switch (evt.keyCode) {
        case 37:
            leftArrowPressed();
            break;
        case 39:
            rightArrowPressed();
            break;
    }
};

```

**Comment by cespare** [comment]
You can use page-up and page-down. See the welcome page: https://tour.golang.org/welcome/1

**Comment by adg** [comment]
Page Up and Page Down keys already do this. Those seem like the more natural keys for this purpose,
