### ISSUE TITLE
runtime: Extremely slow append

### ISSUE THREAD

**Issue by m-m-f** [golang/go#12596]
While trying to reproduce an OOM I found out that appending to a slice is extremely slow. Well beyond what one would expect, even accounting for slice growth and consequent data copy.

The following sample code appends repeatedly a 2kB slice to a slice. I tried go 1.5.1 on linux x86-64 and  mac osx. between 500MB and 1.5GB the growth slows to a crawl. 

Sample code: 
```
package main
import (
	"fmt"
	"time"
)

func main() {
	slimslice := make([]uint64, 256, 256)
	fatslice := make([]uint64, 0)
	i := 0
	lastlog := time.Now()
	var lastsize uint64
	for {
		i++
		fatslice = append(fatslice, slimslice...)
		if i%(1024*128) == 0 {
			now := time.Now()
			size := (uint64(len(fatslice)) * 8) / 1024 / 1024
			fmt.Println("written ", size, "MB total. Speed last chunk: ", float64(size-lastsize)/now.Sub(lastlog).Seconds(), "MB/s")
			lastlog = now
			lastsize = size
		}
	}
}
```

Output:
```
$ ./slowappend 
written  256 MB total. Speed last chunk:  356.02722734909923 MB/s
written  512 MB total. Speed last chunk:  439.0343920798045 MB/s
```
Then is basically gets stuck with 100% to 200% cpu

Profiler output:
```
$ go tool pprof -text ./slowappend  /tmp/profile569733554/cpu.pprof
3.49s of 3.53s total (98.87%)
Dropped 18 nodes (cum <= 0.02s)
      flat  flat%   sum%        cum   cum%
     2.29s 64.87% 64.87%      2.29s 64.87%  runtime.memmove
     0.43s 12.18% 77.05%      0.84s 23.80%  runtime.scang
     0.34s  9.63% 86.69%      0.34s  9.63%  runtime.memclr
     0.29s  8.22% 94.90%      0.41s 11.61%  runtime.readgstatus
     0.09s  2.55% 97.45%      0.12s  3.40%  runtime.atomicload
     0.03s  0.85% 98.30%      0.03s  0.85%  runtime.nop
     0.01s  0.28% 98.58%      0.04s  1.13%  runtime.heapBitsSweepSpan
     0.01s  0.28% 98.87%      0.85s 24.08%  runtime.parfordo
         0     0% 98.87%      2.61s 73.94%  main.main
         0     0% 98.87%      0.84s 23.80%  runtime.backgroundgc
         0     0% 98.87%      0.04s  1.13%  runtime.bgsweep
         0     0% 98.87%      0.84s 23.80%  runtime.gc
         0     0% 98.87%      0.84s 23.80%  runtime.gc.func1
         0     0% 98.87%      0.84s 23.80%  runtime.gcscan_m
         0     0% 98.87%      3.49s 98.87%  runtime.goexit
         0     0% 98.87%      0.04s  1.13%  runtime.gosweepone
         0     0% 98.87%      0.04s  1.13%  runtime.gosweepone.func1
         0     0% 98.87%      2.47s 69.97%  runtime.growslice
         0     0% 98.87%      2.47s 69.97%  runtime.growslice_n
```

Machine configuration: 64GB x86-64 Ubuntu 14.04 on a VM, Go 1.5.1 (similar results with Go 1.5).

**Comment by randall77** [comment]
You're trying to allocate more memory than your system is giving you.  I tried this on my mac (12GB physical) and it runs well up to around 4GB, then performance varies widely depending on whether fatslice is resized or not in the given printing interval.  If it is not resized, writes go really quickly.  If it is resized the resulting copy makes the machine swap like crazy.

Tried it on tip, which is approximately 1.5.1.

Keep in mind that Go keeps the heap at ~2x live data, so a 4GB fatslice means you get an 8GB heap.

Check your ulimit.  Despite having a 64GB machine, you might not be getting anywhere near that much memory from the OS.

written  256 MB total. Speed last chunk:  387.33416552482265 MB/s
written  512 MB total. Speed last chunk:  664.7988847687083 MB/s
written  768 MB total. Speed last chunk:  296.2387515759337 MB/s
written  1024 MB total. Speed last chunk:  418.4479452202733 MB/s
written  1280 MB total. Speed last chunk:  1245.5545925483186 MB/s
written  1536 MB total. Speed last chunk:  274.5760685738801 MB/s
written  1792 MB total. Speed last chunk:  9484.472603119093 MB/s
written  2048 MB total. Speed last chunk:  782.7828789349559 MB/s
written  2304 MB total. Speed last chunk:  126.67826470178927 MB/s
written  2560 MB total. Speed last chunk:  6804.900421446622 MB/s
written  2816 MB total. Speed last chunk:  6438.110232568936 MB/s
written  3072 MB total. Speed last chunk:  50.93872987533951 MB/s
written  3328 MB total. Speed last chunk:  6688.699836155593 MB/s
written  3584 MB total. Speed last chunk:  5081.787196270413 MB/s
written  3840 MB total. Speed last chunk:  38.45605001592904 MB/s
written  4096 MB total. Speed last chunk:  9308.63393978841 MB/s
written  4352 MB total. Speed last chunk:  9095.55926018 MB/s
written  4608 MB total. Speed last chunk:  49.48859244428994 MB/s
written  4864 MB total. Speed last chunk:  6701.735943331378 MB/s
written  5120 MB total. Speed last chunk:  4781.284081824057 MB/s
written  5376 MB total. Speed last chunk:  4813.9282288055565 MB/s

**Comment by m-m-f** [comment]
Randall, thanks for giving it a try. I checked, and the machine is not swapping (no kswap to be seen, the go process gets > 100% cpu). Even preallocating the slice doesn't help, although it changes things at the beginning of the execution.

Ulimits are not an issue here as allocations beyond limits fail, do not hang which is the behavior I'm seeing.

**TL:DR; Even preallocation does not help, preallocating 4GB+ hangs the process.**

I modified the program to print cumulative stats every second. I tried preallocating from 0 to a lot of memory (8GB). The behavior is that when it hits the wall it will stop progressing.  Preallocating space for the slice highlights a deeper issue (see below). Here's the code I'm using:
```
package main

import (
	"fmt"
	"time"
)

func main() {
	//	defer profile.Start(profile.CPUProfile).Stop()

	slimslice := make([]uint64, 256, 256)
	fatslice := make([]uint64, 0,1024*1024*1024/8)
	i := 0
	start := time.Now()
	go func() {
		for {
			time.Sleep(time.Second)
			size := (uint64(len(fatslice)) * 8) / 1024 / 1024
			fmt.Println("written ", size, "MB total. Average speed since start: ", float64(size)/time.Since(start).Seconds(), "MB/s")
		}
	}()	
	for {
		i++
		fatslice = append(fatslice, slimslice...)
	}
}
```


Output with 1GB preallocated:
```
$ ./slowappend 
written  1024 MB total. Average speed since start:  936.4751236023931 MB/s
written  1024 MB total. Average speed since start:  483.77856183038585 MB/s
written  1280 MB total. Average speed since start:  410.652703013525 MB/s
written  1280 MB total. Average speed since start:  310.8820116860208 MB/s
written  1280 MB total. Average speed since start:  250.11781047154787 MB/s
written  1280 MB total. Average speed since start:  209.21983321553577 MB/s
written  1280 MB total. Average speed since start:  179.81955967230124 MB/s
written  1280 MB total. Average speed since start:  157.6632726556781 MB/s
written  1280 MB total. Average speed since start:  140.36683865712325 MB/s
```
and so on.

This is with 2GB preallocated:
```
$ ./slowappend 
written  2048 MB total. Average speed since start:  2046.9358676382342 MB/s
written  2048 MB total. Average speed since start:  1023.4573572801545 MB/s
written  2048 MB total. Average speed since start:  682.2518109450716 MB/s
written  2048 MB total. Average speed since start:  511.71980475059 MB/s
written  2048 MB total. Average speed since start:  409.3896411100044 MB/s
written  2048 MB total. Average speed since start:  341.1667580950821 MB/s
written  2048 MB total. Average speed since start:  292.436268329878 MB/s
``` and so on.

With 4GB preallocated it completely hangs.

**Comment by m-m-f** [comment]
If this helps, on the 4GB preallocated example (which if let go, eventually overnight reached out of memory) here's the output of:
```
sudo perf record -p `pidof slowappend` -- sleep 10
perf report
```

```
Samples: 65K of event 'cpu-clock', Event count (approx.): 16316250000                                          
 28.65%  slowappend  [kernel.kallsyms]  [k] copy_page_rep
 26.73%  slowappend  slowappend         [.] runtime.scang
 21.28%  slowappend  slowappend         [.] runtime.readgstatus
 10.04%  slowappend  slowappend         [.] runtime.atomicload
  6.00%  slowappend  [kernel.kallsyms]  [k] clear_page_c
  3.14%  slowappend  slowappend         [.] runtime.nop
  1.99%  slowappend  slowappend         [.] runtime.memmove
  0.51%  slowappend  slowappend         [.] runtime.memclr
  0.36%  slowappend  [kernel.kallsyms]  [k] migrate_page_move_mapping
  0.20%  slowappend  [kernel.kallsyms]  [k] _raw_spin_unlock_irqrestore
  0.09%  slowappend  [kernel.kallsyms]  [k] clear_huge_page
  0.08%  slowappend  [kernel.kallsyms]  [k] free_hot_cold_page
  0.07%  slowappend  [kernel.kallsyms]  [k] __do_softirq
  0.06%  slowappend  [kernel.kallsyms]  [k] get_page_from_freelist
  0.05%  slowappend  [kernel.kallsyms]  [k] migrate_page_copy
  0.04%  slowappend  slowappend         [.] runtime.retake
```

**Comment by ianlancetaylor** [comment]
@m-m-f How much physical RAM do you have on your machine.  This really looks like the kernel trying to cope with a process that is using too much memory.

**Comment by cespare** [comment]
@ianlancetaylor first post says 64GB

**Comment by ianlancetaylor** [comment]
Thanks, I missed that.  I also see that it is a 64GB VM.  So we still don't know how much physical RAM is there.  I have no idea how large VMs behave.

**Comment by m-m-f** [comment]
@ianlancetaylor it looks like a lot of time is spent in copying pages. I have control over the physical machine (2 6aGB VMs on 128GB physical memory).

This is on the physical server (there's plenty of memory free) with 4GB preallocated slice:
```
$ ./slowappend
written  4096 MB total. Average speed since start:  2900.3322907731563 MB/s
written  4096 MB total. Average speed since start:  1669.0719558305143 MB/s
written  4096 MB total. Average speed since start:  1185.689496049268 MB/s
written  5120 MB total. Average speed since start:  1149.3474968838113 MB/s
written  5120 MB total. Average speed since start:  938.5913028690825 MB/s
written  5821 MB total. Average speed since start:  901.7436961929993 MB/s
written  6400 MB total. Average speed since start:  858.4219129594568 MB/s
written  6400 MB total. Average speed since start:  756.880534135437 MB/s
written  6400 MB total. Average speed since start:  676.8237929120075 MB/s
written  6400 MB total. Average speed since start:  612.0829319347262 MB/s
written  6400 MB total. Average speed since start:  556.8368921547082 MB/s
written  6400 MB total. Average speed since start:  512.2577558905392 MB/s
written  6400 MB total. Average speed since start:  474.2879826971503 MB/s
```

This is with 0 capacity slice:
```
$ ./slowappend
written  385 MB total. Average speed since start:  384.8339553084691 MB/s
written  753 MB total. Average speed since start:  376.3463321473892 MB/s
written  1176 MB total. Average speed since start:  391.85440793153253 MB/s
written  1470 MB total. Average speed since start:  367.3676763671786 MB/s
written  1838 MB total. Average speed since start:  367.4730807509725 MB/s
written  2298 MB total. Average speed since start:  382.8757971334142 MB/s
written  2872 MB total. Average speed since start:  410.15824536481387 MB/s
written  2872 MB total. Average speed since start:  358.89312306352423 MB/s
written  3591 MB total. Average speed since start:  398.88373527462 MB/s
written  3591 MB total. Average speed since start:  358.9978060331447 MB/s
written  3591 MB total. Average speed since start:  326.3654083858592 MB/s
written  4343 MB total. Average speed since start:  361.8212066540727 MB/s
```
So the speed when go starts changing the size of the slice seems fairly constant and in this case around 350MBps. This is likely to be close to 1/100 of the memory bandwidth of this server...

Any ideas? and btw, can anyone reproduce this or is it just my machine?

As s side note, go 1.3.1 seems to

**Comment by rsc** [comment]
Here is a simplified version of your Go program:

	package main
	
	import (
		"fmt"
		"time"
	)
	
	func main() {
		slimslice := make([]uint64, 256, 256)
		fatslice := make([]uint64, 0, 1024*1024*1024/8)
		start := time.Now()
		for {
			fatslice = append(fatslice, slimslice...)
			if len(fatslice)+len(slimslice) > cap(fatslice) {
				size := len(fatslice) * 8
				t := time.Since(start).Seconds()
				fmt.Printf("%d MB at %.2f = %.2f MB/s\n", size>>20, t, float64(size)/(1<<20)/t)
			}
		}
	}

On my Linux workstation with 32 GB of RAM, the program prints:

	1024 MB at 0.16 = 6234.55 MB/s
	1280 MB at 0.48 = 2657.89 MB/s
	1600 MB at 0.83 = 1926.98 MB/s
	2000 MB at 1.27 = 1576.00 MB/s
	2500 MB at 1.78 = 1400.88 MB/s
	3125 MB at 2.43 = 1285.36 MB/s
	3906 MB at 3.55 = 1100.12 MB/s
	4882 MB at 5.44 = 896.84 MB/s
	6103 MB at 10.71 = 569.75 MB/s
	7629 MB at 29.75 = 256.48 MB/s
	9536 MB at 53.44 = 178.47 MB/s

Here is a roughly equivalent C program:

	#include <stdio.h>
	#include <sys/time.h>
	#include <stdlib.h>
	#include <string.h>
	
	char zero[256*8];
	
	double
	now(void)
	{
		struct timeval tv;
		gettimeofday(&tv, 0);
		return (double)tv.tv_sec+tv.tv_usec/1e6;
	}
	
	int 
	main(void)
	{
		char *p;
		long long size, i;
		double start, t;
		
		start = now();
		size = 1<<30;
		for(;;) {
			p = malloc(size);
			for(i=0; i<size; i+=sizeof zero)
				memmove(p+i, zero, sizeof zero);
			t = now() - start;
			printf("%lld MB at %.2f = %.2f MB/s\n", size>>20, t, size/(double)(1<<20)/t);
			size += size/4;
		}
	
		return 0;
	}

On the same workstation it prints:

	1024 MB at 0.15 = 6736.14 MB/s
	1280 MB at 0.32 = 3962.02 MB/s
	1600 MB at 0.54 = 2981.77 MB/s
	2000 MB at 0.80 = 2486.34 MB/s
	2500 MB at 1.14 = 2197.36 MB/s
	3125 MB at 1.55 = 2011.59 MB/s
	3906 MB at 2.07 = 1884.13 MB/s
	4882 MB at 2.72 = 1793.49 MB/s
	6103 MB at 5.37 = 1137.05 MB/s
	7629 MB at 18.39 = 414.96 MB/s
	9536 MB at 40.92 = 233.07 MB/s

This is the same behavior. The program is getting ahead of what the operating system can give it, and the operating system is working hard to free up more memory. Even though you have more memory on the machine, it's in use: freeing it up is expensive. Maybe that's swapping or maybe not, but either way it's hard.

The C program does not free any of the buffers because neither does the Go program. Although the garbage collector does reclaim the memory, the allocation pattern is such that each new allocation cannot use the memory the program has available so it must ask for more from the operating system. (Go does release memory to the operating system at a gradual pace, but this program runs far ahead of that.)

I think this is working as expected, more or less, at least given the current implementation of Linux.
