### ISSUE TITLE
x/net/context: Method called TODO

### ISSUE THREAD

**Issue by willfaught** [golang/go#12591]
https://godoc.org/golang.org/x/net/context#TODO

>func TODO() Context
>
>TODO returns a non-nil, empty Context. Code should use context.TODO when it's unclear which Context to use or it's is not yet available (because the surrounding function has not yet been extended to accept a Context parameter). TODO is recognized by static analysis tools that determine whether Contexts are propagated correctly in a program.

I'm pretty sure that's a search-replace mistake? Wasn't this called something like Root before?

**Comment by cespare** [comment]
No, TODO is intentional and has existed since the project was open-sourced as far as I can recall.

There's no Root; perhaps you're thinking of Background.

**Comment by cespare** [comment]
@willfaught @Sajmani talked about it a bit in a talk about x/net/context that he gave. See, for example, this slide:

https://talks.golang.org/2014/gotham-context.slide#21

**Comment by willfaught** [comment]
Woops, OK. :)

**Comment by Sajmani** [comment]
I'm happy to review a CL improving the comment on the TODO method, if it's
unclear.

**Comment by willfaught** [comment]
The last sentence makes it somewhat clear what's going on. I focused on the first couple sentences, in which TODO really does read like a placeholder. Perhaps mentioning static analysis in the first sentence would make a quick reading clearer. I think it's also the casing, since it's arguably atypical and un-idiomatic (I would expect ToDo; it's not an initialism). But I can understand why it's spelled like that, in this case.
