### ISSUE TITLE
x/mobile/cmd/gomobile: bind -target=ios produces an invalid framework

### ISSUE THREAD

**Issue by hyangah** [golang/go#12604]
It results in an error: bundle format unrecognized, invalid, or unsuitable

As s@ pointed out, it's missing info.plist in Resources file.
https://groups.google.com/forum/#!topic/golang-nuts/NqYUz0dq034

We didn't notice this problem because when releasing Ivy, we didn't use the framework - we used the fat .a file and header files directly.

/cc @crawshaw

**Comment by sridharv** [comment]
You should be able to build an IPA which depends on the framework without this as well. As far as I can see  it is only needed if you attempt to codesign the framework manually.

**Comment by scisci** [comment]
Correct, its still possible to link against the framework even though it is incomplete. When I brought up this issue, I was actually trying to embed the framework into my binary which was bringing up these errors. That was the incorrect approach to begin with, so I would say this is low priority.

However, if you want to make a well formed framework you need to make sure to symlink the Resources folder to the root level and also have an Info.plist in there.

But again, its unnecessary if you are just linking against a static framework.
