### ISSUE TITLE
Suggestion: Enhance array initializer like 1..10 as Groovy Lang does

### ISSUE THREAD

**Issue by zhouzhefu** [golang/go#12607]
Initialize an array [10]int {1,2,3,4,5,6,7,8,9,10} is now shorten as 1..10 in Groovy lang, which is quite useful when a fixed size loop is required but the index is totally not interested. For example, to do this you have to: 
```go
for i:=0; i<10;i++ {/*loop logic*/}
```
or, 
```go
for range []int {0,1,2,3,4,5,6,7,8,9} {/*loop logic*/}
```
Neither of them looks great, and the latter turns impractical when the range becomes 1..100. But if a range array initializer 1..10 is there, it becomes very neat: 
```go
for range 1..10 {/*loop logic*/}
```
All we want is a 10-times loop, and it no more no less done this job. 

Please consider this enhancement for the future release.

**Comment by minux** [comment]
if you want to loop from 1 to 99, then just use
`for i := 1; i < 100; i++ {}`.

It's not Go's style to add syntax sugars just to
reduce some typing.

PS: you can use
```
for i := range [99]struct{}{} {
		println(i+1)
}
```
to archive the same without introducing new
syntax. However, this style is not considered
idiomatic Go.

**Comment by zhouzhefu** [comment]
Understand. Thank you for explanation.
