### ISSUE TITLE
appengine/aetest: appengine.IsDevAppServer() returns false

### ISSUE THREAD

**Issue by PSG-Luna** [golang/go#12603]
When running tests under the new google.golang.org/appengine/aetest package, appengine.IsDevAppServer() returns false, which breaks functionality relying on it to determine whether to run production or dev code.

/cc @okdave, @corollax, @jbuberel

**Comment by okdave** [comment]
@PSG-Luna what type of prod vs. dev behaviour are you trying to guard against?

Also, would you mind re-filing this in the app engine SDK issue tracker?
https://code.google.com/p/googleappengine/issues/entry?template=Go%20defect

**Comment by PSG-Luna** [comment]
@okdave I've created https://code.google.com/p/googleappengine/issues/detail?id=12342 and added the information you asked for there.

**Comment by okdave** [comment]
Thanks. I'll follow up there.
