### ISSUE TITLE
net/http Request.RequestURI returns the incorrect value

### ISSUE THREAD

**Issue by diogogmt** [golang/go#12613]
Instead of returning the path up to the query string it includes the query string in the URI, for example:

Instead of this:
* POST /some/path.html?key=value  		/some/path.html
* GET http://foo.bar/a.html?key=value 		/a.html
* HEAD /xyz?a=b HTTP/1.1 		                /xyz

It returns this:
* POST /some/path.html?key=value  		/some/path.html?key=value
* GET http://foo.bar/a.html?key=value 		/a.html?key=value
* HEAD /xyz?a=b HTTP/1.1 		                /xyz?a=b

**Comment by bradfitz** [comment]
No, this is working as designed and as documented:

http://golang.org/pkg/net/http/#Request

        // RequestURI is the unmodified Request-URI of the
        // Request-Line (RFC 2616, Section 5.1) as sent by the client
        // to a server. Usually the URL field should be used instead.
        // It is an error to set this field in an HTTP client request.
        RequestURI string
