### ISSUE TITLE
x/mobile/bind: reduce Java object generation

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12619]
Code generated by gobind today looks like

```
    public static boolean Bool(boolean p0) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        boolean _result;
        _in.writeBool(p0);
        Seq.send(DESCRIPTOR, CALL_Bool, _in, _out);
        _result = _out.readBool();
        return _result;
    }
```

The Seq objects clean up C allocated memory with a finalizer. This used to be necessary (and still may be in some situations), but most code can do the cleanup immediately. Even better, Seq objects can be put in a pool for reuse.

It would be nice to have a real-world example app that is experiencing performance problems before working on this. Even though this is "obvious", it may turn out to be overshadowed by some other performance issues in this code.

**Comment by diegomontoya** [comment]
:+1: Voting to have this issue prioritized as top go-mobile/android optimization task.

I really think this is a critical issue for wide go-mobile adoption.  Personally I had to attend to wild cases of bad memory GC on various devices and especially on pre 4.4 devices where memory leaks are present within android itself. 

The issue will manifest themselves if we pass a lot of large strings or byte arrays which are copied in and out of Seq. 

Low hanging fruit:

```java
    public static void FuncWithNoParamsAndNoReturns() {
        Seq var0 = new Seq();
        Seq var1 = new Seq();
        Seq.send("myclass", 10, var0, var1);
    }
```

Can be parsed to following and removes 2 java Seq allocations just by checking the number of return vars and params count in gobind.

```java
    public static void FuncWithNoParamsAndNoReturns() {
        Seq.send("myclass", 10, null, null);
    }
```
