### ISSUE TITLE
runtime: heap profiling incorrectly sampling allocations

### ISSUE THREAD

**Issue by rauls5382** [golang/go#12620]
Heap profiling in go is incorrectly sampling allocations, resulting on inaccurate profiles from go tool pprof. It oversamples some locations and undersamples others, depending on the size of the surrounding allocations.

Here is an example:
```
Go 1.5>go version
go version go1.5 linux/amd64
Go 1.5>cat mytest.go
package main

import (
	"log"
	"net/http"
)

import _ "net/http/pprof"

func main() {
	allocate_large_small()
	allocate_small()

	log.Println("Ready to serve")
	http.ListenAndServe("localhost:8234", nil)
}

var a16 *[16]byte
var a512 *[512]byte
var a256 *[256]byte
var a1k *[1024]byte
var a256k *[256 * 1024]byte

func allocate_large_small() {
	for i := 0; i < 100000; i++ {
		a256k = new([256 * 1024]byte)
		a1k = new([1024]byte)
		a256k = new([256 * 1024]byte)
		a512 = new([512]byte)
		a256k = new([256 * 1024]byte)
		a256 = new([256]byte)
		a256k = new([256 * 1024]byte)
		a16 = new([16]byte)
	}
}

func allocate_small() {
	for i := 0; i < 1000000; i++ {
		a1k = new([1024]byte)
		a512 = new([512]byte)
		a256 = new([256]byte)
		a16 = new([16]byte)
	}
}
Go 1.5>go build mytest.go
Go 1.5>./mytest &
... Wait ~30 seconds for the job to start serving
Go 1.5>go tool pprof -lines -top -alloc_objects mytest  localhost:8234/debug/pprof/heap
....
211936406 of 215013112 total (98.57%)
Dropped 13 nodes (cum <= 1075065)
      flat  flat%   sum%        cum   cum%
 174623336 81.22% 81.22%  174623336 81.22%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:33
  11070094  5.15% 86.36%   11070094  5.15%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:31
   5586598  2.60% 88.96%    5586598  2.60%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:29
   4338764  2.02% 90.98%    4338764  2.02%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:32
   4207027  1.96% 92.94%    4207027  1.96%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:26
   4199323  1.95% 94.89%    4199323  1.95%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:28
   3977368  1.85% 96.74%    3977368  1.85%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:30
   2819767  1.31% 98.05%    2819767  1.31%  main.allocate_large_small /home/rsilvera/work/Go/test/mytest.go:27
   1114129  0.52% 98.57%    1114129  0.52%  main.allocate_small /home/rsilvera/work/Go/test/mytest.go:42
```

Here is a summary of the actual and expected results:

Line | Actual | Expected (approx)
------|-----------|---------------
26 | 4207027 | 100000
27 | 1114129 | 100000
28 | 4199323 | 100000
29 | 5586598 | 100000
30 | 3977368 | 100000
31 | 11070094 | 100000
32 | 4338764  | 100000
33 | 174623336 | 100000
39 | 0 | 1000000
40 | 0 | 1000000
41 | 0 | 1000000
42 | 1114129 | 1000000

**Comment by ianlancetaylor** [comment]
The heap profiler doesn't sample based on locations at all.  It samples every N allocations.  A program like yours, in which there is a common multiple between the loops and the allocations, is going to break the algorithm.  But you can control the profiling rate: see http://golang.org/pkg/runtime/#pkg-variables .

I'm going to close this as working-as-expected, but please feel free to reopen if you have specific suggestions for how to change the behaviour.

**Comment by rauls5382** [comment]
Currently the heap profiler samples based on allocation sizes. It is supposed to sample at an average of 1 out of every 512k bytes allocated. Randomization is used to avoid correlation with the user application, so common multiples shouldn't be a factor. The current code is in https://github.com/golang/go/blob/master/src/runtime/malloc.go#L791

Some variation is expected due to sampling, but the current results showing some allocations not being sampled at all, and others reported at 1700X is a bug.

**Comment by ianlancetaylor** [comment]
Sorry, you're right, I did miss some points.
