### ISSUE TITLE
386 build fails on my machine

### ISSUE THREAD

**Issue by randall77** [golang/go#12629]
Running "GOARCH=386 ./all.bash" fails on my machine at tip.  64-bit works fine.  It looks like the builders are also happy.  Yet my machine fails.  What is going on?

    --- FAIL: TestIssue7573 (0.01s)
	go_test.go:257: running testgo [build -n -compiler gccgo cgoref]
	go_test.go:276: standard error:
	go_test.go:277: can't load package: package cgoref: no buildable Go source files in /tmp/gotest770440402/src/cgoref
		
	go_test.go:286: go [build -n -compiler gccgo cgoref] failed unexpectedly: exit status 1
FAIL
FAIL	cmd/go	20.901s

$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

@ianlancetaylor

**Comment by ianlancetaylor** [comment]
You didn't set CGO_ENABLED=1.  Looks like there is a bug in the testsuite--it should be skipping that test if canCgo is false.

**Comment by randall77** [comment]
I thought CGO_ENABLED=1 was the default.  DIdn't it used to be?  I remember having to set CGO_ENABLED=0 explicitly for various reasons.

**Comment by bradfitz** [comment]
Not when you're cross-compiling.

**Comment by randall77** [comment]
Ah, that makes sense.  Compiling 386 on amd64 counts as cross-compiling.

**Comment by davecheney** [comment]
Yup, there is a small function cgoEnabled (?? From memory) in cmd/dist
which determines the effective value of CGO_ENABLED. One of the parameters
is if GOHOSTARCH != GOARCH.
