### ISSUE TITLE
archive/tar: needs hardening and refactoring

### ISSUE THREAD

**Issue by dsnet** [golang/go#12638]
I'm filing this issue as the "capture all" ticket for all currently known archive/tar issues. I've discovered quite a few issues and it's getting unwieldy filing an issue for them. 

Over time, the tar library has become increasingly buggy, especially with the inclusion of support for PAX, GNU, and sparse files. There are many edge conditions where these various formats interact in unexpected ways leading to bugs. The fact that the fuzzer has detected a large of bugs in archive/tar goes to show its fragility. Also, most of the "fixes" done to resolve each issue were bandaids on a larger problem.

I have gone through the Reader implementation several times now and have read parts of the GNU, BSD, and STAR codebases to get a good understanding of how all the different utilities handle all the oddities when it comes to the TAR format.

Some of the major issues with the library are:
* #12594: the package's understanding of GNU format is wrong.
* [Example](https://play.golang.org/p/1WZTth3FSo). Malicious tar files [can cause arbitrary memory allocation](https://github.com/golang/go/blob/a1d093d95dfb888e55f960943bd3ad3d181ec743/src/archive/tar/reader.go#L672) due to blind trust of user provided sizes.
* ~~[Example](https://play.golang.org/p/10I2klLOsK). Malicious tar files [can cause arbitrary infinite loops](https://github.com/golang/go/blob/a1d093d95dfb888e55f960943bd3ad3d181ec743/src/archive/tar/reader.go#L819-L826). This occurs because the current data fragment is only popped when data has been read. However, if the reader experiences an io.EOF before the claimed end of the data fragment, then the EOF will be masked as nil and it will make no progress and readers will loop forever.~~
* ~~[Example](https://play.golang.org/p/xyDSmsYut2). Malicious tar files [can cause arbitrary panics](https://github.com/golang/go/blob/a1d093d95dfb888e55f960943bd3ad3d181ec743/src/archive/tar/reader.go#L810-L813). The position and offset and never verified to be non-negative. Thus, bytesLeft can be computed to be negative.~~

Currently open tickets are:
* #12594: package understanding of GNU format is wrong
* #12557: call to Next does not detect that stream is truncated
* #12436: reader returns bogus headers
* #12435: invalid memory address or nil pointer dereference
* #12358: output is nondeterministic
* #11171: Writer incorrectly encodes header data (Writer does not support sub-second resolution timestamps)
* #9683: do not use ustar long filename encoding and binary number encoding together (fix by avoid GNU format altogether)
* #9647: Writer permits "/" FileHeader rejected by Reader

The plan is to refactor the Reader code first to be as reliable as possible, and then to tackle various out-standing Writer issues.

I'll be filing no more archive/tar related issues after this. I promise :]

**Comment by dsnet** [comment]
@dsymonds, what is the point of the [Writer.Flush method](https://github.com/golang/go/blob/7733a7cad81d1e356a11a8e83221a32e5d622869/src/archive/tar/writer.go#L50-L69)?

At first, I thought that the function was used to ignore the rest of the current file and automatically fill it in with zeros. In fact, the for loop on [L57](https://github.com/golang/go/blob/7733a7cad81d1e356a11a8e83221a32e5d622869/src/archive/tar/writer.go#L57) seems to indicate that this was the original purpose. However, the check on [L51](https://github.com/golang/go/blob/7733a7cad81d1e356a11a8e83221a32e5d622869/src/archive/tar/writer.go#L51) prevents use of the method unless all file contents have been written already. Is the purpose of this method really just to flush out the final padding?

**Comment by dsymonds** [comment]
You're looking at some pretty ancient code. I wrote the original `archive/tar` in mid 2009, before we even really had a good grasp of what good Go code looked like. It's accreted changes ever since as people have had need. It probably needs a good tidy up.

I managed to find an email from the code review where `Writer.Flush` got added. @rsc said:
```
Line 51: func (tw *Writer) writePadding() {
rename to Flush and return os.Error.
clients may want to call this explicitly
to finish one file even if they're not
ready to call Close or WriteHeader.
```
In its original form it did indeed write out zeros to the end of the current file. It seems a little bogus now, but we can't drop it.

The neutering on line 51 does indeed look silly. It was added in d75abb7c (early 2012), and @rsc noticed that it was silly after it was submitted (https://codereview.appspot.com/5777064). I can't remember why we didn't revise it back then.

With the benefit of hindsight, I can't see the use case for writing the zeros automatically. The user of `tar.Writer` needs to know the size in advance (to put it in the header), and can easily write zeros if they want. The 2012 change made `Flush` only write the trailing padding anyway, so we could simplify it now, but it's also somewhat of a historical artifact at this point.

**Comment by dsymonds** [comment]
Sorry, I don't have time to review all these changes. I'll finish off the one I started, but you'll need to track down a different reviewer.

**Comment by dsnet** [comment]
Is there anyone you recommend for doing the reviews?

**Comment by dsymonds** [comment]
@davecheney might be interested, or you can ask around on golang-dev.

**Comment by dsnet** [comment]
@davecheney, would you be willing to do this? Otherwise, I will ask around.

**Comment by rsc** [comment]
Please file separate, focused issues for bugs you find. One giant issue does not help anyone. It doesn't give a crisp statement of something to do, and it doesn't help when you see it in a CL description.
