### ISSUE TITLE
cmd/go: dlopen returns before init has finished

### ISSUE THREAD

**Issue by chamaken** [golang/go#12639]
**version and OS**

    $ go version  
    go version go1.5.1 linux/amd64

**What did you do?**
I tried to dlopen c-shared go object. Please check sample code below:
main.c
```main.c
/* cc -export-dynamic main.c -ldl */
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

static volatile int n;

int add(void)
{
        return ++n;
}

int main(int argc, char *argv[])
{
        void *handle;

        if ((handle = dlopen(argv[1], RTLD_NOW)) == NULL) {
                fprintf(stderr, "dlopen: %s - %s\n", argv[1], dlerror());
                exit(EXIT_FAILURE);
        }
        /* sleep(1); */
        printf("n: %d\n", n);

        return EXIT_SUCCESS;
}
```
dso.go
```dso.go
// go build -buildmode=c-shared dso.go
package main

/*
extern int add(void);
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-all
*/
import "C"
import "fmt"

func init() {
        fmt.Printf("init finished: %d\n", C.add())
}

func main() {}
```
comple both as commented top of the code, and try ``./a.out ./dso``  

**What did you expect to see?**
I expected to see a message and "n: 1". in dlopen(3)

    Constructor  routines  are  executed  before dlopen() returns,  
    and destructor routines are executed before dlclose() returns.

but (my, users) constructor, func init() seems to be defered. 

**What did you see instead?**
It shows "n: 0", I can see the expected by enabling sleep(1), in comment.

**Comment by minux** [comment]
Your C program has to call at least one Go callback (exported function)
to make sure that the Go runtime will finish initializing before your
program exits. (that's the reason why adding sleep(1) will allow the
message to show)

Go's runtime initialization is async, that is, when dlopen returns, it's not
done yet. It's just started in another thread. You need to call a cgo export
to synchronize it.
