### ISSUE TITLE
asm: arm64 condition codes should not be TYPE_MEM

### ISSUE THREAD

**Issue by robpike** [golang/go#12632]
CSINV CS, R1, R2, R3

here the CS is a magic word, not a register, that is parsing as TYPE_MEM. It really shouldn't be; it is certainly not a memory reference. We should fix that somehow or special-case it more precisely in the assembler - it works only by accident.

**Comment by 4ad** [comment]
I am very confused how this happened. I am sure I originally implemented it properly. Anyway, I will fix it.

**Comment by rsc** [comment]
Not important enough for 1.5.2.
