### ISSUE TITLE
builds using compiler 1.4+ fail randomly while using 1.2 works correctly

### ISSUE THREAD

**Issue by jdmontenegro** [golang/go#12637]
Hi all, 
Sorry for creating a new issue here, but the last one got closed before I could reply.

I have rerun my program using the race detector and there is no complain from the race detector

**Comment by jdmontenegro** [comment]
Sorry got sent before I could finish.

the command line used was:

go run -race myprogram -flag1 file1 -flag2 file2 -out outfile -threads 4

and the program starts. It writes the expected things to STDERR but no complain form the race detector.
To test if the race detector was working correctly I ran the example shown here: 

https://golang.org/doc/articles/race_detector.html

and the race detector did show the expected error.
Does this mean that my program does not have a race? Or I cannot see the race detector output because my program is writing to STDERR?

I look forward to your suggestions.

Best regards,

Juan Montenegro

**Comment by minux** [comment]
Hi, please ask questions like this on the golang-nuts mailing list.
the issue tracker is for bugs in Go itself and proposals for new
features.

To answer your question, writing to stderr won't interfere with
the race detector. But the race detector can only detect the
race if it actually happens, so you need to run the program
multiple times with various inputs and work load. (And note
that the race detector can show races, but can never prove
that there is no race.)

Thanks.
