### ISSUE TITLE
encoding/json: Add int support for json.Unmarshal

### ISSUE THREAD

**Issue by tcyrus** [golang/go#12630]

**Comment by minux** [comment]
What do you mean? Could you provide some concrete examples
demonstrating what is missing in encoding/json?

**Comment by nodirt** [comment]
Possibly @tcyrus means that JSON numbers are interpreted as `float64` and not `int`? 

```go
var x interface{}
json.Unmarshal([]byte("1"), &x)
fmt.Printf("%T", x) // "float64"
```

That's because there is no `int` type in JSON, but `number` https://tools.ietf.org/html/rfc7159#page-6

**Comment by adg** [comment]
Closing this issue until it is clarified.
