### ISSUE TITLE
cmd/go: use "go list -json" list two or more packages won't get correct json output

### ISSUE THREAD

**Issue by m3ng9i** [golang/go#12643]
I use the following command to list information of two packages:

```
go list -json builtin container/ring
```

Then I got the result:

    {
            "Dir": "D:\\go\\go1.5.1\\src\\builtin",
            "ImportPath": "builtin",
            "Name": "builtin",
            "Doc": "Package builtin provides documentation for Go's predeclared identifiers.",
            "Target": "D:\\go\\go1.5.1\\pkg\\windows_386\\builtin.a",
            "Goroot": true,
            "Standard": true,
            "Stale": true,
            "Root": "D:\\go\\go1.5.1",
            "GoFiles": [
                    "builtin.go"
            ],
            "Deps": [
                    "runtime",
                    "unsafe"
            ]
    }
    {
            "Dir": "D:\\go\\go1.5.1\\src\\container\\ring",
            "ImportPath": "container/ring",
            "Name": "ring",
            "Doc": "Package ring implements operations on circular lists.",
            "Target": "D:\\go\\go1.5.1\\pkg\\windows_386\\container\\ring.a",
            "Goroot": true,
            "Standard": true,
            "Root": "D:\\go\\go1.5.1",
            "GoFiles": [
                    "ring.go"
            ],
            "Deps": [
                    "runtime",
                    "unsafe"
            ],
            "TestGoFiles": [
                    "ring_test.go"
            ],
            "TestImports": [
                    "fmt",
                    "testing"
            ]
    }

You can see, the format of the result is:

    {
        ...
    }
    {
        ...
    }

not:

    [{
        ...
    },
    {
        ...
    }]

There miss a comma and a pair of square brackets, so the json decorder cannot decorde the output.

My go version: go1.5.1 windows/386

**Comment by bradfitz** [comment]
Sorry, but this isn't something we can change at this point for compatibility reasons.

Note that Go's and other JSON decoders will let you decode multiple JSON objects from a stream in a row, ignoring whitespace. It's not a valid single JSON value (not an array) but it's valid multiple JSON values.
