### ISSUE TITLE
xinetd launched web service fails with accept: invalid argument error

### ISSUE THREAD

**Issue by tedx** [golang/go#12646]
What version of Go are you using (go version)?
1.5

What operating system and processor architecture are you using?
RHEL6 x86_64

What did you do?
xinetd launch a Go web service.

Service code goxinetd.go :

package main

import (
	"os"
    "fmt"
    "net/http"
	"net"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello world")
}

func main() {
    http.HandleFunc("/", handler)

	l, err := net.FileListener(os.Stdin)
	if err != nil {
		fmt.Printf("net.FileListener(os.Stdin) failed: %v\n", err)
		return
	}	
	err = http.Serve(l, nil)
	if err != nil {
		fmt.Printf("http.Serve(l, router) failed: %v\n", err)
		return
	}
}

Append:
goxinetd 10349/tcp 

to /etc/services.

xinetd.d config file /etc/xinetd.d/goxinetd :
service goxinetd
{
	disable	= no
	only_from	= 127.0.0.1
	protocol	= tcp
	server		= <GOPATH>/goxinetd
	wait		= no
	instances	= 20
	socket_type	= stream
	user		= root
	log_on_success	=
}

As root `kill -HUP <xinetd pid>` to get xinetd to reread configuration files.

Run:
wget http://127.0.0.1:10349

What did you expect to see?

index.html file containing "Hello world"

What did you see instead?

index.html file containing http.Serve(l, router) failed: accept tcp 127.0.0.1:10349: accept: invalid argument

strace output:
execve("/home/tedx/gocode/src/goxinetd", ["/home/tedx/gocode/src/goxinetd"], [/* 22 vars */]) = 0
brk(0)                                  = 0x1797000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79fa70000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=188278, ...}) = 0
mmap(NULL, 188278, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb79fa42000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340]\300\3077\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=145896, ...}) = 0
mmap(0x37c7c00000, 2212848, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x37c7c00000
mprotect(0x37c7c17000, 2097152, PROT_NONE) = 0
mmap(0x37c7e17000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x37c7e17000
mmap(0x37c7e19000, 13296, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x37c7e19000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\356A\3077\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1926760, ...}) = 0
mmap(0x37c7400000, 3750152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x37c7400000
mprotect(0x37c758a000, 2097152, PROT_NONE) = 0
mmap(0x37c778a000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18a000) = 0x37c778a000
mmap(0x37c778f000, 18696, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x37c778f000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79fa41000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79fa40000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79fa3f000
arch_prctl(ARCH_SET_FS, 0x7fb79fa40700) = 0
mprotect(0x37c778a000, 16384, PROT_READ) = 0
mprotect(0x37c7e17000, 4096, PROT_READ) = 0
mprotect(0x37c721f000, 4096, PROT_READ) = 0
munmap(0x7fb79fa42000, 188278)          = 0
set_tid_address(0x7fb79fa409d0)         = 16123
set_robust_list(0x7fb79fa409e0, 0x18)   = 0
futex(0x7fffb801995c, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fffb801995c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7fb79fa40700) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x37c7c05c60, [], SA_RESTORER|SA_SIGINFO, 0x37c7c0f710}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x37c7c05cf0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x37c7c0f710}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=10240*1024, rlim_max=RLIM_INFINITY}) = 0
sched_getaffinity(0, 8192,  { ff, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }) = 512
mmap(0xc000000000, 65536, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
munmap(0xc000000000, 65536)             = 0
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79f9ff000
mmap(0xc820000000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820000000
mmap(0xc81fff8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81fff8000
mmap(0xc000000000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79f9ef000
mmap(NULL, 1439992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79f88f000
sigaltstack({ss_sp=0xc820002000, ss_flags=0, ss_size=32672}, NULL) = 0
gettid()                                = 16123
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGHUP, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGILL, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGILL, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGTRAP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTRAP, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGABRT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGABRT, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGBUS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGBUS, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGFPE, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGFPE, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR1, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGSEGV, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSEGV, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR2, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPIPE, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGALRM, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGSTKFLT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSTKFLT, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGURG, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGURG, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGXCPU, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXCPU, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGXFSZ, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXFSZ, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGVTALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGVTALRM, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGPROF, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPROF, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGWINCH, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGWINCH, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGIO, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGIO, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGPWR, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPWR, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGSYS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSYS, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRTMIN, NULL, {0x37c7c05c60, [], SA_RESTORER|SA_SIGINFO, 0x37c7c0f710}, 8) = 0
rt_sigaction(SIGRTMIN, NULL, {0x37c7c05c60, [], SA_RESTORER|SA_SIGINFO, 0x37c7c0f710}, 8) = 0
rt_sigaction(SIGRTMIN, {0x37c7c05c60, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x37c7c0f710}, NULL, 8) = 0
rt_sigaction(SIGRT_1, NULL, {0x37c7c05cf0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x37c7c0f710}, 8) = 0
rt_sigaction(SIGRT_1, NULL, {0x37c7c05cf0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x37c7c0f710}, 8) = 0
rt_sigaction(SIGRT_1, {0x37c7c05cf0, [], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x37c7c0f710}, NULL, 8) = 0
rt_sigaction(SIGRT_2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_2, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_3, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_3, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_4, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_4, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_5, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_5, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_6, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_6, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_7, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_7, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_8, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_8, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_9, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_9, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_10, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_10, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_11, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_11, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_12, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_12, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_13, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_13, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_14, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_14, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_15, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_15, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_16, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_16, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_17, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_17, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_18, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_18, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_19, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_19, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_20, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_20, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_21, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_21, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_22, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_22, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_23, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_23, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_24, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_24, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_25, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_25, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_26, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_26, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_27, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_27, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_28, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_28, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_29, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_29, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_30, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_30, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_31, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_31, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigaction(SIGRT_32, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_32, {0x45bff0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x45c010}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
brk(0)                                  = 0x1797000
brk(0x17b8000)                          = 0x17b8000
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb79ee8e000
mprotect(0x7fb79ee8e000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fb79f88dff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb79f88e9d0, tls=0x7fb79f88e700, child_tidptr=0x7fb79f88e9d0) = 16124
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb79ee4e000
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb79e44d000
mprotect(0x7fb79e44d000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fb79ee4cff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb79ee4d9d0, tls=0x7fb79ee4d700, child_tidptr=0x7fb79ee4d9d0) = 16125
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0xc82002ce90, FUTEX_WAKE, 1)      = 1
futex(0xc82002ca10, FUTEX_WAKE, 1)      = 1
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb79d04b000
mprotect(0x7fb79d04b000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fb79da4aff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb79da4b9d0, tls=0x7fb79da4b700, child_tidptr=0x7fb79da4b9d0) = 16127
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0xc820062110, FUTEX_WAKE, 1)      = 1
openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
read(3, "128\n", 4096)                  = 4
read(3, "", 4092)                       = 0
close(3)                                = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
close(3)                                = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 3
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
bind(4, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
close(4)                                = 0
close(3)                                = 0
fcntl(0, F_DUPFD_CLOEXEC, 0)            = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
getsockopt(3, SOL_SOCKET, SO_TYPE, [1], [4]) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(10349), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
getpeername(3, {sa_family=AF_INET, sin_port=htons(46906), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
epoll_create1(O_CLOEXEC)                = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLET|0x2000, {u32=2665821440, u64=140426621564160}}) = 0
accept4(3, 0xc82005ba38, [112], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EINVAL (Invalid argument)
accept(3, 0xc82005ba48, [112])          = -1 EINVAL (Invalid argument)
epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = 0
close(3)                                = 0
write(1, "http.Serve(l, router) fai"..., 90) = 90
exit_group(0)                           = ?

**Comment by bradfitz** [comment]
I don't think that's a valid program/config. I don't think that os.Stdin is a listener. I bet it's just the first and only connection.

**Comment by tedx** [comment]
Look at the http/fcgi code this is exactly what is done there. FYI xinetd
send the socket connection to the child process via stdin.

**Comment by ianlancetaylor** [comment]
xinetd sends the connected socket to the program.  It doesn't send the listening socket.  The whole point of xinetd is that it does the listening for you.

This is not the same as net/http/fcgi.Server.  That function sets up a server to listen for connections.

You don't want FileListener, you want FileConn.

**Comment by tedx** [comment]
You're right since I'm 'wait=no" xinetd does the accept.
 /* If it's a TCP socket, and we're set to wait, the accept is
       * done by the child process.  Don't set NEW_DESCRIPTOR, since
       * there isn't one.  The descriptor will be/was removed from
       * the descriptor set in svc_suspend and re-enabled in svc_resume.
       */

So is there a way to is there a way to create a http server with a Conn?

**Comment by bradfitz** [comment]
That's a good question for the mailing list.

Closing this bug for lack of bug. Reopen if you find something not working in Go.
