### ISSUE TITLE
playground: getting "process took too long" while printing time

### ISSUE THREAD

**Issue by ainar-g** [golang/go#12645]
This code works with Go 1.5.1, but on the Playground it fails with "process took too long" error:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	c := time.Now().Add(12 * time.Hour * -1)
	n := time.Now()
	fmt.Println(c)
	fmt.Println(n)
	fmt.Println(n.Sub(c))
}
```
Playground: https://play.golang.org/p/6_gCBYeLLO.

Interestingly, it works fine if you remove the trailing newline added by "Format". But if you press "Format" again and try to run it, it will still time out.

EDIT: This was first discovered by [bo-banane on Reddit's /r/golang](https://www.reddit.com/r/golang/comments/3l5rvq/play_bug_process_took_too_long/).

**Comment by mattn** [comment]
I'm not sure. It seems that `time.Now()` is taking long time in first time?

**Comment by cznic** [comment]
@adg - Just a bad cache item: https://play.golang.org/p/Mw8fXrJL2Y

**Comment by bradfitz** [comment]
Yeah, just unfortunate caching of an error.

Unfortunately the halting problem forbids much better behavior here.
