### ISSUE TITLE
playground: typeless map keys output format errors, but compiles

### ISSUE THREAD

**Issue by bruth** [golang/go#12644]
Example: http://play.golang.org/p/DuxMMkl3TF

Running the formatter on it, it complains that the map key does not have the type declaration `[2]int`, but it runs just fine. Is this the expected behavior?

**Comment by crawshaw** [comment]
cc @griesemer

**Comment by ianlancetaylor** [comment]
I assume you mean that the playground "format" button doesn't work, because gofmt (from Go 1.5) does work fine.

**Comment by bruth** [comment]
Sorry I think this actually a `goimports` issue. I first noticed this using the [vim go plugin](https://github.com/fatih/vim-go).. and I realized that I override the plugin to use `goimports`. I presume the playground also uses this?

**Comment by ianlancetaylor** [comment]
I don't know what the playground uses.

goimports works for me too.  Note that omitting the map key type is new for Go 1.5, and that goimports is not part of the Go 1.5 release.  Perhaps you simply need to update your goimports binary?

**Comment by bradfitz** [comment]
I think @adg forgot to update something when deploying the playground for 1.5.

**Comment by bruth** [comment]
> Perhaps you simply need to update your goimports binary?

Thanks, that was it! I thought I had done that, but apparently not.

**Comment by adg** [comment]
It's because App Engine is running Go 1.4.2 and the playground is using its go/format package.

**Comment by albertog** [comment]
There are plan to upgrade Gae to 1.5
Thanks

**Comment by adg** [comment]
This is fixed.
