### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by bits4breakfast** [golang/go#12652]
Context: http://go-tour-ita.appspot.com/

"A Tour of Go" in Italian is completely broken, it won't even start beside the title. 

```
Uncaught SyntaxError: Unexpected token <<
Uncaught ReferenceError: HTTPTransport is not defined(anonymous function)
```

<img width="1280" alt="screen shot 2015-09-17 at 09 15 08" src="https://cloud.githubusercontent.com/assets/1160718/9927196/c3df37e2-5d1c-11e5-81c9-02f7811558e6.png">

**Comment by minux** [comment]
The Italian translation is not maintained here,
Please file an issue at github.com/alebaffa/tour.

Thanks.

**Comment by minux** [comment]
Hi @alebaffa, could you please enable issue reporting in your
tour repo?

PS: please remember to update the issue reporting URL in
static/js/values.js

**Comment by alebaffa** [comment]
Hi, yes I know it's broken. Unfortunately I didn't have time to fix it so far. I enabled the issue reporting.

**Comment by alebaffa** [comment]
I fixed the issue in the values.js file and it's working now :+1: 
Thank you!
