### ISSUE TITLE
x/build/coordinator: truncated snapshot tar.gz

### ISSUE THREAD

**Issue by bradfitz** [golang/go#12671]
I found builders failing on a truncated snapshot of make.bash. The .tar.gz file on Google Cloud Storage was only 6 MB instead of ~40 MB. This led to unhappiness when pushing that tarball to builders.

The question: how did a 6 MB .tar.gz end up in GCS?

The code in question is:

```go
func (st *buildStatus) writeSnapshot() error {
        st.logEventTime("write_snapshot")
        defer st.logEventTime("write_snapshot_done")

        tgz, err := st.bc.GetTar("go")
        if err != nil {
                return err
        }
        defer tgz.Close()

        wr := storage.NewWriter(serviceCtx, snapBucket(), st.snapshotObjectName())
        wr.ContentType = "application/octet-stream"
        wr.ACL = append(wr.ACL, storage.ACLRule{Entity: storage.AllUsers, Role: storage.RoleReader})
        if _, err := io.Copy(wr, tgz); err != nil {
                wr.Close()  // <-------- this is the bug
                return err
        }

        return wr.Close()
}
```

And indeed: the `wr.Close()` inside the `io.Copy` error case should not simply close it. It should abort the write instead, so GCS never makes it available in the namespace.

Do we have an API for that?

/cc @adg @rakyll @okdave

**Comment by okdave** [comment]
No, there's no API like that right now (it seems like the writer should grow a `Cancel` or `Abandon` method?). Looking at the underlying HTTP API, it's not clear how to signal a cancellation like this to GCS.

I'll file a feature request against the cloud package.

**Comment by bradfitz** [comment]
Just closing the HTTP connection mid-cycle is sufficient to break it. If you don't send a 0-byte EOF chunk in the HTTP chunking stream, the server is supposed to interpret it as a broken connection. And if it had a Content-Length (it doesn't in this case), then the abort would also make it fail.

Perhaps we should use the Context's Done channel. (which is already passed to `storage.NewWriter`)

In Go 1.5, `http.Request` has a compatible `Cancel` field.

**Comment by okdave** [comment]
I like the Context idea. Filed GoogleCloudPlatform/gcloud-golang#175.
