### ISSUE TITLE
runtime: Export cputicks function

### ISSUE THREAD

**Issue by brb** [golang/go#12675]
It would be useful, if the `runtime.cputicks` function could be accessed from a non `runtime` package. E.g., think of benchmarks code which requires high-resolution timing information.

**Comment by ianlancetaylor** [comment]
That would mean that we would have to make it reliable, which it is not.  I think this job could be better served by a third party package.  It's not as though cputicks depends on anything else in the runtime package; it can be implemented independently.

**Comment by bradfitz** [comment]
Agreed. I bet it's already in @klauspost's intrinsics package somewhere: http://godoc.org/?q=intrinsics

**Comment by klauspost** [comment]
@bradfitz - unfortunately the intrinsics package isn't functional until some compiler work is done - it is merely "mock" functions.

However @brb, you might be able to do what you want by calling the [RTCounter](https://godoc.org/github.com/klauspost/cpuid#CPUInfo.RTCounter) function in my cpuid package.
