### ISSUE TITLE
tour: Exercise Structs not executable (Process took too long)

### ISSUE THREAD

**Issue by VincentS** [golang/go#12678]
Context: https://tour.golang.org/moretypes/2

Can't execute code 
>process took too long
>Program exited.

**Comment by Skarlso** [comment]
Needs a fmt.Println(&Vertex{1, 2}). & is missing for Struct literal.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
The code works fine for me.
What code did you have on the code panel when you saw this error, @VincentS?

If it was the same code as you get when you click "Reset" this might have been a temporary issue that seems solved now.

**Comment by Skarlso** [comment]
Works for me too now. Though it really wasn't previously. 

I had two comments regarding stuff on tour, neither were correct. :-D Guess I need more learning eh.

**Comment by VincentS** [comment]
Works for me now as well . :+1:
