### ISSUE TITLE
godoc: No way to go get to package tracker

### ISSUE THREAD

**Issue by techtonik** [golang/go#12676]
>> I have a proposal to add partial Windows support to
>> https://godoc.org/golang.org/x/crypto/ssh/terminal but I can't see any links
>> to issue tracker or feedback form. Why?

> It does seem difficult to get from the golang.org page to the actual
> repository.  Please open an issue about that at
> https://golang.org/issue .  Thanks.

**Comment by ianlancetaylor** [comment]
To clarify, what I see is that https://golang.org/x/crypto/ssh/terminal redirects to godoc.org.  At that point there is no obvious way to get to the source code repository, and there is no obvious way to get to the issue tracker.

**Comment by ianlancetaylor** [comment]
CC @adg

**Comment by cespare** [comment]
For the record, the link you're looking for is the repository name up at the top left of the page. (See screenshot.) It's not particularly obvious, though.

![screen_20150918104313](https://cloud.githubusercontent.com/assets/318501/9966552/60632bfc-5df2-11e5-9411-6a02ade8aa02.png)

**Comment by garyburd** [comment]
In addition to the repo link mentioned in the previous comment, the "Package Files" header links to GitHub page for the package.

This issue should be reported at https://github.com/golang/gddo/issues.

**Comment by techtonik** [comment]
Some UX comments:

1. ` Index | Files ` look excessive - better replace it with ` Issues | Code ` there
2. `Package Files` and `Files` are not consistent
3. `Package Files` and `Index` headers are not consistent
4. `Package Files` is buried under API index
