### ISSUE TITLE
cmd/compile: int conversion ignored in shift operation

### ISSUE THREAD

**Issue by kortschak** [golang/go#12677]
When the two package program below is compiled using go1.5.1 (linux/amd64) the build fails with:

```
$ go build foo.go 
# command-line-arguments
./foo.go:6: invalid operation: 1 << uint(bar.f·2) (shift of type float64)
./foo.go:10: tempname called with nil type
./foo.go:10: cannot use autotmp_0001 (type int32) as type float64 in assignment
```

If the Bar function is included in main, the build completes successfully, which is the expected outcome. The build is also successful with go1.4.2, or if the expression within the float64() is evaluated into a temporary variable.

`foo.go`
```
package main

import (
	"fmt"

	"bar"
)

func main() {
	fmt.Println(bar.Baz(2))
}
```

`bar/bar.go`
```
package bar

func Baz(f int) float64 {
	return 1 / float64(int(1)<<(uint(f)))
}
```

See https://groups.google.com/d/topic/golang-nuts/IP1YIOd_PaY/discussion for background.

**Comment by ianlancetaylor** [comment]
Seems to be a bug reading the import data.

**Comment by kortschak** [comment]
Bisected to f09887cdce9dbb63e01503e0598bdeae74ee4e0b.

The effect is abolished by `-gcflags="-l"`.
