### ISSUE TITLE
playground problem, not valid return as expected

### ISSUE THREAD

**Issue by netroby** [golang/go#12672]
http://golang.org/pkg/os/exec/#example_Cmd_Output

All examples of this page, can not "Run",

2009/11/10 23:00:00 exec: "date": executable file not found in $PATH

Program exited.

2009/11/10 23:00:00 exec: "sleep": executable file not found in $PATH

Program exited.

Would you please make it run correct?

**Comment by netroby** [comment]
http://golang.org/pkg/os/exec/#example_Cmd_Output
http://golang.org/pkg/os/exec/#example_Cmd_Start
http://golang.org/pkg/os/exec/#example_Cmd_StdoutPipe
http://golang.org/pkg/os/exec/#example_Command
http://golang.org/pkg/os/exec/#example_LookPath

These example can not run by click the run button

**Comment by bradfitz** [comment]
Sorry, the playground doesn't allow child processes.

You can run them on your own machine (if you run godoc + playground there), but not on our website.

/cc @adg in case he wants to do something else.
