### ISSUE TITLE
website: ANYTHING.golang.org is golang.org

### ISSUE THREAD

**Issue by bradfitz** [golang/go#12684]
It's confusing that ANY_TYPO.golang.org goes to golang.org:

http://sdlkfsdfjdsf.golang.org/
or:
http://playground.golang.org/  (whoops, meant http://play.golang.org/ )

Can we 404 the bogus ones instead?

**Comment by adg** [comment]
It's hard because of the way we have App Engine configured to serve golang.org.
We could do it by having the default app check the serving domain.

**Comment by bradfitz** [comment]
> We could do it by having the default app check the serving domain.

Yes, that's what I was imagining.

**Comment by rakyll** [comment]
We must 404 to avoid serving `someunpleasantmessage.golang.org`.

**Comment by adg** [comment]
I have tentatively deployed the above fix to golang.org. Seems good. Will
keep an eye on it and back it out when I finish work today, unless the CL
is reviewed and +2'd.
