### ISSUE TITLE
build: support -buildmode=c-archive for darwin/386 (iOS sim)

### ISSUE THREAD

**Issue by swisspol** [golang/go#12683]
> Go 1.5.1 on OS X 10.10.5 with Xcode 7

The failure is at the last step during linking (things work fine for iPhone Simulator / x86_64):
```
/Users/pol/Downloads/Tests/go-1.5.1/pkg/tool/darwin_amd64/link -o $WORK/command-line-arguments/_obj/exe/a.out.a -L $WORK -L /Users/pol/Downloads/Tests/go-1.5.1/pkg_cross/iPhoneSimulator_i386 -extld=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -buildmode=c-archive -buildid=a5117489b1092eae5e08f28729578dbb1167953c $WORK/command-line-arguments.a
# command-line-arguments
_rt0_386_darwin_lib.ptr: _rt0_386_darwin_lib: not defined
_rt0_386_darwin_lib.ptr: undefined: _rt0_386_darwin_lib
```

I made a sample test project here: https://github.com/swisspol/Go-Bridge (the [go-build.sh](https://github.com/swisspol/Go-Bridge/blob/master/go-build.sh) script must first be modified to re-enable building for iPhone Simulator on i386).

**Comment by swisspol** [comment]
Is darwin / i386 officially supported anyway? It's in the list of allowed `GOOS` / `GOARCH` [combinations](https://golang.org/doc/install/source#environment), but there is no archive or installer for it.

**Comment by minux** [comment]
Darwin/386 (32-bit OS X programs) is officially supported (because there is
no need 32-bit only Macs, there isn't much need to release 32-bit OS X
package and besides people sometimes confuse about which one to choose when
we did provide that in the past). Just -buildmode=c-archive is not. The
focus is likely on amd64/arm/arm64. How important is the support for 32-bit
iOS simulator?

**Comment by swisspol** [comment]
IMO it's not important as I would assume anyone even trying to run Go inside an iOS app is writing a modern app, which means 64 bit aware. And 32 bit on the device works AFAIK. I filed this issue for the sake of completeness, but I suspect it would not be a wise use of engineering resources to support this unless it were trivial.

Not supporting 32 bit iOS Simulator means in practice that you need to configure the Xcode build settings to only build 64 bit for the iOS Simulator but still 32/64 bit for the device, which is a bit tricky, but that could be easily documented:

![image](https://cloud.githubusercontent.com/assets/627915/9974495/8eda5baa-5e46-11e5-963b-8c2cf1c79f29.png)

But maybe one of the folks from https://github.com/golang/mobile/ should chime in on this topic?

**Comment by minux** [comment]
regarding whether we need to support darwin/386 for iOS simulator.
/cc @crawshaw @hyangah

**Comment by jtsylve** [comment]
I need support for darwin/386 for other reasons.  I need to link some go code to a 32-bit only application on OS X.  I am running into this same issue when trying to compile.

**Comment by azinman** [comment]
It's standard practice to be able to support 32-bit devices, and if you can't run them in the simulator then many iOS devs will be surprised. I'm working on a shared library that will be go-backed, and if I distribute a fat binary that doesn't include 32-bit then many ordinary developers will be very confused IF they happen to pick the iPhone 5 or below for the simulator (often done to test the smaller screen size explicitly, or implicitly since its smaller on your laptop screen).

**Comment by jtsylve** [comment]
Both buildmode c-archive and c-shared work properly in 1.6beta2

**Comment by ianlancetaylor** [comment]
@jtsylve Thanks, yes, looks like this was fixed by https://golang.org/cl/12412 .

**Comment by akamensky** [comment]
Just wondering whether this has been released in some version? I am on 1.6.2 and I get "-buildmode=shared not supported on darwin/386" same as for c-archive option I get

```
can't load package: package main: no buildable Go source files in /Users/akamensky/test
```

**Comment by opaugam** [comment]
same issue ("can't load package") when picking c-archive .. i'm on go1.7.4 darwin/amd64

**Comment by ianlancetaylor** [comment]
@akamensky @opaugam This issue has been fixed and closed.  The "no buildable Go source files" error may mean that you need to set `CGO_ENABLED=1`.  In any case, please do not comment on this issue.  Please use a forum (https://golang.org/wiki/Questions) or, if you are sure you have encountered, please open a new issue.  Thanks.
