### ISSUE TITLE
test: spectralnorm takes 20+ minutes on linux-arm-arm5

### ISSUE THREAD

**Issue by bradfitz** [golang/go#12688]
I notice that the shootout test "spectralnorm" runs for over 20 minutes on linux-arm-arm5

I logged in to one of the machines and indeed, it's working hard, spinning away.

Some looking around...

```
 1740 ?        Ss     0:04 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 104:108
30272 ?        Ssl    0:01 /usr/local/bin/buildlet-stage0
30278 ?        Sl     0:30  \_ ./buildlet.exe --workdir=/workdir --hostname=scaleway-prod-09 --halt=false --reverse=linux-arm,linux-arm-arm5 --coordinato
22948 ?        Sl     0:00      \_ /workdir/go/bin/go tool dist test --no-rebuild --banner=XXXBANNERXXX: shootout:spectralnorm
22953 ?        Sl     0:00          \_ /workdir/go/pkg/tool/linux_arm/dist test --no-rebuild --banner=XXXBANNERXXX: shootout:spectralnorm
22964 ?        S      0:00              \_ bash ./timing.sh -test spectralnorm
23008 ?        Rl    11:02                  \_ a.out

root@buildlet-prep:~# cat /proc/23008/environ
GOHOSTARCH=armGO_TEST_TIMEOUT_SCALE=5TERM=dumbGOROOT_BOOTSTRAP=/usr/local/goWORKDIR=/workdirGOTOOLDIR=/workdir/go/pkg/tool/linux_armGOGCCFLAGS=-fPIC -marm -pthread -fmessage-length=0GO_BUILDER_NAME=linux-arm-arm5PATH=.:/workdir/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binGOARM=5PWD=/workdir/go/test/bench/shootoutGOARCH=armLANG=CGO386=387CGO_ENABLED=1CXX=g++SHLVL=1LANGUAGE=en_US.UTF8GOROOT=/workdir/goGOOS=linuxGOHOSTOS=linuxCC=gcc_=./a.out

root@buildlet-prep:~# cat /proc/22964/environ
PATH=/workdir/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binGOROOT_BOOTSTRAP=/usr/local/goWORKDIR=/workdirGO_BUILDER_NAME=linux-arm-arm5GOARM=5GO_TEST_TIMEOUT_SCALE=5GOROOT=/workdir/goGOARCH=armGOHOSTARCH=armGOHOSTOS=linuxGOOS=linuxGOTOOLDIR=/workdir/go/pkg/tool/linux_armTERM=dumbCC=gccGOGCCFLAGS=-fPIC -marm -pthread -fmessage-length=0CXX=g++CGO_ENABLED=1GO386=387LANG=CLANGUAGE=en_US.UTF8root@buildlet-prep:~# 

root@buildlet-prep:~# stat /proc/22964; date
  File: '/proc/22964'
  Size: 0         	Blocks: 0          IO Block: 1024   directory
Device: 3h/3d	Inode: 496751      Links: 7
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-09-19 02:28:48.417888821 +0000
Modify: 2015-09-19 02:28:48.417888821 +0000
Change: 2015-09-19 02:28:48.417888821 +0000
 Birth: -
Sat Sep 19 02:29:38 UTC 2015
```

@davecheney, can you investigate?

Should I disable these tests on that builder?

/cc @minux @adg

**Comment by bradfitz** [comment]
Oh, and another point: 20 minutes is the new max timeout that the coordinator permits for any particular dist test.

It can be configured per (builder, test) tuple, though, if we need to.

But please let me know whether this is expected first.

**Comment by davecheney** [comment]
This is because spec norm uses lots of floating point ops.

I'll try to disabled it in ./timing.sh

On Sat, Sep 19, 2015 at 12:36 PM, Brad Fitzpatrick <notifications@github.com

**Comment by minux** [comment]
or we can reduce the N for arm in timing.sh.

**Comment by bradfitz** [comment]
Why did this only recently become a problem? The timeout used to be only 10 minutes. I _raised_ it to 20 minutes and sharded the shootout tests and only then started seeing it. Maybe I wasn't looking before?

Or was the GOARM detection just broken before and we weren't making GOARM=5 binaries previously?

**Comment by davecheney** [comment]
Likely the latter.

**Comment by davecheney** [comment]
Or perhaps more correctly, overriding GOARM detection was broken til
recently

**Comment by minux** [comment]
I think before we always use GOARM=7 (probably another reason is we used to
not run the shoutout test or didn't run on GOARM=5 builder.)

I cannot see any recent change that could cause huge performance regression
on arm.

**Comment by bradfitz** [comment]
> I think before we always use GOARM=7 (probably another reason is we used to
not run the shoutout test or didn't run on GOARM=5 builder.)

No, we always did. It wasn't special until just the other day when I experimentally disabled it.

**Comment by minux** [comment]
OK, I will do some bisect to see if we really have a FP performance
regression.

**Comment by bradfitz** [comment]
A bisection would be great. It's probably more likely a GOARM detection bug, but knowing that too would be interesting.

**Comment by davecheney** [comment]
I don't think there is a performance regression. Previously the trybots
always ran that test with GOARM=7 (it use go tool dist env, not go env)
even on the linux-arm-arm5 builder. Not this test is run with GOARM=5 on
linux-arm-arm5.

**Comment by bradfitz** [comment]
(Nit: linux-arm-arm5 was never a trybot)

Which CL changed this test to use GOARM=5 by using a different `go {tool dist,} env` whatever}

**Comment by davecheney** [comment]
3f2baa3e60b54b5cfc45995d7d3616d4a9a509fb

Previously go tool dist env returns GOARM=7, afterwards it returned GOARM=5
on all arm platforms, after 1fd78e1f600d10475b85381427bda9f14f86e0f0 go
tool dist env returns GOARM=5 where GOARM=5 was passed to the bootstrap
stage.

**Comment by minux** [comment]
This test takes more than 33 minutes on the FPU less mips64 builder,
could we skip it there too?

**Comment by davecheney** [comment]
SGTM. I'm sorry, I don't remover the specifics of how we did this for arm5.

**Comment by rsc** [comment]
The tests are disabled now. That sounds fixed to me. (Software floating point is slow.)
