### ISSUE TITLE
cmd/go: go build should honor umask

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#12692]
No matter what the umask, go build would always create a binary with perms 0755.

```
$  ( umask 0022; go build -o foo foo.go ; ls -l foo )
-rwxr-xr-x 1 ubuntu ubuntu 2848496 Sep 19 12:00 foo
$  ( umask 0000; go build -o foo foo.go ; ls -l foo )
-rwxr-xr-x 1 ubuntu ubuntu 2848496 Sep 19 12:00 foo
$  ( umask 0077; go build -o foo foo.go ; ls -l foo )
-rwxr-xr-x 1 ubuntu ubuntu 2848496 Sep 19 12:00 foo
```

Compilers (including gcc, ghc, dmd) usually respect umask while creating executables.

**Comment by ianlancetaylor** [comment]
I think this happens because moveOrCopyFile in cmd/go/build.go calls os.Chmod without considering umask.

**Comment by 0xmohit** [comment]
umask should also be considered while creating the temporary work directory and files therein.

**Comment by AndersKOlsson** [comment]
+1. This is really irritating, for example when building through the golang Docker image, and ending up with root owned, undeletable files on the host.
