### ISSUE TITLE
net/http: add possibility to debug response inside CheckRedirect

### ISSUE THREAD

**Issue by kayrus** [golang/go#12697]
Right now it is not possible to debug server response inside CheckRedirect function. It becomes annoying especially when you use HTTPS connection and can not figure out why your code doesn't work.

I suppose it should be like:

```
CheckRedirect func(req *Request, via []*Request, via_resp []*Response,) error
```

**Comment by minux** [comment]
The usual way to debug this kind of problem is to
use a custom transport.

modifying the type of the CheckRedirect field is
not acceptable given the Go 1 API guarantee.

**Comment by kayrus** [comment]
Is it possible to implement new `CheckRedirectResp`?

**Comment by rakyll** [comment]
The canonical way to debug servers is to implement a RoundTripper that dumps the request and response. You can use `httputil.DumpRequestOut` and `httputil.DumpResponse` to dump the raw HTTP request and response.

http://golang.org/pkg/net/http/httputil/#DumpRequestOut
http://golang.org/pkg/net/http/httputil/#DumpResponse
