### ISSUE TITLE
net/rpc: returned error values fail comparison check

### ISSUE THREAD

**Issue by RomanSaveljev** [golang/go#12695]
I have `go version go1.5.1 linux/amd64`

Say, server part returns `io.EOF` from an exported method, the error is received on the client side and there `err == io.EOF` is `false` instead of `true`

This small program demonstrates the issue: http://play.golang.org/p/eWECxr-OLa

I expected:

```
2009/11/10 23:00:00 EOF == EOF is true
2009/11/10 23:00:00 EOF == EOF is true
```

I got:

```
2009/11/10 23:00:00 EOF == EOF is false
2009/11/10 23:00:00 EOF == EOF is true
```

Thanks for your attention

**Comment by rjeczalik** [comment]
@RomanSaveljev You're comparing two different underlying types: https://play.golang.org/p/ZjGwVrc9ge. Use e.g. error codes/statuses instead.

**Comment by RomanSaveljev** [comment]
Thanks for explanation. This makes sense albeit is confusing for a newcomers like me... Would it be more user-friendly, if the signature of the `Call` method was changed like this?

```go
func (client *Client) Call(serviceMethod string, args interface{}, reply interface{}) ServerError
```

Then it would be clear the direct comparison is not suitable.

**Comment by robpike** [comment]
Because of the Go 1 compatibility guidelines, the signature cannot be changed.
