### ISSUE TITLE
net: golang 1.5 mac address on Windows has additional :00:00

### ISSUE THREAD

**Issue by sathishvj** [golang/go#12691]
I'd written a program in go 1.4 to retrieve mac addresses on windows and used to get the correct mac address. 
With 1.5.1 however, I'm seeing a :00:00 appended to all the mac addresses on Windows (specifically Windows 7 Professional).

Is there a reason for this (or is it simply an error on my side)?

```
 ifs, _ := net.Interfaces()
 for _, v := range ifs {
     h := v.HardwareAddr.String()
     if len(h) == 0 {
         continue
     }
     si.Macs = append(si.Macs, h)
 }
```

Bjorn Graf in [this](https://groups.google.com/forum/#!topic/golang-nuts/M-FqXQsOe_Q) thread reports: "on my Windows 10 Go 1.5,x (amd64 and 386) seems to find only the loopback pseudo-Interface with an all-00 mac while go1.4.2 lists the real interface."

**Comment by ianlancetaylor** [comment]
CC @mikioh @alexbrainman
