### ISSUE TITLE
tour: range-continued.go process took too long

### ISSUE THREAD

**Issue by devonestes** [golang/go#12694]
Context: http://tour.golang.org/moretypes/13

When running the default program on the above page, the result is an error - 'process took too long'. Even if you hit the 'Reset' button, the result is still the same when attempting to run the program.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by Skarlso** [comment]
It is missing capacity.

pow:=make([] int, 10, 10) instead of just ([] int, 10).

**Comment by minux** [comment]
I think the code is correct as is, it's just a bad caching of
the result.

@adg, perhaps we need to drop the caches as I remembered
there is another issue about bad cached entries recently.
(#12645).

**Comment by adg** [comment]
It's tricky because we do want to cache the output of programs like `for {}` as 'process took too long'. I've increased the sandbox's timeout on program execution and provisioned more sandbox servers. Let's see if that improves things.
