### ISSUE TITLE
net/http: client not following redirects by default

### ISSUE THREAD

**Issue by piazzamp** [golang/go#12705]
[this line](https://github.com/golang/go/blob/master/src/net/http/client.go#L174) in client.go causes some confusion in the default behavior of client.Do(). The documentation says that the default HTTP method of a request is GET and that, when clients issue GET requests, redirects will be followed. 

It seems that the aforementioned line should include `req.Method == ""`

**Comment by piazzamp** [comment]
here's a simple test that doesn't run in the play sandbox, but will run on your machine that allows outbound connections:
http://play.golang.org/p/njZvpYq2WN

note the behavior change when uncommenting line 16

**Comment by rakyll** [comment]
The method could be either one of the predefined methods or an extension method. I don't understand why do we support empty string as a method in the first place.

From http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html,

```
Request-Line   = Method SP Request-URI SP HTTP-Version CRLF

 Method         = "OPTIONS"                ; Section 9.2
                | "GET"                    ; Section 9.3
                | "HEAD"                   ; Section 9.4
                | "POST"                   ; Section 9.5
                | "PUT"                    ; Section 9.6
                | "DELETE"                 ; Section 9.7
                | "TRACE"                  ; Section 9.8
                | "CONNECT"                ; Section 9.9
                | extension-method
 extension-method = token
```

/cc @bradfitz

**Comment by bradfitz** [comment]
@rakyll, because we've always guaranteed and documented that, for better or worse:

https://golang.org/pkg/net/http/#Request
```
        // Method specifies the HTTP method (GET, POST, PUT, etc.).
        // For client requests an empty string means GET.
        Method string
```

So we should be consistent.
