### ISSUE TITLE
strip the http or https:// of go get https://girhub.com/xyz

### ISSUE THREAD

**Issue by thewhitetulip** [golang/go#12701]
~$ go get https://github.com/kabukky/journey
package https:/github.com/kabukky/journey: "https://" not allowed in import path.

this is the output currently, we can modify the go tool to strip the http or https and download the code. I would like to work on this if it is accepted!

**Comment by davecheney** [comment]
Sorry. go get works on package names, not urls. Adding support to transparently convert urls to package paths would confuse this message and also bloom into a rash of additional feature requests for other url styles to be support (ssh:// ?)

**Comment by thewhitetulip** [comment]
Okay, cool.
