### ISSUE TITLE
bsdthread_register error iOS 8

### ISSUE THREAD

**Issue by eswick** [golang/go#12704]
Hi. I am able to cross-compile code in Go to iOS. However, when running the code on iOS (jailbroken), the following error occurs:

fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x49c990, 0x21)
	/Users/eswick/Development/go/src/runtime/panic.go:527 +0x78 fp=0x7bd7d8 sp=0x7bd7cc
runtime.goenvs()
	/Users/eswick/Development/go/src/runtime/os1_darwin.go:73 +0x88 fp=0x7bd7f4 sp=0x7bd7d8
runtime.schedinit()
	/Users/eswick/Development/go/src/runtime/proc1.go:60 +0x68 fp=0x7bd818 sp=0x7bd7f4
runtime.rt0_go(0x1, 0x7bd868, 0x1, 0x7bd8e4, 0x0, 0x7bd8f4, 0x7bd908, 0x7bd916, 0x7bd920, 0x7bd93e, ...)
	/Users/eswick/Development/go/src/runtime/asm_arm.s:60 +0x84 fp=0x7bd858 sp=0x7bd818

From some research I've done, apparently this bug is new in iOS 8. Any info?

Note, I compiled this with cgo turned off.

**Comment by minux** [comment]
You need to enable cgo.

**Comment by eswick** [comment]
Upon enabling cgo, I get the following error:

clang: error: argument unused during compilation: '-mno-thumb'

I am cross compiling from OS X to iOS.

**Comment by eswick** [comment]
I fixed the issue by re-compiling my cross compiler with the following flags:

CC_FOR_TARGET=/Users/eswick/Development/go/misc/ios/clangwrap.sh CXX_FOR_TARGET=/Users/eswick/Development/go/misc/ios/clangwrap.sh
