### ISSUE TITLE
os: file current cursor is 0 when open file as append mode with exist file(size>0)

### ISSUE THREAD

**Issue by yuyi98** [golang/go#12710]
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.OpenFile("aaa.dat", os.O_WRONLY|os.O_APPEND, 0666)
	if err != nil {
		fmt.Println("Open aaa.dat failed")
		return
	}

	defer f.Close()

	aa, _ := f.Seek(0, os.SEEK_CUR)
	fmt.Println("cursor position : ", aa)
}
```

cursor position should be size of "aaa.dat", but it's 0.

**Comment by bradfitz** [comment]
Which operating system do you see this on? I assume some Unix variant?

It's quite likely that this behavior is platform-specific.

Linux man pages say:

```
O_APPEND
The file is opened in append mode. Before each write(2), the file offset is positioned at the end of the file, as if with lseek(2). O_APPEND may lead to corrupted files on NFS file systems if more than one process appends data to a file at once. This is because NFS does not support appending to a file, so the client kernel has to simulate it, which can't be done without a race condition.
```

Go's docs merely say:

```
        O_APPEND int = syscall.O_APPEND // append data to the file when writing.
```

Perhaps we're missing some words somewhere. We should also verify that Unix, Windows, and Plan 9 are consistent.

**Comment by yuyi98** [comment]
system:  windows 7 64bit, go 1.5.1 amd64

**Comment by bradfitz** [comment]
I ran an experiment in https://go-review.googlesource.com/14807

Unix and Windows return 0 for the seek position on an O_APPEND file. Plan 9 returns the actual value. I imagine we should change Plan 9 to match the behavior of the popular platforms. (cc @0intro)

And I guess we should just document the behavior on Unix and Windows. (cc @robpike)

**Comment by minux** [comment]
I'd document that calling Seek on a file opened with O_APPEND
is unspecified.

(I.e. you shouldn't call seek and even if the returned value is
non-zero, it's a race condition.)

**Comment by bradfitz** [comment]
@minux, SGTM.

It's only a race if you ever called Write, right? But we can just say it's unspecified and leave it at that.
