### ISSUE TITLE
spec: Make Composite Literals description more precise

### ISSUE THREAD

**Issue by basiliothecat** [golang/go#12717]
The 1.5.1 language spec ($GOROOT/doc/go_spec.html) when describing rules for constructing composite literals, says `The LiteralType must be a struct, array, slice, or map type`. The option for `TypeName` in `CompositeLit` production and actual implementation suggest that it's the `LiteralType`'s underlying type that should be of a struct, array, slice or map.

e.g.

type Digits [2]byte
var binaryAlphabet = Digits{0,1}

here, `Digits` is a `TypeName`, but isn't strictly speaking an array, though it's underlying type is.

**Comment by cespare** [comment]
@basiliothecat perhaps you meant precise, rather than concise, in the issue title.

**Comment by basiliothecat** [comment]
On Tue, Sep 22, 2015 at 12:58:57PM -0700, Caleb Spare wrote:
> @basiliothecat perhaps you meant precise, rather than concise, in the issue title.

Oops.

You seem to be plenty good at reading mind!

**Comment by basiliothecat** [comment]
Per proposed change line #2230 - i don't see how that helps conveying the fact that it is underlying type that matters. 

Why not just put it straight - The underlying type of LiteralType should be array, ... ? That ain't as bulky and what's best - it keeps it precise!

Line #2247 - isn't it about the field name declared in *struct type*?

**Comment by griesemer** [comment]
@basiliothecat re line 2230: Just keep in mind we have some imprecision in lots of places (for ease of reading) and we don't lose clarity. For instance, in map types ( https://golang.org/ref/spec#Map_types ) we talk about the "key type" not the underlying type of KeyType; etc.

Making this more precise everywhere does add bulk and makes the prose more uneven w/o really adding much clarity.
