### ISSUE TITLE
termios support wanted

### ISSUE THREAD

**Issue by gdamore** [golang/go#12716]
POSIX defines termios functions like tcgetattr, tcsetattr, etc.

Right now some code does horrible non-portable things to work around their absence in go.  For example, or prompting for passwords, some packages spawn the stty command, whereas others have hard coded syscall() ioctls.  Neither of these are portable, and often we wind up with packages that don't work on platforms like solaris.

In the x/sys/unix package, we ought to define implementations of the termios functions that behave as per POSIX 1003.1.  Probably also we can define some "higher level" API to do this well, which would properly live not in x/sys but somewhere a bit more portable.  (One can imagine having functions to manipulate a text console that are different on Windows for example.) 

As a concrete example of a higher level function that would be broadly useful, consider getpassphrase(), which could be implemented in terms of termios on POSIX systems, but differently on Windows.

I'd be willing to contribute termios functions for the POSIX systems.  On Solaris this would use the C library functions -- on other systems I guess it amounts to ioctl system calls.

**Comment by ianlancetaylor** [comment]
See https://golang.org/cl/14587 .  You may want to comment there.

For that matter, is this issue different from #12574 ?

**Comment by gdamore** [comment]
Actually, yes, 12574 and the commit proposed with 14587 will address this.

And I'm strongly in favor of the typed ioctls.  I have some concerns, which I'll post there.  I'm closing this for now.
