### ISSUE TITLE
net/textproto: ReadMIMEHeader returns invalid UTF8 in its error message

### ISSUE THREAD

**Issue by signalsensefred** [golang/go#12715]
If ReadMIMEHeader returns an error because the MIME header is invalid, the string in that error contains the original MIME header, which can end up being invalid Unicode. The error string should be escaped, perhaps by formatting the MIME header as a list of byte values if utf8.ValidString returns false on it.

**Comment by bradfitz** [comment]
We can't possibly know the context in which you're rendering your errors. You also seem to confuse Unicode and UTF-8. I think it's up to the caller to properly render or propagate errors. We don't know the original encoding and I don't believe we have any existing precedent for promising UTF-8 error.String() values.
