### ISSUE TITLE
time: time.Parse parses invalid dates

### ISSUE THREAD

**Issue by austincb1** [golang/go#12728]
`go version go1.5.1 windows/amd64`
Windows 7, `cmd /v` says `Microsoft Windows [Version 6.1.7601]`

`time.Parse()` parse invalid dates where it should report an error, for example: 31 Jun 2015 and 30 Feb 2015 are not valid.

Example in playground: http://play.golang.org/p/R4hQhgy24d

**Comment by bradfitz** [comment]
Intentional. See #12333.
