### ISSUE TITLE
cmd/gofmt: inconsistent spaces around bitwise &

### ISSUE THREAD

**Issue by RomanSaveljev** [golang/go#12720]
Go version: `go version go1.5.1 linux/amd64`

What I did: used gofmt on my source code
What I expected: have spaces around bitwise `&` everywhere
What I saw: in one occasion there was no spaces around the operator

I have put "before" and "after" code into a [gist](https://gist.github.com/RomanSaveljev/ced32bbe4324d95e6c49/revisions?diff=split), so from the diff you can easily see the changes applied by gofmt

**Comment by griesemer** [comment]
Working as intended. gofmt uses spaces around binary expressions to express binding strength. Depending on nesting level, spaces are removed.

**Comment by griesemer** [comment]
See also issue #1206, #1848, #1861, #7880, and #11497.

Youl could also find these easily by searching for "gofmt inconsistent spaces".

**Comment by RomanSaveljev** [comment]
@griesemer I did look for duplicates although, I guess, I only checked open issues (will look better next time).

All but #11497 are closed for the reasons of emphasizing the precedence in otherwise complex expressions. Do we have to highlight in this example `sort.SearchInts(arr, i & maxKeys)` that `&` is evaluated before `,`?

I read the long comment for `binaryExpr`:

> To choose the cutoff, look at the whole expression

Is `(arr, i & maxKeys)` a single expression? I might be lacking the deep insights into Go now, but from other languages I practice I remember that it is not. A generic compiler may decide to evaluate function parameters in any order and there is no precedence between them "per se", which might have to be highlighted. (I might have used wrong wording here and I hope my point is understandable)

I am sorry, but in my opinion this error report is different from other closed reports. I could not find the answer from `binaryExpr` comment either.

**Comment by griesemer** [comment]
@RomanSaveljev "(arr, i & maxKeys)" is not a single expression. But the point is that "i & maxKeys" if standing "alone", including standing alone inside ()'s, gets the space around the '&', and otherwise it won't. Which is why we get
```
	f(arr, i&maxKeys)
	g(i & maxKeys)
	h = (i & maxKeys)
	i = x + i&maxKeys
```
to show some examples. That is, an expression inside a parameter list (== a list of expressions) is treated similarly to an expression inside larger expression (e.g., "a list of terms in a sum" as in a + b + c where each a, b, c is "inside").
