### ISSUE TITLE
encoding/json:Unmarshal() doesn't work for struct with lower case field names 

### ISSUE THREAD

**Issue by huangyingyi** [golang/go#12730]
For a struct with a field of integer value, Unmarshal() doesn't put the value in the field. The value is always 0.  Example code:
-------------
package	main
import (
        "fmt"
        "encoding/json"
)
type Animal struct {
	name  string
	order int
}
func main() {
     var jsonBlob = []byte(`
                  {"name": "Platypus", "order": 10}
                                  `)
                     var one Animal
                     var err = json.Unmarshal(jsonBlob, &one)
				if err != nil {
                                         fmt.Println("error:", err)
                           }
                     fmt.Printf("One:%+v", one)
}
----------
The order field is of value 0 which should be 10. If the field name is changed to "Order", then it works.

**Comment by stemar94** [comment]
Works as intended. The fields need to be exported (Upper case starting identifier).

But maybe there could be something added to the documentation in the package.
I only find information about that in: http://blog.golang.org/json-and-go#Decoding

Marvin

**Comment by minux** [comment]
It's fundamentally limited by the reflect package that
any package can't set unexported fields in types
defined in other packages (without using unsafe.)
