### ISSUE TITLE
Possible redeclaration of var in for loop

### ISSUE THREAD

**Issue by elieteyssedou** [golang/go#12735]
Hi,

I was trying Go on http://tour.golang.org/, and I saw that it was possible to declarate two times the same var using := in for loop.
I think that's weird... That's why I'm here.

- Here is my test :
```go
package main

import "fmt"

func main() {
	i := "Hello"
	a := 0
	for a < 2 {
		fmt.Println(i)
		i := "World !"
		fmt.Println(i)
		a++
	}		
}
```

- Output :

>Hello
>World !
>Hello
>World !

Can someone explain that ?

Elie.

**Comment by bradfitz** [comment]
We only use our bug tracker for tracking bugs so let's move discussion of this to the golang-nuts@ mailing list: https://groups.google.com/forum/#!forum/golang-nuts  

FWIW, the topic you're interested is called "scope". See https://en.wikipedia.org/wiki/Scope_(computer_science)
