### ISSUE TITLE
playground: why is share blocked from Hong Kong

### ISSUE THREAD

**Issue by chpapa** [golang/go#12747]
Regarding the following PR:

https://github.com/golang/playground/commit/64f7014affabd5446cabfe7b9e362502c77caa06#commitcomment-13430374

Change Id: I6a9f012346cb332deaba8eae4375040a00e08e57

It was said to hide and block share functionality from specific countries, to serve *.golang.org to Chinese users.

However, Hong Kong (HK) is included as one of the X-AppEngine-Country to disable the functionality, while it is NOT behind the GFW and have a different legal system.

This would be annoying for HongKong residents, so my question is why is HK included? Shall it be removed? (And since Macau is not included so I suppose this is a mistake?)

**Comment by chpapa** [comment]
cc: @adg

**Comment by adg** [comment]
Jason?

**Comment by mrkschan** [comment]
FYI, I live in Shenzhen (a city of China) and use SSH tunnel to visits site like FB / Twitter / Golang playground / etc. I don't see any problem in accessing the mentioned sites so far since 2014.

**Comment by hnfong** [comment]
Why is the patch required anyway?

A suspicion that "Chinese" IP addresses would abuse the system? Forgive my ignorance but I really can't see how it would help any way...

**Comment by stevenyeung** [comment]
I wonder as well, and I don't see the restriction on HK is necessary.

**Comment by adg** [comment]
It is clear that many people wonder. There's no need to comment unless you have information to give. @jbuberel is the one with that information. We will wait for him.

**Comment by hnfong** [comment]
@adg  barring secret agreements with the GFW administrators, the fact that a patch doesn't make any sense should at least mean comments explaining the changes should be added......

I understand you don't want the comments here to become something like youtube, but FWIW it gets on a lot of Hong Kong people's nerves to treat "HK" as Yet Another Chinese City... and of course, this patch raises the usual censorship, discrimination issues. I've refrained from commenting on those fronts before there's more information on the motivation of the patch, but I just wanted to make it clear that the patch doesn't make sense per se and sorely needs a bit of explanatory comments.

**Comment by wanleung** [comment]
I feel disappointed that HK (Hong Kong) and RC (Taiwan) which are not in the China GFW, both regions/countries have their own legal system which are independent from Mainland China are being blocked by this commit.

**Comment by adg** [comment]
After some investigation it appears that the `HN` and `RC` country codes were included in the block list by mistake. I have sent two changes to remove them from the various lists:

https://go-review.googlesource.com/15082
https://go-review.googlesource.com/15083

I hope to have these fixes submitted and deployed in the next 24 hours.

I'd like to thank everyone who brought this to our attention, and apologize for any inconvenience caused.
