### ISSUE TITLE
exp/shiny/driver: inconsistency btw linux-x11 and linux-gl drivers

### ISSUE THREAD

**Issue by sbinet** [golang/go#12740]
hi,

applying the following diff on top of  golang/exp@b80da08 (`shiny/driver/gldriver: per-window GL mutexes`):
```
diff --git a/shiny/driver/driver_x11.go b/shiny/driver/driver_x11.go
index 98ea8e5..4a370ad 100644
--- a/shiny/driver/driver_x11.go
+++ b/shiny/driver/driver_x11.go
@@ -7,10 +7,11 @@
 package driver
 
 import (
-       "golang.org/x/exp/shiny/driver/x11driver"
+       //drv "golang.org/x/exp/shiny/driver/gldriver"
+       drv "golang.org/x/exp/shiny/driver/x11driver"
        "golang.org/x/exp/shiny/screen"
 )
 
 func main(f func(screen.Screen)) {
-       x11driver.Main(f)
+       drv.Main(f)
 }
```

I get different output from running `go run shiny/example/basic/main.go`.

when `drv == x11driver` I get 2 squares where the second is just translated wrt the first.
when `drv == gldriver` I get 2 squares where the second is translated and rotated wrt the first.

first image (`drv==x11driver`):
![x11](https://cloud.githubusercontent.com/assets/1070920/10079531/dfcf8b36-62ea-11e5-949b-5f7a2ace2330.png)

second image (`drv==gldriver`):
![gl](https://cloud.githubusercontent.com/assets/1070920/10079534/eaf4e6e6-62ea-11e5-950a-a51732e2ec1f.png)

I am using `go-1.5.1` on:
```sh
$ uname -a
Linux zoidberg 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
```

**Comment by crawshaw** [comment]
That's a TODO in the X11 driver:

https://github.com/golang/exp/blob/master/shiny/driver/x11driver/texture.go#L58

I believe (Nigel is the expert, but he just left on a long leave) this needs a render.Transform applied to the render.Picture. As I have my X11 machine out, I'll give it a try.
