### ISSUE TITLE
release: PGP-sign source and binary releases

### ISSUE THREAD

**Issue by 4ad** [golang/go#12749]
We should sign the official releases.

**Comment by bradfitz** [comment]
We provide the downloads' checksums over https. We can do better than SHA-1 in future releases, but signing the binaries adds little extra benefit over providing the hashes securely. We do at least already sign the OS X and Windows releases, but that's to make the operating systems happy

**Comment by adg** [comment]
It's much easier to verify a hash than a PGP signature. Plus we already have an HTTPS certificate for golang.org. What's the additional value in also having a PGP key?

**Comment by adg** [comment]
Issue #12057 is about switching to SHA256.

**Comment by rsc** [comment]
Switching to SHA256 seems much better, and less work. Closing as dup of #12057.
