### ISSUE TITLE
encoding/csv: add field ForceQuotes to Writer

### ISSUE THREAD

**Issue by stemar94** [golang/go#12755]
With a boolean field ForceQuotes in the csv.Writer one could force quotation of fields.

**Comment by bradfitz** [comment]
Why?

**Comment by stemar94** [comment]
I had some compability problems, when forced to escape fields not needed to be escaped by current implementation.
>Each field may or may not be enclosed in double quotes
> - [[RFC 4180]](https://www.ietf.org/rfc/rfc4180.txt)

Even if there is no actual specification I guess the RFC is status quo.

And if you would wrap something around the writer as
```go
func WriteWrapper(w *csv.Writer, record []string) error {
    for i, field := range record {
         record[i] = `"` + field+ `"`
    }
    return w.Write(record)
}
```
you would end up with """file2""","""field2"""

**Comment by rsc** [comment]
This package can't be all things to all people.

Unless the compatibility problems you alluded to are widespread, I'd prefer not to add more complexity to this package. I believe this package as it stands today matches the CSV produced by Microsoft Excel and Google Drive. That should be good enough. 

If you really just want to print fully-quoted CSV, you don't even need this package:

	func printCSV(w io.Writer, data [][]string) {
		for _, row := range data {
			sep := ""
			for _, cell := range row {
				fmt.Printf(`%s"%s"`, sep, strings.Replace(cell, `"`, `""`, -1))
				sep = ","
			}
			fmt.Printf("\n")
		}
	}

**Comment by u007** [comment]
what about 
`
\n and \r\n 
`
?
