### ISSUE TITLE
runtime: OS X: hashmap caused SIGILL: illegal instruction

### ISSUE THREAD

**Issue by VojtechVitek** [golang/go#12753]
- go1.5.1 darwin/amd64
- OS X Yosemite 10.10.5 (14F27)
- Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz

```
SIGILL: illegal instruction
PC=0xc12c m=11

goroutine 114
[running]:
runtime.evacuate(0x7e7880, 0xc82081f1a0, 0x1)
    /usr/local/go/src/runtime/hashmap.go:819 +0x1ec fp=0xc820a29cb0 sp=0xc820a29bf0
runtime.growWork(0x7e7880, 0xc82081f1a0, 0x0)
    /usr/local/go/src/runtime/hashmap.go:795 +0x83 fp=0xc820a29cd0 sp=0xc820a29cb0
runtime.mapassign1(0x7e7880, 0xc82081f1a0, 0xc8204a6f90, 0xc820a29de0)
    /usr/local/go/src/runtime/hashmap.go:433 +0x176 fp=0xc820a29d78 sp=0xc820a29cd0
github.com/--------------.func4(0xc8207463b0,
0xc8200b9200, 0x12, 0x20, 0xc820849c00, 0x8, 0x8, 0xc82081f1a0)
    /Users/vojtechvitek/go/src/github.com/--------------.go:175 +0x6e5 fp=0xc820a29f50 sp=0xc820a29d78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820a29f58 sp=0xc820a29f50
created by github.com/--------------Func
    /Users/vojtechvitek/go/src/github.com/--------------.go:178 +0x700

... other goroutines here ... 

rax    0x7e7880
rbx    0x0
rcx    0x40
rdx    0xc820767200
rdi    0xc82028b528
rsi    0xc820767248
rbp    0x200a0a202e7961
rsp    0xc820a29bf0
r8     0xc82081f1a0
r9     0xc82081f1a0
r10    0xc82028b528
r11    0x3fe00ff803fe00
r12    0x24
r13    0xc745e0
r14    0x3fe00ff
r15    0x36
rip    0xc12c
rflags 0x10293
cs     0x2b
fs     0x0
gs     0x0
```

https://github.com/golang/go/blob/go1.5.1/src/runtime/hashmap.go#L819

Userspace pseudo-code:
```go
func Func() {
    mapData := make(map[int64]*Type)

    var wg sync.WaitGroup
    wg.Add(1)
    go func() {
        defer wg.Done()
        // ...
        mapData[key] = value      ///// <<<======= 
        // ...
    }()
    wg.Wait()
}
```

**Comment by bradfitz** [comment]
Please confirm you have no races in your code first. See http://blog.golang.org/race-detector

That limited code snippet looks suspicious, like you're unsafely updating a map without synchronization from multiple goroutines.

If you confirm you have no races and provide a reproducible example (or your entire source code), we can investigate. But usually this is due sort of failure is due to bugs in your code, usually races.

**Comment by VojtechVitek** [comment]
@bradfitz thanks, will do.

It might have been caused by a race condition in the code. So, is that expected that `panic()` / `recover()` don't capture this?

**Comment by bradfitz** [comment]
If you have a race, all bets are off and Go promises nothing.

**Comment by minux** [comment]
What is the instruction at 0xc12c? Is it in the TEXT segment?

**Comment by VojtechVitek** [comment]
Fyi, I found the race condition in the userspace code. Two goroutines were writing data into one map at the same time (missing mutex protection). Thanks for your help.

@minux correct, 0xc12c belongs to TEXT segment.
