### ISSUE TITLE
x/mobile: Segmentation fault: 11 on 0px window resize

### ISSUE THREAD

**Issue by mokiat** [golang/go#12752]
If I resize the window vertically to 0px height, I get the following error on the terminal.

``` bash
Segmentation fault: 11
```

I am using the following:
- OS X 10.10.5
- `go version go1.5.1 darwin/amd64`
- `gomobile version +afa8a11 Fri Sep 18 00:19:08 2015 +0000 (android,ios);`

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by changkun** [comment]
This issue does not exist today. Close.
