### ISSUE TITLE
OS X negative values issue using binary.LittleEndian Put/Uint32()

### ISSUE THREAD

**Issue by mrcook** [golang/go#12765]
In trying to save/load data to files I've been converting `int` values to `[]byte` arrays using the `binary` package. However I'm getting issues with negative numbers, which when tested using Playground, work, but when run on my local OS X they do not.

		package main

		import "fmt"
		import "encoding/binary"

		func main() {
			var a int
			a = -650

			b := make([]byte, 4)
			binary.LittleEndian.PutUint32(b, uint32(a))

			fmt.Println(toInt(b))
		}

		func toInt(b []byte) int {
			return int(binary.LittleEndian.Uint32(b))
		}

http://play.golang.org/p/pYWj1hBCUS

Playground outputs `-650` (expected), while on OS X I get `4294966646`.

My system is a 2011 Macbook Air running OS X 10.9.5. I've tried this with Go 1.4.2, 1.5 and 1.5.1 (installed with Homebrew), but the results are the same each time.

Is this an OS X issue, or desired behaviour?

**Comment by bradfitz** [comment]
This is expected behavior. (the size of "int" varies by platform... change your toInt to return a int32 if you depend on 4 bytes of two's complement)

Let's move discussion of this to the golang-nuts@ mailing list, as there's no bug to track here on the bug tracker.
