### ISSUE TITLE
go 1.5.1 bug?

### ISSUE THREAD

**Issue by wangds9** [golang/go#12760]
package main 

    import "fmt"
 
    func main() {
       a := []int{0, 1, 2, 3, 4, 5, 6, 7}
       b := a[0:3]
       b = append(b, 9)
       b = append(b, a[3:]...)
       fmt.Println(b)
     }
    output: b = [0 1 2 9 9 4 5 6 7] 
    want: b = [0 1 2 9 3 4 5 6 7]

**Comment by rakyll** [comment]
Slicing doesn't copy the underlying array and create a new window. It returns a slice that points to the exact same array pointer.

``` go
a := []int{0, 1, 2, 3, 4, 5, 6, 7}
b := a[0:3]      // b is a slice value pointing to the same array
b = append(b, 9) // when you mutate b's values, you also mutate a's values.
``` 
The behavior and its rationalization is explained throughly at http://blog.golang.org/go-slices-usage-and-internals.

**Comment by wangds9** [comment]
thank you. and how can i do like this, insert element into slice

**Comment by minux** [comment]
Please ask questions on the Go mailing lists. Thanks.

For your specific question, please see
golang.org/wiki/SliceTricks
