### ISSUE TITLE
cmd/go: Followup step for CL 12192 external test repo.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#12769]
This is an issue that should be resolved by @rsc. Ian Lance Taylor has asked me to create an issue for this:

> Please open an issue for this at https://golang.org/issue .  Thanks.

I am following up with one remaining step that should be done by @rsc for a merged CL https://go-review.googlesource.com/#/c/12192/. This is really really minor cleanup issue, but it should not take more than 1 minute for @rsc to resolve (and I just want to get it checked off from my TODO list).

I will quote the CL conversation here for context:

##### Dmitri Shuralyov

> Just in case it's at all helpful, I've rewritten the history as it
> should be with new import paths ("github.com/rsc/go-get-issue-9224-{cmd,lib}")
> and pushed that on "rsc-import-paths" branches:
> https://github.com/shurcooL/go-get-test-cmd/commits/rsc-import-paths
> https://github.com/shurcooL/go-get-test-lib/commits/rsc-import-paths

##### Russ Cox

> > Just in case it's at all helpful, I've rewritten the history as it
> > should be with new import paths ("github.com/rsc/go-get-issue-9224-{cmd,lib}")
> > and pushed that on "rsc-import-paths" branches:
> > https://github.com/shurcooL/go-get-test-cmd/commits/rsc-import-paths
> > https://github.com/shurcooL/go-get-test-lib/commits/rsc-import-paths
>
> Thanks. Pushed those.

##### Dmitri Shuralyov

> > Pushed those.
>
> https://github.com/rsc/go-get-issue-9224-lib looks good.
>
> But https://github.com/rsc/go-get-issue-9224-cmd still has the wrong default branch "work". Its "master" branch should be set default (in GitHub repo settings at https://github.com/rsc/go-get-issue-9224-cmd/settings) and "work" branch can be deleted.

##### Dmitri Shuralyov

> Just checking in here, the above followup step is still not done.

# Issue and Resolution

The issue is that Russ Cox has pushed the changes to the repo, but the branch he pushed to is not the default branch.

The resolution, as I commented above, is:

> But https://github.com/rsc/go-get-issue-9224-cmd still has the wrong default branch "work". Its "master" branch should be set default (in GitHub repo settings at https://github.com/rsc/go-get-issue-9224-cmd/settings) and "work" branch can be deleted.

Note that `go get` ignores the default branch set on GitHub, so `master` is used anyway. But it can be confusing to see the wrong default branch in the github repo.

**Comment by shurcooL** [comment]
> Note that `go get` ignores the default branch set on GitHub, so `master` is used anyway.

https://github.com/golang/go/issues/9032 suggests that this might've changed, although in my testing just now it doesn't seem to be:

```bash
~ $ go get github.com/rsc/go-get-issue-9224-cmd
~ $ cd $GOPATH/src/github.com/rsc/go-get-issue-9224-cmd
go-get-issue-9224-cmd $ git branch
* master
  work
```

(This was done while `work` branch was still the default branch on that GitHub repo.)

**Comment by rsc** [comment]
Made master the default branch and deleted work.

**Comment by shurcooL** [comment]
Thank you very much! Confirmed, this issue is resolved.
