### ISSUE TITLE
Today's not Tuesday

### ISSUE THREAD

**Issue by Dysmondad** [golang/go#12761]
Context: https://tour.golang.org/flowcontrol/10

Today is Saturday. At best it could be Sunday depending on where your server is located. But on September 26th, 2015, it is NOT Tuesday.

Add this to the code sample: fmt.Println(today)
It returns Tuesday: WRONG!

**Comment by dominikh** [comment]
Please read the text to the right:

> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader. 

That's a Tuesday.
