### ISSUE TITLE
strings.TrimRight remove one more letter.

### ISSUE THREAD

**Issue by rockneurotiko** [golang/go#12771]
I don't know if this is the expected result, but I hope it isn't:

``` go
a := strings.TrimRight("1234t.html", ".html")
fmt.Println(a) // Expected 1234t, get 1234
```

[Playground](http://play.golang.org/p/61K08BW1vL)

Edit (Information about my machine according to the guidelines)
Version: 1.5.1
OS: ArchLinux x86_64
The other things are already answered :smile:

**Comment by cespare** [comment]
Please re-read the docs for TrimRight.

You want TrimSuffix: http://play.golang.org/p/gVdhgTSMoL

**Comment by rockneurotiko** [comment]
Thanks.. my bad u.U
