### ISSUE TITLE
net: NXDOMAIN replies from a non-recursive server produce "server misbehaving" errors instead of "no such host"

### ISSUE THREAD

**Issue by gplalonde** [golang/go#12778]
From:
https://github.com/golang/go/blob/ced0646fe5ed9abb3b51fa99748b090f1dfe90e8/src/net/dnsclient.go#L43

it looks like any NXDOMAIN reply where the server doesn't allow recursive queries is treated as "server misbehaving". I would expect this to be treated like any other case where the name doesn't exist and get a "no such host" error instead.

Any reason why we have the "&& dns.recursion_available" part of the condition?

**Comment by dpiddy** [comment]
Is there agreement that the check should be removed?

In looking for prior art I found [a similar check in glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=resolv/res_send.c;h=3550740ada0774c6d50d37a4011d5119876e3543;hb=HEAD#l1335) but it takes additional things into account (answer count == 0, no AA bit, additional record count == 0) before deciding to try another server, if my reading and interpretation are correct.

For maximum strictness the check makes sense: the Go stub resolver expects to talk to a recursor. If the server replied claiming a name doesn't exist but at the same time says recursion is not available maybe that is an issue. But if other stub implementations, such as glibc, don't care about that as much then maybe Go's shouldn't either.

**Comment by ianlancetaylor** [comment]
I think there is agreement that something should be done.  I don't know enough about the issue to know if simply removing that check is the right thing to do.

In the absence of more clever analysis emulating glibc sounds like a good way to go.

**Comment by dpiddy** [comment]
My reading and interpretation were a bit off!

The check I linked is for a different condition (rcode == NOERROR, mainly) and is used to signal a change to the next nameserver when trying a name. I believe in the current Go implementation the returning of [this error](https://github.com/golang/go/blob/25a28da0807f3fa85588fb219f6fa40314bde675/src/net/dnsclient.go#L88) when a response contains no useful answers does the same thing. I haven't found anywhere else in glibc where the RA bit factors in when deciding whether to accept an answer or not.

In addition to the one linked for this issue there is also [this check](https://github.com/golang/go/blob/735c65fa9c8569a8d40411056f6cfa7dbe28a689/src/net/dnsclient_unix.go#L185) that considers the RA bit. I think at least that part of the greater condition could be removed, if not reducing it to just `if err == nil` as it seems to duplicate checks that `answer` does already.

Will open a CL for this.

**Comment by mdempsky** [comment]
For what it's worth, djbdns's stub resolver also ignores whether the server sets RA when answering an RD query.

**Comment by dpiddy** [comment]
I have been meaning to check, thanks. At some point I think it would be good to dig for other behavior changes/improvements we could borrow from stub resolvers in the various libc's and djbdns. djbdns' reloading of `resolv.conf` after N requests (in addition to after N seconds which Go's does now), for example.
