### ISSUE TITLE
x/exp/inotify: go get fails on non-linux OSs

### ISSUE THREAD

**Issue by karlkfi** [golang/go#12774]
This is an issue regarding `golang.org/x/exp`. Hopefully this is the right place to report, since https://github.com/golang/exp does not accept issues or PRs. If not, let me know.

### What version of Go are you using (go version)?
This problem is independent of go version.

### What operating system and processor architecture are you using?
This problem occurs on all non-linux operating systems. 
Tested on `go1.5.1 darwin/amd64`

### What did you do?

```
$ go get golang.org/x/exp/inotify
```

### What did you expect to see?
Expected `go get` not to error.

### What did you see instead?

```
$ go get golang.org/x/exp/inotify
golang.org/x/exp/inotify: no buildable Go source files in /Users/karl/go/src/golang.org/x/exp/inotify
$ echo $?
1
```

### More Context
One example of the failure behavior is to try to build [Kubernetes](https://github.com/kubernetes/kubernetes) on a Mac. The Godep restore fails to checkout the required dependencies, because Godep uses `go get`.

This isn't normally a problem if your application is linux-only, because developers expect to only build it on linux, but if you optionally use this package (OS detection or command detection) this means go getting your project will now fail on non-linux OSs. 

### Proposed Solution
One fix would be to add another file to the package that builds on non-linux OSs. Either a `doc.go` for package docs or an `inotify_other.go` would work. This file would just include the package def. This way compilation would still fail, if you required the linux-only types from a non-linux go file, but `go get` would succeed.

**Comment by rakyll** [comment]
You can use `go get golang.org/x/exp/inotify/...` to clone the entire tree. go get will output a warning that here are no matching packages but the process will exit with a zero status code.

Specifically for the Kubernetes' build process, you must file an issue against them to see what other alternatives they can provide for those who would like to cross compile. Please reopen the issue if Kubernetes cannot find a solution.

**Comment by karlkfi** [comment]
The Kubernetes issue is actually more of a Godep issue, if that's the suggested workaround. 

However, if that workaround is put into Godep it will start censoring significantly more code, which is not a very good option.

**Comment by karlkfi** [comment]
There is a related bug in godep: https://github.com/tools/godep/issues/186
