### ISSUE TITLE
fmt: Sscanf doc disagrees with implementation

### ISSUE THREAD

**Issue by bcmills** [golang/go#12788]
https://golang.org/pkg/fmt/#Sscanf says:
> Newlines in the input must match newlines in the format.

However, in the current implementation, trailing newlines in the format string are treated as matching the end of the input string:
http://play.golang.org/p/r2f16aAYbS

Either the package documentation or the implementation should be updated.  (Probably the package documentation, since a significant number of programs are likely already relying on this behavior.)

**Comment by cznic** [comment]
> Newlines **in the input must** match newlines in the format.

There's no newline in input in the linked example, ie. there's nothing to match. Compare with, for example, http://play.golang.org/p/k8KMqjPRFa

**Comment by bcmills** [comment]
> There's no newline in input in the linked example, ie. there's nothing to match.

Yes, that's the point.  According to the documentation, fmt.Sscanf should return an error in this case (as it does for, say, http://play.golang.org/p/T1_RAgYLC-).

That is: according to the documentation, the newline in the format string should require a corresponding newline in the input string in order to return a nil error.  It currently does not.

**Comment by rsc** [comment]
Up to Rob.

**Comment by rsc** [comment]
Up to Rob.

**Comment by rsc** [comment]
Up to Rob.
