### ISSUE TITLE
fmt: Empty slice and nil slice are printed both as empty slice

### ISSUE THREAD

**Issue by krnowak** [golang/go#12780]
Please see following snippet (also saved in http://play.golang.org/p/bTc5CWT--P):
```go
package main

import "fmt"
import "reflect"

func main() {
	var nilArray []string = nil
	emptyArray := []string{}
	if !reflect.DeepEqual(nilArray, emptyArray) {
		fmt.Printf("They are different as expected, let's see if this is going to be helpful message, like you would like to receive in some test\n")
		fmt.Printf("Expected:\n%+v\nGot:\n%+v\n", nilArray, emptyArray)
	}
}
```

I would expect it to print something like:
```
Expected:
<nil>
Got:
[]
```

but instead, I'm getting:
```
Expected:
[]
Got:
[]
```

Tracking what actually is different might be a PITA in some more complex data structures.

**Comment by cznic** [comment]
When the dictinction matters, the `#` verb modifier can be used to show it: http://play.golang.org/p/smJjDhLM-H

**Comment by krnowak** [comment]
@cznic: Thanks for the hint. But the point probably still stands.

**Comment by ianlancetaylor** [comment]
This is intended behaviour and even documented behaviour.
