### ISSUE TITLE
net/http/httptest: http.Get succeed after Server.Close

### ISSUE THREAD

**Issue by carter2000** [golang/go#12781]
After close a httptest.Server, the following request should failed, but sometimes it succeed.
example code: https://play.golang.org/p/IFv6BKjRgt
more simple one: https://play.golang.org/p/FcpbVEf_HI  (detect deadlock on play.golang.org, but hit "unexpected get succeed" on my server)
go version: go version go1.5.1 linux/amd64

```
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
)

func main() {

	var i int
	for {
		i++
		fmt.Println(i)
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		}))
		resp, err := http.Get(ts.URL)
		if err != nil {
			fmt.Println("unexpected get failed", err)
			break
		}
		resp.Body.Close()
		
		ts.Close()
		
		resp, err = http.Get(ts.URL)
		if err == nil {
			resp.Body.Close()
			fmt.Println("unexpected get succeed")
			break
		}
	}
}
```

**Comment by carter2000** [comment]
CL https://golang.org/cl/15151 focus on Server.Close race. 

But the second example shows Listener.Accept succeed after Listener.Close, I'm not sure if it is right.

Listener.Close: https://github.com/golang/go/blob/go1.5.1/src/net/http/httptest/server.go#L167
Listener.Accept: https://github.com/golang/go/blob/go1.5.1/src/net/http/httptest/server.go#L48

example code: https://play.golang.org/p/FcpbVEf_HI (detect deadlock on play.golang.org, but hit "unexpected get succeed" on my server)

```
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
)

func main() {

	var i int
	for {
		i++
		fmt.Println(i)
		
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		}))
		
		ts.Close()
		
		resp, err := http.Get(ts.URL)
		if err == nil {
			resp.Body.Close()
			fmt.Println("unexpected get succeed")
			break
		}
	}
}
```

go version: go version go1.5.1 linux/amd64

**Comment by vbatts** [comment]
@carter2000 latest commit (a35d7b3b) on CL https://golang.org/cl/15151 fixes your examples for me.
