### ISSUE TITLE
doc: document release support policy

### ISSUE THREAD

**Issue by adg** [golang/go#12790]
We typically don't support releases earlier than the previous stable release (ie, 1.5 is current, we do support 1.4.x for security issues only). This isn't documented, though. We need to confirm this policy and document it.

cc @jbuberel @rsc

**Comment by bradfitz** [comment]
I really hope I don't have to cherry-pick Go 1.5 stuff back to Go 1.3. Doing the 1.4 cherry-picks was painful enough.

**Comment by adg** [comment]
No, 1.3 is not supported.

**Comment by jbuberel** [comment]
Let me know if you'd like me to submit a 'proposal' issue and start the process for a formal definition.

**Comment by adg** [comment]
It doesn't have to be a big deal; I think we should just decide here in
this thread.

**Comment by jbuberel** [comment]
Question: What does it mean to "support" a release?  

* Probably includes applying security patches to current and previous stable releases.
* Probably does not include applying performance, stability or feature patches to any release but the current stable release.

What else?

**Comment by adg** [comment]
Applying *critical* security patches and nothing else.

**Comment by jbuberel** [comment]
In Go project terminology a "major release" is Y.(X+1) and a minor release is Y.X.(Z+1), which is a bit unique. 

So I think our policy should be:

We will apply critical security patches to the current stable release and to the most recent minor release of the previous major release - Y.(X-1).Z.

**Comment by adg** [comment]
SGTM

**Comment by rsc** [comment]
@jbuberel your description is a bit complex.

In Go 1.X is a major release and 1.X.Y is a minor release.  There is no need to make "1" a variable.

We don't update minor releases. We update major releases. Each update is itself a minor release. 1.4.3 is the second update to 1.4, not an update to 1.4.2.

For critical security patches, we update the current and previous major releases. (That update takes the form of a minor release for both.)
