### ISSUE TITLE
tour: Excellent tour! Love it! But seriously, it looks crap.... get a true graphic designer to make it beautiful - which is important to draw in ppl other than nerds, such as myself, and I really almost quit because of how it looks!

### ISSUE THREAD

**Issue by marwik** [golang/go#12795]
Context: https://tour.golang.org/welcome/1

tour: Excellent tour! Love it! But seriously, it looks crap.... 

about the whole golang site:
Get a true graphic designer to make it beautiful - which is important to draw in ppl other than nerds, such as myself, and I really almost quit because of how it looks!

Thanks for your efforts and keep up the good work,

regards, Marwik

**Comment by ianlancetaylor** [comment]
Thanks.  I'm going to close this because there isn't really any action we can take.  If you have specific suggestions, happy to hear them.
