### ISSUE TITLE
x/mobile/cmd/gomobile: gobind plugin generate AndroidManifest.xml with minSdkVersion="\t"

### ISSUE THREAD

**Issue by Kuloud** [golang/go#12809]
Env
---
gomobile version +6072875 Wed Sep 30 20:56:48 2015 +0000 (android); 
android studio 1.4

Problem 
---
Gobind plugin generated aar library have minSdk "\t" from the generated manifest.xml resulting in manifest merger failed:

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be different than version \t declared in library E:\Dev\Go\src\golang.org\x\mobile\example\bind\android\app\build\intermediates\exploded-aar\android\hello\unspecified\AndroidManifest.xml

**Comment by Kuloud** [comment]
after pull the latest gomobile changes and rebuild, the problem still exist

**Comment by hyangah** [comment]
@Kuloud  What does 'gomobile version' say now? I sync'd today rev ca60936 and could build the example/bind/android app.

Does clean the build (android studio) help?
