### ISSUE TITLE
tour: basics/9 wrong package

### ISSUE THREAD

**Issue by cortinico** [golang/go#12807]
Context: https://tour.golang.org/basics/9

There is a wrong package in page basics/9.
```
1package main
```
Must remove the **1**

**Comment by rakyll** [comment]
Package name is already main in that sample. 

![go1](https://cloud.githubusercontent.com/assets/108380/10226493/c3fddd5e-6835-11e5-8b99-f294d7f996d2.png)

**Comment by cortinico** [comment]
My fault, I had a wrong local version.
Thanks anyway :)
