### ISSUE TITLE
net: net.IPNet should implement encoding.TextMarshaler and TextUnmarshaler

### ISSUE THREAD

**Issue by gucki** [golang/go#12803]
package main

    import (
      "encoding/json"
      "fmt"
      "net"
    )

    var input = `
    {
      "network": "127.0.0.1/24"
    }
    `

    type A struct {
      Network net.IPNet `json:"network"`
    }

    func main() {
      var val A

      if err := json.Unmarshal([]byte(input), &val); err != nil {
        panic(err)
      }

      fmt.Println(val)
    }

Fails with "panic: json: cannot unmarshal string into Go value of type net.IPNet".

go version go1.5.1 linux/amd64

**Comment by adg** [comment]
`net.IP` implements `encoding.TextUnmarshaler` and `encoding.TextMarshaler`, so `net.IPNet` could too.

`net.IPNet` is a combination of `net.IP` and `net.IPMask`. The latter does not implement the encoding interfaces, so maybe `IPMask` should be changed also.

**Comment by mattharden** [comment]
What should a `net.IPMask` look like as a JSON string? I see a few options.
* Match `IPMask.String` - always a hex representation of the mask
* Match `IPNet.String` after the slash (a decimal integer or hex representation depending on whether the mask is a valid CIDR or not)
* Match `IPNet.String`, *including* the slash and following characters (always start with a slash).

Then, independently of the above, should `net.IPNet` marshal/unmarshal a format matching `IPNet.String` (as @gucki requested), or just a JSON expansion of the `IPNet` struct, such as this:

```
{ "IP": "127.0.0.1", Mask: "8" }
```

**Comment by rsc** [comment]
Too late, I'm afraid. That would change the current encodings.

http://play.golang.org/p/DY7Juqs9vT

	package main
	
	import (
		"encoding/json"
		"fmt"
		"log"
		"net"
	)
	
	func main() {
		js, err := json.Marshal(net.IPNet{})
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(string(js))
	}

**Comment by gucki** [comment]
@rsc Sorry, I don't get why parsing "127.0.0.1/24" into a net.IPNET could not be implemented anyway?
