### ISSUE TITLE
net: hosts.go lookupStaticHost is case-sensitive 

### ISSUE THREAD

**Issue by corymintz** [golang/go#12806]
Go 1.5.1, Linux amd64.

Given: `net.LookupHost("Blah")`
The resolution will fail if the `/etc/hosts` file contains:
`127.0.0.1 blah`
and succeeds if it contains:
`127.0.0.1 Blah`

Hostnames are expected to be case-insensitive

**Comment by rakyll** [comment]
Name resolution via a hosts file was considered case sensitive in UNIX-like operating systems even though the standardization attempts of the hosts files (rfc952) suggests it must be case insensitive. I am not quite sure what the correct behavior we must bless but the host names in /etc/hosts are conventionally considered case sensitive.

**Comment by corymintz** [comment]
Are there any current examples on Linux where it would be case-sensitive? This was hit because of an upgrade from Go 1.4 to 1.5 (because of the default change from cgo to the go resolver on Linux).  If there is indeed conflicting info I think maintaining compatibly on upgrade to 1.5 should be the tie breaker.

**Comment by bradfitz** [comment]
libc treats /etc/hosts as case-insensitive, so so should we.
