### ISSUE TITLE
runtime: odd expression

### ISSUE THREAD

**Issue by hallas** [golang/go#12802]
I was looking through the source code, as I often do, and today I found this line which struck me as odd.

https://github.com/golang/go/blob/master/src/runtime/extern.go#L139

`1+skip-1`

Which seems redundant but maybe this is some kind of compiler trick?

**Comment by ianlancetaylor** [comment]
We use the issue tracker for bug reports.  Please ask questions on the golang-nuts mailing list or on forum.golangbridge.org.  Thanks.

**Comment by minux** [comment]
Regarding the original problem,
the full history is there, why not find out the answer
on your own?

Hint: see https://golang.org/cl/4810054.
