### ISSUE TITLE
x/mobile/cmd/gomobile: gomobile bind generates binding code on every execution

### ISSUE THREAD

**Issue by sridharv** [golang/go#12819]
This can't really be called a bug, but it is potentially sub-par behaviour. It is a follow on from a suggestion I made in https://github.com/golang/go/issues/12245.

`gomobile bind` currently generates binding code every time it is run. This has the following side effects:
- **Access to source for debugging:** When debugging application errors in the wild, it is useful to have the source available. In the case of native libraries, we can use vendoring or the native package manager for versioning. With `gobind` however, the source is not easily available. It can be generated by manually running `gobind`, but there are a few concerns with this approach.
  - _The options passed to `gobind` are opaque to the user:_ Currently there are no options, but if this changes in the future it becomes a guessing game.
  - _Upgrades of the `gobind` tool can result in source changes:_ For production releases we will need to track the exact version of `gomobile` used to generate the library. This is fine once `gobind` is stable (for example with cgo now). However, it is problematic for early adopters since changes are being made to `gobind` on a regular basis.
- **Incremental builds:** In an SDK app, `gomobile bind` must be run on source changes to regenerate the new framework/aar. There are two ways of approaching this. Manually run `gomobile bind` or have the IDE (XCode/Android Studio) invoke it before compiling the ObjC/Java source. The former, while not a chore, can be error prone. The latter is more robust, but results in the framework/aar being rebuilt even if no go source is changed. This adds delays to the code -> compile -> test cycle and negatively impacts our workflow. It also takes away one of the advantages of go which are its near instantaneous build times.

One solution would be for `gomobile bind` to accept a command line flag which specifies the directory in which to generate code and then skip regenerating code on every run.

This is more a nice to have rather than a need to have since there are workarounds present.

**Comment by jeffallen** [comment]
Yes please. My Android Studio build times went from 2 secs to 10 secs by adding a Go module to my project. For a language with a reputation for fast build times, it's beyond ironic and really unfortunate that Go is making *Java* builds slower!

**Comment by crawshaw** [comment]
Hana and I discussed this last week. We decided to experiment with putting the generated .java files into the .aar. Then ```gomobile bind``` can compare a hash of the newly generated .java against the old, and only touch the .aar if either the .java has changed, or the generated .so would have changed.

This avoids adding a flag for a working directory, which I consider important as keeping and reusing intermediate data introduces a new way you can get incorrect builds.

**Comment by sridharv** [comment]
Thank You! In addition, please keep in mind the fact that a large number (and most likely the majority) of mobile apps are closed source. Shipping production builds with source files might be problematic for many people. However, this can be worked-around by repackaging the final aars manually.

**Comment by eliasnaur** [comment]
gomobile bind also generates .so files for every architecture (currenty arm, x86 and x86_64 and possible arm64 in the future). Would it make sense to make an option to gomobile (and the gradle plugin) to limit the architectures, for example to arm, arm64? Alternatively, an environment option so the architecture set can be changed for debug and release. I rarely use the emulators anyway.

**Comment by hyangah** [comment]
Try --target=android/386 etc

The gradle plugin should be updated though.

On Mon, Mar 7, 2016 at 8:18 AM, eliasnaur <notifications@github.com> wrote:

> gomobile bind also generates .so files for every architecture (currenty
> arm, x86 and x86_64 and possible arm64 in the future). Would it make sense
> to make an option to gomobile (and the gradle plugin) to limit the
> architectures, for example to arm, arm64? Alternatively, an environment
> option so the architecture set can be changed for debug and release. I
> rarely use the emulators anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/12819#issuecomment-193244645>.
>



-- 
__

**Comment by eliasnaur** [comment]
Of course, thanks. I'll look into updating the gradle plugin if noone beats
me to it.

**Comment by eliasnaur** [comment]
I believe this is fixed by https://go-review.googlesource.com/99316. You can now use the `gobind` tool to generate a complete set of bindings. The `gomobile` tool calls `gobind` so you're guaranteed that the output from gobind is what gomobile uses.
