### ISSUE TITLE
net: InterfaceAddrs, Interface.{Addrs,MulticastAddrs} can return addresses on administratively or operational down interface

### ISSUE THREAD

**Issue by akevinbailey** [golang/go#12812]
I found another issue in interface_windows.go:  The <code>interfaceAddrTable</code> returns Interfaces that are not active.  Need to implement the follow code after <code>for ; paddr != nil; paddr = paddr.Next { ...</code> (line 156): 

<code>if paddr.OperStatus == windows.IfOperStatusUp {
 ... 
}</code>

This will exclude inactive interfaces.

**Comment by rsc** [comment]
If the interface is up but it has an address, is it incorrect to return that address? Serious question.

Most down interfaces have no addresses.

**Comment by akevinbailey** [comment]
On Windows, down interfaces do have addresses.  The *IPAdaperAddresses has a field called OperStatus.  On Windows the interface is only considered up if OperStatus=1.  If you don't put in this constrains you will get all the down or dormant connections like Wifi, VPN, and virtual host interfaces.  Ideally, it would be better to just provide the OperStatus in the return and let the caller decide.
-- Kevin

**Comment by rsc** [comment]
OK, I guess we need to decide what InterfaceAddrs does. Does it return only "up" interfaces? I guess it does on other systems? So then maybe it should on Windows too?

**Comment by mikioh** [comment]
This is not a Windows-specific inconsistency. IIRC, there are two types of implementation on routing information. One is that simply adds and drops connected routes (and interface addresses) on link-layer events such as physical-port/{physical/logical}-link/logical-interface arrivals and departures. The other is that just keeps interface addresses and notifies each status of addresses. The former example would be BSD variants and the latter example would be Linux (and Windows probably.)

**Comment by rsc** [comment]
So: should we return addresses for down interfaces or not? @mikioh, what do you think?

**Comment by mikioh** [comment]
I think it's fine as it is. The document on InterfaceAddrs now suggests using Interfaces and Interface.Addrs instead, and each Interface tells us its operational status. Applications have a choice dealing with the returned interface addresses; for example, a customer traffic transport application ignores addresses belongs to operational down interfaces, an infrastructure control/management application treats them as a part of configuration.

**Comment by rsc** [comment]
OK, working as intended.
