### ISSUE TITLE
Static analysis fail for 1.5.1?

### ISSUE THREAD

**Issue by badoet** [golang/go#12827]
```
	var qty int = 0
	for _, item := range list {
		qty, ok := qtyMap[item.sku] // if qty is 5 here
		if ok {
                      // qty will be 5 here
			qty += 1
		} else {
			qty = 1
		}
                // qty is 0 here
       }
```
my hunch is that the static analysis on compile time fail?
to solve this , i just need to remove the `var qty int = 0` at the top.
or is there something that i dont understand?

**Comment by cznic** [comment]
Cannot reproduce with eg. http://play.golang.org/p/4K88D2Ns_e

Please provide a complete compilable reproduction case.

**Comment by bradfitz** [comment]
I also don't see the bug here. And not sure what it has to do with static analysis.

Please open a new bug if you have a complete standalone example of a compilation failure. Or if you just have questions about the language, see https://golang.org/wiki/Questions

**Comment by badoet** [comment]
sorry i was attaching the wrong code for the first one. 
http://play.golang.org/p/vKv9BCKyUm
see the playground above.

**Comment by bradfitz** [comment]
You're shadowing qty on line 9 with a different variable (also called qty). This is working as designed. See https://golang.org/ref/spec#Declarations_and_scope or ask questions about the language at https://golang.org/wiki/Questions
