### ISSUE TITLE
x/mobile/app: basic app doesn't exit when window is closed

### ISSUE THREAD

**Issue by cortex** [golang/go#12828]
I tried running the basic example with:
go install golang.org/x/mobile/example/basic && basic 
When clicking the close-window button, the application does not exit. It does stop repainting however, and appears hung. I tried inserting some log lines for lifetime events, but there doesn't seem to be any event sent when the window is closed, but the paint.Event stops.

This is on Arch Linux running Gnome 3.16.

**Comment by jhsx** [comment]
This is happening on Mac OS X also.

**Comment by db47h** [comment]
On X11, closing the window triggers `onStop()` which sends a lifecycle event then a `stopPumping{}` event. 

In the `app.pump()` loop, he lifecycle event gets in the event buffer, then on the next iteration `stopPumping{}` is received, discarding the input event channel, and the libecycle event has not been sent out yet and remains in the buffer. What happens next is that the application's main loop sits in `a.Send(paine.Event{})`, trying to send to the input event channel, which the `pump()` loop does not read anymore.

A possible fix could be to actually close `eventsIn` upon receiving `stopPumping{}`, and perform all internal event sending via `app.Send()` with modifications to discard events should the channel be closed.

**Comment by db47h** [comment]
I have a much simpler working fix that uses a boolean `done` flag in `pump()` that is set to true when a `stopPumping{}` is received. If `done` is true, incoming events are just ignored, thus keeping both input and output event channels alive. Should I submit a CL with this?

**Comment by crawshaw** [comment]
@db47h: I'd like to see if we could sort this out in the shiny version of closing the events channel first, and then copy that code into x/mobile.

**Comment by changkun** [comment]
Apps can exist properly today, except windows (see #49499). Close.
