### ISSUE TITLE
golang/tools/cmd/vet vs golang/go/tree/master/src/cmd/vet, what is the correct one to use?

### ISSUE THREAD

**Issue by ingvagabund** [golang/go#12820]
Hi Brad,

commit 7454f53604b9953b5b7a3897c6b855957f911e66 in its message says:
No more changes to golang.org/x/tools please. This should not have
happened (and letting it happen was partly my fault).

What does it mean? github.com/golang/tools is becoming read only? Or is just no more updates to golang.org/x/tools packages which is, well, exactly the same.

Just wondering, which repository for vet tool is recommend/correct to use?

Jan

**Comment by ingvagabund** [comment]
@bradfitz

**Comment by bradfitz** [comment]
This isn't a bug report, so I'm closing it. (Unlike some Github projects, we don't use our bug tracker for Q&A)

Please bring questions to the golang-nuts@ mailing list or the Go forum: https://forum.golangbridge.org/

**Comment by minux** [comment]
The message means that new changes to cmd/vet should be made to the one in
master go repository. It doesn't mean the whole x/tools repository will be
readonly.
