### ISSUE TITLE
file path as doc index

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#12837]
https://golang.org/pkg/net/http/ why is `func CanonicalHeaderKey(s string) string` not indexed under `type Header`?

Is it possible to create a index based on file path, for example `/src/net/http/header.go`?

Also the same indentation of type functions `func (r *Request) AddCookie(c *Cookie)` and normal functions `func NewRequest(method, urlStr string, body io.Reader) (*Request, error)` under `type Request` confuses new comers that don't recognize the signature `func (r *Request)`.

**Comment by minux** [comment]
for the first question,
godoc has no way to know that "func CanonicalHeaderKey(s string) string"
has anything to do with type Header.

2nd question, there is no way to do that. And I think the godoc heuristic
is much better than just grouping by source files.

3rd question, the way godoc organizes functions/methods under a
particular type is based on the following heuristic:
1. the method on that type
2. any func that returns that type
are related to the type, so they should be grouped with the type.

Please see https://golang.org/wiki/Questions how to ask questions.
The issue tracker is intended for bug reports and proposals.

**Comment by gertcuykens** [comment]
Proposal was, build a better index system using file paths :) but i understand if using path file is a bad idea. But still the current solution is not perfect, hope you agree.

**Comment by minux** [comment]
How to handle packages that put everything into the same
Go source file?

What if a type has so many methods that the developer
split the methods into multiple files?

In Go, files don't play as much a role as in other compiled
languages, and the developer can split the package into
files arbitrarily so I don't think using file path as index is a
good idea for Go.

**Comment by gertcuykens** [comment]
I agree, what about the idea to not indent the normal functions `func NewRequest(method, urlStr string, body io.Reader) (*Request, error)` and put them above the type

So the index looks like this

```
func NewRequest(method, urlStr string, body io.Reader) (*Request, error)
func ReadRequest(b *bufio.Reader) (req *Request, err error)
type Request
    func (r *Request) AddCookie(c *Cookie)
    func (r *Request) BasicAuth() (username, password string, ok bool)
    ...
```
