### ISSUE TITLE
encoding/xml: typo in docs

### ISSUE THREAD

**Issue by ShawnMilo** [golang/go#12833]
The documentation of `func Unmarshal` states:

>Unmarshal uses a case-sensitive comparison to match XML element names to tag values and struct field names.

Unless I'm really confused about something, that should be "case-insensitive" instead. At least, that's my experience with using `encoding/xml` and `encoding/json`.

**Comment by rakyll** [comment]
The documentation is accurate. The field won't match if the XML element's case doesn't match. See http://play.golang.org/p/9oZIgl9n3X where Name is an empty string after unmarshalling.
