### ISSUE TITLE
os/exec: docs bugs sections points to closed issue

### ISSUE THREAD

**Issue by andrewchambers** [golang/go#12838]
https://golang.org/pkg/os/exec/#pkg-note-BUG points to a closed issue. Should this be addressed?

**Comment by minux** [comment]
I think that's ok.

The bug still exists on 10.6, technically. The issue is closed because we
are not going to fix it as we don't support 10.6 anymore.

I added the unfortunate label to #2603 to signal that it has not been fixed
but we don't care anymore.

**Comment by rakyll** [comment]
Bug is listed as a note, not for the purpose of getting it addressed.
