### ISSUE TITLE
cmd/link: race detector: doesn't work on OS X with CGO_ENABLED=0

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#12844]
Following up on https://groups.google.com/forum/#!topic/golang-nuts/7ZKusMdkNz4.

What version of Go are you using (go version)?
go 1.5.1

What operating system and processor architecture are you using?
OS X 10.10.5

What did you do?
Run `go run -race main.go` on any valid go file.

What did you expect to see?
A running go binary with the race detector enabled.

What did you see instead?
The following error log:
```
go version go1.5.1 darwin/amd64
# command-line-arguments
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): free: not defined
runtime/race(__TEXT/__text): free: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): memcpy: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): memcpy: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): memcpy: not defined
runtime/race(__TEXT/__text): malloc: not defined
runtime/race(__TEXT/__text): setrlimit: not defined
runtime/race(__TEXT/__text): getpid: not defined
runtime/race(__TEXT/__text): getpid: not defined
runtime/race(__TEXT/__text): getpid: not defined
runtime/race(__TEXT/__text): __error: not defined
runtime/race(__TEXT/__text): exit: not defined
runtime/race(__TEXT/__text): usleep: not defined
runtime/race(__TEXT/__text): sched_yield: not defined
/go/go1.5/pkg/tool/darwin_amd64/link: too many errors
```

@ianlancetaylor suggested that I open this issue with the request that either the race detector works with CGO_ENABLED=0, or that it prints a meaningful error message explaining that CGO_ENABLED=1 is required.

**Comment by minux** [comment]
The race detector basically can't work with cgo disabled.

**Comment by ianlancetaylor** [comment]
@minux That is entirely understandable, but we need a better error message.

**Comment by Thomasdezeeuw** [comment]
Thank for the quick fix.
