### ISSUE TITLE
cmd/link: fail when -buildmode requires external linking but -linkmode=internal is passed

### ISSUE THREAD

**Issue by mwhudson** [golang/go#12848]
Currently if you pass a buildmode that requires external linking (e.g. shared) but explicitly request internal linking, -linkdmode=internal is ignored. It should probably error instead.

**Comment by rsc** [comment]
OK

**Comment by rsc** [comment]
@mwhudson, if you want to do this, sounds good to me. I just looked and I can't see where linkmode=internal is ignored.
