### ISSUE TITLE
Error in Note

### ISSUE THREAD

**Issue by llamalloyd** [golang/go#12847]
Context: https://tour.golang.org/methods/9

Under the Note, should be fmt.Sprintf instead of fmt.Sprint

**Comment by cespare** [comment]
Why?

**Comment by rakyll** [comment]
Sprintf requires a format string, there is no format string used in the call.

**Comment by llamalloyd** [comment]
Apologies, I thought fmt.Sprint was a typo as fmt.Sprintf was used is previous sections of the tutorial.

	Dean
