### ISSUE TITLE
net/http: Malformed HTTP status code

### ISSUE THREAD

**Issue by c4milo** [golang/go#12856]
![](https://cldup.com/-3c65YUATC.png)

Test code to reproduce the issue can be found at https://github.com/c4milo/gofetch. This one only happens consistently in Go 1.4.x. I couldn't reproduce it in Go 1.5.1

**Comment by adg** [comment]
Have you tested it against Go 1.4.3?

**Comment by c4milo** [comment]
Yes, same result.

**Comment by c4milo** [comment]
I just saw it happening in Go 1.5.1. But, I can't reproduce reliably.

**Comment by bradfitz** [comment]
That code has many missed error checks.  You're also copying the value of mutexes.

This has enough red flags that this is user error that I'm going to close this report for now. If you have something with complete error checks, no races, and ideally self-containing and easy for me to run and reproduce I can look into it more.
