### ISSUE TITLE
x/mobile/bind: static variables in iOS/Swift aren't reference counted correctly

### ISSUE THREAD

**Issue by scisci** [golang/go#12859]
When I declare a variable statically like this:
```
class SwiftClass {
  // Shared static instance singleton
  static let sharedInstance = SwiftClass();

  // Member variable that is a go struct pointer
  var someGoStruct: GoStruct?

  init() {
    // Create go struct
    someGoStruct = NewGoStruct()
  }

  func doSomething() {
    someGoStruct.SomeMethod();
  }
}
```

I can call SwiftClass.sharedInstance.doSomething();
It works the first time, but if I call it at some later time, it crashes in the reference counting area of the go library. I think this must be because go doesn't understand that the member of the static variable shouldn't be garbage collected. I was able to get around the issue by not declaring my singleton as static, and instead just declaring it as a global variable.

**Comment by ianlancetaylor** [comment]
CC @crawshaw @hyangah

**Comment by hyangah** [comment]
@scisci thanks for the report.
Do you mind sharing a minimal example project to reproduce the problem?
Also the crash log will be helpful.

I tried to reproduce it based on the code snippet you included, but couldn't reproduce the crash.

**Comment by scisci** [comment]
Yep, will do. The bug showed up in a larger project, and the example above I just wrote in here to demonstrate, so it may very well need some better modelling. I will have to break it out which might take a minute. I'll let you know.

**Comment by scisci** [comment]
Hi @hyangah, here is a test project that demonstrates the error:

https://github.com/scisci/gomobile-static-test

/lib holds the golang library (please note I've converted it to a Module so it can be imported by swift after the build process, so you have to do that manually if you want to rebuild it)
/gomobile-static-test holds an xcode project with a view with a single button. If you click the button twice it crashes on a reference count error.

**Comment by hyangah** [comment]
Thanks @scisci. 

The xcode project complains it couldn't find the module Lib (yeah, I see the xcodeproj has a link to your directory :-) I just rebuilt the framework using the build-lib.sh there. FYI, the current version of gomobile bind produces the module map, so you don't have to manually tweak the framework for use in swift any more.

And with iPhone6 simulator (iOS8.4), I couldn't reproduce the crash. From your crash log, I guess you also tried with a simulator. I am puzzled.

Which version of go, and gomobile did you use? Does the problem still exist when you try with the tip?

**Comment by scisci** [comment]
Thanks @hyangah, my gomobile version is +9e2ad8c, I will try to update and see if it changes. Just a question, did you hit the button twice in your tests? It is required to produce the crash.

**Comment by scisci** [comment]
hey @hyangah, indeed updating to the latest version of gomobile has solved the issue. thanks!
