### ISSUE TITLE
syscall: don't check result of close(fd) in forkAndExecInChild on Plan9

### ISSUE THREAD

**Issue by joushou** [golang/go#12851]
On almost every build of Go I have made so far, "Building packages and commands" have failed with either:

    go build ...: ...: fork/exec .../pkg/tool/plan9_amd64/compile: fd out of range or not open
or:

    go build ...: ...: fork/exec .../pkg/tool/plan9_amd64/asm: fd out of range or not open

Completing a build tends to take quite a few tries.

I have traced the error to forkAndExecInChild (https://github.com/golang/go/blob/f9ed2f75c43cb8745a1593ec3e4208c46419216a/src/syscall/exec_plan9.go#L219):
```go
	// Close fds we don't need.
	for i = 0; i < len(fdsToClose); i++ {
		r1, _, _ = RawSyscall(SYS_CLOSE, uintptr(fdsToClose[i]), 0, 0)
		if int32(r1) == -1 {
			goto childerror
		}
	}
```

This is in the child right after the fork succeeded.

I haven't figured out why this occurs yet. fd closed, fd never valid in the first place, ... The fd and index in "fdsToClose" changes, so it's not just the first fd (and maybe all of them), nor it is always the same fd. I do not yet know if the fds are open and valid prior to forking.

#### OS and Go versions
OS: plan9 (up-to-date 9front amd64)
Go: head of master
Go bootstrap: 1.4.3

#### Steps to reproduce
* Install a version of Go for bootstrapping (pre master)
* Fetch master
* GOROOT_BOOTSTRAP=/the/other/go ./make.rc

#### Expected result
Go build completes and gives me a freshly baked toolchain.

#### Actual result
Build crashes the vast majority of the time. Completing a build takes many attempts with --no-clean.

**Comment by joushou** [comment]
Plan9 appears to have a close-on-exec flag (OEXEC, http://man.cat-v.org/plan_9/2/open), making the  fdsToClose construct unecessary.

**Comment by 0intro** [comment]
This bug only appears on multiprocessor machines. This is a long-standing issue.
It seems there is a race condition that leads some file descriptors to be closed twice.

A simple workaround is to ignore the error returned by the close syscall.
This should be safe since we just want to be sure the fd was closed.

But, of course, it would be better to fix the race.

**Comment by rsc** [comment]
None of the other systems check the result from close. Neither should Plan 9.
