### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "\xd7"; err=<nil>

### ISSUE THREAD

**Issue by c4milo** [golang/go#12855]
I'm running into this issue consistently. You can reproduce it by running the tests of this project: https://github.com/c4milo/gofetch, specifically: TestFetchWithoutContentLength

**Comment by minux** [comment]
Could you please provide a standalone test that
only uses net/http to reproduce the issue?

**Comment by bradfitz** [comment]
I'm going to close this one for the same reason I closed #12856.  For now. Please re-open or ping if you have a standalone race-free version with full error checks.

**Comment by c4milo** [comment]
I found the culprit, in the HTTP test server, I was always sending a response body no matter the method, and in the actual module, I'm doing a HEAD request before attempting a GET request. It is clearly a user error as @bradfitz pointed out. However, I must say I was completely clueless with those cryptic error messages.
