### ISSUE TITLE
math: Modf error with negative zero

### ISSUE THREAD

**Issue by ssilverman** [golang/go#12867]
Since math.Modf(-0.333) produces -0 and -0.333, shouldn't calling math.Modf on negative zero produce -0 and -0?

Example code:
http://play.golang.org/p/pJMBWAXiYa

I create negative zero via: 1 / math.Inf(-1)

**Comment by griesemer** [comment]
I think it's a bug. The result is 0, -0 which doesn't add up to -0 as it should.

(FYI, you can create a -0 more easily: http://play.golang.org/p/KTgiTOAZl0)

**Comment by cldorian** [comment]
@griesemer, I can fix this if you wish. The remaining problem I have is that the x87 version returns -0, 0 rather than -0, -0, so it will need to either be fixed or discarded.

**Comment by griesemer** [comment]
@cldorian please go ahead, thanks!
