### ISSUE TITLE
website: Go Download link is down

### ISSUE THREAD

**Issue by sandan** [golang/go#12875]
I'm trying to install Go from the link below:
https://golang.org/dl/

It redirects me here: 
https://storage.googleapis.com/golang/go1.5.1.darwin-amd64.pkg

This webpage is not available

ERR_QUIC_PROTOCOL_ERROR

The webpage at https://storage.googleapis.com/golang/go1.5.1.darwin-amd64.pkg might be temporarily down or it may have moved permanently to a new web address.

**Comment by adg** [comment]
It would be very surprising to me if storage.googleapis.com were malfunctioning. I suspect the issue is on your end.

Do you still see the issue? What browser and operating system are you using? It's surprising to see "QUIC" mentioned in the error message.

**Comment by rakyll** [comment]
Assuming you are a Chrome user, this sounds like a QUIC experiment. Go to chrome://flags/ and disable "Experimental QUIC protocol".

**Comment by sandan** [comment]
@adg I'm using and up to date version of chrome: Version 45.0.2454.101 (64-bit) on a Mac OS X Yosemite (1010.5). @rakyll I tried disabling the Experimental QUIC protocol and relaunched but it still doesn't work. It was set to "default" before I changed it.

**Comment by bradfitz** [comment]
Can you grab a network trace with https://dev.chromium.org/for-testers/providing-network-details ?

**Comment by sandan** [comment]
@bradfitz Tried it many time but saving the dump gives me an empty .json file. I tried re-installing chrome and everything works. Thanks anyway!
