### ISSUE TITLE
tour: Casting return value in first methods example is inconsistent

### ISSUE THREAD

**Issue by markcampanelli-wf** [golang/go#12874]
Context: https://tour.golang.org/methods/2

If one is going to declare one's own type that extends float64 (i.e., MyFloat) and define an absolute value method on it, then one might expect to return a value of the same extended type (i.e., MyFloat not float64). I would change the example as below:

package main

import (
	"fmt"
	"math"
)

type MyFloat float64

func (f MyFloat) Abs() MyFloat { \\ Note: return type is same type as "caller"
	if f < 0 {
		return -f \\ Note: no casting to float64
	}
	return f \\ Note: no casting to float64
}

func main() {
	f := MyFloat(-math.Sqrt2)
	fmt.Println(f.Abs())
}

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
If you read on, it becomes clear the reason that `Abs` returns a `float64` is so that other types can implement the method without referring to `MyFloat`.
