### ISSUE TITLE
About hot replacement of Channel

### ISSUE THREAD

**Issue by hyper-carrot** [golang/go#12877]
Please see: https://gist.github.com/hyper-carrot/85d082e83b35122ca53e .

I run `go run chan_hotrepl_go1.4.go` under go1.4, it (one goroutine) can receive the elements from the getChan()'s result after chan1 reset by another goroutine. The output like:

```bash
Begin to receive elements from chan1...
Send element 0...
Received an element: 0
Send element 1...
Received an element: 1
Send element 2...
Received an element: 2
Reset chan1...
Send element 3...
Received an element: 3
Send element 4...
Received an element: 4
Send element 5...
Received an element: 5
Reset chan1...
Send element 6...
Received an element: 6
```

But, It is not the case in go1.5. In go1.5, the goroutine can not receive the element after chan1 reset. The output like:

```bash
Begin to receive elements from chan1...
Send element 0...
Received an element: 0
Send element 1...
Received an element: 1
Send element 2...
Received an element: 2
Reset chan1...
Send element 3...
Send element 4...
Send element 5...
Reset chan1...
Send element 6...
Send element 7...
Send element 8...
```

I put the reset operation into a independent goroutine, like chan_hotrepl_go1.5.go. Its behavior is normal both in go1.4 and go1.5.
I want to know the cause of these appearances. Is this relevant to the compiler optimizations in the different Golang versions?

**Comment by hyper-carrot** [comment]
All, I know that it will certainly has the problem of race condition. But, I think that it has nothing to do with race condition, or rather, it's not just about race condition.

**Comment by rjeczalik** [comment]
@hyper-carrot: It's too race to have it working like that. You could try rewriting it a bit instead: https://play.golang.org/p/MLrcTEkcHx (it's timing out on playground due to GOMAXPROCS=1, you may want to try it out locally).

**Comment by hyper-carrot** [comment]
@rjeczalik it's `Forbidden`.

**Comment by rjeczalik** [comment]
@hyper-carrot 

```
package main

import (
	"fmt"
	"time"
)

func consumer(newC chan chan int) {
	var jobs chan int
	for {
		select {
		case c, ok := <-newC:
			if !ok {
				return
			}
			jobs = c
			fmt.Println("new job pipeline")
		case job := <-jobs:
			fmt.Println("executing job:", job)
		}
	}
}

func producer(newC chan chan int) {
	var i int
	var c chan int
	for {
		if i%3 == 0 {
			c = make(chan int)
			newC <- c
		}
		c <- i
		i = (i + 1) % 3
	}
}

func main() {
	newC := make(chan chan int)
	go producer(newC)
	go consumer(newC)
	time.Sleep(5 * time.Second)
}
```

**Comment by RLH** [comment]
The default GOMAXPROCS changed between 1.4 when it was 1 and 1.5 which is
now NumCPU.

Races make the program undefined so should be avoided.

**Comment by hyper-carrot** [comment]
@RLH Thank you, but I known the different of GOMAXPROCS between go1.4 and go1.5. I had invoked runtime.GOMAXPROCS() at the beginning, but it didn't resolve the problem. I known the problem about race condition. In fact, I mean: Why are they (go1.4 and go1.5)  so different in this case?

**Comment by hyper-carrot** [comment]
@rjeczalik Thanks, 'chan chan' is a great solution, but it isn't the answer I want. The topic in golang-nuts: https://groups.google.com/forum/m/#!topic/golang-nuts/ucv_stf8uNY

**Comment by minux** [comment]
The behavior of racy programs is undefined, so there could
be arbitrary changes in their behavior between Go releases
(they could even change between minor releases).

**Comment by hyper-carrot** [comment]
@minux Yes, I want to know the change. But I think it's not easy for exposition. So I closed current issue. It's better to read the runtime code of Golang.

**Comment by minux** [comment]
do I bisect and see when does the behavior change.

**Comment by hyper-carrot** [comment]
@minux :+1:
