### ISSUE TITLE
time.Parse broken on custom format

### ISSUE THREAD

**Issue by nickbauman** [golang/go#12870]
time.Parse() doesn't work correctly across timezones. I’ve tried this on OSX and Linux:

    const shortForm = "2006-Jan-02 15:04 MST"
    originalTime, err := time.Parse(shortForm, "2013-Nov-29 06:00 CST")
    // code that checks err...
    fmt.Println("originalTime", originalTime)
    fmt.Println("originalTime.Unix", originalTime.Unix())
    otherTime, err := time.Parse(shortForm, "2013-Nov-29 07:00 EST")
    // code that checks err...
    fmt.Println("otherTime", otherTime)
    fmt.Println("otherTime.Unix", otherTime.Unix())

When the system is in the CST timezone, I get the following:

originalTime 2013-11-29 06:00:00 -0600 CST
originalTime.Unix 1385726400
otherTime 2013-11-29 06:00:00 -0600 CST
otherTime.Unix 1385726400

Sanity, right? Except if the system timezone is something other than CST. Change it to EST:

originalTime 2013-11-29 06:00:00 +0000 CST
originalTime.Unix 1385704800
otherTime 2013-11-29 07:00:00 -0500 EST
otherTime.Unix 1385726400

Note there are no errors.

**Comment by nickbauman** [comment]
One thing to note: a workaround is to use RFC-3339 date formats exclusively (i.e. "2006-01-02T15:04:05Z07:00"). When restricting the format to this, the bug does not reveal itself and everything works as expected.

**Comment by cespare** [comment]
You don't have to use RFC3339; but I would recommend using numeric zones to avoid this situation. It's described in the docs:

> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use ParseInLocation.

**Comment by cespare** [comment]
(Dup of #11815, I think)

**Comment by ianlancetaylor** [comment]
I think so too.

**Comment by nickbauman** [comment]
I think it's a dup of #11815 as well. Thank you.

And I missed that in the doc too, however, the "If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset" does not seem to be a sane implementation of date parsing in any case.
