### ISSUE TITLE
cmd/compile: empty struct takes space

### ISSUE THREAD

**Issue by minux** [golang/go#12884]
Found while experimenting with https://golang.org/cl/15522.

Empty field (`_ struct{}`) takes space in Go 1.5, but not in Go 1.4
or any previous Go releases. See http://play.golang.org/p/OTr-GLz2UN.
```
$ go run OTr-GLz2UN.go # Go tip
16 24
16 16
12
$ go143 run OTr-GLz2UN.go
16 16
16 16
8
```
It's a compiler regression introduced by Go 1.5.

Tentatively labeled Go 1.5.2 as this can't be workaround.

**Comment by bradfitz** [comment]
Nice find!

**Comment by mdempsky** [comment]
In general, they do not take space.  E.g., this program prints 4:

    package main
    
    import (
    	"fmt"
    	"unsafe"
    )
    
    func main() {
    	fmt.Println(unsafe.Sizeof(struct {
    		_ struct{}
    		x int32
    	}{}))
    }

The change to pad out structs that have a final zero-size field was to fix issue #9401.  I think this is working as intended.

**Comment by bradfitz** [comment]
So we should change

```go
type ProgInfo struct {
        Flags    uint32   // flag bits                                                                             
        Reguse   uint64   // registers implicitly used by this instruction                                         
        Regset   uint64   // registers implicitly set by this instruction                                          
        Regindex uint64   // registers used by addressing mode                                                     
        _        struct{} // to prevent unkeyed literals                                                           
}
```

to

```go
type ProgInfo struct {
        _        struct{} // to prevent unkeyed literals                                                           
        Flags    uint32   // flag bits                                                                             
        Reguse   uint64   // registers implicitly used by this instruction                                         
        Regset   uint64   // registers implicitly set by this instruction                                          
        Regindex uint64   // registers used by addressing mode                                                     
}
```
... I guess?

**Comment by mdempsky** [comment]
That should work to avoid the padding.

**Comment by minux** [comment]
ahh, I forgot about that trailing zero-sized field issue entirely.
thanks for pointing it out.

precise GC and zero-sized fields are subtle.

**Comment by davecheney** [comment]
Moving the _ field to the top of the struct SGTM.

**Comment by davecheney** [comment]
Perhaps instead of moving the _ field, augmenting the comment to mention
that zero sized fields consume 1 byte of  space, however that allocation is
subsumed into the padding for the int32.

However on 32 bit platforms, leaving the zero sized field at the end will
cause it to consume 4 bytes, so maybe it does need to move to the top of
the struct.

**Comment by mdempsky** [comment]
It won't take any space at the start of the struct.

**Comment by mdempsky** [comment]
In case anyone's interested in investigating more structs that might benefit from reordering their fields, I put together github.com/mdempsky/maligned as a quick program to calculate struct sizes using cmd/compile's field layout rules, and compare against what they would be if the fields were sorted.

Example:

    $ maligned cmd/internal/obj
    /usr/local/google/home/mdempsky/wd/go/src/cmd/internal/obj/link.go:249:15: struct of size 40 could be 32
    /usr/local/google/home/mdempsky/wd/go/src/cmd/internal/obj/link.go:476:11: struct of size 584 could be 568

**Comment by davecheney** [comment]
@minux  @mdempsky 

> ahh, I forgot about that trailing zero-sized field issue entirely.
> thanks for pointing it out.

How can one take the address of an unnamed field in a struct, zero sized or not ? In #9401 the type in question was
```
type T struct {
    A int
    Y struct{}
}
```
But in the example above the field is unnamed and inaccessible.

**Comment by mdempsky** [comment]
It's possible at least via package reflect: http://play.golang.org/p/esuSUoKomT

**Comment by davecheney** [comment]
@mdempsky, yes of course, thank you for explaining to me.

**Comment by josharian** [comment]
See also: https://go-review.googlesource.com/#/c/2179/
