### ISSUE TITLE
tour: "Must use make, not new" is confusing.

### ISSUE THREAD

**Issue by btelles** [golang/go#12891]
Context: http://tour.golang.org/moretypes/15

At this point in the tour, you haven't introduced "new" yet, and you're saying we should use "make" instead of "new." This is confusing.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
The tour used to talk about `new`, but it was removed a while back. I suggest we just take out the bit about `new` here.

I can take this one.
