### ISSUE TITLE
Inconsistent behavior between fmt and if clause

### ISSUE THREAD

**Issue by v2ray** [golang/go#12897]
The following issue is reproducible on both Mac OS X (amd64, go 1.5.1) and play.golang.org.

Code: http://play.golang.org/p/P53HkYdxyU

In the code above, nil value of *B is casted to interface IB. fmt correctly recognize the instance of IB is nil, but if clause fails to detect it, causing unnecessary confusing.

**Comment by minux** [comment]
Please read https://golang.org/doc/faq#nil_error

The B method on type A will always return
non-nil interface because it returns a *B.

This is working as intended, even though it might
be confusing.
