### ISSUE TITLE
x/net/http2/h2demo: allow binding on different ports/addresses

### ISSUE THREAD

**Issue by raboof** [golang/go#12905]
The pages served by the h2demo server contains links for switching (among other things) jumping from the HTTP/1 version of the site to the HTTP/2 version of the site.

If you want to expose the demo server on, say 'https://pi.bzzt.net:4430' instead of on 'localhost', you can specify this with the '-addr' command-line option. However, this parameter is not only used for generating the links in the HTML, it is also used to determine on which IP address to bind.

When the IP address the rendered hostname resolves to is not known as a local address on the machine on which h2demo is started (for example because there is a reverse proxy in front of it), h2demo will fail to bind (and thus fail to start).

One possible way to allow the above scenario is to allow separately setting the address on which the demo server is visible from the 'outside' and the address on which to bind.

Code at https://go-review.googlesource.com/#/c/15090/

**Comment by bradfitz** [comment]
How about you just add new optional flags for setting the visible hostnames.

If people don't set it, no change in behavior.

```go
var (
     publicHTTPAddr = flag.String("public_http_host", "", "If non-empty, the host or host:port to use when generating self-links to http address. The default is to use XXXX.")
     publicHTTPSAddr = flag.String("public_https_host", "", ....)
)
```

Does that work?

**Comment by raboof** [comment]
That could work. Personally I think having 'addr' and 'bindaddr' is less confusing than having 'addr' and 'public_http_host', but I might be biased ;).

If we do it like this:
* I'd propose changing the default 'addr' (bind address) to 0.0.0.0 instead of 127.0.0.1. Otherwise, someone who wants to deploy outside of localhost would always have to set *both* 'addr' *and* 'public_http_host'.
* users who previously used '-addr' will now have to change that to '-public_http_host'.

Note that my approach was almost entirely backwards-compatible: it added 2 optional configuration options (bindaddr and httpbindaddr), and not setting them would lead to no change in behaviour (except from listening on 0.0.0.0 instead of 127.0.0.1 by default, which is an improvement imho :) )

**Comment by raboof** [comment]
I'm happy to either improve the docs on the current patch or change it to use the 2 options you propose - your call :).

**Comment by bradfitz** [comment]
I've sent https://go-review.googlesource.com/15826

**Comment by raboof** [comment]
Looks good! Thanks for taking the time to look into this!
