### ISSUE TITLE
x/crypto/ssh: login with incorrect credentials

### ISSUE THREAD

**Issue by tobor** [golang/go#12901]
func LinkSSH(host, user, pass string) (info string) {

	config := &ssh.ClientConfig{
		User: user,
		Auth: []ssh.AuthMethod{
			ssh.Password(pass),
		},
	}
	client, err := ssh.Dial("tcp", host, config)
	if err != nil {
                info = "connect error"
		return info
	} else {
		session, err := client.NewSession()
		defer session.Close()

		if err != nil {
                        info = "login error"
			return info
		} else {
			info = "login ok"
			client.Close()
			return info

		}
	}
}

if ssh-server is Dropbear user and pass error return login ok

**Comment by davecheney** [comment]
Are you saying that against a dropbear server, providing incorrect
credentials allows you to login to the server anyway?

**Comment by minux** [comment]
can't reproduce. I've tested SSH-2.0-dropbear_2015.67 in OpenWRT.

Note that if the ssh client is unable to authenticate, the Dial call will
fail.

Please provide more information on how to reproduce.

**Comment by rakyll** [comment]
Not able to reproduce either, please open with more details if it is still the case.

**Comment by tobor** [comment]
Are you saying that against a dropbear server, providing incorrect
credentials allows you to login to the server anyway?

Provided the wrong username and password procedure returns successfully, it should return failure

**Comment by davecheney** [comment]
> Provided the wrong username and password procedure returns successfully, it should return failure

Can you replicate this behaviour with another ssh client (you may have to mess with the order and types of authentication attempted).

In this case the ssh package is acting as a client to the dropbear server, so 

a. this isn't the fault of the client
b. you may have discovered a lucrative bug in dropbear.

**Comment by tobor** [comment]
thank you all，I tested xshell and putty return success, but will be asked to re-enter the password，this isn't the fault of the client

**Comment by rakyll** [comment]
> Are you saying that against a dropbear server, providing incorrect
> credentials allows you to login to the server anyway?

Sorry for not providing little context in my previous comment. It is not reproducible against other servers. I wanted to say the issue is probably dropbear, not the ssh client.

**Comment by davecheney** [comment]
Thank you for confirming, I agree with your assessment.
