### ISSUE TITLE
regexp: [[:xdigit:]] matches some float strings

### ISSUE THREAD

**Issue by dwlnetnl** [golang/go#12900]
The documentation in ```regexp/syntax``` says that ```[[:xdigit:]]``` equals to ```[0-9A-Fa-f]```. But when I execute the code below some non hexadecimal strings are matched.

```go
package main

import (
	"fmt"
	"regexp"
)

func main() {
	re := regexp.MustCompile(`([[:xdigit:]]+),([[:xdigit:]]+)`)
	
	fmt.Println(re.MatchString("0.0,0.0"))   // true
	fmt.Println(re.MatchString("-0.0,0.0"))  // true
	fmt.Println(re.MatchString("0.0,-0.0"))  // false
	fmt.Println(re.MatchString("-0.0,-0.0")) // false
}
```
Playground: http://play.golang.org/p/G5NpPo3gtu

**Comment by bradfitz** [comment]
Yes, it's matching "0,0" in the middle.

Working as intended.

Use ^ and $ around you query if you want to match the full thing. http://play.golang.org/p/xuW71N04-x

**Comment by dwlnetnl** [comment]
Thanks for the quick reply!
