### ISSUE TITLE
cmd/go: PowerShell: Flag silently removes file ending when not between parentheses

### ISSUE THREAD

**Issue by RitchieFlick** [golang/go#12909]
> go version go1.5.1 windows/amd64

This occurred on Windows 8.1 - Powershell, not sure if the problem also exists on Unix systems.

If you pass command line flags to your go executable which contains a file name, without putting it between parentheses, go silently drops the file ending.

*Example*:

> .\myprog.exe -publicKey=test-key.pub

In the program, the variable was set to *test-key* and not *test-key.pub*.

Go should at least fail and not silently drop the file extension.

(Tried hours finding a bug in my code which alas wasn't there)

Edit 1:

There was a file *test-key* in the directory, so that's why my program didn't fail itself.

Edit 2:

As it seems to be a **PowerShell** specific problem, here the version I'm running:

Major  Minor  Build  Revision
4      0      -1     -1

**Comment by cznic** [comment]
Can you reproduce the behavior without Powershell involved? Ie. in the plain terminal (I think that's `cmd.exe`.)

**Comment by RitchieFlick** [comment]
I indeed can't reproduce this error with *cmd.exe* so it seems it's a PowerShell specific problem.

**Comment by cznic** [comment]
> I indeed can't reproduce this error with cmd.exe so it seems it's a PowerShell specific problem.

I'm afraid it's a problem that probably cannot be solved on the Go project side.

**Comment by ianlancetaylor** [comment]
It sounds like there is nothing for the Go project to do, so closing.  If you disagree, please reopen and explain what we should do.  Thanks.
