### ISSUE TITLE
cmd/go: GOBIN requires an absolute path but isn't documented to.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#12907]
I'm using `go version go1.5.1 darwin/amd64`.

I've tried:

```bash
$ GOBIN=. go install
$ echo $?
0
$ ./foo
-bash: ./foo: No such file or directory
```

And the process exited with status 0 (success), but there was nothing written to current folder.

When I used an absolute path for GOBIN, it worked as expected:

```bash
$ GOBIN=`pwd` go install
$ echo $?
0
$ ./foo
```

From https://tip.golang.org/cmd/go/:

> If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin.

> GOBIN - The directory where 'go install' will install a command.

As far as I can tell, nothing in documentation mentions it must be an absolute path. Yet it doesn't work when the path is relative.

**Comment by adg** [comment]
It should be documented and the go command should issue an error when it is set to a relative path.

**Comment by shurcooL** [comment]
That sounds like a reasonable way to resolve this issue.

**Comment by shurcooL** [comment]
Thank you for fixing this!
