### ISSUE TITLE
reflect.DeepEqual returns false for equal slices.

### ISSUE THREAD

**Issue by zyzniewski-filip** [golang/go#12918]
See here: http://play.golang.org/p/QOm2jP6oMs

a1 and b1 have different underlying byte values, but as slices they seem to be equal (there is no difference except for the implementation detail of different initialization).

**Comment by ttacon** [comment]
Semantically, I think your example is working as desired. In the first case, slices a1 and b1 are "not" equal - you're comparing nil with a []string of zero length.

**Comment by zyzniewski-filip** [comment]
This smells funny - I could clearly agree for maps, as a nil map behaves differently to an empty map (assignments fail for example), but in my example both are slices of the same data type, having len() of 0. They are represented differently in memory, but as slice objects - not really different.

I understand the problem at hand, but it still is something that deserves a mention at https://www.destroyallsoftware.com/talks/wat

**Comment by ianlancetaylor** [comment]
This is working as intended.  reflect.DeepEqual aims to replicate the language's == operator for cases where the language permits a comparison.  `[]byte{} == nil` will return false.
