### ISSUE TITLE
encoding/asn1: failed to parse certificate from server: asn1: syntax error: sequence truncated

### ISSUE THREAD

**Issue by dg-ratiodata** [golang/go#12910]
### Issue

I use two projects which are built with go: [`docker`](https://github.com/docker/docker) and [`gitlab-ci-runner`](https://gitlab.com/gitlab/gitlab-ci-runner).

Both products try to connect to an HTTPS-enabled webservice and fail. In one case it's the docker daemon in the other case it's a NGINX in front of [gitlab](https://gitlab.com/gitlab/gitlab). In both cases I get similar errors:

~~~
: tls: failed to parse certificate from server: asn1: syntax error: sequence truncated
~~~

### Setup

Both webservices use a (different) certificate issued by an internal Sub-CA:

~~~
Root-CA
  Sub-CA
     Sub-CA
       Sub-CA
         Server-CRT
~~~

I tried the webservices to serve the full chain excluding the Root-CA. 

* Gitlab:
  
  Accessing `gitlab` with Firefox, Chromium, `curl` and `openssl s_client` works fine since I setup `ca-trust` correctly: The root CA certificate is stored at `/etc/(pki|ca-certificates/trust-source/anchor` + `sudo update-ca-trust`.

* `docker`
  
  This only worked if I added a single CA to the server CRT. This would require to distribute the other Root-/Sub-CAs on quite a few machines where the docker client runs.

### Expected behaviour

I expect both programs to support certificate chains including verification.

### My role

From your perspective I'm a end-user of both products and NOT an developer/maintiner of those products.

#### docker

~~~
Client:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:19:43 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.1
API version:  1.20
Go version:   go1.4.2
Git commit:   d12ea79
Built:        Thu Aug 13 02:19:43 UTC 2015
OS/Arch:      linux/amd64
~~~

#### gitlab-ci-runner

I'm not sure, what `go`-version exactly was used to create the executable, but they use the docker image "golang:1.4" from the docker library.

### Related issues

* https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/222
* https://github.com/docker/docker/issues/16448

I opened an issue for the HTTPS-problem at golang as well @ayufan @cpuguy83

**Comment by rakyll** [comment]
Could you provide us a Go snippet that reproduces the bug? Given the fact that Go maintainers are not necessarily familiar with the other codebases you have cross linked to, It is hard to go through the other issues and being able to reproduce the case.

**Comment by dg-ratiodata** [comment]
@rakyll Puh. I understand your request, but unfortunately I'm not a go-developer. Maybe @ayufan can help us here.

**Comment by dg-ratiodata** [comment]
And I fear we/the developer needs to setup:

Client:
* Requested Code Snippet

Server
* some small HTTPS-webserver
* SSL-Certificate Chain - relatively easy to setup with [XCA](http://sourceforge.net/projects/xca/)

I can help with CA. To open the CA database the developer needs to download XCA and open/export the certificates from there. The given CA file contains 4 CAs and 2 server certificates. One is for `server.example.com` and the other is for `*.example.com`. I hope it's ok to add some binary file to that issue, but it's the most convient way to re-use my work. I will update this comment after I am finished with the CA DB.



![screenshot](https://cloud.githubusercontent.com/assets/1267524/10434640/1b9d126c-711b-11e5-9135-dba3695577c5.PNG)

**Comment by dg-ratiodata** [comment]
Added link to the CA.

**Comment by dg-ratiodata** [comment]
Setup apache:

~~~apache
Listen 443
<VirtualHost *:443>
    ServerName server.example.com
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/server.example.com.crt
    SSLCertificateKeyFile /etc/ssl/private/server.example.com.key
</VirtualHost>
~~~

**Comment by dg-ratiodata** [comment]
Ok. @rakyll I prepared a docker image you can use if you like. It contains "just" the webservers "nginx" and "apache" setup with ssl. Please see https://github.com/fedux-org/centos-webservers for detailed instructions about how to use it.

~~~
docker pull feduxorg/centos-webservers
~~~

**Comment by dg-ratiodata** [comment]
I put together "some kind" of a client via google and C&P. Unfortunately I cannot reproduce the issue with it. :-(

@ayufan Do you do something different in `gitlab-ci-runner` or use some other library?

~~~go
package main

import (
  "crypto/tls"
  "crypto/x509"
  "log"
  "fmt"
  "net/http"
  "io/ioutil"
  "os"
    )
func main() {

  var caFile = "/etc/ca-certificates/trust-source/anchors/CA_Example_Com.crt"

  // Load CA cert
  caCert, err := ioutil.ReadFile(caFile)
  if err != nil {
    log.Fatal(err)
  }

  caCertPool := x509.NewCertPool()
  caCertPool.AppendCertsFromPEM(caCert)
  
  // Setup HTTPS client
  tlsConfig := &tls.Config{
    RootCAs:      caCertPool,
  }

  tlsConfig.BuildNameToCertificate()
  transport := &http.Transport{TLSClientConfig: tlsConfig}
  client := &http.Client{Transport: transport}

  response, err := client.Get("https://localhost:8443/")
  if err != nil {
    fmt.Printf("%s", err)
    os.Exit(1)
  } else {
    defer response.Body.Close()
    contents, err := ioutil.ReadAll(response.Body)
    if err != nil {
      fmt.Printf("%s", err)
      os.Exit(1)
    }
    fmt.Printf("%s\n", string(contents))
  }
}
~~~

**Comment by rsc** [comment]
Can you post the certificate somewhere we can look at it? If you can't post it, can you email it to me (rsc@golang.org)?

Thanks.

**Comment by dg-ratiodata** [comment]
The failing one or the one from the example?

**Comment by rsc** [comment]
@dg-ratiodata, any failing certificate will do. If the one from the example fails, that's fine too/ (I don't have time to go through whatever is required to fish it out of the Docker image.) Thanks.

**Comment by dg-ratiodata** [comment]
Ok.

**Comment by rsc** [comment]
@dg-ratiodata any update on a copy of the failing certificate?

**Comment by dg-ratiodata** [comment]
No. I asked them, but didn't get an info. I am going to ping them again.

**Comment by rsc** [comment]
Any news? FWIW, this is the sort of thing I'm looking for, except that this program succeeds: http://play.golang.org/p/aW9S8XQcNJ.

The certs in that program are the samples that you linked to earlier. They are fine as far as I can tell. It should be the case that if you paste your real certificate into the program instead, the program should fail, with an error coming back from ParseCertificates.

Note that 'BEGIN CERTIFICATE' data only contains a public key, not a private one. If you're worried about exposing the non-cryptographic details (view with `openssl x509 -in foo.crt -text`) publicly but are okay with emailing it to me (rsc@google.com), that's fine too.

Thanks.

**Comment by dg-ratiodata** [comment]
Great. Will have a look. Thanks a lot for your patience.

**Comment by dg-ratiodata** [comment]
I got this output after adding the certificates. I nailed it down to our internal root CA certificate. All other certs in the chain can be parsed. Besides that, running `openssl` worked fine with this certificate.

~~~
% go run parse.go
2015/12/04 10:08:30 failed to parse certificate: asn1: syntax error: sequence truncated
exit status 1
~~~

Hope to get a repsonse from our security guys soon.

**Comment by dg-ratiodata** [comment]
@rsc Wow, that was quick. Thanks for fixing this issue.
