### ISSUE TITLE
syscall: PtracePeekUser

### ISSUE THREAD

**Issue by agis-** [golang/go#12912]
We already have [`syscall.PtracePeekData`](https://golang.org/pkg/syscall/#PtracePeekData) and [`syscall.PtracePeekText`](https://golang.org/pkg/syscall/#PtracePeekText) but not `PtracePeekUser`.

Any thoughts about adding it too? If it makes sense, I could prepare a patch.

**Comment by minux** [comment]
Please consider adding it to x/sys/unix.

The syscall package is frozen.

**Comment by adg** [comment]
It should be added to the golang.org/x/sys repository, not the standard
syscall package.
The standard syscall package will only be changed to accommodate the Go
runtime, standard library, and tools.

**Comment by agis-** [comment]
OK, will do it soon. Thanks!

**Comment by bradfitz** [comment]
Added in https://go-review.googlesource.com/c/38638/ (https://github.com/golang/sys/commit/afadfcc7779c1f4db0f6f6438afcb108d9c9c7cd) by @agis-
