### ISSUE TITLE
bufio: 1.5.1 panic slice bounds out of range

### ISSUE THREAD

**Issue by semihalev** [golang/go#12925]
Hi,

Today, i received panic from bufio reader. I used bufio for tcp connections. The function running for 30 days without problem.

Here is the sample code:
 ```
func TCPReader(connection *net.TCPConn) {
	reader := bufio.NewReaderSize(connection, 8192)

	header := make([]byte, 9)
	for {
		len, err := reader.Read(header[:])
	}
}
```

Panic Log:
panic: runtime error: slice bounds out of range

goroutine 490939 [running]:
bufio.(*Reader).Read(0xc828791f80, 0xc82858b670, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:214 +0x3c8

**Comment by ianlancetaylor** [comment]
Have you run your program under the race detector?

**Comment by semihalev** [comment]
Yes, I did'nt see any problem for read.

**Comment by adg** [comment]
We're going to need a short program that reproduces this. Can you isolate the issue?

**Comment by semihalev** [comment]
Ok, i will create a small project, and inform you again.

**Comment by semihalev** [comment]
I found data race in tcp reconnect function. I try to change first this. I will inform you.

**Comment by adg** [comment]
In that case, I'm going to close this issue until you report back.
