### ISSUE TITLE
text/template: inconsistency when accessing a field of an interface field

### ISSUE THREAD

**Issue by nodirt** [golang/go#12924]
In a pipeline `{{.Foo.Bar}}` where `Foo` field is declared as of type interface `I` and points to a struct `S` that implements `I` and has `Bar` field:

* `Bar` can be resolved if `I` is `interface{}`
* `Bar` cannot be resolved if `I` is a non-empty interface

http://play.golang.org/p/Knps5C6aaL

I think this is inconsistent, `Bar` should be resolvable with non-empty `I`.
This wasn't catched by tests because there is a test for `interface{}`, but not for a non-empty interface.

I'd like to work on this.

**Comment by adg** [comment]
This does seem inconsistent. It also seems like a bad thing to rely on. Happy to review a fix.

**Comment by nodirt** [comment]
While reading the code, discovered one more case
http://play.golang.org/p/eM7lrc1lIM

I think we have to support this because templates are inherently dynamically-typed.

**Comment by nodirt** [comment]
Same thing with `len` http://play.golang.org/p/qXOU4I5Vyj

**Comment by nodirt** [comment]
And with `range`
