### ISSUE TITLE
tour: bad error handling example

### ISSUE THREAD

**Issue by nigham** [golang/go#12926]
Context: http://tour.golang.org/methods/8

The example showing how to check for err being nil always shows the converted integer; the converted integer should only be shown if there is no error? Suggested code:

```
i, err := strconv.Atoi("42")
if err != nil {
    fmt.Printf("couldn't convert number: %v\n", err)
} else {
    fmt.Println("Converted integer:", i)
}
```

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by kytrinyx** [comment]
It's quite uncommon to see an `else` when handling errors. Usually you'll see a return, exit, or break.

I'd suggest that instead of having an else we add a return, even though it's not clear what the context is. Or, perhaps we could add a comment

```
i, err := strconv.Atoi("42")
if err != nil {
    fmt.Printf("couldn't convert number: %v\n", err)
    return
}
fmt.Println("Converted integer:", i)
```


```
i, err := strconv.Atoi("42")
if err != nil {
    fmt.Printf("couldn't convert number: %v\n", err)
    // return, break, or exit here
}
fmt.Println("Converted integer:", i)
```

**Comment by adg** [comment]
The `return` seems good to me.
