### ISSUE TITLE
cmd/compile: compiler allows unreachable statements 

### ISSUE THREAD

**Issue by shoenig** [golang/go#12920]
I noticed this in some badly re-factored complex code, but it reduces nicely into this toy program. Basically the compiler allows unreachable statements that could be detected statically at compile time. It would be nice if code like this failed to compile. 

```code
package main

import "fmt"

func main() {
	fmt.Println("foo", foo())
}

func foo() int {
	fmt.Println("now you see me")
	return 0
	fmt.Println("now you don't")
	return 1
}
```

**Comment by mdempsky** [comment]
While questionable, that's technically valid Go 1 code, so it has to be accepted by the compiler.  It's also already caught by cmd/vet:

$ go vet issue12920.go
issue12920.go:12: unreachable code

**Comment by ianlancetaylor** [comment]
Let me add that to try to ensure that all Go compilers agree on which programs can be compiled, the notion of an unreachable statement is actually defined by the language spec: https://golang.org/ref/spec#Terminating_statements .

**Comment by minux** [comment]
Permitting early returns helps debugging a large function where you might
want to quickly disable the last portion by putting in a return.

The alternative of adding an if 0 (which also introduces deadcode) or
commenting out/deleting aren't as easy.
