### ISSUE TITLE
Compiler blows up at a switch on a struct initialization.

### ISSUE THREAD

**Issue by zyzniewski-filip** [golang/go#12934]
This works nicely: http://play.golang.org/p/DgB7G3g0LB

OTOH this blows up: http://play.golang.org/p/Z_ceHAaOU2 
  prog.go:10: syntax error: unexpected name, expecting case or default or }

Is this by design? Seems weird to not be able to instantiate a struct in a switch statement.

**Comment by bradfitz** [comment]
Expected. You need to use parens in that second case: http://play.golang.org/p/kSr7pUhV7i

Let's move discussion to one of the forums (https://golang.org/wiki/Questions), though, as there's no bug to track here.
