### ISSUE TITLE
net/http: srv.Serve hangs if RemoteAddr() blocks

### ISSUE THREAD

**Issue by glasser** [golang/go#12943]
The PROXY protocol is supported by several proxy servers such as haproxy
and Amazon ELB.  This protocol allows services running behind a proxy to
learn the remote address of the actual client connecting to the proxy,
by including a single textual line at the beginning of the TCP
connection.
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

There are several Go libraries for this protocol (such as
https://github.com/armon/go-proxyproto), which operate by wrapping a
net.Conn with an implementation whose RemoteAddr method reads the
protocol line before returning. This means that RemoteAddr is a blocking
call.

(Blocking inside `Accept` is not an option either; the point is that we want `srv.Serve` to call `Accept` on the underlying socket as soon as the previous `Accept` call succeeded, without any blocking operations.)

This exists in current Go master (eg, 1.5.1) on all platforms (eg, Linux).

**Comment by jingweno** [comment]
@glasser Does that mean i could use https://github.com/armon/go-proxyproto without blocking now?

**Comment by glasser** [comment]
@jingweno I believe so (though my project hasn't upgraded to 1.6 yet so I don't have production experience).
