### ISSUE TITLE
x/mobile/cmd/gomobile: c++ library on mac

### ISSUE THREAD

**Issue by hsinhoyeh** [golang/go#12948]
hi,
I am working on build c/c++ library with cgo into ios platform (by gomobile)
when I run go bind -target=ios, you actually build three environments:
https://github.com/golang/mobile/blob/master/cmd/gomobile/bind_iosapp.go#L49

```
for _, env := range [][]string{darwinArmEnv, darwinArm64Env, darwinAmd64Env} {
        arch := archClang(getenv(env, "GOARCH"))
        path, err := goIOSBindArchive(name, mainFile, env)
        if err != nil {
            return fmt.Errorf("darwin-%s: %v", arch, err)
        }
        cmd.Args = append(cmd.Args, "-arch", arch, path)
    }
```

and it turns out that "by default" darwinArmEnv and darwinArm64Env use libc++ library, while darwinAmd64Env use libstdc++. 

the following workaround works for me:

```
diff --git a/cmd/gomobile/env.go b/cmd/gomobile/env.go
index dcb79eb..98371f4 100644
--- a/cmd/gomobile/env.go
+++ b/cmd/gomobile/env.go
@@ -154,8 +154,8 @@ func envInit() (err error) {
                "GOARCH=amd64",
                "CC=" + clang,
                "CXX=" + clang,
-               "CGO_LDFLAGS=" + cflags + " -mios-simulator-version-min=6.1 -arch x86_64",
+               "CGO_LDFLAGS=" + cflags + " -mios-simulator-version-min=6.1 -arch x86_64 -stdlib=libc++",
                "CGO_ENABLED=1",
        }

```

I think it is better to allow CXXFLAGS can be passed when build.

**Comment by crawshaw** [comment]
Thanks, that's surprising. It's probably worth setting that by default. Would you like to send a CL, or rather I do it?

**Comment by rakyll** [comment]
I am wondering whether there is any advantage of using the system default, libstdc++, given the fact that libc++ and libcstd++ are not ABI compatible.

**Comment by hsinhoyeh** [comment]
if we keep libc++ as default, we need to document somewhere which tells that we always need to use ```CXXFLAGS="-stdlib=libc++"``` to build c/c++ project before link to gomobile.

@crawshaw I will send a CL and also think how to add a unittest. Is it ok to add a test by linking cgo and gomobile? In my case, I use https://github.com/jmhodges/levigo and https://github.com/google/leveldb

**Comment by hyangah** [comment]
@hsinhoyeh adding test sounds great. Just don't depend on 3rd party repositories; instead come up with minimal cgo examples.

**Comment by eliasnaur** [comment]
Is this a problem? Perhaps the default std. c++ runtime has changed with newer iOS SDKs.
