### ISSUE TITLE
reflect: Value.Elem() inconsistency betwen go1.4.3 and go.15

### ISSUE THREAD

**Issue by odeke-em** [golang/go#12954]
In some code whose struct 
```go
type pushCmd struct {
	Hidden         *bool   `json:"hidden"`
	Source         *string `json:"source"`
	Convert        *bool   `json:"convert"`
	Ocr            *bool   `json:"ocr"`
	IgnoreChecksum *bool   `json:"ignore-checksum"`
}
```
I perform some value extraction by json tag and fill in a fresh pushCmd value with a mix of already defined values from a resource configuration and those already entered in the from value. However, running the exact same program http://play.golang.org/p/4NRzI-ejuc on go1.4.3 and then on go.1.5 gives different results
![golang-inconsistency](https://cloud.githubusercontent.com/assets/4898263/10534247/1c64f9ec-7393-11e5-88dc-c5320dd24fdd.png)
The code example and results are at https://github.com/odeke-em/bugs/tree/master/golang/reflect-inconsistency

**Comment by nodirt** [comment]
Distilled, ```fmt.Println(reflect.ValueOf(true))``` changed. In Go 1.4 this prints `<bool Value>`. In Go 1.4, this prints `true`.

This doesn't violate [Go 1 compatibility guidelines](https://golang.org/doc/go1compat#expectations), which says _The Go specification tries to be explicit about most properties of the language, but there are some aspects that are undefined. Programs that depend on such unspecified behavior may break in future releases._

In Go 1.4 `fmt` [didn't specify](https://github.com/golang/go/blob/go1.4.3/src/fmt/doc.go#L141) how it formats `reflect.Value`. It [have been specified](https://github.com/golang/go/blob/go1.5.1/src/fmt/doc.go#L141-L143) only in Go 1.5

Note that `reflect.ValueOf(true).String())` value didn't change.

**Comment by nodirt** [comment]
Actually, I admit it was a breaking change because fmt specification essentially changed: the rule 

```
If an operand implements method String() string, that method
will be invoked to convert the object to a string, which will then
be formatted as required by the verb (if any).
```

applied in the past. I still don't think anything will be done about this.

**Comment by ianlancetaylor** [comment]
The change is documented in https://golang.org/go1.5.html.  I don't consider it to be a Go 1 compatibility breaking change: if we changed reflect.Value.String that wouldn't be a breaking change either.  Breaking user types would be a breaking change.  The handling of library defined types is up to the library.

**Comment by odeke-em** [comment]
Alright, thank you folks for taking a look at this. My way around it was to invoke ".Interface()"
```diff
-   fmt.Sprintf("%v", elem)
+   fmt.Sprintf("%v", elem.Interface())
```
and that produces the desired result between go 1.5 and 1.4.3.
