### ISSUE TITLE
x/crypto/ssh: Make SetDefaults disable diffie-hellman-group1-sha1

### ISSUE THREAD

**Issue by jeffallen** [golang/go#12955]
https://weakdh.org/sysadmin.html recommends that users of OpenSSH who want to continue to support non-elliptic-curve Diffie-Hellman should disable Group 1 support, by removing the diffie-hellman-group1-sha1 Key Exchange.

I think it would be in keeping with Go's normal forward looking and strong security posture that SetDefault does not include kexAlgoDH1SHA1 in Config.KeyExchanges. The docs could be updated to indicate that users wishing to enable this deprecated key exchange algorithm should add it at the end of Config.KeyExchanges themselves after calling SetDefaults.

**Comment by hanwen** [comment]
Would this really fix anything, practically speaking? Group1 is already the least preferred kex anyway. 

Do you have any data on which implementations don't support anything but group1? Are there any clients which prefer group1 over the stronger kexes?

**Comment by jeffallen** [comment]
It's a question of defensive security posture. In a perfect world, clients would protect themselves by insisting on something other than group1, but we don't live in a perfect world.

In my opinion, Go's defaults should be defensive, and we now suspect that group1 is unusable for secure communication, so it has to be removed from the defaults.
