### ISSUE TITLE
Error variable fails err != nil check even when nil

### ISSUE THREAD

**Issue by perj** [golang/go#12956]
I'm honestly not sure what the conditions are exactly but the below code will reproduce the problem on these settings:

go version go1.5 darwin/amd64 (built from commit bb03defe933c89fee44be675d7aa0fbd893ced30)
go version go1.4.2 linux/amd64 (yum epel package)

Changing `var err error` to `var err *Error` makes the code work.

Steps to reproduce:
* go run bug.go

Expected result:
Program exits normally

Actual result:
Panic during panic since the `if err != nil` check succeeds.

```
package main

type Error struct {
	Err error
}

func (err *Error) Error() string {
	return err.Err.Error()
}

func test() *Error {
	return nil
}

func main() {
	var err error
	err = test()
	if err != nil {
		panic(err)
	}
}
```

**Comment by perj** [comment]
Alright, my colleague explained this is per design and I should just make all my functions return `error` instead and I won't run into it. I have a slight problem with that since it makes it much more likely to forget to do my wrapping of the inner error, but I guess it's just how things are.

**Comment by minux** [comment]
FYI, https://golang.org/doc/faq#nil_error
