### ISSUE TITLE
x/tools/oracle does not install into $GOPATH/bin on OS X El Capitan

### ISSUE THREAD

**Issue by carbocation** [golang/go#12976]
### What version of go are you using?
`go version go1.5.1 darwin/amd64`

### What operating system and processor architecture are you using?
`Macbook Air OS X El Capitan version 10.11 (15A284)`

### What did you do?
`go get -u -v golang.org/x/tools/oracle`

### What did you expect to see?
As per [the oracle manual](http://golang.org/s/oracle-user-manual), I expect an installation of `oracle` to appear in `$GOPATH/bin`.

### What did you see instead?
`$GOPATH/bin` is unchanged; no binary appears there.

To ensure that this was not simply a problem with my `go` installation, I performed the same procedures with `go get github.com/tools/godep`, which successfully led to the `godep` binary appearing in `$GOPATH/bin`

**Comment by dominikh** [comment]
`go get golang.org/x/tools/cmd/oracle`, not `go get golang.org/x/tools/oracle` – You're fetching the oracle library, not the actual tool.

**Comment by minux** [comment]
I checked the manual, and the command listed there is correct.
