### ISSUE TITLE
cmd/doc: strange formatting on inline comment in struct with unexported field

### ISSUE THREAD

**Issue by dsnet** [golang/go#12971]
Using ```go1.5```

Consider this Go package:
```go
package foo

type Reader struct {
	InputOffset  int64 // Total number of bytes read from underlying io.Reader.
	OutputOffset int64 // Total number of bytes emitted from Read.
	hidden       int
}
```

Currently I see:
```
$ go doc Reader
type Reader struct {
	InputOffset  int64 // Total number of bytes read from underlying io.Reader.
	OutputOffset int64
				// Total number of bytes emitted from Read.
	// Has unexported fields.
}
```

I expect to see:
```
$ go doc Reader
type Reader struct {
	InputOffset  int64 // Total number of bytes read from underlying io.Reader.
	OutputOffset int64 // Total number of bytes emitted from Read.
	// Has unexported fields.
}
```

---

On a slightly related note, if you just comment out "hidden", but don't delete it, an extra newline is unnecessarily printed:
```
$ go doc Reader
type Reader struct {
	InputOffset  int64 // Total number of bytes read from underlying io.Reader.
	OutputOffset int64 // Total number of bytes emitted from Read.

}
```

@robpike

**Comment by robpike** [comment]
This is how the go/doc package (not cmd/doc) folds lines. The issue is triggered by Output being one byte longer than Input, reaching a threshold.

Working as intended.

**Comment by dsnet** [comment]
I don't think it has to do with Output being one byte longer. The still occurs with this trivial package:
```go
package foo

type A struct {
	A int // A
	B int // B
	c int
}

```

Actually, I believe the bug is from the go/doc package. I traced the issue to the fact that the NamePos is not being set. See [CL/16286](https://go-review.googlesource.com/#/c/16286/).
