### ISSUE TITLE
encoding/json: unexpected json.Unmarshal behavior with maps

### ISSUE THREAD

**Issue by nandosousafr** [golang/go#12972]
http://golang.org/src/encoding/json/decode.go?s=2621:2669#L64
> To unmarshal a JSON object into a map, Unmarshal __replaces the map with an empty map__ and then adds key-value pairs from the object to the map.

But, while unmarshalling it behaves differently.

http://play.golang.org/p/HTjkkCEQBV
```go
var r map[string]string
j := []byte(`{"hello": "world"}`)

json.Unmarshal(j, &r)
fmt.Println(r)
// map[string]string{"hello":"world"}

ja := []byte(`{"world": "hello"}`)
json.Unmarshal(j, &r)
fmt.Println(r)
// map[string]string{"hello":"world", "world":"hello"}
// expected to eq map[string]string{"world": "hello"}
```

I'm totally in favor of this behavior but what docs is saying isn't correct.

That make sense?

**Comment by dominikh** [comment]
749b391c55b0139910d86ac0f8a0c42957e01d1c added said documentation and a test for the behaviour. Unfortunately, the test itself is broken, too. https://github.com/golang/go/blob/master/src/encoding/json/decode_test.go#L313 is supposed to test the overwriting of the map. However, in https://github.com/golang/go/blob/master/src/encoding/json/decode_test.go#L536 the initial value gets thrown away and replaced with an empty map. That way, the test doesn't actually test the overwriting of the map.

**Comment by dominikh** [comment]
Furthermore, this doesn't look like a regression. It does still overwrite slices; and Go 1.4.2 didn't overwrite maps, either.

**Comment by sillyousu** [comment]
http://play.golang.org/p/HTjkkCEQBV
 Unmarshal resets slice, but doesn't rest map. I think they should have the same behavior.

https://github.com/golang/go/blob/release-branch.go1.5/src/encoding/json/decode.go#L521

**Comment by nodirt** [comment]
Fix: https://go-review.googlesource.com/#/c/16020/

**Comment by rsc** [comment]
It's entirely possible we should change the docs instead of changing the implementation.

**Comment by james-lawrence** [comment]
seems like not changing one of the implementations (slices or maps) leads to inconsistency in the api. if that matters at all in your decision.
