### ISSUE TITLE
tour: Switch weekdays example not working 

### ISSUE THREAD

**Issue by AlessioMartorelli** [golang/go#12973]
Context: https://tour.golang.org/flowcontrol/10

I've tried running the switch example that calculates how fare a day of the week is. It doesn't seem to work. If the day is today it works, otherwise I'll just skip to the default action like if the today + number doesn't work.

**Comment by minux** [comment]
What do you mean that it doesn't work?

Have you noticed that the time on the playground server always
starts from the fixed date warning on the right side?

**Comment by AlessioMartorelli** [comment]
I might be missing something but I've tried writing the code on my laptop:
fmt.Println("When is Sunday?")
    today := time.Now().Weekday()
    switch time.Sunday {
    case today:
        fmt.Println("It's today!")
    case today + 1:
        fmt.Println("It's tomorrow!")
    case today + 2:
        fmt.Println("It's in two days!")
    default:
        fmt.Println("It's too far away!")
    }

Since today is Saturday and I'm looking for Sunday, I'd expect to see "It's tomorrow", but I get "It's too far away".
Again this is so simple that I may be missing something stupid.

**Comment by minux** [comment]
Please note that time.Sunday is 0 not 7.

https://golang.org/pkg/time/#Sunday

**Comment by AlessioMartorelli** [comment]
Makes sense. In fact when printing today+1 I get:
%!v(PANIC=runtime error: index out of range)

Which explains why it goes straight to default.
Thanks for your help.

**Comment by minux** [comment]
by the way, please ask questions on the forum or
the mailing list, and not on the issue tracker.
Thanks.

see https://golang.org/wiki/Questions.

**Comment by kjperkin** [comment]
I just ran into this. The example code doesn't give the correct result if you change **time.Saturday** to **time.Sunday** and the current day is Saturday. It seems to be because of the way the cases are written. Since the example code is meant to be played with, I would expect the code to work for any day of the week.

**Comment by minux** [comment]
FYI, One way to make it work for all cases:
http://play.golang.org/p/oCXGykon-H

**Comment by AlessioMartorelli** [comment]
I agree with kjperkin. I neglected to check the doc and that's my bad, but would be nice for people approaching a new language if examples simply worked "out of the box".

Thanks minux, I thought about the same solution after reading the documentation. Is it maybe worth replacing the code in the example with the one you posted to prevent other people encountering the same issue?
