### ISSUE TITLE
x/crypto/ssh/terminal: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.IsTerminal

### ISSUE THREAD

**Issue by techtonik** [golang/go#12978]
This warnings are Windows only:
```
lxc\config.go:99: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.IsTerminal
lxc\config.go:345: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.IsTerminal
lxc\exec.go:57: cannot use syscall.Stdout (type syscall.Handle) as type int in argument to terminal.GetSize
```
And the code in `lxc\config.go:99` is this:
```
	if !terminal.IsTerminal(syscall.Stdin) && value == "-" {
```
How to fix that? Is it a Go bug?

**Comment by bradfitz** [comment]
I don't think the x/crypto/ssh/terminal package supports Windows.

This isn't a bug in Go, but a lack of implementation in an external package.

**Comment by bradfitz** [comment]
Nevermind, the x/crypto/ssh/terminal package does support Windows and build.golang.org says it's passing its tests. I see the code for Windows in x/crypto/ssh/terminal and I can install it fine:

```
bradfitz@dev-bradfitz-debian2:~/src/golang.org/x/crypto/ssh/terminal$ GOOS=windows go install .
```

Your error message contains `lxc/`.

I think you have the wrong bug tracker. I don't know what package you're compiling, but it's not in the Go repos anywhere.

**Comment by techtonik** [comment]
@bradfitz are you sure there are tests for this part?

**Comment by techtonik** [comment]
This is the package https://github.com/lxc/lxd/blob/master/lxc/config.go#L98

    go get github.com/lxc/lxd
    cd %GOPATH%\src\github.com\lxc\lxd
    go get -t -v -d ./...
    go install -v ./lxc

It works on Linux, but fails on Windows. There is no system dependent code in this part of my code. It is solely on Go side.

**Comment by bradfitz** [comment]
Yes, there are tests. And build.golang.org shows that it's passing.

The code in github.com/lxc/lxd is wrong. The error messages (they're not warnings; Go doesn't have warnings) you pasted above are the reason. I can't explain it any more clearly than the error messages already say.

**Comment by bradfitz** [comment]
It doesn't even seem to compile on Linux!

```
$ go get github.com/lxc/lxd
# github.com/lxc/lxd/shared
../../../../../github.com/lxc/lxd/shared/util_linux.go: In function 'shiftowner':
../../../../../github.com/lxc/lxd/shared/util_linux.go:126:18: error: 'O_PATH' undeclared (first use in this function)
../../../../../github.com/lxc/lxd/shared/util_linux.go:126:18: note: each undeclared identifier is reported only once for each function it appears in
```

In any case, all you should have to do is change it to:

```go
  if !terminal.IsTerminal(int(syscall.Stdin)) && value == "-" {
```

**Comment by techtonik** [comment]
It can't be that it don't compile - test are green - https://github.com/lxc/lxd#ci-status Although I can't find where `go get github.com/lxc/lxd` is executed there.

**Comment by techtonik** [comment]
@bradfitz it is strange that syscall.Stdin changes type on Windows. I expected types to be platform-independent, but thanks for this hint.

**Comment by bradfitz** [comment]
In any case, this is the wrong bug tracker.

**Comment by techtonik** [comment]
@bradfitz it is at least documentation bug in golang. According to https://golang.org/pkg/syscall/#pkg-variables syscall.Stdin should be int on all platforms. And for system-specific Windows calls, it could be made with syscall.StdinHandler or something.

**Comment by kostya-sh** [comment]
@techtonik, golang.org/pkg displays documentation for Linux. Actually the additional documentation that you request is already there:

> Package syscall contains an interface to the low-level operating system primitives. The details vary depending on the underlying system, and by default, godoc will display the syscall documentation for the current system. If you want godoc to display syscall documentation for another system, set $GOOS and $GOARCH to the desired system.

**Comment by techtonik** [comment]
@kostya-sh thanks for clarification. Created issue. ;)
