### ISSUE TITLE
x/text: internal/TestParents and language/TestCompactIndex are failing

### ISSUE THREAD

**Issue by awalterschulze** [golang/go#12987]
go 1.5
linux amd64

Also it would be nice it the golang/text repo's readme.md could provide a link to where it wants its issues reported, please.

**Comment by mpvl** [comment]
Thanks for the report. A fix is under review.

Sent out a fix. Note that all go repos, including this one, describe the contribution  guidelines in CONTRIBUTING.md.

**Comment by mpvl** [comment]
Fixed by CL 16011

**Comment by awalterschulze** [comment]
--- FAIL: TestLinking-8 (1.56s)
	currency_test.go:151: size(symbols)-size(base) was 0; want > 2K

**Comment by awalterschulze** [comment]
Seems not all tests are stable.

**Comment by mpvl** [comment]
That one is unrelated. The remaining failures seem to be various issues
with the build environment. (Missing GOPATH and missing test files).

On Tuesday, October 20, 2015, Walter Schulze <notifications@github.com>
wrote:

> Seems not all tests are stable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/go/issues/12987#issuecomment-149462098>.
>


-- 
Marcel van Lohuizen -- Google Switzerland GmbH -- Identifikationsnummer:
CH-020.4.028.116-1

**Comment by awalterschulze** [comment]
That is the only test that is failing.
Could you please fix it?

**Comment by mpvl** [comment]
I don't see it failing on the build dashboard and it passing for me
locally. Could you please file another bug with more context?

The test builds a couple of binaries to verify the linker is dropping
tables properly. Such tests are a bit finicky to get right.

**Comment by awalterschulze** [comment]
Ok weird I can't reproduce it now either.
I guess thats my bad. Sorry.
