### ISSUE TITLE
x/tools/refactor/rename: Unterminated single quote in usage string.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#12981]
[rename.go#L103](https://github.com/golang/tools/blob/f53a5581bc2fdd52820df86cbfd8483816fe8bcc/refactor/rename/rename.go#L103) currently has:

```
% gorename -from \"bytes\".Buffer.Len' -to Size
```

It has an unterminated single quote. It should be fixed either by adding a single quote in front (and not escaping the double quotes):

```
% gorename -from '"bytes".Buffer.Len' -to Size
```

Or by removing the existing single quote:

```
% gorename -from \"bytes\".Buffer.Len -to Size
```

**Comment by dominikh** [comment]
You don't need to/must not escape the double quotes when they're enclosed in single quotes.

**Comment by shurcooL** [comment]
Thanks @dominikh, I've edited the original post to fix that.

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/#/c/16053/
