### ISSUE TITLE
proposal: more functional programming support in standard library

### ISSUE THREAD

**Issue by choleraehyq** [golang/go#12985]
Hello everyone, recently I have written some functional-style code, and found that although function is the first class in Golang, there isn't any other functional programming support like common high level function(map, reduce, partial etc.) in Golang. Why don't we add a package in standard library just like functools in python?

I have already written a simple prototype [gofunctools](https://github.com/choleraehyq/gofunctools) to show my idea.

**Comment by adg** [comment]
Why should it be in the standard library?

**Comment by bradfitz** [comment]
Obligatory link: https://golang.org/doc/faq#x_in_std

**Comment by choleraehyq** [comment]
@adg @bradfitz 
I think this package is very basic. If the bar of standard library is high, how about adding it to Go sub-repository packages?

**Comment by adg** [comment]
What's the advantage of putting it there? To get more people to use it?

Many such libraries have been written over the years, but few see much use. Why? One explanation is that to use such libraries you must sacrifice compile time type safety, one of Go's major strong points. I don't think this is the kind of Go code we want to encourage people to write.

**Comment by choleraehyq** [comment]
@adg 
I have already understood your meaning now. Thank you for your response.
