### ISSUE TITLE
regexp/syntax: syntax.Regexp.String mishandles syntax.OneLine flag

### ISSUE THREAD

**Issue by nvanbenschoten** [golang/go#12980]
The lack of the `OneLine` syntax.Flag when parsing a `syntax.Regexp` should correspond to an `m` regexp flag, which defaults to false when compiling a `regexp.Regexp` if not present. The [`syntax.writeRegexp`](https://golang.org/src/regexp/syntax/regexp.go?#L114) function should therefore add the `m` flag when it is needed. Instead, it looks like the `writeRegexp` function [subtracts the `m` flag](https://golang.org/src/regexp/syntax/regexp.go?#L176) when it is not needed, which would be incorrect based on the default functionality.

Here is a [Go Playground](https://play.golang.org/p/wqawrTj55B) to demonstrate this.

**Comment by ianlancetaylor** [comment]
CC @rsc
