### ISSUE TITLE
Goroutine leak detector

### ISSUE THREAD

**Issue by klauspost** [golang/go#12989]
In my experience it could be very valuable to have a goroutine "leak" detection similar to the race detector we already have. It should be able to detect goroutines that will never we runnable again, and therefore is "leaked".

I have created a [playground example](http://play.golang.org/p/g0L28Rove3) of the things I could imagine would be detectable, which are blocking selects, sync.Mutex, sync.WaitGroup, sync.Cond, where no other goroutine holds a reference to the item needing to unblock it. 

The examples are of course very simple, but I don't see why it shouldn't apply in a much bigger scope.

I imagine this could be used in a similar fashion as the race detector, so it is an option that can be used for testing, problem identification, etc.

**Comment by adg** [comment]
Sounds like a nice research project. We can re-open this issue if/when someone wants to work on it.

**Comment by bradfitz** [comment]
Related: #6705 (testing: add test helpers for measuring goroutine leaks), which I was just working on the other day.

But this bug is a dup of #5308 which is still open.
