### ISSUE TITLE
net/http: incomplete http host header passed with net/http on go 1.5.1

### ISSUE THREAD

**Issue by nishanthb** [golang/go#12997]
This code below results in an incomplete HTTP Host header being passed on go version go1.5.1 linux/amd64. Older versions did not show this problem (tested on go version go1.3 linux/amd64)

> package main
>
> import (
>   "fmt"
>   "net/url"
>   "net/http"
>   "strings"
> )
>
> func main() {
>   uv := url.Values{"data":{"test"}}.Encode()
>   client := &http.Client{}
>   req,_ := http.NewRequest("POST","http://localhost:8000",strings.NewReader(uv))
>   req.Host = `http://www.myhost.com`
>   req.Header.Add("Content-Type","application/x-www-form-urlencoded")
>   req.Header.Add("Content-Length",string(len(uv)))
>   resp,err := client.Do(req)
>   if err != nil {
>       fmt.Println("Got err: ", err)
>   }
>   fmt.Println(resp)
> }

Request sent (go version go1.5.1 linux/amd64)

> POST / HTTP/1.1
> Host: http:
> User-Agent: Go-http-client/1.1
> Content-Length: 9
> Content-Type: application/x-www-form-urlencoded
> Accept-Encoding: gzip
> 
> data=test

Request sent (go version go1.3 linux/amd64)

> POST / HTTP/1.1
> Host: http://www.myhost.com
> User-Agent: Go 1.1 package http
> Content-Length: 9
> Content-Type: application/x-www-form-urlencoded
> Accept-Encoding: gzip
> 
> data=test

Thanks,
Nishanth

**Comment by davecheney** [comment]
Technically both versions are non compliant.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html says the Host header
may contain only a hostname and an optional port.

The workaround for you is to not pass a URL to that field.

I think the solution would be to leverage the fact that method returns an
error and do some validation before issuing the request.

/cc @bradfitz

**Comment by bradfitz** [comment]
What @davecheney said.

**Comment by bradfitz** [comment]
Also this is wrong:

> req.Header.Add("Content-Length",string(len(uv)))

That will not produce the right answer at all. string(int) doesn't do what you think.
