### ISSUE TITLE
html/template broken after clone

### ISSUE THREAD

**Issue by jbeda** [golang/go#12996]
See https://play.golang.org/p/r83esZdCzY.

```
package main

import "os"
import "fmt"
import "html/template"

func main() {
	t := template.New("name")
	t, _ = t.Clone()
	t = template.Must(t.Parse("stuff"))
	err := t.Execute(os.Stdout, nil)
	if err != nil {
		fmt.Printf("Error: %v", err)
	}
}
```

Produces:
```
Error: template: "name" is an incomplete or empty template; defined templates are: "name"
```

For the "source" template, it looks like `Clone` creates two copies.

I *think* adding this in the loop (after the definition of `name` would fix it):

```
if name == ret.text.Name() {
  ret.set[name] = ret
  continue
}
```

**Comment by adg** [comment]
> For the "source" template, it looks like Clone creates two copies.

What does this mean?

**Comment by jbeda** [comment]
"Source" means the template that you are cloning from.  Looks like it creates the copy directly and another in the "textClone.Templates()" loop.  You can see how text/template Clone deals with it here: https://github.com/golang/go/blob/master/src/text/template/template.go#L89

**Comment by nodirt** [comment]
@jbeda it does not create two copies of itself because, unlike html/template, in text/template `Template.Templates()` doesn't return itself
