### ISSUE TITLE
x/tools/refactor/rename: could update godoc as well

### ISSUE THREAD

**Issue by tessr** [golang/go#13000]
When I run `gorename -from '"package".Foo' -to 'Bar'` on the following: 

```
// Foo does some things.
func Foo() {}
```

gorename currently leaves the comment untouched, but it would be nice if the comment updated as well, to: 

 ```
// Bar does some things.
func Bar() {}
```

**Comment by alandonovan** [comment]
It would be nice, but an algorithmic approaches can do a partial job at best.  Heuristics might be able to identify the subject of the first sentence of the doc comment, but the name might appear many times within the doc comment (and other comments), capitalized or not, and it's impossible to distinguish identifiers from technical terms in comments.

For these reasons, I'd rather not touch it.
