### ISSUE TITLE
expected element type <w:document>  as the tag name?

### ISSUE THREAD

**Issue by xpbliss** [golang/go#13009]
package main
    import (
        "encoding/xml"
        "fmt"
    )
    type Document struct {
        XMLName xml.Name `xml:"w:document"`
        W       string   `xml:"xmlns:w,attr"`
        A       string   `xml:"xmlns:a,attr"`
        C       string   `xml:"xmlns:c,attr"`
        Dgm     string   `xml:"xmlns:dgm,attr"`
        Lc      string   `xml:"xmlns:lc,attr"`
        M       string   `xml:"xmlns:m,attr"`
        Mc      string   `xml:"xmlns:mc,attr"`
        O       string   `xml:"xmlns:o,attr"`
        Pic     string   `xml:"xmlns:pic,attr"`
        R       string   `xml:"xmlns:r,attr"`
        Sl      string   `xml:"xmlns:sl,attr"`
        V       string   `xml:"xmlns:v,attr"`
        W10     string   `xml:"xmlns:w10,attr"`
        Wne     string   `xml:"xmlns:wne,attr"`
        Wp      string   `xml:"xmlns:wp,attr"`
        Wpg     string   `xml:"xmlns:wpg,attr"`
        Wps     string   `xml:"xmlns:wps,attr"`
    }

    func main() {
        data := `<w:document xmlns:ve="http://schemas.openxmlformats.org/markup-compatibility/200
    6" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.ope
    nxmlformats.org/officeDocument/2006/relationships" xmlns:v="urn:schemas-microsof
    t-com:vml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordproces
    singDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://s
    chemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr></w:pP
    r><w:r><w:rPr><w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica" w:cs="Helvetica"
    /><w:sz w:val="24"/><w:sz-cs w:val="24"/></w:rPr><w:t xml:space="preserve">Hello
     World</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11900" w:h="16840"/><w:pgMar w:to
    p="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:d
    ocument>  `  
        v := Document{}
        err := xml.Unmarshal([]byte(data), &v)
        if err != nil {
            fmt.Printf("error: %v", err)
            return
        }
        fmt.Println(v)
        fmt.Printf("%#v\n", v)
    }

// If change the `<w:document>` to `<document>`,and change  the `</w:document>` to `</document>`.  all is ok!
It didn't support such the `AA:bb`as the Tag name or Attribute name!

**Comment by bradfitz** [comment]
I don't think "w:document" is a valid XMLName. But I'd ask in a forum. I'm not sure this is actually a bug report. See https://golang.org/wiki/Questions for question forums.

**Comment by xpbliss** [comment]
But the following is ok in marshal !
package main

import (
	"encoding/xml"
	"fmt"
)

type MyThing struct {
	XMLName xml.Name `xml:"w:document"`
	O       string   `xml:"xmlns:o,attr"`
	W       string   `xml:"xmlns:wp,attr"`
}

func main() {
	var thing *MyThing = &MyThing{O: "urn:schemas-microsoft-com:office:office"}
	result, _ := xml.Marshal(thing)
	fmt.Println(string(result))
}

the output is: " <w:document xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:wp=""></w:document>" , althrough the "w:document" is not a valid XMLName.
