### ISSUE TITLE
tour: PgUp, PgDn and arrow buttons don't work in Microsoft Edge browser

### ISSUE THREAD

**Issue by jtraband** [golang/go#13002]
Context: https://tour.golang.org/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by adg** [comment]
Need someone who actually has a Windows 10 machine to address this.

**Comment by andrewaustin** [comment]
This was fixed in aef6c80 but it looks like the tour hasn't been updated since that was merged a month ago.

**Comment by adg** [comment]
I've re-deployed the tour. Let me know if the issue persists.
