### ISSUE TITLE
x/tools/cmd/godoc: detect new packages without restart in http mode

### ISSUE THREAD

**Issue by dwlnetnl** [golang/go#13007]
godoc requires as far as I can see a restart when a package is added. Changes within a package are picked up automatically.

Is this intended behaviour or just the way it has grown?

**Comment by adg** [comment]
This is the way it was designed.

**Comment by minux** [comment]
Yeah, it builds a list of packages at startup, and then
regularly rescan for new packages.

There is an option called -index_interval, which defines
the internal between reindexes, if you want to pick new
packages faster, you can reduce its value (the default
is 5m)
