### ISSUE TITLE
exec c executable causing high cpu usage 

### ISSUE THREAD

**Issue by shravan86** [golang/go#13014]
Hi 

I am trying to exec a C program(redirect.c) from my go program.
Whenever I run this from go I get a very high cpu usage (97% to 100%)
But if I run the C program on its own there is no issue. 

test.go
---------------------
package main

import (
        "fmt"
        "os"
        "os/exec"
)

func main() {
        cmd := exec.Command("./redirect", "top")
        err := cmd.Start()
        if err != nil {
                fmt.Fprintln(os.Stderr, "Error starting Cmd", err)
                os.Exit(1)
        }

        err = cmd.Wait()
         if err != nil {
                 fmt.Fprintln(os.Stderr, "Error waiting for Cmd", err)
                 os.Exit(1)
         }
}

./test.go

top output - 
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
6229 oncueli+  20   0   12764   1776   1636 R  99.9  0.0   0:10.18 redirect

./redirect top

top output - 
 5925 oncueli+  20   0    4672   1800   1396 S   0.0  0.0   0:00.00 redirect

Any idea why this is the case ?

**Comment by minux** [comment]
What does redirect.c do? I can't spot anything wrong with the Go code.

**Comment by shravan86** [comment]
Thanks minux for the response.

Redirect.c basically creates pseudo terminals and forks and execvp's a process based on the command line args it receives. Please see the code below

#define _XOPEN_SOURCE 600
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <stdio.h>
#define __USE_BSD
#include <termios.h>
#include <sys/select.h>
#include <sys/ioctl.h>
#include <string.h>


int main(int ac, char *av[])
{
	int fdm, fds;
	int rc;
	char input[1500];
	char buffer[10000];

	 // Check arguments
	 if (ac <= 1)
	 {
	 	fprintf(stderr, "Usage: %s program_name [parameters]\n", av[0]);
	 	exit(1);
	 }
	
	 fdm = posix_openpt(O_RDWR);
	 if (fdm < 0)
	 {
	 	fprintf(stderr, "Error %d on posix_openpt()\n", errno);
	 	return 1;
	 }
	
	 rc = grantpt(fdm);
	 if (rc != 0)
	 {
	 	fprintf(stderr, "Error %d on grantpt()\n", errno);
	 	return 1;
	 }
	
	 rc = unlockpt(fdm);
	 if (rc != 0)
	 {
	 	fprintf(stderr, "Error %d on unlockpt()\n", errno);
	 	return 1;
	 }
	
	 // Open the slave side ot the PTY
	 fds = open(ptsname(fdm), O_RDWR);
	
	 // Create the child process
	 if (fork())
	 {
	 	fd_set fd_in;

	 	// Parent
	     	// Close the slave side of the PTY
	       	close(fds);
	
	        while (1)
	        {
	        	// Wait for data from standard input and master side of PTY
	        	FD_ZERO(&fd_in);
	                FD_SET(0, &fd_in);
	                FD_SET(fdm, &fd_in);

	                rc = select(fdm + 1, &fd_in, NULL, NULL, NULL);
	                switch(rc)
	                {
	                	case -1 : fprintf(stderr, "Error %d on select()\n", errno);
	                                                             exit(1);
	                        default :
	                        {
	                        	// If data on standard input
	                                if (FD_ISSET(0, &fd_in))                        
					{
						rc = read(0, input, sizeof(input));
						if (rc > 0)
						{
							// Send data on the master side of PTY
							write(fdm, input, rc);
						}
						else
						{
							if (rc < 0)
							{
								fprintf(stderr, 
								        "Error %d on read standard input\n", errno);
								exit(1);

							}
						}
					}
	                        
					// If data on master side of PTY
					if (FD_ISSET(fdm, &fd_in))
					{
						rc = read(fdm, buffer, sizeof(buffer));
						if (rc > 0)
						{
							//write(1, "\n----Data chunk----\n", 21);
							// Send data on standard output
							write(1, buffer, rc);
							memset(buffer, 0, sizeof(buffer));
						}
						else
						{
							if (rc < 0)
							{
								fprintf(stderr, "Error %d on read master PTY\n", errno);
								exit(1);

							}
						}
					}
				}
			} // End switch

		} // End while
	 }
	 else
	 {

		 struct termios slave_orig_term_settings; // Saved terminal settings

		 struct termios new_term_settings; // Current terminal settings

		 // CHILD
		 // Close the master side of the PTY
		 close(fdm);

		 // Save the defaults parameters of the slave side of the PTY
		 rc = tcgetattr(fds, &slave_orig_term_settings);

		 // Set RAW mode on slave side of PTY
		 new_term_settings = slave_orig_term_settings;
		 cfmakeraw (&new_term_settings);
		 tcsetattr (fds, TCSANOW, &new_term_settings);
		 //cfsetospeed(&new_term_settings, B9600);

		 // The slave side of the PTY becomes the standard input and outputs of the child process
		 close(0); // Close standard input (current terminal)
		 close(1); // Close standard output (current terminal)
		 close(2); // Close standard error (current terminal)

		 dup(fds); // PTY becomes standard input (0)
		 dup(fds); // PTY becomes standard output (1)
		 dup(fds); // PTY becomes standard error (2)
	
		 // Now the original file descriptor is useless
		 close(fds);
	 
		 // Make the current process a new session leader
		 setsid();
	 
		 // As the child is a session leader, 
		 // set the controlling terminal to be the slave side of the PTY
		 // (Mandatory for programs like the shell to make them manage 
		 // correctly their outputs)
		 ioctl(0, TIOCSCTTY, 1);
		 struct winsize ws = {1, 1, 0, 0};
		 ioctl(0, TIOCGWINSZ, &ws);

		 // Execution of the program
		 {
			 char **child_av;

			 int i;

			 // Build the command line
			 child_av = (char **)malloc(ac * sizeof(char *));
			 for (i = 1; i < ac; i ++)
			 {
				 child_av[i - 1] = strdup(av[i]);
			 }
			 child_av[i - 1] = NULL;
			 rc = execvp(child_av[0], child_av);
	 	}
		 // if Error...
		 return 1;
	 }

	 return 0;

} // main

**Comment by shravan86** [comment]
Hi Minux,

One more update, the go version I am currently using is 1.4.2 but I see the same problem with go 1.5 as well.
I am still stuck with this issue though. Any update ?

**Comment by mdempsky** [comment]
What happens if you run

    $ ./redirect top </dev/null >/dev/null 2>/dev/null

?

**Comment by shravan86** [comment]
I dont see any output. 

But the cpu goes to 100%.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
12596 oncueli+  20   0   12768   1884   1732 R 100.0  0.0   1:52.02 redirect

**Comment by mdempsky** [comment]
That's your problem then.  Your redirect program doesn't handle being run with stdin set to /dev/null, which is the default behavior for os/exec if you don't set Stdin.
