### ISSUE TITLE
tour: urls/path handling unclear

### ISSUE THREAD

**Issue by hawaiikaos** [golang/go#13012]
Context: https://tour.golang.org/methods/14

It might just have been me, but this exercise had me stumped until I asked an experience Go coder I know. My output on localhost:4000 was "404 page not found" and I could not understand what was wrong. I check a posted solution, and mine was virtually identical. When I ran the the posted solution it too gave a 404. My friend told me that the first argument in the http.Handle function specified the path. No where was the pointed out when this was function was introduced (for the first time in this exercise). While I understand we're expected to look things up in the documentation, this is one of those times where you wouldn't know what's wrong and where to look. I recommend briefly clarifying how http.Handle works.

**Comment by sundy-li** [comment]
Cause your server is just listen to 4000, `404 page not found` is the http server donn't know which handler to handle your "/" request, see `http.Handle(pattern, handler)` function you will know

**Comment by kytrinyx** [comment]
@adg I can think of a few ways of improving this:

1. register a handler for "/" in the code before the `// your http.Handle calls here` comment, or
2. link to the documentation for `http.Handle`, or
3. add something about the first argument being the path, or
4. add something about visiting localhost:4000/string and localhost:4000/struct

**Comment by adg** [comment]
I think 2, 3, and 4 are a good first step.

**Comment by kytrinyx** [comment]
I ended up doing 2 and 4. 3 seemed redundant.
