### ISSUE TITLE
cmd/godoc: links on struct fields sometimes point to wrong package

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#13019]
In the description of DefaultTransport  for net/http (just under https://golang.org/pkg/net/http/#RoundTripper ), the definition is displayed and hyperlinked:

```
var DefaultTransport RoundTripper = &Transport{
        Proxy: ProxyFromEnvironment,
        Dial: (&net.Dialer{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
        }).Dial,
        TLSHandshakeTimeout: 10 * time.Second,
}
```

When clicking on the "Timeout" or "KeepAlive" links, it appears to try and anchor to https://golang.org/pkg/net/http/#Timeout rather than to https://golang.org/pkg/net/#Dialer

**Comment by agnivade** [comment]
Seems to be fixed now. Please reopen if you think otherwise. Also see https://github.com/golang/go/issues/9613.
