### ISSUE TITLE
encoding/base64: documentation issues

### ISSUE THREAD

**Issue by dolmen** [golang/go#13011]
The documentation for the [encoding/base64](https://golang.org/pkg/encoding/base64) package is difficult to follow because some bits are not documented or in a wrong order:
- constants `encodeStd` and `encodeURL` are [not documented](https://golang.org/pkg/encoding/base64/#pkg-constants). But they are referenced in the documentation for variables `StdEncoding` and `URLEncoding`...
- `RawStdEncoding` and `RawURLEncoding` variables are documented before `StdEncoding` and `URLEncoding` while the former are defined using the later.
- functions `NewEncoder` and `NewDecoder` are documented before the `Encoding` type and its methods.

**Comment by adg** [comment]
These are all a result of how godoc works in general. See the [godoc blog post](https://blog.golang.org/godoc-documenting-go-code) for details.

Probably a package-level example would help.
