### ISSUE TITLE
math: pure go version of math.Sqrt is broken

### ISSUE THREAD

**Issue by hydroflame** [golang/go#13013]
If you pass `math.Float64frombits(uint64(2))` to `math.Sqrt` on a machine that uses the software version (such as ppc64x https://golang.org/src/math/stubs_ppc64x.s#L87) it will end up in an infinite loop here https://golang.org/src/math/sqrt.go#L110

Unfortunatelly i don't have a ppc64x machine nearby. So I can't test this properly, however I did copy the library and manually call `math.sqrt` (the unexported, pure go version) with the argument and I have reproduced the problem.

**Comment by cespare** [comment]
Nice find, any subnormal with 0 LSB will hit this. Fixed in https://golang.org/cl/16158.

**Comment by binarycrusader** [comment]
Should this fix also be applied to src/runtime/sqrt.go#L120 ?

https://github.com/golang/go/blob/master/src/runtime/sqrt.go#L120

**Comment by cespare** [comment]
@binarycrusader yeah, I'll submit another CL
