### ISSUE TITLE
runtime: qemu-arm fails to emulate go user programs

### ISSUE THREAD

**Issue by arges** [golang/go#13024]
qemu-arm fails to emulate go user programs due to how qemu handles certain signals.

The original issue/diff that seems to solve the issue is here:
https://codereview.appspot.com/124900043/diff/60001/src/pkg/runtime/os_linux.c

The qemu code is here:
http://git.qemu.org/?p=qemu.git;a=blob;f=linux-user/signal.c;h=1141054be2170128d6f7a340b41484b49a255936;hb=HEAD#l82

Test Case:

Build this on an non-arm platform such as x86.

test.go:

```
package main

import "fmt"

func main() {
 fmt.Println("Hi")
}
```
1. GOARCH=arm go build test.go
2. qemu-arm test

This will fail with the following error:

```
qemu-arm test
fatal error: rt_sigaction failure

runtime stack:
runtime.throw(0x106d68, 0x14)
	/usr/lib/go/src/runtime/panic.go:527 +0x78
runtime.setsig(0x40, 0x6f8b0, 0x1)
	/usr/lib/go/src/runtime/os1_linux.go:297 +0x148
runtime.initsig()
	/usr/lib/go/src/runtime/signal1_unix.go:67 +0x180
runtime.mstart1()
	/usr/lib/go/src/runtime/proc1.go:717 +0xd4
runtime.mstart()
	/usr/lib/go/src/runtime/proc1.go:691 +0x84

goroutine 1 [runnable]:
runtime.main()
	/usr/lib/go/src/runtime/proc.go:28
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1036 +0x4
```

Testing with the aforementioned patch solves the issue, but I'm unsure its the best approach to solving this. I can re-propose that patch if there isn't a better solution, but this would be a very useful feature for using qemu user space emulation with go.

--chris

**Comment by rsc** [comment]
/cc @minux who wrote CL 124900043.

I'm not sure how/why that code got lost/reverted. It seems fine to put in again.

**Comment by davecheney** [comment]
Could this be backported to 1.5.2 ?

**Comment by minux** [comment]
Probably not critical enough, we never supported
running binaries under qemu user emulation before.

**Comment by rsc** [comment]
@davecheney, if you can make a case for why it's important, it's certainly
simple enough that I am OK with putting it in 1.5.2.

**Comment by davecheney** [comment]
Thanks @rsc. Canonical have gone through a lot of internal bureaucratic pain to get up to Go 1.5, if this patch could make it into 1.5.2 that would be much appreciated.

**Comment by streamnsight** [comment]
:+1: for the patch
/cc @minux 
Can someone tell which go version had the original patch? or when 1.5.2 is scheduled to be released?
I'm having the same problem trying to compile code in qemu

thanks

**Comment by rsc** [comment]
No released Go version has had this patch, as far as I understand. Go 1.5.2 should be out by the end of the calendar year, probably sooner.

**Comment by streamnsight** [comment]
@rsc thanks
I thought I understood the patch was there but was 'reversed' at some point. the very first link mentioned by @arges seems to be it, but there is no clear indication of what the version was at the time.

**Comment by mwhudson** [comment]
AIUI the fix was committed to the C version of the runtime on the dev.power64, but I don't think it ever got to master. Perhaps it got lost as part of the transition of the runtime to pure go? Doesn't really matter now anyway.

**Comment by arges** [comment]
@streamnsight FWIW I originally reproduced this issue in go1.5.1

**Comment by luxas** [comment]
I compiled a binary on ARM (`etcd`) with latest `go1.5.2`.
However, now this issue came up instead (on `amd64`):
```
# On host machine
$ qemu-arm-static etcd
Segmentation fault (core dumped)

# Running in docker
$ etcd
/build/buildd/qemu-2.0.0+dfsg/tcg/optimize.c:362: tcg fatal error
Aborted (core dumped)

$ etcd
/build/buildd/qemu-2.0.0+dfsg/tcg/tcg.c:1693: tcg fatal error
Aborted (core dumped)
```

I'm using https://github.com/moul/docker-binfmt-register for running ARM docker images on `amd64`
I'll try to reproduce what @arges did

**Comment by davecheney** [comment]
@luxas this is probably a different issue. Please open a new issue, but note that qemu is not reliable when running go programs. qemu's emulation is too glibc specific.

**Comment by luxas** [comment]
Yep, I'm fine with creating a new issue. Just said it here first, so you guys know about it.

**Comment by minux** [comment]
Yeah, I think we lost the ability to run Go binaries with
qemu-arm long time ago. tcg fatal error also seems to
suggest that it's a qemu bug. (the arm port used to be
developed with qemu-arm, but then as the port is able
to run on real hardwares, we no longer test on qemu-arm.)

The signal patch is originally intended for qemu-ppc64,
btw. I doubt that even qemu-ppc64 is able to run Go
binaries, other than the most trivial one.

As beefy arm boards are widely available, I don't think
we should invest into qemu usermode emulation any
more. It's slower than the more powerful arm boards,
and it doesn't support multithreaded programs well.
