### ISSUE TITLE
x/build: upgrade OpenBSD GCE image

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13029]
[OpenBSD 5.8](http://www.openbsd.org/58.html) was released on Oct 18, 2015, which means OpenBSD 5.6 is no longer supported upstream.  We should upgrade the builder images to 5.7.  (I'm assuming we prefer to continue testing on the oldest supported version.)

CC @bradfitz @adg @4a6f656c

**Comment by bradfitz** [comment]
So what's the plan? We drop 5.6 and only test 5.7? Or test both 5.7 and 5.8?

**Comment by mdempsky** [comment]
I was assuming drop 5.6 and only test 5.7. I'm happy to also prepare builder image scripts for 5.8, just I figured there probably aren't enough Go-relevant differences to merit additional GCE budget.

**Comment by bradfitz** [comment]
I'm not paying for it.

**Comment by 4a6f656c** [comment]
The OpenBSD builders should just run the most current stable release (5.8 at this point in time) - this is how they've been run (at least prior to moving to GCE). The most important thing to verify is that we are able to build on the most recent release. If for some reason we stopped working on the previous stable release and someone wants to run Go tip, then they can upgrade.

**Comment by mdempsky** [comment]
I think this is done now.  The openbsd/386 and openbsd/amd64 builders are now running OpenBSD 5.8.
