### ISSUE TITLE
go/printer: (a + b * *p) contracts to (a + b**p)

### ISSUE THREAD

**Issue by griesemer** [golang/go#13025]
http://play.golang.org/p/TL4gjjbxS6

This is unfortunate and probably should be fixed. Go doesn't have a ** operator so there's no parsing issue, but it is a readability issue in my mind.

**Comment by nodirt** [comment]
I will give it a try.

**Comment by cznic** [comment]
The current outcome seems perfectly logical to me. What result is proposed instead?

**Comment by griesemer** [comment]
@cznic The result is "perfectly logical" but is not great from a readability point of view as mentioned before.
```
a + b * *p
```
does seem clearer than
```
a + b**p
```
(a**b means a to the power of b in some languages, and we even use that notation in some comments to mean that).

**Comment by cznic** [comment]
The `a + b * *p` variant is far less readable for me (and subjectively ugly as it can get). The distinction between the different precedences of `+` and `*` is lost. One more 'visual' rule to learn.

What about `a + b*(*p)`?

**Comment by nodirt** [comment]
AFAIK so far gofmt without `-s` modified only whitespace, so adding parens would be a change to that.
However, `b*(*p)` looks readable to me.

**Comment by griesemer** [comment]
I've thought a bit more about this and decided that this is not worth the special handling.

For one, @cznic 's suggestion is a perfectly good Go solution: If the situation arises and readability is a concern, adding ()'s is the work-around.

Secondly, in the std lib (under GOROOT/src) there appears only a single occurrence of this pattern, and in that case spaces are present. src/runtime/map_test.go:382:26:
```
	nKeys := int(nBuckets * *runtime.HashLoad)
```

(I didn't find any occurrences under x/arch, x/build, x/net, x/oauth2, x/review, x/sys, and x/tools).
