### ISSUE TITLE
os: Create does not return error on invalid filename on Windows

### ISSUE THREAD

**Issue by tpng** [golang/go#13035]
What version of Go are you using (go version)?
`go version go1.5.1 windows/386`

What operating system and processor architecture are you using?
Windows 7 64-bit

What did you do?
```
package main

import (
	"log"
	"os"
)

func main() {
	f, err := os.Create("test:.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	if _, err := f.Write([]byte("testing")); err != nil {
		log.Fatal(err)
	}
}
```
Sorry for not using playground, still got 403 in Hong Kong.

What did you expect to see?
`:` is invalid character for file name on Windows.
Expected error on `os.Create` or `f.Write`.

What did you see instead?
An empty file named `test` is created after running the program, without any errors returned.

**Comment by davecheney** [comment]
I think what you are seeing is NTFS alternative files streams, you've created a file called test, and in the alternative stream the sting "testing" is written.

I think windows explorer doesn't show this properly, but should be able to reopen the same file you created and check for the contents. 


http://blogs.technet.com/b/askcore/archive/2013/03/24/alternate-data-streams-in-ntfs.aspx

**Comment by tpng** [comment]
Wow, that's just eye opening, thanks so much for the response.

By opening the file using the same file name, I can read back the same content.

Since it's a platform-specific feature instead, I will close the issue.
Please feel free to reopen if there's something we can do, thanks again!

**Comment by davecheney** [comment]
I think we'll have to chalk this up to a feature :)

It's only available on Windows, using NTFS.
