### ISSUE TITLE
x/mobile/bind: return nil pointer from function

### ISSUE THREAD

**Issue by scisci** [golang/go#13033]
I am building an iOS library for a swift project. I recently noticed, if I export a pointer type like so:

```
type PubStruct {
  MyThing *Thing
}
```

I get an objective c class created with getter/setters, setMyThing and myThing. However, if MyThing is nil, and I call the getter from the swift side. It doesn't get a nil pointer on the swift side, it gets, what I assume is the proxy object, a reference, so then when I try to call a method on MyThing it crashes on the go side.

Not a great explanation, but I can produce an example if necessary. But in general, does gomobile for iOS support nil pointer fields?

**Comment by hyangah** [comment]
I can take a look next week unless other volunteer fixes it before.

**Comment by scisci** [comment]
Hi @hyangah , did you have a chance to look at this at all?

It seems very similar to the problem stated here: https://github.com/golang/go/issues/13087
which was fixed for strings.

Basically need to detect if pointer is nil and return nil to the objc side.

Dan
