### ISSUE TITLE
go/printer: format x&1<<8 as x&1 << 8?

### ISSUE THREAD

**Issue by minux** [golang/go#13038]
A recent bug on sqrt (#13013) is caused by missing parenthesis
in condition for for loop:
```
    for ix&1<<shift == 0 {}
```

I suspect it might be a common error.
What if we make gofmt formats that to
```
    for ix&1 << shift == 0 {}
```
instead?

/cc: @griesemer

**Comment by griesemer** [comment]
& and << are both multiplicative operators and have the same binding strength. The suggestion implies a different binding for & than for <<. Where do we stop?

/cc: @rsc who wrote the code for the spacing around operators in go/printer.

**Comment by dsnet** [comment]
I had bug related to this in my library as well. I don't have a good solution to this, but

**Comment by rsc** [comment]
The expression formatting logic is basically unchanged from day 1 of the public release, and I think we should leave it that way. There are any number of arguments for and against minor changes, but widespread agreement is more important than any single change. As Rob said recently, gofmt particular syntax choices are no one's favorite but gofmt is everyone's favorite.

For this specific case, a goal for the expression formatting was on a particular line, operators with spaces have looser precedence than operators without. If we write this expression as x&1 << 8 that implies something about & vs << that simply isn't true.

By itself, the expression formats as x & 1 << 8. When used inside a larger expression with another precedence, it gets compressed to make clear that the outer expression has different precedence: 

	x & 1 << 8
	x&1<<8 == 0
	x&1<<8 | 2   NOT  x&1 << 8 | 2

Note in the last case especially that a special case for & vs << would produce a confusing result with respect to addition-level operators like | or +.
	
No matter what the formatting is, people will still make the occasional mistake. It's actually working very well. Let's leave it as it is.

**Comment by mdempsky** [comment]
@minux What about making cmd/vet warn that "a&b<<c == 0" and "a&b<<c != 0" are probably missing parentheses?  They seem very unlikely to occur legitimately.

**Comment by minux** [comment]
Yeah, I think cmd/vet check would be nice.
