### ISSUE TITLE
tour: [No playground in this page.]

### ISSUE THREAD

**Issue by roxxette** [golang/go#13048]
Context: https://tour.golang.org/concurrency/7

No playground in this page.

**Comment by davecheney** [comment]
It flashes briefly on the RHS, then disappears.

**Comment by dominikh** [comment]
IIRC, there's not meant to be an editor on that page, as there's nothing to code.

**Comment by rakyll** [comment]
It's a description page. You need to start coding at the next page, hence no playground.
