### ISSUE TITLE
runtime: netpollblock hang

### ISSUE THREAD

**Issue by guotie** [golang/go#13049]
goroutine 85 [IO wait, 84 minutes]:
net.runtime_pollWait(0x2aaaaaab0368, 0x77, 0xc82000a1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201600d0, 0x77, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc8201600d0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).Write(0xc820160070, 0xc928a98000, 0x156, 0x1000, 0x27, 0x2aaaaaaab050, 0xc82000a1a0)
        /usr/local/go/src/net/fd_unix.go:318 +0x414
net.(*conn).Write(0xc820034028, 0xc928a98000, 0x156, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0xe4
bufio.(*Writer).flush(0xc9294c4240, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:562 +0xe0
bufio.(*Writer).Flush(0xc9294c4240, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:551 +0x2d
github.com/guotie/stomp.(*Writer).Write(0xc8200340a8, 0xc924bd5ec0, 0x0, 0x0)
        /root/go/src/github.com/guotie/stomp/writer.go:100 +0xb4
github.com/guotie/stomp.processLoop(0xc8201600e0, 0xc8200340a8)
        /root/go/src/github.com/guotie/stomp/conn.go:553 +0x1520
created by github.com/guotie/stomp.Connect
        /root/go/src/github.com/guotie/stomp/conn.go:210 +0xd6d

**Comment by guotie** [comment]
goroutine 87 [IO wait]:
net.runtime_pollWait(0x2aaaaaab02a8, 0x72, 0xc82000a1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820161950, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820161950, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201618f0, 0xc92b57e000, 0x1000, 0x1000, 0x0, 0x2aaaaaaab050, 0xc82000a1a0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820035270, 0xc92b57e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc92b58b4a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc92b58b4a0, 0xc92b57e10a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc92b58b4a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:406 +0xa9
github.com/guotie/stomp.(*Reader).readLine(0xc820035278, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/guotie/stomp/reader.go:135 +0x4e
github.com/guotie/stomp.(*Reader).Read(0xc820035278, 0xc92b58b7a0, 0x0, 0x0)
        /root/go/src/github.com/guotie/stomp/reader.go:43 +0x45
github.com/guotie/stomp.readLoop(0xc820161a40, 0xc820035278)
        /root/go/src/github.com/guotie/stomp/conn.go:250 +0x51
created by github.com/guotie/stomp.Connect
        /root/go/src/github.com/guotie/stomp/conn.go:208 +0xd3e

**Comment by ianlancetaylor** [comment]
What program are you running?  What operating system?  What version of Go?  Is this easy to reproduce?

Are you sure this is a bug?  If there is no network activity, then it is normal for this goroutine to wait.

**Comment by guotie** [comment]
OS: Linux; CentOS 6.4 x64
Go: 1.5.1
This is not easy to reproduce.

I use stomp to connect activeMQ, I'm sure the network is Ok and there should be data to send/recv, but the program hangs.

I use the net lib is always ok, but the stomp lib has occurs sevral times, I'm not sure if it is a golang's bug, but the stack shows it hangs at golang libary.

**Comment by guotie** [comment]
stomp: https://github.com/guotie/stomp

**Comment by ianlancetaylor** [comment]
In order to fix any possible bug, we need more information.  It is entirely normal for a goroutine reading from a descriptor to hang at that point waiting for more data on the socket.

For example, please set the environment variable GOTRACEBACK=2 and show us the entire stack dump of the program when it is hanging.  It might also help to see the output of strace -f for a few minutes before the hang.

**Comment by guotie** [comment]
I reviewed activemq call stack, I think this should be activemq bug.
