### ISSUE TITLE
tour: [Example step mismatch]

### ISSUE THREAD

**Issue by motyar** [golang/go#13041]
Context: http://tour.golang.org/moretypes/20

Left and righ sides seems mismatch for many steps

See these two screenshots
https://i.imgur.com/b81M7MO.png ( http://tour.golang.org/moretypes/19 )
https://i.imgur.com/b81M7MO.png ( http://tour.golang.org/moretypes/20 )

Issues seems after the side swap.

**Comment by minux** [comment]
I just visited http://tour.golang.org/moretypes/20,
and I didn't see the problem.

Could you please try again? (with incognito mode
to make sure it's not a client side thing)

**Comment by motyar** [comment]
Yes. works well for me in other browsers.
Its an issue, even if its a client side issue.

I was just making lot of changes to example and running and now I have this mismatch.

Thanks
