### ISSUE TITLE
x/text/encoding/charmap: add aditional codepages

### ISSUE THREAD

**Issue by quinte17** [golang/go#13043]
add more codepages from
https://msdn.microsoft.com/en-us/goglobal/bb964653
to
golang.org/x/text/encoding/charmap

my discrete interest is in OEM 852
maybe it's possible to grab it via the maketables.go script

i havnt found a valid MIB, but maybe there
golang.org/x/text/text/encoding/internal/identifier/mib.go
need to be one added too.

**Comment by andybalholm** [comment]
Currently, the only OEM code page supported is 437, the U.S. default. The data for it is hard-coded in maketables.go. I think it would be fairly practical to have maketables.go fetch the code page data from MSDN (or maybe there is a better source), just like it does from WHATWG for the others.

I did find the MIB in mib.go.

@nigeltao, should we add support for the code pages listed on https://msdn.microsoft.com/en-us/goglobal/bb964655 that are not included yet? Or should that be left for third-party packages?

**Comment by nigeltao** [comment]
Adding support to x/text/encoding/charmap for the code pages listed on https://msdn.microsoft.com/en-us/goglobal/bb964655 SGTM.

**Comment by quinte17** [comment]
in addition you could make encoding.charmap.charmap a public api. so an application could just bring its own charmap easily and use the transfer api transparently.

**Comment by andybalholm** [comment]
I've sent a CL for review: https://go-review.googlesource.com/#/c/16364/
