### ISSUE TITLE
Programmatically import packages 

### ISSUE THREAD

**Issue by h2non** [golang/go#13047]
I suppose that this feature is not supported due to the runtime bootstrap phases and I can figure out that there're a considerable number of constraints to do it, however I would like to open this feature, since in some scenarios, such as loading dynamically a bunch of plugins, could be really useful.

I've seen that this feature is not new and you probably have it in mind, but I cannot see it in Github.

in terms of API, something similar to `src/go/importer` package would be great, but supporting the compilation phase.

**Comment by bradfitz** [comment]
See https://golang.org/s/execmodes

There is ongoing work in this area for the past two releases.
