### ISSUE TITLE
sqrt fix broke arm softfloat

### ISSUE THREAD

**Issue by davecheney** [golang/go#13040]
The fix for #13013, 22d4c8b broke the arm softfloat code. Looks like it is going into an infinite loop.
```
panic: test timed out after 15m0s

goroutine 65 [running]:
testing.startAlarm.func1()
	/workdir/go/src/testing/testing.go:703 +0x10c
created by time.goFunc
	/workdir/go/src/time/sleep.go:129 +0x34

goroutine 1 [chan receive]:
testing.RunTests(0x1c7a9c, 0x23d4b0, 0x3d, 0x3d, 0x1)
	/workdir/go/src/testing/testing.go:562 +0x618
testing.(*M).Run(0x10437f74, 0x12460)
	/workdir/go/src/testing/testing.go:494 +0x6c
main.main()
	math/_test/_testmain.go:300 +0x118

goroutine 55 [running]:
	goroutine running on other thread; stack unavailable
created by testing.RunTests
	/workdir/go/src/testing/testing.go:561 +0x5ec
FAIL
	math	900.169s
```
http://build.golang.org/log/14252e5babfa08a3b0d625a92b7efee9a54c770d

**Comment by cespare** [comment]
@davecheney Isn't that hitting the copy of sqrt that lives in runtime for arm softfloat? It would make sense that it's hanging on the test case I added, then.

I copied the fix to the runtime sqrt in [CL 16291](https://go-review.googlesource.com/#/c/16291/). The trybots were happy as of that commit.

**Comment by davecheney** [comment]
@cespare good point, you were correct that CL 16291 fixed this, 

http://farmer.golang.org/temporarylogs?name=linux-arm-arm5&rev=fb7178e7cc219062efe7d5da5df4f85b01b0f8ac&st=0xc83251c400
