### ISSUE TITLE
tour: No "Foo"s in the code, little confusing

### ISSUE THREAD

**Issue by iHani** [golang/go#13045]
Context: https://tour.golang.org/basics/3

The left side talks about Foo, FOO and foo but there is none of them in the code in the right side!

Thanks

**Comment by kytrinyx** [comment]
I'll tackle this one, @adg

**Comment by kytrinyx** [comment]
I finally looked at this, and this is page 3. We haven't talked about variables or constants or functions yet, so I don't see where it would make sense to add any foos as constants or variables.

I thought about using other constants in the math package to supplement the `math.pi` -> `math.Pi` thing, but there are no useful acronyms that would give us an all caps one (`math.E` almost qualifies, but the lack of subsequent letters is ambiguous).

The time package has some, but they're a bit cryptic if you're not familiar with the whole standards thing (e.g. `time.RFC822`).

The only other acronym I can think of is `io.EOF`.

What do you think--abandon the foo, Foo, and FOO for some real constants, adding (somewhat spurious) lines to the code example and change the text to match?

**Comment by adg** [comment]
Maybe just pi, Pi, and PI ?

**Comment by kytrinyx** [comment]
Hah. Yeah, or that :) Damn, you're good!
