### ISSUE TITLE
go test breaks vendoring because of too aggressive dependency checking

### ISSUE THREAD

**Issue by rasky** [golang/go#13059]
it looks like `go test` fails for missing dependencies it shouldn't care about. For instance:

main.go
```go
package main
import "a"
func main() {
	a.Foo()
}
```

vendor/a/a.go
```
package a
func Foo() {}
```

vendor/a/example/b.go
```go
package main
import "missing"
```

When creating the above structure, with `GO15VENDOREXPERIMENT=1`, `go build` succeeds, but `go test ./...` fails with:

```
vendor/a/example/b.go:3:8: cannot find package "missing" in any of:
	/Users/rasky/Sources/go/src/gotestbug/vendor/missing (vendor tree)
	/usr/local/Cellar/go/1.5/libexec/src/missing (from $GOROOT)
	/Users/rasky/Sources/go/src/missing (from $GOPATH)
```

The example simulates the vendoring of a third-party library `a` which contains an example of usage in a subdirectory; this example includes other third-party libraries that are not required by `a` itself (just for the sake of the example), and thus are not being vendored.

There are other real-world cases in which a package can contain subdirectories with main packages which are not part of the package proper, but just additional stuff: for instance, some packages contain additional command-line applications that can be built and installed separately from the package itself. When the package is imported in a vendor tree, these applications should be ignored.

Can you please clarify why `go test` fails and if you consider this a bug?

**Comment by minux** [comment]
go test ./... means to test any packages found under the current directory,
including main packages.

And before testing a package, it has to build it.

This is working as intended. Don't use ./... if you don't intend to test
every package.

**Comment by rasky** [comment]
Well how do you suggest a Go application test its packages, when using vendoring?

**Comment by bradfitz** [comment]
For asking questions, please use one of the forums: https://golang.org/wiki/Questions
