### ISSUE TITLE
cmd/compile: retire/repair disabled compiler behavior tests

### ISSUE THREAD

**Issue by dr2chase** [golang/go#13068]
SSA has different behavior from the previous backend, and some tests probe this behavior.
In some cases this can be repaired by changes to SSA (i.e., it does the same thing, but doesn't log it or logs it differently) and in other cases SSA just plain does things differently (for example, it removes nil checks very aggressively and so the nil checks emitted do not match).  To allow the tests to run successfully with SSA both enabled and disabled, some of them must be disabled until this is resolved.

Affected tests:
```
live.go
live2.go
nilcheck.go
nilptr3.go
sliceopt.go
```

See https://golang.org/cl/16299

**Comment by rsc** [comment]
Ping @dr2chase

**Comment by dr2chase** [comment]
`live.go` is modified into `live_ssa.go`; there's no way to combine these.
`live2.go` can be re-enabled.
`nilcheck.go` is reenabled already.
`nilptr3.go`  is modified into `live_ssa.go`; there's no way to combine these.
`sliceopt.go` needs #15086 .

**Comment by randall77** [comment]
live_ssa.go -> live.go and nilptr3_ssa.go -> nilptr3.go happened after the legacy backend was deleted.
live2.go and nilcheck.go are enabled.
sliceopt.go has been deleted, it really only made sense for the legacy backend.

(David, live.go has ppc64 disabled - can we reenable it?)

**Comment by dr2chase** [comment]
Not yet:
```
drchase@keplerppc1:~/work/go/test$ go run run.go -- live.go
# go run run.go -- live.go

live.go:305: no match for `live at call to mapaccess1: autotmp_[0-9]+$` in:
	live.go:305: live at call to g18: autotmp_59
	live.go:305: live at call to mapaccess1: autotmp_53 autotmp_59
live.go:307: no match for `live at call to mapaccess1: autotmp_[0-9]+$` in:
	live.go:307: live at call to g18: autotmp_59
	live.go:307: live at call to mapaccess1: autotmp_55 autotmp_59 autotmp_60
Unmatched Errors:
live.go:305: live at call to g18: autotmp_59
live.go:305: live at call to mapaccess1: autotmp_53 autotmp_59
live.go:307: live at call to g18: autotmp_59
live.go:307: live at call to mapaccess1: autotmp_55 autotmp_59 autotmp_60
live.go:308: live at call to g18: autotmp_59 autotmp_60

FAIL	live.go	0.115s
exit status 1
```
