### ISSUE TITLE
database/sql: missing row fetch size and other optimizations for large dataset

### ISSUE THREAD

**Issue by asambeka** [golang/go#13067]
I have been trying to work with large datasets in Oracle and mySQL DBs. There are around 20 million records in these databases. Idea was to use golang to pull and export them as JSON. While I was able to  use golang concurrency for export, I realized performance for pull from DB was VERY bad. Here is an estimate how bad it is:
golang (default driver setting): 30 min for 10 million (running next/scan in loop)
I was able to find configuration options for one of the Oracle drivers (gopkg.in/rana/ora.v3) and after setting **PrefetchRowCount** to 50K, I was able to reduce time taken to 5 min.

Big question, **why is there no standard way to provide hint to underlying driver in database/sql package about configuration parameters**(Or am I missing something here)? I think this is a big implementation issue, and will restrict golang use to very premetive scenarios around  databases. This will also encourage non stadard usage of drivers. PrefetchRowCount is just one example, and there are many others including language (NLS settings) etc. Both ODBC and JDBC specifications have very well articulated and provide lot of options for performance tuning, and other aspects around data retrieval. Having atleast some of those will certainly make life easier.

**Comment by bradfitz** [comment]
Go prefers to start with simplicity instead of preemptively adding knobs. That explains why no explicit knobs yet exist.

But in this case it seems a potential knob already does exist: the database DSN string. Your driver could support a hint in there.

Or your driver could notice the result set is huge and buffer more, if it's buffering at all.

Before we do anything, I'd want to hear from the driver author first and make sure they've done the optimizations on their side.

**Comment by kritika1439** [comment]
hi,
please tell how to set PrefetchRowCount in golang by using the rana driver

**Comment by asambeka** [comment]
You can use StmtCfg to set prefetch memory and row count in rana/ora.

-Ashwin

**Comment by bradfitz** [comment]
Please take questions to the mailing list or other forums: https://golang.org/wiki/Questions

**Comment by kardianos** [comment]
@asambeka I'm still feeling out the best practices here. But the advice I would like you to consider would be to add any driver knobs you need into the context value after the driver adds support for the driver. For instance, your PrefetchRowCount property could be set at some lower request handler as a default, and by the time it reaches your request, you just pass it in normally.

Context methods will be supported in go1.8+.

**Comment by kardianos** [comment]
In go1.9 drivers will be able to implement driver.NamedValueChecker on the driver.Conn. When inspecting the arguments it can determine if the argument is some type of option value and pass back driver.ErrRemoveArgument so it will not be passed into the query argument list, but still use it on the connection to configure it in some way.

I believe this should fully resolve this issue.
