### ISSUE TITLE
cgo: sanitizers test causes a crash when building Go on Red Hat 4.4.7-11

### ISSUE THREAD

**Issue by sergeyarseev** [golang/go#13065]
Trying to build Go from source (current master branch) on Red Hat Linux 4.4.7-11 (gcc version 4.4.7 20120313) with src/all.bash results in a crash during cgo tests:

\##### ../misc/cgo/testshared
PASS
ok      _/localdisk/sarseev/gointel/golang/misc/cgo/testshared  10.066s

\##### ../misc/cgo/testasan

\##### ../misc/cgo/testsanitizers
\# runtime/msan
cc1: error: unrecognized command line option "-fsanitize=memory"
FAIL: msan
\# runtime/msan
cc1: error: unrecognized command line option "-fsanitize=memory"
FAIL: msan2
2015/10/27 14:02:27 Failed: exit status 1

**Comment by ianlancetaylor** [comment]
Do you have clang installed on your system?  Which version?

What happens if you run `cc -fsanitize=memory` ?

**Comment by sergeyarseev** [comment]
Clang is not installed.
cc says "cc1: error: unrecognized command line option "-fsanitize=memory""

**Comment by ianlancetaylor** [comment]
Thanks.  I don't understand why the tests at the start of test.bash are not causing the test to be skipped.  Can you cd to misc/cgo/testsanitizers and run "bash -xv test.bash"?

**Comment by sergeyarseev** [comment]
-bash-4.1$ bash -xv test.bash
\#!/usr/bin/env bash
\# Copyright 2015 The Go Authors. All rights reserved.
\# Use of this source code is governed by a BSD-style
\# license that can be found in the LICENSE file.

\# This directory is intended to test the use of Go with sanitizers
\# like msan, asan, etc.  See https://github.com/google/sanitizers .

set -e
\+ set -e

\# The sanitizers were originally developed with clang, so prefer it.
CC=cc
\+ CC=cc
if test "$(type -p clang)" != ""; then
  CC=clang
fi
\++ type -p clang
\+ test '' '!=' ''
export CC
\+ export CC

if $CC -fsanitize=memory 2>&1 | grep "unrecognized" >& /dev/null; then
  echo "skipping msan test: -fsanitize=memory not supported"
  exit 0
fi
\+ cc -fsanitize=memory
\+ grep unrecognized

\# The memory sanitizer in versions of clang before 3.6 don't work with Go.
if $CC --version | grep clang >& /dev/null; then
  ver=$($CC --version | sed -e 's/.* version \([0-9.-]*\).*/\1/')
  major=$(echo $ver | sed -e 's/\([0-9]*\).*/\1/')
  minor=$(echo $ver | sed -e 's/[0-9]*\.\([0-9]*\).*/\1/')
  if test $major -lt 3 || test $major -eq 3 -a $minor -lt 6; then
    echo "skipping msan test; clang version $major.$minor older than 3.6"
    exit 0
  fi
fi
\+ cc --version
\+ grep clang

go run msan.go
\+ go run msan.go
\# command-line-arguments
cc1: error: unrecognized command line option "-fsanitize=memory"


I guess that I found where the error is (and I also made a small mistake). It's because cc needs to be given a file ("cc helloworld.c -fsanitize=memory") to say "unrecognized command line option". That's how I tested it in my previous comment. If you just run "cc -fsanitize=memory", it says: "cc: no input files" instead.

**Comment by ianlancetaylor** [comment]
Thanks.  Does the file have to exist?  That is, what happens if you run `cc -fsanitize=memory doesnotexist.c`?

**Comment by 0xmohit** [comment]
Related thread: <https://groups.google.com/forum/#!topic/Golang-nuts/2LuHToTKN8k>

It appears that

    if $CC -fsanitize=memory 2>&1 | grep "unrecognized" >& /dev/null; then

could be written as

    if $CC -fsanitize=memory /dev/null 2>&1 | grep -q "unrecognized"; then

This would cause `cc` not to complain about the missing file.  The `-q` option to `grep` is specified by [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/grep.html); although this is probably unrelated to the issue at hand.

**Comment by sergeyarseev** [comment]
The file has to exist.

-bash-4.1$ cc ewqewq.c -fsanitize=memory
cc: ewqewq.c: No such file or directory
cc: no input files

/dev/null doesn't work also:

-bash-4.1$ cc -fsanitize=memory /dev/null
/dev/null: file not recognized: File truncated
collect2: ld returned 1 exit status

**Comment by ianlancetaylor** [comment]
Thanks.  Could you try the patch in https://golang.org/cl/16589 and see if it fixes the problem?
