### ISSUE TITLE
x/build/cmd/coordinator: make all logs URLs permanent

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13076]
No matter what scary text I put in the URL, people still link to farmer.golang.org's emphemeral build logs.

Perhaps farmer.golang.org should start recording all its streamed state to GCS and make sure that all emphemeral build log URLs have enough information in them to fetch the old logs from GCS if the build is not currently in progress.

**Comment by dmitshur** [comment]
I'll close this 2015 issue in favor of #34119, which supersedes it.

This issue describes fairly low level implementation details, and coordinator may have changed since 2015. We can open new specific issues to track this work as needed.
