### ISSUE TITLE
strings.Split returning a slice of length 1 even if string is empty

### ISSUE THREAD

**Issue by Dal-Papa** [golang/go#13075]
Hey guys,

I just discovered with a coworker that `strings.Split` returns a slice of length 1 even if the slice itself is empty in the case of `s` being empty. 

You then can't really figure out by len(slice) if your string was properly parsed or not, sometimes even resulting in such code : `slice[len(slice) -1]` triggering a panic. 

I'm updating `strings.go` l282 to this : `if n == 0 || len(s) == 0 {` 

I wanted to get a green light before doing the commit process. 

Cheers.

**Comment by cespare** [comment]
That's intentional and correct, and the included example even shows this behavior.

**Comment by Dal-Papa** [comment]
I see, then we need to check the length of the first element. 

I didn't know it was intentional. 

Thank you anyway !
