### ISSUE TITLE
project: establish a Code of Conduct

### ISSUE THREAD

**Issue by adg** [golang/go#13073]

**Comment by adg** [comment]
The proposal is submitted: https://golang.org/design/13073-code-of-conduct

Please send all comments or questions directly to adg@golang.org.

(This is a departure from the typical proposal process, since discussions Around Codes of Conduct tend to devolve quickly. By restricting the discussion Of this proposal to 1:1 conversations between myself and members of the Community, I hope to better hear everyone’s specific concerns without generating unnecessary noise.)

**Comment by adg** [comment]
A second revision of the proposal is now available: https://golang.org/design/13073-code-of-conduct

**Comment by dvyukov** [comment]
LGTM

**Comment by randall77** [comment]
LGTM

**Comment by josharian** [comment]
LGTM

**Comment by rsc** [comment]
LGTM, and thanks to you and everyone else for all the effort that went into making this a reality.

**Comment by dr2chase** [comment]
LGTM

**Comment by mdempsky** [comment]
LGTM

**Comment by crawshaw** [comment]
LGTM

**Comment by alandonovan** [comment]
LGTM

**Comment by hyangah** [comment]
LGTM

**Comment by adg** [comment]
Fixed by 90ffb7c806c049ececeb2c6ce7fa0dbb056ae4ca
