### ISSUE TITLE
Round off error in `strconv`

### ISSUE THREAD

**Issue by ilayaraja89** [golang/go#13083]
The rounding of floating point values performs strange for some values. When a float value, with 5 in the 3rd decimal place and 2 or 4 in the 2nd decimal place, is rounded to 2 decimal places, it is NOT properly rounded off.

This is the code used:
```go
package main

import "fmt"
import "strconv"

func main() {
	// Works, expected 74.61
	fmt.Println(strconv.FormatFloat(74.605, 'f', 2, 64))

	// Not works, expected 74.63
	fmt.Println(strconv.FormatFloat(74.625, 'f', 2, 64))	

	// Not works, expected 74.65
	fmt.Println(strconv.FormatFloat(74.645, 'f', 2, 64))	

	// Works, expected 74.67
	fmt.Println(strconv.FormatFloat(74.665, 'f', 2, 64))
}
``` 

PS:
-  What version of Go are you using (go version)?
go version go1.3.3 linux/amd64
- What operating system and processor architecture are you using?
Ubuntu x86_64 GNU/Linux

**Comment by bradfitz** [comment]
I don't believe this is a bug in Go. You're also using an old version of Go. I recommend you bring this to a forum for discussion instead of the bug tracker where people can discuss floating point: https://golang.org/wiki/Questions
