### ISSUE TITLE
x/mobile/bind: returning an empty string from go causes force unwrapping of nil on swift side

### ISSUE THREAD

**Issue by scisci** [golang/go#13087]
If an exported go function with a string return type, returns an empty string. It actually ends up sending nil to the objective-c side. 

However if one tries to read the string from the swift side it results in an error because it attempts to force unwrap a nil value. There also doesn't seem to be any way to test for nil before accessing the property.

This results in having to modify functions to return the string and also an error if that string is empty, and the client side first checks the error and can then read the string, which is none to convenient

I am using this direclty in Swift 2.0 and not using objective-c, so it could be an issue there.

**Comment by rakyll** [comment]
/cc @hyangah 

Returning a `(NSString*)nil` is a bug. We should never override the meaning of an empty string by converting into nil.

Once we return empty NSStrings, the Swift bug will be resolved.
