### ISSUE TITLE
Getting 'missing return at end of function' after panic / in dead code

### ISSUE THREAD

**Issue by dtylman** [golang/go#13094]
Can't compile a function with no return after panic.
IMHO, adding the 'panic' clause after 'throw' in the following example is a dead code and should be omitted. 

```go
package main
import "fmt"


func throw(message string){
	panic(message)
}

func foo(value int) int{
	switch value {
	case 1:
		return 2
	case 3:
		return 4
	}
	throw("Can't do this!")
	//panic("Can't do this!") // uncomment this to compile.
}

func main() {
	fmt.Printf("Hello world: %v", foo(1))

}

```
**expected**: code compiles.
**got**: ```./test.go:18: missing return at end of function```
*version:*
go version go1.5.1 darwin/amd64
go version go1.5.1 windows/amd64

**Comment by griesemer** [comment]
Working as intended. The compiler doesn't look into function calls (throw) to determine if a function terminates or not. The spec rules are pretty clear about this.
