### ISSUE TITLE
DOC: Golang time format layout confuse

### ISSUE THREAD

**Issue by netroby** [golang/go#13102]
I am rarely hard to understand the golang time format layout.

would you please explain more detail about how to format time with golang.

```
 $ go run tf.go 
2015-10-30 13:23:18
2015-23-15 13:10:30
30010-10-10 1030:10:10

```
What the hell, why golang not format time right for us
The source code
```golang
package main

import "fmt"
import "time"

func main() {
	p := fmt.Println

	// Here's a basic example of formatting a time
	// according to RFC3339, using the corresponding layout
	// constant.
	p(time.Now().Format("2006-01-02 15:04:05"))
	p(time.Now().Format("2006-04-06 15:01:02"))
	p(time.Now().Format("2001-01-01 12:01:01"))

}
```

**Comment by netroby** [comment]
For example , how to format 
YYYY-mm-dd HH:ii:ss like php

```
$ php -r "echo date('Y-m-d H:i:s');"
2015-10-30 13:27:18
```

**Comment by adg** [comment]
The format string always has to be this time `Mon Jan 2 15:04:05 -0700 MST 2006`.

To format the string the way you want it, `"2006-01-02 15:04:05"` is the correct format string.
