### ISSUE TITLE
time: Format() produce some strange string

### ISSUE THREAD

**Issue by fffw** [golang/go#13103]
Similar issue might already be logged but hope this can be a useful test case.

Version: both 1.5.1 and 1.4.3

Example code at http://play.golang.org/p/R9dgBT5joU

`time.Now().Format("Fri, 22 Oct 2015 11:52:25 GMT")` produces something like
> Fri, 1010 Oct 101100 1111:0010:1000 GMT

**Comment by minux** [comment]
the format string needs to specify the formatting for
a fixed date:
Mon Jan 2 15:04:05 MST 2006

**Comment by fffw** [comment]
I looked at the doc several times before created the issue, but as a non-native English speaker, I didn't get your point until I read the doc over and over again for 15 minutes. It's REALLY REALLY counter-intuitive to generate some random string for invalid input.
