### ISSUE TITLE
New function needed:transfer with different character encoding standards

### ISSUE THREAD

**Issue by AnotherGoogleFans** [golang/go#13105]
There are many character encoding standards such as UNICODE\UTF-8\UTF-16\UTF-32\UCS\ANSI\GBK\GB2312 and so on. The default that in golang is utf-8. But many times we received others, or we need to send with others , and it's hard for us to deal with. I wonder if golang can support official way to deal with the problem, that means, we can translate the character from one encoding way to another.

**Comment by defia** [comment]
https://godoc.org/golang.org/x/text/encoding

**Comment by AnotherGoogleFans** [comment]
Thanks @defia 
That works, but I think there should be a offical way instead of third-part way to solve this problem.

**Comment by rsc** [comment]
golang.org/x/text/encoding is not third-party. It is written by the same contributors who write the standard library. It's the right answer, it's the official way, and it's well supported.
