### ISSUE TITLE
proposal: x/net/context/ctxhttp: Context-aware HTTP handlers

### ISSUE THREAD

**Issue by kyleconroy** [golang/go#13115]
Proposal: add a context-aware handler interface that is similar to/mirrors `http.Handler` and `http.HandlerFunc`

```go
type Handler interface {
    ServeHTTP(context.Context, http.ResponseWriter, *http.Request)
}

type HandlerFunc func(context.Context, http.ResponseWriter, *http.Request)

// ServeHTTP calls f(w, r).
func (f HandlerFunc) ServeHTTP(c context.Context, w http.ResponseWriter, r *http.Request) {
    f(c, w, r)
}
```

In the future, we’d also want to add a ServerMux that implements the above interface. Thoughts?

**Comment by bradfitz** [comment]
This is a dup of rejected https://go-review.googlesource.com/#/c/15620/

Conversation continues in #13021 (moving context to std).
