### ISSUE TITLE
gccgo:  wrong install directory used for go get golang.org/x/tools/cmd/cover and others

### ISSUE THREAD

**Issue by laboger** [golang/go#13112]
The install directory for the gccgo-built go tool when used for tools from golang.org/x/tools/cmd/ is not correct.

For example on ppc64le using gccgo from gcc trunk, the following command:

go get golang.org/x/tools/cmd/cover

attempts to install the 'cover' tool in pkg/tool/linux_ppc64le/ under the gccgo install directory, when it should go into libexec/gcc/powerpc64le-linux/6.0.0, which is identified by the string found in runtime.GCCGOTOOLDIR.

I have a patch to fix this which I will post shortly.

**Comment by laboger** [comment]
https://go-review.googlesource.com/16516 fixes this.

**Comment by laboger** [comment]
Will this get into gcc trunk and if so can it be backported to gcc 5 so it makes it into 5.3?

**Comment by ianlancetaylor** [comment]
Fixed on mainline and GCC 5 branch.
