### ISSUE TITLE
tour: Concurrency: Exercise Web Crawler would profit from hint about mutex

### ISSUE THREAD

**Issue by bernhardreiter** [golang/go#13110]
Hi,
just took the tour, it was nice. 

I have a suggestion for the last exercise-web-crawler.go.
I could solve the task to run the crawlers in parallel using the channels,
but the task to only crawl urls once could need more hints, it was too hard.

As I am only a beginner once, I'm reporting it.

As far as I say, solving the task of "crawling urls only onces" requires either
*  two way communication to ask via a channel (which was not explained
before and probably would need a way to build individual channels to each goroutine or a way to have them all ask over one common channel) if an url has already been crawled or
* a mutex like mechanism to access a common map 

Both have not been explained in the tour before. The reference solution uses the mutex.
Now I could have read up on the "sync" packages to use a mutex, but because
page concurrency/1 said that this was rarely necessary, I expected a higher level way to exist.
Which I could not find in a reasonable timeframe so I gave up and looked at the solution in the source.

My suggestions are:
* Add a hint that you should read up on the "sync" package and use a mutex for the second task.
* Possibly hint at a pattern how two goroutines could ask each other something over a channel (if such a pattern exist) in the channel part.
* Consider adding the anounymous function that is used in the tour/solutions/webcrawler.go
file to start a go routine to a previous example, I found it non-obvious when looking at webcrawler.go

tour master commit 1c790b9f8bfefe44f33fbc9aacf5a6bc06027321 Date:   Tue Oct 20 14:55:43 2015 -0700
Chromium with go1.5.1 in i386 in Debian GNU/Linux.

Best Regards,
Bernhard

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Hi @bernhardreiter, thanks for your feedback!

I'm going to try to add a couple of slides mentioning `sync.Mutex` before that exercise and a hint on the exercise description too.

Also, awesome job finishing the tour!! Your rock :+1:

**Comment by campoy** [comment]
Proposed change: https://go-review.googlesource.com/17403

**Comment by bernhardreiter** [comment]
Hi Francesc,

thank for maintaining the gotour. :)

Took a quick look at your proposed change:
* It is good to have sync.Mutex explained. Now the solution of the
  last exercise should be doable.
* The mention on the last exercise might be a bit too indirect.
  Instead of "but maps are not safe for concurrent use!", maybe
  be "but maps alone are not safe for concurrent use!" to strongly
  suggest that sync.Mutex can secure maps, so they can be used
  if used properly.

Best,
Bernhard

**Comment by campoy** [comment]
CL updated
