### ISSUE TITLE
cmd/cgo: compiler error for C unsigned short is wrong.

### ISSUE THREAD

**Issue by hydroflame** [golang/go#13129]
When trying to assign a variable of the wrong type to a C.ushort. The compiler will emit the error `cannot use <var> (type <var type>) as type C.unsignedshort in assignment`. However `C.unsignedshort` isn't even a real type. It should say `C.ushort`

short test program:
    package main
    
    import "C"
    
    func main() {
    	var x C.ushort
    	y := 5
    	x = y // ./bug.go:8: cannot use y (type int) as type C.unsignedshort in assignment
    	//var z C.unsignedshort // could not determine kind of name for C.unsignedshor
    }

**Comment by mdempsky** [comment]
@hydroflame Are you still able to reproduce this?  If so, can you provide additional details about your build environment (at least Go version and OS).

I can't reproduce this issue at master (e36bf614c) on linux/amd64 (Ubuntu 14.04):

    $ go build bug.go
    # command-line-arguments
    ./bug.go:8: cannot use y (type int) as type C.ushort in assignment

    $ cat bug.go
    package main
    
    import "C"
    
    func main() {
        var x C.ushort
        y := 5
        x = y // ./bug.go:8: cannot use y (type int) as type C.unsignedshort in assignment
        //var z C.unsignedshort // could not determine kind of name for C.unsignedshor
    }

**Comment by mdempsky** [comment]
Ah, nevermind, I can repro with Clang:

    $ CC=clang-3.5 go build bug.go
    # command-line-arguments
    ./bug.go:8: cannot use y (type int) as type C.unsignedshort in assignment

**Comment by mdempsky** [comment]
Comparing the names in cmd/cgo/gcc.go:dwarfToName and https://github.com/llvm-mirror/clang/blob/master/lib/Basic/TargetInfo.cpp#L107, it looks like the only differences are that Clang uses "short" and "unsigned short" instead of "short int" and "short unsigned int", respectively.

"short" doesn't need to be mapped, so that just leaves "unsigned short".

**Comment by hydroflame** [comment]
10:tornago hydroflame$ go version
    go version go1.5 darwin/amd64

    OSX 10.11.1
