### ISSUE TITLE
tour: Cursor keys on external iPad keyboard don't work in code editor

### ISSUE THREAD

**Issue by ashb** [golang/go#13130]
Context: https://tour.golang.org/basics/4

I was attempting to learn go during my morning commute on my iPad and found that my external keyboard does not work fully in the code input area - typing works and deleting work as expected, but the arrow keys do not move the cursor around.

I tried this in both Safari and Chrome (which may or may not make a difference if it uses a webkit view under the hood) – I'm not sure how to find out any more info from moblile Safari/Chrome as to what the error might be.

(A normal text like this one on Github work with the arrow keys.)

**Comment by ashb** [comment]
The editor on https://play.golang.org works fine however.

**Comment by campoy** [comment]
I'm not sure how to test this as I don't have any external iPad keyboard.

I found this post that might be interesting to you: https://discussions.apple.com/thread/2627932

Does that help? Sorry I can't do much more
