### ISSUE TITLE
tour: Confusing text about nil slices

### ISSUE THREAD

**Issue by kwk** [golang/go#13131]
Context: https://tour.golang.org/moretypes/11

The text on this page says:

> Nil slices
> The zero value of a slice is nil.
> A nil slice has a length and capacity of 0.

According to this statement I've created a slice using `make` and specified a capacity of `0`. Nevertheless, as shown below, both definitions (`var z[] int` and `z2 := make([]int, 0, 0)`) behave differently when checked for `nil`.

The statement 

> A nil slice has a length and capacity of 0.

seems to be false if you put it the other way around

> A slice that has a length and a capacity of 0 is a nil slice.

This should be noted in the page's text because it seems to be wrong as you can see from my example code and output.

```go
package main

import "fmt"

func main() {
	var z []int
	fmt.Println("z: ", z, len(z), cap(z))
	if z == nil {
		fmt.Println("z is nil!")
	}

	z2 := make([]int, 0, 0)
	fmt.Println("z2: ", z2, len(z2), cap(z2))
	if z2 == nil {
		fmt.Println("z2 is nil!")
	}
}
```

***Output:***

```
z:  [] 0 0
z is nil!
z2:  [] 0 0
```

**Comment by champioj** [comment]
Perhaps it should be noted as a reminder, but it's important to understand that there is nothing wrong with the statement in the exercise.

Given the statement

    A dog is a mammal
it would not make sense to to think that

    A mammal is a dog
    
Actually, it would not be an help to suggest that it could be true.

**Comment by cznic** [comment]
>The statement
>
> > A nil slice has a length and capacity of 0.
>
> seems to be false if you put it the other way around
>
> > A slice that has a length and a capacity of 0 is a nil slice.

That's how implication works.

Long version: You cannot `make` a nil slice. Even when passing zero for len and cap to `make`, the resulting slice is non nil because it has assigned the backing array, even if it is of zero length.

**Comment by ianlancetaylor** [comment]
I don't see anything to fix here.

**Comment by kwk** [comment]
@champioj @cznic @ianlancetaylor To be clear: I know what all you mean. No need to overemphasize that you cannot turn a sentence around. The problem is simply that I got a false impression from the tour and its example code. A tour should not lead to any confusion. One should for instance not check if a slice is `nil` to find out if it is empty or has a capacity of 0. And that is something that is implicitly suggested by the example code. At least could get the idea.

**Comment by rakyll** [comment]
Are you trying to suggest we shouldn't encourage users to invoke len and cap on nil slices? I don't think there is anything wrong with the content on the tour. nil is yet another value in Go.
