### ISSUE TITLE
x/crypto/ssh: package does not compile with Go 1.3 or earlier

### ISSUE THREAD

**Issue by davecheney** [golang/go#13137]
https://go-review.googlesource.com/#/c/10953/ added support for converting from the crypto.Signer interface, added in Go 1.4 to an ssh.Signer.

This means the crypto package does not compile under Go 1.3 and earlier. This is a problem for Canonical as (for various long, but immutable reasons) we are stuck on Go 1.2 for several of the operating system versions we support.

@agl one solution to this is to isolate the change to keys.go into a file which is only built with Go 1.4 or later. This would hide this feature from Go versions which do not support crypto.Signer.

An alternative would be to define an interface in the ssh package that is compatible with crypto.Signer, and use that as the formal parameter to those new methods in keys.go

I think the former is a cleaner option. What do you think ?

**Comment by bradfitz** [comment]
Note that build.golang.org only tests subrepos against the past two releases (Go 1.4 and Go 1.5). Unless we change that policy, you're fighting an uphill battle trying to get tip working with Go 1.3.

/cc @adg

**Comment by davecheney** [comment]
Thanks. I appreciate that canonical have bought this on themselves.

**Comment by rakyll** [comment]
It's better to move this conversation to a mailing list since it cannot be considered as a Go issue.

**Comment by davecheney** [comment]
Respectfully, I disagree with this assessment.

**Comment by bradfitz** [comment]
Either way. Or use both. I don't feel strongly about github issue vs mailing list here. Up to ssh authors. This bug tracker is more than just the Go stdlib, though.

The policy issue of support lifetime for sub repos might make a good mailing list topic

**Comment by agl** [comment]
Moving some of the code into a separate file sounds fine to me. I'm hesitant to make any commitments about backwards compatibility in general, but this seems like a minor change that would be useful to someone.

**Comment by agl** [comment]
Assigning this to Dave so that he can craft something that works in a Go 1.3 environment.

**Comment by davecheney** [comment]
@agl after a bit of wrangling internally we're going to try to upgrade to Go 1.5 instead. Given @bradfitz 's points that this change won't be tested by the buildbots, I'd prefer to close this issue instead.
