### ISSUE TITLE
runtime: "scan missed a g"

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13140]
I've seen this failure on the OpenBSD trybot and builders a bunch.  E.g.:

http://build.golang.org/log/9a7a7718cfe2eea41f9d63f236cbca4eb59bc0b8

I believe I've also seen it on a nacl trybot, and I saw it on my work desktop (linux/amd64) earlier today too.

**Comment by mdempsky** [comment]
openbsd-amd64-gce56 at fbf273250fe6f7697db2c1bf24e743226537b266
https://build.golang.org/log/f41a0241c725d24a59ade3a006aa1e6ca187e5d0

linux-amd64 at 82d14d77daab2ee61bba1af3c291cba47010657a
https://build.golang.org/log/79a6081741e984cda8ab8edc7ea378efcaaaa535

**Comment by aclements** [comment]
I'm hoping this will go away once I merge my series at https://go-review.googlesource.com/#/c/16391/. My goal is to do that this week. I'll ping this bug once that's happened and if we still see failures with that in the tree, I'll investigate.

**Comment by aclements** [comment]
I pushed my decentralized GC series last Thursday, November 5th and, in fact, the last time we saw this was in the middle of me pushing that series. Given the failure rate, it's highly likely that this has been fixed, but please reopen if you see it again.

First observed 82d14d7 30 Oct 22:46 2015 (93 commits ago)
Last observed  d986bf2 05 Nov 21:23 2015 (41 commits ago)
0.11% chance failure is still happening
15% failure probability (9 of 53 commits)
