### ISSUE TITLE
Panics in tests do not allow m.Run() to return in TestMain functions

### ISSUE THREAD

**Issue by ianrose14** [golang/go#13149]
If a test panics and you are using a TestMain function, the call to `m.Run()` does not return, which makes cleaning up from that test hard/impossible.

```
package wat

import (
	"fmt"
	"os"
	"testing"
)

func TestOk(t *testing.T) {
	t.Logf("I am ok")
}

func TestPanic(t *testing.T) {
	panic("oh noes")
}

func TestMain(m *testing.M) {
	fmt.Fprintf(os.Stderr, "starting tests!\n")
	result := m.Run()
	fmt.Fprintf(os.Stderr, "finished tests!\n")

	os.Exit(result)
}
```

If I run `go test -v -run TestOk wat_test.go`, I get:
```
starting tests!
=== RUN   TestOk
--- PASS: TestOk (0.00s)
        wat_test.go:10: I am ok
PASS
finished tests!
ok      command-line-arguments  0.006s
```

However if I run `go test -v -run TestPanic wat_test.go`, I get:
```
starting tests!
=== RUN   TestPanic
--- FAIL: TestPanic (0.00s)
panic: oh noes [recovered]
        panic: oh noes

goroutine 17 [running]:
(some stack frames deleted)
testing.tRunner(0x820368000, 0x24e258)
        /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x1ca2d0, 0x24e240, 0x2, 0x2, 0x1)
        /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0x8202efef8, 0x8202dc018)
        /usr/local/go/src/testing/testing.go:494 +0x70
(some stack frames deleted)
main.main()
        command-line-arguments/_test/_testmain.go:54 +0x113
exit status 2
FAIL    command-line-arguments  0.010s
```

Notice that in the latter case "finished test!" was not printed because the process exited before m.Run() could return.  The source of this is `panic(err)` statement in `tRunner` of testing.go.  If, instead of panicking, the function cleanly exited (as in a normal failed test) I think everything would work out.

> What version of Go are you using (go version)?
go version go1.5.1 darwin/amd64

> What operating system and processor architecture are you using?
MacOS v10.10.5

**Comment by minux** [comment]
In general, what was asked is not possible.

The panic could come from a goroutine started by a test and the testing
package can't add a defer to those goroutines to catch the panic.

Aadditionally, some panics are impossible to recover, e.g. out of menory or
runtime memory corruption.

**Comment by ianlancetaylor** [comment]
When that panic was added, in https://golang.org/cl/5658048 , Rob said exiting on panic was a feature, not a bug.  That seems reasonable to me.  As Minux says, you unfortunately can't rely on TestMain retaking control in all cases anyhow.
