### ISSUE TITLE
x/exp/shiny: error on Ubuntu 14.04

### ISSUE THREAD

**Issue by glorieux** [golang/go#13147]
Here is the error I've got when trying to run golang.org/x/exp/shiny/example/tile with go version go1.5.1 linux/amd64:

```sh
# golang.org/x/exp/shiny/driver/x11driver
../../driver/x11driver/screen.go:356: cannot use int32(width) (type int32) as type uint16 in argument to xproto.CreateWindow
../../driver/x11driver/screen.go:356: cannot use int32(height) (type int32) as type uint16 in argument to xproto.CreateWindow
```

I was able to get it to work properly by changing the int32 type used driver/x11driver/screen.go:356 to uint16.

Will submit fix soon.

**Comment by crawshaw** [comment]
Fixed by https://golang.org/cl/16552
