### ISSUE TITLE
tour: [Exercise: Fibonacci closure] - missing return statement

### ISSUE THREAD

**Issue by meatballcoder** [golang/go#13152]
Context: https://tour.golang.org/moretypes/23

Change the title above to describe your issue and add your feedback here, including code if necessary

Hi, I clicked run and get,

prog.go:8: missing return at end of function

Program exited.

Thanks.

**Comment by griesemer** [comment]
Working as intended. The point of this page is that you actually do the exercise and fill in the code.

**Comment by meatballcoder** [comment]
The other pages that are exercises say they are exercises.  I did not see that on this page.  Can the fact that it is an exercise be put on the page?

**Comment by griesemer** [comment]
The title says pretty clearly: "Exercise: Fibonacci closure" . What else do you have in mind?

**Comment by adg** [comment]
The title is "Exercise: Fibonacci closure" ?

**Comment by meatballcoder** [comment]
I edited my response.  It is clearly labeled.  Perhaps I have two many Go learning tabs open.  I don't know.  Sorry for entering an issue.

**Comment by adg** [comment]
No problem!
