### ISSUE TITLE
x/mobile/bind: ios9.1 linker warning

### ISSUE THREAD

**Issue by scisci** [golang/go#13153]
`ld: warning: object file (/Users/xxxxx/app/Frameworks/gotest.framework/gotest(000002.o)) was built for newer iOS version (9.1) than being linked (9.0)`

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by crawshaw** [comment]
@scisci are you building this with gomobile bind?

**Comment by scisci** [comment]
Yeah, I recently upgraded my device to ios 9.1 which then forced me to upgrade to XCode 7.1 and then I started to receive this warning.

**Comment by scisci** [comment]
I guess to specify a min version one would set:

`miphoneos-version-min=9.0`

I don't see anywhere that is being set.

**Comment by dcu** [comment]
We're having the same issue, is there a workaround?
