### ISSUE TITLE
with on not existing key in map produce error with missingkey=error

### ISSUE THREAD

**Issue by zazab** [golang/go#13158]
It looks like a bug, that `with` action in templates produce error with `missingkey=error`.
Due the documentation `with` action is made for checking if pipeline is empty, and perfectly fits in logic, for example, if foo has key "bar", then print something. But with `missingkey=error` option it fails all template generation with error. (http://play.golang.org/p/kmmkkrHZYI)

I found a workaround for this case, using `index` function. It works as expected, and does not produce errors on not existent key. But it makes templates less readable, and, I think, simple addressing should have same behaviour.

**Comment by adg** [comment]
This is exactly how it should work. The `with` action does not check for the presence of a field, but rather whether the field's value is non-zero. See this complementary example that uses a struct instead of a map: http://play.golang.org/p/b_Opy4892i
