### ISSUE TITLE
cmd/go: a package that uses cgo does not compile c code in parallel

### ISSUE THREAD

**Issue by YuleiXiao** [golang/go#13157]
I have a package that uses cgo and some C files in it.  When I compile, it will compile c files in sequence, not parallel. This will take most compile time. I think we should compile it in parallel automatically or add some parameter to decide by user.

**Comment by davecheney** [comment]
If you move the cgo code into a separate package, then go tool will be able to compile it once and cache the result.

**Comment by ianlancetaylor** [comment]
Dup of #9887.
