### ISSUE TITLE
runtime: interface is nil, not *testing.T

### ISSUE THREAD

**Issue by aclements** [golang/go#13169]
Random tests have started failing with "interface conversion: interface {} is nil, not *testing.T" or "interface conversion: interface is nil, not *testing.T". The first was http://build.golang.org/log/d1c8715084bdae5d80214470404aa422ac875dd4.

This flake happens enough that it's quite likely it happened within a few commits of the first occurrence and the commit where it first happened seems like a likely suspect: 8e496f1 runtime: simplify buffered channels (@randall77).

  First observed: 2015-11-05T15:41:05 8e496f1
  Last observed:  2015-11-05T21:29:17 b4447a1
  Failure probability: 44% (8 of 17 commits)
  Chance failure is still happening: 1 in 6
  50% chance failure started within 1 commit of first failure:
    8e496f1 runtime: simplify buffered channels.
    7bb2a7d cmd/dist: remove vestigial -s flag
  95% chance failure started within 5 commits of first failure:
    61ca7e5 crypto/x509: add /etc/ssl/certs to certificate directories
    9496815 cmd/go: put all generate variables in the environment
    b16c699 internal/syscall/unix: eliminate non-trivial randomTrap initializer
    dcd9e5b runtime: make putfull start mark workers

No past failures

**Comment by aclements** [comment]
I should add that the line that fails is `out := (<-t.signal).(*T)`.

**Comment by randall77** [comment]
Finally got a decent repro case for this.  Looks like a bad combination of channel ops and stack copy (shrink) of the receiver.  Somehow the receiver stack gets copied away just as the sender is trying to send to it.
