### ISSUE TITLE
cmd/compile: performance issue with ranging over string

### ISSUE THREAD

**Issue by mpvl** [golang/go#13162]
Looping over a string with range is significantly slower than using utf8.DecodeRuneInString.

So using 
`for i, r := range s { ... }`

is significantly slower than 

``` go
var size int
for i := 0; i < len(s); {
        r := rune(s[i])
        if r < RuneSelf {
            i++
        } else {
            r, size = DecodeRune(s[i:])
            i += size
        }
}
```

An (approximate) example of is one gets by comparing the benchmarks of the implementations for bytes and strings in unicode/utf8:

```
BenchmarkRuneCountTenASCIIChars-8               100000000           16.6 ns/op
BenchmarkRuneCountInStringTenASCIIChars-8       30000000            43.1 ns/op

BenchmarkValidTenASCIIChars-8                   100000000           13.8 ns/op
BenchmarkValidStringTenASCIIChars-8             30000000            52.5 ns/op
```

The benchmarks for the *String versions are considerably slower than their bytes counterparts, when processing ASCII.

**Comment by martisch** [comment]
I am working on a compiler patch that avoids calling stringiter for ascii chars. 
Next step is to remove stringiter completely and call charntorune when needed
directly.

BenchmarkRuneCountTenASCIIChars-4              	100000000	        12.9 ns/op
BenchmarkRuneCountInStringTenASCIIChars-4      	100000000	        12.3 ns/op

BenchmarkValidTenASCIIChars-4            	100000000	        11.7 ns/op
BenchmarkValidStringTenASCIIChars-4      	100000000	        12.6 ns/op

**Comment by martisch** [comment]
at tip on my macbookpro with intel ivy bridge where:

```
func RuneCountInString(s string) (n int) {
	for range s {
		n++
	}
	return n
}
```

name                                 time/op
RuneCountTenASCIIChars-4             11.1ns ± 3%
RuneCountTenJapaneseChars-4          65.0ns ± 2%
RuneCountInStringTenASCIIChars-4     10.9ns ± 1%
RuneCountInStringTenJapaneseChars-4  62.4ns ± 1%

is the speed of ranging over a string good enough on other machines too now?

**Comment by 0xmohit** [comment]
At [tip](https://github.com/golang/go/commit/ef8e85e8b8176fb096683dac00cf536fd7d228bc) on Linux x86_64:

```
name                                 time/op
RuneCountTenASCIIChars-4             10.3ns ± 4%
RuneCountTenJapaneseChars-4          65.2ns ± 2%
RuneCountInStringTenASCIIChars-4     9.79ns ± 2%
RuneCountInStringTenJapaneseChars-4  59.3ns ± 7%
```

**Comment by bradfitz** [comment]
Here are numbers changing `unicode/utf8.RuneCountInString` from its current implementation to:

```go
func RuneCountInString(s string) (n int) {
    for range s {
        n++
    }
    return n
}
```

Looks like it's now only 13-19% slower.

```
name                                 old time/op  new time/op   delta
RuneCountInStringTenASCIIChars-4     9.05ns ± 1%  10.27ns ± 1%  +13.51%  (p=0.000 n=10+10)
RuneCountInStringTenJapaneseChars-4  52.5ns ± 1%   62.4ns ± 1%  +18.86%   (p=0.000 n=10+9)
```

It's at least good enough for Go 1.8. I'll kick this to Unplanned at this point since it's a performance thing, which we don't generally track for releases unless it's really bad or important.

**Comment by randall77** [comment]
I actually get better performance (~10%) using string range.  Brad, I'm not sure why you see something different.

I'll mail a CL to use string range for RuneCountInString.  We can argue on that CL.

**Comment by bradfitz** [comment]
@randall77, I think some compiler changes landed after my comment there. I don't see d2951740303587fc0c5d14cb5461e39b099e6695 mentioned here, but it also apparently landed 3 days before my comment. So not sure which one.

**Comment by bradfitz** [comment]
Marking release-blocker to at least figure out whether we accept https://go-review.googlesource.com/c/go/+/33637 .

Ideally we would accept it, because it makes the code so much nicer, but it seems slower now with Go tip than it did in past releases.

@randall77?

**Comment by randall77** [comment]
Remeasuring, `RuneCountInString` using `range` is no faster for ascii, and it is slower for non-ascii.  So I don't think we should check it in at this point.
I'd like to see #22234 fixed first, looking at the assembly we're tripping on that issue.

**Comment by bradfitz** [comment]
Even with the #22234 fix in, this is still slower.

I measured two variants of the CL above: first with an unnamed result parameter, and second with a named result parameter. (ideally they shouldn't generate different code, but alas.)

```
bradfitz@gdev:~/go/src/unicode/utf8$ benchstat before after     
name                                 old time/op  new time/op  delta
RuneCountTenASCIIChars-4             11.8ns ± 1%  12.7ns ± 3%   +7.61%   (p=0.000 n=9+9)
RuneCountTenJapaneseChars-4          55.7ns ± 2%  55.8ns ± 1%     ~     (p=0.921 n=10+9)
RuneCountInStringTenASCIIChars-4     11.7ns ± 1%  12.2ns ± 2%   +4.52%  (p=0.000 n=9+10)
RuneCountInStringTenJapaneseChars-4  55.1ns ± 1%  71.3ns ± 3%  +29.56%  (p=0.000 n=9+10)

bradfitz@gdev:~/go/src/unicode/utf8$ benchstat before after2
name                                 old time/op  new time/op  delta
RuneCountTenASCIIChars-4             11.8ns ± 1%  13.6ns ±13%  +15.04%   (p=0.000 n=9+10)
RuneCountTenJapaneseChars-4          55.7ns ± 2%  56.1ns ± 2%     ~     (p=0.196 n=10+10)
RuneCountInStringTenASCIIChars-4     11.7ns ± 1%  12.3ns ± 1%   +4.69%   (p=0.000 n=9+10)
RuneCountInStringTenJapaneseChars-4  55.1ns ± 1%  70.1ns ± 1%  +27.25%   (p=0.000 n=9+10)
```

I'll kick this to Go 1.12 for @randall77 et al to investigate more.

**Comment by odeke-em** [comment]
Punting more to Go1.13 but @randall77 sent a CL https://go-review.googlesource.com/c/go/+/33637/ in late 2016.
