### ISSUE TITLE
Have return from a function as default if an error occurs

### ISSUE THREAD

**Issue by narayanan-arunachalam** [golang/go#13173]
Consider the below given code that illustrates the problem:

func (t *mytype) start() (string, error) {
  if result1, err := someMethod1(); err != nil {
    return nil, err
  }
  if result2, err := someMethod2(); err != nil {
    return nil, err
  }
  ...
  if result30, err := someMethod30(); err != nil {
    return nil, err
  }
}

In this implementation the error handling behavior is to just return the error cause and not do anything else. To achieve this, way too boiler plate code is required. Instead, the compiler can do better. If an error is not handled, return from the function by default. With this feature in the compiler, the code now can look like;

func (t *mytype) start() (string, error) {
  someMethod1()
  someMethod2()
  ...
  someMethod30()
}

In fact, handling errors this way need not be default but can be controlled with a new primitive "returnOnErrors" and can be used like:
func (t *mytype) start() (string, error) {
  returnOnErrors
  ...
}

**Comment by bradfitz** [comment]
Sorry, but the language was recently declared frozen.
