### ISSUE TITLE
gdb:Python Exception <class 'gdb.error'> There is no member named status

### ISSUE THREAD

**Issue by huangminlong** [golang/go#13170]
At the iirst i meet the problem is gdb  No struct type named runtime.rtype, and i follow the tips  in the issue:
https://github.com/golang/go/issues/9326
Problem:
i use the common command is okay , but when i use some command about goroutine is wrong ...
and the problem like this.

(gdb) info goroutines
Python Exception <class 'gdb.error'> There is no member named status.: 
Error occurred in Python command: There is no member named status.
(gdb)  goroutine 1 bt
Python Exception <class 'gdb.error'> There is no member named status.: 
Error occurred in Python command: There is no member named status.

my environment is : 
Linux/CentOS 7.1
golang 1.4.2
gdb GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.el7

**Comment by davecheney** [comment]
Have you tried with Go 1.5 ?

**Comment by huangminlong** [comment]
no , i just try it in 1.42

**Comment by davecheney** [comment]
Can you please try Go 1.5. If the bug is still present in Go 1.5 it is likely that it will only be fixed there, or maybe held over til Go 1.6. It is unlikely that a point release will be issued for Go 1.4.
