### ISSUE TITLE
tour: blank screen after clicking current page link in table of contents 

### ISSUE THREAD

**Issue by Daniel-Hug** [golang/go#13179]
Context: https://tour.golang.org/welcome/1

**Comment by Daniel-Hug** [comment]
Environment: chrome on my android phone

**Comment by adg** [comment]
Screenshot?

**Comment by Daniel-Hug** [comment]
Go to for continued in tour and open table of contents: https://goo.gl/photos/SwLLuV321FVjWxVT6ClickThen click "for continued"

**Comment by Daniel-Hug** [comment]
The URL of the page is `http://tour.golang.org/flowcontrol/2` throughout the steps above and refreshing after the blank screen will reload the current page with the content.

**Comment by campoy** [comment]
Ok, this one was a fun one to fix!

https://go-review.googlesource.com/17420

Please review
