### ISSUE TITLE
cmd/compiler: float64 Inf incorrectly represented as near zero in some cases

### ISSUE THREAD

**Issue by kortschak** [golang/go#13171]
```
$ go version
go version devel +6083bd6 Thu Nov 5 22:57:16 2015 +0000 linux/amd64
```
Run the program at http://play.golang.org/p/fjUjC_4mnD :
```
$ go run inf.go 
1
2
2.595975e-317
```
Expect to see:
```
$ go run inf.go 
1
2
+Inf
```

Removing the string field from the anonymous struct or removing the preceeding slice elements, or adding following Inf-containing elements abolishes the effect.

**Comment by kortschak** [comment]
Bisected to 5cf281a9b791f0f10efd1574934cbb19ea1b33da.

**Comment by minux** [comment]
It's because the register allocator doesn't
know that duffcopy will clobber X0.

**Comment by kortschak** [comment]
Yes, I had a suspicion it was a register issue.
