### ISSUE TITLE
issue when try to install offline spanish tour 

### ISSUE THREAD

**Issue by elmoro777** [golang/go#13187]
my go version:
go version go1.5.1 windows/amd64

my paths
set GOROOT=C:\tools\go
set GOPATH=D:\home\user\gocode

command:
go get github.com/rcostu/go-tour-es/gotoures

error:
warning: code.google.com is shutting down; import path code.google.com/p/go-tour/pic will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go-tour/tree will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go-tour/wc will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go.talks/pkg/present will stop working
package code.google.com/p/go.talks/pkg/present: cannot find package "code.google.com/p/go.talks/pkg/present" in any of:
        C:\tools\go\src\code.google.com\p\go.talks\pkg\present (from $GOROOT)
        D:\home\user\gocode\src\code.google.com\p\go.talks\pkg\present (from $GOPATH)
warning: code.google.com is shutting down; import path code.google.com/p/go.talks/pkg/socket will stop working
package code.google.com/p/go.talks/pkg/socket: cannot find package "code.google.com/p/go.talks/pkg/socket" in any of:
        C:\tools\go\src\code.google.com\p\go.talks\pkg\socket (from $GOROOT)
        D:\home\user\gocode\src\code.google.com\p\go.talks\pkg\socket (from $GOPATH)

THIS PATH EXIST
D:\home\user\gocode\src\code.google.com\p\go.talks

BUT "PKG" DIR BELOW DO NOT EXIST

any suggestion to solve this issue ???

thanks in advance !

Regards 

AP
from Arg/BuenosAires

**Comment by adg** [comment]
This has already been reported on the go-tour-es issue tracker: rcostu/go-tour-es#10

**Comment by elmoro777** [comment]
Sorry Andrew ... i see the issue that you refer and in many of answers that explain things that many "newbis" dont understood - the answer IS NOT CLEAR.
How you then - CLOSE - my issue with a reference SO UNSATISFACTORY ?????
PLEASE - PUT A CLEAR ANSWER ABOUT HOW TO RESOLVE OR LEAVE OPEN MY ISSUE 

Regards

by the way - DONT BE NAZI WITH YOUR ATTITUDE !

**Comment by bradfitz** [comment]
Godwin's law; thread is closed.

**Comment by adg** [comment]
@elmoro777 the Go project doesn't maintain the Spanish translation. If you have an issue with that version of the tour, you must report it to the maintainers of that version: https://github.com/rcostu/go-tour-es/issues
