### ISSUE TITLE
spec: make isn't defined on named types

### ISSUE THREAD

**Issue by paulhankin** [golang/go#13184]
https://golang.org/ref/spec#Making_slices_maps_and_channels

"The built-in function make takes a type T, which must be a slice, map or channel type, optionally followed by a type-specific list of expressions."

This appears to exclude named types, even though make will create values of named types.

Maybe: "The built-in function make takes a type T, whose underlying type must be a slice, map or channel type, optionally followed by a type-specific list of expressions."

Here's some working code that I think is not covered by the current spec: http://play.golang.org/p/mekr0KLDWj

package main
import "fmt"
type T []int
func main() {
	fmt.Println(make(T, 10))
}

**Comment by cznic** [comment]
A named slice type is still a slice type (cf. '... *which must be a slice,* ...'). I see no problem with the current wording of how `make` behaves.

**Comment by ianlancetaylor** [comment]
I also think the current text is fine.  Something like "[]int" is a type literal.  Saying "slice type" includes not just type literals but also named slice types.
