### ISSUE TITLE
tour: Nextafter function not explained

### ISSUE THREAD

**Issue by Daniel-Hug** [golang/go#13180]
Context: https://tour.golang.org/basics/2

Also, does go do arithmetic like JS to where it returns 2.0000000000004?

**Comment by Daniel-Hug** [comment]
https://goo.gl/photos/2C7kJTJGPrGdDdVp7

**Comment by minux** [comment]
It's just an example function.

You can always look up its docs on https://golang.org/pkg/math/#Nextafter.
(Actually, it's also in standard C math.h.)

**Comment by kytrinyx** [comment]
How about if we link to the Nextafter docs from the slide?

**Comment by adg** [comment]
Sounds good to me.

**Comment by adg** [comment]
Or we could just use a different function that is less mysterious. Like `math.Sqrt`.

**Comment by kytrinyx** [comment]
Yeah, `math.Sqrt` would probably be less confusing. I'll take this one.
