### ISSUE TITLE
issue when try to install offline spanish tour - NOT ANSWERED !!! CLOSED BY STUPID GUYS !!!

### ISSUE THREAD

**Issue by elmoro777** [golang/go#13188]
THIS ISSUE HAS NOT BEEN ANSWERED 

STUPID PEOPLE ARE IN EVERYWHERE 

EVEN HERE !

issue when try to install offline spanish tour · Issue #13187 · golang/go
https://github.com/golang/go/issues/13187#issuecomment-154984584

**Comment by bradfitz** [comment]
Please be civil. I closed your previous issue because you were calling people Nazis. Now you're calling them stupid people.

Please stop.
