### ISSUE TITLE
path/filepath: Dir() returns incorrect result if the path contains a trailing slash

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#13199]
[filepath.Dir](https://golang.org/pkg/path/filepath/#Dir) returns incorrect result if the specified path contains a trailing slash.  For example, if the input were `/home/`, then `filepath.Dir` and `filepath.Base` return `/home` and `home` respectively.  Playground [link](http://play.golang.org/p/4vjMCjJV-o).

Following is the output of `dirname` and `basename` from GNU coreutils:

```shell
$ dirname /home
/
$ basename /home
home
$ dirname /home/
/
$ basename /home/
home
```

When the input doesn't contain a trailing slash, then the functions yield expected output.

**Comment by adg** [comment]
There does seem to be an inconsistency between `filepath.Dir` and `filepath.Base`. IMO `Dir` should not include the component returned by `Base`.

**Comment by 0xmohit** [comment]
To clarify, the expectation is that `filepath.Dir("/home")` would return `/`.

**Comment by rsc** [comment]
The docs for Dir say "Dir returns all but the last element of path, typically the path's directory." They don't guarantee to get the path's directory. See my longer comment on CL 16791, but I don't think we should change this.

**Comment by 0xmohit** [comment]
This was specifically regarding the oddity in the current implementation (the second case in the playground link above):

```
input path: /home/, dir: /home, base: home
```

Whether `Dir` returns `/home` or `/` in this case, `Base` should adjust itself.  To elaborate, one would expect that

``` go
filepath.Clean(p) == filepath.Join(filepath.Dir(p), filepath.Base(p))
```

**Comment by rsc** [comment]
@0xmohit that's not guaranteed by the docs. The docs state different behaviors for Dir and Base, and I don't feel at liberty to contradict the established behavior and docs. If you need that guarantee, use filepath.Split.
