### ISSUE TITLE
net: flaky TestUnixAndUnixpacketServer

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13205]
Fix this flaky test:

http://build.golang.org/log/c1ce49888891e1022cdd9eacfb765eb0ce497562
```
--- FAIL: TestUnixAndUnixpacketServer (0.00s)
	server_test.go:195: #3: EOF
FAIL
FAIL	net	1.989s
```

@mikioh, care to look into it?
@aclements, is it easy for you to compute stats on this flakiness?

**Comment by aclements** [comment]
> @aclements, is it easy for you to compute stats on this flakiness?

Very! But they're not very interesting. It appears this is the only time this has happened.

$ findflakes -grep TestUnixAndUnixpacketServer
First observed 2fdff95 10 Nov 20:22 2015 (12 commits ago)
Last observed  2fdff95 10 Nov 20:22 2015 (12 commits ago)
Isolated failure
No known past failures

**Comment by rsc** [comment]
Only happened once, so maybe not worth it / not possible to figure out.

**Comment by cherrymui** [comment]
Saw one in a trybot failure https://storage.googleapis.com/go-build-log/31bf88a3/linux-amd64_d97e4f3d.log
in CL https://go-review.googlesource.com/c/38131/. The CL itself is unrelated.
