### ISSUE TITLE
 should flush stdin before printing the prompt and Scanln

### ISSUE THREAD

**Issue by akevinbailey** [golang/go#13209]
I don't know why this is "closed". This is still an issue in Go 1.5.1. Will it be fixed in 1.5.2?

**Comment by davecheney** [comment]
@akevinbailey which issue is closed ? You have opened a new issue without context.

**Comment by ALTree** [comment]
I think he sent this comment: https://github.com/odeke-em/drive/issues/157 here by mistake.
