### ISSUE TITLE
cmd/go: cannot use 'go get -u' after commit bc1f9d20b40998b87c9a5f56f2b22595de65c2d4

### ISSUE THREAD

**Issue by siebenmann** [golang/go#13206]
After commit bc1f9d20b40998b87c9a5f56f2b22595de65c2d4, 'cmd/go: use shallow clones for new git checkouts', it's no longer possible to use 'go get -u'. Attempts to do so error out with a usage error from git:

    $ go get -u github.com/rogpeppe/godef
    # cd /homes/hawkwind/u0/cks/go/src/github.com/rogpeppe/godef; git pull --depth=1 --ff-only
    error: unknown option `ff-only'
    usage: git fetch [<options>] [<repository> [<refspec>...]]
       or: git fetch [<options>] <group>
       or: git fetch --multiple [<options>] [(<repository> | <group>)...]
       or: git fetch --all [<options>]
    [...]

Ordinary 'go get' (still) works.

My version of git is 'git version 2.4.3', which is the standard Fedora Linux 22 package (I'm on x86_64).

Experimentally, running 'git pull --ff-only --depth=1' does not error out. However I don't know if it behaves correctly (ie, forces fast forward only merges), and it prints extra output that 'git pull --ff-only' does not:

    $ git pull --ff-only --depth=1
    remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
    Already up-to-date.
    $ git pull --ff-only
    Already up-to-date.

(Thus, simply switching the order here may not be the correct fix.)

**Comment by bradfitz** [comment]
I can't reproduce with git version 2.6.2 at least. I haven't tested more than that.

**Comment by siebenmann** [comment]
'git pull --depth=1 --ff-only' also fails on Ubuntu 14.04 LTS (git version 1.9.1) but succeeds on FreeBSD 10.something with git 2.6.1, and on Fedora 23 with 2.5.0 (where it prints the extra line of output). Based on the git 2.5.0 changelog I think the fundamental fix for this issue was made in 2.5.0, although it may have been refined later.

(One change is '"git pull" has become more aware of the options meant for underlying "git fetch" and then learned to use parse-options parser'.)

**Comment by ahmetalpbalkan** [comment]
Here's a repro: https://travis-ci.org/Azure/go-autorest/builds/90569740

**Comment by tcz001** [comment]
We have kind of same issue when using travis-ci and it's also having problem when try to `go get gopkg.in/check.v1` without update. see both: 

https://travis-ci.org/twstrike/coyim/jobs/90568623
and
https://travis-ci.org/twstrike/coyim/jobs/90614014

**Comment by rakyll** [comment]
```
$ git version
git version 2.6.2
```
I was able to reproduce it with the following on a mac with a previously cloned unshallow golang.org/x/tools repo.

```
go get  -u golang.org/x/tools/...
```

I am trying to understand what `git pull --depth=1` may mean. Aren't we suppose to unshallow and pull if the repo is shallow?

As a side note, the current behavior of `go get -u` is messing the GOPATHs if the user is not working with unshallow copies. I think we should immediately revert bc1f9d20b40998b87c9a5f56f2b22595de65c2d4 and experiment thoroughly before ever bringing it back.

/cc @rsc

**Comment by ahmetalpbalkan** [comment]
I just found out this is only the `tip` is broken. The issue does not repro on versions such as go1.5.1. In the meanwhile, travis-ci users can add `go: 1.5` to their .travis.yml file to prevent it from happening. @tcz001

**Comment by kostya-sh** [comment]
Debian 8.2 comes with git 2.1.4 that doesn't support `pull --ff-only`. I think go get should support reasonably old versions of git.
