### ISSUE TITLE
compress/gzip: does not document when Reader.Header is valid

### ISSUE THREAD

**Issue by dsnet** [golang/go#13211]
Using ```go1.5```

Is Reader.Header valid after NewReader or after the first Reader.Read?

The code clearly shows that the Reader.Header is read during NewReader and Reader.Reset, but the documentation does not mention when it is valid.

**Comment by rakyll** [comment]
It is valid after NewReader. I don't think we should document anything. In Go, it is useful to document if there is extra work needs to be done before making a call. Unless it is documented, it should just work if APIs allow you to make the call.

**Comment by bradfitz** [comment]
I think this is a valid documentation request.
