### ISSUE TITLE
x/mobile: all apk created by GoMobile give a black screen just on phone

### ISSUE THREAD

**Issue by andrebernard** [golang/go#13217]
Hello,

I have tried to create several example of APK with GOMOBILE, but when i test them, she works in the emulator BlueStacks, and also on my SAMSUNG TAB, but not on my Android Samsung note 1 and not also on my Android Samsung note 2.
All the application give to me only the title, and the screen is black ;-(
After several seconds, the application stop

If someone know, how can i fix my problem

My system is W7 and when i write "Gomobile Version" the answer is "Gomobile version unknow"
SAMSUNG NOTE1 and NOTE2, have ANDROID v4.1.2
SAMSUNG TAB 3, have ANDROID v4.4.2

Have a good day

**Comment by crawshaw** [comment]
Hi @andrebernard.

First off, "gomobile version unknown" probably means you need to run ```go install golang.org/x/mobile/cmd/gomobile``` again.

As for the difference you're seeing between the Samsung Tab and the Samsung Note 1, can you run adb logcat and see if there's any relevant output?

**Comment by eliasnaur** [comment]
Is this still a problem?

**Comment by changkun** [comment]
gomobile apps on Android works today. Close as this should not be a problem. Feel free to comment any updates.
