### ISSUE TITLE
tour: If statement ambiguous

### ISSUE THREAD

**Issue by Judicus** [golang/go#13212]
Context: https://tour.golang.org/flowcontrol/5

The little jab regarding the if declarations sounding familiar [to the for declaration] implies that the parens are not even optional as stated in the for statement.   It could help new user's understanding if this was clarified early.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by rakyll** [comment]
I wished that it was explaining the if statement first rather than making comparisons with the others' ifs. Explain if and then mention the differences.

**Comment by kytrinyx** [comment]
Yes, I think that's a good point, @rakyll, it would be nice to not lead with something that sounds like we're assuming you're coming to Go from C or Java, even though many people do.

**Comment by campoy** [comment]
I created this trying to make references to C and Java less important and giving more detail on what a for loop is. Please review:

https://go-review.googlesource.com/16862

**Comment by kytrinyx** [comment]
I think this change went into the tour. Can this be closed?
