### ISSUE TITLE
compress/testdata: Mark.Twain-Tom.Sawyer.txt is licensed under non-free license

### ISSUE THREAD

**Issue by jcajka** [golang/go#13216]
Mark.Twain-Tom.Sawyer.txt under compress/testdata is licensed under non-free license "Project Gutenberg license". As book itself is in Public Domain I'm proposing to remove the current non-free license from the file including all references to "Project Gutenberg" .

This issue affects all branches of golang source tree including this file. And think it should be fixed in all supported release.

If this change is acceptable/accepted, I will provide patch for review in gerrit.

**Comment by dsnet** [comment]
I don't see what the problem is, the header provided by the Gutenberg server is:
```
The Project Gutenberg EBook of The Adventures of Tom Sawyer, Complete by
Mark Twain (Samuel Clemens)

This eBook is for the use of anyone anywhere at no cost and with almost
no restrictions whatsoever. You may copy it, give it away or re-use
it under the terms of the Project Gutenberg License included with this
eBook or online at www.gutenberg.net
```

The sentence blatantly says "You many copy it", which is exactly what's done.

**Comment by jcajka** [comment]
See footer.

**Comment by adg** [comment]
Please go ahead and send a CL to remove the license and references to Gutenberg.

**Comment by jcajka** [comment]
Opened CL https://go-review.googlesource.com/17196
Sorry for delay(CLA...).
