### ISSUE TITLE
cmd/go: TestGoTestRaceInstallCgo fails on Darwin

### ISSUE THREAD

**Issue by rjammala** [golang/go#13214]
$ go version
go version devel +4255b78 Thu Nov 12 00:08:07 2015 +0000 darwin/amd64

$ uname -a
Darwin 0700077782A 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

--- FAIL: TestGoTestRaceInstallCgo (0.30s)
	go_test.go:257: running testgo [tool -n cgo]
	go_test.go:272: standard output:
	go_test.go:273: /Users/rajanikanth.j/go/pkg/tool/darwin_amd64/cgo

	go_test.go:257: running testgo [test -race -i runtime/race]
	go_test.go:276: standard error:
	go_test.go:277: # runtime
		../../runtime/atomic_pointer.go:8: import /Users/rajanikanth.j/go/pkg/darwin_amd64_race/runtime/internal/atomic.a: object is [darwin amd64 devel +67faca7 Tue Nov 10 17:38:04 2015 +0000 X:none] expected [darwin amd64 devel +4255b78 Thu Nov 12 00:08:07 2015 +0000 X:none]

	go_test.go:286: go [test -race -i runtime/race] failed unexpectedly: exit status 2
FAIL
FAIL	cmd/go	34.698s

**Comment by aclements** [comment]
/cc @michaelmatloob @ianlancetaylor 

I'm seeing this on linux/amd64 as well.

The hash it's expecting is the current commit and I think the hash it's finding is the commit I was on when I last ran all.bash. It looks like the archives in pkg/linux_amd64_race (or equivalent) aren't being updated by all.bash correctly. This is where I find the stale object header that the test is complaining about.

**Comment by aclements** [comment]
Reproducer:

```
git clone https://go.googlesource.com/go go.tmp
cd go.tmp/src
git checkout master^ && ./all.bash && git checkout master && ./all.bash
```

**Comment by ianlancetaylor** [comment]
https://golang.org/cl/16837

Feel free to submit if it looks OK.

**Comment by kostya-sh** [comment]
I had the same error building on linux/amd64. Applying https://golang.org/cl/16837 didn't help. I had to delete $GOROOT/pkg and rerun all.bash

**Comment by aclements** [comment]
This didn't fix the issue for me. My reproducer above still fails on the second all.bash with

```
--- FAIL: TestGoTestRaceInstallCgo (0.06s)
	go_test.go:257: running testgo [tool -n cgo]
	go_test.go:272: standard output:
	go_test.go:273: /home/austin/go.tmp/pkg/tool/linux_amd64/cgo
		
	go_test.go:257: running testgo [test -race -i runtime/race]
	go_test.go:276: standard error:
	go_test.go:277: # runtime
		../../runtime/atomic_pointer.go:8: import /home/austin/go.tmp/pkg/linux_amd64_race/runtime/internal/atomic.a: object is [linux amd64 devel +f5722a8 Thu Nov 12 14:26:00 2015 +0000 X:none] expected [linux amd64 devel +d54c356 Thu Nov 12 15:35:48 2015 +0000 X:none]
		
	go_test.go:286: go [test -race -i runtime/race] failed unexpectedly: exit status 2
FAIL
FAIL	cmd/go	28.969s
```

where f5722a8 is master^ and d54c356 is master.
