### ISSUE TITLE
x/build/cmd/gomote: not go-gettable

### ISSUE THREAD

**Issue by aclements** [golang/go#13213]
golang.org/x/build/cmd/gomote is not go-gettable right now:

```
$ go get -u golang.org/x/build/cmd/gomote
# cd .; git clone --depth=1 https://code.google.com/p/go-decimal-inf.exp /usr/local/google/home/austin/r/go/src/speter.net/go/exp/math/dec/inf
Cloning into '/usr/local/google/home/austin/r/go/src/speter.net/go/exp/math/dec/inf'...
fatal: Server does not support shallow clients
fatal: The remote end hung up unexpectedly
package speter.net/go/exp/math/dec/inf: exit status 128
```

It's not clear who's "fault" this is. Should x/build/kubernetes/api be depending on this external repository? Is it code.google.com's fault for not supporting shallowing clones? Should go get deal with servers that don't support shallow clones?

/cc @bradfitz @mdempsky @evandbrown

**Comment by rakyll** [comment]
The fault of https://github.com/golang/go/issues/13206?

We have more than enough reasons to revert bc1f9d20b40998b87c9a5f56f2b22595de65c2d4 at this point.
