### ISSUE TITLE
a iteration can be saved for "func (r *Rand) Perm(n int) []int"

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#13215]
In `src/math/rand/rand.go`, there is the following code:

```
func (r *Rand) Perm(n int) []int {
	m := make([]int, n)
	for i := 0; i < n; i++ {
		j := r.Intn(i + 1)
		m[i] = m[j]
		m[j] = i
	}
	return m
}
```

`i` can start from `1` instead of `0` since the iteration for `i=0` always swap `m[0]` with `m[0]`. A fix is to change ` i := 0` to ` i := 1`.

**Comment by randall77** [comment]
Indeed.  Unfortunately, this is tricky.  Perm also side-effects r, and making this change will affect the final state of r.  I don't think we can do that for compatibility reasons.
You could start the loop at 1 and call r.Intn(1) (or Int63()) before the loop.  Then add a big comment as to why that call is there and that we should remove it for Go 2.

Too bad Intn(1) wasn't originally coded to do the n==1 shortcut.

Care to make a patch?

**Comment by minux** [comment]
I think preserving the call to rand.Intn will negate any speed advantage of
the saved iteration.

Perhaps we should just add a note that we need to preserve the rand state
here.

**Comment by randall77** [comment]
Yeah, it's not a big win.
Comment sounds fine.  Bonus: that can go in during the freeze.

**Comment by yaojingguo** [comment]
@randall77, so the conclusion is to make a patch which adds a comment, right?

**Comment by randall77** [comment]
Yes, sounds good.

**Comment by minux** [comment]
Yes.

**Comment by yaojingguo** [comment]
A patch is created.

CL link: https://go-review.googlesource.com/16852
