### ISSUE TITLE
runtime/pprof: TestCPUProfileMultithreaded is flaky on ppc64le

### ISSUE THREAD

**Issue by mwhudson** [golang/go#13223]
For example from http://build.golang.org/log/a58e91460d1b6bec7380bd3f9f86f57483aa2e22:

```
--- FAIL: TestCPUProfileMultithreaded (0.25s)
	pprof_test.go:165: total 12 CPU profile samples collected
	pprof_test.go:181: runtime/pprof_test.cpuHog1: 0
	pprof_test.go:181: runtime/pprof_test.cpuHog2: 12
	pprof_test.go:195: runtime/pprof_test.cpuHog1 has 0 samples out of 12, want at least 1, ideally 6
FAIL
```

Very old neurons recall that the timer on powerpc has pretty low resolution, but I don't know if that is true or the problem here.

**Comment by aclements** [comment]
@davecheney, can you provide the kernel config for the linux-ppc64le-canonical builder? In particular, if CONFIG_HIGH_RES_TIMERS is not set, this is probably the same as #13405.

**Comment by aclements** [comment]
I'm guessing it's this one: http://kernel.ubuntu.com/~kernel-ppa/configs/trusty/ppc64el-config.flavour.generic, which does have CONFIG_HIGH_RES_TIMERS set.

**Comment by rsc** [comment]
@aclements, what's the magic /proc file to look in to find out timer resolution?

**Comment by aclements** [comment]
grep resolution: /proc/timer_list

**Comment by rsc** [comment]
FWIW I got lots of '1 nsecs' with that grep on a ppc64le machine (but not
the Canonical builder).
So at least some hardware does have good timers.

**Comment by davecheney** [comment]
@rsc from the canonical ppc64le machine
```
winton-01(~) % grep resolution: /proc/timer_list
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
  .resolution: 1 nsecs
```
