### ISSUE TITLE
Third Party GOPATH tip on wiki is bad advice

### ISSUE THREAD

**Issue by natefinch** [golang/go#13225]
Someone on reddit just asked a question about this section in the wiki: https://github.com/golang/go/wiki/GOPATH#third-party-packages

It states:

> ### Third-party Packages
> It is useful to have two GOPATH entries. One for a location for 3rd party goinstalled packages, and the second for your own projects. List the 3rd party GOPATH first, so that goinstall will use it as a default destination. Then you can work in the second GOPATH directory and have all your packages be importable by using the "go" command, goinstall, or a GOPATH-aware 3rd party build tool like [gb](http://code.google.com/p/go-gb).

I think this is actually bad advice.  It just makes your gopath more confusing than just the standard "one gopath to rule them all). Instead of having one canonical place to look for everything, you have to remember whether a package is "your code" or "someone else's code" so you know which of two directories to look in.  Given that generally "your code" will live under a canonical directory anyway (i.e. in my case, github.com/natefinch for my code or github.com/juju for work code), there seems little benefit to having two different GOPATHs.

Not sure what the policy is on edits to the wiki, so figured I'd post an issue first.

**Comment by adg** [comment]
Please edit the wiki.

**Comment by natefinch** [comment]
Done: https://github.com/golang/go/wiki/GOPATH#use-a-single-gopath

**Comment by adg** [comment]
Thanks
