### ISSUE TITLE
go get is noisy on repos with meta tags

### ISSUE THREAD

**Issue by anacrolix** [golang/go#13224]
Example:
```
$ go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
```
None of this is useful, and shouldn't be shown unless something goes wrong.

**Comment by davecheney** [comment]
You asked for `-v`, you got it.

**Comment by adg** [comment]
This output is very useful when diagnosing issues with repos with meta tags.
As Dave said, you got what you asked for by specifying `-v`. We're not going to add `-vv`.

**Comment by anacrolix** [comment]
I feel this is inconsistent, meta tags are being special cased here. There's no logging of VCS specific stuff, why treat this differently? If there is a meta tag issue, it can be resolved with other tools. Rule of Silence: When a program has nothing surprising to say, it should say nothing.

**Comment by minux** [comment]
Rule of silence should not apply if the user explicitly supplies a verbose
flag.

**Comment by adg** [comment]
What kind of output do you expect when using the verbose flag?

**Comment by anacrolix** [comment]
Just the usual stuff relating to which packages download new changesets.

**Comment by natefinch** [comment]
I think this is incredibly useful, since it shows you the magic that is happening with the meta tags.  If you don't get that output with -v, how else would you get it?

**Comment by adg** [comment]
Also if there's other diagnostic information that we could be showing but
aren't, we should probably include that in the -v output too.
