### ISSUE TITLE
website: provide an api / directory listing for available go binary downloads

### ISSUE THREAD

**Issue by asottile** [golang/go#13220]
I'm planning on writing a tool which will automate setting up go development environments using a specific version of go.

I'd like to be able to list available go downloads in some way that's better than parsing this page: https://golang.org/dl/

Unfortunately, directory listing is turned off for https://storage.googleapis.com/golang/ or I would just use that.

**Comment by bradfitz** [comment]
Seems fine to me at least.

You want to send a CL? Perhaps make it at https://golang.org/dl/?format=json

/cc @adg

**Comment by asottile** [comment]
I'm not sure I understand what CL means, but yeah that endpoint sounds great :)

The information I'd want from it is essentially versions mapping to platform + download url.

**Comment by adg** [comment]
Sounds good to me.

Anthony, a CL is a Change List or Code Review. See
https://golang.org/doc/contribute.html

**Comment by Scorpiion** [comment]
Directory listing have not been turned on now.

I added some samples here of how to parse the information:
https://github.com/golang/go/issues/14385#issuecomment-187276247

Maybe this issue can be closed, or what do you think @asottile?

**Comment by adg** [comment]
I think it's worth closing.

**Comment by asottile** [comment]
looks fine to me, thanks
