### ISSUE TITLE
x/mobile/cmd/gomobile: version unknown

### ISSUE THREAD

**Issue by rakyll** [golang/go#13238]
```
$ gomobile version
gomobile version unknown
```

Can we generate a version string with the Go version gomobile is inited with?

/cc @crawshaw @hyangah

**Comment by crawshaw** [comment]
The goal is to never report a misleading version. I cannot debug anything generated by:

```
go install golang.org/x/mobile/cmd/gomobile
git pull # updates x/mobile
gomobile init
# who knows where we are now
```

But we can say more about why the version is unknown.
