### ISSUE TITLE
cmd/go: generate ignores -tags option when used with ./...

### ISSUE THREAD

**Issue by opennota** [golang/go#13232]
https://github.com/opennota/go-generate-issue/tree/master/a

`cd a`

`go generate -tags tag1` prints `package a`

`go generate -tags tag1 ./...` **prints nothing**.

Remove `// +build tag1` line from `a.go`, and `go generate ./...` will print `package a`.

**Comment by rakyll** [comment]
Also a go build bug.

```
pwd
/Users/jbd/src/github.com/opennota/go-generate-issue/a

go build -tags tag1 .
echo $?
0

go build -tags tag1 ./...
warning: "./..." matched no packages
warning: "./..." matched no packages

# the following works
go build -tags tag1 github.com/opennota/go-generate-issue/a/...
```

**Comment by rsc** [comment]
Possibly a dup of #11246.

**Comment by rsc** [comment]
Dup of #11246.
