### ISSUE TITLE
all: issue Go 1.5.2

### ISSUE THREAD

**Issue by rsc** [golang/go#13233]
Tracking bug for Go 1.5.2.

**Comment by rsc** [comment]
@aclements on #12552:

Since it's not at all obvious from the issue log, here's the set of commits that actually fix this and should be cherry-picked for 1.5.2, in cherry-picking order:

2c91114 runtime: adjust the ppc64x memmove and memclr to copy by word as much as it can (https://golang.org/cl/14840)
9f6df6c runtime: use 4 byte writes in amd64p32 memmove/memclr (https://golang.org/cl/15370)
168a51b runtime: adjust the arm64 memmove and memclr to operate by word as much as they can (https://golang.org/cl/14813)
4b7d5f0 runtime: memmove/memclr pointers atomically (https://golang.org/cl/16668)

I've confirmed that they cherry-pick cleanly (in this order) to the 1.5 release branch.

**Comment by adg** [comment]
Happy to review cherry pick CLs.

**Comment by broady** [comment]
Update on the release:
go1.5.2 is tagged, binaries are built and signed, but ran into a hiccup when uploading the binaries.

The binaries upload to Google Cloud Storage just fine, but the update to golang.org/dl is stuck (some changes were made to the server recently). Working on fixing it with @bradfitz.

**Comment by ianlancetaylor** [comment]
It's out.

**Comment by broady** [comment]
:clap:
