### ISSUE TITLE
x/mobile/cmd/gomobile: init fails with go1.5.x

### ISSUE THREAD

**Issue by BeeAdmin** [golang/go#13246]
Edit: Sorry, Pressed Publish before writing anything :stuck_out_tongue_closed_eyes: 

Anyways, today, I got around installing go/mobile, I followed the instructions, called ```go get ...``` and dowloaded the basic example, and ran ```gomobile init```, that resulted in an error, as in:
```bash
user@Terminal-T61:~/Go/src/terminal/admin/core$ gomobile init
gomobile: go install -p=2 -gcflags=-shared -ldflags=-shared -pkgdir=/home/user/Go/pkg/gomobile/pkg_android_arm std failed: exit status 2
# runtime
flag provided but not defined: -shared
usage: 5g [options] file.go...
/* etc ... */
```
I don't really know how to fix it, I'm using go1.51 and ```go env``` echoes.
```
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/Go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_386"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
I'm rockin' lubuntu on my old T61
Finally, one last thing.
```
user@Terminal-T61:~/Go/src/terminal/admin/core$ ls /home/user/Go/pkg/gomobile/ 
android-ndk-r10e  dl
```

**Comment by ianlancetaylor** [comment]
I can tell by the error message that the version of go you are using when you run `go install` is not Go 1.5.1.  Check your PATH.

**Comment by xuwaters** [comment]
I met the same problem. Modify the source code of gomobile/init.go as following:

	//if err := installStd(androidArmEnv, "-gcflags=-shared", "-ldflags=-shared"); err != nil {
	if err := installStd(androidArmEnv); err != nil {

Recompile gomobile command and try again.

**Comment by BeeAdmin** [comment]
@ianlancetaylor 
```bash
malek@Terminal-T61:~$ go version
go version go1.5.1 linux/386
malek@Terminal-T61:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/go/bin:/home/user/Go/bin
```

**Comment by hyangah** [comment]
I will revert https://go-review.googlesource.com/#/c/16912/ for now.

**Comment by BeeAdmin** [comment]
@xuwaters suggestion worked for me, i edited gomobile/init.go, then I put in
```bash
sudo apt-get install gcc
sudo GOPATH=/home/user/Go go install -a golang.org/x/mobile/cmd/gomobile
```
And it worked!
