### ISSUE TITLE
cmd/compile: simplify import mechanism

### ISSUE THREAD

**Issue by griesemer** [golang/go#13242]
Tracking issue. Once the yacc-parser is gone, we can simplify how imports are handled w/o redirecting the underlying input stream. Perhaps not worth doing if we switch to new import format directly. Target 1.7 Early.

**Comment by griesemer** [comment]
This is pending #13240.

**Comment by bradfitz** [comment]
@griesemer, is this done?

**Comment by griesemer** [comment]
Yes. We don't redirect the import stream anymore.
