### ISSUE TITLE
cmd/compile: switch to new export format

### ISSUE THREAD

**Issue by griesemer** [golang/go#13241]
Tracking issue. Target is 1.7 Early.

**Comment by dr2chase** [comment]
New export format will still allow us to easily add new info, yes?
I have in mind

  "definitely bounds checks argJ"
  "resultK is guaranteed non-nil"
  "resultK is guaranteed non-negative"

For static error checking, it might also be useful to know which args will definitely be dereferenced.

**Comment by griesemer** [comment]
Yes it will. I will describe in details how to do this once the new mechanism is completely in and enabled.
- gri
