### ISSUE TITLE
x/mobile: Getting error in building GO using "org.golang.mobile.bind" plugin

### ISSUE THREAD

**Issue by GhongadiAdinath** [golang/go#13251]
Hi, 
First of all, thanks for the good information on how to build go programs 
I tried the example mentioned in the "https://go-review.googlesource.com/#/c/12800/ "
## But, getting bellow error:

FAILURE: Build failed with an exception.

Where:
Build file '/home/SDL/gocode/src/SDL-SRC/build.gradle' line: 2

What went wrong:
A problem occurred evaluating root project 'SDL-SRC'.

No signature of method: build_4s3bi4u0rg0mg10bktcmg7ughp$_run_closure1.id() is applicable for argument types: (java.lang.String) values: [org.golang.mobile.bind]
## build.gradle:

plugins {
id "org.golang.mobile.bind" version "0.2.1"
}

gobind {
/\* The Go package path; must be under one of the GOPATH elements or
a relative to the current directory (e.g. ../../hello) */
pkg = "/home/SDL/gocode/src/SDL-SRC"

/\* GOPATH where the Go package is; check `go env` */
GOPATH = "/home/SDL/gocode"

/\* Absolute path to the go binary */
GO = "/usr/local/go/bin"
## }

Please help me to resolve this issue

**Comment by ianlancetaylor** [comment]
CC @crawshaw

**Comment by GhongadiAdinath** [comment]
Hi,

I got above issue resolved, the issue was because of old gradle. I update the gradle to 2.4(from 1.12).
after this, issue is something else.

> No such property: GO for class: org.golang.mobile.GobindExtension_Decorated
  Possible solutions: pkg

Please help me to resolve this issue.

**Comment by crawshaw** [comment]
In the snippet you posted you are using version 0.2.1 of the gradle plugin. The current version is 0.2.3. Please try that. Also note there is a GOMOBILE parameter to set. See the README.md in https://github.com/golang/mobile/tree/master/misc/androidstudio

**Comment by hyangah** [comment]
Did the use of Gobind plugin 0.2.3 fix the issue?

**Comment by eliasnaur** [comment]
I'm closing this; there is no followup since 2016.
