### ISSUE TITLE
runtime: Race condition in map_fixed on Linux?

### ISSUE THREAD

**Issue by Eloff** [golang/go#13256]
I was reading the code in mem_linux.go, and discovered what seems to be a race condition in mmap_fixed. If a call to mmap happens between the check addrspace_free(v, n) and mmap(v, n, prot, flags|_MAP_FIXED, fd, offset), then another mmap that happens between the two calls could, at least in theory, return a region within the same address space. The subsequent mmap fixed will happily succeed, even if there is an existing mapping for part of that address space.

    func mmap_fixed(v unsafe.Pointer, n uintptr, prot, flags, fd int32, offset uint32) unsafe.Pointer {
	 p := mmap(v, n, prot, flags, fd, offset)
	 // On some systems, mmap ignores v without
	 // MAP_FIXED, so retry if the address space is free.
	 if p != v && addrspace_free(v, n) {
		 if uintptr(p) > 4096 {
			 munmap(p, n)
		 }
		 p = mmap(v, n, prot, flags|_MAP_FIXED, fd, offset)
	 }
	 return p
    }

**Comment by ianlancetaylor** [comment]
I think you're right, but note that I think it can only happen if the Go program calls syscall.Mmap or if it calls C code that calls mmap.  Unfortunately I don't see how we can fix this for the case of C code calling mmap.

**Comment by minux** [comment]
I think the race won't happen due to higher level locking.
(e.g. mheap is always locked before growing, so no other
thread could request the same address concurrently.)

**Comment by ianlancetaylor** [comment]
@minux I agree that the runtime won't collide with itself, but a separate goroutine might be running at the same time and it might call syscall.Mmap explicitly.

**Comment by ianlancetaylor** [comment]
Ah, yes, I see what you mean.  We are only in trouble with MAP_FIXED, and that is not a case that is worth worrying about.

I'm going to close this issue.  @Eloff please feel free to reopen if you think we are missing something.

**Comment by Eloff** [comment]
I think it's OK to close, it's in a fallback path for who knows which OS
that doesn't handle hints with mmap. However, is not clear to me that it
could only happen with MAP_FIXED, there seems to be no reason to me why a
regular mmap can't succeed on another thread and return that address. It
seems to imply a lot more inside knowledge of how mmap works on a variety
of unixy systems than what I'm comfortable with. It may well be possible,
but it's already on a rare code path and the circumstances around the race
are likely very rare or even impossible. Code that crashes very
occasionally is still useful, in fact that describes pretty much every
software system out there. It's fine by me to focus on more important
things and address this when/if bug reports come in from the wild.

**Comment by ianlancetaylor** [comment]
An mmap without MAP_FIXED can't succeed, because the original mmap that ran before the call to addrspace_free did not succeed.

Well, I suppose it's possible that Go calls mmap, then some other thread calls munmap, then Go calls addrspace_free, then some other thread calls mmap, then Go calls mmap with MAP_FIXED.  If there were a way to fix that we should do it, but I don't think there is.

**Comment by Eloff** [comment]
The previous call ignored the hint, but it did succeed at another address.
It's a bit tough to imagine an algorithm that would let an unrelated mmap
succeed in another thread, giving it part of the address range checked as
free here. But I don't think it's impossible either, for the entire space
of imaginable implementations. But I also don't see a way to fix it. I'm
sure we've spent more energy on it already than the question deserves.
