### ISSUE TITLE
Hello world doesn't print to screen and program doesnt exit

### ISSUE THREAD

**Issue by mbudge** [golang/go#13255]
When I run the following code with the command "go.exe run main.go", the program doesnt print text to the screen or exit. 

    package main

    import "fmt"

    func main(){
        fmt.Println("Hello world")
    }

Line feeds

    package mainLF
    LF
    import "fmt"LF
    LF
    func main(){LF
        fmt.Println("Hello world")LF
    }LF

The following doesn't print to the command prompt either.

    package main

    //import "fmt"

    func main(){
        println("Hello world")
    }

The following gives the error "fmt imported but not used" so it must be doing something.

    package main

    import "fmt"

    func main(){

    }

GOROOT is set to C:\Go\

PATH: C:\Go\bin

Version  windows/386 on Windows 10

Filepath: c:\project

CMD: go run c:\project\main.go

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go\bin
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

![go](https://cloud.githubusercontent.com/assets/15329154/11171809/76c796d0-8bf1-11e5-883f-09f4ce001cc9.jpg)

**Comment by ianlancetaylor** [comment]
This is better discussed on the mailing list, where more people will see it.  Thousands of people are able to do this successfully, but I don't know what is going wrong for you.

I'll just note that in general you should never set GOROOT.

When you say that the program doesn't exit, what do you mean?  It just hangs there doing nothing?  How do you stop it?

Also, how did you install Go?

**Comment by mbudge** [comment]
No worries I'll use the mailing list next time.

I've removed gopath value and set it in the PATH variable instead.

I used go1.5.1.windows-386.msi on the download page. 

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by mbudge** [comment]
Here is an updated image 

![go](https://cloud.githubusercontent.com/assets/15329154/11179516/cdb7fda4-8c4b-11e5-8b92-69d2dcf6d01e.jpg)

Current output from go env

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\project
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by woanware** [comment]
What is the output from "go build"?

**Comment by mbudge** [comment]
Hi Woany,

It creates "project.exe" in the folder "c:\project". Nothing is output to the command prompt.

Thanks,

Budge

**Comment by woanware** [comment]
OK. Would have thought that the .exe would be in the "C:\project\src\project1" folder, if you are running "go build" from there?

**Comment by ianlancetaylor** [comment]
Due to anti-virus program; closing.

**Comment by woanware** [comment]
Stick to python ;-)
