### ISSUE TITLE
tour: purge state code snippet caches

### ISSUE THREAD

**Issue by ysagal** [golang/go#13252]
Context: https://tour.golang.org/moretypes/10

Lesson for making slices has example for nil slices (next lesson). Lesson for nil slices has example for append (next lesson). Lesson for append has example for range.

**Comment by adg** [comment]
The old code snippets are cached in your browser, and a page has been added or removed. Click 'Reset' in the code editor to see the correct content.

@campoy we need to make sure we don't store stale cache entries for changed pages. One approach would be to key the cache entries by page title. Or set a version number for the cache that we increment whenever we change the content.

**Comment by ysagal** [comment]
Ah, yes, thank you!

**Comment by adg** [comment]
@ysagal thanks for the report. =)

**Comment by campoy** [comment]
Solution proposed using hashes of the file content as cache id

https://go-review.googlesource.com/#/c/17407/1

**Comment by rsc** [comment]
Looks like https://go-review.googlesource.com/#/c/17407 fixed this.
