### ISSUE TITLE
path/filepath: confusing error message for Rel

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#13259]
This program
```
U:\>type main.go
package main

import (
        "fmt"
        "path/filepath"
)

func main() {
        fmt.Println(filepath.Rel(`c:\windows`, `d:\windows`))
}
```

outputs
```
 Rel: can't make \windows relative to \windows
```

but should output
```
 Rel: can't make d:\windows relative to c:\windows
```

Alex

**Comment by 0xmohit** [comment]
Currently the error message contains pathnames that are [Clean](https://golang.org/pkg/path/filepath/#Clean)ed after dropping the volumeName.  It may be preferable to instead show the original basepath and targpath in error messages.  If so, some existing tests break.  Should we display the original pathnames in the error messages and _fix_ the existing tests?
