### ISSUE TITLE
builtin for querying an item in a sorted list

### ISSUE THREAD

**Issue by jfcg** [golang/go#13254]
I come up with this often & had talked about it before https://groups.google.com/forum/#!topic/golang-nuts/tRXTa_cdnqg

I propose to have a generic builtin (like append) for comparable types, functionally like this:

```go
// Return indice of itm in sorted list srl or -1 if absent
func ListInd(itm string, srl []string) int {
	if len(srl) < 1 {
		return -1
	}
	var bisec func(a, b int) int

	bisec = func(a, b int) int { // [a, b)
		if b-a > 2 {
			m := (a + b) / 2
			if itm < srl[m] {
				return bisec(a, m)
			}
			if itm > srl[m] {
				return bisec(m+1, b)
			}
			return m
		}

		if itm == srl[a] {
			return a
		}
		a++
		if a < b && itm == srl[a] {
			return a
		}
		return -1
	}

	return bisec(0, len(srl))
}
```
If I write it in Go, I have the following drawbacks:
- At the line of "itm > srl[m]" there is a second (and redundant) comparison because Go does not have three-valued comparisons at the moment. For types like string this is not good (enough).
- All slice access in bisec() is safe but there are (redundant) boundary checks at each srl[] access.

A builtin function can overcome these drawbacks and it would be a very nice & needed addition to the language :)

**Comment by minux** [comment]
Did you know that we already have
https://golang.org/pkg/sort/#SearchStrings
in the standard library.

**Comment by jfcg** [comment]
Yes. All the search methods there have these drawbacks.
Maybe it is better for ListInd() to return (int, bool)
indice & was-in-the-list.

Also of course we dont need recursion, just a crude example ^_^

**Comment by minux** [comment]
The bar of adding new builtin functions is extremely high,
and I don't think this meets the bar (esp. because the
standard library already provides the functionality.)

**Comment by bradfitz** [comment]
Agreed.
