### ISSUE TITLE
json.Unmarshal bug

### ISSUE THREAD

**Issue by codinl** [golang/go#13260]
```
type A struct {
	P string `json:"p"`
}

func main() {
	aaa := []byte("{}")
	var a A
	err := json.Unmarshal(aaa, &a)
	if err != nil {                  // no error ？
		fmt.Println(err)
	}
}
```

**Comment by davecheney** [comment]
This is not an error. `{}` is a json object with no key/value pairs so none of the fields in `a` will be overwritten.

Let's move this to a forum since it's not a bug to track here on the bug tracker. See https://golang.org/wiki/Questions
