### ISSUE TITLE
doc: document that ppc64 requires Linux 2.6.37 or newer

### ISSUE THREAD

**Issue by pjbgtnj** [golang/go#13269]
When I cross-compile for ppc64 using go1.5.1 the net.listen (and tls.listen) function returns the error - "socket - function not implemented".   Doing an strace, it appears that system call 326 is being attempted and the function is not defined on this version of the kernel (centos 6.4 ppc64 2.6.32-358).  Looking deeper, the header file "/usr/include/asm/unistd.h" has many socket specific functions (sendto, recv, etc) commented out.   I believe the socket specific calls will need to mapped to socketcall like what is done in the linux_386 implementation.

**Comment by bradfitz** [comment]
If sockets didn't work in ppc64, how would all.bash pass for http://build.golang.org/? I see a big happy column of "ok" for ppc64.

Is this specifically a centos old kernel problem, or ...?

**Comment by davecheney** [comment]
I have a ppc64le system, can you please supply a small test program that
demonstrates the problem and I'll try to reproduce and diagnose it.

**Comment by pjbgtnj** [comment]
Will do first thing tomorrow morning, thanks.

**Comment by pjbgtnj** [comment]
I believe the following program should fail on the listen (with the socket function not implemented) but I can't test it until I go to work tomorrow.  I compile on my centos 6.4 x86_64 system for the redhat 6.4 ppc64 system with:   GOOS=linux  GOARCH=ppc64  go build test.go

package main

import (
	"log"
	"net"
)

func handleConnection(conn net.Conn) {
   defer conn.Close()
   log.Printf("Connected: %s\n", conn)
}

func main() {
	ln, err := net.Listen("tcp", ":8080")
	if err != nil {
		log.Fatalf("Err: %s\n", err)
	}
	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Fatalf("Err: %s\n", err)
		}
		go handleConnection(conn)
	}
}

**Comment by minux** [comment]
I tested your program on linux/ppc64 with kernel v3.16.7,
and it runs fine.

strace showed that socket(2) syscall completed successfully.

**Comment by davecheney** [comment]
Same here, on ppc64le 3.13.0

Can you please try your program on your system under strace
% go build x.go
% strace -f ./x

^ note the -f so strace follows the threads that the runtime creates
internally

**Comment by ianlancetaylor** [comment]
It looks like PPC GNU/Linux used to use socketcall and was changed to use direct socket system calls in http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=86250b9d12caa1a3dee12a7cf638b7dd70eaadb6 .  That was in 2010; I don't know which Linux kernel version it first appeared in.  The OP says Linux kernel version 2.6.32, though, and that was released December, 2009.

Have we documented a minimum Linux kernel version for PPC support?  If we did document it, where would that be?

**Comment by minux** [comment]
It first appeared in v2.6.37 (a nice trick is to use github to find out
which tags
contain a given commit:
https://github.com/torvalds/linux/commit/86250b9d12caa1a3dee12a7cf638b7dd70eaadb6
)

**Comment by minux** [comment]
https://golang.org/doc/install documents that for amd64/386/arm, the minimum
kernel version is 2.6.23. If we do document the minimum kernel for ppc64,
I think we can add it there.

(Perhaps we should just use socketcall on linux/ppc64, I presume that
socketcall
is still supported on recent kernels, right?)

**Comment by pjbgtnj** [comment]
@davecheney 
I trimmed the program down to just net.listen and it fails. The significant line in strace is:
SYS_326(0x2, 0x80801, 0, 0, 0) = -1  ENOSYS (Function not implemented). 

As minux indicates, the minimum version of linux for the PPC64 is most likely 2.6.37.  (This issue might be glance into the future.   When targeting a different OS/ARCH, should there also be a version so that the compiler can account for such things?)

**Comment by pjbgtnj** [comment]
Within a centos/redhat main revision they don't update kernel versions.  This means that all the 6.x releases will use the 2.6.32 kernel.  I need to convince the IT dept to upgrade to 7.x to get a more recent kernel.

**Comment by ianlancetaylor** [comment]
I don't feel any need to support CentOS 5, but CentOS 6 is not so terribly old given the point of CentOS.  I'm leaning toward changing the PPC support to use socketcall, as Minux suggested.  Does anybody who cares feel that that would be a mistake?

**Comment by davecheney** [comment]
@ianlancetaylor no objection to me, however that would mean our implicit support on ppc64 is a kernel <= 2.6.32. I don't think this is too big a burden, but I'm sure we will get bit by a small incompatibility in the future.

**Comment by rsc** [comment]
@davecheney I think you meant >= 2.6.32.

Given that the initial reporter says it's not worth worrying about CentOS 6, I'm not sure we should bother. Let's just document the requirement and wait for an actual request before adding more complexity.

**Comment by davecheney** [comment]
@rsc, I think I was a bit confused, other arches suggest the min kernel is 2.6.27, redhat 6 ships with 2.6.32 and the feature missing for this bug in 2.6.37, I'm not sure what that says about the documented min kernel for ppc64 (note on Ubuntu ppc64 support is somewhere in the 3.1x (where x is around 4) series )
