### ISSUE TITLE
cmd/compile: cannot take address of a struct literal

### ISSUE THREAD

**Issue by dvyukov** [golang/go#13261]
cmd/compile rejects to compile to following correct program:
```go
package main

func main() {
	switch &(struct{}{}) {
	}
}
```
```
./1.go:6: cannot take the address of struct {} literal
```

gotype and -oldparser eat it.

go version devel +25a28da Sun Nov 15 23:41:28 2015 +0000 linux/amd64

Found with GoSmith (https://github.com/dvyukov/gosmith).

**Comment by griesemer** [comment]
Started.
