### ISSUE TITLE
x/tools/cmd/godoc: start server before scanning $GOPATH

### ISSUE THREAD

**Issue by thewhitetulip** [golang/go#13278]
When we run godoc, it doesn't show any notification that the server has started, typically when I need godoc up and running I am in a middle of a programming crisis and only the doc can save me, but sadly it doesn't print when it is ready, I have to wait for some time or keep refreshing the page in my browser 100 times before it actually is started. So it would be great if we print this message before the call to HandleAndServe function, a way to notify that the server is up and running

**Comment by jnjackins** [comment]
On my laptop, the server finishes starting faster than I can switch to a browser window and press return. Maybe there is another issue here?

**Comment by adg** [comment]
It depends how ​big your workspace is. Sometimes it can take a few seconds
to spin up. I think this is a reasonable request.

**Comment by jnjackins** [comment]
Is this not not covered by the -v flag?

```
$ godoc -v -http :8000
2015/11/17 16:08:58 Go Documentation Server
2015/11/17 16:08:58 version = devel +babdb38 Tue Nov 17 04:06:32 2015 +0000
2015/11/17 16:08:58 address = :8000
2015/11/17 16:08:58 goroot = /Users/jnj/src/go
2015/11/17 16:08:58 tabwidth = 4
2015/11/17 16:08:58 search index disabled
name space {
	/:
		gated(os(/Users/jnj/src/go), 20) /
	/lib/godoc:
		mapfs /
	/src:
		gated(os(/Users/jnj/src/go), 20) /src
		gated(os(/Users/jnj), 20) /src
}
```

There are a couple function calls between these logs and http.ListenAndServe, but they are in new goroutines.

**Comment by thewhitetulip** [comment]
@jnjackins I guess there you misunderstood what I asked, i do not want to know each and every thing as in the -v flag, I just want to know when the server has started! just one line, `starting server on localhost`

**Comment by rsc** [comment]
I don't think godoc shoud print chatter unless asked (with -v). But it would be reasonable for godoc to start the server before scanning the entire $GOPATH. Then at least you can go to the page and get a "we're still indexing" or whatever the status is.

**Comment by agnivade** [comment]
Looks like both the CLs were abandoned. I have a CL prepared which returns a proper message before the scan is complete, so that the webserver is responsive and the scan can continue in the background.

Will send it across shortly.

**Comment by andybons** [comment]
Reverted in golang.org/cl/93115

**Comment by agnivade** [comment]
Oops, so sorry about this. I can't remember why I did not run the tests. My bad.

Anyways, so the `TestWeb` is failing because the http server has started in the background and it is replying with the "Scan in progress. Please try after sometime" message. So the strings which the test is looking for is not there. Hence the failure. 

I will send a CL with the proper fix.

On a side note, should we start running tests in try bots for this repo ?

**Comment by bradfitz** [comment]
Trybots need to be kicked off by a human. They just weren't kicked off.
