### ISSUE TITLE
encoding/json: Marshaller omits false booleans as if they were nil 

### ISSUE THREAD

**Issue by orcaman** [golang/go#13284]
It appears that the `Marshal` function from `encoding/json` treats false booleans as if they were `nil` values, and thus it omits them from the resulted json. I believe this behavior is a bug. I couldn't find reference in the json spec, but it has caused some issues with my client code, that makes a distinction between a non-existent boolean and a false boolean. 

See example here: http://play.golang.org/p/i3cNXqorif

**Comment by cespare** [comment]
This is working as intended. `false` is the zero value of booleans, and your json struct tag has `omitempty`. As you can see from `t2`, if you don't use `omitempty`, the value isn't omitted.

**Comment by cespare** [comment]
Actually that's slightly misleading: it's not that `omitempty` omits precisely zero values; the set of omitted values is listed in the Marshal documentation:

> The empty values are false, 0, any nil pointer or interface value, and any array, slice, map, or string of length zero.

**Comment by spenczar** [comment]
If you need to make a distinction between a non-existent boolean and false boolean, use a *bool in your struct, like this:
```
type t struct {
	Autoplay *bool `json:"autoplay,omitempty"`
}
```

You'll have to do the extra work of checking that t.Autoplay is not nil, but that's unavoidable - it sounds like you _want_ this ternary logic.

**Comment by orcaman** [comment]
@cespare Considering golang's design where primitive types are always initialized to empty values, your comment makes perfect sense. So I realize this is not a bug, but it's also somewhat confusing and perhaps even unexpected. When writing go code, this isn't a big deal. But un the case of `JSON` data moved from client to server (one of the largest use cases of `JSON`) , this makes go somewhat inconsistent with the rest of the world (clients and servers), and can confuse a lot of people. Not sure what a good solution would be. 

@spenczar that's a great idea, thanks. That's exactly what I was after.

**Comment by rsc** [comment]
A boolean only has two values. You can either send false or not, depending on what tag you put on the variable. If you need a three-valued boolean, that's not a boolean. As @spenczar suggested, *bool is a good choice in this case.
