### ISSUE TITLE
Suggestion: slice pointer bug is not noob-friendly, variable declaration is 1off

### ISSUE THREAD

**Issue by falafflepotatoe** [golang/go#13285]
Hi all.  I've written a simple slice function moveIdxToFront, and I'm getting the slice pointer bug, where I cannot reassign a slice. I thought I would ask what to do and leave a humble suggestion.

The premise: 

    idxstomove := []int{4,3}
    for i,v := range s {
         for j,k := range idsxtomove {
                  // move idxs to front of s
                  s = ?
     }}

The bug: matter what you do the 2nd time you modify `s` it pulls the value from the original `s` so your results come out wrong

Why it should be different: (Just for arguments sake)
* The code looks like it should work, but does not.
* The code is almost un-debuggable. Had I not remembered "that one time" a year ago I read about the slice gotchas I would not be able to debug this code
* This is a common paradigm. I've gotten this bug twice this week.
* I dont think users should want to spend 30-60 minutes debugging/rewriting this function that code should work, and compiles, but returns the wrong data.
* It's not very noob friendly code to write. I don't think it would even be possible for a new go-dev to write a func like this

Its almost a bug because even if i do `tmp = append(a[:i],a[i:])` then `a = tmp` it still ignores the new `a` values.

Code: https://play.golang.org/p/LMVtVWxHkP
If you want to show me how you would do this I would like to see it also. Its deceptively complex. Sorry the code isnt that good!

    package main
    import "fmt"
    func main() {
    	fmt.Println( moveValsToFrontFromRight([]int{1,2,3,2,1}, 2,1) )
    }
    
    func moveValsToFrontFromRight(a []int, vals ...int) []int {
    	for _, val := range vals {
    		for i := len(a)-1; i >= 0; i-- {
    			if val == a[i] {
    				fmt.Println("debug:", []int{a[i]}, a[:i], a[i+1:])
    				a = append([]int{a[i]}, append(a[:i], a[i+1:]...)...)
    				break
    			}
    		}
    	}
    	return a
    }
    
    // output: [1 1 1 2 1]  (or something)

My second suggestion is fix this for the next version if its not hard:

    length,half := len(s), length / 2
      ^                    // ^------ Compiler error: Length is undefined
    //^------- It's right there.

Thanks.

**Comment by adg** [comment]
I'm not sure what you're trying to do. You want to shift a bunch of values to the right?

Are you aware of the [copy function](https://golang.org/pkg/builtin/#copy)?

**Comment by adg** [comment]
BTW, this isn't really the right place for such discussions. Please see: https://github.com/golang/go/wiki/Questions

**Comment by falafflepotatoe** [comment]
@adg trying to shift to the left from the right.

**Comment by falafflepotatoe** [comment]
Heres another example:

    func moveFront(a []int, idxs ...int) []int {
	for i, _ := range a {
		for _, v := range idxs {
			if v == i {
				a = append([]int{a[i]}, append(a[:i], a[i+1:]...)...)
				break
			}
		}
	}
	return a
    }

	fmt.Println(moveFront([]int{1, 2, 3, 2, 1}, 2,3))
        //output [1 2 1 2 1]
        //should be [2 3 1 2 1]

**Comment by minux** [comment]
You assumed that in a for range loop, changes to the slice
of the range loop in the loop body will affect the future iterations
of the loop, but that's not the case.

http://play.golang.org/p/ZnTuUy_sDW

**Comment by falafflepotatoe** [comment]
@minux yea sorry I probably pasted bad code. This was my 2nd try at writing the func, the first was different. Thanks for the comment, I'll write a new func.

**Comment by falafflepotatoe** [comment]
One more example: https://play.golang.org/p/bfru7ekgOx

    package main
    import "fmt"
    import "sort"
    
    func moveIdxFront(a []int,i int, print bool) []int {
    	if print {
    		fmt.Println("suppos ret", []int{a[i]}, a[:i],a[i+1:])
    	}
    	return append([]int{a[i]}, append(a[:i],a[i+1:]...)...)
    }
    
    func moveFront(a []int, idxs ...int) []int {
    	b := make([]int,len(a))
    	copy(b,a)
    	sort.Sort(sort.IntSlice(idxs))
    	for _,i := range idxs {
    		fmt.Println("actual ret", moveIdxFront(b,i,true))
    		b = moveIdxFront(b,i,false)
    	}
    	return b
    }
    func main() {
    	a := []int{1, 2, 3, 2, 1}
    	fmt.Println(moveFront(a, 3, 2))
    }

    Output
  suppos ret [3] [1 2] [2 1]
  actual ret [2 1 2 2 1]
  suppos ret [1] [1 1 2] [1]
  actual ret [1 1 1 2 1]
  result: [1 1 1 2 1]

**Comment by falafflepotatoe** [comment]
edit: sorry. I think my example was not right
the 2nd append of course runs first:  `append( []int{a[i]}, append(a[:i], a[i+1:]...)...)`

ill write a good test case and write at the appropriate place

thanks all
