### ISSUE TITLE
optimizations for iterating over an array make invalid assumptions

### ISSUE THREAD

**Issue by BenLubar** [golang/go#13294]
`go version`: go version devel +babdb38 Tue Nov 17 04:06:32 2015 +0000 linux/amd64

Playground: http://play.golang.org/p/2xy228b6Sw

If the array is changed to be a slice, the program has the expected output.

**Comment by dominikh** [comment]
1) Simpler example: http://play.golang.org/p/ov-7rMdZ_g
2) Isn't this expected behaviour? The array is evaluated once at the beginning of the loop, and since it is an array, the loop is essentially operating on a copy.

**Comment by BenLubar** [comment]
Ah, right. I need to iterate over `&numbers` for it to do what I want.
