### ISSUE TITLE
x/net/context/ctxhttp: remove racy go1.4 support

### ISSUE THREAD

**Issue by pwaller** [golang/go#13293]
x/net/context/ctxhttp has code specifically to handle go1.4, and I believe this code is racy.

Details of this style of race: https://github.com/golang/go/issues/11013

[No synchronization here](https://github.com/golang/net/blob/1d9fd3b8333e891c0e7353e1adcfe8a612573033/context/ctxhttp/cancelreq_go14.go#L21)...
...[Against the request going in flight](https://github.com/golang/net/blob/1d9fd3b8333e891c0e7353e1adcfe8a612573033/context/ctxhttp/ctxhttp.go#L35-L41).

[Example of the sort of thing I understand that needs to be done with the 1.4 cancellation interface](https://github.com/golang/go/blob/0cd2999c3b7a853f48af1146db427365a09f8b38/src/net/http/httputil/reverseproxy.go#L137
) (I wrote this with Bradfitz' input, which is when I became aware of the issue).

The problem is the definition of the canceller API in Go1.4 - cancelling the request is only a valid thing to do once the request is in flight, otherwise the cancellation is ignored. Hence the need for the req.Body acrobatics in reverseproxy, and hence the improved API in 1.5.

[golang-dev discussion](https://groups.google.com/d/topic/golang-dev/vRUomu3aSPQ/discussion).

**Comment by pwaller** [comment]
@dsymonds [this method that I linked to is racy](https://github.com/golang/go/blob/0cd2999c3b7a853f48af1146db427365a09f8b38/src/net/http/httputil/reverseproxy.go#L137)?

**Comment by okdave** [comment]
@pwaller would that approach work if there was no request body?

The 1.4 support is racy, yes. I'm not too inclined to invest in fixing it though since a correct solution is going to increase complexity dramatically for little benefit.

**Comment by pwaller** [comment]
@okdave, I understand that it works if there is no request body, yes. The body is written as part of [`Request.Write(conn)`](https://github.com/golang/go/blob/53c21df12153871bf3bfcc8de25ebab0ffc008c7/src/net/http/request.go#L478), which reads the body, [if it is present](https://github.com/golang/go/blob/master/src/net/http/transfer.go#L212) (which it is, in the reverseproxy example). So it is certain to be read from if it's not nil, even if there are zero bytes to read.

I'd like to see this fixed this because it means leaking connections and goroutines to docker in [go-dockerclient](https://github.com/golang/go/blob/master/src/net/http/transfer.go#L212), which a long lived process of mine uses. I want to [implement cancellation in go-dockerclient](https://github.com/fsouza/go-dockerclient/issues/161) in terms of ctxhttp but don't feel comfortable doing so while I know there is some chance that connections are leaked if someone is unlucky enough to build with go 1.4. The presence of this leak makes it harder to identify and diagnose other leaks.

The failure I'm concerned about is particularly pathological because the other side (docker) of the connection will hold the connection open indefinitely in some cases, so it could quickly run out of file descriptors and leak an unreasonable number of goroutines.

By avoiding the complexity in the library, that is pushing it onto the users! :)

**Comment by pwaller** [comment]
By the way, I just ran the ctxhttp tests under go1.4 with this tweak:

```go
func canceler(client *http.Client, req *http.Request) func() {
	rc, ok := client.Transport.(requestCanceler)
	if !ok {
		return func() {
			log.Printf("Not a canceler: %T", client.Transport)
		}
	}
	return func() {
		log.Printf("Using 1.4 canceler")
		rc.CancelRequest(req)
	}
}
```

The output is this:

```
=== RUN TestCancel
2015/11/18 08:57:32 Not a canceler: <nil>
```

This would appear to indicate that anyway, the tests aren't exercising the canceller on go1.4, and possibly the canceller is having no effect anyway?

**Comment by okdave** [comment]
Interesting. ctxhttp.Do was not really designed with cancelling after it returned in mind. @broady, @bradfitz what are your thoughts on that?

**Comment by pwaller** [comment]
I have opened https://github.com/golang/go/issues/13325 for the above question of @okdave to avoid confusing this issue, which is about the go1.4 code being racy *before* the request is in flight. 

(Aside: So now we have a problem where the request can't be cancelled before, and it can't be cancelled after, which means there is only a very "narrow" window — during the exchange of headers — where cancellation does anything. If that's ctxhttp working as intended, the documentation needs to be improved.)

**Comment by pwaller** [comment]
Note: I ended up not using this for my original use case, so I'm unlikely to follow this up. I don't suppose anyone else is either, since 1.4 is soon to be two major versions behind and few people are likely to hit this. I would be OK with closing this issue.

**Comment by ianlancetaylor** [comment]
We may as well leave this open to actually drop the Go 1.4 support soon.

**Comment by broady** [comment]
It's been removed.
