### ISSUE TITLE
x/crypto/ocsp: Certificate Transparency, Stapled SCTs

### ISSUE THREAD

**Issue by mehmooda** [golang/go#13297]
Support for Stapling SignedCertificateTimestamps would be nice:

To implement:
- RFC6960 Single Response Extensions EASY. crypto.pkix.Extension
- RFC6962 Certificate Transparency OCSP MEDIUM

**Comment by agl** [comment]
SCTs via the TLS handshake are already supported. At some point it'll make sense to also support validation of SCTs and thus embedded SCTs in certificates and stapled OCSP responses. But I don't think that time is yet as Chrome is still developing this and Go clients aren't the best early use-case for CT.

**Comment by mehmooda** [comment]
I should have probably created 2 issues. What is required in go is only extension support.

SCTs can be provided by another package at least for now.

All that is required to support extensions is:
https://go-review.googlesource.com/#/c/16946/
