### ISSUE TITLE
Setting up time in UTC

### ISSUE THREAD

**Issue by markcampanelli-wf** [golang/go#13292]
It would be nice to have a TimeUTC object that would always represent time in UTC.

For example, one could call TimeUTC.Now() instead of Time.Now.UTC().

Many packages may want to explicitly specify all times to be in UTC so as to circumvent location headaches and confusion. A TimeUTC object makes this specification much more transparent.

Trying to change the location/timezone on a TimeUTC object would be possible, but it would return a Time object instead of a TimeUTC object.

**Comment by bradfitz** [comment]
Please bring this to the golang-nuts mailing list for discussion first.

**Comment by vgalu** [comment]
We use something like this in production (and inject it as required).

type TimeProvider interface {
	Now() time.Time
}

func NewLocalTimeProvider() interfaces.TimeProvider {
	localTimeProviderSingletonGuard.Do(func() {
		localTimeProviderSingleton = &localTimeProvider{}
	})

	return localTimeProviderSingleton
}

func (tp *localTimeProvider) Now() time.Time {
	return time.Now()
}

func NewUTCTimeProvider() interfaces.TimeProvider {
	utcTimeProviderSingletonGuard.Do(func() {
		utcTimeProviderSingleton = &utcTimeProvider{}
	})

	return utcTimeProviderSingleton
}

func (tp *utcTimeProvider) Now() time.Time {
	return time.Now().UTC()
}

**Comment by markcampanelli-wf** [comment]
Thanks @vgalu!
