### ISSUE TITLE
Additional convenience constants for RFC3339 in time package

### ISSUE THREAD

**Issue by markcampanelli-wf** [golang/go#13291]
Along with the formatting constants time.RFC3339 and time.RFC3339Nano, it would be very convenient to have time.RFC3339Milli and time.RFC3339Micro with the indicated second precisions.

**Comment by bradfitz** [comment]
Why?

**Comment by markcampanelli-wf** [comment]
Because it would be convenient and more self-documenting. For example, our
systems can have a maximum precision of microseconds using RFC3339, and

timestampFormat := time.RFC3339Micro

is more semantically transparent than

timestampFormat := "2006-01-02T15:04:05.999999Z07:00"

Other "Handy time stamps" are already provided, so why not this?



*Mark CampanelliSr. Quality Assurance AnalystWorkiva*

*formerly WebFilings*448 East Main St., Suite 202, Bozeman, MT, 59715
*Email:* Mark.Campanelli@workiva.com
*Office:*
*Mobile:* 1-720-666-8842

**Comment by bradfitz** [comment]
No, thanks. I was hoping for some argument that there was a popular spec I'd never heard of which relied on such formats.

I think this is well beyond the point of diminishing returns. It adds more weight to the time package than utility.

We've both now written more keystrokes in this bug than we'd ever save users wanting these formats. But we would've added more cognitive load to the docs.

Closing as not meeting the bar.

**Comment by dominikh** [comment]
> timestampFormat := time.RFC3339Micro 
> is more semantically transparent than 
> timestampFormat := "2006-01-02T15:04:05.999999Z07:00" 

You're free to define your own constants in your own packages.

**Comment by aaronkavlie-wf** [comment]
Why are `StampMilli` and `StampMicro` included? Do they add cognitive load?
This would make the RFC precisions consistent with that.

The need for microsecond precision comes into play with serialization produced and consumed across languages. Python [cannot deal with nanoseconds](https://bugs.python.org/issue15443).

**Comment by aaronkavlie-wf** [comment]
Nanosecond precision also [causes trouble with rsyslog](https://github.com/spotify/syslog-redirector/pull/6).

**Comment by theckman** [comment]
I agree, it seems silly to have the useless timestamp format with millisecond precision yet the `RFC 3339` formatter does not. I asked for something similar in a duplicate issueI opened (#13424).
