### ISSUE TITLE
gccgo, runtime:  Wrong size for malloc of P struct in runtime_allp.

### ISSUE THREAD

**Issue by laboger** [golang/go#13309]
I don't have a specific failure due to this, but was looking at the code for allocation of the P, M, and G structs within proc.c, and it looks to me like the size being used to allocate a P struct for the runtime_allp array is incorrect.  The call to runtime_mallocgc for a new P struct is using the size of a pointer instead of the size of the struct.  The line of code in procresize in libgo/runtime/proc.c looks like this:

`p = (P*)runtime_mallocgc(sizeof(*p), 0, FlagNoInvokeGC);`

Since it should be allocating a P struct I think it should be sizeof(P) instead.

**Comment by ianlancetaylor** [comment]
This looks OK to me.  This is C, not Go.  p is a variable.  `sizeof(*p)` returns the size of the type to which p points, which in this case is P.
