### ISSUE TITLE
"Code is outside of application range" when building Go tip inside docker

### ISSUE THREAD

**Issue by karalabe** [golang/go#13308]
I've tried to build the latest master branch within a docker container bootstrapped with Go 1.4.3. The build succeeded, but the tests afterwards failed with: https://gist.github.com/karalabe/c0e2ca28abaeae5d29ac . Any idea if this is a failing develop branch or some deeper issue?

**Comment by ianlancetaylor** [comment]
I think this is a dup of #12898 .
