### ISSUE TITLE
cmd/compile: regression in recovery from malformed statement

### ISSUE THREAD

**Issue by rsc** [golang/go#13319]
/tmp/xx.go:

	package main
	
	func f() {
		switch x {
		case 1:
			f(1, g()
		case 2:
			f()
		case 3:
			f(1, g()
		}
	}

go tool compile -oldparser /tmp/xx.go: (yacc parser)

	/tmp/xx.go:6: syntax error: unexpected semicolon or newline, expecting )
	/tmp/xx.go:10: syntax error: unexpected semicolon or newline, expecting )

Note that it successfully got back on track and processed case 2 with no problems. It then found the next syntax error, namely the one in case 3.

go tool compile /tmp/xx.go: (new parser)

	/tmp/xx.go:6: syntax error: need trailing comma before newline in argument list
	/tmp/xx.go:7: syntax error: unexpected case, expecting expression
	/tmp/xx.go:8: syntax error: unexpected f

It never recovers. The one syntax error produces three errors (only one of them real) and misses the later error.

**Comment by griesemer** [comment]
In progress.
