### ISSUE TITLE
syscall: namespace tests fail on Linux with RHEL7.2 ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#13312]
When building gccgo or gc on RHEL7 2 and running the testsuite, the testcase exec_linux_test.go fails for both gccgo and gc.  This happens with gccgo built from trunk and with golang from master with this output from go version:

go version devel +6bf794a Wed Nov 18 19:00:45 2015 +0000 linux/ppc64le

With golang, there are 3 error messages:

 go test .
--- FAIL: TestCloneNEWUSERAndRemapNoRootDisableSetgroups (0.00s)
	exec_linux_test.go:57: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestCloneNEWUSERAndRemapNoRootSetgroupsEnableSetgroups (0.00s)
	exec_linux_test.go:97: Unprivileged gid_map rewriting with GidMappingsEnableSetgroups must fail
--- FAIL: TestEmptyCredGroupsDisableSetgroups (0.00s)
	exec_linux_test.go:105: fork/exec /usr/bin/whoami: invalid argument
FAIL
FAIL	syscall	0.014s

And with gccgo there are 2:
make syscall/check
--- FAIL: TestCloneNEWUSERAndRemapNoRootDisableSetgroups (0.00s)
	testing.go:284: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestCloneNEWUSERAndRemapNoRootSetgroupsEnableSetgroups (0.00s)
	testing.go:284: Unprivileged gid_map rewriting with GidMappingsEnableSetgroups must fail
FAIL

I know there was another issue for this test related to whoami but the error message was not the same.  

I don't see these failures when I build gccgo or golang on other platforms (Ubuntu 14.04, 14.10, SLES12SP1) with the same level of source for the compilers.

uname -r output:

3.10.0-313.el7.ppc64le

**Comment by ianlancetaylor** [comment]
CC @LK4D4

**Comment by LK4D4** [comment]
@laboger Could you check `CONFIG_USER_NS` in your kernel config, pls?

**Comment by LK4D4** [comment]
I suppose it might be because of SeLinux rules. Could you try to disable it and rerun? Thanks!

**Comment by laboger** [comment]
CONFIG_USER_NS=y
I tried:
>setenforce 0
>getenforce
Permissive

tests still failed as before.

I set SELINUX to disabled and rebooted.
>getenforce
Disabled

tests still failed as before.

I also tried a fedora21 ppc64le system and that passes with selinux enabled.  Only RHEL 7.2 fails.

**Comment by LK4D4** [comment]
@laboger Can you try to run tests from root? I'll try to setup VM with rhel 7.2 myself to look at problem.

**Comment by laboger** [comment]
Same failures when run as root.

**Comment by LK4D4** [comment]
@laboger Are you sure that tests names not different? Those tests should be skipped with `root`.

**Comment by laboger** [comment]
Oops sorry I wasn't expecting the failing testnames to be different and didn't look closely.  

Here's my screen output:
[root@willow2 syscall]# pwd
/home/boger/golang/gitsrc/latest/go/src/syscall
[root@willow2 syscall]# go test .
--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
	exec_linux_test.go:57: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
	exec_linux_test.go:57: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestEmptyCredGroupsDisableSetgroups (0.00s)
	exec_linux_test.go:105: fork/exec /usr/bin/whoami: invalid argument
FAIL
FAIL	syscall	0.018s
[root@willow2 syscall]# pwd
/home/boger/golang/gitsrc/latest/go/src/syscall
[root@willow2 libgo]# which go
/home/boger/golang/gitsrc/latest/go/bin/go

And with gccgo, I have to hit Ctrl-C to get the output if I run as root:

root@willow2 libgo]# make syscall/check
^C--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
	testing.go:284: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
	testing.go:284: Cmd failed with err fork/exec /usr/bin/whoami: invalid argument, output: 
/home/boger/gccgo.work/trunk/bld/../src/libgo/testsuite/gotest: line 625: kill: (7658) - No such process

**Comment by mrunalp** [comment]
The unshare system call is returning EINVAL.

**Comment by LK4D4** [comment]
So, it's bug in RHEL, which must be fixed. I'm glad that we helped with finding it :)

**Comment by mrunalp** [comment]
mount namespace isn't supported with user namespace in RHEL 7.2 as some patches haven't been backported. So, this is expected behavior for now.

**Comment by LK4D4** [comment]
@mrunalp I don't see mount namespaces in tests. Maybe *without* mount namespaces?

**Comment by mrunalp** [comment]
@LK4D4 Let me try that. I tried with everything in my testing.

**Comment by mrunalp** [comment]
@LK4D4 You are right. That fails as well. I am following up with RHEL engineers.

**Comment by mrunalp** [comment]
One has to enable user namespace support with a kernel boot option as it is in tech preview right now. After adding `user_namespace.enable=1` as a boot option `unshare -Ur` works for me.

**Comment by rsc** [comment]
From @mrunalp's comments it sounds like this is not a Go bug.

**Comment by rsc** [comment]
(We could of course disable the test, if this is important to any developers on RHEL 7.2 and we can detect that case.)
