### ISSUE TITLE
net/http: invalid method ""

### ISSUE THREAD

**Issue by nathan-osman** [golang/go#13311]
The [documentation for `http.Request`](https://github.com/golang/go/blob/master/src/net/http/request.go#L76) clearly states:

> "For client requests an empty string means GET."

However, when I attempt to make an HTTP request (using `http.DefaultClient.Do()`) with `Method` set to an empty string, I wind up with the following error:

    net/http: invalid method ""

### Details

    $ go version
    go version devel +6bf794a Wed Nov 18 19:00:45 2015 +0000 linux/amd64

**Comment by nathan-osman** [comment]
Seems like this bug was introduced in this commit: a734a8550a17e54548a6c7ebb3220c33d417e767.

**Comment by bradfitz** [comment]
Whoops, thanks. Sent https://go-review.googlesource.com/16952
