### ISSUE TITLE
golang 1.5.1 install problem from source code

### ISSUE THREAD

**Issue by xjg2010go** [golang/go#13322]
Hi:
   when I install golang 1.5 from souce code,it turn out follow this:

[root@yf_27_189 src]# ./all.bash 

##### Building Go bootstrap tool.
cmd/dist

go tool dist: cannot invoke C compiler "gcc -std=gnu99": exec: "gcc -std=gnu99": executable file not found in $PATH

Go needs a system C compiler for use with cgo.
To set a C compiler, export CC=the-compiler.
To disable cgo, export CGO_ENABLED=0.

Has somebody gotten into this trouble. please tell me how to solve this. thanks.

**Comment by ianlancetaylor** [comment]
Please don't use the issue tracker to ask questions.  See https://golang.org/wiki/Questions instead.

Thanks.

Try not setting CC in your environment.
