### ISSUE TITLE
x/net/context/ctxhttp: Request not cancelled once .Do() returns

### ISSUE THREAD

**Issue by pwaller** [golang/go#13325]
If a HTTP request is cancelled via a context once .Do() has returned, the cancellation request is ignored.

[Consider this test in x/net/context/ctxhttp](https://github.com/golang/net/blob/1d9fd3b8333e891c0e7353e1adcfe8a612573033/context/ctxhttp/ctxhttp_test.go#L47-L60):

```go
func TestCancelAfterRequest(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())

	resp, err := doRequest(ctx)

	// Cancel before reading the body.
	// Request.Body should still be readable after the context is canceled.
	cancel()

	b, err := ioutil.ReadAll(resp.Body)
	if err != nil || string(b) != requestBody {
		t.Fatalf("could not read body: %q %v", b, err)
	}
}
```

Unfortunately, I think the test could be problematic for many useful cases for cancelling http requests.

The immediate use case I have is to [attach to the stdout of a docker container over docker's http endpoint](http://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#attach-to-a-container), and disconnect when a client's interest in the output goes away. Otherwise resources are leaked, since the stdout might not otherwise go away. See https://github.com/fsouza/go-dockerclient/issues/161. Secondly, cancelling a build once it is in progress, where the build output is being streamed to you: https://github.com/fsouza/go-dockerclient/issues/182.

Here's an alternative "test" which simulates what I described above, exercising cancellation once Do() has returned. Currently, it hangs forever:

```go
func TestCancelAfterRequest(t *testing.T) {
	var okHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		<-w.(http.CloseNotifier).CloseNotify()
	})

	serv := httptest.NewServer(okHandler)
	defer serv.Close()

	ctx, cancel := context.WithCancel(context.Background())
	resp, err := Get(ctx, nil, serv.URL)

	cancel()

	var bs [1]byte
	n, err := resp.Body.Read(bs[:])
	log.Printf("n, err := %v, %v", n, err)
}
```

It's fairly obvious from [reading the implementation](https://github.com/golang/net/blob/1d9fd3b8333e891c0e7353e1adcfe8a612573033/context/ctxhttp/ctxhttp.go#L41) that the canceler has no effect called once `.Do()` returns, however it is not obvious from the documentation.

See also #13293, and [golang-dev discussion](https://groups.google.com/d/topic/golang-dev/vRUomu3aSPQ/discussion).

**Comment by okdave** [comment]
I'm taking a look at this now. I double checked that closing the request's `Cancel` channel after `Do` return does behave like you'd expect, so I'm just trying to work out the best way to plumb that into the `ctxhttp` package.

FWIW, there is a slight bug in the test above: since the headers are never being flushed the call to `Do` is never even returning. You can fix that by writing sufficient data to the body, or by calling `Flush`:

     w.WriteHeader(http.StatusOK)
     w.(http.Flusher).Flush()

**Comment by pwaller** [comment]
@okdave was this supposed to be closed when https://go-review.googlesource.com/#/c/18188/ was merged?

**Comment by bradfitz** [comment]
Looks like it.
