### ISSUE TITLE
"could not build go file"

### ISSUE THREAD

**Issue by as1ndu** [golang/go#13329]
....."cannot find source files"

**Comment by ianlancetaylor** [comment]
Please don't use the issue tracker to ask questions.  See https://golang.org/wiki/Questions .  Thanks.

If there is a bug here, please feel free to reopen.  We will need a lot more information.  You need to tell us precisely what you did, precisely what happened, and what you expected to happen instead.  Think about what it would take us to recreate the problem ourselves.
