### ISSUE TITLE
time.Format returns a strange result on mac

### ISSUE THREAD

**Issue by AnotherGoogleFans** [golang/go#13321]
The code is simple:

<code>package main

import (
	"fmt"
	"time"
)

func main() {
	mytime := time.Now()
	fmt.Println(getDatabaseName(mytime))

}

func getDatabaseName(createAt time.Time) string {
	return createAt.Format("mdata_20060102")
}

</code>

I thought it should retuen "mdata_20151119" but it returned "mdata190151119".
I don't know if it's a bug.
Mac.Go 1.5.1

**Comment by ianlancetaylor** [comment]
In a time format, "_2" is the two digit day.  That is why it is turning into "19" in your example.  You need to do something like `"mdata_" + createAt.Format("20060102")`.
