### ISSUE TITLE
proposal: add time.MustParse

### ISSUE THREAD

**Issue by miku** [golang/go#13328]
Already in the standard library:

* [template.Must](https://golang.org/pkg/text/template/#Must)
* [regexp.MustComplile](https://golang.org/pkg/regexp/#MustCompile)

As above, the major use case would be initialization.

    import "time"

    var Gutenberg = time.MustParse("2006", "1450")
    ....

    if pubDate.Before(Gutenberg) {
            fmt.Println("probably not printed")
    }

One third-party library [implements this](https://github.com/jinzhu/now/blob/ce80572eb55aa0ac839330041ca9db1afa5f1f6c/now.go#L170).

**Comment by dominikh** [comment]
Templates and regexps are generally provided by the programmer. Input to time.Parse is generally user input. Why would you initialize a variable with time.Parse instead of time.Date?

**Comment by robpike** [comment]
I agree with dominikh. I've never created a time like this at package level. This doesn't seem like a worthwhile contribution.

**Comment by cespare** [comment]
I've wished for MustParse a few times, particularly when creating some testing timestamps or when hardcoding a cutoff (similar to the example).

**Comment by miku** [comment]
> I've wished for MustParse a few times.

Me as well, e.g. in tests. However, I understand that it's probably to little of a use case.
