### ISSUE TITLE
fmt: String format %+d treats zero as a positive number

### ISSUE THREAD

**Issue by mcmil** [golang/go#13326]
Formatting zero using the + flag in `fmt.Printf("%+d",0)` results in `+0` output. It seems that it is a bug, since zero is neither positive nor negative. I would expect a simple `0` as an answer. 

Sample: http://play.golang.org/p/XhcQmGYXMC

**Comment by robpike** [comment]
Working as intended. As the documentation says:

    +	always print a sign for numeric values

You can argue whether 0 is positive, but you can't argue that it's not numeric.
