### ISSUE TITLE
cmd/go: Make go get -u update existing packages, or add another flag

### ISSUE THREAD

**Issue by zimmski** [golang/go#13332]
There is a constant stream (golang/lint#173, golang/lint#169, golang/lint#168, golang/lint#167, golang/lint#165 this list goes on and on) of user for golint that have outdated packages. This reports make it apparent that the `-u` flag of `go get` is kind of flawed. As the documentation for it states

> By default, get uses the network to check out missing packages but does not use it to look for updates to existing packages.

The wording "by default" would suggest that there is another flag which does update existing packages but it seems that this is still missing.

I am happy to work on this, but would first like to discuss if this should be another flag, and if so, what its name should be.

**Comment by dsymonds** [comment]
The golang/lint bugs are often due to the move of x/tools from code.google.com to github. There is, of course, a general class of problems here to do with the use of vanity import paths, but the specific case of the Go subrepos is a particularly notable instance of that class, and I wonder if it would be worth explicitly checking for them in `go get` even if we don't try to solve the general class.

**Comment by adg** [comment]
The wording is "By default, **get** uses..." (emphasis mine).

> The -u flag instructs get to use the network to update the named packages
> and their dependencies.  By default, get uses the network to check out
> missing packages but does not use it to look for updates to existing packages.

So `go get -u` updates the named packages *and* their deps. `go get` without the flag just downloads missing packages.

**Comment by dsymonds** [comment]
Note that it only updates the particular checkout of a package (e.g. approximately `git pull`); it doesn't "update" in the semantic sense if a vanity import path changes where it points.

**Comment by adg** [comment]
@dsymonds hm, that seems like an oversight. We should probably print an error in that case.

**Comment by dominikh** [comment]
Didn't f3a98dee27540afab414d3201aff18f30c2b163e address the issue of vanity paths changing where they point?

**Comment by dsymonds** [comment]
I'm guessing f3a98de only checked the named package, not its dependencies.

**Comment by rsc** [comment]
"go get -u" does update existing packages. Maybe there is something wrong with something else. If so, please file a separate bug.
