### ISSUE TITLE
runtime: TestStackBarrierProfiling failing on ppc64, ppc64le and mips64

### ISSUE THREAD

**Issue by minux** [golang/go#13334]
On linux/mips64:
`panic: fatal error: mallocgc called with gcphase == _GCmarktermination`
http://build.golang.org/log/2f49c7ce157ca522bfd747254573ce47c7a6564c

On linux/ppc64 and linux/ppc64le:
```
--- FAIL: TestStackBarrierProfiling (0.61s)
	pprof_test.go:338: subprocess failed with signal: segmentation fault:
FAIL
```
http://build.golang.org/log/af07ab5aa4c14e100952d98de41012f28a302b00
http://build.golang.org/log/d8c0744f5e27b972a383bb3dae01834cb2d601ce

/cc: @aclements

**Comment by aclements** [comment]
I'm working on getting access to a ppc64 box I can debug this on (the one I had access to went away).

My completely unsubstantiated guess is that GODEBUG=gcstackbarrierall=1 just doesn't work on ppc64. It chews up a lot of stack space and it may just chew up too much on ppc64.

**Comment by aclements** [comment]
It looks like my guess was right, so I'll probably just disable this test on ppc64 (it's not worth making gcstackbarrierall work on ppc64).

The mips64 failure looks like the test is catching a genuine bug.

**Comment by aclements** [comment]
624d798 fixed the ppc64 bug and the mips64 bug is a dup of #12528.
