### ISSUE TITLE
proposal: cmd/go get fork

### ISSUE THREAD

**Issue by mmindenhall** [golang/go#13333]
Working with forks (specifically github, but might apply elsewhere) is complicated (see discussions/blogs [here](https://www.reddit.com/r/golang/comments/2jdcw1/how_do_you_deal_with_github_forking/), [here](http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html), and [here](https://blog.splice.com/contributing-open-source-git-repositories-go/)).

The generally accepted practice is:

1.  `go get` the original project
1.  Fork the project in your github account
1.  Within the project source tree in your GOPATH, add your fork as a new remote
1.  Make changes, test, push to your fork, submit PR to project owner

If I'm the one making changes to the forked repo, this workflow is fine.  But once I'm finished and need to share those changes with the rest of my team, or want those changes pulled into a CI or test environment, it gets ugly.  I can either:

1.  Have everyone else on the team follow steps 1-3 above...and hack something into CI.  This is burdensome for the team, and could be difficult to get/keep working in CI.
1.  Change all internal imports within the fork from "github/com/projectcreator/coolproject" to "github.com/myaccount/coolproject", and have team members and CI `go get` that instead.  This makes it harder to submit PRs back to original project, harder to keep in sync with the original project, and is time consuming.

I would like `go get` to handle this case for me by creating a symlink within my GOPATH:

```
GOPATH/src/github.com/projectcreator/coolproject -> GOPATH/src/github.com/myaccount/coolproject
```

To do this, I would envision something like the following command:

```
$ go get -u -link github.com/projectcreator/coolproject github.com/myaccount/coolproject
```

Now I, other team members, and CI can use one simple command to switch from using the original project to the fork.

Additional thoughts:
- After linking, a `go get` for the original project should fail with an appropriate error message.  This will serve as a reminder that the project at that path is currently linked.
- There should be a way to unlink a project (either a new flag, or force with `-f`)
- Yes, I know I could manually create symlinks, but the idea here is consistent tooling to solve a common problem.

**Comment by adg** [comment]
It's a nice idea, but why not write a stand-alone tool to do it before we try to design it for the `go` command specifically?

**Comment by mmindenhall** [comment]
I could give it a shot.  But it looks like it wouldn't play as nice with `go get`.  I just tried the following:

1.  Created symlink from:

    ```
    GOPATH/src/github.com/symlinktest/etcd -> ../coreos/etcd
    ```
1.  `$ go get -u github.com/symlinktest/etcd`

The `go get` command succeeded in updating github.com/coreos/etcd.  I would want this to fail or emit a warning.

**Comment by rsc** [comment]
Like adg said, I think the solution here is to write a stand-alone tool and demonstrate that the functionality is correct, before adding it to cmd/go.
