### ISSUE TITLE
doc: bad link in concurrent pi example

### ISSUE THREAD

**Issue by utkbansal** [golang/go#13345]
The concurrent pi example at https://golang.org/  (Code at - go/doc/play/pi.go) refers to the url - http://goo.gl/ZuTZM for more details of the algorithm for the calculation. But this gives a HTTP 404 error.

**Comment by rsc** [comment]
New link:
https://web.archive.org/web/20130525072912/http://www.mprescient.com/journal/2011/6/16/is-scala-or-go-the-next-java.html
