### ISSUE TITLE
can add mmap file api?

### ISSUE THREAD

**Issue by runner-mei** [golang/go#13357]
mmap file is very important for the server, can add it to os package.

like https://github.com/edsrzf/mmap-go

**Comment by minux** [comment]
The syscall package contains Mmap and related syscalls.

I don't think a portable memory mapped file facility needs to live inside
the standard library.

A go-gettable package is perfectly fine.

**Comment by ianlancetaylor** [comment]
I agree with minux: in syscall is sufficient.
