### ISSUE TITLE
net: case conversion for hostname in local database 

### ISSUE THREAD

**Issue by mikioh** [golang/go#13359]
The commit d96a3a2d113909a470d2fd039018e1852a8d72b8 makes hostname entries in local database lowercase forcibly during go1.6 development. I don't think it's a good idea because /etc/hosts-like local database is a last resort for name resolution and https://tools.ietf.org/html/rfc4343 never says that "don't preserve case on input and output" for some reasons; perhaps it was for internetworking with old-plain systems and it is just for future use.

I don't see any rationale for the change in d96a3a2d113909a470d2fd039018e1852a8d72b8, so can you please restore the behavior that preserves case on input and output?

Note that we know a few name resolver libraries don't preserve case of hostnames and DNS labels, for example libc for OS X/iOS that supports both unicast and multicast DNS, but I still don't think we need to do case conversion for now especially with inconsistency that providing case-converted hostnames and case-preserved DNS labels.

**Comment by bradfitz** [comment]
Why?

That commit fixed a bug. Are you proposing un-fixing that bug? Or fixing it a different way? How?

**Comment by mikioh** [comment]
> Why?

I think I've already described that that commit fixed a bug in a wrong way. Like handling DNS labels, we need case insensitivity comparison with preserving case on input and output, not case conversion on input and output.

**Comment by rakyll** [comment]
Lowercased host is only preserved in the internal cache for comparison. It is not mutating anything. Could you explain the case with a snippet where it breaks things? I guess I am missing something.

**Comment by mikioh** [comment]
See golang.org/cl/17210.
