### ISSUE TITLE
net: calculation of IPv6 common prefix length is wrong

### ISSUE THREAD

**Issue by mikioh** [golang/go#13360]
Just a reminder.

The commit adb1e030136f14ef8434930f15a04a74568a5948 leaves the issue on calculation of Pv6 common prefix length. It assumes that there's no prefix longer than 64-bit. Of course the assumption is wrong. We perhaps see that some network operators want to use /96 for IPv4-embedded IPv6 addresses.

**Comment by bradfitz** [comment]
The common prefix length function isn't exposed anywhere.

It's specifically there for RFC 6724 where I believe it functions as needed. Feel free to reopen if you have a concrete example of something that this breaks, or somehow that this violates the RFCs.
