### ISSUE TITLE
Use of internal package not allowed in go1.5

### ISSUE THREAD

**Issue by pm-jitendra-kumavat** [golang/go#13369]
I am getting an error "use of internal package not allowed"  while building a package with go version 1.5.  
Error:
package toolsapi
	imports toolsapi/cache
	imports toolsapi/models
	imports gopkg.in/mgo.v2
	imports gopkg.in/mgo.v2-unstable/internal/scram: use of internal package not allowed

My directory structure:
toolsapi/
        cache/
        models/
        controllers/

This works perfectly fine with version go1.4.3. can anyone help to resolve the issue. I couldn't find any solution over internet.

**Comment by ianlancetaylor** [comment]
This is working as intended.  As documented in the Go 1.5 release notes, in Go 1.5 support for internal packages was applied to all repositories.  See https://golang.org/doc/go1.5 and https://golang.org/s/go14internal .

**Comment by pm-jitendra-kumavat** [comment]
How do i access the file then ? what's the way to access those files in 1.5 version.
Example: 
toolsapi/
toolsapi/models/category.go
toolsapi/controller/controller.go

I want to access a methods of category.go in controller.go. What's the way to import the category.go and other files within models package.

**Comment by davecheney** [comment]
@pm-jitendra-kumavat It's generally not useful to hold discussions on closed issues. Very few people see them. The place to discuss things like this is the golang-nuts mailing list. See https://golang.org/wiki/Questions
