### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by rif** [golang/go#13374]
I have this fata error in my project: there is a large amount of data (the process takes around 4gb in memory) cached in a map in the running process. 

The steps I reproduce the error are these:

- load the data in the map
- the memory of the whole process gets to around 6gb
- leave the process for a while and the memory drops to around 4gb
- trigger another load of the whole data

The issue appears on a Debian7 using  go version go1.5.1 linux/amd64
Linux CgrTest2 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

I got this issue both on a virtual machine and a real hardware both running Debian7 amd64.

The whole stack trace:
[issue.txt](https://github.com/golang/go/files/41975/issue.txt)

**Comment by ianlancetaylor** [comment]
Thanks.  This is a dup of #13227.
