### ISSUE TITLE
spec: docs for iota could give an example of incrementing over non-iota definitions

### ISSUE THREAD

**Issue by aidanhs** [golang/go#13371]
i.e. demonstrate the latter half of "It is reset to 0 whenever the reserved word const appears in the source and increments after each ConstSpec." with something like
```
const (
	s = "a" // increments iota
	c0 = iota // c0 == 1
	t = 5
	c1 = iota // c1 == 3
)
```
as this behaviour wasn't obvious to me (as a lazy reader who prefers looking at examples).

**Comment by ianlancetaylor** [comment]
@aidanhs Which docs in particular are you thinking of?  Thanks.

**Comment by aidanhs** [comment]
https://golang.org/ref/spec#Iota

**Comment by griesemer** [comment]
Such an example already exists in the spec in exactly the chapter to are mentioning: https://golang.org/ref/spec#Iota . See the last example:
```
const (
	bit0, mask0 = 1 &lt;&lt; iota, 1&lt;&lt;iota - 1  // bit0 == 1, mask0 == 0
	bit1, mask1                                       // bit1 == 2, mask1 == 1
	_, _                                              // skips iota == 2
	bit3, mask3                                       // bit3 == 8, mask3 == 7
)
```
which explicitly shows how an iota is skipped. The previous examples show explicitly how iota is reset. In fact, there's a lot of examples here. Closing.

(You can re-open if you had something else in mind.)

**Comment by aidanhs** [comment]
That example shows how an iota value can be skipped in a sequence of iota declarations. Given an assumption that iota remains constant over non-iota values, there's no example here to counter that.

I propose changing
```
const (  // iota is reset to 0
	c0 = iota  // c0 == 0
	c1 = iota  // c1 == 1
	c2 = iota  // c2 == 2
)
```
to
```
const (  // iota is reset to 0
	c0 = iota  // c0 == 0
	c1 = "a"   // skips iota == 1
	c2 = iota  // c2 == 2
)
```

**Comment by griesemer** [comment]
How is your proposal different from what's already there? The last example in the spec shows exactly this situation, it even uses the same comment (skips iota == 2). Please elaborate why we need another example showing the same thing.

**Comment by aidanhs** [comment]
The `_, _` line in the last example desugars to `_, _ = 1 << iota, 1 << iota - 1`.
What I'm getting at is that every line of the examples in the `iota` section has a (possibly implicit) `iota` identifier on the line. My proposal shows that `iota` increments even when it's not mentioned at all.

I'm not suggesting a new example, I'm just proposing changing a single line in the first example. If you don't think it's necessary that's fine, I just wanted to flag that (for me) it could have been clearer.

**Comment by griesemer** [comment]
@aidanhs Got it, point taken. Reopened for reconsideration. We may still decide to leave it as is. Thanks.
