### ISSUE TITLE
encoding/gob: zero value array within a struct is transmitted

### ISSUE THREAD

**Issue by robzan8** [golang/go#13378]
Documentation about struct encoding says: "If a field has the zero value for its type, it is omitted from the transmission."
It's actually not true for fields of array type:
https://play.golang.org/p/Zy8PIbmAGy

Is this working as intended?
I'm sorry to bother you here, but no one could answer me on go-nuts.

**Comment by robpike** [comment]
Yes, working as intended but not documented.

**Comment by robzan8** [comment]
May I ask what is the reason for this behavior? A consequence I found surprising is that, If struct X contains even one small array, the whole struct will never figure as zero (and omitted) when X itself is a field of another struct Y.
https://play.golang.org/p/fQ4iqTsrHx

**Comment by robzan8** [comment]
Sorry guys, I could not comment on the CL in time. I believe that the documentation added does not address the issue.
It is very clear that zero elements inside arrays are transmitted. The issue is about struct fields. The doc says that zero value fields are omitted, and this seems to imply that a zero value field of type array are omitted. In fact, a slice field with nil value is omitted. But an array field with zero value is not omitted.

**Comment by robpike** [comment]
Reopening for further investigation and renaming.

**Comment by robzan8** [comment]
I found another "exception". If the struct field is itself a struct, it is always transmitted, even if it has zero value:
https://play.golang.org/p/B4M6SuewBy
But, if the struct filed is a pointer to a struct and has nil value, it is omitted:
https://play.golang.org/p/EE3cfbDM4F
The same thing happens with arrays within structs.
When deciding what to omit from transmission, gob has its own definition of zero value (and it depends on pointer/non-pointer, even if the encoding format doesn't know about pointers).
The rule is apparently the following.

A field within a struct is omitted from transmission iff the field has zero value and kind: Bool, Int, Uint, Float, Complex, Map, Ptr, Slice, String.
So the exceptions (i.e. things that are transmitted even if zero) are kinds Array and Struct (but nil pointers to arrays and structs are omitted).

I would like to explore (as soon as I find the time) if this description exhaustively describes the situation.
