### ISSUE TITLE
cmd/doc: doesn't expose builtin functions

### ISSUE THREAD

**Issue by cespare** [golang/go#13389]
`go doc` doesn't work on the functions in the pseudo-package builtin (probably because they don't look like exported names), even though they are shown by godoc.

Compare https://golang.org/pkg/builtin/#copy with

```
$ go doc builtin.copy
doc: symbol copy not present in package builtin installed in "builtin"
```

**Comment by robpike** [comment]
This is fixed at tip. See #12541.

**Comment by cespare** [comment]
Apologies, my github-search-fu was weak.
