### ISSUE TITLE
encoding/base64: Decoder assumes padding

### ISSUE THREAD

**Issue by acasajus** [golang/go#13384]
Hello,

 I'm trying to use a bas64.NewDecoder(ba64.RawURLEncoding,in) to decode a b64 stream but I've found that it sometimes misses some bytes. If I use the DecodeString method everything is good, but if I use the reader a byte in the end is lost. If I use a base64.URLEncoding with the required padding everything seems to be working fine. 

I've added an example here:

http://play.golang.org/p/pH0Q0FVbn-

**Comment by rsc** [comment]
Shorter: http://play.golang.org/p/slir-4ZqTT
I believe the problem is the

	if d.err != nil || d.nbuf < 4 {

in base64's decoder.Read. The reader expects 4-byte chunks. When unpadded parsing was added, Read was not updated.
