### ISSUE TITLE
go get and github 2FA

### ISSUE THREAD

**Issue by gianluca311** [golang/go#13388]
go get doesn't work if repository is private and user has activated 2FA on github.
Resulting an "remote: Invalid username or password." error.

**Comment by parkr** [comment]
I have activated 2FA on GitHub and find that `go get` works just fine on my system. To solve it, fetch a [personal access token](https://github.com/settings/tokens) and use it in a `~/.netrc`:

```netrc
machine github.com
    login gianluca311
    password YOURTOKEN
```

**Comment by bradfitz** [comment]
I don't think we want to go down this road, catering to every private auth system imaginable.

"go get" is a convenience mechanism. Advanced users with private repos know how to git clone or move the repo into the correct place in the $GOPATH anyway.
