### ISSUE TITLE
http.DetectContentType should regconize `image/jxr`/`image/vnd.ms-photo`

### ISSUE THREAD

**Issue by truongsinh** [golang/go#13381]
> What version of Go are you using (go version)?
> What operating system and processor architecture are you using?

`go version go1.5.1 darwin/amd64`

> What did you do?

```golang
// b is a byte slice of `image/jxr`/`image/vnd.ms-photo` as described at https://en.wikipedia.org/wiki/JPEG_XR
// and can be obtain at 
// `https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/10/9/1444408893785/71d16ffb-de2f-4d5f-a88d-57bd939af93f-2060x1236.jpeg?w=1200&q=85&auto=format&sharp=10&s=f7ae2c7c2f6cf9b94422b873c7719d59`
// with appropriate headers, i.e. `Accept: image/jxr`
mime := http.DetectContentType(b)
```
> What did you expect to see?

```go
mime == "image/jxr"
```

> What did you see instead?

```go
mime == "application/octet-stream"
```

My suggestion: before line https://golang.org/src/net/http/sniff.go?s=2693:2759, we add
```
	&exactSig{[]byte("\x49\x49\xBC"), "image/jxr"},
```

**Comment by bradfitz** [comment]
DetectContentType is documented as being an implementation of https://mimesniff.spec.whatwg.org/

That spec doesn't mention either jxr or image/vnd.ms-photo.
