### ISSUE TITLE
path/filepath: Match incorrectly reports a pattern as malformed

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#13396]
```
$ go version
go version go1.5.1 linux/amd64
```

Match doesn't accept a hyphen inside a character class except when it is a part of a range, e.g. `[0-5]` or when it is escaped `[\-]`.  A hyphen at the beginning or the end of the character class should ideally work without escaping.

``` shell
$ cd $(mktemp -d)
$ touch foo.bar
$ touch foo-bar
$ touch foobar
$ ls -l
total 0
-rw-rw-r-- 1 mohit mohit 0 Nov 25 10:05 foobar
-rw-rw-r-- 1 mohit mohit 0 Nov 25 10:05 foo-bar
-rw-rw-r-- 1 mohit mohit 0 Nov 25 10:05 foo.bar
```

Test program:

``` go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	m, e := filepath.Glob(`foo*[.-]*`)
	if e != nil {
		panic(e)
	}
	for _, v := range m {
		fmt.Printf("%v\n", v)
	}
}
```

Executing it results in:

```
panic: syntax error in pattern

goroutine 1 [running]:
main.main()
	/tmp/tmp.ijbcwjChbR/z.go:11 +0xa1
exit status 2
```

The same `glob` pattern yields results in the shell:

``` shell
$ ls -l -- foo[.-]*
-rw-rw-r-- 1 mohit mohit 0 Nov 25 10:05 foo-bar
-rw-rw-r-- 1 mohit mohit 0 Nov 25 10:05 foo.bar
```

Similar globs appear to work in other languages too:

``` python
>>> from glob import glob
>>> glob("foo[.-]*")
['foo.bar', 'foo-bar']
>>> 
```

``` d
import std.path;

void main()
{
	assert(globMatch("foo-bar", `foo[-]*`) == true);
	assert(globMatch("foo.bar-baz", `foo[-.]*`) == true);
}
```

**Comment by ianlancetaylor** [comment]
rsc commented on the CL: "Thanks but no.  While it's true that some regexp packages do accept [-] or [x-] as equivalent to [\-] or [x\-], it's not universal. Go is not adhering to some external spec here. We defined a specific grammar (see the doc comment on filepath.Match) and that grammar does not admit [-] nor [x-]."

**Comment by mattn** [comment]
However, on windows, we can't escape `-` as `\-` because go disable escape of `[]` on windows. So we can't glob the files with this pattern.
