### ISSUE TITLE
Go shebang

### ISSUE THREAD

**Issue by kelyane** [golang/go#13394]
Hi! I don't know if it is a bug or not, but I have a curious situation:

* <b>Situation works</b>: 
I have a script in Go that exec a phantomjs, but this script is called by a php program.
my index.php there is `system("./screenshot $arg1 $arg2 $arg3 $arg4"); `, in my screenshot.go there is `cmd := exec.Command("screen.js", arg1, arg2, arg3, arg4)` and in the first line screen.js  there is `#!/usr/bin/env phantomjs` 
 
* <b>Situation doesn't work</b>: 
Now my script Go is a service using the lib "github.com/julienschmidt/httprouter". So my php just send a JSON for this service. in my script go exec the same command `cmd := exec.Command("screen.js", arg1, arg2, arg3, arg4)` and the screen.js continues the same `#!/usr/bin/env phantomjs`. However, this way doesn't work. The message error is "exit status 127". 

Then to fix it I just changed the command `cmd := exec.Command("/usr/bin/phantomjs", "screen.js", arg1, arg2, arg3, arg3)`

I don't know if it happens with other bin or if it is just in my case, or if it a bug or not in how the Go executes the process by shebang or not. I just would like to know if someone has a explanation for it.

My phantomjs bin is in /usr/bin/ version 2.0.1-development
Go version is go version go1.5.1 linux/amd64  - Kubuntu 14.04

Thanks!

**Comment by cznic** [comment]
IINM the shebang is interpreted by the shell, so I'd say this is WAI. Perhaps try something like (not tested):

`cmd := exec.Command("sh", "-c", fmt.Sprintf("screen.js %s %s %s %s", arg1, arg2, arg3, arg4))`

or

`cmd := exec.Command([]string{"sh", "-c", "screen.js", arg1, arg2, arg3, arg4}...)`

**Comment by ianlancetaylor** [comment]
Not a bug.  (In general, please ask questions not on the issue tracker but as described at https://golang.org/wiki/Questions .  Thanks.)
