### ISSUE TITLE
memory automatic growth in TCP service 

### ISSUE THREAD

**Issue by heidawei** [golang/go#13392]
a TCP services when the client at the same time to disconnect (30000 client), the memory of the first to be recovered after the slow growth, even if the service and the client without any business interaction

**Comment by bradfitz** [comment]
I'm sorry, I don't quite understand.

If you have 30,000 TCP clients, I would expect the memory to grow over time as new clients connect. Go will release memory back to the operating system slowly over time, if the memory usage has been low for some time. (for example, after the TCP clients are gone, but not immediately after)

But unless there's a bug here (and we'd need concrete details), please take general questions to a forum: https://golang.org/wiki/Questions

**Comment by heidawei** [comment]
I,m sorry ,I do not described clearly, when all clients are disconnected at the same time. the memory will back to the operating system slowly over time, after that the memory will grow to a high-level(higher memory than the client connection) a certain period of time, and hold the line, I see the memory by pprof,but find nothing for the odd memory. if the tcp server never access client, the memory will no change all time.

**Comment by davecheney** [comment]
Can you run your program with this environment variable set

GODEBUG=gctrace=1

and include the output. Please mark on the output the points where

* clients disconnect
* memory usage falls to the expected level
* memory usage grows to the higher level.

Thanks

Dave

**Comment by heidawei** [comment]
OK

**Comment by davecheney** [comment]
Thank you. We need this kind of detail to investigate any memory related
issues.

**Comment by davecheney** [comment]
Oh, also, when you get to the phase where memory usage has grown again. Can
you please send SIGQUIT to the Go process and capture the entire stack
trace. That will show if goroutines are leaking.

**Comment by heidawei** [comment]
Thank you

**Comment by heidawei** [comment]
use GODEBUG=gctrace=1, and get the process GC info:
GC forced
gc15(8): 5416+53+14938+239 us, 40 -> 42 MB, 416228 (1544624-1128396) objects, 5777 goroutines, 10790/8093/0 sweeps, 29(1497) handoff, 56(15163) steal, 264/70/222 yields
scvg1: inuse: 36, idle: 108, sys: 145, released: 0, consumed: 145 (MB)
GC forced
gc16(8): 27+72+14263+73 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/7518/0 sweeps, 25(1239) handoff, 50(12187) steal, 262/70/216 yields
scvg2: 15 MB released
scvg2: inuse: 36, idle: 108, sys: 145, released: 15, consumed: 129 (MB)

// from here the client is disconnect
GC forced
gc17(8): 108+74+17197+165 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 26(1135) handoff, 59(11013) steal, 269/71/217 yields
scvg3: 93 MB released
scvg3: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc18(8): 69+80+12678+195 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 38(1567) handoff, 56(14121) steal, 311/70/181 yields
scvg4: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc19(8): 51+53+14469+23 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 32(1398) handoff, 55(13442) steal, 287/70/207 yields
GC forced
scvg5: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
gc20(8): 63+207+13396+85 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 34(1631) handoff, 52(12838) steal, 278/71/191 yields
GC forced
scvg6: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
gc21(8): 50+212+16009+208 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 29(1475) handoff, 93(18425) steal, 268/71/235 yields
GC forced
scvg7: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
gc22(8): 5+261+14763+67 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 24(965) handoff, 70(13033) steal, 277/71/218 yields
GC forced
gc23(8): 64+78+14186+5 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 29(1070) handoff, 71(15241) steal, 293/70/214 yields
scvg8: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc24(8): 124+91+15471+24 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 29(1634) handoff, 84(14373) steal, 271/71/251 yields
scvg9: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc25(8): 152+82+17096+10 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 29(1818) handoff, 62(8124) steal, 268/70/252 yields
scvg10: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc26(8): 49+62+12848+112 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 29(1499) handoff, 53(8955) steal, 269/70/178 yields
scvg11: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc27(8): 49+111+18930+61 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 25(759) handoff, 65(13280) steal, 277/70/248 yields
scvg12: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc28(8): 61+88+19517+47 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 31(1543) handoff, 73(13360) steal, 281/71/238 yields
scvg13: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc29(8): 8+54+14672+266 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 27(1516) handoff, 49(9034) steal, 268/71/202 yields
scvg14: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc30(8): 77+79+14033+67 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 32(1361) handoff, 62(12503) steal, 268/70/207 yields
scvg15: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc31(8): 49+63+14558+191 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 22(845) handoff, 79(17077) steal, 275/82/210 yields
scvg16: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)
GC forced
gc32(8): 5+103+15603+200 us, 22 -> 22 MB, 126964 (1544624-1417660) objects, 5777 goroutines, 10790/3006/0 sweeps, 27(1172) handoff, 55(11808) steal, 280/71/266 yields
scvg17: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)

**Comment by heidawei** [comment]
and the memeory(physical memory occupancy percentage, use command top) like this:
%0.6     when the client disconnect
%0.2   
%0.6     the memory grow back
%0.2
%0.6

**Comment by davecheney** [comment]
> scvg17: inuse: 36, idle: 108, sys: 145, released: 108, consumed: 36 (MB)

The garbage collector has told the operating system that we don't need 108 mb of the 145 that has been allocated from the operating system. Some operating systems ignore this advice, especially when free memory is plentiful on the system.

Top is not a useful tool for measuring memory use on linux systems. 

I do not believe there is an issue here.

**Comment by heidawei** [comment]
send SIGQUIT to the  process, I get ：
SIGQUIT: quit
PC=0x43f571

goroutine 0 [idle]:
runtime.futex(0x8e8f18, 0x0, 0x0, 0x0, 0x0, 0x8e8380, 0x200000000, 0x40d1ff, 0x40d41e, 0x8e8f18, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:277 +0x21
runtime.futexsleep(0x8e8f18, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.c:49 +0x47
runtime.notesleep(0x8e8f18)
        /usr/local/go/src/runtime/lock_futex.go:145 +0xae
stopm()
        /usr/local/go/src/runtime/proc.c:1178 +0x119
findrunnable(0xc208014400)
        /usr/local/go/src/runtime/proc.c:1487 +0x562
schedule()
        /usr/local/go/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc208134480)
        /usr/local/go/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x435df4)
        /usr/local/go/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [IO wait, 14 minutes]:
net.(*pollDesc).Wait(0xc208010140, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010140, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080100e0, 0x0, 0x7f683e892bf0, 0xc20d99a100)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803e018, 0xc20801e440, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
main.(*Server).start(0xc20803e048, 0x7ffd815f7755, 0xd, 0x0, 0x0)
        /home/hewei/work/src/test/tcpServer/server.go:90 +0x30d
main.main()
        /home/hewei/work/src/test/tcpServer/server.go:126 +0xdf

goroutine 5 [chan receive]:
ac-common-go/glog.(*loggingT).flushDaemon(0x8e8420)
        /home/hewei/work/src/ac-common-go/glog/glog.go:901 +0x78
created by ac-common-go/glog.init·1
        /home/hewei/work/src/ac-common-go/glog/glog.go:411 +0x31d

goroutine 17 [syscall, 15 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall, 15 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35


rax     0xca
rbx     0x8e8f18
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x8e8f18
rsi     0x0
rbp     0x1
rsp     0x7ffd815f5898
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x10
r13     0x3
r14     0x0
r15     0x10
rip     0x43f571
rflags  0x286
cs      0x33
fs      0x0
gs      0x0

**Comment by davecheney** [comment]
Yup, there is no problem here, there is no leak in your application.

**Comment by heidawei** [comment]
OK，thank you，This question is troubled me for a long time.

**Comment by davecheney** [comment]
You're welcome.
