### ISSUE TITLE
Playground: Operation with short timeout does not complete

### ISSUE THREAD

**Issue by avallee** [golang/go#13399]
See http://play.golang.org/p/roUpsZmwfS

In the playground I get a result like this:

    process took too long
    Program exited.

When running on my machine:

    avallee@gust:~/go/src$ time ../bin/produce 
    received a send on a spammy channel - might be doing a costly operation if not for debounce
    *****************************
    * DOING A COSTLY OPERATION! *
    *****************************
    In case you were wondering, the value passed to this function is 95120
    We could have more args to our "compiled" debounced function too, if we wanted.
    break loop
    
    real	0m0.104s
    user	0m0.109s
    sys	0m0.016s

**Comment by ianlancetaylor** [comment]
The number of iterations on your for loop is too large, and the playground decides that your program is taking too long.  Reduce the count.

**Comment by avallee** [comment]
It is intentionally large. I want the timeout in the debounce goroutine to expire, and signal back to main that we're done.

**Comment by ianlancetaylor** [comment]
I'm not sure what to say except that the playground puts strict limits on how long a program will run.  It's not a general purpose tool.

**Comment by avallee** [comment]
Sure, no worries. I was just a bit curious as the expected run duration looks to be on the order of 100ms (on a machine at least).

Thanks.
