### ISSUE TITLE
bytes.Buffer for exec.Cmd.Stdout

### ISSUE THREAD

**Issue by ikrabbe** [golang/go#13398]
A little test shows a quite confusing error. I wrote a little test script to test interaction with lazy commands that write some data to stdout during their execution:

    #!/bin/sh
    T=${1:-60}
    for i in `seq 1 $T`
    do
	let "T--"
	printf "%02ds " $T
	sleep 1
    done
    printf "\nDone.\n"

This shell script simply counts down from $T to 0. An example output of `cmd/test_command 4` is

    03s 02s 01s 00s
    Done.

The go test program waits 3 seconds between reads of the output buffer and writes that output buffer to stdout:

	package main
	
	import (
		"bytes"
		"fmt"
		"os"
		"os/exec"
		"time"
	)
	
	func main() {
		out := bytes.Buffer{}
		cmd := exec.Command("cmd/test_command")
		cmd.Stdout = &out
		cmd.Start()
		step, _ := time.ParseDuration("3s")
		for {
			time.Sleep(step)
			os.Stderr.Write([]byte(fmt.Sprintf("Buffer Length %d\n", out.Len())))
			out.WriteTo(os.Stdout)
		}
	}

Confusingly, this program repeats parts of the buffer, instead of overwriting that with the new input:

    Buffer Length 12
    59s 58s 57s Buffer Length 12
    59s 55s 54s Buffer Length 12
    59s 52s 51s Buffer Length 12
    59s 49s 48s Buffer Length 12
    59s 46s 45s Buffer Length 12
    59s 43s 42s Buffer Length 12

... You can see here, on the second and the following lines, that the first bytes of the buffer seem to overlay the true output from the process.

Even more confusing, if you write more bytes in one step of the test command, the leading buffer offset gets longer too.

**Comment by ikrabbe** [comment]
Funny Fact: When I put the bytes.Buffer into a proxy structure

    type MyBuf {
        intbuf bytes.Buffer
    }

and implement Write, Len and WriteTo as `{ return intbuf.FUNC(ARGS) }`, everything works as expected.

**Comment by bradfitz** [comment]
This looks like it has a race. Run it with the race detector for details.

**Comment by ikrabbe** [comment]
To make the race check simple I created a repository

    go get github.com/ikrabbe/golang_issue13398
    cd $(echo $GOPATH|sed -e 's/:.*//')/src/github.com/ikrabbe/golang_issue13398
    go run -race issue13398-buffer-race.go

and got this result

	==================
	WARNING: DATA RACE
	Read by main goroutine:
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:26 +0x394
	
	Previous write by goroutine 6:
	  bytes.(*Buffer).Truncate()
	      /home/ingo/install/go/src/bytes/buffer.go:74 +0xef
	  bytes.(*Buffer).ReadFrom()
	      /home/ingo/install/go/src/bytes/buffer.go:158 +0xcd
	  io.copyBuffer()
	      /home/ingo/install/go/src/io/io.go:374 +0x1a5
	  io.Copy()
	      /home/ingo/install/go/src/io/io.go:350 +0x78
	  os/exec.(*Cmd).writerDescriptor.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:232 +0x98
	  os/exec.(*Cmd).Start.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:340 +0x2a
	
	Goroutine 6 (running) created at:
	  os/exec.(*Cmd).Start()
	      /home/ingo/install/go/src/os/exec/exec.go:341 +0xe48
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:16 +0x170
	==================
	==================
	WARNING: DATA RACE
	Read by main goroutine:
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:26 +0x3b0
	
	Previous write by goroutine 6:
	  bytes.(*Buffer).Truncate()
	      /home/ingo/install/go/src/bytes/buffer.go:72 +0xb5
	  bytes.(*Buffer).ReadFrom()
	      /home/ingo/install/go/src/bytes/buffer.go:158 +0xcd
	  io.copyBuffer()
	      /home/ingo/install/go/src/io/io.go:374 +0x1a5
	  io.Copy()
	      /home/ingo/install/go/src/io/io.go:350 +0x78
	  os/exec.(*Cmd).writerDescriptor.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:232 +0x98
	  os/exec.(*Cmd).Start.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:340 +0x2a
	
	Goroutine 6 (running) created at:
	  os/exec.(*Cmd).Start()
	      /home/ingo/install/go/src/os/exec/exec.go:341 +0xe48
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:16 +0x170
	==================
	Buffer Length 12
	==================
	WARNING: DATA RACE
	Write by main goroutine:
	  bytes.(*Buffer).WriteTo()
	      /home/ingo/install/go/src/bytes/buffer.go:203 +0x65
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:27 +0x59c
	
	Previous write by goroutine 6:
	  bytes.(*Buffer).ReadFrom()
	      /home/ingo/install/go/src/bytes/buffer.go:155 +0x65
	  io.copyBuffer()
	      /home/ingo/install/go/src/io/io.go:374 +0x1a5
	  io.Copy()
	      /home/ingo/install/go/src/io/io.go:350 +0x78
	  os/exec.(*Cmd).writerDescriptor.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:232 +0x98
	  os/exec.(*Cmd).Start.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:340 +0x2a
	
	Goroutine 6 (running) created at:
	  os/exec.(*Cmd).Start()
	      /home/ingo/install/go/src/os/exec/exec.go:341 +0xe48
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:16 +0x170
	==================
	59s 58s 57s ==================
	WARNING: DATA RACE
	Read by main goroutine:
	  syscall.raceReadRange()
	      /home/ingo/install/go/src/syscall/race.go:25 +0x38
	  syscall.Write()
	      /home/ingo/install/go/src/syscall/syscall_unix.go:178 +0xad
	  os.(*File).write()
	      /home/ingo/install/go/src/os/file_unix.go:245 +0xf4
	  os.(*File).Write()
	      /home/ingo/install/go/src/os/file.go:136 +0xbc
	  bytes.(*Buffer).WriteTo()
	      /home/ingo/install/go/src/bytes/buffer.go:206 +0x199
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:27 +0x59c
	
	Previous write by goroutine 6:
	  runtime.slicecopy()
	      /home/ingo/install/go/src/runtime/slice.go:110 +0x0
	  bytes.(*Buffer).ReadFrom()
	      /home/ingo/install/go/src/bytes/buffer.go:169 +0x27f
	  io.copyBuffer()
	      /home/ingo/install/go/src/io/io.go:374 +0x1a5
	  io.Copy()
	      /home/ingo/install/go/src/io/io.go:350 +0x78
	  os/exec.(*Cmd).writerDescriptor.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:232 +0x98
	  os/exec.(*Cmd).Start.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:340 +0x2a
	
	Goroutine 6 (running) created at:
	  os/exec.(*Cmd).Start()
	      /home/ingo/install/go/src/os/exec/exec.go:341 +0xe48
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:16 +0x170
	==================
	==================
	WARNING: DATA RACE
	Read by main goroutine:
	  syscall.raceReadRange()
	      /home/ingo/install/go/src/syscall/race.go:25 +0x38
	  syscall.Write()
	      /home/ingo/install/go/src/syscall/syscall_unix.go:178 +0xad
	  os.(*File).write()
	      /home/ingo/install/go/src/os/file_unix.go:245 +0xf4
	  os.(*File).Write()
	      /home/ingo/install/go/src/os/file.go:136 +0xbc
	  bytes.(*Buffer).WriteTo()
	      /home/ingo/install/go/src/bytes/buffer.go:206 +0x199
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:27 +0x59c
	
	Previous write by goroutine 6:
	  syscall.raceWriteRange()
	      /home/ingo/install/go/src/syscall/race.go:29 +0x38
	  syscall.Read()
	      /home/ingo/install/go/src/syscall/syscall_unix.go:163 +0x9d
	  os.(*File).read()
	      /home/ingo/install/go/src/os/file_unix.go:224 +0x89
	  os.(*File).Read()
	      /home/ingo/install/go/src/os/file.go:95 +0xbc
	  bytes.(*Buffer).ReadFrom()
	      /home/ingo/install/go/src/bytes/buffer.go:173 +0x414
	  io.copyBuffer()
	      /home/ingo/install/go/src/io/io.go:374 +0x1a5
	  io.Copy()
	      /home/ingo/install/go/src/io/io.go:350 +0x78
	  os/exec.(*Cmd).writerDescriptor.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:232 +0x98
	  os/exec.(*Cmd).Start.func1()
	      /home/ingo/install/go/src/os/exec/exec.go:340 +0x2a
	
	Goroutine 6 (running) created at:
	  os/exec.(*Cmd).Start()
	      /home/ingo/install/go/src/os/exec/exec.go:341 +0xe48
	  main.main()
	      /home/ingo/gotest/src/github.com/ikrabbe/golang_issue13398/issue13398-buffer-race.go:16 +0x170
	==================
	Buffer Length 12
	59s 55s 54s Buffer Length 12

**Comment by ikrabbe** [comment]
I understand the race condition now, but I don't understand yet, why I can work around with a proxy type.

**Comment by ikrabbe** [comment]
Maybe we should add a note to

https://golang.org/pkg/os/exec/#example_Command

**Comment by ikrabbe** [comment]
solved without a race in

https://github.com/ikrabbe/golang_issue13398/tree/norace
