### ISSUE TITLE
net/http: merge http2 Transport dials

### ISSUE THREAD

**Issue by uwillis** [golang/go#13397]
Instead of multiplexing streams, concurrent longpoll HTTP2 connections always create new connection, unless it's preceded by a complete roundtrip.

This code will reuse connection
```
getOnce()
for i:=0;i<10;i++{
        go blockingLongPoll()        
}
```
while this code doesn't (as shown by netstat)
```
for i:=0;i<10;i++{
        go blockingLongPoll()        
}
```
complete test is in [this gist](https://gist.github.com/uwillis/1890d92c16c6336aed32)

`go version devel +e5956bc linux/amd64`

**Comment by bradfitz** [comment]
This has nothing to do with long polling, and nothing to do with whether RoundTrip completes or not. This is simply the case of the Transport not merging outgoing dials when a connection doesn't exist. There was even a TODO in the code for this already. Fix coming.
