### ISSUE TITLE
gccgo: erroneously accepts multi-valued g() in f(g()...)

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13404]
As far as I can tell, this is not valid according to the Go spec:

    package x

    func f(x, y int, z ...int)   {}
    func g() (x, y int, z []int) { return 0, 0, nil }
    func h() {
    	f(g()...)
    }

It's rejected by cmd/compile and golang.org/x/tools/cmd/gotype:

    $ go tool compile x.go
    x.go:6: multiple-value g() in single-value context
    x.go:6: not enough arguments in call to f

    $ gotype x.go
    x.go:6:7: cannot use ... with 3-valued g()

But accepted by gccgo (at least as of 4.8):

    $ gccgo-4.8 -c x.go
    $ echo $?
    0

CC @ianlancetaylor @griesemer

**Comment by ianlancetaylor** [comment]
Dup of #9525.
