### ISSUE TITLE
func need return error. In codes there's nothing returned but can be build successfully.

### ISSUE THREAD

**Issue by AnotherGoogleFans** [golang/go#13408]
The code is very simple:

func test() error {
    for{}
}

and this can be build successfully.

Shouldn't this throw an error like "missing return at end of function" or something like this?

Go1.5.1 mac

**Comment by cespare** [comment]
No. `for {}` is a terminating statement.

https://golang.org/ref/spec#Terminating_statements

**Comment by AnotherGoogleFans** [comment]
Thank U. I see now.
