### ISSUE TITLE
encoding/xml: implement dual of 'omitempty' for unmarshalling «optional» fields

### ISSUE THREAD

**Issue by flyingmutant** [golang/go#13417]
XML is often used in legacy APIs, which are often not very consistent in the data format they output. One of such inconsistencies is emitting of nodes with empty data in case it is missing, so `<tag>123</tag>` becomes `<tag></tag>`, instead of being omitted entirely.

If node data type is non-string, the only way to handle this in Go currently is to mark node data type as `string`, and handle the parsing by hand. This is verbose, error-prone and in contrast with the rest of parsing, which is quite declarative.

Go 1.5.1 // #8333, #8334

**Comment by flyingmutant** [comment]
To be precise, what I'd like to have is

```go
type Foo struct {
        Bar *int `xml:"BAR,allowempty"`
}
```

which will parse `<BAR></BAR>` into `Foo{nil}`.

**Comment by athap** [comment]
:+1:

**Comment by adams-sarah** [comment]
I am happy to take this if nobody is working on it already.

I would think that the unmarshaling behavior for `<Foo><BAR></BAR></Foo>` should be similar to that of encoding/json’s for `{"BAR": null}`. Both should be unmarshaled to `Foo{Bar: (*int)(nil)}`. No need to add a new struct field tag option.

Is there a use case that I’m missing for the error that unmarshaling `<BAR></BAR>` causes when dst is non-string?

Please correct me if I misunderstand the issue.

**Comment by adams-sarah** [comment]
Nvm. ^ goes against xml spec.
