### ISSUE TITLE
tour: reference to wrong conversion type

### ISSUE THREAD

**Issue by kirugan** [golang/go#13412]
Context: https://tour.golang.org/basics/13

Last paragraph is inconsisten with code example on the doc page:

Unlike in C, in Go assignment between items of different type requires an explicit conversion. Try removing the float64 or int conversions in the example and see what happens.

Must be:

Unlike in C, in Go assignment between items of different type requires an explicit conversion. Try removing the float64 or **uint** conversions in the example and see what happens.

**Comment by dominikh** [comment]
It is refering to the editable example on the right side, which uses `int`, not `uint`. 

Maybe the two examples should be in sync, though.

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by kytrinyx** [comment]
I believe this has been fixed.

**Comment by minux** [comment]
Already fixed.
