### ISSUE TITLE
spec: links to charts/lists of supported unicode character categories

### ISSUE THREAD

**Issue by benjamin-rood** [golang/go#13414]
It would help (or at least add value) to add some links to the character types as mentioned in https://golang.org/ref/spec#unicode_letter

To change from line 108 in the source code to:

    In <a href="http://www.unicode.org/versions/Unicode6.3.0/">The Unicode Standard 6.3</a>,
    Section 4.5 "General Category"
    defines a set of character categories.  Go treats those characters in category 
    <a href="http://www.fileformat.info/info/unicode/category/Lu/list.htm">Lu</a>, 
    <a href="http://www.fileformat.info/info/unicode/category/Ll/list.htm">Ll</a>, 
    <a href="http://www.fileformat.info/info/unicode/category/Lt/list.htm">Lt</a>, 
    <a href="http://www.fileformat.info/info/unicode/category/Lm/list.htm">Lm</a>, 
    or <a href="http://www.fileformat.info/info/unicode/category/Lo/list.htm">Lo</a> 
    as Unicode letters, and those in category 
    <a href="http://www.fileformat.info/info/unicode/category/Nd/list.htm">Nd</a> 
    as Unicode digits.
    </p>`

Because the link provided to 6.3 of the standard doesn't have any way to display a chart by categories as is referred to in the documentation, and it took me a while to actually find those links which would show me the specific character sets. If there is a more 'official' set of links than the ones I have suggested, then of course those would be better!

**Comment by griesemer** [comment]
I would prefer linking only to the official Unicode webpages at www.unicode.org. @mpvl , @robpike do you have any input on this?

**Comment by robpike** [comment]
A link needs maintaining, while a prose description is easy to find using a web search and stays current. I  would prefer prose, because Unicode is constant flux.

**Comment by benjamin-rood** [comment]
That's entirely reasonable, but surely the same applies to the link which is provided to the Unicode Standard 6.3.0 when in actual fact the current version of Go is compliant with v. 8.x, right?

Is there a prose solution which adds anything to what is currently there do you think, or, as I am guessing, not?

**Comment by griesemer** [comment]
@benjamin-rood I will update the spec to refer to refer to the current Unicode version.

**Comment by benjamin-rood** [comment]
Instead of providing the links to the charts/list of the sets of characters for each category, what if one appends the full name of the category after the code in brackets, such that the relevant section of text becomes:

> Go treats those characters in category Lu _(Letter, Uppercase)_, Ll _(Letter, Lowercase)_, Lt _(Letter, Titlecase)_, Lm _(Letter, Modifier)_, or Lo _(Letter, Other)_ as Unicode letters, and those in category Nd _(Number, Decimal Digit)_ as Unicode digits. 

At least that would make searching for current charts/lists easier for those not so familiar with Unicode categories.
