### ISSUE TITLE
cmd/pprof: -weblist and -output don't play well together

### ISSUE THREAD

**Issue by lorenzb** [golang/go#13413]
This issue isn't very serious but can be annoying nevertheless.
#### What version of Go are you using (go version)?

go 1.5.1 (the issue also exists in tip)
#### What operating system and processor architecture are you using?

not applicable
#### What did you do?

I was working on a headless system.
I wanted to analyse profiling output by running `go tool pprof -weblist=. -output=listing.html myprogram myprogram.pprof` and copying the resulting listing.html file to my workstation for viewing.
#### What did you expect to see?

I expected that there would be a file named listing.html containing the profiling report.
#### What did you see instead?

```
$ go tool pprof -weblist=. -output=listing.html myprogram myprogram.pprof
Generating report in listing.html
exec: "firefox": executable file not found in $PATH
```

The file listing.html was created, but remained empty.

Note that the same command works if I use `-list` instead of `-weblist`.

I think that the default behaviour of opening a browser to display the report is very convenient. But if the user specifies `-output`, that choice should either be respected or a warning (e.g. "warning : flag -output ignored for -weblist output format") should be printed. In no case an empty listing.html file should be generated.

As a workaround, I placed a small script named `firefox` in my $PATH; the script copies the report to a directory of my choice.

**Comment by lorenzb** [comment]
I'd be happy to contribute a patch if the Go maintainers are interested.

**Comment by ianlancetaylor** [comment]
Sure, send a patch. At this point it would be for the 1.7 release.

**Comment by agnivade** [comment]
This works now for 1.11. 

```
18:56:57-agniva-~/play/go/src/github.com/agnivade/levenshtein$go tool pprof -weblist=. -output=list.html levenshtein.test cpu.prof
Generating report in list.html
18:57:14-agniva-~/play/go/src/github.com/agnivade/levenshtein$ls -l list.html 
-rw-rw-r-- 1 agniva agniva 4026138 Sep 30 18:57 list.html
```

Closing.
