### ISSUE TITLE
stringer does not implement GO15EXPERIMENT=1

### ISSUE THREAD

**Issue by monotrememan42** [golang/go#13411]
we have a project set up using the new vendoring stuff.
we have a source file that imports (say) "github.com/Sirupsen/logrus"
which has been put at the relevent spot. running
go build
works successfully. however running
stringer -type ProcesStatus .
fails complaining it can't find that package:
stringer: checking package: horde.go:6:2: could not import github.com/Sirupsen/logrus (can't find import: github.com/Sirupsen/logrus)

**Comment by bradfitz** [comment]
Dup of #12278 I'm pretty sure.
