### ISSUE TITLE
cmd/dist: The OSX build breaks if  /usr/sbin is not in the path

### ISSUE THREAD

**Issue by williamh** [golang/go#13425]
On Darwin, it appears that the method of determining whether default GOHOSTARCH setting should be amd64 relies on sysctl. There are use cases where sysctl is not in the users' path. In situations like this, the OSx build of go will break.

For an example, see https://bugs.gentoo.org/show_bug.cgi?id=558368.

The suggested patch for that bug is to hard code the path to /usr/sbin/sysctl in the command.

Before I do that, I'm wondering if you are interested in doing so upstream, or if there is a better way to do this autodetection on OSx?

Thanks much,

William

**Comment by davecheney** [comment]
Is it common to not have /usr/sbin in the path ? Can you give some more background on how your discovered this issue.

**Comment by minux** [comment]
It might be fine for Gentoo/Alt to carry that patch,
I don't think we should handcode the path to sysctl
in cmd/dist. For one, there is no guarantee that
future OS X won't move sysctl to /sbin or even
/usr/bin.

Actually, I think a better solution for Gentoo/Alt
is to just define GOHOSTARCH before running
make.bash. Portage knows very well what arch
the host is on, so auto-detection in cmd/dist is
unnecessary.

**Comment by grobian** [comment]
That would be awesome, that we we could also build a different arch than sysctl would report.

**Comment by williamh** [comment]
@minux:
I agree with this suggestion; it would be good to skip the autodetection completely if $GOHOSTARCH is defined, and this would be a very simple fix to the ebuilds on Gentoo as well.
Does anyone have any updates on when this can be done?

Thanks much for your time. :-)

**Comment by rsc** [comment]
Why are we talking about Gentoo? I thought that was Linux. The only mention of sysctl in cmd/dist is when running on OS X.

At this point I think it would be fine to just stop calling sysctl and assume default GOHOSTARCH=amd64 on OS X.

**Comment by grobian** [comment]
This is Gentoo Prefix, where we run a Gentoo Portage (the package manager of Gentoo) on OSX, Solaris, AIX and more to provide tools in some place like $HOME/gentoo (not to mess with the OS in /usr/bin or something).
