### ISSUE TITLE
time: no default RFC 3339 format with millisecond precision

### ISSUE THREAD

**Issue by theckman** [golang/go#13424]
Within the `time` package, there are quite a few default time formats provided as constants. This includes an [RFC 3339](https://tools.ietf.org/html/rfc3339) format string with and without nanosecond precision. There is also a "handy" timestamp format, which has a constant that includes millisecond precision.

I can see there being value in the `RFC 3339` formatters also including one with millisecond precision. I personally have this format string copied amongst a few projects and would love to see it introduced in to the standard library.

**Comment by cespare** [comment]
See #13291.

**Comment by theckman** [comment]
@cespare cheers! I didn't find it when searching.
