### ISSUE TITLE
race between File.Sync() and RWMutex.RLock()

### ISSUE THREAD

**Issue by powerman** [golang/go#13422]
This issue was tested on two servers with go1.4.2 linux/amd64 and one with go1.5.1 linux/amd64, all running up-to-date Hardened Gentoo Linux. Playground doesn't have this issue.

This code hangs after printing "3" in 99% cases:
```go
package main

import (
	"fmt"
	"log"
	"os"
	"sync"
	"time"
)

func main() {
	m := &sync.RWMutex{}
	m.Lock()
	go locker(m)

	f, err := os.Create("/tmp/bug-fsync-mutex")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("1")
	m.RLock()
	fmt.Println("2")
	f.Sync()
	fmt.Println("3")
	m.RLock()
	fmt.Println("4")
}

func locker(m *sync.RWMutex) {
	c := time.Tick(10 * time.Millisecond)
	for {
		m.Unlock()
		<-c
		m.Lock()
	}
}
```
```sh
$ go run main.go
1
2
3

```
Nearly any change will "fix" this issue:
- removing f.Sync()
- using /dev/null instead of real file
- using os.Open() instead of os.Create()
- increasing Tick() delay to 100 milliseconds (actually in real project which have this issue I use 100 milliseconds, but after removing all unrelated code I had to decrease this delay to reliably have this issue)
- removing locker() and initial m.Lock()

strace (without -ff) output is:
```
futex(0x59af10, FUTEX_WAIT, 0, NULL)    = 0
openat(AT_FDCWD, "/tmp/bug-fsync-mutex", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
write(1, "1\n", 21
)                      = 2
write(1, "2\n", 22
)                      = 2
fsync(3)                                = 0
futex(0x59a980, FUTEX_WAKE, 1)          = 1
futex(0x59a8c0, FUTEX_WAKE, 1)          = 1
write(1, "3\n", 23
)                      = 2
futex(0x59af10, FUTEX_WAIT, 0, NULL)    = 0
futex(0x59af10, FUTEX_WAIT, 0, NULL)    = 0
...
```
and with os.Open() instead of os.Create():
```
futex(0xc82000ce90, FUTEX_WAKE, 1)      = 1
futex(0xc82000ce90, FUTEX_WAKE, 1)      = 1
openat(AT_FDCWD, "/tmp/bug-fsync-mutex", O_RDONLY|O_CLOEXEC) = 3
sched_yield()                           = 0
futex(0x5a18a0, FUTEX_WAKE, 1)          = 0
write(1, "1\n", 21
)                      = 2
write(1, "2\n", 22
)                      = 2
fsync(3)                                = 0
write(1, "3\n", 23
)                      = 2
write(1, "4\n", 24
)                      = 2
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by cznic** [comment]
`Lock` after `Rlock` must block and wait for `Runlock`, but there's no `Runlock` in the program. The program can hang randomly, no race is involved AFAICS.

**Comment by powerman** [comment]
@cznic Thanks, I think you right, sorry for invalid report.
