### ISSUE TITLE
net/http: remove "Seek" from File interface, replace with "io.Seeker"

### ISSUE THREAD

**Issue by xoba** [golang/go#13421]
this merely simplifies the interface a bit (no change in functionality) and makes further connection to the io package, which seems appropriate:

    type File interface {
            io.Closer
            io.Reader
            io.Seeker // ADD THIS
            Readdir(count int) ([]os.FileInfo, error)
            // Seek(offset int64, whence int) (int64, error) // REMOVE THIS
            Stat() (os.FileInfo, error)
    }

not sure if there are any policy reasons why this change couldn't be made, like strict api compatibility, etc.

**Comment by rakyll** [comment]
Why not grouping io.Reader and Seek into io.ReadSeeker?

**Comment by xoba** [comment]
sounds good to me, i guess either `io.ReadSeeker`+`io.Closer` (your CL), or `io.ReadCloser`+`io.Seeker` could work? only reason i didn't suggest it at first, is for some reason `io.Closer` and `io.Reader` weren't already combined into `io.ReadCloser`. anyone out there know the reasoning, if any, around that?
