### ISSUE TITLE
x/mobile/app: panic with palm touch on iOS app

### ISSUE THREAD

**Issue by nobonobo** [golang/go#13435]
golang 1.5.1

https://github.com/golang/mobile/blob/master/app/darwin_armx.go#L151
```
panic: out of touchIDs
```

**Comment by hyangah** [comment]
/cc @crawshaw Is the following comment no longer true?

// It is widely reported that the iPhone can handle up to 5 simultaneous
// touch events, while the iPad can handle 11.

**Comment by nobonobo** [comment]
patch & log

```diff
diff --git a/app/darwin_armx.go b/app/darwin_armx.go
index 5344e27..f6fa027 100644
--- a/app/darwin_armx.go
+++ b/app/darwin_armx.go
@@ -132,6 +132,7 @@ var touchEvents struct {
 
 //export sendTouch
 func sendTouch(cTouch, cTouchType uintptr, x, y float32) {
+       log.Println(cTouch, cTouchType, x, y)
        id := -1
        for i, val := range touchIDs {
                if val == cTouch {
```

```
2015/12/05 22:25:26 5601104144 0 149 62
2015/12/05 22:25:26 5602228320 0 832 231
2015/12/05 22:25:26 5601879616 0 1090 337
2015/12/05 22:25:26 5601973040 0 428 117
2015/12/05 22:25:35 5601128704 0 239 91
2015/12/05 22:25:35 5601104144 0 299 612
2015/12/05 22:25:35 5601118880 0 990 122
2015/12/05 22:25:35 5601111664 0 619 133
2015/12/05 22:25:35 5601092240 0 603 327
2015/12/05 22:25:35 5601077024 0 817 107
2015/12/05 22:25:35 5601860816 0 560 597
2015/12/05 22:25:37 5602222480 0 656 160
2015/12/05 22:25:37 5602223728 0 583 597
panic: out of touchIDs
```

**Comment by nobonobo** [comment]
6 fingers touch and release on iPhone5S.

expect:
  6 `touch.TypeEnd` events receive.

instead:
  These `touch.TypeEnd` events disappeared.

**Comment by nobonobo** [comment]
need handle touchesCancelled ?

**Comment by nobonobo** [comment]
No occur panic in Android, but there was a problem of lost touch sequence (similar IOS).
cancel-events must handle for real-device.

- AMOTION_EVENT_ACTION_CANCEL for android
- touchesCancelled for iOS

Proposal:
- Add const value "TypeCancel" to "event/touch/touch.go".
- cancel-event send to app.
- touchIDs delete cancelled ID for iOS

**Comment by crawshaw** [comment]
@nobonobo I missed your comment before submitting your CL. Want to move this to #13859?
