### ISSUE TITLE
path.Dir and filepath.Dir don't seem to work with Windows paths

### ISSUE THREAD

**Issue by mattetti** [golang/go#13437]
Bug reproduction examples:
http://play.golang.org/p/2vJu8wTbr3

```
fmt.Println(path.Dir(`D:\MyDocuments\3799\Defected House - 8.1.3+.zip`))
fmt.Println(filepath.Dir(`D:\MyDocuments\3799\Defected House.zip`))
```

Both return `.` as the directory.  Can it be because I cross compiled my binary?

**Comment by mattn** [comment]
path package is not for the physical paths. please use path/filepath instead of path.
And you seems to not use UNC path in the comment. AFAIK, UNC path is like `\\server\sharefolder\path\to\file.txt`. On my environment, filepath seems to work fine with UNC path on my windows.

```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Dir(`\\server\sharefolder\path\to\file.txt`))
	// \\server\sharefolder\path\to

	fmt.Println(filepath.Dir(`//server/sharefolder/path/to/file.txt`))
	// //server/sharefolder/path/to
}
```

**Comment by mattetti** [comment]
Apologies, I fixed the bug title. I'm using Windows paths, not UNC paths. It would seem that the test cases that are Windows specific would fail on other OS: https://golang.org/src/path/filepath/path_test.go#L98

In case someone runs into the same issue, I fixed the problem locally by not using `filepath.Join` and using `strings.Join(pathItems, "/")` since the version of Windows I'm targeting properly handles these paths.

**Comment by mattn** [comment]
If you want slashed-paths, you can use `filepath.ToSlash(filepath.Join(dir, file))`.

**Comment by ianlancetaylor** [comment]
Closing because there doesn't seem to be a bug here.

The path/filepath package does the right thing for the GOOS value.

**Comment by mattetti** [comment]
@ianlancetaylor with GOOS=windows, `filepath.Dir(`D:\MyDocuments\3799\Defected House.zip`)` still doesn't work. I'm not sure how that's not a bug. I would even say that even on Linux, if I parse files containing Windows path, the behavior should work (might be a stretch tho).

**Comment by alexbrainman** [comment]
Your program works just fine on windows:

```

C:\dev\src\a>type foo.go
package main

import (
        "fmt"
        "path/filepath"
)

func main() {
        fmt.Println(filepath.Dir(`D:\MyDocuments\3799\Defected House.zip`))
}

C:\dev\src\a>go run foo.go
D:\MyDocuments\3799

C:\dev\src\a>
```

path/filepath works differently on different OS, just like it says in the documentation:

```
Package filepath implements utility routines for manipulating filename paths in a way compatible with the target operating system-defined file paths.
```

Alex

**Comment by mattetti** [comment]
Fair enough, so it looks like the issue is that I cross compiled my program from a Mac and executed it on Windows. I guess this might be a bit problematic, I was under the impression that cross compiling would build an binary with identical behaviors as if it was build on the target platform. I guess I misunderstood, thanks

**Comment by davecheney** [comment]
This should absolutely work. Can you please post your cross compilation
setup, flag, and everything else, plus the final binary you got.

**Comment by mattetti** [comment]
Absolutely, let me create a small reduction example

**Comment by alexbrainman** [comment]
Just like @davecheney said. It should not matter where you build your program. What matter is where your program runs. You can build the program above on Mac or Linux or Plan9, but if you run it on Windows, it will display same output.

Alex

**Comment by davecheney** [comment]
The crucial parts of this bug report are

* which version of go
* where did you get it from
* which flags did you you use to cross compile

Thanks

Dave

**Comment by davecheney** [comment]
Oh, and can you please make the test binary print the following

fmt.Println(runtime.GOOS, runtime.GOARCH, runtime.GOROOT())

**Comment by mattetti** [comment]
I feel very embarrassed, @mattn was totally right in his first comment, the issue was that in my own code, I was using `path.Dir` instead of `filepath.Dir` which didn't behave as expected. I was then testing on linux and OS X and didn't re-crosscompile to test until right now. 

I'm extremely sorry to have wasted everybody's time but I'll take this opportunity to mention that I'm very thankful to all of you for being so kind and helpful.

**Comment by davecheney** [comment]
Not a problem. If there was a bug introduced in cross compilation then we'd
want to know about it, this is never a waste of time.
