### ISSUE TITLE
x/review/git-codereview: breaks git rebase -i's "reword" option

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13439]
During "git rebase -i" if you choose "reword" and try to then run "git commit --amend" to edit the commit message, you get:

```
$ git commit -a --amend
git rev-parse --abbrev-ref HEAD@{u}
fatal: HEAD does not point to a branch

git-codereview: exit status 128
```

**Comment by cmarcelo** [comment]
When "reword" is chosen during interactive rebase, git should automatically spawn the editor for amending the commit message. Did you meant "edit"?

I've tried a bit using "edit" and things work correctly. Do you have more details on how to reproduce the issue?

**Comment by ysmolsky** [comment]
I cannot reproduce this no more. I suppose it was fixed since that time...
