### ISSUE TITLE
mime: Loosen the ParseMediaType error checking

### ISSUE THREAD

**Issue by cention-sany** [golang/go#13448]
What version of Go are you using (go version)? *1.5.1*
What operating system and processor architecture are you using? *Ubuntu Intel 64 bits*
What did you do? *use mime.ParseMediaType*
What did you expect to see? *error mime: invalid media parameter*
What did you see instead? *no error or different type of error*

The following is actually output from bad email client for an attachment mime header:
> Content-Type: application/octet-stream; name=Viktoria C
> Content-Disposition: attachment; filename=Viktoria C

This type of header email will output "mime: invalid media parameter" error under golang. But the same email when open/parse by Thunderbird and other C email library will give the attachment with file name *Viktoria* instead of *Viktoria C*.

I understand the main problem is the bad email client and not golang library but the same mail can be opened with other application which is not using Golang library may give the wrong perspective that Golang library capability - the fact is Golang error handling too good that expose those scapegoat buggy software problem. But just because of this tiny error the whole email can not be parsed.

May be Golang library can have something as [this](https://github.com/cention-sany/mime/blob/master/mediatype.go#L139) to discriminate certain error that can be recovered.

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand this bug report.  Can you be more precise about what you want changed?  Can you show a demonstration program?

**Comment by cention-sany** [comment]
using mime.ParseMediaType to parse the line *Content-Type: application/octet-stream; name=Viktoria C* or *Content-Disposition: attachment; filename=Viktoria C* will give *error mime: invalid media parameter*. I hope Golang library can parse these successfully such as other application which output the file name *Viktoria*.

**Comment by ianlancetaylor** [comment]
For this kind of thing it really helps to show a code example.  Does this show the problem you are reporting?  http://play.golang.org/p/uZH0-U2Qgh .

**Comment by ianlancetaylor** [comment]
If that is the problem, I think RFC 2045 is pretty clear: the value must be a token or a quoted string.  A token may not contain a space.  This works: http://play.golang.org/p/fb0OkjnU2L .

**Comment by cention-sany** [comment]
Ya. I understood the problem lie on the *Content-Type: application/octet-stream; name=Viktoria C*. Probably Golang library can treat the line as *Content-Type: application/octet-stream; name=Viktoria* with error instead of return empty and error.

**Comment by bradfitz** [comment]
Is this a bad email client that matters?

Which one?

Where is the bug report for their side?

I'd rather not violate RFCs unless there's a very good reason.

**Comment by cention-sany** [comment]
The bad email client that I mentioned most probably is using different non-Golang library for composing the email. I don't have any knowledge on the mail client but just our application received a raw email with this type of bad formatted Content-Type.

Ya, before I posted I did doubt about whether Golang team will even consider this. I just try it. You may not violent the RFC by still returning the error, just different type of error. But currently mime library *return "", nil, error* [check this](https://github.com/golang/go/blob/master/src/mime/mediatype.go#L137) which wipe out any of the previously successfully parsed mediatype and params.

It would be easier if other email client give error for the same type of email but Thunderbird and some other mail client can read the email. But our email client application can not because we use Golang library to parse the email.

Anyway feel free to close it. There is always others workaround. Thank for the time.

**Comment by ianlancetaylor** [comment]
I am closing because I don't see what we can usefully do.  Trying to sort out the meaning of a value that does not follow the RFC is not a job for the standard package.  That has to be done using some sort of application logic.
