### ISSUE TITLE
TLS support in syslog package

### ISSUE THREAD

**Issue by cancan101** [golang/go#13449]
Currently the syslog packages does not work with a [syslog log destination with TLS support](http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/).

See: https://github.com/docker/docker/issues/18358

**Comment by bradfitz** [comment]
We have no plans to further develop the log/syslog package in the standard library.

We welcome the community to fork it and give it features elsewhere. It was probably a mistake putting it in the standard library to begin with.

**Comment by sirsean** [comment]
If anyone is looking for syslog with TLS, we've forked the original library and added TLS support here:

https://github.com/RackSec/srslog
