### ISSUE TITLE
x/mobile: building bind/hello example meets with an error: "hello/Hello.h  file not found"

### ISSUE THREAD

**Issue by liudanking** [golang/go#13441]
I am building the [gomobile Hello][1] example app, but am running into the following problem: When trying to build and run the app after opening it in Xcode (7.1), I get the error 'hello/Hello.h' file not found'
From what I can tell, Hello.h is in fact in the hello folder of the native directory.

[error in Xcode and the file it's in][2]

  [1]: https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios
  [2]: http://i.stack.imgur.com/CPhQX.png

**Comment by falafelizer** [comment]
I'm also getting this error. [Posted it to SE](http://stackoverflow.com/questions/33746069/hello-hello-h-file-not-found-trying-to-build-run-ios-gomobile-hello-app) a couple weeks ago with no luck.

**Comment by rakyll** [comment]
Xcode 7 doesn't seem to be updating paths to search for the headers automatically the way previous Xcode versions did. If you choose "Copy items if needed" when you are dragging the bundle in the project,

```
#import  <Hello/Hello.h>
# or
#import "Hello/Hello.h"
```
works.

I think there is nothing we can do other than updating the wiki with additional pointers.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/go/wiki/Mobile/63235d5699149fb9701fe6d62e24c086d4d4d752.
