### ISSUE TITLE
website: invalid SSL certificate at golang.org

### ISSUE THREAD

**Issue by nodakai** [golang/go#13452]
Where should I report the invalid SSL of https://golang.org/ ?

![image](https://cloud.githubusercontent.com/assets/90726/11530127/f52502c2-992c-11e5-9244-ae9ec87d7aff.png)

**Comment by bradfitz** [comment]
You should be getting the "misc-sni.google.com" cert served to you, not the "*.appspot.com" one.

@agl, thoughts?

**Comment by nodakai** [comment]
OK, the problem must be specific to my proxy environment, as I do receive a cert by misc-sni.google.com at home now without warnings.  Closing...
