### ISSUE TITLE
cmd/go: TestNoteReading fails on Windows when CGO_ENABLED=0

### ISSUE THREAD

**Issue by jayschwa** [golang/go#13450]
I encountered a test failure while running `all.bat` on my Windows 10 machine. Working copy is 0ea1c1f6715c6fe33c38b6292ce2bdccaa86f0e2. `GOROOT_BOOTSTRAP` points to an installation of Go 1.5.1. `CGO_ENABLED=0` because I don't have a C toolchain installed. The failure seems cgo-related though:
```
--- FAIL: TestNoteReading (0.39s)
        go_test.go:257: running testgo [build -ldflags -buildid=TestNoteReading-Build-ID -o C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.exe C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.go]
        go_test.go:257: running testgo [build -ldflags -buildid=TestNoteReading-Build-ID -linkmode=external -o C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.exe C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.go]
        go_test.go:276: standard error:
        go_test.go:277: # command-line-arguments
                warning: unable to find runtime/cgo.a
                C:\Users\jaysc\Documents\GitHub\golang\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exec: "gcc": executable file not found in %PATH%


        go_test.go:286: go [build -ldflags -buildid=TestNoteReading-Build-ID -linkmode=external -o C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.exe C:\Users\jaysc\AppData\Local\Temp\gotest202420732\hello.go] failed unexpectedly: exit status 2
FAIL
FAIL    cmd/go  26.458s
```
I temporarily modified my working copy to skip [the part that builds with `-linkmode=external`](https://github.com/golang/go/blob/master/src/cmd/go/note_test.go#L58). All tests pass otherwise.

**Comment by alexbrainman** [comment]
I can reproduce this, if I remove gcc from my PATH, and set CGO_ENABLED=0 and run all.bat. But is that expected to work? If yes, should we have builder for that combination? Is that important? Remember that Go on windows does not use cgo anywhere in standard library.

Alex
