### ISSUE TITLE
x/net/proxy: doesn't support uppercase and lowercase all_proxy / no_proxy

### ISSUE THREAD

**Issue by nathanleclaire** [golang/go#13456]
AFAIK, `ALL_PROXY` and `all_proxy` are both valid, but only `all_proxy` is supported.

**Comment by nathanleclaire** [comment]
e.g.: https://github.com/golang/net/blob/master/proxy/proxy.go#L30

**Comment by ReSearchITEng** [comment]
will this be solved in upcoming versions?

**Comment by bradfitz** [comment]
Nobody is working on this. Feel free.

That package isn't released as part of Go, so it can be fixed at any time, regardless of Go's release cycle.
