### ISSUE TITLE
panic on mapassign: overflow is not nil

### ISSUE THREAD

**Issue by msackman** [golang/go#13462]
fatal error: overflow is not nil
    
    goroutine 18 [running]:
    runtime.throw(0x88c070, 0x13)
        /home/matthew/src/golang/go1.5.1/src/runtime/panic.go:527 +0x90 fp=0xc8209d7558 sp=0xc8209d7540
    runtime.hashGrow(0x6fd760, 0xc82137fe90)
        /home/matthew/src/golang/go1.5.1/src/runtime/hashmap.go:776 +0x132 fp=0xc8209d7588 sp=0xc8209d7558
    runtime.mapassign1(0x6fd760, 0xc82137fe90, 0xc8209d7684, 0xc8209d7668)
        /home/matthew/src/golang/go1.5.1/src/runtime/hashmap.go:481 +0x55b fp=0xc8209d7630 sp=0xc8209d7588

Server was busy, but I've run this test before many times and this is the first time I've seen this. Please let me know if there's anything in particular you'd like me to investigate.

**Comment by davecheney** [comment]
This kind of panic is very common if you have a data race in your program. Have you run the tests with -race, or built a racer enabled version of your program?

**Comment by msackman** [comment]
I have compiled and run using -race (I write everything as actors so I use this quite a lot), but there's always a chance I've missed something. I've also re-read https://golang.org/ref/mem but nothing jumps out at me as something I'm doing wrong. However, I wouldn't object if you want to close this unless I can reproduce it with -race and no race reported.

**Comment by davecheney** [comment]
Is the source of your program available ?

Can you post the entire panic message please.

**Comment by msackman** [comment]
Nope, ignore me, some careful reasoning, and I can see exactly how I could have multiple go-routines writing to that same map. Hasn't shown up in testing with -race yet, but that's the joy of these concurrency bugs!

(Source isn't available, at least not for a few more weeks, and everything beneath what I posted is into my code. Anyway, closing this now as I've no doubt it's my own fault. Sorry for the noise and thanks for the help.)
