### ISSUE TITLE
runtime: _ExternalCode when profiling cgo 

### ISSUE THREAD

**Issue by petermattis** [golang/go#13466]
[I'm using go-1.5.1 on Mac OS X]

In profiling an app which uses cgo I see a lot of time locked up in the stack trace `_ExternalCode -> _System`. And stack traces which I expect to see leading up to the cgo calls are not present. Looking at the code in `runtime.sigprof` I can see that the `_ExternalCode` marker is used when the profiling signal handler cannot safely call `gentraceback` (i.e. `setsSP(pc)` returns true). But it looks like this code path is overaggressively applied when we're in a cgo call as it should be safe to call `gentraceback(mp.curg.syscallpc, mp.curg.syscallsp, ...)`. In fact, the current code is executing `gentraceback` for cgo calls, but if `traceback` has been set to false the generated trace is tossed out and replaced with `_ExternalCode`.

To make this more concrete, this diff seems to fix the issue I'm seeing:

```
diff --git a/src/runtime/proc1.go b/src/runtime/proc1.go
index 09cb775..3dbda19 100644
--- a/src/runtime/proc1.go
+++ b/src/runtime/proc1.go
@@ -2581,6 +2581,7 @@ func sigprof(pc, sp, lr uintptr, gp *g, mp *m) {
                // so instead collect Go stack that leads to the cgo call.
                // This is especially important on windows, since all syscalls are cgo calls.
                n = gentraceback(mp.curg.syscallpc, mp.curg.syscallsp, 0, mp.curg, 0, &stk[0], len(stk), nil, nil, 0)
+               traceback = true
        } else if traceback {
                n = gentraceback(pc, sp, lr, gp, 0, &stk[0], len(stk), nil, nil, _TraceTrap|_TraceJumpStack)
        }
```

**Comment by rsc** [comment]
@aclements just rediscovered this in a different context and has applied an equivalent fix, I believe.

**Comment by aclements** [comment]
Yes. Since the fix for this is trivial (and only tangentially related to the rest of the CL it's currently in), I'll pull it out into a CL of its own and mark it against this issue.

**Comment by aclements** [comment]
@petermattis, is it possible for you to double check that https://go-review.googlesource.com/18327 fixes the issue you're seeing?

**Comment by petermattis** [comment]
@aclements: Yes, though I might not get to it until tomorrow.

**Comment by petermattis** [comment]
@aclements: Found time to test today. That patch fixes the issue for me as well.

**Comment by aclements** [comment]
Thanks!
