### ISSUE TITLE
website: Golang.org blocks 178.18.20.0/22

### ISSUE THREAD

**Issue by cynix** [golang/go#13464]
1) What version of Go are you using (go version)?
1.5

2) What operating system and processor architecture are you using?
FreeBSD 10.1 x86_64

3) What did you do?
Tried to install Go packages with `go get`

4) What did you expect to see?
Packages installed

5) What did you see instead?
403 Forbidden

```
> curl https://golang.org/x/net/websocket?go-get=1
<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Forbidden)!!1</title><style>*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>Your client does not have permission to get URL <code>/x/net/websocket?go-get=1</code> from this server.  (Client IP address: 178.18.20.x)<br><br>
We're sorry, but this service is not available in your country.

  <ins>That’s all we know.</ins>
```

**Comment by bradfitz** [comment]
Where is LeaseWeb?
What is its IP range?
What IP do you see at https://ip.appspot.com/ ?

**Comment by cynix** [comment]
LeaseWeb is a large network provider in the Netherlands. This particular server I'm using is in the IP range 178.18.20.0/22.

**Comment by bradfitz** [comment]
I've reported this internally. (Bug number 26003031)

**Comment by bastiaanspw** [comment]
I've tried from many IP addresses in leaseweb NL, DE and US, and do not see isssues.
If you still see problems they would probably be only related to 178.18.20.0/22. 

That range is not a leaseweb IP range.
It is a leaseweb customer IPv4 range.

**Comment by bradfitz** [comment]
I'm removing the Go1.6 tag from this. This wouldn't block the release. Yes, it should happen soon, but it's a different team that does this involving nobody on the Go team, and it's underway.

**Comment by cynix** [comment]
@bastiaanspw: sorry for the confusion. I've removed the reference to LeaseWeb from the issue title.

**Comment by cynix** [comment]
It seems the same IP range is also blocked by go.googlesource.com.

**Comment by bradfitz** [comment]
Same system.

According to the internal bug, this has been fixed, but not yet pushed to production. It's possible it won't be pushed until after the holidays.

I'm going to close this bug, though. Feel free to comment if it's not live after Jan 4th or so.
