### ISSUE TITLE
cmd/compile: endless compile for invalid declaration

### ISSUE THREAD

**Issue by griesemer** [golang/go#13471]
```
package p
const c = 1e646456992
```
works (now), but:
```
package p
const c int = 1e646456992
```
ends up taking forever.

The time is spent trying to convert the large constant into an integer for the error message (constant ... overflows int).

As an aside, we should also make sure that (internally) the constant is not converted into an integer in the first place.

**Comment by mdempsky** [comment]
(Your two code snippets look identical?)

**Comment by griesemer** [comment]
@mdempsky fixed - thanks for pointing it out.
