### ISSUE TITLE
"Go run" doesn't play nice with windows firewall

### ISSUE THREAD

**Issue by Mikarnage** [golang/go#13479]
When using **go run** oh a go program listening to a port, windows firewall triggers a confirmation dialog each time.
It seems like **go run** builds an executable with a new name each time, so windows' firewall can't know it has already been authorized, and thus asks for white-listing.

**Comment by alexbrainman** [comment]
Don't use "go run", if it bothers your firewall. Use "go build -o a.exe && a.exe" or something similar instead. Would that work for you?

Alex

**Comment by Mikarnage** [comment]
Good advice, thanks!
And thanks for quick reply :+1:

**Comment by dominikh** [comment]
(Though one would hope that a decent software firewall doesn't just trust the file name, but also looks at a checksum of the file.)
