### ISSUE TITLE
cmd/compile: accepts invalid comparisons against converted nil

### ISSUE THREAD

**Issue by mdempsky** [golang/go#13480]
cmd/compile accepts this source:

    package zero

    func isZeroSlice(s []byte) bool    { return s == []byte(nil) }
    func isZeroMap(m map[int]int) bool { return m == map[int]int(nil) }
    func isZeroFunc(f func()) bool     { return f == (func())(nil) }

but gotype rejects it with:

    zero.go:3:45: cannot compare s == []byte(nil) (operator == not defined for []byte)
    zero.go:4:45: cannot compare m == map[int]int(nil) (operator == not defined for map[int]int)
    zero.go:5:45: cannot compare f == (func())(nil) (operator == not defined for func())

The Go spec says "However, as a special case, a slice, map, or function value may be compared to the predeclared identifier `nil`." which seems to support gotype's behavior.

**Comment by alandonovan** [comment]
I'm not certain this is a bug.  Constants have basic types (string, number, or boolean), so `nil` is not a constant.  Thus the compiler is not required to know the value of an expression such as `[]byte(nil)` at compile time.

**Comment by mdempsky** [comment]
@alandonovan Sorry, I'm not sure I follow your response.  To clarify, the issue I'm trying to point out is that cmd/compile *does* compile the snippet of source I pasted without errors, whereas my understanding of the Go spec (and supported by gotype's behavior) says it should *not*.

**Comment by bradfitz** [comment]
Also, surely it's a bug that cmd/compile and gotype differ in their opinion. What does gccgo say?
/cc @ianlancetaylor

**Comment by alandonovan** [comment]
Hi Matthew, sorry for the confusion.  I clarified my response but of course that didn't send mail.  I agree with you that `go/types` is correct and `cmd/compile` has a bug.

**Comment by mdempsky** [comment]
Ah, okay. :)

**Comment by ianlancetaylor** [comment]
gccgo says:

    foo.go:3:47: error: slice can only be compared to nil
     func isZeroSlice(s []byte) bool    { return s == []byte(nil) }
                                                   ^
    foo.go:4:47: error: map can only be compared to nil
     func isZeroMap(m map[int]int) bool { return m == map[int]int(nil) }
                                                   ^
    foo.go:5:47: error: func can only be compared to nil
     func isZeroFunc(f func()) bool     { return f == (func())(nil) }
                                                   ^
