### ISSUE TITLE
RFE: stream-oriented versions of strings.Unquote, strconv.ParseInt, etc

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13482]
I often find myself needing variants of the basic parsing functions (strconv.ParseInt, strings.Unquote, and so on) that consume a prefix of an input string and return the unconsumed part.  I realize you can accomplish this using text/scanner, but it is complex and heavyweight.

Could we add these to the standard library?

**Comment by bradfitz** [comment]
Dup of #2632?

Returning the unconsumed part is new. fmt.Scan* exists but probably slower than you want.

FWIW, there's a fork of strconv.ParseUint that works on `[]byte` at https://godoc.org/go4.org/strutil#ParseUintBytes that I find myself using enough to warrant existing.

**Comment by alandonovan** [comment]
Although `fmt.Sscanf(_, "%q%s", _, _)` can be used to scan a double-quoted or raw string literal, it doesn't work for single-quoted rune literals (whereas `strconv.Unquote` does).

The `[]byte` vs `string` issue is orthogonal to the issue of parsing a prefix versus the entire string.

**Comment by rsc** [comment]
I don't believe strconv should be in the business of telling you where the data ends. If you know where it ends, break it before handing it to strconv. If you don't know where the data ends, I think you have a bad data format.
