### ISSUE TITLE
crypto/x509: add support for marshalling PKCS#8 private keys

### ISSUE THREAD

**Issue by AGWA** [golang/go#13487]
crypto/x509 currently supports parsing PKCS#8 private keys with `ParsePKCS8PrivateKey` but doesn't provide a way to marshal them.  A corresponding `MarshalPKCS8PrivateKey` function would be handy.

**Comment by typeless** [comment]
Duplicate of #19972?

**Comment by FiloSottile** [comment]
Yep, duplicate of #19972 and fixed by 0a1a65c.
