### ISSUE TITLE
cmd/link: remove old -X format

### ISSUE THREAD

**Issue by rsc** [golang/go#13498]
In Go 1.7, remove the -X option's old two-argument format from the linker.

Would fix #12338. :-)

Edit: This is about removing `-X name value`, which is deprecated. The more conventional form `-X name=value`, first introduced in Go 1.5, would stay.

**Comment by ae6rt** [comment]
Will there still be a way to bake in compile time information into the resulting application binary?

**Comment by cespare** [comment]
@ae6rt IIUC this is only about the old -X syntax with two arguments; the current syntax has the form `-X importpath.name=value` and will continue to work.

**Comment by rsc** [comment]
@ae6rt, @cespare, yes, that's right. I added a note to the report.

**Comment by rsc** [comment]
Done in 51b624e.
