### ISSUE TITLE
cmd/link: put toolchain version in binary

### ISSUE THREAD

**Issue by randall77** [golang/go#13507]
It would be nice to have a robust mechanism to tell what version of Go built a particular binary.

See go-nuts thread: https://groups.google.com/forum/#!topic/golang-nuts/XIDDj75ngMc

If the binary happens to call runtime.Version, then the version of Go is stored in runtime.buildVersion.  If it doesn't call runtime.Version, runtime.buildVersion is dead-symbol eliminated.

We could teach cmd/link not to remove this symbol even if it is dead.  Probably better is to just reference runtime.buildVersion from some always-used code (schedinit?).  That way it will always be available in the binary, easily extracted with gdb.

**Comment by davecheney** [comment]
@randall77 i'd like to see this as well. A few years ago I suggested (cannot find the issue # anymore) that runtime.Version be printed in panic output. Doing this would solve the problem of keeping runtime.buildVersion alive, and also avoid having to much about with gdb to find the version string.

**Comment by davecheney** [comment]
Nice trick Keith. How quickly I have forgotten that gdb exists.

**Comment by minux** [comment]
we already have https://golang.org/cl/117040043

It's now called runtime/internal/sys.BuildVersion
and it's accessible to gdb.

(gdb) p 'runtime/internal/sys.BuildVersion'
$1 = 0x482ea0 "devel +cd29463 Fri Dec 4 01:47:18 2015 +0000"

**Comment by randall77** [comment]
Ok, excellent, didn't know about that one.

I'm not sure moving back to runtime.buildVersion would help.  runtime.buildVersion isn't reliable in 1.4 because it can be eliminated at link time.

**Comment by minux** [comment]
The change first appeared in Go 1.4, so starting from Go 1.4,
runtime.buildVersion is always available, until Go 1.6.

**Comment by laboger** [comment]
What about programs built with gccgo?

**Comment by ianlancetaylor** [comment]
@laboger For gccgo `strings PROG | grep "gccgo "` is reliable in that it will print the version, although of course other strings might match too.
