### ISSUE TITLE
x/crypto/ocsp: OCSP Extension support

### ISSUE THREAD

**Issue by jsha** [golang/go#13505]
In https://github.com/letsencrypt/boulder/issues/592, we'd like to be able to include [SCTs](https://www.certificate-transparency.org/) in OCSP responses. To do this requires OCSP extension support in golang.org/x/crypto/ocsp.

**Comment by bradfitz** [comment]
Pending review: https://go-review.googlesource.com/#/c/16946/

**Comment by bifurcation** [comment]
This was resolved by https://go-review.googlesource.com/#/c/18202/

**Comment by WinPack** [comment]
@jsha Since it is now implemented in Go, maybe implement it also in Let's Encrypt?
