### ISSUE TITLE
compile: is it a implicit cast?

### ISSUE THREAD

**Issue by chanxuehong** [golang/go#13508]
```
C:\Users\chan>go version
go version go1.5.2 windows/amd64
```

```go
package main

import (
	"fmt"
)

var root int64 = 0xfffff

func main() {
	// section 1
	x := string(root)
	fmt.Println(len(x))

	// section 2
	y := string(rune(root))
	fmt.Println(len(y))
}
```
see section 1, is it a implicit cast?
I think section 2 is better.

**Comment by davecheney** [comment]
@chanxuehong the issue tracker is only used for tracking bugs, please don't ask questions here.

Please ask questions on the mailing list or the go forum, see https://golang.org/wiki/Questions.

Thanks

Dave

**Comment by chanxuehong** [comment]
@davecheney it think it is a bug, but I am not ensure.

**Comment by davecheney** [comment]
It's not a bug

https://golang.org/ref/spec#Conversions
"""
Conversions to and from a string type

Converting a signed or unsigned integer value to a string type yields a string containing the UTF-8 representation of the integer.
"""

**Comment by chanxuehong** [comment]
ok , thanks
