### ISSUE TITLE
x/tools/cmd/godoc: show Go version that types/funcs/etc were introduced in

### ISSUE THREAD

**Issue by jinguoli** [golang/go#13518]
example php:
>gzencode
>
>(PHP 4 >= 4.0.4, PHP 5)
>gzencode — Create a gzip compressed string

example python:
>Compress.copy()
>Returns a copy of the compression object. This can be used to efficiently compress a set of data that >share a common initial prefix.

>New in version 2.5.

**Comment by davecheney** [comment]
For questions about the language, see one of the forums: https://golang.org/wiki/Questions

We only use the Github issue tracker for tracking bugs.

**Comment by Thomasdezeeuw** [comment]
I think is more a proposal rather then a question. @jinguoli maybe you should take a look at https://github.com/golang/proposal, on how to create a proposal.

**Comment by davecheney** [comment]
Thanks for correcting me Thomas, I had misunderstood the OPs original post.

Thanks

Dave

**Comment by mdempsky** [comment]
@jinguoli FYI, you might be interested in the http://tip.golang.org/api/ directory, which contains information about which types/functions/etc were added in each Go release.

**Comment by jinguoli** [comment]
@mdempsky the api txt not easy-to-use, like PHP or Python manual is very intuitive.

@all
sorry, my english is very bad, can not talk more detail. sorry.

**Comment by bradfitz** [comment]
I've re-titled this bug. godoc could do this in HTML mode. It has the information.

**Comment by minux** [comment]
Merged into #5778.
