### ISSUE TITLE
there always need to create a object to tell or compare other object is blank!!!

### ISSUE THREAD

**Issue by hzmnet** [golang/go#13512]
there always need to create a object to tell or compare other object is blank!!!
are there all blank object could equal to Null or nil?
_____________________________________
1# cannot use nil as type reflect.Value in return argument
2# when struct is not pointer
if struct==struct{}{
}

**Comment by bradfitz** [comment]
For questions about the language, see one of the forums: https://golang.org/wiki/Questions

We only use the Github issue tracker for tracking bugs.
