### ISSUE TITLE
website: code of conduct headings aren't linkable

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13514]
The code of conduct headings aren't nicely linkable:

e.g. https://golang.org/conduct#tmp_6

That should be https://golang.org/conduct#reporting (and others)

Would be nice to cherry-pick this back to the 1.5 branch too and push it live even before 1.6.

/cc @campoy @broady (not sure who owns this with adg out)

**Comment by broady** [comment]
cherry-picked to 1.5 and deployed to golang.org

**Comment by bradfitz** [comment]
Thanks!
