### ISSUE TITLE
Master branch?

### ISSUE THREAD

**Issue by nigleb** [golang/go#13510]
The branch called `master` should be called something else (i propose `trunk` or `dev`) as the word `master` is male-centric and insensitive to people of color, therefore it goes against the code of conduct which is promoting diversity.

**Comment by brownl** [comment]
This is ridiculous. 

The word master has multiple definitions, one of which is this:

An original, such as an original document or audio recording, from which copies can be made.

It is completely acceptable for the word 'master' to be used in this context. 

https://www.wordnik.com/words/master

**Comment by quiznilo1** [comment]
Are you going to live by your Code of Conduct or what?  Diminishing that user's concerns as trivial is a microaggression.

**Comment by dominikh** [comment]
Considering that the user is pushing to branches called "master" in his own projects, this issue can hardly be taken seriously.

**Comment by brownl** [comment]
The projects you are talking about do not have any kind of code of conduct in place. Go has created a code of conduct, now they must stick to it. 

I have my mind, this suggestion seems reasonable to me.

**Comment by ALTree** [comment]
I like how the Rust Community handled this issue https://github.com/rust-lang/rust/issues/27504

Don't feed the trolls.

**Comment by bradfitz** [comment]
Per the Code of Conduct "Reporting Issues" section (https://golang.org/conduct#tmp_6 for now, even though I filed #13514 to fix that link), all conduct violations should be reported privately. I'm closing this public issue. If you wish to pursue this further you can follow the reporting instructions at https://golang.org/conduct.
