### ISSUE TITLE
cmd/compile: spurious error for goto jumping over non-var declarations

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#13521]
The compiler issues an error message for a goto jumping over type or const declaration, like

``` go
package main

func main() {
    goto L1
    type A int
L1:
}
```

The specification forbids only jumping over variable declarations.

**Comment by ianlancetaylor** [comment]
Fails on gccgo as well:

/home/iant/foo.go:4:5: error: goto jumps over declaration of ‘A’
     goto L1
     ^
/home/iant/foo.go:5:10: note: ‘A’ defined here
     type A int
          ^

**Comment by bradfitz** [comment]
Passes with `gotypes`.

**Comment by ALTree** [comment]
Exact dup of #8042. 

Also see the old thread for a tentative fix (it was reverted but maybe it's salvageable).

**Comment by mdempsky** [comment]
Closing as duplicate of #8042.
