### ISSUE TITLE
Basic type can not be assigned to its alias type

### ISSUE THREAD

**Issue by justintan** [golang/go#13529]
Id is an alias of int. But it cannot be assigned with int value. 

    type Id int

    func main() {
	    var i Id
	    var k int = 10
	    iv := reflect.ValueOf(&i).Elem()
	    kv := reflect.ValueOf(k)
	    if kv.Type().AssignableTo(iv.Type()) {  // condition is false
		    iv.Set(kv)     
	    }
	    fmt.Print(i)  // output 0
    }

**Comment by mdempsky** [comment]
Right.  `int` is not assignable to `Id`.

**Comment by justintan** [comment]
@mdempsky Thanks for your reply. So how to assign int value to Id variable with reflect?

**Comment by mdempsky** [comment]
You'll need to convert the `int` value to an `Id` value (e.g., using `reflect.Value`'s `Convert` method).  However, if you have further questions, the best place to ask them is golang-nuts, not the issue tracker.  Thanks!
