### ISSUE TITLE
mime/multipart: Doesn't sort headers before writing.

### ISSUE THREAD

**Issue by sthulb** [golang/go#13522]
Problem: The `Writer.CreatePart` func in `mime/multipart` doesn't sort before writing headers.

Proposed solution is to obviously sort them and write them in the sorted order, allowing things like unit tests to accurately check if the resulting document is valid.

This is clearly a known issue as the source code has a comment stating this (https://golang.org/src/mime/multipart/writer.go#L97) 

```go
    97		// TODO(bradfitz): move this to textproto.MimeHeader.Write(w), have it sort
    98		// and clean, like http.Header.Write(w) does.
    99		for k, vv := range header {
   100			for _, v := range vv {
   101				fmt.Fprintf(&b, "%s: %s\r\n", k, v)
   102			}
   103		}
```

cc: @bradfitz

**Comment by sthulb** [comment]
I'm happy to create the patch to fix this, but I understand the stdlib is not accepting changes, I could implement the sort in mime/multipart if required.

**Comment by bradfitz** [comment]
Feel free to fix this. It can't be submitted until early February, though, so no rush.

**Comment by sthulb** [comment]
@bradfitz With the new public `Write` fund?

**Comment by bradfitz** [comment]
No new API surface.

**Comment by sthulb** [comment]
Submitted to Gerrit as: https://go-review.googlesource.com/#/c/17497/
