### ISSUE TITLE
internal/syscall/unix: panic on internal/syscall/unix.init()

### ISSUE THREAD

**Issue by last-g** [golang/go#13537]
Hi

I've used https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip  and it worked fine. But today I suddenly got this error:
```
last-g@yalastdell:~/opt/packer$ ./packer
panic: runtime: allocation size out of range

goroutine 1 [running]:
internal/syscall/unix.init()
        /usr/local/go/src/internal/syscall/unix/getrandom_linux.go:19 +0xef
crypto/rand.init()
        /usr/local/go/src/crypto/rand/util.go:136 +0x56
github.com/hashicorp/go-checkpoint.init()
        /Users/cbednarski/code/golang/src/github.com/hashicorp/go-checkpoint/checkpoint.go:343 +0x3b
main.init()
        /Users/cbednarski/code/golang/src/github.com/mitchellh/packer/version.go:12 +0x4e
```
In 20 minutes this error dissapeared and I can't reproduce it now. 

I've checked source code of packer and it seems to be something very strange with Go runtime.

My system
```
$ uname -a
Linux yalastdell 4.2.0-21-generic #25-Ubuntu SMP Wed Dec 2 18:42:25 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by minux** [comment]
This is interesting. It definitely shouldn't happen.

Have you tested the system (physical) memory
on the system? e.g. with memtest86+.

**Comment by ianlancetaylor** [comment]
Which version of Go?

How repeatable is this?

**Comment by last-g** [comment]
@minux 
I'll test system today. But whole system just works fine

@ianlancetaylor 
Binary is compiled statically with go1.5.
I can't repeat this error now. I've got it for every run of this binary for about 20 minutes and then it just disappeared.

Now i'm getting another error, it be related with original error:
https://gist.github.com/last-g/4c1c5ca4f4e0629a8065

**Comment by ianlancetaylor** [comment]
How large is your program.  What does `size packer` print?

**Comment by last-g** [comment]
``
last-g@yalastdell:~/opt/packer$ size packer
   text    data     bss     dec     hex filename
8072436  131416  181624 8385476  7ff3c4 packer
``

**Comment by ianlancetaylor** [comment]
Thanks for the info.  I'm going to close this as unreproducible.  If you can get this to happen consistently, or on a different machine, please reopen.
