### ISSUE TITLE
Returning pointer to struct allows returns for structs that don't implement the required interface type in method signature

### ISSUE THREAD

**Issue by stuarthicks** [golang/go#13534]
I've believe I've uncovered what is, at best, confusing behaviour in the way structs are associated with interfaces, and at worst, a bug that can hide other issues.

Take the following example go program:

```go
package main

import "github.com/davecgh/go-spew/spew"

type BarInterface interface {
	Bar() string
}

type Foo struct{}

// Incorrect pointer receiver, doesn't actually implement BarInterface correctly.
func (f *Foo) Bar() string {
	return "bar"
}

func foo() BarInterface {
	f := &Foo{}
	// I'm returning a *Foo instead of Foo, and method signature says return is BarInterface (and Foo doesn't implement BarInterface)
	return f
}

func main() {
	f := foo() // Returns BarInterface
	spew.Dump(f) // (*main.Foo)
}
```

I don't expect this to compile because I'm returning a pointer to a struct, instead of a value in the return of `foo()`. In any case, this works and spew prints out correctly that `f` is `*main.Foo`.

However if I were to try do a type assertion (such as `t, ok := f.(BarInterface)` I get a compile error because of the pointer receiver on the implementation of `Bar()`. From this it seems that there's actually two issues with the return call in `Foo()`:

- It's returning a pointer instead of a value, which doesn't match the method signature.
- The struct doesn't actually correctly implement the interface and should error on that return line (and in-fact does error if I dereference `f` in the return).

Would appreciate an explanation if this is intended behaviour (even better if it's documented somewhere I haven't found yet). Otherwise I believe this to be a bug.

> What version of Go are you using (go version)?

I've tried this on 1.5.1 and 1.5.2 (same result).

> What operating system and processor architecture are you using?

OSX El Capitan. x86_64.

> What did you do?

Returned a pointer to a struct instead of the value. Struct doesn't correctly implement the interface that's declared as the return type for that method.

What did you expect to see?

Compile errors.

What did you see instead?

No compile errors, and a return value that doesn't match the method signature.

**Comment by ianlancetaylor** [comment]
You haven't shown any bug here.  We use the issue tracker only for bugs; we prefer that people ask questions as described at https://golang.org/wiki/Questions .  Thanks.

You have some misunderstanding about types, methods, and interfaces, but I'm not sure precisely what it is.  `BarInterface` is satisfied by any type that implements the method `Bar() string`.  The type `*Foo` implements that interface.  The function `foo` in your example returns a value of type `*Foo`.  That type implements the interface, so all is well.  I'm not sure why you think it wouldn't be.

**Comment by stuarthicks** [comment]
I disagree. I've stated that I expected to see a compile error and didn't (and that it allowed me to return a struct that didn't implement the interface correctly because of the pointer receiver).

**Comment by stuarthicks** [comment]
>  The function foo in your example returns a value of type *Foo. That type implements the interface, so all is well. I'm not sure why you think it wouldn't be.

As I said in my description of the bug, if I take that returned struct and try to `t, ok := f.(BarInterface)` the compiler errors because it doesn't actually implement that interface because the method has a pointer receiver. The bug is that I shouldn't have been able to return it from that method at all. I should have gotten the compiler error on the return call.

**Comment by ianlancetaylor** [comment]
I really strongly recommend that you ask questions as described on that wiki page.

Your code doesn't return a struct.  It returns a pointer to a struct.  The method takes a pointer receiver.  You have a pointer.  All is well.

I don't understand where you are adding the line `t, ok := f.(BarInterface)`.  Please show the complete failing code.

**Comment by stuarthicks** [comment]
This code is failing because it compiles. Is this example clearer:

```go
package main

import "fmt"

type CustomErrorType struct{}

// Incorrect method signature, Error() shouldn't have a pointer receiver
func (c *CustomErrorType) Error() string {
	return "basic error message"
}

func doThing() error {
	err := &CustomErrorType{}
	return err // This line should be a compile error, but isn't.
}

func doSomethingElse() error {
	err := &CustomErrorType{}
	return *err // This line correctly doesn't compile because the struct doesn't implement error correctly
}

func main() {
	err := doThing()
	err2 := doSomethingElse()
	fmt.Printf("%v\n%v", err, err2)

	// Impossible type assertion:CustomErrorType does not implement error (Error method has pointer receiver)
	t, ok := err.(CustomErrorType)
}
```

If I save that as "foo.go" and run it:

```
$ go run foo.go
./error_interface.go:19: cannot use *err (type CustomErrorType) as type error in return argument:
        CustomErrorType does not implement error (Error method has pointer receiver)
./error_interface.go:28: impossible type assertion:
        CustomErrorType does not implement error (Error method has pointer receiver)
[1]    86380 exit 2     go run error_interface.go
```

Lines 19 and 28 are correctly showing as incorrect. Line 14, however, shows no errors despite also being an incorrect return.

That is what I'm trying to explain as the bug. Does that make more sense now?

**Comment by ianlancetaylor** [comment]
In line 19 you return a value of type `CustomErrorType`.  That type does not implement `error`, so you a compilation error.  The type `error` requires an `Error` method.  The type `CustomErrorType` has no methods.  The pointer type `*CustomErrorType` does have a method, but the type `CustomErrorType` does not.  So the compilation error is correct.

In line 28 you take a value of type `error` and try to convert it to type `CustomErrorType`.  That conversion can not possibly succeed, because `CustomErrorType` does not implement `error`.  Any value of type `error` must have an `Error` method, and `CustomErrorType` does not.

In line 14 you are returning a value of type `*CustomErrorType`.  That is, you are returning a pointer type, not a struct type.  The pointer type `*CustomErrorType` does have an `Error` method; you defined it on line 8.  So the pointer type `*CustomErrorType` does implement `error`, so the code compiles.

You seem to be suggesting that because `CustomErrorType` does not have an `Error` method, that `*CustomErrorType` also does not have an `Error` method.  But that's not how Go works.  Perhaps it would help to read https://golang.org/doc/faq#different_method_sets .

**Comment by stuarthicks** [comment]
Ok, it seems then that I have misunderstood the exact meaning of pointer receivers. Thanks for explaining it to me. Not a bug then :stuck_out_tongue:
