### ISSUE TITLE
Want to translate the Go Code of Conduct into Brazilian Portuguese

### ISSUE THREAD

**Issue by carlisia** [golang/go#13549]
I'd like to work on this translation. Is this something desirable?

**Comment by campoy** [comment]
I think we should have translated version of the code of conduct outside of this repo, the same way translations of the tour are somewhere else.

I'm wondering if this should be part of one of the resources already linked [here](https://github.com/golang/go/wiki/NonEnglish#brazilian-portuguese---portugu%C3%AAs-brasileiro).

Do you have any contacts with the owners of golangbr.org?

**Comment by carlisia** [comment]
@campoy I do have contact with them. Should I go this route then?

**Comment by campoy** [comment]
Yeah, I think it should be somewhere in [http://www.golangbr.org/projeto/](this page)

**Comment by carlisia** [comment]
Ok, will do. Thanks!

**Comment by guilhermebr** [comment]
:+1:

**Comment by carlisia** [comment]
Ok, I've got that under way and am closing this issue.

As a way of suggestion, people should see a Portuguese speaker on the list of people representing the community for the purpose of CoC issues. c/c @adg

**Comment by carlisia** [comment]
And FYI re: the translation to pt-br: https://github.com/golangbr/golangbr.org/issues/14
