### ISSUE TITLE
Intermittent git SSL failures against go.googlesource.com

### ISSUE THREAD

**Issue by joeshaw** [golang/go#13553]
This may be the same as #9976, but rather than being a problem in `go get` I think it might be a problem with go.googlesource.com.

On an AWS box running Ubuntu 14.04 I get intermittent failures running `go get` against various repos hosted on go.googlesource.com.  Git is version 1.9.1 and I've tried git compiled against both an OpenSSL-linked and GnuTLS-linked libcurl.  My estimation is that it happens about 5% of the time.

It never seems to happen against other servers (such as github.com) and I've never seen the error on my OS X box where I do the majority of my development.  It only seems to happen on our CI and deployment systems.

When git is compiled against OpenSSL, the error is:

    fatal: unable to access 'https://go.googlesource.com/oauth2/': Unknown SSL protocol error in connection to go.googlesource.com:443 

Against GnuTLS, the error is:

    fatal: unable to access 'https://go.googlesource.com/text/': gnutls_handshake() failed: A TLS packet with unexpected length was received.

Problems with git and gnutls are [well documented](https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1111882) and I got fed up enough with the failures that I recompiled git to link against libcurl-openssl rather than libcurl-gnutls expecting that to fix the problem, but we see errors just as often as before, leading me to think it might be somehow server related.

**Comment by bradfitz** [comment]
Paging Mr. @spearce who owns go.googlesource.com etc

**Comment by joeshaw** [comment]
I just learned about `GIT_CURL_VERBOSE=1`, but it doesn't seem to be picked up and passed through by `go get`.

**Comment by spearce** [comment]
This is an SSL glitch between the client library and the Google SSL server. Nothing to do with Git itself, just SSL being a very "interesting" protocol to implement. I'll reach out to the SSL experts I know and see if they can help.

**Comment by agl** [comment]
Can you reproduce? I'd really need to see a tcpdump of the issue happening because the error message is insufficient. I.e.

> sudo tcpdump -i $IFACE -s 9999 -w /tmp/dump

And then run git in a loop until it reproduces.

Also note that these things are often caused by middleware (either on the network or the local machine) doing silly things so it's a good idea to see whether there's a likely candidate around.

**Comment by joeshaw** [comment]
I will give it a shot.  These are running inside Docker containers, so that seems a likely culprit, although the OS inside the container is the same one outside.  I will try to reproduce it on both sides.

**Comment by joeshaw** [comment]
I haven't been able to reproduce this, so I'm closing it.  I'll reopen if I see it again and can track things down.
