### ISSUE TITLE
sys: plan9/mksysnum_plan9.sh has a duplicated, mangled copyright header

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#13569]
The plan9/mksysnum_plan9.sh script has a duplicated, mangled copyright header:

```
# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
```

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/17684

**Comment by binarycrusader** [comment]
Note that while this was fixed for syscall in the 'go' repository (src/syscall/mksysnum_plan9.sh), I was actually filing this bug against the sys repository:

https://github.com/golang/sys/blob/master/plan9/mksysnum_plan9.sh

Apologies for any confusion I might have caused, although it appears the same change should apply to both.
