### ISSUE TITLE
encoding/asn1: roll back CL 16517?

### ISSUE THREAD

**Issue by rsc** [golang/go#13563]
This CL broke a test at Google in the Go port of keyczar. The test vectors check that signatures with non-minimal integer encodings are still accepted, and after CL 16517 they are not. We need to decide whether to roll back the CL or declare that that usage is not important.

**Comment by bradfitz** [comment]
keyczar wants to accept bogus encodings?

**Comment by rsc** [comment]
It's not bogus, it's just non-minimal. I have an email thread going with the author.

**Comment by bradfitz** [comment]
Okay, please summarize what you find out.

Because I thought ASN.1 was DER and DER was the minimal-form-required version of BER, which I guess isn't the full story.

**Comment by danmux** [comment]
Could this be related to a bug we have after upgrading from 1.4 to 1.5:

    pk error x509: trailing data after ASN.1 of public-key

this ...

http://play.golang.org/p/U6pTR1oC1m

works in 1.4

**Comment by danmux** [comment]
FYI. Whilst this is changed behaviour from 1.4 - 1.5 it has shown up the fact that one of our systems is generating 'bad' PK's. We can condition the []byte, and fix the culprit, so can move forward. In our case there would be no compelling argument to revert the stricter 1.5

If this is not the same issue then apologies.

**Comment by rsc** [comment]
@danmux, this issue is about something that changed since 1.5. You may be seeing something in 1.5 different from 1.4 but it's not this. I'd still be interested to hear more about your problem if you'd like to file a new issue. If you can describe the condition you use to detect the issue that might be enough, but of course code is nicer. :-) Thanks.

**Comment by danmux** [comment]
ok thanks, ftr.. https://github.com/golang/go/issues/13580 and happy for you to delete my polluting comments in here.

**Comment by rsc** [comment]
After discussion, the plan is to eliminate that keyczar test. The test cared more that the code didn't crash than that it accepted the signature in question. So we do not need to roll back CL 16517.
