### ISSUE TITLE
Interface type variables cannot be compared with nil while holding nil pointer of interface implementation

### ISSUE THREAD

**Issue by baliame** [golang/go#13562]
This issue had caused days of inconvenience until we could pinpoint what exactly was happening, but I can now reproduce it.

Given a function that returns a specific implementation of an interface - this specific implementation is also a pointer. This value is then assigned to a variable of the interface's type. If the value returned was nil (a null pointer), comparing the variable to nil (determined by the compiler to be a null interface nil, rather than a null pointer nil) will always yield false.

A simple change in a library, going from returning the interface type from returning the specific implementation type broke our code in a completely puzzling way, as we got a null pointer dereference panic from a branch which specifically checks if the variable is indeed nil.

A simple example:
http://play.golang.org/p/wF6w53fz_7

Tested using both go playground and `go version go1.5.1 darwin/amd64`

**Comment by eastany** [comment]
```
if f == (*FooImplementation)(nil) {
      fmt.Println("xxxx")
}
```

**Comment by shurcooL** [comment]
`nil` value always has a type. If you visualize that, it makes the behavior much more clear.

Your if statement, originally written as:

```Go
if f == nil {
	fmt.Println("This code will never run.")
}
```

Is basically doing this:

```Go
if (*FooImplementation)(nil) == (FooInterface)(nil) {
	fmt.Println("This code will never run.")
}
```

Which makes a lot of sense, those two variables are not equal.

A common way to resolve this issue is to change signature of `NewFoo` to return `FooInterface` instead of `*FooImplementation`:

```Go
func NewFoo() FooInterface {
	if ("error" == "error") {
		return nil // Now the type is FooInterface rather than *FooImplementation.
	}
	return &FooImplementation{}
}
```

**Comment by bradfitz** [comment]
This is a common learning mistake. See https://golang.org/doc/faq#nil_error for details.

And a bit more detail: http://research.swtch.com/interfaces
