### ISSUE TITLE
runtime/race: invalid spdelta tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13568]
Weird trybot failure in tsan:

https://storage.googleapis.com/go-build-log/78af9465/linux-amd64-race_91e55cda.log
```
--- FAIL: TestStackBarrierProfiling (4.60s)
	pprof_test.go:342: subprocess failed with signal: segmentation fault:
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5307 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5307 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5307 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a530f 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a530f 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a530f 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5304 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5307 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x5a5270 0x5a5304 0x0 -1
FAIL
FAIL	runtime/pprof	13.799s
2015/12/10 18:38:36 Failed: exit status 1
```

/cc @aclements

**Comment by rsc** [comment]
I think that's the stack unwinder trying to unwind through TSAN during a profiling signal, which it should not. Looks like the linker is not writing down "I don't have information" correctly, or else the runtime is not recognizing it.

**Comment by dvyukov** [comment]
I was able to reproduce it once in 1000 runs, using ```stress ./pprof.test -test.short```:

--- FAIL: TestStackBarrierProfiling (1.16s)
	pprof_test.go:342: subprocess failed with signal: segmentation fault (core dumped):
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x59e850 0x59e8e7 0x0 -1
		invalid spdelta _ZN6__tsanL14MemoryRangeSetEPNS_11ThreadStateEmmmy.isra.32.part.33 0x59e850 0x59e8e4 0x0 -1
FAIL

It took more than an hour.
