### ISSUE TITLE
cmd/compile: arm64 cross-compilation errors "branch too far"

### ISSUE THREAD

**Issue by dvyukov** [golang/go#13579]
There is a similar fixed issue #12540, but I am on "go version devel +7ba85b5 Fri Dec 11 12:09:49 2015 +0100 linux/amd64" and hit the same compiler bug.

Here is the source:
https://gist.github.com/dvyukov/42bc81d1057c88fb6dcf

```
$ GOARCH=arm64 go build -v /tmp/stress/sys.go
# command-line-arguments
/tmp/stress/sys.go:1: branch too far
00004 (/tmp/stress/sys.go:1061)	CMP	$-1314, R1
/tmp/stress/sys.go:1: branch too far
00032 (/tmp/stress/sys.go:1061)	MOVD	$228912, R3
/tmp/stress/sys.go:1: branch too far
00052 (/tmp/stress/sys.go:1061)	SUB	$228080, RSP
/tmp/stress/sys.go:1: branch too far
00108 (/tmp/stress/sys.go:1061)	ADD	$228080, RSP
/tmp/stress/sys.go:1: branch too far
00292 (/tmp/stress/sys.go:5)	MOVD	$"".autotmp_1256-81440(SP), R0
/tmp/stress/sys.go:1: branch too far
00588 (/tmp/stress/sys.go:5)	MOVD	$"".autotmp_1257-177024(SP), R0
/tmp/stress/sys.go:1: branch too far
00624 (/tmp/stress/sys.go:5)	MOVD	$"".autotmp_1258-37624(SP), R0
/tmp/stress/sys.go:1: branch too far
00652 (/tmp/stress/sys.go:5)	ADD	$-8, R1
/tmp/stress/sys.go:1: branch too far
00660 (/tmp/stress/sys.go:5)	ADD	$-8, R0
/tmp/stress/sys.go:1: branch too far
00720 (/tmp/stress/sys.go:5)	MOVD	$"".autotmp_1258-37624(SP), R0
/tmp/stress/sys.go:1: too many errors
```

**Comment by dvyukov** [comment]
@minux @mwhudson @davecheney @rsc

**Comment by matt2909** [comment]
I'm not sure #12540 should have been closed - although it managed to compile the test case I attached, it still can't compile my internal codebase and I can't very easily generate a test case that stresses it in the same way, cross file linking etc... I'll try and generate one, but also trying to release my code on github too, but that might take a while longer .. need to convince those who have power to release it.

**Comment by matt2909** [comment]
Looking at the errors and the gist file you've attached, this is an almost identical issue to that which I see on my internal codebase. For me this means that the arm64 branch is broken.

I'm happy to test any fixes on my internal codebase in addition to the testcase you've got attached here.

**Comment by dvyukov** [comment]
Yes, it is sad. Russ, why did you set Unplanned?

FWIW to workaround this bug I currently use:

```go
func initCalls() {
        func() {
                Calls = append(Calls, &Call{ID: 0, Name: "open", CallName: "open", Ret: ResourceType{TypeCommon: TypeCommon{TypeName: "ret", IsOptional: false}, Kind: ResFD, Subkind: ResAny}, Args: []Type{PtrType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}, Dir: DirIn, Type: FilenameType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}}}, FlagsType{TypeCommon: TypeCommon{TypeName: "flags", IsOptional: false}, TypeSize: 0, Vals: []uintptr{0, 1, 2, 1024, 8192, 524288, 64, 16384, 65536, 128, 0, 262144, 256, 131072, 2048, 2097152, 1052672, 512}}, FlagsType{TypeCommon: TypeCommon{TypeName: "mode", IsOptional: false}, TypeSize: 0, Vals: []uintptr{256, 128, 64, 32, 16, 8, 4, 2, 1}}}})
        }()
        func() {
                Calls = append(Calls, &Call{ID: 1, Name: "open$dir", CallName: "open", Ret: ResourceType{TypeCommon: TypeCommon{TypeName: "ret", IsOptional: false}, Kind: ResFD, Subkind: FdDir}, Args: []Type{PtrType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}, Dir: DirIn, Type: FilenameType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}}}, FlagsType{TypeCommon: TypeCommon{TypeName: "flags", IsOptional: false}, TypeSize: 0, Vals: []uintptr{0, 1, 2, 1024, 8192, 524288, 64, 16384, 65536, 128, 0, 262144, 256, 131072, 2048, 2097152, 1052672, 512}}, FlagsType{TypeCommon: TypeCommon{TypeName: "mode", IsOptional: false}, TypeSize: 0, Vals: []uintptr{256, 128, 64, 32, 16, 8, 4, 2, 1}}}})
        }()
        func() {
                Calls = append(Calls, &Call{ID: 2, Name: "openat", CallName: "openat", Ret: ResourceType{TypeCommon: TypeCommon{TypeName: "ret", IsOptional: false}, Kind: ResFD, Subkind: ResAny}, Args: []Type{ResourceType{TypeCommon: TypeCommon{TypeName: "fd", IsOptional: false}, Kind: ResFD, Subkind: FdDir}, PtrType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}, Dir: DirIn, Type: FilenameType{TypeCommon: TypeCommon{TypeName: "file", IsOptional: false}}}, FlagsType{TypeCommon: TypeCommon{TypeName: "flags", IsOptional: false}, TypeSize: 0, Vals: []uintptr{0, 1, 2, 1024, 8192, 524288, 64, 16384, 65536, 128, 0, 262144, 256, 131072, 2048, 2097152, 1052672, 512}}, FlagsType{TypeCommon: TypeCommon{TypeName: "mode", IsOptional: false}, TypeSize: 0, Vals: []uintptr{256, 128, 64, 32, 16, 8, 4, 2, 1}}}})
        }()
...
```

**Comment by rsc** [comment]
It's Unplanned because arm64 is still an experimental (unstaffed) port and the reproduction case is huge. Now that I look at the case a second time I see that it's not a randomly generated program. On first glance I had thought it was.

I will change this to Go1.6Maybe but no promises.

**Comment by matt2909** [comment]
My reproduction case was auto generated, because I wasn't in a position to release the source, interestingly Dmitry's code is doing something incredibly similar and gets an identical branch too far message.

**Comment by matt2909** [comment]
Debugging into this a bit - it seems that at least some of the offending "branch too far" errors are coming from calls to omovlit, when the assembler is trying to insert a load literal; hence the output of MOVD etc.

The brdist is failing because the offset between the MOVD and the literal is out of the range of a 19 bit immediate. I have yet to discover why this happens - I'm not completely familiar with this code or when/how the literal pools get flushed and adjusted as we insert ops.

**Comment by matt2909** [comment]
I can't confirm this but on my internal code base, I never see the literal pool get flushed on arm64 (added debug to detect this into asm7.go). It appears the ctxt.Blitrl is always nil, and so flushpool is a null call.

**Comment by matt2909** [comment]
I can confirm that after @rsc adjusted the literal pool calculations that my internal codebase now compiles cleanly on arm64.

**Comment by matt2909** [comment]
@rsc thanks for fixing this!
