### ISSUE TITLE
cmd/release: linux-arm release build fails

### ISSUE THREAD

**Issue by davecheney** [golang/go#13577]
After applying CL 17663 the release build fails to complete the tests.
```
--- FAIL: TestGdbPython (4.19s)
        runtime-gdb_test.go:42: gdb version 7.7
        runtime-gdb_test.go:129: failed to load Go runtime support: warning: File "/usr/local/go/src/runtime/runtime-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/workdir/go/src/
runtime".
FAIL
FAIL    runtime 143.480s
```
I believe this is because the release build runs with GOROOT_FINAL set, altering the path to runtime-gdb.py which is embedded into the binary.

Blocks #13066

/cc @bradfitz @broady

**Comment by rsc** [comment]
Where did `auto-load safe-path` come from?

**Comment by davecheney** [comment]
It's coming from the Ubuntu 14.04 flavour of Linux our scaleway arm boxes
come with. I suspect the GCE Linux builders don't come with gdb installed.

**Comment by mwhudson** [comment]
Certainly my not very sophisticated approach to Debian package builds
failing on this test is to run them in a chroot that does not have gdb
installed.

**Comment by rsc** [comment]
https://go-review.googlesource.com/17970 should take care of disabling the test in this case.

**Comment by davecheney** [comment]
I went even more lowbrow. I used gomote to rm /usr/bin/gdb before the builder got to that phase of ./all.bash

**Comment by bradfitz** [comment]
Um, the scaleway builders don't run in Docker containers. They run under systemd with a freshly tmpfs as their build filesystem $WORKDIR, but /usr/bin/gdb was the host's gdb you deleted. :-)

**Comment by davecheney** [comment]
Oh crap. Sorry. I did not know that.

**Comment by rsc** [comment]
Did you try it with my CL before deleting gdb? Just curious whether it
helped at all.

**Comment by davecheney** [comment]
I did that process last week when I was trailing the change on the Go 1.5.2
release tag
