### ISSUE TITLE
type of variable passed into json decode changes 

### ISSUE THREAD

**Issue by hullarb** [golang/go#13574]
I tried to use functions to create the right structures for json decoding, this constructor function has a `func() interface{}` signature. After calling `json.Decode` with a pointer pointing to a struct created by this function, the type of the variable will be `map[string]interface{}` and not the given struct anymore.
Here's a complete example to reproduce this:
https://play.golang.org/p/PQwC4tu71E

**Comment by bradfitz** [comment]
For asking questions about learning the language, see one of our forums: https://golang.org/wiki/Questions

We only use this issue tracker for tracking bugs. People in the forums can explain what is happening here.
