### ISSUE TITLE
path/filepath: EvalSymlinks no longer does

### ISSUE THREAD

**Issue by rsc** [golang/go#13582]
Here's a program that creates /tmp/c -> /tmp/b -> /tmp/a and calls filepath.EvalSymlinks.
Also, on my Mac, /tmp -> /private/tmp.

	package main
	
	import (
		"fmt"
		"os"
		"path/filepath"
	)
	
	func main() {
		os.Remove("/tmp/a")
		os.Remove("/tmp/b")
		os.Remove("/tmp/c")
		os.Create("/tmp/a")
		os.Symlink("/tmp/a", "/tmp/b")
		os.Symlink("/tmp/b", "/tmp/c")
		fmt.Println(filepath.EvalSymlinks("/tmp/c"))
	}

This no longer finds /private/tmp/a, like it has in the past:

	$ go1.2 run /tmp/x.go
	/private/tmp/a <nil>
	$ go1.3 run /tmp/x.go
	/private/tmp/a <nil>
	$ go1.4 run /tmp/x.go
	/private/tmp/a <nil>
	$ go1.5 run /tmp/x.go
	/private/tmp/a <nil>
	$ go run /tmp/x.go
	/tmp/b <nil>
	$ 

I suspect CL 16192.

This broke a real test inside Google as well.

**Comment by rsc** [comment]
@alexbrainman, might be CL 16192.

**Comment by alexbrainman** [comment]
Please say sorry to Google from me. I will try and fix this.

Alex

**Comment by bradfitz** [comment]
Don't worry, it didn't actually break anything real inside Google. We're just doing our normal Go release process thing where we test out all Google's internal unit tests with the Go master branch before we start making a release. Internally we're still using Go 1.5.

**Comment by alexbrainman** [comment]
@bradfitz I was trying to be funny. I always do, but it never works. :-(

Alex
