### ISSUE TITLE
tour: Outputting ASCII 0xC causes output on web page to be different than output on computer

### ISSUE THREAD

**Issue by joelself** [golang/go#13588]
Context: https://tour.golang.org/methods/12

On the Exercise: rot13Reader

I did it incorrectly at first which caused the output to contain an ASCII 0xC (NP form feed, new page) which causes the output to be cleared so instead of what you would see on a local computer:

```
b len 32768
count 21 err <nil>



b len 32768
count 0 err EOF
```

You only see:

```
b len 32768
count 0 err EOF

Program exited.
```

It made  me think I was doing something wrong in reading the string. Here's a full program that will reproduce the problem:

```go
import (
	"fmt"
	"io"
	"os"
	"strings"
)

type rot13Reader struct {
	r io.Reader
}

func (rot *rot13Reader) Read(b []byte) (count int, err error) {
    fmt.Println("b len", len(b))
    count, err = rot.r.Read(b)
    fmt.Println("count", count, "err", err) 
    for i := 0; i < count; i+=1 {
        b[i] = 12 // NP form feed, new page
    }
    return count, err
}

func main() {
	s := strings.NewReader("Lbh penpxrq gur pbqr!")
	r := rot13Reader{s}
	io.Copy(os.Stdout, &r)
}
```

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by campoy** [comment]
I don't see how to fix this other than adding a warning regarding special ASCII characters.

I don't want to change the current behavior as some cool programs depend on it, such as this awesome ASCII train: http://play.golang.org/p/NOycgN2i6b

**Comment by joelself** [comment]
It probably wouldn't have helped. If other stuff relies on this behavior then I guess it doesn't make sense to change it.

**Comment by campoy** [comment]
Thanks for reporting!
