### ISSUE TITLE
None compatible behaviour from 1.4 to 1.5 in creating 1024 RSA Pub Key from too many bytes

### ISSUE THREAD

**Issue by danmux** [golang/go#13580]
Probably not a bug per se. as the new behaviour is correct, however it is a compatibility breaking change. Suggest no fix, imho.
Raising this issue really as a record of the difference, the minor change to keep things working in 1.5 is to truncate the key to the first 162 bytes (as long as you know you are only dealing with 1024 bit RSA PK's)  

>What version of Go are you using (go version)?

Using 1.4 then migrating to 1.5.2, also tested on 1.5.0

>What operating system and processor architecture are you using?

Mac OSX - but reproduceable on RedHat (not 100% sure of version but I think incedental)
go version go1.5 darwin/amd64 - via installer pkg download

>What did you do?

Ran a test to return involving a long public key with more bytes than needed.

>What did you expect to see?

The test pass when running on golang 1.4, and the test still pass when running on 1.5.0

>What did you see instead?

The test pass when running on golang 1.4, and the test fail when running on 1.5.0 wiht the following error

	`x509: trailing data after ASN.1 of public-key`

The offset is clearly returned from this line https://golang.org/src/encoding/asn1/asn1.go?s=26808:26872#L957

The code to reproduce is here ...

http://play.golang.org/p/XkkAqFenC8

the snippet here...

	pkb, _ := base64.StdEncoding.DecodeString(`MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDgkHKMf4B5yc8CU29XdQIj8tQAAyOL0DM3C/F9euuFickCd2brILEhBKDH9NQomP5wc77B3vAbNH0Iza+GSPpjDJ4+Sjg9OsNP7UpWcxbfXBrN7UEUfISc9ZKrhijkS3p7M/8o78XHTjsq1PJKImakBIA0G+VoOj1pVF5BAnBl7QIDAQAB/F9euuFickCd2brILEhBKDH9NQomP5wc77B3vAbNH0IzaGSPpjDJ4Sjg9OsNP7UpWcxbfXBrN7UEUfISc9ZKrhijkS3p7M/8o78XHTjsq1PJKImakBIA0GVoOj1pVF5BAnBl7QIDAQAB`)

	pubKey, err := x509.ParsePKIXPublicKey(pkb) // err != nil

**Comment by rsc** [comment]
Where did this key come from? That is, why do you have a base64 encoding of a key + extra data? How does this come up in practice? I am trying to understand how likely it is that others are affected. Thanks.

**Comment by danmux** [comment]
Ah right, well it was from a legacy Rails codebase which we fully migrated to go (a now familiar story). And it existed in those specs afair, so the key came along for the ride. Having said that I think the keypair would always have originated on a client device (iOS) - though for sure no device initiated keys in recent integration tests exhibit this now.

**Comment by rsc** [comment]
OK. Let's close this and revisit if additional reports come in. Thanks.

**Comment by danmux** [comment]
Yes - tiny bit more info fully in support of closing - the only reference to this key on the old codebase is in (many) jmeter tests - where it is some kind of hybrid url encoded mixed up monster of a key - which I'm told could easily have been generated by the rails codebase and sent to an earlier web based client ap. Still at least its documented forever now :/

**Comment by danmux** [comment]
Ok some absolute reasoning in support of closing - this was an issue with iOS 5 - it appears Apple decided to cut some fields out of the ASN.1 encoding for their X509 pk's(1), they stopped doing this in iOS 6 onwards. iOS 5 possibly accounts for around < 1.4% of all iOS versions in the wild(2) so surely < 0.3% (3) of all mobile generated pks to hit servers. 

(1) - http://blog.wingsofhermes.org/?p=42
(2) - https://david-smith.org/iosversionstats/
(3) - my guesswork
