### ISSUE TITLE
test/bench/shootout: files have licenses without copyright line

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#13584]
In the "Go" repository, the following files, similar to issue #13575, embed a copy of what looks like part of a typical BSD license, which refers to a non-existent copyright notice.

The following files appear to be have been "contributed by the Go Authors", so perhaps like the resolution of #13575 should simply have their header replaced with the "usual" copyright header:

```
test/bench/shootout/reverse-complement.go
test/bench/shootout/regex-dna-parallel.go
test/bench/shootout/k-nucleotide.go
test/bench/shootout/threadring.go
test/bench/shootout/chameneosredux.go
test/bench/shootout/k-nucleotide-parallel.go
test/bench/shootout/regex-dna.go
```

The following files also appear to be have been "contributed by the Go Authors", however, they also claim to be based on a different source file presumably authored by someone else, so it is unclear whether they should use the "usual" copyright header:

```
test/bench/shootout/pidigits.go
test/bench/shootout/spectral-norm.go
test/bench/shootout/meteor-contest.go
test/bench/shootout/mandelbrot.go
test/bench/shootout/binary-tree.go
test/bench/shootout/fasta.go
test/bench/shootout/binary-tree-freelist.go
test/bench/shootout/fannkuch.go
test/bench/shootout/spectral-norm-parallel.go
test/bench/shootout/fannkuch-parallel.go
test/bench/shootout/nbody.go
test/bench/garbage/tree.go
```

The following files are also missing a copyright notice, but do not have the text "contributed by The Go Authors", so presumably cannot use the "usual" copyright header:

```
test/bench/shootout/meteor-contest.c
test/bench/shootout/chameneosredux.c
test/bench/shootout/spectral-norm.c
test/bench/shootout/binary-tree.c
test/bench/shootout/fannkuch.c
test/bench/shootout/nbody.c
test/bench/shootout/mandelbrot.c
test/bench/shootout/pidigits.c
test/bench/shootout/fasta.c
test/bench/shootout/threadring.c
test/bench/shootout/reverse-complement.c
test/bench/shootout/regex-dna.c
test/bench/shootout/k-nucleotide.c
```

**Comment by ianlancetaylor** [comment]
Those files are intended for the benchmark game, and my understanding is that the game requires that all submissions use their license, which is at http://benchmarksgame.alioth.debian.org/license.html.  So any fixes here should be to make the files consistently use that license.

**Comment by bradfitz** [comment]
@binarycrusader, also note that if you're just packaging Go for a distro, you can safely drop those files.

**Comment by rsc** [comment]
To be clear, those files all contain a license, just not a copyright line (I realize that's somewhat odd). I can't explain how that arose, but I am pretty sure they match the files from the shootout site at the time we copied them. Of course, the site looks completely different now, like someone mobile-optimized it by hiding everything, so I can't figure out if the current files still look that way.

**Comment by rsc** [comment]
Maybe now that the shootout has Go programs we don't need them in our own tree. Should we just delete them? We don't actually use them for benchmark purposes anymore. We use test/bench/go1 and the benchmarks subrepo.

@ianlancetaylor what do you think?

**Comment by ianlancetaylor** [comment]
@rsc We would lose the historical data in test/bench/shootout/timing.log, but I see that hasn't been updated in over 2 years anyhow.  I would vote for moving them out of the main tree into golang.org/x/exp.
