### ISSUE TITLE
fmt: drop Scanf %X support for bytes and strings?

### ISSUE THREAD

**Issue by rsc** [golang/go#13585]
CL https://go-review.googlesource.com/#/c/15689/ made a trivial change to fmt.Scanf to make %X an alias for %x when applied to []byte and string values.
%x has always (even before Go 1) accepted either upper or lower case; now %X does too.

The only real effect here is that now people can write code using %X, which will only work with Go 1.6 or later, when they could instead use %x and work with Go 1 or later.

Should we keep the new %X support?
Leaving for @robpike to decide.

The original issue was #12940.

**Comment by robpike** [comment]
It seems like a regularization to accept %X, but there is always a cost to any addition of a feature. Taking that worry too far, we can't change anything ever.

The problem of versioning is being addressed by the community, and in that light I think it's fine for this minor cleanup to persist.
