### ISSUE TITLE
Decode issue: seems the decode cannot work properly sometimes

### ISSUE THREAD

**Issue by feikiss** [golang/go#13591]
Hi,
 I have a encoded string, basically, this is a valid string and I can decode it using Java or Nodejs correctly. When I decode it using golang, it will throw an error saying "illegal base64 data at input byte 368", the sample code is here: http://play.golang.org/p/InjN-Fr3gO  

Notes: If I add an character "=" , it will decode it correctly and the result is expected. This should be a bug for Golang decoding feature. Hope it can be fixed.

Thanks,
Xiaofei

**Comment by cespare** [comment]
Your base64-encoded string doesn't have padding, so you need to use a encoding variant that doesn't expect padding. In this case, you want `RawStdEncoding` rather than `StdEncoding`.

http://play.golang.org/p/IscQiVxXcn

**Comment by feikiss** [comment]
Hi @cespare ,
 Thanks for your reply.  Currently I'm using "go version go1.4.2 windows/amd64". Because of some building server environment reason, I cannot upgrade the go version now. Still thanks for you and I think this ticket can be closed.
