### ISSUE TITLE
go/ast: the position of "range" keyword is lost during parsing

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13590]
Although the AST does not record the entire concrete syntax, it does record most of the important tokens.  The position of the "range" token can't be reliably reconstructed from an ast.RangeStmt, and I need to use it to indicate the location of an implicit channel receive operation.  I propose to add a 'Range token.Pos' field to ast.RangeStmt and set it in the parser.

**Comment by rsc** [comment]
Closing per discussion on CL 17770. (Suggestion is to use RangeStmt.X.Pos() or if X==nil then RangeStmt.Body.Lbrace, and work backward from there.)
