### ISSUE TITLE
flag: panic on android/arm64

### ISSUE THREAD

**Issue by karalabe** [golang/go#13599]
Just been cross compiling to various flavors of Android, and hit a bug present on `android/arm64` (it works as intended on both `android/arm` and `android/386`). The `flag` package reads `os.Args[0]` at https://github.com/golang/go/blob/master/src/flag/flag.go#L939, which is not initialized on `android/arm64`, producing a hard crash.

**Comment by karalabe** [comment]
After some digging around in the code base, the issue is that the `os.Args` isn't initialized for `android/arm64` when building with `buildmode=c-shared`.

[`android/arm64`](https://github.com/golang/go/blob/master/src/runtime/rt0_android_arm64.s) vs. [`android/arm`](https://github.com/golang/go/blob/master/src/runtime/rt0_android_arm.s)

**Comment by karalabe** [comment]
PTAL https://go-review.googlesource.com/#/c/17782/

**Comment by rsc** [comment]
Presumably fixed by CL 17782.

**Comment by karalabe** [comment]
Ah yes, thought it would be auto closed.

**Comment by rsc** [comment]
It gets auto-closed when the commit message says 'Fixes #13599.' But that
got dropped or omitted somehow. :-)
