### ISSUE TITLE
text/template: not documented that the $ is root variable.

### ISSUE THREAD

**Issue by kybin** [golang/go#13592]
Inside of {{range (root).A}} loop, I wanted use (root).B. But intead it refers (root).A.B. 

I noticed it's expected behavior, but I couldn't find what is the root variable in the [document of text/template](https://golang.org/pkg/text/template/) but found in [stackoverflow](http://stackoverflow.com/a/22873315).

I think we need explanation of what is root variable in the standard document of text/template.

**Comment by lstokeworth** [comment]
The variable $ is documented in  [the section on variables](https://golang.org/pkg/text/template/#hdr-Variables):

> When execution begins, $ is set to the data argument passed to Execute, that is, to the starting value of dot.

**Comment by kybin** [comment]
Ah, I didn't catch that.. 

I still think it's needs more clarification. (for non-english users?) But that purely depends on go-team's decision. 

Thank you for letting me know. @lstokeworth
