### ISSUE TITLE
golang.org/x/ regression: `undefined: sliceMax`

### ISSUE THREAD

**Issue by mmikulicic** [golang/go#13603]
```
$ go get -u golang.org/x/tools/cmd/stringer
# golang.org/x/tools/go/types
../golang.org/x/tools/go/types/expr.go:1300: undefined: sliceMax
```

It looks the regression has been introduced in https://go-review.googlesource.com/#/c/17792/

Sorry, not sure if this is the right repo to file an issue to.

**Comment by bradfitz** [comment]
Yeah, looks like @dsymonds forgot a file.
