### ISSUE TITLE
website: Gerrit tarballs for the base packages aren't deterministic

### ISSUE THREAD

**Issue by yurivict** [golang/go#13600]
Downloading this URL: https://go.googlesource.com/net/+archive/d75b190.tar.gz?dummy=/golang-net-d75b190.tgz
always produces a different tar archive. Contents are the same, but tar metadata is different. This prevents using such URLs as fingerprinted distfiles in FreeBSD.

It might be that https://go.googlesource.com uses BSD tar that suffers from this bug: https://github.com/libarchive/libarchive/pull/623 (in this case the fix is switching to GNU tar).

Please either fix this, or provide an alternative URL.

**Comment by bradfitz** [comment]
The Go project doesn't run that Gerrit server, nor do we maintain the Gerrit codebase.

We provide downloads at https://golang.org/dl/

But in the spirit of http://xyproblem.info/, what are you actually trying to do? It appears you're trying to package Go subrepos? Why those? And what Git revisions do you pick and why? 

/cc @spearce

**Comment by yurivict** [comment]
I am separately downloading packages that go into the build of go project in order to make the FreeBSD port.

**Comment by bradfitz** [comment]
Which binaries are you trying to build?

**Comment by yurivict** [comment]
I build the gogs project from sources. No binaries.

**Comment by yurivict** [comment]
@bradfitz Whom to ask to get Gerrit tarballs determinicity fixed? I am almost positive the problem is BSD tar bug.

**Comment by bradfitz** [comment]
gogs has no binaries? I meant executables. FreeBSD is trying to build something if it needs source code I would assume.

In any case, this sounds like a FreeBSD/gogs/Gerrit issue, so I'm closing this bug.

See https://www.gerritcodereview.com/ for links to Gerrit project info (issue tracker, etc).
