### ISSUE TITLE
x/tools/godoc: no max-width on <ul> element

### ISSUE THREAD

**Issue by ALTree** [golang/go#13602]
In `style.css`, we have

```
p {
	max-width: 800px;
	word-wrap: break-word;
}
```

while the `<ul>` element does not have a maximum width, and this result in the ugly long lines you can see in https://golang.org/doc/contribute.html, in the "Contributor License Agreement" section.

**Comment by campoy** [comment]
Please review

https://go-review.googlesource.com/17911 godoc: apply max-width to lists too

**Comment by rsc** [comment]
ping @campoy (please fix your CL)
