### ISSUE TITLE
spec: Integer Operators - Confusing figure/improper formatting

### ISSUE THREAD

**Issue by deathly809** [golang/go#13601]
Under Arithmetic Operators -> Integer Operators

When discussing the exceptions to the truncate towards zero rule we are presented with this figure:

<pre>
						 x, q
int8                     -128
int16                  -32768
int32             -2147483648
int64    -9223372036854775808
</pre>

At first I found the figure to be confusing and thought that maybe it was missing values on the right.  Later I realized that x refers to the types on the left.

Here is what I propose as an alternative:

<pre>
x						    q
int8                     -128
int16                  -32768
int32             -2147483648
int64    -9223372036854775808
</pre>

**Comment by griesemer** [comment]
Actually this formatting is intended and I believe correct. Note the sentence:
```
As an exception to this rule, if the dividend x is the most negative value for the int type of x, the quotient q = x / -1 is equal to x (and r = 0).
```
As is says, x and q are **the same** in these cases.

Closing.
