### ISSUE TITLE
runtime/pprof: invalid spdelta __x86.get_pc_thunk.cx ... (android/386)

### ISSUE THREAD

**Issue by hyangah** [golang/go#13617]
Observed a couple of runtime/pprof TestCPUProfileMultithreaded test failures
with the following error message.

<pre>
--- FAIL: TestCPUProfileMultithreaded (0.26s)
	pprof_test.go:169: total 25 CPU profile samples collected
	pprof_test.go:185: runtime/pprof_test.cpuHog1: 25
	pprof_test.go:185: runtime/pprof_test.cpuHog2: 0
	pprof_test.go:199: runtime/pprof_test.cpuHog2 has 0 samples out of 25, want at least 1, ideally 12
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742430 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
invalid spdelta __x86.get_pc_thunk.cx 0xf7742430 0xf7742433 0x0 -1
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/pprof.test-11065
FAIL	runtime/pprof	14.152s
</pre>

**Comment by mwhudson** [comment]
I guess correct spdelta data for this function shouldn't be hard to create, I don't at all know how to do it though.

**Comment by rsc** [comment]
Duplicate of #13568.
