### ISSUE TITLE
cmd/cover: zero coverage for cgo project

### ISSUE THREAD

**Issue by zhulik** [golang/go#13625]
Hi, i writing bindings for libmediainfo and when i start to write tests i noted, that coverage is 0.0% and coverprofile is empty, i don't see any files in dropdown when doing `go tool cover -html=coverage.out`.

`go version go1.5.2 linux/amd64`

Steps to reproduce:

```
git clone https://github.com/zhulik/go_mediainfo.git
cd go_mediainfo
go test -cover
```

I know, that this is not first issue with cgo and coverage, #6333 is closed over a year ago, but i have the same issue now.

**Comment by gaillard** [comment]
I get the same thing on go1.6. :+1: for fix :)

**Comment by bradfitz** [comment]
@robpike, is `cmd/cover` compatible with `cgo`?

**Comment by robpike** [comment]
It's supposed to. See #6333.

**Comment by ALTree** [comment]
Simple reproducer:

rand.go:
```go
package rand

/*
#include <stdlib.h>
*/
import "C"

func Random() int {
	return int(C.random())
}

func Seed(i int) {
	C.srandom(C.uint(i))
}
```

rand_test.go:
```go
package rand_test

import (
	"testing"

	"github.com/ALTree/rand"
)

func TestRandom(t *testing.T) {
	x := rand.Random()
	if x < 0 {
		t.Fatalf("%d < 0\n", x)
	}
}
```

`go test -cover` gives 0.0% **if and only if the tests are  in a separate package** (in this case, `rand_test`). If the package declaration in rand_test.go is changed to `package rand`, `-cover` reports a correct value; and that is the reason the test introduced in [CL 71230049](https://github.com/golang/go/commit/9abcd53eda0629d009941027ffa2dc680b5f1d00) by rsc didn't catch the problem (that test has `package p` for both the cgo file and the `_test` file).
