### ISSUE TITLE
gccgo, syscall:  unknowndefine NLA_HDRLEN

### ISSUE THREAD

**Issue by laboger** [golang/go#13629]
The definition for syscall NLA_HDRLEN is missing from gccgo in both trunk and the release 5 branch.  This is the only one of the NLA_* syscall defines missing from gccgo.  All of these syscall are correctly defined in golang master and go 1.5.x branch.

Testcase:

package main

import (
        "fmt"
        "syscall"
)

func main() {
    fmt.Printf("NLA_HDRLEN: %x\n", syscall.NLA_HDRLEN)
    fmt.Printf("NLA_F_NESTED: %x\n", syscall.NLA_F_NESTED)
    fmt.Printf("NLA_F_NET_BYTEORDER: %x\n", syscall.NLA_F_NET_BYTEORDER)
    fmt.Printf("NLA_ALIGNTO: %x\n", syscall.NLA_ALIGNTO)
}

With gccgo this error occurs:

error: reference to undefined identifier 'syscall.NLA_HDRLEN'
     fmt.Printf("NLA_HDRLEN: %x\n", syscall.NLA_HDRLEN)

Testcase compiles correctly with golang.
Comment out the line with NLA_HDRLEN and the testcase compiles correctly with gccgo.

**Comment by ianlancetaylor** [comment]
This needs the "Constants that may only be defined as expressions on some systems" treatment in libgo/mksysinfo.sh.

**Comment by laboger** [comment]
Thanks for the pointer, I'll try it.

**Comment by laboger** [comment]
https://go-review.googlesource.com/#/c/17893
I have done a test build to verify it fixes the problem, I am currently doing a bootstrap build and will update this when it is finished.

**Comment by laboger** [comment]
Testing complete.

**Comment by laboger** [comment]
I've uploaded the changes to mksysinfo.sh.

I was looking in the file sysinfo.go and I see there is also a constant named SizeofNlAttr.  Shouldn't this always be the same value as NLA_HDRLEN?  If so then I think the Docker folks could use syscall.SizeofNlAttr instead of syscall.NLA_HDRLEN and it should work for both gccgo and gc.

**Comment by laboger** [comment]
Never mind, I missed the alignment difference.

**Comment by ianlancetaylor** [comment]
CL was committed.  Not sure why it didn't auto-close.
