### ISSUE TITLE
"golang.org/x/crypto/openpgp": strange behaviour with passwords "climatically" and "fezzes"

### ISSUE THREAD

**Issue by GoBijan** [golang/go#13627]
There seem to be problems with "climatically" and "fezzes" as passwords.
When using "climatically": Program terminates with "openpgp: unsupported feature: public key version"
When using "fezzes": Program terminates with "openpgp: invalid data: tag byte does not have MSB set"
Expected behaviour would be a reinvokation of the prompt function in an endless loop until the right password is used.

Here is my gist:
https://gist.github.com/GoBijan/70b50114429e561f80c8

Is this a bug in the implementation?

**Comment by tv42** [comment]
https://godoc.org/golang.org/x/crypto/openpgp/packet#SymmetricallyEncrypted.Decrypt

"An incorrect key can, with high probability, be detected immediately and this will result in a KeyIncorrect error being returned."

I think this is as-good-as-it-gets with GPG, and you need an AEAD, like https://godoc.org/golang.org/x/crypto/nacl/secretbox to do better.

**Comment by bradfitz** [comment]
Can we move this to a forum? See https://golang.org/wiki/Questions
