### ISSUE TITLE
cgo getting confused by struct field name which is the same as a type #define

### ISSUE THREAD

**Issue by bits01** [golang/go#13634]
First of all, I'm no C expert so I'm not sure whether the following is valid C, but it compiles and works OK with gcc on Linux. cgo also works but the field name is wrong. I ran into this with some library I was trying to use, more complicated code so I tried to put together a simple example.
See test.h and main.go files in the attached zip file.

[bug.zip](https://github.com/golang/go/files/63525/bug.zip)

**Comment by ianlancetaylor** [comment]
Dup of #9601 .

**Comment by bits01** [comment]
Is this really a dup? #9601 says that macros are not recognized as field names. My issues seems to be quite the opposite, a filed name is mistaken for a macro, so on the Go side the struct field is the macro, the actual field name is not considered valid.

**Comment by ianlancetaylor** [comment]
I think it boils down to the same issue: macros confuse cgo.
