### ISSUE TITLE
net/http: ServeMux also eliminates repeating "/"

### ISSUE THREAD

**Issue by egonelbre** [golang/go#13639]
Just a documentation issue that - `http.ServeMux` (cleanPath) gets also rid of duplicate `/`-s. `http.ServeMux` already contains:

> ServeMux also takes care of sanitizing the URL request path, redirecting any request containing . or .. elements to an equivalent .- and ..-free URL.

I'm not sure how to reword it nicely to include the case of empty path segments, hence I didn't make a CL. Here's shortest example:
```
package main
import ("fmt"; "net/http")
func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "%s", r.URL.Path)
	})
	http.ListenAndServe(":8001", nil)
}
```

`/hello////world` will redirect to `/hello/world`. From URI standpoint they are different and both valid (https://tools.ietf.org/html/rfc3986#section-3.3).

**Comment by bradfitz** [comment]
Related: #11757

@rsc, I can try to document these but feel free to steal these two as I still consider you the ServeMux owner. I've never really worked on it.

**Comment by rsc** [comment]
Thanks. I'll take these two.
