### ISSUE TITLE
tour: code sample is "undefined"

### ISSUE THREAD

**Issue by rightfold** [golang/go#13640]
Context: http://tour.golang.org/welcome/4

The code sample of this page is `undefined` instead of something sensible.

Using Chromium 44.0.2403.89 (64-bit) on Linux.

![2015-12-16-112245_771x249_scrot](https://cloud.githubusercontent.com/assets/5132125/11838431/58ea4ed8-a3e7-11e5-8f33-c8a335a5d4d0.png)

**Comment by mattn** [comment]
I can't reproduce it on google chrome 47.0.2526.80 m (64-bit) on windows. Could you turn-on developer tools? And is there something errors?

**Comment by rightfold** [comment]
Console is empty. XHR requests don't show anything unusual.

**Comment by rightfold** [comment]
Frankly, I can't seem to reproduce it either if I go incognito.
