### ISSUE TITLE
tour: Editor not showing

### ISSUE THREAD

**Issue by FedericoPonzi** [golang/go#13643]
Contesto: https://go-tour-ita.appspot.com/basics/1
The go editor is not showing up.

There is a `hidden` class on the editor: 

    <div class="relative-content hidden" ng-class="{hidden: toc.lessons[lessonId].Pages[curPage-1].Files.length==0}">

Removing the hidden token the editor comes back again, but it dosen't work

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by campoy** [comment]
This is an old version of the Go tour and the editor is not supposed to show up, as there's no code for this slide.

You can see something similar in the official tour [http://tour.golang.org/welcome/2]
