### ISSUE TITLE
API check (typechecking package net) fails at go tip

### ISSUE THREAD

**Issue by rjammala** [golang/go#13653]
go version devel +7a2913c Thu Dec 17 15:48:10 2015 +0000 darwin/amd64

##### API check
Error running API checker: exit status 1
2015/12/17 10:41:20 error typechecking package net: /Users/rajanikanth.j/go/src/net/hook.go:11:47: undeclared name: dnsDialer (windows-amd64)
exit status 1
2015/12/17 10:41:20 Failed: exit status 1

**Comment by bradfitz** [comment]
Fixed, thanks.
