### ISSUE TITLE
doc: explain multi-commit Gerrit usage

### ISSUE THREAD

**Issue by rsc** [golang/go#13651]
We should finally do this. Perhaps the real docs belong in the git-codereview tool but the contribute guidelines should at least mention the possibility.

**Comment by dr2chase** [comment]
Is this in any way helpful?  I can revise it pretty easily (original is in Omnigraffle, I hope vector PDF comes through, SVG is not accepted).
[Git-MC-FSM.pdf](https://github.com/golang/go/files/65538/Git-MC-FSM.pdf)
