### ISSUE TITLE
net/http: http2 Transport doesn't know about 100-continue response headers

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13659]
the http2 Transport needs to know about 100-continue headers.

There can actually be 3 HTTP response HEADERS for a stream: 100-continue, the real headers, then the trailers.

/cc @bmizerany

**Comment by rsc** [comment]
@bradfitz, what's left after CL 17982? Is it still on the table for Go 1.6?

**Comment by bradfitz** [comment]
I think this one's relatively easy. I'm working on debugging #13556 at the moment and then I'll switch to this one.

**Comment by bradfitz** [comment]
Working on this one now.
