### ISSUE TITLE
bufio: Reader and Writer Support add a method use caller's buf?

### ISSUE THREAD

**Issue by Terry-Mao** [golang/go#13650]
I wrote a tcp server, i use `bufio.Writer` and `bufio.Reader` to read and write with a connection, after many connections, the heap objects grows many, if bufio support this, i can reduce <b>4</b> objects per connections, the bufio.Writer and bufio.Reader inline with my own struct, and buf i use a big buffer reused by bufio.
```golang
// sth like this
func (w *Writer) NewWriterBuffer(w io.Writer, buf []byte) error {
  w.buf = buf
  // ...
}

type MyStruct struct {
  w *bufio.Writer 
// others
}

// switch to 
type MyStruct struct {
  w bufio.Writer 
  r bufio.Reader 
// others
}

func NewMyStruct() *MyStruct {
  s := new(MyStruct)
  s.w.NewWriterBuffer(xxx, mybuf)
  s.r.NewReaderBuffer(xxx, mybuf1)
}
```

**Comment by bradfitz** [comment]
You can reuse bufio Readers and Writers to save on garbage. Look at their `Reset` methods.

I don't think we'll be making further API changes to bufio.
