### ISSUE TITLE
x/build/cmd/release: run make.bash instead of all.bash if all.bash passed previously

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13663]
cmd/release used to be fast and only ran make.bash.

Now it runs all.bash, which is slow.

But if all.bash already succeeded in the past there's no need to run the tests again. Maybe consult build.golang.org and ask if it already succeeded, and then switch to make.bash instead?

/cc @broady

**Comment by adg** [comment]
I rolled the binaries yesterday and didn't think they took a particularly long time. The ARM ones, maybe.  I feel like this is just optimizing for little real benefit.

Also—not that I distrust our build infrastructure, but—I feel there is some value in running the tests one last time before handing over binaries to our users.

**Comment by broady** [comment]
This was a problem because I kept bumping into intermittent failures. Maybe those failures have stopped.

Let's re-open if releases get annoying again.
