### ISSUE TITLE
net/http: docs for http2 appears in package documentation

### ISSUE THREAD

**Issue by ericchiang** [golang/go#13668]
The h2_bundle.go file doesn't remove the "http2" package documentation string [here](https://github.com/golang/go/blob/90a68935733ef37d41cb520ffeb56f196a356811/src/net/http/h2_bundle.go#L4-L15).

See the bottom of the package documentation at https://tip.golang.org/pkg/net/http/

**Comment by bradfitz** [comment]
hah! Good find, thanks.

Alan, can you add a flag to x/tools/cmd/bundle like --break_pkg_doc which adds a newline before the package statement? Otherwise I can do it manually in my wrapper script.

/cc @alandonovan

**Comment by adonovan** [comment]
https://go-review.googlesource.com/18040
