### ISSUE TITLE
website: tip.golang.org auto-scaling is broken

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13682]
Please turn off auto-scaling or fix the health check handler.

It's totally bogus that our public Go 1.6 docs we're linking to are down half the time.

The health check handler from last night didn't work:

![screen shot 2015-12-18 at 10 22 28 am](https://cloud.githubusercontent.com/assets/2621/11903903/67acda0e-a571-11e5-8fe6-7b977ba0fa6c.png)

**Comment by broady** [comment]
reverting to the version with the old health checker.

**Comment by bradfitz** [comment]
Just turn off auto-scaling. The old health checker also didn't work.

Until we understand the problem, configure exactly N instances.

**Comment by odeke-em** [comment]
I noticed that too last night.

**Comment by broady** [comment]
We're running on 4 VMs now with no autoscaling. Looks like the health checker we wrote (https://go-review.googlesource.com/#/c/18025/) doesn't do anything.

I'm investigating more, and filling bugs with the Managed VMs team.

**Comment by bradfitz** [comment]
Status update here? Was the health checker returning the wrong 5xx code due to incorrect documentation?

**Comment by broady** [comment]
Indeed. Only 502, 503, 504 are unhealthy for Managed VMs. The docs are now updated:
https://cloud.google.com/appengine/docs/managed-vms/custom-runtimes

> Note: Although 200 is the preferred healthy status code, all other status codes except 502, 503, and 504 are also treated as a healthy response.

I'll update the app to use 503.

**Comment by broady** [comment]
It still only scales from 1-2, but when it does bring up a new instance, the autoscaler will wait for godoc to finish building before directing traffic to that instance.
