### ISSUE TITLE
net/http: http2 transport doesn't send a default User-Agent

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13685]
The Go http2 client doesn't send a default User-Agent header like the http1 client.

/cc @bmizerany

**Comment by odeke-em** [comment]
CL mailed https://go-review.googlesource.com/#/c/18033/

**Comment by rakyll** [comment]
@bradfitz, could we append the default agent even if User-Agent is set? This allows us to see traffic metrics related to clients written in Go.

**Comment by minux** [comment]
I don't like always appending the default user-agent.
If the user specifies the user agent, it must be for a
reason, and Go should respect that.

**Comment by rakyll** [comment]
I agree that client code must be able to override.

I'd be happy if we were allowing users to append to the default if they'd like to. But there are numerous ways to construct a Request instance (including the zero-value Request) and setting the default user agent during construction is not an option.

**Comment by bradfitz** [comment]
@rakyll, let's move that planning into #13837

This bug is just about http2 feature and behavior parity with http1 for Go 1.6.
