### ISSUE TITLE
net/http: Transport should de-UTF-8 hostname in Host header

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13686]
From golang-nuts, a test was failing in Go 1.6 against httptest.Server because of a unit test line:

```go
	{"http://Doppel.Gänger/foo_Bar-Foo", []byte(`T€st Cont€nt 123`), false},
```

I suspect the http client is sending the "ä" as literal UTF-8 bytes in the Host header, not as punycode or whatever.

**Comment by odeke-em** [comment]
@bradfitz which file/lines should this test be added to reproduce it? Or even the link, please?

**Comment by rsc** [comment]
We've lived a long time without this. We don't need to rush it into Go 1.6. Let's figure it out for Go 1.7. It's a huge topic.

**Comment by bradfitz** [comment]
Didn't happen for 1.7.

**Comment by rsc** [comment]
Brad, is this NeedsFix or NeedsDecision? Still for Go 1.8?

**Comment by bradfitz** [comment]
I did IDNA/Punycode already for Go 1.8. This was fixed by https://golang.org/cl/29072 (git rev b7e53038b8abb4d82cf25cb844395af602150a29)
