### ISSUE TITLE
bots: improve handling of PRs and gopher-bot response

### ISSUE THREAD

**Issue by benjamin-rood** [golang/go#13687]
*(Per Brad Fitzgerald's prompting to write up my idea into an issue in https://github.com/golang/go/issues/13665)*

Even though it is generally well understood in the contributing community for `golang/go` that Pull Requests aren't accepted, I think there is still room for improvement to the automatic response to any PR that might be submitted to the project and related repos managed directly by the Go team. There are several reasons for this, but I would especially highlight the fact that related repositories (e.g.` golang/net`, `golang/blog`) *do not* have the open PR "The Go Project does not use pull requests" as is present in `golang/go`; also, realistically, is everybody (especially if they are well intentioned but relatively inexperienced with GitHub) going to read the contribution guidelines? No, they are not; and yet, they might have something to offer that isn't appropriate for them to go through the Gerrit process (which is even harder to quickly get into that GitHub).

I agree that automatically going from a PR => Gerrit is too much to expect, nor would it be appropriate. The systems are not 1-1. Instead, I propose an in-between solution: PR => New Issue in the repo. In the automatic response generated by the gopher-bot, in addition to the current boilerplate, **politely apologise that the project doesn't use PRs** (*because ultimately it's more important to make people feel glad for trying to help than to risk putting them off)*, inform them about Gerrit, and **offer a link to process their PR into a New Issue** if they would like. Where the issue  template cites the line numbers affected, with the changes in code blocks, the PR comment above, and the PR comment used as the Issue subject header. This prepared New Issue is then left for the user to modify at will and then submit if desired.

**Comment by broady** [comment]
Are you referring to this message? It seems quite polite to me. How would you change it to be more polite?
```
Hi! Thanks for the PR!

However, our project doesn't use GitHub's Pull Requests,
so we can't accept your contribution this way.

We instead use a code review system called Gerrit.
You can find the details in our Contribution Guidelines:
https://golang.org/doc/contribute.html

I'm going to close this Pull Request now.
Please consider sending this change using Gerrit.
```

On automatically creating issues: sounds like a nice idea. If a new issue is being created, then it should just link to the pull request, which includes the diff (not copy/explain the diff in the issue body).

It's not straightforward to simply copy a patch from a diff like that into a gerrit change, since we'd need to ensure the person who contributed it has signed the project's CLA.

**Comment by benjamin-rood** [comment]
Let me put it this way: It’s certainly not rude… but it is also immediately discarding of the work someone put in with kind intentions (it’s best to just assume that)… to the point of being able to be read as dismissive and exasperating.

Imagine if you purely went out of your way to just be helpful, weren’t a super fast programmer, and even something little (to the likes of you guys) actually involved a commitment of someone’s time which they had no motive to do except just to be a decent person, and they felt good about being a nice and helpful. And then, in return for that, what do they get? The effort they put in just got shitcanned. Surely you can see that might be frustrating, and frustration must be one of the a priori reasons for a human being to be rubbed the wrong way, let alone feeling disregarded and your effort immediately dismissed.

My suggestion:

Hi, Gopher-Bot here! Thanks for the PR!

The golang/go project (and its related repositories) don’t use GitHub’s Pull Requests, unfortunately! So we can’t accept your contribution this way.

We instead use a code review system called Gerrit.
You can find the details in our Contribution Guidelines: https://golang.org/doc/contribute.html <https://golang.org/doc/contribute.html>

The good news is that I’ve been sent to help guide your contribution and direct it into an appropriate channel.

We have two options from here: 

We can raise your PR as an issue: I can help convert your PR into a New Issue on the GitHub respository (link)
I can help you getting started with Gerrit: (some text) (links)

I'm going to close this Pull Request now.
If you’re familiar with Gerrit already, please consider sending this change directly: (link to the Gerrit for the appropriate equivalent for the repo the PR was directed for – it’s not unreasonable to provide an autogen link based on the PR)

Thanks,

Gopher-Bot & The Go Team


It never hurts to be extra friendly and helpful. You never know the impression of Go, the Go Team, and Google at large that someone might get from any communication. It’s obvious nobody intended to be anything other than polite with the current response, but I’m living proof that it can be improved. Especially in my case, when I was just pointing out a broken/outdated link to something on Google Store. That had nothing to do with wanting to contribute to any repository, just to aid a massive global corporation to fix something dumb, so that fellow gophers who desperately want their plush toys aren’t let down. I hope, also, that you can see the context of how/why someone might have done something doesn’t always fit into the package or from the approach you might have preconceived. 

Hopefully that helps flesh out my suggestion for ya, thanks for listening.

**Comment by benjamin-rood** [comment]
Let me put it this way: It’s certainly not rude… but it is also immediately discarding of the work someone put in with kind intentions (it’s best to just assume that)… to the point of being able to be read as completely dismissive.

Imagine if you purely went out of your way to just be helpful, weren’t a super fast programmer, and even something little (to the likes of you guys) actually involved a commitment of someone’s time which they had no motive to do except just to be a decent person, and they felt good about being a nice and helpful. And then, in return for that, what do they get? The effort they put in just got shitcanned. Surely you can see that might be *frustrating, and frustration must be one of the* a priori *reasons for a human being to be rubbed the wrong way, let alone feeling disregarded and your effort immediately dismissed.*

My suggestion:

>Hi, Gopher-Bot here! Thanks for the PR!

>The golang/go project (and its related repositories) don’t use GitHub’s Pull Requests, unfortunately! So we can’t accept your contribution this way.

>We instead use a code review system called Gerrit.
>You can find the details in our Contribution Guidelines: https://golang.org/doc/contribute.html <https://golang.org/doc/contribute.html>

>The good news is that I’ve been sent to help guide your contribution and direct it into an appropriate channel.

>We have two options from here: 

>We can raise your PR as an issue: I can help convert your PR into a New Issue on the GitHub repository (link)
>I can help you getting started with Gerrit: (some text) (links)

>I'm going to close this Pull Request now.
>If you’re familiar with Gerrit already, please consider sending this change directly: (link to the Gerrit for the appropriate equivalent for the repo the PR was directed for – it’s not unreasonable to provide an autogen link based on the PR)

>Thanks,

>Gopher-Bot & The Go Team


It never hurts to be extra friendly and helpful. You never know the impression of Go, the Go Team, and Google at large that someone might get from any communication. It’s obvious nobody intended to be anything other than polite with the current response, but I’m living proof that it can be improved. Especially in my case, when I was just pointing out a broken/outdated link to something on **Google Store**. That had nothing to do with wanting to contribute to any repository, just to aid a massive global corporation to fix something dumb, so that fellow gophers who desperately want their plush toys aren’t let down (someone was looking for a working link on the general channel of gophers.slack.com, that's how this all got started). I hope, also, that you can see the context of how/why someone might have done something doesn’t always fit into the package or from the approach you might have preconceived. 

Hopefully that helps flesh out my suggestion for ya, thanks for listening. 

p.s. nobody said go from diff => Gerrit change. In fact, I explicitly said that was too much for anybody to expect.

**Comment by adg** [comment]
@benjamin-rood I just updated the message to be more friendly, as you suggest. Hopefully that will be a more positive experience for first-time contributors.

**Comment by benjamin-rood** [comment]
@adg Wow thanks Andrew, I hope the suggestion was helpful not too preachy.
