### ISSUE TITLE
os/exec: StdoutPipe example fails when run on golang.org

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#13693]
On the [official doc](https://golang.org/pkg/os/exec/), the example under `func (*Cmd) StdoutPipe` fails with error: `2009/11/10 23:00:00 exec: "echo": executable file not found in $PATH` when run.

**Comment by ianlancetaylor** [comment]
What operating system are you using?

**Comment by stevekuznetsov** [comment]
I'm in Fedora 22 but to be clear this is the embedded example in the web page that fails, not me running anything locally.

**Comment by ianlancetaylor** [comment]
Ah, I see.  Yes, none of the os/exec examples will actually work in the limited environment of the Go playground.  We should try to document that somehow.

**Comment by odeke-em** [comment]
I have a few ideas to this
1) We can document this for each example ie
```go
// Note: This example when run in the playground
// will fail because the playground is sandboxed/limited
// so shell utility lookups will fail.
```
2a) Easily detect when we are running on the playground like this
```go
import "runtime"

func execPathsUnavailable() bool {
     // Shell lookups and utilities are
     // unavailable on the playground running nacl
     return runtime.GOOS == "nacl"
}
```
2b) A little more complex:
  - Use the execPathsUnavailable() when extracting each example in exec/ detect and inject that comment before the body of each example.

Please let me know what you think would be a better option. Thanks.

**Comment by minux** [comment]
os/exec is unavailable in nacl, we could just make
the error from os/exec better on nacl.

**Comment by stevekuznetsov** [comment]
Could the 'run' be removed or disabled?

**Comment by bradfitz** [comment]
@stevekuznetsov, yes, that's probably the right answer.

If we don't want to invent new annotation syntax, we could even just have a blacklist of code samples in hard-coded in cmd/godoc. If an example is on the blacklist then it'd get to Run button.

**Comment by minux** [comment]
We just need to blacklist the os/exec package to start with.

**Comment by rsc** [comment]
If you're running your own godoc then the example runs fine, right?
