### ISSUE TITLE
misc/cgo/testcarchive: test4 fails on darwin/{arm,arm64}

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#13701]
From http://build.golang.org/log/bdb16ad9a65cab92ea0c49f86bc7967ca3f3cd94:

(lldb) process continue
Process 808 resuming
(lldb) Process 808 stopped
* thread #1: tid = 0x4d91, 0x0000bbd8 gotest`main + 764, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000bbd8 gotest`main + 764
gotest`main:
->  0xbbd8 <+764>: strb   r2, [r3]
    0xbbdc <+768>: ldr    r0, [r0]
    0xbbe0 <+772>: bl     0x13ff80                  ; symbol stub for: fprintf
    0xbbe4 <+776>: movw   r1, #0x1
go_darwin_arm_exec: command timeout (test completion for 1s)
FAIL test4
2015/12/18 20:21:11 Failed: exit status 1

This is the code in misc/cgo/testcarchive/main2.c that does this:

		if (verbose) {
			printf("triggering SIGSEGV\n");
		}

		*nullPointer = '\0';

Is is intended to trigger a SIGSEGV, but instead on darwin/{arm,arm64} it triggers a EXC_BAD_ACCESS.

**Comment by minux** [comment]
Note that it's a long term issue for lldb:
it just can't translate the Mach exception
EXC_BAD_ACCESS into BSD signal
SIGSEGV.

**Comment by ianlancetaylor** [comment]
Ah, in that case maybe we should treat CL 18090 as an actual fix.
