### ISSUE TITLE
net: don't attempt DNS on .onion addresses

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13705]
(Now that .onion addresses are an official TLD) 

RFC7686 says:

> Applications (including proxies) that implement the Tor protocol MUST recognize .onion names as special by either accessing them directly or using a proxy (e.g., SOCKS [RFC1928]) to do so.  Applications that do not implement the Tor protocol SHOULD generate an error upon the use of .onion and SHOULD NOT perform a DNS lookup.

See https://lists.w3.org/Archives/Public/ietf-http-wg/2015OctDec/0222.html and

https://bugzilla.mozilla.org/show_bug.cgi?id=1228457
https://code.google.com/p/chromium/issues/detail?id=562265
https://github.com/bagder/curl/issues/543

**Comment by mikioh** [comment]
And ".local." too, as per RFC 6762.

The discussion goes on at IAB/IESG like https://tools.ietf.org/html/draft-adpkja-dnsop-special-names-problem and https://www.icann.org/news/announcement-2-2015-11-30-en. Hope the consensus will be landed safely.
