### ISSUE TITLE
x/mobile: is it possible to define an interface on golang and implement it in the foreign language?

### ISSUE THREAD

**Issue by dcu** [golang/go#13709]
And then pass an instance back to Go.
What I want is defining how a storage engine should look and allowing to implement the storage engine in iOS, so it can make use of the Keychain and User Defaults, for example.

**Comment by rakyll** [comment]
Please ask usage related questions at the golang-nuts related mailing list: https://groups.google.com/forum/#!forum/golang-nuts

The issue tracker is for filing bugs and discussing proposals.
