### ISSUE TITLE
/usr/lib/go/pkg/tool/linux_arm/link multiple definition

### ISSUE THREAD

**Issue by tsuibin** [golang/go#13716]
root@compiler01:~/src/dde-api/dde-api-2.92.4# make
env GOPATH="/usr/share/gocode:/root/src/dde-api/dde-api-2.92.4/gobuild" go build -x -v -work -o out/bin/thumbnailer  pkg.deepin.io/dde/api/thumbnailer
WORK=/tmp/go-build171728570
pkg.deepin.io/dde/api/thumbnailer
mkdir -p $WORK/pkg.deepin.io/dde/api/thumbnailer/_obj/
mkdir -p $WORK/pkg.deepin.io/dde/api/thumbnailer/_obj/exe/
cd /usr/share/gocode/src/pkg.deepin.io/dde/api/thumbnailer
/usr/lib/go/pkg/tool/linux_arm/compile -o $WORK/pkg.deepin.io/dde/api/thumbnailer.a -trimpath $WORK -p main -complete -buildid 1871a2b4fd6a706c6779754a63eb580e0f4f6269 -D _/usr/share/gocode/src/pkg.deepin.io/dde/api/thumbnailer -I $WORK -I /usr/share/gocode/pkg/linux_arm -pack ./main.go
cd .
/usr/lib/go/pkg/tool/linux_arm/link -o $WORK/pkg.deepin.io/dde/api/thumbnailer/_obj/exe/a.out -L $WORK -L /usr/share/gocode/pkg/linux_arm -extld=gcc -buildmode=exe -buildid=1871a2b4fd6a706c6779754a63eb580e0f4f6269 $WORK/pkg.deepin.io/dde/api/thumbnailer.a
# pkg.deepin.io/dde/api/thumbnailer
/usr/lib/go/pkg/tool/linux_arm/link: running gcc failed: exit status 1
/tmp/go-link-313243301/000004.o: In function `__aeabi_d2iz':
_arm_fixdfsi.o:(.text+0x248): multiple definition of `__fixdfsi'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x19fc): first defined here
/tmp/go-link-313243301/000004.o: In function `__aeabi_d2iz':
_arm_fixdfsi.o:(.text+0x248): multiple definition of `__aeabi_d2iz'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x19fc): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_l2d':
_arm_addsubdf3.o:(.text+0x688): multiple definition of `__floatdidf'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x13bc): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_i2d':
_arm_addsubdf3.o:(.text+0x60c): multiple definition of `__floatsidf'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1340): first defined here
/tmp/go-link-313243301/000005.o: In function `__floatunsidf':
_arm_addsubdf3.o:(.text+0x5e8): multiple definition of `__aeabi_ui2d'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x131c): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_drsub':
_arm_addsubdf3.o:(.text+0x2cc): multiple definition of `__aeabi_drsub'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1000): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_f2d':
_arm_addsubdf3.o:(.text+0x634): multiple definition of `__extendsfdf2'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1368): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_dadd':
_arm_addsubdf3.o:(.text+0x2d8): multiple definition of `__adddf3'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x100c): first defined here
/tmp/go-link-313243301/000005.o: In function `__floatunsidf':
_arm_addsubdf3.o:(.text+0x5e8): multiple definition of `__floatunsidf'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x131c): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_dadd':
_arm_addsubdf3.o:(.text+0x2d8): multiple definition of `__aeabi_dadd'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x100c): first defined here
/tmp/go-link-313243301/000005.o: In function `__floatundidf':
_arm_addsubdf3.o:(.text+0x674): multiple definition of `__aeabi_ul2d'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x13a8): first defined here
/tmp/go-link-313243301/000005.o: In function `__subdf3':
_arm_addsubdf3.o:(.text+0x2d4): multiple definition of `__aeabi_dsub'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1008): first defined here
/tmp/go-link-313243301/000005.o: In function `__floatundidf':
_arm_addsubdf3.o:(.text+0x674): multiple definition of `__floatundidf'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x13a8): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_i2d':
_arm_addsubdf3.o:(.text+0x60c): multiple definition of `__aeabi_i2d'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1340): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_l2d':
_arm_addsubdf3.o:(.text+0x688): multiple definition of `__aeabi_l2d'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x13bc): first defined here
/tmp/go-link-313243301/000005.o: In function `__aeabi_f2d':
_arm_addsubdf3.o:(.text+0x634): multiple definition of `__aeabi_f2d'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1368): first defined here
/tmp/go-link-313243301/000005.o: In function `__subdf3':
_arm_addsubdf3.o:(.text+0x2d4): multiple definition of `__subdf3'
/tmp/go-link-313243301/000001.o:_arm_fixdfsi.o:(.text+0x1008): first defined here
collect2: error: ld returned 1 exit status

Makefile:46: recipe for target 'out/bin/thumbnailer' failed
make: *** [out/bin/thumbnailer] Error 2

**Comment by ianlancetaylor** [comment]
Dup of #9510 which is fixed on tip.  If you are using tip (you didn't say what version you are using), please reopen.
