### ISSUE TITLE
math/rand: randFloat64() gives the same result irrespective of the number of times run

### ISSUE THREAD

**Issue by odeke-em** [golang/go#13718]
In the docs at https://golang.org/pkg/math/rand/#Float64, it says
<img width="945" alt="screen shot 2015-12-23 at 5 24 18 am" src="https://cloud.githubusercontent.com/assets/4898263/11976449/7b1ece54-a935-11e5-9f8f-cf4a28fcdd98.png">

However, I ran tests on both the playground http://play.golang.org/p/oK5GR_9Z_N and my computer
and it always gave me the same result 0.6046602879796196 no matter how many times I ran this. I found this out when testing out a program that simulates different sleep times to simulate contention for resources.

My test was:
```shell
$ cat randTest.go
package main

import (
	"log"
	"math/rand"
)

func main() {
	log.Println(rand.Float64())
}
```

```shell
$ go version >> randResult.txt && for i in $(seq 1 100); do sleep 0.25;go run randTest.go 2>> randResult.txt;done;cat randResult.txt | cut -d" " -f3 | sort | uniq
0.6046602879796196
devel
```

And from the playground
<img width="951" alt="screen shot 2015-12-23 at 5 32 13 am" src="https://cloud.githubusercontent.com/assets/4898263/11976566/92c636a4-a936-11e5-8d7e-bca296f4c689.png">

That is the exact same result I got from nacl and darwin.

**Comment by odeke-em** [comment]
Never mind: false alarm, just luck of sleep got me not to realize that since we use the same source all the time, the results are always deterministic.

**Comment by odeke-em** [comment]
I was just too used to rand* producing at least pseudo random starting values that weren't the same everytime
<img width="586" alt="screen shot 2015-12-23 at 5 56 10 am" src="https://cloud.githubusercontent.com/assets/4898263/11976884/ecd377f8-a939-11e5-85a9-2638b2db613d.png">

**Comment by cespare** [comment]
From the package docs: "Top-level functions, such as Float64 and Int, use a
default shared Source that produces a deterministic sequence of values each
time a program is run. Use the Seed function to initialize the default
Source if different behavior is required for each run."
