### ISSUE TITLE
x/text/encoding: ShfitJIS doesn't handle cp932

### ISSUE THREAD

**Issue by mattn** [golang/go#13727]
text/encoding/japanese.ShiftJIS explain it can handle cp932 in doc.
https://github.com/golang/text/blob/master/encoding/japanese/shiftjis.go#L17-L18

But below's code doesn't work because the range of lead-byte is range of ShiftJIS not cp932.

```go
package main

import (
	"golang.org/x/text/encoding/japanese"
	"golang.org/x/text/transform"
	"log"
)

func main() {
	// 髙(FBFC)
	s, _, err := transform.String(japanese.ShiftJIS.NewDecoder(), "\xFB\xFC")
	if err != nil {
		log.Fatal(err.Error())
	}
	log.Print(s)
	// 﨑(FAB1)
	s, _, err = transform.String(japanese.ShiftJIS.NewDecoder(), "\xFA\xB1")
	if err != nil {
		log.Fatal(err.Error())
	}
	log.Print(s)
}
```

**Comment by mattn** [comment]
I'm thinking this should be contained in 1.6 .

**Comment by minux** [comment]
This is about a package in a subrepo, and subrepos aren't
tied to a particular Go release, hence the Unreleased label.

**Comment by mattn** [comment]
@minux ah, fair enough. thank you.
