### ISSUE TITLE
exp/inotify: can leak goroutine

### ISSUE THREAD

**Issue by nsd20463** [golang/go#13723]
The readEvents() goroutine blocks when it writes an Event to w.Event chan.
If at the same time the calling code Close()s the watcher, and the calling code doesn't then drain w.Event (which no example code does), the readEvents() goroutine is stuck.

**Comment by nsd20463** [comment]
See
  https://golang.org/cl/7463043
for one possible fix.

**Comment by rsc** [comment]
Deleted this code instead. See github.com/fsnotify for more maintained code.
