### ISSUE TITLE
cgo: C.uchar array or pointer cannot be assigned to uint8 array or pointer

### ISSUE THREAD

**Issue by bits01** [golang/go#13729]
```go
package main

import "C"

import "fmt"

func main() {
	var cp *C.uchar
	var gop *uint8 = cp
	fmt.Println(gop)

	var carr [1]C.uchar
	var goarr [1]uint8 = carr
	fmt.Println(goarr)
}
```

Trying to run it:

./main.go:9: cannot use cp (type *C.unsignedchar) as type *uint8 in assignment
./main.go:13: cannot use carr (type [1]C.unsignedchar) as type [1]uint8 in assignment

If I run `go tool cgo -godefs` it generates a Go file that looks and runs fine:

```go
...
func main() {
        var cp *uint8
        var gop *uint8 = cp
        fmt.Println(gop)

        var carr [1]uint8
        var goarr [1]uint8 = carr
        fmt.Println(goarr)
}
```

Not sure whether this is the same issue as #13635 that I also reported a few days ago and has been fixed.

Is it possible to land a fix for the above in 1.5.x please?

**Comment by minux** [comment]
This is working as intended.

uint8 and C.uchar are not the same type,
according to the Go rules.

You can think of C.uchar as
type C.uchar uint8

Because it's a named type whose underlying type is uint8,
the type is different from uint8.

As an example, even this won't compile for the same reason:

   var c1 C.uchar
   var c2 uint8 = c1

**Comment by bits01** [comment]
I see. I was under the impression that C.uchar works more like the pre-defined byte alias for uint8. Thank you. What confused me was the generated go file when using `cgo -godefs`

**Comment by minux** [comment]
cgo -godefs output is not the file generated for cgo,
it's used to generate various structs/consts that are
equivalent to existing C interface for the syscall and
runtime package.

The cmd/cgo help message made that clear:
  -godefs
    for bootstrap: write Go definitions for C file to standard output

It's only intended to use when bootstrapping Go on
a new platform.

**Comment by bits01** [comment]
Thanks for clarifying. I think somewhere in the group or in some post someone recommended to look at the output of cgo -godefs. Lots of conflicting and sometimes misleading info out there.

**Comment by bits01** [comment]
I may have taken what you posted here out of context, sorry.
http://grokbase.com/t/gg/golang-nuts/12cemmrhk5/go-nuts-cgo-cast-c-struct-to-go-struct
