### ISSUE TITLE
crypto/dsa: tweak GenerateParameters timing doc

### ISSUE THREAD

**Issue by ahmetalpbalkan** [golang/go#13725]
```
    53	// GenerateParameters puts a random, valid set of DSA parameters into params.
    54	// This function takes many seconds, even on fast machines.
    55	func GenerateParameters(params *Parameters, rand io.Reader, sizes ParameterSizes) (err error) {
```

I find the "This function takes many seconds" part confusing because if `sizes`  is chosen to be `dsa.L1024N160` it takes ≤0.5 on my machine (which is not “many seconds” IMHO).

I had to try out more complex sizes such as `dsa.L3072N256` to make sure there's nothing wrong with my code being that fast (that one took >4s).

I'm not sure how the wording can be fixed here, maybe it's not wrong after all. It might be my English that's wrong, but I think 0.5 seconds is not many seconds.

Introduced here: https://github.com/golang/go/blame/220a6de47eced55956eb8af8d643d4f5b67fd634/src/pkg/crypto/dsa/dsa.go#L54 by @agl.

**Comment by rsc** [comment]
s/takes many/can take many/
