### ISSUE TITLE
type as a argument

### ISSUE THREAD

**Issue by liuliuhit** [golang/go#13726]
in effective go:

You can't actually write a function in Go where the type T is determined by the caller. That's why append is built in: it needs support from the compiler.

if I want to pass a type as argument,i use the client passing MyType T as argument, and the server return is interface.(*MyType). because I am the caller, and i know the real type, so I only want server return a entity which type is MyType

**Comment by minux** [comment]
Sorry, I don't understand.

If you are asking a question, please see
https://golang.org/wiki/Questions. Thanks.
