### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by runner-mei** [golang/go#13728]
fatal error: out of memory

runtime stack:
runtime.throw(0x7b2190, 0xd)
        c:/go/src/runtime/panic.go:530 +0x7f
runtime.(*mcache).refill(0x2d0000, 0xe, 0x10f8a180)
        c:/go/src/runtime/mcache.go:121 +0xce
runtime.mallocgc.func2()
        c:/go/src/runtime/malloc.go:638 +0x2b
runtime.systemstack(0xbea3a0)
        c:/go/src/runtime/asm_386.s:313 +0x5e
runtime.mstart()
        c:/go/src/runtime/proc.go:1042

goroutine 1 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:267 fp=0x5092ed64 sp=0x5092ed60
runtime.mallocgc(0xd0, 0x78a280, 0x0, 0xbe772af)
        c:/go/src/runtime/malloc.go:639 +0x6ca fp=0x5092edd0 sp=0x5092ed64
runtime.newobject(0x78a280, 0x0)
        c:/go/src/runtime/malloc.go:777 +0x41 fp=0x5092ede4 sp=0x5092edd0
cmd/compile/internal/gc.Prog(0x307e, 0x6200c180)
        c:/go/src/cmd/compile/internal/gc/gsubr.go:117 +0x4f fp=0x5092ee18 sp=0x
5092ede4
cmd/compile/internal/x86.gins(0x307e, 0x6200d3e0, 0x6200c180, 0x62007e10)
        c:/go/src/cmd/compile/internal/x86/gsubr.go:1785 +0x243 fp=0x5092ee88 sp
=0x5092ee18
cmd/compile/internal/x86.gmove(0x6200d3e0, 0x6200c180)
        c:/go/src/cmd/compile/internal/x86/gsubr.go:1066 +0x40b fp=0x5092ef40 sp
=0x5092ee88
cmd/compile/internal/x86.gmove(0x6200d380, 0x6200c180)
        c:/go/src/cmd/compile/internal/x86/gsubr.go:1094 +0x31a fp=0x5092eff8 sp
=0x5092ef40
cmd/compile/internal/gc.cgen_wb(0x6200d380, 0x6200c180, 0x794900)
        c:/go/src/cmd/compile/internal/gc/cgen.go:251 +0x3c75 fp=0x5092f208 sp=0
x5092eff8
cmd/compile/internal/gc.Cgen_as_wb(0x6200c180, 0x6200d380, 0x6200d300)
        c:/go/src/cmd/compile/internal/gc/gen.go:932 +0x138 fp=0x5092f238 sp=0x5
092f208
cmd/compile/internal/gc.Cgen_as(0x6200c180, 0x6200d380)
        c:/go/src/cmd/compile/internal/gc/gen.go:883 +0x2e fp=0x5092f248 sp=0x50
92f238
cmd/compile/internal/gc.cgen_callret(0x6200c600, 0x6200c180)
        c:/go/src/cmd/compile/internal/gc/cgen.go:2579 +0x118 fp=0x5092f274 sp=0
x5092f248
cmd/compile/internal/gc.cgen_wb(0x6200c600, 0x6200c180, 0x794900)
        c:/go/src/cmd/compile/internal/gc/cgen.go:654 +0x2160 fp=0x5092f484 sp=0
x5092f274
cmd/compile/internal/gc.Cgen_as_wb(0x6200c180, 0x6200c600, 0x0)
        c:/go/src/cmd/compile/internal/gc/gen.go:932 +0x138 fp=0x5092f4b4 sp=0x5
092f484
cmd/compile/internal/gc.Cgen_as(0x6200c180, 0x6200c600)
        c:/go/src/cmd/compile/internal/gc/gen.go:883 +0x2e fp=0x5092f4c4 sp=0x50
92f4b4
cmd/compile/internal/gc.gen(0x6200ca20)
        c:/go/src/cmd/compile/internal/gc/gen.go:833 +0x17b fp=0x5092f574 sp=0x5
092f4c4
cmd/compile/internal/gc.Genlist(0x61ffa400)
        c:/go/src/cmd/compile/internal/gc/gen.go:215 +0x2d fp=0x5092f57c sp=0x50
92f574
cmd/compile/internal/gc.compile(0x61ffdf20)
        c:/go/src/cmd/compile/internal/gc/pgen.go:476 +0xa61 fp=0x5092f6b8 sp=0x
5092f57c
cmd/compile/internal/gc.funccompile(0x61ffdf20)
        c:/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x198 fp=0x5092f6f4 sp=0x
5092f6b8
cmd/compile/internal/gc.genhash(0x62008380, 0x15978c60)
        c:/go/src/cmd/compile/internal/gc/subr.go:2639 +0xa32 fp=0x5092f818 sp=0
x5092f6f4
cmd/compile/internal/gc.dalgsym(0x15978c60, 0xffffffff)
        c:/go/src/cmd/compile/internal/gc/reflect.go:1342 +0x1203 fp=0x5092f924
sp=0x5092f818
cmd/compile/internal/gc.dcommontype(0x42b16e40, 0x0, 0x15978c60, 0x2d0000)
        c:/go/src/cmd/compile/internal/gc/reflect.go:701 +0x764 fp=0x5092f9e4 sp
=0x5092f924
cmd/compile/internal/gc.dtypesym(0x15978c60, 0x206ab540)
        c:/go/src/cmd/compile/internal/gc/reflect.go:1167 +0xb28 fp=0x5092fab8 s
p=0x5092f9e4
cmd/compile/internal/gc.dtypesym(0x15978fc0, 0x206ab1c0)
        c:/go/src/cmd/compile/internal/gc/reflect.go:1151 +0x3ff fp=0x5092fb8c s
p=0x5092fab8
cmd/compile/internal/gc.dumptypestructs()
        c:/go/src/cmd/compile/internal/gc/reflect.go:1250 +0x40f fp=0x5092fbec s
p=0x5092fb8c
cmd/compile/internal/gc.dumpobj()
        c:/go/src/cmd/compile/internal/gc/obj.go:76 +0xb6c fp=0x5092fd14 sp=0x50
92fbec
cmd/compile/internal/gc.Main()
        c:/go/src/cmd/compile/internal/gc/lex.go:495 +0x1ce0 fp=0x5092fea8 sp=0x
5092fd14
cmd/compile/internal/x86.Main()
        c:/go/src/cmd/compile/internal/x86/galign.go:108 +0x53e fp=0x5092ff14 sp
=0x5092fea8
main.main()
        c:/go/src/cmd/compile/main.go:30 +0x117 fp=0x5092ff80 sp=0x5092ff14
runtime.main()
        c:/go/src/runtime/proc.go:185 +0x234 fp=0x5092ffa8 sp=0x5092ff80
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1583 +0x1 fp=0x5092ffac sp=0x5092ffa8

**Comment by minux** [comment]
Please provide more details.

Which version of Go?
How much RAM does the machine have?
What program are you compiling?

Note that you're running 32-bit version of Go, so
it's quite possible that it's legitimately out of memory.

**Comment by runner-mei** [comment]
it is go1.5.x_386 or go1.6_386_beta1.

go1.4.2 is ok

**Comment by minux** [comment]
What program are you trying to compile?

**Comment by runner-mei** [comment]
The program is private.
I move some files to another package and this is ok.
