### ISSUE TITLE
tour: Wrong comment

### ISSUE THREAD

**Issue by Thermi** [golang/go#13736]
Context: https://tour.golang.org/moretypes/1

```
*p = *p / 37   // divide j through the pointer
```
That's not true. That code divides j by 37. 37 is not the pointer.

**Comment by cespare** [comment]
It doesn't say "divide j by the pointer", it says "divide j **through** the pointer" -- that is, divide j by accessing it through the pointer. Seems fine to me.

**Comment by dominikh** [comment]
Maybe s/divide/access ?

**Comment by rsc** [comment]
I think it's fine. It doesn't say "by the pointer". It says "through the pointer". At least in English, we would never say "divide j through 37".
