### ISSUE TITLE
runtime: decide if we should mention cl 17164 change in go1.6.html

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#13731]
From the change:
```
runtime: do not call timeBeginPeriod on windows
Calling timeBeginPeriod changes Windows global timer resolution
from 15ms to 1ms. This used to improve Go runtime scheduler
performance, but not anymore. Thanks to @aclements, scheduler now
behaves the same way if we call timeBeginPeriod or not.

Remove call to timeBeginPeriod, since it is machine global
resource, and there are downsides of using low timer resolution.
See issue #8687 for details.

Fixes #8687
```

Some users might be affected - whoever prefer time.Sleep(time.Nanosecond) to sleep for 1ms, instead of 15ms. I would rather our users use Windows system as is, but, I suspect, sometimes it is important.

Leaving for others to decide what to do / say here. Thank you.

Alex

**Comment by minux** [comment]
I suggest we err on the safe side and document this caveat.

**Comment by rsc** [comment]
On Windows 10 is it still the case that without this call time.Sleep(time.Nanosecond) sleeps for 15 ms?

Operating systems have been moving to so-called high-precision timers that can sleep for smaller amounts of time even if the system clock is set to a relatively high period. Obviously it's not going to do 1ns, but I wouldn't be surprised if it were well under 1ms.

**Comment by alexbrainman** [comment]
> On Windows 10 is it still the case that without this call time.Sleep(time.Nanosecond) sleeps for 15 ms?

This https://play.golang.org/p/wLOU7Ah_g7 program prints:
```
C:\>u:\test
[15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms 15.6252ms]

C:\>
```
on both my Windows XP 32-bit and Windows 7 64-bit. I don't have Windows 10. But, I believe, @mattn has. @mattn, would you be kind to run program above on your Windows 10? Thank you.

Alex

**Comment by mattn** [comment]
@alexbrainman I can try this tonight. I'll look into it.

FYI, below is a result on windows7 64bit.
```
C:\dev>go run tim.go
[1.0001ms 1.0001ms 1.0001ms 1.0001ms 1.0001ms 1.0001ms 1.0001ms 1.0001ms 1.0001m
s 1.0001ms]
```

**Comment by alexbrainman** [comment]
> below is a result on windows7 64bit.

This is strange. I would expect you to display many 15.6252ms (just like my computer). But it is possible that other program (not built by go1.6) is called timeBeginPeriod and is still runinng. This will make your PC timer run at 1ms. Until last program that called timeBeginPeriod exits. See https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/ for details.

Alex

**Comment by mattn** [comment]
Ah, sorry. I must pull the commits in 2 hours ago.

**Comment by mattn** [comment]
hmm, still 1ms.

![](http://go-gyazo.appspot.com/5fa62ac3604f1697.png)

**Comment by mattn** [comment]
here is a result on windows10 64bit.

![](https://i.gyazo.com/f7da38a01040786bd8e00b8614250c6f.png)
