### ISSUE TITLE
remote error: handshake failure

### ISSUE THREAD

**Issue by webluoye** [golang/go#13733]
#### What version of Go are you using (go version)?
   go version go1.5.2 linux/amd64
#### What operating system and processor architecture are you using?
   CentOS release 5.5 (Final)
#### What did you do?
	cert, err := tls.LoadX509KeyPair(eppConfig.crt, eppConfig.key)
	tlsConfig = tls.Config{Certificates: []tls.Certificate{cert}, ClientAuth: tls.VerifyClientCertIfGiven, InsecureSkipVerify: true}
	ladd, lerr := net.ResolveTCPAddr("tcp", eppConfig.clientIp+":0")
	radd, rerr := net.ResolveTCPAddr("tcp", eppConfig.server+":"+eppConfig.port)
        ipConn, err := net.DialTCP("tcp", ladd, radd)
        conn = tls.Client(ipConn, tlsconfig)
        errObj = conn.Handshake()//remote error: handshake failure
#### What did you see instead?
 use openssl test ok,use nodejs test ok
 openssl s_client -connect epp.gtld.knet.cn:700 -cert pem.crt -key pem.key -state

SSL handshake has read 2307 bytes and written 1014 bytes

New, TLSv1/SSLv3, Cipher is EDH-DSS-DES-CBC3-SHA
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : EDH-DSS-DES-CBC3-SHA
    Session-ID: 567E4892317865E04D4FAF16095DD5B04E926639EF9E0A61E76502A1EE5208B7
    Session-ID-ctx:
    Master-Key: 9741F320B81F5D443082C9B83E68405154921EA399B5BD2DBDC1E2B9BEBC3C1B614BBBB135F40C65B59F0E859A102E6E
    Key-Arg   : None
    Krb5 Principal: None
    Start Time: 1451116690
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
`---
<?xml version="1.0" encoding="UTF-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"><greeting><svID>KNET Co.,Ltd. EPP Server</svID><svDate>2015-12-26T07:58:10.528Z</svDate><svcMenu><version>1.0</version><lang>en</lang><objURI>urn:ietf:params:xml:ns:domain-1.0</objURI><objURI>urn:ietf:params:xml:ns:host-1.0</objURI><objURI>urn:ietf:params:xml:ns:contact-1.0</objURI><svcExtension><extURI>urn:ietf:params:xml:ns:secDNS-1.1</extURI><extURI>urn:ietf:params:xml:ns:launch-1.0</extURI><extURI>urn:ietf:params:xml:ns:idn-1.0</extURI><extURI>urn:ietf:params:xml:ns:rgp-1.0</extURI></svcExtension></svcMenu><dcp><access><all/></access><statement><purpose><admin/><prov/></purpose><recipient><ours/><public/></recipient><retention><stated/></retention></statement></dcp></greeting></epp>

**Comment by davecheney** [comment]
Please take your question to the mailing list. The issue tracker is only for bugs. Also, centos versions less than 6 are not supported by any version of Go.
