### ISSUE TITLE
cmd/godoc: make it easier to get anchor links

### ISSUE THREAD

**Issue by cespare** [golang/go#13748]
godoc's generated HTML includes lots of handy anchor tags for every element of the documentation. If you wish to look up a tag in order to link to a particular section, it's not always easy to get at the tag.

For types, functions, and methods, you can scroll up and find the corresponding index entry and click on that. For subsections of the overview section (e.g. https://golang.org/pkg/text/template/#hdr-Arguments), the link doesn't appear anywhere on the page that I can see. (I usually right click > Inspect in Chrome.)

To make these easier, it would be nice if go/doc's HTML output included a small link beside every anchored element. For one example of how this might look, Github renders markdown with a little anchor link beside each section that only appears on hover. (See https://github.com/golang/go#binary-distribution-notes and hover over "Binary Distribution Notes".)

Another, smaller change that would help is if subsections of the Overview were listed in the index at the very top of the page.

**Comment by bradfitz** [comment]
Assigning to @adg to review the outstanding CL. Sorry for the slow review.
