### ISSUE TITLE
x/mobile/cmd/gobind: building error

### ISSUE THREAD

**Issue by star-tek-mb** [golang/go#13740]
There is a error in binding and building go package from AndroidStudio.
Message error:
~~~
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:hello:gobind
/home/startek/go/bin/gomobile: 'go version' failed: exit status 2, go: cannot find GOROOT directory: /usr/local/go
Error:Execution failed for task ':hello:gobind'.
> Process 'command '/home/startek/go/bin/gomobile'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 5.644 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
~~~

General message - GOROOT not found. I installed go to custom folder. GOROOT, GOBIN, GOPATH variables are setted. AndroidStudio dont understand global variables. My decision - Settings -> Build, Execution, Deployment -> Path Variables -> Add new variable - GOROOT - /home/startek/go. But this trick not work.

When I build from console:
~~~bash
./gradlew assembleDebug
~~~
Its OK.

Maybe, there is a fix for gobind plugin. I use gobind 0.2.3.

**Comment by crawshaw** [comment]
In your standard shell environment, are you setting GOROOT?

Typical advice around here is never set GOROOT. If you've taken the binary distribution from golang.org which expects to be installed in /usr/local/go and put it somewhere else, unset GOROOT and run make.bash.
