### ISSUE TITLE
cmd/godoc: missing some functions when using dot imports

### ISSUE THREAD

**Issue by nodirt** [golang/go#13742]
Given

```go

package x

import . "y"

// assume Y is defined in package y.

func F(Y) {}

func G() Y {
  return nil
}
```

godoc will display`F`, but not `G`.

Repro: https://godoc.org/github.com/nodirt/tmp/godoc-bug should display function [`X`](https://github.com/nodirt/tmp/blob/master/godoc-bug/a.go#L8).

**Comment by rsc** [comment]
Is this really about go/doc (the package)? It doesn't look like it.

**Comment by nodirt** [comment]
FWIU, the root cause lies somewhere under https://godoc.org/go/doc#New

**Comment by griesemer** [comment]
This is indeed an issue with go/doc.
