### ISSUE TITLE
GOVENDOR15EXPERIMENT "internal" package issue

### ISSUE THREAD

**Issue by ruseinov** [golang/go#13755]
So basically the problem is as follows: if you have any package vendored that has a sub-package "internal" compiling/running/testing result in an error, that states that package name "internal" could not be used. That breaks compatibility with the libraries that have such a package-name.

An example of such library would be https://github.com/garyburd/redigo .

The go version is 1.5.2.

**Comment by rsc** [comment]
This bug report is incomplete. It needs to answer:

- What did you do?
- What happened?
- What did you expect to happen instead?

I tried to guess by running "go get github.com/garyburd/redigo/redis" (suggested at linked project page) but that worked fine.

**Comment by ruseinov** [comment]
@rsc 
What I did is I had a project with  this library as a dependency in vendor folder
Tried running tests, expected them to complete, instead got an error prior to compilation, which stated that "internal" package name is something I can't use.

**Comment by rsc** [comment]
To fix this, I need to be able to reproduce it. I cannot reproduce it from your description. At the least I would need to know the full path to the source file containing the bad import and the full text of the source line containing the bad import.

**Comment by ruseinov** [comment]
Alright Russ, I will reproduce that tomorrow and send you a step by step
guide for it.

Thanks,
Roman

**Comment by ruseinov** [comment]
@rsc Hello Russ,

So I guess I've identified the issue incorrectly, you can checkout this repo: https://github.com/ruseinov/gofail

and then run `GO15VENDOREXPERIMENT=1 go test ./...` which would also run all the tests in vendor directory.

And that would throw: 
```
package test
	imports github.com/garyburd/redigo/internal: use of internal package not allowed
```

**Comment by alkchr** [comment]
@ruseinov Your issue is not related to `GO15VENDOREXPERIMENT`. You are not allowed to import [`internal` package](https://github.com/ruseinov/gofail/blob/master/main.go#L4) (or its subpackages) of a third party repo. Read more about **Go 1.4 "Internal" Packages** [here](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit#).

**Comment by ruseinov** [comment]
@alkchr So that basically means that if I try to execute tests within the vendor folder on an "internal" package they would always fail.

That's fair enough.

I'm going to close the issue then.

**Comment by kostya-sh** [comment]
There are no tests in https://github.com/ruseinov/gofail as far as I can tell.

**Comment by alkchr** [comment]
> So that basically means that if I try to execute tests within the vendor folder on an "internal" package they would always fail.

@ruseinov Not really. Open your [`vendor/github.com/garyburd/redigo/internal` directory](https://github.com/ruseinov/gofail/tree/master/vendor/github.com/garyburd/redigo/internal) and compare it to the original [`internal` directory](https://github.com/garyburd/redigo/tree/master/internal) of the "redigo" repo. Something is missing, right?

Apparently, that is a bug of **govendor** that you've used (it didn't copy all files it had to). Try to install `go get -u github.com/FiloSottile/gvt` and start `gvt fetch github.com/garyburd/redigo` from your `$GOPATH/src/github.com/ruseinov/gofail`. Then start `go test ./...` again. It should work as expected.

**Comment by ruseinov** [comment]
@alkchr Thanks for clarification, I didn't think to look into that.
