### ISSUE TITLE
encoding/xml: incorrect EOF behavior in (*Decoder).Token

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13757]
The docstring for `(*Decoder).Token` says "At the end of the input stream, Token returns nil, io.EOF", but when this program

   http://play.golang.org/p/8pqgfMmPuU

is run using a tip (not Go 1.5) distribution, the resulting error is an `*xml.SyntaxError`.

This bug is causing the `golang.org/x/tools/go/vcs` tests to fail.

**Comment by shurcooL** [comment]
> This bug is causing the `golang.org/x/tools/go/vcs` tests to fail.

This part has been resolved independently (by resolving #13683 and applying that to x/tools/go/vcs in https://golang.org/cl/18196).

But the rest mentioned here (`(*Decoder).Token` documentation and behavior not matching) is still a valid (and unrelated) issue, right?

**Comment by alandonovan** [comment]
Yes.

**Comment by bradfitz** [comment]
Regression from Go 1.5.

**Comment by jhawk28** [comment]
The change to Token was made by this commit: https://github.com/golang/go/commit/bf2164390bd499145fc712194bb54290effd7e14

It may just need a documentation update.

**Comment by rsc** [comment]
Working as intended. CL 18854. Already mentioned in http://tip.golang.org/doc/go1.6. Note that "<foo>" is not a well-formed XML document: it is missing the "</foo>".
