### ISSUE TITLE
Dynamic shared libraries loading

### ISSUE THREAD

**Issue by 39dotyt** [golang/go#13751]
I understand, that this issue/question may be a duplicate. If so, please, remove it.

Will there be support for dynamic libraries loading in Go?

Regards.

**Comment by minux** [comment]
You can load dynamic library with Go today using cgo (dlopen and the like)
and syscall on Windows.

The missing part is loading Go dynamic library, aka plugins.

**Comment by 39dotyt** [comment]
I know this.

My question is about Go dynamic libraries. Will 1.6 support Go plugins?

**Comment by davecheney** [comment]
No, go 1.6 will not support Go plugins. Nobody has comitted to doing that work.

**Comment by 39dotyt** [comment]
@davecheney 

What is required to add support of Go plugins? May I work on plugins support?

I have read this document https://docs.google.com/document/d/1tU_yNmwu1raKZm9atHJ8THiQizkYTKykdWraIb15TSE/edit.

**Comment by davecheney** [comment]
Of course. But before beginning any work please discuss your design in
detail on the golang-dev mailing list.

**Comment by 39dotyt** [comment]
Sure. Thank you for responses.
