### ISSUE TITLE
syscall: add Windows Process Creation Flag constants

### ISSUE THREAD

**Issue by vChrysanthemum** [golang/go#13754]
I want to create process as "hidden" in windows , and i found os.ProcAttr.Sys.HideWindow is not useful.

Unfortunately, there are not CREATE_NO_WINDOW in syscall/ztypes_windows.go.

hence, if i want create a daemon process in windows , and which won't be closed while the console quit,
i should code as below:

```
var attr os.ProcAttr
attr.Sys = &syscall.SysProcAttr{}
attr.Sys.CreationFlags = 0x08000000
attr.Sys.HideWindow = true
os.StartProcess("foo", []string{}, &attr)
```

**Comment by bradfitz** [comment]
We're missing some Windows constants from https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx in the syscall package.

Maybe they belong in x/syscall/windows instead.

**Comment by alexbrainman** [comment]
I don't see a problem here. You code works fine as expected. Maybe change it to:
```
const CREATE_NO_WINDOW = 0x08000000
var attr os.ProcAttr
attr.Sys = &syscall.SysProcAttr{}
attr.Sys.CreationFlags = CREATE_NO_WINDOW
attr.Sys.HideWindow = true
os.StartProcess("foo", []string{}, &attr)
```
so you understand what it does next time you have to look at it. There are many consts defined in Windows .h files. We cannot have them all include in Go standard packages. Why should we include CREATE_NO_WINDOW and not others?

Alex
