### ISSUE TITLE
Getting started guide for GCS is stale for running service accounts with appengine dev_appserver

### ISSUE THREAD

**Issue by donjaime** [golang/go#13753]
I apologize in advance if this isn't the right spot to file this issue since this is related to documentation of Google cloud api libraries as they related to local appengine development.

The instructions as listed on https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/getstarted explicitly state that this should work:

dev_appserver.py . --appidentity_email_address [your_service_account_email] --appidentity_private_key_path [path_to_pkcs1_pem_file]

With no code modifications, to make your dev_appserver use the service account credentials for the sample code provided.

This is not the case. The code actually checks for the value of the env var GOOGLE_APPLICATION_CREDENTIALS, before falling back to your default credentials under ~/.config/gcloud/application_default_credentials.json. Which is not going to be your service account.

The --appidentity_email_address and --appidentity_private_key_path flags that are recommended don't actually do anything for this code example. The credentials aren't used for the OAuth token dance.

One needs to either add the env variables to the app.yaml, or explicitly write code to pass in a separate TokenSource as an optional cloud.ClientOption in the call to storage.NewClient(...) that has the service account credentials loaded. Neither of which are reflected in the guide.

Using a service account for local dev is important If one wants to use a separate dev-only GCS bucket for testing. This however requires forked code paths just for local development (outside of just swapping the bucket name). 

A better solution IMHO would be to have dev_appserver take in a --appidentity_json <path_to_credentials_json>  (or something like that) and then internally expose that to the go_appengine runtime via the GOOGLE_APPLICATION_CREDENTIALS env var which would make this work with no code changes at all to the libraries since they already pick this up for the managed VM and GCE cases.

**Comment by rsc** [comment]
More generally, @okdave, what's the right bug tracker for this kind of thing? Probably not this one. But where should we redirect people?

**Comment by broady** [comment]
@rsc the correct thing to do is to press the "Send feedback" button inline in the docs.

I'm going to move this to the internal Google bug tracker (b/26490266).
