### ISSUE TITLE
os: Rename cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by zaz600** [golang/go#13766]
go version go1.5.2 windows/386

After 92c5736 with MoveFileEx os.Rename("r:\1.txt", "z:\1.txt") on windows generate error:
> The system cannot move the file to a different disk drive

https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa365240(v=vs.85).aspx
> When moving a file, the destination can be on a different file system or volume. If the destination is on another drive, you must set the MOVEFILE_COPY_ALLOWED flag in dwFlags.

So,  syscall_windows.go Rename must be

```
func Rename(oldpath, newpath string) error {
	from, err := syscall.UTF16PtrFromString(oldpath)
	if err != nil {
		return err
	}
	to, err := syscall.UTF16PtrFromString(newpath)
	if err != nil {
		return err
	}
	return MoveFileEx(from, to, MOVEFILE_REPLACE_EXISTING|MOVEFILE_COPY_ALLOWED)
}
```

**Comment by ianlancetaylor** [comment]
os.Rename doesn't move a file to a different drive on Unix either.  I don't see a good reason to use MOVEFILE_COPY_ALLOWED; this is rename, not copy.  According to the docs MOVEFILE_COPY_ALLOWED can leave you with two copies of the file, which is not desirable.

**Comment by edisonrf** [comment]
what's the status of this issue? I met the same error:
`The system cannot move the file to a different disk drive`

using go1.6 windows/amd64

**Comment by bradfitz** [comment]
@edisonrf, the status is "closed". See previous comments before it was closed.
