### ISSUE TITLE
os: Lstat failed on C:\$Recycle.Bin

### ISSUE THREAD

**Issue by chai2010** [golang/go#13763]
go version devel +c7c7c70 Mon Dec 28 01:12:24 2015 +0000 windows/amd64

```Go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	f, err := os.Open("C:")
	if err != nil {
		log.Fatal("os.Open:", err)
	}
	defer f.Close()

	names, err := f.Readdirnames(-1)
	if err != nil {
		log.Fatal("f.Readdirnames:", err)
	}

	for i, s := range names {
		fmt.Println(i, s)
		filename := filepath.Join("C:", s)
		fileInfo, err := os.Lstat(filename)
		if err != nil {
			log.Fatal("os.Lstat:", err)
		}
		fmt.Println("\t", fileInfo.IsDir())
	}
}
```

error:
os.Lstat:GetFileAttributesEx C:$Recycle.Bin: The system cannot find the file specified.

**Comment by mattn** [comment]
@chai2010 because you don't append last backslash for Join().

```go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	f, err := os.Open(`C:\`)
	if err != nil {
		log.Fatal("os.Open:", err)
	}
	defer f.Close()

	names, err := f.Readdirnames(-1)
	if err != nil {
		log.Fatal("f.Readdirnames:", err)
	}

	for i, s := range names {
		fmt.Println(i, s)
		filename := filepath.Join(`C:\`, s)
		fileInfo, err := os.Lstat(filename)
		if err != nil {
			log.Fatal("os.Lstat:", err)
		}
		fmt.Println("\t", fileInfo.IsDir())
	}
}
```
But it will be fail with some system-file on C:\
```
2015/12/29 20:57:39 os.Lstat:GetFileAttributesEx C:\hiberfil.sys: The process cannot access the file because it is being used by another process.
exit status 1
```

**Comment by chai2010** [comment]
@mattn thanks.
I want to say the os.Lstat can't process some system-file.
I need use `mklink /J dst d:` to mount some disk to subdir, but the `filepath.Walk` failed, if the mounted dir has some system-file(suck as $Recycle.Bin).

**Comment by mattn** [comment]
On my windows10, my modified code above display like below.
```
0 $Recycle.Bin
	 true
1 $WINDOWS.~BT
	 true
2 $Windows.~WS
	 true
3 bootmgr
	 false
4 BOOTNXT
	 false
5 dev
	 true
6 Documents and Settings
	 true
7 hiberfil.sys
2015/12/29 22:20:22 os.Lstat:GetFileAttributesEx C:\hiberfil.sys: The process cannot access the file because it is being used by another process.
exit status 1

```

So `$Recycle.Bin` is not related on this issue, I guess.

**Comment by alexbrainman** [comment]
@chai2010, what do you think the problem is?

I think the problem is that os.Open("C:") currently opens root directory of C: (`C:\`). I think we should change the code so it opens "current directory" on C: (`C:.`), just like "dir c:" command does. What do you think?

I suspect if you run your example program from root directory on C:, it will run just fine.

Alex

**Comment by chai2010** [comment]
@mattn I has the same error as you: `os.Lstat` failed on C:\hiberfil.sys.

@alexbrainman I donot know the reason. I think there are three problems:

1. `C:\` is not same as `C:`
2.  `os.Lstat` failed on C:\hiberfil.sys, I donot know the reason.
3. `filepath.Walk` failed: `C:\$Recycle.Bin\S-1-5-21-1654714224-3836454192-1760979379-1000\$R52OC9K\System Volume Information: Access is denied.`

The `filepath.Walk` test code:

```Go
func main() {
	const root = `C:\`
	err := filepath.Walk(root, func(path string, fi os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		fmt.Printf("filepath.Walk: path = %s; isdir = %v\n", path, fi.IsDir())
		return nil
	})
	if err != nil {
		log.Fatal("filepath.Walk:", err)
	}
	fmt.Println("Done")
}
```
