### ISSUE TITLE
proposal: Add runtime.Free() for GOGC=off

### ISSUE THREAD

**Issue by TUSF** [golang/go#13761]
There is a desire by some to disable Garbage Collection in Go. There are various reasons why someone might want to do this, but when someone DOES disable Garbage Collection through the use of environment variables, there's an issue one might run into:

There's no built in way to implicitly deallocate memory. But the runtime package does have a sysFree() function. I'm proposing to have this function exported by the package, by making a runtime.Free(v interface{}) function that calls sysFree with the proper pointers and all.

While it's great to not have to worry about memory management, garbage collection has some draw backs, and if you're going to implement a feature to disable Garbage Collection, I feel it's necessary to also allow the ability to free up memory manually.

**Comment by minux** [comment]
The Go GC does have the ability to manually deallocate blocks anymore. And
besides, runtime.Free is unsafe (people might free still in use pointers or
double free) and then all sorts of C memory problem that Go tries hard to
get rid of will come back. The other reason is that runtime sometimes
allocates behind your back and there is no way for the program to
explicitly free those memory.

If you really want to manually manage memory with Go, implement your own
memory allocator based on syscall.Mmap or cgo malloc/free.

Disabling GC for extended period of time is generally a bad solution for a
concurrent language like Go. And Go's GC will only be better down the road.

**Comment by TUSF** [comment]
> The Go GC does have the ability to manually deallocate blocks

Do you mean how you can choose to disable GC at runtime, and switch it back on at a later time?

I also understand the need for GC when it comes to avoiding such problems in Go, and I would gladly take GC over having to manually unmap memory I'm not longer using. This proposal is for those who aren't looking for that, and want to make use of every bit of performance they can.

Sure, Garbage Collection can improve, but then what's the point of allowing the disabling of it?

**Comment by bradfitz** [comment]
The ability to disable garbage collection is only for debugging. It is not intended for use by end users.
