### ISSUE TITLE
tour: a sight improvement to avoid repetition of the variables in Printf

### ISSUE THREAD

**Issue by nad2000** [golang/go#13768]
Context: http://127.0.0.1:3999/basics/11

	const f = "%[1]T(%[1]v)\n"
	fmt.Printf(f, ToBe)
	fmt.Printf(f, MaxInt)
	fmt.Printf(f, z)

**Comment by adg** [comment]
I think this just makes the code more harder for newcomers to understand. Thanks anyway.
