### ISSUE TITLE
switch type does not work well(bug of reflection or go compiler on windows 10)

### ISSUE THREAD

**Issue by elebore** [golang/go#13760]
There are two files,main.go and main1.go

-------------------------content of main.go----------------------------------------
package main
import "code.google.com/p/go.net/websocket"
func main() {
	conn := websocket.Conn{}
	TestFunc(&conn)
}
----------------------------------end of main.go--------------------------------------------------
----------------------content of main1.go------------------------------------------
package main
import (
	"fmt"
	"net"
	"reflect"
	"golang.org/x/net/websocket"
)

func TestFunc(conn net.Conn) {
	switch  conn.(type) {
	case *websocket.Conn:
		fmt.Println("OK")
	default:
		fmt.Println("NOT")
	}
}
----------------------------------------end of main1.go----------------------------------------------
We should get OK from console by running this program on windows 10 compiling with go 1.5.2,but I got NOT,when I moved TestFunc to file main.go,then I got OK

**Comment by cznic** [comment]
`conn` is `websocket.Conn`, not `*websocket.Conn`. Working as intended.

**Comment by bradfitz** [comment]
See https://golang.org/wiki/Questions if you'd like to discuss this further.

**Comment by elebore** [comment]
websocket.Conn does not implement the net.Conn interface,could you paste you code?

**Comment by bradfitz** [comment]
Sorry, this is not a Q&A forum. Please move this to the mailing list.

**Comment by elebore** [comment]
I am not discussing question,I am reporting issue.Have you tried the code?Your go compiler did not work

**Comment by mikioh** [comment]
@elebore,

I'd strongly recommend you to have a look at https://golang.org/ref/spec carefully. It describes what's "Type" in the language, how it's related to "Package" and how type assertion works.

**Comment by elebore** [comment]
A package in turn is constructed from one or more source files that together declare constants, types, variables and functions belonging to the package and which are accessible in all files of the same package.So a function should generate same output with same input when it locates in different source file of the same package.Am I right?

**Comment by prashantv** [comment]
@elebore In `main.go` you import websocket from code.google.com/p/go.net and in `main1.go` you import websocket from golang.org/x/net. Since they're not the same type, the type assertion is failing (as it should).

**Comment by elebore** [comment]
thanks
