### ISSUE TITLE
Darwin Go 1.5.2 OS X installer has incorrect timestamps

### ISSUE THREAD

**Issue by davecheney** [golang/go#13769]
I just installed the osx 1.5.2 download from the website<sup>1</sup> and the timestamps for some of the packages are stale compared to their source version.

```
% stat /usr/local/go/pkg/darwin_amd64/errors.a /usr/local/go/src/errors/errors.go 
16777220 6554433 -rw-r--r-- 1 root wheel 0 5842 "Dec 29 15:38:18 2015" "Dec  3 02:01:12 2015" "Dec 29 15:29:26 2015" "Dec  3 02:01:12 2015" 4096 16 0 /usr/local/go/pkg/darwin_amd64/errors.a
16777220 6556089 -rw-r--r-- 1 root wheel 0 499 "Dec 29 15:38:29 2015" "Dec  3 02:01:13 2015" "Dec 29 15:29:27 2015" "Dec  3 02:01:13 2015" 4096 8 0 /usr/local/go/src/errors/errors.go
```
errors.a has an mtime that is _slightly_ older than errors.go

/cc @broady 

1. https://storage.googleapis.com/golang/go1.5.2.darwin-amd64.pkg

**Comment by davecheney** [comment]
```
% stat /usr/local/go/pkg/darwin_amd64/runtime/cgo.a /usr/local/go/src/runtime/cgo/callbacks.go
16777220 6554527 -rw-r--r-- 1 root wheel 0 15534 "Dec 29 15:59:40 2015" "Dec  3 02:01:12 2015" "Dec 29 15:29:26 2015" "Dec  3 02:01:12 2015" 4096 32 0 /usr/local/go/pkg/darwin_amd64/runtime/cgo.a
16777220 6557360 -rw-r--r-- 1 root wheel 0 3424 "Dec 29 16:00:34 2015" "Dec  3 02:01:14 2015" "Dec 29 15:29:27 2015" "Dec  3 02:01:14 2015" 4096 8 0 /usr/local/go/src/runtime/cgo/callbacks.go
```

runtime/cgo.a is out of date with respect to cgo/callbacks.go by at least 2 seconds.

**Comment by gregory-m** [comment]
Same here:
```
⇢ $ stat /usr/local/go/pkg/darwin_amd64/errors.a /usr/local/go/src/errors/errors.go
16777220 4634154 -rw-r--r-- 1 root wheel 0 5842 "Dec  3 03:01:12 2015" "Dec  3 03:01:12 2015" "Dec 29 16:58:55 2015" "Dec  3 03:01:12 2015" 4096 16 0 /usr/local/go/pkg/darwin_amd64/errors.a
16777220 4635839 -rw-r--r-- 1 root wheel 0 499 "Dec  3 03:01:13 2015" "Dec  3 03:01:13 2015" "Dec 29 16:58:56 2015" "Dec  3 03:01:13 2015" 4096 8 0 /usr/local/go/src/errors/errors.go
```
```
⇢ $ stat /usr/local/go/pkg/darwin_amd64/runtime/cgo.a /usr/local/go/src/runtime/cgo/callbacks.go
16777220 4634252 -rw-r--r-- 1 root wheel 0 15534 "Dec  3 03:01:12 2015" "Dec  3 03:01:12 2015" "Dec 29 16:58:55 2015" "Dec  3 03:01:12 2015" 4096 32 0 /usr/local/go/pkg/darwin_amd64/runtime/cgo.a
16777220 4637118 -rw-r--r-- 1 root wheel 0 3424 "Dec  3 03:01:14 2015" "Dec  3 03:01:14 2015" "Dec 29 16:58:56 2015" "Dec  3 03:01:14 2015" 4096 8 0 /usr/local/go/src/runtime/cgo/callbacks.go
```

**Comment by davecheney** [comment]
I just checked 1.5.1 has the same problem.

**Comment by rsc** [comment]
My guess is that some process somewhere does a copy of the tree, and p is alphabetically before s, so pkg gets copied before src. The time stamps are ignored in releases, though.

**Comment by rsc** [comment]
@davecheney Regarding the initial report, yes the time stamps are misordered. But did this cause a problem for you? It's not supposed to, at least not with cmd/go.

**Comment by davecheney** [comment]
@rsc I had a bug report from a gb user who was using the OSX installer. gb recurses into the std library and will rebuild it to a temporary location _iff_ it is out of date or missing (if you're doing a cross compile), so it's important that the timestamps are correct.

I think I found the bug, please see CL 18355

**Comment by rsc** [comment]
Dave, I strongly recommend not rebuilding the standard library in a release
build based on mtimes. There is absolutely no guarantee the time stamps
will be correct. Trees get copied around.

**Comment by davecheney** [comment]
@rsc, thanks for that advice. I've put some checks in place in gb to ensure that it doesn't try to rebuild the stdlib unless cross compiling.

**Comment by broady** [comment]
Not sure why gopherbot didn't close this from 9b694ba7f5c8a2e3f671e53a1ac3618702f63aff, so closing this.

**Comment by rsc** [comment]
@broady if you go get -u golang.org/x/review/git-codereview it will rewrite your commit messages to close bugs in this repo.
