### ISSUE TITLE
x/crypto/ssh: permit use of CBC ciphers without needing to fork repo

### ISSUE THREAD

**Issue by egoldschmidt** [golang/go#13776]
Resurrecting this conversation.

- **Summary**: CBC ciphers are insecure and have been removed from the supported ciphers list in `x/crypto/ssh`. There is no mechanism to override this decision. Unfortunately, many legacy systems (routers, appliances, old SFTP servers, etc) still use these ciphers, presenting an unexpected blocker to using Go to communicate with those systems (specifically, the `ssh: no common algorithms` error).
- **Current solution**: Fork /x/crypto/ssh, uncomment the `aes128-cbc` config line, fix all import paths to reference forked repo, fork all dependent repos and update _their_ import paths (e.g.: https://github.com/ScriptRock/crypto, https://github.com/ScriptRock/sftp)
- **Recommended solution**: Allow an override, perhaps in `ssh.ClientConfig`, to permit use of CBC ciphers.
- **Example of someone running into this issue**: #12982
- **Prior discussions**: #4274, https://groups.google.com/forum/#!topic/golang-nuts/J2XCsTsNQ9o

/cc @bradfitz

**Comment by bradfitz** [comment]
I would like this as well. I also have to maintain a fork to control some "smart" home devices (which are only on a private LAN).

/cc @hanwen @agl

**Comment by hanwen** [comment]
we coudl just uncomment the definition. The cipher would only work if added explicitly in the Client/ServerConfig.
