### ISSUE TITLE
encoding/json: incorrect slice marshaling for slice of bytes implementing json.Marshaler

### ISSUE THREAD

**Issue by tarndt** [golang/go#13783]
encoding/json: Incorrect slice marshaling for slice of bytes implementing json.Marshaler:

Steps to reproduce:
1. Create a type that is based on byte
2. Implement json.Marshaler
3. Create a slice of said byte type
4. Attempt to call json.Marshal on that slice
5. Observe incorrect result, yourtype.MarshalJSON() is never called.

Repeat with int, works as expected.
Use your original byte type, but put them in a slice of json.Marshaler, works as expected.

Code showing working cases and non-working case side-by-side: http://play.golang.org/p/5xgjl4e04R

System details: go1.5.1 / amd64

**Comment by joeshaw** [comment]
Are there any backward compatibility considerations for this?  It seems like a legit bug otherwise.
