### ISSUE TITLE
time: RFC1123 format should not say "UTC"

### ISSUE THREAD

**Issue by m-ivanov** [golang/go#13781]
after reading a couple of times the RFC1123 i think that strings returned by time.Format(time.RFC1123) is not correct

```
fmt.Printf("\n\nthis is not RFC1123  %s \n\n", time.Now().UTC().Format(time.RFC1123));
// Wed, 30 Dec 2015 15:10:40 UTC 
```

searching around i found a post that reflect mo opinions about
http://stackoverflow.com/questions/25658897/is-utc-a-valid-timezone-name-for-rfc-1123-specification

i know that the format already exist and is "http.TimeFormat" but what i want to point out is that the term "time.RFC1123" is wrong/inexact and just bring more confusion

**Comment by ianlancetaylor** [comment]
Looking at RFC 1123 and RFC 822, it does seem that a date in that format should say "GMT" or "UT" but not "UTC".  I think it would probably be a mistake to change the behavior of time.RFC1123 at this point, but we could at least document the discrepancy.  Note that the RFCs recommend the use of what Go calls time.RFC1123Z.
