### ISSUE TITLE
activate the builtin fake clock

### ISSUE THREAD

**Issue by markfink** [golang/go#13788]
I need a fake clock for testing which works reliably in concurrent situations. I am convinced, that the correct strategy is to advance the fake clock with checkdead(). Such an implementation of faketime is already completed and it is contained in runtime/proc.go and runtime/time.go. Unfortunately faketime is deactivated by default with no way to activate it.

I am proposing a one-liner to activate the existing feature.
```
// Faketime activates the builtin fake clock and sets its current time in ns
func Faketime(ns int64) {
	faketime = ns
}
```

My proposal as pull request:
https://github.com/golang/go/pull/13787

If you guys have a way to pin this to test executions (go test ./...) it would perfectly work for me, too.

**Comment by Thomasdezeeuw** [comment]
You can also fake time.Now() with something like this (http://play.golang.org/p/_AMjbv2qWB).

```go
package main

import "fmt"
import "time"

var now = time.Now

func main() {
	fmt.Println("Actual time", now())
	
	now = func() time.Time { return time.Date(2006, 01, 02, 15, 04, 05, 0, time.UTC)}
	
	fmt.Println("New time", now())
}
```

Note the actual time in the playground is fixed to date somewhere in 2009.

**Comment by markfink** [comment]
@Thomasdezeeuw not clear why you answered to this issue. the code you included basically does this: 
`
fmt.Println("New time 2006-01-02 15:04:05 +0000 UTC"
`

My pull request does something completely different. It activates the fake clock that is built into golang which is a sophisticated solution to a complicated concurrency problem (println does not help here). Some details are about the fake clock are documented here:
https://blog.golang.org/playground

**Comment by bradfitz** [comment]
This is a big enough topic that it would require the https://golang.org/s/proposal-process with a proper design doc. But I think https://golang.org/wiki/Questions might be more appropriate. I feel like this topic comes up often on the mailing list.

**Comment by markfink** [comment]
I bet one could discuss this topic till the cows come home. I would really love to do that but I am only a hobby Gopher so I simply can not afford it. The only thing I can do is to ask for help and file an issue. Since this is a testing related issue I guess it has low prio anyway.
So I hope Google has an issue process or something that can deal with this.

**Comment by glestaris** [comment]
@markfink you might want to check https://github.com/pivotal-golang/clock. It provides fake clock and timer. However, it does so by using a non-standard interface and you would need to inject the object (fake or real) in the unit that you want to test.

**Comment by markfink** [comment]
@glestaris thank you for mentioning this one. I did not see it before. I recently started a collection of "broken" fake clocks and added it. In my opinion pivotal-golang/clock "avoids" the hard part of the problem (advancing the clock) and leaves it to the caller. Do not get me wrong - this is totally fair to me.

**Comment by glestaris** [comment]
@markfink Yes, you are correct in thinking that you have to advance the clock yourself. However, I find it useful when I am trying to test a timeout or a sleep:

```go
package main

import (
	"fmt"
	"time"
	"github.com/pivotal-golang/clock"
	"github.com/pivotal-golang/clock/fakeclock"
)

func BananaFunc(clk clock.Clock, t time.Duration) {
	<-clk.NewTimer(t).C()
	fmt.Println("Banana!")
}

func main() {
	fakeClock := fakeclock.NewFakeClock(time.Now())
	c := make(chan struct{})
	go func() {
		BananaFunc(fakeClock, time.Minute)
		close(c)
	}()
	fakeClock.WaitForWatcherAndIncrement(time.Minute)
	<-c
}
```

In a real test, I would assert on a post condition, to make sure that the unit you are testing actually worked.

I am not sure what do you mean by concurrent situations. I guess you would like to test the synchronization between different goroutines (?). I think this is still possible, but admittedly more complex than the above example.

**Comment by markfink** [comment]
the only concurrency that you have in your sample is the one that is required by the fakeclock for advancing it. Lets say one works on a complicated simulation engine like where 1001 things are happening in parallel. In order to test the engine he would write some tests maybe leaving out the real application of the simulation and have reproducible sleep operations instead.
In such a situation where you think it is possible just dealing with some complexity I happen to disagree. I am pretty sure that this is not possible. I am convinced that the only simple and correct approach is already built into the golang scheduler (runtime). I am pretty sure the engineers who built the golang runtime struggled with this problem for quite some time before they came up with this beautiful solution.
Honestly I do not understand why everybody is so afraid of using great stuff that is already built into the runtime.

**Comment by bradfitz** [comment]
Using the runtime's built-in fake clock only works if you can control the whole world and prevent network access, filesystem access, etc. Otherwise programs get confused, seeing two clocks: the internal fake clock, and the outside world's real clock.

I'm closing this until there's a formal proposal. But I don't imagine it'll involve modifying Go's runtime at all. Perhaps we need a clock interface in the standard library somewhere, and maybe other parts of Go could use it. I don't know. It needs a lot of research.
