### ISSUE TITLE
x/mobile/exp/f32: Add some functionality

### ISSUE THREAD

**Issue by star-tek-mb** [golang/go#13786]
Package f32 - is good now. But there are no some functions. I want add functions *f32.Mat4.Raw() and *f32.Mat4.Ortho.

~~~go
// Returns raw matrix (row-major)
func (m *Mat4) Raw() []float32 {
	out := make([]float32, 16)
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			out[i*4+j] = m[i][j]
		}
	}
	return out
}

// Usage:
glctx.UniformMatrix4fv(mvp, MVP.Raw())
~~~

And Ortho:
~~~go
// Ortho sets m to be the GL orthographic matrix
func (m *Mat4) Ortho(width, height, near, far float32) {
	m[0][0] = 2 / width
	m[1][1] = -2 / height
	m[2][2] = -2 / (far - near)
	m[3][2] = -(far + near) / (far - near)
	m[3][3] = 1 
}
~~~

And some structures, like Mat2 (for full functionality) and Vec2 (for UV).
Final update - support for float64 (x/mobilfef32 and x/mobile/f64 packages).

P.S: sorry for my english

**Comment by hyangah** [comment]
This is about the future plan for the highly experimental f32, .. packages.
Let's discuss in golang-nuts mailing list.

/cc @nigeltao
