### ISSUE TITLE
x/net proposal: Add XMPP helpers starting with a JID implementation

### ISSUE THREAD

**Issue by SamWhited** [golang/go#13797]
I'd like to begin adding some experimental helpers for XMPP implementations under `golang.org/x/net/xmpp`.

I thought it might be nice to start with a simple Jabber Identifier (JID) implementation. I've been working on one ([docs](https://godoc.org/bitbucket.org/mellium/xmpp/jid)), but the API isn't very Go-like right now and probably needs to be changed. I'm thinking that if it were to become a part of x/net I'd do something like the following:

```go
type JID struct {
// Nothing exported
}
SplitJID(j string) (localpart, domainpart, resourcepart string, err error)
ParseJID(j string) (JID, error)
UnsafeParseJID(j string) (JID, error) // Fast, but no PRECIS enforcement, eg. for trusted JIDs loaded from a database that were already enforced before being saved.
JIDFromParts(localpart, domainpart, resourcepart string) (JID, error)
UnsafeJIDFromParts(localpart, domainpart, resourcepart string) (JID, error)
(j JID) Bare() JID // Returns a copy of the JID without the resourcepart
(j JID) String() JID
(j JID) Localpart() string
(j JID) Domainpart() string
(j JID) Resourcepart() string
(j JID) MarshalAttr(…) // Satisfies xml.MarshalerAttr, not a pointer so that pointers and normal JIDs marshal the same way… is this idiomatic or does it just make things inconsistant?
(j *JID) UnmarshalAttr(…) // Satisfies xml.UnmarshalerAttr
```

It might be more idiomatic to just export the parts, but I like the idea of having JIDs be (effectively) immutable (unless you unmarshal into them; maybe this is just confusing though?). The other part I'm not sure about is how to distinguish between a JID that has been verified for validity (via the PRECIS enforcement step) and one that hasn't.

I've also considered either making it satisfy the `net.Addr` interface, or having a separate `XMPPAddr` that holds a JID and satisfies the `net.Addr` interface itself, but I'm not sure how useful that would be and it could come later in a separate revision.

Would this be an appropriate fit for the net package?

**Comment by bradfitz** [comment]
I don't think this widely applicable enough to live in x/net.

For what it's worth, I say this as the author of a once-large XMPP server: https://github.com/djabberd/ ... https://github.com/djabberd/DJabberd

I would like to see a good Go implementation of XMPP, but I don't want to develop it incrementally in x/net, and I don't have time to be a reviewer (and I can't think of anybody else working on Go who does).
