### ISSUE TITLE
Add combinatoric generators to standard library

### ISSUE THREAD

**Issue by bruceadowns** [golang/go#13796]
This issue covers the desire to add combinatoric generators to standard library.

* product()
* permutations()
* combinations()
* combinations_with_replacement()

The work could start (or be based on) as a port of the python equivalences documented at https://docs.python.org/3/library/itertools.html. I have already begun the porting process with success, though would ask for guidance on structure and placement.

A recent code challenge at http://adventofcode.com found the only thing missing from the golang standard library was the generation of combinations and permutations.

**Comment by minux** [comment]
Why these must be in the standard library? And not as a go-gettable package?

**Comment by bruceadowns** [comment]
Please clarify what justification is needed and what form it should take. Combinatoric generators are available is the standard library of other languages and IMHO it would be a pleasant addition to golang.

**Comment by ianlancetaylor** [comment]
Adding new functionality to the standard library is a high bar.  Generally we only do it for functions needed by a web server or by lots of programs.  A go-gettable package is just as usable.

In particular, as far as I know, the C and C++ standard libraries do not have these functions.

In any case, the first step is to write the packages and make them go gettable.  Then we can discuss whether they should be added to the standard library.  So I'm closing this issue for now.

**Comment by bruceadowns** [comment]
> Adding new functionality to the standard library is a high bar. Generally we only do it for functions needed by a web server or by lots of programs.

Ok, good to know. Thanks for the insight. :-)

> A go-gettable package is just as usable.

Agreed, it is as useable. Though not as practically applicable for the enterprise. I first need to find the third party functionality, lock into the proper version, and then trust them explicitly.

> In particular, as far as I know, the C and C++ standard libraries do not have these functions.

For C++ I would reference this:
http://www.cplusplus.com/reference/algorithm/next_permutation/
http://www.cplusplus.com/reference/algorithm/prev_permutation/

And ruby:
http://ruby-doc.org/core-2.2.0/Array.html#method-i-combination

And as noted above, for python:
https://docs.python.org/3/library/itertools.html.
