### ISSUE TITLE
tour: is here an error or i can't understand something

### ISSUE THREAD

**Issue by eugenechertikhin** [golang/go#13791]
Context: https://tour.golang.org/basics/7

Hi,

i just start learning and found somthing i can't undestand.
here is code list
```go
package main

import "fmt"

func split(sum int) (x, y int) {
	x = (sum * 4) / 9
	y = sum - x
	return
}

func main() {
	fmt.Println(split(10))
}
```

As i wait result should be 5 and 5, but in result window i see 4 and 6
kindly explain why go calculate so strange.

thanks!

**Comment by minux** [comment]
The division operation uses truncation.

So 40 / 9 == 4, not 5.

Please use other medium to ask questions, the issue tracker is to report
bugs only. Please see https://golang.org/wiki/Questions.
