### ISSUE TITLE
encoding/gob: document gob format compatibility promise 

### ISSUE THREAD

**Issue by dsnet** [golang/go#13808]
Using ```go1.5```.

The ```encoding/gob``` package does a fair job at describing the underlying gob format as it appears on the wire. However, it makes no explicit statements about the stability of the format *across* different versions of Go. For example, will a gob output from ```go1.5``` still be decodable by a hypothetical future ```go1.8```? 

The docstring for the ```GobEncoder``` type, seems to indicate that this is true given the fact that gobs can be stored:
> Note: Since gobs can be stored permanently, It is good design to guarantee the encoding used by a GobEncoder is stable as the software evolves. For instance, it might make sense for GobEncode to include a version number in the encoding.

However, the fact that gobs can be stored permanently is mentioned nowhere else in the package documentation, except for the linked blog post. (In fact, most of package refers to gobs as a data interchange format to be sent over the network, rather than as a format that is suitable for disk storage.)

Can the format compatibility promise be more explicit? Perhaps in the Overview section of the package documentation? Obviously, this promise can only be kept if custom GobEncoder and BinaryMarshaler implementations remain stable. However, a promise could be made for types that do not implement those interfaces.

**Comment by ianlancetaylor** [comment]
CC @robpike
