### ISSUE TITLE
cmd/gofmt: strange indentation of +-separated args

### ISSUE THREAD

**Issue by cespare** [golang/go#13800]
This indentation seems strange:

``` go
b := []byte(
	"foo" +
		"bar" +
		"baz",
)
```

(See playground [here](http://play.golang.org/p/uVLjjZV2gS).)

Not sure whether this is a bug or some weird corner case. I would've expected

``` go
b := []byte(
	"foo" +
	"bar" +
	"baz",
)
```

/cc @griesemer

**Comment by minux** [comment]
I think the current behavior is reasonable: all
continuation lines have extra indentation.

**Comment by cespare** [comment]
Oh, right. It's the same as

``` go
b := []byte(
	foo(
		"bar"),
)
```

**Comment by dsnet** [comment]
If you really cared about alignment (for readability reasons or something). You could do an empty string on the first line:
```go
hex := []byte("" +
	"0123456789abcdef" +
	"0123456789abcdef" +
	"0123456789abcdef" +
	"0123456789abcdef" +
	"0123456789abcdef")
```
