### ISSUE TITLE
x/mobile/exp/audio compilation issue on Mac

### ISSUE THREAD

**Issue by mattetti** [golang/go#13803]
I tried to compile the audio example from my mac to build an apk and getting a compilation error due to openAL headers not being available.

```
# golang.org/x/mobile/exp/audio/al
../../exp/audio/al/al_android.go:13:19: fatal error: AL/al.h: No such file or directory
 #include <AL/al.h>
```

Go version (1.6 beta):
`go version devel +8db371b Thu Dec 17 22:45:50 2015 +0000 darwin/amd64` 

OS X: `10.10.5 (14F1021)`

Xcode:
```
xcodebuild -version
Xcode 6.3.2
Build version 6D2105
```

**Comment by mattetti** [comment]
For the record, I tried to edit a couple files to include `OpenAL/al.h` and `alc.h` but that created other issues:

```
#ifdef GOOS_darwin
#include <OpenAL/al.h>
#include <OpenAL/alc.h>
#endif

#ifdef GOOS_linux
#include <AL/al.h>
#include <AL/alc.h>
#endif
```

`
/Users/mattetti/Code/golang/pkg/gomobile/android-ndk-r10d/arm/bin/arm-linux-androideabi-gcc errors for preamble:
../../exp/audio/al/al_android.go:39:20: error: unknown type name 'LPALENABLE'
 void call_alEnable(LPALENABLE fn, ALenum capability) {
                    ^
../../exp/audio/al/al_android.go:39:35: error: unknown type name 'ALenum'
 void call_alEnable(LPALENABLE fn, ALenum capability) {
`

etc... you get the point.

**Comment by rakyll** [comment]
How do you build the package, could you send me the commands you run with -x flag? And which env variables are set? Are you targeting darwin or Android?

**Comment by mattetti** [comment]
I'm building the example using the information from `main.go`:

`$ gomobile build golang.org/x/mobile/example/audio`

Gomobile doesn't seem to accept shared build flags as the documentation seems to indicate. I can't figure out what version of gomobile I have installed, but I noticed something else odd:

```
$ gomobile build -target=android golang.org/x/mobile/example/basic
usage: gomobile [package]

Build compiles and encodes the app named by the import path.

The named package must define a main function.

If an AndroidManifest.xml is defined in the package directory, it is
added to the APK file. Otherwise, a default manifest is generated.

If the package directory contains an assets subdirectory, its contents
are copied into the APK file.

These build flags are shared by the build, install, and test commands.
For documentation, see 'go help build':
TODO:
	-a
	-tags 'tag list'
```

I've removed the gomobile binary (I couldn't even get a version using the version flag) and reinstalled gomobile which solved the problem. I'm really sorry, it looks like I had an old version installed, maybe in gobin.
