### ISSUE TITLE
Update the documentation on GOROOT_FINAL before release of go1.6

### ISSUE THREAD

**Issue by johnjaylward** [golang/go#13816]
see #13809

https://golang.org/cmd/go/#hdr-Environment_variables

The above documentation is very sparse and should be expanded. It is not clear enough on what this variable does and what it's used for. Some questions that should be answered in the documentation:

* What are valid values? Does it have to be a valid go installation path, or can it be any value? (The documentation makes it sound like it should to be a valid go installation, but maybe not? It just says it's used to overwrite the stack trace, not that it's used for actual building)
* Does it overwrite paths that are relative to GOPATH (i.e. user source), or only paths relative to GOROOT? (The documentation makes it sound like only GOROOT paths are overwritten)
* When should the variable be used (i.e. under what use cases)? Currently, the documentation makes this variable seem downright useless. It doesn't appear to offer any benefit over the standard GOROOT.

Maybe more clarification could be added that I didn't think of.

**Comment by rsc** [comment]
I'm sorry for the runaround but I don't think GOROOT_FINAL should be any more documented than it already is in make.bash:

```
# GOROOT_FINAL: The expected final Go root, baked into binaries.
# The default is the location of the Go tree during the build.
```

It sets the default value of GOROOT for the built toolchain, and it sets the paths that show up in the binaries in that toolchain (like the go command and go compiler). It has nothing to do with user programs. I will comment more on #13809 for your specific problem, which GOROOT_FINAL does not solve.
