### ISSUE TITLE
playground: use import parenthesis

### ISSUE THREAD

**Issue by techjanitor** [golang/go#13813]
I think the default playground snippet should include fmt in parenthesis by default. I am almost always using multiple packages, and it may even teach people about this format rather than writing import over and over again.

    package main
    
    import (
    	"fmt"
    )
    
    func main() {
    	fmt.Println("Hello, playground")
    }

https://github.com/golang/playground/blob/master/app/goplay/edit.go#L67

**Comment by adg** [comment]
I agree it is a more useful starting point.
