### ISSUE TITLE
tour: Ambiguous text "Package io defines Reader and Writer; you don't have to." in methods page 5

### ISSUE THREAD

**Issue by finnigantime** [golang/go#13818]
Context: https://tour.golang.org/methods/5

`Package io defines Reader and Writer; you don't have to.`

The code in this example does explicitly define Reader and Writer, and the package is "main" so it can be run and not "io". So, the above line confused me and I'm not sure exactly what's being said. It is saying that normally Reader and Writer are interfaces defined in the "io" package which can be imported, but in this code snippet we're showing an example of how to define Reader and Writer ourselves?

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
I'm currently working on a CL that replaces this text entirely, so I'll add this issue to the "fixes" line.
