### ISSUE TITLE
log/syslog : support tcp/udp for non-linux platforms

### ISSUE THREAD

**Issue by Nyks06** [golang/go#13810]
Hi, 

I tried to use the log/syslog package under windows and i've seen that it is not available, even when i tried to use it with a windows compatible protocol like udp.

After checking the sources i noticed that the package is not actually compiled for windows.
```
// +build !windows,!nacl,!plan9
```

I found a way to patch it. I compiled the syslog.go file for windows and moved the call to UnixSyslog in the syslog_unix.go file. This doesn't change the behaviour under a linux platform and permits the support of some protocols under windows.

I already have forked the package and patched/tested it. 

Go Version : 1.4.x
OS & processor architecture : linux/amd64 and windows/amd64

**Comment by bradfitz** [comment]
The log/syslog package in the standard library is frozen and probably shouldn't have been included in the standard library in the first place. See https://godoc.org/?q=syslog or community-maintained versions.

See also: #1108 (also closed0
