### ISSUE TITLE
gccgo:  backport of mksysinfo.sh changes

### ISSUE THREAD

**Issue by laboger** [golang/go#13814]
This is a follow up for the discussion: https://groups.google.com/forum/#!searchin/golang-dev/mksysinfo.sh/golang-dev/EtfGEK0zZDU/x8XAMRxaCwAJ

I did not include the change for Solaris in my patch, but all others mentioned were included.

I used the attached patch and built gccgo from gcc5 on ppc64le (bootstrap) and on x86 (not bootstrap).  Ran the go and libgo testsuites successfully.

[gcc5-mksysinfo-backport.txt](https://github.com/golang/go/files/77473/gcc5-mksysinfo-backport.txt)

**Comment by ianlancetaylor** [comment]
Thanks.  Committed to GCC 5 branch.
