### ISSUE TITLE
net/http/pprof: profiling isn't cancelled when the client hangs up

### ISSUE THREAD

**Issue by alexflint** [golang/go#13833]
```
go version go1.5.2 darwin/amd64
```

If I use `go tool pprof` to collect a profile from a server running the `net/http/pprof` endpoints then kill the HTTP client before the profile is completed, the server keeps profiling for the full 30s. This means that any further attempts to collect profiles during this time period will fail with `500 Internal Server Error` because it multiple CPU profiles cannot be collected simultaneously.

It seems that the server should detect termination of the TCP connection and call `pprof.StopCPUProfile` in: https://golang.org/src/net/http/pprof/pprof.go

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/18283
