### ISSUE TITLE
net/http: figure out a better User-Agent story

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13837]
Fork of some discussion in #13685

Let's figure out User-Agents in Go 1.7: perhaps an optional func field on http1 and http2 Transports to modify the User-Agent before it's sent out?

``` go
   SetUserAgent  func(old string) string
```

Or fields for the default value to set if unset? Or a field to append? Maybe those are the two common requests.

In any case, the stdlib's private http2 Transport should use the public http1.Transport's same options, and this should all have new clientserver_test.go additions similar to https://go-review.googlesource.com/18284

/cc @okdave @rakyll @adg

**Comment by rakyll** [comment]
I don't know why we may like to handle it in the Transport layer.  Can we have a setter and an appender on *Request?

```
package http

func (r *Request) AppendUserAgent(ua string) 
func (r *Request) SetUserAgent(ua string)
```

AppendUserAgent appends to the old user agent. If old user agent is empty, it appends to the default UA.
SetUserAgent sets the user agent to the given value.

**Comment by okdave** [comment]
To be honest, I don't see the big downside in the status quo. What problem are we trying to solve?

**Comment by bradfitz** [comment]
Too late for Go 1.7 anyway.

**Comment by bradfitz** [comment]
The problem here is there are too many RoundTripper wrapper implementations which just set or append User-Agents.

Somebody should do an audit (including those inside gocloud) here in this bug before anything happens, though. Maybe it's not as bad as I remember.

**Comment by rsc** [comment]
@bradfitz roll into 'new HTTP client API' issue?

**Comment by bradfitz** [comment]
Closing, folding into #23707.
