### ISSUE TITLE
go/build: creating vendor/a/b/c implicitly vendors a and a/b too

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13832]
The AllowVendor logic in (*build.Context).Import checks for a directory called vendor/a/b when importing a package "a/b".  If only package "a/b/c" was vendored, the directory a/b must exist but will be empty, causing Import not to find the real (unvendored) package.

Import should check for non-empty directories.  This logic differs from the usual (non-vendored) case.

**Comment by bradfitz** [comment]
I'm going to mark this as Go 1.6, as it's blocking x/tools/cmd/bundle from being able to update the std copy of http2 from x/net.

**Comment by rsc** [comment]
Hmm. The vendor spec is very clear:

> If there is a source directory d/vendor, then, when compiling a source file within the subtree rooted at d, import "p" is interpreted as import "d/vendor/p" if that exists.

But obviously that's not good enough. I'm surprised this is the first we've noticed this. I can't decide if that's good. 

The a/b directory in your example _is_ non-empty: it contains c. It's not entirely clear what to do. I guess if there are no .go files at all (not even ones with exclusionary build tags) then we could ignore the directory. I'll try that.

**Comment by alandonovan** [comment]
FWIW, this was an effective fix:

```
--- a/src/go/build/build.go
+++ b/src/go/build/build.go
@@ -581,7 +581,7 @@ func (ctxt *Context) Import(path string, srcDir string, mode ImportMode) (*Packa
                                        vendor := ctxt.joinPath(root, sub, "vendor")
                                        if ctxt.isDir(vendor) {
                                                dir := ctxt.joinPath(vendor, path)
-                                               if ctxt.isDir(dir) {
+                                               if entries, _ := ctxt.readDir(dir); len(entries) > 0 {
```

**Comment by rsc** [comment]
@alandonovan, how does that work? Doesn't a/b contain a/b/c? Am I misunderstanding what readDir does? It looks like it calls ioutil.ReadDir. Maybe you overrided the default with a broken ctxt.ReadDir function set that doesn't return subdirectories?

**Comment by alandonovan** [comment]
See my EDIT: I don't yet know why it seems to work.

**Comment by alandonovan** [comment]
I still can't explain it.  Consider my patch retracted, and sorry for the noise.
