### ISSUE TITLE
x/tools/go/ssa/interp: fails to build on darwin

### ISSUE THREAD

**Issue by rudle** [golang/go#13831]
Hi there,

As of this commit[1], it's not possible to install all of the go tools at once on OSX. This is because the required form of `int pipe2(int pipefd[2], int flags);` is not exposed by the Darwin kernel. This is lamentable, but beyond our control.

```
$ go get golang.org/x/tools/cmd/...
# golang.org/x/tools/go/ssa/interp
../go/src/golang.org/x/tools/go/ssa/interp/external.go:244: undefined: syscall.Pipe2
```

```
uname -a
Darwin hostname 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

[1] https://github.com/golang/tools/commit/8463610142a5a3d2c03b8b57a35848d2c2fd9a55

**Comment by alandonovan** [comment]
Fixed by https://go-review.googlesource.com/#/c/18325/ (I hope).

**Comment by rudle** [comment]
The fix LGTM. Thanks for addressing @alandonovan.
