### ISSUE TITLE
minor error in "A Quick Guide to Go's Assembler"

### ISSUE THREAD

**Issue by notnot** [golang/go#13845]
In chapter Symbols, 5th paragraph:

Adding an offset to the name refers to that offset from the symbol's address, so a+4(SB) is four bytes past the start of foo.

should read:

Adding an offset to the name refers to that offset from the symbol's address, so foo+4(SB) is four bytes past the start of foo.

**Comment by ianlancetaylor** [comment]
Thanks, sent https://golang.org/cl/18307 .
