### ISSUE TITLE
os: Rename does not overwrite existing files on Plan 9

### ISSUE THREAD

**Issue by rsc** [golang/go#13844]
TestRenameOverwriteDest should not need an exception for Plan 9.

**Comment by 0intro** [comment]
This restriction is not the only difference between Plan 9 and other
operating systems in the os.Rename function.

For example, on Plan 9 you can only rename a file located
in the same directory.

Should we change os.Rename to handle both of these cases like other operating systems?

Renaming a file to a different directory could be done by copying the
file and removing the source file. However, if the source file is a directory,
the situation would be a bit more complex.

**Comment by rsc** [comment]
Everyone expects that there are limitations on when you can rename across
directories. Even Unix doesn't let you do that if directories are on
different file systems. But people do expect rename in a single directory
to work. I clarified in the docs.
