### ISSUE TITLE
vendor spec: clarify whether vendor check can return a package from a different workspace root

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13858]
It's unclear from the vendor spec whether the algorithm that finds the `vendor` directory should confine itself to the same workspace source directory (in the sense of `(*build.Context).SrcDirs()`) as the import declaration, or whether it should work across the entire logical package path name space.

The implementation in `go/build` looks only within the same source directory, which seems sensible to me, but we should specify the intention because it will affect the design of interfaces such as the forthcoming `go/types.Importer2`.

**Comment by rsc** [comment]
Yes, only the same source directory. Quoting the first words of the actual spec in golang.org/s/go15vendor:

> If there is a source directory d/vendor, then, when compiling a source file within the subtree rooted at d, ...
