### ISSUE TITLE
encoding/gob: Encode gives "encoder: message too big" when given a large map

### ISSUE THREAD

**Issue by mmp** [golang/go#13850]
OSX / go version go1.5.1 darwin/amd64

The repro case below creates a map that's a few GB big and then attempts to encode it to a file using Encode(). Encode() fails with a "message too big" error. (Presumably because the full size of the map is greater than 1<<30, which is the value of "tooBig" in the gob implementation.

I would expect the gob implementation to be able to handle a map that's larger than the maximum message size, since the individual elements being encoded are much smaller than the limit.

```
package main

import (
    "encoding/gob"
    "fmt"
    "io/ioutil"
    "log"
)

type File struct {
    A, B string
    V    int
}

func main() {
    f, err := ioutil.TempFile("", "foo")
    if err != nil {
        panic(err)
    }

    e := gob.NewEncoder(f)

    m := make(map[string][]*File)
    for i := 0; i < (1 << 22); i += 1 {
        fl := File{"00000000000000000000000000000000000000000000000",
            "11111111111111111111111111111111111111111", 42}
        var arr []*File
        for j := 0; j < 4; j += 1 {
            arr = append(arr, &fl)
        }
        m[fmt.Sprintf("%d", i)] = arr
        if i%(1<<20) == 0 {
            log.Printf("i = %d / %d", i, 1<<22)
        }
    }

    if err := e.Encode(m); err != nil {
        panic(err)
    }
}
```

**Comment by Wouterbeets** [comment]
I have the same issue, is there a work around?

**Comment by robpike** [comment]
Sorry but no. The model requires that a data item is transmitted atomically (although types may break the stream into submessages). Too hard to change.
