### ISSUE TITLE
range skipping elements of slice

### ISSUE THREAD

**Issue by BrianActon** [golang/go#13856]
I'm using Go 1.5 and I'm working in a Windows environment.
I have a slice of strings which I use to create a second copy. I range over the original slice and remove certain entries in the 2nd slice using append. The problem I'm having is that the range skips an entry in the original slice after the append which only operates on the 2nd slice.
After the append but before the end of the loop iteration, k has skipped 1 element ahead and  v == newSlice[i] but I expected v to remain the same as the end of the loop hasnt been reached yet.

      newSlice := fileIn   // fileIn is a slice of strings
      i := 0
      for k, v := range fileIn {
         fileFlag = cleanFile(v.Name())  // cleanFile returns 0, 1, or 2
         if fileFlag == 1 {
           fmt.Println("fileError = ", fileFlag, v.Name)
           break
         }
         if fileFlag == 2 {
           newSlice = append(newSlice[:i], newSlice[i+1:]...)  /* k and v at this point have moved to the next iteration */
           continue
         }
         i++
       }

**Comment by champioj** [comment]
Using `newSlice := fileIn` you create a new slice header, but both share the same backing array.
So when you change the value in the backing array of `newSlice`, it does change the value in `fileIn` too.

This blog post can help you: http://blog.golang.org/go-slices-usage-and-internals
Btw, for such question it's better to use [the forum](groups.google.com/forum/#!forum/golang-nuts)

**Comment by bradfitz** [comment]
See https://golang.org/wiki/Questions (sorry; we only use this issue tracker for bugs)
