### ISSUE TITLE
x/net/http2: delay sending request body in Transport if 100-continue is set

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13851]
In Go 1.6, the HTTP/1 client got Transport.ExpectContinueTimeout.

The http2 Transport should do the same. And ideally it should use the configuration value from the *http1.Transport, at least when used via the standard library.

Issue #13659 is about at least not getting confused by the 100-continue header responses from servers. This bug is about doing it properly.

/cc @bmizerany

**Comment by bradfitz** [comment]
@mdevan, in https://github.com/golang/go/issues/14391#issuecomment-202332260 you mentioned that you didn't think this was relevant for HTTP/2. Why not?

**Comment by mdevan** [comment]
I assumed that was the case from a [previous comment](https://github.com/golang/go/issues/14391#issuecomment-186489381) in the same thread. I also said "_if_ it is not relevant for HTTP/2" :-)

**Comment by bradfitz** [comment]
Sent https://golang.org/cl/23235
