### ISSUE TITLE
encoding/json: add note in  src/encoding/json/decode.go about exporting struct members

### ISSUE THREAD

**Issue by csawyerYumaed** [golang/go#13867]
file src/encoding/json/decode.go 
around the struct docs for the Unmarshall object (around line 39)
// NOTE: you most likely want to "export" your struct fields, to do that, make
//        sure the field name starts with an Uppercase character. 
//        see http://golang.org/ref/spec#Exported_identifiers for more information.

this is basically a drive-by "patch", to make the documentation more sane for go idiots having to wack on some broken code somwhere (i.e. me the go idiot wasting hours digging thru json.Unmarshal because I didn't know I had to "export" my struct.  I want other people to not have to waste as much time.

**Comment by ianlancetaylor** [comment]
Thanks, sent https://golang.org/cl/18394.
