### ISSUE TITLE
cmd/pprof: tool should nuke temporary directories when done

### ISSUE THREAD

**Issue by dsnet** [golang/go#13863]
Using ```go1.5```

Calling ```web``` on ```go tool pprof``` creates a temporary directory, but forgets to clean it up.

Currently, I see:
```
rawr@carbonite: /tmp $ ll pprof-*
pprof-258052144:
total 0

pprof-316027049:
total 0

pprof-394800818:
total 0

pprof-675261706:
total 0

pprof-871857163:
total 0

...
```

I expect to see:
```
rawr@carbonite: /tmp $ ll pprof-*
ls: cannot access pprof-*: No such file or directory
```

Probably just a missing defer in [cmd/pprof/internal/commands/commands.go](https://github.com/golang/go/blob/3bab4ef68da5334a1aac558ec7bee53f6bf15cfc/src/cmd/pprof/internal/commands/commands.go#L206-L217).

**Comment by bradfitz** [comment]
@dsnet, please finish the https://go-review.googlesource.com/#/c/18560/ review or fix/close otherwise?
