### ISSUE TITLE
Keyword: interface{}

### ISSUE THREAD

**Issue by qeremy** [golang/go#13869]
Hi Gophers,

I just want to propose something that could solve a problem for go-illiterates (like me).. :)

```go
// yes, interface is interface for usual devs
type IOWriter interface {
   Write(s string) uint
}
type IO struct {
   IOWriter // well..
}
```
```go
// but, wtf is that? whoops!! :)
// of course it is clear enough to get/use after some googling 
var m map[string]interface{}
```

Problem;

- One keyword for two purposes (use-cases)
- After keyword, "{}" required but not for these; `map[string]string`, `map[string]int`, `[]string` etc.
- Also this; `map[string]string{"foo"}` but `map[string]interface{}{"foo":123}`. Why not just; `map[string]interface{"foo":123}`
- It looks like not interface, but class interface, confusing me
- It is too long, I am an old man and it is f**kin'  tiring me :)
- It is really boring to write down each time long and long 
- Last: no more keyword else in English? (ok, just kidding)

Yes, I called it as "problem" but maybe not for you, I do not know :). I just want to make a suggestion you provide a way to avoid keyword ambiguity. Also, that should be suitable for a -minimalist- language concept.

Solution;

```go
// please add an alternative keyword as built-in, for example "mix" or "any"
var m map[string]mix

m := map[string]mix{"foo": 123}
```
I know, it could be used in a hack-some way below, but I would prefer using a built-in feature (also it is boring to import `mix` into used files or define each file;

```go
type mix interface{
}

var m map[string]mix
```

Thanks for reading, and perhaps implementing (yes, sure!).. :)

Note: Please do not not make us semi-happy like *PHP bosses* after and after years (yes, still we elephants have no `mixed` type).. (what? see: https://wiki.php.net/rfc/scalar_type_hints_v5)

**Comment by davecheney** [comment]
interface{} is not a keyword, it is an anonymous type declaration of an interface type with zero methods.

**Comment by ianlancetaylor** [comment]
This is not an issue, so I'm going to close it.  As @davecheney said, there aren't two uses cases, there is only one.  It just happens that any type satisfies an interface with no methods.

Note that we encourage people to use the issue tracker only for actual issues.  For questions and discussion, please see https://golang.org/wiki/Questions .  Thanks.

**Comment by qeremy** [comment]
As I said, It was just a something proposal but it is still confusing.
Thank you.
