### ISSUE TITLE
sync/atomic 386: 64-bit atomic operations panic when not 8-byte aligned

### ISSUE THREAD

**Issue by jtsylve** [golang/go#13868]
**What version of Go are you using (go version)?**
`go version go1.6beta1 linux/386`

**What operating system and processor architecture are you using?**
`Linux ubuntu32 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:48:35 UTC 2015 i686 i686 i686 GNU/Linux`

**What did you do?**
```go
package main

import "sync/atomic"

func main() {
	var a struct {
		_ uint32
		b uint64
	}
	atomic.AddUint64(&a.b, 1)
}
```

**What did you expect to see?**
No panic

**What did you see instead?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x808c77c]

goroutine 1 [running]:
sync/atomic.AddUint64(0x1830e0f4, 0x1, 0x0, 0x18318180, 0x183000d0)
	/home/joe/Downloads/go/src/sync/atomic/asm_386.s:112 +0xc
main.main()
	/home/joe/Desktop/test2.go:10 +0x41
exit status 2
```

**More Details**
In `sync/atomic/asm_386.s` we see that the 64 bit operations have the following preamble:
```go
MOVL	addr+0(FP), BP
TESTL	$7, BP
JZ		2(PC)
MOVL	0, AX // crash with nil ptr deref
```
We get an intentional panic if the pointer is not 8-byte aligned.

If this is unavoidable (which it may be due to the architecture) it should at least be documented, as it's not obvious.

Documentation aside, what guarantee do we have that any allocation will be 8-byte aligned on a 32-bit system?  I am able to fix the panic in my program by reordering the members of the struct, but I am just assuming that the allocation will always be allocated on 8-byte boundaries.  On 32-bit systems, it may only be reasonable to assume that it will be on a 4-byte boundary.

**Comment by cespare** [comment]
This is documented in the BUGS section at the very bottom of the page:

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned.

It's easy to miss, though.

**Comment by jtsylve** [comment]
Thanks @cespare.
