### ISSUE TITLE
net: UnixListener auto unlinks socket files behavior should be changeable

### ISSUE THREAD

**Issue by absolute8511** [golang/go#13877]
The unlink flag should be designed as changeable from outside to avoid auto unlink unix domain socket file. It can be useful while implementing the graceful restart. The graceful restart need the new process listen on the same file and then close the old one. If the old one auto unlink the socket file, it will cause the socket listened by the new process is not available from the client. 
The graceful restart can be found here https://github.com/facebookgo/grace

**Comment by dpiddy** [comment]
Should this be accomplished by making UnixListener.unlink public?

**Comment by absolute8511** [comment]
Maybe an option for auto unlink and a public method would be great. (just like FD_CLOEXEC)

**Comment by rsc** [comment]
Too late for new API.

**Comment by quentinmit** [comment]
See also #17131
