### ISSUE TITLE
net: LookupIP("My Local Node.local") doesn't work with Go 1.6

### ISSUE THREAD

**Issue by mikioh** [golang/go#13878]
https://github.com/golang/go/commit/bb8c2e19a7fe2ca2283eca44dba2047c9f4307fe introduces "unicast DNS name validation" into Lookup APIs and drops support for mDNS that was available in Go 1.5 and below on some platforms that have mDNS-capable stub resolver library in C such as OS X, Linux, FreeBSD.

**Comment by rsc** [comment]
Reverted that change.
