### ISSUE TITLE
why is "assign an interface{} with struct to interface{...}" illegal?

### ISSUE THREAD

**Issue by weiliming** [golang/go#13872]
package main

import "fmt"

type IPerson interface {
	GetName() string
}

type TTeacher struct {
	name string
	level int32
}

func (t *TTeacher) GetName() string {
     return t.name
}

func main() {
	var t = TTeacher {
		name: "xiaoming",
		level : 3,
	}
	var ei interface{} = t
	
	var person IPerson
	person = ei
	
	fmt.Printf("ei:%v\n", ei)
	fmt.Printf("person:%v\n", person)
}

get an error at "person = ei":
prog.go:26: cannot use ei (type interface {}) as type IPerson in assignment:
	interface {} does not implement IPerson (missing GetName method)

can go support this?

![image](https://cloud.githubusercontent.com/assets/9973753/12196231/0b932a3e-b638-11e5-81c4-ccd20aefc282.png)

**Comment by minux** [comment]
The GetName method is only defined for pointer receiver
on TTeacher, but ei contains t, which is a TTeacher, and
its method set won't contain any methods that are defined
for pointer receiver.

Please see https://golang.org/doc/faq#different_method_sets.

And note that we only use the issue tracker for bug reports,
not for general questions like this, please see
https://golang.org/wiki/Questions
for places to raise questions.
