### ISSUE TITLE
math/big: Typo in the documentation of Int.DivMod

### ISSUE THREAD

**Issue by TomCoates8161** [golang/go#13875]
The documentation for DivMod, in the big library, suggests that z.DivMod(x,y,w) sets z to the quotient q and w to the modulus m, where q and m satisfy
> m = x - y*q  with 0 <= m < |q|

I believe that this should read
> m = x - y*q  with 0 <= m < |y|

so that it agrees with the reference mentioned in the documentation for DivMod: Raymond T. Boute, “The Euclidean definition of the functions div and mod”. ACM Transactions on Programming Languages and Systems (TOPLAS), 14(2):127-144, New York, NY, USA, 4/1992. ACM press.

**Comment by ianlancetaylor** [comment]
I can't tell: is this a problem with the docs, or a problem with the code?

**Comment by TomCoates8161** [comment]
Code looks OK to me.

**Comment by rsc** [comment]
Yes, if the operation is q=x/y then clearly the remainder (sorry, modulus) must be < y, not < q. Thanks.
