### ISSUE TITLE
proposal: bytes, strings: add ReadBytes(byte) ([]byte, error), ReadString(byte) (string, error) to Reader

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#13889]
One of the use-cases of `byte.Reader` is parsing a binary format.
There are some formats use an unpredictable length structure such as NUL-terminated string.
Unfortunately, current API set doesn't treat  it well. 

For example:
```
br := byte.NewReader(data)

func decodeCString(br *bytes.Reader, data []byte) string {
  rest := data[br.Size()-br.Len():]

  i := bytes.IndexByte(rest, 0x0)
  if i == -1 {
    panic("invalid")
  }

  br.Seek(i+1, 1)

  return string(rest[:i])
}
```

I think `decodeCString` has 2 problems.

1. it still need to keep `data` variable.
2. it manually update internal state by `.Size`, `.Len` and `.Seek`.

I want to write it like this:
```
func decodeCString(br *bytes.Reader) string {
  bs, err := br.ReadBytes(0x0)
  if err != nil {
    panic("invalid")
  }

  return string(bs[:len(bs)-1])
}
```

I know some people prefer `bytes.Buffer` because of convenience, even if data is read only.
I want to discourage such a situation.

Same things are also applicable to `strings.Reader`.

Thank you.

hiro

**Comment by bradfitz** [comment]
Here's a simpler, faster version:

```go
func cstr(b []byte) string {
	if i := bytes.IndexByte(b, 0); i != -1 {
		return string(b[:i])
	}
	return ""
}
```

Notice that not only does it not need any changed to bytes.Reader, it also doesn't even need bytes.Reader.

And if you needed to parse these from a stream, you can use bufio.Reader.ReadBytes:

https://golang.org/pkg/bufio/#Reader.ReadBytes

I think there's nothing to do here.

**Comment by hirochachacha** [comment]
The problem in my mind is use with `binary.Read`.

https://github.com/golang/go/blob/master/src/debug/elf/file.go#L480-L508

> And if you needed to parse these from a stream, you can use bufio.Reader.ReadBytes:

I think so, but it is bigger than problem itself, I think. That's my point.

**Comment by hirochachacha** [comment]
>>And if you needed to parse these from a stream, you can use bufio.Reader.ReadBytes:

>I think so, but it is bigger than problem itself, I think. That's my point.

Sorry, I was mistaken.

**Comment by hirochachacha** [comment]
Thank you for commenting.
