### ISSUE TITLE
proposal: cmd/compile, runtime: provide ways to know supported platforms

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#13888]
Sorry, it's just an idea.

Like this:
```
$ go tool compile -showcontexts

linux-386-cgo
linux-386
linux-amd64-cgo
linux-amd64
....
```

In package:
```
package runtime

var Contexts = []string{
  "linux-386-cgo",
  "linux-386",
  ...
}
```
 
It's not only useful for "users" but "tools" like "go tool api" as well.

https://github.com/golang/go/blob/master/src/cmd/api/goapi.go#L40-L71

**Comment by minux** [comment]
I don't think runtime should provide such information.
It's better to make cmd/dist give the list and that is
#12270.

**Comment by bradfitz** [comment]
Yeah, dup of #12270
