### ISSUE TITLE
tour: Channels unnecessarily complicated

### ISSUE THREAD

**Issue by guillaumenel** [golang/go#13894]
Context: https://tour.golang.org/concurrency/2

This section is much harder to grasp than the others, as newcomer. The array slicing and values make it harder to comprehend. Original:
```
    a := []int{7, 2, 8, -9, 4, 0}
[...]
	go sum(a[:len(a)/2], c)
	go sum(a[len(a)/2:], c)
```

Using simpler array 1,2,3... and changing the following to reference using hard-coded lengths (or even just two different arrays) would make it much easier to understand the logic and derive what is happening based on the output.

```
func sum(a []int, c chan int) {
	sum := 0
	for _, v := range a {
		sum += v
	}
	c <- sum // send sum to c
}

func main() {
	a := []int{1, 2, 3, 4, 5, 6}

	c := make(chan int)
	go sum(a[3:], c)
	go sum(a[:3], c)
	x, y := <-c, <-c // receive from c

	fmt.Println(x, y, x+y)
}
```
The resulting output is then: "15 6 21"

Edit: Being nicer after reading Community Guidelines.

**Comment by kytrinyx** [comment]
I've submitted a CL that is more of a suggestion at this point than an actual fix. I think that making it clear up front to the reader what the code example is trying to accomplish (compute the sum of a slice in parallel) will make it easier to see what the `a[:len(a)/2]` stuff means and why it is there.
