### ISSUE TITLE
cmd/compile: spurious writebarriers emitted for global funcs

### ISSUE THREAD

**Issue by DanielMorsing** [golang/go#13901]
gc emits write barriers when a global function is assigned, even though it is unnecessary

reproducer:
```
package foo

type t struct {
	x func() *t
}

func f() *t {
	g := new(t)
	g.x = f
	return g
}
```
Built with `go build -gcflags '-d wb' blah.go`, outputs `./blah.go:9: write barrier`

I don't think there is any correctness issues with emitting the WB and I doubt the performance suffers for it, but I did get a spurious warning when doing some runtime dev.

**Comment by aclements** [comment]
Yes, you're right that it's safe to omit this write barrier, since we only care about heap -> heap pointer changes. We have various conditions for omitting write barriers if the slot is not in the heap, but I'm not aware of conditions for omitting write barriers if the pointer being written isn't a heap pointer. @randall77?

**Comment by DanielMorsing** [comment]
Looks like it's a case of adding a case for PFUNC class nodes in this function https://golang.org/src/cmd/compile/internal/gc/walk.go#L2176

**Comment by randall77** [comment]
Yes, that sounds right.
@aclements: We already have a few conditions on the pointer being written.  nil, address of global, address of stack, ...

**Comment by aclements** [comment]
Yes, I see. Does this not fall under the "address of global" exception because we haven't split up the two words at this point?

**Comment by randall77** [comment]
A PFUNC eventually expands to the address of a global (which is why it is ok), but it is represented differently at this point in the compiler.
