### ISSUE TITLE
x/crypto/ssh: no example for server with public key authentication

### ISSUE THREAD

**Issue by mdlayher** [golang/go#13902]
An example SSH server that uses password authentication is provided, but I can't seem to find any official examples on how to use public key authentication with an `x/crypto/ssh` SSH server.

Password example:
https://godoc.org/golang.org/x/crypto/ssh#example-NewServerConn

Perhaps I'm missing something, but adding an example to demonstrate SSH public key authentication would be incredibly helpful.  Thanks in advance!

**Comment by mdlayher** [comment]
Found this article which details it a bit: https://blog.gopheracademy.com/advent-2015/ssh-server-in-go/.

I could possibly submit a changelist once I dig through this and verify it works as needed.

**Comment by davecheney** [comment]
SGTM

**Comment by odeke-em** [comment]
I've mailed https://go-review.googlesource.com/#/c/29374.

**Comment by mdlayher** [comment]
Thank you very much, @odeke-em !
