### ISSUE TITLE
undefined: base64.RawURLEncoding

### ISSUE THREAD

**Issue by vyachin** [golang/go#13900]
For fix this error need change this method
func (enc *Encoding) WithPadding(padding rune) *Encoding {
	enc.padChar = padding
	return enc
}

**Comment by dominikh** [comment]
The compile error you're getting (#13899) has absolutely nothing to do with your code change, so any change in behaviour is accidental and cannot be attributed to the patch. Odds are you've simply been testing with two different versions of Go, one of which has RawURLEncoding, and an older version that does not.

**Comment by vyachin** [comment]
I am sorry, my mistake
