### ISSUE TITLE
tour: when content is updated, reset snippets in local storage

### ISSUE THREAD

**Issue by adg** [golang/go#13918]
While working on the tour I noticed that my browser caches code snippets that I have changed. This is a nice feature, but it breaks when we change the content (by renumbering pages or changing the code snippets themselves).

One easy fix for this would be to cache user snippets keyed by a hash of the original content. That way if the content changes, any saved code won't be loaded for that snippet.

@campoy - are you able to do this? or point me in the right direction to do it myself?

**Comment by broady** [comment]
I think this is fixed in http://golang.org/cl/17407

**Comment by adg** [comment]
I guess I missed that. Dupe of #13252
