### ISSUE TITLE
x/tools/go/gcimporter15: backport changes from std lib version

### ISSUE THREAD

**Issue by griesemer** [golang/go#13910]
gcimporter15 needs to be updated to incorporate the latest changes to std lib gcimporter.

**Comment by bradfitz** [comment]
Is this done? I thought I saw some similar-sounding CLs fly by.

**Comment by griesemer** [comment]
@bradfitz Indeed. Forgot to mention https://go-review.googlesource.com/18772,  https://go-review.googlesource.com/18771, and https://go-review.googlesource.com/18770 which together fixed this issue.
