### ISSUE TITLE
panic: time: missing Location in call to Date

### ISSUE THREAD

**Issue by dbaroncelli** [golang/go#13922]
I was experiencing this issue with Go 1.5.1 and I am still experiencing with Go 1.5.2

This is my code:
```
60  func DateAddDays(sqlDate string, days int) string {
61     t, _ := time.Parse("2006-01-02", sqlDate)
62     res := t.AddDate(0, 0, days)
63     return res.Format(SqlDateFormat)
64   }
```

line 62 fires this panic:

```
panic: time: missing Location in call to Date

goroutine 48877 [running]:
time.Date(0x1, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/time/time.go:1023 +0x91
time.Time.AddDate(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x7f2000000000, 0x0)
	/usr/local/go/src/time/time.go:658 +0x115
trenit/utils.DateAddDays(0xc82527bb00, 0x12, 0x1, 0x0, 0x0)
	myscript.go:62 +0xac
```

this function runs thousands of times, but the panic only happens very rarely, in the order of 1 every 10,000 times

very strange error!

**Comment by bradfitz** [comment]
Check your error from time.Parse. Fix any data races (http://blog.golang.org/race-detector). Ask questions at https://golang.org/wiki/Questions

I don't see an actionable bug here.

**Comment by dbaroncelli** [comment]
you are absolutely right!
the error is due to the fact that the parsed location has a nil value
so it should be investigated whether the time.Parse() function has returned an error, and what the string-to-be-parsed was like in such case
Thanks!
