### ISSUE TITLE
x/tools/cmd/godoc: should not display vendor packages

### ISSUE THREAD

**Issue by dsnet** [golang/go#13929]
Currently, if someone goes to https://tip.golang.org/pkg/ and scroll to the bottom, they see:
![screenshot from 2016-01-12 17 20 51](https://cloud.githubusercontent.com/assets/6354026/12282187/0ab25952-b951-11e5-95da-af287a97cd58.png)

Instead, godoc should hide this information.

Close this if people believe vendor folders *should* actually be displayed on the package documentation page.

**Comment by ianlancetaylor** [comment]
CC @adg
