### ISSUE TITLE
crypto/ecdsa: the sign method on ecdsa.PrivateKey does not hash

### ISSUE THREAD

**Issue by danielchatfield** [golang/go#13938]
The [sign function](https://github.com/golang/go/blob/70ee525261f7d8adbcf58c2cf54efb7e7efb1c82/src/crypto/ecdsa/ecdsa.go#L147) in `ecdsa` states the following: 

>Sign signs an arbitrary length hash (which should be the result of hashing a
larger message) using the private key, priv. It returns the signature as a
pair of integers. The security of the private key depends on the entropy of
rand.

However the [sign method](https://github.com/golang/go/blob/70ee525261f7d8adbcf58c2cf54efb7e7efb1c82/src/crypto/ecdsa/ecdsa.go#L70) on `ecdsa.PrivateKey` uses the msg directly rather than hashing it (and thus ignores the `crypto.SignerOpts`).

Either the description of the sign function should be changed, or the sign method should perform hashing. I'm not sure what the motivation was for the particular type signature of the sign method but taking a `crypto.SignerOpts` that is ignored is misleading.

**Comment by agl** [comment]
The argument is called `hash` and the description says that it "should be the result of hashing a
larger message". Can you suggest a description that that's clearer that the input should already be hashed?

**Comment by danielchatfield** [comment]
@agl 

The problem is that the [sign method](https://github.com/golang/go/blob/70ee525261f7d8adbcf58c2cf54efb7e7efb1c82/src/crypto/ecdsa/ecdsa.go#L70) on the PrivateKey type doesn't pass in a hash.

**Comment by agl** [comment]
Oh, I see. Fair point; that's generally a bit unclear for `Signer` as a whole and could be improved.

**Comment by bradfitz** [comment]
@agl, want to send a documentation CL, or do you want to use or pass opts?
