### ISSUE TITLE
net/http: net/http.(*http2pipe).Write: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by karmeye** [golang/go#13932]
Using latest code in the master branch (771da53958618108c8ea56a69412eaeaae79e0ae)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x48d65b]

goroutine 48 [running]:
net/http.(*http2pipe).Write(0xc82a437d60, 0xc8201540a0, 0x98, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:2170 +0x1bb
net/http.(*http2clientConnReadLoop).processData(0xc8203e23c0, 0xc8207c9590, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:5359 +0x1a1
net/http.(*http2clientConnReadLoop).run(0xc8203e23c0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:5129 +0x4a4
net/http.(*http2ClientConn).readLoop(0xc8203929a0)
	/usr/local/go/src/net/http/h2_bundle.go:5072 +0x162
created by net/http.(*http2Transport).NewClientConn
	/usr/local/go/src/net/http/h2_bundle.go:4601 +0xd7d
```

Possibly this occurred just after numerous errors returned by http.NewRequest or client.Do: 

`Post https://172.31.29.132:8001/hello: connection error: COMPRESSION_ERROR`

**Comment by bradfitz** [comment]
I have a theory about this one, but still investigating.

Which HTTP/2 server are you running this against? Is it Go or nginx or Apache or .... ?

My theory involves a specific frame order arriving. I know there's a bug in the client to cause it to crash (your stacktrace above), but I'm not sure whether there's also a bug in the Go server.

**Comment by bradfitz** [comment]
Also, how did the compression error occur?

**Comment by bradfitz** [comment]
Can you update to tip and reproduce again with `GODEBUG=http2debug=2` set in your environment and include the debug logs of the frames received?

**Comment by bradfitz** [comment]
The above commit should at least fix the crash. I'm going to mark this closed, at least until I hear more details on how to reproduce.
