### ISSUE TITLE
net: TestSpecialDomainName can hang indefinitely

### ISSUE THREAD

**Issue by mundaym** [golang/go#13939]
The DNS test [TestSpecialDomainName](https://github.com/golang/go/blob/00c0a3a677d8720123b646bb8efa3bfa1e36a8a1/src/net/dnsclient_unix_test.go#L76) can hang indefinitely because it sends a DNS request using UDP and waits for a response without specifying a timeout.

The easiest fix would be to add a timeout to the [call to exchange](https://github.com/golang/go/blob/00c0a3a677d8720123b646bb8efa3bfa1e36a8a1/src/net/dnsclient_unix_test.go#L83) so that the test fails quickly with a nice error message if the request gets lost or is ignored.  For example:

    msg, err := exchange(server, tt.name, tt.qtype, 3 * time.Second)

**Comment by bradfitz** [comment]
You want to send a change, or do you want us to?

**Comment by mundaym** [comment]
I'm happy to send a change.

**Comment by mundaym** [comment]
CL sent https://go-review.googlesource.com/18661

**Comment by dpiddy** [comment]
Ref https://github.com/golang/go/issues/13295

Might be nice to not involve the network for these at some point.
