### ISSUE TITLE
runtime: fatal errors on dragonfly

### ISSUE THREAD

**Issue by mikioh** [golang/go#13947]
The recent logs display the following:

- fatal error: runtime: stack split at bad time
  http://build.golang.org/log/ae9f24a66a50d66cf8ca2de2a0864d26e3a16daa
- fatal error: fatal error: unexpected signal during runtime execution
  [signal 0xb code=0x1 addr=0xffffffffc8200011 pc=0xc820547baf]
  http://build.golang.org/log/b207aed2f1628f1ad8828de714b33e2ebdfa25a9
- fatal error: unlock of unlocked lock
  fatal error: unexpected signal during runtime execution
  panic during panic
  [signal 0xb code=0x1 addr=0x0 pc=0xc8203fe510]
  http://build.golang.org/log/fe324eb68c4836072136d30f41cb5d791ae27b6e

**Comment by bradfitz** [comment]
It seems that dragonfly was still happy until @ianlancetaylor's recent a7cad52e04dd1890420452b38563997930edb2ca (runtime: preserve signal stack when calling Go on C thread).

Ian, can you take a look?

**Comment by ianlancetaylor** [comment]
I'm not sure I would single out that particular change.  After that change, the builder consistently timed out and looked flaky.  The first time I see an error other than a timeout or a SIGTRAP signal was in http://build.golang.org/log/d8be87e27545cca84e8d0721c7b663ddb15ac7e4 for the change  https://github.com/golang/go/commit/d75acd67eccbfe6f03b6474baea3b569cd0135d6 (which was clearly not the cause).  So I think the error could have been introduced anywhere between those two changes, which is unfortunately a fair amount of ground.

**Comment by ianlancetaylor** [comment]
I've been trying to figure out this by deduction and by looking at the source code, but no luck.  gomote doesn't support DragonFly.  @mikioh is there a way I can ssh on to your Dragonfly system and run tests?

**Comment by mikioh** [comment]
@ianlancetaylor,

Sorry I cannot provide you with easy access to my netbsd/dragonfly VMs. I'm happy to try your patch for investigation if you can send it me off-list.

**Comment by ianlancetaylor** [comment]
@mikioh I don't have a patch.  I don't understand how these errors are possible.  I need to have a system that I can use to investigate the problem interactively.

**Comment by kaey** [comment]
62c280a - builds ok
a7cad52 - fatal error: unexpected signal during runtime execution
I've emailed credentials for a dragonfly-current server to @ianlancetaylor

**Comment by mikioh** [comment]
Thanks. I think I've found out the root cause of this issue: https://go-review.googlesource.com/#/c/18715.

**Comment by kaey** [comment]
@mikioh All tests passed with your patch applied. Thanks.
```
% uname -a
DragonFly kulikov-dragonfly.naukanet.ru 4.5-DEVELOPMENT DragonFly v4.5.0.377.g8b5a57-DEVELOPMENT #1: Wed Jan 20 15:49:06 MSK 2016     root@kulikov-dragonfly.naukanet.ru:/usr/obj/usr/src/sys/X86_64_GENERIC  x86_64
```
