### ISSUE TITLE
tour: Exercise: Equivalent Binary Trees

### ISSUE THREAD

**Issue by mavenAtHouzz** [golang/go#13958]
Context: https://tour.golang.org/concurrency/8

The type Tree should be described as well for completing the exercise, instead of I having to google and check the page https://godoc.org/golang.org/x/tour/tree

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
The type Tree is described in the previous slide.

I'll add a link to https://godoc.org/golang.org/x/tour/tree#Tree though.

**Comment by campoy** [comment]
CL sent https://go-review.googlesource.com/18672
