### ISSUE TITLE
doc: Windows default build from source behavior is CGO enabled but docs don't mention C compiler dependency

### ISSUE THREAD

**Issue by srinathh** [golang/go#13954]
I was installing Go from source on a new clean Windows installation today and the installation broke because the default build behavior is CGO enabled whereas Windows doesn't come with a C compiler installed by default. This is not documented in the [installing from source](https://golang.org/doc/install/source) page.

While the fix is pretty simple (either disable CGO via an environment flag or install a C compiler), this should be documented in the install from source doc. A known working compiler should also be recommended if we want CGO enabled like we used to earlier.

I installed TDM-GCC as I seem to recall Go 1.4 build-steps used to recommend it and got a working installation but I also seem to recall Go used to recommend a different C compiler installation for windows in earlier days.

**Comment by davecheney** [comment]
This information, https://github.com/golang/go/wiki/WindowsBuild, used to
be referenced from the install page. The information was moved to the wiki
because it was changing at an incompatible rate.
