### ISSUE TITLE
proposal: new import syntax

### ISSUE THREAD

**Issue by xaircore** [golang/go#13955]
When you import the module, write the name of the module without the quotes. It looks more natural, because in the future, this module is used in code without the quotes.

Before :
```
package main

import "fmt"

func main() {
	fmt.Println("Hello, playground")
}
```
After :
```
package main

import fmt

func main() {
	fmt.Println("Hello, playground")
}
```

**Comment by davecheney** [comment]
> It looks more natural, because in the future, this module is used in code without the quotes.

The syntax of the language is fixed with the Go1 contract. _more natural_ is not a sound justification for a change in the language, especially a cosmetic one.

**Comment by xaircore** [comment]
@davecheney But it can also be changed in the Go2. This replacement will help make using IDE rename the module in all parts as a file and the project in general. Also, the change will be very helpful for static analyzers

**Comment by bradfitz** [comment]
We have static analyzers and safe symbol-aware global renaming already. This adds nothing.

**Comment by minux** [comment]
I think you've confused package name with import path.

When importing a package, the string used is the import
path, and when using the imported package, the identifier
used is the package name. In general, they can be totally
unrelated.

For example, it's possible to import "abc/def/v1" and the
package name be def.

The import path doesn't have to be a Go identifier, so
removing the quotes will make the syntax more complicated
and irregular.
