### ISSUE TITLE
encoding/json Unmarshal don't support string to float64 like ".17" 

### ISSUE THREAD

**Issue by qhsong** [golang/go#13953]
When I use json  Unmarshal a string to float64, the string like ".17",  and I tag the field  like this `json:,string`, and then the unmarshal will error cause it can't parse this to number. But the strconv.ParseFloat can parse this number.

So can you fix this problem?add ".17" into your regex and can make ParseFloat to parse this to 0.17

**Comment by cespare** [comment]
`.17` is not a valid JSON number. See http://www.json.org/ for more information.

**Comment by qhsong** [comment]
Yes, I just notice that, but `".17"` is a string, not a number.
json example: 
{
   "price":".17"
}

Does we need to support this json?

**Comment by cespare** [comment]
The documentation for the `,string` option in `encoding/json` says:

> The "string" option signals that a field is stored as JSON inside a JSON-encoded string.

So even if you're using the `,string` option, your string value has to be JSON-encoded, and the string `".17"` is not a valid JSON encoding.

You should unmarshal that field as a string and then you can do whatever parsing is necessary for that format.

Please see https://github.com/golang/go/wiki/Questions for some forums where you will be able to get more feedback if you'd like to discuss further.

**Comment by qhsong** [comment]
Ok,thanks for your help.I didn't read this wiki carefully.At first, I think maybe it is a bug, So I commit this issue.Thanks for your help.
