### ISSUE TITLE
tour: typo in description of "Choosing a value or pointer receiver"

### ISSUE THREAD

**Issue by shayneski** [golang/go#13951]
Context: http://tour.golang.org/methods/8

Last sentence has an unnecessary 'to': In general, all methods on a given type ~~to~~ should have either value or pointer receivers, but not a mixture of both.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by campoy** [comment]
Thanks for reporting!

CL sent https://go-review.googlesource.com/18670
