### ISSUE TITLE
runtime: print signal name, not number, for fatal signal error

### ISSUE THREAD

**Issue by perillo** [golang/go#13969]
Currently, after a fatal error caused by an unexpected signal during runtime execution, the runtime prints, as an example:
    `[signal 0xb code=0x80 addr=0x0 pc=0x406230]`

Since the runtime knows about signal numbers, it should print the signal name instead of the signal number.

See https://groups.google.com/forum/#!topic/golang-nuts/_FYWG3oU6X8

**Comment by odeke-em** [comment]
@ianlancetaylor I just wanted to get your confirmation that it is okay to fix this or does anyone think this breaks compatibility with older versions of Go? I am asking because I'd like to spin up a CL for this.

**Comment by ianlancetaylor** [comment]
@odeke-em It is OK to fix this.  Thanks.

**Comment by odeke-em** [comment]
Cool, thanks for the ACK.
