### ISSUE TITLE
go/parser: a /* */ file comment immediately preceding package decl is lost

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13960]
See http://play.golang.org/p/jFoDNNrB9y

I would expect a file that starts with
```
    /*a*/package main
```
to have an ast.File.Doc comment of "a", but it has "".

Adding a newline before 'package' causes the File.Doc comment to become "a\n", as it should.

**Comment by griesemer** [comment]
The comment is not lost as http://play.golang.org/p/Zl0pDK6KIV (click on Format) proves.

This is working as intended. The doc string comes from comments on the immediately preceding lines of a declaration. I don't see any reason to make this any more complicated. It also has worked for several years now w/o anybody complaining.

**Comment by alandonovan** [comment]
Fair enough.  My mindset was warped by another (real) bug that I was in the middle of debugging when I found this.
