### ISSUE TITLE
x/crypto/pbkdf2: move to standard library

### ISSUE THREAD

**Issue by alexmullins** [golang/go#13979]
For archive/zip to support reading/writing encrypted volumes (see #12081) it needs pbkdf2 to derive encryption and authentication keys from a password. The package x/crypto/pbkdf2 would need to be moved into the standard library.

**Comment by minux** [comment]
Perhaps it's better to have a x/exp/archive/zip (or x/compress/archive/zip
in a new subrepo) for handling encrypted zip files.

**Comment by dsnet** [comment]
Another possibility is to vendor the pbkdf2 package similar to how [hpack](https://github.com/golang/go/tree/master/src/vendor/golang.org/x/net/http2/hpack) is currently done.

**Comment by alexmullins** [comment]
It is a small package so moving to /internal or straight copying over works.

**Comment by ALTree** [comment]
I don't see this being moved to the standard library just to enable encrypted archives support in archive/zip; vendoring (or just the copy-pasting the needed functionalities) seem more likely; this can be done as a part of the work for #12081 (archive/zip: support for encrypted archives) and it can be tracked there, so I think we can safely close this issue.
