### ISSUE TITLE
cmd/link: UPX doesn't run on 64bit elf binaries

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#13974]
As the title says, upx does't run on Go 64bit elf binaries and exits with:

    upx: exe-name: EOFException: premature end of file

**Comment by OneOfOne** [comment]
I submited a patch @ https://go-review.googlesource.com/18690 (first time using the new Gerrit).

The linker already handles ELF32 headers, so I extended it to ELF64.

**Comment by ebfe** [comment]
For reference:
https://groups.google.com/forum/#!topic/golang-nuts/UtrMwo7zM7M
https://github.com/pwaller/goupx

**Comment by steelbrain** [comment]
:+1: Great
