### ISSUE TITLE
bug: tabwriter can't format wide characters correctly

### ISSUE THREAD

**Issue by WeiZhang555** [golang/go#13989]
Mainly for CJK(Chinese-Jananese-Korean) ideograph words, for example, this is a short example test case:
```
package main

import (
    "fmt"
    "io"
    "text/tabwriter"
)

type myWriter struct {
    io.Writer
}

func (w myWriter) Write(p []byte) (n int, err error) {
    fmt.Printf("%s", string(p))
    return len(p), nil
}

func main() {
    myw := myWriter{}

    tw := tabwriter.NewWriter(myw, 10, 1, 3, ' ', 0)
    str := "hello\tthis\tis\ta\ttest\tfrom\twei\n"
    str1 := "你好\thello\t世界\tworld\t。\t再见\t：）\n"

    fmt.Fprintf(tw, str)
    fmt.Fprintf(tw, str1)
    tw.Flush()
}
```

The printed result will be  really messy:
![image](https://cloud.githubusercontent.com/assets/1203611/12383796/2ca6a610-bde5-11e5-9158-427cbbdac04f.png)

I search the Golang docs, it will assume every unicode have same width, but for most ideograph words it is 2 columns not 1.

I wrote a modified tabwriter for formatting CJK words correctly, and I hope to upstream it to Golang, before that I want to know what you are thinking about this.

The modified tabwriter can be found here [WeiZhang555/tabwriter](https://github.com/WeiZhang555/tabwriter). Thank you!

**Comment by WeiZhang555** [comment]
Test result of my modified tabwriter:
![image](https://cloud.githubusercontent.com/assets/1203611/12383878/3a62b54a-bde6-11e5-87c1-4af036504cf3.png)

**Comment by bradfitz** [comment]
Dup of #12073

**Comment by griesemer** [comment]
@WeiZhang555 Can you send me a CL that shows the changes you made to make this work? Please comment via #12073 . Thanks.

**Comment by WeiZhang555** [comment]
@griesemer 
OK, I will do that. This is my first time trying to send code to Go community, so I need to follow the instruction here https://golang.org/doc/contribute.html right?

**Comment by griesemer** [comment]
@WeiZhang555 Yes, these are the guidelines. But I can also look at the other link you sent. Please note, this is not an urgent issue for us at the moment. Thanks.
