### ISSUE TITLE
x/mobile: do away with app.Main boilerplate

### ISSUE THREAD

**Issue by gordonklaus** [golang/go#13988]
The purpose of app.Main is to ensure that main.main runs on "the main thread" on certain platforms.  Couldn't this also be achieved by having gomobile inject initialization code into the code it is compiling?

It's just a shame that every mobile app currently needs an extra level of indentation in func main.  It adds unnecessary complexity, makes you wonder "what kinds of operations can I do in main vs in the app.Main callback?".  It makes mobile apps feel like second-class citizens.

**Comment by rakyll** [comment]
I proposed that we should minify the verbosity in the main package a while ago as well.

main.main is invoked lazily on mobile platforms, it is more trivial to remove the boilerplate. I am not sure how it could effect the initialization on "desktop" mobile apps.

/cc @crawshaw @hyangah

**Comment by rakyll** [comment]
And @nigeltao.

**Comment by crawshaw** [comment]
The problem is OS X, where Cocoa wants to use the first thread acquired by the process for its event pump. If you have a way to make "go build" work on OS X without app.Main, let's remove it, but it is not a feature I want to lose.

**Comment by gordonklaus** [comment]
@crawshaw Is it just OS X, not also iOS?

Could it be as simple as automatically injecting this file into the build?
```
package main

import "runtime"

func init() {
    runtime.LockOSThread()
}
```

**Comment by mdempsky** [comment]
@gordonklaus One potential flaw with that solution is runtime.LockOSThread is not recursive (at least currently).  So if the main goroutine then calls some function that uses runtime.LockOSThread() + runtime.UnlockOSThread(), the OS thread will end up unlocked.

**Comment by crawshaw** [comment]
@gordonklaus that's not enough, on OS X you need that code and you need to call ```[NSApp run]``` from that thread. That call blocks forever, so it needs to be inside the main function. Hence app.Main.

**Comment by gordonklaus** [comment]
@crawshaw I see.

I think app.Main can still be avoided.  It will just require some source manipulation, rewriting main.main.  Maybe I'll take a crack at it tomorrow.  Any advice is more than welcome :smile:
