### ISSUE TITLE
path/filepath: TestEvalSymlinksCanonicalNames is broken on Windows

### ISSUE THREAD

**Issue by jucie** [golang/go#13980]
What version of Go are you using (go version)?
go version go1.6beta2 windows/amd64

What operating system and processor architecture are you using?
OS Name:                   Microsoft Windows 8 Single Language
OS Version:                6.2.9200 N/A Build 9200
Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~2400 Mhz

What did you do?
cd go\src
all.bat

What did you expect to see?
A clean build & test output.

What did you see instead?
--- FAIL: TestEvalSymlinksCanonicalNames (0.02s)                                                                            
        path_windows_test.go:161: EvalSymlinks("C:\\\\USERS\\\\JUCIE\\\\APPDATA\\\\LOCAL\\\\TEMP\\\\EVALSYMLINKCANONICAL102278141\\\\TEST"
) returns "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\EVALSYMLINKCANONICAL102278141\\\\test", but should return "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\evalsymlinkcanonical102278141\\\\test"                                                                
        path_windows_test.go:161: EvalSymlinks("C:\\\\USERS\\\\JUCIE\\\\APPDATA\\\\LOCAL\\\\TEMP\\\\EVALSYMLINKCANONICAL102278141\\\\TEST\
\DIR") returns "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\EVALSYMLINKCANONICAL102278141\\\\test\\\\dir", but should return "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\evalsymlinkcanonical102278141\\\\test\\\\dir"                                                 
        path_windows_test.go:161: EvalSymlinks("C:\\\\USERS\\\\JUCIE\\\\APPDATA\\\\LOCAL\\\\TEMP\\\\EVALSYMLINKCANONICAL102278141\\\\TESTI
NG_LONG_DIR") returns "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\EVALSYMLINKCANONICAL102278141\\\\TESTING_LONG_DIR", but should 
return "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\evalsymlinkcanonical102278141\\\\testing_long_dir"                            
        path_windows_test.go:161: EvalSymlinks("C:\\\\USERS\\\\JUCIE\\\\APPDATA\\\\LOCAL\\\\TEMP\\\\EVALSYMLINKCANONICAL102278141\\\\TEST2
") returns "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\EVALSYMLINKCANONICAL102278141\\\\TEST2", but should return "C:\\\\Users\\\\jucie\\\\AppData\\\\Local\\\\Temp\\\\evalsymlinkcanonical102278141\\\\TEST2"                                                             
FAIL                                                                                                                        

It appears to me EvalSymlinks works as it should, but the test says it doesn't. The test is broken. To mimic Windows comparison semantics, the test comparison should be case insensitive, because Windows filesystem is not case sensitive. Both "C:\\USERS\\JUCIE" and "C:\\Users\\Jucie" refer to the same file.

[buildAndTestOutput.txt](https://github.com/golang/go/files/92865/buildAndTestOutput.txt)

**Comment by ianlancetaylor** [comment]
CC @alexbrainman

**Comment by alexbrainman** [comment]
@jucie, I am really puzzled here. Everything looks fine to me. You would have to try and understand why it is failing on your system (because you can easily reproduce this failure). I would try and add fmt.Printf calls in evalSymlinks in symlink_windows.go. I suspect toLong function does not convert C:\\USERS\\JUCIE\\APPDATA\\LOCAL\\TEMP\\EVALSYMLINKCANONICAL102278141\\TEST into C:\\Users\\jucie\\AppData\\Local\\Temp\\evalsymlinkcanonical102278141\\test (and similar for other tests).

If you comment out defer os.RemoveAll(tmp) in TestEvalSymlinksCanonicalNames, you should be able to see real files / directories left over after the test. What is real directory name: C:\\USERS\\JUCIE\\APPDATA\\LOCAL\\TEMP\\EVALSYMLINKCANONICAL102278141\\TEST or C:\\Users\\jucie\\AppData\\Local\\Temp\\evalsymlinkcanonical102278141\\test ?

What is your file system type on the disk C: ? Is it NTFS?

Thank you.

Alex

**Comment by jucie** [comment]
Hi, Alex. I did as you suggested. I didn't manage to put fmt.Println inside evalSymlinks due to compilation dependencies (fmt package is not ready at that point in time). But I used bare println to the same effect:
[symlink_windows.go.txt](https://github.com/golang/go/files/94403/symlink_windows.go.txt)

The output goes like this:
[outputWithPrintln.txt](https://github.com/golang/go/files/94409/outputWithPrintln.txt)

I commented out the instruction defer os.RemoveAll(tmp) in TestEvalSymlinksCanonicalNames as well and the result is lowercase:

jucie@PLUTO C:\lixo
> dir C:\USERS\JUCIE\APPDATA\LOCAL\TEMP
 Volume in drive C has no label.
 Volume Serial Number is 8470-AC8B

 Directory of C:\USERS\JUCIE\APPDATA\LOCAL\TEMP

2016-01-18  10:49 AM    <DIR>          .
2016-01-18  10:49 AM    <DIR>          ..
2016-01-18  09:58 AM    <DIR>          evalsymlinkcanonical330536169

Then, I wrote a little C program to call Windows GetLongPathName function, as the Go code does inside function toLong:
[GetLongPathName.c.txt](https://github.com/golang/go/files/94411/GetLongPathName.c.txt)

And so, I used thereafter the resulting executable to ask Windows about what would be the long path for the just created directory:
[GetLongPathNameOutput.txt](https://github.com/golang/go/files/94416/GetLongPathNameOutput.txt)

The result got me by surprise: GetLongPathName function always returns directory EVALSYMLINKCANONICAL330536169 in uppercase letters.

The file system I use is the regular file system in nearly every Windows box, NTFS.

I hope that can bring some light to the issue. Feel free to contact me if I can be of any help, Alex.

**Comment by bradfitz** [comment]
A bug with Windows behaving oddly and nobody has suspected anti-virus messing things up yet?

**Comment by jucie** [comment]
Nice guess, Brad. In Windows that kind of software use to interfere in everything.
But no, I don't have anti-virus installed and as far as I know this computer is virus free.

**Comment by bradfitz** [comment]
Okay, had to ask. 9/10 times I ask that I get lucky and that's the answer. :)

**Comment by jucie** [comment]
Good news here. I can explain what happens. Not sure about what would be the best solution, though.

As you know, Windows is this idiosyncratic beast. I learned the function GetLongPathName has a peculiarity: it tries to convert the casing of directories and filenames, but the rules are a little weird. Let's perform a little test. Please keep at hand my utility to invoke GetLongPathName function and create a temporary directory for us to tinker with:

> mkdir c:\trash

Enter into that directory and create yet another, using a short name, like this:

> mkdir short

Now we can call GetLongPathName to see the results:

> GetLongPathName.exe c:\trash\short
14
c:\trash\short

Let's pass the same path to GetLongPathName, all uppercase this time:

> GetLongPathName.exe C:\TRASH\SHORT
14
C:\trash\short

Do you see? The function brings the path to the correct casing, as it was created. Great.
Now, let us create another directory, still inside our trash directory, this time with a little longer name:

> mkdir aLongName

And let's call GetLongPathName again, first with lowercase letters, and then with uppercase:

> GetLongPathName.exe c:\trash\aLongName
18
c:\trash\aLongName

> GetLongPathName.exe C:\TRASH\ALONGNAME
18
C:\trash\ALONGNAME

Do you see? The function didn't changed the casing like it did when we used a short name. The behavior changed due to the directory name length. Can't you believe? I understand your pain.

So, my friends, that weird behavior alters the test results, as Windows version of Go function evalSymlinks calls GetLongPathName to format the path before returning it. Unpredictable casing results. So, the simple string comparison at path_windows_test.go:61 cannot be trusted anymore.

I hope it helps.

**Comment by jucie** [comment]
As I said earlier, a case insensitive comparison would suffice to pass the test, mainly considering we don't want to change much at this stage in release process. This is just my humble opinion, of course.

**Comment by jucie** [comment]
I know you guys are in a hurry, so I turned my "humble opinion" into a patch and sent it for review.

**Comment by alexbrainman** [comment]
Thank you for investigating. But your C program is different from Go's evalSymlinks. evalSymlinks calls GetShortPathName before calling GetLongPathName. I have modified your program slightly:
```
#include <windows.h>
#include <stdio.h>

int main(int argc, char **argv){
	char buffer[MAX_PATH], buffer2[MAX_PATH];
	printf("GetLongPathName: %d %s\n", GetLongPathName(argv[1], buffer, sizeof (buffer)), buffer);
	printf("GetShortPathName: %d %s\n", GetShortPathName(argv[1], buffer, sizeof (buffer)), buffer);
	printf("GetLongPathName: %d %s\n", GetLongPathName(buffer, buffer2, sizeof (buffer2)), buffer2);
	return 0;
}
```
Can you try my version and see if it works? Specifically see what it does for files created by TestEvalSymlinksCanonicalNames in your TMP directory.

Also what is real directory name: C:\USERS\JUCIE\APPDATA\LOCAL\TEMP\EVALSYMLINKCANONICAL102278141\TEST or C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical102278141\test ? Casing and all. Please use Windows Explorer or dir command or something.

Thank you.

Alex

**Comment by hirochachacha** [comment]
Sorry for the interruption.

FWIW:

This is not the issue related to `GetLongPathName`, 
but `GetShortPathName` as "outputWithPrintln.txt" clarifying.

There is a report explaining same situation:

http://blogs.msdn.com/b/winsdk/archive/2013/10/09/getshortpathname-doesn-t-return-short-path-name.aspx

So, I guess registry settings are key points.

**Comment by alexbrainman** [comment]
Thank you @hirochachacha. That is, probably, what @jucie is having. Sorry everyone, we have learnt something completely useless today.

Alex

**Comment by jucie** [comment]
The file tree created by the test function is this:
> dir /b /s C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical353329413
C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical353329413\test
C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical353329413\TEST2
C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical353329413\testing_long_dir
C:\Users\jucie\AppData\Local\Temp\evalsymlinkcanonical353329413\test\dir

After running the C program modified by Alex, the result is
[modifiedProgramOutput.txt](https://github.com/golang/go/files/95625/modifiedProgramOutput.txt)

The link @hirochachacha posted is elucidative (thanks, @hirochachacha). I issue the mentioned command to query my file system and found it has the short name feature disabled.
[fsutilOutput.txt](https://github.com/golang/go/files/95609/fsutilOutput.txt)

I never touched any of those settings. My box is pretty standard. So I think a lot of Windows installations should be exactly as mine. The build & test process will fail on those computers.

The test code, as it is now, disregards the fact that Windows file names are not case sensitive. The CL I sent yesterday address exactly that point and, as far as I know, solves the problem.

**Comment by hirochachacha** [comment]
@jucie No offence, IMPO, this issue is breaking canonicality (uniqueness).
Your CL seems to compromising without fixing the issue itself for me.
If there is a only choice, I agree with you 100%, but it's not true.

For example, 
we can drop current implementation, and remake it by `CreateFile` and `GetFinalPathNameByHandle`.
It's not the best solution, it requires [hacky workaround](https://gist.github.com/hirochachacha/bba426b5defff3d8f5fe#file-fchdir_windows-go). In this mean, it is also kind of compromising.

I don't know what is important for go's decision-making.
Even if we cannot find the flawless solution, the choice (of compromising) might be better than just compromising.

**Comment by jucie** [comment]
No offence taken, @hirochachacha. Your considerations are very welcome.
The more discussion the better, but sooner or latter we will have to pick up one solution.

**Comment by hirochachacha** [comment]
>No offence taken, @hirochachacha. Your considerations are very welcome.

Thank you!

>The more discussion the better, but sooner or latter we will have to pick up one solution.

I agree. I want to hear Alex's thoughts.

**Comment by alexbrainman** [comment]
> ... this issue is breaking canonicality (uniqueness).

Yes filepath.EvalSymlinks is supposed to return the same path (same string) for the same file. filepath.EvalSymlinks documentation does not spell this out, but we have always assumed this to be true. @rsc asked for this:
```
I would like to be able to depend on filepath.EvalSymlinks
returning the canonical spelling of its argument.
So if root is C:\GO and dir is c:\go\src\cmd,
I would like EvalSymlinks to return strings that
are the actual canonical case recorded in the file system
(say, C:\Go and C:\Go\src\cmd). 
```
See https://codereview.appspot.com/5713043/#msg5 for reference.

Our current implementation is broken on computers like @jucie's. I think we need to try and correct that.

> ... remake it by CreateFile and GetFinalPathNameByHandle.
> It's not the best solution, it requires hacky workaround. In this mean, it is also kind of compromising.

I am not sure what your proposal is. Feel free to send a CL to demonstrate. It can be quick and dirty. We can improve it, if it is a good solution.

> I don't know what is important for go's decision-making.

Sure. We could do nothing too. I will let @rsc to comment here.

Alex

**Comment by hirochachacha** [comment]
Thank you for your prompt response, Alex. 
Sorry for the late reply.
>Yes filepath.EvalSymlinks is supposed to return the same path (same string) for the same file. 

I see.

>I am not sure what your proposal is. Feel free to send a CL to demonstrate. It can be quick and dirty. We can improve it, if it is a good solution.

OK. I'll try to make a prototype within this weekend.

**Comment by alexbrainman** [comment]
> ... I'll try to make a prototype within this week.

No rush. I don't think we'll be changing this code before go1.6 is out (mid Feb).

Alex

**Comment by hirochachacha** [comment]
>No rush. I don't think we'll be changing this code before go1.6 is out (mid Feb).

I understand.

Thank you.

**Comment by jucie** [comment]
Pardon if I digress, bit it just occurred to me that in Windows, besides casing, one can use \\ or /, at will. So, these paths refer to the same file:
\\this\\is\\my\\file
/this/is/my/file
/this\\is/my\\file

**Comment by alexbrainman** [comment]
> function that, given two paths, returns true if they refer to the same file

filepath.EvalSymlinks is kind of that function. If you have path1 and path2 that contain any possible paths to the same file on Windows, then filepath.EvalSymlinks(path1) == filepath.EvalSymlinks(path2) /* I skipped error checking */.

Alex

**Comment by hirochachacha** [comment]
Here is a working example, if you are interested.

https://gist.github.com/hirochachacha/0227f21b6d6aef47f8c2

I have no plan to write the complete CL yet.

**Comment by jucie** [comment]
I am glad you tried a different approach, @hirochachacha, but I confess this one makes me a little worried. The Windows CreateFile function opens the file. I am not sure we can assume it is safe to do that. I applaud your nice try, but I hope we can find another way to do it.

**Comment by hirochachacha** [comment]
>The Windows CreateFile function opens the file. I am not sure we can assume it is safe to do that.

Hmm, I'm not sure what  you mean.
I think we can't follow symlink without opening the file.
Current `os.EvalSymlinks` calls `os.Readlink` internally, and `os.Readlink` calls `syscall.CreateFile`.

**Comment by hirochachacha** [comment]
Ah, it lacked `syscall.CloseHandle`. Maybe it's what you mean.
I only test this on Windows 10 64-bit, and it might contains other bugs.
I hope this implementation is enough to experiment ideas.

**Comment by alexbrainman** [comment]
Changing milestone to go1.7.

Alex

**Comment by alexbrainman** [comment]
Yes @hirochachacha might work. There might be problems with non-absolute paths. Current filapth.EvalSymlinks implementation does not rewrite those, while your version does. Also non-absolute paths on different drive from current will, probably, not work.

Alex

**Comment by hirochachacha** [comment]
>There might be problems with non-absolute paths. Current filapth.EvalSymlinks implementation does not rewrite those, while your version does.

I expect `filepath.Rel` should work.

>Also non-absolute paths on different drive from current will, probably, not work.

I don't think `Go` support such  semantics.
From my understanding, `cmd.exe` implements it as application level, not system level.
In system level (i.e. `CreateFile`), "Z:foo/bar" is not relative path, it depends.
If we are on Z drive, it is treated as relative path (same as "./foo/bar").
If not, it is treated as absolute path (same as "Z:\foo\bar").
(Should I file a new issue for `filepath.IsAbs`?)

Thank you for your reviewing, you two!

**Comment by hirochachacha** [comment]
>If not, it is treated as absolute path (same as "Z:\foo\bar").
(Should I file a new issue for filepath.IsAbs?)

Let me withdraw my controversial words.

```
func EvalSymlinks(path string) (string, error) {
    ... // get normalized abs path

	if filepath.IsAbs(path) {
		return abs, nil
	}

	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}

	if volume := filepath.VolumeName(path); volume != "" {
		if volume == filepath.VolumeName(wd) {
			return volume + filpath.Rel(wd, abs)
		}

		volume = filepath.VolumeName(abs)

		return volume + abs[len(volume)+1:] // trim beginning \
	}

	return filpath.Rel(wd, abs)
}
```

I don't think "trim beginning \" part is meaningful, though.
