### ISSUE TITLE
runtime: indexbytebody runs slower on short strings than 16 byte strings on amd64

### ISSUE THREAD

**Issue by prashantv** [golang/go#13983]
While doing some benchmarking, I noticed that strings.IndexByte was slower than a simple index-based for loop. This was originally reported here:
https://groups.google.com/forum/#!topic/golang-nuts/Vjy_UUcugPE

Keith observed that the benchmark ran faster when the string length was increased to 16 characters.

For a < 16 character string, the results change dramatically:
```
BenchmarkGetHostIndexByte-8    	100000000	        23.3 ns/op
BenchmarkGetHostIndexLoop-8    	200000000	         9.92 ns/op
```

For a 16 character string, the benchmarks are:
```
BenchmarkGetHostIndexByte-8    	200000000	         5.91 ns/op
BenchmarkGetHostIndexLoop-8    	200000000	         9.17 ns/op
```

Keith mentioned that the `REP` instruction was most likely to blame.

**Comment by bradfitz** [comment]
Keith sent https://go-review.googlesource.com/#/c/18703/
