### ISSUE TITLE
net/url: Export function `escape(s string, mode encoding) string` and the `encoding` constants

### ISSUE THREAD

**Issue by jirkadanek** [golang/go#13982]
I am proposing to make the function 

    func escape(s string, mode encoding) string

in https://golang.org/src/net/url/url.go exported, so that the library provides full interface to percent encoding. This has been first suggested in issue #4013.

**Comment by bradfitz** [comment]
I don't think that's a good idea.

The net/url package is full of non-spec compliant hacks for compatibility with our past mistakes. It's not something that should be exported.

**Comment by kelwang** [comment]
seems a lot of api signature use %20 for space encoding
and has to do something like strings.Replace(orignal_encoding, "+", "%20", -1)
