### ISSUE TITLE
text/template: always return nil for (next Node)

### ISSUE THREAD

**Issue by JadenTeng** [golang/go#13993]
`src/text/template/parse/parse.go:280:func (t *Tree) parse() (next Node)`

The return value may don't necessary now.
Would mind any guy to have a check?

**Comment by ianlancetaylor** [comment]
Yes, looks like the return value has not been needed since https://golang.org/cl/5393049 .

**Comment by dominichamon** [comment]
i'd like to take this (for a gentle introduction to making changes to golang).
