### ISSUE TITLE
Incorrect line number for compiling error when -cover for "go test"

### ISSUE THREAD

**Issue by daviddengcn** [golang/go#13990]
`go test t.go t_test.go` and `go test t.go t_test.go -cover` show different line numbers for compiling error (12 vs 14) with same error message. Is this expected?

t.go:
```go
package t

import(
  "fmt"
)

func T() {
  fmt.Println("Hello")
}

func b() {
  var i int = ""
}
```

t_test.go:
```go
package t

import(
  "testing"
)

func Test(t *testing.T) {
}
```

**Comment by ianlancetaylor** [comment]
This is a dup of #6329 .  It's a known problem.
