### ISSUE TITLE
cmd/compile internal compiler error after parse error

### ISSUE THREAD

**Issue by rsc** [golang/go#14006]
Only fix for Go 1.6 if trivial.

	$ cat x.go
	package p
	
	func f() {
		var x int
		switch x{
		case 1: 2:
		}
	
		var y string
		switch y {
		case "foo": "bar":
		}
	}
	$ go1.5 tool compile x.go
	x.go:6: missing statement after label
	x.go:6: syntax error: unexpected :, expecting case or default or }
	x.go:11: missing statement after label
	x.go:11: syntax error: unexpected :, expecting case or default or }
	$ go tool compile x.go
	x.go:6: internal compiler error: newname nil
	$

**Comment by griesemer** [comment]
Fix is safe and straight-forward: https://go-review.googlesource.com/18736
