### ISSUE TITLE
go/test: question about '/...' expansion with symbolic links

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#14005]
The ellipsis `/...`  expansion doesn't seem to follow links. For instance, if I have a package `./path/to/package` in my working directory, which is under `$GOPATH` and I do the following:
```
$ mkdir testpackage
$ ln -s ./path/to/package testpackage
$ go test ./testpackage/package/...
```
I get the following error:
```
warning: "testpackage/package/..." matched no packages
no packages to test
```

Is this expected? Where can I read about the `/...` expansion mechanism more? How can I overcome this issue and get correct expansion for the linked files?

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  Please see https://golang.org/wiki/Questions .  Thanks.

In general the go tool does not have strong support for symlinks, because it's often unclear how they should be handled.  But please discuss this on a mailing list, not here.
