### ISSUE TITLE
"Access is denied" with 1.6beta2 on Windows

### ISSUE THREAD

**Issue by peterh** [golang/go#14000]
After installing 1.6beta2, `go install myapp` results in `go install vendor/golang.org/x/net/http2/hpack: open C:\Program Files (x86)\Go\pkg\windows_amd64\vendor\golang.org\x\net\http2\hpack.a: Access is denied.`

hpack.a exists at that path and is readable from my account, so I guess the error comes from an attempt to re-compile hpack.a in a non-writable path.

It appears as though the special case code that avoids trying to write to system paths is broken with a /vendor/ in the system path, and/or the new installer isn't setting magic timestamps on hpack.a the way it is did on the go1.5 .a files.

After becoming superuser and touching hpack.a, `go install` completes normally.

hpack.a had a timestamp shortly after its source files, so I'm not sure why `go install` is trying to rebuild it. A fudge factor to account for the poor resolution of FAT timestamps (despite the fact I'm on NTFS), maybe?

**Comment by bradfitz** [comment]
cc @rsc for cmd/go and @adg for cmd/release stuff.

**Comment by adg** [comment]
> hpack.a had a timestamp shortly after its source files,

@peterh do you happen to know what the timestamps were?

**Comment by alexbrainman** [comment]
Perhaps 383d817 (that is not part of go1.6beta2) fixes the problem?

Alex

**Comment by peterh** [comment]
In the MSI, hpack.a has a timestamp of 2016-01-14 00:25:12. hpack.go has a timestamp of 2016-01-14 00:24:08. These timestamps appear to be preserved by the installer (although the output of "dir" truncates the seconds, so I'm not absolutely sure about seconds).

Hmm. That's over a minute. So it's probably something else. Sorry for the red herring.

**Comment by adg** [comment]
It is probably related to the vendor directory. Let's see if we can fix it
for the release candidate.

**Comment by peterh** [comment]
Full output of "go install -x" on a sample app that consists of a single call to http.Get after a clean install of go1.6beta2:

>S:\go\src\example>go install -x
WORK=C:\Users\peterh\AppData\Local\Temp\go-build088490102
mkdir -p $WORK\vendor\golang.org\x\net\http2\hpack\_obj\
mkdir -p $WORK\vendor\golang.org\x\net\http2\
cd C:\Program Files (x86)\Go\src\vendor\golang.org\x\net\http2\hpack
"C:\\Program Files (x86)\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\peterh\\AppData\\Local\\Temp\\go-build088490102\\vendor\\golang.org\\x\\net\\http2\\hpack.a" -trimpath "C:\\Users\\peterh\\AppData\\Local\\Temp\\go-build088490102" -p vendor/golang.org/x/net/http2/hpack -complete -buildid c7e6f5aec69b310d87160b6fca31a8005c55e983 -D _/C_/Program_Files__x86_/Go/src/vendor/golang.org/x/net/http2/hpack -I "C:\\Users\\peterh\\AppData\\Local\\Temp\\go-build088490102" -pack "C:\\Program Files (x86)\\Go\\src\\vendor\\golang.org\\x\\net\\http2\\hpack\\encode.go" "C:\\Program Files (x86)\\Go\\src\\vendor\\golang.org\\x\\net\\http2\\hpack\\hpack.go" "C:\\Program Files (x86)\\Go\\src\\vendor\\golang.org\\x\\net\\http2\\hpack\\huffman.go" "C:\\Program Files (x86)\\Go\\src\\vendor\\golang.org\\x\\net\\http2\\hpack\\tables.go"
mkdir -p C:\Program Files (x86)\Go\pkg\windows_amd64\vendor\golang.org\x\net\http2\
cp $WORK\vendor\golang.org\x\net\http2\hpack.a C:\Program Files (x86)\Go\pkg\windows_amd64\vendor\golang.org\x\net\http2\hpack.a
go install vendor/golang.org/x/net/http2/hpack: open C:\Program Files (x86)\Go\pkg\windows_amd64\vendor\golang.org\x\net\http2\hpack.a: Access is denied.

**Comment by alexbrainman** [comment]
I cannot reproduce this. I used https://storage.googleapis.com/golang/go1.6beta2.windows-amd64.zip to install my Go. I used https://golang.org/pkg/net/http/#example_Get as a program to build.

Alex

**Comment by peterh** [comment]
I tried the .zip just now on a 2nd machine, and I could not reproduce. I then installed the MSI https://storage.googleapis.com/golang/go1.6beta2.windows-amd64.msi on the same machine and the error does reproduce.

So it looks like the error is in the MSI, but not in the zip.

Most of the timestamps in the .zip and the .msi differ by about 2 seconds, so a naive "diff -u" on the directory listings isn't helpful.

While both installs preserve the timestamp of files, it may be interesting to note that while the .zip preserves the timestamp on directories, the .msi does not.

**Comment by rsc** [comment]
I believe this is a dup of #13713. My apologies: we should have fixed that before issuing beta 2.

**Comment by peterh** [comment]
This does appear to be a dup. Sorry I missed the other one when searching for issues. I just tried rc1 and it's fixed now. Thanks!

**Comment by rsc** [comment]
No worries. Thanks for confirming the fix.
