### ISSUE TITLE
net/url: Fails to parse URLs with spaces in scope IDs in 1.6beta2

### ISSUE THREAD

**Issue by calmh** [golang/go#14002]
Test program:

```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	u, err := url.Parse("tcp://[fe80::cefa:ff:fef3:5fcc%25Wireless%20Network%20Connection]:22000")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("OK:", u)
	}
}
```

Fine in 1.5.2:

```
jb@syno:~/tmp $ go version
go version go1.5.2 darwin/amd64
jb@syno:~/tmp $ go run test.go 
OK: tcp://[fe80::cefa:ff:fef3:5fcc%25Wireless%20Network%20Connection]:22000
```

Errors in 1.6beta2:

```
jb@syno:~/tmp $ go run test.go 
parse tcp://[fe80::cefa:ff:fef3:5fcc%25Wireless%20Network%20Connection]:22000: invalid URL escape "%20"
jb@syno:~/tmp $ go version
go version devel +66330d8 Wed Jan 13 23:40:13 2016 +0000 darwin/amd64
```

That's how Windows represents scope IDs.

**Comment by bradfitz** [comment]
@rsc, you touched this last. Maybe you still remember all the spec rules and Go decisions made?

**Comment by rsc** [comment]
We started rejecting spaces in host names, which is generally correct. I guess we have to accept spaces in the %-encoded scope section. Ugh.

**Comment by rsc** [comment]
CL 18855.

**Comment by canton7** [comment]
>  Windows: putting spaces where they don't belong since Windows NT 3.1.

Purely out of interest: Windows uses the Scope ID of the network interface in question as the zone identifier. This is a `long`, so zones typically have the value `%1`, `%2`, etc.

Using the network interface name on Windows [seems to be a Go thing](https://github.com/golang/go/blob/ceeb52d86214757b25a39a939fe945eb8e787bf6/src/net/lookup_windows.go#L132). Presumably there's good reason, although it does make taking URLs formatted by Go and parsing them in other languages slightly tricky.

**Comment by calmh** [comment]
That's from String() on a net.Addr returned from Read...() on an UDP socket (whatever the exact read method is that returns the packet plus the source address, I'm on mobile currently). We that put that address in as the Host in a url.URL which in turn gets stringified and sent over the network. The other side does url.Parse which results in the above.

**Comment by bradfitz** [comment]
@rsc, given @calmh's comment, I think your fix above isn't necessary. I think we need to fix the String method instead.

**Comment by rsc** [comment]
I'm not changing the String method to emit an encoded URL with literal spaces in it. URLs do not have spaces. Full stop.

**Comment by rsc** [comment]
There's some notion that we should be using %1 instead of %AdapterName, but I don't know where the 1 comes from and I don't know if it works to send it over the network.

**Comment by calmh** [comment]
As a side note, url.Parse also does not accept spaces in the host name (in the scope ID or otherwise), so that wouldn't be an immediate fix. Perhaps it could be taught to do so, but it seems cleanest to do the escaping as it currently does and then accept that back.

**Comment by calmh** [comment]
Actually the "send over network" part in my description is both incorrect and irrelevant. It's just two packages where the interface between them is in terms of url.URLs to connect to and it so happens that some of these represent link local v6 addresses.

**Comment by rsc** [comment]
OK, well, the fact is that zone identifiers are allowed to have spaces, and this code was trying to make sure they were minimally escaped. Since you can't have a space in a URL, the space must be escaped. This code didn't allow that, and now it does. So I think everything here is in order.

There's some question about whether zone identifiers in practice use spaces, but it appears that at least in Go programs on Windows they do. Maybe that's a mistake, or maybe not, but it's too late in the release cycle to make a fundamental change like that in package net. The acceptance of %20 in the zone identifier is trivial, clearly safe, and consistent with RFCs. (The code in question was actually  being stricter than the RFCs and still is.)

If someone wants to open a separate bug, for Go 1.7, about maybe using %1 instead of "%Windows Ethernet Adapter" or whatever, that's fine.

**Comment by canton7** [comment]
> That's from String() on a net.Addr returned from Read...() on an UDP socket
...
> I think we need to fix the String method instead.
...
> I'm not changing the String method to emit an encoded URL with literal spaces in it.

I think @bradfitz was referring to `net.Addr.String()`, not `URL.String()`? Maybe I'm misreading it...

**Comment by rsc** [comment]
Oh, the net.Addr.String method would make more sense. But the point in my final comment remains: it's fine if someone wants to look into fixing that for Go 1.7, but this seems to work for people in Go 1.6 and the URL change is not technically wrong, and the URL change is also less scary than changing the form of net.Addr.String this close to a release.
