### ISSUE TITLE
x/sys/windows/svc/mgr: CreateService does not allow driver loading

### ISSUE THREAD

**Issue by npetroni** [golang/go#14019]
Summary:

 [golang.org/x/sys/windows/svc/mgr.CreateService](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Mgr.CreateService) does not allow driver loading.

Details:

[golang.org/x/sys/windows/svc/mgr.CreateService](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Mgr.CreateService) is a high-level interface for the Windows [CreateService](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682450(v=vs.85).aspx) function. The former accepts a struct [Config](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Config) but ignores that structure's `ServiceType` field. Instead, it uses the constant [windows.SERVICE_WIN32_OWN_PROCESS](https://github.com/golang/sys/blob/master/windows/service.go#L26). This implementation precludes the creation of other service types, including drivers.

I propose modifying [golang.org/x/sys/windows/svc/mgr.CreateService](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Mgr.CreateService) to honor the `ServiceType` field, but continue using `windows.SERVICE_WIN32_OWN_PROCESS` as the default when that field is unpopulated (i.e., equal to zero). This change is consistent with other `Config` members in that function, preserves the semantics for existing callers, and allows driver loading (more generally, other service types).

Something like this works for me:

```
diff --git a/windows/svc/mgr/mgr.go b/windows/svc/mgr/mgr.go
index 4d7e72e..da8ceb6 100644
--- a/windows/svc/mgr/mgr.go
+++ b/windows/svc/mgr/mgr.go
@@ -85,12 +85,15 @@ func (m *Mgr) CreateService(name, exepath string, c Config, args ...string) (*Se
        if c.ErrorControl == 0 {
                c.ErrorControl = ErrorNormal
        }
+       if c.ServiceType == 0 {
+               c.ServiceType = windows.SERVICE_WIN32_OWN_PROCESS
+       }
        s := syscall.EscapeArg(exepath)
        for _, v := range args {
                s += " " + syscall.EscapeArg(v)
        }
        h, err := windows.CreateService(m.Handle, toPtr(name), toPtr(c.DisplayName),
-               windows.SERVICE_ALL_ACCESS, windows.SERVICE_WIN32_OWN_PROCESS,
+               windows.SERVICE_ALL_ACCESS, c.ServiceType,
                c.StartType, c.ErrorControl, toPtr(s), toPtr(c.LoadOrderGroup),
                nil, toStringBlock(c.Dependencies), toPtr(c.ServiceStartName), toPtr(c.Password))
        if err != nil {
```

**Comment by ianlancetaylor** [comment]
CC @alexbrainman

**Comment by alexbrainman** [comment]
@npetroni SGTM.

Would you like to send your change? Thank you.

Alex

**Comment by npetroni** [comment]
https://go-review.googlesource.com/18760

First time using the process, so please let me know if I did anything wrong. Thanks.

**Comment by alexbrainman** [comment]
> let me know if I did anything wrong

I did just fine. Thank you.

Alex
