### ISSUE TITLE
runtime/race: tests fail

### ISSUE THREAD

**Issue by mwhudson** [golang/go#14011]
`go test runtime/race` fails:

```shellsession
mwhudson@aeglos:deb$ go test -race runtime/race
--- FAIL: TestRace (14.54s)
	race_test.go:45: Failed to run tests: exit status 2
		# command-line-arguments_test
		testdata/issue12225_test.go:11: undefined: unsafe in unsafe.Pointer
		testdata/issue12225_test.go:11: undefined: convert
		testdata/issue12225_test.go:12: undefined: unsafe in unsafe.Pointer
		FAIL	command-line-arguments [build failed]
FAIL
FAIL	runtime/race	33.116s
```

These tests are (obviously) not run by `go tool dist test`. What are they for? Should they be fixed and enabled, deleted, something else?

**Comment by minux** [comment]
It should be run by the race builders in go tool dist -race mode,
but that mode doesn't run test for runtime/race for some reason.

I think it's lost during the transition from race.bash to go tool dist test,
I will send a CL.
