### ISSUE TITLE
net: go 1.5.1 does not use all nameservers for DNS lookups

### ISSUE THREAD

**Issue by jiaweizhou** [golang/go#14025]
On ubuntu , my app can't reslove the domains that can not be find in the first dns but the second.
It just happened when I use **golang 1.5.1** . When I use **golang 1.4.*** , it works well .
For example,I edit /etc/resolve.conf like this：
```
nameserver 10.27.227.194
nameserver 10.27.227.195
```
domain **a.com** is defined in **nameserver 10.27.227.194** , and **b.com** is defined in **10.27.227.195** . 
Then my application can not connect to **b.com** because of the dns , but it can connet to **a.com** . If I exchange the location of the nameserver ,  **b.com** can be connected but **a.com** can not be.

Thank you.

**Comment by ianlancetaylor** [comment]
Could be a dup of #12778 .  Can you try the 1.6 beta?

**Comment by mikioh** [comment]
@jiaweizhou,

Also try the following:
```
drill (or dig or similar) @10.27.227.194 b.com a
drill (or dig or similar) @10.27.227.195 a.com a
```
If your DNS servers return RCODE=3 (known as NXDOMAIN), the builtin DNS stub resolver in Go 1.5 and above stops querying for avoiding some trap using NXDOMAIN such as NXDOMAIN substitution. The bug exists in Go 1.4 and below.

**Comment by mikioh** [comment]
Timeout. Closing.
