### ISSUE TITLE
crypto/x509: FreeBSD CA roots order fix

### ISSUE THREAD

**Issue by lifeforms** [golang/go#14022]
In Go 1.5, the CA root certificate store search order was changed for BSD systems:
- Go 1.4 programs would look for `/etc/ssl/cert.pem` before trying `/usr/local/share/certs/ca-root-nss.crt`. ([source](https://github.com/golang/go/blob/release-branch.go1.4/src/crypto/x509/root_unix.go#L16))
- Go 1.5 programs will try `/usr/local/share/certs/ca-root-nss.crt` first, before looking for `/etc/ssl/cert.pem`. ([source](https://github.com/golang/go/blob/release-branch.go1.5/src/crypto/x509/root_bsd.go#L11))

Looking at FreeBSD itself, libfetch (used by FreeBSD core) appears to try the SSL_CA_CERT_FILE environment variable first, then `/usr/local/etc/ssl/cert.pem`, then `/etc/ssl/cert.pem`. ([source](https://svnweb.freebsd.org/base/head/lib/libfetch/common.c?view=markup&pathrev=294326#l691)) This might be considered the canonical way to determine the location for the trust store on FreeBSD.

In FreeBSD, the location `/usr/local/share/certs/ca-root-nss.crt` is not special or blessed, but it's an implementation detail of the ca_root_nss package (Root certificate bundle from the Mozilla Project). Almost all users will have this package installed, and due to the ca_root_nss package's ETCSYMLINK option, their `/etc/ssl/cert.pem` will be symlinked, in which case the lookup order does not matter.

My issue with Go 1.5 happens because I deploy my own trust store to `/etc/ssl/cert.pem`.

If the ca_root_nss package happens to be installed, Go 1.5 picks up the ca_root_nss package's file `/usr/local/share/certs/ca-root-nss.crt` and no longer looks at the global `/etc/ssl/cert.pem`.

My build boxes have the Mozilla roots ca_root_nss package installed (to incorporate a modified version of it in our own trust store). On these machines, Go 1.5 programs prefer `ca-root-nss.crt` and use only the Mozilla roots, failing to verify servers using the global roots.

Due to fate, the search order in Go 1.4 ([source](https://github.com/golang/go/blob/release-branch.go1.4/src/crypto/x509/root_unix.go#L16)) seems to have been more correct, as `/etc/ssl/cert.pem` was tried first, even if it was marked only as for OpenBSD.

However, since most people will just plainly use the Mozilla CA roots as their global roots file, this issue is probably rare.

I would recommend to duplicate the search order of FreeBSD's libfetch ([source](https://svnweb.freebsd.org/base/head/lib/libfetch/common.c?view=markup&pathrev=294326#l691)) in /src/crypto/x509/root_bsd.go.

The current list is:

```
var certFiles = []string{
    "/usr/local/share/certs/ca-root-nss.crt", // FreeBSD/DragonFly
    "/etc/ssl/cert.pem",                      // OpenBSD
    "/etc/openssl/certs/ca-certificates.crt", // NetBSD
}
```

To prefer the system roots and mimic the behavior of libfetch, while keeping compatibility with the other OSes, the entries could become:

```
var certFiles = []string{
    "/usr/local/etc/ssl/cert.pem",            // FreeBSD
    "/etc/ssl/cert.pem",                      // FreeBSD/OpenBSD
    "/usr/local/share/certs/ca-root-nss.crt", // DragonFly
    "/etc/openssl/certs/ca-certificates.crt", // NetBSD
}
```

Go version: `go version go1.5.3 freebsd/amd64`

**Comment by minux** [comment]
Perhaps we should just add a environment variable for the user to specify
system root directory explicitly. It will be much less fragile than relying
on the default search order.

**Comment by ianlancetaylor** [comment]
Since this is the first complaint I've seen about 1.5, and we are frozen as we can be for 1.6, I'm pushing this back until 1.7.

**Comment by lifeforms** [comment]
That sounds great, good luck with the freeze!

As for environment variables, FreeBSD just brought its libfetch in order with OpenSSL convention of checking SSL_CA_CERT_FILE and SSL_CA_CERT_PATH. I imagine it would be pretty cool if Go programs would do the same, though the change would be a bit bigger.

**Comment by rsc** [comment]
We should make sure to get to this early in Go 1.8.
