### ISSUE TITLE
cmd/dist: "go tool dist: unknown $GOOS linux"

### ISSUE THREAD

**Issue by danhardman** [golang/go#14024]
1. Go version: 1.5.3
2. Windows/AMD64
3. Ran make.bat from C:/go/src
4. Not really sure
5. go tool dist: unknown $GOOS linux

I'm trying to set my target GOOS and GOARCH to `linux/arm` whilst developing using atom go that I can build on save and see appropriate error messages given to me through the atom package: go-plus. However, When I do this on Windows, I get error messages saying go tools cannot be found. 

I was told running make.bat would solve this issue, however when it gets to running `.\cmd\dist\` I get this error `go tool dist: unknown $GOOS linux`.

Obviously "linux" is included in `okgoos` so I'm not sure why https://github.com/golang/go/blob/master/src/cmd/dist/build.go#L115 is failing.

**Comment by davecheney** [comment]
This is likely to be a mistake in your Go installation, caused by step 3. I recommend removing what's left of your Go installation and replacing it with a fresh one. 

As of Go 1.5 no additional steps are required to prepare for cross compilation.

**Comment by danhardman** [comment]
Removed my go installation completely and installed fresh.

Ran `SET GOOS=linux && go build` and got:

>go build runtime: linux /amd64 must be bootstrapped using make.bat

Same thing if I `SET GOARCH=arm` too.

**Comment by minux** [comment]
That error message is wrong and i think it has been fixed in Go 1.6.

**Comment by danhardman** [comment]
Hopefully... Till then I'll develop on my mac. That seems to work fine when I change the target OS

**Comment by minux** [comment]
It's fixed by https://golang.org/cl/15221, and it basically just removed
the error, so you can also apply that to Go 1.5 source code if you want.
The patch should be pretty safe.

**Comment by danhardman** [comment]
That's brilliant. The commit message also mentions the likelihood of an incorrect $GOROOT so I'll check that out as well, although it was installed in the default place so I'm pretty sure it's not even set. I'll set it and see if that makes a difference.

**Comment by davecheney** [comment]
Please do not set $GOROOT. This will not help in resolving this issue.

**Comment by danhardman** [comment]
My `build.go` is completely different to the one in that commit @minux. That error doesn't exist there...
