### ISSUE TITLE
website: on the install from source page the user is told to check out go1.5.2

### ISSUE THREAD

**Issue by keks** [golang/go#14020]
In the [instructions to build go from source][1], the user is asked to call 

    git checkout go1.5.2

I guess this should be changed, especially since go1.5.3 was a severe security fix. 

Edit: typo

[1]: https://golang.org/doc/install/source#fetch

**Comment by ALTree** [comment]
https://go-review.googlesource.com/#/c/18750/

Probably worth updating, since 1.6 is at least 1 month away.
