### ISSUE TITLE
runtime/race: RaceWaitGroupAsMutex flaky on windows

### ISSUE THREAD

**Issue by mwhudson** [golang/go#14035]
As seen here: http://build.golang.org/log/78ed79b153c9a6304a00d52c46523e9fa3961ad8

**Comment by bradfitz** [comment]
Dmitry, can you look into this one?

**Comment by bradfitz** [comment]
Also http://build.golang.org/log/f99b0ecfca9b47a90ab75b01ebd609611af7f633

**Comment by aclements** [comment]
`$ greplogs -l -md -dashboard -e 'RaceWaitGroupAsMutex *FAILED'`
[2016-01-20T06:10:20-9726696/windows-amd64-race](https://build.golang.org/log/78ed79b153c9a6304a00d52c46523e9fa3961ad8)
[2016-01-21T17:00:42-f8f4cfa/windows-amd64-race](https://build.golang.org/log/f99b0ecfca9b47a90ab75b01ebd609611af7f633)
[2016-01-21T18:41:36-754216d/windows-amd64-race](https://build.golang.org/log/a6c55f37380e0c1ddf955083db442623943c42a3)

```
$ findflakes -grep 'RaceWaitGroupAsMutex *FAILED'
First observed 9726696 20 Jan 06:10 2016 (6 commits ago)
Last observed  754216d 21 Jan 18:41 2016 (1 commits ago)
60% chance failure is still happening
40% failure probability (3 of 6 commits)
Likely culprits:
   40% 9726696 cmd/dist: pass -tags race to go list in -race mode
   24% 5395846 cmd/compile: don't print (empty) package name in errors referring to built-ins
   14% df2a9e4 runtime/race: fix test so it compiles
    9% d9b32f0 cmd/compile: add VARLIVE to opnames list
    5% 7ce2402 cmd/compile: don't crash on invalid labeled statement
No known past failures
```

**Comment by mwhudson** [comment]
Fingering the test that starting running these tests again as introducing the flake is probably accurate, but not very helpful, unfortunately.

**Comment by aclements** [comment]
Yeah. That's statistics for you. Just because it's statistically significant doesn't mean anyone cares. :)

Though it does show this flake was introduced at some point after 2015-05-07T21:08:29-9626561, which is around when the tests stopped running (admittedly, that was quite a while ago).
