### ISSUE TITLE
net/http http.FileServer directory list error on windows

### ISSUE THREAD

**Issue by molixiaoge** [golang/go#14034]
code :http.ListenAndServe(":80",http.FileServer(http.Dir("./")))

  build the exe and copy that to two different directory,which call one and two.open one exe and refresh browser, the list right. close one open two, refresh browser, the list right,but close two and open one ,the browser list not refresh, which just show pre list.

**Comment by bradfitz** [comment]
I suspect this is either some browser caching thing (try shift-reload?) or it's some Windows shell/working directory thing I don't know about.

Let's move this to the mailing list or other forum until a bug has been identified.

See https://golang.org/wiki/Questions
