### ISSUE TITLE
net/http/httputil: DumpResponse could corrupt Response object

### ISSUE THREAD

**Issue by Loofort** [golang/go#14036]
Here is a code snippet used inside DumpResponse and DumpResponseOut functions:
```go
	save, resp.Body, err = drainBody(resp.Body)
	if err != nil {
		return
	}
```
In case when resp.Body is corrupted, drainBody returns error and resp.Body is assigned to nil. Then when caller try to execute resp.Body.Close() it will panic.
That is why e.g. this legal code might panic:
```go
	response, err := httpClient.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()

	dump, err := httputil.DumpResponse(response, true)
	if err == nil {
		return err
	}
```

**Comment by bradfitz** [comment]
That's not how defer works. Defer evaluates everything needed for the call but doesn't make the call until later. But "response.Body" is fully evaluated before DumpResponse:

Example for you to play with: http://play.golang.org/p/AE6mwTOV6j

Maybe you meant http://play.golang.org/p/YIOKnNMT-N ?

In any case, this seems like fine behavior. If httputil.DumpResponse returns an error after consuming the body, it seems valid to assume that res.Body is messed up. And code like my first link is much more common than code like my second link.

**Comment by Loofort** [comment]
You right about defer,
I was trying to simplify the code and made mistake.

our real ussage is that we use DumpResponse (for logging purpose) before response.Body.Close(), and don't check dump err.

I was surprising that DumpResponse might assign nil to resp.Body
If it is not bug but feature, it's better to put the notice to documentation.

Thanks.

**Comment by bradfitz** [comment]
Sure, I'll document.
