### ISSUE TITLE
tour: The indirection through the pointer is transparent.

### ISSUE THREAD

**Issue by gswallow** [golang/go#14040]
Context: http://127.0.0.1:3999/moretypes/4

Is this a sentence designed for C programmers with pointer experience to understand, and not dummies like me?  Does this sentence mean that when I assign a value through a pointer to an int, I have to type:

i := 42
p := &i
*p = 21

While if I update a field in a struct, I can type:

type Vertext struct { 
  X int
  Y int
}

v := Vertex{1, 2}
p := &v
p.X = 1e9?

**Comment by ianlancetaylor** [comment]
CC @adg @campoy
