### ISSUE TITLE
proposal: release branch

### ISSUE THREAD

**Issue by adg** [golang/go#14049]
Once upon a time, when we used Mercurial, users who built from source could check out the `release` tag to get the latest stable version of Go. When a new version of Go was released, users could just `hg pull && hg update release` to update.

Git tags don't work like that. They can't practically be moved. So our docs need to be updated with each new release to instruct users to check out a specific tag (eg, `git checkout go1.5.3`).

On a [recent CL](https://go-review.googlesource.com/#/c/18750/) @minux suggested that we could maintain a `release` *branch* and merge the latest stable release into that branch whenever there is a new release. Users could check out the `release` branch and use a simple `git pull` to stay up to date.

To create a release branch, we could start with `release-branch.go1.5` (all this happens inside a go repo with git-codereview set up):
```
$ git change release-branch.go1.5
$ git checkout -b release --no-track   # don't track the release-branch.go1.5 upstream
```
Then, when Go 1.6 is released, we can merge that branch into the release branch. This involves a somewhat bit of a dance to make sure we have a clean merge commit with identical contents to the new release branch.
```bash
# Start with the release branch.
$ git checkout release

# Create a merge commit that merges release-branch.go1.6 into release,
# but actually keeps the content of release as-is (-s ours).
# The only desired result here is a conflict-free merge commit that has two parents,
# the previous release HEAD and the release-branch.go1.6.
$ git merge -s ours release-branch.go1.6

# Create a branch at that merge commit.
$ git branch temp

# Hard reset the release branch HEAD to go1.6.
# At this point the content of the release branch is identical to that of release-branch.go1.6.
$ git reset --hard release-branch.go1.6

# Soft reset the release branch HEAD to the release/release-branch.go1.6 merge commit,
# leaving the contents of release-branch.go1.6 as staged changes.
$ git reset --soft temp

# Amend the commit to replace the contents of the merge commit
# with the content at release-branch.go1.6.
$ git commit --amend

# Delete the temporary branch.
$ git branch -D temp

# Check that the release branch is now indistinguishable from release-branch.go1.6.
$ git diff release release-branch.go1.6
```

On the user end, this is how they would check out a Go release:
```
$ git clone -b release https://go.googlesource.com/go
```
and here's how they would upgrade when a new release is issued:
```
$ git pull
```
I'd like to hear feedback on this approach. I'm no Git expert, so maybe I'm doing things the hard way. But it does seem like a usability win.

**Comment by adg** [comment]
(Note that the dance with the temporary branch and hard/soft resets is only necessary because there is no `theirs` merge strategy; we use `ours` to create the merge commit and then synthesize a `theirs` merge by hand.)

**Comment by adg** [comment]
cc @broady

**Comment by minux** [comment]
I think git merge does support theirs merge strategy.

https://git-scm.com/docs/git-merge

**Comment by adg** [comment]
@minux if you look carefully, the `theirs` mentioned on that page is an option to the `recursive` merge strategy. The `recursive` strategy with the `theirs` option is not the same as the reverse of the `ours` strategy.

There was once a `theirs` strategy but it was [removed by the developers](http://marc.info/?l=git&m=121637513604413&w=2). (They didn't have our use case in mind.)

**Comment by adg** [comment]
(Replying to @minux's comments from the aforementioned CL.)

> I suggest that if we're going to do this, we start from go1, so
> it will be painless for users to stay on the branch and switch
> versions at will.

What's the benefit of going all the way back? `git checkout <tag>` will take you to whatever release you're looking for. The sole purpose of the proposed `release` branch is to make `git checkout release` and/or `git pull` work cleanly to give you the latest stable release. 

> There is one question though, should future go1.x tags point
> to the major version specific release branch or the new release
> branch? I can see arguments from both sides.

IMO the tags should continue point to the relevant commits in the release-branch. Those are the canonical commits. The `release` branch is just a convenience.

**Comment by adg** [comment]
Anyone else have thoughts on this? @broady? @dsymonds? @bradfitz? @rsc?

**Comment by broady** [comment]
I like this.

**Comment by dsymonds** [comment]
What's the audience for this? Is it worth going out of our way to support? Is there a large number of people who both want to stick with official releases but want to do that via git?

Having a long-running `release` branch ends up a bit messy with all the merging, particularly when files are added/deleted. If the release tags aren't going to be pointing to commits on the `release` branch then the people using that branch won't be using the exact proper releases. My concern is that there's going to be an ongoing support burden for very little benefit here.

**Comment by broady** [comment]
Yes, I think that's correct, @dsymonds. The branch would have a different commit (since it'd have a merge commit), but would be functionally the same.

I suppose the use case is people that want to build from source but don't want to look up the latest version. Is that worth it?

**Comment by davecheney** [comment]
I agree with @dsymonds. This started as a documentation issue -- the tag
listed in the docs tends to lag behind the latest released version of Go --
can we solve it as a documentation issue instead. ie, use something like
$RELEASE_TAG, so the documentation becomes

   git clone https://go.googlesource.com/go -r $RELEASE_TAG

Then we just (ha) have to document how to construct a valid value of
$RELEASE_TAG.

**Comment by dsymonds** [comment]
The download page (https://golang.org/dl/) has source tarballs. They can use them if they want to build from source. Is it particularly burdensome to use that, or to look up the latest version number if they really want the git checkout?

**Comment by adg** [comment]
> Having a long-running release branch ends up a bit messy with all the merging, particularly when files are added/deleted. 

@dsymonds how so? The method I described creates a single merge commit for each release, nothing more. I don't know why added/deleted files matter?

> This started as a documentation issue 

@davecheney actually it didn't start as a documentation issue. When we did the conversion to Git in the first place we wanted to make this work, but didn't think of a good way to do it at the time.

With that said, I do agree this is of limited utility, probably for a very small audience indeed.

**Comment by dsymonds** [comment]
Imagine a release deletes a file (e.g. `foo.c` is now `foo.go`, or whatever). The merge has to decide what to do. Depending on the complexity of things changing, a merge may have to make a significant number of manual decisions. I don't think it's quite as trivial as your plan suggests. I've done these merges before, and they can sometimes turn out to be a nightmare.

**Comment by adg** [comment]
@dsymonds the technique described in my proposal doesn't let the merge make any decisions. The content of the merge commit is from a hard reset to the new release commit.

**Comment by dsymonds** [comment]
Hmmm. Not a traditional merge, but it might work.

**Comment by adg** [comment]
It does work. I tested it.

**Comment by rsc** [comment]
I'm meh on the actual implementation - it's complex like everything else in Git - and don't understand the rationale. I don't hear people asking for this. If anything people want to talk about versioned software, not unversioned software. Why take on this complexity?

**Comment by rsc** [comment]
Also if it's just for us to avoid updating our docs, at least the ones in $GOROOT/doc can have template code in them. It would not be hard to compute the version from what is serving the docs.

**Comment by minux** [comment]
I think updating to a new release via source code will also be easier with
the release branch.

Previously you have to first figure out which tag to check out (or
download) and then checkout and build. Now you just pull and build.

**Comment by rsc** [comment]
On Thu, Jan 21, 2016 at 7:59 PM, Minux Ma <notifications@github.com> wrote:

> I think updating to a new release via source code will also be easier with
> the release branch.
>
> Previously you have to first figure out which tag to check out (or
> download) and then checkout and build. Now you just pull and build.


And just hope for the best? I don't think it's unreasonable that people
have to type the version they expect to run.

Russ

**Comment by adg** [comment]
Let's drop it then. I'll find a better way to keep the tag in the docs up-to-date.
