### ISSUE TITLE
tour: reference to Fibonacci sequence without explanation of what it is

### ISSUE THREAD

**Issue by gswallow** [golang/go#14044]
Context: http://127.0.0.1:3999/moretypes/23

So...utterly...lost.

The Fibonacci sequence is the sequence of numbers where the value(n) = value(n-1) + value (n-2) with the seed values value(0) = 0 and value(1) = 1. (source: http://nylira.com/a-tour-of-go-solutions/)

That's all I need.  I'll try to figure this out without looking up the actual solution.

**Comment by bradfitz** [comment]
What's the bug here?

That the tour doesn't define the fibonacci sequence?

**Comment by gswallow** [comment]
The tool tip on the bug icon says "leave feedback;" not "file a bug."  I
find that the tour is extremely difficult for someone who hasn't coded in C
before to follow.

A description of the fibonacci sequence, and perhaps some test data would
be nice.

**Comment by minux** [comment]
we probably just need to link "Fibonacci" to
its wikipedia article.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy
