### ISSUE TITLE
src: move things from internal to vendor for Go 1.7

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14047]
Let's move stuff out of $GOROOT/src/internal and into $GOROOT/src/vendor for Go 1.7.

Related bugs: #13961 and #14031

**Comment by bradfitz** [comment]
Revert this CL too: https://go-review.googlesource.com/#/c/19384/1

/cc @rsc

**Comment by rsc** [comment]
To be clear, the only vendor-able stuff in $GOROOT/src/internal is hpack, right?

**Comment by bradfitz** [comment]
Yes, currently. There was talk of moving singleflight to syncutil too, which has 3-4 copies lately, which are starting to diverge.

**Comment by bradfitz** [comment]
Did enough.
