### ISSUE TITLE
cmd/go: invalid vendoredImportPath error

### ISSUE THREAD

**Issue by bashtian** [golang/go#14054]
Go 1.6beta2

go run fails when the cwd is a symlink to a folder in $GOPATH

``` sh
ln -s $GOPATH/src/golang.org/x/mobile/example/basic/ basic
cd basic
go run main.go

$ invalid vendoredImportPath: ...
```

It works when I disable the vendor experiment

```
export GO15VENDOREXPERIMENT=0
```

**Comment by bradfitz** [comment]
What is main.go?

I think this is fixed, now that we stopped using vendor for std.

**Comment by bradfitz** [comment]
Please try with tip. I'm pretty sure this is fixed now.

**Comment by bashtian** [comment]
The problem still exits in go1.6rc1

**Comment by bradfitz** [comment]
You still didn't answer my original question, so I'm going to leave this closed.

Please provide enough information for us to reproduce the problem.

**Comment by bashtian** [comment]
Sorry for that. It's the example from the mobile repo 
https://github.com/golang/mobile/blob/master/example/basic/main.go
But it happens for me with all main packages when you try to run them in a symlink outside of the gopath.

**Comment by bradfitz** [comment]
Where are you when you try to symlink?

**Comment by bashtian** [comment]
This is my setup:

$GOPATH=/home/me/gopath
CWD=/home/me/

I think it happens anywhere outside of gopath, but works with a symlink inside the gopath.

**Comment by bradfitz** [comment]
I see. Maybe this should work. Go generally isn't too friendly towards symlinks. @rsc?

**Comment by rsc** [comment]
Please try applying this diff to cmd/go and rebuild cmd/go:

	diff --git a/src/cmd/go/pkg.go b/src/cmd/go/pkg.go
	index 5ecfcb8..85f2a50 100644
	--- a/src/cmd/go/pkg.go
	+++ b/src/cmd/go/pkg.go
	@@ -406,8 +406,20 @@ func vendoredImportPath(parent *Package, path string) (found string) {
	 	if parent == nil || parent.Root == "" {
	 		return path
	 	}
	+	// go/build decided that hasSubdir(parent.Root, parent.Dir) is true,
	+	// and that computation applies EvalSymlinks to both before
	+	// doing the string comparison.
	+	// Do the same here so that the strings match up below.
	+	// See golang.org/issue/14054.
	 	dir := filepath.Clean(parent.Dir)
	-	root := filepath.Join(parent.Root, "src")
	+	if p, err := filepath.EvalSymlinks(dir); err == nil {
	+		dir = p
	+	}
	+	root := parent.Root
	+	if p, err := filepath.EvalSymlinks(root); err == nil {
	+		root = p
	+	}
	+	root = filepath.Join(root, "src")
	 	if !hasFilePathPrefix(dir, root) || len(dir) <= len(root) || dir[len(root)] != filepath.Separator {
	 		fatalf("invalid vendoredImportPath: dir=%q root=%q separator=%q", dir, root, string(filepath.Separator))
	 	}

If it fixes your problem (it seems to on my machine) I will work up a test case and try to get it into the final release. Thanks.

**Comment by bashtian** [comment]
@rsc Thanks, this patch fixed the problem

**Comment by rsc** [comment]
Sorry, testing discovered a few problems with that patch. New approach at https://go-review.googlesource.com/19102. If you can try that, it'd be great, but I've verified that it fixes the mobile example above.

**Comment by bashtian** [comment]
@rsc works for me as well, thanks for the quick fix
