### ISSUE TITLE
net: test fails on netbsd7-amd64

### ISSUE THREAD

**Issue by rillig** [golang/go#14050]
Go version: devel from https://go-review.googlesource.com/#/c/18776/3
Platform: netbsd7-amd64

When I bootstrap the compiler using the following command, it fails.

    $ (cd src && env GOROOT_BOOTSTRAP=$HOME/pkg/go GOROOT_FINAL=$HOME/godev bash ./all.bash)

The output is:

```
ok      mime/multipart  2.530s
ok      mime/quotedprintable    1.526s
--- FAIL: TestLookupDotsWithLocalSource (0.00s)
        lookup_test.go:446: netgo: got localhost.; want localhost
        lookup_test.go:446: netcgo: got localhost.; want localhost
FAIL
FAIL    net     9.227s
ok      net/http        19.109s
ok      net/http/cgi    0.267s
```

**Comment by minux** [comment]
We really need a netbsd/amd64 builder.

**Comment by mikioh** [comment]
Can you show us /etc/hosts, /etc/resolv.conf and /etc/resolvconf.conf on the node under test?

**Comment by rillig** [comment]
[/etc/hosts](http://cvsweb.netbsd.org/bsdweb.cgi/src/etc/hosts?rev=1.9&content-type=text/x-cvsweb-markup):

    ::1                     localhost localhost.
    127.0.0.1               localhost localhost.

/etc/resolv.conf:

    nameserver 192.168.43.1
