### ISSUE TITLE
Integrate some additional stream and block ciphers

### ISSUE THREAD

**Issue by andhamm** [golang/go#14057]
My question: Is there a plan to integrate several crypto-primitives to go as additional packages? If so, some implementation ( Serpent, HC128/HC256 ), ready for integration, can be found [here](https://github.com/andhamm/crypto). I'm currently working on Chacha20 (the orig. and the RFC version) - so if there's the wish for additional cryptographic in go, may take a look.

**Comment by bradfitz** [comment]
There's a lot of stuff in golang.org/x/crypto ... https://godoc.org/golang.org/x/crypto

You can discuss on the golang-dev mailing list and contribute code using https://golang.org/doc/contribute.html
