### ISSUE TITLE
runtime: TestCgoExternalThreadSIGPROF fails on netbsd7-amd64

### ISSUE THREAD

**Issue by rillig** [golang/go#14052]
Go version: devel from https://go-review.googlesource.com/#/c/18776/3
Platform: netbsd7-amd64

When I bootstrap the compiler using the following command, it fails.

    $ (cd src && env GOROOT_BOOTSTRAP=$HOME/pkg/go GOROOT_FINAL=$HOME/godev bash ./all.bash)

The output is:

```
ok      regexp  1.385s
ok      regexp/syntax   0.956s
--- FAIL: TestCgoExternalThreadSIGPROF (0.02s)
        crash_cgo_test.go:96: expected "OK\n", but got:
--- FAIL: TestSignalExitStatus (0.01s)
        crash_unix_test.go:145: test program succeeded unexpectedly
FAIL
FAIL    runtime 93.289s
ok      runtime/debug   0.359s
ok      runtime/internal/atomic 0.376s
```

**Comment by bradfitz** [comment]
Is this a regression from Go 1.5, or a breakage from NetBSD 6 to NetBSD 7?

**Comment by ianlancetaylor** [comment]
I have a patch for TestCgoExternalThreadSIGPROF that I will send soon.

Coincidentally I opened issue #14063 earlier today for TestSignalExitStatus.  I have no idea what is going on with that one.

**Comment by rillig** [comment]
@bradfitz 

On go1.5.3 netbsd7 amd64 it looks similar, but still different:

```
ok      regexp  1.770s
ok      regexp/syntax   1.040s
--- FAIL: TestCgoExternalThreadSIGPROF (3.61s)
        crash_cgo_test.go:95: expected "OK\n", but got ""
FAIL
FAIL    runtime 135.428s
ok      runtime/debug   0.500s
exit status 255
FAIL    runtime/pprof   0.230s
ok      runtime/trace   65.243s
ok      sort    0.145s
```
