### ISSUE TITLE
runtime: TestSignalExitStatus fails on NetBSD, flaky on Solaris, FreeBSD

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14063]
The runtime package test TestSignalExitStatus fails on NetBSD.  The program kills itself with SIGTERM, but the process still somehow manages to exit with a zero status.  I have not been able to recreate the problem using a C program.  I do not see anything interesting running ktruss.  I have no idea why this fails.  I'm to change the test to skip on NetBSD, and I'm filing this issue for reference.

**Comment by bradfitz** [comment]
Also seen a few times on Solaris recently. e.g. http://build.golang.org/log/38a44f48270e2fa571f78ce123a6bc9c1c1cd120

/cc @4ad

**Comment by bradfitz** [comment]
Also seen being flaky on freebsd-arm:
https://build.golang.org/log/373efb0b65530ff78563ae17db27c9a8a395a6ee
