### ISSUE TITLE
x/tools/cmd/godoc: URLs to source should be permalinks

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14062]
When people link to golang.org source URLs like https://golang.org/src/net/http/fs.go?s=1591:1755#L52 I always cringe, knowing those links will be broken at the next release, and then we have broken links in mailing list archives.

It'd be nice if we could generate permalinks instead, baking in the version of the file to the links, and then find the right content if needed.

/cc @adg

**Comment by seankhliao** [comment]
pkgsite links to versioned sources
