### ISSUE TITLE
go: return sugar

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#14066]
https://gobyexample.com/reading-files

```go
func check(e error) {
    if e != nil {
        panic(e)
    }
}
```

`check` makes the code clean enough but you can't use `check` if your function returns a `err` which is the most common case.

```go
func example()  error {
     dat, err := ioutil.ReadFile("/tmp/dat")
     if err != nil {
          return err
     }
     ...
}
```

I looked around and didn't find any tickets about it, but what about a little bit of sugar to auto return a value as soon as it is assigned and not nil?

```go
func example()  error {
     dat, !err := ioutil.ReadFile("/tmp/dat")
     ...
}
```

```go
func split() (int, int) {
    !(x, y) := 6, 5
    ...
}
```

**Comment by bradfitz** [comment]
This has been proposed in dozens of forms ad nauseam here and elsewhere. Even if this were to go through the https://golang.org/s/proposal-process, I have no belief it would fare better than the previous proposals.

For previous proposals, I see at least 8 searching the golang-nuts mailing list for "error handling sugar".

**Comment by gertcuykens** [comment]
ok :)

**Comment by bradfitz** [comment]
You're more than welcome to write a formal proposal using https://golang.org/s/proposal-process but the bar for language changes at this point is pretty much impossible (and has been for years), so you'd have to be very convincing with lots of data to back you up on how this would affect Go programs out there.

**Comment by gertcuykens** [comment]
Understandably so :) you don't want to have a python 2, 3 scenario. I couldn't see any issue for breaking current syntax but I am not a expert. Anyway will ask for more expert advice on golang-nuts first.
