### ISSUE TITLE
cmd/asm: confusing syntax error about EOF meaning end-of-line

### ISSUE THREAD

**Issue by rsc** [golang/go#14071]
$ cat x.s
	TEXT foo(SB), $0
		JMP 1(PC) MORE TEXT HERE
		RET
	$ go tool asm x.s
	x.s:2: expected EOF, found MORE
	asm: asm: assembly of x.s failed
	$ 

Use of EOF here to mean end-of-line is confusing.

/cc @robpike

**Comment by tshprecher** [comment]
I posted a review for the fix: https://go-review.googlesource.com/19731

New output:

$ cat test.s
TEXT foo(SB), $0
JMP 1(PC)  MORE TEXT HERE
RET
$ go tool asm test.s
test.s:2: expected end of operand, found MORE
asm: assembly of test.s failed
