### ISSUE TITLE
x/tools/cmd/goimports: use of own package name creates broken imports

### ISSUE THREAD

**Issue by ScottMansfield** [golang/go#14073]
When running goimports on a file in a package that (wrongly) uses it's own name as a qualifier, goimports will rewrite the imports to include the code file's own package in the imports. Goimports shows no error and only on compilation will there be an import cycle error.

I propose that Instead of the imports being rewritten, a check be performed to see if the file is in the same package as goimports is trying to add. If this situation is detected, the command should fail and output an error message instead of rewriting.

I'll be working on patching this behavior if this proposal sounds appropriate.

cc: @alandonovan (since I think you're the one to ask)

**Comment by alandonovan** [comment]
Brad owns goimports.  The feature seems reasonable though.

cc: @bradfitz, @crawshaw

**Comment by bradfitz** [comment]
I wrote goimports once. I wouldn't say I own it. :)

**Comment by bradfitz** [comment]
(I unassigned it so anybody can feel free to fix. I don't want to give the impression that I'm actively working on or planning on working on this)

**Comment by ScottMansfield** [comment]
I can take a stab at it, we'll see if it as easy a fix as I hope it is :)

**Comment by davidrjenni** [comment]
@ScottMansfield, are you working on it? If not, I would like to try to come up with a fix.

**Comment by ScottMansfield** [comment]
@davidrjenni Nope, I never did get around to it. By all means, please go ahead. This bit me again recently, but it turned out to be not as much of a nuisance in the mean time so I forgot about it.

**Comment by heschik** [comment]
I think this was resolved in #30663. Please comment if you disagree.
