### ISSUE TITLE
cmd/go: Add support for `go get {tarball URL}`

### ISSUE THREAD

**Issue by mappu** [golang/go#14076]
**Feature request**

It should ultimately become possible to `go get https://example.com/path/to/release-latest.tar.xz` and use the package as `import "example.com/path/to/release"`, or something like that.

**Rationale**

1. To support a pre-existing packaging workflow that produces tarball artefacts
2. To offer a maximally lightweight method for deploying `go get`-able packages on low-end servers.

**Implementation**

I think it should be possible to implement initially in `src/cmd/go/vcs.go` as a new `vcsCmd` type that shells out to external wget/curl and tar binaries, in much the same way as the existing code.

The go-get process for tarballs is simple enough that it should eventually be rewritten to use internal http/tar/unzip libraries where possible, improving the cross-platform story (especially on Windows where external curl/wget/tar binaries are unexpected). But, i think this would require refactoring the helper method `func (v *vcsCmd) run1` to not always assume it's operating on an external command binary - and `archive/tar` does not automatically implement compression for the common case of `tar.(gz|bz2|xz)`, so that would need to be processed too.

**Comment by bradfitz** [comment]
Sorry, but this is not a direction we're interested in going. The argument to "go get" is a package name, not a URL.
