### ISSUE TITLE
runtime/race: TestRaceChanCloseSend failed once

### ISSUE THREAD

**Issue by rsc** [golang/go#14079]
Seen during an unrelated trybot run on linux-amd64-race builder.
https://storage.googleapis.com/go-build-log/51c1aa35/linux-amd64-race_e41788ba.log

/cc @dvyukov

		=== RUN   TestRaceChanCloseSend
		==================
		WARNING: DATA RACE
		Read by goroutine 60:
		  runtime.chansend()
		      /tmp/workdir/go/src/runtime/chan.go:115 +0x0
		  command-line-arguments_test.TestRaceChanCloseSend()
		      /tmp/workdir/go/src/runtime/race/testdata/chan_test.go:577 +0xbe
		  testing.tRunner()
		      /tmp/workdir/go/src/testing/testing.go:473 +0xdc
		
		Previous write by goroutine 59:
		  runtime.closechan()
		      /tmp/workdir/go/src/runtime/chan.go:292 +0x0
		  command-line-arguments_test.TestRaceChanCloseSend.func1()
		      /tmp/workdir/go/src/runtime/race/testdata/chan_test.go:574 +0x2e
		
		Goroutine 60 (running) created at:
		  testing.RunTests()
		      /tmp/workdir/go/src/testing/testing.go:582 +0xae2
		  testing.(*M).Run()
		      /tmp/workdir/go/src/testing/testing.go:515 +0x11d
		  main.main()
		      command-line-arguments/_test/_testmain.go:736 +0x210
		
		Goroutine 59 (running) created at:
		  command-line-arguments_test.TestRaceChanCloseSend()
		      /tmp/workdir/go/src/runtime/race/testdata/chan_test.go:576 +0x91
		  testing.tRunner()
		      /tmp/workdir/go/src/testing/testing.go:473 +0xdc
		==================
		--- FAIL: TestRaceChanCloseSend (0.00s)

**Comment by mikioh** [comment]
On freebsd-amd64-race builder: http://build.golang.org/log/70e1fc51b96bbac00e875f6c8ca3305dc1c39c12

**Comment by rsc** [comment]
Reopening because that CL can only explain false negatives. This is a false positive.

**Comment by dvyukov** [comment]
This test sends on a closed chan. The intention is that only the race is reported but no panic happens, but in this case it actually paniced. It is a legit outcome. Again due to unexpected scheduling order.
