### ISSUE TITLE
runtime: random fatal errors on iOS

### ISSUE THREAD

**Issue by mikioh** [golang/go#14070]
/cc @ianlancetaylor 

According to the dashboard, the build started to fail with signal failures with a7cad52e04dd1890420452b38563997930edb2ca.

Before (mostly timeouts): http://build.golang.org/log/a04d0ed55471343ddd7dec8bb8ef9459cc02588e
After (signal failures): http://build.golang.org/log/32a73620035a8c1101d15bcbbdce2cdce640d70f

**Comment by mikioh** [comment]
We can observe typically:
- fatal error: runtime: stack split at bad time on log/syslog test
-  fatal error: unexpected signal during runtime execution [signal 0xb code=0x1 addr=0x0 pc=0x4066590] on net test
- fatal error: runtime: stack split at bad time on net/http test
- fatal error: unexpected signal during runtime execution [signal 0xb code=0x1 addr=0x0 pc=0x4064204] on os/signal test
- fatal error: runtime: stack split at bad time on time test

**Comment by ianlancetaylor** [comment]
Those errors do look similar to the ones we saw on NetBSD and DragonFly.

@crawshaw Is it possible for you to run this C program on Darwin/ARM, to see how signal stacks are handled for newly created threads?

    #include <errno.h>
    #include <signal.h>
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <pthread.h>

    static void
    die (const char *s)
    {
      perror (s);
      exit (EXIT_FAILURE);
    }

    static void
    printsigstack (const char *prefix)
    {
      stack_t ss;

      if (sigaltstack (NULL, &ss) < 0)
	die ("sigaltstack get");
      printf ("%s %p 0x%lx 0x%x\n", prefix, ss.ss_sp, (unsigned long) ss.ss_size,
	      (unsigned int) ss.ss_flags);
    }

    static void *
    thread (void *arg)
    {
      stack_t ss;

      printsigstack ("thread");
      ss.ss_sp = malloc (SIGSTKSZ);
      if (ss.ss_sp == NULL)
	die ("malloc");
      ss.ss_size = SIGSTKSZ;
      ss.ss_flags = 0;
      if (sigaltstack (&ss, NULL) < 0)
	die ("sigaltstack set");
      return NULL;
    }

    int
    main ()
    {
      pthread_t tid;
      int i;
      stack_t ss;

      printsigstack ("main 1");

      i = pthread_create (&tid, NULL, thread, NULL);
      if (i != 0)
	{
	  errno = i;
	  die ("pthread_create");
	}

      i = pthread_join (tid, NULL);
      if (i != 0) {
	errno = i;
	die ("pthread_join");
      }

      printsigstack ("main 2");

      ss.ss_sp = malloc (SIGSTKSZ);
      if (ss.ss_sp == NULL)
	die ("malloc");
      ss.ss_size = SIGSTKSZ;
      ss.ss_flags = 0;
      if (sigaltstack (&ss, NULL) < 0)
	die ("sigaltstack set");

      printsigstack ("main 3");

      i = pthread_create (&tid, NULL, thread, NULL);
      if (i != 0)
	{
	  errno = i;
	  die ("pthread_create");
	}

      i = pthread_join (tid, NULL);
      if (i != 0) {
	errno = i;
	die ("pthread_join");
      }

      printsigstack ("main 4");

      return 0;
    }

**Comment by minux** [comment]
I run the program on iOS 5.1.1 and the output is:
main 1 0x0 0x0 0x4
thread 0x0 0x0 0x4
main 2 0x0 0x0 0x4
main 3 0x33000 0x20000 0x0
thread 0x0 0x0 0x4
main 4 0x33000 0x20000 0x0

**Comment by crawshaw** [comment]
For a few (uninteresting) reasons it would take me a couple of hours work to run this. Hopefully the run by @minux does the job.

**Comment by ianlancetaylor** [comment]
The run by minux tells me that the problem on iOS is not the same as the problem on NetBSD and DragonFly.  This will require more investigation.
