### ISSUE TITLE
build: darwin-386-10_10 builder not using cgo?

### ISSUE THREAD

**Issue by rsc** [golang/go#14083]
I just found that running

	GOARCH=386 GOHOSTARCH=386 ./all.bash

was broken on my Mac, due to a cgo test failure. CL sent fixing it, but my guess is that the darwin-386-10_10 builder shown on the dashboard only sets GOARCH, not also GOHOSTARCH. It should set both.

/cc @bradfitz @crawshaw

**Comment by bradfitz** [comment]
Indeed. It's only setting GOARCH=386. I don't remember why. I'll change.
