### ISSUE TITLE
cmd/go: unable to detect version control system for code.google.com

### ISSUE THREAD

**Issue by dz0ny** [golang/go#14096]
Looks like someone ran that migration too quickly :)

```
go version
go version go1.5.2 linux/amd64

go get code.google.com/p/mahonia
package code.google.com/p/mahonia: unable to detect version control system for code.google.com/ path
```

**Comment by mikioh** [comment]
See https://go-review.googlesource.com/#/c/18952

**Comment by ianlancetaylor** [comment]
@dz0ny code.google.com has shut down.  I don't think there is anything we can do to fix this issue.  Please feel free to reopen if you think there is.
