### ISSUE TITLE
Padding issues a bug or something expected?

### ISSUE THREAD

**Issue by aanm** [golang/go#14094]
I have a structure with the following variables with go version go1.5.1 linux/amd64
```go
type Foo struct {
    VarA uint64
    VarB uint32
}
```
and I created the `f` variable of `Foo` type with some values:
```go
f := Foo{
    VarA: 9720496, 
    VarB: 3,
}
```
when I printed that variable with gdb I saw something that I was not expecting:
```gdb
(gdb) x/4w &f 
0xc82008cc18:   0x009452b0      0x00000000      0x00000003      0x000000c8
```
where did the 'c8' came frome?
the `unsafe.Sizeof(f)` have a result of 16. Should I assume that golang doesn't set the padding bytes with zero as well?

As a workaround I had to add a variable `unused` so it would be clean.
```go
type Foo struct {
    VarA   uint64
    VarB   uint32
    unused uint32
}
```
```gdb
(gdb) x/4w &f 
0xc82008cc18:   0x009452b0      0x00000000      0x00000003      0x00000000
```
Is this normal?
Thanks

**Comment by randall77** [comment]
Yes.  Go does not make any promises about padding bytes.  They might be 0, they might not.  If you care about what those values are, do as you did in the workaround.

Typically only stack variables will have nonzero padding bytes.  Of course with unsafe you can manufacture them anywhere.

**Comment by aanm** [comment]
Thanks for the reply, can you point me where I can found the docs stating that? I tried to find that before I filled the issue but wasn't able to. Thanks!

**Comment by ianlancetaylor** [comment]
There are no docs about the padding bytes because Go makes no promises about them.  Any specific behavior may change in future releases or different implementations.  We don't generally document that there is nothing to document.
