### ISSUE TITLE
x/build/cmd/gopherbot: fails to mention some CLs on their issues

### ISSUE THREAD

**Issue by mdempsky** [golang/go#14090]
Gopherbot never commented about https://golang.org/cl/18623/ or https://golang.org/cl/18860/ on their respective issues.

@bradfitz conjectured that it could be due to the trailing period in the "Fixes #NNNN." commit message line, but https://golang.org/cl/18911/ uses the same syntax and was mentioned by gopherbot.

I suspect it has to do with me immediately commenting "R=go1.7" on both CLs.

/cc @rsc

**Comment by bradfitz** [comment]
Looks like it did eventually. I guess it was just stuck. Much has improved in maintner & gopherbot in the past 3 years. I assume this is better now.
