### ISSUE TITLE
Time parsing doesn't work with string time zone offsets

### ISSUE THREAD

**Issue by ewtroan-pendo** [golang/go#14109]
Some timezone parsing doesn't work properly from what I can tell. It seems like it should be the case that:

time.Parse(time.RFC1123,  time.RFC1123).Unix() == 1136239445

(this is missing error checking, etc -- see the play for a working example). The MST seems to not be parsed properly (oddly it makes it into the resulting time object from Parse() and gets displayed ,but the offset doesn't seem to be applied). Note that some time formats (those with numeric offsets) do work.

time.Parse(time.RFC1123Z,  time.RFC1123Z).Unix() == 1136239445

http://play.golang.org/p/FGdOKMwznE

**Comment by minux** [comment]
The abbreviated timezone identifier is ambiguous
without a location.

That is, if your location doesn't have a MST timezone,
then time.Parse won't work, as it happens in playground.

This is working as intended.

**Comment by ewtroan-pendo** [comment]
Thank you. I assumed since it was an RFC time it was parseable in a way which would invert formatting a time with it. After more research I'm clearly incorrect.
