### ISSUE TITLE
website: playground not showing on homepage

### ISSUE THREAD

**Issue by broady** [golang/go#14108]
Only on tip:
http://tip.golang.org/

Flashes for a moment, then disappears.

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36`

**Comment by minux** [comment]
It's probalby because -play option is not
passed to the godoc program.

**Comment by adg** [comment]
This is expected behavior. We don't want to show the playground on tip, because the sandbox is almost never running the same version of Go as tip.
