### ISSUE TITLE
net/http: why isn't there any mentioning about the need for usage of UTC with http.TimeFormat??

### ISSUE THREAD

**Issue by elico** [golang/go#14103]
I was trying to use the http.TimeFormat to format a http response and the way I found to do that is using:
time.Now().UTC().Format(http.TimeFormat) 
which uses the format ...
const TimeFormat = "Mon, 02 Jan 2006 15:04:05 GMT"

But it's just using the format to output a string with a GMT in it.
I have seen that everywhere in the golang code it's being used with a UTC() time conversion and I think that it is worth to mention that it *uses* the local time but just adds a GMT to it unless the time is being converted to UTC using the UTC() function.
I encountered this issue more then once in the last couple month and I have not found anything actually mentioning it that you need to use UTC() with it in the docs.(which can confuse).
Can a small addition to the http.TimeFormat  constant documentation be added??

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bradfitz** [comment]
Sure. https://golang.org/cl/18933

**Comment by elico** [comment]
Thanks!
