### ISSUE TITLE
runtime: TestNumGoroutine flaky 

### ISSUE THREAD

**Issue by mdempsky** [golang/go#14107]
runtime.TestNumGoroutine has flaked at least 3 times recently on openbsd/amd64 with the same failure message:

    --- FAIL: TestNumGoroutine (0.02s)
    	proc_test.go:353: NumGoroutine=3, but found 4 goroutines in stack dump

http://build.golang.org/log/3d5e0edfe768d25a87fe5b3806ec2f846cdfa34f
http://build.golang.org/log/3199fe0c622947092e3fd724dc95176bc6513795
http://build.golang.org/log/b6527fd60a2a459e2c6d1ed2d34fcf7121806f92

**Comment by bradfitz** [comment]
You filed this just as I sent a CL: https://go-review.googlesource.com/18938

**Comment by bradfitz** [comment]
And we have output:

http://build.golang.org/log/27397aad98df8b5ba9c800480156ed29b95f5dd9
```
--- FAIL: TestNumGoroutine (0.02s)
	proc_test.go:353: NumGoroutine=3, but found 4 goroutines in stack dump: goroutine 207553 [running]:
		runtime_test.TestNumGoroutine(0xc82042a000)
			/tmp/workdir/go/src/runtime/proc_test.go:348 +0x14c
		testing.tRunner(0xc82042a000, 0x7d0f58)
			/tmp/workdir/go/src/testing/testing.go:473 +0x98
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:582 +0x892
		
		goroutine 1 [chan receive]:
		testing.RunTests(0x6f0160, 0x7d0340, 0xa7, 0xa7, 0x4cc401)
			/tmp/workdir/go/src/testing/testing.go:583 +0x8d2
		testing.(*M).Run(0xc820159ef8, 0x75f098)
			/tmp/workdir/go/src/testing/testing.go:515 +0x81
		runtime_test.TestMain(0xc820159ef8)
			/tmp/workdir/go/src/runtime/crash_test.go:24 +0x28
		main.main()
			runtime/_test/_testmain.go:932 +0x114
		
		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/tmp/workdir/go/src/runtime/asm_amd64.s:1998 +0x1
		
		goroutine 207554 [runnable]:
		runtime.goexit1()
			/tmp/workdir/go/src/runtime/proc.go:2159
		runtime.goexit()
			/tmp/workdir/go/src/runtime/asm_amd64.s:1999 +0x6
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:582 +0x892
```

**Comment by bradfitz** [comment]
And another, same:
https://storage.googleapis.com/go-build-log/aa2f8572/openbsd-amd64-gce58_14210b99.log

**Comment by bradfitz** [comment]
Hey, now one on Linux-arm!

https://storage.googleapis.com/go-build-log/fae00030/linux-arm_acd2e3b8.log

```
--- FAIL: TestNumGoroutine (0.05s)
	proc_test.go:353: NumGoroutine=3, but found 4 goroutines in stack dump: goroutine 312375 [running]:
		runtime_test.TestNumGoroutine(0x1050e2a0)
			/workdir/go/src/runtime/proc_test.go:348 +0x10c
		testing.tRunner(0x1050e2a0, 0x32eb6c)
			/workdir/go/src/testing/testing.go:473 +0xa8
		created by testing.RunTests
			/workdir/go/src/testing/testing.go:582 +0x600
		
		goroutine 1 [chan receive, locked to thread]:
		testing.RunTests(0x27f1c0, 0x32e548, 0xac, 0xac, 0x10572001)
			/workdir/go/src/testing/testing.go:583 +0x62c
		testing.(*M).Run(0x10533f7c, 0xc7ba0)
			/workdir/go/src/testing/testing.go:515 +0x8c
		runtime_test.TestMain(0x10533f7c)
			/workdir/go/src/runtime/crash_test.go:24 +0x1c
		main.main()
			runtime/_test/_testmain.go:982 +0x118
		
		goroutine 17 [syscall, 1 minutes, locked to thread]:
		runtime.goexit()
			/workdir/go/src/runtime/asm_arm.s:991 +0x4
		
		goroutine 4 [runnable]:
		runtime.SetFinalizer(0x21dea8, 0x11520370, 0x0, 0x0)
			/workdir/go/src/runtime/mfinal.go:285 +0x118
		os.(*Process).release(0x11520370, 0x0, 0x0)
			/workdir/go/src/os/exec_unix.go:66 +0x4c
		os.(*Process).Release(0x11520370, 0x0, 0x0)
			/workdir/go/src/os/doc.go:31 +0x28
FAIL
FAIL	runtime	120.318s
```

**Comment by rsc** [comment]
The goal of the check there (which I only added relatively recently) was to make sure that NumGoroutine was not consistently different from than the number of stacks shown (because one includes system goroutines and one does not). The check is fundamentally racy in that they might see different pictures of the world. I sent CL 19002 to try to reduce the race window. That may be enough. We'll see. In any event I'm not worried about the failures, except as far as they are annoying. Hopefully that CL will cut the frequency enough. If not we can do a retry loop up to 10 times or something.

**Comment by mdempsky** [comment]
Is it suspicious at all that goroutine 4's trackback in the linux-arm repro doesn't have a "created by" line?

**Comment by aclements** [comment]
`os.(*Process).Release` in the last goroutine is a finalizer, so probably it happened to be running during the Stack call and then returned before the NumGoroutine call.

Plus, since Stack stops and restarts the world, it's throwing the scheduler state in to the air, which is probably making this sort of thing more likely.

I think Russ is right that the best we can do is retry a few times.

**Comment by aclements** [comment]
> Is it suspicious at all that goroutine 4's trackback in the linux-arm repro doesn't have a "created by" line?

I was wondering about that, too. That goroutine is the runfinq goroutine, so it was created by a runtime function. printcreatedby elides the "created by" message using the same rules that apply to eliding frames, so it doesn't get printed.

**Comment by mdempsky** [comment]
@aclements Duh, thanks!  Somehow `SetFinalizer` being at the top of the call stack made me rule out that `os.(*Process).Release` could itself have been set as a finalizer.
