### ISSUE TITLE
x/sys/unix: missing xattr symlink xattr syscall functions

### ISSUE THREAD

**Issue by mildred** [golang/go#14116]
The following syscall functions are not implemented, but are necessary if you need to copy symlinks while preserving xattrs:
- llistxattr
- lgetxattr
- lsetxattr
- lremovexattr

Are they going to be implemented? How can we implement them in a separate package?

**Comment by ianlancetaylor** [comment]
The syscall package is more or less frozen, and new system calls are added to the golang.org/x/sys package instead.

**Comment by mildred** [comment]
I learned that. Is there a specific bugtracker for the sys package?

**Comment by minux** [comment]
All subrepo bugs are tracked here too.
