### ISSUE TITLE
net/http: document and protect against unsafe use of ServeFile

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14110]
Martin Lenord notes:

> I've seen this method of handling static files crop up a couple of times:
> http://stackoverflow.com/questions/25945538/go-golang-to-serve-a-specific-html-file
> http://jessekallhoff.com/2013/04/14/go-web-apps-serving-static-files/
>
> Using `http.ServeFile(w, r, r.URL.Path[1:])` to serve up a directory.
> ...

Normally ServeMux protects against this on accident, but it's not a good defense because there are ways around it and not everybody uses ServeMux.

We should instead document louder that it's unsafe, and add some protections against it.

**Comment by nhooyr** [comment]
@bradfitz what ways are there around ServeMux's defence on this?
