### ISSUE TITLE
cmd/cgo: cgo with external linking for linux/mips64

### ISSUE THREAD

**Issue by eswierk** [golang/go#14126]
Implement cgo with external linking for linux/mips64 and linux/mips64le (MIPS N64 ELF ABI, big- and little-endian). Work includes:

- complete external linking support (https://github.com/golang/go/issues/12560)
- fill in the portions of [src/runtime/asm_mips64x.s](https://github.com/golang/go/blob/master/src/runtime/asm_mips64x.s) marked "no cgo yet", plus whatever else cgo requires
- enable cgo external link tests, and get (cd [misc/cgo/test](https://github.com/golang/go/tree/master/misc/cgo/test) && go test -linkmode=external) to pass on Linux on mips64 and mips64le hardware

Initial testing can be done using qemu-user for mips64 and mips64le targets running on any host. [Skyport Systems](https://www.skyportsystems.net/) (my employer) can also provide access to mips64le hardware for testing.

See https://github.com/golang/go/issues/8912 for a description of similar work for ppc64 (though internal linking support is optional/extra credit). For a working example, browse the current arm64 code, which supports exactly the functionality sought for mips64 (cgo with external linking, not internal linking).

**Comment by eswierk** [comment]
Background info, for the benefit of a potential bounty hunter...

[How cgo works](https://golang.org/src/runtime/cgocall.go), from the horse’s mouth. Plus an explanation of golang's odd x86-ish [assembly language](https://golang.org/doc/asm). Some of the links to Plan9 docs are broken; use this [archive](https://web.archive.org/web/http://plan9.bell-labs.com/sys/doc/index.html) instead.

The [Altoros blog series on golang internals](http://blog.altoros.com/golang-part-1-main-concepts-and-project-structure.html) has lots of useful info about code generation, linking, relocations, assembly.

Explanation of golang’s clever [conditional compilation](http://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) features (build tags and magic filenames).

For brushing up on MIPS trivia: [N32/N64 ABI](http://techpubs.sgi.com/library/manuals/2000/007-2816-005/pdf/007-2816-005.pdf) and [other ABIs](https://dmz-portal.mips.com/wiki/MIPS_ABI_Project), [ELF relocation types](https://dmz-portal.mips.com/wiki/MIPS_relocation_types).

There is probably some overlap with the voodoo that needs to be [added to libffi to support closures with gccgo on mips64](https://github.com/atgreen/libffi/pull/197).

**Comment by minux** [comment]
The cgo support is not very difficult, but would it be possible
for you contribute a big endian linux/mips64 builder? We
need one to move forward with the port. Thanks a lot.

**Comment by eswierk** [comment]
@minux We only have little endian mips64 currently. Would that be useful to you?
