### ISSUE TITLE
net: TestListenerClose flaky on dragonfly

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14124]
Bunch of these lately:

http://build.golang.org/log/1cb49fcb72f133c814d420106795a4aca11607b6
```
--- FAIL: TestListenerClose (0.00s)
	net_test.go:227: Dial to closed TCP listener succeeeded.
FAIL
FAIL	net	1.891s
```

/cc @mikioh

**Comment by mikioh** [comment]
Note that this is a regression in Go 1.6, which is introduced by 19aa4209aebce5deaf485268e210ed3fc29cacd5.
