### ISSUE TITLE
cmd/go: assume .c files are for cgo

### ISSUE THREAD

**Issue by rsc** [golang/go#14123]
CL 19003 is kind of stupid.
It's left over from when a .c file could be intended for cgo or for the Go (Plan 9) C compiler.
The Plan 9 C compiler was removed in Go 1.5 and stayed removed in Go 1.6
(not that there was any doubt).
For Go 1.7 we could consider assuming that .c files are for cgo and remove the logic in the go command that considers they might be for the Plan 9 C compiler. Two releases is likely long enough to get people with Plan 9 C files to convert, if there were any people to begin with.

/cc @bradfitz @robpike

**Comment by ianlancetaylor** [comment]
For anybody who fixes this, note that there is a special case for files whose names start with "gcc_" in the runtime/cgo package.  That special case can be removed when this is fixed.  Actually it could be removed now.

**Comment by ianlancetaylor** [comment]
(The special case is in builder.build in cmd/go/build.go.)

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/#/c/19613/5
