### ISSUE TITLE
io: PipeWriter.Write should not block when writing zero bytes

### ISSUE THREAD

**Issue by jongillham** [golang/go#14139]
`io.PipeWriter.Write([]byte{})` blocks when no readers are waiting at the other end of the pipe. To unblock the pipe **zero** or more bytes must be read from `io.PipeWriter.Read`.

I expect `io.PipeWriter.Write([]byte{})` to not ever block.

See https://groups.google.com/forum/#!topic/golang-nuts/nRPhBt0zoAM for the discussion.

See http://play.golang.org/p/MNSyKafKYf for an example.

**Comment by extemporalgenome** [comment]
What's the behavior of network or stdio paired writes when there are no corresponding blocking readers? I figure it should emulate that behavior, whatever it is.

**Comment by ianlancetaylor** [comment]
There are uses for zero-byte writes, exactly to see whether there are readers, but since nothing is documented it seems unlikely that anybody is relying on it.

Whatever we decide, we should document the behavior.

**Comment by rsc** [comment]
io.Pipe preserves message boundaries. Writes and Reads are paired one to one (except when it requires multiple Reads to consume a single Write). Write should block when writing zero bytes, until a Read comes along and takes them.

**Comment by bradfitz** [comment]
We have so many random rules for 0 byte reads & writes. I'll add this to my mental list of special cases. This might be fine behavior for a PipeFoo but it'd be really nice to define semantics for 0-byte operations on the io.Reader and io.Writer interfaces.

**Comment by quentinmit** [comment]
@rsc Does that make this WAI? Or should we repurpose this issue to improve the documentation?

**Comment by bradfitz** [comment]
Yes, it sounds like documentation.
