### ISSUE TITLE
cmd/compile: deduplicated errors on same line still trigger "too many errors"

### ISSUE THREAD

**Issue by dominikh** [golang/go#14136]
For a given line, Go prints the same error only once. For example, trying to use the same unknown field in a struct initialiser multiple times will only emit one error, if that struct initialiser is written on a single line. However, each suppressed error still increments the error counter in Yyerror, which can lead to a "too many errors" even if just one error was actually printed. This can be mildly confusing, and reduces the usefulness of deduplication.

**Input**
http://play.golang.org/p/S18DnIr63o
```
package main

type T struct{}

func main() {
	t := T{X: 1, X: 1, X: 1, X: 1, X: 1, X: 1, X: 1, X: 1, X: 1, X: 1}
	var s string = 1
}
```

**Output**
```
prog.go:6: unknown T field 'X' in struct literal
prog.go:6: too many errors
```

**Expected output**
```
prog.go:6: unknown T field 'X' in struct literal
prog.go:7: cannot use 1 (type int) as type string in assignment
```

**Comment by rsc** [comment]
This seems trivial to fix, low risk (only affects compiles that will fail anyway), and probably worth fixing for Go 1.7.

**Comment by griesemer** [comment]
On it.
