### ISSUE TITLE
How accurate is timer ?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [golang/go#14132]
go version go1.5.3
ubuntu 14.04 linux/amd64
I run the test below.
```
// Ensure that the clock's AfterFunc executes at the correct time.
func TestClock_AfterFunc(t *testing.T) {
        var ok bool
        go func() {
                time.Sleep(10 * time.Millisecond)
                ok = true
        }()
        go func() {
                time.Sleep(30 * time.Millisecond)
                t.Fatal("too late")             
        }()
        gosched()

        var wg sync.WaitGroup
        wg.Add(1)
        time.AfterFunc(20*time.Millisecond, func() {
                wg.Done()
        })
        wg.Wait()
        if !ok {
                t.Fatal("too early")            
        }
}
```
I expect this test passed,but I found this accidentally failed and print "too late".

As far as I know linux x86 time interrupt interval is 10ms (100HZ), and the grain is more than 10ms, which leads to a timer with 30ms duration run before a timer with 20ms duration. 

It seems like there is a timer goroutine to manage the timer heap. So it depends on the scheduling grain I guess it is larger than 10ms , is it right ?

**Comment by bradfitz** [comment]
That looks like a data race. See http://blog.golang.org/race-detector

Therefore the question is moot since the program is incorrect.

Please move questions to a forum. See https://golang.org/wiki/Questions
