### ISSUE TITLE
os: document that FindProcess is a no-op on Unix

### ISSUE THREAD

**Issue by gaurav36** [golang/go#14146]
Hi Team,

I just find one bug in golang.

bug is this when you execute os.FindProcess (pid) command two time then its giving wrong information. ie. if process is not exist then executing os.FindProcess for that process pid again is not giving proper error, its giving nil error.

for eg execute below code:
```go
package main                                                                       
                                                                                   
import (                                                                           
        "fmt"                                                                      
        "os"                                                                       
)                                                                                  
                                                                                   
func main() {                                                                      
        pid := 12345678                                                            
                                                                                   
        if _, err := os.FindProcess(pid); err != nil {                             
                fmt.Printf("process with pid %d is not exist\n", pid)              
        }                                                                          
        if _, e := os.FindProcess(pid); e == nil {                                                                    
                fmt.Printf("process with pid %d exist\n", pid)                     
        }                                                                          
}  
```
so expected behaviour of this code is it should not print anything. but its printing that pid is exist. even process is not running.

Any help regarding this. i am using this in one of the my application.

Thanks, in advance :)

**Comment by dominikh** [comment]
Your issue is unrelated to running os.FindProcess multiple times. Running it once suffices. And the underlying cause of your problem is that on Unix-systems, os.FindProcess isn't actually doing any finding. All it does is return an *os.Process with the pid set to the argument. As such, the error will always be nil. If you ran your code on Windows, it would return an error.

**Comment by gaurav36** [comment]
@dominikh  i don't have window. wondering why golang have limited this error code to only window.

**Comment by gaurav36** [comment]
anyway its seems to be a issue because of giving wrong error information !!!!

**Comment by bradfitz** [comment]
This is documented. Working as intended.

**Comment by gaurav36** [comment]
@bradfitz  Could you please provide me the link of that document. What do you mean by "working as intended" ???

do you mean to say os.FindProcess giving correct error message in all system. ?

If that problem have fixed then i want to know where, in which version it have fixed other wise there is no point of closing known issue bug. known issue bug should always open.

**Comment by bradfitz** [comment]
Oh, it's only documented internally, not in the public docs. Okay, we can fix the docs.

**Comment by gaurav36** [comment]
@bradfitz  Thank you for opening the issue :)

Now you have changed the subject line of this bug " Golang os.FindProcess is giving wrong error information to os: document that FindProcess is a no-op on Unix "

I am using latest version of Golang and didn't saw that error message problem have solved. If error message problem had not solved yet then you should have raised separate documentation issue. Mixing of both documentation and code change issue really confusing. 

Any way closing of issue should only happen when you provide following things:
1) It should be not a bug
2) It have patch in current release or whatever release and its no longer reproducible
3) this issue is same copy of another issue which had raised by another community member.

Thank you :)

**Comment by dominikh** [comment]
There is no code issue, only a documentation issue. os.FindProcess does not check the validity of a PID on most systems. That needs to be documented. Its behaviour won't change.

**Comment by gaurav36** [comment]
@dominikh   Thanks for clearing this. That make sense. Now i will follow some other method to check whether given pid process exist in unix system or not instead of using os.FindProcess.

**Comment by bradfitz** [comment]
You can send it signal 0 to test it, assuming you have permission.

**Comment by gaurav36** [comment]
@bradfitz 
yeah, i am now doing it with kill 0 signal. 
Thank you :)
