### ISSUE TITLE
Go 1.6 Release Notes - text/template block example - missing pipeline 

### ISSUE THREAD

**Issue by blubabbuino** [golang/go#14143]
What version of Go are you using (go version)?
go version go1.6rc1 linux/amd64

What operating system and processor architecture are you using?
linux/amd64

What did you do?
read draft Go 1.6 Release Notes and tried to use new template feature {{block}} following example in release note.

In release note it gives example:
 <title>{{block "title"}}Page Title{{end}}</title>

but this omits non-optional "pipeline" for block as specified on template godoc page:
 {{block "name" pipeline}} T1 {{end}}

so when trying new feature following draft release note example I got error:
  template: test:3: missing value for block clause

What did you expect to see?
I believe example in release note should include pipeline in block clause following "title", e.g. 
 <title>{{block "title" ""}}Page Title{{end}}</title>
Using example in this form worked as expected (no error).

What did you see instead?
When trying to understand new feature by following example in release note, it was hard because release note example omitted pipeline (i.e. additional "") and gave rise to error.

**Comment by ianlancetaylor** [comment]
CC @robpike
