### ISSUE TITLE
encoding/json: Field name tag not respected when encoding if there is a space after ":"

### ISSUE THREAD

**Issue by zsck** [golang/go#14142]
I've found that, when encoding a struct into JSON, if there is a space after the colon character in the tag for the field in the struct in question, then the field will not be renamed.  Below is some very simple code demonstrating what I mean.

```go
package main

import (
	"encoding/json"
	"fmt"
)

type Person struct {
	Name string `json: "name"`
	Age  int    `json: "age"`
}

func main() {
	p := Person{"Alice", 29}
	bytes, _ := json.Marshal(p)
	fmt.Println(string(bytes))
}
```

As you can see, in the above code I've made the apparent "mistake" of adding a space in my JSON tags.
If I run this code, the output I get the following output.

```js
{"Name":"Alice","Age":29}
```

Now if I change the `struct` definition to the following

```go
type Person struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
```

and then recompile and run the code, I get the expected output

```js
{"name":"Alice","age":29}
```

--------------------------

What's interesting is that this isn't a problem when *decoding* JSON.  Reintroducing spaces after the colon character, and switching to decoding from bytes, you'll see that the struct is populated properly even though I have switched the order of the fields in the JSON. I take this to mean that the decoder understands the JSON tags even with the space when decoding.

```go
package main

import (
	"encoding/json"
	"fmt"
)

type Person struct {
	Name string `json: "name"`
	Age  int    `json: "age"`
}

func main() {
	data := []byte(`{"age": 29, "name": "Alice"}`)
	p := Person{}
	json.Unmarshal(data, &p)
	fmt.Println(p)
}
```

The output I get is, as expected,

```
{Alice 29}
```

----------------------------------

I should note that I've also experimented with using a Decoder and Encoder instead of Unmarshal and Marshal.  They suffer from the same problem (and I assume share a similar implementation to their respective counterparts).

I tested this running Go 1.5.3 on the latest OS X.  The output of `go version` is

```
go version go1.5.3 darwin/amd64
```

-----------------------------------

It seems to me that the encoding/json's decoding and encoding functionality should behave the same with regards to how struct tags are treated. I should be able to have spaces after ":" in the tag and still have struct fields encoded such that the right keys are used, especially since decoding isn't affected by this.

**Comment by ianlancetaylor** [comment]
It's working on decode because, in the absence of a tag or an exact match, Decode does a case-insensitive match of tag name to field name.

We want field tag parsing to be a simple as possible: no whitespace or any other syntax beyond what is specified.  This is working as intended.

**Comment by zsck** [comment]
@ianlancetaylor Just because it's "intended" to work that way doesn't mean it's good.
This behavior behavior is misleading and confusing. There is no indication, such as a compile-time warning, about the behavior, and it's quite confusing.
I'm not sure I understand why, in a language whose formatting tools encourage some superfluous whitespace between things like struct field names and their types, a little extra checking can't be done to avoid subtle cases like this.
Can this not be a discussion that isn't just shut down because of what your sacred spec says?

**Comment by ianlancetaylor** [comment]
Yes, this can be a discussion, but the discussion should not take place on the bug tracker.  It's not a bug: the code is working as documented and the documentation seems reasonably clear.  For discussions, please see https://golang.org/wiki/Questions .  Thanks.
