### ISSUE TITLE
Documentation: broken link to plan9.bell-labs.com

### ISSUE THREAD

**Issue by molivier** [golang/go#14147]
plan9.bell-labs.com seems to have been deactivated. There is now many broken links in packages documentation: https://github.com/golang/go/search?utf8=✓&q=plan9.bell-labs.com

For example, `path` package link to: http://plan9.bell-labs.com/sys/doc/lexnames.html. I found a mirror that can be helpful: https://9p.io/sys/doc/lexnames.html.

**Comment by QueenOfReuse** [comment]
The plan9.bell-labs.com was temporarily down, but it is back again.  It is our intention at Bell Labs to provide continued support of the plan9 website.  If you encounter a problem again, please contact me.

**Comment by bradfitz** [comment]
Thanks, @QueenOfRose!

**Comment by molivier** [comment]
Thanks you for these good news @QueenOfReuse!
Le 30 janv. 2016 4:30 PM, "QueenOfReuse" <notifications@github.com> a
écrit :
