### ISSUE TITLE
cmd/dist: ~1GB memory needed for testing, problems on arm (Raspberry Pi 2) 

### ISSUE THREAD

**Issue by myannikos** [golang/go#14144]
go version devel +6d61725 Thu Jan 28 21:10:22 2016 +0000 linux/arm

Linux raspberrypi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux
(default Raspian Jessie, updated)

When compiling and testing (all.bash) this Go version with itself, the 4 core / 1GB Pi 2 almost chokes (>90% iowait, takes a long time).

This seems unnecessary, as it is due to parallelism when running "`go tool dist test...`" especially in the `go/test` directory. I am seeing 14 x "go", 4 x "compile" and 4 x "runtest.exe" processes executing at the same time.

GOMAXPROCS setting seems to have no effect due to the code in `cmd/dist/util.go`, which sets `maxbg` to at least 4 even on low memory 4 core systems like the Pi 2. It seems that builds could run much more smoothly with even 512MB if GOMAXPROCS was honored there.

**Comment by bradfitz** [comment]
Timeout. Moving to Go 1.8, unless @davecheney has an easy fix.

**Comment by myannikos** [comment]
No memory shortage issues on Pi2 with `all.bash` building +b3bf2e7 (about ~150M left of 1GB). Closing issue, thanks.
