### ISSUE TITLE
tour: text does not make sense unless you're familiar with shift operators

### ISSUE THREAD

**Issue by mjbrender** [golang/go#14151]
Context: https://tour.golang.org/basics/16

I love this tour and only take the time to give feedback due to that appreciation. This example uses shift operators in this block: 
 
```
const (
	Big   = 1 << 100
	Small = Big >> 99
)
```

I found this code, along with the description of how conversation is taking place, to require knowledge of the operators in use. It seems reasonable to give a brief instruction on the operators in use or at least why they're there. 

Existing text: 

> Numeric constants are high-precision values.
> 
> An untyped constant takes the type needed by its context.
> 
> Try printing needInt(Big) too.
> 
> (An int can store at maximum a 64-bit integer, and sometimes less.)

**One option:**

Numeric constants are high-precision values. An untyped constant takes the type needed by its context. To show this, we use the shift operator to generate numbers that require `float`s. You can learn more about these [operators here](https://golang.org/ref/spec#Operators).

Try printing needInt(Big) too.

(An int can store at maximum a 64-bit integer, and sometimes less.)

**Longer option** - append a quote from https://golang.org/ref/spec#Operators:     
The shift operators shift the left operand by the shift count specified by the right operand. They implement arithmetic shifts if the left operand is a signed integer and logical shifts if it is an unsigned integer. There is no upper limit on the shift count. Shifts behave as if the left operand is shifted n times by 1 for a shift count of n. As a result, x << 1 is the same as x*2 and x >> 1 is the same as x/2 but truncated towards negative infinity.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
Agree that it's cryptic. We'll make it more straightforward.

**Comment by mjbrender** [comment]
Thanks @adg - I'm glad to have an effect on this awesome introduction.

**Comment by kytrinyx** [comment]
Since the slide is about constants rather than about the shift operators specifically, how about adding a small comment to show what the result would be equivalent to?

```
const (
	Big   = 1 << 100  // == 2**100
	Small = Big >> 99 // == 2**1
)
``

**Comment by adg** [comment]
@kytrinyx the `**` notation is arguably just as cryptic (esp since `**` isn't an operator in go).

Maybe show the actual value?

```
const (
    Big   = 1 << 100  // == 1267650600228229401496703205376
    Small = Big >> 99 // == 2
)
```

**Comment by kytrinyx** [comment]
Yeah, that would work for me. I'll give it a shot.
