### ISSUE TITLE
tour: better introduction to type declaration than it "does what you'd expect."

### ISSUE THREAD

**Issue by mjbrender** [golang/go#14152]
Context: https://tour.golang.org/moretypes/2

This was good for a while, but we can do better. We could borrow from the types definition for knowledge drop: https://golang.org/ref/spec#Types

Example:   
A type determines the set of values and operations specific to values of that type. Each type has an underlying type that goes back to the [basic types discussed earlier](https://tour.golang.org/basics/11). 

Let's define a type that is also a struct, which is made up of multiple fields.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
Agree.

**Comment by kytrinyx** [comment]
This was also discussed in #13530

**Comment by adg** [comment]
Closing in favor of the earlier issue.
