### ISSUE TITLE
test failed when go bootstrap inside Linux Container

### ISSUE THREAD

**Issue by wheelcomplex** [golang/go#14157]
The Linux Container running Ubuntu 14.04.3 LTS created by Proxmox_VE_4.1.

VE information:
<pre>
$ uname -a
Linux pve-40-11 4.2.2-1-pve #1 SMP Mon Oct 5 18:23:31 CEST 2015 x86_64 GNU/Linux

$ pveversion -v
proxmox-ve: 4.0-16 (running kernel: 4.2.2-1-pve)
pve-manager: 4.1-2 (running version: 4.1-2/78c5f4a2)
pve-kernel-4.2.2-1-pve: 4.2.2-16
lvm2: 2.02.116-pve2
corosync-pve: 2.3.5-2
libqb0: 0.17.2-1
pve-cluster: 4.0-29
qemu-server: 4.0-42
pve-firmware: 1.1-7
libpve-common-perl: 4.0-42
libpve-access-control: 4.0-10
libpve-storage-perl: 4.0-38
pve-libspice-server1: 0.12.5-2
vncterm: 1.2-1
pve-qemu-kvm: 2.4-18
pve-container: 1.0-35
pve-firewall: 2.0-14
pve-ha-manager: 1.0-16
ksm-control-daemon: 1.2-1
glusterfs-client: 3.5.2-2+deb8u1
lxc-pve: 1.1.5-5
lxcfs: 0.13-pve2
cgmanager: 0.39-pve1
criu: 1.6.0-1
zfsutils: 0.6.5.2-2
</pre>

Container information:
<pre>
$ uname -a
Linux test-machine-001 4.2.2-1-pve #1 SMP Mon Oct 5 18:23:31 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux

$ go version
go version devel +af15bee Fri Jan 29 18:29:10 2016 +0000 linux/amd64

$ go env
GOARCH="amd64"
GOBIN="/home/stdgo/sandspace/go/bin.linux-amd64"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/stdgo/sandspace/go/external/:/home/stdgo/sandspace/golibs/"
GORACE=""
GOROOT="/home/stdgo/sandspace/go"
GOTOOLDIR="/home/stdgo/sandspace/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

</pre>

all.bash
<pre>
--- FAIL: TestMathBigDivide (6.31s)
	pprof_test.go:212: total 3 CPU profile samples collected
	pprof_test.go:224: too few samples; got 3, want at least 5, ideally 20
	pprof_test.go:169: retrying with 400ms duration
	pprof_test.go:212: total 5 CPU profile samples collected
	pprof_test.go:224: too few samples; got 5, want at least 10, ideally 40
	pprof_test.go:169: retrying with 800ms duration
	pprof_test.go:212: total 7 CPU profile samples collected
	pprof_test.go:224: too few samples; got 7, want at least 20, ideally 80
	pprof_test.go:169: retrying with 1.6s duration
	pprof_test.go:212: total 27 CPU profile samples collected
	pprof_test.go:224: too few samples; got 27, want at least 40, ideally 160
	pprof_test.go:169: retrying with 3.2s duration
	pprof_test.go:212: total 46 CPU profile samples collected
	pprof_test.go:224: too few samples; got 46, want at least 80, ideally 320
--- FAIL: TestStackBarrierProfiling (6.59s)
	pprof_test.go:393: subprocess failed with exit status 1:
		--- FAIL: TestStackBarrierProfiling (6.38s)
			pprof_test.go:212: total 0 CPU profile samples collected
			pprof_test.go:224: too few samples; got 0, want at least 5, ideally 20
			pprof_test.go:169: retrying with 400ms duration
			pprof_test.go:212: total 1 CPU profile samples collected
			pprof_test.go:224: too few samples; got 1, want at least 10, ideally 40
			pprof_test.go:169: retrying with 800ms duration
			pprof_test.go:212: total 9 CPU profile samples collected
			pprof_test.go:224: too few samples; got 9, want at least 20, ideally 80
			pprof_test.go:169: retrying with 1.6s duration
			pprof_test.go:212: total 24 CPU profile samples collected
			pprof_test.go:224: too few samples; got 24, want at least 40, ideally 160
			pprof_test.go:169: retrying with 3.2s duration
			pprof_test.go:212: total 65 CPU profile samples collected
			pprof_test.go:224: too few samples; got 65, want at least 80, ideally 320
		FAIL
FAIL
FAIL	runtime/pprof	16.987s
</pre>

It is repeatable.

reference:
<pre>
http://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_4.1

https://linuxcontainers.org/lxc/introduction/
</pre>

**Comment by davecheney** [comment]
This failure indicates your container provider is limiting the amount of
CPU time the container is being allocated. Can you increase the allocation ?

**Comment by wheelcomplex** [comment]
After 10x CPU power allocated to this container, all test pass.
Thanks you very much.
