### ISSUE TITLE
tour: not implemented error on Windows 10

### ISSUE THREAD

**Issue by josephbudd** [golang/go#14172]
Context: http://127.0.0.1:3999/welcome/1
This began happening after the windows 10 upgrade from windows 7.

2016/01/31 21:32:23 Serving content from C:\Users\user1\My Projects\go\src\golang.org\x\tour
2016/01/31 21:32:23 A browser window should open. If not, please visit http://127.0.0.1:3999
2016/01/31 21:32:24 accepting connection from: 127.0.0.1:49694
2016/01/31 21:32:54 not implemented

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
What version of Go and the tour are you running?

**Comment by josephbudd** [comment]
go version go1.6rc1 windows/amd64

application: go-tour
version: 1
runtime: go
api_version: go1

**Comment by adg** [comment]
Are you running `go tool tour` to run the tour? Or `gotour`? If the latter, did you run `go get` to install `gotour`?

**Comment by josephbudd** [comment]
go get golang.org/x/tour/gotour

i just did that again a few days ago.

**Comment by adg** [comment]
What do you do that triggers the `not implemented` log message? It seems to happen 30 seconds after the process starts, so I am assuming the message is triggered by some user action.

Do you have any problems with the user interface (in your browser) at the time the message is produced?

Can you provide a series of steps to reproduce the issue?

**Comment by josephbudd** [comment]
In the case of the this thread i simply opened the windows command
prompt and cd'd to the go bin folder. then i just typed "gotour.exe".
And it errored out almost right away. Sometimes i can acually run
something once.

Right now it opens edge which  gets a little goofed up sometimes in
the edit area with the cursor moving to the wrong place and text being
typed in the wrong place.

Steps: ( note cdgobin.bat just cd's to the gitgo bin folder and dumps the dir. )


C:\Users\user1>cdgobin
 Volume in drive C is TI106045W0C
 Volume Serial Number is 5DBE-8130

 Directory of C:\Users\user1\My Projects\go\bin

02/01/2016  04:34 PM    <DIR>          .
02/01/2016  04:34 PM    <DIR>          ..
05/27/2015  07:29 PM            37,472 1899922_10151980483252695_1220327366_n.jp
g
05/01/2015  08:51 AM         3,197,440 bolt.exe
08/26/2015  02:52 PM        12,648,986 file_dlg.exe
08/26/2015  02:52 PM        12,577,941 fullscreen.exe
10/15/2015  07:22 PM         7,906,304 golang-html5-sse-example.exe
08/26/2015  03:03 PM        13,219,328 gomobile.exe
02/01/2016  04:34 PM        12,262,912 gotour.exe
01/18/2016  10:34 AM        11,098,624 gotour.exe~
08/26/2015  02:52 PM        12,579,256 hello_world.exe
08/26/2015  02:52 PM        12,705,299 image_viewer.exe
08/26/2015  02:52 PM        12,591,153 linear_layout.exe
08/26/2015  02:52 PM        12,601,147 lists.exe
08/26/2015  02:52 PM        12,578,887 panels.exe
08/26/2015  02:52 PM        12,578,625 polygon.exe
08/26/2015  02:52 PM        12,584,480 progress_bar.exe
11/17/2014  08:39 AM         4,460,544 server.exe
08/26/2015  02:52 PM        12,604,031 tree.exe
              17 File(s)    178,232,429 bytes
               2 Dir(s)  169,792,831,488 bytes free

C:\Users\user1\My Projects\go\bin>gotour.exe
2016/02/04 21:53:57 Serving content from C:\Users\user1\My Projects\go\src\golan
g.org\x\tour
2016/02/04 21:53:58 A browser window should open. If not, please visit http://12
7.0.0.1:3999
2016/02/04 21:53:59 accepting connection from: 127.0.0.1:57325
2016/02/04 21:54:29 not implemented

**Comment by adg** [comment]
Thanks for the information. I have an idea what the issue might be.

Can you please try running this command from a command prompt?

```
cmd /c start https://google.com/
```

Thanks for bearing with me.

**Comment by adg** [comment]
Actually, never mind the above. I think I the issue is related to Microsoft's Edge browser's implementation of the websocket protocol, and a possibly outdated version of the websocket package in your version of the tour.

Can you please run
```
go get -u golang.org/x/tour/gotour
```
The `-u` flag is most important; it will make sure all the packages are updated to their most recent versions.
