### ISSUE TITLE
when using docker + linking + golang it doesn't read /etc/hosts properly

### ISSUE THREAD

**Issue by blacktop** [golang/go#14170]
Please see:
 - https://github.com/docker/docker/issues/19866

**Comment by bradfitz** [comment]
Please file a complete bug report with a summary that stands alone. Nobody likes chasing down a dozen links to guess which part the bug report might be about.

And if this is about the DNS resolver, please search to see if an existing bug is a dup. I suspect it might be in this case. I've seen some others open mentioning similar things.

**Comment by wildattire** [comment]
Ran into this bug today. Why is the issue closed? This is definitely a showstopper for use of go apps in docker containers.

**Comment by mdempsky** [comment]
@bradfitz explained why it's closed:

> Please file a complete bug report with a summary that stands alone. Nobody likes chasing down a dozen links to guess which part the bug report might be about.

**Comment by minux** [comment]
The bug is closed due to lack of information.

If you have more information please file a new issue
Thanks.

**Comment by blacktop** [comment]
@wildattire  https://groups.google.com/forum/?fromgroups#!topic/golang-nuts/G-faJ0bthz0

The problem is with Alpine, specifically musl's DNS behavior, and not 
Go. See e.g. https://github.com/gliderlabs/docker-alpine/issues/8. I 
believe the issue will be fixed in Alpine in the near future. 

I can confirm that Alpine 3.4 fixes the issue.

**Comment by jolestar** [comment]
The problem seem still exist for golang with alpine after 3.4.

**Comment by mattn** [comment]
Please fill asnwers of questions in template at top of comment.

```
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?


### What operating system and processor architecture are you using (`go env`)?


### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.


### What did you expect to see?


### What did you see instead?

```

URL doesn't match with using keywords on [issue search](https://github.com/golang/go/issues).

**Comment by bradfitz** [comment]
Somebody, please file a real bug report. I'm freezing this noisy one.
