### ISSUE TITLE
website: Google Code Archive go default source 404

### ISSUE THREAD

**Issue by juicedatom** [golang/go#14175]
I'm not really sure if this goes here or in some Google Code | Archive reporter but when I click default source from google code archive I get a 404.  Click this [link](https://code.google.com/archive/p/go/source), then click default: source.  You should get a 404.  I'm guessing it's because you guys moved everything over to github and didn't clean this repo, but i'm just guessing.

update:  all the links 404 on the site

**Comment by chrsmith** [comment]
Hello, I work at Google on the Google Code Archive. I'll look into this. Most likely it appears our process for archiving source code somehow didn't get the go repo's source. The data is still available, so nothing was lost. I'll just need to look into what went wrong and make sure it gets corrected.

In the mean time if you were looking for something in particular please let me know and I can help you out.

**Comment by ianlancetaylor** [comment]
I'm not sure how useful it is to have this bug opened against the Go project.  Our sources no longer live on code.google.com (which is being shut down).  Is there a reason you at looking at code.google.com rather than github.com?

**Comment by broady** [comment]
Well, this just redirects to GitHub now, which I think is fine.
