### ISSUE TITLE
tour: cannot find package "golang.org/x/tour/reader" 

### ISSUE THREAD

**Issue by lernisto** [golang/go#14184]
Context: http://127.0.0.1:3999/methods/22

>  compile16.go:3:8: cannot find package "golang.org/x/tour/reader" in any of:
>	/usr/local/go/src/golang.org/x/tour/reader (from $GOROOT)
>	/usr/local/go/misc/tour/src/golang.org/x/tour/reader (from $GOPATH)

there is no reader directory

go version go1.5.3 linux/amd64

**Comment by broady** [comment]
@bradfitz is this documentation? I'm guessing this is only when running tour from a distribution.

**Comment by broady** [comment]
@lernisto can you confirm that you installed Go via a binary distribution?

**Comment by bradfitz** [comment]
@broady, it's either a bad link, so it's documentation or somebody is confused, so it's documentation. It's not a bug in the Go standard library or runtime, so I chose "Documentation". :-)

**Comment by lernisto** [comment]
yes.

> /usr/local/go $ find misc/tour/src -type d 
> misc/tour/src
> misc/tour/src/golang.org
> misc/tour/src/golang.org/x
> misc/tour/src/golang.org/x/tour
> misc/tour/src/golang.org/x/tour/wc
> misc/tour/src/golang.org/x/tour/pic
> misc/tour/src/golang.org/x/tour/tree
> /usr/local/go $ cd ~/Downloads
> ~/Downloads $ sha1sum go1.5.3.linux-amd64.tar.gz 
> c5377eca4837968d043b681f00a852a262f0f5f6  go1.5.3.linux-amd64.tar.gz

**Comment by lernisto** [comment]
It does work when I 

> $ go get golang.org/x/tour/gotour
> $ gotour

just not from the distribution.

**Comment by bradfitz** [comment]
@broady, the same files are in Go 1.6:

```
go/misc/tour/src/
go/misc/tour/src/golang.org/
go/misc/tour/src/golang.org/x/
go/misc/tour/src/golang.org/x/tour/
go/misc/tour/src/golang.org/x/tour/pic/
go/misc/tour/src/golang.org/x/tour/pic/pic.go
go/misc/tour/src/golang.org/x/tour/tree/
go/misc/tour/src/golang.org/x/tour/tree/tree.go
go/misc/tour/src/golang.org/x/tour/wc/
go/misc/tour/src/golang.org/x/tour/wc/wc.go
```

I forgot we shipped the tour in the releases. Is this a bug in cmd/release? Something to fix for Go1.6rc2? (i.e. fix immediately this morning?).
