### ISSUE TITLE
tour: Rename Abs() to Sqrt()

### ISSUE THREAD

**Issue by RezaSR** [golang/go#14181]
Context: https://tour.golang.org/methods/1

It seems that the Abs() function should be renamed to Sqrt()

**Comment by bradfitz** [comment]
That looks intentional. In the next few pages Abs is defined on different values. It returns an absolute value. For a vector it uses Sqrt to implement Abs.

**Comment by mdempsky** [comment]
https://en.wikipedia.org/wiki/Absolute_value#Vector_spaces
