### ISSUE TITLE
runtime or net/http: possible hang

### ISSUE THREAD

**Issue by rsc** [golang/go#14195]
Buildbot hang testing CL 19151:
https://storage.googleapis.com/go-build-log/9875de36/darwin-amd64-10_10_15e7a318.log

The hang is in the net/http tests. It could be another runtime hang (but that CL does sit on top of the most recent fix), or it could be a net/http hang. Someone should diagnose.

/cc @aclements @bradfitz

**Comment by aclements** [comment]
Looks like we're stuck in the select at net/http/transport.go:691 in TestTLSServerClosesConnection.

**Comment by bradfitz** [comment]
I'm going to mark this test as flaky (it was already flaky on Windows and has a comment that it was only an attempt to reproduce a problem), and dup this into #7634 for the long-term.
