### ISSUE TITLE
`log.Logger` should be a interface instead of a struct

### ISSUE THREAD

**Issue by jingweno** [golang/go#14205]
**What version of Go are you using (go version)?**

1.5.3.

**What operating system and processor architecture are you using?**

Linux. AMD 64.

**What did you do?**

We've been using [logrus](https://github.com/Sirupsen/logrus) for structural logging which is good for querying and stuff. And we would like [`httputil.ReverseProxy.ErrorLog`](https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L48) to log in the same format as logrus which is used in the application code. Since `log.Logger` is struct instead of a interface, there's no way to adapt logrus to `log.Logger`.

**What did you expect to see?**

I would expect `log.Logger` to be a interface which defines a bunch of interfaces, e,g. `Fatal(v ...interface{})` and allow different implementations. This way, even the Go standard library can log in same way as application code.

**What did you see instead?**

Well, `log.Logger` is a struct and the log format is different from our application code. We need to have other ways to query the log for stdlib.

**Comment by bradfitz** [comment]
Sorry, https://golang.org/doc/go1compat precludes any changes, regardless of anybody's opinion on the API design.

**Comment by jingweno** [comment]
Alright...Go 2 please come...

**Comment by dpiddy** [comment]
Can or should this be left open with a Go2 label, similar to https://github.com/golang/go/issues/14106 and others?

**Comment by bradfitz** [comment]
Sure. I'm going to leave it closed, though. If Go2 ever actually happens, we know how to find this back.
