### ISSUE TITLE
go install with cross-compile fails with a permissions error

### ISSUE THREAD

**Issue by devoid** [golang/go#14213]
When filing an issue, make sure to answer these five questions:

**What version of Go are you using (go version)?**
```
$ go version
go version go1.5.3 darwin/amd64
```

**What operating system and processor architecture are you using?**
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/devoid/code/github.com/devoid/xcompile"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**What did you do?**
Attempted to `go install` while cross-compiling to `GOOS=linux`. This is on a simple hello-world program:
```go
package main

import "fmt"

func main() {
        fmt.Println("hello world")
}
```

**What did you expect to see?**

That `go install $name` with the appropriate flags installs to `bin/${GOOS}_{GOARCH}/$name` or if this is not sensible, e.g. _"Why would you install a binary for a different architecture?"_, report an error indicating this.

**What did you see instead?**

```
$ GOOS=linux go install github.com/devoid/xcompile
go install runtime: mkdir /usr/local/go/pkg/linux_amd64/: permission denied
$ ls -l /usr/local/go/pkg/
total 0
drwxr-xr-x  58 root  wheel  1972 Jan 13 14:56 darwin_amd64
drwxr-xr-x  57 root  wheel  1938 Jan 13 14:56 darwin_amd64_race
drwxr-xr-x   4 root  wheel   136 Jan 13 14:56 include
drwxr-xr-x   3 root  wheel   102 Jan 13 14:56 obj
drwxr-xr-x   3 root  wheel   102 Jan 13 14:56 tool
```

**Comment by davecheney** [comment]
The permission error is coming from installing the runtime dependencies of your package (you can use -v or -x to check this). 

The solution is to use `go build`, not `go install`.

**Comment by bradfitz** [comment]
Please try with Go 1.6 instead of Go 1.5. Go 1.5 development and bug fixing is over.

**Comment by jzila** [comment]
FYI this problem can be solved by setting the permissions on your `GOROOT` package directory.
`ls $(go env GOROOT)/pkg && sudo chown -R $USER $(go env GOROOT)/pkg`

**Comment by davecheney** [comment]
Please don't do that, use go build when cross compiling instead.

**Comment by jzila** [comment]
`go build` doesn't cache dependencies, so compilation becomes incredibly slow every time. From my research, you can set the target installation directory, but you can't set the target package directory, so the only way to get caching for packages is to become more permissive. Or run from a `$GOROOT` where you have control.

**Comment by mwhudson** [comment]
Or -pkgdir

**Comment by davecheney** [comment]
Or use gb

**Comment by devoid** [comment]
@mwhudson Thanks for the pointer to `-pkgdir <target>`. I did have one, slightly obvious, pitfall trying to use that flag: _don't set the target directory to anything under your GOPATH._ This will drive the toolchain insane. :-)

This works perfectly---after the first cross-compile only changes are rebuilt!

**Comment by gszecsenyi** [comment]
I also have this issue. On OSX, go1.8.3 darwin/amd64. If I set GOOS=linux, then it fails, because it want to create the pkg directory on GOROOT and not on GOPATH.

**Comment by davecheney** [comment]
@gszecsenyi this issue is closed, please open a new issue following the issue template.  Thank you.

**Comment by gszecsenyi** [comment]
Done, thank you.

[https://github.com/golang/go/issues/20571](https://github.com/golang/go/issues/20571)
