### ISSUE TITLE
net: LookupHost sometimes returns slice which when modified ruins cache state.

### ISSUE THREAD

**Issue by suharshs** [golang/go#14212]
To reproduce: 
Machine must have localhost specified in the /etc/hosts file.
Machine must NOT have localhost entry in its DNS Server.

Running this code:

    package main

    import (
        "fmt"
        "net"
    )

    func main() {
        runClient()
        modifyAddrs("localhost")
        runClient()
    }

    func modifyAddrs(host string) []string {
        addrs, err := net.LookupHost(host)
        if err != nil {
                panic(err)
        }
        for i := range addrs {
                addrs[i] += "junk"
        }
        return addrs
    }

    func runClient() {
        _, err := net.Dial("tcp", "localhost:23000")
        fmt.Printf("err = %v\n", err)
    }

Will output:

    err = dial tcp 127.0.0.1:23000: getsockopt: connection refused
    err = dial tcp: lookup localhost on 169.254.169.254:53: no such host

The first error message is able to resolve localhost but after modifying the returned addr slice, it no longer can.
I traced it down to the localStaticHost function returns a slice directly from the cache, rather than returning a copy of it.

I have a fix here: https://go-review.googlesource.com/#/c/19201/

**Comment by bradfitz** [comment]
Is this a regression from Go 1.5?

**Comment by suharshs** [comment]
I observed it in Go 1.5.3 and it also exists at HEAD.

**Comment by bradfitz** [comment]
In that case (since it's not a regression and lived with it in Go 1.5) we can fix it when the Go 1.7 dev tree opens up.

/cc @mikioh

**Comment by mikioh** [comment]
Looks like this is one of long standing issues, actually since r56?

https://github.com/golang/go/commit/d6054fcd88e04e0c7bd0bae92f51883d4f5e3e08
https://github.com/golang/go/commit/a4f6ed3574c7c6edc673346c0629d866108ace7e

PS: Please change the test function names from "runTestSubject" to "testSubject" once the tree opens.
