### ISSUE TITLE
x/sys/unix: add Fstatat on Linux on more than just GOARCH=arm64

### ISSUE THREAD

**Issue by dturner-tw** [golang/go#14216]
x/sys/unix doesn't have the following posix functions:

fstatat()
linkat()
mkfifoat()
readlinkat()
symlinkat()
utimensat()

I propose to add exactly fstat, symlinkat, and linkat because I think those are the only ones I am likely to use.

**Comment by ianlancetaylor** [comment]
Go for it.

**Comment by dturner-tw** [comment]
Actually, looks like I'm not going to end up getting to this (at least not soon) -- I've been pulled away onto another project.  So I'm going to leave this note here and if someone else gets to it before I come back, that's OK with me.

P.S. fdopendir is the *at family version of opendir, but since it's not a syscall, I'm not sure where it should live.

**Comment by perillo** [comment]
I need the fstatat syscall for a project, at least on Linux. In future I would like to add support for other systems like FreeBSD and Darwin.

**Comment by dturner-tw** [comment]
[fstatat-3.zip](https://github.com/golang/go/files/208976/fstatat-3.zip)

Before I got pulled back to my main job hacking on Git, I had written the attached patch.  At the time, I didn't have permission from Twitter legal to post it, but they have since given me permission.  I don't recall what state this was in -- that is, what parts of it worked, what testing was done, etc.  Sorry for the poor record-keeping here.

Anyway, it's a starting point.  If you need any assignments or signatures in order to use this, I am happy to execute them.

**Comment by perillo** [comment]
@dturner-tw thanks for the patch.

However I already patched my local clone of x/sys in order to add support for fstatat for linux amd64.  This will allow me to test my project and waiting for official support before releasing it.

Just some little differences from your code.

Instead of generating the `newfstatat` syscall, with the required wrapper function, I declared the syscall as
```go
//sys	Fstatat(fd int, path string, stat *Stat_t, flags int) (err error) = SYS_NEWFSTATAT
```

Another difference is that I declared Fstatat in syscall_linux_amd64.go, instead of syscall_linux.go, but this a topic that I'm not sure to understand well.

**Comment by tklauser** [comment]
Support for linkat, readlinkat and symlinkat was added in golang/sys@9bb9f0998d48b31547d975974935ae9b48c7a03c (#14459)

**Comment by bradfitz** [comment]
Let's make this bug only about fstatat.

Here's the current status as of 50298aa7a:

```
unix/syscall_linux_arm64.go://sys       Fstatat(fd int, path string, stat *Stat_t, flags int) (err error)
unix/syscall_linux_arm64.go:    return Fstatat(AT_FDCWD, path, stat, 0)
unix/syscall_linux_arm64.go:    return Fstatat(AT_FDCWD, path, stat, AT_SYMLINK_NOFOLLOW)
unix/zsyscall_linux_arm64.go:func Fstatat(fd int, path string, stat *Stat_t, flags int) (err error) {
unix/zsyscall_linux_arm64.go:   _, _, e1 := Syscall6(SYS_FSTATAT, uintptr(fd), uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)), uintptr(flags), 0, 0)
unix/zsysnum_linux_386.go:      SYS_FSTATAT64              = 300
unix/zsysnum_linux_amd64.go:    SYS_NEWFSTATAT             = 262
unix/zsysnum_linux_arm.go:      SYS_FSTATAT64              = 327
unix/zsysnum_linux_arm64.go:    SYS_FSTATAT                = 79
unix/zsysnum_linux_mips.go:     SYS_FSTATAT64              = 4293
unix/zsysnum_linux_mips64.go:   SYS_NEWFSTATAT             = 5252
unix/zsysnum_linux_mips64le.go: SYS_NEWFSTATAT             = 5252
unix/zsysnum_linux_mipsle.go:   SYS_FSTATAT64              = 4293
unix/zsysnum_linux_ppc64.go:    SYS_NEWFSTATAT             = 291
unix/zsysnum_linux_ppc64le.go:  SYS_NEWFSTATAT             = 291
unix/zsysnum_linux_s390x.go:    SYS_NEWFSTATAT             = 293
unix/zsysnum_linux_sparc64.go:  SYS_FSTATAT64              = 289
```

It exists for arm64, but not the rest. Looks like the syscall has evolved a bit over the years, so this might require manually written wrappers to make the API feel the same everywhere (matching linux/arm64)
