### ISSUE TITLE
cmd/link: illegal text-relocation for c-archive darwin/amd64

### ISSUE THREAD

**Issue by azinman** [golang/go#14217]
When compiling using buildmode c-archive on darwin/amd64 (targeting the iOS simulator), I run into this error when trying to link the resulting archive to my Swift code:

ld: illegal text-relocation to 'type..eq.[0]encoding/xml.Attr' in .../lib.a(go.o) from 'runtime.rodata' in .../lib.a(go.o) for architecture x86_64

Looking at the cmd/link/internal/ld/macho.go, it seems that it currently is only checking for shared archives on amd64 when it chooses to use the DATA segment over TEXT.

**Comment by azinman** [comment]
Proposed CL is here: https://go-review.googlesource.com/#/c/19206

**Comment by dcu** [comment]
would it be possible to include this for go 1.6.1? It's kind of blocking my team

**Comment by minux** [comment]
I doubt this meets the bar for point releases, but the CL in question is
pretty small, so you can just apply it to your tree locally without waiting
for a release
