### ISSUE TITLE
cmd/go: better error for test functions with wrong signature

### ISSUE THREAD

**Issue by dominikh** [golang/go#14226]
Running `go test` against test code that declares a `Test*` function with a wrong signature results in a somewhat unpleasant compile error:

```
dominikh-pc /tmp $ cat foo_test.go
package foo

func TestBroken(wrong, signature int) {}
dominikh-pc /tmp $ go test
# testmain
go-build299431253/_/tmp/_test/_testmain.go:22: cannot use foo.TestBroken (type func(int, int)) as type func(*testing.T) in field value
FAIL	_/tmp [build failed]
dominikh-pc 2? /tmp $ 
```

It might be nice to check for the signature before compiling the test binary, to print a customized error.

**Comment by dominikh** [comment]
The same applies to benchmarks.

**Comment by bradfitz** [comment]
I hit this the other day too.

**Comment by cmarcelo** [comment]
@bradfitz or @dominikh could one of you take a look at the CL above?
