### ISSUE TITLE
doc: Contribution Guidelines don't explain R=go1.7

### ISSUE THREAD

**Issue by RalphCorderoy** [golang/go#14225]
https://golang.org/doc/contribute.html needs to have the "R=go1.7" convention described, including that no further review or uploads take place due to the noise created.

https://go-review.googlesource.com/#/c/19178/ had a R=go1.7 added.  I thought that meant it didn't stand a chance of being approved until 1.7 was open for business.  I reviewed it.  The author uploaded a new patchset.  Then @bradfitz repeated the R=go1.7 with "Please hold on updates or reviews until Go 1.6 is out".  Several times.  :-)

I didn't realise any action on a R=go1.7 changeset was unwelcome;  presumably it's generating noise for 1.6's work.  Neither did the changeset's author by the looks of it.  I've re-read https://golang.org/doc/contribute.html and it doesn't mention the "no talking" convention when a future-release marker is added.  Nor does https://github.com/golang/go/wiki/Go-Release-Cycle that it links to AFAICS.  Nor https://github.com/golang/go/wiki/CodeReview, though I don't think that's the right place.

**Comment by bradfitz** [comment]
I think we've been hoping this hack is temporary. We're waiting on a Gerrit feature to be live on go.googlesource.com that would let us have labels on CLs, so we can have an official way to designate which release certain CLs are for.

/cc @rsc @adg @spearce

**Comment by adg** [comment]
I'm not actually sure how the R=go1.7 thing works. If the dashboard sees a commit with that string as its last message, it removes those pending CLs from the current release dashboard? Is there something more to it?

If my understanding is correct, the suggestion should be to not do any further work on the change until after the current release cycle is concluded. Right?

**Comment by bradfitz** [comment]
It's a magic comment respect by @rsc's script which update https://swtch.com/godash/release

The code for that script isn't in our source tree anywhere either, but we want to make it more official and move its code and run it on GCE and probably on a golang domain.

**Comment by rsc** [comment]
Hey look! Documentation: https://swtch.com/godash/.

Russ

**Comment by RalphCorderoy** [comment]
Does that describe R=go1.7?  I don't see it in the R=<whom> section.
It doesn't describe the behavioural conventions around it.  I get the impression that any activity is disliked, e.g. reviewing ready for when 1.7 is open, presumably because it causes noise as there's no gerrit method of filtering it out?

**Comment by RalphCorderoy** [comment]
Does that describe R=go1.7?  I don't see it in the R=whom section.
And after the mechanics of how it works, there's the conventions on behaviour given gerrit's shortfalls.  That bit's still unclear.

**Comment by adg** [comment]
I don't see it either.

@rsc is the `R=go1.7` feature documented somewhere?

**Comment by adg** [comment]
I just added mention of the `R=` convention to the [code review wiki page](https://github.com/golang/go/wiki/CodeReview), which is linked from the contributor guidelines. Once Russ has documented the `R=go1.7` feature, I believe this issue can be closed.

**Comment by RalphCorderoy** [comment]
The feature, including the behaviour expected of people;  this issue's title originally had "Gag" at the end.  :-)

**Comment by bradfitz** [comment]
Oh, now that I know what you meant by "gag". In any case, @rsc says he fixed that part. It doesn't need to be the last comment anymore.

**Comment by rsc** [comment]
I guess R=go1.7 is not documented where I thought it was. In any event, I'll get this cleaned up later. The dashboard is run mainly by golang.org/x/build/cmd/cl although I have local changes that haven't been reviewed.

**Comment by RalphCorderoy** [comment]
OK, so if R=go1.7 doesn't need to be the last comment then I'm going to assume it's OK to post on changes so tagged without causing Brad more "I must have the last word" work.

**Comment by rsc** [comment]
Yes, one R=go1.7 is enough now. And posting comments has always been fine,
it's uploading new patch sets that used to reset the R=.

Russ

**Comment by rasky** [comment]
I'm working on a CL for a rewritten contribute guide that includes R= lines:
https://go-review.googlesource.com/c/go/+/93495

**Comment by rasky** [comment]
CL has been submitted.
