### ISSUE TITLE
x/exp/shiny/example/basic: alpha channel is ignored on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#14220]
The x/exp/shiny/example/basic looks like
![is](https://cloud.githubusercontent.com/assets/9796621/12806973/1fae9440-cb5f-11e5-8744-81f72a4eb8bb.jpg)
but should look like
![expected](https://cloud.githubusercontent.com/assets/9796621/12806987/430f5c44-cb5f-11e5-9df7-db92f4a01750.jpg)

Alex

**Comment by nigeltao** [comment]
The Upload method shouldn't blend. Only those methods which take a draw.Op arg (Fill, Draw, Copy Scale) should blend. (Upload could possibly also take a draw.Op arg, and then blend, but I think that that is a separate issue).

I think the top image is actually working as intended, although IIRC the windriver doesn't do textures yet. In particular, the top image matches what I see on x11driver and gldriver/linux.

**Comment by nigeltao** [comment]
https://go.googlesource.com/exp/+/master/shiny/screen/screen.go#202 says that "The destination's contents are overwritten; the draw operator is implicitly draw.Src."

**Comment by alexbrainman** [comment]
> what I see on x11driver and gldriver/linux

Please post picture of your x/exp/shiny/example/basic window on linux, so I can see what else needs to be done for windows. Thank you.

Alex

**Comment by nigeltao** [comment]
Screenshot of the top-left corner of my window:
![shiny-basic](https://cloud.githubusercontent.com/assets/8565232/12839800/ebbc3174-cc30-11e5-84ce-b85b9b30be43.png)
