### ISSUE TITLE
x/net/http2: should interpret Connection: close request header as Request.Close = true

### ISSUE THREAD

**Issue by adamtanner** [golang/go#14227]
Related to #14214, it doesn't seem possible to explicitly set a protocol version when sending via an http.Transport and this breaks when sending requests with certain headers to servers supporting HTTP2. As an example, the following encounters the same 400 error from the GFE as we were previously seeing with the Proxy-Connection header:

```go
package main

import (
	"net/http"
	"net/url"
	"os"
)

func main() {
	req := &http.Request{
		Method: "GET",
		URL: &url.URL{
			Scheme: "https",
			Host:   "www.google.co.uk",
			Path:   "/",
		},
		ProtoMajor: 1,
		ProtoMinor: 1,
		Proto:      "HTTP/1.1",
		Host:       "www.google.co.uk",
		Header: http.Header{
			"Connection": []string{"close"},
		},
	}
	req.Write(os.Stdout)

	// Uncomment to Nerf HTTP2 support and the request succeeds.
	// http.DefaultTransport.(*http.Transport).TLSNextProto = make(map[string]func(string, *tls.Conn) http.RoundTripper)

	res, err := http.DefaultTransport.RoundTrip(req)
	if err != nil {
		panic(err)
	}
	res.Write(os.Stdout)
}

// Example:
// GET / HTTP/1.1
// Host: www.google.co.uk
// User-Agent: Go-http-client/1.1
// Connection: close
//
// HTTP/2.0 400 Bad Request
// Content-Length: 54
// Content-Type: text/html; charset=UTF-8
// Date: Thu, 04 Feb 2016 14:37:38 GMT
// Server: GFE/2.0
//
// <html><title>Error 400 (Bad Request)!!1</title></html>
```

For non-HTTP2 requests the Connection header is perfectly valid, but when upgraded by http.Transport to HTTP2 they become invalid and break.

**Comment by bradfitz** [comment]
You're not allowed to set the protocol version for outgoing requests. The docs say:

https://tip.golang.org/pkg/net/http/#Request

```go
    // The protocol version for incoming server requests.
    //
    // For client requests these fields are ignored. The HTTP
    // client code always uses either HTTP/1.1 or HTTP/2.
    // See the docs on Transport for details.
    Proto      string // "HTTP/1.0"
    ProtoMajor int    // 1
    ProtoMinor int    // 0
```

As for your,

```go
        Header: http.Header{
            "Connection": []string{"close"},
        },
```

That's not really a header that Go code is supposed to set manually. That's one of the ones managed for you. Note the `Request.Close` boolean, which is how you're supposed to control that.

Did this break real code or was this hypothetical, an experiment after seeing the previous commits and bugs about similar things?

We can update docs, but unless this broke real code, we'd rather not change any code behavior after we did the rc2 release.

**Comment by bradfitz** [comment]
To be clear, there's stuff to change at some point. I'm just trying to determine when.

For example, the Transport code should remove that Connection: "close" header (so it's not sent) and treat it as if you set Request.Close.

**Comment by bradfitz** [comment]
Per offline discussion, I've retitled this bug.
