### ISSUE TITLE
net/http/httputil: the reverse proxy is bypassed when the proxied site redirects to itself using an absolute URL

### ISSUE THREAD

**Issue by opennota** [golang/go#14237]
ReverseProxy doesn't follow redirects by itself, so if the proxied site redirects to itself using an absolute URL in the `Location` header (e.g. `Location: http://servername/path`), the following requests bypass the proxy.

http://play.golang.org/p/DHoUpoPGnf

It would be useful if ReverseProxy had a callback field that allowed modifying the response (at least the headers).

Another use case is when you want to proxy a site that requires registration and do not want any cookies to leak from the proxied server to the client.

**Comment by rsc** [comment]
@bradfitz, what do we want to do here?

**Comment by bradfitz** [comment]
I'd be fine with a new optional func on `httputil.ReverseProxy` like:

```go
      // ModifyResponse is an optional function that modifies the Response from the backend.
      // If it returns an error, the proxy returns with StatusBadGateway.
      ModifyResponse func(*http.Response) error
```

/cc @odeke-em (if you're interested)

**Comment by odeke-em** [comment]
Sorry for the late reply, I hadn't seen this till now. Sounds like a plan, thanks for the ping @bradfitz!
