### ISSUE TITLE
Broken Plan 9 link at https://golang.org/doc/asm

### ISSUE THREAD

**Issue by MrMormon** [golang/go#14233]
I haven't been able to find a replacement for

http://plan9.bell-labs.com/sys/doc/asm.html

"If you plan to write assembly language, you should read that document although much of it is Plan 9-specific. The current document provides a summary of the syntax and the differences with what is explained in that document, and describes the peculiarities that apply when writing assembly code to interact with Go. "

So until someone suggests a replacement (and a better way to contribute to the website) this part of Go's implementation is now missing documentation.

**Comment by adg** [comment]
@robpike @rsc do we know anyone at bell who can resurrect the page?

It's still in the archive.org cache https://web.archive.org/web/20150325175010/http://plan9.bell-labs.com/sys/doc/asm.html

**Comment by mdempsky** [comment]
They're also mirrored at http://doc.cat-v.org/plan_9/4th_edition/papers/.  E.g., http://doc.cat-v.org/plan_9/4th_edition/papers/asm

**Comment by bradfitz** [comment]
Maybe we mirror it at e.g. https://mirror.golang.org/plan9.bell-labs.com/sys/doc/asm.html

**Comment by adg** [comment]
It would be nice if we controlled the hosting of all critical documentation.

**Comment by 0intro** [comment]
I've set up a full mirror of http://plan9.bell-labs.com on https://9p.io a year ago.
It serves HTTP, FTP, 9P and Wikifs.

So you can access URLs like https://9p.io/sys/doc/asm.html.

**Comment by adg** [comment]
Great! That's good enough for now. I'll send a CL.

**Comment by MrMormon** [comment]
Way to get on it, everyone! I missed it in the papers section. Btw OCaml has a similar problem where http://caml.inria.fr/ is deprecated but there's too much in http://caml.inria.fr/pub/ to mirror.
