### ISSUE TITLE
syscall.Select prototype differs on OSX

### ISSUE THREAD

**Issue by Saurbaum** [golang/go#14230]
this

n, err := syscall.Select(socket+1, nil, wfdset, nil, &timeval)

works on linux but on OSX it only returns err

**Comment by bradfitz** [comment]
You didn't say what type of error. Runtime error, compiler error?

There's not enough info here to help.

But in general, we make no promises about the syscall package. It's not portable. It contains sharp edges and you're on your own when you're in there.

**Comment by Saurbaum** [comment]
Ok to clarify it doesn't compile because it is only returning a single error parameter.

I would have expected it to at least match the prototype and also return an int.

**Comment by bradfitz** [comment]
Oh well. Can't change it now.
