### ISSUE TITLE
context: DeadlineExceeded doesn't implement net.Error interface

### ISSUE THREAD

**Issue by abursavich** [golang/go#14238]
It's a common pattern to test for timeout errors by asserting (a subset of) the net.Error interface and calling the Timeout method.

```go
func isTimeout(err error) bool {
	te, ok := err.(interface{ Timeout() bool })
	return ok && te.Timeout()
}
```

DeadlineExceeded timeouts should not require a special case.

**Comment by bradfitz** [comment]
@Sajmani, has this ever been discussed?

**Comment by davecheney** [comment]
This seems like a reasonable request.

**Comment by rsc** [comment]
Seems like a good idea to me and worth doing for Go 1.7 since context is new there.
