### ISSUE TITLE
tour: Unhelpful content describing the structs example

### ISSUE THREAD

**Issue by mwhite05** [golang/go#14248]
Context: http://tour.golang.org/moretypes/2

For those with low exposure to languages like C and C++ (myself included) the comment

"A struct is a collection of fields.
(And a type declaration does what you'd expect.)"

seems a little too light on detail. My general experience with coding and some exposure to C and C++ means I got the gist well enough for now. However; for a tutorial that seems to make few assumptions of the user's knowledge of coding structures and syntax this page is definitely an outlier.

**Comment by kytrinyx** [comment]
Yeah, this has come up a couple of times. See #13530 for a discussion.
