### ISSUE TITLE
encoding/binary uses wrong size for struct while using Read

### ISSUE THREAD

**Issue by qeedquan** [golang/go#14249]
I have a struct layed out like this
`type exitStatus struct {
	Termination uint16
	Exit        uint16
}

type utmp struct {
	Type       uint16
	Pid        uint32
	Line       [UT_LINESIZE]uint8
	ID         [4]uint8
	User       [UT_NAMESIZE]uint8
	Host       [UT_HOSTSIZE]uint8
	ExitStatus exitStatus
	Session    uint32
	Sec        uint32
	Usec       uint32
	Addr6      [4]uint32
	_          [20]uint8
}`

I am trying to use encoding/binary Read to read data into the utmp struct, but for some reason it treats that struct as a size of 382 (dataSize() in encoding/binary.go:339 returns 382) for data size which leads the Read function to read it wrong.

reflect.TypeOf(utmp).Size() and unsafe.Sizeof() gives me size 384 though. 

I am using Go 1.6beta2 on Linux AMD64.

**Comment by minux** [comment]
There is a two byte padding between Type and Pid. The compiler (and unsafe)
enforces struct padding, but encoding/binary only consider real fields so
you must use _ field to fill the two padding bytes.

This is working as intended.

**Comment by davecheney** [comment]
Two bytes of padding exist between Type and Pid
