### ISSUE TITLE
tour: variable name of slice -- s instead of a?

### ISSUE THREAD

**Issue by kytrinyx** [golang/go#14244]
Context: https://tour.golang.org/concurrency/2

The channels code example declares a slice and names it `a` as so:

```
a := []int{7, 2, 8, -9, 4, 0}
```

Should this be named `s` (slice) rather than `a` (array, presumably)?

The `sum` function also uses `a` for the name of the function argument (`a []int`).

**Comment by kytrinyx** [comment]
@adg I should have pinged you on this one up front.

**Comment by adg** [comment]
I'm happy for it to be renamed to `s`.
