### ISSUE TITLE
tour: range Continued

### ISSUE THREAD

**Issue by theCompanyDream** [golang/go#14241]
Context: http://127.0.0.1:3999/moretypes/14

It took me a few minutes to tell that 1 << uint(i) meant 1^i if possible could you add a description saying that << is synonymous with math.power function

**Comment by cznic** [comment]
> It took me a few minutes to tell that 1 << uint(i) meant 1^i if possible could you add a description saying that << is synonymous with math.power function

FTR, `x << y` is `x * 2^y`.

**Comment by griesemer** [comment]
<< is pretty clearly described in the spec - also this section if about range not <<. Perhaps a comment on the line is all it takes:
```
pow[i] = 1 << uint(i) // == 2**i
```

(<< is not synonymous with math.Power which is more "Power"-full :-)

**Comment by kytrinyx** [comment]
Yes, I think the comment does the trick. I've submitted a CL to that effect.
