### ISSUE TITLE
Tests are too slow

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14243]
The tests are too slow. They can be parallelized, and all sleeps like this should be removed:

```go
func testNoService(t *testing.T, e env) {
        s, addr := serverSetUp(t, false, nil, math.MaxUint32, nil, nil, e)
        cc := clientSetUp(t, addr, nil, nil, "", e)
        tc := testpb.NewTestServiceClient(cc)
        defer tearDown(s, cc)
        // Make sure setting ack has been sent.                                                                                                                               
        time.Sleep(2 * time.Second)
```

Tests should almost never have sleeps in them. They're always either too slow or too fast (too flaky).

There are always better ways to synchronize.

**Comment by bradfitz** [comment]
Actually, if a bunch of these sleeps are removed, `t.Parallel()` might not even be needed.

**Comment by ianlancetaylor** [comment]
Which tests is this about?

**Comment by bradfitz** [comment]
Hah, wrong project. Sorry.
