### ISSUE TITLE
x/tools/cmd/godoc: improve recursive Internal call graph presentation 

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#14240]
What version of Go are you using (go version)?

N/A (go 1.5, go tip), using `golang.org/x/tools` at `fe74a4186116b8d7dd38a723993e0d84f8834b34`.

What operating system and processor architecture are you using?

N/A (OS X 10.11.3)

What did you do?

Ran `godoc -http :6060 -analysis type,pointer`.

What did you see instead?

Running analyses on an recursive function creates a rather interesting call graph, see image below. Could there be a better way to display the call graph of recursive functions?

<img width="384" alt="godoc example" src="https://cloud.githubusercontent.com/assets/3159064/12851372/d9b36972-cc29-11e5-81a6-42a62f987f0f.png">

Note: this has no priority, just creating an issue so it's not forgotten.

**Comment by alandonovan** [comment]
This is working as intended; the unrolling of a cyclic graph is an infinite tree.  I don't know of a better way to display an arbitrary cyclic graph; Sugiyama-style layouts do not scale beyond a few dozen nodes.
