### ISSUE TITLE
all go versions, Image package rectangle.Dx() returns one pixel short

### ISSUE THREAD

**Issue by alimoeeny** [golang/go#14253]
the `rectangle.Dx()` returns `r.Max.X - r.Min.X` while it should return `r.Max.X - r.Min.X + 1` 
https://golang.org/src/image/geom.go?s=2215:2242#L85

It is not just the `Dx()` and `Dy()`. In the image package in all the places that I've checked, the `Bounds()` and related functions return the top left as `(0,0)` but put right bottom corner at `(width, height)` when they should put it at `(width-1, height-1)`.
Have I missed something in the docs? Checking the color values using `At(x,y)` shows that the color (at least for JPEG images) at `(width, height) is black, while the color at `(width-1, height-1)` is a reasonable color from the image.

**Comment by bradfitz** [comment]
See the docs at https://golang.org/pkg/image/#Rectangle

"A Rectangle contains the points with Min.X <= X < Max.X, Min.Y <= Y < Max.Y."

I think this is working as intended and documented.
