### ISSUE TITLE
x/crypto/ssh: Return better error message for non-zero exit codes

### ISSUE THREAD

**Issue by variadico** [golang/go#14251]
**Version**
`go version go1.5.3 darwin/amd64`

**What I did**
I executed a script on a remote server through SSH.
```
if err := sesh.Run("/home/jaime/fail.sh"); err != nil {
    log.Println(err)
}
```
This is `fail.sh`.
```
#!/bin/sh
exit 1
```

**What I expected to see**
I expected to see a clear and concise error. Maybe something like: `Process exited with: 1.`

**What I saw instead**
I saw a slightly confusing and half-useless error: `Process exited with: 1. Reason was:  ()`

The code in question is here, [crypto/ssh/session.go:604]. This is happening because it's `Sprintf`ing empty `w.msg` and `w.signal` values. This doesn't seem right.

[crypto/ssh/session.go:604]: https://github.com/golang/crypto/blob/master/ssh/session.go#L604

**Comment by davecheney** [comment]
We could slop the printing of the `Reason was: ()` part if w.msg is blank.

**Comment by variadico** [comment]
Sounds reasonable. I'm willing to submit a PR, if possible.

**Comment by sctb** [comment]
@variadico Are you still working on this one, or is it free to pick up?

**Comment by variadico** [comment]
I never heard back from anyone, so I never started. But, it looks like someone else grabbed this already: https://go-review.googlesource.com/#/c/19444. The status says "Needs Code-Review".

**Comment by udayskyport** [comment]
@gopherbot 
I am still facing the issue where session.Run() returns --> Process exited with: 1. Reason was:  ()
if the scp path is incorrect.
Can you please help?

**Comment by ianlancetaylor** [comment]
@udayskyport Which version of Go are you using?

**Comment by udayskyport** [comment]
@gopherbot go1.6
