### ISSUE TITLE
html/template: removes content inside html comments

### ISSUE THREAD

**Issue by liggitt** [golang/go#14256]
This breaks templates that rely on things like conditional comments for adding classes.

Example:
```go
	data := `<!DOCTYPE html>
<!--[if IE 8]><html class="ie8"><![endif]-->
<!--[if IE 9]><html class="ie9"><![endif]-->
<!--[if gt IE 9]><!--><html><!--<![endif]-->

... content that relies on ie8/ie9 classes ...
`
	tmpl, _ := template.New("name").Parse(data)
	b := &bytes.Buffer{}
	tmpl.Execute(b, data)
	fmt.Println(b.String())
```
renders:
```
<!DOCTYPE html>


<html>

... content that relies on ie8/ie9 classes ...
```
http://play.golang.org/p/MM27D4Qj9j

The behavior of dropping all content inside comments is also undocumented at https://golang.org/pkg/html/template/

**Comment by minux** [comment]
This is working as intended.

Please see https://groups.google.com/forum/#!topic/golang-nuts/mriui-HG65A for
discussion and workaround.

**Comment by liggitt** [comment]
Can the `noescape` syntax be added to the template godoc? That is useful to know

**Comment by liggitt** [comment]
actually, saw that noescape no longer exists... the described workaround assumes control of the go code, but would not work if a template author needed to use comments
