### ISSUE TITLE
x/tools/cmd/godoc: ignored "too many open files" errors can cause incomplete /pkg/ subdirectories listings

### ISSUE THREAD

**Issue by shurcooL** [golang/go#14252]
### What version of Go are you using (go version)?

`go version go1.6rc2 darwin/amd64`
### What operating system and processor architecture are you using?

OS X 10.11.3 (64-bit).
### What did you do?
1. Have a GOPATH workspace with many, many packages.
2. Run `godoc -http=localhost:6060`.
3. Visit http://localhost:6060/pkg/crypto/ (it's used as an example, it affects all packages equally).
### What did you expect to see?

A complete list of subdirectories, with their package synopses.

![image](https://cloud.githubusercontent.com/assets/1924134/12876337/964e4db8-cdb5-11e5-87dc-3a7a5064d4a2.png)
### What did you see instead?

Randomly incomplete listing of subdirectories, and some missing package synopses.

![image](https://cloud.githubusercontent.com/assets/1924134/12876326/4bff2386-cdb5-11e5-9987-78f5ad1bd8fc.png)

![image](https://cloud.githubusercontent.com/assets/1924134/12876330/646c6690-cdb5-11e5-97b0-8f1fd7defb7c.png)

**Comment by shurcooL** [comment]
I've looked into why it happens. At first I thought it might be some race condition, but I've learned it's not.

Instead, the problem is here:

https://github.com/golang/tools/blob/fe74a4186116b8d7dd38a723993e0d84f8834b34/godoc/dirtrees.go#L107-L127

Because all GOROOT and GOPATH workspaces are "walked" in parallel (likely with some concurrency limits), it may run into "too many files open" limits and erroring out. The linked code segment ignores all situations where parsing the .go files results in errors (`if err == nil { ... }`).

I've added a simple `else if err != nil { log.Println(err) }` section there and I saw many "too many files open" errors occur both on .go files in GOROOT as well as in GOPATH.

**Comment by bradfitz** [comment]
@adg improved this in https://go-review.googlesource.com/24060

I'll send a bit more.

**Comment by kevinburke** [comment]
I think this has been addressed.

**Comment by kevinburke** [comment]
Closing, feel free to reopen if this is still a problem, or there's a way to reproduce on tip.

**Comment by shurcooL** [comment]
I suspect that the 2 commits to help this issue (a2a552218a0e22e6fb22469f49ef371b492f6178 and 72ed06fbe2cf37c56ab4877b06571d2e7620627b) were sufficient to resolve it. If I ever run into this again, I'll post an update.
