### ISSUE TITLE
hash/crc32: Use "slice-by-8" for Castagnoli and smaller payloads.

### ISSUE THREAD

**Issue by klauspost** [golang/go#14257]
We should add https://github.com/klauspost/crc32 which uses  "slicing by 8" optimization to Castagnoli tables which will speed  up CRC32 calculation on systems without assembler (all but AMD64). 

In my tests, it is faster to use "slicing by 8" for sizes all down to 
16 bytes, so the switchover point has been adjusted. 

There are no benchmarks for small sizes, so I have added one for 40 bytes, 
as well as one for bigger sizes (32KB). 

```
Castagnoli, No assembler, 40 Byte payload: (before, after) 
BenchmarkCastagnoli40B-4   10000000               161 ns/op         246.94   MB/s 
BenchmarkCastagnoli40B-4   20000000               100 ns/op         398.01   MB/s 

Castagnoli, No assembler, 32KB payload: (before, after) 
BenchmarkCastagnoli32KB-4     10000            115426 ns/op         283.89   MB/s 
BenchmarkCastagnoli32KB-4     30000             45171 ns/op         725.41   MB/s 

IEEE, No assembler, 1KB payload: (before, after) 
BenchmarkCrc1KB-4              500000              3604 ns/op           284.10 MB/s 
BenchmarkCrc1KB-4             1000000              1463 ns/op           699.79 MB/s 
```

**Comment by rsc** [comment]
Done in b212c68b if I understand correctly.
