### ISSUE TITLE
net/mail: ParseAddress should support UTF-8 (RFC 6532)

### ISSUE THREAD

**Issue by ConradIrwin** [golang/go#14260]
I'm using go v1.5.3, and parsing emails found in the wild (from senders like Linkedin and Gmail).

They expect to be able to include UTF-8 in email headers without q-encoding, but this is not currently supported by `mail.ParseAddress`.

There are two possible solutions:

* We can update the parsing functions to allow only valid UTF-8 as defined by RFC 6532,
* OR, we can allow arbitrary 8-byte strings, and allow the caller to decide whether it cares about the encoding of the returned string.

My experience from working on the `mail` gem for ruby would suggest that the second approach is the most pragmatic — often times email is badly formed, and it's really useful to be able to provide a "best-effort" parsing of badly formed email headers. However it seems like the go project tends a little bit more towards correctness, in which case the first approach may sit better in the standard library, and people who want the fuzzy behaviour can do it themselves.

**Comment by dsymonds** [comment]
RFC 6532 is really an extension of RFC 5322, which we claim to support, so it seems fine to permit the extensions that RFC 6532 defines. I'm not keen on net/mail going out of its way to parse broken mail messages; it just makes it harder to use for the non-broken cases.

**Comment by ConradIrwin** [comment]
Ok, sounds good. I'll take a stab at updating the parser to accept UTF-8 multibyte-characters too. (I'm happy for serialization to continue using q-encoding for such names).

**Comment by alexcesaro** [comment]
I agree. I don't think the stdlib should handle broken input. Fixing broken emails should be the role of third-party packages.

**Comment by ConradIrwin** [comment]
I've submitted a CL https://go-review.googlesource.com/19687, would appreciate any feedback you have.
