### ISSUE TITLE
cmd/compile: bad error for very short malformed package file

### ISSUE THREAD

**Issue by rsc** [golang/go#14270]
I'm redoing the package file format and code, and that work should fix this.

Noticed while debugging a cmd/go issue:

```
$ echo package p >p.go
$ echo 'import _ "./q"' >>p.go
$ echo broken >q.a
$ go tool compile p.go
p.go:2: import /tmp/q.a: not a package file
$
```

So far so good. But take the \n away from q.a:

```
$ echo -n broken >q.a
$ go tool compile p.go
compile: reading input: EOF
$ 
```

That's not useful: it doesn't even say what file is broken.

Like I said, the new package file code should fix this. This issue is a reminder to verify that. Please don't send CLs fixing the old code.

**Comment by quentinmit** [comment]
@rsc is this now fixed?

**Comment by rsc** [comment]
No, because the new packages haven't happened.
