### ISSUE TITLE
net/http: http request lost data when a lot of data is submitted from a form

### ISSUE THREAD

**Issue by kyle11rd** [golang/go#14272]
I have a template with multiple drop down lists in a form:

    <form action="/orderinfo" method="post">

        <select name="Item">
          {{range .Items}}
            <option>{{.}}</option>
          {{end}}
        </select>

        <select name="Item">
          {{range .Items}}
            <option>{{.}}</option>
          {{end}}
        </select>

    ... a lot more of the same drop down list....

        <select name="Item">
          {{range .Items}}
            <option>{{.}}</option>
          {{end}}
        </select>

       <input type="submit" value="Save & Proceed">
     </form>

Where 

    Items: []string{"Apple", "Banana", "Orange", "Cabbage"},

The problem is, when I have 9 drop down lists, r.Form is 

    map[Item:[Apple Apple Apple Apple Apple Apple Apple Apple Apple]]

But when I have 10 or more drop down lists, r.Form becomes 

    map[]

p.s. This happens with Go 1.5.3

**Comment by davecheney** [comment]
Thank you for your report. There are several issues here, the first is the repeated values in the 9 value case and the missing value in the 10 value case.

Can you please provide a small runnable sample with a http handler and template that demonstrate this problem so we can investigate.

**Comment by kyle11rd** [comment]
Here is the link:

https://play.golang.org/p/ZUcoPCQKmK

Please copy and run on local machine with port 8080. It will print out r.Form after the button is clicked. 

The above code has 2 drop down lists in the template, please copy and paste to more then 10 of them and you will see r.Form is empty.

Thanks!

**Comment by davecheney** [comment]
Please check the error from your template executions. This is probably the
source of your error.

**Comment by davecheney** [comment]
And the parse

**Comment by kyle11rd** [comment]
There are no errors from err functions. So I use "_" in this example.

**Comment by cespare** [comment]
@kyle11rd `r.ParseForm()` is returning a non-nil error that you're not checking.

**Comment by kyle11rd** [comment]
https://play.golang.org/p/O0OqEkGFLI

Here I have included error checks, unfortunately no error on my side.

**Comment by cespare** [comment]
@kyle11rd no, you're not checking the `ParseForm` error, and it is not nil.

The problem is that you're reading the request body (with ParseForm) **after** you've written the response. You need to read first, then write.

**Comment by kyle11rd** [comment]
!!!!!!!!!!!!!!!!!!!!!
You are right.. Never thought ParseForm can return this error:

    http: invalid Read on closed Body

Strange that with only a few drop down lists no error is returned...
