### ISSUE TITLE
defer recover() doesn't work

### ISSUE THREAD

**Issue by Merovius** [golang/go#14273]
When trying to solve Dave Chaney's popquiz https://twitter.com/davecheney/status/696883109124403200 I saw that this doesn't work:
http://play.golang.org/p/Oc2koIXkL7
but this does:
http://play.golang.org/p/0HzIJgVRtP

It seems counter intuitive that the first doesn't work, though it's technically allowed by the spec (as the spec always talks about recover being called "by a deferred function".

**Comment by cespare** [comment]
The spec (and https://golang.org/pkg/builtin/#recover) both say that recover has to be called *by* a deferred function to be useful.

> The return value of recover is nil if any of the following conditions holds: [...] recover was not called directly by a deferred function.

and

> Executing a call to recover inside a deferred function (but not any function called by it) stops the panicking sequence by restoring normal execution and retrieves the error value passed to the call of panic.

I admit that I see no reason why

    defer recover()

should not operate the same way as

    defer func() { recover() }()

but the current behavior does follow the documentation.

(Also, one argument against relaxing the definition of recover() in this way is that it might suggest to people that `defer recover()` is a good idea.)

**Comment by Merovius** [comment]
Yeah, see original comment, I'm not doubting that the spec allows it, technically. I created this issue mainly because I'm unsure if this was the *intended* reading of those paragraphs. If it is, fine, I acknowledge that it won't matter often enough to be a big deal. Though I could also see it as "no one ever thought about this so they just put *some* phrasing to that effect there.

> (Also, one argument against relaxing the definition of recover() in this way is that it might suggest to people that defer recover() is a good idea.)

Why wouldn't it be? I think using recover is the only way to write this function in a goroutine-safe way, I see value in such a function (or a variation thereof) to exist (for example: I hide an asynchronous process from a user of my package and want to offer an idempotent, goroutine-safe Close) and I see no particular reason why we *need* to wrap recover in a func() then.

**Comment by ianlancetaylor** [comment]
This is working as intended.  Here is the reply I wrote one of the times this came up earlier: https://groups.google.com/d/msg/golang-nuts/SwmjC_j5q90/99rdN1LEN1kJ .

Note that the Go project doesn't use the issue tracker for discussion or questions.  If you want to discuss this further please see https://golang.org/wiki/Questions .  Thanks.
