### ISSUE TITLE
golang.org: documentation examples show spell-check lines 

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#14287]
On the documentation page for package `time` (as seen [here](https://golang.org/pkg/time/#Time.Format)), example code contains what look like spell-check red underlines:

![screenshot from 2016-02-10 11 24 56](https://cloud.githubusercontent.com/assets/7328370/12953547/ee4acec6-cfe8-11e5-95fc-c3996d11469c.png)

I'm using Firefox 40.0.3

**Comment by ianlancetaylor** [comment]
I don't see any red underlines there, using Chrome 48.0.2564.103.  I also don't see any using Firefox 44.0.  Could they be from some sort of Firefox extension or setting that you have enabled?

**Comment by bradfitz** [comment]
There are things like `<textarea spellcheck="false">` we could set. Maybe with CSS too.

/cc @adg @broady

**Comment by stevekuznetsov** [comment]
@ianlancetaylor I'm seeing it with no extensions installed. Can confirm it doesn't show up on Chrome 45.0.2454.85

**Comment by broady** [comment]
@ianlancetaylor you need to click inside the textarea. Happens for me. My UA:
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36```

**Comment by ianlancetaylor** [comment]
Ah, yes, I do see it if I click inside the text area.
