### ISSUE TITLE
runtime: addrspace_free bug causes large mmap to fail on mips64

### ISSUE THREAD

**Issue by eswierk** [golang/go#14297]
Testing the new mips64 support, I ran into out of memory errors whenever the heap grew beyond ~500 MB. I isolated the problem to an apparent bug in addrspace_free (https://github.com/golang/go/blob/53b6661/src/runtime/mem_linux.go#L34). mincore returns _ENOMEM, not -_ENOMEM, if the given page is unmapped. Removing the minus sign makes the problem go away.

I don't know if there are any platforms where the return value is actually negative. The equivalent function in the gccgo runtime also assumes a positive value.

**Comment by bradfitz** [comment]
/cc @ianlancetaylor 

I tagged this Go1.6Maybe, if there's a tiny mips64-only fix. But it's not really a supported architecture yet, so it's probably a 1.7 issue.

**Comment by davecheney** [comment]
@bradfitz this file is used by all linux implementations. I think this warrants investigation as it could affect supported linux platforms.

**Comment by bradfitz** [comment]
Yes, that's used by all linux implementations. We can investigate, but if nobody else is having problems, we don't want to touch common code this late in 1.6 if we can help it. Maybe all other architectures correct for this elsewhere but mips64 doesn't. That's the tiny fix I was alluding to.

**Comment by davecheney** [comment]
I'm concerned that with the exception of arm32, nothing is really memory constrained enough to trigger this error path.

**Comment by ianlancetaylor** [comment]
On GNU/Linux, on 386, amd64, arm, and arm64, system calls return a negative errno value, in eax, rax, r0, r0, respectively.  On mips64 and ppc64, they return a positive errno value, in r2 and r3, respectively.

In the runtime package, I think that the implementation of mmap on arm64 is wrong and the implementation of mincore on mips64 and ppc64 is wrong.

**Comment by davecheney** [comment]
Thanks Ian. I wonder if the scavenger being disabled on arm64 and ppc64
systems has hidden this error so far. I'm assuming that if we don't use
madvise to return memory to the OS, mincore could be wrong and it wouldn't
matter -- just a wild guess.

What is the page size on mips64?

**Comment by eswierk** [comment]
Adjustable I think, but normally 4k.

**Comment by ianlancetaylor** [comment]
@eswierk can you test https://golang.org/cl/19455?

**Comment by eswierk** [comment]
I tested https://golang.org/cl/19455 on mips64 hardware and it didn't work. I added a comment with details.
