### ISSUE TITLE
tour: rand.Intn(10) always returns 1

### ISSUE THREAD

**Issue by d5ve** [golang/go#14303]
Context: http://127.0.0.1:3999/basics/1

```fmt.Println("My favorite number is", rand.Intn(10))```

When I run basics/1 on the tour, the random number returned is always 1. This persists between different runs of  ```$ go tool tour```

```
$ go version
go version go1.5.3 darwin/amd64
```

**Comment by davecheney** [comment]
Have a read of the documentation for the math/rand package. If the random number generator is not seeded, it defaults to seed of 1. https://golang.org/pkg/math/rand/#Seed. As the generator always starts with the same seed, it will always emit the same sequence.

**Comment by d5ve** [comment]
I can see a similar closed issue at https://github.com/golang/go/issues/12371

**Comment by d5ve** [comment]
If the tour code doesn't have the seed call, then I think that it is an issue.

**Comment by davecheney** [comment]
The usual way to seed a rng is with the current time (not cryptographically secure of course), but the time is also fixed in the playground, so you'll still get the same seed and same sequence.

**Comment by d5ve** [comment]
I see. I guess seeding with the PID wouldn't help in this case either as the same PID is likely used for the whole tour.

**Comment by minux** [comment]
We could seed the rng on playground with crypto/rand as NaCl has
a real CSPRNG. But then the problem is that the output for playground
programs are cached, so if you don't change the program, the result
will still be same.
