### ISSUE TITLE
testing: (*B).Fatal should cause non-zero exit status

### ISSUE THREAD

**Issue by davecheney** [golang/go#14307]
```
lucky(~/src/issue) % cat issue_test.go 
package issue

import "testing"

func BenchmarkFail(b *testing.B) {
        for n := 0; n < b.N; n++ {
                b.Fatal("non zero exit")
        }
}
lucky(~/src/issue) % go test issue_test.go -test.bench=.
testing: warning: no tests to run
PASS
BenchmarkFail-4 --- FAIL: BenchmarkFail-4
        issue_test.go:7: non zero exit
ok      command-line-arguments  0.003s
lucky(~/src/issue) % echo $?
0
```

**Comment by robpike** [comment]
The subject of the issue does not match the behavior of the program, and there is no explanatory text. Please explain.

**Comment by davecheney** [comment]
`b.Fatal` should terminate the test program like its counterpart `t.Fatal`

**Comment by robpike** [comment]
t.Fatal does not terminate the program.

**Comment by davecheney** [comment]
I am sorry, you are correct. But calling t.Fatal in a test will cause the
test binary to eventually exit with a non zero error code. I was surprised
that calling the counterpart on testing.B did not cause the same behaviour.

**Comment by cespare** [comment]
@davecheney want to change the issue title? Maybe "testing: (*B).Fatal should cause non-zero exit status".

I took a brief look at this. The code does this right now (irrelevant lines elided):

``` go
testOk := RunTests(m.matchString, m.tests)
exampleOk := RunExamples(m.matchString, m.examples)
if !testOk || !exampleOk {
	fmt.Println("FAIL")
	return 1
}
fmt.Println("PASS")
RunBenchmarks(m.matchString, m.benchmarks)
return 0
```

Unfortunately the exported function RunBenchmarks doesn't return failure status. Perhaps we could modify InternalBenchmark to smuggle failure status through.

If we fix this, should we also only print "PASS" if benchmarks pass, as well as tests and examples?

**Comment by cmarcelo** [comment]
Would adding a return value to RunBenchmarks break the compatibility promise? It seems to me it keeps the source compatibility since ignoring the single return value doesn't require any change to calling code.

**Comment by bradfitz** [comment]
> Would adding a return value to RunBenchmarks break the compatibility promise?

Yes.

**Comment by bradfitz** [comment]
@cmarcelo, see http://blog.merovius.de/2015/07/29/backwards-compatibility-in-go.html

**Comment by cmarcelo** [comment]
@bradfitz Thanks for the link.

I wrote a CL that adds an extra field to the struct InternalBenchmark to pass the information (a "failed bool" field). It does pass the API check in all.bash, and seems "acceptable" from reading https://golang.org/doc/go1compat document, and the Internal in the name makes me thing is not widely used. On the other hand it doesn't pass the criteria from the post you've linked. So I'm a bit unsure whether is OK or not.

Pushed the CL in https://go-review.googlesource.com/#/c/19889/.

**Comment by cmarcelo** [comment]
Ian had a better suggestion without having to add a field to the exported struct, it became patch set 3 in the CL.

I'm still curious about the compatibility: because of the embedding explanation mentioned in the link, is adding fields a no-go for exported structs?

**Comment by ianlancetaylor** [comment]
In the compatibility doc (https://golang.org/doc/go1compat) we explicitly permit adding fields to exported structs.
