### ISSUE TITLE
path/filepath: filepath.Clean() does not ensure newlines are stripped.

### ISSUE THREAD

**Issue by tduzan** [golang/go#14316]
I have a Go program that's being used for some queue management functions for Postfix.  I'm getting the queue_directory value from postconf and then passing it into filepath.Clean() to return a valid path.  Unfortunately, when I stat this it fails because it ends in a newline character.  My understanding is that since a newline character is not a valid path character it should be stripped via filepath.Clean().

getQueueDir()
```Go
func getQueueDir(config *Config) (string, error) {
	var (
		out      []byte
		err      error
		queuedir string
		here     bool
	)
	args := []string{"-h", "queue_directory"}
	if out, err = exec.Command("postconf", args...).Output(); err != nil {
		panic(err)
	}
	queuedir = filepath.Clean(string(out))
	if config.Verbose {
		fmt.Println("Queue dir retrieved from postconf.")
		fmt.Println(queuedir)
	}
	if here, err = util.Exists(queuedir); err != nil {
		return queuedir, err
	} else if here != true {
		return queuedir, ErrQueueDirectoryMissing
	}
	return queuedir, nil
}
```

util.Exists()
```Go
func Exists(dirorfile string) (bool, error) {
	if _, err := os.Stat(dirorfile); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return true, err
	}
	return true, nil
}
```

`strace` shows the issue:

```
[pid 17402] stat("/var/spool/postfix\n", 0xc208060240) = -1 ENOENT (No such file or directory)
[pid 17402] write(1, "UNKNOWN: Process Terminated: The"..., 105UNKNOWN: Process Terminated: The queue directory configured for Postfix is either missing or unreadable.
) = 105
```

I can get around this in the interim by passing the string through `strings.TrimSuffix()`

**Comment by bradfitz** [comment]
> My understanding is that since a newline character is not a valid path character it should be stripped via filepath.Clean

That's the root of the problem. filepath.Clean does not do that, and is not documented to do that.

I think this is working as intended & documented, and https://golang.org/doc/go1compat would preclude us from changing this right now in any case.

**Comment by dominikh** [comment]
On top of that, newlines as part of file names are valid on many file systems.
