### ISSUE TITLE
Use environment variables for trusted certificate store

### ISSUE THREAD

**Issue by raspy** [golang/go#14310]
OpenSSL allows to use SSL_CERT_FILE and SSL_CERT_DIR to point to trusted root CA certificates. This is extremely useful when trying to connect to sites secured with enterprise internal root CA on hosts where one does not manage system certificate store. It would be good to have such possibility with Go as well.

**Comment by calmh** [comment]
I second this as it would also allow programs to run easier under nontypical environments. I recall seeing issues with nonstandard cert locations on certain NAS devices and similar for example.

I'd be happy to contribute this if it's accepted as an idea.

**Comment by minux** [comment]
Duplicate, merged into #14311.
