### ISSUE TITLE
LDAP support in golang

### ISSUE THREAD

**Issue by asambeka** [golang/go#14314]
It is pretty lame to see no built-in support for LDAP v3. LDAP is a most widely used protocol for authentication and identity management. Having a core package with full ASN/DER/BER support will make it very easy for everyone. Mozilla C LDAP SDK and Java JNDI could be good reference points for this implementation. I would love to see LDAP included in roadmap for golang (along with ASN/BER/DER which will open the doors for server side implementation as well).

**Comment by bradfitz** [comment]
See https://golang.org/doc/faq#x_in_std

**Comment by asambeka** [comment]
I believe X is referring to X.yyy specs(ITU). LDAP v3 is an RFC spec. X'specs were for directory support(X.500-X.522). Even with X' golang does support X.509. So the argument is not valid. Also, LDAP is structured, uses ASN.1 for structured data representation. LDAP is core to system authentication  and authorization. Not supporting LDAP will restrict adoption of golang for security applications.

**Comment by bradfitz** [comment]
No, I wrote that FAQ entry. X is a placeholder to mean anything.

We are not adding LDAP to the standard library. See https://godoc.org/?q=ldap

I'm sorry if you find this lame.
