### ISSUE TITLE
Support secondary format for date parsing

### ISSUE THREAD

**Issue by dlsniper** [golang/go#14312]
Hi,

I'm not sure if this should go via the proposal process but I wonder if Go could support an additional format for date parsing. The one that I have in mind is: `12/13/2006` which would make it easier to understand for all of us non-US accustomed users of Go as we'd at least have a chance to know which is is the month and which is the day.

Please let me know if I should open this separately on the mailing list or similar.

Thank you.

**Comment by bradfitz** [comment]
I think that design ship sailed about 4 years ago now when Go 1 was released. You're welcome to make your own time parsing package, though. But adding new identical but different parsing mechanisms to the standard library just invites unnecessary user confusion.
