### ISSUE TITLE
cmd/compile: improve error message when a method expression references ambiguous method name

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#14321]
In the following program

``` Go
package main
type A struct {}
func (A) F() {}
type B struct {}
func (B) F() {}
type C struct {
    A
    B
}
var _ = C.F
func main() {}
```

the `go` compiler issues error message `C.F undefined (type C has no method F)`, whereas the type `C` in fact has a method `F`, even two of them :)

`gccgo` and `gotype` correctly report ambiguous method error.

go version devel +76cb265 Sat Feb 13 06:46:47 2016 +0000 linux/amd64

**Comment by minux** [comment]
FTR, according to the spec, type C really doesn't have method
F because neither of them is promoted. (See #14309.)

so technically gc is correct and there is no ambiguities here.

**Comment by momchil-velikov** [comment]
Right. I see now. Thank you.

**Comment by odeke-em** [comment]
@minux after @momchil-velikov's agreement of your explanation, do you think this issue should be closed?

**Comment by griesemer** [comment]
This is not about whether gc has a bug or not - this is about improving the error message. gc may be technically correct, but a typical user not fluent in the fine points of the spec by heart (really, all of us), is going to scratch his or her head.

I think remarking on the ambiguity of the selector in the error message is helpful.

Please keep this open. It's not urgent, though.

**Comment by rsc** [comment]
It would be nice to say '(type C has ambiguous method F)' instead, in this case.
