### ISSUE TITLE
net: LookupPort does not perform lookup if service starts with number

### ISSUE THREAD

**Issue by joushou** [golang/go#14322]
Calling net.LookupPort with a service-name starting with a number, regardless of whether or not it is in /etc/services, incorrectly returns the numeric prefix of the service-name as port. In my case, I was trying to perform a lookup on "9pfs".

LookupPort (net/lookup.go) calls dtoi (net/parse.go). lookupPort is only called if dtoi returns that it was not successful, but dtoi is successful as long as the string starts with a digit, which makes it incapable of detecting if a string is a service or a port.

**Test code**
```go
package main

import "fmt"
import "net"

func main() {
	x, err := net.LookupPort("tcp", "9pfs")
	fmt.Printf("Port: %d, err: %v\n", x, err)
	x, err = net.LookupPort("tcp", "1234port")
	fmt.Printf("Port: %d, err: %v\n", x, err)
	x, err = net.LookupPort("tcp", "port1234")
	fmt.Printf("Port: %d, err: %v\n", x, err)
	x, err = net.LookupPort("tcp", "http")
	fmt.Printf("Port: %d, err: %v\n", x, err)
}
```

**Expected result**
```
Port: 564, err: <nil>
Port: 0, err: lookup tcp/1234port: nodename nor servname provided, or not known
Port: 0, err: lookup tcp/port1234: nodename nor servname provided, or not known
Port: 80, err: <nil>
```

**Actual result**
```
Port: 9, err: <nil>
Port: 1234, err: <nil>
Port: 0, err: lookup tcp/port1234: nodename nor servname provided, or not known
Port: 80, err: <nil>
```

**Comment by msiebuhr** [comment]
The above CL fails on quite a few platforms, as `9pfs` apparently isn't included in `/etc/services` (I don't have a linux box at hand to check on; my FreeBSD and OS X boxes both have it).

I hope to dig a bit more into it once the kids have been put to bed. And any ideas on how to handle this? Leave the test out entirely, or selectively include that particular test only on known-good platforms?

**Comment by joushou** [comment]
Example 2 (the 1234port one) can test without an entry in service:
```go
x, err := net.LookupPort("tcp", "1234superfake")
if err == nil {
    t.Errorf("fake service was accepted as %s", x)
}
```

**Comment by msiebuhr** [comment]
@joushou - I don't quite follow your idea for testing `1234port` without service. AFAIK, the test-code already checks if the lookup is expected to fail or not.

What really puzzles me is that this change causes some of the other networking tests to fail on windows/386...

**Comment by joushou** [comment]
In the previous code, 1234port would always succeed, returning 1234. The correct behaviour is to return the port if it is in /etc/services, otherwise fail. If you use an intentionally fake service starting with a digit, you can verify that the fix works as intended without having any requirements to /etc/services. This might be necessary, as only some Linux distros as well as BSD and OSX have 9pfs in /etc/services.

Does that make sense?

Not sure about the other tests failing, haven't looked into them.

**Comment by msiebuhr** [comment]
Agreed, it would be best with a positive test too. But I fail to see how the code you gave above adds a fake service to do the lookup against. If I revert the fix in `net/lookup.go` and re-run the tests, they do indeed fail to report an error when looking up `123badservice`.

Digging through what's being called, I should be able to dump something into the `services`-map in https://golang.org/src/net/port_unix.go, but that will only fix it on unixes w/o. cgo. As far as I've skimmed the others, they fairly begin calling system libraries...

**Comment by joushou** [comment]
Ah, sorry, you already had a test for 123badservice. I'm just spouting nonsense, then.

As for a positive test, a quick read of my ubuntu box's /etc/services show that a positive test on all platforms won't be possible. It contains no services starting with a digit (although OS X got 43 of such entries). I suspect injection of entries on some platforms might make the test a bit too nasty.

As for the test errors. the issue is that you're now accepting arbitrarily large ports, as you fall to lookupPort if the port wasn't ok (`(!ok && port != big && port != -big)`) *or* if it didn't consume everything (`consumed != len(service)`). That means that, if the port was invalid because the service was longer than a valid port, it'll call lookupPort instead of throwing and error with "invalid port".

I guess the correct flow is either:
* Look up service. If found, return
* Convert to port number. If successful, return
* Return error.

Or:
* Convert to port number. If successful and fully consumed, return
* Look up service. If found, return
* Return error.

I'm not sure if service should take precedence here. For the latter, the code should probably look like: 
```go
func LookupPort(network, service string) (port int, err error) {
	if service == "" {
		// Lock in the legacy behavior that an empty string
		// means port 0. See Issue 13610.
		return 0, nil
	}
	port, consumed, ok := dtoi(service, 0)
	if ok || port == big || port == -big {
		if 0 > port || port > 65535 {
			return 0, &AddrError{Err: "invalid port", Addr: service}
		}

		return port, nil
	}
	
	return lookupPort(network, service)
}
```

(Note that I just return lookupPort. If lookupPort can return non-0 port number with a non-nil error, then this changes behaviour over the previous error handling, which always returned 0 as port with a non-nil error).

**Comment by joushou** [comment]
(I'm sorry for not just having made a CL for this myself, but I haven't figured out the entire process for that yet)
