### ISSUE TITLE
misc/cgo/test: callback_c.c should compile on Windows 32-bit

### ISSUE THREAD

**Issue by nadiasvertex** [golang/go#14328]
The Windows API does not have a sleep() function, it has a
   Sleep() function. In addition, the parameter does not take
   seconds. It takes milliseconds.

   https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298(v=vs.85).aspx

I have submitted a patch to address this issue: https://go-review.googlesource.com/#/c/19500/

**Comment by alexbrainman** [comment]
Please provide instructions to demonstrate the problem.

You say

> callback_c.c should compile

so I assume something does not compile for you. What exactly doesn't compile?

Thank you.

Alex

**Comment by minux** [comment]
sleep should be provided by libmingwex.a.

The file callback_c.c has been compiled fine on the 32-bit
windows builder, so I don't think we need to change anything.

**Comment by nadiasvertex** [comment]
@alexbrainman : The compiler complains that sleep() is an undefined function. To demonstrate the problem, compile Go on a 32-bit Windows system using the compiler at http://tdm-gcc.tdragon.net/

@minux: Two observations:

1. You include windows.h. Which logically presupposes that you want the Windows API call, and not whatever mingw may provide.
2. I have been told in other patches to prefer the Windows API, as opposed to whatever compatibility layer may be provided by a compiler.

Also:

1. Either the code is not actually getting compiled on 32-bit because it doesn't support the code paths that expose the test OR
2. The compiler at http://tdm-gcc.tdragon.net/ does not provide the sleep() compatibility function.

**Comment by nadiasvertex** [comment]
I might take this opportunity to make another point. I followed the instructions on:

https://github.com/golang/go/wiki/WindowsBuild

Which recommended:

https://github.com/golang/winstrap

which is what I used. This program installs the compiler from TDM-GCC. I later installed the latest TDM-GCC version (5.1) instead of 4.9. So, it's not like I went all wild west here. :-) 

I also tried the manual MingW/Msys route but it never worked for me. So. That may give you context into my build environment.

**Comment by alexbrainman** [comment]
> sleep should be provided by libmingwex.a.

We have implemented sleep here https://go.googlesource.com/go/+/master/misc/cgo/test/sleep_windows_386.go#14

> @alexbrainman : The compiler complains that sleep() is an undefined function.

Can you provide steps for me to reproduce your problem? Don't worry about me having same mingw version as you for the moment. What should I do to see the error you're seeing? Thank you.

Alex

**Comment by minux** [comment]
I don't believe the file is not build on 32-bit windows as I just tried,
the relevant test
TestParallelSleep does run (and pass) on 32-bit windows.

Hint: see misc/cgo/test/sleep_windows_386.go.

**Comment by nadiasvertex** [comment]
@alexbrainman I have already told you how to reproduce it. All I do is run all.bat.

**Comment by alexbrainman** [comment]
> @alexbrainman All I do is run all.bat.

Please provide error message you see when your all.bat run fails.
What OS do you use? What does "go version" say? What does "gcc --version" say?
Thank you.

Alex

**Comment by nadiasvertex** [comment]
```
##### ../misc/cgo/test
# _/C_/Users/Christopher/t/misc/cgo/test
.\callback_c.c: In function 'mysleep':
.\callback_c.c:39:2: error: implicit declaration of function 'sleep' [-Werror=implicit-function-declaration]
  sleep(seconds);
  ^
cc1.exe: all warnings being treated as errors
FAIL    _/C_/Users/Christopher/t/misc/cgo/test [build failed]
2016/02/15 18:34:45 Failed: exit status 2
# _/C_/Users/Christopher/t/misc/cgo/test
.\callback_c.c: In function 'mysleep':
.\callback_c.c:39:2: error: implicit declaration of function 'sleep' [-Werror=implicit-function-declaration]
  sleep(seconds);
  ^
cc1.exe: all warnings being treated as errors
FAIL    _/C_/Users/Christopher/t/misc/cgo/test [build failed]
2016/02/15 18:34:47 Failed: exit status 2
# _/C_/Users/Christopher/t/misc/cgo/test
.\callback_c.c: In function 'mysleep':
.\callback_c.c:39:2: error: implicit declaration of function 'sleep' [-Werror=implicit-function-declaration]
  sleep(seconds);
  ^
cc1.exe: all warnings being treated as errors
FAIL    _/C_/Users/Christopher/t/misc/cgo/test [build failed]
2016/02/15 18:34:47 Failed: exit status 2
# _/C_/Users/Christopher/t/misc/cgo/test
.\callback_c.c: In function 'mysleep':
.\callback_c.c:39:2: error: implicit declaration of function 'sleep' [-Werror=implicit-function-declaration]
  sleep(seconds);
  ^
cc1.exe: all warnings being treated as errors
FAIL    _/C_/Users/Christopher/t/misc/cgo/test [build failed]
2016/02/15 18:34:48 Failed: exit status 2
2016/02/15 18:34:48 FAILED

C:\Users\Christopher\t\src>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-32/bin/../libexec/gcc/mingw32/5.1.0/lto-wrapper.exe
Target: mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=mingw32 --enable-langu
ages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-g
raphite --enable-libstdcxx-debug --enable-threads=posix --enable-version-specifi
c-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable
-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-reg
istry --disable-symvers --enable-cxx-flags='-fno-function-sections -fno-data-sec
tions -DWINPTHREAD_STATIC' --prefix=/mingw32tdm --with-local-prefix=/mingw32tdm
--with-pkgversion=tdm-1 --enable-sjlj-exceptions --with-bugurl=http://tdm-gcc.td
ragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm-1)


C:\Users\Christopher\t\src>systeminfo
OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Model:              VirtualBox
System Type:               X86-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: x86 Family 6 Model 60 Stepping 3 GenuineIntel ~2294 Mhz

C:\Users\Christopher\t\src>ver

Microsoft Windows [Version 6.1.7601]
```

**Comment by ianlancetaylor** [comment]
What happened is that in GCC 5 the default compilation mode changed to C11 mode (https://gcc.gnu.org/gcc-5/changes.html, see the note about -std=gnu11).  In C11, an implicit function declaration is an error by default.  In versions of C before C99, it is not.

To fix this we need to add an explicit declaration of sleep in misc/cgo/test/callback_c.c.  Or it might be even simpler to copy sleep_windows_386.go into callback_c.c, since we already have a `#ifdef` in the latter anyhow.

**Comment by nadiasvertex** [comment]
Great. Is someone else doing this, or would you like me to update this patch?

**Comment by alexbrainman** [comment]
@nadiasvertex go ahead and send CL (as per Ian's suggestion) once Go tree opens after go1.6 release. Thank you.

Alex
