### ISSUE TITLE
zipfs "file not found" error should make `os.IsNotExist` return true

### ISSUE THREAD

**Issue by beyang** [golang/go#14330]
This concerns https://github.com/golang/tools/blob/master/godoc/vfs/zipfs/zipfs.go#L115
```
		return -1, zipFI{}, fmt.Errorf("file not found: /%s", zippath)
```

It is common to use `os.IsNotExist(err)` to check if a filesystem operation failed because it didn't find a file. Should the above line be modified to return a `os.PathError` (or something else that would cause `os.IsNotExist` to return true)?

Alternatively, an error type in `golang.org/x/tools/godoc/vfs` to signify a file-not-found error in VFS implementations could suffice.

**Comment by beyang** [comment]
Looks like @shurcooL beat me to it: https://go-review.googlesource.com/#/c/19503/1/godoc/vfs/zipfs/zipfs.go

**Comment by shurcooL** [comment]
Yeah, this issue has been resolved in CL 19503 and can be closed now.
