### ISSUE TITLE
cmd/go: slice bounds out of range in test

### ISSUE THREAD

**Issue by jucie** [golang/go#14337]
go version devel +387d5b8 Sat Feb 13 17:33:22 2016 +0000 windows/amd64

It builds fine, but I got an error during test.

`##### Testing packages.
. . .
ok      math/cmplx      0.609s
ok      math/rand       0.350s
ok      mime    2.359s
ok      mime/multipart  5.000s
ok      mime/quotedprintable    2.704s
panic: runtime error: slice bounds out of range

goroutine 14 [running]:
syscall.createEnvBlock(0xc082043400, 0x55, 0x68, 0xc082a0a1f0)
        C:/go/src/syscall/exec_windows.go:115 +0x5b3
syscall.StartProcess(0xc082365180, 0x4c, 0xc0829e5aa0, 0x3, 0x3, 

0xc082c136d0, 0x0, 0x0, 0x0, 0x0)
        C:/go/src/syscall/exec_windows.go:326 +0x8b1
os.startProcess(0xc082365180, 0x4c, 0xc0829e5aa0, 0x3, 0x3, 0xc082c13928, 

0x9d2e20, 0x0, 0x0)
        C:/go/src/os/exec_posix.go:45 +0x345
os.StartProcess(0xc082365180, 0x4c, 0xc0829e5aa0, 0x3, 0x3, 0xc082c13928, 

0x0, 0x0, 0x0)
        C:/go/src/os/doc.go:28 +0x70
os/exec.(*Cmd).Start(0xc082cd8b40, 0x0, 0x0)
        C:/go/src/os/exec/exec.go:332 +0x87e
main.(*builder).runTest(0xc0820eefc0, 0xc0829765b0, 0x0, 0x0)
        C:/go/src/cmd/go/test.go:1107 +0xa2b
main.(*builder).do.func1(0xc0829765b0)
        C:/go/src/cmd/go/build.go:1257 +0x3b9
main.(*builder).do.func2(0xc082abe710, 0xc0820eefc0, 0xc082740ea0)
        C:/go/src/cmd/go/build.go:1314 +0x15d
created by main.(*builder).do
        C:/go/src/cmd/go/build.go:1320 +0x3a5
2016/02/15 15:59:10 Failed: exit status 2
`
It happened only once. I tried to reproduce, to no avail. Next build was fine

**Comment by ianlancetaylor** [comment]
There should have been a bit more to the output that you did not include.  Which package's tests failed?

**Comment by jucie** [comment]
This is the full output from my terminal session:
[goIssue14377.txt](https://github.com/golang/go/files/132224/goIssue14377.txt)
panic is at line 407.
When I saw the error I opened vi to see the offending source line.
Right after, I inspected my environment variables then I tried to find a script to run tests only. Couldn't find.
Then I tried to build again (by running all.bat) and this time build & test succeeded.

**Comment by ianlancetaylor** [comment]
Thanks for the full log.

I think I see an unlikely race condition.  In cmd/go, each test sets `cmd.Env` to the result of envForDir(cmd.Dir,`envForDir(cmd.Dir, origEnv)`.  The `envForDir` function calls `mergeEnvLists`, which appends to its second argument.  Multiple tests are run in parallel.  This means that there is a race condition changing the environment used to run the tests.  On Windows, the environment is converted into a block of NUL-terminated strings by looping over the environment slice twice.  A very precisely timed race could cause the environment slice to change between the two loops, which could cause this error.

I build a version of cmd/go using -race (`go build -race -o gorace cmd/go`) and then ran `gorace test std`.  I got this, which is the race I am describing.

    ==================
    WARNING: DATA RACE
    Read by goroutine 14:
      main.mergeEnvLists()
          /home/iant/go/src/cmd/go/main.go:461 +0x1cc
      main.envForDir()
          /home/iant/go/src/cmd/go/main.go:452 +0x131
      main.(*builder).runTest()
          /home/iant/go/src/cmd/go/test.go:1077 +0x82b
      main.(*builder).do.func1()
          /home/iant/go/src/cmd/go/build.go:1257 +0x56f
      main.(*builder).do.func2()
          /home/iant/go/src/cmd/go/build.go:1314 +0x181
    
    Previous write by goroutine 13:
      main.mergeEnvLists()
          /home/iant/go/src/cmd/go/main.go:463 +0x2aa
      main.envForDir()
          /home/iant/go/src/cmd/go/main.go:452 +0x131
      main.(*builder).runTest()
          /home/iant/go/src/cmd/go/test.go:1077 +0x82b
      main.(*builder).do.func1()
          /home/iant/go/src/cmd/go/build.go:1257 +0x56f
      main.(*builder).do.func2()
          /home/iant/go/src/cmd/go/build.go:1314 +0x181
    
    Goroutine 14 (running) created at:
      main.(*builder).do()
          /home/iant/go/src/cmd/go/build.go:1320 +0x68e
      main.runTest()
          /home/iant/go/src/cmd/go/test.go:595 +0x33f3
      main.main()
          /home/iant/go/src/cmd/go/main.go:181 +0xa38
    
    Goroutine 13 (running) created at:
      main.(*builder).do()
          /home/iant/go/src/cmd/go/build.go:1320 +0x68e
      main.runTest()
          /home/iant/go/src/cmd/go/test.go:595 +0x33f3
      main.main()
          /home/iant/go/src/cmd/go/main.go:181 +0xa38
    ==================
