### ISSUE TITLE
1.6 will not compile

### ISSUE THREAD

**Issue by EricLagergren** [golang/go#14338]
Compilation of branch release-branch.go1.6 *and* tip both fail with this:

```
##### Building go_bootstrap for host, linux/amd64.
... successful building up until this point...
cmd/pprof/internal/tempfile
cmd/trace
cmd/vet/internal/whitelist
cmd/pprof/internal/plugin
cmd/pprof/internal/symbolz
cmd/vet
cmd/yacc
cmd/pprof/internal/report
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/pprof

unknown shorthand flag: 'f' in -f

Usage: rm [OPTION]... FILE...
Remove (unlink) the FILE(s).

  -f, --force           ignore nonexistent files and arguments, never prompt
  -i                    prompt before every removal
  -I                    prompt once before removing more than three files, or
                          when removing recursively; less intrusive than -i,
                          while still giving protection against most mistakes
      --interactive[=WHEN]  prompt according to WHEN: never, once (-I), or
                          always (-i); without WHEN, prompt always
      --one-file-system  when removing a hierarchy recursively, skip any
                          directory that is on a file system different from
                          that of the corresponding command line argument
      --no-preserve-root  do not treat '/' specially
      --preserve-root   do not remove '/' (default)
  -r, -R, --recursive   remove directories and their contents recursively
  -d, --dir             remove empty directories
  -v, --verbose         explain what is being done
      --help     display this help and exit
      --version  output version information and exit

By default, rm does not remove directories.  Use the --recursive (-r or -R)
option to remove each listed directory, too, along with all of its contents.

To remove a file whose name starts with a '-', for example '-foo',
use one of these commands:
  rm -- -foo

  rm ./-foo

Note that if you use rm to remove a file, it might be possible to recover
some of its contents, given sufficient expertise and/or time.  For greater
assurance that the contents are truly unrecoverable, consider using shred.
```

Also, `GOROOT_BOOTSTRAP=/usr/lib/go` and `go version go1.5.3 linux/amd64`

**Comment by minux** [comment]
Do you have some kind of wrapper around rm?

I don't think the error message "unknown shorthand flag: 'f' in -f"
is emitted by rm and rm clearly supports -f as explained by the
help message.

You can try sh -x make.bash to find the offending command
invocation. it seems to be "rm -f
$GOROOT/pkg/tool/$GOOS_$GOARCH/go_bootstrap",
but I didn't see anything wrong with that command.

**Comment by EricLagergren** [comment]
> Do you have some kind of wrapper around rm?

Not that I'm aware of, @minux.

The offending line is:

`+ rm -f /tmp/go/pkg/tool/linux_amd64/go_bootstrap`

```
$ which rm
/usr/local/bin/rm
$ rm --version
rm (GNU coreutils) 8.24.104-ad9d
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Rubin, David MacKenzie, Richard M. Stallman,
and Jim Meyering.
```

**Comment by minux** [comment]
Have you tried to manually execute that command?

And why is your rm in /usr/local/bin instead of /bin?

**Comment by EricLagergren** [comment]
Manually executing the command works fine.

For whatever reason I have GNU coreutils 8.24 inside /usr/local/bin, yet 8.25 inside /usr/bin.

Even after blasting away /usr/local/bin (it only contained the outdated coreutils) the build still fails.

**Comment by minux** [comment]
I don't understand, something is wrong with your environment.
You might to modify make.bash to add more debugging prints
(like "type rm"), or try use an absolute path in that rm command
and see if it still fails.

Go 1.4 and earlier versions also have that rm command.

**Comment by dominikh** [comment]
It should be noted that GNU rm produces different errors for unknown flags:

```
rm: invalid option -- 'X'
Try 'rm --help' for more information.
```

And no automatic invocation of `--help` happens. The primary reference to `unknown shorthand flag: 'f' in -f` I could find was https://github.com/ogier/pflag/blob/master/flag.go#L530 and OpenShift/Kubernetes related things.

**Comment by EricLagergren** [comment]
Me neither. 1.5.x have all built fine. Previous 1.4.x, 1.3.x, etc. releases have built fine too.

Since you suggested debugging make.bash, I noticed this:

```
+ which rm
/home/eric/gopath/bin/rm
+ /usr/bin/rm -f /tmp/go/pkg/tool/linux_amd64/go_bootstrap
```

/usr/bin comes before $GOPATH/bin inside $PATH, and both commands (type and which) both find the proper `rm` command outside of running make.bash.

Does Go's building process fiddle with this at all?

**Comment by minux** [comment]
I don't think Go build scripts fiddle with $PATH.
You can try printing $PATH inside the script too.

**Comment by EricLagergren** [comment]
I'll take a look at it, since it is kinda confusing why $GOPATH/bin would take precedence over /usr/bin *only* while running make.bash.

But since the issue is resolved I guess this issue is closed. Thanks for your help, @minux
