### ISSUE TITLE
Suggestion: use the system pager to display `go help` topics

### ISSUE THREAD

**Issue by Trevoke** [golang/go#14336]
I'm brand-new to Golang.

I'm using golang 1.5.1 on Ubuntu, on a Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz.

I typed `go help gopath`.

I expected to see the beginning of the help at the top of the screen, much like a man page would.

Instead, I saw "when the vendor experiment is enabled, ..."

My suggestion is to use whatever the system pager is to output that information; it knows what to do. I have no idea what to do for Windows, though. Sorry.

**Comment by minux** [comment]
I can think no other software that does this for their command
help messages.

Why not pipe through a pager by yourself?

**Comment by bradfitz** [comment]
Git does that magic if it detects output is a terminal.

People are used to that now. I admit I kinda like it too.

**Comment by minux** [comment]
But "git help cmd" just delegates to "man git-cmd", so
for help messages, it is still man that does the pager
magic.

**Comment by dominikh** [comment]
And a plain `git help` doesn't get paged (nor uses man).

**Comment by robpike** [comment]
Scroll bars are a help here too. I don't see the need for stty-driven magic.

**Comment by bradfitz** [comment]
I'm not arguing for this feature, but I do understand people's desire here. If you're in a terminal inside screen or tmux and not using a terminal program that's integrated with screen or tmux, then your scrollbars and in-terminal search are basically useless. But if you're in your pager, you can navigate and search comfortably. git only invokes the pager when the height of the output is greater than the height of the screen, which seems like a reasonable trade-off.

Again, I'm not the advocate for this feature, but it would be kinda nice. I almost never invoke go help or godoc or go doc without piping it into my pager.

**Comment by minux** [comment]
A real technical difficulty is that we don't have
portable api in the standard library to implement
this feature.

I guess we need to finish x/term first, then we
can vendor the portable terminal handling package
and implement a git like feature.

**Comment by robpike** [comment]
Or we could do nothing, which would be the resolution I would prefer. If "go help" scrolls off the screen, it's easy to run "go help | $PAGER" next. It's a slippery slope once you start gluing system tools into the system you're building.

**Comment by Trevoke** [comment]
I realize that I am just Yet Another Rando On Github (YAROG).

The entire reason I opened this issue is because as a brand-new user of the language, the experience broke any past expectations I had from an interaction between the terminal and myself. This should be cause for concern.

My experience reading the output of some of the `go help foo` commands is comparable to reading the nascent help system in a young MUD. Providing a stable textual structure used by each and every `go help foo` command will go a long way in improving the user experience. It would set clear expectations of repeatable behavior. As is, there is literally no way to know where the message began if I don't see the line where I typed the command (or use a pager). This I would consider a usability failure of Golang's terminal-based help system.

@robpike scroll bars are a help? Long-lived terminal window scroll bars will not blink twice at the added vertical length of the output of something like `go help gopath`.

@robpike If our argument deals with "system tools" vs. "system", I'll suggest the following separation:

- Operating System
- Shell
- Adapter Layer
- Golang

If this is an acceptable separation of concerns, then whose responsibility is it to build the adapter? The user? I would argue it is up to Golang to make itself usable. If this is not an acceptable separation of concerns, what is an acceptable separation of concerns?

To address @minux and @dominikh's note  --- Yes, `go help` or `git help`, per the age-old UNIX-like convention, would likely simply output to the terminal. Usually that command is understood to either give you the baby and the bathwater or a breakdown of further instructions for more detailed help. Based on a cursory examination, `go help` seems to fall in the latter category. My expectation is that if you've built a complex help system and you want me to go through your tool, the least you could do is use man pages -- which have worked for decades. Also 'cause if I'm using emacs it means I can use `woman`, but that's a minor concern.

**Comment by kostya-sh** [comment]
The problem with using the system pager by default is that once it is enabled some people will want to disable it (e.g. http://stackoverflow.com/questions/12166295/disable-all-paging-in-git). This will require additional command line options or environment variables and more documentation, not to mention additional effort to implement, test and support this feature.

BTW, `go help` output is available online: https://golang.org/doc/cmd and https://golang.org/cmd/go/

**Comment by ulikunitz** [comment]
On a Unix system the functionality can be achieved by a shell function.

`gh() { go help $1 | more }`

Use `gh gopath` to use it.

For the less command use  `gh() { go help $1 | less -FX }`.

On an Ubuntu system put the function into the .bash_aliases file.

**Comment by Trevoke** [comment]
Alright, it sounds like implementing a pager is just not a good idea. I'll close this issue and open a new one that will discuss the problem I'm running into instead of a suggested solution without knowing everything you all know; this conversation is going backwards.
