### ISSUE TITLE
math:  Poor performance for math.Sqrt on ppc64le/ppc64

### ISSUE THREAD

**Issue by laboger** [golang/go#14349]
The implementation of the Sqrt function is written in Go and performs poorly on ppc64le & ppc64.  For other platforms there are asm implementations.

I have a change to use the asm sqrt instruction to improve the performance on Power.  I will post that change shortly.

**Comment by laboger** [comment]
https://go-review.googlesource.com/#/c/19515/ 

Improved some sqrt testcases by 10X or more.

Further improvement if this was inlined so that the load of the argument and store of the return value could be avoided.

**Comment by mundaym** [comment]
There is an easy to miss hack in cmd/compile/internal/gc/walk.go which inlines the square root function on platforms where it is a single instruction:
```go
if n.Left.Op == ONAME && n.Left.Sym.Name == "Sqrt" && n.Left.Sym.Pkg.Path == "math" {
    switch Thearch.Thechar {
        case '5', '6', '7':
            n.Op = OSQRT
            n.Left = n.List.N
            n.List = nil
            break opswitch
        }
}
```
It sounds like `'9'` should be added to the case statement.

**Comment by laboger** [comment]
Thanks!  I'll try it out.

**Comment by minux** [comment]
You also need to handle gc.OSQRT in optoas in the ppc64
backend.

**Comment by laboger** [comment]
I had to change a few files to get the inlining to work for sqrt but I think it is right now.  Are these additional files something I can add to my original CL or should I create a new one?

**Comment by bradfitz** [comment]
Add to your existing CL.
