### ISSUE TITLE
cmd/dist: go tool dist banner: incorrectly reported gobin value

### ISSUE THREAD

**Issue by perillo** [golang/go#14341]
The `go tool dist banner` command uses the current value of `GOBIN` from environment, to report the path where go commands where installed during bootstrap.

It should probably report the `gobin` value actually used during bootstrap, instead.

**Comment by minux** [comment]
When will those two GOBIN values be different?

**Comment by perillo** [comment]
On Mon, Feb 15, 2016 at 9:04 PM, Minux Ma <notifications@github.com> wrote:

> When will those two GOBIN values be different?
>

When using go from Archlinux:
```
$go tool dist banner

---
Installed Go for linux/amd64 in /usr/lib/go
Installed commands in /home/manlio/.local/bin
```

However go *core* commands (`go` and `gofmt`) were installed in
`/usr/lib/go/bin`, not in `/home/manlio/.local/bin`.
Probably it is just a misunderstanding about the meaning of *go command*.

**Comment by bradfitz** [comment]
Related? #14340 and its https://go-review.googlesource.com/23255 ("build: unset GOBIN during build")

Or not related?

**Comment by rsc** [comment]
Dup of #14340.
