### ISSUE TITLE
make.bash: GOBIN should be unset

### ISSUE THREAD

**Issue by perillo** [golang/go#14340]
When I try to compile `go` from git repository, the `go dist` command installs the commands in `GOBIN`. However I think this is wrong, since the commands should be installed in `GOROOT_FINAL/bin`, instead.

The `make.bash` script should probably unset `GOBIN`.

**Comment by minux** [comment]
Isn't consistent with the go tool a good thing?

We probably should just document GOBIN in make.bash.

**Comment by perillo** [comment]
On Mon, Feb 15, 2016 at 9:03 PM, Minux Ma <notifications@github.com> wrote:

> Isn't consistent with the go tool a good thing?
>

Well, I have always assumed that core go commands where treated differently
compared to normal user commands.

>
> We probably should just document GOBIN in make.bash.
>

I'm +1 for documenting it, since I was surprised by the current behavior.

**Comment by bradfitz** [comment]
This just bit @robpike too.

**Comment by bradfitz** [comment]
For the record, this was causing @robpike to get random test failures, since cmd/go was being installed to his $GOBIN, and not to $GOROOT/bin. Failures included:

```

--- FAIL: TestCmdGoNoHTTPServer (0.10s)
http_test.go:87: cmd/go unexpectedly links in HTTP server code; found
symbol "net/http.(*Server).Serve" in cmd/go
http_test.go:87: cmd/go unexpectedly links in HTTP server code; found
symbol "net/http.(*ServeMux).ServeHTTP" in cmd/go
http_test.go:87: cmd/go unexpectedly links in HTTP server code; found
symbol "net/http.DefaultServeMux" in cmd/go
FAIL
```

... because the net/http tests (via testenv) were expecting the cmd/go binary under GOROOT.
