### ISSUE TITLE
simple fcgi.Serve(nil, handler) call crashes

### ISSUE THREAD

**Issue by yultide** [golang/go#14347]
% go build foo.go
% ./foo
2016/02/16 04:04:09 file file+net /dev/stdin: getsockopt: socket operation on non-socket

Attached source code
[foo.go.txt](https://github.com/golang/go/files/132391/foo.go.txt)

Happens on OSX & Linux x86_64

**Comment by bradfitz** [comment]
I think this is intended behavior. To use nil, you need to run it in an environment where stdin is the proper type of descriptor. It won't work with bash as its parent process.
