### ISSUE TITLE
Unused "C" import is not a compiler error

### ISSUE THREAD

**Issue by eatonphil** [golang/go#14342]
Acknowledging that the "C" pseudo-package is different than most, I wanted to bring up that this code compiles while it might not be expected to:

```go
package main

import "C"

func main() {}
```

If nothing else, this is an inconsistency and others can decide if it is worth "fixing" (if that decision hasn't already been made).

**Comment by ianlancetaylor** [comment]
This is not an error.  As you say, import "C" is special.  In particular, it's entirely reasonable to import "C" and only //export functions.
