### ISSUE TITLE
A wrong way to insert into a slice?

### ISSUE THREAD

**Issue by ThePiachu** [golang/go#14352]
I was trying to insert an entry into a slice and was puzzled why it wasn't working correctly. Turns out I was appending slices in a wrong order in comparison to the canonical way from SliceTricks. However, I think the behaviour I noticed should be considered a bug. Here is the code:

```
package main

import "fmt"

func main() {
	//My approach
	test:=[]string{"A", "B", "C"}
	test = append(append(test[:1], "1"), test[1:]...)
	fmt.Printf("%v\n", test)
	
	//Canonical approach
	test2:=[]string{"A", "B", "C"}
	test2 = append(test2[:1], append([]string{"1"}, test2[1:]...)...)
	fmt.Printf("%v\n", test2)
}
```

And the results are:

```
[A 1 1 C]
[A 1 B C]
```

As I understand, my approach should behave as follows:

- Take first entry from `test`
- Append to it entry "1", keep that slice in memory
- To the slice in memory, append entries at position 1+ from `test`
- Store the result in `test`

But it looks like something is messed up and the entry "1" is stored into `test` somewhere in-between the two `append`s.

**Comment by cespare** [comment]
This is not a bug. Your code is equivalent to

``` go
test := []string{"A", "B", "C"}
test2 := append(test[:1], "1") // now test is ["A", "1", "C"]
test = append(test2, test[1:]...)
```

See http://play.golang.org/p/-PC4R68dK9.

The reason this happens is that `test[:1]` is a slice of the larger original slice, and when you append to the smaller slice, it reuses that memory.

**Comment by ThePiachu** [comment]
So `append` modifies the underlying array? Then what is the point of being forced to do

```
test := []string{"A", "B", "C"}
test = append(test, "D") //<-this
...
```

If instead we could just do

```
test := []string{"A", "B", "C"}
append(test, "D") //prog.go:7: append(test, "D") evaluated but not used
...
```

?

I was under the impression we always assign the result of `append` to the original slice since the original slice was NOT meant to be modified by append, but I guess I'm wrong...

**Comment by cespare** [comment]
@ThePiachu append allocates a new array and copies if necessary, so that's why the assignment is needed. If there is adequate space in the underlying array (as in your case), it reuses that space.

If you want to continue the discussion, you should head over to golang-nuts or another forum (see https://github.com/golang/go/wiki/Questions). There are also some previous threads about append which may be helpful.

**Comment by ianlancetaylor** [comment]
See also https://golang.org/blog/slices .
