### ISSUE TITLE
cmd/go: improve documentation in go help packages

### ISSUE THREAD

**Issue by perillo** [golang/go#14351]
From `loadPackage` documentation:
`In addition to ordinary import paths,  loadPackage accepts pseudo-paths beginning with cmd/ to denote commands  in the Go command directory, as well as paths to those directories.`.

However this is not documented. `go help package` only says:
`"cmd" expands to the Go repository's commands and their internal libraries.`.

**Comment by mdempsky** [comment]
Aside: This confused me when playing around with gb, where it's typical for end users to use command paths like "cmd/foo". It seems that package go/build is okay with finding "cmd/foo" within GOPATH, but cmd/go rejects "go install cmd/foo" unless it can find cmd/foo within GOROOT.
