### ISSUE TITLE
cmd/doc: a private field may be listed even when only public fields ought to be.

### ISSUE THREAD

**Issue by lootch** [golang/go#14356]
The following artificial example:

	package dummy

	type (
		private struct {
			z *int
		}
		Public struct {
			p *int
		}
		Sample struct {
			*Public
			*private
			x *int
		}
	)

when inspected with "go doc Sample" yields:

	type Sample struct {
		*Public
		*private

		// Has unexported fields.
	}

where *private should not appear at all.

**Comment by robpike** [comment]
In the example, the command to run is "go doc Sample" not "go doc Public".

**Comment by lootch** [comment]
Indeed. Cut-n-paste emulation error. I apologise.

Lucio.

**Comment by lootch** [comment]
I see one can edit one's comments, so I did. I normally find that confusing, I hope I'm not compounding the confusion.

Lucio.
