### ISSUE TITLE
net, x/net/ipv4: Need API for reading both ifIndex and remote socket address for received UDP datagram

### ISSUE THREAD

**Issue by udhos** [golang/go#14362]
Use case is to identify both input interface and remote UDP endpoint (IP-addr,port) for received datagram directed at a local multicast address.

PacketConn.ReadFrom() can provide ControlMessage containing the ifIndex for the input interface.

UDPConn.ReadFromUDP() returns net.UDPAddr with the source socket address (srcIP+srcPort) of the datagram.

However, how to get BOTH informations: input interface ifIndex **AND** remote socket address (srcIPAddr+srcPort) ?

In C, I can read those informations with recvmsg() plus IP_PKTINFO. But it seems such an API is missing from Go.

**Comment by mikioh** [comment]
See https://godoc.org/golang.org/x/net/ipv4#PacketConn.ReadFrom and https://godoc.org/golang.org/x/net/ipv6#PacketConn.ReadFrom. Both methods return a net.Addr, which represents a source address on the received packet.

**Comment by udhos** [comment]
But UDPConn.ReadFromUDP() actully provides the full UDP endpoint address: net.UDPAddr ...
Can I somehow get the remote socket port with .ReadFrom() ?

**Comment by mikioh** [comment]
Please have a look at https://golang.org/ref/spec#Interface_types. The net.Addr is an interface type.

**Comment by udhos** [comment]
Thanks, got one *net.UDPAddr disguised as net.Addr from .ReadFrom(). That did the trick. Sorry for the noise. :-{
