### ISSUE TITLE
doc for filepath.Clean links to an invalid url for Pike's "Lexical File Names in Plan 9 or Getting Dot-Dot Right"

### ISSUE THREAD

**Issue by mohae** [golang/go#14364]
https://golang.org/pkg/path/filepath/#Clean:

    See also Rob Pike, “Lexical File Names in Plan 9 or Getting Dot-Dot Right,” http://plan9.bell-labs.com/sys/doc/lexnames.html

This link comes back with:
```
Object not found

The object /sys/doc/lexnames.html does not exist on this server.
errstr: '/usr/web/sys' i/o on hungup channel
uri host: 
header host: plan9.bell-labs.com
actual host: plan9.bell-labs.com
```

**Comment by bradfitz** [comment]
This was fixed in the past few weeks at tip (https://tip.golang.org/pkg/path/filepath/#Clean) and will be included in Go 1.6 in the next few hours.

**Comment by odeke-em** [comment]
I think the URL we want is https://9p.io/sys/doc/lexnames.html. I can create a CL for this.

**Comment by odeke-em** [comment]
Oh never mind, @bradfitz already got this covered.
