### ISSUE TITLE
cmd/compile: missed constant folding

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#14363]
dev.ssa branch.

The compiler doesn't detect that v24 is a copy of v23 in the following case.
v23 = Or64 <uint64> v19 v22
v24 = Or64 <uint64> v19 v23

The compiler doesn't detect that v24 is a copy of v22 in the following case.
v23 = Xor64 <uint64> v12 v22
v24 = Xor64 <uint64> v12 v23

Not sure if we care about them or if they can be done (in a more general case) using rewrite rules only.

**Comment by randall77** [comment]
(or x (or x y)) -> (or x y) seems like a simple rewrite rule to capture this case.

In general, I'm not too worried about such cases.  They tend not to happen much in user's code (except maybe generated code?) and the compiler doesn't introduce them as part of other phases.
