### ISSUE TITLE
website: create `issue_template.md` to provide a template for new issues

### ISSUE THREAD

**Issue by dgryski** [golang/go#14365]
Google code had a template for new issues for users to fill in.  GitHub has just added this functionality (as requested in the "dear-github" letter.)

A file called `issue_template.md` will be used to pre-populate the new issue form.

**Comment by bradfitz** [comment]
Nice!

/cc @adg

**Comment by myitcv** [comment]
@dgryski - where did you hear/read about this update?

**Comment by dgryski** [comment]
@myitcv https://github.com/dear-github/dear-github/issues/125

**Comment by dgryski** [comment]
Official blog post: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by cespare** [comment]
And feature docs: https://help.github.com/articles/helping-people-contribute-to-your-project/

To do:

- Add `ISSUE_TEMPLATE.md` which lists the sections for an issue
- Add `PULL_REQUEST_TEMPLATE.md` which advises the user not to file a PR and to use Gerrit instead instead (it could contain similar text to #9220)
- Think about whether to move some or all of `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` into a top-level `.github/` directory. These files are github-specific so maybe it would be nice to hide them. On the other hand, I know how @robpike et al feel about dot files :)
