### ISSUE TITLE
doc/install-source.html: Wrong Go version.

### ISSUE THREAD

**Issue by cznic** [golang/go#14371]
in the `#Fetch the repository` section @ `release-branch.go1.6`  it says

> `$ git checkout go1.5.3`

**Comment by minux** [comment]
We really should have an automated way to update this (or have a release
branch)

**Comment by bradfitz** [comment]
Assigning to @adg since he closed #14049 (basically a dup)

/cc @broady

**Comment by bradfitz** [comment]
Another: https://go-review.googlesource.com/#/c/22001
This needs to be automated.

**Comment by adg** [comment]
This isn't fixed immediately on the web site, but it will be fixed when Go 1.6.2 is released next week.
