### ISSUE TITLE
crypto/tls: missing some cipher suite constants

### ISSUE THREAD

**Issue by rutledgechinfeman** [golang/go#14370]
This file has a list of constants for TLS cipher suites:

https://golang.org/src/crypto/tls/cipher_suites.go

The list is incomplete, for example the ChaCha20-Poly1305 ciphers are missing. It would be useful to either (a) complete the list of ciphers and, or (b) document how the list of ciphers is curated.

If (a), there should also be some mechanism to keep the list up-to-date over time.

**Comment by alvarolm** [comment]
+1

**Comment by minux** [comment]
I think the criteria is simply it includes what the package
supports.

**Comment by bradfitz** [comment]
@agl, do you want [somebody else] to document that this is only those supported by the crypto/tls package, or do you want [somebody else] to auto-generate those constants, perhaps with go generate from https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4 ?

**Comment by agl** [comment]
I don't think that we should try to include every constant in that package because of the large number of them. I'll send out a change to document this in a sec.
