### ISSUE TITLE
tour: [Exercise fibonacci closure]

### ISSUE THREAD

**Issue by cicio** [golang/go#14373]
Context: http://127.0.0.1:3999/moretypes/23

The following code will run the Fibonacci sequence without issues up to the number 93. After that it returns negative values for few of the values where the integer is bigger than 93. I have tested the code in Python 2.7.6.

```golang
package main

import "fmt"

// fibonacci is a function that returns
// a function that returns an int.
func fibonacci() func() int {
	fib1, fib2 := 0, 1
	return func() int {
		fib:= fib2+fib1
		fib1 = fib2
		fib2 = fib
		return fib1
	}
}

func main() {
	f := fibonacci()
	for i := 0; i < 100; i++ {
		fmt.Println(f(), i)
	}
}
```

**Comment by minux** [comment]
It's overflowing the int (64-bit when running locally,
32-bit when running on the playground.)

Python does transparent bignum for you, so it
works there.

If you want to have that for Go too, see the
math/big package at https://golang.org/pkg/math/big.

And btw, please ask questions like this on other
mediums, this issue tracker is for bugs and
proposals only. See https://golang.org/wiki/Questions.

**Comment by cicio** [comment]
I am sorry for having posted it in this medium. I thought it might be a bug on the tour.
Thank you
