### ISSUE TITLE
net/http: malformed HTTP status code "client"

### ISSUE THREAD

**Issue by sger** [golang/go#14388]
Hello,

just installed go 1.6 my issue is that i'm trying to send a POST request to apns server and i'm getting this message

malformed HTTP status code "client"

probably trying to send HTTP 1.1 requests instead of HTTP 2.0

any ideas on this issue?

**Comment by ianlancetaylor** [comment]
Show us your code.

Where is the message coming from?  The client or the server?

See the net/http package docs for how to disable HTTP 2.0.

If you just want to ask a question, please don't use the issue tracker.  Please see https://golang.org/wiki/Questions .  Thanks.

**Comment by sger** [comment]
same issue with https://github.com/golang/go/issues/14275 thanks @ianlancetaylor
