### ISSUE TITLE
cmd/compile: [ssa] invalid instruction: 00027

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#14389]
I'm not sure if it's alright to report SSA bugs yet, however using `go version devel +bc1fb32 2016-02-17 16:31:44 +0000 linux/amd64`, I end up with : `<autogenerated>:9: invalid instruction: 00027 ($GOPATH/src/github.com/OneOfOne/xxhash/native/xxhash32_native.go:112) ADDL    $-3688676312, AX`

To reproduce:
``` shell
➜ env GOPATH="/tmp/x" go get -x github.com/OneOfOne/xxhash
➜ env GOPATH="/tmp/x" go test github.com/OneOfOne/xxhash
```

**Comment by randall77** [comment]
Yes, please report bugs.  Thanks for this one.

19740 is an immediate fix, but I think we need something more generic here.  This will almost certainly happen for more than just ADD.

@tzneal

**Comment by randall77** [comment]
Somehow gopherbot didn't close the issue.  Todd's change is in, this should be fixed.
