### ISSUE TITLE
community: let's talk Gitter

### ISSUE THREAD

**Issue by vadimyer** [golang/go#14382]
I've noticed there's no "official" gitter channel for Go, what's more - not even a "general Go room" there. Why is that so? I suggest doing this!

**Comment by mholt** [comment]
There's a Gophers slack: https://gophersinvite.herokuapp.com/

**Comment by ianlancetaylor** [comment]
I don't know what Gitter is.  Assigning to Andrew to see if we want an approved channel there.

**Comment by mholt** [comment]
Personal opinion: Gitter is nice, but everyone already uses IRC or Slack for Go chat. I moved my project from Slack to Gitter because of the lower barrier to entry, but now I kind of regret it, since Gitter is really rough around the edges. I definitely think Slack/IRC is good for now, at least as far as "official" channels go.

**Comment by adg** [comment]
I don't see a compelling reason to create another official chat room. Thanks for the suggestion, though.

**Comment by vadimyer** [comment]
@adg Let me be more specific, probably someone will watch for this little "feature" in the feature.

Personally (and maybe pity for me) I don't know what Slack is, and it's a bit unfamiliar for me. The reason I've suggested this is the fact that Gitter is easy to connect with Github, there're many repos with an "official gitter button".

It's never bad to have more coverage. More ways of communicating. Creating a room and a button doesn't require anything to maintain, but it allows more people to join in and share with the community. The audience there is huge as well. It's just like organizing meet-ups in different locations of world, though they're actually being organized by a variety of people. Well I could create a channel, but it would be like "vadimyer/go" - that's not something people might look for there.

As @mholt mentioned, it might be a "lower level" or something (I don't quite get it why), but it still a community that counts.

P.S. Personally I didn't like Slack, I didn't even know it exists. I knew Go has IRC, and I've born in the IRC era, but eh... Gitter is cool. They have a cool button which anyone can insert. And it was easy to connect to it with only Github account. Moreover, searching for "Go" there returned nothing, people are lazy todays, they probably need more ways of communicating.

But that's only my opinion after all, yeah. Thanks for considering that at least.

**Comment by adg** [comment]
It's just that maintaining such a room requires moderation. We can't just let it be the wild west in there. If there were enough trusted volunteers to run the space in accordance with our [code of conduct](https://golang.org/conduct) then it is something we could consider.
