### ISSUE TITLE
cmd/link, runtime: panic "invalid spdelta" with -ldflags="-linkmode internal"

### ISSUE THREAD

**Issue by mattn** [golang/go#14397]
https://github.com/mattn/go-sqlite3/issues/272

forwarning report of issue. sorry.

**Comment by minux** [comment]
Why is the runtime traceback routine tries to unwind
foreign stacks?

The internal linking mode on windows is really buggy,
perhaps we should just deprecate its support.

**Comment by ToadKing** [comment]
Internal linking is needed on Windows in order for DWARF info to work. If it is going to be deprecated, #10776 should be fixed first.

**Comment by rsc** [comment]
Might be same fix at least as #13568. I never got that the fix for that one to a point where I believed it, so it didn't get checked in. Maybe someone can try that fix here?

**Comment by rsc** [comment]
I doubt there will be a Go 1.6.3, but Go 1.7 will include https://go-review.googlesource.com/18322, which will likely fix this.

**Comment by ToadKing** [comment]
I've tested this on the latest master, and while the "invalid spdelta" warning is fixed the program still fails to run.

**Comment by ianlancetaylor** [comment]
@ToadKing If the invalid spdelta error is gone, please open a new issue for the new problem you are encountering.  Thanks.
