### ISSUE TITLE
x/exp/shiny: screen.Window events does not exist

### ISSUE THREAD

**Issue by Triangle345** [golang/go#14401]
In shiny.go:  https://github.com/golang/mobile/blob/master/app/shiny.go

w.Events line 42 throws an error because Events does not exist in the Window interface : https://github.com/golang/exp/blob/master/shiny/screen/screen.go

> ..\golang.org\x\mobile\app\shiny.go:42: w.Events undefined (type screen.Window has no field or method Events)

This was caught while trying to run the basic mobile example on Windows 10 64 bit.

**Comment by wdsgyj** [comment]
the same error

**Comment by Triangle345** [comment]
however; this did compile fine using the gomobile executable... Wondering maybe it was not meant to be ran stand alone via go run
