### ISSUE TITLE
cmd/get: Go get panic

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#14402]
version `go version go1.6 linux/amd64`
cmd `go get github.com/go-ini/ini`
os `Linux 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Log
`# runtime
/home/meng/go/src/runtime/os2_linux_generic.go:12: _SS_DISABLE redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:8
/home/meng/go/src/runtime/os2_linux_generic.go:13: _NSIG redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:9
/home/meng/go/src/runtime/os2_linux_generic.go:14: _SI_USER redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:10
/home/meng/go/src/runtime/os2_linux_generic.go:15: _SIG_BLOCK redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:11
/home/meng/go/src/runtime/os2_linux_generic.go:16: _SIG_UNBLOCK redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:12
/home/meng/go/src/runtime/os2_linux_generic.go:17: _SIG_SETMASK redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:13
/home/meng/go/src/runtime/os2_linux_generic.go:18: _RLIMIT_AS redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:14
/home/meng/go/src/runtime/os2_linux_generic.go:24: sigset redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:20
/home/meng/go/src/runtime/os2_linux_generic.go:26: rlimit redeclared in this block
        previous declaration at /home/meng/go/src/runtime/os2_linux.go:22
/home/meng/go/src/runtime/panic1.go:11: paniclk redeclared in this block
        previous declaration at /home/meng/go/src/runtime/panic.go:535
/home/meng/go/src/runtime/panic1.go:11: too many errors
`

**Comment by davecheney** [comment]
This is usually caused by having a corrupt Go installation. You should remove any Go installation before installing another, don't simply unpack over the top of an existing one.

Also, _please_ do not set GOROOT, this is the cause of this problem 99% of the time.

**Comment by mengzhuo** [comment]
Sorry, It's our deploy script which `tar xvzf go1.6` into `~/go` which go1.5 already there
Close issue.
