### ISSUE TITLE
Group file permissions are not properly set on OS X 10.11.3

### ISSUE THREAD

**Issue by mikewied** [golang/go#14400]
Please see my test code below. It seems that no matter what I do I am not able to create a file properly with group write permissions. Interestingly though I am able to get them set if I chmod the file after I create it. I suspect there may be a bug in the OpenFile API.

	package main

	import (
		"fmt"
		"os"
	)

	func main() {
		f, err := os.OpenFile("test.tmp", os.O_CREATE|os.O_RDWR, 0660)
		if err != nil {
			fmt.Printf("%v\n", err)
		}

		info, err := f.Stat()
		if err != nil {
			fmt.Printf("%v\n", err)
		}

		fmt.Printf("Permissions: %#o\n", info.Mode())

		f.Chmod(0660)
		if err != nil {
			fmt.Printf("%v\n", err)
		}

		info, err = f.Stat()
		if err != nil {
			fmt.Printf("%v\n", err)
		}

		fmt.Printf("New Permissions: %#o\n", info.Mode())
	}

Mikes-MacBook-Pro:test mikewied$ ./test 
Permissions: 0640
New Permissions: 0660

**Comment by minux** [comment]
What's your umask setting?

files created by os.OpenFile will obey the umask.
I suspect that your umask is 022.

**Comment by mikewied** [comment]
Of course. Thanks for the quick response. Closing this as invalid.
