### ISSUE TITLE
cmd/go: cc1: error: unrecognised debug output level "no-record-gcc-switches"

### ISSUE THREAD

**Issue by rjammala** [golang/go#14414]
I am trying to build at tip on CentOS Linux and it fails with this error.

[rjammalamadaka@localhost src]$uname -a
Linux localhost.localdomain 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[rjammalamadaka@localhost src]$ go version
go version devel +387d5b8 Sat Feb 13 17:33:22 2016 +0000 linux/amd64
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# runtime/cgo
cc1: error: unrecognised debug output level "no-record-gcc-switches"
runtime/debug
runtime/pprof
runtime/trace
internal/trace
go/internal/gccgoimporter
go/internal/gcimporter
testing
math/cmplx
net/internal/socktest
os/signal
internal/testenv
go/importer
runtime/race
testing/iotest
testing/quick
cmd/api
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/compile/internal/big
cmd/internal/gcprog
cmd/cover
cmd/asm/internal/arch
cmd/dist
cmd/asm/internal/asm
cmd/compile/internal/gc
cmd/asm
cmd/doc
cmd/fix
cmd/gofmt
cmd/link/internal/ld
cmd/newlink
cmd/nm
cmd/objdump
cmd/pack
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/pprof/internal/profile
cmd/pprof/internal/svg
cmd/link
cmd/pprof/internal/tempfile
cmd/vet/internal/whitelist
cmd/vet
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/yacc
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/x86
cmd/compile
[rjammalamadaka@localhost src]$

/cc: @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Should be fixed by https://golang.org/cl/19686 .
