### ISSUE TITLE
math/rand: document Rand output compatibility promise

### ISSUE THREAD

**Issue by dsnet** [golang/go#14416]
Using `go1.6`

It seems from [rand/regress_test.go](https://github.com/golang/go/blob/master/src/math/rand/regress_test.go) that there is an explicit test to:
> Test that random number sequences generated by a specific seed do not change from version to version.

The public documentation for [math/rand](https://golang.org/pkg/math/rand/) doesn't really saying anything about this. If there is a hard guarantee for deterministic output of Rand *between* versions of Go, can this be documented?

**Comment by ianlancetaylor** [comment]
I don't think we want that to be a hard guarantee.  There is some discussion in issue #8013.  We don't want to change the sequence gratuitously, but we don't necessarily want to lock ourselves into that exact sequence if there is ever a really good reason to change it.  The test is there to make sure that we don't change the sequence accidentally.
