### ISSUE TITLE
net/http/httputil: permit ReverseProxy to change Host header

### ISSUE THREAD

**Issue by linquize** [golang/go#14413]
net/http/httputil: ReverseProxy
Currently it preserves HTTP request Host header.
However, this may cause problem for some servers complaining Host not match.
I suggest to have a option to change Host header

For example: A reverse proxy
`http://a.com/*` -> `http://192.168.1.123/*`
The client sends HTTP request with header `Host: a.com`
After forwarding, the server expects HTTP request header `Host: 192.168.1.123`, so we need to change it.

In https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go
```
func NewSingleHostReverseProxy(target *url.URL) *ReverseProxy {
    ......
    req.URL.Host = target.Host
    req.Host = target.Host // Add this line to change Host header
    ......
}
```

**Comment by dpiddy** [comment]
Do you have an example that shows the target receives a different `Host` header? As [the docs](https://golang.org/pkg/net/http/#Request) say, `Request.URL.Host` is the server to connect to, `Request.Host` is the value used for the `Host` header.

**Comment by dpiddy** [comment]
I believe this is also specifically tested for in [this test](https://github.com/golang/go/blob/5c5e8d41054940ccf9e1c025bf21c86e85f33bde/src/net/http/httputil/reverseproxy_test.go#L32). Note [the checking](https://github.com/golang/go/blob/5c5e8d41054940ccf9e1c025bf21c86e85f33bde/src/net/http/httputil/reverseproxy_test.go#L51) of `req.Host` in the backend server to verify it stays the same as what was in [the original request](https://github.com/golang/go/blob/5c5e8d41054940ccf9e1c025bf21c86e85f33bde/src/net/http/httputil/reverseproxy_test.go#L76) sent to the proxy.

**Comment by dpiddy** [comment]
Sorry, I misread. If you want to modify the `Host` header in this way you'll probably need to define your own `ReverseProxy` with a custom `Director`.

**Comment by bradfitz** [comment]
Closing due to lack of reply. I think this is probably already sufficiently configurable.
