### ISSUE TITLE
"testing packages" hangs on golang 1.6 osx 10.6

### ISSUE THREAD

**Issue by karstenw** [golang/go#14425]
go version go1.5.3 darwin/amd64
os: OSX 10.6.8

When running all.bash for golang 1.6, go builds but hangs in testing packages. The last printed message is:
`ok  	mime/quotedprintable	0.370s``

After some 10s the cpu usage frops to zero but nothing else happens.

Killing the process after 10 min leaves an invisible "net.test" and a visible "go" process active. With invisible I mean not visible in `top` and `Activity Monitor`.

**Comment by bradfitz** [comment]
Go 1.6 requires OS X 10.7+ and only has downloads for OS X 10.8+, IIRC.
Go 1.5 also requires OS X 10.7+ (see https://golang.org/doc/go1.5)

(Your subject says Go 1.6 but your message says Go 1.5.3.)

In any case, if you can't update your OS X, you'll have to use an older version of Go.
