### ISSUE TITLE
tour: Typo in last sentence.

### ISSUE THREAD

**Issue by PierreVannier** [golang/go#14429]
Context: https://tour.golang.org/methods/8

_Last sentence has a typo :_
In general, all methods on a given type **to** should have either value or pointer receivers, but not a mixture of both. (We'll see why over the next few pages.)

_Should be replaced by :_
In general, all methods on a given type should have either value or pointer receivers, but not a mixture of both. (We'll see why over the next few pages.)

**Comment by mahendrakariya** [comment]
Looks like this is already fixed in the master branch.

**Comment by minux** [comment]
Fixed by https://golang.org/cl/18670.
