### ISSUE TITLE
fmt: maps with NaN keys are not printed correctly

### ISSUE THREAD

**Issue by soniakeys** [golang/go#14427]
go version go1.6 linux/amd64

```
m := map[float64]int{math.NaN(): 3, math.NaN(): 4, .1: 5}
fmt.Println(m)
```

prints `map[0.1:5 NaN:<nil> NaN:<nil>]`.

I would have hoped for `map[0.1:5 NaN:3 NaN:4]` since for example iterating over the map with a `for` loop can retrieve the values 3 and 4.  Perhaps acceptable would be `map[0.1:5 NaN:0 NaN:0]`, consistent with `v, ok := m[math.NaN()]` returning 0, false.  But printing <nil> when nil is not a valid value for the int type is unexpected.

**Comment by martisch** [comment]
This behaviour comes from the reflect package used in fmt to print the map. 
For a NaN float as reflect value, as key to MapIndex the return is: <invalid reflect.Value>

https://play.golang.org/p/oY7vr1WgKk

**Comment by randall77** [comment]
Yes, this is an unfortunate wart that comes from the combination of NaN and the fact that reflect only provides MapKeys, not MapEntries.  MapEntries wouldn't be hard to do, I'd be in favor of doing it.  The question is whether it is worth the extra API just to accommodate NaN keys, something that is probably not advisable anyway.

Also see https://github.com/golang/go/issues/11104
