### ISSUE TITLE
x/oauth2: fix Wunderlist api usage (easy fix)

### ISSUE THREAD

**Issue by bubuntux** [golang/go#14439]
https://github.com/golang/oauth2/pull/172
there is the fix, one line change
Wunderlist api needs to send the client_secret when requesting the token, therefore this change is need it to work with it (https://developer.wunderlist.com/documentation/concepts/authorization)

**Comment by shurcooL** [comment]
FYI, the patch you've sent in golang/oauth2#172 is missing a trailing comma after the string.

**Comment by ianlancetaylor** [comment]
CC @adg
