### ISSUE TITLE
runtime: error returned by os.OpenFile blocks panic handler

### ISSUE THREAD

**Issue by mxk** [golang/go#14432]
go1.6 windows/amd64 on Windows 8

The following program tries to create a new file with os.O_EXCL and panics if the file already exists. When `panic(err)` is called, "panic:" is written to stderr and the program blocks. You have to terminate it with Ctrl-C. If you uncomment err.Error() then you get a normal backtrace and the program exits.

I'm guessing that there is a problem with retrieving the error information in the panic handler, but if done before panicking, then everything works as expected.

```go
package main

import "os"

func main() {
	_, err := os.OpenFile("tmp", os.O_RDWR|os.O_CREATE|os.O_EXCL, 0666)
	if err != nil {
		//err.Error()
		panic(err)
	}
}
```

**Comment by minux** [comment]
Interesting. The program could be further simplified to:

package main

import "syscall"

func main() {
      panic(syscall.Errno(0x50))
}

**Comment by minux** [comment]
The FormatMessageW syscall returns successfully,
but after that the runtime deadlocks in stoplockedm
(line 1682 of runtime/proc.go, `notesleep(&_g_.m.park)`)

**Comment by minux** [comment]
OK, it's because startpanic_m has already called
freezetheworld() (and set sched.gcwaiting to 1).
Calling any cgocall after that point is going to deadlock.
Normally this won't be a problem, but Windows
syscall.Errno.Error() relies on cgocalls to retrieve
the error messages.

I don't know how to fix this problem. Any suggestions?

/cc @aclements

**Comment by aclements** [comment]
Interesting. I wonder if we shouldn't be calling in to user code to format the panic message after freezing the world. Presumably on *any* platform, if an Error method calls cgo or does something nontrivial with goroutines or something, it would deadlock the system in the same way.

We could format all of the panic messages first, then freeze the world, then print them.

**Comment by aclements** [comment]
This also means we're calling in to user code while holding a runtime lock (paniclk). For example, the following results in a "panic: fatal error: schedule: holding locks", which should not be triggerable by user code:

```
package main

import "runtime"

type e struct{}

func (e) Error() string {
	runtime.Gosched()
	return "error"
}

func main() {
	panic(e{})
}
```

**Comment by aclements** [comment]
This one deadlocks on Linux (I haven't looked in to why the Println is necessary):

```
package main

/*
char *geterror() {
	return "error";
}
*/
import "C"
import "fmt"

type e struct{}

func (e) Error() string {
	fmt.Println("Hi!")
	return C.GoString(C.geterror())
}

func main() {
	panic(e{})
}
```

And this one panics with another internal error, "fatal error: stopm holding locks":

```
package main

import "fmt"

type e struct{}

func (e) Error() string {
	fmt.Println("Hi!")
	fmt.Println("Bye!")
	return "x"
}

func main() {
	panic(e{})
}
```
