### ISSUE TITLE
cmd/guru/guru.el

### ISSUE THREAD

**Issue by abourget** [golang/go#14438]
I'm having an issue with the new way `guru.el` hooks in key bindings.

I get:

    Symbol's value as variable is void: go-guru-map

each time I try to load `guru.el` from the latest `master` (https://github.com/golang/tools/commit/b0452eeec4321022e8c7484acba84858c4e418bf that is)

Reverting to the previous `go-mode-map` additions fix the issue.

I'm using go1.6, Emacs 24.3.1 under Ubuntu 14.04.

/cc @alandonovan

**Comment by dominikh** [comment]
https://go-review.googlesource.com/#/c/19749/

**Comment by abourget** [comment]
oh wow, thanks :)

**Comment by abourget** [comment]
that fixes it here.. can I do anything more ? Not sure how to proceed with `go-review` .. would it be useful that I confirm over there too ?

**Comment by dominikh** [comment]
Not really. It's a trivial fix, and someone with contributor rights has to +2 it. What's left for us is to wait :)

**Comment by dominikh** [comment]
This issue has been fixed and can be closed.
