### ISSUE TITLE
tour: clarify Buffered Channels

### ISSUE THREAD

**Issue by RDevet** [golang/go#14442]
Context: http://127.0.0.1:3999/concurrency/3

Please provide a better explanation.  Even after getting it to break I was puzzled.

**Comment by campoy** [comment]
@adg, are you by any chance working on the concurrency section?

**Comment by adg** [comment]
Not right now, no.

**Comment by ALTree** [comment]
Issues with the tour's content should Go in the golang/tour issue tracker. Closing here.
