### ISSUE TITLE
x/mobile/bind: Controling names of generated code

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#14445]
Feature:
Provide a way to control the names of the generated  code- i.e. namespaces, 1st level method names, log tag, etc.

**Comment by hyangah** [comment]
Please discuss the missing features on golang-nuts@ mailing list first.

--

It's not clear what you mean by 'namespaces': If you meant custom Java package path or custom Objective-C name prefix, check the flags listed in gobind -h.

1st level method names:  You are free to modify your API to bind to have desired names.

log tag: The generated code itself doesn't include much logging except the fatal log. For logging from Go side, I think it's possible to allow customization but, not through code generation but through users' Go code.
