### ISSUE TITLE
x/sys/unix: zero-sized field may be removed by go1.5's change.

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#14440]
Currently source code seems to be generated by go <= 1.4.

https://godoc.org/golang.org/x/sys/unix#InotifyEvent

Because of go 1.5's change, we may want to remove zero-size field.

https://golang.org/doc/go1.5#cgo

I don't know this is intentional. If not we need to updated code.
I also want to know which OS version are targeted for x/sys/unix.
Clarifying it somewhere is reasonable for me.

Thank you.

**Comment by ianlancetaylor** [comment]
Thanks for the bug report.

There is no clear documentation for which operating system versions are supported by x/sys/unix.  That would be desirable, but it seems an unrelated issue.  Note that the set of supported versions is distinct from the question of which version is used to generate the files.

**Comment by hirochachacha** [comment]
>> it seems an unrelated issue.

Indeed.

Honestly, I want to post more general question to golang-dev: 
"which version of OS and Go is preferable for code generation?"
I tried to post it, but it failed silently. So I filed a relevant issue instead. Sorry for that.

**Comment by hirochachacha** [comment]
Oops. It seems to that google group has delayed. sorry.

**Comment by prattmic** [comment]
Done in https://go.dev/cl/37943.
