### ISSUE TITLE
cmd/go: go build -v broken

### ISSUE THREAD

**Issue by zephyr** [golang/go#14446]
The verbose flag of go build should “print the names of packages as they are compiled”. But compiling the [hello word example](https://play.golang.org/p/3VsQMI4Rx5) with go version devel 9ad41f6 2016-02-21 16:36:56 +0000 linux/amd64 gives only:

```bash
$ go run -v helloworld.go 
command-line-arguments
Hello, 世界
```

I would expect at least `fmt`, `runtime`, …

**Comment by zephyr** [comment]
Interestingly enough, it does work as expected when cross-compiling to a different architecture:
```bash
$ GOARCH=386 go run -v hello-world.go 
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
math
unicode/utf8
sync
syscall
io
strconv
time
reflect
os
fmt
command-line-arguments
Hello, 世界
```
but still
```bash
$ GOARCH=amd64 go run -v hello-world.go 
command-line-arguments
Hello, 世界
```

**Comment by Thomasdezeeuw** [comment]
I think they are not being compiled, try running with `-a` to force the packages to recompile.

**Comment by zephyr** [comment]
That works—so it was my error. Thank you very much! :)
