### ISSUE TITLE
x/sys/unix: add *at (POSIX.1-2008 conformed) functions on darwin.

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#14458]
OS X 10.10 (IOS 8.0) add list of *at syscalls.
- openat
- renameat
- fchmodat
- fstatat
- mkdirat
- faccessat
- fchownat
- linkat
- readlinkat
- symlinkat
- unlinkat

Currently, only `fchmodat` is exposed.

**Comment by perillo** [comment]
These syscalls are also supported on FreeBSD, and I need them for a project that currently only supports Linux.

**Comment by avg-I** [comment]
I would like to second both requests (macOS / FreeBSD) in this issue.
Other popular BSDs (Net, Open)most likely support the requested system calls as well.

**Comment by calmh** [comment]
Yes. Openat is required, as I understand it, to be able to reliably open a path without following symlinks. Currently this is only possible on Linux, with Go...

**Comment by ianlancetaylor** [comment]
I encourage anyone who wants to fix this to write a patch and submit it following the guidelines at https://golang.org/doc/contribute.html.
