### ISSUE TITLE
x/sys/unix: expose fchmodat(2) on darwin/386, darwin/arm, darwin/arm64.

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#14457]
AFAIK, fchmodat(2) is introduced since OS X 10.10 and  IOS 8.0.

I read the related discussion: 
https://groups.google.com/forum/#!topic/golang-codereviews/Fm_icdtNKe0

I cannot understand why it is restricted to amd64.

**Comment by tklauser** [comment]
At least for darwin/386 it was added in https://golang.org/cl/50450 (golang/sys@c4489faa6e5ab84c0ef40d6ee878f7a030281f0f).

**Comment by bradfitz** [comment]
@tklauser, I take it you're going to mail the CL for arm and arm64? (fix commit message to remove double `add add` first)

**Comment by tklauser** [comment]
@bradfitz Yes, currently working on a CL. Thanks for the hint about commit message.
