### ISSUE TITLE
tour: package not found golang.org/x/tour/reader

### ISSUE THREAD

**Issue by andresrestrepo** [golang/go#14453]
Context: http://127.0.0.1:3999/methods/22

compile329.go:3:8: cannot find package "golang.org/x/tour/reader" in any of:
	/home/andres/Software/go/src/golang.org/x/tour/reader (from $GOROOT)
	/home/andres/Software/go/misc/tour/src/golang.org/x/tour/reader (from $GOPATH)

go version go1.6 linux/amd64
opensuse leap 42.1

**Comment by minux** [comment]
Confirmed that go1.6.linux-amd64.tar.gz lacked the golang.org/x/tour/reader
package.

drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/golang.org/
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
golang.org/x/
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
golang.org/x/tour/
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
golang.org/x/tour/pic/
-rw-r--r-- 0/0             815 2016-02-17 15:35 go/misc/tour/src/
golang.org/x/tour/pic/pic.go
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
golang.org/x/tour/tree/
-rw-r--r-- 0/0             955 2016-02-17 15:35 go/misc/tour/src/
golang.org/x/tour/tree/tree.go
drwxr-xr-x 0/0               0 2016-02-17 15:47 go/misc/tour/src/
golang.org/x/tour/wc/
-rw-r--r-- 0/0            1245 2016-02-17 15:35 go/misc/tour/src/
golang.org/x/tour/wc/wc.go

**Comment by minux** [comment]
Merged into #14184.
