### ISSUE TITLE
x/sys/plan9 is missing constants for the flag parameter of its Mount and Bind funcs

### ISSUE THREAD

**Issue by 9nut** [golang/go#14452]
Constants like MAFTER, MBEFORE, etc. are missing from the package.

**Comment by 0intro** [comment]
Do you want to submit a patch, or do you want I do it for you?

**Comment by 9nut** [comment]
It would be great if you could. I'm not setup to submit patches yet.

**Comment by 0intro** [comment]
I've created [CL 19729](https://golang.org/cl/19729). You may want to register to [go-review](https://go-review.googlesource.com/), so I could CC you next time.
