### ISSUE TITLE
net/http/httputil: NewSingleHostReverseProxy doesn't pass http authentication 

### ISSUE THREAD

**Issue by amulyas** [golang/go#14469]
I am using NewSingleHostReverseProxy its working well for us except it not passing any authentication if I pass the URL with auth its just ignoring auth, is there any way I can work around it

**Comment by mgenov** [comment]
You can write your own transport that wraps the default transport one. 

https://golang.org/src/net/http/httputil/reverseproxy.go?s=564:1486#L34

**Comment by bradfitz** [comment]
Yeah, I think @mgenov's suggestion is your best bet. I don't think we want to modify ReverseProxy at this point to support auth in URLs. In general, auth info in URLs is somewhat gross and deprecated, and I don't think we should be encouraging it.

**Comment by amulyas** [comment]
@bradfitz if I add credentials in header will it work?

**Comment by bradfitz** [comment]
Headers are propagated through the proxy.

**Comment by amulyas** [comment]
thanks @bradfitz
