### ISSUE TITLE
GOPATH entry is relative; must be absolute path: "".

### ISSUE THREAD

**Issue by veeravel** [golang/go#14460]
i set GOPATH in my windows environment variable.
F:\gocode;F:\retesting_go\new_prj;
when run the project it shows GOPATH entry is relative; must be absolute path: "".
i want to create two workspace but it not taken..pls tell me what should i do

**Comment by dominikh** [comment]
Remove the trailing semicolon.

**Comment by veeravel** [comment]
DB_Function.go:6:2: cannot find package "xxx/Common/DB/Mysql/InitializeDB" in any of:
	C:\Go\src\xxx\Common\DB\Mysql\InitializeDB (from $GOROOT)
	F:\gocodeF:\retesting_go\xxx\src\xxx\Common\DB\Mysql\InitializeDB (from $GOPATH)
DB_Function.go:7:2: cannot find package "xxx/Model" in any of:
	C:\Go\src\xxx\Model (from $GOROOT)
	F:\gocodeF:\retesting_go\xxx\src\xxx\Model (from $GOPATH)
DB_Function.go:5:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	C:\Go\src\github.com\go-sql-driver\mysql (from $GOROOT)
	F:\gocodeF:\retesting_go\xxx\src\github.com\go-sql-driver\mysql (from $GOPATH


i got the errors in my cmd

**Comment by minux** [comment]
Please ask questions on the golang-nuts mailing list or
forums. See https://golang.org/wiki/Questions.

The issue tracker is for bug reports and proposals.
Thanks.

**Comment by veeravel** [comment]
thank you
