### ISSUE TITLE
Can i test the android applications using golang?

### ISSUE THREAD

**Issue by veeravel** [golang/go#14463]
Can i test the android applications using golang?
please tell me any frameworks if available?
thank you

**Comment by iamybj** [comment]
yeah, this is the time of mobile internet.
golang team should make golang support mobile app developing as soon as possible.

**Comment by veeravel** [comment]
oh..tahnks iamybj

**Comment by integrii** [comment]
this thread gave me cancer

**Comment by veeravel** [comment]
what??? :P

**Comment by bradfitz** [comment]
Spam comments removed. Please move discussion to a forum. See https://golang.org/wiki/Questions . Thanks.
