### ISSUE TITLE
x/mobile: binary weight too much for mobile

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#14465]
Since the compiled file is statically linked, the binary weight too much (simple SDK script 6mb).
In mobile applications the size of an SDK/application have a very big impact.

**Comment by Thomasdezeeuw** [comment]
I think this is a dup of #6853

**Comment by crawshaw** [comment]
Yes, this is a dup of #6853.

Note also that 1. the .apk produced by gomobile contains several different architectures which can be broken up for smaller distribution sizes to each type of phone, and 2. you can compile with -ldflags=-s to remove the symbol table and DWARF info, making the binary smaller.

**Comment by AlmogBaku** [comment]
@crawshaw I compiled using `-s` flag, but it didn't help much. 6mb for a simple SDK that uses HTTP is way too much for embedding in apps.

In my case- I had no choice but implementing it on swift/java.. but in the future reducing it might help
