### ISSUE TITLE
The biggest 3 things that golang should do first. #14461

### ISSUE THREAD

**Issue by iamybj** [golang/go#14462]
android/ios
bigdata
GUI

I think these 3 things should have the highest priority.
If golang doesn't notice this, it will lost the time.

java is slow, fat and complex, but why java is the top 1 programming language for a dozen years ?
that is java satisfy the requirement of time. Java is lucky and a legend.

If golang wants to be a legend too, it must resolve the requirement of android/ios, bigdata, GUI developing first.

**Comment by integrii** [comment]
![Make it stop](https://media1.giphy.com/media/cqcTjuggnRqIE/200_s.gif)

**Comment by bradfitz** [comment]
Dup of #14461

**Comment by bradfitz** [comment]
(and spam comments removed)

**Comment by bradfitz** [comment]
Let's move any discussion to a forum. See https://golang.org/wiki/Questions
