### ISSUE TITLE
cmd/link: incorrect relocations during external linking on linux/386 with musl libc

### ISSUE THREAD

**Issue by minux** [golang/go#14478]
See https://github.com/golang/go/issues/14476#issuecomment-187554053

Tentatively labeled Go1.6.1, but it probably doesn't meet the line.

**Comment by rsc** [comment]
Is this a tracking bug for the other being in 1.6.1 or a separate bug? If it's a separate bug maybe it can wait until 1.6.3.

**Comment by minux** [comment]
this is a separate bug: external linking doesn't work on linux/386 with
musl libc.
I don't know what's wrong yet....

**Comment by rsc** [comment]
Given there's no fix, it seems like this should be at least investigated for Go 1.7. It won't be in Go 1.6.3 (which probably won't happen).

**Comment by ianlancetaylor** [comment]
This would be nice to fix but it doesn't seem to be happening.  Dropping to 1.8.

**Comment by rsc** [comment]
The relevant part of Minux's comment from #14476:

An externally linked hello world program couldn't even start:
(gdb) r
Starting program: /root/go.git/src/hello

Program received signal SIGSEGV, Segmentation fault.
0xb7f98656 in do_relocs (dso=dso@entry=0xb7ffd660 <app>, rel=0x80000910,
rel_size=145784, stride=2)
    at src/ldso/dynlink.c:407
407 src/ldso/dynlink.c: No such file or directory.
(gdb) bt
#0  0xb7f98656 in do_relocs (dso=dso@entry=0xb7ffd660 <app>,
rel=0x80000910, rel_size=145784,
    stride=2) at src/ldso/dynlink.c:407
#1  0xb7f98ea7 in reloc_all (p=p@entry=0xb7ffd660 <app>) at
src/ldso/dynlink.c:1115
#2  0xb7f9a5e3 in __dls3 (sp=0xbffffd60) at src/ldso/dynlink.c:1598
#3  0xb7f99e5c in __dls2 (base=0xb7f7b000 "\177ELF\001\001\001",
sp=0xbffffd60)
    at src/ldso/dynlink.c:1389
#4  0xb7f97ec5 in _dlstart_c (sp=0xbffffd60, dynv=0xb7ffcef8) at
src/ldso/dlstart.c:147
#5  0xb7f97dbb in _dlstart () from /lib/ld-musl-i386.so.1

Something is wrong with the relocations.

**Comment by rsc** [comment]
This doesn't seem like it is affecting many people. Moving to Go1.8Maybe.

**Comment by ianlancetaylor** [comment]
Is this still a problem?
