### ISSUE TITLE
Slice syntax in documentation wrong

### ISSUE THREAD

**Issue by jarro2783** [golang/go#14477]
The syntax for a slice given in the documentation is wrong.

https://golang.org/ref/spec#Primary_expressions

    Slice          = "[" ( [ Expression ] ":" [ Expression ] ) |
                         ( [ Expression ] ":" Expression ":" Expression )

The inner parens are unnecessary, but the whole alternate inside the [ ] needs parens since sequences have higher precedence than alternatives.

**Comment by griesemer** [comment]
Indeed! Thanks for pointing this out. Amazing how many eyes must have missed this. Fix forthcoming.
