### ISSUE TITLE
tour: [Fix Best Code]

### ISSUE THREAD

**Issue by hifisultonauliya** [golang/go#14484]
Context: https://tour.golang.org/basics/9

Why use int on it: var i, j int = 1, 2
this should work perfectly using var i, j = 1, 2

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by minux** [comment]
I think the type is there so that the user can remove it and
see what will happen.

**Comment by dominikh** [comment]
The text points out that the type can be omitted, and the code sample shows both variants: with and without the type, showing that both are possible. IMO it should stay the way it is.

**Comment by rakyll** [comment]
The section's intent is to explain Go's var declaration. Following section also mentions the shortened form.
