### ISSUE TITLE
build: misc/cgo/fortran fails with ld: library not found for -lgfortran

### ISSUE THREAD

**Issue by josharian** [golang/go#14498]
At tip:

```bash
##### ../misc/cgo/fortran
# _/Volumes/Data/src/go.tip/misc/cgo/fortran
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL	_/Volumes/Data/src/go.tip/misc/cgo/fortran [build failed]
2016/02/24 14:28:34 Failed: exit status 2
```

This is fixable (for me) by setting `LIBRARY_PATH=/usr/local/Cellar/gcc/5.3.0/lib/gcc/5`, but given the length of the discussion at https://github.com/Homebrew/homebrew/issues/8539, I think that I'm not going to be the only person to hit this. It'd be nice if this failed gracefully if libgfortan isn't on the library path.

/cc @kortschak

**Comment by kortschak** [comment]
I have a crude fix for this that I will send tonight.
