### ISSUE TITLE
cmd/vet: shadowed variables check doesn't catch shadowing from short assignment in if statements

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#14494]
For the following example:
```go
package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("Usage: jsonformat.go <filename>")
	}

	byt, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		log.Fatalf("ERROR: Unable to read file %q: %v\n", os.Args[1], err)
	}

	var dat map[string]interface{}

	if err := json.Unmarshal(byt, &dat); err != nil { // this err is not flagged as masking the err in the outer scope, incorrectly
		log.Fatalf("ERROR: Invalid JSON file  '%v': %v\n", os.Args[1], err)
	}

	if output, err := json.MarshalIndent(dat, "", "  "); err != nil { // this err is flagged as masking the err in the outer scope, correctly
		log.Fatalf("ERROR: Unable to indent JSON file: %v\n", os.Args[1])
	} else {
		os.Stdout.Write(append(output, '\n'))
	}
}
```

One the errors is not flagged correctly, even when using `-shadowstrict`. My version of `go tool vet` is at `108746816ddf01ad0c2dbea08a1baef08bc47313`

**Comment by stevekuznetsov** [comment]
Original discussion: https://groups.google.com/forum/#!topic/golang-nuts/uD0wsdeQ-xs

**Comment by ianlancetaylor** [comment]
This is fixed in Go 1.6, though I do not know what fixed it.

**Comment by stevekuznetsov** [comment]
I updated my version of `go vet` with a `go get -u golang.org/x/tool/cmd/vet` today... Should that not have picked up this change?

**Comment by kostya-sh** [comment]
I believe this was fixed by https://github.com/golang/go/commit/3c1712db0bd3aa360ad08d9a8e57f6f9b64df6a4#diff-e83f78900998667ec15c83c5b59ba017

@stevekuznetsov, vet is part of Go tool set since Go 1.5.  golang.org/x/tool/cmd/vet is no longer maintained.

I think  golang.org/x/tool/cmd/vet should be deleted at some point as it creates a lot of confusion.
