### ISSUE TITLE
proposal: Why not provide SetDeadline(time.Duration) instead of SetDeadline(time.Time) ?

### ISSUE THREAD

**Issue by spance** [golang/go#14490]
Why not provide `SetDeadline(time.Duration)` instead of `SetDeadline(time.Time)` ?

The net.Conn object provides `SetDeadline(time.Time)/SetReadDeadline/SetWriteDeadline` to set timeout, but those methods were designed for passing an absolute time to determine timeout duration, it's unnecessary and wasting performance.

for example:
```go
// user code
for{
	conn.SetDeadline(time.Now().Add(time.Second))
	conn.Read(buf)
	....
}
```
In the golang internal, SetDeadline() -> fd.setDeadline() -> setDeadlineImpl(), the setDeadlineImpl is:
```go
// src/net/fd_poll_runtime.go
func setDeadlineImpl(fd *netFD, t time.Time, mode int) error {
	d := runtimeNano() + int64(t.Sub(time.Now()))  // to duration, syscall occurred again
	if t.IsZero() {
		d = 0
	}
	......
}
```
I provide an absolute time then it will be converted to duration in golang internal. Why do such a thing to waste performance?

Why not provide methods like this:
```go
for{
	conn.SetDeadline(time.Second) // use time.Duration directly
	conn.Read(buf)
	....
}
```
or 
```go
conn.SetDeadline(time.Second) // Set once, but it will have an effect until it has been set up again.
for{
	conn.Read(buf)
	....
}
```

**Comment by ianlancetaylor** [comment]
This was discussed extensively in the past and will not be revisited.

The brief summary is that setting a duration is ambiguous when there are multiple packets involved.  Does the deadline apply to the entire read or to each separate communication?

The performance cost of calling time is negligible compared to the other costs involved.

**Comment by spance** [comment]
Sorry, I'm disagree with you.
The consumption of calling time.Now() 2 times(syscall, user once and internal net package once) and time.Add() and time.Sub(), is not negligible. We should not waste cpu cycles on those unnecessary operations, even if that cost is negligible.

How to understand "setting a duration is ambiguous when there are multiple packets involved." ?

The most important is the `runtime_pollSetDeadline()` need a time duration not an absolute time.

**Comment by ianlancetaylor** [comment]
As I said, this decision was discussed and made a long time ago.  See https://golang.org/issue/2723 and https://golang.org/cl/5555048 .

If you want to discuss it further, this issue is not a good place for it.  It should be discussed in a forum; see https://golang.org/wiki/Questions .

**Comment by spance** [comment]
I know it would be unwise to change the current API, and it is impossible.

But, can it be possible that we add new methods (SetTimeout...) to net.Conn in future ?

**Comment by bradfitz** [comment]
As Ian said, if you want to discuss it further, this issue is not a good place for it. It should be discussed in a forum; see https://golang.org/wiki/Questions .
