### ISSUE TITLE
doc: GOOS=android target is not documented

### ISSUE THREAD

**Issue by rakyll** [golang/go#14497]
On https://tip.golang.org/doc/install/source, android/arm is not listed as a valid GOOS/GOARCH combination.

**Comment by mwhudson** [comment]
Would it be possible to generate or check this against the output of go tool dist list? There are at least a few others missing (android/arm64. android/386, plan9/arm, nacl/*)

**Comment by rakyll** [comment]
I am not sure we would like to list all the options the go tool supports such as experimental or unstable ones.
