### ISSUE TITLE
runtime: cgo check ignores type's ptrdata field

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14508]
The cgo check code in cgoCheckTypedBlock in runtime/cgocheck.go, in the case where kindGCProg is not set, ignores the type's ptrdata field.  It assumes that the gcdata field is valid for the entire size of the type.  I think this means that in some cases cgoCheckTypedBlock might mistake a non-pointer value for a pointer, potentially triggering an incorrect panic.

**Comment by rsc** [comment]
No actual failure here. While I certainly believe you, maybe this can wait until it happens and be in Go 1.6.3.

**Comment by broady** [comment]
@ianlancetaylor do we want this in Go 1.6.3? It hasn't been cherry-picked.

**Comment by ianlancetaylor** [comment]
We don't want this in 1.6.3.  Changing the milestone.
