### ISSUE TITLE
runtime: make TestCgoCheckBytes less strict

### ISSUE THREAD

**Issue by randall77** [golang/go#14519]
I just got a "too slow" error from TestCgoCheckBytes.  Any chance we could make this test lest strict?

##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestCgoCheckBytes (0.04s)
	crash_cgo_test.go:178: cgo check too slow: got 32.498982ms, expected at most 24.46407ms
FAIL
FAIL	runtime	31.021s
2016/02/26 03:59:26 Failed: exit status 1
2016/02/26 03:59:26 FAILED

@ianlancetaylor

**Comment by ianlancetaylor** [comment]
Are you synced past 5c096cc092013331022c33c5e3d31228edd17dab?  Seems like you  might not be.

**Comment by randall77** [comment]
SSA last pulled in tip at 7786f9790561ceda98e9883256ed50d26fa136d6, which looks to be 3 days ago now.
