### ISSUE TITLE
syscall, x/sys/unix: Time(), Utime(), Getrlimit() use invalid syscall number on linux/arm

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#14524]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
any

2. What operating system and processor architecture are you using (`go env`)?
linux/arm

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
nothing

4. What did you expect to see?
invalid syscall numbers are not used

5. What did you see instead?
invalid syscall numbers are used

As far as is known, linux/arm sycalls are slightly limited.
Here is the list taken from [kernel header]( http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/arch/arm/include/uapi/asm/unistd.h):

```
/*
 * The following syscalls are obsolete and no longer available for EABI.
 */
#if !defined(__KERNEL__)
#if defined(__ARM_EABI__)
#undef __NR_time
#undef __NR_umount
#undef __NR_stime
#undef __NR_alarm
#undef __NR_utime
#undef __NR_getrlimit
#undef __NR_select
#undef __NR_readdir
#undef __NR_mmap
#undef __NR_socketcall
#undef __NR_syscall
#undef __NR_ipc
#endif
#endif
```

I confirmed `time`, `utime` and `getrlimit` are used, others are not used in both syscall package and x/sys/unix package.

I also suggest such syscall numbers should be removed from these packages on linux/arm. 
(except syscall package? because of compatibility promise)

Thank you.

**Comment by bradfitz** [comment]
Please show a complete program which misbehaves, and the `strace -f ./yourbinary` output when run on `linux/arm`. Thanks.

**Comment by hirochachacha** [comment]
Actually, I found this by just reading source code. I have no accessible `linux/arm` here.
You are right. I should have tried it before filing as a issue. Sorry.
I'll try it later by `QEMU` or something. Thank you for your reply.

**Comment by hirochachacha** [comment]
Input:
```
package main

import (
	"syscall"
)
func main() {
	t := new(syscall.Time_t)

	_, err := syscall.Time(t)
	if err != nil {
		println(err.Error())
	}
}
```

Output:
```
function not implemented
```

As I expected, linux return ENOSYS. is it enough info?

**Comment by hirochachacha** [comment]
For the record, root of the problem is code-generation scripts couldn't recognize `#undef`.
We should fix such scripts and hope nothing changes after re-generation.

**Comment by davecheney** [comment]
@hirochachacha the syscall package is a mismash of incompatible implementations. The go runtime does not use syscall.Time, it uses an implementation of nanotime(2), although that depends on the platform you are calling it on.

If there is a fix that needs to be made, it will be in the x/sys/unix package, the syscall package is closed for modifications.

**Comment by hirochachacha** [comment]
>the syscall package is a mismash of incompatible implementations. The go runtime does not use syscall.Time, it uses an implementation of nanotime(2), although that depends on the platform you are calling it on.

I see. And also runtime's `getrlimit` is implemented by `ugetrlimit`.
Yes, runtime's implementation looks like more sophisticated and well tested than syscall's one to me.

>If there is a fix that needs to be made, it will be in the x/sys/unix package, the syscall package is closed for modifications.

Fair enough.

By the way, do you want to accept such a trivial bug report?
I know you guys work for more important issues everyday.
Maybe you don't want to spare time for trivial one.
Maybe you don't want to see the issue tracker is filled by trivial ones.
I don't want annoy you. That's not my intention.
So when I found a trivial issue, what should I do?

Thank you for responses, anyway.

**Comment by minux** [comment]
Trivial or not, if it's a bug, we need to fix it.

If you think it's trivial, perhaps the best way
is to just send a CL to fix it :)

I think we need to fix x/sys/unix, and fix the syscall
package if the fix is simple. (IIUC, the syscall
package is frozen for non-bugfixes and additions
except adding of new ports, but if the implementation
of some existing functions is wrong, then we'd better
fix it.)

Reopen this issue.

**Comment by hirochachacha** [comment]
Thanks! I'll send a CL.
>and fix the syscall package if the fix is simple.

Yes it's simple. For example, we can implement `Time` by `gettimeofday`, 
`Utime` by `utimes` and `Getrlimit` by `ugetrlimit`.

But corresponding syscall numbers are already declaraed by api/go*.txt. 
(i.e. SYS_TIME, SYS_UMOUNT, etc ...)

How can I treat these?

**Comment by davecheney** [comment]
@hirochachacha in general the `syscall` package exists to support the standard library. If the standard library does not need or use the function (even if it is buggy or not implemented), the preferred way is to fix it in the `x/sys/unix` repository.

**Comment by hirochachacha** [comment]
@davecheney I'm confusing. which should I follow?

**Comment by davecheney** [comment]
@hirochachacha we cannot change any of the public values declared in the syscall package. You may have to declare some private constants instead.

Also, please try to make as small as possible a fix. If the issue is not apparent to callers of this code, ie the rest of the standard library, the recommendation is to fix the issue in the `x/sys/unix` package instead.

**Comment by minux** [comment]
Those SYS_* constants are still correct, it's just they
can't be used by the current kernel, so leave them as
they are. The syscall numbers are currently automatically
generated, so it probably hard to add comments to
those numbers, but I think most people will use existing
functions rather than calling Syscall directly anyway, so
it probably won't affect much.

Just fix the implementation to use the correct syscalls.

For the functions in syscall package, I think if the fix
is simple, we can fix those functions. The syscall package
is to serve the standard library, that's the reason why
we don't extend it anymore, but existing bugs should
still be fixed, IMO.

**Comment by hirochachacha** [comment]
Can you please talk to each other? I want to follow the decision.

**Comment by davecheney** [comment]
I am sorry for the confusion. I will let you and @minux decide what to do.

**Comment by hirochachacha** [comment]
No worries. Thanks! I will follow @minux 's decision here.

**Comment by minux** [comment]
To make my suggestions more concrete:

1. don't change constants in either syscall or x/sys/unix
(my understanding is that the numbers are correct but they
are not implemented by the kernel anymore. please correct
me if I'm wrong.) I'm also open to delete those constants in
x/sys/unix, but we have to keep those in the syscall package.

2. move affected functions from auto-generated zsyscall
file into a linux/arm specific file, and implement them correctly.

3. For x/sys/unix only, consider adding tests for syscalls that
are straightforward to test. For example, we can test time.Now()
and unix.Time agrees with each other. The test should be
generic so that it runs on all linux platforms (not only arm).

**Comment by hirochachacha** [comment]
>1. don't change constants in either syscall or x/sys/unix (my understanding is that the numbers are correct but they are not implemented by the kernel anymore. please correct me if I'm wrong.) I'm also open to delete those constants in x/sys/unix, but we have to keep those in the syscall package.

I investigated it. according to [this](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0483c/BABJCGGE.html),  EABI is supported since 2.6.16.
I downloaded [linux-2.6.16](https://www.kernel.org/pub/linux/kernel/v2.6/).

Here is related source code:

include/asm-arm/unistd.h
```
#define __NR_time			(__NR_SYSCALL_BASE+ 13)

...

#if !defined(CONFIG_AEABI) || defined(CONFIG_OABI_COMPAT)
#define __ARCH_WANT_SYS_TIME
#define __ARCH_WANT_SYS_OLDUMOUNT
#define __ARCH_WANT_SYS_ALARM
#define __ARCH_WANT_SYS_UTIME
#define __ARCH_WANT_SYS_OLD_GETRLIMIT
#define __ARCH_WANT_OLD_READDIR
#define __ARCH_WANT_SYS_SOCKETCALL
#endif
```

kernel/time.c
```
#ifdef __ARCH_WANT_SYS_TIME
 
asmlinkage long sys_time(time_t __user * tloc)
{
...
}
...
#endif /* __ARCH_WANT_SYS_TIME */
```

arch/arm/kernel/calls.S
```
/* 0 */		CALL(sys_restart_syscall)
...
/* 10 */	CALL(sys_unlink)
		CALL(sys_execve_wrapper)
		CALL(sys_chdir)
		CALL(OBSOLETE(sys_time))	/* used by libc4 */
		CALL(sys_mknod)
/* 15 */	CALL(sys_chmod)
...
```

syscall table is defined by calls.S . So syscall numbers are defined, but functions are not.

>2. move affected functions from auto-generated zsyscall file into a linux/arm specific file, and implement them correctly.

I see.

>3. For x/sys/unix only, consider adding tests for syscalls that are straightforward to test. For example, we can test time.Now() and unix.Time agrees with each other. The test should be generic so that it runs on all linux platforms (not only arm).

I guess you mean `time.Unix`. I understand.

Thank you.

**Comment by hirochachacha** [comment]
>I guess you mean `time.Unix`

Sorry, I was wrong. `Unix.Time` is right.

**Comment by hirochachacha** [comment]
>>3. For x/sys/unix only, consider adding tests for syscalls that are straightforward to test. For example, we can test time.Now() and unix.Time agrees with each other. The test should be generic so that it runs on all linux platforms (not only arm).

>I guess you mean time.Unix. I understand.

I'm really sorry. I didn't understand it. what "agrees with" exactly mean?
Is this mean: abs(timeA - timeB) < some value ?

**Comment by minux** [comment]
On Sat, Feb 27, 2016 at 6:24 AM, hirochachacha <notifications@github.com>
wrote:

>
>    1. For x/sys/unix only, consider adding tests for syscalls that are
>    straightforward to test. For example, we can test time.Now() and unix.Time
>    agrees with each other. The test should be generic so that it runs on all
>    linux platforms (not only arm).
>
> I guess you mean time.Unix. I understand.
>
> I'm really sorry. I didn't understand it. what "agrees with" exactly mean?
> Is this mean: abs(timeA - timeB) < some value ?
>
Repeat ten times and see if timeA == timeB at least once?

**Comment by hirochachacha** [comment]
>Repeat ten times and see if timeA == timeB at least once?

Is this preferable to `timeA - timeB < n seconds`? and why?
Maybe both of them use CLOCK_REALTIME, so sometimes it failed? I'm not sure.

**Comment by minux** [comment]
I was talking about the 1-second granularity Time() syscall.

**Comment by hirochachacha** [comment]
I sent a CL for syscall package.
I've rethought about deleting obsolete syscall numbers, and don't want to change it now.
So if the CL is acceptable, then it's OK to close this.

Thank you.

**Comment by hirochachacha** [comment]
The CL wasn't approved. But I suppose no one wants to continue this.
So I close it. 
Thank you for responses.
