### ISSUE TITLE
XML unmarschal returns ERROR for chardata Float64

### ISSUE THREAD

**Issue by Lagy** [golang/go#14526]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Latest

2. What operating system and processor architecture are you using (`go env`)?
OS-Debian, 64bit architecture

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

```
type SomeStruct struct {
	Key       string     `xml:"Key,attr"`
	Value    float64   `xml:",chardata"`
}
```

Input XML
```
    <SomeTag Key="blah">0.1</SomeTag>
    <SomeTag Key="blah">0.2</SomeTag>
    <SomeTag/>
```

4. What did you expect to see?
I expect no strconv.ParseFloat error on <SomeTag/> unmarschaling
Expected filled value: 0.0

5. What did you see instead?
Still see error and deep black hole :)

**Comment by Lagy** [comment]
use string Tuttle

note: I dont like talking with myself

**Comment by minux** [comment]
Could you please show a complete program to show the problem?

**Comment by Lagy** [comment]
sorry. I think I post enaught..just unmarshal XML to some structure float64 always fails

**Comment by Lagy** [comment]
fix Value    float64   `xml:",chardata"` -> Value    string  `xml:",chardata"`
