### ISSUE TITLE
os: Rename("oldDir", "newExistingDir") doesn't work on Windows

### ISSUE THREAD

**Issue by RezaSR** [golang/go#14527]
1. What version of Go are you using (`go version`)?
1.5.3

2. What operating system and processor architecture are you using (`go env`)?
windows - amd64

3. What did you do?
Rename a folder to new name that is already a folder. It works fine on linux-amd64 but cause error on windows-amd64

http://play.golang.org/p/m__tRp4mZh

4. What did you expect to see?
Replacement of newDir on windows as it does on linux.

5. What did you see instead?
Error. Access denied. Even running as administrator!

**Comment by RezaSR** [comment]
Thanks

**Comment by ianlancetaylor** [comment]
Note that on GNU/Linux the os.Rename will only succeed if the destination directory is empty.  If the destination directory has any files it will fail with ENOTEMPTY.  I think we should consider checking for and rejecting rename to an existing directory on non-Windows.

**Comment by alexbrainman** [comment]
@bradfitz, latest change (CL 6140) of windows os.Rename introduced use of MoveFileEx. Our code uses MOVEFILE_REPLACE_EXISTING flag, I guess, to make "overwriting of destination file" work. But according to the doco https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx:
```
MOVEFILE_REPLACE_EXISTING ... This value cannot be used if lpNewFileName or lpExistingFileName names a directory.
``` 
That is why, I guess, MoveFileEx return ERROR_ACCESS_DENIED in that scenario. (Running example above I see MoveFileEx return ERROR_ACCESS_DENIED).

I will let you decide what to do here.

Alex

**Comment by alexbrand** [comment]
@alexbrainman is there anything blocking this? can I be of any help?

**Comment by alexbrainman** [comment]
> is there anything blocking this?

No, not really. Someone needs to come up with solution to this problem. I am not looking at this.

> can I be of any help?

Feel free to propose solution to this.

Alex
