### ISSUE TITLE
cmd/vet: teach vet that putting a large value in an interface makes a copy

### ISSUE THREAD

**Issue by josharian** [golang/go#14529]
```go
package main

import "sync"

type T struct {
	sync.Mutex
	_ [4]byte
}

func main() {
	var t T

	var s T
	s = t

	var e interface{}
	e = t
}
```

```bash
$ go vet x.go
x.go:14: assignment copies lock value to s: main.T
exit status 1
```

vet should also complain about the assignment `e = t`, since it also copies t's value.

**Comment by rogpeppe** [comment]
This would have caught some bugs for us.

**Comment by josharian** [comment]
cc @valyala :)

**Comment by valyala** [comment]
It looks like this is already fixed in #14664 (go tip):

```
go vet 1.go
1.go:14: assignment copies lock value to s: main.T
1.go:17: assignment copies lock value to e: main.T
```

**Comment by valyala** [comment]
Other cases must be checked such as passing lock as function argument accepting `interface{}` or returning lock from function returning `interface{}`

**Comment by valyala** [comment]
Prepared a CL, which expands copylock check to function calls and return values - see https://go-review.googlesource.com/20832 . This catches passing lock into `interface{}`.
