### ISSUE TITLE
x/review/git-codereview: -trybot option not documented

### ISSUE THREAD

**Issue by msiebuhr** [golang/go#14535]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)? - 
   `go version go1.6 darwin/amd64`
2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/.../Source/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
1. What did you do?
   `go codereview mail -h` describes an option, `-trybot`, but neither `go codereview help` nor https://godoc.org/golang.org/x/review/git-codereview describes the option
2. What did you expect to see?
   Something telling me what the `-trybot` option does (esp. if I can use it).
3. What did you see instead?
   Nothing telling me what `-trybot` does.

**Comment by ALTree** [comment]
Fixed by https://go-review.googlesource.com/c/24960/ and https://go-review.googlesource.com/c/41693/
