### ISSUE TITLE
cmd:  incorrect assembly of CMP Rn,$0 on ppc64le/ppc64

### ISSUE THREAD

**Issue by laboger** [golang/go#14532]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go 1.6

2. What operating system and processor architecture are you using (`go env`)?
linux ppc64le

3. What did you do?
I'm working on updating some asm file changes to improve performance on ppc64le.  I see many
files that contain CMP Ra,$0 that generate the wrong ppc64 assembler.   I'm guessing that the contents of r0 is usually 0 and that is allowing these to work by luck.

4. What did you expect to see?
For an ASM like this:
CMP  R3,$0
the code should be
cmpdi r3,0

5. What did you see instead?
cmpd r3,r0

This is from an objdump:

TEXT runtimeÂ·memeqbody(SB),NOSPLIT,$0-0
       ......
        CMPU    R5,$0
   757ac:       40 00 25 7c     cmpld   r5,r0

However if the value is not 0, then it assembles correctly

        CMP     R5,$32      
   757b4:       20 00 25 2c     cmpdi   r5,32

**Comment by ianlancetaylor** [comment]
On PPC r0 always contains 0 by definition (that is, it is not a real register.  I think this is working as intended.

**Comment by minux** [comment]
Yeah, R0 is alwaya 0 in the Go ABI.

**Comment by laboger** [comment]
And what happens when Go code calls C code built by gcc where it is not always 0?  Does it reinitialize it when it returns?

**Comment by mwhudson** [comment]
On 27/02/2016 8:44 am, "laboger" <notifications@github.com> wrote:
>
> And what happens when Go code calls C code built by gcc where it is not
always 0? Does it reinitialize it when it returns?

Yes.

**Comment by laboger** [comment]
Thanks for the responses.

**Comment by peter-bergner** [comment]
ianlancetaylor wrote:
> On PPC r0 always contains 0 by definition (that is, it is not a real register).

To be pedantic, r0 is a real register and can contain non-zero data.  In fact, we use r0 as a scratch register in GCC all the time, as well as when we save/restore the link register in the prologue/epilogue.

That said, there are instructions where the contents of r0 are ignored and the value zero is used instead.  For example, the base register in load and store instructions and addi and addis, etc. but only if r0 is the RA operand.  If r0 isn't reset whenever r0 is used like calling non GO routines (eg, C), or whenever making syscalls (r0 holds the syscall number), then you can't guarantee that r0 is zero.

**Comment by minux** [comment]
Yes. R0 is a real register on ppc64, but Go always keeps it zero.
