### ISSUE TITLE
net/http/httptest: ResponseRecorder accepts post-write headers

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#14531]
1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu 15.10 amd64

3. What did you do?
Add header after calling `WriteHeader` or `Write` on a `httptest.ResponseRecorder`

4. What did you expect to see?
Header not set unless `Trailer` has been set

5. What did you see instead?
Header is set

**Comment by cmarcelo** [comment]
Related to https://github.com/golang/go/issues/8857

**Comment by cmarcelo** [comment]
@bradfitz
