### ISSUE TITLE
io: add test to verify that ReadAt doesn't affect seek offset (for Plan 9 kernel bug)

### ISSUE THREAD

**Issue by 0intro** [golang/go#14534]
Running `go tool nm` on object files doesn't work anymore on Plan 9:

```
% go tool nm file.o
open file.o: unrecognized object file
```

This error is returned by [rd.parseObject](https://github.com/golang/go/blob/c2d3e1123c/src/cmd/internal/goobj/read.go#L475) in goobj.Parse.
It reads the "386 deve" string which doesn't match the expected "go objec" string.
It happens because [objfile.Open](https://github.com/golang/go/blob/c2d3e1123c/src/cmd/internal/objfile/objfile.go#L53) calls [debug/elf.NewFile](https://github.com/golang/go/blob/c2d3e1123c/src/debug/elf/file.go#L228) before, which does a ReadAt of 16 bytes. However, the implementation of [pread](https://9p.io/magic/man2html/2/read) in the Plan 9 kernel contains a bug where it updates the channel offset while it  shouldn't. Hence, the first 16 bytes of the files are already read before calling goobj.Parse.

This is related to #11265

This can be fixed by [fixing the pread system call](http://9legacy.org/9legacy/patch/9-pread-offset.diff) in the Plan 9 kernel.

A workaround is to add `Seek(0, 0)` after calling ReadAt:

```
--- a/src/cmd/internal/objfile/objfile.go
+++ b/src/cmd/internal/objfile/objfile.go
@@ -50,6 +50,10 @@ func Open(name string) (*File, error) {
 		return nil, err
 	}
 	for _, try := range openers {
+		_, err = r.Seek(0, 0)
+		if err != nil {
+			return nil, err
+		}
 		if raw, err := try(r); err == nil {
 			return &File{r, raw}, nil
 		}
```

**Comment by minux** [comment]
Isn't that confirmed to be a Plan 9 kernel bug? I don't think Go needs to
change anything here.

**Comment by 0intro** [comment]
Yes, this is a Plan 9 bug. I've opened this issue so people could find it and figure what to do if they encounter this bug.

**Comment by bradfitz** [comment]
We're not going to change cmd/nm or any of the other million high-level Go programs to work around Plan 9 kernel bugs.

Let's repurpose this bug for several things:

1) verify we have a test in Go's repo to catch this plan9 bug.
2) verify Go's builders are running an updated plan9 kernel with this bug fixed.

**Comment by 0intro** [comment]
Yes, I'll update the builders and write a test once I'll be back in two weeks.

**Comment by 0intro** [comment]
And of course, there was absolutely no intention to change any of the Go tool to work around this bug.
