### ISSUE TITLE
tour: Minor Typo in Page Description

### ISSUE THREAD

**Issue by gatkin** [golang/go#14545]
Context: https://tour.golang.org/methods/8

Minor typo in the last paragraph on the page. I think 
> all methods on a given type to should have either value or pointer receivers

has an extra "to" and should be

> all methods on a given type should have either value or pointer receivers

**Comment by minux** [comment]
This has been fixed. But the latest tour has not been
deployed.

/cc @adg @campoy

**Comment by adg** [comment]
Deployed.
