### ISSUE TITLE
Defer is not run if another goroutine panics

### ISSUE THREAD

**Issue by slava-vishnyakov** [golang/go#14542]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64
(also on linux/amd64 and probably others, did not test on Windows)

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
https://play.golang.org/p/KdHIPSSiaX

4. What did you expect to see?
Defer called

5. What did you see instead?
nothing

This led to a real-life problem where I was running a process via `exec.Command` (which would have been be killed by `defer`), then later another goroutine paniced, `defer` did not run, the service manager restarted the main process and I was stuck with accumulation of infinite number of same programs (that was run via `exec.Command`) running. ( More of context here, if interested, but not necessary http://stackoverflow.com/questions/34095254/panic-in-other-goroutine-not-stopping-child-process  )

**Comment by davecheney** [comment]
I am sorry but this is working as intended, `defer` only runs if the function the defer block is declared in returns. If the panic occurs in another goroutine, defer will not run.

See https://golang.org/ref/spec#Defer_statements

> A "defer" statement invokes a function whose execution is deferred to the moment the surrounding function returns, either because the surrounding function executed a return statement, reached the end of its function body, or because the corresponding goroutine is panicking.

**Comment by slava-vishnyakov** [comment]
Thank you for the explanation.

There a lot of places where unexpected panics could happen. In other languages you could have a global try-catch block in main, which would definitely always run if something bad happens. Frankly I expected the defer-recover in main() to work like that.

Is there another mechanism to recover from such failures or is the only way to deal with it is to add defer-recover into every goroutine?

Thank you for your time!

**Comment by davecheney** [comment]
@slava-vishnyakov we don't use the issue tracker for general discussions. Please ask your question [via another method](golang.org/wiki/Questions)
