### ISSUE TITLE
cmd/go: list template Context is missing GOPATH

### ISSUE THREAD

**Issue by gima** [golang/go#14547]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
> ~~~
> go version go1.6 linux/amd64
> ~~~

2. What operating system and processor architecture are you using (`go env`)?
> ~~~
> GOARCH="amd64"
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> ~~~

3. What did you do?
> **`go list -f '{{ context.GOPATH }}'`**

4. What did you expect to see?
> Something along the lines of `go env | grep GOPATH`

5. What did you see instead?
> Nothing was returned.

### Investigation

I believe this to be the problem:

The `Context` struct for the template is constructed in [context.go#L24](https://github.com/golang/go/blob/3cb870d47b5611465c46c6a6512b7f059584c66f/src/cmd/go/context.go#L24) and assigned in [list.go#L160](https://github.com/golang/go/blob/3cb870d47b5611465c46c6a6512b7f059584c66f/src/cmd/go/list.go#L160), but the field GOPATH doesn't seem to be assigned.

I'm not knownledgeable enough to know if this has some meaning, but it seems like a bug.

**Comment by davecheney** [comment]
Why not use go env GOPATH instead ?

**Comment by gima** [comment]
I have two entries in GOPATH and was trying to see if fmt would give me only the first one, but then I hit this bug.

Already went ahead to wrote the desired GOPATH manually. *(Trying to avoid platform-dependency like piping to sed or some such.)*

**Comment by davecheney** [comment]
Are you trying to determine which GOPATH entry the package was located in ?

**Comment by gima** [comment]
Not quite. I was abusing go fmt to try and obtain a single path from GOPATH, because using $GOPATH without parsing would not work if there were multiple paths in it.

**Comment by davecheney** [comment]
When you say "single GOPATH" do you mean the first element in GOPATH ?

**Comment by gima** [comment]
Yes, the first element of GOPATH.

**Comment by davecheney** [comment]
If you need to do this in Go you can use
https://golang.org/pkg/path/filepath/#SplitList

If you need to do it in shell there are a few options depending on your
requirement.

**Comment by gima** [comment]
Thank you. I know these; I was just, uh.., doing something stupid, probably.
For what it's worth, here's the background: I wanted to install godoc to $GOPATH/bin/godoc instead of go get forcing it in to $GOROOT/bin/godoc.

And thus I worked around it:

~~~
go get -u -d golang.org/x/tools/cmd/godoc
go build -o $GOPATH/bin/godoc golang.org/x/tools/cmd/godoc
~~~

..I couldn't find what in-place-of $GOPATH would make the command the *least* platform-dependent (no grep, no sed, etc., as they wouldn't work in windows).

Really, this is not a big deal, I just reported this template context -problem as there seemed to be a bug in the code. I feel bad to have taken your time and to have bothered you for this long, apologies.

**Comment by davecheney** [comment]
It's no problem. In the future consider asking questions like this [in another forum](golang.org/wiki/Questions).

**Comment by gima** [comment]
<sup>\*beep\*</sup> The original bug still exists. <sub>And you promoted this into a question, not me `>;)` <sub>..sorry..</sub></sub>

**Comment by cespare** [comment]
Someone please reopen and change the title to something like

> cmd/go: list template Context is missing GOPATH

I mailed CL 20010.

@gima FYI, the GOPATH that list will output will have all components listed, so it won't help with your problem.

**Comment by gima** [comment]
> @cespare wrote:
> @gima FYI, the GOPATH that list will output will have all components listed, so it won't help with your problem.

No problem. Just wanted to make sure that this issue got attention and possibly resolved.
