### ISSUE TITLE
cmd/go: native support for *.proto (proto3 dialect) files compiled to gRPC

### ISSUE THREAD

**Issue by weingart** [golang/go#14556]
Considering the out-of-band, extra build things, that need to be done to support even a simple protobuf definition/compilation, is there any benefit in extending the current "go build/install" and compiler to be able to deal with .proto files (specifically proto3, generating gRPC) in a native manner?

Proposal is to have the compiler recognize imports of files that end in .proto, .proto3, and possibly .grpc, and treat them as if they were the generated *.pb.go files.  In other words, the golang code would look something like:

```golang
package main

import (
  "fmt"
  pb "github.com/someuser/somerepo/someproto.proto"
)

//... continue as if "pb" was the import of .../someproto.pb.go
```

Thoughts?

**Comment by minux** [comment]
We already have //go:generate support, and
protobuf/grpc are not the only tools that generate
Go code, we shouldn't special case those and
ignore all the other Go code generators.

**Comment by bradfitz** [comment]
I agree with Minux.

**Comment by weingart** [comment]
I've re-tooled things to use go:generate.  While not quite as nice as completely integrated (needs another explicit "go generate" step), it will do.  :)
