### ISSUE TITLE
The variable 'err' on left side of := is not nil when a return a nil in the method on the right side.

### ISSUE THREAD

**Issue by chance1254** [golang/go#14552]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
Mac OS

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

type Error1 struct {
}

func (e *Error1) Error() string {
	return "This is Error1"
}

type Error2 struct {
}

func (e *Error2) Error() string {
	return "This is Error2"
}

func Test1() (*int, error) {
	eNum := 1
	return &eNum, &Error1{}
}

func Test2() (*int, *Error2) {
	eNum := 2
	return &eNum, nil
}

func main() {

	aNum, err := Test1()
	_, err = Test2()

	fmt.Println(*aNum)

	if err != nil {
		fmt.Println("err is not nil")
	} else {
		fmt.Println("err is nil")
	}
}

4. What did you expect to see?
err is nil

5. What did you see instead?
err is not nil

**Comment by bradfitz** [comment]
This isn't a bug. See: https://golang.org/doc/faq#nil_error and http://research.swtch.com/interfaces

**Comment by chance1254** [comment]
Thanks for your answer.
