### ISSUE TITLE
cmd/cgo: tsan hooks broke linux-amd64-sid builder

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14559]
@josharian notes that https://go-review.googlesource.com/17421 broke the linux-amd64-sid builder:

e.g.
http://build.golang.org/log/cd17e7f7d6e331b31d626105c6abbab6753eccf8

```
##### ../misc/cgo/testsanitizers
skipping msan tests: -fsanitize=memory not supported
FAIL: tsan
FAIL: tsan2
2016/02/28 05:10:58 Failed: exit status 1
2016/02/28 05:10:58 FAILED
```

**Comment by siebenmann** [comment]
This is also broken on x86 Fedora (22 and 23) at the moment. The latest git tip (with the report stderr commit) reports: 

    ##### ../misc/cgo/testsanitizers
    skipping msan tests: clang version 3.7 (older than 3.8) incompatible with linux version 4.3 (4.1 or newer)
    # command-line-arguments
    /usr/bin/ld: cannot find /usr/bin/../lib/clang/3.7.0/lib/linux/libclang_rt.tsan-x86_64.a: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    FAIL: tsan
    # command-line-arguments
    /usr/bin/ld: cannot find /usr/bin/../lib/clang/3.7.0/lib/linux/libclang_rt.tsan-x86_64.a: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    FAIL: tsan2
    2016/02/29 10:55:40 Failed: exit status 1

As far as I can tell, Fedora doesn't build or package libclang_rt.tsan-x86_64.a. It does package gcc versions (as libtsan/libtsan-static), which I didn't have installed until I went looking for them; installing them made no difference in the error here.

**Comment by ianlancetaylor** [comment]
This is working now.
