### ISSUE TITLE
PATH variable not altered by MSI installer

### ISSUE THREAD

**Issue by marnikvde** [golang/go#14555]
The "Getting Started" docs on https://golang.org/doc/install?download=go1.6.windows-amd64.msi#install say "The installer should put the c:\Go\bin directory in your PATH environment variable. You may need to restart any open command prompts for the change to take effect.". However, my PATH variable has not been altered by the installer.

I downloaded the MSI from https://storage.googleapis.com/golang/go1.6.windows-amd64.msi on feb 28th 2016 (SHA256 checksum: 9e185fe7985505e3a65633f5e4db76664607f67f8331f0ce4986ba69b51015b7)

Go info:

go version go1.6 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1=

**Comment by bradfitz** [comment]
@broady, randomly assigning to you. Maybe this is docs. Maybe it's an installer bug.

**Comment by alexbrainman** [comment]
@marnikvde what does
```
echo %PATH%
```
command outputs (if you don't mind)? Thank you.

Alex

**Comment by alexbrainman** [comment]
And the output of:
```
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
```
please. Thank you.

Alex

**Comment by marnikvde** [comment]
%PATH% contains lots of directories, but was not altered to include the Go bin directory, I should have added it to the initial report. I have now been playing with the PATH and am no longer sure what the state was before the changes. This is the PATH now (<...> means is edited):

C:\Program Files (x86)\<...>;C:\Oracle\<...>\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\<...>\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\<...>\bin;C:\Program Files(x86)\Skype\Phone\;C:\Go\bin;;C:\Program Files\Docker Toolbox\;C:\Go\bin

I notice that the C:\Go\bin is listed twice. The last 2 directories are from my personal account PATH, the rest is the system PATH (the double ;; is the delimiter). I added the last dir (C:\Go\bin) manually. I cannot confirm with 100% confidence that the Go bin dir that is now twice in the Path (actually the system PATH ends with the go bin dir) was not there a few days ago, i no longer have the terminal open.

OS info:

OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601

**Comment by ULayGyi** [comment]
Good use.

**Comment by alexbrainman** [comment]
I just tried to install https://storage.googleapis.com/golang/go1.6.windows-amd64.msi on

OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601

and everything works for me as expected. Given that your PATH looks OK now, perhaps, there is some confusion on your part. See https://blogs.msdn.microsoft.com/oldnewthing/20150915-00/?p=91591 for details (quoting Raymond Chen is my pasttime, sorry).

I am not sure there is anything else we can do to help future users.

Alex

**Comment by marnikvde** [comment]
Thanks for the link to the article Alex, it seems like a very plausible explanation for what I have observed. I'm guessing that the installer did its job, and that the environment variables were altered, but that running the command prompt after the install did not pick those changes up yet. I probably (incorrectly) assumed that the env vars were not changed because of that. It would explain why I now have the directory in both the system PATH as my personal PATH.
