### ISSUE TITLE
libgo crashes on arm64

### ISSUE THREAD

**Issue by zhangyichao** [golang/go#14567]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go 1.6
2. What operating system and processor architecture are you using (`go env`)?
   linux and arm64 big-endian
3. What did you do?
   (Use play.golang.org to provide a runnable example, if possible.)
   run docker on arm64 big-endian
4. What did you expect to see?
   run successfully on arm64 big-endian
5. What did you see instead?
   crashes on arm64 big-endian but run successfully on arm64 little-endian

acquirep: p->m=0x4208004500(0) p->status=143006016
fatal error: acquirep: invalid p state
runtime stack:
runtime_dopanic
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:135
runtime_throw
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
acquirep
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2797
stopm
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1466
startlockedm
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1604
schedule
         /usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1854
goexit0
         /usr1/zhangyichao/gcc-newest/libgo/runtime/proc.c:1977
runtime_mstart
         /usr1/zhangyichao/gcc-newest/libgo/runtime/proc.c:1076

goroutine 0 [idle]:
Segmentation fault

use gccgo 6.0 and go 1.6

**Comment by ianlancetaylor** [comment]
Does this happen every time you start docker?

**Comment by zhangyichao** [comment]
yes, every time.  But the fault or call stack maybe different every time. There are maybe 4 or 5 kinds of stack, leads to segfault or dead loop.
But when I use GDB to run the docker, in maybe 100 times, there are one run successfully!
all faults are in proc.c, i checked the registers when segfault, the register's content is illegal but use gdb to print the value of which load in the register is right. the content in register is wrong,  the value of c code is right.
Is there maybe bugs when golang do schedule? what does schedule do, it will save and recover register?

**Comment by ianlancetaylor** [comment]
The stack trace suggests memory corruption.

The most likely cause of memory corruption is a stack overrun.

You could try increasing the size of StackMin in libgo/runtime/proc.c.

Yes, when switching between goroutines, the scheduler will save and restore registers.  This is implemented by calling the C library routines getcontext and setcontext.

**Comment by zhangyichao** [comment]
Here is the crashes.

I will try to increase the size of StackMin.

But why little-endian is fine?

发件人: Ian Lance Taylor [mailto:notifications@github.com]
发送时间: 2016年3月1日 9:30
收件人: golang/go
抄送: Zhangyichao (AB)
主题: Re: [go] libgo crashes on arm64 (#14567)


The stack trace suggests memory corruption.

The most likely cause of memory corruption is a stack overrun.

You could try increasing the size of StackMin in libgo/runtime/proc.c.

Yes, when switching between goroutines, the scheduler will save and restore registers. This is implemented by calling the C library routines getcontext and setcontext.

—
Reply to this email directly or view it on GitHub<https://github.com/golang/go/issues/14567#issuecomment-190481918>.

root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/docker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
acquirep: p->m=0x4208004500(0) p->status=143006016
fatal error: acquirep: invalid p state

runtime stack:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:135
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
acquirep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2797
stopm
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1466
startlockedm
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1604
schedule
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1854
goexit0
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1977
runtime_mstart
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1076

goroutine 0 [idle]:
Segmentation fault






root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/doc
ker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0]

goroutine 30 [running]:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:131
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
sig_panic_leadin
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:249
sig_panic_info_handler
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:283

	:0
runtime_markspan
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2704
MCentral_Grow
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mcentral.c:283
runtime_MCentral_CacheSpan
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mcentral.c:84
runtime_MCache_Refill
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mcache.c:79
runtime_mallocgc
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/malloc.goc:211
__go_convert_interface_2
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-convert-interface.c:110
runtime.ifaceI2I2
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-iface.goc:74
io.copyBuffer
	/usr1/zhangyichao/src/gcc-newest/libgo/go/io/io.go:373
io.Copy
	/usr1/zhangyichao/src/gcc-newest/libgo/go/io/io.go:350
exec.$nested2
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:236
exec.$nested3
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:344
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by os_exec.Start.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:343

goroutine 0 [idle]:
Segmentation fault





root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/doc
ker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4207f6fff8]

goroutine 23 [running]:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:131
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
sig_panic_leadin
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:249
sig_panic_info_handler
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:283

	:0
runtime_MSpan_Sweep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:1734
runtime_sweepone
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:1880
bgsweep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:1831
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by mgc
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2215

goroutine 16 [syscall]:
	goroutine in C code; stack unavailable
created by main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-main.c:54

goroutine 17 [syscall]:
	goroutine in C code; stack unavailable
created by runtime_main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
runfinq
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2512
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by runtime_createfing
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2577

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/signal/signal_unix.go:26

goroutine 24 [chan receive]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
chanrecv
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:299
runtime.chanrecv2
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:384
daemon.$nested27
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:17
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by daemon.setupDumpStackTrap
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:16

goroutine 25 [select]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
selectgo
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:815
github_com_docker_libnetwork.watchLoop.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:411
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by github_com_docker_libnetwork.startWatch.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:425

goroutine 30 [runnable]:
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:232
created by os_exec.Start.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:343
	
	
	
	
	
	root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/doc
ker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
Segmentation fault




root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/doc
ker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0]

runtime stack:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:135
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
sig_panic_leadin
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:249
sig_panic_info_handler
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:283

	:0
retake
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2973
sysmon
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2941
runtime_mstart
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1100

goroutine 16 [syscall]:
	goroutine in C code; stack unavailable
created by main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-main.c:54

goroutine 17 [syscall]:
	goroutine in C code; stack unavailable
created by runtime_main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
runfinq
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2512
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by runtime_createfing
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2577

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/signal/signal_unix.go:26

goroutine 23 [runnable]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
bgsweep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:1833
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by mgc
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2215

goroutine 24 [chan receive]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
chanrecv
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:299
runtime.chanrecv2
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:384
daemon.$nested27
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:17
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by daemon.setupDumpStackTrap
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:16

goroutine 25 [select]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
selectgo
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:815
github_com_docker_libnetwork.watchLoop.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:411
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by github_com_docker_libnetwork.startWatch.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:425
fatal error: unexpected signal during runtime execution

goroutine 16 [syscall]:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:131
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
sig_panic_leadin
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:249
sig_panic_info_handler
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:283

	:0
exitsyscallfast
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2153
syscall.Exitsyscall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2104
syscall.readlen
	/usr1/zhangyichao/obj/build-gcc-final/aarch64_be-linux-gnu/libgo/libcalls.go:864
syscall.forkExec
	/usr1/zhangyichao/src/gcc-newest/libgo/go/syscall/exec_unix.go:253
syscall.StartProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/syscall/exec_unix.go:291
os.startProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec_posix.go:45
os.StartProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/doc.go:28
os_exec.Start.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:327
os_exec.Run.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:259
os_exec.CombinedOutput.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:453
iptables.raw
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:345
github_com_docker_libnetwork_iptables.Raw
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:329
github_com_docker_libnetwork_iptables.Remove.pN47_github_com_docker_libnetwork_iptables.ChainInfo
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:292
bridge.removeIPChains
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ip_tables.go:334
github_com_docker_libnetwork_drivers_bridge.configure.pN50_github_com_docker_libnetwork_drivers_bridge.driver
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:382
github_com_docker_libnetwork_drivers_bridge.Init
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:141
libnetwork.initDrivers
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers.go:20
github_com_docker_libnetwork.New
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/controller.go:190
github_com_docker_docker_daemon.initNetworkController.pN38_github_com_docker_docker_daemon.Daemon
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:550
github_com_docker_docker_daemon.NewDaemon
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/daemon.go:773
main.CmdDaemon.pN14_main.DaemonCli
	/usr1/zhangyichao/docker/docker-master/docker/daemon.go:266

	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/sysv.S:113
ffi_call_int
	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/ffi.c:702
reflect.call
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-reflect-call.c:225
reflect.call.N13_reflect.Value
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/value.go:450
reflect.CallSlice.N13_reflect.Value
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/value.go:313
reflect.call.pN20_reflect.makeFuncImpl
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc.go:149
reflect.FFICallbackGo
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc_ffi.go:39
ffi_callback
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc_ffi_c.c:64
ffi_closure_SYSV_inner
	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/ffi.c:1149

	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/sysv.S:270
github_com_docker_docker_cli.Run.pN32_github_com_docker_docker_cli.Cli
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/cli/cli.go:89
main.main
	/usr1/zhangyichao/docker/docker-master/docker/docker.go:63
runtime_main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:626
created by main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-main.c:54
fatal error: runtime_lock: lock count

goroutine 16 [syscall]:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:131
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
runtime_lock
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/lock_futex.c:41
runtime_allocmcache
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mcache.c:26
runtime_startpanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:83
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:191
runtime_unlock
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/lock_futex.c:101
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:142
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
sig_panic_leadin
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:249
sig_panic_info_handler
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-signal.c:283

	:0
exitsyscallfast
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2153
syscall.Exitsyscall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2104
syscall.readlen
	/usr1/zhangyichao/obj/build-gcc-final/aarch64_be-linux-gnu/libgo/libcalls.go:864
syscall.forkExec
	/usr1/zhangyichao/src/gcc-newest/libgo/go/syscall/exec_unix.go:253
syscall.StartProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/syscall/exec_unix.go:291
os.startProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec_posix.go:45
os.StartProcess
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/doc.go:28
os_exec.Start.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:327
os_exec.Run.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:259
os_exec.CombinedOutput.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:453
iptables.raw
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:345
github_com_docker_libnetwork_iptables.Raw
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:329
github_com_docker_libnetwork_iptables.Remove.pN47_github_com_docker_libnetwork_iptables.ChainInfo
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/iptables/iptables.go:292
bridge.removeIPChains
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_ip_tables.go:334
github_com_docker_libnetwork_drivers_bridge.configure.pN50_github_com_docker_libnetwork_drivers_bridge.driver
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:382
github_com_docker_libnetwork_drivers_bridge.Init
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:141
libnetwork.initDrivers
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/drivers.go:20
github_com_docker_libnetwork.New
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/controller.go:190
github_com_docker_docker_daemon.initNetworkController.pN38_github_com_docker_docker_daemon.Daemon
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:550
github_com_docker_docker_daemon.NewDaemon
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/daemon.go:773
main.CmdDaemon.pN14_main.DaemonCli
	/usr1/zhangyichao/docker/docker-master/docker/daemon.go:266

	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/sysv.S:113
ffi_call_int
	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/ffi.c:702
reflect.call
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-reflect-call.c:225
reflect.call.N13_reflect.Value
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/value.go:450
reflect.CallSlice.N13_reflect.Value
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/value.go:313
reflect.call.pN20_reflect.makeFuncImpl
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc.go:149
reflect.FFICallbackGo
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc_ffi.go:39
ffi_callback
	/usr1/zhangyichao/src/gcc-newest/libgo/go/reflect/makefunc_ffi_c.c:64
ffi_closure_SYSV_inner
	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/ffi.c:1149

	/usr1/zhangyichao/src/gcc-newest/libffi/src/aarch64/sysv.S:270
github_com_docker_docker_cli.Run.pN32_github_com_docker_docker_cli.Cli
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/cli/cli.go:89
main.main
	/usr1/zhangyichao/docker/docker-master/docker/docker.go:63
runtime_main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:626
created by main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-main.c:54
	ËÀÑ­»·
	
	
	
	

	
	
root@Hi1382/# docker-1.11.0-dev daemon -p /tmp/run/docker.pid -s vfs -g /tmp/doc
ker -H 127.0.0.1:1234
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
fatal error: releasep: invalid arg

runtime stack:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:135
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
releasep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2812
findrunnable
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1722
schedule
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1847
goexit0
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1977
runtime_mstart
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1076

goroutine 16 [syscall]:
	goroutine in C code; stack unavailable
created by main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/go-main.c:54

goroutine 17 [syscall]:
	goroutine in C code; stack unavailable
created by runtime_main
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
runfinq
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2512
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by runtime_createfing
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2577

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/signal/signal_unix.go:26

goroutine 23 [runnable]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
bgsweep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:1833
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by mgc
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/mgc0.c:2215

goroutine 24 [chan receive]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
chanrecv
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:299
runtime.chanrecv2
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:384
daemon.$nested27
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:17
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by daemon.setupDumpStackTrap
	/usr1/zhangyichao/docker/docker-master/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:16

goroutine 25 [select]:
runtime_mcall
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:295
selectgo
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/chan.goc:815
github_com_docker_libnetwork.watchLoop.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:411
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:235
created by github_com_docker_libnetwork.startWatch.pN39_github_com_docker_libnetwork.controller
	/usr1/zhangyichao/docker/docker-master/vendor/src/github.com/docker/libnetwork/store.go:425

goroutine 30 [runnable]:
kickoff
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:232
created by os_exec.Start.pN11_os_exec.Cmd
	/usr1/zhangyichao/src/gcc-newest/libgo/go/os/exec/exec.go:343

**Comment by ianlancetaylor** [comment]
I have no idea why big- and little- endian would be different.

**Comment by zhangyichao** [comment]
does libgo have been used on complex programs on arm64 big-endian?  does any other arm64 big-endian program with golang run all fine?

**Comment by mwhudson** [comment]
We (canonical) have used gccgo a fair amount on arm64 little endian but not
at all big endian. You could maybe ask on the linaro-toolchain list.

**Comment by zhangyichao** [comment]
do you know when will go compiler(not gccgo) support arm64 big-endian?   is it under developing?

**Comment by mwhudson** [comment]
I am not aware of any work being done on that.

**Comment by zhangyichao** [comment]
another information: all segfaults are caused by the illegal content of rigister x0, but what x0 means in c code is right, which means x0 was modified by something.  is it maybe related to setcontext and getcontext functions?
but i use the newest glibc2.23, and have no effective.

**Comment by minux** [comment]
gc support for arm64be shouldn't be hard if we could get a builder for it.

But I'm curious, why use big endian arm64?

**Comment by ianlancetaylor** [comment]
Is still a problem with the current sources?

**Comment by andybons** [comment]
Ping. Is this still a problem with the current sources?
