### ISSUE TITLE
net/http: TimeoutHandler timing out instantly

### ISSUE THREAD

**Issue by dim** [golang/go#14568]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
http://play.golang.org/p/K9IgiTNaFk

4. What did you expect to see?
`204 No content`

5. What did you see instead?
`503 Service Unavailable`

It looks like the timer of the timoutHandler is created when the handler is wrapped in https://github.com/golang/go/blob/fdd0179bb1fdd70d405929b78c7d2fb6b61369b0/src/net/http/server.go#L2312. By the time the request is actually made, `timer.C` will have already triggered.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

This may be a documentation issue rather than  a bug.  I'm not sure.

**Comment by cmarcelo** [comment]
Looks like a bug to me.

@bradfitz https://go-review.googlesource.com/#/c/20046/

**Comment by cmarcelo** [comment]
@bradfitz ping
