### ISSUE TITLE
How to execute `go test ./...` skipped files in `vendor` directory

### ISSUE THREAD

**Issue by ckeyer** [golang/go#14562]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.6 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
.......
```

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

4. What did you expect to see?

5. What did you see instead?

**Comment by minux** [comment]
Merged into #14417.
