### ISSUE TITLE
After a multi-line comment tags doesn't work

### ISSUE THREAD

**Issue by ckeyer** [golang/go#14560]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.6 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
.......
```

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

```
$ cat main.go
package main

func main() {
	Print()
}
```

```
$ cat p_aa.go
/**
 * balabala
 **/

// +build aa

package main

import (
	"fmt"
)

func Print() {
	fmt.Println("from package p.Add; aaaaaaaaa")
}
```

```
$ cat p_bb.go
/**
 * balabala
 **/

// +build !aa

package main

import (
	"fmt"
)

func Print() {
	fmt.Println("from package p.Add; bbbbbbbbb")
}
```

4. What did you expect to see?
```
$ go build --tags aa
$ ./test
from package p.Add; aaaaaaaaa
```

5. What did you see instead?

```
$ go build --tags aa
# fx
./p_bb.go:13: Print redeclared in this block
	previous declaration at ./p_aa.go:13
```

**Comment by ckeyer** [comment]
But if use the one-line comments,it work. 
```
$ cat p_bb.go
//
// balabala
//

// +build !aa

package main

import (
    "fmt"
)

func Print() {
    fmt.Println("from package p.Add; bbbbbbbbb")
}
```

**Comment by minux** [comment]
This is working as intended and documented.

https://golang.org/pkg/go/build/#hdr-Build_Constraints

A build constraint, also known as a build tag, is a line comment that begins
// +build
that lists the conditions under which a file should be included in the
package.
Constraints may appear in any kind of source file (not just Go), but they
must
appear near the top of the file, preceded only by blank lines and other
*line comments*. These rules mean that in Go files a build constraint must
appear before the package clause.
