### ISSUE TITLE
cmd/compile: internal compiler error: large ONEW with EscNone: new()

### ISSUE THREAD

**Issue by bobziuchkovski** [golang/go#14574]
### What version of Go are you using (`go version`)?

Go Playground

### What operating system and processor architecture are you using (`go env`)?

Go Playground

### What did you do?

See https://play.golang.org/p/beWgN_LRyJ -- it fails to compile with `internal compiler error: large ONEW with EscNone: new()`.  The code itself doesn't make a lot of sense, building a buffer and not using it, but it should still compile.

### What did you expect to see?

The program should run on the Go Playground.

### What did you see instead?

The program fails to compile with `internal compiler error: large ONEW with EscNone: new()`

### Other

If I assign the buffer to a variable and invoke a method, the code compiles and runs.  See https://play.golang.org/p/tKXN_mw_Sp

**Comment by davecheney** [comment]
Shorter repo, https://play.golang.org/p/AhOFy1FI7D

**Comment by mdempsky** [comment]
Shorter still: https://play.golang.org/p/PyB02E34XI

**Comment by mdempsky** [comment]
I suspect CL 10268 (e5060c7), which added that error message.

/cc @dr2chase @rsc

**Comment by dgryski** [comment]
Duplicate of https://github.com/golang/go/issues/11728 ?

**Comment by ianlancetaylor** [comment]
Compiles with 1.4, fails with 1.5 and 1.6.

**Comment by cespare** [comment]
@dgryski yes, definitely a duplicate.
