### ISSUE TITLE
doc, wiki: mention that Go 1.7 drops support for OpenBSD < 5.6

### ISSUE THREAD

**Issue by mmcco** [golang/go#14572]
As mentioned in #13785, Go 1.7 drops support for OpenBSD 5.5 and earlier by assuming that `getentropy(2)` is available. This isn't a problem because OpenBSD 5.5 has been unsupported since May 2015, but it's worth mentioning in the release notes.

**Comment by bradfitz** [comment]
I put this in go1.7.txt already, BTW.

**Comment by mmcco** [comment]
@bradfitz That's the only place we need it, right?

**Comment by bradfitz** [comment]
For now, yes. We'll put it in the release notes when it's time.
