### ISSUE TITLE
path/filepath: paths case is not always corrected by EvalSymlinks on Windows

### ISSUE THREAD

**Issue by karaziox** [golang/go#14588]
This issue makes TestDriveLetterInEvalSymlinks fails in some path configuration from at least Go 1.4 up to Go 1.6. The problem exists only on windows.

My current setup has go installed at the location G:\\.go\. When running all.bash, the test TestDriveLetterInEvalSymlinks will fail with this result:
> --- FAIL: TestDriveLetterInEvalSymlinks (0.00s)
> path_test.go:1200: Results of EvalSymlinks do not match: "G:\\.go\\src\\path\\filepath" and "G:\\.GO\\src\\path\\filepath"

I tracked down the issue to the case-correcting procedure in symlink_windows.go. It seems that Windows's GetLongPathName will not correct the casing of a folder if it starts with a period.

The issue seem to be on Windows side and not on Go's. But it makes all.bat fail when someone's GOROOT has a folder starting with a dot in it so I prefered to make an issue for it.

**Comment by hirochachacha** [comment]
Duplicate of #13980 ?

**Comment by alexbrainman** [comment]
I cannot reproduce it on my computer. I also suspect it might be dup of  #13980 ?

What do these two commands output:
```
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
fsutil 8dot3name query
```
?

Thank you.

Alex

**Comment by karaziox** [comment]
The commands results:
> OS Name:                   Microsoft Windows 10 Pro
> OS Version:                10.0.10586 N/A Build 10586

(This is 64 bits too) and the second command (with G: for its volume)
> The volume state is: 1 (8dot3 name creation is disabled).
> The registry state is: 2 (Per volume setting - the default).
>
> Based on the above two settings, 8dot3 name creation is disabled on g:

I admit it does look quite a bit like the problem in #13980, especially since the short names were disabled on that volume (How did that happen, I have no idea). I'll close this and track the other issue.

Thanks!
