### ISSUE TITLE
proposal: net: internetAddrList return multiple addresses 

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#14580]
https://github.com/golang/go/blob/master/src/net/ipsock.go#L204
```golang
type addrList []Addr
func internetAddrList(net, addr string, deadline time.Time) (addrList, error)
```
However the internetAddrList only return one valid address.
I proposal split addr string by "," and return REAL addrList.

**Comment by mikioh** [comment]
See filterAddrList in ipsock.go. It certainly returns a list of addresses.

**Comment by mengzhuo** [comment]
No, I mean in 
```
net.Listen
    |->net.resolveAddrList
           |-> net.internetAddrList
```
and at https://github.com/golang/go/blob/master/src/net/ipsock.go#L244
if addr string is an valid IPv4/IPv6 it would nether return multi addresses nor  call filterAddrList

**Comment by mikioh** [comment]
Can you please elaborate your problem? I don't understand what's the problem.

**Comment by mengzhuo** [comment]
For example, If I want to listen to both 127.0.0.1 and 10.0.0.1
net.Listen can't do it.

**Comment by mikioh** [comment]
You didn't explain your problem. I'm still not sure what's your problem but looks like you want to have a single control knob that handles multiple address families, endpoints and subflows. So this is a duplicate of #9334.
