### ISSUE TITLE
cmd/vet: make sure copylock knows sync.Cond cannot be copied

### ISSUE THREAD

**Issue by rsc** [golang/go#14582]
As a followup to #8005, make sure that vet understands that `sync.Cond` cannot be copied. The `Locker` in that struct does not suffice because it's an interface value, not an embedded struct, so it's a pointer to a lock, which is in general fine to copy.

**Comment by stemar94** [comment]
What about ```sync.WaitGroup```?
https://play.golang.org/p/J-JP2U62fo

**Comment by valyala** [comment]
I'll look into this on the next week
