### ISSUE TITLE
x/tools/cmd/guru: confusing error message when scope has trailing slash

### ISSUE THREAD

**Issue by tschottdorf** [golang/go#14584]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
darwin

3. What did you do?
```
go get github.com/tschottdorf/goplay && oracle \
  -pos=$GOPATH/src/github.com/tschottdorf/goplay/oracle_test_boom/main.go:#40 \
  callers github.com/tschottdorf/goplay/oracle_test_boom/
```

4. What did you expect to see?
The list of callers of `(*X).Bar()` (i.e., an empty list).

5. What did you see instead?
```
/Users/tschottdorf/go/src/github.com/tschottdorf/goplay/oracle_test_boom/main_test.go:10:2: invalid operation: (&(main.X literal)) (value of type *github.com/tschottdorf/goplay/oracle_test_boom.X) has no field or method Foo
oracle: couldn't load packages due to errors: github.com/tschottdorf/goplay/oracle_test_boom/_test
```

In fact, this completely renders oracle unusable in source trees which have this phenomenon.

(cc: @mrtracy)

**Comment by kostya-sh** [comment]
@tschottdorf, oracle is no longer developed. It has been renamed to guru (golang.org/x/tools/cmd/guru) recently.

This problem exists in guru as well. The following command line can be used to reproduce:

    guru -scope github.com/tschottdorf/goplay/oracle_test_boom/ callers $GOPATH/src/github.com/tschottdorf/goplay/oracle_test_boom/main.go:#40

**Comment by alandonovan** [comment]
Thanks for the bug report. 

I notice that the trailing slash in the -scope argument seems to confuse the tool:

```
$ guru -scope github.com/tschottdorf/goplay/oracle_test_boom/ callers $GOPATH/src/github.com/tschottdorf/goplay/oracle_test_boom/main.go:#40
/usr/local/google/home/adonovan/got3/src/github.com/tschottdorf/goplay/oracle_test_boom/main_test.go:10:2: invalid operation: (&(main.X literal)) (value of type *github.com/tschottdorf/goplay/oracle_test_boom.X) has no field or method Foo
guru: couldn't load packages due to errors: github.com/tschottdorf/goplay/oracle_test_boom/_test
```

Removing the slash seems to be an effective workaround:

```
$ guru -scope github.com/tschottdorf/goplay/oracle_test_boom callers $GOPATH/src/github.com/tschottdorf/goplay/oracle_test_boom/main.go:#40
/usr/local/google/home/adonovan/got3/src/github.com/tschottdorf/goplay/oracle_test_boom/main.go:5:10: (github.com/tschottdorf/goplay/oracle_test_boom.X).Bar is called from these 0 sites:
```
