### ISSUE TITLE
x/tools/cmd/gorename: analysis of variable usage differs from go build

### ISSUE THREAD

**Issue by iand** [golang/go#14596]
gorename reports a variable as being unused when the variable is assigned in a closure. go build will compile the code without complaining.

Error reported by gorename:

```
11:50 $ gorename -offset rotator.go:#831 -to TimeFormat
/home/iand/src/code.avct.io/services/log/rotator.go:398:6: s declared but not used
gorename: couldn't load packages due to errors: code.avct.io/services/log
```

Can reproduce with code like this:

```
func Scan() {
	var s string

	tester(func() {
		s = "done"
	})
}

func tester(fn func()) {
	fn()
}
```

go version go1.6 linux/amd64
golang.org/x/tools commit 6f233b96dfbc53e33b302e31b88814cf74697ff6 

This renders gorename unusable if any of the GOPATH contains this pattern of code, even though it compiles fine with the go command.

**Comment by alandonovan** [comment]
This is really a duplicate of https://github.com/golang/go/issues/8560, the more general problem that the two frontends accept slightly different dialects.

**Comment by iand** [comment]
Yes it's the same as the example given by adg on 6 Nov 2014 so I'm happy to close this as a dupe

**Comment by jim-minter** [comment]
Out of interest, are there any known workarounds (short of not using closures in this way across a codebase) that can be used to enable use of gorename in codebases such as this before #8650 is resolved?

**Comment by jim-minter** [comment]
Out of interest, are there any known workarounds (short of not using closures in this way across a codebase) that can be used to enable use of gorename in codebases such as this before #8560 is resolved?

**Comment by alandonovan** [comment]
I've added a workaround to gorename to ignore "soft" errors like "unused variable".

**Comment by jim-minter** [comment]
Thank-you @alandonovan , that workaround has really helped!
