### ISSUE TITLE
math/big: implement GobDecode/Encode for big.Float.

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#14593]
I'll submit a CL tomorrow if there's interest.

**Comment by bradfitz** [comment]
Int and Rat have those methods, so it makes sense that Float should too. Please send a CL.

/cc @griesemer

**Comment by OneOfOne** [comment]
Alright

**Comment by OneOfOne** [comment]
Submitted a CL @ https://go-review.googlesource.com/21755
