### ISSUE TITLE
cmd/compile: shouldn't use duffcopy and duffzero on plan9/amd64

### ISSUE THREAD

**Issue by 0intro** [golang/go#14605]
Since commit [commit a6fb2aede7](https://github.com/golang/go/commit/a6fb2aede7c8d47b4d913eb83fa45bbeca76c433) (merge of dev.ssa branch), programs built by the Go compiler don't work anymore on plan9/amd64.

```
go_bootstrap 477229: suicide: sys: floating point in note handler pc=0x2c717c
```

See http://build.golang.org/log/43797a52b5ed323d15f7736d8cc66ee154493a99

go_bootstrap is crashing in runtime·duffcopy, because it uses MOVUPS, while floating point instructions are not allowed in the Plan 9 note handler.

**Comment by minux** [comment]
I proposed that we disable duffzero and duffcopy only for the runtime
package on plan 9. User packages are unaffected.

**Comment by 0intro** [comment]
I've just seen the discussion on [golang-dev](https://groups.google.com/forum/#!searchin/golang-dev/duffcopy/golang-dev/p2sgqaXa-JM/ZaCfqIIuCQAJ). Your proposed solution seems good to me.

**Comment by 0intro** [comment]
I propose [CL 20171](https://golang.org/cl/20171) to disable the use of duffcopy and duffzero entirely on Plan 9, for now.

**Comment by minux** [comment]
Should we introduce ssa.Config. NoDuffDevice field and use that instead of
isPlan9 package level variable?

**Comment by nightlyone** [comment]
Can this be closed @0intro?
