### ISSUE TITLE
mime: cannot round-trip Word{En,De}coder

### ISSUE THREAD

**Issue by nigeltao** [golang/go#14608]
WordEncoder sometimes passes text straight through, sometimes it does not. From the example_test.go:

```go
fmt.Println(mime.QEncoding.Encode("utf-8", "¡Hola, señor!"))
fmt.Println(mime.QEncoding.Encode("utf-8", "Hello!"))
```

prints

```
// Output:
// =?utf-8?q?=C2=A1Hola,_se=C3=B1or!?=
// Hello!
```

The problem is that, given an arbitrary output of a WordEncoder, how should a user tell whether or not to pass it to a WordDecoder to recover the original? A WD returns an error if the input isn't actually escaped:

```go
func main() {
	testCases := []string{
		"=?utf-8?q?=C2=A1Hola,_se=C3=B1or!?=",
		"Hello!",
	}
	for _, tc := range testCases {
		d := new(mime.WordDecoder)
		fmt.Println(d.Decode(tc))
	}
}
```

prints

```
¡Hola, señor! <nil>
 mime: invalid RFC 2047 encoded-word
```

RFC 2047 actually says that `Generally, an "encoded-word" is a sequence of printable ASCII characters that begins with "=?", ends with "?=", and has two "?"s in between` and, as a workaround, users of the mime package can check that before calling Decode.

Still, this should probably be provided by the library, instead of users of that library. I can think of two possible solutions:
1. Add a WordDecoder.CanDecode(string) bool method. The caller should call that before calling Decode.
2. Export the existing errInvalidWord as ErrInvalidWord (or as a better name). The caller should check err == mime.ErrInvalidWord after calling Decode.

@bradfitz, WDYT?

**Comment by nigeltao** [comment]
CC @alexcesaro.

**Comment by natefinch** [comment]
Thanks for filing this.  Honestly, my preference would be for a 3rd way - if the word is not encoded, just return it.. that would mirror what WordEncoder does, and would be what I would expect to work.  But I think that may not be possible with the backwards compatibility guarantee.  

Barring that, an IsEncoded function would be a nice alternate, so I could know if I need to try to Decode at all. The problem with calling it CanDecode is that if it returns false, I wonder if it actually is encoded, but incorrectly or something.  IsEncoded is more clear, IMO. Obviously, it may still be encoded in some way that the Decoder doesn't understand, but as far as the Decoder is concerned, that's still "not encoded".

**Comment by bradfitz** [comment]
I'm fine with options 1, 2 or 3, actually.

**Comment by alexcesaro** [comment]
I'm on holidays with a slow wifi but if I remember correctly
WordDecoder.DecodeHeader has the behavior you are looking for.

The documentation might need some clarification.

**Comment by nigeltao** [comment]
I'm closing this based on @alexcesaro's comment. @natefinch, please re-open if his suggestion doesn't work for you.
