### ISSUE TITLE
proposal: cmd/link: align symbols to an architecture specific minimum value

### ISSUE THREAD

**Issue by mundaym** [golang/go#14604]
In the upcoming z (s390x) port all data symbols (i.e. global variables and constants) need to be 2-byte aligned to facilitate relative addressing. To implement this I propose:

* adding a `Minalign` field to complement the `Maxalign` field in `ld.Arch`
* enforcing `Minalign` in the `symalign` function in cmd/link/internal/ld/data.go

For all preexisting architectures the value of `Minalign` would be 1.

Other architectures could also use this property to enable some optimizations.  For example on platforms where single byte loads are more expensive than n byte loads `Minalign` could be set to n to ensure that all global `bool` variables are aligned to n bytes enabling the use of n byte loads/stores.

_Note_: this would only apply to global variables (or constants), __not__ struct fields or array elements. So in the following example `a`, `b` and `c` would all consume, and be aligned to, 2 bytes in the data section. Currently `a` would only consume 1 byte and all of them would be aligned to 1 byte:

```go
package main
var a bool
var b struct { x, y bool }
var c [2]byte
...
```

CL to follow shortly. Currently setting Minalign to a value > 8 breaks the code that reads `firstmoduledata`.

**Comment by minux** [comment]
I think this is fine.

**Comment by randall77** [comment]
Sounds good.

**Comment by mdempsky** [comment]
Does this affect the alignment for 1-byte values allocated on the stack or in the heap?  (It sounds like no, but I want to be clear.)

**Comment by mundaym** [comment]
No, it won't affect heap/stack data alignment at all.

`Minalign` will only affect data that can be the target of a relocation. So only statically allocated global variables/constants (and functions, although functions are usually already aligned to a higher value anyway).

**Comment by mdempsky** [comment]
SGTM
