### ISSUE TITLE
doc: available list of first class ports

### ISSUE THREAD

**Issue by fgergo** [golang/go#14612]
(Possibly very minor issue, but might be worth to clarify, because go supports such a wide range of os/arch pairs.)

I use these sources (I could find these easily):
1. https://github.com/golang/go/wiki/PortingPolicy
2. https://golang.org/doc/install
3. https://golang.org/dl/
4. https://build.golang.org

1. defines these easily available requirements for identification:

`-` "Official binaries are provided" and

`-` "Installation is documented at http://golang.org/doc/install"

Looking at https://golang.org/dl/  ∩  http://golang.org/doc/install : 
freebsd/386 is missing from installation documentation (System requirements)

If it's "easy", this is probably also worth to clarify:
Looking at https://golang.org/dl/  ∩  http://golang.org/doc/install ∩ https://build.golang.org : 
build.golang.org lists these as first class ports, not mentioned in the canonical source of lists:
darwin/arm
darwin/arm64
darwin/386
freebsd/arm
freebsd/386
linux/mips64le
linux/ppc64
linux/ppc64le
android/arm

**Comment by broady** [comment]
Let's track it over at #17018. Sorry to dup an older bug with a newer one.
