### ISSUE TITLE
HTTP/2 on a server with a listener

### ISSUE THREAD

**Issue by trajber** [golang/go#14619]
I am trying to enable HTTP/2 on a server that is started using a net.Listener but it doesn't work. It only works on HTTP/1.1 mode.
http://play.golang.org/p/muebCalxpl

But when I set the http.Server.TLSConfig the HTTP/2 is enabled.
http://play.golang.org/p/HhPJA0EfEb

Is this the correct behavior? Why the server doesn't use the tls.Config of the net.Listener?

I'm using Go 1.6 on Linux amd/64.

**Comment by rafaeljusto** [comment]
I also notice that you need to use the same instance of tls.Config in **tls.Listen** and **http.Server.TLSConfig** to make it work.

**Comment by bradfitz** [comment]
Yes, http.Server.Start will update the TLSConfig if it can. If it doesn't have a reference to it, it cannot.

Or you can set your listener's *tls.Config.NextProtos yourself (set it to `[]string{"h2"}`).
