### ISSUE TITLE
x/mobile/bind: bind is using API not available before 1.6

### ISSUE THREAD

**Issue by hyangah** [golang/go#14615]
o.Val().ExactString undefined (type constant.Value has no field or method ExactString)

This usage was introduced with cl/20092 to fix the long strings handling bug.
ExactString however is not available in go1.5

**Comment by choleraehyq** [comment]
I also meet this problem.
Moreover, [the document of gomobile](https://godoc.org/golang.org/x/mobile/cmd/gomobile) tells me that "At least Go 1.5 is required. ", which is misleading.

**Comment by kristian-hermansen** [comment]
I just tested this and it still seems broken to me.

**Comment by kristian-hermansen** [comment]
Thanks. Working now. I presume the repo is now updated.
