### ISSUE TITLE
os/user: implement basic cgo-free Current user function

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14626]
`os/user.Current` returns a (*User, error). User is:

```go
type User struct {
        Uid      string // user id
        Gid      string // primary group id
        Username string
        Name     string
        HomeDir  string
}
```

When the binary is built without cgo, `os/user.Current` returns an error.

This bites people often (most recently: #14625) and is confusing. I propose that in cgo-free builds, we make Current work using:

```go
user := &User{
   Uid: strconv.Itoa(os.Getuid()),
   Gid: strconv.Itoa(os.Getgid()),
   Username: os.Getenv("USER"),  // or USERNAME on Windows
   HomeDir: os.Getenv("HOME"),   // or HOMEDRIVE+HOMEDIR on windows
}
```

and only if either Username or HomeDir are empty do we return an error.

I think we can ignore the User.Name field.

**Comment by minux** [comment]
SGTM.
