### ISSUE TITLE
user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by hacdias** [golang/go#14625]
Hello

I'm currently using Go 1.6 and crosscompiling [```caddy-hugo```](https://github.com/hacdias/caddy-hugo) on Travis using [```gox```](https://github.com/mitchellh/gox). When trying to execute the executable on Linux, I get the error ```user: Current not implemented on linux/amd64```. 

I tested the Windows executable and it works well.

What should I do?

Thanks,

**Comment by OneOfOne** [comment]
`user.Current` needs cgo on Linux, your best bet is using a linux vm to compile.

**Comment by minux** [comment]
Or you could download the linux prebuilt binary, extract the
pkg/linux_amd64 directory and put it under your GOROOT/ pkg. Then you don't
need to use a VM or setup linux cross compiler just to compile a pure Go
program that happens to use net or os/user packages that require cgo.

Please ask further questions on golang-nuts or see
https://golang.org/wiki/Questions

**Comment by bradfitz** [comment]
During the Go 1.7 dev cycle we've updated that error text to tell you that it's because you built a pure Go binary (usually because cross-compiled) and `os/user` requires `cgo`.

Maybe we should fix this, though. I've filed #14626

**Comment by hacdias** [comment]
Thank you all.
