### ISSUE TITLE
database/sql/driver: update documentation on what types drivers can return from Scan calls

### ISSUE THREAD

**Issue by pib** [golang/go#14621]
[src/database/sql/driver/driver.go](https://github.com/golang/go/blob/master/src/database/sql/driver/driver.go#L13) says
> // Value is a value that drivers must be able to handle.
> // It is either nil or an instance of one of these types:
> //
> //   int64
> //   float64
> //   bool
> //   []byte
> //   string   [*] everywhere except from Rows.Next.
> //   time.Time

and then [in the driver.Rows.Scan spec](https://github.com/golang/go/blob/master/src/database/sql/driver/driver.go#L164) it says:
>	// The dest slice may be populated only with
>	// a driver Value type, but excluding string.
>	// All string values must be converted to []byte.

But in [sql.convertAssign](https://github.com/golang/go/blob/master/src/database/sql/convert.go#L86) which is called by [sql.Rows.Scan](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1838), it actually handles values of pretty much every type depending on the type the value is being scanned into.

According to the spec, this fix for the go-sql-driver/mysql driver shouldn't work, but it does: https://github.com/go-sql-driver/mysql/pull/434

It seems like the docs should be updated to reflect the actual behavior, or at least include all the types which are handled by [asString](https://github.com/golang/go/blob/master/src/database/sql/convert.go#L287) and [asBytes](https://github.com/golang/go/blob/master/src/database/sql/convert.go#L310) for values which are allowed to be returned from driver.Rows.Scan implementations.

**Comment by bradfitz** [comment]
Fixed already in #6497
