### ISSUE TITLE
all: mipsel linux 32bit not supported

### ISSUE THREAD

**Issue by wumao** [golang/go#14637]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go 1.6
2. What operating system and processor architecture are you using (`go env`)?
   ubuntu
3. What did you do?
   (Use play.golang.org to provide a runnable example, if possible.)
   I want to cross compile mipsel 32 bit software for openwrt  linux。
4. What did you expect to see?
   support mipsel 32 bit
5. What did you see instead?

**Comment by ALTree** [comment]
Linux/mipsle is supported since go1.8, closing here.
