### ISSUE TITLE
change slice from other goroutine

### ISSUE THREAD

**Issue by WanliTian** [golang/go#14634]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

centos6.3

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

http://play.golang.org/p/pGxGS9YNC8

4. What did you expect to see?

i want see that the data is changed by the routine

5. What did you see instead?

data is unchaged

i can see that, in the master process and goroutine process, the slice has the same addr.

**Comment by ianlancetaylor** [comment]
You are sending a struct on the channel, and changing the struct.  Changing one copy of a struct does not change a different copy.

You need to use a pointer, as in http://play.golang.org/p/_MN5e6cbk3 .

**Comment by minux** [comment]
The main goroutine sent a copy of the struct to the data
to the other goroutine, so the modification done in that
goroutine will not affect the copy of Data in the main
goroutine.

Please ask further questions on the mailing list or forum,
see https://golang.org/wiki/Questions.

**Comment by WanliTian** [comment]
but if i using assignment instead of append, it can affect the original struct.

**Comment by ianlancetaylor** [comment]
Slice have an underlying array that is passed by reference.

As Minux said, please do not use the issue tracker to ask questions.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by WanliTian** [comment]
ok

struct is copied, but struct's field is **slice**
