### ISSUE TITLE
os/exec: Command doesn't seem to work as I expected

### ISSUE THREAD

**Issue by iamthemuffinman** [golang/go#14632]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

  1.6

2. What operating system and processor architecture are you using (`go env`)?

  GOARCH="amd64"
  GOHOSTARCH="amd64"
  GOHOSTOS="darwin"
  GOOS="darwin"

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

  Basically, I'm just calling ovftool with some arguments using exec.Command, but it's erroring out due to the way quotes are being passed in. Here's an example: https://play.golang.org/p/thL1dc3yxd

4. What did you expect to see?

  This is what I get when ovftool is called via exec.Command:

  Opening OVF source: "vsphere-ubuntu-14.04.4.vmx"
  Error: Failed to open OVF descriptor
  Completed with errors

  But when the command is copy-pasted into the terminal, it works.

5. What did you see instead?

  I expected it to work exactly like it would If I typed it in a terminal. I don't quite understand what is or isn't happening so I don't know if this is a Go problem or not.

**Comment by bradfitz** [comment]
Your shell is doing argument parsing for you. Try removing the double quotes.

**Comment by iamthemuffinman** [comment]
I've updated the example with what I think you mean @bradfitz: https://play.golang.org/p/fF3xTONlIq

If that is what you meant, then this will not work for me. Double quotes HAVE to be passed to the arguments in case of spaces (In my case there were no spaces). If that is not what you meant, please elaborate further.

**Comment by minux** [comment]
os/exec doesn't parse the arguments for you, unlike C's system,
which uses shell to execute the command.

Given a command executed with shell:
command -A="a b c" "d e"

with os/exec, pass the following args to achieve the same effect:
[]string{ "-A=a b c", "d e" }

If the program really require the double-quotes, then at the shell
command line, you will need to do this:
command -A='"a b c"'

with os/exec, use this as args:
[]strings{ "-A=\"a b c\"" }

Please ask questions on mailing lists or forums, see
https://golang.org/wiki/Questions. Thanks.
