### ISSUE TITLE
x/sys/unix: TimevalToNsec missing on linux arm 32bit

### ISSUE THREAD

**Issue by nkovacs** [golang/go#14643]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
arm, raspbian (raspberry pi 2)

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
Tried to install golang.org/x/sys/unix

4. What did you expect to see?

5. What did you see instead?
It doesn't compile, because TimevalToNsec is missing from https://github.com/golang/sys/blob/master/unix/syscall_linux_arm.go

**Comment by morriswinkler** [comment]
are you serious, why don't you add 

````
func TimevalToNsec(tv Timeval) int64 { return int64(tv.Sec)*1e9 + int64(tv.Usec)*1e3 }
````
to /unix/syscall_linux_arm.go

**Comment by nkovacs** [comment]
Yes, I'm serious. This is a bug in x/sys/unix. That's why I reported it.

I already added it and it compiled and works, but that's just a short-term workaround until the bug gets fixed (hopefully soon, since it's trivial).

**Comment by morriswinkler** [comment]
so what is the context of the bug, it is a missing function in the arm version of the package, if you want i can test the fix on my beaglebone

**Comment by nkovacs** [comment]
Someone probably forgot to add it to syscall_linux_arm.go.

**Comment by morriswinkler** [comment]
my guess too 

is it going to be fixed ?

**Comment by bradfitz** [comment]
Yes. It'll be fixed. No need to worry.

**Comment by morriswinkler** [comment]
great, all my worries are gone :) thanks
