### ISSUE TITLE
crypto/x509: typo in docs for x509.CreateCertificateRequest

### ISSUE THREAD

**Issue by voutasaurus** [golang/go#14649]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
Read https://golang.org/pkg/crypto/x509/#CreateCertificateRequest

4. What did you expect to see?
"CreateCertificateRequest creates a new certificate request based on a template."

5. What did you see instead?
"CreateCertificateRequest creates a new certificate based on a template."

This was really confusing for a minute because there is currently no exposed function in x509 that creates a certificate from a request, but that sentence implies that's what CreateCertificateRequest does, even though the name of the function makes it sort of obvious that's not what it does.

**Comment by ianlancetaylor** [comment]
CC @agl 

(I would fix it but I really don't understand this stuff.)

**Comment by rsc** [comment]
I do understand this one detail and I confirm that
"CreateCertificateRequest creates a new certificate based on a template."
should instead be
"CreateCertificateRequest creates a new certificate *request* based on a template."

If someone creates the CL, LGTM.
