### ISSUE TITLE
poor performance when using make and large reserve capacity

### ISSUE THREAD

**Issue by pjbgtnj** [golang/go#14658]
Problem appears in (at least) versions 1.5 and 1.6 on Linux amd64

When doing a make([]string, ....) with a large reserve capacity, the performance is poor.   It appears that a lot of  potentially unnecessary work is done.

See the following comparison between similar go and c++ programs:
```
$ cat xxx.go
package main

import (
	"time"
	"log"
)

func main() {
for cap := 1; cap <= 100000; cap *= 10 {
	t1 := time.Now().UnixNano()
	for count := 0; count < 100000; count += 1 {
		strs := make([]string, 0, cap)
		if len(strs) != 0 {
			log.Printf("Error: %d\n", len(strs))
		}
	}
	t2 := time.Now().UnixNano()
	log.Printf("Time: %d %f\n", cap, float64(t2 - t1) / 1000000000.0)
}
}
$ go run xxx.go
2016/03/04 19:34:07 Time: 1 0.006270
2016/03/04 19:34:07 Time: 10 0.019383
2016/03/04 19:34:07 Time: 100 0.071207
2016/03/04 19:34:08 Time: 1000 0.474111
2016/03/04 19:34:11 Time: 10000 3.924790
2016/03/04 19:34:46 Time: 100000 34.735739

$ cat xxx.cc
#include <vector>
#include <iostream>
#include <stdint.h>
#include <chrono>

int32_t main(int32_t argc, char **argv) {
   for (int32_t cap = 1; cap <= 100000; cap *= 10) {
      auto t1 = std::chrono::high_resolution_clock::now();
      for (int32_t count = 0; count < 100000; count += 1) {
         std::vector<std::string> strs;
         strs.reserve(num);
         if (strs.size() != 0) {
            std::cout << "Error: " << strs.size() << std::endl;
         }
      }
      auto t2 = std::chrono::high_resolution_clock::now();
      std::cout << cap << " " << static_cast<double>(std::chrono::duration_cast<std::chrono::nanoseconds>(t2-t1).count()) / 1000000000.0l << std::endl;
   }
   return 0;
}
$ ./xxx
1 0.0158139
10 0.0142682
100 0.0150497
1000 0.0147065
10000 0.0167867
100000 0.0146535
```

**Comment by cznic** [comment]
Assuming C++ does not initialize memory allocated by `strs.reserve(num)`, you are comparing an O(1) operation in case of C++ to an O(n) operation in case of Go. The numbers seems to confirm that, so I'm inclined to say working as intended.

**Comment by pjbgtnj** [comment]
Why would go initialize the difference between the initial size and capacity entries with values?  You can't ever access them.

**Comment by cznic** [comment]
You can re-slice a slice at any time to any len up to its cap.

**Comment by pjbgtnj** [comment]
It might make sense to defer the creating/initialization of elements until a slice/re-slice brings the "capacity objects" into view/existance.

An often used pattern for an arrays is to create one with no objects and add objects to it until some condition is met (ie, dynamic/variable length array).  This is also true for strings (which as far as I know doesn't have a reserve capacity).  The implementation in go pretty makes one choose a capacity that on average doesn't initialize too many objects and one that doesn't make too many copies when extending.  Either that, or code up their own dynamic array.

**Comment by bradfitz** [comment]
> It might make sense to defer the creating/initialization of elements until a slice/re-slice brings the "capacity objects" into view/existance.

That would require keeping additional state (extra memory) somewhere, which isn't feasible at this point.

I don't think there's really anything to do here.
