### ISSUE TITLE
proposal: x/tools/cmd/present: Support presenter notes on the Go present tool

### ISSUE THREAD

**Issue by audreylim** [golang/go#14654]
I propose adding support for presenter notes in the Go present tool.

Motivation: Go present is great. I used Go present at the recent GopherCon India and wished there was support for presenter notes. Having a presenter tool, with Go present, can make presentations a lot smoother and calm the presenter's nerves. Presenters don't have to use alternatives with presenter options if they want to use Go present. Best of both worlds.

Demo: http://virtivia.com:27080/1vs4fiwjm924q.mov

An implementation: https://github.com/audreylim/go-presenter#readme 

If this proposal is accepted, I can submit a CL with the changes I've done for further review.

EDIT: [here](https://github.com/audreylim/go-presenter/compare/6d2d6fe87af7948f2e44ea75fdbe2d39418cc3ad...master) are the changes

**Comment by kostya-sh** [comment]
Related issue: #12355

**Comment by ianlancetaylor** [comment]
CC @adg

**Comment by audreylim** [comment]
Summary of changes (latest): https://github.com/audreylim/go-presenter/compare/6d2d6fe87af7948f2e44ea75fdbe2d39418cc3ad...9b35c29d607932193220b7b1137788d0e9c606e1

Technical implementation:

- Presenter uses localStorage event listeners to sync both windows - the main browser window and the pop up window, which will display the slides and presenter notes
- Processing is done entirely in the front end (javascript), no websockets involved
- The main browser window listens for keypress 'P', which will open the Presenter window. However, 'P' only works when Presenter mode is enabled, by running `present -p` instead of `present`
- Instructions for pressing 'P' appears in the terminal logs when `present -p` is run - for informing the speaker
- The slides are loaded onto the Presenter window using an iframe - this retains the layout of the Go present slides, and allows dual syncing triggered by localStorage events, which ensures reliability and speed of the syncing
- Notes are parsed/identified in the backend by prefixing a paragraph with `"& "`. Multiple paragraphs are supported

Notes/Concerns:

- Running `.play` actions by clicking on `Run` does not sync in the other window (see [example](https://github.com/audreylim/go-presenter#what-presenter-does-not-do))
- Currently does not display timer, but that can be added
- The focus was to get this working, so it currently only supports Chrome. Multiple browser support can be investigated/enabled
- This implementation is meant to help speakers primarily, so speaker notes will not be directly available on sites like go-talks.appspot.com for readers/audiences. It works only if run locally as `present -p` can be enabled
- `"& "` is the current syntax for notes, but that can be changed. Maybe (`"// "`) or something comment/notes like

Please let me know what you think.

**Comment by adg** [comment]
I think the general approach looks fine. We'll need to resolve the issue with `run` not being synchronized. The state of the presenter window and the main window should be completely synchronized.

Hey @robpike (who has some propriety over the present file format) do you think that `&` is a fine start-of-line symbol for presenter notes?

**Comment by robpike** [comment]
I think it doesn't matter much but I might choose > or even -> .

**Comment by shurcooL** [comment]
> I think it doesn't matter much but I might choose > or even -> .

I don't mean to bikeshed, but I would mention the following about `>` as the prefix:

`>` is often used as a prefix for doing a quote or blockquote. It's what it looks like:

```
> some quote goes here

some reply goes here
```

Which is also valid Markdown that gets rendered as:

> some quote goes here

some reply goes here

`->` prefix does not have this problem as far as I know.

However, I looked at some existing talks, and did not find any usages of this markdown idiom there. The one quote I found was actually written as a quote rather than a blockquote, so maybe `>` is not bad (even if it conflicts with markdown).

**Comment by adg** [comment]
`->` seems unnecessarily hard to type, imo.

Another options is `:`, which is (too?) similar to the comment character `;`.

```
Slide content

& Speaker note
```

```
Slide content

> Speaker note
```

```
Slide content

: Speaker note
```

I'm actually kinda partial to `:`. More so than `&` at least. I too apologize for bike shedding.

**Comment by audreylim** [comment]
I liked `> ` but as @shurcooL pointed out, it conflicts with Markdown convention.

The next best choice seems to be `: `. It's more correlated to "speaking" than `& `.

Eg.
```
Person A says: hello
Person B says: hi
```

My vote goes to `: `.

**Comment by adg** [comment]
Okay, let's go with `:` assuming there are no fierce objections.

Implementation-wise, I suggest going in this order:

- [ ] Parse notes and record them in the `Section` struct
- [ ] Add the command-line flag to enable presenter notes
- [ ] Add the notes to the slide template
- [ ] Display the notes, synchronize browser windows

I also suggest, since notes seem to be the focus here, that the flag be `-notes` rather than `-p`.

**Comment by adg** [comment]
I would consider issue #12355 closed once this is resolved. The approach described there is overkill, I think.

**Comment by shurcooL** [comment]
I like `:`. More than `&`.

After seeing @audreylim's analogy to "Person A says: something", that makes it easy to remember too.

**Comment by audreylim** [comment]
@adg Noted your suggestions.

With the `-notes` flag instead of `-p`, any preference for the keypress? It's currently `P` (for Presenter) to open a window. With notes, might be more consistent to use keypress `N`

**Comment by adg** [comment]
`N` also sounds good. :+1:
