### ISSUE TITLE
strings.TrimRight() has bug when trim some strings

### ISSUE THREAD

**Issue by hongjianzhu** [golang/go#14657]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

darwin/amd64

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

func main() {
	path := "Order.thrift"

	b := filepath.Base(path)
	fmt.Println(b) // Order.thrift

	e := filepath.Ext(path)
	fmt.Println(e) // .thrift

	n := strings.TrimRight(b, e)
	fmt.Println(n)
}

4. What did you expect to see?

Order

5. What did you see instead?

Orde

**Comment by davecheney** [comment]
Trimright removes characters in the set e from b, starting from the right. It's not what you want. 

You want, n := b[:len(b)-len(e)]

As you know that e is the suffix of b

**Comment by minux** [comment]
Quote https://golang.org/pkg/strings/#TrimRight

func TrimRight(s string, cutset string) string
TrimRight returns a slice of the string s, with all trailing Unicode code
points contained in cutset removed.

What you want is probably https://golang.org/pkg/strings/#TrimSuffix

**Comment by hongjianzhu** [comment]
@davecheney, @minux  thank you guys for your kindly replay :-]
