### ISSUE TITLE
doc: Clarify what code is referred in the "Pointers vs. Values" section of Effective Go

### ISSUE THREAD

**Issue by alkchr** [golang/go#14656]
![Pointers vs. Values section of Effective Go document](https://cloud.githubusercontent.com/assets/6612636/13546602/d39a73ae-e2dc-11e5-8f01-d89fe0a40181.png)
[`Append`](https://tip.golang.org/doc/effective_go.html#append) section is a few screens before [`Pointers vs. Values`](https://tip.golang.org/doc/effective_go.html#pointers_vs_values) and (1) is easy to miss. It is therefore not clear for the reader what code is referred in the comment of snippet (2) and subsequent ones. At least, that was my experience.

I would, transform (1) into a link to `#append` (to attract reader's attention and clarify what exactly `Append` is meant) and change (2) to something like:
```diff
- // Body exactly the same as above
+ // Body is exactly the same as described in the Append section above.
```

**Comment by ianlancetaylor** [comment]
CC @robpike

**Comment by rsc** [comment]
The fix is to insert the two words "func Append":

	// Body exactly the same as func Append above

If someone wants to create this CL, LGTM.
