### ISSUE TITLE
website: https://golang.org/doc/contribute.html uses old Gerrit link

### ISSUE THREAD

**Issue by MrMormon** [golang/go#14662]
https://golang.org/doc/contribute.html, https://github.com/golang/go/blob/master/CONTRIBUTING.md, and https://github.com/golang/go/blob/master/doc/contribute.html link to https://code.google.com/p/gerrit/.
It's not a big deal for the first and third link, but https://github.com/golang/go/blob/master/CONTRIBUTING.md doesn't link to Google's Gerrit instance at all.

**Comment by ianlancetaylor** [comment]
CC @adg
