### ISSUE TITLE
x/sys/unix/zerrors_linux_arm.go contains incorrect constants

### ISSUE THREAD

**Issue by nkovacs** [golang/go#14661]
1. What version of Go are you using (`go version`)?
   1.6 linux/arm
2. What operating system and processor architecture are you using (`go env`)?
   arm, linux (raspbian), raspberry pi 2
3. What did you do?
   try to compile an app using this package: https://github.com/nkovacs/go-udev/
4. What did you expect to see?
   a successfully built executable
5. What did you see instead?
   ../../github.com/nkovacs/go-udev/monitor.go:161: constant -2147483647 overflows uint32

I regenerated the file $GOPATH/src/golang.org/x/sys/unix/zerrors_linux_arm.go using mkerrors.sh. It generated this file: https://gist.github.com/nkovacs/03a77ecf7ce03102923a
After this, I was able to compile the app and it works.

**Comment by tklauser** [comment]
Should be fixed by commit golang/sys@ea9bcade75cb975a0b9738936568ab388b845617 ([CL 37943](https://go-review.googlesource.com/37943))

**Comment by nkovacs** [comment]
Thanks.
