### ISSUE TITLE
vet: copylock check doesn't detect certain copies

### ISSUE THREAD

**Issue by valyala** [golang/go#14664]
copylock check must emit a warning on copying `sync.Mutex` or struct containing `sync.Mutex`. It doesn't detect the following cases:

```go
        var a sync.Mutex
        b := a   // doesn't detect
        var c = a  // doesn't detect
        b = a  // detects
```

See #8005 for details.

**Comment by valyala** [comment]
Submitted a patch for code review - https://go-review.googlesource.com/20254 .

**Comment by valyala** [comment]
Added yet another patch for detecting locks' copying inside composite literals:

```go
type A struct {
   L sync.Mutex
}

var m sync.Mutex
a := A{
    L: m,   // now this case is detected
}
b := []sync.Mutex{m, a.L}  // and this one
c := map[string]sync.Mutex{"foo": m}  // and this one
```

**Comment by valyala** [comment]
https://go-review.googlesource.com/20258

**Comment by josharian** [comment]
Thanks for working on these. I left some comments and asked Rob to take over reviewing once they're addressed (that's what R=r means).

**Comment by valyala** [comment]
@josharain, I updated the CL according to comments.

**Comment by josharian** [comment]
Please ping the CL. (Just write a comment that says "Ping.") Feel free to repeat as needed. I'm leaving the remainder of the review to Rob.

**Comment by valyala** [comment]
There is yet another case not covered by `cmd/vet`:

```go
var a [5]sync.Mutex
b := a // here we copy mutexes by value
```

Will create a CL for this case.

**Comment by valyala** [comment]
See [the CL](https://go-review.googlesource.com/24340)

**Comment by valyala** [comment]
Yet another case has been caught and covered by the CL mentioned above:

```go
a := sync.Mutex{}
a = sync.Mutex{}  // here a is overwritten by new value
```
