### ISSUE TITLE
cmd/compile: internal compiler error: unhandled addr INDEXMAP 

### ISSUE THREAD

**Issue by rhysh** [golang/go#14678]
> What version of Go are you using (`go version`)?

```
go version devel +da1802f Sun Mar 6 23:57:06 2016 +0000 darwin/amd64
```

> What did you do?

https://play.golang.org/p/t1rcQ_zYVD

```
// compile

// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

func main() {
	m := make(map[int]bool)
	i := interface{}(false)

	_, m[1] = i.(bool)
}
```

> What did you expect to see?

Successful compilation

> What did you see instead?

Tip fails with `internal compiler error: unhandled addr INDEXMAP`, go1.6 and go1.5.3 fail with `internal compiler error: agen: unknown op INDEXMAP u(2) l(13) tc(1) assigned bool`, compilation on go1.4 succeeds.

**Comment by ianlancetaylor** [comment]
CC @randall77

**Comment by mdempsky** [comment]
Had to revert the fix due to #15602. Will try again for 1.8.

Minimal repro of regression:

    package p

    func f(i interface{}) {
            i, _ = i.(error)
    }

(Sorry @tshprecher, I think your original CL did not have this problem, and it was only introduced by my suggested rewrite.)

**Comment by tshprecher** [comment]
@mdempsky, sorry for this, and sorry for responding so late as I rewrite my noisy github gmail filters. It's no problem.

**Comment by mdempsky** [comment]
Possibly related issue #13433.

Also, FYI (and for my own reference), running cmd/compile with -W -W will dump the nodes list both before and after the "order" pass.  E.g., for function foo, it's before-order form is printed as "before order foo", and then it's after-order form is printed as "before foo".  ("before foo" here really means "before walk foo", where 'walk' is the compiler's next function pass after 'order'.)

Unfortunately the raw Nod tree dump is very informative, but not very intuitive.  (Aside: If anyone wants to play with prettier ways to print those out, that would be awesome.)

**Comment by rsc** [comment]
Seems to work fine now.
