### ISSUE TITLE
Go process is getting stuck.

### ISSUE THREAD

**Issue by sagar8192** [golang/go#14673]
Please answer these questions before submitting your issue. Thanks!

go versions:
 go1.5.2 linux/amd64
I am having the same issue with go 1.6

OS version:
Linux host 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 GNU/Linux

I am working on a application that I doing ~20 QPS on a UDP socket. After accepting data on UDP socket I am writing to a buffered channel.

strace -ttt -f -p <pid>
[pid 1052205] 1457261183.644962 <... select resumed> ) = 0 (Timeout)
[pid 1052205] 1457261183.644990 futex(0x780f60, FUTEX_WAIT, 0, {60, 0} 
[pid 1052206] 1457261183.645062 <... futex resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.645081 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.645269 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.645456 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.645643 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.645829 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.646017 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid 1052206] 1457261183.646203 futex(0x780f50, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)

This looks pretty similar to #11019 @bradfitz

**Comment by bradfitz** [comment]
Please provide your code. How do we reproduce this? It's quite likely a bug in your code.

**Comment by sagar8192** [comment]
`package main

import (
    "encoding/json"
    "fmt"
    "net"
    "os"
    "sync"
)

func CheckError(err error) {
    if err  != nil {
        fmt.Println("Error: " , err)
        os.Exit(0)
    }
}

var WorkQueue = make(chan WorkRequest, 100)

func Reader(ws *sync.WaitGroup) {
    ServerAddr,err := net.ResolveUDPAddr("udp",":10001")
    CheckError(err)

    ServerConn, err := net.ListenUDP("udp", ServerAddr)
    CheckError(err)
    defer ServerConn.Close()

    buf := make([]byte, 4096)
    var request WorkRequest

    for {
        n,addr,err := ServerConn.ReadFromUDP(buf)
        err1 := json.Unmarshal(buf[:n], &request)
        fmt.Println("Received from ", addr)

        if err != nil {
            fmt.Println("Error: ",err1)
        }
        if err1 != nil {
            fmt.Println("Problem in unmarchalling data: ",err1)
        }

        work := WorkRequest{Topic: request.Topic, Logline: request.Logline}

        WorkQueue <- work
        fmt.Println("Work request queued", request.Topic, request.Logline)
    }
    ws.Done()
}`

**Comment by minux** [comment]
We will need the full program to reproduce this.

**Comment by sagar8192** [comment]
@bradfitz @minux Here the code. https://github.com/sagar8192/Flash

**Comment by sagar8192** [comment]
In order to reproduce exclude kafka_client.go from the build. After creating the executable. Just run the executable and then run following:

watch -n 0.1 go run kafka_client.go

**Comment by davecheney** [comment]
I am sorry but your code does not compile cleanly

```
lucky(~/src/github.com/juju/juju) % go get github.com/sagar8192/Flash



# github.com/sagar8192/Flash
../../sagar8192/Flash/dispatcher.go:50: undefined: m
../../sagar8192/Flash/dispatcher.go:56: undefined: m
../../sagar8192/Flash/kafka_client.go:14: CheckError redeclared in this
block
        previous declaration at ../../sagar8192/Flash/collector.go:12
../../sagar8192/Flash/kafka_worker.go:39: undefined: check
../../sagar8192/Flash/kafka_worker.go:55: undefined: check
../../sagar8192/Flash/main.go:31: main redeclared in this block
        previous declaration at ../../sagar8192/Flash/kafka_client.go:20
```

Please restructure your code into two packages, a client binary and a
server binary (go run is not suitable for writing anything by non trivial
programs).

**Comment by sagar8192** [comment]
@davecheney Sorry about that. I have separated server and client package and also verified that code compiles now.

**Comment by davecheney** [comment]
Thank you. Some feedback

client/kafka_client.go

line 36: you must stop here on error
line 40: you are checking the wrong error

server/ is no longer a main package.

How can we reproduce the problem you see. Thank you.

**Comment by bradfitz** [comment]
Let's move this to a forum until a problem is identified. It's increasingly sounding like an issue learning the language or tools, and the issue tracker isn't really the place for that.

See https://golang.org/wiki/Questions
