### ISSUE TITLE
mime/multipart/partReader ignores first EOF it reads and fails if next Read call returns another error

### ISSUE THREAD

**Issue by AsamK** [golang/go#14676]
1. What version of Go are you using (`go version`)?
 go1.6

2. What operating system and processor architecture are you using (`go env`)?
 linux/amd64

3. What did you do?
https://play.golang.org/p/ePzW9GtCEe

4. What did you expect to see?
the multipart reader should correctly read the multipart content

5. What did you see instead?
ReadForm() fails with "multipart: Part Read: unexpected EOF"

This worked in go1.5 and fails in go1.6 because of a change in the zlib reader (see #14675)

**Comment by bradfitz** [comment]
Re-milestoning for consideration for Go 1.6.1. This bug was always present, but was exposed by #14675. If #14675 goes into Go 1.6.1, that might be enough. Although this fix is trivial too.
