### ISSUE TITLE
x/exp/inotify: inotify_linux RemoveWatch needs to delete reference to watch even if system returns error.

### ISSUE THREAD

**Issue by jasonrichardsmith** [golang/go#14685]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go 1.6

2. What operating system and processor architecture are you using (`go env`)?
amd64, Linux

3. What did you do?
in inotify_linux RemoveWatch does not remove from the registry of watches if Linux returns an error.

I notify returns an error if you need to stop watching a directory, as it should because it automatically removes directories, but you still need to remove the registry because if the directory gets added back you need a new watcher reference id.

4. What did you expect to see?
when a directory is removed and added back files within the directory should return the full path name

5. What did you see instead?
If a directory is removed and added just the file name with no path is returned for the Event.Name

The delete function just needs to be moved
Fix can be found here:
https://github.com/jasonrichardsmith/exp/commit/6d6db11842483d91223ca57b2a462a39699e0249

**Comment by rsc** [comment]
Deleted this code instead. See github.com/fsnotify for more maintained code.
