### ISSUE TITLE
crypto/x509: occasional failure on FreeBSD builders

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14688]
The FreeBSD builders and trybots are occasionally showing a failure testing crypto/x509.  For example, from http://build.golang.org/log/be7097e5de7cd4ce84f49856fd3f128a6040dcbb:

    unexpected fault address 0x531159
    fatal error: fault
    [signal 0xa code=0x3 addr=0x531159 pc=0x531159]
    
    goroutine 26 [running]:
    runtime.throw(0x659f39, 0x5)
    	/tmp/workdir/go/src/runtime/panic.go:566 +0x8c fp=0xc820041be8 sp=0xc820041bd0
    runtime.sigpanic()
    	/tmp/workdir/go/src/runtime/sigpanic_unix.go:21 +0x1ce fp=0xc820041c38 sp=0xc820041be8
    math/big.nat.bytes(0xdeaddeaddeaddead, 0x6, 0x17, 0xc8203861e0, 0x30, 0x30, 0xc8203861b0)
    	/tmp/workdir/go/src/math/big/nat.go:1245 +0x29 fp=0xc820041c40 sp=0xc820041c38
    math/big.(*Int).Bytes(0xc82038ef00, 0x61, 0x61, 0xc820064070)
    	/tmp/workdir/go/src/math/big/int.go:396 +0x8f fp=0xc820041c98 sp=0xc820041c40
    crypto/elliptic.Marshal(0x800822928, 0xc8200e2880, 0xc82038ef00, 0xc82038ef20, 0x30, 0x30, 0xc8200e4b20)
    	/tmp/workdir/go/src/crypto/elliptic/elliptic.go:311 +0xa6 fp=0xc820041cf8 sp=0xc820041c98
    crypto/x509.MarshalECPrivateKey(0xc820063a40, 0xa7, 0xa7, 0xc820063a40, 0x0, 0x0)
    	/tmp/workdir/go/src/crypto/x509/sec1.go:51 +0x197 fp=0xc820041dd8 sp=0xc820041cf8
    crypto/x509.TestParseECPrivateKey(0xc820092000)
    	/tmp/workdir/go/src/crypto/x509/sec1_test.go:35 +0x10a fp=0xc820041f70 sp=0xc820041dd8
    testing.tRunner(0xc820092000, 0x7683e0)
    	/tmp/workdir/go/src/testing/testing.go:473 +0x7e fp=0xc820041f90 sp=0xc820041f70
    runtime.goexit()
    	/tmp/workdir/go/src/runtime/asm_amd64.s:2006 +0x1 fp=0xc820041f98 sp=0xc820041f90
    created by testing.RunTests
    	/tmp/workdir/go/src/testing/testing.go:581 +0x313
    
    goroutine 1 [chan receive]:
    testing.RunTests(0x672e50, 0x768380, 0x21, 0x21, 0x1)
    	/tmp/workdir/go/src/testing/testing.go:582 +0x359
    testing.(*M).Run(0xc820031f08, 0x403c8a)
    	/tmp/workdir/go/src/testing/testing.go:515 +0x79
    main.main()
    	crypto/x509/_test/_testmain.go:120 +0xb4
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    	/tmp/workdir/go/src/runtime/asm_amd64.s:2006 +0x1
    FAIL	crypto/x509	0.245s

**Comment by bradfitz** [comment]
Dup of #14667 and #14591
