### ISSUE TITLE
cmd/compile: "dot import" causes confusing error in 1.6

### ISSUE THREAD

**Issue by ThisGuyCodes** [golang/go#14683]
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   amd64 all around. Reproduced identical output in both Ubuntu (well, mint) and OSX 10.11.
3. What did you do?

```
$ go get github.com/conslo/badlink
$ cd $GOPATH/src/github.com/conslo/badlink
$ go install
$ go test
```
1. What did you expect to see?

```
PASS
ok      github.com/conslo/badlink       0.001s
```
1. What did you see instead?

```
# testmain
/usr/local/go/pkg/tool/linux_amd64/link: cannot open file /usr/local/go/pkg/linux_amd64/github.com/conslo/badlink.a: open /usr/local/go/pkg/linux_amd64/github.com/conslo/badlink.a: no such file or directory
FAIL    github.com/conslo/badlink [build failed]
```

@davecheney and I have already had a bit of a back and forth on this already on golang-nuts (I'll avoid actually requiring anyone to read this, but for attribution sake it's [here](https://groups.google.com/forum/#!topic/golang-nuts/OAQzIysNSuU)). It seems if I replace the dot import in the test file (`badlink_test.go`):

``` Go
import "."
```

with a full import:

``` Go
import "github.com/conslo/badlink"
```

It fixes it. However the dot import did (and still does) work in 1.5.3.

Dave thinks the dot import should be a compiler error. I agree. However I'm a bit confused as to the state of relative imports in go. I held they were [a deliberate omission](https://github.com/golang/go/issues/3515#issuecomment-66066361), but there's mention of [limited support](https://github.com/golang/go/issues/6147#issuecomment-94483157) which I don't know the details of. And again, this _does_ work in 1.5.3, so unless I screwed something else up (repeatedly, on different machines) this is a regression.

Possibly related?:
https://github.com/golang/go/issues/14609

For the record, I don't generally like relative imports, but saw the dot import in tests at a talk and thought that it seemed like a nice exception. A way for a `_test` package to say "I'm testing myself". But I'd be happy if this was just a more clear error.

**Comment by rsc** [comment]
`import "."` should not work. The error here should be changed to something like "cannot import current directory". That's probably still doable for Go 1.7.

**Comment by ianlancetaylor** [comment]
We actually have tests in `cmd/go/go_test.go` that verify that `import "."` works.  See https://golang.org/src/cmd/go/testdata/local/easysub/main.go .

**Comment by quentinmit** [comment]
@rsc In light of the explicit test to make sure this works, do we still want to continue to treat this as an error?

@ianlancetaylor If we have explicit tests for this, why are they not failing?

**Comment by conslo** [comment]
@quentinmit it works when you use `go run somefile.go`, but not with `go build`. Since the test in question has the `main.go` (package `main`) in the same folder as the `easysub` package it's importing, I imagine that's how it's being run.

**Comment by ianlancetaylor** [comment]
To be pedantically clear, it also works with `go build somefile.go` which is what cmd/go/go_test.go is testing.

**Comment by rsc** [comment]
All right, well if there are tests that it should work, then I guess it can stay. The error message here is not critical for Go 1.7.

**Comment by bradfitz** [comment]
The error message is now different at Go tip (as of 992ce90):

```
bradfitz@gdev:~/src/github.com/conslo/badlink$ go test
# github.com/conslo/badlink
badlink_test.go:6:2: local import "." in non-local package
FAIL    github.com/conslo/badlink [setup failed]
```

But still not critical.
