### ISSUE TITLE
Undefined Reference to Pastry

### ISSUE THREAD

**Issue by sharayuS** [golang/go#14686]
My code-

package pastry

import "fmt"

func main() {
    fmt.Printf("hello, world\n")

id, err := https://github.com/edsrzf/pastry.NodeIDFromBytes([]byte("ubuntu"+" test server"))
if err != nil {
    panic(err.Error())
}
node := https://github.com/edsrzf/pastry.NewNode(id, "192.168.1.17", "192.168.252.1", "pune", 8080)
cluster := https://github.com/edsrzf/pastry.NewCluster(node, "123sharayu555")
}

Errors-
root@ubuntu:~/work/src/github.com/user/shello# go install github.com/user/shello# github.com/user/shello
./shello.go:8:12: error: reference to undefined name ‘pastry’
 id, err := pastry.NodeIDFromBytes([]byte("ubuntu"+" test server"))
            ^
./shello.go:12:9: error: reference to undefined name ‘pastry’
 node := pastry.NewNode(id, "192.168.1.17", "192.168.252.1", "pune", 8080)
         ^
./shello.go:13:12: error: reference to undefined name ‘pastry’
 cluster := pastry.NewCluster(node, "123sharayu555")

**Comment by bradfitz** [comment]
Please bring this to the mailing list or other forum. See https://golang.org/wiki/Questions

Thanks!
