### ISSUE TITLE
error: reference to undefined name ‘pastry’

### ISSUE THREAD

**Issue by jayashree-saraf** [golang/go#14682]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/386

2. What operating system and processor architecture are you using (`go env`)?
ubuntu 14.04

I have written this code to create a local node in pastry(peer to peer network):

package main

import "fmt"

func main() {
	id, err := pastry.NodeIDFromBytes([]byte("ubuntu"+" test server"))
if err != nil {
    panic(err.Error())
}
node := pastry.NewNode(id, "192.168.139.1", "192.168.252.1", "pune", 8080)
}

errors generated:
./pastry.go:2:1: error: redefinition of ‘main’
 func main() { 
 ^
./hello.go:5:1: note: previous definition of ‘main’ was here
 func main() {
 ^
./hello.go:6:13: error: reference to undefined name ‘pastry’
  id, err := pastry.NodeIDFromBytes([]byte("ubuntu"+" test server"))
             ^
./hello.go:10:9: error: reference to undefined name ‘pastry’
 node := pastry.NewNode(id, "192.168.139.1", "192.168.252.1", "pune", 8080)
         ^
./pastry.go:3:12: error: reference to undefined name ‘pastry’
 id, err := pastry.NodeIDFromBytes([]byte("ubuntu"+" test server"))
            ^
./pastry.go:7:9: error: reference to undefined name ‘pastry’
 node := pastry.NewNode(id, "192.168.139.1", "192.168.252.1", "pune", 8080)
         ^

**Comment by Thomasdezeeuw** [comment]
You need to import the `pastry` package to use it. And you seem to have two main functions, which isn't allowed.

**Comment by bradfitz** [comment]
Please bring this to the mailing list or other forum. See https://golang.org/wiki/Questions

Thanks!
