### ISSUE TITLE
website: release history links to missing "Go1.5.3" milestone

### ISSUE THREAD

**Issue by rhysh** [golang/go#14687]
The [release history](https://golang.org/doc/devel/release.html#go1.5.minor) page links to the [Go1.5.3](https://github.com/golang/go/issues?q=milestone%3AGo1.5.3) milestone on GitHub, which does not currently exist. I'd expect the milestone to be available for viewing, or to not be linked from the release notes.

Of the 23 released versions of Go (go1, go1.0.1, ..., go1.6), 21 have matching milestones on GitHub. The Go1.2.2 and Go1.5.3 milestones are missing, though I don't know of any links to the former.

Has the milestone been intentionally removed?

**Comment by bradfitz** [comment]
The things that were going to become Go1.5.3 were bumped to Go1.5.4 (https://github.com/golang/go/issues?q=milestone%3AGo1.5.4) so Go1.5.3 would be purely a security release. But the commit for Go 1.5.3 never had an issue with that label. 

They were backports of #13907 and #13515 (both Milestone Go 1.6)

**Comment by bradfitz** [comment]
See https://github.com/golang/go/commits/release-branch.go1.5

**Comment by rhysh** [comment]
Thanks for the backstory and links, Brad. Should there be separate placeholder issues for the two math/big bugs so they can be referenced by the Go1.5.3 milestone? That seems almost gratuitous.
