### ISSUE TITLE
os/user: warning building on mac

### ISSUE THREAD

**Issue by robpike** [golang/go#14696]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +8969ab8 Mon Mar 7 22:41:22 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

mac osx 10.11.3 

 gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

3. What did you do?

./make.bash. I am now seeing

os/user/lookup_unix.go:43:35: warning: passing 'gid_t *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/unistd.h:653:43: note: passing argument to parameter here

**Comment by bradfitz** [comment]
Ross, can you take a look? I see the same thing on my mac.

(To be clear, it's a compiler warning during make.bash, not a fatal error, which is probably why we didn't catch it; C warnings are basically the only warnings that exist and are allowed to spam in a Go build)

**Comment by zombiezen** [comment]
Taking a look now. For the future, should the build bots (or at least, try bots) error on C warnings?

**Comment by bradfitz** [comment]
@zombiezen, that is the topic of #14698
