### ISSUE TITLE
cmd/dist: should C warnings cause make.bash to fail?

### ISSUE THREAD

**Issue by josharian** [golang/go#14698]
The warning described in #14696 did not cause the build to fail. Should it have?

cc @bradfitz for opinions.

**Comment by bradfitz** [comment]
I'd be in favor of making C warnings fatal during make.bash.

@robpike, @rsc, @ianlancetaylor ... ?

**Comment by bradfitz** [comment]
Then again, C compilers add warnings all the time, and we were already bitten by that recently with https://github.com/golang/go/commit/a527bdbda39c48fa772d8d54eb6b849f240442c1 for #12345

**Comment by bradfitz** [comment]
Talking to myself, maybe we only make them fatal for dev builds, or only when run under the builders, so end users with release builds are never affected by the latest and greatest C warnings added in C compilers newer than what we used during development.

**Comment by josharian** [comment]
I like it.

**Comment by robpike** [comment]
SGTM

**Comment by alexbrainman** [comment]
SGTM

Alex

**Comment by bradfitz** [comment]
Gopherbot never mentioned this, probably because it says Do Not Review, but: https://go-review.googlesource.com/#/c/23005/
