### ISSUE TITLE
fmt wrongly detects type of list item in []interface{} as another []interface{} instead of interface{}

### ISSUE THREAD

**Issue by ProhtMeyhet** [golang/go#14695]
1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
amd64 / linux

3. What did you do?
https://play.golang.org/p/aPx9TXrNaQ

4. What did you expect to see?
[]interface {}, interface {} = test

5. What did you see instead?
[]interface {}, []interface {} = [test]

as you can see it's a bit tricky to hit as - what i can see - there's a need to totally loose the original type information via a struct.

the compiler however is correct in this case, as if you uncomment lines 27 - 29 you get a compile time error:

prog.go:27: cannot range over ss (type interface {})

**Comment by bradfitz** [comment]
Let's move this to a forum. See https://golang.org/wiki/Questions

The type of `atype ...interface{}` is indeed `[]interface{}`.

**Comment by ProhtMeyhet** [comment]
but why is there a difference between the compiler and fmt?

**Comment by bradfitz** [comment]
There is no difference. The compiler's error message is correct.

Let's move this to a forum and discuss there.

**Comment by ProhtMeyhet** [comment]
but i said it's not a compiler bug, but a bug in fmt.

**Comment by bradfitz** [comment]
It's also not a bug in fmt.
