### ISSUE TITLE
Failed building 1.6 from source on docker

### ISSUE THREAD

**Issue by waghanza** [golang/go#14693]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

**go** version `1.4` in order to build **go** `1.6`

2. What operating system and processor architecture are you using (`go env`)?

+ **GOOS** `linux`
+ **GOARCH** `amd64`

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

4. What did you expect to see?

~~~sh
--- FAIL: TestHostname (0.00s)
	os_test.go:1287: fork/exec /bin/hostname: no such file or directory
--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
	exec_linux_test.go:34: Failed to stat /proc/self/ns/user: stat /proc/self/ns/user: permission denied
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
	exec_linux_test.go:34: Failed to stat /proc/self/ns/user: stat /proc/self/ns/user: permission denied
--- FAIL: TestEmptyCredGroupsDisableSetgroups (0.00s)
	exec_linux_test.go:34: Failed to stat /proc/self/ns/user: stat /proc/self/ns/user: permission denied
~~~

5. What did you see instead?

I expect those test run

**Comment by bradfitz** [comment]
This isn't enough information to help you.

What does "on Docker" mean? In a Docker container? Where is your Dockerfile?

**Comment by waghanza** [comment]
sorry, there is my dockerfile
my purpose is to build from a clean env (could be a **Vagrant** on a **VirtualBox**)
~~~dockerfile
FROM fedora:latest
MAINTAINER waghanza@gmail.com

RUN dnf -y update
RUN dnf -y install @development-tools @rpm-development-tools git golang

RUN dnf -y install wget
RUN wget -O /tmp/go.tgz https://storage.googleapis.com/golang/go1.4.3.linux-amd64.tar.gz
RUN mkdir /root/go1.4
RUN tar -xvzf /tmp/go.tgz -C /root/go1.4
ENV GOROOT_BOOTSTRAP /root/go1.4/go
RUN echo localhost > /etc/hostname

RUN git clone https://go.googlesource.com/go /opt/go

RUN cd /opt/go && git tag | sort -V | grep -v -E 'weekly|release|beta|rc' | tail -n1 | xargs git checkout
~~~

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/20342 to skip more tests.
