### ISSUE TITLE
golang.org is not available for developers from Iran

### ISSUE THREAD

**Issue by RezaSeyf** [golang/go#14707]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
mac os x 10.9.5

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)
I want to download golang package for mac os x from an ISP in Iran using golang.org

4. What did you expect to see?
I expect to see that golang is available for developers from Iran. 
You call golang "open-source" that it means its OPEN for anybody. we are developers too. 

5. What did you see instead?
403. That’s an error.
Your client does not have permission to get URL / from this server. (Client IP address: xxx.xxx.xxx.xxx)
We're sorry, but this service is not available in your country. That’s all we know.

**Comment by Thomasdezeeuw** [comment]
Dup of #7392 and #12380.

**Comment by RezaSeyf** [comment]
so what is the solution for this issue?

**Comment by Thomasdezeeuw** [comment]
From what I understand there is none. The Iranian government doesn't allow for encryption stuff to be accessed. And Google is following the law.

Maybe try a VPN or get a copy of go in some other way and use godoc to host it locally.

PS. I'm not from Google, but that's what I understood from the other bugs.

**Comment by ianlancetaylor** [comment]
Closing as duplicate.
