### ISSUE TITLE
http.Server: memory corruption with computed Addr

### ISSUE THREAD

**Issue by asquare** [golang/go#14701]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version go1.6 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/.../ws/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

```
package main

import (
	"log"
	"net/http"
)

const (
	port = 9900
)

func main() {
	server := http.Server{Addr: ":" + string(port), Handler: nil}
	log.Fatalf("error listening on port %d: %v\n", port,
		server.ListenAndServe())
}
```

4. What did you expect to see?

server listening on specified port

5. What did you see instead?

see below - note the unexpected character after 'tcp/'

```
2016/03/07 17:29:22 error listening on port 1337: listen tcp: lookup tcp/Թ: nodename nor servname provided, or not known
2016/03/07 17:31:03 error listening on port 9900: listen tcp: lookup tcp/⚬: nodename nor servname provided, or not known
```

the problem goes away if Addr is specified as ":9900" and not computed by adding two strings

**Comment by davecheney** [comment]
This is not a bug, you are printing the rune value of the code point 9000.

http://play.golang.org/p/8JuZdffaAo

You probably want something like fmt.Sprintg(":%d", port)

Let's move this to a forum. See https://golang.org/wiki/Questions
