### ISSUE TITLE
cover: broken error message

### ISSUE THREAD

**Issue by davelondon** [golang/go#14716]
1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
The following test fails:

```
func TestName(t *testing.T) {
	const filename = "/tmp/file.txt"
	ioutil.WriteFile(filename, []byte("mode: set\nfoo"), 0644)
	defer os.Remove(filename)
	_, err := cover.ParseProfiles(filename)

	if strings.HasPrefix(err.Error(), "line [] doesn't") {
		t.Fatal("Error message does not mention line contents:", err.Error())
	}
}
```

... the error should read "line [foo] doesn't...". I fixed it and submitted a CL a while ago, but I don't want to disturb the core devs from their important work for such a small bug. https://go-review.googlesource.com/#/c/19330/

**Comment by ianlancetaylor** [comment]
Thanks, I submitted your CL.  Please feel free to ping a CL that gets no response.  In your case you sent the CL in the middle of the 1.6 release push, and it just got dropped.
