### ISSUE TITLE
cmd/compile: fix bounds check regressions from Go 1.6

### ISSUE THREAD

**Issue by rsc** [golang/go#14721]
The old compiler knows that

	var x [16]byte
	z := x[i&15]
	z := x[i%16]
	...
	
does not need bounds checks. We need to make sure that the new SSA compiler knows this too. Today it seems not to, in certain cases.

Per discussion today.

**Comment by randall77** [comment]
Note that [i%16] can only skip the bounds check if i is unsigned (or can otherwise be proved >= 0).

**Comment by brtzsnr** [comment]
The first one can be done with rewrites easily. Something like.

(IsInBounds (And64 (Const64 [c]) x) (Const64 [d])) && c < d -> (ConstBool [1]).

Is something more general than this you have in mind?

**Comment by rsc** [comment]
I have no implementation in mind. I just don't want Go 1.7 to regress
compared to Go 1.6 on any eliminated bounds checks. Thanks.

(I know it's eliminating new ones. I just want to make sure we don't lose
any old ones.)
