### ISSUE TITLE
crypto/tls: timeout tests

### ISSUE THREAD

**Issue by randall77** [golang/go#14722]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

tip

2. What operating system and processor architecture are you using (`go env`)?

linux/amd64

3. What did you do?

run the crypto/tls tests.  Occasionally, I get the error:

--- FAIL: TestDialTimeout (0.01s)
	tls_test.go:192: resulting error not a timeout: dial tcp 127.0.0.1:49575: i/o timeout

The test used to detect whether an error is a timeout is to look for the string "timed out" in the error string.  Maybe we should include "timeout" also?

**Comment by bradfitz** [comment]
I can't reproduce but I sent https://go-review.googlesource.com/20403 which at least also still passes for me and will fail with more info if it continues to flake for you.
