### ISSUE TITLE
Request: make src/go/types/gotype.go go-gettable (as x/tools/cmd/gotype was).

### ISSUE THREAD

**Issue by alecthomas** [golang/go#14727]
As discussed in #12703, `x/tools/cmd/gotype` is deprecated since 1.6 and its replacement (`src/go/types/gotype.go`) is no longer go-gettable.

gotype was very useful for interactive linters in text editors (see below). It is the only "linter" that picks up a certain class of errors (like misspelt keywords). Without it, these errors go unreported.

Using the compiler itself for inline linting is not ideal, as you generally don't want to generate artifacts. Additionally it may result in quite lengthy linting times under some circumstances (uncompiled dependencies).

I could simply copy `gotype.go` into its own repository and go get that, but that has ongoing maintenance issues. I'd prefer not to do this.

Please consider making `gotype` go-gettable again. Thanks!

---

Linters using gotype:
1. [Syntastic (VIM)](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/gotype.vim)
2. [SublimeLinter](https://packagecontrol.io/packages/SublimeLinter-contrib-gotype)
3. [Atom](https://atom.io/packages/linter-gotype)

Also, any editor linter using [gometalinter](https://github.com/alecthomas/gometalinter) also relies on this functionality, including [Emacs flycheck](https://github.com/favadi/flycheck-gometalinter) and many others.

**Comment by griesemer** [comment]
Would it be sufficient to keep an updated version of gotype in x/tools/cmd/gotype (that is based on the latest std repo go/types)?

**Comment by alecthomas** [comment]
The only issue is that gotype would stop working for people using &lt; 1.6. Another option might be to expose it under `go tool type ...`?

**Comment by alecthomas** [comment]
(though I guess you could make x/tools/cmd/gotype continue to work with all versions with some build tag magic)

**Comment by griesemer** [comment]
Even if it were exposed under go tool type (which we probably don't want) it would stop working for people using < 1.5 (go/types moved to the std repo for 1.5, not 1.6). We very much want to delete x/tools/go/types. This seems unrelated to gotype being go-gettable.

I am proposing we have x/tools/cmd/gotype and that it requires 1.5 or higher. Would that resolve the issue?

(People depending on x/tools compiling against 1.4 will need to vendor.)

**Comment by alecthomas** [comment]
Sure, that works for me.

**Comment by kostya-sh** [comment]
`x/tools/cmd/gotype` now uses `go/types`. I guess it means that it is no longer deprecated ;)

`src/go/types/gotype.go` file is identical to `x/tools/cmd/gotype/gotype.go` + `x/tools/cmd/gotype/doc.go` except docs in x being slightly more accurate. I suggest to delete it and close this issue.

**Comment by bradfitz** [comment]
Yup, this looks fixed as of https://go-review.googlesource.com/20810
