### ISSUE TITLE
cmd/compile: ssa fails to flush return values during deferred func

### ISSUE THREAD

**Issue by rsc** [golang/go#14725]
Reduced from a bug in cmd/doc found by @robpike.
/cc @khr @dr2chase

The -ssa=0 behavior is correct: the program should print 1, not 0.

```
$ go run -gcflags -ssa=0 /tmp/x.go
1
$ go run /tmp/x.go
0
$ cat /tmp/x.go
package main

func main() {
	println(f())
}

func f() (x int) {
	for {
		defer func() {
			recover()
			x = 1
		}()
		panic(1)
	}
}
$ 
```

**Comment by randall77** [comment]
Upon further investigation, this seems unrelated to #14591.  It looks like x is allocated on the heap and we never copy the heap value back to the stack at the end of the function (after deferreturn).
