### ISSUE TITLE
x/tools/cmd/guru: whicherrs doesn't always output something useful

### ISSUE THREAD

**Issue by dominikh** [golang/go#14736]
The following query should probably output something saying that there's no useful information, or that the error is always nil:

```
$ cat $GOPATH/src/foo/foo.go
package main

func foo() error { return nil }

func main() {
    err := foo()
    _ = err
}
$ guru -scope foo whicherrs $GOPATH/src/foo/foo.go:\#64
$
```

Similarly, the following query should either say that there are no useful information, or that there are errors returned that aren't global variables:

```
$ cat $GOPATH/src/foo/foo.go
package main

import "errors"

func foo() error { return errors.New("an error") }

func main() {
    err := foo()
    _ = err
}
$ guru -scope foo whicherrs $GOPATH/src/foo/foo.go:\#100
$
```

/cc @alandonovan @DanielMorsing

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete.
