### ISSUE TITLE
net: TestDialerFallbackDelay fails when no external IPv6 connectivity

### ISSUE THREAD

**Issue by mikioh** [golang/go#14731]
For example, 
```
go test -v -run=TestDialerFallbackDelay
--- FAIL: TestDialerFallbackDelay (0.00s)
	dial_test.go:477: #1: got 378.549µs; want >= 199ms
	dial_test.go:477: #2: got 440.764µs; want >= 299ms
FAIL
```
Looks like it requires -ipv6 flag.

**Comment by pmarks-net** [comment]
I see the problem. `slowDialTCP` interprets a zero deadline as "don't wait", rather than "wait forever".

You can reproduce the bug on a dual-stack Linux machine by running:

    $ sudo ip -6 route add unreachable 2001:2::254
    $ ../bin/go test -v net -run TestDialerFallbackDelay
