### ISSUE TITLE
encoding/json: add Encoder option to control escaping behavior

### ISSUE THREAD

**Issue by cyberphone** [golang/go#14749]
1. What version of Go are you using? `5.3`

2. What operating system and processor architecture are you using? `amd64,windows`

3. What did you do?
```go
package main

import "fmt"
import "encoding/json"

func main() {
    mapD := map[string]string{"trouble": "</script>"}
    mapB, _ := json.Marshal(mapD)
    fmt.Println(string(mapB))
}
```

4. What did you expect to see?
<code>{"trouble":"&lt;/script&gt;"}</code>

5. What did you see instead?
<code>{"trouble":"\u003c/script\u003e"}</code>

Related: https://github.com/golang/go/issues/14135

Comment: In my JSON implementation for Java, I have made JavaScript serialization an *option*.  When supplied as JavaScript the above does not break signatures (JSON.stringify() performs the normal serialization), but "on the wire" you should IMHO always use ES6: https://mailarchive.ietf.org/arch/msg/json/I2dF4osWAUlvax48WTxnAei3ldQ

**Comment by minux** [comment]
JSON is not originally defined by ES6, and the current serialization
is perfectly valid JSON, so why should we change?

Also, the current behavior fixes a security concern where a browser
that incorrectly sniffs content might be tricked to interpret a JSON
document as HTML.

**Comment by odeke-em** [comment]
The reason for this behavior is explained here https://golang.org/pkg/encoding/json/#Marshal
<img width="881" alt="screen shot 2016-03-10 at 3 16 55 pm" src="https://cloud.githubusercontent.com/assets/4898263/13687912/2ab1b900-e6d3-11e5-8b6c-51fa82a48d0c.png">

For the time being if this issue is blocking you, please see http://stackoverflow.com/a/25923407.

**Comment by cyberphone** [comment]
Yes, this is perfectly legal JSON but hardly no other JSON serializer does this.

The use case for following ES6 is enabling "crypto safe" JSON/JavaScript that can travel between different systems without getting corrupted:
https://cyberphone.github.io/openkeystore/resources/docs/jsonsignatures.html

The best solution to this problem is offering different options/modes for serialization which I did in my Java implementation:
https://github.com/cyberphone/openkeystore/blob/master/library/src/org/webpki/json/JSONOutputFormats.java
It wasn't very difficult :-)

**Comment by bradfitz** [comment]
Let's make this bug about adding a method on json.Encoder to change its quoting behavior. The default will be unchanged.

(a method similar to https://golang.org/pkg/encoding/json/#Decoder.UseNumber or https://tip.golang.org/pkg/encoding/json/#Encoder.Indent)

**Comment by cespare** [comment]
I can send a CL. (Or does this need more buy-in first?)

**Comment by bradfitz** [comment]
Send a CL. It has a valid use case for JSON signing, etc.
