### ISSUE TITLE
typo in https://golang.org/pkg/net/http/#ServeFile documentation

### ISSUE THREAD

**Issue by yansal** [golang/go#14755]
> What version of Go are you using (`go version`)?

Any

> What operating system and processor architecture are you using (`go env`)?

Any

> What did you do?

Visit https://golang.org/pkg/net/http/#ServeFile

> What did you expect to see?

_If the provided file or direc**t**ory name is a relative path_

> What did you see instead?

_If the provided file or direcory name is a relative path_

**Comment by bradfitz** [comment]
> > What version of Go are you using (go version)?
> Any

Actually, not "any" because this has already been fixed at tip.
