### ISSUE TITLE
proposal: crypto, hash: add WriteString support

### ISSUE THREAD

**Issue by josharian** [golang/go#14757]
Add WriteString to crypto/sha1, crypto/sha256, hash/crc64, etc. Similar to #11805. Probably easy pickings.

**Comment by sctb** [comment]
Initial CL submitted. I expect it's not quite there yet; glad to make any changes necessary.

**Comment by minux** [comment]
My thought on this issue:

If you want high performance hashing, then using strings
is very probable already a mistake (the string must come
from somewhere else, so it gets converted from []byte in
the first place.) But if the string does not come from outside
(I/O), then it's still better to use []byte directly.

Could you please given a real scenarios where you want
WriteString support on a crypto.Hash while still care about
the utmost performance?

While I agree that WriteString support on io.MultiWriter is fine,
adding WriteString support to all io.Writer implementations
doesn't look necessary esp. if doesn't bring enough
performance improvement.

**Comment by josharian** [comment]
I think you're probably right. Before abandoning this, I'd like to do a bit of research in my Go corpus, but that might take a while.

**Comment by Scratch-net** [comment]
Having WriteString might indirectly suggest using it to hash passwords, which is a very, very bad idea.

**Comment by rsc** [comment]
I am very skeptical of an unsafe implementation of WriteString here.
Even the one in os.File is not unsafe - it does Write([]byte(s)).
I don't believe crypto should set a precedent that "unsafe is OK if it's for performance",
for others to follow.

**Comment by rsc** [comment]
Based on the discussion above (and the general lack of interest over 4 years), this seems like a **likely decline**.

Leaving open for a week for final comments.

**Comment by rsc** [comment]
No change in consensus, so declined.

**Comment by rsc** [comment]
Over on #38776 we realized that WriteString can be added without requiring use of unsafe, so maybe we should do that. WriteString is now included in #38776.
