### ISSUE TITLE
tour: The "count each word" exercise should be clarified that case insensitivity is in effect.

### ISSUE THREAD

**Issue by omulmo** [golang/go#14752]
Context: https://tour.golang.org/moretypes/20

See above.

**Comment by omulmo** [comment]
Bah. Negations... I meant it the other way around.

The exercise is set up to count "The" and "the" as if they were two different words. Either the test suite should allow for an alternative solution, where the student makes use of strings.ToLower(), or make a note in the instructions about case sensitivity.

**Comment by ALTree** [comment]
Tour issues are tracked in the tour repo. I've migrated this issue there as https://github.com/golang/tour/issues/370. Closing here.
