### ISSUE TITLE
runtime: Go function call is hanging forever in C child process.

### ISSUE THREAD

**Issue by orange881217** [golang/go#14767]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version go1.6 linux/amd64`

`gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ams2/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

[my example program](https://github.com/orange881217/go_fork_test)

4. What did you expect to see?

I wanna call Go function in C child process

5. What did you see instead?

I'd like to call Go function from C program as like a static library. and I was trying to make my C daemon program using fork(). but as you see in my `_main.c` code(in my reop), Go function call hanging forever in child process.

Thank you in advance for your help.

**Comment by ianlancetaylor** [comment]
In general fork does not work with multi-threaded processes, and Go programs are always multi-threaded.  A simple fork/exec that does not call any Go code between fork and exec should work.  An attempt to call Go code after fork will generally fail, as you are seeing.

There is really no way to fix this, so I am going to close this issue.  If you want to discuss this, please use a forum, not the issue tracker; see https://golang.org/wiki/Questions.
