### ISSUE TITLE
cmd/go: go get: is there any way that 'go get' can retrieve packages which have no buildable go source files

### ISSUE THREAD

**Issue by hongjianzhu** [golang/go#14764]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

darwin/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

i have a package that it can generate some go source files using txt/template. Without initial makefile, it can't build at all which i intend to that.

4. What did you expect to see?

it's just download package itself, without compile or build

5. What did you see instead?

package XXX: no buildable Go source files in ...

ps: go get -d also fails ...

**Comment by ianlancetaylor** [comment]
If the package has no Go files, then you can't import it, so you have to use `go get -d`.  You say that `go get -d` fails; how does it fail?

**Comment by minux** [comment]
I think go get / go get -d can download anything if the
SCM is supported.

They will give out the error "no buildable Go source files",
but the content is still correctly cloned to $GOPATH.

**Comment by hongjianzhu** [comment]
@ianlancetaylor @minux 

thanks~

my scenario is using Makefile to build/deploy go projects.
the Makefile file contents may looks like:

```
init:
    go get -u github.com/xx/yy
    go get github.com/aa/bb
```

if i want to build the project, i can simply type "make init". BUT, if the command "go get github.com/aa/bb" fails, it will break the process of making. although i can use "make -i init", but as a programmer, it feels uncomfortable to see any exceptions.😂

i want to know or as a suggestion, if go can provide any callbacks of cmd/go tools, so we can register some events to do specified functions

**Comment by davecheney** [comment]
go get is just a wrapper around git clone, why not call git clone explicity
?

**Comment by rsc** [comment]
That's really not what go get is for. Probably git clone is your best bet.
