### ISSUE TITLE
godoc.org: there is no bugs link

### ISSUE THREAD

**Issue by kortschak** [golang/go#14765]
1. What version of Go are you using (`go version`)?
This is a godoc.org issue, so whichever version gddo is running at the moment (go1.6?)

2. What operating system and processor architecture are you using (`go env`)?
This is a godoc.org issue, probably linux.

3. What did you do?
Browse to https://godoc.org/encoding/xml and compare with https://golang.org/pkg/encoding/xml/

4. What did you expect to see?
A link reasonably high up on the page linking to the single BUG section.

5. What did you see instead?
No link.

It would be nice to either reflect the behaviour of golang.org/pkg, or IMO preferably have a link next to "Index | Examples | Files".

**Comment by adg** [comment]
This should be reported on the golang/gddo issue tracker.

**Comment by adg** [comment]
https://github.com/golang/gddo/issues/new
