### ISSUE TITLE
path.Base() does not split path properly on Windows 10

### ISSUE THREAD

**Issue by mynameismevin** [golang/go#14763]
* What version of Go are you using (`go version`)?

```
>go version
go version go1.6 windows/amd64
```

* What operating system and processor architecture are you using (`go env`)?

```
>go env
set GOARCH=amd64
set GOBIN=C:\Users\<user>\Development\GoSource\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\<user>\Development\GoSource
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

* What did you do?

The [documentation](https://golang.org/pkg/path/#Base) gives an example on the expected behaviour of `path.Base()`, however, it does not actually split the trailing path element. Also, `path.Base()` duplicates the `\` in the path.

```go
package main

import (
	"fmt"
	"path"
	"strings"
)

func main() {
	base := `c:\users\username`
	fmt.Println(path.Base(base))
	fmt.Println(fmt.Sprintf("%q\n", strings.SplitAfter(base, `\`)))
	lines := strings.SplitAfter(base, `\`)
	fmt.Println(lines[len(lines)-1])
}
```

* What did you expect to see?

The expected behaviour should be consistent with the [documentation examples](https://golang.org/pkg/path/#Base); `path.Base()` should return the trailing path element.

* What did you see instead?

`path.Base()` returns the full path instead of the final path element.

**Comment by mattn** [comment]
Please use path/filepath instead of path for filesystems.

**Comment by mynameismevin** [comment]
What is the difference? Is it just OS specific differences?

**Comment by bradfitz** [comment]
See https://golang.org/wiki/Questions
