### ISSUE TITLE
Documentation: Effective Go Defer section incorrectly states when defer is executed 

### ISSUE THREAD

**Issue by kkruups** [golang/go#14769]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
All versions

2. What operating system and processor architecture are you using (`go env`)?
N/A

3. What did you do?
Read two articles which describe defer behavior.  The first article is the Effective Go section on Defer  ( https://golang.org/doc/effective_go.html?h=defer ) and second is the " Go Blog" article, "Defer, Panic, and Recover"  ( http://blog.golang.org/defer-panic-and-recover ).  

There is a discrepancy between these two pieces of documentation on how defer behaves in Surrounding Function(Calling Function) with respect to the return statement of the Surrounding Function.   "Effective Go" article states defer statement defers the execution immediately before the return of Surrounding Function and the "Go Blog" article states the exact opposite, the defer statement defers the execution of the function after the return of the Surrounding Function.

If possible, provide a recipe for reproducing the error.

The Go Blog article accurately describes the defer execution behavior. Ran the demo code which proves the deferred function, anonymous function, is called after return of surrounding function c() in this case.
http://play.golang.org/p/FqVdPx_leT

4. What did you expect to see?
Correct the Effective Go Defer  documentation section.
I expect to see the Effective Go section on Defer to describe the correct behavior as detailed in the Go Blog article, Panic, Recover and Defer which is "the defer statement defers the execution of the deferred function after the return of the Surrounding Function".

5. What did you see instead?

Defer

Go's **defer statement schedules a function call (the deferred function) to be run immediately before the function executing the defer returns.** It's an unusual but effective way to deal with situations such as resources that must be released regardless of which path a function takes to return. The canonical examples are unlocking a mutex or closing a file.

**Comment by minux** [comment]
I don't think before/after "return" makes much distinction
here. And you can't write a program to distinguish these
two cases either.

In your example, i++ could also be treated as executed
after the function returns but before the Print call executes.

Technically it's before the return, but that's not differentiable
from Go code.

**Comment by kkruups** [comment]
Hi Minux,

Clearly the language is wrong and is completely opposite of blog article. Minux you got wrong the context is not the applications main function.  It is the c( ) function the deferred function is in. From that context the the deferred function clearly returns after the deferred anonymous function. The value would have been equal to 1 from c( ) method return, but it is not it is 2, because the value was changed after the return of the c ( ) function which is not a deferred function but does have a deferred function embedded.

Please use the correct point of reference to understand this subtle difference.  That is why the Effective Go Defer section needs to be revised.  The behavior is clearly contrary to what is stated and the  go Blog has it dead write.

Please update documentation to help others avoid this confusion.

BR/KK

**Comment by minux** [comment]
In http://play.golang.org/p/FqVdPx_leT, you can't tell whether
the deferred function in c() runs before or after the c() function
returns because at long as the deferred function runs before
the call to fmt.Println at line 16 , the external behavior is the
same.

Also note that "before the return" does not mean "before the
execution of the return statement", which is false. The return
here means the transferring of execution to the called function.

**Comment by mdempsky** [comment]
For what it's worth, the Go spec uses the same "immediately before the function returns" wording as Effective Go: https://golang.org/ref/spec#Defer_statements

/cc @adg @campoy

**Comment by carlmjohnson** [comment]
What's going on in the example doesn't have to do with "when" the deferred function runs. It has to do with where the return value is being stored.

For example, [this code](http://play.golang.org/p/0AkPss0fLo) behaves differently than the prior example:

```go
func c() (i int) {
	j := 1
	defer func() { j++ }()
	return j
}
```

`i` is the name of a slot in the stack that is owned by the caller and `j` is the name of a slot owned by the callee. `return 1` means "copy the value of 1 into the location of `i`, so the `i++` has an effect on it.

**Comment by kkruups** [comment]
Hi Minux,

http://play.golang.org/p/1BkdgghXrA
Would be safe to say that if an output statement is executed in c() after the deferred function's output statement is executed we can clearly see that the deferred function clearly runs after the caller function (this normally how we would demonstrate the order of execution of normally nested functions).  

From what I understood, in Russ Cox article,"[Broken abstractions in Go](http://research.swtch.com/goabstract)" is what is actually occuring is in fact a rewinding of the Call instruction, calling the defer instruction after the Caller then returning back to caller (see excerpt below). 

Excerpt: "....Well, the assembly trampoline jmpdefer has one more abstraction breaker up its sleeve. It subtracts five—the size of CALL instruction that invoked deferreturn—from the return address on the stack before jumping to fn, so the deferred function returns not to the instruction after the CALL, as it normally would, but back to the CALL itself. That is, subtracting five turns the CALL instruction into a loop. The only way out of the loop is for deferreturn to find no work left for this call frame and return normally, without calling jmpdefer. This subterfuge avoids the need to write a loop at the end of every function with a defer statement."

So it would appear we are both correct, but it would be more accurate language to describe the behavior as the Go  Blog article, "... the defer statement defers the execution of the function after the return of the Surrounding Function" since this behavior clearly explains the what is being observed.

**Comment by minux** [comment]
No, I don't think Russ' article means the deferred functions
are called after the deferring function returns.

The deferred functions are tail called by runtime.deferreturn,
which manipulates the return PC so that when the deferred
function returns, it will call the runtime.deferreturn function
again, but all these magic happens before the deferring func
returns. That is, before the RET instruction of the deferring
function. To put it another way, the rewinding of the call
instruction is for the runtime.deferreturn function call, not
the call instruction that calls the deferring instruction which
still is inside the deferring function.

As I argued above, there is no way to know if the deferred
functions are called before or after executing the deferring
functions' RET instruction in pure Go.

For example, another way to implement the defer mechanism
is to manipulate the return PC of the deferring function to
point to runtime.deferproc, and save the original return PC
in another place for all functions that calls defer. In this
alternative implementation, the deferred functions will be
called after the deferring function's RET instruction has
been executed.

As long as the deferred functions are called after the
returned values are updated and before the next instruction
in the calling function executes, it doesn't matter whether
it's before the return of the deferring function or after.

**Comment by kkruups** [comment]
Hi Minux,

Thank you for your thorough explanation.  Please clarify your final statement (bold below):

As long as the deferred functions are called after the
returned values are updated and **before the next instruction
in the calling function executes,** it doesn't matter whether
it's before the return of the deferring function or after.

By "before the next instruction in the calling function executes" do you  mean the RET instruction in the calling function or any expression prior to RET in caller?

i.e.  c( ){

**Comment by minux** [comment]
There are three functions involved:

func f() {
      print(g())
}

func g() (r int) {
      defer func () {
            r = 1
      } ()
      return 0
}

f is the calling function, g is the deferring function and the literal
function func () { r = 1 } is the deferred function.

What I mean by that statement is that as long as the deferred function
executes after assign 0 to r and before print(1) executes, it will meet the
language semantic. And the execution point can be before or after the
actual RET instruction executed by g.

I hope this is clear. Both expressions, although seems contradicting, are
valid.

**Comment by adg** [comment]
The wording in the language specification is canonical. If the blog post does not match the spec, then it should be revised.

**Comment by kkruups** [comment]
Hi Minux,

Thanks for the clarification.
I will close this issue.
However, ADG please revise the the Blog Article, since your the author, to correspond to Spec.


BR/KK
