### ISSUE TITLE
runtime: funcdata.h - GO_RESULTS_INITIALIZED produces a syntax error

### ISSUE THREAD

**Issue by millerresearch** [golang/go#14772]
The assembly macro GO_RESULTS_INITIALIZED (as documented in https://golang.org/doc/asm) produces a syntax error. Working in src/runtime:
```
cpu% cat resinit_arm.s
#include "funcdata.h"

TEXT resinit(SB),0,$0
    GO_RESULTS_INITIALIZED
    RET
cpu% go tool asm resinit_arm.s
resinit_arm.s:4: expected '(', found $
asm: assembly of resinit_arm.s failed
```
The definition of the macro in funcdata.h is:
`#define GO_RESULTS_INITIALIZED	FUNCDATA PCDATA $PCDATA_StackMapIndex, 1
`
Removing `FUNCDATA` and changing `1` to `$1` makes the syntax error go away, but I haven't been able to find documentation for these pseudo instructions so this is only guesswork.

**Comment by robpike** [comment]
Assigning to Russ. This is some runtime-internal magic and to the assembler it is just a black box. It is not an assembler bug, as far as I can tell.

**Comment by millerresearch** [comment]
That's right, it seems to be just a typo in funcdata.h (I've changed the issue title accordingly). Experimenting with compiler output suggests that the right definition is

`#define GO_RESULTS_INITIALIZED PCDATA $PCDATA_StackMapIndex, $1`

I'll offer this as a CL for Russ to check.
