### ISSUE TITLE
x/mobile/bind/objc: EXC_BAD_ACCESS when building for iOS

### ISSUE THREAD

**Issue by rpdprd** [golang/go#14778]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6, gomobile version +6fca37c Thu Mar 3 15:03:45 2016 +0000 (android,ios); androidSDK=

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/joesmith/Desktop/projects/sliceone/"
GORACE=""
GOROOT="/Users/joesmith/Desktop/go/1.6"
GOTOOLDIR="/Users/joesmith/Desktop/go/1.6/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Followed https://medium.com/@rakyll/calling-go-from-swift-be88709942c3, built the hello library. 

![Screenshot](https://cloud.githubusercontent.com/assets/17749775/13709917/5feb3ac2-e784-11e5-8057-58d1894aafe0.png)

It seems to work fine up to 988d17d203b37629f567701771685077ac5e1174, but 6fca37c69e243b777b0910e0fa6a32125159f4fc and beyond end up triggering the EXC_BAD_ACCESS error.

**Comment by eliasnaur** [comment]
Nasty. I can reproduce the crash only on an actual device if I force it to run armv7. It happens from an ObjC project as well. Perhaps it has something to do with #12896. Still investigating.

**Comment by eliasnaur** [comment]
CL 20261 should fix the issue for Go tip, and it might be included in a Go 1.6.1 release. In the meantime, Go 1.5 does seem to work on darwin/arm.
