### ISSUE TITLE
regexp.MatchString does not work as expected IMHO

### ISSUE THREAD

**Issue by d3ce1t** [golang/go#14779]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go1.6 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
Mac OS X 10.11.3
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

Match a string to a pattern by using regexp. MatchString behaviour is similar to FindString, where the left-most string matching the pattern is found. Because of this, a simple regex like the following does not work as expected:

```
var myRegex = regexp.MustCompile(`[A-Za-z0-9]+`)
result := myRegex.MatchString("hello goodbay")
fmt.Printf("Match? %v, Expected=false\n", result)
```

Link to code: http://play.golang.org/p/kV_MibkKFv

4. What did you expect to see?

After running above code, result variable gets a true value.

5. What did you see instead?

I would have expected to get false, like in other languages (e.g. Java)

**Comment by bradfitz** [comment]
It seems to work as documented and consistently between MatchString and FindString. FindString matches too: http://play.golang.org/p/YnL9JVDqmL

I'm not seeing a bug here, so let's move this to a forum. See https://golang.org/wiki/Questions.
