### ISSUE TITLE
range a map or slice, address of item is the last?

### ISSUE THREAD

**Issue by wchh** [golang/go#14788]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
all

3. What did you do?

https://play.golang.org/p/pr1eo1hiut

**Comment by bradfitz** [comment]
This is working properly. There is only one variable which varies per loop iteration.

Let's move this to https://golang.org/wiki/Questions if you want to discuss more.
