### ISSUE TITLE
cmd/compile: generate static data into fewer Progs

### ISSUE THREAD

**Issue by josharian** [golang/go#14786]
When compiling the `unicode` package, every single int in the static data (e.g. the RangeTables) gets its own Prog. (It also gets its own Node and Mpint, but that's another matter; see also #4617.) This blows through the Prog cache that @randall77 put into place and a lot more. Rather than generating a sequence of linked ADATA Progs and then writing them out, we should create fewer ADATA Progs containing more data, or maybe write it out even more directly like obj.Setuintxx.

I'm not sure how or where the right place to do this is. Advice welcomed.

**Comment by josharian** [comment]
For that matter, does data need to go into Progs at all?

**Comment by mdempsky** [comment]
I suspect there's no actual requirement anymore.

In particular, I notice there's already a TYPE_SCONST type that allows passing string values, but it's arbitrarily capped to 100 bytes in obj.savedata.  I suspect we could remove that restriction (and maybe allow To.Val to contain either []byte or string), and the compiler could cut down on a lot of Progs.

**Comment by mdempsky** [comment]
https://golang.org/cl/20607 generalizes cmd/internal/obj to support arbitrary length string constants and to update cmd/compile and cmd/asm to make use of them.  Seems to work.

**Comment by mdempsky** [comment]
I'm trying to benchmark CL 20607, but compilebench keeps giving me wildly noisy timings on my workstation.  Will try to test on some other machines.

@josharian BTW, what were you doing to measure how many Progs were generated and/or to determine that it was problematic?

**Comment by josharian** [comment]
I doubt that CL 20607 will address this directly; rather it lays one useful piece of groundwork. There'll also be work in sinit.go and elsewhere to use these newfound powers.

The Progs in unicode mostly get generated in sinit.go, func staticassign, case OSTRUCTLIT, call to gdata. gdata then jumps through a bunch of hoops (gc Gins, x86 gins, gc Prog, gc Naddr, etc.) and spits out a single Prog with a single int attached. Similar things happen throughout sinit.go.

To measure how many Progs were being generated, I just stuck some fmt.Printlns in "*Link".NewProg (cmd/internal/obj/util.go) for the new(Prog) branch that printed out ctxt.Cursym.Name and ran the output through [pct](https://github.com/josharian/pct).

**Comment by josharian** [comment]
Started.
