### ISSUE TITLE
cmd/compile: nowritebarrier not checked by SSA compiler

### ISSUE THREAD

**Issue by aclements** [golang/go#14784]
The `//go:nowritebarrier` and `//go:nowritebarrierrec` annotations in the runtime are not being checked in SSA mode.

For example, add `sched.gfree = sched.gfree` to any `go:nowritebarrier` function and compile the runtime. It should fail, but doesn't. Recompile with -gcflags -ssa=0 and it will correctly fail with "write barrier prohibited".

/cc @randall77 @dr2chase

**Comment by randall77** [comment]
The check is easy to add in.  But it is failing, SSA is generating a write barrier in runtime/mstkbar.go:208 where we store a slice to the heap:
```
	gp.stkbar = gp.stkbar[:len(gp.stkbar)+1]
```
When the frontend passes this assignment to SSA, it is marked as requiring a write barrier:
```
.   ASWB u(100) l(17067) tc(1)
.   .   DOTPTR u(2) l(17067) x(136+0) tc(1) assigned ARRAY-[]stkbar
.   .   .   NAME-runtime.gp u(1) a(true) g(2) l(17030) x(0+0) class(PPARAM) f(1) esc(no) tc(1) used(true) PTR64-*g
.   .   .   NAME-runtime.stkbar u(1) a(true) l(17067) x(0+0)
.   .   SLICE u(2) l(17067) tc(1) ARRAY-[]stkbar
.   .   .   DOTPTR u(2) l(17067) x(136+0) tc(1) ARRAY-[]stkbar
.   .   .   .   NAME-runtime.gp u(1) a(true) g(2) l(17030) x(0+0) class(PPARAM) f(1) esc(no) tc(1) used(true) PTR64-*g
.   .   .   .   NAME-runtime.stkbar u(1) a(true) l(17067) x(0+0)
.   .   .   KEY l(17067)
.   .   .   .   NAME-runtime.autotmp_2802 u(1) a(true) l(17067) x(0+0) class(PAUTO) esc(N) tc(1) assigned used(true) int
```

I guess there's some subsequent logic in the legacy compiler that removes the write barrier if it notices that the pointer being written is to the same object as the pointer that is already there.  Might be nice if we pushed that logic up to before the SSA cutoff so it can be shared.

The only other occurrence is at mstkbar.go:233:
```
	gp.stkbar = gp.stkbar[:0]
```
