### ISSUE TITLE
spec: operators/shift misleading comment

### ISSUE THREAD

**Issue by powerman** [golang/go#14785]
In this example:
```
var n = 1.0<<s != i    // 1.0 has type int; n == false if ints are 32bits in size
```
phrase "if ints are 32bits in size" makes no sense - n is always false, both on 32- and 64-bit.

**Comment by minux** [comment]
I think it should be "==" instead of "!="

**Comment by powerman** [comment]
`i` is `1<<s`. Other side is the same, and 32/64 bit makes no difference. So either this example was meant to demonstrate something else, or you can just remove "if ints are 32bits in size" part and keep the rest as is.

**Comment by griesemer** [comment]
@powerman Agreed. This is a leftover historic comment. Will try to change this into an example that is making a point again.
