### ISSUE TITLE
runtime: modify_ldt is optional in newer linux kernels, use set_thread_area instead

### ISSUE THREAD

**Issue by minux** [golang/go#14795]
see https://lkml.org/lkml/2015/7/21/759

we probably need to switch to use set_thread_area(2) instead for linux/386.
(do we need to apply this Go 1.4.4 so that Go 1.4 continues to run on
newer kernels with disabled modify_ldt? tentatively labeled Go1.4.4)

According to arch_prctl(2) man page: http://man7.org/linux/man-pages/man2/arch_prctl.2.html
       Context switches for 64-bit segment bases are rather expensive.  As
       an optimization, if a 32-bit TLS base address is used, arch_prctl(2)
       may use a real TLS entry as if set_thread_area(2) had been called,
       instead of manipulating the segment base register directly.

so we probably could switch to set_thread_area even on linux/amd64,
but I see that glibc still uses arch_prctl(ARCH_SET_FS), so probably
the overhead is not that big a problem.

**Comment by stanaka** [comment]
I've got an error, `Trace/breakpoint trap` with a crossbuilt 386 binary on Amazon Linux 2016.03, which is released a few days ago. This issue probably caused the error.

```
$ go version
go version go1.6 linux/amd64
$ uname -a
Linux ip-10-1-8-251 4.4.5-15.26.amzn1.x86_64 #1 SMP Wed Mar 16 17:15:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Songmu** [comment]
新しめの Linuxカーネルで、Go製のパッケージが動かなくなっていた。
具体的には、最新のAmazonLinuxなどで発生。対応を入れて、暫定的に動くように修正。
(kcpsとmsiは変更を入れていない)

ただし、以下の環境で動かなくなっている可能性がある。

- 32bit環境
- 古いカーネル(CentOS 5台の前半など)

その場合は、逆に古いパッケージを利用してもらう。ただ、それは暫定対処であり、改善はしていく。URLは以下。

## rpm

http://yum.mackerel.io/centos/i386/mackerel-agent-0.30.0-1.noarch.rpm
http://yum.mackerel.io/centos/i386/centos/i386/mackerel-agent-plugins-0.19.0-1.noarch.rpm
http://yum.mackerel.io/centos/i386/centos/i386/mackerel-check-plugins-0.5.0-1.noarch.rpm
http://yum.mackerel.io/centos/i386/centos/i386/mkr-0.9.0-1.noarch.rpm


## deb

http://apt.mackerel.io/debian/pool/contrib/m/mackerel-agent/mackerel-agent_0.30.0-1_all.deb
http://apt.mackerel.io/debian/pool/contrib/m/mackerel-agent-plugins/mackerel-agent-plugins_0.19.0-1_all.deb
http://apt.mackerel.io/debian/pool/contrib/m/mackerel-check-plugins/mackerel-check-plugins_0.5.0-1_all.deb
http://apt.mackerel.io/debian/pool/contrib/m/mkr/mkr_0.9.0-1_all.deb

**Comment by djtm** [comment]
You can also try to echo 1 > /proc/sys/modify_ldt as workaround. But this has security implications.

**Comment by stanaka** [comment]
Unfortunately `CONFIG_MODIFY_LDT_SYSCALL` of kernel of Amazon Linux 2016.03 is disabled, so `/proc/sys/modify_ldt` is not found. ( `/proc/sys/kernel/modify_ldt` is also not found. )

```
$ cat /boot/config-4.4.5-15.26.amzn1.x86_64  | grep MODIFY_LDT
# CONFIG_MODIFY_LDT_SYSCALL is not set
```

**Comment by stanaka** [comment]
With this patch, https://gist.github.com/stanaka/2b63a16d484692b3599f, which is based on the patch on this comment https://github.com/golang/go/issues/386#issuecomment-66049488, linux/386 binary seems to work well on Amazon Linux 2016.03, of which kernel is 4.4.5.
