### ISSUE TITLE
regexp/syntax: \Z not documented/implemented

### ISSUE THREAD

**Issue by perillo** [golang/go#14793]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go1.6 linux/amd

The documentation of the regexp/syntax package, in the "Empty strings" sections, says:
```
$              at end of text (like \z not \Z) or line (flag m=true)
```

However \Z is not documented, and it does not appear in the source code, except this comment in the (*Regex).Equal method:

```go
// The parse flags remember whether this is \z or \Z.
```

**Comment by perillo** [comment]
`git log -p regexp/syntax | grep -w '\\Z'` returns:

```
   $              at end of text (like \z not \Z) or line (flag m=true)
+  $              at end of text (like \z not \Z) or line (flag m=true)
+		// The parse flags remember whether this is \z or \Z.
```
It seems that \Z is a typo or it was a planned feature but implemented.

**Comment by junyer** [comment]
> It seems that \Z is a typo or it was a planned feature never implemented.

The `WasDollar` flag in RE2 – and in Go – is for distinguishing between `$` and `\z`. As such, the comment at https://github.com/golang/go/blob/master/src/regexp/syntax/regexp.go#L71 should be corrected.

The `regexp/syntax` documentation does not describe `\Z`, so it might not be helpful to mention it when describing `$`. https://golang.org/s/re2syntax does describe `\Z` as "at end of text, or before newline at end of text (NOT SUPPORTED)".

**Comment by rsc** [comment]
If someone wants to change "not \Z" to "not Perl's \Z", LGTM.

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/23201
