### ISSUE TITLE
runtime: should testSchedQueue[,Steal]Test be in export_test.go instead of proc.go?

### ISSUE THREAD

**Issue by odeke-em** [golang/go#14796]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +060a2ba Fri Mar 4 06:30:25 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/emmanuelodeke/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/emmanuelodeke/go"
GORACE=""
GOROOT="/Users/emmanuelodeke/go/src/go.googlesource.com/go"
GOTOOLDIR="/Users/emmanuelodeke/go/src/go.googlesource.com/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Read the source code in runtime/proc.go and runtime/export_test.go.

4. What did you expect to see?
Functions `testSchedQueueTest` and `testSchedQueueStealTest` should be in runtime/export_test.go?

5. What did you see instead?
The functions `testSchedQueueTest` and `testSchedQueueStealTest` are only used once in runtime/export_test.go yet are in runtime/proc.go

**Comment by odeke-em** [comment]
If them being in proc.go was unintended, I can submit a CL real quick to move them to the suggested location.

**Comment by bradfitz** [comment]
I thought this might've once been called at runtime to test the system it was being run on, but that doesn't appear to be the case. Starting at its creation in rev 353ce60f6e8e5898efec62945fbafd33bc28a37b, it's doesn't look like it was ever used like that.

Sure, you can move it to export_test.go.

**Comment by odeke-em** [comment]
Awesome. Thanks. CL mailed https://go-review.googlesource.com/20640.
