### ISSUE TITLE
encoding/xml: did not see expected CDATA

### ISSUE THREAD

**Issue by ckeyer** [golang/go#14798]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.6 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/***"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="0"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

http://play.golang.org/p/23xH1pmJuv

4. What did you expect to see?
```
<Response><KKName><![CDATA[ something bulabula ]]></KKName><Age>12</Age></Response>
```
https://golang.org/pkg/encoding/xml/#Marshal

5. What did you see instead?
```
<Response><KKName>something bulabula</KKName><Age>12</Age></Response>
```

**Comment by ianlancetaylor** [comment]
When I run your program using Go 1.6, I get

    xml: invalid tag in field Name of type main.Response: "KKName,cdata"

I do get your reported results with Go 1.5.  The problem is that a cdata element is not an XML element, and therefore should not have a name.

One way to get what you want is http://play.golang.org/p/-DVeAjptj5 .

Please take any questions about this to a forum; see https://golang.org/wiki/Questions.  Thanks.

**Comment by ckeyer** [comment]
@ianlancetaylor  Thanks.

**Comment by ckeyer** [comment]
How to set the name of the outermost xml? like
```
<xml><KKName><![CDATA[namewang]]></KKName><Age>12</Age></xml>
```

**Comment by bradfitz** [comment]
Please take any questions about this to a forum; see https://golang.org/wiki/Questions. Thanks.

**Comment by ckeyer** [comment]
:ok:
