### ISSUE TITLE
strange use of core's

### ISSUE THREAD

**Issue by deepch** [golang/go#14794]
go version go1.6 linux/amd64

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

I noticed that strange golang uses load between cores

![2016-03-13 0 39 35](https://cloud.githubusercontent.com/assets/7899955/13725500/8d6e076e-e8b4-11e5-886a-92728669bf59.png)

i have two cpu six core + HT

core 1-6 low usage
core 7-12 hi usage
core 13-24 very low or not usage

I use a lot of channel 
I use a lot of mutex 

Do golang no problems with HT or distribution of the cores ?

**Comment by bradfitz** [comment]
For general Go questions see https://golang.org/wiki/Questions. Thanks!

**Comment by deepch** [comment]
you want what I found there ?

**Comment by bradfitz** [comment]
Let's discuss any findings or questions on the mailing list or other forum.

**Comment by deepch** [comment]
thanks for the help
closed
