### ISSUE TITLE
tour: "on the top left of the page" should read "on the top right of the page"

### ISSUE THREAD

**Issue by danielfaust** [golang/go#14801]
Context: https://tour.golang.org/welcome/1

**Comment by danielfaust** [comment]
uhm, okay...

**Comment by danielfaust** [comment]
Hi Brad, it was my mistake, the text was correct. I thougt it was referring to the menu on the top right, which is then explained in the next paragraph.

**Comment by bradfitz** [comment]
Oh, I see.
