### ISSUE TITLE
wiki: document struct tag usage

### ISSUE THREAD

**Issue by nightlyone** [golang/go#14805]
**Problem**: Due to increased usage of Go and thus Go struct tags, clashes become inevitable.
**Proposed Solution**: Offer an IANA like registry for struct tags for publically available projects/libraries.

**Background**: 

Go offers [struct tags](https://golang.org/ref/spec#Tag) which are discoverable via [reflection](https://golang.org/pkg/reflect/#StructTag). These enjoy a wide range of use in the standard library in the JSON/XML and other encoding packages. The community welcomed them and build ORMs, further encodings, flag parsers and much more around them.

Since esp. while handling encodings and ORMs [single sourcing](https://en.wikipedia.org/wiki/Single_source_of_truth) data structures is beneficial for data structures.

**Comment by bradfitz** [comment]
Seems like a new wiki page would be sufficient, at least to start.

**Comment by davecheney** [comment]
If IANA want to host this more power to them, I don't think this is the
sort of thing the Go team needs to be involved in.

**Comment by adg** [comment]
I'm in favor of a wiki page. If someone wants to do that, please go right ahead.

**Comment by nightlyone** [comment]
Started the wiki page here: https://github.com/golang/go/wiki/Well-known-struct-tags and feedback and contribution is very welcome.

**Comment by adg** [comment]
@nightlyone nice work. Now we just need people to add all the non-standard-library stuff.

**Comment by balanatarajan** [comment]
@nightlyone : Would you like help on reviewing all libraries under github and documenting them here? Is that the expectation of the issue?

**Comment by nightlyone** [comment]
@balanatarajan yes, that is certainly the idea. But your help would be very welcome!

**Comment by seankhliao** [comment]
The page exists and looks up to date, I don't think there's anything else to do here.
