### ISSUE TITLE
x/text/width: lose one character

### ISSUE THREAD

**Issue by naduma** [golang/go#14817]
When Fold.String/Narrow.String was called, it was lost one character.

```
want := "A" + strings.Repeat("0", 127) + "B"
got := width.Fold.String("\uff21" + strings.Repeat("0", 127) + "B")
=> got != want, "B" is lost.
```

conditions:

* long string (more than 128 [initialBufSize])

* contains wide character

initialBufSize from https://github.com/golang/text/blob/master/transform/transform.go#L506

cause:

https://github.com/golang/text/blob/master/width/transform.go#L25

Even when the length of "dst" is 0, "nSrc" increases one.

InitStmt(nSrc++) is necessary?

**Comment by bradfitz** [comment]
Please post a complete and minimal program demonstrating the problem, not just a snippet. Is the `\uff21` necessary for the repro? Ideally please provide a share link from https://play.golang.org/ where it reproduces online.

`InitStmt(nSrc++)` is not valid Go. `++` is not an expression in Go.

**Comment by naduma** [comment]
```
$ go version
go version go1.6 linux/amd64
```

Steps to Reproduce

```
$ go get "golang.org/x/text"

$ go run sample.go
```

sample.go

```
package main

import (
    "fmt"
    "strings"

    "golang.org/x/text/width"
)

func main() {
    want := "A" + strings.Repeat("0", 127) + "B"
    got := width.Fold.String("\uff21" + strings.Repeat("0", 127) + "B")
    if got != want {
        fmt.Println("Fold.String NG!")
        fmt.Printf("got  %s (%d)\n", got, len(got))
        fmt.Printf("want %s (%d)\n", want, len(want))
    } else {
        fmt.Println("Fold.String OK!")
    }

    want = "A" + strings.Repeat("0", 127) + "B"
    got = width.Narrow.String("\uff21" + strings.Repeat("0", 127) + "B")
    if got != want {
        fmt.Println("Narrow.String NG!")
        fmt.Printf("got  %s (%d)\n", got, len(got))
        fmt.Printf("want %s (%d)\n", want, len(want))
    } else {
        fmt.Println("Narrow.String OK!")
    }
}
```

> InitStmt(nSrc++) is not valid Go. ++ is not an expression in Go.

InitStm is ForClause's InitStmt. ex. for i:=0; i < 10; i++ {

I'm not good at English. I wrote a patch sample, please check it.

https://gist.github.com/naduma/90a8fa3e21fffa1bbf80
