### ISSUE TITLE
os.user.Lookup fails with fatal error: C malloc failed in go1.5 but worked in go1.4

### ISSUE THREAD

**Issue by ascesh** [golang/go#14814]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

./go version
go version go1.5.1 linux/amd64  (Not working)

./go version
go version go1.4 linux/amd64  (working)

2. What operating system and processor architecture are you using (`go env`)?
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="XXXXXXXXXXXXX:/home/dandey/bin/gopath"
GORACE=""
GOROOT="XXXXXXXXXXXXXXXXXXXX"
GOTOOLDIR="XXXXXXXXXXXXXXXXXXXXX"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
loaded lots of internal data structs from info read from the database server (go application size is about 4gb in ram, but the server has well over 100gb ram, so the lack memory is not suspected)
on our proprietary application written in go.
once done all subsequent REST requests, seem to fail during authentication at the server.
authentication was done using os/user.lookup call, which fails with this call stack

------------------------------------------
fatal error: C malloc failed 

goroutine 533 [running]: 
runtime.throw(0x9d2c70, 0xf) 
        /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xe048e0b238 sp=0xe048e0b220 
runtime.cmalloc(0x400, 0xd920031ff0) 
        /usr/local/go/src/runtime/cgocall.go:148 +0x68 fp=0xe048e0b268 sp=0xe048e0b238 
os/user._Cfunc__CMalloc(0x400, 0x400) 
        ??:0 +0x21 fp=0xe048e0b280 sp=0xe048e0b268 
os/user.lookupUnix(0xffffffffffffffff, 0xe04d142500, 0x4, 0xe04d142701, 0x0, 0x0, 0x0) 
        /usr/local/go/src/os/user/lookup_unix.go:70 +0xaf fp=0xe048e0b3f0 sp=0xe048e0b280 
os/user.lookup(0xe04d142500, 0x4, 0x2eaecdaf, 0x0, 0x0) 
        /usr/local/go/src/os/user/lookup_unix.go:43 +0x45 fp=0xe048e0b430 sp=0xe048e0b3f0 
os/user.Lookup(0xe04d142500, 0x4, 0x0, 0x0, 0x0) 
        /usr/local/go/src/os/user/lookup.go:15 +0x37 fp=0xe048e0b460 sp=0xe048e0b430 
xxxxxxxxxxx/security.ValidateOperation(0xe04d142500, 0x4, 0xe04b644ac0, 0x3, 0x0, 0x0, 0x0) 
        /XXXX/XXXXX/security/Authorise.go:43 +0x5a fp=0xe048e0b590 sp=0xe048e0b460 
XXXXXXXXX/security.Authorise(0xe04d142500, 0x4, 0xe04b644ac0, 0x3, 0x1, 0x0, 0x0) 
        /XXXXXX/XXXXXXXXXX/security/Authorise.go:33 +0x247 fp=0xe048e0b628 sp=0xe048e0b590 
XXXXXX.(*RouteFactory).handlerFactory.func1(0x7f5e90f4c950, 0xe04d91b550, 0xe04aa0c000) 
        /XXXXXXXXX/XXXXXXXXXXXXX/routes.go:320 +0xad3 fp=0xe048e0baa8 sp=0xe048e0b628 
net/http.HandlerFunc.ServeHTTP(0xe046be4280, 0x7f5e90f4c950, 0xe04d91b550, 0xe04aa0c000) 
        /usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xe048e0bac8 sp=0xe048e0baa8 

------------------------------------------

**The same code when recompiled on older go 1.4 compiler works as is?**

4. What did you expect to see?
Expected the HTTP authentication to work, and response served

5. What did you see instead?
crash on go1.5, but not in go1.4

**Comment by bradfitz** [comment]
os/user users cgo and requires a thread. I suspect you have too many goroutines calling into cgo requiring threads and you're running out of memory. Put a semaphore in your authentication guarding your call to os/user.

Go 1.4 vs Go 1.5 vs Go 1.6 shouldn't matter here. You're just getting lucky vs unlucky between them probably.
