### ISSUE TITLE
x/tools/go/gcimporter15: TestImportTestdataNewExport panics with Go 1.6 (but not tip)

### ISSUE THREAD

**Issue by mwhudson** [golang/go#14824]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

linux/amd64, but I bet that doesn't matter

3. What did you do?

go test -v -run=TestImportTestdataNewExport golang.org/x/tools/go/gcimporter15

4. What did you expect to see?

The test passing

5. What did you see instead?

panic: interface conversion: types.Type is *types.Pointer, not *types.Named [recovered]
        panic: interface conversion: types.Type is *types.Pointer, not *types.Named

You can see this on build.golang.org too e.g. http://build.golang.org/log/6431d22fbbbf6d626c0462ce47b33fd9fc7a1819

**Comment by mwhudson** [comment]
This sounds like I should /cc @griesemer

**Comment by griesemer** [comment]
On it.

**Comment by mwhudson** [comment]
Er, the test now fails for me with

```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
```

with *both* go 1.6 and tip. Not sure this is progress? :-)

**Comment by mwhudson** [comment]
Ah no, it passes with very recent tip. But it fails with 1.6 -- maybe the gcimporter16_test.go file should be tagged go1.7, not go1.6?

**Comment by griesemer** [comment]
Yes, that's I mention in the CL desc - we're tracking tip here. Separate fix coming tonight/tomorrow unless somebody beats me to it.
