### ISSUE TITLE
net: SplitHostPort has returns strange host when err != nil

### ISSUE THREAD

**Issue by okdave** [golang/go#14827]
When `SplitHostPost` is given an invalid input (for example, and IPv6 address without a port), it returns an invalid/strange value for host alongside the error. This differs from many other funcs in the standard library (where usually zero values are returned unless documented otherwise), and invites mistakes if the user doesn't check the error.

For example in `host, port, err := net.SplitHostPort("2001:db8::ff00:42:8329")` host is `"2001:db8::ff00:42"`.

**Comment by mikioh** [comment]
Thanks for the report. Are you interested in fixing this issue?

**Comment by okdave** [comment]
Yes, happy to.

**Comment by bradfitz** [comment]
I'm happy to review, too.

**Comment by rsc** [comment]
Yes, please fix this to avoid setting host until success is assured.
