### ISSUE TITLE
cmd/compile/ssa: missed constant folding opportunity

### ISSUE THREAD

**Issue by davecheney** [golang/go#14825]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
% go version
go version devel +80f2aff Tue Mar 15 00:57:54 2016 +0000 linux/amd64
```
2. What operating system and processor architecture are you using (`go env`)?

linux/amd64

3. What did you do?
```
package p

const (
        WORDSIZE = 4
        WORDBITS = 32
        WORDMASK = WORDBITS - 1
)

type T struct {
        n int32
        b []uint32
}

func f(n int32) T {
        sz := uint(n) + WORDBITS - 1    // line 15
        sz = sz / WORDBITS              // line 16
        sz = sz * WORDSIZE              // line 17
        sz = sz / 4                     // line 18
        return T{n, make([]uint32, sz)}
}
```
4. What did you expect to see?

Constant division and multiplication will have been folded away

5. What did you see instead?

        0x001e 00030 (t.go:15)  MOVL    "".n+56(FP), CX
        0x0022 00034 (t.go:15)  MOVLQSX CX, AX
        0x0025 00037 (t.go:15)  ADDQ    $31, AX
        0x0029 00041 (t.go:16)  SHRQ    $5, AX
        0x002d 00045 (t.go:17)  SHLQ    $2, AX
        0x0031 00049 (t.go:18)  SHRQ    $2, AX

**Comment by griesemer** [comment]
I don't know that this is doable in general: n is not a constant. Even the last 2 instructions may have to stay if there is sign extension happening.

**Comment by randall77** [comment]
Todd, can you take a look?  I think we can replace the last two shifts with an AND.

**Comment by tzneal** [comment]
Sure, I can take it, but we already have a rule that would undo an AND created from the last two shifts since it's several bytes shorter:
```
func foo_ssa(x uint64) uint64 {
        return x & 0x3fffFFFFffffFFFF
}

Tip
        0x0000 00000 (/tmp/m.go:4)      MOVQ    "".x+8(FP), AX
        0x0005 00005 (/tmp/m.go:4)      SHLQ    $2, AX
        0x0009 00009 (/tmp/m.go:4)      SHRQ    $2, AX
        0x000d 00013 (/tmp/m.go:4)      MOVQ    AX, "".~r1+16(FP)
        0x0012 00018 (/tmp/m.go:4)      RET
```

vs:
```
        0x0000 00000 (/tmp/m.go:4)      MOVQ    "".x+8(FP), BP
        0x0005 00005 (/tmp/m.go:4)      MOVQ    $4611686018427387903, BX
        0x000f 00015 (/tmp/m.go:4)      ANDQ    BP, BX
        0x0012 00018 (/tmp/m.go:4)      MOVQ    BX, "".~r1+16(FP)
        0x0017 00023 (/tmp/m.go:4)      RET
```

Since sz is unsigned though, I think the last two shifts are just a no-op in this case. I'll look into that.

**Comment by davecheney** [comment]
> Since sz is unsigned though, I think the last two shifts are just a no-op
in this case. I'll look into that.

Thanks Todd, this is the case I was wondering about.
