### ISSUE TITLE
spec: clarify restrictions on RHS of non-constant shifts

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#14822]
The spec says (https://golang.org/ref/spec#Operators):

> The right operand in a shift expression must have unsigned integer type or be an untyped constant
> that can be converted to unsigned integer type.

All of go, gotype and gccgo seem to allow any unsigned type as the right operand. However, if the right operand is untyped, all of them seem to try to convert the operand specifically to `uint`, as opposed to, say, trying to find some unsigned integer type, capable of representing the value.

``` Go
package main
const A0 uint64 = 0xffffffff + 1
const A1 = 0xffffffff
const A2 = 0xffffffff + 1
var B, C uint64
func main() {
    C = B << A0
    C = B << A1
    C = B << A2 // error
}
```

If this is the intended behavior, then the spec should look like:

> The right operand in a shift expression must have unsigned integer type or be an untyped constant
> that can be converted to `uint`.

**Comment by griesemer** [comment]
@momchil-velikov I cannot reproduce this error with go tool compile or gotype. What am I missing?

**Comment by momchil-velikov** [comment]
@griesemer The testcase above needs GOARCH where `uint`  is smaller than `uint64`.

**Comment by griesemer** [comment]
@momchil-velikov Ok, I see the error with go tool compile, but not with gotype. This looks like a gc (cmd/compile) error to me.

**Comment by griesemer** [comment]
The above program compiles fine with the latest version of gccgo and is accepted by gotype. The spec clearly permits arbitrarily large untyped shift counts. This program should be accepted by the gc compiler.

**Comment by griesemer** [comment]
Not urgent. Downgrading to Go1.8Maybe.

**Comment by griesemer** [comment]
After some deliberation and discussion with others, I think we should simply document what the compilers do and thus adjust the spec. Both cmd/compile and gccgo expect that a constant right-hand side can be represented by a uint. That seems perfectly fine and this "restriction" has zero impact in practice. I'm going to adjust the spec and go/types instead.
