### ISSUE TITLE
x/tools/imports: TestFindImportVendor and TestProcessVendor fail

### ISSUE THREAD

**Issue by mwhudson** [golang/go#14823]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +c6e8342 Mon Mar 14 14:28:49 2016 +1300 linux/amd64

(but also 1.6)

2. What operating system and processor architecture are you using (`go env`)?

linux/amd64

3. What did you do?

go test golang.org/x/tools/imports

4. What did you expect to see?

tests passing

5. What did you see instead?

```
(master)mwhudson@aeglos:tools$ go test golang.org/x/tools/imports
--- FAIL: TestFindImportVendor (0.05s)
	fix_test.go:909: findImportGoPath("hpack", HuffmanDecode ...)="internal/golang.org/x/net/http2/hpack", false, want "golang.org/x/net/http2/hpack", false
--- FAIL: TestProcessVendor (0.05s)
	fix_test.go:942: Process("/opt/opensource/go/src/math/x.go") did not add expected hpack import:
		package http
		
		import (
			"strings"
		
			"internal/golang.org/x/net/http2/hpack"
		)
		
		func f() { strings.NewReader(); hpack.HuffmanDecode() }
FAIL
FAIL	golang.org/x/tools/imports	0.192s
```

(this happens on build.golang.org too)

**Comment by mwhudson** [comment]
I think these fail because Go 1.6's stdlib does not, in the end, use any vendoring but this test still assumes they do.

**Comment by bradfitz** [comment]
It will use vendoring again soon.

**Comment by bradfitz** [comment]
This was fixed recently.
