### ISSUE TITLE
cmd/go: -count option for benchmark runs each test n time before passing onto the next

### ISSUE THREAD

**Issue by hydroflame** [golang/go#14837]
1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOOS="darwin"

3. What did you do?
run any benchmark with the `-count` option set to more then 1 (for instance 3) and for at least 2 benchmark (eg. `A` and `B`)

all `n` instance of `A` will be run before any instance of `B` is ran (`AAABBB` instead of `ABABAB`)

The problem with this is that if I run my benchmarks several thousand time and the CPU is slightly less or more busy during the begining or the end it may bias the benchmark, while if they we're alternating at least it would affect the results equally

I have a feeling this will get rejected but I wanted a second opinion

**Comment by ALTree** [comment]
If you want to collect statistical data about benchmark A it makes sense to minimize noise in the results by grouping all A runs together, no? 

I don't get why ABABAB would be less biased. If the machine is busy at the beginning (AB----) and free at the end (----AB) you'll get huge variance on both A and B results. If you run like AAABBB then it does not really matter if the machine is busy on not, because A is always run in the same conditions, and same for B.

**Comment by hydroflame** [comment]
Oh I missed a details, I'm trying to compare benchmark `A` and `B`, so if the cpu affects `AAA-` but not `-BBB` then the A benchmarks ran slower then they should have, however by alternating, at least the machine utilisation will equally affect both benchmark. To prevent having too much of a big variance I just let them run multiple times (-count = 100-1000)

**Comment by randall77** [comment]
You're often not trying to compare benchmarks A and B, but benchmark A to itself with and without a change to the underlying system it is benchmarking.  Alternation will not help with that.

**Comment by josharian** [comment]
I agree that alternation is desirable; benchstat can help detect high variance. I gave this exact feedback when the feature was proposed. The response was: Alternation can be trivially achieved with a shell loop. Non-alternation cannot. Whether or not I agree with this, it is unlikely to change, so I am going to close this. Use a shell loop or a runner script.
