### ISSUE TITLE
cmd/cgo: could we add a C.CBytes function?

### ISSUE THREAD

**Issue by jbardin** [golang/go#14838]
Would it be possible to add `func C.Cbytes([]byte) unsafe.Pointer` to the cgo package?

I have copied the `C.CString` function, minus the added `0` byte a couple times, and this seems like it could be a useful addition. Granted it's only 3 lines to do the malloc and copy, but this would also serve as documentation for users needing to copy data into C.

**Comment by ianlancetaylor** [comment]
Want to send in a CL?

**Comment by jbardin** [comment]
Sure, though I'm not quite as sure what to do with the `cPrologGccgo`. Should I use `__go_open_array`? Something like this:

```
void *_cgoPREFIX_Cfunc_CBytes(struct __go_open_array b) {
	char *p = malloc(b.__count);
	memmove(p, b.__data, b.__count);
	return p;
}
```

**Comment by ianlancetaylor** [comment]
Yes.
