### ISSUE TITLE
tour: some errors on the spanish version

### ISSUE THREAD

**Issue by skozz** [golang/go#14832]
Following https://github.com/golang/go/issues/9090#issuecomment-196977535: 

> This translate error are present on the tour yet, 
> 
> `Observa que el tipo de indica [...]` must be `Observa que el tipo se indica[...]` and more. 
> ---
> ## <img width="528" alt="captura de pantalla 2016-03-15 a las 20 08 58" src="https://cloud.githubusercontent.com/assets/1021463/13790645/ccedaba6-eae9-11e5-97ce-01860c5c5220.png">
> 
> [This changes](https://github.com/rcostu/go-tour-es/pull/11/commits/31bab96b22a6ddae30de587432291f2bee480566) are gone at sometime. 

_First errors found on https://go-tour-es.appspot.com/#7_

The Spanish version have some typos again. I'm newbie with Go and its community so I'll be happy if you tell me where I can fix this typos on the repo to make a pull request with all typos that I can find through the tour.

**Comment by ALTree** [comment]
> I would file a bug at https://github.com/golang/tour/
> We don't track tour bugs here, and definitely not non-English ones.
> Thanks!

from https://github.com/golang/go/issues/19066#issuecomment-279527474

closing this, then. We don't control or deploy the spanish tour translation. You could file a bug to https://github.com/golang/tour/ and then contact the spanish tour maintainer to propose a fix.
