### ISSUE TITLE
cmd/go: go test <single file> no longer works with new vendoring support

### ISSUE THREAD

**Issue by bschoch** [golang/go#14842]
Please answer these questions before submitting your issue. Thanks!

**What version of Go are you using (`go version`)?**
go version go1.6 darwin/amd64

**What operating system and processor architecture are you using (`go env`)?**
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Bradley/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**What did you do?**
I am not sure if 
`go test <single file>`
is officially supported but it used to work.  If any of the packages imported by the test file are in the new vendor directory I get an error.  If none of the packages are in the vendor directory the test runs fine.

**What did you expect to see?**

I expect it to first print the path to my projects vendor directory, then look in the GOROOT, and then look in the GOPATH.

**What did you see instead?**

```
Bradleys-MacBook-Pro:wallet-api Bradley$ go test ./integration/api_test.go 
# command-line-arguments
integration/api_test.go:19:2: cannot find package "command-li/vendor/golang.org/x/net/context" in any of:
    /usr/local/go/src/command-li/vendor/golang.org/x/net/context (from $GOROOT)
    /Users/Bradley/go/src/command-li/vendor/golang.org/x/net/context (from $GOPATH)
```

It seems to be manipulating the string wrong to determine the paths for where it is supposed to look.
I can change how we run certain tests regardless but this behavior does not seem correct.

**Comment by davecheney** [comment]
What's happening is the single file you provided is being compiled in a
"fake" package. That package is no longer a sibling of the correct vendor/
directory so those paths are invisible.

I cannot comment on if this is supported behaviour or not, but can tell you
that the go tool really wants to work with packages, not single files, and
you will get much better results if you do things its way.

**Comment by rsc** [comment]
Sorry for the delayed questions, but I need to know more about the file tree.

What is the import statement at integration/api_test.go line 19? 

What directory is the go test command being run in?

That is, where is the integration directory relative to the command-li/vendor directory?

Thanks.

**Comment by bschoch** [comment]
The import statement is "golang.org/x/net/context"

I ran the tests from the base project directory, the vendor and the integration directory are in the directory that I run the tests from.
wallet-api/integration
wallet-api/vendor
cd wallet-api
go test ./integration/api_test.go

**Comment by bschoch** [comment]
This appears to be fixed.
