### ISSUE TITLE
cmd/objdump:  unsupported architecture for ppc64/ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#14846]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +c63dbd8 Thu Mar 10 18:35:10 2016 +0000 linux/ppc64le
Doesn't work on any earlier versions either.

2. What operating system and processor architecture are you using (`go env`)?
ppc64le

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
go tool objdump a.out

4. What did you expect to see?
A disassembly of the program.

5. What did you see instead?
objdump: disassemble a.out: unsupported architecture

I've seen a CL for this from Minux a while ago but haven't seen any recent updates.
If this was started but needs finishing I could help with that.

**Comment by bradfitz** [comment]
@minux?

**Comment by minux** [comment]
Duplicate. Merged into #9039.
