### ISSUE TITLE
golang/x/crypto/sha3:  proper alignment for ppc64/ppc64le improves performance

### ISSUE THREAD

**Issue by laboger** [golang/go#14847]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +ac1608a Thu Mar 10 15:54:08 2016 +0000 linux/ppc64le

2. What operating system and processor architecture are you using (`go env`)?
ppc64le using a golang built from master shown above

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
In looking at the sha3 implementation I noticed a difference in the alignment handling based on the target platform.  Having just made a similar change to crypo/cipher/xor.go, I recognized the same could be done here. 

4. What did you expect to see?
N/A?
5. What did you see instead?
N/A?

I have a change for this.

**Comment by mundaym** [comment]
Lynn did you test this on ppc64 or just ppc64le? Bill tried this on s390x and it didn't work. I think the unaligned xor code will only work on little endian machines.

**Comment by laboger** [comment]
@mundaym You are right, I thought I tried this on ppc64 but it doesn't work there.  I will have to change it to ppc64le only.
