### ISSUE TITLE
cmd/compile: building with -N produces "phis in single-predecessor block" error

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14857]
At tip revision 248c3a3c7b376e128c14fcb13eebf28733553d03:

    > go build -a -gcflags=-N runtime
    # runtime
    runtime/cgocall.go:567: internal compiler error: phis in single-predecessor block

**Comment by bradfitz** [comment]
Visible on build.golang.org too. The `-noopt` builder is broken: http://build.golang.org/log/6572eab8287245fc4e5482159f2b0fb7b6b109bd
