### ISSUE TITLE
x/tools/cmd/goimports: -srcdir rewrites paths in parser errors

### ISSUE THREAD

**Issue by dominikh** [golang/go#14864]
Running `goimports` with the `-srcdir` flag on a file with invalid Go syntax will produce syntax errors with paths in the directory provided by `-srcdir`, not the actual file. This is arguably confusing, because now the error might refer to a file that doesn't exist.

```
$ echo "package" > /tmp/foo.go                 
$ goimports -srcdir /somewhere/else /tmp/foo.go
/somewhere/else/foo.go:1:9: expected 'IDENT', found 'EOF'
```

I would expect `/tmp/foo.go:1:9` in the error output.

/cc @bradfitz

**Comment by bradfitz** [comment]
@dominikh, is this still an issue?

**Comment by dominikh** [comment]
The behaviour hasn't changed since my bug report. However, we handle it in go-mode now and I don't feel strongly about fixing it in goimports.

**Comment by bradfitz** [comment]
Okay, I'll close this then. It's a little gross to fix in goimports.

But re-open if needed later.
