### ISSUE TITLE
tour: Avoiding Beginner's 2D Array Confusion

### ISSUE THREAD

**Issue by tsalopek** [golang/go#14871]
Context: https://tour.golang.org/moretypes/8

In the Slices of Slices page within the Tour of Go I have identified an example which could be improved to better avoid confusion among beginner programmers. When working with multidimensional arrays, I frequently find that I second guessing myself regarding which index comes first, row or column. The example code on this page constructs a 2D array emulating a tic-tac-toe board:

```
board := [][]string{
		[]string{"_", "_", "_"},
		[]string{"_", "_", "_"},
		[]string{"_", "_", "_"},
	}
	// The players take turns.
	board[0][0] = "X"
	board[2][2] = "O"
	board[2][0] = "X"
	board[1][0] = "O"
	board[0][2] = "X"
```

This will produce a board which looks like this:
X _ X
O _ _
X _ O

For a beginner or someone, like myself, who doesn't work with multidimensional arrays frequently, it may be beneficial if the example where to construct a board such as this to avoid confusion:
X _ X
O _ X
 _ _ O

The updated example would show:
```
	// The players take turns.
	board[0][0] = "X"
	board[2][2] = "O"
	board[1][2] = "X"
	board[1][0] = "O"
	board[0][2] = "X"`
```

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by broady** [comment]
Thanks, nice idea, @tsalopek
