### ISSUE TITLE
x/exp/shiny: windows driver cannot set window height

### ISSUE THREAD

**Issue by Sythe2o0** [golang/go#14879]
GO/OS info:

Go1.6 windows/amd64
GOARCH = amd64
GOOS = windows

Using x/exp/shiny, we were starting a new project and trying to manipulate the initial window size. 

We expected using screen.NewWindowOptions{640,480} to result in a screen of 640 width and 480 height

The screen had no height. See [here](https://github.com/golang/exp/blob/master/shiny/driver/internal/win32/win32.go#L79).

In shiny's windows driver, it sets width to be the option's width, then to be the option's height, without actually ever setting height. This should be a simple fix:

```
	if opts != nil {
		if opts.Width > 0 {
			w = opts.Width
		}
		if opts.Height > 0 {
			h = opts.Height
		}
	}
```

**Comment by alexbrainman** [comment]
Silly mistake. @Sythe2o0, please, try https://go-review.googlesource.com/20862 to see if it fixes your problem. Thank you.

Alex

**Comment by Sythe2o0** [comment]
That's the same change we made locally, and it did fix it, yes.
