### ISSUE TITLE
website: establish a no-me-too policy

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14888]
@adg and I realized our "no-me-too" policy has only ever been "documented" in the golang-dev mailing list. Let's make it more official.

**Comment by adg** [comment]
I wrote this: https://github.com/golang/go/wiki/NoMeToo

Thoughts? @ianlancetaylor @rsc ?

**Comment by bradfitz** [comment]
@adg, should we link that from somewhere else? Although most people arriving at a github issue and me-tooing it will probably be arriving there from a direct link or search, so linking it from e.g. https://golang.org/doc/contribute.html might not be too effective. Still, can't hurt.

We can also just let people of the policy by cc'ing them from this bug if/when we delete comments.

**Comment by adg** [comment]
> We can also just let people of the policy by cc'ing them from this bug if/when we delete comments.

I think we should do this, at least. But I don't see much point in documenting it elsewhere, because people who do this aren't going to read our contribution guidelines.

**Comment by adg** [comment]
> I wrote this: https://github.com/golang/go/wiki/NoMeToo

> Thoughts?

I'd like advice on this text with regard to tone. I don't want it to come across as passive aggressive.

**Comment by ianlancetaylor** [comment]
The text you wrote on the wiki LGTM.

**Comment by shurcooL** [comment]
@adg That wiki page currently says:

> we cannot sort issues by "reactions" (yet)

That is no longer true, it's now possible to sort issues by most reactions. E.g.:

https://github.com/golang/go/issues?q=is%3Aopen+is%3Aissue+sort%3Areactions-%2B1-desc

**Comment by adg** [comment]
@shurcooL oh, that's great! I've replaced the paragraph you quoted with this text:

> Instead of commenting, you may add a :+1: reaction to the comment or issue.

**Comment by bradfitz** [comment]
@runningmaster, per the NoMeToo policy, we've deleted your +1 comments at https://github.com/golang/go/issues/14861

**Comment by bradfitz** [comment]
@timoteoponce, per the NoMeToo policy, we've deleted your "+1 for this!!" comment on #10010

**Comment by bradfitz** [comment]
@marcopeereboom, please note the https://golang.org/wiki/NoMeToo policy (per your comment on #15405)
