### ISSUE TITLE
proposal: add small api to support byte/string views

### ISSUE THREAD

**Issue by nightlyone** [golang/go#14889]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6 linux/amd64

(rest doesn't apply, since I don't report  a bug here)

It would be nice to make it easier to define, shareable, read-only views of data from which many consumable readers can be derived.

I did expect something like https://godoc.org/github.com/nightlyone/views/bytes 
and https://godoc.org/github.com/nightlyone/views/strings in the respective bytes and strings packages of the stdlib.

These are useful in interfaces like https://godoc.org/github.com/nightlyone/views

**Comment by davecheney** [comment]
Can't you just use bytes.Reader and strings.Reader ? If they lack the
ReaderAt behaviour, maybe we could add that instead.

**Comment by nightlyone** [comment]
@davecheney The problem with bytes.Reader and strings.Reader is, that they cannot be shared. The are consumables. I want something to share and create many consumables with known size from.

**Comment by davecheney** [comment]
Why does this need to go in the standard library?

**Comment by nightlyone** [comment]
@davecheney the reason would be to encourage that pattern of sharing. 

It probably makes more sense when including https://godoc.org/github.com/nightlyone/views#SizeReaderAt as well in io.

This has been duplicated in various places already (e.g. https://godoc.org/google.golang.org/api/googleapi#SizeReaderAt and https://godoc.org/go4.org/readerutil#SizeReaderAt), which define interfaces types incompatible to each other when put in a function signature.

**Comment by davecheney** [comment]
But why does it need to go in the standard library to achieve that? The
stdlib shouldn't just be a dumping ground of good ideas waiting for a rainy
day, that's how we got python 2.

**Comment by bradfitz** [comment]
If this bug is about adding `SizeReaderAt` to the `io` package, I could support that. I meant to add `SizeReaderAt` ages ago and I still think it's a good idea.

If this bug is about e.g. #5376, then this can be closed as a dup.

**Comment by nightlyone** [comment]
@bradfitz the goal was also to add the matching support for bytes/strings. But if this is too much API for these, then I would live with adding those in lots of *_test.go files as I do now...

**Comment by nightlyone** [comment]
@davecheney e.g. Static asset serving in net/http could be improved based on that.

**Comment by bradfitz** [comment]
What is "the matching support"? Can you concretely explain what this bug is about? `*strings.Reader` and `*bytes.Reader` are both already implement `SizeReaderAt`.

**Comment by nightlyone** [comment]
@bradfitz This issue is about immutable in-memory assets originally based on `string` or `[]byte`, but handled in the same way by API on top of it. Its a different approach to your old idea of a "byte view". `*strings.Reader` and `*bytes.Reader` are both not shareable, because they implement to many other interfaces besides SizeReaderAt.

**Comment by bradfitz** [comment]
@nightlyone, you can share a `*strings.Reader` or *bytes.Reader` as a `SizeReaderAt`.

**Comment by nightlyone** [comment]
OK, looks like I have a bit trouble getting my point across. Let's close it and focus on more important stuff.
