### ISSUE TITLE
1.2676506002282295e+29 - error? must be 1.2676506002282295e+30

### ISSUE THREAD

**Issue by vvershov** [golang/go#14886]
Context: http://tour.golang.org/basics/16

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ianlancetaylor** [comment]
What is the bug?

**Comment by minux** [comment]
Big = 1 << 100 = 1.2676506002282294e+30,
but note that needFloat returns x * 0.1, so
the printed result is 1.2676506002282294e+29.
