### ISSUE TITLE
image: remove bounds check in "At" and "Set" methods, with re slice

### ISSUE THREAD

**Issue by pierrre** [golang/go#14884]
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   linux amd64

I just saw this https://go-review.googlesource.com/#/c/20654/

Could we rewrite

``` go
func (p *RGBA64) RGBA64At(x, y int) color.RGBA64 {
    if !(Point{x, y}.In(p.Rect)) {
        return color.RGBA64{}
    }
    i := p.PixOffset(x, y)
    return color.RGBA64{
        uint16(p.Pix[i+0])<<8 | uint16(p.Pix[i+1]),
        uint16(p.Pix[i+2])<<8 | uint16(p.Pix[i+3]),
        uint16(p.Pix[i+4])<<8 | uint16(p.Pix[i+5]),
        uint16(p.Pix[i+6])<<8 | uint16(p.Pix[i+7]),
    }
}
```

to

``` go
func (p *RGBA64) RGBA64At(x, y int) color.RGBA64 {
    if !(Point{x, y}.In(p.Rect)) {
        return color.RGBA64{}
    }
    i := p.PixOffset(x, y)
    s := p.Pix[i:i+8]
    return color.RGBA64{
        uint16(s[0])<<8 | uint16(s[1]),
        uint16(s[2])<<8 | uint16(s[3]),
        uint16(s[4])<<8 | uint16(s[5]),
        uint16(s[6])<<8 | uint16(s[7]),
    }
}
```

I did some benchmarks on my package https://github.com/pierrre/imageserver/tree/master/image/internal (that borrows code from `image`).
And I see interesting results.

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
Yeah, I'd be willing to accept a CL, if the results are sufficiently interesting.

**Comment by pierrre** [comment]
How to check if bounds check are really removed?

Should I read assembly code with `go build -gcflags="-S"`?
What do they look like?

**Comment by randall77** [comment]
On Mon, Mar 21, 2016 at 1:15 AM, Pierre Durand <notifications@github.com>
wrote:

> How to check if bounds check are really removed?
>
> Should I read assembly code with go build -gcflags="-S"?
> What do they look like?
>
Yes, that will work.  They are just a compare and branch where the
destination is a call to panicindex (or panicslice, for slice bounds
checks).

We could use a -d=bounds to print all the places where a bounds check
happens.  We have -d=nil and -d=wb for nil checks and write barriers,
respectively.  It might be kind of tricky to implement though.

**Comment by brtzsnr** [comment]
FWIW, the correct line to use is `s := p.Pix[i:i+8:len(p.Pix)]`.
