### ISSUE TITLE
'net/http' server does not set http.Request's TLS field when using other implementations of TLS

### ISSUE THREAD

**Issue by cstrahan** [golang/go#14891]
1. What version of Go are you using (`go version`)?

  1.5 (though this applies to master).

2. What operating system and processor architecture are you using (`go env`)?

  Linux, amd64.

3. What did you do?

  Looked at [src/net/http/server.go#L1398](https://github.com/golang/go/blob/8540a1c4dfd6f4950f5a1da6241c76765262ddbd/src/net/http/server.go#L1398) and saw that the following conditional branch was used to decide whether or not to capture the TLS state:

  ```go
	if tlsConn, ok := c.rwc.(*tls.Conn); ok {
  ```

  As a result, when using `net/http`'s server with e.g. https://github.com/spacemonkeygo/openssl, the `TLS` field in `http.Request` is `nil`.

4. What did you expect to see?

  Some way to handle alternative TLS implementations while properly setting the `TLS` field in `http.Request`.

5. What did you see instead?

  No support for alternative TLS implementations while properly setting the `TLS` field in `http.Request`.

**Comment by bradfitz** [comment]
I don't think we'll be fixing this. I would rather improve Go's TLS implementation than complicate the HTTP package implementation and docs.

**Comment by cstrahan** [comment]
@bradfitz I might also add that this also breaks anything that attempts to wrap a `Conn`. For example, in [`goji`](https://github.com/zenazn/goji): https://github.com/zenazn/goji/blob/master/graceful%2Flistener%2Fconn.go

**Comment by cstrahan** [comment]
(Perhaps a more insightful link: https://godoc.org/github.com/zenazn/goji/graceful)
