### ISSUE TITLE
tour: windows: cannot find package "golang.org/x/tour/reader"

### ISSUE THREAD

**Issue by lbednarek** [golang/go#14898]
I am using Go 1.6 in Windows - downloaded today.  I was working on the 'Exercise:Readers' part of the tour ( http://127.0.0.1:3999/methods/22 ), and got the following error when trying to Run:
compile291.go:3:8: cannot find package "golang.org/x/tour/reader" in any of:
	C:\Go\src\golang.org\x\tour\reader (from $GOROOT)
	C:\Go\misc\tour\src\golang.org\x\tour\reader (from $GOPATH)

This looks like the same thing as described in https://github.com/golang/go/issues/14184 , but I am reporting for Windows.  Steps to fix as described by lernisto worked for me as well.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
This will be fixed when Go 1.6.1 is released (soon).
