### ISSUE TITLE
net/http: it's a bug?

### ISSUE THREAD

**Issue by aegsea** [golang/go#14895]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
The same as issue #14548 , How to fix it?

`
	goroutine 26204301 [IO wait]:
	net.runtime_pollWait(0x7f8ebcc030e0, 0x77, 0x45a330)
		/opt/work/golang/go/src/runtime/netpoll.go:160 +0x60
	net.(*pollDesc).Wait(0xc83fc2edf0, 0x77, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
	net.(*pollDesc).WaitWrite(0xc83fc2edf0, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:82 +0x36
	net.(*netFD).connect(0xc83fc2ed90, 0x0, 0x0, 0x7f8ec1895c90, 0xc83fb9c2e0, 0xece8190e1, 0x3b3f615e, 0xf82ba0, 0x0, 0x0, ...)
		/opt/work/golang/go/src/net/fd_unix.go:127 +0x28e
	net.(*netFD).dial(0xc83fc2ed90, 0x7f8ec1895c48, 0x0, 0x7f8ec1895c48, 0xc82037c780, 0xece8190e1, 0xc83b3f615e, 0xf82ba0, 0x0, 0x0, ...)
		/opt/work/golang/go/src/net/sock_posix.go:137 +0x364
	net.socket(0xb23770, 0x3, 0x2, 0x1, 0x0, 0xc82037c700, 0x7f8ec1895c48, 0x0, 0x7f8ec1895c48, 0xc82037c780, ...)
		/opt/work/golang/go/src/net/sock_posix.go:89 +0x429
	net.internetSocket(0xb23770, 0x3, 0x7f8ec1895c48, 0x0, 0x7f8ec1895c48, 0xc82037c780, 0xece8190e1, 0xc83b3f615e, 0xf82ba0, 0x1, ...)
		/opt/work/golang/go/src/net/ipsock_posix.go:161 +0x153
	net.dialTCP(0xb23770, 0x3, 0x0, 0xc82037c780, 0xece8190e1, 0x3b3f615e, 0xf82ba0, 0x0, 0x1, 0x0, ...)
		/opt/work/golang/go/src/net/tcpsock_posix.go:171 +0x12b
	net.dialSingle(0xc820808f30, 0x7f8ec1895bb8, 0xc82037c780, 0xece8190e1, 0x3b3f615e, 0xf82ba0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dial.go:371 +0x40c
	net.dialSerial.func1(0xece8190e1, 0x3b3f615e, 0xf82ba0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dial.go:343 +0x75
	net.dial(0xb23770, 0x3, 0x7f8ec1895bb8, 0xc82037c780, 0xc8219b1538, 0xece8190e1, 0x3b3f615e, 0xf82ba0, 0x0, 0x0, ...)
		/opt/work/golang/go/src/net/fd_unix.go:40 +0x60
	net.dialSerial(0xc820808f30, 0xc82074ccc0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dial.go:345 +0x751
	net.(*Dialer).Dial(0xc8219b17b0, 0xb23770, 0x3, 0xc83f00c140, 0x19, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dial.go:239 +0x512
	net.DialTimeout(0xb23770, 0x3, 0xc83f00c140, 0x19, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dial.go:200 +0xa3
	webcrawler/httplib.TimeoutDialer.func1(0xb23770, 0x3, 0xc83f00c140, 0x19, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:552 +0x8d
	net/http.(*Transport).dial(0xc82184af00, 0xb23770, 0x3, 0xc83f00c140, 0x19, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:655 +0x96
	net/http.(*Transport).dialConn(0xc82184af00, 0x0, 0xc83f00c0c0, 0x5, 0xc83f00c140, 0x19, 0xc8224f3a40, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:758 +0x1e3d
	net/http.(*Transport).getConn.func4(0xc82184af00, 0x0, 0xc83f00c0c0, 0x5, 0xc83f00c140, 0x19, 0xc83fbab9e0)
		/opt/work/golang/go/src/net/http/transport.go:702 +0x66
	created by net/http.(*Transport).getConn
		/opt/work/golang/go/src/net/http/transport.go:704 +0x262

	goroutine 26228283 [IO wait]:
	net.runtime_pollWait(0x7f8ec17e2098, 0x72, 0xc82e9e9000)
		/opt/work/golang/go/src/runtime/netpoll.go:160 +0x60
	net.(*pollDesc).Wait(0xc821476530, 0x72, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
	net.(*pollDesc).WaitRead(0xc821476530, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:78 +0x36
	net.(*netFD).Read(0xc8214764d0, 0xc82e9e9000, 0x1000, 0x1000, 0x0, 0x7f8ec1891050, 0xc82000a240)
		/opt/work/golang/go/src/net/fd_unix.go:250 +0x23a
	net.(*conn).Read(0xc83d86af90, 0xc82e9e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/net.go:172 +0xe4
	net/http.noteEOFReader.Read(0x7f8ec1860448, 0xc83d86af90, 0xc83f64c548, 0xc82e9e9000, 0x1000, 0x1000, 0x60, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1683 +0x67
	net/http.(*noteEOFReader).Read(0xc8229a9ee0, 0xc82e9e9000, 0x1000, 0x1000, 0xb19df0, 0x0, 0x0)
		<autogenerated>:284 +0xd0
	bufio.(*Reader).fill(0xc82ede86c0)
		/opt/work/golang/go/src/bufio/bufio.go:97 +0x1e9
	bufio.(*Reader).Peek(0xc82ede86c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/bufio/bufio.go:132 +0xcc
	net/http.(*persistConn).readLoop(0xc83f64c4e0)
		/opt/work/golang/go/src/net/http/transport.go:1069 +0x177
	created by net/http.(*Transport).dialConn
		/opt/work/golang/go/src/net/http/transport.go:853 +0x10a6

	goroutine 26227170 [select]:
	net/http.(*persistConn).roundTrip(0xc8308be8f0, 0xc83342b9e0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1469 +0xf1f
	net/http.(*Transport).RoundTrip(0xc82fd423c0, 0xc8307f9180, 0xc82fd423c0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:320 +0x9bb
	net/http.send(0xc8307f9180, 0x7f8ec1895550, 0xc82fd423c0, 0x0, 0x0, 0x0, 0xc8334314a0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:260 +0x6b7
	net/http.(*Client).send(0xc83f5f1ad0, 0xc8307f9180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:155 +0x185
	net/http.(*Client).doFollowingRedirects(0xc83f5f1ad0, 0xc82fd4a0e0, 0xc4fd10, 0xc833402870, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:475 +0x8a4
	net/http.(*Client).Do(0xc83f5f1ad0, 0xc82fd4a0e0, 0xa, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:188 +0xff
	webcrawler/httplib.(*BeegoHTTPRequest).DoRequest(0xc82fd42300, 0xc82fd21e00, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:463 +0x800
	webcrawler/httplib.(*BeegoHTTPRequest).getResponse(0xc82fd42300, 0xa754c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:380 +0x5f
	webcrawler/httplib.(*BeegoHTTPRequest).Response(0xc82fd42300, 0xc82fd313c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:546 +0x2d
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc82fd3e960, 0xf, 0xb200d8, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:179 +0x7de
	main.(*WebCrawler).concurrentCheck(0xc820c88840, 0xc82fd2f160, 0xb, 0x20fe80)
		/opt/work/golang/project/src/webcrawler/main.go:381 +0x169
	created by main.(*WebCrawler).loadRange
		/opt/work/golang/project/src/webcrawler/main.go:417 +0x544

	goroutine 26230881 [IO wait]:
	net.runtime_pollWait(0x7f8ebcbfd860, 0x72, 0xc830f78000)
		/opt/work/golang/go/src/runtime/netpoll.go:160 +0x60
	net.(*pollDesc).Wait(0xc83439a290, 0x72, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
	net.(*pollDesc).WaitRead(0xc83439a290, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:78 +0x36
	net.(*netFD).Read(0xc83439a230, 0xc830f78000, 0x1000, 0x1000, 0x0, 0x7f8ec1891050, 0xc82000a240)
		/opt/work/golang/go/src/net/fd_unix.go:250 +0x23a
	net.(*conn).Read(0xc833c4bd98, 0xc830f78000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/net.go:172 +0xe4
	net/http.noteEOFReader.Read(0x7f8ec1860448, 0xc833c4bd98, 0xc8218a7c08, 0xc830f78000, 0x1000, 0x1000, 0x60, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1683 +0x67
	net/http.(*noteEOFReader).Read(0xc830f4ca20, 0xc830f78000, 0x1000, 0x1000, 0xb19df0, 0x0, 0x0)
		<autogenerated>:284 +0xd0
	bufio.(*Reader).fill(0xc830f47c20)
		/opt/work/golang/go/src/bufio/bufio.go:97 +0x1e9
	bufio.(*Reader).Peek(0xc830f47c20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/bufio/bufio.go:132 +0xcc
	net/http.(*persistConn).readLoop(0xc8218a7ba0)
		/opt/work/golang/go/src/net/http/transport.go:1069 +0x177
	created by net/http.(*Transport).dialConn
		/opt/work/golang/go/src/net/http/transport.go:853 +0x10a6

	goroutine 26230788 [IO wait]:
	net.runtime_pollWait(0x7f8ec17df898, 0x72, 0xc830b04000)
		/opt/work/golang/go/src/runtime/netpoll.go:160 +0x60
	net.(*pollDesc).Wait(0xc834eefb10, 0x72, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
	net.(*pollDesc).WaitRead(0xc834eefb10, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:78 +0x36
	net.(*netFD).Read(0xc834eefab0, 0xc830b04000, 0x1000, 0x1000, 0x0, 0x7f8ec1891050, 0xc82000a240)
		/opt/work/golang/go/src/net/fd_unix.go:250 +0x23a
	net.(*conn).Read(0xc833c4b5c8, 0xc830b04000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/net.go:172 +0xe4
	net/http.noteEOFReader.Read(0x7f8ec1860448, 0xc833c4b5c8, 0xc83487a208, 0xc830b04000, 0x1000, 0x1000, 0x60, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1683 +0x67
	net/http.(*noteEOFReader).Read(0xc834ffe9a0, 0xc830b04000, 0x1000, 0x1000, 0xb19df0, 0x0, 0x0)
		<autogenerated>:284 +0xd0
	bufio.(*Reader).fill(0xc83500e3c0)
		/opt/work/golang/go/src/bufio/bufio.go:97 +0x1e9
	bufio.(*Reader).Peek(0xc83500e3c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/bufio/bufio.go:132 +0xcc
	net/http.(*persistConn).readLoop(0xc83487a1a0)
		/opt/work/golang/go/src/net/http/transport.go:1069 +0x177
	created by net/http.(*Transport).dialConn
		/opt/work/golang/go/src/net/http/transport.go:853 +0x10a6

	goroutine 26230547 [IO wait]:
	net.runtime_pollWait(0x7f8ebd562ea0, 0x72, 0xc83404b400)
		/opt/work/golang/go/src/runtime/netpoll.go:160 +0x60
	net.(*pollDesc).Wait(0xc8341da060, 0x72, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
	net.(*pollDesc).WaitRead(0xc8341da060, 0x0, 0x0)
		/opt/work/golang/go/src/net/fd_poll_runtime.go:78 +0x36
	net.(*netFD).Read(0xc8341da000, 0xc83404b400, 0x200, 0x200, 0x0, 0x7f8ec1891050, 0xc82000a240)
		/opt/work/golang/go/src/net/fd_unix.go:250 +0x23a
	net.(*conn).Read(0xc833ae4728, 0xc83404b400, 0x200, 0x200, 0x200, 0x0, 0x0)
		/opt/work/golang/go/src/net/net.go:172 +0xe4
	net.(*UDPConn).readDNSResponse(0xc833ae4728, 0xc834045700, 0x0, 0x0)
		/opt/work/golang/go/src/net/dnsclient_unix.go:52 +0xa5
	net.exchange(0xc8341d8090, 0xd, 0xc8341bdc00, 0x12, 0xc8341d0001, 0x12a05f200, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/dnsclient_unix.go:155 +0x4ea
	net.tryOneName(0xc82007c500, 0xc8341bdc00, 0x12, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/opt/work/golang/go/src/net/dnsclient_unix.go:181 +0x2f3
	net.goLookupIPOrder.func1(0xc82007c500, 0xc8341d21e0, 0xc8341ce600, 0x1)
		/opt/work/golang/go/src/net/dnsclient_unix.go:462 +0x59
	created by net.goLookupIPOrder
		/opt/work/golang/go/src/net/dnsclient_unix.go:464 +0x3d0

	goroutine 26230440 [select]:
	net/http.(*persistConn).roundTrip(0xc833c02340, 0xc833c5ae60, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1469 +0xf1f
	net/http.(*Transport).RoundTrip(0xc833ad0540, 0xc833b3e540, 0xc833ad0540, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:320 +0x9bb
	net/http.send(0xc833b3e540, 0x7f8ec1895550, 0xc833ad0540, 0x0, 0x0, 0x0, 0xc833bffb20, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:260 +0x6b7
	net/http.(*Client).send(0xc82232dad0, 0xc833b3e540, 0x0, 0x0, 0x0, 0x16, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:155 +0x185
	net/http.(*Client).doFollowingRedirects(0xc82232dad0, 0xc833b3e540, 0xc4fd10, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:475 +0x8a4
	net/http.(*Client).Do(0xc82232dad0, 0xc833b3e540, 0xa, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:188 +0xff
	webcrawler/httplib.(*BeegoHTTPRequest).DoRequest(0xc833ad0480, 0xc833c57410, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:463 +0x800
	webcrawler/httplib.(*BeegoHTTPRequest).getResponse(0xc833ad0480, 0xa754c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:380 +0x5f
	webcrawler/httplib.(*BeegoHTTPRequest).Response(0xc833ad0480, 0xc833bffae0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:546 +0x2d
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc833bffaa0, 0x16, 0xb200d8, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:179 +0x7de
	main.(*WebCrawler).concurrentCheck(0xc820c88840, 0xc833b1d940, 0x12, 0x20ff7b)
		/opt/work/golang/project/src/webcrawler/main.go:381 +0x169
	created by main.(*WebCrawler).loadRange
		/opt/work/golang/project/src/webcrawler/main.go:417 +0x544

	goroutine 26214952 [select]:
	net/http.(*persistConn).roundTrip(0xc82164dd40, 0xc820fbdce0, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:1469 +0xf1f
	net/http.(*Transport).RoundTrip(0xc82307c840, 0xc8224ee540, 0xc82307c840, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:320 +0x9bb
	net/http.send(0xc8224ee540, 0x7f8ec1895550, 0xc82307c840, 0x0, 0x0, 0x0, 0xc8218d0e40, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:260 +0x6b7
	net/http.(*Client).send(0xc820eedad0, 0xc8224ee540, 0x0, 0x0, 0x0, 0xb, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:155 +0x185
	net/http.(*Client).doFollowingRedirects(0xc820eedad0, 0xc8224ee540, 0xc4fd10, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:475 +0x8a4
	net/http.(*Client).Do(0xc820eedad0, 0xc8224ee540, 0xa, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:188 +0xff
	webcrawler/httplib.(*BeegoHTTPRequest).DoRequest(0xc82307c780, 0xc83f62eed0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:463 +0x800
	webcrawler/httplib.(*BeegoHTTPRequest).getResponse(0xc82307c780, 0xa754c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:380 +0x5f
	webcrawler/httplib.(*BeegoHTTPRequest).Response(0xc82307c780, 0xc8218d0de0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:546 +0x2d
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc820fbdbf0, 0xb, 0xb200d8, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:179 +0x7de
	main.(*WebCrawler).concurrentCheck(0xc820c88840, 0xc82027b647, 0x7, 0x20fab0)
		/opt/work/golang/project/src/webcrawler/main.go:381 +0x169
	created by main.(*WebCrawler).loadRange
		/opt/work/golang/project/src/webcrawler/main.go:417 +0x544

	goroutine 26209595 [select]:
	net/http.(*Transport).getConn(0xc83f3d18c0, 0xc82277e7e0, 0x0, 0xc8219d5aa0, 0x5, 0xc8219d5b20, 0x16, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:707 +0x4ef
	net/http.(*Transport).RoundTrip(0xc83f3d18c0, 0xc82277e7e0, 0xc83f3d18c0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:307 +0x7e9
	net/http.send(0xc82277e7e0, 0x7f8ec1895550, 0xc83f3d18c0, 0x0, 0x0, 0x0, 0xc8219d5b00, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:260 +0x6b7
	net/http.(*Client).send(0xc82093d810, 0xc82277e7e0, 0x0, 0x0, 0x0, 0x12, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:155 +0x185
	net/http.(*Client).doFollowingRedirects(0xc82093d810, 0xc82277e7e0, 0xc4fd10, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:475 +0x8a4
	net/http.(*Client).Do(0xc82093d810, 0xc82277e7e0, 0xa, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:188 +0xff
	webcrawler/httplib.(*BeegoHTTPRequest).DoRequest(0xc83f3d1800, 0xc821e1cc30, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:463 +0x800
	webcrawler/httplib.(*BeegoHTTPRequest).getResponse(0xc83f3d1800, 0xa754c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:380 +0x5f
	webcrawler/httplib.(*BeegoHTTPRequest).Response(0xc83f3d1800, 0xc8219d5ac0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:546 +0x2d
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc820a0fac0, 0x12, 0xb200f0, 0x5, 0xc800000002, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:179 +0x7de
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc820a0fac0, 0x12, 0xb200d8, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:187 +0x8ed
	main.(*WebCrawler).concurrentCheck(0xc820c88840, 0xc820f0fcf0, 0xe, 0x20f90a)
		/opt/work/golang/project/src/webcrawler/main.go:381 +0x169
	created by main.(*WebCrawler).loadRange
		/opt/work/golang/project/src/webcrawler/main.go:417 +0x544

	goroutine 26154807 [select]:
	net/http.(*Transport).getConn(0xc8218cc600, 0xc83f6442a0, 0x0, 0xc821305460, 0x5, 0xc821305520, 0x16, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:707 +0x4ef
	net/http.(*Transport).RoundTrip(0xc8218cc600, 0xc83f6442a0, 0xc8218cc600, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/transport.go:307 +0x7e9
	net/http.send(0xc83f6442a0, 0x7f8ec1895550, 0xc8218cc600, 0x0, 0x0, 0x0, 0xc8213054e0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:260 +0x6b7
	net/http.(*Client).send(0xc8231dd810, 0xc83f6442a0, 0x0, 0x0, 0x0, 0x12, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:155 +0x185
	net/http.(*Client).doFollowingRedirects(0xc8231dd810, 0xc83f6442a0, 0xc4fd10, 0x0, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:475 +0x8a4
	net/http.(*Client).Do(0xc8231dd810, 0xc83f6442a0, 0xa, 0x0, 0x0)
		/opt/work/golang/go/src/net/http/client.go:188 +0xff
	webcrawler/httplib.(*BeegoHTTPRequest).DoRequest(0xc8218cc540, 0x7f8ec18e14b0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:463 +0x800
	webcrawler/httplib.(*BeegoHTTPRequest).getResponse(0xc8218cc540, 0xa754c0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:380 +0x5f
	webcrawler/httplib.(*BeegoHTTPRequest).Response(0xc8218cc540, 0xc821305480, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/httplib/httplib.go:546 +0x2d
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc83ef7a5e0, 0x12, 0xb200f0, 0x5, 0xc800000002, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:179 +0x7de
	main.(*WebCrawler).checkDomain(0xc820c88840, 0xc83ef7a5e0, 0x12, 0xb200d8, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
		/opt/work/golang/project/src/webcrawler/main.go:187 +0x8ed
	main.(*WebCrawler).concurrentCheck(0xc820c88840, 0xc821b3c060, 0xe, 0x20e7d8)
		/opt/work/golang/project/src/webcrawler/main.go:381 +0x169
	created by main.(*WebCrawler).loadRange
		/opt/work/golang/project/src/webcrawler/main.go:417 +0x544
`

**Comment by ianlancetaylor** [comment]
This is not the same as #14548, as that problem was specific to Darwin and you are running GNU/Linux.

You didn't say what you are doing and you didn't say what failed.  Thanks for posting the stack trace, but what program were you running?  What happened?

**Comment by bradfitz** [comment]
Timeout. Closing.
