### ISSUE TITLE
tour: Elaboration on slicing a slice with 0 len but 5 cap

### ISSUE THREAD

**Issue by louy2** [golang/go#14893]
Context: https://tour.golang.org/moretypes/10

The code below is surprising and confusing:

```
	b := make([]int, 0, 5) // here b is made a slice with 0 len
	printSlice("b", b)

	c := b[:2]
	printSlice("c", c)

	d := c[2:5]
	printSlice("d", d)
```

The sample on the side indicates that slicing a slice with len 0 returns a slice with len the same as cap. Further elaboration of this decision and its implications is appreciated.

**Comment by ianlancetaylor** [comment]
CC @adg @campoy

**Comment by adg** [comment]
> The sample on the side indicates that slicing a slice with len 0 returns a slice with len the same as cap. 

How do you arrive at this conclusion? If you can elaborate then I can zero in on where this misunderstanding has occurred.

**Comment by louy2** [comment]
My bad, I did not phrase that to convey my idea properly. What I meant was, slicing a slice with len 0 but cap 5 returns a slice with the requested length for both len and cap. As indicated by this sample on the side:

```go
b := make([]int, 0, 5) // len(b)=0, cap(b)=5

b = b[:cap(b)] // len(b)=5, cap(b)=5
b = b[1:]      // len(b)=4, cap(b)=4
```

So the range of slicing a slice is constrained by its cap, but not its len. This is a decision I am surprised with. Because right before this, on https://tour.golang.org/moretypes/9:

```go
// missing high index implies len(s)       *nope, that should be cap(s)
fmt.Println("s[4:] ==", s[4:])
```

-----------------

Above was what I originally wrote, and soon after I found my mistake. Experimenting on the playground a bit:

```go
b := make([]int, 0, 5)
printSlice("b", b)               // => b len=0 cap=5 []

c := b[:2]
printSlice("c", c)               // => c len=2 cap=5 [0 0]

d := c[2:5]
printSlice("d", d)               // => d len=3 cap=3 [0 0 0]

e := c[2:]                       // it still defaults to len(e)
printSlice("e", e)               // => e len=0 cap=3 []

f := c[2:6]
printSlice("f", f)               // => panic: runtime error: slice bounds out of range

g := b[2:]
printSlice("g", g)               // => panic: runtime error: slice bounds out of range
```

Interaction between len, cap and slicing only got apparent to me after the above experiement. The upper bound of slicing is bound by cap, but defaults to len, while the lower bound is bound by len, and defaults to 0. The len of returned slice will be the range specified, but the cap will be the lower bound toward the cap.

I guess I should have inferred these from the sentence

> Slices can be re-sliced, creating a new slice value that points to the same array.

in the previous step.

**Comment by louy2** [comment]
Great update! "View of" is such a nice way to capture it. Like a window. Thank you a lot.
