### ISSUE TITLE
encoding/binary, cmd/compile: improve bounds checking hints

### ISSUE THREAD

**Issue by josharian** [golang/go#14900]
CL 20981 added bounds checking hints to encoding/binary, of the form

`b = b[:8:len(b)]`

It would be clearer and simpler and generate less code to use:

`_ = b[7]`

However, the compiler isn't yet able to use such a hint.

This issue is to teach the compiler to use such a hint and to update whatever sites it has already been used. At a minimum, this is encoding/binary, but #14884 suggests using it in the `image` package, and I wouldn't be surprised to find it popping up other places soon as well.

For more background, see the discussion at https://groups.google.com/forum/#!topic/golang-dev/jVP6h21OyL8

Marking tentatively as Go 1.7, because once this gets released, lots of folks will start adding bounds checking hints of one kind or another, and it'd be nice if they were of the shorter form.

**Comment by rasky** [comment]
I think an even clearer hint would be:

```
if len(b) < 8 {
    panic("slice too short")
}
```

Obviously, it would be great if both worked, so that each developer can choose the best for their code.

**Comment by randall77** [comment]
21008 will handle both the `_ = b[7]` and `if len(b) < 8 { panic/return }` idioms.
