### ISSUE TITLE
cmd/compile: remove bounds checking for sub-slices

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#14905]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version devel +259b7ed 2016-03-22 00:18:31 +0000 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
`Linux Ava 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux`

3. What did you do?
```go
func a(in []byte) uint64 {
	return uint64(in[0]) | uint64(in[1])<<8 | uint64(in[2])<<16 | uint64(in[3])<<24 |
		uint64(in[4])<<32 | uint64(in[5])<<40 | uint64(in[6])<<48 | uint64(in[7])<<56
}

func b(p []byte) uint64 {
        p = p[:16]
	return a(p[8:8])
}
```

4. What did you expect to see?
No check for p[8:8]

5. What did you see instead?
```asm
        0x001a 00026 (blah.go:10)       CMPQ    CX, $8
        0x001e 00030 (blah.go:10)       JCS     $0, 39
```

On a side note, by inlining that function by hand, some of my code is now faster than using unsafe, so there's that.

Amazing job with the SSA branch guys.

**Comment by ianlancetaylor** [comment]
CC @randall77 @dr2chase

**Comment by randall77** [comment]
I think you mean p[8:16], not p[8:8].  p[8:8] is guaranteed to panic when given to a.

But I think your general issue is still there.  p[8:16] looks ok, but p[7:15] has the same extra comparison in there that p[8:8] has.  After we do cap(p)>=16, we know to get rid of another cap(p)>=16, but not a cap(p)>=15.

@brtzsnr

**Comment by brtzsnr** [comment]
It should be `p = p[:16:len(p)]` otherwise you extend p over the original length. This is binary.BigEndian.Uint64(), right? Why not use that instead, we might be able to do something faster your example.

**Comment by brtzsnr** [comment]
There is some more opportunity here to optimize:

```
    v9 = Const64 <int> [16]
    v8 = SliceLen <int> v7
    v17 = IsSliceInBounds <bool> v9 v8
```

So we have v8 >= v9. Later
```
    v25 = Const64 <int> [8]
    v35 = Eq64 <bool> v25 v8
```

v35 cannot be true. Related to #14900.

**Comment by brtzsnr** [comment]
I think this is fixed after https://go-review.googlesource.com/#/c/21008/

**Comment by OneOfOne** [comment]
Yep, I just confirmed, closing.
