### ISSUE TITLE
CanonicalMIMEHeaderKey in `net/textproto` wrongly considers underscores to be an invalid header byte

### ISSUE THREAD

**Issue by cstrahan** [golang/go#14907]
`CanonicalMIMEHeaderKey` in `net/textproto` wrongly considers underscores to be an invalid header byte. Per http://tools.ietf.org/html/rfc7230#section-3.2, underscores are perfectly acceptable in in header names.

This breaks my code, where the browser sends a header of `user_dn`, and I attempt to get the value via `header.Get("User_Dn")`. I now have to manually traverse the `Header` map and perform a case-insensitive comparison in order to work around this bug.

**Comment by bradfitz** [comment]
Dup of #13767, which has been fixed for Go 1.7.
