### ISSUE TITLE
golang closure(anonymous function) output wrong result

### ISSUE THREAD

**Issue by yujinliang** [golang/go#14911]
go 1.6 
intel x86 on mac osx EI Capitan

my test code here:

package main

import "fmt"

func main()  {

	i := 10;
	closure1 := func() {

		fmt.Printf("closure, i: %d\n", i)
		i = 15
	}

	closure1()

	fmt.Printf("in main, i: %d\n", i)

	closure2 := func(x int) {

		fmt.Printf("function call, pass parameter, i: %d\n", x)

	}
	//closure2(i)

	i = 20

	closure1()
	closure2(i) **# //I think the output of the closure2 should be 20, but the real output is 15, i do not know why???**
	
}

call me scott ,anybody can help me , thanks in advance , my email : 285779289@qq.com

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions
