### ISSUE TITLE
tour: can't edit code on Nexus 5X

### ISSUE THREAD

**Issue by dmytrobr** [golang/go#14912]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
2. What operating system and processor architecture are you using (`go env`)?
   https://tour.golang.org/methods/4
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   A link on play.golang.org is best.

Can't edit code in sandbox from Go tutorial on my Nexus 5x. I'm able to type nee code, but existing code "backspace" does not work ( does nothing)
1. What did you expect to see?
   I should be able to edit code in go sandbox as any other web form
2. What did you see instead?

**Comment by dmytrobr** [comment]
Why did you close it?

**Comment by davecheney** [comment]
I am very sorry, this was an accident.

**Comment by dmytrobr** [comment]
Thank you for updating title anyway :)

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by campoy** [comment]
I can confirm this is a bug, I can also confirm this is really weird and help is welcome 😄 
Working on it now

**Comment by nathany** [comment]
Does it make any difference whether syntax highlighting is on or off?

Does https://play.golang.org also misbehave or does backspace work fine there?

(I don't have a Nexus 5X to test on)

**Comment by nathany** [comment]
Here is a related issue in CodeMirror:

https://github.com/codemirror/CodeMirror/issues/2234#issuecomment-75757336

**Comment by peggyl** [comment]
I don't believe it's specific to Nexus 5X. I was able to reproduce on Nexus 6 (phone) and Nexus 9 (tablet), both on Android 6.0.1.

**Comment by nathany** [comment]
Most likely a problem on any Android device. It sounds like a newer version of CodeMirror will solve the problem, though of course it needs testing. I'd help but I don't have any Android devices 😱 and I think @campoy has it under control. 

Thanks for reporting the issue @dmytrobr.

**Comment by dmytrobr** [comment]
https://play.golang.org work fine, btw. 

One more detail, I can use backspace on the text I typed in. Until I press format button. After that backspace doesn't work on any text. Syntax on/off does not make any difference.

Thank you for following up on this

**Comment by seankhliao** [comment]
I'm guessing this is no longer relevant
