### ISSUE TITLE
Fortran test fails on windows because it uses bash script

### ISSUE THREAD

**Issue by gshimansky** [golang/go#14926]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +3eaa304 Sun Mar 20 04:37:04 2016 +0000 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Users\gashiman\Documents\work\golang
set GOTOOLDIR=C:\Users\gashiman\Documents\work\golang\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\gashiman\AppData\Local\Temp\go-build867009826=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

When running cmd //c all.bat I get the following error in tests:

```
##### ../misc/cgo/fortran
2016/03/23 13:06:00 Failed: fork/exec ./test.bash: %1 is not a valid Win32 application.

```
4. What did you expect to see?

Either exclude this test on windows, use windows compatible script or require to run it using a mingw bash shell.

5. What did you see instead?

**Comment by ianlancetaylor** [comment]
Dup of #14929 .
