### ISSUE TITLE
net/http/httptest: something about the ResponseRecorder change

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#14928]
This seems like a significant addition that should be mentioned.

Associated with this is a change to net/http/httptest.ResponseRecorder
that ended up breaking our tests because for historical reasons
we were constructing the ResponseRecorder directly with the HeaderMap
field, expecting that that be reflected in result of the Header method,
but that's no longer the case.

It was an easy fix and we shouldn't have been doing that anyway, but
a reminder that it's easy to break things even when keeping the
exposed API ostensibly the same.

**Comment by bradfitz** [comment]
Go has supported Trailers in net/http for ages. Which particular change are you talking about?

**Comment by cmarcelo** [comment]
I'm guessing the change is https://github.com/golang/go/commit/c69e6869c9793872cb0282008ea8ab643a92da65 but that isn't in Go 1.6.

Before that change it was possible for the handler to access the values in the (previously set) HeaderMap. Should we re-enable this use case? @bradfitz

**Comment by rogpeppe** [comment]
I'm sorry - I hadn't noticed the Trailer stuff before and a brief git blame
made me think it was new. c69e686 is indeed the change I'm talking
about, and yes, it's not in Go 1.6. It did break our tests, but it's
arguable whether that's a problem (FWIW we were creating the
ResponseRecorder directly to remain backwardly compatible with an old
API that used it, even though we changed all our tests to use httptest.NewServer
instead for better correspondence of tests to real world behaviour).

**Comment by bradfitz** [comment]
How were you creating the ResponseRecorder? With a HeaderMap already made? Can you post a minimal test that passed before and fails now?
