### ISSUE TITLE
Why is "const true = false" allowed?

### ISSUE THREAD

**Issue by Zhomart** [golang/go#14925]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

https://play.golang.org

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Run a small program:
```
package main

import "fmt"

const true = false

func main() {
    if (true == false) {
        fmt.Println("True equals to false")
    }
    fmt.Println("Hello World")
}
```

https://play.golang.org/p/KwePsmQ_q9

4. What did you expect to see?

Error or warning message that I'm creating constant with already defined name, and potentially breaking whole app.

5. What did you see instead?

Running without a problem. No warnings or anything to prevent creating new constant with already defined name.

**Comment by bradfitz** [comment]
This is working as intended. For questions, see https://golang.org/wiki/Questions
