### ISSUE TITLE
cmd/compile: regression in 69a7c15

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#14920]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version devel +5cdb3d0 2016-03-22 20:35:53 +0000 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
Linux amd64

3. What did you do?
```bash
go get -u github.com/OneOfOne/xxhash
go test -bench=XXChecksum64\$ -benchtime 3s -tags safe github.com/OneOfOne/xxhash
```

4. What did you expect to see?
`BenchmarkXXChecksum64-32        20000000               291 ns/op`

5. What did you see instead?
`BenchmarkXXChecksum64-8          5000000               870 ns/op`

I ran a bisect and the offending commit is 69a7c152a72c713032498bfbc6ec7c41d84a4b63.

**Comment by randall77** [comment]
This looks like 69a7c15 broke the combine-8-byte-loads-into-a-quadword-load optimization.  That's what the slowdown is coming from.  I'll see if I can figure out why.
