### ISSUE TITLE
cmd/go: fix go get for paths ending with .go

### ISSUE THREAD

**Issue by henvic** [golang/go#14923]
1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/henvic/projects/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
Tried to clone github.com/launchpad-project/api.go with:
`go get github.com/launchpad-project/api.go`

4. What did you expect to see?
Expected `go get` to work as intended.

5. What did you see instead?
stat error (not found).

I have written and sent a one-line patch to https://go-review.googlesource.com/#/c/20893/1

This affects https://github.com/gojp/goreportcard/issues/90 as well.

**Comment by ianlancetaylor** [comment]
That is kind of a terrible name for that directory.  It's confusing to use because the package name does not match the directory name.  But I guess I can't think of a reason that the go tool should not support it.

**Comment by minux** [comment]
It has happened before, if we accept .go import paths, then what about go
build with such paths? How could go build disambiguate such import paths
with a Go source file? No, i don't think trying both interpretations is the
way to go.

I vote for this being working as intended.

**Comment by davecheney** [comment]
I agree with @minux there is already enough confusion around go build and go test supporting `.go` files vs the recommend use of packages. To allow the go tool to fetch a package that has a _directory_ named `something.go` will just add more confusion to an area newcomers already find difficult.

The clincher for me is `package something.go` is not a valid package declaration, so the name of directory cannot match the packages' name.

I vote to close this as unfortunate.

**Comment by henvic** [comment]
@minux,

I don't get your concerns about go build with such paths. Can't go just check if the path is a file or a directory?

My package is not the only one I have found ending in .go. I can very well rename it to have the .golang suffix (or any other name) and avoid this issue. But what about the several packages out there with the same issue (and future ones that will run into it eventually)?

I agree that the name of the package is not good, but go tools failing inconsistently due to directories with the .go suffix without being noisy about it is worse imho.

Reference: https://github.com/gojp/goreportcard/issues/90

**Comment by henvic** [comment]
What about adding info to the docs that directories should never end with .go and / or failing noisy when it happens for the know reasons?

**Comment by henvic** [comment]
Or, better yet, explaining that projects / package directories should always use valid package names...

**Comment by henvic** [comment]
Blocked on Code-Review Label
https://go-review.googlesource.com/#/c/20893/
