### ISSUE TITLE
cmd/compile: windows build alwasy stop

### ISSUE THREAD

**Issue by mattn** [golang/go#14922]
1. What version of Go are you using (`go version`)?

  tip

2. What operating system and processor architecture are you using (`go env`)?

  Windows10 64bit

3. What did you do?

  make.bat

4. What did you expect to see?

  build success without errors

5. What did you see instead?

  build failure without errors :-(

```
...
cmd/trace
cmd/pprof/internal/plugin
cmd/pprof/internal/report
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/pprof/internal/commands
cmd/pprof/internal/fetch
cmd/link
cmd/pprof/internal/driver
cmd/pprof/internal/symbolizer
cmd/pprof/internal/symbolz
cmd/vet/internal/whitelist
cmd/yacc
cmd/pprof
cmd/vet
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/x86
cmd/compile
```
After this, i can see the prompt of cmd.exe without any messages or action.

![](http://go-gyazo.appspot.com/3e8d86cb9ca39bba.png)

**Comment by randall77** [comment]
The build has completed successfully.
The go.exe and related tools should be in the ..\bin directory.
Maybe you are asking how to use the tools after building?

**Comment by mattn** [comment]
Ah, right. Sorry. I don't set PATH into $GOROOT/bin.

**Comment by mattn** [comment]
But AFAIK, the last line was like below.
```
---
Installed Go for windows/amd64 in c:\go
Installed commands in c:\go\bin
```
