### ISSUE TITLE
go tool vet complain about package name for *_test.

### ISSUE THREAD

**Issue by gaillard** [golang/go#14933]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
amd64 linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Created a test in the same dir as the package api except the test package was api_test. Should go vet complain here?

4. What did you expect to see?
No error?

5. What did you see instead?
package api_test; expected api

**Comment by broady** [comment]
Yes. Your package name for tests should be the same as for your code.

**Comment by gaillard** [comment]
Ah ok thanks, was the special handling for _test only meant for the stdlib?
Also, go vet didn't report it only go tool vet -v did, is that intentional? I was under the impression go vet runs all checks by default.

**Comment by dominikh** [comment]
As far as I know, `*_test` test packages aren't limited to the standard library. Their main purpose is to break circular dependencies, which is equally valid for 3rd party code as it is for the stdlib. Furthermore, a fair amount of people use them to write blackbox tests.

However, I'm not sure there's an issue here. `-v` prints verbose information, and the "package api_test, expected api` is likely to be a semi-internal debug message related to the type checker. If it was an offence that the tool wanted to report to the user, it would do so without the `-v` flag, too.

**Comment by dominikh** [comment]
The error is returned by `config.Check` in the `check` function in `types.go`. And this only occurs when using `go tool vet` on a set of files, as all files are expected to be in the same package. If you use `go vet`, which deals with Go packaging, it will work correctly and test the two packages separately.

**Comment by gaillard** [comment]
Ah that last part makes sense, thanks.

**Comment by gaillard** [comment]
I am also trying to diagnose where /usr/local/go vet ./somepackage is working on my host but not in a docker container. This is after a fresh untar of the go1.6.linux-amd64.tar.gz on both. Only difference in go env. One is reporting a struct field not using key and the other is not. Any ideas?
