### ISSUE TITLE
gccgo internal compiler error on case aStruct{}

### ISSUE THREAD

**Issue by bz2** [golang/go#14931]
Compiling a switch with a struct literal in a case statement hits a gccgo internal compiler errror.

*What version of Go are you using (`go version`)?*

```
$ gccgo --version
gccgo (Ubuntu 4.9.3-0ubuntu4) 4.9.3
```

*What operating system and processor architecture are you using (`go env`)?*

Ubuntu 14.04 PPC64el.

*What did you do?*

http://play.golang.org/p/70E3YlrAYG

Reduced test case from:

<https://github.com/juju/charmstore/blob/a19f96921f585203d9d9d45e0dad5987d35da8c8/internal/v5/api.go#L358>

*What did you expect to see?*

```
$ go run bug.go
As expected
```

*What did you see instead?*

```
$ gccgo-go run bug.go
# command-line-arguments
In function ‘main.main’:
go1: internal compiler error: in fold_binary_loc, at fold-const.c:10124
```

**Comment by ianlancetaylor** [comment]
Thanks for the bug report.  This is already fixed in GCC 5.

**Comment by bz2** [comment]
Thanks. Google let me down on finding an existing bug against 4.9 then.
