### ISSUE TITLE
all: testdata/*.gz files should zero mtime in headers

### ISSUE THREAD

**Issue by rsc** [golang/go#14937]
Apparently Debian expects to be able to zero mtimes in imported trees. I don't understand exactly why that's a problem, since I don't think we look at the mtime, but it's easy enough to zero those bytes to make Debian happy. We should probably do that.

---------- Forwarded message ---------
From: Sean Burford <sburford@google.com>
Date: Wed, Mar 23, 2016 at 7:20 PM
Subject: Fixing timestamps in golang testcase .gz files?
To: Russ Cox <rsc@google.com>

Hi,

In https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819030 I ask the golang debian package maintainers to skip overwriting of the gzip header mtimes on these golang files (because their reproducible build script produces unique versions of these files with every new package version):
./usr/share/go/src/encoding/json/testdata/code.json.gz
./usr/share/go/src/debug/elf/testdata/hello-world-core.gz
./usr/share/go/src/compress/gzip/testdata/issue6550.gz

Looking at the source for the normalizer (https://anonscm.debian.org/git/reproducible/strip-nondeterminism.git/tree/lib/File/StripNondeterminism/handlers/gzip.pm), a global fix would be to zero the mtimes on these files upstream (in the go source).  ie. zero bytes 4-7 in each of those files.

How would I go about arranging this?

**Comment by cespare** [comment]
I'll send the CL.

**Comment by mwhudson** [comment]
On 24 March 2016 at 13:21, Caleb Spare <notifications@github.com> wrote:

> I'll send the CL.
>
Thanks, I'd been looking at the bug report and getting slightly confused by
it :-)

**Comment by minux** [comment]
if our test suite doesn't complain about the changed mtime
by Debian's reproducible build script, why should we care
about changed mtime in the *.gz files.

**Comment by cespare** [comment]
@minux 

> *.gz files are not compressible, so changing
> the 120KB file will add 120KB to the repo, or does git do
> delta compression on binary files too?

Yes, binary files can be delta-compressed in packfiles just fine.
