### ISSUE TITLE
cmd/compile: confusing type checking error

### ISSUE THREAD

**Issue by aclements** [golang/go#14948]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.6 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   linux/amd64
3. What did you do?
   http://play.golang.org/p/_P4s_RvFbr

This program mistakenly defines a function called "color" that returns a "color.Color". The intent was for the return type to refer to the "image/color" package, but of course the name was shadowed by the function itself.
1. What did you expect to see?
   A non-confusing error message perhaps explaining that "color" is a function or perhaps that "color" refers to itself.
2. What did you see instead?

```
prog.go:9: typechecking loop involving color
    prog.go:9 color.Color
    prog.go:9 <T>
    prog.go:9 color
    prog.go:9 <node DCLFUNC>
```

While technically correct, this error message reads like an internal failure of the type checker, especially since it's outputting internal compiler node names and gives no details about what lines 2 through 5 mean.

/cc @griesemer

**Comment by griesemer** [comment]
For the reference: gotype complains with
```
$ gotype x.go
x.go:9:14: invalid operation: color (value of type func()) has no field or method Color
```

**Comment by ianlancetaylor** [comment]
gccgo says

    foo.go:9:19: error: expected package
     func color() color.Color {
                       ^

**Comment by griesemer** [comment]
With Go 1.18 we now get the `go/types` (`types2`) error:
```
./prog.go:9:20: color.Color undefined (type func() has no field or method Color)
```
which seems pretty good. Closing.
