### ISSUE TITLE
x/crypto/ssh: add DialTimeout

### ISSUE THREAD

**Issue by corny** [golang/go#14941]
I need the ability to set a timeout for dialing.
My patch: https://github.com/digineo/crypto/commit/6aa3ece94bfd415686558665fec0e0e9bb6dd93a

**Comment by bradfitz** [comment]
See https://golang.org/doc/contribute.html for instructions on how to send a code review.

**Comment by corny** [comment]
Ok, done: https://go-review.googlesource.com/#/c/21136/
