### ISSUE TITLE
time:timer stop ,how to use?

### ISSUE THREAD

**Issue by koggle** [golang/go#14947]
package main

import "time"
import "fmt"

func main() {
	timer1 := time.NewTimer(time.Second * 2)
	c := make(chan time.Time, 1)
	c <- time.Now()
	t := <-c
	timer1.C <- t
	fmt.Println("Timer 1 expired")

}

prog.go:11: invalid operation: timer1.C <- t (send to receive-only type <-chan time.Time)

**Comment by ianlancetaylor** [comment]
Please see https://golang.org/wiki/Questions .
