### ISSUE TITLE
misc/cgo: TestSignalForwardingExternal flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14956]
TestSignalForwardingExternal was seen being flaky on trybots:

https://storage.googleapis.com/go-build-log/2edf97e5/linux-386_fc7f575b.log
```
##### misc/cgo/testcarchive
--- FAIL: TestSignalForwardingExternal (60.49s)
	carchive_test.go:340: test program succeeded unexpectedly
FAIL
2016/03/25 02:52:47 Failed: exit status 1
```

/cc @ianlancetaylor @jtsylve

**Comment by jtsylve** [comment]
I don't understand how this can be an intermittant problem on the trybots.  I haven't been able to trigger it once locally.  The fact that the test ran the full 60 seconds leads me to believe that the signal isn't being delivered.  I'm not sure what would cause this.

**Comment by jtsylve** [comment]
@bradfitz looking at http://build.golang.org there seems to be one x64 linux test that passes consistantly.  What's OS is that build using?  What makes it different than the others?

**Comment by ianlancetaylor** [comment]
It's happening on two different amd64 builders:

http://build.golang.org/log/ad4c7de6b6b335379c5059d6e1d41dac75b523f3
http://build.golang.org/log/9eb96591cddd20ba66665654e3c5d7813a6f75f1

It's happening on 386:

http://build.golang.org/log/fde75bb1881d91a80ba06ea071dae2ced173da26

I was able to reproduce it on my laptop after 35 runs.  I will investigate.

**Comment by ianlancetaylor** [comment]
The problem is that sometimes the SIGSEGV is delivered to one of the threads started by Rungoroutines, which causes it to be ignored.  Testing a fix.

**Comment by jtsylve** [comment]
Why is this only an issue on Linux?

**Comment by ianlancetaylor** [comment]
In general the signal will be delivered to the main thread.  However, if the main thread is already running in the kernel, it won't be.  The implementation of sleep in older versions of glibc happens to do some extra work like disabling SIGCHLD.  I think that is what is giving the opening for the signal to be delivered to a different thread.

**Comment by jtsylve** [comment]
Hmm, so if it's just a race condition, we can add a 1 second delay between when the "OK" trigger is received and when we raise the signal.

**Comment by ianlancetaylor** [comment]
Every 1 second delay in a test slows everybody down by a second.

I'm testing a patch.
