### ISSUE TITLE
1.6 http package doc incorrectly states support for HTTP/2 is automatic

### ISSUE THREAD

**Issue by hapnermw** [golang/go#14950]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)? 1.6

2. What operating system and processor architecture are you using (`go env`)? OS X, darwin-64

3. What did you do? 
Attempted to use http Client for HTTP/2

4. What did you expect to see?
Client supported HTTP/2

5. What did you see instead?
Client only supported HTTP 1.1

You must still use golang.org/x/net/http2 ConfigureTransport to create an HTTP/2 client. I verified this with the http2.golang.org. Both the http docs and the golang.org/x/net/http2 docs imply that the 1.6 http package now automatically support HTTP/2 for both Client and Server. They do not.

**Comment by ianlancetaylor** [comment]
It's an unfortunate known bug, already fixed on tip.  Issue #14391.
