### ISSUE TITLE
Get current slice..

### ISSUE THREAD

**Issue by amanuel2** [golang/go#14953]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/workspace"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
```
func Join(stringArray []string, seperator string ) string{
    for _,v:=range stringArray{
        fmt.Println(v[i])
    }
}
sampleString := []string{"Amanuel","Is","Programming"}
    Join(sampleString,"1")
```

4. What did you expect to see?
Like the letters.... 

Amanuel
Is 
Programming

5. What did you see instead?

This...
```
109
115
114

```

**Comment by bradfitz** [comment]
This is not a bug. For questions about Go, see https://golang.org/wiki/Questions.
