### ISSUE TITLE
no fsnotify on SunOS / Solaris / Illumos

### ISSUE THREAD

**Issue by tidux** [golang/go#14968]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.5.2 solaris/amd64`

If it matters, this is on SmartOS inside of a Zone, which is its own ZFS dataset.  

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH="/home/jon/go"
GORACE=""
GOROOT="/opt/local/go"
GOTOOLDIR="/opt/local/go/pkg/tool/solaris_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
jon@abydos:~ > cd go/src/github.com/mattermost/platform && make build
```

4. What did you expect to see?
I expected Mattermost and its dependencies to compile and give me a working binary.

5. What did you see instead?
```
Building mattermost server
/home/jon/go/bin/godep go clean  -i ./...
/home/jon/go/bin/godep go install  -ldflags "-X github.com/mattermost/platform/model.BuildNumber=dev -X 'github.com/mattermost/platform/model.BuildDate=March 25, 2016 07:20:31 PM UTC' -X github.com/mattermost/platform/model.BuildHash=f4e5fb711f5ace84793e9343d9deda9ac6aee636 -X github.com/mattermost/platform/model.BuildEnterpriseReady=false" ./...
utils/html.go:12:2: no buildable Go source files in /home/jon/go/src/github.com/mattermost/platform/Godeps/_workspace/src/gopkg.in/fsnotify.v1
godep: go exit status 1
Makefile:128: recipe for target 'build' failed
make: *** [build] Error 1
```
There is no fsnotify for Solaris/Illumos like there is for the BSDs, Darwin, or Linux, which causes multiple applications like whyrusleeping/gx and mattermost/platform to fail to build on Illumos.

**Comment by ianlancetaylor** [comment]
I think you need to report this problem against github.com/mattermost or gopkg.in/fsnotify.  I don't see what the Go project can do to fix this.

I'm going to close this issue, but please free to reopen if you think there is something to be fixed in the Go tools or the Go standard library.
