### ISSUE TITLE
cmd/compile: skip ptr writeback for appends which don't grow

### ISSUE THREAD

**Issue by randall77** [golang/go#14969]
```
func(t *[]int) {
    *t = append(*t, 7)
}
```
We only need to write the pointer (and the capacity) back when we take the growslice path.  For the standard path, only the length needs to be written back.

See #14921 and #14855 .

**Comment by randall77** [comment]
Looks like this is related to the following in SSA (ssa.go:OAS case):
```
		if rhs != nil && rhs.Op == OAPPEND {
			// Yuck!  The frontend gets rid of the write barrier, but we need it!
			// At least, we need it in the case where growslice is called.
			// TODO: Do the write barrier on just the growslice branch.
			// TODO: just add a ptr graying to the end of growslice?
			// TODO: check whether we need to do this for ODOTTYPE and ORECV also.
			// They get similar wb-removal treatment in walk.go:OAS.
			needwb = true
		}
```
So we need to be less aggressive in adding back the write barrier.  The frontend basically punts to the backend to decide if write barriers are needed (walk.go, OAS case):
```
			if r.Op == OAPPEND {
				// Left in place for back end.
				// Do not add a new write barrier.
				break opswitch
			}
```

For `*p = append(*p, x)` we need to generate code like:
```
a := *p
newlen := a.len+1
if newlen > a.cap {
   a = growslice()...
   p.ptr = a.ptr
   p.cap = a.cap
}
p.len = newlen
a.ptr[newlen-1] = x // with a write barrier, if needed
```
This code is similar to what we generate for the generic OAPPEND case, maybe we can share some code.

See #15023 for another case of this same problem.

**Comment by josharian** [comment]
I'll take a look at this.
