### ISSUE TITLE
go1.6 version, go get not supported insecure

### ISSUE THREAD

**Issue by JoseFeng** [golang/go#14961]
go version go1.6 linux/amd64

go get -insecure -v 192.168.6.70/golib/beego 

> 
Fetching https://192.168.6.70/golib/beego?go-get=1
Parsing meta tags from https://192.168.6.70/golib/beego?go-get=1 (status code 200)
get "192.168.6.70/golib/beego": found meta tag main.metaImport{Prefix:"192.168.6.70/golib/beego", VCS:"git", RepoRoot:"https://192.168.6.70/golib/beego.git"} at https://192.168.6.70/golib/beego?go-get=1
> 

add  -insecure param  still use https

**Comment by bradfitz** [comment]
`-insecure` doesn't mean to use http immediately. It means it can use invalid TLS certs if https is available, else it can fall back to http. So I think this is working as intended.

**Comment by JoseFeng** [comment]
How to let him use only http，Because my github use https prompt invalid TLS certs。
`
[root@php-6-174 ~]# go get 192.168.6.70/golib/goredis
`

> 
package 192.168.6.70/golib/goredis: unrecognized import path "192.168.6.70/golib/goredis" (https fetch: Get https://192.168.6.70/golib/goredis?go-get=1: x509: cannot validate certificate for 192.168.6.70 because it doesn't contain any IP SANs)
>

**Comment by JoseFeng** [comment]
@bradfitz 

How to let him use only http，Because my github use https prompt invalid TLS certs。
`
[root@php-6-174 ~]# go get 192.168.6.70/golib/goredis
`

> 
package 192.168.6.70/golib/goredis: unrecognized import path "192.168.6.70/golib/goredis" (https fetch: Get https://192.168.6.70/golib/goredis?go-get=1: x509: cannot validate certificate for 192.168.6.70 because it doesn't contain any IP SANs)
>

**Comment by bradfitz** [comment]
`192.168.6.70` is not a github URL, so I'm not sure what you mean. But this is not a forum for questions. See https://golang.org/wiki/Questions for the best places for such discussion.
