### ISSUE TITLE
x/net: Add a BPF package

### ISSUE THREAD

**Issue by danderson** [golang/go#14982]
From #14974, @mikioh suggested adding a BPF/eBPF package to x/net to handle compiling BPF/eBPF programs. Filing this bug to track that proposal and work.

I have a BPF package in progress, which I'll send out for an API review shortly. Looking at the spec for eBPF, while the VMs have similar names the ISA is different enough that I think we should have two separate packages, and have a FromBPF() helper in the ebpf package to translate Classic BPF into the extended form.

**Comment by danderson** [comment]
Initial implementation done for BPF, working on eBPF.

**Comment by mikioh** [comment]
Much appreciated. One thing: Perhaps it might be better to drop LoadIPv4HeaderLen for avoiding confusion because that's a Linux-specific extension not included in LoadExtension.

**Comment by danderson** [comment]
Hmm, AFAICT LoadIPv4HeaderLen is part of standard BPF, it's mentioned in the original paper (http://www.tcpdump.org/papers/bpf-usenix93.pdf). It was a compromise to the "purity" of the VM because looking at L4 headers is very common, and it requires some annoying math to calculate the IPv4 header length - so the designers put it in as a standalone opcode.

I'll check the BPF source code for freebsd/netbsd and see if it's implemented there.

**Comment by mikioh** [comment]
Well, I mean, I suppose that the classic BPF_MSH (stands for BSD's memory buffer shift?) simply reads 4 bits from the given offset whatever the frame is. But I may be wrong.

**Comment by danderson** [comment]
Oh, yeah, LoadIPv4HeaderLen is just a BPF_MSH under the hood, there's nothing that explicitly checks for IPv4-ness. In practice, the operation "read the lower nibble of a byte, multiply by 4, and load into the indirection register" is only ever used to calculate the IPv4 header length to skip past it, so I gave it an IPv4-specific name. Do you think we should use a more generic name?

**Comment by mikioh** [comment]
> Do you think we should use a more generic name?

Or drop it. I'm fine either way.

**Comment by danderson** [comment]
Reducing the scope of this issue to just BPF, not eBPF - that VM is quite a bit more complex, so I'd like to track it separately.

Given that, this bug is done.
