### ISSUE TITLE
cmd/compile: dedup gclocals at compile time

### ISSUE THREAD

**Issue by skohanim** [golang/go#14983]
### Version:
`go version devel +4ffa5eb Sun Mar 27 05:31:54 2016 +0000 linux/amd64
`
### Env:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/shaharko/gopath"
GORACE=""
GOROOT="/home/shaharko/src/go_master"
GOTOOLDIR="/home/shaharko/src/go_master/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build742740600=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```
```
$ go tool nm pkg/linux_amd64/io.a | grep gclocals | awk '{ print $3 }' |  wc -l
142 # total gclocals
$ go tool nm pkg/linux_amd64/io.a | grep gclocals | awk '{ print $3 }' | uniq | wc -l
38  # unique gclocals
```
The symbol duplication factor is ~3.5x.

**Comment by minux** [comment]
it's working as intended. gclocals are content addressable symbols
so the linker will deduplicate them. As the compiler is compiling one
function at a time, or it currently doesn't know that a matching gclocals
symbol has already been emitted.

Perhaps the compiler should check if a matching gclocals has already
been emitted before emitting a new one.

**Comment by skohanim** [comment]
Yes the linker will deduplicate but this should be done by the compiler ahead of time.
It would reduce the object file size and make the linker faster. Possibly also reducing the compiler memory usage.

**Comment by mwhudson** [comment]
Oh wow, I had no idea each .o file contained multiple copies of the gclocals symbols.

**Comment by skohanim** [comment]
Nice! Thanks.
