### ISSUE TITLE
net: TestLookupGoogleSRV flaky on linux-arm bot

### ISSUE THREAD

**Issue by mdempsky** [golang/go#14997]
Looking at build.golang.org right now, all 4 linux-arm failures are due to TestLookupGoogleSRV flakes:

    --- FAIL: TestLookupGoogleSRV (20.05s)
    	lookup_test.go:71: lookup _xmpp-server._tcp.google.com on 10.1.31.38:53: no such host
    FAIL
    FAIL	net	22.518s

http://build.golang.org/log/18b91c9dd84cfa397ae48f92f5806eb64be62d41
http://build.golang.org/log/31c93edec34c46a3b140db465f905f2412b8ef2f
http://build.golang.org/log/afede4adbc79168d91a430d5033cbd9d962d2729
http://build.golang.org/log/e6e72e6ad1f44c4ecd87884374d964bb8497582f

This is also causing trybot flakes; e.g., I had linux-arm flakes on golang.org/cl/21231 and golang.org/cl/21232.

**Comment by bradfitz** [comment]
The scaleway ARM builders have:

```
# cat /etc/resolv.conf  
domain cloud.scaleway.com
search cloud.scaleway.com
nameserver 10.1.31.38
nameserver 10.1.31.39
```

Which explains the error message.

I guess that DNS server just sucks (is flaky).

Maybe the external net tests should hard-code 8.8.8.8?

**Comment by mdempsky** [comment]
I feel like it should be reasonable for tests to assume /etc/resolv.conf points to reliable DNS servers.  What about just configuring the Scaleway ARM VMs to use "nameserver 8.8.8.8" in their /etc/resolv.conf instead of changing any tests?

We should probably also warn Scaleway that their DNS servers appear unreliable.

**Comment by bradfitz** [comment]
Done. Sent https://go-review.googlesource.com/21194 and deployed.
