### ISSUE TITLE
cmd/vet: new(sync.Once) copies lock value: sync.Once contains sync.Mutex

### ISSUE THREAD

**Issue by mholt** [golang/go#14994]
1. What version of Go are you using (`go version`)?
go version devel +ad391c9 Sat Mar 26 12:12:04 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go"
GOTOOLDIR="/home/travis/.gimme/versions/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build398857422=/tmp/go-build"
CXX="g++"
CGO_ENABLED="0"

3. What did you do?
Ran CI tests on Go tip. Tests now fail on code that hasn't changed recently and still passes on Go 1.6. For example: https://travis-ci.org/mholt/caddy/builds/118687079

4. What did you expect to see?
No errors

5. What did you see instead?

```
$ go vet ./...
caddy/config.go:194: function call copies lock value: sync.Once contains sync.Mutex
caddy/config_test.go:114: function call copies lock value: sync.Once contains sync.Mutex
caddy/config_test.go:115: function call copies lock value: sync.Once contains sync.Mutex
```

Relevant lines of code are:

```go
onces[dir.name] = new(sync.Once)
```

```go
map[string]*sync.Once{
    "dummy":  new(sync.Once),
    "dummy2": new(sync.Once),
}
```

Is new() really a function call that is copying a lock value?

**Comment by valyala** [comment]
Should be fixed by the CL https://golang.org/cl/21222
