### ISSUE TITLE
CopyN with net.Conn oddness

### ISSUE THREAD

**Issue by deviantmk** [golang/go#14998]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
win10, intel i5

3. What did you do?
```
package main

import (
	"log"
	"io"
	"net"
	"fmt"
)

func main() {

	l, err := net.Listen("tcp", ":4444")
	if err != nil {
	    log.Fatal(err)
	}

	defer l.Close()

	for {
		// Wait for a connection.
		conn, err := l.Accept()
		if err != nil {
			log.Fatal(err)
		}

		fmt.Println("new connection")

		go func(c net.Conn) {
			// Echo all incoming data.
			n, err := io.CopyN(c, c, 5);

			if err != nil {
				fmt.Println(err)
			}

			fmt.Println(n)
			fmt.Println("connection closed")
			// Shut down the connection.
			c.Close()
		}(conn)
	}
}
```

4. What did you expect to see?
using telnet
```
1 -> 1
2 -> 2
3 -> 3
4 -> 4
5 -> 5

new connection
5
connection closed
```

5. What did you see instead?
```
1 -> 1
2 -> 

new connection
5
connection closed
```

**Comment by bradfitz** [comment]
I don't see a bug here. Let's move questions to a forum. See: https://golang.org/wiki/Questions Thanks!

**Comment by deviantmk** [comment]
what do you mean you don't see a bug, CopyN it takes each single byte as 3 bytes
can you elaborate please

**Comment by bradfitz** [comment]
Let's move this to the mailing list and I and others can help there. Again, there's no bug here. Telnet is sending a carriage return and newline after each byte you enter. Those count towards your 5.

**Comment by deviantmk** [comment]
Thank you sir, approval is pending on the forum.
