### ISSUE TITLE
cmd/compile/internal/ssa/gen: add size expansion

### ISSUE THREAD

**Issue by stemar94** [golang/go#14993]
It would be nice to have a way specifying a rule, which can directly be applied for multiple sizes (e.g. 8,16,32,64)
Would make the .rules files more readable and smaller in size.

I have a [CL](https://go-review.googlesource.com/#/c/21221/) proposing a syntax like:
```go
..=8,16,32,64
(Add.. (Const.. [c]) (Const.. [d])) -> (Const.. [c+d])
```
which semantically expands to
```go
(Add8 (Const8 [c]) (Const8 [d])) -> (Const8 [c+d])
(Add16 (Const16 [c]) (Const16 [d])) -> (Const16 [c+d])
(Add32 (Const32 [c]) (Const32 [d])) -> (Const32 [c+d])
(Add64 (Const64 [c]) (Const64 [d])) -> (Const64 [c+d])
```

I just want to know, if there is any interest in something like this.

Best,
 Marvin

**Comment by randall77** [comment]
No thanks.

By my count this would save ~100 lines of rewrite rules.  I don't think that's the pain point for anyone.

I get that the stutter in the rules can be annoying, but the resulting rules are clear and understandable.  Adding another layer of indirection would save space but impede understanding.
