### ISSUE TITLE
encoding/json: Respect escape sequences in struct tags

### ISSUE THREAD

**Issue by gibson042** [golang/go#15000]
It is impossible to serialize structs into JSON objects with keys containing certain characters, most notably commas (in contrast with all other ASCII punctuation, because they are used to separate key name from tag options). This could be corrected by interpreting escape sequences in the tags as if they were double-quoted strings, which is possible since backslash characters are [reserved](https://github.com/golang/go/blob/5fea2ccc77eb50a9704fa04b7c61755fe34e1d95/src/encoding/json/encode.go#L743).

1. What version of Go are you using (`go version`)?
`go version go1.5.1 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
Attempted to serialize a struct into a JSON object with fields containing commas: http://play.golang.org/p/2KgYUahN8a

4. What did you expect to see?
```json
{
 "a": "A:a",
 "b": "B:\u0062",
 "\\u0063": "EscapedC:\\u0063",
 ",": "Comma:\u002c",
 "\\u002c": "EscapedComma:\\u002c"
}
```

5. What did you see instead?
```json
{
 "a": "A:a",
 "b": "B:b",
 "EscapedC": "EscapedC:\\u0063",
 "Comma": "Comma:,",
 "EscapedComma": "EscapedComma:\\u002c"
}
```

**Comment by bradfitz** [comment]
Is this a solution in search of a problem? Do people actually use commas in JSON object keys?

**Comment by gibson042** [comment]
While it's probably not seen in the wild, I ran into this while trying to be thorough in testing. And even though the impact is low, having the mapping from struct tag to JSON key be non-surjective does seem unnecessarily flawed.

**Comment by bradfitz** [comment]
Okay, let's close this then until there's a use case.
