### ISSUE TITLE
goroutine  semacquire in fmt.Print

### ISSUE THREAD

**Issue by sorawa** [golang/go#15009]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6 window386

2. What operating system and processor architecture are you using (`go env`)?
win xp sp3 

3. What did you do?
goroutine 6537 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x59f23e00, 0xa0, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x59f23e00, 0xa0, 0x100, 0x63250000, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x63259eac, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x63259eac, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x8091f0, 0
xe, 0x63259f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
.

4. What did you expect to see?

5. What did you see instead?

**Comment by bradfitz** [comment]
What is the bug report?

This is incomplete.

**Comment by sorawa** [comment]
goroutine 6240 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x59f23b00, 0x9a, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x59f23b00, 0x9a, 0x100, 0x63250000, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x6325beac, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x6325beac, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63

github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x8091f0, 0xe, 0x6325bf50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:158 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x8091f0, 0xe, 0x6325bf50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveLoop(0x46be4f00)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.go:75 +0x65c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:51 +0x32

goroutine 6529 [select]:
github.com/TriangleGo/gorouter/network.(*Connection).servePacket(0x46be4f00)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:107 +0x70e
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:52 +0x4f

goroutine 6530 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x61c88200, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x61c88200, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x2a211dc8, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x2a211dc8, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63

github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:158 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveHandle(0x46be4f00)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:147 +0x9c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:53 +0x6c

goroutine 6531 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x59f23c00, 0x98, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x59f23c00, 0x98, 0x100, 0x63250000, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x63257eac, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x63257eac, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63


github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x8091f0, 0
xe, 0x63257f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x8091f0, 0xe, 0x63257f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveLoop(0x46be50b0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:75 +0x65c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:51 +0x32

goroutine 6532 [select]:
github.com/TriangleGo/gorouter/network.(*Connection).servePacket(0x46be50b0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:107 +0x70e
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:52 +0x4f

goroutine 6533 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x11233100, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x11233100, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x62f87dc8, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x62f87dc8, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63


github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x81b180, 0
x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveHandle(0x46be50b0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:147 +0x9c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:53 +0x6c

goroutine 6545 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x1f2b7100, 0x99, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x1f2b7100, 0x99, 0x100, 0x63250000, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x63255eac, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x63255eac, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x8091f0, 0
xe, 0x63255f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x8091f0, 0xe, 0x63255f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveLoop(0x612e3950)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:75 +0x65c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:51 +0x32

goroutine 6546 [select]:
github.com/TriangleGo/gorouter/network.(*Connection).servePacket(0x612e3950)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:107 +0x70e
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:52 +0x4f

goroutine 6547 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x27266e00, 0x43, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x27266e00, 0x43, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x63437dc8, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x63437dc8, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x81b180, 0
x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveHandle(0x612e3950)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:147 +0x9c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:53 +0x6c

goroutine 6536 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x61c88500, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x61c88500, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x5d891dc8, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x5d891dc8, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x81b180, 0
x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveHandle(0x46be5410)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:147 +0x9c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:53 +0x6c

goroutine 6537 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x59f23e00, 0xa0, 0x100, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x59f23e00, 0xa0, 0x100, 0x63250000, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x63259eac, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x63259eac, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x8091f0, 0
xe, 0x63259f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x8091f0, 0xe, 0x63259f50, 0x1, 0x1)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveLoop(0x46be5470)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:75 +0x65c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:51 +0x32

goroutine 6538 [select]:
github.com/TriangleGo/gorouter/network.(*Connection).servePacket(0x46be5470)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:107 +0x70e
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:52 +0x4f

goroutine 6539 [semacquire]:
sync.runtime_Semacquire(0x111b2254)
        d:/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0x111b2250)
        d:/go/src/sync/mutex.go:83 +0x19f
os.(*File).write(0x111ce0d8, 0x61c88580, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file_windows.go:395 +0x59
os.(*File).Write(0x111ce0d8, 0x61c88580, 0x43, 0x80, 0x0, 0x0, 0x0)
        d:/go/src/os/file.go:136 +0x6f
fmt.Fprint(0x2141b8, 0x111ce0d8, 0x585d9dc8, 0x1, 0x1, 0x40c7b9, 0x0, 0x0)
        d:/go/src/fmt/print.go:223 +0x8c
fmt.Print(0x585d9dc8, 0x1, 0x1, 0x7246c0, 0x0, 0x0)
        d:/go/src/fmt/print.go:232 +0x63
github.com/TriangleGo/gorouter/logger.(*Logger).Log(0x111b45a0, 0x3, 0x81b180, 0
x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/logger.go:15
8 +0x25b
github.com/TriangleGo/gorouter/logger.Info(0x81b180, 0x17, 0x0, 0x0, 0x0)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/logger/instance.go:
25 +0x111
github.com/TriangleGo/gorouter/network.(*Connection).serveHandle(0x46be5470)
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:147 +0x9c
created by github.com/TriangleGo/gorouter/network.(*Connection).AsyncServe
        d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.
go:53 +0x6c

runtime stack:
runtime.throw(0x808e00, 0xd)
        d:/go/src/runtime/panic.go:530 +0x7f
runtime.(*mcache).refill(0x160de0, 0xb, 0x4570fd98)
        d:/go/src/runtime/mcache.go:121 +0xce
runtime.mallocgc.func2()
        d:/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x1124e430)
        d:/go/src/runtime/asm_386.s:313 +0x5e
runtime.mstart()
        d:/go/src/runtime/proc.go:1048

**Comment by sorawa** [comment]
only catch this  infomation in my  console
is this completed

**Comment by methane** [comment]
mcache.go:121 is:
```
	// Get a new cached span from the central lists.
	s = mheap_.central[sizeclass].mcentral.cacheSpan()
	if s == nil {
		throw("out of memory")
	}
```

So your problem is "out of memory".  Not a runtime bug.

**Comment by sorawa** [comment]
@methane
thanks.
i think it must be " out of memory " error
i saw the pprof , then i found 

`196 @ 0x42d280 0x43a268 0x43983f 0x54c781 0x453701
#	0x54c781	github.com/TriangleGo/gorouter/network.(*Connection).serveHandle+0xa81	d:/go/bin/project/src/github.com/TriangleGo/gorouter/network/connection.go:163`

but in the 
connection:go 163
the code is "select"

`	//loop recv protocol
	for {
		select {
		case data, _ := <-this.TcpChan:
			//logger.Info("TCPHandler %v %v\r\n", data, ok)
			h := router.GetRouter().GetTcpHandler()[data.ModuleId]
			if h != nil {
				c := h.Handle(client,&data)
				if c != nil {
					client = c
				}
			}`

why does "select" produce so many goroutines

**Comment by methane** [comment]
@sorawa How about go to golung-nuts ML?
Here is golang issue tracker.

**Comment by methane** [comment]
If you prefer slack to google groups, there is slack team.
You can find invite form from this blog.
https://blog.gopheracademy.com/gophers-slack-community/

**Comment by bradfitz** [comment]
Let's move this to a forum: See https://golang.org/wiki/Questions

This is not of the form a bug report would need to be in order to be actionable, and there are too many questions to ask to even determine if there is a bug.
