### ISSUE TITLE
cmd/compile: suboptimal compilation of 64-bit OMOD for 386/arm

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15010]
Compiling:

```
package p

func f(t int64) int64 {
        return t%1e9
}
```

for 386 or arm compiles as

```
func f(t int64) int64 {
        return t - runtime.int64div(t, 1e9) * 1e9
}
```

even though we're not able to do anything to optimize the `* 1e9` multiplication.  We might as well just call `runtime.int64mod`.

**Comment by minux** [comment]
is there any performance benefit of using int64mod other
than saving a few bytes of code?

**Comment by mdempsky** [comment]
@minux Looking at https://github.com/golang/go/blob/master/src/runtime/vlrt.go, it seems like there should be.  int64div and int64mod both just call a common dodiv function that calculates (quotient, remainder), and then they return the appropriate value.  So they seem like they should be roughly identical in cost.

The int64div form also costs 48 extra bytes of 386 instructions and 52 extra bytes of arm instructions compared to just calling int64mod.

**Comment by ALTree** [comment]
Both go1.9 and go1.10 generate a `int64mod` call on 386 and arm, so I'm assuming this is fixed.
