### ISSUE TITLE
crypto/elliptic: does not have p128 support

### ISSUE THREAD

**Issue by pctj101** [golang/go#15019]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.5 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
Looked at: https://golang.org/src/crypto/elliptic/

4. What did you expect to see?
A really easy to use implementation of p128

5. What did you see instead?
Only p224 and p256

---

Is there any reason why p128 is not implemented?  

If there is no strong reason against it, if I was to contribute p128 in my spare time would it be rejected for some reason such as "It isn't cryptographically strong enough to be added into golang"?

**Comment by minux** [comment]
128-bit ECC is too weak (~768-bit RSA), and it's not
used by TLS, so I don't think we should add it to
crypto/elliptic.

Of course, you can still use crypto/elliptic with a
custom CurveParams for p128. It's just you won't
get custom assembly implementations.

**Comment by braincommerce** [comment]
@minux Thanks for the feedback!

**Comment by pctj101** [comment]
Thanks for the feedback @minux
