### ISSUE TITLE
cmd/dist: missing zversion.go when building for windows on mac

### ISSUE THREAD

**Issue by dcboy** [golang/go#15018]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
➜  src git:(master) go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/D/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
cd $GOROOT/src
GOOS=windows GOARCH=386 PATH=$PATH ./make.bash

4. What did you expect to see?

##### Building Go bootstrap tool.
cmd/dist
go: open /usr/local/go/src/runtime/internal/sys/zversion.go: no such file or directory

**Comment by ianlancetaylor** [comment]
Note that it is not necessary to run `make.bash` again for a cross-compiler.  Once you've run `make.bash` for darwin/amd64, you can build for Windows by running

    GOOS=windows GOARCH=386 go install PROGRAM

**Comment by minux** [comment]
crosscompiling doesn't need to run make.bash anymore.

Just

GOOS=windows GOARCH=386 go install std
and
GOOS=windows GOARCH=386 go build somePackage

**Comment by davecheney** [comment]
@minux @ianlancetaylor I think we should stop shipping the make.bash and other scripts as part of the binary distributions. They cannot be used safely.

**Comment by adg** [comment]
@davecheney they can't?

**Comment by davecheney** [comment]
@adg in an ideal world, maybe those scripts would work, but when the files
are owned by root, they are a temptation to reach for the sudo hammer and
that'll just make things worse.

You don't need to run ./make.bash to season a Go install for cross
compilation, so I think we should remove the scripts to prevent the
temptation to follow the outdated tutorials on the internet.

**Comment by adg** [comment]
@davecheney I didn't think about root. The scripts do work for people that install the binary tarball or zip under their own usernames.

Maybe we should just remove make/all.bash/bat for the MSI and PKG installers?

**Comment by davecheney** [comment]
> @davecheney I didn't think about root. The scripts do work for people that install the binary tarball or zip under their own usernames.

I don't think this is the case. Our installation instructions tell people to place the contents in `/usr/local/go` and not owned by their own username. 

We strongly discourage people from placing the contents elsewhere as that raises the spectre of GOROOT. 

I agree that these scripts should be stripped from the MSI and PKG installers. I think they should also be stripped from the zip and tar distributions.

If people want to install from source, they should check it out from git.

**Comment by adg** [comment]
> We strongly discourage people from placing the contents elsewhere as that raises the spectre of GOROOT.

See the [Getting Started](https://golang.org/doc/install) docs, where we helpfully explain how to install Go elsewhere. We don't mention permissions at all.

> I agree that these scripts should be stripped from the MSI and PKG installers. I think they should also be stripped from the zip and tar distributions.

Seems reasonable. Should be a trivial change to x/build/cmd/release.

**Comment by minux** [comment]
we still don't understand the problem here, so we shouldn't hurry
to blame make.bash.

zversion.go should exist, and if it's really owned by root, how could
make.bash somehow make it disappear?

**Comment by davecheney** [comment]
@minux, yes. Sorry I distracted the issue by talking about strategies to
talk about overcoming the outdated information on the internet on how to
prepare your Go installation for cross compilation, which are now
unnecessary.

**Comment by bradfitz** [comment]
@dcboy, sure you don't have Go 1.4 or Go 1.5 in /usr/local/go?

What does `/usr/local/go/bin/go version` say?

**Comment by rsc** [comment]
Timed out.

**Comment by JoopClaireIT** [comment]
I just got this problem when checking out go1.7beta1 and compiling it from source, then trying to use it to build master.

**Comment by ianlancetaylor** [comment]
@JoopClaireIT Please show us the exact sequence of commands that you ran.

**Comment by JoopClaireIT** [comment]
```bash-session
~$ cd go/src # I already checked out Go from git before
$ git pull
$ git checkout go1.7beta1
$ GOROOT=/usr/local/go GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
$ sudo rm -r /usr/local/go
$ sudo cp -r /home/joop/go /usr/local/
$ go version
go version devel +3c6b668 Thu Jun 2 00:22:03 2016 +0000 linux/amd64
$ git checkout master
$ GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
##### Building Go bootstrap tool.
cmd/dist
go: open /usr/local/go/src/runtime/internal/sys/zversion.go: no such file
or directory
```

Op do 2 jun. 2016 om 17:31 schreef Ian Lance Taylor <
notifications@github.com>:

> @JoopClaireIT <https://github.com/JoopClaireIT> Please show us the exact
> sequence of commands that you ran.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/golang/go/issues/15018#issuecomment-223328406>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AMmsF8WcYV0792C7r5cLZ7qzU8ESGG12ks5qHvdNgaJpZM4H67ri>
> .
>
-- 
Met vriendelijke groet,

Joop Kiefte

Claire Automotive Support - Galvanistraat 1 - 6716AE - EDE
Tel 0850020211 - www.claireit.nl

**Comment by JoopClaireIT** [comment]
```bash-session
~$ cd go/src # I already checked out Go from git before
$ git pull
$ git checkout go1.7beta1
$ GOROOT=/usr/local/go GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
$ sudo rm -r /usr/local/go
$ sudo cp -r /home/joop/go /usr/local/
$ go version
go version devel +3c6b668 Thu Jun 2 00:22:03 2016 +0000 linux/amd64
$ git checkout master
$ GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
##### Building Go bootstrap tool.
cmd/dist
go: open /usr/local/go/src/runtime/internal/sys/zversion.go: no such file
or directory
```

**Comment by ianlancetaylor** [comment]
I'm not sure I understand.  What directory were you running in--what directory do you get to when you `cd go/src`? 

It does not make sense to set both `GOROOT` and `GOROOT_BOOTSTRAP` to the same directory.  It doesn't really make sense to set `GOROOT` at all when running `all.bash`.  I'm surprised that it worked as well as it did.  Did you mean to set `GOROOT_FINAL` rather than `GOROOT`?

**Comment by Patuti** [comment]
I believe I'm having the same problem here.
It's the first time I'm trying to build it from source so maybe I missed some step.

My env vars:
```
GOARCH=amd64
GOOS=windows
GOROOT_BOOTSTRAP=C:\go
GOROOT_FINAL=D:\personal\labs\go
```

GOROOT_BOOTSTRAP points to my binary dist `go version go1.6.2 windows/amd64`
GOROOT_FINAL points to my local repo of go master branch.

Then, when calling all.bat:
```
D:\personal\labs\go\src>all.bat
##### Building Go bootstrap tool.
cmd/dist
go: open C:\go\src\runtime\internal\sys\zversion.go: Le fichier spécifié est introuvable.
```

**Comment by ianlancetaylor** [comment]
@Patuti Whatever problem that is, it is not this problem, which is about building for Windows on the Mac.  Please take your question to a forum; see https://golang.org/wiki/Questions .  Thanks.
