### ISSUE TITLE
net/http/server: readRequest() should use `Host` member instead of header

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#15015]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
darwin amd64 [os x]

3. What did you do?
See https://github.com/elazarl/goproxy/issues/149
Briefly- in a context of proxy server, I've sent a get request with an absolute URL without `Host` header:
```
GET http://bot.whatismyipaddress.com/ HTTP/1.1


```

4. What did you expect to see?
HTTP Server should parse the `Host` from the URL

5. What did you see instead?
HTTP Server looked up for the `Host` header, instead of the request's host member(which is parsed):
https://github.com/golang/go/blob/master/src/net/http/server.go#L716

This line should be:
```go
hosts, haveHost := req.Host
```

**Comment by elithrar** [comment]
HTTP/1.1 requires a `Host` header field: http://tools.ietf.org/html/rfc2616 (pg. 129)

>  A client MUST include a Host header field in all HTTP/1.1 request
   messages . If the requested URI does not include an Internet host
   name for the service being requested, then the Host header field MUST
   be given with an empty value. An HTTP/1.1 proxy MUST ensure that any
   request message it forwards does contain an appropriate Host header
   field that identifies the service being requested by the proxy. All
   Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request)
   status code to any HTTP/1.1 request message which lacks a Host header
   field.

**Comment by bradfitz** [comment]
Yeah, I agree with @elithrar. I don't see a bug here.

With HTTP/1.0 you don't need a Host header, but with HTTP/1.1 you do.

**Comment by AlmogBaku** [comment]
@bradfitz @elithrar 
Basically, your right, but why not using the parsed header in order to "recover" misbehaved clients?
Other servers do that..

**Comment by bradfitz** [comment]
This is not the forum for debating such things. Let's move this to the mailing list.
