### ISSUE TITLE
x/tools/cmd/godoc: list packages in the correct order

### ISSUE THREAD

**Issue by perillo** [golang/go#15020]
https://github.com/golang/go/wiki/CodeReviewComments#imports says that `"Imports are organized in groups, with blank lines between them. The standard library packages are in the first group."`.

However godoc simply sorts imports in lexicographical order.
This makes it very hard to find the documentation of a standard package.

The order should be:
1) standard library packages
2) golang.org/x/ packages
3) other packages

**Comment by ianlancetaylor** [comment]
godoc sorts imports within groups.

If you want to maintain groups, use golang.org/x/tools/cmd/goimports.

**Comment by perillo** [comment]
Sorry, but what do you mean with "use golang.org/x/tools/cmd/goimports".

I'm referring to the package index available at `http://localhost:6060/pkg/`.

As you can see from https://imagebin.ca/v/2c2N6BhjBUmp, finding documentation for a standard package is quite a pain, since all third party package are interleaved with standard packages.

**Comment by ianlancetaylor** [comment]
I'm sorry, I misunderstood your comment.  I don't understand your reference to the CodeReviewComments wiki page, as that has nothing to do with what godoc displays.

You are suggesting that godoc should sort the packages it displays differently.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by perillo** [comment]
I added a reference to CodeReviewComments because Go programmers expect to see packages listed in a well defined order, and this order is not respected by godoc.

However the real problem is that godoc package listing seems to be specialized for https://golang.org/pkg/.
Packages are listed in a section named "Standard library".  The problem is that when godoc is executed on a local system, all installed packages are considered part of the standard library.

One possible solution is to add an additional section, that it is only visible when there are third-party packages installed on the system.
