### ISSUE TITLE
cmd/compile: spooky compilation failure

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15029]
https://go-review.googlesource.com/#/c/21333/

When I try testing that CL, I get:

    $ go run run.go
    # go run run.go -- fixedbugs/bug278.go

    bug278.go:21: missing error "cannot|invalid"
    bug278.go:22: missing error "cannot|invalid"

    FAIL	fixedbugs/bug278.go	0.081s
    # go run run.go -- fixedbugs/issue8183.go

    issue8183.go:21: missing error "const initializer len\\(composite literal\\) is not a constant"
    issue8183.go:22: missing error "array bound must be non-negative"
    issue8183.go:22: missing error "const initializer len\\(composite literal\\) is not a constant"

    FAIL	fixedbugs/issue8183.go	0.075s
    exit status 1

I don't see how that's possible.  Either the compiler should have panicked because at some point `t == nil`, or the behavior should have been identical.

/cc @randall77 @josharian

**Comment by josharian** [comment]
Try Fatalf. Panics are caught and handled later, and my guess is that the typchecking error happens before the panic gets printed.

As an aside, it'd sure be nice for Fatalf to print the stack before dying.

**Comment by randall77** [comment]
I too have been annoyed that when the compiler itself fails, you sometimes don't get a good report.  The -h flag to the compiler sometimes helps.  It would be a good thing to clean up / normalize.

Keep in mind though that we're not the target audience.  Error reports need to be understandable and reportable by the average Go user.

**Comment by mdempsky** [comment]
Ugh, yeah, the panic is just getting eaten somewhere.  So at least that clarifies the "spookiness".

Agreed that error reports are targeting the end users.  What was confusing me is that there wasn't any output due to the panic, so I thought it just wasn't triggering at all.  Which made me extra confused why some of the error messages went missing.
