### ISSUE TITLE
cmd/compile: clarify Type.IsPtr and Isptr

### ISSUE THREAD

**Issue by josharian** [golang/go#15028]
`func (t *Type) IsPtr() bool` was introduced for the SSA backend. It reports (roughly) whether type is pointer-shaped, so it returns true for e.g. maps and channels. The "roughly" qualifier is because there are some things that are pointer-shaped (`struct { i *int }`) for which it returns false.

`var Isptr [NTYPE]bool` is used extensively in the frontend. It is set to true for only TPTR32 and TPTR64.

This doesn't matter directly to my type encapsulation efforts, but it seems confusing/dangerous. Here's a proposal. I'd like feedback before I implement it, because the CL will be large, albeit mostly automated:

* Rename the `IsPtr` method to `IsPtrShaped` and adjust ssa.Type appropriately. Use docs to explain the caveat noted above.
* Eliminate the `Isptr` var in favor of an `IsPtr` method on Type.
* Add an `IsUnsafePtr` method on Type to highlight that `IsPtr` does not include TUNSAFEPTR.
* Bonus: Add checks to `IsPtr` to ensure that the right pointer width is in use everywhere.

@randall77 @mdempsky @bradfitz

**Comment by griesemer** [comment]
Seems like a good idea to me, regarding the front-end. I let @randall77 comment on the SSA change.

Sometimes IsPtr may need to include IsUnsafePtr, and sometimes not. Depending on how many use cases of each kind you may want to make IsPtr include unsafe.Pointer, or not. It'll be obvious enough once the rewrite is done.

**Comment by mdempsky** [comment]
FYI: https://go-review.googlesource.com/#/c/21232/

**Comment by mdempsky** [comment]
Aside: I'm wondering if IsPtrShaped should include the extra checks for single-element structs and arrays that isdirectiface has. It's not obvious to me that there are use cases for wanting to identify channel, map, and func types because they fit into a single pointer value, but not single element struct/arrays that do too.  I haven't looked much into that yet though.

**Comment by josharian** [comment]
> FYI: https://go-review.googlesource.com/#/c/21232/

I guess I'm in good company. :) The methods could use some docs, a la the discussion above. Are you also planning to send a CL switching the front-end to use IsPtr?

> Aside: I'm wondering if IsPtrShaped should include the extra checks for single-element structs and arrays that isdirectiface has.

It's complicated. See the comment at `case OEFACE` in ssa.go's expr method, around line 1994 right now.

**Comment by mdempsky** [comment]
> Are you also planning to send a CL switching the front-end to use IsPtr?

Yeah.  I was going to try to get rid of all the Isslice, Isfixedarray, Isptr stuff in favor of the Type methods that were added for SSA.

**Comment by josharian** [comment]
Fabulous. We are in danger of stepping on each others' toes with large scale automated rewrites, but I think/hope that mine should be done pretty soon.

Type is actually getting closer to being extractable into its own package. Hard to believe.

**Comment by josharian** [comment]
I think the only todo item from this issue is "Bonus: Add checks to IsPtr to ensure that the right pointer width is in use everywhere." and that's really a part of #15032, so closing. @mdempsky et al feel free to 
re-open if I missed something.
