### ISSUE TITLE
net/http: add customization of proxy CONNECT requests

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#15027]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   darwin amd64 [os x]
3. What did you do?
   I tried to use Proxy with a `Bearer` authentication method.
4. What did you expect to see?
   Allow other authentication method than Basic HTTP
5. What did you see instead?
   Proxy authentication is limited to Basic-HTTP-Authentication only, with user & password:
   https://github.com/golang/go/blob/master/src/net/http/transport.go#L493
6. Suggestion
   - `url.URL` should allow custom authentication such as `bearer`
   - `url.URL` should provide a method that returns the "authentication header value", and do the base64 etc.

**Comment by bradfitz** [comment]
This proposal is a little confused. It's proposing modifications to `url.URL`, but talking about `net/http` stuff. I think you're probably looking for https://godoc.org/golang.org/x/oauth2 and friends. In general, I think everything you need is already on godoc.org somewhere.

Let's discuss your actual needs on the mailing list before jumping to proposals. See https://golang.org/wiki/Questions.

**Comment by mattn** [comment]
Well, I don't make sure but this seems not change of net/url. And maybe simply implementation of Transport.Proxy.
```go
package main

import (
	"net/http"
	"net/url"
)

func main() {
	token := "blur"
	http.DefaultClient.Transport.(*http.Transport).Proxy = func(r *http.Request) (*url.URL, error) {
		r.Header.Add("Authorization", "Bearer " + token)
		return r.URL, nil
	}
}
```

**Comment by AlmogBaku** [comment]
@mattn As I mentioned on the mailing-list, the problem is that when you do https, the CONNECT request wraps the original request, and there is no way to attach headers to the CONNECT req

**Comment by AlmogBaku** [comment]
@mattn see https://github.com/golang/go/blob/master/src/net/http/transport.go#L1031

**Comment by bradfitz** [comment]
This was added to Go 1.8. See https://beta.golang.org/pkg/net/http/#Transport.ProxyConnectHeader

Dup of #13290
