### ISSUE TITLE
bytes, string: add Reset method to bytes.Reader and strings.Reader

### ISSUE THREAD

**Issue by dsnet** [golang/go#15033]
Using `go1.6`

Currently, there is no easy allocation-free way to turn a `[]byte` or `string` into an `io.Reader`. Adding a Reset method would allow this to easily done. It would also be consistent with the fact that many io.Readers in the standard library already have a Reset method of some sort: `bytes.Buffer`, `bufio.Reader`, `gzip.Reader`, `flate.Reader`, etc.

**Comment by bradfitz** [comment]
A Reset on bytes.Reader and strings.Reader seems fine, and it would reduce allocations if you're repeatedly needing the Reader, but when does that occur? You'd still need to allocate the strings.Reader in the first place (40 bytes). Coincidentally, creating an `io.SectionReader` to get a Reader out of the strings.Reader (which is an io.ReaderAt) is also 40 bytes.

Anyway, seems fine, but I'm curious about your needs more.

**Comment by dsnet** [comment]
I had two in mind, but I'm sure there are more.

1) Embed it in a struct and Reset it as needed:
```go
type OtherReader struct {
    // Other fields.    

    strRd strings.Reader
}

func (or *OtherReader) someFunc() {
    or.strRd.Reset(buf)
    // Do stuff with or.stdRd
}
```

2) Use it in benchmarks to avoid allocation (that way any allocations seen occur because of the object we are actually benchmarking):
```go
var byteRd bytes.Reader
for i := 0; i < b.N; i++ {
    byteRd.Reset(testBuf)
    or.Reset(&byteRd)
    io.Copy(ioutil.Discard, or)
}
```

**Comment by bradfitz** [comment]
Oh, I thought you just wanted to seek back to the beginning:

```go
func (r *Reader) Reset() {
    r.i = 0
    r.prevRune = -1

```

But in retrospect, we already have `Seek` for that.

Changing the source of the Reader is a bit more of a chance, but it's true that it's already consistent with...

```
go1.1.txt:pkg time, method (*Timer) Reset(Duration) bool
go1.2.txt:pkg bufio, method (*Reader) Reset(io.Reader)
go1.2.txt:pkg bufio, method (*Writer) Reset(io.Writer)
go1.2.txt:pkg compress/flate, method (*Writer) Reset(io.Writer)
go1.2.txt:pkg compress/gzip, method (*Writer) Reset(io.Writer)
go1.2.txt:pkg compress/zlib, method (*Writer) Reset(io.Writer)
go1.3.txt:pkg compress/gzip, method (*Reader) Reset(io.Reader) error
go1.4.txt:# CL 97140043 compress/flate: add Reset() to allow reusing large buffers to compress multiple buffers, James Robinson <jamesr@google.com>
go1.4.txt:pkg compress/flate, type Resetter interface { Reset }
go1.4.txt:pkg compress/flate, type Resetter interface, Reset(io.Reader, []uint8) error
go1.4.txt:pkg compress/zlib, type Resetter interface { Reset }
go1.4.txt:pkg compress/zlib, type Resetter interface, Reset(io.Reader, []uint8) error
go1.5.txt:pkg debug/dwarf, method (*LineReader) Reset()
go1.5.txt:pkg os/signal, func Reset(...os.Signal)
go1.txt:pkg bytes, method (*Buffer) Reset()
go1.txt:pkg crypto/rc4, method (*Cipher) Reset()
go1.txt:pkg go/scanner, method (*ErrorList) Reset()
```

So, sure. Send a change?

**Comment by bradfitz** [comment]
This wasn't auto-closed for some reason.

**Comment by dsnet** [comment]
I think it's because the CL wasn't submitted?

**Comment by bradfitz** [comment]
Whoops. Not sure what I was reading.
