### ISSUE TITLE
review: git change doesn't work on windows cmd.exe

### ISSUE THREAD

**Issue by mattn** [golang/go#15036]
using git bundled on msys2 on windows10 64bit.

`git change` failed because the `git rev-parse` doesn't work correctly on cmd.exe.

## how to reproduce

1. install git bundled on msys2
2. goto some repository that already registered aliases to `git change` or others.
3. make new branch and modify some codes
4. `git add` and `git change`

This problem can be reproduced on cmd.exe. On msys2 shell, it doesn't. `git change` run `git rev-parse --abbrev xxx@{u}`. But this `xxx@{u}` is not passed into git command correctly.

![](https://embed.gyazo.com/f677acd43aad33acadbc7389a81892fd.png)

This is cased of different behavior of parsing command-line arguments. As you know, on windows, the arguments are parsed from one-line string by the process it-self. So there are few implementations and behaviors.

**args.c**
```
#include <stdio.h>
int main(int argc, char *argv[]) {
  puts(argv[1]);
}
```
For example, if compiling code above with mingw native compiler, it works expectedly.

```
C:\>args @{u}
@{u}
```

And this works well on msys2 shell too. But if compiling this code with msys2 or cygwin compiler, it doesn't work correctly.

```
C:\>args @{u}
@u
```

![](https://embed.gyazo.com/e25ec3121b8160f12c6207e4fcca9b13.png)

![](https://embed.gyazo.com/dac68247b13c7fa2139fef43b5dacedb.png)

I alredy confirmed this issue will be fixed with following patch.

https://go-review.googlesource.com/#/c/21018/2

BTW, please don't answer `Use "bash on windows"`.

**Comment by alexbrainman** [comment]
> install git bundled on msys2
> ...
> This problem can be reproduced on cmd.exe.

I would say, don't do it. You are looking for trouble. cmd.exe and bash are very different - it is difficult to please both at the same time.

Use standard git version that everyone else is using. If you want to use msys2, then stay inside msys2.

Alex
