### ISSUE TITLE
gccgo: running gcc failed: Can't build

### ISSUE THREAD

**Issue by tsirolnik** [golang/go#15038]
1. What version of Go are you using (`go version`)?
**go version1.5.1 linux/amd64**

2. What operating system and processor architecture are you using (`go env`)?
**amd64 linux (debian stretch) running on vmware**

3. What did you do?
**I've just tried to build my app using _go build ._**

4. What did you expect to see?
**Compiled program**

5. What did you see instead?

```
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section '.init'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

```

I've tried rebooting, upgrading and etc but nothing works

**Comment by ianlancetaylor** [comment]
This is not a gccgo problem.  This is a variant of #13114 .  Your system linker (/usr/bin/ld) is not up to date with your compiler/assembler.  It's not a Go problem at all.

**Comment by sjackman** [comment]
Upgrading `binutils` (for `/usr/bin/ld`) did not help. Setting `CGO_ENABLED=0` did help. See https://github.com/Linuxbrew/linuxbrew/issues/1057
