### ISSUE TITLE
The argument `...` cannot use arr (type []string) as type []interface {}

### ISSUE THREAD

**Issue by huayi** [golang/go#15037]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6 windows/amd64`

2. What operating system and processor architecture are you using (`go env`)?
  ```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Aworkspace\go
set GORACE=
set GOROOT=D:\Develop\go
set GOTOOLDIR=D:\Develop\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
  ```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
  ```go
  func print(a ...interface{}){
      fmt.Println(a...)
  }

  func main() {
      var sl []string
      sl = append(sl, "a","b")
      print(sl...)  //cannot use sl (type []string) as type []interface {} in argument to print
      //print("a","b")   //this line can be output: "a" "b"
      fmt.Println(sl...) //cannot use sl (type []string) as type []interface {} in argument to fmt.Println
  }
  ```
4. What did you expect to see?
`Print(sl...)` and ` fmt.Println(sl...) ` 
Should be normal output

5. What did you see instead?
`cannot use sl (type []string) as type []interface {} in argument to print`
`cannot use sl (type []string) as type []interface {} in argument to fmt.Println`

I know that `[]string` and `[]interface{}` are not the same type.
But I use `...`, It should be compared to `string` and `interface{}` instead of `[]string` and `interface{}`
I think `sl...` should be equal to `"a","b"`

Thanks!

**Comment by bradfitz** [comment]
https://golang.org/doc/faq#convert_slice_of_interface

**Comment by huayi** [comment]
I know how to convert `[]T` to `[]interface`
But I don't want to do this every time when I call the function.
I mean `sl...` should be equal to `"a","b"` instead of `[]string`

**Comment by bradfitz** [comment]
I understand what you want, but the language doesn't work that way. A better place for this discussion might be the golang-nuts mailing list. See https://golang.org/wiki/Questions
