### ISSUE TITLE
expvar: export http.Handler

### ISSUE THREAD

**Issue by captncraig** [golang/go#15030]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
darwin amd64

3. 
If not using http's default serveMux, `import _ "expvar"` cannot add the appropriate handler for me. The handler added by the [init function](https://golang.org/src/expvar/expvar.go#L305) adds an http handler that does a bit of logic I would like to have. I can make it work a couple of different ways:

- Copy expvarHandler into my application and attach it to my mux.
- `myMux.Handle("/debug/vars", http.DefaultServeMux)`, which sort of works, but doesn't help me if I want it at another path or anything like this. 

Simply exporting `expvarHandler` would allow me to do `myMux.HandleFunc("/whatever/route/I/want", expvar.Handler)`.

Would the go team consider a change to that effect?

**Comment by bradfitz** [comment]
Sure, feel free to send a change adding:

```go
// Handler returns the expvar HTTP Handler.
//
// This is only needed to install the handler in a non-standard location. 
func Handler() http.Handler {
   return http.HandlerFunc(expvarHandler)
}
```

**Comment by palaiyacw** [comment]
Any updates on the issue?

**Comment by bradfitz** [comment]
We're in a freeze for Go 1.7. The CL above was tagged as R=go1.8 for review during the Go 1.8 dev cycle, opening soon.
