### ISSUE TITLE
runtime: go gets stuck when running in a FreeBSD jail

### ISSUE THREAD

**Issue by galdor** [golang/go#15044]
## Go version
1.6 (official freebsd pkg 1.6,1)

## System
FreeBSD 10.2 (10.2-RELEASE-p13).
Commands executed in a jail.

## Problem
Running any kind of go command (even something as simple as `go --help`) in a jail gets stuck and has to be killed with SIGKILL. There is no such problem when running `go` outside of a jail.

## Trace

Running `ktrace go --help`:

```
 72810 go       CALL  sigaction(SIG 32,0x7fffffffea18,0)
 72810 go       RET   sigaction 0
 72810 go       CALL  clock_gettime(0x4,0xc820020750)
 72810 go       RET   clock_gettime 0
 72810 go       CALL  sigprocmask(SIG_SETMASK,0x7fffffffe970,0x7fffffffe9a0)
 72810 go       RET   sigprocmask 0
 72810 go       CALL  _umtx_op(0x8010ad330,0x11,0,0,0)
```

Full trace: [go-help-ktrace.txt](https://github.com/golang/go/files/197693/go-help-ktrace.txt)

I have the exact same problem when executing in a jail a binary built with `go build` outside a jail.

This is the first time we are trying to run our Go software on FreeBSD, so I have no idea whether it is a FreeBSD problem or a Go problem. We did not have any problem when our software was in C, and have been using FreeBSD jails for some time now.

**Comment by ianlancetaylor** [comment]
Does every Go program fail in this was, or just the go tool itself?  For example, you should be able to use the go tool outside of a jail to build a simple hello, world program.  Does that program fail when run in a jail?

What kind of processor are you running on?

I actually don't see how that ktrace output is possible.  The Go runtime only ever passes `0xf` and `0x10` to `_umtx_op`.  I don't know where the `0x11` is coming from.

**Comment by vgalu** [comment]
Is the userland in your jail in sync with your kernel?

**Comment by galdor** [comment]
The architecture is amd64; the CPU is an Intel Core i5 750.
Both the userland and the base system and the jail are `10.2-RELEASE-p13`.

I tried with a simple hello world program.

- Building it out of the jail works. Running the generated executable in the jail works.
- Building it in the jail results in the go runtime getting stuck the same way.

Finally I tried a hello world program using the `C` package:

```go

package main

// #include <stdio.h>
//
// static void helloWorld() {
//     printf("hello world\n");
// }
import "C"

func main() {
        C.helloWorld()
}
```

Building it out of the jail, then running it in the jail results in it getting stuck.
Our software also uses `C`, and also gets stuck in the same situation.
Does the go runtime use `C` ? If yes, there could be something wrong with `C` when running in a jail.

**Comment by ianlancetaylor** [comment]
The Go runtime itself does not use C.  However, many Go programs do use C.  Go makes system calls directly, including to `_umtx_op`.  `_umtx_op` is related to threads.  If the jail does not support threads, then no substantial Go program is going to work inside it.

**Comment by galdor** [comment]
There is afaik nothing in jails that prevent using threads in any way. I already ran multithreaded applications in jails without any problem.

**Comment by ianlancetaylor** [comment]
Thanks.  I'm going to close this issue because I don't think there is anything we can do on the Go side to fix it.  Please reopen if there is something we can change in Go to make it work.
