### ISSUE TITLE
reflect: Type.Field does not panic when out of range

### ISSUE THREAD

**Issue by crawshaw** [golang/go#15046]
In both Go 1.6 and at tip, reflect.Type.Field is documented to panic when out of range:

```
// Field returns a struct type's i'th field.
// It panics if the type's Kind is not Struct.
// It panics if i is not in the range [0, NumField()).
```

It doesn't. The program

```
package main

import (
	"fmt"
	"reflect"
)

func main() {
	t := reflect.TypeOf(struct{ X int }{})
	fmt.Println(t.NumField())
	fmt.Println(t.Field(0))
	fmt.Println(t.Field(1))
}
```

prints

```
1
{X  int  0 [0] false}
{  <nil>  0 [] false}
```

http://play.golang.org/p/G-NOR9EMrB

**Comment by ianlancetaylor** [comment]
Unfortunately this has been true at least since Go 1.  I suppose we should probably fix it, but it will likely break some currently working programs.
