### ISSUE TITLE
cmd/compile: constants of same underlying type are not merged

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#15043]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +d8f1f8d Wed Mar 30 22:27:13 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?

Compiled the following program

```
package main

type foo int
type bar int
type spam int
type eggs int

func f(a []int) {
        _ = a[foo(3)]
        _ = a[bar(3)]
        _ = a[spam(3)]
        _ = a[eggs(3)]
}

func main() {
}
```

4. What did you expect to see?
One bounds check.

5. What did you see instead?
4 bounds checks. The constants foo(3), bar(3), spam(3), eggs(3) are not merged by the zcse pass nor by the constants cache. However, most rewrite rules ignore the type and only use op.

@josharian @tzneal

**Comment by josharian** [comment]
Yep. We use the frontend's notion of the equality, which takes into account named types, etc. I think there's an item in the ssa todo file to use a looser notion of equality; good to have it as an issue too.

cc @mdempsky

**Comment by randall77** [comment]
The particular example in this bug will be fixed by https://go-review.googlesource.com/c/21008
The more general problem of using fuzzy type equality still stands, however.

**Comment by tzneal** [comment]
I might be mis-remembering, but I thought that @dr2chase had implemented a structural type equality, but didn't commit it.  I think it would be fairly easy and safe to modify zcse to handle cases like this without much effort.

**Comment by randall77** [comment]
This looks fixed now.
