### ISSUE TITLE
tour: Math.PI is no longer an export of the Math package

### ISSUE THREAD

**Issue by sgraessle** [golang/go#15047]
Context: http://127.0.0.1:3999/basics/3

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by 0xmohit** [comment]
Appears that you didn't read the accompanying text that says:

`To fix the error, rename math.pi to math.Pi and try it again. `

**Comment by sgraessle** [comment]
The text says "Pi is an exported name, as is PI." That latter phrase seems to be incorrect.

**Comment by bradfitz** [comment]
At http://tour.golang.org/basics/3

> `Pi` is an exported name, as is `PI`. The name `pi` is not exported.

On that line, it's not talking about about the math package at all. Only the names themselves. Maybe it should say "as is `Pizza`" to make it obvious there is no `math.Pizza`.

**Comment by ALTree** [comment]
Note that this was changed to address #13045. See https://go-review.googlesource.com/#/c/18987/

**Comment by bradfitz** [comment]
@ALTree, hah. @kytrinyx, maybe we should use a mix of `Pi` and `Foo` variants?

**Comment by broady** [comment]
Here's my idea:
https://go-review.googlesource.com/#/c/21387/

I moved the examples of names next to the sentence that introduces them, to separate it from the thing about `math`.

Also, I don't think we should use all-caps names as examples.

**Comment by kytrinyx** [comment]
> Also, I don't think we should use all-caps names as examples.

I agree. All caps is used for acronyms, but not names as such.

It's a shame golint can't know programmatically what is an acronym or not; I've seen a fair number of all caps names that don't get flagged. https://github.com/golang/lint/blob/9bad2ac064ef73cba57dec90e67d45fec2ab67bc/lint.go#L539

**Comment by adg** [comment]
On the CL I suggested that @cbro change `Pizza` to `Phi`. The latter does exist in the `math` package.

@kytrinyx lint [does know about initialisms](https://github.com/golang/lint/blob/9bad2ac064ef73cba57dec90e67d45fec2ab67bc/lint.go#L719) but I don't think it approves of names that are _only_ an initialism. Maybe this should change. (@dsymonds?)

**Comment by dsymonds** [comment]
golint is heuristic based, and isn't going to get every instance right. It flags ALL_CAPS names that are caps with underscores (and at least 5 chars), but it's not going to distinguish URL from POO without a big English database.

**Comment by kytrinyx** [comment]
> golint is heuristic based, and isn't going to get every instance right.

Yeah, it can't possibly get it. The English language is just too fuzzy. I'd be pretty annoyed if I had an initialism that got flagged because it wasn't part of the official list in golint.
