### ISSUE TITLE
cmd/compile: a9407b breaks address offset calculation

### ISSUE THREAD

**Issue by kortschak** [golang/go#15042]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +93098de

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
go get -u github.com/gonum/matrix/mat64
go test -a -run DenseOverlaps github.com/gonum/matrix/mat64 # unsafe dependency
go test -a -tags appengine -run DenseOverlaps github.com/gonum/matrix/mat64 # no unsafe dependency
```

4. What did you expect to see?

Both test invocations pass. This is the behaviour with go1.6

5. What did you see instead?

Both invocations fail.

The change in behaviour was bisected to a9407b5797c0d4dcbed965462204cdc4e38bb621.

The now failing code calculates relative address offsets between two []float64 elements (either with [unsafe](https://github.com/gonum/matrix/blob/master/mat64/offset.go) or [reflect](https://github.com/gonum/matrix/blob/master/mat64/offset_appengine.go)) to [identify matrix overlaps](https://github.com/gonum/matrix/blob/master/mat64/shadow.go).

**Comment by josharian** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
Simple test case.  This program does not panic with Go 1.5 or Go 1.6, does panic with tip.

    package main

    type S struct {
	    i int
    }

    func F(c bool, s1, s2 S) (int, int) {
	    if c {
		    s1.i, s2.i = s2.i, s1.i
	    }
	    return s1.i, s2.i
    }

    func main() {
	    i, j := F(true, S{1}, S{20})
	    if i != 20 || j != 1 {
		    panic(i+j)
	    }
    }
