### ISSUE TITLE
cmd/compile: not compiled

### ISSUE THREAD

**Issue by indariums** [golang/go#15058]
Processor architecture arm5, OS Synelogy+ipkg(optware may be)
Install from gvm.
Log errors:

> Building C bootstrap tool.
> cmd/dist

> Building compilers and Go bootstrap tool for host, linux/arm.
> lib9
> libbio
> liblink
> cmd/cc
> cmd/gc
> cmd/5l
> cmd/5a
> cmd/5c
> cmd/5g
> runtime
> go tool dist: FAILED: /root/.gvm/gos/go1.4/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main -+ /root/.gvm/gos/go1.4/src/runtime/alg.go /root/.gvm/gos/go1.4/src/runtime/arch_arm.go /root/.gvm/gos/go1.4/src/runtime/atomic_arm.go /root/.gvm/gos/go1.4/src/runtime/cgocall.go /root/.gvm/gos/go1.4/src/runtime/cgocallback.go /root/.gvm/gos/go1.4/src/runtime/chan.go /root/.gvm/gos/go1.4/src/runtime/compiler.go /root/.gvm/gos/go1.4/src/runtime/complex.go /root/.gvm/gos/go1.4/src/runtime/cpuprof.go /root/.gvm/gos/go1.4/src/runtime/debug.go /root/.gvm/gos/go1.4/src/runtime/env_posix.go /root/.gvm/gos/go1.4/src/runtime/error.go /root/.gvm/gos/go1.4/src/runtime/extern.go /root/.gvm/gos/go1.4/src/runtime/hashmap.go /root/.gvm/gos/go1.4/src/runtime/hashmap_fast.go /root/.gvm/gos/go1.4/src/runtime/iface.go /root/.gvm/gos/go1.4/src/runtime/lock_futex.go /root/.gvm/gos/go1.4/src/runtime/malloc.go /root/.gvm/gos/go1.4/src/runtime/mem.go /root/.gvm/gos/go1.4/src/runtime/mgc0.go /root/.gvm/gos/go1.4/src/runtime/mprof.go /root/.gvm/gos/go1.4/src/runtime/netpoll.go /root/.gvm/gos/go1.4/src/runtime/netpoll_epoll.go /root/.gvm/gos/go1.4/src/runtime/noasm_arm.go /root/.gvm/gos/go1.4/src/runtime/os_linux.go /root/.gvm/gos/go1.4/src/runtime/panic.go /root/.gvm/gos/go1.4/src/runtime/print1.go /root/.gvm/gos/go1.4/src/runtime/proc.go /root/.gvm/gos/go1.4/src/runtime/race0.go /root/.gvm/gos/go1.4/src/runtime/rdebug.go /root/.gvm/gos/go1.4/src/runtime/rune.go /root/.gvm/gos/go1.4/src/runtime/runtime.go /root/.gvm/gos/go1.4/src/runtime/select.go /root/.gvm/gos/go1.4/src/runtime/sema.go /root/.gvm/gos/go1.4/src/runtime/signal_unix.go /root/.gvm/gos/go1.4/src/runtime/sigpanic_unix.go /root/.gvm/gos/go1.4/src/runtime/sigqueue.go /root/.gvm/gos/go1.4/src/runtime/slice.go /root/.gvm/gos/go1.4/src/runtime/softfloat64.go /root/.gvm/gos/go1.4/src/runtime/sqrt.go /root/.gvm/gos/go1.4/src/runtime/stack.go /root/.gvm/gos/go1.4/src/runtime/string.go /root/.gvm/gos/go1.4/src/runtime/stubs.go /root/.gvm/gos/go1.4/src/runtime/symtab.go /root/.gvm/gos/go1.4/src/runtime/time.go /root/.gvm/gos/go1.4/src/runtime/traceback.go /root/.gvm/gos/go1.4/src/runtime/typekind.go /root/.gvm/gos/go1.4/src/runtime/vlrt.go /root/.gvm/gos/go1.4/src/runtime/zgoarch_arm.go /root/.gvm/gos/go1.4/src/runtime/zgoos_linux.go /root/.gvm/gos/go1.4/src/runtime/zruntime_defs_linux_arm.go /root/.gvm/gos/go1.4/src/runtime/zversion.go

**Comment by davecheney** [comment]
This output looks truncated, can you please include the full output if possible.

**Comment by davecheney** [comment]
Also, have you tried building without gvm?

**Comment by indariums** [comment]
> Also, have you tried building without gvm?

Yes.Same.

> This output looks truncated, can you please include the full output if possible.

Tell me how to do it?

**Comment by davecheney** [comment]
Download the go 1.4 sources. cd go/src ./make.bash

**Comment by indariums** [comment]
If I downloaded from the desired site (https://go.googlesource.com/go/+/go1.4), the output is almost the same.

> Building C bootstrap tool.
cmd/dist

> Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
cmd/5a
cmd/5c
cmd/5g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
go tool dist: FAILED: /go14/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main /go14/src/cmd/go/bootstrap.go /go14/src/cmd/go/build.go /go14/src/cmd/go/clean.go /go14/src/cmd/go/context.go /go14/src/cmd/go/env.go /go14/src/cmd/go/fix.go /go14/src/cmd/go/fmt.go /go14/src/cmd/go/generate.go /go14/src/cmd/go/get.go /go14/src/cmd/go/go11.go /go14/src/cmd/go/help.go /go14/src/cmd/go/list.go /go14/src/cmd/go/main.go /go14/src/cmd/go/pkg.go /go14/src/cmd/go/run.go /go14/src/cmd/go/signal.go /go14/src/cmd/go/signal_unix.go /go14/src/cmd/go/test.go /go14/src/cmd/go/testflag.go /go14/src/cmd/go/tool.go /go14/src/cmd/go/vcs.go /go14/src/cmd/go/version.go /go14/src/cmd/go/vet.go /go14/src/cmd/go/zdefaultcc.go

**Comment by davecheney** [comment]
Thank you.

I think it's time to go back to basics.

What is the platform you are using? How much memory does it have, does it have any swap? You will need more than 256mb of ram to run ./make.bash. Don't bother running all.bash, it won't pass without extra twiddling for you.

Have you checked dmesg, is the Oom killer stomping on your process?

**Comment by indariums** [comment]
Platform -  Synology USB Station 2. Memory 128mb. Then the matter is the lack of memory.
Thank you.

**Comment by davecheney** [comment]
The first Go asm builder was a similar platform. Sadly it was outgrown by
Go 1.0. You won't be able to compile locally on that system. However you
can cross compile from another platform with one command

http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

I recommend that.

**Comment by bradfitz** [comment]
Closing, since there isn't anything actionable here for us to do.
