### ISSUE TITLE
gccgo: runtime: runtime_stoptheworld deadlock on ppc64le

### ISSUE THREAD

**Issue by hanumantmk** [golang/go#15051]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

  go version go1.4.2 gccgo (GCC) 5.3.0 linux/ppc64le

2. What operating system and processor architecture are you using (`go env`)?

  ppc64le
  linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

  Unfortunately haven't been able to come up with a simple repro, but core dump and binary are provided (all of the interesting source information is within gccgo's libgo c implementation).

4. What did you expect to see?

  Something other than a hard deadlock across all threads.  If this is an application derived deadlock, perhaps deadlock detection triggering.

5. What did you see instead?

  All threads stuck in runtime_futexsleep without a timeout.

  One thread is in runtime_stoptheworld, all other threads are blocked.  On inspection, the stoptheworld thread is waiting because one of the outstanding P's is still in Psyscall (runtime_sched.stop_wait == 1).  Values for that P:

  ```
  (gdb) p runtime_allp[1][0]
  $1 = {{key = 0}, id = 1, status = 2, link = 0x0, schedtick = 88, syscalltick = 10, m = 0x0, mcache = 0x3fff90df0898,
    deferpool = 0x0, goidcache = 37, goidcacheend = 49, runqhead = 21, runqtail = 21, runq = {0xc2094b0000, 0xc2094b0000,
      0xc20a10ba00, 0xc20a10c700, 0xc20a10d400, 0xc2094b0000, 0xc20a10e100, 0xc20a10e100, 0xc20a10e100, 0xc20bd8a000,
      0xc20bd8ad00, 0xc20bd8ba00, 0xc2094b0000, 0xc20d592700, 0xc2094b0000, 0xc2094b0000, 0xc2094b0000, 0xc20d590000,
      0xc20bd82d00, 0xc20d594e00, 0xc20b526100, 0x0 <repeats 235 times>}, gfree = 0x0, gfreecnt = 0,
    pad = '\000' <repeats 63 times>}
  ```

  All of the other P's are in status 3, I.e. Pgcstop

  I'm partly suspicious of the doentersyscall() edge, which seems to do a non-atomic load of runtime_sched.gcwaiting, which feels like it could race with the gc'ing thread:

  ```
  // doentersyscall()
  ...
        runtime_atomicstore(&m->p->status, Psyscall);
        if(runtime_sched.gcwaiting) {
                runtime_lock(&runtime_sched);
                if (runtime_sched.stopwait > 0 && runtime_cas(&m->p->status, Psyscall, Pgcstop)) {
                        if(--runtime_sched.stopwait == 0)
                                runtime_notewakeup(&runtime_sched.stopnote);
                }
                runtime_unlock(&runtime_sched);
        }
  ...
```

Coredump with binary and goroutine stack output:
https://www.dropbox.com/s/3lht3xs4fgi7fub/hang_info.tgz?dl=0

**Comment by gabrielrussell** [comment]
I've written a smaller piece of code that seems to exhibit the same behavior. Running this with a higher GOMAXPROCS seems to make it more likely to deadlock. On the 80 core machine I'm running this on I run it with GOMAXPROCS=200. For me, it hangs somewhere between 15 and 60 seconds.

```
package main

import (
        "syscall"
        "fmt"
)

func main() {
        n := 200
        count := make([]int,n)
        for i:=0;i<n;i++ {
                go func(x int) {
                        for {
                                syscall.Nanosleep(&syscall.Timespec{ 0, 100} ,&syscall.Timespec{})
                                count[x]++
                                _ = make([]byte,1024)
                        }
                }(i)
        }
        for i := 0;;i++ {
                syscall.Nanosleep(&syscall.Timespec{ 1, 0} ,&syscall.Timespec{})
                fmt.Printf("%v %#v\n",i, count)
        }
}
```

**Comment by gabrielrussell** [comment]
With this patch, my reproo program no longer deadlocks.

```
[ec2-user@ubuntu1404-ppc-2 gabriel]$ diff  -u -r gcc-5.3.0 gcc-5.3.0-fix                                                                                                                                                                                                                    diff -u -r gcc-5.3.0/libgo/runtime/proc.c gcc-5.3.0-fix/libgo/runtime/proc.c
--- gcc-5.3.0/libgo/runtime/proc.c      2015-04-29 21:32:07.000000000 +0000
+++ gcc-5.3.0-fix/libgo/runtime/proc.c  2016-04-01 16:04:01.471160881 +0000
@@ -2042,7 +2042,7 @@
        m->mcache = nil;
        m->p->m = nil;
        runtime_atomicstore(&m->p->status, Psyscall);
-       if(runtime_sched.gcwaiting) {
+       if(runtime_atomicload(&runtime_sched.gcwaiting)) {
                runtime_lock(&runtime_sched);
                if (runtime_sched.stopwait > 0 && runtime_cas(&m->p->status, Psyscall, Pgcstop)) {
                        if(--runtime_sched.stopwait == 0)
```

**Comment by ianlancetaylor** [comment]
Thanks for tracking this down.
