### ISSUE TITLE
net: bad shadowing in ipsock_posix.go; unhelpful ip.String result

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#15052]
On tip, the file net/ipsock_posix.go has these lines

    		if ip = ip.To4(); ip == nil {
    			return nil, &AddrError{Err: "non-IPv4 address", Addr: ip.String()}
    		}

It's pretty clear here that the `ip.String` stored in `AddrError` is using the wrong `ip`.  This code will always set the `Addr` field to `"<nil>"`.

The same error occurs a few lines down using `To16`.

I would send in the obvious fix, but the effect would be to change the `Addr` field from `"<nil>"` to `"?"`, which is only barely an improvement.  We probably need to fix these cases in ipsock_posix.go and also fix `IP.String` to produce more useful output for an unrecognized length.

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by hbhasker** [comment]
Would it make sense to change the name and replace it with something like

Addr: fmt.Sprintf("%v", origIP)

That will print the IP as a byte array, which is probably the right thing to do rather than have ip.String() return an invalid ip representation?
