### ISSUE TITLE
cmd/compile: adding a constant to a memory location needs 3 instructions

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#15054]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version devel +e775b8d Thu Mar 31 18:41:30 2016 +0000 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   linux amd64
3. What did you do?
   Compiled the following function

```
func g(a *int) {
        *a += 3
}
```
1. What did you expect to see?
   One single instruction

```
ADDQ (CX), $3
```
1. What did you see instead?
   Three instructions

```
MOVQ (CX), AX
ADDQ $3, AX
MOVQ AX, (CX)
```

**Comment by brtzsnr** [comment]
@randall77  I don't know if it's easy or not to handle this.

**Comment by minux** [comment]
Utilizing memory-memory x86 instructions is also a topic of #14587,
although that one is for a simpler cade. However, I think the solution
should be the same.

**Comment by randall77** [comment]
This should be easier than #14587, as we don't have to deal with flags.  You'd just need to make sure there are no other uses of the load.  Then it would just be a simple rewrite.
The challenge is just the bulk of it.  You'd want all the possible addressing modes, plus all the ops (ADD, SUB, AND...).  In addition, this is something that only x86 can do, all the other archs are load-store architectures which can't do this.
I'm leaning toward punting on this for now.  When the SSA backend gets more mature we can revisit.

**Comment by rasky** [comment]
We could... generate the rules :)

**Comment by randall77** [comment]
This is fixed.
