### ISSUE TITLE
Support emulating arm64 go binaries with qemu

### ISSUE THREAD

**Issue by luxas** [golang/go#15050]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.5.2 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lucas/luxas/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
$ cat > main.go <<EOF
package main

func main(){
	println("hello")
}
EOF
$ GOARCH=arm64 go build main.go
$ contrib/qemu-aarch64-static ./main
```

4. What did you expect to see?
```
hello
```

5. What did you see instead?
```
qemu: unhandled CPU exception 0x10004 - aborting
PC=00000000000636a8  SP=00000040007ffd60
X00=000000000000001e X01=0000000000000004 X02=00000000000d1180 X03=0000000000000000
X04=000001482000d200 X05=0000014820001080 X06=0000000000004000 X07=0000000000002000
X08=0000000000000087 X09=000000000000002c X10=00000000000004d2 X11=0000014820001080
X12=0000000000039ea0 X13=0000000000000000 X14=0000000000000000 X15=0000000000000180
X16=000000000002b150 X17=00000000000a6b88 X18=0000000000000000 X19=0000000000000000
X20=0000000000000000 X21=0000000000000000 X22=0000000000000000 X23=0000000000000000
X24=0000000000000000 X25=0000000000000000 X26=00000000000a6d98 X27=00000000000f256c
X28=00000000000d1280 X29=0000000000000000 X30=000000000001847c 
PSTATE=20000000 --C- EL0t
Aborted (core dumped)
```

I'm not sure if it's a go or qemu issue, but qemu works fine with other binaries.
This works for `arm` and `ppc64le`, but not `arm64`
Thanks!
/cc @rsc (this is Kubernetes related https://github.com/kubernetes/kubernetes/issues/17981)

**Comment by minux** [comment]
Should be a qemu issue as the binary runs fine on real arm64 machines. Note
that we never support running with qemu-user and it's known to have
problems when running multithreaded programs.

**Comment by mwhudson** [comment]
That said, we have made simple changes to Go to work around qemu issues in the past as well. More investigation required, basically.

**Comment by luxas** [comment]
Can you think about an easy way to fix?

**Comment by mwhudson** [comment]
No. I asked a qemu maintainer and they said "I would say there is no immediate prospect of a fix". qemu-user is known to be bad with threads, although it works at least a bit with go binaries from other architectures.

**Comment by luxas** [comment]
@suihkulokki

**Comment by rsc** [comment]
Michael, did you test with qemu/arm64? Does it fix the problem? Thanks.

**Comment by mwhudson** [comment]
No, I haven't tested anything.

**Comment by rsc** [comment]
Did anyone test this? If not, why did it reference this bug? Was it clear
from the qemu crash registers that the problem was the CPU count?

**Comment by mwhudson** [comment]
Oh sorry! Referencing this bug from that CL was simply a mistake (fixed before that CL was submitted).

**Comment by suihkulokki** [comment]
We've just merged major threading and signals rework has been into Qemu HEAD. From a quick check, running at least the @mwhudson hello world example works now.

**Comment by quentinmit** [comment]
Excellent. @luxas Would you be able to check if this works now with Qemu HEAD?

**Comment by quentinmit** [comment]
I'm going to close this bug for now; please comment if there are still problems with Qemu HEAD. Thanks!
