### ISSUE TITLE
doc: update wiki WindowsCrossCompiling

### ISSUE THREAD

**Issue by unapiedra** [golang/go#15056]
The wiki page _WindowsCrossCompiling_ needs to be updated to reflect the current status of cross compiling for Windows. The process has gotten much easier since version 1.5.

Page: 
https://github.com/golang/go/wiki/WindowsCrossCompiling

I've upated the page to refer to both versions. Please let me know here if you are not happy with this change. I would actually suggest deleting the pre1.5 part of the page.

---
1. What version of Go are you using (`go version`)?
   go 1.6 (`go version go1.6 darwin/amd64`)
2. What operating system and processor architecture are you using (`go env`)?
   "A browser"
3. What did you expect to see?
   I think the page could be replaced more or less with a single line of 
   
   GOOS=windows GOARCH=amd64 go build hello.go
4. What did you see instead?
   A long-winded page on building go etc.

**Comment by alexbrainman** [comment]
> I think the page could be replaced more or less with a single line of
> GOOS=windows GOARCH=amd64 go build hello.go

The command above will silently rebuild most of standard library unless you already installed all windows-amd64 standard packages with
```
GOOS=windows GOARCH=amd64 go install
```
first. So `GOOS=windows GOARCH=amd64 go build hello.go` will run much slower than it need be.

Alex

**Comment by ALTree** [comment]
Instructions for `>= go1.5` are on the wiki since Apr 2016: https://github.com/golang/go/wiki/WindowsCrossCompiling.

I added a note about the slow builds and how to avoid them as suggested by Alex, so we can now close this.
