### ISSUE TITLE
testing: FAIL: TestBRun

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#15063]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Tip at 014f3e1 + https://go-review.googlesource.com/#/c/21410/

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
Patch https://go-review.googlesource.com/#/c/21410/

go test testing/...

4. What did you expect to see?
Test passes

5. What did you see instead?
```
--- FAIL: TestBRun (0.00s)
        sub_test.go:392: MemAllocs was 8; want 2
        sub_test.go:395: MemBytes was 4096; want 512
FAIL
```

6. Additional information
First showed up here https://storage.googleapis.com/go-build-log/63567c79/darwin-amd64-10_10_d6336420.log but the with the above patch it can be reproduced on linux amd64, too.

**Comment by bradfitz** [comment]
@mpvl, can you take a look?
