### ISSUE TITLE
"compile: reading input: EOF" errors on windows-amd64 builder

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#15061]
Starting from ea306ae windows-amd64 builder failes with random messages like:
```
# cmd/internal/obj/x86_test
compile: reading input: EOF
ok  	cmd/internal/obj	0.040s
FAIL	cmd/internal/obj/x86 [build failed]
```
http://build.golang.org/log/859abd9846408995635e59a593e1e48ac794bb39
http://build.golang.org/log/024d163ef18c6748b539ef4acc72dee8f53ee6fa
http://build.golang.org/log/21b57103160b11601f7f5131d3a4142198d9d75f

Alex

**Comment by bradfitz** [comment]
I've seen these failures in trybots too.

/cc @ianlancetaylor @randall77 @brtzsnr

**Comment by alexbrainman** [comment]
> I've seen these failures in trybots too.

Do you ever sleep? ;_)

Alex

**Comment by bradfitz** [comment]
More:

Failed on windows-amd64-gce: https://storage.googleapis.com/go-build-log/8778695a/windows-amd64-gce_5eeffde3.log
Failed on windows-386-gce: https://storage.googleapis.com/go-build-log/8778695a/windows-386-gce_c6cbe451.log
Failed on windows-amd64-gce: https://storage.googleapis.com/go-build-log/7a64722f/windows-amd64-gce_d7378bf3.log

**Comment by brtzsnr** [comment]
From http://build.golang.org/ the first failure appeared with https://go-review.googlesource.com/#/c/17761/.

**Comment by bradfitz** [comment]
Paging Mr. @aclements for build failure history analysis.

**Comment by aclements** [comment]
That's Dr. @aclements. :)

`$ greplogs -dashboard -md -l -e 'compile: reading input: EOF'`
[2016-04-01T04:13:44-ea306ae/windows-amd64-gce](https://build.golang.org/log/859abd9846408995635e59a593e1e48ac794bb39)
[2016-04-01T09:37:58-b91cc53/windows-amd64-gce](https://build.golang.org/log/024d163ef18c6748b539ef4acc72dee8f53ee6fa)
[2016-04-01T09:37:58-b91cc53/windows-amd64-race](https://build.golang.org/log/ea1cc74297d2effe27d3ca55ae141e50d1642de9)
[2016-04-01T09:39:50-014f3e1/windows-amd64-gce](https://build.golang.org/log/21b57103160b11601f7f5131d3a4142198d9d75f)
[2016-04-01T09:39:50-014f3e1/windows-amd64-race](https://build.golang.org/log/0459d40ac70e7d7b2533659b6149d16c892514b8)

This is just the most recent three commits on the dashboard, which is perhaps not helpful.

**Comment by bradfitz** [comment]
My current suspicion is this line, 118:

https://go-review.googlesource.com/#/c/17761/13/src/runtime/cgocall.go@118

But I'm not familiar with this code.

**Comment by bradfitz** [comment]
Experimenting in https://go-review.googlesource.com/#/c/21425/

**Comment by aclements** [comment]
We should probably allocate cgoCallers earlier no matter what if iscgo || GOOS == "solaris" || GOOS == "windows".

**Comment by ianlancetaylor** [comment]
I agree with Austin.

I gather the problem is that cgocall is being called from places where we can't call new?
