### ISSUE TITLE
cmd/compile: The bounds check can be removed in u%uint(x) for all x != 0 && x <= len(slice).

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#15079]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
      go version devel +29267c2 2016-04-03 01:50:04 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
http://play.golang.org/p/gWCa1r06CI

4. What did you expect to see?
 `bb` (and maybe `aa`)'s bounds checking removed

5. What did you see instead?
```
        0x0013 00019 (blah.go:21)       MOVQ    $0, "".autotmp_6+6(SP)
        0x001c 00028 (blah.go:21)       MOVQ    $0, "".autotmp_6+8(SP)
        0x0025 00037 (blah.go:22)       MOVQ    $-3689348814741910323, AX
        0x002f 00047 (blah.go:22)       MOVQ    $32768, CX
        0x0036 00054 (blah.go:22)       MULQ    CX
        0x0039 00057 (blah.go:22)       SHRQ    $3, DX
        0x003d 00061 (blah.go:22)       LEAQ    (DX)(DX*4), AX
        0x0041 00065 (blah.go:22)       SHLQ    $1, AX
        0x0044 00068 (blah.go:22)       SUBQ    $32768, AX
        0x004a 00074 (blah.go:22)       NEGQ    AX
        0x004d 00077 (blah.go:22)       CMPQ    AX, $10
        0x0051 00081 (blah.go:22)       JCC     $0, 101
        0x0053 00083 (blah.go:21)       LEAQ    "".autotmp_6+6(SP), CX
        0x0058 00088 (blah.go:22)       MOVBLZX (CX)(AX*1), CX
        0x005c 00092 (blah.go:22)       MOVB    CL, "".~r0+24(FP)
        0x0060 00096 (blah.go:22)       ADDQ    $16, SP
        0x0064 00100 (blah.go:22)       RET
        0x0065 00101 (blah.go:22)       PCDATA  $0, $0
        0x0065 00101 (blah.go:22)       CALL    runtime.panicindex(SB)
```

I could've sworn there was a bug about this, but I can't find it

**Comment by randall77** [comment]
I would assert that this bug is about all this arithmetic not constant-folding away to nothing.

**Comment by cznic** [comment]
Note: Wrt issue title: The bounds check can be removed in u%uint(x) for all x != 0 && x <= len(slice).

**Comment by minux** [comment]
Note that in general, if i is a signed type, slice[i % len(slice)]
still need to do bound check against the i < 0 case because
Go specifies that if i < 0, i % len(slice) < 0.

**Comment by brtzsnr** [comment]
@brtzsnr
