### ISSUE TITLE
x/review/git-codereview: provide a way to configure gerrit URL without codereview.cfg file in the repository

### ISSUE THREAD

**Issue by cmarcelo** [golang/go#15073]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.5.3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cmdeoliv/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Trying to use git-codereview with a Gerrit repository that doesn't have codereview.cfg configuration file. It is not always possible to add the file to upstream repository, but git-codereview features that depend on Gerrit could still be used.

4. What did you expect to see?

git-codereview either provide a way for me to configure the gerrit URL that doesn't depend on the codereview.cfg file being in the repository.

5. What did you see instead?

git-codereview doesn't identify my repository as Gerrit, then disable features that depend on Gerrit.

**Comment by josharian** [comment]
Does CL 24001 help with this?

**Comment by rsc** [comment]
Closing; I think CL 24001 is a good fix.
