### ISSUE TITLE
x/net/http2: client should drop connection specific headers

### ISSUE THREAD

**Issue by jmhodges** [golang/go#15085]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.0

2. What operating system and processor architecture are you using (`go env`)?
OS X and Linux (but it affects any of them)

3. What did you do?

net/http2 errors when adding a connection-specific header to client requests. 

For example, adding a Keep-Alive header to an HTTP request (as the Google [certificate-transparency client does](https://github.com/google/certificate-transparency/blob/39dd3f13a37a935a8a5be5e8a4248422c9facd08/go/client/logclient.go#L127)) and have it go over an HTTP/2 connection.

Per [Section 8.1.2.2 of the HTTP/2 spec](https://http2.github.io/http2-spec/#rfc.section.8.1.2.2), connection-specific headers are to be dropped by HTTP/2 clients.

See this sample code that talks to www.google.com: http://play.golang.org/p/W2C9LfLBlO

4. What did you expect to see?

A working GET request to an HTTP/2 server that returns a 200

5. What did you see instead?

A 400 Bad Request response from the HTTP/2 server.

This was discovered in https://github.com/google/certificate-transparency/issues/1136

**Comment by jmhodges** [comment]
(Original play.golang.org link in the issue went to a sample that hit google.com, instead of www.google.com. That would redirect on success, so I've swapped out the sample for one that went to www.google.com)

**Comment by bradfitz** [comment]
Thanks!
