### ISSUE TITLE
TestBRun flaky

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#15081]
A trybot run of

https://go-review.googlesource.com/#/c/21379

revealed a flaky TestBRun on the darwin/amd64 builder:

https://storage.googleapis.com/go-build-log/63567c79/darwin-amd64-10_10_d6336420.log

--- FAIL: TestBRun (0.01s)
	sub_test.go:388: MemAllocs was 5; want 2
	sub_test.go:391: MemBytes was 2304; want 512
FAIL
FAIL	testing	1.947s

The flakiness is more often apparent on the darwin/arm{,64} builders:

http://build.golang.org/log/f4fa781d0a3fc2bf9e1012a4b9ee703fae819505
http://build.golang.org/log/ced8e366663ebf6f7a950f36ee3417210b8a3ba4
http://build.golang.org/log/8219815499ce481b6e6041b902a1a1a794c95320

etc.

Alexandru isolated the problem to https://go-review.googlesource.com/#/c/21410/, however I've not been able to reproduce the crash on my own linux/amd64 setup.

/cc @mpvl

**Comment by bradfitz** [comment]
Dup of #15063
