### ISSUE TITLE
x/net/http2: client should allow 'trailers' Transfer-Encoding header

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#15089]
1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu 15.10 amd64

3. What did you do?
```
package main

import (
	"log"
	"net/http"
)

func main() {
	// Enables HTTP/2 in the DefaultClient on Go 1.6.0
	if tr, ok := http.DefaultTransport.(*http.Transport); ok {
		tr.ExpectContinueTimeout = 0
	}
	req, err := http.NewRequest("GET", "https://www.google.com", nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Transfer-Encoding", "trailers")
	_, err = http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
}
```

4. What did you expect to see?
No error

5. What did you see instead?
`http2: invalid Transfer-Encoding request header`.

`checkConnHeaders` fails on any `Transfer-Encoding` header values other than `chunked`, but `encodeHeaders` ignores any `Transfer-Encoding` headers anyway. This is contrary to the spec which says

> The only exception to this is the TE header field, which MAY be present in an HTTP/2 request; when it is, it MUST NOT contain any value other than "trailers".

**Comment by bradfitz** [comment]
`TE` and `Transfer-Encoding` are different headers:

http://tools.ietf.org/html/rfc7230#section-4.3 (TE)
http://tools.ietf.org/html/rfc7230#section-3.3.1 (Transfer-Encoding)

**Comment by rolandshoemaker** [comment]
Confusing names are confusing, my bad!

**Comment by bradfitz** [comment]
No prob. Thanks for fixing the other one.

**Comment by rolandshoemaker** [comment]
Now that I look `checkConnHeaders` should probably be checking `TE == ("trailers" || "")`?

**Comment by bradfitz** [comment]
Yeah, looks like it.
