### ISSUE TITLE
cmd/compile: "attempt to load unspilled value" compiling valid code

### ISSUE THREAD

**Issue by josharian** [golang/go#15084]
Attempt to compile:

```go
package x

type T struct {
	i int
	e interface{}
}

func (t *T) F() bool {
	if t.i != 0 {
		return false
	}
	_, ok := t.e.(string)
	return ok
}

var x int

func g(t *T) {
	if t.F() || true {
		if t.F() {
			x = 0
		}
	}
}
```

Result:

`x.go:19: internal compiler error: attempt to load unspilled value v69 = MOVQload <*uint8> [8] v5 v1`

git bisect points at 40f2b57e0b007aaabe2b6ec5650223d047cd1452, CL 19728.

This is blocking other compiler changes I'm working on.

cc @brtzsnr @dr2chase @randall77

**Comment by brtzsnr** [comment]
Looks like an issue in the register allocator and that cl is just triggering it. I don't know enough about the register allocator, so I cannot be sure.

**Comment by josharian** [comment]
May be, although it is also possible that this case tickles deadcode into feeding the register allocator invalid SSA. I haven't looked.

In any case, when this is fixed, we should also remove the go:noinline work around for IsSlice (in type.go) introduced in CL 21611.

**Comment by randall77** [comment]
Combination of:
  1) phielimValue leaving graph with values not dominating uses (https://go-review.googlesource.com/c/22335/)
  2) bug in the dominator graph calculation (#22334)
  3) bug in check() not detecting #1 or #2 (#22330)
All in all, a very nice test case.

**Comment by dr2chase** [comment]
Should be fixed, see https://go-review.googlesource.com/#/c/22347/
