### ISSUE TITLE
tour: Maps can be created and used without make

### ISSUE THREAD

**Issue by SpencerBrown** [golang/go#15083]
Downloaded Go 1.6 and ran `go tool tour`. Nicely done!

Found one small issue. On slide `moretypes/16` it says:

"Maps must be created with make before use; the nil map is empty and cannot be assigned to."

This is not completely accurate. The second part is true. However, the first part is not. I can create a map by assigning it from a map literal, and use it, without ever invoking `make`. 

For example, from the very next slide:

```
var m = map[string]Vertex{
	"Bell Labs": Vertex{
		40.68433, -74.39967,
	},
	"Google": Vertex{
		37.42202, -122.08408,
	},
}
```

and I can use this map, for example:

```
	m["Somewhere"] = Vertex{42.2, 43.3}
	fmt.Println(m)
```

**Comment by ianlancetaylor** [comment]
CC @adg @campoy
