### ISSUE TITLE
cmd/go: -buildmode=c-shared with non-main package should fail rather than building an archive

### ISSUE THREAD

**Issue by jaseg** [golang/go#15082]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

Go 1.6, but tried with 1.5.3 to same result.
1. What operating system and processor architecture are you using (`go env`)?

(debian 8/jessie, amd64 on KVM)

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/jaseg/ffi/go"
GOTOOLDIR="/home/jaseg/ffi/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
1. What did you do?

Using the source file at https://github.com/jaseg/ffi/blob/9baa10bd4f5c780a7ae6816db48ea7e5b79a813b/stage24.go

```
go build -buildmode=c-shared -o libstage24.so stage24.go
```
1. What did you expect to see?

Something along the lines of

```
debian~/ffi <3 file libstage24.so
libstage24.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=26aed769e1c0f9026e59b47ab0544d32aada2b40, not stripped
```

as promised by `go help buildmode`.
1. What did you see instead?

```
debian~/ffi <3 file libstage24.so
libstage24.so: current ar archive
```

edit: [Here is the output](https://gist.github.com/jaseg/a4a84a083e5f7616983c842ba293cde3) of `go build -x [...]`.

Since I do not have any experience with go, this might very well be due to some oversight on my part. I would still be glad for any hints.

Thank you.

**Comment by ianlancetaylor** [comment]
You need to use `package main`, not `package stage24`.

Let's change this issue to reporting an error rather than building something useless.

**Comment by jaseg** [comment]
Thank you, that fixed it. I agree that an error message would be helpful in this case.

**Comment by jaseg** [comment]
tgo

**Comment by rsc** [comment]
I will send a CL making -buildmode=c-shared match the others that require a single main package as the argument. I have no idea if that's correct.
