### ISSUE TITLE
cmd/go: go generate doesn't obey $GOPATH that `go` uses

### ISSUE THREAD

**Issue by purpleidea** [golang/go#15095]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

```
go version go1.5.3 linux/amd64
```

but present in latest golang too i think.
1. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/james/code/gopath/"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
1. What did you do?
   I ran:

```
export GOPATH=something
GOPATH=whatever go generate
```
1. What did you expect to see?
2. What did you see instead?

I expected go generate to use the $GOPATH `whatever`, instead it uses `something`

This is obviously a huge issue because if you want to override the GOPATH in a script, this causes completely unexpected results!

**Comment by purpleidea** [comment]
Alternatively, it could be that `go generate`, isn't falling back to the second term in the $GOPATH search term when more than one is specified...

**Comment by robpike** [comment]
Please give a full reproducible example. The issue text is not clear.
