### ISSUE TITLE
test: goprint.go is timing dependent

### ISSUE THREAD

**Issue by millerresearch** [golang/go#15097]
The plan9_arm builder is occasionally failing in test/goprint.go, for example [here](http://build.golang.org/log/dc1d20083ee84f40c8e0a43a143be74267a58a25).

Like #15096, this is a timing dependency + slow builder issue rather than being specifically a Plan 9 issue.  It's a simple test:
```
func main() {
	go println(42, true, false, true, 1.5, "world", (chan int)(nil), []int(nil), (map[string]int)(nil), (func())(nil), byte(255))
	time.Sleep(100*time.Millisecond)
}
```
Since the parent goroutine doesn't wait for the child to terminate, this will only succeed if the child can run and deliver all its output in a tenth of a second.  On the plan9_arm builder, running 16 go programs (4 simultaneous shards x 4 tests per shard) in 1GB of RAM, this doesn't always happen.

Doubling the sleep time is a quick fix but costs all the builders 0.1 second, without being an absolute guarantee of success.

Instead, would it make sense to check explicitly for termination of the child goroutine, something like this? (assuming there are no garbage collectors or other hidden goroutines in the background):
```
func main() {
	go println(42, true, false, true, 1.5, "world", (chan int)(nil), []int(nil), (map[string]int)(nil), (func())(nil), byte(255))
	for i := 0; i < 10 && runtime.NumGoroutine() > 1; i++ {
		time.Sleep(50*time.Millisecond)
	}
}
```

**Comment by bradfitz** [comment]
Or just:

```go
func main() {
    go println(42, true, false, true, 1.5, "world", (chan int)(nil), []int(nil), (map[string]int)(nil), (func())(nil), byte(255))
    for runtime.NumGoroutine() > 1 {}
}
```

**Comment by minux** [comment]
On Apr 4, 2016 11:22 AM, "Brad Fitzpatrick" <notifications@github.com>
wrote:
> Or just:
>
> func main() {
>     go println(42, true, false, true, 1.5, "world", (chan int)(nil),
[]int(nil), (map[string]int)(nil), (func())(nil), byte(255
> ))
>     for runtime.NumGoroutine() > 1 {}
> }

Should we use runtime.Gosched() in the body? NumGoroutine might not always
be a preemption point.

**Comment by bradfitz** [comment]
We don't need to pre-empt.

We just need to wait for println to finish.

**Comment by millerresearch** [comment]
If tests are running on a uniprocessor, won't spinning in a loop delay println from running?
Also I thought the wait should be bounded just in case there is another goroutine in the background.

**Comment by bradfitz** [comment]
Oh, I see the concern. I think any function call should be a preemption point anyway, but you can call runtime.Gosched or sleep if you want.

**Comment by minux** [comment]
A function call might not be a preemption point if it's (recursively)
inlined and I imagine that we could implement runtime.NumGoroutine as a
single atomic load.
