### ISSUE TITLE
godoc: standard library and GOPATH packages are mixed.

### ISSUE THREAD

**Issue by siritinga** [golang/go#15094]
1. What version of Go are you using (`go version`)?

go version go1.6 windows/386

2. What operating system and processor architecture are you using (`go env`)?

Windows 7 32 bits

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Dropbox\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?

I have several packages in GOPATH/src, some mine, some from other people. I run the Godoc server locally (using the installed shortcut) and browse the packages.

4. What did you expect to see?

I expect to see only the standard library in the "Standard library" section, and GOPATH packages in its own section (possibly in Other packages)

5. What did you see instead?

There is a first section called "Standard library". However, all available packages (from the standard library and at GOPATH/src) are listed here, mixed. Later, there is a section called "Other packages" with two subsections (Sub-repositories and Community) but no packages from GOPATH listed there.

**Comment by bradfitz** [comment]
Dup of #3305

/cc @adg
