### ISSUE TITLE
Build fails at tip on darwin/amd64 with net: FAIL

### ISSUE THREAD

**Issue by rjammala** [golang/go#15101]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +f229e46 Mon Apr 4 14:07:47 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rajanikanth.j/gocode"
GORACE=""
GOROOT="/Users/rajanikanth.j/go"
GOTOOLDIR="/Users/rajanikanth.j/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4f/4vg7m4ys42vg8r2q7pxhqdw8jrldwy/T/go-build904284838=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Tried to build go at tip.

4. What did you expect to see?
Build passes.

5. What did you see instead?
Build fails:
FAIL
FAIL	net	1.748s

2016/04/04 10:33:55 Failed: exit status 1

@bradfitz

**Comment by rjammala** [comment]
Seems like a random failure. I cannot reproduce.

**Comment by Thomasdezeeuw** [comment]
Maybe related issue #14986.
