### ISSUE TITLE
cmd/go: remove special-case that puts godoc in $GOROOT/bin

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#15106]
1. What version of Go are you using (`go version`)?
> go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="$HOME/devel/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
```bash
go get -v golang.org/x/tools/cmd/godoc
```

4. What did you expect to see?
`godoc` gets installed to `$GOPATH/bin/godoc`.

5. What did you see instead?
> go install golang.org/x/tools/cmd/godoc: open /usr/lib/go/bin/godoc: permission denied

On Arch Linux, and, I assume, most other distributions that have a Go package in their repositories, `$GOROOT` is set to a directory that all users have access to. On Arch, it gets set to `/usr/lib/go/`. This means that installing `godoc` via `go get` can only be done by root because it is hardwired in the `go` tool (pkg.go:703) to install to `$GOROOT/bin`.

**Comment by bradfitz** [comment]
I believe this was intentional, as part of the transition of moving godoc out of the standard library. But maybe it's time to reconsider that. @adg, @robpike?

**Comment by robpike** [comment]
-me, +@rsc

**Comment by adg** [comment]
I think we should probably remove the special case for Go 1.7.
Once this was necessary to make `go doc` work, but `cmd/doc` has made that unnecessary.

The release-builder tool can take care of putting `godoc` in `$GOROOT/bin` for binary releases.

**Comment by adg** [comment]
I have submitted the fix to `cmd/go`, but will hold off on submitting the corresponding [change to `x/build/cmd/release`](https://go-review.googlesource.com/#/c/21703/) until just before Go 1.7 beta1. Keep this issue open and associated with the Go 1.7 milestone until then.

**Comment by quentinmit** [comment]
Ping @adg. We're closing in on the beta release, so it's about time to submit your CL.

**Comment by adg** [comment]
Thanks for the reminder @quentinmit!
