### ISSUE TITLE
x/tools/cmd/godoc: first return value with an unqualified imported type not showing up in documentation output

### ISSUE THREAD

**Issue by mikeatlas** [golang/go#15107]
1. What version of Go are you using (`go version`)?
   `go version go1.5.3 linux/amd64`
2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mikeatlas/gopath"
GORACE=""
GOROOT="/home/mikeatlas/golang/go"
GOTOOLDIR="/home/mikeatlas/golang/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
1. What did you do?

Using `godoc -http=:6060` to generate live documentation, I seem to have an edge case that does not appear to make any sense. Function return values with an imported type without a qualifier as the first value do not appear in documentation, with return order being the only difference and the imported type without a qualifier as the first return value will cause the function to not show up in documentation output HTML. An example is as follows:

``` go
package xyz

import . "qpackage/q"

// TestFn is a test function
func TestFn(input string) (Q, error) {}

// TestFnX is a test function
func TestFnX(input string) (error, Q) {}
```

In this example, only `TestFnX` appears in the documentation output. However, if I qualify the imported package type, both work:

``` go
package xyz

import q "qpackage/q"

// TestFn is a test function
func TestFn(input string) (q.Q, error) {}

// TestFnX is a test function
func TestFnX(input string) (error, q.Q) {}
```

In this example, both `TestFn` and `TestFnX` appear in the documentation output.
1. What did you expect to see?

Both examples in the code sample above should have worked - the return order of the imported type seems to be the only difference; I'm able to generate documentation for the function if the first return value type is not from the unqualified imported package.
1. What did you see instead?

Only if a native type is returned first, or if the imported type has a qualifier, will the function appear correctly in the `godoc` output.

**Comment by mikeatlas** [comment]
Would a test project here on GitHub demonstrating the bug be useful?

**Comment by bradfitz** [comment]
Maybe this is just punishment for using `import .`?  :-)

**Comment by mikeatlas** [comment]
@bradfitz You know someone's eventually going to shoot themselves in the foot if you give out guns :) Thanks for triaging this.

**Comment by agnivade** [comment]
@mikeatlas - Yes, it would be great if you can setup a test repo on github.

**Comment by agnivade** [comment]
I am unable to repro this. Can you try with latest go 1.10.1 and godoc tip ?

**Comment by mikeatlas** [comment]
If you can't repro it from the steps above, and no other reports, it is likely resolved!
