### ISSUE TITLE
x/tools/mobile: gomobile and iphone 5 issue

### ISSUE THREAD

**Issue by ConradKurth** [golang/go#15115]
Hello, I am using  go1.6 darwin/amd64 and on a mac running OSX 10.10.5

I am trying to build an SDK for a mobile project using gomobile bind -target ios and the SDK produced will work on iphones newer than an iphone 5 but, anything sub iphone 5 will produce a crash. 

<img width="573" alt="crash" src="https://cloud.githubusercontent.com/assets/1794593/14264226/b74bc14a-fa73-11e5-83af-3dd37dd45089.png">

Now when I go back to go version 1.5.3 and init the mobile tool chain again it will work just fine on iphone 5. I saw issue #12590 referenced a similar crash a year ago, but it seems to have resurfaced

**Comment by eliasnaur** [comment]
Have you tried Go tip? This is a possible dup of #14778, which was fixed by ea4b785ae03a067f4a26adac78213ff6caac5128.

I'm hoping to get the fix into Go 1.6.1, if/when it is released.
