### ISSUE TITLE
cmd/compile: s[i:] should be treated the same as s[i:len(s):len(s)]

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#15116]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
 `go version devel +bc94282 2016-04-04 21:22:44 +0000 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
```go
func a(i int, in []byte) []byte { return in[i:] }
func b(i int, in []byte) []byte { return in[i:len(in):len(in)] }
```

4. What did you expect to see?
 Same assembly for both.

5. What did you see instead?
 a is larger.

**Comment by mdempsky** [comment]
`in[i:]` is the same as `in[i:len(in):cap(in)]`, not `in[i:len(in):len(in)]`.  If I change b to actually be semantically equivalent to a, then they compile to the same number of instructions for me on linux/amd64.

**Comment by OneOfOne** [comment]
So no way to get the lower number of instructions (aka `in[i:len(in):len(in)]`) without using that hack?

**Comment by mdempsky** [comment]
Your bug report as originally stated is invalid: you're comparing two functions with different semantics, so it's unsurprising that the Go compiler compiles them into different instruction sequences.

If you can suggest a more efficient instruction sequence that the Go compiler could use to implement `a` *without* altering its semantics, that would be something we could consider.
