### ISSUE TITLE
build: ssa "gen" binary is created during make.bash

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15122]
Some SSA-related `gen` binary is created during make.bash and lives in `bin`.

Do we need it there? Do we need it after make.bash?

I'm happy to clean if it's not intentional.

/cc @randall77

**Comment by minux** [comment]
It's cmd/compile/internal/ssa/gen, and it's not intended to
be installed into $GOROOT/bin.

I guess cmd/dist should only install top-level cmd/* programs.

**Comment by bradfitz** [comment]
It's not needed during make.bash, right? Can it be +build ignore?

**Comment by davecheney** [comment]
Yup, and the instructions in that packages' README say to use `go run
*.go`.

See, https://go-review.googlesource.com/21524

**Comment by minux** [comment]
it's not needed by make.bash. yeah, +build ignore should
be fine.
