### ISSUE TITLE
Merge mlockall support to *BSDs

### ISSUE THREAD

**Issue by sean-** [golang/go#15136]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version devel +eb876dd Tue Apr 5 17:41:47 2016 +0000 freebsd/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
% go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/vagrant/go"
GORACE=""
GOROOT="/home/vagrant/go-devel"
GOTOOLDIR="/home/vagrant/go-devel/pkg/tool/freebsd_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build517630784=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

Attempt to use `syscall.Mlocall` on FreeBSD.

The work has been done and it's sitting in Gerritt waiting to be merged, but seems like it's lost in the fray.  I'm creating an issue to keep track of this patch.  Getting `mlockall(2)` and friends added to FreeBSD (and other BSDs) is important in order to support projects that should keep sensitive data off disk (i.e. Vault, https://www.vaultproject.io).  In an ideal world this code would land in time for the 1.7 release.

https://go-review.googlesource.com/#/c/1921

**Comment by bradfitz** [comment]
That was merged already, a year ago.

(That change you linked to is in the x/sys subrepo: golang.org/x/sys/unix)

If you're talking about the syscall package in the standard library, it has been frozen for the past few releases. See https://golang.org/s/go1.4-syscall, which is also noted at the top of https://golang.org/pkg/syscall/#pkg-overview

**Comment by sean-** [comment]
! Thanks Brad, I missed that along the way.  Cheers.
