### ISSUE TITLE
time.Time  json encoding

### ISSUE THREAD

**Issue by bd4k** [golang/go#15144]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +7e0d660 Tue Apr 5 20:38:41 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64

3. What did you do?
May be  RFC3339Nano encoding problem in time.Time ? 

package main

import (
"fmt"
"time"
"encoding/json"
)
func main() {
	t:=time.Now()
	bb,_:=json.Marshal(t)
	fmt.Println(string(bb))
}
4. What did you expect to see?
2016-04-05T23:59:59Z05:00

5. What did you see instead?
2016-04-05T23:59:59Z

**Comment by bradfitz** [comment]
It depends on the timezone: http://play.golang.org/p/pw7q1sLTE4
