### ISSUE TITLE
testing: TestTRun failing on the plan9/arm builder since CL 21504

### ISSUE THREAD

**Issue by 0intro** [golang/go#15149]
Since [CL 21504](https://golang.org/cl/21504), TestTRun is failing on the plan9/arm builder.

```
--- FAIL: TestTRun (0.06s)
	sub_test.go:373: failnow skips future sequential and parallel tests at same level:ouput:
		got:
		--- FAIL: failnow skips future sequential and parallel tests at same level (0.01s)
		    --- FAIL: failnow skips future sequential and parallel tests at same level/#00 (0.00s)
		want:
		--- FAIL: failnow skips future sequential and parallel tests at same level (0.00s)
		    --- FAIL: failnow skips future sequential and parallel tests at same level/#00 (0.00s)
FAIL
FAIL	testing	3.440s
```

See http://build.golang.org/log/41d221b5accf16216bb6d9f1a767cbfff7c8e6f1

The plan9/arm builder is running on a Raspberry Pi 3, which is a slow machine. The output comparison is failing because the test executes slightly slower than expected.

Perhaps we should ignore the time when comparing the string. What do you think?

CC: @mpvl @bradfitz @millerresearch

**Comment by millerresearch** [comment]
> Perhaps we should ignore the time when comparing the string. What do you think?

Yes, either sanitizeLog could remove the duration (N.NNs) from the end of lines, or the comparison between want: and got: could be done as a regular expression match (and sanitizeLog would not be needed).
