### ISSUE TITLE
runtime: randomNumber is unused on linux/arm64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15147]
In the runtime, linux/arm defines a global variable `randomNumber` which is used by `cputicks`.

arm64 instead has this in `src/runtime/os_linux_arm64.go`

```go
var randomNumber uint32

//go:nosplit
func cputicks() int64 {
        // Currently cputicks() is used in blocking profiler and to seed fastrand1().
        // nanotime() is a poor approximation of CPU ticks that is enough for the profiler.
        // randomNumber provides better seeding of fastrand1.
        return nanotime() + int64(randomNumber)
}
```

... but never defines randomNumber to anything, unlike arm.

Bug? Incomplete? Missing TODO?

**Comment by minux** [comment]
it is probably an oversight. Sent CL 21580.
