### ISSUE TITLE
encoding/json: ",string" bool field accepts "terrible" as true

### ISSUE THREAD

**Issue by chanxuehong** [golang/go#15146]
*EDIT by @bradfitz*: see below in comment https://github.com/golang/go/issues/15146#issuecomment-207343147 ; _Original bug report follows..._

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\gopath
set GORACE=
set GOROOT=d:\go
set GOTOOLDIR=d:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?  
If possible, provide a recipe for reproducing the error.  
A complete runnable program is good.  
A link on play.golang.org is best.  

http://play.golang.org/p/Jmzo5N4kHV
```Go
package main

import (
	"encoding/json"
	"fmt"
)

type X struct {
	A string `json:"a,string"`
	B bool   `json:"b,string"`
	C int    `json:"c,string"`
}

func main() {
	b := []byte(`{"a":"n","b":"t","c":"100"}`)

	var x X
	if err := json.Unmarshal(b, &x); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("%+v\n", x)
}
```

4. What did you expect to see?

like
```
json: invalid use of ,string struct tag, trying to unmarshal ...
```

5. What did you see instead?
```
{A: B:true C:100}
```

**Comment by bradfitz** [comment]
The error message is correct: it's an invalid use of the `,string` option. After removing the quotes on `"n"`, what's left is `n`, which isn't a valid JSON string.

**Comment by chanxuehong** [comment]
@bradfitz yes, After removing the quotes on  "n" , what's left is  n , which isn't a valid JSON string.

but now encoding/json does not report the error message, and we got
```
{A: B:true C:100}
```

it is right???

**Comment by chanxuehong** [comment]
After removing the quotes on  "n" , what's left is  n , which isn't a valid JSON string.
and 
After removing the quotes on  "t" , what's left is  t , which isn't a valid JSON string.

but now the result is 
```
{A: B:true C:100}
```
A is "" and B is true

I think it is a bug!

**Comment by bradfitz** [comment]
Let's move this discussion to a forum. See https://golang.org/wiki/Questions

You're obviously looking something, but whatever it is, I don't think it's the `,string` option.

**Comment by chanxuehong** [comment]
I think it's the ```,string``` option
since it has ```,string``` option, it should unquoteBytes(https://github.com/golang/go/blob/853f1a1a63b759686421196d419ddaa626a44bf5/src/encoding/json/decode.go#L1071)

https://groups.google.com/forum/#!forum/golang-nuts

**Comment by yunyet** [comment]
It is definitely a bug. Why it be closed?

**Comment by transtone** [comment]
@bradfitz 
```
The error message is correct: it's an invalid use of the ,string option. After removing the quotes on "n", what's left is n, which isn't a valid JSON string.
``` 
so it should get a err, not a struct.

**Comment by kostya-sh** [comment]
This looks like a bug.

Also decoding bool field with ",string" tag doesn't looks correct: *tra-la-la* is decoded to *true*.

http://play.golang.org/p/upVyInopWQ
```
package main

import (
	"encoding/json"
	"fmt"
)

type X struct {
	B bool   `json:"b,string"`
}

func main() {
	b := []byte(`{"b":"tra-la-la"}`)
	var x X
	if err := json.Unmarshal(b, &x); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("%+v\n", x)
}
```

**Comment by bradfitz** [comment]
@kostya-sh, thanks! I've reopened this bug and edited the original bug report's header to link to your example.

**Comment by sergeylanzman** [comment]
This is not bug(maybe?)
if value started from 't' json decoder return true (example "tra-la-la")
if value started from 'f' json decoder return false(example "foo")
in code this 
[line in code](https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L1028)
```
case 't', 'f': // true, false
		return c == 't'
```
@bradfitz  If you think this is bug?

**Comment by kostya-sh** [comment]
This example shows the difference in error handling while decoding fields with and without ",string" tag: http://play.golang.org/p/RatENpHcvP


There are 3 problems as far as I can see (with ",string" tag):
- any value starting with "t" is interpreted as true for bool field
- any value starting with "f" is interpreted as false for bool filed
- any value starting with "n" is interpreted as null for bool, string and int fileds

**Comment by rsc** [comment]
The single letter check is not meant to intentionally accept "terrible" as true and "factual" as false. It is simply a mistake introduced when ,string was added. Originally the JSON parser was only letting true, false, and null through to that case, so looking at the first letter was sufficient. But the ,string code started passing arbitrary strings to that code and didn't first check to see if that was appropriate. Just a bug, not intended, nothing more.

Should be easy to fix.

Thanks for the simple case @kostya-sh.
