### ISSUE TITLE
runtime/pprof: TestGoroutinesCounts is flaky

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15156]
https://storage.googleapis.com/go-build-log/4d227eb8/openbsd-amd64-gce58_b43ea4d4.log

```
--- FAIL: TestGoroutineCounts (0.04s)
    pprof_test.go:607: expected sorted goroutine counts:
        goroutine profile: total 102
        49 @ 0x426a61 0x426b34 0x403f2d 0x403c6b 0x4706e6 0x44f441
        #   0x4706e5    runtime/pprof_test.func3+0x35   /tmp/workdir/go/src/runtime/pprof/pprof_test.go:584
        #   0x0

        40 @ 0x426a61 0x426b34 0x403f2d 0x403c6b 0x470696 0x44f441
        #   0x470695    runtime/pprof_test.func2+0x35   /tmp/workdir/go/src/runtime/pprof/pprof_test.go:583
        #   0x0

        10 @ 0x426a61 0x426b34 0x403f2d 0x403c6b 0x470646 0x44f441
        #   0x470645    runtime/pprof_test.func1+0x35   /tmp/workdir/go/src/runtime/pprof/pprof_test.go:582
        #   0x0

        1 @ 0x403c70 0x403c6b 0x4706e6 0x44f441
        #   0x4706e5    runtime/pprof_test.func3+0x35   /tmp/workdir/go/src/runtime/pprof/pprof_test.go:584
        #   0x0

        1 @ 0x426a61 0x426b34 0x403f2d 0x403c6b 0x4628a0 0x465bbd 0x46263a 0x4636d6 0x462c18 0x401244 0x42660a 0x44f441
        #   0x46289f    testing.(*T).Run+0x21f      /tmp/workdir/go/src/testing/testing.go:579
        #   0x465bbc    testing.RunTests.func1+0x5c /tmp/workdir/go/src/testing/testing.go:724
        #   0x462639    testing.tRunner+0x79        /tmp/workdir/go/src/testing/testing.go:547
        #   0x4636d5    testing.RunTests+0x2b5      /tmp/workdir/go/src/testing/testing.go:730
        #   0x462c17    testing.(*M).Run+0x77       /tmp/workdir/go/src/testing/testing.go:675
        #   0x401243    main.main+0xb3          runtime/pprof/_test/_testmain.go:72
        #   0x426609    runtime.main+0x209      /tmp/workdir/go/src/runtime/proc.go:188
        #   0x0

        1 @ 0x46ac28 0x46aa41 0x4672c9 0x47085c 0x46263a 0x44f441
        #   0x46ac27    runtime/pprof.writeRuntimeProfile+0x97      /tmp/workdir/go/src/runtime/pprof/pprof.go:555
        #   0x46aa40    runtime/pprof.writeGoroutine+0x90       /tmp/workdir/go/src/runtime/pprof/pprof.go:517
        #   0x4672c8    runtime/pprof.(*Profile).WriteTo+0x318      /tmp/workdir/go/src/runtime/pprof/pprof.go:236
        #   0x47085b    runtime/pprof_test.TestGoroutineCounts+0x15b    /tmp/workdir/go/src/runtime/pprof/pprof_test.go:603
        #   0x462639    testing.tRunner+0x79                /tmp/workdir/go/src/testing/testing.go:547
        #   0x0

FAIL
FAIL    runtime/pprof   1.683s
ok      runtime/trace   18.945s
```

**Comment by chlunde** [comment]
It looks like it's still flaky 
* [2017-05-15T19:17:35-256210c/linux-amd64-noopt](https://build.golang.org/log/b477478f529b5a7a3ace44166b78c18bca8f720c)
* [2017-05-16T12:26:10-b2363ee/linux-386-sid](https://build.golang.org/log/795dec4688564d447d1f152ebedfa82abdc6757b)
* [2017-05-16T15:44:29-84a5143/linux-amd64-noopt](https://build.golang.org/log/dee7a0a3a71d1790c93aa317554e26831c8dd0d8)

I suspect it might be related to a busy OS scheduler, I can reproduce it within 500 runs when running the new test using tip when I have ~10 other busy processes on a Linux system.  Sometimes the slower goroutine seems to be in or just return from `runtime.morestack_noctxt`.

The flakyness goes away (under the same load) with 40 000 runs if I add

    defer runtime.GOMAXPROCS(runtime.GOMAXPROCS(1))

@aclements would you like me to add a CL, or is there a better way to synchronize for this test?

PS!  Looks like profile.String() here has an unrelated issue: `pprof_test.go:643: expected count profile to contain goroutines with counts [50 40 10 1], got %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)`

**Comment by aclements** [comment]
@chlunde, sure, that seems like a fine change to that test. Please send a CL.

> PS! Looks like profile.String() here has an unrelated issue

I tried to reproduce this and get a stack using testing/quick, but the only thing it found is that passing a nil *Profile crashes, but that would have crashed the real test earlier. (Unfortunately, testing/quick itself often crashes when it tries to set the value of an unexported field in Profile!)

**Comment by chlunde** [comment]
@aclements I see there's an uncommited change for the panic on https://go-review.googlesource.com/c/43152/
