### ISSUE TITLE
net: dial tests are flaky on BSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15157]
These have been flaking a lot on OpenBSD ...

https://storage.googleapis.com/go-build-log/f99ca413/openbsd-amd64-gce58_83506189.log

```
--- FAIL: TestDialTimeoutFDLeak (1.89s)
    dial_test.go:164: got 96; want >= 100
--- FAIL: TestDialerDualStackFDLeak (0.80s)
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
    dial_test.go:213: dial tcp 127.0.0.1:24574: i/o timeout
--- FAIL: TestReadUnixgramWithUnnamedSocket (0.19s)
    unixsock_test.go:60: read unixgram /tmp/go-nettest180765192: i/o timeout
--- FAIL: TestDialTimeoutMaxDuration (0.40s)
    timeout_test.go:140: #0: Dial didn't return in an expected time
FAIL
FAIL    net 12.082s
```

/cc @mikioh

**Comment by bradfitz** [comment]
Also on FreeBSD:

https://build.golang.org/log/73446e673c8f780dbfbc11aaab2b4f8e4daefb68
```
ok  	mime/quotedprintable	0.156s
--- FAIL: TestDialerDualStackFDLeak (0.58s)
	dial_test.go:172: dial tcp: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
	dial_test.go:172: dial tcp 127.0.0.1:59846: i/o timeout
FAIL
FAIL	net	2.256s
2016/05/11 17:45:36 Failed: exit status 1
```

@mikioh, @mdempsky, can one of you investigate?

**Comment by mdempsky** [comment]
Yeah, I'll look into the OpenBSD failures today.

**Comment by josharian** [comment]
Just saw what looked like a flake on a linux/amd64 race trybot run:

https://storage.googleapis.com/go-build-log/01e274f4/linux-amd64-race_4322dd7e.log

**Comment by mundaym** [comment]
Another possible flake on a linux/amd64 race trybot run:

https://storage.googleapis.com/go-build-log/f6b2f823/linux-amd64-race_be3b785d.log

**Comment by mdempsky** [comment]
I a little time looking into the TestDialerDualStackFDLeak flake on OpenBSD last night.

I was able to repro the issue under ktrace, and Go doesn't appear to be doing anything obviously wrong. We make a non-blocking connect call, it returns EINPROGRESS, we register it with kqueue, and then the kernel reports back 6 seconds later that the connect failed.

The failure is always around 6 seconds, so I suspect it's something TCP timeout related.

I was next trying to repro the issue while tcpdump'ing lo0 (hoping it hints what part of the stack might be failing), but no success yet.

**Comment by bradfitz** [comment]
@mdempsky, thanks for investigating.

If we can't make progress on this, though, the openbsd builders are doing more harm than good with flaky tests.

I think it might be time to slap on a bunch of `testenv.SkipFlaky(t, 15157)` to all these tests on OpenBSD.

**Comment by mdempsky** [comment]
@bradfitz For net flakes on OpenBSD, I'm inclined to agree.

**Comment by mdempsky** [comment]
Doesn't seem to be limited to BSD: https://storage.googleapis.com/go-build-log/fa1eb023/linux-amd64-race_e3f8fc0c.log

    --- FAIL: TestDialTimeoutFDLeak (0.59s)
    	dial_test.go:136: got 99; want >= 100

**Comment by bcmills** [comment]
On `darwin-386-10_14` (https://build.golang.org/log/6e8422bf8109adb9f942363402c03bd942fe0):

```
--- FAIL: TestDialTimeoutMaxDuration (0.36s)
    timeout_test.go:133: #0: Dial didn't return in an expected time
FAIL
FAIL	net	11.653s
```

**Comment by bcmills** [comment]
Filed the `darwin` failures separately as #43069.

**Comment by bcmills** [comment]
I don't see any recent failures for `TestDialTimeoutFDLeak` or `TestReadUnixgramWithUnnamedSocket`.

**Comment by bcmills** [comment]
The `i/o timeout` failure mode of `TestDialerDualStackFDLeak` now only occurs on Solaris (#43070).

**Comment by bcmills** [comment]
The remaining `TestDialerDualStackFDLeak` failures on BSD have a different failure mode from the one reported here, filed as #43071.

I'm going to close out this meta-issue, since there are now separate issues for the individual observed failure modes.
