### ISSUE TITLE
bytes: buffer.readSlice is not exported

### ISSUE THREAD

**Issue by Tasssadar** [golang/go#15154]
Currently, `readSlice` method in `bytes.Buffer` is private, which means there is no easy way to read the buffer by delimiter without needlessly allocating another slice.

Since it is already there, and [bufio package has the same method exported](https://golang.org/pkg/bufio/#Reader.ReadSlice), I propose making this method exported in the `bytes` package as well (with proper warnings about its usage in the comments, the same way `bufio` does it).

I can submit a patch, but since I'm not sure whether these kind of changes are acceptable (it is non-breaking change, right?), I'd rather ask first.

**Comment by bradfitz** [comment]
Can't you already do this by calling Buffer.Peek + searching Buffer.Bytes in a loop with an increasingly large peek value?

**Comment by Tasssadar** [comment]
Yes, you can, or just implement readSlice yourself in like 5 lines. It is just a matter of convenience and bufio already has it (in fact, it took me a while to figure out why do I remember that I could use ReadSlice - I've used it on bufio.Reader previously), so I thought I'd mention it and/or send a patch.

**Comment by bradfitz** [comment]
Sorry, I don't think we'll do this. We try not to expand the API unless it's really valuable (needed by many people and/or solves a problem not otherwise solvable). I don't think this falls into either of those buckets.

Related: https://golang.org/doc/faq#x_in_std
