### ISSUE TITLE
context: TestTimeout is flaky

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15158]
https://storage.googleapis.com/go-build-log/40e67803/openbsd-amd64-gce58_28491a1d.log
```
--- FAIL: TestTimeout (0.88s)
	context_test.go:235: context should have timed out
FAIL
FAIL	context	5.052s
```

/cc @mikioh

**Comment by mikioh** [comment]
It happens on freebsd/amd64: https://storage.googleapis.com/go-build-log/142b529a/freebsd-amd64-gce101_b840e700.log

**Comment by mdempsky** [comment]
I'm under the impression the problem is just the test was sensitive to >100ms spikes of kernel process scheduling latency, which was common on OpenBSD and not impossible on other OSes?

**Comment by bradfitz** [comment]
Correct.
