### ISSUE TITLE
net/http: ErrWriteAfterFlush unused

### ISSUE THREAD

**Issue by perillo** [golang/go#15150]
The variable ErrWriteAfterFlush, defined in net/http/server.go, is never used.

After a bit of code archaeology with git, I found that the variable was introduced in https://github.com/golang/go/blob/e73acc1b35f3490f3d800b4bf49da79630e808fc/src/lib/http/server.go, but at some point it was no more used.

**Comment by perillo** [comment]
The `unused` tool, with the `-export` flag, also reports the following error variables to be unused:

- ErrHeaderTooLong
- ErrShortBody
- ErrNotSupported
- ErrMissingContentLength
- ErrNoCookie
- ErrLineTooLong

However I have not checked if they are obsolete as with ErrWriteAfterFlush.

**Comment by dominikh** [comment]
All of those are part of the public API and cannot be removed under the Go 1 compatibility guarantee. Also, most of these are defined in terms of their `net/http/internal` counterpart are returned from internal and used by users of net/http.

As an aside, `unused -exported` is not at all useful for the standard library, except when checking `internal` packages. All exported identifiers in the stdlib are by nature used by users of Go.

**Comment by perillo** [comment]
On Wed, Apr 6, 2016 at 12:34 PM, Dominik Honnef <notifications@github.com>
wrote:

> All of those are part of the public API and cannot be removed under the Go
> 1 compatibility guarantee. Also, most of these are defined in terms of
> their net/http/internal counterpart are returned from internal and used
> by users of net/http.
>

At least ErrWriteAfterFLush seems to be obsolete.  Of course it can not be
removed, but a comment can be added to explain that it is no more used.

IMHO, a variable without a comment and that appears to be never used, only
cause confusion for users (at least for me).
