### ISSUE TITLE
cmd/link: go.dwarf.info.runtime.symtab: cannot find elf name .debug_abbrev

### ISSUE THREAD

**Issue by gyuho** [golang/go#15166]
I think https://github.com/golang/go/commit/a037c73ccfc7c35a389e95ffa7996c8dd38e0cde broke something with `go build`. We didn't see this error before this commit.

###### What version of Go are you using (`go version`)?

```
go version devel +b17b953 Thu Apr 7 04:17:26 2016 +0000 linux/amd64
```

###### What operating system and processor architecture are you using (`go env`)?

```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gyuho/go"
GORACE=""
GOROOT="/home/gyuho/go-master/go"
GOTOOLDIR="/home/gyuho/go-master/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build034386466=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
###### What did you do?

```
git clone git@github.com:coreos/etcd.git
cd ./etcd
./build

# or 

CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-s -X github.com/coreos/etcd/version.GitSHA=GitNotFound" -o bin/etcd github.com/coreos/etcd/cmd
```

###### What did you expect to see?

No error message.

###### What did you see instead?

```
go.dwarf.info.runtime.symtab: cannot find elf name .debug_abbrev
```

Thanks all!

**Comment by gyuho** [comment]
Sorry that I didn't give enough information. I am not expert on this. Please let me know
if there's anything I can do to help you investigate on this. I will try to get simplest code
that can fail from this change.

**Comment by crawshaw** [comment]
@ribrdb can you take a look at this? I would guess this is related to -X.

**Comment by gyuho** [comment]
Confirmed that it is fixed in `etcd` side. Thanks a lot!
