### ISSUE TITLE
1.6.2: backport runtime GOMAXPROCS crash fix

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15160]
Tracking bug to decide whether to backport the fix to #15131 (Go binaries failing at start with `procresize: invalid arg` if there are more than 256 CPUs)

Request to do so from @mwhudson: https://github.com/golang/go/issues/15131#issuecomment-206656551

The fix (31cf1c17792d4da9dae2504c703633a0db8072c7) is small and just caps the CPUs to 256:

```patch
diff --git a/src/runtime/proc.go b/src/runtime/proc.go
index 5145c84..1f55b0f 100644
--- a/src/runtime/proc.go
+++ b/src/runtime/proc.go
@@ -449,6 +449,9 @@ func schedinit() {
 
        sched.lastpoll = uint64(nanotime())
        procs := int(ncpu)
+       if procs > _MaxGomaxprocs {
+               procs = _MaxGomaxprocs
+       }
        if n := atoi(gogetenv("GOMAXPROCS")); n > 0 {
                if n > _MaxGomaxprocs {
                        n = _MaxGomaxprocs
```

/cc @rsc @ianlancetaylor

**Comment by minux** [comment]
Note: there is a workaround. just use taskset(1) to
run Go processes with less than 256 CPUs.

As machines with more than 256 CPUs should be
rare, I don't think this meets the bar for Go 1.6.x.

**Comment by bradfitz** [comment]
The other workaround is the end user setting GOMAXPROCS=256. But if that user is just trying to run Docker and doesn't know Go, that's weird. There's nothing Docker themselves can do.

**Comment by minux** [comment]
Does docker use cgo? A workaround is call sched_setaffinity(2)
in a C constructor function to reduce the number of CPUs allowed
to run the current process. Or it can just set $GOMAXPROCS.

As docker is much more likely to run on machines with a huge
number of cores than any Go programs, a docker-specific
workaround seems plausible.

**Comment by ianlancetaylor** [comment]
The patch doesn't meet the guidelines, but it's so simple, and it's for Docker, so I'm inclined to think it is OK.
