### ISSUE TITLE
os: Mkdir can't add write permission to group/other user

### ISSUE THREAD

**Issue by math345** [golang/go#15161]
1. go version go1.5.1 linux/amd64
2. centos 7
3. go run xxx.go : success
4. ls -ll  
drw-r--r-- 2 root root 4096 Apr  7 10:03 testdir

question: Mkdir failed to add write permission to group/other user. Why?

code:

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	savepath := "testdir"
	if err := os.Mkdir(savepath, 0666); err != nil {
		fmt.Println("mkdir(", savepath, ") error:", err)
	} else {
		fmt.Println("mkdir success:", savepath)
	}
}
```

**Comment by bradfitz** [comment]
See https://en.wikipedia.org/wiki/Umask
