### ISSUE TITLE
playground: make the embedded version more compact

### ISSUE THREAD

**Issue by adg** [golang/go#15163]
This blog post makes good use to the playground:

https://developer.washingtonpost.com/pb/blog/post/2016/04/06/embrace-go/

It'd be nice if there were no "The Go Playground" heading, or "About", "Format", or "Imports" button. Instead the Run button could float in the top right (or bottom right, over the output section).

cc @broady

**Comment by mattn** [comment]
currently, `#wrap` is defined as `bottom: 25%`. how about to add `max-height`?
I never see my SL 

http://mattn.kaoriya.net/sl.html

**Comment by adg** [comment]
It's not that simple, I'm afraid. If you can devise a way to have the output resize itself dynamically, then I'd like to see it.

**Comment by mattn** [comment]
Do you mean playground should change the height with something like query parameter?

**Comment by adg** [comment]
No, I mean it should adjust the size of the output box depending on the
output itself
