### ISSUE TITLE
cmd/link: remove dependencies on cmd/internal/obj

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15165]
cmd/internal/obj is for writing Go object files, whereas cmd/link only reads Go object files.  We should remove cmd/link's dependencies on cmd/internal/obj by moving legitimately shared constants/types into separate packages.

See also #14782.

**Comment by davecheney** [comment]
Yes please.

**Comment by mwhudson** [comment]
Concur. I even wonder about de-coupling the constants used for LSym.Type between cmd/internal/obj and the linker -- the latter uses far more. The code to read them from object files could map from the obj.Type to the ld.Type. Or something -- currently the constant definitions in obj "know" way too much about the guts of the linker. (It doesn't help that the linker depends on the order these constants sort in)
