### ISSUE TITLE
cmd/compile: wrong code generation

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#15175]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +121c434 Thu Apr 7 09:57:06 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?

Compiled and ran the following code:

```
// gostress -seed 22885316 -want 253
package main
import "fmt"
import "os"
var b2i = map[bool]int{true:1}
func main() {
if got := f1_ssa(0, false, false, 1, 2, 2, 1, 1, ); got != 253 {
fmt.Printf("f1_ssa(0, false, false, 1, 2, 2, 1, 1, ) = %v, wanted 253\n", got)
os.Exit(1)
}
}
func f1_ssa(a1 uint, a2 bool, a3 bool, a4 uint64, a5 int8, a6 uint8, a7 int, a8 uint64, ) uint8 {
switch {} // prevent inlining
a4--
a7 *= a7 // int
a6 -= a6 + 3 // uint8
v1 := a7 | ((a7 & a7) + (a7 << a6) | (a7 - a7 - a7)) // int
_ = v1
a7--
v2 := a4 - (a4 & a4) // uint64
_ = v2
v3 := a3 // bool
_ = v3
return a6 >> (((2 << 3) - 1) >> a6)
}
```

4. What did you expect to see?
To print nothing

5. What did you see instead?
```
f1_ssa(0, false, false, 1, 2, 2, 1, 1, ) = 253, wanted 253
exit status 1
```

Clearly the comparison is wrong here.

**Comment by ALTree** [comment]
Small comment:

```
switch {} // prevent inlining
```

this no longer works. In fact, at tip `f1_ssa` in inlined.

**Comment by ALTree** [comment]
Also, disabling inlining fixes the issue: the code prints nothing.

**Comment by brtzsnr** [comment]
The fact that is behaves differently with inlining disabled and enabled it's a clear bug in the code generated. Most likely it's a rule that folds the comparisons, but I'd have to minimize the results first to figure out which. Alternatively one can bisect and find which patch is the culprit.

**Comment by brtzsnr** [comment]
A few more examples: 

http://play.golang.org/p/-HaD6RhlJj
http://play.golang.org/p/wtaffQRc2a
http://play.golang.org/p/6Mb6gmLQyE

**Comment by brtzsnr** [comment]
This is one is minimized:

```
package main
import "fmt"
import "os"
func main() {
a6 := uint8(253)
got := a6 >> 0
if got != 253 {
fmt.Printf("f1_ssa(0, false, false, 1, 2, 2) = %v, wanted 253\n", got)
os.Exit(1)
}
}
```

**Comment by ALTree** [comment]
Git bisect says it was introduced in go-review.googlesource.com/#/c/21256/

**Comment by brtzsnr** [comment]
There are a few things wrong:
a6 := uint8(253) -> (Const8 <uint8> [-3])  . I think it should be (Const8 <uint8> 253) instead.

This also happens:
(Neq8 (Const8 <uint8> [-3]) (Const8 <uint8> [-3])) -> (ConstBool <bool> [true])

which is an instantiation of 
(Neq8  (Const8  [c]) (Const8  [d])) -> (ConstBool [b2i(c != d)])

where c = 253 (coming from right shift) and d = -3 (coming from the constant above).

@randall77

**Comment by randall77** [comment]
In 21256 I changed the semantics of the AuxInt field to always be sign-extended.  So -3 is right, 253 is wrong.  It is ending up with 253 anyway because of a bad rewrite rule.  CL pending.
