### ISSUE TITLE
cgo: getting unsafe.Pointer of a slice slower in go 1.6 vs 1.5.3

### ISSUE THREAD

**Issue by piotrnar** [golang/go#15172]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
I tried on Windows 7 and all kinds of Linux OS.
I only tried on 64-bit hosts.

3. What did you do?
Just run this program with go 1.6 and see how slow it is, comparing to running it with 1.5.3

```
package main

/*
void alloc_ptr(void *c) {
	return;
}

*/
import "C"

import (
	"unsafe"
	"time"
)

type data_ptr_t unsafe.Pointer

func gcc_AllocPtr(v []byte) {
	C.alloc_ptr(unsafe.Pointer(&v[0]))
}

func main() {
	source_buf := make([]byte, 1024)
	start := time.Now()
	for i:=0; i<1e6; i++ {
		gcc_AllocPtr(source_buf)
	}
	println("done in", time.Now().Sub(start).String())
}

```

4. What did you expect to see?

> done in 228.0131ms

5. What did you see instead?

> done in 6.0343452s

**Comment by piotrnar** [comment]
I also want to add that there is an easy workaround:

```
package main

/*
void alloc_ptr(void *c) {
	return;
}

*/
import "C"

import (
	"unsafe"
	"time"
)

type data_ptr_t unsafe.Pointer

func gcc_AllocPtr(v []byte) {
	ptr := unsafe.Pointer(&v[0])
	C.alloc_ptr(ptr)
}

func main() {
	source_buf := make([]byte, 1024)
	start := time.Now()
	for i:=0; i<1e5; i++ {
		gcc_AllocPtr(source_buf)
	}
	println("done in", time.Now().Sub(start).String())
}

```

**Comment by ianlancetaylor** [comment]
Dup of #14387 .
