### ISSUE TITLE
database/sql: different handling of underlying types in DefaultParameterConverter

### ISSUE THREAD

**Issue by AlekSi** [golang/go#15174]
After e405c29ce74bf8145f88e4ce33b292474911ce71 (#11489) `DefaultParameterConverter` documentation says:

// DefaultParameterConverter returns its argument directly if
// IsValue(arg). Otherwise, if the argument implements Valuer, its
// Value method is used to return a Value. As a fallback, the provided
// argument's underlying type is used to convert it to a Value:
// underlying integer types are converted to int64, floats to float64,
// and **strings to []byte**. If the argument is a nil pointer,
// ConvertValue returns a nil Value. If the argument is a non-nil
// pointer, it is dereferenced and ConvertValue is called
// recursively. Other types are an error.

Underlying integers are really converted to int64, but underlying strings are not in fact converted – there is no code for this.

Testcase: https://github.com/AlekSi/go-sql-bugs/blob/master/issue15174_test.go
Test output: https://travis-ci.org/AlekSi/go-sql-bugs/builds/121408329 (see 1.6 and tip)

I propose to do what documentation says and convert the underlying string to []byte, it will help with custom string-like types with constants (enums).
Also, can we do the same thing for bools?

/cc @bradfitz

**Comment by sctb** [comment]
Is there a reason to convert underlying strings to []byte instead of just string (it is a Value after all)? We could then go ahead and support all of the Value types consistently: int64, float64, bool, []byte, string, time.Time.

**Comment by sctb** [comment]
I've got a change ready to go once 1.7 is out.

**Comment by 220kts** [comment]
@sctb A bit of a tangent, any chance you could take a look at #8415 and see if my proposed fix there ties in with the code changes you are working on here?

cc @ianlancetaylor , @ConnorFoody

**Comment by sctb** [comment]
@220kts  The change I had in mind here is quite straightforward, 
but I didn't include and changes to the handling of `nil` values:
```
@@ -245,6 +245,16 @@ func (defaultConverter) ConvertValue(v interface{}) (Value, error) {
                return int64(u64), nil
        case reflect.Float32, reflect.Float64:
                return rv.Float(), nil
+       case reflect.Bool:
+               return rv.Bool(), nil
+       case reflect.Slice:
+               ek := rv.Type().Elem().Kind()
+               if ek == reflect.Uint8 {
+                       return rv.Bytes(), nil
+               }
+               return nil, fmt.Errorf("unsupported type %T, a slice of %s", v, ek)
+       case reflect.String:
+               return rv.String(), nil
        }
        return nil, fmt.Errorf("unsupported type %T, a %s", v, rv.Kind())
 }
```

**Comment by 220kts** [comment]
Thanks @sctb  The current implementation is a bit inconsistent in its handling of nil pointers: a nil pointer to a basic type returns `nil, nil` but a nil pointer to a type that implements the Valuer interface calls the type's Value function.  This in turn breaks when the Value function is defined on a value (not on a pointer).

I would suggest to handle nil pointers consistently between basic types and types that implement the Valuer interface.  In the case of a type that implements the Valuer interface, this would allow the caller to decide whether to pass a pointer or a value to the ConvertValue function (which logically tends to correspond to database columns with or without NOT NULL constraint).  

Just thought it might make sense to consider that along with the change you propose.

**Comment by AlekSi** [comment]
Original testcase still fails on tip: https://travis-ci.org/AlekSi/go-sql-bugs/jobs/169501389.

**Comment by bradfitz** [comment]
@AlekSi, closed bugs aren't tracked. File a new bug if you must.

**Comment by kardianos** [comment]
@AlekSi Your bug tests for Scan types which should use valuers if custom. This issue talked about query parameters.

**Comment by AlekSi** [comment]
> Your bug tests for Scan types which should use valuers if custom. This issue talked about query parameters.

It wasn't my intention to limit this issue only to query parameters, although my analysis was incorrect. Basically, I wanted to be able to insert a value into a database and read it back into the same variable. And I wanted this behavior to be consistent for both predeclared types and named types with predeclared underlying types. As testcase shows, I can do it for `type Int64 int64` and `type Int32 int32`, and I can insert `type String string` into a database, but I can't read it back.

The reason why my analysis was incorrect is this comment:
```
// ValueConverter is the interface providing the ConvertValue method.
// …
// … The ValueConverters have several uses:
// …
// * by the sql package, for converting from a driver's Value type
//    to a user's type in a scan.
```

`DefaultParameterConverter` implements `ValueConverter`, but it's not used by scan, that's right. `convertAssign` implements this logic slightly differently (it does not check for `reflect.String`), and that's where the problem lies.

I will create a new issue.

**Comment by kardianos** [comment]
Please add the following code to your test:
```
func (s *String) Scan(v interface{}) error {
	switch t := v.(type) {
	default:
		return fmt.Errorf("Unsupported type %[1]T %[1]v", v)
	case []byte:
		*s = String(string(t))
	case string:
		*s = String(t)
	}
	return nil
}
```

**Comment by AlekSi** [comment]
That works, unsurprisingly. But custom `Scan()` method is not required for `Int32` and `Int64`. [Here](https://github.com/golang/go/blob/master/src/database/sql/convert.go#L254) `reflect.Int32` and `reflect.Int64` are checked, but `reflect.String` (and also slice of bytes) is not.

**Comment by kardianos** [comment]
Filed https://github.com/golang/go/issues/18101
