### ISSUE TITLE
testing: TestTRun: panic: test timed out after 3m0s

### ISSUE THREAD

**Issue by mikioh** [golang/go#15170]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

git rev-parse HEAD
438ce713a1c8e4d24aea547b6fcf907b5dbf0bec

2. What operating system and processor architecture are you using (`go env`)?

linux-386 at a9434e7adad58b3099817b676aa81d20fc2af87e

:: Running /tmp/workdir/go/src/make.bash with args ["/tmp/workdir/go/src/make.bash"] and env ["CONSOLE=/dev/console" "HOME=/" "init=/sbin/init" "runlevel=2" "INIT_VERSION=sysvinit-2.88" "TERM=linux" "COLUMNS=80" "BOOT_IMAGE=/boot/vmlinuz-3.16-0.bpo.3-amd64" "PATH=/sbin:/usr/sbin:/bin:/usr/bin" "RUNLEVEL=2" "PREVLEVEL=N" "SHELL=/bin/sh" "PWD=/" "previous=N" "LINES=24" "rootmnt=/root" "GOROOT_BOOTSTRAP=/go1.4" "WORKDIR=/tmp/workdir" "GO_BUILDER_NAME=linux-386" "GOARCH=386" "GOHOSTARCH=386" "GOBIN="] in dir /tmp/workdir/go/src

3. What did you do?

Ran TyrBotts

4. What did you expect to see?

TryBots are happy

5. What did you see instead?

https://storage.googleapis.com/go-build-log/a9434e7a/linux-386_2dc97521.log

**Comment by mikioh** [comment]
Looks like it happened on the following buildbots:
- http://build.golang.org/log/aa29d6c2258ddfe7757829f9b9b62f955cae8f4c (linux/386-387)
- http://build.golang.org/log/38cdf7997d077de09e4552c952f2d7f09b6863ce (linux/386-clang)
- http://build.golang.org/log/dacf549399d2245dc92decd46456dce51ce1da33 (linux/amd64-sid)
- http://build.golang.org/log/b4126483f74b6cec53e15553df8a3fbc4463d751 (linux/amd64-clang)
- http://build.golang.org/log/8a4608695dd0a4370c91ff26602da9734fd2f5df (linux/amd64-noopt)

**Comment by bradfitz** [comment]
Many more.

https://storage.googleapis.com/go-build-log/e13c40ef/linux-amd64_0ed1f78d.log

Paging Dr. @aclements for stats.

@mpvl, can you take a look?

**Comment by mpvl** [comment]
will do

On Wed, Apr 13, 2016 at 11:42 PM, Brad Fitzpatrick <notifications@github.com
