### ISSUE TITLE
cmd/vet: go vet not supporting vendoring

### ISSUE THREAD

**Issue by gaillard** [golang/go#15182]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

1.6
1. What operating system and processor architecture are you using (`go env`)?

linux amd64
1. What did you do?

vendor a package into another. run 'go tool vet -v thepkg/thefile.go'
1. What did you expect to see?

Any vet reports.
1. What did you see instead?

Missing reports when compared to having the vendored lib in the gopath like normal. Also see in the output, something like:

vet: ./internal/httpserver/httpserver.go:13:2: could not import github.com/rs/cors (can't find import: COMPANYSPECIFIC/vendor/github.com/rs/cors)

which is not the case if the dependency is in the gopath.

Another user with the same thing on the mailing list and me whining in the thread :)
https://groups.google.com/forum/#!searchin/golang-nuts/vet$20vendor/golang-nuts/uTcfZ15Ks0U/XBOXyfVPAQAJ

Thanks!

**Comment by bradfitz** [comment]
I think this might only work at the package level, not files.

/cc @robpike @dsymonds

**Comment by gaillard** [comment]
using without going through tool swallows errors, so is there a way to find out? It seems consistent that the error given from going through tool is what is causing the missing vet reports when not going through tool.

**Comment by robpike** [comment]
Given just the file, it can't do the imports necessary to do the full job, and lacking the imports will lack the vendored imports.  Try go tool vet -v thepkg. If that doesn't work, call in a vendoring expert.
