### ISSUE TITLE
Byte Package Read method, unexpected result

### ISSUE THREAD

**Issue by NerdsvilleCEO** [golang/go#15187]
Hello all,
I have noticed an issue with how the byte Read method works, please advise

0. Relevant line in source repository
https://github.com/golang/go/blob/master/src/bytes/reader.go#L46

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/JOSHUA/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/4AnOGXPIgG

4. What did you expect to see?
Value at memory address associated with non-pointer variable to remain unmodified.

5. What did you see instead?
Value at memory address associated with non-pointer variable modified.

**Comment by bradfitz** [comment]
The play snippet's output looks correct. See the definition of the io.Reader interface.

For questions learning the language and standard library, see https://github.com/golang/go/wiki/Questions

**Comment by NerdsvilleCEO** [comment]
Hi,
  I am aware that according to the definition, the output is correct, but I am suggesting it would be better to accept a pointer in the Read interface for predictable results :)
