### ISSUE TITLE
cmd/vet: tab symbol silently breaks go tags

### ISSUE THREAD

**Issue by aka-rider** [golang/go#15193]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
All platforms

3. What did you do?
Suppose we have a struct with a tags.
``` 
    type Foo struct {
        Bar string    `db:"bar" json:"bar"`
    }
```
If there is a TAB symbol before the json, it makes the json tag unreadable (we get ^Ijson instead).

4. What did you expect to see?
 
 - It would be nice to have a warning during go vet run or
 - It might be automatically corrected by the go fmt or
 - go can treat TAB in tags as a whitespace

5. What did you see instead?
json tag is silently ignored

**Comment by bradfitz** [comment]
https://golang.org/pkg/reflect/#StructTag is pretty clear that only space (U+0020 ' ') is valid whitespace, so this is probably a job for `cmd/vet`.

**Comment by sergeylanzman** [comment]
It already alerts on  tab tags
```
type Foo struct {
	Bar string `db:"bar"	json:"bar"`
}
```
```
go vet
main.go:9: struct field tag `db:"bar"	json:"bar"` not compatible with reflect.StructTag.Get: bad syntax for struct tag key
exit status 1
```
```
go version
go version devel +c3b3e7b Fri Apr 8 21:06:39 2016 +0000 darwin/amd64
```

**Comment by bradfitz** [comment]
Okay, so nothing to do here, then.
