### ISSUE TITLE
reassigned values don't need to be used

### ISSUE THREAD

**Issue by huoy** [golang/go#15197]
Shouldn't err need to be used again in this code? It applies to all variables but it seems especially troublesome for error handling.

```go
package main

import "errors"

func main() {
	err := errors.New("error!")

	if err != nil {}
	
	err = nil
}
```

**Comment by bradfitz** [comment]
Let's move this to https://golang.org/wiki/Questions. The language won't be changing in this regard in any case, so no point using a bug tracker.

**Comment by huoy** [comment]
Hey no problem. It is not actually a question though. I have a pretty firm grasp of the semantics at work here. Why do you say that the language won't be changing in this regard?

**Comment by bradfitz** [comment]
> Why do you say that the language won't be changing in this regard?

Just because the language is frozen and because of https://golang.org/doc/go1compat.

The time to change the language was 2011. It's a bit late now, and we have to keep old programs working. Your program above compiles.

Or are you proposing that this be a new `cmd/vet` warning?

**Comment by huoy** [comment]
Proposing that would make more sense I guess. The reason I put this here at all is because it seems  like an oversight in the compiler. In go you're encouraged to check all errors. And reassigning errors is super common.

I'm just being naive I guess since I'm sure it's been brought up once or twice in the time go has been around :)
