### ISSUE TITLE
tour: compiler server seems to need time synchronization

### ISSUE THREAD

**Issue by rickysarraf** [golang/go#15207]
Context: http://tour.golang.org/flowcontrol/10

Change the title above to describe your issue and add your feedback here, including code if necessary
![screenshot from 2016-04-09 16-14-53](https://cloud.githubusercontent.com/assets/65480/14403266/5a84df60-fe6e-11e5-96b8-a4b0d59ad437.png)

**Comment by nuss-justin** [comment]
The time on the playground/tour is frozen. It never changes.
