### ISSUE TITLE
crypto/tls: Expose signature_algorithms in ClientHelloInfo

### ISSUE THREAD

**Issue by titanous** [golang/go#15200]
The [`signature_algorithms`](https://tools.ietf.org/html/rfc5246#section-7.4.1.4.1) extension is provided in the TLS 1.2 ClientHello and could be used with the existing `GetCertificate` hook to choose between certificate chains with RSA and ECDSA signatures if exposed in `ClientHelloInfo`.

/cc @agl

**Comment by agl** [comment]
You don't need to look at `signature_algorithms` because `ClientHelloInfo` already includes the offered cipher suites, curves and point formats.

**Comment by agl** [comment]
(To elaborate, TLS cipher suites specify the certificate format too. So an …`_ECDSA_`… cipher suite has to use an ECDSA certificate. The `crypto/tls` code is smart enough not to try and select an RSA cipher suite if you hand it an ECDSA certificate.)

**Comment by titanous** [comment]
Makes sense, thanks!
