### ISSUE TITLE
x/mobile: gomobile init fails when checking sha256 for NDK (linux)

### ISSUE THREAD

**Issue by uaalto** [golang/go#15202]
1. What version of Go are you using (`go version`)?

```
go version go1.6 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alvatar/code/lantern"
GORACE=""
GOROOT="/home/alvatar/code/go1.6.0"
GOTOOLDIR="/home/alvatar/code/go1.6.0/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?

```
go install golang.org/x/mobile/cmd/gomobile
gomobile init 
```

4. What did you expect to see?

Correct `gomobile init` run

5. What did you see instead?

```
bin/gomobile: sha256 for "gomobile-ndk-r10e-linux-x86_64.tar.gz": bacfed664a7b69b1b693f246ea49a85f04f502bd1ae723351c5345ab5b2ba850, want 709d96f5234c224e4b72254fd2e196d0e1486b8d943e972ed98cf14e3ca7bdde
```

**Comment by clsung** [comment]
Maybe the gomobile repo should be upgraded, sha256 "709d96f5234c224e4b72254fd2e196d0e1486b8d943e972ed98cf14e3ca7bdde" is previous one.

See https://github.com/golang/mobile/commit/74ee969d3ffc95befa9a96a6590c36d71b6afd52#diff-5eee0baa37843d6875734b7ec91206a7

**Comment by hyangah** [comment]
Yes, please update the gomobile repo.
I hope that we can handle release better after the next ndk upgrade.

**Comment by myleshorton** [comment]
I'm experiencing the same issue @uaalto =).

**Comment by uaalto** [comment]
Updating to Go 1.6.1 sha's change, but it is still incorrect:

gomobile: sha256 for "gomobile-ndk-r10e-darwin-x86_64.tar.gz": e8bff8a56f5688ec849a95a4e85130ce02eff5c2d54e361103777c396db8d308, want 9185a734b1b3d8dd29f3bc3c55cf03e397414e656345b7ed835879ee8eb76ebb

**Comment by hyangah** [comment]
@uaalto Please update the gomobile repo.

**Comment by uaalto** [comment]
Thanks @hyangah . I'm actually installing it from scratch every time I try, so I'm confident that I have the latest version and that there are no leftovers.

**Comment by hyangah** [comment]
@uaalto the error message is from https://go.googlesource.com/mobile/+/master/cmd/gomobile/init.go#569 and it seems your gomobile command was built with version prior to https://github.com/golang/mobile/commit/74ee969d3ffc95befa9a96a6590c36d71b6afd52#diff-5eee0baa37843d6875734b7ec91206a7

What does 'gomobile version' command say?

**Comment by uaalto** [comment]
It works now. We are using Docker with an external directory, so it was probably some stale data. I'll close it because it probably isn't Gomobile's issue.

**Comment by uaalto** [comment]
Ps: thank you for your comments and help!
