### ISSUE TITLE
Import cycle not allowed for a trivial source

### ISSUE THREAD

**Issue by ynabid** [golang/go#15218]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yassine/Dev/godev"
GORACE=""
GOROOT="/home/yassine/Dev/go"
GOTOOLDIR="/home/yassine/Dev/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
compiling this code :

package main

import "fmt"

func main() {
        fmt.Printf("hello, world\n")
}

4. What did you expect to see?
Binary code

5. What did you see instead?
this error : 
import cycle not allowed
package github.com/golang/example/hello
	imports fmt
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime

NB : whene I install the version 1.5.3 its work fine

**Comment by bradfitz** [comment]
I think something is messed up in your Go installation or environment and you have a mix of Go versions installed atop each other. I suggest you bring this to the forum for help. See https://golang.org/wiki/Questions

**Comment by minux** [comment]
You're probably using a Go command from an older version
of Go with Go 1.6.
