### ISSUE TITLE
context: decide on naming convention for context key variables

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15229]
Before Go 1.7, let's be sure we're happy with the naming convention for context key values.

/cc @adg @Sajmani @dsymonds

**Comment by dsymonds** [comment]
Naming convention? Context keys are based on types.

**Comment by bradfitz** [comment]
The naming convention for well-known context key values we use. See https://go-review.googlesource.com/#/c/21829 as an example.

**Comment by dsymonds** [comment]
I see.

I'll suggest using "<name describing value>Key".

**Comment by dsymonds** [comment]
Though we've often found it nicer to expose `WithFoo` and `Foo` functions that wrap `context.WithValue` and `ctx.Value` calls instead of exposing the context key directly.

**Comment by adg** [comment]
Are you talking about `ContextKeyServer`?

I'd prefer `ServerContextKey`.

**Comment by rsc** [comment]
@adg, @sajmani, @bradfitz, are you happy now?

**Comment by adg** [comment]
Brad seems to have gone with `FooContextKey` which is a-ok with me.

**Comment by Sajmani** [comment]
For exported context keys, FooKey or FooContextKey seem fine to me.  But my personal preference is to encapsulate the key and provide foo.NewContext(ctx, val)/foo.FromContext(ctx) or pkg.ContextWithFoo(ctx, val)/pkg.FooFromContext(ctx).
