### ISSUE TITLE
Proposal: Add more styling options with curly brackets

### ISSUE THREAD

**Issue by AG-Systems** [golang/go#15220]
Hello, is it possible to have another style option with curley brackets:

```
import "fmt"

func main() 
{
	fmt.Println("Hello")
}
```

Is there anyway to have this type of styling in GO?

Not just 

```
import "fmt"

func main() {
	fmt.Println("Hello")
}
```

**Comment by minux** [comment]
No, it's not possible in Go to not place the opening
brace on the same line as the other parts of the line.

This has been discussed at length on the mailing
list. Please search the golang-nuts mailing list archive.

Closing. We're not going to change the language now,
especially for such cosmetic grammatical changes.

**Comment by AG-Systems** [comment]
Thank you for your time and your comment.
