### ISSUE TITLE
undefined: system.Setgid

### ISSUE THREAD

**Issue by vanloswang** [golang/go#15248]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/mips64le

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="mips64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_mips64le"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
When I compile libcontainer on fedora 21 mips64el, it report undefined: system.Setgid. The full infomation is as bellow:

# rpmbuild -bb golang-github-docker-libcontainer.spec 
execute (%prep): /bin/sh -e /var/tmp/rpm-tmp.wqHull
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/libcontainer-c964368.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
execute (%build): /bin/sh -e /var/tmp/rpm-tmp.UHQwdG
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f ./_build/src/github.com/docker/libcontainer
+ mkdir bin
++ pwd
+ export GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ gobuild -o bin/nsinit github.com/docker/libcontainer/nsinit
+ go build -o bin/nsinit github.com/docker/libcontainer/nsinit
# github.com/docker/libcontainer
_build/src/github.com/docker/libcontainer/init_linux.go:183: undefined: system.Setgid
_build/src/github.com/docker/libcontainer/init_linux.go:186: undefined: system.Setuid

4. What did you expect to see?
no undefined symbol.

5. What did you see instead?

is there some way to be fixed this problem?

**Comment by vanloswang** [comment]
After search the golang source code, I found out that there is no implementation for 
cd src/syscall
grep 'func Setgid' -r .
./zsyscall_netbsd_arm.go:func Setgid(gid int) (err error) {
./zsyscall_netbsd_amd64.go:func Setgid(gid int) (err error) {
./zsyscall_solaris_amd64.go:func Setgid(gid int) (err error) {
./zsyscall_openbsd_386.go:func Setgid(gid int) (err error) {
./zsyscall_freebsd_386.go:func Setgid(gid int) (err error) {
./zsyscall_darwin_amd64.go:func Setgid(gid int) (err error) {
./zsyscall_freebsd_arm.go:func Setgid(gid int) (err error) {
./zsyscall_darwin_arm.go:func Setgid(gid int) (err error) {
./zsyscall_freebsd_amd64.go:func Setgid(gid int) (err error) {
./syscall_linux.go:func Setgid(gid int) (err error) {
./zsyscall_darwin_386.go:func Setgid(gid int) (err error) {
./zsyscall_darwin_arm64.go:func Setgid(gid int) (err error) {
./zsyscall_dragonfly_amd64.go:func Setgid(gid int) (err error) {
./zsyscall_openbsd_arm.go:func Setgid(gid int) (err error) {
./zsyscall_openbsd_amd64.go:func Setgid(gid int) (err error) {
./zsyscall_netbsd_386.go:func Setgid(gid int) (err error) {

and in syscall_linux.go, then implementation  of Setgid is empty and a commit for explain for this:
// issue 1435.
// On linux Setuid and Setgid only affects the current thread, not the process.
// This does not match what most callers expect so we must return an error
// here rather than letting the caller think that the call succeeded.

func Setuid(uid int) (err error) {
    return EOPNOTSUPP
}

func Setgid(gid int) (err error) {
    return EOPNOTSUPP
}

Then how to resolve it ? Just commit the call code in init_linux.go???

**Comment by ianlancetaylor** [comment]
This is not a problem with the Go distribution.  The undefined `system.Setgid` is supposed to be defined in the package `github.com/docker/libcontainer/system`.  There is no `system` package in the Go distribution.

Closing, because there is nothing we can do to fix this.
