### ISSUE TITLE
cmd/compile: use cheaper runtime.writeBarrier check

### ISSUE THREAD

**Issue by josharian** [golang/go#15245]
The pre-SSA backend checked the value of runtime.writeBarrier with:

```
CMPB    runtime.writeBarrier(SB), $0
JNE $0, 167
```

The SSA backend uses:

```
MOVL    runtime.writeBarrier(SB), AX
TESTB   AL, AL
JNE $0, 168
```

The old version is one instruction and one byte shorter and does not use a register.

I tried and failed to use the old check in CL 21817. Generating flags directly from memory does not play nicely with how we currently handle flags; see Keith's comments.

This issue is so that we don't forget, and to discuss alternative approaches.

**Comment by randall77** [comment]
Possibly add a new SSA block, WBEnabled, which acts like an If block but takes a memory instead of a flag as its input.  It can generate the CMPB $0, runtime.writeBarrier(SB) instruction implicitly (as part of genBlock).

**Comment by josharian** [comment]
Thanks. Once @aclements has indicated what direction he'd like to take on #14921, I'll give that a try.
