### ISSUE TITLE
Unexpected or incorrect initialization loop error

### ISSUE THREAD

**Issue by mitchellh** [golang/go#15243]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mitchellh/code/go"
GORACE=""
GOROOT="/Users/mitchellh/code/3rdparty/go"
GOTOOLDIR="/Users/mitchellh/code/3rdparty/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

I've reproduced it in a minimal case: http://play.golang.org/p/ERjFhItIfV

That produces an "initialization loop" error. Note that this is a minimal case. You can imagine this [also erroring] case where it wouldn't in fact be a runtime infinite loop: http://play.golang.org/p/fVZWOf6Obw And yet it still gives us an init loop error.

However, if I do this, it compiles fine: http://play.golang.org/p/KZkAZXyqm- 

4. What did you expect to see?

I expected both cases to compile fine.

5. What did you see instead?

I saw an "initialization loop" error for one case when they're both seemingly equivalent.

**Comment by cespare** [comment]
This is described in the spec at https://golang.org/ref/spec#Package_initialization:

> If any variables are still uninitialized when this process ends, those variables are part of one or more initialization cycles, and the program is not valid.

So I guess you're asking for a language relaxation?

**Comment by mitchellh** [comment]
Ah, no, if its in the spec then I yield. I didn't check prior. 

As a user, even an experienced one, it felt unintuitive. Feel free to close if you agree. Sorry for the trouble.

**Comment by ianlancetaylor** [comment]
The spec for initialization is written to be simple so that all compilers agree on what is and what is not an initialization loop.  It doesn't try to be clever about things like a reference that is only from a function.

Closing.
