### ISSUE TITLE
Concurrent request handling?

### ISSUE THREAD

**Issue by caarlos0** [golang/go#15241]
### 1. What version of Go are you using (`go version`)?

```
go version go1.6 darwin/amd64
```

### 2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/carlos/Code/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### 3. What did you do?

```go
package main

import (
	"net/http"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/status", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("OK"))
	})
	http.ListenAndServe(":3000", mux)
}
```

I opened 2 terminal instances and execute the following command:

```console
for i in `seq 1 1000`; do
  curl  localhost:3000/status
done
```

Some requests eventually take a lot of time to process. I see that it happens sometimes in production (a request take more time than it should), and I was able to easily reproduce this with this recipe.

When I was testing this, I was trying labstack/echo, so I first [opened an issue there](https://github.com/labstack/echo/issues/465), but the behavior is the same with the example provided here.

To help the understanding, here is a [video showing what happens](https://www.dropbox.com/s/smcdgltv06yd06i/echo-slow.mov?dl=0).

Maybe I'm just doing something wrong, if so, I'm sorry for wasting your time :(

### 4. What did you expect to see?

I expect the requests to be handled faster.

### 5. What did you see instead?

Some requests take a lot of time, like 1s or more.

**Comment by bradfitz** [comment]
Let's move this to a forum. See https://golang.org/wiki/Questions. If and when a concrete bug is identified with a repro, we can move it back to the bug tracker.

**Comment by caarlos0** [comment]
@bradfitz OK, sorry. Opened https://forum.golangbridge.org/t/concurrent-request-handling/2370
