### ISSUE TITLE
json.RawMessage does not work within a Map.

### ISSUE THREAD

**Issue by edpingoogle** [golang/go#15240]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

$ go version
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/edpin/projects"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -gno-record-gcc-switches -fdebug-prefix-map=/tmp/go-build159147170=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

Used json.RawMessage with a map.

https://play.golang.org/p/6kG_iLxslP

4. What did you expect to see?

(See "expected" in third test from top.)

{"first":{"S":{"A":10,"B":"Hello"},"C":32}}

5. What did you see instead?

Encoding of the json.RawMessage as bytes instead of the untouched raw message.

 {"first":{"S":"eyJBIjoxMCwiQiI6IkhlbGxvIn0=","C":32}}

**Comment by cespare** [comment]
Dup of #14493, I'd say.

**Comment by robpike** [comment]
Dup of #14493
