### ISSUE TITLE
net/http make response.Write consistent with http.ReadResponse

### ISSUE THREAD

**Issue by shanemhansen** [golang/go#15244]
1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
3. What did you do?

Unit test that passed under go1.5 failed under go1.6
https://play.golang.org/p/Ny_UOGmHhM

net/http.Response.Write() will write something that can't be consumed by http.ReadResponse if StatusCode < 100

4. What did you expect to see?

I expect one of:
* resp.Write() returns error indicating 11 is a bad status code
* resp.Write() writes a ReadResponse-compatible 3 digit status code "011"
* http.ReadResponse() parses value without errors

5. What did you see instead?

```
malformed HTTP status code "11"
```

Clearly the response being serialized is invalid (status code 11). I think we can just be consistent about not writing invalid responses OR being able to read the responses we write.

**Comment by bradfitz** [comment]
"Fixed" already in 3bbede0c512ca645fa19522480c0200ee4711bf3

**Comment by shanemhansen** [comment]
Thanks @bradfitz . My github issue search skills failed me.
