### ISSUE TITLE
x/build: plan9 is holding up trybots again

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15251]
plan9 has recently become slow again, holding up the trybots. (That is, 14 of the trybots will finish, but then plan9-386 continues to run for much longer....)

It seems like buildlets time out or otherwise disappear during tests, which causes the coordinator to retry the tests, thinking it was a transient network issue, and then the build system retries the whole build from the beginning in some cases (depending on which of the sharded helper buildlets disappears).

There is some plan9 bug here, but it's also a problem with the coordinator (maybe #13026)

I think I'll demote plan9 to be a regular builder again while I fix this and once we have logs with timings (#12669) showing that plan9 is behaving, then I'll reinstate it.

/cc @0intro @adg

**Comment by adg** [comment]
+1 for temporary demotion

**Comment by bradfitz** [comment]
I'm going to keep this demoted. Closing.
