### ISSUE TITLE
cmd/compile: invalid instruction on nacl amd64p32

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#15252]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
tip

2. What operating system and processor architecture are you using (`go env`)?
nacl amd6432

3. What did you do?
See change: https://go-review.googlesource.com/#/c/21872/

4. What did you expect to see?
To compile:

5. What did you see instead?
cmd/compile/internal/ssa/zcse.go:83: invalid instruction: 01074 (/tmp/workdir/go/src/cmd/compile/internal/ssa/phiopt.go:66)	MOVQL	16(R15)(R8*1), BX

https://storage.googleapis.com/go-build-log/c2282152/nacl-amd64p32_0c3a4e20.log

@randall77

**Comment by randall77** [comment]
Small repro:
```
package main

type T struct {
	i int64
}

func f(v *T) int32 {
	ops := [2]int32{3, 4}
	return ops[v.i]

}
```
