### ISSUE TITLE
cmd/objdump: implement s390x disassembler

### ISSUE THREAD

**Issue by mundaym** [golang/go#15255]
Unplanned at the moment.

**Comment by srinivas-pokala** [comment]
@rsc,  I am working on disassembler support for linux/s390x

**Comment by Vishwanatha-HD** [comment]
The s390x disassembler support CL# is (arch repo):
https://go-review.googlesource.com/c/arch/+/575675

**Comment by srinivas-pokala** [comment]
Disassembler support for s390x  enabled, hence closing the issue.
