### ISSUE TITLE
doc: contribution guidelines page should mention criteria clearly

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#15259]
It would be helpful if the Contribution Guidelines page (https://golang.org/doc/contribute.html#Code_review) clearly documented which guidelines submitted contributions are expected to adhere to.  For example, either in the "Code Review" section of that page, or in the "Make a Change" section, it should probably point readers at:

https://github.com/golang/go/wiki/CodeReviewComments

...and explicitly state that submissions should follow the guidelines there.  Today, it references https://github.com/golang/go/wiki/CodeReview, but only near the very end under "more information", which might lead some to never read those links, or at least not in the context of "required for submission".

Likewise, if submissions are expected to follow all of the guidelines found in "effective go" (https://golang.org/doc/effective_go.html), it should indicate that as well.

It might also be helpful to point to https://github.com/golang/go/wiki/CodeReviewComments#useful-test-failures in the Testing Redux section, reminding contributors of the expected practice.

This will save time during the review process since none of the automated tools included with Go seem to complain about these things (e.g. '_' in variable names is not warned about) and less frustration for everyone involved.

**Comment by cespare** [comment]
@binarycrusader fwiw [golint](https://github.com/golang/lint) will find the var/field names with _ in them. (golint is not part of the Go distribution, however.)

**Comment by binarycrusader** [comment]
@cespare thank you, I had completely forgotten about golint.  I will use that too from now on.

**Comment by rsc** [comment]
FWIW, it's important for these pages not to turn into legal documents. Guidance is good, but a litany of criteria is probably not. /cc @adg

**Comment by adg** [comment]
I'd prefer to move the mention of the CodeReview wiki page higher in contribute.html, and add the resources mentioned here to that wiki page.

**Comment by rasky** [comment]
The wiki page is now mentioned at the top, and some criterias have been listed in a compact form. The wiki can hold the rest.
