### ISSUE TITLE
test: deferfin flaky on Windows? (Go 1.6)

### ISSUE THREAD

**Issue by chanxuehong** [golang/go#15267]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\gopath
set GORACE=
set GOROOT=d:\go
set GOTOOLDIR=d:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

install go1.6.1 from souce

4. What did you expect to see?

succeeded

5. What did you see instead?

first time faild
```
##### ../test
# go run run.go -- deferfin.go
exit status 1
10 out of 10 finalizer are not called
panic: not all finalizers are called

goroutine 1 [running]:
panic(0x46ca40, 0xc082006120)
        D:/go1.6.1/src/runtime/panic.go:464 +0x3f4
main.main()
        D:/go1.6.1/test/deferfin.go:60 +0x1dc
exit status 2

FAIL    deferfin.go     2.495s
2016/04/13 09:47:18 Failed: exit status 1

##### API check
Go version is "go1.6.1", ignoring -next D:\go1.6.1\api\next.txt
2016/04/13 09:47:45 FAILED

D:\go1.6.1\src>
```

second time succeeded
```
ok      cmd/pprof/internal/profile      0.063s
ok      cmd/vet 0.047s

##### GOMAXPROCS=2 runtime -cpu=1,2,4
ok      runtime 69.267s

##### Testing without libgcc.
ok      crypto/x509     2.813s
ok      net     0.094s
ok      os/user 0.063s

##### sync -cpu=10
ok      sync    0.813s

##### ../test/bench/go1
testing: warning: no tests to run
PASS
ok      _/D_/go1.6.1/test/bench/go1     5.938s

##### ../test

##### API check
Go version is "go1.6.1", ignoring -next D:\go1.6.1\api\next.txt

ALL TESTS PASSED


---
Installed Go for windows/amd64 in D:\go1.6.1
Installed commands in D:\go1.6.1\bin
*** You need to add D:\go1.6.1\bin to your PATH.

D:\go1.6.1\src>
```

I'm not sure this is a bug

**Comment by bradfitz** [comment]
@alexbrainman, is deferfin known to be flaky on Windows? Or @aclements, flaky anywhere?

@chanxuehong, can you try with master instead of Go 1.6.x?

**Comment by alexbrainman** [comment]
> is deferfin known to be flaky on Windows?

I have never seen this before. But, given that Windows timer for go1.6 is 15ms, maybe the test is close to the edge:
```
# tail deferfin.go
        for i := 0; i < 3; i++ {
                time.Sleep(10 * time.Millisecond)
                runtime.GC()
        }
        if count != 0 {
                println(count, "out of", N, "finalizer are not called")
                panic("not all finalizers are called")
        }
}
```

Alex

**Comment by chanxuehong** [comment]
@bradfit
i am sorry i have no Windows env yet

**Comment by aclements** [comment]
Slightly flaky on Solaris. We've never seen this fail on Windows on the builders.

I could definitely see this test being flaky though. We *should* kick off the finalizers during that 10ms sleep, but nothing enforces this.

`$ greplogs -md -l -dashboard -E 'not all finalizers are called' -E deferfin`
[2015-11-20T19:55:15-52f111f/solaris-amd64-smartos](https://build.golang.org/log/b80f91d039ea1d2d5d59c35112476575b1ee6994)
[2015-11-24T19:06:11-b790ad5/solaris-amd64-smartos](https://build.golang.org/log/b2dc6f97a70e05306744e78b696b9d505ac15ff3)
[2016-03-02T20:43:48-2faf5bc/solaris-amd64-smartosbuildlet](https://build.golang.org/log/41da3605a5e2bf1b1eb5734efa7dffed6857a604)
[2016-04-08T05:21:10-b8af3fd/solaris-amd64-smartos](https://build.golang.org/log/adb1def898af71aba26f0950e13ce29b560dbf57)

**Comment by aclements** [comment]
That test is clearly a little crufty, too. It has a comment at the top about being disabled on 32-bit because of conservative GC.

**Comment by rsc** [comment]
We just dropped the sleep back down to 1ms for Go 1.7. Maybe that has deflaked this.

**Comment by alexbrainman** [comment]
What Russ said. I think we should close this issue until we see it again.

Alex

**Comment by ianlancetaylor** [comment]
closing.

**Comment by hartzell** [comment]
FWIW, I just tripped over this on a CentOS 7 box.

Was building via [Spack](https://github.com/llnl/spack) on a very slimly configured CentOS 7 system on Digital Ocean (based on their 7 images, with a handful of other packages).

```
mkdir foo
cd foo
git clone https://github.com/llnl/spack .
export PATH=`pwd`/bin:$PATH
spack install go
```

and watch it chug for a while, installing prereqs, including a bootstrap version of 1.4.

Reran the build with verbose turned on to see if I could get more details and it succeeded.  Sadly, that cleaned up the build log from the failing run.

I've been building (via Spack) regularly and only ever seen this this once.
