### ISSUE TITLE
bytes: Reader should use new io.SeekStart, io.SeekCurrent, and io.SeekEnd constants

### ISSUE THREAD

**Issue by EricLagergren** [golang/go#15269]
In https://github.com/golang/go/commit/acefcb732cae4daa59a621cb102793860b564a12 three new constants were added for seeking positions in a stream of bytes.

bytes.Reader, strings.Reader, and io.SectionReader currently do not use these constants and instead use 0, 1, and 2.

Since packages bytes and strings (and by default io) all import io, it'd make sense to use those constants internally for their Readers' `Seek` methods.

IMO it doesn't make sense to import io into any other packages for the sake of using named constants.

It's a rather trivial issue but it would clarify the source code which iirc was one of the reasons for having defined constants.

**Comment by bradfitz** [comment]
Agreed. Will do.

**Comment by EricLagergren** [comment]
@bradfitz it was also mentioned in that CL that the comments should probably be reworded to say *stream* instead of *file*. (I think Rob said it.)

Unsure if that requires its own issue since it's so trivial.

**Comment by bradfitz** [comment]
You can't seek on a stream. Bikeshed that elsewhere.
