### ISSUE TITLE
x/build/cmd/tip: add _tipstatus error monitoring to farmer.golang.org#health

### ISSUE THREAD

**Issue by adg** [golang/go#15266]
A recent change to cmd/go (5b3e576) broke cmd/tip, but we didn't realize it was broken because the active instances just kept serving the last working version. Eventually all four instances were restarted and they all failed to start godoc, being unable to find it. By that stage it was hard to understand what was going on.

It would be better if cmd/tip could somehow report that it has been wedged for a long time. Ideally before it stops serving properly.

An additional, more radical idea is for cmd/tip to—on startup—try earlier versions of go and tools to see if they work. That seems like a lot of fiddly nonsense though.

**Comment by adg** [comment]
cc @bradftiz @broady

**Comment by bradfitz** [comment]
Well, we could add monitoring for tip's /_status and send emails when it's angry.

**Comment by dmitshur** [comment]
We have https://farmer.golang.org/#health now, which is a great place to add a check for this.

However, we'll likely need to resolve #32949 first.
