### ISSUE TITLE
cmd/compile: crash on package name used as value in constant declaration

### ISSUE THREAD

**Issue by EricLagergren** [golang/go#15265]
This is seemingly low-priority. I only ran into this because of a typo but it threw me off for a second.

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

     1.6

2. What operating system and processor architecture are you using (`go env`)?

    GOOS=linux
    GOARCH=amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

    https://play.golang.org/p/M93SytJouJ

4. What did you expect to see?

    An error message telling me that what I did was stupid.
    E.g.: "Cannot concatenate identifier 'fmt'"

5. What did you see instead?

    A cryptic message

**Comment by bradfitz** [comment]
Message is:

```
treecopy [0xc8201a8bd0]
.   PACK l(4) main.fmt
prog.go:8: internal compiler error: treecopy Name
```

**Comment by EricLagergren** [comment]
@bradfitz Ah yes I should've added that to my original comment.

**Comment by davecheney** [comment]
Ok, thus is something we should fix. This isn't a syntax error, that code
crashed the compiler.

**Comment by EricLagergren** [comment]
Additionally, it crashes with ints: https://play.golang.org/p/mztla8DYUz

**Comment by mdempsky** [comment]
@EricLagergren Thanks for the report. Minimal repro:

    package main
    import "fmt"
    const x = fmt

I think the fix is as simple as adding `OPACK` to `case ONAME, OLITERAL, OTYPE:` in treecopy.

**Comment by ALTree** [comment]
Dup of #11361

**Comment by ianlancetaylor** [comment]
Closing as dup.
