### ISSUE TITLE
x/exp/io/i2c: Devfs should not use read() and write() calls

### ISSUE THREAD

**Issue by rakyll** [golang/go#15264]
Only a subset of the I2C and SMBus protocols can be implemented by using read() and write() calls, e.g. full duplex transmission is not supported. Most user-space programs directly depend on the I2C driver functions.

See  `i2c_smbus_read_word_data` and `i2c_smbus_write_word_data` at the kernel driver reference (https://www.kernel.org/doc/Documentation/i2c/dev-interface).

**Comment by rakyll** [comment]
Rather than i2c_smbus_read_word_data and i2c_smbus_write_word_data, we are depending on ioctl functions. These are more flexible about what the data payload could be.

**Comment by ALTree** [comment]
Since `x/exp/io` is no longer developed and essentially frozen, I'm closing this issue.
