### ISSUE TITLE
go/types: ExampleMethodSet errors, but doesn't fail

### ISSUE THREAD

**Issue by jmank88** [golang/go#15261]
1. What version of Go are you using (`go version`)?
Whatever golang.org is using behind the scenes to run examples, as of 2016-4-12 ~5pm CT.

2. What operating system and processor architecture are you using (`go env`)?
Same as 1.

3. What did you do?
Ran the example code here: https://golang.org/pkg/go/types/#example_MethodSet

4. What did you expect to see?
I expected the program to "Print the method sets of Celsius and *Celsius." as documented.

5. What did you see instead?
An error:
> 2009/11/10 23:00:00 celsius.go:3:8: could not import fmt (can't find import: )

The error is returned from this call:
> pkg, err := conf.Check("temperature", fset, []*ast.File{f}, nil)

~~Since this example does not specify its expected output (// Output:), this failure will not be registered via go test.~~ Edit: the source files have // Output:, so it's not clear to me what is happening.

I'm new to go/types, so it's not clear to me whether the example is broken, or packages are broken.

**Comment by jmank88** [comment]
The same problem affects ExampleScope as well.

**Comment by griesemer** [comment]
@jmank88 go/types requires the "fmt" package to be installed. This code runs fine if you copy it and run it locally (with a std library installed), or if you run the godoc server locally (with a std library installed). go/types and the example are correct but the example set up may need tweaks, or perhaps an explanation. Leaving for @alandonovan who added this example.

**Comment by alandonovan** [comment]
As the comment in the example says, the importer loads files from $GOROOT/pkg/$GOOS_$GOOARCH/fmt.a; these files are not present in the Playground's sandbox.

Not all example programs are intended to be executable in the Go Playground, for example, anything that accesses the network.  This is a limitation of the Playground, not a mistake in the example.
