### ISSUE TITLE
json Marshl misbehavior with a type pointing to a slice

### ISSUE THREAD

**Issue by GuyBrand** [golang/go#15273]
using version 1.4 or 1.3 on any operating system  , this code snippet :

package main

import(
	"fmt"
	"encoding/json"
)

type me struct{
	Name	string
	Fee int64
}

type Mes []me

type base struct{
	Id int64	`json:"id"`
	Mes `json:"mes"`
}

func main(){
	b := []base{{Id:1},{Id:2}}
	b[0].Mes = append(b[0].Mes , me{Name : "n1", Fee :63}, me{Name : "n2", Fee :88})
	b[1].Mes = append(b[1].Mes , me{Name : "m1", Fee :63})
	if bt , err := json.Marshal(b);err !=nil{
		fmt.Println(err)
	} else {
		fmt.Println(string(bt))
	}
}

func (m Mes) MarshalJSON() ([]byte, error) {
		return []byte(fmt.Sprint(len(m))), nil
}

expected result :
expected result :
[{"id":1,"mes":2},{"id":2},"mes":1]

actual result :
[2,1]

i.e. not only the Mes slice is without a variable name, but the Marshaller totally ignores the Id element .

**Comment by davecheney** [comment]
Could you please verify this bug occurs with Go 1.6.

**Comment by GuyBrand** [comment]
Just did , reconstructed on 1.6 as well .

------ Original Message ------

**Comment by davecheney** [comment]
If you remove the MarshalJSON method from your `Mes` type, you get the expected behaviour.

**Comment by GuyBrand** [comment]
No , If I remove it I get :
[{"id":1,"mes":[{"Name":"n1","Fee":63},{"Name":"n2","Fee":88}]},{"id":2,"mes":[{"Name":"m1","Fee":63}]}]

while the requested behavior is :
[{"id":1,"mes":2},{"id":2},"mes":1]

that's the reason for using MarshalJSON , to override the default 
Marshaller ....


------ Original Message ------

**Comment by fraenkel** [comment]
The simple fix is to add the type for Mes 
type base struct{
Id int64 `json:"id"`
Mes Mes `json:"mes"`
}

The result is
[{"id":1,"mes":2},{"id":2,"mes":1}]

**Comment by GuyBrand** [comment]
It's a workaround, which could be find, still, that would need some code
refactoring...

**Comment by rogpeppe** [comment]
This is totally expected behaviour. The base type implements MarshalJSON, so its MarshalJSON method is used to marshal it.

**Comment by fraenkel** [comment]
See https://golang.org/ref/spec#Struct_types especially what happens with anonymous fields and what is promoted. If your case as mentioned, the MarshalJSON is promoted and applied to your base struct.

**Comment by GuyBrand** [comment]
Well , I was about to ask : "so what if I implement more than one anonymous member , and the answer "solved" my problem , watch this simple code , I only added a new type "Mes1" :


package main

import(
	"fmt"
	"encoding/json"
)

type me struct{
	Name	string
	Fee int64
}

type Mes []me
type Mes1 []me

type base struct{
	Id int64	`json:"id"`
	Mes `json:"mes"`
	Mes1 `json:"mes1"`
	
}

func main(){
	b := []base{{Id:1},{Id:2}}
	b[0].Mes = append(b[0].Mes , me{Name : "n1", Fee :63}, me{Name : "n2", Fee :88})
	b[1].Mes = append(b[1].Mes , me{Name : "m1", Fee :63})
	if bt , err := json.Marshal(b);err !=nil{
		fmt.Println(err)
	} else {
		fmt.Println(string(bt))
	}
}

func (m Mes) MarshalJSON() ([]byte, error) {
		return []byte(fmt.Sprint(len(m))), nil
}

func (m Mes1) MarshalJSON() ([]byte, error) {
		return []byte(fmt.Sprint(len(m)+5)), nil
} 

now this amazingly returns :


[{"id":1,"mes":2,"mes1":5},{"id":2,"mes":1,"mes1":5}]


which is what I wanted in the beginning with "a little extra" , I was already "ready to leave with a little junk in my json" , but tried this `json:"-"`


type base struct{
	Id int64	`json:"id"`
	Mes `json:"mes"`
	Mes1 `json:"-"`
	
}

and abracadabra :

[{"id":1,"mes":2},{"id":2,"mes":1}]

so , this IS inconsistent , not really anticipate-able and a little awkward .

**Comment by FaisalDirieA** [comment]
This is not a bug. 

You forgot the back-quote.
json:"id" should be  `json:"id"`
json:"mes" should be `json:"mes"`


Here is the code you wrote with the back quote added and returns [2,1]
`package main

import(
"fmt"
"encoding/json"
)

type me struct{
Name string
Fee int64
}

type Mes []me

type base struct{
Id int64 json:"id"
Mes json:"mes"
}

func main(){
b := []base{{Id:1},{Id:2}}
b[0].Mes = append(b[0].Mes , me{Name : "n1", Fee :63}, me{Name : "n2", Fee :88})
b[1].Mes = append(b[1].Mes , me{Name : "m1", Fee :63})
if bt , err := json.Marshal(b);err !=nil{
fmt.Println(err)
} else {
fmt.Println(string(bt))
}
}

func (m Mes) MarshalJSON() ([]byte, error) {
return []byte(fmt.Sprint(len(m))), nil
}`

**Comment by FaisalDirieA** [comment]
This is not a bug. 
Try to wrap the back qoute in json:"id" and json:"mes", and you get the correct response of [2,1]

here is the playground code. https://play.golang.org/p/UdK00l6qgZ

**Comment by rhedile** [comment]
Checking that groups doesn't eat back ticks
type base struct {
Id  int64 `json:"id"`
Mes `json:"mes"`
}

**Comment by GuyBrand** [comment]
Well it does in my case .

My code is right, the GitHub's eliminates the backquotes .

Please notice the new result *IS *different .

**Comment by bradfitz** [comment]
From skimming the replies on the thread here, it sounds like there's no bug.

Let's move this to a forum for now (https://golang.org/wiki/Questions) and come back to the bug tracker when a bug has been identified.

**Comment by GuyBrand** [comment]
does look like a bug to me .
none of answers really addressed the issue I presented .
if you do think this behavior as "as designed", then its your call :)

**Comment by kostya-sh** [comment]
This works according to the spec.

As @rogpeppe mentioned, in your first example MarshalJSON method is promoted to `base` from `Mes` and is used to encode an instance of `base` type.

In your second example (with `Mes1` type) MarshalJSON is not promoted. Relevant parts of Go spec:

> A field or method f of an anonymous field in a struct x is called promoted if x.f is a legal **selector** that denotes that field or method f.

and

> The following rules apply to selectors:
>
> 1. For a value x of type T or \*T where T is not a pointer or interface type, x.f denotes the field or method at the shallowest depth in T where there is such an f. **If there is not exactly one f with shallowest depth, the selector expression is illegal.**

**Comment by GuyBrand** [comment]
So how does that explain that when I set json:"-" I get the required format?

**Comment by kostya-sh** [comment]
Probably better to ask this question on a forum (https://golang.org/wiki/Questions), but here is a short explanation: http://play.golang.org/p/Ka2cqCnYzW

**Comment by GuyBrand** [comment]
This sample IS working according to spec, and therefore, the solution is
simple, you just:
y, _ := b2.M1.MarshalJSON() (or M2).

When I json:"-" I am telling the system to ignore Mes1.
Probably, reflection resolved "how many anonymous public members are there"
first, and then ignores (ad suggested by the "-") the Mes1.

I don't mind this "dirty trick" at all, as long as I know it is according
to spec, and will not be changed in the future, leaving me with a broken
program.

I can still down the json package, and see if that's the case, but that
will not promise me future comparability either.

So a maybe this is not a "bug", but rather :
"A HOLE IN THE SPEC"

AND I don't know if those are entitled to be here, do you?

**Comment by GuyBrand** [comment]
Also note that if I make a minor change in your code :
remark on of the M's and `json:"-"` the other , it will surprisingly still return a value : 
http://play.golang.org/p/QVHWcVwfc0

meaning if M1 has a jsonMarshaller , and I have various structs having it as an anonymous member none of them can "-" it , or in other words "-" does not work :

type dog struct{
   Animal
   BlaBla
   ....
}

type cat struct{
   Animal  `json:"-"`
   BlaBlaX
   ....
}

simply will make no change .

I guess the method selector in this case "skips" the json package parsing for "-", and that may give me some "non official promise" this behavior will be consistent on the next versions
