### ISSUE TITLE
improve interface {} performance advice

### ISSUE THREAD

**Issue by munggruel** [golang/go#15272]
Specify interface size of the memory space occupied,

Reduced dynamic memory application system call,

for example , 
var aa interface {} (n)  : n is Number of bytes
var bb interface{}(nType)  : nType is  occupies the largest type

**Comment by munggruel** [comment]
interface {} performance is too low.

**Comment by munggruel** [comment]
Generally, We know the scope of the need to use the memory,  but do not know the specific size

var cc interface{}(nType1*2 + nType2)

**Comment by munggruel** [comment]
Can specify an estimated maximum memory

**Comment by munggruel** [comment]
Static allocation rather than dynamic allocation

**Comment by mwhudson** [comment]
We don't use the issue tracker for asking questions. Please see https://golang.org/wiki/Questions. Thanks.
