### ISSUE TITLE
Are mutex locks fair?

### ISSUE THREAD

**Issue by Batter2014** [golang/go#15285]
Context: https://tour.golang.org/concurrency/9

If i will add to line 20: time.Sleep(time.Second)
And decrease loop in line 33 from 1000 to let's say 30

I will get response in 30 seconds it means that lock is fair. But is guaranteed? Or it could be unfair?

**Comment by mdempsky** [comment]
Good question, but sorry, we don't use the issue tracker for answering questions. Please see https://github.com/golang/go/wiki/Questions on where to ask instead. Thanks!
