### ISSUE TITLE
tour: [variable name is confusing, make clearer]

### ISSUE THREAD

**Issue by RonDrabkin** [golang/go#15289]
Context: http://www.tour.golang.org/flowcontrol/3

For new people trying to learn Go, using a variable called "sum" is confusing.  
sum looks like an operator.

Suggest changing the name of the variable to say, "total"

(refers to this)

func main() {
	sum := 1
	for sum < 1000 {
		sum += sum
	}
	fmt.Println(sum)

**Comment by ianlancetaylor** [comment]
CC @adg @campoy 

(Not sure I agree with this suggestion.  Go doesn't have text operators, and people need to learn that.)

**Comment by mdempsky** [comment]
@RonDrabkin Can you elaborate on why new Go programmers may think "sum" is an operator? E.g., are there other common programming languages where it's an operator and/or can't be used as a variable name?  How widespread is this expectation?  Off hand, I'm not familiar with any such language.

As @ianlancetaylor points out, Go does not have name-like operators; only name-like keywords.  And `sum` is an idiomatic variable name in Go.

**Comment by RonDrabkin** [comment]
I just realized why I was confused - because I'm new to Go and was most recently using the Excel function SUM.

https://support.office.com/en-us/article/Use-AutoSum-to-sum-numbers-543941e7-e783-44ef-8317-7d1bb85fe706

No worries if this doesn't make sense to change, but I missed it.

**Comment by adg** [comment]
So you learned something! :-)

I think we can leave this as-is.
