### ISSUE TITLE
syscall: backport ppc64/ppc64le epoll_event struct fix to Go 1.6.2?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15288]
@laboger requests we backport the fix to #15135 (44f80f6d4925ae59b519ced3a626170099258904, https://golang.org/cl/21582) for Go 1.6.2.

This bug is to consider that.

It only affects ppc64, and makes Docker run there.

/cc @rsc @adg @ianlancetaylor

**Comment by ianlancetaylor** [comment]
SGTM

**Comment by laboger** [comment]
Just to be clear, above where Brad says it only affects ppc64, I believe he means generically both GOARCH values for POWER, ppc64le and ppc64, not just ppc64 (big endian).

**Comment by rsc** [comment]
OK
