### ISSUE TITLE
cmd/gofmt: Minor spacing difference in cmd/gofmt formatting between 1.5 and 1.6.

### ISSUE THREAD

**Issue by dmitshur** [golang/go#15294]
As a preface, I am completely okay if this issue is marked as "Unfortunate", I don't think it negatively affects me or anyone, and the chances of other people running into it are very low (and if they do, working around it is trivial). But given how unexpected and rare the event is (a difference in cmd/gofmt behavior between point releases of Go), it may be interesting/useful to investigate the root cause and ensure such regressions don't happen in future releases. I'm reporting it for that reason only.

So far, I have not spent any time looking into why the behavior changed (again, because I didn't think it was worth the time, and there are higher priority Go issues for me to get to first).
#### 1. What version of Go are you using (`go version`)?

``` bash
go version go1.6.1 darwin/amd64
```
#### 2. What operating system and processor architecture are you using (`go env`)?

``` bash
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Dmitri/Dropbox/Work/2013/GoLanding:/Users/Dmitri/Dropbox/Work/2013/GoLand"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
#### 3. What did you do?

Take the following .go file and `gofmt` it using `cmd/gofmt` of Go 1.6 (either 1.6 or 1.6.1). I've done it on OS X, but I think it affects all OSes.

``` Go
package main

import (
    "fmt"
    "runtime"

    // Some comment.
)

func main() {
    fmt.Println(runtime.Version())
}
```

(https://play.golang.org/p/iYq3-js1Em)
#### 4. What did you expect to see?

According to Go 1.5 (specifically tested version right now is 1.5.3), there would be no difference, that file is considered "gofmt"ed as is.

``` bash
$ ~/Downloads/go1.5.3/bin/gofmt -d fmt.go
$ 
```
#### 5. What did you see instead?

The `gofmt` of Go 1.6 removes the blank line between the import spec and the line with comment.

``` bash
$ gofmt -d fmt.go 
diff fmt.go gofmt/fmt.go
--- /var/folders/tw/kgz4v2kn4n7d7ryg5k_z3dk40000gn/T/gofmt204683414 2016-04-13 23:54:20.000000000 -0700
+++ /var/folders/tw/kgz4v2kn4n7d7ryg5k_z3dk40000gn/T/gofmt140905213 2016-04-13 23:54:20.000000000 -0700
@@ -3,7 +3,6 @@
 import (
    "fmt"
    "runtime"
-
    // Some comment.
 )

$ 
```

Resulting in:

``` Go
package main

import (
    "fmt"
    "runtime"
    // Some comment.
)

func main() {
    fmt.Println(runtime.Version())
}
```

Workarounds are to accept the new gofmt behavior and not have the blank line, or simply remove that comment. I ran into this by accident (/cc @neelance), the comment was going to be removed soon thereafter anyway.

**Comment by 0xmohit** [comment]
Seems to be a side-effect of https://go-review.googlesource.com/#/c/17440/

**Comment by bradfitz** [comment]
Over to @griesemer to triage.

**Comment by griesemer** [comment]
@0xmohit Thanks for investigating this. I probably won't try to address this at the moment - there's more important work to be finished for 1.7. That said, down the road I am hoping to allocate some time to address this and many other open gofmt issues.

**Comment by lzl124631x** [comment]
Facing the same issue.

My gofmt on localbox format the code in this way
```
		log.StdoutHandler,                                     // Log to terminal
		log.Must.FileHandler(logFileName, log.LogfmtFormat()), // Log to file
```
But the gofmt in Travis gave me this result
```
-		log.StdoutHandler,                                     // Log to terminal
+		log.StdoutHandler, // Log to terminal
 		log.Must.FileHandler(logFileName, log.LogfmtFormat()), // Log to file
```

**Comment by agnivade** [comment]
@lzl124631x - Your issue is slightly different I believe. It was already raised and marked as unfortunate. See https://github.com/golang/go/issues/25161.

**Comment by lzl124631x** [comment]
@agnivade Thanks. Interesting. Unfortunate 🤣

**Comment by seankhliao** [comment]
Seems reasonable to close now that the behaviour has been standard for ~7 years
