### ISSUE TITLE
net: TestDialAddrError failure on Windows XP

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#15291]
1. What version of Go are you using (`go version`)?

go version devel +ae98045 Thu Apr 14 00:41:29 2016 +0000 windows/386

2. What operating system and processor architecture are you using (`go env`)?

I use Windows XP.

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\dev
set GORACE=
set GOROOT=c:\dev\go
set GOTOOLDIR=c:\dev\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\DOCUME~1\brainman\LOCALS~1\Temp\go-build795879670=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?

I run `go test -short net` command.

4. What did you expect to see?

I expected no failing tests.

5. What did you see instead?

C:\>go test -short net
--- FAIL: TestDialAddrError (0.00s)
        error_test.go:245: tcp6 ""/0123456789abcdef:0: should be AddrError: dial tcp6 0123456789abcdef:0: socket: An address incompatible with the requested protocol was used.
FAIL
FAIL    net     23.328s

Alex

**Comment by mikioh** [comment]
Does the node under test support IPv6?

**Comment by alexbrainman** [comment]
> Does the node under test support IPv6?

How can I tell?

Alex

**Comment by mikioh** [comment]
> How can I tell?

What's the value of supportsIPv6 in net package on the node?

**Comment by alexbrainman** [comment]
> What's the value of supportsIPv6 in net package on the node?

supportsIPv6 variable is false.

Alex

**Comment by mikioh** [comment]
J'ai compris.
