### ISSUE TITLE
Go + Windows != DLL

### ISSUE THREAD

**Issue by akamajoris** [golang/go#15301]
1. go version
go1.6 windows/386
2. Windows 7x64

3. What did you do?
I want compile go pseudocode to dll...
```
go build --buildmode=dll
buildmode=dll not supported
```
Ok.
```
go build --buildmode=shared
-buildmode=shared not supported on windows/386
```
Ok
```
go build --buildmode=c-shared
-buildmode=c-shared not supported on windows/386
```
Wtf?

4. What did you expect to see?
Dynamic link library

5. What did you see instead?
I see error :(

**Comment by mattn** [comment]
dup #11058
