### ISSUE TITLE
cmd/compile: make deadcode pass cheaper and do it after cse

### ISSUE THREAD

**Issue by josharian** [golang/go#15306]
[moved from discussion in CL 21981]

CSE can remove many values, so it'd be good to do a deadcode pass promptly after it, to speed up other passes. We used to, but it has slowly drifted away. However, deadcode allocates some potentially large slices: two work lists (small) and two bool slices (larger). We should make at least those bool slices reusable in f.Config and then add a deadcode after CSE.

cc @tzneal 

Btw, @bradfitz, do you think it's worth having a label for compiler performance/speed (as opposed to compiled code performance)?

**Comment by bradfitz** [comment]
We used to have too many labels, so we're trying to make do with fewer these days. But build speed is a focus, so, sure. We can always delete it if unused.

**Comment by stemar94** [comment]
I uploaded a CL, but I need some assistance in order to properly benchmark the change.

**Comment by josharian** [comment]
Please benchmark with godoc.org/rsc.io/compilebench and compare results with https://godoc.org/rsc.io/benchstat.

**Comment by thanm** [comment]
Seems unlikely to land in Go1.11, updated milestone accordingly.
