### ISSUE TITLE
cmd/compile: silly amounts of code generated for simple struct equality tests

### ISSUE THREAD

**Issue by josharian** [golang/go#15303]
[partial move from #15164]

```go
package x

type T struct {
	a, b int8
}

func g(a T) bool {
	return a == T{1, 2}
}
```

With ssa, this generates the following code:

```
"".g t=1 size=80 args=0x10 locals=0x8
	0x0000 00000 (swtopt.go:23)	TEXT	"".g(SB), $8-16
	0x0000 00000 (swtopt.go:23)	SUBQ	$8, SP
	0x0004 00004 (swtopt.go:23)	FUNCDATA	$0, gclocals·23e8278e2b69a3a75fa59b23c49ed6ad(SB)
	0x0004 00004 (swtopt.go:23)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0004 00004 (swtopt.go:24)	MOVBLZX	"".a+16(FP), AX
	0x0009 00009 (swtopt.go:24)	MOVB	AL, "".autotmp_16+6(SP)
	0x000d 00013 (swtopt.go:24)	MOVBLZX	"".a+17(FP), AX
	0x0012 00018 (swtopt.go:24)	MOVB	AL, "".autotmp_16+7(SP)
	0x0016 00022 (swtopt.go:24)	MOVB	$0, "".autotmp_17+4(SP)
	0x001b 00027 (swtopt.go:24)	MOVB	$1, "".autotmp_17+4(SP)
	0x0020 00032 (swtopt.go:24)	MOVB	$2, "".autotmp_17+5(SP)
	0x0025 00037 (swtopt.go:24)	MOVBLZX	"".autotmp_16+6(SP), AX
	0x002a 00042 (swtopt.go:24)	MOVBLZX	"".autotmp_17+4(SP), CX
	0x002f 00047 (swtopt.go:24)	CMPB	AL, CL
	0x0031 00049 (swtopt.go:24)	JNE	70
	0x0033 00051 (swtopt.go:24)	MOVBLZX	"".autotmp_16+7(SP), AX
	0x0038 00056 (swtopt.go:24)	CMPB	AL, $2
	0x003a 00058 (swtopt.go:24)	SETEQ	AL
	0x003d 00061 (swtopt.go:24)	MOVB	AL, "".~r1+24(FP)
	0x0041 00065 (swtopt.go:24)	ADDQ	$8, SP
	0x0045 00069 (swtopt.go:24)	RET
	0x0046 00070 (swtopt.go:24)	MOVB	$0, AL
	0x0048 00072 (swtopt.go:24)	JMP	61
```

This is better than the old backend, but still way too much. Some of the fat is due to #15300, but there's still an unnecessary zero at 0x0016 and unnecessary spills.

The unnecessary zero is introduced during the decompose user phase.

The unnecessary spills are probably due to how the front end does small struct equality, but I haven't double-checked.

cc @mdempsky @brtzsnr @randall77

**Comment by josharian** [comment]
CL 22277 mostly addresses this, but it doesn't explain or fix the unnecessary zeroing introduced during the decompose phase, which I suspect could still happen via another code path. For example, it also used to happen when appending arrays/structs prior to CL 22248. Maybe @brtzsnr would be interested in looking into that?

**Comment by josharian** [comment]
CL 22277 is on hold until SSA is the default everywhere. In the meantime, hopefully @brtzsnr will succeed in making SSA do a better job with what we've got.

**Comment by brtzsnr** [comment]
Not sure I can do anything simple here. I looked into a == T{1, 2} example and the tradeoff seems to be between 1 cmp + 1 jmp + 1/2 cmp and 2 cmp + 1 and8. If the cmp (ints) is cheap we can do the latter. Otherwise (for strings) the former is faster.

Maybe one improvement is to order the comparisons of fields by cost. First ints, then string/slice length, then small arrays, etc.

**Comment by josharian** [comment]
Thanks for checking into it, @brtzsnr, much appreciated.

**Comment by randall77** [comment]
This seems fixed.  If there are any outstanding remnants (unnecessary zeroing?) you can open a different issue.
