### ISSUE TITLE
cmd/compile: no tail call optimisation

### ISSUE THREAD

**Issue by hydroflame** [golang/go#15304]
http://play.golang.org/p/CPSqcLkE5K

This wouldn't crash if gc had tail call optimisation.

**Comment by bradfitz** [comment]
Correct. Go does not do tail call optimization. It has been discussed in the past. It would hide stack frames useful in debugging. One early proposal was to make it explicit and make users call tail called functions with a keyword like "become". Somebody else in a different language once proposed "goto" as the keyword.
