### ISSUE TITLE
encoding/json: doc on valid key names is outdated

### ISSUE THREAD

**Issue by glasser** [golang/go#15317]
On master, the [documentation for json.Marshal](https://github.com/golang/go/blob/7f52b43954d75aa0c444d57b9d0eb7ff36eb3dd0/src/encoding/json/encode.go#L91-L93) says:

```
// The key name will be used if it's a non-empty string consisting of
// only Unicode letters, digits, dollar signs, percent signs, hyphens,
// underscores and slashes.
```

However, this is [quite outdated](https://github.com/golang/go/commit/52f122d72ee3fab46603ccd76259d1f9db50be7b). The [current list of allowed characters](https://github.com/golang/go/blob/7f52b43954d75aa0c444d57b9d0eb7ff36eb3dd0/src/encoding/json/encode.go#L754) consists of letters, digits, space, and these punctuation characters: `!#$%&()*+-./:<=>?@[]^_{|}~`

I'm happy to send a Gerrit CL to fix this but am curious about what people think would be better: literally listing this set of characters, or saying something like "most punctuation characters, excluding backslash, quotes, and comma"?

**Comment by bradfitz** [comment]
What are you trying to link to? There is no line 7540 in that file?

**Comment by glasser** [comment]
Whoops, my fingers must have slipped and added an extra 0. Link fixed.

**Comment by bradfitz** [comment]
I see. Yeah, I don't think we want that soup of punctuation near English.

**Comment by glasser** [comment]
Something like:

> Valid key names can contain Unicode letters, digits, spaces, and some punctuation marks (not including quotes, backslash, or comma). If the key name is not valid, the default name is used.

?

**Comment by rsc** [comment]
This is the right text (fix the text, don't rewrite it):

// The key name will be used if it's a non-empty string consisting of
// only Unicode letters, digits, and ASCII punctuation except quotation
// marks, backslash, and comma.
