### ISSUE TITLE
example link does not load

### ISSUE THREAD

**Issue by morenoh149** [golang/go#15320]
Over at https://github.com/golang/proposal/blob/master/design/15292-generics.md#generic-arguments-in-favor-of-generics

`(even C has generics, where they are called preprocessor macros; example).` link https://gcc.gnu.org/viewcvs/gcc/trunk/gcc/vec.h?revision=165314&view=markup&pathrev=165314 returns forbidden

**Comment by bradfitz** [comment]
@morenoh149, it loads for me. You might be behind a proxy blocking it.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I have nothing to add except that it works for me too.

Can you access http://gcc.gnu.org at all?

**Comment by morenoh149** [comment]
nope. And I can on my phone. I'm probably behind a proxy then. thanks.
