### ISSUE TITLE
net: make cgo-based DNS resolution respect context cancel

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15321]
We should make cgo-based DNS lookups respect deadline + cancelation via a Context.

See https://go-review.googlesource.com/#/c/22101/2/src/net/lookup_unix.go@70

/cc @ianlancetaylor

**Comment by sctb** [comment]
@bradfitz Is this still desired for 1.7? I'm ready to open a CL if you like.

**Comment by mdempsky** [comment]
@sctb How do you propose to fix the issue? It seems non-trivial to me to make getaddrinfo respect deadline/cancellation.

**Comment by sctb** [comment]
I can't say I have any magic to interrupt a call to `getaddrinfo`, but it seems like we can at least make it in a goroutine so we can return to the caller on time. This is what's done in the Windows code.

**Comment by bradfitz** [comment]
@sctb, that sounds fine. Do you want to send a change?
