### ISSUE TITLE
net/http: set Dialer.DualStack on DefaultTransport?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15324]
The http package doesn't set net.Dialer.DualStack on its default transport configuration. Maybe it should.

@mikioh, @pmarks-net, thoughts?

(This might've helped @jfrazelle who I recall was fighting IPv6 once)

**Comment by pmarks-net** [comment]
Happy Eyeballs is a prisoner's dilemma: if one client uses it, it gains an advantage over its neighbors when the network is broken.  But if everyone uses it, then everyone pays the 300ms penalty, and the network never gets fixed.

I have no strong opinion on whether or not it should be the default.

**Comment by bradfitz** [comment]
@pmarks-net, maybe we spew a log message to stderr whenever the slow dial in happy eyeballs win the race. "WARNING: your IPv6 is broken; fell back slowly to IPv4"

**Comment by mikioh** [comment]
I'd like to hear the detail of the fight. It might be a help to understand what would be a root cause of bad, ambient unaware selection on multiple IP links, addresses, various name to address mappings.
