### ISSUE TITLE
net: clean up port parsing

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15326]
https://go-review.googlesource.com/#/c/19720/ updated the parsing of port numbers, but now it accepts
stuff starting with a `+' sign, like:

```go
   net.Dial("tcp", "foo.com:+80")
```

Nobody ever told me why that should be allowed, but the CL was submitted anyway. Or I missed it, but I can't find it.

Investigate and ideally fix.

/cc @mikioh @msiebuhr

**Comment by mikioh** [comment]
Yes, I will send a followup CL for better consistency. FWIW, unfortunately the following snippet works w/ CGO_ENABLED=1 older versions or GODEBUG=netdns=cgo newer versions.
```
package main

import "net"

func main() {
	for _, arg := range []string{"127.0.0.1:+0", "127.0.0.1:-0"} {
		ln, err := net.Listen("tcp", arg)
		if err != nil {
			println(err.Error())
			continue
		}
		println(ln.Addr().String())
		ln.Close()
	}
}
```
Probably we should make consistent representation on transport service names and literal port numbers in ABNF for Dial/Listen APIs before Go 1.

**Comment by bradfitz** [comment]
Okay, if +n worked before, we don't need to do anything here. Still weird, but yay compatibility.
