### ISSUE TITLE
cmd/compile: mishandling multiple reflect.Value uintptr=>unsafe.Pointer conversions in single statement

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15329]
[I thought I've pointed this out before, but I can't find the issue for it now, so filing again.]

[tip.golang.org/pkg/unsafe](https://tip.golang.org/pkg/unsafe) says:

> (5) Conversion of the result of reflect.Value.Pointer or reflect.Value.UnsafeAddr from uintptr to Pointer.
>
> Package reflect's Value methods named Pointer and UnsafeAddr return type uintptr instead of unsafe.Pointer to keep callers from changing the result to an arbitrary type without first importing "unsafe". However, this means that the result is fragile and must be converted to Pointer immediately after making the call, in the same expression:
>
>     p := (*int)(unsafe.Pointer(reflect.ValueOf(new(int)).Pointer()))
>
> As in the cases above, it is invalid to store the result before the conversion:
>
>     // INVALID: uintptr cannot be stored in variable
>     // before conversion back to Pointer.
>     u := reflect.ValueOf(new(int)).Pointer()
>     p := (*int)(unsafe.Pointer(u))

However, the Go compiler does not correctly handle this case when there are multiple reflect.Value.Pointer invocations in a single statement.  For example: http://play.golang.org/p/lBhYwaBvSa

The problem is that when there are multiple function calls in a statement, cmd/compile rewrites all of the calls into separate statements that spill to temporary stack variables with the same type as their return value.  Conversions are only applied after all of the function calls are evaluated, which leaves the reflect.Value.Pointer return value sitting on the stack for a while, at risk of becoming invalidated.  I.e.,

    	eq(unsafe.Pointer(f(1).Pointer()), unsafe.Pointer(f(2).Pointer()))

is compiled as roughly:

        var autotmp_1 uintptr = f(1).Pointer()
        var autotmp_2 uintptr = f(2).Pointer()
     	eq(unsafe.Pointer(autotmp_1), unsafe.Pointer(autotmp_2))

I think the least surprising fix would be that we recognize the pattern `unsafe.Pointer(x())` where `x()` has type `uintptr`, and ensure its autotmp variable is type `unsafe.Pointer` instead of `uintptr`.  This should fix both of the test cases in the sample program above.

**Comment by randall77** [comment]
This sounds like a bug in the current compiler and what you're proposing is a band-aid for a symptom, not a fix of the underlying cause.

When evaluating f(e1, e2, e3) we should evaluate (completely, as far as can be observed) f, then e1, then e2, then e3.  The spec says so.  I'm not sure why we're hopping around evaluating parts of the e's in zigzag order.  My guess is that it was done to improve codegen in the legacy compiler.

Maybe you've just found a corner case in the "as far as can be observed" logic, and we just fix that.

**Comment by mdempsky** [comment]
cmd/compile already rewrites statements to respect the Go spec's order of evaluation rules.  E.g., it rewrites:

     x := y[f()] + int(g())

into

    autotmp_f := f()
    autotmp_g := g()
    x := y[autotmp_f] + int(autotmp_g)

Note that the Go spec doesn't define the order of evaluation for all kinds of subexpressions (such as array/slice indexing), so cmd/compile only rewrites statements to avoid more than one ordered subexpression.

Conversions don't generally have visible side effects (aside from changing value representation), so the Go spec doesn't specify an ordering for them.  Similarly, cmd/compile doesn't proactively rewrite them right now either.

However, `uintptr` to `unsafe.Pointer` conversions *do* have visible side effects, as demonstrated above.

**Comment by randall77** [comment]
Maybe it would be enough to treat ptr<->uintptr conversions as a function call?

**Comment by rsc** [comment]
cmd/compile/internal/gc/order.go must be changed to make ordercall include any outer uintptr->unsafe.Pointer conversion (but critically NOT the reverse) when pulling out the piece to be ordered.

**Comment by mdempsky** [comment]
@rsc Yep, that's roughly what I was thinking as well.

**Comment by mdempsky** [comment]
@rsc Any comments on CL 22273, and whether we should still try to submit it for 1.7?

The issue has existed for a while, so it wouldn't be unreasonable to defer to 1.8.

Also, I don't have any evidence of it being a problem that affects real-world applications. I've briefly reviewed all of the uses of unsafe.Pointer(reflectValue.Pointer()) in Google's internal code, and none of them appear at risk of triggering this issue.

I'm personally a little wary of touching order.go right now after #15602 and #15604.

**Comment by rsc** [comment]
I think this can / should wait for Go 1.8.
