### ISSUE TITLE
net/http: backport TimeoutHandler fix to Go 1.6.2

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15327]
As Andy Hochhaus writes on golang-nuts:

> Starting in go 1.6.0 issue #14568 caused http.TimeoutHandler() to not behave correctly (timer was started too early and was not reset per http request). This bug was introduced in Dec 2015 in 0478f7b9d6e9e0461e67716f003f4dbf26bf634d and resolved in Feb 2016 in bd68b8abc2e3ceaa3b9bde98568a4a9af8bde40f.
>
> Any chance the fix could be included in 1.6.2 as the bug was a 1.6 regression?

I agree we should backport the fix. I never realized it was introduced in 1.6.

@adg, @rsc?

**Comment by adg** [comment]
Looks low-risk enough to be worthy of inclusion.

**Comment by adg** [comment]
@bradfitz the cherry-pick of bd68b8abc2e3ceaa3b9bde98568a4a9af8bde40f doesn't apply cleanly. Would you mind doing the cherry-pick, since you're the domain expert? Thank you.

**Comment by bradfitz** [comment]
Remind me of the process? (Or link to docs?)

**Comment by adg** [comment]
```
# create work branch tracking release branch
$ git change release-branch.go1.6
$ git change go16pick
# cherry pick and mail cl
$ git cherry-pick $HASH
$ git mail
```
