### ISSUE TITLE
Syscall6，can't support passing non-pointered value。for example：VARIANT. 

### ISSUE THREAD

**Issue by chengziqing** [golang/go#15335]
DLL API sometimes passing non-pointered vlue. for example:
1、
BmOpcDaClt_API BOOL _stdcall BMDACReadItem(DWORD ServerHandle,DWORD GroupHandle,DWORD ItemHandle,VARIANT* Value,FILETIME* pTimeStamp,WORD* pQuality

Here V-ARIANT* is pointer value type.

This is OKay：

var Value *ole.VARIANT
Value1 := ole.VARIANT{}
Value = &Value1

var pTimeSBmOpcDaClt_API BOOL _stdcall BMDACWriteItem(DWORD ServerHandle,DWORD GroupHandle,DWORD ItemHandle,VARIANT Value, BOOL DoAsync)tamp *w32.FILETIME
pTimeStamp1 := w32.FILETIME{}
pTimeStamp = &pTimeStamp1
var pQuality *uint16
var pQuality1 uint16 = 0
pQuality = &pQuality1

BMDAC_ReadItem.Call(uintptr(ConnectHandle), uintptr(GroupHandle), uintptr(ItemHandle), uintptr(unsafe.Pointer(Value)), uintptr(unsafe.Pointer(pTimeStamp)), uintptr(unsafe.Pointer(pQuality)))

2、
BmOpcDaClt_API BOOL _stdcall BMDACWriteItem(DWORD ServerHandle,DWORD GroupHandle,DWORD ItemHandle,VARIANT Value, BOOL DoAsync)

Here VARIANT is value type
Hiow to do?

**Comment by bradfitz** [comment]
Let's move this discussion to the mailing list or other forum. See https://golang.org/wiki/Questions. Thanks!
