### ISSUE TITLE
bufio.NewWriter combined with encoding/json Encode()

### ISSUE THREAD

**Issue by ZYecho** [golang/go#15338]
go version 1.5.1

I use `func (dec *Decoder) Decode(v interface{}) error` to write json objects, when I use File * to create `func NewDecoder(r io.Reader) *Decoder`, it was all right, but when I change the File * to bufio.NewWriter when call `func NewDecoder(r io.Reader) *Decoder`, and this Decoder I got can't write json objects. I think it was the buffered feature change the work way of Decoder,  but I did't understand it.

And I find the Decoder also has a buffer function https://golang.org/pkg/encoding/json/#Decoder.Buffered,  what differences between bufio.Writer and the built-in buffered function?

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions
