### ISSUE TITLE
net: TestDialTimeout failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#15333]
Since [CL 22101](https://golang.org/cl/22101), TestDialTimeout is failing on Plan 9.

```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:99: #5: dial tcp 127.0.0.1:0: write /net/tcp/clone: connection refused
FAIL
FAIL	net	1.007s
```

See http://build.golang.org/log/eb55b9009e42158295e02337ffa9b5ba1882a40b

The three last tests, which set a positive Dialer.Timeout or Dialer.Deadline, are no longer returning errTimeout.

```
=== RUN   TestDialTimeout
#0: dial tcp 127.0.0.1:0: i/o timeout
#1: dial tcp 127.0.0.1:0: i/o timeout
#2: dial tcp 127.0.0.1:0: i/o timeout
#3: dial tcp 127.0.0.1:0: i/o timeout
#4: dial tcp 127.0.0.1:0: i/o timeout
#5: dial tcp 127.0.0.1:0: write /net/tcp/clone: connection refused
#6: dial tcp 127.0.0.1:0: write /net/tcp/clone: connection refused
#7: dial tcp 127.0.0.1:0: write /net/tcp/clone: connection refused
```

**Comment by 0intro** [comment]
The expected timeout comes from [dialChannel](https://github.com/golang/go/blob/519474451a/src/net/dial_gen.go#L36).
The dialChannel function should probably be modified to use context.Context instead of a deadline.

**Comment by 0intro** [comment]
CC: @bradfitz

**Comment by 0intro** [comment]
The problem is that the os-dependent [dial](https://github.com/golang/go/blob/519474451a44b861e54466998a893a173bd54c4b/src/net/fd_plan9.go#L35) function isn't called anymore from [dialSerial](https://github.com/golang/go/commit/b6b4004d5a5bf7099ac9ab76777797236da7fe63#diff-af10cab567dbd44651926d200c231fceL422).

**Comment by 0intro** [comment]
I propose [CL 22143](https://golang.org/cl/22143) to fix this issue, but I'm not really sure about the interaction with context.Context.
Please take a look.

**Comment by alexbrainman** [comment]
I don't see this failure on my Windows XP pc.

Alex

**Comment by alexbrainman** [comment]
I think Windows XP (any windows) is not currently broken, because plan9 uses different code.

Alex

**Comment by bradfitz** [comment]
@alexbrainman, according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms737606(v=vs.85).aspx ConnectEx isn't available on Windows XP, yet my https://golang.org/cl/22101 deleted 1 of the 2 paths that checked whether ConnectEx was available. It seemed likely to break XP, or at least make XP go into the wrong code path. I think it just disabled the backup racer dial on XP, meaning timeouts wouldn't be reliable?

**Comment by alexbrainman** [comment]
ConnectEx does work on my Windows XP:

```
C:\dev\go\src\net>git rev-parse HEAD
04535459caf349bc5a731133f5e9eef5e1ab9af9

C:\dev\go\src\net>git diff
diff --git a/src/net/fd_windows.go b/src/net/fd_windows.go
index d1d91a6..c776dfd 100644
--- a/src/net/fd_windows.go
+++ b/src/net/fd_windows.go
@@ -70,7 +70,10 @@ func sysInit() {
 	}
 }
 
-func canUseConnectEx(net string) bool {
+func canUseConnectEx(net string) (ret bool) {
+	defer func() {
+		println("canUseConnectEx: net=", net, " returns=", ret)
+	}()
 	switch net {
 	case "udp", "udp4", "udp6", "ip", "ip4", "ip6":
 		// ConnectEx windows API does not support connectionless sockets.

C:\dev\go\src\net>go test -v -run=TestDialTimeout$
=== RUN   TestDialTimeout
canUseConnectEx: net= tcp  returns= true
canUseConnectEx: net= tcp  returns= true
canUseConnectEx: net= tcp  returns= true
--- PASS: TestDialTimeout (0.33s)
PASS
Running goroutines:
net.(*ioSrv).ProcessRemoteIO(0x10d70428)
        c:/dev/go/src/net/fd_windows.go:143 +0xcc
created by net.startServer
        c:/dev/go/src/net/fd_windows.go:243 +0xc9
net.(*ioSrv).ProcessRemoteIO(0x10d70430)
        c:/dev/go/src/net/fd_windows.go:143 +0xcc
created by net.startServer
        c:/dev/go/src/net/fd_windows.go:245 +0x11e

Socket statistical information:
(inet4, stream, default): opened=3 connected=0 listened=0 accepted=0 closed=3 openfailed=0 connectfailed=0 listenfailed=0 acceptfailed=0 closefailed=0

ok      net     0.922s

C:\dev\go\src\net>
```

Alex

**Comment by 0intro** [comment]
> @alexbrainman, according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms737606(v=vs.85).aspx ConnectEx isn't available on Windows XP

I think there is an error in this documentation. As far I understand it, ConnectEx is available since Windows XP. This specific case in Go was probably written for Windows 2000.

Amusingly, the German version of same page have the accurate version (appeared in Windows XP):

https://msdn.microsoft.com/de-de/library/windows/desktop/ms737606(v=vs.85).aspx

**Comment by alexbrainman** [comment]
I agree with what @0intro said. I think non-ConnectEx code is actually for w2k. We don't support w2k, but Go runs on w2k just fine. So I think we should just let that code be as is.

Alex

**Comment by bradfitz** [comment]
If we don't support Go on Windows 2000, don't say we support it on the downloads page, don't have a builder for it, and don't have any developer with a Windows 2000 machine that regularly tests and reports its status, I am going to delete the non-ConnectEx code path from the net package and simplify things.

Sorry, that's way too old.

**Comment by alexbrainman** [comment]
> I am going to delete the non-ConnectEx code path from the net package and simplify things.

Sure. If you think this is worth breaking someone using (even unsupported) version of Go.

Alex

PS: I think you should be able to remove oldLookupPort and oldLookupIP too. Would you like me to send the change and test it here on my Windows XP?

**Comment by bradfitz** [comment]
> PS: I think you should be able to remove oldLookupPort and oldLookupIP too. Would you like me to send the change and test it here on my Windows XP?

Yes, please. I have an XP install CD and license but I have not yet installed it, and my XP install CD is currently in a different city.
