### ISSUE TITLE
DATA RACE on sync.Mutex

### ISSUE THREAD

**Issue by bronze1man** [golang/go#15340]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
I use -race on my code,but I see DATA RACE Write by sync/atomic.CompareAndSwapInt32 and Read by my code.

4. What did you expect to see?
DATA RACE on some my code

5. What did you see instead?
DATA RACE on sync.Mutex

```
==================
WARNING: DATA RACE
Write by goroutine 91:
  sync/atomic.CompareAndSwapInt32()
      /usr/local/go/src/runtime/race_amd64.s:279 +0xb
  sync.(*Mutex).Lock()
      /usr/local/go/src/sync/mutex.go:44 +0x4d
  xxx/kmgClose.(*Closer).GetCloseChan()
      /xxx/kmgClose/closer.go:53 +0x3d
  xxx/xxx.(*xxx).runOnMainThread()
      /xxx/xxx/xxx.go:666 +0x7c
  xxx/xxx.(*xxx).closeOneTcpConn__notMainThread()
      /xxx/xxx/xxx.go:660 +0xcd
  xxx/xxx.(*xxx).newConn.func1()
      /xxx/xxx/xxx.go:525 +0x250

Previous read by goroutine 13:
  xxx/xxx.(*xxx).tunReadAckProcess()
      /xxx/xxx/xxx.go:388 +0x8c8
  xxx/xxx.(*xxx).ipReadProcess__mainThread()
      /xxx/xxx/xxx.go:250 +0x10cf
  xxx/xxx.(*xxx).runLoop()
      /xxx/xxx/xxx.go:144 +0x20b
  xxx/xxx.RunTcpDirectOutMethod.func1()
      /xxx/xxx/xxx.go:33 +0x2e

Goroutine 91 (running) created at:
  xxx/xxx.(*xxx).newConn()
      /xxx/xxx/xxx.go:557 +0x28e
  xxx/xxx.(*xxx).ipReadProcess__mainThread()
      /xxx/xxx/xxx.go:211 +0x669
  xxx/xxx.(*xxx).runLoop()
      /xxx/xxx/xxx.go:144 +0x20b
  xxx/xxx.RunTcpDirectOutMethod.func1()
      /xxx/xxx/xxx.go:33 +0x2e

Goroutine 13 (running) created at:
  xxx/xxx.RunTcpDirectOutMethod()
      /xxx/xxx/xxx.go:34 +0x2c4
  xxx/xxx.(*xxx).startConnectToServer()
      /xxx/xxx.go:46 +0x457
==================
```

**Comment by ianlancetaylor** [comment]
I don't understand what bug you are reporting.  The race detector is saying that it found a problem.  You seem to agree that there is a problem.  Are you asking why it didn't report a different problem?  That seems like a question better discussed in a forum; see https://golang.org/wiki/Questions .  If you think there is a bug here, please explain more clearly what the bug is.  Thanks.

**Comment by bradfitz** [comment]
Yeah, this is best suited to a forum (https://golang.org/wiki/Questions).

**Comment by bronze1man** [comment]
Thanks,@bradfitz 
I just known why this kind of data race happened, I just copied a sync.Mutex.
I think the DATA RACE message should provide more infomation.

**Comment by ianlancetaylor** [comment]
@bronze1man What additional information would you like?  Please be specific, and if possible consider whether it is possible to gather that information efficiently.  Thanks.

**Comment by bronze1man** [comment]
@ianlancetaylor how about some references to the actually disassembly code ?
One line of code can do a lot of things, I just want to know which thing of them tiggers the data race.

The null reference panic have same problem.

**Comment by ianlancetaylor** [comment]
The race detector doesn't work at the assembly instruction level.  It changes the way that the code is compiled.  It does in fact point you at the exact instruction.  In the line `/xxx/kmgClose/closer.go:53 +0x3d` it's the instruction 0x3d into the function at line 53 of closer.go.  You can disassemble the program using `go tool objdump` to spot the exact instruction.  Make sure you disassemble the version of the function built with `-race`.

Similarly you can look at the stack trace of a panic to identify the exact instruction that does a nil dereference.
