### ISSUE TITLE
help needed on failing code on go 1.6.1 but was passing on go 1.4.2

### ISSUE THREAD

**Issue by salimane** [golang/go#15341]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.1 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
This code was green on go 1.4.2
https://travis-ci.org/buger/gor/builds/92756998

but now it's failing on go 1.6.1 https://travis-ci.org/buger/gor/builds/123705073

4. What did you expect to see?
https://travis-ci.org/buger/gor/builds/92756998

5. What did you see instead?

https://travis-ci.org/buger/gor/builds/123705073

Any help is appreciated

Thanks

**Comment by bradfitz** [comment]
Please write a self-contained bug report, ideally with no links to travis build results.

What changed or doesn't work as expected now? Do you have a small, self-contained way to reproduce the failure?

**Comment by salimane** [comment]
@bradfitz thanks for the quick response.

I'm thinking it's around ``net.Listener`` and family.

I didn't want to include links to travis-ci, but the problem only manifests itself while running the tests.

```
git clone https://github.com/buger/gor.git
cd gor
git checkout fix_tests
go get ./...
go test ./... -v -timeout 60s -race
```

I will really appreciate help in debugging this.

Thanks

**Comment by buger** [comment]
Worth noticing that tests depend on RAW sockets, it creates HTTP server, opens RAW socket, and validate that data that comes to HTTP successfully captured.

**Comment by salimane** [comment]
It was not related to the golang version, so i'm closing this
