### ISSUE TITLE
function call when function is in variable works 3 times slower

### ISSUE THREAD

**Issue by powerman** [golang/go#15351]
1. What version of Go are you using (`go version`)?
go version go1.6.1 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/powerman/gocode"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"

3. What did you do?
https://play.golang.org/p/_fWEoXo0yF
On playground it doesn't show this issue because it doesn't play nice with time, so you have to run it on real system.

4. What did you expect to see?
Incr2 should not be slower than other cases.

5. What did you see instead?
Incr1: 4.624273ms
Incr2: 15.624789ms
Incr3: 4.61209ms

I've also benchmarked many other variants to indirectly call function and all have same speed as normal function call - except function-in-a-var case.

**Comment by randall77** [comment]
This is expected.  For both the Incr1 and Incr3 calls the target of the call is statically determined (and the target is probably inlined).  For the Incr2 call the callee cannot be statically determined (as some other code might overwrite Incr2 with something else).  The Incr2 call site requires a dynamic dispatch.
