### ISSUE TITLE
cmd/compile: generate fewer OKEY Nodes

### ISSUE THREAD

**Issue by josharian** [golang/go#15350]
We generate an OKEY node for every element of a static array. However, relatively few static arrays manually number their elements. We should be able to get rid of two nodes (OKEY, OKEY.Left) per static array element and rely on the implicit numbering for non-manually-numbered arrays.

/cc @mdempsky @ianlancetaylor

**Comment by mdempsky** [comment]
Sounds reasonable to me.

**Comment by josharian** [comment]
Started on this, but haven't gotten it working yet. In case I don't get it done by the 1.7 freeze, here are some notes for future me and other readers.

Previously, composite literals stored their elements in Node.List. When there was a key present, the Node.List element is an OKEY, with key in Left and value in Right. Instead, switch to use both List and Rlist; keys are in List, values are in Rlist, and they correspond by index. A nil element in List means no value. Step one is switching to that representation. Step two is changing OARRAYLITs to leave keys nil when the constant they hold corresponds to their index. Possibly, step two-and-a-half is changing OSTRUCTLIT to leave keys nil when the struct field they hold corresponds to their index. Step three is leaving List itself nil when it contains all nils.

The only remaining use of OKEY after that would be slices. It might well be more efficient to use a List for that instead of an OKEY. Here's an excerpt from syntax.go:

```go
	OSLICE     // Left[Right.Left : Right.Right] (Left is untypechecked or slice; Right.Op==OKEY)
	OSLICEARR  // Left[Right.Left : Right.Right] (Left is array)
	OSLICESTR  // Left[Right.Left : Right.Right] (Left is string)
	OSLICE3    // Left[R.Left : R.R.Left : R.R.R] (R=Right; Left is untypedchecked or slice; R.Op and R.R.Op==OKEY)
	OSLICE3ARR // Left[R.Left : R.R.Left : R.R.R] (R=Right; Left is array; R.Op and R.R.Op==OKEY)
```

Note that OSLICE, OSLICEARR, and OSLICESTR could be `Left[List[0]:List[1]]`. OSLICE3 and OSLICE3ARR could be `Left[List[0]:List[1]:List[2]]`. At this point, Node slices are definitely cheaper than Node trees.

There are probably other such instances where we could flatten trees into slices.

Also, we introduce a bunch of OPAREN nodes just to track line numbers before typechecking; see wrapname in parser.go. I wonder whether there's a cheaper way to accomplish this.

**Comment by griesemer** [comment]
Please make sure that all.bash keeps running with -newexport after these changes since it's not yet enabled by default. The easiest way to check is: `(export GO_GCFLAGS=-newexport; sh all.bash)`.
