### ISSUE TITLE
website: play.golang.org post's 403ing

### ISSUE THREAD

**Issue by swynter-ladbrokes** [golang/go#15358]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version g1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
I went to http://play.golang.org/p/YMf_UBvDsH

4. What did you expect to see?
A shared post

5. What did you see instead?
Forbidden

I was having a chat with the chaps on #go-nuts, they suspect that the /28 IP range we switched too last night might appear to be from the PRC or something - it's not, it's Brisbane Australia (poke all the fun you like, but some of us actually have internet)

I can visit http://play.golang.org and play as much as I like, but the share button is missing and if I try to view other peoples posts then I get 403 Forbidden.

The IP I'm coming from is 103.58.192.211 (we actually have the whole 103.58.192.0/22), there are no proxies at this end.

**Comment by ianlancetaylor** [comment]
CC @jbuberel

**Comment by bradfitz** [comment]
Jason, see b/26003031 as an example of a previous bug I filed about broken geolocation.

**Comment by jbuberel** [comment]
Reported to the geolocation team internally as: 
b/28265208

I will update here when it is resolved.

**Comment by broady** [comment]
@swynter-ladbrokes - is this still an issue?

**Comment by swynter-ladbrokes** [comment]
![image](https://cloud.githubusercontent.com/assets/8284169/17755953/5a0c96e0-6520-11e6-9593-2174940b0423.png)

Nope, seems good, either you guys fixed it, or it fixed itself.

Thanks!
