### ISSUE TITLE
Golang catch stdout and send http.ResponseWriter

### ISSUE THREAD

**Issue by PumpkinSeed** [golang/go#15368]
1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/loow/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
I wanted to catch the whole os.Stdout and os Stderr and send it in http response. I didn't get the whole. Example at the git clone.

4. What did you expect to see?
```
Cloning into '/home/loow/github/wallball'...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), done.
Checking connectivity... done.
```

5. What did you see instead?
```
Cloning into '/home/loow/github/wallball'...
```

My code: 
```
type flushWriter struct {
	f http.Flusher
	w io.Writer
}

func (fw *flushWriter) Write(p []byte) (n int, err error) {
	n, err = fw.w.Write(p)
	eH(err)
	if fw.f != nil {
		fw.f.Flush()
	}
	return
}

func pioBuild(w http.ResponseWriter, r *http.Request) {

	fw := flushWriter{w: w}
	if f, ok := w.(http.Flusher); ok {
		fw.f = f
	}
	cmd := exec.Command("/bin/sh", "/srv/pio/build.sh")
	cmd.Stdout = &fw


	cmd.Stderr = &fw

	cmd.Start()
	cmd.Wait()

	io.WriteString(w, "End")
}
```

**Comment by bradfitz** [comment]
git isn't writing those lines to stdout or stderr.

You can convince yourself of that with:

```
$ git clone https://github.com/easiware/wallball.git 2>&1 | cat
Cloning into 'wallball'...
```

Or:

```
$ git clone https://github.com/easiware/wallball.git 2>&1 | less
```

**Comment by PumpkinSeed** [comment]
Thank you, have a nice day.

**Comment by PumpkinSeed** [comment]
I [found ](https://github.com/kr/pty)the best solution.

```
cmd := exec.Command("/bin/sh", "/srv/pio/build.sh")
f, err := pty.Start(cmd)
if err != nil {
	panic(err)
}
io.Copy(w, f)
```
Thanx for @nvcnvn
