### ISSUE TITLE
net/http: Response.Write has bogus Connection header after auto-ungzipped Content-Length response

### ISSUE THREAD

**Issue by sbadame** [golang/go#15367]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

3. What did you do?
I can't use the playground because this requires localhost, which the playground doesn't support.
https://gist.github.com/sbadame/6672153feb5a5430a0129d40b263d8e9

4. What did you expect to see?
Either "Connection: close" or "Connection:keep-alive" and a content length. Or maybe chunk encoding?

5. What did you see instead?

http.Transport.RoundTrip response: HTTP/1.1 200 OK
Connection: close
Connection: keep-alive
Keep-Alive: timeout=7200

http.DefaultClient.Do Response: HTTP/1.1 200 OK
Connection: close
Connection: keep-alive
Keep-Alive: timeout=7200

**Comment by bradfitz** [comment]
Dup of #15366
