### ISSUE TITLE
Json Decoder.Decode fails to recognize invalid Json Arrays

### ISSUE THREAD

**Issue by mpoornima** [golang/go#15363]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mpoornima/Work/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
http://play.golang.org/p/Z2TL2pn9Vt

4. What did you expect to see?
An error while de-serializing a wrong json array

5. What did you see instead?
No error while de-serialization and ignoring of all objects apart from the first object in the input

**Comment by kostya-sh** [comment]
This is feauture, not a bug ;)
It works as documented, see https://golang.org/pkg/encoding/json/#Decoder.Decode and its example.

**Comment by mpoornima** [comment]
Apologies :(. Just read the documentation fully. Makes sense as it is written specifically for streaming (concatenated) JSON Objects.
