### ISSUE TITLE
go test doesn't fully support vendor

### ISSUE THREAD

**Issue by armstrongli** [golang/go#15360]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/armstrongli/gobin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/armstrongli/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
 - create vendor and add all dependencies to the project
 - write test case file
 - run `go test <path to test file>`
 - get error message 
```shell 
armstrongli$ go install cmd/server.go
armstrongli$ go test pkg/server/serverhandler_test.go
# command-line-arguments
pkg/server/serverhandler_test.go:13:2: cannot find package "vendor/github.com/golang/glog" in any of:
	/usr/local/go/src/vendor/github.com/golang/glog (from $GOROOT)
	/Users/armstrongli/gopath/src/vendor/github.com/golang/glog (from $GOPATH)
```

4. What did you expect to see?
test cases run

5. What did you see instead?
 ```shell 
armstrongli$ go install cmd/server.go
armstrongli$ go test pkg/server/serverhandler_test.go
# command-line-arguments
pkg/server/serverhandler_test.go:13:2: cannot find package "vendor/github.com/golang/glog" in any of:
	/usr/local/go/src/vendor/github.com/golang/glog (from $GOROOT)
	/Users/armstrongli/gopath/src/vendor/github.com/golang/glog (from $GOPATH)
```

actually the `glog` exists:
```shell
armstrongli$ ls vendor/github.com/golang/glog/
LICENSE      glog.go      glog_file.go
```

**Comment by cespare** [comment]
You should give `go test` a package to run rather than a test file. See `go help test` and `go help packages` for more info.

I recommend going through the channels listed in https://github.com/golang/go/wiki/Questions if you have follow-up questions.
