### ISSUE TITLE
x/playground: "save" shortcuts could be more useful

### ISSUE THREAD

**Issue by rakyll** [golang/go#15378]
It would be nice to register cmd+s and control+s shortcuts to perform the share action. The current behavior is the browser default which is saving the page to my local drive and is never ever what is intended.

/cc @adg @campoy

**Comment by adg** [comment]
Sounds good to me.

**Comment by robpike** [comment]
Sounds undiscoverable and random to me.

**Comment by fabiopicchi** [comment]
I understand that overriding a browser default is not something that should be done arbitrarily but I saw myself pressing CRTL + S  on the playground a couple of times and I never intended to save the HTML. Neither did I intend to share the code...

Maybe it would be more useful to save the code in a go file, when the text area has focus. It is closer to the browser default and it's the action I wanted to happen when I pressed the shortcut.

**Comment by adg** [comment]
That's an interesting idea. Ctrl-S could redirect to the .go page with a
'Content-Disposition: attachment' header so that it is downloaded to the
user's computer.

**Comment by rakyll** [comment]
Closing. The suggested behavior is not the expected behavior as far I can see from this thread. The focused/unfocused behavior change suggestion sounds very complicated and hard to discover to me. I will click on the button.

**Comment by adg** [comment]
Re-opening this and re-titling as it is now about something else. @rakyll feel free to unsubscribe if this feature doesn't interest you.

**Comment by broady** [comment]
Deployed. Looks great. Thank you to Alexander Kucherenko.
