### ISSUE TITLE
container/heap incorrect benchmark

### ISSUE THREAD

**Issue by djadala** [golang/go#15380]
Hi,
in heap_test.go, function BenchmarkDup, heap is created as 
`h := make(myHeap, n)` and then n elements are added: `Push(&h, 0)`, 
so first time there are 2*n elements in heap,

heap should be created with zero len:
`h := make(myHeap, 0, n)` 
Regards

**Comment by davecheney** [comment]
Do you want to send a CL for this, https://golang.org/doc/contribute.html

**Comment by djadala** [comment]
done
https://go-review.googlesource.com/22310 container/heap: fix benchmark
