### ISSUE TITLE
spec: "representability" is not well defined in the spec

### ISSUE THREAD

**Issue by griesemer** [golang/go#15389]
We define other terms such as assignability, type identity, etc. Representability (as in "representable as a value of type T") is not explicitly defined. Yet it is a crucial concept: type checkers typically have a function implementing this predicate.

**Comment by griesemer** [comment]
See also #15384 as an example of where "representability" plays a role.

**Comment by odeke-em** [comment]
How's it going @griesemer? Just a gentle reminder about this issue.

**Comment by griesemer** [comment]
@odeke-em Not urgent but I'm aware of it.
