### ISSUE TITLE
spec: conversion of constant string to []byte not allowed by spec but accepted by the compiler

### ISSUE THREAD

**Issue by cznic** [golang/go#15384]
The specs might be missing a piece of information(?).

In [Conversions](http://tip.golang.org/ref/spec#Conversions):
> A constant value x can be converted to type T in any of these cases:
>
> - x is representable by a value of type T.
> - x is a floating-point constant, T is a floating-point type, and x is representable by a value of type T after rounding using IEEE 754 round-to-even rules, but with an IEEE -0.0 further rounded to an unsigned 0.0. The constant T(x) is the rounded value.
> - x is an integer constant and T is a string type. The same rule as for non-constant x applies in this case.

The compiler [accepts](http://play.golang.org/p/dWk9Bsaj5M) conversions like `[]byte("foo")`. The converted expression in this case *is* a 'constant value', but it's none of the above quoted legal cases.

FTR: Later on the section says:

> A non-constant value x can be converted to type T in any of these cases:
> ...
>  - x is a string and T is a slice of bytes or runes.

However, `"foo"` is not a 'non-constant value'.

**Comment by davecheney** [comment]
> The converted expression in this case is a 'constant value',

I'm not sure that is true, http://play.golang.org/p/Cj7sRWifuf. Maybe I misunderstood.

**Comment by cznic** [comment]
Unfortunate ambiguity. I should have written 'the expression being converted' to be more precise.

**Comment by griesemer** [comment]
Roughly speaking, the underlying types of constants must be basic types (or they are untyped). So []byte("foo") is not a constant. But this may not be well defined in the spec. Investigating.

**Comment by griesemer** [comment]
I believe the spec is correct here; but I agree that it perhaps could be organized more clearly (this latter point is of a more general nature - so let's leave that alone for now). Specifically, the spec says, as you pointed out:

> A constant value x can be converted to type T in any of these cases:
> 
> x is representable by a value of type T.
> x is a floating-point constant, T is a floating-point type, and x is representable by a value of type T after rounding using IEEE 754 round-to-even rules, but with an IEEE -0.0 further rounded to an unsigned 0.0. The constant T(x) is the rounded value.
> x is an integer constant and T is a string type. The same rule as for non-constant x applies in this case.

`"foo"` is clearly a constant value. But `"foo"` is not _representable_ as a value of type `[]byte` (nor is it a floating point or integer constant). Hence this section does not apply, but the next sentences do:

> Specific rules apply to (non-constant) conversions between numeric types or to and from a string type. These conversions may change the representation of x and incur a run-time cost.

That is, []byte("foo") conversions are non-constant, and they do change representation - and even incur a runtime cost.

The term "representable" is not well defined - we have been using it somewhat loosely with numeric values only. I'm going to file a separate issue for that.
