### ISSUE TITLE
cmd/compile: extra zero initialization in &T{}

### ISSUE THREAD

**Issue by randall77** [golang/go#15391]
```
type T struct {
	a, b int
}
func f() *T {
	return new(T)
}
func g() *T {
	return &T{}
}
```
`f` just calls `newobject` and returns the result.
`g` calls `newobject`, writes two zeros to the result, then returns it.  Those zero writes are unnecessary.

**Comment by bontibon** [comment]
Previously reported here: #15199

**Comment by randall77** [comment]
Closing as duplicate.
