### ISSUE TITLE
go test ./... (go v1.6) why test vendor folder?

### ISSUE THREAD

**Issue by smaxwellstewart** [golang/go#15401]
Hey Gophers!

Why does go test ./... test the vendor folder?

I know this has already had much discussion mainly in #11659, but I can't contribute to that locked thread and I have a compelling reason to put forward that no one else has.

My argument as to why go test ./... should not test the vendor folders is that the default behaviours of the main vendoring mechanism (godep) and the main test mechanism (go test) should play nice together, no? 

So when you run godep save it vendors your dependencies WITHOUT test files. But then go test by default tests this folder? Why this makes no sense and just results in a lot of useless output from what used to be a very useful command. As others have said it could be very simple to cd into vendor and then run a test in there if that edge case needs supporting.

Does this make sense to other folks?

**Comment by bradfitz** [comment]
Questions should be sent to the mailing list. See https://golang.org/wiki/Questions

godep is one of many vendoring tools. It is not a bug if we're inconsistent with something in the world.
