### ISSUE TITLE
x/mobile: gomobile init error on os X

### ISSUE THREAD

**Issue by dingbo8128** [golang/go#15400]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go 1.6.1
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="darwin"
   GOOS="darwin"
   GOPATH="/Users/bo/GOPATH"
   GORACE=""
   GOROOT="/usr/local/go"
   GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="clang"
   GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
   CXX="clang++"
   CGO_ENABLED="1"
3. What did you do?
   init go mobile development environment
   my xcode version is 6.4
4. What did you expect to see?
   go mobile tool chain installed successfully
5. What did you see instead?
   data:~ bo$ gomobile init
   gomobile: go install -p=8 golang.org/x/mobile/app failed: exit status 2
   # golang.org/x/mobile/app
   
   In file included from GOPATH/src/golang.org/x/mobile/app/darwin_amd64.go:16:
   In file included from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:29:
   In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/HIToolbox.h:240:
   In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/IMKInputSession.h:23:
   In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
   In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:6:
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
   @class NSArray<ObjectType>;
             ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:16: error: cannot find protocol declaration for 'ObjectType'
   @class NSArray<ObjectType>;
              ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:25: error: cannot find protocol declaration for 'ObjectType'
   @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                       ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:37: error: expected identifier or '('
   @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                                   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:13: error: expected ')'
6. (nullable ObjectType)nextObject;
           ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:3: note: to match this '('
7. (nullable ObjectType)nextObject;
   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:25: error: cannot find protocol declaration for 'ObjectType'
   @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                       ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:1: error: duplicate interface definition for class 'NSEnumerator'
   @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:12: note: previous definition is here
   @interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
          ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:37: error: method type specifier must start with '-' or '+'
   @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:38: error: expected a type
   @interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                    ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: error: expected selector for Objective-C method
   @property (readonly, copy) NSArray<ObjectType> *allObjects;
   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:36: error: cannot find protocol declaration for 'ObjectType'
   @property (readonly, copy) NSArray<ObjectType> *allObjects;
                                  ^
   In file included from GOPATH/src/golang.org/x/mobile/app/darwin_amd64.go:16:
   In file included from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:29:
   In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/HIToolbox.h:240:
   In file included from /System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/IMKInputSession.h:23:
   In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
   /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:32: error: cannot find protocol declaration for 'ObjectType'
   @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                              ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:44: error: expected identifier or '('
   @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                                          ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:19:4: error: expected a type
8. (ObjectType)objectAtIndex:(NSUInteger)index;
   ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:40: error: expected ')'
9. (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                      ^
   /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:33: note: to match this '('
10. (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:20: error: cannot find protocol declaration for 'ObjectType'
    @interface NSArray<ObjectType> (NSExtendedArray)
                   ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:1: error: duplicate interface definition for class 'NSArray'
    @interface NSArray<ObjectType> (NSExtendedArray)
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
    @interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
    @interface NSArray<ObjectType> (NSExtendedArray)
                               ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
    @interface NSArray<ObjectType> (NSExtendedArray)
                                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:28:1: error: expected selector for Objective-C method
11. (NSArray<ObjectType> *)arrayByAddingObject:(ObjectType)anObject;
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:29:12: error: cannot find protocol declaration for 'ObjectType'
12. (NSArray<ObjectType> *)arrayByAddingObjectsFromArray:(NSArray<ObjectType> *)otherArray;
           ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:29:65: error: cannot find protocol declaration for 'ObjectType'
13. (NSArray<ObjectType> *)arrayByAddingObjectsFromArray:(NSArray<ObjectType> *)otherArray;
                                                                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:31:25: error: expected a type
14. (BOOL)containsObject:(ObjectType)anObject;
                        ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:35:13: error: expected ')'
15. (nullable ObjectType)firstObjectCommonWithArray:(NSArray<ObjectType> *)otherArray;
            ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:35:3: note: to match this '('
16. (nullable ObjectType)firstObjectCommonWithArray:(NSArray<ObjectType> *)otherArray;
    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:35:60: error: cannot find protocol declaration for 'ObjectType'
17. (nullable ObjectType)firstObjectCommonWithArray:(NSArray<ObjectType> *)otherArray;
                                                           ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:36:21: error: expected a type
18. (void)getObjects:(ObjectType __unsafe_unretained [])objects range:(NSRange)range;
                    ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:37:30: error: expected a type
19. (NSUInteger)indexOfObject:(ObjectType)anObject;
                             ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:38:30: error: expected a type
20. (NSUInteger)indexOfObject:(ObjectType)anObject inRange:(NSRange)range;
                             ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:39:41: error: expected a type
21. (NSUInteger)indexOfObjectIdenticalTo:(ObjectType)anObject;
                                        ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:40:41: error: expected a type
22. (NSUInteger)indexOfObjectIdenticalTo:(ObjectType)anObject inRange:(NSRange)range;
                                        ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:41:33: error: cannot find protocol declaration for 'ObjectType'
23. (BOOL)isEqualToArray:(NSArray<ObjectType> *)otherArray;
                                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:42:43: error: unknown type name 'ObjectType'
    @property (nullable, nonatomic, readonly) ObjectType firstObject NS_AVAILABLE(10_6, 4_0);
                                          ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:42:20: error: nullability specifier 'nullable' cannot be applied to non-pointer type 'int'
    @property (nullable, nonatomic, readonly) ObjectType firstObject NS_AVAILABLE(10_6, 4_0);
                   ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:43:43: error: unknown type name 'ObjectType'
    @property (nullable, nonatomic, readonly) ObjectType lastObject;
                                          ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:43:20: error: nullability specifier 'nullable' cannot be applied to non-pointer type 'int'
    @property (nullable, nonatomic, readonly) ObjectType lastObject;
                   ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:44:17: error: cannot find protocol declaration for 'ObjectType'
24. (NSEnumerator<ObjectType> *)objectEnumerator;
                ^
    /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:45:17: error: cannot find protocol declaration for 'ObjectType'
25. (NSEnumerator<ObjectType> *)reverseObjectEnumerator;

**Comment by st3fan** [comment]
Xcode 6.4 is pretty old. Maybe give this another try with the current 7.3.1?

**Comment by eliasnaur** [comment]
Is this still a problem with updated Xcode 9, gomobile and Go 1.10?
