### ISSUE TITLE
log.Fatal and defer w.Close

### ISSUE THREAD

**Issue by mandolyte** [golang/go#15402]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
Using the log package, use the SetOutput, for example:
		lg,lgerr := os.Create(logfile)
		if lgerr != nil {
			fatal(fmt.Sprintf("os.Create() Error:%v\n",lgerr))
		}
		w = bufio.NewWriter(lg)
		defer w.Flush()
		defer lg.Close()
		log.SetOutput(w)

Then log some messages, then lastly use log.Fatal to terminate.

The defer to w.Flush() isn't called and the log file doesn't include the last buffer containing the error messages prior to the os.Exit

4. What did you expect to see?
I expected the log package to flush the underlying Writer before exiting.

5. What did you see instead?
The log file was truncated (or if short, was empty), making debugging more difficult. 

The work around was to write my own function, which used a non-Fatal logger method to output the last message; then use a Flush (which required me to make the Writer global - yuck) and then called the Fatal method.

Thank you.

**Comment by bradfitz** [comment]
The log package does write to its writer immediately. You're choosing to use a bufio.Writer.

This is all documented:

https://golang.org/pkg/log/#Fatal -- "Fatal is equivalent to Print() followed by a call to os.Exit(1)."
https://golang.org/pkg/os/#Exit -- "The program terminates immediately; deferred functions are not run."

For compatibility reasons, this can't be changed at this point even if we wanted to.
