### ISSUE TITLE
Unexpected behavior of net library.

### ISSUE THREAD

**Issue by AlexandrButenko** [golang/go#15417]
go version go1.6.2 darwin/amd64

I just write two programs. First - tcp-server. Second - tcp-client. And i tried to count, how many qps can handle my tcp server.

My server
https://gist.github.com/AlexandrButenko/410a7380ab2ab8c23b8cce92edc1b182
My client
https://gist.github.com/AlexandrButenko/997b697fe345dad4d46f3b4b68d8a7db

Actually, i expect to see numbers of requests, which one can be handled by my server. I see it for a while, and then server just stop handle requests (just write 0 in console).

May be i just do something wrong?

P.S. Sorry for my english... I hope somebody can answer.

**Comment by bradfitz** [comment]
The problem is ephemeral port exhaustion. (Your operating system can't do net.Dial that many times in a row)

This is not a Go-specific question.

Let's move this to the mailing list for further discussion.
