### ISSUE TITLE
builders: ppc64le GNU/Linux builder DNS lookup is flaky

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#15414]
The ppc64le GNU/Linux builder has failed several times recently with

    --- FAIL: TestLookupDotsWithRemoteSource (5.20s)
    lookup_test.go:513: LookupCNAME(www.mit.edu) = , lookup www.mit.edu on 192.168.60.10:53: no such host, want cname ending in . with trailing dot (mode=go)
    FAIL
    FAIL net 7.351s

@bradfitz suggests that we need to update the DNS lookup to use 8.8.8.8.

**Comment by laboger** [comment]
I noticed these errors on the build dashboard last week.  I have been under the assumption that if I use ./all.bash when I build then it will build golang and run all the tests and that is the way I've been testing.  When I do that I see this in the list of packages:
...
ok      net     1.365s     
....
ALL TESTS PASSED

But then if I go back and build the test from the net directory after adding the latest go to my path this happens:
go test -c net
./net.test
--- FAIL: TestLookupGoogleSRV (0.00s)
        lookup_test.go:73: lookup _xmpp-server._tcp.google.com on 9.8.234.129:53: no such host
--- FAIL: TestLookupDotsWithRemoteSource (0.89s)
        lookup_test.go:542: LookupSRV(xmpp-server, tcp, google.com): lookup _xmpp-server._tcp.google.com on 9.8.234.129:53: no such host (mode=go)
        lookup_test.go:542: LookupSRV(xmpp-server, tcp, google.com): lookup _xmpp-server._tcp.google.com on 9.8.234.129:53: no such host (mode=cgo)
FAIL

Shouldn't the same results occur no matter which way the net package test is run?

**Comment by minux** [comment]
all.bash runs what is mostly equivalent to go test -short net, some of the
tests that rely on external network accesses are skipped in the short mode.

**Comment by laboger** [comment]
How does the builder run all the tests then?

**Comment by bradfitz** [comment]
all.bash runs tests in short mode.

Builders run more of the tests in short mode.

**Comment by bradfitz** [comment]
Fixed by https://golang.org/cl/22883 and https://golang.org/cl/22852
