### ISSUE TITLE
cmd/go: TestGoGetInsecure fails

### ISSUE THREAD

**Issue by griesemer** [golang/go#15410]
At tip, run on darwin_amd64 and confirmed on a linux laptop. This test does not run in -short mode (i.e., on the builders).

```
$ go test -run GoGetInsecure
--- FAIL: TestGoGetInsecure (3.42s)
    go_test.go:244: running testgo [get -d wh3rd.net/git.git]
    go_test.go:281: testgo succeeded unexpectedly
FAIL
exit status 1
FAIL    cmd/go  9.208s
```

**Comment by bradfitz** [comment]
Looks like that's because @adg added LetsEncrypt (free HTTPS cert) support to https://wh3rd.net/

<img width="423" alt="screen shot 2016-04-22 at 10 46 25 am" src="https://cloud.githubusercontent.com/assets/2621/14750026/849ccdcc-0877-11e6-9162-ce1d2c98e112.png">

**Comment by adg** [comment]
Yup, I saw this coming. I'll prepare an alternate place for the insecure repo.

**Comment by rsc** [comment]
ping @adg

**Comment by adg** [comment]
I propose to fix this by starting a tiny VM running an HTTP server at the host name `insecure.wh3rd.net`. Can anyone suggest a simpler/cheaper approach?

**Comment by bradfitz** [comment]
`insecure.golang.org` would be better. See Google CL 86637006 as an example of how to add the DNS record, which I had @danderson review previously.

**Comment by danderson** [comment]
I would be happy to review another such change, fire it my way and It Shall Be Done.

I presume you would actually point DNS at a GCE load-balanced IP, so that you're not tied to the lifetime of one VM? You probably know the cloud side of things better than me.

**Comment by adg** [comment]
@danderson I'd probably start with a single VM. The IP can be moved to a load balancer if it makes sense to do so, but I doubt it ever will.

**Comment by ianlancetaylor** [comment]
We are currently skipping the test, so retargeting for 1.8.
