### ISSUE TITLE
spec: empty vs absent struct field tag

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15412]
Go spec says

> Two struct types are identical if they have the same sequence of fields, and if corresponding fields have the same names, and identical types, and identical tags.

What does it mean for tags to be identical?  In particular, is an absent tag identical to an empty tag?

cmd/compile rejects this code, but gotype and gccgo-4.8 accept it:

    package p
    var _ *struct{ x int } = (*struct{ x int "" })(nil)

Package reflect's StructField doesn't provide a way to distinguish absent from empty tags, but then it also agrees with cmd/compile that the above types are not assignable to each other: http://play.golang.org/p/QNISntvhWb

/cc @griesemer

**Comment by ianlancetaylor** [comment]
See also #6858 .

**Comment by ianlancetaylor** [comment]
Marking this as Go 1.7 because the compilers disagree.  We should at least figure out what the correct behavior is.

gccgo has ignored empty field tags since the feature was added to the compiler in 2008.

**Comment by griesemer** [comment]
This, together with #6858 is on my list to be addressed soon - probably once we are frozen for 1.7 (changes to this are not going to make it into 1.7 either way, and we have lived with this for years now). I agree this needs to be resolved.

**Comment by mdempsky** [comment]
My 2c: We should treat empty and absent tags as identical. Package reflect's current API makes it difficult to extend to support distinguishing them: we can't add new fields to `reflect.StructField` without breaking backwards compatibility, so we would need to do something clunky like a `FieldHasTag(i int) bool` method to `reflect.Type`.

There also seems to be little value in distinguishing them.  The conventional usage of struct tags involve key-value pairs, for which empty and absent tags can be treated identically anyway.

**Comment by griesemer** [comment]
go/types doesn't distinguish between absent and empty tag strings. It would need an internal change of representation and probably an API change.

**Comment by griesemer** [comment]
Actually, the spec is already clear: See http://tip.golang.org/ref/spec#Struct_types, first example:
```
struct {
	x, y float64 ""  // an empty tag string is like an absent tag
	name string  "any string is permitted as a tag"
	_    [4]byte "ceci n'est pas un champ de structure"
}
```
Comment on first fields: **an empty tag string is like an absent tag**

I'll add an additional sentence to the prose.
