### ISSUE TITLE
Question! compiled binary size and its performance

### ISSUE THREAD

**Issue by hardcoar** [golang/go#15428]
running on: GO 1.6 linux amd64 ubuntu 14.04

this would be a pretty dumb, lazy and basic question i wanted to answer.
and please bare with me because i really want to have answers from more experienced gophers.

i am compiling a web server written in go.
does the size of compiled executable affect the overall performance of the server?

thanks a lot!

**Comment by bradfitz** [comment]
See https://golang.org/wiki/Questions for questions.
