### ISSUE TITLE
unsafe.Sizeof, unsafe.Alignmentof, and unsafe.Offsetof should abide to CamelCaps format.

### ISSUE THREAD

**Issue by falafelizer** [golang/go#15423]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
Using package "unsafe", I noticed Sizeof, Alignmentof, and Offsetof do not abide by the CamelCase format.

4. What did you expect to see?
unsafe.SizeOf
unsafe.AlignmentOf
unsafe.OffsetOf

5. What did you see instead?
unsafe.Sizeof
unsafe.Alignmentof
unsafe.Offsetof

Note: Is the lack of CamelCaps intentional to provide similarity to the C 'sizeof' operator?

**Comment by griesemer** [comment]
This is not going to change, as it would be a backward-incompatible change of the library, and arguably in this case, even the language. Unfortunate.
