### ISSUE TITLE
proposal: change type of syscall.EpollEvent.Pad from int32 to [8]byte

### ISSUE THREAD

**Issue by leonxu0** [golang/go#15435]
1. What version of Go are you using (`go version`)?
go1.6

2. What operating system and processor architecture are you using (`go env`)?
linux 64bit

3. What did you do?

epoll_event struct is defined like this in c:
           
           typedef union epoll_data {
               void    *ptr;
               int      fd;
               uint32_t u32;
               uint64_t u64;
           } epoll_data_t;

           struct epoll_event {
               uint32_t     events;    /* Epoll events */
               epoll_data_t data;      /* User data variable */
           };
member ptr is used to save the pointer, which points to some context data.

in the go1.6 runtime package (runtime/defs_linux_amd64.go), i can also find the struct member for saving the context pointer
           
           type epollevent struct {
                  events uint32
                  data   [8]byte // unaligned uintptr
           }
but when it comes to syscall.EpollEvent (syscall/ztypes_linux_amd64.go) definition :
          
           type EpollEvent struct {
                  Events uint32
                  Fd     int32
                  Pad    int32
           }
i have no room for saving a pointer, Pad only has 4 bytes.

**Comment by bradfitz** [comment]
Good idea or not, the Go 1 compatibility promise (https://golang.org/doc/go1compat) precludes us from changing this.

**Comment by extemporalgenome** [comment]
Can we just add an extra field that either 1) contains a copy of all 8 bytes, or 2) contains the remaining 4 bytes and can be used with a new method/function to construct the full array ?

**Comment by bradfitz** [comment]
A new method(s) might be possible, but not new fields. But that should be done in x/sys/unix, not in the syscall package which is frozen.
