### ISSUE TITLE
cmd/compile: global variable references have weird line numbers

### ISSUE THREAD

**Issue by randall77** [golang/go#15430]
```
package main

import "os"

func main() {
	x := os.Stdout
	x.WriteString("foo\n")
}
```

When I compile this with SSA, I get:
```
	0x0013 00019 (tmp.go:3)	MOVQ	os.Stdout(SB), AX
```
Note the line number.  It's the line number of the `import` statement, not the line number where `os.Stdout` is mentioned.

This bug comes from earlier in the pipeline than the SSA backend.  On input to SSA, we have:
```
.   AS u(2) l(6) colas(true) tc(1)
.   .   NAME-main.x u(1) a(true) g(1) l(6) x(0+0) class(PAUTO) f(1) tc(1) used(true) PTR64-*os.File
.   .   NAME-os.Stdout u(1) a(true) l(3) x(0+0) class(PEXTERN) tc(1) used(true) PTR64-*os.File
```
Note the `l(3)` on the os.Stdout reference.

I suspect the old compiler ends up using the line number of the AS, so it is ok, whereas the SSA compiler uses the line number for the NAME.

Probably a dup of #14742

See issue #15427 

@davecheney

**Comment by minux** [comment]
I think that was used to help reporting errors so the
line number points to the defining line (in this case,
the import statement.)

**Comment by mdempsky** [comment]
All references to an imported object share the same ONAME Node, so their line numbers (at least currently) have to correspond to the definition line rather than the usage line.

**Comment by mdempsky** [comment]
It looks like this should just be a matter of avoiding the `s.pushLine(n.Lineno)` call in `(*state).expr` for ONAME Nodes.  Maybe for named OLITERAL Nodes too.
