### ISSUE TITLE
cmd/go: go install -buildmode=pie fails with permission denied

### ISSUE THREAD

**Issue by petercolberg** [golang/go#15433]
I am trying to compile and install a position-independent executable (PIE) of a minimal Go program:
```go
// hello.go
package main

import "fmt"

func main() {
    fmt.Println("hello world")
}
```

I am using Go 1.6.1 on Debian unstable amd64:
```
# export GOPATH=$PWD
# export GOBIN=$PWD/_install
# go env
GOARCH="amd64"
GOBIN="/tmp/hello/_install"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/hello"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

Compiling the executable works fine:
```
# go build -v -buildmode=pie
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
math
unicode/utf8
sync
syscall
io
strconv
time
reflect
os
fmt
runtime/cgo
_/tmp/hello

# ./hello 
hello world
```

Compiling and installing the executable fails with this error:
```
# go install -v -buildmode=pie
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/lib/go/pkg/linux_amd64_shared: permission denied
```

**Comment by ianlancetaylor** [comment]
In order to run `go install`, you must have permission to write to `GOROOT`.  In your case `GOROOT` is `/usr/lib/go`, but you don't have permission to write there.  I don't think there is anything we can do to fix this.

**Comment by petercolberg** [comment]
Could you please keep this issue open? I do think this issue can be fixed.

Now I have a slightly better understanding of the problem. The Debian package `golang-go` ships only the static variants of the standard and runtime libraries, which are installed in `/usr/lib/go`. Compiling with `-buildmode=pie` requires the shared variants, however, which are not available; hence `go install` builds and tries to install these, which (rightly so) fails due to permissions.

What would be the recommended way to install the Go compiler including both static and position-independent shared variants of the standard and runtime libraries? Debian uses `src/make.bash` for installation, but simply passing `GO_LDFLAGS=-buildmode=pie` does not seem to work.

**Comment by ianlancetaylor** [comment]
Debian can run `go install -buildmode=pie std` to install a version of the standard library ready to build PIE executables.

At this point I don't see a reason to reopen this issue.  I don't see anything we can do on the Go side to fix this; any fix has to be on the Debian side.  I'm happy to reopen if you have a suggestion for what we can do.

**Comment by mwhudson** [comment]
I've been meaning to talk on golang-dev about this for a while, so I finally posted https://groups.google.com/d/msg/golang-dev/BcSBfR2CVo8/ArTy2n7WCAAJ
