### ISSUE TITLE
mime/multipart: part.Reader hangs on an open stream even if entire multipart data is available

### ISSUE THREAD

**Issue by blixt** [golang/go#15431]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go1.6.2
2. What operating system and processor architecture are you using (`go env`)?
   darwin/amd64 (Mac OS/X 10.11.4)
3. What did you do?
   http://play.golang.org/p/D5so_L8JDD
4. What did you expect to see?
   At the very least, all available parts successfully read before the reader hangs on more data from the socket. In this particular example the multipart reader can even reach "EOF" because once it reaches the postamble, it's impossible for there to be any more parts.
5. What did you see instead?
   The multipart reader hangs before even reading the first part. Presumably because it's trying to peek ahead but the socket doesn't have enough data available for the peek buffer.

**Comment by blixt** [comment]
For some background, the reason I want to use `multipart.Reader` with an open stream is because of [Amazon's new AVS API](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service) which involves creating a long-lived HTTP/2 request that progressively receives data in the form of multipart parts.

I did some experiments and the `multipart.Part`'s `Read` method seems to block on `bufio.Reader`'s `Peek` method. It doesn't seem possible to make `bufio` work with open streams that are shorter than the buffer length, so this might be tricky to fix. I even tried making a [non-blocking reader](https://gist.github.com/blixt/2160207dbcb166e3e4e414ced3af0562) to see how it would behave, but `bufio.Reader` just errors out.

**Comment by blixt** [comment]
For anyone else who runs into this issue, here's a working reimplementation of `mime/multipart` which works on both open and closed streams: https://github.com/rogertalk/go-avs/tree/master/multipart2

A few caveats:
* I didn't implement `quoted-printable` support
* It won't be as forgiving for incorrect implementations (e.g., whitespace after boundary)
* It uses a `bufio.Reader` on top of a private implementation similar to `bufio` which wastes some memory (the reason is because `textproto.NewReader(…)` requires `*bufio.Reader` instead of `io.Reader`)
* Probably a few other things are missing too since I only needed this for a specific use case

**Comment by blixt** [comment]
This is fixed by CL https://golang.org/cl/32092 instead so I'm closing this issue.

**Comment by quentinmit** [comment]
We still need to add a test.
