### ISSUE TITLE
os/signal: not all notifications about SIGCHLD are sent

### ISSUE THREAD

**Issue by noxiouz** [golang/go#15437]
1. What version of Go are you using (`go version`)?
```
go version go1.6.2 darwin/amd64
```
Also it's cross compiled and tested on Linux

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/noxiouz/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
http://play.golang.org/p/lLTgaA8MRo

4. What did you expect to see?
Get notification about SIGCHLD from every child 

5. What did you see instead?
Only 65-72 notifications are sent in average case

```
sigchld watcher is ready
10 sec without SIGCHLD. Got 72
```

**Comment by ianlancetaylor** [comment]
I haven't checked yet, but doesn't the same thing happen in a C program?  Except for the real time signals, Unix systems do not normally ensure that all instances of a signal are delivered.  If a signal is raised twice before the program has a chance to handle the first raised signal, the signal handler is only invoked once.

**Comment by noxiouz** [comment]
Unfortunately, I am not an expert in Unix signals sphere. So if it's a planned behavior, the issue can be closed, of course.

**Comment by noxiouz** [comment]
Yes, I found http://www.gnu.org/software/libc/manual/html_node/Merged-Signals.html#Merged-Signals
Thanks! At least, now I know.
