### ISSUE TITLE
SSH KeyChange integration test broken 

### ISSUE THREAD

**Issue by hanwen** [golang/go#15445]
the open ssh server log says:

		debug1: SSH2_MSG_NEWKEYS received
		Bad packet length 1560169096.

which suggests that either a packet with the old key was sent, or the wrong key material was being used.

bisect points to  https://go-review.googlesource.com/#/c/21606/ as the cause.

**Comment by hanwen** [comment]
Looks like kexResult.SessionID isn't set anymore on subsequent key exchanges.

**Comment by shurcooL** [comment]
This is fixed now via https://github.com/golang/crypto/commit/285fb2ed20d1dc450fc743a1b3ff7c36bef372b9 and can be closed.
