### ISSUE TITLE
builtin: new function: abs()

### ISSUE THREAD

**Issue by jfcg** [golang/go#15447]
Absolute value of a numeric value is very often needed in code, hence this is a proposal to add a builtin abs(). Proposed signature:

abs(constant) returns absolute value also as a constant
abs(unsigned integer) returns same value & type
abs(signed integer) returns absolute value as unsigned version of type
abs(float) returns absolute value & same type
abs(complex) returns absolute value as underlying float type

optional:
abs(pointer) returns value of pointer as uintptr

**Comment by bradfitz** [comment]
The language is pretty frozen since 2012. I don't this meets the bar. It would also invite dozens more global functions, which isn't the type of language Go is.

It also is already served by https://golang.org/pkg/math/#Abs, https://golang.org/pkg/math/cmplx/#Abs etc.

**Comment by kafeltz** [comment]
Is there abs() as a built-in function in another languages instead a external lib?
It feels so strange this request.
