### ISSUE TITLE
cmd/vet: go vet on s390x can't handle assembly

### ISSUE THREAD

**Issue by billotosyr** [golang/go#15454]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   tip
2. What operating system and processor architecture are you using (`go env`)?
   linux s390x
3. What did you do?
   go vet in math/big
4. What did you expect to see?
   not an error
5. What did you see instead?
   : arith_s390x.s: cannot determine architecture for assembly file

I will fix this...

**Comment by mundaym** [comment]
cc @minux @cherrymui 

mip64 is missing from the list in cmd/vet too.
