### ISSUE TITLE
install -a  causes access denied on writing to /opt/go/pkg

### ISSUE THREAD

**Issue by neopaf** [golang/go#15450]
Please answer these questions before submitting your issue. Thanks!

What version of Go are you using (`go version`)?
```
[alexander.petrossian@rhel7-build csearch]$ $GOROOT/bin/go version
go version go1.6 linux/amd64
```
What operating system and processor architecture are you using (`go env`)?
```
[alexander.petrossian@rhel7-build csearch]$ $GOROOT/bin/go env
GOARCH="amd64"
GOBIN="/home/alexander.petrossian/csearch/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alexander.petrossian/csearch"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
[alexander.petrossian@rhel7-build csearch]$ 
```
What did you do?
```
[alexander.petrossian@rhel7-build csearch]$ $GOROOT/bin/go get github.com/google/codesearch/cmd/cindex
[alexander.petrossian@rhel7-build csearch]$ $GOROOT/bin/go install -a  github.com/google/codesearch/cmd/cindex
go install runtime/internal/sys: open /opt/go/pkg/linux_amd64/runtime/internal/sys.a: permission denied
[alexander.petrossian@rhel7-build csearch]$ 
```

What did you expect to see?

I expect "install -a" to force-compile only my modules, leave /opt/go/pkg/linux_amd64/runtime/internal/sys.a as it was.
without -a it works perfectly:
```
[alexander.petrossian@rhel7-build csearch]$ $GOROOT/bin/go install github.com/google/codesearch/cmd/cindex
[alexander.petrossian@rhel7-build csearch]$ 
```
But sometimes due to funny date problems I'd like to be able to use that -a option, why not?

What did you see instead?
```
open /opt/go/pkg/linux_amd64/runtime/internal/sys.a: permission denied
```

Previous discussions
There were a discussion about a "bug" #13713, but that approach seems not to cover -a force-compiling. It only limited to considering dots in folder names...

**Comment by bradfitz** [comment]
The behavior is intentional. See https://golang.org/cl/10761

There should be no need to run `-a` in normal use. The "why not?" motivation isn't enough. If you have a concrete bug report where you needed the `-a` option to fix something, that would be the interesting bug and you should file that.

**Comment by rsc** [comment]
In addition to what Brad said, we depend heavily on -a actually recompiling releases when working in the release branch. It does what it says.

**Comment by neopaf** [comment]
Got it, Russel and Brad. 

Russel, BTW, thanks for sharing that fantastic idea
https://swtch.com/~rsc/regexp/regexp4.html
and code behind it.
