### ISSUE TITLE
cmd/go: `go env` discards all but the first word of $CC

### ISSUE THREAD

**Issue by AxbB36** [golang/go#15457]
1. What version of Go are you using (`go version`)?

go1.6.2
1. What operating system and processor architecture are you using (`go env`)?

linux/386

If you try to stuff extra arguments into the CC environment variable, `go env` will throw them away (here, `bar` is discarded):

```
go1.6.2$ CC="foo bar" ./bin/go env
...
CC="foo"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
```

Earlier releases, for example 1.4.3, also remove arguments from CC, but keep them in a separate variable, GOGCCFLAGS:

```
go1.4.3$ $ CC="foo bar" ./bin/go env
...
CC="foo"
GOGCCFLAGS="bar -fPIC -m32 -pthread -fmessage-length=0"
```

The code responsible for this shuffling lies in the `mkEnv` function in env.go:
https://github.com/golang/go/blob/go1.4.3/src/cmd/go/env.go#L55-L56

```
        env = append(env, envVar{"CC", cmd[0]})
        env = append(env, envVar{"GOGCCFLAGS", strings.Join(cmd[3:], " ")})
```

(Indices 1 and 2 are skipped because they [are inserted](https://github.com/golang/go/blob/go1.4.3/src/cmd/go/build.go#L2080-L2081) by `ccompilerCmd` in build.go.) Note that `mkEnv` ignores any previous value of GOGCCFLAGS.

b38fa898c682d6d3f709e4a84710938de5b29d2d is the commit that caused the behvior to change, by [calling `mkEnv` an extra time](https://github.com/golang/go/blob/b38fa898c682d6d3f709e4a84710938de5b29d2d/src/cmd/go/main.go#L155-L162) and overwriting environment variables with its output. Since one application of `mkEnv` does this:

```
CC ← CC[0]
GOGCCFLAGS ← CC[1:] -fPIC -m32 -pthread -fmessage-length=0
```

two applications have the effect of discarding CC[1:]:

```
CC ← CC[0]
GOGCCFLAGS ← -fPIC -m32 -pthread -fmessage-length=0
```

Why this matters to me: I'm cross-compiling using a specially installed GCC that needs extra -I and -L flags to find its files. (Specifically, I'm doing a cross build from linux to darwin for Tor Browser; [see here](https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/descriptors/mac/gitian-pluggable-transports.yml?id=tbb-5.5.5-build3#n76) for details.) I'm running this command, which worked with 1.4.3:

```
CGO_ENABLED=1 CC_FOR_TARGET="$CC $CFLAGS $LDFLAGS" CC= CFLAGS= LDFLAGS= ./make.bash
```

(`$CC` is the cross compiler.) But because make.bash [calls `dist env`](https://github.com/golang/go/blob/go1.6.2/src/make.bash#L129), the necessary `$CFLAGS and $LDFLAGS` disappear and the build fails somewhere in cgo because the compiler cannot find errno.h.
#13377 is a related issue, particularly [this comment](https://github.com/golang/go/issues/13377#issuecomment-159432447) that talks about "only using the first word of $CC." As a workaround I'm using a suggestion from that ticket: I'm making a shell script called cc-for-target that contains `exec $CC $CFLAGS $LDFLAGS "$@"` and invoking make.bash with `CC_FOR_TARGET=cc-for-target`.

**Comment by AxbB36** [comment]
This is what I did to find that b38fa898c682d6d3f709e4a84710938de5b29d2d was the commit that changed behavior.
```
git bisect start
git bisect new go1.6.2
git bisect old go1.4.3
git bisect run ../check.sh
```
where check.sh contains:
```
#!/bin/sh
git clean -df
(cd src && CGO_ENABLED=0 ./make.bash) || exit 125
CC='gcc XYZ' ./bin/go env | grep XYZ
exit $?
```

**Comment by dominikh** [comment]
See also #11685

**Comment by davmaz** [comment]
Ian -
  Have you looked into this. It's killing my cross compile now because of this problem. Is there any work-around? I don't quite understand the one mentioned above.

Thanks -
Dave

**Comment by ianlancetaylor** [comment]
@davmaz I have not looked into this at all.  As far as I know it only affects `go env` output.

In any case it appears that a simple workaround for now is to store your command line in an executable shell script, and set CC to that shell script.

**Comment by davmaz** [comment]
I guess I'll have to find a way. But it does not just effect "go env", it changes the compiler calls (ignores the exported values after the first) and puts in new ones that wreck the cross-compile. I'm surprised more user haven't complained, but I understand. I'll just have to find a way around it if I want to stay current with the latest go version.

**Comment by ianlancetaylor** [comment]
@davmaz This issue just talks about `go env`.  If this affects more than that, can you show the problem in detail, or open a new issue for the problem you are having?  Thanks.

**Comment by davmaz** [comment]
Ian,
  I think it may involve more than go env.  My problem is with cross-compiling a popular C/Fortran library called OpenBLAS. Here's what I did:

I've got the OpenBLAS make to cross-compile the library by doing this:

  *   Find all installed packages for the ARM compiler: sudo aptitude search arm-linux-gnueabi
  *   Purge ALL gnueabi versions: sudo apt-get purge --auto-remove gfortran-arm-linux-gnueabi, etc for any "installed"
  *   Install only gnueabihf versions: sudo aptitude install gfortran-arm-linux-gnueabihf (this also installs gnueabihf gcc)
  *   From the OpenBLAS directory: make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA9
  *   Install the ARM libs: sudo make PREFIX=/usr/local install

The make runs to completion and I can install the ARM OpenBLAS library. I followed similar steps to get FFTW to cross-compile if anyone is interested.

Next, installing go for cross-compiling I did this:

  *
  *    export CGO_ENABLED=1
  *    export CC_FOR_TARGET=arm-linux-gnueabihf-gcc
  *    export GOGCCFLAGS="-fPIC -pthread -mfpu=vfp -mfloat-abi=hard --static"
  *    export GOOS=linux
  *    export GOARCH=arm
  *    export GOARM=7
  *    bash ./all.bash
  *
  *   go env shows:
  *
  *   GOARCH="arm"
  *   GOBIN=""
  *   GOEXE=""
  *   GOHOSTARCH="amd64"
  *   GOHOSTOS="linux"
  *   GOOS="linux"
  *   GOPATH="/opt/Projects/Golang"
  *   GORACE=""
  *   GOROOT="/usr/local/go"
  *   GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
  *   CC="arm-linux-gnueabihf-gcc"
  *   GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build149148529=/tmp/go-build -gno-record-gcc-switches"
  *   CXX="g++"
  *   CGO_ENABLED="1"

Notice the GOGCCFLAGS get mangled (see golang go issues 8161). I can work around that by specifying GOGCCFLAGS on the command line:
GOOS=linux GOARCH=arm GOARM=7 GOGCCFLAGS="-fPIC -pthread -mfpu=vfp -mfloat-abi=hard  --static" CC=arm-linux-gnueabihf-gcc CGO_LDFLAGS="-L/usr/local/lib -lopenblas " go build -x rand_zgeev.go

However, when I copy this to the arm system, it does not run:
 ./rand_zgeev
-sh: ./rand_zgeev: not found

Any ideas why this won't run?
________________________________

**Comment by ianlancetaylor** [comment]
@davmaz Let's please take that part of the conversation to a forum (see https://golang.org/wiki/Questions) or a separate issue, rather than complicating this issue.  Thanks.

**Comment by davmaz** [comment]
Sorry Ian. I didn't know how to get back there. Thanks for the link.
________________________________
