### ISSUE TITLE
net/http: add Transport.MaxIdleConns limit

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15461]
There's been a long-standing TODO in net/http.Transport that says:

```go
type Transport struct {
....
    // TODO: tunable on global max cached connections
....
```

This bug is about that.

We already have `Transport.MaxIdleConnsPerHost`, but it's been requested by many (and again recently) that we have a `Transport.MaxIdleConns` for any host.

In the process, I also noticed that we're not aggressively removing cached connections when the peer server disconnects. We only lazily clean them up from the idle structures, which means we can hold onto memory for the bufio.Readers/Writers for a long time, wasting memory.

/cc @adg

**Comment by adg** [comment]
So `MaxIdleConns` would limit the total number of idle connections across all hosts? SGTM.
