### ISSUE TITLE
reflect: Name != "" for empty interface

### ISSUE THREAD

**Issue by crawshaw** [golang/go#15468]
At tip this program

```
package main

import (
        "fmt"
        "reflect"
)

func main() {
        fmt.Printf("%q\n", reflect.TypeOf((*interface{})(nil)).Elem().Name())
}
```

prints ```"interface {}"```
it should print ```""```: https://play.golang.org/p/4OmgYJ7NFt

**Comment by Mr4x** [comment]
@crawshaw it prints "". Check your playground again ;)

**Comment by crawshaw** [comment]
@Mr4x yes it prints "" in the playground, which is Go 1.6. At tip, it prints "interface {}". That's the bug.
