### ISSUE TITLE
cmd/compile: generate opname array

### ISSUE THREAD

**Issue by josharian** [golang/go#15462]
The comment in cmd/compile/internal/gc/opnames.go indicates that it was autogenerated by 'go tool dist', but that is clearly not the case now. (See CL 22495.) We should automatically generate it and document more clearly exactly how to do so. It is possible we should also generate it as part of make.bash.

Cc @davecheney

**Comment by mvdan** [comment]
I believe with https://github.com/golang/go/issues/16539 implemented we could easily reuse stringer for this, so I'm going to give that one a go and then use it here.
