### ISSUE TITLE
net: dnsConfig could be more usable as-is

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15473]
dnsConfig currently reflects the contents of /etc/resolv.conf, but that means some of the fields need to be repeatedly processed in dnsclient_unix.go before being used.  For example, in tryOneName we have to call JoinHostPort every time for each queried server, producing extra garbage, or convert cfg.timeout to time.Duration.  (\*dnsConfig).nameList could be simplified if we ensured search list entries always ended in a period.  Maybe there are more.

/cc @dpiddy @bradfitz

**Comment by dpiddy** [comment]
Sounds good. How about I start with changing cfg.timeout to a duration?

**Comment by mdempsky** [comment]
SGTM

**Comment by mdempsky** [comment]
This is as done as I had in mind. Can reopen or file new issues if anyone has ideas for more work.
