### ISSUE TITLE
x/net/http2: no public method to send PING frames

### ISSUE THREAD

**Issue by blixt** [golang/go#15475]
There is, as far as I can tell, no method for sending a PING frame to an open HTTP/2 connection right now. While in most cases there is no direct need to send PING frames, I've encountered multiple cases where it's important, lest you discard the connection and recreate it:

* [Apple's APNs][apns] HTTP/2 API is picky about what it receives and only supports PING frames as a way to ensure a healthy connection. Sending dummy requests may get your connection closed.
* Go's HTTP/2 lib chokes on idle sockets on Google Compute Engine VMs (see #14607 for some info). If the socket happens to be an HTTP/2 connection (which it often is in my case), being able to send PING frames would be a viable workaround for this issue.
* [Amazon's AVS HTTP/2 API][avs] expects a PING frame at least once per 10 minutes and it should be possible to send them. (Luckily, there's a workaround to call `/ping` in this case.)

So my suggestion is to somehow expose a way to send PING frames.

[apns]: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html
[avs]: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service

**Comment by zjx20** [comment]
I suggest that x/net/http2 should periodically send PING frames to the peer, and kick muted connections from the connection pool automatically. This feature should be off by default, and could be turned on by setting some kind of options.

**Comment by szpakas** [comment]
Like @blixt, I'm implementing APNS client and lack of access to PING frame is a bit of a show stopper for pushing to prod environment. It makes sense to have periodical ping as proposed by @zjx20, but it would be great to have also some kind of read-only access to connection stats for both PING and GOAWAY frames (to have connection behaviour in metrics).

@bradfitz: As I'm on a bit tight schedule and not sure can wait for the official fix, could You recommend some temporary solution which will allow access to ping on client side? I'm still quite green in GO and can't figure out how to extend the connection without actually forking x/net/http2 and making exported getter for Framer in http2ClientConn.

**Comment by tombergan** [comment]
PING frames are also useful for measuring the true end-to-end RTT, which you can't reliably measure at the transport level due to split TCP in cellular networks. I don't have a need for this feature, but if it's implemented, I would vote for a blocking API so the caller can time the RTT. Something like:

```go
func (s *h2connection) Ping(opaque uint64) (uint64, error)
```

If you need to PING periodically, you could always do so from a timer loop.

**Comment by bradfitz** [comment]
@tombergan, what is the return `uint16` in your example? If it's the data, it must match the ping opaque value in the sent frame, so it's redundant, no?

**Comment by tombergan** [comment]
That's right, I missed that the ACK must echo the opaque value from the original PING. The uint64 return value is not necessary.

**Comment by rs** [comment]
Any update on this?

I think this ping method should get a context as first argument to let the caller manage deadline and cancellation. Something like:

```go
func (cc *ClientConn) Ping(ctx context.Context) error
```

**Comment by rs** [comment]
Here is a proposal implementation: https://go-review.googlesource.com/#/c/29965/
