### ISSUE TITLE
cmd/compile/internal/gc/ssa: noisy vet output

### ISSUE THREAD

**Issue by robpike** [golang/go#15488]
Generated and hand-written files in this directory produce a lot of vet noise it would be easy to address.

A sample:

cmd/compile/internal/gc/ssa.go:4298: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4298: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4301: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4302: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4303: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4319: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4319: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4322: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4322: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4334: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
cmd/compile/internal/gc/ssa.go:4336: cmd/compile/internal/ssa.LocalSlot composite literal uses unkeyed fields
exit status 1
cmd/compile/internal/ssa/rewrite.go:145: unreachable code
cmd/compile/internal/ssa/rewriteAMD64.go:1542: unreachable code
cmd/compile/internal/ssa/rewriteAMD64.go:1558: unreachable code
cm

**Comment by dr2chase** [comment]
@randall77 did you want me to get this instead?

**Comment by randall77** [comment]
Already on it.
