### ISSUE TITLE
crypto/tls: Add support for SHA256 CBC ciphers

### ISSUE THREAD

**Issue by fatmcgav** [golang/go#15487]
I am currently attempting to use Golang v1.6 to interact with a 3rd party WS API.

Currently, they have a very limited set of supported ciphers:

> - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_AES_128_CBC_SHA256

Unfortunately none of these overlap with supported Go's supported ciphers. Therefore I just get an 'EOF' response currently. 

Putting it out on the golang-nuts mailing list, I got a response from [Phus Lu](https://groups.google.com/d/msg/golang-nuts/8sS9AXWfj-M/a40rs5LZAQAJ) which included a [commit](https://github.com/phuslu/go/commit/353372383f5bf452d3ca4a9425919cc423eb7e97) that adds the following ciphers:

> - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_AES_256_CBC_SHA256

Is there appetite to add support for these cipher suites to core?

**Comment by phuslu** [comment]
There're more and more TLSv1.2-only servers in these days. 
Hopefully go could have full TLSv1.2 ciphers support in future releases.

**Comment by phuslu** [comment]
Very happy to see fix in tip, is it possible to put it in go 1.7.1 ?
