### ISSUE TITLE
x/mobile: gomobile init not working

### ISSUE THREAD

**Issue by lxROKxl** [golang/go#15484]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
Windows 10
amd64

3. What did you do?
When I try to install gomobile it downloads after (go get golang.org/x/mobile/cmd/gomobile)
then when i attempt to use the command (gomobile init) it says 'gomobile' is not recognized as an internal or external command,
operable program or batch file.

4. What did you expect to see?
I expected it to initialize so i could use it

5. What did you see instead?
'gomobile' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dskinner** [comment]
You need to add `$GOPATH/bin` to system path, not `$GOPATH`. If you used the MSI installer as described in the [Getting Started](https://golang.org/doc/install) guide, this should have been done automatically for you.

**Comment by rakyll** [comment]
Make sure you have added $GOPATH/bin in your PATH.
