### ISSUE TITLE
cmd/link: should pass -Wl,-z,relro when linking with -buildmode=pie

### ISSUE THREAD

**Issue by mwhudson** [golang/go#15485]
By my reading of the code, we currently do all the prep in the linker to work with -zrelro when linking with -buildmode=pie, but we don't actually pass it to the linker.

@crawshaw ?

**Comment by crawshaw** [comment]
That's what it looks like. But then, how does anything work?

**Comment by ianlancetaylor** [comment]
Many GNU/Linux distros pass -z relro by default.
