### ISSUE TITLE
x/sys/unix: O_TMPFILE forgotten for arch=arm

### ISSUE THREAD

**Issue by wmark** [golang/go#15498]
`O_TMPFILE` has been forgotten for arch=arm. It's the only architecture where this constant is missing from x/sys/unix.

rel #7830

**Comment by wmark** [comment]
https://github.com/golang/sys/search?utf8=%E2%9C%93&q=O_TMPFILE

**Comment by tklauser** [comment]
Should be fixed by commit golang/sys@ea9bcade75cb975a0b9738936568ab388b845617 ([CL 37943](https://go-review.googlesource.com/37943))

**Comment by wmark** [comment]
Thanks!
