### ISSUE TITLE
net/http: optional Request-line length limit

### ISSUE THREAD

**Issue by markstgodard** [golang/go#15494]
Using net/http ReverseProxy server and encountering cases where it would be ideal to reject HTTP requests that exceed a **request-line** greater than some configurable value.

According to the RFC and request-line:

```
Request-Line   = Method SP Request-URI SP HTTP-Version CRLF
```
there is no predefined limit on the request line size, so the http server in go is doing the right thing.

However scenarios such as plain old invalid requests or potentially malicious requests with large payloads, it would be ideal to have the option to cap the **request-line** and return a 400 - Bad Request.

Any thoughts on potentially providing optional support to have a max length request line?

Cheers

**Comment by bradfitz** [comment]
Can't you just do it yourself in your `http.Handler` or `Handler` wrapper? We already give you the `Server.MaxHeaderBytes` knob as a DoS prevention mechanism.

**Comment by markstgodard** [comment]
Hi @bradfitz 

Thanks for the info.  

I originally thought that `Server.MaxHeaderBytes` was only limiting the reader of all the HTTP headers, but this would also include `Read-Line`?

I did a quick test and seems like it also is limiting the read-line

Thanks

**Comment by bradfitz** [comment]
I'll send a documentation change.

**Comment by markstgodard** [comment]
Thanks for clarifying! 👍  🍺

**Comment by markstgodard** [comment]
Hi @bradfitz 

One last question, would you be open to having a separate `Server.MaxRequestLineBytes` so that you could control the limits of request-line and headers independently?

The problem I am having right now is coming up with a value that works for both headers vs. request line.

I'd also be happy to submit a contribution to help.

Cheers

**Comment by bradfitz** [comment]
No, we have enough knobs. I don't think there's enough of a use case to warrant a new knob.

**Comment by markstgodard** [comment]
Fair enough
Cheers
