### ISSUE TITLE
cmd/compile/internal/gc: ssa.go contains some Intel-flavored idioms (and maybe an error)

### ISSUE THREAD

**Issue by dr2chase** [golang/go#15492]
Cherry spotted this, came to me for a sanity check.  In insertWBmove and insertWBstore this code appears:

```
	flagaddr := s.newValue1A(ssa.OpAddr, Ptrto(Types[TUINT32]), aux, s.sb)
	// TODO: select the .enabled field. It is currently first, so not needed for now.
	// Load word, test byte, avoiding partial register write from load byte.
	flag := s.newValue2(ssa.OpLoad, Types[TUINT32], flagaddr, s.mem())
	flag = s.newValue1(ssa.OpTrunc64to8, Types[TBOOL], flag)
```

Note the 32-bit-load followed by a Trunc64to8 -- as far as we know, not a bug, but not quite what was intended.  The Intel flavoring is the wide load followed by truncate; on other platforms a load byte is going to work just fine because they lack the partial-register craziness.

Since this is in writebarrier code, we actually care.

**Comment by randall77** [comment]
That should be Trunc32to8.

We could just use all 32-bit operations on amd64, no reason to use the byte instructions.
  MOVL foo(SB), AX
  TESTL AX, AX
  JNE dowritebarrier

**Comment by josharian** [comment]
Related (alternative fix): #15245

**Comment by cherrymui** [comment]
Thanks @randall77 and @josharian. As we may have alternative fix, I leave it unchanged on amd64 for now, except Trunc64to8 -> Trunc32to8.

**Comment by randall77** [comment]
I believe this is fixed.  On all archs we now use 32-bit operations.
