### ISSUE TITLE
x/build: email the author who broke the build

### ISSUE THREAD

**Issue by rakyll** [golang/go#15506]
Builders don't email the author of the committer when a build is broken. This results in having broken builds for a long enough time period until someone notices the broken build and notifies the original author. The issue could have been easily improved if a notification email was sent out to the author who last broke build.

/cc @bradfitz @adg

**Comment by ianlancetaylor** [comment]
We used to do something like this but it was incredibly annoying because the builders are flaky.  Perhaps we could start with a check that no similar error occurred in the last 100 builds or so, and only notify if the failure appears to be new.

**Comment by ianlancetaylor** [comment]
Come to think of it, we should also delay any notification until after we've confirmed that the next build fails in the same way.

**Comment by bradfitz** [comment]
Dup of #12509
