### ISSUE TITLE
cmd/pprof: very fat arrows in output

### ISSUE THREAD

**Issue by jmhodges** [golang/go#15500]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

go version go1.6.2 darwin/amd64
1. What operating system and processor architecture are you using (`go env`)?

darwin/amd64
1. What did you do?

Ran `go tool pprof -base ./howsmyssl-1.heap -inuse_objects` and then `web`. Then also, `-png` from the command line. This is with graphviz 2.38.0_3 installed via MacPorts.

When doing so, my arrows are often very fat, sometimes to the point of obscuring the boxes they connect.

The most egregious of these I caught as an SVG and is here (github won't allow the upload directly on this ticket): https://gist.github.com/jmhodges/72869f007b58f527595766487add4af0

Here is a less obvious example that I managed to capture as a PNG. ![fairlyfatarrows](https://cloud.githubusercontent.com/assets/598/14938761/47319b44-0ee3-11e6-905b-f00e525144b2.png)

**Comment by bradfitz** [comment]
That's kinda neat, actually. I'd never seen that.

**Comment by robpike** [comment]
That's working as intended, I think. Dominant flow is indicated by much ink.

**Comment by jmhodges** [comment]
Here's a screenshot of the SVG. It demonstrates the obscuring of text.

![screen shot 2016-04-30 at 4 52 19 pm](https://cloud.githubusercontent.com/assets/598/14939260/f170fefa-0ef3-11e6-8bc1-cee56934c8d3.png)

**Comment by bradfitz** [comment]
Yeah, that might be a little excessive.

**Comment by jmhodges** [comment]
Yeah, once you start looking, you notice the even the arrows in the PNG overlap the "4xxxxx"s right down the middle of the screen, which could suck if they were really "14xxxx" or whatever. So a max thickness would get this pretty far, but it might also need some overlap prevention depending on how the arrows are laid out with the text.

**Comment by griesemer** [comment]
The good news is there's some well identified serious hot spot... :-)

**Comment by ALTree** [comment]
@jmhodges can you reproduce this with go1.9 (after the pprof update from upstream)?
