### ISSUE TITLE
x/exp/io: introduce NotSupportedErr

### ISSUE THREAD

**Issue by rakyll** [golang/go#15505]
io packages should export an `NotSupportedErr` and enforce driver implementations to return this value as an error if the driver doesn't support the protocol properly.

Given the number of protocol implementations and the fragmentation in implementations and target boards, users can fallback to another strategy or turn off certain features dynamically if the driver doesn't provide full support.

**Comment by ALTree** [comment]
Since `x/exp/io` is no longer developed and essentially frozen, I'm closing this issue.
