### ISSUE TITLE
sql.Open() does not return an error on failure ?

### ISSUE THREAD

**Issue by Sve1nn** [golang/go#15502]
Hey guys, I ran into something strange today.. I might be doing something wrong since it's my second day of programming in GO, but I figured I'd post this anyways. ( sorry if it is a duplicate )

1. What version of Go are you using (`go version`)?
**go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64**

2. What operating system and processor architecture are you using (`go env`)?
**GOARCH="amd64"
GOBIN="/home/vagrant/work/code/go-server/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vagrant/work/code/go-server"
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/lib/gccgo/tool"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"**

3. What did you do?
Repository: **https://gitlab.com/Sve1nn/go-web-framework**
File/ Line: **https://gitlab.com/Sve1nn/go-web-framework/blob/master/sql.go#L45**
Error trigger: **when loading the root route "/"**
Description: **The sql.Open() func does NOT return any kind of error. Not when credentials are  wrong or if the SQL server is simply offline. The funny part is that it DOES require you to either set the   error or throw the error into the bit bucket ( _ )**

4. What did you expect to see?
**Some sort of database connection error.**

5. What did you see instead?
**nil / Nothing**

P.s. THANK YOU FOR GO. This language has been needed for a long time. 
P.s.s. You hiring ? :)

**Comment by dominikh** [comment]
`sql.Open` doesn't actually talk to the database yet. It initializes a connection pool. Upon making a query, a new connection will be established. If you want to ensure that the credentials are correct, you can call the Ping method. Also see the following part of the documentation of Open:

> Open may just validate its arguments without creating a connection
> to the database. To verify that the data source name is valid, call
> Ping.

**Comment by Sve1nn** [comment]
That makes more sense. 

Wouldn't it be kind of handy to call Ping automatically within Open for an error return ? 

Or at least remove the need to set an error to the _ ?

**Comment by OneOfOne** [comment]
@Sve1nn pretty much a design mistake that stuck around because of the [go1compat](https://golang.org/doc/go1compat).

Also you're using a rather old/outdated version of Go/gcc, and while upgrading won't solve your specific issue, it's still a good idea.

**Comment by bradfitz** [comment]
Whether handy or not, it's probably not a change we could make at this point for compatibility reasons. Sorry. :-/

**Comment by bradfitz** [comment]
@OneOfOne, I wouldn't be so quick to call it a design mistake. It was a decision.

**Comment by Sve1nn** [comment]
@bradfitz I get where you are coming from, it's only a minor thing anyways. Thanks for the quick reply !

**Comment by Sve1nn** [comment]
@bradfitz is google / golang hiring software engineers at this point in time :) ?

**Comment by bradfitz** [comment]
@Sve1nn, Google is always hiring. Go generally hires from within Google, unless you're a world-class expert in an area we really need help with in Go. If you just want to hack on Go stuff, though, there are plenty of places you can do that outside of Google. There is regular discussion on the golang-nuts mailing list about people hiring for Go.

**Comment by Sve1nn** [comment]
@bradfitz well, I'm certainly no world class expert on anything, but GO seems to be something that will be here to stay and I would love to work on the language it self :) 

Working for Google wouldn't be to shabby either. 

Would you mind if I shot you an email with a few questions on google and recruitment ? :)
