### ISSUE TITLE
build: openbsd-arm build is failing

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15511]
Joel,

@4a6f656c, can you update your openbsd-arm builder to set the HOME environment variable?

It's been failing for quite some time with:

```
--- FAIL: TestCurrent (0.00s)
	user_test.go:24: Current: user: Current not implemented on openbsd/arm (got &user.User{Uid:"1001", Gid:"1001", Username:"gopher", Name:"", HomeDir:""})
FAIL
FAIL	os/user	0.079s
```

A few of the other builders were fixed by setting the HOME variable. (You might also have to update the builder binary?)

**Comment by 4a6f656c** [comment]
@bradfitz - fixed, just needed to update the builder.

**Comment by bradfitz** [comment]
Thanks!
