### ISSUE TITLE
encoding/asn1:  add utility function for parsing object-identifier strings

### ISSUE THREAD

**Issue by phayes** [golang/go#15523]
The asn1 package is fairly narrowly focused on marshaling / unmarshaling DER data.  

I would like to propose incrementally improving the asn1 package to be more generally useful for working with all data related to the ASN.1 standard.  To start, I have created a new function `NewObjectIdentifier` to parse the string representation of a ASN.1 Object Identifier. 

```
// NewObjectIdentifier creates an object identifier from it's string representation.
// Supports ASN.1 notation and dot notation. OID-IRI notation is not supported.
func NewObjectIdentifier(oid string) (oi ObjectIdentifier, err error) {
```

I have created a PR for it here as a preview: https://github.com/phayes/go/pull/1/files

If the go authors are interested in this, I'll roll it into a proper gerrit change-request. If they are not interested, I'll create a new 3rd party package.

**Comment by minux** [comment]
I'd suggest you start with a go-gettable package first, and then
we'll see if we could add a x/crypto/asn1 package. I don't think
we want to extend encoding/asn1 to handle everything about
ASN.1.

**Comment by phayes** [comment]
OK that sounds fine @minux .   Do you want to close this ticket then?

**Comment by minux** [comment]
Yes, please if you agree that it's better to add those
functionality to a separate package.

**Comment by phayes** [comment]
Well, I actually think it's better to integrate into the `encoding/asn1` package (or else I wouldn't have filed this issue!).  However, having said that, I respect your decision. 

Closing this ticket.
