### ISSUE TITLE
cmd/compile: statically initialize some interface values

### ISSUE THREAD

**Issue by josharian** [golang/go#15528]
The code in #15520 generates a giant init function, aimed at setting up an array of interface values. The components are, however, entirely static: Static itab and static data. We should thus be able to create the entire array statically instead of making an init function.

cc @walken-google @randall77 @crawshaw

**Comment by randall77** [comment]
Yes, please.  The more we can do at link time the better.

**Comment by josharian** [comment]
image/color/palette appears to be a good test case for this in the stdlib.

**Comment by josharian** [comment]
CL prepared for 1.8. [Unstable url](https://github.com/josharian/go/commit/ac16414618d49351dc99446f6b6034046efedfaf) for those who want to peek.
