### ISSUE TITLE
IPto4() in package net is not returning nil for IPv6 address.

### ISSUE THREAD

**Issue by kspessard** [golang/go#15529]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/kspessard/Go"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -gno-record-gcc-switches -fdebug-prefix-map=/tmp/go-build103771964=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
https://play.golang.org/p/uKxvfsPPvu

4. What did you expect to see?
Since function ip.To4() is supposed to return nil if ip is IPv6, I expected to see....

```
    address 2001:abc:abc::/128 is IPv6    <------  This is correct.
    address 1.1.1.1/32 is IPv4
```

5. What did you see instead?

```
    address 2001:abc:abc::/128 is IPv4    <------  This is incorrect.
    address 1.1.1.1/32 is IPv4
```

**Comment by dominikh** [comment]
`if ip.To4 != nil` should be `if ip.To4() != nil`. You're comparing a function value against nil, not the return value of the function.
