### ISSUE TITLE
cmd/compile: ppc64x rounding large uint64 to float64 cast incorrectly

### ISSUE THREAD

**Issue by mundaym** [golang/go#15539]
Seen in TestFP/TestFp on the builder: https://build.golang.org/log/d9a463f06b55a67d70805a7bcb1cd18eed65d3ec

`uint64` to `float64` casts should round to nearest with ties to even. However on ppc64 large `uint64` values are shifted right by 1 so that they can be reinterpreted as `int64` values (so that they can be fed into the `fcfid` instruction). Unfortunately this truncates the original value, possibly (as in this test I think) resulting in a tie where there was none before.

Can ppc64 use the `fcfidu` instruction instead?

**Comment by mundaym** [comment]
cc @laboger @dr2chase

**Comment by minux** [comment]
I suspect the fix doesn't support ppc970, reopen the issue.

**Comment by mundaym** [comment]
It probably doesn't since as far as I can tell `fcfidu` was only added in 2010... One option is to use `fcfid` for every type except `uint64`. Then for `uint64` we could use `fcfidu` when in little endian mode (as you suggested in the CL) and use bitwise/integer instructions to do the cast manually in big endian mode (or something more clever).

I don't really like the idea of keeping the code the way it is on big endian machines. If a big endian builder is added it won't pass the tests.

**Comment by mundaym** [comment]
Based on Lynn and Russ' comments in golang-dev and in the CL I'm going to close this issue again for now.
