### ISSUE TITLE
Add special comments or a flag to force "go generate" during a "go get"

### ISSUE THREAD

**Issue by alonsovidales** [golang/go#15536]
**Problem statement:**
We are working on the [Go API for TensorFlow](https://github.com/tensorflow/tensorflow/pull/1771).
The problem is that this package depends on the tensorflow shared libraries, and in order to compile this libraries we depend on "go generate", but since there is no way to run "go generate" during the "go get" this package can't be go-gettable. I came up with this ugly solution:
```sh
$ TF_REPO=github.com/tensorflow/tensorflow/tensorflow/contrib/go/;go get $TF_REPO || (go generate $TF_REPO && go get $TF_REPO)
```
First I use the "go get" to clone the repo, if it is already installed, that's it, but if not it executes the "go generate" and the "go get" once again.

I think that it would be a good idea to add a way to execute "go generate" while executing "go get", something like a special comment on the package or so. This could be useful on situations like the described below as also on other cases like to generate protobuf files or any other code necessary to get the package so we don't need to upload them to the repository.

**Possible solutions:**

It could be nice to have a special comment like:
```go
// go:get generate
```
or something like that in the package in order to force the execution of "go generate" before "go get".

Another option could be to add a `-g` to "go get" but this could be more confusing for the users since they would need to know in advance that the flag is required to get the package.

**Comment by alonsovidales** [comment]
I can't add the `proposal` label sorry, I think that is because I have no permissions, could please someone add the label to the ticket?

**Comment by kostya-sh** [comment]
What are the reasons for not committing the generated code to the repository which I beleive is the recommended way of using go generate?

Looking at https://github.com/alonsovidales/tensorflow/blob/go_bindings_tensors/tensorflow/contrib/go/gen.go I have the following questions/comments:

- What if I don't have protoc installed on my PC or have an incompatible version?
- I don't want to install a random shared library to my /usr/lib when I go get a package (`go:generate sh -c "sudo cp ../../../bazel-bin/tensorflow/libtensorflow.so /usr/lib/"`)
- Generally I don't want to execute any untrusted code from the internet automatically

**Comment by alonsovidales** [comment]
I agree with you, but the other options could be to add a MakeFile, Bazel, or any other system to compile the libs and install them with the same problems, when you install a package with apt-get the postinstall script will execute code on your machine, it would be nice don't have this dependency but for this project I think that is not possible.

**Comment by minux** [comment]
One of the design goal of go:generate is specifically that it must be
invoked separately.

We don't want arbitrary command to run when you simply go get a package
(even go build doesn't run arbitrary commands.)

I think you need to find another solution to your problem, unfortunately.

**Comment by alonsovidales** [comment]
Ok, I was also trying to be 100% sure that it was impossible to do this just with the current implementation of `go get`, I agree with you that is better to don't execute code during a `go get`.
If with a `go get` is not possible we are going to try to find any other way, perhaps Bazel or just go with the `go get || (go build && go get)` option.

Thanks a lot!
