### ISSUE TITLE
gccgo: duplicate symbols under specific package and package_test conditions

### ISSUE THREAD

**Issue by tamird** [golang/go#15547]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ gccgo go version
go version go1.6.1 gccgo (GCC) 6.1.0 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ gccgo go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tamird/src/go"
GORACE=""
GOROOT="/opt/gccgo"
GOTOOLDIR="/opt/gccgo/libexec/gcc/x86_64-pc-linux-gnu/6.1.0"
GO15VENDOREXPERIMENT="1"
CC="/opt/gccgo/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/opt/gccgo/bin/g++"
CGO_ENABLED="1"
```

3. What did you do?
```
$ gccgo go test github.com/tamird/gccgo_duplicate_symbols
```

4. What did you expect to see?
```
ok  	github.com/tamird/gccgo_duplicate_symbols	0.002s
```

5. What did you see instead?
```
# testmain
/usr/bin/ld.gold: error: /home/tamird/src/go/pkg/gccgo_linux_amd64/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): multiple definition of 'github_com_tamird_gccgo_duplicate_symbols.AIe1e$hash$descriptor'
/usr/bin/ld.gold: $WORK/github.com/tamird/gccgo_duplicate_symbols/_test/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): previous definition here
/usr/bin/ld.gold: error: /home/tamird/src/go/pkg/gccgo_linux_amd64/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): multiple definition of 'github_com_tamird_gccgo_duplicate_symbols.AIe1e$equal$descriptor'
/usr/bin/ld.gold: $WORK/github.com/tamird/gccgo_duplicate_symbols/_test/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): previous definition here
/usr/bin/ld.gold: error: /home/tamird/src/go/pkg/gccgo_linux_amd64/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): multiple definition of 'github_com_tamird_gccgo_duplicate_symbols.Sup$descriptor'
/usr/bin/ld.gold: $WORK/github.com/tamird/gccgo_duplicate_symbols/_test/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): previous definition here
/usr/bin/ld.gold: error: /home/tamird/src/go/pkg/gccgo_linux_amd64/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): multiple definition of 'github_com_tamird_gccgo_duplicate_symbols.Sup'
/usr/bin/ld.gold: $WORK/github.com/tamird/gccgo_duplicate_symbols/_test/github.com/tamird/libgccgo_duplicate_symbols.a(_go_.o): previous definition here
collect2: error: ld returned 1 exit status
FAIL	github.com/tamird/gccgo_duplicate_symbols [build failed]
```

**Comment by mwhudson** [comment]
I think I fixed this in 12e3b184f0fe15787be7f0837d2b168a4fbe60be, can you check tip?

**Comment by tamird** [comment]
Sure, how? Do I need to check out gcc from tip and recompile?

**Comment by mwhudson** [comment]
Oh, sorry, you're using the go tool from gccgo. I *think* the fix is upstream there too, but maybe you should look in the commit history first before starting the build. The patch is in the gccgo-6 package in Ubuntu 16.04, at least.

**Comment by tamird** [comment]
Nope, gcc at HEAD doesn't appear to contain this patch.

**Comment by mwhudson** [comment]
Paging @ianlancetaylor then, do you think it's worth bringing that patch into tip before the merge for 1.7? And/or fixing it on the gcc-6-branch?

**Comment by tamird** [comment]
@ianlancetaylor ping?

**Comment by ianlancetaylor** [comment]
Michael's patch is now in the gofrontend repository and is in GCC mainline.  It will be in the GCC 7 release.  Your test passes with GCC mainline.

I'm willing to listen to arguments otherwise, but right now I don't think this is worth adding to the GCC 6 branch.  So, closing.

**Comment by tamird** [comment]
Isn't GCC 7 still 8 months out? I'd like to see this get into a GCC release before then, and it looks like the next GCC point release might be about 2 months out. What do you think?

**Comment by ianlancetaylor** [comment]
Can you send me a patch against GCC 6 branch that fixes the problem?

**Comment by tamird** [comment]
@ianlancetaylor in what repository? `gofrontend` doesn't seem to have any branches besides `master`. Are you talking about the `gcc` repository? How should I send the patch?

**Comment by tamird** [comment]
FWIW, here's the patch in the GCC repo: https://gist.github.com/tamird/4b5a9481bfa6432f9672c652b220d11e

**Comment by ianlancetaylor** [comment]
Backported to GCC 6 branch.
