### ISSUE TITLE
cmd/compile: crash during import

### ISSUE THREAD

**Issue by griesemer** [golang/go#15548]
Given the files
a.go:
```
package a

import (
	_ "./b"
	_ "./c"
)
```
b.go:
```
package b

import "./c"

func B(c.T) {}
```
c.go:
```
package c

type I0 interface {
	I1
}

type T struct {
	I1
}

type I1 interface {
	M(*T) // removing * makes crash go away
}
```
The compile
```
go tool compile c.go && go tool compile b.go && go tool compile a.go
```
dies in import:
```
a.go:5: inconsistent definition for type c.I1 during import
	interface { M(*c.T) } (in "/Users/gri/bug/b")
	interface { M(*<T>) } (in "/Users/gri/bug/c")
```

**Comment by griesemer** [comment]
cc @robpike

**Comment by robpike** [comment]
I0 isn't used anywhere. Can it be removed and still trigger the crash?

**Comment by mdempsky** [comment]
In a standard go workspace, the files would be laid out

    a.go
    b/b.go
    b/c/c.go
    c/c.go

So a.go's "./c" import would import a different package than b/b.go's "./c" import.

Does bimport need to know that when it's loading a package for "x/y" and it sees a reference to a package "./z", that we need to rewrite it to "x/y/z"?

**Comment by griesemer** [comment]
I believe the code is correct. The issue is the type equality check in
bimport.go is called before a type is fully set up (too early). It's really
just an assertion and not required unless we have a true bug in the
importer.

That is, the fix is to delay the check. I think if you comment out the
Fatal after the equality test all will work fine.

- Gti
