### ISSUE TITLE
gccgo: runtime/trace not available in gcc-6.1.0

### ISSUE THREAD

**Issue by tamird** [golang/go#15544]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

```
$ gccgo go version
go version go1.6.1 gccgo (GCC) 6.1.0 linux/amd64
```
1. What operating system and processor architecture are you using (`go env`)?

```
$ gccgo go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tamird/src/go"
GORACE=""
GOROOT="/opt/gccgo"
GOTOOLDIR="/opt/gccgo/libexec/gcc/x86_64-pc-linux-gnu/6.1.0"
GO15VENDOREXPERIMENT="1"
CC="/opt/gccgo/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/opt/gccgo/bin/g++"
CGO_ENABLED="1"
```
1. What did you do?

```
$ cat main.go
package main

import _ "runtime/trace"

func main() {
fmt.Println("hello world")
}
$ gccgo go run main.go
```
1. What did you expect to see?

```
hello world
```
1. What did you see instead?

```
main.go:3:8: cannot find package "runtime/trace" in any of:
    /opt/gccgo/src/runtime/trace (from $GOROOT)
    /home/tamird/src/go/src/runtime/trace (from $GOPATH)
```

**Comment by tamird** [comment]
@ianlancetaylor triage ping. This also affects gcc mainline.

**Comment by ianlancetaylor** [comment]
This is going to require updating the gccgo runtime package to 1.7.  I've started working on it but it will take a while.  It's definitely not going to happen for GCC 6.

**Comment by tamird** [comment]
@ianlancetaylor looks like this was initially done in https://github.com/golang/gofrontend/commit/9401e714d690e3907a64ac5c8cd5aed9e28f511b#diff-2eab022867c5cfa1e28487d9bf4b836f?

**Comment by ianlancetaylor** [comment]
Yes, current gccgo has the runtime/trace package.
