### ISSUE TITLE
export os/exec prefixSuffixSaver and friends

### ISSUE THREAD

**Issue by sb10** [golang/go#15555]
1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

This is not a bug, but a feature request:

I am using os/exec and really like Output()'s ability to capture STDERR while keeping only the head and tail of it. However, I want to apply this to STDOUT as well, to capture my own number of bytes, and I want to have all this with my own Start() and Wait() calls.

For now I have done:

    cmd := exec.Command(...)
    cmd.Stderr = &prefixSuffixSaver{N: 4096}
    cmd.Stdout = &prefixSuffixSaver{N: 4096}
    cmd.Start()
    ...
    cmd.Wait()
    stdErr := cmd.Stderr.(*prefixSuffixSaver).Bytes()
    stdOut := cmd.Stdout.(*prefixSuffixSaver).Bytes()

But since prefixSuffixSaver is not exported, I've had to just copy and paste all that related code in to my own package.

prefixSuffixSaver is generally useful and non-trivial, so it would be great if this functionally was exposed publicly.

**Comment by minux** [comment]
prefixSuffixSaver is not within the scope of os/exec, so I don't think we
should
export it. If you find it useful, just copy it and (optionally) make a go
gettable
package.

**Comment by sb10** [comment]
Yes, I could do that.

My preference would be that the author find an appropriate golang package to put it in and export it from there, so it's built in to the language, esp. since the author has commented in the code that he might have a better way of implementing it in the future.

**Comment by bradfitz** [comment]
Sorry, I have no desire to export that code. I agree you should just copy it to a new repo and then you can maintain it instead of me. :-)
