### ISSUE TITLE
gccgo: mishandling of contrived iota use case

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15551]
This program should print 1, but with gccgo-4.8 it prints 4.  (Sorry, I don't have a more recent version to test with.)

    package main
    
    import (
            "fmt"
            "unsafe"
    )
    
    const (
            _ = unsafe.Sizeof(func() int {
                    const (
                            _ = 1
                            _
                            _
                    )
                    return 0
            }())

            y = iota
    )

    func main() {
            fmt.Println(y)
    }

**Comment by mdempsky** [comment]
See also #15550.

**Comment by mwhudson** [comment]
Same with "gccgo (Ubuntu 6.0.1-0ubuntu1) 6.0.0 20160414 (experimental) [trunk revision 234994]"

**Comment by thanm** [comment]
@mdempsky  -- judging from the comments on [https://github.com/golang/go/issues/15550](https://github.com/golang/go/issues/15550) gccgo is actually correct -- can this issue be closed out?

**Comment by mdempsky** [comment]
@thanm If you strictly interpret the Go spec, then printing 4 like gccgo does is technically correct.  But part of the discussion on #15550 is that the Go spec's wording is incorrect, because it doesn't consider that const declarations can be nested.
