### ISSUE TITLE
misc/cgo/testcarchive: TestSigaltstack flake on darwin-386

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15576]
Recent flaky test:

https://build.golang.org/log/bedf20ab4fc42f711d6379688739cbc2575642fd
```
##### misc/cgo/testcarchive
--- FAIL: TestSigaltstack (1.08s)
	carchive_test.go:438: pthread_kill: No such process
	carchive_test.go:439: exit status 1
FAIL
2016/05/06 08:41:15 Failed: exit status 1
```

**Comment by ianlancetaylor** [comment]
CC @eliasnaur 

All failures are since https://golang.org/cl/22841 .

**Comment by eliasnaur** [comment]
I don't think CL 22841 can be blamed. There are two similar darwin/386 flakes before it, on the same day (May 4th):

https://build.golang.org/log/3ece6e277d2eac6f12f970f4193682117c9500bd
https://build.golang.org/log/6979ce1335dd7dde1e246beacbb090bcfb502498

and once again, a few days before that:

https://build.golang.org/log/d20fc6d4b6336c03743e918a1dd108ac31a92bff

You also say "failures" in plural. The only other darwin/386 flake I see after my CL is

https://build.golang.org/log/6427c7946ca0d9770e4ff54c8986eb8a901a4fcd

which is in the std lib, not in testcarchive.

Finally, the darwin/386 builder seems flaky in general. Here is a third kind of recent flake:

https://build.golang.org/log/abbe46f70a9e4a1e6db900d12c66552506faee8a

**Comment by bradfitz** [comment]
The darwin/386 builders are the same builders that run darwin/amd64, btw.

**Comment by ianlancetaylor** [comment]
@eliasnaur sorry for the false pointer.

**Comment by eliasnaur** [comment]
Sorry is hardly necessary; while I was deflecting blame, you fixed the bug :)
