### ISSUE TITLE
all: copy & paste errors in tests

### ISSUE THREAD

**Issue by dominikh** [golang/go#15570]
The following lines of code either have copy & paste errors or redundant comparisons:

```
/usr/lib/go/src/encoding/gob/codec_test.go:1256:5: identical expressions on the left and right side of the '!=' operator
/usr/lib/go/src/encoding/gob/codec_test.go:1283:5: identical expressions on the left and right side of the '!=' operator
/usr/lib/go/src/net/conn_test.go:46:6: identical expressions on the left and right side of the '||' operator
/usr/lib/go/src/net/mockserver_test.go:228:5: identical expressions on the left and right side of the '||' operator
```

All position information are for Go 1.6.2

**Comment by josharian** [comment]
@dominikh how did you find these? I wonder whether vet should warn about x BINARY OP x, when x is not a float.

**Comment by dominikh** [comment]
@josharian It's a rule for [staticcheck](https://github.com/dominikh/go-staticcheck) that I'm currently working on. It might be nice in vet. BINARY OP shouldn't be `+` or `*` though, and `x` probably shouldn't be function calls.

**Comment by josharian** [comment]
staticcheck looks awesome. Filed #15586 for whether some of this should go into vet.
