### ISSUE TITLE
runtime: using CryptGenRandom to generate randomness slows process startup

### ISSUE THREAD

**Issue by jstarks** [golang/go#15589]
In Windows's `runtime.getRandomData()`, [CryptGenRandom](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942(v=vs.85).aspx) is used to retrieve random data from the system random number generator. Using this API causes initialization of the entire Windows crypto API surface, which is expensive and probably usually otherwise unnecessary.

The recommended way to fix this is to use [BCryptGenRandom](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375458(v=vs.85).aspx) with a `NULL` provider and `BCRYPT_USE_SYSTEM_PREFERRED_RNG`. This is what .NET Core does on Windows, for example. However, this is only supported on Windows 7 and newer OSes.

A slightly faster approach and one that works on XP is to use [RtlGenRandom](https://msdn.microsoft.com/en-us/library/windows/desktop/aa387694(v=vs.85).aspx). Although this function is not well-documented, it uses the same RNG as the other functions, it has been recommended by Microsoft in [a blog](https://blogs.msdn.microsoft.com/michael_howard/2005/01/14/cryptographically-secure-random-number-on-windows-without-using-cryptoapi/), and it is used in other open source projects such as Chromium and Firefox.

I have a prototype (38633e27df4ce0d1e3f95bcefe3bae330ff66c0d) of that uses `RtlGenRandom` that reduces process startup time from 22ms to 20ms on my machine.

If this approach seems worthwhile then I can send out a code review.

**Comment by alexbrainman** [comment]
Use of RtlGenRandom sounds good to me. Please send a code review. But it won't get submitted until after go1.7 is released - the tree is frozen at this moment. Thank you.

Alex
