### ISSUE TITLE
godoc: Doesn't handle repos with no master

### ISSUE THREAD

**Issue by bep** [golang/go#15580]
@kr has created a "left-pad npm like" situation by deleting the master branch in https://github.com/kr/text -- that works in Go 1.6, but not in Go 1.5.4.

I wish that fix had been backported, but you should at least have a look at the logic behind:

https://godoc.org/github.com/kr/text

(I assume godoc.org is backed by you)

**Comment by minux** [comment]
It also breaks pre Go 1.6 go get, so I'm not sure if we should encourage
that.

What's the rationale behind deleting the master branch?

**Comment by bep** [comment]
>What's the rationale behind deleting the master branch?

Vanity? But it sure gets people to look hard at vendoring.

**Comment by kr** [comment]
Please see https://github.com/golang/gddo/issues/405

**Comment by bep** [comment]
@kr not sure what point you are trying to make here ...

... but if you can confirm that you have no intention to reintroduce the master branch, I will have to fork your repo and try to patch up my stuff.

**Comment by cespare** [comment]
It seems reasonable that tools should use the default branch even if it's not master. Since the go tool already does and there's a separate gddo issue, I think there's nothing to be done here and this issue should be closed.
