### ISSUE TITLE
cmd/compile: investigate SSA stack size regressions

### ISSUE THREAD

**Issue by josharian** [golang/go#15597]
For the most part, SSA generates smaller stacks than the old backend, but not always. This issue is to (a) document an easy way to find such regressions and (b) serve as a reminder to investigate some of them to see whether there are reasonable improvements available.

First, apply this diff, so that -S prints just package, function, and stack size:

``` dif
diff --git a/src/cmd/internal/obj/objfile.go b/src/cmd/internal/obj/objfile.go
index a1fdee6..ea13412 100644
--- a/src/cmd/internal/obj/objfile.go
+++ b/src/cmd/internal/obj/objfile.go
@@ -114,6 +114,7 @@ import (
        "log"
        "path/filepath"
        "sort"
+       "strings"
 )

 // The Go and C compilers, and the assembler, call writeobj to write
@@ -310,6 +311,11 @@ func (w *objWriter) writeRefs(s *LSym) {

 func (w *objWriter) writeSymDebug(s *LSym) {
        ctxt := w.ctxt
+       if s.Type != STEXT {
+               return
+       }
+       fmt.Fprintf(ctxt.Bso, "STACK %s.%s %d\n", ctxt.Pathname, strings.TrimPrefix(s.Name, `"".`), s.Locals)
+       return
        fmt.Fprintf(ctxt.Bso, "%s ", s.Name)
        if s.Version != 0 {
                fmt.Fprintf(ctxt.Bso, "v=%d ", s.Version)
```

Then

``` bash
$ go build -a -gcflags="-S" std 2>&1 | sort > ssa.stacksize
$ go build -a -gcflags="-S -ssa=0" std 2>&1 | sort > nossa.stacksize
$ diff --suppress-common-lines --width 10000 --side-by-side nossa.stacksize ssa.stacksize | awk '{if ($2!=$6) {next} if(($7==0) && ($3 ==0)) {next} if ($7<=$3) {next} print $3/$7" "$2" "$3" -> "$7}' | sort -n
```

This is using OS X's diff. This prints four columns: old stack size / new stack size, package+function, old stack size, new stack size.

A few sample lines, pulled from a few places in the output:

```
0 crypto/cipher.fastXORBytes 0 -> 8
0 image.yCbCrSize 0 -> 8
0 math/big.shlVU_g 0 -> 8
0 math.qzero 0 -> 96
0 testing.(*B).add 0 -> 136
0.0248963 image/color/palette.init 48 -> 1928
0.0444444 vendor/golang.org/x/net/http2/hpack.init 112 -> 2520
0.75 sort.doPivot 96 -> 128
```

Full output at commit e6ec82067a9068c93db6e7041017060a1c863452 is at https://gist.github.com/josharian/9919226c603e9c90a367738962241a06.

cc @randall77 @dr2chase

**Comment by randall77** [comment]
I'm going to close this, it's not really actionable any more.
It would still be nice to shrink stack frames as much as we can.  But this method of investigation no longer works :(
