### ISSUE TITLE
website: windows download page gives bad advice

### ISSUE THREAD

**Issue by xobs** [golang/go#15598]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
Windows 8.1, amd64

3. What did you do?
Download Go for the first time, to see what the language is about.

4. What did you expect to see?
Useful information on setting up and using Go.

5. What did you see instead?

Most of the advice on the website is downright wrong.  For example, the website says to set GOPATH:

    C:\> set GOPATH=%HOME%\work

On Windows, following this advice will lead to a go installation that does not work.  First, the variable is named %HOMEPATH%, and second, the variable is relative so it should be %HOMEDRIVE%\%HOMEPATH%.

After manually correcting GOPATH, I tried building the "Hello, world!" example, also from the page.

The page then illustrates how to build the .go file, using "go install" (?).  This does not work:

    C:\Users\Sean\Code\go\hello>go install github.com/user/hello
    can't load package: package github.com/user/hello: cannot find package "github.com/user/hello" in any of:
            C:\Go\src\github.com\user\hello (from $GOROOT)
            C:\Users\Sean\Code\go\src\github.com\user\hello (from $GOPATH)
    
    C:\Users\Sean\Code\go\hello>

As a brand-new user, this is very confusing.

**Comment by alexbrainman** [comment]
> the website says to set GOPATH:
> 
> C:\> set GOPATH=%HOME%\work

Where does it actually say that? Can you point me in the right direction. Thank you.

Alex

**Comment by minux** [comment]
https://golang.org/doc/install will show the windows specific content
if you download the windows installer.

try accessing
https://golang.org/doc/install?download=go1.6.2.windows-amd64.msi
to see them (and cancel the download of the msi file).

**Comment by alexbrainman** [comment]
> try accessing
> https://golang.org/doc/install?download=go1.6.2.windows-amd64.msi
> to see them (and cancel the download of the msi file).

Found it. Thank you.

Perhaps, for a new user, we should just say
```
C:\> set GOPATH=c:\a
```
and mention that the `c:\a` directory can be anywhere.

Also I don's see why (for a first time user) we need %GOPATH%\src\github.com\user\hello. It can just be %GOPATH%\src\hello.

Alex

**Comment by adg** [comment]
I just sent a change to replace `%HOME%` with `C:\`, which should be more straightforward.

The whole `github.com/user/...` thing is supposed to be a teaching moment about name spaces. As part of resolving this issue, I am going to leave it as-is. I am working on a better solution to that problem.

**Comment by zeasratwde** [comment]
I had the same problem. 
Assuming that your in %GOPATH% : 
Make sure your 'hello.go' file, the one you compiling, is in the following folder:
'src\github.com\user\hello'.  
Do the following:
1. create the required folder structure by typing: 'md src\github.com\user\hello'
2. create your source file 'hello.go' in the new folder ' src\github.com\user\hello'
3. compile the program  by typing: 'go install github.com/user/hello'
4. The output should be under 'bin' folder 
5. you should be able to see the output by typing 'bin/hello'
