### ISSUE TITLE
cmd/compile: enable test/fixedbugs/bug398.go again

### ISSUE THREAD

**Issue by griesemer** [golang/go#15596]
The new export format can handle arbitrary cycles. However, to match the existing compiler infrastructure, tracking of arbitrary cycles is disabled for now (bexport.go: trackAllTypes = false). As a consequence, some cycles are not recognized.

test/fixedbugs/bug398.go crashes if the interfaces are exported and the new export format is used with trackAllTypes disabled. Once we track all types again, this test case can export the cyclic interfaces again.

Note that the existing exporter cannot properly export these interfaces either. But it recognizes this case and doesn't crash. But the export data is invalid and cannot be imported.

**Comment by griesemer** [comment]
Fixing this will require possibly significant changes to the existing type checker in the compiler. Unlikely that we will get to this for 1.8.

**Comment by josharian** [comment]
@griesemer I think this might be fixed. bug398 shows no signs of being disabled now, and switching to exported interfaces doesn't appear to cause crashes. Can you confirm? And if desired, send a CL for 1.9 to switch it to use exported interfaces?
