### ISSUE TITLE
hash/crc32: add more use of Castagnoli's polynomial

### ISSUE THREAD

**Issue by perillo** [golang/go#15605]
Currently the documentation of the Castagnoli variable says that it is used by iSCSI.
However it is also used in SCTP, Btrfs, ext4 and Ceph, as listed on 
https://en.wikipedia.org/wiki/Cyclic_redundancy_check

I suggest to add SCTP to the list of standards using CRC32-c.

**Comment by ALTree** [comment]
The list is not really supposed to be exhaustive, and in the end listing some names won't help a reader that doesn't already know what we're talking about. Let's close this.
