### ISSUE TITLE
gofmt does not align constant assignment after multiline initializer

### ISSUE THREAD

**Issue by dottedmag** [golang/go#15601]
1. What version of Go are you using (`go version`)?

`go version go1.6.2 darwin/amd64`
1. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dottedmag/g"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
1. What did you do?

Run `gofmt` on

```
package main
const (
    password    = "12345"
    expectedKey = "\x87\xe4\x51\x48\x5a\xc9\x57\x2a\x74\x3c\x88\xcc\x79\x50\xd6\xc3\x7b\xdc\x81\x3d\x4b\xd5\x1f" +
        "\xcd\x81\xd2\x46\x08\xac\xb7\xc2\xe3"
    expectedIv = "\x34\x94\x7e\x3c\x62\x24\x1d\xfb\x0e\xcb\xca\x9b\x41\x62\x38\x8c"
)
```
1. What did you expect to see?

`expectedIv` should be aligned to `expectedKey` and `password`. Changing order of `expectedIv` and `expectedKey` causes alignment to work properly.
1. What did you see instead?

`expectedIv` was not aligned.

**Comment by griesemer** [comment]
This is probably working as intended (you have an explicit line break) but I'll have a look.

**Comment by griesemer** [comment]
This is working as intended: Alignment works only across immediately adjacent lines, never across unaligned lines. This is a consequence of the fundamental mechanism underlying alignment in gofmt. We are not going to change that.

The multi-line expression for expectedKey breaks the previous aligned "section", and then expectedIv starts a new section.
