### ISSUE TITLE
os: TestStdPipe flake on darwin

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15613]
Noticed on a trybot run:

https://storage.googleapis.com/go-build-log/0e1049fe/darwin-amd64-10_10_bc2daf40.log
```
--- FAIL: TestStdPipe (0.08s)
	pipe_test.go:85: unexpected exit status exit status 2 for descriptor 1s sig false
FAIL
FAIL	os	0.428s
```

Paging Mr. Signals, @ianlancetaylor.

**Comment by bradfitz** [comment]
This happens much more often on the new OS X 10.9 builder.

I also notice leftover spinning `testprogcgo.exe` processes sometimes. (Related?)

**Comment by ianlancetaylor** [comment]
I have not been able to recreate this with gomote.  I have a theory and will send a CL, but it's just a logical guess, not something I can demonstrate will work.

**Comment by ianlancetaylor** [comment]
Maybe fixed.
