### ISSUE TITLE
x/net/http2/hpack: Possible decoding mistake in HPACK decoder

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#15614]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
CC="gcc"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
https://play.golang.org/p/GCCEi-6zBN

4. What did you expect to see?
An error

5. What did you see instead?
No error

I am working on an HTTP/2 compliance test which involves Fuzz testing the HPACK Decoder.  The problem was originally found in the Java implementation of [Netty](https://github.com/netty/netty).  When I looked to see how Go was handling it, it seemed to be different from Netty and also different from the Spec.  

Two 0xFF bytes in the input are interpreted as trailing padding in a huffman encoded value. From reading the [spec](https://http2.github.io/http2-spec/compression.html#string.literal.representation), the last paragraph says that padding in excess of 7 bits is an error (rather than being ignored).  I believe this should be a decoding error, rather than being treated as an empty string as the code above behaves.

Note that the string in the example was shortened for brevity.  The original suspect bytestring is:

```
  []byte{19, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 164, 91, 41, 164, 33, 1, 0, 130, 255, 255, 0, 15, 0, 164, 0, 0}
```

**Comment by carl-mastrangelo** [comment]
Note that the example was shortened for brevity.  The original bytes that caused the error

**Comment by bradfitz** [comment]
Do you want to fix?

**Comment by carl-mastrangelo** [comment]
@bradfitz Sure, I just wanted to confirm it was actually a bug and not a misreading of the spec.  I think I already have a CLA for Go from a few years back.  I'll send out a CL.

**Comment by bradfitz** [comment]
Googlers don't need to do a CLA.

I don't remember that part of the spec, so it's likely I just missed it the first time. I at least don't see a test for it.

Can you also add a test for the EOS case? ("A Huffman-encoded string literal containing the EOS symbol MUST be treated as a decoding error.")

**Comment by carl-mastrangelo** [comment]
Sure.  I'll have a CL by tomorrow probably.
