### ISSUE TITLE
cmd/asm, cmd/internal/obj/ppc64: ppc64 and ppc64le do not support vector (VMX) registers/instructions

### ISSUE THREAD

**Issue by ceseo** [golang/go#15619]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +149ac34 Mon May 9 17:50:29 2016 +0000 linux/ppc64le

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="ppc64le"
GOOS="linux"

3. What did you do?
I noticed that the current port for Power does not support vector (VMX/Altivec) registers and instructions.

4. What did you expect to see?
Vector registers and instructions support are important to enable performance optimization for runtime packages on Power. Those should be implemented.

I have a change to add the initial support for the VMX instructions, starting with the vector registers and X-form load/store instructions.

**Comment by minux** [comment]
Thanks, please send the CL after the tree reopens (~Aug 2016).

**Comment by laboger** [comment]
Related to this work, I was not able to find much documentation about the golang ABI for ppc64x in general and how it affects the VMX registers in particular.

**Comment by minux** [comment]
Re Go ABI: all registers are callee-save (except for the constant R0
register).
Certainly all VMX registers will be callee-save too.
