### ISSUE TITLE
x/crypto/ssh/terminal: MakeRaw() does not unset the OPOST flag

### ISSUE THREAD

**Issue by fdawg4l** [golang/go#15625]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fahmed/src/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

The `stty` utility can set a serial device to raw mode as such.
```
# Set to raw
$ sudo stty -F /dev/ttyS0 raw

# Inspect settings.   Notice the presence of the -opost flag.
$ sudo stty -F /dev/ttyS0
speed 9600 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel
-opost
-isig -icanon -echo
```

The `-opost` flag suppresses post processing used by terminals to send/interpret exit codes (color, carriage returns, etc.). 

Using the `MakeRaw` method in the `ssh/terminal` package should give us the same results.  Example code can be found [here](https://play.golang.org/p/_LFLN6rBXH). 

4. What did you expect to see?

Running the above snippet should add the `-opost` flag (e.g. unseting the `syscall.OPOST` bit), but it does not. 

5. What did you see instead?

Instead of seeing `-opost` in the output of `stty` after running the above snippet, we see the following

```
# Before issuing
$ sudo stty -F /dev/ttyS0
speed 9600 baud; line = 0;
-imaxbel
-echo


$ sudo ./setraw 
setting terminal to raw mode
s = &terminal.State{termios:syscall.Termios{Iflag:0x526, Oflag:0x5, Cflag:0xcbd, Lflag:0x8a33, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4, 0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}}f

# Check what was set.  Notice the lack of -opost as in (3) above.
$ sudo stty -F /dev/ttyS0
speed 9600 baud; line = 0;
min = 1; time = 0;
-icrnl -imaxbel
-isig -icanon -echo
```

**Comment by fdawg4l** [comment]
Gah...  wrong repo.  Apologies.

**Comment by fdawg4l** [comment]
Actually it looks like the supplemental packages don't have issue trackers.  I'm reopening this in case a member of `golang` knows where this should go.

**Comment by fdawg4l** [comment]
The issue is `newstate.Oflag` isn't being modified from `oldstate` in `MakeRaw()`.  PR to follow.

**Comment by minux** [comment]
FYI: This is the correct issue tracker for all the golang.org/x/* subrepos.

**Comment by fdawg4l** [comment]
Fix [here](https://go-review.googlesource.com/#/c/22964/)

**Comment by fdawg4l** [comment]
Hi!  Is there anything this change needs?  This changeset has been open for a few weeks and want to make sure there isn't anything I need to do to make progress.  Thanks!

**Comment by caglar10ur** [comment]
Ping @bradfitz (as you are the last person approved a change that affected MakeRaw - https://github.com/golang/crypto/commit/3fbbcd23f1cb824e69491a5930cfeff09b12f4d2 )! 

Do you need anything else for this to go in or have any objections?

**Comment by bradfitz** [comment]
I'll let @hanwen or @ianlancetaylor continue the review. Looks like @ianlancetaylor left you comments.
