### ISSUE TITLE
proposal: add flag to `go build` to install dependent packages (or have as a default)

### ISSUE THREAD

**Issue by broady** [golang/go#15634]
The disparity in behavior between `go install` and `go build` is confusing.

Subsequent builds with `go build` are slow and it doesn't really make sense why.

`go install` is required to install dependent packages, but there's no control (other than `$GOBIN`) about the final location of the binary.

I propose adding a flag to `go build` (like `-install`), or alternatively supporting the `-o` flag for `go install`.

**Comment by adg** [comment]
From `go help build`:

> The -i flag installs the packages that are dependencies of the target.

**Comment by broady** [comment]
Totally missed that in the output of `go help build`.
