### ISSUE TITLE
TestPackageMainTestImportsArchiveNotBinary always fails on Fedora 22 with updated packages

### ISSUE THREAD

**Issue by gshimansky** [golang/go#15640]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +c1e8892 Wed May 11 08:30:53 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/nfs/ims/home/gashiman/work/gopath"
GORACE=""
GOROOT="/nfs/site/disks/ms-ssg_dpd_tcar_sat/users/gashiman/golang"
GOTOOLDIR="/nfs/site/disks/ms-ssg_dpd_tcar_sat/users/gashiman/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build054107870=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

When I run all.bash I always get a test failure on Fedora 22. All packages are updated to their most recent versions, so kernel build is 4.4.8-200.fc22.x86_64.

4. What did you expect to see?

Passed test. It passes for me on other linuxes like Ubuntu 15.04 and RHEL 6.6.

5. What did you see instead?

`--- FAIL: TestPackageMainTestImportsArchiveNotBinary (1.92s)
        go_test.go:244: running testgo [test main_test]
        go_test.go:259: standard output:
        go_test.go:260: ok      main_test       0.001s

        go_test.go:244: running testgo [install main_test]
        go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} main_test]
        go_test.go:259: standard output:
        go_test.go:260: true:newer source file

        go_test.go:559: after go install, main listed as stale
FAIL
FAIL    cmd/go  67.935s
`

**Comment by davecheney** [comment]
J'cuse coarse nfs time stamps.

**Comment by gshimansky** [comment]
Indeed. Building on local disk makes this test pass. The bug is invalid.
