### ISSUE TITLE
x/tools/cmd/vet: check for unexecuted defers

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15645]
Creating a bug to track this open CL from @mjibson:

https://golang.org/cl/11972

Can somebody review? @josharian, @minux, @adg?

**Comment by josharian** [comment]
I've been deferring to @robpike on new vet checks. I'm happy to help vet the code, but I want some direction from Rob first about whether the check itself will be approved.

**Comment by adg** [comment]
Assigning to @robpike to decide whether this belongs in vet.

IMO it should go in. It's a common error and the check doesn't yield false positives.

**Comment by rsc** [comment]
Using the vet metrics in cmd/vet/README, this passes on correctness and precision. Can someone say anything about frequency? How often does this come up in real code?

Regardless, it's too late for Go 1.7.

**Comment by mjibson** [comment]
Running this on my $GOPATH found some usages, but none of them were real, so I think this check as is would need some improvements anyway.

```
/data/go/src/github.com/coreos/etcd/wal/repair.go:63: defer in non-terminating for loop
/data/go/src/github.com/golang/go/src/net/dial.go:406: defer in non-terminating for loop
/data/go/src/github.com/golang/go/src/net/http/h2_bundle.go:5439: defer in non-terminating for loop
/data/go/src/github.com/rjeczalik/notify/watcher_inotify.go:201: defer in non-terminating for loop
/data/go/src/golang.org/x/net/http2/transport.go:752: defer in non-terminating for loop
```

All of these cases are in loops that don't always terminate. However, in practice they do, so I'm not convinced how useful this check is.

**Comment by robpike** [comment]
I don't think this is a common enough error to go in.
