### ISSUE TITLE
website: 403 Forbidden from golang.org

### ISSUE THREAD

**Issue by acidnik** [golang/go#15642]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.6.2 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/nik/go"
   GORACE=""
   GOROOT="/usr/local/go"
   GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   $ go get -v github.com/revel/revel
   Fetching https://golang.org/x/net/websocket?go-get=1
   Parsing meta tags from https://golang.org/x/net/websocket?go-get=1 (status code 403)
   package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (parsing golang.org/x/net/websocket: XML syntax error on line 9: expected /> in element)
   Fetching https://golang.org/x/sys/unix?go-get=1
   Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 403)
   package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (parsing golang.org/x/sys/unix: XML syntax error on line 9: expected /> in element)

curl https://golang.org/x/net/websocket?go-get=1 -v
- Hostname was NOT found in DNS cache
-   Trying 2a00:1450:400e:803::2011...
- Connected to golang.org (2a00:1450:400e:803::2011) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server key exchange (12):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
- Server certificate:
-        subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=misc-sni.google.com
-        start date: 2016-05-04 09:19:41 GMT
-        expire date: 2016-07-27 08:39:00 GMT
-        subjectAltName: golang.org matched
-        issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
-        SSL certificate verify ok.
  > GET /x/net/websocket?go-get=1 HTTP/1.1
  > User-Agent: curl/7.38.0
  > Host: golang.org
  > Accept: _/_
  > 
  < HTTP/1.1 403 Forbidden
  < Content-Type: text/html; charset=UTF-8
  < Content-Length: 1594
  < Date: Wed, 11 May 2016 14:15:19 GMT
  < 
  <!DOCTYPE html>
  <html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    _{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:
  30px 0 15px}_ > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-d
  ecoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/image
  s/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/
  branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.
  png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;
  -webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/x/net/websocket</code> from this server.  <ins>That’s all we know.</ins>
- Connection #0 to host golang.org left intact
1. What did you expect to see?
   working go get
2. What did you see instead?
   403 forbidden
# ip ad

...
inet 178.62.239.252
inet6 2a03:b0c0:2:d0::b6:1001
...

**Comment by ianlancetaylor** [comment]
CC @adg @jbuberel

**Comment by adg** [comment]
@acidnik does visiting https://golang.org work for you?

**Comment by acidnik** [comment]
@adg "for me" as in "from my home machine"? Yes it does.
"for me" as in "from my virtual machne at digital ocean?" No, it doesn't. See curl output above

**Comment by adg** [comment]
@acidnik Right. I am asking you to clarify that you get the same result with just "curl https://golang.org/" from that machine.

**Comment by kennygrant** [comment]
These commands:

```
curl -v https://golang.org/x/net/websocket?go-get=1
curl https://golang.org/
```

Return 200 OK for me tested from a couple of different DO instances (CoreOS, Ubuntu) - returns a redirect or a page respectively. So I don't think there is a general problem. Suggest this is closed unless @acidnik wants to pursue it further.

**Comment by bradfitz** [comment]
@broady, could you file an IP geolocation bug? (see my previous ones)

**Comment by broady** [comment]
We've made some changes since May.

@acidnik are you still seeing this? Please reply/re-open if you are.
