### ISSUE TITLE
builder: DragonFly buildbot is more flaky than passing

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15648]
The Dragonfly BSD builder is failing more often than it's passing lately on https://build.golang.org/

If we can't get it more reliable, it might be time to drop the port.

Can somebody give it some love?

/cc @fupjack, Dragonfly builder owner
/cc @mdempsky, @mikioh, @minux, @4a6f656c (previous BSD interest)

**Comment by mdempsky** [comment]
FWIW, I just briefly reviewed all of the DragonFly-specific code in packages runtime and syscall, and nothing stands out to me as obviously wrong. However, I don't claim to be knowledgeable about DragonFly's kernel interface aside from what their man pages document.

**Comment by mikioh** [comment]
During go1.7 development cycle, dragonfly is one of the most stable development platforms to me and I didn't see any runtime, net and cmd/go test failures on my dragonfly-vm which runs 4.4-RELEASE (v4.4.x).

**Comment by bradfitz** [comment]
@mikioh, that's not what the builders would suggest.

**Comment by fupjack** [comment]
The machine where the builder is running is used by a number of people to build a lot of other packages; my initial assumption is that it's interference from all the other work being done there.  

I will move it to a separate machine, though it may be a few days before I can complete that.

**Comment by fupjack** [comment]
DragonFly builder is moved to a new machine that isn't building the entire dports collection.  We'll see if a change in location makes a difference as the week progresses.

**Comment by bradfitz** [comment]
Thanks!

**Comment by bradfitz** [comment]
Seems much better now. Closing. Thanks again!
