### ISSUE TITLE
x/mobile: Failed to compile when Code Sign On Copy is enabled

### ISSUE THREAD

**Issue by dcu** [golang/go#15657]
We are creating a "super" framework that wraps the gomobile SDK framework so we can provide a nicer interface to the user.
After including the "super" framework in an app it won't compile if "Code Sign On Copy" is enabled. The error we are getting is the following:

```shell
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /go_workspace/src/sdk/sdk.framework/Versions/A/sdk -r -o /Library/Developer/Xcode/DerivedData/SDKSample-hekfbucrqcjiftbuxvajgryylwtw/Build/Products/Debug-iphoneos/SDKSample.app/Frameworks/sdk.framework/Versions/A/sdk
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: string table not at the end of the file (can't be processed) in file: /go_workspace/src/sdk/sdk.framework/Versions/A/sdk(go.o) (for architecture armv7)
error: bitcode_strip /go_workspace/src/sdk/sdk.framework/Versions/A/Coresdk: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1
```

when "Code Sign On Copy" is not checked the error changes to:

```shell
A signed resource has been added, modified, or deleted.
```

**Comment by crawshaw** [comment]
There is not enough information here. What does "generating a wrapper" mean?

Part of the gomobile build process is invoking an xcode tool to sign the binary produced. If you are presenting something different to xcode, it may need a different process. You can run the gomobile tool with -x flag to see what commands are being run.

To start the debugging process: do the basic examples or Ivy from the mobile subrepository work on your xcode installation? If so, there is some interaction between your build process, xcode, and the go binary that is the problem. If not, please report what you're seeing with the examples, which should work on armv7.

**Comment by dustin-graham** [comment]
@dcu any update on your progress with this? I'm trying to do something similar and hitting the same walls.

**Comment by dcu** [comment]
we generated the umbrella framework in a different way and this issue is now gone. Closing the ticket.

**Comment by petraalm** [comment]
@dcu could you please describe how did you generate the umbrella framework in the end? I'm having similar problems.
