### ISSUE TITLE
net: GODEBUG=netdns=go massive DNS lookups crash w/ "runtime/cgo: pthread_create failed: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by mikioh** [golang/go#15659]
This happens on darwin 21d781070cea6001ee541933ed76dc6da96bde4c and doesn't happen on darwin go1.6, and not sure whether darwin-specific issue.

Caution: TestLookupIPDeadline in lookup_test.go is a bad test in bad manner. It generates massive DNS queries to confirm that the net package doesn't create system threads extravagantly. Before testing, you need to make sure whether the flood is acceptable to your circumstances.

When we run `go test -v -run=TestLookupIPDeadline -dnsflood -count=10`, the expected result is that probably the test may fail but not crash. On tip, TestLookupIPDeadline crashes unfortunately.
```
# export CGO_ENABLED=1
# go build

# export GODEBUG=netdns=cgo
# go test -v -run=IPDeadline -dnsflood -count=10
=== RUN   TestLookupIPDeadline
(snip)
ok  	net	30.542s

# export GODEBUG=netdns=go
# go test -v -run=IPDeadline -dnsflood -count=10
=== RUN   TestLookupIPDeadline
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fff84223f06 m=2
(snip)
rax    0x0
rbx    0x6
rcx    0x700000080bd8
rdx    0x0
rdi    0xd03
rsi    0x6
rbp    0x700000080c00
rsp    0x700000080bd8
r8     0x40
r9     0x7fff74c4b1e0
r10    0x8000000
r11    0x206
r12    0xc9001070bc281990
r13    0x30
r14    0x700000081000
r15    0x700000080c58
rip    0x7fff84223f06
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```
Not sure the reason why GODEBUG=netdns=go DNS lookups on tip require the functionality of runtime/cgo.

**Comment by minux** [comment]
The program requires cgo because the net package is compiled with
cgo support. It doesn't matter the runtime choice is to use the pure
Go resolver.

If the program uses cgo, then Go cannot create threads on its own,
and it must use pthread_create to create threads in order to
cooperate with cgo (actually, dynamically linked programs on
Darwin can't create threads without pthread.)

**Comment by mikioh** [comment]
The problem is, I guess, in go1.6 GODEBUG=netdns=go never invokes C.getaddrinfo and friends via cgo, but looks like tip uses them.

**Comment by mikioh** [comment]
> but looks like tip uses them.

Nope, the series of cgoLookup are not called during the test. Who is the main culprit?

**Comment by minux** [comment]
Whether the program calls cgo functions doesn't matter.
If the program is built with cgo, then it will use pthread
to create threads.

**Comment by mikioh** [comment]
Okay, I now understand why I'm confused; simply, a) Darwin consumes various kernel resources more than I expect because of probably bridging cosumer thread cancelation stuff and Mach stuff, b) there was no -test.count flag in go1.4 and I used -test.cpu flag when I added TestLookupIPDeadline. There is no big difference about the # of cosumed Ms via runtime.newm between go1.4 and tip. Thanks.
