### ISSUE TITLE
cmd/compile: make ascompatte generate less garbage

### ISSUE THREAD

**Issue by josharian** [golang/go#15665]
@crawshaw noted over email:

> ascompatte (a) is called a lot, (b) returns a new []_Node, and (c) that return value almost always replaces the []_Node passed in as parameter lr. Might be due for a rewrite inline modifies a Nodes...

Transferring to an issue so that it doesn't get lost.

**Comment by quasilyte** [comment]
I think this function is gone now.
Could be the right time to close this issue, maybe?

For the reference, git bisect shows that this function was replaced in 2578ac54eb417488c70324e7f3fc25565ec3f03d.
```
    Prior to this change, walk was responsible for constructing (most of) the stack for function calls.
    ascompatte gathered variadic arguments into a slice.
    It also rewrote n.List from a list of arguments to a list of assignments to stack slots.
    ascompatte was called multiple times to handle the receiver in a method call.
    reorder1 then introduced temporaries into n.List as needed to avoid smashing the stack.
    adjustargs then made extra stack space for go/defer args as needed.

    his change moves stack construction to the SSA construction phase.
    ascompatte, now called walkParams, does all the work that ascompatte and reorder1 did.
```
