### ISSUE TITLE
website: https://tip.golang.org/pkg/archive/tar/ shows no such directory

### ISSUE THREAD

**Issue by minux** [golang/go#15667]
Please see https://tip.golang.org/pkg/archive/tar/.

The web pages says:
File archive/tar
archive/tar
"/src/archive/tar" is not a directory

Screenshot:
![image](https://cloud.githubusercontent.com/assets/135652/15237884/38779e84-18a0-11e6-91fa-800945854452.png)

Not only archive/tar, a lot of other packages are broken too.

/cc @adg @bradfitz

**Comment by bradfitz** [comment]
I just noticed this too. Have there been recent godoc changes?

**Comment by mikioh** [comment]
See https://go-review.googlesource.com/23076/

**Comment by minux** [comment]
Seems related to the recent fix of #3428.

**Comment by odeke-em** [comment]
My apologies for that, I am the one who made and pushed for that CL as godoc and other utils seemed to be working for me locally after that change.

**Comment by mikioh** [comment]
Fixed by https://go-review.googlesource.com/23076.
