### ISSUE TITLE
go doesn't call finalizer for global objects

### ISSUE THREAD

**Issue by rekby** [golang/go#15660]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\gopath\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
https://play.golang.org/p/VoHL5HMskL

4. What did you expect to see?
I expect the finalizer call and print ok

5. What did you see instead?
Nothing

It is problem when cleanup must free external resource, for example kill external process.
In my case I run a headless browser for testing scripts and can't stop it when tests finished.

**Comment by mattn** [comment]
Go (or most of programming languages that implement GC like mark&sweep) doesn't promise to free all instances. note that some programming languages implement GC as  auto-release and those promise to free all of instances.

**Comment by bradfitz** [comment]
In addition to finalizers don't being guaranteed by the spec, the spec also says your program ends when main ends: https://golang.org/ref/spec#Program_execution

**Comment by mattn** [comment]
@rekby 
> In my case I run a headless browser for testing scripts and can't stop it when tests finished.

If you want to stop/close/terminate the instance/scripts or something resourceses, you can use defer https://play.golang.org/p/ZBBYRNVCoW

**Comment by minux** [comment]
The real reason is that globals are not allocated on the heap
(they are statically allocated and always assumed live), so by
definition, their finalizer won't be called no matter how precise
Go's GC become.

**Comment by minux** [comment]
On Thu, May 12, 2016 at 2:13 AM, mattn <notifications@github.com> wrote:

> Go (or most of programming languages that implement GC like mark&sweep)
> doesn't promise to free all instances. note that some programming languages
> implement GC as auto-release and those promise to free all of instances.
>

I don't think this is correct. Go GC does guarantee the execution of
finalizers
and there are tests to verify that. You just can't know when do that happen,
but eventually they will (you can force GC to make it happen sooner.)

**Comment by mattn** [comment]
Thanks explaining & Sorry about OT. Go's GC will correct all of instances by sweep(`runtime.GC()`) at once if there are some references to mark to the instance?

**Comment by rekby** [comment]
@mattn I can't use defer in my case:
I have run go test for test webinterface with webdriver.
I want to start a browser instance and use it for all tests, then close browser.

With defer I can run/stop browser for every test (but it take a lot of time), but can't stop browser after all tests finished.
