### ISSUE TITLE
strings: assembly optimization causes regression in functionality

### ISSUE THREAD

**Issue by dsnet** [golang/go#15679]
Commit 6b02a1924725688b4d264065454ac5287fbed535 caused a regression in the strings package that causes some tests to fail.

A simple test to exercise this behavior is the following:
```go
strings.Contains("abcdef?v=profileM", "abcdef?v=profile&")
```

On go1.6, this returns `false` as expected.
On 6b02a1924725688b4d264065454ac5287fbed535, this returns `true`, which is incorrect.

/cc @rsc, @TocarIP, @nigeltao

**Comment by minux** [comment]
Should this issue remain open to track the bugfix for Go 1.8?

**Comment by randall77** [comment]
I'll open a separate issue.
