### ISSUE TITLE
cmd/go: make it easier for toolexec authors to get access to full package path

### ISSUE THREAD

**Issue by josharian** [golang/go#15677]
I'm writing a toolexec-able program for which I want to know the full package path for whatever code is being operated on. The code to figure out this package path is currently a pile of hacks. E.g. for compile, look for the `-p` arg. For asm, use `-trimpath` to figure out $WORK and then slice that off the `-o` arg. This breaks down entirely for invocations of cgo with `-dynpackage`.

I would like to have cmd/go pass extra information when toolexec is in use. For backwards compatibility, I propose to do this via an environment variable, something like `TOOLEXEC_PKG_PATH` (improvements welcome). There might be other, similar bits of data to add in the future.

Feedback and suggestions requested. I'm going to hack this in myself anyway, it's just a question of whether I should plan to mail a CL at the end (for 1.8, of course).

**Comment by bradfitz** [comment]
I had this same pain recently but figured I was just doing something wrong. Glad I'm not alone.

**Comment by mvdan** [comment]
@josharian given that you self-assigned this, do you still intend to implement this? If not, I'd like to have a go for 1.16 :)

**Comment by josharian** [comment]
All yours.
