### ISSUE TITLE
misc/trace: backport trace viewer fix to 1.6

### ISSUE THREAD

**Issue by prattmic** [golang/go#15678]
I'm not sure how far away Go 1.7 is, but if it is not soon, would it be possible to backport https://github.com/golang/go/commit/2c9d773f7411de211389b9e1da441fae68f826d8 to the next 1.6 point release? As new versions of Chrome roll-out, `go tool trace` is effectively broken.

I'm not sure how heavily used the feature is, but I use it occasionally to trace goroutine execution and syscalls.

CC @dvyukov

**Comment by ianlancetaylor** [comment]
I'll leave this open just in case, but there are no present plans for another 1.6 point release.  We're only going to do one if there is a need for it, and this request is not enough by itself.

1.7 should be released August 1.

**Comment by minux** [comment]
It might not meet the bar for point releases. Go 1.7 is due Aug 1st.

**Comment by prattmic** [comment]
Thanks for considering this. I agree that this alone is not enough for a point release.

**Comment by dvyukov** [comment]
FWIW, one can build tip trace command and it should work with traces collected with Go 1.5/6.

**Comment by rsc** [comment]
Given that Go 1.7 is on its way and that affected people can grab the latest trace command separately, we're not going to do this (probably Go 1.6.3 won't happen at all).
