### ISSUE TITLE
net/http: TestTransportEventTraceRealDNS fails on solaris

### ISSUE THREAD

**Issue by mikioh** [golang/go#15682]
See https://build.golang.org/log/5af4e7607bf0c12e2973cb6c09bf39bef7e6ea63
```
--- FAIL: TestTransportEventTraceRealDNS (0.13s)
	transport_test.go:3344: expected substring "DNSDone: {Addrs:[] Err:" in output.
	transport_test.go:3350: should not see Connect events
	transport_test.go:3353: Output:
		DNSStart: {Host:dns-should-not-resolve.golang}
		DNSDone: {Addrs:[{IP:127.0.0.1 Zone:}] Err:<nil> Coalesced:false}
		ConnectStart: tcp 127.0.0.1:80
		ConnectDone: tcp 127.0.0.1:80 dial tcp 127.0.0.1:80: connect: connection refused
FAIL

```

**Comment by mikioh** [comment]
Like a bad control plane never implements discovery stuff, this issues is merged into #15685.

**Comment by bradfitz** [comment]
> Like a bad control plane never implements discovery stuff

I have no clue what that means. Please explain in #15685?

**Comment by mikioh** [comment]
No, it does mean nothing except "you have control, issue #15685". Sorry for confusing by such a local sign.
