### ISSUE TITLE
strings: fix indexShortStr for 17+ bytes

### ISSUE THREAD

**Issue by randall77** [golang/go#15689]
There's a bug in indexShortStr for 17+ bytes.  That case has been disabled for the 1.7 release.  This bug is to track the fix and reenabling of this case for 1.8.
See issue #15679 .

@TocarIP

**Comment by randall77** [comment]
I think maybe the fix is simple.  The code mistakenly uses the 16-byte code when there are 17 bytes.
```
_16_or_more:
	CMPQ AX, $17
	JA   _17_to_31
```
The fix may be a simple as using `JAE` instead.
But I want some more tests before reenabling.

**Comment by minux** [comment]
I think we also need much more extensive tests
on those newly introduced (optimized) assembly
functions before Go 1.7. Recent experiences
showed that they are not as reliable as one would
expect (e.g. #15617 for crypto/sha1)

**Comment by TocarIP** [comment]
This is caused by 
-       CMPQ BX, $16
 +	CMPQ AX, $17
from https://github.com/golang/go/commit/6b02a1924725688b4d264065454ac5287fbed535

Changing 17 back to 16 indeed works.
