### ISSUE TITLE
GoLang Scrypt Package "Pull Request"

### ISSUE THREAD

**Issue by amanuel2** [golang/go#15688]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Latest

2. What operating system and processor architecture are you using (`go env`)?
This is an Online IDE Cloud9IDE:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/workspace"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

Im adding a New Go-Lang function for the scrypt package:

A link on play.golang.org is best.

4. What did you expect to see?
This is a pull request.... Not expecting to see anything. Im just making sure somone just fixes this.

5. What did you see instead?
Like i said above..

Other info.. I preety much pasted this in gerrit code review too:

Im preety much adding a function to check if Hashed Password is equal to the Password they inputed.. This is the function

```
func checkPassword(passCheck string, HashedPass string , salt []byte ,N, r, p, keyLen int) error{
    checkFunc,err := scrypt.Key([]byte(passCheck), salt, N, r, p, keyLen)
    if err != nil{
      errOrg = errors.New("Could Not Activate Key.")
    }
    if string(checkFunc) == HashedPass{
        errOrg = nil
    }else{
        errOrg = errors.New("ACCESS DENIED")
    }
    return errOrg;
}

```

I could not represent a go playground or any online simple compiler since i need to import the scrypt package.. But here is a working test:

```
package main;

import(
    "fmt"
    "errors"
    "golang.org/x/crypto/scrypt"
    )

var errOrg error;
func main(){
    //func Key(password, salt []byte, N, r, p, keyLen int) ([]byte, error)
    dk,err := scrypt.Key([]byte("Password"), []byte("dfs"), 16384, 8, 1, 32)
    check(err)
    fmt.Println(string(dk))
    
    checkPassword("Password", string(dk), []byte("dfs"), 16384, 8, 1, 32)
    if errOrg == nil{
        fmt.Println("*******ACCESS GRANTED********")
    }else{
        panic(errOrg)
    }
}

func check(e error){
    if e!=nil{
        panic(e);
    }
}

func checkPassword(passCheck string, HashedPass string , salt []byte ,N, r, p, keyLen int) error{
    checkFunc,err := scrypt.Key([]byte(passCheck), salt, N, r, p, keyLen)
    if err != nil{
      errOrg = errors.New("Could Not Activate Key.")
    }
    if string(checkFunc) == HashedPass{
        errOrg = nil
    }else{
        errOrg = errors.New("ACCESS DENIED")
    }
    return errOrg;
}

```

**Comment by bradfitz** [comment]
I think that function is trivial enough that callers can implemented it as needed. We try not to add too many helper functions unless they're needed often.
