### ISSUE TITLE
time: time.After uses memory until duration times out

### ISSUE THREAD

**Issue by ston1th** [golang/go#15698]
I would like to see some memory usage information in the docs for time.After like time.Tick already has.

**Comment by bradfitz** [comment]
See also: #8895 and #8898

But worst case we can just document something.

**Comment by dhiltonp** [comment]
I just got bit by this; after 10 minutes of execution, my program had 80MB used just by timers.

For now I've switched to NewTimer so I can explicitly stop them.

Looking forward to the fix.
