### ISSUE TITLE
go1.4.1 build breaks on ubuntu

### ISSUE THREAD

**Issue by hvishwanath** [golang/go#15694]
I am trying to build go1.4.1 from the latest repo on Ubuntu 14.04.02 x86_64 box

```
$ git checkout go1.4.1
$ cd src
$ ./all.bash
...
...
..
# Checking API compatibility.
Error running hg clone on go.tools: exit status 255
abort: HTTP Error 404: Not Found
exit status 1

```

The cause of the failure seems to be that go tools has been moved from code.google.com to a github repo.

```
~/g/src git:tags/go1.4.1 ❯❯❯ grep -r  "hg clone"                                                                                               ◼
cmd/api/run.go:// else it hg clones it.
cmd/api/run.go:	// cloneDir is where we run "hg clone".
cmd/api/run.go:	os.RemoveAll(tmpDir)   // in case of aborted hg clone before
cmd/api/run.go:		log.Fatalf("Error running hg clone on go.tools: %v\n%s", err, out)

```

Though the above is the last test before the "ALL PASSED" mark, it still results in an unclean build.

**Comment by bradfitz** [comment]
You can just run `./make.bash` instead. We won't be doing any new releases of Go 1.4, especially for such a minor issue.

**Comment by pciet** [comment]
Seen with SteamOS building go 1.4.3 branch to build latest 1.7, unblocked go.googlesource.com/go build by running make.bash instead as suggested. The "just works" path may always pause here with the go 1.4 dependency.

**Comment by bradfitz** [comment]
@pciet, we don't reuse old bugs. Open a new bug if you have a unique issue to discuss. If it's the same as this one, this one is closed.
