### ISSUE TITLE
nil custom error pointer convert to non-nil error interface

### ISSUE THREAD

**Issue by localvar** [golang/go#15695]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\litead\oxygen
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/E88xYL625X

4. What did you expect to see?
err is nil

5. What did you see instead?
err is nil
e is not nil

**Comment by dominikh** [comment]
Please see https://golang.org/doc/faq#nil_error

**Comment by localvar** [comment]
Thanks @dominikh, but this is really confusing.
