### ISSUE TITLE
x/mobile: ios framework generated by "gomobile bind"  does not contain bitcode

### ISSUE THREAD

**Issue by justintan** [golang/go#15691]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Use "gomobile bind" to compile and create a iOS framework. Import this framework in Xcode.  

4. What did you expect to see?
Expect building successfuly.

5. What did you see instead?
A link error: "... does not contain bitcode"

=================
My question is: 
How to enable bitcode in "gomobile bind" ?

Thanks

**Comment by minux** [comment]
There is currently no way to enable bitcode,
and I don't know if there is plan to add a
bitcode backend (probably not).

Please ask questions on forums. See
https://golang.org/wiki/Questions.
