### ISSUE TITLE
crypto/tls: provide a way to dynamically handle client hellos

### ISSUE THREAD

**Issue by danp** [golang/go#15699]
I'd like to control whether or not to offer the "h2" protocol during TLS handshake based on the client's requested server name. Currently there's no way to do this with crypto/tls.

Would an optional callback similar to GetCertificate be useful for this and other similar cases?

**Comment by dpiddy** [comment]
Erlang's [ssl module](http://erlang.org/doc/man/ssl.html) has a similar facility: sni_fun in server-side ssl options, though it's only called when SNI is used. A callback that's used regardless of SNI (as GetCertificate is now) would be more generally useful.

**Comment by bradfitz** [comment]
To @agl for thoughts. (Not necessarily for implementation)

**Comment by dpiddy** [comment]
@agl this is something I'd really like to help implement or at least see for 1.8. Any input on this and/or #15707?

I'm roughly thinking of something like `tls.Config.GetClientConfig(*tls.ClientHelloInfo) (*tls.Config, error)` with a more info on tls.ClientHelloInfo, such ALPN protos. Select items on the returned config would be used for the connection. This hook would be called [here](https://github.com/golang/go/blob/9c8809f82aa59e0725e93cffb03de863e61cbbae/src/crypto/tls/handshake_server.go#L191) or so.

**Comment by agl** [comment]
It's on my desiderata list for 1.8.

**Comment by bradfitz** [comment]
See #16066 for a related issue and my comment https://github.com/golang/go/issues/16066#issuecomment-250606132 for one idea.
