### ISSUE TITLE
x/tools/cmd/stringer: don't concatenate all strings

### ISSUE THREAD

**Issue by josharian** [golang/go#15704]
stringer concatenates strings (see https://github.com/golang/tools/commit/22ede605a76fe5957178d9b6290c986ae066316d). The original motivation was to shrink the resulting binary. Thanks for work by @crawshaw and @rsc during the Go 1.7 cycle, there is no longer a penalty for having multiple smaller strings. The non-concatenated strings are more readable, so we might want to go back to multiple smaller strings.

Low priority.

**Comment by robpike** [comment]
A single string is still smaller: there are more slice headers. That was the motivation for the design. Are you suggesting something else?

**Comment by robpike** [comment]
P.S. I don't care about readability here. It's machine-generated code whose readability matters no more than it does for assembly output from a compiler.

**Comment by josharian** [comment]
There was also the overhead of the individual string headers. But if you're happy and don't care about readability, I'm happy.

**Comment by bradfitz** [comment]
> It's machine-generated code whose readability matters no more than it does for assembly output from a compiler.

There does exist plenty of machine-generated code which I regularly read. (e.g. protobufs)

**Comment by robpike** [comment]
You need to read protobuf code to know what's going on. That doesn't apply to stringer. I certainly hope it doesn't, anyway.
