### ISSUE TITLE
x/sys/windows: Consider exporting kernel32 *LazyDLL

### ISSUE THREAD

**Issue by taruti** [golang/go#15702]
Currently all libraries needing more procedures load the libraries by hand using either syscall or x/sys/windows. The most common DLL by a large margin used in this fashion appears to be kernel32.dll.

This means that in larger applications there are half-a-dozen libraries loading kernel32.dll. They could use a shared copy since *LazyDLL is safe for concurrent use.

Exporting:
```
var ModKernel32DLL = NewLazySystemDLL("kernel32.dll")
```
from x/sys/windows would enable sharing this for applications.

x/sys/windows loads a copy of kernel32.dll in any case (modkernel32).

If needed I can write a proposal or a patch.

**Comment by alexbrainman** [comment]
I don't see what the benefit here. Is something going to be faster? Less lines of code? What? Please explain. Thank you.

Alex

**Comment by taruti** [comment]
@alexbrainman 
It would call LoadLibrary once for sys/x/windows instead once for each library needing functions from kernel32.dll. 

Underneath Windows does reference counting of the DLLs loaded so calling LoadLibrary("kernel32.dll") multiple times results in only a single copy of the library in the address space. So the saving is a little bit of memory and few less syscalls.

**Comment by alexbrainman** [comment]
> It would call LoadLibrary once for sys/x/windows instead once for each library needing functions from kernel32.dll.

I don't see any benefit here. It is just few more calls into LoadLibrary. It is not slow code. And average app calls LoadLibrary just couple of times. And since I use $GOROOT/src/syscall/mksyscall_windows.go to generate my syscalls, I don't even have to write that code.

It is not worth the trouble.

Alex

**Comment by taruti** [comment]
Ok, thanks for considering it.
