### ISSUE TITLE
crypto/tls: allow choosing ClientAuth (and others?) based on SNI

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#15707]
`tls.Config.ClientAuth` is global per server, however there's no reason it shouldn't be a func(clientHello *ClientHelloInfo) (ClientAuthType, *x509.CertPool). See example use case in mholt/caddy#829.

On the other hand, the same can be said about NextProtos (already a desired feature, to have HTTP/2 enabled only on some hosts, mholt/caddy#189), CipherSuites, SessionTicketKey, ClientSessionCache, CurvePreferences...

I suspect some of them have issues open about them already, but couldn't find them.

**Comment by dpiddy** [comment]
Probably related to #15699.

**Comment by groob** [comment]
The ability to do this in a Go application would be great for internet facing services. Currently it's relatively easy to support Let's Encrypt, but this limitation requires us to go back to using HAProxy. 

My application bundles a SCEP server to issue client certificates and then requires the client to provide the cert at another SNI. Currently it's impossible to do both in a single Go server without using two separate ports.

**Comment by agl** [comment]
I hope to spend a week working on Go in the 1.8 cycle and to address this.

**Comment by dpiddy** [comment]
Noticed title prefix of this issue has a typo: crpyto -> crypto

**Comment by bradfitz** [comment]
See #16066 for a related issue and my comment https://github.com/golang/go/issues/16066#issuecomment-250606132 for one idea.
