### ISSUE TITLE
cmd/compile: sparseMaps and sparseSets could shrink size of "sparse" arrays

### ISSUE THREAD

**Issue by dr2chase** [golang/go#15718]
ssa/sparseMap and sparseSet allocate a "sparse" array with length proportional to the size of an ID (used to index Blocks and Values) containing indices of elements in a "dense" array that must necessarily not be larger than the sparse array.

It is therefore sufficient to use an int32 as elements of the sparse array, but currently it is an int, or 64 bits on quite a few Go platforms.  We could save space by shrinking these.

**Comment by josharian** [comment]
Looks like this got done. @dr2chase can you confirm and close if so? Thanks.

**Comment by dr2chase** [comment]
This got done.
https://github.com/golang/go/commit/d35a4158ab66aef99d9204c65cc2e2fa74b57a73
