### ISSUE TITLE
encoding/json:  can't omit empty value with type time.Time while encoding struct to json payload?

### ISSUE THREAD

**Issue by thinkhy** [golang/go#15719]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/thinkhy/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```golang
import (
        "encoding/json"
        "time"
        "os"
)


type Response struct {
        Name     string    `json:"name,omitempty"`
        Counter  int       `json:"counter,omitempty"`
        CreateAt time.Time `json:"createat,omitempty"`
}


func main() {
        var r Response

        enc := json.NewEncoder(os.Stdout)
        enc.Encode(r)
}
```

4. What did you expect to see?

Seems the expected result should be "{}" because the field createat is empty with ZERO value.

5. What did you see instead?

The above code will output:

       {"createat":"0001-01-01T00:00:00Z"}

**Comment by bradfitz** [comment]
Dup of #4357, etc
