### ISSUE TITLE
initializing variable from MaxUInt64 doesn't work

### ISSUE THREAD

**Issue by gmarek** [golang/go#15715]
From go playground:

```
package main

import (
	"fmt"
	"math"
)

func main() {
	test := math.MaxUint64
	fmt.Printf("Hello, playground: %v", test)
}
```

prog.go:9: constant 18446744073709551615 overflows int

**Comment by minux** [comment]
Working as intended. Without an explicit type,
by default, integer untyped constants will get
an int type, which can't hold math.MaxUint64.

You need to write "test := uint64(math.MaxUint64)".

Please ask further questions on the forums.
See https://golang.org/wiki/Questions.
