### ISSUE TITLE
package testing fail for go1.6+

### ISSUE THREAD

**Issue by paeynivek** [golang/go#15726]
1. What version of Go are you using (`go version`)?
go1.4

2. What operating system and processor architecture are you using (`go env`)?
redhat el6/amd64

3. What did you do?
tried to compile go1.6.2 from source using go1.4 (also compiled from source) using the instructions on https://golang.org/doc/install/source

4. What did you expect to see?
ALL TESTS PASSED

5. What did you see instead?
panicking during package testing. Full error linked below.
[go1.6.2 package testing panic.txt](https://github.com/golang/go/files/269532/go1.6.2.package.testing.panic.txt)

The package testing errors only occurred when trying to compile for go1.6 and above. Compiling versions go1.5.4 and below is successful and passes package testing.

**Comment by davecheney** [comment]
The system you were building on does not have enough free memory (either physical, or swap) to complete the build. We don't track the memory usage required to run ./all.bash but it is at least 512mb per core.

I'm going to close this as I think there is no issue here.

**Comment by paeynivek** [comment]
Increasing thread count per user solved the issue. Same bug here with solution. https://github.com/golang/go/issues/13968
