### ISSUE TITLE
cmd/compile, go/types: erroneously accepts method expressions with anonymous receiver type

### ISSUE THREAD

**Issue by mdempsky** [golang/go#15721]
The Go spec's grammar restricts method expressions to using either a named type or pointer to a named type:

    MethodExpr    = ReceiverType "." MethodName .
    ReceiverType  = TypeName | "(" "*" TypeName ")" | "(" ReceiverType ")" .

cmd/compile erroneously accepts this Go source:

    package p
    var _ = struct{ error }.Error

go/types erroneously accepts it too.

gccgo correctly rejects with the error message "method expression requires named type or pointer to named type"

/cc @griesemer @ianlancetaylor

**Comment by griesemer** [comment]
This is so closely related to #9060 that I'm going to close it as duplicate. I believe we should just accept this code and adjust the spec.
