### ISSUE TITLE
Crypto/Rsa.VerifyPKCS1v15 - minor bug non security related

### ISSUE THREAD

**Issue by cobookman** [golang/go#15725]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6.1

2. What operating system and processor architecture are you using (`go env`)?
 GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/******/work"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -gno-record-gcc-switches -fdebug-prefix-map=/tmp/go-build413535140=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

The following should result in an error, but do not. I'm assuming crypto.Hash points to md4?
```
rsa.VerifyPKCS1v15(public_key, crypto.Hash, hashed[:], sig[:])`
rsa.SignPKCS1v15(rand.Reader, priv, crypto.Hash, hashed)`
```

However it works, causing obvious errors later on when you wonder why a signature from openssl does not validate.

Here's an example of good api calls to the rsa sign & verify functions:
```
rsa.SignPKCS1v15(rand.Reader, priv, crypto.SHA512, hashed)
rsa.VerifyPKCS1v15(&priv.PublicKey, crypto.SHA512, hashed, sig)
```

4. What did you expect to see?
I expected an error to be returned when specfying crypto.Hash as the hash algorithm used in the making of the digest.

5. What did you see instead?
No error, and it successfully signed and validated using crypto.Hash.  I'm not sure which hash algorithm it validated against though.

**Comment by OneOfOne** [comment]
I think something is wrong with your Go, because that doesn't even compile.

`crypto.Hash` is a type not a variable, it would give you an error `prog.go:26: type crypto.Hash is not an expression`.

https://play.golang.org/p/IG4bnQW60q

**Comment by OneOfOne** [comment]
I think something is wrong with your Go, because that doesn't even compile.

`crypto.Hash` is a type not a variable, it would give you an error `prog.go:26: type crypto.Hash is not an expression`.

https://play.golang.org/p/IG4bnQW60q

**Comment by cobookman** [comment]
Here's a working example of the problem:
https://play.golang.org/p/QAEs9MWgIZ

Not sure if this is working as intenteded behavior, but caused me trouble when debugging.  As I forgot to set the `h` variable to crypto.SHA512.

**Comment by bradfitz** [comment]
This is documented:

https://golang.org/pkg/crypto/rsa/#SignPKCS1v15 says:
"If hash is zero, hashed is signed directly. This isn't advisable except for interoperability."

https://golang.org/pkg/crypto/rsa/#VerifyPKCS1v15 says:
"If hash is zero then hashed is used directly."

This appears to be working as documented.
