### ISSUE TITLE
x/crypto/nacl/box, x/crypto/nacl/secretbox: implement cipher.AEAD

### ISSUE THREAD

**Issue by rakyll** [golang/go#15720]
Are box and secretbox packages supposed to be AEAD implementations? If so, is there a particular reason why they don't implement cipher.AEAD but introducing their slightly different API surfaces?

/cc @agl @dsymonds @adg

**Comment by agl** [comment]
They don't support additional data. (I.e. they are AE, not AEAD.)

They could be shoehorned into `crypto.AEAD` if `Seal` paniced on non-empty additional data. I don't know if that would be useful or a landmine.

**Comment by rakyll** [comment]
Since they are not AEAD, there is no good reason to try to comply with the AEAD interface. Misleading APIs with panic'ing runtime behavior is uglier than anything else.

(If anyone has other arguments, please comment and/or reopen.)
