### ISSUE TITLE
encoding/asn1: ASN1 UTC Time support should accept Time in "YYMMDDhhmm[ss](+|-)hhmm" format

### ISSUE THREAD

**Issue by sthorne** [golang/go#15732]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sthorne/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

encoding/asn1 does not support both known ASN1 UtcTime formats as described here: http://www.obj-sys.com/asn1tutorial/node15.html.

[asn1.parseUTCTime](https://golang.org/src/encoding/asn1/asn1.go?h=parseUTCTime#L315)

Currently, only "YYMMDDhhmm[ss]Z" is supported.

4. What did you expect to see?
Support for "YYMMDDhhmm[ss]Z" or "YYMMDDhhmm[ss](+|-)hhmm"

5. What did you see instead?
When using a server with the second format this is the error.

Error : Get https://ovirt.example.com/: tls: failed to parse certificate from server: asn1: time did not serialize back to the original value and may be invalid: given "141020123326+0000", but serialized as "141020123326Z"response Status:

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by agl** [comment]
> UTCTime values MUST be expressed in Greenwich Mean Time (Zulu) and MUST include seconds (i.e., times are YYMMDDHHMMSSZ)

(From [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.1.2.5.1).)

If the certificate is issued by a public CA please include it and I'll complain to the CA.
