### ISSUE TITLE
log/syslog: variables and documentation for facility misleading

### ISSUE THREAD

**Issue by awreece** [golang/go#15731]
[`syslog.Dial`](https://github.com/golang/go/blob/master/src/log/syslog/syslog.go#L115) and `syslog.New` take a `syslog.Priority` as an argument and stores it in a field named `priority`. This field is used exactly twice:
- as a syslog _facility_  in [`writeAndRetry`](https://github.com/golang/go/blob/master/src/log/syslog/syslog.go#L245)
- as the syslog priority in [`Writer.Write`](https://golang.org/src/log/syslog/syslog.go#L171)

For examples of someone confused by this in the wild, check out  [`logrus_syslog`](https://github.com/Sirupsen/logrus/blob/master/hooks/syslog/syslog.go#L22) or [`golang-samples`](https://github.com/golang-samples/log/blob/master/syslog/main.go#L9), which thinks that creating a syslog writer with a severity instead of a facility will do something meaningful:

```
package main

import (
    "fmt"
    "log/syslog"
)

func test(p syslog.Priority, msg string) {
    w, e := syslog.New(p, msg)
    if e != nil {
        fmt.Println("Error opening syslog", e)
    } else {
        w.Debug("hello, world")
    }
}

func main() {
    test(syslog.LOG_ERR, "ALEX")
    test(syslog.LOG_INFO, "BEN")
    test(syslog.LOG_DAEMON, "CAROLE")
    test(syslog.LOG_USER, "DOUG")
}
```

```
<7>1 2016-05-18T10:50:43.326575-07:00 ubuntu-16 ALEX 2517 - -  hello, world
<7>1 2016-05-18T10:50:43.327090-07:00 ubuntu-16 BEN 2517 - -  hello, world
<31>1 2016-05-18T10:50:43.327409-07:00 ubuntu-16 CAROLE 2517 - -  hello, world
<15>1 2016-05-18T10:50:43.327707-07:00 ubuntu-16 DOUG 2517 - -  hello, world
```

It would be great if facility was a different type from priority, but barring that it would be wonderful to update the documentation here. In particular, I would love to see `syslog.New` and `syslog.Dial` take a variable named _facility_ and explain the difference, with an example usage.

I'm happy to do it if such a change could be merged. I see that the package is "frozen" -- will it still accept doc fixes?

**Comment by bradfitz** [comment]
Documentation changes are fine.

**Comment by awreece** [comment]
The value given to `syslog.New` is a:
 - _priority_ for `syslog.Writer.Write`
 - _facility_ for all other consumers of the syslog interface (e.g. `syslog.Write.Info`)

What is the best way to describe the behavior here? I'd _prefer_ to deprecate that `syslog.Writer.Write` will use the priority and to indicate that `syslog.New` prefers a facility; however we obviously can't break backwards compatibility.
