### ISSUE TITLE
feature request: fast-compile mode in Mac

### ISSUE THREAD

**Issue by kokizzu** [golang/go#15743]
1. What version of Go are you using (`go version`)?

1.4.3

2. What operating system and processor architecture are you using (`go env`)?

mac, linux, windows

3. What did you do?
writing software

4. What did you expect to see?
fast compile/reload

5. What did you see instead?
waiting about 1-7 seconds for 120084 loc in mac (i7, 16GB, SSD)
```
[gin] Build Successful in 2071.91 ms (first time running gin)
[gin] Build Successful in 1858.39 ms 
[gin] Build Successful in 1775.83 ms 
[gin] Build Successful in 1965.04 ms 
[gin] Build Successful in 2280.93 ms 
[gin] Build Successful in 2337.21 ms
[gin] Build Successful in 6777.76 ms (when changing code, recompiled by gin)
[gin] Build Successful in 6199.36 ms
[gin] Build Successful in 5891.96 ms
[gin] Build Successful in 5708.85 ms
[gin] Build Successful in 6030.66 ms
[gin] Build Successful in 5560.73 ms
```
waiting about 1-7 seconds for the same loc in linux (i3, 8-16GB, Non-SSD)
```
[gin] Build Successful in 6263.01 ms (first time running gin)
[gin] Build Successful in 1307.85 ms (when changing code, recompiled by gin)
[gin] Build Successful in 1267.70 ms
[gin] Build Successful in 1267.71 ms
[gin] Build Successful in 1981.24 ms
```
the start script:
```
killall -9 gin 2> /dev/null
killall -9 gin-bin 2> /dev/null
gin=`which gin`
if [ -z "$gin" ]; then
  gin=$GOPATH/bin/gin
fi
echo 'starting gin..'
$gin -b /tmp/gin-bin
```

gin taken from `github.com/codegangsta/gin` or `github.com/kokizzu/gin` (requires `github.com/songgao/colorgo`)

I'm not sure if this Go issue or gin issue

**Comment by bradfitz** [comment]
We are actively working on build speed and tracking it in a number of issues. This is a duplicate.
