### ISSUE TITLE
wrong vendor iteration in `go build`

### ISSUE THREAD

**Issue by armstrongli** [golang/go#15746]
1. go version go1.6 darwin/amd64

2. project path
/project/main.go
/project/Godeps/_workspace/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar

And project reference is:
project/Godeps/_workspace/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar

Run `go build project`

4. What did you expect to see?
build one project binary. The `vendor` should only apply the `vendor` in `project` path. Not the iterator ones.

5. What did you see instead?
package project
imports project/Godeps/_workspace/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar : must be imported as src/code.google.com/p/go/src/pkg/archive/tar

**Comment by bradfitz** [comment]
The error message looks correct to me. That's how vendor works.

See golang.org/s/go15vendor for the design.
