### ISSUE TITLE
net/http: SetCookie 'Max-Age' field can not be empty

### ISSUE THREAD

**Issue by yandd** [golang/go#15742]
I need to set a cookie which expired after closing browser. 
Chrome browser just work well when 'Max-Age' field is  empty.
So I think "http.SetCookie" function must support 'Max-Age' field to keep empty.

**Comment by bradfitz** [comment]
@nigeltao, are you still the cookie monster?

**Comment by nigeltao** [comment]
I'm a little confused as to what the original post is asking for.

https://golang.org/pkg/net/http/#Cookie says:

        // MaxAge=0 means no 'Max-Age' attribute specified.
        // MaxAge<0 means delete cookie now, equivalently 'Max-Age: 0'
        // MaxAge>0 means Max-Age attribute present and given in seconds
        MaxAge   int

Do either of the first two do what you want?

**Comment by yandd** [comment]
http://tools.ietf.org/html/rfc6265#section-4.1.2.2
“If a cookie has neither the Max-Age nor the Expires
   attribute, the user agent will retain the cookie until "the current
   session is over" (as defined by the user agent).”

**Comment by yandd** [comment]
@nigeltao  thank you
