### ISSUE TITLE
net/http: interface-like Transport.Dial being deprecated in favor of concrete *net.Dialer Transport.Dialer

### ISSUE THREAD

**Issue by dpiddy** [golang/go#15748]
In https://github.com/golang/go/commit/585590549a3c6e26e7963081e11478a1913744a6 the interface-like Transport.Dial was deprecated for a new Transport.Dialer which is a concrete *net.Dialer.

I understand Transport.Dial will remain but as seen in https://github.com/golang/go/issues/12737 and https://github.com/golang/go/issues/14221 it might be preferable in the long run to use something interface-based. Only DialContext is used on the new Transport.Dialer.

Before this goes out in 1.7 would it be worthwhile to change from a concrete *net.Dialer to either:

* having Transport.Dialer be interface { DialContext(ctx context.Context, network, addr string) }
* keeping only Transport.Dial but using DialContext on it if it implements the above interface?

**Comment by dpiddy** [comment]
And even while Transport.Dial remains as-is there will be no way for a non-*net.Dialer to receive context since that is only used with Transport.Dialer.

cc @bradfitz

**Comment by mikioh** [comment]
Ping @bradfitz

**Comment by bradfitz** [comment]
Sorry, I've been rushing to finish my Go 1.7 bugs before I disappear on vacation for a month. That month begins approximately 15 minutes ago. I'll leave this to others.

**Comment by dpiddy** [comment]
Happy to submit a CL for this if we can decide on a solution.

**Comment by rsc** [comment]
It seems like it should be a DialContext func, to match the previous Dial func.

**Comment by dpiddy** [comment]
Sounds good, I should be able to get a CL together later today.

**Comment by rsc** [comment]
@dpiddy, I'm heading out soon and want to get this in, so I'll write the CL. I'll make sure you are on it. Thanks.

**Comment by dpiddy** [comment]
Thanks!
