### ISSUE TITLE
Mixed assignation / declaration of variables

### ISSUE THREAD

**Issue by tmielcza** [golang/go#15751]
```
// Not working
a := 1
{
    a, b := 2, 3
}

// Works
a := 1
a, b := 2, 3
```

[playground](https://play.golang.org/p/DPqV6S7Ssi)

I want to assign two variables simultaneously.
One is already declared, in a superior scope, the other one is not.

It does not work: the compiler tries to redeclare the former variable.
However, it works fine if this variable is declared in the same scope.

**Comment by bradfitz** [comment]
This is working per the spec.

For questions about the language, see https://golang.org/wiki/Questions
