### ISSUE TITLE
cmd/compile: parallelize compilation

### ISSUE THREAD

**Issue by randall77** [golang/go#15756]
We should be able to parallelize large parts of cmd/compile to make builds faster.

Parsing could be done in parallel on multiple files in a package.
Typechecking may be parallelizeable to some extent, I'm not sure.
Things like escape analysis might have to remain serial.
Compiling functions (order+walk+SSA+obj) can easily be done on each function in parallel.  My only concern is making sure we don't use too much memory.

For all of these changes, we'd need to de-globalize the current compiler.

See also #9887 #15736

@josharian

**Comment by randall77** [comment]
@griesemer @mdempsky @dr2chase

**Comment by rasky** [comment]
@josharian is there a design document about this work? I'm especially interested in hearing why such a big effort is being attempted compared to just spawning multiple processes (like `make -j`). Also, it looks like there will be an ongoing cost on keeping the compiler concurrency-safe after this work is finished (e.g.: running trybots with -race, etc.), so I was wondering if there's a public log of the discussion.

**Comment by bradfitz** [comment]
@rasky, `cmd/go` already spawns multiple processes for different packages. It works well, but not as well as if single packages were also parallelized. That's what Josh is doing.

**Comment by josharian** [comment]
Also, the most common development cycle is incremental compilation, where the most important factor is recompiling ~1 package and linking. In that case, making the single package compile is very important.

For lots more discussion of this and related topics, start at #15734, #15681, #8893, #15752, #15736, and follow links from there. :)
