### ISSUE TITLE
Go map invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by qingfuwang** [golang/go#15750]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data0/go/bin"
GORACE=""
GOROOT="/data0/go"
GOTOOLDIR="/data0/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

```go
func getUser(uid string) *User {
	defer userRW.Unlock()
	var u *User
	
	userRW.Lock()
	u = userMap[uid]  <= line 25
	if u == nil {
		u = &User{c: nil, uid: uid, status: 1, enable_log: false, last_redis_status: 100}
		userMap[uid] = u
	}

	return u
}
```

4. What did you expect to see?
  line 25 should't throw exception

5. What did you see instead?

```
runtime error: invalid memory address or nil pointer dereference
goroutine 71473121 [running]:
net/http.(*conn).serve.func1(0xc90c7c4980)
	/data0/go/src/net/http/server.go:1389 +0xc1
panic(0x81fd60, 0xc82000a0d0)
	/data0/go/src/runtime/panic.go:443 +0x4e9
main.getUser(0x0, 0xa, 0x0)
	/home/huali/ws_test/chatServer/user.go:25 +0x97
main.(*connection).getUser(0xc8d7458240, 0x0, 0xa, 0x470f90)
	/home/huali/ws_test/chatServer/conn.go:366 +0x2b
```

**Comment by qingfuwang** [comment]
userMap is protected by lock, why this run time error could happen?

**Comment by bradfitz** [comment]
You probably forgot a lock elsewhere or have some race. See https://blog.golang.org/race-detector

There isn't really enough context or code here to help, so I'm going to close this. The golang-nuts@ mailing list might be a better place for help. Per https://golang.org/wiki/Questions we don't do general user support here.
