### ISSUE TITLE
playground: ParseFile example at godoc.org cannot be run

### ISSUE THREAD

**Issue by gyuho** [golang/go#15764]
`example_test.go` is used for Go example output test.
Is there anyway to make this runnable on golang.org?
If not, please feel free to close this.

Thanks!

> What version of Go are you using (`go version`)?

https://golang.org/pkg/go/parser/#example_ParseFile

> What operating system and processor architecture are you using (`go env`)?

https://golang.org/pkg/go/parser/#example_ParseFile

> What did you do?
> If possible, provide a recipe for reproducing the error.

Hit run button at  https://golang.org/pkg/go/parser/#example_ParseFile

> What did you expect to see?

No error.

> What did you see instead?

```
open example_test.go: No such file or directory
```

**Comment by ianlancetaylor** [comment]
I'm not sure what we can do about this, but perhaps somebody will have an idea.

**Comment by odeke-em** [comment]
So in a weird twist, it seems like by the time that a snippet's Run is triggered, it has been removed from the file system or at least it isn't in the place that it reports being called from see https://play.golang.org/p/QJrwR06lnA or
```go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

func callerSourcePath() string {
	_, callerPath, _, _ := runtime.Caller(1)
	return callerPath
}

func main() {
	// Will walk up to the root from the call site of this file
	curPath := callerSourcePath()
	fmt.Printf("This file location is %q, attempt to walk up the root\n", curPath)
	for {
		if curPath == "" || curPath == "/" {
			break
		}
		fmt.Printf("walking to %v ", curPath)
		f, err := os.Open(curPath)
		fmt.Printf("\n\tpath %s exists=%v(f=%v) err=%v\n", curPath, f != nil, f, err)
		if f != nil {
			_ = f.Close()
		}
		curPath = filepath.Dir(curPath)
	}
}
```

when run on the playground shows that only `/tmp` exists but the file that it is purported to exist in cannot be found
```shell
This file location is "/tmp/sandbox025674958/main.go", attempt to walk up the root
walking to /tmp/sandbox025674958/main.go 
	path /tmp/sandbox025674958/main.go exists=false(f=<nil>) err=open /tmp/sandbox025674958/main.go: No such file or directory
walking to /tmp/sandbox025674958 
	path /tmp/sandbox025674958 exists=false(f=<nil>) err=open /tmp/sandbox025674958: No such file or directory
walking to /tmp 
	path /tmp exists=true(f=&{0x10434210}) err=<nil>
```

I came to this conclusion by stripping down os.Open down to the nacl implementation of syscall and running that raw implementation on the playground itself. Please see https://play.golang.org/p/9fMAPM6lNc
which produces
```shell
<nil> stat /tmp/sandbox890988319/main.go: No such file or directory
```

**Comment by nightlyone** [comment]
You (intentionally) cannot read files, which you didn't create before in the playground. 
see https://play.golang.org/p/hORbzSS4NT for an example.

**Comment by minux** [comment]
The tmp source file is created in another world (outside the nacl runtime)
and so the program cannot access it.

**Comment by odeke-em** [comment]
@nightlyone true, yap I tested that out too last night.
@minux ahh I see, could you please point me to a place I can see how this is done or might it be documented? I'll take a look at setting up my nacl environment locally then inspect it.

In relation to @nightlyone's comment, does this mean that the unintended consequence of intentionally sandboxing is that all godoc snippets whose underlying functionality involves the use of os.Open or even os.Stat(since these files were not created by the user) won't work on nacl?

**Comment by ysmolsky** [comment]
This example was fixed in godoc. Please close the issue, @bradfitz
