### ISSUE TITLE
spec: "special form" description of comma-ok assignments is incomplete

### ISSUE THREAD

**Issue by griesemer** [golang/go#15782]
The spec refers to "special forms" of assignments such as
```
v, ok = x.(T)
v, ok := x.(T)
var v, ok = x.(T)
```
etc. For completeness it should also mention
```
var v, ok T = x.(T)
```
where T is a type. (The only possible type is a boolean type, though).

**Comment by mdempsky** [comment]
var v, ok I = x.(T)

is also valid if I is an empty interface type.
