### ISSUE TITLE
build: crash when running all.bash

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#15786]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +1f8d276 Sat May 21 01:30:43 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
arl@carl-desktop:~/.golive/src$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/carl/go"
GORACE=""
GOROOT="/home/carl/.golive"
GOTOOLDIR="/home/carl/.golive/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build015270482=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
Tried to run all.bash

5. What did you see instead?

carl@carl-desktop:~/.golive/src$ ./all.bash 
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/carl/.goboot.
bootstrap/internal/sys
bootstrap/asm/internal/flags
bootstrap/internal/bio
bootstrap/compile/internal/big
bootstrap/internal/obj
bootstrap/internal/gcprog
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/mips
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/s390x
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/link/internal/ld
bootstrap/compile/internal/ssa
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/mips64
bootstrap/link/internal/ppc64
bootstrap/link/internal/s390x
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/gc
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/mips64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/s390x
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
encoding
errors
internal/race
internal/syscall/windows/sysdll
math
sort
sync/atomic
unicode
unicode/utf16
unicode/utf8
sync
container/heap
internal/singleflight
io
syscall
hash
hash/adler32
bytes
strings
strconv
bufio
path
reflect
encoding/base64
crypto
regexp/syntax
crypto/sha1
internal/syscall/windows
internal/syscall/windows/registry
time
regexp
os
os/signal
path/filepath
io/ioutil
encoding/binary
fmt
context
flag
go/token
log
net/url
text/template/parse
compress/flate
encoding/json
debug/dwarf
os/exec
go/scanner
go/ast
compress/zlib
text/template
debug/macho
debug/elf
go/parser
go/doc
go/build
cmd/go

##### Building packages and commands for linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
unicode
unicode/utf8
math
sync
sort
io
syscall
hash
hash/adler32
hash/crc32
container/heap
container/list
bytes
strings
strconv
bufio
path
text/tabwriter
compress/bzip2
container/ring
reflect
regexp/syntax
crypto
crypto/subtle
time
crypto/cipher
crypto/aes
math/rand
crypto/sha512
regexp
crypto/hmac
crypto/md5
internal/syscall/unix
crypto/rc4
os
crypto/sha1
crypto/sha256
encoding/base64
encoding/pem
internal/nettrace
internal/singleflight
path/filepath
encoding
encoding/ascii85
encoding/base32
unicode/utf16
vendor/golang.org/x/net/lex/httplex
io/ioutil
hash/crc64
hash/fnv
html
image/color
internal/syscall/windows/sysdll
runtime/debug
encoding/binary
fmt
image
image/color/palette
cmd/internal/sys
crypto/des
index/suffixarray
runtime/trace
image/internal/imageutil
math/cmplx
flag
log
debug/dwarf
compress/flate
debug/gosym
cmd/internal/obj
debug/plan9obj
cmd/vendor/golang.org/x/arch/arm/armasm
compress/zlib
cmd/vendor/golang.org/x/arch/x86/x86asm
debug/elf
cmd/internal/goobj
debug/macho
debug/pe
archive/tar
archive/zip
compress/gzip
compress/lzw
context
math/big
encoding/hex
go/token
cmd/internal/objfile
go/scanner
os/exec
go/ast
cmd/addr2line
database/sql/driver
database/sql
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
go/parser
crypto/rsa
crypto/x509/pkix
crypto/ecdsa
go/printer
encoding/csv
encoding/gob
encoding/json
encoding/xml
cmd/cgo
vendor/golang.org/x/net/http2/hpack
mime
mime/quotedprintable
net/http/internal
net/url
text/template/parse
go/constant
go/format
text/scanner
image/draw
go/types
image/gif
text/template
image/jpeg
image/png
go/doc
html/template
runtime/cgo
go/build
runtime/pprof
testing
net
internal/testenv
internal/trace
net/internal/socktest
os/signal
os/user
go/internal/gccgoimporter
go/internal/gcimporter
runtime/race
testing/iotest
testing/quick
cmd/api
cmd/internal/obj/arm
go/importer
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/x86
crypto/x509
crypto/tls
net/textproto
net/http/httptrace
log/syslog
mime/multipart
net/mail
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/internal/bio
cmd/compile/internal/big
cmd/compile/internal/ssa
net/http
net/smtp
cmd/asm/internal/arch
cmd/internal/gcprog
cmd/compile/internal/test
cmd/cover
cmd/asm/internal/asm
cmd/asm
cmd/dist
cmd/doc
cmd/fix
expvar
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/rpc
cmd/go
cmd/gofmt
net/rpc/jsonrpc
cmd/internal/pprof/profile
cmd/internal/pprof/svg
cmd/internal/pprof/tempfile
cmd/link/internal/ld
cmd/internal/pprof/plugin
cmd/internal/pprof/report
cmd/compile/internal/gc
cmd/internal/pprof/commands
cmd/internal/pprof/driver
cmd/internal/pprof/fetch
cmd/internal/pprof/symbolizer
cmd/internal/pprof/symbolz
cmd/nm
cmd/objdump
cmd/pack
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/pprof
cmd/trace
cmd/link
cmd/vet/internal/whitelist
cmd/vet
cmd/yacc
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile

##### Testing packages.
ok  	archive/tar	0.058s
ok  	archive/zip	0.067s
ok  	bufio	0.110s
ok  	bytes	0.149s
ok  	compress/bzip2	0.134s
ok  	compress/flate	1.394s
ok  	compress/gzip	0.031s
ok  	compress/lzw	0.007s
ok  	compress/zlib	0.034s
ok  	container/heap	0.008s
ok  	container/list	0.004s
ok  	container/ring	0.015s
ok  	context	0.929s
ok  	crypto/aes	0.044s
ok  	crypto/cipher	0.010s
ok  	crypto/des	0.014s
ok  	crypto/dsa	0.009s
ok  	crypto/ecdsa	0.101s
ok  	crypto/elliptic	0.043s
ok  	crypto/hmac	0.002s
ok  	crypto/md5	0.004s
ok  	crypto/rand	0.025s
ok  	crypto/rc4	0.119s
ok  	crypto/rsa	0.161s
ok  	crypto/sha1	0.004s
ok  	crypto/sha256	0.005s
ok  	crypto/sha512	0.008s
ok  	crypto/subtle	0.031s
ok  	crypto/tls	1.379s
ok  	crypto/x509	1.165s
ok  	database/sql	0.058s
ok  	database/sql/driver	0.016s
ok  	debug/dwarf	0.011s
ok  	debug/elf	0.024s
ok  	debug/gosym	0.289s
ok  	debug/macho	0.004s
ok  	debug/pe	0.011s
ok  	debug/plan9obj	0.004s
ok  	encoding/ascii85	0.006s
ok  	encoding/asn1	0.005s
ok  	encoding/base32	0.012s
ok  	encoding/base64	0.004s
ok  	encoding/binary	0.038s
ok  	encoding/csv	0.004s
ok  	encoding/gob	0.046s
ok  	encoding/hex	0.035s
ok  	encoding/json	0.332s
ok  	encoding/pem	0.034s
ok  	encoding/xml	0.021s
ok  	errors	0.003s
ok  	expvar	0.006s
ok  	flag	0.006s
ok  	fmt	0.155s
ok  	go/ast	0.016s
ok  	go/build	0.092s
ok  	go/constant	0.004s
ok  	go/doc	0.054s
ok  	go/format	0.026s
ok  	go/internal/gccgoimporter	0.004s
ok  	go/internal/gcimporter	0.589s
ok  	go/parser	0.049s
ok  	go/printer	0.657s
ok  	go/scanner	0.004s
ok  	go/token	0.038s
ok  	go/types	0.816s
ok  	hash/adler32	0.016s
ok  	hash/crc32	0.023s
ok  	hash/crc64	0.040s
ok  	hash/fnv	0.022s
ok  	html	0.017s
ok  	html/template	0.045s
ok  	image	0.153s
ok  	image/color	0.106s
ok  	image/draw	0.108s
ok  	image/gif	0.110s
ok  	image/jpeg	0.163s
ok  	image/png	0.053s
ok  	index/suffixarray	0.010s
ok  	internal/singleflight	0.013s
ok  	internal/trace	0.028s
ok  	io	0.020s
ok  	io/ioutil	0.005s
ok  	log	0.010s
ok  	log/syslog	2.022s
ok  	math	0.006s
ok  	math/big	0.505s
ok  	math/cmplx	0.003s
ok  	math/rand	0.095s
ok  	mime	0.010s
ok  	mime/multipart	0.408s
ok  	mime/quotedprintable	0.228s
ok  	net	1.482s
ok  	net/http	9.897s
ok  	net/http/cgi	0.401s
ok  	net/http/cookiejar	0.008s
ok  	net/http/fcgi	0.006s
ok  	net/http/httptest	0.012s
ok  	net/http/httptrace	0.005s
ok  	net/http/httputil	0.043s
ok  	net/http/internal	0.008s
ok  	net/internal/socktest	0.006s
ok  	net/mail	0.006s
ok  	net/rpc	0.040s
ok  	net/rpc/jsonrpc	0.009s
ok  	net/smtp	0.063s
ok  	net/textproto	0.005s
ok  	net/url	0.007s
ok  	os	0.341s
ok  	os/exec	0.288s
ok  	os/signal	4.284s
ok  	os/user	0.003s
ok  	path	0.004s
ok  	path/filepath	0.011s
ok  	reflect	0.085s
ok  	regexp	0.118s
ok  	regexp/syntax	0.398s
ok  	runtime	18.985s
ok  	runtime/debug	0.024s
ok  	runtime/internal/atomic	0.149s
ok  	runtime/internal/sys	0.004s
ok  	runtime/pprof	1.436s
ok  	runtime/trace	2.935s
ok  	sort	0.060s
ok  	strconv	0.779s
ok  	strings	0.147s
ok  	sync	0.174s
ok  	sync/atomic	0.133s
ok  	syscall	0.113s
ok  	testing	2.404s
ok  	testing/quick	0.113s
ok  	text/scanner	0.032s
ok  	text/tabwriter	0.025s
ok  	text/template	0.586s
ok  	text/template/parse	0.007s
ok  	time	2.464s
ok  	unicode	0.014s
ok  	unicode/utf16	0.012s
ok  	unicode/utf8	0.005s
ok  	vendor/golang.org/x/net/http2/hpack	0.006s
ok  	vendor/golang.org/x/net/lex/httplex	0.016s
ok  	cmd/addr2line	0.616s
ok  	cmd/api	0.005s
ok  	cmd/asm/internal/asm	0.262s
ok  	cmd/asm/internal/lex	0.003s
ok  	cmd/compile/internal/big	1.231s
ok  	cmd/compile/internal/gc	19.399s
ok  	cmd/compile/internal/ssa	0.300s
ok  	cmd/compile/internal/test	0.010s
ok  	cmd/cover	1.592s
ok  	cmd/doc	0.024s
ok  	cmd/fix	0.015s
ok  	cmd/go	36.424s
ok  	cmd/gofmt	0.036s
ok  	cmd/internal/goobj	0.010s
ok  	cmd/internal/obj	0.014s
ok  	cmd/internal/obj/x86	0.004s
ok  	cmd/internal/pprof/profile	0.005s
ok  	cmd/link	0.004s
ok  	cmd/nm	0.908s
ok  	cmd/objdump	2.459s
ok  	cmd/pack	2.045s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.021s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	0.341s
ok  	cmd/vet	2.902s

##### GOMAXPROCS=2 runtime -cpu=1,2,4
ok  	runtime	32.062s

##### Testing without libgcc.
ok  	crypto/x509	1.173s
ok  	net	0.006s
ok  	os/user	0.024s

##### sync -cpu=10
ok  	sync	0.156s

##### ../misc/cgo/test
PASS
ok  	_/home/carl/.golive/misc/cgo/test	1.736s
PASS
ok  	_/home/carl/.golive/misc/cgo/test	1.671s
PASS
ok  	_/home/carl/.golive/misc/cgo/test	1.660s
PASS
ok  	_/home/carl/.golive/misc/cgo/testtls	0.003s
PASS
ok  	_/home/carl/.golive/misc/cgo/testtls	0.002s
PASS
ok  	_/home/carl/.golive/misc/cgo/testtls	0.002s
PASS
ok  	_/home/carl/.golive/misc/cgo/nocgo	0.021s
PASS
ok  	_/home/carl/.golive/misc/cgo/nocgo	0.003s
PASS
ok  	_/home/carl/.golive/misc/cgo/nocgo	0.008s
PASS
ok  	_/home/carl/.golive/misc/cgo/test	1.641s
PASS
ok  	_/home/carl/.golive/misc/cgo/testtls	0.003s
PASS
ok  	_/home/carl/.golive/misc/cgo/nocgo	0.025s

##### Testing race detector
ok  	runtime/race	2.850s
ok  	flag	1.031s
ok  	os/exec	2.024s
PASS
scatter = 0x5b3200
hello from C
sqrt is: 0
ok  	_/home/carl/.golive/misc/cgo/test	3.064s
ok  	flag	1.041s
ok  	os/exec	2.045s

##### misc/cgo/testcarchive
PASS

##### ../misc/cgo/testcshared
ok

##### ../misc/cgo/testshared
PASS
ok  	_/home/carl/.golive/misc/cgo/testshared	12.076s

##### ../misc/cgo/testsanitizers
skipping msan tests: -fsanitize=memory not supported

##### ../test/bench/go1
testing: warning: no tests to run
PASS
ok  	_/home/carl/.golive/test/bench/go1	7.815s

##### API check
Error running API checker: exit status 1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 1 [running]:
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:500 +0x18c
go/types.(*Checker).handleBailout(0xc4200e80e0, 0xc4202fb620)
	/home/carl/.golive/src/go/types/check.go:213 +0x9f
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:458 +0x226
go/types.(*Checker).handleBailout(0xc4200e81c0, 0xc4202fab28)
	/home/carl/.golive/src/go/types/check.go:213 +0x9f
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:458 +0x226
go/types.(*Checker).handleBailout(0xc4200e8380, 0xc4202fa030)
	/home/carl/.golive/src/go/types/check.go:213 +0x9f
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:458 +0x226
go/types.(*Checker).handleBailout(0xc4200e8460, 0xc4202f9538)
	/home/carl/.golive/src/go/types/check.go:213 +0x9f
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:458 +0x226
go/parser.ParseFile.func1(0xc4202f8a48, 0xc42026a780, 0xc4202f8a50)
	/home/carl/.golive/src/go/parser/interface.go:96 +0x2b1
panic(0x5d1020, 0xc42000e130)
	/home/carl/.golive/src/runtime/panic.go:458 +0x226
exit status 1
2016/05/21 10:45:24 Failed: exit status 1
2016/05/21 10:45:24 FAILED

**Comment by ianlancetaylor** [comment]
Is this repeatable?  I don't recall seeing anything like this.

**Comment by carl-mastrangelo** [comment]
Not repeatable no.   Rerunning the command actually worked, so unfortunately I can't provide any more detail. I can try running it a few more times, but I assumed the stack trace would be enough to give a hint.

**Comment by ianlancetaylor** [comment]
Unfortunately it tells me nothing.  It looks like memory has become unreadable or something.  The original point of the failure is not reported.

I'm going to close this as a bizarre fluke but please add a comment if it happens again.
