### ISSUE TITLE
Time.After doesn't release memory

### ISSUE THREAD

**Issue by dhiltonp** [golang/go#15781]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version: 1.6

2. What operating system and processor architecture are you using (`go env`)?
amd64, Debian 8 (stretch/sid)

3. What did you do?
Something equivalent to this:

```
package main

import (
	"errors"
	"time"
)

var q chan []byte

func push(data []byte) error {
	select {
	case q <- data:
		return nil
	case <-time.After(time.Millisecond * 4):
		return errors.New("push timed out")
	}
}

func main() {
	q = make(chan []byte)

	for true {
		go func() {
			data := []byte("we are bytes")
			push(data)
		}()
	}
}
```

It would take up a lot of memory and go oom within seconds on the machine in question.

```
[  208.259383] Out of memory: Kill process 1032 (timermem) score 883 or sacrifice child
[  208.259412] Killed process 1032 (timermem) total-vm:1229512kB, anon-rss:412480kB, file-rss:0kB
```

If I ran the debugger and stopped it early, I saw something like this:
<img width="422" alt="screen shot 2016-05-20 at 5 57 19 pm" src="https://cloud.githubusercontent.com/assets/111300/15444970/d999f3d8-1eb4-11e6-8af4-afd604c2610a.png">

----------------

I've used this on a MBP with 16GB of ram. The sample program got hit by the OOM killer after about 5 minutes.

**Comment by bradfitz** [comment]
The timer is a red herring. Your program is starting new goroutines as quickly as it can in a loop.

If there's an actual problem with timers, it needs a demonstration program without unrelated allocation problems.

**Comment by dhiltonp** [comment]
Agreed, in the case of this program.

However, it was fixed in my original program via:

```
func push(data []byte) error {
	timeout := time.NewTimer(time.Millisecond * 4)
	defer timeout.Stop()
	
	select {
	case q <- data:
		return nil
	case <- timeout.C:
		return errors.New("DiskQ.Push timed out")
	}
}
```
