### ISSUE TITLE
net/http: ServeContent does not send Content-Range in 416 errors

### ISSUE THREAD

**Issue by anacrolix** [golang/go#15798]
https://tools.ietf.org/html/rfc7233#section-4.4 says that if the range cannot be satisfied because it is beyond the length of the instance, Content-Range should be returned with a 416 containing the instance length. This does not occur with http.ServeContent.

**Comment by quentinmit** [comment]
/cc @bradfitz @adg

With anything HTTP... I defer to the experts to decide if we should follow the spec.

**Comment by adg** [comment]
Sure, seems like a failure mode we overlooked in the implementation. Also seems like low hanging fruit for anyone looking for something to do.
