### ISSUE TITLE
cmd/go: test -cover confused by import "." in xtest

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#15795]
#### Version of Go
`1.6`, also replicated on `devel +4b6e560`.

#### Operating system and processor architecture
Operating System: `darwin`
Processor Architecture: `amd64`

#### What I did
  * `git clone https://github.com/leighmcculloch/static.git`
  * `git checkout with-xtests`
  * `go test -cover`
  * `git diff with-xtests..with-tests` – change the tests package from `static_test` to `static`
  * `git checkout with-tests`
  * `go test -cover`

#### What I expected to see
I expected to see a coverage percentage for the `static` package that included the test files that are in the same directory but have their package at the top of their files named `static_test`. I expected that it wouldn't matter if the tests were in the package `static_test` or `static`, the coverage should be the same.
```
$ git checkout with-xtests
Switched to branch 'with-xtests'
Your branch is up-to-date with 'origin/with-xtests'.

$ go test -cover
PASS
coverage: 93.9% of statements
ok      github.com/leighmcculloch/static        0.023s

$ git checkout with-tests
Switched to branch 'with-tests'
Your branch is up-to-date with 'origin/with-tests'.

$ go test -cover
PASS
coverage: 93.9% of statements
ok      github.com/leighmcculloch/static        0.028s
```

Additionally expected that looking at the coverage in the HTML format would show most lines green.

#### What I saw instead
The coverage percentage for the `static` package is only `20.4%` and is not including tests that are named as being in the `static_test` package, even though those tests are in the same directory as the `static` package and are being executed.

When I change the package the tests live in from `static_test` to `static`, they are included in the coverage and the coverage is `93.9%`.
```
$ git checkout with-xtests
Switched to branch 'with-xtests'
Your branch is up-to-date with 'origin/with-xtests'.

$ go test -cover
PASS
coverage: 20.4% of statements
ok      github.com/leighmcculloch/static        0.023s

$ git checkout with-tests
Switched to branch 'with-tests'
Your branch is up-to-date with 'origin/with-tests'.

$ go test -cover
PASS
coverage: 93.9% of statements
ok      github.com/leighmcculloch/static        0.028s
```

Additionally saw that looking at the coverage in the HTML format showed most lines red.

#### What I've attempted so far to fix it
I've looked (naively) at the source of [cmd/go/test.go](https://github.com/golang/go/blob/master/src/cmd/go/test.go) and I can see the tests grouped in `pxtest` are not recompiled, there are no coverVars associated with pxtest. I attempted to fix this by adding the `p.GoFiles` to the `pxtest`s `coverVars` but I ended up with errors like the below. I'm guessing this is because there's an assumption being made somewhere that files included in coverage are in the same package as the tests.
```
/var/folders/yr/llg1db9x72v7dgycypwy9pyc0000gq/T/go-build725799557/github.com/leighmcculloch/static/_test/_testmain.go:109: undefined: static_test.GoCover_6 in static_test.GoCover_6.Count
```

I plan to continue looking at this in more depth, but hoped I could get some suggestions, pointers or confirmation of where I should be looking.

**Comment by bradfitz** [comment]
@robpike, are you still the cmd/cover maintainer?

**Comment by robpike** [comment]
Where is the comment I wrote when I added the WaitingForInfo tag?

What it said was this: Cover handles this situation correctly in packages such as fmt. And I tried changing encoding/binary to have both internal and external tests, and cover got the same result both times. So I don't understand the problem.

Can you please create a reproducing example that is self-contained?

**Comment by rsc** [comment]
@leighmcculloch, the problem is caused by the `import "."` in your xtest versions. The go command should really disallow that. The convention for an xtest is to change

	package static
	
to

	package static_test
	
	import . "github.com/leighmcculloch/static"

and then you don't need to change anything else (in particular you don't have to put a "static." prefix on every identifier). That produces the right coverage percentages.

If instead I do

	package static_test
	
	import . "."

then I get the result you describe, where the coverage percentage does not include all the lines in the test.

I can't remember where the issue is about disallowing import of ".", but this may be an argument one way or the other in that issue.

@robpike, no need to work on this.

**Comment by leighmcculloch** [comment]
Ah fantastic. Thank you!!!

I can confirm replacing `import "."` with `import "github.com/leighmcculloch/static"` (e.g. leighmcculloch/static@5890d89e84e448955fa317098840854402fbbd01) results in the xtests returning the correct coverage.

```
$ git checkout with-xtests
Switched to branch 'with-xtests'
Your branch is up-to-date with 'origin/with-xtests'.

$ go test -cover
PASS
coverage: 93.9% of statements
ok      github.com/leighmcculloch/static        0.020s

$ git checkout with-tests
Switched to branch 'with-tests'
Your branch is up-to-date with 'origin/with-tests'.

$ go test -cover
PASS
coverage: 93.9% of statements
ok      github.com/leighmcculloch/static        0.020s
```

I will avoid use of `import "."` in the future.
