### ISSUE TITLE
tour: Go Playground sembra non funzionare

### ISSUE THREAD

**Issue by mordillo123** [golang/go#15791]
Contesto: https://go-tour-ita.appspot.com/basics/3

Quando si eseguono i programmi inclusi ne tour non si ottiene risultato (neanche messaggi di errore)
la versione in lingua inglese invece funziona correttamente.
Uso:

```
Google Chrome	50.0.2661.102 (Official Build) (64-bit)
Revision	c26c0312e940221c424c2730ef72be2c69ac1b67-refs/branch-heads/2661@{#680}
OS	Linux 
Blink	537.36 (@c26c0312e940221c424c2730ef72be2c69ac1b67)
JavaScript	V8 5.0.71.48
Flash	21.0.0.242
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
```

**Comment by ianlancetaylor** [comment]
CC @campoy 

I have no idea what our options are here.

**Comment by adg** [comment]
This is #15693

**Comment by mordillo123** [comment]
I apologize, I'm sorry for Italian writing. I have supposed that was a local/translation project issue tracker.
