### ISSUE TITLE
cmd/trace,cmd/pprof: should error out when both symbols and binary are missing

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#15792]
Go 1.7 added the option to generate trace/pprof files with symbols annotations, so the `trace` help reads:

```
[pkg.test] argument is required for traces produced by Go 1.6 and below.
Go 1.7 does not require the binary argument.
```

However, if a trace/pprof generated with Go 1.6 and no binary are supplied to the tool, no error is shown. Instead, the output is simply broken (the profiles are all one empty node, for example).

cmd/trace and cmd/pprof should check if the trace/pprof has annotations, and if not require the binary to be supplied.

**Comment by FiloSottile** [comment]
cc: @dvyukov

**Comment by cespare** [comment]
#10863 tracks this for cmd/pprof already, and a fix (https://golang.org/cl/23323/) was just mailed for that. (Although it only adds a warning; an error might be better.)

**Comment by FiloSottile** [comment]
c3818e5 seems to be a fix for cmd/trace

**Comment by hyangah** [comment]
cmd/trace already addressed this issue.
go uses vendored pprof now so if this fix is still necessary for pprof, let's open an issue in pprof upstream.
