### ISSUE TITLE
A issue about fork

### ISSUE THREAD

**Issue by ruinanchen** [golang/go#15790]
I've been stucked with this issue for days:
I listen a port with a fd in master process. Then I fork a new child process which inhert the fd.
I don't want to kill the master process, and How can I accept connection no mattter master process or child process????

I has try somes: If master process is alive,  only it can accept connection; it is killed, child do it.

My golang's version is 1.6.2.
Thx, Look forward to your reply！！！

**Comment by ianlancetaylor** [comment]
We don't the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions for good places to ask.  Thanks.

**Comment by ruinanchen** [comment]
OK, sorry!!!
