### ISSUE TITLE
x/exp/io: distinguish transport layer config from protocol required config

### ISSUE THREAD

**Issue by rakyll** [golang/go#15803]
Currently, in order to keep the driver implementations extendible enough, driver.Opener interfaces requires no arguments. But it is creating barriers in the reusability of certain configuration fields.

I implemented the following high-level Grove LCD package and running it against i2c.Devfs and a custom driver that talks through a web service.
```
package grovelcd

import  "golang.org/x/exp/io/i2c/driver"
func New(o driver.Opener) (*GroveLCD, error) 
```

```
glcd, err := grovelcd.New(&grovelcd.WebProxy{
	URL: "http://192.168.159.121:8080",
})

glcd, err := grovelcd.New(&i2c.Devfs{Dev: "/dev/i2c-1", Addr: 0x62})
```

What is not nice is that grovelcd package cannot embed the I2C address required by the device at the device library level since Addr needs to be injected by the transport layer, i2c.Devfs.

We should distinguish such arguments from the driver implementation configurations to allow libraries to encapsulate the protocol details from the users.

The new i2c.Driver should look like:

```
type Opener interface {
    Open(addr int) (Conn, error)
}
```

And the user should only care about opening the right bus, address will be embedded in grovelcd package. 

```
glcd, err := grovelcd.New(&i2c.Devfs{Dev: "/dev/i2c-1"})
```

Thoughts?

/cc @minux @proppy

**Comment by proppy** [comment]
+1 for passing protocol level argument (i.e: addresses), independently from backend specific args (`path/to/devfs/device`).

**Comment by minux** [comment]
SGTM.

**Comment by mattetti** [comment]
Having to pass the address all the time is confusing for new users and since it's static and related to the i2c device you are targeting. The part I don't quite understand tho is how/why the proxy would know about the address to implement the `Opener` interface, more specifically the `addr` argument:

`glcd, err := grovelcd.New(&grovelcd.WebProxy{
    URL: "http://192.168.159.121:8080",
})`

Shouldn't the `addr` be available on the package already and therefore the interface could be simplified to:

`
type Opener interface {
    Open() (Conn, error)
}
`

**Comment by rakyll** [comment]
> Shouldn't the addr be available on the package already and therefore the interface could be simplified to:

This is exactly why we are putting the addr back to Open, so the devfs driver won't need you to pass it. Higher level packages, such as the grovelcd package, can hardcode it and encapsulate from the user.

```
grovelcd.New(&i2c.Devfs{Dev: "/dev/i2c-1"})
```

Am I misunderstanding anything?

**Comment by mattetti** [comment]
No, it was me being confused. It looks great
