### ISSUE TITLE
package io: read method can not return if no "EOF" 

### ISSUE THREAD

**Issue by zjxpsetp** [golang/go#15800]
I found a bug in this package (I used version 1.6)

I use the following code:
`io.Copy(local_conn, remote_conn)`
And actually, it will call
`for {
		nr, er := src.Read(buf)
		if nr > 0 {
			nw, ew := dst.Write(buf[0:nr])
			if nw > 0 {
				written += int64(nw)
			}
			if ew != nil {
				err = ew
				break
			}
			if nr != nw {
				err = ErrShortWrite
				break
			}
		}
		if er == EOF {
			break
		}
		if er != nil {
			err = er
			break
		}
	}`

if the data source doesn't include EOF, it will never return from "Read". How to handle it?

**Comment by nuss-justin** [comment]
This is not a bug. This is the way io.Copy was designed and also the basic idea for IO in go. 

The first sentence in the description of io.Copy explains this:

```
Copy copies from src to dst until either EOF is reached on src or an error occurs.
```

Most functions that do some kind of IO use io.EOF to signal the end of a stream of data. The functions and interfaces in the io package are built around this idea. 

Seeing it from another angle, without the io.EOF many functions wouldn't know when to stop. The same holds for code that you write. Without an explicit mechanism like io.EOF you would need to know the exact amount bytes to read or use some other kind of mechanism (like delimiters).

If your source doesn't return an io.EOF, it is from the point of view of the io package, an infinite stream. If you don't want your code to "hang" forever, you can wrap your reader inside another reader, for example with a [LimitReader](https://golang.org/pkg/io/#LimitReader) or you could implement a type that wraps your io.Reader and adds timeouts to the Read() method.

**Comment by dsnet** [comment]
You could also use [`io.CopyN`](https://golang.org/pkg/io/#CopyN), which uses io.LimitReader under the hood.
