### ISSUE TITLE
Assignment in scope reverts to value out of scope with goto

### ISSUE THREAD

**Issue by titpetric** [golang/go#15817]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.2 linux/amd64 + play.golang.org.

3. What did you do?

https://play.golang.org/p/-T0o_8p5_T

4. What did you expect to see?

~~~
Err: Hello world (inner scope)
Err: Hello world (outer scope)
~~~

I expected this because the `err` variable which is modified in the inner scope is declared in the outer one. If inner scope uses `=` for assignment (instead of `:=`), then `err` holds it's value in the outer scope. An example of a working modification of err: https://play.golang.org/p/Fh0hwMvb53

5. What did you see instead?

~~~
Err: Hello world
Err: Should not exist
~~~

If i declare `err` in the outer scope, and use `isCondition, err := conditional();` in the inner scope, then the value of `err` is reset to whatever it was when I hit `goto Finish` (jump to label).

**Comment by titpetric** [comment]
Investigating further, it seems it's not related to `goto`, but a general capability of the language. For example, this gives the same result:

~~~
func testLabelScope() {
	var err error
	err = errors.New("Should not exist")
	{
		err := errors.New("What is this?");
		fmt.Printf("Err: %s\n", err)
	}
	fmt.Printf("Err: %s\n", err)
}
~~~

In this case I'd expect a build error. I'm not sure that allowing variable redecleration in inner scopes is... fine. You can see and modify outer scope variables, but as soon as you declare a variable in the inner scope, you can't modify the one in the outer one. It's... confusing.

**Comment by ianlancetaylor** [comment]
That is how the language works.  The `:=` operator used in a inner block declares a new variable whose scope is only within that block.  See https://golang.org/ref/spec#Short_variable_declarations .

For much more discussion about `:=` see issue #377.  Closing this one.

**Comment by titpetric** [comment]
It's also allowed with 'var' @ianlancetaylor

~~~
var x int
x = 1
{
    var x int
    x = 2
}
~~~

Results in same behaviour, no short declaration there.

**Comment by ianlancetaylor** [comment]
@titpetric Yes.  Go is a block scoped language.

**Comment by titpetric** [comment]
Okay, thank you. I'll file this under TIL :)

**Comment by griesemer** [comment]
@titpetric Just FYI, this is not in any way unusual or specific to Go. This is absolutely normal behavior for block-structured languages, and established practice since the 1960s.

**Comment by titpetric** [comment]
@griesemer From what I remember, variable declarations in C, C++ and Java are block scoped, but don't allow redeclaration within a nested block. I never noticed redecleration in any of these languages. You couldn't do something like this in any of them:

~~~
for (int x=0; x < 10; x++) {
    offset = x;
    for (int x=0; x < 10; x++) {
         pos = offset + (x*10);
    }
}
~~~

There might be other block-scoped languages that apply a similar behaviour as golang, I just didn't come across them in the last 20 years or so. And the whole redecleration pattern is anti- even in php, javascript, etc. - since they are "anything goes" languages, it takes discipline to avoid problems.

I'd appreciate a lint check or some kind of static analysis step on build time tell me that I'm doing something that might be unexpected/edge case/fringe. I realize execution behavior here is not likely to change, so I'm wondering if the tools around it can notify the developer of this at some point (a la gcc)

**Comment by kostya-sh** [comment]
Java and C# do not allow shadowing of local variables. A local variable can
shadow a field though. If I remember correctly C and C++ have the same
rules as Go wrt variable shadowing.

You can use

go vet -shadow [-shadowstrict]

to see shadowed variables in Go files.

I must admit that shadowed variables have been the source of a few hard to
find bugs for me initially. After some practice this becomes less of an
issue.

**Comment by titpetric** [comment]
@griesemer @kostya-sh I stand corrected, c has same result as golang in this case. I threw up a small program just to test it, and oh my... :)

~~~
int main() {
    int pos, offset;
    int x;
    for (x=0; x < 3; x++) {
        offset = x;
        printf("x %d ", x);
        int x;
        for (x=0; x < 3; x++) {
            pos = offset + (x*3);
            printf("y %d (%d) ", x, pos);
        }
        printf("ex %d\n", x);
    }
}
~~~

@kostya-sh thank you for info about `go vet`, i'll look into it - seems like a good pre-build step if you're trying to discourage variable shadowing. Global-vs-function scope is easier to control just by keeping global scope clean, but inside function blocks I expect I'll be having a few more hard to find bugs in my future, as you had ;)

**Comment by griesemer** [comment]
@titpetric To be very clear: "Shadowing" is not the same as "redeclaration". A redeclaration is a Go-specific concept which permits a variable, which must have been previously declared **in the same block**, to appear again on the lhs of a `:=` short variable declaration.

Shadowing is the notion of a new, different, but equally named object (variable, constant, type, etc.) making another object declared in an outer block (scope) inaccessible as that object is now "in the shadow" of the object declared in the inner block.

Java is one of the first languages which doesn't permit shadowing, and it was then followed by C#. The idea in Java was to prevent programming errors.

Preventing shadowing is a pretty severe violation of the encapsulation notion of a block: If shadowing is not permitted, the validity of identifier declarations inside a block depend on the surroundings of that block. The choice of new identifiers is all of sudden restricted by the enclosing environment.

The solution here is not to restrict the language unnaturally, but to provide tools (go vet) to find common errors.
