### ISSUE TITLE
Way to disable runtime environment variables

### ISSUE THREAD

**Issue by RaveNoX** [golang/go#15819]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.2 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\projects\golang
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?
Building software

4. What did you expect to see?
Way to disable runtime environment variables (like GOMAXPROCS, GODEBUG, etc...) for release build which will shipped to end users. I don't want to get this funtional to end users of my program.

5. What did you see instead?
I can't find any way to do this at this moment

**Comment by ianlancetaylor** [comment]
There is no way to prevent a Go program from checking those environment variables.  That is not a feature we are going to add without a good reason.  Having those environment variables is complicated enough.  Having a way to disable them makes the runtime that much more complicated.
