### ISSUE TITLE
cmd/go: No support for vendoring with gccgo toolchain.

### ISSUE THREAD

**Issue by mwhudson** [golang/go#15814]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +ebbe4f8 Wed May 18 21:20:33 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

Irrelevant.

3. What did you do?

```
$ cat $GOPATH/src/vendor/bar/bar.go
package bar

var World = "world"
$ cat $GOPATH/src/foo/foo.go
package main

import (
	"fmt"

	"bar"
)

func main () {
	fmt.Println("Hello", bar.World)
}
$ go build -compiler gccgo foo
```

4. What did you expect to see?

Nothing, and an executable 'foo' created.

5. What did you see instead?

```
$ go build -compiler gccgo foo
# foo
src/foo/foo.go:6:5: error: import file ‘bar’ not found
  "bar"
     ^
src/foo/foo.go:10:23: error: reference to undefined name ‘bar’
  fmt.Println("Hello", bar.World)
                       ^
```

This isn't that serious as I mostly use gccgo for packaging purposes and most packages are not built with bundled dependencies, but it's caused one package build failure I know about (https://launchpad.net/ubuntu/+source/docker-registry/2.3.1~ds2-1/+build/9640391).

**Comment by urandom** [comment]
Perhaps this is related to #15628

**Comment by mwhudson** [comment]
Oh yes, that's the same bug. Thought I searched first, apparently not!
