### ISSUE TITLE
tools/container/intsets does not properly support gccgo 

### ISSUE THREAD

**Issue by tychoish** [golang/go#15816]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.4.2 (go) in GCC (5.3.0) 

2. What operating system and processor architecture are you using (`go env`)?

Various. 

3. Explain the issue?

Attempted to build [graph from gonum](https://godoc.org/github.com/gonum/graph), which produced the following error while building dependencies: 

    imports golang.org/x/tools/container/intsets: C source files not allowed when not using cgo: popcnt_gccgo_c.c

**Comment by ianlancetaylor** [comment]
I can repeat the problem with Go 1.4, but it is fixed in Go 1.5 and later.  Go 1.4 is no longer supported, so closing.
