### ISSUE TITLE
doc: write release notes

### ISSUE THREAD

**Issue by rsc** [golang/go#15810]
Go 1.7 beta needs proper release notes. They are in progress.

**Comment by dsnet** [comment]
Slight change in `compress/flate` in that it now returns `io.EOF` eagerly. This may break some tests that incorrectly assumed `flate` never did that.

**Comment by kostya-sh** [comment]
https://tip.golang.org/doc/go1.7 still mentions SizedReaderAt and File.Size

Also new package net/http/httptrace (https://tip.golang.org/pkg/net/http/httptrace/) is not mentioned.

**Comment by rsc** [comment]
Leaving these last few fixes for @adg. Thanks for catching those @kostya-sh. For that matter api/next.txt needs updating too.

**Comment by rsc** [comment]
@adg, in addition to what @kostya-sh said, see @dsnet's comment above.

**Comment by adg** [comment]
I believe the docs are in good shape for the beta now.

**Comment by tombergan** [comment]
Still no mention of net/http/httptrace
/cc @bradfitz

**Comment by adg** [comment]
@tombergan I'm on it.

**Comment by robpike** [comment]
Ignore this update. Testing.

**Comment by client9** [comment]
Hello!

not sure if this is separate issue or not.  My apologizes on nitpicking a sentence but this one confused me.   In the "Minor changes to the library" is this

```
compress/flate
As noted above, there are significant performance optimizations throughout the package.
```

1. It's not "noted above".  This is the first mention of `compress/flate`.  Its not noted in the performance section, although this appears to be a 2x improvement in many cases. 
2. is this "significant" or "minor".  The is in the "minor changes" section but this is "significant". Which is it?

Maybe a simpler statement such as 

"There are many performance optimizations throughout the package."  

would be more clear.

Looking forward to 1.7

thanks!

n

**Comment by broady** [comment]
@client9 good point.

@adg, others: should we close this out soon? What is remaining?

**Comment by bradfitz** [comment]
Seems done enough for me. I'd just fix @client9's thing and remove the DRAFT heading.
