### ISSUE TITLE
x/exp/io: support for interrupt pins

### ISSUE THREAD

**Issue by mattetti** [golang/go#15821]
In a lot of cases polling a pin for its state is sub optimum, being able to rely on interrupts is kind a convenient way to reduce the latency of change detection and avoid potential bugs. While this is not needed everywhere, I think it would be great to have that in the x/exp/io package.

This approach was implemented in the embd package using the following interface:
https://github.com/kidoman/embd/blob/master/gpio.go#L37

And implementing it on linux using epoll:
https://github.com/kidoman/embd/blob/master/host/generic/interrupt.go

@rakyll how do you feel about supporting such an approach?

**Comment by minux** [comment]
We need the runtime poller to be exposed first.

As for the API, I'm not so keen on callback based ones, and I think we
should use channels, which ties nicely with other parts of Go. We could
also add a convenience blocking API like "wait for certain level (with
optional debounce) or edge" that mimic our Reader/Writer interfaces (blocks
the goroutine until the event arrives).

**Comment by mattetti** [comment]
I agree about avoiding a callback API and a using channels + blocking API

**Comment by rakyll** [comment]
Closing because we have removed the gpio package from io. We should discuss the design on a different medium.
