### ISSUE TITLE
Chdir fails for relative paths with tilde ~

### ISSUE THREAD

**Issue by karysto** [golang/go#15827]
1. What version of Go are you using (`go version`)?
`go version go1.6.1 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/karysto/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
--
Playground Link:
https://play.golang.org/p/DpGGD2SLhu

First create a directory using `mkdir ~/test_from_go` (since `os.Mkdir` also fails for `~` paths).
Then run `os.Chdir("~/test_from_go")` using the relative `~/` path as the argument.

Using the absolute path, `/home/<USER_NAME>/test_from_go` works. The documentation for `os.Chdir` should be more specific stating that paths using `~` fail. It currently states: 

From https://golang.org/pkg/os/#Chdir:
```
Chdir changes the current working directory to the file, which must be a directory. If there is an error, it will be of type *PathError.
```

4. What did you expect to see?
No stdout output and the created directory `~/test_from_go`

5. What did you see instead?
An error. The error thrown is `chdir ~/test_from_go: No such file or directory`.

**Comment by minux** [comment]
~ is expanded by the shell. This is working as intended and I don't think
we need to document that. It's similar to why os.Mkdir("$HOME/Go") won't
work as expected.

**Comment by karysto** [comment]
A note, I understand that Go's filesystem interface is meant to be cross-platform. I'm proposing an update to the documentation for `os.Chdir` about requiring absolute paths, so that it's understood immediately what works and doesn't.

**Comment by minux** [comment]
Chdir does support relative path (e.g. ./abc/def), but ~/abc is not a
relative path (it is absolute path after shell expands ~)

**Comment by karysto** [comment]
Ah you're right, I appreciate the quick help.
