### ISSUE TITLE
Workaround for issue #3117

### ISSUE THREAD

**Issue by tj800x** [golang/go#15828]
This workaround for issue #3117 works in Go 1.6 (amd64, windows).

//This doesn't work as per https://github.com/golang/go/issues/3117 .
//var m = map[string]struct{x, y int} {
//    "foo": {2, 3},
//}

//This syntax works by changing the comma to a semi-colon 
//and specifying the type for both members
var m = map[string]*struct{x int; y int} {
	"foo": {20, 30},
	"bar": {51, 81},
}

https://play.golang.org/p/tCCJr5iKpP

That issue is closed so I'm posting here.

**Comment by griesemer** [comment]
Please do not use the issue tracker for discussions.

Note also, that this has nothing to do with #3117, which already states a work-around.
Also, both variable declarations above work, there's no difference between `struct{x, y int}` and `struct{x int; y int}` as far as the types are concerned.
