### ISSUE TITLE
The asn1 Marshal/Unmarshal get confused if I use a type instead the original type

### ISSUE THREAD

**Issue by ggeorgiev** [golang/go#15826]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/.../golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="/usr/local/bin/gcc-5"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="/usr/local/bin/c++-5"
CGO_ENABLED="1"

3. What did you do?
If I have
id_sha1 = asn1.ObjectIdentifier{1, 3, 14, 3, 2, 26}
type Foo struct {
    oid asn1.ObjectIdentifier
}
this works correctly, but if I change it to:

type AlgorithmId asn1.ObjectIdentifier
id_sha1 = AlgorithmId{1, 3, 14, 3, 2, 26}
type Foo struct {
    oid AlgorithmId
}

which seems to be the way most of the asn1 documentations are written the asn1 marshaling gets confused.

4. What did you expect to see?
I would expect the marshaller to be smart enough to recognize that a type is originating from the asn1.ObjectIdentifier and serialize it as such

5. What did you see instead?
The asn1.ObjectIdentifier is serialized as a binary blob

**Comment by ianlancetaylor** [comment]
In Go a new type is a different type, it's not an alias for an existing type.  There isn't any way that the encoding/asn1 package can detect that you are using a type based on ObjectIdentifier, rather than any other []int.  If you need to marshal as an object identifier, you need to use ObjectIdentifier.

**Comment by ggeorgiev** [comment]
Hi Ian,


This is a great golang feature. It seems though that such info should be provided from the reflection. Similarly as there is MapOf, ChanOf, PtrTo etc, maybe it is a good idea if there is Type method ... say BasedOn that returns the type the current one was based on and this could be used in asn1 to detect such cases.

Thanks,

George


________________________________
