### ISSUE TITLE
cmd/compile: compute builtin import data directly from source files

### ISSUE THREAD

**Issue by griesemer** [golang/go#15839]
builtin.go contains the export data for the built-in and unsafe package. It is created by running mkbuiltin.go which runs a special compilation over the sources in the builtin directory and then extracts the export data.

A change to the export data format requires a careful multi-step process to update the data in builtin.go; see issue #15835.

Investigate generation of the builtin and unsafe package export data directly from the source files (they are small). This would eliminate the need for builtin.go and mkbuiltin.go and corresponding tests and make it much easier to play with export format changes.

**Comment by rsc** [comment]
Bumping priority here. Not sure if @griesemer or @mdempsky is the one working on it.

**Comment by griesemer** [comment]
This is now a duplicate of #17508 which has been fixed.

**Comment by griesemer** [comment]
https://go-review.googlesource.com/c/31433/ removed the need to handle the unsafe package via builtin.go.

https://go-review.googlesource.com/c/31493/ generates builtin.go directly from the source and uses the go/* libs to do so.
