### ISSUE TITLE
reflect: spurious looking race condition

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#15832]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +fa3f484 Wed May 25 01:47:53 2016 +0000 linux/amd64

but this problem has been around for at least a couple of weeks on tip.

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

3. What did you do?

I ran a test with "go test -race".
Unfortunately the code to reproduce it is not open source, but
most of the dependencies are. I'll try to see whether I can reproduce
the issue in a smaller program, but that might be problematic,
hence I'm reporting the issue now.

4. What did you expect to see?

No races detected. Go 1.6.3 and previous doesn't report a race.

5. What did you see instead?

This race detector output (I've removed goroutines that mention
the non-open-source project).

Note that regardless of what code is calling it, I don't think there should
ever be a race between reflect.SliceOf and reflect.Value.Call, which
is what appears to be happening.

	==================
	WARNING: DATA RACE
	Read at 0x00c420390c90 by goroutine 147:
	  runtime.mapaccess2_fast64()
	      /home/rog/go/src/runtime/hashmap_fast.go:147 +0x0
	  reflect.addReflectOff()
	      /home/rog/go/src/runtime/runtime1.go:518 +0x5c
	  reflect.SliceOf()
	      /home/rog/go/src/reflect/type.go:2302 +0x36f
	  github.com/juju/juju/state.loadAllWatcherEntities()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1211 +0x25a
	  github.com/juju/juju/state.(*allModelWatcherStateBacking).loadAllWatcherEntitiesForModel()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1119 +0x177
	  github.com/juju/juju/state.(*allModelWatcherStateBacking).GetAll()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1105 +0xaa
	  github.com/juju/juju/state.(*storeManager).loop()
	      /home/rog/src/go/src/github.com/juju/juju/state/multiwatcher.go:221 +0x14c
	  github.com/juju/juju/state.newStoreManager.func1()
	      /home/rog/src/go/src/github.com/juju/juju/state/multiwatcher.go:198 +0x66
	
	Previous write at 0x00c420390c90 by goroutine 153:
	  runtime.mapassign1()
	      /home/rog/go/src/runtime/hashmap.go:442 +0x0
	  reflect.addReflectOff()
	      /home/rog/go/src/runtime/runtime1.go:523 +0x120
	  reflect.funcLayout()
	      /home/rog/go/src/reflect/type.go:3099 +0x8c1
	  reflect.Value.call()
	      /home/rog/go/src/reflect/value.go:399 +0x355
	  reflect.Value.Call()
	      /home/rog/go/src/reflect/value.go:302 +0xb3
	  github.com/juju/juju/rpc/rpcreflect.newMethod.func6()
	      /home/rog/src/go/src/github.com/juju/juju/rpc/rpcreflect/type.go:323 +0x125
	  github.com/juju/juju/apiserver.(*srvCaller).Call()
	      /home/rog/src/go/src/github.com/juju/juju/apiserver/root.go:126 +0x197
	  github.com/juju/juju/rpc.(*Conn).runRequest()
	      /home/rog/src/go/src/github.com/juju/juju/rpc/server.go:558 +0xc8
	==================
	==================
	WARNING: DATA RACE
	Write at 0x00c420390c60 by goroutine 147:
	  runtime.mapassign1()
	      /home/rog/go/src/runtime/hashmap.go:442 +0x0
	  reflect.addReflectOff()
	      /home/rog/go/src/runtime/runtime1.go:522 +0xde
	  reflect.SliceOf()
	      /home/rog/go/src/reflect/type.go:2302 +0x36f
	  github.com/juju/juju/state.loadAllWatcherEntities()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1211 +0x25a
	  github.com/juju/juju/state.(*allModelWatcherStateBacking).loadAllWatcherEntitiesForModel()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1119 +0x177
	  github.com/juju/juju/state.(*allModelWatcherStateBacking).GetAll()
	      /home/rog/src/go/src/github.com/juju/juju/state/allwatcher.go:1105 +0xaa
	  github.com/juju/juju/state.(*storeManager).loop()
	      /home/rog/src/go/src/github.com/juju/juju/state/multiwatcher.go:221 +0x14c
	  github.com/juju/juju/state.newStoreManager.func1()
	      /home/rog/src/go/src/github.com/juju/juju/state/multiwatcher.go:198 +0x66
	
	Previous write at 0x00c420390c60 by goroutine 153:
	  runtime.mapassign1()
	      /home/rog/go/src/runtime/hashmap.go:442 +0x0
	  reflect.addReflectOff()
	      /home/rog/go/src/runtime/runtime1.go:522 +0xde
	  reflect.funcLayout()
	      /home/rog/go/src/reflect/type.go:3099 +0x8c1
	  reflect.Value.call()
	      /home/rog/go/src/reflect/value.go:399 +0x355
	  reflect.Value.Call()
	      /home/rog/go/src/reflect/value.go:302 +0xb3
	  github.com/juju/juju/rpc/rpcreflect.newMethod.func6()
	      /home/rog/src/go/src/github.com/juju/juju/rpc/rpcreflect/type.go:323 +0x125
	  github.com/juju/juju/apiserver.(*srvCaller).Call()
	      /home/rog/src/go/src/github.com/juju/juju/apiserver/root.go:126 +0x197
	  github.com/juju/juju/rpc.(*Conn).runRequest()
	      /home/rog/src/go/src/github.com/juju/juju/rpc/server.go:558 +0xc8

**Comment by davecheney** [comment]
I hit this race today as well, addReflectOff is protected by a lock in the
runtime, but maybe the race runtime doesn't understand that lock, or the
use of go:linkname is throwing it off.

/cc @dvyukov

**Comment by crawshaw** [comment]
I wrote https://go-review.googlesource.com/23441 speculatively, though I don't have a reproduction for the error. Could you cherry-pick it and see if it helps?

**Comment by crawshaw** [comment]
I believe I have a test for this in CL 23441 now, but I'd still appreciate confirmation.
