### ISSUE TITLE
spec: never says fields are promoted

### ISSUE THREAD

**Issue by jba** [golang/go#15834]
The spec defines "promoted", and talks about the properties of promoted fields. But it never says which fields do in fact get promoted.

**Comment by cznic** [comment]
It's not said explicitly, but:

> A field or method f of an anonymous field in a struct x is called promoted if x.f is a legal selector that denotes that field or method f. ([src](https://tip.golang.org/ref/spec#Struct_types))

I think the above effectively equals saying that promoted fields/methods are anonymous fields/methods of anonymous fields which can be accessed using a selector that omits the anonymous field name because the selector is unambiguous.

**Comment by griesemer** [comment]
As @cznic already pointed out, the term "promoted" is clearly defined in https://golang.org/ref/spec#Struct_types and then used in next few following paragraphs, only after it's been defined. It's also the only place where the term "promoted" appears in the spec. This seems pretty clear.
