### ISSUE TITLE
cmd/compile: stop marking arguments live for entire function call

### ISSUE THREAD

**Issue by rsc** [golang/go#15843]
For Go 1.8 we probably need to stop marking args live for the entire function call. It just doesn't fit with the sophisticated analyses being done by the SSA back end. Programmers will have runtime.KeepAlive already in Go 1.7, so people doing Go 1.8 beta testing will be able to update their code in a (Go 1.7-)backwards compatible way. And maybe we can find some way to help people find problems faster. It's going to be quite a band-aid to rip off.

But see [my recent comment](https://github.com/golang/go/issues/15277#issuecomment-221768072) in #15277 for the pain we're in if we don't do this.

/cc @randall77 @aclements @RLH @dr2chase

**Comment by randall77** [comment]
Here's the plan:

1. Tell people they have to use runtime.KeepAlive
2. Stop marking arguments live for the entire function call.
3. Have the SSA backend intrinsify runtime.KeepAlive so it costs little to nothing.

I'm signing myself up to do #2 and #3.  I will put #2 behind a flag of some sort and have it default to the new 1.8 behavior.  We should probably think more about how to do #1 robustly.

**Comment by bradfitz** [comment]
I don't think we need to go out of our way for step 1. It was already in the Go 1.7 release notes, and we'd put it in the Go 1.8 release notes again, probably a bit more prominently.

I think even a flag is pretty generous.

**Comment by davecheney** [comment]
Same about the flag, it just gives people a way to continue to use subtly
incorrect code for longer than their users expect, but less than they
really want.

**Comment by randall77** [comment]
Ok, #2 and #3 are in, and there is no flag.
