### ISSUE TITLE
tour: installing Go tour locally requires setting GOPATH; as a novice, GOPATH may be indecipherable

### ISSUE THREAD

**Issue by volmarias** [golang/go#15846]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
OS X

3. What did you do?
Cloned the tour repo (went to https://go.googlesource.com/tour first, which didn't show the readme)
Read README
Ran go get golang.org/x/tour/gotour

4. What did you expect to see?
A prior instruction to set GOPATH and why

5. What did you see instead?
package golang.org/x/tour/gotour: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by ianlancetaylor** [comment]
CC @adg @campoy
