### ISSUE TITLE
x/exp/io: i2c support for reading/writing to registers

### ISSUE THREAD

**Issue by mattetti** [golang/go#15858]
Some i2c devices function by reading and writing to registers, here is an example: http://www.seeedstudio.com/wiki/Grove_-_I2C_ADC

There is already a TODO inside the Device`Read` method but I think it's worth tracking as an issue since it will be needed to implement drivers and the API needs to be different (we'd need to pass the registry id). Suggestion API: 

```go
func (d *Device) ReadFromReg(reg byte, buf []byte) error{}
func (d *Device) WriteToReg(reg byte, buf []byte) error{}
```

**Comment by minux** [comment]
I'd suggest adding a new Tx API to the driver, that does
the more generic write then read i2c transaction.

Then the i2c package itself can provide convenience
register read/write functions built on top of that.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/exp/commit/88ba02563bded2674458a4c459ea3d46469a8d02.
