### ISSUE TITLE
net/http: support Cookie "SameSite" attribute

### ISSUE THREAD

**Issue by haoxins** [golang/go#15867]
https://tools.ietf.org/html/draft-west-first-party-cookies-07
https://www.chromestatus.com/feature/4672634709082112

**Comment by hkeide** [comment]
Since this is already supported in Chrome 51, and it won't be in Go for a while yet, here is a simple workaround (tested to work in Chrome 51):

```
cs := w.Header().Get("Set-Cookie")
cs += "; SameSite=lax"
w.Header().Set("Set-Cookie", cs)
```

**Comment by bradfitz** [comment]
This seems trivial, but it also seems like we should wait until there's more web consensus. Chrome can pull or modify support, but our Go 1 compatibility promise is stronger. It would be unfortunate if we added a `SameSite bool` field to `net/http.Cookie` and then they renamed it yet again before it became fully standardized.

**Comment by kardianos** [comment]
SameSite would probably need to be an const (Strict, Lax).

Would it make sense to serialize Cookie.Unparsed into the cookie string? Then I can just set `Unparsed: []string {"SameSite=Strict"},`.

**Comment by JaredWilliams** [comment]
Alternative hack allowing for multiple cookies.

    type SameSite string

    const (
        SameSiteLax    SameSite = "lax"
        SameSiteStrict          = "strict"
    )

    func SetCookie(w http.ResponseWriter, cookie *http.Cookie, sameSite SameSite) {
        if v := cookie.String(); v != "" {
            switch sameSite {
            case SameSiteLax:
                v = v + "; SameSite=lax"
            case SameSiteStrict:
                v = v + "; SameSite=strict"
            }
            w.Header().Add("Set-Cookie", v)
        }
    }

**Comment by reedloden** [comment]
Keep in mind there are actually three different possible values here. `SameSite`, `SameSite=Lax`, and `SameSite=Strict`. `SameSite` without a value means the same as `SameSite=Strict`.

Updated spec: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00

**Comment by blitzprog** [comment]
It's been a year now and the name hasn't changed.
I believe it should be added to the standard lib.

**Comment by mbyczkowski** [comment]
It's still only [supported](https://caniuse.com/#search=samesite) by Chrome and Opera and the IETF draft (both, orignal and the updated spec) [has expired](https://datatracker.ietf.org/doc/draft-ietf-httpbis-cookie-same-site/) last year.  ¯\\\_(ツ)\_/¯

**Comment by kardianos** [comment]
I had to remove the samesite cookie attribute even for chrome due to https://bugs.chromium.org/p/chromium/issues/detail?id=626245 .

Until bugs like this are resolved in chrome, I don't see any viable implementation. Not one, zero.

**Comment by srenatus** [comment]
@kardianos oh that's a bummer. I'll close the change then.

**Comment by kardianos** [comment]
@srenatus You can leave it open and put R=go1.11 in a comment line so it won't show up on a dashboard until then. If it does become a standard, the bug will eventually get fixed. It just might not be ready now. Go can't accept the change for now anyway as it is in a freeze.

**Comment by srenatus** [comment]
@kardianos done -- thanks 😃

**Comment by agnivade** [comment]
ping on this.

OAWSP [site](https://www.owasp.org/index.php/SameSite) says 
> As of November 2017 the SameSite attribute is implemented in Chrome, Firefox, and Opera.

[caniuse.com](https://caniuse.com/#search=samesite) is still pretty red but FF and Chrome support is there.

**Comment by andybons** [comment]
60% usage globally is still pretty low given that Chrome is much more cavalier about removing features.

**Comment by bradfitz** [comment]
Still not in Edge or Safari, and still only a draft standard. I still think we should wait. There's no rush and people can't use string concatenation in the meantime.

**Comment by reedloden** [comment]
Firefox just announced support for this

https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/

**Comment by bradrydzewski** [comment]
FYI this shipped in Edge 18 and in the Edge 17 June security patch
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/samesitecookies/

**Comment by bradfitz** [comment]
If somebody wants to send a change for this for Go 1.12, that's fine.

**Comment by agnivade** [comment]
I believe [CL 79919](https://github.com/golang/go/issues/15867#issuecomment-347158494) is already there. Probably needs to be bumped to 1.12.

**Comment by ptman** [comment]
unless I'm interpreting something wrong the samesite code seems to be in 1.11, no need to wait for 1.12
