### ISSUE TITLE
path/filepath: Glob does not work at Windows drive root

### ISSUE THREAD

**Issue by AudriusButkevicius** [golang/go#15863]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6

2. What operating system and processor architecture are you using (`go env`)?

Windows AMD64

3. What did you do?
```
	res, _ := filepath.Glob("C:\\*")
	for _, match := range res {
		fmt.Println(match)
	}
```
4. What did you expect to see?
```
C:\$$PendingFiles
C:\$Recycle.Bin
C:\AudioSwitch
...
```

5. What did you see instead?
```
C:goplay
C:goplay.go
C:liteide
```

It seems that it lists content of the $PWD, and then blindly prepends `C:` to stuff.

The workaround seems to be to use double slashes `C:\\\\*`, so that only one separator would get trimmed off.

**Comment by alexbrainman** [comment]
@AudriusButkevicius filepath.Glob code was changed recently (see issue #14949 for details). Perhaps your issue was fixed too. Please try current tip, to see if your issue is fixed on current tip. Thank you.

Alex

**Comment by AudriusButkevicius** [comment]
Works on tip
