### ISSUE TITLE
build: darwin/amd64 builder is sick

### ISSUE THREAD

**Issue by rsc** [golang/go#15860]
We kind of need the darwin/amd64 builder to tell us the release is OK before cutting Go 1.7 beta. Lots of us run on laptops so it's maybe OK to test there explicitly, but a builder would be nice. What happened to it?

Maybe one of @crawshaw @evandbrown @hyangah @bradfitz knows.

**Comment by crawshaw** [comment]
The one I know about is darwin-amd64_10_10, which looks like it's working. There's a new one darwin-amd64_10_9 that's failing, but I'm guessing that's because it's new and not configured correctly yet.

Or is there something other than build.golang.org I should be looking at?

**Comment by quentinmit** [comment]
darwin-amd64_10_9 only started failing on May 17 - it was passing before then. I agree though that it looks misconfigured.

**Comment by rsc** [comment]
Sorry, I misread the columns and didn't realize there is another amd64 that's OK. Good enough for the beta at least.

**Comment by crawshaw** [comment]
The misconfigured 10.9 builder has fallen off the map. As we didn't have it for other releases, I don't think this is blocking 1.7.

**Comment by quentinmit** [comment]
We have a 10.8 builder now; I think that should be sufficient to cover 10.8 and 10.9. We also have 10.10 and 10.11 builders.
