### ISSUE TITLE
cmd/go: show the version GOROOT corresponds to in `go bug` output

### ISSUE THREAD

**Issue by minux** [golang/go#15877]
A lot of issue reports are due to incorrect `$GOROOT` setting.
For example, I suspect that #15874 is one of them.

I propose that go env also print the version of the tools
the GOROOT corresponds to as a comment.

For example, instead just of printing:

```
....
GOROOT="/Users/minux/go/rel/go1.6"
GOTOOLDIR="/Users/minux/go/rel/go1.6/pkg/tool/darwin_amd64"
...
```

I'd like it also show the version as a comment (so that the output
is still a valid shell script):

```
GOROOT="/Users/minux/go/rel/go1.6" # version go1.6
GOTOOLDIR="/Users/minux/go/rel/go1.6/pkg/tool/darwin_amd64" # version go1.5
```

For Windows, we probably need to use `REM` on separate lines:

```
REM version go1.6
set GOROOT=C:\go
REM version go1.5
set GOTOOLDIR=C:\go\tool\tool\windows_386\
```

For GOROOT, it could use the `go version` command from the directory,
for GOTOOLDIR, we can use `compile -V` to get the actual tool version.

Because GOTOOLDIR is not settable via environment variables, so
showing the tool version might not be that important, but it will definitely
help when $GOROOT/bin/go is out of sync from the toolchain (this might
help #15372.)

I'd like to add this to Go 1.7 if at all possible.

**Comment by adg** [comment]
Sounds good to me.

**Comment by adg** [comment]
Although I'm a bit concerned about breaking people that are parsing the output of 'go env'. Maybe these comments should only be printed with `go env -v`? Although I'm hesitant to add new flags.

**Comment by minux** [comment]
We can always print the comment in separate lines so it shouldn't confuse
existing parser that only looks for specific keywords.

**Comment by davecheney** [comment]
Can you think of a situation where having a mismatch could be anything but
a mistake? What if a mismatch caused go env to print an error and exit 1?

**Comment by adg** [comment]
Looks like this missed the boat for 1.7. We're cutting the beta today.

**Comment by dominikh** [comment]
> We can always print the comment in separate lines so it shouldn't confuse existing parser that only looks for specific keywords.

Parsers that expect each line to be a `variable=value` pair and don't expect anything else would break due to this, too. 

Also, what about something like `go env GOROOT GOPATH`? A parser might expect exactly two lines of output, with the order specified in the command. That's how go-mode for Emacs currently works, and I wouldn't be surprised if other tools had the same expectations.

**Comment by minux** [comment]
I didn't propose to change the output for "go env VARNAME", only the output
of "go env".

We can limit the extra output lines to cases where there is actually a
version mismatch.

**Comment by rsc** [comment]
Will fix in go bug instead.
