### ISSUE TITLE
runtime: unrecognized instruction "PCMPESTRI"

### ISSUE THREAD

**Issue by AudriusButkevicius** [golang/go#15874]
1. What version of Go are you using (`go version`)?

tip = b859a78e0a71d769274dac8cf0108bdf41ec55a5

2. What operating system and processor architecture are you using (`go env`)?

Intel i5-2320

```
Audrius@Audrius syncthing $ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoHome\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?

Tried to compile a hello world example

4. What did you expect to see?

Compiled binary

5. What did you see instead?
```
# runtime
C:\Go\src\runtime\asm_amd64.s:1853: unrecognized instruction "PCMPESTRI"
C:\Go\src\runtime\asm_amd64.s:1862: unrecognized instruction "PCMPESTRI"
asm: asm: assembly of C:\Go\src\runtime\asm_amd64.s failed
```

Seems to have been broken by 6b02a1924725688b4d264065454ac5287fbed535

**Comment by kostya-sh** [comment]
Could it be that you are still using an old version of Go? What does `go version` print?

`go env` from tip doesn't have `set GO15VENDOREXPERIMENT=1` in its output.

How did you build go compiler?

**Comment by AudriusButkevicius** [comment]
Yep, I am a muppet.
