### ISSUE TITLE
cmd/vet: possible bug in code

### ISSUE THREAD

**Issue by dlsniper** [golang/go#15883]
1. What version of Go are you using (`go version`)? 17396575135ba71472ab8a5b82f31af50d8bf312
2. What operating system and processor architecture are you using (`go env`)? not important
3. What did you do?

Looking at https://github.com/golang/go/blob/17396575135ba71472ab8a5b82f31af50d8bf312/src/cmd/vet/print.go#L359 it seems that there's a new variable initialized called `indexPending`. I believe the correct code should remove that and change the code at https://github.com/golang/go/blob/17396575135ba71472ab8a5b82f31af50d8bf312/src/cmd/vet/print.go#L373 to check for `state.indexPending` instead of `indexPending` as it does right now.
1. What did you expect to see?
   Not sure what that will impact, hopefully nothing.
2. What did you see instead?
   Either a possible leftover or a possible bug / inconsistency.

**Comment by dlsniper** [comment]
I will send the CL soon.

**Comment by valyala** [comment]
FYI, The bug will be resolved in #15884  . See [the CL](https://go-review.googlesource.com/24391), so the issue may be closed now.

**Comment by ALTree** [comment]
Closing, then.
