### ISSUE TITLE
net: test fails - TestLookupDotsWithLocalSource

### ISSUE THREAD

**Issue by robjloranger** [golang/go#15881]
go version: 1.6.2 - also present when testing master branch
linux/amd64

trying to run all.bash eventually fails on testing packages.
`--- FAIL: TestLookupDotsWithLocalSource (0.02s)
	lookup_test.go:457: netgo: got localhost.; want localhost
FAIL
FAIL	net	1.958s
`
I saw issue #14050 but my /etc/hosts does not contain any trailing dots.

**Comment by robjloranger** [comment]
apparently this does not present itself in version 1.5.4
I checked out go1.5.4 and afterward all tests pass and compilation continues

**Comment by ianlancetaylor** [comment]
What does your `/etc/hosts` file look like?  What does `dig 1.0.0.127.in-addr.arpa` print?

(For what it's worth, this test failure is not all that serious.  At the point of the failure your Go build is installed and working.)

**Comment by robjloranger** [comment]
/etc/hosts

> 127.0.1.1 openheart localhost
 ::1 openheart ip6-localhost ip6-loopback
 ff02::1 ip6-allnodes
 ff02::2 ip6-allrouters

dig

> 127.in-addr.arpa.	10800	IN	SOA	localhost. nobody.invalid. 1 3600 1200 604800 10800

**Comment by mikioh** [comment]
@robjloranger,

This is probably related to your circumstances. Can you show us the following:
- /etc/resolv.conf, /etc/nsswitch.conf
- configuration on the running local recursive/cache server or similar if possible. I'm sure there is someone who speaks DNS and returns "nobody.invalid." on your circumstances

**Comment by robjloranger** [comment]
resolv.conf

> # Generated by NetworkManager
search telus
nameserver 192.168.1.254
nameserver 75.153.171.114
nameserver 2001:568:ff09:10a::56
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 2001:568:ff09:10a::114

nsswitch.conf

> # Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

publickey: files

hosts: files mdns_minimal [NOTFOUND=return] dns myhostname
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files

# End /etc/nsswitch.conf

i'm not sure what you mean by the second point. what else could be setting this?

**Comment by mikioh** [comment]
@robjloranger,

> i'm not sure what you mean by the second point. what else could be setting this?

Ah, you are using telus, that's enough for investigation, thanks. Probably we should skip TestLookupDotsWithLocalSource in short-mode on non-buildbots/trybots for avoiding complicated testing.

**Comment by mikioh** [comment]
For the record, this might happen when the node under test uses a) some agent software that touches/modifies the local database file /etc/hosts, and b) some full resolver that provides local-data/local-zone-like RR caches.

From go1.6, the check on /etc/hosts runs every 5 secs, not every 5 mins. My dumb hypothesis is that;
1) some agent software makes /etc/hosts empty for some reason
2) built-in stub resolver reads the empty /etc/hosts file and has no record
3) built-in stub resolver throws a query to some full resolver
4) the full resolver replies its local-data/local-zone RR, which contains "127.in-addr.arpa. IN SOA localhost. nobody.invalid."
5) TestLookupDotsWithLocalSource barks at "localhost."

**Comment by robjloranger** [comment]
this stopped happening with go 1.6.2, and the test continues to pass in go 1.7rc2 as well
