### ISSUE TITLE
 json unmarshal lost some fields with UnmarshalJSON used

### ISSUE THREAD

**Issue by xiezhenye** [golang/go#15890]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
any

2. What operating system and processor architecture are you using (`go env`)?
any

3. What did you do?
https://play.golang.org/p/RbXnSUVtEx

4. What did you expect to see?
{map[001:{{100 500} test}]}

5. What did you see instead?
{map[001:{{100 500} }]}

**Comment by hyper-carrot** [comment]
It's OK: https://play.golang.org/p/rrej4sGnr6

Does that mean the embedded fields is unsupported in this case?

**Comment by xiezhenye** [comment]
maybe op struct take over the UnmarshalJSON . 
Is there some way to set default value on a embedded field?

**Comment by kostya-sh** [comment]
This is working as intended. Methods of the embedded struct (`operation`) are promoted to the parent struct (`op`). `json.Unmarshal` calls `op.UnmarshalJSON`.
