### ISSUE TITLE
net/http: Serve violates tls.Config immutability promise

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#15908]
From `tls.Confg` docs:

```
After one has been passed to a TLS function it must not be modified.
```

But calling Serve will call setupHTTP2, which calls http2ConfigureServer, which will modify the tls.Config. Since by the time you call Serve you must have already called tls.Listen, the immutability promise is broken.

I don't think anything relies on it yet, but nothing stops someone from for example caching the NextProtos in crypto/tls.Listen or something, breaking the setupHTTP2 magic.

**Comment by tombergan** [comment]
This might be a dup of Issue #15771

**Comment by adg** [comment]
I'm not sure what, if anything, can be done about this before the 1.7 release.

**Comment by bradfitz** [comment]
Sent https://golang.org/cl/24508
