### ISSUE TITLE
flag: zero value for time.Duration not recognized

### ISSUE THREAD

**Issue by xi2** [golang/go#15904]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +4223294 Tue May 31 13:02:09 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build043601680=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
   Ran the following with argument `-h`:
   ```go
package main

import "flag"

func main() {
        _ = flag.Duration("duration", 0, "set a duration")
        flag.Parse()
}
```

4. What did you expect to see?
   On Go 1.6 I see:
   ```
Usage of test:
  -duration duration
        set a duration
exit status 2
```

5. What did you see instead?
   ```
Usage of test:
  -duration duration
        set a duration (default 0s)
exit status 2
```

Does `isZeroValue` in flag/flags.go now need a `case "0s":`?

**Comment by mark-rushakoff** [comment]
[The string version of a zero duration has been discussed before on the mailing list](https://groups.google.com/d/topic/golang-nuts/qGTvqrCHV6Q/discussion).
