### ISSUE TITLE
cmd/go: LANG environment variable affect go build under a cgo package

### ISSUE THREAD

**Issue by lazytiger** [golang/go#15900]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pirate/go_path:/home/pirate/code/arpgserver"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

execute go build under a cgo package

4. What did you expect to see?
with LANG=zh_CN.UTF-8 compiler complains "-no-pie" not supported by gcc/g++
with LANG=en_US.UTF-8 ok

5. What did you see instead?

**Comment by ianlancetaylor** [comment]
Please show us the output of `go build -x` with two different settings of `LANG`.  Thanks.

**Comment by lazytiger** [comment]
LANG=en_US.UTF-8
WORK=/tmp/go-build206280267
mkdir -p $WORK/babeltime.com/ncmc/_obj/
mkdir -p $WORK/babeltime.com/
cd /home/pirate/code/arpgserver/src/babeltime.com/ncmc
CGO_LDFLAGS="-g" "-O2" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/babeltime.com/ncmc/_obj/ -importpath babeltime.com/ncmc -- -I $WORK/babeltime.com/ncmc/_obj/ ncmc.go
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/_cgo_main.o -c $WORK/babeltime.com/ncmc/_obj/_cgo_main.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o -c $WORK/babeltime.com/ncmc/_obj/_cgo_export.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o -c $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.c
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o -c ./Allocator.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o -c ./Chunk.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o -c ./Cmc.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o -c ./Hashtable.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/List.cpp.o -c ./List.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o -c ./RWLockGroup.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -c ./Util.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/babeltime.com/ncmc/_obj/_cgo_.o $WORK/babeltime.com/ncmc/_obj/_cgo_main.o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o $WORK/babeltime.com/ncmc/_obj/List.cpp.o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -g -O2
/usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/babeltime.com/ncmc/_obj/ -dynpackage ncmc -dynimport $WORK/babeltime.com/ncmc/_obj/_cgo_.o -dynout $WORK/babeltime.com/ncmc/_obj/_cgo_import.go
cd $WORK
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -no-pie -c trivial.c
cd /home/pirate/code/arpgserver/src/babeltime.com/ncmc
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/babeltime.com/ncmc/_obj/_all.o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o $WORK/babeltime.com/ncmc/_obj/List.cpp.o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -g -O2 -Wl,-r -nostdlib -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/babeltime.com/ncmc.a -trimpath $WORK -p babeltime.com/ncmc -buildid 642ded236c8402a02d3b3422773b1b9ee8cfb179 -D _/home/pirate/code/arpgserver/src/babeltime.com/ncmc -I $WORK -pack $WORK/babeltime.com/ncmc/_obj/_cgo_gotypes.go $WORK/babeltime.com/ncmc/_obj/ncmc.cgo1.go $WORK/babeltime.com/ncmc/_obj/_cgo_import.go
pack r $WORK/babeltime.com/ncmc.a $WORK/babeltime.com/ncmc/_obj/_all.o # internal


LANG=zh_CN.UTF-8
WORK=/tmp/go-build342536274
mkdir -p $WORK/babeltime.com/ncmc/_obj/
mkdir -p $WORK/babeltime.com/
cd /home/pirate/code/arpgserver/src/babeltime.com/ncmc
CGO_LDFLAGS="-g" "-O2" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/babeltime.com/ncmc/_obj/ -importpath babeltime.com/ncmc -- -I $WORK/babeltime.com/ncmc/_obj/ ncmc.go
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/_cgo_main.o -c $WORK/babeltime.com/ncmc/_obj/_cgo_main.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o -c $WORK/babeltime.com/ncmc/_obj/_cgo_export.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o -c $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.c
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o -c ./Allocator.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o -c ./Chunk.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o -c ./Cmc.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o -c ./Hashtable.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/List.cpp.o -c ./List.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o -c ./RWLockGroup.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -I $WORK/babeltime.com/ncmc/_obj/ -g -O2 -o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -c ./Util.cpp
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/babeltime.com/ncmc/_obj/_cgo_.o $WORK/babeltime.com/ncmc/_obj/_cgo_main.o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o $WORK/babeltime.com/ncmc/_obj/List.cpp.o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -g -O2
/usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/babeltime.com/ncmc/_obj/ -dynpackage ncmc -dynimport $WORK/babeltime.com/ncmc/_obj/_cgo_.o -dynout $WORK/babeltime.com/ncmc/_obj/_cgo_import.go
cd $WORK
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -no-pie -c trivial.c
cd /home/pirate/code/arpgserver/src/babeltime.com/ncmc
g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/babeltime.com/ncmc/_obj/_all.o $WORK/babeltime.com/ncmc/_obj/_cgo_export.o $WORK/babeltime.com/ncmc/_obj/ncmc.cgo2.o $WORK/babeltime.com/ncmc/_obj/Allocator.cpp.o $WORK/babeltime.com/ncmc/_obj/Chunk.cpp.o $WORK/babeltime.com/ncmc/_obj/Cmc.cpp.o $WORK/babeltime.com/ncmc/_obj/Hashtable.cpp.o $WORK/babeltime.com/ncmc/_obj/List.cpp.o $WORK/babeltime.com/ncmc/_obj/RWLockGroup.cpp.o $WORK/babeltime.com/ncmc/_obj/Util.cpp.o -g -O2 -Wl,-r -nostdlib -no-pie -Wl,--build-id=none
# babeltime.com/ncmc
g++: 无法识别的选项‘-no-pie’
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/babeltime.com/ncmc.a -trimpath $WORK -p babeltime.com/ncmc -buildid 642ded236c8402a02d3b3422773b1b9ee8cfb179 -D _/home/pirate/code/arpgserver/src/babeltime.com/ncmc -I $WORK -pack $WORK/babeltime.com/ncmc/_obj/_cgo_gotypes.go $WORK/babeltime.com/ncmc/_obj/ncmc.cgo1.go $WORK/babeltime.com/ncmc/_obj/_cgo_import.go
pack r $WORK/babeltime.com/ncmc.a $WORK/babeltime.com/ncmc/_obj/_all.o # internal

**Comment by mwhudson** [comment]
I guess the "supported := err == nil && !bytes.Contains(out, []byte("unrecognized"))" thing doesn't work when LANG is not English. Oh my. I guess the fix is to force LANG=C for the trial compilations.

**Comment by mwhudson** [comment]
Can you try the change in https://go-review.googlesource.com/#/c/23536/ ?
