### ISSUE TITLE
cmd/compile: bad line number for duplicate default case

### ISSUE THREAD

**Issue by josharian** [golang/go#15911]
```go
func f(e interface{}) {
	switch e { // ERROR "multiple defaults in switch"
	default:
	default:
	}
	switch e.(type) { // ERROR "multiple defaults in switch"
	default:
	default:
	}
}
```

Those errors are on the wrong line. They should be on the second default line. The fix is trivial, just waiting for 1.8.

**Comment by mdempsky** [comment]
And for the record, go/types and gccgo emit the error message on the second default lines.
