### ISSUE TITLE
cmd/dist: enable misc/cgo/* tests on android/iOS

### ISSUE THREAD

**Issue by hyangah** [golang/go#15919]
many of cgo tests still remain disabled on android/ios, which prevents from detecting bugs early.
See grep -r android src/cmd/dist/test.go
Re-enable them.

**Comment by aclements** [comment]
I recently discovered that some cgo tests appear to be enabled for Android in cmd/dist, but actually do nothing. For example, misc/cgo/stdio and misc/cgo/life are run on Android, but then immediately t.Skip.
