### ISSUE TITLE
x/mobile: go tool pprof profile crashes the process

### ISSUE THREAD

**Issue by balboah** [golang/go#15917]
1. What version of Go are you using (`go version`)?
   1.6.2
   gomobile revision c435d0b
2. What operating system and processor architecture are you using (`go env`)?
   built on darwin amd64
   executed on ARMv7 android 6
3. What did you do?
- Enable pprof via `net/http/pprof`
- Start profiling with `go tool pprof http://<host>/debug/pprof/profile`

This causes the application to exit without any more details than:
`Zygote  : Process 6268 exited due to signal (27)`

The other goroutine & heap profiling works fine.

**Comment by zllak** [comment]
Tested with go1.8b2, still crashing. Any progress on this issue ?
Tested on both iOS and Android, same.

**Comment by eliasnaur** [comment]
Is this still a problem? If so, can you verify that profiling a Go library (built with -buildmode=c-shared) run from a C main program works? The result of that experiment will determine whether the problem is with android in particular or with profiling c-shared libraries.
Thank you.

**Comment by changkun** [comment]
pprof works on mobile as of today. Close as outdated, and feel free to comment if there is any updates on the issue.
