### ISSUE TITLE
net/http: cancel context when underlying connection closes

### ISSUE THREAD

**Issue by nhooyr** [golang/go#15927]
There was a comment on `http.Request.Context` that said that when the underlying connection closes, the context would be cancelled. However, this has not been implemented.

I'm not sure if we want to do this because it would double the number of goroutines running and I'm not sure exactly how to implement it because `http.CloseNotifier` is incompatible with `http.Hijacker`.

**Comment by bradfitz** [comment]
I finally have a plan for this! Or rather, I have a plan for #15224 now which will make fixing this bug possible. I'll post details in #15224.
