### ISSUE TITLE
cmd/cgo: _cgoCheckPointer call occurs too early for deferred function calls.

### ISSUE THREAD

**Issue by bcmills** [golang/go#15921]
I found a related-but-different problem when investigating issue #13830.

Making the _cgoCheckPointer call explicitly in the function parameters of a deferred call causes the pointer check to occur at the wrong time.  We end up checking whether the argument had a Go pointer at the point where the call was deferred, not whether the argument had a Go pointer at the point where the C call was actually made.

Consider this program:

```go
package main

/*
#include <stdint.h>

struct sneaky {
  int *p;
};

void sneak(struct sneaky *s, uintptr_t *u) {
  *u = (uintptr_t)(s->p);
}
*/
import "C"

import "fmt"

func main() {
	var s C.struct_sneaky
	var u C.uintptr_t

	defer func() { fmt.Println(u) }()
	defer C.sneak(&s, &u)

	var escapee C.int
	s.p = &escapee
}
```

With go version go1.6.1 linux/amd64, the program (incorrectly) prints a leaked address and exits with code 0.

Changing the call to `C.sneak` to an explicit call at the end of `main` causes the program to (correctly) panic with a cgo pointer violation.

The problem is that the _cgoCheckPointer calls wrap the function's arguments, not the function call itself:

```go
  defer _Cfunc_sneak(_cgoCheckPointer((*_Ctype_struct_sneaky)(&s), true).(*_Ctype_struct_sneaky), &u)
```

**Comment by ianlancetaylor** [comment]
Nice example.
