### ISSUE TITLE
release: the go 1.7 beta source  archive contains the github issue/pull request templates

### ISSUE THREAD

**Issue by thomasf** [golang/go#15932]
the `.github` directory with the files `ISSUE_TEMPLATE`  and  `PULL_REQUEST_TEMPLATE` is included in the source archive of go 1.7 beta. I really don't know if this is intentional or not but I'm guessing it isn't.

**Comment by broady** [comment]
It's part of the source repo, and present when one checks out the tag.

We could remove it before tagging and on the release branch, but I don't think it hurts anyone, so let's not complicate the build process further.

**Comment by broady** [comment]
I will check if we can put the templates on another branch, though.

**Comment by bradfitz** [comment]
This is also super easy to fix in cmd/release, though. There's already a list of things we delete, no?

**Comment by broady** [comment]
Yeah, I suppose so. We can also just delete it when we create the release branch.

(I talked to GitHub, the templates must live on the default branch)

**Comment by ibnesayeed** [comment]
Or perhaps we can just add a directive in `.gitattributes` file that will prevent it from being archived.

**Comment by adg** [comment]
Sent a change to rm .github in the cmd/release tool.
