### ISSUE TITLE
http2: timeout waiting for client preface

### ISSUE THREAD

**Issue by dbaroncelli** [golang/go#15938]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
I have enabled https

4. What did you expect to see?

5. What did you see instead?

I have lots of these lines in the logs:
`http2: server: error reading preface from client x.x.x.x:xxxxx: timeout waiting for client preface`

@bradfitz is there any specific reason for that?

**Comment by ianlancetaylor** [comment]
There is no bug report here at this point.  We don't use the issue tracker to ask questions.  We use forums.  Please see https://golang.org/wiki/Questions .

Closing as I don't see a bug.
