### ISSUE TITLE
cmd/go: TestPackageNotStaleWithTrailingSlash fails in release distribution

### ISSUE THREAD

**Issue by unclejack** [golang/go#15933]
Go 1.7 beta1 can't pass the tests when being built with Go 1.4.3 or Go 1.6.2. Go 1.6.2 can be built and tested without seeing any kind of error using the 1.4.3 toolchain on the same machine. This can be reproduced every time.

1. What version of Go are you using (`go version`)?
Go 1.7 beta1

2. What operating system and processor architecture are you using (`go env`)?
Linux, amd64

3. What did you do?
```GOROOT_BOOTSTRAP=/usr/local/go1.4.3 ./all.bash```
```GOROOT_BOOTSTRAP=/usr/local/go1.6.2 ./all.bash```

4. What did you expect to see?
tests passing, working build

5. What did you see instead?
```
--- FAIL: TestPackageNotStaleWithTrailingSlash (0.27s)
        go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} runtime]
        go_test.go:259: standard output:
        go_test.go:260: false:standard package in Go release distribution

        go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
        go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} os]
        go_test.go:259: standard output:
        go_test.go:260: false:standard package in Go release distribution

        go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
        go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} io]
        go_test.go:259: standard output:
        go_test.go:260: false:standard package in Go release distribution

        go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
```

**Comment by mwhudson** [comment]
Those tests are new in 1.7 so that explains that aspect. I guess the tests are broken in a release build though.
