### ISSUE TITLE
x/tools/guru: autocompletion/jump to declaration does not work/is very slow in LiteIDE with Go1.7 beta 1 on Ubuntu amd64

### ISSUE THREAD

**Issue by leeview** [golang/go#15945]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go1.7beta1 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu amd64

3. What did you do?
While editing a (~larger) project using the LiteIDE editor, I noticed that the auto completion does not work anymore and "jump to declaration" and "view expression information" functionality is very slow (5-10 seconds delay) right after I updated from Go 1.6.2 to Go 1.7 beta 1 and the slowdown didn't go away after reboot.

4. What did you expect to see?
Auto completion, "jump to declaration" and "view expression information" should be responsive (like when using Go 1.6.2)

5. What did you see instead?
Auto completion not working at all; "jump to declaration" and "view expression information" are very slow

**Comment by ianlancetaylor** [comment]
What does LiteIDE use for auto-completion?  I'm guessing it is guru?  Except that doesn't make sense, because updating to Go 1.7 beta 1 should not change guru, unless you explicitly rebuilt it.

CC @alandonovan

**Comment by kostya-sh** [comment]
I haven't use LiteIDE but I am fairly sure that it uses https://github.com/nsf/gocode for autocompletion. You need to update it to the latest version to be able to use with Go 1.7:

    go get -u github.com/nsf/gocode

You might also to try using https://github.com/mdempsky/gocode instead.

I suggest to report this issue on LiteIDE bug tracker.

**Comment by leeview** [comment]
@ianlancetaylor @kostya-sh Reply from LiteIDE author (it solves the issue):

please update and build gotools gocode in go1.7 and copy to liteide/bin
go get -u github.com/visualfc/gotools
go get -u github.com/nsf/gocode
