### ISSUE TITLE
cmd/go: match go-import package prefixes by slash

### ISSUE THREAD

**Issue by smcquay** [golang/go#15947]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sm"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

I am hosting the following information over https:

```
curl https://go.mcquay.me/?go-get=1                                                                                                                        
<!DOCTYPE html>
<html><head>
<meta name="go-import" content="go.mcquay.me/sm/fooa git https://s.mcquay.me/sm/ud">
<meta name="go-import" content="go.mcquay.me/sm/foob git https://s.mcquay.me/sm/ud">
<meta name="go-import" content="go.mcquay.me/sm/fooaa git https://s.mcquay.me/sm/ud">
</head>
<body><p>go tool metadata in head</p></body>
</html>
```

and when I point the go tool at it, the following work:

    go get -x go.mcquay.me/sm/fooa
    go get -x go.mcquay.me/sm/foob

But this fails:

    go get -x go.mcquay.me/sm/fooaa
    package go.mcquay.me/sm/fooaa: unrecognized import path "go.mcquay.me/sm/fooaa" (parse https://go.mcquay.me/sm/fooaa?go-get=1: multiple meta tags match import path "go.mcquay.me/sm/fooaa")

4. What did you expect to see?

I'd expect that these are separate repositories and can be used to build and emit different pkg/bins. I'd expect the go tool to install it correctly.

5. What did you see instead?

`go get` failed with message:

    package go.mcquay.me/sm/fooaa: unrecognized import path "go.mcquay.me/sm/fooaa" (parse https://go.mcquay.me/sm/fooaa?go-get=1: multiple meta tags match import path "go.mcquay.me/sm/fooaa")

I can appreciate that the go tool can't clone a repo into a folder that's already a repo. The check on:

https://github.com/golang/go/blob/master/src/cmd/go/vcs.go#L782

seems a bit aggressive. Perhaps it just needs to be relaxed and test substrings on '/' boundaries?

**Comment by adg** [comment]
I agree with the suggestion, it should just test on slash boundaries.

**Comment by smcquay** [comment]
CL https://golang.org/cl/23732 mentions this issue.
