### ISSUE TITLE
website: broken links in profiling go programs blog

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#15957]
Various links on [Profiling Go Programs](https://blog.golang.org/profiling-go-programs) point to Google Code.  While some of these lead the reader to alternate locations, several pointing to [benchgraffiti](http://code.google.com/p/benchgraffiti/) are essentially broken.

**Comment by broady** [comment]
This one's probably a bit more tricky, need to hunt down the relevant commits in the now defunct nacl tree.

If someone would like to help, I made a clone of the Mercurial repository, retaining the commit hashes:
https://bitbucket.org/broady/go-archive/
