### ISSUE TITLE
net: dnsMsg.Pack() doesn't support compression

### ISSUE THREAD

**Issue by iangudger** [golang/go#15954]
RFC 1035 specifies (among other things) two requirements for DNS packet transport and parsing:
* All DNS packet parsers must accept compressed packets
* DNS packets sent over UDP cannot be larger than 512 bytes

Supporting compression is optional on the packet building side, but not supporting it often results in packets larger than 512 bytes. Long domains and domains with lots of records are common, so not supporting compression often results in DNS packet corruption when using UDP because most DNS implementations (including the one in this package) will only read the first 512 bytes.

**Comment by mdempsky** [comment]
This is intentional: dnsMsg.Pack is only used (aside from tests) for encoding single-question query packets, which aren't compressible anyway.
