### ISSUE TITLE
x/crypto/ssh/agent: when adding a cert to the agent, constraints are ignored for non-rsa key types

### ISSUE THREAD

**Issue by nsheridan** [golang/go#15953]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
Try to add a ssh certificate to the agent with a time limit. The time limit is honored for certs added with an rsa private key, ignored for others (ecdsa, ed25519...)
https://gist.github.com/nsheridan/e67bd4d26860b6db46f9d8caa0fbaad9

4. What did you expect to see?
```
% date && go run key_expiry.go && ssh-add -l
Fri  3 Jun 2016 20:53:19 IST
2048 SHA256:8yWp2quo0pXpU1+RkO5FRnGsL7FahlFNNSEQEs7Dgro  (RSA-CERT)
384 SHA256:c5dmdgIV4LOHlLd89aBi1m7YnfT6GR+1FtuOSSoHYG4  (ECDSA-CERT)
% date && ssh-add -l
Fri  3 Jun 2016 20:53:29 IST
The agent has no identities.
```

5. What did you see instead?
```
% date && go run key_expiry.go && ssh-add -l
Fri  3 Jun 2016 20:53:19 IST
2048 SHA256:8yWp2quo0pXpU1+RkO5FRnGsL7FahlFNNSEQEs7Dgro  (RSA-CERT)
384 SHA256:c5dmdgIV4LOHlLd89aBi1m7YnfT6GR+1FtuOSSoHYG4  (ECDSA-CERT)
% date && ssh-add -l
Fri  3 Jun 2016 20:53:29 IST
384 SHA256:c5dmdgIV4LOHlLd89aBi1m7YnfT6GR+1FtuOSSoHYG4  (ECDSA-CERT)
```

The issue appears to be that `client.insertCert()` sets the constraints only if the key type is rsa:
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L579
while constraints are not set for other key types:
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L586
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L593
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L601

The only impacts ssh certificates. keys are handled correctly:
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L453
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L464
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L474
https://github.com/golang/crypto/blob/master/ssh/agent/client.go#L482

**Comment by ianlancetaylor** [comment]
CC @agl @hanwen
