### ISSUE TITLE
gofmt: Inconsistent alignment with composite literals

### ISSUE THREAD

**Issue by amayausky** [golang/go#15951]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/amayausky/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
Trying to initialize an array of structs using keyed composite literals: https://play.golang.org/p/gObERVYL19

4. What did you expect to see?
I expected to see all elements aligned properly.

5. What did you see instead?
The second element's alignment is off even though the third element, with the same keys but different arrangement, is aligned correctly.

**Comment by ianlancetaylor** [comment]
Same as #7819.
