### ISSUE TITLE
2016_06_06 Version Fails to Build on Raspberry Pi 1

### ISSUE THREAD

**Issue by martinvahi** [golang/go#15965]
The citation is for fresh checkout.

    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ ./bootstrap.bash 
    usage: GOOS=os GOARCH=arch ./bootstrap.bash
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ GOOS=linux GOARCH=arm ./bootstrap.bash 
    #### Copying to ../../go-linux-arm-bootstrap
    
    #### Cleaning ../../go-linux-arm-bootstrap
    
    #### Building ../../go-linux-arm-bootstrap
    
    ##### Building Go bootstrap tool.
    cmd/dist
    ERROR: Cannot find /home/mmmv/go1.4/bin/go.
    Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ uname -a
    Linux computenode1softf1com 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ date
    Sun Jun  5 21:58:05 UTC 2016
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ which go
    /usr/bin/go
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $ go version
    go version go1.3.3 linux/arm
    mmmv@computenode1softf1com /opt/mmmv/go/v2016_06/go/src $

**Comment by adg** [comment]
```
ERROR: Cannot find /home/mmmv/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
```

Did you follow the instructions at https://golang.org/install/source ?

**Comment by martinvahi** [comment]
The link [seems to be broken](https://archive.is/W34bg), but I did follow the instructions at ["Getting Started"](https://golang.org/doc/install).

**Comment by adg** [comment]
Sorry,  I sent the wrong link. You need the follow the source installation instructions: https://golang.org/doc/install/source
