### ISSUE TITLE
x/net/webdav: Wrong name0 passed to Confirm() with Handler prefix.

### ISSUE THREAD

**Issue by gaillard** [golang/go#15967]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.7beta1 and go1.6

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
Install davfs and `sudo mount -t davfs 'http://127.0.0.1/some/path/prefix/theresource' /tmp/dav`
Run the http server with the webdav handler:

```
&webdav.Handler{
	"/some/path/prefix",
	NewMemFS(),
	NewMemLS(),
	func(r *http.Request, err error) {
		fmt.Println(r.Method, r.Header, err)
	},
```

Touch a file.

4. What did you expect to see?
Success!

5. What did you see instead?
The PUT request had a "webdav: locked" error.
When printing the inside the following function found in lock.go int he webdav package:

```
func (m *memLS) lookup(name string, conditions ...Condition) (n *memLSNode) {
	// TODO: support Condition.Not and Condition.ETag.
	for _, c := range conditions {
		n = m.byToken[c.Token]
		fmt.Println("HERE!", c, n, name)
		if n == nil || n.held {
			continue
		}
		if name == n.details.Root {
			return n
		}
		if n.details.ZeroDepth {
			continue
		}
		if n.details.Root == "/" || strings.HasPrefix(name, n.details.Root+"/") {
			return n
		}
	}
	return nil
}
```

name is "/some/path/prefix/theresource" while n.details.Root is "/theresource" :(

Problem seems to be here https://github.com/golang/net/blob/master/webdav/webdav.go#L151
I have verified that if you put the following instead of line 151:

```
reqPath, status, err := h.stripPrefix(u.Path)
if err != nil {
	return nil, status, err
}
lsrc = reqPath
```

it solves the issue in my case.

**Comment by nigeltao** [comment]
Thanks for the great bug report and diagnosis.
