### ISSUE TITLE
Switch statement should support same if semantics

### ISSUE THREAD

**Issue by purpleidea** [golang/go#15968]
I'm matching a whole bunch of conditions in a switch statement. In this case a bunch of errors. It looks like this:

```
		switch {
		case err == etcdserver.ErrStopped:
		fallthrough
		case err == raft.ErrStopped:
		fallthrough
		case isGrpc(etcdserver.ErrStopped):
		fallthrough
		case isGrpc(grpc.ErrClientConnClosing):
		fallthrough
		case delayErr, ok := err.(*CtxDelayErr); ok: // custom error

		// TODO: do some stuff here...

}
```

The last case that I added:

```
	case delayErr, ok := err.(*CtxDelayErr); ok: // custom error
```

isn't supported in golang and causes a syntax error. I think this should be a nice addition to the language. The best part is that it's a completely backwards compatible change.

Thanks

**Comment by adg** [comment]
What are the advantages of your proposed syntax compared to the following code snippet?
```
if err == etcdserver.ErrStopped ||
  err == raft.ErrStopped ||
  isGrpc(etcdserver.ErrStopped) ||
  isGrpc(grpc.ErrClientConnClosing) {
  if delayErr, ok := err.(*CtxDelayErr); ok {
    // do something
  }
}
```

At this stage in Go 1, the bar for language changes is high, and I doubt this one meets it. There must be a more compelling story than "it should be a nice addition to the language," before this change can be seriously considered.

If you're interested in pursuing this further, there is a process for proposing changes to Go. https://golang.org/s/proposal-process

**Comment by purpleidea** [comment]
@adg 

> What are the advantages of your proposed syntax compared to the following code snippet?

They're not identical. Mine is an OR of many different conditions. 

But to answer your question, I think the advantage of including the case statement I mentioned is that it's logically consistent with the rest of the language.

The technical advantages are that it allows big matches on error conditions (and other things) while keeping some variables limited in scope (as in my example).

I don't really have the cycles to go through this long proposal process, but I was hoping I had planted a useful seed here. If you implement it, a props to @purpleidea would be classy.

Cheers,
James

**Comment by adg** [comment]
> They're not identical. Mine is an OR of many different conditions.

Right, I originally wrote this using logical || but then tricked myself into changing it to &&. Oops.

FWIW, a cleaner way of expressing OR in a switch:

```
switch {
case err == etcdserver.ErrStopped,
  err == raft.ErrStopped,
  isGrpc(etcdserver.ErrStopped),
  isGrpc(grpc.ErrClientConnClosing):
  if delayErr, ok := err.(*CtxDelayErr); ok {
    // TODO: do some stuff here...
  }
}
```

> I don't really have the cycles to go through this long proposal process, but I was hoping I had planted a useful seed here.

Okay, well I'll close the issue until such time as someone wants to pursue it.

**Comment by purpleidea** [comment]
@adg 

> FWIW, a cleaner way of expressing OR in a switch:

Unfortunately, your example is still not correct. The correct version, which doesn't have the scope benefits I mentioned is:

```
delayErr, isDelayErr := err.(*CtxDelayErr) // custom error
switch {
case err == etcdserver.ErrStopped, err == raft.ErrStopped:
	fallthrough
case isGrpc(etcdserver.ErrStopped) || isGrpc(grpc.ErrClientConnClosing):
	fallthrough
case isDelayErr:

	// DO STUFF
}
```

> Okay, well I'll close the issue until such time as someone wants to pursue it.

Thanks for your consideration.

As an aside (and I mean this is the most friendly way) I've heard the phrase "the bar for [language|stdlib|whatever] changes is high" from others before. I don't think this is the most inviting way to encourage people to contribute and think about how to improve golang. Don't worry, I'm not mad, but it might be a good thing to reconsider for others :) It makes me feel that since I'm not a google employee I wouldn't have an idea that could be worth the consideration of google employees.

With respect,
James

**Comment by adg** [comment]
Hey, sorry it came off that way.

> It makes me feel that since I'm not a google employee I wouldn't have an idea that could be worth the consideration of google employees.

It has nothing to do with google employees vs non-google employees, but rather the scope and purpose of the proposed change. To be considered seriously at this late stage of the language's development, the change must solve a real, significant problem or it must be very minor indeed. Take a look at the [change history of the spec](https://github.com/golang/go/commits/master/doc/go_spec.html) to get an idea of what passes for 'language change' over the last few years. (Almost all the changes there do not affect users of the language at all.)

**Comment by purpleidea** [comment]
@adg 

> Hey, sorry it came off that way.

Seriously no apology needed, I'm sure you're a good dude. It was more just a general comment to hopefully provide positive reflection because I seem to hear that a lot (whether directed at me or others).

I guess I don't see golang in the "late stage" is all. Only soon-to-be-deprecated is in late state to me :)

Keep up the good work, I enjoy (most of) your language, thanks!

**Comment by ianlancetaylor** [comment]
@purpleidea Here is one way to think about it.  Every change to the language has a cost: it's an additional thing that users of the language need to learn and understand.  I agree that your proposal makes case clauses more like if statements, but it makes them less like case clauses.  It's something else to learn.  So the benefit of the change has to outweigh the cost.  One way to measure the benefit is to look through a body of Go code and see how often this could be used.  Look for chains of if statements in which the else clauses use simple statements in their if conditions, and look for switch statements that use convoluted logic to call functions and capture the results.

That said, I don't understand how your initial example could work anyhow.  The first cases, the fallthrough cases, are going to wind up in a block in which `delayErr` and `ok` are declared but were never set.  That seems like a recipe for confusion.  You can say that `delayErr` and `ok` do get set, but now there is a complicated rule to remember involving `fallthrough`.  Or you could say that `delayErr` and `ok` can only be used in the case statement condition, but now there is a complicated rule to remember involving `case`.  So I think the complexity of this suggestion is actually higher than it appears.

**Comment by purpleidea** [comment]
@ianlancetaylor 

>  Every change to the language has a cost: it's an additional thing that users of the language need to learn and understand

I understand, and I am fine with your decision not to include this, however for me it felt as if the extra thing I needed to remember (the "exception") is that short declaration doesn't work with case statements instead of it being consistent through out the language.

>  One way to measure the benefit is to look through a body of Go code and see how often this could be used.

I don't have millions of lines I could run a script on to check this. Word on the street is that google has tools that can do this type of analysis on their existing bodies of code. Do you think you could run such an analysis and share the data? Perhaps I've misunderstood what is possible.

> That said, I don't understand how your initial example could work anyhow.

Sorry about that, I guess I didn't explain clearly. Put another way, the idea is to have a readable case statement which can match many different error conditions, including some that require short declaration to see if the err is of the correct type.

Thanks again for your time and keep up the great work! (not sarcasm)

Cheers,
James
