### ISSUE TITLE
x/mobile: gomobile init fails when checking sha256 for NDK (again)

### ISSUE THREAD

**Issue by atavism** [golang/go#15973]
1. What version of Go are you using (`go version`)?

`go version go1.6.2 darwin/amd64`
1. What operating system and processor architecture are you using (`go env`)?

`GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/todd/Dev/go/src/github.com/getlantern/lantern"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"`
1. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   A link on play.golang.org is best.

Completely removed gomobile and re-installed from scratch. Ran `gomobile init`
1. What did you expect to see?

Successful `gomobile init`
1. What did you see instead?

`gomobile: sha256 for "gomobile-openal-soft-1.16.0.1.tar.gz": 84c9361734902df622dd49a8c0cfb0090fd7743a2cbf927a9ae85c4826beb173, want ff7ff835355a1158001e6b6cc03d3a65abb508abc34a5f19ae9af0bdeadd978b`

**Comment by 8tt** [comment]
This still happens, even after re-install.
go version go1.7.1 darwin/amd64

**Comment by eliasnaur** [comment]
Gomobile doesn't download the NDK anymore.
