### ISSUE TITLE
syscall.Stat_t{} for blocks always returns 0 instead of amount of blocks present on hdd

### ISSUE THREAD

**Issue by pkutys** [golang/go#15971]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.4.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
Centos 7
GOARCH="amd64"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

package main

import (
        "fmt"
         linuxproc "github.com/c9s/goprocinfo/linux"
        "regexp"
        "syscall"
)

func main() {
        var disk = make([]string, 1)
        var match = regexp.MustCompile("[a-z]{3,4}$")
        stat, err := linuxproc.ReadDiskStats("/proc/diskstats")
        if err != nil {
                fmt.Printf("Erroc accured %v\n", err)
        }
        for i := range stat {
                match1 := match.MatchString(stat[i].Name)
                if match1 {
                        fmt.Println(stat[i].Name)
                        makePath := "/dev/" + stat[i].Name
                        disk = append(disk, makePath)
                }
        }
        // var path string
         var fs = syscall.Stat_t{}
        for i := range disk {
        //      fs := syscall.Stat_t{}
                path := disk[i]
                fmt.Println(path)
                err := syscall.Stat(path, &fs)
                if err != nil {
                        fmt.Printf("FATAL: %v\n", err)
                }
                fmt.Printf("Blocks on device: %s %d\n", path, fs.Blocks)
                fmt.Printf("Blocksize: %s %d\n", path, fs.Blksize)
                fmt.Printf("space of disk: %s %v\n", path, fs.Blocks*fs.Blksize)
        }

}

4. What did you expect to see?
Real amount blocks on device

5. What did you see instead?
fs.Blocks returns 0

**Comment by davecheney** [comment]
I am sorry but Go 1.4 is not supported. Please upgrade to Go 1.6.2 and see if the issues has been fixed.

**Comment by pkutys** [comment]
Hi @davecheney, 
I think it doesn't matter, as Stat() cannot provide amount of blocks from block device, seems this function only can manage files.
I've found workaround how i can obtain amount blocks on device.
Thank you the help anyway.
