### ISSUE TITLE
cmd/compile: defer of nil interface call does not panic

### ISSUE THREAD

**Issue by aclements** [golang/go#15975]
The following program behaves differently depending on whether or not it's compiled with SSA:

```go
package main

type Closer interface {
	Close()
}

func main() {
	var x Closer
	defer x.Close()
	println("not reached")
}
```

When compiled without SSA, it does not print "not reached". However, when compiled with SSA, it *does* print "not reached". Based on my understanding of the spec, this program should not print "not reached" because the evaluation of `x.Close` to a function value happens on the defer line and should cause a nil panic (though either way it shouldn't change with SSA).

```
$ go run -gcflags -ssa=0 x.go
panic: runtime error: invalid memory address or nil pointer dereference
...

$ go run x.go
not reached
panic: runtime error: invalid memory address or nil pointer dereference
```

This pattern appears in `test/fixedbugs/issue6055.go`.

/cc @cherrymui @randall77

**Comment by cherrymui** [comment]
It also behaves differently for `go` statement (change the `defer` to `go` in the above test case).
CL 23820 mailed for matching the old behavior.
