### ISSUE TITLE
misc/cgo/testsanitizers: tsan6.go flaky on ubuntu 16.10

### ISSUE THREAD

**Issue by mwhudson** [golang/go#15983]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +3ba3155 Mon Jun 6 21:15:40 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

Ubuntu 16.10, amd64

testsanitizers failed for me. Digging shows that it's the recently added tsan6.go reporting a race:

```
==================
WARNING: ThreadSanitizer: data race (pid=23760)
  Write of size 1 at 0x00c420300000 by main thread:
    #0 f <null> (tsan6+0x00000044f90c)
    #1 _cgo_e3fc48de400e_Cfunc_f <null> (tsan6+0x00000044f996)

  Previous write of size 8 at 0x00c420300000 by thread T3:
    #0 mmap <null> (libtsan.so.0+0x000000027b86)
    #1 x_cgo_mmap <null> (tsan6+0x00000045028c)
    #2 runtime.callCgoMmap /home/ubuntu/go/src/runtime/sys_linux_amd64.s:329 (tsan6+0x00000044dfed)
    #3 <null> <null> (libtsan.so.0+0x0000000244c9)

  Thread T3 (tid=23764, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x000000028410)
    #1 _cgo_sys_thread_start <null> (tsan6+0x0000004500f2)
    #2 x_cgo_thread_start <null> (tsan6+0x0000004504f6)
    #3 runtime.asmcgocall /home/ubuntu/go/src/runtime/asm_amd64.s:620 (tsan6+0x00000044c35c)

SUMMARY: ThreadSanitizer: data race (/home/ubuntu/go/misc/cgo/testsanitizers/tsan6+0x44f90c) in f
==================
```

It doesn't fail all the time, but it's most of the time, maybe 75%.

The full test doesn't fail for me on 16.04, but if I run CGO_CFLAGS=-fsanitize=thread CGO_LDFLAGS=-fsanitize=thread  go build  "-installsuffix=tsan" tsan6.go, the resulting tsan6 binary reports a race most of the time. Which is odd.

**Comment by ianlancetaylor** [comment]
What version of clang?  What is the kernel version?

**Comment by ianlancetaylor** [comment]
Oh, I bet you are using GCC, not clang.  I will send a CL.

**Comment by mwhudson** [comment]
Ah yes, gcc. Test passes reliably with CC=clang.

**Comment by ianlancetaylor** [comment]
Can you try https://golang.org/cl/23833 ?
