### ISSUE TITLE
go/test: doesn't pass flags to tests in sub folders

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#15982]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +3ba3155 2016-06-06 21:15:40 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
n/a

3. What did you do?
project/lib/lib_test.go:
```go
package lib

import (
	"flag"
	"log"
	"os"
	"testing"
)

var f = flag.Bool("f", false, "")

func TestMain(m *testing.M) {
	flag.Parse()
	if *f {
		log.Println("w00t!")
	}
	os.Exit(m.Run())
}
```

4. What did you expect to see?
"w00t" or even an error.

5. What did you see instead?
```
➤ go test -f ./lib/...
?       _/tmp/proj      [no test files]
```
Removing `-f` works as intended:

```
➤ go test ./lib/...
ok      _/tmp/proj/lib  0.001s
```

**Comment by ianlancetaylor** [comment]
Flags that you want to pass to the test binary must follow the list of packages you want to test.

    go test ./lib/... -f

But note that by default `go test` does not display the output of tests that pass.  If you want to see that output, run

    go test -v ./lib/... -f

Closing because this is working as expected.
