### ISSUE TITLE
cmd/compile: compiler does not allow "direct binding" of function return values to `copy` arguments

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#15992]
go version devel +2f08888 Tue Jun 7 06:04:23 2016 +0000 linux/amd64

The spec allows "forwarding"/"direct binding" of return values to function arguments 
https://golang.org/ref/spec#Calls

> As a special case, if the return values of a function or method g are equal in number and individually
> assignable to the parameters of another function or method f, then the call f(g(parameters_of_g)) will
> invoke f after binding the return values of g to the parameters of f in order. 

For the following program (https://play.golang.org/p/YEJSEfQLA8):

``` Go
package main

import (
    "fmt"
)

func f(a []byte) ([]byte, []byte) {
    return a, []byte("abc")
}

func g(a []byte) ([]byte, string) {
    return a, "abc"
}

func main() {
    a := []byte{1, 2, 3}
    n := copy(f(a))
    fmt.Println(n, a)

    b := []byte{1, 2, 3}
    n = copy(f(b))
    fmt.Println(n, b)
}
```

the compiler issues messages

> prog.go:17: missing arguments to copy
> prog.go:21: missing arguments to copy

The same program passes when compiled via `gotypes` and `gccgo`.

**Comment by griesemer** [comment]
Moving to 1.9Maybe. There are easy work-arounds and this is exceedingly rare in the first place.

**Comment by odeke-em** [comment]
I actually wanted to work on this but I spent so much time but in vain trying to figuring out why ascompatet wasn't firing, so I moved on to the next bug.

**Comment by griesemer** [comment]
Unlikely to happen at this point. Moving to 1.10.

**Comment by mdempsky** [comment]
cmd/compile also erroneously errors on

    delete(func() (map[int]int, int) { return nil, 0 }())

**Comment by mdempsky** [comment]
@odeke-em The error about wrong number of arguments to copy happens during typechecking. See `case OCOPY` in typecheck1.

For comparison, see `case OCOMPLEX` for how to correctly handle multi-valued function calls. Well, almost; it fails to handle this case:

    package p

    var x interface{ g() (float64, float64) }
    var _ = complex(x.g())

**Comment by odeke-em** [comment]
Interesting, thanks for the debugging @mdempsky I was stumped before as to when it happened.

**Comment by mdempsky** [comment]
@odeke-em I usually start by tracking down where the error message is being printed. In this case, `"missing arguments to copy"` only appears once in typecheck.go.

**Comment by odeke-em** [comment]
Nice nice, same-ish here. See the thing though is I spent hours tracing through all the steps that I could but it led me for some reason down to astcomp*. Perhaps I should have done it not at 2AM :)

**Comment by griesemer** [comment]
Been like this forever. Not urgent (but shouldn't bee too hard, either). Moving to 1.12.

**Comment by griesemer** [comment]
Moving to unplanned. This is not stopping anyone from getting work done.
