### ISSUE TITLE
Strange output from "go tool vet"

### ISSUE THREAD

**Issue by bobjalex** [golang/go#15990]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

>go version
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?

>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoLib
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?

Ran "go vet", producing mysterious results

A tiny Go source file that demonstrates the issue (which I named "vet_check.go"):

    package xxx

    type XXX struct {
        s string
    }

    func (xxx *XXX) Peek(length int) string {
        return xxx.s
    }

4. What did you expect to see?

No suggestions.

5. What did you see instead?

 >go tool vet \junk\vet_check.go
 \junk\vet_check.go:7: method Peek(length int) string should have signature Peek(int) ([]byte, error)

If the name of the method is changed from Peek to Peekx, problem goes away.

I was able to reproduce this problem with my test program isolated from all other Go source files, in its own directory, and the $GOPATH environment variable removed (wondering if there might have been interaction from other source files -- apparently not).

**Comment by ianlancetaylor** [comment]
`Peek` is on the list of canonical methods in cmd/vet/methods.go.  A `Peek` method is normally expected to have the signature Peek(int) ([]byte, error), just like `Read` is expected to be `Read([]byte) (int, error)`.

So, I'm going to close this issue as working as expected.  Note that the warnings from vet are advisory.  Your code is likely still correct.

**Comment by bobjalex** [comment]
Hi Ian --

Thanks for the quick reply -- that clears up the mystery.

A thought: I had never heard of "canonical methods" before, and spent a
fair amount of time trying to figure out why on earth my method signature
was wrong. Perhaps adding a bit of explanation to the message issued by
"vet" could save others an hour or so of wild-goose-chase time...

Bob
