### ISSUE TITLE
cmd/compile: bad compilation

### ISSUE THREAD

**Issue by dsnet** [golang/go#16016]
Using `go1.7beta1`

Consider the following program:
```go
package foo

import (
	"testing"
	"time"
)

type T struct{}

func (*T) Foo(vals []interface{}) {
	switch v := vals[0].(type) {
	case string:
		_ = v
	}
}

type R struct{ *T }

type Q interface {
	Foo([]interface{})
}

func TestQueryStreaming(t *testing.T) {
	var q Q = &R{&T{}}
	for i := 0; i < 10000; i++ {
		go func() {
			defer q.Foo([]interface{}{"meow"})
			time.Sleep(100 * time.Millisecond)
		}()
	}
	time.Sleep(1 * time.Second)
}
```
The method `Foo` is a read only method that does a type assertion on the input. It should be safe to run that operation concurrently.

Currently this leads to corrupted memory:
```
$ go test foo_test.go
unexpected fault address 0x1643
unexpected fault address 0x14f5
fatal error: fault
unexpected fault address 0x15e8
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1643 pc=0x46d48c]

goroutine 464 [running]:
runtime.throw(0x50a6eb, 0x5)
	/usr/local/go.tip/src/runtime/panic.go:566 +0x95 fp=0xc42022b6b8 sp=0xc42022b698
runtime.sigpanic()
	/usr/local/go.tip/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42022b710 sp=0xc42022b6b8
command-line-arguments.(*T).Foo(0x5adfd8, 0xc420234000, 0x1, 0x1)
	/home/joetsai/foo_test.go:11 +0x3c fp=0xc42022b758 sp=0xc42022b710
command-line-arguments.TestQueryStreaming.func1(0x580320, 0xc42003a028)
	/home/joetsai/foo_test.go:29 +0xe0 fp=0xc42022b7b0 sp=0xc42022b758
runtime.goexit()
	/usr/local/go.tip/src/runtime/asm_amd64.s:2060 +0x1 fp=0xc42022b7b8 sp=0xc42022b7b0
created by command-line-arguments.TestQueryStreaming
	/home/joetsai/foo_test.go:29 +0x9c
```

This passes with SSA or GC off:
```
$ GOGC=off go test foo_test.go
ok  	command-line-arguments	1.030s
$ go test -gcflags=-ssa=0 foo_test.go
ok  	command-line-arguments	1.048s
```

/cc @randall77 @ianlancetaylor

**Comment by adg** [comment]
cc @randall77 @ianlancetaylor

**Comment by dr2chase** [comment]
I'm sitting in a meeting, so I'm bisecting.

**Comment by dr2chase** [comment]
commit 3572c64  cmd/compile: keep pointer input arguments live throughout function
Preceding good commit is d520226

**Comment by randall77** [comment]
Looks like the live variable info at the start of one of the autogenerated functions is not correct.
good CL:
<autogenerated>:1: live at entry to (*R).Foo: .this vals
bad CL:
<autogenerated>:1: live at entry to (*R).Foo: .this

vals is missing from the live list, so if we trigger a GC right at the start of (*R).Foo, we won't scan its argument (the slice of interface{}).

There's no "use" of the arg variable visible in the assembly.  The JMPRET implicitly uses the args, though, as they are read by the tail callee.  The fix may be to consider JMPRET as having read all the args.
