### ISSUE TITLE
cmd/compile: PowerPC (LE) SSA support

### ISSUE THREAD

**Issue by dr2chase** [golang/go#16010]

**Comment by randall77** [comment]
David, should we close this?

**Comment by dr2chase** [comment]
Depends -- there's a fair amount of optimization yet to do (e.g., nil
checks) but I did turn it on and so it is now regularly tested.
I had hoped that Lynn Boger would be jumping on this, but I think she is
also dealing with more urgent bugs (like the giant
sections problem).  If no progress soon, I'll get back on it.

**Comment by randall77** [comment]
Ok.  I'm happy to close this bug when we reach parity with the old compiler.  We don't need to be finished all the optimizations to declare success.

**Comment by rsc** [comment]
What remains to be done before closing this bug? 
@dr2chase @laboger

**Comment by bradfitz** [comment]
I'd say this is done. Closing. File new bugs as needed.
