### ISSUE TITLE
reflect modyfied all strings (I can not modified single instance by reflect)

### ISSUE THREAD

**Issue by SebastianPozoga** [golang/go#16023]
1. What version of Go are you using (`go version`)?
current play.golang version
 
2. What operating system and processor architecture are you using (`go env`)?
current play.golang version

3. What did you do?
I create script like that https://play.golang.org/p/u_tH8tTgs4
package main

```
import (
	"fmt"
	"reflect"
)

type T struct {
	p interface{}
}

func main() {
	str := "str"
	tree := T{
		p: interface{}(&str),
	}
	v := reflect.ValueOf(tree.p).Elem()
	if !v.CanSet() {
		panic("the value can not be set")
	}
	v.SetString("new str")

	fmt.Println("Hello, ", *(tree.p.(*string)), " ", str)
}
```

Output:

> Hello,  new str   new str

It mean str variable is changed. I am not sure it is correct action.  CanSet return false for *string always. When I use reflect I modified  both value.

4. What did you expect to see?

> Hello,  new str  str

5. What did you see instead?

> Hello,  new str   new str

**Comment by ianlancetaylor** [comment]
In effect, you did `p := &str` and then you did `*p = "new str"`.  This is working as expected.
