### ISSUE TITLE
syscall: EpollEvent struct incorrect for s390x

### ISSUE THREAD

**Issue by mundaym** [golang/go#16021]
This was fixed for ppc64/ppc64le in https://github.com/golang/go/issues/15135. The struct is missing a padding field between the ```Events``` and ```Fd``` fields.

I think the ```syscall.EpollEvent``` struct is wrong for all 64-bit architectures except amd64 (which uses the packed attribute and therefore has no alignment padding) and ppc64/ppc64le (which was fixed).

https://github.com/docker/containerd currently uses the ```syscall.EpollEvent``` struct directly for some operations. Presumably they should be using ```golang.org/x/sys/unix``` (which uses the correct padding on arm64 and s390x) instead however I'd like to fix this anyway since it is a very small change.

CL to follow.

**Comment by mwhudson** [comment]
Am I going to want to fix this on s390x (and arm64 I guess?) for the version of Go in Ubuntu 16.04 before I try to build docker/containerd there? Do you have a test case, or are containerd's own tests enough?

**Comment by mundaym** [comment]
I think you will need to yes. You might also want to pick up https://github.com/golang/go/commit/0324a3f828d3a2f48751df2bbd54ad20499e598a if you do an update (this also came up during docker testing).

The issue manifests itself as docker-containerd hanging when trying to run the CI tests, so I guess you won't be able to get the test suite to start without this change.

I don't *think* you'll need the change for arm64 - they appear to have worked around this issue by re-implementing the epoll calls using cgo (!): https://github.com/docker/containerd/commit/6299489d03d024ad8f973f121a7c183840904c33.

**Comment by mwhudson** [comment]
Thanks, I've got both those fixes in 16.10 now and have started the process for getting them into 16.04.
