### ISSUE TITLE
cmd/compile: possible liveness bug

### ISSUE THREAD

**Issue by randall77** [golang/go#16026]
```
type T [10]*int
func f(t T) {
	g = t
}
var g T
```
compiles to roughly:
```
autotmp_0 = t (using duffcopy)
if writebarriers_enabled {
    typedmemmove(&g, &autotmp_0)
} else {
    g = autotmp_0 (using duffcopy)
}
```
Problem: ```autotmp_0``` is not considered live at `typedmemmove`.  The fact that `typedmemmove` (and callees) are marked as nosplit saves us, but I can't yet convince myself that there won't be other cases like this but without nosplit saving us.
```
$ go tool compile -live ~/go/tmp4.go
/usr/local/google/home/khr/go/tmp4.go:8: live at entry to f: t
/usr/local/google/home/khr/go/tmp4.go:9: live at call to typedmemmove: t   <- missing autotmp_0
```

(Another less serious issue is that autotmp_0 is unnecessary in this example, but compilers; go figure.)

Found using CL https://go-review.googlesource.com/23924 

@aclements

**Comment by adg** [comment]
@randall77 any movement here?

**Comment by randall77** [comment]
No, I have been unable to write a test that actually demonstrates a real bug.  I'm still working on it.

**Comment by adg** [comment]
@randall77 should this block go1.7beta2?

**Comment by randall77** [comment]
No.

**Comment by randall77** [comment]
I've determined that typedmemmove is the only call for which this happens.  All other calls are ok.  So I'm marking this closed, I'll get my clobber code in (deactivated by default) for 1.8.
