### ISSUE TITLE
x/review/git-codereview: support mailing multiple revisions with a single CL

### ISSUE THREAD

**Issue by josharian** [golang/go#16034]
``` bash
$ git mail
git-codereview: cannot mail: multiple changes pending; must specify commit on command line:
    cacb069 git-codereview: pass args to installHook
    e3eeef8 git-codereview: use codereview.cfg from working tree
    1ac8f8d git-codereview: fix TestPendingNoneBranch
    1c26cef git-codereview: disable failing tests
```

I will now proceed to run `git mail` individually on every single commit, in order, manually copying and pasting in the SHA1s. This happens all the time, at least for me. I'd like to be able to tell `git mail` to mail all of them, re-using the other flags (reviewer, trybot) for every commit:

Maybe:

``` bash
$ git mail -r adg -trybot --all
```

@adg, opinions?

**Comment by josharian** [comment]
Never mind. I'm an idiot. Can't believe it has taken me how long?? to figure out that I can just git mail the topmost commit. Sigh.

**Comment by timbunce** [comment]
You're not an idiot @josharian.
The error message is not helpful. This is a valid usability bug.
Adding something like "(use latest commit to submit them all)" would be simple and helpful.

**Comment by josharian** [comment]
CL welcome!

**Comment by rasky** [comment]
Keep this open as it's a valid issue.

**Comment by mvdan** [comment]
I also completely failed to understand that this is how it's supposed to be used.

Here's a question - why shouldn't `git-codereview mail` (with no arguments) just mean `git-codereview HEAD`? It seems to me like that's what people would understand it to mean. For example, `git push` with no arguments also pushes the head of the current branch.

**Comment by josharian** [comment]
That sounds good to me. Alternatively I’d be happy enough with a better error message and accepting any git ref (eg “head”).

**Comment by ysmolsky** [comment]
Wait a minute, but `mail HEAD` works for me:
```
~/golang (ssa_cfg $%) % git mail HEAD
remote: Processing changes: refs: 1, updated: 2, done
remote:
remote: SUCCESS
remote:
remote: Updated Changes:
remote:   https://go-review.googlesource.com/c/go/+/142517 cmd/compile: add control flow graphs to ssa.html
remote:   https://go-review.googlesource.com/c/go/+/144557 cmd/compile: make ssa blocks collapsable in ssa.html
remote:
Updated tag 'ssa_cfg.mailed' (was 7794b8dadd)
```
Do we want to make `mail` command to mail the `HEAD` by default in case of the chain of changes?

**Comment by ysmolsky** [comment]
This was fixed by the CL.
