### ISSUE TITLE
x/tools/cmd/godoc: broken links

### ISSUE THREAD

**Issue by pierrre** [golang/go#16031]
On https://golang.org/pkg/net/http/#DefaultTransport
There are links like this one: https://golang.org/pkg/net/http/#ExpectContinueTimeout
They are all broken. (the anchor is invalid)

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by pierrre** [comment]
Quick fix: godoc.org does not display links on `ExpectContinueTimeout`:
https://godoc.org/net/http#DefaultTransport
