### ISSUE TITLE
net/http: http.ServeMux can't find registered handler for CONNECT requests

### ISSUE THREAD

**Issue by fanyang01** [golang/go#16045]
1. What version of Go are you using (`go version`)?
`go version devel +fee02d2 Fri Jun 10 04:12:50 2016 +0000 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
`linux amd64`

3. What did you do?
Register a CONNECT proxy handler to `http.ServeMux`:
[https://play.golang.org/p/5rrDNhffaz](https://play.golang.org/p/5rrDNhffaz)

4. What did you expect to see?
The proxy handler was called for CONNECT requests.

5. What did you see instead?
`http.ServeMux` can't find the registered handler. It uses `http.NotFoundHandler()` to handle the CONNECT request and `Client.Get` returns a `Not Found` error.

This issue has been reported in #9561 but it has been closed. I want to build a proxy using App Engine, but there is no way to register a proxy handler because only `http.Handle`(underly using `http.ServeMux.Handle`) is available for App Engine. Although it can be avoided by using `http.ListenAndServe` in a normal environment, I think small changes to `http.ServeMux.Handler` implementation can fix this problem.

**Comment by adg** [comment]
What you want to do on App Engine is not possible. App Engine apps cannot accept CONNECT requests from anywhere. Sorry. 😢 

The resolution of issue #9561 still applies, AFAICT.
