### ISSUE TITLE
encoding/json: marshaling a zero value json.Marshaler interface struct field panics

### ISSUE THREAD

**Issue by advincze** [golang/go#16042]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   darwin/amd6
3. What did you do?
   https://play.golang.org/p/MsVP9u-We5
4. What did you expect to see?
   {"M":null}
   https://golang.org/pkg/encoding/json/#Marshal  says "A nil interface value encodes as the null JSON object."
5. What did you see instead?
   panic: interface conversion: interface is nil, not json.Marshaler

**Comment by as** [comment]
This issue is the result of this discussion on golang-nuts: https://groups.google.com/forum/#!topic/golang-nuts/rSfgMzknNIY

**Comment by adg** [comment]
It's a bad error message. The panic should be about attempting to call a nil MarshalJSON method, and not about the interface conversion.

**Comment by adg** [comment]
Also if the code is bailing early on seeing a nil json.Marshaler value, then it shouldn't; it's possible for a json.Marshaler whose concrete type is nil to correctly implement the method.
