### ISSUE TITLE
x/sys/unix: arm64 does not have poll

### ISSUE THREAD

**Issue by Jagmn** [golang/go#16052]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.1 and go 1.6.2

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
go get golang.org/x/sys/unix

4. What did you expect to see?
Successful completion

5. What did you see instead?
# golang.org/x/sys/unix
src/golang.org/x/sys/unix/zsyscall_linux_arm64.go:57: undefined: SYS_POLL

Looks like 7f918dd405547ecb864d14a8ecbbfe205b5f930f in https://github.com/golang/sys broke arm64 builds

**Comment by ianlancetaylor** [comment]
Breaking commit is https://golang.org/cl/23661.

I suspect that on ARM64 GNU/Linux we need to use ppoll, which will require converting the timeout field.

CC @kortschak

**Comment by kortschak** [comment]
Using ppoll in place of poll for the ARM64 linux blocks later addition of Ppoll to sys which may be required. Maybe just remove Poll from the ARM64 linux code? What is the best way to leave this?

**Comment by mwhudson** [comment]
I'm not sure if x/sys is the place to have the shim translating poll to ppoll... I'd be ok with removing it on arm64 I think.

**Comment by kortschak** [comment]
What is preferable? Upgrading all to Ppoll or removing Poll from arm64.

**Comment by ianlancetaylor** [comment]
I think it is most useful to implement Poll on arm64 by having it call Ppoll.  That is what we have done for system calls like Stat, Lchown, Dup2, InotifyInit, etc.

**Comment by kortschak** [comment]
While I'm there should I add ppoll to the other arches?

**Comment by ianlancetaylor** [comment]
> While I'm there should I add ppoll to the other arches?

That would be great if you feel like doing it.
