### ISSUE TITLE
cmd/compile: error message with vendor folder not clear 

### ISSUE THREAD

**Issue by sergeylanzman** [golang/go#16053]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2 and 1.7beta1

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/XXXXX/Documents/XXXXX"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
```
package main
func main(){
n := negroni.New()

n = A.AddMiddlewares(n)
...
}
```
```
package A
func AddMiddlewares(n *negroni.Negroni) *negroni.Negroni {
	n.UseFunc(setContext())
	n.UseFunc(newRelicRecorder())
	n.UseFunc(cors())
	n.UseFunc(recovery())
	return n
}
```
4. What did you expect to see?
go 1.6.2
```
cannot use n (type *"github.com/ZZZ/XXXX/vendor/github.com/codegangsta/negroni".Negroni) as type *"github.com/codegangsta/negroni".Negroni in argument to A.AddMiddlewares
```

5. What did you see instead?
go 1.7beta
```
cannot use n (type *negroni.Negroni) as type *negroni.Negroni in argument to A.AddMiddlewares
```

**Comment by adg** [comment]
The compiler is aware that these are distinct packages. The error message should include some disambiguation when the package names are equivalent.

**Comment by ianlancetaylor** [comment]
I'm pretty sure this was reported again as #16133, which is fixed on tip.  I'm going to close this.  If this is still happening on tip, please provide clear instructions for how to reproduce it.
