### ISSUE TITLE
x/mobile/cmd/gomobile: build tags are ignored in a certain situation

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#16062]
Please answer these questions before submitting your issue. Thanks!
## What version of Go are you using (`go version`)?

`go version go1.6.2 darwin/amd64`
## What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### foo.go

```
package foo

import (
    _ "/path/to/package/bar"
)

func foo() {
}
```
### bar.go (in /path/to/package/bar)

```
// any slash slash comment
// +build ignore
This text won't affect compiling, right?
```

Tried `gomobile bind -target ios` for foo.go but failed like:

```
gomobile: go install -p=4 -pkgdir=/Users/hajimehoshi/go/pkg/gomobile/pkg_darwin_arm -tags="" github.com/hajimehoshi/go-ios-test failed: exit status 1
foo.go:4:2: 
internal/bar/bar.go:3:1: expected 'package', found 'IDENT' This
```

It seems like a slash-slash comment prevents from interpreting build tags in dependent libraries. `gomobile bind -target android` worked well BTW.

**Comment by hajimehoshi** [comment]
Hmm, it looks like GOOS=darwin GOARCH=amd64 go run main.go when just running `go run` with GOOS and GOARCH. On my Mac,

```
GOOS=darwin GOARCH=amd64 go run main.go
```

causes the same thing (a comment starting with `//` before build tag comments prevents from interpreting build tags).

**Comment by hajimehoshi** [comment]
The syntax checking might be expected, but it looks like imports are checked: if a lib imported at bar.go is not available on iOS, `gomobile bind -target ios` causes an error. Is this expected?

**Comment by hajimehoshi** [comment]
> The syntax checking might be expected, but it looks like imports are checked: if a lib imported at bar.go is not available on iOS, gomobile bind -target ios causes an error. Is this expected?

Oops, I found this (unexpected lib importing) was my mistake. Please ignore this.

**Comment by hajimehoshi** [comment]
Has this been solved?

**Comment by eliasnaur** [comment]
Sorry, I misread your "Please ignore this." to mean the entire issue.

However, I think this issue should stay closed, because the problem is not gomobile. If you run go install /path/to/foo, you will get the same error:

````
../../../github.com/petejkim/foo/foo.go:4:2: 
../../../path/to/package/bar/bar.go:3:1: expected 'package', found 'IDENT' This
../../../path/to/package/bar/bar.go:3:14: rune literal not terminated
````

gomobile can't bind invalid Go code.
