### ISSUE TITLE
cmd/compile: SSA runtime performance regression on function with multiple idiv instructions

### ISSUE THREAD

**Issue by ALTree** [golang/go#16061]
```
$ gotip version
go version devel +53242e4 Tue Jun 14 05:17:57 2016 +0000 linux/amd64
```

code:

```go
package foo

import "testing"

func maxRem(a int32) int32 {
	maxR := int32(0)
	m := a * a
	r1, r2 := a+1, a-1
	for n := int32(1); n <= a*a; n++ {
		r1 = (r1 * (a + 1)) % m
		r2 = (r2 * (a - 1)) % m
		if r := (r1 + r2) % m; maxR < r {
			maxR = r
		}
	}
	return maxR
}

var sink int32

func BenchmarkMaxRem(b *testing.B) {
	for n := 0; n < b.N; n++ {
		sink = maxRem(100)
	}
}
```

go1.6 vs tip:

```
name      old time/op  new time/op  delta
MaxRem-4   116µs ± 1%   134µs ± 2%  +15.48%  (p=0.000 n=8+8)
```

same function with `int64` is also slower, by `~5%`.

**Comment by randall77** [comment]
Looks like the SSA code does a bunch of spilling to the stack where the legacy compiler doesn't.  The divide instructions require values in specific registers.  Given two subsequent divide instructions, the result of the first needs to be moved somewhere else before the second is issued.  SSA uses a stack slot for that, whereas the legacy compiler uses a register.
This will be a bit tricky to fix, but it is possible.  1.8 milestone sounds right.
