### ISSUE TITLE
compress/gzip: document that Flush writes additional data, even if there is no more compressed data to write 

### ISSUE THREAD

**Issue by pavelnikolov** [golang/go#16068]
I find it confusing that the `gzip.Writer.Flush()` method doesn't actually flush the compressed data to the underlying buffer.
I'm running: `go version go1.6.1 darwin/amd64`

Here is the code: https://play.golang.org/p/zXIh2ZL5Cs 

I was expecting the number of written bytes after flushing and after closing the writer to be the same but that is not the case.

Also calling `Flush()` multiple times results in more data being written to the underlying buffer than it was written to the gzip writer – https://play.golang.org/p/ochlIkK6KS – is this expected behavior or is it a bug?

**Comment by adg** [comment]
It is expected that `Close` should write data in addition to the final `Flush`, as it must conclude the gzip stream with a checksum of its contents.

As for `Flush` writing additional data, the docs say:

> In the terminology of the zlib library, Flush is equivalent to Z_SYNC_FLUSH.

A google search for `Z_SYNC_FLUSH` yields [this page](http://www.bolet.org/~pornin/deflate-flush.html) which contains a description of `Z_SYNC_FLUSH` and it does indeed involve writing extra data.

I don't think we want to change this behavior, as people use `gzip` streams in weird and wonderful ways. Maybe we should document it more?

**Comment by pavelnikolov** [comment]
Thank you for the quick response! Yeah, better documentation would be very useful as I would expect `Flush()` to behave differently and probably I'm not alone.

**Comment by dsnet** [comment]
What @adg said is correct. The behavior is of gzip flushing is necessary for the correct operation of some network protocols.

I can document this.
