### ISSUE TITLE
x/sys/unix: go get golang.org/x/sys/unix (still) broken on arm64

### ISSUE THREAD

**Issue by Jagmn** [golang/go#16065]
Thanks for the ppoll fix! Unfortunately: 

1. What version of Go are you using (`go version`)?
go 1.6.1

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GO15VENDOREXPERIMENT="1"
CC="gcc"
CGO_ENABLED="1"

3. What did you do?
go get golang.org/x/sys/unix

4. What did you expect to see?
Successful completion

5. What did you see instead?

`# golang.org/x/sys/unix`
`src/golang.org/x/sys/unix/syscall_linux_arm64.go:185: cannot use new(*Timespec) (type **Timespec) as type *Timespec in assignment`
`src/golang.org/x/sys/unix/syscall_linux_arm64.go:186: cannot use timeout * 1e+06 (type int) as type int64 in argument to NsecToTimespec`

I can get it to build with the following patch:

`diff --git a/unix/syscall_linux_arm64.go b/unix/syscall_linux_arm64.go`
`index 4211cf6..4b6ff2a 100644`
`--- a/unix/syscall_linux_arm64.go`
`+++ b/unix/syscall_linux_arm64.go`
`@@ -182,8 +182,8 @@ const (`
` func Poll(fds []PollFd, timeout int) (n int, err error) {`
`        var ts *Timespec`
`        if timeout >= 0 {`
`-               ts = new(*Timespec)`
`-               *ts = NsecToTimespec(timeout * 1e6)`
`+               ts = new(Timespec)`
`+               *ts = NsecToTimespec(int64(timeout) * 1e6)`
`        }`
`        if len(fds) == 0 {`
`                return ppoll(nil, 0, ts, nil)`

Does the gopherbot not do compile tests for each GOARCH?

**Comment by ianlancetaylor** [comment]
CC @kortschak 

I actually do not know what tests are done on the subrepos.

@kortschak You can build yourself for a different architecture by simply typing

    GOARCH=amd64 go build

When I do that on my amd64 system I do indeed see

    ./syscall_linux_arm64.go:185: cannot use new(*Timespec) (type **Timespec) as type *Timespec in assignment
    ./syscall_linux_arm64.go:186: cannot use timeout * 1e+06 (type int) as type int64 in argument to NsecToTimespec

**Comment by kortschak** [comment]
@iant, Ugh. I am mortified, this is what you get for almost never using the new built-in.

Thanks for the tip. CL sent.

**Comment by kortschak** [comment]
Unfortunately, that would not have picked up the error though - I'm building on 1.6.2 here, which does not recognised the arm64 GOARCH.

**Comment by kortschak** [comment]
>~~Unfortunately, that would not have picked up the error though - I'm building on 1.6.2 here, which does not recognise the arm64 GOARCH.~~

No, just a typo. Sorry.

**Comment by narJH27** [comment]
Hey,

I am running the `go1.7.4` with the following env settings, and I still see the above issue:

```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

Any idea if this fix has been included in the 1.7.4 build, because the current status of this issue is still `Unreleased` ?

**Comment by bradfitz** [comment]
@narJH27, it's Unreleased because golang.org/x/sys/unix does not ship with Go releases. You need to update your copy of golang.org/x/sys/unix on disk.

**Comment by narJH27** [comment]
@bradfitz I am unsure as to how to go about this update as I am new to Go. Can you please guide me on how to do so?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

But the short summary is "go get -u golang.org/x/sys/unix". If you have problems, see https://golang.org/wiki/Questions.
