### ISSUE TITLE
net/http/pprof: pprof over HTTPS

### ISSUE THREAD

**Issue by Allendar** [golang/go#16073]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/erwin/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

```
$ go tool pprof https://127.0.0.1:8900/debug/pprof/profile
```

4. What did you expect to see?

PPROF console/result

5. What did you see instead?

```
Fetching profile from https://127.0.0.1:8900/debug/pprof/profile
Please wait... (30s)
http fetch https://127.0.0.1:8900/debug/pprof/profile: Get https://127.0.0.1:8900/debug/pprof/profile: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

========================

How can I actually hand my certificate over to the `pprof` tool?

**Comment by mdempsky** [comment]
Your certificate is already being transported to the pprof tool over the HTTPS connection.  The problem is it's not valid for the IP address 127.0.0.1.

**Comment by Allendar** [comment]
Ah yes that seemed to fixed it. Oddly enough browsers and test-tools accept both 127.0.0.1 and localhost locally for testing on that certificate tho.

Now I'm not getting any output tho. I'm using Gin and have `_ "net/http/pprof"` also imported but not seeing anything:

```
$ go tool pprof https://localhost:8900/debug/pprof/profile
Fetching profile from https://localhost:8900/debug/pprof/profile
Please wait... (30s)
Saved profile in /Users/erwin/pprof/pprof.localhost:8900.samples.cpu.002.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) list
profile is empty
(pprof) top5
profile is empty
(pprof) top
profile is empty
```

Am I missing something?

**Comment by mdempsky** [comment]
I'm guessing your service was idle during those 30 seconds, so there was nothing for pprof to measure.

It seems like there's no bug here, so I'm going to optimistically close.  Happy to reopen if mistaken though.

If you have more questions about *using* Go (as opposed to suspected problems within Go itself), please see: https://github.com/golang/go/wiki/Questions

Cheers
