### ISSUE TITLE
/usr/lib/golang/pkg/tool/linux_arm64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

### ISSUE THREAD

**Issue by vanloswang** [golang/go#16082]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/arm64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
Just build openshift origin 1.1.6 on aarch64 platform on CentOS aarch64 edition. failed with below error:
/usr/lib/golang/pkg/tool/linux_arm64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

My device have only 2G memory and no swap space.

4. What did you expect to see?
compile ok.

5. What did you see instead?
compile failed.

**Comment by vanloswang** [comment]
compile k8s and give the same error as follow:
Go version: go version go1.6.2 linux/arm64
+++ [0616 15:45:17] Building go targets for linux/arm64:
    cmd/hyperkube
    cmd/kube-apiserver
    *# k8s.io/kubernetes/cmd/hyperkube
/usr/lib/golang/pkg/tool/linux_arm64/link: running aarch64-linux-gnu-gcc failed: fork/exec /usr/bin/aarch64-linux-gnu-gcc: cannot allocate memory

!!! Error in /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:423
  'go build -o "${outfile}" "${goflags[@]:+${goflags[@]}}" -ldflags "-B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \n') ${goldflags}" "${binary}"' exited with status 2
Call stack:
  1: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:423 kube::golang::build_binaries_for_platform(...)
  2: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:576 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:496
  'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
  1: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:496 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
error: Bad exit status from /var/tmp/rpm-tmp.OphhgA (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.OphhgA (%build)

**Comment by ianlancetaylor** [comment]
I don't see any way for us to fix this.  Your system is out of memory.  It happens.

You  may be able to make the build succeed by setting the environment variable `GOMAXPROCS` to 1.

Closing because I don't think there is anything to do.  Please feel free to comment if you disagree.

**Comment by vanloswang** [comment]
@ianlancetaylor  On RPI3B arm32 os, there is only 1G memory and k8s will compile ok on it. But on Pine64 with 2G memory and aarch64 os, k8s compile failed. After I trace it, I found that as follow:
root      5983  3.4  2.1 265380 44528 pts/0    Sl+  11:41   0:26 go install -ldflags -X github.com/openshift/origin/pkg/version.majorFromGit 1 -X github.com/openshift/orig
root      7762 97.0 76.3 1559592 1554580 pts/0 Rl+  11:51   2:40 /usr/lib/golang/pkg/tool/linux_arm64/link -o /tmp/go-build013022721/github.com/openshift/origin/cmd/opensh......

When the compile proccess reach here, the memory is linear decreasing. It is so obvious and strange.  

Setting the environment variable GOMAXPROCS to 1 is not working for me.

**Comment by maruel** [comment]
Should https://github.com/golang/go/wiki/GoArm#swap be updated? It hints that 256Mb of RAM with 512Mb of swap is sufficient.

**Comment by minux** [comment]
On Sep 19, 2016 9:45 AM, "M-A" <notifications@github.com> wrote:
> Should https://github.com/golang/go/wiki/GoArm#swap be updated? It hints
that 256Mb of RAM with 512Mb of swap is sufficient.

That's the requirement for building Go from source, not the minimum
requirement for building arbitrary Go programs.

**Comment by maruel** [comment]
Oh you are right this issue is about build a random project; I got this error from building the toolchain from sources.

**Comment by davecheney** [comment]
The minimum for building Go from source is 512mb per core for 32bit system,
1/3rd more for 64bit.

Please update the wiki page.
