### ISSUE TITLE
net/http: canceled requests with Timeout set always return a Timeout error

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#16094]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

`go version devel +9e8fa1e Fri Jun 17 15:18:39 2016 +0000 darwin/amd64`
1. What did you do?

Make a http.Client with a Timeout. Cancel the request. 

https://play.golang.org/p/v-QbAxdj-3
1. What did you expect to see?

If the cause was not a Client.Timeout, then the error should be left alone.

```
net/http: request canceled
```
1. What did you see instead?

The error is

```
net/http: request canceled (Client.Timeout exceeded while reading body)
```

---

This is because `reqWasCanceled` returns true whatever the reason for the cancelation is, be it a library user cancel or a Timeout. Then `cancelTimerBody.Read` uses that function to add the message.

The `(Client.Timeout exceeded while awaiting headers)` message is more likely to be correct (even if slightly racy), because it only adds the message if `!deadline.IsZero() && !time.Now().Before(deadline)`.

**Comment by FiloSottile** [comment]
Looking into it, this is not only the error message. The error is actually a net Timeout.

**Comment by bradfitz** [comment]
@FiloSottile, is this a regression from Go 1.6?

**Comment by FiloSottile** [comment]
Yep, it's a regression.

I'll address the points on the CL now, sorry for the delay, I've been offline for a bit.

**Comment by odeke-em** [comment]
I've updated @FiloSottile's CL https://golang.org/cl/24230 with https://go-review.googlesource.com/32478.

**Comment by KingRider** [comment]
https://github.com/golang/go/blob/7448eb4172bfc8f704b9ea39d77d0113a042b9dc/src/net/http/client.go#L301 is wrong! 

Check L303
https://go-review.googlesource.com/#/c/32478/1/src/net/http/client.go@303

Please is what correct?

**Comment by bradfitz** [comment]
@KingRider, we don't track comments on closed issues. Please file a new bug if you have a reproducible problem with the Go master branch.

**Comment by keitaj** [comment]
Where is `cancelTimerBody.Read` used?

**Comment by bradfitz** [comment]
@keitaj, we don't track comments on closed issues. Please file a new bug if you have a reproducible problem with the Go master branch.
