### ISSUE TITLE
go/build: .syso files can't be specified with .go files

### ISSUE THREAD

**Issue by kevinpostal** [golang/go#16090]
I am trying to build a windows golang executable with exe information. 

(https://github.com/josephspurrier/goversioninfo)

When using go build alone everything works as desired.

When I try to pass a specific go file to build the resource.syso is not included/added.

How would I go about passing the syso file to the go build command?

**Comment by mikioh** [comment]
Is your problem the same as #16050?

**Comment by kevinpostal** [comment]
I don't believe so. I am using go 1.5 

The exe is generated correctly with go build alone. Its only when I pass go files to the build command do I have issues.

**Comment by mikioh** [comment]
Then I think you need to describe the following:
```
1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

4. What did you expect to see?

5. What did you see instead?
```

**Comment by quentinmit** [comment]
@kevinpostal Can you please provide us with a sample .go and .syso file, and show us what happens when you try to run "go build"? What error message do you get?

**Comment by rsc** [comment]
Closing for lack of information.

**Comment by rsc** [comment]
It sounds like the answer is:

Naming .go files on the command line is a shorthand for making a package directory out of just those Go files. This is a convenience. If you need non-Go files to be in your package, then the solution is to put them in a directory.

**Comment by virtuald** [comment]
I've ran into the same issue, it appears that when you run 'go build' without naming .go files then it links the syso file (perhaps some autodiscovery?), and when you run go build and name each .go file, then it doesn't link the syso file. There is no error message reported, and the resulting binary still works (it just doesn't have the Windows resources in it).
