### ISSUE TITLE
x/crypto/ssh: ed25519 support for the agent

### ISSUE THREAD

**Issue by corny** [golang/go#16096]
The ssh agent does not support ed25519 yet. See also https://github.com/golang/go/issues/8581#issuecomment-226803187
@pmoody- might add the missing support soon.

**Comment by ianlancetaylor** [comment]
CC @agl @hanwen

**Comment by pmoody-** [comment]
alright, I've got a diff adding the functionality, now I just need to add some tests.

**Comment by pmoody-** [comment]
fyi: https://go-review.googlesource.com/#/c/24285/
