### ISSUE TITLE
x/exp/inotify: Watcher.paths leaks memory

### ISSUE THREAD

**Issue by krousey** [golang/go#16097]
`inotify.Watcher.RemoveWatch` cleans up the `Watcher.watches` map, but doesn't remove the entry from `Watcher.paths`.

1. What version of Go are you using (`go version`)?

go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

linux amd64

3. What did you do?

Added and removed files from an `inotify.Watcher`. 

https://play.golang.org/p/n95Yttt4Xi

4. What did you expect to see?

Memory usage not to continually increase.

5. What did you see instead?

Memory usage steadily increased.

**Comment by krousey** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/27456

**Comment by krousey** [comment]
I proposed a fix https://go-review.googlesource.com/#/c/24289/

**Comment by krousey** [comment]
@quentinmit This is my first attempt to contribute to the Go project. Am I missing a step to get a reviewer for the change? Or should I just wait longer?

**Comment by ianlancetaylor** [comment]
To be honest I'm not sure who is maintaining the exp/inotify project these days.

**Comment by ianlancetaylor** [comment]
I put some comments on the CL.  Thanks for pinging it.
