### ISSUE TITLE
cmd/compile: fast build mode/flag

### ISSUE THREAD

**Issue by kokizzu** [golang/go#16091]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.4.3
   1.7.0b1
2. What operating system and processor architecture are you using (`go env`)?
   amd64 darwin
3. What did you do?
   just normal daily edit-compile-debug.
   not an error, just an idea for faster compilation, for edit-compile-debug cycle (including restarting webserver), it would be nice to have `--fast-compile` mode even the compile binary not optimized is ok, as long it's fast to compile
4. What did you expect to see?
   not waiting too long
5. What did you see instead?
   for each cycle, 
   waited about 4 seconds in 1.4 on linux
   waited about 6 seconds in 1.4 on mac 
   waited about 8 seconds in 1.7b1 on mac
   this still too much..

**Comment by sergeylanzman** [comment]
set GOGC=false for go build => 20%-30% fast
set ssaEnabled flag false => maybe help for compile time(only 1.7)

**Comment by quentinmit** [comment]
/cc @randall77 @dr2chase 

I'm not sure there really is all that much we could do to trade off optimizations for speed.

**Comment by ianlancetaylor** [comment]
Use -gcflags=-N to turn off the optimizers.

I agree we need to keep making the compiler faster, but I don't think it's a good idea to encourage different compilation modes unnecessarily.

**Comment by ALTree** [comment]
`GOGC=off` to turn the GC off and `-gcflags=-N` to turn the optimizer off are two things that definitely help speeding up compilation.

Looks like the idea of a new `--fast-compilation` flag was rejected, so I'm closing this issue.
