### ISSUE TITLE
text/template: does not document how values are formatted

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#16105]
go version devel +3c6b668 Thu Jun 2 00:22:03 2016 +0000 linux/amd64

I may well have missed it, but text/template package doesn't seem to specify
anywhere how values are actually displayed. For example, by reading the
documentation, it's not clear whether a value's String method will be called
to produce text to display in the template.

**Comment by cespare** [comment]
I agree; the closest thing in the documentation currently is

> The default textual representation of the value of the pipeline is copied to the output.

The "default" it refers to is (AFAICT) the same "default format" that the fmt package documentation refers to. Perhaps the fix is simply to say that values are formatted as if using the `%v` verb.

/cc @robpike @adg
