### ISSUE TITLE
debug/pe: ImportedSymbols returns no symbols

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#16103]
Running this program:

```
package main

import (
    "debug/pe"
    "fmt"
    "os"
)

func main() {
    for _, v := range os.Args[1:] {
        f, err := pe.Open(v)
        if err != nil {
            fmt.Fprintf(os.Stderr, "can not create PE structure for %s: %v\n", v, err)
            continue
        }
        defer f.Close()

        libs, err := f.ImportedSymbols()
        if err != nil {
            fmt.Fprintf(os.Stderr, "can not get imported symbols: %v\n", err)
            continue
        }
        for _, v := range libs {
            fmt.Printf("%s\n", v)
        }
    }
}
```

with [PsService.zip](https://github.com/golang/go/files/318935/PsService.zip) file as argument, lists no imported dlls / functions. But it should:

```
$ objdump -x PsService.exe | sed '/The Import Tables/,$!d' | head
The Import Tables (interpreted .rdata section contents)
 vma:            Hint    Time      Forward  DLL       First
                 Table   Stamp     Chain    Name      Thunk
 00026aa4       00026e18 00000000 00000000 00026e7e 000202ac

        DLL Name: VERSION.dll
        vma:  Hint/Ord Member-Name Bound-To
        26e4e       0  GetFileVersionInfoA
        26e64       3  GetFileVersionInfoSizeA
        26e3c      13  VerQueryValueA
$
```

The reason for this is because debug/pe assumes that imported symbols live in section named ".idata", but it is not always true (as you can see from objdump output). We should use PE "The Data Directory" to determine location of imported info.

Alex

**Comment by mewmew** [comment]
I would be happy to prepare a CL for this, if you haven't started already @alexbrainman.

**Comment by alexbrainman** [comment]
> I would be happy to prepare a CL for this, if you haven't started already @alexbrainman.
>  👍 1

Please go ahead, if you like. I am fighting with symlinks at this moment :-).
Just a warning - I suspect for this CL we would have to introduce some new exported from debug/pe bits. go1.9 freeze starts soon, so we have very little time to get new exported bits right.

Alex

**Comment by mewmew** [comment]
Hi Alex,

Thanks for the heads up. I'll try to tackle it sometime next week. Good luck in your battle with the symlinks : )

Cheers /u

**Comment by bradfitz** [comment]
@mewmew, any update?

@alexbrainman, can you remilestone this to Go 1.10 if this isn't important for Go 1.9? You decide.

**Comment by mewmew** [comment]
> @mewmew, any update?

I have this mostly working in a [local PE parser](https://github.com/decomp/exp/blob/master/bin/pe/pe.go), which may be cleaned up and adapted for inclusion to the debug/pe package timed for the 1.10 release.

I will try to prepare a CL within the following month.

Cheers /u

**Comment by alexbrainman** [comment]
> @alexbrainman, can you remilestone this to Go 1.10 if this isn't important for Go 1.9?

You already remilestoned it yourself. Thank you, Brad.

Alex
