### ISSUE TITLE
x/net/http2: flaky TestTransportReqBodyAfterResponse_403

### ISSUE THREAD

**Issue by mikioh** [golang/go#16102]
See https://build.golang.org/log/e59465cf2e0b92444c0598c3a4d813353f3e53d9 and https://build.golang.org/log/ae3a78dd1d3ac52f57795918af38fb43cfe0aa59
```
--- FAIL: TestTransportReqBodyAfterResponse_403 (0.05s)
	transport_test.go:664: client: RoundTrip: http2: stream closed
FAIL
FAIL	golang.org/x/net/http2	13.922s
```

**Comment by bradfitz** [comment]
Not fixed:
https://build.golang.org/log/56e0561f9f6a740b75538692a1c3288f08949dd0

I have the real fix.
