### ISSUE TITLE
hash/crc32: use faster method for CRC32-C 

### ISSUE THREAD

**Issue by RaduBerinde** [golang/go#16107]
The hardware (SSE4.2) assisted CRC32-C implementation can be made faster (from my experience about 2.5 - 2.7 times faster if checksumming enough bytes e.g. 512+),

The gist of the idea is that (on recent Intel platforms at least) the CRC32 instruction takes three cycles but three of them can be pipelined in parallel if they don't depend on each other; so we can split the buffer into three, checksum the three pieces in "parallel" (interleaving the CRC32 instructions) and then combine the results using some tables.

This article goes into more depth: http://www.drdobbs.com/parallel/fast-parallelized-crc-computation-using/229401411

I can take a stab at implementing it at some point when I have some time of my hands, unless there are objections.

**Comment by ianlancetaylor** [comment]
If you can make it faster while producing the same results, by all means go for it.  Thanks.

**Comment by RaduBerinde** [comment]
Working on a decent initial version. Sneak peek:

```
CastagnoliCrc15B-4    597MB/s ± 0%    662MB/s ± 1%   +10.86%  (p=0.029 n=4+4)
CastagnoliCrc40B-4   1.74GB/s ± 0%   1.68GB/s ± 1%    -3.35%  (p=0.029 n=4+4)
CastagnoliCrc1KB-4   7.99GB/s ± 0%  14.14GB/s ± 0%   +76.89%  (p=0.029 n=4+4)
CastagnoliCrc4KB-4   8.84GB/s ± 0%  18.15GB/s ± 0%  +105.38%  (p=0.029 n=4+4)
CastagnoliCrc32KB-4  9.11GB/s ± 1%  19.40GB/s ± 0%  +112.94%  (p=0.029 n=4+4)
```
