### ISSUE TITLE
Timeout in test phase.

### ISSUE THREAD

**Issue by jucie** [golang/go#16106]
1. What version of Go are you using (`go version`)?
go version devel +f3d5478 Fri Jun 17 19:15:29 2016 +0000 windows/386

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=C:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0

3. What did you do?
>git clone https://github.com/golang/go.git
>cd go\src
>all

4. What did you expect to see?
A clean build & test.

5. What did you see instead?
...
ok      cmd/compile/internal/test       0.360s
ok      cmd/cover       14.877s
ok      cmd/doc 0.614s
ok      cmd/fix 0.372s
panic: test timed out after 6m0s

I tried twice:
[firsttry.txt](https://github.com/golang/go/files/321709/firsttry.txt)
[secondtry.txt](https://github.com/golang/go/files/321710/secondtry.txt)

The computer is an old and slow netbook:
![netbook](https://cloud.githubusercontent.com/assets/8865244/16170590/315b65e0-352e-11e6-9a15-0cc1cf40fd82.png)

Please note I have set CGO_ENABLED  to zero, to avoid C compiler installation issues.

**Comment by davecheney** [comment]
I'm sorry but I don't think there is much we can do here. If your machine is too slow to complete `all.bat` you can try increasing the timeout with something like `GO_TEST_TIMEOUT_SCALE=10`.

I'm going to close this issue as I don't think there is an issue that can be addressed here.

**Comment by jucie** [comment]
I was not aware of GO_TEST_TIMEOUT_SCALE. I changed it, as you suggested and now everything goes fine. Thanks, Dave.

**Comment by mikioh** [comment]
Just FYI: #10314

**Comment by jucie** [comment]
That's exactly the same situation. Thanks, Mikio.
