### ISSUE TITLE
cmd/compile: not compiled

### ISSUE THREAD

**Issue by indariums** [golang/go#16118]
Device - Synology DS115
RAM - 512Mb
Processor architecture - Marvell Armada-375 Board v7l( from proc/cpuinfo)
I downloaded from the desired site (https://go.googlesource.com/go/+/go1.4), the output is:

>
DS115>./make.bash
Building C bootstrap tool.
cmd/dist
Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
cmd/5a
cmd/5c
cmd/5g
runtime
<unknown line number>: internal compiler error: fault
go tool dist: FAILED: /opt/go/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main -+ /opt/go/src/runtime/alg.go /opt/go/src/runtime/arch_arm.go /opt/go/src/runtime/atomic_arm.go /opt/go/src/runtime/cgocall.go /opt/go/src/runtime/cgocallback.go /opt/go/src/runtime/chan.go /opt/go/src/runtime/compiler.go /opt/go/src/runtime/complex.go /opt/go/src/runtime/cpuprof.go /opt/go/src/runtime/debug.go /opt/go/src/runtime/env_posix.go /opt/go/src/runtime/error.go /opt/go/src/runtime/extern.go /opt/go/src/runtime/hashmap.go /opt/go/src/runtime/hashmap_fast.go /opt/go/src/runtime/iface.go /opt/go/src/runtime/lock_futex.go /opt/go/src/runtime/malloc.go /opt/go/src/runtime/mem.go /opt/go/src/runtime/mgc0.go /opt/go/src/runtime/mprof.go /opt/go/src/runtime/netpoll.go /opt/go/src/runtime/netpoll_epoll.go /opt/go/src/runtime/noasm_arm.go /opt/go/src/runtime/os_linux.go /opt/go/src/runtime/panic.go /opt/go/src/runtime/print1.go /opt/go/src/runtime/proc.go /opt/go/src/runtime/race0.go /opt/go/src/runtime/rdebug.go /opt/go/src/runtime/rune.go /opt/go/src/runtime/runtime.go /opt/go/src/runtime/select.go /opt/go/src/runtime/sema.go /opt/go/src/runtime/signal_unix.go /opt/go/src/runtime/sigpanic_unix.go /opt/go/src/runtime/sigqueue.go /opt/go/src/runtime/slice.go /opt/go/src/runtime/softfloat64.go /opt/go/src/runtime/sqrt.go /opt/go/src/runtime/stack.go /opt/go/src/runtime/string.go /opt/go/src/runtime/stubs.go /opt/go/src/runtime/symtab.go /opt/go/src/runtime/time.go /opt/go/src/runtime/traceback.go /opt/go/src/runtime/typekind.go /opt/go/src/runtime/vlrt.go /opt/go/src/runtime/zgoarch_arm.go /opt/go/src/runtime/zgoos_linux.go /opt/go/src/runtime/zruntime_defs_linux_arm.go /opt/go/src/runtime/zversion.go

Why  /opt/go/src if if you should be /root/go/src

I think that this platform should not be compiled at all, only the cross-compilation.
However, it does not work either.
go duild runtime: linux/arm must be bootstrapped using make.bash
Ok, GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 ./make.bash --no-clean
No errors...

**Comment by OneOfOne** [comment]
1.4 is no longer supported, you should try go 1.6 or even 1.7 beta (or git), your best option is:

1. On your *current** system (not your Synology), install go 1.6/1.7 and make sure it's working (for example run `go env`).
2. `cd "$(go env GOROOT)/src"`
3. `env GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 GOROOT_BOOTSTRAP="$(go env GOROOT)" ./bootstrap.bash`
4. Move `../../go-linux-arm-bootstrap` to your target board and you can use that directly.

**Comment by indariums** [comment]
thx, all ok
