### ISSUE TITLE
path/filepath: behavior of Clean is not explicitly mentioned in its doc, which is surprising and easy to miss

### ISSUE THREAD

**Issue by shurcooL** [golang/go#16111]
_(Usually an issue is when a function does something which is not documented, or different than documented. This is not the case here, but I still believe there is an issue that can and should be resolved, i.e., improvement is possible.)_

One of my favorite properties of Go is that many things are explicit and there's little magic. When you want to learn what a func in standard library does, often just reading its doc string will tell you everything you need to know, without having to look at the implementation details. This is very nice and follows Principle of Least Surprise.

I was trying to confirm the behavior of `filepath.Join`, so I began by reading its doc:

```
// Join joins any number of path elements into a single path, adding
// a Separator if necessary. The result is Cleaned, in particular
// all empty strings are ignored.
// On Windows, the result is a UNC path if and only if the first path
// element is a UNC path.
func Join(elem ...string) string
```

It says that the result is Cleaned, so I read the doc for `Clean`:

```
// Clean returns the shortest path name equivalent to path
// by purely lexical processing.  It applies the following rules
// iteratively until no further processing can be done:
//
//	1. Replace multiple Separator elements with a single one.
//	2. Eliminate each . path name element (the current directory).
//	3. Eliminate each inner .. path name element (the parent directory)
//	   along with the non-.. element that precedes it.
//	4. Eliminate .. elements that begin a rooted path:
//	   that is, replace "/.." by "/" at the beginning of a path,
//	   assuming Separator is '/'.
//
// The returned path ends in a slash only if it represents a root directory,
// such as "/" on Unix or `C:\` on Windows.
//
// If the result of this process is an empty string, Clean
// returns the string ".".
//
// See also Rob Pike, ``Lexical File Names in Plan 9 or
// Getting Dot-Dot Right,''
// http://plan9.bell-labs.com/sys/doc/lexnames.html
func Clean(path string) string
```

With that, I am confident that I understand the behavior of `filepath.Join` because I've read its documentation.

However, as I have learned today (by chance), my understanding of `filepath.Join`, `filepath.Clean` was incorrect because I overlooked a **very important, behavior altering** paragraph in the package documentation (which is used to describe this package). Read the second paragraph:

```
// Package filepath implements utility routines for manipulating filename paths
// in a way compatible with the target operating system-defined file paths.
//
// Functions in this package replace any occurrences of the slash ('/') character
// with os.PathSeparator when returning paths unless otherwise specified.
package filepath
```

It turns out that `Clean` replaces any occurrences of the slash ('/') character with `os.PathSeparator` when returning path. So does `Join` since it calls `Clean`.

I believe this is the first time I have ever encountered a standard library package where a part of the behavior (which is not the expected behavior for this package) is specified/overridden by package docs.

If I'm not mistaken, I believe it'd be better to change documentation to document `Clean`s behavior explicitly, and change the package documentation to summarize behavior rather than be the only place that specifies it.

### Exaggerated, contrived example

If I may provide an exaggerated, contrived example of how this current situation makes me feel, it would be like seeing a function in std lib like this:

```Go
// Add returns sum of two numbers.
func Add(a, b int) int
```

Then I run `Add(1, 2)` and get -3 instead of 3. Instead of a bug, imagine it turns out that:

```Go
// Package math has some utilities for dealing with numbers.
//
// Functions in this package return the negation of the expected result, unless
// otherwise specified.
package math
```

This issue is the same as https://github.com/golang/go/issues/10122. However, that issue was resolved a year ago, and I hadn't noticed that it was resolved because I primarily read the function documentation when determining behavior of a function. I read the package documentation when I want to get a better overview of the purpose of package, but it's not where I expect to find unexpected behaviors specified.

### Proposed improvement

I propose improving `path/filepath` by changing `Clean` documentation to be explicit about its behavior, and changing the package summary to be more descriptive of the package, rather than being the canonical place where behavior of individual functions is altered or specified.

E.g., something like this:

![image](https://cloud.githubusercontent.com/assets/1924134/16174123/88bc2c02-356a-11e6-83f4-369710843395.png)

/cc @hyangah since you originally ran into this issue as well (#10122), and worked on the original fix to the doc.

**Comment by shurcooL** [comment]
This proposal appears to have two 👍 s and no pushback (at this time), so I suppose I'll go ahead and create a CL, which can be reviewed and considered for merging.

FWIW, I've also run a lightweight informal twitter poll, and [it suggested](https://twitter.com/shurcooL/status/744303350875725824) that the majority of people currently mis-interpret the functionality of `Clean` regarding slash (`/`) character replacement. 29% of people got it right, and 43% incorrectly thought that `Clean` does not replace slash characters. The rest didn't know/didn't vote.

Created CL https://golang.org/cl/24467.

**Comment by as** [comment]
I disagree with this change. The package claims that all "/" are replaced with Seperator unless otherwise specified. Some functions document the negative behavior (stating they don't replace "/" with Seperator). This change documents positive behavior for Clean(). But is Clean the only one that needs to re-affirm this? As a user, I can no longer reason about the behavior of other functions in the package that have neither positive nor negative documentation. 

In my opinion, It would be better to properly document the negative behavior for all functions and fullfill the "unless otherwise specified" contract in the documentation. Then the positive redundant documentation can be removed.

**Comment by shurcooL** [comment]
@as, thanks for feedback. As I understand, you're referring to the current CL (aka, the proposed solution), and not the issue filed here.

My initial plan for the CL to resolve this issue was to simply add the phrase `Any occurrences of the slash ('/') character are replaced with Separator when returning path.` to _every_ method except the two (Split and SplitList) that don't do it.

When I looked at the other methods, it seemed to me that they already specify that "path is cleaned" before being returned. So as long as the user understands that `Clean` replaces the slashes, they can know exactly what the other functions perform.

The package document still mentions that _most functions_ do the replacement, which makes it harder to miss.

However, now that I took another closer look at the other methods, it seems only `Join` and `Dir` explicitly say that the path is Cleaned before being returned:

> Dir returns all but the last element of path, typically the path's directory. After dropping the final element, the path is Cleaned and trailing slashes are removed.

> Join joins any number of path elements into a single path, adding a Separator if necessary. The result is Cleaned, in particular all empty strings are ignored.

So I think the CL needs to be updated to make it clear (explicitly) for all other methods that slashes will indeed be replaced.

**Comment by adg** [comment]
I would be happy if the documentation redundantly mentioned all the cases where slashes *are* replaced. I'd rather know what the functions do rather than what they don't.

**Comment by shurcooL** [comment]
@adg I agree with that, it'd be much better.

That was my original plan. But I found it hard to verify/confirm that all methods except `Split` and `SplitList` actually do the slash replacement.

There are some methods which don't return a path at all, so they can't do it. For example, `Match` returns a `bool` and `error`.

Here's a list of all function in `path/filepath`. Which ones do the replacement?

-	[ ] `func Abs(path string) (string, error)`
-	[ ] `func Base(path string) string`
-	[x] `func Clean(path string) string`
-	[ ] `func Dir(path string) string`
-	[ ] `func EvalSymlinks(path string) (string, error)`
-	[ ] `func Ext(path string) string`
-	[ ] `func FromSlash(path string) string`
-	[ ] `func Glob(pattern string) (matches []string, err error)`
-	[ ] `func HasPrefix(p, prefix string) bool`
-	[ ] `func IsAbs(path string) bool`
-	[x] `func Join(elem ...string) string`
-	[ ] `func Match(pattern, name string) (matched bool, err error)`
-	[ ] `func Rel(basepath, targpath string) (string, error)`
-	[ ] `func Split(path string) (dir, file string)`
-	[ ] `func SplitList(path string) []string`
-	[ ] `func ToSlash(path string) string`
-	[ ] `func VolumeName(path string) string`
-	[ ] `func Walk(root string, walkFn WalkFunc) error`

**Comment by as** [comment]
@shurcooL
I agree that saying "path is Cleaned" is a better solution. 

As for enumerating the behavior, I had a similar idea but no Windows system:
https://play.golang.org/p/PBk9FfGZmA

The source suggests filepath.FromSlash() does the replacement, and only filepath.Clean() calls it from within the package. 

I'm more interested in the functions that do not perform the replacement, since they contradict the current documentation.

**Comment by adg** [comment]
Well I think the current docs are flat out wrong. The majority of the functions in `path/filepath` that return paths do not do the replacement, as far as I can tell. I haven't looked too deeply into it, though.

I suspect we'll end up with a short list of functions that do the replacement, and we can document those explicitly and remove the clause from the package doc.

**Comment by shurcooL** [comment]
That sounds good.

By the way, I'll say this now and update the commit message. When debugging/looking into the history of this issue, I found that what happened was:

1. In 2011 or so, a CL that was meant to be a Windows-only bug fix inadvertently (it was not documented) introduced the behavior of `filepath.Clean` replacing `/` with `filepath.Separator`.
2. It went unnoticed and undocumented for 4 years until 2015, when @hyangah ran into the issue and opened #10122. It was resolved by documenting the actual behavior rather than trying to undo the unintended behavior change... because no one noticed for 4 years.
3. One year later, I ran into this and didn't see the documentation fix from https://go-review.googlesource.com/#/c/7310/ until Hana pointed me at it. When I did find the docs, I wasn't happy with the and opened this issue.

So, that kinda explains why we're in this situation right now, where the behavior is odd and documentation is not very accurate or precise.

**Comment by as** [comment]
After looking at the implementation, I see that filepath does not currently enforce what is Clean and what is merely converted from slash to backslash across operating systems. We should enumerate which functions truly Clean and which merely apply FromSlash (or call library functions that emulate it).

On Windows:
filepath.Abs -> abs (path_windows.go:108) -> syscall.Fullpath 

So the path is not Cleaned on Windows, and it isn't even passed into FromSlash (are they replaced by the call to syscall.FullPath by Windows itself?). 

On UNIX, the path is explicitly Cleaned. Either via 
Abs -> unixAbs -> Clean
Abs -> unixAbs -> Join -> Clean

**Comment by shurcooL** [comment]
Ok, I've written the following Go program to try and figure out the current implementation situation. Hopefully this is enough data to go on.

https://play.golang.org/p/zV4Mib1EqY

I ran it on a Windows machine (with Go 1.6; I'll try installing 1.7beta2 tomorrow and ensure it produces same output), and got:

```
$ go version
go version go1.6 windows/386

$ go run filepath.go
filepath.Abs("forward/slash/foo/bar") = (string)("c:\\Documents and Settings\\Dmitri\\Desktop\\forward\\slash\\foo\\bar"),
        (interface{})(nil)
filepath.Base("forward/slash/foo/bar") = (string)("bar")
filepath.Clean("forward/slash/foo/bar") = (string)("forward\\slash\\foo\\bar")
filepath.Dir("forward/slash/foo/bar") = (string)("forward\\slash\\foo")
filepath.EvalSymlinks("C:/Go/src/path/filepath") = (string)("C:\\Go\\src\\path\\filepath"),
        (interface{})(nil)
filepath.Ext("forward/slash.foo/bar") = (string)("")
filepath.Ext(`forward/slash.foo\bar`) = (string)("")
filepath.Ext("forward/slash.foo_bar") = (string)(".foo_bar")
filepath.FromSlash("forward/slash/foo/bar") = (string)("forward\\slash\\foo\\bar")
filepath.Glob("C:/Go/src/*/template") = ([]string)([]string{
        (string)("C:\\Go\\src\\html\\template"),
        (string)("C:\\Go\\src\\text\\template"),
}),
        (interface{})(nil)
filepath.IsAbs(`forward/slash/foo/bar`) = (bool)(false)
filepath.IsAbs(`/forward/slash/foo/bar`) = (bool)(false)
filepath.IsAbs(`\forward/slash/foo/bar`) = (bool)(false)
filepath.IsAbs(`C:/forward/slash/foo/bar`) = (bool)(true)
filepath.IsAbs(`C:\forward/slash/foo/bar`) = (bool)(true)
filepath.Join("forward/slash/foo/bar") = (string)("forward\\slash\\foo\\bar")
filepath.Match("C:/Go/src/*/filepath", `C:/Go/src/path/filepath`) = (bool)(true),
        (interface{})(nil)
filepath.Match(`C:\Go\src\*\filepath`, `C:\Go\src\path\filepath`) = (bool)(true),
        (interface{})(nil)
filepath.Rel("C:/Go/src", "C:/Go/src/path/filepath") = (string)("path\\filepath"),
        (interface{})(nil)
filepath.Split("forward/slash/foo/bar") = (string)("forward/slash/foo/"),
        (string)("bar")
filepath.SplitList("forward/slash/foo/bar") = ([]string)([]string{
        (string)("forward/slash/foo/bar"),
})
filepath.ToSlash("forward/slash/foo/bar") = (string)("forward/slash/foo/bar")
filepath.VolumeName(`forward/slash/foo/bar`) = (string)("")
filepath.VolumeName(`/forward/slash/foo/bar`) = (string)("")
filepath.VolumeName(`\forward/slash/foo/bar`) = (string)("")
filepath.VolumeName(`C:/forward/slash/foo/bar`) = (string)("C:")
filepath.VolumeName(`C:\forward/slash/foo/bar`) = (string)("C:")
path = (string)("C:/Go/src/path")
path = (string)("C:\\Go\\src\\path\\example_test.go")
path = (string)("C:\\Go\\src\\path\\filepath")
path = (string)("C:\\Go\\src\\path\\filepath\\example_unix_test.go")
path = (string)("C:\\Go\\src\\path\\filepath\\export_test.go")
path = (string)("C:\\Go\\src\\path\\filepath\\match.go")
path = (string)("C:\\Go\\src\\path\\filepath\\match_test.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path_plan9.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path_test.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path_unix.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path_windows.go")
path = (string)("C:\\Go\\src\\path\\filepath\\path_windows_test.go")
path = (string)("C:\\Go\\src\\path\\filepath\\symlink.go")
path = (string)("C:\\Go\\src\\path\\filepath\\symlink_unix.go")
path = (string)("C:\\Go\\src\\path\\filepath\\symlink_windows.go")
path = (string)("C:\\Go\\src\\path\\match.go")
path = (string)("C:\\Go\\src\\path\\match_test.go")
path = (string)("C:\\Go\\src\\path\\path.go")
path = (string)("C:\\Go\\src\\path\\path_test.go")
filepath.Walk("C:/Go/src/path", walkFn) = (interface{})(nil)
```

**Comment by hyangah** [comment]
@shurcooL thanks for doing this. 
The filepath.Walk's behavior is annoying  - the first path is fed without any slash replacement.
What about filepath.Rel("C:\\Go\\src", "C:/Go/src/path/filepath")?

If we decide to stay with the current (unintended) behavior, I hope to convert those as a test too to ensure no regression, and to ensure documentation when a new function is introduced.
