### ISSUE TITLE
cmd/cgo: panic instead of error for insufficient arguments to C function

### ISSUE THREAD

**Issue by qeedquan** [golang/go#16116]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go 1.7 beta 2

2. What operating system and processor architecture are you using (`go env`)?
Linux amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/4NVQYgjnhx

4. What did you expect to see?
A compile error

5. What did you see instead?

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5876a0, 0xc4200141d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*Package).rewriteCall(0xc42001c5a0, 0xc42000a240, 0xc420014b10, 0xc420090300)
	/usr/local/go/src/cmd/cgo/gcc.go:628 +0x1645
main.(*Package).rewriteCalls(0xc42001c5a0, 0xc42000a240)
	/usr/local/go/src/cmd/cgo/gcc.go:593 +0x167
main.(*Package).Translate(0xc42001c5a0, 0xc42000a240)
	/usr/local/go/src/cmd/cgo/gcc.go:170 +0x112
main.main()
	/usr/local/go/src/cmd/cgo/main.go:290 +0x726
```

It seems that Issue 13423 isnt fully fixed because the check can break early in the presence of void pointers as shown in the code example so it can still get out of bounds

**Comment by quentinmit** [comment]
I'm going to tentatively put this in Go 1.7, but realistically it will probably get pushed to 1.8.
