### ISSUE TITLE
cmd/compile: SSA runtime performance regression on rotate function

### ISSUE THREAD

**Issue by ALTree** [golang/go#16119]
```
$ gotip version
go version devel +691c5c1 Sun Jun 19 05:18:09 2016 +0000 linux/amd64
```

Code:

```go
package foo

import "testing"

//go:noinline
func Rotate(x uint64, n uint) uint64 {
	return (x << n) | (x >> uint(64-n))
}

var sink uint64

func BenchmarkRotate(b *testing.B) {
	for n := 0; n < b.N; n++ {
		sink = Rotate(0xff88ff88cc77cc77, 32)
	}
}
```
(note that the `//go:noinline` directive is necessary, because tip is able to fold the `Rotate` call into a load of the result).

`go1.6.2` vs `tip`:

```
name      old time/op  new time/op  delta
Rotate-4  3.00ns ± 1%  4.36ns ± 0%  +45.09%  (p=0.000 n=10+9)
```

The problem with the generated code looks similar to the one in #16061 (SSA does two stack spilling and the legacy compiler does not), but this time we're not using instructions that requires values to be in specific registers. I'm not sure whether this can be considered the same as #16061 or not.

**Comment by randall77** [comment]
This does seem to be the same as #16061.  The instruction that requires a value in a specific register is the shift (shift amounts must be in CX).
