### ISSUE TITLE
Incorrect pointers while iteration through list with RANGE keyword 

### ISSUE THREAD

**Issue by sev3ryn** [golang/go#16149]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.5 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\slisovskyi\code\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/Y2Sx72JHUZ

Iteration through list with RANGE and sending object pointer through channel - produces incorrect pointers.
Iteration by element index don't produce such bug.
I suggest it is garbage collector issue

4. What did you expect to see?

------PTR {Name:A}
------PTR {Name:B}
------PTR {Name:C}
------PTR {Name:D}

5. What did you see instead?

------PTR {Name:B}
------PTR {Name:B}
------PTR {Name:D}
------PTR {Name:D}

**Comment by ALTree** [comment]
Not a bug, you're using channels and `range` incorrectly. See the explanation at [Unexpected behavior when dealing with channels](https://groups.google.com/d/topic/golang-nuts/gzpqjtp5SOQ/discussion).

**Comment by martisch** [comment]
looks to me as working as intended.

for _, member := range team.memberList {

the member here is a local variable. When sending a pointer to that variable it will print whatever is in that variable at that moment not what was in the variable when the pointer was taken.

If you add a delay after sending the pointer you will see that output becomes different. 		
time.Sleep(100 * time.Millisecond)

With the delay the range loop usually wont be faster than the routine that selects and prints from the channel. This is only for demonstration of the effect not to be meant as solution to a problem.

**Comment by rajender** [comment]
This working correctly. 

for _, member := range team.memberList { 

will create member variable once, not for every iteration.

https://play.golang.org/p/m44DU-orkq

**Comment by sev3ryn** [comment]
Thanks guys, lot clearer right now. Sorry for raising this issue
