### ISSUE TITLE
gob decode nil value occur EOF error

### ISSUE THREAD

**Issue by linlexing** [golang/go#16147]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\skydrive\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
https://play.golang.org/p/faypK8uobF
```go
package main

import (
	"bytes"
	"encoding/gob"
	"log"
)

type T struct {
	A int
}

func init() {
	gob.Register(map[string]interface{}{})
	gob.Register(new(T))
}
func main() {
	bys := bytes.NewBuffer(nil)
	gob.NewEncoder(bys).Encode(map[string]interface{}{
		"v": (*T)(nil),
	})
	out := map[string]interface{}{}
	if err := gob.NewDecoder(bys).Decode(&out); err != nil {
		log.Panic(err)
	}
	return
}
```

4. What did you expect to see?
no error

5. What did you see instead?
panic: EOF

**Comment by Limdi** [comment]
Encode returns an `error`, try checking that before decoding.
```
gob: cannot encode nil pointer of type *main.T inside interface
```
https://play.golang.org/p/SXh-aHivuZ

**Comment by linlexing** [comment]
I got a very detailed answer .

http://stackoverflow.com/questions/37962021/gob-attempting-to-decode-nil-value-results-in-eof-error
