### ISSUE TITLE
encoding/xml: Unmarshal ignores error return from Decoder.unmarshalAttr

### ISSUE THREAD

**Issue by EricLagergren** [golang/go#16158]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6.2

2. What operating system and processor architecture are you using (`go env`)?

GOOS=GNU/Linux
GOARCH=amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/wAByp2MpkB

4. What did you expect to see?

One of two things, in order of preference:

~~1.) Since `C` is one byte long I'd expect to see `foo.B` set to 0x43 (and also error out if the attribute is longer than one byte long.)~~
2.) An error since `C` is an invalid number and `Decoder.unmarshalAttr` calls `strconv.ParseUint` yet decides to ignore the return value of `copyValue`.

5. What did you see instead?

Nothing -- it doesn't touch `foo.B` and `foo.B` remains 0x0.

**Comment by EricLagergren** [comment]
The offending commit (if it's in any way relevant to why the return value of `copyValue` is ignored): https://github.com/golang/go/commit/84b0842a59b8bf8e890861f7859869fb73d8681c

**Comment by ianlancetaylor** [comment]
The fix is to change `Decoder.unmarshalAttr` to not ignore the error return of `copyValue`.  The obvious fix causes one of the testsuite tests to fail.

This has worked this way since 1.0.3, so leaving for 1.8.

**Comment by EricLagergren** [comment]
Is this coveted under the Go 1.0 promise?

**Comment by ianlancetaylor** [comment]
This kind of thing is not strictly covered by the Go 1 promise.  We are permitted to fix bugs.  However, if fixing this bug causes packages to fail, we might decide that it's not worth fixing.

**Comment by EricLagergren** [comment]
Okay, I'll go ahead with the CL then. I noticed the failed test too—is that
in the scope of this issue or not?

**Comment by ianlancetaylor** [comment]
I'm not quite sure what you are asking.  Certainly all the tests must pass when the CL is committed.

**Comment by EricLagergren** [comment]
Yes, of course.

The failing test could be indicative of another bug in the xml package, or
it could just be a small issue with the test.

My question was about the *former* and whether it'd require a separate
issue or not.
