### ISSUE TITLE
x/tools/cmd/present error on Darwin (works on Linux)

### ISSUE THREAD

**Issue by rjammala** [golang/go#16151]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +1f44643 Wed Jun 22 00:12:55 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rajanikanth.j/gocode"
GORACE=""
GOROOT="/Users/rajanikanth.j/go"
GOTOOLDIR="/Users/rajanikanth.j/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4f/4vg7m4ys42vg8r2q7pxhqdw8jrldwy/T/go-build066027774=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Tried to run a simple presentation using the x/tools/cmd/present

4. What did you expect to see?
That I am able to access the presentation without errors.

5. What did you see instead?

$ present 
2016/06/22 11:56:24 Open your web browser and visit http://127.0.0.1:3999
2016/06/22 11:56:30 template: slides.tmpl:10:27: executing "root" at <.NotesEnabled>: can't evaluate field NotesEnabled in type struct { *present.Doc; Template *template.Template; PlayEnabled bool }
2016/06/22 11:56:30 http: multiple response.WriteHeader calls

**Comment by adg** [comment]
Run `go get -u golang.org/x/tools/cmd/present`

**Comment by rjammala** [comment]
Thanks. Works now.
