### ISSUE TITLE
crypto/x509: ParsePKIXPublicKey parses invalid RSA public keys without errors

### ISSUE THREAD

**Issue by szank** [golang/go#16166]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6.2 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mgalkowski/work/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/qMQ1aqX5Ox

4. What did you expect to see?
Last line should say: 
`Error parsing incorrect RSA public key`

5. What did you see instead?
`INCORRECT public key have been parsed`

According to 
RFC3279 https://tools.ietf.org/html/rfc3279#section-2.3.1 : 
```
The rsaEncryption OID is intended to be used in the algorithm field
of a value of type AlgorithmIdentifier.  The parameters field MUST
have ASN.1 type NULL for this algorithm identifier.
```
Could you please fix it ?

**Comment by szank** [comment]
I am happy to fix it myself if I find some time this weekend.

**Comment by ianlancetaylor** [comment]
CC @agl
