### ISSUE TITLE
x/net/http2: server should use weights and dependencies when scheduling frame writes

### ISSUE THREAD

**Issue by tombergan** [golang/go#16168]
As of version 51, Chrome has started using HTTP/2 dependencies to express an ordering for its requests. I'm not sure about other browsers, but I'm sure they will start using dependencies soon if they're not already. I have direct evidence that this improves pageload performance. Unfortunately my example is not easy to make public, but the gist is:

1. Chrome downloads HTML for a page and makes a bunch of H2 requests for subresources (CSS, JS, etc).
2. Chrome needs to evaluate these in a specific order, so it forms a linear sequence of dependencies that are communicated directly to the server. The server is expected to deliver subresources in this order.
3. Eventually, Chrome runs some JS code that imports two other CSS files. These CSS files are needed immediately to start rendering the page -- they are more important than any requests currently in flight. Chrome expresses this importance using stream dependencies.

Go's HTTP/2 server currently does not respect stream dependencies. In fact, frame writes are scheduled in a mostly random order, even though the priority tree is being maintained:
https://github.com/golang/net/blob/master/http2/server.go#L457
https://github.com/golang/net/blob/master/http2/writesched.go#L133

This causes problems in both step 2 (where resources are delivered in a random rather than sequential order) and step 3 (where the immediacy of the new requests is not respected).

At first glance, fixing this seems easy. The difficulty comes from the following scenario: Suppose the server needs to schedule two streams, A and B, where A is the stream parent of B. Suppose the server has data for B _right now_. Should it eagerly write the available data for B, or should it wait for data on A? This is complicated by the fact that the kernel's TCP send buffer is usually larger than the TCP congestion window, meaning the server can buffer multiple RTTs worth of data for B, then slowly flush that buffer even when data for A has become available. This problem has been seen in practice. There's a long (but interesting) discussion here:
https://insouciant.org/tech/prioritization-only-works-when-theres-pending-data-to-prioritize/

I'm going to do some reading about what other servers do in this scenario, and experiment with a prototype implementation, then report back. We may want to do a simple implementation first that ignores the above problem, then come up with something more complex later. I need this feature for some experiments that I'm doing, so I'll end up implementing a fix of some sort unless someone else has code ready-to-go. Feel free to assign this bug to me.

Note: A related problem is that Go's H2 client currently has no API for expressing stream dependencies to the server, however this bug is entirely about server-side scheduling.

/cc @bradfitz

**Comment by bradfitz** [comment]
Did you like my TODO in the linked `writesched.go` file? :)

```go
// TODO: find the best queue
```

**Comment by tombergan** [comment]
I did see that :)

Did you intend for those to actually be queues? AFAICT, the only way for a per-stream queue to have more than one queued frame is if you write a response headers frame that doesn't have any headers. This seems pretty rare. In all other cases, ResponseWriter.Write waits for the current frame to be serialized onto the wire before writing the next frame.

**Comment by bradfitz** [comment]
When an http.Handler exits without having called Flush, aren't there a HEADERS & 0+ DATA frames in the queue?

I admit I wrote the write scheduler before I used it, but I thought the queues were used.

**Comment by tombergan** [comment]
IIUC, frames don't get added to the queue until writeFrameFromHandler is called. When this happens for a data frame, the handler always waits:
https://github.com/golang/net/blob/master/http2/server.go#L773

When this happens for a header frame, the handler waits if the headers are not empty:
https://github.com/golang/net/blob/master/http2/server.go#L1718

There's no wait for 100-continue frames, but those are rare as well:
https://github.com/golang/net/blob/master/http2/server.go#L1741

**Comment by bradfitz** [comment]
Is it a problem that it's a queue? Seems like a distraction from the main issue. The queues are still being used, even if not much (currently?).

**Comment by tombergan** [comment]
It's not a problem. I was just wondering if you had a larger plan for buffering data frames that was never implemented?

**Comment by bradfitz** [comment]
Yeah, I think there's more to be done there. The http.Handler goroutine could track its flow control state more and return from `ResponseWriter.Write` more quickly. It's pretty conservative at the moment. Very little work has gone into performance. I think I'll be looking at that during Go 1.8.

**Comment by tombergan** [comment]
Possibly relevant for the following reason: I have a prototype running where the scheduler respects priorities. However, there's a race. Suppose we have a priority tree A -> B -> C. A should be served first. But A's frames won't be scheduled until A makes a Write call. The handlers all run concurrently, so it's possible that B or C will happen to make a Write call first, in which case their frames get written first because there's nothing (yet) queued for A. The scheduler doesn't know if it should wait for A (how long might it have to wait?), so it eagerly writes what it has. I have cases where this is a significant performance degradation relative to optimal delivery (10% worse).

One way to make the race less likely is to buffer multiple frames per stream. You still get the race on the first Write call, but at least after that call, A has a chance to generate more frames while its first frame is being written. (I haven't actually evaluated this idea.)

Simon Pelchat and I are also kicking around the following idea: suppose we knew the connection's bandwidth. (We can estimate this from RTT and CWND from the kernel's tcp_info.) We could use this to pace the scheduler -- if the frame size is X, then we write one frame ever X/bw seconds. As long as A can make Write calls faster than X/bw, it should always win the race. If it can't, we don't want to wait because we'd be leaving bandwidth on the floor. (Lot's of potential problems with this idea, obviously.)

**Comment by bradfitz** [comment]
> The scheduler doesn't know if it should wait for A (how long might it have to wait?), so it eagerly writes what it has. I have cases where this is a significant performance degradation relative to optimal delivery (10% worse).

I think that's fine. I don't think the server should be sending nothing while waiting for something better when it already has something to send.

**Comment by tombergan** [comment]
The point was that sometimes you get better performance by waiting, especially when you only need to wait a few milliseconds at most. (How often does this happen? I don't know yet. But it does happen sometimes. In any case, we should do the simple thing first.)

**Comment by bradfitz** [comment]
> The point was that sometimes you get better performance by waiting,

Better? You never said by which metric. Certainly not bandwidth. I could believe you increased the time-to-first-render for Chrome or something, but you almost certainly delayed the total load time.

I'll entertain the idea of sleeping and more complexity once we do better than random.

**Comment by tombergan** [comment]
Sorry, I meant better for SpeedIndex in the browser. (And if you're only waiting a few ms, it's unlikely you'll do better on bandwidth, unless your connection is really fast.)
