### ISSUE TITLE
important!!!! report a compile bug!!!!

### ISSUE THREAD

**Issue by imiskolee** [golang/go#16160]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/MiskoLee/developer/go_workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
3. What did you do? 

report a compile bug!

reply:  https://play.golang.org/p/PBv6tC5ftA

4. What did you expect to see?

5. What did you see instead?

**Comment by mwhudson** [comment]
This does not seem to be a bug report.

**Comment by mikioh** [comment]
@imiskolee,

You need to have a look at https://golang.org/doc/faq#nil_error.

**Comment by imiskolee** [comment]
tanks
