### ISSUE TITLE
cmd/compile: PPC64 SSA support

### ISSUE THREAD

**Issue by laboger** [golang/go#16175]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
master ssa branch

2. What operating system and processor architecture are you using (`go env`)?
ppc64le Ubuntu 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Initial implementation of SSA for GOARCH ppc64le, possibly ppc64

4. What did you expect to see?
Correct implementation of ssa on ppc64le as a basis for future ongoing optimizations.

5. What did you see instead?
Work in progress....

**Comment by laboger** [comment]
Keith answered my question first so I went with what he recommended.  I don't think he explicitly said to open an issue but that's what I've done in the past so I did and I like to have a place to ask questions.

I submitted what I have so far.  It builds and all tests pass when running ./all.bash.  I can build hello.go using SSATEST=yes without error but it doesn't run! (nothing gets printed).

 @dr2chase 

I think there was a question at one time if it should be both ppc64le & ppc64 but ppc64le is more important so if that is done first, that is fine.  Unless the plan is to move all GOARCHes to SSA?

https://go-review.googlesource.com/24453

**Comment by dr2chase** [comment]
Plan is to move all GOARCHes to SSA.  Not quite sure how we're organizing PPC64le vs PPC64be, but agreed le is more important.  I'm looking at the CL, I'm inclined to LGTM it permissively because it's a great start.  Still working on my own PPCle access (can log in, have no home dir, might complicate use of tool chain).

**Comment by laboger** [comment]
@drchase OK to close this?  Or are we still waiting/deciding on PPC64 BE?

**Comment by dr2chase** [comment]
Seems closeable to me, not sure what the exact PPC64 BE build+test story is (haven't paid close attention to the builders lately).

**Comment by bradfitz** [comment]
@dr2chase, we just got the ppc64 BE builders yesterday. I'll try to set them up now.

**Comment by bradfitz** [comment]
Builders are now online.

**Comment by bradfitz** [comment]
With @ianlancetaylor's fix to #17361, we have our first "ok" on the dashboard. Closing this.
