### ISSUE TITLE
cmd/pprof: redundant TMPDIRs

### ISSUE THREAD

**Issue by dsnet** [golang/go#16178]
Using `go1.7beta2`

The pprof tool has at least two TMPDIRs:
- One that it can take from [$PPROF_TMPDIR, and defaults to $HOME/pprof](https://github.com/golang/go/blob/204b6f48c5107d3132033324fd492ca0253568dc/src/cmd/internal/pprof/driver/driver.go#L699-L705). As far as I can tell, this directory is only ever used when pprof is [operating remotely](https://github.com/golang/go/blob/204b6f48c5107d3132033324fd492ca0253568dc/src/cmd/internal/pprof/driver/driver.go#L404-L410). This pprof directory is never deleted after it is used. So if `pprof` is used locally, it keeps generating empty pprof directories in a user $HOME directory and never cleans them up.
- The other temporary directory, it [generates on the fly](https://github.com/golang/go/blob/e9407ae514df7d18e162ce03ebd530fe21aed16d/src/cmd/internal/pprof/commands/commands.go#L192-L203) when it needs to invoke some type of visualizer for HTML, SVG, GIF, etc... pprof [now properly cleans](https://github.com/golang/go/commit/e9407ae514df7d18e162ce03ebd530fe21aed16d) this directory up.

Why have two different variations of TMPDIRs? Why doesn't pprof clean itself up?

**Comment by rsc** [comment]
I believe the idea behind $HOME/pprof was to save profiles for future reference. If everything written there is being deleted by pprof when it exits, that kind of defeats the point and I agree that either we should just not use that directory or else we should not delete those profiles from it.

/cc @rauls5382

**Comment by rauls5382** [comment]
Yes, the idea behind $HOME/pprof is to save profiles retrieved over http and save them for future reference. pprof does not delete them so that you can examine them in the future.

The other temp directory is used to store actual temporary files, for example to communicate with dot or other tools. This directory is cleaned up when pprof exits.

I think this is working as intended.

**Comment by dsnet** [comment]
> Yes, the idea behind $HOME/pprof is to save profiles retrieved over http and save them for future reference. 

If that's the case, I would argue that $HOME/pprof *only* be generated when pprof is invoked when retrieving the profile over HTTP, rather is all uses of pprof.

**Comment by rauls5382** [comment]
I agree. I'll clean this up on the upstream pprof.
