### ISSUE TITLE
doc: GoTalk Link to slides broken

### ISSUE THREAD

**Issue by IzakMarais** [golang/go#16173]
On the [GoTalks](https://github.com/golang/go/wiki/GoTalks) page the [link](http://wh3rd.net/practical-go) to the slides for the _Practical Go Programming_ talk is broken. I get _404 Page not Found_.

**Comment by ianlancetaylor** [comment]
@adg I would fix this myself but I don't know where the slides are.

**Comment by adg** [comment]
I also don't know where the slides are.

**Comment by dgryski** [comment]
The text of the slides is in the repository for the talk: https://github.com/nf/goto/tree/master/talk

They're just not hosted anywhere anymore.  Could they be moved to talks.golang.org, or is that specifically for Present-based slide decks?

**Comment by adg** [comment]
@dgryski thanks. I put the slides back in their original location.
