### ISSUE TITLE
database/sql: support connection wait timeout when out of free connections

### ISSUE THREAD

**Issue by NeoCN** [golang/go#16174]
1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
set the db.maxOpen to limit connections count.
and try to do db query when connection pool is out of  free connections

4. What did you expect to see?
expect database/sql support connection wait timeout setting, the connection wait timeout specifies how long an db request waits to obtain a connection if there are no longer any free connections in the pool. 
with this setting, we can make the db request fail fast when out of  free connections

5. What did you see instead?
according the related code block https://github.com/golang/go/blob/master/src/database/sql/sql.go#L800-L817, the db request will wait, until get an connection to return, when returned, the application may have been waiting for 10s, or longer 10min.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by h12w** [comment]
It seems to be the same as https://github.com/golang/go/issues/13327

**Comment by redfoxli** [comment]
Support connection wait timeout is a good idea.
In our online environment, that's what I did.

Another way, it can return when out of free connections, like the treatment method of redis pool.
https://github.com/garyburd/redigo/blob/master/redis/pool.go#L124

**Comment by kardianos** [comment]
This should be closed now that https://github.com/golang/go/issues/15123 is completed.

**Comment by bradfitz** [comment]
Done.
