### ISSUE TITLE
No Orig_rax and Rax field in PtraceRegs struct on arm

### ISSUE THREAD

**Issue by vanloswang** [golang/go#16181]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/arm64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
Just compile docker-slim, then it reports as follow:
../../vendor/src/github.com/cloudimmunity/docker-slim/sensor/monitors/ptrace/monitor.go:91: regs.Orig_rax undefined (type syscall.PtraceRegs has no field or method Orig_rax)
../../vendor/src/github.com/cloudimmunity/docker-slim/sensor/monitors/ptrace/monitor.go:99: regs.Rax undefined (type syscall.PtraceRegs has no field or method Rax)

4. What did you expect to see?
No such an error reports.

5. What did you see instead?

CC https://github.com/docker-slim/docker-slim/issues/25

**Comment by bradfitz** [comment]
PtraceRegs differs by architecture. The syscall package is not portable, by definition. This is a problem in docker-slim, not Go.

**Comment by vanloswang** [comment]
@bradfitz Need to shield these differences to upper applications.

**Comment by ianlancetaylor** [comment]
@vanloswang Go permits people to write system-specific code.  There is no way to shield a program that chooses to write such code.
