### ISSUE TITLE
Instead of dreaming about Generics, why not improve the existing system of types?

### ISSUE THREAD

**Issue by mezoni** [golang/go#16186]
Below is my thoughts about that problem/
The term `desugaring` means a valid source code in the Go language of the current version.
The names of built-in functions are `fictitious` and are only for the understanding of the operation of the algorithm.

```go
var a [6]int
var s []int
var m map[string]int
```

```go
// [6] - Array with length 6
// int - Element type
var a [6]int
```

```go
// [] - Array without length (slice)
// int - Element type
var s []int
```

```go
// map - Type specifier `map`
// [string] - Key type `string`
// [int] - Element type `int`
var m map[string]int
```

```go
// Foo - Type specifier `Foo`
// [string, int] - Arguments types `string` and `int`
var foo Foo[string, int]
```

Assume we want implement alternative to `slice` and use it similar to use the slice:

```go
var slice []int
var alternative Slice[int]
```

```go
// Syntactic sugar
// This type cannot be instantiated w/o type arguments
type Slice[E] struct {
  slice []E
  some  bool
}
```

```go
// Desugaring
type Slice struct {
  slice []interface{}
  some  bool
}

```

```go
// Syntactic sugar
// The `XYZ` is a name (identifier) of the type parameter
// for the method `NewSlice` (it also has an index '0')
func NewSlice[XYZ](length int) *Slice[XYZ] {
  // Syntactic sugar
  s := &Slice[XYZ]{}

  // Syntactic sugar
  s.slice = make([]XYZ, length)

  s.some = some
 return s
}
```

```go
// Desugaring
func NewSlice(typeArgs []*_type, length int) *Slice {

  // s := &Slice[XYZ]{}
  __typ0 = make_parametrized_type((*_type)(Slice), typeArgs[0])
  s := newobject(__typ0)

  // s.slice = make([]XYZ, length)
  __typ1 = make_slice_type(typeArgs[0]) // typeArgs[0] is `elem type`
  s.slice = make_slice_by_elem_type(__typ1, length)

  s.some = some
  return s
}
```

The '[]' is not valid identifier but must be allowed in the method declaration name.

```go
// Syntactic sugar
// The `E` is a name of the first type parameter of `Slice`
// and available in the method of the receiver of the type `Slice`
func (s *Slice) [](index int) E {
  return s.slice[index]  
}
```

```go
// Desugaring
// This is a method of the parametrized type `Slice` and it must
// be able to return the value of any type.
// So we always using `interface{}` to return value of any type
// This is often called as the `boxing` value
//
// This means that the compiler should after a return silently
// unbox a value
func (s *Slice) [](index int) interface{} {
  return s.slice[index] // Value was `boxed` automatically
}
```

That is, after the call:

```go
var data Slice[int]
// ...
// Syntactic sugar
i := data[5]
```

```go
// Desugaring
// Type of the 'i' was obtained from the above source code
var i int
// Pseudo code for call method '[]'
__temp0 := data.[](5)
unbox(__temp0, &i)
```

And also, as example:

```go
// Syntactic sugar
func (s *Slice) []=(index int, val E) {
  // This is only for the code complexity
  var v E
  v = val
  s.slice[index] = v
}
```

```go
// Desugaring
func (s *Slice) []=(index int, val interface{}) {
  // Begin of the `type safety block`

  // Obtain the receiver type
  // Eg. Slice with typeArgs is [string], that is Slice[string]
  __typ0 := elem_type_of_receiver_ptr(s)

  // Validate every method argument with the receiver type arguemnts
  // In our case this is a paramater `val E`
  validate_argument_by_type_arg(val, __typ0.typeArgs[0])

  // End of the `type safety block`

  var v interface{}
  v = val
  s.slice[index] = v
}
```

And other similar procedures...

P.S.

If this is impossible then why?
- There are no resources
- There is no need
- It is a heresy

I don't think the the following procedures are very bad in the reusable parameterized methods:
- unbox
- elem_type_of_receiver_ptr
- validate_argument_by_type_arg
- make_slice_type
- make_slice_by_elem_type
- make_parametrized_type
- etc

Also what can be wrong with the following type notation?

```go
var foo Foo[string, int, bool]
```

Sorry, for the mistakes in the examples that can found.

**Comment by ianlancetaylor** [comment]
I don't think it's useful to discuss this on the issue tracker, unless you want to turn it into a formal proposal.  I recommend taking this to the golang-dev mailing list.

Have you read the proposals linked from issue #15292?

When and how is something like your `NewSlice` function compiled?  Is `elem_type_of_receiver_ptr` a compile time or run time operation?

I'm going to close this.  If you want to turn it into a proposal, please comment, but a proposal needs to be complete and needs to describe implementation details.  See the proposals linked from #15292 for minimal examples of what a complete proposal requires.

**Comment by mezoni** [comment]
@ianlancetaylor 

Can I propose the solution as the worked example?
That is proposal as a working source code example with comments (in current Go language).
With the describing all possible nuances.

**Comment by ianlancetaylor** [comment]
This is not yet a useful proposal because it does not describe the implementation.  Do you plan to add that?  Can you add your proposal to the existing #15292 instead?
