### ISSUE TITLE
x/mobile/cmd/gobind: Go's int is always exported as int (32bit) in Objective-C

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#16182]
Whether the architecture is 32bit or 64bit in Objective-C side, Go's int is exported as Objective-C's int, which is 32bit.

**Comment by hyangah** [comment]
Any objection to change to long?
On the other hand, Go's int type is mapped to long for java (android), which causes a different issue #11421. Fortunately, for iOS, it seems 'long' matches Go's int type. Best practice is to avoid int type though.
