### ISSUE TITLE
cmd/compile: a global lambda with a function named glob with lambda in it is an error

### ISSUE THREAD

**Issue by xfix** [golang/go#16193]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

  go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

  GOARCH="amd64"
  GOBIN=""
  GOEXE=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOOS="linux"
  GOPATH=""
  GORACE=""
  GOROOT="/usr/lib/go-1.6"
  GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
  GO15VENDOREXPERIMENT="1"
  CC="gcc"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
  CXX="g++"
  CGO_ENABLED="1"

3. What did you do?
  If possible, provide a recipe for reproducing the error.
  A complete runnable program is good.
  A link on play.golang.org is best.

  Defined a global anonymous function and a function called `glob` that uses an anonymous function internally.

  https://play.golang.org/p/ZofsJuBk7s

4. What did you expect to see?

  No error.

5. What did you see instead?

  ```
  # command-line-arguments
  ./glob.go:6: glob.func1 redeclared in this block
          previous declaration at ./glob.go:11
  ```

**Comment by kostya-sh** [comment]
Happens with Go tip too
