### ISSUE TITLE
unicode: Update to version 9.0.0

### ISSUE THREAD

**Issue by nightlyone** [golang/go#16191]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"
(rest redacted)

3. What did you do?

$ go doc unicode.Version

4. What did you expect to see?

const Version = "9.0.0"
    Version is the Unicode edition from which the tables are derived.

5. What did you see instead?

const Version = "8.0.0"
    Version is the Unicode edition from which the tables are derived.

**Comment by nightlyone** [comment]
I didn't see it tracked somewhere so I opened an issue. Please close, if I did overlook an already existing issue.

Useful links: 
* Blogpost: http://blog.unicode.org/2016/06/announcing-unicode-standard-version-90.html
* Changes and migration guidance: http://unicode.org/versions/Unicode9.0.0/

**Comment by Thomasdezeeuw** [comment]
Is it correct that the issue and the commit state version 9, while `api/except.txt` states version 8.0.0? (see 
https://github.com/golang/go/blob/a2a4db7375204c22898559d3b96a748c6df96294/api/except.txt#L332).

**Comment by mpvl** [comment]
@Thomasdezeeuw: yes.  api/except.txt tells the API checker that it is okay to no longer have the Version constant be 8.0.0.  api/go1.7.txt says it is now 9.0.0.

(See https://github.com/golang/go/blob/a2a4db7375204c22898559d3b96a748c6df96294/api/go1.7.txt)

**Comment by Thomasdezeeuw** [comment]
Ok, just checking.
