### ISSUE TITLE
[question] compile a source for mips

### ISSUE THREAD

**Issue by MrDini123** [golang/go#16210]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`
go version go1.2.1 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

4. What did you expect to see?

5. What did you see instead?

-------

Hi!

I have a mipsel router (mips32) with TomatoUSB and I have a 4g dongle, which uses hi-link. And I found [this](https://github.com/knq/hilink) source, So I want to compile it using cross-compiler on my ubuntu PC.

But when I try to get it, it says:

```
# env GOOS=linux GOARCH=mips go get https://github.com/knq/hilink
2016/06/29 16:59:45 unsupported GOARCH mips
```

So how Can I compile it?

Thanks!

**Comment by ianlancetaylor** [comment]
The Go project does not use the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions .  Thanks.

Go 1.2 does not support MIPS.  MIPS support was added in Go 1.6.  And even in 1.6 there is no mips 32-bit support, only GOARCH=mips64.

**Comment by MrDini123** [comment]
Okay, but I have a gccgo (from opewrt-go) So with it I also Can't compile the code to mips32?

_The Go project does not use the issue tracker to ask questions._

Sorry.

**Comment by ianlancetaylor** [comment]
Please use a forum.

To use gccgo, use the -compiler=gccgo option and set the compiler to a mips32 cross-compiler.

**Comment by bradfitz** [comment]
Dup of #14637 also.
