### ISSUE TITLE
x/mobile/cmd/gomobile: remove gomobile stripped NDK

### ISSUE THREAD

**Issue by hyangah** [golang/go#16211]
gomobile stripped NDKs created by release.go are still smaller than the android full NDK.
But 
- it adds maintenance overhead. 
- go starts supporting more architectures so stripped NDK is no longer tiny.
- some users want to choose android api level different from the default the stripped NDK contains.

I propose to remove the need of stripped NDK.
Now gomobile can reuse cached NDKs, so I don't expect the tool to require users to download it for every init command.

Unclear issue is 
what to do about open-AL tar file gomobile init also downloads?

@crawshaw @eliasnaur @rakyll

**Comment by eliasnaur** [comment]
Is it too naive to attempt to build the openal libraries during gomobile init?

**Comment by hyangah** [comment]
that's what i am thinking as well but according to what's in cmd/gomobile/release.go,
building open-al requires 'cmake'. I don't know how easy to set it up.

**Comment by dskinner** [comment]
Another case, I talked to someone at gophercon that customizes ndk to compliment their android fork. As @rakyll mentions on #14618 I agree this should be settable as an env var.
