### ISSUE TITLE
x/tools/cmd/present: slides.js not running on safari

### ISSUE THREAD

**Issue by glorieux** [golang/go#16216]
1. What version of Go are you using (`go version`)?
go version go1.5 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/glorieux/Workspace/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Install present. 
Create a really simple slide presentation.
Run `present`
Open Safari.

4. What did you expect to see?
I expected the slides to display on Safari.

5. What did you see instead?
It did not display and raised the following error on the console: `SyntaxError: Unexpected identifier 'i'. Expected either 'in' or 'of' in enumeration syntax.
(anonymous function)slides.js:540`

6. Fix
Since Safari is not yet supporting ES6 `let` statements they need to be replaced by `var` ones.

Looks like the bug was introduced by https://go-review.googlesource.com/21488

**Comment by binary132** [comment]
I confirm this is affecting me and other users of my hosted slides.
