### ISSUE TITLE
Weird Behavior on Single Computer

### ISSUE THREAD

**Issue by orware** [golang/go#16217]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.2 windows/386

2. What operating system and processor architecture are you using (`go env`)?

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Gocode
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

So I was developing and testing out essentially my first "real" go application here:
https://code.imperial.edu/online-services/go-user-client-info

Over the weekend I was working from home on my laptop (which is running Windows 10 64-bit and the same version of Go) and everything was working fine with the page being served when running the executable generated after running "go build main.go".

By fine, I mean that I was able to see the CSS being served and presented for the HTML page correctly.

Contrast this when running the same code from my work PC (which is the machine I generated the 'go env' info above). Essentially, I wanted to continue the work I had started over the weekend. So after updating my local copy of the repository and running "go build main.go" I started it up to test.

Here on my work PC it does not serve the CSS files correctly (they get interpreted as text/plain files in Chrome, Internet Explorer or Firefox so the browser doesn't appear to be the culprit).

I've also tested taking the same folder containing all of the project files I'm trying from my work PC and copying them to a different machine here in our environment...when I start it up on the other machine it works correctly (so this rules out there being an issue with the 32-bit version of the EXE, which was one potential thought). The other PC I tried it on was a 64-bit machine though, so I need to try it from another 32-bit machine as well just to be doubly-sure that's not the potential issue.

If I try and go to the URLs directly I can access the files when the server is running...but I'm just not sure why it's showing them incorrectly as text/plain in one case, and showing them correctly as text/css when running it on other machines.

4. What did you expect to see?

I expected the CSS files to get served correctly on any machine I run the code on since that's one of the benefits of Go :-).

5. What did you see instead?

Instead, currently on my local PC it's not serving the CSS files correctly, even though the same exact code was used to generate the executable running in two different locations (and it works when running it from one machine, but not the other).

I'll see if I can run a few more tests and report back what I learn.

I'm not sure if the issue is a newbie mistake that I made in the code since I am just starting out, but it definitely feels weird the way things are currently behaving.

**Comment by bradfitz** [comment]
Since no bug has been identified here, it seems like a forum would be a more appropriate venue for discussion. See https://golang.org/wiki/Questions
