### ISSUE TITLE
Can not customize http request header "Host" when sending http request.

### ISSUE THREAD

**Issue by cmingxu** [golang/go#16223]
```
request  := http.NewRequest()
request.Header.Add("Host", "foobar")
```

Code above doesn't change http host header

**Comment by ericmdantas** [comment]
Try using `request.Host = "foobar"`.

Relevant: https://github.com/golang/go/issues/7682.
Playground: https://play.golang.org/p/DEFLb7_WRJ.

**Comment by odeke-em** [comment]
@cmingxu building off your snippet to produce a runnable example, one can definitely change the header at least on Go1.6.2 and on tip. Please see https://play.golang.org/p/m2j_uLvVaX
```go
package main

import (
	"log"
	"net/http"
	"runtime"
)

func main() {
	request, _ := http.NewRequest("POST", "https://golang.org", nil)
	newHost := "foobar"
	request.Header.Add("Host", newHost)

	gotHost := request.Header.Get("Host")
	if gotHost != newHost {
		log.Fatalf("gotHost=%q wantHost=%q; GoVersion=%q", gotHost, newHost, runtime.Version())
	}
}
```
If that errors out then that's a regression, I've tested it on tip 
```shell
$ go version devel +e0c8af0 Thu Jun 30 00:25:29 2016 +0000 darwin/amd641
```
and also on play.golang.org which is currently running Go1.6.2 without any failures.

**Comment by bradfitz** [comment]
This is documented on Request.Host: https://golang.org/pkg/net/http/#Request
