### ISSUE TITLE
net/http, net/http/httptest: locks being copied

### ISSUE THREAD

**Issue by josharian** [golang/go#16228]
From cmd/vet:

```
net/http/h2_bundle.go:5133: assignment copies lock value to *cfg: crypto/tls.Config contains sync.Once contains sync.Mutex
net/http/httptest/server.go:119: assignment copies lock value to *s.TLS: crypto/tls.Config contains sync.Once contains sync.Mutex
```

These seem like legitimate complaints.

It seems like tls.Config could use a Copy method, but probably not for Go 1.7.

cc @bradfitz @ianlancetaylor

**Comment by odeke-em** [comment]
Related to https://github.com/golang/go/issues/15177?

**Comment by josharian** [comment]
Yes, probably. It's not obvious to me from the immediate context why these are ok, though.

If they are ok, they're yet more (new?) false positives...in which case, #16227 is related.

cc @valyala

**Comment by valyala** [comment]
Both cases look like buggy, since they overwrite already existing mutex inside `tls.Config` with a new one.

**Comment by bradfitz** [comment]
d24f446 did the first half, and https://go-review.googlesource.com/28344 is the http2 part, which will be bundled in to std before Go 1.8. Closing.
