### ISSUE TITLE
database/sql/driver: support slices?

### ISSUE THREAD

**Issue by snadrus** [golang/go#16235]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.7
2. What operating system and processor architecture are you using (`go env`)?
   All
3. What did you do?
   
   db := ...connect to mysql db
   cursor, err := db.Query("SELECT \* FROM user WHERE firstName IN (?)",  
       []string{"Bob", "Matt", "Sam"})
   
   if err != nil {       ////// Errored
    fmt.Println(err)
    return
   }
   .....
4. What did you expect to see? 
   Comparing to PHP, I expected the following query's result:
     SELECT \* FROM user WHERE firstName IN ('Bob', 'Matt', 'Sam')
5. What did you see instead?
   sql: converting Exec argument #0's type: unsupported type []int, a slice

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by kardianos** [comment]
Related to https://github.com/golang/go/issues/13567

**Comment by bradfitz** [comment]
Which database(s) support this at at the wire level? Where you send SQL with a single placeholder and an array type of values comes later?

**Comment by kardianos** [comment]
Postgresql is the main one I'm aware of, as it has native array types. MS SQL server can also support custom types that can included table valued types.

**Comment by bhcleek** [comment]
@kardianos Postgres and SQL Server (assuming the array is a custom table-valued type) would each treat that slice/array as a single scalar value. In the example given, `firstName` would have to be the array of names, not _one_ of the names in the array. Postgres' array type, however, would allow `ANY` to match, assuming that the value was provided as an array (e.g.  `db.Query("SELECT * FROM user WHERE firstName = ANY (?)",
pg.Array([]string{"Bob", "Matt", "Sam"})`).

**Comment by kardianos** [comment]
@snadrus I think this is actually fixed. go1.9 now supports custom import types so it is now up to drivers to implement. Can you confirm?
