### ISSUE TITLE
gomobile init fails rename on windows

### ISSUE THREAD

**Issue by Triangle345** [golang/go#16233]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
WIndows 10 64 bit

After grabbing gomobile as per wiki, I ran gomobile init.  Seemed to freeze but noticed that after I pressed enter, i recved this message:

PS C:\cygwin64\home\peterpan\Projects\GoProjects\src> ../bin/gomobile init
C:\cygwin64\home\peterpan\Projects\GoProjects\bin\gomobile.exe: rename C:\cygwin64\home\peterpan\Projects\GoProjects\pkg
\gomobile\work-307124643\android-ndk-r12\toolchains\llvm\prebuilt\windows-x86_64\bin\clang C:\cygwin64\home\peterpan\Projects\GoProjects\pkg\gomobile\android-ndk-r12\llvm\bin\clang: The system cannot find the file specified.

I have cygwin installed but I was not using cygwin, only windows powershell

I tried several times, even wiping my entire src, pkg and bin folders with the same results.

**Comment by JeffMangan** [comment]
I am having a similar problem. I am using windows 10 pro 64x and go version go1.5.3 windows/amd64

I ran this and this ran ok: go get golang.org/x/mobile/cmd/gomobile

but always this when trying to run gomobile init

C:\GoPath>gomobile init
gomobile: rename C:\GoPath\pkg\gomobile\work-200728631\android-ndk-r12\toolchains\llvm\prebuilt\windows-x86_64\bin\clang C:\GoPath\pkg\gomobile\android-ndk-r12\llvm\bin\clang: The system cannot find the file specified.

C:\GoPath>gomobile init
gomobile: rename C:\GoPath\pkg\gomobile\work-339924407\android-ndk-r12\toolchains\llvm\prebuilt\windows-x86_64\bin\clang C:\GoPath\pkg\gomobile\android-ndk-r12\llvm\bin\clang: The system cannot find the file specified.

C:\GoPath>gomobile init
gomobile: rename C:\GoPath\pkg\gomobile\work-941100635\android-ndk-r12\toolchains\llvm\prebuilt\windows-x86_64\bin\clang C:\GoPath\pkg\gomobile\android-ndk-r12\llvm\bin\clang: The system cannot find the file specified.

**Comment by JeffMangan** [comment]
C:\GoPath>
C:\GoPath>gomobile build -target=android golang.org/x/mobile/example/basic
gomobile: toolchain partially installed, run `gomobile init`

C:\GoPath>gomobile init
gomobile: rename C:\GoPath\pkg\gomobile\work-250709683\android-ndk-r12\toolchains\llvm\prebuilt\windows-x86_64\bin\clang C:\GoPath\pkg\gomobile\android-ndk-r12\llvm\bin\clang: The system cannot find the file specified.

C:\GoPath>

**Comment by alexbrainman** [comment]
Does https://go-review.googlesource.com/#/c/24720/ fixes your problem?

Alex

CC @eliasnaur

**Comment by DmitriyMV** [comment]
Applied proposed fix, and now it results in different error

```
mv $WORK\go\importer.a C:\dmitriym\Coding\Go\pkg\gomobile\pkg_android_arm\go\importer.a
rm -r -f "$WORK"
gomobile: go install -p=8 -gcflags=-shared -ldflags=-shared -pkgdir=C:\dmitriym\Coding\Go\pkg\gomobile/pkg_android_arm -v -x std failed: exit status 2
```

**Comment by eliasnaur** [comment]
I've updated the fix, and verified it works on a Windows 10 installation. Please try again.

**Comment by DmitriyMV** [comment]
Yeah, sorry - my bad. Works fine now.
