### ISSUE TITLE
unicode, x/text: unit tests fail on Go1.7

### ISSUE THREAD

**Issue by dsnet** [golang/go#16234]
A recent change a2a4db7375204c22898559d3b96a748c6df96294 causes the following tests to fail:
* `golang.org/x/text/cases`
* `golang.org/x/text/secure/precis`

This is using golang/txt@4440cd4f4c2ea31e1872e00de675a86d0c19006c.

/cc @mpvl

**Comment by mpvl** [comment]
Should be fixed now. Will check in the upgrade to Unicode 9.0.0 for x/text soon after verifying the reverse issue does not exist.

**Comment by quentinmit** [comment]
See also #11811
