### ISSUE TITLE
HTTP redirect to the same host does not reuse the connection

### ISSUE THREAD

**Issue by jeffallen** [golang/go#16238]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

$ go version
go version devel +dcc42c7 Tue May 24 16:13:44 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jra"
GORACE=""
GOROOT="/Users/jra/go"
GOTOOLDIR="/Users/jra/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?

https://play.golang.org/p/Dm_HQj_Zbr

4. What did you expect to see?

Only two connections, one to :80 and one to :443.

5. What did you see instead?

Two connections to :80 and one to :443. It seems like during a redirect the existing connection that told us to redirect is not available for reuse for following the next URL. Why not?

**Comment by jeffallen** [comment]
Sorry, I debugged this further and I now see that the two calls to http.(* Transport)getIdleConn are for different keys, |http|www.golang.org:80 and |http|golang.org:80.

Makes sense, though now I'm wondering why the key is not the IP address.

**Comment by bradfitz** [comment]
> Makes sense, though now I'm wondering why the key is not the IP address.

Frontend load balancers can mux on the hostname and send you to different backends which can only deal with your first Host from then on.

HTTP/2 tries to permit this more explicitly and has guidance around it which would let us do it (see http://httpwg.org/specs/rfc7540.html#rfc.section.9.1.1) but it remains to be seen how it's implemented by servers in practice.

There's a TODO in the `x/net/http2/client_conn_pool.go` code:

```
        // TODO: add support for sharing conns based on cert names                                                                                                                           
        // (e.g. share conn for googleapis.com and appspot.com)                                                                                                                              
```

Looks like you were using HTTP/1.x though.
