### ISSUE TITLE
cmd/trace: low_resolution_timer warning

### ISSUE THREAD

**Issue by benburkert** [golang/go#16247]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version go1.7beta2 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/benburkert"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7beta2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7beta2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jl/n78jzg3j6nb8nzbn1vvpg9xc0000gn/T/go-build951352621=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

build `./fibtrace` from https://play.golang.org/p/tWpeEL4jse

```
$ go build -o fibtrace fibtrace.go
$ ./fibtrace
$ go tool trace .fibtrace fib.trace
```

Then browse to the "View trace" page (/trace).

4. What did you expect to see?

The trace viewer displayed without a warning.

5. What did you see instead?

The trace viewer with a `Import Warning: low_resolution_timer: Trace time is low
resolution, trace may be unusable.` warning.

![trace-warning](https://cloud.githubusercontent.com/assets/77/16530074/0851cd0e-3f7b-11e6-99b5-761c04b3062d.png)

**Comment by ianlancetaylor** [comment]
CC @dvyukov

**Comment by dvyukov** [comment]
It's not harmful. Just ignore it.
If somebody enjoys Javascript, he can dive into layers and layers of Javascript abstractions in Catapult and fix it.

**Comment by benburkert** [comment]
ok, thanks @dvyukov.

**Comment by bradfitz** [comment]
I'm going to reopen this bug. I spent time trying to find a machine with good enough timers to make that go away, but apparently the warning is always there?

This is not a good user experience.

**Comment by ianlancetaylor** [comment]
The warning has supposedly been removed from new versions of chrome, as of June.

https://codereview.chromium.org/2016863004

**Comment by cespare** [comment]
@ianlancetaylor so perhaps we simply need to re-copy the upstream sources? (The trace viewer bundled with the go tool is separate from that built into Chrome.)

**Comment by ianlancetaylor** [comment]
Oh, I didn't realize we had our own copy of the HTML.  I guess we could make a new copy, or just clobber the warning message in misc/trace/trace_viewer_lean.html.  It's easy to find by searching for "Trace time is low resolution" in that file.

**Comment by rsc** [comment]
Not sure why this is still open. We decided the warning was not real, and it's been removed. Closing. /cc @bradfitz
