### ISSUE TITLE
build: DragonFly builder is missing

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16245]
The DragonFly BSD builder is absent from https://build.golang.org

Did it die?

Does it not yet run on AWS on GCE or some cloud?

/cc @fupjack @mikioh

**Comment by fupjack** [comment]
No DragonFly on AWS/GCE.  My builder's hardware appears to have up and died - I am getting power lights on the main board but not much else.  I'll see what I can cobble together in the next 24 hours.

**Comment by tdfbsd** [comment]
Hi Brad, I'm taking over the gobuilder for Dragonfly and I've got it back up and running now

**Comment by mikioh** [comment]
@tdfbsd,

@tdfbsd,

Thanks. Well, which version of DragonFly BSD kernel are you running? We now observe the following test failure:
```
--- FAIL: TestGetfsstat (0.00s)
	syscall_bsd_test.go:31: an empty Statfs_t struct was returned
FAIL
```
I don't see the failure on 4.4.x, so I guess that it may be a side effect of hammer2 improvement work: http://lists.dragonflybsd.org/pipermail/commits/2016-June/541618.html.

**Comment by tdfbsd** [comment]
It can't be related to that because it's hammer2 specific and I'm not running hammer2, plus the version of DFBSD I'm using doesn't include those changes. If you can tell me specifically what that test is doing, I may be able to determine what's going on.

**Comment by tdfbsd** [comment]
I'm running 4.5 (the master branch), but I haven't updated in a while.

**Comment by mikioh** [comment]
You can check the status of buildbots at https://build.golang.org; e.g., https://build.golang.org/log/4128a364804b078e16a6c5a7e3432a2fb2119ebe.

**Comment by mikioh** [comment]
> what that test is doing

Looks like TestGetfsstat in syscall/syscall_bsd_test.go just calls getfsstat and tests the returned statfs whether it's empty or not.

**Comment by tdfbsd** [comment]
After some digging, I'm almost convinced that there is nothing wrong with DragonFly or Go, but rather something about the way I've mounted fllesystems on this machine. I'm going to see if I can get another machine going for gobuilder while I work this out.

**Comment by mikioh** [comment]
@tdfbsd,

Thanks, the column of dragonfly looks okay, closing.
