### ISSUE TITLE
Why doesn't golang build on many different archs running debian?

### ISSUE THREAD

**Issue by mrphs** [golang/go#16248]
1. What version of Go are you using (`go version`)?
2:1.6.1-2

2. What operating system and processor architecture are you using (`go env`)?
Debian - multiple archs

From Debian build page (https://buildd.debian.org/status/package.php?p=golang&suite=sid) it seems the maintainer has not included many archs in golang package. This results in packages written in go being broken or not available on any of this archs. 

A good example of that is [obfs4proxy](https://buildd.debian.org/status/package.php?p=obfs4proxy&suite=sid)

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

The upcoming Go 1.7 includes some new ports. See https://tip.golang.org/doc/go1.7#ports
