### ISSUE TITLE
Add option to gofmt and goimports to use spaces instead of tabs

### ISSUE THREAD

**Issue by pmalek** [golang/go#16256]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.2 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/monkey/.gvm/pkgsets/go1.6.2/global"
GORACE=""
GOROOT="/home/monkey/.gvm/gos/go1.6.2"
GOTOOLDIR="/home/monkey/.gvm/gos/go1.6.2/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

I have (I presume many people do as well) `goimport` running on each save of my `.go` files in vim.
Normally I use spaces in all my projects but after using `goimport` or `gofmt` I receive my files tabified. 

It would be handy if it was possible to run `goimports` or `gofmt` with flags like `--usetab=true` or something similar which would allow the alternate behavior of using spaces/tabs.

I believe it's fairly easy to implement in e.g. `goimports` - https://github.com/golang/tools/blob/master/cmd/goimports/goimports.go

Here is a connected issue in [vim-go project](https://github.com/fatih/vim-go)  https://github.com/fatih/vim-go/issues/5

**Comment by dominikh** [comment]
The point of gofmt is to have a single style that everybody uses. That includes the choice of using tabs over spaces. It doesn't have to be your – or anyone's – favourite style; just the style that is used by everyone.

gofmt used to have a flag to use spaces, but that flag was removed for precisely that reason. The output of the current gofmt is what your code should look like, no ifs or buts.

**Comment by pmalek** [comment]
Ah.. I have forgotten about this one. You're right.

**Comment by daggilli** [comment]
"The output of the current gofmt is what your code should look like, no ifs or buts."

My code **should** look exactly the way **I** want it. I don't want tabs. I want spaces. My boss wants spaces. My company wants spaces. There are no unbroken go formatting tools I can find.

**Comment by bradfitz** [comment]
You can write your own `gofmt` replacement and use it within your company if you never want to share code with the wider community (the Go ecosystem expects gofmt'd code). It'd be around 100 lines of code:

https://github.com/golang/go/blob/master/src/go/format/format.go

I advise you not to.
