### ISSUE TITLE
time: the time.After channel does not close when reusing it 

### ISSUE THREAD

**Issue by blackbeans** [golang/go#16259]
i want use the same  channel of time.After for  waiting some response timeout.
but when i reuse the channel to read  ,it blocks the current goroutine.

Now ,i use another way to solve the problem.

	latch := make(chan time.Time, 1)
	t := time.AfterFunc(timeout, func() {
		close(latch)
	})

	defer t.Stop()
	tch := (<-chan time.Time)(latch)

	//wating for response
	for g, f := range self.futures {
		resp, err := f.Get(tch)
        }

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand.  Can you provide a complete self-contained example that shows the bug?

**Comment by blackbeans** [comment]
code like this:

package main
import "time"
import "fmt"

func main() {
	ch := time.After(10 * time.Second)
	<-ch
	fmt.Println("timeout")
	<-ch
	fmt.Println("unreachable")
}

"ch" should be close when timeout has been happen .

**Comment by adg** [comment]
That's not how the `time.After` function works. It doesn't close the channel. The docs say:

```
After waits for the duration to elapse and then sends the current time on the returned channel. 
```

and that's what it does.
