### ISSUE TITLE
path/filepath: Abs can give incorrect results on unix systems

### ISSUE THREAD

**Issue by kevina** [golang/go#16255]
filepath.Abs can give incorrect results on unix systems.  The reason for this is it calls filepath.Clean() which does not take into account symbolic links when handling `..`.  For example in the sample program below it is incorrect to transform `dir2/dir1/../afile` to `dir2/afile` as dir1 is a symbolic link.

> What version of Go are you using (`go version`)?

```
go version go1.6.2 linux/amd64
```

> What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kevina/gocode2"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
> What did you do?

Use `filepath.Abs` in combination with symbolic links and `..`

Here is a sample program at https://play.golang.org/p/ZAhkresUaD, but note it won't run on the playground.  To reproduce the results it needs to be run on a Unix system.

The programs creates the following files/dirs/symlink
```
afile
dir1/
dir2/
dir2/dir1 -> ../dir1
```
And than uses the path `dir2/dir1/../afile` to read `afile`.  This correctly resolves when the path it relative or the absolute path is created manually, but fails when filepath.Abs() is used.

The path `/somedir/dir2/dir1/../afile` should resolve to `/somedir/afile`; however filepath.Abs() transforms that to the incorrect `/somedir/dir2/afile`.

> What did you expect to see?

The sample program should run without error.

> What did you see instead?

`open /tmp/abstest062312103/dir2/afile: no such file or directory`

**Comment by rsc** [comment]
This is working as intended, or at least as documented:

    Abs returns an absolute representation of path. If the path is not absolute
    it will be joined with the current working directory to turn it into an
    absolute path. The absolute path name for a given file is not guaranteed to
    be unique. Abs calls Clean on the result.

And Clean clearly states that:

    Clean returns the shortest path name equivalent to path by purely lexical
    processing. 

The effect is that unusual symlinks can cause Abs to return non-working paths. 
That's unfortunate, but it's unavoidable as documented.

Symlinks like these cause strange behavior in other programs too. See the transcripts at the beginning of https://9p.io/sys/doc/lexnames.html, for example.

**Comment by kevina** [comment]
I was afraid you were going to say that but I needed to be sure.

I have created my on version of Clean that does not remove ".." at https://github.com/kevina/safepath.
