### ISSUE TITLE
os/user: listgroups_unix.go: missing build directive line

### ISSUE THREAD

**Issue by cznic** [golang/go#16252]
tip @ 519b469795287dc81ab3b994f8809f61a0c802da

AFAICT, there is a line missing:
```go
 // +build cgo
```

The missing directive causes load errors when the `cgo` build tag is not defined, for example:

```
/home/jnml/go/src/os/user/lookup_stubs.go:65:6: listGroups redeclared,
        previous declaration at /home/jnml/go/src/os/user/listgroups_unix.go:22:6
```

I believe `getgrouplist_darwin.go` and `getgrouplist_unix.go` have the same problem.

**Comment by mikioh** [comment]
@cznic,

I guess that it happens when `CGO_ENABLED=0` and using `go build --tags cgo`, not only on os/user package but net package, right?

**Comment by cznic** [comment]
It's triggered by a 3rd party package loader (work in progress), which does not support CGO, so the `cgo` tag is undefined.

Do you need a exact reproduction case/steps? I can prepare that, it's just it involves unfinished/unstable stuff.

OTOH, `CGO_ENABLED= 0 ./all.bash` should do the same, in theory, and I did not try that.

**Comment by mikioh** [comment]
> It's triggered by a 3rd party package loader (work in progress), which does not support CGO, so the cgo tag is undefined.

But cross-compiling, maybe?

> Do you need a exact reproduction case/steps?

I think it's better.

**Comment by cznic** [comment]
Cannot reproduce using `CGO_ENABLED=0`. For example
```bash
$ CGO_ENABLED=0 go build -x -a os/user
...
mkdir -p $WORK/os/user/_obj/
mkdir -p $WORK/os/
cd /home/jnml/go/src/os/user
/home/jnml/go/pkg/tool/linux_amd64/compile -o $WORK/os/user.a -trimpath $WORK
-p os/user -complete -buildid 5ea22e2e3f690c420c76db9f6b3a981a0173d286
-D _/home/jnml/go/src/os/user -I $WORK -pack ./lookup.go ./lookup_stubs.go ./user.go
$
```
I don't know why the build does not include `getgrouplist_unix.go` and `listgroups_unix.go`. `unix` is not an item in syslist, the suffix `_unix` should not exclude the file from build on linux and the build directive seems to be satisfied:
```go
// +build dragonfly darwin freebsd !android,linux netbsd openbsd
```

Particulary, `!androind and linux` should be true in my case and thus the whole expression as well. I must be missing something. I'm no more sure if there really is a bug.

My env
```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jnml"
GORACE=""
GOROOT="/home/jnml/go"
GOTOOLDIR="/home/jnml/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build543108208=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
$ 
```

**Comment by ianlancetaylor** [comment]
Normally if cgo is enabled then files with import "C" are built, and if cgo is not enabled then files with import "C" are ignored.  Search for `isCgo` in go/build/build.go.

I don't know what the problem is here, but it would help to know how to reproduce it.

**Comment by cznic** [comment]
Thanks for clarifying. It means the bug is not in the Go project. Sorry for the noise.
