### ISSUE TITLE
time: update tzdata for Go 1.7?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16273]
Should we update our bundled tzdata for Go 1.7?

Egypt just changed their DST rules (canceling DST) with 3 days notice:
http://mm.icann.org/pipermail/tz/2016-July/023855.html

https://www.iana.org/time-zones/repository/releases/tzdata2016f.tar.gz was released 2016-07-05

/cc @robpike @adg @ianlancetaylor @quentinmit

**Comment by adg** [comment]
Sounds good to me.

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/24744

**Comment by OneOfOne** [comment]
Off topic, as an Egyptian, YAYAYAYAYAYAYAY.

**Comment by bradfitz** [comment]
Per comments on the CL, this no longer affects Egypt. (they changed their mind back and forth in-between our releases)

So demoting this to a Maybe.

@ianlancetaylor, your call.

The diff of affected zones is https://gist.github.com/bradfitz/08ad560eaa9790311bd0a168a53c7ca6

Here are the relevant NEWS entries which we'd pull in:

```
Release 2016f - 2016-07-05 16:26:51 +0200

  Changes affecting future time stamps

    Asia/Novosibirsk switches from +06 to +07 on 2016-07-24 at 02:00.
    (Thanks to Stepan Golosunov.)

  Changes to past and future time stamps

    Asia/Novokuznetsk and Asia/Novosibirsk now use numeric time zone
    abbreviations instead of invented ones.

  Changes affecting past time stamps

    Europe/Minsk's 1992-03-29 spring-forward transition was at 02:00 not 00:00.
    (Thanks to Stepan Golosunov.)


Release 2016e - 2016-06-14 08:46:16 -0700

  Changes affecting past time stamps

    Locations while uninhabited now use '-00', not 'zzz', as a
    placeholder time zone abbreviation.  This is inspired by Internet
    RFC 3339 and is more consistent with numeric time zone
    abbreviations already used elsewhere.  The change affects several
    arctic and antarctic locations, e.g., America/Cambridge_Bay before
    1920 and Antarctica/Troll before 2005.

    Asia/Baku's 1992-09-27 transition from +04 (DST) to +04 (non-DST) was
    at 03:00, not 23:00 the previous day.  (Thanks to Michael Deckers.)
```

**Comment by ianlancetaylor** [comment]
I think we should go ahead and commit your CL.
