### ISSUE TITLE
path/filepath: SkipDir does not work as expected for non-directory files

### ISSUE THREAD

**Issue by Fugiman** [golang/go#16280]
1. What version of Go are you using (`go version`)?
go version go1.6.1 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

3. What did you do?
Returned `filepath.SkipDir` in a `filepath.WalkFunc` when the file was not a directory.

4. What did you expect to see?
`filepath.Walk` would return `nil`

5. What did you see instead?
`filepath.Walk` returned `filepath.SkipDir`

I don't know whether this is an issue with the documentation or implementation, but the behavior seems to contradict the [documentation for `filepath.WalkFunc`](https://golang.org/pkg/path/filepath/#WalkFunc).
> If an error is returned, processing stops. The sole exception is when the function returns the special value SkipDir. If the function returns SkipDir when invoked on a directory, Walk skips the directory's contents entirely. If the function returns SkipDir when invoked on a non-directory file, Walk skips the remaining files in the containing directory.

**Comment by ianlancetaylor** [comment]
Can you provide a test case?  I'm not seeing the problem.

**Comment by Fugiman** [comment]
I've created a test case at https://play.golang.org/p/fGh07NE1g3

I would expect the output to be
```
2009/11/10 23:00:00 /tmp
2009/11/10 23:00:00 /tmp/first054003078
2009/11/10 23:00:00 /tmp/second116774189
2009/11/10 23:00:00 Worked as expected!
```

but instead it is
```
2009/11/10 23:00:00 /tmp
2009/11/10 23:00:00 /tmp/first054003078
2009/11/10 23:00:00 /tmp/second116774189
2009/11/10 23:00:00 skip this directory
```

**Comment by ianlancetaylor** [comment]
Thanks for the example.

I think the bug is a failure to handle `SkipDir` in the top-level directory.
