### ISSUE TITLE
Why should Golang stop appending certificate file after finding one

### ISSUE THREAD

**Issue by HuKeping** [golang/go#16284]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/h00283522/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

As the issue title, I don't quite understand why Golang stop appending certificate file after finding one, see https://golang.org/src/crypto/x509/root_unix.go:
```
func initSystemRoots()
```

Doesn't it possible that different certificates stored in different directory or different certs-bundle file?

4. What did you expect to see?

5. What did you see instead?

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

I'm closing this bug because there's no bug report here.
