### ISSUE TITLE
gofmt not ignoring easter egg keywords

### ISSUE THREAD

**Issue by nubunto** [golang/go#16297]
1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/foo/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
https://play.golang.org/p/TBKqnR0WY5

4. What did you expect to see?
I expected gofmt to ignore these keywords: https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/lex.go#L610-L615
to comply with the lexer.

5. What did you see instead?
A gofmt error. In my program, I make use of those keywords to improve readability, e.g.
```
func maybeErr() error {
  // ....
  despiteallobjections return err
}
```
Gofmt errors saying `expected ';', found return`
It would be nice if gofmt could handle these cases.

**Comment by ianlancetaylor** [comment]
I don't think the jokes need to be spread everywhere.  They're just jokes.
