### ISSUE TITLE
download image get memory leak

### ISSUE THREAD

**Issue by xuanzhaopeng** [golang/go#16290]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
`
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
[root@localhost scripts]# go version
go version go1.6 linux/amd64
[root@localhost scripts]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
`

3. What did you do?
`
url := <one image url , ex: www.google.fr/abc.png>
resp, err := http.Get(url)
defer resp.Body.Close()

if err != nil {
	return ""
}
contents, err := ioutil.ReadAll(resp.Body)
defer func() {
	contents = nil
}()

if err != nil {
	return ""
}

err = ioutil.WriteFile(filePath, contents, 0644)
if err != nil {
		return ""
}
`
Run above code 10000 times, than memory leak

4. What did you expect to see?
I try several ways, but always get memory leak

5. What did you see instead?
memory leak

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

The mailing list can help you improve your program. I'm going to close this because there's no concrete bug to be fixed. Thanks!

**Comment by xuanzhaopeng** [comment]
thanks :+1:
