### ISSUE TITLE
cmd/compile: make UNDEF into a pseudo-instruction

### ISSUE THREAD

**Issue by josharian** [golang/go#16291]
The compiler inserts `obj.AUNDEF` instructions into exit blocks without a return instruction, so that liveness analysis understands the control flow. However, `obj.UNDEF` is assembled into a two byte UD2 instruction (`0f 0b`). Something similar occurs on arm, and presumably on other architectures. Since that instruction is unreachable, we may as well omit it entirely, much like we do with `obj.NOP`. (Savings are small, approx 0.15% binary size, but might help a bit in small, hot, cache-sensitive functions.)

One easy fix is to change the assemblers to treat `obj.AUNDEF` the same as `obj.NOP`. However, this will break any hand-written assembly that uses UNDEF and wants it to mean UD2.

Another fix is to add `obj.AUNDEFNOP`, which plive.go would treat as the same as `obj.AUNDEF`, but which would be converted to `obj.NOP` at assembly time.

Opinions? I'd rather do the former.

@randall77

**Comment by randall77** [comment]
I think treating UNDEF as NOP (no generated code) would be fine.  I'm not worried about people depending on it generating real code; assembly isn't under the go1 guarantee.

I remember there being a case where we need a nop that generated real code - maybe before deferreturn so we get correct line numbers?  Just make sure we don't break that.

**Comment by josharian** [comment]
The nop that generates real code is inserted via ginsnop (per arch). On x86, it uses XCHGL AX, AX.

**Comment by rsc** [comment]
Missed Go 1.8. Doesn't really seem worth it at all, at least not without more motivation. You'll probably spend more time debugging it than all the CPU saved ever.

**Comment by josharian** [comment]
Fixed by https://go-review.googlesource.com/c/go/+/171058.
