### ISSUE TITLE
runtime: runtime-lldb test failure on Mac OS

### ISSUE THREAD

**Issue by broady** [golang/go#16295]
Came across this while releasing go1.7rc1 on my Macbook Air:

```
--- FAIL: TestLldbPython (2.26s)
	runtime-lldb_test.go:182: Unexpected lldb output:
		Created target
		Created breakpoint
		Process launched
		Hit breakpoint
		Stopped at main.go:10
		Stopped in main.main
		intvar = None
FAIL
FAIL	runtime	28.910s
```

TryBots are happy, though, so could be an issue with whatever Python version I have installed on this machine?

**Comment by ianlancetaylor** [comment]
It's more likely to do with the version of lldb you have installed.

**Comment by broady** [comment]
```
$ which lldb
/usr/bin/lldb
$ lldb -v
lldb-300.2.51
$ ls -l $(which python)
lrwxr-xr-x  1 cbro  wheel  33 Nov 11  2014 /usr/local/bin/python -> ../Cellar/python/2.7.6/bin/python
```

(my Python is installed via Homebrew)

**Comment by bradfitz** [comment]
Sounds like this was a homebrew/Python mismatch issue, since nobody else can repro this.

Closing for now per the release meeting.
