### ISSUE TITLE
cmd/cgo: C.malloc does not support comma error return values

### ISSUE THREAD

**Issue by catalase** [golang/go#16309]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.6.2 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Administrator\Go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?

I ran `cgom.go` whose source is at https://play.golang.org/p/lFkVjkjn5W

4. What did you expect to see?

In cgo manual (https://golang.org/cmd/cgo/), the manual states that

> Any C function (even void functions) may be called in a multiple assignment context to retrieve both the return value (if any) and the C errno variable as an error (use _ to skip the result value if the function returns void). For example:

I think C.malloc is C function. And Any C function may be called in a multiple assignemt context. Therefore, C.malloc should be called in a multiple assignment.

The idea was correct only if compilation would be successful.

5. What did you see instead?

```
$ go run cgom.go
# command-line-arguments
.\cgom.go:22:12: no two-result form for C.malloc
```

Unfortunately, reality is not. C.malloc cannot be used in that way, even though free function can be used in that way.

C.malloc function seems not to be part of a set of C functions, because contraposition of "Any C function may be called in a multiple assignment context" is "if a function may not be called in a multiple context, then the function is not C function".

This contradicts usual idea that malloc should be C function. Go override some of special functions as malloc, etc. But these functions do not act like C functions.

**Comment by josharian** [comment]
cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
I think the likely resolution of this is to say that `C.malloc` is an exception.

Is there any reason that it is important to get an `errno` result from `C.malloc`?  It has no defined `errno` results anyhow, and in practice the only one it ever returns is `ENOMEM`.

**Comment by catalase** [comment]
@ianlancetaylor If `C.malloc` changes as an exception, https://golang.org/cmd/cgo/ should be modified to specify that `C.malloc` is an exception.

I'm think differently. Whether `C.malloc` may support comma error return has something with consistency. There are a lot of C functions that has no defined or uesless `errno` such as `C.malloc`, `C.free`, .... It is consistency to support comma error return regardless of advantage of that `errno`. I think unnecessary consistency is a consistency for consistency.

**Comment by jfrazelle** [comment]
I think `C.malloc` should be an exception, if that's ok I can make a patch to the docs.

**Comment by sh4m1l65** [comment]
Please explain the rationale for making an C.malloc an exception. malloc(3) is documented to use errno=ENOMEM to signal failure. The documented CGO multi-valued return makes the Go idiom of checking for err != nil possible:

> cptr, err := C.malloc(C.sizeof_struct_foo)
> if err != nil {
>         return nil, fmt.Errorf("allocating memory exempt from GC: %v", err)
> }
> // ... use cptr

If there is an overriding concern, I don't yet understand it. If possible, please explain it.

**Comment by minux** [comment]
I think the reason is likely historical artifact or overlook.

I don't think fixing it buys much. The only documented errno return is
ENOMEM,
and you can check the returned pointer for the same effect.

Anyway, I suspect that Go would has crashed somewhere else already if malloc
ever runs out of memory.

**Comment by aclements** [comment]
While the case is certainly obscure, it seems reasonable to me to make C.malloc consistent with other functions and keep the documentation simple. Arguably, the obscurity of the case even *supports* keeping the documentation simple.

Is there some technical reason why this isn't easy to fix?

**Comment by jessfraz** [comment]
This would be a breaking change to the API

**Comment by w7tek** [comment]
un. freaking. believable.

How is that a breaking change? It is already the case that Cgo code may call C functions with either a single or a single plus error result. Code that is already written to not "request" the error result from `C.malloc` will continue to work just the same as other code for C language functions that doesn't care to pick up the error result. Code that currently won't work if written as documented, would become compilable.

Please explain how this is an incompatible change?

**Comment by quentinmit** [comment]
Supporting code that previously didn't compile, without changing behavior for code that did previously compile, doesn't seem like a breaking change to me.

**Comment by aclements** [comment]
> This would be a breaking change to the API

How so? Currently the only way to call C.malloc is with zero or one return values. I don't think anyone's proposing changing the behavior in this case (including the panic behavior). This just adds the possibility to call it with two return values. The only oddity would be that, presumably, we would still want it to panic in the zero or one case, and not panic in the two case. This is different from other C functions, but not without precedent in the language (e.g., one- versus two-assignment type assertions).

**Comment by jessfraz** [comment]
ok calm yourself I misunderstood apologies

**Comment by w7tek** [comment]
Ok. That's understandable. If it were true, the "breaks API compatibility" card would clearly trump the desire to avoid gratuitous one-off, contrary-to-documented behavior. That's why the (mistaken?) claim of incompatible change comes across as such a big deal.

**Comment by w7tek** [comment]
and when I say "gratuitous one-off, contrary-to-documented" behavior, I would be glad to be proved wrong. I just don't think the conversation thus far on this issue has demonstrated that it's not a gratuitous deviation from documented behavior. Maybe it's the search for that answer that will bring about a satisfactory closing of this issue. Or, maybe it is what I think it is, and should be fixed to support calling the same way other Cgo functions can be called.

**Comment by ianlancetaylor** [comment]
I'm fine with handling an `errno` return from `C.malloc`.  It seems pointless to me but I'll review the CL if someone wants to do the work.

**Comment by w7tek** [comment]
@ianlancetaylor help? I don't recognize the CL acronym. I would be glad to roll up my sleeves and dig into this, because gratuitous inconsistency consistently bugs me. Is there a contributor agreement, or can you direct me to where the process is documented? I understand that PR's are not accepted on this project, but I don't know how to actually contribute. Thanks.

**Comment by bradfitz** [comment]
CL = "change list". Think "PR" (Pull request) or "patch".

You found the right contributing docs.

**Comment by rsc** [comment]
C.malloc is special because we guarantee it can never fail. I will send a CL documenting this.

**Comment by ianlancetaylor** [comment]
@sh4m1l65 Both changes will be in the Go 1.8 release.
