### ISSUE TITLE
runtime: improve documentation on SetFinalizer

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#16301]
The documentation for [SetFinalizer](https://tip.golang.org/pkg/runtime/#SetFinalizer) uses named variables `obj` and `finalizer` in the method signature, but refers to `x` and `f` in the documentation comment.  This makes it harder to read, since the doc refers to hypothetical variables rather than the ones used by the function.  

Additionally, later down in the comment `obj`:

    It is not guaranteed that a finalizer will run if the size of *obj is zero bytes.

I believe this already tricky method would be easier to understand if the doc used consistent terminology.

**Comment by cespare** [comment]
@carl-mastrangelo it seems that this is already fixed on tip (which you linked).

**Comment by bradfitz** [comment]
Yes, fixed by 1d809c5c1476338af180014e2152b3f5b0fac327

**Comment by carl-mastrangelo** [comment]
d'oh!  Sorry for the noise!
