### ISSUE TITLE
cmd/go: go generate confounded by errors in generated code

### ISSUE THREAD

**Issue by monotrememan42** [golang/go#16307]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andrew/code/myriad"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Unfortunately, this error requires multiple files to reproduce. the description should suffice, tho.

i use yacc and nex as part of a package. the generated code lives in another package
(so that generated code is not mixed in with source-controlled code).
occasionally, a mistake is made in my parse.y so that the generated parse.go causes an import cycle.
at this point, i can't simply correct parse.y (to not have the import cycle), because go generate
won't run the generate commands because (apparently) it processes the import directives first.

i observe that "go generate --help" says, in part, 
             Note that go generate does not parse the file, so lines that look
            like directives in comments or multiline strings will be treated
             as directives.

4. What did you expect to see?
i would expect go generate to run the command and not worry about an import cycle.

5. What did you see instead?
go generate determines (correctly but irrelevantly) that there is an import cycle and does not run the generate commands.

**Comment by ianlancetaylor** [comment]
What is the exact command that you run?  What is the exact error that you see?

**Comment by ianlancetaylor** [comment]
Note that we are likely to need a small test case in order to fix this.  Unfortunate experience shows that it is very hard to recreate a specific problem from a text description.

**Comment by cznic** [comment]
@monotrememan42 `go generate` does not [seem](https://github.com/golang/go/blob/57e459e02b4b01567f92542f92cd9afde209e193/src/cmd/go/generate.go) to parse go source files.

Do your go generate lines (the magic comments) invoke, for example, `stringer` or any other tool that needs the package to be compiled?

Sometimes it might help to "reset" the `parser.go` file before doing other things, like

```go
//go:generate echo "package foo" > parser.go
//...
//go:generate go tool yacc -o parser.go parser.y
```

or

```go
// Start with the last known good parser.go
//go:generate git checkout -f parser.go
//...
//go:generate go tool yacc -o parser.go parser.y
```

**Comment by monotrememan42** [comment]
the first few lines of the source file are

//go:generate nex -p Parse -e -o ../../gen/rivegen/lexer.go lexer.nex
//go:generate go tool yacc -p Parse -o ../../gen/rivegen/parse.go parse.y
//go:generate mv y.output ../../gen/rivegen

package rive


i am working on getting a small reproducible example for you; i think i can do it in 2-3 files.
i’ll send a zipped tar file. when i do.

**Comment by monotrememan42** [comment]
attached is a small tar file that contains a reproducible example.
there is a script.out file that shows the bug.
sorry i did not include this originally.

	andrew

**Comment by monotrememan42** [comment]
did the attached tar file make it? i don't see it here. i'll attach it again just in case.
ohhh, stupid system doesn't support tar but doesn't tell you (when submitting by email).
lovely. here is the same stuff in a zip file.
[go16307.zip](https://github.com/golang/go/files/360738/go16307.zip)

**Comment by monotrememan42** [comment]
i added the test case to reproduce

**Comment by monotrememan42** [comment]
i'm not trying to annoy anyone, but i wanted to ensure someone had gotten the test cases etc. can someone please speak to that? thanks.

**Comment by cznic** [comment]
With some modifications I was able to reproduce the problem. I didn't investigate more. I'd look for go/types interfering when go generate is invoked, shooting in the dark, of course.
