### ISSUE TITLE
fmt: define what %p means (or doesn't mean) on interfaces

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16314]
(split from https://github.com/golang/go/issues/16230#issuecomment-231563421)

What does %p mean in the `fmt` package for interface values?

It seems to do something, but the documentation says nothing.

/cc @josharian @robpike

**Comment by josharian** [comment]
It's well-defined. The fmt package docs say: "Regardless of the verb, if an operand is an interface value, the internal concrete value is used, not the interface itself." This is a bug in vet, and I already have a fix in my tree for it as part of fixing #11041.
