### ISSUE TITLE
Fork/Exec perfomance issue

### ISSUE THREAD

**Issue by TLavocat** [golang/go#16319]
Good morning, 

I'm reporting what seems to be a performance issue for the Fork Exec of golang.

1. What version of Go are you using (`go version`)?

go1.5.1 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

Debian jessie.

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/faquin/Documents/inria/workspace"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

I try to execute a lot of small commands efficiently.
Here is some runnable code showing the issue :

```
package main
import (
    "fmt"
    "strconv"
    "os/exec"
)

func main() {
    for i:= 0; i<2000; i++{
        var cmd *exec.Cmd = exec.Command("echo", strconv.Itoa(i));
        o, _ := cmd.CombinedOutput();
        fmt.Println(string(o));
    }
}
```

running time :
```

time ./main  > output

real	0m2.048s
user	0m0.276s
sys	0m0.704s

```
When not taking care of the output : 
```
package main

import (
    "strconv"
    "os/exec"
)

func main() {
    for i:= 0; i<2000; i++{
        var cmd *exec.Cmd = exec.Command("echo", strconv.Itoa(i));
        cmd.Run();
    }
}
```

Running time :

```
time ./main > t

real	0m2.035s
user	0m0.176s
sys	0m0.504s
```

4. What did you expect to see?

A running time in the same order of magnitude that 
```
time for i in `seq 1 2000`; do echo "echo $i" ; done > output
```

```
real	0m0.030s
user	0m0.016s
sys	0m0.012s
```

5. What did you see instead?

A running time 100x slower.

I've manged a tiny hack, enable to obtain a suffisent running time but it present some inconvenient, I cannot get any error code or really separate executions output.

```
package main

import (
    "strconv"
    "fmt"
    "bufio"
    "os/exec"
)

func main() {
    var cmd *exec.Cmd = exec.Command("/bin/bash");
    in,_   := cmd.StdinPipe();
    out,_  := cmd.StdoutPipe();
    reader := bufio.NewReader(out);
    cmd.Start();
    for i:= 0; i<2000; i++{
        in.Write([]byte("echo "+strconv.Itoa(i) + " 2>&1 \n"));
        s, _ := reader.ReadString('\n')
        fmt.Println(s);
    }
}
```

Running time :
```
time ./main > t

real	0m0.076s
user	0m0.012s
sys	0m0.020s
```

Is there something to do on this subject ?

Thanks for your attention,
Thomas

**Comment by ianlancetaylor** [comment]
Your time comparisons are invalid, as the shell implements echo directly, not via fork and exec.  For a proper timing comparison, run

    time for i in `seq 1 2000`; do /bin/echo "echo $i" ; done > output

Closing as I see no bug here.

**Comment by TLavocat** [comment]
Ok, thanks for the precision and the answer.
