### ISSUE TITLE
go/types: calling Sizeof(*Struct) twice with different sizes yields incorrect results

### ISSUE THREAD

**Issue by josharian** [golang/go#16316]
Typecheck a package containing:

```go
type S struct {
	i int
	b bool
	s string
	n int
}
```

Given `t` (of type `*types.Struct`) that contains the type `S`, run:

```go
	sizes := types.StdSizes{WordSize: 4, MaxAlign: 4}
	fmt.Println(sizes.Sizeof(t))
	sizes = types.StdSizes{WordSize: 8, MaxAlign: 8}
	fmt.Println(sizes.Sizeof(t))
```

Want: `20`, then `40`. Got: `20`, then `20`. It appears that the problem is in `go/types/sizes.go`:

```go
func setOffsets(s *Struct, sizes Sizes) bool {
	var calculated bool
	s.offsetsOnce.Do(func() {
		calculated = true
		s.offsets = sizes.Offsetsof(s.fields)
	})
	return calculated
}
```

Once the offsets for a struct have been calculated once, they are cached forever, even if the `sizes` parameter changes.

I encountered this while working on improvements to vet. I'm happy to fix, but I'd like input on what direction the fix should take. It's not obvious to me. The only decent options I see are:

(1) removing the cached offsets entirely
(2) keeping a map from StdSizes to cached offsets and type assert to go from Sizes to StdSizes (because not all Sizes implementations can serve as a map key)

and neither of those is particularly appealing.

My temporary workaround to eliminate the call to `s.offsetsOnce.Do`, to force recalculation each time.

cc @griesemer @mdempsky

**Comment by josharian** [comment]
Another, intermediate option: Store the Sizes param that was used to calculate the cached offsets. If it is unchanged (normal case), used the cache. Otherwise recalculate and replace the old cache. Simple, and should maintain performance for normal uses. It loses the concurrency safety of once.Do; does that matter?

**Comment by griesemer** [comment]
I suspect recomputing the size each time is ok. I doubt this is a speed-critical portion of code.

**Comment by josharian** [comment]
I have a CL ready for 1.8 that removes the cache. I'm not sure how best to confirm that the performance impact is ok, though. Is there a standard corpus to measure on?

**Comment by griesemer** [comment]
@josharian I tend to run the type checker on the std lib and look at the times. But I doubt that will show you much. Calls to Sizeof are exceedingly rare.
