### ISSUE TITLE
OSX crash writing C-side data from c-shared library

### ISSUE THREAD

**Issue by JohnCGriffin** [golang/go#16320]
Please answer these questions before submitting your issue. Thanks!

*  What version of Go are you using (`go version`)?

go1.6.2 darwin/amd64, 1.7 beta 2 and 1.7 RC1.  There appears to be no problem on Ubuntu.

System compiler

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

*  What operating system and processor architecture are you using (`go env`)?

El Capitan 10.11.5 (15F34)
2.8 Ghz Intel Core Duo

* What did you do?
After building shared library with:
go build -o libsample.dylib -buildmode=c-shared sample.go

of the following program,
```
package main

/*
#include <string.h>
*/
import "C"

//export sample
func sample(buf *C.char) int {
	s := "sample"
	cs := C.CString(s)
	C.strcpy(buf, cs)
	return len(s)
}

func main() { }

```
*  I expected to see the copied bytes from "sample" in the buffer passed by the exported sample function.

* Instead I saw following output results upon trying to execute the code from Python or Racket
```
[signal 0xb code=0x1 addr=0x263aab0 pc=0x7fff9bdd4245]

runtime stack:
runtime.throw(0x1027e54c0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x1027ab960, 0xc820034e98, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820034e60 sp=0xc820034e30
main._Cfunc_strcpy(0x263aab0, 0x100737760, 0x0)
	command-line-arguments/_obj/_cgo_gotypes.go:53 +0x42 fp=0xc820034e98 sp=0xc820034e60
main.sample(0x263aab0, 0x10279dbc0)
	/Users/john/GOWORK/src/jcgsrq/gozulu/zululink/sample.go:12 +0x51 fp=0xc820034ec8 sp=0xc820034e98
main._cgoexpwrap_811a8bc3212f_sample(0x263aab0, 0x7fff5bffd500)
	command-line-arguments/_obj/_cgo_gotypes.go:71 +0x21 fp=0xc820034ee0 sp=0xc820034ec8
runtime.call32(0x0, 0x7fff5bffd438, 0x7fff5bffd4c8, 0x10)
	/usr/local/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc820034f08 sp=0xc820034ee0
runtime.cgocallbackg1()
	/usr/local/go/src/runtime/cgocall.go:267 +0x10c fp=0xc820034f40 sp=0xc820034f08
runtime.cgocallbackg()
	/usr/local/go/src/runtime/cgocall.go:180 +0xd7 fp=0xc820034fa0 sp=0xc820034f40
runtime.cgocallback_gofunc(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:716 +0x60 fp=0xc820034fb0 sp=0xc820034fa0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820034fb8 sp=0xc820034fb0

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
```
Sample Python driver sequence.  The same results happen in Racket.

```

from ctypes import c_void_p, CDLL

lib = CDLL('/Users/john/GOWORK/src/jcgsrq/gozulu/zululink/libsample.dylib')

lib.sample.argtype = (c_void_p,)
import array
bs = array.array('b',[0 for x in range(10) ])
buf,sz = bs.buffer_info()
lib.sample(buf)
```

**Comment by ianlancetaylor** [comment]
I don't know enough Python to know whether you are calling the function the right way.  Could you call a similar C function in this way?

What is the traceback if you run your program with the environment variable `GOTRACEBACK=system`?

**Comment by JohnCGriffin** [comment]
A few answers.

1) Calling an equivalent C library also crashes.  That points away from a GO problem.

2) I was incorrect about the Racket access. It's quite fine.  That points away from a GO problem.

3) I've only used GO for 2 weeks.  That points to the user. 

It turns out that installing Python from the python.org site is clashing somewhere with Apple OS installed python libraries.  Rather than actually trying to fix it, I'm just going to reinstall all the OS from scratch and accept Apple's outdated Python version.

Thanks for the response and consider this not a GO problem.

**Comment by bradfitz** [comment]
Thanks for the clarification. I'll close this for now.
