### ISSUE TITLE
crypto/sha256: add AVX/AVX2 implementations of SHA2

### ISSUE THREAD

**Issue by fkautz** [golang/go#16322]
Golang has a software based SHA2 implementation. Specifically, SHA256 is slower than it needs to be.

With the new upcoming OCI images which bring content-addressable layers which are SHA256 based, it would be very useful to have AVX2 enabled SHA2 sums.

---

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
Linux

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fkautz/go"
GORACE=""
GOROOT="/home/fkautz/opt/go"
GOTOOLDIR="/home/fkautz/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0"
CXX="g++"
CGO_ENABLED="0"

3. What did you do?

https://play.golang.org/p/Lg2dgrXJht

4. What did you expect to see?
Very fast SHA2 when hardware supports is present
Normal SHA2 when hardware support is not present

5. What did you see instead?
Slower than necessary SHA2

**Comment by bradfitz** [comment]
This was already done in 2210d88a889e0ea463bcdef2b658aaec1050cf01
