### ISSUE TITLE
 ocsp: wrong default value of Version in ResponseData

### ISSUE THREAD

**Issue by indutny** [golang/go#16321]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="ccache"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="ccache"
CGO_ENABLED="1"
```

3. What did you do?

I tried to use OCSP response by LetsEncrypt, but it is incorrectly encoded. Turned out to be a go problem.

4. What did you expect to see?

Properly formatted DER-encoding.

5. What did you see instead?

`ResponseData`'s `version` field encoding is present, even though it is equal to `0` (default value).

ASN.1 specification of `ResponseData` is:

    ResponseData ::= SEQUENCE {
          version              [0] EXPLICIT Version DEFAULT v1,
          responderID              ResponderID,
          producedAt               GeneralizedTime,
          responses                SEQUENCE OF SingleResponse,
          responseExtensions   [1] EXPLICIT Extensions OPTIONAL }

Where `Version` is:

    Version ::= INTEGER { v1(0) }

Invalid default value results in a presence of a field that otherwise
should not be present.

**Comment by indutny** [comment]
I have a CL open, just in case : https://go-review.googlesource.com/#/c/24841/

**Comment by odeke-em** [comment]
Since the CL was merged, I think we can now close this issue. /cc @agl and @ianlancetaylor
