### ISSUE TITLE
cmd/cover: when a panic occurs in a function call, cover still marks the whole basic block covered

### ISSUE THREAD

**Issue by wadey** [golang/go#16325]
go version go1.6.2 darwin/amd64
This is similar to #10185, but the issue still occurs if the panic happens inside of a function call.

A contrived example:

rand.go:

```go
package covertest

import (
	"log"
	"math/rand"
)

func Rand(i int64) int64 {
	v := rand.Int63n(i)
	log.Println(v)
	return v
}

func MaybeRand(i int64) int64 {
	defer func() {
		recover()
	}()
	return Rand(i)
}
```

rand_test.go:
```go
package covertest

import "testing"

func TestMaybeRand(t *testing.T) {
	if MaybeRand(0) != 0 {
		t.Error("expected zero")
	}
}
```

Coverage should be less than 100% because the `log.Println` inside of Rand is never called. But executing the tests with coverage shows:

    coverage: 100.0% of statements

The issue is that the coverage blocks are not fine grained enough if a panic occurs in a function call.

**Comment by robpike** [comment]
This is a reasonable request but is impractical to fix given the way the cover tool works. It works line-by-line, file-by-file. To solve it would require a much more global analysis of the program or be much more expensive. In your example it would either need to examine the rand package to see that Int63 can panic, or put a counter on every line, which could be too expensive in time and memory (and would require a major redesign).
