### ISSUE TITLE
encoding/pem: pem.Decode should take care of PEM file's encapsulation boundaries

### ISSUE THREAD

**Issue by simon-xia** [golang/go#16335]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

   ` go version go1.6.2 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

    ```
GOARCH="amd64"
GOBIN="/Users/simon/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/simon/Myfruit/Go/imports:/Users/simon/Mygo"
GORACE=""
GOROOT="/Users/simon/go"
GOTOOLDIR="/Users/simon/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

code:  [https://play.golang.org/p/kjL-dBzhI5](https://play.golang.org/p/kjL-dBzhI5)

according to [rfc1421 4.4  Encapsulation Mechanism](https://tools.ietf.org/html/rfc1421), the key is in invaild format

when I run the command `openssl rsa -noout -text -in test.key`, the following error occurred:
```
unable to load Private Key
10374:error:0906D066:PEM routines:PEM_read_bio:bad end line:/SourceCache/OpenSSL098/OpenSSL098-50/src/crypto/pem/pem_lib.c:747:
```

similar issue goes here:
[http://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6](http://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6)

4. What did you expect to see?

output message: `fail to decode the key`

5. What did you see instead?

output message: `success to decode the key`

maybe the following patch help

```
diff --git a/src/encoding/pem/pem.go b/src/encoding/pem/pem.go
index 506196b..b00d504 100644
--- a/src/encoding/pem/pem.go
+++ b/src/encoding/pem/pem.go
@@ -132,6 +132,11 @@ func Decode(data []byte) (p *Block, rest []byte) {
                return decodeError(data, rest)
        }

+       endLine, next := getline(rest[endIndex:])
+       if !bytes.HasSuffix(endLine, pemEndOfLine) {
+               return decodeError(data, next)
+       }
+
        base64Data := removeWhitespace(rest[:endIndex])
        p.Bytes = make([]byte, base64.StdEncoding.DecodedLen(len(base64Data)))
        n, err := base64.StdEncoding.Decode(p.Bytes, base64Data)
```

**Comment by agl** [comment]
I don't immediately see where the RFC requires that the PEM block end with a newline. I'm usually happy to make things strict but this case isn't clear to me.

**Comment by simon-xia** [comment]
it is not about newline, it's about the footer of the PEM file. there should be *five* `-` at end of the file, less or more is incorrect.

**Comment by agl** [comment]
Ha, right. Sorry I didn't see that. Patch coming.

**Comment by tarndt** [comment]
@agl I don't think this PR was rolled out as thoughtfully as it should have been; this made the same production Go code (and the same config files) when redeployed with an updated version of Go break.... all because some config files were missing a dash. :crying_cat_face: 

Since not being strict here wasn't really a security issue I would suggest that in the future fixes for issues of trivial severity, but potentially high impact, like this warn/log for a Go version before they start enforcing. Thanks!
