### ISSUE TITLE
invalid memory address or nil pointer dereference in /usr/local/go/src/sync/atomic/64bit_arm.go

### ISSUE THREAD

**Issue by jkowalski** [golang/go#16330]
I'm getting "invalid memory address or nil pointer dereference" in /usr/local/go/src/sync/atomic/64bit_arm.go on my ARM box when trying to run unit tests for my little project (http://github.com/kopia/kopia).

Tried on both 1.6.2 and 1.7 RC1 using official binaries. 

The same test works fine on AMD64.

1. What version of Go are you using (`go version`)?

go version go1.6.2 linux/arm
go version go1.7rc1 linux/arm

2. What operating system and processor architecture are you using (`go env`)?

$ uname -a

Linux chip1 4.3.0-ntc #1 SMP Fri Feb 19 09:37:25 PST 2016 armv7l GNU/Linux
The hardware is from http://getchip.com/

$ go env (1.6.2)

GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chip/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

$ go env (1.7rc1)

GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chip/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
$ go test github.com/kopia/kopia/fs/...

4. What did you expect to see?
no failures

5. What did you see instead?

--- FAIL: TestUpload (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0xc8b5c]

goroutine 8 [running]:
panic(0x39a2d8, 0x1070a038)
	/usr/local/go/src/runtime/panic.go:481 +0x330
testing.tRunner.func1(0x1076a9c0)
	/usr/local/go/src/testing/testing.go:467 +0x168
panic(0x39a2d8, 0x1070a038)
	/usr/local/go/src/runtime/panic.go:443 +0x448
sync/atomic.addUint64(0x1074ef5c, 0x3, 0x0, 0x3, 0x0)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x68
github.com/kopia/kopia/repo.(*countingReader).Read(0x107a4cf0, 0x107ba000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/chip/go/src/github.com/kopia/kopia/repo/counting_reader.go:19 +0xa4
io.copyBuffer(0xb65ab2b8, 0x1070a870, 0xb65ab9c8, 0x107a4cf0, 0x107ba000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/io/io.go:380 +0x1c4
io.Copy(0xb65ab2b8, 0x1070a870, 0xb65ab9c8, 0x107a4cf0, 0x107a4cf0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:350 +0x64
github.com/kopia/kopia/blob.(*fsStorage).PutBlock(0x107108d0, 0x10710e71, 0x20, 0xb65ab9a8, 0x107a4cf0, 0x0, 0x0, 0x0)
	/home/chip/go/src/github.com/kopia/kopia/blob/filesystem.go:174 +0x51c
github.com/kopia/kopia/repo.(*objectWriter).flushBuffer(0x10719540, 0x0, 0x0, 0x0)

**Comment by ianlancetaylor** [comment]
The address you are passing to atomic.AddUint64 is 0x1074ef5c, which is not 64-bit aligned.  See the very bottom of https://golang.org/pkg/sync/atomic/ , where it says "On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically."

Closing.
