### ISSUE TITLE
gccgo: improve caching for backend interface types (reduces peak memory consumption)

### ISSUE THREAD

**Issue by thanm** [golang/go#16334]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +5701174 Mon Jun 13 14:05:52 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?

When I compile the predefined "fmt" package (using as a benchmark) with gccgo, the heap usage tops out at about 16MB for the compile.  

4. What did you expect to see?

5. What did you see instead?

I have been looking at heap and execution profiles for gccgo when compiling the "fmt" package, to get a sense for where time + memory are being spent.

As would be expected, the front end code goes not show up at all in the cpu profile; nearly all the time is in the back end (no surprise there).

The memory profile looked a bit different, though, and I think there may be some opportunities for caching that would bring down the front end memory use.

The first attached image shows the peak heap usage from "massif", note the top three blue items (Interface_info_expression::do_type(), Typed_identifier_list::copy(), etc). This is suspicious.

From looking at Interface_info_expression::do_type() in callgrind (second attached image), it looks as though there are about 800 calls to the routine for the INTERFACE_INFO_METHODS case, each results in a new type returned.

All of the calls are passing in the same type (the interface for "fmt"); it would be better to keep a cached of previously constructed results. I prototyped this change, looks like the memory consumption comes down to about 10mb (third attached image).

![massif-snapsnot](https://cloud.githubusercontent.com/assets/12280172/16772478/6d7bf42a-4822-11e6-8cc5-64373368b9cb.png)
![callgrind-snapshot](https://cloud.githubusercontent.com/assets/12280172/16772483/71f19848-4822-11e6-99e1-f4ecf73a4cbc.png)
![massif-new-snapshot](https://cloud.githubusercontent.com/assets/12280172/16772485/75792dbe-4822-11e6-8ddd-f86e7af44020.png)

**Comment by ianlancetaylor** [comment]
SGTM.  I'll just note that one idea I've had for a while, but never implemented, is to use a special purpose allocator for the C++ objects in the gofrontend, which would make it very easy to discard all of them when we enter the backend.
