### ISSUE TITLE
reflect: doc clarification for equality and reflect.Type

### ISSUE THREAD

**Issue by zombiezen** [golang/go#16348]
It seems like we guarantee that `reflect.Type` values can be compared for equality for ==.  The only mention of this seems to be in the `String()` method of the interface, but it seems worth calling out in the type's documentation.  Thoughts?

**Comment by ianlancetaylor** [comment]
Sure.

**Comment by quentinmit** [comment]
This might affect #8082 - I would imagine that reflect.Type would not == compare for two interfaces that are considered identical under #8082. Also #16339 might cause two Types to have different names even though they're the same. So it seems like it's not a good idea to add this guarantee if either of those proposals goes in.

**Comment by ianlancetaylor** [comment]
I think it can be written such that it is OK.  If `T1` and `T2` are Go types, and `v1` and `v2` are values of those types respectively, then `reflect.TypeOf(v1) == reflect.TypeOf(v2)` precisely when both `(interface{})(v1).(T1)` and `(interface{})(v1).(T2)` succeed (and the same type assertions also succeed for `v2`).
