### ISSUE TITLE
A Pokémon in Go

### ISSUE THREAD

**Issue by shlomizadok** [golang/go#16344]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Go 1.6.2

2. What operating system and processor architecture are you using (`go env`)?
Linux x86_64

3. What did you do?
Nothing, I swear... I have only searched for a Pokémon

4. What did you expect to see?
I have expected to find a Pokémon in Go (duh!)

5. What did you see instead?
Since I have not  found a Pokémon in Go, I thought of adding one. Can you find it? 

![image](https://cloud.githubusercontent.com/assets/433583/16796203/0d90e822-48ea-11e6-8ec8-93a12a33e7fd.png)

This issue is just to say: **thank you ♥**

Hint: look  under the magnifier :smiley:

**Comment by mattn** [comment]
Really? I found this on pokemon branch of Go.

![86acddef50d76293](https://cloud.githubusercontent.com/assets/10111/16798260/2ace0f78-4926-11e6-9a5b-2c2be6e584d6.png)

**Comment by catalase** [comment]
Gokémon?

**Comment by adg** [comment]
Let's revisit this in Go 2.

**Comment by AlekSi** [comment]
We have it now: https://github.com/tompng/pokemon-go
