### ISSUE TITLE
runtime: if we make a 1.6.3 release, backport the macOS Sierra patch

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#16354]
If we make a 1.6.3 release, it should include the fix for issue #16272 , so that 1.6.3 will work correctly on Sierra.

**Comment by geoff-codes** [comment]
Not fixed. https://github.com/golang/go/issues/16570

**Comment by bradfitz** [comment]
It was fixed. But Beta 4 broke it again.

We'll open a new bug rather than repurpose this one, though.

**Comment by liggitt** [comment]
did a bug to track backporting the ultimate sierra fix to 1.6.x ever get opened?

**Comment by liggitt** [comment]
not seeing it in https://github.com/golang/go/milestone/45, opened https://github.com/golang/go/issues/17234 to track
