### ISSUE TITLE
net: internal dtoi and xtoi helpers have unusual API

### ISSUE THREAD

**Issue by mdempsky** [golang/go#16350]
These internal helpers have signatures like:

    func dtoi(s string, i0 int) ...
    func xtoi(s string, i0 int) ...

and they parse an integer value from `&s[i0]`.  Especially since the majority of callers use `i0==0`, it seems like it would be simpler / more idiomatic to just have the caller pass `s[i0:]` as an argument.

In particular, dtoi theoretically supports parsing negative integers, except it looks for the `'-'` character at `s[0]`, not `s[i0]`.

/cc @bradfitz @dpiddy

**Comment by bradfitz** [comment]
Yes, those weird me out every time I encounter them.
