### ISSUE TITLE
x/tools/cmd/guru: melpa go-guru incompatible with current 'go get' version

### ISSUE THREAD

**Issue by samv** [golang/go#16351]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I first installed go guru via MELPA (version 20160712.622)

I then ran `go get golang.org/x/tools/cmd/guru`

I opened a go file and tried to run `go-guru-definition` (C-x C-o j) to jump to the definition of a file

4. What did you expect to see?

Jump to the definition

5. What did you see instead?

`flag provided but not defined: -json`

My workaround was to remove the melpa-sourced version of guru using `rm -r ~/.emacs.d/elpa/go-guru*` and then put some nonsense in my `.emacs` like

```lisp
(load-file
 (concat (car (split-string (getenv "GOPATH") ":"))
  "/src/golang.org/x/tools/cmd/guru/go-guru.el")```

**Comment by kostya-sh** [comment]
go-guru.el from golang.org/x and go-guru.el from MELPA are identical: https://www.diffnow.com/?report=u7t18

Most likely you have an old version of guru program that does not support JSON output. MELPA snapshot version of the go-guru.el is guaranteed to work only with the latest version of guru. Try running `go get -u golang.org/x/tools/cmd/guru` (note `-u` flag).

**Comment by dominikh** [comment]
No response in a few months, and go-guru.el no longer lives in x/tools but in https://github.com/dominikh/go-mode.el instead. This issue can be closed.
