### ISSUE TITLE
doc: improve example coverage

### ISSUE THREAD

**Issue by ccirello** [golang/go#16360]
I'd like to resume expanding the documentation with more examples. After some discussion offline and previous experiences, such [17295](https://go-review.googlesource.com/c/17295/) and [13926](https://go-review.googlesource.com/c/13926/), I have mapped potential packages that could use some work on example in documentation.

Also, I'd like to suggest some aspirational guidelines about how far should an example go:

1 - Examples should be able to convey the intention of the package or some subset of its interface. Or, in other terms, intention revealing package or type level examples are preferred over function level examples. Exception being, of course, functions whose functionality are entirely self-contained, e.g. `crypto/sha1.Sum`.

2 - The goal for examples is to reveal intention first; to be a reusable snippet of code later second. I am not sure how to phrase this, but in the end, we do not want to promote a copy'n'paste culture out of the documentation.

3 - In the process of adding examples, perhaps add link to wiki, blog or external resources to help novices to bridge occasional lack of context.

4 - Be careful in not inducing abstraction decisions in the process of making easy examples - prefer simple examples over easy ones.

I think it is a good idea to open issues for each one of these packages, and discuss them individually. Not all of them are missing examples, but could have a more complete set.

- compress/flate ([30162](https://go-review.googlesource.com/#/c/30162/))
- encoding/json ([29611](https://go-review.googlesource.com/#/c/29611/))
- [x] bytes ([25062](https://golang.org/cl/25062/))
- [x] compress/bzip2 ([25173](https://golang.org/cl/25173/))
- [x] compress/gzip ([29218](https://golang.org/cl/29218/))
- [x] context ([26930](https://golang.org/cl/26930/) [27405](https://golang.org/cl/27405/))
- [x] crypto/md5 ([29375](https://go-review.googlesource.com/#/c/29375/))
- [x] crypto/sha1 ([29375](https://go-review.googlesource.com/#/c/29375/))
- [x] crypto/sha256 ([29375](https://go-review.googlesource.com/#/c/29375/))
- [x] encoding/hex ([28482](https://golang.org/cl/28482/) and #11254)
- [x] encoding/pem ([31137](https://go-review.googlesource.com/#/c/31137/))
- [x] go/format ([26696](https://golang.org/cl/26696/))
- [x] image/draw ([29443](https://go-review.googlesource.com/#/c/29443/))
- [x] image/png ([28992](https://golang.org/cl/28992/))
- [x] index/suffixarray ([27433](https://golang.org/cl/27433/))
- [x] math/cmplx ([30554](https://golang.org/cl/30554/))
- [x] mime/quotedprintable ([25575](https://golang.org/cl/25575/))
- [x] net/http/cookiejar ([27993](https://golang.org/cl/27993/))
- [x] net/http/httptrace ([27398](https://golang.org/cl/27398/))
- [x] os ([27443](https://golang.org/cl/27443/) [27996](https://golang.org/cl/27996/) [25571](https://golang.org/cl/25571/) [28963](https://golang.org/cl/28963/))
- [x] os/exec ([29150](https://go-review.googlesource.com/#/c/29150/))

Edit: Removed packages that have not been worked. Let's focus fixing bugs on this cycle and resume example efforts for Go1.9 cycle.
- compress/lzw
- encoding/ascii85
- encoding/asn1
- expvar
- fmt 
- hash/adler32
- hash/crc64
- hash/fnv
- image/color
- image/color/palette
- image/gif
- image/jpeg
- math
- net/http/cgi
- net/http/pprof
- net/rpc
- net/rpc/jsonrpc
- net/textproto
- os/user
- regexp/syntax
- testing/iotest
- testing/quick
- unicode/utf16

//cc: @adg

**Comment by adg** [comment]
Looks great to me. Added the 'Unplanned' milestone because these are not tied to a specific release. Added the 'HelpWanted' label as this is something anyone can work on.

Thanks for the list!

**Comment by ccirello** [comment]
Welcome - I'm going to start working on at least few of them.

**Comment by RobbieMcKinstry** [comment]
Hi! I'd love to contribute to this. Is there anything in particular you would like home @ccirello? :)

**Comment by ccirello** [comment]
@RobbieMcKinstry contributions are always welcome. I suggest you looking for the package you care most or is most knowledgeable about and start with it. If you find something that's not in the list above, it won't be a problem - go ahead and work on it.

**Comment by kavirajk** [comment]
@ccirello Great idea. I'd love to contribute whatever I can. +1

**Comment by bradfitz** [comment]
There have been a ton of examples added to tip (for Go 1.8) so far. I'm very happy about this.

That said, I think we should take a break for the next few months, until the Go 1.9 cycle opens up again. There's a shortage of reviewer time at the moment and I'd like everybody to focus on open bugs instead of example documentation reviews.

**Comment by ccirello** [comment]
Makes sense. I am going to update the list with the completed work, and move away with what's not done yet, and close the issue. We can always open a new issue with a newer up to date list during Go1.9 cycle
