### ISSUE TITLE
doc/asm: need details for s390

### ISSUE THREAD

**Issue by robpike** [golang/go#16362]
The assembler document has a section at the end summarizing architecture-dependent details. It needs one for the new IBM 390 port.

This must be done for the 1.8 release.

**Comment by mundaym** [comment]
I'll take this (I can't assign issues).

**Comment by robpike** [comment]
Thanks. Please send me the review.

**Comment by robpike** [comment]
Hmmm, when I wrote it was needed for the 1.8 release, I meant 1.7. Is it too late?

**Comment by mundaym** [comment]
I can write something up this evening. I guess since it's a documentation change we should be ok?

**Comment by bradfitz** [comment]
More docs are fine for 1.7.
