### ISSUE TITLE
cmd/compile: compile taking a long time for large computed struct literals

### ISSUE THREAD

**Issue by mpvl** [golang/go#16361]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
tip

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Run the attached file.
[main.go.txt](https://github.com/golang/go/files/362379/main.go.txt)

4. What did you expect to see?
Sub-second compile times.

5. What did you see instead?
16s+ compile times.

**Comment by ianlancetaylor** [comment]
CC @randall77 @josharian

**Comment by randall77** [comment]
@dr2chase

**Comment by dr2chase** [comment]
I tried the faster-phi-location patch (since I had it immediately at hand) and it was no help at all.
Profile says that 70% of the time is in regalloc.
