### ISSUE TITLE
cmd/vet: unable to detect unreachable code

### ISSUE THREAD

**Issue by pi** [golang/go#16370]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7rc1 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/work/go/
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=c:\temp\go-build108228690=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
go tool vet -unreachable main.go
```go
// main.go
package main
const flag = false
func main() {
	if flag {
		println("<<unreachable code>>")
	}
}
```

4. What did you expect to see?
a warning from vet

5. What did you see instead?
no warnings

**Comment by josharian** [comment]
I don't think we'd want vet to complain about such code. That's a fairly typical way to add debugging code, particularly in hot functions where you can't accept any runtime overhead when not debugging.

**Comment by pi** [comment]
It turns out that it is impossible to determine what code was eliminated?
```go
package main
const erraneous = (1 << 0) - 1
func main() {
	if erraneous == 1 {
            println("dead code")
	}
}
```
Code is silently eliminated by the compiler. And no warnings from vet.
Maybe it makes sense to add `-report-eliminated-code` flag to the compiler or vet? Just an idea.

**Comment by josharian** [comment]
We try fairly strenuously to avoid flags.

**Comment by robpike** [comment]
Working as intended, as @josharian explained.
