### ISSUE TITLE
doc: Go 1.7 release notes contains incorrect information about ppc64x instruction set usage

### ISSUE THREAD

**Issue by laboger** [golang/go#16372]
The draft of the Go 1.7 release notes contains incorrect information concerning the instruction set requirements for ppc64 BE.

New in Go 1.7 is that power8 instructions are now used for ppc64le.  ppc64 big endian maintains compatibility with power5, as described in #16004.

**Comment by bradfitz** [comment]
@robpike, @ianlancetaylor, not Go 1.7?

**Comment by ianlancetaylor** [comment]
Thanks for noticing, sent https://golang.org/cl/24915.
