### ISSUE TITLE
x/tools/cmd/goimports: add configuration mechanism for ignore list

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16386]
Per the golang-nuts thread (https://groups.google.com/forum/#!msg/golang-nuts/in9IVmPc_fQ/BO4wzOylCAAJ), goimports should have a configuration mechanism to permit designated ignored directories.

**Comment by pi** [comment]
Please make an unified mechanism. Then other src-scanning tools could also use it.

**Comment by bradfitz** [comment]
@pi, which other ones? Who should I talk to? Does one already exist?

**Comment by pi** [comment]
godoc for example;
in analysys/analysys.go:
```
	// Enumerate packages in $GOPATH.
	for i, dir := range filepath.SplitList(build.Default.GOPATH) {
		root := filepath.Join(dir, "src") + string(os.PathSeparator)
....
```
And I doubt you should talk to anyone. You boss ;)

**Comment by thomasf** [comment]
@bradfitz  the other src tool that I use quite a bit is gorename.. It maybe takes about a minute to run it  and it spews out errors about C code which isn't used by any Go code at all.. I'll guess that the answer of which source tool needs speed improvements differ depending on who uses what often.

(and... thanks for the very much speedier goimports)

**Comment by bradfitz** [comment]
@thomasf, I filed #16427 to track that. Let's move any discussion there.
