### ISSUE TITLE
fmt: Scanf misses last character with io.EOF

### ISSUE THREAD

**Issue by dsnet** [golang/go#16393]
Commit 6520da6ed5241b0383d50a286b4be0da70dc352b caused a regression where the last character in a string would be dropped if it was accompanied by an io.EOF.

Consider the following test:
```go
func main() {
    r := iotest.DataErrReader(strings.NewReader("hello"))
    var s string
    fmt.Fscanf(r, "%s", &s)
    fmt.Println(s)
}
```

On `1.6.2`, this prints `"hello"`.
On `1.7rc1`, this prints `"hell"`

**Comment by dsnet** [comment]
Fix is [CL/24981](https://go-review.googlesource.com/#/c/24981/)

**Comment by pi** [comment]
It is correct to return both data and EOF in one call? From io.EOF doc:
EOF is the error returned by Read when no more input is available. Functions should return EOF only to signal a graceful end of input. If the EOF occurs unexpectedly in a structured data stream, the appropriate error is either ErrUnexpectedEOF or some other error giving more detail.

**Comment by robpike** [comment]
Yes, it is correct to return data and EOF in one call, although the situation is unfamiliar to many and is often mishandled.

**Comment by pi** [comment]
Thanks for clarification.

**Comment by ianlancetaylor** [comment]
CC @martisch
