### ISSUE TITLE
runtime: re-enable TestCgoCallbackGC flaky on FreeBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16396]
I see a number of recent TestCgoCallbackGC flakes on FreeBSD

amd64:
https://build.golang.org/log/c47d9b4fe69df9c91af66122e7633f77cb623794
https://build.golang.org/log/2c93bb5f172cf8082a80bd567628bcea4f437c20
https://build.golang.org/log/92ad760a01e814bb0021486856b4d3123a4a11b7

386:
https://build.golang.org/log/47a3e8462838b94a69459a3e56de5ea852b5e86e
https://build.golang.org/log/d6604ec508fd4166c46bd6fb3e04a4b0fb945959
https://build.golang.org/log/85e6aab2ff5692ee7372f03dd187fc555f8a685c

Most are:

```
--- FAIL: TestCgoCallbackGC (93.64s)
    crash_test.go:105: testprogcgo CgoCallbackGC exit status: signal: quit (core dumped)
    crash_cgo_test.go:61: expected "OK\n", but got:
FAIL
FAIL    runtime 147.968s
```

Some are:

```
--- FAIL: TestCgoCallbackGC (102.14s)
    crash_test.go:105: testprogcgo CgoCallbackGC exit status: signal: quit (core dumped)
    crash_cgo_test.go:61: expected "OK\n", but got:
panic: test timed out after 5m0s

goroutine 232809 [running]:
panic(0x81f2c80, 0x39220b20)
    /tmp/workdir/go/src/runtime/panic.go:500 +0x334 fp=0x392b1fa0 sp=0x392b1f5c
testing.startAlarm.func1()
    /tmp/workdir/go/src/testing/testing.go:918 +0xef fp=0x392b1fe0 sp=0x392b1fa0
runtime.goexit()
    /tmp/workdir/go/src/runtime/asm_386.s:1612 +0x1 fp=0x392b1fe4 sp=0x392b1fe0
created by time.goFunc
    /tmp/workdir/go/src/time/sleep.go:154 +0x30

goroutine 1 [chan receive]:
runtime.gopark(0x8246704, 0x39632d30, 0x8224051, 0xc, 0x17, 0x3)
    /tmp/workdir/go/src/runtime/proc.go:259 +0x12d fp=0x39233cd4 sp=0x39233cc0
runtime.goparkunlock(0x39632d30, 0x8224051, 0xc, 0x17, 0x3)
    /tmp/workdir/go/src/runtime/proc.go:265 +0x45 fp=0x39233cf0 sp=0x39233cd4
...
```

Why did these start recently?

**Comment by ianlancetaylor** [comment]
I think these are other versions of #15658 and #16136.  There is something wrong on FreeBSD but I don't understand what it is and I have not been able to recreate it myself.

If anybody has a FreeBSD machine I can ssh into that would help.

**Comment by bradfitz** [comment]
Our FreeBSD builders run on GCE. I can create you an instance there.

**Comment by ianlancetaylor** [comment]
> Our FreeBSD builders run on GCE. I can create you an instance there.

That would help if you have time.  Thanks.

**Comment by bradfitz** [comment]
@ianlancetaylor, done. Emailed you details.

**Comment by ianlancetaylor** [comment]
I think I was incorrect in thinking that this was related to the other FreeBSD problems.  The other FreeBSD problems are less frequent, and I have not been able to recreate them at all.

I now think this is the same as issue #13926: a problem that arises when there are many simultaneous callbacks from C to Go, which is exactly what the CgoCallbackGC test case does.  The problem is that on FreeBSD you can surprisingly large delays during the callback.  My theory is that when enough of those delays occur, the test times out.  That is consistent with the failures reported on the builder, which are in all cases the program crashing from SIGQUIT; SIGQUIT is sent by the runtime test harness when the test program runs for more than 1 minute (`runTestProg` in runtime/crash_test.go).

Working on a patch.

**Comment by ianlancetaylor** [comment]
`TestCgoCallbackGC` is still failing on FreeBSD on the builders.  The change did not fix it, at least not completely.

**Comment by adg** [comment]
We may just have to punt on this for Go 1.7, which should be okay since IIUC this is not a regression in Go 1.7. (Or is it?)

**Comment by ianlancetaylor** [comment]
To the best of my knowledge this is not a regression in 1.7.

**Comment by bradfitz** [comment]
@adg, @broady, should we at least document this as a known issue in the release notes for Go 1.7? And then punt this to Go 1.8 for actually fixing.

It'd be a pity to ship something with known crashes for a "first class port". I'd rather warn FreeBSD users about this bug so they don't deploy something with cgo callbacks in production and see crashes.

**Comment by adg** [comment]
Agree, sounds like the right move.

**Comment by broady** [comment]
Maybe, but if it's not a regression then the release notes really aren't the place for this.

We could say something like "Reduced runtime crashes on FreeBSD, but some are still present."

**Comment by bradfitz** [comment]
I don't think it matters whether it's a regression. Had I know about this in Go 1.6 I would have also argued we need a dedicated "Known Issues" section in our release notes, especially for first class ports.

Or: we demote FreeBSD to no longer be a first-class port.

**Comment by broady** [comment]
I suppose it wasn't known at the time, so we couldn't document as a known issue. SGTM.

Perhaps we should also amend the 1.6 release notes (with a date for said addendum).

**Comment by stevenh** [comment]
Does anyone have any tips on reproducing this?
I'm currently running with the following and haven't seen the test take over 7 seconds.
```
setenv GOMAXPROCS 2
runtime> sh -c 'while true; do go test -run=TestCgoCallbackGC -cpu=1,2,4; sleep 1; done'
```

Test machine is dual E5-2640 @ 2.50GHz running FreeBSD 11.0-RELEASE-p3 go version go1.7.3 freebsd/amd64

**Comment by stevenh** [comment]
Also testing this on 10.1 (metal) and 10.2 (gce VM) currently nothing longer than 8 seconds, tests are still running.

**Comment by stevenh** [comment]
Test has been running in a loop on three different machines for over 28 hours not a single failure so far.

**Comment by ianlancetaylor** [comment]
@stevenh Which version of FreeBSD?  It's possible that changes to the kernel scheduler have eliminated the problem.  As it says in https://golang.org/cl/25047 the problem was much worse on FreeBSD than on GNU/Linux for some reason.

Or of course it's possible that something we've changed in the runtime has fixed the problem, though I don't know what that could be.

**Comment by stevenh** [comment]
I tested on 10.1 (metal), 10.2 (GCE) and 11 (metal) all under golang 1.7.3.

With all machines clearing well over 24 hours (coming up to 32 now) on tight loop running this test I think it may be good to remove the [Skip](https://github.com/golang/go/commit/604efe128195c1fbb1d14cbd36bf681fcff723a3) for 1.8 to see if we can confirm it is indeed no longer an issue.

**Comment by stevenh** [comment]
All three machines have now been running the test in loop for over 3 days no errors.

**Comment by ianlancetaylor** [comment]
Thanks for trying it so thoroughly.  Sounds like this issue can be closed.

**Comment by bradfitz** [comment]
@ianlancetaylor, did you mean to close this? It sounds like we need to at least remove the `t.Skip` for this test on FreeBSD.

**Comment by paulzhol** [comment]
Hello,
I've starting running builds with CGO_ENABLED=1 on freebsd-arm-paulzhol and it fails consistently:
```
ok  	regexp/syntax	4.107s
--- FAIL: TestCgoCallbackGC (180.11s)
	crash_test.go:105: testprogcgo CgoCallbackGC exit status: exit status 2
	crash_cgo_test.go:61: expected "OK\n", but got:
		SIGQUIT: quit
		PC=0x20263cd0 m=0
		signal arrived during cgo execution
		
		goroutine 166 [syscall, locked to thread]:
		runtime.cgocall(0xc0c78, 0x30a7d7c4, 0x0)
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/cgocall.go:131 +0x130 fp=0x30a7d7ac sp=0x30a7d790
		main._Cfunc_foo()
			_/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/testdata/testprogcgo/_obj/_cgo_gotypes.go:176 +0x38 fp=0x30a7d7c0 sp=0x30a7d7ac
		main.CgoCallbackGC.func2(0x30a5a040)
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/testdata/testprogcgo/callback.go:81 +0x14 fp=0x30a7d7d4 sp=0x30a7d7c0
		runtime.goexit()
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/asm_arm.s:998 +0x4 fp=0x30a7d7d4 sp=0x30a7d7d4
		created by main.CgoCallbackGC
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/testdata/testprogcgo/callback.go:83 +0xd8
		
		goroutine 1 [chan receive]:
		main.CgoCallbackGC()
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/testdata/testprogcgo/callback.go:86 +0x114
		main.main()
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/testdata/testprogcgo/main.go:34 +0x1ac
		
		goroutine 17 [runnable, locked to thread]:
		runtime.goexit()
			/tmp/gobuilder/freebsd-arm-paulzhol-6ceba5d5e85b/go/src/runtime/asm_arm.s:998 +0x4
```

System is an ALLWINNER A20 running FreeBSD 11.0-RELEASE-p2. I've noticed CGO_ENABLED was off by default because the bootstrap 1.4.3 compilers need to be built with CGO_ENABLED=0.

**Comment by ianlancetaylor** [comment]
@paulzhol This issue is closed and the problem you are reporting has different symptoms.  Please open a new issue with the details.  Thanks.

**Comment by paulzhol** [comment]
@ianlancetaylor I've opened #18811 but I do have the following in my log which look like the "Most are:" example in the original issue:
```
ok      regexp/syntax   4.205s
--- FAIL: TestCgoCallbackGC (204.17s)
        crash_test.go:106: testprogcgo CgoCallbackGC exit status: signal: quit
        crash_cgo_test.go:66: expected "OK\n", but got:
FAIL
FAIL    runtime 427.836s
ok      runtime/debug   0.088s
```
But the builder failed to push that:
```
2017/01/27 02:25:42 Failed: exit status 1
Build complete, duration 41m53.837957541s. Result: error: exit status 1
 RunTime:41m53.837957541s Builder:freebsd-arm-paulzhol PackagePath:]
2017/01/27 02:25:45 Post https://build.golang.org/result?builder=freebsd-arm-paulzhol&key=1afbfdbb5478d3637b69643e3da41377&version=1: dial tcp: lookup build.golang.org on 192.168.XXX.XXX:53: server misbehaving
```
