### ISSUE TITLE
cmd/compile: converting []byte to string could re-use non-escaping memory

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16408]
In a program like:

```go
package alloc_test

import "testing"
        
var s = "some string to be doubled by foo"

func foo() string {
        buf := make([]byte, len(s)*2)
        copy(buf, s)
        copy(buf[:len(s)], s)
        return string(buf)
}

func BenchmarkGarbage(b *testing.B) {
        b.ReportAllocs()
        for i := 0; i < b.N; i++ {
                foo()
        }
}
```

The `string(buf)` conversion allocates memory, even though the `buf` variable should not escape, and is only used by string(buf) at the exit of the function.

This results in two allocations per call to `foo`:

```
BenchmarkGarbage-2   20000000     108 ns/op     128 B/op     2 allocs/op
```

More practically, this affects things like `filepath.Join` or `path.Join` which uses `strings.Join` (which looks like `foo` above)

I thought we had this bug open already but I can't find it.

/cc @randall77 @josharian

**Comment by randall77** [comment]
Reusing the storage of the byte slice in string([]byte) should be doable.
The escape analysis pass already provides the escape info we need, I believe.
The additional check would be to make sure that the []byte is not modified after the string cast by the function being compiled.  I'm not sure what mechanism we'd need for that.  Maybe just an imminent return after the cast would catch most cases we want.

**Comment by bradfitz** [comment]
> Maybe just an imminent return after the cast would catch most cases we want.

I suspect so.

**Comment by nuss-justin** [comment]
This is #6714 :-)

**Comment by bradfitz** [comment]
@nuss-justin, indeed! Thanks. Closing this as a dup.
