### ISSUE TITLE
error in rendering a template

### ISSUE THREAD

**Issue by erkidhoxholli** [golang/go#16401]
1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
OS = Windows 7 x64 
GOARCH = and64

3. What did you do?
I was trying to include a modal (materializecss) into a template and then using this modal everywhere.

step1. defining the modal into a template
{{ define "auth" }}
   ... inside here I had some go template code which was already commented but for some strange reason did not let me render the template at all
{{ end }}

step2. using the template
{{ template "auth" }}

step3. parsing the template
`t, _ := template.ParseFiles("views/index.html", "views/partials/_head.html", "views/partials/_footer.html", "views/partials/_auth.html")
`
step4: execution 
`t.Execute(w, data)`

4. What did you expect to see?
I was expected to see the auth template(modal) after clicking a particular button but nothing showed.I viewed the source code and noticed that the code was interrupted at that part where there was commented golang template code

5. What did you see instead?
Just the other templates.

6. How did I fix this ?
I just removed the commented golang code from the template and it worked

**Comment by bradfitz** [comment]
I don't think there's enough information here to help. We need to be able to reproduce any errors.

For now, let's move this to the forum. See https://golang.org/wiki/Questions

In the future, be sure to check your errors and not assign them to `_`, especially in bug reports.
