### ISSUE TITLE
Runtime generate code and load it, generics

### ISSUE THREAD

**Issue by lobster2012-user** [golang/go#16403]
1.I would like to be able to load  packages ( plug-ins ) in runtime , to seek, to create objects for specific interfaces. I would like to dynamically generate code and use it (or|and to store)
(as in C#)
2. I would like to use templates or generics
(as in C#,C++)
(i know about interface {})

Do the developers plan to implement these features ?

Hello from Russia 
Thanks
Sorry for my english.

**Comment by ianlancetaylor** [comment]
Hi, we don't use the issue tracker to ask questions.  Please ask on a mailing list instead.  See https://golang.org/wiki/Questions .  Thanks.  I'm going to close this issue.

In this case, see https://golang.org/s/execmodes .  I'm not aware of anybody actively working on the proposed plugin package.

**Comment by lobster2012-user** [comment]
Thanks. Sorry.
