### ISSUE TITLE
Go 1.3 

### ISSUE THREAD

**Issue by semafor** [golang/go#16406]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`1.3`

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu on arm64 and powerpc64

3. What did you do?
https://play.golang.org/p/wFcYsDDbPt

4. What did you expect to see?
`<date> my_file.go:<lineno> hello world`

5. What did you see instead?
`<date> linux64.S:140 hello world` *
`<date> sysv.S:113 hello world` † 
_\* on ppc64
† on arm64_

**Comment by davecheney** [comment]
I'm sorry, but Go 1.3 supported neither of these platforms. Perhaps you are using gccgo?

In any case, please upgrade to the latest point release of Go 1.6.x as previous versions are not supported.

**Comment by semafor** [comment]
Okay.
