### ISSUE TITLE
net/http: documentation for interaction between http2 imported and http pkgs.

### ISSUE THREAD

**Issue by gaillard** [golang/go#16412]
Just requesting some documentation for the case when someone does something like

```
hs := &http.Server{Handler: thehandler}
if err := http2.ConfigureServer(hs, &http2.Server{}); err != nil {
    //handle
}
if err := hs.Serve(existingTLSListener); err != nil {
    //handle
}
```

and has therefore vendored in the http2 package. How does this interact with the bundled http2 in the http package?

**Comment by gaillard** [comment]
Any kind of one sentence answer here before documentation is worked on would be highly valued if anyone has the time

**Comment by bradfitz** [comment]
If you import golang.org/x/net/http2 and use it to register the client or server, the (presumably newer) http2 package you imported wins.

The bundled copy is only used as a default.

**Comment by gaillard** [comment]
Much appreciated, but which in the example above is doing the "registering"?

**Comment by bradfitz** [comment]
http2.ConfigureServer

**Comment by gaillard** [comment]
thanks !!
