### ISSUE TITLE
ARMv6 packages missing for Go 1.6.3

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#16429]
It appears that no packages were publishes for ARMv6 for Go 1.6.3. Checking the download page; https://golang.org/dl/, and https://storage.googleapis.com/golang, there are [packages for Go 1.6.2](https://storage.googleapis.com/golang/go1.6.2.linux-armv6l.tar.gz), but not for 1.6.3

Are there plans to provide packages, or should we build from source?

Relates to https://github.com/docker/docker/pull/24811

**Comment by quentinmit** [comment]
@broady Can we build ARMv6 binaries?

**Comment by bradfitz** [comment]
We can. He just didn't notice some error earlier and forgot to upload them. cmd/release needs a summary at the end to say which ports built.

**Comment by broady** [comment]
They're up there. I'm building 1.7rc2 binaries too.

**Comment by thaJeztah** [comment]
Thanks for the quick response, really appreciated :heart:

**Comment by DieterReuter** [comment]
@broady glad to see your fast response to resolve this issue! Well done. 👍
