### ISSUE TITLE
net/http: ServeFile generates wrong links in a directory when a path doesn't end in a slash

### ISSUE THREAD

**Issue by solarsea** [golang/go#16424]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
Windows, amd64

3. What did you do?

I ran the program with the directory structure "c:/temp/dir1/file.txt" and opened 
both "http://localhost/dir1/" and "http://localhost/dir1" (without trailing slash)

/-------------------------------------------------------------
package main

import (
	"net/http"
)

func main() {
	http.ListenAndServe(":80", http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		http.ServeFile(rw, req, "C:/temp")
	}))
}
/-------------------------------------------------------------

4. What did you expect to see?

Same html output for both.

5. What did you see instead?

The URL without the trailing slash shows correct directory content but generates a wrong link in the form of "http://localhost/file.txt" instead of "http://localhost/dir1/file.txt"

**Comment by davecheney** [comment]
rfc 2616 and 4918 are mute on what happens when you request a representation of a collection (rfc 4918 terms for a directory) without the trailing slash. To be explicit, rfc 4918 defines

    http://localhost/dir/

is a collection

    http://localhost/dir 

is not defined (by my reading). There are two possibly solutions I can seeL

- `/dir` should issue a 30x redirect to `/dir/`
- `/dir` should return a 404, the name of there resource is `/dir/`

**Comment by solarsea** [comment]
It seems that option a is implemented already - https://golang.org/src/net/http/fs.go?s=14478:14535#L379 but it is explicitly turned off in the case of ServeFile

**Comment by davecheney** [comment]
@solarsea i'm sorry i don't understand, can be more explicit please.

**Comment by solarsea** [comment]
ServeFile uses serveFile internally - https://golang.org/src/net/http/fs.go#L353. The later has a parameter called 'redirect' that when true already implements the behavior that you suggest - that /dir should redirect to /dir/

**Comment by solarsea** [comment]
I traced the implementation back to https://github.com/golang/go/commit/fa6022607351616844bb063c312f52bc7912cbc2 by @rsc where 'serveFile' is named 'serveFileInternal'

**Comment by solarsea** [comment]
I think that a straightforward fix is to drop the 'redirect' parameter of serveFile(...) altogether and therefore unify ServeFile(...) and FileServer(...) behaviors

**Comment by 0xmohit** [comment]
This appears to be the same as https://github.com/golang/go/issues/13996

@solarsea Could you verify this with go1.7rc?

**Comment by bradfitz** [comment]
Yeah I think this is a dup.

**Comment by solarsea** [comment]
It is a dup, but the fix looks weird. It is adding corrective code, instead of fixing it by removal of the defective flag.

**Comment by bradfitz** [comment]
Glad to hear it's fixed. Feel free to send a change if you have something which makes the code more clear. I'm just happy we have a test for it now.
