### ISSUE TITLE
mime/multipart: CreateFormFile does not allow setting the Content-Type for the file.

### ISSUE THREAD

**Issue by pwhelan** [golang/go#16425]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

Go 1.6.2

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

I used mime/multipart CreateFormFile but was unable to set the Content-Type for the part.

4. What did you expect to see?

Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

xxxxxxxxxxxxxxxxxxxxxxx

5. What did you see instead?

Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: application/octet-stream

xxxxxxxxxxxxxxxxxxxxxxx

**Comment by bradfitz** [comment]
Use CreatePart.

CreateFormFile is a very thin wrapper around CreatePart. Click https://golang.org/pkg/mime/multipart/#Writer.CreateFormField and then click the CreateFormFile heading to see its source code.

**Comment by pwhelan** [comment]
I did that. It just seems to me like an absolutely necessary feature to make the method useful at all.

**Comment by bradfitz** [comment]
Where do you draw the line? Just content type? Content type and disposition? And Filename? All permutations thereof? Method for each?

Everybody's opinions on the most useful parts vary, I'm sure.

If you come back with some data suggesting that most users need a certain API which we don't provide and everybody is doing a tedious thing we could make easier, then I think we can make changes.

See https://medium.com/google-cloud/analyzing-go-code-with-bigquery-485c70c3b451#.9mr0dcybl for how to do some SQL queries against all code on Github.

/cc @campoy

**Comment by pwhelan** [comment]
will do.
