### ISSUE TITLE
cmd/compile: ICE after regular error on [...]byte("string")

### ISSUE THREAD

**Issue by josharian** [golang/go#16428]
```go
package p

var (
	 b = [...]byte("abc")
	 s = len(b)
 )
```

compiled yields:

```
bad.go:4: use of [...] array outside of array literal
bad.go:5: internal compiler error: NumElem array [...]byte does not have bound yet
// stack trace omitted
```

This is an easy fix -- just check nerrors before calling NumElem. This is a reminder issue to fix for 1.8.

**Comment by rsc** [comment]
Isn't the "internal compiler error" supposed to be suppressed if there has already been some other error printed?
