### ISSUE TITLE
go/types: Info.Types does not map ast.IfStmt.Cond

### ISSUE THREAD

**Issue by hydroflame** [golang/go#16422]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.3 darwin/amd64

3. What did you do?
 - Parse the AST for any program with any `if` statement
 - Walk the tree until you find an `*ast.IfStmt` node
 - Try to find the type of the expression via the `types.Info` struct you processed.

4. What did you expect to see?
An entry of type types.Basic with kind bool.

5. What did you see instead?
no entry in the map

6. Extra
This is quite obviously not necessary as the types.Type of any ast.IfStmt.Cond is obviously types.Basic (with kind bool) but this complicates at least one piece of my code.

**Comment by ianlancetaylor** [comment]
Can you provide a complete standalone example (perhaps a program plus an input file) showing the problem you are describing?  Code is much easier to understand than text.  Thanks.

**Comment by hydroflame** [comment]
Ok turns out I can't reproduce the bug with a playground example (it compiles fine but the bug doesn't show up) I'll reopen the issue if I can find a isolated example where it didn't parse correctly.
