### ISSUE TITLE
Something wrong in time.Parse()

### ISSUE THREAD

**Issue by Frozen-Shadow** [golang/go#16437]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
    1.6.2 

2. What operating system and processor architecture are you using (`go env`)?
    windows 10/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

    I was learning golang this week.When I using time.Parse() to format time string,I tried "2006-01-02      15:04:09"~"2006-01-02 15:04:00" for fun.I fund some bugs in this function,but I can't fix them...Sorry...
    You can see the program in  [play.golang.org](https://play.golang.org/p/c2Yqa5tRZa)

4. What did you expect to see?
    Can we use "Y-m-d" for the layout ?

5. What did you see instead?

**Comment by bradfitz** [comment]
Your layout is wrong. Please re-read the time package documentation for its format.

For general questions and language learning help, see https://golang.org/wiki/Questions

**Comment by Frozen-Shadow** [comment]
The question is I use the **wrong layout** and I got the **wrong value** and **nil** 

```go
str :="2016-07-20 02:30:00"
fmt.Println(str)
tm6,err:=time.Parse("2006-01-02 15:04:06",str)
fmt.Println(tm6,err)
tm3,err:=time.Parse("2006-01-02 15:04:03",str)
fmt.Println(tm3,err)
tm2,err:=time.Parse("2006-01-02 15:04:02",str)
fmt.Println(tm2,err)

//resault
2016-07-20 02:30:00
2000-07-20 02:30:00 +0000 UTC <nil>
2016-07-20 00:30:00 +0000 UTC <nil>
2016-06-30 02:30:00 +0000 UTC <nil>
```

**Comment by minux** [comment]
Because it's impossible for time.Parse to detect errors in the layout
without using heuristics.
