### ISSUE TITLE
net/smtp: timeout support similar to net.DialTimeout

### ISSUE THREAD

**Issue by harlow** [golang/go#16436]
Similar to the addition of `DialTimeout` to `net` package:
https://github.com/golang/go/issues/240
https://github.com/golang/go/blob/964309e2fdd7f1e1b7b7e0c601446dc85d5d41bf/src/pkg/net/dial.go#L78

Would be nice to add some symmetry with `DialTimeout` for `smtp` package:
https://github.com/golang/go/blob/master/src/net/smtp/smtp.go#L43-L45

**Comment by bradfitz** [comment]
Sorry, the SMTP package is frozen. Please fork it and add features on Github. We should have never included it in the standard library. 

I'll keep this bug open to document that it's frozen though. We'll fix bugs but not add features.

**Comment by harlow** [comment]
OK sounds good - thanks for the quick reply. I worked around it by passing in the net client:

```go
// Dial the tcp connection
conn, err := net.DialTimeout("tcp", addr, 10*time.Second)
if err != nil {
    return "", err
}

// Connect to the SMTP server
c, err := smtp.NewClient(conn, host)
if err != nil {
    return "", err
}
defer c.Quit()
```
