### ISSUE TITLE
x/tools/cmd/goimports: doesn't work for Go 1.4 and below

### ISSUE THREAD

**Issue by kortschak** [golang/go#16434]
I don't know if this is considered a concern, but https://github.com/golang/tools/commit/edf8e6fef861d8c5ecc9e394b0146d6ebba57795 breaks goimport use on go version < 1.5 because of the absence of the runtime/trace package before 1.5.

/cc @bradfitz

**Comment by bradfitz** [comment]
This is fixable, but we try to only support three releases at a time (the dev release, and last two stable ones), which means supporting things anywhere from 12-18 months.

https://build.golang.org only runs tests for Go 1.5 and above, so we have no visibility into Go 1.4 and below breakages at the moment. (which was an explicit decision earlier when we were deciding what to build)  And shortly even Go 1.5 will become unsupported.

I'd take a change if you want to send one, but without a test keeping it working, it might regress again.

**Comment by kortschak** [comment]
I'm not particularly fussed. You will have noticed where we've seen this and in that that any requirement for 1.4 will go away when 1.7 is released since we also only support 3 releases at most.

You're welcome to close this if it's not important to you.

(sorry for the mangled issue name - swapped thought and failed to return).

**Comment by bradfitz** [comment]
Okay, will close. Anybody else who is fussed can send a CL.
