### ISSUE TITLE
go get goimports fails on go 1.4.2

### ISSUE THREAD

**Issue by jonlawlor** [golang/go#16444]
1. What version of Go are you using (`go version`)?
1.4.2

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.4.2.linux.amd64"
GOTOOLDIR="/home/travis/.gimme/versions/go1.4.2.linux.amd64/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
go get golang.org/x/tools/cmd/goimports

4. What did you expect to see?
successful install

5. What did you see instead?
package runtime/trace: unrecognized import path "runtime/trace"

It appears to be caused by https://go-review.googlesource.com/#/c/25001/

I know that 1.4.2 is out of date.  We ran into this while doing CI on the gonum/internal package, and we are planning on dropping support for it entirely.  However, goimports is integrated into some IDEs and this might lead to some breakage, so I figured I would point it out.

**Comment by bradfitz** [comment]
Dup of #16434.

Also, gonum itself no longer supports Go1.4: https://github.com/gonum/internal/pull/33/commits/518f259eb2a573d42d591c29afb87b39c14f3845

**Comment by jonlawlor** [comment]
Oops, sorry.
