### ISSUE TITLE
Typo in Go memory model doc

### ISSUE THREAD

**Issue by FZambia** [golang/go#16440]
Hello, looks like there is a typo in docs – in Go memory model document the word `serialize` used instead of `synchronize` in 2 places: [first line](https://github.com/golang/go/blob/bc33dd7432369b3abd2a6fd75cb57d6c5c3defa7/doc/go_mem.html#L29) and [second](https://github.com/golang/go/blob/bc33dd7432369b3abd2a6fd75cb57d6c5c3defa7/doc/go_mem.html#L33)

**Comment by ianlancetaylor** [comment]
It's not obvious to me that "serialize" is wrong here.  Rob wrote it so I'll let him decide.

**Comment by robpike** [comment]
It is correct as written.
