### ISSUE TITLE
x/build: migrate farmer.golang.org to LetsEncrypt before April 4th 2017

### ISSUE THREAD

**Issue by bystones** [golang/go#16442]
Going to https://farmer.golang.org/try?commit=773db5cd produces a SEC_UNKNOWN_ISSUER in Firefox 47 on Windows 8.

The exported certificate looks like this:

-----BEGIN CERTIFICATE-----
MIICljCCAX4CCQDerFGz933ozjANBgkqhkiG9w0BAQUFADANMQswCQYDVQQDEwJn
bzAeFw0xNTA0MDUyMDE0MDlaFw0xNzA0MDQyMDE0MDlaMA0xCzAJBgNVBAMTAmdv
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx5DegqvOjndHlwBtxabm
0EbgpPWwVIQM/eOELYrGCvtTPAsQCVQY74/EJBpOfl+bu37hgFU1QEJeACT6S31G
G/b1VCAKe4ltp1rZp+3RMSuvUui3C1Y4QrgN/wQY47OFJqiq9VE2adcVC1PjmIoW
5U0Wy9JaKVn15Uw+Ez2Q+RgBpRRsrdr8tPEy7k/J1hBjkxK550RVsY+nRNimNOR2
dOImNNe8G+fIUbQUQCrRG2pz9IulnfH95Wh6KDUNOIyXdNcFfQEPEIhHaHoJazXV
TQx1znsldlZLLFvw1ULBJ4WXTozP9r5vqdyBBaicqPwrCCF2x8nBsyuhNtjgW/K1
CwIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQBSBV5kt5lI6uImGLpWCh5fxeL4WECY
hXS5vnL2Z5pFoHCdOR3goHuHvNuI1J/PnjsYpnPxZAqujXlCeT1MvuVpflpP1qOb
U4mU5aedDETYUfYYeIWxdZRiqDkKg828v5YS5FM+rA3dURQnKYIWKAYw5r577Kfm
bV0aGdnWQYUoId6cySLB7fe4/R9JOAxnCqS82+WZF/oy4ONu/zquxU1qugIOzq3I
rN/faUQTZkmJr+eb5RddNEZ61wwM+sJkbkydpqw17xTSYWv2roHrMGNH41K/NlBr
WyM81JLyaoXhAT1Bh66T55eodas7nXg4U1xjolTXWZ75Cnon34VpHQzI
-----END CERTIFICATE-----

**Comment by bradfitz** [comment]
That's intentional. It's self-signed and clients of it expected a certain pinned cert.

How did you get to that URL? If by hand, this is expected.

**Comment by bystones** [comment]
It get's posted by the Gobot in Gerrit.

**Comment by bradfitz** [comment]
Show me an example. I'm pretty sure they're always "http" links.

**Comment by bystones** [comment]
You are correct, sorry for the wrong report.
It was the HTTPS Everywhere addon rewriting the URL.

**Comment by josharian** [comment]
I got sick of this. I've sent a PR to HTTPS Everywhere to fix: https://github.com/EFForg/https-everywhere/pull/8984

**Comment by bradfitz** [comment]
Actually, our self-signed cert expires "Tuesday, April 4, 2017" (and is a SHA-1 cert). It's probably time we just switched to LetsEncrypt with autocert and updated the reverse buildlets to not require the pinned cert anymore. That's just legacy from when certs were annoying.

**Comment by kevinburke** [comment]
I'm interested in working on this (was just about to open a new issue for this and tip.golang.org)

**Comment by bradfitz** [comment]
This isn't something that can be done easily without access to all the builders.
