### ISSUE TITLE
net/http: http.Server.ReadTimeout never reset in http2

### ISSUE THREAD

**Issue by grahamking** [golang/go#16450]
1. What version of Go are you using (`go version`)?
go1.7rc2
go1.6.3
go1.6 if you use http2 (custom Transport without ExpectContinueTimeout)

2. What operating system and processor architecture are you using (`go env`)?
linux_amd64

3. What did you do?

https://play.golang.org/p/7nC5EIVRCq  (change `my_cert`, `my_key` and `my_host`)
Set a `ReadTimeout` on `http.Server`. Make several requests to the server using the same client (so that the TCP conn is re-used). With http2 program exits with 'unexpected EOF' after `ReadTimeout`.

4. What did you expect to see? 5. What did you see instead?

Program should run forever.

This works:
> GODEBUG=http2client=0 go run the_file.go

This fails:
> go run the_file.go

Program exits after `ReadTimeout` because the TCP connection hits it's deadline, is closed. This means that in http2 `ReadTimeout` applies not to a single request but to the keep-alive connection.

The deadline is set here during TLS handshake: https://github.com/golang/go/blob/master/src/net/http/server.go#L1501-L1503

In http1 case the deadline is reset every request: https://github.com/golang/go/blob/master/src/net/http/server.go#L743-L751

In http2 it is never reset. I suspect the solution is to reset the deadline here: https://github.com/golang/net/blob/master/http2/server.go#L579-L602

There is a similar problem with `WriteTimeout`. The example program will hang after `WriteTimeout`.

This was fixed for http1 in #4676.

**Comment by bradfitz** [comment]
I haven't had time to investigate this yet, but if this isn't a regression from Go 1.6, it's hard to justify fixing it this late in the Go 1.7 cycle.

**Comment by bradfitz** [comment]
(I do admit that it's a regression from Go 1.5, but I'm surprised nobody has mentioned it in the last year)

**Comment by grahamking** [comment]
I agree it's strange that no-one else has mentioned it, and I did do a fair amount of searching. If you reproduce it, maybe 1.7 could add a documentation note that those timeouts are not supported on http/2 connections?

**Comment by bradfitz** [comment]
Bug is fixed in x/net/http2 now, but keeping this open until we figure out #14204 (Server.IdleTimeout) and add tests.

**Comment by bradfitz** [comment]
#14204 is sufficiently complete. Closing this one.
