### ISSUE TITLE
cmd/go: go test -coverprofile broken on 1.7rc2/OSX

### ISSUE THREAD

**Issue by 0x434D53** [golang/go#16454]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7rc2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxx/Dev/GOCODE"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7rc2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7rc2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m5/04gz8l2941vgv9_8ggx_s8_80000gn/T/go-build004510646=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?

go test -coverprofile=cover.out

4. What did you expect to see?

Correct paths to the source files in the cover.out file

5. What did you see instead?

Every path starts with is prefixed with a _ and therefore cannot be found (for example from  go tool cover -html=cover.out)

Actual output:
_/Users/xxx/dev/GOCODE/src/github.com/0x434D53/jose/jwa/signerverifier.go:18.13,22.2 3 1

 it should be:
/Users/xxx/dev/GOCODE/src/github.com/0x434D53/jose/jwa/signerverifier.go:18.13,22.2 3 1

**Comment by ianlancetaylor** [comment]
Is this a change from 1.6?

**Comment by 0x434D53** [comment]
I just checked: In go1.6.3 darwin/amd64 i have 

github.com/0x434D53/jose/jwa/signerverifier.go:18.13,22.2 3 1

as the path in the cover.out, which will work fine with the cover tool.

**Comment by davecheney** [comment]
The underscore comes from trying to use the go tool with code outside
GOPATH.

On Thu, Jul 21, 2016 at 12:32 PM, Ian Lance Taylor <notifications@github.com

**Comment by 0x434D53** [comment]
I found the issue: I have my OSX volume formatted as case insensitive: My GOPATH is unser ~/Dev/GOPATH . Most tools also from the go toolchain also work when i am in ~/dev/GOPATH - for OSX this is the same directory. So Dave is right: Go at least thinks i am not in the GOPATH and is half right/wrong.
