### ISSUE TITLE
cmd/go: check for change in custom import path repo even without import comment

### ISSUE THREAD

**Issue by jba** [golang/go#16471]
1. What version of Go are you using (`go version`)? go 1.6

This is a re-open of #10952. The issue was that a change to the form of a repo's URL would lead to an erroneous error during "go get -u". In that case, the error alluded to a custom import path even though there wasn't one.

The fix was to only perform the check if the package had an import comment. This conflates having a custom import path with having an import comment. If (a) there is a custom import path, (b) there is no import comment, and (c) the repo pointed to by the import path changes, then "go get -u" will incorrectly pull from the old repo.

The right fix is to resolve the import path to a repo URL, and compare that to the origin of the local repo.

**Comment by quentinmit** [comment]
Can you please provide sample code/setup that demonstrates this problem?

**Comment by rsc** [comment]
The bug report has enough information to reproduce the problem.
