### ISSUE TITLE
Missing zversion.go

### ISSUE THREAD

**Issue by oldwo** [golang/go#16478]
1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/386

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\WinProg\Go
set GORACE=
set GOROOT=C:\WinProg\Go
set GOTOOLDIR=C:\WinProg\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
Probably one of these caused my problem:

`go clean`
`src\clean.bat`

Now I have no clue how to get back zversion.go:

`all.bat`

> ##### Building Go bootstrap tool.
> cmd/dist
> go: open C:\WinProg\go\src\runtime\internal\sys\zversion.go: The system cannot find the file specified.
> 

`go get -tags tcl85 github.com/nsf/gothic`

> warning: GOPATH set to GOROOT (C:\WinProg\Go) has no effect
> go: open C:\WinProg\Go\src\runtime\internal\sys\zversion.go: The system cannot find the file specified.
> 

Now I need a way to get **zversion.go** back. Looking at src\cmd\dist\build.go , I cannot figure how to invoke `func install(dir string)` to exercise the `gentab` array (with a command line for the existing binaries). My Go tree comes directly from **go1.6.2.windows-386.msi** , on Windows7.

**Comment by davecheney** [comment]
Hello,

Sorry you are having problems. It looks like you started with the binary
release of Go 1.6.2 and tried to rebuild it. This won't work and you should
reinstall the binary release to correct this.

If you want to build go from source you should start with the source
distribution.

Thanks

Dave
