### ISSUE TITLE
net/http program in centos6.3 mach will be down with the special param sysctl.conf, 

### ISSUE THREAD

**Issue by zfwslf** [golang/go#16470]
Please answer these questions before submitting your issue. Thanks!

### 1. What version of Go are you using (`go version`)?
    have try 1.4 & 1.6

### 2. What operating system and processor architecture are you using (`go env`)?
    centos6.3   2.6.32-279.el6.x86_64    mach is down
    centos6.3   2.6.32-642.3.1   normal
    centos5.8   2.6.18-308.el5   normal

### 3. What did you do?
    when i connect the http server by the command of [nc -vz localhost 8080] or telnet the port of http server，and then mach will be down

### [the sysctl.conf]
    net.ipv4.tcp_max_syn_backlog = 65536
    net.core.netdev_max_backlog =  32768
    net.core.somaxconn = 62144

![image](https://cloud.githubusercontent.com/assets/2442573/17057705/608509d0-504e-11e6-8c11-66f5d11e22f6.png)

### [/var/log/messages]
     Jul 22 12:31:33 develop_183_60_123_72_gz abrtd: DUP_OF_DIR: /var/spool/abrt/oops-2015-09-14-11:29:08-6576-0
     Jul 22 12:31:33 develop_183_60_123_72_gz abrtd: New problem directory /var/spool/abrt/oops-2016-07-22-12:31:17-3408-0, processing
    Jul 22 12:31:33 develop_183_60_123_72_gz abrtd: Can't open file '/var/spool/abrt/oops-2016-07-22-12:31:17-3408-0/uid': No such file or directory
    Jul 22 12:31:33 develop_183_60_123_72_gz abrtd: Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### [code]
`package main

import (
	"net/http"
	"log"
)

func Start() {
	addr := "127.0.0.1:8080"
	s := &http.Server{
		Addr:           addr,
		MaxHeaderBytes: 1 << 30,
	}
	log.Println("listening", addr)
	log.Fatalln(s.ListenAndServe())
}

func main() {
	Start()
}`

**Comment by ianlancetaylor** [comment]
I don't see any Go code here.  What makes you think this is a problem with Go?

**Comment by zfwslf** [comment]
I'am sorry,  I just supply the demo code with the problem. I'am confuse with the env of  centos6.3   2.6.32-279.el6.x86_64(with the sysctl param)，but other env(with the sysctl)  is normal.   I am not sure that It is the kenel bug??

**Comment by bradfitz** [comment]
Sorry, I also see no Go issue here. Unfortunately I also don't know where to redirect you. Maybe some CentOS forum would be better?
