### ISSUE TITLE
runtime: insufficient padding in the `p` structure

### ISSUE THREAD

**Issue by bcbrock** [golang/go#16477]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

This issue is observed by reading the source code of the master branch.

While reading the code the other day I noticed that the `p` structure in `src/runtime/runtime2.go` includes the following at line 501:
```
pad [64]byte
```

I assume the intention is to pad by `sys.CacheLineSize` to avoid false sharing between the `p` structures. The value of 64 is currently plausible, but only because `ppc64x` is incorrectly configured with a cache line size of 64. (It should be 128; Someone from IBM will propose/confirm a fix - @laboger ?)

**Comment by ceseo** [comment]
Yes, the cache line size should be 128. The only ppc64 processors I'm aware of that have a 64 byte cache line size are the e5500 and the PA6T, which, I believe, aren't supported by Golang.

I'll work on this issue.
