### ISSUE TITLE
crypto/cipher: StreamReader.Read() panics with slice bounds out of range

### ISSUE THREAD

**Issue by riobard** [golang/go#16487]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

    1.6.3
2. What operating system and processor architecture are you using (`go env`)?

    darwin/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

    https://play.golang.org/p/K9hAxbE5fL

4. What did you expect to see?

    It should not panic.

5. What did you see instead?

    panic: runtime error: slice bounds out of range

**Comment by riobard** [comment]
The issue happens because `StreamReader.Read()` does not check for errors from the embedded `Reader.Read()`. 

Relevant code here: https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/src/crypto/cipher/io.go#L21

A simple fix would be:

```go
func (r StreamReader) Read(dst []byte) (n int, err error) {
	n, err = r.R.Read(dot)
	if n <= 0 { return }
	r.S.XORKeyStream(dst[:n], dst[:n])
	return
}
```

**Comment by minux** [comment]
Can an io.Reader return negative n with error?

I think such a misbehaving Reader will cause panics in
a lot of places (e.g. io/ioutil.ReadAll).

**Comment by riobard** [comment]
@minux It can happen, for example with `syscall.Read` due to the convention of returning negative numbers for errors.

**Comment by minux** [comment]
According to docs of io.Reader: https://golang.org/pkg/io/#Reader

"It returns the number of bytes read (0 <= n <= len(p)) and any error
encountered."

I think this is working as intended. Read can only return non-negative n.

**Comment by bradfitz** [comment]
Yeah, there's nothing to fix here. -1 is not a valid return value from an io.Reader, which has a different contract from the syscall package.

Normally when a function returns a value and an error, the value is ignored if the error is non-nil, but io.Reader specifically says that both the integer and error are used.

As @minux pointed out, it's documented as needing to be >= 0.
