### ISSUE TITLE
doc: add note about vendoring

### ISSUE THREAD

**Issue by Kashomon** [golang/go#16495]
This is a documentation request for [How to Write Go Code](https://golang.org/doc/code.html).

Given that the vendoring experiment is going away in 1.7, would it be possible to discuss vendoring and the vendor directory in the How to Write Go Code doc?

**Comment by freeformz** [comment]
We should do this. Although it may be a little tricky trying not to be
prescriptive wrt which tool to use (we shouldn't be).

**Comment by pciet** [comment]
In editing/retyping Effective Go for typesetting/print I found it to be a great still, but I think the primary documentation could be much clearer with a new pass by the core Go team.

**Comment by ianlancetaylor** [comment]
I'm going to close this as we plan more work on package management for 1.10, which will likely require this to be rethought anyhow.
