### ISSUE TITLE
syscall: mksyscall_windows.go doesn't handle goroot correctly

### ISSUE THREAD

**Issue by mattn** [golang/go#16493]
1. What version of Go are you using (`go version`)?
      go version devel +1d2ca9e Mon Jul 18 21:07:34 2016 +0000 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
     windows/amd64

3. What did you do?
      set GOROOT=c:\dev\go
      set GOPATH=c:\dev\gopath
      go generate with `//go:generate go run $GOROOT/src/syscall/mksyscall_windows.go -output zsyscall_windows.go syscall_windows.go`

4. What did you expect to see?
    mksyscall_windows.go doesn't put import `internal/syscall/windows` because it's not a standard package, or x/sys package.

5. What did you see instead?
      I can see import `internal/syscall/windows` in the code.

https://github.com/golang/go/blob/4cffe44e361deb39e3274774a7984ab78a5b3931/src/syscall/mksyscall_windows.go#L698-L712

goroot is checked without delimiter.

**Comment by alexbrainman** [comment]
> What did you do?
> set GOROOT=c:\dev\go
> set GOPATH=c:\dev\gopath
> go generate with //go:generate go run $GOROOT/src/syscall/mksyscall_windows.go -output zsyscall_windows.go syscall_windows.go

What did you do? Did you run "go generate" command? Which directory?

I don't understand what the problem is. Please provide more details. Thank you.

Alex

**Comment by mattn** [comment]
Few days ago, I contributed some patches for https://github.com/tompng/pokemon-go .
I modified pokemon-go to use https://github.com/jteeuwen/go-bindata .

In my configuration, `GOROOT` and `GOPATH` have same prefix part `C:\dev\go` but not same directory as you can see in above. But mksyscall_windows.go handle those as same. So the code made by mksyscall_windows.go are generated as [pkgStd](https://github.com/golang/go/blob/master/src/syscall/mksyscall_windows.go#L727) because [IsStdRepo](https://github.com/golang/go/blob/master/src/syscall/mksyscall_windows.go#L698) [doesn't check](https://github.com/golang/go/blob/master/src/syscall/mksyscall_windows.go#L711) trailing path separator as delimiter.
If I have backslash in GOPATH and GOROOT, it will works fine. But official [installation instruction](https://golang.org/doc/install#tarball_non_standard) doesn't have trailing slash/backslash in the environment variables.

**Comment by alexbrainman** [comment]
> Few days ago, I contributed some patches for https://github.com/tompng/pokemon-go .
> I modified pokemon-go to use https://github.com/jteeuwen/go-bindata .

I checked github.com/tompng/pokemon-go package. It does not use mksyscall_windows.go. Why are you telling me about github.com/tompng/pokemon-go package?

> In my configuration, GOROOT and GOPATH have same prefix part C:\dev\go but not same directory as you can see in above. But mksyscall_windows.go handle those as same. So the code made by mksyscall_windows.go are generated as pkgStd because IsStdRepo doesn't check trailing path separator as delimiter.

You keep repeating yourself. I understanding that you think there is a bug here. And I don't disagree with you. But I would like to see the bug by myself. Please provide some code or commands to demonstrate the bug. Show us some real computer output, and explain why that output is wrong in your opinion.

Thank you.

Alex

**Comment by mattn** [comment]
> I checked github.com/tompng/pokemon-go package. It does not use mksyscall_windows.go. Why are you telling me about github.com/tompng/pokemon-go package?

Sorry much! I was confusing. True repository is my private for my job. Please check following code.

foo.go is below:
```go
package foo

//go:generate go run $GOROOT/src/syscall/mksyscall_windows.go -output bar.go foo.go

//sys	GetLastError() (lasterr error)
```

```
C:\dev\godev\src\github.com\mattn\foo>go generate
```

and `go generate`. bar.go is following.
```go
// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package foo

import (
	"internal/syscall/windows/sysdll"
	"syscall"
	"unsafe"
)

var _ unsafe.Pointer

var (
	modkernel32 = syscall.NewLazyDLL(sysdll.Add("kernel32.dll"))

	procGetLastError = modkernel32.NewProc("GetLastError")
)

func GetLastError() (lasterr error) {
	r0, _, _ := syscall.Syscall(procGetLastError.Addr(), 0, 0, 0, 0)
	if r0 != 0 {
		lasterr = syscall.Errno(r0)
	}
	return
}
```

`internal/syscall/windows/sysdll` should not be generated.

P.S. I must say sorry again.

**Comment by alexbrainman** [comment]
> Please check following code.

Thanks for the test.

Alex
