### ISSUE TITLE
crypto/x509: re-unify the OS X code paths for loading roots

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16508]
This bug is about fixing #16473 properly for Go 1.8.

OS X 10.8 crashes for some reason when loading cert roots using code which works fine from OS X 10.9+.

https://golang.org/cl/25233 + https://golang.org/cl/25281 went in as conservative fixes for Go 1.7, but @hinman has a better patch (https://golang.org/cl/25190) which needed more review and somebody understanding what was happening on OS X 10.8. (see confusion in https://github.com/golang/go/issues/16473#issuecomment-235441802 for instance)

**Comment by rsc** [comment]
Let's just wait until we can retire OS X 10.8.

**Comment by ianlancetaylor** [comment]
Sounds like there is nothing to do here.
