### ISSUE TITLE
cmd/compile: improve error message in initialization loop

### ISSUE THREAD

**Issue by willfaught** [golang/go#16503]
Please answer these questions before submitting your issue. Thanks!

- What version of Go are you using (`go version`)?

The current play.golang.org version.

- What operating system and processor architecture are you using (`go env`)?

The current play.golang.org version.

- What did you do?

See https://play.golang.org/p/ISPl1bA6OP:

    package main
    
    import (
    	"fmt"
    )
    
    var x int = y
    
    var y int = x
    
    func main() {
    	fmt.Println(x, y)
    }

- What did you expect to see?

This:

    prog.go:7: initialization loop:
        prog.go:7 x refers to y
        prog.go:9 y refers to x

- What did you see instead?

This:

    prog.go:7: initialization loop:
    	prog.go:7 x refers to
    	prog.go:9 y refers to
    	prog.go:7 x

**Comment by odeke-em** [comment]
Could we update the title of this bug from
```
cmd/compile:
```
to something maybe like
```
cmd/compile: improve error message in initialization loop
```
because fixers can't easily search for it.

**Comment by davecheney** [comment]
Done. @adg @broady how about giving @odeke-em the commit bit so he can do this himself?

**Comment by bradfitz** [comment]
@davecheney, @odeke-em, done.

**Comment by odeke-em** [comment]
Wow, thanks @davecheney and @bradfitz!!

**Comment by griesemer** [comment]
FWIW: Not sure making this more verbose helps much. If you read the messages together it's pretty clear, w/o repetition. But I defer to the sentiment of the majority here.

**Comment by rsc** [comment]
The current formatting is not a mistake.

**Comment by willfaught** [comment]
The issue isn't the formatting, it's the wording: it clearly doesn't make sense: "prog.go:7: x refers to prog.go:9: y refers to prog.go:7: x". If a cycle has two edges, it doesn't take three lines to describe it.

**Comment by griesemer** [comment]
@willfaught It does with the current formatting which is less verbose. There's no need to change it.
