### ISSUE TITLE
x/sys/windows: a way to load dll functions by ordinal (not only by name)

### ISSUE THREAD

**Issue by matwachich** [golang/go#16507]
It would be usefull to be able to load DLL functions by ordinal in syscall package.

Example: to use the SHCreateMemStream function on Windows XP

Thanks :)

**Comment by bradfitz** [comment]
The syscall package is frozen (see its package docs) but maybe something can be added to the https://godoc.org/golang.org/x/sys/windows package (it's a bug that those docs don't show anything: #16509).

**Comment by alexbrainman** [comment]
> It would be usefull to be able to load DLL functions by ordinal in syscall package.

I don't see usefulness of that. You have mentioned "SHCreateMemStream", but I have never used that function. What is the problem that you are trying to solve?

And you can do it now. You can copy syscall.GetProcAddress and change the function to pass integer to syscall.Syscall instead of string. I just don't see how this can be used to justify us adding this functionality even in golang.org/x/sys/windows.

Alex

**Comment by matwachich** [comment]
SHCreateMemStream is exported by ordinal in WindowsXP. I needed it to
create a memory stream to export/import an in-memory jpeg GpImage.

Finally, I solved the problem by using GlobalAlloc/Free and
CreateStreamFromHGlobal.

Le ven. 5 août 2016 à 07:54, Alex Brainman <notifications@github.com> a
écrit :

**Comment by alexbrainman** [comment]
> SHCreateMemStream is exported by ordinal in WindowsXP.

Do you have some references? Just for my curiosity. Thank you.

> I solved the problem by using GlobalAlloc/Free and
> CreateStreamFromHGlobal.

Cool. I take it you don't need ability to find DLL procedure by cardinal number then.

Alex

**Comment by matwachich** [comment]
Reference: MSDN

In fact, I don't need it anymore but using SHCreateMemStream would have
been easier.

Thanks.

**Comment by alexbrainman** [comment]
> Reference: MSDN

How do I use this reference? I was hoping you have some official links on the Internet. I tried implementing this, but I cannot even write a test for it - what should my test do?

Alex

**Comment by hillu** [comment]
Example: https://msdn.microsoft.com/en-us/library/windows/desktop/bb773795.aspx tells me to import `shlwapi.dll:IsOS` by ordinal in order to be compatible across OS versions.

**Comment by alexbrainman** [comment]
> Example: https://msdn.microsoft.com/en-us/library/windows/desktop/bb773795.aspx tells me to import shlwapi.dll:IsOS by ordinal in order to be compatible across OS versions.

@hillu thank you for the reference. I will try to implement this when I have spare time. Unless someone beats me to it.

Alex

**Comment by alexbrainman** [comment]
@hillu I have found your CL 70690. I will review it when I have time. Thank you.

Alex
