### ISSUE TITLE
time: local timezone affects parsing RFC1123

### ISSUE THREAD

**Issue by homingli** [golang/go#16517]
1. What version of Go are you using (`go version`)?
go version go1.5.3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
Parsing RFC1123 the 4digit timezone exhibit different behavior depending on local timezone.
On my laptop set to PDT, the result is expected.
On a server set to UTC, the result is +0000 PDT (same behavior as https://play.golang.org/p/Tlbt2g24Fb)

4. What did you expect to see?
2016-07-26 03:34:46 -0700 PDT

5. What did you see instead?
2016-07-26 03:34:46 +0000 PDT

**Comment by homingli** [comment]
This behavior is observed downstream https://github.com/SlyMarbo/rss/issues/33

**Comment by minux** [comment]
timezone abbreviation is only meaningful within a certain
location.

You need to parse the date within the location that have
valid timezone called PDT.

This is working as intended.

**Comment by homingli** [comment]
@minux can you explain this behavior further?

I also tried time.ParseInLocation with time.LoadLocation("Americas/Los Angeles") but still with the same behavior. How do I properly parse that time string to get the expected result consistently?

**Comment by minux** [comment]
https://play.golang.org/p/r_-W5GYLm0

**Comment by homingli** [comment]
Duh! Bad typos in my location, it's working fine. Thanks! 

I still don't understand your statement though: "timezone abbreviation is only meaningful within a certain location."

Shouldn't PDT be -0700 parsed from anywhere and everywhere? If i parse PDT from Los_Angeles, or parse PDT from New_York, PDT should still mean -0700, is that not true?

**Comment by cespare** [comment]
@homingli no, the abbreviations are not unique and depend on the locale. For instance if you look at [this list](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations), you can see many duplicate abbreviations (ACT, BST, etc).

**Comment by homingli** [comment]
Wow. Did not know that timezone abbreviation is not standardized. Thanks!

Is it because PDT is not known so it parses to "+0000 PDT"? This really threw me off for some time calculations.

I'm also curious if it makes sense to have sane defaults, at least for non-duplicating definitions. But anyway, you guys are right, this is working as expected. Thank you for pointing this out to me.

**Comment by cespare** [comment]
> Is it because PDT is not known so it parses to "+0000 PDT"?

Yes. The docs for https://golang.org/pkg/time/#Parse say, in part:

> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset.

I think that answers your question.

But if you want to discuss further, you should use the mailing list rather than this issue.
