### ISSUE TITLE
x/term: IsTerminal 

### ISSUE THREAD

**Issue by techtonik** [golang/go#16518]
I've added code to x/term https://github.com/techtonik/term/tree/isterm to fix #16420

I can't mail them:

```
>git codereview mail
remote: Processing changes: refs: 1, done
To https://go.googlesource.com/go
 ! [remote rejected] HEAD -> refs/for/master (no common ancestry)
error: failed to push some refs to 'https://go.googlesource.com/go'
(running: git push -q origin HEAD:refs/for/master)
git-codereview: exit status 1
```

Should the function be called IsTerminal, IsConsole or IsInteractive?

**Comment by techtonik** [comment]
@mattn can we get get https://github.com/mattn/go-isatty in here?

**Comment by mattn** [comment]
What do you mean `get`? If you mean about using my codes on go-isatty, I am okay and feel free to use.

**Comment by minux** [comment]
the git remote "origin" should be set to
https://go.googlesource.com/term
instead of
https://go.googlesource.com/go

**Comment by techtonik** [comment]
Submitted. https://go-review.googlesource.com/38050

`git-codereview` doesn't support cloning from GitHub and then changing remote 'origin' (change command fails to detect changes), so I have to `git clone https://go.googlesource.com/term`, then `git pull git@github.com:techtonik/term isterm` and only then it worked.

**Comment by ysmolsky** [comment]
I think this issue was solved and it's not a proper bug. ping @bradfitz
