### ISSUE TITLE
os/signal: test timeout (entire VM hangs) on netbsd/386 (7.0.1 GENERIC)

### ISSUE THREAD

**Issue by minux** [golang/go#16511]
I upgraded the netbsd/386 builder to the latest 7.0.1 release,
and suddenly a lot of the builds fail at os/signal.

E.g.
timeout:
https://build.golang.org/log/f4c637234824467172beb3c7fdaf61fbd403d55c
illegal instruction:
https://build.golang.org/log/d1841610bb2fd982671f4db6bd8d1836a0a2d735
(this log also shows a failure in runtime/pprof, which might be interesting
as well.)
SIGTRAP:
https://build.golang.org/log/7275a54c64635553b418a15a58475698cf772f64

Repeated run of os/signal tests showed that it's failing in TestStress.

/cc @ianlancetaylor any ideas?

**Comment by bradfitz** [comment]
Ian is on vacation.

**Comment by bsiegert** [comment]
Is that the same as #10027?

**Comment by minux** [comment]
the test timeout part is different from #10027.
but they might have the same cause.

**Comment by minux** [comment]
The problem on netbsd is even worse,
the builder VM freezes (sometimes
restarts automatically) after a few builds.

so far I haven't been able to capture a
copy of the kernel messages yet.

there isn't any log on the console.

**Comment by ianlancetaylor** [comment]
See if you can get the strace output (or dtruss, or whatever it is called on NetBSD) of `signal.test -test.short -test.run=TestStress`.

Sounds like something is going wrong if a signal is received while handling that signal.  Or, it's a problem with the alternate signal stack.

**Comment by rsc** [comment]
If the entire builder VM freezes then it's probably not Go's fault. Sounds like a kernel problem.

**Comment by wenheping** [comment]
The same test error of Go-1.8 On NetBSD/amd64(7.0.1 GENERIC).

**Comment by bradfitz** [comment]
This is fixed by requiring NetBSD 8-BETA+.
