### ISSUE TITLE
runtime/race: support core dumps in race mode

### ISSUE THREAD

**Issue by sillyousu** [golang/go#16527]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7beta1 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/supei/project/jx3m/Server/go"
GORACE=""
GOROOT="/home/supei/goroot"
GOTOOLDIR="/home/supei/goroot/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144261612=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
get or set resource limit via system call.

https://play.golang.org/p/ZEsI1Xxyqi

4. What did you expect to see?
same core size limit 

5. What did you see instead?
```
without -race 
rlimit core: 0 18446744073709551615
with
rlimit core: 0 0
```

**Comment by davecheney** [comment]
What is the output you get under the race detector.

**Comment by sillyousu** [comment]
without -race 
`rlimit core: 0 18446744073709551615`

with
`rlimit core: 0 0`

**Comment by sillyousu** [comment]
[strace.txt](https://github.com/golang/go/files/388453/strace.txt)
It calls setrlimit somewhere.

**Comment by quentinmit** [comment]
That code comes from the sanitizer library (see https://github.com/llvm-mirror/compiler-rt/blob/929d23ef5045d955ef2c36f2bbdb3dc61eca518f/lib/sanitizer_common/sanitizer_posix_libcdep.cc#L90)

The documentation for that flag says:
> Disable core dumping. By default, disable_core=1 on 64-bit to avoid dumping a 16T+ core file. Ignored on OSes that don't dump core by default and for sanitizers that don't reserve lots of virtual memory.

Given that comment, it seems like it would be difficult or impossible to fix this.

**Comment by mdempsky** [comment]
It looks like Linux 3.4 added a `MADV_DONTDUMP` flag that can be used to omit memory from core dumps, so compiler-rt could potentially use that to avoid needing to disable core dumps altogether.

**Comment by tombergan** [comment]
I believe this is WAI. Set GORACE='disable_coredump=0' in your environment if you want coredumps with the race detector:

$ cat https://play.golang.org/p/ZEsI1Xxyqi > main.go
$ go run main.go
rlimit core: 0 18446744073709551615
$ go run -race main.go
rlimit core: 0 0
$ GORACE='disable_coredump=0' go run -race main.go
rlimit core: 0 18446744073709551615
