### ISSUE TITLE
os: Stat never stops if the path is a circular symbolic link on windows

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#16538]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.3

2. What operating system and processor architecture are you using (`go env`)?
windows/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```go
package main

import (
  "os"
)

func main() {
  os.Symlink("a", "b")
  os.Symlink("b", "a")
  err := os.Stat("a")
  if err != nil {
    panic(err)
  }
}
```
4. What did you expect to see?
stopped with some errors.

5. What did you see instead?
No errors. busy loop

**Comment by minux** [comment]
A simple fix (as used by Unix) is to limit the maximum number
of iterations the loop at https://tip.golang.org/src/os/stat_windows.go#L64
executes.

However, determining that threshold seems tricky. For Linux,
MAXSYMLINKS is defined to be 40.

**Comment by hirochachacha** [comment]
>A simple fix ...

I agree with you.
>MAXSYMLINKS is defined to be 40.

or _POSIX_SYMLOOP_MAX = 8 

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html

**Comment by alexbrainman** [comment]
> A simple fix (as used by Unix) is to limit the maximum number
> of iterations

Sure. We already do something like that here https://tip.golang.org/src/path/filepath/symlink.go#L36

@hirochachacha do you want to send change (with new test) after go1.7 is released?

Alex

**Comment by hirochachacha** [comment]
Yes, I will.
