### ISSUE TITLE
cmd/go: go run -cover

### ISSUE THREAD

**Issue by AlekSi** [golang/go#16537]
Currently `-cover` is only supported in unit tests. Running service with `-cover` and then running functional/system/API tests against it will give information about what parts are tested and what are not.

It's possible to [(ab)use](https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests) `go test -cover -c` to get desirable result, but there have to be a better way.

**Comment by quentinmit** [comment]
I'm not sure how "go run" would communicate to the subprocess that it should collect coverage. "go test" does so by passing a command-line flag, no?

**Comment by broady** [comment]
This would be amazing. Here's one example of a test that builds the binary, runs it to test the main function: [app_test.go](https://github.com/GoogleCloudPlatform/golang-samples/blob/bbbbe266902ae707b1179ee19c2ca6df27df41c2/getting-started/bookshelf/app/app_test.go#L31-L39)

It would be great to have that considered by `-cover` somehow.

**Comment by rsc** [comment]
Need to think more but I don't really understand what this would mean.

**Comment by AlekSi** [comment]
> I'm not sure how "go run" would communicate to the subprocess that it should collect coverage. "go test" does so by passing a command-line flag, no?

Not quite. Passing `-cover` to `go test` enables rewriting of source code. See https://blog.golang.org/cover for more info. `go run -cover` can do the same.

**Comment by dajoo75** [comment]
I uploaded a fix for discussion here: https://go-review.googlesource.com/42096.
cc @rsc

**Comment by rsc** [comment]
I tend to agree that we want to keep go run limited in its scope. 

But there is no 'go build -cover' so at the very least that would need to happen first. If that did happen, then go run -cover might fall out for free. That said, I'm not sure go build -cover should happen. Coverage is fairly tied to testing. If you did -cover outside of tests you'd need to recreate the testing package support that exports the coverage info.

**Comment by AlekSi** [comment]
Uh. Then maybe testing support for coverage info should be extracted to some package, /x/ maybe? Right now it's private, and [existing solution](https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests) is too fragile.

**Comment by ianlancetaylor** [comment]
@AlekSi Whatever you suggest, that should probably be in a different issue.  We are still unlikely to add `go run -cover`.  Thanks.
