### ISSUE TITLE
os: TestHostname fails if docker container doesn't have /bin/hostname

### ISSUE THREAD

**Issue by meghalidhoble** [golang/go#16536]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6 , using branch release-branch.go1.6

2. What operating system and processor architecture are you using (`go env`)?
Rhel 7.2 

3. What did you do and what's the result?
The ./all.bash command fails for me inside the docker container with the below error: 
   Error : --- FAIL: TestHostname (0.00s)
   os_test.go:1287: fork/exec /bin/hostname: no such file or directory

4. What did you expect to see?
All the tests should pass.

5. My analysis
I found that the issue I am getting is exactly similar to issue #14693. Hence when I tried applying the patch for this particular issue in my work environment; I found that all the tests were passing. 

I would like to know if we can cherry-pick the fix for issue #14693 and merge it into the branch release-branch.go1.6, (which I have done for my environment to verify if it works).
Please note that this commit is not found in the particular branch.

**Comment by davecheney** [comment]
I don't think this issue is worth issuing another 1.6 release. This is not a bug with the test, just an artefact that your docker image doesn't have the host name command. 

Your go install has built successfully at this time, you can ignore the test failure.

**Comment by quentinmit** [comment]
I agree with @davecheney, 1.7 is about to land and I don't think this merits a 1.6 release.

**Comment by meghalidhoble** [comment]
Thanks @davecheney and @quentinmit for responding, that helped.
