### ISSUE TITLE
reflect: DeepEqual treats nil and empty map as not equal

### ISSUE THREAD

**Issue by zombiezen** [golang/go#16531]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Go tip (be91515)

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64

3. What did you do?
https://play.golang.org/p/S_vq5DdCzu

4. What did you expect to see?
`true`

5. What did you see instead?
`false`

The doc for `reflect.DeepEqual` says:

> Map values are deeply equal if they are the same map object or if they have the same length and their corresponding keys (matched using Go equality) map to deeply equal values.

Empty and nil maps both have a length of zero, so I would expect this to be true.

**Comment by mdempsky** [comment]
My 2c: I think the behavior is consistent with how we handle slices (nil and zero-length slices are unequal), but we should document that (like we already do for slices).

**Comment by zombiezen** [comment]
Yeah, I think it aligns with what we do with slices, but it does not match docs. I'd be fine with a doc fix.

**Comment by bradfitz** [comment]
Dup of #12918

Maybe a documentation issue.

**Comment by zombiezen** [comment]
#12918 is about slices, though. They are related, but the docs are correct AFAICT for slices now.

**Comment by mdempsky** [comment]
Yeah, @ianlancetaylor's argument on #12918 is compelling that this is a documentation issue: `map[string]int{} == nil` is a valid Go expression that evaluates to false, so reflect.DeepEqual should report the same.

**Comment by zombiezen** [comment]
Yeah, let's fix the docs.

**Comment by dsnet** [comment]
I think that we should provide some example usages of reflect.DeepEqual on a variety of edge inputs. I'm sure there are more subtleties about DeepEqual that are probably better demonstrated through example rather than prose. DeepEqual is probably the most used (and abused?) function in the reflect package and lacks examples.

Related to #16360.
