### ISSUE TITLE
cmd/cover: internal error: overlapping blocks for func literals in switch cases

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#16540]
1. What version of Go are you using (`go version`)?
   
   ```
   $ go version
   go version go1.6.2 linux/amd64
   ```
2. What operating system and processor architecture are you using (`go env`)?
   
   ```
   $ go env
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/data"
   GORACE=""
   GOROOT="/usr/lib/golang"
   GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
   ```
3. What did you do?
   I ran the OpenShift Origin unit tests. Unfortunately this is fairly complicated, but can be achieved with:
   
   ``` sh
   $ git clone git@github.com:openshift/origin.git
   $ cd origin
   $ make build
   $ JUNIT_REPORT=true TEST_KUBE=true hack/test-go.sh
   ```
4. What did you expect to see?
   A successful test run with no errors.
5. What did you see instead?
   Full output to [stdout](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4233/s3/download/test-go/logs/test-go.log) and [stderr](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4233/s3/download/test-go/logs/test-go-err.log)
   
   ```
   [WARNING] `go test` had the following output to stderr:
   # cover github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient
   cover: internal error: block 264 overlaps block 266
     /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:#27640,#27764 /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:#27685,#27704
   ```
   
   The file mentioned above can be seen here: [`request.go`](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go).

I'm happy to do more digging but I'm not really sure what the `#27640` syntax means or what to look for in the source.

**Comment by quentinmit** [comment]
@stevekuznetsov I believe the "#27640,#27764" means that the block begins at byte 27640 in the file and ends at byte 27764. So something like "head -c 27764 request.go | tail -c +27640" should print the block it's talking about.

Can you try again with Go 1.7rc3? It's possible that this has already been fixed since 1.6.2. Thanks!

**Comment by stevekuznetsov** [comment]
I'm afraid I can't install `golang-1.7.0-rc3` on our CI super easily so I'm not sure if I can run it on the newer version without also changing other environmental stuff, but I'll give it a shot. Until then:
```sh
$ head -c 27764 vendor/k8s.io/kubernetes/pkg/client/restclient/request.go | tail -c +27640
	case bytes.IndexFunc(body, func(r rune) bool { return r < 0x0a }) != -1:
			glog.Infof("Response Body:\n%s", hex.Dump(body))
```

**Comment by stevekuznetsov** [comment]
The other block identified is:
```sh
$ head -c 27704 vendor/k8s.io/kubernetes/pkg/client/restclient/request.go | tail -c +27685 > debug.go
```
```go
// debug.go 
 { return r < 0x0a }
```

**Comment by fjl** [comment]
We have a similar issue [in github.com/ethereum/go-ethereum/p2p](https://github.com/ethereum/go-ethereum/blob/5f55d95aea433ef97c48ae927835d833772350de/p2p/server.go#L228). The statement that causes it also involves a function literal inside `case`.

**Comment by minux** [comment]
A smaller and standalone reproduction:

$ cat issue16540_test.go
package issue16540
import "testing"
func Test(t *testing.T) {
switch {
case 1 == func() int { return 1 }():
return
}
}
$ go tool cover -mode=set -var=XXXX issue16540_test.go  > /dev/null
cover: internal error: block 1 overlaps block 2
issue16540_test.go:#73,#118 issue16540_test.go:#94,#106

The two overlapping ranges are:
     case 1 == func() int { return 1 }(): return
And:
     { return 1 }
