### ISSUE TITLE
x/build/cmd/release: installer says Win2k requires; download page says XP

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16544]
The Wix installer says:

```
  <Condition Message="Windows 2000 or greater required."> VersionNT >= 500</Condition>                                                                                             
```

But the golang.org/dl download page says Windows XP+ is required.

**Comment by minux** [comment]
As of Go 1.3, Windows 2000 is no longer supported by Go.
We'd better fix the installer before Go 1.7 to avoid confusing
people.

https://golang.org/doc/go1.3#win2000

**Comment by bradfitz** [comment]
I'll flag it as a maybe since we might still need to tweak something in that xml file yet anyway. But not critical if we don't do it right away. I think that message only comes up if your Windows is too old anyway.

**Comment by alexbrainman** [comment]
I suggest we change:
```
 <Condition Message="Windows 2000 or greater required."> VersionNT >= 500</Condition>  
```
with
```
 <Condition Message="Windows XP or greater required."> VersionNT >= 500</Condition>  
```

If someone use this on Windows 2000, good luck to them.

Alex

**Comment by bradfitz** [comment]
@alexbrainman, why not also bump the 500 to 501, per https://msdn.microsoft.com/en-us/library/windows/desktop/aa370556(v=vs.85).aspx ?

Specifically, Go requires Windows XP with Service Pack 2 (SP2), IIRC.

If a user really wants to try it on an earlier Windows, they can use the ZIP file instead of the MSI.

**Comment by alexbrainman** [comment]
> why not also bump the 500 to 501, per https://msdn.microsoft.com/en-us/library/windows/desktop/aa370556(v=vs.85).aspx ?

I am just trying to change as little as possible. So we don't break some users. I know nothing about MSIs.

> If a user really wants to try it on an earlier Windows, they can use the ZIP file instead of the MSI.

Sure. They can use MSI or ZIP file.

Alex

**Comment by bradfitz** [comment]
> I am just trying to change as little as possible.

For Go 1.7 that sounds fine, just changing the text. I'll keep this bug open for more later.

**Comment by mkrautz** [comment]
FYI, CL 25364 only changed the text, but not the NT version.

It now reads:

`<Condition Message="Windows XP or greater required."> VersionNT >= 500</Condition>`

but it should probably read:

`<Condition Message="Windows XP or greater required."> VersionNT >= 501</Condition>`

**Comment by bradfitz** [comment]
@mkrautz, yup. See https://github.com/golang/go/issues/16544#issuecomment-236397205 above. We're being conservative for 1.7.

**Comment by mkrautz** [comment]
Ah, sorry. I came here from the CL, and I didn't read the issue thread. Oops. :-)
