### ISSUE TITLE
wiki: cgo wiki examples of function pointer use the default prototype for callbacks

### ISSUE THREAD

**Issue by vincentbernat** [golang/go#16541]
Hey!

The [wiki page about how to use function pointer callbacks](https://github.com/golang/go/wiki/cgo#function-pointer-callbacks) emits a warning with recent versions of gcc (due to warning being enabled by default now):

```
$ go build
# _/home/bernat/src/ccalbacks
./cfuncs.go: In function ‘callOnMeGo_cgo’:
./cfuncs.go:11:12: warning: implicit declaration of function ‘callOnMeGo’ [-Wimplicit-function-declaration]
     return callOnMeGo(in);
            ^
```

It's easy to silent the warning (with `-Wno-implicit-function-declaration`) but this also means that the compiler is working with the default `int f()` prototype and there is no sanity check available. It's a bit of chicken-egg problems since the header for the Go functions (`_cgo_export.h`) is generated only after so we can't use it yet.

I don't know if there exists a workaround that could be documented in the wiki or if this is a weakness to be fixed in cgo.

**Comment by rakyll** [comment]
Cgo callbacks tests uses manual forward declaration for a [similar case](https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/misc/cgo/test/callback_c.c#L65), I am going to update the wiki page accordingly.

**Comment by rakyll** [comment]
Closed via https://github.com/golang/go/wiki/cgo/69b7bf5decfafffa21335c73e3b4c815a2452a1f.

**Comment by vincentbernat** [comment]
Hey @rakyll!

Your modification shows how dangerous it may be to have to manually add a forward declaration. You added:

```
int callOnMeGo(int);
```

But the real prototype of this function is (on my platform):

```
typedef long long GoInt64;
typedef GoInt64 GoInt;
extern GoInt callOnMeGo(GoInt p0);
```

`sizeof(int) == 4` and `sizeof(long long) == 8`. You can't use `GoInt` here and I suppose that the size of `GoInt` depends on the platform. The best we should be able to do is to include `_cgo_export.h` but it is not generated yet.
