### ISSUE TITLE
internal/syscall/windows/registry: godoc says "Not Found" about this package

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#16559]
Please answer these questions before submitting your issue. Thanks!

3. What did you do?

I entered this
https://godoc.org/internal/syscall/windows/registry
into my browser.

4. What did you expect to see?

Some documentation about internal/syscall/windows/registry package.

5. What did you see instead?

Not Found
Oh snap! Our team of gophers could not find the web page you are looking for. Try one of these pages:

Alex

**Comment by bradfitz** [comment]
Why would you expect to see it there? It's internal.

**Comment by alexbrainman** [comment]
> Why would you expect to see it there? It's internal.

https://godoc.org/internal/syscall/windows works. And https://godoc.org/internal/syscall/windows/sysdll works. Why https://godoc.org/internal/syscall/windows/registry does not work? At least it needs to be consistent.

Alex

**Comment by quentinmit** [comment]
This problems seems specific to godoc.org; the "go doc" command correctly shows either both or neither package, based on the value of GOOS. I'll move this over to the gddo issue tracker.
