### ISSUE TITLE
text/template: can add io.Writer as default argument with name is '&'  in the empty?

### ISSUE THREAD

**Issue by runner-mei** [golang/go#16558]
1. What version of Go are you using (`go version`)?
go version go1.7rc3 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\developing\go\meijing\..\3td;d:\developing\go\meijing\
set GORACE=
set GOROOT=d:\tools\go_amd64
set GOTOOLDIR=d:\tools\go_amd64\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\meifakun\AppData\Local\Temp\go-build810938422=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
Take the simple example from
https://play.golang.org/p/KMgTlxbI_s

4. What did you expect to see?
  aaaa

**Comment by quentinmit** [comment]
You are ignoring the error return from template.New. If you actually look at the error, you'll see:

https://play.golang.org/p/NJcVvM9pzL
template: root:1: unexpected "&" in operand

"&" is not a valid expression in the template. AFAICT this is working as intended.

**Comment by runner-mei** [comment]
replace & with $output ?
