### ISSUE TITLE
x/crypto/ssh/terminal: ReadPassword skips input on Windows with 15 character input

### ISSUE THREAD

**Issue by schmich** [golang/go#16552]
**Issue**

On Windows 10, when `terminal.ReadPassword` is called twice in succession (e.g. for password prompt and confirmation), and the first input is exactly 15 characters, the second call skips input entirely and immediately returns an empty string.

**Repro**

``` go
package main

import (
  "golang.org/x/crypto/ssh/terminal"
  "fmt"
  "os"
)

func readPassword(prompt string) string {
  fmt.Print(prompt)
  pass, err := terminal.ReadPassword(int(os.Stdin.Fd()))
  if err != nil {
    panic(err)
  }
  println()
  return string(pass)
}

func main() {
  pass := readPassword("Password: ")
  confirm := readPassword("Confirm: ")
  fmt.Printf("%s -- %d\n", pass, len(pass))
  fmt.Printf("%s -- %d\n", confirm, len(confirm))
}
```

For a working scenario, use `test` (or any non-15-character string) for the password and confirmation. You'll see the following output, as expected:

```
Password:
Confirm:
test -- 4
test -- 4
```

For the failing scenario, use `testtesttesttes` (or any 15 character string) for the password. You will not be prompted for confirmation, and the program will output:

```
Password:
Confirm:
testtesttesttes -- 15
 -- 0
```

In this scenario, I expect the second call to `terminal.ReadPassword` to prompt for input (just like the working scenario), but it doesn't.

**Environment**
- Windows 10 10.0.10586 amd64
- go version go1.6.3 windows/amd64

**Notes**
- This doesn't repro on OSX
- My guess is that this some kind of buffer issue. I haven't dug deeply, but the main difference I see between [`util.go`](https://github.com/golang/crypto/blob/911fafb28f4ee7c7bd483539a6c96190bbbccc3f/ssh/terminal/util.go#L92) and [`util_windows.go`](https://github.com/golang/crypto/blob/3fbbcd23f1cb824e69491a5930cfeff09b12f4d2/ssh/terminal/util_windows.go#L129) is the `\r` handling on Windows. This might be related.
- You can use [gopass](https://github.com/howeyc/gopass) as a workaround. It provides similar functionality and does not have this problem. It appears to operate quite differently, however, by reading individual characters from a raw terminal.

**Comment by alexbrainman** [comment]
Can someone, please, review CL https://golang.org/cl/25355.
Thank you.

Alex

**Comment by hanwen** [comment]
I have no qualifications for reviewing terminal code; is there anyone who understands this stuff? I can look at it if we have noone better.

**Comment by creshal** [comment]
FWIW the bug happens on Windows 7 as well, and gopass is a poor substitute as it breaks multi-byte input in exciting ways.
