### ISSUE TITLE
bash: error while loading shared libraries: libncursesw.so.6

### ISSUE THREAD

**Issue by diman82** [golang/go#16557]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.3

2. What operating system and processor architecture are you using (`go env`)?
Entware-ng ARM7

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
root@DD-WRT:/opt/share/Go/go/src# taskset 1 ./make.bash
**bash: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory**
```

4. What did you expect to see?

5. What did you see instead?

Any ideas?

**Comment by bradfitz** [comment]
Let's move this to https://golang.org/wiki/Questions as there's no Go-specific bug here. We don't have any reference to curses in our source tree. You must have something in your GOROOT which doesn't belong.
