### ISSUE TITLE
log: document Print and Printf adding newlines more

### ISSUE THREAD

**Issue by joegrasse** [golang/go#16564]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.3 linux/386

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr2/ps/isp/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
https://play.golang.org/p/qF9NrwS_2Y

4. What did you expect to see?
2009/11/10 23:00:00 1st Line.
2009/11/10 23:00:00 2nd Line. I want on 2nd line as well.
2009/11/10 23:00:00 3rd Line.I want on the 3rd line

5. What did you see instead?
2009/11/10 23:00:00 1st Line.
2009/11/10 23:00:00 2nd Line.
2009/11/10 23:00:00  I want on 2nd line as well.
2009/11/10 23:00:00 3rd Line.
2009/11/10 23:00:00 I want on the 3rd line

**Comment by bradfitz** [comment]
This is a documented feature of the `log` package: https://golang.org/pkg/log/#Logger.Output

Use the `fmt` package if you want control over line endings.

**Comment by joegrasse** [comment]
I now see that this is documented. However, this seems very counterintuitive based on the fact that the 3 different function exist for the log package.

**Comment by bradfitz** [comment]
True. Maybe it warrants more docs.

**Comment by joegrasse** [comment]
Probably too late now, but it would be nicer for ```Println``` vs ```Print``` to work as expected. When falling back to ```fmt```, you lose a lot of the niceties that ```log``` provides, such as ```SetOutput```, ```SetPrefix```, etc.

**Comment by bradfitz** [comment]
Yeah, we won't be changing the behavior.
