### ISSUE TITLE
go/doc: ToHTML does not properly handle URLs containing semicolons

### ISSUE THREAD

**Issue by mdlayher** [golang/go#16565]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

```
go version go1.6.3 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matt/git/go"
GORACE=""
GOROOT="/home/matt/.gvm/gos/go1.6.3"
GOTOOLDIR="/home/matt/.gvm/gos/go1.6.3/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/s7-kyuoQx3

Credit to @normanvashon for this example and diagnosing the bug in `go/doc` here: https://github.com/golang/gddo/issues/406#issuecomment-236632063.

4. What did you expect to see?

The entire git.qemu.org URL should be hyperlinked.

5. What did you see instead?

The hyperlink is cut off right before the first semicolon.

I have a patch ready and will submit a CL for this in the next few minutes.

**Comment by bradfitz** [comment]
Looking at that regexp in the CL, looks like it also doesn't handle IPv6 addresses: https://play.golang.org/p/PvwsEXAwWR

Probably doesn't matter, though.
