### ISSUE TITLE
x/mobile: Cryptic error message when a keyword that is reserved in C/ObjC but not in Golang is used in Go code

### ISSUE THREAD

**Issue by petejkim** [golang/go#16560]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   
   ```
   1.6.3
   ```
2. What operating system and processor architecture are you using (`go env`)?
   
   ```
   darwin/amd64
   ```
3. What did you do?
   
   `$GOPATH/src/github.com/petejkim/foo/foo.go`
   
   ```
   package foo
   
   func DoSomethingWithLocation(lat, long, alt float64) float64 {
     return 0.0
   }
   ```
   
   ```
   $ gomobile bind -target=ios github.com/petejkim/foo
   gomobile: darwin-armv7: go build -p=8 -pkgdir=/Users/jihoon/code/go/pkg/gomobile/pkg_darwin_arm -tags="" -buildmode=c-archive -tags=ios -o /var/folders/7t/zvcfl61j57d722hzvyxm5cym0000gn/T/gomobile-work-326555581/foo-arm.a /var/folders/7t/zvcfl61j57d722hzvyxm5cym0000gn/T/gomobile-work-326555581/src/iosbin/main.go failed: exit status 2
   # _/var/folders/7t/zvcfl61j57d722hzvyxm5cym0000gn/T/gomobile-work-326555581/src/gomobile_bind
   /var/folders/7t/zvcfl61j57d722hzvyxm5cym0000gn/T/gomobile-work-326555581/src/gomobile_bind/GoFoo.m:21:54: error: parameter name omitted
   /var/folders/7t/zvcfl61j57d722hzvyxm5cym0000gn/T/gomobile-work-326555581/src/gomobile_bind/GoFoo.m:23:25: error: expected expression
   ```
4. What did you expect to see?
   
   I expected it to show an error saying it cannot be compiled due to the presence of reserved keyword `long`. It would be better if it could just handle it automatically by perhaps prepending/appending `_` to the reserved keyword (`_long`) to avoid Obj-C compilation error.
5. What did you see instead?
   
   A cryptic error message. It took me a while before I realized it was due to the argument name `long` (short for `longitude` in my case), which is a reserved keyword (a data type) in ObjC.

**Comment by 8tt** [comment]
Another example:

`package bug

type Interface1 interface {
}

func Func1(i Interface1, id int) int {
    return 0
}
`

**Comment by eliasnaur** [comment]
Fixed by https://golang.org/cl/28494.
