### ISSUE TITLE
reflect: clarify FieldByNameFunc docs?

### ISSUE THREAD

**Issue by legendtkl** [golang/go#16573]
My Env is as follow:
```
go version go1.6 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

In the package reflect, the func `func (v Value) FieldByNameFunc(match func(string) bool) Value` return the struct field that satisfies the match func.

My question is what will the func return if there are more than one struct fields that satisfy the match func. In my opinion, it should return the first field, but actually it return invalid. The test code is as follow.
```go
type S struct {
    A int
    B int
    C int
    D int
}

func main() {
    var f = func(s string) bool {
        if s == "A" || s == "B" || s == "C" {
            return true
        }
        return false
    }
  
    var a S
    S := reflect.ValueOf(a)

    fields := S.FieldByNameFunc(f)
    fmt.Println(fields.Kind())
}
```
 It output `invalid`. I think it should output `int` (field A). Is this expected ?

Thanks.

**Comment by bradfitz** [comment]
Maybe it needs more documentation.

/cc @crawshaw

**Comment by legendtkl** [comment]
So this is expected ? 

If the answer is yes, now I have another question. What should I do to filter more than one struct fields ?

Many thanks.

**Comment by bradfitz** [comment]
I didn't look at your code or the reflect code or docs. I was reacting based purely on the confusion. If the docs said the expected behavior, this bug probably wouldn't exist.

**Comment by ianlancetaylor** [comment]
This is expected behavior.

Please ask questions on a forum, not on the issue tracker.  See https://golang.org/wiki/Questions .  Thanks.

**Comment by mdempsky** [comment]
Hm, from interface Type's documentation:

        // FieldByNameFunc returns the **first** struct field with a name
        // that satisfies the match function and a boolean indicating if
        // the field was found.
        FieldByNameFunc(match func(string) bool) (StructField, bool)

Experimentally, it does not seem to do that.  If match matches against multiple fields, at the same nesting depth, it returns (nil, false): https://play.golang.org/p/tP1JkvDxlt

**Comment by ianlancetaylor** [comment]
@mdempsky See the comment in the code.

    	// This uses the same condition that the Go language does: there must be a unique instance
    	// of the match at a given depth level. If there are multiple instances of a match at the
    	// same depth, they annihilate each other and inhibit any possible match at a lower level.
    	// The algorithm is breadth first search, one depth level at a time.
