### ISSUE TITLE
Go: unoccurred deadlock in using cgo

### ISSUE THREAD

**Issue by catalase** [golang/go#16571]
1. What version of Go are you using (`go version`)?

`go version go1.6.2 windows/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=C:\Users\Home\go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Home\go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?
I ran the code.
```go
package main

import "C"
import "fmt"

var _ C.int

func main() {
	fmt.Println("Jesus saves Go from deadlock")
	select {}
}
```

4. What did you expect to see?
```
Jesus saves Go from deadlock
fatal error: all goroutines are asleep - deadlock!
...
```

5. What did you see instead?
```
Jesus saves Go from deadlock
(the execution don't complete without any error message)
```

Seems that `import C` prevents the program from raising deadlock.

**Comment by bradfitz** [comment]
Yes, this is known and unfortunate. See 34c67eb24e1b3cfe16a512ab2d4899c78032030b for some background.

/cc @dvyukov
