### ISSUE TITLE
Add support for line breaks for base64 input to json.Unmarshal()

### ISSUE THREAD

**Issue by flimzy** [golang/go#16578]
I would like to see `encoding/json` support email-style formatted base64 input.  That is to say, I would like to see the following code not panic.

    var data []byte = []byte(`
    ["VGhpcyBpcyBhIGxvbmcgdGV4dCBmaWxlLCBqdXN0IGZpbGxlZCBpbiB3aXRoIHJhbmRvbSB0ZXh0
    IHRvIGZvcmNlIGxpbmUKd3JhcHBpbmcgb25jZSBpdCdzIEJhc2U2NC1lbmNvZGVkLgo="]
    `)

    func main() {
    	dec := make([]string,0)
    	err := json.Unmarshal(data, &dec)
    	if err != nil {
    		panic(err)
    	}
    }

With the current implementation, however, it does panic:

> panic: invalid character '\n' in string literal

Why? It would make it easier to write readable unit tests of code that does a lot of marshaling and unmarshaling of custom data types.

I can't imagine it would be especially expensive to support this feature always, as I imagine simply filtering out all whitespace from the input stream would do it. But if it did prove to be expensive, supporting it only optionally some how would be reasonable for me as well.

**Comment by cespare** [comment]
Your input isn't valid JSON, though. As http://www.json.org/ says, strings cannot contain control characters -- and that's what the error message indicates.

**Comment by flimzy** [comment]
Ah quite.  Then any implementation ought to be strictly optional.  But that does seem rather evil then.
