### ISSUE TITLE
runtime: External tests not run with the correct compiler

### ISSUE THREAD

**Issue by quentinmit** [golang/go#16577]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go 1.7rc4

3. What did you do?

$ cd go/
$ ./src/make.bash
$ ./bin/go test -short runtime

4. What did you expect to see?
Tests run with ./bin/go

5. What did you see instead?
Tests run with the first "go" in $PATH (in this case, the "go" on $PATH was broken, so the tests failed.)

**Comment by bradfitz** [comment]
There's already this in `testenv`:

```go
// GoToolPath reports the path to the Go tool.                                                                                                       
// If the tool is unavailable GoToolPath calls t.Skip.                                                                                               
// If the tool should be available and isn't, GoToolPath calls t.Fatal.                                                                              
func GoToolPath(t *testing.T) string {
        MustHaveGoBuild(t)
```

There's probably stuff not using it.

**Comment by randall77** [comment]
Excellent, that's new to me.  We should use GoToolPath instead of the MustHaveGoBuild + "go" combo.
Same for MustHaveGoRun, I guess.
