### ISSUE TITLE
mmap uses unsigned for offset

### ISSUE THREAD

**Issue by jnewlin1970** [golang/go#16576]
https://golang.org/src/runtime/mmap.go

offset is unsigned, but the mmap syscall takes an off_t that is signed 32-bit.

**Comment by mdempsky** [comment]
I don't think it matters in practice.  The runtime only uses mmap for MAP_ANON mappings, and always passes 0 as the offset.  (Also, off_t is 64-bit on some OSes.)

Closing as non-issue.  But if you have a proposal for how to fix it, I'd listen.
