### ISSUE TITLE
regexp panics with malformed expression

### ISSUE THREAD

**Issue by jnewlin1970** [golang/go#16574]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
play.golang.org

3. What did you do?
https://play.golang.org/p/d8aVBAeFjc

4. What did you expect to see?
An error that the regexp is malformed?

5. What did you see instead?
panic

**Comment by jnewlin1970** [comment]
Here's another panic, I sort of expected this to work
https://play.golang.org/p/9RTKkTe7o_

**Comment by fraenkel** [comment]
In both cases you aren't checking the error coming back from Compile which are non-nil.

**Comment by bradfitz** [comment]
Not a bug. Check your errors.
https://play.golang.org/p/xqUuc-HSMB
