### ISSUE TITLE
website: In 'hello world', include GitHub repo and clarify user name

### ISSUE THREAD

**Issue by MarkDBlackwell** [golang/go#16584]
Documentation webpage [Getting Started](https://golang.org/doc/install)—in section [Test your installation](https://golang.org/doc/install#testing)—currently says:

> Next, make the directories src/github.com/**_user**_/hello inside your workspace (if you use GitHub, substitute your **_user name**_ for user),

The following would be better:

> Next, make the directories src/github.com/user/**_try-golang**_/hello inside your workspace (if you use GitHub, substitute your **_GitHub**_ user name for user),

(The bolding is just for emphasis in this issue.)

The new text aids novice Go users, in two ways:
1. Novices will wonder where their GitHub [repo](https://help.github.com/articles/github-glossary/#repository) names fit in the pattern. This will slow them down, and be frustrating. The new text supplies the answer (`try-golang`, in this case).
2. "User name" seems (in effect) ambiguous here.

Novice Go users (by definition) are unfamiliar with the semantics of Go's workspace directory structure. For them (as well as generally, outside Go), the most commonly used context for the term "user name" is OS X, Linux or Windows—not GitHub.

Likely they'd assume the former (as I did). They can figure it out, but why include this stumbling block in the first place?

The new text specifies it means the GitHub user name.

This change aims to help smooth the path, for new Go language users.

---
1. What version of Go are you using (`go version`)? N/A
2. What operating system and processor architecture are you using (`go env`)? N/A
3. What did you do? N/A
4. What did you expect to see? N/A
5. What did you see instead? N/A

**Comment by ALTree** [comment]
That section has been rewritten for go1.8 after the introduction of default GOPATH, and there's now no reference to `github.com/usr` paths

> Create your workspace directory, $HOME/go. (If you'd like to use a different directory, you will need to set the GOPATH environment variable; see How to Write Go Code for details.)
> 
> Next, make the directory src/hello inside your workspace, and in that directory create a file named hello.go that looks like:

So this is fixed.
