### ISSUE TITLE
gccgo: crypto/sha1 FAIL: TestOutOfBoundsRead on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#16592]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7rc3 gccgo (GCC) 7.0.0 20160803 (experimental) linux/ppc64le

2. What operating system and processor architecture are you using (`go env`)?
ppc64le Ubuntu

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Built gccgo from trunk, ran the go testsuite:
make check-go

4. What did you expect to see?
crypto/sha1 pass

5. What did you see instead?
...
--- FAIL: TestOutOfBoundsRead (0.00s)
panic: invalid argument [recovered]
        panic: invalid argument

goroutine 25 [running]:
runtime_dopanic
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/panic.c:131
__go_panic
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-panic.c:111
testing.$nested8
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:568
__go_panic
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-panic.c:67
crypto_sha1_test.TestOutOfBoundsRead
        /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest4102/test/issue15617_test.go:23
testing.tRunner
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:609
kickoff
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:235
created by testing.Run.pN9_testing.T
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:645

goroutine 16 [chan receive]:
runtime_mcall
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:295
runtime_park
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1871
runtime_parkunlock
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1887
chanrecv
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/chan.goc:269
testing.Run.pN9_testing.T
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:646
testing.$nested9
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:792
testing.tRunner
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:609
testing.RunTests
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:790
testing.Run.pN9_testing.M
        /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:742
main.main
        /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/gotest4102/test/_testmain.go:42
runtime_main
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:626
created by main
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-main.c:54

goroutine 17 [syscall]:
        goroutine in C code; stack unavailable
created by runtime_main
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:295
runtime_park
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1871
runtime_parkunlock
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1887
runfinq
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/mgc0.c:2512
kickoff
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:235
created by runtime_createfing
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/mgc0.c:2577

goroutine 19 [GC sweep wait]:
runtime_mcall
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:295
runtime_park
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1871
runtime_parkunlock
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:1887
bgsweep
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/mgc0.c:1844
kickoff
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:235
created by mgc
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/mgc0.c:2215

goroutine 20 [syscall]:
        goroutine in C code; stack unavailable
created by addtimer
        /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/time.goc:147
Keeping gotest4102
FAIL: crypto/sha1
...

This failure is new with the update to Go 1.7rc3 in r238662.

**Comment by ianlancetaylor** [comment]
I believe this was fixed earlier today by https://golang.org/cl/25460 .
