### ISSUE TITLE
crypto/rsa: GenerateKey never returns on some values of bits

### ISSUE THREAD

**Issue by steve-wang** [golang/go#16596]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.3

2. What operating system and processor architecture are you using (`go env`)?
windows10/amd64
ubuntu16.04/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/gYYUDxj6Z5

**Comment by minux** [comment]
Docs issue. crypto/rsa.GenerateKey doesn't support generating
toy keys (<7 bits).

**Comment by steve-wang** [comment]
How about returning an error or even panicking?

**Comment by odeke-em** [comment]
@minux doesn't seem like it works for even 8 bit keys https://play.golang.org/p/a7Ig2HcKzz, but it does work for 7 bits.

**Comment by bradfitz** [comment]
A panic would be fine. But an error would be even better, since the function already returns an error.

**Comment by shethchintan7** [comment]
8 bit key generation is failing because of how prime numbers are generated, only possible 4 bit prime that can be generated is 13 while the function requires two distinct primes. 7 works as it generates one 4 bit and one 3 bit prime similar case for 5
