### ISSUE TITLE
cmd/compille: BCE checking not optimized at some places

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#16595]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go1.7rc5 

2. What operating system and processor architecture are you using (`go env`)?

linux/amd64

3. What did you do?

`package main

import "math/rand"

func f(s []int, index int) {
	_ = s[:index] // yes
	_ = s[index:] // yes // bug?
}

func main() {
	s := []int{0, 1, 2, 3, 4, 5, 6}
	index := rand.Intn(7)
	_ = s[:index] // yes
	_ = s[index:] // no
}`

4. What did you expect to see?

no need to check boundary for the 2nd "s[index:]"

5. What did you see instead?

still check boundary for the 2nd "s[index:]"

**Comment by josharian** [comment]
cc @brtzsnr

**Comment by brtzsnr** [comment]
Working as intended as demonstrated here: https://play.golang.org/p/odv9EPjbFP

_For slices, the upper index bound is the slice capacity cap(a) rather than the length._
 -- https://golang.org/ref/spec#Slice_expressions

**Comment by yaxinlx** [comment]
cool optimization for knowing capacity==length!
