### ISSUE TITLE
strings.FieldsFunc crash with different condition for count of fields

### ISSUE THREAD

**Issue by mattn** [golang/go#16594]
See https://medium.com/@mlowicki/how-to-crash-strings-fieldsfunc-in-go-8aca27624a28#.ih32mpwxw

If returns different condition for counting fields, FieldsFunc crash. It should avoid out of index.

Most easy way to fix is:
```go
diff --git a/src/strings/strings.go b/src/strings/strings.go
index 919e8c8..df1530e 100644
--- a/src/strings/strings.go
+++ b/src/strings/strings.go
@@ -333,7 +333,7 @@ func FieldsFunc(s string, f func(rune) bool) []string {
 			fieldStart = i
 		}
 	}
-	if fieldStart >= 0 { // Last field might end at EOF.
+	if na < n && fieldStart >= 0 { // Last field might end at EOF.
 		a[na] = s[fieldStart:]
 	}
 	return a
```

**Comment by mattn** [comment]
I don't have strong opinion whether fixing this or not because I think that this is wrong usage of the strings.FieldsFunc.

**Comment by mattn** [comment]
Well, I feel this function bits inefficiency. How about store []bool for the index?

**Comment by josharian** [comment]
As I read it, that blog post is just explaining a line from the documentation about which the reader might be curious. Given that this limitation is already documented, however, and since this is not a coherent use of the function, I don't see a need to change anything to try to avoid the panic.

**Comment by mattn** [comment]
```go
package main

import (
	"fmt"
	"strings"
)

func fieldsFunc(r rune) bool {
	// implement something here
}

func main() {
	fmt.Println(strings.FieldsFunc("foo", fieldsFunc))
}
```
If we will implement this, I wonder we will consider the function will be called twice, and it should be retuned same condition always.

**Comment by josharian** [comment]
I'd say it doesn't matter. The documentation is clear: The function must return consistent results.

**Comment by mattn** [comment]
Ah, I missed it in the document.

**Comment by josharian** [comment]
No prob. I am going to close this issue. Feel free to comment if you think it should be reopened.
