### ISSUE TITLE
x/mobile: Binding go mobile framework on iOS 10 causing memory issues

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [golang/go#16598]
[Decryptor.framework.zip](https://github.com/golang/go/files/401252/Decryptor.framework.zip)
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/AlexSFD/Sn0wfreeze-Dev/GO"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

On iOS I/m testing on an iPhone 6S with arm64 and iOS 10 beta 4 installed

3. What did you do?
If possible, provide a recipe for reproducing the error.

Build a go framework with  
gomobile bind -target=ios <#pathToGoProject#>  
Include the framework into a running Xcode project 

Run it on an iOS 10 arm64 device. The framework is not able to load into memory and causes a crash 

4. What did you expect to see?
The App should start and run. All framework methods should be available and work as expected

5. What did you see instead?
The app crashes with a strange memory bug  before it starts. 

error: memory read failed for 0x2c3891c1600
runtime/cgo: chdir(/var/containers/Bundle/Application/7D8670DC-7F07-4F6C-BB81-1B3DEBB7EBE1/Cryptocall%20Enterprise.app) failed

**Comment by bytex64** [comment]
Having the same problem with my project. Early in app startup, a newly-started thread crashes by trying to execute memory it doesn't have access to. This bad address is the only frame in the backtrace.

**Comment by merickson** [comment]
While working with @bytex64 , I determined that this issue *does not* reproduce in the iOS 10 simulator, but on ARM hardware only.

**Comment by dcu** [comment]
do you think this is related to #16570 ?

**Comment by merickson** [comment]
$5 says it is.

**Comment by bytex64** [comment]
I would say it's likely related. It's also worth noting that this worked in early iOS 10 betas, suggesting that the same change in Sierra betas also broke it in iOS 10.

**Comment by merickson** [comment]
Yeah, it's fixed along with #16570, see https://github.com/golang/go/commit/9fde86b0124b8c75000eb5d05887eff922a24566

**Comment by dcu** [comment]
was this fixed? @Sn0wfreezeDev can you confirm?

**Comment by Sn0wfreezeDev** [comment]
Yes it was fixed !

**Comment by cmanus** [comment]
Can anyone tell me if this is available in the 1.7.1 stable release, it is tagged with 1.7.2 but I saw some notes about backport.
