### ISSUE TITLE
cmd/cgo: synthesized _cgoCheckPointer calls weaken function calling type checking

### ISSUE THREAD

**Issue by mdempsky** [golang/go#16591]
Trying to build this code:

    package p
    
    // extern void foo(int** p) {}
    import "C"
    
    type x *C.int
    
    func bar(**C.int) {
    }

    func f(p *x) {
    	C.foo(p)
    	bar(p)
    }

fails with:

    ./foo.go:13: cannot use p (type *x) as type **C.int in argument to bar

I.e., the `bar(p)` call is rejected, but the `C.foo(p)` call is not, even though they both logically have a parameter of type `**C.int`.

The `C.foo(p)` is being rewritten by cgo into:

        _Cfunc_foo(_cgoCheckPointer((**_Ctype_int)(p)).(**_Ctype_int))

The Go spec says function call arguments should be assignable to their corresponding parameters.  But because of the explicit conversion introduced by cgo, this requirement is being relaxed from assignability to convertibility.

Probably not an issue in practice, but I noticed it while addressing mdempsky/unconvert#16.

I think we could address this by generating type-specific _cgoCheckPointer wrappers, but until we can inline calls to non-leaf functions, that might be undesirable.

/cc @ianlancetaylor

**Comment by rsc** [comment]
It seems like we should fix this. It was broken in Go 1.7 so it's not terribly urgent, but the longer we wait the harder it is to fix. I don't really mind about having extra calls even without non-leaf inlining. OK to drop for Go 1.8 but if it's easy to fix, please do.
