### ISSUE TITLE
timer never triggering in a busy select

### ISSUE THREAD

**Issue by tv42** [golang/go#16608]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

```
go version go1.7rc5 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tv/go"
GORACE=""
GOROOT="/home/tv/src/go-1.6"
GOTOOLDIR="/home/tv/src/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/uAyqR8uG--

Won't run on playground, but grab https://play.golang.org/p/uAyqR8uG--.go and run locally.

4. What did you expect to see?

Some number of dots, and then "timeout" and program ending.

5. What did you see instead?

Infinite dots.

Adjusting timings makes the select sometimes notice the timer (second->dots, millisecond->dots, microsecond->"timeout" no dots, nanosecond->"timeout" no dots), but it seems far from "uniform pseudo-random" (https://golang.org/ref/spec#Select_statements), or the timer just doesn't trigger.

https://github.com/golang/go/issues/15706 might be relevant, but that issue is supposedly closed in 1.7rc5.

**Comment by bradfitz** [comment]
Your program is buggy. Each iteration makes a new 1 second timer.

**Comment by tv42** [comment]
Hah! Thanks. This came up on IRC and managed to fool at least three of us.
