### ISSUE TITLE
x/build: move off of google.golang.org/cloud

### ISSUE THREAD

**Issue by rakyll** [golang/go#16605]
Builder is still importing google.golang.org/cloud packages, need to switch to the new cloud.google.com/go and its new pattern of client construction.

/cc @bradfitz 

(I may have time to get this done later today, will assign it to me if I start.)

**Comment by rakyll** [comment]
Also /cc @broady.

**Comment by broady** [comment]
Addressed in https://go-review.googlesource.com/#/c/25464/
30d377d8a375e0c3a3b8ec0226957374e4d18edc
