### ISSUE TITLE
net/http: ambiguous sentence in docs for Response.ParseForm

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#16609]
Please answer these questions before submitting your issue. Thanks!

1 What version of Go are you using (`go version`)?

go1.6.2

2 What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cjohnson/Documents/Code/Golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3 What did you do?

```shell
$ go doc http.ParseForm
func (r *Request) ParseForm() error
    ParseForm parses the raw query from the URL and updates r.Form.

    For POST or PUT requests, it also parses the request body as a form and put
    the results into both r.PostForm and r.Form. POST and PUT body parameters
    take precedence over URL query string values in r.Form.

    If the request Body's size has not already been limited by MaxBytesReader,
    the size is capped at 10MB.

    ParseMultipartForm calls ParseForm automatically. It is idempotent.
```

4 What did you expect to see?

Grammatically unambiguous documentation.

5 What did you see instead?

In "It is idempotent," "it" ambiguously refers to `ParseForm` or `ParseMultipartForm` or both.

I think it should be `ParseForm`, but I'm not sure. Maybe both?

**Comment by odeke-em** [comment]
I just noticed another thing that can be improved in that documentation is fixing the typo
`and put the results`
to
`and puts the results`.
@carlmjohnson please feel free to send a CL for Go1.8, and we can review it.

**Comment by odeke-em** [comment]
@carlmjohnson the Go1.8 freeze begins in a few days, please let me know in the next few if you are interested in closing this otherwise I'll send a CL to fix this. Thanks.

**Comment by cespare** [comment]
@odeke-em the freeze doesn't so much apply to documentation changes.

**Comment by carlmjohnson** [comment]
I can try to look at this tonight.

**Comment by carlmjohnson** [comment]
https://go-review.googlesource.com/32091

**Comment by carlmjohnson** [comment]
https://golang.org/cl/70990044 in 2014 changed ParseForm to also update r.PostForm on PATCH, but didn't update the docs to reflect that…
