### ISSUE TITLE
encoding/xml: `,innerxml` values are not escaped.

### ISSUE THREAD

**Issue by txgruppi** [golang/go#16604]
1. What version of Go are you using (`go version`)?
```
go version go1.6.3 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
```

3. What did you do?
https://play.golang.org/p/r-pLR_UIXe

4. What did you expect to see?
```
<Company>Test &amp; Test</Company>
```

5. What did you see instead?
```
<Company>Test & Test</Company>
```

----

This is causing problems for other software to parse the generated XML file.

**Comment by quentinmit** [comment]
The docs do say "a field with tag ",innerxml" is written verbatim, not subject to the usual marshalling procedure". I feel like we probably can't change the behavior at this point.

What made you think that ampersands would be escaped?

**Comment by txgruppi** [comment]
I got problems when using `xmllint` or parsing the file using `python` so I imagined it was an error.

**Comment by minux** [comment]
I think this is working as intended.  Innerxml fields are supposed to
contain the exact inner XML data in verbatim. If we escape any
meta-characters then innerxml fields won't roundtrip anymore. The user is
supposed to provide valid XML for such fields.

**Comment by txgruppi** [comment]
I understand it, the user has to provide a valid value for the field. I'm sorry about it.

**Comment by kostya-sh** [comment]
If you need automatic escaping you should use `,chardata`: https://play.golang.org/p/nJEc61MqkK

**Comment by txgruppi** [comment]
@kostya-sh this is great! :)

Thanks.
