### ISSUE TITLE
syscall: delete the "use" func

### ISSUE THREAD

**Issue by ahl** [golang/go#16607]
'src/syscall/syscall.go' contains this comment:

```
// use is a no-op, but the compiler cannot see that it is.
// Calling use(p) ensures that p is kept live until that point.
// This was needed until Go 1.6 to call syscall.Syscall correctly.
// As of Go 1.6 the compiler handles that case automatically.
// The uses and definition of use can be removed early in the Go 1.7 cycle.
//go:noescape
func use(p unsafe.Pointer)
```

Either this comment should be updated or `use` should be removed in 1.7 from `syscall.go` and `src/syscall/mksyscall.pl`.

Happy to do this work if it's wanted.

**Comment by bradfitz** [comment]
Sure, send a CL when the tree opens next week.

**Comment by Sajmani** [comment]
Brad notes that there are also uses of "use" in x/sys/unix.
