### ISSUE TITLE
crypto/x509: CreateCertificate can panic in asn1 code

### ISSUE THREAD

**Issue by jefferai** [golang/go#16603]
Please answer these questions before submitting your issue. Thanks!

(1) What version of Go are you using (`go version`)?

go version go1.7rc4 linux/amd64

(2) What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jeff/go"
GORACE=""
GOROOT="/home/jeff/src/go"
GOTOOLDIR="/home/jeff/src/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build022291271=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

(3) What did you do?

https://play.golang.org/p/P68H4kx8AF

Created a self-signed certificate. This goes away if I set a `SerialNumber` on the template. The documentation says that SerialNumber will be used from the template, but not that it is required (so it's reasonable to think that it may be randomly chosen if not set). Either way, I'd argue that there should be a check to detect this and return an error, rather than an undocumented panic situation.

(4) What did you expect to see?

An error.

(5) What did you see instead?

A panic.

**Comment by hirochachacha** [comment]
Here is a minimal code.
```
package main

import (
	"encoding/asn1"
	"math/big"
)

type A struct {
	B *big.Int
}

func main() {
	asn1.Marshal(A{})
}
```

**Comment by jefferai** [comment]
Whether that's a minimal code example depends on where the problem lies. It may be appropriate for asn1 to panic on a null big.Int; it may be that the appropriate fix is for the x509 package to ensure it never is and error if so.

**Comment by hirochachacha** [comment]
maybe yes, maybe no (I'm not a judge either:)
`asn1.Marshal` also undocumented panic at least.
