### ISSUE TITLE
cmd/go: unable to download gopkg.in/gcfg.v1

### ISSUE THREAD

**Issue by pkhadka56** [golang/go#16613]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

go get -u -v gopkg.in/gcfg.v1

4. What did you expect to see?
well it should run successfully but it didnt

5. What did you see instead?

FULL DEATLAIL:
# go get -u -v gopkg.in/gcfg.v1
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

My real problem was downloading another but it also stuck here:

# go get -u -v github.com/paulstuart/influxsnmp
github.com/paulstuart/influxsnmp (download)
github.com/influxdata/influxdb (download)
github.com/kardianos/osext (download)
github.com/paulstuart/snmputil (download)
github.com/hashicorp/go-immutable-radix (download)
github.com/hashicorp/golang-lru (download)
github.com/pkg/errors (download)
github.com/soniah/gosnmp (download)
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

Any help?

**Comment by broady** [comment]
I can't reproduce this, does it hang? I can't see an error in your output.

**Comment by pkhadka56** [comment]
yes it stuck there.

go get -u -v gopkg.in/gcfg.v1

Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

[after this nothing happens]

**Comment by pkhadka56** [comment]
FYI I was following http://lkhill.com/using-influxdb-grafana-to-display-network-statistics/ 

You will find steps I am followingin "Influxsnmp" section.

**Comment by broady** [comment]
What happens when you run `git clone https://gopkg.in/gcfg.v1 gcfg`? (anywhere)

**Comment by pkhadka56** [comment]
current output:

\# git clone https://gopkg.in/gcfg.v1 gcfg
Initialized empty Git repository in /root/gcfg/.git/

Hmm nothing is happening. can we enable verbose mode?

**Comment by broady** [comment]
I think you should take it up with the gopkg.in folks. Looks like it's not
related to "go get".

**Comment by pkhadka56** [comment]
Hmm. Thanks.

**Comment by davecheney** [comment]
This issue is sometimes caused by a .gitconfig line that redirects https://
to ssh:// and then git hangs because it's waiting for you to type the
passphrase to your ssh key.

**Comment by justinkillen** [comment]
Upgrading git seemed to fix this for me
