### ISSUE TITLE
gddo: play links not working (Forbidden)

### ISSUE THREAD

**Issue by ulrichSchreiner** [golang/go#16617]
hi,

many of the examples in godoc.org do not work when clicking on *play*. Is this the desired behaviour?

For example: when going to this example:

https://godoc.org/time#example-Time-Format

and click on the "play" link, i'm redirect to this URL "https://play.golang.org/p/Forbidden" with the content "Snippet not found".

I tried many examples with a "play" link .... i always get "Snippet not found"

 - https://godoc.org/time?play=Time-Format
 - https://godoc.org/net/url?play=URL
 - https://godoc.org/io/ioutil?play=ReadAll

I'm using current Chrome on Ubuntu, my Location is Germany

</usc>

**Comment by broady** [comment]
Looking.

**Comment by broady** [comment]
Deployed.
