### ISSUE TITLE
Add _ignore file suffix support

### ISSUE THREAD

**Issue by emersion** [golang/go#16615]
Go already supports `_GOOS`, `_GOARCH` and `GOOS_GOARCH` fix suffixes. Add support for `_ignore` that is the same as `// +build ignore`. That can be useful when providing Go templates, e.g. `config_ignore.go` that contains config with empty fields so the user can `cp config_ignore.go config.go` and fill `config.go`.

**Comment by cznic** [comment]
> Add support for `_ignore` that is the same as `// +build ignore`

Why duplicate an already existing functionality?

**Comment by kostya-sh** [comment]
All files that start with `_` are ignored. You can name your file `_config.go`

**Comment by emersion** [comment]
Ow, didn know that, thanks @kostya-sh :-)
