### ISSUE TITLE
Program hangs and never terminates

### ISSUE THREAD

**Issue by arelangi** [golang/go#16611]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
````
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/golibs"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
````

3. What did you do?
````go
package main

import (
	"fmt"
	"time"
)

func main() {
	ticker := time.NewTicker(time.Millisecond)
	cond := false
	go func() {
		for {
			time.Sleep(time.Microsecond)
			//fmt.Print(".") // This can be any set of operations after sleep, just to show that the porgram is running
		}
	}()

	go func() {
		for {
			if cond {
				select {
				case v := <-ticker.C:
					fmt.Println("Ticker ticking ", v)
				}
			}
		}
	}()

	time.Sleep(time.Second)
	fmt.Println("Exiting")
}
````
[link on play.golang.org](https://play.golang.org/p/gNBp6Oc9Eh)

4. What did you expect to see?

- I expected the program to terminate after printing "Exiting", but it doesn't.

5. What did you see instead?

- The program just hangs, it doesn't terminate but consumes cpu. If the comment is removed on the `fmt.Print(".")`, you will see output being printed for sometime after which we do not see anything being printed and the program just hangs.
- If the cond is changed to true instead of false, the programs runs fine.

**Comment by davecheney** [comment]
You're program has an infinite loop, it's blocking the scheduler scheduling
the main goroutine so the program doesn't exit.

**Comment by arelangi** [comment]
Got it. Thanks!
