### ISSUE TITLE
the go.exe returns none under windows

### ISSUE THREAD

**Issue by horizon3d** [golang/go#16614]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
I installed a stable release of go1.6.3 on my windows. However, i execute 'go version' under the cmd.exe as administrator.

2. What operating system and processor architecture are you using (`go env`)?
my development environment is  the windows7 enterprise. 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

actually, i had ever built projects written using golang. But i cannot use it after my pc joined into an domain of my company. I tried 'go version' 'go help'... etc, but it cannot returns any words.
I am sure that GOROOT and GOPATH is set.
Therefore, I can only launch the remote Linux(CentOS 7.1) machine and upload my project code to build my project.

**Comment by horizon3d** [comment]
$ ls
go.exe*  godoc.exe*  gofmt.exe*

milky@PC-Milky MINGW64 /c/Go/bin
$ go version

milky@PC-Milky MINGW64 /c/Go/bin
$ go build


=====================================
that all my console returns
I just hide the username and hostname of windows

**Comment by alexbrainman** [comment]
Please try and use Windows command prompt (cmd.exe) to run 'go' command. Do not use mingw shell.

Thank you.

Alex

**Comment by horizon3d** [comment]
C:\Go\bin>dir
 C:\Go\bin 的目录
2016-07-13  10:20    <DIR>          .
2016-07-13  10:20    <DIR>          ..
2016-04-19  23:51        12,507,648 go.exe
2016-04-19  23:52        18,429,440 godoc.exe
2016-04-19  23:51         4,080,640 gofmt.exe

C:\Go\bin>go

C:\Go\bin>go version

C:\Go\bin>go help

C:\Go\bin>
C:\Go\bin>

--------------------------------------
the output is those above
and i tried to install go1.6.3 again, but it doesn't work

**Comment by mattn** [comment]
@horizon3d could you please try this?

```
C:\Go\bin>go version > version.log
C:\Go\bin>type version.log
```

**Comment by horizon3d** [comment]
C:\Go\bin>
C:\Go\bin>go version > ver.log

C:\Go\bin>type ver.log

C:\Go\bin>

that is the result above. and the output file is empty although the ver.log is producted

**Comment by alexbrainman** [comment]
I am puzzled. Maybe you could use gdb to run go.exe. See where it takes you.

Alex

**Comment by quentinmit** [comment]
Any chance your antivirus software thinks go.exe is malware? I suppose I could see that turning into a silent execution failure.

**Comment by horizon3d** [comment]
i run the go.exe using the windows7 compatibility mode, and now it works well.

**Comment by mattn** [comment]
@horizon3d you are already in windows7 as you said.

> my development environment is the windows7 enterprise.

**Comment by horizon3d** [comment]
yes, that why i am puzzled. the os on my pc is windows7 enterprise X64. it worked well before i joined the domain. and then didn't work after i joined the domain util i run those executable files(.exe) under the windows7 compatibility mode.
that case would be test, i think

**Comment by alexbrainman** [comment]
What does `go version` and `go env` output (now that you can see their output) ?

Thank you.

Alex

**Comment by horizon3d** [comment]
C:\Windows\system32>go version
go version go1.6.3 windows/amd64

C:\Windows\system32>go env
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Coding
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

the output of `go version` and `go env`
that's the output expected

**Comment by alexbrainman** [comment]
> the output of go version and go env

Thank you. All looks OK to me.
I really don't know what your problem is.

Alex

**Comment by mattn** [comment]
@horizon3d what is different between https://github.com/golang/go/issues/16614#issuecomment-237767684 and https://github.com/golang/go/issues/16614#issuecomment-238453420 ?

**Comment by horizon3d** [comment]
one is returns nothing, and the other one return the expected output.
i don't understand what is your mean by different between the two output.

the only difference is that i set the executable file(s) to run under the comatibility mode, then it can output the result i expected.
@mattn
