### ISSUE TITLE
time: large times do not roundtrip through Format/Parse

### ISSUE THREAD

**Issue by zachjs** [golang/go#16639]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   `go version go1.6.3 darwin/amd64`
2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zach/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
1. What did you do?
   I created a `time.Time` using a large Unix timestampt that corresponds to a date with a year >9999. I formatted the time and parsed the result.
   Playground demo: https://play.golang.org/p/QSE-o48r5c
2. What did you expect to see?
   I expected Go to be able to parse the time it formatted using the same layout. Given that `Format` produced the timestamp, `time.Parse` should be able to parse it.
3. What did you see instead?
   It returned an error.

**Comment by bradfitz** [comment]
Doesn't seem worth caring about.

Do you actually care for some reason?

**Comment by zachjs** [comment]
This issue came to my attention when one of the customers for the software I work on filed a ticket about it.

I agree that it’s pretty ridiculous, but the software I work on may be used in some ridiculous ways, and I don’t want to lose support because the programming language’s standard library supports only the minimum ISO standard rather than the maximum (including optional bits).

**Comment by bradfitz** [comment]
Lose whose support? It sounds like they filed a ticket against you, so you are support, no? If your software needs to support years past 9999, you might have to write some specialized code instead of using the time package.

There are many things the time package doesn't do (like leap seconds: #15247, etc) or non-Gregorian calendars. It only aims to address the most common cases.

**Comment by rsc** [comment]
Not going to worry about this.
