### ISSUE TITLE
misc/cgo/testcarchive: TestSigaltstack flake on linux-amd64

### ISSUE THREAD

**Issue by aliasaila** [golang/go#16649]
```
##### misc/cgo/testcarchive
--- FAIL: TestSigaltstack (0.66s)
    carchive_test.go:438: looping too long waiting for signal
    carchive_test.go:439: exit status 1
```

go version go1.7rc6 linux/amd64

Debian GNU/Linux 8.5 (jessie)

gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by ianlancetaylor** [comment]
How repeatable is this?

**Comment by aliasaila** [comment]
Just ran the test in a loop. It failed 7 out of 20.

**Comment by ianlancetaylor** [comment]
I can not recreate the problem on my system (Ubuntu trusty).

Can you try this:

    cd $GOROOT/misc/cgo/testcarchive
    GOPATH=`pwd` go build -buildmode=c-archive -o libgo4.a libgo4
    gcc -o testp -g main4.c libgo4.a -lpthread

Simply running the program `testp` should now presumably fail 7 out of 20 times.  Run `strace -f ./testp`.  Attach the output of a failing run.

Thanks.

**Comment by aliasaila** [comment]
The test passed every run out of 100,000 when executed with "strace -f".

Without the "-f" flag, I get this:
```
execve("./testp", ["./testp"], [/* 18 vars */]) = 0
brk(0)                                  = 0x146b000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcbc05b3000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=20263, ...}) = 0
mmap(NULL, 20263, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fcbc05ae000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20o\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=137440, ...}) = 0
mmap(NULL, 2213008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fcbc0178000
mprotect(0x7fcbc0190000, 2093056, PROT_NONE) = 0
mmap(0x7fcbc038f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fcbc038f000
mmap(0x7fcbc0391000, 13456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fcbc0391000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1738176, ...}) = 0
mmap(NULL, 3844640, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fcbbfdcd000
mprotect(0x7fcbbff6f000, 2093056, PROT_NONE) = 0
mmap(0x7fcbc016e000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a1000) = 0x7fcbc016e000
mmap(0x7fcbc0174000, 14880, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fcbc0174000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcbc05ad000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcbc05ab000
arch_prctl(ARCH_SET_FS, 0x7fcbc05ab740) = 0
mprotect(0x7fcbc016e000, 16384, PROT_READ) = 0
mprotect(0x7fcbc038f000, 4096, PROT_READ) = 0
mprotect(0x7fcbc05b5000, 4096, PROT_READ) = 0
munmap(0x7fcbc05ae000, 20263)           = 0
set_tid_address(0x7fcbc05aba10)         = 3535
set_robust_list(0x7fcbc05aba20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fcbc017e9f0, [], SA_RESTORER|SA_SIGINFO, 0x7fcbc01878d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fcbc017ea80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fcbc01878d0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
rt_sigaction(SIGIO, {0x40113a, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fcbc01878d0}, NULL, 8) = 0
rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGILL, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTRAP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGABRT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGBUS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGBUS, {0x4542b0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x454370}, NULL, 8) = 0
rt_sigaction(SIGFPE, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGFPE, {0x4542b0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x454370}, NULL, 8) = 0
rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSEGV, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSEGV, {0x4542b0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x454370}, NULL, 8) = 0
rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSTKFLT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGURG, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXCPU, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGXFSZ, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGVTALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPROF, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGWINCH, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGIO, NULL, {0x40113a, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGIO, NULL, {0x40113a, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGPWR, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSYS, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRTMIN, NULL, {0x7fcbc017e9f0, [], SA_RESTORER|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGRTMIN, NULL, {0x7fcbc017e9f0, [], SA_RESTORER|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGRTMIN, {0x7fcbc017e9f0, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fcbc01878d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, NULL, {0x7fcbc017ea80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGRT_1, NULL, {0x7fcbc017ea80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGRT_1, {0x7fcbc017ea80, [], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x7fcbc01878d0}, NULL, 8) = 0
rt_sigaction(SIGRT_2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_3, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_4, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_5, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_6, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_7, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_8, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_9, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_10, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_11, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_12, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_13, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_14, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_15, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_16, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_17, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_18, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_19, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_20, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_21, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_22, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_23, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_24, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_25, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_26, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_27, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_28, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_29, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_30, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_31, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGRT_32, NULL, {SIG_DFL, [], 0}, 8) = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fcbbf5cc000
brk(0)                                  = 0x146b000
brk(0x148c000)                          = 0x148c000
mprotect(0x7fcbbf5cc000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fcbbfdcbfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fcbbfdcc9d0, tls=0x7fcbbfdcc700, child_tidptr=0x7fcbbfdcc9d0) = 3536
futex(0x6b01c4, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x6b0180, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x6b0180, FUTEX_WAKE_PRIVATE, 1)  = 0
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
sigaltstack(NULL, {ss_sp=0, ss_flags=SS_DISABLE, ss_size=0}) = 0
sigaltstack({ss_sp=0xc420026000, ss_flags=0, ss_size=32672}, NULL) = 0
gettid()                                = 3535
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0xc420024110, FUTEX_WAIT, 0, NULL) = 0
futex(0xc420024910, FUTEX_WAKE, 1)      = 1
futex(0xc420024110, FUTEX_WAIT, 0, NULL) = 0
rt_sigaction(SIGIO, NULL, {0x40113a, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fcbc01878d0}, 8) = 0
rt_sigaction(SIGIO, {0x4542b0, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x454370}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
sigaltstack({ss_sp=0, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fcbbcdc7000
mprotect(0x7fcbbcdc7000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fcbbd5c6fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fcbbd5c79d0, tls=0x7fcbbd5c7700, child_tidptr=0x7fcbbd5c79d0) = 3541
futex(0x7fcbbd5c79d0, FUTEX_WAIT, 3541, NULL) = 0
clone(child_stack=0x7fcbbd5c6fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fcbbd5c79d0, tls=0x7fcbbd5c7700, child_tidptr=0x7fcbbd5c79d0) = 3542
futex(0x7fcbbd5c79d0, FUTEX_WAIT, 3542, NULL <unfinished ...>
+++ exited with 1 +++
```

**Comment by ianlancetaylor** [comment]
Thanks for trying it so many times.  Unfortunately, without the `-f` flag we don't see the essential information, like the delivery of the `SIGIO` signal.

Does the problem happen if you run the program under `gdb`?

**Comment by aliasaila** [comment]
It does happen under gdb.

**Comment by ianlancetaylor** [comment]
Well, if you are up for some debugging, I think the first step is to find out which test is failing.  There are two places the program can print that message.  Then we need to find out whether signal is being sent on the channel, which you can discover by setting a breakpoint on the call to `atomic.AddInt32` in src/libgo4/libgo4.go.  If not, we need to find out where it is being diverted between `runtime.sigtrampgo` and `runtime.sigsend`.

I totally understand if you don't want to tackle this.

**Comment by aliasaila** [comment]
I've been able to reproduce this on another linux machine, compiled with `gcc version 4.9.3 (Debian 4.9.3-14)`. The output of `strace -f` is attached.

To reproduce I had to set `GOMAXPROCS=1` and used these kernel settings (the default values from the first machine, a single core VPS):

```
kernel.sched_autogroup_enabled = 0
kernel.sched_child_runs_first = 0
kernel.sched_latency_ns = 6000000
kernel.sched_migration_cost_ns = 500000
kernel.sched_min_granularity_ns = 750000
kernel.sched_nr_migrate = 32
kernel.sched_rr_timeslice_ms = 7
kernel.sched_rt_period_us = 1000000
kernel.sched_rt_runtime_us = 950000
kernel.sched_shares_window_ns = 10000000
kernel.sched_time_avg_ms = 1000
kernel.sched_tunable_scaling = 1
kernel.sched_wakeup_granularity_ns = 1000000
```

[strace.txt.gz](https://github.com/golang/go/files/412502/strace.txt.gz)

**Comment by lufia** [comment]
I have same issue with go 1.7.1 on CentOS 7 on Hyper-V.

```
kernel.sched_autogroup_enabled = 0
kernel.sched_cfs_bandwidth_slice_us = 5000
kernel.sched_child_runs_first = 0
kernel.sched_latency_ns = 6000000
kernel.sched_migration_cost_ns = 500000
kernel.sched_min_granularity_ns = 1000000
kernel.sched_nr_migrate = 32
kernel.sched_rr_timeslice_ms = 100
kernel.sched_rt_period_us = 1000000
kernel.sched_rt_runtime_us = 950000
kernel.sched_shares_window_ns = 10000000
kernel.sched_time_avg_ms = 1000
kernel.sched_tunable_scaling = 1
kernel.sched_wakeup_granularity_ns = 15000000
```

To avoid this failure, I ran 
```
export GOMAXPROCS=2
./all.bash
```

**Comment by rsc** [comment]
@ianlancetaylor, in the strace listing, pid 26447 appears to be the C function thread1. This is the trace from the time 26447 starts executing until it does the sigreturn:

	26447 set_robust_list(0x7f70caffd9e0, 24 <unfinished ...>
	26444 <... select resumed> )            = 0 (Timeout)
	26447 <... set_robust_list resumed> )   = 0
	26447 mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0 <unfinished ...>
	26444 select(0, NULL, NULL, NULL, {0, 640} <unfinished ...>
	26448 set_robust_list(0x7f70ca7fc9e0, 24 <unfinished ...>
	26447 <... mmap resumed> )              = 0x7f70bc000000
	26448 <... set_robust_list resumed> )   = 0
	26447 munmap(0x7f70c0000000, 67108864 <unfinished ...>
	26448 sigaltstack(NULL,  <unfinished ...>
	26447 <... munmap resumed> )            = 0
	26448 <... sigaltstack resumed> {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
	26447 mprotect(0x7f70bc000000, 143360, PROT_READ|PROT_WRITE <unfinished ...>
	26448 sigaltstack({ss_sp=0xc420074000, ss_flags=0, ss_size=32672},  <unfinished ...>
	26447 <... mprotect resumed> )          = 0
	26448 <... sigaltstack resumed> NULL)   = 0
	26448 gettid( <unfinished ...>
	26447 sigaltstack({ss_sp=0x7f70bc0008c0, ss_flags=0, ss_size=8192},  <unfinished ...>
	26448 <... gettid resumed> )            = 26448
	26447 <... sigaltstack resumed> NULL)   = 0
	26448 rt_sigprocmask(SIG_SETMASK, [],  <unfinished ...>
	26447 tgkill(26442, 26447, SIGIO <unfinished ...>
	26448 <... rt_sigprocmask resumed> NULL, 8) = 0
	26447 <... tgkill resumed> )            = 0
	26448 futex(0xc42002d510, FUTEX_WAIT, 0, NULL <unfinished ...>
	26447 --- SIGIO {si_signo=SIGIO, si_code=SI_TKILL, si_pid=26442, si_uid=1000} ---
	26447 rt_sigprocmask(SIG_SETMASK, NULL, ~[KILL STOP], 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
	26447 sigaltstack(NULL, {ss_sp=0x7f70bc0008c0, ss_flags=SS_ONSTACK, ss_size=8192}) = 0
	26447 gettid()                          = 26447
	26447 rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP BUS FPE KILL SEGV STKFLT CHLD STOP PROF RTMIN RT_1], NULL, 8) = 0
	26447 futex(0x6cb000, FUTEX_WAKE, 1)    = 1
	26443 <... futex resumed> )             = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[],  <unfinished ...>
	26443 futex(0x6b1230, FUTEX_WAIT, 0, NULL <unfinished ...>
	26447 <... rt_sigprocmask resumed> NULL, 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[KILL STOP], NULL, 8) = 0
	26447 rt_sigreturn({mask=[]})           = 0

I'm pretty sure the aggressive mask a few lines from the bottom is the point where Go takes over the thread, and then the restoration of `~[KILL STOP]` marks returning back to C, and then of course the rt_sigreturn.

Then it goes into a loop:

	26447 rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
	26447 sigaltstack(NULL, {ss_sp=0x7f70bc0008c0, ss_flags=0, ss_size=8192}) = 0
	26447 gettid()                          = 26447
	26447 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
	26447 sched_yield()                     = 0

	26447 rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
	26444 <... select resumed> )            = 0 (Timeout)
	26447 sigaltstack(NULL, {ss_sp=0x7f70bc0008c0, ss_flags=0, ss_size=8192}) = 0
	26447 gettid()                          = 26447
	26447 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
	26447 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
	26447 sched_yield()                     = 0

	...

That's this C code:

	// Wait until the signal has been delivered.
	i = 0;
	while (SIGIOCount() == 0) {
		if (sched_yield() < 0) {
			perror("sched_yield");
		}
		i++;
		if (i > 100000) {
			fprintf(stderr, "looping too long waiting for signal\n");
			exit(EXIT_FAILURE);
		}
	}

The setting of the mask to `~[]` and the call to sigaltstack mark the entry into Go. The sigaltstack is to fetch the signal stack settings and I think decide if we're on the signal stack. The gettid marks the end of minit during needm. Then Go runs briefly and starts undoing the sigprocmask changes and eventually gets back out to C, which calls sched_yield and we repeat.

From the fact that this only happens with GOMAXPROCS=1, it sounds like maybe these repeated calls into Go from C are starving out the signal handling goroutine:

	func GoCatchSIGIO() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGIO)
		go func() {
			for range c {
				atomic.AddInt32(&sigioCount, 1)
			}
		}()
	}

Unless the goal of this test is to make sure that Go can move forward when C is in a high-frequency "call into Go" loop, I wonder if maybe there should be a sleep on the C side instead of just sched_yield.

What do you think?

**Comment by ianlancetaylor** [comment]
@rsc thanks for debugging, will send CL.

**Comment by ianlancetaylor** [comment]
@aliasaila Can you see if the patch in https://golang.org/cl/33239 fixes the problem?  Thanks.
