### ISSUE TITLE
doc: proposed wording change for context

### ISSUE THREAD

**Issue by MichaelTJones** [golang/go#16642]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.7rc6

2. What operating system and processor architecture are you using (`go env`)?

moot

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

moot

4. What did you expect to see?

moot

5. What did you see instead?

Introductory paragraph on "what's changed" reads:

The release adds a port to IBM LinuxOne; updates the x86-64 compiler back end to generate more efficient code; includes the context package, promoted from the x/net subrepository and now used in the standard library; and adds support in the testing package for creating hierarchies of tests and benchmarks. The release also finalizes the vendoring support started in Go 1.5, making it a standard feature.

Proposed change permutes the reference order within the third clause...

The release adds a port to IBM LinuxOne; updates the x86-64 compiler back end to generate more efficient code; promotes the context package from the x/net subrepository to the standard library; and adds support in the testing package for creating hierarchies of tests and benchmarks. The release also finalizes the vendoring support started in Go 1.5, making it a standard feature.

**Comment by broady** [comment]
This does miss one small note, that the `context` package is now used in the standard library. I'll try to retain that.

**Comment by broady** [comment]
@MichaelTJones I can't think of wording that retains the information that `context` is used within the standard library better than the way it is currently.

If you can, please suggest it.

**Comment by MichaelTJones** [comment]
Hmm… How about:

 

promoted the <a href="#context">context package</a> from the

<a href="https://golang.org/x/net/context">x/net subrepository</a>

into and used by the standard library;

**Comment by quentinmit** [comment]
Go 1.7 has been shipped now.
