### ISSUE TITLE
runtime: closeonexec return value ignored

### ISSUE THREAD

**Issue by josharian** [golang/go#16641]
Quoting runtime/sys_openbsd_arm.s:

```
// int32 runtime·closeonexec(int32 fd);
TEXT runtime·closeonexec(SB),NOSPLIT,$0
	MOVW	fd+0(FP), R0		// arg 1 - fd
	MOVW	$2, R1			// arg 2 - cmd (F_SETFD)
	MOVW	$1, R2			// arg 3 - arg (FD_CLOEXEC)
	MOVW	$92, R12		// sys_fcntl
	SWI	$0
	RSB.CS	$0, R0
	MOVW	R0, ret+4(FP)
	RET
```

The comment at the top indicates an int32 return value, and the second to last line confirms that. However, the Go function prototype (runtime/netpoll_{epoll,kqueue}.go) has no return value:

```go
func closeonexec(fd int32)
```

And openbsd/arm appears to be the only platform in which we attempt to return a value.

Discovered while working on the interminable (but valuable?) #11041.

Input requested. Should we:

* eliminate the bad ret value write in openbsd/arm
* accept a return value from closeonexec, update all the other platforms to provide it, and then use it

**Comment by ianlancetaylor** [comment]
There is no reasonable action the runtime can take if `closeonexec` fails, other than simply carry on, and there is no actual likelihood of failure, so I think we should consistently not return a value.

**Comment by josharian** [comment]
Great. Thanks, Ian. I'm on it.
