### ISSUE TITLE
net/mail: export parseDate?

### ISSUE THREAD

**Issue by themihai** [golang/go#16657]
RFC5322 has [resent fields](https://tools.ietf.org/html/rfc5322#appendix-A.3). Therefore we need a key param on (Header).Date() method so that we can parse the "Resent-Date" header. I see 3 possible options:

```
// key is optional for backwards compatibility. If it's not set it parses "Date"
func (h Header) Date(key ...string) (time.Time, error)

// Parses "Resent-Date" header.
func (h Header) DateReset() (time.Time, error)

// Parse a date-time format as specified in rfc5322

func ParseDate(s string)(time.Time, error)
```

**Comment by bradfitz** [comment]
We can't change Header.Date.

Exposing "func ParseDate" seems fine. Of course, the workaround is pretty easy too:

https://play.golang.org/p/SvuD6Mahsb
```go
func main() {
	h := mail.Header{"Resent-Date": {"Wed, 10 Aug 2016 02:37:48 -0700"}}

	fmt.Println(mail.Header{"Date": {h.Get("Resent-Date")}}.Date())
}
```
