### ISSUE TITLE
golint crashes with "index out of range"

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#16654]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

build from the tip:
go version devel +392bf3a Tue Aug 9 00:43:25 2016 +0000 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yoshiki/gocode:/home/yoshiki/gpl_exercises"
GORACE=""
GOROOT="/home/yoshiki/go"
GOTOOLDIR="/home/yoshiki/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build975893472=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

 $ go get gopl.io/ch12/display
 $ golint gopl.io/ch12/display

4. What did you expect to see?
 No panic

5. What did you see instead?

[panic.txt](https://github.com/golang/go/files/410419/panic.txt)

**Comment by sillyousu** [comment]
`go get -u  github.com/golang/lint` should fix this.

**Comment by sillyousu** [comment]
Binary package encoding format changed. `lint` use outdate gcimporter package cause this isuse.
https://github.com/golang/tools/blob/master/go/gcimporter15

**Comment by josharian** [comment]
Closing. @YoshikiShibata if you still have problems after updating lint, please add a comment here.

**Comment by YoshikiShibata** [comment]
I just confirmed that updating binaries fixed the problem. Thanks.
