### ISSUE TITLE
x/net/context/ctxhttp: implementation for <1.7 may not be correct

### ISSUE THREAD

**Issue by lujiajing1126** [golang/go#16668]
```
go version go1.6.3 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/megrez/Code/project/wosai/push/worker"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

I dont think the ctx implementation in go 1.6 is semantically correct `https://github.com/golang/net/blob/master/context/ctxhttp/ctxhttp_pre17.go`

It simply start a goroutine to do the request and discard response

It will send request first and the peer will receive the request and make response, which will make some mistake in some specific situations

Like a MQ server will consider A client has been received message so that the message cannot be consumed by B client who should have received this message.

consider following flow:

1. cancel `A` client, but the request `R` is under flying, for `R` is a blocking request
2. start client `B` and send a message `M`
3. `A` client may have chance to receive the message `M` for we cannot determine who will receive the message, so i have to wait all `A`'s requests fail then start B which may a waste of time

**Comment by bradfitz** [comment]
I'm not sure I understand your scenario. The ctxhttp has a bunch of tests, though. Perhaps you can write a test which demonstrates how it's wrong? Or explain it in pseudo-code?

/cc @broady @okdave

**Comment by lujiajing1126** [comment]
https://gist.github.com/lujiajing1126/d46af42294015274e926d52c850212d4

I wrote a server and client to reproduce the issue

It may express my idea more clearly

I mean calling `cancel` not really close the socket but just waits for the request done and discard the response

**Comment by lujiajing1126** [comment]
Sorry I may confused about that. I used `tcpdump` and `lsof` to diagnose the network problem and I found that there may be some error at server-end. It's nothing about the `ctxhttp` lib.

![](https://trello-attachments.s3.amazonaws.com/57ac526f246c0d92b19385de/600x165/4e639a76554beb7b0def2b9dc590a6bf/upload_12_8_2016_at_13_52_31.png)

![](https://trello-attachments.s3.amazonaws.com/57ac526f246c0d92b19385de/600x112/505f972358e1c7df7ce2c2f580889128/upload_12_8_2016_at_13_48_05.png)

The `CLOSE_WAIT` and the `tcpdump` logs show that the server did not response correctly

And I change my gist

**Comment by broady** [comment]
Great, thanks for the follow up, @lujiajing1126.
