### ISSUE TITLE
x/playground: support reading from os.Stdin

### ISSUE THREAD

**Issue by nathany** [golang/go#16667]
It would be great if newcomers could write interactive programs in The Go Playground by reading from `os.Stdin`.

E.g. https://play.golang.org/p/vYsHq3MUiO

[Google Cloud Shell](https://cloud.google.com/shell/docs/), [nitrous.io](https://www.nitrous.io), and [c9.io](https://c9.io/) have shell environments that support this, but they have associated fees and may be more complex than necessary for someone just starting out.

**Comment by cznic** [comment]
There's no way to cache the results of an interactive program.

**Comment by as** [comment]
Even thought it doesn't allow interactivity, you can read from os.Stdin on the playground if you assign it to another file.

https://play.golang.org/p/Y_6O1stTh1

**Comment by nathany** [comment]
Yah, I expected that it would prevent caching, which certainly complicates matters.

**Comment by minux** [comment]
Besides caching difficulties, the program also needs to kept running for
much much longer, which means much more resource usage when there are a lot
concurrent users.

That being said, if you run playground locally, I don't why it can't
support interactive programs as it's already using websocket for transport.

**Comment by nathany** [comment]
Thanks for the input -- definitely some things I hadn't considered.

I will continue writing Learn Go to use the Go playground without any expectation of this happening soon. The section on branching with `if` would be more realistic if the conditions for branching weren't hardcoded values or cached random numbers -- but it's not the end of the world.

**Comment by ysmolsky** [comment]
Playground is not supposed to be interactive platform. I would say implementing this feature requires another different beast than what we have. Don't want to be a party pooper but does it make sense to leave such bugs open when we cannot solve them, @andybons ?

**Comment by andybons** [comment]
Yeah I think this is outside the (admittedly non-codified) scope of playground. Closing.

**Comment by thebod** [comment]
Hi,

https://github.com/golang/go/issues/3806#issuecomment-66068339 suggests that using an input field / textarea might be simpler way of implementing this, and would actually allow to cache (and share) the program.
Essentially it's just a static buffer this way, which is attached to the NaCL sandbox's stdin.

If you guys think it makes sense to give it a try, I'd be happy to take over.

**Comment by andybons** [comment]
@thebod thanks for the offer. We're not going to be adding this functionality any time in the near future.

Perhaps if it was integrated into a playground alternative (e.g. https://goplay.space/) and became super popular we can reconsider, but for now we're going to go without it.
