### ISSUE TITLE
net/mail: ParseAddress fails if the name part contains round parentheses

### ISSUE THREAD

**Issue by zephyr** [golang/go#16692]
I'm using

	go version devel +31ad583 2016-08-10 19:44:08 +0000 linux/amd64

I tried to parse all email adresses from the `git log` output of <https://github.com/golang/go>.

`mail.ParseAddress` choked on five adresses. Two times it was legitimate; but three of them failed to parse just because they contain round parentheses in the name part.

Here is a minimal example:

	package main

	import (
		"fmt"
		"log"
		"net/mail"
	)

	func main() {
		s := "Hyang-Ah (Hana) Kim <hyangah@gmail.com>"
		a, err := mail.ParseAddress(s)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(a)
	}

I expected to see

	"Hyang-Ah (Hana) Kim" <hyangah@gmail.com>

but instead i see

	2016/08/14 21:28:50 mail: no angle-addr

Even if name aren’t allowed to contain round parentheses, the error message is confusing, because there clearly are square/angle bracket with an email adress between.

**Comment by hirochachacha** [comment]
I think that address format is illegal.
You can use `git log --pretty=format:'"%an" %aE'` to get a legal address.

I agree that error message is poor, though. 

Maybe,

`2016/08/14 21:28:50 mail: expected angle-addr, got '('`

is better?

**Comment by zephyr** [comment]
Thank you very much, this solves my issue!

And I totally agree that you version of the error message would be clearer.
