### ISSUE TITLE
fmt: Printf %v, %+v, %#v do not consider Stringer or GoStringer interfaces recursively

### ISSUE THREAD

**Issue by ScottMansfield** [golang/go#16698]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
$ go version
go version go1.6.3 darwin/amd64
```

I also checked tip.golang.org source to see if it had been changed. It hasn't.
https://tip.golang.org/src/fmt/print.go#L677

2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/smansfield/gopkg"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

This playground is the minimal example: https://play.golang.org/p/A9U4LteYyF

When creating an enum that is meant to be passed around in a larger struct, I wanted to create a human readable version of it. In this case, printing with any form of `v` doesn't do what I expect. The String() and GoString() methods are not considered when recurively printing the fields of a struct. This issue is stating that the Stringer and GoStringer interfaces should be checked in the printValue method and used if available.

https://tip.golang.org/src/fmt/print.go#L677

4. What did you expect to see?

```
{foo}
main.containsEnum{field1:go type foo}
{field1:foo}
foo
go type foo
foo
```

5. What did you see instead?

```
{0}
main.containsEnum{field1:0}
{field1:0}
foo
go type foo
foo
```

**Comment by martisch** [comment]
The field1 is unexported and needs to be exported by naming it Field1 otherwise fmt cant use reflect to "extract" the concrete value of field1 from the struct and user the Stringer and GoStringer interfaces.

```
type containsEnum struct {
	Field1 enumType
}
```

**Comment by minux** [comment]
Yeah, it's working as intended.
