### ISSUE TITLE
net/http/httputil: support for HTTP/2 in ReverseProxy

### ISSUE THREAD

**Issue by jmhodges** [golang/go#16696]
Currently, `httputil.ReverseProxy` [hardcodes the HTTP/1.1 protocol](https://github.com/golang/go/blob/6a6c1d9841a1957a2fd292df776ea920ae38ea00/src/net/http/httputil/reverseproxy.go#L182) in requests going to the backend service. It would be nice if it could support HTTP/2.

That hardcoding seems to have been around since the beginning of reverseproxy.go's existence, so I'm not sure if there are real constraints such that ReverseProxy can't be allowed to use the usual net/http HTTP protocol version detection or if this was just some dregs.

**Comment by bradfitz** [comment]
No reason I recall. I think it was just muscle memory when I wrote it.

**Comment by jmhodges** [comment]
I started digging into this, and can't seem to write a test that works.

The problem is that HTTP/2 is disabled on all clients that set `InsecureSkipVerify` on their transports, needed to use `httptest`'s HTTPS servers, because `TLSClientConfig` will be non-nil but there's no public func like http2.ConfigureTransport to reenable it. The one bundled in the net/http library is unexported and so are the structs it relies on.

But maybe there's something I missed?

**Comment by jmhodges** [comment]
(edited last comment to be more clear)

**Comment by bradfitz** [comment]
Actually, the hard-coding of the fields is pointless.

From the docs:

https://golang.org/pkg/net/http/#Request
```
        // The protocol version for incoming server requests.
        //
        // For client requests these fields are ignored. The HTTP
        // client code always uses either HTTP/1.1 or HTTP/2.
        // See the docs on Transport for details.
        Proto      string // "HTTP/1.0"
        ProtoMajor int    // 1
        ProtoMinor int    // 0
```

And I saw another bug where people were using ReverseProxy with HTTP/2 just fine. (But that wasn't the point of the bug, IIRC).

So I think there's nothing to do here.

I'll remove those lines from the ReverseProxy code, though.
