### ISSUE TITLE
x/exp/inotify: Remove watches from the internal map even if a directory is deleted

### ISSUE THREAD

**Issue by agorman** [golang/go#16709]
**What version of Go are you using (go version)?**

go version go1.6.1 linux/amd64

**What operating system and processor architecture are you using?**

CentOS 6
Intel Core 2 Duo
2.6.32-431.20.3.el6.centos.plus.x86_64 #1 SMP Thu Jun 19 23:04:15 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**

I deleted a directory that was being watched.

**What did you expect to see?**

If a directory is deleted I expect to be able to watch another directory that gets created with the same name.

**What did you see instead?**

If a watched directory is deleted from the OS it will never be removed from the watches map which cases a directory with the same name to never be able to be watched again during the programs execution.

My proposed change: https://github.com/agorman/exp/commit/66dcf7196d65fcc530adf9beb0fa954943bf6110

I created a gist for a program that shows the bug. You can test it against the current code and my proposed change. https://gist.github.com/agorman/000e5aca46827057accc8312bf55d989

Thanks

**Comment by chenchun** [comment]
Also happened to find this problem. I deleted a directory that was being watched, then I tried to invoke `inotify.RemoveWatch` and it erred out "inotify_rm_watch: invalid argument". I think disallowing to remove watch on a deleted directory is the normal behavior of kernel. `inotify.go` should delete the keys from `watches` and `paths` map and suppress the error returned by `syscall.InotifyRmWatch` in this situation. 

@agorman I think you fix is wrong, `ok` in the statement `if !ok && success == -1 {`should always be true. My fix is as follows

```
diff --git a/vendor/golang.org/x/exp/inotify/inotify_linux.go b/vendor/golang.org/x/exp/inotify/inotify_linux.go
index 901f308..c8bd944 100644
--- a/vendor/golang.org/x/exp/inotify/inotify_linux.go
+++ b/vendor/golang.org/x/exp/inotify/inotify_linux.go
@@ -141,7 +141,10 @@ func (w *Watcher) RemoveWatch(path string) error {
        }
        success, errno := syscall.InotifyRmWatch(w.fd, watch.wd)
        if success == -1 {
-               return os.NewSyscallError("inotify_rm_watch", errno)
+               // If path not exists, we should continue delete keys from watchs and paths
+               if _, err := os.Stat(path); err == nil {
+                       return os.NewSyscallError("inotify_rm_watch", errno)
+               }
        }
        delete(w.watches, path)
        // Locking here to protect the read from paths in readEvents.
```

**Comment by agorman** [comment]
Doh, you're right about my logic error. Good catch. I don't think this change quite fixes it either though. If a directory was deleted and then RemoveWatch is called it will still error without deleting the watch internally.

I propose that we just move the internal deletes up and keep the error handling the same. That way users can handle the error as they see fit but the watch is cleaned up properly internally.

https://github.com/agorman/exp/commit/93822845401277baa4dd15f54f13bc9c84ae2b69

**Comment by chenchun** [comment]
My patch fix the situation that the path was deleted and retrying to remove the watch is useless. But if `InotifyRmWatch` returns error due to other problems which we don't know if retry helps, I think maybe we need to add a `forceRemove bool` field to `func (w *Watcher) RemoveWatch(path string) error`. If forceRemove is set, we delete keys from watches and paths map even if error returns.

**Comment by agorman** [comment]
I'm fine with not doing the syscall to inotify if the directory doesn't exist as long as the internal maps are cleaned up even if an error is returned. I don't think a user should have to force anything to allow for the watches to be removed internally even if there is no actual inotify watch.

**Comment by rsc** [comment]
Deleted this code instead. See github.com/fsnotify for more maintained code.
