### ISSUE TITLE
cmd/compile: spurious error in equality comparison

### ISSUE THREAD

**Issue by alandonovan** [golang/go#16702]
The gc compiler issues a spurious error for this comparison:

    (*int)(nil) == interface{}(nil) // gc: illegal constant expression: *int == interface {}

For some reason it seems to consider the operands to the comparison to be constants, even though they are both nil (and thus not even values of a type that has constants).

When the operands are bound to variables, the error goes away:
 
    func _(p *int, q interface{}) bool { return p == q }

`go/types` correctly reports no error.

See https://play.golang.org/p/gtgb4En-KE

```
$ go version
go version devel +31ad583 Wed Aug 10 19:44:08 2016 +0000 darwin/amd64
```

**Comment by TreyLawrence** [comment]
So would this just be changing const.go [here](https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/const.go#L836) and [here](https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/const.go#L854) to also check that the kind of both nodes is also not `TINTER`?
cc: @pbiggar @kgibilterra
