### ISSUE TITLE
runtime: cgo using programs have a goroutine marked [syscall, locked to thread]; make it clearer

### ISSUE THREAD

**Issue by shiyanhui** [golang/go#16714]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   
   ```
   go1.6
   go1.6.3
   go1.7
   ```
   
   All tried.
2. What operating system and processor architecture are you using (`go env`)?
   
   ```
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/root/work"
   GORACE=""
   GOROOT="/root/go"
   GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go- build476293257=/tmp/go-build -gno-record-gcc-switches"
   CXX="g++"
   CGO_ENABLED="1"
   ```
3. What did you do?
   
   DHT implements BitTorrent DHT Protocol. It sends and receives UDP packets.
   
   ```
   go get github.com/shiyanhui/dht
   cd github.com/shiyanhui/dht/sample/spider
   go build spider.go
   nohup ./spider &
   curl http://localhost:6060/debug/pprof/goroutine?debug=2
   ```
   
   And you will see it. 
4. What did you expect to see?
   
   Not blocked, maybe **[syscall, locked to thread]**
5. What did you see instead?
   
   **[syscall, 214 minutes, locked to thread]**, always blocked. It can be repeatable.

**Comment by minux** [comment]
Could you please post more about the blocked thread?
e.g. its stack trace.

**Comment by shiyanhui** [comment]
It's here. https://github.com/shiyanhui/dht/issues/6#issuecomment-239743849

**Comment by ianlancetaylor** [comment]
I don't understand why this goroutine does not show any stack trace.

Is there a way that we can recreate the problem ourselves?

**Comment by jbardin** [comment]
@ianlancetaylor,

Most programs that import "net" will have this goroutine:

```
import _ "net"

func main() {
	panic("done")
}
```

I always assumed it was a cgo finalizer, since the goroutine doesn't appear with `CGO_ENABLED=0`

**Comment by shiyanhui** [comment]
I tried it with **CGO_ENABLED=0** and **[syscall, locked to thread]** is gone.

**Comment by ianlancetaylor** [comment]
@jbardin Thanks for pointing that out.  That explains it.  It's not a finalizer goroutine (which indicates its status with "finalizer").  It's a spare goroutine that is created for any Go program that uses cgo in case a thread started by C code calls a Go function.

So this is completely normal.  I will leave this issue open to make it appear less odd in a stack trace, such as by using a function other than `goexit`.  For the record, it can be seen by running the above trivial program with `GOTRACEBACK=system`.
