### ISSUE TITLE
net: TestIgnoreLameReferrals failure

### ISSUE THREAD

**Issue by gfoxiii** [golang/go#16718]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Users/rex/workspace/github/go/1.6/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rex/workspace/go"
GORACE=""
GOROOT="/Users/rex/workspace/github/go/1.6"
GOTOOLDIR="/Users/rex/workspace/github/go/1.6/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

`~/workspace/github/go/1.7/go/src$ ./all.bash`

```
--- FAIL: TestIgnoreLameReferrals (0.00s)
	dnsclient_unix_test.go:589: got address 220.255.2.153, want 192.0.2.1
FAIL
FAIL	net	2.239s

```

4. What did you expect to see?

`go version go1.6 darwin/amd64`  -> `go version go1.7 darwin/amd64`

5. What did you see instead?

nothing else !

**Comment by mdempsky** [comment]
Does `go test -run TestIgnoreLameReferrals net` reliably fail for you?

If so, can you run the process under strace (or whatever OS X has) and/or tcpdump to see what's going on?  That test should be self-contained and not talk to the network at all.  It's puzzling where 220.255.2.153 would come from.

Oh, do you have www.golang.org in your /etc/hosts by any chance?

**Comment by gfoxiii** [comment]
/etc/hosts
```
# 220.255.2.153	www.golang.org
```

`go version`
```
go version go1.7 darwin/amd64
```

Thx!
