### ISSUE TITLE
crypto/X509: tbsCertificate struct has wrong default version value.

### ISSUE THREAD

**Issue by zhengping12** [golang/go#16711]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6.3
2. What operating system and processor architecture are you using (`go env`)?
OS X El Capitan 10.11.6

3. Issue
According to RFC5280 Section 4.1.  Basic Certificate Fields
The default version should be version 1. Or int 0. 
In Golang x509 library, the default is set to int 1, which means Version 2.

**Comment by odeke-em** [comment]
Originally reported in closed issue https://github.com/golang/go/issues/13382. Fixed by https://go-review.googlesource.com/#/c/20548 in March 2015 for Go1.7.

Another issue where the default version was fixed to int 0 to represent version 1 was ocsp issue https://github.com/golang/go/issues/16321.
