### ISSUE TITLE
runtime: cpu-bound goroutine blocks finalization

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#1671]
<pre>When I run the following program, I get this output:

finalizing 251; total 600
finalizing 250; total 602
finalizing 249; total 3997
finalizing 248; total 9501
finalizing 247; total 20908
finalizing 246; total 53407
finalizing 245; total 100954
finalizing 244; total 225684
finalizing 243; total 526626
finalizing 242; total 984099
finalizing 241; total 2116933
finalizing 240; total 4875429

Hardly any finalizers are called, even though there is evidently
some garbage collection going on.

6g macos f618e5e0991d+ tip

package main

import (
    &quot;runtime&quot;
    &quot;fmt&quot;
)

type Foo bool

func main() {
    for {
        newFoo()
    }
}

var count int

func newFoo() *Foo {
    f := new(Foo)
    this := count
    runtime.SetFinalizer(f, func(_ *Foo) {
        fmt.Printf(&quot;finalizing %d; total %d\n&quot;, this, count)
    })
    count++
    return f
}</pre>

**Comment by bradfitz** [comment]
@aclements, I'll let you dup or close this one as appropriate.

**Comment by aclements** [comment]
While it's still theoretically possible for us to fall behind on the finalizers queue since there's no backpressure on it, it looks like we keep up just fine now in practice, even without any sleeps or explicit Goscheds. I guess there have been some improvements to the scheduler in the past five years. :)

**Comment by ianlancetaylor** [comment]
I would guess that the relevant change was invoking the finalizer queue from the sysmon thread, in https://golang.org/cl/75960043.
