### ISSUE TITLE
cmd/go: get -v missing from usage

### ISSUE THREAD

**Issue by JesseWeinstein** [golang/go#16719]
On go version go1.5.1 linux/amd64, the first line of `go get --help` is: `usage: get [-d] [-f] [-fix] [-insecure] [-t] [-u] [build flags] [packages]` which doesn't mention the `-v` flag, even though it does work, and so should be documented. The function of `-v` appears to be to make the output more verbose.

This was originally reported by @epitron, here https://github.com/golang/go/issues/12197#issuecomment-196019906 -- but no-one seems to have made the requested separate bug till now.

**Comment by JesseWeinstein** [comment]
Nice quick response! I'm not sure I fully agree with documenting the flag both in the list of build flags, *and* in the detailed list on `go get` (but not on `clean`, `install`, `list`, `run` or `test`) -- but since this bug is now closed, I guess that's another issue, and one I don't feel like opening. :-/

**Comment by rakyll** [comment]
I am thinking about writing a proposal for reorganizing the flags. Current way of mentioning build tags and delegating users  to go help build is not working especially for the new comers.
