### ISSUE TITLE
cmd/vet: check unkeyed fields only when pkg is built

### ISSUE THREAD

**Issue by ymmt2005** [golang/go#16725]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.7 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ymmt/t"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329948438=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

* Create a.go and b.go as follows:

```
cd $GOPATH
mkdir -p src/a src/b
cat >src/a/a.go <<EOF
package a

type A struct {
    Key string
}
EOF
cat >src/b/b.go <<EOF
package b

import "a"

var B = []a.A{
    {"abc"},
}
EOF
```

* Run `go vet` without built binaries will not produce warnings.

```
cd $GOPATH
rm -rf pkg
go vet a b
```

* After built a, `go vet` produce warnings.

```
cd $GOPATH
go install a
go vet a b
```

4. What did you expect to see?

    src/b/b.go:6: a.A composite literal uses unkeyed fields
    exit status 1

5. What did you see instead?

Nothing, if no a binary.

**Comment by robpike** [comment]
Unfortunate, known, and maybe working as intended. Vet can't type check if the packages being imported have not been compiled, as there is no type information for them.

**Comment by ymmt2005** [comment]
@robpike Thank you.

If this is intended, I'd like to suggest improving cmd/vet documentation
so that users can compile packages in advance.

Currently, there's no compilation information:
https://golang.org/cmd/vet/
