### ISSUE TITLE
x/playground: upgrade to go1.7

### ISSUE THREAD

**Issue by tomheng** [golang/go#16729]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/1VcPUlPk_3

4. What did you expect to see?
1.7

5. What did you see instead?
1.7rc6

**Comment by dgryski** [comment]
1.7rc6 was released as 1.7 with no changes.  This "is" the latest release, but will be properly updated to a 1.7-tagged release "soon".

**Comment by broady** [comment]
This happened a couple days ago. 

![screen shot 2016-08-19 at 12 03 35 am](https://cloud.githubusercontent.com/assets/24982/17801697/68543ee4-65a0-11e6-8676-6117a98976ff.png)
