### ISSUE TITLE
x/time/rate: use context package from Go 1.7+

### ISSUE THREAD

**Issue by gyuho** [golang/go#16745]
Hope this is the right place to ask this question.

Could anybody provide some timeline on switching [`golang.org/x/net/context`](https://github.com/golang/time/blob/master/rate/rate.go#L14)  to `context`?
When would this happen?

Reference
- https://github.com/golang/time/blob/master/rate/rate.go#L14
- https://github.com/coreos/etcd/issues/6174

Thanks!

**Comment by bradfitz** [comment]
They're mostly compatible, so we'll probably keep external libraries using golang.org/x/net/context for awhile so we don't break Go 1.6 users.

That is, you can use a stdlib context.Context and pass it to a function taking a golang.org/x/net/context.

There are some cases where it's not as nice, but it mostly works out.

Did you hit specific problems?

If we had type aliases (#16339) this would've been less gross.

**Comment by gyuho** [comment]
@bradfitz We don't have any problem. Just trying to plan in advance, along with grpc.

As you suggest, we can just keep external context for awhile.

We will revisit this if we hit any problem. Thanks!
