### ISSUE TITLE
cmd/vet: warn for reflect.DeepEqual on errors

### ISSUE THREAD

**Issue by zombiezen** [golang/go#16748]
A common antipattern I see in production code is using `reflect.DeepEqual` on errors in tests, which results in brittle tests.  Even just adding more diagnostic information to the error can break it.  The more proper thing to do is either:

1. Check whether a substring is present in the error message (not great, but more correct).
2. Use something like Dave Cheney's [errors package](https://github.com/pkg/errors) to make the system-under-test provide more useful errors (great! because it's better API design anyway).

It would be helpful to have a vet check that discourages this.

(cc @dsnet)

**Comment by dsnet** [comment]
To be more specific, this is a check that warns if either `a` or `b` in `reflect.DeepEqual(a, b)` is of the `error` type.

If they are structs that contain a field of an `error` type, no warning is given. While I would consider using deep equal in that case a code smell, there are legitimate uses of it when it is used to compare sentinel errors.

**Comment by robpike** [comment]
This is not a correctness issue, so it is not a vet problem. Perhaps golint should do this, but not vet.
