### ISSUE TITLE
x/tools: release static analysis tool for context propogation

### ISSUE THREAD

**Issue by mdlayher** [golang/go#16742]
Now that `context` is part of the standard library in Go 1.7, it would be nice for the tool mentioned in the comment of `context.TODO()` to be available to the public: https://golang.org/pkg/context/#TODO.

If this isn't feasible for some reason, I instead propose that this comment be removed, to prevent misleading others who are looking for the same tool:

> TODO is recognized by static analysis tools that determine whether Contexts are propagated correctly in a program.

/cc @broady

**Comment by dgryski** [comment]
Also @alandonovan for the status of the tooling

**Comment by dsnet** [comment]
There's a pull request at golang/lint#227 that tries to add this check to `lint`, but the check really should be done in `vet` or in some other tool.

**Comment by shurcooL** [comment]
A tool that determines whether contexts are propagated correctly (instead of being forgotten and dropped) would also be useful in this context, see https://github.com/google/go-github/pull/529#issuecomment-280872026.

**Comment by shazow** [comment]
Any news on the hypothetical static analysis tool that the `context.TODO()` comment refers to?

This is proving to be a source of much confusion; any feelings on updating the `context.TODO()` comment meanwhile?

**Comment by mdlayher** [comment]
In that case, I'll close this out. Thanks for the follow-up.
