### ISSUE TITLE
cmd/link: -ldflags -X does not allow values with spaces

### ISSUE THREAD

**Issue by mediocregopher** [golang/go#16743]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

```
go version go1.7 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/home/mediocregopher/src/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mediocregopher/src/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build914586157=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
package main

import "fmt"

var foo string

func main() {
	fmt.Printf("%q\n", foo)
}
```

Then:

```
go build -ldflags '-X main.foo="bar baz"' main.go && ./main
```

4. What did you expect to see?

```
"bar baz"
```

5. What did you see instead?

```
# command-line-arguments
usage: link [options] main.o
  -B note
        add an ELF NT_GNU_BUILD_ID note when using ELF
  -C    check Go calls to C code

... etc
```

The linker doesn't like spaces in the value. In 1.6 this could be worked around by not using the equal sign, but that form is no longer allowed in 1.7

EDIT: Should note, I've tried all combinations of single-quote/double-quote/no-quote I could think of, none seem to work

**Comment by mwhudson** [comment]
go run -ldflags '-X "main.foo=bar baz"' main.go works for me.
