### ISSUE TITLE
doc: Go 1.7 release notes missing 'unordered examples' change

### ISSUE THREAD

**Issue by magical** [golang/go#16744]
The release notes for Go 1.7 say:

> go/doc
> 
>  To support the corresponding change in go test described above, Example struct adds a Unordered field indicating whether the example may generate its output lines in any order.

...but no corresponding change is mentioned above. I assume it is referring to https://golang.org/cl/19280/.

**Comment by broady** [comment]
We really should stop saying "above" in the release notes.

**Comment by rsc** [comment]
FYI, there is nothing wrong with the word "above".

**Comment by bradfitz** [comment]
We generally don't update release notes retroactively.

The audience will be minimal at this point.

Somebody can send a CL if they want, but this isn't a Go 1.8 blocker.
