### ISSUE TITLE
encoding/json: marshaling nil value stored in interface value doesn't omitempty

### ISSUE THREAD

**Issue by jnross** [golang/go#16750]
1. What version of Go are you using (`go version`)?
1.7, also verified with 1.6.3

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
I have a struct "result" defined with one of the members "Err" as an interface type "error". The json annotation specifies "omitempty".  I define another struct type concreteError which implements this interface on the pointer receiver (i.e. *concreteError implements the interface).  

If I assign a nil pointer variable to result.Err, the field is not omitted from the marshaled JSON as expected.  Instead the field is marshaled as a JSON null.  

If I assign the nil literal to result.Err, the field is omitted from the marshaled JSON as expected

This issue is clearly demonstrated here: https://play.golang.org/p/uw6jvKN-qX

4. What did you expect to see?
A nil interface value should be omitted from the marshaled JSON when the field is annotated with "omitempty"

5. What did you see instead?
The nil interface value was not omitted.

**Comment by dgryski** [comment]
This looks like fallout from https://golang.org/doc/faq#nil_error

**Comment by jnross** [comment]
Yes, that must be the case.  Perhaps the JSON marshaller should use reflect.ValueOf(res.Err).IsNil() to determine whether an interface is empty and should be omitted per the annotation.

**Comment by jnross** [comment]
This appears to resolve the issue:  https://github.com/jnross/go/commit/36aa259f821ce0bfa4ddb76bc3584d184d3fa3e6

I'll see about contributing this patch directly per the instructions here: https://golang.org/doc/contribute.html

**Comment by rsc** [comment]
Working as intended. If you have 

	I int `json:",omitempty"
	S string `json:",omitempty"`
	J interface{} `json:",omitempty"

Then if I = 0 it gets omitted, or if S is "" it gets omitted, or if J is nil it gets omitted. But if J is 0 or "", it does not get omitted. That's not considered "empty" for an interface.

**Comment by jnross** [comment]
No, this issue still occurs as originally reported. See my example:  https://play.golang.org/p/uw6jvKN-qX

**Comment by freeformz** [comment]
@jnross The example you provide is what both @dgryski and @rsc described. 

FWIW: I would like an interface  of a nil concrete value to also omitempty, but I would be surprised if that change happens.
