### ISSUE TITLE
cmd/compile: crash: schedule does not include all values

### ISSUE THREAD

**Issue by robpike** [golang/go#16751]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +248c3a3 Fri Mar 18 03:56:28 2016 +0000 darwin/amd64
It does not happen with go1.7, the release, so i think the bug was checked in overnight.

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/Users/r/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/r"
GORACE=""
GOROOT="/Users/r/go"
GOTOOLDIR="/Users/r/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0y/zwb3fjyn3tlbj8363tp0pfqw0000gp/T/go-build736867730=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

cd google.golang.org/grpc/transport
go build

4. What did you expect to see?

correct compilation

5. What did you see instead?

quokka=% go build
# google.golang.org/grpc/transport
./http_util.go:247: internal compiler error: schedule does not include all values

```
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/r/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x6013d7, 0x24, 0x0, 0x0, 0x0)
	/Users/r/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.(*ssaExport).Fatalf(0x8d60c6, 0xc4000009f0, 0x6013d7, 0x24, 0x0, 0x0, 0x0)
	/Users/r/go/src/cmd/compile/internal/gc/ssa.go:4569 +0x74
cmd/compile/internal/ssa.(*Config).Fatalf(0xc4213be000, 0x9f0, 0x6013d7, 0x24, 0x0, 0x0, 0x0)
	/Users/r/go/src/cmd/compile/internal/ssa/config.go:272 +0x6e
cmd/compile/internal/ssa.(*Func).Fatalf(0xc421e84f00, 0x6013d7, 0x24, 0x0, 0x0, 0x0)
	/Users/r/go/src/cmd/compile/internal/ssa/func.go:397 +0x6b
cmd/compile/internal/ssa.schedule(0xc421e84f00)
	/Users/r/go/src/cmd/compile/internal/ssa/schedule.go:257 +0x11ef
cmd/compile/internal/ssa.Compile(0xc421e84f00)
	/Users/r/go/src/cmd/compile/internal/ssa/compile.go:64 +0x321
cmd/compile/internal/gc.buildssa(0xc4210b03f0, 0x0)
	/Users/r/go/src/cmd/compile/internal/gc/ssa.go:235 +0xc5c
cmd/compile/internal/gc.compile(0xc4210b03f0)
	/Users/r/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1367
cmd/compile/internal/gc.funccompile(0xc4210b03f0)
	/Users/r/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186
cmd/compile/internal/gc.Main()
	/Users/r/go/src/cmd/compile/internal/gc/main.go:464 +0x196c
cmd/compile/internal/amd64.Main()
	/Users/r/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/Users/r/go/src/cmd/compile/main.go:33 +0x2a3
```

**Comment by bradfitz** [comment]
Dup of #16741
