### ISSUE TITLE
x/tools/cmd/guru: go-guru-build-tags in go-guru.el does not work

### ISSUE THREAD

**Issue by nwidger** [golang/go#16756]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

```
go version go1.7 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/niels/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bb/xxdvfvm103n8p4vktz66d7d40000gn/T/go-build040892158=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

I'm using `go-guru` with Emacs 24.5.1 from [emacsformacosx.com](https://emacsformacosx.com/), here's my `M-x version RET` output:

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

- Open Emacs with `go-guru.el` from [this commit](https://github.com/golang/tools/blob/92480e476063dbeb161fff66c62da6e55c10310a/cmd/guru/go-guru.el) loaded
- Type `M-x customize-group RET go-guru RET`
- Type `M-x eval-expression RET (setq go-guru-build-tags "one") RET`
- Type `M-x toggle-debug-on-error RET`
- Run any go-guru command that calls `go-guru--command`

4. What did you expect to see?

Normal `guru` output.

5. What did you see instead?

The following stacktrace is produced:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep 111)
  mapconcat(identity "one" ",")
  (format "-tags=%s" (mapconcat (quote identity) go-guru-build-tags ","))
  eval((format "-tags=%s" (mapconcat (quote identity) go-guru-build-tags ",")) nil)
  eval-expression((format "-tags=%s" (mapconcat (quote identity) go-guru-build-tags ",")) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

This seems to have been broken by [this commit](https://github.com/golang/tools/commit/9ae7e1769c8df0883c58182c2a555089bed55e31#diff-676c3e607c54e9f2a2a5b566eafcc730).  Note that the stacktrace is only produced if `go-guru-build-tags` is a non-empty string, which explains why this bug was not immediately noticed.

I see a few possible solutions.

1. Change the following line in `go-guru--command` from

```
(format "-tags=%s" (mapconcat 'identity go-guru-build-tags ","))
```

back to just

```
"-tags" go-guru-build-tags
```

If choosing this solution it would probably be good to expand the docstring for `go-guru-build-tags` to indicate that the value must be comma-separated when including multiple build tags.

2. Change the declaration for `go-guru-build-tags` to a list of strings

```
(defcustom go-guru-build-tags '()
  "Build tags passed to guru."
  :type '(repeat string)
  :group 'go-guru)
```

and leave `go-guru--command` as it currently is.  This solution seems better except that it would break anyone currently setting `go-guru-build-tags` as a string.  Therefore, I'm not sure which one should be preferred.

/cc @alandonovan, @dominikh

**Comment by dominikh** [comment]
@nwidger Want to send a patch to https://github.com/dominikh/go-mode.el? That's the new home of the Emacs guru integration. In either case the issue should be refiled there, and this one closed.

**Comment by nwidger** [comment]
Sure, I'll submit a PR to the new repo soon.
