### ISSUE TITLE
log/syslog: Dial function needs examples

### ISSUE THREAD

**Issue by geofffranks** [golang/go#16761]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

 1.7

2. What operating system and processor architecture are you using (`go env`)?

darwin/amd_64

3. What did you do?

Tried to view  the docs for https://golang.org/pkg/log/syslog/#Dial

4. What did you expect to see?

Documentation/examples describing what the 'network' and 'raddr' values should be.

5. What did you see instead?

No mention of what those should be. It appears 'network' refers to 'address family' or 'protocol' (tcp/udp/unix/unixgram), rather than some string representing a network address. 'raddr' seems to be the 'host:port', or file path string for connecting to the socket.  I had to browse the test suite's source code to figure out what these should be.

**Comment by geofffranks** [comment]
Thanks!

**Comment by magical** [comment]
Isn't syslog frozen?

**Comment by geofffranks** [comment]
My understanding is that frozen indicates people can expect not to notice API or under the hood functionality changes moving forward, but I don't see how clarifying documentation should ever be dissuaded.

**Comment by bradfitz** [comment]
Documentation is okay.
