### ISSUE TITLE
cmd/test: make it easy to -cover and browse

### ISSUE THREAD

**Issue by rakyll** [golang/go#16768]
Cover tool requires two steps to produce HTML from the coverage data whereas, as a user, I am often interested in being able to see the coverage results page as quickly as possible when running go test cover.

I am proposing that we should slightly modify the behavior of the -html flag to combine `go test -coverprofile=c.out` and `go tool cover -html=c.out` when -html="".

If -html="" is breaking anything, we may introduce a new flag like -browse.

/cc @bradfitz @adg @broady

**Comment by broady** [comment]
Maybe better as a flag to `go test`?

`go test -cover -cover.html`

**Comment by rakyll** [comment]
Sounds better to add it to the test command.

> go test -cover -cover.html

Any reasons why `go test -cover -html` wouldn't be good enough. It is simpler.

**Comment by broady** [comment]
Only if `html` flag produces output without `cover`. Which, I guess, it could.

**Comment by rakyll** [comment]
Apart from the flag name, I spoke too soon.

The big problem is the case where go test exists with non-zero -- mainly why coverage browsing is a two-step process.

I guess we can still start a server to serve the coverage and exit with the necessary code during ctrl+c but not sure it would ever be an expected behavior.

**Comment by adg** [comment]
The current behavior is analogous with the way pprof works for heap and cpu profiles.
It'd be worthwhile to consider them at the same time.

cc @robpike

**Comment by robpike** [comment]
The go command can't embody every work flow. I'd be happy leaving it alone. I mean, it's only an && to get this yourself.

go test -coverprofile foo.out && go tool cover -html foo.out

Why is that too hard?

**Comment by rakyll** [comment]
> The go command can't embody every work flow. 

Looking at test coverage is not just "embodying every work flow". This is a fundamental feature advertised by the tool but implemented for machines not human users.

> Why is that too hard?

The promise of the tool is to provide coverage, yet it only provides coverage readable by machines. I would expect the Go tool to be human-first.

It still can output a coverprofile to be consumed by other tools. But the user of the Go tool is primarily a human. And I don't know why we need to depend on an alias to achieve something that is commonly required. The current situation only encourages users to write more makefiles or create aliases replace the go tool.

**Comment by robpike** [comment]
I still don't really understand the point here. It's easy enough to use as is, and things like IDEs can and do take care of this, or the user can write a shell script if the && burns the fingers.

And, as you observe, trying to flow things like this automatically raises lots of issues of error handling and recovery and expands the space of interacting flags. The go command is already FAR too complex, and go test one of the worst offenders, and go test -cover its worst piece.

I would prefer to leave things as they are, but I will not veto a complete, implementable, clean proposal. At the moment this is just brainstorming.

**Comment by mattn** [comment]
Currently, cover doesn't support multiple package. If the steps will be once, And remove `-html` flag, cover will have to support merge multiple profiles, maybe. Of course, prefer it since I'm author of [goveralls](https://github.com/mattn/goveralls). :)

**Comment by rakyll** [comment]
> IDEs can and do take care of this, or the user can write a shell script if the && burns the fingers.

If escalating the work to other tools is the goal, we should keep things as it is. There is no point of further discussing the ux for the go tool.
