### ISSUE TITLE
cmd/compile: type checks can be ineffective for slices as function arguments

### ISSUE THREAD

**Issue by songgao** [golang/go#16767]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version go1.7 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/home/songgao/gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/songgao/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/songgao/go-build405294454=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?

This builds and runs fine: https://play.golang.org/p/XPDlxvky-4

But this has compile errors: https://play.golang.org/p/XQ4SXHlJNR

4. What did you expect to see?

Both cases should have compile errors, consistent with [spec](https://golang.org/ref/spec#Properties_of_types_and_values)

5. What did you see instead?

 `foo`(`type foo int`) is treated as a different from `int`, but `bar`(`type bar []byte`) is treated as the same type as `[]byte`

**Comment by magical** [comment]
Some more test cases: https://play.golang.org/p/Aq74lddwDH

**Comment by magical** [comment]
I think this is actually working as intended.

The spec says:
> A value x is assignable to a variable of type T ("x is assignable to T") in any of these cases: 
>  * ...
>  * x's type V and T have identical underlying types and at least one of V or T is not a named type. 

and

> Each type T has an underlying type: If T is one of the predeclared boolean, numeric, or string types, or a type literal, the corresponding underlying type is T itself. Otherwise, T's underlying type is the underlying type of the type to which T refers in its type declaration. 

and

> Types may be named or unnamed. Named types are specified by a (possibly qualified) type name; unnamed types are specified using a type literal, which composes a new type from existing types. 

Consider this code:
```
type T []byte
var x = []byte{1, 2, 3}
var _ T = x
```

T is a named type whose underlying type is []byte. X is a variable with an unnamed type (call it V) whose underlying type is also []byte. Since T and V have the same underlying type, and V is unnamed, the assignment in the third line is permitted.

**Comment by songgao** [comment]
Hmm.. interesting. But under this rule, shouldn't `byte(4)` be assignable to variable typed `t5` since only one of them is named type and they both have the same underlying type `byte`?

**Comment by rsc** [comment]
@magical's explanation is correct. 
To respond to @songgao's final question: no, because byte and t5 are both named types ("byte" is a name).
