### ISSUE TITLE
gerrit: eliminate negative scores

### ISSUE THREAD

**Issue by josharian** [golang/go#16764]
I propose that we eliminate negative scores from gerrit and add a separate "Hold" or "Do not submit" flag that prevents submission.

Negative scores serve two purposes. First, to convey that the reviewer is not happy with the CL. Second, in the case of a -2, to block submission.

Negative opinions about a CL need to occur in English, for two reasons. First, humans don't like negative feedback, and written language offers the opportunity to give negative feedback gracefully and with shades of meaning. Second, the negative feedback must explain what is wrong, so that the contributor can improve the CL (if possible) and can learn for the future.

Given that negative opinions must be accompanied by text, the negative score adds nothing except possibly negative emotion.

As to blocking submission, this need can occur independently of the reviewer's opinion of a CL. For example, I would like to be able to +2 CLs sent during a freeze and also block them to avoid accidental submission. And using a -2 to block submission can still carry some of the emotional weight of a negative score. (Humans are irrational. That's life.)

I don't know about the technical feasibility/reasonability of adding a "Do not submit" flag. If it is infeasible, we could keep the -1 score and document that its sole purpose is to block submission, not to provide feedback, although this would be non-ideal.

We would also need to update all accompanying documentation around contribution, although I expect that this would minimal.

**Comment by matloob** [comment]
I'm not sure how easy it is possible to implement this in gerrit, but it seems like great idea to me.

**Comment by bradfitz** [comment]
I believe this is technically just a Gerrit config change.

**Comment by broady** [comment]
I like `Hold`. Let's go with that.

**Comment by josharian** [comment]
Ping. If nothing else, a `Hold` flag would be useful.

**Comment by josharian** [comment]
@rsc just did this. Yay! 🤞🏽that it works well in practice.
