### ISSUE TITLE
cmd/go: test doesn't compile examples unless an output is provided

### ISSUE THREAD

**Issue by rakyll** [golang/go#16773]
`go test` doesn't compile and report compilation errors if the example doesn't have an output section. This used to be different in the past and we were able to use examples to provide usage snippets without worrying that they are broken.

The current requirement to have an output section is impractical in complex examples such as:

```
func ExampleClientCredentialsJSON() {
	key, err := ioutil.ReadFile("/path/to/downloaded-client-secret.json")
	if err != nil {
		log.Fatal(err)
	}

	cfg, err := google.ConfigFromJSON(key, datastore.ScopeDatastore)
	if err != nil {
		log.Fatal(err)
	}

	client, err := datastore.NewClient(
		ctx, "project-id", option.WithTokenSource(cfg.TokenSource(ctx, nil)))
	if err != nil {
		log.Fatal(err)
	}
	// output:
	// something to assert
}
```

where go test is trying to run the block and fails because it cannot find the downloaded-client-secret.json. Since we are only caring about the integrity of the examples and not willing to verify them, please give us an option to build examples without output assertion.

**Comment by okdave** [comment]
This looks like a regression that is probably worth fixing in a 1.7.x. The [testing package](https://golang.org/pkg/testing/#hdr-Examples) still says that it will run and verify example code, and only that the example **may** include the expected output.

**Comment by cznic** [comment]
> [Example functions without output comments are compiled but not executed.](https://golang.org/pkg/testing/#hdr-Examples)

**Comment by okdave** [comment]
@rakyl commented that they're not being compiled at all though, which is a regression

**Comment by cznic** [comment]
I cannot reproduce it. I am on 1.7 stable and I have just checked making one of examples, *without an output section*, invalid (`s//fmt.Println/fmt.Printlnn` and deleting the `// Output:` part) and the result is:

```
jnml@r550:~/src/github.com/cznic/gc$ head -n 15 ast_test.go 
// CAUTION: Generated by yy - DO NOT EDIT.

// Copyright 2016 The GC Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gc

import (
	"fmt"
)

func ExampleArgument() {
	fmt.Printlnn(exampleAST(2, "package a ; 'b' ( 'c' )"))
}
jnml@r550:~/src/github.com/cznic/gc$ go test
# github.com/cznic/gc
./ast_test.go:14: undefined: fmt.Printlnn
FAIL	github.com/cznic/gc [build failed]
jnml@r550:~/src/github.com/cznic/gc$
```

**Comment by rakyll** [comment]
I cannot produce this problem anymore. I was able to produce both against tip and go1.7. There was something sketchy about my env a week ago. I have little idea how it affected the example tests but am going to close this issue to avoid more noise.
