### ISSUE TITLE
hash/crc32: wrong output for unaligned input on s390x

### ISSUE THREAD

**Issue by randall77** [golang/go#16779]
CL https://go-review.googlesource.com/#/c/24470/ introduced a test for unaligned crc32 computations.  It seems this broke the s390x implementation.

See https://build.golang.org/log/e03a4804f6a0c93d08194fb85a168701774f729d , the build bot for s390x is failing.

@ChrisXZou

**Comment by bradfitz** [comment]
s390x assembly problem, uncaught until now? All the other builders look happy.

/cc @mundaym @billotosyr for s390x

**Comment by randall77** [comment]
Yes, I'm assuming this is a s390x assembly bug unless proven otherwise.

**Comment by billotosyr** [comment]
We'll have a look at it.

**Comment by mundaym** [comment]
Can this fix be marked for 1.7.1? The CL is simple and should apply cleanly to 1.7.

**Comment by bradfitz** [comment]
Sure.
