### ISSUE TITLE
proposal: strings: add ListIndex

### ISSUE THREAD

**Issue by 256dpi** [golang/go#16774]
While reading the source code of many packages lately I  stumbled a lot over the following function declaration:

```go
func stringInList(list []string, str string) bool {
	for _, val := range list {
		if val == str {
			return true
		}
	}

	return false
}
```

I have the feeling that searching a slice of strings for the first occurrence of a string is a very common need and might be a good addition to the standard library.

I would propose the following function for the strings package:

```go
func ListIndex(list []string, str string) int {
	for i, val := range list {
		if val == str {
			return i
		}
	}

	return -1
}
```

I know adding stuff to the standard library is a big thing, but I had to give it a least a try. ;)

**Comment by Ganners** [comment]
If you're happy for your list of strings to be sorted, then this essentially exists as sort.SearchStrings: https://golang.org/pkg/sort/#SearchStrings

The linear search listed above is so trivial in implementation that I wouldn't think it's worth adding, binary search is far superior if you can afford the sort.

**Comment by griesemer** [comment]
Adding this would set a precedent for many other little "useful" utility functions that are trivial to write. Where does it end? I'm against adding things like this to the std lib.

**Comment by 256dpi** [comment]
@Ganners I wasn't aware of sort.SearchStrings existence... Thanks for pointing it out. You're right, a binary search would be a better choice.

@griesemer: I wouldn't ask for a `Max(ints []int) int` function, but as there is already a package with string utility functions in place, I thought it would be a nice addition. I scrolled multiple times through the package to check if there is really no such function already there. ;)
