### ISSUE TITLE
os.ExpandEnv doesn't recursively fetch environment variables

### ISSUE THREAD

**Issue by jnmoal** [golang/go#16785]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.7 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
https://play.golang.org/p/-chU68uIbC

4. What did you expect to see?
/first/value:/second/value

5. What did you see instead?
$ENV1:$ENV2

I'm working on an example for the "os" package to help a little on the issue [16360](https://github.com/golang/go/issues/16360).

According to how os.Expand is implemented this is not a bug, but I was expecting that this function would recursively fetch the environment variables in order to expand it.

Is this a wanted behavior?

**Comment by bradfitz** [comment]
I don't think this is wanted behavior. In any case, compatibility would preclude us from changing this, sorry. You'll have to write your own wrapper.
