### ISSUE TITLE
os: Getenv documentation update to point user to os.LookupEnv

### ISSUE THREAD

**Issue by techtonik** [golang/go#16782]
go 1.5 adds `os.LookupEnv` (#9676)

But it is not sufficiently described on the web, e.g.
https://gobyexample.com/environment-variables

It will valuable to add reference to it to `os.Getenv`
documentation https://golang.org/pkg/os/#Getenv

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/27322

**Comment by techtonik** [comment]
Thanks. I would fix it myself if that was possible to edit on GitHub, but setting up the whole toolchain with Gerrit will probably take too much time for such a small change.
