### ISSUE TITLE
x/net/ipv4: Recieving multiple Multicast UDP streams with same ports

### ISSUE THREAD

**Issue by ahmadissa** [golang/go#16797]
go version:
go version go1.7 linux/amd64

go env:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aissa/code/go"
GORACE=""
GOROOT="/home/aissa/go"
GOTOOLDIR="/home/aissa/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build583051275=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

with referance to : https://godoc.org/golang.org/x/net/ipv4

Im trying to catch to different multicast streams  having the same port and saving its data to two separate files, both files are created but both files are having duplicate content from both streams.

'netstat -tulnp' is giving the below:

`udp        0      0 0.0.0.0:1234            0.0.0.0:*                           24951/main    `      
`udp        0      0 0.0.0.0:1234            0.0.0.0:*                           24951/main` 

is should be 

`udp        0     238.1.2.2:1234            0.0.0.0:*                           24951/main `         
`udp        0      238.1.2.1:1234            0.0.0.0:*                           24951/main`

the code  is below:

`package main

        import (
            "io"
            "net"
            "os"
            "time"

            "golang.org/x/net/ipv4"
        )

        func main() {
            c1, err := net.ListenPacket("udp4", "224.0.0.0:1234")
            if err != nil {
                // error handling
            }
            en0, err := net.InterfaceByName("en0")
            if err != nil {
                // error handling
            }
            c2, err := net.ListenPacket("udp4", "224.0.0.0:1234")
            if err != nil {
                // error handling
            }
            p1 := ipv4.NewPacketConn(c1)
            if err := p1.JoinGroup(en0, &net.UDPAddr{IP: net.IPv4(238, 1, 2, 2)}); err != nil {
                // error handling
            }
            p2 := ipv4.NewPacketConn(c2)
            if err := p2.JoinGroup(en0, &net.UDPAddr{IP: net.IPv4(238, 1, 2, 1)}); err != nil {
                // error handling
            }
            fo1, err := os.Create("test1.ts")
            defer fo1.Close()
            if err != nil {
                return
            }
            go io.Copy(fo1, p1)
            fo2, err := os.Create("test2.ts")
            defer fo2.Close()
            if err != nil {
                return
            }
            go io.Copy(fo2, p2)
            time.Sleep(time.Second * 10)
            p1.LeaveGroup(en0, c1.LocalAddr())
            p1.Close()
            c1.Close()
            p2.LeaveGroup(en0, c2.LocalAddr())
            p2.Close()
            c2.Close()
        }
`

**Comment by mikioh** [comment]
In that case, you need to use ipv4.ControlMessage to distinguish the original IP destination addresses.
