### ISSUE TITLE
string concatenate very slow

### ISSUE THREAD

**Issue by tw4452852** [golang/go#16796]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version devel +00b779a Wed Aug 17 03:12:29 2016 +0000 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tw/golib"
GORACE=""
GOROOT="/home/tw/goroot"
GOTOOLDIR="/home/tw/goroot/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build370309872=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
```
package main

func main() {
        s := ""

        for i := 0; i < 1024*1024; i++ {
                s += "c"
        }
}
```

run it:

`time ./test`

4. What did you expect to see?

It should return quickly.

5. What did you see instead?

very slowly:

`./test  70.82s user 4.62s system 126% cpu 59.499 total`

**Comment by davecheney** [comment]
/cc @aclements @RLH 

This program is allocation bound, but even so, adding `c` to a string a million times shouldn't take over a minute. `env GODEBUG=gctrace=1` shows the program is spending all its time in the gc, which is to be expected, but 70 seconds still feels high.

**Comment by randall77** [comment]
You're doing an O(n^2) operation.  Each append of a single character reallocates and copies the whole string.

For better ways to do this, see http://stackoverflow.com/questions/1760757/how-to-efficiently-concatenate-strings-in-go

I don't think there is any easy fix for this.  Perhaps with enough compiler analysis we could figure out one of those better ways automatically.

**Comment by bradfitz** [comment]
No, this is expected quadratic behavior.

**Comment by DocMerlin** [comment]
I suggest using a buffer for this sort of thing.  Strings in golang are not meant to be edited heavily.
