### ISSUE TITLE
io: endless loop in MultiReader in Go 1.7

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16795]
https://golang.org/cl/17873 (git rev ccdca832c, bug #13558) was added in Go 1.7 and introduced a bug where the EOF of a (non-zero, EOF) Read could be ignored and the MultiReader could loop, forever yielding bytes.

Just hit this myself.

**Comment by bradfitz** [comment]
Sent https://golang.org/cl/27397

**Comment by ianlancetaylor** [comment]
The CL says that this bug has been present since Go 1.0, so this is not a 1.7.1 issue.

**Comment by bradfitz** [comment]
@ianlancetaylor, I think this is bad enough and in a core piece of io to warrant a fix, regardless of how many cycles it's been broken.

Like I said, this bit me in real code and I had to go on a debugging spree to figure out what was going on.

What would people who weren't comfortable debugging the standard library do?

**Comment by ianlancetaylor** [comment]
Hmmm, well, OK, I guess.
