### ISSUE TITLE
cmd/compile, runtime: need to squeeze StackGuard back down

### ISSUE THREAD

**Issue by dr2chase** [golang/go#16792]
This is for 1.8.

Change in the runtime and changes in the compiler (SSA, and porting) have caused the stack guard to creep up, and it needs to go back down.  It's temporarily extra-high because of the PPC port; this is filed to make a note of the problem.

The 3 files that must be changed in sync to modify the StackGuard size are:

src/cmd/internal/obj/stack.go
src/runtime/stack.go
test/nosplit.go

**Comment by cherrymui** [comment]
FYI, some history:
long time ago -- 160
9510034 -- increased to 256
b6951bc -- increased to 512
db40624 -- increased to 640
c1b6e39 -- increased to 720

**Comment by cespare** [comment]
There's also #9214

**Comment by bradfitz** [comment]
@cespare, thanks. Let's move to the older bug.
