### ISSUE TITLE
x/text/collate: recommends using nonexistent package locale instead

### ISSUE THREAD

**Issue by c12h** [golang/go#16790]
The introductory comment for package golang.org/x/text/collate says "Package locale provides a high-level interface to collation. Users should typically use that package instead." However, AFAICT there is no package locale. This is a documentation error, and a minor one at that, but still might be worth fixing.

This applies to Go 1.6 and Go 1.7.

**Comment by stapelberg** [comment]
I just stumbled over this as well. I’m wondering which package the documentation is referring to, though. It seems like there is no package (at least not within x/text) which uses the collate package:

```
x/text $ grep --exclude-dir=collate --exclude-dir=internal -r 'collate\.' *
x/text $
```

Is the referenced package not released yet?
