### ISSUE TITLE
race detector: Possible false positive?

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#16809]
`go version go1.7 linux/amd64`
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build700676214=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

While working on #14200, I discovered what appears to be a false positive in the race detector. It is illustrated by [this example](https://play.golang.org/p/ohovO1MyDl). The detection disappears if `String()` is given a pointer receiver. Even locking a mutex is detected as a race. Commenting out line 21 still results in a race detection.

I know why it's detecting this as a race, but there doesn't seem to be any actual race happening here.

**Comment by bradfitz** [comment]
That's a real race. You're copying the mutex by value, reading it in your first goroutine while you mutate it in the other goroutine.

**Comment by quentinmit** [comment]
Why is the struct being copied? The receiver is unnamed, so there's no way to access the copy.
