### ISSUE TITLE
CGO_ENABLED=1 causing the '-marm' unrecognized

### ISSUE THREAD

**Issue by thincal** [golang/go#16801]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.7rc3 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build972111986=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?

when build for ARM, it will report bellow error:
`GOOS=linux GOARCH=arm CGO_ENABLED=1 go build -o logservice`
it will report bellow error:
```
# runtime/cgo
gcc: error: unrecognized command line option '-marm'
```
but build for AMD64, it is ok.
`GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o logservice`

**Comment by cherrymui** [comment]
You'll need to set `CC` to the C cross-compiler, e.g. `CC=arm-linux-gnueabi-gcc`.

**Comment by davecheney** [comment]
This is a very common error. I Wonder if the go tool could.be more helpful
if I refused to cross compile with cgo enabled unless CC was set.

Cherry/Minux what do you think?

**Comment by cherrymui** [comment]
Sounds a good thing to do. There is exception: GOARCH=386 on AMD64.

**Comment by minux** [comment]
How about this: when runtime/cgo fails to compile, run $CC -v and let its
output goes to screen (along with instructions to check $CC)

Not only does it point out errors with unset CC, it also helps when you
used a wrong CC.

**Comment by thincal** [comment]
Thanks for help, it works. Yes print out the possible error info would be greate to understand the direction.
