### ISSUE TITLE
net: Document UDPConn.ReadMsgUDP not implemented on Windows.

### ISSUE THREAD

**Issue by v2ray** [golang/go#16802]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.7

2. What operating system and processor architecture are you using (`go env`)?
Windows 2012 amd64

3. What did you do?
Calling UDPConn.ReadMsgUDP on Windows.

4. What did you expect to see?
The function behaves the same as it does on Linux.

5. What did you see instead?
The function constantly raises error "not supported on Windows".

The document for this function is not clear that it doesn't run on Windows. It can't be easily figured out through source code as well. 

UDPConn.ReadMsgUDP() -> UDPConn.readMsg() -> fd.readMsg() -> error

I appreciate if this behavior is documented, either in the function description, or in the bugs section, to avoid some hassle during debugging.

**Comment by mikioh** [comment]
See #9252.
