### ISSUE TITLE
cmd/go: TestBuildOutputToDevNull overwrites /dev/null on OpenBSD

### ISSUE THREAD

**Issue by DominoTree** [golang/go#16811]
This appears to be related to issue #12407
```
# go version
go version go1.7 openbsd/amd64

# ls -al /dev/null
crw-rw-rw-  1 root  wheel    2,   2 Aug 20 08:42 /dev/null
# go tool dist test -no-rebuild -v go_test:cmd/go 

##### Testing packages.
# go tool dist test -run=^go_test:cmd/go$
ok      cmd/go  167.748s

ALL TESTS PASSED (some were excluded)
# ls -al /dev/null
-rwxr-xr-x  1 root  wheel  968656 Aug 20 09:15 /dev/null
```
Disabling the `TestBuildOutputToDevNull` test in `src/cmd/go/go_test.go` with a  `runtime.GOOS` check similar to the existing one seems to prevent the issue.

**Comment by bradfitz** [comment]
We could disable the test, or we could fix the underlying problem, if there's an underlying problem to be fixed.

/cc @mdempsky
