### ISSUE TITLE
return nil pointer that is  not export struct pointer to a interface occur error

### ISSUE THREAD

**Issue by funnywwh** [golang/go#16817]
1. What version of Go are you using (`go version`)?
go version go1.7 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOROOT=D:\tools\go1.7.windows-amd64\go
GOARCH=amd64
GOOS=linux
CGO_ENABLED=0

GO15VENDOREXPERIMENT=1

PATH=%GOROOT%\bin;%PATH%

LITEIDE_GDB=gdb
LITEIDE_MAKE=mingw32-make
LITEIDE_TERM=%COMSPEC%
LITEIDE_TERMARGS=
LITEIDE_EXEC=%COMSPEC%
LITEIDE_EXECOPT=/C

3. What did you do?

package a

type a struct {
}

func (this *a) F() {

}
func GetA() *a {
	return nil
}

package main

import (
	"a"
)

type A interface {
	F()
}

func main() {
	var aa A
	aa = a.GetA()
	if aa == nil {
		print("ok")
	} else {
		panic("error no nil")
	}
}

4. What did you expect to see?

"ok"
5. What did you see instead?

"error no nil"

**Comment by bradfitz** [comment]
This is a common mistake when learning Go. See the FAQ: https://golang.org/doc/faq#nil_error
