### ISSUE TITLE
cmd/compile: BCE not clever enough or intended?

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#16813]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go1.7 
2. What operating system and processor architecture are you using (`go env`)?
   linux/amd64
3. What did you do?

```
// example4.go
package main

import "math/rand"

func fa2() {
    s := []int{0, 1, 2, 3, 4, 5, 6}
    index := rand.Intn(7)
    _ = s[index:] // line 9: bounds check 
    _ = s[:index] // line 10: bounds check eliminatd!
}

func fb2(s []int, index int) {
    _ = s[index:] // line 14: bounds check
    _ = s[:index] // line 15: bounds check // not clever enough?
}

func fc2() {
    s := []int{0, 1, 2, 3, 4, 5, 6}
    s = s[:4]
    index := rand.Intn(7)
    _ = s[index:] // line 22: bounds check 
    _ = s[:index] // line 23: bounds check eliminatd!
}

func main() {}

go build -gcflags="-d=ssa/check_bce/debug=1" example4.go
# command-line-arguments
./11.go:9: Found IsSliceInBounds
./11.go:14: Found IsSliceInBounds
./11.go:15: Found IsSliceInBounds
./11.go:22: Found IsSliceInBounds
```
1. What did you expect to see?

BCE should also applied for line 15.
1. What did you see instead?

BCE is not applied for line 15.

**Comment by josharian** [comment]
cc @brtzsnr

**Comment by brtzsnr** [comment]
WAI: higher index in a slice is limited by cap not by len.

**Comment by brtzsnr** [comment]
Thanks for reporting. Definitely not smart enough:

    v10 = SliceLen <int> v6
    v11 = SliceCap <int> v6
    v12 = IsSliceInBounds <bool> v7 v10
    v32 = IsSliceInBounds <bool> v7 v11

There is the implication that v12 -> v32 which is not seen by the prove pass. This is short coming of the current algorithm.
