### ISSUE TITLE
cmd/link: make code more readable

### ISSUE THREAD

**Issue by matloob** [golang/go#16818]
I'd like to clean up cmd/link and help improve its Go style.

A few things I'd like to do:
- Remove a bunch of the global variables, especially Ctxt
- Reverse the dependency between the ld package and the architecture specific packages.
- Localize more of the state to smaller components

**Comment by agnivade** [comment]
@matloob - Can you post an update here on what are the things pending on this so that others can pick this up if they want to ?

**Comment by matloob** [comment]
This is totally obsolete, closing.
