### ISSUE TITLE
flag panics on empty os.Args

### ISSUE THREAD

**Issue by erikh** [golang/go#16812]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.7 darwin/amd64 (latest homebrew install on el capitan)

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/erikh"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build283785545=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?

I modified os.Args and flag flipped out. Here's an example.

https://play.golang.org/p/wCeTjjXSJV

4. What did you expect to see?

Flag should probably handle an empty array without panicking, even if I screwed it up.

5. What did you see instead?

Flag should be a cool cat and not panic.

**Comment by bradfitz** [comment]
I was neutral on this until I saw the documentation:

> Parse parses the command-line flags from os.Args[1:]. Must be called after all flags are defined and before flags are accessed by the program.

It's explicitly documented to access `[1:]`. If it weren't documented I might be convinced it's okay to change, but arguably we'd be violating the documentation by changing it.

Sorry, it seems better to do nothing here.
