### ISSUE TITLE
x/tools/cmd/guru: Add packages/functions "sameids" to what response

### ISSUE THREAD

**Issue by thomasf** [golang/go#16829]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.7

2. What operating system and processor architecture are you using (`go env`)?

linux/amd64

3. What did you do?

I've been using the far simpler text matching auto highlight symbol mode in emacs which for go mode more or less matches all strings which are the same.

`go-guru-hl-identifier-mode` is great because it highlights variable's according to scope scoping but I kind of miss package and function highlighting I had before now:

![image](https://cloud.githubusercontent.com/assets/330847/17851396/08ef3f34-6862-11e6-85ed-81d723d697f4.png)

It's not a really big issue for me but it is quite helpful to have such highlight as well.

**Comment by alandonovan** [comment]
Are you using the latest version of guru?  I added support for this feature in July:
  https://go-review.googlesource.com/c/24949/
