### ISSUE TITLE
cmd/compile: internal compiler error: textual export format request

### ISSUE THREAD

**Issue by martisch** [golang/go#16820]
1. What version of Go are you using (`go version`)?
go version devel +6a393dc Sun Aug 21 16:49:48 2016 +0000 darwin/amd64

3. What did you do?

compile files with flags such as "-m -m" that call e.g. Nconv(n, FmtSharp)

```
go build -gcflags="-m -m" main.go
```
4. What did you expect to see?

some debug output and normal exit

5. What did you see instead?

internal compiler error: textual export format request

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/martisch/Documents/development/go/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x6408de, 0x1d, 0x0, 0x0, 0x0)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.setfmode(0xc4203ff6e8, 0xc4203d2ce8, 0xc4203ff6d0)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/fmt.go:117 +0xda
cmd/compile/internal/gc.Nconv(0xc4203ee480, 0x4, 0x24, 0xc42002a7b0)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/fmt.go:1658 +0x47
cmd/compile/internal/gc.caninl(0xc4203ee3f0)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/inl.go:151 +0x4a3
cmd/compile/internal/gc.Main.func1(0xc42002a798, 0x1, 0x1, 0xc4203ff900)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/main.go:442 +0x5c
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc4203ff9c0, 0xc4203ee3f0, 0xc4203e1680)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/esc.go:106 +0x2ad
cmd/compile/internal/gc.visitBottomUp(0xc42002a778, 0x1, 0x1, 0x697b58)
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/esc.go:62 +0xd6
cmd/compile/internal/gc.Main()
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/gc/main.go:446 +0x26c6
cmd/compile/internal/amd64.Main()
	/Users/martisch/Documents/development/go/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/Users/martisch/Documents/development/go/go/src/cmd/compile/main.go:33 +0x2a3

cc @griesemer @mdempsky 

To fix extended debug output should we rather change all the call sites of Nconv and others to not use FmtSharp anymore or make the fmt.go functions ignore the FmtSharp flag for now.

**Comment by griesemer** [comment]
@martisch Hm, yes, that code is gone. Perhaps prematurely.It may be ok to just ignore FmtSharp.
