### ISSUE TITLE
net/http/httptest: Example uses ResponseRecorder directly

### ISSUE THREAD

**Issue by ceocoder** [golang/go#16837]
`httptest.ResponseRecorder` is inspected directly instead of calling `Result()` to obtain a `http.Response`

[1] https://golang.org/pkg/net/http/httptest/#example_ResponseRecorder

**Comment by bradfitz** [comment]
@ceocoder, that was the old way, and still acceptable. But yes, we should probably show the new way in the example.

**Comment by ceocoder** [comment]
@bradfitz I've a CL ready, I'm trying to push it up.  Just waiting on CLA to propagate

**Comment by ceocoder** [comment]
Here we go, https://go-review.googlesource.com/27495
