### ISSUE TITLE
errors: example_test doesn't use errors package

### ISSUE THREAD

**Issue by tortuoise** [golang/go#16831]
The example in the errors package doesn't import or use the errors package.

The example illustrates how to implement the error interface but doesn't illustrate any feature of the errors package. If it's agreed the example isn't illustrative I'll attempt to claim the issue.

**Comment by rakyll** [comment]
It has an example for New, see https://golang.org/pkg/errors/#example_New.

I am not sure what else we can add, there is only New exported from the package.

**Comment by davecheney** [comment]
I don't think there is anything that can be done here. `errors.New` has an example. I'm going to close this issue as WAI.
