### ISSUE TITLE
cmd/link: mips64x linking with cgo broken

### ISSUE THREAD

**Issue by cherrymui** [golang/go#16838]
Seems after commit 0a15d95 external linking with cgo on mips64x is broken.

Failure build example:
https://build.golang.org/log/18b5dee1d5363bf6412b564f5e6d9d767dc0f2ff

/cc @matloob 

I can have a look some time later or tomorrow.

**Comment by dr2chase** [comment]
Also broken on PPC64, fixed by changing cmd/link/internal/ppc64/obj.go:
```
-       ld.Thearch.Linuxdynld = "/lib64/ld64.so.1"
+       ld.Thearch.Linuxdynld = "/lib64/ld64.so.2"
```
(still testing, but at least I can run 'go')

**Comment by cherrymui** [comment]
Linking on mips64 is fixed by https://go-review.googlesource.com/c/27555/, ppc64 is fixed by https://go-review.googlesource.com/c/27562/. Thanks!
