### ISSUE TITLE
x/mobile: error: cannot find symbol `class error`

### ISSUE THREAD

**Issue by dcu** [golang/go#16835]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/go"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
Attempted to bind my SDK with `gomobile bind` and the current master of gomobile

4. What did you expect to see?
gomobile compiling successfully

5. What did you see instead?

```
go/Seq.java:50: error: cannot find symbol
	private static void throwException(Universe.error err) throws Exception {
	                                           ^
  symbol:   class error
  location: class Universe
go/Seq.java:54: error: cannot find symbol
	private static Universe.error wrapThrowable(final Throwable t) {
	                       ^
  symbol:   class error
  location: class Universe
go/Seq.java:55: error: cannot find symbol
		return new Universe.error() {
		                   ^
  symbol:   class error
  location: class Universe
3 errors

make: *** [android] Error 1
```

/cc @eliasnaur

**Comment by eliasnaur** [comment]
I think you somehow have an outdated Seq.java in play. Seq.java in gomobile master doesn't have that code anymore.

**Comment by dcu** [comment]
how can this happen? I'm able to reproduce in 2 different computers

**Comment by eliasnaur** [comment]
I'm not sure, and I can't reproduce the error locally either. Do you have multiple copies of Seq.java in your GOPATH?

**Comment by dcu** [comment]
someone vendored gomobile and that was causing the issue, thanks ! the issue is fixed now.

**Comment by longtq6195-seta-international** [comment]
longtran@longtran:~$ go get golang.org/x/mobile/cmd/gomobile
# golang.org/x/mobile/bind
work/src/golang.org/x/mobile/bind/genjava.go:986: o.Val().ExactString undefined (type constant.Value has no field or method ExactString)
work/src/golang.org/x/mobile/bind/genobjc.go:371: o.Val().ExactString undefined (type constant.Value has no field or method ExactString)
longtran@longtran:~$ gomobile install golang.org/x/mobile/example/basic
gomobile: command not found
longtran@longtran:~$ gomobile install golang.org/x/mobile/example/basic
gomobile: command not found
longtran@longtran:~$ go get golang.org/x/mobile/cmd/gomobile
# golang.org/x/mobile/bind
work/src/golang.org/x/mobile/bind/genjava.go:986: o.Val().ExactString undefined (type constant.Value has no field or method ExactString)
work/src/golang.org/x/mobile/bind/genobjc.go:371: o.Val().ExactString undefined (type constant.Value has

**Comment by eliasnaur** [comment]
What version of Go are you using? You need at least go 1.7 to use go mobile.

Den man. 3. jul. 2017 18.34 skrev longtq6195-seta-international <
notifications@github.com>:

**Comment by longtq6195-seta-international** [comment]
i'm using go version go1.7 linux/amd64
