### ISSUE TITLE
cgo LDFLAGS file in the wrong format

### ISSUE THREAD

**Issue by Almodovar** [golang/go#16849]
I am trying to use cgo to link go with c library. I put the lib file in the same folder with go and write #cgo LDFLAGS: -L. -llpsolve55 (i am using windows and the library i want to link is lpsolver). However, when I build the go file the error message shows as below:

# github.com/draffensperger/golp
./lpsolve55.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status
   
I've already read the cgo document and some online tutorials and still cannot find solution. Thanks for the help.

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  Please see https://golang.org/wiki/Questions .  Thanks.

This does not look like a Go problem.  It looks like lpsolve55.lib is not in the format expected by the C linker you are using.  Perhaps lpsolve55.lib is a MSVC file and you are using GCC to link.
