### ISSUE TITLE
runtime: madvise() failure during scavenging causing crash on darwin arm64

### ISSUE THREAD

**Issue by bytex64** [golang/go#16850]
1. What version of Go are you using (`go version`)?

go version go1.7 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

iOS 9.3.4 arm64 (though I believe this applies to armv7 as well)

3. What did you do?

Create a gomobile library with `gomobile bind -target ios` and link the framework into an iOS app. Run the app, then switch away for five minutes or more. Switch back to the app.

4. What did you expect to see?

Normal operation.

5. What did you see instead?

Upon returning to the app, one thread will have crashed via `notok` as a result of a failed `madvise` syscall during scavenging. `GODEBUG=scavenge=1` accelerates things significantly, and it will crash almost immediately.

----

It seems this was [fixed for 386 and amd64 a while ago](https://codereview.appspot.com/6998052/), but the same treatment never got applied to arm/arm64. I tested [a similar fix](https://github.com/golang/go/compare/release-branch.go1.7...SpiderOak:darwin-arm-ignore-madvise-failure) and it solved my problem, but I'm not that confident in my ability to edit ARM assembly correctly.

Frustratingly, I couldn't replicate the problem with any of the gomobile example apps. I suspect that they are too simple to sufficiently provoke the GC.

**Comment by randall77** [comment]
@aclements

**Comment by minux** [comment]
The fix to 386 and amd64 just covers up the problem. The real fix is in
#16644.

I'm going to close this as a dup for that issue.
