### ISSUE TITLE
Regexp FindAll second argument purpose

### ISSUE THREAD

**Issue by stgleb** [golang/go#16853]
I've got a question about regexp package function

`(re *Regexp) FindAll(b []byte, n int) [][]byte`

Official documentation says

`FindAll is the 'All' version of Find; it returns a slice of all successive matches of the expression, as defined by the 'All' description in the package comment. A return value of nil indicates no match.`

But what is purpose of n int argument?

I've supposed it is uppder bound of entries count we need to retrieve, but when i set it to 1 << 32
i've got 49 entries even if i really have only 2.

**Comment by bradfitz** [comment]
It's documented in the package doc at the top:

> If 'All' is present, the routine matches successive non-overlapping matches of the entire expression. Empty matches abutting a preceding match are ignored. The return value is a slice containing the successive return values of the corresponding non-'All' routine. These routines take an extra integer argument, n; if n >= 0, the function returns at most n matches/submatches.

**Comment by stgleb** [comment]
Thanks

**Comment by ianlancetaylor** [comment]
Note that we don't use the issue tracker for questions.  Going forward, please ask questions in a forum.  See https://golang.org/wiki/Questions .  Thanks.
