### ISSUE TITLE
x/crypto/acme/autocert: Certificate renewal broken

### ISSUE THREAD

**Issue by takeyourhatoff** [golang/go#16851]
It looks like when a certificate expires, autocert will not renew it but instead just hangup incoming TLS connections.

Offending line:

https://github.com/golang/crypto/blob/b35ccbc95a0eaae49fb65c5d627cb7149ed8d1ab/acme/autocert/autocert.go#L270

**Comment by bradfitz** [comment]
The package isn't done. @crhym3 knows.

**Comment by crhym3** [comment]
Yes, working on it right now.

**Comment by crhym3** [comment]
Can't assign this to myself.

**Comment by crhym3** [comment]
Fixed by https://github.com/golang/crypto/commit/33b41827e673eff8a3b8c2f2089bf0d14d99e1ef.
This can be closed now. I think I referenced this issue from the commit incorrectly, so it didn't show up here.
