### ISSUE TITLE
cmd/vet: detect situations in which runtime.KeepAlive() must be added

### ISSUE THREAD

**Issue by rasky** [golang/go#16864]
There have been a couple of CLs in which @ianlancetaylor has manually added `runtime.KeepAlive()` after careful code inspection:

 * http://golang.org/cl/27637
 * http://golang.org/cl/27650

In Ian's words:

> The cases that matter are where you have a parameter or local variable that is pointer to some type, there is or might be a finalizer on the object, the last reference to the object in the function is passing a field to some other function, and the finalizer might in some way invalidate that field value.

It would be nice if `go vet` could detect these situations, especially if it ends up being run on `std` regularly (eg. on trybots).

My proposal to make it possible is to add a tag `vet:”finalizer_invalidate"` to struct fields that matter in this context; with this tag, `vet` should be able to detect the missing calls to `KeepAlive` with no false positives.

**Comment by bradfitz** [comment]
Nobody should use finalizers, so nobody should need this. Even if this sort of vet rule were easy to write (it won't be), I don't think we need to encourage the use of finalizers by making them easier.

**Comment by robpike** [comment]
I agree with Brad, plus it would be a bad precedent to introduce source-level markers to silence or enable vet warnings.

I vote against this proposal.

**Comment by rasky** [comment]
OK it was just a suggestion to help development of `std`. Never mind.
