### ISSUE TITLE
review: warn when committing large files

### ISSUE THREAD

**Issue by adg** [golang/go#16867]
It's easy to accidentally 'git add' a binary. It'd be nice if the pre-commit hook would warn when adding a file larger than (say) a few hundred KB, in the same way it warns for bad commit messages.

**Comment by josharian** [comment]
Related: #10658. I find appealing the idea of blocking unless (say) the path of the file is present in the commit message. Warnings are easy to miss.

**Comment by adg** [comment]
Closing in favor of #10658
