### ISSUE TITLE
syscall: Readlink is incorrect for windows

### ISSUE THREAD

**Issue by gooid** [golang/go#16861]
`

------------------------ src/syscall/syscall_windows.go ------------------------
index 703bb53..eb9a7e1 100644
@@ -1028,11 +1028,11 @@ func Readlink(path string, buf []byte) (n int, err error) {
 	case IO_REPARSE_TAG_SYMLINK:
 		data := (*symbolicLinkReparseBuffer)(unsafe.Pointer(&rdb.reparseBuffer))
 		p := (*[0xffff]uint16)(unsafe.Pointer(&data.PathBuffer[0]))
-		s = UTF16ToString(p[data.PrintNameOffset/2 : (data.PrintNameLength-data.PrintNameOffset)/2])
+		s = UTF16ToString(p[data.PrintNameOffset/2 : (data.PrintNameLength+data.PrintNameOffset)/2])
 	case _IO_REPARSE_TAG_MOUNT_POINT:
 		data := (*mountPointReparseBuffer)(unsafe.Pointer(&rdb.reparseBuffer))
 		p := (*[0xffff]uint16)(unsafe.Pointer(&data.PathBuffer[0]))
-		s = UTF16ToString(p[data.PrintNameOffset/2 : (data.PrintNameLength-data.PrintNameOffset)/2])
+		s = UTF16ToString(p[data.SubstituteNameOffset/2 + 4 : (data.SubstituteNameLength+data.SubstituteNameOffset)/2])
 	default:
 		// the path is not a symlink or junction but another type of reparse
 		// point

`

![705d06f0-69df-4601-aa5c-5a879f60b4f7](https://cloud.githubusercontent.com/assets/11555940/17930059/e56ae3ca-6a36-11e6-9354-c4ed155d36e6.png)

**Comment by hirochachacha** [comment]
Dup of #15978.

**Comment by alexbrainman** [comment]
Yes, looks like related to issue #15978.

Alex
