### ISSUE TITLE
runtime: adjust _HeapAllocChunk dynamically to improve performance

### ISSUE THREAD

**Issue by toddboom** [golang/go#16866]
I know there is a huge desire to limit the number of user-facing variables for memory allocation and garbage collection, but through internal testing @rw found that increasing `GO_HEAP_MALLOC_MB` can give us performance gains that we can't obtain by modifying `GOGC` alone. Specifically, increasing it to 64MB from the default of 1MB gave us a ~60% boost in write throughput.

I realize that opening this up for user modification might be a non-starter, but I figured I'd bring it up for discussion since the 1.8 dev cycle is kicking off. Curious to hear what you guys think about this. Let me know if you've got any questions about our use case or testing.

Here's a quick patch for the change that @rw put together:

```
--- src/runtime/malloc.go       2016-08-12 00:04:10.524693000 +0000
+++ src/runtime/malloc.go       2016-08-12 00:12:04.328693000 +0000
@@ -109,6 +109,27 @@
        _PageMask  = _PageSize - 1
 )

+// modeled after `readgogc`
+func readgoheapallocmb() uintptr {
+       p := gogetenv("GO_HEAP_MALLOC_MB")
+       if p == "" {
+               return 1 << 20
+       }
+       mb := atoi(p)
+       sz := mb << 20
+       println("GO_HEAP_MALLOC_MB", mb)
+       println("GO_HEAP_MALLOC_MB as bytes", sz)
+       return uintptr(sz)
+}
+
+// we're in the allocator guts here, so ensure this is always sane by
+// initializing it:
+var _HeapAllocChunk uintptr = 1 << 20
+
+func init() {
+       _HeapAllocChunk = readgoheapallocmb()
+}
+
 const (
        // _64bit = 1 on 64-bit systems, 0 on 32-bit systems
        _64bit = 1 << (^uintptr(0) >> 63) / 2
@@ -129,7 +150,6 @@

        _FixAllocChunk  = 16 << 10               // Chunk size for FixAlloc
        _MaxMHeapList   = 1 << (20 - _PageShift) // Maximum page length for fixed-size list in MHeap.
-       _HeapAllocChunk = 1 << 20                // Chunk size for heap growth

        // Per-P, per order stack segment cache size.
        _StackCacheSize = 32 * 1024
```

/cc @pauldix @jwilder @rw

**Comment by bradfitz** [comment]
You're proposing a solution but barely mentioning the problem.

What is your problem or motivation with this patch?

**Comment by aclements** [comment]
Interesting. @toddboom, can you describe your workload, in particular how it grows/shrinks the heap over time and how much heap it uses? A GODEBUG=gctrace=1 log would be particularly concrete. Even better would be a benchmark that exhibits the improvement with this change.

Rather than adding a knob, I suspect we could just adjust this dynamically. If the heap is large already, allocate more heap in larger chunks.

**Comment by aclements** [comment]
@toddboom, it would also be useful to know more about the hardware where you got the 60% boost. For example, is it a large multicore?

**Comment by adg** [comment]
Ping @toddboom ?

**Comment by rsc** [comment]
Given the admitted "huge desire to limit the number of user-facing variables for memory allocation and garbage collection", I think it's pretty clear we're not going to make one just for this one setting. We'd love to hear more about the bigger context here, though, and adjust it automatically in the runtime as appropriate. Thanks.

**Comment by toddboom** [comment]
@rsc Understood. I owe you guys some more detail on this, but I've been swamped on the product side. I'll dig in and try to provide more detail over the next few weeks. Thanks for all the feedback so far!
