### ISSUE TITLE
doc/go1.7: mention crypto[oscp, x509] default version fixes

### ISSUE THREAD

**Issue by odeke-em** [golang/go#16872]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version devel +9be2a27 Wed Aug 24 05:08:52 2016 +0000 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/emmanuelodeke/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/emmanuelodeke/go"
GORACE=""
GOROOT="/Users/emmanuelodeke/go/src/go.googlesource.com/go"
GOTOOLDIR="/Users/emmanuelodeke/go/src/go.googlesource.com/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-build277360793=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

 Viewed doc/1.7.html and inspected issues https://github.com/golang/go/issues/13382, 
  https://github.com/golang/go/issues/16321 and https://github.com/golang/go/issues/16711(which was a duplicate of #16321)

4. What did you expect to see?
 Go1.7 docs mentioning crypto fixes:
 + x509.tbsCertificate default version fixed to 1 which is encoded on the wire as 0, fixed by CL https://go-review.googlesource.com/#/c/20548.
 + oscp.ResponseData default version fixed to 1 which is encoded on the wire as 0, fixed by CL https://go-review.googlesource.com/#/c/24841.

5. What did you see instead?
No mention of the fixes. I didn't want to cause much noise here, but I think mentioning
these fixes might be useful to crypto folks.
I sought @agl's thoughts here https://twitter.com/odeke_et/status/766184243533930496 on 
whether we should update docs,  but he doesn't know if we can update doc/go1.7
so that's why I've filed this issue.

**Comment by bradfitz** [comment]
Did anybody get confused or report this, or is this just proactive?

We can amend old notes, but only if it matters.

**Comment by odeke-em** [comment]
@bradfitz it is mostly being proactive, motivation being that someone made a duplicate issue for Go1.6 with https://github.com/golang/go/issues/16711.

I guess, no one has yet gotten confused yet since that report was for Go1.6 and not Go1.7 😁.

**Comment by bradfitz** [comment]
All yours, @odeke-em.

**Comment by broady** [comment]
Sorry, missed this. Yes, please send a CL.

Should this end up on the 1.7 release branch?

**Comment by odeke-em** [comment]
Thanks for accepting the suggestion and for the assignment.
For sure, I've mailed  https://go-review.googlesource.com/28871.

**Comment by rsc** [comment]
In general we don't enumerate bugs fixed like this, especially after the release.
