### ISSUE TITLE
spec: clarify init must be functions

### ISSUE THREAD

**Issue by robpike** [golang/go#16874]
The core compiler rejects top-level identifiers named init unless they declare a function. I can't find that restriction in the specification.

```
package main

func main() {}

var init = 3
```

main.go:5: cannot declare init - must be func

**Comment by mdempsky** [comment]
This text in https://golang.org/ref/spec#Declarations_and_scope seems to be relevant?

"In the package block, the identifier init may only be used for init function declarations, and like the blank identifier it does not introduce a new binding."

**Comment by griesemer** [comment]
What @mdempsky said. Closing.

**Comment by robpike** [comment]
That's good, but it might be nice to mention it again in the section that actually talks about initialization functions.

**Comment by griesemer** [comment]
In that section (initialization functions) it says:

The init identifier is not declared and thus init functions cannot be referred to from anywhere in a program.

With "declared" a link to the declaration section which talks about init not being usable elsewhere. Do you still think it needs more?

Happy to prepare a CL if you had a suggestion for the phrasing. Maybe an add-on to the sentence above?

**Comment by robpike** [comment]
Yes, I was thinking something like,

At package scope, the identifier init can be used only to declare init functions.

Might also be worth moving the mention of multiple init functions here, to put all the specialness of the identifier in one place.
