### ISSUE TITLE
cmd/compile: avoid dead code in escape analysis

### ISSUE THREAD

**Issue by dsnet** [golang/go#16871]
Using `go1.7`

Consider the following function:

``` go
func Foo(codes []int) int {
    const debug = false
    if debug && !sort.IntsAreSorted(codes) {
        panic("input slice is not sorted")
    }

    var s int
    for _, i := range codes {
        s += i
    }
    return s
}
```

Currently, `codes` escapes to the heap. I expect it to not escape since the function where it does escape sort.IntsAreSorted is dead. (the fact that `codes` escapes at all in sort.IntsAreSorted is a separate concern).

/cc @dr2chase

**Comment by josharian** [comment]
Ordering the many compiler stages is a tricky problem. It'd also be nice for dead code not to count against a function's budget for inlining. It might be nice to add an early, crude deadcode pass, which implies also doing a bunch of constant folding. And we'd need to make sure all code gets typechecked, dead or not.

**Comment by navytux** [comment]
Looks to be the same as #12397.

**Comment by minux** [comment]
Could we just do escape analysis at the very end? After at least inlining
and DCE.

**Comment by dr2chase** [comment]
Right now DCE is in SSA and SSA uses results of escape analysis, so that's moderately tricky.  We would need an even-more-generic form of SSA that was (initially) agnostic about whether things were heap or stack allocated.

**Comment by minux** [comment]
On Feb 1, 2017 10:38 AM, "dr2chase" <notifications@github.com> wrote:

Right now DCE is in SSA and SSA uses results of escape analysis, so that's
moderately tricky. We would need an even-more-generic form of SSA that was
(initially) agnostic about whether things were heap or stack allocated.

But running escape analysis after inlining and DCE would be well worth the
effort.

**Comment by randall77** [comment]
On Wed, Feb 1, 2017 at 8:10 AM, Minux Ma <notifications@github.com> wrote:

> On Feb 1, 2017 10:38 AM, "dr2chase" <notifications@github.com> wrote:
>
> Right now DCE is in SSA and SSA uses results of escape analysis, so that's
> moderately tricky. We would need an even-more-generic form of SSA that was
> (initially) agnostic about whether things were heap or stack allocated.
>
> But running escape analysis after inlining and DCE would be well worth the
> effort.
>
>
Escape analysis does run after inlining.

I agree that running escape analysis after DCE would be nice.  I suspect it
is a ton of work, though.
