### ISSUE TITLE
panic running golint

### ISSUE THREAD

**Issue by richardwilkes** [golang/go#16877]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
**go version go1.6.3 darwin/amd64**

2. What operating system and processor architecture are you using (`go env`)?
**GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rich/code/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"**

3. What did you do?
**Ran 'golint test.go' on this file (OK, not really this file, but I was able to distill it down to this):**

```
package main

// typedef struct {
//	double x;
//} tst;
import "C"

func (t C.tst) f() float64 {
	return float64(t.x)
}
```

4. What did you expect to see?

**No output or appropriate warnings.**

**The actual code (before pruning) compiles and runs fine.**

5. What did you see instead?

```
panic: unknown method receiver AST node type *ast.SelectorExpr

goroutine 1 [running]:
panic(0x24dfa0, 0xc82000ec80)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/golang/lint.receiverType(0xc820014d20, 0x0, 0x0)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:1446 +0x311
github.com/golang/lint.(*pkg).scanSortable.func1(0x52c0c0, 0xc820014d20, 0x2ce201)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:336 +0x93
github.com/golang/lint.walker.Visit(0xc82000ae40, 0x52c0c0, 0xc820014d20, 0x0, 0x0)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:1474 +0x40
go/ast.Walk(0x52bf78, 0xc82000ae40, 0x52c0c0, 0xc820014d20)
	/usr/local/go/src/go/ast/walk.go:52 +0x56
go/ast.walkDeclList(0x52bf78, 0xc82000ae40, 0xc82000aa80, 0x2, 0x2)
	/usr/local/go/src/go/ast/walk.go:38 +0xd5
go/ast.Walk(0x52bf78, 0xc82000ae40, 0x52bb08, 0xc820084500)
	/usr/local/go/src/go/ast/walk.go:353 +0x29b9
github.com/golang/lint.(*file).walk(0xc820010800, 0xc82000ae40)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:1450 +0x80
github.com/golang/lint.(*pkg).scanSortable(0xc8200135e0)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:341 +0x22a
github.com/golang/lint.(*pkg).lint(0xc8200135e0, 0x0, 0x0, 0x0)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:149 +0x75
github.com/golang/lint.(*Linter).LintFiles(0xc8200b5970, 0xc8200b5ae0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rich/code/go/src/github.com/golang/lint/lint.go:110 +0x4c9
main.lintFiles(0xc8200b5e88, 0x1, 0x1)
	/Users/rich/code/go/src/github.com/golang/lint/golint/golint.go:92 +0x2ca
main.main()
	/Users/rich/code/go/src/github.com/golang/lint/golint/golint.go:54 +0x568
```

**Comment by richardwilkes** [comment]
Changing the code to read:

```
package main

// typedef struct {
//  double x;
//} tst;
import "C"

func f(t C.tst) float64 {
    return float64(t.x)
}
```

eliminates the panic. Perhaps we aren't supposed to attach functions to C structs? I've only done this in one place in my code, but it seems to work -- and the compiler doesn't complain.

**Comment by dsnet** [comment]
This belongs in the golang/lint issue tracker. I filed there on your behalf.

See golang/lint#236
