### ISSUE TITLE
net/http/cookiejar: adding example

### ISSUE THREAD

**Issue by ceocoder** [golang/go#16884]
I've prepared two versions of examples for `net/http/cookiejar`, 

[Version 1](https://play.golang.org/p/xz74yExiHG) makes actual HTTP requests to www.google.com and https://golang.org/doc/tos.html and prints out cookies.   

*Pro:* It keeps example code small
*Con:*  One needs internet access for this test to pass, it takes `0.59s` on my MacBook Pro.  Time that adds up over many test runs.

[Version 2](https://play.golang.org/p/DTxy75fZKR) uses a dummy transport that writes `COOKIE!` cookie to response.

*Pro:* Tests run very quickly, about `0.00s` on same machine.
*Con:* Example adds additional code, which looks rather out of place in context of an example. I've not see any other example creating a separate transport. 

Any suggestions on how to proceed?

**Comment by ceocoder** [comment]
Related to #16360

**Comment by quentinmit** [comment]
I prefer version 1. However, it seems bad to rely on the exact set of cookies that google.com (or golang.org for that matter) sets. Perhaps you can do a bit of both worlds and have the test run a simple HTTP server that sets a cookie, and then connect and fetch it?

All that said, please also submit the example in the form of a pull request. Thanks!

**Comment by bradfitz** [comment]
Don't rely on external services for tests.

Use httptest.Server and hit its URL using a normal transport, but to localhost.

**Comment by ceocoder** [comment]
Thanks @bradfitz @quentinmit, I've the change ready, just fighting my gerrit setup ATM, somehow I'm getting `Invalid authentication credentials.`,  despite having generated my password and `~/.gitcookies` about 10 times.

**Comment by bradfitz** [comment]
@ceocoder, none of us can upload to Gerrit right now. We suspect they're having some sort of outage.

**Comment by ceocoder** [comment]
@bradfitz ah, that makes more sense.  I'll lay off button smashing for a while.
