### ISSUE TITLE
os.Rename() fails under some circumstances under Windows 10 64 bits

### ISSUE THREAD

**Issue by vadmeste** [golang/go#16882]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.7 windows/amd64`

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\work
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?
https://play.golang.org/p/Vym8My0fsM

4. What did you expect to see?
50 dots in the output to indicate successful operation

5. What did you see instead?
`....2016/08/25 20:03:02 rename c:\tmp\work\bugtest.085104555 c:\tmp\config.json: Accès refusé.
exit status 1`

("Accès refusé" is Access denied in English, sorry..)

**Comment by mattn** [comment]
I don't reproduce this. If using Anti Virus scan on your windows, I had met similar situation.

**Comment by alexbrainman** [comment]
I cannot reproduce this either. But I run very few programs on my computer too. I wonder if you have some antivirus or file system indexing tool or something else that opens the file.

Alex

**Comment by vadmeste** [comment]
Thanks both of you, it was the antivirus. I am not a regular Windows user and I have the antivirus installed by default.
