### ISSUE TITLE
cmd/cover: add total (statements) coverage to HTML output

### ISSUE THREAD

**Issue by savinov** [golang/go#16888]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.7 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/user/gowork"
   GORACE=""
   GOROOT="/home/user/go"
   GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   https://blog.golang.org/cover

go tool cover -func=coverage.out

```
size.go:    Size          42.9%
total:      (statements)  42.9%
```

go tool cover -html=coverage.out
1. What did you expect to see?
   I'd want to see total (statement) in generated HTML as in console output (func flag).
2. What did you see instead?
   An HTML without total (statement) coverage

**Comment by dhananjay92** [comment]
After [golang.org/cl/32762](http://golang.org/cl/32762):

```shell
$ ../pkg/tool/linux_amd64/cover -func=coverage.out
size.go:3:	Size			3/7		42.9%
total:		(statements)	3/7		42.9%
```

And for `-html`:
![cover_screenshot](https://cloud.githubusercontent.com/assets/6269279/20034129/a6d7e7fc-a370-11e6-9e08-83afaf9ac3cc.png)

**Comment by robpike** [comment]
The CL has been abandoned. We decided not to proceed with this.
