### ISSUE TITLE
cmd/link: panic in deadcode flood

### ISSUE THREAD

**Issue by wangkechun** [golang/go#16887]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.7 darwin/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="darwin"
   GOOS="darwin"
   GOPATH="/Users/wkc"
   GORACE=""
   GOROOT="/Users/wkc/local/go"
   GOTOOLDIR="/Users/wkc/local/go/pkg/tool/darwin_amd64"
   CC="clang"
   GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xw/mx32d21j5hd_1gyxv14c77m00000gn/T/go-build713088348=/tmp/go-build -gno-record-gcc-switches -fno-common"
   CXX="clang++"
   CGO_ENABLED="1"
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   A link on play.golang.org is best.

```
go install my-package
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x19fa40, 0xc420012190)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
cmd/link/internal/ld.(*deadcodepass).flood(0xc420069cd0)
        /usr/local/go/src/cmd/link/internal/ld/deadcode.go:279 +0xe88
cmd/link/internal/ld.deadcode(0xc4204a2000)
        /usr/local/go/src/cmd/link/internal/ld/deadcode.go:100 +0x498
cmd/link/internal/ld.Ldmain()
        /usr/local/go/src/cmd/link/internal/ld/pobj.go:192 +0x1089
cmd/link/internal/amd64.Main()
        /usr/local/go/src/cmd/link/internal/amd64/obj.go:45 +0x19
main.main()
        /usr/local/go/src/cmd/link/main.go:28 +0x27d
```
1. What did you expect to see?
2. What did you see instead?

**Comment by davecheney** [comment]
Is the source of the code you are compiling available so I can try to
reproduce this bug?

**Comment by josharian** [comment]
cc @crawshaw -- the panic is probably from decodetypeKind in this line:

```go
			if decodetypeKind(s)&kindMask == kindInterface {
```

**Comment by mandeepbrar** [comment]
+1. Same error. Trying to build and otherwise working program with go:binary-only-package  in official docker.

go env.

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build035439187=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by crawshaw** [comment]
@mandeepbrar want to try out https://golang.org/cl/29692? It's designed to fix #17140 but the diagnostics change may mean you get further into linking before an error.

**Comment by mandeepbrar** [comment]
@crawshaw Seems to go a little further, but an error again

`
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x59f780, 0x690520)
	/home/mandeep/test/go/src/runtime/panic.go:496 +0x1a0
cmd/link/internal/ld.newtype(0xc420494000, 0xc4224ad118, 0xc42ebc3770)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:379 +0x3701
cmd/link/internal/ld.defgotype(0xc420494000, 0xc4224ad118, 0x592ac0)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:374 +0x1f1
cmd/link/internal/ld.newtype(0xc420494000, 0xc42249ad48, 0xc42eb64700)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:425 +0x2e77
cmd/link/internal/ld.defgotype(0xc420494000, 0xc42249ad48, 0x592ac0)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:374 +0x1f1
cmd/link/internal/ld.defdwsymb(0xc420494000, 0xc42249ae30, 0xc4224fac00, 0x2f, 0xc42b5ac944, 0x2a76e0, 0xc42249ad48)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:846 +0x1ba
cmd/link/internal/ld.genasmsym(0xc420494000, 0x5d87d0)
	/home/mandeep/test/go/src/cmd/link/internal/ld/lib.go:1892 +0x643
cmd/link/internal/ld.dwarfgeneratedebugsyms(0xc420494000)
	/home/mandeep/test/go/src/cmd/link/internal/ld/dwarf.go:1453 +0x8c1
cmd/link/internal/ld.(*Link).dodata(0xc420494000)
	/home/mandeep/test/go/src/cmd/link/internal/ld/data.go:1752 +0x2f4b
cmd/link/internal/ld.Main()
	/home/mandeep/test/go/src/cmd/link/internal/ld/main.go:204 +0x907
main.main()
	/home/mandeep/test/go/src/cmd/link/main.go:55 +0x139

`

**Comment by bradfitz** [comment]
Does anybody have a repro here?

I'm going to kick to Go1.10 since we don't have one yet.
