### ISSUE TITLE
runtime/trace, cmd/trace: include CPU profile samples

### ISSUE THREAD

**Issue by rhysh** [golang/go#16895]
The trace viewer UI provides a [mechanism for displaying CPU profile stack samples](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.n7ma43wztmu).

Access to that data inline with other execution trace data—seeing what functions are being executed by goroutines that run for a surprisingly long time—would have been very helpful for diagnosing bugs like #14812, #16293, and #16432. Though the time for those specific bugs may have passed, I think that Go and its users will encounter similar bugs in the future (either in the runtime or in user code).

**Comment by rsc** [comment]
@aclements, this is what confused me!

**Comment by rhysh** [comment]
Yes! There are places to improve (some day), but those can get new issues.
