### ISSUE TITLE
hash/crc32: port faster CRC32-C implementation from AMD64 to AMD64P32

### ISSUE THREAD

**Issue by RaduBerinde** [golang/go#16908]
In #16107 a faster SSE4.2-based implementation for CRC32-C was introduced for AMD64. It should be adapted for AMD64P32 as well. The change should be easy, I just need to become more familiar with NaCl/amd64p32.

**Comment by bradfitz** [comment]
Is this hurting you somehow? Are you using nacl/amd64p32 and this is bottleneck for your application?

**Comment by RaduBerinde** [comment]
Not at all, it's just for the sake of completeness - the AMD64 optimization should work for AMD64P32 as well (with some minor modifications) and they should be on par if possible.

If we don't think it's not useful, we can definitely drop or punt it.

**Comment by agnivade** [comment]
amd64p32 support is going to be [dropped](https://github.com/golang/go/issues/30439). Closing this.
