### ISSUE TITLE
website: SHA sums per binary release's download button are non selectable nor copyable

### ISSUE THREAD

**Issue by pikeview** [golang/go#16900]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   ubuntu
3. What did you do?
   Opened golang website. and clicked downloads link
4. What did you expect to see?
   The sha sum in the download button is too small and not available for copying.
   The same sha sum is available down the page in stable releases section.
   So we have sha sum duplicated on the same page

Please replace the small "not copy-able" sha text in the download button with a clickable link pointing to the sha in the stable releases section.

**Comment by bradfitz** [comment]
Indeed. Thanks for the bug report.

/cc @broady

**Comment by bradfitz** [comment]
Ping @broady.

**Comment by broady** [comment]
Given that the "Featured downloads" section is a subset of the latest stable version download, I think we should just remove it from the "Feature download" section.

The SHA sums are clearly visible in the section below.

**Comment by broady** [comment]
This will go live once 1.8 lands, unless we cherry-pick it before then.

**Comment by shurcooL** [comment]
I'm okay with them being removed for reason @broady stated, but want to share an observation. Even though that SHA sum text was neither selectable nor copyable, it was "findable", which is helpful to verify a file you've downloaded is the featured download you expect. E.g., see [this screenshot](https://cloud.githubusercontent.com/assets/1924134/20352035/8f241cfe-abca-11e6-95fd-5d952f5dd513.png). It's still findable in the section below so I expect that it's fine.
