### ISSUE TITLE
Cannot create the same folder name as package name

### ISSUE THREAD

**Issue by sj82516** [golang/go#16905]
I am using go version go1.7 darwin/amd64.
$GOPATH=~/Go
my project folder structure is 
```
-GO
---bin
---pkg
---src
   |--- `folder_name`
       |--- sort1.go
---main.go
```
I am trying to build my own pkgs and import into main.go.
The pkg name of sort1.go is "sort"
If I name `folder_name` equal "sort", 
then I run `go build sort` `go install sort`, no error msgs output neither sort.a file in pkg.
However, when I name "folder_name" not to equal "sort", like "sortlib" , sortlib.a file show up and every thing work fine.

**Comment by davecheney** [comment]
I'm sorry that will not work because packages in the standard library
always take precedence.

The recommendation is to nanespace your package with your company name or
remote package location, ie

github.com/yourname/sort

**Comment by sj82516** [comment]
I see. 
Thanks for prompt reply.

**Comment by davecheney** [comment]
Thank you. I will close this issue now. Please see https://golang.org/wiki/Questions for good places to ask questions.
