### ISSUE TITLE
variable is redefined in sub block by `:=`

### ISSUE THREAD

**Issue by lifei** [golang/go#16915]
### What version of Go are you using (`go version`)?

go version go1.6.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lifei/Work/bytedance/buton"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

```
func getInt() (int, error) {
	return 1, nil
}

func getString() (string, error) {
	return "", nil
}

func getBytes() ([]byte, error) {
	return nil, errors.New("Bad bytes")
}

func test2() ([]byte, error) {
	var err error
	n := []int{1, 2}

	for _ = range n {
		i, err := getInt()
		if err != nil {
			continue
		}
		fmt.Println(i) // use i
		s, err := getString()
		if err != nil {
			continue
		}
		fmt.Println(s) // use s
		b, err := getBytes()
		if err != nil {
			continue
		}
		return b, nil
	}
	fmt.Println(err)
	return nil, err
}
```

### What did you expect to see?

I expect to see the last err is returned.

### What did you see instead?

I get nil instead.

### Point

`:=` should be more clever. A defined variable in parent block scope should be not redefined. Only undefined variable can be defined just like `:=`'s behaviour in the same block.

**Comment by minux** [comment]
The variable redefinition behavior has been defined by the
language specification and we can't change it without breaking
existing Go programs.

Please ask questions on forums: https://golang.org/wiki/Questions.

Closing as there is nothing we can do.
