### ISSUE TITLE
build: freebsd/arm is flaky (memory corruption?)

### ISSUE THREAD

**Issue by josharian** [golang/go#16917]
Just on the front page of build.golang.org, I see:

https://build.golang.org/log/70def938cb56a09f6dff143b976a79340baa0e8f
https://build.golang.org/log/a3898e3eab6a2f7db95aef5388a04713feb4ac79
https://build.golang.org/log/4df567faa5ea973c2a05e985bb659d7bb2c26831
https://build.golang.org/log/45ec2ba0ebc6cf57eb80d764267f208d97a92a2a

These are all over the map and smell like memory corruption. Possibly related to #15658?

Does anyone have a freebsd/arm machine that they can do a stress test / bisection on? I fear it maybe 71ab9fa312f8266379dbb358b9ee9303cde7bd6b, but it'd be good to know more confidently before digging into that commit.

**Comment by minux** [comment]
I think there are prebuilt freebsd SD images available for raspberry pi.
It's probably easier to have a local installation.

**Comment by josharian** [comment]
I don't have physical access to any of my machines for a week and a half. Will plan to look then.

**Comment by quentinmit** [comment]
@josharian Have you had a chance to investigate this further?

**Comment by quentinmit** [comment]
It seems like the freebsd/arm builders have fallen off the face of the earth on Oct 5. Presumably they're still flakey, though.

**Comment by josharian** [comment]
I got as far as burning a pre-built freebsd SD card for my rpi but couldn't get it to boot. Unsure whether hardware or software or wetware problem. I'll try again at some point, although I have a lot in my queue at this point.

**Comment by minux** [comment]
Josh, try connecting the serial port and you should be able to see
what's going on.

**Comment by josharian** [comment]
It was a hardware problem (dead board). I now have FreeBSD-11.0-STABLE-arm-armv6-RPI2-20161021-r307749.img running on an rpi 2 b, bootstrapping with cross-compiled Go 1.7.3. First all.bash failed with

```
--- FAIL: TestStackGrowth (83.41s)
        stack_test.go:114: finalizer did not run
FAIL
FAIL    runtime 209.282s
```

but that looks more like a flake than the failures I saw on the build dashboard. Will update again when I have more data, although it'll be a while--it runs very slowly.

**Comment by josharian** [comment]
I've been running all.bash in a loop for 12 hours and haven't seen a single failure. (I had to bump up the `TestStackGrowth` timeout, though.) And looking at the dashboard, I don't see any non-timeout failures in a while. I think whatever was going on is either fixed or was never real to begin with (e.g. due to flaky memory hardware on the builder), so I'm going to close this. I'll keep all.bash running overnight, and will reopen if I see anything tomorrow morning.

And at some point, when I have a better physical setup for doing so, maybe I'll run an additional freebsdm/arm builder, since the current one seems to be struggling to keep up.

**Comment by josharian** [comment]
Just one runtime test flake overnight. Calling it good.

```
--- FAIL: TestGoroutineCounts (0.04s)
        pprof_test.go:659: expected sorted goroutine counts:
                goroutine profile: total 102
                39 @ 0x39dac 0x39e74 0x149ac 0x14644 0xe77a8 0x62378
                #       0xe77a7 runtime/pprof_test.func3+0x2b   /home/freebsd/go/src/runtime/pprof/pprof_test.go:633
                
                31 @ 0x39dac 0x39e74 0x149ac 0x14644 0xe7764 0x62378
                #       0xe7763 runtime/pprof_test.func2+0x2b   /home/freebsd/go/src/runtime/pprof/pprof_test.go:632
                
                11 @ 0xe777c 0x62378
                #       0xe777c runtime/pprof_test.func3+0x0    /home/freebsd/go/src/runtime/pprof/pprof_test.go:633
                
                9 @ 0xe7738 0x62378
                #       0xe7738 runtime/pprof_test.func2+0x0    /home/freebsd/go/src/runtime/pprof/pprof_test.go:632
                
                8 @ 0x39dac 0x39e74 0x149ac 0x14644 0xe7720 0x62378
                #       0xe771f runtime/pprof_test.func1+0x2b   /home/freebsd/go/src/runtime/pprof/pprof_test.go:631
                
                2 @ 0xe76f4 0x62378
                #       0xe76f4 runtime/pprof_test.func1+0x0    /home/freebsd/go/src/runtime/pprof/pprof_test.go:631
                
                1 @ 0x39dac 0x39e74 0x149ac 0x14644 0xb4938 0xb71d4 0xb4634 0xb548c 0xb4c40 0xe8978 0x39964 0x62378
                #       0xb4937 testing.(*T).Run+0x263          /home/freebsd/go/src/testing/testing.go:717
                #       0xb71d3 testing.runTests.func1+0x53     /home/freebsd/go/src/testing/testing.go:900
                #       0xb4633 testing.tRunner+0x123           /home/freebsd/go/src/testing/testing.go:679
                #       0xb548b testing.runTests+0x23b          /home/freebsd/go/src/testing/testing.go:906
                #       0xb4c3f testing.(*M).Run+0xcb           /home/freebsd/go/src/testing/testing.go:841
                #       0xe8977 main.main+0xc7                  runtime/pprof/_test/_testmain.go:60
                #       0x39963 runtime.main+0x1e3              /home/freebsd/go/src/runtime/proc.go:185
                
                1 @ 0xd5e60 0xd5cb8 0xd32f8 0xe7910 0xb4634 0x62378
                #       0xd5e5f runtime/pprof.writeRuntimeProfile+0x77          /home/freebsd/go/src/runtime/pprof/pprof.go:612
                #       0xd5cb7 runtime/pprof.writeGoroutine+0x73               /home/freebsd/go/src/runtime/pprof/pprof.go:574
                #       0xd32f7 runtime/pprof.(*Profile).WriteTo+0x2af          /home/freebsd/go/src/runtime/pprof/pprof.go:300
                #       0xe790f runtime/pprof_test.TestGoroutineCounts+0x14f    /home/freebsd/go/src/runtime/pprof/pprof_test.go:655
                #       0xb4633 testing.tRunner+0x123                           /home/freebsd/go/src/testing/testing.go:679
                
FAIL
FAIL    runtime/pprof   12.249s
``
