### ISSUE TITLE
FAQ is outdated or not clear on sizes of floating point numbers

### ISSUE THREAD

**Issue by lernisto** [golang/go#16916]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

using `go version go1.7 linux/amd64`

### What did you do?
https://play.golang.org/p/CF7xy52g2B

### What did you expect to see?

float32   4: 40000000
float32   4: 40c90fdb
complex64   8: 4000000040400000

(https://play.golang.org/p/OvRuleLGR5)

https://golang.org/doc/faq#q_int_sizes states

 On the other hand, floating-point scalars and complex numbers are always sized: float32, complex64, 
 etc., because programmers should be aware of precision when using floating-point numbers. The 
 default size of a floating-point constant is float64. 

### What did you see instead?

float64   8: 4000000000000000
float64   8: 401921fb54442d18
complex128  16: 40000000000000004008000000000000

**Comment by cznic** [comment]
I fail to detect what the perceived problem is. The default type of a floating point constant is specified to be float64, which is what the code produces when no specific type is provided.

**Comment by ianlancetaylor** [comment]
I don't see a bug here.  Please comment if you disagree.

**Comment by lernisto** [comment]
"floating-point scalars and complex numbers are always sized: float32, complex64"
How is this possible if constants are float64? How can you create a scalar float value without 
a) specifying the type with var, or b) using a constant with :=?

After playing with it, I discovered that there are no `float` or `complex` basic types, and I understand why. Ah Ha! That's what the FAQ is saying. I missed the ", etc." OK, for me, the confusion would not have occurred with the following wording:

> 
On the other hand, there is no `float` or `complex` type: you must always choose a size. Programmers should always be aware of precision when using floating point numbers. The default size of a floating point constant is `float64`, so `foo := 3.0` will create foo with type `float64` and `bar := 3+2i` will create `bar` with type `complex128`. If you want `float32` or `complex64`, you will have to explicitly say so. e.g. `var f1 float32`.


I would suggest making this a separate paragraph from the `int` part that precedes it.

**Comment by lernisto** [comment]
BTW: I would make a PR, but I haven't found the repo for the web site.

**Comment by minux** [comment]
The web site content is in the doc directory of the go repository.

**Comment by ianlancetaylor** [comment]
Constants in Go are untyped.

Change to the FAQ are done as changes to the file doc/go_faq.html following the directions at https://golang.org/doc/contribute.html

**Comment by lernisto** [comment]
Yes, constants are untyped, but if you say `whatever := constant` then whatever is definitely typed.

https://go-review.googlesource.com/27998

Wow. That is a lot of work to make a simple change. But the second change will be easier.
