### ISSUE TITLE
tools/cmd/goimports: compile error on Go 1.4

### ISSUE THREAD

**Issue by jmhodges** [golang/go#16921]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Linux and amd64. This is on a Travis CI machine.

### What did you do?
Attempted to `go get golang.org/x/tools/cmd/goimports` with Go 1.4.

### What did you expect to see?

goimports installing.

### What did you see instead?

`github.com/lib/pq` `travis.yml` errors out when building against Go 1.4 because its installation of goimports can't find `runtime/trace`.

I made sure it built against the latest goimports by dropping an extra `-u` in there. You can see an example failed build at <https://travis-ci.org/jmhodges/pq/jobs/156090817> as well as that build's [travis.yaml]( https://github.com/jmhodges/pq/blob/292e0664f9d84e2e26de2e1835644ebacd360e26/.travis.yml). I'm not sure why there's an implicit `gc` build flag on that version, though? Or maybe build flags were introduced later than I thought?

I'm working on a workaround for `pq` in case this gets closed if 1.4 is no longer supported by the tools repo.

**Comment by bradfitz** [comment]
Dup of #16444, #16661, etc. No longer supported.

**Comment by jmhodges** [comment]
Thanks!
