### ISSUE TITLE
compress: always return uncompressed data in the event of error

### ISSUE THREAD

**Issue by js6626069** [golang/go#16924]
For some applications it would be useful to be able to decompress only the beginning of a truncated archive. For example, for web content filtering by file type, it is usually sufficient to only look at the first few bytes of a response ("magic bytes") to determine if the content should be filtered, which greatly improves performance.

As of Go 1.7, decompressing the beginning of a truncated archives is not supported. I tested this for `compress/gzip`, `compress/zlib` (both of which use `compress/flate`) and `compress/bzip2`.

Here is a simple example demonstrating the problem with `compress/gzip`: https://play.golang.org/p/S5WaR_bvy9
The compression algorithms seem to read the compressed data in blocks. In the case of a truncated archive, bytes may be missing from the end of the first block, so the error "unexpected EOF" is returned and nothing is written to the reader, as we can see in the example. However, even in the face of a truncated block, the algorithm should be able to decompress the first bytes of the block. The UNIX tool `zcat` is able to do so when invoked on the same input data:

    $ zcat /tmp/test.gz
    <!DOCTYPE html>
    gzip: /tmp/test.gz: unexpected end of file

`zcat` also encounters the "unexpected EOF" error, but still returns all the bytes it can decompress. It would be nice to have that in Go too.

This should actually not be too hard to implement. At least for `compress/flate`, the decompressor already holds the decompressed bytes in an internal data structure when the "unexpected EOF" occurs. Writing those bytes to the reader is thus merely a matter of adding something like

    if f.err == io.ErrUnexpectedEOF {
        f.flush(f.step)
    }

to `(*flate.decompressor).Read`. Alternatively, we could add a new method to flush the currently decompressed bytes to a reader, in case of an error.

**Comment by dsnet** [comment]
For `flate`, `gzip`, `zlib`, it's easy to return uncompressed data mid-block in a truncated stream since they are LZ-based compression streams.

For `bzip2`, it's difficult to return data when truncated mid-block since it's not obvious how to perform the inverse BWT with only part of the symbols.
