### ISSUE TITLE
x/crypto/ssh: ssh_message_ignore (message type 2) causing an error on Dial()

### ISSUE THREAD

**Issue by treehau5** [golang/go#16927]
### What version of Go are you using (`go version`)?

go1.7 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?

darwin, amd64 
### What did you do?

attempted to connect to an ssh server via /x/crypto/ssh using ssh.Dial()
### What did you expect to see?

A successful connection.
### What did you see instead?

 `unexpected message type 2 (expected one of [31])`

RFC4253 states "all implementations must understand and subsequently ignore this message at any time" but the package is treating it as an invalid message type, causing the transmission attempt to fail. (see https://tools.ietf.org/html/rfc4253#page-26)

**Comment by belak** [comment]
We're running into this server-side as well. The issue appears to be that in the handshake transport, it's not ignored properly, as during the handshake, there are multiple messages exchanged in a specific order. However, it looks like it's valid for msgIgnore to come between those.

At the end of `enterKeyExchangeLocked` we use `t.conn.readPacket` which can return msgIgnore. As an example, in `(t *handshakeTransport) readLoop()` msgIgnore is ignored as expected, but when we fall back to the underlying connection, we still get those messages.

**Comment by belak** [comment]
CC @agl @hanwen

**Comment by treehau5** [comment]
There is one caveat in that the requirement to accept this message type is only levied after the identification string is sent which should happen after the connection is established. I don't think that is the case here since the message type it is expecting is related to key exchanging. Key exchange comes after the identification string  has been sent.

**Comment by belak** [comment]
I'm not as familiar with this part of the protocol (yet) but it seems like the identification string is always the first line sent and it's not a part of a packet. So, anywhere packets are sent and received, msgIgnore can show up.

**Comment by belak** [comment]
I feel like it should be fine to ignore msgIgnore at the transport level... unless there's any pressing need, couldn't `t.conn.readPacket` just never return msgIgnore?

Or does that mean other stuff has to be refactored because we translate messages into msgIgnore to drop them in at least one instance.

**Comment by hanwen** [comment]
you should be able to drop in the code that decrypts a packet.

**Comment by athom** [comment]
I encounter the same issue when I use crypto/ssh for client side.
Thanks @belak and @treehau5, I made a hacking and solved my problem now.
My solution is doing a retry the `t.conn.readPacket` every time it return the `msgIgnore`.
I would like to contribute my code, but I don't think it is a good way to fix.

![](http://content.screencast.com/users/yeer/folders/Jing/media/32aba32b-8206-4ddb-afba-c104e96e4c21/00002062.png)


> couldn't t.conn.readPacket just never return msgIgnore?

I feel it was a good suggestion, had voted +1.

> you should be able to drop in the code that decrypts a packet

could you explain more?

**Comment by belak** [comment]
It looks like this should have been closed a few days ago. https://github.com/golang/crypto/commit/7c6cc321c680f03b9ef0764448e780704f486b51
