### ISSUE TITLE
go1.7 runtime error on CentOS6 when go get ...

### ISSUE THREAD

**Issue by hao1118** [golang/go#16925]
I just updated go to v1.7 on my centos6 server, when installing new packages, the console always shows runtime error and some vars already defined, something like that. When downgraded to v1.63, everything is OK.

**Comment by davecheney** [comment]
I'm sorry, you have not given us any details to work with.

Can you please follow the issue template (close this issue and open an new one if you have lost the template)

**Comment by hao1118** [comment]
OK, let me reinstall v1.7 and post the details.
