### ISSUE TITLE
x/crypto/acme/autocert: Manager.Client uses internal type

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#16938]
I'm sure this is in the radar, but in case it isn't, the Manager.Client field
is of type acme.Client, but that acme package is internal (golang.org/x/crypto/acme/internal/acme)
and so can't be imported, so it's not possible to use that field.

**Comment by bradfitz** [comment]
Yeah, it's probably time to move the acme package out of internal. We put it there during development so we didn't surprise people when the API changed every day.

@crhym3, feel free to move it up. But be sure to mention in the package doc both that it's not a stable API yet (users should vendor) and give a pointer to the autocert package.

**Comment by crhym3** [comment]
Completely forgot about this, sorry. Will do it later today.
