### ISSUE TITLE
runtime: regression in memmove

### ISSUE THREAD

**Issue by dsnet** [golang/go#16939]
Commit 3607c5f4f18ad4d423e40996ebf7f46b2f79ce02 caused a regression.

On my machine, running in a VM:
Kernel: `Linux 3.13.0-37-generic`
CPU: `Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz`
CPU flags: `fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm`

I see the following crash (using golang/text@09c7ea1fcb3345da09be5a32c9c52303acd1dc2c):
```
$ go.tip test golang.org/x/text/search
signal: illegal instruction
FAIL	golang.org/x/text/search	0.002
```

Running with gdb indicates that it's in memmove.s
```
$ gdb ./search.test
Starting program: /home/rawr/search.test 

Program received signal SIGILL, Illegal instruction.
runtime.memmove () at /usr/local/go.tip/src/runtime/memmove_amd64.s:345
345		VMOVDQU	(SI), Y4
```

\cc @randall77 @dvnagorny

**Comment by bradfitz** [comment]
@dsnet, feel free to revert that change. Reverting & investigating later is a fine strategy.

**Comment by davecheney** [comment]
+1, please revert the change.

**Comment by dsnet** [comment]
This [change has been reverted](https://go.googlesource.com/go/+/6fb4b15f98bba7ef3966c5edc6b8fe2cc99c6beb), but the github mirror seems to be lagging behind the source repo.

**Comment by diegomontoya** [comment]
For my non-vm system, ./make.bash core dumps with tip (69e7e8a696825fa818b70587563ac68e52f8b1a1) . Same build with yesterday's master was fine. Related or same issue.

````
./make.bash: line 173:  2117 Illegal instruction     (core dumped) CC=$CC_FOR_TARGET "$GOTOOLDIR"/go_bootstrap install $GO_FLAGS -gcflags "$GO_GCFLAGS" -ldflags "$GO_LDFLAGS" -v std cmd
```

```
model name	: Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz
stepping	: 5
microcode	: 0x7
cpu MHz		: 2533.216
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm
bugs		:
bogomips	: 5065.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
```
