### ISSUE TITLE
doc: docs.html links to code.google.com/p/go-tour

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16933]
This link is old:

```
doc/docs.html:<a href="//code.google.com/p/go-tour/">install it locally</a>.
```

**Comment by odeke-em** [comment]
Aha, nice catch @bradfitz. I saw this too, late Sunday night along with https://github.com/golang/go/blob/master/doc/gccgo_contribute.html#L15
and had changed the references locally to point to the respective location, but just hadn't committed the code nor mailed out a CL.
