### ISSUE TITLE
doc: add FAQ answer for conversion between []T1 and []T2 where each has underlying type T 

### ISSUE THREAD

**Issue by kortschak** [golang/go#16934]
See [discussion on golang nuts](https://groups.google.com/d/topic/golang-nuts/jDcUu4gUIRc/discussion).

The post by @iant [here](https://groups.google.com/d/msg/golang-nuts/jDcUu4gUIRc/n5romSSSBQAJ) could be worked into a good answer to explain the reasons behind not allowing the conversion being asked about in the golang nuts thread.

/cc @adg

**Comment by rsc** [comment]
Not sure this Q is FA.

**Comment by kortschak** [comment]
Over the past few years I've seen it on the order of a dozen times on golang-nuts. This is vastly more than for some questions that are answered on the FAQ which I have not seen ever asked there (although there is an obvious acquisition bias in this comparison).
