### ISSUE TITLE
restful retorna 204 sin contenido en el body

### ISSUE THREAD

**Issue by fabianpallares** [golang/go#16941]
Tengo el siguiente problema: Quiero procesar una función que retorne 204 en el código de estado HTTP y la función no finaliza nunca.

El problema, es que yo estoy retornando en la cabecera del mensaje, en el campo authorization, un token para que el cliente pueda procesar los futuros recursos rest.

Este recurso, no necesita retornar absolutamente nada en el cuerpo del mensaje, pero sí necesito retornar en la cabecera una llave (un token).
Al hacer esto, se queda colgado el servicio.

La referencia del código de estado 204 es clara, no debe retornar contenido en el cuerpo. Solo en el cuerpo. Pero sí es posible retornar información en campos de la cabecera del mensaje.

En C# puedo hacerlo. Puedo retornar 204 sin contenido en el cuerpo y con contenido en la cabecera.

Actualmente con golang, tengo que retornar un objeto de manera forzada que no me representa nada de valor, ya que estoy obligado a retornar 200 con algún valor en el cuerpo del mensaje.

La cuestión, es que yo tengo una función que se llama "Retornar", el cual me resuelve estas cuestiones de manera automática. La función es la siguiente:

    // Responder el resultado de la consulta
    // Retornar el resultado restful por HTTP
    func Responder(w http.ResponseWriter, token string, respuesta interface{}) {
	    estadoHttp := Estado_200_Ok // int 200

		// Verificar Si el valor a retornar es de tipo recursos.Error
		// o es de un tipo de estructura del negocio.
		err, esError := respuesta.(*Error)
		if esError {
			estadoHttp = err.EstadoHttp
		} else {
			if respuesta == nil {
				estadoHttp = Estado_204_SinContenido // 204
			}
		}

		// Si el token tiene un valor, retornarlo en el campo
		// "authorization" del Header del mensaje.
		if token != "" {
			w.Header().Set("authorization", token)
		}

		// Valores de retorno del mensaje por defecto:
		// Retorno en JSON y conjunto de caracteres UTF-8
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.WriteHeader(estadoHttp)

		// Escribir en el body siempre y cuando no sea vacío
		if respuesta != nil {
			if err := json.NewEncoder(w).Encode(respuesta); err != nil {
				panic(err)
			}
		}
    }

Muchísimas gracias, les envío un muy fuerte abrazo.
Adoro golang, me encanta. Para mi es como volver a desarrollar en C, es como volver a mis 18 años.

Fabián Alejandro Pallares
Buenos Aires, Argentina
+54 11 5753-5678

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.6.3

### What operating system and processor architecture are you using (`go env`)?
Windows / Linux (Servidores Ubuntu y Centos)

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Soy un desarrollador.

### What did you expect to see?
Espero que la respuesta de un servicio rest cuyo código de estado es 204, finalice normalmente.

### What did you see instead?
Cuando realizo pruebas, la petición se queda colgada. Nunca finaliza de procesar la función.

**Comment by Thomasdezeeuw** [comment]
I think most people reading these issues prefer English and after translating this seems more like a question then an issue, please see https://golang.org/wiki/Questions for the future.

But adding the following might fix your problem:

```go
 if respuesta == nil {
	w.WriteHeader(http. StatusNoContent)
	return
}
```

**Comment by bradfitz** [comment]
> En C# puedo hacerlo. Puedo retornar 204 sin contenido en el cuerpo y con contenido en la cabecera.

You can return a "204 No Content" response with header values in Go too:

https://play.golang.org/p/bxy_rEBy-s

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by fabianpallares** [comment]
Un millón de gracias !!!
Les pido perdón, pero lamentablemente yo no se escribir en inglés.   :(

No es tan simple la vida en el sur del mundo. Tengan piedad de mí: soy argentino.  :)
Muchísimas, muchísimas gracias.

**Comment by Jackgris** [comment]
Hola Fabian, yo también soy de Argentina, te recomiendo que leas bien el enlace que te paso Dave. (sobre todo la lista de correo) y como bien dice, este no es un buen lugar para realizar preguntas.
En el caso, del impedimento del idioma, es bueno que veas estas dos comunidades:
https://plus.google.com/communities/105964860738231827761
https://plus.google.com/communities/110325783890611262108
Saludos

**Comment by bradfitz** [comment]
This ended up being a problem with some particular client software (some buggy Firefox extension), not with Go.
