### ISSUE TITLE
gccgo: reject typed non-int len/cap arguments to make

### ISSUE THREAD

**Issue by martisch** [golang/go#16949]
while writing test cases in https://go-review.googlesource.com/#/c/28301/ for #16940 
this inconsistency turned up:

gc (tip https://github.com/golang/go/commit/f8555ea6fdbbfc32e26f351ac16138fad31a2d62 and playground 1.7)  accept it but the go/types test does not:

```
type    TCOMPLEX64  complex64

_ = make([]byte, TCOMPLEX64(1+0i))
```

trybot error:

stdlib_test.go:123: /tmp/workdir/go/test/fixedbugs/issue16940.go:49:22: invalid argument: index TCOMPLEX64(1 + 0i) (constant (1 + 0i) of type TCOMPLEX64) must be integer

\cc @josharian @dsnet @griesemer @randall77 @ianlancetaylor

**Comment by griesemer** [comment]
This is a compiler bug. The spec says very clearly: "The size arguments n and m must be of integer type or untyped." (https://tip.golang.org/ref/spec#Making_slices_maps_and_channels).

go/types reports the correct error.

**Comment by griesemer** [comment]
@ianlancetaylor gccgo appears to have the same problem. It accepts this code silently.

**Comment by martisch** [comment]
thanks. In that case i will prepare a CL to fix checkmake in typecheck.go to reject these cases.

**Comment by josharian** [comment]
CL 28301 fixed cmd/compile. Changing the issue to be able gccgo.
