### ISSUE TITLE
cmd/compile: nil pointer dereference in walk

### ISSUE THREAD

**Issue by dsnet** [golang/go#16940]
Using ffa2bd2. The offending commit is probably something recent (last 2 weeks).

I'm seeing this compiler failure building a (proprietary) test:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b43b2]

goroutine 1 [running]:
panic(0xa2e120, 0xc42000e0a0)
	src/runtime/panic.go:502 +0x1b2
cmd/compile/internal/gc.(*Mpint).Cmp(0x0, 0xc42007b1d0, 0xc424c325a0)
	src/cmd/compile/internal/gc/mpint.go:252 +0x22
cmd/compile/internal/gc.walkexpr(0xc424c32630, 0xc44340f498, 0xc424c32900)
	src/cmd/compile/internal/gc/walk.go:1521 +0xa23c
cmd/compile/internal/gc.walkexpr(0xc424c327e0, 0xc44340f498, 0x0)
	src/cmd/compile/internal/gc/walk.go:738 +0x1261
cmd/compile/internal/gc.walkstmt(0xc424c327e0, 0xc424c32a20)
	src/cmd/compile/internal/gc/walk.go:192 +0xe59
cmd/compile/internal/gc.walkstmtlist(0xc439669900, 0x11, 0x20)
	src/cmd/compile/internal/gc/walk.go:80 +0x4d
cmd/compile/internal/gc.walk(0xc424c439e0)
	src/cmd/compile/internal/gc/walk.go:65 +0x1e4
cmd/compile/internal/gc.compile(0xc424c439e0)
	src/cmd/compile/internal/gc/pgen.go:391 +0x1d4
cmd/compile/internal/gc.funccompile(0xc424c439e0)
	src/cmd/compile/internal/gc/dcl.go:1258 +0x186
cmd/compile/internal/gc.Main()
	src/cmd/compile/internal/gc/main.go:484 +0x2065
cmd/compile/internal/amd64.Main()
	src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	src/cmd/compile/main.go:33 +0x2a3
```

\cc @randall77 @mdempsky @ianlancetaylor 

I'm still trying to strip the offending code into a smaller reproduction. Any advice on how to isolate the problem is welcome.

**Comment by bradfitz** [comment]
Which test? (which source code reproduces this?)

/cc @josharian @davecheney

**Comment by randall77** [comment]
Probably this: https://github.com/golang/go/commit/e6f9f39ce52e880b54e4cb08bf0cde73cf6c7dc2

@martisch

**Comment by dsnet** [comment]
I confirm that the offending commit is e6f9f39.

**Comment by davecheney** [comment]
Thanks for confirming. @dsnet, would you please revert that commit.

**Comment by josharian** [comment]
How urgent is this, @dsnet? Can we try rolling forward?

**Comment by josharian** [comment]
AFK but my guess from my recollection of that CL is that the error stems from something like `make([]T, n)` where n is a named int type.

**Comment by dsnet** [comment]
Not urgent. It was 1 build failure out of many thousands.

**Comment by davecheney** [comment]
I would prefer to continue the practice of reverting changes rather than
trying to muscle through.

**Comment by josharian** [comment]
Reproduction:

```go
package src

func f(n T) []byte { return make([]byte, 0, T(0i)) }

type T complex64
```

Will send a fix tomorrow if @martisch doesn't beat me to it.

As for "muscling through", new code will frequently introduce bugs. Reverting on every single bug, during the open dev period, will add a lot of overhead. I am all for reverting when it's during the freeze, or it causes significant breakage that might impede other developers or cause unnoticed further build breakage, or the bug is subtle or unknown and might take a long time to track down, etc. This is a small bug with a minor impact and a minor fix. Let's just fix it.

> It was 1 build failure out of many thousands.

Ouch.

**Comment by bradfitz** [comment]
I'm fine rolling forward here if the fix is known and everybody can work and build.golang.org isn't all red and impeding workflows.

This just broke on some internal Google code on a test run of tip Go, not affecting anybody, so yay... @dsnet's early testing of Go 1.8 is already bearing fruit.

**Comment by martisch** [comment]
Working on the fix and new test cases.

**Comment by dsnet** [comment]
CC me on the fix and I'll test the change on the failing test case.

**Comment by josharian** [comment]
@dsnet based on Robert's comment in #16949, I suspect that the compiler is soon going to reject your test case.
