### ISSUE TITLE
net/http: Response.Write includes Content-Length header on 204s

### ISSUE THREAD

**Issue by bradfitz** [golang/go#16942]
Apparently we send a Content-Length header on a 204 response:

https://play.golang.org/p/bxy_rEBy-s

A 204 can't have a body anyway, so the Content-Length is useless and misleading. (It might be a protocol violation? Haven't checked.)

**Comment by freeformz** [comment]
https://tools.ietf.org/html/rfc7230#section-3.3.2

```
...
 A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).
...
```

**Comment by bradfitz** [comment]
Oh, we're fine actually. This is a bug in Response.Write. It's correct on the network:

https://play.golang.org/p/ettdRyiOtn

**Comment by 0xmohit** [comment]
Athough this appears to be specifically about 204, [an existing test](https://github.com/golang/go/blob/master/src/net/http/responsewrite_test.go#L256) expects Content-Length with a status code of 1xx.
