### ISSUE TITLE
flag: NewFlagSet returns a FlagSet with a nil Usage func

### ISSUE THREAD

**Issue by d3ce1t** [golang/go#16955]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.6.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

Mac OS X 10.11.6
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?

Create a new flag.FlagSet and call Usage() function.

Please, find the source code related to this issue in the following link: https://play.golang.org/p/_GujXXUvno

### What did you expect to see?

Printed information on screen about used flags.

### What did you see instead?

Runtime error because of nil pointer dereference

**Comment by bradfitz** [comment]
It's been like this since Go 1: https://github.com/golang/go/blob/release-branch.go1/src/pkg/flag/flag.go#L785

So, super low priority. Maybe documentation.

/cc @robpike
