### ISSUE TITLE
go routine leak in net/http.(*persistConn).readLoop+0x9c8 and writeLoop

### ISSUE THREAD

**Issue by spx** [golang/go#16953]
go 1.7 stable
centos 6.4

426 @ 0x4416ea 0x450c79 0x44fa6c 0x4c72e9 0x472411
#	0x4c72e8	net/http.(*persistConn).readLoop+0x9c8	/usr/local/go/src/net/http/transport.go:1536

426 @ 0x4416ea 0x450c79 0x44fa6c 0x4c866d 0x472411
#	0x4c866c	net/http.(*persistConn).writeLoop+0x3bc	/usr/local/go/src/net/http/transport.go:1641

//code
var trans *http.Transport
func init() {
	trans = &http.Transport{
		DisableKeepAlives:  true,
		DisableCompression: true,
	}
}
trans.RoundTrip(req)

**Comment by bradfitz** [comment]
You need to close your Response.Body. See the net/http docs.

A better forum for discussion is probably the mailing list. See https://golang.org/wiki/Questions

**Comment by spx** [comment]
i close...

**Comment by alex-hsl** [comment]
me,too

**Comment by spx** [comment]
sometimes (randomly) it doesnt work. looks like response body ignores Close call
after 100k requests or works several days and then sometimes appears readLoop + writeLoop. these go routines are not used anymore and they slowly grows. and i think they are not in idle conns list. 
```
resp, err = hc.Transport.RoundTrip(req)
if resp != nil {
	if resp.Body != nil {
		defer resp.Body.Close()
	}
}
if err....
```

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
