### ISSUE TITLE
x/mobile: Iphone 4s supported ?

### ISSUE THREAD

**Issue by joeblew99** [golang/go#16966]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build614371786=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I am running the standard example at: 
https://github.com/golang/mobile/tree/master/example/bind

### What did you expect to see?

running in SIM and actual IPhone 4s

### What did you see instead?

![screen shot 2016-09-02 at 14 46 05](https://cloud.githubusercontent.com/assets/11999859/18204249/03fbae3c-711c-11e6-9887-df8f8779e2b4.png)

**Comment by minux** [comment]
you need to disable bitcode as Go archives produced by gobind
doesn't contain bitcode.

**Comment by joeblew99** [comment]
thanks @minux 
Yep that was it. Fixed the problem for me.
Ironically last week we dropped support for older IPhones, so i dont really need to deal with this anymore.

**Comment by FZambia** [comment]
@minux hello, if disabling bitcode is a required step for deploying gomobile bindings on all real iOS devices why there is no information about it nowhere in readme, wiki, godoc etc? I was unfamilar with iOS ecosystem before and actually it was a bit unexpected when my lib was almost ready and I started to test it on actual device.

**Comment by joeblew99** [comment]
@FZambia i hit this problem too.

I guess its nto there because its only relevent for older IOS devices ?
Also IOS no longer works on an idevice this ancient. so its kind of irrelevent now i guess

**Comment by FZambia** [comment]
> I guess its nto there because its only relevent for older IOS devices ?

@joeblew99 I don't think this is related to old devices only - because Apple introduced bitcode not so long ago (end of 2015) and it's already required for watchOS and tvOS.

**Comment by joeblew99** [comment]
definitely my mistake then. Maybe i got it the wrong way round, but thanks
for pointing it out.
