### ISSUE TITLE
x/crypto/ssh: guessed kex handled improperly

### ISSUE THREAD

**Issue by belak** [golang/go#16962]
### Go env information

```
% go version
go version go1.7 linux/amd64
% go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/belak/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build164292563=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

Attempt to connect to a golang ssh server using dropbear

### What did you expect to see?

A successful handshake

### What did you see instead?

Dropbear fails to connect, claiming the server closed the connection.

I initially tested disabling the guess in dropbear entirely, and that avoids this bug. Enabling debugHandshake, I saw `server exited key exchange (first true), err ssh: unexpected message type 30 (expected 21)`

https://tools.ietf.org/html/rfc4250#section-4.1.2 states that 21 is SSH_MSG_NEWKEYS (essentially the end of the kex) and https://tools.ietf.org/html/rfc5656#section-7.1 states that 30 is SSH_MSG_KEX_ECDH_INIT. So, this means the server was getting an extra 30 before getting 21.

### Potential fix

Under https://tools.ietf.org/html/rfc4253#section-7, it states that a guess can be counted as wrong if "the kex algorithm and/or the host key algorithm is guessed wrong (server and client have different preferred algorithm)" or all the algorithms cannot be agreed upon. Currently the check in x/crypto/ssh only checks `algs.kex != otherInit.KexAlgos[0]` and not the host key algorithm. The following patch is a quick and dirty way of solving this which also checks the host key algorithm. I'm not sure what the proper solution would be, but if requested, I can try to submit this.

This is what was causing the problem because the server and the client didn't agree that the first kex packet should be ignored, so the client sent another one (because it realized that the host key algorithms didn't match) and the server thought it was fine (because the kex algorithm matched). After the first kex packet is handled by the server, it finds another one, and not SSH_MSG_NEWKEYS as expected.

```patch
diff --git a/ssh/handshake.go b/ssh/handshake.go
index ae26191..04ad3e7 100644
--- a/ssh/handshake.go
+++ b/ssh/handshake.go
@@ -371,7 +371,7 @@ func (t *handshakeTransport) enterKeyExchangeLocked(otherInitPacket []byte) erro
        }
 
        // We don't send FirstKexFollows, but we handle receiving it.
-       if otherInit.FirstKexFollows && algs.kex != otherInit.KexAlgos[0] {
+       if otherInit.FirstKexFollows && (algs.kex != otherInit.KexAlgos[0] || algs.hostKey != otherInit.ServerHostKeyAlgos[0]) {
                // other side sent a kex message for the wrong algorithm,
                // which we have to ignore.
                if _, err := t.conn.readPacket(); err != nil {
```

**Comment by mkj** [comment]
That fix looks good, though I think the original code was also wrong in comparing the agreed algorithm. It should compare the first ("preferred") myInit algorithm? Something like this:

```diff
diff --git a/ssh/handshake.go b/ssh/handshake.go
index ae26191..3fb58f0 100644
--- a/ssh/handshake.go
+++ b/ssh/handshake.go
@@ -371,7 +371,9 @@ func (t *handshakeTransport) enterKeyExchangeLocked(otherInitPacket []byte) erro
        }
 
        // We don't send FirstKexFollows, but we handle receiving it.
-       if otherInit.FirstKexFollows && algs.kex != otherInit.KexAlgos[0] {
+       if otherInit.FirstKexFollows &&
+               (myInit.KexAlgos[0] != otherInit.KexAlgos[0] ||
+                       myInit.ServerHostKeyAlgos[0] != otherInit.ServerHostKeyAlgos[0]) {
                // other side sent a kex message for the wrong algorithm,
                // which we have to ignore.
                if _, err := t.conn.readPacket(); err != nil {

```
(I'm the Dropbear developer)

**Comment by belak** [comment]
CC @agl @hanwen
