### ISSUE TITLE
Possible float64 precision bug in go 1.7

### ISSUE THREAD

**Issue by huichen** [golang/go#16964]
### What version of Go are you using (`go version`)?

go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/newhome/unmerged/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build710415065=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

code snippet as following

```
package main

import (
	"fmt"
)

func main() {
	var budget float64
	budget = float64(36.98)
	fmt.Printf("%d", uint64(budget*10000))
}
```

### What did you expect to see?

369800

### What did you see instead?

369799

**Comment by martisch** [comment]
This is not a bug. Other programming languages e.g. python will give the same result.

Floating point with 64bits can not represent budget*10000 precisely and the result is
369799.99999999994.

For float to integer conversion according to the go spec: 
"When converting a floating-point number to an integer, the fraction is discarded (truncation towards zero)."

So 369799.99999999994 is truncated to 369799 for uint64.

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
