### ISSUE TITLE
x/mobile: ios, No matching provisioning profiles found

### ISSUE THREAD

**Issue by joeblew99** [golang/go#16967]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

1.7
### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build159594453=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?

building this: https://github.com/golang/mobile/tree/master/example/network
### What did you expect to see?

On android i get the green / blue screen as i expect.
On IOS i expected the same.
### What did you see instead?

```
x-MacBook-Pro:network apple$ gomobile build --target=android
x-MacBook-Pro:network apple$ gomobile build --target=ios
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/gomobile-work-486467550/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “org.golang.todo.network” were found.

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)

```

**Comment by ZetaChow** [comment]
I get same ERROR ! How to fix it!

**Comment by joeblew99** [comment]
i never worked it out..

I can build other things for IOS, just not with gomobile

**Comment by viru** [comment]
This is a duplicate of #12660, check there for workarounds.

**Comment by joeblew99** [comment]
hey @viru 
Thats does sound exactly like what i experience too.  Thanks for letting me know.

The problem is that its not really fixed. The fix is to hardcode a namespace into the gomobile tool and then recompile. 

@eliasnaur
Could someone on the gomobile team think about fixing this obvious tooling bug ?
What might be best is a command line flag for compiling for ISO ? This woudl then get ride of the hardcoded constant in the common code as shown at the https://github.com/golang/go/issues/12660

**Comment by eliasnaur** [comment]
I agree that it seems like an obvious tooling bug, but unfortunately iOS provisioning and signing is not obvious to me. I'll gladly review any CL that attempts a fix.

**Comment by joeblew99** [comment]
@shurcool did you ever get past this ??

**Comment by shurcooL** [comment]
No, I haven't built for mobile recently. My latest status was https://github.com/golang/go/issues/12660#issuecomment-145306339.

**Comment by joeblew99** [comment]
in summary, for now I guess i will also just have to maintain my own fork and hack it too.

@shurcooL 
thanks for update. 

@eliasnaur
 i doubt i have the skills to fix this. IOS signed etc is also newish to me, and when it works i am shocked half the time :)

**Comment by egonelbre** [comment]
I'm looking into fixing this.

I think the first solution should be to allow specifying the BundleID (and Android package ID) manually and direct people to create an application in XCode with the specified identifier. This would make gomobile easier to use now, with little effort. _PS: Currently when I tried to use an existing profile then xcodebuild also required to specify DEVELOPMENT_TEAM (that can be detected from the provisioning profile)._

Then as a next step there are few ideas:

1. Try to figure out how to create provisioning profile automatically (command-line tools or write the code). Unfortunately, I haven't yet found a nice way to do it. We can create BundleID with this https://play.golang.org/p/ZiOkpaU3HP... but this could still be problematic when you want to build application that is already registered and you don't have the signing key.
2. Use wildcard AppID for multiple apps (https://developer.apple.com/library/content/qa/qa1713/_index.html) -- this would avoid the need to create manually multiple profiles. There probably are restrictions when doing it in this way.
3. Combine XCode and gomobile. When selecting a new project there are templates "Empty" and "External-Build-System"... maybe we can use XCode to trigger "gomobile" with the correct parameters. Or create a custom template for gomobile.

Any thoughts?

**Comment by egonelbre** [comment]
PS: it seems that #12660 is pretty much the same issue? Should the discussion be moved there and this closed as a duplicate?

**Comment by joeblew99** [comment]
@egonelbre Thanks for picking this up.
yes #12660  is the same. i will close this, so it can be worked on at #12660
