### ISSUE TITLE
net/http/httptrace: Add TLS handshake timing information

### ISSUE THREAD

**Issue by sajal** [golang/go#16965]
httptrace currently does not offer a way to measure the TLS handshake of a request when using https. This might be trivial to implement in [net/http/transport.dialConn](https://golang.org/src/net/http/transport.go#L1012) by adding a few more callbacks in httptrace. I suggest `TLSHandshakeStart` and `TLSHandshakeDone` . 

A hacky solution I am considering for now is to use `ConnectDone` as a proxy for `TLSHandshakeStart` and `WroteRequest` as a proxy for `TLSHandshakeDone`, but its better to have the real measurements.

PS: Thanks a lot for httptrace. I am now removing lots of ugly hacks from my project and letting the standard library do its thing.

**Comment by moorereason** [comment]
The delta between `ConnectDone` and `GotConn` is the TLS negotiation time.  My understanding is that `ConnectDone` means "TCP dial completed" and `GotConn` means the http package received a connection on which it can begin sending HTTP requests.  The TLS handshake happens between those two events.

If nothing else, the godocs could be updated to make this more apparent.

**Comment by freeformz** [comment]
If there is interest in a CL for this I will submit one. I was thinking of adding the following methods to httptrace.ClientTrace:

```go
	// TLSHandshakeStart is called when tls.Handshake() is started.
	// When connecting to a https destination through a https proxy
	// TLSHandshakeStart could be called twice
	TLSHandshakeStart func()

	// TLSHandshakeDone is called after tls.Handshake is done
	// When connecting to a https destination through a https proxy
	// TLSHandshakeDone could be called twice.
	TLSHandshakeDone func(tls.ConnectionState)
```

**Comment by bradfitz** [comment]
The "could be called twice" part is a little confusing. It should probably distinguish which conn it is.

How do we deal with the proxy conn stuff elsewhere in httptrace?

**Comment by freeformz** [comment]
@bradfitz Looks like I misread the code last night.

How just this instead...

```go
    // TLSHandshakeStart is called when tls.Handshake() is started.
    TLSHandshakeStart func()

    // TLSHandshakeDone is called after tls.Handshake is done
    TLSHandshakeDone func(tls.ConnectionState)
```

Side Note: When we connect to a https site through a http proxy, the TLSHandshakeStart/Done fire after the CONNECT bridges the connection through the proxy. Not sure if we should bother calling that out or not.
