### ISSUE TITLE
nacl: support mmap

### ISSUE THREAD

**Issue by tv42** [golang/go#16975]
GOOS=nacl seems to implement `runtime·mmap` in terms of `NACL_SYSCALL(SYS_mmap)`, but not expose a `syscall.Mmap` (or `golang.org/x/sys/unix#Mmap`). It'd be great to be able to use mmap even from a sandboxed process.

Use case: https://github.com/boltdb/bolt/issues/571

**Comment by minux** [comment]
Just make a large enough []byte for mmap.

NaCl can't access files by default, so mmap could only used
to allocate memory.

**Comment by tv42** [comment]
@minux The whole point is to cooperate with the thing starting the sandbox; see https://github.com/golang/go/issues/7930

**Comment by minux** [comment]
syscall.Syscall6 is supported, you just need to hardcode the
syscall number (21).

**Comment by ALTree** [comment]
With nacl support being removed in 1.14 (#30439), this seems unlikely to be implemented. Closing here.
