### ISSUE TITLE
Build Error (github mirror) OSX 10.10 (building go from source)

### ISSUE THREAD

**Issue by skaller** [golang/go#16970]
Installed Binary: go version go1.7 darwin/amd64
Repository: GitHub master as at approx Sept 1 2016.

OSX101.0 (darwin/amd64)
Standard xcode installed AND
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-apple-darwin14.5.0log/syslog
installed from LLVM website.

<pre>~/go/src>GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
...
##### Building packages and commands for darwin/amd64.
# crypto/x509
crypto/x509/root_cgo_darwin.go:16:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^
1 error generated.
net/mail</pre>

The bin directory contains gofmt. No compiler or other binaries.
Not sure what to expect, since first attempt to build.

**Comment by ianlancetaylor** [comment]
By default, Go will build with support for calling C code, and on Darwin will call into C code to retrieve the set of trusted root certificates.  This requires you to have xcode installed.

Or, you can build without xcode and without support for calling C code by setting `CGO_ENABLED=0` in the environment.

Closing because there isn't a bug that we can fix.  You may find it easier to ask questions on a forum; see https://golang.org/wiki/Questions .

**Comment by skaller** [comment]
I have xcode installed. You have to explain the error, its YOUR error. Your code assumes
something about the available C headers which is incorrect. I am trying to build the same
go as you would for distribution, so disabling a key feature is not an option.

Traditional (horrible) configuration systems check the available resources
are available so that the do not bug out in an incomprehensible way.
If this file is required, and is not standard on all OSX/xcode installs, you should 
test for it and bug out the build with a suitable message.

**Comment by skaller** [comment]
BTW: this is the ONLY error I see. Other parts of the system appear to build without error.
Its possible Apple has changed the headers on you. They seem to do that
regularly. In that case it IS your problem.

**Comment by quentinmit** [comment]
CoreFoundation.h is a standard header that exists in all working XCode
installs. If you do not have it, your XCode install is broken. Perhaps the
compiler on your PATH is not from your XCode install? Or perhaps you have
not installed the XCode command line tools?

**Comment by bradfitz** [comment]
I agree that something is broken with @skaller's xcode install.

We've never seen this on any of our builder machines (vanilla OS X, all versions + XCode), and users haven't reported this either.

**Comment by skaller** [comment]
Why do you say "perhaps"? I state clearly that I have a version of clang which was installed from LLVM website. I also have the stock Xcode installed. CoreFoundation.h exists:

<pre>
~/felix>locate CoreFoundation.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreFoundation.framework/Versions/A/Headers/CoreFoundation.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreFoundation.framework/Versions/A/Headers/CoreFoundation.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h</pre>

so clearly the fault is in your build. You should be calling /usr/bin/clang not clang:

Given this file:

<pre>
#include <CoreFoundation/CoreFoundation.h>
int main(){ return 0; }
</pre>

this works just fine:

<pre>
~/felix>/usr/bin/clang -framework CoreFoundation xx.c
</pre>

but this fails:

<pre>
~/felix>clang -framework CoreFoundation xx.c
xx.c:1:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^
1 error generated.
</pre>

I'm not sure why but that's not the issue: you cannot assume that the default clang is the xcode supplied one. That's like invoking gcc, which on OSX 10.10 actually calls clang by default, but not on my system because I have a real gcc installed.

Build systems are complex and messy, I spent several years on the one for my system (argghh). But they're intrinsically the responsibility of the builder not the client. If there is a condition like "the xcode clang must be the one on the path" they you should document that because, as I said, upgrading one's compiler is pretty usual for a developer.

I suggest you change your build system to call /usr/bin/clang instead of just clang.

**Comment by skaller** [comment]
For my part I will remove my upgraded clang from my PATH and see how far I get.

**Comment by bradfitz** [comment]
Why would we force /usr/bin/clang if you've configured your environment to prefer a different compiler? That's your choice.

If you change your environment or upgraded compiler to put CoreFoundation.h in your C include path, it should work.

Supporting every possible compiler configuration is not a goal for the project. Most users install binaries. Users who are compiling Go from source usually use the default C compiler. You're off in on-your-own land. At this point we assume you know what you're doing. For a user who's chosen their own compiler, it would be equally surprising for us to override it.

Maybe we could emit a warning on failure, though, noting that the compiler used is not what is typically seen.

**Comment by skaller** [comment]
Just so you know, removing my upgraded clang from the PATH fixed the build. So your build is definitely broken, and the fix is easy: use /usr/bin/clang not clang as the C compiler.

You don't need to support "every possible compiler configuration". You just need to call the xcode supplied one. Its not enough to say as the docs do, that xcode must be installed. Obviously because it didn't work for me. Note, I did not modify anything supplied by xcode.

It may be, at some stage, I understand enough go and enough about building it that I will indeed "know what I'm doing" but most people get errors like this on their very first build attempt, as I did.

**Comment by skaller** [comment]
BTW: its silly to assume "I know what I'm doing". Sure, I have a Mac. I also have a Windows box and use a remote Ubuntu system. I develop platform independent code (more or less) so I have never heard of CoreFoundation.h before. @quentinmit obviously know more about Apple software setup than I do, and of course about go and its tools. I do know something about custom service though .. I always support my customers, not dismiss their issues without investigation.

**Comment by ianlancetaylor** [comment]
Set the `CC` environment variable to the compiler you want to use when building Go.

We are not going to change the Go build to prefer /usr/bin/clang over whatever clang is first in your `PATH`.

**Comment by skaller** [comment]
Fair enough, then please document that this in the build instructions if not already done?
