### ISSUE TITLE
sync/atomic, cmd/compile: stack corruption with AddUint32

### ISSUE THREAD

**Issue by iangudger** [golang/go#16985]
### What version of Go are you using (`go version`)?
devel +fd41951

### What operating system and processor architecture are you using (`go env`)?
AMD64 Linux

### What did you do?
Compile and run this program:
```go
package main

import "sync/atomic"

var count uint32

func main() {
	buffer := []byte("T")
	for i := 0; i < len(buffer); {
		atomic.AddUint32(&count, 1)
		_ = buffer[i]
		i++
		i++
	}
}
```

### What did you expect to see?
No output. This is what happens in Go 1.7.

### What did you see instead?
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x458f40, 0xc42000a150)
	/go/src/runtime/panic.go:500 +0x1a0
main.main()
	inc_panic_example/main.go:11 +0x76
```

**Comment by dsnet** [comment]
Nice. Thanks for the report.

Git bisect reports the cause as d6098e4277bab633c2df752ed90e1e826918ca67. 
/cc @randall77 @cherrymui
