### ISSUE TITLE
io: MultiReader doesn't free input readers after use (Go 1.7)

### ISSUE THREAD

**Issue by PhilipBorgesen** [golang/go#16983]
I've noticed that io.MultiReader doesn't set input reader references to nil before shrinking its slice. From my understanding of Go's garbage collector this means that the Readers won't be freed before the whole underlying array is freed.

In other words I propose that:

```
n, err = mr.readers[0].Read(p)
if err == EOF {
	mr.readers = mr.readers[1:]
}
```
is changed to:
```
n, err = mr.readers[0].Read(p)
if err == EOF {
	mr.readers[0] = nil
	mr.readers = mr.readers[1:]
}
```
In my encounter with this issue, the MultiReader may unnecessarily hold references to potentially large buffers (8 MB) for extended periods of time, wasting memory.

**Comment by randall77** [comment]
@bradfitz

**Comment by rakyll** [comment]
There is something more troubling about MultiReader. Even when MultiReader is collected, the readers are not. See https://play.golang.org/p/9dX8bk8P_I.

**Comment by rakyll** [comment]
I put the example above in a loop and I now can see r1s are collected later in the program's life. It is just not immediately collected in the first passes. Maybe because of the mr->r1 dependency.

**Comment by bradfitz** [comment]
@rakyll, more discussion of the liveness issues in #16996.
