### ISSUE TITLE
x/build/cmd/release: windows installer propose to remove detected old version in installation directory

### ISSUE THREAD

**Issue by techtonik** [golang/go#16986]
### What version of Go are you using (`go version`)?

go1.6.3.windows-386.msi
### What operating system and processor architecture are you using (`go env`)?

```
set GOROOT=C:\Program Files\Go
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
```
### What did you do?

Run installer `go1.6.3.windows-386.msi`, it didn't detect existing 1.6.2 installation, so I thought that maybe it is a feature to run multiple versions of Go side by side. Pointed it to existing `C:\Program Files\Go` installation.
### What did you expect to see?

Expected it at least to warn about non-empty directory, then tell me what is he going to do with it:
1. remove
2. blend its files inside
3. fail
### What did you see instead?

I see request for administration privileges to continue installation.

**Comment by 0xmohit** [comment]
The [current instructions](https://golang.org/doc/install?download=go1.7.windows-amd64.msi) mention:

> If you are upgrading from an older version of Go you must first [remove the existing version](https://golang.org/doc/install?download=go1.7.windows-amd64.msi#uninstall).

**Comment by techtonik** [comment]
@0xmohit yea, I saw that, but many open source projects automate this in installer - for example VLC installer detects old installation and proposes several actions:

![image](https://cloud.githubusercontent.com/assets/515889/18231488/9c5a9a82-72c3-11e6-808c-27c8cf3b315f.png)

https://github.com/videolan/vlc/tree/master/extras/package/win32

**Comment by bradfitz** [comment]
Related: #16305

We don't have a Windows installer expert on the team. Any help is wanted.

**Comment by iWdGo** [comment]
Warning as displayed to install Go 1.12beta1 seems to solve the issue:
![go uninstall warning](https://user-images.githubusercontent.com/19574010/50375747-e26ce780-0602-11e9-820f-1b4ebfe93ce2.JPG)

**Comment by bradfitz** [comment]
Thanks. Will close then.
