### ISSUE TITLE
x/mobile: attaching method docs to generated code

### ISSUE THREAD

**Issue by karalabe** [golang/go#16998]
This is a feature request / discussion starter rather than an issue. AFAIK gomobile only generates pure code, but doesn't attach any documentation to the generated classes. I think we could improve heavily on this by taking the docs from the original Go code and trying to move it over to Java/ObjC.

Was this ever considered, and if yes but decided against, I'd be curious of the reasoning behind it.

**Comment by eliasnaur** [comment]
Implemented in golang.org/cl/52330.
