### ISSUE TITLE
runtime: remove maxstring restriction when printing strings

### ISSUE THREAD

**Issue by martisch** [golang/go#16999]
go tip (go1.7 and many before)

in runtime/string.go there is a maxstrings variable that starts with a value of 256 and is updated whenever rawstring is called.

This limit can be expanded by concatenating any strings.

However it is not consistent with what the length of the longest go string really is:

https://play.golang.org/p/BUY9zhs7pT

package main

```
func main() {
	s := "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"+
	     "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"+
	     "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"+
 	     "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"
	_ = s+" "
	print(s)
}
```

e.g. defining a string constant that is longer than the starting maxstring value will not print.

when updating the maxstring length by e.g. adding the string with " " (or adding any other strings where the concatination is longer than orginal s) the above program prints the string fine.

Since gwrite later just truncates the string in a copy if it does not fit into the g.writebuf there seems no risk of out of bounds write. Since the limit can just be pushed upwards by arbitrary string concatenations there seems also to be no protection against the string output being cut off early depending on g.writebuf capacity.

Removing maxstring and running ./all.bash did not reveal any immediate problems.
( apart from an explicit test that maxstring is updated by gostringnocopy which would be obsolete once maxstring is removed )

rsc "I don't see that it's causing any harm, and it's still useful.":
https://groups.google.com/forum/#!msg/golang-dev/J2OiPumlwuc/neEqKcCWyf8J

however that seems to be from a time where runtime was not written in go and we did not have extra updates to maxstrings in e.g. gostringnocopy https://github.com/golang/go/issues/8706 .

Would it be ok to remove maxstrings in runtime and maxstring updates from runtime/strings.go nowadays? 

If not should cases were this protection against broken go string lengths is overprotecting be fixed (e.g. similar to /go/issues/8706) ?

/cc @josharian @randall77

**Comment by josharian** [comment]
To be clear, is the motivation for removing it performance? code cleanliness?

I'm inclined towards removing it, but this is really not my call. Russ or Keith, maybe.

If we don't remove it, it'd be nice to fix printing of long constant strings.

**Comment by martisch** [comment]
A bit of all:
- it seems to be not documented what it is really protecting against, so i am not sure how useful it still is and if that couldn't be done differently then globally keeping maxstring up to date
- if not removing it i would guess there are more places we need to take care of that maxstring is updated if a larger string is created that could be printed. ( Which is more difficult the more places there are were string([]byte) temporaries are made for the runtime without allocating a new string but just as a unsafe view on an existing byteslice )
- performance would be a secondary concern (need to benchmark) but it is generally nice to have less globally synchronized variables if they can be easily replaced by other mechanisms.

**Comment by ianlancetaylor** [comment]
I believe the original purpose of `maxstring` was to avoid printing enormous amounts of garbage if the runtime somehow got a garbage string.

Given that you've found a case where it is causing harm, I think we can reasonably remove it.  It seems silly to go into contortions to preserve it.

**Comment by bradfitz** [comment]
@ianlancetaylor, that was @rsc's recommendation yesterday too.

**Comment by ianlancetaylor** [comment]
@bradfitz Thanks, I didn't see that.

**Comment by martisch** [comment]
thanks for the feedback. I will go forward then and submit my local test CL to remove maxstring and maxstring updates after some final polish.
