### ISSUE TITLE
net/http: returned typed error when proxy connection fails

### ISSUE THREAD

**Issue by tcmichael** [golang/go#16997]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

$go version
go version go1.6.2 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
package main

import (
    "fmt"
    "net"
    "net/http"
    "net/url"
    "time"
)

func main() {
    proxy := "http://2.2.2.2:80"
    tr := &http.Transport{
        Proxy: func(*http.Request) (*url.URL, error) {
            return url.Parse(proxy)
        },
        Dial: (&net.Dialer{Timeout: 500 * time.Millisecond}).Dial,
    }
    c := http.Client{Transport: tr}
    req, _ := http.NewRequest("GET", "http://golang.org", nil)
    _, err := c.Do(req)
    uerr, ok := err.(*url.Error)
    if ok {
        nerr, ok := uerr.Err.(*net.OpError)
        fmt.Println(ok, nerr)
    }
}
```
### What did you expect to see?

```
true, http://2.2.2.2:80: dial tcp 2.2.2.2:80: i/o timeout".
```

I could find the Op of the error would be dial.
net/http/transport.go: 765 "err = fmt.Errorf("http: error connecting to proxy %s: %v", cm.proxyURL, err)". 
That rewrites the error, and the details of the error are missing
### What did you see instead?

```
false <nil>
```

**Comment by asticode** [comment]
Hey guys, if everyone is OK with I'd like to take a stab at it
