### ISSUE TITLE
Compiler still allows unused variables to pass by!

### ISSUE THREAD

**Issue by zexerlang** [golang/go#17004]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 on AMD64 architecture.

### What did you do?
Since warnings are errors, people use a workaround to fool the compiler. They assign a variable or function result to the blank identifier (underscore), which fools the compiler into thinking that var is used.

### What did you expect to see?
I expected compiler to stop and say that variable is still unused, because assigning to blank identifier does nothing.

### What did you see instead?
Compiler successfully compiled the file.

### Solution

1. Treat the assignment of variables to blank identifier as if the var is still unused. This will make the compiler stop and report error, which is consistent with golang philosophy so far.

2. Or a better solution, don't report an error when a variable is not used. Report a warning. And don't treat warnings as errors. 

True, warnings should be very visible, in BOLD ORANGE font. Not only during compilation, but in runtime the app should say "THIS APP IS UNFINISHED AND CONTAINS WARNINGS AND POSSIBLE BUGS". So that whoever releases such an app to production has to explain himself.

BUT, during debugging and experimenting it's a complete waste of time to constantly comment and uncomment code, or delete vars which will be required just a few seconds later. This completely kills the joy of working and experimenting in golang.

If you ever see a laboratory or workshop where everything is nice and tidy, and every tool is at the right place, then either the shop is closed, or it's a place full of dull people which will never make something new, good and innovative.

**Comment by bradfitz** [comment]
This debate has been played out on the golang-nuts@ mailing list many times. The Go policy hasn't changed in this regard for the past 8 releases. It's not going to change now.
