### ISSUE TITLE
cmd/vet: failed import causes spurious printf error

### ISSUE THREAD

**Issue by alandonovan** [golang/go#17006]
```
$ cat a.go
package main

import "nosuchpkg"

var format = "%s %s"
var _ = nosuchpkg.Sprintf(format, "a", "b")

$ vet ~/a.go
/usr/local/google/home/adonovan/a.go:6: no formatting directive in Sprintf call
```

The `printf` check issues a spurious error when type information for an imported printf-like function is not available.  Without the function's type signature, the checker heuristically assumes that the first string constant is the format string, such as `"a"` in the example above.

**Comment by josharian** [comment]
cc @valyala

**Comment by valyala** [comment]
Prepared [the CL](https://go-review.googlesource.com/29014).
