### ISSUE TITLE
src/log/log.go: What makes it expensive in this code of log.go?

### ISSUE THREAD

**Issue by maxwell92** [golang/go#17003]
Hey, It's commented "release lock while getting caller info - it's expensive" in source code of /src/log/log.go line:150. 

I'm confused with what makes it expensive if we didn't unlock the l.mu ? 

```golang
func (l *Logger) Output(calldepth int, s string) error {
	now := time.Now() // get this early.
	var file string
	var line int
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.flag&(Lshortfile|Llongfile) != 0 {
		// release lock while getting caller info - it's expensive.
		l.mu.Unlock()
		var ok bool
		_, file, line, ok = runtime.Caller(calldepth)
		if !ok {
			file = "???"
			line = 0
		}
		l.mu.Lock()
	}
	l.buf = l.buf[:0]
	l.formatHeader(&l.buf, now, file, line)
	l.buf = append(l.buf, s...)
	if len(s) == 0 || s[len(s)-1] != '\n' {
		l.buf = append(l.buf, '\n')
	}
	_, err := l.out.Write(l.buf)
	return err
}
```

AND

What will happen if I moved the `_, file, line, ok = runtime.Caller(calldepth)` like below?

```golang
func (l *Logger) Output(calldepth int, s string) error {
	now := time.Now() // get this early.
	var file string
	var line int
       
        //moved here
    var ok bool
    _, file, line, ok = runtime.Caller(calldepth)

	l.mu.Lock()
	defer l.mu.Unlock()

        l.buf = l.buf[:0]
	if l.flag&(Lshortfile|Llongfile) != 0 {
		if !ok {
			file = "???"
			line = 0
		}
	        l.formatHeader(&l.buf, now, file, line)
	}
	
	l.buf = append(l.buf, s...)
	if len(s) == 0 || s[len(s)-1] != '\n' {
		l.buf = append(l.buf, '\n')
	}
	_, err := l.out.Write(l.buf)
	return err
}
```
Thanks for all

**Comment by davecheney** [comment]
Generating a stack trace is expensive, and would block any other call to Log while doing so

**Comment by maxwell92** [comment]
@davecheney Yes you are right. And without l.mu.Unlock(), it may lead to problems if the goroutine was suspended while calling the runtime.Caller(). 

How do you think of the next code spec below `What will happen if I moved the _, file, line, ok = runtime.Caller(calldepth) like below?`

**Comment by davecheney** [comment]
It's just about contention on the lock, nothing more.

**Comment by maxwell92** [comment]
@davecheney Sorry I didn't test it, but I do believe the code below works better. Mutex Lock() and Unlock() will cost time in the original one. The code below just get rid of this cost. Am I right?

**Comment by davecheney** [comment]
Please close this issue, a discussion like this is best held on
golang-nuts.
