### ISSUE TITLE
x/tools/cmd/goimports: 

### ISSUE THREAD

**Issue by tomerf8** [golang/go#17013]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.6.2 (appengine-1.9.40) darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tomerf/go"
GORACE=""
GOROOT="/usr/local/go_appengine/goroot"
GOTOOLDIR="/usr/local/go_appengine/goroot/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
`go get -u golang.org/x/tools/cmd/goimports`

### What did you expect to see?
`goimports installed`

### What did you see instead?
```
# golang.org/x/tools/imports
src/golang.org/x/tools/imports/fastwalk_unix.go:23: readDir redeclared in this block
       	previous declaration at src/golang.org/x/tools/imports/fastwalk_portable.go:18
```

**Comment by bradfitz** [comment]
This is almost certainly because you're using the AppEngine version of Go to fetch a binary, and it's making assumptions about dependent packages that you want to run them on App Engine.

Use the normal Go binary to install goimports.

/cc @okdave @broady (Is there anything to do here?)
