### ISSUE TITLE
Cross-compilation and GOROOT

### ISSUE THREAD

**Issue by pcj** [golang/go#17017]
I'm working on golang cross-compilation support for bazel within [rules_go](https://github.com/bazelbuild/rules_go).  rules_go jumps through a number of hoops to marry golang's and bazel's filesystem opinions, requiring the explicit use of `GOROOT`.  

What I'm finding is that for cross-compilation of the stdlib via `go install stdlib`, GOROOT must be an absolute path, without symlinks.  For reasons outside of the scope of this question, the absolute path can be challenging to figure out within bazel.  

Is this expected behaviour?  Any suggested workaround?

darwin/amd64, go1.6.2 and go1.7

**Comment by pcj** [comment]
Actually just realized one workaround may be to get the abs path from `go env`, but question remains if behavior is expected.  Thanks.

**Comment by bradfitz** [comment]
In general, `cmd/go` is very hostile towards symlinks, which nobody seems to mind. So at least that part I would find to be expected.

There is https://golang.org/pkg/path/filepath/#EvalSymlinks to evaluate symlinks if that helps.

**Comment by bradfitz** [comment]
But the golang-dev mailing list might be a better place to discuss this, per https://golang.org/wiki/Questions 

There's nothing actionable for us to do here, so closing for now. If there's an identified bug or feature request, then we can track its resolution.

**Comment by dr2chase** [comment]
Not quite nobody, but I gave up trying to figure out why or how to fix it.
