### ISSUE TITLE
doc: define the first class ports

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17018]
build.golang.org links to "First Class Ports":

https://github.com/golang/go/wiki/PortingPolicy

But that doesn't say which ports are the first class ones.

Further, the checkbox on https://build.golang.org to show only first class ports seems to only filter by GOOS, not (GOOS,GOARCH), so it shows things like linux-mips64le and linux-ppc64 as being first class, which I don't think is true. We don't even have linux-ppc64 big-endian builders at the moment.

Let's clarify.

**Comment by broady** [comment]
I'm pretty sure about these ones:

OS | arch
--- | ----
Windows | 386, amd64
Linux | 386, amd64, armv6l
Darwin | 386, amd64

Any others, someone will have to make an argument for.

FreeBSD? The runtime is not considered stable, so I'd make a case for it not being considered first-class until [these issues](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20runtime%20label%3AOS-FreeBSD%20) are resolved.

**Comment by ianlancetaylor** [comment]
See also #14612.

**Comment by ianlancetaylor** [comment]
My vague understanding is that the first class ports are the ones for which we provide a binary download.  According to https://golang.org/doc/install.html that is "FreeBSD (release 8-STABLE and above), Linux, Mac OS X (10.8 and above), and Windows operating systems and the 32-bit (386) and 64-bit (amd64) x86 processor architectures."  According to the downloads page, that is darwin/amd64, freebsd/386, freebsd/amd64, linux/386, linux/amd64, linux/arm, linux/s390, windows/386, windows/amd64.

**Comment by bradfitz** [comment]
@ianlancetaylor, that's necessary but not sufficient. That's one of the three conditions listed at https://github.com/golang/go/wiki/PortingPolicy#first-class-ports

We now distribute binaries for s390x, even though the majority of Go contributors are unable to contribute fixes to it.

We also ship binaries for FreeBSD, despite instability, and we didn't stop the Go 1.7 release for it. If we had runtime crashing bugs for Linux (or even Windows), we certainly would've debugged more before shipping. That shows that FreeBSD is not a first class port.

**Comment by laboger** [comment]
We had a discussion about including ppc64le as a first class port so its binary would be included on the dl page here https://groups.google.com/forum/#!topic/golang-dev/D1-F7mDP65Y

I would like to request ppc64le be included as a first class port.

**Comment by bradfitz** [comment]
@laboger, those are two different things. What you actually want are binary downloads. We did that for FreeBSD and s390x, even though I argue neither of those is a first class port. It's possible we could host ppc64{,le} binaries, but I don't think we're ready to make ppc64 a first-class port just yet. I'll let @ianlancetaylor, @dr2chase, et al chime in.

**Comment by broady** [comment]
Also, even if a port meets the three conditions on the PortingPolicy page, it doesn't automatically become a first-class port.

That's why we need a page that explicitly lists the first-class ports.

**Comment by robpike** [comment]
A first-class port by definition is one we deem to be so. List them (which we do) and the question is answered.

A separate question is the set of criteria for deciding when a port is first-class, or no longer first-class. I don't believe those criteria need to be rigid. We can use judgment.

**Comment by rsc** [comment]
PortingPolicy says

> A first class port has these properties:
> - Broken builds block releases
> - Official binaries are provided
> - Installation is documented at http://golang.org/doc/install

Those are supposed to be all true or all not, for each port. More specifically, I believe the list on /doc/install under supported systems is the master list of first-class ports. I have certainly edited that list in the past with that in mind.

We have in the past agreed to put up binaries for other ports, but we should do a better job of clarifying them on the download page as not officially supported.

**Comment by bradfitz** [comment]
We need to decide how to label these binaries-but-not-first-class downloads. "2nd-class" sounds bad. "Community" isn't quite right. "Preview" also doesn't entirely correct.

I don't want a label that suggests "Flaky" or "Not so good".

**Comment by josharian** [comment]
Unsupported?

**Comment by josharian** [comment]
Unofficial?

**Comment by bradfitz** [comment]
Except we do support them, and they come from us, so they're kinda official?

**Comment by josharian** [comment]
If it is just for website copy, maybe First Class ports and Other ports, and allow conversational implicature to do the rest.

**Comment by mdempsky** [comment]
"Silver ports"

**Comment by robpike** [comment]
Incomplete

**Comment by bradfitz** [comment]
@josharian, agreed. That's effectively what we have now with "Featured Downloads" and then the table.

We can make the table split into two sections:

1. Primary Ports
2. Other Ports

(I don't like using the word "class" too prominently.)

SGTY, @broady?

**Comment by broady** [comment]
SGTM. Will send a CL this week.

**Comment by bradfitz** [comment]
I've updated the wiki to match @cbro's split of the download page binaries.

The wiki at https://github.com/golang/go/wiki/PortingPolicy#first-class-ports now says:

The current first class ports are:

* linux/amd64
* linux/386
* linux/arm
* darwin/amd64
* windows/amd64
* windows/386

We distribute binaries for other GOOS/GOARCH pairs (other "ports"), but they are not "first class" by this definition.
