### ISSUE TITLE
test/float_lit2: Wrong exponent in comment.

### ISSUE THREAD

**Issue by cznic** [golang/go#17012]
Please answer these questions before submitting your issue. Thanks!

- What version of Go are you using (`go version`)?

tip @ https://github.com/golang/go/commit/0cff219c1279cb76f042004bffcefba0a169cb67

- What operating system and processor architecture are you using (`go env`)?

N/A

----

[test/float_lit2:21](https://github.com/golang/go/blob/0cff219c1279cb76f042004bffcefba0a169cb67/test/float_lit2.go#L21) reads

`// The halfway point is (f₁+f₂)/2 = 2¹²⁸ - 2¹⁰⁵.`

The expression should be `2^128-2^103`, ie. `s/105/103/` above.

If approved, I can send a CL later today.

**Comment by griesemer** [comment]
I think there are other mistakes in this comment as well. The largest float32 exponent is 127, thus the largest float32 is maxMant * 2**127. maxMant is 1 (implicit) + (2**23 -1)/(2**23) = 1 + 1 - 1/(2**23). Together we have maxFloat32 = (1 + 1 - 1/(2**23)) * 2**127 == (2 - 2**-23) * 2**127 == 2**128 - 2**104 == f1 (first line).

With f2 == 2**128, f1 + f2 == 2**128 - 2**104 + 2**128 == 2**129 - 2**104. Thus (f1 + f2)/2 == 2**128 - 2**103, as you suggest.

Feel free to send me a CL and assign it to me for review. Thanks.
