### ISSUE TITLE
Typo in comments / docs

### ISSUE THREAD

**Issue by pete-a** [golang/go#17010]
### What version of Go are you using (`go version`)?
go1.7 darwin/amd64

### What did you do?
Viewed documentation for `crypto/rand Int()` at https://golang.org/pkg/crypto/rand/#Int

### What did you expect to see?
There is a small typo in the comments and therefore the docs: https://github.com/golang/go/blob/master/src/crypto/rand/util.go#L105
I believe `// ... random value in [0, max)` should be `// ... random value in [0, max]` (square bracket)

**Comment by bradfitz** [comment]
Intentional. See https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints
