### ISSUE TITLE
`go list` "can't load package"

### ISSUE THREAD

**Issue by katylava** [golang/go#17027]
### What version of Go are you using (`go version`)?

`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kyl/Code/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6f/k23pyfjx09l61t96dyyg3kyh0000gn/T/go-build752362407=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

`~ > go list`

### What did you expect to see?

a list of installed go packages

### What did you see instead?

`can't load package: package .: no buildable Go source files in /Users/kyl`

---

installed with brew. just uninstalled all go versions and reinstalled and it still happens.

```
 ~ > brew info go
go: stable 1.7.1 (bottled), HEAD
The Go programming language
https://golang.org
/usr/local/Cellar/go/1.7.1 (6,436 files, 250.6M) *
  Poured from bottle on 2016-09-08 at 12:05:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb
```

**Comment by bradfitz** [comment]
That's not what `go list` does.

Run `go help list` for details.
