### ISSUE TITLE
x/tools/cmd/goimports: rewrites imports to include vendored folder in go1.7

### ISSUE THREAD

**Issue by toli** [golang/go#17034]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
MacOSX 10.11.6
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/toli/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z2/gkdbnz8x0bd0yr2l93lny7c40000gn/T/go-build827522954=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
had an `imports` line that was rewritten to include same package from `vendor` directory
```
imports(
-       "gopkg.in/dancannon/gorethink.v2"
+       "github.com/docker/dhe-deploy/vendor/gopkg.in/dancannon/gorethink.v2"
)
```
### What did you expect to see?
No imports rewrites i this case at all; and specifically not changing it to a `/vendor/` location

### What did you see instead?
+       "github.com/docker/dhe-deploy/vendor/gopkg.in/dancannon/gorethink.v2"

This happens on a number of packages, not just the one above and in a number of files

Didn't see this until upgraded from `go 1.6` to `go 1.7`

**Comment by bradfitz** [comment]
Goimports doesn't come with Go, and has nothing to do with Go 1.6 vs Go 1.7.

Can you update your goimports binary and confirm you still see this behavior?

**Comment by toli** [comment]
Update fixed everything. guess lots changed in the past X months since i installed it.

thanks a lot for pointing me to (obviously, i should've done it myself first) the solution
