### ISSUE TITLE
Unable to clean.bash on darwin.

### ISSUE THREAD

**Issue by ggaaooppeenngg** [golang/go#17035]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.7 darwin/amd64`
### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mike/workplace/GOPATH"
GORACE=""
GOROOT="/Users/mike/workplace/go"
GOTOOLDIR="/Users/mike/workplace/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z4/vplvdvkx6fsfv7z6w8pzfqnr0000gn/T/go-build489990318=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

run clean.bash in $GOORT/src 
### What did you expect to see?
I want to use source code in my darwin to build on centos, I want to run clean.bash to make a clean directory to build a new go binary. (For some cgo headers can only be built on Linux).

### What did you see instead?
go: open /Users/mike/workplace/go/src/runtime/internal/sys/zversion.go: no such file or directory

**Comment by davecheney** [comment]
You do not need to use clean.bash. Use make.bash

**Comment by ggaaooppeenngg** [comment]
![image](https://cloud.githubusercontent.com/assets/4769989/18376012/9d9ceba2-768d-11e6-8fed-0657aaa9a5a4.png)

Yes, I got this error first, that's why I try to run clean.bash

**Comment by davecheney** [comment]
I'm pretty sure you working directory contains a mixture of go versions. I
recommend deleting your checkout and starting from a clean checkout.

**Comment by ggaaooppeenngg** [comment]
I download a go1.5 linux binary for GOROOT_BOOTSTRAP, and run `GOROOT_BOOTSTRAP=go1.5path ./make.bash`

I use git to clean the directory `git checkout .` , but still get this message.

**Comment by davecheney** [comment]
> I use git to clean the directory git checkout . , but still get this message. (On centos)

Your working directory is not clean. Check `git status` and be aware that some files may be hidden by `.gitignore`. I recommend you delete your checkout and make a fresh checkout.

**Comment by bradfitz** [comment]
Let's move this to a mailing list.
