### ISSUE TITLE
some questions in fmt source code

### ISSUE THREAD

**Issue by fu607666** [golang/go#17049]
I reorganized this issue. (Don't mind my words, my English is poor.)

I was reading fmt source code and found a few questions:

---

**Question 1**

go/src/fmt/print.go
version 1.7

This format should be the wrong way (%.[1]3d):
```go
fmt.Printf("%.[1]3d", 1)
```
The correct way is (%.3[1]d):
```go
fmt.Printf("%.3[1]d", 1)
```

Replace line 1046(doPrintf method) by the following code to fix:

```go
} else if afterIndex { // "%.[3]2d"
    p.goodArgNum = false
}
```

---

**Question 2**

go/src/fmt/format.go
version 1.7

line 205:
```go
width := 3 + f.wid + f.prec // wid and prec are always positive.
```

For `fmt.Printf("%#60.30x", 1)`, it only needs 63 width, but the value of 'width' is 93, and then, it will allocate more unused memory by `make([]byte, width)`.

I think the right 'width' should be:

```go
width := 3
if f.wid > f.prec {
    width += f.wid
} else {
    width += f.prec
}
```

---

GOARCH=amd64
GOOS=linux

**Comment by martisch** [comment]
```
width *= 2   // should be width += 2
```

fmt.Printf("% #x\n","123") = "0x31 0x32 0x33"

When f.space is set and f.sharp the there is an extra "0x" before every element (which is printed as two bytes). So the length is doubled for each element. From my understanding and the test cases the code is correct.

**Comment by fu607666** [comment]
Oh, yes, I understand is wrong, it should be width *= 2, thank you!

**Comment by martisch** [comment]
While it seems correct that fmt.Printf("%.[1]3d", 1) should not work
but fmt.Printf("%.[1]*3d", 1) should. 

Your fix:
```
Add these code after line 1046 (doPrintf method) to fix:
```
wont work as it would reject e.g.:
fmt.Printf("%.[2]f", 5.0,1.0)

**Comment by fu607666** [comment]
Yes, my fix above is not perfect, if replace line 1046 as following code, It will work well:
```go
} else if afterIndex { // "%.[3]2d"
	p.goodArgNum = false
}
```

**Comment by fu607666** [comment]
I found a new question in format.go (line 205):
```go
width := 3 + f.wid + f.prec // wid and prec are always positive.
```
For fmt.Printf("%#60.30x", 1), it only needs 63 width, but the value of 'width' is 93, and then, it will allocate more unused memory by make([]byte, width).

I think the right width is:
```go
width := 3
if f.wid > f.prec {
	width += f.wid
} else {
	width += f.prec
}
```

**Comment by martisch** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. 

If you find bugs please open a new issue for each new case of a bug.  If you want to propose a detailed code improvement please send a CL: https://golang.org/doc/contribute.html.

In this case it may over allocate but in the most scenarios i would assume width := 3 + f.wid + f.prec is small and just checking if width > len(buf) is faster than having a data dependent branch like the above in addition which makes the common case slower. So my personal opinion is to leave it as is.

**Comment by fu607666** [comment]
OK, I understand. Thank you for your help!
