### ISSUE TITLE
Proposal: add context import path upgrade to go tool fix

### ISSUE THREAD

**Issue by SamWhited** [golang/go#17040]
It would be convenient if `go tool fix` had a rule (possibly off by default?) added to upgrade imports of the context package to the new version in the standard library.

Here is a CL that I'm using to upgrade my projects: https://go-review.googlesource.com/#/c/28872/

This makes the new rewrites list read as follows:

```
Available rewrites are:

context
        Change imports of golang.org/x/net/context to context

gotypes
        Change imports of golang.org/x/tools/go/{exact,types} to go/{constant,types}

netipv6zone
        Adapt element key to IPAddr, UDPAddr or TCPAddr composite literals.

        https://codereview.appspot.com/6849045/

printerconfig
        Add element keys to Config composite literals.
```

This isn't strictly the same as some of the other rewrites in the tool because the old context package is still perfectly usable, so maybe it would be best to leave this fix off by default and allow it to be manually specified.

**Comment by quentinmit** [comment]
You likely want to remain with the old package for quite a while to support building with Go <1.7. I think perhaps we'd want to do this a year or more from now.

**Comment by SamWhited** [comment]
Agreed, having it off by default seems sensible (so that it can still be used if you explicitly want to upgrade)

**Comment by SamWhited** [comment]
I've updated the CL to require the `-force` argument for the context fix to be run (it looks like force wasn't otherwise used). Would this be an acceptible way to do it? The behavior could then be changed after the 1.8 release cycle or whenever the Go team decides it's more appropriate to be default-on.

**Comment by adg** [comment]
cc @bradfitz

**Comment by bradfitz** [comment]
We still ship and use `go tool fix`? Flashback!

**Comment by bradfitz** [comment]
But yeah, SGTM. Opt-in sounds good.
