### ISSUE TITLE
x/net/ipv6: all-{node,routers} or solicited node multicast addresses?

### ISSUE THREAD

**Issue by porjo** [golang/go#17050]
There doesn't appear to be a way to read multicast packets **not** destined for the local host when using `net.PacketConn`.

I'm trying to use `x/net/ipv6` as follows:

```Go
	var c net.PacketConn
	c, err = net.ListenPacket("ip6:ipv6-icmp", ifaceIP.String())
...
	p := ipv6.NewPacketConn(c)
	err = p.SetControlMessage(ipv6.FlagSrc|ipv6.FlagDst, true)
...
	var f ipv6.ICMPFilter
	f.SetAll(true)
	f.Accept(ipv6.ICMPTypeNeighborSolicitation)
	f.Accept(ipv6.ICMPTypeNeighborAdvertisement)
	err = p.SetICMPFilter(&f)
...
	payload := make([]byte, snaplen)
	i, rcm, src, err := p.ReadFrom(payload)
...
```
I would like to read, for example, IPv6 neighbor solicitations where the destination solicited-node multicast address does not belong to the local host.

Can this be done with the standard lib (i.e. not using pcap library)? If not, could it be added? Thanks.

go version go1.6.3 linux/amd64

**Comment by mikioh** [comment]
In accordance with https://golang.org/wiki/Questions, please use golang-nuts instead. FWIW, the packages x/net/{ipv4,ipv6,icmp} are designed for helping implementing userland IP control plane applications, so in general it's possible to read any multicast address defined in RFC 4291. If you think the current package documentation is insufficient, please open a new issue.
