### ISSUE TITLE
bufio: Reader swallows 0-length reads

### ISSUE THREAD

**Issue by droyo** [golang/go#17059]
I have a package that uses bufio.Reader to decode protocol messages. It implements
trace debugging by writing all messages through an `io.Pipe()`. I was surprised to find
that the first 100 0-length writes were ignored by the `bufio.Reader.fill` method, as
the documentation explicitly states

	The bytes are taken from at most one Read on the underlying Reader, hence
	n may be less than len(p).

I would like to suggest a documentation change to indicate that zero-length reads are
not counted.

### What version of Go are you using (`go version`)?

	go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

	GOARCH="amd64"
	GOBIN="/usr/local/bin"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/"
	GORACE=""
	GOROOT="/go"
	GOTOOLDIR="/go/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build706953720=/tmp/go-build -gno-record-gcc-switches"
	CXX="g++"
	CGO_ENABLED="1"

### What did you do?
A zero-length write to an `io.PipeWriter`, whose corresponding
`io.PipeReader` was read through a `bufio.Reader`. The following
simplified program illustrates the issue: https://play.golang.org/p/lI14R5CMQ-

### What did you expect to see?

The program should print one item for every write to the pipe:

	1 foo
	2 bar
	3 
	4 
	5 
	6 baz

### What did you see instead?

The bufio.Reader ignored the 0-byte reads.

	1 foo
	2 bar
	3 baz

**Comment by bradfitz** [comment]
Without looking into the details of this issue just yet, I'll note that 0-byte reads and writes are inconsistent and ill-defined everywhere in Go.

**Comment by ianlancetaylor** [comment]
Any change to bufio in this regard needs to pay attention to #7611.

**Comment by droyo** [comment]
The issue is easy enough to work around if it is documented. I am curious about the original intent behind this behavior.

**Comment by ianlancetaylor** [comment]
@droyo See issue #7611 and the CL that was committed to fix it.  That CL may have been erroneous, but I think that is the intent behind the current behavior.

**Comment by rsc** [comment]
I think this is a bug. The fix in CL 86590043 for ReadByte (for #7745) incorrectly affected Read as well. Will send a CL.

@ianlancetaylor, #7611 is about bufio.Writer, not bufio.Reader, so I think these are mostly independent.
