### ISSUE TITLE
testing: B.Run

### ISSUE THREAD

**Issue by jezek** [golang/go#17055]
go version: go1.6.2 linux/386

Sorry, if this is not relevant, but I can not find answer to this issue:

In documentation the testing pakage has function B.Run(...)
https://golang.org/pkg/testing/#B.Run

But compiler gives me error, that it is undefined.

Am I missing something? why it is in doc and not implemented?﻿

**Comment by bradfitz** [comment]
Introduced in Go 1.7. https://golang.org/doc/go1.7#testing

**Comment by jezek** [comment]
@bradfitz thank you. sorry for inconvenience and a dumb question.
