### ISSUE TITLE
Pointers and pass by value is confusing

### ISSUE THREAD

**Issue by Bleezworld** [golang/go#17062]
Go is great and I love it. However, working with it daily on a relatively big project (20 engineers for 2 years) I see that pointers and byValue are confusing.

Small struct are referred to by value, and bigger struct by reference (both in function parameters and in instance variables)
But

1. We have no idea if this is the right way to do and if this is optimal or not
2. Small structs grow into bigger structs
3. It is hard to see what is there by reference because we need to modify / not copy it, or if it is by reference because it is a large struct

Some guidelines would be much appreciated, or some way of thinking the language in a different way

Note: though the "byValue" is strange at the beginning, I really like that it is the default, it proves to be what we want to do most of the time

Note 2: Im submitting this as an issue but it's more a "feature request" / FAQ kind of thing but I don't know where I should ask

### What version of Go are you using (`go version`)?
1.7.1

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
