### ISSUE TITLE
Feature request : make slices the python way

### ISSUE THREAD

**Issue by Bleezworld** [golang/go#17061]
Go is almost perfect. Working with Go daily for 6 months, this is a typical pattern that we use all the time and would make LOTS of programmers super happy

Having

type A struct {
   name string
}

going from []A to the slice of the names, I have to write:
 
    var objs []A
    ...
    names := make([]string, 0, len(objs))
    for _, obj := range objs {
      names = append(names, obj.name)
   }

when we could just have 

    names := []string[obj.name for _, obj := range objs]

or some similar syntax

Thanks for taking this into consideration!

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
OS X, amd64

**Comment by bradfitz** [comment]
For questions learning the language, see https://golang.org/wiki/Questions

**Comment by Thomasdezeeuw** [comment]
I think this is a proposal rather then a question. That is my interpretation anyway.

**Comment by bradfitz** [comment]
The language is currently frozen, in any case.

**Comment by Bleezworld** [comment]
frozen until when ? Can we get this on the list of "to be discussed" for the next version?

**Comment by bradfitz** [comment]
Consider it on the list for consideration for any future major version of Go.

**Comment by minux** [comment]
List comprehension has been discussed several times in the past, please
search the golang-nuts mailing list archive.
