### ISSUE TITLE
nil check on interface not working properly

### ISSUE THREAD

**Issue by bocajim** [golang/go#17067]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
https://play.golang.org/p/ZePYwF-z_v

### What did you expect to see?
I expected the nil check to be properly evaluated (and the 2nd printf not to be seen).

### What did you see instead?
Using a structure that implements an interface, and returning nil resulted in a nil check that failed.

**Comment by bradfitz** [comment]
https://golang.org/doc/faq#nil_error
