### ISSUE TITLE
cmd/go: cgo generates too long a path on windows

### ISSUE THREAD

**Issue by chai2010** [golang/go#17070]
https://github.com/chai2010/hello-swig-bug

**Comment by Luisa456** [comment]
Long Path Tool can help you to remove blocked files or too long path files. You can easily fix file errors with this software.

**Comment by Thomasdezeeuw** [comment]
I think https://github.com/golang/go/issues/3358 is related.

**Comment by chai2010** [comment]
if use cgo, it is ok. the bug is only for build with x.swig.

**Comment by quentinmit** [comment]
It looks like these filenames are chosen by SWIG, not by Go. Is there anything we can do about that?

**Comment by ianlancetaylor** [comment]
What is the file whose path is too long?

What created that file?

Is the problem that the total path is too long, or that an individual name in the path is too long?

**Comment by chai2010** [comment]
## 1. swig generate the hello_with_tooooooo_long_path.go

swig -go -cgo -intgosize 64 -module hello_with_tooooooo_long_path -o "C:\\Users\\chai\\AppData\\Local\\Temp\\go-build509547282\\github.com\\chai2010\\hello-swig-bug\\_test\\_obj_test\\hello_with_tooooooo_long_path_wrap.c" -outdir "C:\\Users\\chai\\AppData\\Local\\Temp\\go-build509547282\\github.com\\chai2010\\hello-swig-bug\\_test\\_obj_test\\" hello_with_tooooooo_long_path.swig

the full path length is 135.

## 2. then cgo use the hello_with_tooooooo_long_path.go to generate `xxx.cgo1.go`

go tool cgo -objdir "C:\\Users\\chai\\AppData\\Local\\Temp\\go-build509547282\\github.com\\chai2010\\hello-swig-bug\\_test\\_obj_test\\" -importpath github.com/chai2010/hello-swig-bug  "C:\\Users\\chai\\AppData\\Local\\Temp\\go-build509547282\\github.com\\chai2010\\hello-swig-bug\\_test\\_obj_test\\hello_with_tooooooo_long_path.go"

the `xxx.cgo1.go` full path length large than 260 (overflow).

open C:\\Users\\chai\\AppData\\Local\\Temp\\go-build509547282\\github.com\\chai2010\\hello-swig-bug\\_test\\_obj_test\\\C___Users__chai__AppData__Local__Temp__go-build509547282__github.com__chai2010__hello-swig-bug___test___obj_test__hello_with_tooooooo_long_path.cgo1.go: The system cannot find the path specified.

**Comment by ianlancetaylor** [comment]
Thanks.  I don't think there is any swig problem here.  The problem is cgo.  cgo is generating the file WORKDIR/WORKDIRNAME_FILE.cgo1.go where WORKDIRNAME is WORKDIR with the slashes replaced by underscores.  When WORKDIR is long, as it often is, the resulting file name is quite long.  One way to fix this is to have cmd/go pass a -srcdir option to cmd/cgo, which will cause WORKDIRNAME to contain just the file name, which is all we really need anyhow.

**Comment by rsc** [comment]
The root cause here is #3358, which we have yet to fix.

Why is cgo putting WORKDIRNAME into the generated file name at all?

Also, cgo has no -srcdir option (that's a local Google modification we should upstream).

**Comment by ianlancetaylor** [comment]
cgo putting WORKDIRNAME into the generated file name predates the go tool, when apparently cgo files could live in a separate directory.  It was added in https://golang.org/cl/1734047 to fix #533.  Maybe we could just stop doing that now.
