### ISSUE TITLE
encoding/json: Go's json decoder should support '*' spill over

### ISSUE THREAD

**Issue by liquidgecka** [golang/go#17079]
If the process decoding JSON wants to detect unsupported fields its very difficult. Either the json has to be decoded into a map[string]json.RawMessage then parse out each field into sub object, etc. But this could be codified into the decoder very easily. For example I would love to see this work:

What I would love is to be able to write this as code:

```go
type Object struct {
    Size int64 `json:"size"`
    Name string`json:"name"`
    Misc map[string]interface{} `json:"*"` 
}

func ParseObject() error {
    input := []byte(`{
        "size": 1,
        "name": "user_name",
        "unsupported_field": 10
    }`)

    obj := new(Object)
    if err := json.Unmarshal(input, obj); err != nil {
       return err
    }
    if len(obj.Misc) != 0 {
        return fmt.Errorf("Unsupported fields: %s", MakeKeysAList(obj.Misc))
    }

    return nil
}
```

In order to work `json:"*"` should only be used on a map[string]interface{} or a map[string]json.RawMessage. That is the one oddity to this that I can see outright.

**Comment by cespare** [comment]
Possibly a duplicate of #6213; see also some relevant discussion in #15314.

**Comment by liquidgecka** [comment]
Ahh yea sure enough! That looks like exactly what I am suggesting.. I will close this out. =)

Thanks! I didn't see that in my initial searches.
