### ISSUE TITLE
cmd/go: test -i and -o options together don't work as expected

### ISSUE THREAD

**Issue by aaronlehmann** [golang/go#17078]
### What version of Go are you using (`go version`)?

`go version go1.7 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/aaronl/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

I tried to run `go test` with both the `-i` and `-o` flags. The help output implies this combination is supported:

```
           -i
               Install packages that are dependencies of the test.
               Do not run the test.

           -o file
               Compile the test binary to the named file.
               The test still runs (unless -c or -i is specified).
```

```
$ go test
PASS
ok     	fmt    	0.070s
$ go test -i -o testbinary
$ ./testbinary
-bash: ./testbinary: No such file or directory
```

### What did you expect to see?

I expected `go test -i -o testbinary` to create a `testbinary` executable, and also install the package's dependencies.

### What did you see instead?

No executable created.

**Comment by 0xmohit** [comment]
This appears to be more of a documentation issue.  You'd need to specify `-c`, i.e. `go test -c -i -o testbinary`:

```
        -c
                Compile the test binary to pkg.test but do not run it
                (where pkg is the last element of the package's import path).
                The file name can be changed with the -o flag.
```

Perhaps, `-o` should state that it _renames_ the compiled binary to the named file instead of suggesting that it compiles.

**Comment by robpike** [comment]
I agree this is a documentation issue. The code is working as expected.

**Comment by rsc** [comment]
I don't believe the code is working as expected. The docs spell out the behavior of -o quite clearly, and the code doesn't do what the docs say. It is trivial to make 'go test -i -o x.test' work as documented, and harder to document the current behavior clearly. I'll send a CL for the code.
