### ISSUE TITLE
x/mobile: passing `error` into a callback crashes the library init

### ISSUE THREAD

**Issue by karalabe** [golang/go#17073]
When a method returns an error type, gomobile will internally convert that into a Java exception Android side. Of course, converting errors into exceptions would mean that an `error` cannot be passed to a callback method (implemented in Java) since it's not actually a real type, rather a special case.

However doing exactly this will cause gomobile to happily build the archive without reporting an error. This will result in the library crashing the android application when it's first accessed. Since errors are handled in a special way I can fully accept that they cannot be passed to functions as an argument, however we should probably abort compilation in that case and bail out with an error.

e.g. the below interface will build and crash upon library load

```go
type I interface {
	OnError(err error)
}
```

The error is something like this:

```
JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.NoSuchMethodError: no non-static method "Lorg/ethereum/geth/FilterLogsHandler;.onError(Lgo/error;)V"
```

**Comment by eliasnaur** [comment]
Thank you. Is the type declaration enough to crash the program? If not, please provide the complete code and I'll take a look.

**Comment by karalabe** [comment]
It is enough. I've added the following code to the end of `bind/testpkg/testpkg.go`:

```go
type ErrorCrasher interface {
	OnError(err error)
}
```

And ran the `TestJavaSeqTest` test inside `bind/java`, which fails with

```
go.SeqTest > testAdd[Nexus 5X - 6.0.1] FAILED 
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details
Tests on Nexus 5X - 6.0.1 failed: Instrumentation run failed due to 'Native crash'
```
