### ISSUE TITLE
Keep a trace of body in request for http.Request

### ISSUE THREAD

**Issue by LeaklessGfy** [golang/go#17088]
### What version of Go are you using (`go version`)?
go1.6.2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/keleyroot/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

(ubuntu 16.04)

### What did you do?
I'm am working on a simple API that make HTTP request. 
When a user enter this command : "http make", an http POST request with parameters is send to the host he specified. (classic)

Then I want that when the user type : "http info" he got the info of the request he made (url, method, header, *body*)

So everything works when I do these :
```go
func showRequestHeaders(r *http.Request) {
	fmt.Println(r.Header)
}
```

```go
func showResponseStatus(r *http.Response) {
	fmt.Println(r.Status)
}
```

```go
func showResponseHeaders(r *http.Response) {
	fmt.Println(r.Header)
}
```

```go
func showResponseRequest(r *http.Response) {
	fmt.Println(r.Request) //Here r.Request does not contain the body
}
```

But when I'm trying to do :
```go
func showRequestBody(r *http.Request) {
	fmt.Println(r)
	fmt.Println(r.Body)
}
```

Nothing is in the body AFTER the request is sent. I try to add `r.ParseForm()` but not helping ...
I also try to keep a copy of http.Request like that : m.Request = *req (req is what I get from `http.NewRequest` and the * is to make a copy and not storing the pointer.) And same with the copy (and here I really don't know why) the map that contains the body disapear after the `client.Do`

### What did you expect to see?
I except to keep a trace of the request body after it's sent.

### What did you see instead?
A "nil" or empty map (try Body, Form, PostForm and all of them are empty or nil)

Thank you for your time. Maybe I'm doing something wrong and I'm really sorry if it's the case. Thanks again.

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

**Comment by rdp** [comment]
See http://stackoverflow.com/questions/39473493/golang-keep-a-trace-of-request-body-inside-http-request
