### ISSUE TITLE
gzip seek

### ISSUE THREAD

**Issue by thimoonxy** [golang/go#17087]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What did you do?
I just want to code a log analyse tool. Since log files are huge , it's not possible to decompress to plain text and analyse .

### What did you expect to see?
I want to locate/seek to the position as os.open does.

### What did you see instead?
Since gzip has no seek function , I tried using seek func on os.open or say io.reader object, and send to gzip.newreader.  But when I tried to bufio.readbyte, it raised  panic runtime error: invalid memory address or nil pointer dereference.

**Comment by quentinmit** [comment]
gzip has no Seek function because the file format simply does not allow it. The only way to find byte N is to decompress and discard N-1 bytes.

If you want to easily do that in go, I suggest `io.Copy(ioutil.Discard, io.LimitedReader{r, n-1})`

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
