### ISSUE TITLE
Improvements for Go and IDE

### ISSUE THREAD

**Issue by zashibis** [golang/go#17098]
### What version of Go are you using (`go version`)?
I don't use Go

### What operating system and processor architecture are you using (`go env`)?
I don't use Go

### What did you do?
I thought a lot about programming languages.

### What did you expect to see?
Something like my presentation:
https://www.youtube.com/watch?v=aQHtIouaYzA
I'm open to discus it.

### What did you see instead?
Typical source code.

**Comment by bogem** [comment]
I can't understand what do you want.

**Comment by ianlancetaylor** [comment]
This isn't an issue for which we can sensibly take action, so I am going to close this.  This would be better discussed on a forum, not the issue tracker.  Please see https://golang.org/wiki/Questions .  Thanks.
