### ISSUE TITLE
net: cgoLookupAddrPTR returns single PTR regardless of number of PTR records

### ISSUE THREAD

**Issue by DominoTree** [golang/go#17093]
I've looked around at this and I'm pretty sure this is a bug with how the Cgo implementation gets PTR records using `getnameinfo` versus the native Go implementation.

### What version of Go are you using (`go version`)?
`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nxp6336/Projects/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hr/sptqjvgs6g9580rch5z5c81c0000gn/T/go-build396826714=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?
`net.LookupAddr("138.12.4.174")` or any other IP that has multiple PTR records

### What did you expect to see?
Multiple hostnames returned

### What did you see instead?
Only one hostname returned when using Cgo.  By setting `CGO_ENABLED=0`, the native Go implementation is used instead, and multiple PTR records are returned as expected.

**Comment by ianlancetaylor** [comment]
I'm not sure what to do about this.  The cgo code does a `PTR` lookup by calling the C function `getnameinfo`, which is the usual way to the name corresponding to an IP address.  `getnameinfo` only returns a single answer.  Is there a standard C interface that returns multiple `PTR` records?

**Comment by DominoTree** [comment]
Just to add some more thoughts here - as an end-user, the frustrating part for me wasn't really the ability to get multiple records.  What frustrated me was the fact that the documentation states that I should receive multiple records for this call, and the default behavior will only return one.

`LookupAddr performs a reverse lookup for the given address, returning a list of names mapping to that address.`

The other really fun part of this is that (at least) BIND9 will return record results for a query in a random order.  This means that if LookupAddr only returns one name, every time you query a single IP with multiple PTRs, you'll get a different result.

**Comment by bradfitz** [comment]
At minimum we could document the situation I suppose.

**Comment by rsc** [comment]
@bradfitz, it looks to me like we should document LookupAddr with something like

	// LookupAddr performs a reverse lookup for the given address, returning a list
	// of names mapping to that address.
	//
	// When using the host C library resolver, at most one result will be returned.
	// To bypass the host resolver, use a custom Resolver. 
	func LookupAddr(addr string) (names []string, err error) {

but that requires actually making (*Resolver).LookupAddr respect PreferGo, which it does not today. I filed #17532 for that.
