### ISSUE TITLE
compress/gzip produces incomplete file for Go 1.7+, Go 1.6.3 not affected

### ISSUE THREAD

**Issue by spirilis** [golang/go#17090]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7, 1.7.1

### What operating system and processor architecture are you using (`go env`)?
 GOARCH="amd64"
 GOBIN=""
 GOEXE=""
 GOHOSTARCH="amd64"
 GOHOSTOS="linux"
 GOOS="linux"
 GOPATH="/root/gowork"
 GORACE=""
 GOROOT="/usr/local/go"
 GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
 GO15VENDOREXPERIMENT="1"
 CC="gcc"
 GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
 CXX="g++"
 CGO_ENABLED="1"

### What did you do?
I wrote an application which can optionally stream gzipped Mysqldump files into a running mysql command for the purpose of restoring & converting old database data into a new format for an internal company application.  When mysql tables were mysteriously going missing, I started investigating further, and discovered that my gzip.NewReader() reader was aborting early.

I have written a test harness which illustrates this problem against the current "go1.7.1.linux-amd64.tar.gz" as a test dataset.

Test golang program (provides main()): https://play.golang.org/p/MdAVgNBay3

Test file: https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz

SHA256 of test file:
 [root@toybox local]# sha256sum go1.7.1.linux-amd64.tar.gz
 43ad621c9b014cde8db17393dc108378d37bc853aa351a6c74bf6432c1bbd182  go1.7.1.linux-amd64.tar.gz

Using GNU gunzip utility:
 [root@toybox local]# gunzip --version
 gunzip (gzip) 1.5

The gunzipped file looks as such:
 [root@toybox local]# gunzip -c go1.7.1.linux-amd64.tar.gz > go171_good.tar
 [root@toybox local]# ls -l go171_good.tar
 -rw-r--r-- 1 root root 248978432 Sep 13 10:36 go171_good.tar
 [root@toybox local]# sha256sum go171_good.tar
 5c6ecdbb8e9bfc166a17f76ff93ef909e233bbfd75f61e018a7e691f15600841  go171_good.tar

Using the aforementioned Golang utility, which I called "gogunzt1", when built using Go 1.6.3 (linux-amd64):
 [root@toybox local]# gogunzt1 --gzin go1.7.1.linux-amd64.tar.gz --output go171_gotest1.tar
 2016/09/13 10:37:35 Total bytes written: 248978432
 [root@toybox local]# ls -l go171_gotest1.tar
 -rw-r--r-- 1 root root 248978432 Sep 13 10:37 go171_gotest1.tar
 [root@toybox local]# sha256sum go171_gotest1.tar
 5c6ecdbb8e9bfc166a17f76ff93ef909e233bbfd75f61e018a7e691f15600841  go171_gotest1.tar

Using the same Golang utility, but built using Go 1.7.1 (linux-amd64):
 [root@toybox local]# gogunzt1 --gzin go1.7.1.linux-amd64.tar.gz --output go171_gotest2.tar
 2016/09/13 10:38:38 Total bytes written: 248971264
 [root@toybox local]# ls -l go171_gotest2.tar
 -rw-r--r-- 1 root root 248971264 Sep 13 10:38 go171_gotest2.tar
 [root@toybox local]# sha256sum go171_gotest2.tar
 82d124705de008af2d03c5524b653d12b4054e746bcd743a6e1cbb772f985e14  go171_gotest2.tar

Obviously an issue there, the Go 1.7.1 built utility was 7168 bytes short.

As a quick check, I tried using dd to trim the go 1.6.3-built test output (go171_gotest1.tar) by 7168 bytes, storing it into "go171_gotest3.tar" and comparing the SHA256:

 [root@toybox local]# dd if=go171_gotest1.tar of=go171_gotest3.tar bs=1 count=248971264
 248971264+0 records in
 248971264+0 records out
 248971264 bytes (249 MB) copied, 211.809 s, 1.2 MB/s
 [root@toybox local]# sha256sum go171_gotest3.tar
 82d124705de008af2d03c5524b653d12b4054e746bcd743a6e1cbb772f985e14  go171_gotest3.tar

The SHA256 sum for go171_gotest3.tar and go171_gotest2.tar match, which tells me that Go 1.7.1's compress/gzip implementation is faithfully decompressing the data, but just seems to be stopping short of decompressing all the data.

**Comment by quentinmit** [comment]
WAI. When you get an error from Read (on line 52) you need to still process the data in buf before you return. Go <1.7 used to delay the io.EOF until the next call to Read, but now Go 1.7 returns io.EOF and data in the same call. (This was always the case, but many of the Readers in the standard library used to not do it, so buggy code like this is out in the wild.)

**Comment by bradfitz** [comment]
Yup. You also ignore the error on line 53.

**Comment by spirilis** [comment]
I gotcha.  So I have to check len and process as necessary, THEN check if err is io.EOF before assuming it's done.

**Comment by quentinmit** [comment]
Yes, that's correct. That's how Read works for any Reader.
