### ISSUE TITLE
syscall: exec_linux.go not using cross architecture safe SYS_SETGROUPS

### ISSUE THREAD

**Issue by celledge** [golang/go#17092]
### What version of Go are you using (`go version`)?

go 1.7.1
### What operating system and processor architecture are you using (`go env`)?

GOOS=linux
GOARCH=arm
### What did you do?

groups = []uint32{20, 21, 22}
cmd.SysProcAttr.Credential = &syscall.Credential{Groups: groups}
cmd.Run()

Run strace on the process:
strace -e trace=setgroups -e trace=setgroups32 -f {executable}
### What did you expect to see?

setgroups32(3, [20, 21, 22])
### What did you see instead?

setgroups(3, [20, 0, 21])
### Source of problem and possible fix

It appears that syscall/linux_exec.go line 217, the RawSyscall is using SYS_SETGROUPS which on linux/arm is the 16bit GID system call. Since golang always uses 32bit GIDs, this fails. I switched this statement to SYS_SETGROUPS32, and it worked fine on my linux/arm system.

Perhaps this RawSyscall should be replaced with syscall.setgroups so that the correct architecture dependent system call is used.

Please note that this is also true for the SYS_SETUID and SYS_SETGID syscalls just below this line as well. Those statements will operate correctly, unless a UID or GID >= 2^16 is used. In which case it will truncate the integer and use the wrong ID instead of giving an error. However, I do not see an architecture dependent function already implemented to replace those.

**Comment by ianlancetaylor** [comment]
CC @LK4D4

**Comment by LK4D4** [comment]
@ianlancetaylor This code was there before me :/ Looks pretty bad and I don't about policy in `forkAndExecInChild` - if it's possible to call functions instead of RawSyscall there. I hope there won't hack as with s390x SYS_CLONE :)

**Comment by ianlancetaylor** [comment]
@LK4D4 Oh, sorry, I just assumed it was your code.

The child process in `forkAndExecInChild` can call any function, as long as it is nosplit and does not allocate any memory.

**Comment by LK4D4** [comment]
Just to be sure, here is function for arm:
https://github.com/golang/go/blob/master/src/syscall/zsyscall_linux_arm.go#L1263
Also, there are no functions for `setuid` and `setgid`. They need to be created in something like `exec_linux_arm.go` :(

**Comment by celledge** [comment]
I went over the patch at https://golang.org/cl/31458
It does fix the SYS_SETGROUPS issue, but it doesn't address the SYS_SETUID and SYS_SETGID 16bit vs 32bit potential issue that I mentioned.
