### ISSUE TITLE
Possible bug in io.TeeReader or json.Decoder

### ISSUE THREAD

**Issue by kshvakov** [golang/go#17095]
### What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64
go version go1.6.3 linux/amd64
go version go1.5.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kshvakov/gopath"
GORACE=""
GOROOT="/home/kshvakov/go"
GOTOOLDIR="/home/kshvakov/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build670233841=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
I'm using `io.TeeReader` for reading data from "reader" to "json.Decode" and write data for verification hash sum. It seems that sometimes json decode do not read last `\n`

https://play.golang.org/p/VsJGHZS6vy

### What did you expect to see?

correctly working

### What did you see instead?
```
 HMAC verification failed (bug: 4240)
```

**Comment by nuss-justin** [comment]
The JSON decoder works correctly. There is no need for it to scan past the object it decodes. If you want to the reader to be drained you can use io.Copy to copy the rest (if any) to ioutil.Discard. See https://play.golang.org/p/PSWUR_wEFK

**Comment by kshvakov** [comment]
Ok. But this means that I can use an invalid json

Ex:

```go 
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type test struct {
	ID   int
	Desc string
}

func main() {

	var buffer bytes.Buffer

	if err := json.NewEncoder(&buffer).Encode(&test{1, "Hello"}); err != nil {

		panic(err)
	}

	buffer.WriteString("\n Invalid json")

	var response test

	if err := json.NewDecoder(&buffer).Decode(&response); err != nil {

		panic(err)
	}

	fmt.Printf("%#v\n", response)
}


```

**Comment by bradfitz** [comment]
This is a feature.

You can use one json Decoder to decode multiple values in a row.

Your Decoder will fail on its next Decode call.
