### ISSUE TITLE
testcert.go contains private key that gets into go binary

### ISSUE THREAD

**Issue by saswatp** [golang/go#17103]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="-----"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

Run the command 
strings <go_binary> | sed -n '/-----BEGIN/,/-----END/p' 

If a program is using net/http library (package internal), it will contain a private key and certificate.
This is perceived as a security issue in the binary. 

The key/certificate is coming from https://github.com/golang/go/blob/master/src/net/http/internal/testcert.go

So, the bug is 
- Why is a private key / cert part of the binary ? (main issue)
- Why is test code getting into binary . (Side issue)

Additionally, Is there a way to avoid the issue and not use package internal , so that bug is avoided.
@adg 
@bradfitz 

### What did you expect to see?
No keys in the binary. 

### What did you see instead?
Private / Key Cert in binary.

**Comment by bradfitz** [comment]
The key is only used by `httptest.Server`. Your package main binary is apparently depending on httptest, and somehow using httptest.Server. You can verify with `go list -json your/package/main/path`

In Go 1.6, methods aren't stripped by the linker, so any reference to httptest.Server in your program will cause that key to be included.

In Go 1.7, that symbol with the private key will be stripped if you never call httptest.Server.StartTLS.

I verified this is all true and reproduced this with Go 1.6 and Go 1.7, verifying with `go tool nm` on the 6 binaries with different combinations of importing httptest.
