### ISSUE TITLE
fmt.Fscanf: "  \n  a  %d" can't match "  \n  a  1"

### ISSUE THREAD

**Issue by fu607666** [golang/go#17115]
version 1.7
GOARCH=amd64
GOOS=linux

---

I was reading go/src/fmt/scan.go and found a issue:

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	var i int
	s := strings.NewReader("  \n  a  1")
	fmt.Fscanf(s, "  \n  a  %d", &i)
	fmt.Println(i) // want 1, but 0

	s.Reset("  \na  1")
	fmt.Fscanf(s, "  \n  a  %d", &i)
	fmt.Println(i) // want 1, is 1
}
```
The bug is about at go/src/fmt/scan.go line 1124, not handled the space after \n.

**Comment by bogem** [comment]
Fscanf returns an error. Maybe error can say something

**Comment by fu607666** [comment]
err : input does not match format

but  " \n a 1" is matched " \n a %d" in literally.

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions
