### ISSUE TITLE
io: Add SectionWriter type for parity with SectionReader

### ISSUE THREAD

**Issue by jasdel** [golang/go#17114]
It would be helpful to have an io.SectionWriter for writing chunks to a io.WriterAt in an concurrent environment. I think a starting point would be to define the io.SectionWriter in a similar way to io.SectionReader taking advantage of the backing type's io.WriterAt implementation.

```
type SectionWriter
    func NewSectionWriter(w WriterAt, off int64, n int64) *SectionWriter
    func (s *SectionWriter) Write(p []byte) (n int, err error)
    func (s *SectionWriter) WriteAt(p []byte, off int64) (n int, err error)
    func (s *SectionWriter) Seek(offset int64, whence int) (int64, error)
    func (s *SectionWriter) Size() int64
```

I'm I didn't see any pending issues in github.com/golang/go on this, so I'm looking to create one. Several years ago there was [brief discussion](https://groups.google.com/d/topic/golang-nuts/ALKKuVPffyk/discussion) on the type, but It doesn't look like it went anywhere.

I'm be glad to provide an implementation for this.

**Comment by bradfitz** [comment]
Do you have an implementation already?

**Comment by jasdel** [comment]
Not yet, posted this issue as i started to work on it.

**Comment by bradfitz** [comment]
Per https://golang.org/doc/faq#x_in_std , most things should live outside of the standard library, unless many people would benefit from it, and/or callers existing in the standard library already.

Are either of those true?

The fact that it doesn't exist yet seems to be a strike against it.

Symmetry alone is probably not enough of a reason.

**Comment by jasdel** [comment]
Both of these most likely are not true. I don't know of are any of the std lib using anything like a section writer. How many would benefit is probably somewhere between some and a few due to writing multiple sections of a file being a fairly limited use case. Symmetry with Section Reader is probably the strongest case in this situation.

Off hand the obvious use cases would be writing sections of a file concurrently from a download such as byte rage file from a network, or something similar to a torrent.

The code being written already or not I'm not sure has a big impact, but understand not wanting to have outstanding issues that potentially never get fulfilled.

**Comment by dsnet** [comment]
I've needed a `SectionWriter` only once or twice in the time that I've been writing Go. I've also only needed to use `SectionReader` about the same amount. They have use, but are probably not widely useful enough to be in the standard library. It wasn't particularly hard implementing `SectionWriter` myself, though.

Also, the argument for symmetry can go both ways. That is, it could be argued that we should remove `SectionReader` to keep it symmetrical. Compatibility agreement aside, I would actually vote to remove `SectionReader`.

**Comment by jasdel** [comment]
@dsnet out of curiosity in the `SectionWriter` you wrote, how did you handle a caller attempting to write beyond the section bound? I'm assuming returning `EOF` with n bytes written is least surprising result. Though it is uncommon for `io.Writer` to return EOF, but in this case I think it makes sense.

**Comment by dsnet** [comment]
I returned `io.ErrShortWrite`, maybe not the best error. Having Write return `EOF` is a little strange to me since `EOF` is explicitly documented in relation to Read.

**Comment by jasdel** [comment]
Good point, `ErrShortWrite` makes much more sense than `EOF`.

**Comment by jasdel** [comment]
Hi @bradfitz , @dsnet , curious if this issue should be closed. I agree the use case of this added functionality is very limited, and probably rarely needed. I've only had a one off need to use this functionality, and noticed the missing SectionReader/Writer parity.

**Comment by bradfitz** [comment]
Sure, we can close for now. We can revisit once there's an implementation and more data to say how often it'd be used.

**Comment by jasdel** [comment]
Thanks!
