### ISSUE TITLE
x/mobile: ios tag not added any more automatically

### ISSUE THREAD

**Issue by karalabe** [golang/go#17116]
I've tried to build a mobile package for ios, and was surprised to get strange compilation errors. It turned out that even though I specified `--target=ios`, the tags used during build was empty. After specifying explicitly `--tags=ios` too beside the target, compilation succeeded correctly. My guess is that some refactor broke this as I remember seeing commits in the code adding the `ios` tag.

**Comment by eliasnaur** [comment]
Can you provide with an example that breaks? Much has happened since this was reported and I believe the ios tag is passed in gomobile bind and gomobile build.

**Comment by changkun** [comment]
the ios tag has became part of GOOS. Since it behaves slightly different, I think this is outdated. Close.
