### ISSUE TITLE
reflect.Value.Elem is unaddressable for interfaces

### ISSUE THREAD

**Issue by dmage** [golang/go#17117]
### What version of Go are you using (`go version`)?
tip, go version devel +27eebba

### What did you do?
I tried to change the value inside interface{} variable.
```
i := interface{}("hello")
v := reflect.ValueOf(&i).Elem()
v.Elem().SetString("world")
fmt.Println(i)
```
https://play.golang.org/p/U8WaCBA4o4

### What did you expect to see?
"world" stored in i.

### What did you see instead?
Runtime error.

### Proposed change
```(diff)
diff --git a/src/reflect/all_test.go b/src/reflect/all_test.go
index 780799c..4bb408b 100644
--- a/src/reflect/all_test.go
+++ b/src/reflect/all_test.go
@@ -5752,3 +5752,10 @@ func BenchmarkNew(b *testing.B) {
 		New(v)
 	}
 }
+
+func TestInterfaceElemSet(t *testing.T) {
+	i := interface{}("hello")
+	v := ValueOf(&i).Elem()
+	v.Elem().SetString("world")
+	assert(t, i.(string), "world")
+}
diff --git a/src/reflect/value.go b/src/reflect/value.go
index e6b846e..0340d25 100644
--- a/src/reflect/value.go
+++ b/src/reflect/value.go
@@ -714,6 +714,9 @@ func (v Value) Elem() Value {
 		x := unpackEface(eface)
 		if x.flag != 0 {
 			x.flag |= v.flag & flagRO
+			if x.flag&flagIndir != 0 {
+				x.flag |= flagAddr
+			}
 		}
 		return x
 	case Ptr:
```

**Comment by ianlancetaylor** [comment]
That does not correspond to an operation permitted by the language.  In the language, a value stored in an interface variable is not addressable.  The interface variable is addressable, but not the value contained within.  It's also inconsistent: your code permits changing the value if it is something like a string, but not if it is something like a pointer.  We're not going to make this change.
