### ISSUE TITLE
net: resolv.conf rotate option captured but not used

### ISSUE THREAD

**Issue by dpiddy** [golang/go#17126]
The resolv.conf rotate option is [captured](https://github.com/golang/go/blob/3eb16c059d301bc7242461ac8480d95e433e0374/src/net/dnsconfig_unix.go#L113-L114) when reading config but is [not used](https://github.com/golang/go/blob/3eb16c059d301bc7242461ac8480d95e433e0374/src/net/dnsclient_unix.go#L191) by the Go stub resolver when querying.

Linux's resolv.conf(5) says:

```
rotate sets  RES_ROTATE in _res.options, which causes round-robin selection of name‐
       servers from among those listed.  This has the effect of spreading the  query
       load  among  all listed servers, rather than having all clients try the first
       listed server first every time.
```

cc @captncraig

**Comment by captncraig** [comment]
We noticed this caused an imbalance on the load our dns servers were handling. Would be really nice if the flag were honored.

**Comment by mdempsky** [comment]
Seems worth supporting to me.  Were either of you planning to prepare a CL for this?

**Comment by captncraig** [comment]
not me.

**Comment by dpiddy** [comment]
I can do it, sure.

**Comment by captncraig** [comment]
If I were implementing this, I would consider just incrementing an atomic int at the beginning of [tryOneName](https://github.com/golang/go/blob/3eb16c059d301bc7242461ac8480d95e433e0374/src/net/dnsclient_unix.go#L188) and using that as an offset for my iteration.
