### ISSUE TITLE
x/mobile: error when running 'gomobile init'

### ISSUE THREAD

**Issue by fanus** [golang/go#17120]
### What version of Go are you using (`go version`)?

`go version go1.7.1 linux/amd64`
### What operating system and processor architecture are you using (`go env`)?

go env:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/host/projects/golang-prototyping"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

echo $PATH:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/host/projects/golang-prototyping/bin`
### What did you do?

```
cd /host/projects/golang-prototyping
export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin
go get golang.org/x/mobile/cmd/gomobile
gomobile init
```

~10 minutes later I got the error message
### What did you expect to see?

No error message and then being able to run:
`gomobile build -target=android hello.go`
### What did you see instead?

I received this error message.
`gomobile: open /host/projects/golang-prototyping/pkg/gomobile/work-685604373/android-ndk-r12b/platforms/android-21/arch-arm64/usr/include/linux/netfilter/xt_connmark.h: file exists`
### Additional notes

I'm running this go version inside a Arch Linux Docker container. I installed go, go-tools, etc. (all dependencies) using pacman package manager. My host is Windows 10 64bit and my terminal is "Docker Quickstart Terminal" using VMware and not Hyper-V. Not sure if this is all relevant.

**Comment by eliasnaur** [comment]
Gomobile doesn't download the NDK anymore.
