### ISSUE TITLE
import order when import "C" in cause error

### ISSUE THREAD

**Issue by stgleb** [golang/go#17122]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.1
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gstepanov/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build148165501=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

I have a code snipped https://play.golang.org/p/hyTNhSJ-eI where i import python.h and use objects from there using C. 

But when using multiline import like code snippet https://play.golang.org/p/7Fo_k4qLT2 do.
build failed with

``could not determine kind of name for C.PyLong_FromLongLong``
``could not determine kind of name for C.PyObject``

Command used for buiild

go build -buildmode=c-shared -o bin/main.go.so main.go

Full version of code can be found at https://github.com/stgleb/py_to_go

It seems pretty weird  that way of import syntax affect in such way, i've spent a few hours to
figure out that issue was in simple import syntax.

**Comment by ianlancetaylor** [comment]
This is working as documented at https://golang.org/cmd/cgo.

**Comment by stgleb** [comment]
Thanks, i've missed that.
