### ISSUE TITLE
doc: clarify arguments of function called by ServeHTTP in Effective Go

### ISSUE THREAD

**Issue by StevenMaude** [golang/go#17128]
In the [Interfaces and Methods](https://golang.org/doc/effective_go.html#interface_methods) section of Effective Go, there are two mentions of `ServeHTTP` calling a function `f(c, req)` ([first occurrence](https://github.com/golang/go/blob/4466298df47fee61c31933e6fd5dde474dcfd2ad/doc/effective_go.html#L2412), [second occurrence](https://github.com/golang/go/blob/4466298df47fee61c31933e6fd5dde474dcfd2ad/doc/effective_go.html#L2450)).

Judging from how `ServeHTTP` is documented in the [Go source](https://github.com/golang/go/blob/4466298df47fee61c31933e6fd5dde474dcfd2ad/src/net/http/server.go#L1724-L1727), and given the actual call in the Effective Go `ServeHTTP` example is listed as `f(w, req)`, it possibly would be clearer as `f(w, req)`.

Arguably, you could also change the `req` to `r` to match the server.go source, but that's less of an issue as usage is at least consistent within the documentation section.

### What version of Go are you using (`go version`)?
1.7.1

**Comment by bradfitz** [comment]
Thanks. `c` is an ancient holdout from before Go 1.0 when the signature took an `*http.Conn`.

**Comment by vdemario** [comment]
I'd like to do this.

It's small enough that it should be a good issue to do my first contribution and understand the guidelines. BTW, the contribution guidelines talk about _claiming an issue_, it this comment enough or is there more to it?

**Comment by bradfitz** [comment]
Go for it.

**Comment by vdemario** [comment]
https://go-review.googlesource.com/#/c/29311/
