### ISSUE TITLE
x/tools/cmd/godoc: link from filename to source code

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#17125]
Can for example `src`/`net`/`http`/client.go be made clickable so you can navigate more easily through the source code instead of changing the url in the urlbar manually? 
![image](https://cloud.githubusercontent.com/assets/863731/18552618/6d92b958-7b5d-11e6-920f-019b1e37ee3a.png)
godoc.org has a navigation menu and also links to the golang.org source code but once you are in the src file you have no navigation.

 I am asking this because when you learn Go you end up easely in src files using the golang.org search field to look up golang stuff, for example https://golang.org/search?q=request 

EDIT: One of the suggestions I can think of for the example https://golang.org/src/net/http/client.go

```
Source file src/net/http/client.go    Pakage name http <- https://golang.org/pkg/net/http/
- https://golang.org/src/net/http/
- https://golang.org/src/net/
- https://golang.org/src/
```

the left side we navigate the src files on the right side we have the general package link

**Comment by bradfitz** [comment]
Sounds fine.

**Comment by siadat** [comment]
The above CL makes net and http segments of

    src/net/http/client.go

clickable. E.g., if you click on the http segment you will go to the pkg/http. Is this what we are looking for here?

**Comment by bhcleek** [comment]
I can commit to doing this.

**Comment by gertcuykens** [comment]
@siadat yes what ever feels the most convenient. Take https://godoc.org/net/http#pkg-files navigation just as a example. The way to implement is open to any suggestions or methods.

**Comment by gertcuykens** [comment]
Let me know the navigation scheme below makes sense to everybody for the following page
https://golang.org/src/net/http/client.go
```
Source file src/net/http/client.go    Pakage name http <- https://golang.org/pkg/net/http/
- https://golang.org/src/net/http/
- https://golang.org/src/net/
- https://golang.org/src/
```

So on the left side we navigate the src files on the right side we have the general pakage

**Comment by siadat** [comment]
Thanks @gertcuykens. I updated the CL.

## Before

![before-screenshot](https://cloud.githubusercontent.com/assets/364548/18601916/fd108790-7c7a-11e6-9b42-fd3a525bf8a5.png)

## After

![after-screenshot](https://cloud.githubusercontent.com/assets/364548/18601715/dda80d48-7c79-11e6-96a7-8db950575901.png)

The source file segments are clickable. In the second screenshot I am hovering on **http**.

Regarding the look of it, I used `<h2>` subtitle for the link to documentation because it was already available in the HTML template.

**Comment by gertcuykens** [comment]
Looks very nice :D thanks, PS how can I test it ?

**Comment by siadat** [comment]
Get the go tools

    go get golang.org/x/tools/cmd/...

Fetch and install the CL

    cd $GOPATH/src/golang.org/x/tools
    git fetch https://go.googlesource.com/tools refs/changes/79/29279/4 && git checkout FETCH_HEAD
    go install ./...

Run it!

    godoc -http=:6060

For any CL you can find the fetch command in the Download menu of CL in Gerrit.

**Comment by gertcuykens** [comment]
@siadat nailed it! This is waaaaay beter now to navigate trough source code and it even works wel on mobile too! Please put this in milestone Go1.8 instead of Go1.8Maybe

**Comment by siadat** [comment]
Latest screenshot (grey text for the last segment, similar to godoc.org):
![screenshot](https://cloud.githubusercontent.com/assets/364548/18643166/1bbbd736-7eb9-11e6-8678-8a9d45e3e340.png)
