### ISSUE TITLE
cmd/link: -buildmode=plugin fails on linux/arm64

### ISSUE THREAD

**Issue by crawshaw** [golang/go#17138]
At least on the builder, it tickles gold the wrong way:

```
/tmp/workdir/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld.gold: internal error in global, at ../../gold/aarch64.cc:4973
```

Odd, as the plugin mode mostly depends on linker configuration used by either c-shared or shared.

**Comment by mwhudson** [comment]
Do you know which version of gold is installed?

**Comment by mwhudson** [comment]
If I revert 569340ebafcd20c01227ed9cbeb5ccd29c52f2bc it fails with:

```
##### ../misc/cgo/testplugin
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw(0x520f77, 0x1e)
```

do you know what's going on there?

**Comment by crawshaw** [comment]
Nope, I'd have to spend some time with an arm64 machine, and I don't think I'll get to it in 1.8. I'd rather just say we haven't implemented -buildmode=plugin there yet and deal with it in 1.9.

**Comment by quentinmit** [comment]
We haven't made a Go1.9 milestone yet, so I'll tag this 1.8Maybe with the expectation that it's likely going to get punted.

**Comment by cherrymui** [comment]
With CL https://go-review.googlesource.com/c/go/+/109917, testplugin passes locally. It still fails on the builder with an internal error in gold.

```
##### ../misc/cgo/testplugin
# host
/workdir/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld.gold: internal error in global, at ../../gold/aarch64.cc:4973
collect2: error: ld returned 1 exit status
```

Seems the gold linker on the builder is rather old:
```
$ gomote run $VM /usr/bin/gold --version
GNU gold (GNU Binutils for Debian 2.25) 1.11
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

On the machine where the test passes:
```
$ gold --version
GNU gold (GNU Binutils for Ubuntu 2.26.1) 1.11
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

I wonder, could we update gold on the builder, and require a newer gold for using plugin on linux/arm64? cc @bradfitz

**Comment by zhouguangyuan0718** [comment]
I'm sorry for bothering. It is unbelievable for me, I had used buildmode=plugin on linux-arm64 on our production environment for three years. I found it is not tested just now. 
Three years on, had gold been updated on the builder? And can we run the testcases on the builder now? 

Thanks.
