### ISSUE TITLE
The site at localhost:1234 can't be reached.

### ISSUE THREAD

**Issue by ace411** [golang/go#17136]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
Windows 10 32-Bit

### What did you do?
I created a Go Server. At least I think I did.

### What did you expect to see?
Output on a web page at localhost:1234

### What did you see instead?
An error message: the website at localhost:1234 cannot be reached.

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions
