### ISSUE TITLE
net/url: QueryEscape doesn't properly encode spaces

### ISSUE THREAD

**Issue by dalu** [golang/go#17142]
### What version of Go are you using (`go version`)?

go version go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/darko/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build727280122=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

source string:
`10000 Meters.G_o_D.+2-GAYnesis_Prollcheckers.zip`

encoded into:
`10000+Meters.G_o_D.%2B2-GAYnesis_Prollcheckers.zip`    

which, in a handler turns into (r.URL.Path):
`10000+Meters.G_o_D.+2-GAYnesis_Prollcheckers.zip`

QueryUnescaped from r.URL.Path:
`10000 Meters.G_o_D. 2-GAYnesis_Prollcheckers.zip` `<nil>`

### What did you expect to see?

encoded into:
`10000%20Meters.G_o_D.%2B2-GAYnesis_Prollcheckers.zip`

### What did you see instead?

encoded into:
`10000+Meters.G_o_D.%2B2-GAYnesis_Prollcheckers.zip`

https://play.golang.org/p/awvgBNydCi

**Comment by dalu** [comment]
I see there's issue #4013

Maybe it's working as intended but it's not working as it should in the real world.

Perhaps the issue should be named

"Provide URLEncode function"

What do you do when you have to output a filename as weird as this and put it into a `<a href=`?

**Comment by minux** [comment]
Working as intended. QueryEscape is to escape query string in the URL.

If you want to escape a path, use:

   url := url.URL{Path: name}
   url.String()
