### ISSUE TITLE
cmd/vet: accept space-separated tag list, like cmd/go

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#17148]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.7.1 linux/amd64
```

Now different go cmds handle tag list in different ways:

- `go build` , `go test` and `go vet` accepts space-separated tag list.
- `go tool vet` accepts comma-separated tag list.  `go tool vet -h` says:

```
  -tags string
    	comma-separated list of build tags to apply when parsing
```

If these cmds handle tag list in a consistent way, it will be easier for users to use them.

**Comment by quentinmit** [comment]
This probably means we need to accept both command and space separated lists to avoid breaking any existing callers.

**Comment by rsc** [comment]
go tool vet added its tag list much more recently than the others. I think we can change vet to take spaces too, but we're not going to change the go command proper to start taking commas.
