### ISSUE TITLE
cmd/go: unexpected exit codes for go tool ...

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#17145]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.7.1 linux/amd64
```

https://golang.org/cmd/vet/ says:

> Vet's exit code is 2 for erroneous invocation of the tool, 1 if a problem was reported, and 0 otherwise. 

The vet exit code is set by [setExit function](https://github.com/golang/go/blob/master/src/cmd/vet/main.go#L123). A check of the source code in `src/cmd/vet` shows that there is no invocation like `setExit(2)`. Should the doc be updated to reflect the code logic?

**Comment by robpike** [comment]
It's correct as is. It exits with code 2 if the arguments are incorrect, that is, if Usage is called.

**Comment by yaojingguo** [comment]
`go vet` behaves as the documentation describes. But `go tool vet` does not.

```
$ go tool vet -h
$ echo $?
1
```

**Comment by robpike** [comment]
The go tool subcommand mishandles error codes. It's not disastrous but the codes are odd.

```
% go tool asdf
go tool: no such tool "asdf"
% echo $?
3
% 
```

That one is due to an explicit setExitCode(3); it should be 2.

```% go vet -asdf
<errors>
% echo $?
2
% go tool vet -asdf
<same errors>
% echo $?
1
% 
```

One would expect the go tool vet command to exit with the same code as go vet. Also, as one expects, the vet binary run without the go tool exits with 2 in this case.

**Comment by robpike** [comment]
This error, the second one above,

```% go vet -asdf
<errors>
% echo $?
2
% go tool vet -asdf
<same errors>
% echo $?
1
% 
```

is not cleanly addressable because os.ProcessState does not tell you the failing exit code portably; in fact, the exit code is simply unix-specific. Might as well leave it alone; at least it's non-zero indicating command failure.

**Comment by yaojingguo** [comment]
If we leave it alone, I think that the related description in https://golang.org/cmd/vet/ should be updated.
