### ISSUE TITLE
doc: more detailed description of -tags option

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#17144]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.7.1 linux/amd64
```

The description [`-tags` option](https://golang.org/cmd/go/) is:

```
-tags 'tag list'
	a list of build tags to consider satisfied during the build.
	For more information about build tags, see the description of
	build constraints in the documentation for the go/build package.
```

`tag list` needs to be separated by spaces. And https://golang.org/pkg/go/build/ talks about using spaces or commas to separate tags. I think that it will be clearer if `a list of build tags` is changed to `a list of space-separated build tags`.

**Comment by quentinmit** [comment]
I'm going to close this as a dupe of #17148; resolving that will include updating the documentation to clarify what is accepted.
