### ISSUE TITLE
net/http/httptrace: redirections make it hard to use the hooks

### ISSUE THREAD

**Issue by rakyll** [golang/go#17152]
Consider the following program:

```
req, _ := http.NewRequest("GET", "https://google.com", nil)
trace := &httptrace.ClientTrace{
    DNSDone: func(dnsInfo httptrace.DNSDoneInfo) {
        fmt.Printf("DNS Info: %#v\n", dnsInfo)
    },
}
req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))
http.DefaultClient.Do(req)
```

https://google.com is redirected to https://www.google.com and making it harder to use the DNS hooks because DNSDoneInfo doesn't contain any information about the host it is trying to resolve.

It is also not documented anywhere that these hooks might be called more than once.

Should we think about a way to report the redirection or include enough details, so the user can determine for which actual request, the hooks are being invoked?

/cc @bradfitz

**Comment by bradfitz** [comment]
Instead of documenting something overly-vague like they can be called more than once, I'd rather say that it's a `Transport` (`RoundTrip`) tracing mechanism, rather than a `Client` (`Do`) tracing mechanism, and the lifetime is a single request so if you're using `Client`, you're responsible for your own tracing within the `CheckRedirect` hook.

/cc @tombergan for thoughts.

**Comment by rakyll** [comment]
I like the way you put it, and I will try to update the godoc representing more of the scope of the tracing. It would be nice to demonstrate a case with redirection to document the usage with `Client`, that will help us making the difference obvious.

The example I recently contributed does a Client.Do which might be misleading. We should, at least, modify it before we cut 1.8.

**Comment by bradfitz** [comment]
> The example I recently contributed does a Client.Do which might be misleading. We should, at least, modify it before we cut 1.8.

SGTM. And any other examples/docs until Client if so.

**Comment by rakyll** [comment]
I am going to close this bug given we published a blog post how to use the package. I don't think we should try to verbally explain the same points in the godoc. Warning about the ClientTrace is bound to RoundTripper and giving a link to the blog post might be better.

**Comment by rsc** [comment]
@rakyll, you said you were going to close this bug but didn't. The rationale sounds fine provided you add a link to the blog post from the httptrace package doc. I don't see the link there now. Thanks.
