### ISSUE TITLE
path/filepath: ensure Glob() returns in lexical order and comment about that

### ISSUE THREAD

**Issue by joesis** [golang/go#17153]
`glob()`'s comment mentioned the order.

**Comment by minux** [comment]
Why should we specify the order?

It's quite possible that we can speed Glob up by not
sorting the filenames.

If you want a specific ordering, you should sort the
result manually.

**Comment by joesis** [comment]
I thought the order was intentionally maintained per the comment of `glob()` (it's called only by `Glob`). The only other method in the same package that deals with multiple files, `filepath.Walk`, maintains lexical order too.

If the order is intentionally unspecified, adding a line of comment would be good to avoid callers from depending on the current implementation.

**Comment by dgryski** [comment]
I've had `Glob()` heavy code which profiles showed the call to `Sort()` is what was dominating the runtime.    (I switched to a large in-memory index to virtually eliminate the calls to `Glob()` for a significant performance win.)

**Comment by quentinmit** [comment]
I don't think we want to guarantee any particular order. I read `glob`'s comment as specifying the order in which it appends items to the argument, which is not at all guaranteed to be the order that `Glob` returns. I also don't think we need to, ahem, specify that it is unspecified in a comment. There are many things all over the standard library that have undocumented additional behavior. (See also the recent changes to the implementations of `Read` in standard library types.)
