### ISSUE TITLE
cmd/compile: binary.BigEndian.UintXX should compile to a load+bswap on amd64

### ISSUE THREAD

**Issue by rasky** [golang/go#17151]
Given the existing pattern-matching for `binary.LittleEndian.UintXX` functions, the functionality could be extended to support also `binary.BigEndian`, by doing a straight load followed by a `BSWAP` instruction.

**Comment by dsnet** [comment]
Possible duplicate of #14366.

**Comment by dsnet** [comment]
Related to #16832
