### ISSUE TITLE
plugin: symbol lookup fails if plugin not in current directory

### ISSUE THREAD

**Issue by paulsmith** [golang/go#17155]
go version devel +964639c Sat Sep 17 14:21:32 2016 +0000 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/paul"
GORACE=""
GOROOT="/go"
GOTOOLDIR="/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build779914587=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

If the name of the plugin given to plugin.Open is a path to a file not in the current directory, like "plugins/foo.so", symbol name lookup will fail with an error like:

```
plugin.Open: could not find symbol MyFunc: /home/paul/src/example/plugins/foo.so: undefined symbol: plugins/foo.MyFunc
```

The symbol to be looked up in the example should be `foo.MyFunc`, not `plugins/foo.MyFunc`.

**Comment by quentinmit** [comment]
Why is it looking at `plugins/foo.MyFunc` to begin with? The docs say that the package should be called "main"; is there something internal to plugin .so files where the "main" package is renamed to the filename instead?

**Comment by crawshaw** [comment]
Yes. Otherwise symbols would conflict between plugins and the host binary.

Unfortunately it's not complete. It needs to use the entire path to the package to avoid conflicts between plugins.
