### ISSUE TITLE
runtime: spurious cgo dynamic check failure on darwin/amd64

### ISSUE THREAD

**Issue by crawshaw** [golang/go#17160]
On darwin/amd64, several uses of ```C.free(unsafe.Pointer(cstr))``` in plugin/plugin_dlopen.go get caught incorrectly on the dynamic cgo check:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x40b85c0, 0xc42000c280)
	/Users/crawshaw/go/src/runtime/panic.go:496 +0x1a0
plugin._cgoCheckPointer0(0x4303550, 0x0, 0x0, 0x0, 0x1)
	plugin/_obj/_cgo_gotypes.go:41 +0x59
plugin.open(0x40cff89, 0x7, 0x0, 0x0, 0x0)
	/Users/crawshaw/go/src/plugin/plugin_dlopen.go:106 +0x828
plugin.Open(0x40cff89, 0xa, 0x403e78e, 0xc42000c208, 0xc42000c200)
	/Users/crawshaw/go/src/plugin/plugin.go:28 +0x35
main.main()
	/Users/crawshaw/go/misc/cgo/testplugin/src/host/host.go:24 +0x5c
```

Calling a C helper function, C.freestr(cstr), does not get caught.

I spent a while trying to isolate a test case, but no luck. Once I've mailed the darwin plugin CLs, replacing C.freestr with C.free shows the error consistently when running misc/cgo/testplugin.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
The usual false positive with the tests is passing a pointer to a field in a struct such that cgo does not recognize that you are passing just a pointer to a field, and the runtime examines the whole struct, not just the field, for Go pointers.

**Comment by crawshaw** [comment]
No struct fields here, just *C.char objects created either with C.CString or returned from C.realpath (which was created with malloc).

**Comment by ianlancetaylor** [comment]
I would need to see a test case.  I am not aware of any false positives such as you describe.

**Comment by crawshaw** [comment]
All I have is plugin/plugin_dlopen.go after the CL series ending in golang.org/cl/29393 minus the changes in golang.org/c/29392. My attempts to isolate it failed.

**Comment by crawshaw** [comment]
I believe I've found the problem, it's in the darwin plugin CL series not the cgo check. Working on a fix.

**Comment by crawshaw** [comment]
Patch set 3 of CL 29394 addresses this.

When I opened this bug I had written off dlopen being the cause because the stack trace pointed to the first C.free in the function. Of course that C.free was in a defer, so it happened after the dlopen. For some reason it took me a while to see that.
