### ISSUE TITLE
Some Binaries compiled with Go 1.7.1 now long run on Mac OS X 10.6.8 (Snow Leopard)

### ISSUE THREAD

**Issue by rbarbey** [golang/go#17169]
### What version of Go are you using (`go version`)?
`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```shell
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/robert/Development/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mq/1myb21g91m51qgcx40m4wz7c0000gn/T/go-build486584467=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
and on the target machine
```shell
Darwin elstar.fritz.box 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386
```

### What did you do?
I wrote a little web service using [Gizmo](https://github.com/NYTimes/gizmo/). I compile it on OS X 10.11.6 (x68_64) and let it run on OS X 10.6.8 (i386). With Go 1.6.x, there was no problem, after I upgraded to Go 1.7.1 I could still compile my service but no longer run it on OS X 10.6.8 (but can run it on OS X 10.11)

I reduced the code to a [minimal service](https://play.golang.org/p/Bw0LmLGwTh) which reproduces the problem. I tried to reproduce the problem without using Gizmo but to no avail yet. I'll update the issue once I find a "pure" Go solution since I think that the problem is not related to Gizmo specifically.

### What did you expect to see?
I expected that recompiling my Gizmo-based service using Go 1.7.1 would still run on OS X 10.6.8 despite #10403. I read through the release notes for Go 1.7 and did not find any hint that OS X 10.6.8 or any 32-bit OS X platform for that matter is no longer supported.

### What did you see instead?
When I try to start the executable, I get this
```shell
dyld: Symbol not found: _SecCertificateCopyNormalizedSubjectContent
  Referenced from: /Users/robert/./test
  Expected in: flat namespace

Trace/BPT trap
```

**Comment by bradfitz** [comment]
Sorry, we only support OS X 10.8 (Mountain Lion) and up.

This is documented at https://golang.org/dl/ and elsewhere.

**Comment by quentinmit** [comment]
See #9511 for where we dropped support for 10.6.
