### ISSUE TITLE
pkg/net/http/ - missing information about the need to empty the resp.Body, possible memory leak

### ISSUE THREAD

**Issue by Marmeladenbrot** [golang/go#17166]
Package: https://golang.org/pkg/net/http/

Stated in this link (http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/) and confirmed on the official #go-nuts IRC channel the behaviour for resp.Body.Close() changed

> The original implementation for resp.Body.Close() also reads and discards the remaining response body data. This ensured that the http connection could be reused for another request if the keepalive http connection behavior is enabled. The latest http client behavior is different. Now it's your responsibility to read and discard the remaining response data. If you don't do it the http connection might be closed instead of being reused. This little gotcha is supposed to be documented in Go 1.5.

But I can't find anything about this in the http docs which leads to wasted ressources if you have to open a new http connection for every request instead of reusing the old ones.

Also the memory leak when you have a "stopped after 10 redirects" where the resp is non-nil but the error is also non-nil, with the standard 

`if err != nil  {
 log.error(err)
return 
}
resp.Body.Close()`

you just leak memory every time this occurs.

`if err != nil  {
 log.error(err) 
if resp != nil {
		if resp != nil {
			_, _ = ioutil.ReadAll(resp.Body)
			defer resp.Body.Close()
}
return
}
`

would be needed here. This must also be in the documentation.

**Comment by bradfitz** [comment]
It's documented on Response.Body:
https://golang.org/pkg/net/http/#Response

```
        // The http Client and Transport guarantee that Body is always
        // non-nil, even on responses without a body or responses with
        // a zero-length body. It is the caller's responsibility to
        // close Body. The default HTTP client's Transport does not
        // attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
        // ("keep-alive") unless the Body is read to completion and is
        // closed.
```

The CheckRedirect thing is also documented:

https://golang.org/pkg/net/http/#Client
```
        // CheckRedirect specifies the policy for handling redirects.
        // If CheckRedirect is not nil, the client calls it before
        // following an HTTP redirect. The arguments req and via are
        // the upcoming request and the requests made already, oldest
        // first. If CheckRedirect returns an error, the Client's Get
        // method returns both the previous Response (with its Body
        // closed) and CheckRedirect's error (wrapped in a url.Error)
        // instead of issuing the Request req.
        // As a special case, if CheckRedirect returns ErrUseLastResponse,
        // then the most recent response is returned with its body
        // unclosed, along with a nil error.
```

I'm not sure there's anything more to do here.
