### ISSUE TITLE
os: Remove(x) doesn't return an error that passes os.IsExist() on Windows

### ISSUE THREAD

**Issue by akalin-keybase** [golang/go#17164]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7

### What operating system and processor architecture are you using (`go env`)?

Windows

### What did you do?

Example program:

https://play.golang.org/p/pd_mMUsR-c

### What did you expect to see?

This should print "is exist = true" on Windows, too.

### What did you see instead?

(Caveat: didn't run exactly this program, but a similar one.)

On Windows, an errno of 145 is returned, which corresponds to [ERROR_DIR_NOT_EMPTY](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx).

From https://golang.org/src/os/error_windows.go , it looks like this particular value isn't in `isExist`.

**Comment by bradfitz** [comment]
Thanks. Seems easy enough to fix.

/cc @alexbrainman
