### ISSUE TITLE
Struct to interface conversion slowness

### ISSUE THREAD

**Issue by stgleb** [golang/go#17171]
### What version of Go are you using (`go version`)?

1.7.1

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/stgleb/go"
GORACE=""
GOROOT="/usr/local/go"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build388208242=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

I run bechmark that consist of calling function with struct argument,
and second benchmark calls function with interface argument.

https://github.com/stgleb/method_set_test/blob/master/method_set_test.go

I wonder why struct to interface is so slow compare to struct as an argument.
On my computer it yields

BenchmarkStruct-4       2000000000           0.02 ns/op
BenchmarkInteface-4     2000000000           0.44 ns/op

So difference is pretty significant.

### What did you expect to see?

I thought that all type checks are made during compile time.
So there should not be such big difference as far I understand
interfaces and structs.

**Comment by slimsag** [comment]
Interfaces are effectively implemented as pointers, and that type check is done at runtime, the performance difference is normal.

**Comment by stgleb** [comment]
@slimsag Yeah, but if I set another interface that my struct doesnt implement i could not even compile the code, not just run.

**Comment by bradfitz** [comment]
Some background reading: http://research.swtch.com/interfaces

Let's move discussion to the mailing list, though. See https://golang.org/wiki/Questions

**Comment by randall77** [comment]
BTW, this is fixed on tip.  #15375
