### ISSUE TITLE
Proposal: Parameters in `main()` map to command-line parameters (Perl6)

### ISSUE THREAD

**Issue by Kroc** [golang/go#17178]
One very nice feature in Perl6 which greatly speeds up tool writing is that the handling of command-line parameters can be defined and managed simply through the parameters given on the `MAIN` function -- a brief example: https://perl6advent.wordpress.com/2010/12/02/day-2-interacting-with-the-command-line-with-main-subs/

This would of course require quite some spec-changing, so it could be considered for Go2.

**Comment by bradfitz** [comment]
We probably won't take every language's every feature in a hypothetical Go2.

Closing this, as there's no need to track it specifically.
