### ISSUE TITLE
net: dial tcp: lookup "domain": no such host, on Darwin

### ISSUE THREAD

**Issue by drgomesp** [golang/go#17172]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/drgomesp/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7m/gc_br8z53hgdck9bg42ktr900000gn/T/go-build951792739=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

Unfortunately, I can't share the code. The idea is simple: perform lots of concurrent requests on a loop until you get the error.

### What did you expect to see?

I expect to not see errors related to TCP or network.

### What did you see instead?

`dial tcp: lookup "example.com": no such host`

**Comment by ianlancetaylor** [comment]
We are going to need a test case.  This clearly doesn't happen normally.  If the idea is simple, can you write a simple test?

**Comment by bradfitz** [comment]
Macs have very low default fd limits. And we use cgo by  default on Darwin. (Which might change in 1.8)

This is almost certainly a fd exhaustion problem. The real question is why the error message sucks.

**Comment by bradfitz** [comment]
Related: #16345 (net: revisit unconditional use of cgo lookups for darwin), cc @dpiddy

**Comment by rsc** [comment]
It's pretty clear the error message came from the host C library saying there was no such host. I don't think we have control over that. Maybe #16345 will fix this but I'm not holding my breath.

Closing as dup of #16345 or else not enough information.
