### ISSUE TITLE
net: TestResolveIPAddr and TestLookupPort_Minimal fails

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#17175]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +35d22af Wed Sep 21 01:25:29 2016 +0000 windows/386

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\dev
set GORACE=
set GOROOT=c:\dev\go
set GOTOOLDIR=c:\dev\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\DOCUME~1\brainman\LOCALS~1\Temp\go-build716372902=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

### What did you do?
I run `go test -short net` command.

### What did you expect to see?
I expect command to PASS.

### What did you see instead?
```
--- FAIL: TestResolveIPAddr (0.00s)
        iprawsock_test.go:60: #6: lookup IPv6-ICMP: getprotobyname: The requested name is valid and was found in the database, but it does not have the correct associated data being resolved for.
--- FAIL: TestLookupPort_Minimal (0.00s)
        lookup_test.go:693: LookupPort("tcp", "ssh") = 0, lookup tcp/ssh: getaddrinfow: The specified class was not found.; want 22, error=nil
FAIL
FAIL    net     23.362s
```

Alex

**Comment by bradfitz** [comment]
Yet it works fine on our builders, so perhaps you can tell us what's different about your system? Like, what version of Windows do you have?

That said, this is a regression I introduced and I know where it is.

**Comment by alexbrainman** [comment]
> what version of Windows do you have?

```
C:\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows XP Professional
OS Version:                5.1.2600 Service Pack 3 Build 2600
```

But all broken tests are network related. I don't know what to print for these.

Alex
