### ISSUE TITLE
doc: misaligned text for covariant result types section of FAQ

### ISSUE THREAD

**Issue by StevenMaude** [golang/go#17170]
### What version of Go are you using (`go version`)?
1.7.1

### What did you expect to see?
A body text layout as for the rest of the FAQ, for instance in the "Why is my nil error value not equal to nil?" section:

![correct-layout](https://cloud.githubusercontent.com/assets/3818079/18688687/5b08bc1e-7f7d-11e6-8adc-0d842c8ad2ab.png)

### What did you see instead?
Text that's to the left and right of what's considered the text margins for the FAQ body:

![covariant-types-layout](https://cloud.githubusercontent.com/assets/3818079/18688716/723b63a0-7f7d-11e6-93bb-fa283eef7300.png)

### Fix
The inconsistent use of `<p>` tags is the cause of the difference; see [the covariant return section](https://github.com/golang/go/blob/master/doc/go_faq.html#L890-L915) compared with the [nil error value section](https://github.com/golang/go/blob/master/doc/go_faq.html#L795-L818).

Changing the [relevant HTML](https://github.com/golang/go/blob/master/doc/go_faq.html#L890-L903) to:

```
<p>
Covariant result types would mean that an interface like
</p>

<pre>
type Copyable interface {
	Copy() interface{}
}
</pre>

<p>
would be satisfied by the method
</p>
```
fixes this:

![covariant-types-layout-fixed](https://cloud.githubusercontent.com/assets/3818079/18689366/a9128bee-7f80-11e6-89ba-6bf826352a62.png)

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/29442
