### ISSUE TITLE
Does go test will check the format of Example function ?

### ISSUE THREAD

**Issue by kevingo** [golang/go#17179]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.7 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kevingo/Documents/go_workspace"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mf/s60v2ry561x58q4yn66bd_88jv4r3c/T/go-build080744240=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
I have read the [https://blog.golang.org/examples](https://blog.golang.org/examples) document, it says the `go test` will captures data written to standard output and then compares the output against the example's "Output:" comment.

However, I change the "Output" or remove the "Output" from the Example function and execute `go test`, the Example function still passed.

I just wonder the `go test` will really check the Example function's format about the `Output` in comment ?

**Comment by bradfitz** [comment]
> I just wonder the go test will really check the Example function's format about the Output in comment ?

Yes, it does.

I would send source code to golang-nuts@ (see https://golang.org/wiki/Questions) to see what you're doing wrong.

**Comment by kevingo** [comment]
Thanks.
