### ISSUE TITLE
vet: fmt.Errorf("ordinary string") should be replaced by errors.New("ordinary string")

### ISSUE THREAD

**Issue by kevinburke** [golang/go#17173]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.1

### What operating system and processor architecture are you using (`go env`)?

All

### What did you do?

Vet this program: https://play.golang.org/p/krp8cxL_Lv

```go
package main

import "fmt"

func main() {
	err := fmt.Errorf("ordinary error")
	fmt.Printf("%#v\n", err)
}
```

### What did you expect to see?

`fmt.Errorf("an ordinary string")` - with no formatting arguments - should be replaced by `errors.New("an ordinary string")`, to avoid the overhead of calling `errors.New(Sprintf(...))`.

### What did you see instead?

No warning.

I'm happy to try to provide a patch here, if this is of interest.

**Comment by minux** [comment]
I'm not sure this is worth a vet check.

For packages that already imports fmt, there is nothing to gain
from using errors.New instead of fmt.Errorf (except slight
performance gain, but that shouldn't matter).

benchmark: https://play.golang.org/p/gXzQC2Ux4J

**Comment by dsnet** [comment]
`vet` is intended to check issues of correctness. The difference between using `fmt.Errorf` or `errors.New` here is clearly one of style since they are semantically equivalent. This should be an issue to file at [golang/lint](https://github.com/golang/lint/issues). I just checked and it doesn't seem like `golint` complains about this case.

I'm going to close this, but feel free to open the issue on the `lint` tracker.

**Comment by minux** [comment]
For the reason I've given, I don't even think it's appropriate for golint
to complain about: it's not a mistake if the package is already using
the fmt package.

**Comment by jimmyfrasche** [comment]
Perhaps you could try https://github.com/dominikh/go-simple

**Comment by dominikh** [comment]
It's probably not appropriate for gosimple, either, for the reason minux has given. One could of course check if fmt is being used for anything else already, but I don't think the slight benefit is worth the added complexity.

**Comment by jimmyfrasche** [comment]
Well thought I'd mention it as it was the most likely place it would find a home that I know of.

Personally I'd consider it a simplification even if it meant importing errors and fmt. A Printf/Errorf/Anythingf with just a string looks wrong.

Understandable if it's out of scope, though.

**Comment by kevinburke** [comment]
OK
