### ISSUE TITLE
x/text/unicode/bidi: Support changes to Bidi algorithm in Unicode 8.0

### ISSUE THREAD

**Issue by deepakjois** [golang/go#17189]
Here is a change to support updates to the Bidi algorithm in Unicode 8.0:
https://go-review.googlesource.com/c/29630/

@mpvl, I guess you are the right person to look at this?

I am the author of [luabidi]. I initially referred the Go implementation along with the reference Java implementation to write a line by line port of the reference code to Lua. However, both the Go version and the Java reference version do not support the changes to the algorithm made in Unicode 8.0.

[luabidi]:https://github.com/deepakjois/luabidi

I looked at the changes in the C reference implementation, and then modified my Lua version, as well as the [Java reference version](https://github.com/deepakjois/BidiReferenceJava). Finally, I decided to port the implementation to Go as well, just to get some more confidence. These changes have been tested pretty thoroughly both in Lua and in the (updated) Java reference implementation.

I had to make a minor change to the test file to get the tests to pass. But I believe, that change should have been there in the first place, if we go by the Java reference version.

**Comment by mpvl** [comment]
Hi Deepak,

Thanks for your contribution! That is very useful.  Will take a look now.

Note that the reference implementation is not yet hooked up to the API,
which is still on the TODO list. But if you intend to use it let me know.

Thanks,

Marcel

**Comment by deepakjois** [comment]
I read in the comments that it needs a Segmenter interface, which would be nice.

I have no immediate use for it, but I do plan to use this BiDi implementation sometime in the future for a text processing package I have plans to work on. No idea if and when that will happen. So I guess you can take your time.

**Comment by mpvl** [comment]
The CL was merged
