### ISSUE TITLE
doc: FAQ states copies of an interface results in copies of underlying data.

### ISSUE THREAD

**Issue by andyleap** [golang/go#17181]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7

### What operating system and processor architecture are you using (`go env`)?
nacl amd64p32 (go playground https://play.golang.org/p/BRJAYJccog)

### What did you do?
The FAQ states that "Copying an interface value makes a copy of the thing stored in the interface value. If the interface value holds a struct, copying the interface value makes a copy of the struct."  After having been told that this was wrong on the #go-nuts irc, I did some testing, and discovered that while a copy is made when the interface value is first "created", from then on further copies of the interface value retain the same underlying struct.

Example playground:
https://play.golang.org/p/s0A35084oY

To my mind this is an understandable change, as it is pretty much impossible to change the underlying struct without the use of the unsafe package.  The main issue is that this leaves the FAQ at https://golang.org/doc/faq#pass_by_value out of date, so I am requesting that the FAQ be updated.

### What did you expect to see?
Expected to see the "copies" of the interface value to have different "value" pointers.

### What did you see instead?
All copies of the interface value have the same "value" pointer, while obviously being copies due to different addresses.

**Comment by randall77** [comment]
I think you're confusing language semantics with language implementation.
The semantics are that interface assignment always makes a copy.
The implementation has optimizations where the copy can sometimes be elided.
The FAQ should describe the language semantics, not implementation details.

**Comment by andyleap** [comment]
Then the implementation is not following the language semantics...?  I'm not saying it even needs to be spelled out, but I think it's wrong for the FAQ to say "This happens" and the language to decide "Nope, cause I know better"

**Comment by randall77** [comment]
But that happens all the time in the implementation.  The spec says that every slice index operation has a bounds check.  But when the compiler can prove that the bounds check is guaranteed to succeed, it can be removed from the generated code.  When you write `f()`, the spec says it calls function `f`.  But the compiler can inline `f` and there's no actual call in the implementation.

The interface situation is similar.  interfaces are value types just like `int`, etc.  They are passed by value.  Each assignment is a copy.  The implementation implements interface assignment so that the pass-by-value semantics are preserved.  Whether it does that using an actual copy or some other mechanism that is indistinguishable from a copy is up to the implementation.

**Comment by ianlancetaylor** [comment]
@andyleap What do you suggest that the FAQ say instead?

I think it would be very misleading to say that copying an interface value does not copy the value stored in the interface, or that it sometimes copies the value stored in the interface.  That would give a person new to Go entirely the wrong idea.

**Comment by andyleap** [comment]
No where do I see "every slice index operation checks bounds at run time", there's plenty of wording around constant indices and such.  I'd rather have the FAQ not make a specific mention of how interface values copy rather then say something that is wrong...

**Comment by yaxinlx** [comment]
I would support @andyleap on this point.

First, I think there is no need to emphasize "interface assignment always makes a cop", for there is no differences between assignments of interfaces values and assignments of other values. It is all the same, all assignments in golang are copies.

Second, the assignments of interface values have nothing related to the values hold by the interface values. Assignments of interface values just copying the two fields of the interface values. There is no implementation optimizations at all.

**Comment by ianlancetaylor** [comment]
Since so far the Go team members find the FAQ to be OK, I think we need someone else to propose specific alternate wording.

**Comment by yaxinlx** [comment]
no alternate wording, I think it is just ok to just remove those lines from docs.
