### ISSUE TITLE
x/tools/playground: infinite loop in Edge and Firefox when embedded iframe styled with "display:none"

### ISSUE THREAD

**Issue by jdalton** [golang/go#17199]
The while loop in `fillOutLines` of [static/jquery-linedtextarea.js](https://play.golang.org/static/jquery-linedtextarea.js) is
causing [an infinite loop in Edge and Firefox browsers](https://github.com/hakimel/reveal.js/issues/1546)

The snippet is:

``` js
/*
 * Helper function to make sure the line numbers are always kept up to
 * the current system
 */
var fillOutLines = function(linesDiv, h, lineNo) {
  while (linesDiv.height() <= h) {
    linesDiv.append("<div>" + lineNo + "</div>");
    lineNo++;
  }
  return lineNo;
};
```

**Comment by bzbarsky** [comment]
I expect a simple test case this:

    <iframe style="display: none" src="https://play.golang.org/p/ZGmpjak_7O"></iframe>

or at least that certainly reproduces the problem in Firefox and I can't test Edge right this minute.  The loop never terminates, because `linesDiv.height()` keeps returning 0.

**Comment by bradfitz** [comment]
Can you give more details? It seems to work fine in Firefox for me.

What is different for you?

**Comment by jdalton** [comment]
A falsey guard in the `while` condition may avoid problems:
```js
var linesH;
while ((linesH=linesDiv.height()) && linesH <= h) {
```

**Comment by jdalton** [comment]
@bradfitz Try https://output.jsbin.com/zakenaf/1.

**Comment by bradfitz** [comment]
Do you have the wrong bug tracker? This is the Go bug tracker. If you have a jQuery bug, file against jQuery?

I'm not sure why you're linking to jsbin. How can I reproduce on https://play.golang.org/ with Firefox?

**Comment by jdalton** [comment]
If you view the source of the jsbin it is:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
<iframe style="display: none" src="https://play.golang.org/p/ZGmpjak_7O"></iframe>
</body>
</html>
```
The script on `play.golang.org`, this https://play.golang.org/static/jquery-linedtextarea.js, is causing an infinite loop when the iframe of `play.golang.org` is hidden because it's computing a height of `0`. The code lives on the golang playground.

**Comment by jdalton** [comment]
It appears to be custom code adapted from others for use on `play.golang.org` so there's no bug to report to jQuery. It's your site's bug.

**Comment by bradfitz** [comment]
Okay, now we're getting to something that sounds like a bug report. You have to provide complete background info and repro steps. Jumping to saying what the fix is is useless if you don't identify the problem.

**Comment by jdalton** [comment]
👏

**Comment by broady** [comment]
I thought I'd replied to this, but I guess it didn't come through.

This will go live once we release 1.8, in February. We can cherry-pick it to release branch 1.7 and deploy it if there's a good reason to do that.
