### ISSUE TITLE
build: provide a golang binary for ppc64le on the download page

### ISSUE THREAD

**Issue by laboger** [golang/go#17193]
This is a request to provide the binary for ppc64le on the golang.org/dl page.

**Comment by bradfitz** [comment]
We did s390x, so this seems reasonable.

And the ppc64le column on build.golang.org has been happy for quite some time.

Thoughts, anybody?

/cc @ianlancetaylor @dr2chase @broady @minux @randall77 @campoy @quentinmit

**Comment by ianlancetaylor** [comment]
SGTM (on the assumption that I personally would not have to do anything).

**Comment by minux** [comment]
SGTM. What about ppc64?

**Comment by bradfitz** [comment]
We don't have our ppc64 builders back yet. And we're not even sure ppc64 works at the moment. It seems irresponsible to distribute binaries for something without knowing if the port is stable.

**Comment by rsc** [comment]
We are getting basically no requests, not even from IBM, for ppc64. Doing ppc64le only is fine.

**Comment by bradfitz** [comment]
Related: #17018 to define the first-class ports.

**Comment by bradfitz** [comment]
Hey @jfrazelle, want to do the same thing you did for s390x cross-compiling for ppc64le?

In the meantime, I sent https://go-review.googlesource.com/33299

**Comment by bradfitz** [comment]
https://storage.googleapis.com/golang/go1.8beta1.linux-ppc64le.tar.gz is live. Thanks, @broady.

Closing this bug. But somebody should test that tarball and verify it works.
