### ISSUE TITLE
exec.Cmd.Dir does not set working directory properly for symlinks

### ISSUE THREAD

**Issue by nmiyake** [golang/go#17198]
### What version of Go are you using (`go version`)?
go version go1.7.1

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
Set the value of `exec.Cmd.Dir` to be a symlink and performed operations that depend on the path of the current working directory.

Minimal example:

```go
package main

import (
	"os"
	"io/ioutil"
	"path"
	"fmt"
	"os/exec"
)

func main() {
	tmpDir, _ := ioutil.TempDir("", "")
	defer os.RemoveAll(tmpDir)

	realDir := path.Join(tmpDir, "real")
	_ = os.MkdirAll(realDir, 0755)

	symlinkDir := path.Join(tmpDir, "symlink")
	_ = os.Symlink(realDir, symlinkDir)

	cmd := exec.Command("pwd")
	cmd.Dir = symlinkDir
	stdout, _ := cmd.Output()
	fmt.Printf("Expected: %v\nActual:   %v", symlinkDir, string(stdout))
}
```

Expanded example that demonstrates that running equivalent commands as a script produces expected behavior:

```
package main

import (
	"os"
	"io/ioutil"
	"path"
	"fmt"
	"os/exec"
)

func main() {
	tmpDir, _ := ioutil.TempDir("", "")
	defer os.RemoveAll(tmpDir)

	realDir := path.Join(tmpDir, "real")
	_ = os.MkdirAll(realDir, 0755)

	symlinkDir := path.Join(tmpDir, "symlink")
	_ = os.Symlink(realDir, symlinkDir)

	// run "pwd" after setting cmd.Dir
	cmd := exec.Command("pwd")
	cmd.Dir = symlinkDir
	stdout, _ := cmd.Output()
	fmt.Printf("Expected: %v\nActual:   %v", symlinkDir, string(stdout))

	// run "pwd" after running "cd"
	cmd = exec.Command(writeScript(tmpDir), symlinkDir)
	cmd.Dir = symlinkDir
	stdout, _ = cmd.Output()
	fmt.Printf("Expected: %v\nActual:   %v", symlinkDir, string(stdout))

	fmt.Println()
}

func writeScript(tmpDir string) string {
	f, _ := ioutil.TempFile(tmpDir, "")
	_, _ = f.WriteString(`#!/bin/bash
cd "$1"
pwd`)
	_ = f.Chmod(0755)
	_ = f.Close()
	return f.Name()
}
```

### What did you expect to see?
Expected that, if `exec.Cmd.Dir` is explicitly set to be a symlink, then the path operations would perform as it would if a Go program was executed from that directory as the working directory.

### What did you see instead?
The working directory of the new process is the resolved location of the symlink instead of the path of the symlink itself.

**Comment by minux** [comment]
Nothing to fix here. This is handled by the kernel. Bash actually goes out
of its way to pretend that you can chdir into a symbolic linked directory.

As a demo, this C program also exhibit the behavior:
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>
#include <assert.h>
int main() {
        const char *real = "/tmp/real", *sym = "/tmp/symlink";
        rmdir(real);
        unlink(sym);
        assert(mkdir(real, 0700) == 0);
        assert(symlink(real, sym) == 0);
        assert(chdir(sym) == 0);
        char buf[128];
        getcwd(buf, sizeof buf);
        printf("cwd = %s\n", buf);
        assert(execl("/bin/pwd", "pwd", NULL) == 0);
}

The output is:
cwd = /tmp/real
/tmp/real

**Comment by nmiyake** [comment]
Got it; makes sense. Thanks for investigating.
