### ISSUE TITLE
cgo: multiple definition of variables

### ISSUE THREAD

**Issue by mattn** [golang/go#17202]
### What version of Go are you using (`go version`)?

go version devel +e6158b3 Wed Sep 21 01:15:56 2016 +0000 windows/amd64

but occur this on linux too.

### What operating system and processor architecture are you using (`go env`)?

Windows 7 amd64

### What did you do?

```go
package main

/*
int Bar = 0;
*/
import "C"

func main() {
}

//export Foo
func Foo() {
	println("foo")
}
```

go build

### What did you expect to see?

succeeded to build

### What did you see instead?

`go build` occur error `multiple definition of 'Bar'`

When removing `Foo`

```go
package main

/*
int Bar = 0;
*/
import "C"

func main() {
}
```

This seems okay to me. And I notice we don't have way to export global variables on Windows. So won't work plugin on Windows.

**Comment by appleby** [comment]
**DISCLAIMER: I know nothing about cgo. I am a monkey blindly following repro steps.**

I am not able to repro this on my linux/amd64 system, neither with the version mentioned by OP (+e6158b3) nor with current tip (+3311275). I realize that OP is running Windows/amd64, but mentions that it occurs on linux, too. I do not have access to a Windows system to test there.

Here is output from my shell session for version +e6158b3. I get similar results for tip.

	[ma@march gobugs]? go version
	go version devel +e6158b3 Wed Sep 21 01:15:56 2016 +0000 linux/amd64
	[ma@march gobugs]? go env
	GOARCH="amd64"
	GOBIN=""
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/home/ma/opt/godev"
	GORACE=""
	GOROOT="/home/ma/src/repos/go"
	GOTOOLDIR="/home/ma/src/repos/go/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build094294721=/tmp/go-build -gno-record-gcc-switches"
	CXX="g++"
	CGO_ENABLED="1"
	[ma@march gobugs]? go build
	[ma@march gobugs]? ls
	cgo.go  gobugs
	[ma@march gobugs]? cat cgo.go
	package main

	/*
	int Bar = 0;
	*/
	import "C"

	func main() {
	}

	// Foo export
	func Foo() {
			println("foo")
	}

I also tried the same test setting CC=clang and CXX=clang++. I have no idea if that's relevant, but it didn't affect the result.

**Comment by minux** [comment]
This is working as intended.

If you use //export, then all C definitions must be in a separate C file
because the cgo preamble code is included in more than one C files.

https://golang.org/wiki/cgo#export-and-definition-in-preamble
