### ISSUE TITLE
cmd/vet: doesn't seem to like C.CBytes

### ISSUE THREAD

**Issue by asimshankar** [golang/go#17201]
### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

### What did you do?
Ran `go vet` on [`go/misc/cgo/test/issue14838.go`](https://github.com/golang/go/blob/53fd522c0db58f3bd75d85295f46bb06e8ab1a9b/misc/cgo/test/issue14838.go)
```
# Download 
curl https://raw.githubusercontent.com/golang/go/53fd522c0db58f3bd75d85295f46bb06e8ab1a9b/misc/cgo/test/issue14838.go \
  -o /tmp/x.go
# Run go vet
go vet /tmp/x.go
``` 

### What did you expect to see?
No output and exit status 0

### What did you see instead?
```
/tmp/x.go:31: possibly passing Go type with embedded pointer to C
exit status 1
```

**Comment by ianlancetaylor** [comment]
This got filed separately as #17563.  That one has a CL, so closing this one in favor of that one, even though this one was older.
