### ISSUE TITLE
vet: unrecognized printf flag for verb 's': '#'

### ISSUE THREAD

**Issue by dmportella** [golang/go#17208]
### What version of Go are you using (`go version`)?
> $ go version
> go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
> $ uname -a 
> Linux chester 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

I have a simple app that make use of the `#` token in my print formating when i run `Vet` it shows me as an error.

[Play Golang Link](https://play.golang.org/p/t9M1xA1kz_)

```
package main

import (
	"fmt"
)

type Point struct {
	X int
	Y int
	Z int
}

func main() {
	fmt.Printf("%#s", Point{1, 2, 3})
}
```
outputs:

> {%!s(int=1) %!s(int=2) %!s(int=3)}
> Program exited.

`$ go tool vet main.go`

outputs:
> $ go tool vet main.go
> main.go:14: unrecognized printf flag for verb 's': '#'

### What did you expect to see?

No `Vet` error on the usage of `#`.

### What did you see instead?

Vet tells me that it doesn't recognise `#` token.

**Comment by Ganners** [comment]
There is no `#` Printf verb for a string:

> 	# alternate format: add leading 0 for octal (%#o), 0x for hex (%#x);
	0X for hex (%#X); suppress 0x for %p (%#p);
	for %q, print a raw (backquoted) string if strconv.CanBackquote
	returns true;

What you are doing is therefore equivalent to `fmt.Printf("%s", Point{1, 2, 3})` as there are no flags as Vet points out.
