### ISSUE TITLE
Why are there no enums in Go?

### ISSUE THREAD

**Issue by raeesbhatti** [golang/go#17205]
### What version of Go are you using and what is your operating system and processor architecture?
`go version go1.7.1 darwin/amd64`

### What did you do?
Tried to declare enums in my package.

### What did you expect to see?
That there would be some mechanism to declare enums types.

### What did you see instead?
That there was no native way to declare enum types in Go lang instead I saw some weird hacks to make things work barely.

### What is your question?
Why is there no native way to declare enum types in Go lang, it is such a useful and convenient feature.
Here are [enums in HackLang](https://docs.hhvm.com/hack/enums/introduction) for example.

**Comment by raeesbhatti** [comment]
It would be really nice to have something like:
```go
enum HTTP struct {
    GET   string    "GET"
    POST            "POST"
    DELETE          "DELETE"
    PUT             "PUT"
}
```

**Comment by ALTree** [comment]
Hi! The Go project does not uses the github issue tracker for asking questions. In fact, there is no "What is you question?" header in the issue template. 

See the [Questions](https://github.com/golang/go/wiki/Questions) wiki page for a list of places where you could ask about enums.

**Comment by stemar94** [comment]
```go
type HTTP string

const (
    GET    = HTTP("GET")
    POST   = HTTP("POST")
    DELETE = HTTP("DELETE")
    PUT    = HTTP("PUT")
)
```

**Comment by raeesbhatti** [comment]
@stemar94 But you can't use this to verify type, e.g. in Type struct:
```go
type Request struct {
    Method    HTTP    `json:"method"`
}
```
It will not make sure that values are one of the `const`s. Any ideas?

**Comment by bradfitz** [comment]
Yeah, let's discuss this on the mailing list or Slack instead. See https://golang.org/wiki/Questions
