### ISSUE TITLE
syscall: TestUnshare fails with "operation not permitted", even with CONFIG_NET_NS=y

### ISSUE THREAD

**Issue by owlab-exp** [golang/go#17206]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

none
### What operating system and processor architecture are you using (`go env`)?

linux arm64
### What did you do?
# If possible, provide a recipe for reproducing the error.
# A complete runnable program is good.
# A link on play.golang.org is best.

I am building go1.7.1 on my arm64 machine, with go-linux-arm64-bootstrap.
I performed **all.bash** in src directory.
### What did you expect to see?

Completed build without any error.
### What did you see instead?

Build failed with the following error

```
...
--- FAIL: TestUnshare (0.01s)
    exec_linux_test.go:171: Cmd failed with err fork/exec /bin/cat: operation not permitted, output: 
FAIL
FAIL    syscall 0.960s
...
```

So, I changed the **exec_linux_test.go** from this,

```
165         cmd := exec.Command("cat", path)
166         cmd.SysProcAttr = &syscall.SysProcAttr{
167                 Unshareflags: syscall.CLONE_NEWNET,
168         }
169         out, err := cmd.CombinedOutput()
170         if err != nil {
171                 t.Fatalf("Cmd failed with err %v, output: %s", err, out)
172         }
173 
174         // Check there is only the local network interface
175         sout := strings.TrimSpace(string(out))
176         if !strings.Contains(sout, "lo:") {
177                 t.Fatalf("Expected lo network interface to exist, got %s", sout)
178         }
179 
180         lines := strings.Split(sout, "\n")
181         if len(lines) != 3 {
182                 t.Fatalf("Expected 3 lines of output, got %d", len(lines))
183         }
```

to this,

```
165         cmd := exec.Command("cat", path)
166         //cmd.SysProcAttr = &syscall.SysProcAttr{
167         //      Unshareflags: syscall.CLONE_NEWNET,
168         //}
169         out, err := cmd.CombinedOutput()
170         if err != nil {
171                 t.Fatalf("Cmd failed with err %v, output: %s", err, out)
172         }
173 
174         // Check there is only the local network interface
175         sout := strings.TrimSpace(string(out))
176         if !strings.Contains(sout, "lo:") {
177                 t.Fatalf("Expected lo network interface to exist, got %s", sout)
178         }
179 
180         lines := strings.Split(sout, "\n")
181         //if len(lines) != 3 {
182         if len(lines) != 4 {
183                 t.Fatalf("Expected 3 lines of output, got %d", len(lines))
184         }
```

After those changes, building finished without error.

**Comment by minux** [comment]
Are you running inside some kind of container that blocked
new net namespace creation?

**Comment by owlab-exp** [comment]
I am running it in a physical machine (Hikey board, debian-jessie), not in a container.

**Comment by mwhudson** [comment]
Which kernel? Maybe it doesn't have CONFIG_NET_NS=y set?

**Comment by owlab-exp** [comment]
The kernel is **3.1.8-linaro-hikey**. 
And /boot/config-3.1.8.0-linaro-hikey shows :
```
CONFIG_NET_NS=y
```

**Comment by minux** [comment]
The test already checks for the existence of /proc/self/ns/net
before the exec, so I don't think the reason is lack of networking
namespace support.

**Comment by mwhudson** [comment]
3.1 still sounds pretty old but I certainly don't know the details here,
sorry.

**Comment by mdcnz** [comment]
Saw this issue in a docker container:
starting from docker golang:1.7.3-wheezy image
removed go1.7.3
downloaded go1.4 binaries
git clone latest go source
ran ./all.bash as root

--- FAIL: TestUnshare (0.00s)
	exec_linux_test.go:177: Cmd failed with err fork/exec /bin/cat: operation not permitted

If test is skipped, build is successful.

go version devel +3cbfcaa Mon Oct 24 02:33:39 2016 +0000 linux/amd64

**Comment by CAFxX** [comment]
Ran into this today using docker:
```
FROM ubuntu:latest
RUN apt-get -y update && apt-get install -y git golang build-essential gcc
RUN git clone https://github.com/golang/go.git
CMD cd go/src; GOROOT_BOOTSTRAP=`go env GOROOT` ./all.bash
```

**Comment by bradfitz** [comment]
@CAFxX, privileged container or not? Kernel version? What does "ubuntu:latest" currently resolve to?

**Comment by shanemhansen** [comment]
FWIW I verified that go1.9 docker builds work if you use the --privileged.
