### ISSUE TITLE
x/mobile: preview app on desktop

### ISSUE THREAD

**Issue by acornejo** [golang/go#17203]
One of the most painful points of developing mobile applications, is that you need to use a physical device or emulator to preview any and all changes to the app.

It would be awesome if gomobile could produce desktop binaries where one could preview the app before deploying to the mobile phone. Essentially one would add another backend (for instance, using the linux X server) that implements the gomobile app interface.

Is this feature on gomobile's roadmap?

**Comment by hyangah** [comment]
why not 'go build'?

**Comment by udhos** [comment]
This issue does not make sense. gomobile already has the feature.

**Comment by changkun** [comment]
A mobile app can be built using `go build`, and the compiled binary can directly run on the host. This is not an issue. Close.
