### ISSUE TITLE
strange panic depending on struct field order or 32bit-64bit arch

### ISSUE THREAD

**Issue by fgergo** [golang/go#17207]
### What version of Go are you using (`go version`)?
both 1.7.1 and 1.4.3 behave the same, not tested anything else. yet.

### What operating system and processor architecture are you using (`go env`)?
32 bit architectures seems to be affected
tested:
panic on: 32 bit windows 7 and raspbian on a pi2
no panic (normal, expected behaviour) on 64bit freebsd and linux

### What did you do?
Links to playground are only for easier copy-pasting. Playground is working correctly, probably because play.golang.org is running on 64 bit arch.

Minimal full runnable repro program:
https://play.golang.org/p/EtJre5AGtw
To reproduce please check on 32 bit windows 7 or 32 bit raspbian.
I suspect the bug probably depends on if the test program is running on 32bit or 64bit architectures, though I could not test on the same os and on different architectures.

Also working correctly:
i.) when int64 and AddInt64() are changed to int32 and AddInt32() respectively the panic goes away
https://play.golang.org/p/gk2IacMYBU
ii.) when *a and i int64 order is changed, panic goes away:
https://play.golang.org/p/T0VbE_-bBb

### What did you expect to see?
The minimal repro program should finish normally and print the log message, like it does on the playground or when run on 64bit linux or 64bit freebsd.

These are the errors I get:
on 32bit raspbian with go1.7.1:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x6b5a8]

goroutine 1 [running]:
panic(0xb2ce0, 0x1040a010)
        /src/go/src/runtime/panic.go:500 +0x33c
sync/atomic.addUint64(0x1046a054, 0x1, 0x0, 0x1, 0x0)
        /src/go/src/sync/atomic/64bit_arm.go:31 +0x68
main.main()
        /home/pi/src/a.go:19 +0x64
exit status 2
--- end of 32bit raspbian error with go1.7.1

on 32bit raspbian with go1.4.3:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x4a374]

goroutine 1 [running]:
sync/atomic.addUint64(0x10338034, 0x1, 0x0, 0x1, 0x0)
        /src/go/src/sync/atomic/64bit_arm.go:31 +0x70
main.main()
        /home/pi/src/a.go:19 +0x78

goroutine 2 [runnable]:
runtime.forcegchelper()
        /src/go/src/runtime/proc.go:90
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /src/go/src/runtime/mgc0.go:82
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /src/go/src/runtime/malloc.go:712
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4
exit status 2
--- end of 32bit raspbian go1.4.3 error message

on 32bit windows 7 with go1.7.1:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x4a374]

goroutine 1 [running]:
sync/atomic.addUint64(0x10338034, 0x1, 0x0, 0x1, 0x0)
        /src/go/src/sync/atomic/64bit_arm.go:31 +0x70
main.main()
        /home/pi/src/a.go:19 +0x78

goroutine 2 [runnable]:
runtime.forcegchelper()
        /src/go/src/runtime/proc.go:90
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
        /src/go/src/runtime/mgc0.go:82
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
        /src/go/src/runtime/malloc.go:712
runtime.goexit()
        /src/go/src/runtime/asm_arm.s:1322 +0x4
exit status 2
-- end of 32bit windows 7 error message

**Comment by dominikh** [comment]
Please see the third paragraph in the Bugs section of the sync/atomic package: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned

**Comment by fgergo** [comment]
thanks!
