### ISSUE TITLE
runtime: TestCollisions takes 61 seconds on linux-arm

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17217]
Do we need this test in short-mode? It takes 60 seconds on ARM:

```
=== RUN   TestCollisions
--- PASS: TestCollisions (61.30s)
```

/cc @randall77

**Comment by bradfitz** [comment]
And 1.53 seconds on amd64.

**Comment by randall77** [comment]
It would be fine to punt this test out of -short.
