### ISSUE TITLE
path/filepath: Abs does not call Clean on windows

### ISSUE THREAD

**Issue by zevdg** [golang/go#17210]
The [filepath.Abs documentation](https://golang.org/pkg/path/filepath/#Abs) clearly states that "Abs calls Clean on the result", but this is not always true.  This was already noticed and mentioned in [this comment](https://github.com/golang/go/issues/16111#issuecomment-228955189) on issue #16111, but this one quirk seems to have been missed in the patch.

I understand that changing this behavior to match the docs would break any code that depends on the existing implementation.  If the implementation cannot be changed, the documentation should at least be updated to match the implementation.

go version: go1.7.1 windows/amd64

Run this code from [this playground](https://play.golang.org/p/mSWVatv4ql) on windows and linux and compare the output

I expected to see a cleaned result coming out of Abs on windows.  I'm using the trailing slash as the indicator that clean was not called.

Instead, I see that Clean was not called by Abs on windows.  A quick comparison of the windows and unix implementations of Abs verifies this inconsistency.

**Comment by alexbrainman** [comment]
I agree, we should change windows filepath.Abs to call filepath.Clean before it returns. Maybe add new test from your example (https://play.golang.org/p/mSWVatv4ql) to path/filepath.TestAbs .

@psywolf would you like to send a change? See https://golang.org/doc/contribute.html for instructions. Maybe wait couple days to see if others object.

Thank you.

Alex

**Comment by psywolf** [comment]
Interestingly, the check is already in [the test](https://golang.org/src/path/filepath/path_test.go#L1080).  There just aren't any test cases that triggered it.  I'd be happy to contribute a patch if no one minds the potential downstream breakage.

**Comment by zevdg** [comment]
Ok, this has sat here long enough without objection.  I'll start work on a patch.

**Comment by rsc** [comment]
@zevdg, did you create the patch?

**Comment by zevdg** [comment]
Yeah, I did.  I just have to get approval from my company's legal to upstream it.  Given how trivial this is, I don't anticipate any problem there.

**Comment by rsc** [comment]
Ping @zevdg.

**Comment by zevdg** [comment]
legal approved this today.  Will submit this patch tomorrow morning.

**Comment by zevdg** [comment]
code review at  https://go-review.googlesource.com/#/c/32292/
