### ISSUE TITLE
cmd/compile: regalloc spilling unecessarily before ops with constrained inputs

### ISSUE THREAD

**Issue by mundaym** [golang/go#17214]
In  the s390x port we have quite a few ops that heavily constrain input registers. For example, STMG4 forces its inputs into R1, R2, R3 and R4. It does this because it requires consecutive registers and there is no other way (that I can think of) to get consecutive input registers using SSA rules. We have a similar problem with instructions that require an even-odd register pair. Other architectures also do something similar for LoweredMoves because it clobbers the input registers.

Unfortunately constraining the input registers can cause the register allocator problems. For example, in BenchmarkAppend:

```
at entry: R1=b R3=d R4=c

a = MOVDaddr <uintptr> {type.int} _ : R1 // forces b out of R1
b = LoadReg <*uint8> _ : R2
c = Copy <int> R4 : R3                   // forces d out of R3
d = LoadReg <int> _ : R4
_ = STMG4 <mem> _ a b c d _
```

`b` and `d` are spilled unnecessarily because we have unallocated registers available and could have re-arranged the inputs as:

```
b = Copy <*uint8> R1 : R2
a = MOVDaddr <uintptr> {type.int} : R1
_ = Copy <int> R3 : R5
c = Copy <int> R4 : R3
d = Copy <int> R5 : R4
_ = STMG4 <mem> _ a b c d _
```

I'm planning to take a look at the register allocator to see if I can fix this. I think both these cases are a little fiddly though. I'm not sure if there is a general solution to this problem... Perhaps copying evicted values to a new register when there are further uses close by?

In this particular case it would also help if the `StoreReg` ops were moved into this basic block (I noticed there are some TODOs to do this in the regalloc code). Currently the generated code ends up something like this:

```
for {
     // spill here
     if unlikely {
          // load spilled values
     }
}
```

**Comment by randall77** [comment]
I believe this is a dup of #16061.

It would be good to either:
1) Make the desired register portion of regalloc stronger so it handles these cases.
    Maybe just make sure that s390x is triggering desired registers at all.
2) Implement "spill to register" instead of spill to stack.  That is required for #16061, where no amount of desired register information can help, because we desire 2 different values in the same register (two DIVs that both need their args in AX).

**Comment by quentinmit** [comment]
@mundaym @randall77 #16061 is now marked as fixed; can this issue be closed as well?

**Comment by mundaym** [comment]
Ah yes, sorry, it can be closed. The fix for #16061 fixed this too. It would be nice to firm up the 'desired register' code for s390x but it isn't as important.

I'm not completely certain but it looks to me like the desired registers aren't triggered in this case because the `Block` containing the `STMG` instruction has a successor that is also a predecessor and has already been processed.

In other words B2's desired registers are  ignored if B1 is processed first and B1 is a successor of B2:

```
──> B1 ───> B2 ──>
    ^       │
    └───────┘
```

**Comment by randall77** [comment]
I'm not sure I understand your example and what exactly isn't working.  Which block is the STMG in?  B1 should get desired register information from B2.
Maybe we should discuss in a new bug.

**Comment by mundaym** [comment]
Hmm, after studying the code again I think the comment above is wrong, my apologies. I'll see if I can put together a better bug report, but I think (I haven't fully verified this) the following is happening:

1. The desired register information is being dropped when it is propagated backwards through phis [here](https://github.com/golang/go/blob/d0e92f61e5c5c59395d9b1a3b4f5c7b90dec5bc8/src/cmd/compile/internal/ssa/regalloc.go#L2322) and so it doesn't make it to the initial register allocation of the value.
2. The desired register information at the start of the block with the `STMG` in it (B2) is being overridden by the dynamically calculated values present in the previous block (B1) [here](https://github.com/golang/go/blob/d0e92f61e5c5c59395d9b1a3b4f5c7b90dec5bc8/src/cmd/compile/internal/ssa/regalloc.go#L949).

(2) is what I was trying to talk about in my comment above, although (1) is probably the more important bit. 'Fixing' (2) would probably result in code similar to that generated by https://golang.org/cl/29732, albeit with values moved into their desired registers at the start of the block rather than just before they are clobbered.

**Comment by dr2chase** [comment]
This might have some bearing on the parameters-in-registers experiment, too.  I'll keep an eye out for unfortunate-looking register movement.
