### ISSUE TITLE
x/tools/go/ast/astutil: AddImport removes imports

### ISSUE THREAD

**Issue by rhysh** [golang/go#17212]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.7.1 darwin/amd64
```

golang/tools@3f4088edb48e8a4e3c66a5f8e7b2a78615fcb83f

### What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rhys/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/zmds5zsn75z1283vtzxyfr5hj7yjq4/T/go-build054967312=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

I added a test case to golang.org/x/tools/go/ast/astutil's imports_test.go for adding an import of `"net/http"` the following file:

```
package main

import "bufio"
import "net/url"
```

### What did you expect to see?

I expected the output file to include all three imports, probably in a single import block.

```
package main

import (
	"bufio"
	"net/http"
	"net/url"
)
```

### What did you see instead?

```
package main

import "bufio"
```

---

It seems that this doesn't happen when the new package doesn't share a prefix with an existing package, or when the packages are all listed in a single block-style import.

**Comment by bradfitz** [comment]
You want to fix?

**Comment by rhysh** [comment]
I'll take a stab at it, though I'm not yet familiar with manipulating the AST.

Do you want to review?

**Comment by bradfitz** [comment]
I'm scarred by and now scared of the AST package.

I think @griesemer likes those CLs.  :-)

**Comment by griesemer** [comment]
@bradfitz "likes" is a strong word. I prefer "unfortunately spent too much time with"... - I'll review it, but I cannot promise a quick turn-around as I am under water at the moment with other stuff.

**Comment by rhysh** [comment]
I've got a fix (https://golang.org/cl/29688), though I may have messed up the multi-commit workflow (it requires the change for #17213). I'd be happy to do them as a single commit, if that ends up being easier.
