### ISSUE TITLE
net: missing Multicast UDP support for plan9

### ISSUE THREAD

**Issue by sirnewton01** [golang/go#17218]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version 1.7.1

### What operating system and processor architecture are you using (`go env`)?
Plan9 (9front)

### What did you do?
I attempted to open a UDP multicast socket using the API's in net.

### What did you expect to see?
I was expecting to see that the support was there and multicast connections could be established.

### What did you see instead?
Unfortunately, it produced an error indicating that the plan9 port doesn't support this.

**Comment by bradfitz** [comment]
Sorry, the plan9 port is pretty immature.

**Comment by sirnewton01** [comment]
I have a set of commits that implement it. I'm just trying to figure out how to get the gerrit stuff working.

**Comment by sirnewton01** [comment]
Here's a link to the code review:
https://go-review.googlesource.com/29750
