### ISSUE TITLE
x/mobile: unable to run in ios9

### ISSUE THREAD

**Issue by iikira** [golang/go#17229]
- Please answer these questions before submitting your issue. Thanks!
- 
- ### What version of Go are you using (`go version`)?
- go version devel +3f4de49 Mon Apr 20 15:56:56 2015 +0000 linux/amd64
- 
- ### What operating system and processor architecture are you using (`go env`)?
- linux/amd64
- 
- ### What did you do?
- If possible, provide a recipe for reproducing the error.
- A complete runnable program is good.
- A link on play.golang.org is best.
- 
- I compiled a support binary software of ios
- > export GOOS=darwin GOARCH=arm GO386=sse2 CGO_ENABLED=1
- go build -o out/test
- 
- The file to run in ios7(ipad3) successful,But in ios9(iphone5s) run failed,like following.
- 
- >sh-3.2 # /var/root/test
- Killed: 9
- 
- So how to do?
- Forgive my poor English, :)

**Comment by minux** [comment]
Did you code sign your binary?

In previous versions of iOS, ldid -S did the trick.

**Comment by iikira** [comment]
I should code sign in ios7 device?
I can give it a try.Thank you.

**Comment by quentinmit** [comment]
I'm going to close this issue since it doesn't sound like there is a bug in Go. Please see https://golang.org/wiki/Questions for resources to help you get your code running.
