### ISSUE TITLE
what's the best way to calculate md5 with very large file (~1GB)

### ISSUE THREAD

**Issue by thincal** [golang/go#17225]
### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
ubuntu14.04

### Question in detail
Current md5 calculation way is trying to load the content in memory then do the calculation finally.
But if the content is very large such a 1GB file, the memory consumption will be very high.

md5 itself is a 512 bits chunk based, so md5 in Golang is only loading a chunk then sum all ?

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by minux** [comment]
You can use the io.Writer interface of hash.Hash interface
so that you don't need to read the whole file into memory.

BTW, please ask questions on other mediums, see
https://golang.org/wiki/Questions. Thanks.

**Comment by odeke-em** [comment]
In support of what @minux said here is an example in the new docs on tip.golang.org https://tip.golang.org/pkg/crypto/md5/#example_New_file. It will be available in the next release under golang.org instead of tip.golang.org.

**Comment by thincal** [comment]
@odeke-em @minux thanks for your quick info. Yes, the digest.Write is chunk based. Many thanks again.
