### ISSUE TITLE
text/template: template function index should permit integer values of float type

### ISSUE THREAD

**Issue by willfaught** [golang/go#17236]
The text/template function `index` should permit integer values of float type as indexes, since there's no way to convert types in templates themselves.

I hit this particular problem when using unmarshaled JSON as the template data, similar to what's done in the play link below, where an integer in one part refers to an index of a list in another part, but when parsed, the integer is converted to float64.

Note that the function `eq` is also loose with types.

### What did you do?

https://play.golang.org/p/_9K1wu6THk

### What did you expect to see?

    9

### What did you see instead?

    template: :1:2: executing "" at <index .a .b>: error calling index: cannot index slice/array with type float64

**Comment by bradfitz** [comment]
You should probably unmarshal into a concrete type, instead of unmarshalling into `interface{}`.

I don't think this is a change we want to make. I'm closing this, but I'll let @robpike or @adg reopen if they feel otherwise.

**Comment by willfaught** [comment]
@bradfitz In my case, the JSON can be anything, hence why it unmarshals into `interface{}`. I suppose this might be an edge case, but it seems like we already went down this road with `eq`...

**Comment by robpike** [comment]
Happy to keep it closed.
