### ISSUE TITLE
encoding/json docs reference an unknown entity "DisableHTMLEscaping"

### ISSUE THREAD

**Issue by xoba** [golang/go#17255]
i think it actually means Encoder's method "SetEscapeHTML."

**Comment by mvdan** [comment]
Looks like this was indeed changed earlier this year:

```
-pkg encoding/json, method (*Encoder) DisableHTMLEscaping()
+pkg encoding/json, method (*Encoder) SetEscapeHTML(bool)
```

**Comment by mvdan** [comment]
CL sent: https://go-review.googlesource.com/#/c/29878/

This is also present in 1.7. Do doc fixes qualify for point releases, e.g. `1.7.2`?

**Comment by minux** [comment]
No, doc changes doesn't meet the bar for point releases.
