### ISSUE TITLE
time.String produces garbage out for time.Parse (garbage in)

### ISSUE THREAD

**Issue by Yndoendo** [golang/go#17254]
time.String() produces non-standard output that time.Parse cannot handle.  This goes against less is more since either a person needs to write a custom parser or change the output format which both increases the code base.

If marked as not a bug nor not fixing, documentation for time package should be updated to inform that that time.String output is incompatible with time.Parse.

### What version of Go are you using (`go version`)?
go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="$HOME/.local/share/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build766838131=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
https://play.golang.org/p/wmfQP5wX0S
```
func main() {
    t := time.Now().UTC()
    s := t.String()

    t, err := time.Parse(s,s)
    if err != nil {
        fmt.Println(s, "parsed with error", err)
    } else {
        fmt.Println(s, "equals", t.String())
    }
}
```

**Comment by freeformz** [comment]
The first value to time.Parse is the layout. time.String's [docs](https://golang.org/pkg/time/#Time.String) indicate what the layout is. So [this](https://play.golang.org/p/LmCYLaBA3u) works.

If anything here it would be nice to export that format as a constant instead of embedding the string directly in time.String().

**Comment by bradfitz** [comment]
You already filed this bug in #17253. What @freeformz is correct. You're just not using the time package correctly.

I recommend https://golang.org/wiki/Questions for questions about learning Go.

**Comment by Yndoendo** [comment]
Sorry, didn't know layout had to be certain date and time, looked only to be just the format.
