### ISSUE TITLE
time.Parse fails at parsing time.String

### ISSUE THREAD

**Issue by Yndoendo** [golang/go#17253]
time.Parse can not parse the default format produced by time.String()

### What version of Go are you using (`go version`)?
go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="$HOME/.local/share/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build766838131=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
https://play.golang.org/p/wmfQP5wX0S
```
func main() {
	t := time.Now().UTC()
	s := t.String()
	
	t, err := time.Parse(s,s)
	if err != nil {
		fmt.Println(s, "parsed with error", err)
	} else {
		fmt.Println(s, "equals", t.String())
	}
}
```

### What did you expect to see?
```
2016-09-27 16:53:03.13465009 +0000 UTC equals 2016-09-27 16:53:03.13465009 +0000 UTC
```
### What did you see instead?
There were different out comes, local:
```
2016-09-27 16:53:03.13465009 +0000 UTC parsed with error parsing time "2016-09-27 16:53:03.13465009 +0000 UTC": month out of range
```

go playground:
```
2009-11-10 23:00:00 +0000 UTC parsed with error parsing time "2009-11-10 23:00:00 +0000 UTC" as "2009-07-10 23:00:00 +0000 UTC": cannot parse "9-11-10 23:00:00 +0000 UTC" as "009"
```

**Comment by bradfitz** [comment]
Not a bug. The result of String is not a valid format.
