### ISSUE TITLE
x/net/http2: scheme is hardcoded to https

### ISSUE THREAD

**Issue by ayanamist** [golang/go#17257]
https://github.com/golang/net/blob/f09c4662a0bd6bd8943ac7b4931e185df9471da4/http2/transport.go#L1049
Here `scheme` is hardcoded to `https`, but for #15830 the scheme may be `http`, so the request received by h2c server has wrong scheme.
When using with a http2 proxy, this leads to a wrong request, `GET http://www.example.com` becomes `GET https://www.example.com` when remote proxy server received, and wrong content is fetced.

**Comment by bradfitz** [comment]
I have a full plate and am not prioritizing any non-https features or fixes in the http2 package, but somebody else can take this bug.

**Comment by ayanamist** [comment]
@bradfitz I fix it and add some test.
https://go-review.googlesource.com/29975
Do you know who can review it?
