### ISSUE TITLE
x/time/rate: document that the rate limiter is safe for concurrent usage

### ISSUE THREAD

**Issue by nightlyone** [golang/go#17261]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go version go1.7.1 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ingo/sources/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build059178747=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
### What did you do?

Read documentation of https://godoc.org/golang.org/x/time/rate
### What did you expect to see?

Mention that all types (or at least which types, functions, methods) are safe for concurrent usage and don't need extra locking around them.
### What did you see instead?

Nothing. But I concluded that by reading the code.

**Comment by nightlyone** [comment]
I only filed that issue, because I wanted to refer a colleague to the docs saying that this needs no extra locks, but found that the docs don't mention it and Go documentation style default is "you need locking until stuff is marked as concurrency safe".

**Comment by zengchu2** [comment]
Can I work on this issue ?
I would like to implement a couple test cases for functions like `Limit(), SetLimit() ...` for type Limiter. Currently there is only one test case for method `Allow()` that uses multi goroutines. @ALTree  @bradfitz

**Comment by ianlancetaylor** [comment]
@zengchu2 Go ahead.  Thanks.

**Comment by zengchu2** [comment]
> @zengchu2 Go ahead. Thanks.

Suggested implementation has been submitted here [https://go-review.googlesource.com/c/time/+/416374](url). Any comments and suggestions are appreciated :)
