### ISSUE TITLE
x/mobile: sha256 for "gomobile-ndk-r10e-darwin-x86_64.tar.gz":

### ISSUE THREAD

**Issue by jsaguiar** [golang/go#17260]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

Go 1.7.1
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/user/GoWork"
GORACE=""
GOROOT="/Users/user/Frameworks/go"
GOTOOLDIR="/Users/joao/Frameworks/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n9/6nv6w38n1psdddz183zlk0lw0000gn/T/go-build050620701=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### What did you do?

Re-install go and gomobile
### What did you see?

gomobile: sha256 for "gomobile-ndk-r10e-darwin-x86_64.tar.gz": e8bff8a56f5688ec849a95a4e85130ce02eff5c2d54e361103777c396db8d308, want 9185a734b1b3d8dd29f3bc3c55cf03e397414e656345b7ed835879ee8eb76ebb

**Comment by eliasnaur** [comment]
gomobile doesn't download the NDK anymore. Closing this.
