### ISSUE TITLE
crypto/tls: Sometimes fails to parse private key

### ISSUE THREAD

**Issue by Foosvald** [golang/go#17279]
### What version of Go are you using (`go version`)?
`go version go1.7 darwin/amd64`

### What did you do?
I'm trying to load X.509 key pairs using tls.LoadX509KeyPair. The key pairs have been generated using node-forge, and are generated using the same options each time. In most cases tls.LoadX509KeyPair works and loads the key pair, but for some of the key pairs it cannot parse the private key. All of the generated keys are parsed correctly by openssl though.

```
$ openssl rsa -in broken.key -check -noout
RSA key ok
```

This is the program I run:
```
package main

import (
    "crypto/tls"
    "log"
)

func main() {
    _, err := tls.LoadX509KeyPair("broken.pem", "broken.key")
    if(err != nil) {
        log.Fatal(err)
    }
    log.Print("Go loaded key successfully")
}
```

I've also attached both the key pair that is not working, and a key pair that is working (and is correctly opened by tls.LoadX509KeyPair) which has been generated using the same options.  
[keys.zip](https://github.com/golang/go/files/500658/keys.zip)

### What did you expect to see?
`2016/09/29 14:31:49 Go loaded key successfully`

### What did you see instead?
```
2016/09/29 14:32:19 tls: failed to parse private key
exit status 1
```

**Comment by ebfe** [comment]
x509.ParsePKCS1PrivateKey fails with `asn1: structure error: integer not minimally-encoded` for `broken.key`

**Comment by Foosvald** [comment]
So is this a problem with node-forge? Or Go? OpenSSL says that they key is valid...

**Comment by quentinmit** [comment]
/cc @agl 

I *think* from recent issues that this is WAI and the key is incorrectly generated. But I'll let Adam confirm.

**Comment by Foosvald** [comment]
This was an issue in Node-forge, which has now been resolved. So I'm closing this issue.

**Comment by jeroiraz** [comment]
Found the same issue, just using openssl and go 1.9, besides openssl validating the key the http server failed to parse it. Tried again with a key generated in the same way and worked. Seems the issue is still present

**Comment by izaaklauer** [comment]
I'm also still seeing this issue with go 1.9. Openssl reports `RSA key ok`, x509.ParsePKCS1PrivateKey returns `asn1: structure error: integer not minimally-encoded`.

**Comment by bradfitz** [comment]
@jeroiraz, @izaaklauer, you're either using an old version of Node-forge before it was fixed (https://github.com/digitalbazaar/forge/commit/4dfc87ce0f7a2709d4feccb12b0d04a0184271e8) or you're commenting on the wrong bug.

In any case, this bug is closed and no longer tracked.

If you're having an issue, file a new bug with complete details.
