### ISSUE TITLE
reduce time of fetching record 

### ISSUE THREAD

**Issue by kritika1439** [golang/go#17273]
i am using revel framework with ubuntu  to make a web service which executes a statement and fetches the result . the result set contains 20-25 row . my requirement is to reduce the time to less than 50 ms but now the time is 400-600 ms . 
the same service in php takes around 120 ms . 

i have made connection in app.init file as follows . this file excute once on starting the service first time . i made this so that the connection is persistant and time reduce in subsequent hits : 
**app.init.go**
var Environment *ora.Env
var Serv *ora.Srv
var OracleSes *ora.Ses
func InitDB() {
ServiceConfig := ora.SrvCfg{Dblink: "//hostname/sid"}
 
   err:= (*ora.StmtCfg).SetPrefetchRowCount(prefetchRowCount)
   fmt.Println(err)

	SesConfg := ora.SesCfg{
		Username: "username",
		Password: "password",
	}
    Environment, Err = ora.OpenEnv(nil)
	//defer Environment.Close()
	if Err != nil {
		fmt.Println(Err)
	}
	Serv, Err  = Environment.OpenSrv(&ServiceConfig)
	//defer Serv.Close()

	if Err != nil {
		fmt.Println(Err)
	}
 	OracleSes, Err  = Serv.OpenSes(&SesConfg)
	//defer Ses.Close()
	if Err != nil {
		panic(Err)
	}
}

now in my other file where i used app.OracleSes object to execute my query and fetch the result : 

func GetGrouplist() {

 		time6 := time.Now()
 		querystr := "call myprocedure(:IN_GRP_ID,:OUT_CUR_OFR)"
 		var IN_GRP_ID int64
		IN_GRP_ID = 34
 
		stmtProcCall, err := app.OracleSes.Prep(querystr)
		//	defer stmtProcCall.Close()
		if err != nil {
			fmt.Println(err)
		}
		procRset := &ora.Rset{}
		_, err = stmtProcCall.Exe(IN_GRP_ID, procRset)
		time5 := time.Now()
		fmt.Printf("Main total after query  %v \n", time5.Sub(time6))
		if err != nil {
			fmt.Println(err)
		}
		if procRset.IsOpen() {
  			for procRset.Next() {
				time3122 :=time.Now()
				//-----------------------------------------------------------------------------------
				rowdata := make(map[string]interface{})
				col := procRset.ColumnNames
				for i, y := range col {
					rowdata[y] = procRset.Row[i]
				}
				//start for additional info
				time322 :=time.Now()
				fmt.Printf("Main total procRset.Next() GRP_NAME %v \n", time322.Sub(time3122))
 			}
			time152 := time.Now()

			if procRset.Err != nil {
				fmt.Println(procRset.Err)
			}	 
		}	 
}

i read that increasing row prefetch size may help but i have two doubt 
1. my row result size is 20-25 rows
2 how to increase the prefetch row size programitically . 
3. i noticed that while fetching the results the following code snippet takes more time : 

     			for procRset.Next() {
				time3122 :=time.Now()
				
 				rowdata := make(map[string]interface{})
				col := procRset.ColumnNames
				for i, y := range col {
					rowdata[y] = procRset.Row[i]
				}
				//start for additional info
				time322 :=time.Now()
				fmt.Printf("Main total procRset.Next() GRP_NAME %v \n", time322.Sub(time3122))
  
 			}

i m new to golang so please help

**Comment by bradfitz** [comment]
For help learning Go or questions about the language, see https://golang.org/wiki/Questions
