### ISSUE TITLE
proposal: cmd/cover: report untested nil values entry-points

### ISSUE THREAD

**Issue by henvic** [golang/go#17272]
Given that null references cause so much unexpected trouble, what about reporting untested entry points that could cause nil point panics on the code coverage report?

This could be limited to public functions and show as a small flag on the HTML reports.

Example:

``` go
...
var projects, err = repo.GetProjects() [nil]
...
```

where `[nil]` would actually be a report flag saying this code wasn't covered with a nil return for this value.

Reference: [Null References: The Billion Dollar Mistake
](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare)

**Comment by adg** [comment]
This is not the purpose of the test coverage tool. If you want to build a tool that does this and use the coverage UI, the code is there for the taking.
