### ISSUE TITLE
runtime: stackFromSystem can leak memory or leave unmapped memory behind

### ISSUE THREAD

**Issue by binarycrusader** [golang/go#17289]
When stackFromSystem = 1, the stack allocation size is rounded to the nearest page size:

```
 339         if debug.efence != 0 || stackFromSystem != 0 {
 340                 v := sysAlloc(round(uintptr(n), _PageSize), &memstats.stacks_sys)
```

...however, that rounded size is not returned to/used by the caller of stackalloc(), so when a stackfree() is later done:

```
 436         if debug.efence != 0 || stackFromSystem != 0 {
 437                 if debug.efence != 0 || stackFaultOnFree != 0 {
 438                         sysFault(v, n)
 439                 } else {
 440                         sysFree(v, n, &memstats.stacks_sys)
 441                 }
```

We'll either set less than the actual bytes allocated for faulted access, or fail to free/unmap all of the memory.

**Comment by binarycrusader** [comment]
I suspect this isn't generally noticed on architectures that use a pagesize of 4096, since when we do a stackalloc, we'll typically do it for at least 4096, which is the nearest page size, so it usually works as expected.

As such, I suspect this is generally the most noticeable on mips64, ppc64, arm, arm64, etc.

This was discovered while working on the sparc64 port since the DefaultPhysPageSize is 8192.

**Comment by randall77** [comment]
We should just increase _StackMin to at least _PageSize if stackFromSystem is set.
