### ISSUE TITLE
x/net/http2: pre-1.7 broken build

### ISSUE THREAD

**Issue by rolandshoemaker** [golang/go#17286]
### What version of Go are you using (`go version`)?

`go version go1.6 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/roland/gopath"
GORACE=""
GOROOT="/home/roland/go1.6"
GOTOOLDIR="/home/roland/go1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

Try to run `x/net/http2` tests with 1.6

### What did you expect to see?

No error

### What did you see instead?

```
# golang.org/x/net/http2
./transport.go:1853: ctx.Done undefined (type contextContext is interface with no methods)
./transport.go:1854: ctx.Err undefined (type contextContext is interface with no methods)
FAIL	golang.org/x/net/http2 [build failed]
```

It appears that [golang.org/x/net/http2 ed0556cc888129faa06ff0ef3c65e0ce59c8b75c](ed0556cc888129faa06ff0ef3c65e0ce59c8b75c) introduces this bug by attempting to use methods on `contextContext` which is a empty interface for 1.6 whereas for 1.7 it implements `context.Context`.

It seems like the simplest solution would be to make `contextContext` for 1.6 implement `golang.org/x/net/context.Context`.

**Comment by leadinglocally** [comment]
This just started happening to me about 12 hours ago for no reason, on Go 1.7 ?????
How do i fix it?
