### ISSUE TITLE
x/net/http2: support graceful close of client connection

### ISSUE THREAD

**Issue by rs** [golang/go#17292]
I'm implementing my own http2.ConnPool with some health checking done using the new `Ping()` method. My problem is that my pool doesn't have the capability to dispose client connections because there is no way to cleanly close a client connection other than keeping it's `net.Conn` on the side and abruptly close it.

What about adding a `Close()` method `http2.ClientConn` that would send a `GOAWAY` frame and wait for the in-flight streams to complete?

Implementation proposal: https://go-review.googlesource.com/#/c/30076/

**Comment by rs** [comment]
This PR has been sitting for month now. Is there something to be done to resume the review?

**Comment by bradfitz** [comment]
Sorry, that CL (its tests mostly) exhausted me earlier and then I forgot about it during Go 1.8 chaos.

Its tests still need a bit of clarity about what they're trying to do. The test code itself might be fine now, but it's hard to tell without comments saying what the intent is.

It looks like the non-test code is still fine.

/cc @tombergan

**Comment by rs** [comment]
I am sorry to hear tests exhausted you :)
I added some comments to clarify the tests.

**Comment by rs** [comment]
Thank you @bradfitz

**Comment by gaorong** [comment]
> I'm implementing my own http2.ConnPool with some health checking done using the new `Ping()` method.

@rs sorry to bother you,  I want to find a proper way to use `Ping()` method, but can hardly find some valuable reference, would you mind sharing your implement of ConnPolol?  thanks

**Comment by rs** [comment]
Our final implementation ended up not using ping.
