### ISSUE TITLE
syscall: Fsid.X__val not exported on s390x

### ISSUE THREAD

**Issue by mundaym** [golang/go#17298]
Kubernetes recently added https://github.com/pkg/sftp as a dependency. The sftp package uses the `X__val` member in the `Fsid` struct which we currently replace with `_` on s390x using mkpost.go.

The usage is here: https://github.com/pkg/sftp/blob/8197a2e580736b78d704be0fc47b2324c0591a32/server_statvfs_linux.go#L19.

Since this variable is used on other architectures we should expose it so that sftp will compile (although it may need an endianness fix too). I will send a CL.

**Comment by bradfitz** [comment]
They should just not use the built-in syscall package.

Also, that field is kinda disgusting and the comment is very encouraging:

```go
  Fsid:  uint64(uint64(stat.Fsid.X__val[1])<<32 | uint64(stat.Fsid.X__val[0])), // endianness?
```

Do they even need that field? They don't seem to know what it even is.

Deleting that line might be a better fix?

**Comment by ianlancetaylor** [comment]
You have to love the statfs man page on GNU/Linux: "Nobody knows what f_fsid is supposed to contain."

But it does go on to say "The general idea is that f_fsid contains some random  stuff  such  that the  pair (f_fsid,ino) uniquely determines a file."
