### ISSUE TITLE
Cross compilation to android arm architecture gcc/gco failed

### ISSUE THREAD

**Issue by esperlu** [golang/go#17297]
Trying to cross compile a simple Hello World to android/arm failed.

### What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN="/home/jeanluc/scripts/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jeanluc/scripts/golang"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build829110422=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
`$ env GOOS=android GOARCH=arm  go build -v ~/scripts/golang/src/test/hello.go`
and various combination of options ( CGO_ENABLED, GOARM...)

### What did you expect to see?
a binary in the PWD

### What did you see instead?
At the end of the  build process:
```command-line-arguments
# command-line-arguments
warning: unable to find runtime/cgo.a
/usr/lib/go-1.7/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘-marm’; did you mean ‘-mabm’?
```

**Comment by thanm** [comment]
GCC (and hence gccgo) doesn't support having a single compiler that selects an arbitrary target at runtime. If you want a linux/amd_64 hosted arm target cross compiler, you have to build gcc/gccgo that way (unlike clang or the regular go compiler).

**Comment by esperlu** [comment]
Thanks for your input, but I rarely compile anything and what you say sounds rocket science to me. The cross compiling to windows/amd64 and linux/arm worked like a charm with the go commands and I was hoping to achieve the same (easy) path for the android/arm architecture...

**Comment by thanm** [comment]
Whoops, I just realized I misread your bug report -- it says "gcc/gco" and I read it as "gccgo". Apologies for the confusion.

**Comment by crawshaw** [comment]
That looks like you are using the host gcc toolchain instead of the cross compiler. Did you set CC_FOR_TARGET when you ran make.bash/all.bash?

**Comment by esperlu** [comment]
I only ran the by Go supplied `go build` command with the GOOS and GOARCH env. variables set on the `android` and `arm`. It worked flawlessly for windows/amd64 and linux/arm with the standard settings of my compile environment. No CC_FOR_TARGET variable thet environment. Forgive me, but as I said above, compilation intimidates me and I have a (very) limited experience in that. What value should I set to CC_FOR_TARGET variable?

**Comment by crawshaw** [comment]
For future reference, questions like this don't really fit into the issue tracker. See https://golang.org/wiki/Questions.

Unlike other GOOS targets, GOOS=android needs a C/C++ toolchain to compile binaries. Setting up a C cross compiler requires pointing CC_FOR_TARGET at the C compiler when building the Go installation. You can get the C compiler from the Android NDK.

You may want to consider golang.org/x/mobile/cmd/gomobile for building your binaries, which uses the Android NDK. Even if you don't want to use cmd/gomobile directly, exploring it may show you what you want to know about the go tool.
