### ISSUE TITLE
database/sql queryRow doesn't close mysql connections (creates sleep connections)

### ISSUE THREAD

**Issue by therudite** [golang/go#17295]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?
Used queryRow to query mysql

### What did you expect to see?
query to work fine

### What did you see instead?
query worked fine
But it is opening connections and not closing it automatically and since there is no close method for this queryRow method, client can't defer close this cursor

**Comment by nuss-justin** [comment]
QueryRow, like the Query and Exec methods, does not close connections, but puts them back into a connection pool once you are done with the result (in the case of QueryRow, this means calling the Scan method on the result Row). Other queries can than use a connection from the pool, if there is any, to avoid creating new connections (which can take some time). See the documentation for [sql.DB](https://golang.org/pkg/database/sql/#DB).

You can limit the number of idle connections in the pool by using [SetMaxIdleConns](https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns), limit the maximum number of open connections with [SetMaxOpenConns](https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns) and use [SetConnMaxLifetime](https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime) to limit the lifetime of connections (note that this method does not guarantee that connections are closed immediately).

**Comment by therudite** [comment]
But these connections are different from idle connections. It is a sleeping connection which never goes off. I set setmaxidleconns to 0. These connections kept increasing as this particular query was part of a high traffic connection

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

If this is a regression from Go 1.6 to Go 1.7, please file a bug with a reproducible minimal example (with full source code).
