### ISSUE TITLE
x/review: Support custom git remote helpers

### ISSUE THREAD

**Issue by wlynch** [golang/go#17299]
### What version of Go are you using (`go version`)?

go version go1.7.1 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"
### What did you do?

`go get` a package that belonged to a repository that used a custom [git remote helper](https://git-scm.com/docs/git-remote-helpers).
### What did you expect to see?

The repo was successfully fetched.
### What did you see instead?

"cannot download, <repo> uses insecure protocol"
### Proposal

vcs.go is opinionated about what schemes are [considered secure](https://github.com/golang/go/blob/master/src/cmd/go/vcs.go#L44). If you are using a [git remote helper](https://git-scm.com/docs/git-remote-helpers), tools like `go get` will return an error because it thinks it is insecure. Passing `--insecure` allows the repo to be successfully fetched, but this isn't ideal because then all fetches that are pulled in from `go get` will allow insecure schemes.

We should let vcs.go be aware of the [GIT_ALLOW_PROTOCOL](https://git-scm.com/docs/git) environment variable to override the list of secure schemes for git fetches.

Other tools like [git-codereview](https://github.com/golang/review) that are affected by [similar issues](https://github.com/golang/review/blob/master/git-codereview/api.go#L76) should also be updated.

I'm happy to work on this.

**Comment by quentinmit** [comment]
@wlynch Does your commit resolve this issue?

**Comment by wlynch** [comment]
With respect to golang/go, this should be resolved. I'll open a new issue in [golang/review](https://github.com/golang/review) to track the changes needed for git-codereview.

**Comment by wlynch** [comment]
Issues are shared between golang/go and golang/review. Reopening to track the changes to golang/review.

I'm also fine with owning this change.
