### ISSUE TITLE
context: WithValue documentation should discourage use of basic types

### ISSUE THREAD

**Issue by mdlayher** [golang/go#17302]
Related to: https://github.com/golang/go/issues/17293.

I've submitted a fix to `golint` to begin warning about this, but I also feel that it would be a good idea to explicitly document that only user-defined types should be used as keys in `context.WithValue`.

As of now, there is no such warning.  The only advice given is:
> The provided key must be comparable.

EDIT: I was incorrect, see: https://github.com/golang/go/issues/17302#issuecomment-250854297.

CC @bradfitz @alandonovan

**Comment by bradfitz** [comment]
Yes, please!

**Comment by mdlayher** [comment]
I'll submit a CL shortly.

**Comment by mdlayher** [comment]
It appears I was incorrect: https://golang.org/pkg/context/#Context

```
        // A key identifies a specific value in a Context. Functions that wish
        // to store values in Context typically allocate a key in a global
        // variable then use that key as the argument to context.WithValue and
        // Context.Value. A key can be any type that supports equality;
        // packages should define keys as an unexported type to avoid
        // collisions.
```

Should this be reiterated in the documentation for `context.WithValue`, or is the documentation on the `context.Context` interface enough?

**Comment by bradfitz** [comment]
More warnings SGTM.

**Comment by mdlayher** [comment]
CL submitted: https://go-review.googlesource.com/c/30134/.

Happy to re-phrase as needed.
