### ISSUE TITLE
for on a map reuses the same address for values

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#17303]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.4 -> tip as of today

### What operating system and processor architecture are you using (`go env`)?
Linux 64bit

### What did you do?
https://play.golang.org/p/wbn3YAwyVD

### What did you expect to see?
Different pointers.

### What did you see instead?
The same pointer.

Judging since this existed since 1.4 I'm guessing it's a part of the spec but for the life of me I couldn't find it.

**Comment by bradfitz** [comment]
This is how the language is defined. Working as defined.

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

**Comment by minux** [comment]
This is how for range loop works. See also
https://golang.org/doc/faq#closures_and_goroutines.

**Comment by OneOfOne** [comment]
@minux I can't believe after all those years (answering that very question with goroutines 100 times on SO), I missed that, thank you.
