### ISSUE TITLE
net/http: len() call number can be reduced

### ISSUE THREAD

**Issue by tabakerov** [golang/go#17308]
there is a function in `server.go`:

    func pathMatch(pattern, path string) bool {
	if len(pattern) == 0 {
		// should not happen
		return false
	}
	n := len(pattern)
	if pattern[n-1] != '/' {
		return pattern == path
	}
	return len(path) >= n && path[0:n] == pattern
    }

if assign len(pattern) to variable n at the first line and do check `if n == 0` then number of calls len() will be reduced.

**Comment by bradfitz** [comment]
`len()` is not a call. It's as cheap as accessing a variable. Both "calls" will likely just be the same register access.
