### ISSUE TITLE
Go allows multiple imports of same package using package aliasing

### ISSUE THREAD

**Issue by bradclawsie** [golang/go#17301]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go v1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

debian sid, linux amd/64

### What did you do?

https://play.golang.org/p/GJ8Iru85xd

### What did you expect to see?

That `fmt` cannot be imported multiple times.

### What did you see instead?

I was able to import the same package again under an alias...personally this strikes me as wrong.

**Comment by griesemer** [comment]
This is working as intended.

Perhaps this shouldn't be allowed, but that would be a spec change.
