### ISSUE TITLE
x/mobile/bind: name clash for returned values named 'res'

### ISSUE THREAD

**Issue by scisci** [golang/go#17309]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

1.7.1
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/usr/documents/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mr/3xqmfb0d2cxcck1vlkrj4fp80000gn/T/go-build333938532=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### What did you do?

gomobile bind on code that contains a return value named 'res', like this:

```
type FooStruct struct {
}

func TestReturnVars() (res *FooStruct, err error) {
    err = json.Unmarshal([]byte{}, res)
    return
}
```
### What did you expect to see?

Should compile fine.
### What did you see instead?

Generates objective c code that has a variable redefinition because the variable name 'res' is used internally.

Generated code:

```
BOOL GoVapiTestReturnVars(GoVapiFooStruct** res, NSError** error) {
    struct proxyvapi__TestReturnVars_return res = proxyvapi__TestReturnVars();
    GoVapiFooStruct* _res = nil;
    GoSeqRef* _res_ref = go_seq_from_refnum(res.r0);
    if (_res_ref != NULL) {
        _res = _res_ref.obj;
        if (_res == nil) {
            _res = [[GoVapiFooStruct alloc] initWithRef:_res_ref];
        }
    }
    GoUniverseerror* _error = nil;
    GoSeqRef* _error_ref = go_seq_from_refnum(res.r1);
    if (_error_ref != NULL) {
        _error = _error_ref.obj;
        if (_error == nil) {
            _error = [[GoUniverseerror alloc] initWithRef:_error_ref];
        }
    }
    *res = _res;
    if (_error != nil && error != nil) {
        *error = go_seq_to_nserror(_error, errDomain);
    }
    return (_error == nil);
}
```

Which generates errors that look like this:

```
error: redefinition of 'res' with a different type: 'struct proxyvapi_FooStruct_return' vs 'FooStruct *__autoreleasing *'
```

**Comment by scisci** [comment]
I've just renamed my return variables from res to something else, but it was confusing when I got the error.

**Comment by eliasnaur** [comment]
I can't reproduce this. Newer versions of gomobile generate the binding for the above function without named return parameters:

````
TestpkgFooStruct* TestpkgTestReturnVars(NSError** error) {
    struct proxytestpkg__TestReturnVars_return res = proxytestpkg__TestReturnVars();
    TestpkgFooStruct* _res = nil;
    GoSeqRef* _res_ref = go_seq_from_refnum(res.r0);
    if (_res_ref != NULL) {
        _res = _res_ref.obj;
        if (_res == nil) {
            _res = [[TestpkgFooStruct alloc] initWithRef:_res_ref];
        }
    }
    Universeerror* _error = nil;
    GoSeqRef* _error_ref = go_seq_from_refnum(res.r1);
    if (_error_ref != NULL) {
        _error = _error_ref.obj;
        if (_error == nil) {
            _error = [[Universeerror alloc] initWithRef:_error_ref];
        }
    }
    if (_error != nil && error != nil) {
        *error = _error;
    }
    if (_error != nil) {
        return nil;
    }
    return _res;
}
````
