### ISSUE TITLE
reflect: remove almost duplicated implementation

### ISSUE THREAD

**Issue by timakin** [golang/go#17307]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.1(darwin/amd64)

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/takahashiseiji/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/87/j2gkygwn5sjgb61p83d8w3w40000gn/T/go-build844429572=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
https://github.com/golang/go/blob/master/src/reflect/value.go#L911
The top of `valueInterface` seems a little bit duplicated implementation with `CanInterface`.
Checking value flag should be done through `CanInterface`

### What did you expect to see?
https://github.com/golang/go/blob/master/src/reflect/value.go#L911-L914
A part of `L911 ~ L914` should be replaced by `CanInterface`

**Comment by bradfitz** [comment]
I don't think it's worth it. It would be more call overhead in code that's already very performance sensitive, and even it got inlined properly, the error message would then be difference and misleading, pointing the caller to the wrong function.

I think it's probably fine as-is.
