### ISSUE TITLE
Go spec shows it is possible to define identical named types. However, it is impossible.

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#17310]
### What version of Go are you using (`go version`)?

go1.7.1 linux/amd64

### What did you do?

See this discussion for details: https://groups.google.com/forum/#!topic/golang-nuts/7d_B1AhI5ho 

https://play.golang.org/p/PmkcvdNQnx

### What did you expect to see?

Either of the two:
1. "fmt.Println(a == b)" should return true in the play example above.
2. this line "Two named types are identical if their type names originate in the same TypeSpec." in go spec should be removed, for there is no ways to define identical named types.

**Comment by griesemer** [comment]
This is not a bug: You are declaring two types X (same names) but they are declared in different functions (so you can use the same name without conflict), and thus also different places in the code (and thus different TypeSpecs - or more wordly, different pieces of source code text following the syntax of a TypeSpec). Thus these two X's represent different types. Consequently, when two values of different types X are compared via an interface, the types don't match and thus the result is false. Please continue using the discussion thread if this doesn't make sense to you. Thanks.

**Comment by yaxinlx** [comment]
@griesemer, if what you says is ture, that means there is no ways to define identical named types in Golang. then, pls remvoe this line "Two named types are identical if their type names originate in the same TypeSpec." from go spec, for it is meaningless.

**Comment by minux** [comment]
Of course it's meaningful.
The example section below gives one such example:

"these types are identical:
T0 and T0
..."

"Two Xs" doesn't imply you can't use two copies of the same X.

**Comment by yaxinlx** [comment]
"T0 and T0 are identical", does this need to explain?

**Comment by minux** [comment]
Of course.

For example, if f := math.Nan(), then f != f is true.

**Comment by yaxinlx** [comment]
Sadly, there is no any explanation for "f != f" for the function math.NaN.

And even if "f != f" should be explained, I still think "T0 and T0 are identical" doesn't need to explain?

**Comment by bradfitz** [comment]
Please move this to a mailing list or similar forum.
