### ISSUE TITLE
net: Dial timeout reports incorrect problem DNS entry

### ISSUE THREAD

**Issue by dtcaciuc** [golang/go#17329]
### What version of Go are you using (`go version`)?
go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux_amd64, scilinux 6.3

### What did you do?

1. Have two nameserver entries in /etc/resolve.conf; first one is the invalid, second one is valid.
2. Run the test program

```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	_, err := http.Get("https://www.google.ca/")
	if err != nil {
		fmt.Println(err)
	}
}
```

### What did you expect to see?
Timeout message reporting the invalid nameserver IP

### What did you see instead?
Timeout message erroneously reporting the second valid nameserver IP

**Comment by vcabbage** [comment]
I think this was fixed in 1.7.1 by https://golang.org/cl/28057

I was able to reproduce this with the Go resolver on 1.7:
```
# cat /etc/resolv.conf
nameserver 8.8.8.9
nameserver 8.8.8.8
# go version
go version go1.7 linux/amd64
# GODEBUG=netdns=go+2 go run main.go
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(www.google.ca) = files,dns
lookup www.google.ca on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
exit status 1
```

With Go 1.7.1 the sample program correctly resolves the address:
```
# cat /etc/resolv.conf
nameserver 8.8.8.9
nameserver 8.8.8.8
# go version
go version go1.7.1 linux/amd64
# GODEBUG=netdns=go+2 go run main.go
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(www.google.ca) = files,dns
[172.217.3.163 2607:f8b0:400a:801::2003]
```

(The cgo resolver did not exhibit the issue for 1.7 or 1.7.1)

Note that I modified the demo program to just do the DNS lookup:
``` go
package main

import (
	"fmt"
	"net"
	"os"
)

func main() {
	ips, err := net.LookupIP("www.google.ca")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Println(ips)
}
```

**Comment by bradfitz** [comment]
@vcabbage, oh, thanks. I missed the "go1.7" in the original report.

**Comment by mikioh** [comment]
This is a duplicate of #16865.
