### ISSUE TITLE
os/file: more helpful message when trying to read from closed file

### ISSUE THREAD

**Issue by goldcaddy77** [golang/go#17320]
Note: I'd like to put in a PR for this if the team thinks it's worthwhile.  Just wanted to get the green light that it's something you're interested in before doing the work, though.

### What version of Go are you using (`go version`)?

`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/<name>/Code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wl/kq_vhh45269_fc6kzby0mk480000gp/T/go-build341095088=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

I wrote a function that was supposed to return an open io.Reader, but I accidentally closed it.  The resulting error messages are not super helpful (see below)

See: https://play.golang.org/p/geHz9FFR7I

### What did you expect to see?

I'd expect to see a more helpful error message - perhaps `read: foo.md: file already closed`

### What did you see instead?

OSX:  bad file descriptor
play.golang:  Bad file number

### Proposal

Check if `file.fd == -1` as that's already set in close.  If it's -1, send user `file already closed` message

**Comment by 0xmohit** [comment]
The error that you're observing is `syscall.EBADF` implying that the underlying fd isn't open or valid.  You may also want to refer to [`PathError`](https://golang.org/pkg/os/#PathError).

**Comment by quentinmit** [comment]
This seems reasonable if it doesn't add too much overhead to Read. We don't use PRs here, we use Gerrit. See https://golang.org/doc/contribute.html for details.

**Comment by goldcaddy77** [comment]
Thanks.  DEV is complete, just working through some gcc issues on OSX.  No allocations introduced, so shouldn't be a performance hit.
