### ISSUE TITLE
fmt: docs specify incorrect format for uint when printed with %#v

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#17322]
### What version of Go are you using (`go version`)?

go version go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build963251590=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

https://play.golang.org/p/vDgR-zpii2

### What did you expect to see?

As per the [documentation](https://golang.org/pkg/fmt/):

> The default format for %v is:
> uint, uint8 etc.:        %d, %x if printed with %#v

### What did you see instead?

unsigned integers when printed with `%#v` are formatted similar to `%#x`.

Here is a [test](https://github.com/golang/go/blob/master/src/fmt/fmt_test.go#L615) supporting it.

**Comment by quentinmit** [comment]
Can we really do anything with this at this point? I think we have to keep the current behavior to preserve backwards compatibility.

**Comment by robpike** [comment]
We just need to document it.
