### ISSUE TITLE
cmd/compile: getcallerpc ought to be intrinsified

### ISSUE THREAD

**Issue by dr2chase** [golang/go#17327]
Reasons:
- getcallerpc gets called in many places; even in assembly language, a call is a call
- the compiler has a pretty good idea of where it put the caller's PC.
- taking the address of the first parameter reduces opportunities for optimization somewhat, though of course SSA could be smarter about noescape functions.
- relying on the first parameter having an address in the caller's frame with a firm relationship to the saved return PC locks down our existing calling conventions; there are other obstacles to changing them and we might not change this part of them, but it's not a feature.

**Comment by crawshaw** [comment]
getcallerpc is on the entersyscall critical path so it may have positive effects on unexpected benchmarks.

**Comment by rsc** [comment]
If you want to do this for Go 1.8, please do it soon.

**Comment by cherrymui** [comment]
getcallerpc currently has stack barrier logic in it. Maybe do it after removing stack barrier?

**Comment by dr2chase** [comment]
This looks iffy for 1.8, but I'll see.

**Comment by josharian** [comment]
Definitely missed the 1.9 window on this. Marking 1.10Early.
