### ISSUE TITLE
go/build: permit vendoring golang.org from std without breaking users

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17326]
In #16333 a user reported that they were unable to vendor code which the Go standard library itself vendored.

To "fix" the problem for the 1.7 release, we renamed the "$GOROOT/src/vendor/golang.org" directory to "golang_org" with an underscore, so it wouldn't conflict with users.

This is slightly annoying for us to maintain in the stdlib.

We should probably fix it properly in `go/build` and/or `cmd/go`.

/cc @ianlancetaylor @rsc

**Comment by ianlancetaylor** [comment]
The standard library no longer has a top level vendor directory.  The contents have moved to `internal/x` to fix #26988 and #27285.  I think that fixes this problem, so closing.
