### ISSUE TITLE
doc: Effective Go should make it clear that values are *copied* in a range clause

### ISSUE THREAD

**Issue by Kegsay** [golang/go#17333]
Effective Go doesn't mention that the 2nd value in a `range` clause is actually a copy of that value. It appears that only https://tour.golang.org/moretypes/16 mentions this:

> When ranging over a slice, two values are returned for each iteration. The first is the index, and the second is a copy of the element at that index.

I think this is important to mention as this makes iterate-and-modify loops very error prone: https://play.golang.org/p/mq9sz3O19J

**Comment by davecheney** [comment]
Every assignment in Go is a copy, there are no exceptions to this rule.

**Comment by Kegsay** [comment]
My intention was not to imply that there are exceptions. My intention was to indicate that there are [a lot](http://stackoverflow.com/questions/15945030/change-values-while-iterating-in-golang) of [people](http://stackoverflow.com/questions/20185511/golang-range-references-instead-values) who get confused over it, and that we can be a lot clearer if we actually spell this out to people in the guides/tutorials.

**Comment by robpike** [comment]
I think Effective Go is not the place to explain that computers copy values when they make assignments.
