### ISSUE TITLE
cmd/compile: unnecessary write barriers to stack

### ISSUE THREAD

**Issue by aclements** [golang/go#17330]
There's some situation in which the compiler generates unnecessary write barriers when writing to a pointer in the current stack frame. Here's a simple script to find these (it may have false positives, but I didn't find any when flipping through them):

```shell
go tool objdump `which go` | awk '/LEAQ .*\(SP\),/ {lea=$0;next} /writebarrierptr/ && lea {if (text){print text;text=""};print lea;print} $4!="MOVQ"{lea=""} /^TEXT/ {text=$0}'
```

These are currently harmless. However, with the hybrid barrier it's important not to generate these because the stack slot being written to may be dead prior to this write and currently contain junk (such as a pointer to a dead object).

I flipped through several of these but there wasn't an obvious pattern to me.

/cc @dr2chase @cherrymui @randall77

**Comment by cherrymui** [comment]
In gc/ssa.go:
```
		if rhs != nil && rhs.Op == OAPPEND {
			// The frontend gets rid of the write barrier to enable the special OAPPEND
			// handling above, but since this is not a special case, we need it.
			// TODO: just add a ptr graying to the end of growslice?
			// TODO: check whether we need to provide special handling and a write barrier
			// for ODOTTYPE and ORECV also.
			// They get similar wb-removal treatment in walk.go:OAS.
			needwb = true
		}
```
