### ISSUE TITLE
cmd/go: go test timeout doesn't take into account count

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#17337]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

When running a large number of tests or benchmarks, the test timeout in src/cmd/go/test.go is hard coded to 10 minutes

This means that the `-test.count` parameter is not taken into account, when in fact it should be.

**Comment by quentinmit** [comment]
You can already override the timeout with `-timeout`. I don't think it makes sense to just multiply the `-timeout` by `-count` because you'd very quickly get into unfeasibly long timeouts.

**Comment by carl-mastrangelo** [comment]
@quentinmit In the case of benchmark, I really do want to wait the full length.  Some benchmarks have to be run with high counts to get good accuracy.  It's annoying to add the timeout every time.

Please reconsider opening this bug.

**Comment by dsnet** [comment]
Duplicate of #12446

**Comment by davecheney** [comment]
A possible workaround is to use `go test -c`, then run the resulting
`$PKG.test -test.timeout=NNNs -test.count=NNN` binary.

**Comment by carl-mastrangelo** [comment]
@davecheney it's risky, because if the timer is even off by a little, it would first too early (and also ignores the -test.benchtime).  It would be better to not have a work around at all, and the test runner do the right thing by default.

My own version was just to set the timeout to 20 hours, which is arguably not good either.  @dsnet mentioned in his bug that it isn't straightforward, but I think it should still be solved (by me maybe, if there is agreement that it's a problem).
