### ISSUE TITLE
consistent predictable error messages

### ISSUE THREAD

**Issue by fkluknav** [golang/go#17334]
A long build process involving lots of dependencies often fails without any obvious error message at the end.  Sometimes, reading of loooooong logs line by line is necessary to identify the error. It would be great if every error message started with something fixed, like gcc-style "Error: ...". That would allow to find error messages in build logs easily. 

### What did you do?
https://play.golang.org/p/GMT52cBqGe

### What did you expect to see?
tmp/sandbox995579036/main.go:8: Error: undefined: fmt.Printn

### What did you see instead?
tmp/sandbox995579036/main.go:8: undefined: fmt.Printn

**Comment by bradfitz** [comment]
We write it to stderr, which is a special place just for errors. We also use the "standard" filename-colon-line-[colon-column]-colon-space prefix.

I don't think saying "Error: " adds anything useful. We don't have warnings, so anything to stderr is an error.

I recommend you redirect stderr to a file for inspection later if your build is that long and wide.

**Comment by fkluknav** [comment]
Build systems quite often mix stdout and stderr, the rationale being that stderr torn from stdout into a separate log file usually does not make sense because of lost context.
filename-colon-line-[colon-column]-colon-space is good to read with human eyes but quite unwieldy to search for.
