### ISSUE TITLE
go get cmd

### ISSUE THREAD

**Issue by BafFlynN** [golang/go#17349]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ss/CODE/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/32/p3cxd_xd06ddxlxxn8mwb52r0000gn/T/go-build243772216=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I went into my project dir. ran the cmd `go get ./...` 
then went to run go test 

### What did you expect to see?
It should of run the test

### What did you see instead?

but the go get ./... apparently skips over tests.

**Comment by bradfitz** [comment]
`go help get`
...
`
The -t flag instructs get to also download the packages required to build
the tests for the specified packages.
```

**Comment by BafFlynN** [comment]
whoops sorry.
