### ISSUE TITLE
runtime: performance improvements for memclr on ppc64x

### ISSUE THREAD

**Issue by laboger** [golang/go#17348]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +a0d83eb Wed Oct 5 12:44:29 2016 -0500 linux/ppc64le

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 ppc64le

Looking at performance of runtime benchmarks and found that memclr could be improved on ppc64x.

**Comment by bradfitz** [comment]
This needs more details. What is the code for memclr now, and what should it be?

**Comment by laboger** [comment]
The file to be changed is memclr_ppc64x.s.  The change will be similar to what is currently done in memmove_ppc64x.s, where loops are unrolled to improve performance.

For example when it can be determined that chunks of 32 bytes are being cleared:

loop:
std r0, 0(r3)
std r0, 8(r3)
std r0, 16(r3)
std r0, 24(r3)
bc loop

Does much better than 

loop:
stdu r0,8(r3)
bc loop
