### ISSUE TITLE
a nil interface != nil

### ISSUE THREAD

**Issue by hzmnet** [golang/go#17346]
```
package main

import(
	"fmt"
)
type itest interface{
	Error() string
}

type test struct{
}

func (e *test) Error() string {
	if e==nil{
		fmt.Println("e is nil")
	}
	return "erre"
}

func X()*test{
	return nil
}
func Y()itest{
	return X()
}
func main(){
	var i interface{}
	i=nil
	err:=Y()
	fmt.Println("Hello World" ,i,err,err.Error(),err==nil)
}
```
## **How can check err whether nil or not. in this situation it always not nil**

**Comment by dominikh** [comment]
Please see https://golang.org/doc/faq#nil_error for why it is not nil. Also, the issue tracker is for issues and features only. Please use one of the forums (https://golang.org/help/) for asking for help.
