### ISSUE TITLE
spec: is package name _ allowed; compiler refuses it

### ISSUE THREAD

**Issue by golang101** [golang/go#17358]
We all know _ can be used as constant and variable identifier.
And it looks using _ as function name is also allowed, but a function named with _ is almost useless.
The only usefulness I can image is put some interface assertions in it to check if a concrete type implements an interface to avoid allocing memory in package scope.

```go
package main

type I interface {F()}

type T [2^32]int

func (T) F(){}

func _ (){var _ I = T{}}
  
func main(){
	// _() // compiling error: cannot use _ as value
}
```

**Comment by mdempsky** [comment]
https://golang.org/ref/spec#Declarations_and_scope

> The blank identifier may be used like any other identifier in a declaration, but it does not introduce a binding and thus is not declared.

Writing "func _() {}" is valid, but does not declare a function.  That's why you can't call it as "_()".

Just like writing "var _ I = T{}" doesn't declare a variable named "_".

The spec also explicitly says PackageName can't be "_".

I don't see a bug here.

**Comment by golang101** [comment]
@mdempsky, in the same link your provide, it says:

> The package clause is not a declaration; the package name does not appear in any scope. Its purpose is to identify the files belonging to the same package and to specify the default package name for import declarations.

**Comment by golang101** [comment]
@mdempsky, and your claim "Writing "func () {}" is valid" is wrong.

**Comment by mdempsky** [comment]
@golang101 Sorry, but I don't understand what you're arguing.  Do you think there's a bug in the compiler, spec, or both?

If there's a compiler bug, please give an example input, what the compiler does, and what you think the compiler should do instead.  (You gave an input above, but didn't say what you think it *should* do.)

If there's a spec bug, please quote the relevant sections and explain why you think they're wrong.

**Comment by golang101** [comment]
Either spec or compiler has a bug. Now they are not consistent. 
For the following one line file, assume it in the foo folder under GOPATH:
> package _
"import foo" will cause compiling error.
But this file is valid by spec.

If compiler does right here, the in the https://golang.org/ref/spec#Package_clause section, the definition of PackageName should be changed.

**Comment by mdempsky** [comment]
A file containing

    package _

is not valid.  Like I said above, [the Go spec says](https://golang.org/ref/spec#Package_clause):

> The PackageName must not be the blank identifier.

**Comment by golang101** [comment]
ok, I didn't notice that line. :)
