### ISSUE TITLE
x/sys/unix appears to be broken

### ISSUE THREAD

**Issue by JackKnifed** [golang/go#17352]
### What version of Go are you using (`go version`)?

```
go version go1.7 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jack/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

On that arch, it looks like there's a broken build:

```
$ go get -u golang.org/x/sys/unix
# golang.org/x/sys/unix
./syscall_linux.go:83: undefined: unlinkat
```
Further, if you `go test` `HEAD` it does the same.

I believe that line 83 of `syscall_linux.go` should be?

```
	return Unlinkat(AT_FDCWD, path, AT_REMOVEDIR)
```

But I'm not the one to figure that out. Besides, it looks like this is auto-generated anyway?

Additionally, it looks like this is present only in `1f5e250e1174502017917628cc48b52fdc25b531` - the previous commit `c47cb47a3064eaebd36bc07aeb9a6e4b22681103` seems to test just fine. Additionally, based on that commit, this only looks to be a few hours old?

**Comment by bradfitz** [comment]
Reverting.

**Comment by bradfitz** [comment]
Fixed in https://golang.org/cl/30491 (in which I messed up the github issue reference syntax)
