### ISSUE TITLE
Go language should support AVR and ARC architectures

### ISSUE THREAD

**Issue by viscropst** [golang/go#17353]
Golang will be used in the IOT solution,But the low-price and low-power chips with ARC and AVR architectures  will be more popular. So the AVR and ARC version of golang is necessary in IOT development of golang.

**Comment by minux** [comment]
Supporting 8-bit microcontrollers like AVR will be very hard as the limited
address space and the lack of MMU makes supporting a modern garbage
collected language almost impossible.

I don't think AVR32 is ever going to complete with ARM and RISC-V, and
Atmel itself seems to have abandoned the AP family of AVR32.

Right now, Go only supports platforms with enough high-level OS support:
threads and virtual memory management are a must, so extending to support
bare-metal embedded systems will be a lot of work.

Supporting ARC with Linux is possible though. But I find architecture
information on ARC to be a little sparse and we'll likely be limited by the
availability of hardware for Go builders.

**Comment by bradfitz** [comment]
I'm closing this in favor of more focused bugs later with more details.
