### ISSUE TITLE
Two logically equivalent switch structures: one wont compile

### ISSUE THREAD

**Issue by ragnese** [golang/go#17351]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rob/work/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build437698452=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
Tried to handle a type assertion from interface{} to a slice of custom types and allow multiple custom types in one case block. The following code works. I make each []CustomType its own case:
https://play.golang.org/p/K94vyFfARt

Notice, starting on line 36, that the two cases have identical bodies. If I collapse them into one case, it will not build:
https://play.golang.org/p/7eLDvIjANf

### What did you expect to see?
I expected the second version to build and return identical results to the first version.

### What did you see instead?
Second version wont build, despite being provably equivalent.

Thank you for your time and I hope I submitted this correctly. Please let me know if I can elaborate further.

**Comment by bradfitz** [comment]
Working per the spec. See https://golang.org/ref/spec#Type_switches

The type of your variable `s` on line 39 is `interface{}`, so you can't range over it, because it's not a slice.

**Comment by ragnese** [comment]
I see. Is anyone willing to waste their time explaining why this choice was made? It seems to go against the principal of least astonishment. It would be less surprising if the compiler just "unrolled" the cases and compiled them as though each one was written independently. Is there some optimization or special feature one can take advantage of with the current spec being the way it is?

**Comment by davecheney** [comment]
Would you expect this to compile ? https://play.golang.org/p/V-MFgV5Qfp

**Comment by ragnese** [comment]
No, of course not! Because it's also invalid Go if you split the case up: https://play.golang.org/p/JIntQ3pis3

My point is that in my example, splitting the case works when they have identical bodies and logically that implies that it should work when the cases are lumped together. I can't think of a single case where my proposal is not better than the current spec. If one of your cases wouldn't work on the body, then of course it shouldn't compile. If all of your cases *would* work on the body, then it should compile!

What I'm arguing for is that the compiler should automatically unroll/copy+paste the grouped cases for us and then compile *that*. 

The compiler doing something like that is not unheard of, either. Take, for example, automatic pointer dereferencing- that's basically the compiler inserting a \*() for us.

**Comment by extemporalgenome** [comment]
That behavior couldn't change before Go2. I agree that the unrolling and
"only if all are valid" behavior is compelling, but I suspect it'd be
increasingly difficult to make the case body valid for all types in
anything but trivial cases, and without generics the actual usefulness of
unrolling in practice is limited -- what do you do with the result of
processing, for example, and how would you avoid having to rely on empty
interfaces anyway?

**Comment by ragnese** [comment]
Well, the logic wouldn't be "unroll only if all are valid", the logic would be "always unroll grouped cases". Then the compile can fail/succeed as it would have if the author had written the cases individually.

I can see how the use cases may be pretty limited, but it would make writing functions that take "slices of any type that satisfies an interface" (disguised as interface{}) much nicer.

I stumbled across the behavior when writing some code that takes slices of one of several types and stores each of those into a database. But each type has a slightly different way of being stored, and objects that are not one of those types should not get stored at all.

**Comment by extemporalgenome** [comment]
I think we're on the same page with what you mean by "grouped cases." My
previous comment was written with that in mind.

**Comment by ragnese** [comment]
Ah. You're right. I reread your comment and it does seem like we're on the same page about that.
