### ISSUE TITLE
x/oauth2:  TestExchangeRequest_JSONResponse_Expiry is broken on Go 1.8

### ISSUE THREAD

**Issue by dsnet** [golang/go#17363]
Using `3c3a985cb79f52a3190fbc056984415ca6763d01` of `oauth2`.

A change introduced in https://golang.org/cl/18692 expanded upon the errors returned by the `json` package to be more informative about where the error occurred.

This breaks the oauth2 package, which does direct comparison on specific errors, which I find to be fairly brittle. In fact, when Go 1.5 was released, this code broke, @bradfitz fixed it in golang/oauth2@c58fcf0ffc1c772aa2e1ee4894bc19f2649263b2, but I that doesn't solve the deeper issue that the test is just brittle. We could adjust it again for Go1.8, but it seems to be just a bad test.

Does anyone object to just removing the exact errors and simply checking whether the test passes or fails?

Failure:
```
$ go.dev test golang.org/x/oauth2
--- FAIL: TestExchangeRequest_JSONResponse_Expiry (0.01s)
	oauth2_test.go:249: Error = json: cannot unmarshal bool into Go struct field tokenJSON.expires of type json.Number; want json: cannot unmarshal bool into Go value of type json.Number
	oauth2_test.go:249: Error = json: cannot unmarshal object into Go struct field tokenJSON.expires of type json.Number; want json: cannot unmarshal object into Go value of type json.Number
FAIL
FAIL	golang.org/x/oauth2	0.027s
```

/cc @bradfitz @rakyll @adg 

Related to #11811

**Comment by rakyll** [comment]
Yes, please remove the error string comparisons. These are mostly coming from the legacy repo's tests and needs to be cleaned up.
