### ISSUE TITLE
net/http: Add missing tests for parsePostForm 

### ISSUE THREAD

**Issue by asticode** [golang/go#17368]
@bradfitz since https://github.com/golang/go/issues/14655 has been reverted I think that would be wise to patch tests as well in TestPostQuery and TestPatchQuery with use cases mentionned in https://go-review.googlesource.com/#/c/30454/ and https://go-review.googlesource.com/#/c/30470/ so that those cases are not forgotten in the future. What do you think ?

**Comment by bradfitz** [comment]
Sounds good.
