### ISSUE TITLE
x/build: set up WSL Windows Subsystem For Linux (Linux-on-Windows) builder

### ISSUE THREAD

**Issue by quentinmit** [golang/go#17365]
Even if it's not a first-class port, it's useful to know if/how it's broken.

**Comment by bradfitz** [comment]
I'd prefer a Windows 10 builder (or "Windows Server 2016") first, which we don't even have.

But it's not offered on GCE yet: https://cloud.google.com/compute/docs/instances/windows/#windows_server (only 2008 and 2012).

So unless we want to run builders on Azure or our Mac VMWare cluster, this is blocked for now.

**Comment by quentinmit** [comment]
@bradfitz
Windows Server 2016 is now available on GCE

**Comment by quentinmit** [comment]
However, more relevantly for this bug, Windows Server 2016 does not support Linux on Windows yet.

**Comment by quentinmit** [comment]
I ran `./run.bash -no-rebuild` and the output is attached here. Obviously, we have a ways to go. @aclements thinks many of the failures may be due to our signal handling, where we apparently modify `siginfo_t` and expect that to control where we return from the signal handler.
[go-run.txt](https://github.com/golang/go/files/542681/go-run.txt)

**Comment by bradfitz** [comment]
"We" don't have a ways to go. We target Linux.

**Comment by ianlancetaylor** [comment]
Yes, what we do is modify the stack to look like a call to `runtime.sigpanic`, and then set the stack pointer and PC in the `ucontext_t` structure passed to the signal handler.  When we return from the signal handler, we expect that to execute the `sigreturn` system call which should then re-enter the user program with the stack pointer and PC set to the values in the `ucontext_t` (on some systems we execute `sigreturn` directly).  On tip this is done in `sigctxt.preparePanic`, which has CPU-specific versions in signal_GOARCH.go and for modifying the `ucontext_t` struct relies on support in signal_GOOS_GOARCH.go.

Looking at your log that is at least partially working.  I see that the signal handler is indeed returning to `sigpanic` as it should.  What seems to be failing is that `g.sigcode0` does not have the expected value in `sigpanic`.  That field is set from the `si_code` field of the `siginfo_t` passed to the signal handler.  If you want to pursue this further, change `sigpanic` to print out the `g.sigcode0` field.

**Comment by quentinmit** [comment]
@bradfitz: Agreed, this is mostly Microsoft's problem, not ours. I think we should have the goal of Go running on Linux-on-Windows, and we should invest (some) time in debugging problems with that configuration. If the problem is caused by our code, we should change our code. If the problem is a bug in the Windows kernel, we should file a bug upstream and not work around it in Go. Likely most/all of the test failures are kernel bugs, but we should at least do the debugging to find out what the kernel bugs are so we can file issues upstream.

**Comment by bradfitz** [comment]
> If the problem is caused by our code, we should change our code. 

I think by definition is can not be a problem with our code, ever.

Microsoft has committed to emulating Linux, which isn't a spec. We're targeting Linux, not a spec. If our Linux builders are passing, it's not our fault.

So the onus is on Microsoft to forever play catch-up and react to Linux differences.

But I agree we can help report bugs to Microsoft, and it would be nice to see it work.

**Comment by peterGo** [comment]
@bradfitz Actually it's Ubuntu on Windows by Canonical.

[Ubuntu on Windows – The Ubuntu Userspace for Windows Developers](https://insights.ubuntu.com/2016/03/30/ubuntu-on-windows-the-ubuntu-userspace-for-windows-developers/)

[Howdy, Windows! A Six-part Series about Ubuntu-on-Windows for Linux.com](https://insights.ubuntu.com/2016/08/09/howdy-windows-a-six-part-series-about-ubuntu-on-windows-for-linux-com/)

**Comment by bradfitz** [comment]
@peterGo, I don't care about their marketing department. They implement the Linux system calls. There's nothing specific to Ubuntu here other than marketing.

**Comment by bradfitz** [comment]
Update: we have Windows Server 2016 builders now. Maybe this is easier with that?

Or maybe we need to wait for the Nano server builders? #15287

/cc @johnsonj

**Comment by quentinmit** [comment]
@bradfitz My understanding is that Linux-on-Windows is not yet available for Windows Server 2016, because it's "not intended for server use".

**Comment by bradfitz** [comment]
Hah. Interesting.

**Comment by johnsonj** [comment]
[src](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-windows-skus-is-wsl-included-in)

I wonder if there's a workaround to enable the feature? I'm not sure if we can run desktop SKUs on GCP.

**Comment by johnsonj** [comment]
And now that's going to change: [WSL on Windows Server](https://blogs.technet.microsoft.com/hybridcloud/2017/05/10/windows-server-for-developers-news-from-microsoft-build-2017/)

**Comment by bradfitz** [comment]
Hah... I asked @bitcrazed about this at OSCON on Wednesday about an hour before this was announced. Props to Rich for managing to not spill the beans.

**Comment by bitcrazed** [comment]
Lol 😀 Thanks! Just for clarity though, WSL on server is just for admin tasks,  not for production server workloads.

**Comment by bradfitz** [comment]
@bitcrazed, yes, I heard the warning at your talk that y'all are apprehensive of people of using WSL on Server and judging its I/O performance going through layers atop NTFS.

But for running builders, we don't really care about speed much. We're mostly curious whether the Go Linux build runs on WSL unmodified, and so we can file bugs against WSL if not. That's neither an admin task nor a production server workload, but I think qualifies as a valid use.

**Comment by bradfitz** [comment]
As of today we can run WSL on Windows Server:
https://blogs.windows.com/buildingapps/2017/08/08/windows-subsystem-linux-windows-server/

(Our builders on GCE use Windows Server 2008, 2012, and 2016)

@johnsonj, want to own this bug to setup WSL builders?

**Comment by johnsonj** [comment]
Yes I do

**Comment by johnsonj** [comment]
We'll need to wait till build 16215+ hits GCE which is currently in the insiders ring

**Comment by johnsonj** [comment]
Unavailable on GCE, current build is 14393 on Server 2016 image build on 9/16. Snooze till January.

**Comment by johnsonj** [comment]
WSL is now available on GCE as the `windows-1709-core` family ([proof](https://i.imgur.com/z2neufJ.png)) so this is now possible.

**Comment by bradfitz** [comment]
We wouldn't want to "wsl pull ubuntu" (or whatever the operation is to download a distro) on every build, so I guess we'd want to get ubuntu once in the Powershell that creates the image, eh?

**Comment by johnsonj** [comment]
ACK- The baked image should have the desired distro(s) installed (~5 mins) and I think the Linux(!) stage0 setup to start on boot.

The image is different enough from the existing windows build that its probably a different environment all together. `windows-linux`, `windows-wsl`, `linux-windows`?

**Comment by alexbrainman** [comment]
@bradfitz and @johnsonj sorry to hijack this thread, but I want to ask you if current windows Go builders have SSD installed. I have 2 similar laptops with WIndows 10 - one with SSD and one without. I noticed that SSD makes laptop boot much faster, and makes computer usable quicker after reboot. Laptop without SSD always have CPU 0%, but Disk usage of around 100% well after reboot. Perhaps SSD might make our builders faster. Perhaps builders do not reboot, and reboot speed is not important.

Alex

**Comment by bitcrazed** [comment]
@bradfitz You may find these docs useful: https://docs.microsoft.com/en-us/windows/wsl/install-on-server 

Please let @tara-raj know if you bump into any unexpected WSL issues.

**Comment by mengzhuo** [comment]
@johnsonj Hi, any news?

**Comment by johnsonj** [comment]
Thanks for the ping @mengzhuo ! 

I'm unassigning as I am not actively working on this.

**Comment by mengzhuo** [comment]
@bradfitz @bcmills Could you guys assigned this issue to me? I've got a spare Win10 NUC for this builder.

**Comment by bcmills** [comment]
@mengzhuo, see http://golang.org/wiki/DashboardBuilders#how-to-set-up-a-builder for setup instructions; you'll need to coordinate with @golang/release to get a builder key.

**Comment by mengzhuo** [comment]
@bcmills I've send the request on golang-dev.

**Comment by cagedmantis** [comment]
@mengzhuo I've responded to you via email with the host and private builder key. A list of next steps are included in the email as well.

**Comment by mengzhuo** [comment]
@cagedmantis Hi, I've uploaded 2 CLs for adding this builder.

The builder is now runing the build service and ready to go :)

**Comment by mengzhuo** [comment]
I've submitted builder to repo, however I found binary from googlesource still end up like old one. Is there any progress I'm missing?

```Nov 25 08:57:07 PN50 stage0[167743]: 2020/11/25 08:57:07 buildlet starting.
Nov 25 08:57:07 PN50 stage0[167743]: 2020/11/25 08:57:07 Dialing coordinator farmer.golang.org:443 ...
Nov 25 08:57:17 PN50 stage0[167743]: 2020/11/25 08:57:17 dialing proxy "proxy:8123" ...
Nov 25 08:57:17 PN50 stage0[167743]: 2020/11/25 08:57:17 Dialed coordinator farmer.golang.org:443.
Nov 25 08:57:17 PN50 stage0[167743]: 2020/11/25 08:57:17 Doing TLS handshake with coordinator (verifying hostname "farmer.golang.org")...
Nov 25 08:57:17 PN50 stage0[167743]: 2020/11/25 08:57:17 Registering reverse mode with coordinator...
Nov 25 08:57:18 PN50 stage0[167743]: 2020/11/25 08:57:18 Connected to coordinator; reverse dialing active
Nov 25 08:57:18 PN50 stage0[167743]: 2020/11/25 08:57:18 Dialing coordinator farmer.golang.org:443 ...
Nov 25 08:57:28 PN50 stage0[167743]: 2020/11/25 08:57:28 buildlet reverse mode exiting.
Nov 25 08:57:28 PN50 systemd[1]: go-builder.service: Succeeded.
```

**Comment by mengzhuo** [comment]
@cagedmantis @bcmills Could you take a look?

**Comment by mengzhuo** [comment]
Ping

**Comment by bcmills** [comment]
@golang/release, is this just waiting on a `cmd/coordinator` push?

**Comment by cagedmantis** [comment]
We can plan for a deployment of the coordinator. The buildlet should connect (and maintain a connection to the coordinator without a deployment though).

**Comment by cagedmantis** [comment]
@mengzhuo The coordinator has been deployed. That builder should be up and running.

**Comment by mengzhuo** [comment]
> @mengzhuo The coordinator has been deployed. That builder should be up and running.

Thanks! It's up and testing CL now!

**Comment by oiooj** [comment]
I have talked with @mengzhuo add another WSL builder in `host-linux-amd64-wsl` pool to improve availability.

**Comment by oiooj** [comment]
The two builders for WSL are up now.
