### ISSUE TITLE
Small wording problem in go spec.

### ISSUE THREAD

**Issue by golang101** [golang/go#17377]
In the [Declarations and scope](https://golang.org/ref/spec#Declarations_and_scope) section, which says:
> A declaration binds a non-blank identifier to a constant, type, variable, function, label, or package.

Here, a more proper word for "package" is "package import", for in the same section below, it says:
> The package clause is not a declaration;  ...

**Comment by cznic** [comment]
Specs are ok. The [Import declaration](https://golang.org/ref/spec#Import_declarations) binds a non-blank identifier to a package.

**Comment by golang101** [comment]
I mean the wording is not perfect. There is no package declaration.

**Comment by cznic** [comment]
> There is no package declaration.

From the specs

> A declaration binds a non-blank identifier to a constant, type, variable, function, label, or package.

This does not say there is a package declaration. It just says what a declaration is / what a declaration does. AFAICT, it is correct.

**Comment by golang101** [comment]
Maybe it is ok, but I still following one is better:
> A declaration binds a non-blank identifier to a constant, type, variable, function, label, or import.

**Comment by golang101** [comment]
Ok, it is my English understanding problem.
