### ISSUE TITLE
compress/gzip: Missing Reader.Read doc

### ISSUE THREAD

**Issue by willfaught** [golang/go#17374]
Non-trivial method with no documentation.

**Comment by odeke-em** [comment]
/cc @dsnet.

@willfaught we recently added some examples to tip https://tip.golang.org/pkg/compress/gzip/#Reader.Read so they won't yet be on https://golang.org until the next major release, so for now perhaps that could be of use, before documentation for that method is in?

**Comment by willfaught** [comment]
Thanks. I think I figured it out, but it'll help the next person.

By examples, do you mean actual worded documentation like the rest of the methods there, or code in a doc comment, or actual example functions?

**Comment by odeke-em** [comment]
By examples, I meant snippets of runnable code in the godoc.

**Comment by willfaught** [comment]
OK

I think Read should still have its own proper godoc comment like the other methods.

**Comment by bradfitz** [comment]
We often don't document implementations of common interface methods, unless there's something notable to say.

Does this reader do something special over a typical `io.Reader`?

**Comment by dsnet** [comment]
> Does this reader do something special over a typical io.Reader?
Nope. 

I'm not opposed to documenting it either, though.

@odeke-em, want to write a single documentation sentence for it?

**Comment by odeke-em** [comment]
@dsnet thanks. For sure I'd love to do that. If it is urgent please go ahead and add it, otherwise I'll be able to submit a patch in about 9 hours when am back home from work.

**Comment by willfaught** [comment]
I was unsure at first whether this Read read into or out of the param. The two Readers involved confused me. In that context, I didn't recognize it as an io.Reader.Read method. Makes sense when you recognize that.
