### ISSUE TITLE
cmd/compile: optimize range comparisons like 'A' <= c && c <= 'Z'

### ISSUE THREAD

**Issue by rillig** [golang/go#17372]
### What version of Go are you using (`go version`)?

go version go1.7.1 windows/amd64

### What did you do?

https://play.golang.org/p/91drTKDs_m

### What did you expect to see?

```
andl    $-33, %eax
subl    $65, %eax
cmpb    $25, %al
setbe   %al
movzbl  %al, %eax
```

This is what GCC 5.4.0 produces. I was surprised by this code, since I only expected it to combine the `CMP + CMP` to a `SUB + CMP`. But now that I see this, I'd like the Go compiler to produce similar code.

### What did you see instead?

```
   MOVZX 0x8(SP), AX
   CMPL $0x41, AL
   JB L2
   CMPL $0x5a, AL
   JA L2
   MOVL $0x1, AX
L1:
   MOVB AL, 0x10(SP)
   RET
L2:
   CMPL $0x61, AL
   JB L3
   CMPL $0x7a, AL
   SETBE AL
   JMP L1
L3:
   XORL AX, AX
   JMP L1
```

**Comment by dsnet** [comment]
Related to #16697

**Comment by minux** [comment]
I think Go tip already does the sub+cmp trick, which should be enough. See
#16697.

**Comment by rillig** [comment]
Tested with 78a267e. The generated code uses 11 instead of 15 instructions, which is good enough for now.
