### ISSUE TITLE
x/tools/present: textarea displaying .code is always editable

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#17379]
### What version of Go are you using (`go version`)?

```
go version go1.7.1 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build108877481=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

```
git clone https://github.com/bradfitz/talk-2016-08-16-seattle-go-1.7
cd talk-2016-08-16-seattle-go-1.7
present
```

Navigate to slide 33.  Observe the textarea displaying the code.  It corresponds to the following:

```
.code src/context_http.go /START OMIT/,/END OMIT/
```

### What did you expect to see?

The textarea displaying the code shouldn't be editable (`-edit` not specified).

### What did you see instead?

All such code blocks are editable.

**Comment by robpike** [comment]
Ha! This happened to me in talk at Gophercon this year.

**Comment by campoy** [comment]
Working on adding tests to the way this works, then I'll fix the bug
