### ISSUE TITLE
cmd/compile: escape analysis too pessimistic for value-captures at closure evaluation.

### ISSUE THREAD

**Issue by dr2chase** [golang/go#17388]
```
package main

var s int

//go:noinline
func qux(ops func(i, j int) int, j int) (err *int) {
    enqueue := func(i int) *int {
        s = ops(i, j)
        return &s
    }
    err = enqueue(4)
    return
}

//go:noinline
func barfun(i, j int, ops func(i, j int) int) *int {
    s = ops(i, j)
    return &s
}

//go:noinline
func bar(ops func(i, j int) int, j int) (err *int) {
    err = barfun(4, j, ops)
    return
}

func main() {
    q := func(i, j int) int {
        return i + j
    }
    println("*qux(q,3) =", *qux(q, 3))

    b := func(i, j int) int {
        return i + j
    }
    println("*bar(b,3) =", *bar(b, 3))
}
```

The parameter `ops` to `qux` is inferred to escape, incorrectly,
compared to the equivalent rewriting into `bar` and `barfun`.
`go build -gcflags '-m -l' e2.go` yields

```
./e2.go:7: func literal escapes to heap
./e2.go:6: leaking param: ops to result err level=0
./e2.go:9: &s escapes to heap
./e2.go:6: leaking param: ops
./e2.go:18: &s escapes to heap
./e2.go:16: barfun ops does not escape
./e2.go:22: bar ops does not escape
./e2.go:28: func literal escapes to heap
./e2.go:28: func literal escapes to heap
./e2.go:33: main func literal does not escape
```

I think this results from a very simple model of closure behavior; anything captured is regarded as transmitted to any result, regardless of the actual behavior of the closure.

It is plausible that the escape behavior of closures could be modeled in the same way as the escape behavior for ordinary functions, with captured-by-value parameters treated equivalently.

**Comment by marigonzes** [comment]
I think this issue has been fixed by @mdempsky's escape analysis rewrite.

**Comment by mdempsky** [comment]
@marigonzes Thanks. Agreed, fixed and tested implicitly through the [updates to test/fixedbugs/issue17318.go](https://github.com/golang/go/commit/a9831633be548c039ada30a2fb9d7290c35ac0c0#diff-cb9f318a6fd919581a5edd80f605697a).
