### ISSUE TITLE
x/net/icmp: Can not access Echo struct fields

### ISSUE THREAD

**Issue by wgjohnson** [golang/go#17380]
### What version of Go are you using (`go version`)?
go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOOS="darwin"
GOARCH="amd64"

### What did you do?
https://play.golang.org/p/Ejp3XuTl8n
Tried to read the body of an ICMPv4 echo reply. On line 34, I'm trying to confirm that the ICMP Echo Reply received has the same data as the ICMP Echo created on line 16. 

### What did you expect to see?
Per https://godoc.org/golang.org/x/net/icmp#Echo, I expected access to `rm.Body` struct fields. 

### What did you see instead?
```bash
hosaka:Workspace wes$ go run test.go
# command-line-arguments
./test.go:34: rm.Body.Data undefined (type icmp.MessageBody has no field or method Data)
```
When line 34 is commented:
```bash
hosaka:Workspace wes$ go run test.go
2016/10/07 19:23:26 rm.Body type: *icmp.Echo
2016/10/07 19:23:26 rm.Body value: &{ID:40650 Seq:0 Data:[116 101 115 116 115 116 114 105 110 103]}
2016/10/07 19:23:26 rm.Body string: &{%!s(int=40650) %!s(int=0) teststring}
```

**Comment by mikioh** [comment]
For questions, please take a look at https://golang.org/wiki/Questions. The Body field of Message structure is an interface, so you probably need to take a look at https://golang.org/ref/spec#Type_assertions too.

**Comment by wgjohnson** [comment]
I wasn't asking a question, and thought it was an actual error. Your reply made me realize that the problem was in my code, and not in x/net/icmp. Thank you, and sorry for misusing Go's issue reporting.
