### ISSUE TITLE
x/crypto/acme/autocert: Always uses ecdsa as key for client.CreateCert

### ISSUE THREAD

**Issue by danilobuerger** [golang/go#17385]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

```
go version go1.7.1 darwin/amd64
```
### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/danilo/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s5/40xvmrjd7bbg4vglbfmtppz80000gn/T/go-build400687808=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?

```
m := autocert.Manager{
    Prompt: autocert.AcceptTOS,
    HostPolicy: autocert.HostWhitelist("example.org"),
}
s := &http.Server{
    Addr: ":https",
    TLSConfig: &tls.Config{GetCertificate: m.GetCertificate},
}
s.ListenAndServeTLS("", "")
```
### What did you expect to see?

I want to be able to specify rsa for key usage instead of ecdsa. However

```
func (m *Manager) certState(domain string) (*certState, error)
```

forces the usage of ecdsa.

**Comment by danilobuerger** [comment]
@titanous @x1ddos I saw you implemented using ecdsa here:  https://github.com/golang/crypto/commit/0e31b188fd38db611d4fbab7de9373a95f36aae5.

However, if your client is AWS Cloudfront, it won't be able to connect:

> CloudFront forwards HTTPS requests to the origin server by using the following ciphers. Your origin server must support at least one of these ciphers for CloudFront to establish an HTTPS connection to your origin.
> 
> ECDHE-RSA-AES128-SHA256
> ECDHE-RSA-AES256-SHA384
> AES256-SHA
> AES128-SHA
> DES-CBC3-SHA

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html

**Comment by bradfitz** [comment]
Closing this in favor of the more active dup #17744 bug.
