### ISSUE TITLE
spec: description of complex numbers says valid code is illegal

### ISSUE THREAD

**Issue by golang101** [golang/go#17398]
const s uint = complex(1, 0)       // untyped complex constant 1 + 0i can be converted to uint
	_ = complex(1, 2<<s)               // illegal: 2 has floating-point type, cannot shift

second line is not the fact. (go1.7.1 linux/amd64)

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't understand what bug you are reporting.  The code snippet you show does compile for me (https://play.golang.org/p/qDYvQIUugr).  Are you saying that it should not compile?

Your comment on the second line suggests that you think that `2` should have floating point type.  Why?  An unadored `2` has type `int`.  The use of the shift operator does not change that.

**Comment by golang101** [comment]
That is the what spec says, not my code.

**Comment by ianlancetaylor** [comment]
Thanks for the explanation.

**Comment by golang101** [comment]
btw, in the same example block, the comment for the last line is also not correct
> _ = imag(3 << s)                   // illegal: 3 has complex type, cannot shift

It is really illegal, but the reason is 
> invalid argument 3 << n (type int) for imag

**Comment by griesemer** [comment]
Thanks for these. I believe the `s` in the examples used to be a variable not a constant, at which point the comments would be correct. Will fix.
