### ISSUE TITLE
Spec inaccuracy: Handling panics

### ISSUE THREAD

**Issue by golang101** [golang/go#17399]
The return value of recover is nil if any of the following conditions holds:
	    * panic's argument was nil;
	    * the goroutine is not panicking;
	    * recover was not called directly by a deferred function.

In fact, the third condition is just a special case of the second one. I don't know this description is ok or not.

**Comment by ianlancetaylor** [comment]
The third condition is not a special case of the second condition.  Consider

    package main

    import "fmt"

    func F() {
	    fmt.Println(recover())
    }

    func G() {
	    defer F()
	    panic(1)
    }

    func H() {
	    defer func() {
		    F()
	    }()
	    panic(2)
    }

    func main() {
	    G()
	    H()
    }

**Comment by golang101** [comment]
Do you want to prove the recover in H will return nil? It return 2 instead.

**Comment by spenczar** [comment]
@golang101, you are mistaken. https://play.golang.org/p/jabvSNqPrZ

**Comment by golang101** [comment]
ok, get it. Never know this.

But why so?

**Comment by bradfitz** [comment]
For questions, see https://golang.org/wiki/Questions

**Comment by golang101** [comment]
@ianlancetaylor, @spenczar,
I modify the example a little, by also deferring the inner F() calling.
But the recover calling in this F still returns nil.
The 3 conditions described in spec don't cover this condition.

	package main

	import "fmt"

	func F() {
		fmt.Println(recover())
	}

	func G() {
		defer F()
		panic(1)
	}

	func H() {
		defer func() {
			defer F() // I modify this line
		}()
		panic(2)
	}

	func main() {
		fmt.Print("G(): ")
		G()
		fmt.Print("H(): ")
		H()
	}

**Comment by ianlancetaylor** [comment]
This is expected.  Please take discussion of how panic and recover work to a forum, not the issue tracker.  See https://golang.org/wiki/Questions .  Thanks.
