### ISSUE TITLE
[feature request] http module request path variables binding!

### ISSUE THREAD

**Issue by leaxoy** [golang/go#17395]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`1.7.1`

The http module is easy to build an web app with the `http.Handler`.
With the param `*http.Request` we can get a full list of request info.
But in most apps. We should get variable from path string.
For example:
`localhost:3000/user/lily/app/1`
can use `user` and `id` to bind `lily` and `1`
we can just use `http.HandleFunc("/user/{user}/app/{id}", list)` to archive here.

Please consider this for simplify the process of build a web app.
Thanks!!

**Comment by bradfitz** [comment]
There are dozens of http routers/muxes on Github. I don't foresee us adding a competing one in the standard library since we already include a minimal one. Having two would be crowded.
