### ISSUE TITLE
Multiple issues with gzip package

### ISSUE THREAD

**Issue by least-olegs** [golang/go#17397]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.6.1 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/redacted"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I tried to read gzipped stream over SSH using `gzip` package.  I'm still struggling with minimal example, but here's the gist of it:
1. Using `golang.org/x/crypto/ssh` package connect to a remote machine and execute
```
cat some-large.file | gzip -f
```
2. Set `session.Stdout` to an instance of `bytes.Buffer`.
3. Try feeding this buffer to `gzip.NewReader`

### What did you expect to see?
Gzip stream is parsed.

### What did you see instead?

1. First problem: `gzip.NewReader` is blocking - why do you try to read in this function? A workaround is to create a fake reader which will instantiate `gzip.Reader` after ensuring some data are already received.
2. Second problem: `gzip` code seems to not be able to read from stream (i.e. it wants all bytes to have been already received). This is just my guess though. See below: it panics when truncating the `bytes.Buffer`

```
panic(0xa2fec0, 0xc820c9a370)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
bytes.(*Buffer).Truncate(0xc820bf2690, 0x0)
	/usr/local/go/src/bytes/buffer.go:71 +0xbf
bytes.(*Buffer).ReadByte(0xc820bf2690, 0xf7, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:300 +0x51
compress/flate.(*decompressor).moreBits(0xc82111a400, 0x0, 0x0)
	/usr/local/go/src/compress/flate/inflate.go:719 +0x4d
compress/flate.(*decompressor).huffSym(0xc82111a400, 0xc82111a430, 0x0, 0x0, 0x0)
	/usr/local/go/src/compress/flate/inflate.go:741 +0x5b
compress/flate.(*decompressor).huffmanBlock(0xc82111a400)
	/usr/local/go/src/compress/flate/inflate.go:485 +0x46
compress/flate.(*decompressor).copyHuff(0xc82111a400)
	/usr/local/go/src/compress/flate/inflate.go:638 +0x3e
compress/flate.(*decompressor).Read(0xc82111a400, 0xc820d78000, 0x8000, 0x8000, 0xc82015b400, 0x0, 0x0)
	/usr/local/go/src/compress/flate/inflate.go:355 +0x1ae
compress/gzip.(*Reader).Read(0xc820c8c2c0, 0xc820d78000, 0x8000, 0x8000, 0x656375746f624578, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:269 +0xef
```
3. Error message in both `bytes` and in `gzip` packages are nondescript and carry very little useful information.  Eg. `"bytes.Buffer: truncation out of range"` is next to useless w/o specifying what the range was and what the index was.  Same goes for `"gzip: invalid checksum"` and `"gzip: invalid header"`, spurious `io.EOF` and other low-level non-digestable stuff.

**Comment by dsnet** [comment]
I'm going to say this as working as intended.

> 1. Set session.Stdout to an instance of bytes.Buffer.
> 2. Try feeding this buffer to gzip.NewReader

This is not safe. The SSH session will be writing to the bytes.Buffer concurrently while gzip.Reader is reading from the buffer. This is racy and I suspect that running the program with the race detector will report an error. You should be using [`io.Pipe`](https://golang.org/pkg/io/#Pipe).

> 1. First problem: gzip.NewReader is blocking - why do you try to read in this function?
That is how GZIP works. There is a header that has to be read.

> 2. Second problem: gzip code seems to not be able to read from stream
GZIP uses DEFLATE under the hood. Read only returns data when the internal dictionary is filled (~32KB or so) or if there was a special synchronization marker. These markers are only inserted if `gzip.Writer.Flush` is called or if Z_SYNCFLUSH is used in the C library.

> 3. Error message in both bytes and in gzip packages are nondescript
My guess is that the program is racy. I don't think we'll be able to provide good errors in this case.
