### ISSUE TITLE
proposal: x/crypto/acme/autocert: enforce OCSP must staple

### ISSUE THREAD

**Issue by nhooyr** [golang/go#17390]
Given we automatically staple OCSP responses, I think it makes sense to enforce OCSP must staple on all certificates. If not, I think it should at least be configurable.

It looks like a pretty simple change: https://github.com/hlandau/acme/commit/f19e7121cf52a25a2e6c35fbb4e040e08add1743

**Comment by nhooyr** [comment]
Holy, my bad. I misread my report on ssllabs.com. We're not OCSP stapling.

**Comment by nhooyr** [comment]
Actually, given OCSP must staple is standardized in RFC 7633, maybe we should staple OCSP responses and enforce OCSP must staple?

**Comment by adg** [comment]
I have no idea what this means.

**Comment by robpike** [comment]
Please send a change list for review.

**Comment by x1ddos** [comment]
@nhooyr to clarify. By "configurable" do you mean just the OCSP must stable CSR extension? Because the rest is not related to acme/autocert. It's up to your TLS server.

Configurable certs seems like a good idea to me. Maybe #17744 could also benefit from it.

**Comment by x1ddos** [comment]
Although, watch out what you wish for: https://github.com/golang/go/issues/8549. OCSP must staple should probably be "opt in" at best.

**Comment by nhooyr** [comment]
@x1ddos Precisely. But I think it'd be nice if acme/autocert also supported OCSP stapling. With OCSP must staple it actually makes things more secure.

**Comment by robpike** [comment]
If anyone wants to explain what they're talking about here, it would be appreciated. Otherwise we should close this issue.

**Comment by nhooyr** [comment]
I'll create a new issue where things are explained more clearly.
