### ISSUE TITLE
go test ./... fail when two hierarchy both use TestMain(m *testing.T)

### ISSUE THREAD

**Issue by zykzhang** [golang/go#17394]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go version go1.6.2 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxx/go:/home/xxx/go_project"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
### What did you do?

my project has some sub folder, like this:

```
project
    dir_a
        dir_d
    dir_b
    dir_c
```

all the folders have test file and `TestMain(m *testing.M)`

and I wrote a failed test at `dir_d`

I run `go test ./...` at `project/` 
and the output is **all the test pass**
### What did you expect to see?

test at `dir_d` should fiail
### What did you see instead?

all the test pass

**Comment by zykzhang** [comment]
if remove `TestMain(m *testing.M)` at `dir_d` , the `go test ./...` acts as expected

**Comment by bradfitz** [comment]
Can you share the code? Do you have a minimal reproduction example?

**Comment by alexd765** [comment]
I was unable to reproduce this on  go1.6.2 linux/amd64.

Can you verify that the test in dir_d is actually running by doing go test ./... -v

What you have described could be explained if you forgot m.Run() in TestMain in dir_d. Then the test in dir_d wouldn't run, which means all tests pass in dir_d.

**Comment by rsc** [comment]
I'm not sure what the problem is on your system, but it's likely not that there are two TestMains. Please try running each of the tests separately and see if either fails by itself:

	for pkg in $(go list ./...); do echo $pkg && go test $pkg; done

We have multiple packages in the standard library that use TestMain and we run their tests as part of one big 'go test' during every all.bash, and that works.

**Comment by rsc** [comment]
No response.
