### ISSUE TITLE
x/mobile/cmd/gomobile: code signing issue with Xcode 8

### ISSUE THREAD

**Issue by antoine-richard** [golang/go#17407]
Hello,
### What version of Go are you using (`go version`)?

`go version go1.7.1 darwin/amd64`
`gomobile commit checksum #6ea0bb5`
`Xcode 8`
### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/antoine/workspace_go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6v/sh_3nzrx4w92ky1806rt8ml00000gn/T/go-build155350486=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?

I ran `gomobile build -target=ios -x golang.org/x/mobile/example/flappy`
It used to work with Xcode 7, but it started failing after I upgraded to Xcode 8.

FYI, I proceed as I used to do with Xcode 7 to obtain a signing identity: running a Swift app from Xcode to my phone in order to get a 7-day provisioning profile (I’m not subscribed to Apple developer program). That's how i used to get rid of code signing issues.
### What did you expect to see?

I expected to see gomobile build working (as it used to with XCode 7).
### What did you see instead?

I saw the build failing with the following error:

```
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/6v/sh_3nzrx4w92ky1806rt8ml00000gn/T/gomobile-work-884184723/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Signing for "main" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** BUILD FAILED **
```

Please let me know if you need more information.

Regards,
Antoine

**Comment by samuel** [comment]
I was able to get this to work but adding "DEVELOPMENT_TEAM" to the generated project file. I'm not sure how to discover the correct value other than looking at a generated project from xcode, however. Red

```
diff --git a/cmd/gomobile/build_iosapp.go b/cmd/gomobile/build_iosapp.go
index 0b2a923..316054d 100644
--- a/cmd/gomobile/build_iosapp.go
+++ b/cmd/gomobile/build_iosapp.go
@@ -366,6 +366,7 @@ const projPbxproj = `// !$*UTF8*$!
         CLANG_WARN_UNREACHABLE_CODE = YES;
         CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
         "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
+        DEVELOPMENT_TEAM = XREDACTEDX;
         COPY_PHASE_STRIP = NO;
         DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
         ENABLE_NS_ASSERTIONS = NO;
```

**Comment by alamse** [comment]
does anyone already have solution for this ?

**Comment by xor-gate** [comment]
Problem still remains with Xcode 8.2, we are currently unable to inject the development team.

**Comment by WillyWinkel** [comment]
@samuel how did you determine you key? I did a grep -rn "DEVELOPMENT_TEAM in an ios app main folder where I did set the team to my so called Personal team. The command resulted in:

    ./GeilerScheiß.xcodeproj/project.pbxproj:418:				DEVELOPMENT_TEAM = 6G25K53CBC;
    ./GeilerScheiß.xcodeproj/project.pbxproj:432:				DEVELOPMENT_TEAM = 6G25K53CBC;
    ./GeilerScheiß.xcodeproj/project.pbxproj:447:				DEVELOPMENT_TEAM = 6G25K53CBC;
    ./GeilerScheiß.xcodeproj/project.pbxproj:462:				DEVELOPMENT_TEAM = 6G25K53CBC;
    ./GeilerScheiß.xcodeproj/project.pbxproj:476:				DEVELOPMENT_TEAM = 6G25K53CBC;
    ./GeilerScheiß.xcodeproj/project.pbxproj:490:				DEVELOPMENT_TEAM = 6G25K53CBC;

which I put in the `build_iosapp.go`. Still the same error, did I miss something out?

**Comment by asalazar0228** [comment]
Hi has anyone found a fix for this?

**Comment by fastfading** [comment]
+        DEVELOPMENT_TEAM = XREDACTEDX;   
will work  
but I still got following error when I upload to itunes connect,  any help?
ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle gopher.golang.xxxx [Payload/flappy.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

**Comment by binron** [comment]
@samuel how did you determine you key? I did a grep -rn "DEVELOPMENT_TEAM" . in an ios app main folder where I did set the team to my so called Personal team.

**Comment by malisit** [comment]
Here's the workaround I used. I first created a project named `main` using Xcode and get the `PRODUCT_BUNDLE_IDENTIFIER` and `DEVELOPMENT_TEAM` from the `project.pbxproj` file. I placed both on the `build_iosapp.go`. 
From this one, 
```
    254BB8631B1FD08900C56DE9 /* Release */ = {
      isa = XCBuildConfiguration;
      buildSettings = {
        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
        INFOPLIST_FILE = main/Info.plist;
        LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
        PRODUCT_NAME = "$(TARGET_NAME)";
      };
      name = Release;
    };

```
to this one,
```
    254BB8631B1FD08900C56DE9 /* Release */ = {
      isa = XCBuildConfiguration;
      buildSettings = {
        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
        INFOPLIST_FILE = main/Info.plist;
        LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
        PRODUCT_NAME = "$(TARGET_NAME)";
        PRODUCT_BUNDLE_IDENTIFIER = malisit.main;
        DEVELOPMENT_TEAM = development team from project.pbxproj file;
      };
      name = Release;
    };
```

Finally I ran `go install golang.org/x/mobile/cmd/gomobile` and `gomobile build -target=ios golang.org/x/mobile/example/flappy`.
It's working now!

**Comment by fastfading** [comment]
Add this should work

DEVELOPMENT_TEAM = xxxx

The big problem is not install,  but to distribute.
Can you upload it to ituneconnect ?

What is worse is that, gomobile stop developing


2017-07-25 22:50 GMT+08:00 Muhammed Ali Sit <notifications@github.com>:

**Comment by JimmyMow** [comment]
any update on this? I'm having issues even after I manually add my `DEVELOPMENT_TEAM `

```
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/mv/j9y7n05d085cr61czvz1rtr00000gq/T/gomobile-work-568640832/main.xcodeproj failed: exit status 65
=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Signing for "main" requires a development team. Select a development team in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by kruffin** [comment]
I have a fix for it, requires a few edits to allow your team and bundle IDs to be set as well as turning on the auto provisioning updates. Attached a diff, will see if i can get all the junk set up to get the patch in.

[patch.txt](https://github.com/golang/go/files/1459960/patch.txt)

**Comment by fastfading** [comment]
Could this fix be used for appstore distribution ?
There is no problem to run it on device.
But I found it hard to upload it to itunesconnect

2017-11-10 11:16 GMT+08:00 kruffin <notifications@github.com>:

**Comment by kruffin** [comment]
@fastfading I'm not sure. I would say you really want the XCode project that gets auto generated, with it you could open it up in XCode like any other project and change settings more easily.

At least that was what I thought of when wanting to configure some of the other items like supported orientations.
