### ISSUE TITLE
archive/zip: Writer should only use extended timestamps for non-zero times

### ISSUE THREAD

**Issue by dsnet** [golang/go#17403]
4c79ed5f4483f1de065ba2b409de58ae2b6907d2 caused a regression where a round-trip zip file does not preserve the same ModTime. The reason is because the logic for using extra timestamp is always applied in the Writer no matter what.

This is an issue for when the user doesn't set the ModifiedDate and ModifiedTime fields at all. Causing the Writer to convert a zero MS-DOS timestamp (gibberish) to a Unix timestamp (now gibberish) and back again. The fix is to only apply Extra timestamp only if the MS-DOS timestamp is non-zero.

See: https://github.com/golang/go/blob/4c79ed5f4483f1de065ba2b409de58ae2b6907d2/src/archive/zip/writer.go#L102-L109

/cc @mattn

**Comment by mattn** [comment]
What do you mean `same`? Timestamp in the zip file is always preserved without timezone. It was really problem.

**Comment by dsnet** [comment]
This fails on tip, but passes on Go 1.7

https://play.golang.org/p/-ckATAnaEn

**Comment by mattn** [comment]
Are you trying to fix to avoid preserve ModifiedTime=0 ModifiedDate=0 if the file already having timestamp?
