### ISSUE TITLE
Type information missing for argument of three function in package regexp

### ISSUE THREAD

**Issue by RWPearson** [golang/go#17400]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.1 - Not relevant

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64 macOS Sierra 10.12.0 - Not relevant.

### What did you do?

Documentation on package regexp ( **https://golang.org/pkg/regexp/** )

func (re *Regexp) ReplaceAll(src, repl []byte) []byte
func (re *Regexp) ReplaceAllLiteral(src, repl []byte) []byte
func (re *Regexp) ReplaceAllLiteralString(src, repl string) string
func (re *Regexp) ReplaceAllString(src, repl string) string

### What did you expect to see?

The type for **src**, is it a string or an []byte?

### What did you see instead?

Argument type is missing.

**Comment by dsnet** [comment]
For functions, you are permitted to have a list of identifiers, followed by the type. So the identifiers `src` and `repl` are followed by the type `[]byte`, which applies both preceding identifiers. This is a language feature specified in [Function types](https://golang.org/ref/spec#Function_types) section.

Working as intended.

**Comment by odeke-em** [comment]
@RWPearson in case you need to, here are some resources you can use https://github.com/golang/go/wiki/Questions to ask some questions, since we use the issue tracker to track bugs.
