### ISSUE TITLE
fmt: Printf not respecting String() method of elements of a struct

### ISSUE THREAD

**Issue by musiphil** [golang/go#17409]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7

### What operating system and processor architecture are you using (`go env`)?
play.golang.org

### What did you do?
First reported in https://groups.google.com/d/topic/golang-nuts/Upiw-xxCJxQ/discussion

If an operand of `fmt.Printf` implements method `String() string`, `fmt.Printf` respects it and uses it.
But it doesn't if an operand is a `struct` that has such an element.

https://play.golang.org/p/QJC7Q9Kpch

### What did you expect to see?
```go
Int(73) Int(73) 73
&{Int(73)} &{elem:Int(73)} &main.Box{elem:73}
…
```

### What did you see instead?
```go
Int(73) Int(73) 73
&{73} &{elem:73} &main.Box{elem:73}
…
```

In the second line of the output, none of the format specifiers (`"%v"`, `"%+v"`, `"%#v"`) calls the `String()` method of `Int`, in contrast to the first line.

**Comment by quentinmit** [comment]
This only happens if the field is unexported. If it's exported, String is properly called:

https://play.golang.org/p/STKBOnEVrb

**Comment by musiphil** [comment]
That was mentioned in the original "golang-nuts" thread quoted earlier.
But I don't see why the exported-ness of a field should affect whether String() is used or not to print that field.

**Comment by martisch** [comment]
works as expected.

reflect can not access an unexported field and thereby fmt cant either to call the String method.
https://play.golang.org/p/JPUA_FHkov

related:
https://github.com/golang/go/issues/8965

**Comment by martisch** [comment]
If there are no arguments against i think this can be closed.

That the String method of an unexported field can not be called in another package is normal behavior and fmt is another package. In general e.g. somestruct.someunexportedfield.String() is not directly callable in another package.

It is possible to define a String method on Box that has access to elem and then hands this over to fmt directly to allow for the unexported fields String method to be called:

```
func (b Box) String() string { return fmt.Sprintf("%s", b.elem) }

func (i Int) String() string { return fmt.Sprintf("Int(%d)", int(i)) }
```

**Comment by ianlancetaylor** [comment]
I wonder if we can document this in some way that makes sense.
