### ISSUE TITLE
Type information missing for argument of several function in package strings

### ISSUE THREAD

**Issue by RWPearson** [golang/go#17401]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.1

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64 macOS Sierra 10.12.0

### What did you do?

Looked at documentation for package strings ( **https://golang.org/pkg/strings/** )

### What did you expect to see?

Argument types for all functions.

### What did you see instead?

func Compare(**a**, b string)
func ContainsAny(**s**, chars string) bool
func ContainsAny(**s**, chars string) bool
func Count(**s**, sep string) int
func EqualFold(**s**, t string) bool
func HasPrefix(**s**, prefix string) bool
func HasSuffix(**s**, suffix string) bool
func Index(**s**, sep string) int
func IndexAny(**s**, chars string) int
func LastIndex(**s**, sep string) int
func LastIndexAny(**s**, chars string) int
func Replace(**s**, **old**, new string, n int) string
func Split(**s**, sep string) []string
func SplitAfter(**s**, sep string) []string
func SplitAfterN(**s**, sep string, n int) []string
func TrimPrefix(**s**, prefix string) string
func TrimSuffix(**s**, suffix string) string

**Comment by dsnet** [comment]
See my response on #17400.
