### ISSUE TITLE
html/template: Spamming error

### ISSUE THREAD

**Issue by bep** [golang/go#17414]
See https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/html/template/template.go#L83

* This error isn't very useful if you have 100s or 1000s of templates
* If I really need that debug info, I will call `DefinedTemplates` myself
* One could even argue that this is a `DDoS`  "invitation" in certain situations

https://github.com/spf13/hugo/issues/2343

**Comment by rsc** [comment]
Going to try sending a CL and see what people think.
