### ISSUE TITLE
cmd/go: --buildmode plugin fails: cannot handle R_TLS_IE

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#17415]
### What version of Go are you using (`go version`)?

    go version devel +2287296 Wed Oct 12 08:03:00 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOOS="linux"
    GOPATH="/home/rog/src/go"
    GOTOOLDIR="/home/rog/go/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build045198637=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"

### What did you do?

    go build -buildmode plugin tst.go

where tst.go was:

    package main
    func main() {}
    var Foo = 99

### What did you expect to see?

A built plugin binary.

### What did you see instead?

    # command-line-arguments
    2016/10/12 10:58:11 cannot handle R_TLS_IE (sym runtime.memhash8) when linking internally

**Comment by ianlancetaylor** [comment]
I think the bug here is that the error message is not very good.

A plugin that does not export any symbols, which requires using `import "C"`, is not very useful.

**Comment by quentinmit** [comment]
@ianlancetaylor Where does this use `import "C"`? I see an exported symbol, "Foo".

**Comment by ianlancetaylor** [comment]
I'm sorry, you're right, I got confused between this and  -buildmode=c-shared.

Seems like -buildmode=plugin needs to force an external link, probably by changing `mustLinkExternal` in cmd/link/internal/ld/config.go.

**Comment by crawshaw** [comment]
Agreed. Sending a CL.
