### ISSUE TITLE
x/crypto/poly1305/sum_arm.s: #include "textflags.h"

### ISSUE THREAD

**Issue by bytex64** [golang/go#17422]
### What version of Go are you using (`go version`)?

1.7.1

### What operating system and processor architecture are you using (`go env`)?

iOS and Android on arm/arm64

### What did you do?

Attempted to compile a program using golang.org/x/crypto

### What did you expect to see?

Successful compilation.

### What did you see instead?

```
../../gopath/src/golang.org/x/crypto/poly1305/sum_arm.s:6: #include: open /usr/local/go/pkg/include/textflags.h: no such file or directory
```

Seems to be a typo. The companion amd64 version includes `"textflag.h"`, which works fine.

**Comment by quentinmit** [comment]
@bradfitz Is this fixed now? What work remains?

**Comment by bradfitz** [comment]
Yup, fixed.
