### ISSUE TITLE
Enable full rebuild of standard library for cross-compiling

### ISSUE THREAD

**Issue by networkimprov** [golang/go#17426]
Distro: Arch Linux
Version: go1.7.1 linux/amd64
go env:
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build554928497=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

I wish to rebuild the standard library for cross-compiling, following advice from
http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

When logged in as root in empty directory...

This gives an error:
\# GOOS=linux GOARCH=arm go install -a -v -p 4
can't load package: package .: no buildable Go source files in /home/x/y

This only rebuilds part of the stdlib:
\# GOPATH=/home/x/y GOOS=linux GOARCH=arm go install -a -v -p 4 github.com/x/y

There should be a way to rebuild the whole stdlib for a different architecture.

**Comment by bradfitz** [comment]
This is no longer necessary. Those instructions are old. Let's move this to https://golang.org/wiki/Questions

**Comment by davecheney** [comment]
`env GOOS=linux GOARCH=arm go install -v std` is the command you want.

**Comment by networkimprov** [comment]
@davecheney thanks. I looked and looked for 'std'.

If the docs made [packages] a link to the package-lists section where `go xyz ... [packages]` appears, I would have found that answer quickly. How about re-titling and reopening this issue to that effect?
