### ISSUE TITLE
FanOut pattern as a function

### ISSUE THREAD

**Issue by anderejd** [golang/go#17420]
Hi, this is a proposal for a new function in the sync package.

This is a small pattern I use with WaitGroup to wait for a group of go routines that I repeat for almost every go program I write. I have been copy-pasting it around until recently, now it's tiny library:
https://github.com/anderejd/syncext

Is there something similar in the standard library already? Am I going about this all wrong? It's just 14 lines of code, but to me that means 14 lines less to write every time I want to use this pattern.

The details of the proposal including a use case is in README.md in the repos.

Any kind of feedback welcome! :)

**Comment by bradfitz** [comment]
I think this is fine in github. See https://golang.org/doc/faq#x_in_std

We don't add things to the standard library lightly.

Thanks for the offer, though.

**Comment by anderejd** [comment]
Closed one hour after opening, that's dissapointing. I was hoping for a discussion.

**Comment by minux** [comment]
The proposed FanOut is not as useful as hardcoded
version because the control inversion issue.

Usually when I write the fan out pattern, I want the
current goroutine to wait, rather than having a dedicated
goroutine to wait for the completion.

**Comment by anderejd** [comment]
Hi Minux! Thanks for the feedback!

I experimented with a blocking variant of the FanOut function in the library too, but I found that in my case the caller code could be reduced further with the callback variant. 

Would you like to provide some example code for your use case?
