### ISSUE TITLE
spec: Type assertions

### ISSUE THREAD

**Issue by golang101** [golang/go#17428]
In the "Type assertions" section, there is an example listed as following:

	type I interface { m() }
	var y I
	s := y.(string)        // illegal: string does not implement I (missing method m)
	r := y.(io.Reader)     // r has type io.Reader and y must implement both I and io.Reader

The comment for the last line is weird. y is a value, how values can implement interfaces?

And here, using io.Reader as a demo is not good, for io.Reader has no m method.

**Comment by cznic** [comment]
> The comment for the last line is weird. y is a value, how values can implement interfaces?

```go
type t int

func (i t) m() { fmt.Println(i) }
```

> And here, using io.Reader as a demo is not good, for io.Reader has no m method.

That's why the comment says `and y must implement both I and io.Reader`.

```go
type t struct {
        io.Reader
}

func (t t) m() { t.Read(nil) }

var _ I = t{} // ok
```

**Comment by bradfitz** [comment]
Let's move language questions to the mailing list.

**Comment by golang101** [comment]
@cznic, I think it is ok to say "a type Y implements I", but not ok to say "a value y implements I".

**Comment by golang101** [comment]
@bradfitz @cznic, I strongly recommend to reopen this issue, for this example in the go spec is too bad. It is not professional.  

The comment "y must implement both I and io.Reader" is wrong. For, in fact, the concrete type of y is not essential to implement io.Reader.

**Comment by ianlancetaylor** [comment]
It compiles but it will not run.

Please discuss on the mailing list, not here.

**Comment by golang101** [comment]
@ianlancetaylor, I have create a discussion here: https://groups.google.com/forum/#!topic/golang-nuts/7Tz2UamO30c

I know the type assertion mechanism well, I just think the example in the spec is not professional, for some reasons:
1. the example make people think y == nil
1. the example doesn't make it clear what "y must implement both I and io.Reader" means, it means to compile, or to avoid panicking?

So here I made a better example. Certainly, if you go team don't think so, just ignore it.

	type I interface { m() }
	var y I

	func f(y I) {
		s := y.(string)        // illegal: string does not implement I (missing method m)
		r := y.(io.Reader)     // r has type io.Reader and y must implement io.Reader to avoid panicking
		...
	}

**Comment by ianlancetaylor** [comment]
CC @griesemer see previous comment.

**Comment by ianlancetaylor** [comment]
@golang101 I would like to gently suggest that your suggestions will be appreciated more if you avoid saying things like "not professional."  That seems like an unnecessary insult.  Everything can always be improved.  It's not necessary to say that the current thing, whatever it is, is bad.  It's sufficient to say that it could be better.  Thanks.

**Comment by golang101** [comment]
sorry, I have no any intention to make an insult here. In fact, most parts of go spec are excellent. 
My English is not good so I often use improper word in my comments.  Here, for "not professional", I mean "not good". :D
