### ISSUE TITLE
proposal: make "_ := x" legal if there is no harm to do so.

### ISSUE THREAD

**Issue by golang101** [golang/go#17429]
Reasons:
1. "var _ = x" is legal.
2. Often, in debugging/developing a program, programmers often change a line like 
> _, newV, _ := x, y, z

to
> _, _, _ := x, y, z

and change them back and forth for several times.

But " _, _, _ := x, y, z" is illegal, programmer must change it to "_, _, _ = x, y, z". 
This may be a small inconvenience, but it is really annoying.

**Comment by bradfitz** [comment]
Dup of #377

**Comment by golang101** [comment]
@bradfitz, sorry, I can't understand how the two issues are related.

**Comment by kostix** [comment]
@golang101 , please see [this comment](https://github.com/golang/go/issues/377#issuecomment-66049391) from #377.
