### ISSUE TITLE
fmt: exhibits strange behaviour when format strings contain spaces

### ISSUE THREAD

**Issue by echlebek** [golang/go#17436]
It seems that when spaces are inserted in a format string like %#v, some slightly surprising formatting occurs.

### What version of Go are you using (`go version`)?
Go 1.7.1 (on the Go playground)

### What operating system and processor architecture are you using (`go env`)?
The Go playground.

### What did you do?
https://play.golang.org/p/2jeholpKdb

### What did you expect to see?
I would expect to see errors from fmt complaining about invalid format strings, or a literal representation of the string without the formatting applied, or the space simply be ignored. Instead, the formatting is applied in an inconsistent way.

### What did you see instead?

```
main.Compound{C:(*main.Compound)(0x1040e130), A:5, B:"foo"}
main.Compound{C:(*main.Compound)( 0x1040e130), A: 5, B:"foo"}
main.Compound{C:(*main.Compound)( 0x1040e130), A: 5, B:"foo"}
```

**Comment by ianlancetaylor** [comment]
Note that space is a valid and documented flag character.  The docs say  leave a space for elided sign in numbers (% d); put spaces between bytes printing strings or slices in hex (% x, % X)".

I think the output shown above is correct, so I'm going to close this.
