### ISSUE TITLE
cmd/link: 'index out of range' when build with buildmode=plugin

### ISSUE THREAD

**Issue by mateuszdyminski** [golang/go#17443]
### go version

> go version devel +d13fa4d Fri Oct 14 03:58:15 2016 +0000 linux/amd64

### go env

> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/md/.gvm/pkgsets/master/global"
> GORACE=""
> GOROOT="/home/md/.gvm/gos/master"
> GOTOOLDIR="/home/md/.gvm/gos/master/pkg/tool/linux_amd64"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545183226=/tmp/go-build -gno-record-gcc-switches"
> CXX="g++"
> CGO_ENABLED="1"

### What did you do?
I tried to build following code:

> package main
> 
> func Test(value string) string {
>      return "test" + value
> }

by calling `go build -buildmode=plugin`

### What did you expect to see?
`go build -buildmode=plugin` should not return any error

When `func Test(value string) string` has no `string` argument:

> package main
> 
> func Test() string {
>      return "test"
> }

code compiles without any error. 

### What did you see instead?

> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> panic(0x5aa860, 0x69d560)
> 	/home/md/.gvm/gos/master/src/runtime/panic.go:527 +0x1a0
> cmd/link/internal/ld.(*deadcodepass).flood(0xc42006fce0)
> 	/home/md/.gvm/gos/master/src/cmd/link/internal/ld/deadcode.go:292 +0xdd2
> cmd/link/internal/ld.deadcode(0xc4200768f0)
> 	/home/md/.gvm/gos/master/src/cmd/link/internal/ld/deadcode.go:62 +0xdb
> cmd/link/internal/ld.Main()
> 	/home/md/.gvm/gos/master/src/cmd/link/internal/ld/main.go:186 +0x81b
> main.main()
> 	/home/md/.gvm/gos/master/src/cmd/link/main.go:55 +0x139

**Comment by crawshaw** [comment]
I believe this is #17140, which I believe is fixed by https://golang.org/cl/29692, which is waiting for review.
