### ISSUE TITLE
suggestion: invert the order of printing panics in printpanics function in runtime/panic.go

### ISSUE THREAD

**Issue by golang101** [golang/go#17452]
For example:

	package main

	func main() {
		defer func() {
			// println(recover().(int)) // 5
		}()
		
		defer panic(5)
		defer panic(4)
		defer panic(3)
		defer panic(2)
		panic(1)
	}

For above program, the final crash report is like: 

	panic: 1
		panic: 2
		panic: 3
		panic: 4
		panic: 5

	goroutine 1 [running]:

It gives people the impression that the panic 1 is more special, and the calling or recover() would return 1 if the "println(recover().(int))" line is not commented off. In fact, 5 would be returned.

Another reason for this suggestion is that the final report is like a stack trace, so inverting the orders would be better.

Not a big problem, just a small suggestion.

**Comment by ianlancetaylor** [comment]
The panic values are printed in the order in which the panics are executed.  I think anything else would be impossibly confusing.

**Comment by golang101** [comment]
@ianlancetaylor, but is there any special reason to prefix a '\t' character exception the first line?

**Comment by ianlancetaylor** [comment]
I suppose it does seem to make it a little clearer which value started the chain of panics.  The tab character dates back to when Russ initially implemented panic: https://golang.org/cl/831042 (see `printpanics` in pkg/runtime/proc.c).
