### ISSUE TITLE
proposal: golang.org/x/text/unicode/ucd package for Unicode Character Database data

### ISSUE THREAD

**Issue by nigeltao** [golang/go#17460]
I'd like to write a self-contained utility program to print what Unicode codepoints are covered by a font file. I have codepoint values (e.g. '\u0102') and I'd like to print e.g. "LATIN CAPITAL LETTER A WITH BREVE".

I'd therefore like a golang.org/x/text/unicode/ucd package for Unicode Character Database data (http://unicode.org/ucd/).

There is an existing golang.org/x/text/internal/ucd package, but it's (1) internal, and (2) currently about _parsing_ UCD files instead of exposing pre-generated tables.

There is also an existing golang.org/x/text/unicode/cldr package (CLDR, not UCD), which is not internal, and it is also about parsing. However, its package doc says "This package is inteded to be used by the table generation tools for the various internationalization-related packages." The git log for that directory ends with "The cldr package is quite low-level and probably would only for internal use if it hadn't predated the internal directory convention." Maybe we should make it internal, although that is a separate concern.

Back to a "package ucd", a strawman proposal for its API would be:

```
fmt.Println(ucd.Name('\u2603'))           // Prints "SNOWMAN".
fmt.Println(ucd.Block('\u2603'))          // Prints "Miscellaneous Symbols".
fmt.Println(ucd.HanDescription('\u4E2D')) // Prints "central; center, middle; in the midst of; hit (target); attain".
```

Other possible package names are "chardb" and "codepoints", so it would be "chardb.Name" or "codepoints.Block", but for now, I'll paint the bikeshed "ucd", consistent with the "cldr" abbreviation.

Canonical sources:
http://www.unicode.org/Public/UCD/latest/ucd/NamesList.txt
http://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip and its Unihan_Readings.txt

**Comment by bradfitz** [comment]
Seems fine to me.

**Comment by mpvl** [comment]
SGTM.  

Regarding the naming, though: is your intention to expose _all_ data in the ucd package? What about the derived and test data or data that is already exposed in other packages? If not, I am not very keen on the name ucd, as it would be akin to a Unicode equivalent of calling a package "util". Personally I would split data into functional packages, such as one for names/chardb, emoji, indic, hangul, vertical, etc. to complement the packages that already expose UCD data (norm, width, cases, bidi, etc.) The names package alone would be huge, let alone a unihan package.

Also, although the cldr package should probably be internal, it is conceivable that the ucd parser would be exposed.

**Comment by rsc** [comment]
Is ucd going to hard-code the tables as data or is it going to expect to find them at run time?

**Comment by nigeltao** [comment]
@mpvl, yeah, not all of UCD. Perhaps the bikeshed should be x/unicode/names, x/unicode/blocks, x/unicode/unihan (unihan.Description), etc. loosely based on the filenames in http://www.unicode.org/Public/UCD/latest/ucd/

**Comment by nigeltao** [comment]
@rsc hard-code the tables as (go generate'd) data.

**Comment by nigeltao** [comment]
@mpvl, looking at some Lookup functions in the existing golang.org/x/text sub-repo:

width/width.go
74:func Lookup(b []byte) (p Properties, size int) {
81:func LookupString(s string) (p Properties, size int) {
87:func LookupRune(r rune) Properties {

unicode/bidi/prop.go
61:func LookupRune(r rune) (p Properties, size int) {
85:func Lookup(s []byte) (p Properties, sz int) {
148:func LookupString(s string) (p Properties, sz int) {

(I note that width.LookupRune and bidi.LookupRune are inconsistent wrt returning a size... but that's a side conversation).

**Comment by nigeltao** [comment]
Anyway, for a concrete proposal:

A new package, golang.org/x/text/charnames. It contains one function, func Name(rune) string.

For example, charnames.Name('\u0201') returns "LATIN SMALL LETTER A WITH DOUBLE GRAVE".

**Comment by mpvl** [comment]
@nigeltao To be consistent with Go, why not runenames or runename?  The latter reeds a bit better if the intended API is to be of the form runename.Lookup(b).

Also this package is quite low-level and I would therefore not put it at top level. The most obvious place is golang.org/x/text/unicode/runename. An alternative could be golang.org/x/text/runes/runename (but I think I like the first better). Other low-level packages, like bidi, norm, and rangetables are already under x/text/unicode.

The LookupRunes should probably be made consistent, indeed.

**Comment by nigeltao** [comment]
I went with char because the C in UCD stands for Character. But I don't feel strongly either way, and I'm happy to roll with rune.

I went for names plural to be consistent with the existing golang.org/x/image/colornames package.

It's not entirely obvious to me when something is x/foo and when it's x/unicode/foo (why is looking up rune names low level and not high level??), but again, I don't feel strongly either way, and I'm happy to roll with x/unicode/runenames.

As for the function name being Lookup, that seems inconsistent with the Lookup functions in other packages, which take a []byte argument and return a size.

Calling the function Name instead of LookupRune is shorter, but again, I don't feel strongly either way, so if you prefer LookupRune, let's roll with that.

(I'm not sure if it's a good idea, but while I think of it, another possibility is to rename Lookup and LookupRune to LookupBytes and Lookup across all of the golang.org/x/text packages).

Anyway, new new proposal:

package import path is golang.org/x/text/unicode/runenames

It has one function:

func LookupRune(r rune) (name string)

**Comment by mpvl** [comment]
Admittedly, calling it Name will be consistent with language/display. In fact, this package defines a Namer interface, although it might be too contrived to make it fit in this case.
I just didn't like the stutter of runename.Name(). But I'm fine with Name, if you don't think this is an issue.
I'm also fine with runenames if you feel strongly about this and for the sake of consistency. I guess runenames.Name is less bad then runename.Name, if you go with that.

The high vs low-level is indeed somewhat arbitrary. Common vs. uncommon usage is another part of it. Or pure Unicode or not. Package width should probably go in the unicode directory too. Package cases and collate also mix in CLDR data.

What would you rename all the Lookup methods too?

**Comment by nigeltao** [comment]
(Side-track Conversation Number 1: For high vs low-level, uses UCD/CLDR or doesn't distinctions, another idea is just flatten everything, so x/text/unicode/foo becomes x/text/foo for foo in {bidi,norm}, with the presumption that anything under x/text imples Unicode, other than x/text/encoding/bar which converts to and from Unicode. Separately, x/text/unicode/cldr would become an internal package. Maybe the same for x/text/unicode/rangetable but I don't have a good sense for who uses it.)

(Side-track Conversation Number 2: To clarify renaming Lookups, I meant: s/Lookup/LookupBytes/ and s/LookupRune/Lookup/.)

As for the actual topic, a new new new proposal: golang.org/x/text/unicode/runenames and func Name(rune) string. We could take the "unicode" out of the import path pending Side-track Conversation Number 1.

**Comment by mpvl** [comment]
ST 1) I don't think it is a good idea to give up unicode now. There is a lot more to add and a flattened hierarchy would become quite large. Also, if that approach is taken, it may be good to group all shaping- and rendering-related packages into a single directory (bidi, arabshaping, vertical, etc.), but I'm not sure such a reorganization would be better. 

ST 2) I think such a renaming would be gratuitous and even undesirable. The primary focus of text is centered around bytes, second strings, then runes. It is often iffy to deal with text in units of runes, so this should be discouraged as much as possible, e.g. by making the text APIs feel like they are byte-sequence-centered foremost.  Also, the current naming is consistent with the core utf8 package. 

My preference of naming is, from most-preferred to least:
golang.org/x/text/unicode/runenames
golang.org/x/text/runes/runenames, or  // similar to language/display
golang.org/x/text/runes/names, or         // similar to language/display
golang.org/x/text/runenames

If you feel strongly about either you can go with that.  I'm okay with using the Name signature as you proposed in this case, as it is a very rune-centered package. But generally speaking lookups should be optimized for bytes in API and implementation. So I would consider this to be an exception.

**Comment by nigeltao** [comment]
@mpvl my reading of your latest comment is that we both agree with the new new new proposal. To repeat: golang.org/x/text/unicode/runenames and func Name(rune) string.

**Comment by mpvl** [comment]
@nigeltao: ack
