### ISSUE TITLE
runtime: TestLldbPython fails on macOS Sierra

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#17463]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +ad5fd28 Sat Oct 15 21:27:45 2016 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl"
GORACE=""
GOROOT="/Users/yoshiki/tools/go"
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/f30_9n8958j4ndrjyl1k7mp40000gn/T/go-build223200854=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

I tried to rebuild go with src/all.bash.

### What did you expect to see?

The build is OK

### What did you see instead?

ok  	path/filepath	0.112s
ok  	reflect	0.115s
ok  	regexp	0.129s
ok  	regexp/syntax	0.353s
--- FAIL: TestLldbPython (4.38s)
	runtime-lldb_test.go:182: Unexpected lldb output:
		Created target
		Created breakpoint
		Process launched
		Hit breakpoint
		no intvar
FAIL
FAIL	runtime	40.270s
ok  	runtime/debug	0.018s

**Comment by mikioh** [comment]
Looks like this issue happens only on macOS 10.12 Sierra.

**Comment by quentinmit** [comment]
I'm able to repro this. TestLldbPython is skipped by default; you need to enable developer mode with `DevToolsSecurity -enable` before it will run.

@bradfitz, presumably this is why we're not failing on the buildbots. Can you add that command to the setup process for new OS X VMs?

**Comment by bradfitz** [comment]
Is there a way to programmatically do it without a password prompt?

**Comment by quentinmit** [comment]
In classic Apple fashion, it's not documented. Does it still prompt if run as root?

If so, try

`/usr/sbin/dseditgroup -o edit -t user -a $user _developer`

as root. Google thinks that *might* work.

**Comment by quentinmit** [comment]
I just tested it and `DevToolsSecurity -enable` runs without a password prompt when run by root.

**Comment by bradfitz** [comment]
@quentinmit, cool. Want to file a separate builder-specific bug? There are two separate things to fix with two separate owners I think: enabling this on our builders, vs actually fixing this.

Oh, and we also need Sierra builders too.

**Comment by josharian** [comment]
git bisect says 7c431cb7f9780fcaf58b9ef07028d5129e1e5fe7 / [CL 29397](https://go-review.googlesource.com/c/29397/) broke this. 

cc @cherrymui @crawshaw
