### ISSUE TITLE
cmd/go: go generate ./... will recurse into vendor

### ISSUE THREAD

**Issue by willfaught** [golang/go#17497]
Is that correct behavior? (go version go1.7.1 darwin/amd64) I didn't expect it, at least.

Where is this feature explained in the official documentation? `go help` what?

**Comment by bradfitz** [comment]
Yes, that's the correct behavior. vendor and internal are not special in any of these regards. All the other commands also work like that.

I'm not sure there's anything to document, since it's not a special case.

**Comment by willfaught** [comment]
Makes sense.

Shouldn't `go help build` at least explain how vendor and internal work? The spec doesn't explain it, IIRC. It's puzzling when `go help build | grep vendor` or the same for `internal` print nothing.

**Comment by bradfitz** [comment]
`go help gopath`

**Comment by willfaught** [comment]
Thanks.
