### ISSUE TITLE
removing 1 package level var results in 300x test run improvement

### ISSUE THREAD

**Issue by casualjim** [golang/go#17493]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

happens in both 1.6 and 1.7

### What operating system and processor architecture are you using (`go env`)?

happens on both osx and linux amd64

### What did you do?

running `go test` on https://github.com/go-openapi/validate

When https://github.com/go-openapi/loads has the branch borked checked out
https://github.com/go-openapi/loads/tree/borked

to go from this: --- PASS: TestIssue61_ResolvedRef (204.44s) to --- PASS: TestIssue61_ResolvedRef (1.27s), I had to remove 1 package level unexported var in a dependency. That was a bit counter-intuitive

Another test does not complete at all and times out eventually.

### What did you expect to see?

I expect not to see that much contention when I run tests serially and tests to complete swiftly 

### What did you see instead?

I see tests timing out and taking a very long time when I don't run them in isolation.

**Comment by mattn** [comment]
I'm not sure but seems to be wrong on the tests it-self.

![](http://go-gyazo.appspot.com/fc2f58c71a2fb03a.png)

As far as I can see, it seems that something is growing-up in github.com/go-openapi/spec/expandSchema or somewhere.
Please make small program which can reproduce this issue.

**Comment by casualjim** [comment]
I think you're right, will reopen when I've properly diagnosed the issue
