### ISSUE TITLE
net/http: tests failing on Plan 9 since CL 31173

### ISSUE THREAD

**Issue by 0intro** [golang/go#17498]
Since [CL 31173](https://golang.org/cl/31173) the HTTP server relies on deadlines to read requests from clients. This change broke various tests in the net/http package, because deadlines aren't implemented on Plan 9 yet.

```
2016/10/18 03:15:56 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0x10976f98 127.0.0.1:47045 in state active
  *net.TCPConn 0x10976110 127.0.0.1:43006 in state active
panic: test timed out after 3m0s
FAIL    net/http    180.069s
```

See https://build.golang.org/log/726c2a2970f3e33d3728a27645521822e2ef8d03

**Comment by rsc** [comment]
To be clear, the fix here is to implement deadlines on Plan 9, right?

**Comment by bradfitz** [comment]
Yes. And there's now a pending CL for it too.

**Comment by 0intro** [comment]
Yes, we have to implement deadlines on Plan 9.
I've proposed an experimental implementation in [CL 31521](https://golang.org/cl/31521), which is able to pass the currents tests.
