### ISSUE TITLE
website: playground internals article contains many broken references to code.google.com

### ISSUE THREAD

**Issue by dgryski** [golang/go#17501]
The article https://blog.golang.org/playground has ~25 links to repositories and individual commits on code.google.com for various projects.  These links are all dead.

**Comment by broady** [comment]
This one's probably a bit more tricky, need to hunt down the relevant commits in the now defunct nacl tree.

If someone would like to help, I made a clone of the Mercurial repository, retaining the commit hashes. It might help to match them to CLs and/or git hashes.
https://bitbucket.org/broady/go-archive/

**Comment by bradfitz** [comment]
@broady, which Mercurial hashes (and in which original repo?) are you trying to map?

**Comment by broady** [comment]
@bradfitz from the original code.google.com/p/go repo.

No particular hashes at the moment - I mapped a bunch for some other articles:
https://golang.org/cl/36311/

The links in the playground article are completely broken and very difficult to map, as they referred to @rsc's nacl fork of the go repo. It looks like Google Code forks weren't archived, so they're possibly lost forever.

Example URL from the playground article:
https://code.google.com/r/rsc-go13nacl/source/browse/src/pkg/runtime/sys_nacl_amd64p32.s?r=1f01be1a1dc2#54

No commit ID exists:
https://bitbucket.org/broady/go-archive/commits/1f01be1a1dc2

So they'd require some more manual work (and maybe removing/changing line numbers in the URL hash).

**Comment by rsc** [comment]
Re

> (This special tool chain will be merged into the core for Go 1.3. To learn more, read the design document. If you want to play with NaCl before then, you can check out a fork that has all the changes.)

Let's just rewrite to

> (This special tool chain was merged into Go 1.3. To learn more, read the design document.)

**Comment by broady** [comment]
Well, I dug up an archive of the rsc-go13nacl fork. Hosted here now:
https://bitbucket.org/broady/rsc-go13nacl-archive/
