### ISSUE TITLE
comparison of parsed, Truncated dates fails in docker containers

### ISSUE THREAD

**Issue by tdi** [golang/go#17506]
### What version of Go are you using (`go version`)?

go version go1.7.1 and 1.6 linux/amd64
go version go1.7.1 and 1.6 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build610621160=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

When you compare dates that are both truncated with `time.Truncate`, and one of them is parsed with `time.Parse`, the test fails in docker containers. It works locally on OSX and Linux, go version 1.6 and 1.7. Below is the code and link to play.golang.org. 

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	now := time.Now()
	date2 := time.Now()
	parsed, _ := time.Parse(time.RFC3339, date2.Format(time.RFC3339))
	if now.Truncate(time.Hour) != parsed.Truncate(time.Hour) {
		fmt.Println("Dates differ in docker", now.Truncate(time.Hour), parsed.Truncate(time.Hour))
	} else {
		fmt.Println("Dates are equal on the host", now.Truncate(time.Hour), parsed.Truncate(time.Hour))
	}
}
``` 

https://play.golang.org/p/JKXJrjUun3

### What did you expect to see?

I expected the comparison to be true. 

### What did you see instead?

Was false.

**Comment by quentinmit** [comment]
You cannot compare times with `==` or `!=`. You must use the `t1.Equal(t2)` method.

The reason is that time.Now() always has the magic "local" location. time.Parse when given a numeric timezone will use the "local" location if that is a valid offset for the local timezone, and otherwise will create a new Location with the fixed offset.

I suspect your Docker container has UTC as the default timezone, but your local machine has a different timezone.

**Comment by tdi** [comment]
@quentinmit but what if both dates are created on the same docker with the same UTC ? Should it not be equal ? I checked the location field in both dates and was equal. In this case you described should not the behavior be predictable no matter where we execute?

**Comment by quentinmit** [comment]
The location fields in both dates are not equal. See

https://play.golang.org/p/XpmFLX_A9n
