### ISSUE TITLE
x/tools/cmd/godoc: generate docs for test files

### ISSUE THREAD

**Issue by rpetersen76** [golang/go#17509]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go1.7 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/projects/ntsw-sw19/home/ryanp/ngsdk/INTERNAL/appl/regress/go"
GORACE=""
GOROOT="/projects/ntsw-tools/go"
GOTOOLDIR="/projects/ntsw-tools/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build767044606=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
### What did you do?

Trying to run godoc on a directory with test files (<xxx>_test.go) does not produce documentation.

It would be great if a -test flag could be added to include generating documentation for packages that contain test files.

**Comment by rsc** [comment]
Godoc is about showing the exported API from a package. Test files are not part of the exported API. 

If the tests are so complex that they need documentation to find out how to use them, they're also often worth using from multiple tests, in which case we typically move them into separate standalone packages (not in \*\_test.go files), like testing/iotest and net/http/httptest. That might be the right solution for your case as well.
