### ISSUE TITLE
reflect/type.go : struct tag Lookup can not find right tag name

### ISSUE THREAD

**Issue by Tang-RoseChild** [golang/go#17514]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
call  [Lookup](https://golang.org/pkg/reflect/#StructTag.Lookup) will not find the tag name if it's not the first tag name. 

playbord:
https://play.golang.org/p/NRLtObwwTD

detail info : 
```
package main

import (
	"fmt"
	"reflect"
)

type demo1 struct {
	Name string `json:"name",valid:"string"`
}

type demo2 struct {
	Name string `valid:"string",json:"name"`
}

func main() {
	demo1Tag := reflect.TypeOf(demo1{}).Field(0).Tag
	if value, ok := demo1Tag.Lookup("valid"); ok {
		fmt.Println("demo1 valid tag : ", value)
	}

	demo2Tag := reflect.TypeOf(demo2{}).Field(0).Tag
	if value, ok := demo2Tag.Lookup("valid"); ok {
		fmt.Println("demo2 valid tag : ", value)
	}
}

```

### What did you expect to see?
out put result should be:

demo1 valid tag :  string
demo2 valid tag :  string

### What did you see instead?
demo2 valid tag :  string

### maybe the reason
In source code,after check the first tag name, rest tag string will include the delimiter of the tag name,then the next tag name's first character will be the delimiter.

And if change as follow,it will work:

```
diff --git a/src/reflect/type.go b/src/reflect/type.go
index 8916710..1188229 100644
--- a/src/reflect/type.go
+++ b/src/reflect/type.go
@@ -1183,7 +1183,13 @@ func (tag StructTag) Lookup(key string) (value string, ok bool) {
                        break
                }
                qvalue := string(tag[:i+1])
-               tag = tag[i+1:]
+
+               // skip tag name delimeter
+               if i+2 >= len(tag) {
+                       tag = ""
+               } else {
+                       tag = tag[i+2:]
+               }
 
                if key == name {
                        value, err := strconv.Unquote(qvalue)
```

**Comment by bradfitz** [comment]
You're formatting your struct tags incorrectly. See:

https://golang.org/pkg/reflect/#StructTag

> By convention, tag strings are a concatenation of optionally space-separated key:"value" pairs.

If you don't follow the convention, you don't get to use the helpers.
