### ISSUE TITLE
x/crypto/poly1305: Sum declared in both sum_ref.go:37 and  sum_arm.go for Go 1.6

### ISSUE THREAD

**Issue by chadmiller** [golang/go#17512]
### What version of Go are you using (`go version`)?
1.6.2-0ubuntu5~16.04

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04, armhf

### What did you do?

Tried to build/install https://github.com/Yawning/obfs4 on an ARMHF machine.

```
go install ./obfs4.git/...
# golang.org/x/crypto/poly1305
golang.org/x/crypto/poly1305/sum_ref.go:37: Sum redeclared in this block
	previous declaration at golang.org/x/crypto/poly1305/sum_arm.go:16
Command '['/bin/sh', '/tmp/tmpy80swmr2', 'go', 'install', './obfs4.git/...']' returned non-zero exit status 2
```

Happens only for 32-bit arm. Not arm64, amd64, i386.

**Comment by bradfitz** [comment]
@agl, this only affects Go 1.6. The +build constraints aren't quite right.

I'm tagging this Go1.8 because it needs to be done soon (red builders aren't useful to anybody), but it's not actually part of the release.
