### ISSUE TITLE
cmd/compile: regression in type switch deduplication

### ISSUE THREAD

**Issue by dsnet** [golang/go#17517]
8c85e23087d90e831a70ccd199cac49a38d91027 caused a regression where duplicate cases fail to be detected in a switch.

```go
package main

func main() {
	var a int
	switch a {
	case 0,1:
	case 0:
	}
}
```

On Go1.7, the above program fails:
```
./main.go:13: duplicate case 0 in switch
	previous case at ./main.go:12
```

On Go1.8dev, the above program, unexpectedly succeeds.

I understand that this is not a language guarantee:
> Implementation restriction: A compiler *may* disallow multiple case expressions evaluating to the same constant. For instance, the current compilers disallow duplicate integer, floating point, or string constants in case expressions.

However, we should be consistent with how it is done. The following snippet is rejected on both Go1.7 and Go1.8dev:
```go
var a int
switch a {
case 0:
case 0:
}
```

/cc @josharian @mdempsky

**Comment by rsc** [comment]
Caused by 8c85e230. Must be fixed for Go 1.8.

/cc @josharian @mdempsky

**Comment by odeke-em** [comment]
Interestingly type switches catch the duplicates but the expression switches
do not catch them like @dsnet reported
```go
package main

func main() {
	var a int
	switch a {
	case 1, 0:
	case 0:
	}

	var s interface{} = "hello"
	switch s.(type) {
	case string:
	case int, string:
	}
}
```

```shell
$ go run main.go
./main.go:13: duplicate case string in type switch
	previous case at ./main.go:12
$ go version
go version devel +930ab0a Fri Oct 21 02:14:57 2016 +0000 darwin/amd64
```
so I think that can narrow the bug to the code for *exprSwitch

**Comment by odeke-em** [comment]
I've mailed https://go-review.googlesource.com/31671

**Comment by mdempsky** [comment]
@odeke-em Thanks again for your help in root causing the issue!
