### ISSUE TITLE
Failing test in `time` package

### ISSUE THREAD

**Issue by luther9** [golang/go#17519]
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What did you do?
From the `src` directory I ran `./all.bash`.

### What did you expect to see?
All tests passing.

### What did you see instead?
One test failed:
```
--- FAIL: TestLoadFixed (0.06s)
	time_test.go:943: Now().In(loc).Zone() = "-01", -3600, want "GMT+1", -3600
FAIL
FAIL	time	2.526s
```

**Comment by dgryski** [comment]
The fix for https://github.com/golang/go/issues/17276 didn't make it into 1.7.3

**Comment by luther9** [comment]
So I guess this is a duplicate issue. It seems I don't have permission to mark it as such, even though I *do* see a "Close" button here. I'd prefer that someone marks this issue as duplicate before closing it.

**Comment by quentinmit** [comment]
We don't have a separate dupe state, so closed it is.
