### ISSUE TITLE
Expose cmsgData

### ISSUE THREAD

**Issue by vincentbernat** [golang/go#17527]
Hey!

When working with ancillary data, it is difficult to not use `cmsgData` from the `syscall` package. The package implements FD passing but everything else will need access to the data. A [previous proposition](https://codereview.appspot.com/6448110/) was made to make the function public but was rejected due to returning `unsafe.Pointer`.

I would propose to use the following signature for the public function:

```
func CmsgData(h *Cmsghdr, len int) []byte
```

It could still panic if `len` is incorrect. Is that admissible?

**Comment by ianlancetaylor** [comment]
Why can't you use `syscall.ParseSocketControlMessage`?

**Comment by vincentbernat** [comment]
Oooh, terribly sorry. You are right. I just need the "reverse" function (`SocketControlMessage`) taking `[]SocketControlMessage` and returning `[]byte`.

**Comment by ianlancetaylor** [comment]
Closing since I don't think there is anything to do in the syscall package, which is more or less frozen anyhow.

**Comment by vincentbernat** [comment]
So, not possible to add `SocketControlMessage()` which would be the reverse for `ParseSocketControlMessage()`? Much like `UnixRights()` and `ParseUnixRights()`.
