### ISSUE TITLE
proposal: reserve GOOS=zos for IBM z/OS

### ISSUE THREAD

**Issue by mundaym** [golang/go#17528]
As discussed here: https://groups.google.com/d/topic/golang-dev/f6IC8Dm7weI/discussion there may be a z/OS port in the future (subject to further discussions etc.).

As part of this effort it would be helpful to reserve GOOS=zos now, in order to make supporting z/OS outside of Go itself easier in the future (similar to what was done here: https://github.com/golang/go/issues/10165).

I am open to names other than zos if zos is considered undesirable for whatever reason.

**Comment by bradfitz** [comment]
Seems pretty uncontroversial.

/cc @minux @ianlancetaylor @rsc

**Comment by ianlancetaylor** [comment]
Sure.

**Comment by randall77** [comment]
Speaking of which, @josharian , want to reserve a RISC-V arch name?

**Comment by josharian** [comment]
> Speaking of which, @josharian , want to reserve a RISC-V arch name?

Yes. Is there any reason to do it now (in 1.8) vs when the port is ready (hopefully 1.9)?

There are some naming questions, too--there are many RISC-V variants (ISA subsets, 32 vs 64 bit, compressed).

**Comment by bradfitz** [comment]
The advantage is that "foo_riscv.go" would be recognized as a reserved file in Go 1.8, even without +riscv build tags.

But we'd probably need them anyway, at least in subrepos, for people using Go 1.7 and below.

**Comment by josharian** [comment]
Ok. That doesn't feel urgent enough to rush the discussion.

**Comment by minux** [comment]
Reserving zos SGTM.
Yeah, I think we should riscv and riscv64 as GOARCHes too.

**Comment by minux** [comment]
I think we should use riscv and riscv64 to match the existing GOARCHes,
and the ISA variant should be specified in $GORISCV.

Actually, I don't think Go (at least the gc port) needs to handle any ISA
subsets at all. The compiler should target the generic (G) variant, and
additional feature required should be tested at runtime.

**Comment by josharian** [comment]
SGTM. Want to send a CL and add me as a reviewer? I'll pull in the other folks working on the port as well just to confirm.

**Comment by ianlancetaylor** [comment]
I'm not sure why we are discussing this on this issue, but I would also toss in aix as a GOOS.  I know some people at IBM are interested in porting Go to AIX.
