### ISSUE TITLE
time: uppercase day/month names are not recognized in format strings

### ISSUE THREAD

**Issue by BupjaeLee** [golang/go#17523]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go 1.7
### What operating system and processor architecture are you using (`go env`)?

play.golang.org
### What did you do?

https://play.golang.org/p/ORGoq1knm0
### What did you expect to see?

Tue Nov 10 2009
TUE NOV 10 2009
### What did you see instead?

Tue Nov 10 2009
MON JAN 10 2009

While "Mon" and "Jan" are parsed as placeholder, I was surprised "MON" and "JAN" are not parsed.

The documentation https://golang.org/pkg/time/ is not sufficient to determine format string specification without examining source code https://golang.org/src/time/format.go .

**Comment by cznic** [comment]
> The documentation https://golang.org/pkg/time/ is not sufficient to determine format string specification without examining source code https://golang.org/src/time/format.go .

Let me disagree please. From the docs:

> The reference time used in the layouts is the specific time:
>
> `Mon Jan 2 15:04:05 MST 2006`
>
> which is Unix time 1136239445. Since MST is GMT-0700, the reference time can be thought of as
>
> `01/02 03:04:05PM '06 -0700`
>
> To define your own format, write down what the reference time would look like formatted your way; see the values of constants like ANSIC, StampMicro or Kitchen for examples.

The format string in you example obviously is not 'what the reference time would look like formatted your way' b/c it uses `MON` instead of `Mon` etc, but nowhere is such thing documented to be allowed.

**Comment by quentinmit** [comment]
@cznic This request seems reasonable to me; they're saying that "MON" is how they wanted the day to be formatted. We ought to either document the allowed symbols or support upper/title/lower case.
