### ISSUE TITLE
os/exec: Command does not pass absolute path to argv[0]

### ISSUE THREAD

**Issue by APTy** [golang/go#17536]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
`darwin amd64`

### What did you do?
Run `sshd` in `exec.Command()` fails due to an incorrect absolute path.
https://play.golang.org/p/z1UMtdSY2N

### What did you expect to see?
Successful execution of the command
```
Server listening on 0.0.0.0 port 8022.
Server listening on :: port 8022.
```

### What did you see instead?
A message indicating that the command was not executed as it should be.
```
sshd re-exec requires execution with an absolute path
```

## Discussion

[`exec.Command`](https://golang.org/src/os/exec/exec.go?s=4289:4334#L119) does in fact expand the absolute path of a command and save it to `cmd.Path`; however, it does not update the value of `cmd.Args[0]`, which remains the original string `name`.

Even though the executed program is run correctly from its full system path, programs like `sshd` may make [application-level checks](https://github.com/openssh/openssh-portable/blob/1cfd5c06efb121e58e8b6671548fda77ef4b4455/sshd.c#L1509) against `argv[0]`. In these cases, we see the failure case as above.

Note that this may be intentional, but the docs for `Command` state that the path is resolved to a complete name, which makes the behavior above a little unexpected.
>If name contains no path separators, Command uses LookPath to resolve the path to a complete name if possible. Otherwise it uses name directly.

**Comment by ianlancetaylor** [comment]
If you write `exec.Command("ls") then I think the os/exec package should invoke /bin/ls passing `"ls"` as `argv[0]`.  The user of os/exec should be able to control the `argv[0]` passed to the program.  For your case I think you should be calling `exec.LookPath("ssh")` to get the value to pass to `exec.Command`.

If there is a bug here, I think it is only in the documentation.

**Comment by APTy** [comment]
Cool, just wanted to make sure that was indeed the intended behavior - it does make sense. In this case I agree a documentation fix will suffice.

**Comment by mattn** [comment]
FYI (as you know), It's possible to pass different argument into path and argv[0] for execve. So that exec.LookPath just find `command name` from your $PATH.

For linux, you can get absolute path with `readlink("/proc/self/exe", path, sizeof(path)-1)`.
For windows, `GetModuleFileName`. For macOS, `_NSGetExecutablePath`.
