### ISSUE TITLE
syscall: mksyscall_windows.go doesn't generate syscalldot for internal/syscall/windows.

### ISSUE THREAD

**Issue by mattn** [golang/go#17539]
### What version of Go are you using (`go version`)?

go version devel +9670403 Mon Oct 17 09:20:04 2016 +0900 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

Windows7 64bit

### What did you do?

`go generate` on $GOROOT/src/internal/syscall/windows, then `go build`.

### What did you expect to see?

No errors

### What did you see instead?

Compilation error
```
# internal/syscall/windows
.\zsyscall_windows.go:16: undefined: ERROR_IO_PENDING
.\zsyscall_windows.go:25: undefined: ERROR_IO_PENDING
```

**Comment by mattn** [comment]
I sent CL 31541

But I wonder how this part is generated.

https://github.com/golang/go/commit/ca264cdc6247141a1e042f38c83fff4783f03324

I guess errWSAEINPROGRESS is meaning-less. cc: @bradfitz @alexbrainman

**Comment by alexbrainman** [comment]
Does https://go-review.googlesource.com/#/c/29690/ fixes your problem?

Alex

**Comment by mattn** [comment]
Yes, abandoned my CL. Thank you. please fix this. We must merge by hand always after do go generate in internal/syscall/windows.

**Comment by alexbrainman** [comment]
Will fix.

Alex
