### ISSUE TITLE
`golang_org/...` in `import`

### ISSUE THREAD

**Issue by quchunguang** [golang/go#17548]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7 and HEAD now

### What operating system and processor architecture are you using (`go env`)?

any

### What did you do?

This cause `atom` generate many import error message. And of course, cannot build.
For src\net\http\h2_bundle.go file are `go:generate` by tool, may this issue is from the tool.

### What did you expect to see?

src\net\http\h2_bundle.go
```
	"golang.org/x/net/http2/hpack"
	"golang.org/x/net/idna"
	"golang.org/x/net/lex/httplex"
```

### What did you see instead?

src\net\http\h2_bundle.go
```
	"golang_org/x/net/http2/hpack"
	"golang_org/x/net/idna"
	"golang_org/x/net/lex/httplex"
```

**Comment by quentinmit** [comment]
I do not know what the "atom" tool is in this context, but these import paths are correct. These packages are vendored with these paths, which means they can be found in `src/vendor/golang_org/x/net`.

See #17326 for being able to change the path back to golang.org.

**Comment by davecheney** [comment]
Those packages exist inside GOROOT/src/vendor. Is this an atom bug?

**Comment by minux** [comment]
Sorry, I don't understand what this issue is about.

h2_bundle.go imports the vendored copy of x/net/http2/hpack package.
The reason we use golang_org instead of golang.org is #16333.
