### ISSUE TITLE
testing: add -test.report flag for xunit/junit results

### ISSUE THREAD

**Issue by techtonik** [golang/go#17542]
The idea is to add `-test.report=junit` flag to `go test`, which will produce `gotests.xml` in current directory (borrowed from https://nose.readthedocs.io/en/latest/plugins/xunit.html#options).

This is an extension of #2981 (and this specific https://github.com/golang/go/issues/2981#issuecomment-66062807 by @alberts).

**Why xUnit/JUnit first and not JSON?**

JSON is not a specification for testing, so services like AppVeyor [can't support it](https://www.appveyor.com/docs/running-tests/#uploading-xml-test-results).

**Why write report to file instead of streaming it to the screen?**

Because screen is for humans and report are for robots. It is very inconvenient to sacrifice one for another with pipe formatters like https://github.com/jstemmer/go-junit-report and https://github.com/tebeka/go2xunit because there is no `tee` on Windows.

**Comment by quentinmit** [comment]
As already discussed in #2981, we're not going to directly generate JUnit or xUnit or any of these other formats. Our goal is to implement a single well-specified output format for Go, and you can then use whatever converter you want on that output. I don't understand why this makes it difficult to use AppVeyor?

There is a kernel of an interesting idea here, however, which is to support both structured output and human-readable output at the same time. That has been mentioned obliquely on #2981, but feel free to raise this request explicitly.

**Comment by techtonik** [comment]
@quentinmit can you cite the exact message. https://github.com/golang/go/issues/2981 is too long to find the answer for people coming here from search engine(s).

Problem with AppVeyor and Windows in general that there is no native `tee` command there, so directing output to file and to screen at the same time is tricky.

The output for user should be different than for build engine, and the problem with #2981 that it probably tries to kill that other bird. Another issues is that the request is about JSON format only, which bears the risk to provide a poor interface/API for extension.
