### ISSUE TITLE
x/net/http2: write on closed buffer

### ISSUE THREAD

**Issue by wjdp** [golang/go#17543]
### What version of Go are you using (`go version`)?

`go version go1.6.2 linux/amd64`
### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/will/local/htmltest"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
### What did you do?

Perform a sequence of http.Get-s to the https://photos.smugmug.com domain for jpg images.

``` go
resp, err := http.Get(url)
if err != nil {
  log.Println(err.Error())
} else {
  log.Println(url)
}
```

Output: https://gist.github.com/wjdp/ba545c7ae1925e3be1b10f05425abeda
### What did you expect to see?

No errors, 200 response codes
### What did you see instead?

Majority were error free, a random subset return `write on closed buffer` (see http2.log in gist)

When running with `GODEBUG=http2client=0` no errors were seen (see http1.log in gist)

**Comment by bradfitz** [comment]
Can you try Go 1.7.3?

**Comment by bradfitz** [comment]
Also, can you share a more complete program? Your sample code doesn't seem to match the output.

**Comment by bradfitz** [comment]
Looks like this was a dup of #16974

**Comment by wjdp** [comment]
Sorry for not getting back to you on this! If this is still an issue in 1.7 I'll run into it again in a few weeks, will post here I do.
