### ISSUE TITLE
doc: Install documentation on Windows has issues

### ISSUE THREAD

**Issue by Lassesen** [golang/go#17553]
Please answer these questions before submitting your issue. Thanks!
### What operating system and processor architecture are you using (`go env`)?

Windows 10 Professional
### What did you do?

Installed Go to D: Drive
MISSING instruction, adding to Path, D:\Go\Bin (or wherever...)

Executed:
D:
D:> go install github.com/lassesen/hello
Got:
go: cannot find GOROOT directory C:\go

Checked environmental variables... there was no GOROOT item
### What did you expect to see?

Smooth execution
### What did you see instead?

Error messages

**Comment by bradfitz** [comment]
Did you use the MSI installer, or do it manually with the ZIP file?

**Comment by quentinmit** [comment]
Fixing this for real is #17833 which is too late for 1.8, unfortunately.

Doc fixes are encouraged in the meantime.

**Comment by mxplusb** [comment]
Also, the docs need to update that upgrades require you to delete the installed location's directory, or the installer will just overwrite ruin the installation.

**Comment by bradfitz** [comment]
Timed out waiting for reply.

Moving to Go 1.9.

**Comment by bradfitz** [comment]
Sounds like this was fixed by #17833.
