### ISSUE TITLE
x/tools/go/loader: fails to load packages that contain XTest files that use vendored imports

### ISSUE THREAD

**Issue by nmiyake** [golang/go#17556]
### What version of Go are you using (`go version`)?

go version go1.7.1 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
### What did you do?
1. Create a directory that contains a `vendor` directory (`mkdir -p foo/vendor/test.com`)
2. Create a vendored package (`echo 'package bar' > foo/vendor/test.com/bar.go`)
3. Create a Go test file in the directory that imports a vendored package (`echo 'package foo_test; import _ "test.com/bar"' > foo/foo_test.go`
4. Use `loadcfg.ImportWithTests("./foo")` to specify the package should be imported
5. Call `loadcfg.Load()` to load the packages

Full Go test that reproduces the issue:

``` go
package main_test

import (
    "io/ioutil"
    "os"
    "path"
    "testing"

    "golang.org/x/tools/go/loader"
)

const (
    bar = `package bar`
    foo = `package foo; import _ "test.com/bar"`
    foo_test = `package foo_test; import _ "test.com/bar"`
)

func TestRepro(t *testing.T) {
    wd, _ := os.Getwd()
    tmpDir, _ := ioutil.TempDir(wd, "")
    defer func() { os.RemoveAll(tmpDir) }()

    ioutil.WriteFile(path.Join(tmpDir, "foo.go"), []byte(foo), 0644)
    barDir := path.Join(tmpDir, "vendor", "test.com", "bar")
    os.MkdirAll(barDir, 0755)
    ioutil.WriteFile(path.Join(barDir, "bar.go"), []byte(bar), 0644)

    loadcfg := loader.Config{}
    loadcfg.ImportWithTests("./" + path.Base(tmpDir))
    // succeeds if non-test file imports vendored package
    if _, err := loadcfg.Load(); err != nil {
        t.Errorf("Error loading package without test")
    }

    // add test file that imports the vendored directory
    ioutil.WriteFile(path.Join(tmpDir, "foo_test.go"), []byte(foo_test), 0644)

    loadcfg = loader.Config{}
    loadcfg.ImportWithTests("./" + path.Base(tmpDir))
    // fails -- only change was adding a test file that imports the same vendored package
    if _, err := loadcfg.Load(); err != nil {
        t.Errorf("Error loading package that contains test that imports vendored library")
    }

    loadcfg = loader.Config{}
    loadcfg.Cwd = tmpDir
    loadcfg.ImportWithTests(".")
    // succeeds with test file if Cwd is set to the directory that is at the same level as the "vendor" directory
    if _, err := loadcfg.Load(); err != nil {
        t.Errorf("Error loading package after Cwd is set")
    }
}
```
### What did you expect to see?

The `loadcfg.Load()` call should succeed without errors
### What did you see instead?

The `loadcfg.Load()` call returns the following error:

```
 could not import test.com/bar (cannot find package "test.com/bar" in any of:
        /usr/local/go/src/test.com/bar (from $GOROOT)
        /Volumes/git/go/src/test.com/bar (from $GOPATH))
```
### Notes from investigation
- This works correctly if the current working directory is at the same level as the "vendor" directory
- The behavior appears to be correct for non-test files -- if step 3 in the repro steps is replaced with `echo 'package foo; import _ "test.com/bar"' > foo/foo.go`, then this works
- This behavior only exists for external test files (package name `*_test`) -- if step 3 in the repro steps is replaced with `echo 'package foo; import _ "test.com/bar"' > foo/foo_test.go`, then this works

Seems to be an issue with how the vendor directory is processed, but the behavior of XTest files should match the behavior of non-test and same-package test files (especially since the built-in Go commands like `go build` and `go test` handle this correctly).

**Comment by nmiyake** [comment]
More concretely, this causes tools that use `loader` (for example, [errcheck](https://github.com/kisielk/errcheck) and [varcheck](https://github.com/opennota/check/tree/master/cmd/varcheck)) to fail when run on projects that have a layout that match the scenario described in this issue.

**Comment by stamblerre** [comment]
Since support `golang.org/x/tools/go/loader` is now [deprecated](https://github.com/golang/tools/blob/master/go/loader/doc.go#L10), I'll go ahead and close this issue. Sorry that we never addressed it!
