### ISSUE TITLE
cmd/cgo: compiler complains about `C.free(*C.char)` but is happy with `defer C.free(*C.char)`

### ISSUE THREAD

**Issue by fanyang01** [golang/go#17562]
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/home/fan/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fan/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build668013101=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
```go
package main

// #include <stdlib.h>
// #include <string.h>
//
// const char *s = "hello";
//
// char *cstring(int *len) {
//     *len = strlen(s);
//     char *buf = (char *)malloc(*len);
//     return strncpy(buf, s, *len);
// }
import "C"
import "fmt"

func main() {
	fmt.Println(f())
}

func f() string {
	var (
		buf *C.char
		len C.int
	)

	if buf = C.cstring(&len); buf == nil {
		return ""
	}
	// defer C.free(unsafe.Pointer(buf))
	defer C.free(buf)
	return C.GoStringN(buf, len)
}

func g() string {
	var (
		buf *C.char
		len C.int
	)

	if buf = C.cstring(&len); buf == nil {
		return ""
	}
	s := C.GoStringN(buf, len)

	// C.free(unsafe.Pointer(buf))
	C.free(buf)

	return s
}
```

### What did you expect to see?
Consistent behavior.

### What did you see instead?
- Compile error for `C.free(*C.char)`:
```
./test.go:46: cannot use buf (type *C.char) as type unsafe.Pointer in argument to _cgoCheckPointer0
```
- Runtime error for `defer C.free(*C.char)`:
```
panic: interface conversion: interface {} is *main._Ctype_char, not unsafe.Pointer
```

**Comment by ianlancetaylor** [comment]
Thanks for providing a standalone test case.  This is a dup of #16591, already fixed for 1.8.  With 1.8 I get

    foo8.go:30: cannot use buf (type *C.char) as type unsafe.Pointer in argument to func literal
    foo8.go:46: cannot use buf (type *C.char) as type unsafe.Pointer in argument to func literal
