### ISSUE TITLE
x/tools/cmd/goimports: 

### ISSUE THREAD

**Issue by deftworker** [golang/go#17576]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
mac

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Try to run the newrelic go-agent plugin in Sublime Text with goimports and gosublime - since the plugin name is different from the package name, goimports keeps deleting it and making it impossible to use. I have to disable the automatic gosublime goimports functionality to use newrelic. 

### What did you expect to see?
Allow some plugins to be used even if they don't meet your naming conventions

### What did you see instead?
Breaking behaviour.

**Comment by deftworker** [comment]
"github.com/newrelic/go-agent" 

https://github.com/newrelic/go-agent

**Comment by bradfitz** [comment]
Sorry, I'm not going to fix this.

If you don't follow conventions, you don't get the tools which are built on conventions.

You'll have to write your imports by hand, I'm afraid.

**Comment by deftworker** [comment]
Reporting to newrelic as well.

**Comment by bradfitz** [comment]
Thanks, please do.

goimports will respect any of these options:

package newrelic in github.com/newrelic/go-agent/newrelic
package agent in github.com/newrelic/go-agent
package goagent in github.com/newrelic/go-agent  (after #17546 at least)
