### ISSUE TITLE
gccgo: switch to new export format

### ISSUE THREAD

**Issue by paranoiacblack** [golang/go#17573]
cmd/compile recently switched to a non-textual export format (https://github.com/golang/go/issues/13241) and now it seems like gccgo is the odd compiler out with respect to the export format. We should update gccgo's export format to match cmd/compile's.

For the team working on Go tooling, this will simplify the work these tools have to do to analyze compiled Go programs in build environments with multiple compilers. Ideally, they shouldn't have to consider that they are possibly looking at gccgo-compiled code; it should be transparent.

**Comment by thanm** [comment]
This seems like a good thing to do. It does seem as though there are things in the gccgo export data that don't have directly correspondents in the cmd/compile format (notably init function handling).

**Comment by alandonovan** [comment]
Speaking of init functions, why does gccgo gather them up and present them all to the main package, rather than taking the regular and uniform approach of gc, which is (a) make each package initialize its direct dependencies and (b) make init functions idempotent?

**Comment by ianlancetaylor** [comment]
This may not be the best place for gccgo design discussions, but it's simply because the gccgo approach is more efficient for large programs.

**Comment by moazzamk** [comment]
I'm willing to work on this if someone can show me what needs to be done (I don't have much experience with C/C++).
