### ISSUE TITLE
math/cmplx: Cot(0) loops infinitely

### ISSUE THREAD

**Issue by catalase** [golang/go#17577]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7 (I tested on play.golang.org)

### What did you do?
1. https://play.golang.org/p/TYwrN6agmD

cmplx.Cot(0) will loop infinitely

2. https://play.golang.org/p/b4IG3wqBm_

let f be a function in the pakcage, and let g be the inverse function of f if f is invertible. If math/cmplx has no error in its implementation, then f(g(z)) is z for a complex z that is well-defined on f and g, which I tested.

but some function calculates wrongly, and some has poor error.

**Comment by odeke-em** [comment]
Just a drive by comment here, if I recall from my rusty Maths:
* cot(x) = 1/tan(x) where tan(0) = 0
coming from 1/tan(x) = cos(x)/sin(x):
and cos(0) = 1, sin(0) = 0 so:
cot(0) = 1/0 => Infinity.

I wonder if the package has a problem with detecting this case and should return infinity asap.
/cc @griesemer @rsc

**Comment by 0xmohit** [comment]
The issue happens due to floating-point comparison [here](https://github.com/golang/go/blob/master/src/math/cmplx/tan.go#L142).  In this specific case, `t/d` is NaN and the comparison returns false resulting in an infinite loop.  Will send a CL.

**Comment by odeke-em** [comment]
@0xmohit and @griesemer, did y'all mean to say "Fixes" instead of "Updates" with the CL https://go-review.googlesource.com/31952 that prevents an infinite loop in tanSeries, or is there more work for this issue?

**Comment by 0xmohit** [comment]
I probably specified "Updates" because more tests could be added for `Cot`.  However, those aren't strictly related to this change.

**Comment by griesemer** [comment]
@odeke-em Thanks for heads-up. Yes, I would consider this fixed.
