### ISSUE TITLE
x/net/http2: clarifying concurrent Close on requestBody

### ISSUE THREAD

**Issue by voutasaurus** [golang/go#17589]
### What version of Go are you using (`go version`)?
go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/voutasaurus"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v_/gz6l428x5w97h0zrm5m03rlm0000gn/T/go-build981066443=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

Read https://github.com/golang/net/commit/40a0a189809a998e2e62a8279990087f94fd01f6

### What did you expect to see?

Based on the commit message, support for concurrent calls to requestBody.Close.

### What did you see instead?

A closed bool field that makes Close() idempotent but not goroutine safe.

Supporting concurrent Close() may not be worth the effort. I've been bitten by it once due to defers and timeouts but that was my fault and now context makes that stuff much simpler. The commit message could be clearer about what the closed bool is for though.

**Comment by bradfitz** [comment]
io.Closer and io.Reader are not in general safe for concurrent uses.

Does this affect any code in the wild?

**Comment by voutasaurus** [comment]
> Does this affect any code in the wild?
Not to my knowledge

**Comment by bradfitz** [comment]
Okay, then I'm going to close this.
