### ISSUE TITLE
cmd/vet: ignore build comments in string literals

### ISSUE THREAD

**Issue by josharian** [golang/go#17580]
```go
package p

const buildtag = `
// +build abc
`
```

```bash
$ go tool vet x.go
x.go:4: +build comment must appear before package clause and be followed by a blank line
```

This is a detectable false positive. This is very unlikely to be an actual attempt at a build comment; it's inside a string literal. This happens when writing code generators. There's a concrete instance in TestBinaryOnlyPackages in cmd/go/go_test.go.

cc @valyala @robpike

**Comment by 0xmohit** [comment]
Also reported [earlier](https://github.com/golang/go/issues/13533).

**Comment by ianlancetaylor** [comment]
Closing as dup of #13533.
