### ISSUE TITLE
cmd/cgo: C.malloc test fails on dragonfly

### ISSUE THREAD

**Issue by tdfbsd** [golang/go#17585]
The recent builder logs display:

- ##### ../misc/cgo/errors succeeded unexpectedly 2016/10/24 19:59:03 Failed: exit status 1
https://build.golang.org/log/e8cf241ebc765f154671932c3ba24588d8d8117e

**Comment by ianlancetaylor** [comment]
I think this is a bug in the Dragonfly libc.  When I run this C program on Dragonfly:

    #include <stdio.h> 
    #include <stdlib.h>
    
    int main() {
      printf("%p\n", malloc((size_t)-1));
    }

it prints `0x800455000`.  It should print `0` or `(nil)`.
