### ISSUE TITLE
"unexpected directory layout error" too draconian

### ISSUE THREAD

**Issue by kaihendry** [golang/go#17597]
### What version of Go are you using (`go version`)?

go version devel +6e02750 Wed Oct 26 02:24:45 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

Travis

### What did you do?

    go run go/stars.go
    unexpected directory layout:
	import path: _/home/travis/gopath/src/github.com/Spuul/static-website/go/staticgen

### What did you expect to see?

For it not to croak

### What did you see instead?

    make: *** [public/stars.txt] Error 1

I know Golang is pretty pedantic about the directory layout, but as I've [griped about before](https://twitter.com/kaihendry/status/777683894137188352), having private dependencies in a proprietary project is a huge pain! Couldn't this please be instead picked up by a `go vet` flag?!

**Comment by bradfitz** [comment]
This bug report is more of a rant than a useful bug report. It lacks information for us to help or even understand the problem. Closing.
