### ISSUE TITLE
Syntax error causes hang/crash in goimports

### ISSUE THREAD

**Issue by sporkmonger** [golang/go#17591]
### What version of Go are you using (`go version`)?

go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sporkmonger/Projects/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pj/bcdnqjjs2gqdf7yjcgwmlk0c0000gn/T/go-build388449077=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

`goimports < myfile.go`
(freezes forever, usually)
`goimports -v < myfile.go`
(crashes, usually)

### What did you expect to see?

The transformed version of `myfile.go` or an error of some kind indicating problem w/ syntax.

### What did you see instead?

Hang w/ CPU pegged.
Or crash w/ verbose turned on.

Here's some logs from the verbose run. Both verbose and non-verbose are non-deterministic. Sometimes they hang, sometimes they crash. Verbose is vastly more likely to crash, non-verbose is vastly more likely to hang. Unfortunately full source input is something I can't supply. I'll try to find a minimal reproducible test case, but relevant snippet is below.

https://gist.github.com/sporkmonger/b90437fbc15d18beb0dc5a1456a7fb3a

The specific syntax that appears to be triggering this (obviously invalid!!!) is as follows:

```go
func (a *B) someFunction() func(c D, e *F) {
}
```

Note the second `func`.

**Comment by griesemer** [comment]
@sporkmonger The syntax is valid: it's perfectly fine for someFunction to return another function with type `func(c D, e *F)` (see e.g., https://play.golang.org/p/zdopODrEHg).

**Comment by bradfitz** [comment]
I bet you're using Sierra and haven't updated your goimports binary. Recompile your goimports with Go 1.7.

**Comment by sporkmonger** [comment]
Oh interesting. Either way, that does appear to be pertinent. Everything is fine with the intended code:

```
func (a *B) someFunction(c D, e *F) {
}
```

**Comment by sporkmonger** [comment]
@bradfitz That does indeed seem to have been the problem. Thanks!

Out of curiosity, why would you get non-deterministic behavior from this?

**Comment by bradfitz** [comment]
Non-deterministic memory corruption.

**Comment by sporkmonger** [comment]
One more tiny question (thanks for your patience!): would you expect runtime for correct code to be 0m0.009s and runtime for incorrect code to be 0m3.135s? Can be pretty painful in an editor context if I save a file w/ a bug in it since the plugin I'm using locks the editor up while `goimports` is running.

**Comment by bradfitz** [comment]
File a separate bug for performance, with a detailed bug report. Use the verbose mode to see what it's doing.
