### ISSUE TITLE
go version 1.7.3 is not work ubuntu ????

### ISSUE THREAD

**Issue by raysole** [golang/go#17605]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.3 ...

### What operating system and processor architecture are you using (`go env`)?
GOARCH = amd64
GOOS=linux

This project in the CENTOS compiler, the UBUNTU can not work.

centos for GNU/Linux 2.6.32

ubuntu for GNU/Linux 2.6.24

error message：Segmentation fault...

code :::
-----------------------------------------------------------------------------------
 package main

   import "fmt" 

    func main() {
       fmt.Printf("Hello, world; or Καλημέρα κόσμε; or こんにちは 世界\n")
  }

**Comment by rakyll** [comment]
Could you share the entire `go env` and your stack trace please?

**Comment by bradfitz** [comment]
Let's move this to a forum. See https://golang.org/wiki/Questions

**Comment by davecheney** [comment]
Your kernel version is below the minimum required. You need 2.6.27 or later
on Intel.
