### ISSUE TITLE
release: Installation on Windows x64 in C:\Program Files\Go redirects to C:\Program Files (x86)\Go\

### ISSUE THREAD

**Issue by lkarlslund** [golang/go#17602]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

Tested with Go 1.6.x and Go 1.7.x
### What operating system and processor architecture are you using (`go env`)?

Windows 10 64-bit
### What did you do?

Download latest install .MSI from Golang site. Double click to install. Override default C:\Go\ path to C:\Program Files\Go\ path. Installer redirects to C:\Program Files (x86)\Go\
### What did you expect to see?

The installer should install to the path asked, not the 32-bit variant.
### What did you see instead?

Installer redirected to 32-bit variant path of C:\Program Files\

**Comment by bradfitz** [comment]
I don't think anybody on the Go team knows how our MSI installer thing works, and this isn't a regression from Go 1.7, so kicking down the road to Go 1.9. Sorry.

Any help on this would be great.

**Comment by kardianos** [comment]
If I had to guess, the installer executable is a 32-bit program so part of windows magic redirects it to use the 32-bit program files folder. I again would guess that the fix would be to make the installer 64-bit for 64-bit installs.

**Comment by bradfitz** [comment]
How do we get a 64-bit installer? We don't compile the installer.

**Comment by kardianos** [comment]
I'm looking into it now. I can confirm this happens with the go1.8beta1 msi.

**Comment by bradfitz** [comment]
Okay, all yours. This is still tagged Go 1.9, but if you have a fix, we can try it out earlier.

**Comment by kardianos** [comment]
In `golang.org/x/build/cmd/release/releaselet.go` Line 545
```
<Package
    Id='*' 
    Keywords='Installer'
    Description="The Go Programming Language Installer"
    Comments="The Go programming language is an open source project to make programmers more productive."
    InstallerVersion="300"
    Compressed="yes"
    InstallScope="perMachine"
    Languages="1033" />
    <!--    Platform="x86 or x64" -->
```

Currently we don't specify in the wxs file if the platform is 32-bit or 64-bit. The msiexec will assume it is 32-bit if not specified. The fix will be to set the attribute. I'll send a CL later, though probably not in time for the beta2.

**Comment by bradfitz** [comment]
Ah, great.

/cc @broady
