### ISSUE TITLE
syscall: incorrect arguments of prlimit64 syscall on linux

### ISSUE THREAD

**Issue by ultimatesolution** [golang/go#17606]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

go version devel +7124056 Mon Oct 24 19:29:18 2016 +0000 linux/amd64
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/gopath"
GORACE=""
GOROOT="/home/user/go"
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build394839699=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
### What did you do?

I look at Go sources and see incorrect argument passing to sys_prlimit64 Linux syscall:

https://github.com/golang/go/blob/master/src/syscall/zsyscall_linux_386.go#L767

https://github.com/golang/go/blob/master/src/syscall/zsyscall_linux_amd64.go#L767

etc

```
    _, _, e1 := RawSyscall6(SYS_PRLIMIT64, uintptr(pid), uintptr(resource), uintptr(unsafe.Pointer(old)), uintptr(unsafe.Pointer(newlimit)), 0, 0)
```
### What did you expect to see?

`newlimit` MUST be passed first, `old` must be passed next.

```
    _, _, e1 := RawSyscall6(SYS_PRLIMIT64, uintptr(pid), uintptr(resource), uintptr(unsafe.Pointer(newlimit)), uintptr(unsafe.Pointer(old)), 0, 0)
```

see Linux kernel source tree for example:

```
asmlinkage long sys_prlimit64(pid_t pid, unsigned int resource,
                const struct rlimit64 __user *new_rlim,
                struct rlimit64 __user *old_rlim);
```
### What did you see instead?

see above

**Comment by quentinmit** [comment]
It looks like only the names of the arguments are wrong; the calls do actually pass the right thing. `Getrlimit` passes `nil, old` and `Setrlimit` passes `new, nil`.

**Comment by bradfitz** [comment]
@quentinmit, ah, great. That's reassuring. Sent https://golang.org/cl/32889
