### ISSUE TITLE
cmd/compile: internal compiler error: not lowered: v13494, Unknown invalid

### ISSUE THREAD

**Issue by calmh** [golang/go#17618]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version devel +bea5252 Wed Oct 26 18:46:59 2016 +0000 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jb"
GORACE=""
GOROOT="/Users/jb/src/go"
GOTOOLDIR="/Users/jb/src/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9l/prphpj9n431dsb2myvdjpj4w0000gp/T/go-build644174000=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

```
$ go get -u github.com/cznic/ql
# github.com/cznic/ql
../../cznic/ql/parser.go:1715: internal compiler error: not lowered: v13494, Unknown invalid

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/jb/src/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x6278dd, 0x2, 0xc4238a0050, 0x1, 0x1)
	/Users/jb/src/go/src/cmd/compile/internal/gc/subr.go:165 +0x226
cmd/compile/internal/gc.(*ssaExport).Fatalf(0x90ed35, 0x43d1, 0x6278dd, 0x2, 0xc4238a0050, 0x1, 0x1)
	/Users/jb/src/go/src/cmd/compile/internal/gc/ssa.go:4615 +0x5d
cmd/compile/internal/ssa.(*Config).Fatalf(0xc4221c0000, 0xc4000043d1, 0x6278dd, 0x2, 0xc4238a0050, 0x1, 0x1)
	/Users/jb/src/go/src/cmd/compile/internal/ssa/config.go:319 +0x6e
cmd/compile/internal/ssa.(*Func).Fatalf(0xc42882c5a0, 0x6278dd, 0x2, 0xc4238a0050, 0x1, 0x1)
	/Users/jb/src/go/src/cmd/compile/internal/ssa/func.go:413 +0x6b
cmd/compile/internal/ssa.checkLower(0xc42882c5a0)
	/Users/jb/src/go/src/cmd/compile/internal/ssa/lower.go:36 +0x3ce
cmd/compile/internal/ssa.Compile(0xc42882c5a0)
	/Users/jb/src/go/src/cmd/compile/internal/ssa/compile.go:68 +0x304
cmd/compile/internal/gc.buildssa(0xc421db0480, 0x0)
	/Users/jb/src/go/src/cmd/compile/internal/gc/ssa.go:176 +0x918
cmd/compile/internal/gc.compile(0xc421db0480)
	/Users/jb/src/go/src/cmd/compile/internal/gc/pgen.go:357 +0x204
cmd/compile/internal/gc.funccompile(0xc421db0480)
	/Users/jb/src/go/src/cmd/compile/internal/gc/dcl.go:1282 +0xdc
cmd/compile/internal/gc.Main()
	/Users/jb/src/go/src/cmd/compile/internal/gc/main.go:469 +0x1eff
main.main()
	/Users/jb/src/go/src/cmd/compile/main.go:47 +0x15d
```

That's `v1.0.0-19-gc81467d` of `czniq/ql`, if it changes in the meantime.

**Comment by rjammala** [comment]
It happens with go 1.6.3 on Linux too.

[rjammalamadaka@localhost ~]$ go version
go version go1.6.3 linux/amd64
[rjammalamadaka@localhost ~]$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rjammalamadaka/gocode"
GORACE=""
GOROOT="/home/rjammalamadaka/go"
GOTOOLDIR="/home/rjammalamadaka/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
[rjammalamadaka@localhost ~]$ go get -u github.com/cznic/ql
# github.com/cznic/ql
gocode/src/github.com/cznic/ql/parser.go:1715: internal compiler error: not lowered: v13494, Unknown invalid

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/rjammalamadaka/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0xa28c9c, 0x2, 0xc427950070, 0x1, 0x1)
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/subr.go:165 +0x226
cmd/compile/internal/gc.(*ssaExport).Fatalf(0xd112f5, 0x43d1, 0xa28c9c, 0x2, 0xc427950070, 0x1, 0x1)
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/ssa.go:4615 +0x5d
cmd/compile/internal/ssa.(*Config).Fatalf(0xc4234c0000, 0xc4000043d1, 0xa28c9c, 0x2, 0xc427950070, 0x1, 0x1)
	/home/rjammalamadaka/go/src/cmd/compile/internal/ssa/config.go:319 +0x6e
cmd/compile/internal/ssa.(*Func).Fatalf(0xc428768360, 0xa28c9c, 0x2, 0xc427950070, 0x1, 0x1)
	/home/rjammalamadaka/go/src/cmd/compile/internal/ssa/func.go:413 +0x6b
cmd/compile/internal/ssa.checkLower(0xc428768360)
	/home/rjammalamadaka/go/src/cmd/compile/internal/ssa/lower.go:36 +0x3ce
cmd/compile/internal/ssa.Compile(0xc428768360)
	/home/rjammalamadaka/go/src/cmd/compile/internal/ssa/compile.go:68 +0x304
cmd/compile/internal/gc.buildssa(0xc421d4def0, 0x0)
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/ssa.go:176 +0x918
cmd/compile/internal/gc.compile(0xc421d4def0)
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/pgen.go:357 +0x204
cmd/compile/internal/gc.funccompile(0xc421d4def0)
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/dcl.go:1282 +0xdc
cmd/compile/internal/gc.Main()
	/home/rjammalamadaka/go/src/cmd/compile/internal/gc/main.go:469 +0x1eff
main.main()
	/home/rjammalamadaka/go/src/cmd/compile/main.go:47 +0x15d

**Comment by josharian** [comment]
@randall77 this was also caused by c78d072c8e4a8b0283da21423732f93c503711a4 according to git bisect.
