### ISSUE TITLE
net: no docs about the consecutive dialing introduced in Go 1.5

### ISSUE THREAD

**Issue by mikioh** [golang/go#17617]
The release notes of Go 1.5, https://golang.org/doc/go1.5, say:

```
The net package will now Dial hostnames by trying each IP address in order until one succeeds. 
```

but there is no documentation about the behavior in net package.

**Comment by quentinmit** [comment]
Especially important is documenting how timeouts are handled by this algorithm.

**Comment by kavirajk** [comment]
@quentinmit do you mean about calcularing partialDeadline for single address when multiple addresses are pending?

**Comment by bradfitz** [comment]
@mikioh, are you going to write something?

**Comment by mikioh** [comment]
@bradfitz,

Will do if no one wants to do, but it will start from the end of this month. Happy to review a CL.

**Comment by bradfitz** [comment]
You have about 20 days before we probably won't accept even a doc change.

**Comment by kavirajk** [comment]
after walking through the Dial function, I feel llike we have to document two things.

1. Dial method. If a hostname have multiple IP addresses, each one of the them is tried in order until first one succeed

2. dialSerial method. How partialDeadline is calculated from actual deadline, for dialing each IP-address based on total number of IP addresses for the hostname.

correct me if I'm wrong or If I am missing anything, I am happy to raise CL.

/cc @mikioh @quentinmit @bradfitz
