### ISSUE TITLE
net: net.Listen("tcp", "0.0.0.0:1234") also listens on IPv6

### ISSUE THREAD

**Issue by mikioh** [golang/go#17615]
I asked several times on golang-nuts, golang-dev or golang-codereviews like the following:
https://groups.google.com/d/msg/golang-dev/MvAlef3CTqk/DGs5sLBcCgAJ

**Comment by bradfitz** [comment]
Please make bug reports self-contained. Don't link off to other threads for the majority of the information.

For the record:

Audrius Butkevicius asked:

>Maybe I am completely missing out something, but here it goes:
>
> I understand that net.Listen("tcp", ":1234") - is v4 and v6, as the stack is unspecified.
> But why on earth is net.Listen("tcp", "0.0.0.0:1234") listening on v6 [::]:1234?
> Yet why is net.Listen("tcp", "192.168.1.2:1234") only listening on v4, even if the same interface has a v6 address?
> 
> Most of the software I used (nginx for example) listens only on v4 when given 0.0.0.0, which I think makes perfect sense, as that means all v4 interfaces.
> Same way it only listens to v6 when [::]:80 is specified.
> 
> This complicates matters, as I am making an application where the user can specify a listen address I either have to add -tcp4 or -tcp6 flags to work out the stack the user is interested in, or do a bunch of .IsIP4()/.isIP6() to work out the users actual intent from the provided 0.0.0.0 address.
> 
> Can someone shed some light on this?
> 
> Thanks.

**Comment by quentinmit** [comment]
/cc @rsc 

I think there is an implementation bug here; an IPv4 address should cause an IPv4 listener to be created, even if it's `0.0.0.0`

That said... I can't imagine many users actually care about listening on all v4 interfaces but not v6 interfaces. They almost certainly want `:1234` instead.

**Comment by mikioh** [comment]
@quentinmit,

I don't think it's a good idea to mix two issues here. I just wanted to update documentation. Can you please open a new issue for the new behavior?
