### ISSUE TITLE
net: no docs on "0" or empty name of transport service

### ISSUE THREAD

**Issue by mikioh** [golang/go#17614]
#13610 and CL 17755 fixed the behavior without documentation. There is no documentation that describes what happens when the zero value of transport service in Dial, Listen, ListenPacket functions and Resolve{TCP,UDP,IP}Addr functions. I guess those two groups behave differently.

**Comment by mikioh** [comment]
And Listen{TCP,UDP} functions.

**Comment by bradfitz** [comment]
Guess this isn't happening. @mikioh, feel free to send something for Go 1.8, but otherwise I'm assuming this is Go 1.9 material. I would send a CL but I don't know what you want to say.
