### ISSUE TITLE
net: inaccurate docs about announcing or listening on all local addresses

### ISSUE THREAD

**Issue by mikioh** [golang/go#17616]
The current documentation says:

```
func Listen, ListenPacket, Listen{TCP,UDP,UP}

Listen listens on all available interfaces instead of just the interface with the given
host address. 
```

I think it provides inaccurate information. What happens when you move an interface address on network interface X to another? Does it break your application? (Please consider that how VRRP or CARP works) Actually it announcing or listening on `all local addresses`.

**Comment by quentinmit** [comment]
I don't understand the question. I read the docs as saying "Listen without a host address listens on all possible addresses on all interfaces". I think it's unspecified whether it picks up changes to the host's interfaces after startup - on *nix I expect that it would, but I don't think we guarantee that.

**Comment by mikioh** [comment]
@quentinmit,

From architectural point of view, an IP address is basically assigned to a link (or an interface or network interface which is an attachment to the link), agree. But practically, there are implementations that have addresses not assigned to link or interface; for example, 127.0.0.1/8 or IPv6 loopback address. I personally don't want to see an issue like "the Addr method of net.Interface doesn't show 127.0.0.1/8 but net.Listen("tcp", "127.0.0.1") works perfectly. Is this a bug?"
