### ISSUE TITLE
flag: no way to access a FlagSet's output

### ISSUE THREAD

**Issue by dominikh** [golang/go#17628]
The FlagSet type has a SetOutput method for setting the destination for
usage messages. This destination is used by the default Usage
function, but it's impossible to use it in custom implementations,
because no accessor for the output exists.

I propose adding a field or method to access the set output.

Relatedly, FlagSet.Usage currently writes the banner to os.Stderr,
ignoring the set output, while PrintDefaults writes to the set output.
### What did you do?

https://play.golang.org/p/tDimNWwNwD
### What did you expect to see?

This or similar code to compile and write to the set output
### What did you see instead?

No way to do so.

**Comment by odeke-em** [comment]
@dominikh I too found a need for this when working on https://go-review.googlesource.com/#/c/28488 but then thought I was overthinking it for that CL.

There is an unexposed FlagSet.output method https://github.com/golang/go/blob/49543695c56486d6a941e55520b37a9d098d3379/src/flag/flag.go#L308

**Comment by rakyll** [comment]
You can rewrite FlagSet.Usage easily. PrintDefaults output can be forwarded to any io.Writer by using *FlagSet.SetOutput.

I don't think we should add more APIs to this package. Usage exists for convince and is rewritable for cases where default behavior is not good enough.

See the program below:

```
func main() {
	fs := flag.NewFlagSet("name", flag.ExitOnError)
	fs.Int("count", 0, "")
	fs.Usage = usage(fs, os.Stdout)
}

func usage(fs *flag.FlagSet, out io.Writer) func() {
	fs.SetOutput(out)
	return func() {
		fmt.Fprintf(out, "Usage of %s:\n", os.Args[0])
		fs.PrintDefaults()
	}
}
```

**Comment by dominikh** [comment]
@rakyll there are two issues here, both involving broken contracts.

1. The API allows the user to specify where output should go. The user's wish is, however, ignored any time they use a custom Usage function that needs to output text. This turns SetOutput into a special case that is only relevant for the default function. Having to write another wrapper (your `usage`) is not only a crutch, it also makes for very odd code, where printing a usage message mutates the flag set, overwriting previous calls to SetOutput, creating two disjoint truths of where output should go.

2. The fact that even the default Usage function ignores the user's wish half of the time is both a bug and further indication of how weirdly special SetOutput currently is. It cannot even be used with the default Usage function if one expects correct results.

Quoting the documentation of SetOutput:

> SetOutput sets the destination for usage and error messages

None of that is really true.

**Comment by bruceauyeung** [comment]
i think after user called `flag.CommandLine.SetOutput(os.Stdout)`, `Usage of xxx` should also be printed to stdout without customizing usage function
