### ISSUE TITLE
x/build: trybots should test subrepos against previous Go releases

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17626]
Subrepos trybots should test against Go tip, Go 1.N, Go 1.N-1.

**Comment by dsnet** [comment]
What's the general policy for how many versions back we maintain support on a given subrepo?

**Comment by bradfitz** [comment]
In general, the two most recent. (which means between 12-18 months for us)

**Comment by mxplusb** [comment]
I'm new to the language contribution process, but I'd like to help with this issue since it seems like something simple (relative). How can I help with this issue?

**Comment by bradfitz** [comment]
This is a hard one to contribute to because the machine that runs the Go build system is large and has many moving parts, and it's difficult to run without access to our GCP project, and/or paying for it.

The code is in https://github.com/golang/build (mostly in cmd/coordinator) and you can run it in localhost machine. Kinda. But it might require some hackery for local testing. That code bitrots often and needs occasional love. I suspect it's partially broken.

**Comment by mxplusb** [comment]
Alright, I'll see if I can make some progress, and update here if I need help. Do I need a builder hash at all?

**Comment by bradfitz** [comment]
Nope.

**Comment by mxplusb** [comment]
I'm getting this issue when trying to run it locally:

`failed to get a token source: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

Do those creds need to be on the Go build system or will any credentials work?

**Comment by bradfitz** [comment]
You're starting to discover why this is difficult. You shouldn't need any credentials in localhost mode.  But we also don't develop the build system in localhost mode, so you probably need to fix it up to work.

**Comment by mxplusb** [comment]
Fix the system to fix the system, can do! I'll create a sub-issue to allow it to work in localhost mode and tackle that first.

**Comment by bradfitz** [comment]
@andybons, after the dev.golang.org migration (#20691), this would be a good second one.

**Comment by heschik** [comment]
This would be really nice for x/tools/go/packages, which has very different behavior on 1.10.

**Comment by dmitshur** [comment]
Reopening for deploy and verification.

**Comment by dmitshur** [comment]
Deployed.

According to https://go-review.googlesource.com/c/tools/+/147137#message-af8badf0a004b89d6130ff01bdf798052e2bebc8, it's not working yet. There are still 18 trybots for a subrepo run, that only include the latest Go tip version. /cc @bradfitz

**Comment by dmitshur** [comment]
Whoops. I deployed `cmd/coordinator`, but for this to take effect I should be deploying `maintnerd`.

So, this isn't actually deployed yet. Working on that now.

**Comment by bradfitz** [comment]
So it seems to work, but I missed something in the UI. It's using the builder name and not the new `Name() string` accessor here:

<img width="323" alt="screen shot 2018-11-03 at 12 49 15 pm" src="https://user-images.githubusercontent.com/2621/47956760-026b1d80-df67-11e8-87e7-d24fa9dddf32.png">

Notice that (and the grid below) is missing the Go version in parens.

**Comment by bradfitz** [comment]
But I do get the nice names in the final email:

<img width="840" alt="screen shot 2018-11-03 at 12 50 52 pm" src="https://user-images.githubusercontent.com/2621/47956770-2169af80-df67-11e8-998f-215db567b995.png">

**Comment by bradfitz** [comment]
Also, `(go branch release-branch.go1.10)` is pretty verbose. I clearly didn't think that through.

We could make that accessor clean up the string a bit and just say `(Go 1.10)`.

**Comment by dmitshur** [comment]
Indeed! From https://go-review.googlesource.com/c/tools/+/147137#message-d1a29aad64e636ed4ffcbaf1f2c3f324dc5d5d54:

> 7 of 20 TryBots failed:
> ...
> Failed on linux-amd64 (go branch release-branch.go1.10): https://storage.googleapis.com/go-build-log/1ae73979/linux-amd64_c18e47da.log
> Failed on linux-amd64 (go branch release-branch.go1.11): https://storage.googleapis.com/go-build-log/e8a95aeb/linux-amd64_1798cb41.log
> Failed on linux-amd64: https://storage.googleapis.com/go-build-log/f2cd0fa7/linux-amd64_fbab8151.log
> ...

That's proof it's working as intended! 🎉

I'll consider this issue resolved. Let's open a new one for the UI improvements.

**Comment by bradfitz** [comment]
I'm fine reusing this bug, but new one is also fine.
