### ISSUE TITLE
cmd/go: docs need section on cross-compiling

### ISSUE THREAD

**Issue by networkimprov** [golang/go#17620]
I got OK to post this issue from:
https://groups.google.com/d/msg/golang-nuts/IW4FiCclZTw/45wa1V9UBwAJ

Add a new section to docs for cmd/go: "Cross Compiling"

Instructions to rebuild Go source for new platform:

```
sudo GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go install -v -a std
sudo GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go install -v -a cmd

sudo is required if Go was installed via system package manager
CGO_ENABLED and CC are only required for cross-compiling with C source
CC varies for the toolchain installed
```

Instructions for cross compiling packages:

```
GOOS=linux GOARCH=arm go install -v github.com/id/package # .go only
GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=... go install -v github.com/id/package # .go & .c

GOARM=5|6|7 may be included to generate optimized code for that family

Output lands in:
$GOPATH/pkg/$GOOS_$GOARCH/github.com/id/package
$GOPATH/bin/$GOOS_$GOARCH/package
```

Also need instructions for Windows, OS X, etc.

**Comment by minux** [comment]
I don't think sudo is ever required.

**Comment by networkimprov** [comment]
Sudo is usually required to rebuild std & cmd. Dave Cheney has been saying:
> Unless you have built Go from source and/or your user owns the path Go is installed in, [cross compiling] is one of the few cases where go build is recommended over go install. 

The go package for my system installs the following; one must have root privs to modify it.
```
$ ls -la /lib/go/pkg/linux_amd64/
total 6632
drwxr-xr-x 30 root root    4096 Oct 12 22:57 .
drwxr-xr-x  7 root root    4096 Oct 12 23:13 ..
drwxr-xr-x  2 root root    4096 Oct 12 22:57 archive
-rw-r--r--  1 root root   98084 Sep  8 00:12 bufio.a
...
```

**Comment by davecheney** [comment]
That is why I recommend go build.

For the record, I do not think we should document this on godoc.org. I
think it should be documented on the wiki because this documentation is
fragile, baroque, and all the things which combine the ease of use of a
cross target gcc toolchain, with the ease of use of cgo.

**Comment by networkimprov** [comment]
All of the cross-compiling environment variables are documented in cmd/go, but not how to use them for practical purposes. It's an omission which generates recurring questions.

To my eye, the only arcane aspect is the value for CC, which can be left out of the command line examples and discussed in a separate paragraph.

**Comment by rsc** [comment]
@davecheney Thanks so much for the constructive, actionable feedback about our documentation!

**Comment by networkimprov** [comment]
@rsc I'm the one who posted the constructive, actionable feedback :-)

**Comment by rsc** [comment]
None of this setup is necessary anymore.
