### ISSUE TITLE
cmd/compile: improve error message when field not found in anonymous struct

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#17631]
go version devel +2113c9a Tue Oct 25 07:51:17 2016 +0000 linux/amd64

I just saw this error message and it took a while for me to parse it:

./database_test.go:554: unknown struct { about string; before map[mongodoc.EntityCount]mongodoc.Count; update map[mongodoc.EntityCount]int; updateTime time.Time; expect map[mongodoc.EntityCount]mongodoc.Count } field 'updates' in struct literal

Perhaps it would be better if the type went at the end of the message so
the entire struct type wasn't in the middle of the sentence.

For example:

./database_test.go:554: unknown field 'updates' in struct literal of type struct { about string; before map[mongodoc.EntityCount]mongodoc.Count; update map[mongodoc.EntityCount]int; updateTime time.Time; expect map[mongodoc.EntityCount]mongodoc.Count }

**Comment by josharian** [comment]
cc @odeke-em

**Comment by odeke-em** [comment]
Thanks for the ping @josharian! Done, I've mailed https://go-review.googlesource.com/32240.
