### ISSUE TITLE
cmd/link: misc/cgo/testshared fail on ARM64

### ISSUE THREAD

**Issue by cherrymui** [golang/go#17642]
### What version of Go are you using (`go version`)?

tip +bba1ac4
### What operating system and processor architecture are you using (`go env`)?

linux/arm64

```
##### ../misc/cgo/testshared
2016/10/27 20:49:17 executing go install -installsuffix=8674665223082153551 -buildmode=shared runtime sync/atomic failed exit status 2:
# /tmp/go-build461932225/libruntime,sync-atomic.so
/home/cherry/src/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld.gold: error: /tmp/go-link-711780168/go.o: unsupported reloc 311 against local symbol
/usr/bin/ld.gold: error: /tmp/go-link-711780168/go.o: unsupported reloc 312 against local symbol
/usr/bin/ld.gold: internal error in relocate, at ../../gold/aarch64.cc:5651
collect2: error: ld returned 1 exit status
```

It wasn't broken yesterday when I tested my CL 32180 locally. So, I think it is probably somewhere between 829aa67 and bba1ac4.

**Comment by cherrymui** [comment]
>  I think it is probably somewhere between 89632aa and bba1ac4.
I was wrong. 89632aa is today. The commit I tested yesterday was 829aa67.

**Comment by mwhudson** [comment]
I presume this is 8b07ec20f7a971edce9eaf413b20e453c50858c6. Where has the arm64 builder gone? :(

**Comment by mwhudson** [comment]
Although that worked when backported to 1.7 on Ubuntu zesty: https://launchpadlibrarian.net/291097700/buildlog_ubuntu-zesty-arm64.golang-1.7_1.7.3-1ubuntu2_BUILDING.txt.gz -- which version of gold do you have installed?

**Comment by cherrymui** [comment]
> Where has the arm64 builder gone? :(

I am wondering it, too.

**Comment by cherrymui** [comment]
> which version of gold do you have installed?

```
$ gold --version
GNU gold (GNU Binutils for Debian 2.25) 1.11
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by mwhudson** [comment]
Looks like this was fixed in October 2015 (https://sourceware.org/bugzilla/show_bug.cgi?id=19042) which I think means binutils 2.26.

I'm a bit confused as to how this is happening. Can you confirm that it really is the commit I mentioned that causes the problem? (I don't have easy access to an arm64 system with a sufficiently old version of gold installed).

**Comment by cherrymui** [comment]
Thank you for investigation. Yes, it is indeed that commit. I tested it and one commit before to confirm.

So, the problem seems that my gold linker is too old? Are we going to require a newer version? At the least we should document it, though I'm not sure where.

**Comment by mwhudson** [comment]
Well there is something strange going on in that we really shouldn't be accessing a local symbol via the GOT. Can you see if https://github.com/mwhudson/go/commit/f30efbdea5849ab467768dc7459954e6a42b3067 helps?

**Comment by cherrymui** [comment]
This indeed works. Thank you! (I have not tested on other architectures though.)
