### ISSUE TITLE
doc: Golang release 1.7 notes indicate macOS Sierra is supported for 1.6.x, when it is not

### ISSUE THREAD

**Issue by smarterclayton** [golang/go#17643]
The [1.7 release notes](https://golang.org/doc/go1.7) indicate that 

```
Go 1.7 adds support for macOS 10.12 Sierra. This support was backported to Go 1.6.3. Binaries built with versions of Go before 1.6.3 will not work correctly on Sierra.
```

As per https://github.com/golang/go/issues/17234 this is no longer the case, and should be qualified.

**Comment by bradfitz** [comment]
I sent https://go-review.googlesource.com/32238

@broady, please cherry-pick to the 1.7 branch and push it live to the website.

**Comment by quentinmit** [comment]
@bradfitz Can this be closed now? It has been pushed to the website.

**Comment by bradfitz** [comment]
Yup. Thanks again, @broady.
