### ISSUE TITLE
gccgo: function calls in slice/array literals evaluated out of order

### ISSUE THREAD

**Issue by mdempsky** [golang/go#17640]
Consider this program:

    package main

    func f(x int) int { println(x); return x }

    func main() {
    	_ = [2]int{1: f(1), 0: f(0)}
    }

The Go spec says function calls should be evaluated in lexical left-to-right order, which implies `f(1)` should be evaluated before `f(0)`.  cmd/compile does this, and outputs `1\n0\n`.

However, gccgo outputs `0\n1\n`.

I'm using "gccgo (google-gccgo-238667) 7.0.0 20160722 (experimental)".

/cc @ianlancetaylor

**Comment by thanm** [comment]
I took a look at this just now. Looks to me like a phase ordering issue. The code in Composite_literal_expression::lower_array is reordering the values within the literal by index, but this is happening in the lowering phase, meaning before ::gogo->order_evaluations(). The fix would be to delay the reordering until after evaluation ordering (maybe in flatten).

Ian, I can take a shot at fixing this if you have no objections.
