### ISSUE TITLE
crypto/sha256: improve performance on ppc64le for sha256.block

### ISSUE THREAD

**Issue by laboger** [golang/go#17652]
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

tip
### What operating system and processor architecture are you using (`go env`)?

Ubuntu 16.04

We have an asm version of sha256.block for ppc64le to improve performance.

**Comment by mstrosaker** [comment]
The assembly implementation was submitted here:
https://go-review.googlesource.com/32318
