### ISSUE TITLE
net/http: flaky "connection reset by peer" on macOS Sierra

### ISSUE THREAD

**Issue by rsc** [golang/go#17651]
all.bash on Sierra at master:

```
--- FAIL: TestTransportDiscardsUnneededConns (0.14s)
    clientserver_test.go:979: Get: Get https://127.0.0.1:59047: read tcp 127.0.0.1:59050->127.0.0.1:59047: read: connection reset by peer
FAIL
FAIL    net/http    10.072s
```

I saw this on the Go 1.6 branch too. Haven't dug into it to find out what it means, whether it's Sierra or a race in the test. Just happens once in a while.

/cc @bradfitz

**Comment by bradfitz** [comment]
I at least can't reproduce it on Linux with a high `-count` value and/or `-race` (which randomizes goroutine scheduling a bit and often exposes timing issues).

Will try on Mac.

**Comment by bradfitz** [comment]
My corp laptop is still 10.11 so I'll need to setup Sierra builders before I can work on this.

**Comment by bradfitz** [comment]
I've been running `go test -short net/http` in a loop for the past hour on my home Sierra desktop and haven't gotten a single error. I also tried `go test -short -run=TransportConcurrency -count=500` and `go test -short -run=TestTransportDiscardsUnneededConns -count=500`.

I suspect I might've accidentally fixed this during my recent test parallelization and de-flaking spree: 

cd670a61c193e6717400c6cc130484d6ad97c96b
276c29ff6da13ef7089075d8cd2172fe3d3956fb
f9d406ebeaa0af42d2a88bab498a44a91c6c03ee
27a3d30dd09cdd869b1b67f0154fa698bdf8ead2
2f2b57853eeccf854e8e47e5f77ff043d34b2a34

I'm going to close for now, but please reopen if you see it happen again or have ideas on how I can make it fail.
