### ISSUE TITLE
cmd/go: improve error message when unable to detect symlinked packages during go install

### ISSUE THREAD

**Issue by kris-nova** [golang/go#17662]
V 1.6.2 Darwin/AMD64

`filepath.Walk` does not (and will not) respect traversing symlinks. (See https://github.com/golang/go/issues/17451)

Can we improve the error message when a user attempts to run `go install` on a package that is a symlink? Right now the error message is ["warning: %q matched no packages\n"](https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/cmd/go/main.go#L576). 

That does not offer the user insight into why the package did not build as expected.

**Comment by bradfitz** [comment]
Kinda documentation. But also code. For Go 1.8 if trivial.
