### ISSUE TITLE
compress/gzip: avoid setting MTIME if Header.ModTime is zero

### ISSUE THREAD

**Issue by dsnet** [golang/go#17663]
The `gzip` writer always [writes the ModTime](https://github.com/golang/go/blob/c9517b1ffe7c99a3fd2a748fab51645bd674ad75/src/compress/gzip/gzip.go#L159) regardless of what the value is.

In most instances, the ModTime is the zero value because the user did not care what value to use. When the zero value is converted to a Unix timestamp, it's value is -62135596800, which cannot even be encoded into the gzip format since the MTIME field is a uint32.

The logic for gzip.go should only write the MTIME field if `!Header.ModTime.IsZero()`.

This issue came up in http://golang.org/cl/32260

\cc @rsc

**Comment by rsc** [comment]
Yes, we should definitely fix this. :-)
