### ISSUE TITLE
cmd/compile: optimizations to generated code on amd64

### ISSUE THREAD

**Issue by gopherbot** [golang/go#1766]
by **umbricola**:

<pre>What steps will reproduce the problem?
1. tar xf umbricola-go-defect-report-addloop1.tar
2. ./umbricola-go-defect-report-addloop1/addloop1_run.sh

What is the expected output?
Timing statistics similar to those below but with the modular and monolithic Go versions
having the same speed.

What do you see instead?
C version:
-1243309312
        0.50 real         0.50 user         0.00 sys
Modular Go version:
-1243309312
        0.86 real         0.85 user         0.00 sys
Monolithic Go version:
-1243309312
        3.02 real         3.01 user         0.00 sys

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g/6l

Which operating system are you using?
Mac OS X 10.5.8

Which revision are you using?  (hg identify)
9266c53a8fc0 tip

Please provide any additional information below.
The shell script compiles and measures the running time of three programs that each
compute and print the sum of the integers from
0 to 10^9 - 1 reduced modulo 2^32 (i.e., they accumulate the sum into an int and it
overwraps a lot).  The measurements I quoted above were run on my Mac laptop with a 2.0
GHz Core 2 (65 nm process) CPU.

The first program is a 386 binary compiled from C99 source addloop1_c.c with gcc -O3. 
It runs the 10^9 loop iterations in 0.50 s, i.e., one iteration per clock, which is the
best result I would realistically expect from a compiler.  The generated code is quite
natural: an add, an inc, and a cmp/jne pair eligible for macrofusion, which fit nicely
on execution ports 0, 1, and 5.

The second program is an x86-64 binary compiled with 6g/6l from Go sources
addloop1_sum.go and addloop1_modular.go.  The former contains the arithmetic loop as an
exported function that the main function in the latter file calls out to.  This version
deserves to be a little slower than the first program just because it's an x86-64 binary
running on a chip that can't do macrofusion in 64-bit mode.  Theoretically I'd expect
3/4 iterations per cycle, thus about 0.50 s * 4/3 = 0.67 s running time.  The observed
0.86 s suggests that Go is generating worse code than gcc here, but the speed is still
reasonable.  Unfortunately, I don't know a way to disassemble the code in a 6l binary,
so I don't know what the loop looks like.

The third program is another x86-64 binary compiled with 6g/6l.  This time there is only
one Go source file addloop1_monolithic.go, in which the main() function contains the
arithmetic loop.  Because we didn't change the loop, just inlined it in the main
function, I'd expect to see the same 0.86 s timing again.  Instead I got 3.02 s --- much
worse!  I can't guess how that happened, but I'm sure it's not the behavior you want.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/1766/0/umbricola-go-defect-report-addloop1.tar">umbricola-go-defect-report-addloop1.tar</a> (10240 bytes)

**Comment by ALTree** [comment]
I think this can be closed; the "modular" vs "monolithic" performance issue (which was the main problem here) is a thing of the past; I tested the monolithic version and it's as fast as I'd expect.

We're still slower than `gcc -O3`, and that's mainly because `gcc -O3` unrolls the loop **very** aggressively, while gc doesn't; but we know that and the function benchmarked here (`for i := 1; i < 1e9; i++ { sum += i }`) is not particularly notable, so it's not worth leaving the issue open just for that.
