### ISSUE TITLE
x/net/http2/h2i: tool is broken

### ISSUE THREAD

**Issue by raeesbhatti** [golang/go#17661]
### What version of Go are you using (`go version`)?

`go version go1.7.1 windows/amd64`
### What operating system and processor architecture are you using (`go env`)?

`Windows 10 Pro x64 1607`
### What did you do?

Follow the [demo guide](https://github.com/golang/net/blob/master/http2/h2i/README.md) provided for `h2i` tool:
- `go get golang.org/x/net/http2/h2i`
- `h2i google.com`
### What did you expect to see?

`h2` debug log for connection to `google.com`. Something like this:

```
Connecting to google.com:443 ...
Connected to 74.125.224.41:443
Negotiated protocol "h2-14"
[FrameHeader SETTINGS len=18]
  [MAX_CONCURRENT_STREAMS = 100]
  [INITIAL_WINDOW_SIZE = 1048576]
  [MAX_FRAME_SIZE = 16384]
[FrameHeader WINDOW_UPDATE len=4]
  Window-Increment = 983041
```
### What did you see instead?

```
Connecting to google.com:443 ...
Connected to 172.217.20.14:443
Negotiated protocol "h2"
The handle is invalid.
```

**Comment by bradfitz** [comment]
I suspect the `golang.org/x/crypto/ssh/terminal` package doesn't work on Windows.

**Comment by bradfitz** [comment]
Have you tried the Bash for Windows thing? Maybe it'll work there.

**Comment by raeesbhatti** [comment]
That didn't work also it results in some sys call error and then:
```
# golang.org/x/net/http2/hpack
/home/raees/go/src/golang.org/x/net/http2/hpack/huffman.go:14: undefined: sync.Pool
```

**Comment by bradfitz** [comment]
Um, I think you're using some ancient version of Go then. I'm not convinced you're actually using Go 1.7 as you think you are.

**Comment by raeesbhatti** [comment]
I've verified the version and it is `go version go1.7.1 linux/amd64` and here is the error:
```
raees@RAEES-PROBOOK:~$ go get golang.org/x/net/http2/h2i
# cd /home/raees/go/src/golang.org/x/crypto; git submodule update --init --recursive
package golang.org/x/crypto/ssh/terminal: read |0: interrupted system call
```
My guess is that Microsoft WSL team has not yet implemented the system calls used by this package.

**Comment by bradfitz** [comment]
Okay, closing this bug then. I'm not sure there's anything I can do.

**Comment by raeesbhatti** [comment]
On a second try, it actually worked without changing anything. The output text is displayed in a wired way but the tool seems to be working fine.

**Comment by alexbrainman** [comment]
I can reproduce this. And https://go-review.googlesource.com/32373 fixes my problem.

Alex
