### ISSUE TITLE
misc/cgo: testsanitizers can never succeed on a Linux host with strict virtual memory overcommit set

### ISSUE THREAD

**Issue by siebenmann** [golang/go#17689]
### What version of Go are you using (`go version`)?
go version devel +f4c7a12 Mon Oct 31 04:49:52 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?

If you attempt to build and test Go devel tip on a 64-bit Linux machine with strict virtual memory overcommit set, it will always fail because testsanitizers attempts to allocate many TB of virtual memory and strict VM overcommit disallows that. A typical error message is:

```
##### ../misc/cgo/testsanitizers
==28515==ERROR: MemorySanitizer failed to allocate 0xf0000000000 (16492674416640) bytes at address 10000000000 (errno: 12)
FATAL: MemorySanitizer can not mmap the shadow memory.
FATAL: Make sure to compile with -fPIE and to link with -pie.
FATAL: Disabling ASLR is known to cause this error.
FATAL: If running under GDB, try 'set disable-randomization off'.==28515==Process memory map follows:
[...]
==28515==End of process memory map.
exit status 77
FAIL: msan
[...]
2016/10/31 11:16:57 Failed: exit status 1
```

(Strict virtual memory overcommit is the sysctl `vm.overcommit_memory` set to '2'. Errno 12 is `ENOMEM`.)

This test error then fails the entire test run and some further tests don't run, reporting 'skipped due to earlier error'.  As far as I know this error is unavoidable on a 64-bit Linux machine with strict overcommit set, so I can't fault testsanitizers failing. However, since this failure is inevitable I think that either testsanitizers should be explicitly skipped on such a machine or failure of these tests should not make the overall test run fail and stop (some) further tests.

(This error has been happening for some time, but I only occasionally build Go on machines with strict overcommit set so I haven't gotten around to reporting it before now.)

**Comment by rsc** [comment]
@dvyukov and @ianlancetaylor, I can disable the tests on machines with vm.overcommit_memory=2, but the fact remains that the sanitizers don't work on such systems. Is that expected? Seems to be the case, but I wanted to make sure.

**Comment by dvyukov** [comment]
> sanitizers don't work on such systems. Is that expected?

Yes, it is expected. Sanitizers allocate tens of TBs of memory by design.
It's only Go version of tsan that allocates memory lazily.
