### ISSUE TITLE
database/sql: IsolationLevel constants are spelled incorrectly

### ISSUE THREAD

**Issue by kevinburke** [golang/go#17682]
Commit ce6aa2eb added three constants which contain a misspelled word - LevelReadUncommited, LevelReadCommited, LevelWriteCommited should be LevelReadUncommitted, LevelReadCommitted, and LevelWriteCommitted respectively.

I'm happy to submit a patch but not sure if they have to stay as-is or break the compatibility promise. A search on github.com for "LevelReadUncommited" returns only two results, the golang/go result, and a fork. https://github.com/search?q=LevelReadUncommited&ref=simplesearch&type=Code&utf8=%E2%9C%93

http://www.dictionary.com/browse/committed

**Comment by minux** [comment]
The commit has not been released yet, so we can change it if
necessary.
