### ISSUE TITLE
sync: speed up Mutex.Unlock

### ISSUE THREAD

**Issue by johnrs** [golang/go#17684]
### Proposal

I was looking at the Unlock method in mutex.go and I noticed something about line #110:
```
  if (new+mutexLocked)&mutexLocked == 0 {
```
It can be simplified to:
```
  if new&mutexLocked != 0 {
```
This does not change the functionality of Unlock in any way, other than to speed it up slightly.

### Benefit

A quick and dirty test on my machine showed about a 5% run time improvement when doing a Lock/Unlock in a tight loop.

  Before: 58.8-59.1 ns
  After:  55.6-56.0 ns

Note:  I did this in Jan 2016.  I discussed it with Dmitry and he recommended submitting it.  Then I misplaced it and didn't notice it till now.  Sorry for the delay!

**Comment by mvdan** [comment]
@johnrs you should use a benchmark with https://github.com/rsc/benchstat, that will give more useful results as to whether this change speeds up the function or not.

Also, I think you should open a CL instead of an issue for this. This issue is pretty much just a manual patch submission.

**Comment by josharian** [comment]
Please feel free to send a CL. Thanks. Today is the last day before the (three month) freeze, though.

**Comment by bradfitz** [comment]
I benchmarked this with benchstat and don't see any difference:

```
name                old time/op  new time/op  delta
MutexUncontended-4  8.37ns ± 0%  8.37ns ± 0%  -0.11%  (p=0.001 n=20+17)
```

I assume SSA is helping. Please reopen if you find otherwise, or just send a CL in February (or today, soon).
