### ISSUE TITLE
x/net/http2: if http1 Server's keep-alives are disabled, only do one request

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17717]
As part of #9478, I noticed the HTTP/2 server doesn't respect SetKeepAlivesEnabled.

Do that.

After the first http2 Server response, check:

```go
func (s *Server) doKeepAlives() bool {
```

And if it's false, start a graceful GOAWAY shutdown.

/cc @tombergan

**Comment by tombergan** [comment]
HTTP/2 does not support `Connection: keep-alive` or `Connection: close`.

http://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2
> HTTP/2 does not use the Connection header field to indicate connection-specific header fields

The HTTP/2 protocol is centered around the idea of multiple requests per connection. If someone wants one request per connection, they should just use HTTP/1. Maybe just update the SetKeepAliveEnabled docs?

**Comment by bradfitz** [comment]
Yeah, simplest case is just documentation.

Or we could even change the advertised ALPN protos at runtime to exclude "h2" if keep-alives are disabled. But h2 + immediate GOAWAY after first response isn't really worse than h1 + "Connection: close".

**Comment by rsc** [comment]
Sounds like there was a decision since there is now a CL. Change to NeedsFix?
