### ISSUE TITLE
runtime: parse option numbers set through environment correctly

### ISSUE THREAD

**Issue by martisch** [golang/go#17718]
on go tip runtime.atoi does not do any kind of overflow checks or error reporting.
which can lead to internal variables being set to surprising numbers without a warning.

### What did you do?

compile a test program:
```
package main

import "runtime"

func main() {
	print("runtime.MemProfileRate=", runtime.MemProfileRate, "\n")
}
```
https://play.golang.org/p/WhUyslK_Em

supply some number value flags:
$ GODEBUG=memprofilerate=10000000000000000000 ./test

### What did you expect to see?
runtime.MemProfileRate=10000000000000000000
or an error 
or a documented default value

### What did you see instead?
runtime.MemProfileRate=-8446744073709551616

**Comment by martisch** [comment]
https://golang.org/cl/32390 would fixes the atoi implementation and provides a ok return value such that call sites can report an error that the option could not be set correctly if need be.

**Comment by rsc** [comment]
Thanks @martisch. The CL you submitted fixes the issue as far as I am concerned. A bad setting in the environment is not cause for failing to run the program.
