### ISSUE TITLE
database/sql: Support for changing the username and password of an existing connection

### ISSUE THREAD

**Issue by F21** [golang/go#17727]
Opening as per the suggestion in https://groups.google.com/forum/#!topic/golang-nuts/_OakZP-dLZw

My use case for this feature it to support rotating username and passwords using [Vault](https://www.vaultproject.io/). Vault leases database usernames and passwords and forces clients to rotate them before expiry. Be able to update the username and password of an existing connection pool would be extremely useful.

All drivers currently use the DSN to pass in the username and password, so perhaps this could be generalized to updating the DSN of an existing database connection pool.

**Comment by bradfitz** [comment]
Sorry, I don't think we want to do this. Just re-open the database and with the new password.

/cc @kardianos
