### ISSUE TITLE
GOOS=android GOARCH=arm doesn't compile on amd64

### ISSUE THREAD

**Issue by erlanger** [golang/go#17736]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gocode"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build431324223=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Just compile a simple program:
```go
package main
import "fmt"
func main() {
   fmt.Printf("Hello")
}
```
```sh
$ env GOOS=android GOARCH=arm go build -o g1 g.go
# command-line-arguments
warning: unable to find runtime/cgo.a
/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘-marm’; did you mean ‘-mabm’?
```

### What did you expect to see?
The same as if I change GOOS to linux
```sh
$ env GOOS=linux GOARCH=arm go build -o g1 g.go
$
```
### What did you see instead?
See error above.

**Comment by ianlancetaylor** [comment]
In order to cross-compile for Android, you need to set the `CC` environment variable to a C cross-compiler.

For details on building for Android, please use a forum.  See https://golang.org/wiki/Questions.
