### ISSUE TITLE
go/types: export `Original` function (or perhaps method)

### ISSUE THREAD

**Issue by griesemer** [golang/go#17730]
go/types internally defines an original function that returns the original object of an alias, if so, or just the incoming object, otherwise.

This is useful externally, as well, similar to types.Underlying().

**Comment by griesemer** [comment]
cc: @alandonovan

**Comment by alandonovan** [comment]
I agree that this would be a useful package-level function.  (We cannot add a method to Object because that would break compatibility with user-defined implementations.)

**Comment by rsc** [comment]
Adding a method to Object is OK, @alandonovan. Object has unexported methods so there are no from-scratch user-defined implementations. At most there are user-defined implementations that embed some implementation provided by the go/types package.

**Comment by alandonovan** [comment]
Ah, I forgot about that.  Good point.

**Comment by griesemer** [comment]
Decision to back out current alias implementation. See #16339. Closing.
