### ISSUE TITLE
x/tools/go/gcimporter: update export data format version

### ISSUE THREAD

**Issue by griesemer** [golang/go#17734]
Tracking issue.

x/tools/go/gcimporter15/bexport.go still generates export data format version 1, but now that we can export aliases, we should probably update to the latest version. This is not urgent, but may avoid confusion down the road.

**Comment by griesemer** [comment]
cc: @alandonovan

**Comment by alandonovan** [comment]
It is somewhat urgent.  For example, Google's source code tools must understand Go 1.8 source and export data before we can start to evaluate 1.8rc1, which will ideally be a long time before the 1.8 release.

**Comment by griesemer** [comment]
We should still do this, even w/o aliases. We should have all importers understand the latest version.
