### ISSUE TITLE
x/crypto/acme/autocert: failed cert creation is never retried

### ISSUE THREAD

**Issue by niemeyer** [golang/go#17740]
When the creation of a certificate fails, the `certState` is being stored in `m.state` with an empty `cert` field, and there's no logic to retry the creation. On follow up requests the bogus state is returned and requests fail forever after.

Instead, it should retry after a short delay.

**Comment by x1ddos** [comment]
@niemeyer good point. It's a known behaviour, well at least for me. I was planning on improving it.

Define "short" and for how long would it need to keep retrying (in case of consecutive failure)?

**Comment by x1ddos** [comment]
Maybe a simpler way is to just remove the "bogus" state from in-memory map and retry on the next TLS hello. So, it would just seem like a new domain to the Manager.

How does it sound?

**Comment by bradfitz** [comment]
If you're under heavy load and push a misconfiguration, you don't want to be slamming LetsEncrypt with requests. I'd make sure you not speak out any ACME for, say, a minute after any ACME rejection. Or be smart about which errors incur which time penalties. Some might mean infinite. Some might be transient network failures and you could retry in seconds.

But I think just waiting for the next TLS hello to kick off the retry seems fine.

**Comment by robpike** [comment]
This is related to the Upspin bug:

https://github.com/upspin/upspin/issues/367

**Comment by x1ddos** [comment]
Thinking about this more, I'm leaning towards @bradfitz's suggestion - wait a minute and then remove the failed state, allowing next TLS hello to kick off a cert request again.

**Comment by x1ddos** [comment]
Something like this: https://golang.org/cl/41694
