### ISSUE TITLE
[question] inconsistent behaviour of type switch

### ISSUE THREAD

**Issue by kamilsk** [golang/go#17741]
### What did you do?

I ran code in play.golang.org

https://play.golang.org/p/a701GtehQQ
https://play.golang.org/p/GT51lpmogI

### What did you expect to see?

All cases work the same way.

### What did you see instead?

Second example doesn't compile
```
main.go:23: cannot convert v (type interface {}) to type int64: need type assertion
```

Maybe I missed something in docs?

**Comment by crawshaw** [comment]
Go doesn't use the issue tracker for questions. Please see https://golang.org/wiki/Questions.
