### ISSUE TITLE
x/mobile: `go get golang.org/x/mobile/...` reports errors

### ISSUE THREAD

**Issue by hyangah** [golang/go#17750]
% go get golang.org/x/mobile/...
package golang.org/x/mobile/bind/testpkg/javapkg
	imports Java/java/lang/Float: unrecognized import path "Java/java/lang/Float" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/javapkg
	imports Java/java/lang/Integer: unrecognized import path "Java/java/lang/Integer" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/javapkg
	imports Java/java/lang/System: unrecognized import path "Java/java/lang/System" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/javapkg
	imports Java/java/util/Collections: unrecognized import path "Java/java/util/Collections" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/javapkg
	imports Java/java/util/jar/JarFile: unrecognized import path "Java/java/util/jar/JarFile" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/objcpkg
	imports ObjC/Foundation: unrecognized import path "ObjC/Foundation" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/objcpkg
	imports ObjC/Foundation/NSDate: unrecognized import path "ObjC/Foundation/NSDate" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/objcpkg
	imports ObjC/Foundation/NSString: unrecognized import path "ObjC/Foundation/NSString" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/objcpkg
	imports ObjC/QuartzCore/CAMediaTimingFunction: unrecognized import path "ObjC/QuartzCore/CAMediaTimingFunction" (import path does not begin with hostname)
package golang.org/x/mobile/bind/testpkg/objcpkg
	imports ObjC/UIKit: unrecognized import path "ObjC/UIKit" (import path does not begin with hostname)

**Comment by mirtchovski** [comment]
instead of trying to compile everything recursively (and failing the tests, which aren't working even on the builders at the moment), you may want to install only the gomobile binary, which knows how to do the rest:

```
% go get golang.org/x/mobile/cmd/gomobile
% gomobile init
```
