### ISSUE TITLE
cmd/godoc: describe aliases

### ISSUE THREAD

**Issue by rsc** [golang/go#17763]
See test case in #17762.

godoc should handle aliases at least as much as described in #17762. Today it panics:

	$ cd go/src/cmd/doc/testdata
	$ godoc .
	panic: interface conversion: ast.Spec is *ast.AliasSpec, not *ast.ValueSpec
	
	goroutine 1 [running]:
	panic(0x15bffc0, 0xc4201d8c00)
		/Users/rsc/go/src/runtime/panic.go:531 +0x1cf
	go/doc.(*reader).filterSpecList(0xc4201a7698, 0xc4201d48e0, 0x1, 0x1, 0x40, 0xc4201d48c0, 0x1, 0x1)
		/Users/rsc/go/src/go/doc/exports.go:202 +0x195
	go/doc.(*reader).filterDecl(0xc4201a7698, 0x1974a00, 0xc4201d8080, 0x1975e01)
		/Users/rsc/go/src/go/doc/exports.go:229 +0xd2
	go/doc.(*reader).fileExports(0xc4201a7698, 0xc42014c980)
		/Users/rsc/go/src/go/doc/exports.go:246 +0x79
	go/doc.(*reader).readPackage(0xc4201a7698, 0xc4201d10e0, 0x0)
		/Users/rsc/go/src/go/doc/reader.go:550 +0x3aa
	go/doc.New(0xc4201d10e0, 0x1659242, 0x7, 0x0, 0xc4201d10e0)
		/Users/rsc/go/src/go/doc/doc.go:96 +0x7f
	golang.org/x/tools/godoc.(*handlerServer).GetPageInfo(0xc420192078, 0x1659242, 0x7, 0x1659242, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/rsc/src/golang.org/x/tools/godoc/server18.go:139 +0x75c
	golang.org/x/tools/godoc.(*Presentation).GetPkgPageInfo(0xc420192000, 0x1659242, 0x7, 0x1659242, 0x7, 0x0, 0x1659242)
		/Users/rsc/src/golang.org/x/tools/godoc/pres.go:159 +0x94
	golang.org/x/tools/godoc.CommandLine(0x196f3c0, 0xc42000e018, 0xc42018c120, 0xc420192000, 0xc42000c2f0, 0x1, 0x1, 0x2, 0x0)
		/Users/rsc/src/golang.org/x/tools/godoc/cmdline.go:62 +0xa9b
	main.main()
		/Users/rsc/src/golang.org/x/tools/cmd/godoc/main.go:326 +0x1390

**Comment by dlsniper** [comment]
Should be closed as it's been fixed in https://go-review.googlesource.com/c/32711/ but the link was wrong in the CL.
