### ISSUE TITLE
x/tools/playground: share blocked from Russia

### ISSUE THREAD

**Issue by mkevac** [golang/go#17765]
My public IP is 2a00:1ec8:77:101:7a24:afff:fe89:e7f3. According to https://www.iplocation.net/ it's Russia. And I am in Russia indeed.

DNS gives me California server for play.golang.org: 

```
$ dig play.golang.org

; <<>> DiG 9.10.4-P3-RedHat-9.10.4-2.P3.fc24 <<>> play.golang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61863
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;play.golang.org.		IN	A

;; ANSWER SECTION:
play.golang.org.	13	IN	A	172.217.22.177

;; AUTHORITY SECTION:
golang.org.		77248	IN	NS	ns4.google.com.
golang.org.		77248	IN	NS	ns2.google.com.
golang.org.		77248	IN	NS	ns1.google.com.
golang.org.		77248	IN	NS	ns3.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.		179243	IN	A	216.239.32.10
ns2.google.com.		179243	IN	A	216.239.34.10
ns3.google.com.		179243	IN	A	216.239.36.10
ns4.google.com.		179243	IN	A	216.239.38.10

;; Query time: 2 msec
;; SERVER: 192.168.4.170#53(192.168.4.170)
;; WHEN: Thu Nov 03 16:23:11 MSK 2016
;; MSG SIZE  rcvd: 206
```

But I don't see share button on play.golang.org and I get "Forbidden" when going to shared playground code.

I know that you have some restrictions for China according to open source playground code, but I am in Russia.

**Comment by bradfitz** [comment]
@broady, could you file an internal geolocation bugs like the previous ones we've filed?

**Comment by broady** [comment]
Interesting. Google also thinks this IP is in Russia. It might be specific to App Engine. I will follow up.
