### ISSUE TITLE
os/exec: example test setting Command.Stdout does not terminate

### ISSUE THREAD

**Issue by stapelberg** [golang/go#17768]
### What version of Go are you using (`go version`)?

```
go version go1.7.3 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/stapelberg/gocode"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build817336530=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

The following example test does not terminate:

```c
package example_test

import (
    "os"
    "os/exec"
)

func ExampleFoo() {
    cmd := exec.Command("/bin/sh", "-c", "sleep 999d")
    cmd.Stdout = os.Stdout
    cmd.Start()

    // OUTPUT:
    // foo
}
```

Removing the `cmd.Stdout = os.Stdout` line makes it terminate.

In case it matters, I’m running `go test -v example/...`, the above example is stored in `gocode/src/example/example_test.go`

### What did you expect to see?

I expected the test to fail.

### What did you see instead?

The test does not terminate.

**Comment by quentinmit** [comment]
@stapelberg Why did you expect the test to fail? The command is still running, so the test is still waiting for the output.

**Comment by stapelberg** [comment]
How is `testing` determining that stdout might still be written to? Can the condition be documented, so that the behavior is at least not a surprise?

**Comment by freeformz** [comment]
I'm pretty sure this is related to the use of an Example and how it captures os.Stdout. When cmd.Stdout == nil it's effectively set to /dev/null and then closed during Start().

Also the use of exec.Start() isn't exactly correct as Start() doesn't wait for the program to complete, to do so you need to call cmd.Wait().

**Comment by stapelberg** [comment]
> How is testing determining that stdout might still be written to? Can the condition be documented, so that the behavior is at least not a surprise?

It seems like `runExample` is redirecting os.Stdout to a pipe and reads until EOF.

I think adjusting the documentation to mention that all uses of os.Stdout in an example test must close os.Stdout in order to have the example test terminate is sufficient to close this issue.

**Comment by bradfitz** [comment]
I'm not sure where we'd document this, or even that we'd want to. Examples are supposed to be simple. If you're doing these sorts of shenanigans, I think this sort of pain is exactly the sort of feedback you need to stop writing complicated examples.

This works fine for me:

```go
func ExampleFoo() {
        cmd := exec.Command("/bin/sh", "-c", "echo hello")
        cmd.Stdout = os.Stdout
        if err := cmd.Run(); err != nil {
                log.Fatal(err)
        }

        // OUTPUT:                                                                                                         
        // hello                                                                                                           
}
```

So I don't think there's anything to do here.
