### ISSUE TITLE
cmd/doc: describe aliases

### ISSUE THREAD

**Issue by rsc** [golang/go#17762]
I added this to cmd/doc/testdata/pkg.go:

	diff --git a/src/cmd/doc/testdata/pkg.go b/src/cmd/doc/testdata/pkg.go
	index 924daa1..0a5ecdc 100644
	--- a/src/cmd/doc/testdata/pkg.go
	+++ b/src/cmd/doc/testdata/pkg.go
	@@ -5,6 +5,13 @@
	 // Package comment.
	 package pkg
	 
	+import (
	+	"io"
	+	"math"
	+	"text/template"
	+	"unicode"
	+)
	+
	 // Constants
	 
	 // Comment about exported constant.
	@@ -172,3 +179,12 @@ const (
	 )
	 
	 const ConstGroup4 ExportedType = ExportedType{}
	+
	+const MathPi => math.Pi
	+
	+func MathSin => math.Sin
	+func TemplateNew => template.New
	+
	+var UnicodeVersion => unicode.Version
	+
	+type UnicodeRangeTable => unicode.RangeTable

But then go doc cmd/doc/testdata does not show anything about these, and in fact go doc cmd/doc/testdata.TemplateNew says "no symbol TemplateNew".

This is very important to fix before the release. It would be fine if the definition just showed the alias and synthesized a comment 

	// TemplateNew is an alias for text/template.New.
	func TemplateNew => template.New

**Comment by griesemer** [comment]
Decision to back out current alias implementation. See #16339. Closing.
