### ISSUE TITLE
go/types: incorrect Info.Uses map entry for struct { a } where a is an alias

### ISSUE THREAD

**Issue by alandonovan** [golang/go#17778]
The Uses map entry for `struct { a }` ought to be the Alias object for type alias a, not its original type.
However, the logic in  `(*Checker).structType` calls recordUse on the TypeName derived from the computed type of the field, rather than the object (type or type alias) with which the field is declared.

In at least some cases, such as a simple ident, the recordUse call made by the add function within structType is redundant, since check.typeExpr(f.Type) already calls recordUse.

**Comment by griesemer** [comment]
Decision to back out current alias implementation. See #16339. Closing.

See also: https://go-review.googlesource.com/32837
