### ISSUE TITLE
cmd/stringer: master required Go 1.8, but not released yet

### ISSUE THREAD

**Issue by mitchellh** [golang/go#17783]
### What version of Go are you using (`go version`)?

go1.7.3

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

`go get -u golang.org/x/tools/cmd/stringer`

### What did you expect to see?

`stringer` is installed

### What did you see instead?

Errors related to Go 1.8 AST nodes. Go 1.8 isn't released yet so I'd expect the standard installation flow to continue working with Go 1.7 until then.

It looks like this commit made the change: https://github.com/golang/tools/commit/9a286cdc334bcda1296aaa1c8cc85c2d5d64dac7

**Comment by bradfitz** [comment]
Yes, the whole tools repo is broken on the dashboard now for Go 1.6 and Go 1.7.

Looks like it was:

commit 9a286cdc334bcda1296aaa1c8cc85c2d5d64dac7
Author: @alandonovan 
Date:   Thu Nov 3 17:19:55 2016 -0400

    cmd/stringer: reject Go 1.8 type aliases
    
    Change-Id: I56e615bf202ca2018602c93e66ecdbc2577335e2
    Reviewed-on: https://go-review.googlesource.com/32731
    Reviewed-by: @griesemer

**Comment by bradfitz** [comment]
@alandonovan, considering this is breaking external users, please prioritize this over other Go 1.8 stuff.

**Comment by alandonovan** [comment]
Reverted, sorry about that.
