### ISSUE TITLE
use EncodedLen function consistenly in "encoding/hex" package Decode functions

### ISSUE THREAD

**Issue by crackerplace** [golang/go#17782]
### What version of Go are you using (`go version`)?
go version go1.6 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux(ubuntu 14.04) and amd64

### What did you do?
The DecodeString function in hex.go is used to return the bytes represented by a hexadecimal string.This function internally invokes the decode function by passing it dest and src slices.So the length of des slice is calculated using DecodedLen function ,but it is not used consistently in both these functions.

https://github.com/golang/go/blob/master/src/encoding/hex/hex.go#L97
In DecodeString function ,DecodedLen function is used to create a dest slice.This is half the length of src slice.
Now in the same DecodeString function Decode(dst, src) function is invoked in which it is mentioned as below.But inside this function in the for loop ,len(src)/2 is used for filling up the dest slice.So I feel it would be better to use the same DecodedLen(len(src)) in this function as well so as to be consistent and also as per what is mentioned in this methods doc.

"Decode decodes src into DecodedLen(len(src)) bytes,returning the actual number of bytes written to dst. "

Would be interested to work on this change,if the community feels this change is fine to be incorporated.This is not any bug or performance improvement as such but to make the code consistent and clean.Do let me know your thoughts.

**Comment by bradfitz** [comment]
I'm not sure it's worth changing. DecodedLen is there mostly for symmetry with other packages where the function is less trivial. But reading `/2` is very clear. There is no mystery about what it does. And it's much shorter than DecodedLen.

Let's just keep it as-is.
