### ISSUE TITLE
local package a import a

### ISSUE THREAD

**Issue by seanchann** [golang/go#17787]
$ go version
go version go1.7.1 linux/amd64

$ go env
GOARCH="amd64"
GOBIN="/home/seanchann/source/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/seanchann/source/golang:/home/seanchann/pgitlab/cloud"
GORACE=""
GOROOT="/home/seanchann/source/software/go"
GOTOOLDIR="/home/seanchann/source/software/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build128521881=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

use:
```
package a

import (
  test "xxx/pkg/a"
) 

var test  test.TestStruct
```
compile error:  undefined: a.TestStruct

how to fix it , thanks!

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions
