### ISSUE TITLE
spec: clarify meaning of alias decls in sequence of "enum" const declaration

### ISSUE THREAD

**Issue by griesemer** [golang/go#17784]
```
package main

import "math"
import "fmt"

const (
	a = iota
	b
	c => math.Pi
	d
)

func main() {
	fmt.Println(a, b, c, d)
}
```
prints
```
0 1 3.141592653589793 2
```
It probably shouldn't be allowed in the first place. Certainly the output is wrong (iota should be incremented with each semicolon).

**Comment by mdempsky** [comment]
>  Certainly the output is wrong (iota should be incremented with each semicolon).

Currently the spec says iota's value increments after each ConstSpec, and AliasSpec is disjoint from ConstSpec.  So I think replacing "d" with "d = iota" would logically assign 2 to d, under the current wording.

That said, if we did want to change it to increment at semicolons, I'm not opposed to that.  I just expect in practice it won't really matter.  If we choose to increment only after ConstSpecs, users can still include blank ConstSpecs next to AliasSpecs to increment iota; conversely, they can move AliasSpecs out-of-line to prevent them from incrementing iota.

**Comment by alandonovan** [comment]
I agree with Matthew that the current interpretation is clear, and that it matters little in practice.  I also think the current interpretation is defensible: iota shouldn't increment after an alias declaration that can't possibly use it.

**Comment by griesemer** [comment]
@mdempsky, @alandonovan Good point - with the current spec, incrementing iota with each ConstSpec is the same as incrementing with each semicolon...

There's a simpler solution: Do not alias const aliases in the first place. Just something to keep in mind.

**Comment by jimmyfrasche** [comment]
If you replace `=>` with `=` it prints

0 1 3.141592653589793 3.141592653589793 ( https://play.golang.org/p/4xOWo5vx8P )

Since => and = are essentially the same for consts, I'd expect them to behave identically.

**Comment by rsc** [comment]
Locking because aliases are no longer proposed.
