### ISSUE TITLE
cmd/vet: printfunc false negative on struct without String method

### ISSUE THREAD

**Issue by josharian** [golang/go#17798]
```go
package main

import "fmt"

type T int

func (T) String() string { return "T" }

type S struct {
	t T
}

func main() {
	var t T
	fmt.Printf("%s\n", t)
	var s S
	fmt.Printf("%s\n", s)
}
```

```bash
$ go tool vet x.go
$ go run x.go 
T
{%!s(main.T=0)}
```

vet should know that S isn't a fmt.Stringer. The printfunc's "satisfies interface" check needs improvements. Related is #17057.

cc @robpike @valyala

**Comment by valyala** [comment]
I'll look into this and the #17057 on the weekend.

**Comment by valyala** [comment]
FYI, it looks like the cl 28959 breaks printf check on `errror` interfaces:
```go
err := errors.New("foobar")
fmt.Printf("%d", err) // vet silently skips this
```

**Comment by valyala** [comment]
I think it would be better to fix these issues in go 1.8.

**Comment by josharian** [comment]
CL 28959 doesn't change cmd/vet at all. It only changes cmd/vet/all, which is a script that runs cmd/vet over the standard library.

> I think it would be better to fix these issues in go 1.8.

If the changes are fairly safe and we can get them in soon, I think that's fine.

**Comment by josharian** [comment]
> FYI, it looks like the cl 28959 breaks printf check on errror interfaces:

Btw, this is intentional. See #16314.

**Comment by valyala** [comment]
This looks like a bug in package `fmt` - it must properly print all the struct fields if they implement `fmt.Stringer` according to the rule:

> For compound operands such as slices and structs, the format applies to the elements of each operand, recursively, not to the operand as a whole.

In this case struct `S` contains only a single field of type `T`, which implements Stringer. So `fmt.Printf` must print contents of the struct - `{T}` instead of printing `{%!s(main.T=0)}`.

`fmt.Printf` works as expected for slices, arrays and maps with `fmt.Stringer` values, but doesn't work for structs:

```go
type S [5]T
type S []T
type S map[string]T
```

**Comment by valyala** [comment]
cc'ing @ALTree , @martisch and @robpike

**Comment by martisch** [comment]
```
type S struct {
	t T
}
```

the field t is not exported. If t is changed to be exported fmt will print {T}. fmt is in another package and does not have access to call the String method of t if it is not exported.

**Comment by mvdan** [comment]
CL was marked as R=go1.10, so moving the issue milestone too.
