### ISSUE TITLE
go/constant: BinaryOp does not support relational operators on numbers

### ISSUE THREAD

**Issue by dominikh** [golang/go#17797]
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What did you do?
https://play.golang.org/p/Paqll33YBG

### What did you expect to see?
`false`

### What did you see instead?
```
panic: invalid binary operation 0 < 0

goroutine 1 [running]:
panic(0x132680, 0x1050a138)
	/usr/local/go/src/runtime/panic.go:500 +0x720
go/constant.BinaryOp(0x1c0e20, 0x1050e160, 0x28, 0x1c0e20, 0x1050e168, 0x1050e0f8, 0x0, 0x0)
	/usr/local/go/src/go/constant/value.go:1110 +0x2c0
main.main()
	/tmp/sandbox478253161/main.go:11 +0xa0
```

**Comment by quentinmit** [comment]
This might be too late for 1.8, depending on how much work it is to fix.

**Comment by dhananjay92** [comment]
`BinaryOp()` does not handle comparison operations, [`Compare()`](https://golang.org/pkg/go/constant/#Compare) does. Is it supposed to?
If not, we should give more helpful message saying that `op X is not supported`, and put that in doc as well (that would be trivial and can be done in time for 1.8).

**Comment by dominikh** [comment]
I did not see `Compare`. I think a doc change on `BinaryOp` should suffice for now.
