### ISSUE TITLE
http: no way to request pipeling

### ISSUE THREAD

**Issue by jech** [golang/go#17799]
Consider the following:

    func someLengthyOperation() {
            time.Sleep(10 * time.Second)
    }

    func handler(w http.ResponseWriter, req *http.Request) {
            log.Printf("%v %v %v", req.Method, req.Proto, req.URL)
            someLengthyOperation()
            w.Header().Set("content-type", "text/plain")
            io.WriteString(w, "Hello, world!\n")
    }

When a client pipelines multiple requests to this handler, the handler is not invoked until the first request has finished processing.  While this is probably the right default, there appears to be no way to request the increased concurrency that pipelining makes possible.

Note that doing that right is probably not completely trivial.  In particular, in the second request the write to w needs to either block or buffer the output until the first request has completed.

I'm using the following highly refined server tester (patent pending):

    #!/bin/sh
    nc localhost 8080 <<EOF
    GET / HTTP/1.1
    Host: locahost

    GET / HTTP/1.1
    Host: localhost

    EOF

**Comment by bradfitz** [comment]
I do not intend to implement pipelining, since ~0 clients in the wild use it. There's a comment in the source code saying a bit more.

Use HTTP/2 instead, which Go implements.

**Comment by bradfitz** [comment]
To be clear, we support pipelining just fine. We just don't launch separate Handler goroutines for each one.

**Comment by jech** [comment]
> I do not intend to implement pipelining, since ~0 clients in the wild use it.
> There's a comment in the source code saying a bit more.

Right, found it.

> Use HTTP/2 instead, which Go implements.

With all due respect, if I did control the clients, I'd be using either
Websockets or raw TCP.  (Let alone the issue of debugging HTTP/2 using
tcpdump and friends, since it doesn't run over plain TCP.)

Thanks for your replies, Brad.

**Comment by bradfitz** [comment]
Out of curiousity, which clients of yours are doing pipelining?

**Comment by jech** [comment]
> Out of curiousity, which clients of yours are doing pipelining?

I *swear* I'd seen pipelined requests from both Firefox and Chromium in
the past, but now that you've caused me to check, it looks like recent
versions disable it by default.  So it looks like APT and Polipo are the
only aggressively pipelining clients nowadays...  That sucks.

(While we're having an enjoyable off-topic chat on the issue tracker --
have you played with Websockets in Go?  It's so easy it's not even funny.)

**Comment by bradfitz** [comment]
I think Firefox turned it on briefly by default once (very briefly), but I don't remember Chrome ever doing it.

Yes, I use WebSockets in Go for Camlistore. I'm a fan.
