### ISSUE TITLE
net/http: document more how to abort a response from Handlers

### ISSUE THREAD

**Issue by jech** [golang/go#17790]
HTTP/1.1 doesn't provide a way to signal an error to the client after we have started writing out a body (not sure about HTTP/2).  When serving a chunked reply, an error can only be signaled by interrupting the connection without terminating the chunked framing. 

I'm currently doing the following to abort a reply prematurely, which is less than obvious and does nothing useful with HTTP/2:

    hj, ok := w.(http.Hijacker)
    if ok {
            conn, _, err := hj.Hijack()
            if err != nil {
                    return;
            }
            conn.Close()
    }
    return

(This can be tested with curl, which should display "transfer closed with outstanding read data remaining" when this code triggers.)

Please provide an official, documented way to brutally interrupt a reply after the headers have been sent.

**Comment by bradfitz** [comment]
Calling `panic` works for both http1 and http2 and does the right thing in both, and we have tests for both.

See https://github.com/golang/go/issues/16542#issuecomment-236288246 for some background.

The docs already say:

> If ServeHTTP panics, the server (the caller of ServeHTTP) assumes that the effect of the panic was isolated to the active request. It recovers the panic, logs a stack trace to the server error log, and hangs up the connection.

I suppose you want a way to do this without the stack trace, though?

I thought we had a bug open about that, but I can't find it, so we'll use this one. Thanks for filing.

**Comment by jech** [comment]
>     If ServeHTTP panics [...] hangs up the connection.

Ah, right.

> I suppose you want a way to do this without the stack trace, though?

Yes, this is meant to happen when the backend times out, and it's part of
the normal behaviour of the application.

-- Juliusz

**Comment by rhysh** [comment]
I've found that `runtime.Goexit()` and `panic(nil)` both work well for this—they interrupt the request and do not cause a stack track to be printed. @bradfitz , are these behaviors intentional and supported?

https://play.golang.org/p/96dhROeoTh
https://play.golang.org/p/g_1P56OIKr

**Comment by bradfitz** [comment]
@rhysh, neither of those were intentional. `panic(nil)` looks like it only works for HTTP/1. In the http2.Server, the code looks like:

```go
// Run on its own goroutine.                                                                                                                                                                                                                           
func (sc *serverConn) runHandler(rw *responseWriter, req *http.Request, handler func(http.ResponseWriter, *http.Request)) {
        didPanic := true
        defer func() {
                rw.rws.stream.cancelCtx()
                if didPanic {
                        e := recover()
                        // Same as net/http:                                                                                                                                                                                                           
                        const size = 64 << 10
                        buf := make([]byte, size)
                        buf = buf[:runtime.Stack(buf, false)]
// ...
                        sc.logf("http2: panic serving %v: %v\n%s", sc.conn.RemoteAddr(), e, buf)
                        return
                }
                rw.handlerDone()
        }()
        handler(rw, req)
        didPanic = false
}
```

Likewise, it looks like http2.Server would interpret a `runtime.Goexit` as if it were a panic.

I suppose we could make that the official way, though. One one official way.

I think I'd prefer to make an explicit panic value, though, so if you're using a different http server hosting http.Handlers and that implementation forgets to do the `recover()` thing, at least the error message will be explicit about the Handler's intentions, rather than a mystery panic.

**Comment by jech** [comment]
Thanks, Brad.
