### ISSUE TITLE
x/net/http2: server ignores GOAWAY

### ISSUE THREAD

**Issue by tombergan** [golang/go#17800]
processFrame doesn't handle GOAWAY:
https://github.com/golang/net/blob/master/http2/server.go#L1137

Firefox apparently sends GOAWAY after a connection is idle, but this frame is ignored by our http2 server. With VerboseLogs=true, I see:

```plain
2016/11/04 21:27:28 http2: server read frame GOAWAY len=8 LastStreamID=2 ErrCode=NO_ERROR Debug=""
2016/11/04 21:27:28 http2: server ignoring frame: [FrameHeader GOAWAY len=8]
```

Is this intentional?

/cc @bradfitz

**Comment by bradfitz** [comment]
What should the server do? I forget what the spec says here. Intuitively, I'd think the server doesn't care if the client wants to go away.

**Comment by tombergan** [comment]
I just reread [Section 6.8](http://httpwg.org/specs/rfc7540.html#GOAWAY). The main effects of GOAWAY are: (a) it tells the peer which requests have been processed, and (b) it stops the peer from creating new requests (so the connection eventually quiesces and shuts down gracefully).

(a) is only meaningful when the server tells the client to GOAWAY (so the client knows which POSTs were handled). (b) means the server shouldn't send new pushes. So maybe the only effect is that the server should disable push upon receiving a GOAWAY?

I agree this doesn't seem very important.

**Comment by bradfitz** [comment]
> So maybe the only effect is that the server should disable push upon receiving a GOAWAY?

SGTM. Want to send a CL for that?

**Comment by tombergan** [comment]
Sure, I'll get to that next week.
