### ISSUE TITLE
http.Request Context() results in -> type context.Context has no field or method WithValue

### ISSUE THREAD

**Issue by JakeKalstad** [golang/go#17806]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
`
package main

import "net/http"

func appVersionMiddleWare(next http.Handler) http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		appV := 1
		ctx := req.Context()
		ctx.WithValue(ctx, "APP", appV)
		next.ServeHTTP(rw, req.WithContext(ctx))
	})
}
`

### What did you expect to see?
Compilation

### What did you see instead?
ctx.WithValue undefined (type context.Context has no field or method WithValue)
https://golang.org/src/context/context.go?s=14326:14386#L437

**Comment by bradfitz** [comment]
You have two problems:

1) WithValue is in the `context` package, not on the `context.Context` interface.
2) don't use string context keys. See #17293

Also, use three backticks to do quoted code on Github, not one.

**Comment by JakeKalstad** [comment]
Ah, thanks a million. It must be getting late.
