### ISSUE TITLE
doc: contribute.html is long and wordy

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17802]
Tracking bug for making the contribution process seem less intimidating, forked from #17794.

Observations:

* contribute.html is long and wordy. It might be good for some users, but it scares other users.

Maybe we need a high-level summary at the top showing the brief steps, with links to more info, rather than making users read a book first.

Also, I had an idea to write a go-gettable tool to walk people through the contribution process step-by-step, inspecting their httpcookies (for Gerrit), CLA state, git config, git-codereview, etc, and telling them what to do next. I want the instructions for contributors to just be:

```
$ go get go4.org/tools/gocontribute
$ gocontribute
```

And then the tool would say what needs to be done next.

/cc @quentinmit @robmccoll

**Comment by josharian** [comment]
Yes please. Anything we can do to make the barrier to entry lower will help a lot. We lose a lot of talented (and thus busy) potential contributors at step 1.

**Comment by mvdan** [comment]
It's also longer than it could be because there are several "git aficionados" and "git terms" bits. Perhaps you should make a very short guide for newbies, ignoring all git internals, and a separate advanced information page for those who are already familiar with `git-codereview` and `git` gitself.

**Comment by bradfitz** [comment]
No reason to tie this to Go 1.8. We can backport the docs later too, so it can go live on the website unrelated to the Go release cycle.

**Comment by bradfitz** [comment]
Bumping this to Go 1.10 for now. The recent reorganization helped.

The `golang.org/x/tools/cmd/go-contrib-init` tool is pretty nice now, but we could polish it up and recommend it during the Go 1.10 cycle.

**Comment by bradfitz** [comment]
Actually, we can drop the note in Go 1.9.
