### ISSUE TITLE
go test -bench shouldn't complain about no tests

### ISSUE THREAD

**Issue by natefinch** [golang/go#17814]
go test -bench shows `testing: warning: no tests to run` if there are no unit test functions in the current directory.  go test -bench shouldn't care if there are tests, it's not running tests.

Note that adding a simple `func TestFoo(t *testing.T){}` silences the error, but that shouldn't be required.

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?
// in a directory with benchmarks, but no tests:
`go test -bench Foo` 

### What did you expect to see?
\<benchmark output\>

### What did you see instead?
testing: warning: no tests to run
\<benchmark output\>

**Comment by dominikh** [comment]
Should be fixed by 11ff4b21f253f1c8a5a63608b0108a1438378c20

**Comment by natefinch** [comment]
Ahh yep, fixed in tip. Thanks!
