### ISSUE TITLE
net/http/fcgi: dead link in docs

### ISSUE THREAD

**Issue by natefinch** [golang/go#17815]
Package docs state

> The protocol is defined at http://www.fastcgi.com/drupal/node/6?q=node/22

But that link is dead

### What version of Go are you using (`go version`)?
1.7/tip

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
went to https://golang.org/pkg/net/http/fcgi/
same on https://tip.golang.org/pkg/net/http/fcgi/

### What did you expect to see?
A valid link to info about fastcgi.

### What did you see instead?
http://www.fastcgi.com/drupal/node/6?q=node/22
which is a dead link

**Comment by ALTree** [comment]
One backup that says `v 1.4 2002/02/25`

https://htmlpreview.github.io/?https://github.com/FastCGI-Archives/fcgi2/blob/master/doc/fcgi-spec.html

Another with `v 1.1.1.1 2000/08/21`

http://www.mit.edu/~yandros/doc/specs/fcgi-spec.html

Not sure what version the go package implements.

**Comment by 0xmohit** [comment]
The two don't seem to differ<sup>[*]</sup> in content apart from the CVS header you've highlighted.  Another difference is the link to "The WWW Common Gateway Interface Version 1.1" (both of which don't work!).

Wikipedia also [tells](https://en.wikipedia.org/wiki/FastCGI#External_links) that the primary link is offline and mentions these two.

<sup>[*]</sup> As observed using `diff` and `lynx -dump`.
