### ISSUE TITLE
cmd/cover: Avoid importing atomic package if not used

### ISSUE THREAD

**Issue by dhananjay92** [golang/go#17817]
### What did you do?
```shell
$ cat ~/tmp/test/haha.go
package haha

type A struct{
	i int
}

$ go tool cover -mode=atomic ~/tmp/test/haha.go
package haha

import _cover_atomic_ "sync/atomic"

type A struct {
	i int
}

var _ = _cover_atomic_.AddUint32

var GoCover = struct {
	Count     [0]uint32
	Pos       [3 * 0]uint32
	NumStmt   [0]uint16
} {
	Pos: [3 * 0]uint32{
	},
	NumStmt: [0]uint16{
	},
}
```

### What did you expect to see?
If not needed, `sync/atomic` shouldn't be imported. Expected to see instrumented code like below
```shell
$ go tool cover -mode=atomic ~/tmp/test/haha.go
package haha

type A struct {
	i int
}

var GoCover = struct {
	Count     [0]uint32
	Pos       [3 * 0]uint32
	NumStmt   [0]uint16
} {
	Pos: [3 * 0]uint32{
	},
	NumStmt: [0]uint16{
	},
}
```

### What did you see instead?
`sync/atomic` was imported, even though it's not used (well, except for blank assignment, but that's to prevent unused compiler errors).

**Comment by bradfitz** [comment]
Why does it matter to you?

**Comment by dhananjay92** [comment]
This is not critical, but it's better if we can avoid importing unused dependencies. Looks like it's easier to do: [golang.org/cl/32763](http://golang.org/cl/32763)

**Comment by dhananjay92** [comment]
As discussed in the CL, this adds more complexity for less value. Closing the issue.
