### ISSUE TITLE
cmd/go: get hangs indefinitely for github.com/cockroachdb/cockroach

### ISSUE THREAD

**Issue by crackerplace** [golang/go#17810]
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What version of Git are you using (`git version`)?
git version 2.10.2

My **~/.gitconfig** is empty

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/OSS/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build565192650=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
a)When I run below,it completes in less than **30 seconds** succesfully
go get -d -x -v github.com/uber-go/ratelimit 

b)When I run below,it completes in **3 mins** succesfully
go get -d -x -v github.com/astaxie/beego

c)When I run below,it completes in **30 mins** succesfully
go get -d -v -x github.com/chrislusf/glow

d)When I run below,it hangs indefinitely.I tried even waiting for 2 hours,but still it just hangs.
**Command** : go get -d -x -v github.com/cockroachdb/cockroach
**Output** : 
github.com/cockroachdb/cockroach (download)
cd .
git clone https://github.com/cockroachdb/cockroach /home/OSS/go/src/github.com/cockroachdb/cockroach

How should I resolve this issue.I have seen other similar ones such as [this](https://github.com/golang/go/issues/16104)  and [this](https://github.com/golang/go/issues/13453),but none of them helped me in getting past this issue inspite of setting GIT_SSH_COMMAND='ssh -o ControlMaster=no'.

Also,what are the other options to install cockroachdb or any other go package ? Not sure if git clone works as it might not get dependent packages ?

Thanks

**Comment by josharian** [comment]
What happens if you directly run `git clone https://github.com/cockroachdb/cockroach`?

**Comment by crackerplace** [comment]
git clone works instantly.No issues with it.

**Comment by myitcv** [comment]
I'm seeing some bizarre, as-yet-unconfirmed Github issues at the moment.... issues that appear to be related to the network route to Github and even then, only effecting certain repos.

**Comment by crackerplace** [comment]
Looks like the time to start downloading the package is proportional to the code base size.This is what I could observe based on different codebase sizes that I tried testing.Finally I was able to download cockroachdb.But this is like so slow,not sure where it is going wrong.

**Comment by quentinmit** [comment]
Your 30 minute clone ("glow") takes a few seconds on my machine. If you don't have any special ControlMaster configuration, there is probably something wrong with your network connection. If you're willing to make a slight change to Go's source code, we can hopefully find out more about what's going on. If you add "--progress" to the clone command at

https://github.com/golang/go/blob/master/src/cmd/go/vcs.go#L143

and then reinstall Go (with `make.bash`), -v should show the progress of the git clone.

**Comment by crackerplace** [comment]
@quentinmit I tried installing go from source and running ./all.bash and go get is working fine both on master and go1.7.3 tag.
Btw , my previous go binary installation is working fine(go get) and issue might be with github or network.

Thanks for your inputs.I will be able to make changes next time in case of any issue and debug better.
