### ISSUE TITLE
context: documentation could suggest how to use Context key types efficiently

### ISSUE THREAD

**Issue by nizsheanez** [golang/go#17826]
https://github.com/golang/go/issues/17293 - defined that usage of basic types is terrible and proposed to use private type `type key int`. 
But it cause allocation on each usage of context. 
We can avoid allocation, by usage `type key interface{}`
Here is test:
```go
package test

import (
	"context"
	"testing"
)

type key interface{}
var keyInterface key = 0

type keyIntType int
var keyInt keyIntType = 0

type List struct{}

func BenchmarkInterfaceKey(b *testing.B) {
	ctx := context.Background()
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			ctx.Value(keyInterface)
		}
	})
}

func BenchmarkIntKey(b *testing.B) {
	ctx := context.Background()
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			ctx.Value(keyInt)
		}
	})
}

```

Result: 
```
BenchmarkIntKey-8         	500000000	        10.2 ns/op	       8 B/op	       1 allocs/op
BenchmarkInterfaceKey-8   	5000000000	         1.36 ns/op	       0 B/op	       0 allocs/op
```

Does it make sense to use `type key interface{}` in docs?

**Comment by bradfitz** [comment]
No need for that. You can just do:

```go
var FooKey interface{} = foo
```

And the allocation (if any) will only be done once at program start-up, and then you can use FooKey as a key allocation-free whenever.

Or make your key be an empty struct type:

```go
type MyKey struct{}
```

And then just:

```go
     context.WithValue(ctx, MyKey{}, val)
```

... because putting `MyKey{}` (an empty struct) into an interface also doesn't allocate.

**Comment by nizsheanez** [comment]
I found that usage of `type key interface{}` cause conflicts:
```go
type structType1 struct{}
type structType2 struct{}
var key1 structType1
var key2 structType2

type interfaceType1 interface{}
type interfaceType2 interface{}
var key3 interfaceType1 = 1
var key4 interfaceType2 = 1

func main() {
	ctx := context.Background()

	ctx = context.WithValue(ctx, key1, "Yes!")
	fmt.Printf("%s\n", ctx.Value(key2))

	ctx = context.WithValue(ctx, key3, "Sure!")
	fmt.Printf("%s\n", ctx.Value(key4))
}

// Result:
// StructKey: %!s(<nil>)
// InterfaceKey: Sure!
```

Yes, usage of `interface{}` is a bad idea, but `struct{}` look good. 
For me looks valuable to:
Recommend don't use `type key interface{}`
Recommend to use empty struct type: 
```go
type keyType struct{}
...
context.WithValue(ctx, keyType{}, val)
``` 
or with global variable (looks more natural)  
```
type keyType struct{}
type key keyType
...
context.WithValue(ctx, key, val)

Also now docs have `The key type is unexported to prevent collisions with context keys defined in
// other packages.` -  with `type key struct{}` it can be exported, different types don't cause collisions even if they in same package.

**Comment by bradfitz** [comment]
I think you're confused about how interfaces and types in general work in Go.

Your key3 and key4 are identical.

See https://play.golang.org/p/fyBgLguaOb and http://research.swtch.com/interfaces

**Comment by nizsheanez** [comment]
Actually, I and people in my team know, but it coming to head only when facing issue :-) 
Same when people think `need to use cheap data type here` - they use `int` instead of `struct{}` (they just don't remember about existing of `struct{}` in this time, even they know that it's cheaper) 

Anyway, benchmark int vs empty struct has only 2 time difference in speed: 
```
BenchmarkStructKey-8   	300000000	         4.45 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntKey-8   	200000000	         8.24 ns/op	       8 B/op	       1 allocs/op
```

Even speed is almost same, I think collision-free is valuable in `type key struct{}` usage
