### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by deltaskelta** [golang/go#17824]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.6.3 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Jeff/Development/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

`go run euler17.go`

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

It is not reproducible, it seems to happen intermittently with a valid go program...

### What did you expect to see?

The proper output of the program

### What did you see instead?

MacBook-Air:euler Jeff$ go run 16.go 
# command-line-arguments
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x78eaa84308a pc=0xf47b]

runtime stack:
runtime.throw(0x2c4900, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a60a0)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a60a0, 0x1, 0x12, 0x47e178)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82003fe58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a60a0, 0x1, 0x10000000012, 0xf11f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a7b50, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a7b50, 0x466488)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x401000, 0xc800000012, 0x466488)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001c000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820038988 sp=0xc820038980
runtime.mallocgc(0x120, 0x276fa0, 0x0, 0x1d7520)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc820038a60 sp=0xc820038988
runtime.newobject(0x276fa0, 0xc820010420)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc820038a88 sp=0xc820038a60
cmd/link/internal/ld._lookup(0xc820074240, 0xc820c0a480, 0x35, 0x0, 0x1, 0x8)
	/usr/local/go/src/cmd/link/internal/ld/sym.go:201 +0xf3 fp=0xc820038b00 sp=0xc820038a88
cmd/link/internal/ld.Linklookup(0xc820074240, 0xc820c0a480, 0x35, 0x0, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/sym.go:208 +0x48 fp=0xc820038b38 sp=0xc820038b00
cmd/link/internal/ld.readsym(0xc820074240, 0xc8200137c0, 0x27e550, 0x7, 0xc8200110b0, 0x30)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:187 +0x36c fp=0xc820038f80 sp=0xc820038b38
cmd/link/internal/ld.ldobjfile(0xc820074240, 0xc8200137c0, 0x27e550, 0x7, 0x2a19eb, 0xc8200110b0, 0x30)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc820039190 sp=0xc820038f80
cmd/link/internal/ld.ldobj(0xc8200137c0, 0x27e550, 0x7, 0x2a1a45, 0xc8200110b0, 0x30, 0xc820010570, 0x28, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc820039400 sp=0xc820039190
cmd/link/internal/ld.objfile(0xc82001a3f0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc820039710 sp=0xc820039400
cmd/link/internal/ld.loadlib()
	/usr/local/go/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc8200399f0 sp=0xc820039710
cmd/link/internal/ld.Ldmain()
	/usr/local/go/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc820039e70 sp=0xc8200399f0
cmd/link/internal/amd64.Main()
	/usr/local/go/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc820039e78 sp=0xc820039e70
main.main()
	/usr/local/go/src/cmd/link/main.go:27 +0x36f fp=0xc820039f50 sp=0xc820039e78
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820039fa0 sp=0xc820039f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820039fa8 sp=0xc820039fa0

### Here is the code that was being run:

https://gist.github.com/deltaskelta/a276a499b376de20ba7ae1d0e3053e8e

**Comment by minux** [comment]
Are you using macOS 10.12?
Is is possible that you have $GOROOT set that
points to a previous version than 1.6.3?

**Comment by deltaskelta** [comment]
hmm interesting....

`which go` will output

```
/usr/local/go/bin/go
```

but then when I run `go env GOROOT` I see

```
/usr/local/go
```

I never set the environment variable because I read that GOROOT was set when it was installed....Did the location change with the upgrade to 10.12?

**Comment by quentinmit** [comment]
Go 1.6.3 does not support 10.12, you need to update to 1.7 or later. (1.6.3 did support the 10.12 public beta, but Apple made another change for the final release that broke Go programs.)

**Comment by deltaskelta** [comment]
Thanks for the reply, where could one find this information on the go site? I've tried to locate where to look for such information in the future and couldn't track it down.

**Comment by bradfitz** [comment]
https://golang.org/doc/go1.7#ports

**Comment by bradfitz** [comment]
Also https://golang.org/wiki/MinimumRequirements

**Comment by minux** [comment]
Perhaps we should add a note to
https://golang.org/doc/devel/release.html#go1.6.minor
to make it clear that go 1.6.3 doesn't actually have support for macOS
Sierra.
