### ISSUE TITLE
Effective Go - Redeclaration and reassignment Section

### ISSUE THREAD

**Issue by paulistoan** [golang/go#17827]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
N/A

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
N/A

### What did you expect to see?
The comment "there is at least one other variable in the declaration that is being declared anew." in the "Redeclaration and reassignment" section is slightly misleading as "anew" also has the sense of "once more; again", which seems to be the opposite sense of what the comment is trying to convey. The intent seems to be that there is at least one new variable which is being declared.

### What did you see instead?
N/A

**Comment by quentinmit** [comment]
I believe that your misleading interpretation is indeed what it is trying to convey:

```
a := 1
{
  b := 2
  a, b := 3, 4
  println(a, b)
}
println(a)
```

will print

```
3 4
1
```

(https://play.golang.org/p/3x7nsuQtUb)

In this scenario, "a" is being declared anew.

**Comment by paulistoan** [comment]
Thanks for the feedback, but can you please take a look at http://stackoverflow.com/questions/38664844/multiple-return-value-and-in-go? It seems that those answers interpret "anew" as being the condition that at least one variable needs to be new, else the compiler will throw a `no new variables on left side of :=` error.
