### ISSUE TITLE
cmd/go: Go project using library from another vendor folder under the same $GOPATH causing type error

### ISSUE THREAD

**Issue by EwanValentine** [golang/go#17822]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.7.3

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ewanvalentine/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n
b/mc8yq3sn31j8_jfw_0xdhgc40000gn/T/go-build624813324=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
Ran... 

```bash
$ govendor add google.golang.org/grpc
$ govendor add google.golang.org/grpc/internal 
```

In project A, then... 

```bash
$ govendor add google.golang.org/grpc
$ govendor add google.golang.org/grpc/internal
```

In project B.

### What did you expect to see?
I expected to have access to the google gRPC library from the local vendor folder. 

### What did you see instead?
The gRPC library from another project in the same $GOPATH was being used instead, causing a 'incorrect type' error. 

```
./main.go:44: cannot use conn (type *"bitbucket.org/bandzest/bandzest-service-artists/api/vendor/google.golang.org/grpc".Clien
tConn) as type *"bitbucket.org/bandzest/bandzest-service-auth/api/vendor/google.golang.org/grpc".ClientConn in argument to pro
to.NewAuthClient
```

**Comment by freeformz** [comment]
If project A imports project B, project B needs to be added to project A's vendor folder by a tool like govendor so that it can flatten out the dependency graph so there is only one version of each dependency for project A.

**Comment by quentinmit** [comment]
This sounds like it is WAI. Go treats each vendored package as a separate package. If you want to use types from one vendored library across two packages, those packages need to share a single library in a single vendor directory.

If you don't think that's what is happening here, please provide a complete test case (with two packages) and we can try to reproduce.
