### ISSUE TITLE
cmd/go: add subcommand to manage dependencies

### ISSUE THREAD

**Issue by m-abdalrahman** [golang/go#17820]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.3

### What operating system and processor architecture are you using (`go env`)?
N/A

### What is your suggestion?
add `vendor` subcommand for example to mange dependencies inside vendor directory

### What did you expect to see?
`go vendor golang.org/x/sys`  download golang.org/x/sys pkg inside vendor directory
`go vendor -u golang.org/x/sys`  update golang.org/x/sys pkg
`go vendor -u` update all packages
`go vendor -l`  list all packages inside vendor directory
`go vendor -d golang.org/x/sys` delete golang.org/x/sys pkg

**Comment by wendigo** [comment]
What you're proposing is already discussed in https://docs.google.com/document/d/18tNd8r5DV0yluCR7tPvkMTsWD_lYcRO7NhpNSDymRr8/edit

**Comment by adg** [comment]
I'm going to close this, as work is underway to solve this issue.
