### ISSUE TITLE
plugin: initializers not run on plugin load

### ISSUE THREAD

**Issue by captncraig** [golang/go#17821]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Tip: `go version devel +2b445c7 Sat Nov 5 23:59:04 2016 +0000 darwin/amd64`

### What did you do?
Plugin package built with `go build -buildmode=plugin`:
```
package main

func init() {
	print("INIT!")
}

func main() {
	print("MAIN")
}

func F() {
	print("F")
}
```

Host App:
```
package main

import (
	"fmt"
	"plugin"
)

func main() {
	fmt.Println("HOST")
	p, err := plugin.Open("plugin.so")
	if err != nil {
		panic(err)
	}
	fmt.Println(p)
	f, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}
	fmt.Println(f)
	f.(func())()
	select {}
}
```

### What did you expect to see?
I expected to see the `INIT!` line from the plugin init printed as per the [docs](https://tip.golang.org/pkg/plugin/). Instead, that line seems to be missing. Full output:
```
HOST
&{github.com/captncraig/scratch/testmain/plug 0xc420074060 map[F:0x6041800]}
0x6041800
F
```

Am I misreading how plugin loading works, or is it not working as intended?

**Comment by 0xmohit** [comment]
It seems to work using `[fmt.Println](https://golang.org/pkg/fmt/#Println)`.  Is there a specific reason for using the built-in print function in the plugin?

**Comment by wendigo** [comment]
I don't know if print is buffered but maybe something related to flushing stdout with \n ?

**Comment by wendigo** [comment]
I've ran attached test case and on my ```go version devel +2b445c7 Sat Nov 5 23:59:04 2016 +0000 darwin/amd64``` the output is 
```
➜  ~ (master) ✗ go run host.go
HOST
INIT!&{command-line-arguments 0xc42001c0c0 map[F:0x58417b0]}
0x58417b0
F
```

**Comment by captncraig** [comment]
I started with `fmt` and experienced it behaved the same. I switched to `print` to remove dependencies in case it made a difference. It did not. Odd that it works for you but not me.

**Comment by 0xmohit** [comment]
I just realized that your original code also works for me (linux/amd64).

**Comment by captncraig** [comment]
working on an exact reproducible setup.

**Comment by captncraig** [comment]
Put my code in https://github.com/captncraig/plugintest.

go env:
```
GOARCH="amd64"                                                                                                                                                                         
GOBIN=""                                                                                                                                                                               
GOEXE=""                                                                                                                                                                               
GOHOSTARCH="amd64"                                                                                                                                                                     
GOHOSTOS="darwin"                                                                                                                                                                      
GOOS="darwin"                                                                                                                                                                          
GOPATH="/Users/craig/gopath"                                                                                                                                                           
GORACE=""                                                                                                                                                                              
GOROOT="/Users/craig/go"                                                                                                                                                               
GOTOOLDIR="/Users/craig/go/pkg/tool/darwin_amd64"                                                                                                                                      
GCCGO="gccgo"                                                                                                                                                                          
CC="clang"                                                                                                                                                                             
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mb/4rxpmz611m773qkhcgz_rx_m0000gn/T/go-build798077178=/tmp
/go-build -gno-record-gcc-switches -fno-common"                                                                                                                                        
CXX="clang++"                                                                                                                                                                          
CGO_ENABLED="1"                                                                                                                                                                        
PKG_CONFIG="pkg-config"                                                                                                                                                                
CGO_CFLAGS="-g -O2"                                                                                                                                                                    
CGO_CPPFLAGS=""                                                                                                                                                                        
CGO_CXXFLAGS="-g -O2"                                                                                                                                                                  
CGO_FFLAGS="-g -O2"                                                                                                                                                                    
CGO_LDFLAGS="-g -O2"           
```

go version:
`go version devel +2b445c7 Sat Nov 5 23:59:04 2016 +0000 darwin/amd64 `

in directory `$GOPATH/src/github.com/captncraig/plugintest`:

`go build -buildmode=plugin -o plugin.so ./plug`
`go run host.go`:
```                                                                                                             
HOST                                                                                                                                                                                   
&{github.com/captncraig/plugintest/plug 0xc42001e0c0 map[F:0x4541800]}                                                                                                                 
0x4541800                                                                                                                                                                              
F     
```

**Comment by captncraig** [comment]
Also deleted all of $GOPATH/pkg and $GOPATH/bin. No change.

**Comment by wendigo** [comment]
Hi @captncraig: I can also reproduce this with steps you've provided.

**Comment by wendigo** [comment]
It's weird. If you build plugin with commands:

```
go get github.com/captncraig/plugintest
cd $GOPATH/src/github.com/captncraig/plugintest/plug
go build -buildmode=plugin -o plugin.so plugin.go
mv plugin.so ../
cd ../
go run host.go
```

Output is as expected:
```
HOST
INIT!
&{command-line-arguments 0xc420018180 map[F:0x58417b0]}
0x58417b0
F
```

Also there is significant difference between Plugin.pluginpath: `github.com/captncraig/plugintest/plug` vs `command-line-arguments`

**Comment by crawshaw** [comment]
Yes, there is a bug in the linker that is easy enough to fix.

I haven't done it yet because I'm trying to decide whether we should disallow unnamed package plugins altogether. Without a name, we have to assume that either all ```command-line-arguments``` plugins are the same and only allow one of them to be loaded, or assume they are all different and allow all of them to be loaded, even if it turns out there are two versions of the same plugin. @ianlancetaylor, opinion?

**Comment by captncraig** [comment]
Is the package path not "baked in" to the plugin binary at compile time? I would generally foresee building all of my plugins in a similar way, so if one is unnamed, multiple different ones may be as well. It would be nice if file locations and working directories mattered as little as possible.

**Comment by ianlancetaylor** [comment]
This is what I think.

A plugin built outside of `GOPATH` should not have a plugin path.  It certainly shouldn't have a plugin path of "command-line-arguments".  At least, not if the user ever sees that.

When opening a plugin with no path, we should disambiguate only by the file name used to open the plugin.  If the same .so is opened under multiple names, so be it.

**Comment by crawshaw** [comment]
That makes sense to me. I'll have cmd/go generate a -pluginpath flag for cmd/link with a random suffix so that there are no symbol collisions, then modify the plugin package to detect these nameless plugins and use the file path instead for identification.

**Comment by crawshaw** [comment]
I think we need some kind of "plugin path" for plugins built outside ```GOPATH```. My reasoning is that if plugin1.so and plugin2.so both export a symbol F, they should be distinct symbols. For ld.so to do that, we the full symbol names for F and F to be distinct.

I've tried using the symbol name ```plugin/unnamed-$buildID.F``` and it seems to work.

**Comment by crawshaw** [comment]
I think the major issues here are basically fixed. There's still some nicer handling we could do of nameless plugins as Ian suggested, but I believe it will only improve the quality of errors. That I think it can wait for a later Go release.
