### ISSUE TITLE
doc: Document how much RAM is required to compile Go

### ISSUE THREAD

**Issue by kevinburke** [golang/go#17825]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Tip

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 16

### What did you do?

```
GOROOT_BOOTSTRAP=/home/kevin/go1.4 ./make.bash
```

### What did you expect to see?

I expected Go to compile.

### What did you see instead?

I got a confusing error message:

```
GOROOT_BOOTSTRAP=/home/kevin/go1.4 ./make.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/kevin/go1.4.
bootstrap/cmd/internal/dwarf
bootstrap/cmd/internal/sys
bootstrap/cmd/internal/obj
bootstrap/cmd/internal/obj/arm
bootstrap/cmd/internal/obj/arm64
bootstrap/cmd/internal/obj/mips
bootstrap/cmd/internal/obj/ppc64
bootstrap/cmd/internal/obj/s390x
bootstrap/cmd/internal/obj/x86
bootstrap/cmd/asm/internal/arch
bootstrap/cmd/asm/internal/flags
bootstrap/cmd/asm/internal/lex
bootstrap/cmd/asm/internal/asm
bootstrap/cmd/internal/bio
bootstrap/cmd/asm
bootstrap/cmd/compile/internal/ssa
go build bootstrap/cmd/compile/internal/ssa: /home/kevin/go1.4/pkg/tool/linux_amd64/6g: signal: killed
bootstrap/cmd/compile/internal/syntax
bootstrap/cmd/internal/gcprog
bootstrap/math/big
bootstrap/debug/pe
bootstrap/cmd/link/internal/ld
bootstrap/cmd/link/internal/amd64
bootstrap/cmd/link/internal/arm
bootstrap/cmd/link/internal/arm64
bootstrap/cmd/link/internal/mips64
bootstrap/cmd/link/internal/ppc64
bootstrap/cmd/link/internal/s390x
bootstrap/cmd/link/internal/x86
bootstrap/cmd/link
go tool dist: FAILED: /home/kevin/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go -v bootstrap/cmd/...: exit status 1
```

I didn't know how to check whether the program was out of memory at first but then I found this message in `/var/log/syslog`:

```
Nov  7 04:51:25 cheetah kernel: [620627.924208] Out of memory: Kill process 11971 (6g) score 830 or sacrifice child
Nov  7 04:51:25 cheetah kernel: [620627.924289] Killed process 11971 (6g) total-vm:850316kB, anon-rss:841312kB, file-rss:1232kB
```

That's about 850MB of RAM. I know this is a moving target but it would be nice to document on the [Go compile page](https://golang.org/doc/install/source) how much RAM is necessary to compile Go. 

Specifically I'm trying to build Go at tip. It would also be nice to know if compiled versions of tip are available anywhere (or other tips for getting Go tip in a lower memory environment)

**Comment by minux** [comment]
Not only it's a moving target, it also depends on the version
of Go used to bootstrap and the $GOGC setting, to name
a few factors.

I don't think we want to document this. (Or put it another way,
if we do document this, we're likely to use a very conservative
value, say 2GB, which is very unlikely to be useful anyway.)

Try setting GOGC to a small value (like 10), and try again.
if it is still failing, you might want to use Go 1.7 to bootstrap
tip on low memory systems and also temporarily enable swap.

Or better yet, just bootstrap Go tip on a machine with more
memory and copy the result to the low-memory machine.

**Comment by minux** [comment]
Also note that I do bootstrap Go tip on a machine
with only 512MB of memory. A combination of
enabling swap temporally and lower GOGC helps.

**Comment by quentinmit** [comment]
We do have precompiled copies of tip... not sure why, but we don't link them anywhere public.

@bradfitz Can we link the tarballs from the build dashboard?

**Comment by bradfitz** [comment]
Maybe. I might start deleting them. They're getting a little large I think, at least from the bill.

**Comment by kevinburke** [comment]
managed to get this working by compiling tip with GOGC=10 and go1.7.3!
