### ISSUE TITLE
cmd/go: use os.Executable to find GOROOT

### ISSUE THREAD

**Issue by quentinmit** [golang/go#17833]
Use os.Executable to find GOROOT.

**Comment by bradfitz** [comment]
... as a fallback if GOROOT isn't set.

**Comment by bradfitz** [comment]
See #12773

**Comment by minux** [comment]
Yeah, I think the result from os.Executable should override the
embedded runtime.GOROOT.

Just remember to apply path/filepath.EvalSymlinks to the path
returned from os.Executable (so that people can symlink the
go command to a central bin directory.)

**Comment by bradfitz** [comment]
This was fixed in dup bug #18678.
