### ISSUE TITLE
apparent return of problem #5382

### ISSUE THREAD

**Issue by sdwarwick** [golang/go#17837]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What did you do?
If possible, provide a recipe for reproducing the error.

http;//localhost/directory?test=t  

redirects to (301) 
http;//localhost/directory/

if Httprouter selector is "/directory/"
query string is missing

expected to see at a minimum

http;//localhost/directory/?test=t

**Comment by bradfitz** [comment]
This is not a complete bug report.

Please provide code, and verify that your URLs are actually well-formed with colons after `http` and not semicolons.

**Comment by sdwarwick** [comment]
ok, sorry will re-enter
