### ISSUE TITLE
suggestion: Add a switch interface for the hostname validation in the base-package

### ISSUE THREAD

**Issue by shuqilou** [golang/go#17843]
we know that the safety inspection mechanism in GO will check the hostname of certificate. If the security certificate does not configure DNS or IP, it will be unable to achieve the function of secure communication.

**Here is the question:**

*Can we construct a switch API to select whether to verify the hostname of certificate, rather than verifying it all the time?*

 If I have a certificate that does not contain DNS and IP but I want to do secure communication, then I can enable the switch API and filter out the hostname validation. 

I think it will be easier for developers to operate and more flexible to use. What's your opinion?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions

I think what you're looking for is tls.Config.InsecureSkipVerify.

**Comment by shuqilou** [comment]
Thanks for your timely response!

tls.Config.InsecureSkipVerify ignores most of the certificate validation logic, but what I want to realize is just filtering out the **hostname validation**.

The certificate we use does not contain valid hostname (DNS or IP), but our usage situation is not for testing, so I put forward the above suggestion. Do you have any idea to resolve the contradictive of my situation?

**Comment by ctrlaltdel121** [comment]
I also agree that it would be nice to independently skip the hostname validation and the trust chain validation. We have certs that for certain reasons don't match up with the server's DNS name and are self-signed, but it would be nice for us to import our CA in tls Config and still have that part of the validation performed.
