### ISSUE TITLE
how to get a clear conn from the database/sql conn pool?

### ISSUE THREAD

**Issue by xuewindy** [golang/go#17849]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.6

### What operating system and processor architecture are you using (`go env`)?
debian

### What did you do?
i didn't get a error  ,
but i write a server using database/sql
when i want to set time_zone ="+00:00"  and do something   in session a and then put conn
and then i wang do another things  and i got a conn from pool
will the status  be "+00:00" instead of system time ?
can i do sometiong to reset the conn when put back conn?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions
