### ISSUE TITLE
runtime/pprof/internal/protopprof: TestTranslateCPUProfileWithSamples failing on s390x

### ISSUE THREAD

**Issue by mundaym** [golang/go#17852]
Example: https://build.golang.org/log/25b034d5756b4d4fb9c69e5204180cd67289b04a

```
count:0 nstk: 1
count:0 nstk: 1
--- FAIL: TestTranslateCPUProfileWithSamples (0.00s)
	protopprof_test.go:165: Less than two mappings
FAIL
FAIL	runtime/pprof/internal/protopprof	30.005s
```

I'll investigate and see if I can figure out what the problem is.

**Comment by mundaym** [comment]
The problem is that there is only one mapping (as stated in the error message). s390x is using internal linking so isn't loading any shared objects and there is therefore only one executable region of memory.

```
00010000-0012d000 r-xp 00000000 fc:00 262920                             /tmp/go-build695301680/runtime/pprof/internal/protopprof/_test/protopprof.test
```

We could switch to external linking by default on s390x (which I might do anyway since I thought external linking was the default...) which causes the test to pass.  On linux/amd64 when you have internal linking there are still more than two executable regions due to vdso/vsyscall, so this test happens to pass:

```
00400000-0050c000 r-xp 00000000 fc:00 1842738                            /tmp/go-build939535083/runtime/pprof/internal/protopprof/_test/protopprof.test
7ffc24071000-7ffc24073000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

Since 1 mapping is a valid state AFAICT, I think the test should be skipped rather than fail if there are less than 2 mappings. Does this sound like a reasonable plan? Any other thoughts?

**Comment by matloob** [comment]
Can we tell from the test how the binary's linked, or selectively skip for certain GOOS/GOARCH/etc?

**Comment by mundaym** [comment]
> Can we tell from the test how the binary's linked, or selectively skip for certain GOOS/GOARCH/etc?

I'm not aware of a way to get the linkmode at runtime. We could maybe use something like ldd to check if the test binary loads any shared objects.

I don't really like the idea of disabling the test on a specific GOARCH (I think this is a Linux only test) since it seems to me that only having 1 executable region is a valid state that could occur on most architectures. For example, if might occur if someone was statically linking against libc.

We could fail the test if there are no entries at all. That might help catch parsing problems.
