### ISSUE TITLE
runtime/pprof/internal/protopprof: TestCPUProfileParse sleeps for 30s

### ISSUE THREAD

**Issue by mundaym** [golang/go#17853]
This means that these tests take 30s even in -short mode. Seems undesirable.

**Comment by matloob** [comment]
Would this be fixed by skipping these tests in -short mode?

**Comment by mundaym** [comment]
It's just the one test, TestCPUProfileParse. You could skip it, but can it be shortened instead somehow?

**Comment by bradfitz** [comment]
I've been on a mission to save a second here and a second there all across the standard library. A 30 second test defeats that whole mission. I don't know what this test is trying to do, but surely there's a better way.

**Comment by matloob** [comment]
The test needs to run for a bit of time to collect profile samples, but it certainly doesn't need to run for 30s. 30s was just the length of time the profiles are collected for in the tests on the original Google version of this code.

**Comment by ianlancetaylor** [comment]
It may be helpful to look at tests like runtime/testdata/testprogcgo/pprof.go which test the profiler but limit how long they run.

**Comment by rsc** [comment]
This test has been deleted.

**Comment by mundaym** [comment]
> This test has been deleted.

There is now a new TestCPUProfileParse in runtime/pprof_test.go that sleeps for 5 seconds always: https://github.com/golang/go/blob/9a5bddd7ed57596a259f3896dd31ea30e331027d/src/runtime/pprof/pprof_test.go#L665. That is much better than 30 seconds, but all the other tests in that package seem to try and complete in 200ms in short mode. Maybe this new test should do the same?

**Comment by rsc** [comment]
That test will be deleted in https://go-review.googlesource.com/33136. Thanks.
