### ISSUE TITLE
runtime: duffcopy is not a duff copy

### ISSUE THREAD

**Issue by robpike** [golang/go#17850]
Just formalizing an old gripe.

**Comment by josharian** [comment]
May I suggest a Duff beer to ease your worries?

**Comment by josharian** [comment]
(Poor Rob, having to work with such duffers.)

**Comment by randall77** [comment]
It's just a tribute to the legendary actress [Hilary Duff](https://en.wikipedia.org/wiki/Hilary_Duff).

**Comment by bradfitz** [comment]
I'm closing this bug. If somebody wants it open, they can reopen it and make it clear at the same time what the action item is.
