### ISSUE TITLE
test failed while building go on debian 8(debian jessie)

### ISSUE THREAD

**Issue by zhangwen-qq** [golang/go#17864]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
My operation system is debian 8
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhw2101024/.local/share/go"
GORACE=""
GOROOT="/home/zhw2101024/go1.7"
GOTOOLDIR="/home/zhw2101024/go1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build424418262=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1

### What did you do?
build go from source using following command:
GOROOT_BOOTSTRAP=/home/zhw2101024/go1.7 GOROOT_FINAL=/home/zhw2101024/go1.7 ./all.bash

### What did you expect to see?
Go version is "go1.7.3", ignoring -next /mnt/floppy/src/go/api/next.txt

ALL TESTS PASSED

---
Installed Go for linux/amd64 in /mnt/floppy/src/go
Installed commands in /mnt/floppy/src/go/bin

The binaries expect /mnt/floppy/src/go to be copied or moved to /home/zhw2101024/go1.7

### What did you see instead?
--- FAIL: TestLoadFixed (0.08s)
        time_test.go:943: Now().In(loc).Zone() = "-01", -3600, want "GMT+1", -3600

**Comment by ALTree** [comment]
Dup of #17276, already fixed on tip.
