### ISSUE TITLE
proposal: make atomic.Swap/Load/StorePointer functions support generic pointer parameters

### ISSUE THREAD

**Issue by golang101** [golang/go#17870]
As @randall77 suggested, in https://github.com/golang/go/issues/17866#issuecomment-259473668,
generic pointers will be a good way to avoid verboseness.

**Comment by bradfitz** [comment]
Please do not file bugs for every possible library change we would make if Go had generics. Rest assured that if/when we add generics, we will comprehensively revisit everything in the standard library.

**Comment by golang101** [comment]
@bradfitz, 
I don't excessively demand an overall generic, I just want generic for atomic.Swap/Load/StorePointer functions.

BTW, do you mean an overall generic implementation is coming?

**Comment by bradfitz** [comment]
It would be all or nothing. We're not going to add generics for just atomic.Swap/Load/StorePointer.

**Comment by golang101** [comment]
@bradfitz, 
ok, I believe you go team will not stand by and ignore the verboseness of calling atomic.Swap/Load/StorePointer functions.

**Comment by jhump** [comment]
@bradfitz, I'm guessing since the methods are in a package (`sync/atomic`) vs builtins, there would be strong objections to making them compiler intrinsics, like the `make`, `append`, and `copy` builtins?

```go
package atomic

import "builtin" // uses faux *Type instead of unsafe.Pointer, for type safety

func SwapPointer(addr **builtin.Type, new *builtin.Type) (old *builtin.Type) { /* ... */ }
func CompareAndSwapPointer(addr **builtin.Type, old, new *builtin.Type) (swapped bool) { /* ... */ }
func LoadPointer(addr **builtin.Type) (val *builtin.Type) { /* ... */ }
func StorePointer(addr **builtin.Type, val *builtin.Type) { /* ... */ }
```

Then they could be type-safe as well as more concise. I suspect that was the real intent behind this proposal. Perhaps that's already how you interpreted it when the issue was closed...

**Comment by bradfitz** [comment]
They are compiler intrinsics already.

**Comment by jhump** [comment]
I meant intrinsics specifically like `make`, `copy`, and `append` -- not only does the compiler emit special code, but it also handles type-checking in a special way -- in that they can take arbitrary types and be type-safe (e.g. no need for users to cast everything through `unsafe.Pointer`).
