### ISSUE TITLE
Exclude vendor/ from linters

### ISSUE THREAD

**Issue by mcandre** [golang/go#17879]
Could the `go vet` and `gofmt` tools please make it easier for users to skip third-party (vendored) code?

For now, I'm wrapping `go vet` and `gofmt` with `find . -name vendor -prune -o -name '*.go' -exec go vet -v {} \;` and `find . -name vendor -prune -o -name '*.go' -exec gofmt -s -w {} \;`, respectively.

**Comment by bradfitz** [comment]
Dup of #14417

I'm going to close this because I haven't seen anything to indicate there's been a policy change since that time.
