### ISSUE TITLE
x/sys/unix: add Getsid for Linux

### ISSUE THREAD

**Issue by amenzhinsky** [golang/go#17872]
I think the function should be added to https://github.com/golang/go/blob/master/src/syscall/syscall_linux.go like it's done for the darwin platform https://github.com/golang/go/blob/master/src/syscall/syscall_darwin.go#L236

I'm not sure whether it can be done in the stdlib since the syscall package is frozen since go1.4.
If it's not I can submit a fix to the golang.org/x/sys/unix package.

### What version of Go are you using (`go version`)?
```
go version go1.7.3 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/amenzhinsky/Development/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build858666576=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by minux** [comment]
yeah, if it's not available in x/sys/unix, then it's fine to add
to x/sys/unix (not syscall, as it has been frozen for such
additions.)
