### ISSUE TITLE
encoding/json: calls UnmarshalJSON with a nil receiver on anonymous fields

### ISSUE THREAD

**Issue by epelc** [golang/go#17877]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.7.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Custom `UnmarshalJSON` methods do not properly update an anonymous field on an outer struct when it is unmarshaled. 
https://play.golang.org/p/wkQhDFiO82

It works correctly if the outer struct's field is not anonymous. If the field is anonymous it only works if you initialize it first`x.SomeType = &SomeType{}`.
https://play.golang.org/p/DYuygZrLgk

edit - also note this works fine if you do not have custom `UnmarshalJSON` https://play.golang.org/p/2HhHJ19wpQ

### What did you expect to see?
The anonymous field should be set and have `Price: 99` like in the second example.

### What did you see instead?
The anonymous field is nil

I'm not sure if this counts as a bug or what underlying issue is causing it. But it is very confusing from a user's perspective and it seems like it might be a compiler issue(maybe?).

**Comment by quentinmit** [comment]
I'm not sure if this is just a documentation bug or if we actually want to create a SomeType instance. In general nil receivers are fine, but I agree it doesn't make sense for UnmarshalJSON to be given a nil receiver.

/cc @rsc

**Comment by shantuo** [comment]
My understanding is that this is working as intended. In the first case, Outer is a Marshaler, so Unmarshal will call its custom UnmarshalJSON on it directly. While in other cases, Outer is not a Marshaler. The default behavior for Unmarshal is documented as:

> If the pointer is nil, Unmarshal allocates a new value for it to point to.

**Comment by rsc** [comment]
Yes, @shantuo is right. From the json package's point of view, it allocates an Outer, sees that Outer has an UnmarshalJSON method (due to the embedding), and invokes Outer's UnmarshalJSON method. The raison d'être of UnmarshalJSON is to stop the usual processing, and in this case, that means not looking inside Outer at all. The json package cannot be responsible for allocating the inner struct. 

Other ways to write this code include embedding a struct instead of a pointer-to-struct.
