### ISSUE TITLE
multidimentional arrays or matrices

### ISSUE THREAD

**Issue by drrob1** [golang/go#17882]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`Ubuntu 16.04 amd64`)?
I am requesting a new feature.  
I am not a computer scientist, merely a hobby programmer.  Working out all the complexities of adding multidimentional arrays or matrices to be able to do linear algebra using mathematically standard syntax as used in C++, Fortran, Python, etc, would be advantageous for the language, but is beyond my abilities.

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by drrob1** [comment]
I don't know if I successfully posted here.

**Comment by ainar-g** [comment]
Looks like a dup of #6282.

**Comment by robpike** [comment]
It is a dup.
