### ISSUE TITLE
Multidimentional arrays or multidimentional matrices 

### ISSUE THREAD

**Issue by drrob1** [golang/go#17881]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)?
I am requesting a new feature.  
I am not a computer scientist, merely a hobby programmer.  Working out all the complexities of adding multidimentional arrays or matrices to be able to do linear algebra using mathematically standard syntax as used in C++, Fortran, Python, etc, would be advantageous for the language, but is beyond my abilities.

### What did you do?
If possible, provide a recipe for reproducing the error.  
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by drrob1** [comment]
I don't understand the error I'm getting while trying to post here.  I don't even know if my posting succeeded.

**Comment by randall77** [comment]
Dup of https://github.com/golang/go/issues/6282
