### ISSUE TITLE
cmd/objdump: does not provide file/line info for files built with -buildmode=pie

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#17883]
go build -buildmode=pie ~/hello.go
    go tool objdump -s 'main.main' hello

Observe that the file/line information is shown as just `:0`.  If you do the same commands but omit `-buildmode=pie` the correct file/line information is shown.

I have a partial fix for this, but a full fix requires applying the dynamic relocations to the pclntab data.  The `RELATIVE` dynamic relocations can be ignored, but there are some non-relative relocations to symbols defined in runtime/cgo.

**Comment by bradfitz** [comment]
Ian, still interested in this for 1.9?

**Comment by ianlancetaylor** [comment]
Moving to 1.10.
