### ISSUE TITLE
html/template: URL escapes query params

### ISSUE THREAD

**Issue by rudydai** [golang/go#17894]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
The version available on play.golang.org, which appears to be version 1.7

### What operating system and processor architecture are you using (`go env`)?
Whatever play.golang.org uses

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/or2urL8dh0

### What did you expect to see?
Expected to see the url pass through the template without being escaped, as documented in https://golang.org/pkg/html/template/ which states "Types HTML, JS, URL, and others from content.go can carry safe content that is exempted from escaping."

### What did you see instead?
The template outputs the url as "https://hostname.example.com/test.png?abc=1&amp;def=2", which has the ampersand escaped.

**Comment by rsc** [comment]
Using template.URL disables URL sanitization. It does not disable HTML escaping when you print the value in an HTML page. That &amp; is just what you have to do to get past the HTML parser. If you want to put raw HTML in the page, use template.HTML.

See https://play.golang.org/p/vaa4kvWDaY:

```
package main

import (
	"html/template"
	"os"
	"fmt"
	"runtime"
)

func main() {
	fmt.Println(runtime.Version())
	t, _ := template.New("foo").Parse(`
	             U: <a href="{{.U}}">
	                         {{.U}}</a>
	            JS: <a href="{{.JS}}">
	                         {{.JS}}</a>
	        SafeJS: <a href="{{.SafeJS}}">
	                         {{.SafeJS}}</a>
	`)
	t.Execute(os.Stdout, map[string]interface{}{
		"U": "https://example.com/?x=\"hello\"&y=\"world\"",
		"JS": "javascript:alert(\"hello\")",
		"SafeJS": template.URL("javascript:alert(\"hello\")"),
	})
}
```

Prints:

```
go1.7

	             U: <a href="https://example.com/?x=%22hello%22&amp;y=%22world%22">
	                         https://example.com/?x=&#34;hello&#34;&amp;y=&#34;world&#34;</a>
	            JS: <a href="#ZgotmplZ">
	                         javascript:alert(&#34;hello&#34;)</a>
	        SafeJS: <a href="javascript:alert%28%22hello%22%29">
	                         javascript:alert(&#34;hello&#34;)</a>
```

**Comment by rudydai** [comment]
Thanks for your quick replies! Looks like most browsers accept both formats, but this is certainly the more correct way.
