### ISSUE TITLE
gofmt does not correctly align struct literal values

### ISSUE THREAD

**Issue by jba** [golang/go#17899]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.3. Also current playground version.

### What operating system and processor architecture are you using (`go env`)?

linux amd64
### What did you do?

https://play.golang.org/p/meDdSOWCWa

### What did you expect to see?

last field value aligned with others

### What did you see instead?

last field value unaligned

**Comment by 0xmohit** [comment]
This is probably intentional.  See https://github.com/golang/go/issues/16170#issuecomment-228216605
