### ISSUE TITLE
Import statement makes it hard to apply GitHub Flow on the project

### ISSUE THREAD

**Issue by wigy-opensource-developer** [golang/go#17893]
go1.7.3 linux/amd64

### What did you do?
- Have a GitHub repository with 2 go modules (say https://github.com/golang/example/)
- Import one module from the other (say example/hello imports example/stringutils)
- Fork the project on GitHub to start working on a contribution (say to https://github.com/statler-and-waldorf/example)
- go get the fork (`go get github.com/statler-and-waldorf/example/hello`)

### What did you expect to see?
- I wanted to just work on all modules of the repository without jumping through hoops.
- I expected separation of the build system configuration from the source code that is being built. Which is a [well-documented pattern](http://enterprisedevops.org/article/2014/3/2/pattern-script-injection) in DevOps.

### What did you see instead?
- You need to change the go module references *internal* to the repository to compile and test your contributions, then you need to change it back before you create the pull request to the original repository.
- Especially with complex projects (like https://github.com/ipfs/go-ipfs/) you need to touch many files in the source code. I need to yet see a reason to use a different version of a dependent module in different files of a module, so it makes no sense to me why I need to duplicate the absolute path in all import statements in all files.

**Comment by ianlancetaylor** [comment]
If you use vendoring (https://golang.org/cmd/go/#hdr-Vendor_Directories) then you don't need to change your import statements.  You can vendor your dependency while you are working on it, then remove the vendor directory when you are prepared to go back to the real directory.

This is not the kind of thing that will be productive to discuss in the issue tracker.  You will get much better feedback in a forum (https://golang.org/wiki/Questions).  So let's take it to a forum.  Closing this issue.

**Comment by dominikh** [comment]
Further reading: http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

**Comment by wigy-opensource-developer** [comment]
@ianlancetaylor I do not have control over how the original repo set up imports, so I cannot use vendoring to change both the dependent and depending module in the same repo.

@dominikh Thanks for the link! The idea to checkout my fork under the original $GOPATH/src/github.com/golang/example path really does the trick! Awesome!
