### ISSUE TITLE
make.bash: $GOBIN is ignored

### ISSUE THREAD

**Issue by robpike** [golang/go#17896]
I have $GOBIN set but the go tool is ignoring it when installing.

### What version of Go are you using (`go version`)?

go version devel +b6a1568 Fri Nov 11 20:20:23 2016 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/Users/r/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/r"
GORACE=""
GOROOT="/Users/r/go"
GOTOOLDIR="/Users/r/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q2/2bw_4fq90jnb9w80wltgwtkh0000gn/T/go-build531580070=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

./make.bash

### What did you expect to see?

My commands installed in $GOBIN

### What did you see instead?

Installed Go for darwin/amd64 in /Users/r/go
Installed commands in /Users/r/go/bin
bismarck=% echo $GOBIN
/Users/r/bin
bismarck=%

**Comment by bradfitz** [comment]
The top of `make.bash says:

```sh
unset GOBIN # Issue 14340
```

See #14340 and https://golang.org/cl/23255 where you wanted and approved the opposite.

**Comment by robpike** [comment]
I may have been confused then. I'm certainly confused now. What is GOBIN for if make.bash ignores it? If the go binary is not installed there?

I need remedial training.

**Comment by bradfitz** [comment]
`GOBIN` is only for `cmd/go` I believe: 

https://golang.org/cmd/go/ says:

> If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin. GOBIN must be an absolute path.

**Comment by robpike** [comment]
Wow, I had no idea. Amazing. I've had GOBIN set since day one. Jeez.
