### ISSUE TITLE
go1.7.3 transport.go:1429 panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by botvs** [golang/go#17903]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.3

### What operating system and processor architecture are you using (`go env`)?
windows 386

### What did you do?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x74 pc=0x80f61a]

goroutine 261555 [running]:
panic(0x9b6c00, 0x1252c030)
        /opt/dev/gopkg/go/src/runtime/panic.go:500 +0x331
net/http.(*persistConn).readLoop(0x1254c240)
       /opt/dev/gopkg/go/src/net/http/transport.go:1429 +0x2ba
created by net/http.(*Transport).dialConn
        /opt/dev/gopkg/go/src/net/http/transport.go:1062 +0xda5
2016/11/13 09:05:09 Exit 43027

**Comment by bradfitz** [comment]
Sorry, there's not enough information to help you here.

Let's move this to a mailing list (https://golang.org/wiki/Questions) if you're new to Go and this is a likely a problem with your program, or please post more information, like the source code, and whether you ran the race detector.
