### ISSUE TITLE
os: Clearenv sets variables to "" rather than deleting them on Windows

### ISSUE THREAD

**Issue by jszwedko** [golang/go#17902]
It appears that, on Windows, `os.Clearenv` sets all variables to `""` rather than actually unsetting them (as it does on Linux and Unix based other platforms).

I can submit a patch for this, but wanted to clarify if it was expected behavior.

### What version of Go are you using (`go version`)?

`go version go1.7.3 windows/386`

### What operating system and processor architecture are you using (`go env`)?

`windows/386`

### What did you do?

```golang
package main

import (
        "fmt"
        "os"
)

func main() {
        os.Setenv("FOO", "bar")
        v, ok := os.LookupEnv("FOO")
        fmt.Printf("%q %q\n", v, ok)

        os.Clearenv()
        v, ok = os.LookupEnv("FOO")
        fmt.Printf("%q %q\n", v, ok)

        os.Unsetenv("FOO")
        v, ok = os.LookupEnv("FOO")
        fmt.Printf("%q %q\n", v, ok)
}
```

### What did you expect to see?

```
"bar" %!q(bool=true)
"" %!q(bool=false)
"" %!q(bool=false)
```

### What did you see instead?

```
"bar" %!q(bool=true)
"" %!q(bool=true)
"" %!q(bool=false)
```

On linux/amd64:

```
"bar" %!q(bool=true)
"" %!q(bool=false)
"" %!q(bool=false)
```

**Comment by bradfitz** [comment]
Not intentional. Feel free to send a fix.

The Go 1.8 dev cycle is closed for the release freeze, though, so it might not make it until Go 1.9.
