### ISSUE TITLE
 cmd/go: TestGoBuildUmask fails when source tree has a POSIX ACL set

### ISSUE THREAD

**Issue by zhengkai** [golang/go#17909]
# summary

when using POSIX ACL in go source dir, test fail

    --- FAIL: TestGoBuildUmask (0.06s)
        go_test.go:252: running testgo [build /tmp/gotest237673041/x.go]
        go_unix_test.go:29: wrote x with mode=-rwxrwxr-x, wanted no 0077 bits

I think the test confuses the differences between the original and the extra permissions

# detail

system is `Ubuntu 16.04.1 x64`

my `/usr/local/src` dir had been set POSIX ACL sudo group write

    sudo setfacl -d -R -m g:sudo:rwx /usr/local/src
    sudo setfacl    -R -m g:sudo:rwX /usr/local/src

and my account in sudo group

     » id
    uid=1000(zhengkai) gid=1000(zhengkai) groups=1000(zhengkai),4(adm),27(sudo)

getfacl shows:

     » getfacl /usr/local/src
    getfacl: Removing leading '/' from absolute path names
    # file: usr/local/src
    # owner: root
    # group: root
    user::rwx
    group::r-x
    group:sudo:rwx
    mask::rwx
    other::r-x
    default:user::rwx
    default:group::r-x
    default:group:sudo:rwx
    default:mask::rwx
    default:other::r-x

I download the newest binary `https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz` for build, extract files to `/usr/local/src/gobin1.7.3`

and clone source

    git clone https://go.googlesource.com/go /usr/local/src/go

goto `src` dir and build ( commit: `2f76c198` )

    GOROOT_BOOTSTRAP=/usr/local/src/gobin1.7.3 ./all.bash

fail:

    ok      cmd/doc 0.036s
    ok      cmd/fix 0.021s
    --- FAIL: TestGoBuildUmask (0.06s)
        go_test.go:252: running testgo [build /tmp/gotest237673041/x.go]
        go_unix_test.go:29: wrote x with mode=-rwxrwxr-x, wanted no 0077 bits
    FAIL
    FAIL    cmd/go  28.873s
    ok      cmd/gofmt   0.018s
    ok      cmd/internal/goobj  0.014s
    ok      cmd/internal/obj    0.002s
    ok      cmd/internal/obj/x86    0.002s
    ok      cmd/link    0.016s
    ok      cmd/nm  0.507s
    ok      cmd/objdump 0.813s
    ok      cmd/pack    1.016s
    ok      cmd/trace   0.004s
    ok      cmd/vendor/golang.org/x/arch/arm/armasm 0.004s
    ok      cmd/vendor/golang.org/x/arch/ppc64/ppc64asm 0.016s
    ok      cmd/vendor/golang.org/x/arch/x86/x86asm 0.110s
    ok      cmd/vet 1.246s
    ok      cmd/vet/internal/cfg    0.016s
    2016/11/14 14:39:38 Failed: exit status 1

if I remove the POSIX ACL settings, everything will be ok

    sudo setfacl -b -R /usr/local/src/go

I think the test confuses the differences between the original and the extra permissions

**Comment by bradfitz** [comment]
@jessfraz, this seems up your alley?

**Comment by jessfraz** [comment]
Sweeet on it
