### ISSUE TITLE
Interface function recieving wrong type.

### ISSUE THREAD

**Issue by kiljacken** [golang/go#17911]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.7.3 windows/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\dev\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

### What did you do?
A snippet of code reproducing the problem can be found [here](https://play.golang.org/p/bT2xGl-xH4)

### What did you expect to see?
I expected the code to compile and run, as the implementation signature matches the interface.

### What did you see instead?
The compiler errors out, telling me there's a problem with the implementing funcition:
```
tmp/sandbox100611389/main.go:25: cannot use NewStubModel() (type *StubModel) as type ModelProvider in assignment:
	*StubModel does not implement ModelProvider (wrong type for SearchArtist method)
		have SearchArtist(bool, string, int) []string
		want SearchArtist(int, int, int) []string
```

**Comment by dominikh** [comment]
WAI. The interface defines a method SearchArtist with three integer arguments, called `bool`, `string` and `limit`.

**Comment by nuss-justin** [comment]
SearchArtist is defined as `SearchArtist(bool, string, limit int) []string` in the interface. This is equivalent to `SearchArtist(bool int, string int, limit int) []string`. So, yeah, the compiler is right with the error.

If you remove the word `limit` from the interface method or name the first two parameters the code works.

**Comment by kiljacken** [comment]
Ohh, so I have to use names for all or none? I see. *facepalm*

**Comment by kiljacken** [comment]
A case of syntax highlighting gone awry then...
