### ISSUE TITLE
runtime: add a comment which briefly mentions where (or how) `g_stackguard0` is defined

### ISSUE THREAD

**Issue by typeless** [golang/go#17915]
Am I missing something obvious? I attempted but failed to locate the definition of the symbol with `grep` and `ack`.

A brief comment will certainly save time for people who are trying to learn the runtime's internal.

**Comment by bradfitz** [comment]
It looks like it's just a local variable name.

/cc @ianlancetaylor

**Comment by typeless** [comment]
@bradfitz It looks like the symbol is generated by `dumpasmhdr`  (/cmd/compile/internal/gc/export.go), which is equivalent to `offsetof(g, stackguard0`).

**Comment by ianlancetaylor** [comment]
You are asking where the assembler constant `g_stackguard0` is defined?  As you say, it's defined in go_asm.h, which is a generated file.  It's not just `g_stackguard0`; it's all the TYPE_FIELD symbols used by the assembler files--`g_sched`, `gobuf_sp`, `g_m`, etc., etc.  I just checked, and go_asm.h defines 1634 constants.  I'm not sure how to make a comment for that that will help people looking for a specific symbol.

**Comment by typeless** [comment]
@ianlancetaylor @bradfitz Indeed, adding a comment does not help much as I thought (as I brought up the issue before I found out the answer). Maybe the assembler deserves a more capable language which won't need such kind of cleverness in the future.

Thanks for your responses and feel free to close the issue.

**Comment by minux** [comment]
I don't think we could make the assembler more capable to eliminate the
auto-generated header unless we embed a copy of cmd/compile inside cmd/asm.

**Comment by mwhudson** [comment]
​I guess https://golang.org/doc/asm could/should mention asmhdr? Would give
people a chance to figure out what's going on at least.

**Comment by minux** [comment]
Yeah, we could document go_asm.h in doc/asm, but my concern is that it will
not help much as it's such a rarely used feature that I don't know any
package besides runtime uses it.
