### ISSUE TITLE
encoding/json: encoding duplicate struct keys fail silently (and does not report error)

### ISSUE THREAD

**Issue by mlitvin** [golang/go#17913]
When due to a bug a structure has two fields with the same key like:

```
type bug struct {
	Key   string `json:"bug"`
	Value string `json:"bug"`
}
```

The JSON marshaller will silently ignore the fields. I would expect it to return an error to the caller.

Example program: https://play.golang.org/p/DOUbRT9k_U

### What version of Go are you using (`go version`)?

go version go1.7 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/moshe/Documents/code/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y6/cd3mw6tx1qn89g0vn2pdz4gc0000gn/T/go-build725917179=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

https://play.golang.org/p/DOUbRT9k_U

### What did you expect to see?

I expected to get an error from json.Marshal

### What did you see instead?

No error and no encoding

**Comment by dominikh** [comment]
`go vet` in 1.8 will report duplicate tags (see https://github.com/golang/go/issues/12791). encoding/json probably shouldn't (can't) fail on duplicate tags because of a) embedding b) backwards compatibility.

**Comment by 0xmohit** [comment]
This appears to be by design; see https://golang.org/cl/8617044.

Also from the [documentation](https://golang.org/pkg/encoding/json/):

> Otherwise there are multiple fields, and all are ignored; no error occurs.

**Comment by 0xmohit** [comment]
[`vet`](https://golang.org/cmd/vet/) at tip detects duplicate struct tags (#17599).
