### ISSUE TITLE
encoding/json: stateEndTop allocates an error it doesn't return

### ISSUE THREAD

**Issue by sandymcp** [golang/go#17914]
### What version of Go are you using (`go version`)?

go version go1.7 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/almcpherson/gopath"
GORACE=""
GOROOT="/Users/almcpherson/go1.7"
GOTOOLDIR="/Users/almcpherson/go1.7/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jv/2c5lqc993lgdnm85hggybmw43959v8/T/go-build941373586=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

Running benchmarks to see why 
func stateEndTop(s *scanner, c byte) int  

is making calls to 

func (s *scanner) error(c byte, context string) int 

on valid json.

```go
package mapping

import (
	"encoding/json"
	"testing"
)

func BenchmarkLittleJSON(b *testing.B) {
	little := []byte(`{ "hello": "world", "x": {"n": 1, "m":2}, "world": ["1","2","3"], "what": "heh?"}`)
	for i := 0; i < b.N; i++ {
		var result struct {
			Hello string `json:"hello"`
			World []string `json:"world"`
		}
		if err := json.Unmarshal(little, &result); err != nil {
			b.Error(err)
		}
	}
}
```

https://play.golang.org/p/Fsvp3vGwXO

go test -bench "BenchmarkLittleJSON" -cpuprofile c.out
go tool pprof -peek error  test.test c.out 

### What did you expect to see?
no calls to error

### What did you see instead?
calls to error

1.18s of 1.18s total (  100%)
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context              
----------------------------------------------------------+-------------
                                             0.21s   100% |   encoding/json.stateEndTop
         0     0%     0%      0.21s 17.80%                | encoding/json.(*scanner).error
                                             0.11s 52.38% |   runtime.concatstring4
                                             0.07s 33.33% |   encoding/json.quoteChar
                                             0.03s 14.29% |   runtime.newobject
----------------------------------------------------------+-------------

**Comment by tejasmanohar** [comment]
May be worth providing a runnable example

**Comment by sandymcp** [comment]
Was in the middle of doing that, but inadvertently pasted too soon

**Comment by sandymcp** [comment]
Actually according to the comment for stateEndTop it seems it is intended to be called only when the top-level closes. However it is called multiple times. I put a print statement in stateEndTop. On the simple example above it gets called twice: once with ' ' and once with '}' as the argument c.

```go
// stateEndTop is the state after finishing the top-level value,
// such as after reading `{}` or `[1,2,3]`.
// Only space characters should be seen now.
func stateEndTop(s *scanner, c byte) int {
```

**Comment by sandymcp** [comment]
Possible fix works for me, passes the go build
```
diff --git a/src/encoding/json/scanner.go b/src/encoding/json/scanner.go
index a6d8706..c475642 100644
--- a/src/encoding/json/scanner.go
+++ b/src/encoding/json/scanner.go
@@ -180,12 +180,7 @@ func (s *scanner) popParseState() {
        n := len(s.parseState) - 1
        s.parseState = s.parseState[0:n]
        s.redo = false
-       if n == 0 {
-               s.step = stateEndTop
-               s.endTop = true
-       } else {
-               s.step = stateEndValue
-       }
+       s.step = stateEndValue
 }

 func isSpace(c byte) bool {
```

**Comment by sandymcp** [comment]
At the end of an object or array in the first level of the json object the parseLevel falls back to 0 and the code calls stateEndTop.

**Comment by quentinmit** [comment]
I don't understand the bug here; it looks to me like the Unmarshal call is correctly returning a nil error. It sounds like you think there is some optimization to be done?

**Comment by pascaldekloe** [comment]
Correct @quentinmit, I've submitted a FIX as: https://go-review.googlesource.com/#/c/33276/

**Comment by bradfitz** [comment]
Assigned to @rsc for review of https://go-review.googlesource.com/c/go/+/47152
