### ISSUE TITLE
plugin: cannot load a plugin from a test where the plugin includes the tested package

### ISSUE THREAD

**Issue by crawshaw** [golang/go#17928]
On #17832 @wendigo notes that a go test for package ```p``` cannot load a plugin that imports package ```p``` without an error message about incorrect versions. This example is provided:

https://github.com/wendigo/go-plugin-33161

This is caused by the go tool rebuilding a package to include the test files, making the package in the test program incompatible with the equivalent package in the plugin.

I don't think this necessarily needs to work, it is entirely possible to do the plugin work from an external test from a package ```p_test```. But maybe we could use a more helpful error message.

Any suggestions?

cc @ianlancetaylor

**Comment by wendigo** [comment]
```plugin.so``` built with particular version of go cannot be loaded in any test package built with the same go version. From my perspective it basically limits possible usage of plugins as I cannot load and use plugins in tests and cannot test plugin itself in a test.

**Comment by crawshaw** [comment]
It cannot be loaded into a test that is inside a package included in the plugin. Try changing your test to a separate package, typically done by replacing the package declaration with ```package mypkg_test```.

**Comment by wendigo** [comment]
Already done that in the attached test case - result is the same (it seems that package name doesn't matter at all).

**Comment by wendigo** [comment]
Also I've noticed that for mismatched packages like `runtime` or `os` `*pkghash.runtimehash` is `""` (empty string).

**Comment by wendigo** [comment]
Any news @crawshaw. I noticed that sometimes plugin cannot be also loaded outside the test (`plugin.Open: plugin was built with a different version of package runtime`).

**Comment by wendigo** [comment]
Ping @crawshaw, @ianlancetaylor

**Comment by wendigo** [comment]
Fixed for me 👍 Thx @crawshaw
