### ISSUE TITLE
cmd/compile: branch too far on arm64

### ISSUE THREAD

**Issue by dvyukov** [golang/go#17925]
go version devel +b687d6a Tue Nov 15 05:35:54 2016 +0000 linux/amd64

Compilation of this file crashes on arm64:
https://gist.githubusercontent.com/dvyukov/85c7fa1b78b89ae2a16b27c3d681653f/raw/94b1ba106e5d748ab4b0efc8cbecc14b240f49fe/gistfile1.txt

```
$ GOARCH=arm64 compile sys_amd64.go
sys_amd64.go:20611: branch too far 0xc9579 vs 0x40000 [0x0]
00180 (/tmp/sys_amd64.go:1780)	CBNZW	R2, 3298968
3298968 (/tmp/sys_amd64.go:1780)	MOVD	R0, 8(RSP)
```

amd64 works fine.

**Comment by dvyukov** [comment]
@matt2909

**Comment by bradfitz** [comment]
@cherrymui, can you triage for Go 1.8 vs Go 1.9?

**Comment by cherrymui** [comment]
The bug is introduced in b662e52. Marked as Go 1.8. Will try to make a fix.
