### ISSUE TITLE
syscall.MAFTER plan9 constant has disappeared

### ISSUE THREAD

**Issue by sirnewton01** [golang/go#17921]
### What version of Go are you using (`go version`)?
1.7.3

### What operating system and processor architecture are you using (`go env`)?
plan9 386

### What did you do?
I tried compiling an existing golang library that worked with earlier versions of go with the latest. It make a call to plan9 bind (syscall.Bind) and specifies that the bind should come after existing entries in that directory using the MAFTER flag.

The repository is here: https://bitbucket.org/mischief/draw9

### What did you expect to see?
I expected that the code would continue to compile.

### What did you see instead?
Instead, there is a compile error indicating that syscall.MAFTER is not defined in the syscall package.

**Comment by minux** [comment]
Interesting. It's removed in CL 2167 (https://golang.org/cl/2167), which is
included in Go 1.5 and above.

**Comment by bradfitz** [comment]
plan9 is not a first class port and has never had the API checker enabled for it. (The API checker checks we never change or remove symbols between releases).

**Comment by bradfitz** [comment]
@0intro, I'll let you prioritize how you want to fix this, if at all.

**Comment by 0intro** [comment]
Thanks for reporting. I'll add these back for inclusion into Go 1.8.

**Comment by bradfitz** [comment]
Related: #14892 tracks adding more GOOS/GOARCH pairs to the API checker.
