### ISSUE TITLE
misc/cgo/testcshared: flaky on linux/amd64?

### ISSUE THREAD

**Issue by cherrymui** [golang/go#17947]
(The issue may already exist, but I couldn't find one...)

builder failure:
https://build.golang.org/log/17502ae096be2c10fedd81dbb9211e195aba2871
https://build.golang.org/log/415ae3c44929c4e3d54987e18fbe382b6aeac3f1

trybot failure: (on https://go-review.googlesource.com/c/33304/)
https://storage.googleapis.com/go-build-log/7d760e06/linux-amd64-ssacheck_598c0c9b.log
https://storage.googleapis.com/go-build-log/2f40e962/linux-amd64_a884cd40.log
etc.

**Comment by bradfitz** [comment]
Yeah, @ianlancetaylor and I were just discussing this. No clue what's going on yet.

**Comment by ianlancetaylor** [comment]
I'm pretty sure this must be related to https://golang.org/cl/33142, though I don't see how.

@bcmills

**Comment by ianlancetaylor** [comment]
The failure, as seen in 

https://build.golang.org/log/17502ae096be2c10fedd81dbb9211e195aba2871
https://build.golang.org/log/415ae3c44929c4e3d54987e18fbe382b6aeac3f1
https://storage.googleapis.com/go-build-log/2f40e962/linux-amd64_a884cd40.log

is that the third and last time that misc/cgo/testcshared/main5.c raises `SIGIO`, the program crashes.  At that point the signal handler is supposed to be the C signal handler that was installed before the shared library was dlopened'd.  The C signal handler should have been restored by the call to `ResetSIGIO` which calls `signal.Reset(syscall.SIGIO)` which eventually calls `sigdisable(SIGIO)` which calls `setsig(sig, fwdSig[sig])` which should have the effect of setting the signal handler back to the value it had when the shared library was loaded.

**Comment by ianlancetaylor** [comment]
I don't know for sure that this is fixed, as I was not able to recreate the problem.  Optimistically leaving this closed; let's see if the problem recurs.

**Comment by mwhudson** [comment]
I saw this a bunch of times on Launchpad builders but haven't seen it since that fix (I have daily builds going now). I'll post here if it reappears.
