### ISSUE TITLE
compress/bzip2: dead shifts in newHuffmanTree 

### ISSUE THREAD

**Issue by mvdan** [golang/go#17949]
I just found this code in `compress/bzip2/huffman.go`, line 110:

```
if length > pairs[i].length {
        // If the code length decreases we shift in order to
        // zero any bits beyond the end of the code.
        length >>= 32 - pairs[i].length
        length <<= 32 - pairs[i].length
        length = pairs[i].length
}
```

I fail to see what the two shifts accomplish. Whatever the expressions do, the value is stomped by the final assignment. I'm not sure what the expected logic is here, or whether this is causing a bug of some sort. But the code seems wrong to me.

**Comment by mvdan** [comment]
CC @agl who it seems wrote the code.

**Comment by dsnet** [comment]
I can take this. I want to re-write the bzip2 huffman decoder anyways. It's the same decoder as what's used in `compress/flate`, only that the the flate version is faster.

**Comment by bradfitz** [comment]
@dsnet, fix looks easy. Send for 1.9?

**Comment by dsnet** [comment]
Filing seperate issue for re-writing bzip2 huffman logic. #20485
