### ISSUE TITLE
gerrit: complains about commit bodies wrapped at 72 chars

### ISSUE THREAD

**Issue by mvdan** [golang/go#17941]
```
 $ git-codereview mail
remote: Processing changes: new: 1, done
remote: (W) f3388a2: too many commit message lines longer than 70 characters; manually wrap lines
[...]
```

It is my understanding that this is a setting that can be changed in gerrit. Is there a reason why 70 was chosen?

As far as I can tell, 72 is the most commonly used wrapping length for commit bodies in git:

http://chris.beams.io/posts/git-commit/#wrap-72
https://bugs.chromium.org/p/gerrit/issues/detail?id=841
https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c#.3154gadgk

At the same time, I can't find any reference to this in any official Git docs.

Is there a reason why our gerrit instance is configured like this?

**Comment by 0xmohit** [comment]
The choice may be subjective, but the default `fill-column` for emacs is 70.

**Comment by mvdan** [comment]
For comparison, vim seems to default to 72:

```
 $ grep textwidth </usr/share/vim/vim80/ftplugin/gitcommit.vim
setlocal nomodeline tabstop=8 formatoptions+=tl textwidth=72
```

I don't think editor defaults should play a major role here, though.

**Comment by robpike** [comment]
Just ignore the warning. I do. 

No person should care how many characters are on a line, but for a computer to care is just ridiculous.

**Comment by mvdan** [comment]
@robpike given that git doesn't play well with non-wrapped commit bodies, I do think a warning (not an error) like this is somewhat useful for people who aren't wrapping their non-quoted text.

What I'm proposing is that since 72 chars seems to be common practice and still plays well with git, the warning should be made less strict. Removing the warning altogether is also an option, but this change is a simple compromise.

**Comment by bradfitz** [comment]
I'm not sure this is even a Gerrit setting. @spearce?

Quick Google search didn't find anything at least. I didn't try too hard.

**Comment by mvdan** [comment]
@bradfitz have you looked at https://bugs.chromium.org/p/gerrit/issues/detail?id=841?

It's something that gerrit remote is saying, so I don't know where else this could be set. It's definitely not a git thing.

**Comment by bradfitz** [comment]
Ah, great. I missed that.

For reference,

```
Commit Message Length Configuration
===================================

The maximum lengths of the subject and message body can be
configured in the standard Gerrit config file `gerrit.config`.

commitmessage.maxSubjectLength
:       Maximum length of the commit message's subject line.  Defaults
        to 65 if not specified or less than 0.

commitmessage.maxLineLength
:       Maximum length of a line in the commit message's body.  Defaults
        to 70 if not specified or less than 0.

commitmessage.longLinesThreshold
:       Percentage of commit message lines allowed to exceed the
        maximum length before a warning or error is generated.  Defaults
        to 33 if not specified or less than 0.

commitmessage.rejectTooLong
:       If set to `true`, reject commits whose subject or line
        length exceeds the maximum allowed length.  If not
        specified, defaults to `false`.
```

**Comment by bradfitz** [comment]
Okay, I sent https://go-review.googlesource.com/#/c/33323/ to @ianlancetaylor adding:

```
[commitmessage]
	maxSubjectLength = 76
	maxLineLength = 72
```

... to the Go All-Projects configuration.

**Comment by mvdan** [comment]
Thanks!

Any rationale behind the subject length being so large? Usually it's kept lower, like 50 as mentioned in the links I provided or 65 according to gerrit.

**Comment by robpike** [comment]
Is there some reason we're picking 76? Is it some celebration of the signing of the US Declaration of Independence? Can't it be something useful, like 100 or 200 or 1e6?

I need to oil my 026 keypunch http://www.columbia.edu/cu/computinghistory/026.html

**Comment by bradfitz** [comment]
I'm bored of this bug.

I'll let somebody else take this over.

**Comment by rsc** [comment]
A year later, I have taken this over, in part because the default limits seem to be decreasing over time. I set both limits to 1000 in https://go-review.googlesource.com/c/All-Projects/+/78090/3/project.config. I hope we can all agree that lines longer than 1000 characters do deserve a warning.

**Comment by rsc** [comment]
OK, that CL did nothing. For future reference, the right magic appears to be:

	gob-ctl <<<'update_host{host: "go" set_gerrit_config{name: "commitmessage.maxSubjectLength" value: "1000"}}'
	gob-ctl <<<'update_host{host: "go" set_gerrit_config{name: "commitmessage.maxLineLength" value: "1000"}}'

or else to have edited the gerrit.config stored in Google's internal repos and waited for the next (day or two) config push.
I hope the gob-ctl commands do not get overwritten.
