### ISSUE TITLE
cmd/compile: use directive instead of command-line option for the `compiling_runtime` mode (aka '-+')

### ISSUE THREAD

**Issue by typeless** [golang/go#17942]
In summary, that will make the subset of Go which is capable of writing the runtime code available to users.

Purposes:

1. Sometimes we want to write libraries in Go that would be linked by other languages. Most of the time a library equipped with its own runtime would be too heavyweight.

2. Compiler-aided guarantee of zero-allocation code. That would make Go usable in certain extreme environments (like writing IRQ handlers!). Writing performance-critical tight loops can be benefited as well.

3. Much economical binary size for tiny programs that don't require full-fledged GC and concurrency support (like those simple utilities whose jobs are mostly calling syscalls).

4. Potentially we gophers can invade further into C's territory.

5. Save C programmers from the living standard belonging to the last century.

**Comment by bradfitz** [comment]
I don't think we want to support two languages (Go and pseudo-Go). The `-+` flag is a necessary evil and internal detail, not something we want to encourage.

I'm going to close this, but @ianlancetaylor and @rsc can reopen it if they disagree.

**Comment by typeless** [comment]
I'm a bit of confused about calling the idea psudeo-Go. By the standard any application which consciously avoids certain language features would be using a pseudo-Go. I agree it would probably incentivize people to overly use it

**Comment by typeless** [comment]
Oh sorry I'm on my phone and the above comment is a WIP accidentally getting posted. Please ignore it for now.
