### ISSUE TITLE
blog: replace protocol-relative references to https in Atom/RSS feed

### ISSUE THREAD

**Issue by yaronf** [golang/go#17961]
Sorry, there's no way to open an issue on the go/blog repo.

The Go Blog advertises an Atom feed, however its URL is broken (no http or https).

```
	<link rel="alternate" type="application/atom+xml" title="blog.golang.org - Atom Feed" href="//blog.golang.org/feed.atom" />
```
Similarly, each post has a link that's missing the http/https URL scheme.

Thanks!

**Comment by dominikh** [comment]
These are [protocol-relative URLs](https://en.wikipedia.org/wiki/Uniform_Resource_Locator#prurl).

**Comment by yaronf** [comment]
From a security POV, see why this doesn't make sense: https://www.paulirish.com/2010/the-protocol-relative-url/

And from a standards POV, relative URLs are not allowed in feeds. https://tools.ietf.org/html/rfc4287#section-4.2.6 says: "Its content MUST be an IRI, as defined by [RFC3987].  Note that the definition of "IRI" excludes relative references."

**Comment by bradfitz** [comment]
Leaving for @broady

**Comment by stqn1** [comment]
I believe this is the bug I’m seeing. It still happens with the latest blog post. When I try to open a link to an article from my RSS reader (the Bamboo addon) I get an error message saying it can’t open "//blog.golang.org/…".
It was also similarly broken months ago when I was using Liferea.

**Comment by davecheney** [comment]
Have your reported a bug to the manufactures of those products?

**Comment by yaronf** [comment]
This is clearly a server-side bug. Please see my [comment](https://github.com/golang/go/issues/17961#issuecomment-261270457) up this thread for an explanation why the RSS stream is not standards compliant.

**Comment by bwjohnson-ss** [comment]
This issue doesn't seem like it's got much attention in a while, but it still exists today. Any chance we can fix this?

**Comment by bradfitz** [comment]
Looks fixed to me in the code at least:

```
bradfitz@gdev:~/src/golang.org/x/blog$ git grep "blog.golang.org - Atom Feed"
template/root.tmpl:     <link rel="alternate" type="application/atom+xml" title="blog.golang.org - Atom Feed" href="https://blog.golang.org/feed.atom" />
```

From commit https://github.com/golang/blog/commit/f415e5b29c5b4d211782c6c6851b62d2070f2fdc

@broady, was this never deployed or something? But we've had tons of blog posts since then.

**Comment by broady** [comment]
Blog was last deployed today, so something else must be up.

**Comment by bwjohnson-ss** [comment]
To be more specific, I was referring to the actual feed content (https://blog.golang.org/feed.atom)

`<link rel="alternate" href="//blog.golang.org/modules2019">`

**Comment by broady** [comment]
Ahhh, got it. OK, I'm on it.

**Comment by broady** [comment]
Not sure why gopherbot didn't pick up the CL, but here it is:

https://go-review.googlesource.com/c/blog/+/155357

**Comment by bwjohnson-ss** [comment]
Hmmmm, I'm not too familiar with gopherbot and how it works, but should I expect the atom feed to be fixed now? Did the above change get deployed to prod? I don't see the fix yet.

**Comment by broady** [comment]
It'll go out with the next deploy (either if a blog post gets published or if someone decides to deploy before then).

And yeah, as Brad notes in the CL, I forgot to prefix with `golang/go` because it was outside the main repo.
