### ISSUE TITLE
x/image/font/gofont: ambiguous fonts names

### ISSUE THREAD

**Issue by sbinet** [golang/go#17964]
The https://blog.golang.org/go-fonts blog post speaks about "proportionally-spaced fonts" and "monospaced fonts".

While the latter set of fonts is easily mapped back to `"golang.org/x/image/font/gofont/gomono{,bold,bolditalic,italic}"`, the mapping is less obvious for the former.

What should be the equivalent `gofont` fonts for `Helvetica-{,Bold,Oblique,BoldOblique}` ? (ie: the sans-serif fonts)

Also, it seems there is no `Times-{Roman,Bold,Italic,BoldItalic}` equivalent ? (ie: the serif fonts)

Perhaps the `godoc` documentation for each package should mention `mono`, `serif` and `sans-serif` ?

**Comment by nigeltao** [comment]
The Go Font equivalents of Helvetica-{,Bold,Oblique,BoldOblique} are go{,bold,italic,bolditalic}, as both are proportional-width sans-serif.

There are no proportional-width serif fonts in the Go Font family. There might be in the future, but that's really up to Bigelow & Holmes, and I can't speak for them. (They also don't frequent this issue tracker, but we'll let them know that you're wondering about a proportional-width serif).
