### ISSUE TITLE
gc: unused variable bound to closure not recognized

### ISSUE THREAD

**Issue by stjj89** [golang/go#17968]
gc accepts the following snippet of code, but gccgo and go/types report that: "x declared but not used":

```go
func myfunc() {
  var x int
  go func() {
    x = 3
  }()
}
```

gccgo and go/types are probably correct here. x is only ever assigned to, but never returned or used. 

If I make x a return value, none of one of gc, gccgo, and go/types complain.

```go
func myfunc() {
  var x int
  go func() int {
    x = 3
    return x
  }()
}
```

**Comment by ianlancetaylor** [comment]
Dup of #8560.
