### ISSUE TITLE
x/image/font/gofont: poor quality on windows 7 firefox

### ISSUE THREAD

**Issue by ktye** [golang/go#17960]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
https://blog.golang.org/go-fonts

### What operating system and processor architecture are you using (`go env`)?
Windows 7
Firefox 49.0.2 or 50.0
Chrome 54.0.2840.99 m

### What did you do?
Read the article https://blog.golang.org/go-fonts

### What did you expect to see?
New nice fonts

### What did you see instead?
The experience differs quite a lot with zoom factor and browser supplier

While I strongly appreciate the work that lead to the new fonts for go, the experience on firefox is rather poor.
Please see the screenshots below.
Specialy 90% zoom factor looks not very nice, but also the (most imporant) 100% could be a lot better.
On chrome, the fonts look just different, a little lighter over all.
This is on windows 7 and it might be different with other operating systems.

Chrome 80%:
![ff_080](https://cloud.githubusercontent.com/assets/14950262/20391606/76c11738-acd4-11e6-9670-7bdfbf3bc060.PNG)

Firefox 80%:
![ff_080](https://cloud.githubusercontent.com/assets/14950262/20391635/8faa0f7a-acd4-11e6-8941-96fe4a425306.PNG)

Chrome 90%:
![chrome_090](https://cloud.githubusercontent.com/assets/14950262/20391608/7a1880ce-acd4-11e6-97ff-1a47e22f156e.PNG)

Firefox 90%:
![ff_090](https://cloud.githubusercontent.com/assets/14950262/20391661/a65e7760-acd4-11e6-9c3b-d36d24e5940f.PNG)

Chrome 100%:
![chrome_100](https://cloud.githubusercontent.com/assets/14950262/20391672/b105c13c-acd4-11e6-8931-b9dcf0fab452.PNG)

Firefox 100%:
![ff_100](https://cloud.githubusercontent.com/assets/14950262/20391953/05735dbe-acd6-11e6-9155-56ad80ca849a.PNG)

Chrome 150%:
![chrome_150](https://cloud.githubusercontent.com/assets/14950262/20391685/bd93239a-acd4-11e6-8da8-1703bf5ded3e.PNG)

Firefox 150%:
![ff_150](https://cloud.githubusercontent.com/assets/14950262/20391694/c51a83b0-acd4-11e6-8d4c-c83b61f097ca.PNG)

**Comment by dr2chase** [comment]
This seems not to reproduce on Mac OS X 10.11.6 w/Firefox 50.0, MacBook Air, display 1440x900.

At 90%:
![screen shot 2016-11-17 at 11 03 21 am](https://cloud.githubusercontent.com/assets/1928999/20396844/8d1d432c-acb5-11e6-93f8-c9961bbb04bf.png)

It also looked okay (the same, more or less) at 90% on Ubuntu.recent, and on both platforms it looked okay at other magnifications.

Can you try this on a more recent version of Windows?

**Comment by ktye** [comment]
It seems better with windows 10:
Firefox 90%:
![ffwin10_090](https://cloud.githubusercontent.com/assets/14950262/20407149/639ff8b8-ad10-11e6-8eb3-211f5e6ec882.PNG)

Firefox 100%:
![ffwin10_100](https://cloud.githubusercontent.com/assets/14950262/20407152/65889ff4-ad10-11e6-80fa-253a1a2343cb.PNG)

**Comment by robpike** [comment]
Windows 7 is very old and the font technology there is old too. I doubt there's much we can do.

**Comment by fraenky8** [comment]
Srsly? This is the "solution" to the problem? What about people working with a windows 7 computer given by the company?
