### ISSUE TITLE
sync: tests fail with mutex profiling

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17966]
As reported by @hyangah,

```
$ go test -v  -mutexprofile=prof.mutex -test.mutexprofilefraction=1 -test.bench=Misuse2
```

... sometimes fails. At least on Linux and with 

Can we detect (from the sync tests) that mutex profiling is enabled and skip some tests?

**Comment by rsc** [comment]
This report is not particularly actionable. Fails how? On Linux and with _what_?

**Comment by rsc** [comment]
Please reopen if you have more details. I'm assuming those are lost at this point.
