### ISSUE TITLE
Error while building bootstrap GO 1.4.3

### ISSUE THREAD

**Issue by magallardo** [golang/go#17962]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
GO 1.4.3

### What operating system and processor architecture are you using (`go env`)?
Linux/ARM5

### What did you do?

time sudo ./make.bash

### What did you expect to see?
Install success

### What did you see instead?
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
cmd/5a
cmd/5c
cmd/5g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
go tool dist: FAILED: /usr/local/go/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main /usr/local/go/src/cmd/go/bootstrap.go /usr/local/go/src/cmd/go/build.go /usr/local/go/src/cmd/go/clean.go /usr/local/go/src/cmd/go/context.go /usr/local/go/src/cmd/go/env.go /usr/local/go/src/cmd/go/fix.go /usr/local/go/src/cmd/go/fmt.go /usr/local/go/src/cmd/go/generate.go /usr/local/go/src/cmd/go/get.go /usr/local/go/src/cmd/go/go11.go /usr/local/go/src/cmd/go/help.go /usr/local/go/src/cmd/go/list.go /usr/local/go/src/cmd/go/main.go /usr/local/go/src/cmd/go/pkg.go /usr/local/go/src/cmd/go/run.go /usr/local/go/src/cmd/go/signal.go /usr/local/go/src/cmd/go/signal_unix.go /usr/local/go/src/cmd/go/test.go /usr/local/go/src/cmd/go/testflag.go /usr/local/go/src/cmd/go/tool.go /usr/local/go/src/cmd/go/vcs.go /usr/local/go/src/cmd/go/version.go /usr/local/go/src/cmd/go/vet.go /usr/local/go/src/cmd/go/zdefaultcc.go

real	10m1.072s
user	3m8.600s
sys	1m15.050s
robot@ev3dev:/usr/local/go/src$

**Comment by bradfitz** [comment]
Did you run out of memory?

ARM5 machines aren't known for having much RAM.

In any case, this sounds like a better topic for the mailing list. See https://golang.org/wiki/Questions

**Comment by davecheney** [comment]
What Brad said. Check dmesg to see if the OOM killler kicked in. You need a
minimum of 512mb pee core to compile Go.
