### ISSUE TITLE
x/tools/present: support mathematical symbols

### ISSUE THREAD

**Issue by Marqin** [golang/go#17978]
It would be nice to have support for mathematical symbols and equations in `present` tool.

You could implement it on your own (with LaTeX syntax or your own) or use some existing JS tool (eg. MathJax [Apache license]).

**Comment by robpike** [comment]
Present is pretty simple-minded. This seems outside its requirements.

**Comment by Marqin** [comment]
@robpike actually I found a **simple** way for doing this, with `.html` function.

If anyone want mathematical symbols, here's tutorial:
1. Save `<script...></script>` that includes your favourite JS syntaxer as `math.html`
2. Add `.html math.html` to any of slides (best I think is to add to last one)
3. It will magicaly work, you can test by writing`$$x_i = i\prime$$` in any slide and seeing it rendered.
