### ISSUE TITLE
strconv: FormatFloat(38.675, 'f', -1, 64) does not give the most precise decimal approximation

### ISSUE THREAD

**Issue by mrwonko** [golang/go#17997]
### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
Playground

### What did you do?
`strconv.FormatFloat(38.675, 'f', -1, 64)`
https://play.golang.org/p/r2SL1x_Uu6

### What did you expect to see?
38.675 doesn't have an exact float64 representation; I expected 38.6749999999999971578290569595992565155029296875.

### What did you see instead?
38.675

**Comment by ALTree** [comment]
> The special precision -1 uses the smallest number of digits necessary such that ParseFloat will return f exactly. 

The documentation doesn't say that `FormatFloat` will print the most precise decimal approximation. What it does say is that it'll output just enough digits so that `ParseFloat` will return f exactly.

**Comment by mrwonko** [comment]
So "exactly" in this context means a decimal representation whose closest float64 representation is the correct one?

**Comment by rsc** [comment]
Note that for what you expect, you can use:

    strconv.FormatFloat(38.675, 'g', 1000, 64)
