### ISSUE TITLE
cmd/compile: nil check not removed for Zero/Copy on some architectures

### ISSUE THREAD

**Issue by cherrymui** [golang/go#18003]
### What version of Go are you using (`go version`)?
tip (0bae74e)

### What operating system and processor architecture are you using (`go env`)?
AMD64

Compile this code:
```
type T struct {
        a, b, c, d, e, f, g, h int
}

func f(t *T) T {
        return *t
}
```

The nil check in `f` is not removed:
```
v6 = Arg <*T> {t}
v10 = LoweredNilCheck <void> v6 v9
v12 = VarDef <mem> {~r1} v9
v13 = DUFFCOPY <mem> [840] v7 v6 v12
```
It is because some Zero/Move ops are not marked as `faultOnNilArg0` etc. Will send a fix.

**Comment by bradfitz** [comment]
Unless this is a regression from Go 1.7, I'm targeting this as Go 1.9.
