### ISSUE TITLE
question: make([]byte, len, len) heap leaks

### ISSUE THREAD

**Issue by spx** [golang/go#18002]
go version go1.7.1 darwin/amd64 and binary runs on linux and compiled from osx with GOOS=linux GOARCH=amd64

(pprof) top
1.25GB of 1.25GB total (99.84%)
Dropped 209 nodes (cum <= 0.01GB)
      flat  flat%   sum%        cum   cum%
    1.25GB 99.84% 99.84%     1.25GB 99.84%  main.tvACL.backendRequest
         0     0% 99.84%     1.25GB 99.84%  github.com/golang/groupcache/singleflight.(*Group).Do
         0     0% 99.84%     1.25GB 99.84%  github.com/gorilla/mux.(*Router).ServeHTTP
         0     0% 99.84%     1.25GB 99.84%  main.(*tvACL).ServeHTTP
         0     0% 99.84%     1.25GB 99.84%  main.tvACL.ServeHTTP
         0     0% 99.84%     1.25GB 99.84%  main.tvACL.ServeTV
         0     0% 99.84%     1.25GB 99.84%  main.tvACL.ServeTV.func3
         0     0% 99.84%     1.25GB 99.84%  net/http.(*conn).serve
         0     0% 99.84%     1.25GB 99.84%  net/http.serverHandler.ServeHTTP
         0     0% 99.84%     1.25GB   100%  runtime.goexit
(pprof) 

(pprof) list main.tvACL.backendRequest
Total: 1.25GB
ROUTINE ======================== main.tvACL.backendRequest in /Users/mindaugas/code/rubinet/rb-cache/tvacl.go
    1.25GB     1.25GB (flat, cum) 99.84% of Total
<...>
    1.25GB     1.25GB    396:	buff := make([]byte, resp.ContentLength, resp.ContentLength)

(pprof) list runtime.goexit
Total: 1.25GB
ROUTINE ======================== runtime.goexit in /usr/local/go/src/runtime/asm_amd64.s
         0     1.25GB (flat, cum)   100% of Total
         .          .   2081:	RET
         .          .   2082:
         .          .   2083:// The top-most function running on a goroutine
         .          .   2084:// returns to goexit+PCQuantum.
         .          .   2085:TEXT runtime·goexit(SB),NOSPLIT,$0-0
         .     1.25GB   2086:	BYTE	$0x90	// NOP
         .          .   2087:	CALL	runtime·goexit1(SB)	// does not return
         .          .   2088:	// traceback from goexit1 must hit code range of goexit
         .          .   2089:	BYTE	$0x90	// NOP
         .          .   2090:
         .          .   2091:TEXT runtime·prefetcht0(SB),NOSPLIT,$0-8
(pprof)

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions
