### ISSUE TITLE
expvar: returned are not json string when using Publish()

### ISSUE THREAD

**Issue by Mohanson** [golang/go#18000]
### What version of Go are you using (`go version`)?
go version go1.6.1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\root\gopath
set GORACE=
set GOROOT=D:\Program Files\Go
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
```Go
package main

import (
	"expvar"
	"net/http"
	"time"
)

var origin = time.Now()

func init() {
	expvar.Publish("origin", origin)
}

func main() {
	go http.ListenAndServe("127.0.0.1:8080", nil)
	select{}
}
```

### What did you expect to see?
`curl http://127.0.0.1:8080/debug/vars | python -m json.tool` returned a JSON string and the KV of "origin" is `"origin": "2016-11-2123:19:50.3948635+0800CST"`

### What did you see instead?
`curl http://127.0.0.1:8080/debug/vars | python -m json.tool` raise a error because the returned output are not a JSON string. The KV of "origin" is `"origin": 2016-11-21 23:16:58.4657459 +0800 CST` (missing quote)

**Comment by bradfitz** [comment]
This is your responsibility. The docs were clarified recently in 2a12035f8ec18f0a577853fda78faf2826397131 :

```
commit 2a12035f8ec18f0a577853fda78faf2826397131
Author: Scott Bell <scott@sctsm.com>
Date:   Wed May 18 18:44:46 2016 -0700

    expvar: slightly expand documentation for Var's String method
    
    Fixes #15088.
    
    Change-Id: I7727829a4062e15c0e5e3beff4d0bfc1fa327b0f
    Reviewed-on: https://go-review.googlesource.com/23232
    Reviewed-by: Andrew Gerrand <adg@golang.org>
    Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>
```
