### ISSUE TITLE
encoding/json: unexported embedded fields are marshalled, but cannot be unmarshalled

### ISSUE THREAD

**Issue by jba** [golang/go#18009]
encoding/json will marshal field foo in
```go
type S struct{ foo }
type foo int
```
But since foo is unexported, unmarshalling panics.

### What version of Go are you using (`go version`)?

1.7.3

### What operating system and processor architecture are you using (`go env`)?

linux amd64 
### What did you do?

https://play.golang.org/p/P4iGGhkOAB

### What did you expect to see?

"{}" 

The only field of S is unexported, so it shouldn't marshal.

### What did you see instead?

{"foo":1}

and panic on unmarshal.

**Comment by dsnet** [comment]
This is a regression from Go 1.5 (i.e., it started to panic in Go 1.6).

**Comment by jba** [comment]
To be clear, the bug is in marshalling the unexported field, right?

My fix for the problem in my generalized field-selection package: https://code-review.googlesource.com/9485.

**Comment by jba** [comment]
Right. According to Go rules, an exported field inside an embedded struct (whether that embedded struct is exported or not) is visible. In other words, this works:
```
t := &Top{}
t.Q = 18
```
So "Q" should indeed be a key in the marshaled object.

**Comment by thoeni** [comment]
I'm trying to do my first contribution, therefore bear with me.
I've written this test, and I have an implementation that makes it pass (and doesn't break anything existing): does it model correctly what we want to achieve?

If I get to a field which happens to be not exported and not a struct, then it shouldn't be marshalled, but if the unexported field is actually a struct, then it's members might be marshalled if exported...

```go
type MyStructContainingUnexportedStruct struct {
	unexportedStruct
	unexportedIntType
}

type unexportedStruct struct {
	ExportedInt
	unexportedIntType
}

type ExportedInt int

func TestUnexportedAnonymousStructWithExportedType(t *testing.T) {
	s := unexportedStruct{11, 13}
	a := MyStructContainingUnexportedStruct{s, 12}
	const want = `{"ExportedInt":11}`

	b, err := Marshal(a)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	if got := string(b); got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}
```

**Comment by jba** [comment]
@thoeni That looks like the correct behavior to me.

**Comment by thoeni** [comment]
@jba I'll read the instructions on how to contribute and I'll push my proposal for this fix then :-)
Thanks for clarifying it for me!
