### ISSUE TITLE
net/http: TestLinuxSendfile failing on mips64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18008]
TestLinuxSendfile is failing on mips64 (but not mips64le) with:

```
--- FAIL: TestLinuxSendfile (0.25s)
	fs_test.go:1122: no sendfile system call found in:
		[pid  2578] +++ exited with 0 +++
		[pid  2577] +++ exited with 0 +++
		[pid  2576] +++ exited with 0 +++
		+++ exited with 0 +++
FAIL
FAIL	net/http	96.972s
```

Not sure why.

**Comment by cherrymui** [comment]
One possibility is that `strace` on the machine is either too old or not fully compatible with MIPS64 ABI. On some distros `strace` by default uses a different ABI, even the kernel is 64-bit. Not sure `trace=n64_sendfile` works or not.

**Comment by bradfitz** [comment]
Good theory.

**Comment by bradfitz** [comment]
That last CL didn't help. New output is:

```
--- FAIL: TestLinuxSendfile (0.16s)
	fs_test.go:1126: no sendfile system call found in:
		execve("/tmp/go-build627887128/net/http/_test/http.test", ["/tmp/go-build627887128/net/http/"..., "-test.run=TestLinuxSendfileChild"], [/* 33 vars */]) = 0
		[pid 20665] +++ exited with 0 +++
		[pid 20664] +++ exited with 0 +++
		[pid 20663] +++ exited with 0 +++
		+++ exited with 0 +++
```

**Comment by cherrymui** [comment]
I tried to trace `n64_sendfile` on linux-mips64 gomote machine. Now it sees the syscall,
```
=== RUN   TestLinuxSendfile
--- FAIL: TestLinuxSendfile (0.22s)
	fs_test.go:1122: no sendfile system call found in:
		[pid  4003] n64_sendfile()              = 22
		[pid  4006] +++ exited with 0 +++
		[pid  4005] +++ exited with 0 +++
		[pid  4004] +++ exited with 0 +++
		+++ exited with 0 +++
```
but it fails to get the arguments as it uses different ABI, so the regexp match later in the test function fails.

Also changing to trace `n64_sendfile` would break systems on which `strace` is using the 64-nit ABI (because the syscall is named `sendfile` there...). (One possible way is to try both...)

**Comment by vstefanovic** [comment]
This test is passing on a 64bit rootfs. We might want to setup mips64 buildbot to run on a 64bit rootfs (especially because of cgo), rather than adapting this test for 32bit rootfs.

**Comment by bradfitz** [comment]
@vstefanovic, what's the latest here? Can the test be re-enabled or be made robust to whichever environment it's running in?

**Comment by vstefanovic** [comment]
Yes, mips64 builder has a 64bit rootfs now, the test can be re-enabled.
