### ISSUE TITLE
net/http: TestTimeoutHandlerRaceHeader flaky?

### ISSUE THREAD

**Issue by cherrymui** [golang/go#18006]
trybot failure in CL https://go-review.googlesource.com/c/33235/.
https://storage.googleapis.com/go-build-log/85433af5/linux-amd64_b1b153f7.log

**Comment by bradfitz** [comment]
Fixed by https://go-review.googlesource.com/c/33420/

**Comment by bradfitz** [comment]
Oh, nevermind. Different timeout test.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/c/33432/
