### ISSUE TITLE
cmd/go: windows build doesn't report write error

### ISSUE THREAD

**Issue by piotrfti** [golang/go#18014]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH=amd64
GOHOSTOS=windows
GOOS=windows
GOGCCFLAGS=-m64 -mthreads -fmessage-length=0

### What did you do?
Compiled 'test.exe', run it, tried to compile to same file again while running.

### What did you expect to see?
Write error.

### What did you see instead?
Nothing. Go build exited without error, but 'test.exe' was obviously not updated.

**Comment by davecheney** [comment]
Please use -x to confirm that the go tool is compiling something.

**Comment by piotrfti** [comment]
OK, but shouldn't compiler inform user about such error by default? Any text editor does, for instance.

**Comment by davecheney** [comment]
If there is nothing to compile, go build will do nothing.

**Comment by bradfitz** [comment]
Please copy & paste here the command you run (with `-x` added) and its output.

**Comment by piotrfti** [comment]
go build -ldflags="-H windowsgui" -x

`WORK=AppData\Local\Temp\go-build870179366
mkdir -p $WORK\_\C_\Data\git\translations\go\gui\quarkChecker\_obj\
mkdir -p $WORK\_\C_\Data\git\translations\go\gui\quarkChecker\_obj\exe\
cd C:\Data\git\translations\go\gui\quarkChecker
"c:\\Data\\Portable\\PortableApps\\go\\pkg\\tool\\windows_amd64\\compile.exe" -o "AppData\\Local\\Te
mp\\go-build870179366\\_\\C_\\Data\\git\\translations\\go\\gui\\quarkChecker.a" -trimpath "AppData\\
Local\\Temp\\go-build870179366" -p main -buildid b9a1985bd9270962f5b434b31379e26bfb1c5797 -D _/C_/Data/git/translations/
go/gui/quarkChecker -I "AppData\\Local\\Temp\\go-build870179366" -pack "C:\\Data\\git\\translations\
\go\\gui\\quarkChecker\\checker.go" "C:\\Data\\git\\translations\\go\\gui\\quarkChecker\\quarkChecker.go"
pack r "AppData\\Local\\Temp\\go-build870179366\\_\\C_\\Data\\git\\translations\\go\\gui\\quarkCheck
er.a" "C:\\Data\\git\\translations\\go\\gui\\quarkChecker\\rsrc.syso" # internal
cd .
"c:\\Data\\Portable\\PortableApps\\go\\pkg\\tool\\windows_amd64\\link.exe" -o "AppData\\Local\\Temp\
\go-build870179366\\_\\C_\\Data\\git\\translations\\go\\gui\\quarkChecker\\_obj\\exe\\a.out.exe" -L "C:\\Users\\pczajko\
\AppData\\Local\\Temp\\go-build870179366" -extld=gcc -buildmode=exe -buildid=b9a1985bd9270962f5b434b31379e26bfb1c5797 -H
 windowsgui "AppData\\Local\\Temp\\go-build870179366\\_\\C_\\Data\\git\\translations\\go\\gui\\quark
Checker.a"
cp $WORK\_\C_\Data\git\translations\go\gui\quarkChecker\_obj\exe\a.out.exe quarkChecker.exe`

I've stripped c:\users\username part.

**Comment by davecheney** [comment]
It doesn't look like you've set GOPATH

**Comment by piotrfti** [comment]
It's set to c:\Data\go. And sometimes there's mv instead of cp, like "mv $WORK\_\C_\Data\git\translations\go\gui\quarkChecker\_obj\exe\a.out.exe quarkChecker.exe".

**Comment by davecheney** [comment]
It doesn't look like your source is in C:\data\go\src

**Comment by piotrfti** [comment]
That's true, it's in completely different location.

**Comment by sgen** [comment]
Your GOPATH structure isn't optional. Go source code must reside in GOPATH\src\. See [Getting Started](https://golang.org/doc/code.html#GOPATH).

**Comment by rsc** [comment]
Why is it obvious that test.exe was not updated? 

Please show a command transcript (full commands and output) with these commands in sequence:

* build
* dir test.exe
* build
* dir test.exe

Thanks.

**Comment by rsc** [comment]
Timed out waiting for reply.
