### ISSUE TITLE
playground: playground doesn't report panic upon div-zero

### ISSUE THREAD

**Issue by griesemer** [golang/go#18024]
https://play.golang.org/p/WMAoDrz4eu

runs without panic. Running the same program on the command line
```
package main

func main() {
	x := 0
	_ = 1 / x
}
```
results in a run-time panic:
```
$ go run x.go
panic: runtime error: integer divide by zero

goroutine 1 [running]:
panic(0x1058460, 0x1095be0)
	/Users/gri/go/src/runtime/panic.go:531 +0x1cf
main.main()
	/Users/gri/tmp/x.go:5 +0x5
exit status 2
```

**Comment by odeke-em** [comment]
@griesemer that reminds me of this bug https://github.com/golang/go/issues/8613. Can we check that the playground is using a version of Go that uses the SSA backend? Running https://play.golang.org/p/gWA-fmyoJW on the playground gives me Go version 1.7.

**Comment by bradfitz** [comment]
SSA didn't support `nacl` until Go 1.8 (https://play.golang.org/p/SWEsB2dtNo). So no, it's not SSA.

**Comment by odeke-em** [comment]
Thanks @bradfitz. In that case then according to @randall77's comment here https://github.com/golang/go/issues/8613#issuecomment-203721632, it is fixed but not until Go1.8 rolls out for the playground, so a dup of https://github.com/golang/go/issues/8613.

**Comment by randall77** [comment]
On tip we should update Brad's test to remove the +amd64.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/33491

**Comment by odeke-em** [comment]
@bradfitz could we triage this bug for Go1.9 instead of Unreleased so that once Go1.8
is released and when the playground is updated, we can then close this bug?

**Comment by ALTree** [comment]
Fixed by the playground go1.8 upgrade.
