### ISSUE TITLE
cmd/go: go test runner needs a monotonic clock

### ISSUE THREAD

**Issue by tamird** [golang/go#18021]
On (not as rare as we'd like) occassion, we observe clocks moving backwards in our CI environment. 

There are many problems with this, but in particular, it can cause `go test` to emit negative test runtimes (see https://github.com/cockroachdb/cockroach/issues/10937, which contains:
```
--- FAIL: TestServerQueryStarvation (-0.13s)
	server_test.go:262: error storing data for series 22, source 4: storage/store.go:2257: rejecting command with timestamp in the future: 1479800017448958100 (281.69074ms ahead)
FAIL
```
).

This is due to the use of a non-monotonic clock in:
- https://github.com/golang/go/blob/26827bc/src/testing/testing.go#L601
- https://github.com/golang/go/blob/26827bc/src/testing/testing.go#L635

and perhaps others.

This issue is related to #12914.

**Comment by rsc** [comment]
Fixed along with #12914.
