### ISSUE TITLE
x/tools/cmd/goimports: unnecessary PackageName in ImportSpec

### ISSUE THREAD

**Issue by mdempsky** [golang/go#18027]
$ printf 'package p\nvar _ = sheets.SpreadsheetsReadonlyScope\n' | goimports
    package p

    import sheets "google.golang.org/api/sheets/v4"

    var _ = sheets.SpreadsheetsReadonlyScope

The package name is already `sheets`, so there's no need to explicitly name it.

/cc @bradfitz

**Comment by bradfitz** [comment]
Intentional.

It's more explicit. And it makes future goimports runs faster, not having to scan the "v4" directory to figure out what it means.

**Comment by mdempsky** [comment]
Seems inconsistent that it leaves `import "google.golang.org/api/sheets/v4"` alone.

**Comment by bradfitz** [comment]
I don't follow. You didn't say anything about that in your bug report.

**Comment by mdempsky** [comment]
$ printf 'package p\nimport "google.golang.org/api/sheets/v4"\nvar _ = sheets.SpreadsheetsReadonlyScope\n' | goimports
    package p

    import "google.golang.org/api/sheets/v4"

    var _ = sheets.SpreadsheetsReadonlyScope

**Comment by bradfitz** [comment]
I still think it's fine. That is: don't mess with people's existing imports if they wrote them by hand or tweaked them by hand. But if we're adding them automatically, then we get to remind them of convention. (dir name == package name) If they don't follow convention, we help readers out. If they don't like it, they can delete it or follow convention.
