### ISSUE TITLE
binary.Write(net.UDPAddr.Port) silently fails

### ISSUE THREAD

**Issue by jech** [golang/go#18032]
Using go 1.7.3 on linux/amd64.

I tried to use binary.Write on a net.UDPAddr.Port, nothing was buffered.  This took a while to debug.

    https://play.golang.org/p/CtZgXsWMUL

I would have expected the binary.Write to either do the right thing (buffer two octets of data) or generate an error (either at compile time or at runtime).

**Comment by bradfitz** [comment]
It did return an error. You didn't check it. https://play.golang.org/p/owZlw_-2LP

**Comment by jech** [comment]
My bad.

**Comment by jech** [comment]
Thinking about it some more -- shouldn't it panic instead of returning an
error?  It's clearly a programmer's error, and it's all the more confusing
since Buffer.Write is documented as never returning an error.

**Comment by bradfitz** [comment]
bytes.Buffer's documentation is irrelevant. You're not even making it that far. You're passing in something bogus to binary.Write and that is what is returning an error.

**Comment by jech** [comment]
> bytes.Buffer's documentation is irrelevant. You're not even making it that
> far. You're passing in something bogus to binary.Write and that is what is
> returning an error.

I realise that.  But I find this behaviour confusing, I'd expect it to
panic in this particular case.

**Comment by bradfitz** [comment]
If something returns an error, check the error. That is the rule in Go.

A panic is not appropriate in this case.
