### ISSUE TITLE
encoding/json: simplify dominantField

### ISSUE THREAD

**Issue by jba** [golang/go#18037]
### What version of Go are you using (`go version`)?

1.7.3

### What operating system and processor architecture are you using (`go env`)?

any

### Enhancement

Since byName sorts by index depth and tag presence, the dominant field is always the first. So the dominantField function can be simplified to checking for the error case: more than one field at top level, both tagged or both untagged.

```go
func dominantField(fs []field) (field, bool) {
    if len(fs) > 1 && len(fs[0].index) == len(fs[1].index) && fs[0].tag == fs[1].tag {
        return field{}, false
    }
    return fs[0], true
}
```
See  https://code-review.googlesource.com/9552.

**Comment by mvdan** [comment]
@jba I'm not sure I understand the point of this issue - are you going to send a CL with the simplification?
