### ISSUE TITLE
x/mobile: java.lang.UnsatisfiedLinkError when package name with '-'

### ISSUE THREAD

**Issue by Kuloud** [golang/go#18046]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kuloud/Dev/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dq/1jrcxg1156l7ncr_8jsmwwpc0000gn/T/go-build903651586=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
gomobile bind package for android which contains '-', it throws UnsatisfiedLinkError when call the gobind methods.

for example:
com.kuloud.gobind.test-case

### What did you expect to see?
support package name with '-'

### What did you see instead?
N/A

**Comment by eliasnaur** [comment]
Please provide me with a complete example that demonstrates the error. You only provided a package name.
