### ISSUE TITLE
cmd/go: tests regularly timing out on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#18047]
The cmd/go tests are regularly timing out after 3m on the plan9/386 builder. The issue happened the first time on 2016-11-18.

See https://build.golang.org/log/d0b1a47cba400dd5f3693a0702fe19385a73372c

On the plan9/arm builder, the cmd/go tests are passing successfully because the timeout has been set to 18m. On this machine (Raspberry Pi 3), cmd/go tests takes approximately 14m to complete.

Maybe we should try to set `GO_TEST_TIMEOUT_SCALE=2` on the plan9/386 builder.

**Comment by bradfitz** [comment]
`GO_TEST_TIMEOUT_SCALE` was deployed and seems to have worked. The column is all happy now.
