### ISSUE TITLE
Is That a bug to strings.TrimRight() ?

### ISSUE THREAD

**Issue by AnotherGoogleFan** [golang/go#18045]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
$ go version
go version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\GoProject
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
	fmt.Println(strings.TrimRight("a/b/b/ccccc/", "abc/"))
	fmt.Println(strings.TrimRight("a/b/b/ccccc/", "bc/"))
	fmt.Println(strings.TrimRight("a/b/b/ccccc/", "c/"))
	fmt.Println(strings.TrimRight("a/b/b/ccccc/", "/"))
### What did you expect to see?

a
abb
abbcccc
### What did you see instead?

a
a/b/b
a/b/b/ccccc

**Comment by davecheney** [comment]
This is working as intended. 

TrimRight removes the _set_ of characters from the string starting from the right. It stop when it finds a character that is not in the remove set.

    strings.TrimRight("a/b/b/ccccc/", "abc/")

starts from the right, removes the `/`, leaving a set of `abc/`, then it removes all the `c`s, then it removes the `/`, then it removes the `b`, and so on.

    fmt.Println(strings.TrimRight("a/b/b/ccccc/", "c/"))

Removes the `/`, then all the `c`s, then the `/`, then finds a `b`, which is not part of the remove set so it stops.

**Comment by AnotherGoogleFan** [comment]
@davecheney   Thank U so much. Now I understand it.
