### ISSUE TITLE
cmd/compile: document go:noinline compiler directive

### ISSUE THREAD

**Issue by hiltjo** [golang/go#18049]
### What version of Go are you using (`go version`)?
go-git (commit a2bd5c5563261309cb14a7f233d9fc89a2873c8a) and 1.7.3

### Issue ###

I noticed the go:noinline compiler directive is not documented on the page
https://golang.org/cmd/compile/ .

### Fix ###

A patch is attached to fix it. The wording can probably be expanded and improved though.

https://cow.codemadness.org/go/patches/0001-cmd-compile-document-go-noinline-compiler-directive.patch

Edit: attaching patches on github sucks, so I made a link to the patch.

**Comment by 0xmohit** [comment]
Please refer to [Contributing Guidelines](https://golang.org/doc/contribute.html).

**Comment by ianlancetaylor** [comment]
The go:noinline comment is only intended for testing the compiler.  It is not intended for general use.  Therefore, it is not documented in the user documentation.  See the discussion at #12312.

(It would be nice if there were better internal documentation for the compiler, which is where this should be documented, but that is a separate issue.)
