### ISSUE TITLE
runtime: fatal error: failed to get system page size / panic before malloc heap initialized

### ISSUE THREAD

**Issue by steeve** [golang/go#18041]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version devel +8ace346 Wed Nov 23 01:16:47 2016 +0000 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/steeve/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/HEAD-8ace346/libexec"
GOTOOLDIR="/usr/local/Cellar/go/HEAD-8ace346/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bs/51dlb_nn5k35xq9qfsxv9wc00000gn/T/go-build321427714=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
Build a `gomobile` library for Android, link it, and try to launch the app and use the library.

### What did you expect to see?
The app launching.

### What did you see instead?
```
fatal error: failed to get system page size
runtime: panic before malloc heap initialized
runtime stack:
runtime.throw(0x7f75837534, 0x1e)
    /usr/local/Cellar/go/HEAD-8ace346/libexec/src/runtime/panic.go:596 +0x70 fp=0x7f74fe2300 sp=0x7f74fe22e0
runtime.mallocinit()
    /usr/local/Cellar/go/HEAD-8ace346/libexec/src/runtime/malloc.go:223 +0x46c fp=0x7f74fe23a0 sp=0x7f74fe2300
runtime.schedinit()
    /usr/local/Cellar/go/HEAD-8ace346/libexec/src/runtime/proc.go:465 +0x38 fp=0x7f74fe23e0 sp=0x7f74fe23a0
runtime.rt0_go(0x7f8fa36d48, 0x7f8ff012c0, 0x4f14, 0x0, 0x0, 0x7f75f3f440, 0x0, 0x4f1400004f26, 0x0, 0x7f74ee5000, ...)
    /usr/local/Cellar/go/HEAD-8ace346/libexec/src/runtime/asm_arm64.s:70 +0xbc fp=0x7f74fe2410 sp=0x7f74fe23e0
```

**Comment by minux** [comment]
/cc @aclements

It seems we need to have a fallback method (read /proc/self/auxv?)
to get the physical page size in runtime/os_linux.go?

**Comment by steeve** [comment]
Also, it this was not clear, the bug happens on android/arm arm64. Works fine on darwin/arm64. Haven't tested linux/arm64 too.

Seems to be linked to https://go-review.googlesource.com/#/c/25022/.

**Comment by minux** [comment]
Right. darwin/arm64 always uses sysctl to query system page size,
only the linux port relies on AUXV. But for shared library and static
libraries, the AUXV might not be (directly) available.

**Comment by aclements** [comment]
> It seems we need to have a fallback method (read /proc/self/auxv?)
> to get the physical page size in runtime/os_linux.go?

Yes, we probably need something like that, but since this is GOOS=android, os_linux.go isn't involved right now. As far as I can tell, Android isn't even trying to set the physical page size. I'm not very familiar with the Android runtime init process, which is quite different from other OSes, so I'm trying to work out where to put this setup now.

**Comment by aclements** [comment]
> I'm not very familiar with the Android runtime init process

Okay, for example, I did not understand the GOOS=android apparently implies the linux build tag, so os_linux.go *is* involved. But I think rt0_android_*.go is synthesizing an empty auxv.

**Comment by steeve** [comment]
FYI, this is still an issue in go 1.8b2.
While 6f287fa fixes the issue in debug mode apps, release mode apps fail because `/proc/self/auxv` because of denied permissions.

This is the same issue as https://github.com/golang/go/issues/9229

**Comment by minux** [comment]
@crawshaw, perhaps it's time to bump NDK requirement
and just use bionic's getauxval?

**Comment by steeve** [comment]
I would advize against that since using `getauxval` requires 21+.
That means dropping almost 37% of the Android user base, according to https://developer.android.com/about/dashboards/index.html

Could falling back to auvx generation (like it used to) as a last resort be an option ?

We ourselves release on 16+.

**Comment by quentinmit** [comment]
Can we use `getauxval` on 21+ and the private `__libc_auxv` if available on
previous versions?​

**Comment by minux** [comment]
A crazy idea:
when all else fail, we try mmap a few times to
determine the system page size.

**Comment by minux** [comment]
@steeve, could you please test CL 34610 and see if it works
in production build?

If you got "Recompile using GOARM=5." message, please
see if making "func checkgoarm" in runtime/os_linux_arm.go
simply return fixes the problem and allow the application to
run. Thanks.

I failed to find an Android device with such limiting SELinux
rules.

**Comment by steeve** [comment]
@minux sorry for the lag.
Just tested it with `860c9c0` and i can confirm it works fine.
Thank you all, that was super fast!
