### ISSUE TITLE
linker.exe not looking in GOPATH for some packages

### ISSUE THREAD

**Issue by BahNahNah** [golang/go#18050]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
amd64
windows 10

### What did you do?
Importing some(?) packages seems to confuse link.exe
In my "projectname/controllers/users.go" file, i am trying to import the package "github.com/gorilla/mux".

Doing so results in this error:

```
# command-line-arguments
C:\Go\pkg\tool\windows_amd64\link.exe: cannot open file C:\Go\pkg\windows_amd64/github.com/gorilla/mux.a: open C:\Go\pkg\windows_amd64/github.com/gorilla/mux.a: The system cannot find the path specified.
```

but my GOPATH variable is set to D:\Dev\Go\Projects. When I change the mux package to an invalid path, I get this error (as expected)

```
controllers\users.go:6:2: cannot find package "github.com/gorilla/mux_err" in any of:
C:\Go\src\github.com\gorilla\mux_err (from $GOROOT)
D:\Dev\Go\Projects\src\github.com\gorilla\mux_err (from $GOPATH)
```

But it is looking in the correct path now.

### What did you expect to see?
linker.exe looking in the correct directory for the package.

### What did you see instead?
linker.exe only looking in the GOROOT path.

This does not happen in the main package.

**Comment by tural-esger** [comment]
How did you solve this issue?

**Comment by BahNahNah** [comment]
Make sure you are using the full path when importing packages (e.g. github.com/BahNahNah/MyProject/controllers)

I cant remember exactly what I was doing to cause this error but it was something to do with the way I was importing my controllers package.

**Comment by dzdx** [comment]
I reslove the problem by remove all file in $GOPATH/pkg.  The cause of this problem is that I upgraded golang

**Comment by KromDaniel** [comment]
> I reslove the problem by remove all file in $GOPATH/pkg. The cause of this problem is that I upgraded golang

I'm a programmer 5 years, I never had this huge nightmare with new language as I have with GO.
it just doesn't work.
I have to delete $GOPATH/pkg before **EVERY** compile or I get linker error, no body knows why

**Comment by davecheney** [comment]
@KromDaniel this issue was closed several years ago. I suggest you open a new issue or ask for help using one of the support forums. Please see https://golang.org/wiki/Questions for good places to ask questions.
