### ISSUE TITLE
It looks Go spec doens't cover comparing two untype values.

### ISSUE THREAD

**Issue by golang101** [golang/go#18057]
It seems the two untyped numeric values will both converted to complex128. 

Example:

	package main
	
	func main() {
		const C = 1 + 2i
		const F = 1.0
		const I = 0xFFFFFFFFFFFFFFFFFFF

		println(C == F) // <=> complex128(c) == complex128(F)
		println(I == F) // <=> complex128((I) == complex128((F)
	}

**Comment by griesemer** [comment]
Untyped numbers are just that: numbers. They will be compared as numbers, there's no conversion going on. So C == F is false because 1+2i != 1.0. And I == F is false because 1.0 != 0xFFFFFFFFFFFFFFFFFFF = 75557863725914323419135.

There's no bug here and the spec covers this.

**Comment by griesemer** [comment]
PS: See https://golang.org/ref/spec#Constant_expressions for details.
