### ISSUE TITLE
net: JoinHostPort should not enclose non-IP literals in square brackets

### ISSUE THREAD

**Issue by mikioh** [golang/go#18059]
Looks like I forgot to add a test case. As per https://tools.ietf.org/html/rfc4007 (and considering https://tools.ietf.org/html/rfc6874 for the interoperability of the output of JoinHostPort), JoinHostPort should not enclose any non-IP literal in square brackets, and remove any scope zone identifier if necessary for avoiding ambiguity.

For example,
```
package main

import (
	"fmt"
	"net"
)

func main() {
	// /etc/hosts should have an entry mapping "locahost" to "::1".
	for _, host := range []string{"localhost", "::1", "::1%lo0", "localhost%lo0"} {
		fmt.Println(net.JoinHostPort(host, ""))
	}

	// Output:
	// localhost:
	// [::1]:
	// [::1%lo0]:
	// localhost: not [localhost%lo0]:
}
```

**Comment by kavirajk** [comment]
@mikioh Sorry this may sound stupid. How do we identify non-IP literal? both "::1%lo0", "localhost%lo0" seems to be invalid.

**Comment by kavirajk** [comment]
@mikioh got it. "localhost" is not a valid ipv6 address.
