### ISSUE TITLE
net/http: dubious code in TestServeMuxHandlerRedirects

### ISSUE THREAD

**Issue by dominikh** [golang/go#18068]
The test `TestServeMuxHandlerRedirects` in `net/http/serve_test.go` looks dubious. The `for tries > 0` loop will execute exactly once – `tries` starts at 1, gets decremented once at the bottom of the loop, and there is no path that would skip the decrement and execute the loop again. Similarly, the check `if tries < 0` can never be true – `tries` will either be its initial value of 1, or the once-decremented value 0.

/cc @bradfitz

**Comment by bradfitz** [comment]
@minux, looks like you wrote this code over three years ago in 716a409b9044850d0edf11318ec0eca63de57a93

You want to take a look?

**Comment by bradfitz** [comment]
Marking Go 1.9, but Go 1.8 is fine too if somebody wants to look into it.
