### ISSUE TITLE
crypto/aes: improve performance on ppc64le for aes

### ISSUE THREAD

**Issue by pfsmorigo** [golang/go#18076]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Using upstream.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="ppc64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_ppc64le"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

Add asm implementation for AES in order to make use of VMX cryptographic acceleration instructions for POWER8. There is a speed boost of over 11 times for AES using ppc64el.

**Comment by dr2chase** [comment]
There is a CL for this, or coming soon?

@laboger

**Comment by laboger** [comment]
My understanding is that a performance change like this could not go into Go 1.8 but would have to wait for Go 1.9.  Is that correct?

**Comment by pfsmorigo** [comment]
Assembly implementation uploaded to:
https://go-review.googlesource.com/#/c/32579

**Comment by bradfitz** [comment]
Yes, Go 1.8 is frozen for everything but critical bugs and maybe docs.
