### ISSUE TITLE
A Tour of Go map-literals.go

### ISSUE THREAD

**Issue by gmseed** [golang/go#18074]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.3
### What operating system and processor architecture are you using (`go env`)?
Win7

### What did you do?
Went to https://tour.golang.org/moretypes/20
and see a dangling ","

### What did you expect to see?

	var mLiteral = map[string]Vertex{
		"Bell Labs": Vertex{
			40.68433, -74.39967,
		},
		"Google": Vertex{
			37.42202, -122.08408,
		}}

### What did you see instead?

	var mLiteral = map[string]Vertex{
		"Bell Labs": Vertex{
			40.68433, -74.39967,
		},
		"Google": Vertex{
			37.42202, -122.08408,
		},
	}

**Comment by davecheney** [comment]
Hi @gmseed 

Both forms are value, however gofmt will prefer the "canonical" version that you see.

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
