### ISSUE TITLE
encoding/json: export func Valid([]byte) bool

### ISSUE THREAD

**Issue by sj26** [golang/go#18086]
I'm running go version go1.7.1 darwin/amd64 on macOS 10.12.1.

I'm trying to validate some a byte array is valid JSON so it can be marshalled literally like [RawMessage](https://golang.org/pkg/encoding/json/#RawMessage). The only way to do this at the moment is to create a [Decoder](https://golang.org/pkg/encoding/json/#Decoder) and fully decode the bytes causing many useless allocations, or write a custom scanner.

But there's a lovely, allocation-free function for scanning a byte array to see if it's valid JSON tucked away inside the encoding/json package ([checkValid](https://github.com/golang/go/blob/f7c351bdf6c8a70c90aac132194a9df390d002e0/src/encoding/json/scanner.go#L18-L32)), and used in several places within the package. It'd be great to expose this for general use as something like [`IsValid(data []byte) bool`](https://github.com/golang/go/commit/c746aaefb7e3d9b0c2c13efaa2a8945da491e4ae).

I proposed [this change](https://go-review.googlesource.com/#/c/29494/) a while back but I didn't understand the contribution process sorry! Is this the right place to file the issue @bradfitz?

**Comment by bradfitz** [comment]
@sj26, we just had a proposal review meeting today, so this'll be discussed at the next one, usually weekly.

I'll let others chime in here in the meantime.

**Comment by rsc** [comment]
By analogy with unicode/utf8's func Valid, it seems like this should be encoding/json's func Valid.

**Comment by rsc** [comment]
If you (or anyone else) would like to send a CL, please do, for Go 1.9.
