### ISSUE TITLE
Now and Parse set different location UTC objects in the time structure when the system local is UTC 

### ISSUE THREAD

**Issue by ggeorgiev** [golang/go#18087]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/george/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="/usr/local/bin/gcc-5"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/var/folders/f1/17sq245d7639797h5dmqrb4w0000gn/T/go-build700069154=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="/usr/local/bin/c++-5"
CGO_ENABLED="1"

### What did you do?
https://play.golang.org/p/FPuDXFSiRz

### What did you expect to see?
correct

### What did you see instead?
incorrect

Note that this is happening only on systems that have their local set to UTC - everywhere else in the world, this code will print 'correct'.

**Comment by bradfitz** [comment]
Go makes no promises about time.Time and ==. See 023556c07166be15a914d1f828d8c7b20a59a804 and 2c5bce1cfa242f27ffece3d30e8b851e3e923be2

But this was also changed for Go 1.8 in 5fbf35dc3fadd29785739fcec061d42157ea7861

**Comment by ggeorgiev** [comment]
It used to, and it still does in 1.7.3 which is the latest release. That is a significant change because not only time but every struct that has directly or indirectly `time` in it is not comparable anymore.

This is a lot of code that I have to review now - what about of the reset of the world. Thank you for fixing the actual issue, as well.

**Comment by bradfitz** [comment]
023556c and 2c5bce1 merely clarified the (lack of) promise that was already implicit and oft-mentioned on the mailing lists and other forums. It's just now explicitly recommended against.

**Comment by ggeorgiev** [comment]
I am not aware of any other language that the standard time type is not comparable. In your place, I would try harder to make/keep it as such.

Anyways, at least you should probably advertise this in a more aggressive way - say, add this to go vet or lint.
