### ISSUE TITLE
httptest.NewRequest causes http: Request.RequestURI can't be set in client requests

### ISSUE THREAD

**Issue by kalbasit** [golang/go#18082]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kalbasit/code"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build176110842=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
https://play.golang.org/p/_K2QegSjjL

### What did you expect to see?
The request is made, nothing printed. Same as using `http.NewRequest()`: https://play.golang.org/p/E06ae1K9kp

### What did you see instead?
```
2009/11/10 23:00:00 error doing the request: Get http://127.0.0.1:2?N5fUNeXF3q...OXvHWg: http: Request.RequestURI can't be set in client requests.
```

**Comment by bradfitz** [comment]
You're using the wrong NewRequest.

https://golang.org/pkg/net/http/#NewRequest is for outgoing client requests.
https://golang.org/pkg/net/http/httptest/#NewRequest is for incoming server requests.

**Comment by kalbasit** [comment]
@bradfitz sorry for the false alarm Brad, long day... Thank you for clarifying the docs.
