### ISSUE TITLE
x/tools/cmd/godoc: min-width instead of width

### ISSUE THREAD

**Issue by ajackson-cpi** [golang/go#18091]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
All

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://godoc.org/github.com/nicksnyder/go-i18n/goi18n
http://instantshare.virtivia.com:27080/4r28fpq4btj0.mov

package foo
/*
Doc Problem:
       Any GoDoc formatted section (which is indented in the code) that becomes very long has the problem of a UI treatment that produces a scrollbar if the line goes on for too long. What's worse is if the formatted section is over a page tall, then the user must navigate to the end of the section to scroll. 
*/

### What did you expect to see?
The format box should have expanded to use more available screen space on both sides of the hard-coded width. 

### What did you see instead?
A hard-coded width (100 chars?) is imposed and longer test needs left-right scroll. The left-right scrollbar could be off the end of the page if the section of code is long enough making the document experience that shows example code a painful experience. 

Suggestion: Widths for GoDoc should use min-width instead of width and allow growth.

**Comment by broady** [comment]
This isn't a problem for godoc itself, it's specific to godoc.org:
https://github.com/golang/gddo/issues/458
