### ISSUE TITLE
golang not work same as description in language reference information

### ISSUE THREAD

**Issue by quchunguang** [golang/go#18093]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7 and current.

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\repos\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

In Section `Selectors` of [language reference](https://golang.org/ref/spec),

```
For example, given the declarations:
...
var t T2     // with t.T0 != nil
var p *T2    // with p != nil and (*p).T0 != nil
var q Q = p
```

But When print out p and q, it's value is nil.

I do not certain if i can report this issus here. Because I think the golang works reasonable and it more likely the issue of language reference information of golang.

### What did you expect to see?

Fix the `Go Language Reference`.

### What did you see instead?

```
var p *T2    // with p != nil and (*p).T0 != nil
```

**Comment by ianlancetaylor** [comment]
When the spec says

    var t T2 // with t.T0 != nil

it means set `t` to a value of type `T2` such that `t.T0 != nil` is true.  It does not mean that the exact code that appears in the spec should be executed.

Closing because I don't think there is anything to change here.
