### ISSUE TITLE
malloc redeclares _MaxSmallSize in sizeclasses.go

### ISSUE THREAD

**Issue by mxplusb** [golang/go#18107]
### What version of Go are you using (`go version`)?

`go1.7.3 windows/amd64`

### What operating system and processor architecture are you using (`go env`)?

This is on Windows 10 Pro, Version	10.0.14393 Build 14393.

```shell
set GOARCH=amd64
set GOBIN=E:\Programming\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Programming\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

### What did you do?

Testing net.LookupNS [on my local machine](https://play.golang.org/p/LRjhWRjoxf). Executed like this: `C:/Go\bin\go.exe run C:/Users/Mike/.PyCharm2016.3/config/scratches/scratch_1.go`.

### What did you expect to see?

The program execute with `Protocol not available` error.

### What did you see instead?

```shell
# runtime
C:\Go\src\runtime\sizeclasses.go:7: _MaxSmallSize redeclared in this block
	previous declaration at C:\Go\src\runtime\malloc.go:124
C:\Go\src\runtime\sizeclasses.go:11: _NumSizeClasses redeclared in this block
	previous declaration at C:\Go\src\runtime\malloc.go:121
C:\Go\src\runtime\sizeclasses.go:12: _PageShift redeclared in this block
	previous declaration at C:\Go\src\runtime\malloc.go:107
C:\Go\src\runtime\sizeclasses.go:15: class_to_size redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:49
C:\Go\src\runtime\sizeclasses.go:16: class_to_allocnpages redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:50
C:\Go\src\runtime\sizeclasses.go:18: divMagic redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:225
C:\Go\src\runtime\sizeclasses.go:25: class_to_divmagic redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:51
C:\Go\src\runtime\sizeclasses.go:26: size_to_class8 redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:53
C:\Go\src\runtime\sizeclasses.go:27: size_to_class128 redeclared in this block
	previous declaration at C:\Go\src\runtime\msize.go:54
C:\Go\src\runtime\utf8.go:16: surrogateMin redeclared in this block
	previous declaration at C:\Go\src\runtime\rune.go:49
C:\Go\src\runtime\utf8.go:16: too many errors
```

I had errors relating to `rune.go` with `go1.7 windows/amd64`, so I uninstalled `go1.7` and installed `go1.7.3 windows/amd64`. This is a fresh installation, and the first Go code that was tested on it.

**Comment by davecheney** [comment]
It looks like something is corrupt in you go installation. Perhaps you have installed one version on top of another or perhaps you have the 386 version installed not the x64 version.

**Comment by bradfitz** [comment]
Yeah, looks like your GOROOT has a mix of Go versions on top of each other.

I'd just nuke it and start over. Let's take this to https://golang.org/wiki/Questions if problems persist.
