### ISSUE TITLE
doc: asm.html has no discussion of mips architectures

### ISSUE THREAD

**Issue by robpike** [golang/go#18105]
The sections at the end of the document provide architecture-specific details. There needs to be a section for the MIPS.

**Comment by bradfitz** [comment]
@vstefanovic, this is a requirement of a new architecture. Could you add some words to the documentation in the next week or three?

If not, let us know and maybe @cherrymui can do it.

**Comment by vstefanovic** [comment]
@bradfitz, ok, I guess I'll pull out a few sentences.

**Comment by bradfitz** [comment]
@vstefanovic, ping on this.

**Comment by vstefanovic** [comment]
Is this any worth?:

MIPS, MIPS64

GP registers are named R0 - R31, FP registers are F0 - F31.
R30 (ie. $fp) is reserved to point to g (goroutine). R23 ($s7) is used as a temporary register.
Most of pseudo-instructions are MOV(e). For example,
MOVW  R1, 8(R4) translates into sw $at, 8($a0);
MOVW  8(R4), R1 becomes lw $at, 8($a0);
MOVW  R1, R2 is move $v0, $at.
For mips, frame size $-4 for the TEXT means that linker should not save LR (R31, $ra). For mips64, it is $-8.
SP refers to the virtual stack pointer described above, for the hardware register, use R29.

Addressing modes:
  16(R1): The location at R1 plus 16.
  (R1): Alias for 0(R1).

**Comment by bradfitz** [comment]
Could you send a CL modifying the HTML?

**Comment by vstefanovic** [comment]
Sure.
