### ISSUE TITLE
os/user: add pure Go LookupGroup when cgo isn't available

### ISSUE THREAD

**Issue by kevinburke** [golang/go#18102]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

tip

Currently when you cross compile Go for a Unix target, calls to `user.LookupGroup` fail with `user: LookupGroup requires cgo`. Under the hood, `LookupGroup` calls `getgrnam_r` from C. 

Is there any interest in replacing this with a pure Go function? We'd probably need a clean rewrite, but here's some Go code that parses /etc/group, so it's at least possible. https://github.com/opencontainers/runc/blob/master/libcontainer/user/user.go#L141

The other consideration (reading through libc) is that apparently getgrnam checks other sources besides /etc/group:

> The getgrnam() function returns a pointer to a structure containing the broken-out fields of the record in the group database (e.g., the local group file /etc/group, NIS, and LDAP) that matches the group name name.

It might be trickier to replicate that other behavior.

**Comment by bradfitz** [comment]
Feel free to add /etc/group parsing code for Unix in the no-cgo case, but the default shouldn't change: when cgo is available, use cgo.

There's no way to write a pure Go function, since the configuration of libc's user/groups allows arbitrary shared libraries to be loaded to do the work.

**Comment by minux** [comment]
If we fix LookupGroup, I think it makes sense to fix all of os/user to be
like the net package: if /etc/nsswitch.conf allows, use a pure Go version
rather than cgo.

**Comment by bradfitz** [comment]
But DNS is common. LookupUser and LookGroup aren't, I imagine.

**Comment by minux** [comment]
Yeah, but parsing /etc/passwd and /etc/group is so much simpler than a DNS
client, so I think it's still worthwhile.

**Comment by kevinburke** [comment]
I've started working on this. Related to @minux's comment, should we respect the group setting in /etc/nsswitch.conf, if it exists? There's code to parse nsswitch.conf in net, but it's not currently exported.

**Comment by bradfitz** [comment]
The parsing should probably move to a new internal package if it's to be shared.

But I'm not sure how much it matters. What's an interesting case that parsing nsswitch.conf solves? It seems that it should either be simple (no cgo, only parsing /etc/group) or complete (cgo). Things in-between seem "meh" unless there's a common use case or common configuration that you're looking to address. What do you have in mind?

**Comment by kevinburke** [comment]
To be honest I just want to cross compile and find the GID for a groupname. But I figured if I was going to write a patch I could try to match libc, to a degree. I'll ignore it for now.
