### ISSUE TITLE
os.Remove doesn't return freed space back to the volume.

### ISSUE THREAD

**Issue by jaekim0908** [golang/go#18110]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)? Dockerized environment.
Based image: alpine 3.4
File system is tmpfs.

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

1. Create docker image from alpine 3.4 and go app.
2. Create large file in /tmp on container.
3. Check used disk space
4. Delete file and check used disk space again.
5. Repeat steps 2-4 multiple times.

Filesystem           1K-blocks      Used Available Use% Mounted on
none                  61896484  13219536  45509716  23% /
tmpfs                  1022788         0   1022788   0% /dev
tmpfs                  1022788         0   1022788   0% /sys/fs/cgroup
/dev/vda2             61896484  13219536  45509716  23% /etc/resolv.conf
/dev/vda2             61896484  13219536  45509716  23% /etc/hostname
/dev/vda2             61896484  13219536  45509716  23% /etc/hosts
shm                      65536         0     65536   0% /dev/shm
tmpfs                  1022788         0   1022788   0% /proc/kcore
tmpfs                  1022788         0   1022788   0% /proc/timer_list
tmpfs                  1022788         0   1022788   0% /proc/sched_debug

### What did you expect to see?
Used space for file is returned and used space stays the same.

### What did you see instead?
Used space keeps going up.

Code snippet:

func processFileWorker(jobs <-chan string) {
	for i := range jobs {
		fmt.Println("processing file start ...", i)
		time.Sleep(time.Second * 45)
		fmt.Println("processing file done ...", i)
		err := os.Remove(i)
		if err != nil {
			fmt.Println(err)
			continue
		}
		fmt.Println("deleted file ...", i)
	}
}

**Comment by cespare** [comment]
Please show code. It's possible you're holding onto file handles of files that you've deleted.

**Comment by minux** [comment]
Did you check the error from os.Remove?

If no error returns, then this can only be an OS bug because you should be
able to reproduce with rm(1) too.

**Comment by bradfitz** [comment]
This is almost certainly a mistake in your program. Go either makes the system call or it doesn't, and if it didn't, many of our tests would fail.

Let's bring this to https://golang.org/wiki/Questions for now until a concrete problem in Go has been identified.

**Comment by jaekim0908** [comment]
@cespare - I've updated the post with code snippet.
@minux - There was no error returned and when I checked the file it's gone but the used space is still not returned.

**Comment by minux** [comment]
It's possible that your program still holds the file open,
check /proc/$PID/fd to make sure it closes the files.
