### ISSUE TITLE
x/crypto/blake2b: supportSSE4 detection wrong, SIGILL on Atom D2700

### ISSUE THREAD

**Issue by stargrave** [golang/go#18113]
% go version
    go version go1.7.3 linux/amd64

    % go env
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/usr/lib/go"
    GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build635952482=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"

I am using Arch Linux x86-64 with 4.8.10-1-arch Linux kernel. I am using some code that runs blake2b, but it fails with the following error:

    SIGILL: illegal instruction
    PC=0x56d15a m=7

    goroutine 22 [running]:
    golang.org/x/crypto/blake2b.hashBlocksSSE4(0xc4200f2040, 0x0, 0xc4200f2058, 0x80, 0x80, 0xc420038be8)
            /tmp/.../aur-govpn/src/govpn-7.0/src/golang.org/x/crypto/blake2b/blake2b_amd64.s:145 +0x7a fp=0xc420038b60 sp=0xc420038b30

seems that it is trying to call SSE4.1-related assembler instruction, but host CPU does not support it.

    % cat /proc/cpuinfo
    processor       : 0
    vendor_id       : GenuineIntel
    cpu family      : 6
    model           : 54
    model name      : Intel(R) Atom(TM) CPU D2700   @ 2.13GHz
    stepping        : 1
    microcode       : 0x103
    cpu MHz         : 2127.966
    cache size      : 512 KB
    physical id     : 0
    siblings        : 4
    core id         : 0
    cpu cores       : 2
    apicid          : 0
    initial apicid  : 0
    fpu             : yes
    fpu_exception   : yes
    cpuid level     : 10
    wp              : yes
    flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl
    +nonstop_tsc aperfmperf eagerfpu pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat
    bugs            :
    bogomips        : 4257.26
    clflush size    : 64
    cache_alignment : 64
    address sizes   : 36 bits physical, 48 bits virtual
    [...]

supportSSE4 assembler code has the following line:

    SHRL $15, CX  // Bit 15 indicates SSE4 support

but Wikipedia says that SSE4.1 is indicated by 19-bit: https://en.wikipedia.org/wiki/SSE4#SSE4.1

I have never programmed in assembler, so possibly this is false assumption.

**Comment by agl** [comment]
Thanks for the report. Does simply changing the 15 to 19 (as in [this fix](https://go-review.googlesource.com/#/c/33830/)) work for you?

**Comment by stargrave** [comment]
Yes, 19-bit solves the problem (it correctly detects SSS4 absence and does not try to use that optimized instructions).

**Comment by stargrave** [comment]
Thank you!
