### ISSUE TITLE
autocert should trim trailing dots

### ISSUE THREAD

**Issue by jeffallen** [golang/go#18114]
### What did you do?

When accessing a server that gets certificates using autocert via a url like https://server.domain.com./ (note the trailing dot) you get an error from the ACME server. See letsencrypt/boulder#2367 for why. They propose that clients should resolve this situation by removing the trailing dot in the certificate request.

Thus, autocert should trim trailing dots.

**Comment by bradfitz** [comment]
Thanks. Seems easy enough.

/cc @x1ddos

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/33711 ... reviews welcome!

**Comment by x1ddos** [comment]
Yeah, sounds good. I'll create a change.

Although, hard to imagine someone typing a url with a trailing dot... Out of curiosity, does it happen regularly in your case? Never happened to me or visitors of domains that I own.

**Comment by x1ddos** [comment]
Ah, Brad already did.

**Comment by mikioh** [comment]
For the record, `absolute FQDN` that ends with a dot is not permitted for SNI of TLS. See https://tools.ietf.org/html/rfc6066#section-3 and #14404.

**Comment by bradfitz** [comment]
Oh, yeah? So which browser is sending it, @jeffallen, and why are we accepting it, @agl?

**Comment by jeffallen** [comment]
When I hacked autocert to nuke the dot, what I saw is that the URL bar had a dot on the end, but I still had a green padlock even though the SNI had no dot on the end. Don't recall if it was ff or chrome.

**Comment by agl** [comment]
We shouldn't accept this. Too late for the current cycle, but [this](https://go-review.googlesource.com/#/c/33904/) should do it in the future.
