### ISSUE TITLE
cmd/cgo: _cgoCheckPointer calling convention is suboptimal

### ISSUE THREAD

**Issue by mdempsky** [golang/go#18121]
_cgoCheckPointer is currently defined to take a ...interface{} parameter, but it always takes 0 or 1 arguments. And even in the 0 argument case, it would take less stack space to pass a nil interface{} value than a nil []interface{}.

Also, the []interface{} and the `true` argument used for pointers-to-fields currently escape to the heap. This could be addressed with the //go:noescape annotation.

/cc @ianlancetaylor

**Comment by bradfitz** [comment]
For putting bools into interface values: #17725

**Comment by egonelbre** [comment]
With https://go-review.googlesource.com/c/go/+/198081 it should be fixed, forgot to update the commit message.

**Comment by mdempsky** [comment]
@egonelbre Thanks. I didn't notice any //go:noescape changes in that CL. Does it turn out that's not needed?

**Comment by egonelbre** [comment]
AFAIU it that was addressed in https://github.com/golang/go/commit/03583675765933d4a5fb394cfa89fb41b274aaa7, however, I did not verify it.

**Comment by mdempsky** [comment]
@egonelbre Ah, right. I think this issue is fixed then. Thanks!
