### ISSUE TITLE
go/doc: ToHTML incorrectly marks up URLs containing :: in the filename component

### ISSUE THREAD

**Issue by alandonovan** [golang/go#18139]
See https://play.golang.org/p/763fuQgeJT
```
doc.ToHTML(os.Stdout, "before http://domain.com/x/y/z:b::c after", nil)
// got: before <a href="http://domain.com/x/y/z:b">http://domain.com/x/y/z:b</a>::c after</p>
// want: before <a href="http://domain.com/x/y/z:b">http://domain.com/x/y/z:b::c</a> after</p>
```

The urlRx regexp permits only a single colon in the file component, not a consecutive pair.

/cc @pjweinbgo

**Comment by bradfitz** [comment]
The regexp is kinda bogus.

It's not matching what its comments on the right suggest the author intended.

See https://play.golang.org/p/F56JrSSFO_
