### ISSUE TITLE
How to get the original Content-Length header when Content-Encoding is gzip 

### ISSUE THREAD

**Issue by myzhan** [golang/go#18132]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
```golang
package main

import (
	"net/http"
	"log"
)

func main() {
	resp, _ := http.Get("http://www.google.com")
	defer resp.Body.Close()
	log.Println(resp.ContentLength)
	log.Println(resp.Uncompressed)
}

```

### What did you expect to see?
I'm expecting the original Content-Length returned by www.google.com, then I know how many bytes have been transfered.

### What did you see instead?
resp.ContentLength == -1
resp.Uncompressed == true

**Comment by bradfitz** [comment]
If you actually need that, make your own `Transport` with `DisableCompression: true` and add your own 'Accept-Encoding: gzip` header and then Go won't help/interfere and it's on you to do it all by hand.

**Comment by myzhan** [comment]
Cool, Thx!
