### ISSUE TITLE
doc: mention concurrent map iteration and map write panic (throw) in release notes

### ISSUE THREAD

**Issue by bmhatfield** [golang/go#18137]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8beta1

### What operating system and processor architecture are you using (`go env`)?

linux, amd64

### What did you do?
I canary'd Go 1.8 on a program that has existed for 3 years, and been run on nearly every version of Go prior to 1.8. Nothing else changed other than switching to Go 1.8.

### What did you expect to see?
All the wonderful goodness in Go 1.8!

### What did you see instead?
```
fatal error: concurrent map iteration and map write

goroutine 67 [running]:
runtime.throw(0x812ca8, 0x26)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc443d32e18 sp=0xc443d32df8
runtime.mapiternext(0xc443d32f68)
	/usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc443d32ec8 sp=0xc443d32e18
github.com/crashlytics/gusset/caching-proxy.(*CachingProxy).Start.func1(0xc420012a00)
	/home/ubuntu/gopath-root/src/github.com/crashlytics/gusset/caching-proxy/caching-proxy.go:179 +0x2fa fp=0xc443d32fd8 sp=0xc443d32ec8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2184 +0x1 fp=0xc443d32fe0 sp=0xc443d32fd8
created by github.com/crashlytics/gusset/caching-proxy.(*CachingProxy).Start
	/home/ubuntu/gopath-root/src/github.com/crashlytics/gusset/caching-proxy/caching-proxy.go:187 +0x1a3
```

The code in question is:

```go
// A goroutine method to watch the cache size. Runs in the background,
// polling the cache's size and reporting statistics. This is to improve
// performance of cache-fills (where this used to live, synchronously) as
// well as ensure that the cache-size is properly reported even when no
// new requests are making it against the backend.
go func() {
	for true {
		time.Sleep(20 * time.Second)
		cacheSize := c.Cache.ItemCount()
		processing := len(c.processing)

		if processing > 0 {
			for k, v := range c.processing {
				extralog.Debugf("Processing request: %s, with %d waiting for a response", k, len(v))
			}
		}
		extralog.Debugf("Cache-watcher: Cache Size: %d, Processing: %d", cacheSize, processing)
		extralog.Gauge("cachingproxy.cache.size", cacheSize)
		extralog.Gauge("cachingproxy.cache.fill.processing", processing)
	}
}()
```

I believe I do see a potential for an unsynchronized map access here, and am going to review this 2-year old code (and other accesses to c.processing) more deeply. However, I am surprised that this is the first time I am seeing this.

Does go1.8 include additional concurrency protections or checks that are previously not in earlier versions? If so, it may be worth highlighting that people should re-check old programs for correctness in the release notes.

**Comment by bmhatfield** [comment]
This GH issue is dumb. This issue is definitely in my code.

That said, it is indeed true that this was not observed prior to Go1.8 - so it may be worth a note that incorrect programs related to concurrent map access are more likely to fail, if something really changed around this, and that folks should proceed with caution.

**Comment by bmhatfield** [comment]
After fixing the first one, I just hit another one, in code I don't control (directly). Yes, these are incorrect statements in my code. But if other folks are in a similar boat, this may prove to be a very bad experience if people are unprepared. Something seems much different about the way these accesses are checked.

I feel that this warrants a clear call-out in the release notes.

**Comment by randall77** [comment]
The fix in question is https://go-review.googlesource.com/c/24749/ which catches iter/write races.
This check is intended to catch real bugs that would otherwise cause random unattributable crashes.

I agree we should mention this in the release notes.

**Comment by davecheney** [comment]
Wasn't this check added in Go 1.7?

**Comment by bradfitz** [comment]
@davecheney, it got better. See the release notes that Keith wrote: https://golang.org/cl/33768

**Comment by deckarep** [comment]
Hey @davecheney and @bradfitz -- i know this feature was added back to Go's runtime quite a while ago...but I'm just wondering how the decision was made to panic applications when this case is hit rather than let it run and log?  For the record I typically agree that you never want such behavior in prod but it also seems like a pretty big deal to just crash in production scenarios?  Any thread on this you can point me to?  Thanks again!

**Comment by bradfitz** [comment]
See 50c5042 which references #13062. Panicking prevents people from wasting everybody's time with bogus Go bug reports. If it panics, it's very clear whose bug it is.

**Comment by deckarep** [comment]
I think this is a great change and illuminates the importance of mitigating data races for not just maps but all scenarios.

Two questions though:

1. Does similar logic exists for slices?
2. Is this regarded as a breaking change since the runtime now panics under these circumstances whereas before it didn't do anything?

**Comment by ianlancetaylor** [comment]
In general let's discuss things on the golang-dev mailing list, not on a closed issue.  Thanks.
