### ISSUE TITLE
proposal: make (http.CloseNotifier).CloseNotify() implementations close their channel instead of writing to it

### ISSUE THREAD

**Issue by vvekic** [golang/go#18134]
The point of this would be the ability to use (http.CloseNotifier).CloseNotify() to broadcast the event of closing the connection. Often do I need to read from this channel, only to close another one to broadcast this event to possibly many interested goroutines. It would be a lot simpler and clearer to use this single channel with all the goroutines that need to act in response to this event.

I may not be seeing a bigger picture here, so please enlighten me if I fail to recognize that the current implementation might be superior to what I'm proposing.

For reference, the HTTP implementation is [here](https://golang.org/src/net/http/server.go?h=CloseNotify#L1663), and HTTP2 [here](https://golang.org/src/net/http/h2_bundle.go?h=CloseNotify#L4701).

**Comment by bradfitz** [comment]
Sorry, that's a major API change we can't make. It would break programs causing their for{select{..}} loops to spin.
