### ISSUE TITLE
I want to know how golang will solve the memory fragmentation problem

### ISSUE THREAD

**Issue by 437305629** [golang/go#18158]
I want to know how golang will solve the memory fragmentation problem
**Do you have a plan?**

**Comment by minux** [comment]
Please ask questions on proper forums, not on the issue tracker,
which is for bug reports and proposals.

Please see https://golang.org/wiki/Questions.

**Comment by davecheney** [comment]
Go uses a slab like allocator that groups things of the same size together.
This reduces fragmentation to the point that we rarely have bug reports
about heavily fragmented heaps.

Do you have a specific bug report, or is this just an inquiry?
