### ISSUE TITLE
x/tools/cmd/godoc: comment listed before signature, not after

### ISSUE THREAD

**Issue by artyom** [golang/go#18150]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

1. Run local godoc server: `godoc -http=127.0.0.1:6060`
2. Navigate to any package documentation, i.e.: http://127.0.0.1:6060/pkg/net/http/#Server.ListenAndServe

#### What did you expect to see?

Function signature located between title and description/comment as here: https://golang.org/pkg/net/http/#Server.ListenAndServe

<img width="811" alt="screen shot 2016-12-01 at 23 57 40" src="https://cloud.githubusercontent.com/assets/68182/20812289/100879d8-b822-11e6-826d-6f3d9c8cb6dc.png">

#### What did you see instead?

Function signature listed after description.

<img width="809" alt="screen shot 2016-12-01 at 23 57 52" src="https://cloud.githubusercontent.com/assets/68182/20812376/5955b8a8-b822-11e6-9041-b28033bbd70e.png">

#### Does this issue reproduce with the latest release (go1.7.3)?

No

#### System details

```
go version go1.8beta1 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/tmp/go:/Users/artyom/go"
GORACE=""
GOROOT="/Users/artyom/Library/go"
GOTOOLDIR="/Users/artyom/Library/go/pkg/tool/darwin_amd64"
TERM="dumb"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lb/3rk8rqs53czgb4v35w_342xc0000gn/T/go-build900274628=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8beta1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.8beta1 X:framepointer
uname -v: Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
lldb --version: lldb-360.1.65
```

**Comment by bradfitz** [comment]
We only meant to do that for types, not for all things.

**Comment by bradfitz** [comment]
e.g. https://beta.golang.org/pkg/net/http/#Server.ListenAndServe

**Comment by broady** [comment]
Looks like it was intentional:
https://go-review.googlesource.com/#/c/33279/

#16278

**Comment by bradfitz** [comment]
Semi. We wanted it for that case and types at least. But not funcs.

**Comment by bradfitz** [comment]
Chris, you got this one?

**Comment by broady** [comment]
I was going to do it this afternoon but @griesemer beat me to it.
