### ISSUE TITLE
runtime: inconsistent filename separators between Unix/Windows with runtime.Caller

### ISSUE THREAD

**Issue by griesemer** [golang/go#18151]
While writing the test code for another issue (https://go-review.googlesource.com/#/c/33799/), I noticed that filenames defined via //line filename:line directives when returned from runtime.Caller always contained '/' (forward) slashes on Windows, even if the filename in the directive used '\\' (backward) slashes. Both these line directives:
```
//line c:\foo\bar.go:987
//line c:/foo/bar.go:987
```
return "c:/foo/bar.go" when followed by a runtime.Caller(0) call on Windows. On Unix, the filename reported matches the filename in the directive ( https://play.golang.org/p/7E_bDYfhy4 ).

There's an inconsistency somewhere that should be addressed.

**Comment by alexbrainman** [comment]
> I noticed that filenames defined via //line filename:line directives when returned from runtime.Caller always contained '/' (forward) slashes on Windows

This is purely historical.

All code written in Go always produced file paths delimited by \\ and happily accepted paths delimited by both \ and /. But paths read by runtime.Caller are generated by cmd/link, and cmd/link was written in C. Originally cmd/link code was for non-windows paths, like /a/b. Windows is quite OK with these paths, so some people just put drive letter in front, like c:/a/b, and that was that.

It is, probably, quite easy to change cmd/link to use \\. I just wonder who will be affected.

Alex

**Comment by griesemer** [comment]
@alexbrainman Thanks for the background. I'm not surprised that this is simply a historical "accident".

However, it does lead to surprising (and inconsistent) behavior across platforms, which I why I think we should address it at some point.

**Comment by odeke-em** [comment]
@griesemer duplicate of https://github.com/golang/go/issues/3335 that has existed for the last 4 years.

**Comment by griesemer** [comment]
@odeke-em Thanks for tracking this down! Closing as duplicate.

**Comment by minux** [comment]
I still think the right fix is to always use forward-slash '/'
consistently on all platforms.

**Comment by davecheney** [comment]
Seconded. This issue continues to crop up over and over because it is
always addressed in a piece meal fashion. Windows can work with forward
slashes, so we should just standardise on that everywhere.
