### ISSUE TITLE
type mistaken when passed by ...interface{} twice

### ISSUE THREAD

**Issue by l2dy** [golang/go#18164]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.7.4 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="..."
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_z/.../T/go-build...=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
https://play.golang.org/p/c1b8h7pHNT

### What did you expect to see?
Two "ok"s.

### What did you see instead?
`2009/11/10 23:00:00 ok`

**Comment by bradfitz** [comment]
This is not a bug.

For questions about Go, see https://golang.org/wiki/Questions.
