### ISSUE TITLE
runtime: mips32 soft float point support

### ISSUE THREAD

**Issue by juliandroid** [golang/go#18162]
I have built Golang by using the master branch and I have realized that there is no soft point support for the new mips32 target. That means the core like MIPS32 74Kc is not supported due to lack of FPU.

I have wrote an email to Vladimir Stefanovic, asking him to confirm the soft-float point support issue and his response was that in the near future there are no plans soft-point support to be implemented, but that might change later.

It would be great to have a ticket here to keep track the development of the issue and hopefully one day this issue to be resolved.

**Comment by cherrymui** [comment]
see also #14635.

**Comment by cherrymui** [comment]
There are softfloat code for ARM that we can reuse. What still need to be done is MIPS instruction decoding.

**Comment by vstefanovic** [comment]
@juliandroid
Yes, and after you quite a few other people asked about soft float support, so looks like the future has almost arrived.
If the code wasn't in feature freeze state, the patch would be submitted relatively soon.

**Comment by juliandroid** [comment]
@vstefanovic 
That was fast, the issue comes with twist :) Thanks for working on it!
Can you please leave the commit id (gerrit) here, once you complete the soft-float support? I'm willing to try it even before the merge in the master.

**Comment by vstefanovic** [comment]
@juliandroid 
Sure, I'll add a link.

**Comment by minux** [comment]
After discussion with @cherrymui on this issue, we think it's
probably a good idea to always enable soft float for mips and
mips64 (for both endianness) so that we don't need to add
a GOMIPS knob.

We can make _sfloat return immediately without interpreting
the following FPU instructions if the machine does have an
FPU.

The rationale is that most MIPS machines do not have an
FPU, this is unlike the ARM situation where if we do drop
ARMv6 support, almost all supported machine will have an
FPU.

Of course, we should base our final decision on both binary
size and execution time overhead for this.

If we decide to add a $GOMIPS knob to mirror the existing
$GOARM, we should also consider add support for the
legacy 32-bit MIPS instruction sets (i.e. MIPS I/II) so that
our 32-bit port also runs on Loongson 2.

**Comment by petar-jovanovic** [comment]
> The rationale is that most MIPS machines do not have an
> FPU

I have to disagree. Majority of modern MIPS boards do have FP
unit. There is a long list of legacy boards that indeed lack FPU
support, but relatively modern MIPS boards all have it.
$GOMIPS is important also to make a distinction between MIPS32r1/r2/r6 and
MIPS64r2/r6 (and MIPS3 as a legacy) that we plan to support through Go.

**Comment by aep** [comment]
@vstefanovic any change? need any help with this?

**Comment by vstefanovic** [comment]
@aep
Thanks, this will be submitted after go 1.8 is released, since it was too late for 1.8.

**Comment by elimisteve** [comment]
@vstefanovic I just heard of this via https://groups.google.com/forum/#!topic/golang-nuts/DT_P9UPKHgI . Adding soft floating point support for MIPS(32) would be fantastic! As soon as a patch or release is ready, I'm excited to use it. Think that might be soon?

**Comment by vstefanovic** [comment]
@elimisteve great to hear that. I'd like to prepare docker diffs first, then get back to the soft-float with a rebase and some double-checking; presumably it'll be uploaded in a few weeks.

**Comment by juliandroid** [comment]
I'm watching the calendar on the wall patiently too :+1:

**Comment by krasin** [comment]
@vstefanovic any updates? I would be willing to be a guinea pig for any work-in-progress patch you might have. The device I have is based on MT7628AN, mips32 little endian, if that matters.

**Comment by vstefanovic** [comment]
Hi @krasin, give me a few more days, then I'll upload the code to gerrit.

**Comment by krasin** [comment]
@vstefanovic sure things. As a workaround, I have compiled my kernel with FPU emulation flag, but that does not feel like the way to go, so a proper soft float support is highly appreciated.

**Comment by pqyptixa** [comment]
@vstefanovic
I cloned Go master and merged your patches, but still wasn't able to run the binary:
```
$ echo -e 'package main\nfunc main(){\n\tprintln("hello world!")\n}' > hello.go
$ env GOOS=linux GOARCH=mips GOMIPS=soft-float,mips32r2 ~/go-mips32-soft-float/bin/go build hello.go
scp hello my@mips:/tmp/
```

At mips system (openwrt):
```
# /tmp/hello 
Illegal instruction
# gdb /tmp/hello
[...]
(gdb) x/i $pc 
=> 0x4732c <runtime.check+48>:  mtc1    zero,$f0
```

Compiling with/without GOMIPS=soft-float,mips32r2 doesn't seem to make any difference:
```
$ env GOOS=linux GOARCH=mips GOMIPS=soft-float,mips32r2 ~/go-mips32-soft-float/bin/go build hello.go
dacf38f5eb593a1e145f47de0da08c4e  hello
$ rm hello
$ env GOOS=linux GOARCH=mips ~/go-mips32-soft-float/bin/go build hello.go
$ md5sum hello
dacf38f5eb593a1e145f47de0da08c4e  hello
$ file hello
hello: ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, not stripped
```
However, the go compiler is parsing the GOMIPS env var:
```
$ env GOOS=linux GOARCH=mips GOMIPS=blah ~/go-mips32-soft-float/bin/go build hello.go
# command-line-arguments
[...] Invalid GOMIPS value. Valid values are: soft-float/hard-float, mips32/mips32r2.
If more than one, separate them with comma. E.g. GOMIPS=soft-float,mips32.
```

Am I doing something wrong, or missing something? Are these patches not yet complete?

BTW, thanks a lot for your work!

**Comment by vstefanovic** [comment]
@pqyptixa
The patches are complete. Maybe you're missing '-a', ie. 'go build -a', if you have previously built something as hard-float.
The build system doesn't do clean build when you change GOMIPS (or GOARM, GO386) value, we might want to improve that, but at the moment 'go build -a' is the safe way.

**Comment by pqyptixa** [comment]
@vstefanovic 
That was it, I needed to use -a ! :D
Thank you!

**Comment by juliandroid** [comment]
I have forgotten to mention that I also managed to run a program on a mips32 device, but I had some merge issues, so I would wait for official merge and then try again. For now I'm sticking with go 1.8 and kernel level FPU emulation.

@vstefanovic 
I'm following you on Gerrit and I'm wondering are there any blocking issues with the soft-float point? It seems that they have forgotten your commits? :)

**Comment by pqyptixa** [comment]
My "recipe" to get the mips32r2/soft-float code working is:

    git clone https://go.googlesource.com/go go-mips32
    cd go-mips32
    git reset --hard d343478295f8635e60014fa9481ccea04b6c53a8
    git pull https://go.googlesource.com/go refs/changes/54/37954/2
    git pull https://go.googlesource.com/go refs/changes/58/37958/1
    GOROOT_BOOTSTRAP=/usr/local/go ./make.bash

(I could be doing something wrongly or redundant with the merge process. I guess if you have any issues, you could be missing some more patches or something)
Then you can run Go/MIPS as I did above:

    GOOS=linux GOARCH=mips GOMIPS=mips32r2,soft-float ./bin/go build -a -ldflags '-s -w' program.go

But, yeah, I was wondering if these patches had just been abandoned, and was going to ask the same question... From the discussion of the patches (see https://go-review.googlesource.com/c/37954/, below "Messages"), it seems like the Go maintainers (@ianlancetaylor, @bradfitz) had some issues with using env vars to pass parameters, and wanted to remove them, but things didn't move from that (https://groups.google.com/forum/#!topic/golang-dev/utpaIeO9lx4)

**Comment by juliandroid** [comment]
Another possibility is the later news "Imagination to Double-Down on GPU Business, MIPS and Ensigma to Be Sold" :/

**Comment by petar-jovanovic** [comment]
Go is being actively developed and improved for MIPS32/MIPS64. No slowdown.

**Comment by ematsu** [comment]
@vstefanovic
I have back ported your patches to go1.8.1 and seems working perfectly. But I would want to wait official merge before (if possible) go1.9 source code freeze.

For me it's difficult to support this issue from technical perspective, but if there is anything that I could do, please let us know. I really want to move this issue to forward.

**Comment by vstefanovic** [comment]
@pqyptixa, @juliandroid, @ematsu thanks for keeping this thread live. Yes, these patches depend on sorting out the GOMIPS/GOSOFTFLOAT environment variable(s).

I've updated the code according to Keith's comments on that golang-dev thread, in case you want to check them, they're not using GOMIPS anymore, but GOSOFTFLOAT:

`GOSOFTFLOAT=1 go build -a ...`

I too hope that soft-float gets into 1.9 release.

**Comment by ematsu** [comment]
@vstefanovic

I have checked your new patchset and updated my back port patch to 1.8.3. It seems working fine.
I really hope this patchset will be merged to master branch.

Many thanks for your great work, @vstefanovic

**Comment by aclements** [comment]
Sadly, it's too late in the Go 1.9 cycle to apply these. :(

I'm moving this to Go1.10Early so we focus on getting these in ASAP when the tree opens.

Ideally, I'd like to get these fully reviewed now so we can just hit submit when the tree opens. Assigning to @cherrymui to see this through.

**Comment by juliandroid** [comment]
That so sad and this is delayed for bikeshedding (no reason) :(

**Comment by bradfitz** [comment]
It may seem like bikeshedding to you, but it's something we can't change later so it's important to get right. Also, had the conversation happened earlier in the cycle and/or quicker we could've reached a design consensus quicker. Alas, we did not. Let's do this earlier next time.

**Comment by aclements** [comment]
> That so sad and this is delayed for bikeshedding (no reason) :(

There was some bikeshedding delay, certainly, but the patches that actually implement the soft-float functionality are still under review. The knob wasn't the only thing holding this up. I've made sure the CLs all have a reviewer (and I'm taking a skim myself).

**Comment by pqyptixa** [comment]
@ematsu is your backport public?

**Comment by ematsu** [comment]
@pqyptixa
Not yet. I want to wait for all the reviews at gerrit, and once get merged, update my patches and want to share it. Maybe for both 1.8 branch and 1.9 branch.
Sorry for that, but currently they are still under reviews and want to distribute well-reviewed codes.

**Comment by pqyptixa** [comment]
@ematsu OK, thank you.

**Comment by ematsu** [comment]
@vstefanovic 

One question. When using "math.Sqrt", I need to specify "asmflags='-D GOMIPS_softloat'" together with "-a" to build softloat binary, even if I use go binary bootstrapped with "GOMIPS=softfloat".  

With the same go binary, if I don't use "math.Sqrt", I only need to specify GOOS and GOARCH to build softfloat binary, no "GOMIPS" required because I thought it was bootstrapped with "GOMIPS=softfloat".

I just thought if bootstrapped with softfloat enabled, generated "math.a" is also expected to be softfloat enabled (assembled with "GOMIPS_softfloat"). Then no need to build with "-a" I think...

Sorry, I'm not sure I should post this question to golang-dev or here. so if this is not the right place, my apologize.

Rgds.

**Comment by vstefanovic** [comment]
@ematsu, thanks, you've discovered a bug, I was passing GOMIPS_SOFTFLOAT instead of GOMIPS_softfloat to the assembler.
So you don't need to pass the flag manually to the assembler (now that it's fixed), that would be very user-unfriendly.

**Comment by ematsu** [comment]
@vstefanovic, glad to hear that. Now I don't have to pass the flag manually. 
BTW, code reviews are still undergoing ? or just waiting for  new tree open ? if reviews are almost completed, I would share my go1.8.3 backport patch. What is the current status ?

**Comment by bradfitz** [comment]
The tree will open in August.

**Comment by juliandroid** [comment]
@ematsu: that will be great!
I would try this one, if you publish it somewhere (or instructions/how-to) :)

**Comment by ematsu** [comment]
Release branch for go1.9 was now created, and I feel the code review for mips32 softfloat is getting close to the final stage. (although, not yet merged to master branch). so decided to share my backport patchset to 1.8.3. 

@juliandroid : 
Please download from [here](https://gist.github.com/ematsu/0410ef110e1e9ad9733b9f8dccfe729b/archive/73f8f580bb6fb07c1d12bf60008df9c66c9d0e46.zip) and try it. I checked simple functions and seems working fine. Hope it helps.

-- 
eiji

**Comment by Nick-Hopps** [comment]
How to use go1.8.3sf.diff?

**Comment by rdslw** [comment]
I've read the discussion here, but wasn't able to conclude which go version will have mips soft float.
Anybody can confirm me this?

**Comment by ALTree** [comment]
@rdslw the relevant changes seem to be here:

https://go-review.googlesource.com/q/soft+float

apparently, they were reviewed but they're not yet merged. If someone pushes the button quickly, they'll be included in go1.10. Otherwise, they won't.

**Comment by rdslw** [comment]
Thanks @ALTree . Some of them are quite recent, so I hope they will make it.

Do I get correct that alternative to this, would be having kernel fpu emulation enabled? /my firmware has linux kernel without fpu emulation currently/

**Comment by ALTree** [comment]
> alternative to this, would be having kernel fpu emulation enabled

I believe this is correct. Please see:

https://github.com/golang/go/wiki/MinimumRequirements#mips-big-endian-and-mipsle-little-endian

> **mips (big endian) and mipsle (little endian)**
> MIPS32r1, with FPU or kernel FPU emulation

**Comment by petar-jovanovic** [comment]
This has been planned for 1.10, since it missed 1.9 for some reasons. The issue had Go1.10Early milestone.
Any update on including this @cherrymui  @bradfitz ?

**Comment by ALTree** [comment]
@petar-jovanovic I pinged them yesterday asking for the status and Cherry said they were all reviewed except this one: https://go-review.googlesource.com/c/go/+/37954. So as soon as that one is also `+2`ed reviewers will decide if they can be all included in 1.10.

**Comment by bradfitz** [comment]
I'm bumping this back to Go 1.10 because it might've been moved to Go1.11 along with a bunch of other bugs en masse.

I'd prefer this go into Go 1.10 if @rsc doesn't find it too invasive.

**Comment by juliandroid** [comment]
I would greatly appreciate if this ends up in Go 1.10 as @aclements pledged to try his best last time :)

@bradfitz Thanks for pushing this into 1.10 :+1:

**Comment by aclements** [comment]
This is fixed as of 6be1c09. Thanks! I opened #22966 for creating a builder to test this configuration.

**Comment by dtodor** [comment]
We have a problem with the Go compiler on a MIPS target without the CONFIG_MIPS_FPU_EMULATOR being enabled. I thought in such case the soft-float support in go1.10RC1 would be sufficient but unfortunately be cannot build any runnable Go programs. The FPU configuration of the target is:
CONFIG_MIPS_FPU_EMULATOR=n
CONFIG_CPU_R4K_FPU=y

Any ideas?

**Comment by davecheney** [comment]
@dtodor. Please open a new issue including how you built Go or the target binary.

**Comment by ALTree** [comment]
@wengerxin No, apparently. Softfloat for mips64 is issue #14635, which is still open.

**Comment by cherrymui** [comment]
@wengerxin Soft float on MIPS64 are not officially supported. However, the functionality are all there. You are welcomed to try it, by setting `GO_GCFLAGS="-d softfloat"` on bootstrap and setting `-gcflags=all="-d softfloat"` on `go build`. (This is not tested though.)

**Comment by wengerxin** [comment]
I consulted the mips32 modification and modified the flowing files to shield the float instructions:
src/runtime/cgo/asm_mips64x.s
/src/runtime/cgo/gcc_mips64x.S

[0001-add-mips64-soft-float.zip](https://github.com/golang/go/files/1770316/0001-add-mips64-soft-float.zip)
 Modifications are in the attached file, but I don't know whether these modifications are right?

**Comment by milanknezevic** [comment]
These modifications are needed only if you need CGO (you can disable it with CGO_ENABLED=0). But if you need it, you are on the right track. Are you planning to send the patch for review?
Just to mention, in a week or two we plan to do modifications which will enable softfloat on MIPS64.

**Comment by wengerxin** [comment]
@milanknezevic , Thank you for your answer. Yes, I need CGO to compile docker.
I'm not planning to send the patch for review, I would wait for official merge and then try again.
