### ISSUE TITLE
Strange behaviour of strings.TrimLeft

### ISSUE THREAD

**Issue by pikoscielniak** [golang/go#18160]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.3 

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
I executed following test:
```
import (
	"testing"
	"strings"
)

func TestTrimLeft(t *testing.T) {
	trimed := strings.TrimLeft("record:edocument", "record:")

	if trimed != "edocument" {
		t.Fatalf("Expected 'edocument' got '%s' ", trimed)
	}
}
```

### What did you expect to see?
This test failed. I wouldn't expect this. Could someone explain this to me?

### What did you see instead?
I got following output from this test:
```
Expected 'edocument' got 'ument' 
```

**Comment by myitcv** [comment]
@pikoscielniak you want [`TrimPrefix`](https://godoc.org/strings#TrimPrefix) and not `TrimLeft`

Please also consider asking questions like this in the go-nuts mailing list [or other help forums](https://golang.org/help/) as a first port of call. If the behaviour you are seeing is then confirmed as a bug/issue it can easily be re-raised here in the issue tracker.

**Comment by pikoscielniak** [comment]
Thanks a lot. This is what I was looking for.
