### ISSUE TITLE
net: fix comment on IPv4bcast

### ISSUE THREAD

**Issue by mikioh** [golang/go#18176]
The comment says `IPv4bcast = IPv4(255, 255, 255, 255) // broadcast`, but it's a limited broadcast address and should be distinguished from directed broadcast addresses.

**Comment by bradfitz** [comment]
Just send a CL if there's a one-word fix.

But I don't think anything is needed here. If people are looking for 255.255.255.255, they found it. Otherwise they didn't.

**Comment by bradfitz** [comment]
Not a regression from any Go release, so removing the Go 1.8 label. Feel free to send a CL if you have something succinct and okay for end users and not networking experts.
