### ISSUE TITLE
net: Pipe does not properly implement the Conn interface

### ISSUE THREAD

**Issue by dsnet** [golang/go#18170]
The in-memory `net.Conn` implementations returned by `net.Pipe` are just thin wrappers over `io.Pipe` and do not properly implement `net.Conn` due to lack of `SetDeadline` support. Should `net.Pipe` implement deadline support?

\cc @bradfitz

**Comment by bradfitz** [comment]
I suppose they could. For testing, I assume?

**Comment by flyingmutant** [comment]
Is there interest in a CL implementing deadline support (to make `net.Pipe` more suitable for testing, yes)?

**Comment by bradfitz** [comment]
@flyingmutant, yes, seems like @dsnet and I think it could. I haven't heard objections from others.

@rsc, @ianlancetaylor?

**Comment by dsnet** [comment]
I've adjusted enough `net.Conn` implementations to respect deadlines, that doing the same here would be fairly straightforward. I just didn't want to add complexity to `net.Pipe` if it isn't really being used.

**Comment by flyingmutant** [comment]
Does https://github.com/flyingmutant/go/commit/f63b38c8b35c4cfc7f1050d6fb13b18b7d3778e7 (untested) look like a reasonable direction and complexity/performance tradeoff?

**Comment by bradfitz** [comment]
@flyingmutant, sorry, we can only look at and review code on Gerrit. See https://golang.org/doc/contribute.html

**Comment by bradfitz** [comment]
Also, be sure your implementation passes https://godoc.org/golang.org/x/net/nettest

**Comment by dsnet** [comment]
A brief glance at your implemention seems to show that deadlines are not extendable, refreshable. There also seems to allow for possible raciness when deadlines occur on a read or write call since the buffers are still accessed by the opFn.

**Comment by flyingmutant** [comment]
@dsnet good point about possible race, thanks.
Am I right that `SetDeadline` calls should only be made between `Read`/`Write` calls? If so, I don't quite understand what do you mean by "not extendable, refreshable".

**Comment by bradfitz** [comment]
@flyingmutant, we spent some time polishing the docs on the Conn interface during Go 1.8.  See if this addresses your questions:

https://beta.golang.org/pkg/net/#Conn

If not, we should fix the docs.

**Comment by flyingmutant** [comment]
@bradfitz thanks! It seems that it should be possible to `SetDeadline` concurrently with `Read`/`Write` calls (`and pending` bit in the new docs), and my naive implementation certainly does not allow that.

**Comment by flyingmutant** [comment]
I've got a working implementation which passes nettest (with `-race`). However, it required modifications to `io.Pipe`: support for interrupting I/O much like `Close` does, but only for 1 operation. Is this an acceptable API addition, and is there interest in this style of implementation?

**Comment by nightlyone** [comment]
Instead of making net.Pipe more complex, adding a decent abstraction of http://man7.org/linux/man-pages/man2/socketpair.2.html and using that might be more rewarding in terms of realistic test scenarios. That also allows way more settings enabling even more test scenarios.
