### ISSUE TITLE
Failing to compile Go 1.7.4 on macOS

### ISSUE THREAD

**Issue by mitchellh** [golang/go#18188]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Not passing tests, but attempting to compile go1.7.4

`$GOBOOTSTRAP/bin/go version` is:

    go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

macOS 10.12.1

```
src → go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mitchellh/code/go"
GORACE=""
GOROOT="/Users/mitchellh/code/3rdparty/go"
GOTOOLDIR="/Users/mitchellh/code/3rdparty/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3q/c37yygcs4vl7cvzq3k3wdnyr0000gn/T/go-build018200950=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

1. Clone Go Git repo
2. `git checkout go1.7.4`
3. `cd src; ./all.bash`

### What did you expect to see?

Successful completion

### What did you see instead?

When testing system packages, this fails every time:

```
--- FAIL: TestLoadFixed (0.00s)
	time_test.go:943: Now().In(loc).Zone() = "-01", -3600, want "GMT+1", -3600
FAIL
FAIL	time	2.422s
```

**I've reproduced this on all 3 macOS machines I have: two MacBook Airs and one iMac**

I feel like I'm probably doing something wrong but I can't figure it out...

**Comment by mitchellh** [comment]
Looks like this is fixed on master (go1.8) and is just a macOS 10.12 issue on <= go1.7. I'm not sure if the fix should be backported for a clean compile. I'll leave this issue open but if its working as intended (only 1.8 should compile+test cleanly) then I accept that.

**Comment by bradfitz** [comment]
Dup of #17276.
