### ISSUE TITLE
unicode: FoldCategory and FoldScript incorrectly defined

### ISSUE THREAD

**Issue by IsaacDunlap** [golang/go#18186]
In Go version 1.7.3, the unicode package provides 2 maps: FoldCategory and FoldScript. FoldCategory is only supposed to map category names to tables of code points, but includes script names ("Common", "Greek", "Inherited"). By contrast, although FoldScript is supposed to map script names to tables of code points, the 3 script names ("Common", "Greek", "Inherited") are missing and FoldScript is an empty map.

This bug could be fixed by instead defining Fold Category and FoldScript thus:

`var FoldCategory = map[string]*RangeTable{
	"L":  foldL,
	"Ll": foldLl,
	"Lt": foldLt,
	"Lu": foldLu,
	"M":  foldM,
	"Mn": foldMn,
}`

`var FoldScript = map[string]*RangeTable{
	"Common":    foldCommon,
	"Greek":     foldGreek,
	"Inherited": foldInherited,
}`

This much better fits what the user of unicode expects when reading the descriptions of FoldCategory and FoldScript (as well as better matching what the names of the variables imply).

**Comment by robpike** [comment]
This is outside my bailiwick. cc @mpvl @rsc

**Comment by rsc** [comment]
It looks like this is a bug in maketables. I believe @mpvl is away. I'll try to take a look this week.

**Comment by bradfitz** [comment]
@mpvl, could you look at this if you're back?

**Comment by bradfitz** [comment]
Ping @mpvl.

**Comment by bradfitz** [comment]
Ping @mpvl.

**Comment by rsc** [comment]
Seems like @mpvl is away (not sure). I'll take care of this. I thought the tables were now generated from something in x/text, but unicode/maketables.go is still in the main distribution and editing and rerunning it has the desired effect, so good enough for me.
