### ISSUE TITLE
net/http/httputil: ReverseProxyHeader doesn't preserve header key case

### ISSUE THREAD

**Issue by JasonGLYao** [golang/go#18196]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
Windows 7 & Intel Core I5(x64)

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

1. A Client program written in C# which will post HTTP request to the server side with additional customized header key(eg: HostName)
2. A proxy written in Go which acting the role of proxy ,after this action , the header key will be change to canonicalMIME style(Hostname).
3. Server side program will try to fetch the header info, while use the key(HostName)to get its value, empty value got.
4. How to process the Standard Key word of "TE" in GoLang?

### What did you expect to see?
 HostName -->HostName  in httprequest header while using the ReverseProxy functions

/*proxy := httputil.NewSingleHostReverseProxy(remote)
	proxy.ServeHTTP(w, r)*/ 

### What did you see instead?
HostName -->Hostname  in httprequest header while using the ReverseProxy functions

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

**Comment by bradfitz** [comment]
Sorry, HTTP headers are case insensitive.

Your backend sounds buggy.

I'm not sure this is worth "fixing" in Go because it would be very invasive at many levels.

**Comment by JasonGLYao** [comment]
Thanks for reply.

**Comment by bradfitz** [comment]
I thought about this more and still think the change would be way too invasive to be worth supporting broken application. Considering that http2 doesn't preserve the case of headers either, and http2 is becoming increasingly prevalent, people will need to fix their buggy assumptions sooner or later anyway.

Sorry, closing.
