### ISSUE TITLE
x/sys/unix: doesn't build with GOARCH=mips

### ISSUE THREAD

**Issue by ncw** [golang/go#18192]
I noticed this while attempting to build rclone with go1.8beta and mips

### What version of Go are you using (`go version`)?

go version devel +41908a5 Thu Dec 1 02:54:21 2016 +0000 linux/amd64

I'm using ca83bd2cb9abb47839b50eb4da612f00158f5870 of the x/sys repo (2 December 2016)

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ncw/go"
GORACE=""
GOROOT="/opt/go/go1.8"
GOTOOLDIR="/opt/go/go1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build407009917=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

```
$ GOARCH=mips GOOS=linux go install golang.org/x/sys/unix/
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
../../../golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
../../../golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
../../../golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
```

Same for `mipsle`

### What did you expect to see?

It to compile

### What did you see instead?

Error messages about undefined symbols

**Comment by bradfitz** [comment]
@vstefanovic, this is important for Go 1.8. Do you have time to work on it?

**Comment by vstefanovic** [comment]
Ok, here it is - https://go-review.googlesource.com/#/c/33952/

**Comment by bradfitz** [comment]
Fixed by https://github.com/golang/sys/commit/478fcf54317e52ab69f40bb4c7a1520288d7f7ea

**Comment by ncw** [comment]
Tested and compiling - thank you very much :-)
