### ISSUE TITLE
Could change checkValid to CheckValid in encoding/json?

### ISSUE THREAD

**Issue by AnotherGoogleFan** [golang/go#18195]
Sometimes in our project we just need to receive json data,  check valid and send it to other part such as nsq. We do not need to unmarshal it at all. We found a checkValid method but we could not use it. May it be changed to CheckValid so that we can use it?

Besides, we know that we can check valid by other method such as 
   if _, err := json.Unmarshal(....); err != nil{
        // do the things
    }
but that might lead to performance degradation, and we will deal a very huge number of this so performance is very important.

**Comment by mvdan** [comment]
dup of #18086

**Comment by minux** [comment]
Closing as dup.
