### ISSUE TITLE
how to use gomobile to manipulate database for both android and ios

### ISSUE THREAD

**Issue by jacentsao** [golang/go#18194]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/Work/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w4/75xgx41n2bb7mm3m0dxbp0d40000gn/T/go-build938436427=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
here is my test demo.

package test

import (
	"database/sql"
	"fmt"
	_ "github.com/mattn/go-sqlite3"
	"log"
	"os"
)

func Test() {
	os.Remove("./foo.db")

	db, err := sql.Open("sqlite3", "./foo.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	sqlStmt := `
	create table foo (id integer not null primary key, name text);
	delete from foo;
	`
	_, err = db.Exec(sqlStmt)
	if err != nil {
		log.Printf("%q: %s\n", err, sqlStmt)
		return
	}

	tx, err := db.Begin()
	if err != nil {
		log.Fatal(err)
	}
	stmt, err := tx.Prepare("insert into foo(id, name) values(?, ?)")
	if err != nil {
		log.Fatal(err)
	}
	defer stmt.Close()
	for i := 0; i < 100; i++ {
		_, err = stmt.Exec(i, fmt.Sprintf("こんにちわ世界%03d", i))
		if err != nil {
			log.Fatal(err)
		}
	}
	tx.Commit()

	rows, err := db.Query("select id, name from foo")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var name string
		err = rows.Scan(&id, &name)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, name)
	}
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}

	stmt, err = db.Prepare("select name from foo where id = ?")
	if err != nil {
		log.Fatal(err)
	}
	defer stmt.Close()
	var name string
	err = stmt.QueryRow("3").Scan(&name)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(name)

	_, err = db.Exec("delete from foo")
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.Exec("insert into foo(id, name) values(1, 'foo'), (2, 'bar'), (3, 'baz')")
	if err != nil {
		log.Fatal(err)
	}

	rows, err = db.Query("select id, name from foo")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var name string
		err = rows.Scan(&id, &name)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, name)
	}
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}
}

### What did you expect to see?

* I want to use gomobile and manipulate the database in our andriod and ios app

### What did you see instead?

* I/GoLog: "unable to open database file": 
                                                     	create table foo (id integer not null primary key, name text);
                                                     	delete from foo;

**Comment by sywesk** [comment]
Hello,

Just my 2 cents about this issue : I really think you have file permissions issues with your app. See this stackoverflow post : http://stackoverflow.com/questions/33815541/golang-gomobile-app-cannot-generate-files 

I don't think it is related to this project by itself. Go works as it should, and the behavior seems, at least to me, expected.

**Comment by jacentsao** [comment]
@sywesk Thanks for your comment, i use the "./" stand for the app external directory and it will under the "data/data/packagename", I think no permission is needed.

**Comment by sywesk** [comment]
Golang sqlite is calling the native library. From their home page (readme)
> go-sqlite3 is cgo package

From their source code : 
```go
ErrCantOpen   = ErrNo(14) /* Unable to open the database file */
```

So, after this bit of research, i can now even state that this problem is not even related to the go language / standard library. Try to asking on stackoverflow for help.

**Comment by jacentsao** [comment]
@sywesk Thanks for your kindly reply . i have already seek for help both github and stackoverflow. Thanks

**Comment by quentinmit** [comment]
I'm closing this bug because it doesn't sound like there's anything wrong with x/mobile; unfortunately I don't know how you are supposed to find a writeable data directory on Android, but it seems likely that you're just writing to the wrong directory.

**Comment by jacentsao** [comment]
@quentinmit We now have a golang project using beego, and we build a exec file and run it in android device, using http to communicate with the exec server by connecting to localhost. the writing directory of our database is the same to code below "./", so i don't think the directory is wrong. Only change is change the compile method, so that we can build our current project for both android and ios (with gomobile)
