### ISSUE TITLE
build: error when using go installed from tarball for ppc64le due to build tags in runtime/*lfs* files

### ISSUE THREAD

**Issue by laboger** [golang/go#18197]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8beta1 linux/ppc64le

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 ppc64le

### What did you do?
Tried to install go from ppc64le tarball for go1.8beta1 from location described in #17193.

### What did you expect to see?
Correct install with usable go.

### What did you see instead?
Errors when trying to build simple hello.go program after installing.

which go
/usr/local/go/bin/go

go build hello.go 
// # runtime
/usr/local/go/src/runtime/lfstack_linux_ppc64x.go:20: addrBits redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:29
/usr/local/go/src/runtime/lfstack_linux_ppc64x.go:21: cntBits redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:34
/usr/local/go/src/runtime/lfstack_linux_ppc64x.go:24: lfstackPack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:37
/usr/local/go/src/runtime/lfstack_linux_ppc64x.go:28: lfstackUnpack redeclared in this block
	previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:41
/usr/local/go/src/runtime/os_linux.go:27: _FUTEX_WAIT redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:22
/usr/local/go/src/runtime/os_linux.go:28: _FUTEX_WAKE redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:23
/usr/local/go/src/runtime/os_linux.go:36: futexsleep redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:31
/usr/local/go/src/runtime/os_linux.go:67: futexwakeup redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:62
/usr/local/go/src/runtime/os_linux.go:83: getproccount redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:78
/usr/local/go/src/runtime/os_linux.go:109: _CLONE_VM redeclared in this block
	previous declaration at /usr/local/go/src/runtime/os1_linux.go:104
/usr/local/go/src/runtime/os_linux.go:109: too many errors

Looks like the tags are wrong in the lfstack files in runtime.  Seems like this should fail on other platforms too, not just ppc64le, based on how the build tags are set in these files?  There are also duplicate symbols in the os1 and os2 files but there are no build tags in the os files.

**Comment by laboger** [comment]
Sorry my mistake here somewhere.  Maybe I didn't clear out what was there before.  Tried again on a few other systems and it installed OK and built hello.go without error.

**Comment by minux** [comment]
Those files are using explicit build tags (//+build).
