### ISSUE TITLE
doc: installation docs don't list all OS architectures

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18207]
https://beta.golang.org/doc/install says:

Operating System: "Linux 2.6.23 or later with glibc" .... Architectures: "amd64, 386, arm"

That's missing a bunch.

Also, for FreeBSD, it only lists amd64, but 386 and arm are also supported.

/cc @minux

**Comment by minux** [comment]
I think that list is for ports with binary distributions, and
golang.org/doc/install/source lists all supported platforms.

I think we do need to add linux/ppc64le and linux/s390x
to the list though. I don't know why we omitted freebsd/386
from the list.

But we need to first determine whether we want to ship
binary distribution for linux/mips and others?

**Comment by bradfitz** [comment]
> I think that list is for ports with binary distributions

I see.

> But we need to first determine whether we want to ship
binary distribution for linux/mips and others?

I think mips needs to bake at least another cycle. See also: #17018
