### ISSUE TITLE
gccgo: gcc testsuite failures due to regression in ppc64le 

### ISSUE THREAD

**Issue by laboger** [golang/go#18200]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 gccgo (GCC) 7.0.0 20161128 (experimental) linux/ppc64le

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 ppc64le

### What did you do?
Looking at the test failures in gcc-testresults for gccgo from 7.0.0

### What did you expect to see?
No failures (except the expected cplx.go)

### What did you see instead?
Failures

In looking at the gcc-testresults output for ppc64le I found that the failures for stack.go and recover.go started happening in commit 241222, and passed in 241215.  The commit for 241222 looks suspicious since it affects functions and trampolines.  This change doesn't look to be specific to Go but caused regressions in gccgo.

gcc-testresults log shows this when it fails (cplx.go is a known error):

	=== go tests ===

Running target unix
FAIL: go.test/test/ken/cplx2.go execution,  -O2 -g 
FAIL: go.test/test/recover.go execution,  -O2 -g 
FAIL: go.test/test/stack.go execution,  -O2 -g 

Running the new test failures individually show this output:
./recover.x 
panic: 13
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa]

goroutine 16 [running]:
__go_panic
	/home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-panic.c:110__go_panic
	/home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-panic.c:66main.test13reflect2
	/home/boger/gccgo.work/trunk/src/gcc/testsuite/go.test/test/recover.go:456main.main
	/home/boger/gccgo.work/trunk/src/gcc/testsuite/go.test/test/recover.go:58
goroutine 18 [finalizer wait]:

./stack.x 
bad func 21 at level 8000
panic: fail

goroutine 16 []:
__go_panic
	/home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/go-panic.c:110main.recur
	/home/boger/gccgo.work/trunk/src/gcc/testsuite/go.test/test/stack.go:87main.main
	/home/boger/gccgo.work/trunk/src/gcc/testsuite/go.test/test/stack.go:99

**Comment by ianlancetaylor** [comment]
Mentioned externally at https://gcc.gnu.org/ml/gcc-patches/2016-12/msg00388.html.

**Comment by laboger** [comment]
libgo testcase crypto/tls also started failing with this commit.

**Comment by laboger** [comment]
The go testcases stack.go, recover.go and libgo testcase crypto/tls now pass according to the latest gcc-testresults for gccgo 7.0.0 on ppc64le.
