### ISSUE TITLE
x/net/http2: support sendfile optimization

### ISSUE THREAD

**Issue by nhooyr** [golang/go#18204]
It doesn't look like the http2 response writer supports the sendfile optimization that the http/1.x one does as it does not implement the ReadFrom method.

This method is what I am talking about: https://github.com/golang/go/blob/8016808562c514dbb1146739b56ca67be9028d91/src/net/http/server.go#L537

**Comment by bradfitz** [comment]
This isn't really relevant for http2.

http2 is basically always over TLS (at least for common browsers, and for Go), where sendfile doesn't work.

But even if you used golang.org/x/net/http2 directly to implement h2c (cleartext http2), http2 has framing boundaries and a 16KB or so frame boundary, so you'd need to do many repeated small sendfile calls, which are much less beneficial.

So, closing this as not applicable.
