### ISSUE TITLE
build: The Android and iOS builders should be online and green

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#18214]
The Android builders are online, but at least the arm64 builder seems to be misconfigured. The iOS builders are not online at all.

I know @crawshaw is working on it, but I wanted to add it here so it won't be forgotten.

**Comment by quentinmit** [comment]
I'm moving this to Maybe because they are not first-class ports.

**Comment by rsc** [comment]
Ping @crawshaw

**Comment by eliasnaur** [comment]
Current status of this: I have received a Mac Mini and iPhone (thanks!) from crawshaw and josharian. The mini is ready to run, with most fixup CLs merged. In fact, the remaining CLs are waiting for your cmd/go ban to lift :) When those are in, darwin/arm and darwin/arm64 successfully runs all.bash.

I'm also waiting for builder keys from @bradfitz or @crawshaw.

If everything goes well, I plan to add android device(s) to the builder next.

**Comment by rsc** [comment]
Thanks very much @eliasnaur

**Comment by bradfitz** [comment]
@eliasnaur, email me bradfitz at go domain.

**Comment by eliasnaur** [comment]
darwin/arm, darwin/arm64, android/arm and android/arm64 builders are now running and green.

**Comment by bradfitz** [comment]
Thanks!
