### ISSUE TITLE
gccgo: regression in libgo test text/tabwriter on ppc64x

### ISSUE THREAD

**Issue by laboger** [golang/go#18228]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 gccgo (GCC) 7.0.0 20161206 (experimental) linux/ppc64le
+ patch to fix #18200

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04

### What did you do?
Testing the fix for #18200, reviewing other new failures, mainly those that are new within the past few months.

### What did you expect to see?
No new failures during that time.

### What did you see instead?
Consistent failure in text/tabwriter.  Based on gcc-testresults data, this test passed with gcc commit 242702 and started failing on 242719.  Looking at the commits between, this one looks like the one most likely:  https://gcc.gnu.org/ml/gcc-patches/2016-11/msg02259.html
@ianlancetaylor 

Running this test:

./a.out 
--- FAIL: TestPanicDuringFlush (0.00s)
Segmentation fault

Ran this with gdb and saw this:

--- FAIL: TestPanicDuringFlush (0.00s)

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x3fffb332f010 (LWP 28608)]
runtime.ifaceT2Ip (to=<optimized out>, from=<optimized out>) at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/runtime/iface.go:294
294		if from.uncommontype == nil || len(from.methods) == 0 {
(gdb) bt
#0  runtime.ifaceT2Ip (to=<optimized out>, from=<optimized out>) at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/runtime/iface.go:294
#1  0x00003fffb7723b18 in runtime.preprintpanics (p=0x3fffb2b2f930) at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/runtime/panic.go:363
#2  runtime.gopanic (e=...) at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/runtime/panic.go:470
#3  0x00003fffb77754a8 in testing.$nested8$recover (pr.2=<optimized out>)
    at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:578
#4  0x00003fffb77755fc in testing.$nested8 () at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:568
#5  0x00003fffb7768b30 in testing.$thunk21 (__go_thunk_parameter=<optimized out>)
    at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:568
#6  0x00003fffb7719ae8 in runtime.deferreturn (frame=<optimized out>) at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/runtime/panic.go:197
#7  0x00003fffb7768d84 in testing.tRunner (param=<optimized out>, fn=<optimized out>)
    at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:611
#8  0x00003fffb7768e54 in testing.$thunk22 (__go_thunk_parameter=<optimized out>)
    at /home/boger/gccgo.work/trunk/bld/../src/libgo/go/testing/testing.go:645
#9  0x00003fffb72ccbe8 in kickoff () at /home/boger/gccgo.work/trunk/bld/../src/libgo/runtime/proc.c:257
#10 0x00003fffb656448c in makecontext () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/makecontext.S:137
#11 0x0000000000000000 in ?? ()

segv happens here

(gdb) x/i $pc
=> 0x3fffb7717b30 <runtime.ifaceT2Ip+112>:	ld      r9,56(r26)
(gdb) info reg $r26
r26            0x4	4

r26 was set from r4 which should have been a value passed as the second argument to this procedure.

**Comment by laboger** [comment]
Failure also happens on ppc64.

**Comment by ianlancetaylor** [comment]
Thanks for the report, it is indeed a bug in https://golang.org/cl/33414.
