### ISSUE TITLE
[package][fmt][print.go]how about become a little smarter come with this return line ? func (p *pp) doPrintln(a []interface{}) {

### ISSUE THREAD

**Issue by indescribable** [golang/go#18223]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
172

### What operating system and processor architecture are you using (`go env`)?
win7 amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
make same code smart suitable to different os

### What did you expect to see?
func (p *pp) doPrintln(a []interface{}) {
	for argNum, arg := range a {
		if argNum > 0 {
			p.buf.WriteByte(' ')
		}
		p.printArg(arg, 'v')
	}
        //==========================
       //here ,the  return line with diff os
       //============================
	if runtime.GOOS == "windows" {
		p.buf.WriteByte('\r')
		p.buf.WriteByte('\n')
	}

	if runtime.GOOS == "linux" {
		p.buf.WriteByte('\n')
	}

        // maybe there should plus macos..but im not sure what suit it. "/r"?

}

**Comment by davecheney** [comment]
I'm sorry, there doesn't appear to be a bug report here. 

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. If there is a bug report, they'll tell you to log one.

Thanks.
