### ISSUE TITLE
net/http: Transport.RoundTrip regression when retrying requests on Request.Body read error

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18239]
Bug report from Docker:

https://twitter.com/cpuguy83/status/806263794368397312 from https://github.com/docker/docker/pull/29030

Repro from the change where I'm working on a fix:

```go
func TestTransportBodyReadError(t *testing.T) {  
        defer afterTest(t)  
        ts := httptest.NewServer(HandlerFunc(func(w ResponseWriter, r *Request) {  
                if r.URL.Path == "/ping" {  
                        return  
                }  
                buf := make([]byte, 1)  
                n, err := r.Body.Read(buf)  
                w.Header().Set("X-Body-Read", fmt.Sprintf("%v, %v", n, err))  
        }))  
        defer ts.Close()  
        tr := &Transport{}  
        defer tr.CloseIdleConnections()  
        c := &Client{Transport: tr}  
  
        res, err := c.Get(ts.URL + "/ping")  
        if err != nil {  
                t.Fatal(err)  
        }  
        res.Body.Close()  
  
        r, w := io.Pipe()  
        errClose := errors.New("some error")  
        w.CloseWithError(errClose)  
        if _, err := c.Post(ts.URL+"/test", "", r); err != nil {  
                t.Logf("Got error: %v", err)  
        }  
}  
```

Go 1.7 always says "some error" as the error. In Go 1.8, we read from the request body, get an error, and then try to send the request again since we never wrote anything. But the first write ends up closing the request body (the pipe), and it can't be read the second time.

We need to do the same thing @tombergan and I did for http2 in https://github.com/golang/net/commit/8dab9293431a241c65a8e8d46bbaa0492ec94849 and not retry a request once its Body has been messed with, unless it has a `GetBody` func that can be used to reset itself.

/cc @cpuguy83

**Comment by cpuguy83** [comment]
Thanks for opening, was going to do this once the kids went to bed!

**Comment by cpuguy83** [comment]
Confirmed the changes in the CL fix our issue.
