### ISSUE TITLE
x/net/http2: flaky TestServer_Rejects_HeadersSelfDependence

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18235]
@tombergan, another test flake I just saw on OpenBSD during a trybot run:

```
openbsd-amd64-gce58 at d4177877c6d6e710d77dd8c94b91f8567f1aaa87 building net at 3e1ed1d52e454d78e90962ee54c440d41bc4d25d

--- FAIL: TestServer_Rejects_HeadersSelfDependence (2.04s)
	server_test.go:475: Error while expecting an RSTStream frame: timeout waiting for frame
FAIL
FAIL	golang.org/x/net/http2	43.217s
```
(from https://storage.googleapis.com/go-build-log/d4177877/openbsd-amd64-gce58_4c0035ad.log)

**Comment by tombergan** [comment]
It would be nice if we got full stack dumps on timeouts.

**Comment by bradfitz** [comment]
That's easy enough to add as a first step.

But often it's not enough, at least with the server half of things, if for example something isn't happening because the state machine isn't happy, as opposed to actually blocking on something like a channel or mutex. You often just see something blocked in the network waiting for something to arrive, but that's about it.

If it's not too noisy, though, it doesn't hurt to add.

**Comment by dsnet** [comment]
Related to #18111?

**Comment by tombergan** [comment]
I can't repro after 10s of 100s of runs with various combinations of tsan and gomaxprocs. The ReadFrame timeout is 2s. Is it possible these machines are so busy that this test gets descheduled for 2s on rare occasions?

**Comment by bradfitz** [comment]
Our OpenBSD VMs have always been the slowest.

I need to update them anyway. Maybe new OpenBSD sucks less on GCE. (Or sucks less in general?)

**Comment by bradfitz** [comment]
Closing in favor of earlier dup #18111.
