### ISSUE TITLE
io: regression in MultiReader.Read causes nil panic

### ISSUE THREAD

**Issue by dsnet** [golang/go#18232]
The combination of the following CLs causing a nil panic:
* [CL/17873](http://golang.org/cl/17873): make chained multiReader Read more efficient
* [CL/28533](http://golang.org/cl/28533): make MultiReader nil exhausted Readers for earlier GC

The first CL allows MultiReader to "inherit" another MultiReader's list of io.Reader. This is problematic when combined with the later CL since that can set readers in that list to nil.

Reproduction: https://play.golang.org/p/jPl_pRr3ul
```go
mr1 := io.MultiReader(strings.NewReader("def"), strings.NewReader("ghi"))
mr2 := io.MultiReader(strings.NewReader("abc"), mr1)

io.ReadFull(mr2, make([]byte, 4))
io.ReadFull(mr1, make([]byte, 4))
io.ReadFull(mr2, make([]byte, 3))
```

Discussion: https://groups.google.com/forum/#!topic/golang-dev/a5K3132l3_E

\cc @rsc @bradfitz @ncw

**Comment by rsc** [comment]
Suggested fix is to change`= nil` to `= eofReader` where eofReader is some pre-allocated reader that does the obvious thing. That will make sure the behavior of io.MultiReader(nil) does not change.

**Comment by dsnet** [comment]
@rsc, would you like me to make the change?

**Comment by bradfitz** [comment]
Go for it. Otherwise I can if you're busy.

**Comment by ncw** [comment]
I can confirm that this fixes my original issue - thanks for tracking it down and making a fix :-)
