### ISSUE TITLE
doc: release notes need to mention trace changes

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18234]
I have a big fat TODO for the trace changes in Go 1 .8:

https://beta.golang.org/doc/go1.8#tool_trace

I haven't kept track of trace very closely this release.

@aclements, are you the right person to write these? If not, reassign to me or somebody else.

/cc @dvyukov @hyangah if either of you have words you'd like to be added to the release notes here.

**Comment by aclements** [comment]
Sure, I can write these. I'll send the CL to @dvyukov and @hyangah.

**Comment by bradfitz** [comment]
Thanks!
