### ISSUE TITLE
cmd/go: ldflags -X needs better documentation

### ISSUE THREAD

**Issue by james-lawrence** [golang/go#18246]
the [cmd/link](https://golang.org/cmd/link/) documentation's example is rather useless and most of the
examples I've managed to find of using -X all use `main.name` in there example. It'd be helpful for a more complete example to exist within the documentation.

[example 1](https://blog.cloudflare.com/setting-go-variables-at-compile-time/)
[example 2](http://stackoverflow.com/questions/11354518/golang-application-auto-build-versioning)
### What version of Go are you using (`go version`)?
```
go version go1.7.3 linux/amd64
```
### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```
### What did you do?
```
// file is located at src/github.com/james-lawrence/spike/commands/spike/main.go

// note: I've tried `var version string` as well, and it prints the zero value.
const version = "spike"
func main() {
   fmt.Println("version:", version)
}
```
```
go install -ldflags "-X github.com/james-lawrence/spike/commands/spike.version=abc" github.com/james-lawrence/spike/commands/...
./bin/spike
```

### What did you expect to see?
`abc` or an error/warning about not being able to replace the value.

### What did you see instead?
`spike`

**Comment by bradfitz** [comment]
Just docs, so maybe we can sneak it into 1.8 yet.

**Comment by ianlancetaylor** [comment]
We tried giving a warning if the `-X` variable did not exist in the program, but that broke people that use `-X` all the time but for whom only some programs have the variable in question.  That seemed like a reasonable workflow, so we decided that we shouldn't break it.

The problem with your program is that you are using a `const`.  The docs say you must use a "string variable".  A `const` is not a "string variable".

I'm not sure where to put an example.  cmd/link/doc.go seems like an odd place for that, as there are no other examples there.  Do you have any suggestions?

**Comment by james-lawrence** [comment]
if you read my comment right above that I tried `var version string` to the same result.

Not sure of a better place to put it. maybe an example .go file with a link from the cmd/link/doc?

**Comment by ianlancetaylor** [comment]
Would a change like https://golang.org/cl/34230 help?

**Comment by james-lawrence** [comment]
yes, super helpful actually.

but it also brings up more questions, I'll play with it more tomorrow and make sure what I'm seeing actually works as I expect. but otherwise it looks good.

**Comment by rsc** [comment]
CL is incorrect and should be reverted.

**Comment by james-lawrence** [comment]
Oh? It worked for my initial tests.

**Comment by rsc** [comment]
@james-lawrence It sounds like the part missing from the docs that would have helped you is that package main's import path is 'main', not the fully-qualified directory name like for other packages. Am I right that that's what you needed? Or do I misunderstand your situation above?

Thanks.

**Comment by bradfitz** [comment]
@ianlancetaylor, now that the docs have been reverted, do you want to say something else there instead?

**Comment by rsc** [comment]
The sentence I can imagine adding would be something like

> The importpath for the top-level package main is "main".

But I'm a little confused because in @james-lawrence's original post explicitly calls out that the examples he found use 'main', so I was expecting a different shortcoming in the docs.

**Comment by james-lawrence** [comment]
@rsc it was both the main package piece. (In retrospect thats fairly obvious and i just missed it) and the types for which it works. I was having issues in regular packages as well, not main ones. i was also surprised by no support for const :)

**Comment by james-lawrence** [comment]
My initial use cases for using this included both main package and any random package.

They were:
- compile time optimizing of code. Ie set a bool const to false to optimize a code path out. (Build flags are more suited to this in retrospect)
- setting a version value at build.

**Comment by ianlancetaylor** [comment]
I've added an example of using -X to https://golang.org/wiki/GcToolchainTricks .

That's the best approach I've been able to come up with. I'm not sure it's worth adding a pointer from the cmd/link page; I hope that search engines will give the Go wiki high relevance as they discover it.  I'm going to close this issue.
