### ISSUE TITLE
Need new grammar instead if err then return.

### ISSUE THREAD

**Issue by wangxingge** [golang/go#18242]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.7

### What operating system and processor architecture are you using (`go env`)?
Centos 6.5, Centos 7.

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Write code and check error, feel bad.

### What did you expect to see?

I want to have a grammar to instead following code:
if err != nil{
return err
}
grammer likes: onErrorReturn(err)
### What did you see instead?
grammer likes: onErrorReturn(err)

**Comment by wangxingge** [comment]
It's beautifull, isn't it?

**Comment by bradfitz** [comment]
This has been discussed at length in many forums and rejected in the past. The language is frozen, especially for things this invasive.

Also, this isn't a formal proposal. See https://github.com/golang/proposal/ for the proposal process and examples of formal proposals.

**Comment by wangxingge** [comment]
Thanks for your response.
