### ISSUE TITLE
net/http ServeMux clears query when redirecting

### ISSUE THREAD

**Issue by Maydell** [golang/go#18249]
### What operating system and processor architecture are you using (`go env`)?
go version go1.7.1 linux/amd64

### What did you do?

```
package main

import "net/http"

func main() {
	http.HandleFunc("/route/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	})

	http.ListenAndServe(":8080", nil)
}
```
I made a request to the above server as follows
`curl "localhost:8080/route?test=a" -v`

### What did you expect to see?
As described in the docs, I expected the server to redirect me to path `/route/?test=a`

### What did you see instead?
Instead the server redirected me to path `/route/`, ignoring the query provided in the original request. 

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /route?test=a HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: /route/
< Date: Thu, 08 Dec 2016 18:22:54 GMT
< Content-Length: 42
< Content-Type: text/html; charset=utf-8
< 
<a href="/route/">Moved Permanently</a>.

* Connection #0 to host localhost left intact
```

**Comment by bradfitz** [comment]
Dup of #17841
