### ISSUE TITLE
net/http: make Transport use GetBody, retry requests when no bytes were written

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18241]
#15723 (https://golang.org/cl/27117) for Go 1.8 was too aggressive and buggy.

It was partially rolled back (see #18239).

This bug tracks fixing it properly for Go 1.9.

/cc @tombergan

**Comment by rogpeppe** [comment]
I'm not convinced about GetBody as an abstraction - it's not natural when using some kinds of obviously-retriable bodies such as files. Why not just seek to the body start if it implements io.Seeker? (you'd probably want to make that behaviour opt-in rather than opt-out).

**Comment by bradfitz** [comment]
But since you need an opt-in anyway, this seems like a reasonable opt-in. And we can't change our previous Close behavior, so seeking back to the beginning of a closed file obviously isn't going to work. Plus the more experience I have with type sniffing magic, the more it bites me. I like the explicitness of GetBody. GetBody is not just for Transport retries on network failures, but also Client redirects, replaying the request body. Trying to reuse the same Body while coordinating across those two layers (not forgetting http2) and without adding new API surface seems like it'd be gross.

I'm not sure this is the best place to discuss GetBody, though.

**Comment by odeke-em** [comment]
@bradfitz should we fold this issue into https://github.com/golang/go/issues/17844? I ask since this one is more recent and no bytes written might be considered idempotency, so this one becomes a subset of the mentioned issue.
