### ISSUE TITLE
blog: 404s on profiling-go-programs to benchgraffiti.googlecode.com 

### ISSUE THREAD

**Issue by bradleyfalzon** [golang/go#18244]
The blog post https://blog.golang.org/profiling-go-programs has a couple of URLs pointing to the domain benchgraffiti.googlecode.com, all of these URLs return 404s:

- http://benchgraffiti.googlecode.com/hg/havlak/havlak1.html
- http://benchgraffiti.googlecode.com/hg/havlak/havlak1.svg

Those are the only URLs on the page that return a 404.

The actual source code still appears to be available: https://code.google.com/archive/p/benchgraffiti/source/default/source

**Comment by minux** [comment]
We might need to rework the profiling go program blog post
again to incorporate some recent profiling additions?

e.g. it will be very cool if we can add a concurrent program,
and show case using tracer to improve concurrent programs.

**Comment by ALTree** [comment]
Dup of #15957
