### ISSUE TITLE
x/net/http2: exceeding the maximum flow-control window should be a connection error, not a stream error

### ISSUE THREAD

**Issue by tombergan** [golang/go#18259]
We have:
https://github.com/golang/net/blob/c46f265c325130a7a6c7b27db8c6fe14b64f1a68/http2/server.go#L1185
```go
if !st.flow.add(int32(f.Increment)) {
  return streamError(f.StreamID, ErrCodeFlowControl)
}
```

But the spec says:
http://httpwg.org/specs/rfc7540.html#InitialWindowSize
> An endpoint MUST treat a change to SETTINGS_INITIAL_WINDOW_SIZE that causes any flow-control window to exceed the maximum size as a connection error (Section 5.4.1) of type FLOW_CONTROL_ERROR.

**Comment by bradfitz** [comment]
Sure? The code you cite is from processing WINDOW_UPDATE frames, but the spec you cite is about SETTINGS frames.

There are at least parts of the spec that suggest FLOW_CONTROL_ERROR can be used as both connection and stream errors. ("A receiver MAY respond with a stream error (Section 5.4.2) or connection error (Section 5.4.1) of type FLOW_CONTROL_ERROR if it is unable to accept a frame.")

**Comment by tombergan** [comment]
You're completely right, I have no idea what I was thinking.
