### ISSUE TITLE
cmd/compile: rotate instructions are not always emitted when they could be

### ISSUE THREAD

**Issue by dgryski** [golang/go#18254]
go version devel +41908a5453 Thu Dec 1 02:54:21 2016 +0000 linux/amd64
(1.8beta1)

### What did you do?

https://play.golang.org/p/eyIlsgnmc4

### What did you expect to see?

Both of the rotate functions can be inlined.  For `rot7`, a `ROLL` instruction is generated:

```
ROLL    $7, AX
```

However, the constant propagation is incomplete for `rot`:

```
MOVQ    AX, CX
SHLL    $7, AX
SHRL    $25, CX
ORL     CX, AX
```

Rotate instructions are common in crypto code and hashing algorithms.  Here's an example of a significant speedup by forcing the compiler to emit the ROLQ:
https://github.com/cespare/xxhash/commit/4a66a12749189566cb040736cbb48d16af4b45ce

**Comment by randall77** [comment]
This issue is a side effect of doing rotate detection in walk instead of the SSA rewriter.
We just need to put rotate-generation rules in the SSA rewriter and remove them from walk.
Then we can retire the OLROT opcode.  And for that matter, all of walkrotate.

**Comment by dgryski** [comment]
I might try to tackle this.

**Comment by randall77** [comment]
See https://go-review.googlesource.com/#/c/34232/

**Comment by rasky** [comment]
This function does not generate a rotation, even after CL 34232 is applied:

```go
func testRotate(op uint32) uint32 {
	rot := uint((op >> 7) & 0x1E)
	return ((op & 0xFF) >> rot) | ((op & 0xFF) << (32 - rot))
}
```

Should I open a different issue?

**Comment by randall77** [comment]
@rasky Yes, if you could please open a different issue.
This issue is about rotates by a constant amount.
Your issue is rotates by a non-constant amount.
