### ISSUE TITLE
x/net/http2: 

### ISSUE THREAD

**Issue by wujieliulan** [golang/go#18258]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
 go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build560134607=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
http2 server  getRequestBodyBuf() creates lots garbage and memory usage is high

### What did you see instead?
Most requests don't have body, but all allocates a 64K buffer, no request body read is called , therefore, putRequestBodyBuf() won't be called to recycle the buffer.

Is it possible to allocate 64k buffer only if there is a request body?

**Comment by bradfitz** [comment]
Fixed by https://github.com/golang/net/commit/3bafa3320efdf0c95d056586aa9abdd05ad72ee1

**Comment by wujieliulan** [comment]
with golang/net@3bafa33 it still creates lots of garbage, the reason is for requests with no body, putRequestBodyBuf() is never called. Calling it in handlerDone() helps, but it still wastes lots of 64k buffer for requests without body (which is majority). I use this workaround, it saves lots of memory with busy servers:
--- a/http2/server.go
+++ b/http2/server.go
@@ -1418,13 +1418,12 @@ func (sc *serverConn) processData(f *DataFrame) error {
 
                return streamError(id, ErrCodeStreamClosed)
        }
-       if st.body == nil {
-               panic("internal error: should have a body in this state")
-       }
 
        // Sender sending more than they'd declared?
        if st.declBodyBytes != -1 && st.bodyBytes+int64(len(data)) > st.declBodyBytes {
-               st.body.CloseWithError(fmt.Errorf("sender tried to send more than declared Content-Length of %d bytes", st.declBody
+               if st.body != nil {
+                       st.body.CloseWithError(fmt.Errorf("sender tried to send more than declared Content-Length of %d bytes", st.
+               }
                return streamError(id, ErrCodeStreamClosed)
        }
        if f.Length > 0 {
@@ -1435,6 +1434,16 @@ func (sc *serverConn) processData(f *DataFrame) error {
                st.inflow.take(int32(f.Length))
 
                if len(data) > 0 {
+                       reqbodyMu.Lock()
+                       if st.body == nil {
+                               //fmt.Println("getBuf in processData")
+                               st.reqBuf = getRequestBodyBuf()
+                               st.body = &pipe{
+                                       b: &fixedBuffer{buf: st.reqBuf},
+                               }
+                               //panic("internal error: should have a body in this state")
+                       }
+                       reqbodyMu.Unlock()
                        wrote, err := st.body.Write(data)
                        if err != nil {
                                return streamError(id, ErrCodeStreamClosed)
@@ -1483,12 +1492,14 @@ func (st *stream) endStream() {
        sc := st.sc
        sc.serveG.check()
 
-       if st.declBodyBytes != -1 && st.declBodyBytes != st.bodyBytes {
-               st.body.CloseWithError(fmt.Errorf("request declared a Content-Length of %d but only wrote %d bytes",
-                       st.declBodyBytes, st.bodyBytes))
-       } else {
-               st.body.closeWithErrorAndCode(io.EOF, st.copyTrailersToHandlerRequest)
-               st.body.CloseWithError(io.EOF)
+       if st.body != nil {
+               if st.declBodyBytes != -1 && st.declBodyBytes != st.bodyBytes {
+                       st.body.CloseWithError(fmt.Errorf("request declared a Content-Length of %d but only wrote %d bytes",
+                               st.declBodyBytes, st.bodyBytes))
+               } else {
+                       st.body.closeWithErrorAndCode(io.EOF, st.copyTrailersToHandlerRequest)
+                       st.body.CloseWithError(io.EOF)
+               }
        }
        st.state = stateHalfClosedRemote
 }
@@ -1741,11 +1752,6 @@ func (sc *serverConn) newWriterAndRequest(st *stream, f *MetaHeadersFrame) (*res
                return nil, nil, err
        }
        if bodyOpen {
-               st.reqBuf = getRequestBodyBuf()
-               req.Body.(*requestBody).pipe = &pipe{
-                       b: &fixedBuffer{buf: st.reqBuf},
-               }
-
                if vv, ok := rp.header["Content-Length"]; ok {

**Comment by bradfitz** [comment]
To send changes, see https://golang.org/doc/contribute.html

We can't accept diffs over email or github.
