### ISSUE TITLE
No late binding for interface pointer

### ISSUE THREAD

**Issue by thanhpk** [golang/go#18266]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

If I have an object type of struct S which implemented interface I, then I can place the object in any param typed I.

So, why can't I do it with pointers of S and I. Why can't I pass pointer of object S to any parameters that require pointer typed I

```go
package main

type I interface {
	F()
}

type S struct {
}

func (S) F() {}

func MakeS() *I {
	return &S{}
}

func main() {}
```

### What did you expect to see?
It should complied with no error

### What did you see instead?
The compiler give me the following error
```
cannot use S literal (type *S) as type *I in return argument:
	*I is pointer to interface, not interface
```

Also, when I try to convert an S pointer to I pointer, I have to write
```go
func MakeS() *I {
    i := I(S{})
    return &i
}
```
instead of
```go
func MakeS() *I {
    return &(I(S{}))
}
```

**Comment by mvdan** [comment]
The compile error is correct; You need to take the address twice, once of the object and once of the interface.

Nevertheless, pointers to interfaces are rarely what you want: https://golang.org/doc/faq#pointer_to_interface

Please use https://github.com/golang/go/wiki/Questions.

**Comment by minux** [comment]
Yeah, please ask questions on other mediums.

**Comment by thanhpk** [comment]
As an "end"-developer, auto conversion pointer to its interface is very reasonable, right ?

I want to use pointer to interface because I am trying to write a mock struct for `mgo.Database` 
http://bazaar.launchpad.net/+branch/mgo/v2/view/head:/session.go#L492
```go
func (db *Database) C(name string) *Collection {...}
```

By define an interface like this
```go
type ICollection interface {...}
type IDatabase interface {
    C(name string) *ICollection {
} 
```
I am able to write a mock for `mgo.Database` struct and can run unit test without requiring mgo.

**Comment by minux** [comment]
Convert pointer to interface is reasonable, but convert interface to
pointer to interface is not.

Anyway, I still think using pointer to interface is a design mistake.
And not making it easier to write is probably a good idea.

**Comment by thanhpk** [comment]
@minux Can you suggest me how to build a mock for that struct without using pointer to interface then.

Also, wouldn't it be nicer when I can write

```go
func MakeS() *I {
    return &(I(S{}))
}
```
instead of
```go
func MakeS() *I {
    i := I(S{})
    return &i
}
```

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
