### ISSUE TITLE
go/types: cannot assign "nil..." to ... parameters

### ISSUE THREAD

**Issue by stjj89** [golang/go#18268]
The following code is accepted by both gc and gccgo, but not go/types:

```go
func foo(args ...string) {}

func bar() {
  foo(nil...)
}
```

The error returned by go/types is 

```
cannot use nil (untyped nil value) as parameter of type []string
```

It appears that go/types is wrong here. Per the spec
( https://golang.org/ref/spec#Passing_arguments_to_..._parameters, https://golang.org/ref/spec#Assignability ):

> If f is variadic with a final parameter p of type ...T, then within f the type of p is equivalent to type []T.
> ...
> If the final argument is assignable to a slice type []T, it may be passed unchanged as the value for a ...T parameter if the argument is followed by .... In this case no new slice is created.
> 

> A value x is assignable to a variable of type T ("x is assignable to T") in any of these cases:
> ...
> - x is the predeclared identifier nil and T is a pointer, function, slice, map, channel, or interface type.

**Comment by alandonovan** [comment]
I don't know why one would ever write that code, but you're right, the spec is pretty clear that it's a legal Go program.

/cc @griesemer
