### ISSUE TITLE
# golang.org/x/net/ipv6# golang.org/x/net/ipv4

### ISSUE THREAD

**Issue by fksmta** [golang/go#18265]
# golang.org/x/net/ipv6
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:7: sysIPV6_ADDRFORM redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:7
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:8: sysIPV6_2292PKTINFO redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:8
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:9: sysIPV6_2292HOPOPTS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:9
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:10: sysIPV6_2292DSTOPTS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:10
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:11: sysIPV6_2292RTHDR redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:11
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:12: sysIPV6_2292PKTOPTIONS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:12
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:13: sysIPV6_CHECKSUM redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:13
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:14: sysIPV6_2292HOPLIMIT redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:14
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:15: sysIPV6_NEXTHOP redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:15
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:16: sysIPV6_FLOWINFO redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv6/zsys_linux_amd64.go:16
../../../golang.org/x/net/ipv6/zsys_linux_arm64.go:16: too many errors
# golang.org/x/net/ipv4
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:7: sysIP_TOS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:7
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:8: sysIP_TTL redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:8
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:9: sysIP_HDRINCL redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:9
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:10: sysIP_OPTIONS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:10
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:11: sysIP_ROUTER_ALERT redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:11
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:12: sysIP_RECVOPTS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:12
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:13: sysIP_RETOPTS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:13
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:14: sysIP_PKTINFO redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:14
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:15: sysIP_PKTOPTIONS redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:15
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:16: sysIP_MTU_DISCOVER redeclared in this block
        previous declaration at ../../../golang.org/x/net/ipv4/zsys_linux_amd64.go:16
../../../golang.org/x/net/ipv4/zsys_linux_arm64.go:16: too many errors

**Comment by davecheney** [comment]
I'm sorry this is not an acceptable bug report. You have not used the template provided or given instructions how someone can reproduce the issue you are having.

At a guess, you're either trying to cross compile, or your Go installation is very old and or damanged.

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by mikioh** [comment]
See https://github.com/golang/go/wiki/Linux. Go 1.5 or above is required to build and run those packages on linux/arm64.
