### ISSUE TITLE
TrimSpace does not remove trailing spaces from byte array originated string slice

### ISSUE THREAD

**Issue by sanderssj** [golang/go#18263]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
https://play.golang.org/p/_y4zTPpIKu
I believe TrimSpaces should be removing the trailing space from the byte array.
### What did you expect to see?
I expect TrimSpaces to remove the trailing whitespace if I make the byte array a string

### What did you see instead?
The trailing space remains only on the string that was originally a byte array. I guess the difference the fact that the length of the barray includes the NUL character, but sarray does not is the reason why. This means that TrimSpaces doesn't remove the space because it isn't technically trailing (because the NUL byte is after it)? Even if this somewhat expected, I'd argue that it makes a very poor experience, given that the NUL byte is not actually printed.

**Comment by dsnet** [comment]
Hi.

Go strings are not NUL-terminated. So `TrimSpace` on sarray isn't implicitly removing the NUL byte. The documentation for [`unicode.IsSpace`](https://golang.org/pkg/unicode/#IsSpace) explicitly doesn't list NUL as being a "space".

Working as intended.
