### ISSUE TITLE
runtime/cgo: cgo support for linux/mips and linux/mipsle

### ISSUE THREAD

**Issue by minux** [golang/go#18267]
Tracking bug for linux/mips and linux/mipsle cgo support.

**Comment by vstefanovic** [comment]
The cgo support is ready, we can submit the patch if it is not too late for 1.8.

**Comment by bradfitz** [comment]
I'm pretty sure it's too late, but I'll let @ianlancetaylor decide. He'd probably have to review it. One argument is that this port is new, so perhaps it's okay for code to land this late.

**Comment by ianlancetaylor** [comment]
I think it's OK if the changes only touch MIPS-specific code.

**Comment by bradfitz** [comment]
@vstefanovic, can you send it in the next day or two? The next (and maybe last) beta is Thursday. It would need to be in by Wednesday night (US/Pacific), but it also needs review time.

**Comment by minux** [comment]
Should we fix the softfloat first? That seems to be the biggest
complaint from user?

**Comment by vstefanovic** [comment]
Ok, let me commit cgo now, soft-float tomorrow.

**Comment by bradfitz** [comment]
This happened in https://golang.org/cl/34318
