### ISSUE TITLE
io: document whether LimitedReader.Read returns EOF or ErrUnexpectedEOF

### ISSUE THREAD

**Issue by dsnet** [golang/go#18271]
The documentation for io.LimitedReader says:
> A LimitedReader reads from R but limits the amount of data returned to just N bytes. Each call to Read updates N to reflect the new amount remaining.

It doesn't say anything about what happens when EOF is hit first in the underlying R and N > 0. Does it return EOF or ErrUnexpectedEOF?

Current behavior is to return EOF. We should document that.

**Comment by bradfitz** [comment]
Well, ErrUnexpectedEOF wouldn't be the right error in any case. I think you mean EOF vs ErrUnexpectedDataNotEOFViolatingTruncatingYourData.

But yes, it's EOF, silently truncating your data at the desired location.

Feel free to send for 1.8 if you'd like, but don't re-milestone to 1.8.
