### ISSUE TITLE
x/tools/godoc: copying source code should not copy the line numbers as well

### ISSUE THREAD

**Issue by kevinburke** [golang/go#18279]
If I go to e.g. https://golang.org/src/path/filepath/path.go?s=4925:4961#L171, and try to copy the source code, the line numbers are included in the highlighted text. In general I'd rather not copy the source code with the line numbers.

If you view the same code on github.com, you can highlight and copy the source code without the line numbers included.

https://github.com/golang/go/blob/master/src/path/filepath/path.go

Happy to work on a fix but it might take a while.

**Comment by bradfitz** [comment]
SGTM.

/cc @broady

**Comment by josharian** [comment]
This and variants have come up a bunch before. A sample: #4656, #5867, #9042.  It'd be awesome to get it fixed broadly.

**Comment by dhananjay92** [comment]
After [golang.org/cl/34279](http://golang.org/cl/34279):
<img width="1414" alt="screen shot 2016-12-10 at 10 16 10 pm" src="https://cloud.githubusercontent.com/assets/6269279/21078520/c2ce4a50-bf27-11e6-98a7-b96d888d9a1e.png">

**Comment by kevinburke** [comment]
I've also submitted a CL that changes the CSS only and fixes the problem. I
don't think gopherbot adds "mentions this issue" links for the tools repo.

**Comment by dhananjay92** [comment]
Ah, never mind. Just saw Kevin's change at http://golang.org/cl/34278

**Comment by dhananjay92** [comment]
Yes, abandoned my change. gopherbot's mention would have saved effort on my side 😅

**Comment by bradfitz** [comment]
Gopherbot works if you make the reference correctly fully qualified. See other commits in history.

**Comment by kevinburke** [comment]
Neat. Thanks!
