### ISSUE TITLE
website: drop reddit from golang.org/conduct list of official spaces

### ISSUE THREAD

**Issue by rsc** [golang/go#18289]
Per https://www.reddit.com/r/golang/comments/5h87u6 we need to drop Reddit from the list of official spaces moderated by conduct@golang.org on https://golang.org/conduct.

I am not entirely sure how to do this.

@broady or @adg, do you know?

Thanks.

**Comment by dgryski** [comment]
That file is https://github.com/golang/go/blob/master/doc/conduct.html , specifically https://github.com/golang/go/blob/master/doc/conduct.html#L70

**Comment by rsc** [comment]
Reopening until someone (@broady?) pushes the change to the live site.

**Comment by kavu** [comment]
Fixed in 265e547658ac6e91df308326041ea462593053fc?

**Comment by bradfitz** [comment]
Kavu, see Russ's comment.

**Comment by broady** [comment]
It's live

**Comment by rsc** [comment]
Thanks Chris.
