### ISSUE TITLE
x/image/font: no method to measure exact string drawing bounds

### ISSUE THREAD

**Issue by rgeronimi** [golang/go#18297]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/raphaelgeronimi/Local/Others/Go workspace"
GORACE=""
GOROOT="/opt/local/lib/go"
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
CC="/usr/bin/clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zw/0zvr11l11975vn4gk7s4hrx00000gn/T/go-build732769753=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I need to measure the exact drawing bounds of a string with a Face from x/image/font, to draw it in a bitmap of the proper size, and position the origin of the string properly so as to not clip any extraneous left, top, bottom or right typographic "limb".

### What did you expect to see?
A function or method to measure the exact bounds, as:
- It is a very common need
- Measuring them is not trivial for a library end-user as it requires some typographic knowledge (e.g., kerning), and the amount of duplicated code goes beyond the usual loop 3-liners (with standard formatting, this takes 40 lines).

### What did you see instead?
No method found.

I wrote a patch with the missing functions and methods BoundString and BoundBytes, that I am ready to contribute.

**Comment by josharian** [comment]
Possible dup: https://github.com/golang/go/issues/14436

**Comment by josharian** [comment]
cc @nigeltao
