### ISSUE TITLE
net: TestTCPSelfConnect failures due to unexpected connections

### ISSUE THREAD

**Issue by RLH** [golang/go#18290]
```
#!watchflakes
post <- pkg == "net" && test == "TestTCPSelfConnect"
```

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
On a 
rlh@rlh1:~/work/go/src$ go version
go version devel +d4b46aa Thu Dec 8 01:36:44 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
rlh@rlh1:~/work/go/src$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/rlh/work/code"
GORACE=""
GOROOT="/usr/local/google/home/rlh/work/go"
GOTOOLDIR="/usr/local/google/home/rlh/work/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build725383804=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
rlh@rlh1:~/work/go/src$ go version
go version devel +d4b46aa Thu Dec 8 01:36:44 2016 +0000 linux/amd64
rlh@rlh1:~/work/go/src$ 
rlh@rlh1:
This is a 6 core 12 thread machine.
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
stepping	: 2
siblings	: 12
```

### What did you do?
I ran ./run.bash in a simple loop using the following.
GOTRACEBACK=crash ./run.bash -no-rebuild

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
See above.

### What did you expect to see?
Success.

### What did you see instead?

After a day (34 hours) 727 successful runs I got the following failure.

..snip. ...

ok  	mime/quotedprintable	0.162s
--- FAIL: TestTCPSelfConnect (0.13s)
	tcpsock_test.go:661: Dial 127.0.0.1:48322 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48324 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48325 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48326 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48327 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48328 should fail
	tcpsock_test.go:661: Dial 127.0.0.1:48329 should fail
FAIL
FAIL	net	1.527s
ok  	net/http	2.550s
ok  	net/http/cgi	0.495s

... snip ..

Note missing 48323.

I have not reproduced it. The only reason this is a concern is that it limits stress testing speculative parts of the GC and runtime.

**Comment by mikioh** [comment]
Challenging against TCP simultaneous open is a bit tough job. Let's push out the test from short-mode testing except when running on buildbots.

**Comment by bradfitz** [comment]
If the test just rarely catches the bug, I'd rather not sweet it under the rug by making it run less often.

Is this not a real bug?

If so, what's the bug.
If not, I'd rather deflake it.

**Comment by mikioh** [comment]
> Is this not a real bug?

I'm confused. The fix (https://codereview.appspot.com/5650071) was approved by you. I'm not sure what you are asking for.

My understanding is that TCP simultaneous open is a valid behavior of TCP and the fix written by @rsc was just a try to mitigate some undesirable side effect of the behavior for helping some application. But that might be a compromise. I think it's basically impossible to avoid TCP simultaneous open completely unless we have full control of each TCP FSM and IP control block inside the kernel.

**Comment by ianlancetaylor** [comment]
I don't see any GNU/Linux failures of TestTCPSelfConnect in the builders at all.  I do see a few failures on Solaris; for example: https://build.golang.org/log/5315cb250600796a1ffe1c4c3a8c3f626769b692.

**Comment by bcmills** [comment]
[2020-11-09T15:46:56-979e137/dragonfly-amd64](https://build.golang.org/log/ce45aaa896e96f5cb4846c4ebbb0a3b3d304b585)

**Comment by bcmills** [comment]
`watchflakes` found another one of these, reported in #57609.

**Comment by bcmills** [comment]
I propose that we fix this by deleting the test (https://go.dev/cl/460657).

The test's condition seems to be buggy: due to a typo in https://go.dev/cl/21447, it fails if it finds any connection whose source port OR IP address matches the destination port or address, which includes much more than just self-connects. (It essentially becomes a port-scanner for the previously-closed destination port.)

But even if we fixed that bug, the cost of dialing an arbitrary, possibly-reused port is fairly high (port exhaustion, CPU time, etc.), the potential for interference with other tests is high (because these dials may be accepted _in lieu of_ a dial expected by some other test process), and the coverage of the test is low (on non-Linux short tests it scales back by 1000x, and it can only even _possibly_ fail in the presence of what is arguably a kernel bug).

To me, the marginal benefit of keeping this test is not worth the cost of maintaining it.

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.19 and 1.20. This is a trivial backport to delete a noisy test.
