### ISSUE TITLE
x/build: fix coordinator's localhost dev mode; should not require GCE

### ISSUE THREAD

**Issue by mxplusb** [golang/go#18291]
Attempted to run `golang.org/x/build/cmd/coordinator` locally without GCE access, ran into this error:

`failed to get a token source: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

Related to #17626

**Comment by bradfitz** [comment]
I assume you mean you're running `golang.org/x/build/cmd/coordinator` and not just a single file, right?

Also, which flags are you running the binary with?

**Comment by mxplusb** [comment]
I updated the description to reflect `golang.org/x/build/cmd/coordinator`.

I'm running it with `-mode "dev"`.
