### ISSUE TITLE
cmd/compile: autogenerate rules for commutative ops

### ISSUE THREAD

**Issue by randall77** [golang/go#18292]
We have a lot of almost-duplicate rules like this:
```
(ADDL x (MOVLconst [c])) -> (ADDLconst [c] x)
(ADDL (MOVLconst [c]) x) -> (ADDLconst [c] x)
```
We know that `ADDL` is commutative (the description of ops includes a commutative flag which is currently used for other purposes). We should be able to auto-generate the second rule from the first.

We could get rid of a lot of rules using this technique.

**Comment by josharian** [comment]
@brtzsnr mentioned in https://github.com/golang/go/issues/16270. that there is a way to do many of these without having to write a bunch of rewrite rules.
