### ISSUE TITLE
blog: links need more contrast against body text

### ISSUE THREAD

**Issue by spf13** [golang/go#18302]
In the main content of the blog the links are hard to identify. They are navy while the primary text is black. There are no other visual cues unless you mouse over. 

The links should be a different color with further separation from the body text and should have a visual cue that they are links. 

Example: https://blog.golang.org/survey2016

**Comment by broady** [comment]
Let's re-add back the underline to `.article a:link`

**Comment by rsc** [comment]
@broady, are you going to send a CL to put underlines back? SGTM.

**Comment by broady** [comment]
Deployed live.

https://blog.golang.org/survey2016
