### ISSUE TITLE
x/oauth2/jwt: does not send kid

### ISSUE THREAD

**Issue by tcolgate** [golang/go#18307]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.7 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tristan/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build824281085=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
We are using google.JWTConfigFromJSON to read credentials from a google service account JSON config file. We're are then using these tokens with an internal service. This service requires the kid field in the JWT header, however x/oauth2/jwt does not set the header.

https://play.golang.org/p/xEDTBIsxXZ

If we use  google.JWTAccessTokenSourceFromJSON, the correct headers are sent, but that provides no way to set scopes, or get an oauth2.Config

### What did you expect to see?

kid header should be set.

### What did you see instead?

kid header not set.

**Comment by tcolgate** [comment]
Raised https://go-review.googlesource.com/#/c/34320/

**Comment by bradfitz** [comment]
@rakyll, who owns JWT stuff?

/cc @broady @adg

**Comment by rakyll** [comment]
Looking at it.

**Comment by tcolgate** [comment]
Fix has been merged, closing.
Many thanks!
