### ISSUE TITLE
doc: Specify please when it's needed that the value should be passed by reference

### ISSUE THREAD

**Issue by arnogo** [golang/go#18306]
I'm relatively new to strictly typed programming, and I've seen code like:  
`fmt.Scan(&name)`  

I understand why is it passed by reference, since we want to modify the existing variable, yet still  
I've tried looking up documentation, and both:  
https://golang.org/pkg/fmt/#Scan
and
https://golang.org/src/fmt/scan.go?s=2653:2699#L53  
Didn't have anything mentioned about passing the value by reference (both specify `a ...interface{}`)  

I've also tried experimenting with the code and doing `fmt.Scan(name)` and maybe it should throw an error or something, since you obviously need to pass the variable by reference, otherwise it will be lost

My question is, could the documentation somehow mention that the value should be passed by reference? Maybe have it something like `a ...*interface{}`?

Thank you

**Comment by minux** [comment]
Use a pointer when you expect the function (in this case, Scan)
to modify the value.

If you want to ask a question, please see https://golang.org/wiki/Questions.

**Comment by arnogo** [comment]
Thank you and sorry that is is the wrong place to ask
