### ISSUE TITLE
RFE: please make it possible to core dump on program failures by default

### ISSUE THREAD

**Issue by jfilak** [golang/go#18304]
I would like to have "crash" as the default value of GOTRACEBACK. I know I can export the environment variable in system profile but it is not so uncommon that applications run in clear environment (`env -i`). I am asking because, I want to automatically report program crashes and the easiest way how be notified about them is to register own /proc/sys/kernel/core_pattern.

Thank you for considering my request.

**Comment by bradfitz** [comment]
We're not going to make that the default. But doesn't https://golang.org/pkg/runtime/debug/#SetTraceback work for you?

**Comment by jfilak** [comment]
I am working on ABRT - Automatic Bug Reporting Tool - that is enabled on Fedora. We detect core dumps, python exception, ... and would like to detect failures of go programs. Currently, we must export GOTRACEBACK=crash and pollute global environment to achieve this goal

SetTraceback would work if I needed to set it for a single program, but I want to be able to detected failures of all go programs.

I don't want you to make "crash" the default. I would be happy with a build-time configuration option that would make that default for Fedora.

**Comment by bradfitz** [comment]
We don't really do build-time configuration options.

About the closest we have is the CGO_ENABLED and GO386/GOARM environment variables.

Can you just add the 1-line patch to the Fedora repo? I assume you likely already carry a configuration patch or two in your tree?

**Comment by minux** [comment]
Making coredump the default affects too many users but
I don't think the benefit outweigth the cost and confusion
it causes -- not every one has such automatic bug reporting
tool (and I also think if Go has such a report builtin, we
will just get a lot of irrelevant bug reports, besides it's
a violation of user's privacy.)

**Comment by bradfitz** [comment]
@minux, it sounds like he only wants to enable it by default on Fedora.

@jfilak, if you modify Fedora's version of Go, please do a (fast) check at start-up to verify you're running on Fedora (and ABRT is available) before setting the default GOTRACEBACK value.

It would be kinda unfortunate if a Fedora user distributed binaries to non-Fedora users and they were surprised by core dumps they didn't ask for and didn't expect.

**Comment by jfilak** [comment]
Oh, I see. If we change something in https://github.com/golang/go/blob/master/src/runtime/runtime1.go, the change will be built into programs. That's something different than I hoped for and I'm not sure we want to do that. Perhaps we can find a way how to let official Go programs do core dump files while leaving user Go programs untouched. Seems that it won't be a 1-line patch.

Just a question, could it be an option of `go build` - e.g. `--traceback=crash`? It would be easier for us to pass this argument on command line when building official packages, then detecting that a programs is not running on Fedora.

**Comment by bradfitz** [comment]
What's an "official Go program"? One that Fedora builds and includes in the package manager?

You could use `go build --tags=use_abrt` (some arbitrary tag you make up), and then add a file to Fedora's copy of the runtime package, like:

```go
// +build use_abrt

func init() {
    SetTraceback("crash")
}
```

So if that tag is specified when you build official programs, that file with `+build use_abrt` is included, and it then sets "crash" as the default for that process.

**Comment by jfilak** [comment]
> What's an "official Go program"? One that Fedora builds and includes in the package manager?

Yes, exactly.

> You could use go build --tags=use_abrt ...

Sounds great! I'll give it a try.
Thank you very much indeed.
