### ISSUE TITLE
go/internal/gccgoimporter: import control function v2 format not properly parsed

### ISSUE THREAD

**Issue by stjj89** [golang/go#18301]
The follow sequence of import control function list in time.gox:

```
init time time..import runtime runtime..import sync sync..import syscall syscall..import;
```

results in the following gccgoimporter error while it is being parsed:

```
import error time:7:31 (byte offset = 152): expected Int, got Ident (runtime))
```

gccgoimporter appears to expect only the v1 format:

https://golang.org/src/go/internal/gccgoimporter/parser.go?h=parsePackageInit#L695

while the gccgo frontend has logic to specifically handle the v1 format:

https://github.com/golang/gofrontend/blob/master/go/import.cc#L466

**Comment by ianlancetaylor** [comment]
CC @thanm
