### ISSUE TITLE
x/crypto/twofish: twofish_test.go copyright

### ISSUE THREAD

**Issue by keithbostic** [golang/go#18311]
In the `twofish_test.go` file, there's the standard Go copyright, along with the comment:
```
        // These test are derived from http://www.schneier.com/code/ecb_ival.txt
```
and there's no copyright on that source file, so it's unclear the basis for the inclusion.

That might be worth clarifying.

**Comment by bradfitz** [comment]
Those have been there since 2011 from 1aec7c7f34ff88a09a3fa7c9ff131598360f8751 (when it was still in std).

IANAL but I'm also not terribly concerned due to the source, and that these are just test vectors.

But cc @agl @ianlancetaylor.

**Comment by keithbostic** [comment]
Thank you.

I think it's one of the issues where nobody will ever get sued, and anyone sued would win and the damages are zero, but it's a technical violation and companies that look for copyright violations will flag it, which wastes everyone's time.

If it's trivial to fix, might be worth it.

**Comment by agl** [comment]
While it's the sort of statement that lawyers might cringe at, Schneier [says](https://www.schneier.com/academic/twofish/) that "Twofish is unpatented, and the source code is uncopyrighted and license-free; it is free for all uses".

**Comment by bradfitz** [comment]
Thanks, @agl. I think that's sufficient to close this bug. If somebody wants to add a comment line to twofish_test.go and send that CL, that works too.
