### ISSUE TITLE
cmd/go: go get -t do not install packages

### ISSUE THREAD

**Issue by powerman** [golang/go#18315]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/build/a94a8fe5"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build834793487=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
go get -v -t ./proto/apns/

### What did you expect to see?
Packages required for running tests not only downloaded, but also installed.

### What did you see instead?
```
proto/apns# cat init_test.go 
package apns

import (
	"testing"

	. "gopkg.in/check.v1"
)

func Test(t *testing.T) { TestingT(t) }
proto/apns# ls -l $GOPATH/pkg/linux_amd64/gopkg.in/check.v1.a
ls: cannot access /tmp/build/a94a8fe5/pkg/linux_amd64/gopkg.in/check.v1.a: No such file or directory
proto/apns# go get -v -t .
proto/apns# ls -l $GOPATH/pkg/linux_amd64/gopkg.in/check.v1.a
ls: cannot access /tmp/build/a94a8fe5/pkg/linux_amd64/gopkg.in/check.v1.a: No such file or directory
proto/apns# go get -v gopkg.in/check.v1
gopkg.in/check.v1
proto/apns# ls -l $GOPATH/pkg/linux_amd64/gopkg.in/check.v1.a
-rw-r--r-- 1 root root 400968 Dec 14 19:28 /tmp/build/a94a8fe5/pkg/linux_amd64/gopkg.in/check.v1.a
```

Real reason why I need it to be installed is because golang.org/x/tools/cmd/gotype fails if it's not installed (so maybe this should be fixed in `gotype` instead of `go get`):

```
proto/apns# rm $GOPATH/pkg/linux_amd64/gopkg.in/check.v1.a
proto/apns# gotype -a .
init_test.go:6:4: could not import gopkg.in/check.v1 (can't find import: gopkg.in/check.v1)
proto/apns# go get -v gopkg.in/check.v1
gopkg.in/check.v1
proto/apns# gotype -a .
proto/apns#
```

**Comment by rsc** [comment]
I think this is working as documented:

```
$ go help get
usage: go get [-d] [-f] [-fix] [-insecure] [-t] [-u] [build flags] [packages]

Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.

...

The -t flag instructs get to also download the packages required to build
the tests for the specified packages.

...
$ 
```

Overall, get downloads and installs the named targets, but -t only downloads the test dependencies: it does not install them. If you want to install the test dependencies as well, then you can follow `go get -v -t gopkg.in/check.v1` with `go test -i gopkg.in/check.v1`.

The new caching work planned for Go 1.10 will require gotype to coordinate a bit more anyway, and that coordination will make plain downloads of the test dependencies good enough.
