### ISSUE TITLE
x/sys/unix: Add UMOUNT_NOFOLLOW constant

### ISSUE THREAD

**Issue by schmichael** [golang/go#18316]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.7.3 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/schmichael/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build019656358=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### Enhancement

Add `UMOUNT_NOFOLLOW = 0x8` constant to prevent symlink traversal attacks when unmounting filesystems.

Present since Linux 2.6.34: https://github.com/torvalds/linux/commit/db1f05bb85d7966b9176e293f3ceead1cb8b5d79

**Comment by ianlancetaylor** [comment]
Want to send a patch?  https://golang.org/doc/contribute.html
