### ISSUE TITLE
x/sys/unix: functions redeclared in gccgo builds

### ISSUE THREAD

**Issue by stjj89** [golang/go#18312]
In gccgo builds, the {Raw,}Syscall{,6} and gettimeofday functions in go.sys/unix are redeclared.

While gccgo tolerates this, this is technically incorrect according to the spec (https://golang.org/ref/spec#Declarations_and_scope):

"No identifier may be declared twice in the same block..."

**Comment by bradfitz** [comment]
Is there a bug tracking why gccgo tolerates that?

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
@bradfitz There is an Google-internal bug report against gccgo for this behavior.  I'm not aware of an external one.
