### ISSUE TITLE
Non-determinism when updating a map that is being iterated over

### ISSUE THREAD

**Issue by peter-edge** [golang/go#18325]
`go version`: go version go1.7.4 darwin/amd64

Code:

```go
package main

import "fmt"

func main() {
	m := make(map[int]int)
	m[1] = 0
	for k, v := range m {
		m[k+k] = v
	}
	fmt.Println(m)
}
```

This should do one of two things:

- Print out a map that is `{1: 0, 2: 0}`
- Never print anything and never return

Instead, it's non-deterministic in terms of how many loops it does:

```bash
$ for i in 1 2 3 4 5 6 7 8 9 10; do go run main.go; done
map[2:0 4:0 8:0 1:0]
map[8:0 16:0 32:0 64:0 1:0 2:0 4:0]
map[2:0 4:0 8:0 16:0 32:0 64:0 128:0 1:0]
map[1:0 8:0 32:0 128:0 256:0 2:0 4:0 16:0 64:0]
map[1:0 2:0 4:0]
map[1:0 2:0]
map[8:0 16:0 32:0 64:0 1:0 2:0 4:0]
map[32:0 1:0 2:0 4:0 8:0 16:0]
map[2:0 4:0 8:0 16:0 32:0 64:0 128:0 1:0]
map[16:0 32:0 64:0 1:0 2:0 4:0 8:0]
```

Throwing an error/panicking if you update a map in place is one choice, updating deterministically is another, but the lack of an error and the non-determinism is concerning.

**Comment by dominikh** [comment]
The behaviour is covered by the spec: 

> If map entries are created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next.

Making it an error is not possible in Go 1 under the backwards compatibility promise. Making it always deterministic would limit possible implementations.

**Comment by peter-edge** [comment]
Ya, we found that right after. Closing.
