### ISSUE TITLE
net/http/httputil: ReverseProxy req.Header copying is unclear

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#18327]
ReverseProxy makes an attempt at not modifying the original req.Header

```go
	// We are modifying the same underlying map from req (shallow
	// copied above) so we only copy it if necessary.
	copiedHeaders := false
```

However it skips the check for `X-Forwarded-For`

```go
outreq.Header.Set("X-Forwarded-For", clientIP)
```

But more importantly, Director is called on the shallow copied req, and the NewSingleHostReverseProxy one modifies `req.Header` without making a new map

```go
		if _, ok := req.Header["User-Agent"]; !ok {
			// explicitly disable User-Agent so it's not set to default value
			req.Header.Set("User-Agent", "")
		}
```

It looks to me like this is useless unless it's consistent. It should either make a new Header map before calling Director, or make no attempt at copying them at all.

See also #18326

**Comment by bradfitz** [comment]
I suppose it should just always copy.

This isn't a regression from Go 1.7 to master, is it? How is this related to #18326?

**Comment by FiloSottile** [comment]
Not a regression, even if 24d8f3fa4b02784af2419eec8a28aee303aae0c5 is a partial fix.

I linked #18326 because I expect it to end up into a discussion of whether you are supposed to modify `req.Header`, which is relevant to this issue. (And also because it's how I found #18326.)
