### ISSUE TITLE
playground: error rates increasing

### ISSUE THREAD

**Issue by davecheney** [golang/go#18322]
I'm sorry for not using the template or having concrete details, but it's hard to link to a failed invocation of the playground. 

Over the last few months I've experienced an increase in failures running playground samples, "error communicating with backend server".

I've experienced this from multiple geographies including Australia, Japan, Korea, Amsterdam, London, and Paris, and others have reported similar results (again anocdotally, I do not have a count of the exact number of reports) so I believe it is not localised to my computers or location. 

Obviously once then compile succeeds the result is cached and the problem masked. 

Have the error rates monitored from the playground been increasing? Can something be done to reverse this trend?

**Comment by kris-nova** [comment]
# My experience from Denver, CO

I have never noticed an issue before.. but I could repeatably create the issue from the [go playground link](https://play.golang.org/p/ZRfp3kn9HA)


With the output as
<img width="536" alt="screen shot 2016-12-14 at 11 57 15 pm" src="https://cloud.githubusercontent.com/assets/13757818/21214652/47f89f44-c259-11e6-8bdc-bbe582c5e0a4.png">

**Comment by odeke-em** [comment]
Same thing from San Francisco running @kris-nova's program in https://github.com/golang/go/issues/18322#issuecomment-267253875,
fails with the same error consistently
<img width="723" alt="screen shot 2016-12-14 at 11 06 38 pm" src="https://cloud.githubusercontent.com/assets/4898263/21214840/251488be-c252-11e6-895a-040b668d8f4a.png">

**Comment by cznic** [comment]
No problems here:

![screenshot at 2016-12-15 11 59 10](https://cloud.githubusercontent.com/assets/729580/21221547/0da67130-c2be-11e6-9484-e9a3f00ef017.png)

**Comment by bradfitz** [comment]
@broady has reported App Engine problems.

I think the plan is to move it off App Engine.

Is that correct, @broady? What are the App Engine problems?

**Comment by broady** [comment]
The old infrastructure ("vm:true") appears to be flaky, and we (me, and the App Engine team) can't figure out why.

It's up and running on the new infrastructure now, so should be more stable. If you see any errors at all, re-open this issue.

Relevant CLs:
https://go-review.googlesource.com/#/c/34558/
https://go-review.googlesource.com/#/c/34559/
https://go-review.googlesource.com/#/c/34560/
