### ISSUE TITLE
cmd/compile: dead pointers kept alive across loop iterations

### ISSUE THREAD

**Issue by mdempsky** [golang/go#18336]
A little while back we noticed that 01bf5cc caused an internal test to start failing due to allocating too much memory. Simplifying, the test is basically:

	var v reflect.Value
	for m := in.pop(); m != nil; m = in.pop() {
		v = reflect.ValueOf(m)
		// ... use v ...

		// Clear out reference to m so it doesn't stay alive during in.pop().
		v = reflect.Value{}
	}

This works as intended when reflect.ValueOf is *not* inlined. But 01bf5cc happened to cause reflect.ValueOf to become eligilble for inlining, and suddenly m was being kept alive during the in.pop() calls.

I've produced two partially minimized repros:

One with //go:noinline that pases: https://play.golang.org/p/Bu1qLfD60c

One without that fails: https://play.golang.org/p/iTNJxtmiSN

The same problem exists in 1.7.3, so targeting for 1.9.

**Comment by mdempsky** [comment]
Experimenting further, the issue can be reproduced even without inlining:

    for m := in.pop(); m != nil; m = in.pop() {
            i := m
            _ = &i  // dummy statement that takes i's address, but doesn't escape it
    }

Here `i` is being kept alive during the `m = in.pop()` PostStmt clause.

Of course, in this case you could add `i = nil` to forcefully clobber the variable. That's not an option with inlined variables though.

Perhaps we need to emit VARKILL instructions for Addrtaken Nodes that don't escape when they exit scope?

**Comment by josharian** [comment]
Finding just the right spot for a VARKILL here seems like @dr2chase cup o' tea.

**Comment by randall77** [comment]
This should now be fixed due to stack tracing (CLs https://go-review.googlesource.com/c/go/+/134155 and https://go-review.googlesource.com/c/go/+/134156)
