### ISSUE TITLE
[go1.8beta2] Investigating bad bad break in docker test suite

### ISSUE THREAD

**Issue by cpuguy83** [golang/go#18347]
### What version of Go are you using (`go version`)?
1.8beta2

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?

Testing 1.8beta on docker's test suite

### What did you expect to see?
Tests actually run

### What did you see instead?

**All** of our integration tests are erroring.

This only happens with beta2. Beta1 had a couple of failures (1 which was fixed).
Beta2 has broken our entire integration suite.
We are still investigating the potential cause, but are turning up short at the moment as there's not much to go on.

I have not reproduced any issue with manual testing, but using the test suite any and every test errors during cleanup with a response from the docker daemon of `page not found`

**Comment by bradfitz** [comment]
What is Docker's tracking bug for this?

**Comment by cpuguy83** [comment]
Just tracking in docker/docker#29030 at the moment.

**Comment by cpuguy83** [comment]
```diff
diff --git a/integration-cli/docker_utils.go b/integration-cli/docker_utils.go
index b87ae2d..1f34d14 100644
--- a/integration-cli/docker_utils.go
+++ b/integration-cli/docker_utils.go
@@ -379,7 +379,9 @@ func unpauseAllContainers(c *check.C) {
 	containerList := strings.Split(containers, " ")
 
 	for _, value := range containerList {
-		unpauseContainer(c, value)
+		if len(value) > 0 {
+			unpauseContainer(c, value)
+		}
 	}
 }
 ```

But not sure what changed that it's causing an issue.

**Comment by dsnet** [comment]
Are you able to git bisect to a given commit that broke it?

**Comment by bradfitz** [comment]
Please provide an update on this. Was this all due to one of your dependencies doing exact string comparisons on an error value from the reflection package? (as I think I saw elsewhere) Which?

**Comment by cpuguy83** [comment]
Ok, I've tracked this to a change we've pulled in since testing 1.8. Both beta1 and beta2 are a problem after this change (which is just to check errors on test cleanups). Still trying to figure out a minimal repro case for the behavior change (1.7.x works with above error checking enabled, 1.8bX does not).

**Comment by rsc** [comment]
@cpuguy83, what Docker commit caused the problem? Maybe something will jump out at us.

Also, what do you mean by "above error checking"? I don't see error checking above; I do see a workaround for empty strings in the result of strings.Split; I commented about that in docker/docker#29030, but I'd still like to understand if and why something changed from 1.7 to 1.8. Thanks.

**Comment by cpuguy83** [comment]
@rsc Error checking is happening via the passed down `c` var, which is go-check's equivalent of `*testing.T`

**Comment by rsc** [comment]
This program changed from Go 1.7 to Go 1.8 and is (I believe) the source of docker's problems.

```
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"os"
)

func main() {
	http.DefaultClient.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		fmt.Printf("redirect %s", req.URL)
		for _, v := range via {
			fmt.Printf(" via %s", v.URL)
		}
		fmt.Printf("\n")
		return nil
	}
	http.HandleFunc("/", show)
	srv := httptest.NewServer(nil)
	r, err := http.Post(srv.URL+"/x//z", "text/plain", bytes.NewReader(nil))
	if err != nil {
		log.Fatal(err)
	}
	if r.StatusCode != 200 {
		log.Fatal("status: " + r.Status)
	}
	io.Copy(os.Stdout, r.Body)
}

func show(w http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(w, "%s %s\n", req.Method, req.URL)
}
```

Before the POST got a redirect and returned that error. Now it follows the redirect, translates to GET, and gets 404. I guess Docker was swallowing the 301 but is now choking on the 404.

```
r$ go1.7 run /tmp/x.go
2016/12/20 10:29:59 status: 301 Moved Permanently
exit status 1
r$ go run /tmp/x.go
redirect http://127.0.0.1:52118/x/z via http://127.0.0.1:52118/x//z
GET /x/z
r$
```

**Comment by cpuguy83** [comment]
Thanks @rsc 
Sorry for the delay on my end tracking this down.

**Comment by rsc** [comment]
@cpuguy83 Can you try the containerList change and then see whether there are more bugs after this one?

**Comment by cpuguy83** [comment]
@rsc Already building.

**Comment by ianlancetaylor** [comment]
I don't see this change called out in the release notes, though it is possible that I misunderstand it.

**Comment by bradfitz** [comment]
It doesn't say enough, but it's there _kinda:

> The Client now supports 307 and 308 redirects. If the redirect requires resending the request body, the request must have the new Request.GetBody field defined. NewRequest sets Request.GetBody automatically for common body types.

I'll send more.

**Comment by bradfitz** [comment]
For the record, 7db996ee77b20b68ee583c65d59be1d81cef9090 (CL 29852) changed `shouldRedirectPost` from only redirecting StatusFound, StatusSeeOther (302 & 303) to also including StatusMovedPermanently (301) in the new func `redirectBehavior`, to fix #9348 and other bugs.

https://tools.ietf.org/html/rfc7231#section-6.4.2 says:

```
6.4.2.  301 Moved Permanently

   The 301 (Moved Permanently) status code indicates that the target
   resource has been assigned a new permanent URI and any future
   references to this resource ought to use one of the enclosed URIs.
   Clients with link-editing capabilities ought to automatically re-link
   references to the effective request URI to one or more of the new
   references sent by the server, where possible.

   The server SHOULD generate a Location header field in the response
   containing a preferred URI reference for the new permanent URI.  The
   user agent MAY use the Location field value for automatic
   redirection.  The server's response payload usually contains a short
   hypertext note with a hyperlink to the new URI(s).

      Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.
```

And from the discussion in #9348, it seems the new behavior is the desired and correct behavior.

**Comment by cpuguy83** [comment]
@bradfitz Works for me. No big deal to update the docker client to handle this better.

**Comment by bradfitz** [comment]
@cpuguy83, Happy 2017. Any update here? Is Docker passing with Go 1.8?

**Comment by cpuguy83** [comment]
Sorry, thought this was closed.
I opened docker/docker#29602 to track changes we need on the docker side.
Docs update LGTM.

**Comment by nieksand** [comment]
Should this be mentioned in the 1.8 release notes?

**Comment by bradfitz** [comment]
@nieksand, it is. See above.

**Comment by nieksand** [comment]
Ah.. my mistake.  All is well!
