### ISSUE TITLE
-buildmode=plugin stopped working in go1.8beta2

### ISSUE THREAD

**Issue by tylertreat** [golang/go#18345]
### What version of Go are you using (`go version`)?

go1.8beta2

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

```
$ go version
go version go1.8beta1 darwin/amd64
$ go build -buildmode=plugin plugin.go

$ go1.8beta2 version
go version go1.8beta2 darwin/amd64
$ go1.8beta2 build -buildmode=plugin plugin.go
-buildmode=plugin not supported on darwin/amd64
```

### What did you expect to see?

`-buildmode=plugin` works with go1.8beta1, so I expected it to work with go1.8beta2. The documentation indicates plugins are supported on darwin.

### What did you see instead?

`-buildmode=plugin not supported on darwin/amd64`

**Comment by bradfitz** [comment]
Yes, it was removed from Darwin after beta1 and before beta2. There were too many bugs we didn't have time to fix before the release. Plugins will be Linux-only for Go 1.8.

**Comment by tylertreat** [comment]
@bradfitz is there an issue tracking plugin support for Darwin (I assume support is still planned)?

**Comment by tylertreat** [comment]
This appears to be it: https://github.com/golang/go/issues/18190

**Comment by baiyunping333** [comment]
so sadly!
