### ISSUE TITLE
path/filepath: HasPrefix should be marked deprecated

### ISSUE THREAD

**Issue by dsnet** [golang/go#18355]
The documentation for [`filepath.HasPrefix`](https://golang.org/pkg/path/filepath/#HasPrefix) says:
> HasPrefix exists for historical compatibility and should not be used.

We should switch this to use the "Deprecated:" tag so that tools can flag new uses of this.

As it is currently implemented, it is misleading because it only does `strings.HasPrefix` and does not actually match on patch segments. Thus, the following reports true, which is surprising:
```go
filepath.HasPrefix("/home/userwrongdir/abc", "/home/user") // This reports true
```

\cc @neild

**Comment by bradfitz** [comment]
Just send it now for Go 1.8. It's only docs.

**Comment by dsnet** [comment]
Opened #18358 to investigate actually fixing this function.

**Comment by RobbieMcKinstry** [comment]
Just checking: this function is deprecated, and there is no alternative? Maybe a regex.Match? I assume that's why there's interest in fixing.

**Comment by bradfitz** [comment]
@RobbieMcKinstry, your comment would be better on an open bug, like #18358. Closed bugs aren't tracked.

**Comment by RobbieMcKinstry** [comment]
Thank you Brad! Still learning! :)
