### ISSUE TITLE
cmd/go: docs to make it more obvious how build tags are meant to be passed

### ISSUE THREAD

**Issue by mrkane27** [golang/go#18351]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/dev/gpuroot"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kp/m9dnkfhx4r9_8dv1cns7m0gh00bkfl/T/go-build113285281=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
Looked for instructions online.

### What did you expect to see?
The same page to contain information about specifying build constraints, and how to pass those via the go tool.
Information on how to pass multiple flags i.e. separated by spaces?

### What did you see instead?
I had to look through source code and tests to find out how multiple tags were passed. The official docs are scarce.
Space-separated tags seems a bit error-prone. If commas are not allowed in tag names, would it be possible to support commas as well?

**Comment by ALTree** [comment]
> The official docs are scarce.

This was fixed by 48d71990722f3cc81305c794d3d3b6d9007770c8

> would it be possible to support commas as well?

#18800 is also about this (well, in that issue they are suggesting to make the tool complain about commas, while you ask for commas support, but that's the same issue: we just need to decided what to do).

**Comment by ALTree** [comment]
Looks like the final decision was to **not** support comma-separated lists. 

16b6bb88ebfbd079a1d0b7c0cef80fa55eaf0211 makes the compiler error on commas. We fixed the doc so that it explains the list is space-separated and we fixed the compiler so that it errors when it's not, so closing this.
