### ISSUE TITLE
proposal: doc: document when symbols were introduced

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#18356]
The standard library is growing more and more, and it's becoming hard to track what is safe to use in backwards-compatible code.

I propose at least functions and classes, when introduced after 1.0 (or 1.4? or in the last 3 major versions? or `¯\_(ツ)_/¯`?) should have a documentation line like

```
// New in Go 1.7.
```

This would be fairly easy to automate.

**Comment by bradfitz** [comment]
I believe there's already a dup bug open about this.

**Comment by bradfitz** [comment]
Dup of #5778
