### ISSUE TITLE
net/http Security issue - no way to send request to IP and verify CN of certificate against Host header

### ISSUE THREAD

**Issue by akamensky** [golang/go#18366]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.7.4 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/akamensky/IdeaProjects/eswift-control"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m9/_w9cqs554d55x_sscy_0mcrm0000gn/T/go-build077409161=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
Example code:
```
package main

import (
	"net/http"
	"fmt"
	"time"
)

func main() {
	client := &http.Client{Timeout: time.Second * 10}
	req, _ := http.NewRequest("GET", "https://104.154.89.105/", nil) // This is a www.badssl.com IP
	req.Host = "www.badssl.com"
	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Printf("%x\n", res.Status)
}
```

### What did you expect to see?
Successfully execute GET request with valid SSL certificate

### What did you see instead?
Failed request "certificate not valid for domain" error

### Comment
This may be a feature request and not a bug, but what I am trying to achieve is to avoid situations when hostname is exposed to any 3rd-party. What happens currently is that giving a hostname in URL will lead to CONNECT %hostname% sent in plaintext. Even if that is changed and connect would use DNS resolution, then it still would be very obvious which domain name is being requested (and even open it to DNS poisoning).

In order to avoid problems above I hope I could just set `Host` header and connect by IP directly (that is of course I must be sure that server IP will stay the same), where certificate would be validate against `Host` header value and not against URL domain name.

I've observed this behavior in some clients, which means that is a possible change.

**Comment by akamensky** [comment]
Just to shed some light on how I came to this issue: I currently working on the application where exposing this information to any 3rd party can compromise security.

**Comment by bradfitz** [comment]
You have to wire this up yourself, depending on what you specifically want. The high-level HTTP client does the typical thing only.

See:
https://golang.org/pkg/net/http/#Transport (specifically the Dial hooks, and `TLSClientConfig`)
and
https://golang.org/pkg/crypto/tls/#Config

It's not exactly clear what you want, though. You're talking about CONNECT, but you didn't mention proxies. You didn't mention SNI, though. I'm not sure what your threat model is. As such, I can't give you specific advice.

This might be best for https://golang.org/wiki/Questions

**Comment by activeshadow** [comment]
@akamensky I think what you want to set is `ServerName` on `tls.Config`.
