### ISSUE TITLE
http.Request setting PostForm manually has no effect

### ISSUE THREAD

**Issue by akamensky** [golang/go#18367]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.7.1 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m9/_w9cqs554d55x_sscy_0mcrm0000gn/T/go-build997471420=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
Use following code snippet to execute request
```
	var httpClient = &http.Client{
		Timeout: time.Second * 10,
	}
	req, _ := http.NewRequest("POST", "https://127.0.0.1:8000/post", nil)
	req.PostForm = url.Values{"email": {email}, "pass":{password}}
	res, err := httpClient.Do(req)
```

Inspect traffic (on receiving server) using tcpdump -> tcpdump -i lo -n port 8000 -A

### What did you expect to see?
Data was sent properly as body and being url encoded

### What did you see instead?
Empty body

### Comment

Common sense is - if the field is exposed, then using it should be expected behavior. Right now only way to assign those values is when creating request using NewRequest and then creating intermediate `bytes.NewBufferString()`

**Comment by akamensky** [comment]
Additionally it will require manually setting `Content-Type` and `Content-Length` Headers.. Sigh...

**Comment by bradfitz** [comment]
This is documented:

https://beta.golang.org/pkg/net/http/#Request.PostForm

>    This field is only available after ParseForm is called.
>    The HTTP client ignores PostForm and uses Body instead.
