### ISSUE TITLE
Go operating system build tags/file suffixes

### ISSUE THREAD

**Issue by redpois0n** [golang/go#18364]
I have some questions about how the Go compiler handles the operating system build tags

A file named `name_windows.go` will only be included when built for Windows, that's straightforward.
Same goes for `name_darwin.go` which is OS X/macOS.

However, there is some unclear names I'd like to get some answers to, since I'm currently writing OS dependent code.

`route_bsd.go` in package [syscall](https://golang.org/src/syscall/), does it build on all BSD flavors?
There are one route.go for each flavor, `route_freebsd.go`, `route_openbsd.go`, `route_netbsd.go`, `route_dragonfly.go`.

Same is for `sockcmsg_unix.go` in [syscall](https://golang.org/src/syscall/), exactly what systems will this be built for? Does the unix flag include darwin and all BSD flavors?

**Comment by cespare** [comment]
@redpois0n see https://github.com/golang/go/wiki/Questions for the ways to ask questions.

In this case https://golang.org/pkg/go/build/#hdr-Build_Constraints is the documentation you're looking for.

**Comment by redpois0n** [comment]
@cespare You misunderstood my question or I did not explain correctly, I am mostly wondering what the unix and bsd build constraints includes

**Comment by cespare** [comment]
@redpois0n I think those names are just conventional. The constraints for those files are listed using build tags in the file.

But please close this issue and let's continue the discussion on one of the forums listed in https://github.com/golang/go/wiki/Questions. We try not to use the issue tracker for questions.

**Comment by redpois0n** [comment]
You are correct. Thank you.
