### ISSUE TITLE
Assign string to string alias inconsistency

### ISSUE THREAD

**Issue by DasJott** [golang/go#18372]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.6.2

### What operating system and processor architecture are you using (`go env`)?
Linux amd64 Ubuntu 16.04

### What did you do?
Having a `type sstring string`, wanted to assing a string. `"such a string"` does work, but not `string("such a string")` nor `word := "this variable"`.

https://play.golang.org/p/AwJsr9fOpQ

### What did you expect to see?
```
word := "Hello"
var foo sstring = word
```

everything's fine

### What did you see instead?
`cannot use word (type string) as type sstring in assignment`

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

See also https://blog.golang.org/constants for some background info.
