### ISSUE TITLE
C function printf under go with linux is not working

### ISSUE THREAD

**Issue by godcong** [golang/go#18384]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
window 10:
GOROOT=D:\go
GOARCH=386
GOOS=windows
CGO_ENABLED=1

linux:
export PATH=$PATH:/usr/local/go/bin

### What did you do?
this is my code:
package main

/*
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
int zooinit(){
	printf("%d",123);
	return 12121;
}
*/
import "C"

import "fmt"
import "time"

func main() {
	//	fmt.Println(C.ZOPERATIONTIMEOUT)
	fmt.Println(C.zooinit())
	time.Sleep(1000)
}

under window 10 it outputs
/*
12121
123
*/

under docker ubuntu 16.10 it only outputs
/*
12121
*/
i think the printf function isn't work

is this an issus?

**Comment by cznic** [comment]
Try `s/time.Sleep(1000)/C.fflush(C.stdout)/` or `s/"%d"/"%d\n"/`, w/o that it seems like WAI to me.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

I agree with @cznic. The C library's default buffering differs between your two environment. I believe Linux is line-buffered by default. Looks like Windows isn't buffered.
