### ISSUE TITLE
XML parser weird behaviour

### ISSUE THREAD

**Issue by ugoud** [golang/go#18386]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/uday/gospace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
Go is mandating that the data variable in struct defining for xml should start with capital letter

Please see code at https://play.golang.org/p/EykZ2v3LG6
and https://play.golang.org/p/MoyzH5eCVF

### What did you expect to see?
I am not sure if there is a mandatory requirement to start data type with capital letter

**Comment by bradfitz** [comment]
This is as designed and as documented. This is because reflect can't set private fields.

For questions about Go, see https://golang.org/wiki/Questions.
