### ISSUE TITLE
template/text: Parse not fully static

### ISSUE THREAD

**Issue by mh-cbon** [golang/go#18382]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/home/mh-cbon/gow/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mh-cbon/gow"
GORACE=""
GOROOT="/home/mh-cbon/.gvm/gos/go1.7"
GOTOOLDIR="/home/mh-cbon/.gvm/gos/go1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build188381695=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
develop.

### What did you expect to see?
change.

### What did you see instead?
tbd.

### actual issue

In template/text.Parse,
the parse operation rely on non static values,
currently the FuncMap,
see here https://golang.org/src/text/template/parse/parse.go?s=1642:1753#L41

It seems to me it is used for only one specific reason,
check at parsing that given func exists in the attached FuncMap.
see here https://golang.org/src/text/template/parse/parse.go?#L705
and https://golang.org/src/text/template/parse/parse.go?#L667

Looks likes the very same test is performed during template execution,
see https://golang.org/src/text/template/exec.go#526

I m thinking to change Parse in order to make it really static.
The signature of that function would change from,
`Parse(text, leftDelim, rightDelim string, treeSet map[string]*Tree, funcs ...map[string]interface{}) (tree *Tree, err error)`
to
`Parse(text, leftDelim, rightDelim string, treeSet map[string]*Tree) (tree *Tree, err error)`

ref https://golang.org/src/text/template/parse/parse.go?#L229

I believe it may be acceptable because,
I think the check done on parse,
could be done by a function which does occur right after the parse phase, not during it.
That function would just have to receive (tree, funcMap),
browse the tree nodes, find IdentifierNodes, test their ident against the funcMap.

The template parse* function would have to be updated, to add function call for this funcMap checker.
https://golang.org/src/text/template/template.go?#L190

Also, it seems the test is duplicated in both exec and parse phases.

I d like this change to happen because i'm looking forward to compile text/template to go code, the current requirement of runtime funcmap values during the parse phase is blocking to reach this goal.

**Comment by bradfitz** [comment]
We can't change existing API in the standard library, per https://golang.org/doc/go1compat.

For questions about Go, see https://golang.org/wiki/Questions. Let's move this discussion to the mailing list first.
