### ISSUE TITLE
cmd/pprof: weblist filtering not working

### ISSUE THREAD

**Issue by benbjohnson** [golang/go#18385]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go 1.8 beta2

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/benbjohnson/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/56mhx0pn5vl_h2hzd90v9d1c0000gn/T/go-build341403676=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

```sh
# In terminal #1
$ go install github.com/influxdata/influxdb/cmd/influxd
$ influxd
```

```sh
# In terminal #2
$ go tool pprof ~/go/bin/influxd http://localhost:8086/debug/pprof/heap
(pprof) weblist .
```

### What did you expect to see?

A listing of functions in my web browser.

### What did you see instead?

The `weblist` command returns "`no samples found on routines matching: .`" in 1.8beta2.

It works properly in Go 1.7. The `list` command in 1.8beta2 also works correctly.

**Comment by dsnet** [comment]
\cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
When testing with a simple program the weblist command seems to work.

Will take a look at the influxdata code.

**Comment by benbjohnson** [comment]
@ianlancetaylor It doesn't seem to be specific to `influxdb`. I just tried it on some other packages with the same result. Perhaps it's just a fluke on my system.

**Comment by ianlancetaylor** [comment]
@benbjohnson Can you test with https://play.golang.org/p/eOlUFUFGAR ?  That one worked for me.

**Comment by ALTree** [comment]
I can reproduce this on tip.

let 
`go = version go1.7.3`
`gotip = devel +0ef4815150 Wed Dec 21`

Now:

```
$ cd src/strconv
$ gotip test -c
$ ./strconv.test -test.bench=FormatFloat/Slowpath64 -test.cpuprofile=cpu.prof
```

using `tip` pprof:

```
$ gotip tool pprof ./strconv.test cpu.prof 
Entering interactive mode (type "help" for commands)
(pprof) weblist
no samples found on routines matching: .
```

but go 1.7 pprof works:

```
$ go tool pprof ./strconv.test cpu.prof 
Entering interactive mode (type "help" for commands)
(pprof) weblist
[actually opens the webprofile]
```

**Comment by ALTree** [comment]
Looks like it has been broken by [CL 23781](https://go-review.googlesource.com/#/c/23781/) (cmd/pprof: instruction-level granularity in callgrind output).

**Comment by ianlancetaylor** [comment]
CC @prattmic @rauls5382
