### ISSUE TITLE
Templating is broken.

### ISSUE THREAD

**Issue by NikosEfthias** [golang/go#18399]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
tested on both 1.7.1 and 1.7.4

### What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOBIN="/home/nikos/projects/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nikos/projects/go"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965913370=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
please see the the article [here](http://stackoverflow.com/questions/41255403/golang-templating-does-not-work-properly?noredirect=1#comment69711368_41255403)
in addition to this {{else if}} also doesnt work 
as here 
```html
<script>
			  {{ if .PassChange }}
			  swal("{{.Lang.Success}}", "{{.Lang.PleaseLogin}}", "success")
			  {{ else if .UserExists }}
			  swal("{{.Lang.Fail}}", "{{.Lang.AlreadyMember}}", "error")
			  {{ end }}
</script>
```

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by NikosEfthias** [comment]
@bradfitz this is a bug not a question if you read what i wrote above everything is proper but templating wont render so how come this is just a question i dont ask how to use templating

**Comment by bradfitz** [comment]
It's not in the format of a typical bug report. A good bug report includes complete but minimal reproduction code to demonstrate the problem, and describe problems, expectations, and actual results. You deleted those sections from the issue template. You can't just ignore the bug report template and refer to a stackoverflow page which is also lacking detail.

I suggest you discuss this on the mailing list and come back when there's a detailed bug report to be filed.

**Comment by NikosEfthias** [comment]
well so this is how google works if something is not in the shape you expect dont even check that because the cover is more important than the actual problem . Correct ? @bradfitz . Above the problem is entirely described i just didnt want to write the same issue over and over again .

**Comment by bradfitz** [comment]
Sorry, if you don't want to write a self-contained and understandable bug report, I guess we can't help.
