### ISSUE TITLE
website: golang.org/doc/install#help should mention Slack

### ISSUE THREAD

**Issue by hitjim** [golang/go#18406]
I noticed this after downloading go.  at [the install's help section](https://golang.org/doc/install#help) it only lists IRC for getting real-time help.  While IRC is nice, it seems that Slack should get a mention here, as seen at the [help page](https://golang.org/help/).

Not sure how much more duplication is appropriate?  This seemed like the most important addition.

**Comment by bradfitz** [comment]
Actually, I got this.
