### ISSUE TITLE
net/http/httptest: Using NewTLSServer is not intuitive

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#18411]
### What version of Go are you using (`go version`)?
`go1.7.4`

### What operating system and processor architecture are you using (`go env`)?
`Linux/amd64`

### What did you do?
I tried to figure out how to use `httptest.NewTLSServer` and found it cumbersome. I submitted an example of the boilerplate required in my CL to improve documentation, https://go-review.googlesource.com/#/c/34639/, but the consensus is that this API should be improved for 1.9 instead of patching poor API with an example in documentation.

Here's an example of a working `NewTLSServer` in use:

```go
func ExampleNewTLSServer() {
	ts := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Hello, client")
	}))
	defer ts.Close()

	cert, err := x509.ParseCertificate(ts.TLS.Certificates[0].Certificate[0])
	if err != nil {
		log.Fatal(err)
	}

	certpool := x509.NewCertPool()
	certpool.AddCert(cert)

	client := http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs: certpool,
			},
		},
	}

	res, err := client.Get(ts.URL)
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()

	greeting, err := ioutil.ReadAll(res.Body)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%s", greeting)
	// Output: Hello, client
}
```

### What did you expect to see?
An easy to use TLS server for HTTPS testing.

### What did you see instead?
A server that requires accessing and parsing TLS config internals for proper TLS authentication to work.

**Comment by johanbrandhorst** [comment]
I will look at this as an expansion to my CL https://go-review.googlesource.com/#/c/34639/

**Comment by LeonineKing1199** [comment]
This needs to be added to the official `httptest` docs on the Go site. It's amazingly helpful!

**Comment by johanbrandhorst** [comment]
@LeonineKing1199 in Go 1.9 it will be much easier to use the `httptest.NewTLSServer`, so the docs will not be updated for the old behaviour.

See https://tip.golang.org/pkg/net/http/httptest/#example_NewTLSServer for an example of the new testing API coming in 1.9.
