### ISSUE TITLE
gccgo: spurious redefinition error for anon struct 

### ISSUE THREAD

**Issue by thanm** [golang/go#18414]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

$ gccgo --version
gccgo (GCC) 7.0.0 20161222 (experimental)

This is gcc trunk (svn revision 243890)

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"

### What did you do?

From Cherry:

// p1.go
package p1

type S struct {
        X struct{ _ struct{} }
}

// p.go
package p

import "p1"

type T struct {
        A  *p1.S
        X  struct{ _ struct{} }
}

Build first package "p1" with gccgo, then package "p".

### What did you expect to see?

Compile cleanly.

### What did you see instead?

"go build -compiler gccgo" succeeds for package p1, however for package "p" the following happens:
$ go build -compiler gccgo .
<built-in>: error: redefinition of ‘S1__See$hash’
<built-in>: note: previous definition of ‘S1__See$hash’ was here
<built-in>: error: redefinition of ‘S1__See$equal’
<built-in>: note: previous definition of ‘S1__See$equal’ was here
<built-in>: error: redefinition of ‘S1__See$hash’
<built-in>: note: previous definition of ‘S1__See$hash’ was here
<built-in>: error: redefinition of ‘S1__See$equal’
<built-in>: note: previous definition of ‘S1__See$equal’ was here

**Comment by thanm** [comment]
Sequence of events seems to be as follows:

Type "S" is imported from package 'p1'. This creates the top-level structure type but also creates an anonymous struct type corresponding to the type of "X". Compiler generates hash and equal functions by invoking Type::specific_type_functions, doesn't find anything, so creates new functions and installs them into Type::type_functions_table. These functions are named via Gogo::pack_hidden_name, meaning that they are given a name something like "./p.S1__See$hash" (package path combined with "$" and mangled name).

Next the compiler processes the type T, which results in the creation of another anonymous struct type (again corresponding to "struct{ _ struct{} }"). Although this type is structurally identical to the one imported from "p1", it winds up as a separate Type object. This means that when Type::specific_type_functions is called on it, lookup fails and we create new hash/equal functions. Again Gogo::pack_hidden_name is called, and so the new functions get the same name as the ones created previously (resulting in naming collision).

Possible fixes:

- change Type::specific_type_functions() so that it compares Type's structurally as opposed to using pointer equality (which would mean we could share the functions)

- use something other than Gogo::pack_hidden_name (or in addition to it) when choosing names for the functions, so as to avoid the naming collision

**Comment by thanm** [comment]
Correction -- Type::specific_type_functions() is already doing a structural comparison. The compare is failing due to the difference in the field names between the two types.

**Comment by ianlancetaylor** [comment]
I think the fix is that `Struct_type::do_mangled_name` should not call `Gogo::unpack_hidden_name(p->field_name())`.  It should use `p->field_name()` directly.

**Comment by thanm** [comment]
This seems to work (although I needed to post-process the field name with Gogo::pkgpath_for_symbol.
I thought about adding a flag of some sort to Type::is_identical to control whether it compares struct field names, but that would have been good deal more code.
