### ISSUE TITLE
cmd/dist docs: Unclear which versions of ARM work for which OSes

### ISSUE THREAD

**Issue by mholt** [golang/go#18418]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/matt/Dev"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/86/75b471wx6sn8bjtd4jz48kbm0000gn/T/go-build807743432=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
Tried to cross compile to ARM version 5 for operating systems other than Linux. The build succeeds, but there is some confusion as to whether ARM 5 is supported on OSes other than Linux; see thread here: https://twitter.com/bradfitz/status/812063327564099584 (/cc @bradfitz)

The `xgogetarm()` function [here](https://golang.org/src/cmd/dist/util.go) makes it seem that ARMv5 is the only supported ARM version for Open/FreeBSD.

### What did you expect to see?
An error if that ARM version is not supported for that OS

### What did you see instead?
A successful build

**Comment by davecheney** [comment]
All other operating systems require arm6 or higher.

**Comment by minux** [comment]
I've updated https://golang.org/wiki/GoARM page for this.

Please note that the return value from xgetgoarm in cmd/dist doesn't mean
the
supported ARM architecture version.

GOARM is overloaded to mean both minimum required ARM architecture version,
and VFP support status (5 = software FP, 6 = VFPv1, 7=VFPv3).

As Dave has mentioned, on non-Linux platforms, only ARMv6K or above is
supported. But some operating system has broken VFP support, thus we
force GOARM=5 on those operating systems.

**Comment by mholt** [comment]
That's splendidly helpful @minux, thank you for the clarifications -- and the edit on the wiki is useful as well! I'm satisfied with this, so I'll close the issue.
