### ISSUE TITLE
Add option to force net/http request to resolve names to specific ip address families

### ISSUE THREAD

**Issue by laplaceon** [golang/go#18422]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.3

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
I'm trying to use the net/http library to make requests to certain pages, resolving the names with a certain ip family.

### What did you expect to see?
An option to specify the ip family to use.  I can do this in curl using the -6 flag (for ipv6) and the -4 flag (ipv4). I have a dual stack machine, but I can only access the pages over ipv6.

### What did you see instead?
I can use the following code:

`http.DefaultTransport.(*http.Transport).DialContext = func(ctx context.Context, _, addr string) (net.Conn, error) {
// or tcp4
return dialer.DialContext(ctx, "tcp6", addr) 
}`

to switch the default network that http library connects to. In my testing, this doesn't work that well as I can not quickly switch between ipv6 and ipv4 using this method.

I have tried using andelf's libcurl binding library, but that has pretty much no documentation and when using it, it provides inconsistent results. I could also try to use the os/exec library to execute curl commands but that idea seems to be too complex for this simple issue.

**Comment by minux** [comment]
Isn't setting DualStack field in https://golang.org/pkg/net/#Dialer
to true in the http Transport does what you want automatically?

Setting the default transport is not recommended. And what
does not work when changing the DefaultTransport?

If you're just asking a question, please see
https://golang.org/wiki/Questions.
If you're reporting a bug, please include more information. What doesn't
work?
We're not going to add a ipv4/ipv6 to top-level net/http interfaces as I
believe
low-level interface already provides such flexibility.

Thanks.

**Comment by laplaceon** [comment]
DualStack might do this automatically,  but in the case where a name resolves to both ipv4 and ipv6 addresses, I would like to choose which address to use. As for the DefaultTransport, I had set up a test where a bool variable determined which family to resolve to. Sometimes switching the bool variable didn't change the page resources I was getting. The page I was accessing in particular displays different data depending on if you accessed over ipv6 or ipv4

**Comment by minux** [comment]
I think the behavior you're seeing is that net/http reuses cached
connections from previous connections to the same server.

If you want ultimate control, use dedicated net/http.Client
for different tests.

**Comment by laplaceon** [comment]
Assuming those aren't the only solutions to this problem, I should've asked a question before opening this feature request issue. This should be closed.
