### ISSUE TITLE
[Feature Request] Shorter error catching

### ISSUE THREAD

**Issue by graarh** [golang/go#18425]
Lets look at the common function

```go
func MyFunc() (*SomeStruct, int, error) {
    data, err := callSomething()
    if err != nil {
        return nil, 0, err
    }
    return data, callSomethingOther(), nil
}
```

the 

```go
if err != nil {
   return <default type value>, <default type value>, err
}
```

is the most common error checking code. But it can be removed by adding syntax construction like

```go
func MyFunc() (*SomeStruct, int, error) {
    data, <err> := callSomething()
    return data, callSomethingOther(), nil
}
```

that means if the err is not nil, exit from the function and return default type values except error value. It should not compile if more than one error type returned. 

It is pretty clean for reading, and removes a lot of code lines with identical error checking.

**Comment by as** [comment]
This is a common suggestion, but Go doesn't do things this way. Just use the if statement. If shorter code is your goal, name the returns in the parameter list and use a bare return.

func a() (b, c int, err error) {
   If err = mayfail(); err != nil {
      return
   }
   return 1, 2, nil
}

**Comment by minux** [comment]
This has been discussed numerous times in the past. Please search the
mailing list archive for previous discussions.

The short answer is no, we shouldn't add syntax auger for this.

**Comment by bradfitz** [comment]
Before closing this, let's make sure we have an index of past discussions. Telling people to search the history is convenient but unsatisfying for the OP.

**Comment by graarh** [comment]
Thanks for the answers, I will search the archive.

**Comment by bradfitz** [comment]
I filed #18430 for more docs.
