### ISSUE TITLE
Understanding and output of "slices"

### ISSUE THREAD

**Issue by rxa1031** [golang/go#18435]
go version go1.7.4 windows/amd64
Windows 10 64 bit

Executed / Ran code present at link http://127.0.0.1:3999/moretypes/7

I first raised a concern about the behavior that I assume is erroneous, under tour Issues, as I observed them while using the tour. Link below:
[https://github.com/golang/tour/issues/133](url)

I feel however as these issues are related with go language, hence, submitting the issue under go issues.

As a user / coder, I expect to use a syntax that is more generic. I expect that if both the inputs are of same type, then their permitted first value should be same. Please refer to example where I have used N and M to discuss the issue.

Also please help me understand whether other observations are bugs that need to be fixed?

Issue details below:

primes := [6]int{2, 3, 5, 7, 11, 13}

used in "slices" explanation present on "tour" at location / url / Context: http://127.0.0.1:3999/moretypes/7

Various observations:

Observation 1. Let us assume we want to slice value from "primes" array. Hence, we will write some thing like below, with N and M being two integer numbers:

var s[]int = primes[N:M]

where:
N = Position of the first number to be copied to slice. Here we use C style reference, hence the position count starts from 0
There is however confusion about what value of M should be used:
i. M can be a numeric number that informs how many values need to be copied
ii. M can be the position of the last number that should be a part of the slice:
a. assuming that the first value in the array is at position 0
b. assuming that the first value in the array is at position 1

Based on shared example for M the description used is ii.b

Query:
Why cannot N and M count from 0? Why does N start count from 0 and M from 1?
Why cannot we use M as the number of elements we want to keep in slice?

Observation 2. Printing value of "var s []int = primes[4:4]" prints [] and does not throw error. Is there a reason to come up with this behavior / output?

Observation 3. Also why error is not thrown for "var s[]int = prime[6:6]" (as the permitted values for N are 0 through 5)?

The details / information provided in slices section should elaborate on above observations. Also in case the Observations 2 and 3 are some kind of bug, then they must be fixed.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
