### ISSUE TITLE
Is there has a graceful way to refactor interface.

### ISSUE THREAD

**Issue by leaxoy** [golang/go#18436]
Go is different with java.
In old java, if we change an interface, we must change classes which implement this interface.
In recent version, we have default method in interface.

But in go, we implement an interface implicitly.
If I change an interface, the implement code will broken.
Is there any way without either broken old code nor change implements to refactor an interface?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
