### ISSUE TITLE
golang does not offer ways to use ~/ in source code

### ISSUE THREAD

**Issue by aurelien-git** [golang/go#18443]
###
go version go1.7.4 linux/amd64

### 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aurelien/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build289559283=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### 
     package main
 
     import (
            "fmt"
            "os"
            "io/ioutil"
            "log"
      )

      func main() {
           // part to ask the question and get the input                                                                                            
           fmt.Print("Which file would you like to read?: ")
           var input string
           os.ExpandEnv("$HOME/file")                                                                                                               
           fmt.Scanln(&input)
 
          // part to give the output                                                                                                               
          f, err := os.Open(input) // Open the file                                                                                                
          if err != nil {
                  log.Fatalln("my program broken")
           }

           defer f.Close() // Always close things open                                                                                              

           bs, err := ioutil.ReadAll(f)
           if err != nil {
                    log.Fatalln("my program broken")
           }

           // part to print the output                                                                                                              
           // fmt.Println() // %s convert directly in string the result                                                                             
           fmt.Printf("%s", bs)
        } 

### What did you expect to see?
I expect to be able to request the a file in ~/

### What did you see instead?
2016/12/28 13:52:08 my program broken
exit status 1

**Comment by cznic** [comment]
Try something like
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"encoding/hex"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatalf("%s: expected one argument", os.Args[0])
	}

	f, err := os.Open(os.Args[1]) // Open the file
	if err != nil {
		log.Fatal(err)
	}

	defer f.Close()

	bs, err := ioutil.ReadAll(f)
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Printf("%s", hex.Dump(bs))
}
```

```bash
jnml@4670:~/src/tmp/20161228$ echo bar > ~/foo
jnml@4670:~/src/tmp/20161228$ ./20161228 ~/foo 
00000000  62 61 72 0a                                       |bar.|
jnml@4670:~/src/tmp/20161228$ ./20161228 ~/
2016/12/28 14:01:57 read /home/jnml/: is a directory
jnml@4670:~/src/tmp/20161228$ 
```

**Comment by aurelien-git** [comment]
If i do that:
$ go run gocat2.go 
2016/12/28 14:09:36 /tmp/go-build654268849/command-line-arguments/_obj/exe/gocat2: expected one argument
exit status 1
aurelien@icecloud:~/git/go-experimentations/gocat2$ go run gocat2.go ~/bob
00000000  68 6d 6d 20 68 6d 6d 0a                           |hmm hmm.|

**Comment by aurelien-git** [comment]
but without the hex.dump it works fine ... now I need it to works as a request of the user that says ~/ in the terminal not directly on execution of the program

**Comment by cznic** [comment]
Wherever possible, do not ask the user to input at runtime what could have been passed on the command line. That keeps the command easily scriptable/able to run autonomously.

Anyway, if you want to interpret correctly arguments like `~/` (which is BTW a directory), then you have to parse the input and expand it like the shell does.

I suggest to take this to the mailing list, it's not a bug.

**Comment by aurelien-git** [comment]
ok cznic, thanks for your help
