### ISSUE TITLE
x/tools/cmd/godoc: indentation stripped from raw string literals in example blocks

### ISSUE THREAD

**Issue by biztos** [golang/go#18446]
In code examples (e.g. `foo_examples_test.go`), leading whitespace is stripped from lines of a string declared with backticks, e.g.:

```go
func Example() {
	foo := `One
    Two
Three`
	fmt.Println(foo)
	// Output:
	// One
	//     Two
	// Three
}
```

That will be rendered as follows by godoc:

```html
<div class="expanded">
		<p class="exampleHeading toggleButton">▾ <span class="text">Example</span></p>
		
		
		
			<p>Code:</p>
			<pre class="code">foo := `One
Two
Three`
fmt.Println(foo)
<span class="comment"></pre>
			
			<p>Output:</p>
			<pre class="output">One
    Two
Three
</pre>
			
		
	</div>
</div>
```

...ergo the code will appear without the crucial indentation in the string:

```
foo := `One
Two
Three`
fmt.Println(foo)
```

This bug is present in `godoc` and also at godoc.org despite the latter rendering code blocks quite differently.

Answers to the questions:

### What version of Go are you using (`go version`)?

    go version go1.7 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/Users/frost/go"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vd/dv4ywnzd0gq3gsv6_sfq9nv80000gn/T/go-build153742415=/tmp/go-build -gno-record-gcc-switches -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"

### What did you do?

Used a multi-line string declared with backticks in a code example for my
project [frostedmd](https://github.com/biztos/frostedmd).

The string has meaningful indentation describing a code block in Markdown,
and the bug (or an identical bug) can be seen in action on Godog.org here:

https://godoc.org/github.com/biztos/frostedmd#ex-package

### What did you expect to see?

The string correctly indented in the code block of the example documentation.

### What did you see instead?

The string with leading whitespace stripped from indented lines, thus making
the example invalid.

**Comment by dhananjay92** [comment]
Looks like, it's because [`example_htmlFunc()`](https://github.com/golang/tools/blob/e5f9a3deee5b06348b13f525a32018b324159594/godoc/godoc.go#L589) and [`example_textFunc()`](https://github.com/golang/tools/blob/e5f9a3deee5b06348b13f525a32018b324159594/godoc/godoc.go#L555) try to unident function block by replacing `"\n<4 spaces>"` with `"\n"`. That replacement ends up removing indentation from backticked-string too.

Value of `code`, before:
```
{
    foo := `One
        Two
    Three
Four`
    fmt.Println(foo)
    <span class="comment">// Output:</span>
    <span class="comment">// One</span>
    <span class="comment">//     Two</span>
    <span class="comment">// Three</span>
}
```
and after:
```
foo := `One
    Two
Three
Four`
fmt.Println(foo)
<span class="comment">
```

Also there's a side issue that it retains the last `<span class="comment">`.
