### ISSUE TITLE
Bytes Buffer WriteTo returns a int64 instead of an int

### ISSUE THREAD

**Issue by dannin** [golang/go#18444]
Just wondering why many of the WriteTo methods have a return int, error. But Bytes Buffer returns int64?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

int is used for the size of in-memory things. len, Write, Red, etc. But things that can loop and/or overflow an int use int64 (Copy, WriteTo, FileInfo.Size, etc).

**Comment by dsnet** [comment]
The reason is that is because the WriteTo signature is matching the io.WriterTo interface.

Thanks for the interest in Go, but questions are probably better asked in one of the locations in: https://golang.org/wiki/Questions.

**Comment by dsnet** [comment]
Derp. @bradfitz beat me.
