### ISSUE TITLE
cmd/vet: remove check for trailing newline in Println

### ISSUE THREAD

**Issue by dsnet** [golang/go#18445]
One of the requirements for a vet check is correctness.

Currently, the vet tool has a [check for trailing "\n" in `fmt.Println`](https://github.com/golang/go/blob/662d25351542d624f397bb0a83ff1c0ca38b6428/src/cmd/vet/print.go#L661). It doesn't seem like this is a matter of correctness, but rather of style. Should this check be moved from `vet` to `lint`?

\cc @robpike

**Comment by robpike** [comment]
I would like to leave it in, under the unwritten "venerable" criterion. It fits in well with the existing Printf checks, some others of which are also arguably less clearly wrong. But in practice, it does find errors, at least in my experience.
