### ISSUE TITLE
runtime: use monotonic time on darwin

### ISSUE THREAD

**Issue by gabriel** [golang/go#18455]
### What version of Go are you using (`go version`)?
```
go version go1.7.4 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vm/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y9/b0pxmq754gn9spczf1cw_sq80000gn/T/go-build998056904=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

If you have a loop with time.Sleep(time.Second) and you set the clock back (for example, an hour), the time.Sleep will hang for that amount of time (an hour), instead of 1s.

Run this:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for {
		fmt.Printf("Sleeping 1s (%s)\n", time.Now())
		time.Sleep(time.Second)
	}
}
```

And then set the clock back an minute or hour, or however much time you want it to hang.

### What did you expect to see?

I expect time.Sleep not be affected by clock changes (or skew).

### What did you see instead?

The `time.Sleep` will hang (for a minute or however long you set the clock back).

**Comment by gabriel** [comment]
Some discussion here about this:
https://groups.google.com/forum/#!msg/golang-dev/gVFa7DC8UI0/3gfW_2bV1U4J

**Comment by gabriel** [comment]
https://github.com/golang/go/issues/6007

**Comment by bradfitz** [comment]
Thanks for filing.

**Comment by gabriel** [comment]
Another related/same issue: https://github.com/golang/go/issues/12914

**Comment by ayanamist** [comment]
I'm suffering the same issue under linux
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build850130315=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by namsral** [comment]
Possible fix by using `mach_absolute_time` for `runtime.nanotime` as mentioned in https://github.com/golang/go/issues/17610

**Comment by bradfitz** [comment]
@namsral, thanks for pointing out that this is a dup of #17610. I'll close this one.
