### ISSUE TITLE
http.Server always responses with http/1.1!

### ISSUE THREAD

**Issue by mziraki** [golang/go#18462]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
os: windows
arch: amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
````golang
package main

import (
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		w.Write([]byte("This is an example server.\n"))
	})
	log.Fatalln(http.ListenAndServeTLS(":443", "certificate.crt", "private.key", nil))
}
````

### What did you expect to see?
http/2 response in google chrome

### What did you see instead?
http/1.1 response in google chrome even with sample code that has
````golang
srv := &http.Server{
	Handler:      r,
	Addr:         configs.DefaultPort,
	ReadTimeout:  time.Minute,
	WriteTimeout: time.Minute,
	TLSConfig: &tls.Config{
		NextProtos: []string{"h2"}, // this line
	},
}
````
BTW: https://http2.golang.org/ in google chrome, firefox & edge for desktop shows that http2 is disable incorrectly, but in google chrome & firefox in mobile works fine! and I double-checked my browser's flags & test it in 2 PCs

**Comment by bradfitz** [comment]
This bug report is inconsistent. There are two totally different code fragments.

Then I also don't understand the last bit about http2.golang.org. It works fine for me. What is "disable incorrectly" about it?

I think this is best for a question to the mailing list. See https://golang.org/wiki/Questions.

**Comment by mziraki** [comment]
@bradfitz I cleaned up my question, can you check it again, please. this issue affected my project performance because of http/1.1 responses

**Comment by bradfitz** [comment]
Your updated bug report is no longer inconsistent, but it's also not very useful as a bug report, since it lacks so much information. The code you now cite (for the record: currently just Hello World http.ListenAndServeTLS) should work, and has tests making sure it works. So it's the problem with your client or how you're determining what the protocol version is.

I think this is best discussed on the mailing list (see https://golang.org/wiki/Questions). There is nothing actionable here as a bug report.

**Comment by mziraki** [comment]
@bradfitz I asked my question here because I thought this problem occurred because google chrome dropped NPN support and golang http package uses NPN to switch to http/2
can this be my client problem that you referred to?

**Comment by bradfitz** [comment]
That is not the issue. Go has done ALPN for over two years (4 releases) now, since d0e255f259b106ecb6f4663bb179e0cbdc7b96cd
