### ISSUE TITLE
Go race detector false positive

### ISSUE THREAD

**Issue by jeffizhungry** [golang/go#18463]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/jeffreyh/gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jeffreyh/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
```
➜  testrace got -race
=== RUN   TestWorker
--- PASS: TestWorker (0.00s)
=== RUN   TestWorker2
--- PASS: TestWorker2 (0.00s)
=== RUN   TestRealFileFunc
--- PASS: TestRealFileFunc (0.00s)
=== RUN   TestTestFileFunc
--- PASS: TestTestFileFunc (0.00s)
PASS
==================
WARNING: DATA RACE
Read at 0x000000238000 by main goroutine:
  sync/atomic.LoadInt32()
      /usr/local/go/src/runtime/race_amd64.s:206 +0xb
  testing.coverReport()
      /usr/local/go/src/testing/cover.go:94 +0x291
  testing.after()
      /usr/local/go/src/testing/testing.go:879 +0x162
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:752 +0x396
  main.main()
      _/Users/jeffreyh/testrace/_test/_testmain.go:106 +0x2f8

Previous write at 0x000000238000 by goroutine 8:
  _/Users/jeffreyh/testrace.(*Worker).run()
      _/Users/jeffreyh/testrace/_test/_obj_test/race.go:7 +0x57

Goroutine 8 (finished) created at:
  _/Users/jeffreyh/testrace.TestWorker()
      /Users/jeffreyh/testrace/race_test.go:18 +0x5c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
==================
WARNING: DATA RACE
Read at 0x000000238004 by main goroutine:
  sync/atomic.LoadInt32()
      /usr/local/go/src/runtime/race_amd64.s:206 +0xb
  testing.coverReport()
      /usr/local/go/src/testing/cover.go:94 +0x291
  testing.after()
      /usr/local/go/src/testing/testing.go:879 +0x162
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:752 +0x396
  main.main()
      _/Users/jeffreyh/testrace/_test/_testmain.go:106 +0x2f8

Previous write at 0x000000238004 by goroutine 12:
  _/Users/jeffreyh/testrace.realfilefunc()
      _/Users/jeffreyh/testrace/_test/_obj_test/race.go:12 +0x57

Goroutine 12 (finished) created at:
  _/Users/jeffreyh/testrace.TestRealFileFunc()
      /Users/jeffreyh/testrace/race_test.go:27 +0x42
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
coverage: 0.0% of statements
Found 2 data race(s)
exit status 66
FAIL	_/Users/jeffreyh/testrace	1.019s
```

```go
package testrace

type Worker struct {}

func (w *Worker) run() {}

func realfilefunc() {}
```

```go
package testrace

import "testing"

type Worker2 struct {}

func (w *Worker2) run() {}

func testfilefunc() {}

func TestWorker(t *testing.T) {
    w := &Worker{}                                                                  
    go w.run()
}

func TestWorker2(t *testing.T) {
    w := &Worker2{}
    go w.run()
}

func TestRealFileFunc(t *testing.T) {
    go realfilefunc()
}

func TestTestFileFunc(t *testing.T) {
    go testfilefunc()
}
```

### What did you expect to see?
I didn't expect any race condition errors.

### What did you see instead?
I'm running unittests with the -race flag for a larger program, but I boiled the issue down to this. Creating a struct with one method, then attempting to run that method in a go routine causes the race detector to go off.

I'm aware I could be missing something obvious, but what I don't understand is why the race detector only fires when I do this for structs created in non *_test.go files.

TestWorker1 triggers the race detector, while TestWorker2 does not.

This applies to free standing functions as well.

**Comment by bradfitz** [comment]
What is `testrace got -race`? This looks like a race on code coverage code. Does this only happen when using code coverage? What about `-covermode=atomic`? Or are you overriding that? It should be the default in `-race` mode.

**Comment by jeffizhungry** [comment]
Ahhh it's an alias that I use ```alias got="go test -v -timeout 30s -covermode=count"```. I didn't realize there was that nuance. Thanks!
