### ISSUE TITLE
x/net/bpf: disassemble load extension to type LoadExtension

### ISSUE THREAD

**Issue by breml** [golang/go#18469]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux, amd64

### What did you do?

Disassemble bpf instructions including `ld rand` (load bpf extension rand).

### What did you expect to see?

`ld rand` should be disassembled to `bpf.LoadExtension{Num:56}`.

### What did you see instead?

`ld rand` was disassembled to `bpf.LoadAbsolute{Off:0xfffff038, Size:4}`.

CC: @danderson, @mikioh, @mdlayher

**Comment by mdlayher** [comment]
Nice, thanks for the quick CL.  Unfortunately, I'm not well-versed in the assembly and disassembly portions, so I'll leave this for @danderson and @mikioh.
