### ISSUE TITLE
Convert json with optional naming policy

### ISSUE THREAD

**Issue by Luolc** [golang/go#18467]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/LuoLiangchen/personal/develop/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tv/jxx18j9925v9ct0l75c1rtb00000gn/T/go-build236813399=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?

----------------

When parsing json string, we often get a json with key like "user_id", "updated_at". I mean, lower case letters with underscores.
But the field name of a struct is often like "UserId", "UpdatedAt".
In this case, we are not able to parse a json straightly. It is really inconvenient, even if we use a tag. 

As a reference, the java lib gson implements this feature. It will be great if we could parse json with optional naming policy as well :D
```
public static final FieldNamingPolicy LOWER_CASE_WITH_UNDERSCORES
Using this naming policy with Gson will modify the Java Field name from its camel cased form to a lower case field name where each word is separated by an underscore (_).
Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":

someFieldName ---> some_field_name
_someFieldName ---> _some_field_name
aStringField ---> a_string_field
aURL ---> a_u_r_l
```

**Comment by bradfitz** [comment]
The encoding/json package does not have such a hook. You have to specify the names of fields, sorry.

For questions about Go, see https://golang.org/wiki/Questions.
