### ISSUE TITLE
How to run 2 bat file in same server program?

### ISSUE THREAD

**Issue by shageeth** [golang/go#18474]
Actually i want to run 2 bat scripts , first script will set a system variable[set NEWPATH="E:/Some"] and second script will show the path of that variable(echo %NEWPATH%). this is not working with the same server at first time , when i restart server that will show the path otherwise it'll show nothing. so can anyone help me on that? 

Thanks in advanse.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
