### ISSUE TITLE
html/template;(?:) makes me feel annoyed 

### ISSUE THREAD

**Issue by forsaken628** [golang/go#18475]
### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/michael/GoProjects"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d5/3m7zltl5583b69_0p77y9j680000gp/T/go-build213418470=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### What did you do?
https://play.golang.org/p/sFeuAKks-4
### What did you expect to see?
 Unescape Text 
```
<script type="text/tpl"><label></label><div class=""><div class=".$^&amp;*()"></script>
```
### What did you see instead?

weird (?:)

**Comment by mvdan** [comment]
Why did you re-file this? #18466

**Comment by bradfitz** [comment]
Please don't file this again because we closed your last report.

As I said before, for questions about Go, see https://golang.org/wiki/Questions.

If the mailing list agrees it's a bug, somebody can file a detailed bug report following the issue template.
