### ISSUE TITLE
the "rpc_call" error does not return the go-inside custom error type which implement error interface, like "PathError", which will cause method like os.IsNotExist is unusable

### ISSUE THREAD

**Issue by KevinTHU** [golang/go#18472]
### What version of Go are you using (`go version`)?
go version go1.6.3 linux/amd64
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/hexin/go"
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
### What did you do?
the program is a little complicated, I just express some code related with this issue.
In this program, I have a client which will call a remote method by using rpc_call, and this remote method will read a file in its local filesystem (os is centos), if the file does not exist, a PathError will come out like "open /opt/open-falcon/graph/data/6070/26/2606ecefaaafff55fec4c9e62cca1253_GAUGE_60.rrd: no such file or directory", this error will be caught by client, and if the client use `os.IsNotExist(err)` to find out where it is a pathError, this will not work, because the rpc_call cannot return the type of error.

### What did you expect to see?
some go inside custom error type need to be returned by rpc_call, so the go inside method for error type can be used correctly.

### What did you see instead?
the go inside custom error type is not returned by rpc_call, and some method for error can not be used like `os.IsNotExist`

**Comment by bradfitz** [comment]
I think you might have the wrong bug tracker.

I'm not sure what "rpc_call" means. It's nothing about Go.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by KevinTHU** [comment]
@bradfitz sorry, the rpc_call is not a go inside method, it should be `net/rpc/client.Go` method, which has been modified above.
but I think the issue problem is clear in the comment.

**Comment by KevinTHU** [comment]
for update, in my client, I have this test code `	if pathErr, ok := err.(*os.PathError); ok && os.IsNotExist(pathErr) {
		fmt.Println(pathErr, " is os.PathError")
	}`
if that remote method is run locally, the return err would be a PathError, however, through `net/rpc/client.Go`, I can not find out it is a PathError by the code above, it is just an normal error, for a go-inside error type ,I think this is not a correct return result.

**Comment by bradfitz** [comment]
Why don't you discuss it on one of the various forums at https://golang.org/wiki/Questions and then if there's a concrete bug report and sample reproduction code you can file a new bug?

**Comment by KevinTHU** [comment]
@bradfitz ok, thank you for recommand, I will take a look.

**Comment by KevinTHU** [comment]
@bradfitz I got a test for reproducting this bug, but I don't know where should I put it on? can you give me some suggestion? thx~
