### ISSUE TITLE
tour: invalid date on server?

### ISSUE THREAD

**Issue by hholst80** [golang/go#18481]
```
package main

import (
	"fmt"
	"time"
)

func main() {
	today := time.Now().Weekday()
	fmt.Println("Today:", today)
}
```

returns

```
Today: Tuesday

Program exited.
```

expected result:

```
Friday
```

(or Saturday but not Tuesday!)

**Comment by cespare** [comment]
If you click "about" (top right corner), you'll see

> In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.

**Comment by hholst80** [comment]
Ah sorry. I missed that one. So every time you press run the time is set to that date?
