### ISSUE TITLE
playground: Cannot view specific plays from AS64241

### ISSUE THREAD

**Issue by ianweller** [golang/go#18488]
Hello, I'm a network operator for AS64241 (Wobscale). A customer of ours reported the following:

* https://play.golang.org/ works, and they can run code
* https://play.golang.org/p/eK8-Ye7SKQ does not work (403 Forbidden)

Some research pointed me in the direction of country-code filtering. https://country-test.golang.org/ returns `"ZZ"`. Our network is in the US. Is GeoIP data out of date?

Our network blocks are 209.251.245.0/24 and 2620:fc:c000::/48.

### What version of Go are you using (`go version`)?
n/a

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
Clicked on https://play.golang.org/p/eK8-Ye7SKQ

### What did you expect to see?
Somebody else's code, with the ability to run it

### What did you see instead?
`Forbidden`

**Comment by bradfitz** [comment]
@broady, please file an internal geolocation bug.

**Comment by broady** [comment]
Apparently Google thinks it's in the USA.

@ianweller, can you check again? Maybe it has been updated or rolled out in the past few days.

Internal bug ID (for Googlers only): 34091640

I'll keep you updated as the internal bug progresses.

**Comment by ianweller** [comment]
@broady It's working fine for me now.

**Comment by broady** [comment]
Oh, good, thanks for getting back so quickly.
