### ISSUE TITLE
cmd/go: go bug fills the issue form without using any newlines

### ISSUE THREAD

**Issue by opennota** [golang/go#18485]
### What version of Go are you using (`go version`)?

go version go1.8beta2 linux/amd64

### What did you do?

`go bug`

### What did you expect to see?

A new issue form filled with multiple lines separated by empty lines:

    Please answer these questions before submitting your issue. Thanks! 
    
    #### What did you do?

    If possible, provide a recipe for reproducing the error. A complete runnable program is good. A link on play.golang.org is best. 
    
    #### What did you expect to see? 
    
    #### What did you see instead? 
    
    #### Does this issue reproduce with the latest release  go1.7.4 ? 
    
    #### System details
    
    go version go1.8beta2 linux/amd64
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/opennota/gocode"
    GORACE=""
    GOROOT="/home/opennota/go"
    GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build957029296=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    ...

### What did you see instead?

All is joined into one long line:

    Please answer these questions before submitting your issue. Thanks! #### What did you do? If possible, provide a recipe for reproducing the error. A complete runnable program is good. A link on play.golang.org is best. #### What did you expect to see? #### What did you see instead? #### Does this issue reproduce with the latest release  go1.7.4 ? #### System details     go version go1.8beta2 linux/amd64 GOARCH  amd64 GOBIN  GOEXE  GOHOSTARCH  amd64 GOHOSTOS  linux GOOS  linux GOPATH  /home/opennota/gocode GORACE  GOROOT  /home/opennota/go GOTOOLDIR  /home/opennota/go/pkg/tool/linux_amd64 GCCGO  gccgo CC  gcc GOGCCFLAGS  -fPIC -m64 -pthread -fmessage-length 0 -fdebug-prefix-map /tmp/go-build132067965 /tmp/go-build -gno-record-gcc-switches CXX  g  CGO_ENABLED  1 PKG_CONFIG  pkg-config CGO_CFLAGS  -g -O2 CGO_CPPFLAGS  CGO_CXXFLAGS  -g -O2 CGO_FFLAGS  -g -O2 CGO_LDFLAGS  -g -O2 GOROOT/bin/go version: go version go1.8beta2 linux/amd64 GOROOT/bin/go tool compile -V: compile version go1.8beta2 X:framepointer uname -sr: Linux 4.8.3-gentoo /lib64/libc.so.6: GNU C Library  Gentoo 2.22-r4 p13  stable release version 2.22, by Roland McGrath et al. gdb -version: GNU gdb  Gentoo 7.10.1 vanilla  7.10.1     

The default browser is Mozilla Firefox 40.0.2

**Comment by ALTree** [comment]
Oddly, I can't reproduce this on a vanilla debian Linux with firefox (v 50.1.0) as the default browser.

**Comment by opennota** [comment]
Seems like NoScript add-on somehow intervenes. If I disable it, `go bug` works like a charm.
