### ISSUE TITLE
cmd/go: go get emits an error when given a repository ending with .go

### ISSUE THREAD

**Issue by opennota** [golang/go#18484]
### What version of Go are you using (`go version`)?

go version go1.8beta2 linux/amd64

### What did you do?

`go get github.com/tumblr/tumblr.go`

### What did you expect to see?

`go get` silently cloned the repository.

### What did you see instead?

`go get` cloned the repository and emitted an error message:

    stat github.com/tumblr/tumblr.go: no such file or directory

**Comment by robpike** [comment]
I agree it's not handling this well. You should get an error up front and no download, I would think.

But whatever the resolution, putting .go on the end of a repository name is sure to cause lots of problems. Too many programs look for .go (or .c or .java or .py or ...) and assume items named like that are program source files. It would be wise to avoid fighting that assumption. Choose a different name.

**Comment by opennota** [comment]
But arguments to `go get` cannot be files, can they?
I personally don't mind the message as long as `go get` works, but it can confuse others.

**Comment by rsc** [comment]
Arguments to go get can be files or local directories. Saying "go get ." means get all the things imported by the current directory. Saying "go get -u ." updates those things. The same for "go get x.go" and "go get -u x.go".

The answer is not to name repositories ending in .go.
