### ISSUE TITLE
json.Marshal cause fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by tqyq** [golang/go#18489]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.7.linux-amd64.tar.gz

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/gopath"
GORACE=""
GOROOT="/data/go"
GOTOOLDIR="/data/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build893020014=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

`func JsonEncode(v interface{}) (r string) {
	b, err := json.Marshal(v)
	if err != nil {
		Error(err)
	}
	r = string(b)
	return
}`

### What did you expect to see?

encode map to string

### What did you see instead?

fatal error: concurrent map read and map write

goroutine 34805 [running]:
runtime.throw(0xc9848e, 0x21)
        /data/go/src/runtime/panic.go:566 +0x95 fp=0xc420ef0c20 sp=0xc420ef0c00
runtime.mapaccess2(0xbb0900, 0xc423148fc0, 0xc420966b40, 0xc420ef0cb0, 0xc420ef0cb0)
        /data/go/src/runtime/hashmap.go:340 +0x249 fp=0xc420ef0c68 sp=0xc420ef0c20
reflect.mapaccess(0xbb0900, 0xc423148fc0, 0xc420966b40, 0xc423148fc0)
        /data/go/src/runtime/hashmap.go:1008 +0x3f fp=0xc420ef0ca0 sp=0xc420ef0c68
reflect.Value.MapIndex(0xbb0900, 0xc423148fc0, 0x15, 0xb6a8e0, 0xc420966b40, 0x98, 0xb97520, 0xc420966c00, 0x94)
        /data/go/src/reflect/value.go:1040 +0x128 fp=0xc420ef0d28 sp=0xc420ef0ca0
encoding/json.(*mapEncoder).encode(0xc4207fe0b0, 0xc4200a7b80, 0xbb0900, 0xc423148fc0, 0x15, 0xbb0100)
        /data/go/src/encoding/json/encode.go:646 +0x4f0 fp=0xc420ef0e80 sp=0xc420ef0d28
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200a7b80, 0xbb0900, 0xc423148fc0, 0x15, 0xc423140100)
        /data/go/src/encoding/json/encode.go:662 +0x64 fp=0xc420ef0ec0 sp=0xc420ef0e80
encoding/json.(*encodeState).reflectValue(0xc4200a7b80, 0xbb0900, 0xc423148fc0, 0x15, 0xc423140100)
        /data/go/src/encoding/json/encode.go:307 +0x82 fp=0xc420ef0ef8 sp=0xc420ef0ec0
encoding/json.interfaceEncoder(0xc4200a7b80, 0xb97520, 0xc420966ae0, 0x94, 0xc420960100)
        /data/go/src/encoding/json/encode.go:573 +0xdb fp=0xc420ef0f38 sp=0xc420ef0ef8
encoding/json.(*mapEncoder).encode(0xc4207fe0b0, 0xc4200a7b80, 0xbb0900, 0xc4207556b0, 0x15, 0xbb0100)
        /data/go/src/encoding/json/encode.go:646 +0x542 fp=0xc420ef1090 sp=0xc420ef0f38
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200a7b80, 0xbb0900, 0xc4207556b0, 0x15, 0xc420750100)
        /data/go/src/encoding/json/encode.go:662 +0x64 fp=0xc420ef10d0 sp=0xc420ef1090
encoding/json.(*encodeState).reflectValue(0xc4200a7b80, 0xbb0900, 0xc4207556b0, 0x15, 0x100)
        /data/go/src/encoding/json/encode.go:307 +0x82 fp=0xc420ef1108 sp=0xc420ef10d0
encoding/json.(*encodeState).marshal(0xc4200a7b80, 0xbb0900, 0xc4207556b0, 0x9200000000c80100, 0x0, 0x0)
        /data/go/src/encoding/json/encode.go:280 +0xb8 fp=0xc420ef1140 sp=0xc420ef1108
encoding/json.Marshal(0xbb0900, 0xc4207556b0, 0x412133, 0xc420966a98, 0xc4230f5298, 0xc4230f5218, 0xc4230f5201)
        /data/go/src/encoding/json/encode.go:145 +0x8f fp=0xc420ef1188 sp=0xc420ef1140
datahunter.cn/util.JsonEncode(0xbb0900, 0xc4207556b0, 0xc420ef1248, 0xc420ef1238)
        /data/gopath/src/datahunter.cn/util/util.go:283 +0x3c fp=0xc420ef1200 sp=0xc420ef1188

**Comment by davecheney** [comment]
This is working as intended. The go runtime detects concurrent misuse of maps and will crash the program. 

https://golang.org/doc/go1.6#runtime

For more information run your program under the race detector. 

https://golang.org/doc/articles/race_detector.html

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by rami-dabain** [comment]
How to recover from that?
Recover doesn't seem to work when json encoder crashes with the con-map-access!

**Comment by ALTree** [comment]
>  How to recover from that?

@rami-dabain you don't. A program that has a data race on a map is not a valid Go program. If you're getting this, you need to fix your code to avoid the data race. 

Please dont' ask questions on closed issue. If you have further questions, see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.
