### ISSUE TITLE
struct with embedded time.Time prints incorrectly

### ISSUE THREAD

**Issue by jba** [golang/go#18480]
If you embed time.Time in a struct, %+v prints it out as just a time, not a struct.

### What version of Go are you using (`go version`)?

1.7.4

### What operating system and processor architecture are you using (`go env`)?

playground

### What did you do?

https://play.golang.org/p/r-zlQzU67e

### What did you expect to see?

{X:0 Time:0001-01-01 00:00:00 +0000 UTC}

### What did you see instead?

0001-01-01 00:00:00 +0000 UTC

**Comment by cespare** [comment]
%v and %+v both call String(), if defined, and time.Time has a String method that's getting invoked here because you used struct embedding. Working as intended.
