### ISSUE TITLE
crypto/aes: add dedicated asm version of AES, AES-GCM for arm64

### ISSUE THREAD

**Issue by matt2909** [golang/go#18498]
Add a dedicated asm version of AES, AES-GCM for arm64 - utilizing ARMv8-A crypto extension when available.

It should be noted that an asm accelerated version of this algorithm, utilizing AES-NI when available,  exists for amd64.

**Comment by matt2909** [comment]
A partial implementation seems to have been developed under changelist:
https://go-review.googlesource.com/#/c/32579/

**Comment by gaillard** [comment]
Any chance to be targeted for 1.9?

**Comment by bradfitz** [comment]
@cherrymui, is this something you could review?

**Comment by cherrymui** [comment]
I am not familiar with the algorithm. I may be able to review in terms of whether the assembly version and the Go version are equivalent. Probably not so fast though.

**Comment by vielmetti** [comment]
There's related wrok here https://github.com/minio/sha256-simd/ and this open issue there for upstream support https://github.com/minio/sha256-simd/issues/7

**Comment by matt2909** [comment]
I agree it's "related" in that they both accelerate crypto things, and they
are both nice to haves, but sha256 acceleration should be filed as a
separate issue.

**Comment by ALTree** [comment]
A partial fix here: https://go-review.googlesource.com/c/go/+/64490

**Comment by vielmetti** [comment]
On arm64, Packet Type 2A / c1.large.arm Cavium ThunderX:

```
ed@ed-2a-bcc-llvm:~$ go test crypto/cipher -bench GCM

goos: linux
goarch: arm64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-96           20000             68788 ns/op          14.89 MB/s
BenchmarkAESGCMOpen1K-96           20000             68697 ns/op          14.91 MB/s
BenchmarkAESGCMSign8K-96           10000            182114 ns/op          44.98 MB/s
BenchmarkAESGCMSeal8K-96            3000            536359 ns/op          15.27 MB/s
BenchmarkAESGCMOpen8K-96            3000            537432 ns/op          15.24 MB/s
PASS
ok      crypto/cipher   9.404s
ed@ed-2a-bcc-llvm:~$ 
ed@ed-2a-bcc-llvm:~$ go version
go version go1.10.2 linux/arm64
ed@ed-2a-bcc-llvm:~$ ~/go/bin/go1.11beta1 test crypto/cipher -bench GCM
goos: linux
goarch: arm64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-96           50000             37520 ns/op          27.29 MB/s
BenchmarkAESGCMOpen1K-96           50000             37550 ns/op          27.27 MB/s
BenchmarkAESGCMSign8K-96           10000            172278 ns/op          47.55 MB/s
BenchmarkAESGCMSeal8K-96            5000            289794 ns/op          28.27 MB/s
BenchmarkAESGCMOpen8K-96            5000            288511 ns/op          28.39 MB/s
PASS
ok      crypto/cipher   9.274s
```

1.11beta1 is substantially faster than 1.10.2.

**Comment by jared2501** [comment]
So excited to see this merge! https://go-review.googlesource.com/c/go/+/107298

**Comment by jared2501** [comment]
Thanks so much for the hard work on this!
