### ISSUE TITLE
cmd/go: go test -mutexprofile does not retain test binary

### ISSUE THREAD

**Issue by vcabbage** [golang/go#18494]
#### What did you do?

Ran a test with `-mutexprofile` option enabled.

#### What did you expect to see?

The test binary in the current directory after the test completed.

#### What did you see instead?

No test binary.

#### Does this issue reproduce with the latest release (go1.7.4)?

`-mutexprofile` added for 1.8 release. Reproducible with latest master.

#### System details

```
go version devel +0b11f5e372 Wed Dec 28 20:04:34 2016 -0800 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kale/go"
GORACE=""
GOROOT="/Users/kale/gomaster"
GOTOOLDIR="/Users/kale/gomaster/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jv/fp0q8rhx427f6p892mh4mpx40000gn/T/go-build063411575=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version devel +0b11f5e372 Wed Dec 28 20:04:34 2016 -0800 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +0b11f5e372 Wed Dec 28 20:04:34 2016 -0800 X:framepointer
uname -v: Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67
lldb --version: lldb-360.1.70
```

**Comment by minux** [comment]
is the binary still required for latest cmd/pprof and new protobuf based
profile format?

**Comment by vcabbage** [comment]
I can't answer that one, but the help says:
```
	-mutexprofile mutex.out
	    Write a mutex contention profile to the specified file
	    when all tests are complete.
	    Writes test binary as -c would.
```

**Comment by ianlancetaylor** [comment]
CC @pjweinbgo

**Comment by pjweinbgo** [comment]
Yes: some test flags leave a binary behind and some don't. go/src/cmd/go/testflag.go has a switch at line 137 that deals with all the test-only flags. I'll either change the behavior or the comment. (It looks like it's the behavior that needs to be changed, but I'm not sure.)

**Comment by rakyll** [comment]
(It would be nice to have a decision on this before the 1.8 release. Adding tentatively to the 1.8 milestone.)

**Comment by pjweinbgo** [comment]
I have a CL coming today or tomorrow. (changes the behavior)
