### ISSUE TITLE
net/http: ProxyFromEnvironment does not support socks5

### ISSUE THREAD

**Issue by bruceauyeung** [golang/go#18508]
### What version of Go are you using (`go version`)?
`go version go1.7.4 linux/amd64
`
### What operating system and processor architecture are you using (`go env`)?

actually it's Manjaro
~~~
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bruce/go_ext_path"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build134643851=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
~~~

### What did you do?
~~~
git config --global http.proxy 'socks5://127.0.0.1:1080'
git config --global https.proxy 'socks5://127.0.0.1:1080'
export http_proxy=socks5://127.0.0.1:1080
export https_proxy=socks5://127.0.0.1:1080
go get -u -v github.com/zmb3/gogetdoc
~~~

### What did you expect to see?

Git can use socks5 proxy to clone a repo, so i expect `go get` can use socks5 proxy to download/update package `github.com/zmb3/gogetdoc`

### What did you see instead?

> github.com/zmb3/gogetdoc (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout)
Fetching https://golang.org/x/tools/go/loader?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/loader?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout
package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader" (https fetch: Get https://golang.org/x/tools/go/loader?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout)
[bruce@bruce-manjaro ~]$ set https_proxy=socks5://127.0.0.1:1080
[bruce@bruce-manjaro ~]$ go get -u -v github.com/zmb3/gogetdoc
github.com/zmb3/gogetdoc (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/buildutil?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout)
Fetching https://golang.org/x/tools/go/loader?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/loader?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout
package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader" (https fetch: Get https://golang.org/x/tools/go/loader?go-get=1: http: error connecting to proxy http://socks5://127.0.0.1:1080: dial tcp 59.50.43.82:0: i/o timeout)

**Comment by davecheney** [comment]
Is there a specification for http_proxy ?

**Comment by josharian** [comment]
From a quick glance, looks like maybe cmd/go needs to use http.ProxyFromEnvironment.

**Comment by davecheney** [comment]
I'm pretty confident there is no socks handling code in the std lib, so it
wouldn't really help.

**Comment by davecheney** [comment]
If there is a standard for a socks URL, we can at least spot it and give a
better error rather than blindly using the provided URL as a http proxy.

**Comment by bradfitz** [comment]
Yes, we don't support SOCK5 proxies in the standard library and thus we don't support it in the cmd/go tool.

We have SOCK5 support elsewhere, so we could vendor it into std at least for use by cmd/go, but it's not clear how much it matters. Is SOCK5 still widely used?

**Comment by bruceauyeung** [comment]
@davecheney useful informations that i can found about http.proxy is http://unix.stackexchange.com/a/212972

@bradfitz In China, shadowsocks is used widely

**Comment by davecheney** [comment]
If you use tor, the answer is a strong yes.

**Comment by bradfitz** [comment]
That still wouldn't get you SOCKS5 support.

**Comment by rsc** [comment]
cmd/go does use http.ProxyFromEnvironment, because http.DefaultTransport does.

http.ProxyFromEnvironment does not support socks5. @bradfitz, where is the socks5 code we have elsewhere? It seems like it should be a tiny amount of code (under 100 lines plus tests) to proxy TCP connections into socks5. Assuming it really is small, I would not object to putting that into the standard library, on by default. It's very useful combined with `ssh -D`. I used to use that and tsocks, but Go doesn't play well with tsocks if I remember correctly, and tsocks is a bit of a hack.

As @davecheney says, at the least we should give a better error. But it would be nice to add support.

**Comment by bradfitz** [comment]
@rsc, SOCK5 support is at https://godoc.org/golang.org/x/net/proxy#SOCKS5

**Comment by iamzhout** [comment]
@bruceauyeung Just suggest to use privoxy / squid alike tool to setup a local http proxy server over socks5 one to get workaround of this issue.

@bradfitz it would be useful if socks proxy could be supported. As to me it would also be ok if not as for the workaround I mentioned above.

**Comment by bruceauyeung** [comment]
> @bruceauyeung Just suggest to use privoxy / squid alike tool to setup a local http proxy server over socks5 one to get workaround of this issue.

@iamzhout thanks for your tip. now i `go get` packages through a http proxy ([XX-Net](https://github.com/XX-net)), although it's slow.

**Comment by iamzhout** [comment]
@bradfitz actually there is another issue https://github.com/golang/go/issues/18519 which really bothers me a lot. Hope there would be a fix or workaround also.

**Comment by davecheney** [comment]
@iamzhout it looks like your employer is MITM'ing your SSL communcations.

Go get is just a wrapper over git, I recommend git cloning that repository directly.

**Comment by iamzhout** [comment]
@bruceauyeung, I do suggest you to give privoxy/squid a try, as the speed should be the same as to your socks5 one. and the configuration is really simple, take privoxy as an example, you just add below line to your /etc/privoxy/config file, and then do `service privoxy restart`, all done.
```
listen-address  0.0.0.0:12345
forward-socks5  /  your-socks5-ip:port  .
```

**Comment by icexin** [comment]
You may want this `github.com/icexin/sockhttp`. It's a small tool written in go that makes a HTTP proxy over SOCK5.

**Comment by bruceauyeung** [comment]
@icexin i'll give it a shot, thanks for your work!

**Comment by mattn** [comment]
Maybe, implementaion will be like below.

```go
package main

import (
	"context"
	"io"
	"log"
	"net"
	"net/http"
	"os"

	"golang.org/x/net/proxy"
)

type dialer struct {
	addr   string
	socks5 proxy.Dialer
}

func (d *dialer) DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
	return d.Dial(network, addr)
}

func (d *dialer) Dial(network, addr string) (net.Conn, error) {
	var err error
	if d.socks5 == nil {
		d.socks5, err = proxy.SOCKS5("tcp", d.addr, nil, proxy.Direct)
		if err != nil {
			return nil, err
		}
	}
	return d.socks5.Dial(network, addr)
}

func Socks5Proxy(addr string) *http.Transport {
	d := &dialer{addr: addr}
	return &http.Transport{
		DialContext: d.DialContext,
		Dial:        d.Dial,
	}
}

func main() {
	http.DefaultTransport = Socks5Proxy("127.0.0.1:1080")

	resp, err := http.Get("http://www.google.com/")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	io.Copy(os.Stdout, resp.Body)
}
```
tested with server written in go https://github.com/armon/go-socks5

**Comment by mattn** [comment]
So, to add common interfaces between http_proxy and socks5, I guess we should not modify ProxyFromEnvironment. it's better to add new API for set-up proxy.

**Comment by walken-google** [comment]
I  could use this feature too, and I've been looking into implementing it.

This has probably been answered before, but how do I go about importing a golang.org package (such as golang_org/x/net/proxy) so that the net/http package can use it ? I know this would require creating a src/vendor/golang_org/x/net/proxy directory but I'm not sure if it needs any tracking metadata, if the import needs to be a separate commit, etc...

**Comment by walken-google** [comment]
Prototype in https://go-review.googlesource.com/35488
