### ISSUE TITLE
x/sys/unix: missing SYS_MSYNC for NetBSD

### ISSUE THREAD

**Issue by Artoria2e5** [golang/go#18513]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Problem exists on HEAD.

### What operating system and processor architecture are you using (`go env`)?

Let's pretend I am using NetBSD.

### What did you do?

A few days ago I somehow saw edsrdf's mmap-go, which [self-defines an syscall number](https://github.com/edsrzf/mmap-go/blob/master/msync_netbsd.go) for `SYS_MSYNC` (277) on NetBSD. Apparently Go's current syscall extraction fails to find it in NetBSD headers.

For cross-check I looked at [`syscalls.master`](https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/kern/syscalls.master), which also points to 277 as msync:

```
277	STD 		{ int|sys|13|msync(void *addr, size_t len, int flags); }
```

### What did you expect to see?

Proper `SYS_MSYNC`.

### What did you see instead?

It doesn't exist.

**Comment by bradfitz** [comment]
The Go syscall package is frozen. See https://golang.org/pkg/syscall/#pkg-overview

We can repurpose this bug for the https://godoc.org/golang.org/x/sys/unix package, though.

**Comment by LionNatsu** [comment]
@bradfitz BTW,  I cannot access https://golang.org/s/go1.4-syscall (the URL in https://golang.org/pkg/syscall/#pkg-overview).

**Comment by LionNatsu** [comment]
@minix Yes you are right. I forgot to turn on my lovely local DNS, embarrassing...
