### ISSUE TITLE
There is no reuse objects

### ISSUE THREAD

**Issue by 94else** [golang/go#18521]
https://github.com/golang/go/blob/master/src/net/rpc/server.go
```
unc (server *Server) getRequest() *Request {
	server.reqLock.Lock()
	req := server.freeReq
	if req == nil {
		req = new(Request)
	} else {
		server.freeReq = req.next
		*req = Request{}   //There is no reuse objects
	}
	server.reqLock.Unlock()
	return req
}

func (server *Server) getResponse() *Response {
	server.respLock.Lock()
	resp := server.freeResp
	if resp == nil {
		resp = new(Response)
	} else {
		server.freeResp = resp.next
		*resp = Response{}
	}
	server.respLock.Unlock()
	return resp
}
```

**Comment by ianlancetaylor** [comment]
I don't see a bug report here.  At least, if this is a bug report, I don't understand it.

Please ask questions on a forum -- see https://golang.org/wiki/Questions .  If, after asking a question, we determine that there is a bug here, please go ahead and file an issue or comment on this one.

Closing.

**Comment by mvdan** [comment]
I believe this was about every call meaning an alloc. This isn't a bug report though, and if it's a suggestion to improve performance it should come with a reason why and a possible solution (e.g. pool).

**Comment by 94else** [comment]
this is pool
```
type Request struct {
	ServiceMethod string   // format: "Service.Method"
	Seq           uint64   // sequence number chosen by client
	next          *Request // for free list in Server
}

```
put to pool

```
func (server *Server) freeRequest(req *Request) {
	server.reqLock.Lock()
	req.next = server.freeReq
	server.freeReq = req
	server.reqLock.Unlock()
}

```
get from pool

```
func (server *Server) getRequest() *Request {
	server.reqLock.Lock()
	req := server.freeReq
	if req == nil {
		req = new(Request)
	} else {
		server.freeReq = req.next
		*req = Request{}  //realloc
	}
	server.reqLock.Unlock()
	return req
}

```

@mvdan

**Comment by mvdan** [comment]
The code is not my main concern - what I meant is why this is a bottleneck or problem or any sort. Optimizations like these should in general only be done where they actually affect performance considerably.
