### ISSUE TITLE
UrlQueryUnescape loses properly escaped '+' symbols

### ISSUE THREAD

**Issue by charles-l** [golang/go#18528]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.7.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nc/dev/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build870758629=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/SEk0hwSCD5

### What did you expect to see?

The string: "1+1=2"

### What did you see instead?

The string: "1 1=2"

**Comment by rakyll** [comment]
You are unescaping the original string, not the escaped one. See https://play.golang.org/p/JtTYvX_0sb where QueryUnescape handles the escaped "+" correctly.

**Comment by charles-l** [comment]
@rakyll Ah, shoot - my bad. Sorry about that. Closing.
