### ISSUE TITLE
x/mobile: gomobile init fails to download ndk on x86 host

### ISSUE THREAD

**Issue by justmax437** [golang/go#18522]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 linux/386

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/max/dev/workspace/go"
GORACE=""
GOROOT="/home/max/dev/go"
GOTOOLDIR="/home/max/dev/go/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build501597397=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
I'm trying to install gomobile using https://github.com/golang/go/wiki/Mobile as a manual.
Running (`gomobile init`) ends up with error message:
"gomobile: error fetching https://dl.google.com/go/mobile/gomobile-ndk-r12b-linux-x86.tar.gz, status: 404 Not Found"

Looks like it just can't find proper ndk to download. Is there any known fix or workaround for this?

**Comment by mvdan** [comment]
To the best of my knowledge, the NDK dropped 32-bit support on Linux quite a few releases ago. They still seem to offer 32-bit builds for Windows, though.

**Comment by rakyll** [comment]
32-bit Linux is not supported anymore. We should die with a proper error message saying it is not supported.

**Comment by justmax437** [comment]
@rakyll 
No way to get to work with an outdated ndk for 386?
Something like "linux/386 ndk is outdated and is not supported by gomobile anymore. Use with caution"

**Comment by rakyll** [comment]
There is no way to override the NDK location right now, but you should be able to override CC, CXX, CGO_CFLAGS, CGO_CPPFLAGS and CGO_LDFLAGS individually to target an earlier version of NDK toolchain.
