### ISSUE TITLE
crypto/ecdsa: Expose ecdsaSignature class

### ISSUE THREAD

**Issue by stevenroose** [golang/go#18520]
Currently the `ecdsa.Sign` method returns the r and s values. However, there is a struct for the signature
```go
type ecdsaSignature struct {
	R, S *big.Int
}
```

Verification of a signature also requires these two values. However, signatures are usually communicated as byte strings, being the ASN.1 encoded form of both these values in a SEQUENCE. This is exactly what the `ecdsaSignature` struct provides.

So it would be a lot more convenient to have this struct provided by the library instead of individual implementations having to define this struct themselves, making their structs incompatible with other people's code.

So, the suggestion I put forward is expose the struct as `EcdsaSignature` and alter the `ecdsa.Sign` and `ecdsa.Verify` methods to not take r and s as arguments, but an `EcdsaSignature`.

**Comment by bradfitz** [comment]
Sorry, but for better or worse, https://golang.org/doc/go1compat precludes changing the API at this point.
