### ISSUE TITLE
playground: add instructions for link removal

### ISSUE THREAD

**Issue by rsc** [golang/go#18530]
Twice in the past few months people have mailed golang-dev asking how to have a playground entry removed. I don't mind doing the occasional manual removal in these cases. Should we create an alias playground-removal@golang.org (or reuse security@golang.org?) and put a note somewhere on the playground?

/cc @bradfitz @broady

**Comment by bradfitz** [comment]
I'm fine reusing security but it does mean a bit more spam. That's fine for now. We can adjust later if needed.

**Comment by broady** [comment]
Re-using security seems fine for now. (Though I don't receive those e-mails - maybe I should?)

**Comment by rsc** [comment]
If you go to play.golang.org and click About, it has some uncopyable text that contains a hyperlinked "contact us first" and that points at golang-dev. This was the root cause of the mail being sent to golang-dev the last time, and maybe the time before that. It's not obvious from that description that it's a public mailing list. We should put (public mailing list) in the link text or else change the address being used.

The "how to remove" can go into the same About screen.

**Comment by broady** [comment]
deployed, but it's not possible to copy and paste from that screen - once clicked, the screen disappears.
