### ISSUE TITLE
cmd/go: module-aware get x.go should not look up the host x.go

### ISSUE THREAD

**Issue by KevinGimbel** [golang/go#18533]
### What version of Go are you using (`go version`)?
`go version go1.7.4 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
MacOS Sierra 10.12.1
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kevingimbel/Development/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m7/zzw3lkfd03v0zrv0d_yvcrbh0000gn/T/go-build857722417=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

I tried to get a script I wrote from my personal GitHub Profile using `go get github.com/kevingimbel/vhost.go`

### What did you expect to see?

I expected to get the source code from [github.com/kevingimbel/vhost.go](https://github.com/kevingimbel/vhost.go) to download to `$GOPATH/src/github/kevingimbel/vhost.go`

### What did you see instead?

Instead [github.com/kevingimbel/vhost.go](https://github.com/kevingimbel/vhost.go) and [github.com/kevingimbel/vhost](https://github.com/kevingimbel/vhost) were downloaded to `$GOPATH/src/github/kevingimbel`. The second one is a shell script which should not be downloaded when I specify the "url" `github.com/kevingimbel/vhost.go`. 

---

Is this intended behaviour? Should `go get` look for similar names to what you specify, let's say in case of a typo? I expected it to only download one of the two repository, namely `vhost.go` which I specified. 

My script itself is broken, too, because it searches for a package named `vhost` which does not exist. When I clone the repository with git to `$GOPATH/src/github.com/kevingimbel` and try to run it I get the following error: 

```sh
$ go run vhost-cli.go
vhost-cli.go:5:2: cannot find package "github.com/kevingimbel/vhost/api" in any of:
        /usr/local/go/src/github.com/kevingimbel/vhost/api (from $GOROOT)
        /Users/kevingimbel/Development/go/src/github.com/kevingimbel/vhost/api (from $GOPATH)
```

When I rename the directory `vhost.go` to `vhost` it works as expected. 

```shell
$ go run vhost-cli.go
2017/01/06 09:15:23 Successfully created file
```
---

 What would be the best naming convention if two repositories under the same account have the "same" or similar name? To "fix" this I would need to re-name `vhost.go` to `vhost` and the shell script to something like `vhost.sh`. This might be an edge case but it should be documented somewhere since it can affect other users, too. 

Might be related to #18484.

**Comment by bradfitz** [comment]
The `go get` command takes a package as its argument, not a filename.

I suspect something might be attempting to canonicalize your argument and removing the `.go` suffix.

In any case, it should probably have a better error message.

/cc @rsc

**Comment by rsc** [comment]
In the current model, go get foo (with no -u) means to install foo and any missing dependencies, but not update anything. So if you have foo already 'go get foo' and 'go install foo' are the same. 

In general, you can list .go files instead of a package name and the go command will pretend they make up a package and do what you ask for them, for example build it or tell you information: `go list -json x.go`.

go get foo/bar/x.go means get all the dependencies needed by that file and then build and install the file. The install will fail since it doesn't know where to install it, but you didn't get that far.

All of this may be rethought this year, so I'm not inclined to make tweaks right now. The best solution is to change your repo name not to end in ".go". That's just not the convention and it's not going to work.

**Comment by davecheney** [comment]
This is the second report about using go get to get a repo ending in .go.
The first was intentional, the second was not, and the overwhelming
concensus was neither use cases were a good idea.

My suggestion is the go tool should refuse to download any repo ending in
.go.

**Comment by opennota** [comment]
@rsc 
> go get foo/bar/x.go means get all the dependencies needed by that file and then build and install the file.
Then this is somewhat underdocumented.

**Comment by davecheney** [comment]
It's not documented because it's wrong. Go get works on packages, not files.

**Comment by opennota** [comment]
@davecheney 
> It's not documented because it's wrong. Go get works on packages, not files.

Then `go get` should not reject any repos based on their suffix and should not attempt to trim that suffix.

**Comment by davecheney** [comment]
That was my suggestion.

**Comment by kevingimbel** [comment]
@rsc 
> The best solution is to change your repo name not to end in ".go". That's just not the convention and it's not going to work.

Would `*-go` be better then? Let's say you have a project which provides SDKs in multiple languages and each repo is named `myproject-lang` so `myproject-go`, `myproject-javascript`, `myproject-scala`, etc. - would this be an appropriate naming convention?

Is it documented anywhere that repos cannot end in `.go`?

In my opinion for the 1.9 release there should be a more verbose error message when downloading a package which ends on `.go`.

**Comment by gulyasm** [comment]
I'm thinking: checking in `runGet` that the package names are "valid" before downloading. If any package name ends with `.go`, exit with meaningful error message. 

Is it a good approach or it's too aggressive to fail if any package name is "wrong"?

**Comment by rsc** [comment]
> It's not documented because it's wrong. Go get works on packages, not files.

And when you name .go source files in place of a package, the command is operating on the package defined by those source files. See also "go build x.go y.go z.go", "go test x.go", and so on.

**Comment by rsc** [comment]
Will keep in mind for next cycle.

**Comment by rsc** [comment]
Module-aware get should just reject .go files on the command line. That will clear this up. We'll leave legacy GOPATH get alone until we remove it.

**Comment by rsc** [comment]
Needs fix as described in previous comment.

**Comment by seankhliao** [comment]
I believe this is done

```
main » go version                    
go version devel go1.21-10ad6c91de1 Fri May 5 19:53:39 2023 +0000 linux/amd64

main » go get x.go                               
go: x.go: arguments must be package or module paths
```
