### ISSUE TITLE
x/playground: add a "close" button for the "About" screen

### ISSUE THREAD

**Issue by broady** [golang/go#18546]
At the moment, the screen closes when it's clicked anywhere.

Add a proper modal dialog with a close button.

/cc @rsc @bradfitz

**Comment by rsc** [comment]
Yes please. :-)

**Comment by ysmolsky** [comment]
Trying my hand on it. Something likes this? ping @andybons 

![screen shot 2018-03-03 at 17 14 30](https://user-images.githubusercontent.com/140245/36935905-68efc438-1f06-11e8-9f6d-85d6c9d90fda.png)

**Comment by andybons** [comment]
Yes that’s fine with me. We can work on styling when the review is sent.

**Comment by seankhliao** [comment]
go.dev/play displays the about below the interactive sections.
