### ISSUE TITLE
Variadic function slice parameter problem

### ISSUE THREAD

**Issue by veecue** [golang/go#18547]
### What version of Go are you using (`go version`)?
go version go1.7.4 linux/amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/VCp9myxdUU

`
	x := []interface{}{"0","1","2"}
	
	// This is working
	fmt.Println(x...)
	// -> fmt.Println("0","1","2")
	
	// This isn't
	//fmt.Println("-1", x...)
	// -> fmt.Println("-1","0","1","2")
	
	// This is working
	fmt.Printf("", x...)
	// -> fmt.Printf("","0","1","2")
	
	// This isn't
	//fmt.Printf(x...)
	// -> fmt.Printf("0","1","2")
`

Apparently a parameter like `x []int` used as `x...` can only feed a parameter of the type `x ...int` and not multiple ints.
While this is obvious, because nobody guarantees that x is big enough to fulfil the function's parameters at compile time, the other way round seems weird... Why cannot `y, x...` feed a new parameter of the type `x ...int`, which could take an infinite amount of parameters

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

You can only use ... for the variadic parts. It can't span the requirement arguments and the variadic ones. This is by design and documented in the spec.

**Comment by veecue** [comment]
This seems obvious, you're right. The other way round should be possible (like `fmt.Println("a", x...)`)
