### ISSUE TITLE
x/build: auto submit bot?

### ISSUE THREAD

**Issue by minux** [golang/go#18552]
Relevant discussion: https://groups.google.com/d/msg/golang-dev/afkXKoAd8IQ/S8G8_YfaEAAJ

Right now it is impossible to see if a CL author can submit or not from Gerrit CL page.
Either make Gerrit show such or just make trybot also in charge of submission?

Brad said in the mailing list thread:
> We could have a bot that auto-rebases and auto-tests +2ed CLs, and if they're not merged in N hours, it could add a reviewer who has +2 access, leaving a comment at the same time like, "This CL is rebased & tests pass. It needs somebody to press submit."
>
> (unless the CL had some sort of AUTOSUBMIT=true comment, in which case it'd just happen)

Related #9858 (trybot should rebase when testing)
/cc @bradfitz

**Comment by mvdan** [comment]
Kubernetes has had something like this for years. @thockin any wisdom to share? Don't know who actually engineered @k8s-merge-robot, though.

**Comment by thockin** [comment]
The merge not brought a modicum of sanity to a really bad situation.  We
had a regular occurrence of 2 changes which passed tests independently and
didn't literally conflict at the code level, but would fail tests
together.  Now we almost never hand-merge.

**Comment by mvdan** [comment]
Thanks @thockin. I wanted to bring up the bot because I don't think Go itself re-runs tests after every cherry-pick. For example: https://go-review.googlesource.com/#/c/29137/

The two CLs mentioned were green separately. The bot could have picked it up.

**Comment by bradfitz** [comment]
Minux, you already filed this bug and your dup is still open: #12482
