### ISSUE TITLE
CONTRIBUTING.md doesn't describe proper procedure for proposals in issues

### ISSUE THREAD

**Issue by msiebuhr** [golang/go#18550]
### What did you do?
Make a proposal for golang

### What did you expect to see?
[guidelines for contributing](https://github.com/golang/go/blob/master/CONTRIBUTING.md) telling me when using issues is a proper venue for discussing things (rather than ex. go-nuts@)

While I'm not quite sure myself, some GitHub-centric people might not even be aware of especially the mailing-lists used for discussing all things Go.

**Comment by bradfitz** [comment]
The think you linked to in your bug report already says to use golang-nuts for questions.

But I can add a bit more. I sent out https://go-review.googlesource.com/34917

**Comment by msiebuhr** [comment]
> The think you linked to in your bug report already says to use golang-nuts for questions.

Yes. But I wasn't sure when to opt for doing a proposal rather than heading over to golang-nuts.

> But I can add a bit more. I sent out https://go-review.googlesource.com/34917

Looks Good To Me
