### ISSUE TITLE
encoding/xml: Marshal fails to handle conflicting tags

### ISSUE THREAD

**Issue by alexd765** [golang/go#18564]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
tip and 1.7.4
(this is not a regression)

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
https://play.golang.org/p/w6DV-tXCwT

### What did you expect to see?
```<A><name2></name2></A>```

### What did you see instead?
```xml: name "name1" in tag of main.A.B conflicts with name "name2" in main.B.XMLName```

https://golang.org/pkg/encoding/xml/#Marshal lists the order of preference for the name of an element. 

The example works if you remove the tag name1 or name2. This means the order of preferences (name1,name3) and (name2,name3) are working, but (name1,name2) is not.

**Comment by titanous** [comment]
This appears to be working as intended. The comment around [the code that implements the error](https://github.com/golang/go/blob/d8264de8683dac99ffbbbc1f46415e627b73c9ed/src/encoding/xml/typeinfo.go#L216-L226) says:

> If the field type has an XMLName field, the names must match so that the behavior of both marshaling and unmarshaling is straightforward and unambiguous.

Having conflicting name tags in the code is incorrect and this error is designed to point that out.

**Comment by alexd765** [comment]
Hm then maybe this is just a documentation issue?

The documentation i linked gave me the impression that there are 5 different ways to name an element and it would be able to handle conflicts by the order of preference.

I would argue that it is a little bit confusing that some conflicts can be handled, but others can't.

**Comment by leighmcculloch** [comment]
I've added a paragraph to the `xml.Marshal` function docs that mirror the comment in `structFieldInfo` to bring the knowledge into godocs. [CL 76321](https://golang.org/cl/76321)
