### ISSUE TITLE
go/types: typo in doc

### ISSUE THREAD

**Issue by gonutz** [golang/go#18562]
In go/types/api.go in the package comment, it says in the first paragraph "create a new type checked with NewChecker". It says "checked" but should be "checker".
This confused me, so I am reporting it here (since pull requests are not accepted).

**Comment by ALTree** [comment]
Yes, looks like it should be "checker".

The project does not use pull requests but you can send a patch via gerrit if you'd like to. The [contribution guidelines page](https://golang.org/doc/contribute.html) explains how to do it.
