### ISSUE TITLE
cmd/fix: lots of unused code

### ISSUE THREAD

**Issue by shawnps** [golang/go#18568]
Maybe I'm missing something, but there seems to be a lot of unused code in `cmd/fix`, many of which I believe left over after this commit:

https://github.com/golang/go/commit/df93283d5694814efc97efd2132da11722d11523

```
➜  fix git:(master) gometalinter --deadline=60s \
             --disable-all --enable=deadcode \
             --exclude=vendor ./...
fix.go:335:1:warning: isPtrPkgDot is unused (deadcode)
fix.go:353:1:warning: isCall is unused (deadcode)
fix.go:359:1:warning: isIdent is unused (deadcode)
fix.go:373:1:warning: isBlank is unused (deadcode)
fix.go:378:1:warning: isEmptyString is unused (deadcode)
fix.go:383:1:warning: warn is unused (deadcode)
fix.go:393:1:warning: countUses is unused (deadcode)
fix.go:408:1:warning: rewriteUses is unused (deadcode)
fix.go:435:1:warning: assignsTo is unused (deadcode)
fix.go:467:1:warning: newPkgDot is unused (deadcode)
fix.go:787:1:warning: renameFix is unused (deadcode)
typecheck.go:136:1:warning: typecheck is unused (deadcode)
```

They do appear to be unused to me, after checking with `git grep`:

```
➜  src git:(master) git grep isPtrPkgDot
cmd/fix/fix.go:// isPtrPkgDot reports whether f is the expression "*pkg.name"
cmd/fix/fix.go:func isPtrPkgDot(t ast.Expr, pkg, name string) bool {
(END)
```

```
➜  src git:(master) cd cmd/fix
➜  fix git:(master) git grep "typecheck("
typecheck.go:func typecheck(cfg *TypeConfig, f *ast.File) (typeof map[interface{}]string, assign map[string][]interface{}) {
(END)
```

If they are in fact not necessary anymore, I can go ahead and make a CL removing them.

**Comment by josharian** [comment]
Go for it. Thanks.

For the future, please use "pkg: bug description" format for issue titles. It helps with triage and tools. I'll fix this one now.

**Comment by shawnps** [comment]
Thanks @josharian. CL is coming soon.

> For the future, please use "pkg: bug description" format for issue titles. It helps with triage and tools. I'll fix this one now.

Thanks, will remember that for the future.

**Comment by rsc** [comment]
Please do _NOT_ delete all that code. That's unused because there are relatively few fixes. It's still useful code. Think of cmd/fix as a library with a bunch of plugins all linked into the same package. The fact that there are few plugins doesn't mean you delete the library.

**Comment by shawnps** [comment]
@rsc okay. I'll abandon the CL
