### ISSUE TITLE
Why does the -run option not apply to benchmark tests?

### ISSUE THREAD

**Issue by object88** [golang/go#18560]
Please answer these questions before submitting your issue. Thanks!  _No, thank you!_

### What version of Go are you using (`go version`)?

```
% go version
go version go1.7.4 darwin/amd64
````

### What operating system and processor architecture are you using (`go env`)?

```
% go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pbrousseau/work"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ll/qnwx1hrs2hgfnsp43nhpdghrlr0j81/T/go-build010452723=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

I have a project that has a suite of tests and a suite of benchmarks.  I want to profile one particular benchmark for any potential hotspots.  I have to two following commands:

```
go test -bench=. -run=Benchmark_Hashmap_Get_LargeBlock -cpuprofile=./cpu.out  
go tool pprof -pdf ./immutable.test ./cpu.out > ./cpu.pdf
```

The resulting file shows the graph of all my benchmark tests, instead of just the test named by the `-run` command.

### What did you expect to see?

Not so much _expect_, per se, because I see that the docs explicitly say that the `-run` option only applies to Test and Example functions with the matching regex... but I think that it would be very helpful to use this with a benchmark.

### What did you see instead?

The `-run` option is ignored, and my entire suite of benchmarks is executed.  When used in conjunction with the `-cpuprofile`, the output becomes very cluttered and noisy.  With many common sub-functions down (up?) the call stack, it's difficult to know what impression the changes between different benchmarks makes.  It would be most useful to see the individual benchmarks separately.

I recognize that I can take my benchmarks, and replicate them as tests or examples, but that seems overly redundant and unnecessary.  It's performance that I am looking to dive into, and that isn't what _test_ or _example_ is there for, it seems?

I also recognize that the running the benchmark means executing the same code repeatedly, however I don't think that this is detrimental for a profile, as long as the performance is consistent.

Maybe I'm just Doing It Wrong, and this is already available?

**Comment by josharian** [comment]
The -bench flag is like -run, but for benchmarks. So instead of `-bench=. -run=Benchmark_Hashmap_Get_LargeBlock`, try `-bench=Benchmark_Hashmap_Get_LargeBlock -run=NONE`. (NONE is selected as a mnemonic regexp that is unlikely to match any of your tests.)

**Comment by titanous** [comment]
In the future please use a forum for questions about Go, see https://golang.org/wiki/Questions.
