### ISSUE TITLE
x/tools/godoc: code section highlighting includes line numbers

### ISSUE THREAD

**Issue by ALTree** [golang/go#18561]
```
go version devel +067bab00a8 Sat Jan 7 16:53:25 2017 +0000 linux/amd64
```

### What did you do?

Click, for example, on `CloseNotifier` in https://golang.org/pkg/net/http/#CloseNotifier to access the source with the relevant code highlighted.

### What did you expect to see?

Highlighted section of source code that does not include line numbers.

### What did you see instead?

Line numbers are included in the highlighted section. Example:
https://golang.org/src/net/http/server.go?s=6099:6922#L157

I don't know if that's done on purpose (I doubt it), but it's rather ugly.

**Comment by ALTree** [comment]
cc @kevinburke who filed and fixed the (somewhat) similar #18279, and may be interested in this one.

**Comment by kevinburke** [comment]
Thanks, looking

**Comment by kevinburke** [comment]
looks a lot better now: <img src="https://monosnap.com/file/6jfeFBG6tzhy3ZErqYWn6BfZ4fyk1R.png">

**Comment by ALTree** [comment]
Definitely!

I can't help with the review process because I've never touched godoc, so leaving for someone else to review.
