### ISSUE TITLE
x/net/idna: typo breaks cloud.google.com/go/bigquery

### ISSUE THREAD

**Issue by thylong** [golang/go#18574]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/thylong/www/repositories"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dk/fklfd7ns5vs4r6g0yf7trjhw0000gp/T/go-build270511806=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
go get cloud.google.com/go/bigquery

### What did you expect to see?
No output, just download and install the package.

### What did you see instead?
    # golang.org/x/net/idna
    src/golang.org/x/net/idna/idna.go:470: undefined: bidirule.ValidString

This issue, regardless its complexity is very critical.

**Comment by bradfitz** [comment]
Run `get get -u`. You have an old x/net/text package.

**Comment by thylong** [comment]
Thanks for the tips !

**Comment by fredmenez** [comment]
typo fix : golang.org/x/text is the one to update
