### ISSUE TITLE
all: string(2) doesn't throw an error

### ISSUE THREAD

**Issue by Simeon4x** [golang/go#18578]
Go 1.7.3

### What did you do?

string(1)
https://play.golang.org/p/rut8mpiipO

### What did you expect to see?

"cannot convert 1 to type string" - compile error 

### What did you see instead?

Integer has been converted in a string empty value.

**Comment by ALTree** [comment]
Spec:

> Conversions to and from a string type
> Converting a signed or unsigned integer value to a string type yields a string containing the UTF-8 representation of the integer

The fact that this is bad is #3939, labelled go2 since it can't be changed now (because of the Go 1 compatibility promise).
