### ISSUE TITLE
how to cross compile go code from Linux to windows

### ISSUE THREAD

**Issue by shageeth** [golang/go#18587]
I want to know the way to cross compile my Go language code from Linux to windows.I set the environment variables GOARCH and GOOS to "AMD64" and "windows" respectively. when i build go lang code it's generating executable file for Linux not for windows. I don't know what's happening?

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
