### ISSUE TITLE
Can't access Go libraries after cloning project

### ISSUE THREAD

**Issue by ashish29agre** [golang/go#18591]
### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

OS: macOS Sierra

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s5/lxpss5xs7gg15nvg58m8tpyr0000gr/T/go-build050028115=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I had a project with libraries developed somedays back. I completed and pushed to git repo on gitlab. Days after i cloned that repository and when i tried to build i 

### What did you expect to see?
I expected to get all the libraries clone along with my source code. 

### What did you see instead?
But i only got library folder structure and files inside them are missing.

`go get -u github.com/jinzhu/gorm
package github.com/jinzhu/gorm: directory "/testapp/src/github.com/jinzhu/gorm" is not using a known version control system`

Question open on stackoverflow as well:
http://stackoverflow.com/questions/41565764/cant-access-go-libraries/

**Comment by ianlancetaylor** [comment]
Remove the directory `$GOPATH/src/github.com/jiznhu/gorm" and run `go get` again.

In general, please ask questions on a forum, not in the issue tracker.  See https://golang.org/wiki/Questions .

Closing.  Please reopen if you think there is a bug here.
