### ISSUE TITLE
crypto/tls: session resumption (session id caching)

### ISSUE THREAD

**Issue by tam7t** [golang/go#18607]
### What version of Go are you using (`go version`)?

`go version go1.7.4 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

### What did you do?
I have 2 web servers, one that supports TLS session resumption based on a session cache and another that supports session cache and session tickets.

https://play.golang.org/p/9n4OZRjqHh

### What did you expect to see?

I had expected the 2nd connection to each server to resume the session.

### What did you see instead?

`DidResume` is only `true` for the server that supports session _ticket_ resumption.

It appears that session ID caching is not supported in client or server mode. Perhaps the documentation for `ClientSessionCache` could be a bit more explicit that it is only a cache for session tickets.

**Comment by FiloSottile** [comment]
Session ID caching is not supported in neither client nor server.

I guess the client side can be documented in `Config.ClientSessionCache`. Not sure where the docs for the server side could go.

I had to look at the code myself a week ago to confirm this.

**Comment by Kanshiroron** [comment]
Any plan on implementing it?
The thing is without this feature, it's impossible to configure a load balancer with sticky TLS sessions (without TLS offload)

**Comment by FiloSottile** [comment]
No plans I'm aware of. You can open a new issue to request the feature.

Almost sure you could implement sticky TLS on top of tickets with #19199, but the discussion should move away from this closed issue.
