### ISSUE TITLE
doc: mention required OS changes in the release notes

### ISSUE THREAD

**Issue by khm** [golang/go#18610]
### What version of Go are you using (`go version`)?

Go 1.8 release candidate 1.

### What operating system and processor architecture are you using (`go env`)?
Plan 9 from Bell Labs, any supported architecture.

### What did you do?

Attempted to run net_test.go

### What did you expect to see?

Overwhelming and unrelenting success

### What did you see instead?

FAIL: TestConnClose because of an unknown control request

### Epilogue

In the draft release notes for Go 1.8[1], we get the following:

> The Plan 9 port's networking support is now much more complete and matches the behavior of Unix and Windows with respect to deadlines and cancelation. 

Sounds great! but it fails to mention that this change requires modification of the OS itself; specifically, as described in a Go commit message[2], which refers to (but does not specify) a different Github repository entirely, as 'the' Plan 9 kernel[3].  This change is not present in the latest ISO made available by Bell Labs.

In the end, it's a simple change that other Plan 9 kernels can easily accomodate, but it would be very kind of you if this sort of OS-scope change were at least mentioned somewhere in the release notes, even if it's just a tiny asterisk with an href to a changelog somewhere.  It would save us some detective work, and make it easier for us to use Go.

[1] https://beta.golang.org/doc/go1.8
[2] https://github.com/golang/go/commit/3d1ae4b75c77a88ba3b20ada874f1027365a8060
[3] https://github.com/0intro/plan9-contrib/commit/390a902aece1c009c614d3fdb3757e0470a93304

**Comment by andlabs** [comment]
(Are the ISOs "made available by Bell Labs" even current anymore?)

**Comment by ALTree** [comment]
According to the documentation (assuming that the [Plan9 wiki page](https://github.com/golang/go/wiki/Plan9) is not outdated), we support:

- Plan 9 from Bell Labs (386 and arm) kernel (https://9p.io/plan9)
- 9front amd64 kernel (http://9front.org/)
- Charles Forsyth's 9k (amd64) kernel (https://bitbucket.org/forsyth/plan9-9k)

I read your report, but it's not clear to me whether that commit actually broke go on one of the supported kernels, or just on some other kernel/fork. There're builders for those 3, and although the x64 one does not feel very well at the moment, it succeeded at least once the last week, so I assume that the `net` change didn't broke it.

What's "the latest ISO made available by Bell Labs", exactly? Is it something different than https://9p.io/plan9 ?

**Comment by bradfitz** [comment]
Sure, we could add some text to the Go 1.8 release notes.

I have no clue what to say. The Plan 9 community at least from my perspective doesn't look very organized, with code and kernels scattered all over the place. Maybe I have the wrong perspective.

@0intro, I can write the text if you tell me what to say. Or you can send a CL.

**Comment by khm** [comment]
Hi,

Thanks for your reply.

On Wed, Jan 11, 2017 at 09:12:32AM -0800, Alberto Donizetti wrote:
> 
> - Plan 9 from Bell Labs (386 and arm) kernel (https://9p.io/plan9)
> - 9front amd64 kernel (http://9front.org/)
> - Charles Forsyth's 9k (amd64) kernel (https://bitbucket.org/forsyth/plan9-9k)

The 9p.io/plan9 link is a mirror of the Bell Labs distribution.  Both it
and the 9front kernel lack the required changes.  The plan9-9k kernel is
the only one that got the change.  The 9front people did not know the
change was required until someone tried Go 1.8rc1 -- hence the request
for documentation.

khm

**Comment by ALTree** [comment]
Thanks for the clarification. Leaving for brad and/or 0intro.

**Comment by 0intro** [comment]
Sorry for the delay. It seems I've missed this conversation for some reason.

Following the change in [CL 31271](https://golang.org/cl/31271), you have to apply a change to the Plan 9 kernel to be able to handle the "close" message on the TCP connection control file. The "close" message in analogous to the "hangup" message, but closes the TCP connection gracefully with a FIN instead of a RST.

The patch is available here: [9-tcp-close](http://9legacy.org/9legacy/patch/9-tcp-close.diff)

This is already documented on the [Plan 9 wiki page](https://github.com/golang/go/wiki/Plan9), which is up-to-date.

I'll propose a CL to document the new requirement in the Go 1.8 release notes.
