### ISSUE TITLE
cmd/vet: new shadow false positive in 1.8 when using range iteration

### ISSUE THREAD

**Issue by tamird** [golang/go#18613]
Given the following program:
```go
package main

import (
	"context"
	"fmt"
	"strings"
)

func main() {
	ctx := context.Background()
	{
		// go1.7.4, go1.8rc1: declaration of "ctx" shadows declaration at shadow.go:9
		ctx, cancel := context.WithCancel(ctx)
		cancel()
	}
	fmt.Println(ctx)

	var strs []string
	for _, str := range strs {
		// go1.8rc1: declaration of "str" shadows declaration at shadow.go:19
		str := strings.Replace(str, "1", "2", -1)
	}
}
```

There are two `go tool vet -shadow` false positives present, but one of them is new in go1.8.

This code is also at https://github.com/tamird/vet-bugs. cc @petermattis

**Comment by bradfitz** [comment]
(I don't follow vet, but will conservatively mark this as Go1.8Maybe until owners say otherwise)

**Comment by ianlancetaylor** [comment]
I'm sure I'm missing something, but why is that a false positive?  There is a `str` variable declared in the for/range statement, and it is shadowed by the `str` variable defined using `:=` within the loop.

**Comment by robpike** [comment]
Both of those messages from vet are correct.

**Comment by tamird** [comment]
I've updated the program below to demonstrate why this is a false positive. Note that the block

```go
	var strs []string
	for _, str := range strs {
		_ = str

		str := "foo"
		_ = str
	}
```

does **not** produce a vet warning.

```go
package main

import (
	"context"
	"strings"
)

func main() {
	ctx := context.Background()
	{
		// go1.7.4, go1.8rc1: declaration of "ctx" shadows declaration at shadow.go:9
		ctx, cancel := context.WithCancel(ctx)
		_ = ctx
		cancel()
	}

	var strs []string
	for _, str := range strs {
		_ = str

		// no warning
		str := "foo"
		_ = str
	}
	for _, str := range strs {
		// go1.8rc1: declaration of "str" shadows declaration at shadow.go:25
		str := strings.Replace(str, "1", "2", -1)
		_ = str
	}
}

```

Please reopen this issue. Either this is a false positive, or the behaviour is inconsistent.

**Comment by robpike** [comment]
The behavior is inconsistent but the documentation also says the check is experimental. Honestly, I'd rather delete it than fix it; the approach is all wrong.

**Comment by tamird** [comment]
I'd be OK with deleting it, for what it's worth. I believe tools like https://github.com/dominikh/go-staticcheck can fill in the gaps.
