### ISSUE TITLE
Go mobile is not downloading on my OSX 10.12 system.  What is going on?

### ISSUE THREAD

**Issue by shyamalschandra** [golang/go#18614]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

Mac OSX 10.12.1 Sierra

### What did you do?

I followed the instructions after successfully installing Go on my OSX 10.12.1:
https://godoc.org/golang.org/x/mobile/cmd/gomobile

### What did you expect to see?

A successful installation of go mobile for my platform.

### What did you see instead?

Nothing happen.  What is going on?  Can you please help?

When I do `gomobile init`, nothing happens.  What is missing?

**Comment by bradfitz** [comment]
I think the delay here is just it downloading the SDK during `gomobile init`.

But for questions about Go, see https://golang.org/wiki/Questions.

@eliasnaur, what is the recommended mailing list for gomobile users?

**Comment by hyangah** [comment]
https://github.com/golang/mobile says golang-nuts@ mailing list.
