### ISSUE TITLE
misc/cgo/testcshared: 1.8rc1 build from source fails on Yakkety on testcshared

### ISSUE THREAD

**Issue by karalabe** [golang/go#18611]
```
$ git rev-parse HEAD
3de6e96e4b8147f5267a2e8218a7c780b09a434f
```

Build log: https://gist.github.com/karalabe/4bb005aec52ea941ac1cdfd8be867695

**Comment by ianlancetaylor** [comment]
Looks like your `env` program is not behaving as expected.  Assuming you use bash as your shell, what does `type env` print?

**Comment by bradfitz** [comment]
Trying to reproduce in a Yakkety Docker container, I also see:

```
--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
        exec_linux_test.go:81: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted, output: 
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
        exec_linux_test.go:81: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted, output: 
--- FAIL: TestEmptyCredGroupsDisableSetgroups (0.00s)
        exec_linux_test.go:129: fork/exec /usr/bin/whoami: operation not permitted
--- FAIL: TestUnshare (0.00s)
        exec_linux_test.go:177: Cmd failed with err fork/exec /bin/cat: operation not permitted, output: 
--- FAIL: TestGroupCleanupUserNamespace (0.00s)
        exec_linux_test.go:238: Cmd failed with err fork/exec /usr/bin/id: operation not permitted, output: 
FAIL
FAIL    syscall 0.074s
```

**Comment by bradfitz** [comment]
Actually, those failures I hit are only because I was running as root in a privileged container.

But after fixing that, I'm unable to reproduce this bug. Running `all.bash` passes for me in a Yakkety container.

Removing Go 1.8 milestone, waiting for info.

**Comment by karalabe** [comment]
@ianlancetaylor Good catch. `evn` actually pointed to a binary within my GOPATH bin. If I replace/delete that, everything works fine with building Go. My curiosity now is how did an `env` get into my GOPATH in the first place. Looking at it in a hex editor, it's definitely a Go binary. Anyway, this issue is unrelated to the Go repository anymore. Closing. Thanks!

**Comment by karalabe** [comment]
Ha! https://github.com/joefitzgerald/go-config/tree/master/spec/tools/env

**Comment by ianlancetaylor** [comment]
We could consider setting PATH to start with /bin:/usr/bin, but that would bug people who specifically set their PATH differently to run different tools.  I guess best choice is to leave as is.
