### ISSUE TITLE
x/tools/godoc/vfs: NameSpace.bind not working on Windows

### ISSUE THREAD

**Issue by alexsaveliev** [golang/go#18629]
### What version of Go are you using (`go version`)?

`go version go1.7 windows/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\projects\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=.....=/tmp/go-build -gno-record-gcc-
switches
set CXX=g++
set CGO_ENABLED=1
```

### What did you do?

Hello, I think that there is a missing way to set up a `vfs.NameSpace` filesystem backed up by Windows filesystem without specific root to be able to:

```
ns.Open("C:\\foo\\bar") // gives content of C:\foo\bar
ns.Open("D:\\qux") // gives content of D:\qux
```

Why do I need it? Imagine a local file system backed by in-memory map (pretty common scenario in language server protocol where some files may be read directly from disk and some may be provided by a client while being edited). Sometimes it's impossible to predict what parts of local file system may be needed and caller may be unable to declare all the potential mount points.

`fs.Bind("/", vfs.OS("/"), "/", vfs.BindBefore)` does not work on Windows because `PATH`  being resolved into `\PATH` and Windows FS is unable to access such a file.

I think it's may be worth to add such a possibility and resolve paths on Windows specific way (remove "\" prefix if there is any). What do you think?

Test case that fails on Windows

```go
package vfs_test

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/tools/godoc/vfs"
)

func TestOpen(t *testing.T) {

	tmpDir, err := ioutil.TempDir("", "vfs-localfs")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)
	if err = os.MkdirAll(tmpDir, 0700); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(tmpDir, "foo")
	if err = ioutil.WriteFile(file, []byte("bar"), 0600); err != nil {
		t.Fatal(err)
	}

	fs := vfs.NameSpace{}
	fs.Bind("/", vfs.OS("/"), "/", vfs.BindAfter)

	_, err = fs.Open(file)
	if err != nil {
		t.Errorf("Cannot read local file (%s)", err)
	}
}
```

I have a pull request in mind, if needed.

Sincerely, 
Alex

**Comment by mattn** [comment]
You should call fs.Bind with specifying second argument `vfs.OS(tmpdir)`.

```go
package vfs_test

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/tools/godoc/vfs"
)

func TestOpen(t *testing.T) {

	tmpDir, err := ioutil.TempDir("", "vfs-localfs")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)
	if err = os.MkdirAll(tmpDir, 0700); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(tmpDir, "foo")
	if err = ioutil.WriteFile(file, []byte("bar"), 0600); err != nil {
		t.Fatal(err)
	}

	fs := vfs.NameSpace{}
	fs.Bind("/", vfs.OS(tmpDir), "/", vfs.BindAfter)

	_, err = fs.Open("/foo")
	if err != nil {
		t.Errorf("Cannot read local file (%s)", err)
	}
}
```

The path to call fs.Open should be the virtual path, not physical.

**Comment by alexsaveliev** [comment]
@mattn 

> You should call fs.Bind with specifying second argument vfs.OS(tmpdir).

I think that your proposal solves only particular case, where I assume that all files I will work with are located on the same logical disk, e.g. `C:\Users\alexsaveliev\AppData\Local\Temp\`. But if there is a need to access any file on any logical disk, there is currently no way to make all of them accessible without iterating over them and binding `C:\` => `C:\`, `D:\` => `D:\`, and so on which I find inconvenient, because on Unix it's enough to bind `/` => `/` and you'll see all the files on all partitions.

Is there a way to call `fs.Bind` once to make the following snippet work?

```
fs.Bind(?)
fs.Open("C:/foo");
fs.Open("D:/foo");
fs.Open("E:/foo");
...
```
will not work.

> The path to call fs.Open should be the virtual path, not physical.

It is. My tests says `fs.Open("/foo")` - I expect to open virtual file `/foo` located somewhere in temp dir on local FS

Thanks

**Comment by mattn** [comment]
Then, you can call ns.Bind for each drives.
```go
package main

import (
	"io"
	"log"
	"os"

	"golang.org/x/tools/godoc/vfs"
)

func main() {
	fs := vfs.NameSpace{}
	fs.Bind("/C", vfs.OS("C:/"), "/", vfs.BindAfter)
	fs.Bind("/D", vfs.OS("D:/"), "/", vfs.BindAfter)
	fs.Bind("/E", vfs.OS("E:/"), "/", vfs.BindAfter)

	file, err := fs.Open("/C/Windows/System32/drivers/etc/hosts")
	if err != nil {
		log.Fatalf("Cannot read local file (%s)", err)
	}
	io.Copy(os.Stdout, file)
}
```

**Comment by alexsaveliev** [comment]
@mattn 

Thanks for the suggestion, will do it this way

**Comment by keegancsmith** [comment]
@alexsaveliev I don't have a windows machine to test on, but this may possibly work without having to mount each drive:
```
fs := vfs.NameSpace{}
fs.Bind("/", vfs.OS(""), "/", vfs.BindAfter)
```

**Comment by keegancsmith** [comment]
@mattn given that `fs` is a `vfs.NameSpace` shouldn't you be using virtual paths. This instead
```
file, err := fs.Open("/C:/Windows/System32/drivers/etc/hosts")
```

**Comment by mattn** [comment]
@keegancsmith doesn't work because it call

```
os.Open(`\C:\Windows\System32\drivers\etc\hosts`)
```

**Comment by keegancsmith** [comment]
@mattn do you think we could adjust the `vfs.OS` implementation for windows such that `resolve` does the "right" thing for `vfs.OS("")`?

**Comment by mattn** [comment]
Sorry, I don't think that it is "right".
