### ISSUE TITLE
unsupported GOARCH mipsel

### ISSUE THREAD

**Issue by deepch** [golang/go#18622]
You have no plans to support mipsel?

GOOS=linux GOARCH=mipsel go build *.go
unsupported GOARCH mipsel

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

You didn't even attempt to use the bug report template.

**Comment by deepch** [comment]
perhaps it means that there is no support thanks for your reply.

**Comment by bradfitz** [comment]
Go supports 32-bit MIPS in big and little endian modes.

You spelled it differently, and you never even said which version of Go you're running.

See https://beta.golang.org/doc/go1.8#ports

**Comment by minux** [comment]
The correct GOARCH for little endian mips is spelled "mipsle", not "mipsel".

The latter one is a joke created by Debian. (Because little endian reverse
the byte order, they also reversed the letter LE to form el.)

**Comment by deepch** [comment]
Thanks for the answer.
I updated to 1.8 rc1.
closed

**Comment by deepch** [comment]
Thanks all work
CPU xburst
