### ISSUE TITLE
encoding/csv: confusing about flush

### ISSUE THREAD

**Issue by visaxin** [golang/go#18646]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.3

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

```
fileSink, err := os.OpenFile("./text.txt", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0655)
	if err != nil {
		return
	}

	csv := csv.NewWriter(fileSink)
	csv.Write([]string{"haha"})
	csv.Flush()
	//fileSink.Sync()
	time.Sleep(time.Minute)
```

After csv.Flush, the file doesn't Sync. 

Shouldn't sync after csv.Flush?

**Comment by bradfitz** [comment]
Flush only does as is documented:

> Flush writes any buffered data to the underlying io.Writer. 

If you want to do something else to your `*os.File`, that's your job.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by visaxin** [comment]
@bradfitz  thanks for your response!
