### ISSUE TITLE
net/url: documentation - 0xAB is confusing

### ISSUE THREAD

**Issue by riking** [golang/go#18642]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8beta

### What did you do?
The documentation for url.PathUnescape is confusing, as 0xAB is an actual hexadecimal byte - implying that the 0xAB byte is somehow special. https://beta.golang.org/pkg/net/url/#PathEscape

### What did you expect to see?
Letters such as %YZ -> 0xYZ should be used for placeholder characters not referencing specific bytes in the context of string transformation.

**Comment by bradfitz** [comment]
I think the very next sentence would clear up any confusion:

> It returns an error if any % is not followed by two hexadecimal digits.

But sure, we can insert a word or two. I don't like %YZ, though.

**Comment by riking** [comment]
Yeah… that was me struggling to come up with something that made sense.

>I think the very next sentence would clear up any confusion:
It took me some googling of what U+00AB was to realize that :)
