### ISSUE TITLE
blog: typo in "Go Concurrency Patterns: Context"

### ISSUE THREAD

**Issue by slimsag** [golang/go#18656]
The sentence:

> The best way to see how to use the context package is through a **worked** example.

Located directly above the ["Example: Google Web Search"](https://blog.golang.org/context#TOC_3.) header

Hope this is useful somehow :)

**Comment by ALTree** [comment]
What's the typo? "worked example"? https://www.google.it/search?q=worked+example

**Comment by slimsag** [comment]
Whoops, my mistake. Sorry!
