### ISSUE TITLE
cmd/go: refactor into multiple packages

### ISSUE THREAD

**Issue by rsc** [golang/go#18653]
It would help to split the go command into some packages,
in particular to separate out package loading from package building.
I have a plan and will send CLs at the start of Go 1.9
to try to get ahead of any possible merge conflicts.

CLs will be attached to this issue.

**Comment by mvdan** [comment]
Would this cover the need for https://github.com/kisielk/gotool?

**Comment by mvdan** [comment]
> Would this cover the need for https://github.com/kisielk/gotool?

All the new packages are internal, so it seems like it won't replace gotool just yet.

**Comment by rsc** [comment]
There is no intent to expose the internals of the go command for direct import by programs that want to behave like it. I would prefer if those programs invoked the go command to find out what they need to find out: the API is the binary itself, not the Go package. Using the binary means that when some detail of the go command changes, all those other tools don't need to be updated. I'd be happy to talk about what those tools need.

**Comment by mvdan** [comment]
@rsc this sounds like a good idea. Should I open a separate issue and ping people who'll probably be interested?

**Comment by rsc** [comment]
Sure, please open a new issue 'cmd/go: define command-line API for tools' and please list there the kinds of things your tools need to find out from the go command. Thanks.

**Comment by shurcooL** [comment]
I'm very happy about this happening. I've been considering making a proposal and try to motivate doing exactly this. 👍

I'll also mention #11490 here - that issue might be worth revisiting and updating now that this is happening, since it's relevant.

**Comment by bradfitz** [comment]
This happened.
