### ISSUE TITLE
Problem opening directories with software written in Go, while using Dokany FUSE

### ISSUE THREAD

**Issue by qnorsten** [golang/go#18659]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Q\A
ppData\Local\Temp\go-build149491418=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

This issue is directly connected to and has been discussed in https://github.com/dokan-dev/dokany/issues/406. 
Just creating it here also in case the go community can help solve the problem (I am not sure if it is a dokany problem or something that can be fixed in go, as it only affects the window implementation for opening file and directories) 

### What did you do?
Created a mounted file system on Z: with the command **"mirror.exe Z:",** using  the dokany-fuse mirror sample. Available after installation of https://github.com/dokan-dev/dokany/wiki/Installation . It is by standard  located in 
C:\Program Files\Dokan\Dokan Library-1.0.1\sample\fuse_mirror", and you need Cygwin to be installed to run it.

Then tried accessing the mounted file system (Z:) from any go application , for example https://gist.github.com/klauspost/5f87caf402a8abf369d5#file-test-go-L42

### What did you expect to see?
The go application to be able to access the files and folders of the mounted filesystem. 

### What did you see instead?
Accessing the mounted filesystem from any go application fails as go tries to open directories as a file and no error is returned from dokany so error messages such these below is given.  (see https://github.com/dokan-dev/dokany/issues/406 for some more technical information. 

With UNC paths:

> 
    Local file system at \\?\X:: Failed to open directory: \\?\X:: Readdir \\?\X:: The system cannot find the path specified.

Without UNC paths:

>     Local file system at X:: failed to read directory "X:\": Readdir X:: The system cannot find the path specified.

**Comment by kardianos** [comment]
As far as I can tell from all the comments, this is on dokeny, not Go. It looks like Dokeny should be returning an error when it isn't. Dokeny isn't written in Go, nor is the mirror driver or other fs driver in question. Current behavior has been working just fine on windows for many years.

While I understand that it is Go that triggered this bug, I don't see how this needs Go expertise to solve. Am I wrong?
