### ISSUE TITLE
x/arch/x86/x86asm: Mem.Disp is positive for negative displacements

### ISSUE THREAD

**Issue by minux** [golang/go#18666]
```
package main

import "golang.org/x/arch/x86/x86asm"

func main() {
	text := []byte{0x48, 0x8d, 0x05, 0x0d, 0xea, 0xff, 0xff}
	inst, err := x86asm.Decode(text[:], 64)
	if err != nil {
		panic(err)
	}
	println(x86asm.GNUSyntax(inst))
}
```

The program outputs:
`lea 0xffffea0d(%rip),%rax`
which is obviously incorrect. The correct disassembly should be:
```
$ echo '0x48, 0x8d, 0x05, 0x0d, 0xea, 0xff, 0xff' | tr -d ',' | llvm-mc -disassemble
leaq	-5619(%rip), %rax
```

The problem is that, in the decoded arg, the Disp is int64(0xffffea0d). Whereas it should be a negative number instead as the displacement is always signed.

I haven't checked other use of Mem, but I suspect they all have this problem.

/cc @rsc

**Comment by josharian** [comment]
Possibly related: #8000

**Comment by josharian** [comment]
If it is related, https://codereview.appspot.com/100480046/ might be of use.

**Comment by minux** [comment]
Yeah, it's related.

It seems we need even better tests for x86asm.
I'm quite surprised that x86asm is still missing basic instructions
(#18665) as I think it has been very thoroughly tested against multiple
disassemblers.

**Comment by minux** [comment]
This is indeed a dup of #8000.
Closing.
