### ISSUE TITLE
cmd/gofmt: gofmt should rewrite snake-case.

### ISSUE THREAD

**Issue by timakin** [golang/go#18669]
When I declare a snake-case value like `FOO_BAR_CONST`, golint warn me to redefine with camel-case.
But gofmt won't do anything for it.
It should automatically rewrite a snake-case value to camel-case or pascal-case.
Is it too much?

**Comment by minux** [comment]
gofmt (without -s) shouldn't change anything except white spaces.
Changing the identifier naming is obviously too much for gofmt.

**Comment by dgryski** [comment]
In the past I've done this with
```
golint |
   awk '/should be/{printf("gofmt -w -r %c%s -> %s%c .\n", 39, $9, $12, 39)}' |
   sh
```

**Comment by josharian** [comment]
Thanks for the suggestion. But if your program contained:

```go
const (
  FOO_BAR_CONST = 0
  FooBarConst = 1
)
```

Then gofmt would make your program cease to compile. And if someone else imported your package and used `p.FOO_BAR_CONST`, then changing it to `FooBarConst` would make someone else's code cease to compile.

gofmt must always be safe to run, so we cannot do this.

**Comment by timakin** [comment]
@josharian 
Thank you for a critical example and your polite response.
This seems bad and I can figure out the risk.
