### ISSUE TITLE
README.md: outdated install instructions, GOROOT setting is too prominent

### ISSUE THREAD

**Issue by ALTree** [golang/go#18675]
CL c497c9ea4bbe90833ee0bb8660fe91b8f17adee7 updated the installation instructions in `doc/install.html` to clarify that GOROOT should only be set when using a custom install path. This fixed #6613 (doc: clarify that GOROOT is only necessary for non-standard install locations), but the `README.md` file (the one you see when you visit github.com/golang/go) was not updated, and the **Binary distribution** section still starts like this:

> If you have just untarred a binary Go distribution, you need to set the environment variable $GOROOT

which is not ideal.

**Comment by minux** [comment]
What if we make cmd/go use the new os.Executable API to find GOROOT
automatically? Then we can remove mention of GOROOT in all user facing
documents.

**Comment by kardianos** [comment]
@minux Only if you require the go exec to live in the GOROOT, which is different then today.

**Comment by minux** [comment]
Let's discuss the GOROOT auto-detection proposal in #18678.
