### ISSUE TITLE
x/mobile: gomobile generated apk is too big

### ISSUE THREAD

**Issue by seaguest** [golang/go#18674]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/seaguest/go"
GOTOOLDIR="/home/seaguest/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build907249124=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
`
I just tried to write some SDK api with gomobile, and introduced it in my android project, the api are quite simple, but the generated libgojni.so is too big (about 10M), which makes the apk very big, it at least incresed 10M of the size.
`
### What did you expect to see?
how could I shrink the apk size? 

### What did you see instead?
the apk file's size increased at least 10 M. if gomobile compiled sdk is not introduced, the apk is 1.5M, however if it is introduced then the apk becomes 15M.

**Comment by ALTree** [comment]
Essentially a dup of #14465 (which is also a dup of the more generic #6853).

> how could I shrink the apk size?

See [comment in the old 14465 thread](https://github.com/golang/go/issues/14465#issuecomment-187323718) for some tips.

Also note that the Go project does not use its bug tracker for general discussion or asking questions. It's only for tracking bugs and proposals. If you have a question, please see https://github.com/golang/go/wiki/Questions for a list of better places for asking questions.
