### ISSUE TITLE
Channel unexpectedly blocked by misoperation

### ISSUE THREAD

**Issue by ychen11** [golang/go#18679]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4 

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

* Case 1
This is the first file
```go
var hb chan string

func a() {
  hb = make(chan string, 1)
  ticker := time.NewTicker(1 * time.Second)
  for t := range ticker.C {
    heartbeat <- "hb"
    log.Printf("Time at : ", t)
  }
}

func b() {
  for {
    log.Printf(<-hb)
  }
}
```

This is the second file
```go
func Main() {
  go a()
  go b()
}
```

Actually I added something which could block the function Main() to make it blocked here forever. No need to mention those.

The output occasionally looks like the hb channel is blocked by something: logs in both function a and b were not printed at all.
And sometimes, the code could print out the log: ```Time at``` periodically.

* Case 2
So I changed my code to
```go
var hb chan string

func ini() {
  hb = make (chan string, 1)
}

func a() {
  //hb = make(chan string, 1)
  ticker := time.NewTicker(1 * time.Second)
  for t := range ticker.C {
    heartbeat <- "hb"
    log.Printf("Time at : ", t)
  }
}

func b() {
  for {
    log.Printf(<-hb)
  }
}
```

```go
func Main() {
  ini()
  go a()
  go b()
}
```

All things are normal now.

### What did you expect to see?
I think, the b() goroutine receives the channel hb without initialization, just a declared channel in the case 1, but this problem should be warned in compiling process.

**Comment by minux** [comment]
your code has a data race on hb.

This is not a bug of Go, and in general the compiler can't detect such data
races.
Besides, Go compiler don't issue warnings.

please ask further questions on other mediums, see
https://golang.org/wiki/Questions.

**Comment by ychen11** [comment]
Very, very sorry to hear about it: **This is not a bug of GO**

**Comment by minux** [comment]
Of course it's not a bug of Go.

On the other hand, Go does provide race detector to help detecting those
kind of data races at runtime.
blog.golang.org/race-detector
