### ISSUE TITLE
x/crypto/poly1305: multiple definition of `poly1305Mask'

### ISSUE THREAD

**Issue by mappu** [golang/go#18673]
Hi, this bug report is for the x/crypto package, but the github doesn't have its dedicated issue tracker, so sorry if it's misplaced.

### What version of Go are you using (`go version`)?
`go version go1.8rc1 windows/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\mappu\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\cygwin\tmp\go-build713941879=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### What did you do?
1. Have a program that uses golang.org/x/crypto/poly1305 and also CGO
2. Update from old commit `e311231e83195f401421a286060d65643f9c9d40` to new commit `2f8be38b9a7533b8763d48273737ff6e90428a96`
3. Attempt to build using the updated library

### What did you expect to see?
normal successful build

### What did you see instead?
```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\cygwin\tmp\go-link-667453455\go.o:(.text+0x615bb0): multiple definition of `poly1305Mask'
C:\cygwin\tmp\go-link-667453455\go.o:(.text+0x615ba0): first defined here
/usr/lib/gcc/x86_64-w64-mingw32/5.4.0/../../../../x86_64-w64-mingw32/bin/ld: $WORK\backup-tool\_obj\exe\a.out.exe: .rsrc merge failure: corrupt .rsrc section
collect2: error: ld returned 1 exit status
```

The build succeeds if i revert to the older x/crypto commit.

**Comment by mappu** [comment]
I can confirm the updated commit abc5fa7 did fix the issue.

**Comment by minux** [comment]
Thanks for the confirmation!
