### ISSUE TITLE
go to WebAssembly

### ISSUE THREAD

**Issue by SerkanSipahi** [golang/go#18684]
Is there any plan for a go tool that transform go to webassembly? There is nothing/useful out there !
Look at this: https://www.reddit.com/r/golang/comments/5ai8ct/webassembly_browser_preview/ ... and ~~the last (thread) sentence of the bottom~~ some of the tread sounds not good (see below)

>...
> i see a bright future for WebAssembly but if Go misses the boat chances are that others will eat its lunch(i.e. Rust, Swift or whatever language will be first to compile to wasm)
>...
>VR/AR/smellovision can happen on the web too once wasm is available in browsers.

**Comment by cherrymui** [comment]
cc @griesemer

**Comment by SerkanSipahi** [comment]
I will be good when this come from https://github.com/golang/go and not from the community !

**Comment by bradfitz** [comment]
There is ongoing llvm-go work happening now. We'll probably get wasm out of that. We can track this separately later. The llvm work is happening regardless of whether this wishlist bug is open.

**Comment by SerkanSipahi** [comment]
@bradfitz do you have any release(alpha, beta, rc, etc) date? 

nice :)
>We'll probably get wasm out of that

**Comment by bradfitz** [comment]
No, sorry.

**Comment by minux** [comment]
On Tue, Jan 17, 2017 at 11:35 AM, Brad Fitzpatrick <notifications@github.com
> wrote:

> There is ongoing llvm-go work happening now. We'll probably get wasm out
> of that.
>
Any details regarding whether is based on the gc or gofrontend?

From the current activity on the gofrontend repository, it looks like
llvm-go will be using gofrontend, not gc?

**Comment by bradfitz** [comment]
gofrontend

**Comment by bradfitz** [comment]
I created a new WebAssembly tracking bug at #18892 for people to watch.
