### ISSUE TITLE
release: after installing via MSI installer, prompt says "go is not a recognized command"

### ISSUE THREAD

**Issue by rakyll** [golang/go#18680]
1. Fresh install Go on Windows via the the MSI installer (version: go1.8rc1).
2. After installation is complete, start a new command prompt.
3. Type `go` into the prompt.

Actual result:
```
"go" is not recognized as an internal or external command, operable program or batch file.
```

Expected result:
The go binary is found.

**Comment by minux** [comment]
Does the go installer modify the system %PATH%? What's the system %PATH%
after installation?

From the source code, it does look like it should modify the system %PATH%.
https://github.com/golang/build/blob/master/cmd/release/releaselet.go#L647

**Comment by alexbrainman** [comment]
> "go" is not recognized as an internal or external command, operable program or batch file.

I cannot reproduce it. It does work for me. I am running Windows 7.

Perhaps something is not quite right with your step 2.
https://blogs.msdn.microsoft.com/oldnewthing/20150915-00/?p=91591/ for the background.

> Does the go installer modify the system %PATH%?

It does modify mine.

Alex

**Comment by as** [comment]
How was the new command prompt started? On most systems I've noticed running CMD.exe in the existing console doesn't work. It has to be a new window.

**Comment by rakyll** [comment]
I am able to produce it on 32-bit Windows 8 and 10.

My %PATH% is not modified.

I am opening a new command prompt window via a right click on the Start button.

**Comment by broady** [comment]
Couldn't reproduce on a fresh VM (Windows Server 2016 Datacenter - version 1607, OS version 14393.693).

Also couldn't reproduce on a 64-bit Windows 10. Could be specific to 32-bit?

Related to #17602 perhaps?

**Comment by rakyll** [comment]
I used

```
msiexec /l*v install.log /i C:\Users\jbd\Downloads\go18rc.windows-386.msi
```

to gather logs but installation succeed (at my third retry) and added GOROOT and modified the GOPATH. I don't understand what makes this inconsistently fail.

I haven't updated the installation path, I am not thinking it might be related to #17602.

**Comment by alexbrainman** [comment]
> and modified the GOPATH

Go installer does not add GOPATH variable. Did you mean it modified PATH?

Alex

**Comment by alexbrainman** [comment]
> I am able to produce it on 32-bit Windows 8 and 10.

Are you sure you have 32-bit Windows. What does "echo %PROCESSOR_ARCHITECTURE%" prints? 32-bit Windows is not common now days.

I tried installing 32-bit version of Go on 64-bit version of Windows, and that works for me.

Alex

**Comment by bradfitz** [comment]
There is only today or tomorrow to get a change submitted for Go 1.8.

This won't block the release.

**Comment by johnsonj** [comment]
No repro on a fresh 32-bit Server 2008 Datacenter VM for Go1.8rc2

**Comment by rakyll** [comment]
Closing this until reproduced. It is clear that it is not making to 1.8 if the bug is there.

**Comment by as** [comment]
I'm able to reproduce this on W10 amd64, the details are in the session below.

```

C:\Users\as>ver & set | findstr -i arch

Microsoft Windows [Version 10.0.14393]
PROCESSOR_ARCHITECTURE=AMD64

C:\Users\as> call "C:\Users\as\Downloads\go1.8rc3.windows-amd64.msi"

#
# After install, opened a new cmd window from the run bar
#

C:\Users\as>go
'go' is not recognized as an internal or external command,
operable program or batch file.

#
# Installed git before go msi (no reboot), but its in the %path%
# Go is not.

C:\Users\as>echo %path% | findstr -i git
C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Users\as\AppData\Local\Microsoft\WindowsApps;

C:\Users\as>echo %path% | findstr -i go

#
# Check weird GUI thing for updated path environment variable
# Not in path here either
C:\Users\as>sysdm.cpl

#
# Check registry
# C:\Go\bin is here, as the last element

C:\Users\as>reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" | findstr -i go
    Path    REG_SZ    C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Go\bin
    GOROOT    REG_SZ    C:\Go\
```

**Comment by johnsonj** [comment]
@as does it repro when you open a new command line? it needs to run from explorer.exe, so `Start > Run > cmd.exe > Go`

**Comment by as** [comment]
@johnsonj 

Yes, until explorer was restarted, even using "Start > Run" failed to find the go program. I've edited the previous comment with more details.

**Comment by johnsonj** [comment]
Thanks for the detailed repro! I tested mine via double click (instead of msiexec as @rakyll and @as mentioned)

Perhaps cli needs an explicit `WM_SETTINGCHANGE` as mentioned in https://github.com/nodejs/node/pull/613

As @as pointed out with the `reg` query- we're setting the right upstream value, it's just not propagating to existing processes.

**Comment by johnsonj** [comment]
@rakyll maybe re-open and tag for Go1.9?

**Comment by johnsonj** [comment]
I believe this is the issue. It's a reasonable explanation of why it doesn't repro in all environments/consistently: 

> Windows Installer itself sends the WM_SETTINGCHANGE message for settings it changes while processing an MSI package but cannot do so for changes a package makes via custom action. Also, Windows Installer does not send WM_SETTINGCHANGE for environment variable changes **when a reboot is pending**. [src](http://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html)

CL inbound

**Comment by broady** [comment]
Our version of Wix doesn't include this flag. We'll need to update it.

**Comment by johnsonj** [comment]
@broady I was worried about that! Is the install built by the build bots or somewhere else?

**Comment by broady** [comment]
Yeah, by the build bots. I just sent a change to revert it for the 1.8 release (today), but if you can see a straightforward fix, that'd be good.

**Comment by johnsonj** [comment]
Wix needs to be >= v3.10.0.1519 and looks like we're at 3.5. 

With a release today, rollback seems appropriate.

**Comment by bradfitz** [comment]
@broady, can you handle updating our Wix, or do you need help?
