### ISSUE TITLE
net/http/cookiejar: New does not need an error as return argument

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [golang/go#18685]
https://github.com/golang/go/blob/92ecd7893308ad222bfdd33b10be1cce769a3cdf/src/net/http/cookiejar/jar.go#L77

Should not return an error, since it will always yield nil it is useless.

**Comment by mdlayher** [comment]
Too late to fix now, it would break Go 1 compatibility to modify the return values of that function.

At some point, it probably did return an error, but since the signature can't be changed, the error return is always nil now.

**Comment by ALTree** [comment]
I think the API was designed that way to allow for a future different/more complex implementation. Here a golang-dev discussion: https://groups.google.com/forum/#!topic/golang-dev/ygDB3nbir00/discussion

cc @nigeltao who designed the api

**Comment by morriswinkler-simplesurance** [comment]
Ok makes sense, but from a design point, the new method is not part of the interface. More complex storage implementations could still have their own New func with custom signature.

But well too late is too late, did not think about that.
