### ISSUE TITLE
cmd/compile: remove writebarrierfat-referencing code from order.go

### ISSUE THREAD

**Issue by mdempsky** [golang/go#18687]
In [CL 21242](https://golang.org/cl/21242/) (deb83d0), I tried to remove some code that referenced the then (and now still) non-existent writebarrierfat function. However, it caused net/http's TestServerEmptyBodyRace_h2 test to mysteriously become flaky.

This seems to be fixed now, and bisecting identifies [CL 23522](https://golang.org/cl/23522) (42da35c) as the fix.

It should be safe to remove for 1.9.

**Comment by cherrymui** [comment]
Coincidentally I was doing the same thing in https://go-review.googlesource.com/c/35261/ yesterday, and it seems to work ok.

**Comment by mdempsky** [comment]
@cherrymui Yeah, that was the next step I had in mind after removing that bit of code in order.go. If you've already got it done, we can go with your CL when tree reopens.

I just wanted to file the issue since I've poked at that code a few times, but kept forgetting to write down my notes somewhere and end up reinvestigating it. :)

**Comment by mdempsky** [comment]
@cherrymui Do you plan on looking at this still?

**Comment by cherrymui** [comment]
@mdempsky Yeah, I'll rebase my CL to tip and send for review (although if we address issue #18872 then the optimization of zeroing part may be not necessary?).

**Comment by mdempsky** [comment]
@cherrymui SGTM. I'm mostly interested in getting rid of that weird bit in order.go. :)
