### ISSUE TITLE
x/exp/shiny: windriver: wrong mouse.Event coordinates for wheel events

### ISSUE THREAD

**Issue by ktye** [golang/go#18695]
### What version of Go are you using (`go version`)?
go version go1.8rc1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/local/msys64/home/elmar
set GORACE=
set GOROOT=C:\local\go
set GOTOOLDIR=C:\local\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\local\msys64\tmp\go-build565066079=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
See the discussion on golang-nuts:
https://groups.google.com/forum/#!topic/golang-nuts/F_mfbMCZyNU

### What did you expect to see?
Mouse pointer position in mouse.Events should return the position relative to the window.

### What did you see instead?
Mouse wheel events return the absolute position on the screen, not relative to the window.
The problem is only for windows and only for mouse wheel events (not normal movements).
Winapi lparam of the WM_MOUSEWHEEL message returns absolute positions.

**Comment by alexbrainman** [comment]
Sounds like a bug to me.

Would you like to send a fix by following this https://golang.org/doc/contribute.html ? Thank you

Alex

**Comment by ktye** [comment]
I'll send a patch later today.

**Comment by alexbrainman** [comment]
@bradfitz 
there is a CL to fix this issue https://go-review.googlesource.com/#/c/35412/
but I don't see issue updated to notify about the CL.
I don't see anything wrong with CL description - it say "Fixes golang/go#18695" - looks OK to me.
Am I wrong?

Alex

**Comment by bradfitz** [comment]
@alexbrainman, maybe the cron on @rsc's machine is busted. We need to move it to a Kubernetes cron instead.

**Comment by alexbrainman** [comment]
> maybe the cron on @rsc's machine is busted

Good to know.

Alex
