### ISSUE TITLE
Flattening transitive dependencies of a library results in Heisenberg vendoring uncertainty.

### ISSUE THREAD

**Issue by poncele1** [golang/go#18698]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7

### What operating system and processor architecture are you using (`go env`)?

darwin amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

In a library (called maglev-appcontainer-go below) I have vendored 3rd party dependencies. In the application consuming that library, there are also vendored 3rd party dependencies. There is now a type conflict between Package A at the path of the vendor directory of the library. 

 cisco.com/sample/service
cisco.com/sample/service/service.go:31: cannot use "vendor/github.com/emicklei/go-restful".RouteFunction(api.Ping) (type "vendor/github.com/emicklei/go-restful".RouteFunction) as type "maglev-appcontainer-go/vendor/github.com/emicklei/go-restful".RouteFunction in argument to rest.RegisterSomeAPI
cisco.com/sample/service/service.go:35: cannot use "vendor/github.com/emicklei/go-restful".RouteFunction(api.CreateUser) (type "vendor/github.com/emicklei/go-restful".RouteFunction) as type "maglev-appcontainer-go/vendor/github.com/emicklei/go-restful".RouteFunction in argument to rest.RegisterSomeAPI

### What did you expect to see?

The govendoring experiment being continued with a proposed solution for this. Instead it seems to be labeled "Mission accomplished", but it still results in unresolvable undecidability between packages. 

### What did you see instead?

A well-defined problem left hastily unsolved. The solution being semantic versioning of packages (perhaps some decoration in package declaration of the .go files belonging to a package?) and including a resolver at compilation that looks at them in go vendor as the final word in establishing the type. If you're looking at aliasing methods and types in 1.9, please consider this for 1.9 as well. A match between decorations for the package and the package name would unite the type despite different paths. People are expecting breaking changes in 2.0 right? It's not even a breaking change. You could slip it into 2.0 and get knighted.

**Comment by minux** [comment]
The general problem of vendering the same package twice and expect them to
interoperate correctly is unsolvable.

I don't think this should be solved by the tool chain. The user should make
sure a given package is only vendored once.

**Comment by bradfitz** [comment]
Much vendoring work is currently underway by a number of people. I'm going to close this bug (which is frankly a bit ranty) in favor of more specific, actionable and calm bugs.

**Comment by poncele1** [comment]
Semantic versioning of packages (perhaps some decoration in package declaration of the .go files belonging to a package?) and including a resolver at compilation that looks at them in go vendor as the final word in establishing the type solves this. A match between decorations for the package and the package name would take precedence over the path and resolve the symbol.

**Comment by kardianos** [comment]
@poncele1 What you are describing is in the works. Brad was not dismissing you. He was saying this issue wasn't itself actionable.
