### ISSUE TITLE
net/http: TestServerKeepAlivesEnabled_h2 test flake

### ISSUE THREAD

**Issue by minux** [golang/go#18701]
A recent trybot run showed this failure (CL is https://go-review.googlesource.com/c/35352/2):

https://storage.googleapis.com/go-build-log/ad057e0a/windows-386-gce_7ecf210b.log

```
--- FAIL: TestServerKeepAlivesEnabled_h2 (0.08s)
	clientserver_test.go:50: Get https://127.0.0.1:50159: read tcp 127.0.0.1:50161->127.0.0.1:50159: wsarecv: An established connection was aborted by the software in your host machine.
FAIL
FAIL	net/http	6.180s
```

/cc @bradfitz

**Comment by bradfitz** [comment]
I see nothing suspicious or racy in the test.

I'm afraid I won't be able to help on this one, just like I was unable to help last time in #14061.

/cc @alexbrainman

**Comment by alexbrainman** [comment]
I run
```
go test -v -short -run=TestServerKeepAlivesEnabled_h2 net/http
```
in a loop against https://go-review.googlesource.com/#/c/35352/2 on my both windows xp and windows 7. It didn't fail even once.

Alex

**Comment by alexbrainman** [comment]
Another failure from dashboard https://build.golang.org/log/cf6c2853214fb8d7a7667e0872d3bc3b8520b56d

Alex

**Comment by josharian** [comment]
Another from trybot: https://storage.googleapis.com/go-build-log/bebb0f25/windows-amd64-gce_fd553238.log

**Comment by bradfitz** [comment]
Another: https://storage.googleapis.com/go-build-log/f5e15285/windows-amd64-gce_a7914729.log

**Comment by mdempsky** [comment]
Another: https://storage.googleapis.com/go-build-log/20d6577d/windows-386-gce_75489d06.log

**Comment by mvdan** [comment]
Yet another: https://storage.googleapis.com/go-build-log/55ca0192/linux-amd64_45ee111b.log

**Comment by mvdan** [comment]
Err, I just noticed this was supposed to be a windows issue, and that the error is not exactly the same. Should I open a separate issue?

**Comment by tombergan** [comment]
@mvdan yep, that looks like a separate issue

**Comment by bcmills** [comment]
One more: windows, but the error message is closer to this one that #21724.
https://storage.googleapis.com/go-build-log/622d6748/windows-386-2008_eeda70f1.log

**Comment by alexbrainman** [comment]
I applied this diff:
```
diff --git a/src/net/fd_windows.go b/src/net/fd_windows.go
index c2156b2..96f68b0 100644
--- a/src/net/fd_windows.go
+++ b/src/net/fd_windows.go
@@ -125,12 +125,20 @@ func (fd *netFD) connect(ctx context.Context, la, ra syscall.Sockaddr) (syscall.
 		}
 	}
 	// Refresh socket properties.
+	fd.debug("connect", "")
 	return nil, os.NewSyscallError("setsockopt", syscall.Setsockopt(fd.pfd.Sysfd, syscall.SOL_SOCKET, syscall.SO_UPDATE_CONNECT_CONTEXT, (*byte)(unsafe.Pointer(&fd.pfd.Sysfd)), int32(unsafe.Sizeof(fd.pfd.Sysfd))))
 }
 
+func (fd *netFD) debug(cmd, msg string) {
+	println(&fd.pfd, ":", cmd, ":", fd.pfd.Sysfd, ":", msg)
+}
+
 func (fd *netFD) Close() error {
+	fd.debug("close", "about to close")
 	runtime.SetFinalizer(fd, nil)
-	return fd.pfd.Close()
+	err := fd.pfd.Close()
+	fd.debug("close", "closed")
+	return err
 }
 
 func (fd *netFD) shutdown(how int) error {
@@ -148,7 +156,13 @@ func (fd *netFD) closeWrite() error {
 }
 
 func (fd *netFD) Read(buf []byte) (int, error) {
+	fd.debug("read", "about to read")
 	n, err := fd.pfd.Read(buf)
+	if err != nil {
+		fd.debug("read", "err="+err.Error())
+	} else {
+		fd.debug("read", "read "+itoa(n))
+	}
 	runtime.KeepAlive(fd)
 	return n, wrapSyscallError("wsarecv", err)
 }
@@ -220,6 +234,7 @@ func (fd *netFD) accept() (*netFD, error) {
 	rsa, _ := rrsa.Sockaddr()
 
 	netfd.setAddr(netfd.addrFunc()(lsa), netfd.addrFunc()(rsa))
+	fd.debug("accept", "")
 	return netfd, nil
 }
```
to 538b4bab3dd9e34b3d30b6aeaef8db1d34275274 and I can see this:
```
C:\Users\Alex>u:\test -test.v -test.run=TestServerKeepAlivesEnabled_h2
=== RUN   TestServerKeepAlivesEnabled_h2
0xc042094b40 : connect : 256 :
0xc042094900 : accept : 244 :
0xc042144000 : read : 312 : about to read
0xc042094b40 : read : 256 : about to read
0xc042144000 : read : 312 : read 160
0xc042144000 : read : 312 : about to read
0xc042094b40 : read : 256 : read 799
0xc042094b40 : read : 256 : about to read
0xc042144000 : read : 312 : read 93
0xc042094b40 : read : 256 : read 51
0xc042144000 : read : 312 : about to read
0xc042094b40 : read : 256 : about to read
0xc042144000 : read : 312 : read 167
0xc042094b40 : read : 256 : read 62
0xc042144000 : read : 312 : about to read
0xc042144000 : close : 312 : about to close
0xc042144000 : close : -1 : closed
0xc042144000 : read : 312 : read 38
0xc042094b40 : read : 256 : about to read
0xc042094b40 : read : 256 : read 239
0xc042094b40 : close : 256 : about to close
0xc0421fe000 : connect : 384 :
0xc042094b40 : close : -1 : closed
0xc0421fe000 : read : 384 : about to read
0xc042094900 : accept : 244 :
0xc042200000 : read : 344 : about to read
0xc042200000 : read : 344 : read 160
0xc042200000 : read : 344 : about to read
0xc0421fe000 : read : 384 : read 799
0xc0421fe000 : read : 384 : about to read
0xc042200000 : read : 344 : read 93
0xc0421fe000 : read : 384 : read 51
0xc042200000 : read : 344 : about to read
0xc0421fe000 : read : 384 : about to read
0xc042200000 : read : 344 : read 167
0xc0421fe000 : read : 384 : read 62
0xc042200000 : close : 344 : about to close
0xc0421fe000 : read : 384 : about to read
0xc042200000 : close : -1 : closed
0xc042200000 : read : 344 : about to read
0xc042200000 : read : -1 : err=use of closed network connection
0xc0421fe000 : read : 384 : err=An existing connection was forcibly closed by the remote host.
0xc0421fe000 : close : 384 : about to close
0xc042094900 : close : 244 : about to close
0xc0421fe000 : close : -1 : closed
0xc042094900 : close : -1 : about to close
0xc042094900 : close : -1 : closed
0xc042094900 : close : 244 : closed
--- FAIL: TestServerKeepAlivesEnabled_h2 (0.34s)
        clientserver_test.go:50: Get https://127.0.0.1:53283: read tcp 127.0.0.1:53285->127.0.0.1:53283: wsarecv: An existing connection was forcibly closed by the remote host.
FAIL
```
Note how there are two similar connections here. And during first connection client receives 799, 51, 62 and 239 bytes. While during second connection it fails to receive last 239 bytes.

I suspect what is happening here, the server sends these 239 bytes and closes connection immediately. That forces connection closed before client can read the data. If server wants to make sure that client gets the data, it must use CloseWrite followed by multiple Read until connection is closed.

Alex

**Comment by tombergan** [comment]
> I suspect what is happening here, the server sends these 239 bytes and closes connection immediately.

You are right. I ran the test on a Windows box with GODEBUG=http2debug=2. After receiving a request, the server replies with a HEADERS, DATA, and GOAWAY, then closes the connection. The client's ReadFrame fails immediately, before receive any of those frames.

I understand why this flakes on Windows: The flake depends on whether or not the server reads the client's WINDOW_UPDATE frame before or after the server sends GOAWAY. If the WINDOW_UPDATE is not read when the connection is closed, then the kernel closes the connection with RST (instead of FIN) due to the non-empty receive buffer. I reduced this to the following repro:
https://play.golang.org/p/IEGfOLUQyP

I don't understand why TestServerKeepAlivesEnabled_h2 flakes on Windows but not Linux. Given that I have not seen a Linux flake, I expected the above program to fail on Windows but not Linux, but it fails deterministically on both Windows and Linux. Interestingly, the above program does not fail on play.golang.org. Perhaps docker is doing something weird.

In any case, the fix is simple. Currently, we close the connection immediately if we've responded to all streams that were open before we sent GOAWAY. Instead, we should keep the connection open for a short period of time so we can drain any packets from the kernel receive buffer. Ideally we'd delay about 1 RTT, under the assumption that the client won't send more frames after seeing GOAWAY, but getting a precise RTT measurement is annoying. I think it's sufficient to wait about 1 second (which we are [already doing](https://github.com/golang/net/blob/fe686d45ea04bc1bd4eff6a52865ce8757320325/http2/server.go#L1232) in a similar case).

**Comment by alexbrainman** [comment]
> I don't understand why TestServerKeepAlivesEnabled_h2 flakes on Windows but not Linux

I really wouldn't know. But you said "If the WINDOW_UPDATE is not read when the connection is closed, then the kernel closes the connection with RST", maybe WINDOW_UPDATE is always read before connection is closed on Linux (for one reason or another). Is it easy enough to make server close connection before reading WINDOW_UPDATE on Linux (just to see what happens)?

> Interestingly, the above program does not fail on play.golang.org. Perhaps docker is doing something weird.

I don't think play.golang.org is running docker. Is it?

> In any case, the fix is simple.

If you say so. Happy to leave it for you.

Alex
