### ISSUE TITLE
vendor: go install -pkgdir <dir> fails with vendored packages

### ISSUE THREAD

**Issue by stevenh** [golang/go#18703]
When running  ```go install``` with ```-pkgdir <directory>``` it fails if the package includes a vendored  package.
e.g. 
```
git clone git@github.com:stevenh/golang-pkgdir-test.git
cd golang-pkgdir-test/cmd/test
go install -pkgdir pkgs
```

This fails with:
```
# github.com/stevenh/golang-pkgdir-test/pkg1
../../pkg1/test.go:4: can't find import: "github.com/stevenh/golang-pkgdir-test/vendor/golang.org/x/net/context"
```

go version 1.7.3
```GOARCH="amd64"
GOBIN="/data/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/data/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build318285652=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"```

**Comment by DirtyHairy** [comment]
Is there anything planned on this issue? This keeps us from using `go install` together with `-pkgdir` to create static and cross builds without messing with the installed standard library ;) We are now using `go build` for each binary as a workaround.

**Comment by prateekgogia** [comment]
Workaround is if you pass in the absolute path to `-pkgdir` flag it works. 
I will send a PR shortly for the fix for this.

**Comment by seankhliao** [comment]
Closing as it doesn't appear relevant with modules
