### ISSUE TITLE
runtime: backport CLs 33339 and 35353

### ISSUE THREAD

**Issue by aclements** [golang/go#18700]
If we do a 1.7.5 release, backport CLs [33339](https://golang.org/cl/33339) and [35353](https://golang.org/cl/35353), which add diagnostics for and may mitigate #16083.

**Comment by bradfitz** [comment]
Austin, I'll let you send these two. These aren't trivial like the others.

**Comment by bradfitz** [comment]
Submitted to 1.7 branch.
