### ISSUE TITLE
Errors when modifying files from a plugin. Go1.8

### ISSUE THREAD

**Issue by adanto** [golang/go#18713]
When executing a plugin importing the "C" library, I'm finding some bugs that doesn't let me read and write files with some libraries. 

I'm running the application on a Debian amd64 and the go version is go1.8rc1. I've prepared an example that shows how the error appears: 

This is the main file that loads the plugin and executes the F function: 

```go
package main

import (
	"plugin"
)

func main() {

	p, err := plugin.Open("pluginReader.so")
	if err != nil {
		panic(err)
	}

	f, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}
	
	f.(func())()
}
```

And this is the plugin, that can be compiled using 
`go build -buildmode=plugin pluginReader.go`

```go
package main

import (
	"C"
	"fmt"
	"bufio"
	"os"
	"io"

)

func F() {

	fmt.Println("Openning file")
	f, err := os.Open("testFile")

	if err != nil {
		fmt.Print(err)
		return
	}

	fmt.Println("Creaating reader with bufio")
	r4 := bufio.NewReader(f)
	fmt.Printf("Created! Lets copy... %d bytes\n", r4.Buffered())


	// This works!!!
	f2, _ := os.Create("copyOfTestFileA")
	_, err = io.Copy(f2, r4)
	if err != nil {
		fmt.Println(err)
	}


	// This does not work...
	f2, _ = os.Create("copyOfTestFileB")
	w := bufio.NewWriter(f2)
	_, err = io.Copy(w, r4)
	if err != nil {
		fmt.Println(err)
	}

}
```

When the execution finished, you will see it creates a copy of the "testFile" (named "copyOfTestFileA"), that has the same content as the first one, and another ("copyOfTestFileB") that is empty. This is the problem I'm getting. What causes that second file to be empty?

**Comment by tzneal** [comment]
This is not a bug in Go, there are errors in your code:

- The file position is at the end of the file before  your second copy so there is nothing to read, use [f.Seek](https://golang.org/pkg/os/#File.Seek) to seek back to the beginning
- In the general case, the buffer may have some data buffered so call [Reset](https://golang.org/pkg/bufio/#Reader.Reset) after seeking the underlying reader.
- You're not flushing the writer (see bufio.Writer [example](https://golang.org/pkg/bufio/#Writer))


For questions about Go, see https://golang.org/wiki/Questions.

**Comment by olekukonko** [comment]
I think you sould also consider [io.MultiWriter](https://golang.org/pkg/io/#MultiWriter)
