### ISSUE TITLE
text/template, html/template: nil argument to function yields wrong number of args error

### ISSUE THREAD

**Issue by sethvargo** [golang/go#18716]
### What version of Go are you using (`go version`)?
```
go version go1.7.4 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sethvargo/Development/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/g1brm3hj0431461p8cxqtjth0000gn/T/go-build267389745=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
https://play.golang.org/p/R3CMVl_nmx

### What did you expect to see?
Passing a nested field in a struct that is nil should pass in the zero value for the accepting function. I either expected a different error, or I expected text/template to coerce the value into the signature of the receiving function (string in this case), and use the string zero value.

### What did you see instead?
An error is returned indicating an incorrect number of arguments was provided. This is especially confusing because, even if the zero value is provided, the result of the function call should be `nil`. At worst you're passing `nil` to a function that accepts a string, but that's not "incorrect number of args", it's a TypeError.

### Related Code
From my tracing, the code appears to [be here](https://github.com/golang/go/blob/6593d8650da5d19787bea9383dabe94f36fa04be/src/text/template/exec.go#L631-L633).

**Comment by sethvargo** [comment]
Even if I initialize the map and/or the map key, the error message is still the same if the provided value is nil: https://play.golang.org/p/lpFcNJYNdu

**Comment by sethvargo** [comment]
Further playing has narrowed it down to https://github.com/golang/go/blob/6593d8650da5d19787bea9383dabe94f36fa04be/src/text/template/exec.go#L622-L624. In most cases, it looks like `final` is treated as an argument (input) to the function. In the case that the value is nil, it's not "valid" and therefore does not increment the number of valid args.

**Comment by paranoiacblack** [comment]
I updated the description since this is not specific to maps, per se. Passing nil in any way to template-evaluated function causes it to exit early rather than type-checking the argument and giving the error you expect. Consider the following example: https://play.golang.org/p/PkAsQyklDW.

It seems like it might be a good idea to try to allow `nil` specifically to be used as an argument although `reflect.ValueOf(nil)` is `!reflect.Value.IsValid`.

**Comment by robpike** [comment]
This is unchanged since 1.4 and probably the beginning, so no urgency but it is annoying.

Looks like a bug to me, might be hard to fix because nil is poorly handled by reflect and the template code doesn't do much to improve the situation.

**Comment by odeke-em** [comment]
Same problem for html/template, by modifying @paranoiacblack's test program in https://github.com/golang/go/issues/18716#issuecomment-277812443 to import "html/template" instead i.e https://play.golang.org/p/Kf4gtQWnOn

**Comment by rsc** [comment]
Clearly this is the wrong error, but it should be _some_ error, so this can wait until Go 1.10.

**Comment by odeke-em** [comment]
Ooh unfortunately we didn't get a CL in for Go1.10, @sethvargo might you be interested in solving this for Go1.11? Or @rsc is this still open game for Go1.10?

**Comment by sethvargo** [comment]
Hey @odeke-em 

I tried to solve it myself, but unfortunately I got lost in the reflection bits 😦

**Comment by odeke-em** [comment]
Not a problem @sethvargo, I had asked because, since you had been investigating it, it'd be nice to carry on the ownership/credit and dibs :) We can take a look at it for Go1.11. Thank you!

**Comment by odeke-em** [comment]
@rsc am punting it to Go1.11, please feel free to rollback.
