### ISSUE TITLE
image/png: invalid format: chunk out of order

### ISSUE THREAD

**Issue by hyhlinux** [golang/go#18712]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7

### What operating system and processor architecture are you using (`go env`)?
➜  imgtask git:(dev_img) ✗ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/go-dev"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fy/whcwmcyx7tnc33h9x5y1q1pw0000gn/T/go-build407965459=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
➜  imgtask git:(dev_img) ✗ 

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

no err 
### What did you see instead?

i wait

**Comment by ALTree** [comment]
There's no code in this bug report, not even a summary description of what did you do, or a link to the .png image that gave you that error, so it's really hard to understand what's going on.

Please provide a complete, runnable Go program that exhibits the unexpected behaviour, and a link to the .png image you were trying to decode.

**Comment by bradfitz** [comment]
Also, try Go 1.8. This is likely a dup of #17511 which was fixed.

But like @ALTree says, without any detail here, there's no way to help.
