### ISSUE TITLE
encoding/json changes type of large integers when deserializing and then serializing

### ISSUE THREAD

**Issue by rtjoseph11** [golang/go#18722]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kp/n63r7pwn20s8wwlfxc_npn440000gn/T/go-build285133725=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I deserialized a json object
```json
{"Event":{"id":182295565},"Error":"some error","ClientName":"client","Critical":true}
```
that has an arbitrary object in the Event field. I then serialized the object in the event field.

https://play.golang.org/p/8P8cQ1iHxH

Fina

### What did you expect to see?
I expected the serialization to produce the same string as it received
```json
{"id":182295565}
```
I then wanted to deserialize this into another struct (OtherStruct in play.golang.org link)

### What did you see instead?
```json
{"id":1.82295565e+08}
```
and when I tried to deserialize into
```golang
type OtherStruct struct {
	ID int
}
```
I get the error
```
json: cannot unmarshal number 1.82295565e+08 into Go value of type int
```

**Comment by bradfitz** [comment]
This is "fixed" (changed in a way that happens to work for your case) in Go 1.8.

See https://beta.golang.org/doc/go1.8#encoding_json

But to be explicit about preserving integers, see https://golang.org/pkg/encoding/json/#Decoder.UseNumber

**Comment by rtjoseph11** [comment]
@bradfitz thanks!
