### ISSUE TITLE
cmd/go: TestMissingGOPATHEnvShowsDefault fails if srcDir == defaultGOPATH on windows

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#18726]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Hiroshi\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Hiroshi\AppData\Local\Temp\go-build344340558=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
```
### What did you do?
move tip source code to default GOPATH (C:\Users\Hiroshi\go)
run all.bat

### What did you expect to see?
no errors.

### What did you see instead?
```
 --- FAIL: TestMissingGOPATHEnvShowsDefault (0.62s)
             go_test.go:260: running testgo [env GOPATH]
             go_test.go:275: standard output:
             go_test.go:276:

             go_test.go:1697: got ""; want "C:\\Users\\Hiroshi\\go"
```

FWIW, I don't see this error on OS X.

**Comment by bradfitz** [comment]
I suppose we could at least fail with a better error message saying to not put your GOROOT in your GOPATH.

**Comment by hirochachacha** [comment]
Fixed by https://github.com/golang/go/commit/57d06fff3e7e020510fe9460ccfa247370c472ba.
