### ISSUE TITLE
x/playground: synchronize editor library with tour

### ISSUE THREAD

**Issue by spf13** [golang/go#18723]
for unknown reasons the playground and the go tour use completely separate editor libraries. The tour one is much more advanced leveraging http://codemirror.net. 

Ideally we would use a single script to power both and simply embed one in the other. To as much of a degree as possible sharing code between them would result in better features and less maintenance. 

Somewhat dependent on https://github.com/golang/tour/issues/146

**Comment by dlsniper** [comment]
Hi, maybe considering merging https://goplay.space/ into the official playground would be a good improvement for all gophers? Thank you.

**Comment by spf13** [comment]
I've not seen this before. It looks quite impressive.

**Comment by andybons** [comment]
CodeMirror is an enormous library and we wouldn’t use 99% of the features. I’d rather move the tour to a simpler editor implementation.

**Comment by ysmolsky** [comment]
Okay. Adding the whole library just for the sake of syntax highlighting is a no go. Closing.
