### ISSUE TITLE
cmd/cgo: #define is not exportable in some situations

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#18720]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I know 4 failing scenarios.
```go
package main

/*

#define PI 3.14

#define HELLO "hello"
#define WORLD "world"
#define HELLO_WORLD HELLO " " WORLD

#define VAR VAR1
#define VAR1 var

#define PAREN (var)
#define ADDR &var
#define ADDR_STAR *&var

int var = 5;

*/
import "C"

func testFloatConst() {
	if C.PI != 3.14 {
		panic("fail")
	}
}

func testStringConstPropagation() {
	if C.HELLO_WORLD != "hello world" {
		panic("fail")
	}
}

func testVariablePropagation() {
	if C.VAR != 5 {
		panic("fail")
	}
}

func testVariableIndirection() {
	if C.PAREN != 5 {
		panic("fail")
	}
	if *C.ADDR != 5 {
		panic("fail")
	}
	if C.ADDR_STAR != 5 {
		panic("fail")
	}
}

func main() {
	testFloatConst()
	testStringConstPropagation()
	testVariablePropagation()
	testVariableIndirection()
}
```

#### What did you expect to see?
no errors.

#### What did you see instead?
none of them can compile.

#### Does this issue reproduce with the latest release (go1.7.4)?
I think so.

#### System details

```
go version devel +d935b30 Tue Jan 17 12:56:29 2017 +0900 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hiro/.go"
GORACE=""
GOROOT="/Users/hiro/go"
GOTOOLDIR="/Users/hiro/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wq/dwn8hs0x7njbzty9f68y61700000gn/T/go-build288724185=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version devel +d935b30 Tue Jan 17 12:56:29 2017 +0900 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +d935b30 Tue Jan 17 12:56:29 2017 +0900 X:framepointer
uname -v: Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67
lldb --version: lldb-360.1.70
gdb --version: GNU gdb (GDB) 7.12
```

**Comment by minux** [comment]
We currently only support very simple macros that simply renames a value.

The reason is that to support complicated macros like *&var or even
HELLO_WORLD, cgo must implement its own C parser and translate the C
expression into equivalent Go.

Right now, only VAR and HELLO work and "#define PI 3" also works, and I
think we can make "#define PI 3.14" work too, but I don't think we can make
the others work. They might appear simple, but supporting them still
requires a full C parser.

The workaround is to assign the macro into a C variable or const and then
use them in Go.

**Comment by hirochachacha** [comment]
Thank you for quick reply!

I think we can solve testVariablePropagation also. 
for example:

x.h
```
#define VAR VAR1
#define VAR1 var
```
x.txt
```
#include "x.h"
"VAR" = VAR
```

`gcc -P -E -xc -c x.txt`

output:
```
"VAR" = var
```

So, we can get a finalized definition, instead of a shallow definition.
before https://github.com/golang/go/blob/ea7d9e6a52ca64c200dcc75621e75f209ceceace/src/cmd/cgo/gcc.go#L267

**Comment by bradfitz** [comment]
For @ianlancetaylor to decide/review.

**Comment by ALTree** [comment]
No CL for this and we're deep in the freeze, moving to go1.10.

**Comment by hirochachacha** [comment]
I didn't complete that because it conflicts with https://go-review.googlesource.com/c/44290/
Now, I did.
