### ISSUE TITLE
x/build/gerrit: document lack of stable API

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18743]
The golang.org/x/build/gerrit package is a private implementation detail of the Go build system.

I have no time nor desire to maintain a complete and stable API for Gerrit.

We need to document that people are able to use it if they like, but it may change without notice, and it's on them to vendor it.

We have such notices on other packages, but I forgot to add it to the Gerrit package. And maybe it's missing in other x/build/*** packages.

**Comment by kevinburke** [comment]
Problem with gopherbot? Here's my commit message which is (I believe) formatted correctly but no comment.

```
gerrit: support contexts

Switch all API methods that make requests to Gerrit to take a
context.Context as their first argument. Adds a package example and
a simple test that we make requests to the correct endpoint and that
the Client can handle correct responses and error responses from the
Gerrit server.

Switches all code in the x/build tree to use the new Gerrit
client. There are several projects outside the tree that import
x/build/gerrit; I'll submit CL's against those to pull in the new
interface once this gets merged.

Documents that the API is unstable.

Fixes golang/go#18742.
Fixes golang/go#18743.

Change-Id: Ifa78cbb058981e23cf5769955f6312fcbe08e174
```

https://go-review.googlesource.com/#/c/35559/
