### ISSUE TITLE
cmd/asm: s390x instruction VREPI{H,F,G} encoding is incorrect

### ISSUE THREAD

**Issue by mundaym** [golang/go#18749]
The M3 field isn't being written out (it is hardcoded to 0) so `VREPI{H,F,G}` are all encoded as `VREPIB`.

**Comment by dr2chase** [comment]
I assume this is for 1.9?  Seems very late for 1.8, though also not very risky, and the risk is almost entirely on PPC/IBM.

**Comment by mundaym** [comment]
I can work around it so 1.9 is fine I think.
