### ISSUE TITLE
cmd/pprof: remove redundant URLs in error messages

### ISSUE THREAD

**Issue by vcabbage** [golang/go#18754]
### What version of Go are you using (`go version`)?

`go version go1.8rc2 darwin/amd64`

### What did you do?

As observed in #18746:
```
# go tool pprof ./project http://localhost:5000/debug/pprof/profile
Fetching profile from http://localhost:5000/debug/pprof/profile
Please wait... (30s)
http fetch http://localhost:5000/debug/pprof/profile: Get http://localhost:5000/debug/pprof/profile: EOF
```

The URLs in the message are redundant, making the relevant portion less obvious. I propose omitting the redundant URL when the error is of type `*url.Error`.

**Comment by bradfitz** [comment]
It's always of type *url.Error if it comes from an http.Client.
