### ISSUE TITLE
runtime: tests fail in raspbian jessie on Raspberry Pi 3

### ISSUE THREAD

**Issue by indiandragon** [golang/go#18756]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go src version : 1.7.4

### What operating system and processor architecture are you using (`go env`)?

Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### What did you do?
If possible, provide a recipe for reproducing the error.
Try building Go v 1.7.4 on latest Raspbian.

### What did you expect to see?

We expect to see sucessful build of Go like mentioned in - [https://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi](https://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi)

### What did you see instead?

`pi@raspberrypi:~/go/src $ sudo env GO_TEST_TIMEOUT_SCALE=10 GOROOT_BOOTSTRAP=$HOME/go-linux-arm-bootstrap ./all.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/pi/go-linux-arm-bootstrap.
bootstrap/internal/sys
bootstrap/internal/bio
bootstrap/asm/internal/flags
bootstrap/compile/internal/big
bootstrap/internal/obj
bootstrap/internal/gcprog
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/mips
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/s390x
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/link/internal/ld
bootstrap/compile/internal/ssa
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/mips64
bootstrap/link/internal/ppc64
bootstrap/link/internal/s390x
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/gc
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/mips64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/s390x
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, linux/arm.
runtime/internal/sys
runtime/internal/atomic
runtime
unicode/utf16
unicode
unicode/utf8
math
internal/syscall/windows/sysdll
encoding
sort
sync/atomic
errors
internal/race
sync
container/heap
syscall
internal/singleflight
io
hash
hash/adler32
strings
bytes
strconv
bufio
path
internal/syscall/windows/registry
internal/syscall/windows
time
regexp/syntax
crypto
encoding/base64
reflect
crypto/sha1
regexp
os
path/filepath
os/signal
io/ioutil
fmt
encoding/binary
text/template/parse
debug/dwarf
compress/flate
context
go/token
net/url
encoding/json
log
flag
go/scanner
os/exec
go/ast
compress/zlib
text/template
debug/elf
debug/macho
go/parser
go/doc
go/build
cmd/go

##### Building packages and commands for linux/arm.
runtime/internal/sys
runtime/internal/atomic
runtime
internal/race
errors
sync/atomic
unicode
unicode/utf8
math
sort
sync
io
syscall
hash
hash/adler32
hash/crc32
container/heap
container/list
container/ring
bytes
strings
strconv
bufio
path
time
text/tabwriter
compress/bzip2
crypto/subtle
reflect
regexp/syntax
crypto
crypto/cipher
crypto/aes
math/rand
os
crypto/sha512
regexp
crypto/hmac
crypto/md5
internal/syscall/unix
crypto/rc4
crypto/sha1
path/filepath
crypto/sha256
encoding/base64
internal/nettrace
internal/singleflight
encoding
encoding/pem
encoding/ascii85
io/ioutil
encoding/base32
unicode/utf16
vendor/golang_org/x/net/lex/httplex
hash/crc64
hash/fnv
html
image/color
internal/syscall/windows/sysdll
runtime/debug
image
encoding/binary
fmt
image/color/palette
cmd/internal/sys
crypto/des
image/internal/imageutil
index/suffixarray
image/draw
image/jpeg
flag
log
debug/dwarf
compress/flate
cmd/internal/obj
debug/gosym
debug/plan9obj
compress/zlib
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/x86/x86asm
debug/elf
cmd/internal/goobj
debug/macho
debug/pe
archive/tar
archive/zip
compress/gzip
cmd/internal/objfile
compress/lzw
context
math/big
encoding/hex
go/token
cmd/addr2line
go/scanner
os/exec
go/ast
database/sql/driver
database/sql
encoding/csv
go/parser
go/printer
encoding/gob
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
crypto/rsa
cmd/cgo
crypto/ecdsa
crypto/x509/pkix
encoding/json
encoding/xml
vendor/golang_org/x/net/http2/hpack
mime
mime/quotedprintable
net/http/internal
net/url
text/template/parse
go/constant
go/format
text/scanner
image/gif
go/types
image/png
text/template
runtime/pprof
runtime/trace
go/doc
html/template
runtime/cgo
go/build
testing
internal/trace
internal/testenv
net
math/cmplx
net/internal/socktest
os/signal
os/user
runtime/race
testing/iotest
testing/quick
go/internal/gccgoimporter
go/internal/gcimporter
cmd/api
go/importer
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
crypto/x509
net/textproto
mime/multipart
crypto/tls
net/http/httptrace
log/syslog
net/mail
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/internal/bio
cmd/compile/internal/big
cmd/internal/gcprog
cmd/compile/internal/test
cmd/cover
net/http
net/smtp
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/compile/internal/ssa
cmd/dist
cmd/asm
cmd/doc
cmd/fix
expvar
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/fcgi
net/http/httputil
net/http/pprof
net/rpc
cmd/go
cmd/gofmt
net/rpc/jsonrpc
cmd/internal/pprof/profile
cmd/internal/pprof/svg
cmd/internal/pprof/tempfile
cmd/link/internal/ld
cmd/internal/pprof/plugin
cmd/internal/pprof/report
cmd/compile/internal/gc
cmd/internal/pprof/commands
cmd/internal/pprof/driver
cmd/internal/pprof/fetch
cmd/internal/pprof/symbolizer
cmd/internal/pprof/symbolz
cmd/nm
cmd/objdump
cmd/pack
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/pprof
cmd/trace
cmd/link
cmd/vet/internal/cfg
cmd/vet/internal/whitelist
cmd/vet
cmd/yacc
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile

##### Testing packages.
ok  	archive/tar	1.499s
ok  	archive/zip	1.918s
ok  	bufio	0.399s
ok  	bytes	0.713s
ok  	compress/bzip2	0.465s
ok  	compress/flate	17.219s
ok  	compress/gzip	0.124s
ok  	compress/lzw	0.096s
ok  	compress/zlib	0.343s
ok  	container/heap	0.041s
ok  	container/list	0.060s
ok  	container/ring	0.043s
ok  	context	0.968s
ok  	crypto/aes	0.347s
ok  	crypto/cipher	0.115s
ok  	crypto/des	0.202s
ok  	crypto/dsa	0.102s
ok  	crypto/ecdsa	1.208s
ok  	crypto/elliptic	0.381s
ok  	crypto/hmac	0.018s
ok  	crypto/md5	0.030s
ok  	crypto/rand	0.167s
ok  	crypto/rc4	0.845s
ok  	crypto/rsa	1.206s
ok  	crypto/sha1	0.026s
ok  	crypto/sha256	0.020s
ok  	crypto/sha512	0.055s
ok  	crypto/subtle	0.074s
ok  	crypto/tls	21.416s
ok  	crypto/x509	7.896s
ok  	database/sql	0.208s
ok  	database/sql/driver	0.014s
ok  	debug/dwarf	0.119s
ok  	debug/elf	0.139s
ok  	debug/gosym	0.115s
ok  	debug/macho	0.047s
ok  	debug/pe	0.567s
ok  	debug/plan9obj	0.017s
ok  	encoding/ascii85	0.016s
ok  	encoding/asn1	0.025s
ok  	encoding/base32	0.017s
ok  	encoding/base64	0.039s
ok  	encoding/binary	0.050s
ok  	encoding/csv	0.017s
ok  	encoding/gob	0.468s
ok  	encoding/hex	0.018s
ok  	encoding/json	2.613s
ok  	encoding/pem	0.111s
ok  	encoding/xml	0.141s
ok  	errors	0.014s
ok  	expvar	0.067s
ok  	flag	0.019s
ok  	fmt	1.102s
ok  	go/ast	0.053s
ok  	go/build	1.875s
ok  	go/constant	0.034s
ok  	go/doc	0.607s
ok  	go/format	0.107s
ok  	go/internal/gccgoimporter	0.061s
ok  	go/internal/gcimporter	7.137s
ok  	go/parser	2.369s
ok  	go/printer	5.862s
ok  	go/scanner	0.064s
ok  	go/token	0.204s
ok  	go/types	5.048s
ok  	hash/adler32	0.109s
ok  	hash/crc32	0.023s
ok  	hash/crc64	0.040s
ok  	hash/fnv	0.043s
ok  	html	0.023s
ok  	html/template	0.488s
ok  	image	1.196s
ok  	image/color	1.085s
ok  	image/draw	0.758s
ok  	image/gif	0.535s
ok  	image/jpeg	1.562s
ok  	image/png	0.474s
ok  	index/suffixarray	0.088s
ok  	internal/singleflight	0.034s
ok  	internal/trace	0.197s
ok  	io	0.048s
ok  	io/ioutil	2.775s
ok  	log	0.061s
ok  	log/syslog	2.214s
ok  	math	0.025s
ok  	math/big	5.651s
ok  	math/cmplx	0.017s
ok  	math/rand	0.816s
ok  	mime	0.069s
ok  	mime/multipart	3.468s
ok  	mime/quotedprintable	1.184s
ok  	net	2.877s
ok  	net/http	43.851s
ok  	net/http/cgi	2.415s
ok  	net/http/cookiejar	0.109s
ok  	net/http/fcgi	0.075s
ok  	net/http/httptest	0.061s
ok  	net/http/httptrace	0.020s
ok  	net/http/httputil	0.222s
ok  	net/http/internal	0.048s
ok  	net/internal/socktest	0.020s
ok  	net/mail	0.040s
ok  	net/rpc	0.119s
ok  	net/rpc/jsonrpc	0.100s
ok  	net/smtp	0.259s
ok  	net/textproto	0.052s
ok  	net/url	0.090s
ok  	os	2.775s
ok  	os/exec	1.267s
ok  	os/signal	4.342s
ok  	os/user	0.039s
ok  	path	0.038s
ok  	path/filepath	0.271s
ok  	reflect	0.745s
ok  	regexp	1.078s
ok  	regexp/syntax	4.605s
--- FAIL: TestGCFairness (3.37s)
	crash_test.go:77: starting testprog GCFairness: fork/exec /tmp/go-build175788758/testprog.exe: cannot allocate memory
--- FAIL: TestGCFairness2 (7.18s)
	crash_test.go:77: starting testprog GCFairness2: fork/exec /tmp/go-build175788758/testprog.exe: cannot allocate memory
--- FAIL: TestNumGoroutine (5.98s)
	crash_test.go:77: starting testprog NumGoroutine: fork/exec /tmp/go-build175788758/testprog.exe: cannot allocate memory
--- FAIL: TestDwarfAranges (8.04s)
	runtime-lldb_test.go:205: building source fork/exec /home/pi/go/bin/go: cannot allocate memory
--- FAIL: TestLargeStringConcat (2.42s)
	crash_test.go:77: starting testprog stringconcat: fork/exec /tmp/go-build175788758/testprog.exe: cannot allocate memory
FAIL
FAIL	runtime	423.697s
ok  	runtime/debug	0.115s
ok  	runtime/internal/atomic	0.649s
ok  	runtime/internal/sys	0.042s
ok  	runtime/pprof	6.378s
ok  	runtime/trace	20.906s
ok  	sort	0.575s
ok  	strconv	5.642s
ok  	strings	1.026s
ok  	sync	0.810s
ok  	sync/atomic	0.269s
ok  	syscall	0.624s
ok  	testing	1.867s
ok  	testing/quick	0.487s
ok  	text/scanner	0.033s
ok  	text/tabwriter	0.024s
ok  	text/template	3.684s
ok  	text/template/parse	0.096s
ok  	time	4.487s
ok  	unicode	0.024s
ok  	unicode/utf16	0.016s
ok  	unicode/utf8	0.030s
ok  	vendor/golang_org/x/net/http2/hpack	0.042s
ok  	vendor/golang_org/x/net/lex/httplex	0.015s
ok  	cmd/addr2line	6.076s
ok  	cmd/api	0.057s
ok  	cmd/asm/internal/asm	2.411s
ok  	cmd/asm/internal/lex	0.020s
ok  	cmd/compile/internal/big	350.904s
ok  	cmd/compile/internal/gc	119.390s
ok  	cmd/compile/internal/ssa	2.085s
ok  	cmd/compile/internal/test	0.030s
ok  	cmd/cover	11.208s
ok  	cmd/doc	0.178s
ok  	cmd/fix	0.082s
ok  	cmd/go	22.705s
ok  	cmd/gofmt	0.259s
ok  	cmd/internal/goobj	0.044s
ok  	cmd/internal/obj	0.025s
ok  	cmd/internal/obj/x86	0.031s
ok  	cmd/internal/pprof/profile	0.015s
ok  	cmd/link	0.013s
ok  	cmd/nm	4.258s
ok  	cmd/objdump	13.423s
ok  	cmd/pack	11.288s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.034s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	1.103s
ok  	cmd/vet	16.117s
ok  	cmd/vet/internal/cfg	0.027s
2017/01/23 07:05:49 Failed: exit status 1
`

**Comment by bradfitz** [comment]
Looks like it just doesn't have enough memory.

**Comment by mvdan** [comment]
@indiandragon have you looked at https://github.com/golang/go/wiki/GoArm? It shows some tricks to make use of less memory and add more via swap.

I also seem to remember that 1.8 should take slightly less memory when compiling, so try building rc2 if all else fails.

**Comment by davecheney** [comment]
note: Go is built and installed by the time you encounter this failure. If
your goal is to build Go from source, you can safely ignore this error, and
opt to use ./make.bash in the future to avoid running the entire test suite.

**Comment by indiandragon** [comment]
@bradfitz @mvdan I'll look into the memory as you guys suggest and revert.

@davecheney That's interesting, I installed go-lang as a dependency, I check whether my intended project runs fine and revert.

**Comment by quentinmit** [comment]
@indiandragon Did this work for you or are you still unable to use Go on your Pi 3?
