### ISSUE TITLE
cmd/vet: Docs missing headings

### ISSUE THREAD

**Issue by akshayjshah** [golang/go#18758]
### What version of Go are you using (`go version`)?
`go version go1.7.4 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ashah"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3m/040fyqk55px9hk_9hqqy0jn80000gn/T/go-build911511586=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?
I checked the documentation for `cmd/vet`, by both running `go doc cmd/vet` and visiting https://golang.org/cmd/vet/.

### What did you expect to see?
I expected to see a heading and an accompanying table of contents entry for each of the options listed in `go tool vet -h`.

### What did you see instead?
In both my local docs output and the online docs, there appear to be a number of missing headings. This makes both the table of contents and the document body rather confusing.

For example, there's no heading for the `-tests` flag; the docs are included under the section on [copying locks](https://golang.org/cmd/vet/#hdr-Struct_tags), which doesn't make much sense.

Even more confusing, the section on [struct tags](https://golang.org/cmd/vet/#hdr-Struct_tags) doesn't contain any information about struct tags at all. Instead, it contains the documentation for `-rangeloops`.

If this is indeed a bug (and not just an organizational scheme I'm not grokking), I'm happy to open a CL to fix it.

**Comment by vcabbage** [comment]
Fixed for 1.8 by https://golang.org/cl/29340/ and https://golang.org/cl/31319/. You can view the pre-release docs here: https://beta.golang.org/cmd/vet/.

I'm going to go ahead an close this, feel free to reopen if there are any additional formatting errors not addressed.
