### ISSUE TITLE
Set default value for functions or methods params

### ISSUE THREAD

**Issue by fnouama** [golang/go#18765]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
N/A: Not an issue, more a request for an additional feature

### What did you expect to see?
I was expecting the language to allow to define default value for function parameters as we can do with python and scala

### What did you see instead?
This feature is not available

**Comment by bradfitz** [comment]
Sorry, Go does not support this.

For questions about Go, see https://golang.org/wiki/Questions.

For language change proposals, see https://github.com/golang/proposal/ but be aware that Go 1 is pretty frozen at this point.

**Comment by fnouama** [comment]
thanks @bradfitz
