### ISSUE TITLE
x/build/cmd/buildstats: Cannot compile project

### ISSUE THREAD

**Issue by kevinburke** [golang/go#18764]
I'm getting the following error with the latest version of golang.org/x/build and the latest version of cloud.google.com/go/bigquery.

```
$ go build golang.org/x/build/cmd/buildstats
# golang.org/x/build/cmd/buildstats
cmd/buildstats/buildstats.go:63: undefined: "cloud.google.com/go/bigquery".ValueList
```

Searching through the bigquery codebase reveals a private `valueList` struct. It looks like it was unexported here: https://code-review.googlesource.com/#/c/9567/

**Comment by bradfitz** [comment]
@jba, what should we do?

**Comment by kevinburke** [comment]
Switching the ValueList in buildstats.go to a `[]*bigquery.Value` yields the following compile error:

```
invalid type assertion: values[0].(time.Time) (non-interface type *"cloud.google.com/go/bigquery".Value on left)
```

though a Value is:

```
type Value interface{}
```

**Comment by jba** [comment]
Should be a *[]bigquery.Value

**Comment by jba** [comment]
I mean
```
var values []bigquery.Value
err = it.Next(&values)
```

**Comment by bradfitz** [comment]
@kevinburke, can you try that?
