### ISSUE TITLE
r.MultipartReader() always returns "multipart handled by ParseMultipartForm"

### ISSUE THREAD

**Issue by omani** [golang/go#18767]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7.4

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hasan/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build624472938=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

OS: Ubuntu 14.04 LTS

### What did you do?
```go
func check(err error) {
	_, file, line, _ := runtime.Caller(1)
	if err != nil {
		log.Fatalf("Fatal from <%s:%d>\nError:%s", file, line, err)
	}
}

func (ds *StorageHandler) WriteToStorage(w http.ResponseWriter, r *http.Request) {
        logrus.Info(r.Header.Get("Content-Type"))

        reader, err := r.MultipartReader()
	check(err)
        ...
```

### What did you expect to see?
I don't know since I've never experienced a successful run.

### What did you see instead?
```
Error:http: multipart handled by ParseMultipartForm
exit status 1
```

my request was:
```bash
curl http://localhost:8080/files/58868f73b1c2f92763557e20?access_token=eyJhbGciOiJIUzI1.... -i -F file=@somefile.txt
```

It just fatals on the line where I check `reader, err := r.MultipartReader()`. But the logrus output is the following:
```
INFO[0000] multipart/form-data; boundary=------------------------4df6bdf6c6e75bf2
```

isn't this supposed to be a valid mutipart/form-data?

**Comment by bradfitz** [comment]
You don't have a complete program here demonstrating any bug.

You cite your `check` function that dies with "Fatal from ...." but I don't see "Fatal from" in your output. So what is your error from?

Sounds like a question for the mailing list, perhaps?

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by odeke-em** [comment]
@omani would you mind providing a full standalone reproducible snippet?

That error seems to me like you already invoked Request.ParseMultipartForm.
If you've already invoked it you can then use Request.MultipartForm.

**Comment by odeke-em** [comment]
Oops, @bradfitz beat me to the punch :)

**Comment by bradfitz** [comment]
The error message `multipart handled by ParseMultipartForm` suggests you already consumed the body somehow by calling `(*Request).ParseMultipartForm` 

As the docs says:

https://golang.org/pkg/net/http/#Request.MultipartReader

> Use this function instead of ParseMultipartForm to process the request body as a stream.

Note "instead of".

**Comment by omani** [comment]
yes you were right. another package was using ParseMutipartForm already. Sorry for the inconvenience.

thanks.
