### ISSUE TITLE
mime/multipart: SetBoundary validation is overly restrictive

### ISSUE THREAD

**Issue by mgoldsmi** [golang/go#18768]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mgoldsmi/golang/terraform"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build636760827=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
Setting the boundary of a mime/multipart Writer to the following value "Encrypted Boundary" failed due to the space character. A space is allowed by the MIME standard in all but the final character of the boundary (RFC 2046 https://www.ietf.org/rfc/rfc2046.txt, section 5.1.1, p22) however the standard library prohibits it anywhere in the boundary.

This particular MIME boundary setting is mandated by the Microsoft Web Services Management Protocol Extensions for Windows Vista protocol (https://msdn.microsoft.com/en-us/library/cc251526.aspx).

### Sample application demonstrating fault
~~~~
package main

import (
        "bytes"
        "log"
        "mime/multipart"
)

func main() {
        const multipartBoundary = "Encrypted Boundary"

        ntlmBody := bytes.Buffer{}
        ntlmBodyWriter := multipart.NewWriter(&ntlmBody)
        if err := ntlmBodyWriter.SetBoundary(multipartBoundary); err != nil {
                log.Printf("Failed to set boundary: %v", err)
        }
}
~~~~
### What did you expect to see?
Expected to see boundary to be set with no error.

### What did you see instead?
~~~~
$ ./multipart-boundary
2017/01/23 21:59:35 Failed to set boundary: mime: invalid boundary character
~~~~

**Comment by skinp** [comment]
I'll work on this if @mgoldsmi isn't already at it...

**Comment by bradfitz** [comment]
There is already https://golang.org/cl/35507

**Comment by skinp** [comment]
Cool, the issue didn't link I guess.

Reading the RFC while looking into this, I realized the boundary length was also wrong... "the boundary parameter, which consists of 1 to 70 characters from a set of characters"
boundary := 0*69<bchars> bcharsnospace

New issue?
