### ISSUE TITLE
fmt.Printf of 

### ISSUE THREAD

**Issue by ctwoodward** [golang/go#18777]
### What version of Go are you using (`go version`)?
go version go1.7.4 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\woodwc2\work
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
package main
import (
	"fmt"
	"os/exec"
)
func main() {
	cmd := exec.Command("netsh", "wlan", "connect name=mywifi interface=\"Wireless Network Connection\"")
	fmt.Printf("%v", cmd.SysProcAttr.CmdLine)
}
## What did you expect to see?

something along the lines of:
netsh wlan connect name=mywifi interface="Wireless Network Connection"

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4010e5]

goroutine 1 [running]:
panic(0x4b90a0, 0xc0420040c0)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.main()
        C:/Users/woodwc2/work/src/defect/main.go:10 +0xa5

**Comment by bradfitz** [comment]
This is a bug in your program, not in Go.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by minux** [comment]
cmd.SysProcAttr is set only after the cmd has Started.

**Comment by bradfitz** [comment]
@minux, cmd.SysProcAttr is never set automatically. It's an optional read-only field.
