### ISSUE TITLE
doc: source install page should mention make.bash again

### ISSUE THREAD

**Issue by ericomali** [golang/go#18771]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
None installed yet (1.4 bootstrap)

### What operating system and processor architecture are you using (`go env`)?
OSX 10.11.6

### What did you do?
Try to build 1.4 bootstrap installation

### What did you expect to see?
Successful build

### What did you see instead?
Build produces some files including a go binary but fails during tests -
# Testing packages.
ok  	cmd/addr2line	0.765s
...
ok  	unicode/utf16	0.005s
ok  	unicode/utf8	0.009s
?   	unsafe	[no test files]
% echo $?
1
% 

I tried to cobble together the resulting binary and packages into a GOROOT that could build 1.7.4 but unsurprisingly came up short. In any case the 1.4 build should work correctly.

**Comment by davecheney** [comment]
You need to use the latest source tarball t compile Go 1.4 on recent osx
releases.

Details: https://golang.org/doc/install/source#go14

**Comment by ericomali** [comment]
I downloaded go1.4-bootstrap-20161024.tar.gz and it fails in the same way.

**Comment by davecheney** [comment]
You don't need to use go 1.4 to bootstrap. Any version of go, including
1.7.4 will work.

**Comment by ericomali** [comment]
Documents clearly state 1.4 is the last version that would build with a C compiler. Are you suggesting I download binaries?

**Comment by davecheney** [comment]
Yes.

**Comment by ianlancetaylor** [comment]
Note that you did not show us what exactly fails for you.

**Comment by rsc** [comment]
You don't need to use binaries. The Go 1.4 bootstrap tgz works for many of us on OS X / macOS. I use it every day.

That said, as Ian pointed out, we need a full log of the failed build to understand what went wrong. What you've shown looks OK.

**Comment by ericomali** [comment]
The build shell script is supposed to return a 1 and not install anything?

Full log attached.
[go-build-fail.txt](https://github.com/golang/go/files/727356/go-build-fail.txt)

**Comment by bradfitz** [comment]
@ericomali, did you look at your log? Here's the error:

```
--- FAIL: TestCgoExternalThreadSIGPROF (0.65s)
	crash_cgo_test.go:74: expected "OK\n", but got "fatal error: cgo callback before cgo call\n"
FAIL
FAIL	runtime	8.053s
```

**Comment by ericomali** [comment]
Why would the failure not be made obvious at the bottom of a log?

How can this be fixed?

**Comment by ianlancetaylor** [comment]
You are only going to use Go 1.4 to build a newer release of Go.  That test failure does not matter.  We are not going to ensure that all Go 1.4 tests continue to pass when using newer compilers and newer operating system versions.  We are only going to ensure that Go 1.4 works to build newer releases of Go, and ensure that the tests of those newer releases pass.

The instructions do not recommend that you run the Go 1.4 all.bash.  I don't recommend it either.  If you choose to follow that path, I'm afraid that you are on your own.

**Comment by ericomali** [comment]
So is there any documented path to build go purely from source?

It is started to sound like I am on my own no matter what.

**Comment by ALTree** [comment]
Maybe in the doc, after mentioning `go1.4-bootstrap-20161024.tar.gz`, we should make clear that you're not supposed to run `all.bash`, just `make.bash`.

**Comment by ericomali** [comment]
Thank you; that worked great.

**Comment by bradfitz** [comment]
@ALTree, where does it suggest running `all.bash`? But sure. We can mention `make.bash` there.

**Comment by ALTree** [comment]
> where does it suggest running all.bash?

@bradfitz it doesn't, but it doesn't mention `make.bash` either, and people that read this sentence

>  To build a bootstrap tool chain from source, use either the git branch release-branch.go1.4 or go1.4-bootstrap-20161024.tar.gz

and are used to run `all.bash` to build source will do that, and then hit errors.

**Comment by ericomali** [comment]
ALTree is exactly correct; this hapless new user simply wanted to build 1.7.4, found no explicit bootstrapping directions, and applied what he had read about 1.7.4 to the bootstrap version.

**Comment by bradfitz** [comment]
Looks like this got done. https://golang.org/doc/install/source mentions make.bash four times.
