### ISSUE TITLE
fmt: float64 formatting behaving differently than expected (and than documented)

### ISSUE THREAD

**Issue by vvekic** [golang/go#18772]
### What version of Go are you using (`go version`)?
1.7.3

### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?
https://play.golang.org/p/LEVTU7r4wX

### What did you expect to see?
The %g-formatted (or %v) float64 number to be the same as either %f or %e, as per [documentation](https://golang.org/pkg/fmt/).

### What did you see instead?
The %g-formatted number was 24.849999999999998.

**Comment by ALTree** [comment]
>  The default precision for %e and %f is 6; for %g it is the smallest number of digits necessary to identify the value uniquely.

**Comment by ianlancetaylor** [comment]
Probably needs a doc tweak, as the short description of `%g` does suggest that it is either `%e` or `%f`.

CC @robpike @martisch

**Comment by rsc** [comment]
There's only so much we can say in a one-line summary. The full details of the precision _are_ documented. I tend to think this is fine as is, unless someone can come up with a very short replacement for the current one-line summary.

**Comment by griesemer** [comment]
It may suffice to replace
```
%g	%e for large exponents, %f otherwise
```
with
```
%g	%e for large exponents, %f otherwise (see below for default precision in this case)
```
