### ISSUE TITLE
add name tag optional with ignore tag json

### ISSUE THREAD

**Issue by m-abdalrahman** [golang/go#18789]
### Introduction
I use struct to decode and encode json,
and in many times I use `json:"-"` tag to ignore fields from struct when encode to json,
this means I should create new struct have same fields without ignore tag to decode json format have object ignored at main struct.

### I propose
add name tag optional with ignore tag like `omitempty` `json:"myName,omitempty"` 
to ignore this field when encode it but not when decode it.

**Comment by bradfitz** [comment]
Sorry, the JSON package is basically frozen at this point.

This is probably better discussed on the mailing list to see what others are doing: https://golang.org/wiki/Questions.
