### ISSUE TITLE
x/crypto/ssh: Add tools for parsing a user's .ssh/config file

### ISSUE THREAD

**Issue by kevinburke** [golang/go#18781]
It's nice to be able to type "ssh nickname" and have the details loaded from your `.ssh/config` file:

```
Host nickname
    HostName somerealhost.region.hostingplatform.com
    User kevin
    IdentityFile ~/.foo/bar
```

Having to parse this file manually to figure out e.g. which IdentityFile to use and which user to authenticate as is a major blocker to using the primitives in x/crypto/ssh. Maybe it could parse into a `map[string]*ssh.ClientConfig` with appropriate defaults chosen.

The closest thing I've been able to find in the wild is https://godoc.org/github.com/moul/advanced-ssh-config/pkg/config, which seems like it should do the right thing. Unfortunately I was unable to use it to successfully parse my own SSH config file; there's some problem with it attempting to use a yaml parser to parse the file, or I'm passing it the wrong thing.

Apologies if this issue has been submitted before, I searched the issues list and couldn't find anything.

**Comment by kevinburke** [comment]
(although Host fields can have wildcards e.g. `Host 10.30.*`, so maybe `map[string]*ssh.ClientConfig` is not the right data structure)

**Comment by hanwen** [comment]
I think this shouldn't be in the x/crypto/ssh package. The config file is not a standard, and does not need access to any of the internals of the package.

openssh predates YAML's popularity by a large margin. Are you sure yaml is the right technology for parsing the file?

**Comment by kevinburke** [comment]
I went ahead and wrote this: https://github.com/kevinburke/ssh_config

> The config file is not a standard

There's a manpage that describes the expected behavior in pretty explicit detail.

**Comment by hanwen** [comment]
there is no RFC, though. Let's just see how popular this package becomes, and if it becomes very popular, we can always promote it into crypto/ssh
