### ISSUE TITLE
cmd/gofmt: comment lines broken at new position

### ISSUE THREAD

**Issue by kortschak** [golang/go#18782]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8rc2

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Run `gofmt -d` on https://github.com/biogo/biogo/blob/master/align/matrix/matrices.go

### What did you expect to see?
No difference.

### What did you see instead?
Log output here https://travis-ci.org/biogo/biogo/jobs/195029064#L501

**Comment by griesemer** [comment]
This appears to be a regression from 1.7. The problem doesn't appear with https://play.golang.org/p/iptkp861qM (simple repro case) in the playground. But with 1.8 we get:
```
package p

var _ = [][]int{
	/*       a, b, c, d, e */
	/* a */
	{0, 0, 0, 0, 0},
	/* b */ {0, 5, 4, 4, 4},
	/* c */ {0, 4, 5, 4, 4},
	/* d */ {0, 4, 4, 5, 4},
	/* e */ {0, 4, 4, 4, 5},
}
```
Likely related to https://go-review.googlesource.com/#/c/33016/ (need to confirm).

**Comment by bradfitz** [comment]
@griesemer, you're confident this is sufficiently rare to push off to Go 1.9?

**Comment by griesemer** [comment]
@bradfitz I haven't seen this before and none of the code we regularly gofmt appears to have the problem. That is all I can say at the moment. I will look into the problem today - perhaps there's a safe and easy fix.

**Comment by griesemer** [comment]
Confirming that https://go-review.googlesource.com/#/c/33016/ (commit a0d2e9699f1cc83a854c52843ff15d07f83bce47) is indeed the culprit. The bug is not present before (commit 8cd55615d4d00f48c30dff85d5d5e3f2adce70ce).

**Comment by kortschak** [comment]
>@griesemer, you're confident this is sufficiently rare to push off to Go 1.9?

As a data point, this breaks my CI as I perform automated gomft checks on that repo. The failure masks other real failures.

**Comment by griesemer** [comment]
@kortschak Understood. I've started working on this.

**Comment by kortschak** [comment]
@griesemer Thank you

**Comment by griesemer** [comment]
@kortschak Not a completely satisfactory "solution", but a work-around: The following source
```
var _ = [][]int{ /* a, b, c, d, e */
	/*    a */ {0, 0, 0, 0, 0},
	/*    b */ {0, 5, 4, 4, 4},
	/*    c */ {0, 4, 5, 4, 4},
	/*    d */ {0, 4, 4, 5, 4},
	/*    e */ {0, 4, 4, 4, 5},
}
```
(first comment on same line as /*) will be preserved. Still trying to see if there's a simple (1.8-acceptable solution).

**Comment by griesemer** [comment]
@kortschak Can you verify that https://go-review.googlesource.com/35811 fixes the problem for you? Thanks.

**Comment by kortschak** [comment]
@griesemer Yes, that fixes the problem. Thanks.
