### ISSUE TITLE
path/filepath: needless dot appear in filepath.Dir(`\\server\share`)

### ISSUE THREAD

**Issue by mattn** [golang/go#18783]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +c1730ae Wed Jan 18 15:40:33 2017 +0000 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

windows amd64

### What did you do?

```go
package main

import (
	"path/filepath"
)

func main() {
	println(filepath.Dir(`\\foo\bar\`))
	println(filepath.Dir(`\\foo\bar`))
}
```

### What did you expect to see?

```
\\foo\bar\
\\foo\bar
```

### What did you see instead?

```
\\foo\bar\
\\foo\bar.
```

Needless last dot.

**Comment by bradfitz** [comment]
You didn't say whether this is a regression from Go 1.7, so I'm assuming this is for Go 1.9.

**Comment by mattn** [comment]
@bradfitz I'm sorry. I'm finding the last change of commit from blame, which commit break Dir.  However, this may be early release before go1.9. Because this bug make hang when finding parent directory like below.

```go
parent := ""
current, _ := path
for {
    parent = filepath.Dir(current)
    if parent == current {
        break
    }
   current = parent
}
```

**Comment by mattn** [comment]
It seems older than this commit. So It's not regression from Go 1.7 .

https://github.com/golang/go/commits/c007ce824d9a4fccb148f9204e04c23ed2984b71/src/os/path.go
