### ISSUE TITLE
time, cmd/compile: backport fixes to 1.7.5

### ISSUE THREAD

**Issue by josharian** [golang/go#18787]
Reminder issue so that these come up in the 1.7.5 milestone. Per golang-dev thread, consider backporting fixes for issues #17276 and #18410 for 1.7.5.

**Comment by bradfitz** [comment]
I think I did both of those already:

https://go-review.googlesource.com/q/status:merged+branch:release-branch.go1.7

**Comment by josharian** [comment]
Indeed, sorry.
