### ISSUE TITLE
1.7.4

### ISSUE THREAD

**Issue by umarbrowser** [golang/go#18797]
Please answer these questions before submitting your issue. Thanks!

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by umarbrowser** [comment]
Add == hausa langauge, if you allow i can cintribute

**Comment by mvdan** [comment]
I don't understand this issue. What is the bug or feature request?

**Comment by umarbrowser** [comment]
it a request if you allow i will contribute

**Comment by mvdan** [comment]
If you have a patch to contribute, see https://golang.org/doc/contribute.html.

Otherwise, issues are for bugs, enhancements and proposals. I see none of those here. Feel free to open one with details on exactly what your suggestion or problem is.
