### ISSUE TITLE
doc: broken wiki Images in golang/go/wiki/Mobile

### ISSUE THREAD

**Issue by cesarliws** [golang/go#18795]
I'm reading the Go Mobile docs, and some images is not found

* Deploying app bundle
https://camo.githubusercontent.com/fbc28cc15ba04a995fe26925658557d8be5565fe/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427966536a64505673394d5a626b686a6555684d597a52546545452f676f77696b692f676f6d6f62696c652d696f732d6465706c6f792e706e67

* Xcode project layout with hello.framework
https://camo.githubusercontent.com/ca8480d267fa6fba06cd69ddbd7a157083a7dab9/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427966536a64505673394d5a626b686a6555684d597a52546545452f676f77696b692f676f6d6f62696c652d696d706f72742d616e64726f696473747564696f2e706e67

* Drag and drop Hello.framework
https://camo.githubusercontent.com/4056086ee93aa86233588f92a7e180374d11807d/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427966536a64505673394d5a626b686a6555684d597a52546545452f676f77696b692f676f6d6f62696c652d62696e642d696f73647261672e706e67

* Xcode project layout with Hello.framework
https://camo.githubusercontent.com/158aaea172021b5c38d1cf2fcccfa39336384a77/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427966536a64505673394d5a626b686a6555684d597a52546545452f676f77696b692f676f6d6f62696c652d62696e642d696f732e706e67

Should this be reported here? If I know which image should be there I can send a fix, but as I am a begginer looking for how to start to work with go, I'm not familiar with this documentation yet.

**Comment by ALTree** [comment]
The wiki is editable by anyone but if you're not sure how to fix the link reporting the problem here is the right thing to do, thanks.

**Comment by gulyasm** [comment]
Images are missing (404) and I can't find the proper URLs. 

The missing images:

- https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/gowiki/gomobile-ios-deploy.png
- https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/gowiki/gomobile-import-androidstudio.png
- https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/gowiki/gomobile-bind-iosdrag.png
- https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/gowiki/gomobile-bind-ios.png

Maybe @rakyll knows where these images are (some of the commits including these screenshots came from her).

**Comment by rakyll** [comment]
Fixed them all.
