### ISSUE TITLE
x/net/http2: WriteDataPadded shouldn't accepted padding characters

### ISSUE THREAD

**Issue by daurnimator** [golang/go#18809]
Carrying over from https://github.com/summerwind/h2spec/issues/71#issuecomment-274985943

In http2, padding *MUST* be null bytes. It makes no sense for `WriteDataPadded` to take padding bytes as an argument (it should only take the number of bytes)

**Comment by bradfitz** [comment]
Note the API permits writing invalid stuff:

https://godoc.org/golang.org/x/net/http2#Framer

... has both AllowIllegalWrites and AllowIllegalReads.

This is useful for testing other implementations.

But I agree that there's something to do here. We should probably validate the pad on write unless AllowIllegalWrites is set.
