### ISSUE TITLE
cmd/go: go test -buildmode=plugin

### ISSUE THREAD

**Issue by crawshaw** [golang/go#18814]
Over on #18729 I am finding bugs by taking existing package unit tests and converting them into plugins that shell unit test can then call.

This is a bit messy to do outside of the go tool, as it requires messing with the definition of a package (including export_test.go, exporting the test functions, etc). It would be relatively straightforward to do inside the go tool, and we already have the flags we would need to trigger it. 

Then we could have a builder that runs all the tests under plugins, which would exercise the multi-module code paths in the runtime package used by -buildmode=shared and -buildmode=plugin.

**Comment by cespare** [comment]
Here's an example where I'd love to be able to just run `go test -buildmode=plugin` to run all my normal tests with dynamic linking: https://github.com/cespare/xxhash/commit/3b9a658f01dd5db41fa2272fb9a22e60ce4c1807. Instead, I settled for just running a few cursory tests through a plugin that my test compiles.
