### ISSUE TITLE
crypto/x509: path lookup order change affects CentOS from Go 1.7->8

### ISSUE THREAD

**Issue by joegrasse** [golang/go#18813]
### What version of Go are you using (`go version`)?
```go version go1.8rc3 linux/386```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr2/ps/isp/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build005892966=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
```go get -d -u <package location>```

### What did you expect to see?
Successful completion of ```go get```

### What did you see instead?
```package <package location>: unrecognized import path "<package location>" (https fetch: Get https://<package_url>?go-get=1: x509: certificate signed by unknown authority)```

Using ```go version go1.7.4 linux/386```, this worked successfully. We are using our own CA, and the package_url is our own internal server.

**Comment by joegrasse** [comment]
Doing more research looks like https://github.com/golang/go/blob/ce645534e481368b4ec6141d48eb361422e423b8/src/crypto/x509/root_linux.go#L10 was added in go1.8. On our server we have both /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem and /etc/pki/tls/certs/ca-bundle.crt. In go 1.7.4, it would find /etc/pki/tls/certs/ca-bundle.crt, which has the root certificate. In go 1.8rc3, it found /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem first, which doesn't have the root certificate.

Our server is CentOS 6.8.

**Comment by bradfitz** [comment]
If this were found during the Go 1.8 beta testing period, or even an earlier rc, it would've been easier to fix. It might be too late now. :-/

As a workaround, can you just add your certs to the first location?

Do other popular TLS clients read & merge all files?

/cc @agl

**Comment by joegrasse** [comment]
@bradfitz  By default the openssl command was working correctly. It was able to verify the certificate.

**Comment by joegrasse** [comment]
Here is a snippet from ```man verify```.

"The process of ’looking up the issuers certificate’ itself involves a number of steps. In versions of OpenSSL before 0.9.5a the first certificate whose subject name matched the issuer of the current certificate was assumed to be the issuers certificate. In OpenSSL 0.9.6 and later all certificates whose subject name matches the issuer name of the current certificate are subject to further tests."

Which to me sounds like it keeps looking.

**Comment by agl** [comment]
I think that section of the man page is suggesting that it'll check multiple certificates from a file, as opposed to merging several files. Generally OpenSSL is configured with `https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_load_verify_locations.html` which takes a single file and a single directory for hash lookups. Of course, OpenSSL is very complex and it's possible to make things happen differently and there's the possibility of distro-specific patches too.

Why do we think that the system OpenSSL isn't just looking at `/etc/pki/tls/certs/ca-bundle.crt`?

**Comment by joegrasse** [comment]
> Why do we think that the system OpenSSL isn't just looking at /etc/pki/tls/certs/ca-bundle.crt?
I not saying it doesn't, but with the change in go1.8, go isn't looking there by default.

I am still trying to research this, but it looks like in CentOS 6 (not sure what dot revision it was introduced) there is a legacy way and a new way to handle certs.

**Comment by joegrasse** [comment]
@bradfitz I am leaning toward this being a breaking change for CentOS 6, because I believe by default CentOS 6 uses the legacy method, which is /etc/pki/tls/certs/ca-bundle.crt. I am by no means an expert in this though.

**Comment by agl** [comment]
To clarify: does CentOS include both `/etc/pki/tls/certs/ca-bundle.crt` and `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` but expect that the former is the default?

**Comment by bradfitz** [comment]
If we got this bug report two months a fix would've been much easier.

Between go1.8beta1, go1.8beta2, go1.8rc1, go1.8rc2, and go1.8rc3 we make fewer and smaller and safer changes. We're basically not making changes at this point of the release cycle. We can't risk causing regressions for other crypto/x509 users. The fact that we only got one bug report about this (and so late) suggests this isn't an issue that will impact many people at least.

Unless there's a great diagnosis of what's happening and a super minimal and obviously-correct fix, you'll probably have to just modify both *.crt files, use a locally-patched Go, stay on Go 1.7, or wait for Go 1.9. Sorry.

**Comment by joegrasse** [comment]
@bradfitz I have already worked around the issue, I am more just worried about the CentOS 6 user that this might break. What population of them have test go1.8?

**Comment by joegrasse** [comment]
> To clarify: does CentOS include both ```/etc/pki/tls/certs/ca-bundle.crt``` and ```/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem``` but expect that the former is the default?

@agl I believe Yes and Yes. I don't have a "stock" CentOS 6 box though.

**Comment by agl** [comment]
It sounds like we could just flip the order of the two entries then, but I'd love to get some clarification from RedHat about their policy here. I'll see if I can reach someone who'll claim to know.

**Comment by joegrasse** [comment]
@bradfitz  @agl I am wondering for easier discovery and because this doesn't just impact ```go get``` if the title should now be 

crypto/x509: "certificate signed by unknown authority" regression from go1.7 to go1.8 on CentOS due to cert file lookup paths change.

**Comment by agl** [comment]
(I've emailed @nmav to see if we can get word about what the "correct" answer is here.)

**Comment by nmav** [comment]
In RHEL7 the files to use for openssl apps are ```/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem``` [0]. ```ca-bundle.crt``` is a link to the first one.

In RHEL6 the primary file is ```ca-bundle.crt```. (There it is optional for an administrator to enable the rhel7 trust management, by running ```update-ca-trust enable```. In that case tls-ca-bundle.pem and ```ca-bundle.crt``` should be the same file).

Based on the above I think using ca-bundle.crt seems like a safe choice.

[0]. http://www.unix.com/man-page/centos/8/update-ca-trust/

**Comment by joegrasse** [comment]
@agl As a side note, I have noticed the following.

CentOS 7
```
~$ ls -alh /etc/pki/tls/cert.pem
lrwxrwxrwx. 1 root root 49 Nov 29 02:53 /etc/pki/tls/cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

CentOS 6
```
~$ ls -alh /etc/pki/tls/cert.pem
lrwxrwxrwx. 1 root root 19 Jun  8  2016 /etc/pki/tls/cert.pem -> certs/ca-bundle.crt
```

Not sure if it would make sense to just point at ```/etc/pki/tls/cert.pem```?

**Comment by joegrasse** [comment]
@bradfitz @agl It looks like ce645534e481368b4ec6141d48eb361422e423b8 is the commit that caused this problem. It also looks like it was a fix for #15749. On CentOS 7 though, ```/etc/pki/tls/certs/ca-bundle.crt``` is linked to ```/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem```. So, I think there was a different cause for the issue in #15749.

**Comment by bradfitz** [comment]
I defer to @agl to decide what to do here.

@agl, we ship Feb 14th. It'd be nice to have this done before then. There might be an -rc4.

**Comment by rsc** [comment]
I agree that CL 36093 is too much for Go 1.8. Can we just move the new RHEL7 line down to the bottom of the preference list for Go 1.8?

ping @agl

**Comment by rsc** [comment]
Sent CL 36429 to reorder the list. I checked, and the line was added for #17549, which was "can't find any certs"; that is, on the system we were trying to fix, none of the listed files existed. On this CentOS 6 system, the existing files were better than the new file, but putting the new file earlier in the list broke things. Moving the new file to the end of the list should keep #17549 fixed and still fix this issue.

**Comment by agl** [comment]
It's still unclear why `/etc/pki/tls/certs/ca-bundle.crt` didn't exist in #15749, but Russ's change should still take care of that so LGTM.

**Comment by rsc** [comment]
https://go-review.googlesource.com/36530 for cherry-pick to Go 1.8.

**Comment by rsc** [comment]
Closing. CL 36093 mentions this issue but is really about a broader thing. This specific issue should now be fixed entirely.
