### ISSUE TITLE
x/build: run cl2issue on GKE

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18818]
As part of #18817 ("Kubernetes-ify all misc build services & bots"), this is a tracking bug to also migrate @rsc's https://godoc.org/rsc.io/github/cl2issue bot:

@rsc writes:

> The code is in rsc.io/github/cl2issue if anyone wants to make it part of the build infrastructure (please!).

/cc @kevinburke @rakyll @quentinmit

**Comment by mxplusb** [comment]
Is there a base container image to use?

**Comment by bradfitz** [comment]
The new plan is to put this functionality into golang.org/x/build/cmd/gopher

There's an outstanding CL (https://go-review.googlesource.com/c/39352/) that indexes the github references. Once that's in, this becomes a few lines in gopherbot.

**Comment by mxplusb** [comment]
Cool, should this be closed, then?

**Comment by rsc** [comment]
It should be closed once the new bot is running.

**Comment by kevinburke** [comment]
I'm happy to take this one... Currently `cl2issue` calls `exec.Command("issue", ...)` which seems a little funky since `issue` is also a Go binary. It seems like we could just make a function call from within the same process and avoid needing to install a separate binary.

**Comment by bradfitz** [comment]
Kevin, this will just be a few line gopherbot task like the others, once CL 39352 is in.
