### ISSUE TITLE
x/build: Kubernetes-ify all misc build services & bots

### ISSUE THREAD

**Issue by bradfitz** [golang/go#18817]
The Go build system & project bots are all ran in different ways & places.

This is a tracking bug to unify them to all run consistently on Kubernetes on GKE in our existing build project.

First CL was https://golang.org/cl/35810 to write a Dockerfile for the coordinator.

/cc @kevinburke @quentinmit @rakyll

**Comment by mxplusb** [comment]
What else is left to do for this?

**Comment by bradfitz** [comment]
So far gitmirror (internal) and https://pubsubhelper.golang.org/ are on GKE.
So is tip.golang.org.
TODO: beta.golang.org
TODO: finish maintner, move it to GKE
TODO: finish gopherbot, move it to GKE, subscribing to maintner
TODO: move the coordinator from CoreOS to GKE

**Comment by mxplusb** [comment]
Where is beta.golang.org?

**Comment by bradfitz** [comment]
A GCE VM running Debian. Overkill.

**Comment by mxplusb** [comment]
Gotcha, where does the code exist and is there an existing issue for it? I can work on migrating it Soon<sup>TM</sup>.

**Comment by bradfitz** [comment]
I created #19867 with the details for what beta.golang.org needs.

**Comment by jessfraz** [comment]
I can help with converting the dockerfiles away from the VM stuff! I just realized this is the goal and I loveeeeee small Dockerfiles!

**Comment by bradfitz** [comment]
With the coordinator now on GKE, I think we're all done.
