### ISSUE TITLE
spec: clarification of "value receiver" vs "pointer receiver" (missing definition)

### ISSUE THREAD

**Issue by go101** [golang/go#18828]
4 "value receiver" plus one "value-receiver".

Besides no definition for it, I feel it is better to be replaced with "non-pointer receiver", as pointers are also values.

**Comment by griesemer** [comment]
@golang101 I agree that "non-pointer receiver" is technically more correct; though it feels a bit more "clunky" than "value receiver" (even though I agree that a pointer is technically also a value). I'm going to let this simmer for a bit. I'm not quite convinced that "non-pointer" is the right choice, or if there's a better term (or we just need to define "value receiver").

**Comment by go101** [comment]
I decided to close this issue. Because when a method is declared with a non-pointer receiver, and implicit method with the corresponding pointer receiver is also declared. So a value receiver could be viewed as both pointer and non-pointer receiver.
