### ISSUE TITLE
MIP32 support request

### ISSUE THREAD

**Issue by countofsanfrancisco** [golang/go#18826]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go. 1.7.4
### What operating system and processor architecture are you using (`go env`)?
Linux, MIPS 32-bit, little endian

### What did you do?
The Golang.org website mentions only MIPS64 support. I would like to request support for MIPS32. I do not need floating point support or soft float if it makes fulfilling this request easier. 

At minimal, I would like to cross compile Go code on an x86 platform for a MIPS32 target for any endianess. 

Please let me know what other information you would like. 

I hope this is the correct forum/website for requesting new features such as this one. If not, I apologize.

### What did you expect to see?
N/A

### What did you see instead?
N/A

**Comment by ianlancetaylor** [comment]
You're in luck: 32-bit MIPS support has been added in the Go 1.8 release, which will be available soon.  You can download a release candidate today to try it out.

**Comment by mikioh** [comment]
See also #18162.
