### ISSUE TITLE
tools/cmd/stringer: Generated files have go lint warnings

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#18829]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8rc3

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

I used tools/cmd/stringer on the following piece of code, then I checked the code with golint.

```golang
const (
        NoColor Color = iota
        Black
        White
)
```

### What did you expect to see?

Golint prints no warnings

### What did you see instead?

Golint prints the following warnings

```
color_string.go:11:7: don't use underscores in Go names; const _Color_name should be _ColorName
color_string.go:13:5: don't use underscores in Go names; var _Color_index should be _ColorIndex
```

**Comment by minux** [comment]
Dup of #15346.
