### ISSUE TITLE
testing: -timeout affects benchmarks too (regression)

### ISSUE THREAD

**Issue by evverx** [golang/go#18845]
This regression was introduced in https://github.com/golang/go/commit/ead08e91f6468ab1c35c250ec487935103c580f6#diff-70e628298261565d825f7199d13042f2L758

```go
package bench

import (
        "testing"
        "time"
)

func BenchmarkSleep10(b *testing.B) {
        time.Sleep(10 * time.Second)
}
```

```sh
go test -v -bench=. -timeout=1s
```
* `go version go1.7.5 linux/amd64`
```
BenchmarkSleep10-2             1        10000282918 ns/op
PASS
```
* `go version devel +6bdb0c1 Sun Jan 29 00:49:56 2017 +0000 linux/amd64`
```
panic: test timed out after 1s
```

**Comment by ALTree** [comment]
Looks like `stopAlarm()` was removed by rsc between patch set 4 and 5, but in the CL discussion I see nothing that can explain why.

I've cooked up a quick patch and in theory just adding back a `stopAlarm()` call after `runExamples()` should fix the problem, but I'm not confident I'm not missing something.
