### ISSUE TITLE
proposal: driver/sql: context methods fallback on non-context versions

### ISSUE THREAD

**Issue by willhf** [golang/go#18849]
I propose that if `driver.ExecerContext` or `driver.QueryerContext` return `driver.ErrSkip` then the functions in ctxutil.go fall back on the non-context versions.

This makes it much easier to "wrap" drivers:  It would allow the wrapper to always implement `ExecerContext` and `QueryerContext` regardless of whether or not the underlying connection does.  Wrapping types with lots of optional interfaces is difficult since reproducing the set of methods implemented exactly requires a large number of wrappers.

For similar usefulness, I think it would be nice if the following were allowed to return `ErrSkip`:  `StmtQueryContext`, `StmtQueryContext`, and `ConnBeginTx`.  Similarly, if these returned `ErrSkip`, ctxutil.go functions could fall back on the non-context versions.

Thanks for your consideration!  Loving these new context methods!

**Comment by bradfitz** [comment]
This would've been more useful feedback a few months ago. At this point we're about to ship Go 1.8 at which point the current behavior is probably frozen.

**Comment by kardianos** [comment]
I agree with Brad that this would have been great feedback before go1.8 was cut.

As s side note, what is your use case for wrapping other drivers?

**Comment by willhf** [comment]
@kardianos  The use case for wrapping other drivers is performance instrumentation.

I share your wish that I had begun investigating this new functionality earlier!

**Comment by kardianos** [comment]
@willhf People who liked performance instrumentation also liked issue https://github.com/golang/go/issues/18080 .

I would prefer to address that issue directly rather then complicating and changing this code for go1.9.

**Comment by willhf** [comment]
@kardianos Yep, that sounds good.  I will close this issue.
