### ISSUE TITLE
cross-build error on Darwin zhangdeMac-mini.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64 

### ISSUE THREAD

**Issue by zhangweilun** [golang/go#18851]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.5

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/willian/go/proxy"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4c/xgznys191rsgcfwx16z5rp6m0000gn/T/go-build870210267=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I compile my project ,with the command
I get this github.com/djimenez/iconv-go library,and do build
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build
then
### What did you expect to see?
build success
### What did you see instead?
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ALTree** [comment]
Dup of #12888. See [Ian's comment](https://github.com/golang/go/issues/12888#issuecomment-146880368).

**Comment by minux** [comment]
To cross compile with cgo enabled, you will need a cross compiling
toolchain for linux on OS X.
