### ISSUE TITLE
proposal: flag to let "go test" terminate on first failed test

### ISSUE THREAD

**Issue by luca-moser** [golang/go#18852]
### What version of Go are you using (`go version`)?
go version go1.7.4 windows/amd64

### What did you do?
Writing tests using the `testing` package.

### What did you expect to see?
A flag to let `go test` terminate on the first failed test.

### What did you see instead?
Tests just get executed sequentially instead, it doesn't matter if previous tests passed or not.

### Why would this be useful?
Tests I write to test a REST API are heavily dependend on prior tests passing. If the previous test fails, there is no reason to run subesquent tests which depend on the previous tested (not working) functionality.

Example:
1. create a user -> 2. update the newly created user -> 3. delete the user

If the creation of the user already fails, steps 2 and 3 must not be executed. It would be easier to let `go test` terminate by flag instead of polluting the tests everywhere with if/else panics.

**Comment by cznic** [comment]
That can by done using [`testing.T.Run`](https://golang.org/pkg/testing/#T.Run).

[Usage example](https://github.com/cznic/browse/blob/9c708378b88df1b3e968477a86d8144435d5f3d3/internal/gc/all_test.go#L790).

**Comment by minux** [comment]
Different tests should be fully independent as the order each test runs is
not documented. You can implement what you want with subtest (skip
subsequent subtests when previous one failed.)

**Comment by luca-moser** [comment]
@cznic Thanks for the hint. I restructured my tests by your example.

I also replaced `httpexpect` (an external package) to use FailNow.

I don't think the need flag is needed anymore.
