### ISSUE TITLE
cmd/go: `get get -u all` fails!

### ISSUE THREAD

**Issue by LEGOlord208** [golang/go#18859]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Linux Mint (linux), AMD64

### What did you do?
I had an old version of a library. I was going to update it.
I ran `go get -u all`

### What did you expect to see?
The plugin updated.

### What did you see instead?
That changes would be overwritten, and "Please, commit your changes or stash them before you can merge" and abort. I had to reinstall".
No update was applied
To update I had to uninstall and reinstall the dependency

**Comment by ALTree** [comment]
Is this a one-time failure or can you reproduce this reliably? If it's the latter, can you provide instructions on how to reproduce the failure? 

Was the repository that triggered the failure in a strange state?

I tried to reproduce this on a very simple repository but I couldn't, even if you have uncommited changes `go get -u` does not fail like that.

**Comment by bradfitz** [comment]
Sounds like you had manually modified a package's source and git is complaining that it would lose your changes if `go get` updated that git repo.

There's not enough information here to help you, but it sounds like it did the right thing and protected you from losing your modifications.

For questions about Go, see https://golang.org/wiki/Questions.

If you have a reproducible bug report, or more details, feel free to reopen.

**Comment by LEGOlord208** [comment]
I did not modify the source, though... And there should really be some flag to overwrite any conflicts either way. While I cannot reproduce it for you, Googling the error message shows some extra git commands you should run to overwrite...

**Comment by ALTree** [comment]
> I did not modify the source

But git says the source was modified and if we can't reproduce this there's no way to debug a possible problem / tell if `go get -u` is doing something wrong. 

> And there should really be some flag to overwrite any conflicts either way

I don't think a flag is needed. Note that you don't need to delete the dependency to fix the problem: just run `git stash` as the warning suggested and the `go get` again.

**Comment by LEGOlord208** [comment]
Oh... I AM I giant idiot. I never even tried running the commands because I thought it would be more complicated than that... Never really used Git.

Thanks for everything =)

**Comment by LEGOlord208** [comment]
It happened again. I did NO changes to the thing, at least not myself. Running `git stash` gives an error, because in the directroy I am in, there is no `.git` file.

**Comment by eduncan911** [comment]
Most (if not all) dependency managers put your dependencies into a disconnected Head state (for non-git gurus, this means it changes the branch from master).  

IOW, does this look similar to your workflow?

    $ godep restore
    $ go build

This basically will break any full `go get -u all` or any mass updating technique, such as with `gostatus` and tooling.  This is especially true for older versions of Go.

Instead, you should be using the latest version of Go (1.6+) and:

    $ mkdir vendor
    $ godep save
    $ godep go build

This resolved all my issues over the last few years across various dev machines and VMs that all started around Go 1.1 or 1.2 and I keep upgrading them.  Kind of a PITA during this transition actually.

**Comment by LEGOlord208** [comment]
Mine worked after stashing them a second time. It hasn't asked me again so far.

**Comment by eduncan911** [comment]
I suspect you have a tool or your workflow has some scripting that keeps attempting to restore certain versions of those repos.  It's a lot more common than you think: I've even seen `Makefile`s have `godep restore` right smack in the middle of 3rd party packages.  *shakes head*

Anyhow.. Before running `git stash` next time:

1. tell us what repo(s) keeps showing issues.
2. change to a few of them, and run `git status` and paste an output or two from a couple. 

If number 2 shows them in an `detached head` state, then my theory is correct - you have some tooling that keeps attempting to restore them.  Dig into each step of your projects and find it.

If it indeed shows modified files, then perhaps some installer tooling is running a Makefile or some other installation tool and modifying sources.  But `git status` will tell us that as well.
