### ISSUE TITLE
syscall: use pipe2 on freebsd?

### ISSUE THREAD

**Issue by nbari** [golang/go#18854]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 freebsd/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
CC="cc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

Trying to compile from source https://github.com/ssh-vault/ssh-vault

    $ mkdir -p $HOME/go/src/github.com/ssh-vault
    $ git clone git@github.com:ssh-vault/ssh-vault.git $HOME/go/src/github.com/ssh-vault/ssh-vault
    $ cd $HOME/go/src/github.com/ssh-vault/ssh-vault
    $ go get
    

### What did you expect to see?

Get a binary.

### What did you see instead?

    $ cd .; git clone https://github.com/ssh-vault/crypto /root/go/src/github.com/ssh-vault/crypto
    package github.com/ssh-vault/crypto/aead: pipe: function not implemented

**Comment by minux** [comment]
This serms a problem of the ssh-vault/crypto package, not Go's.

Please file an issue in ssh-vault's issue tracker.

**Comment by nbari** [comment]
Seems to be happening with other packages as well, I just tried `go get gopkg.in/yaml.v2` and have same error:

    pipe: function not implemented

I have a feeling is because the images I am using don't use lib32 and syscons (`src.conf`):

    WITHOUT_LIB32: On 64-bit platforms, set to not build 32-bit library set and a
             ld-elf32.so.1 runtime linker.

     WITHOUT_SYSCONS
             Set to not build syscons(4) support files such as keyboard maps,
             fonts, and screen output maps.

Will give a try with a generic instance in the meantime.

**Comment by minux** [comment]
I see. It is using the pipe syscall that is not implemented in your kernel?

**Comment by nbari** [comment]
This is the current [kernel](https://github.com/nbari/freebsd/blob/master/kernels/tequila.kernel) and the [src.conf](https://github.com/fabrik-red/images/blob/master/src.conf) I use.

Checking the `/usr/src/UPDATE` file I found this:

    The libc stub for the pipe(2) system call has been replaced with
    a wrapper that calls the pipe2(2) system call and the pipe(2)
    system call is now only implemented by the kernels that include
    "options COMPAT_FREEBSD10" in their config file (this is the
    default).  Users should ensure that this option is enabled in
    their kernel or upgrade userspace to r302092 before upgrading their
    kernel.

I am missing `options COMPAT_FREEBSD10` will give a try and should be working, in case I continue having issues will update the post.

Thanks for the hint.

**Comment by minux** [comment]
When is the pipe syscall introduced? Perhaps we can change Go to always use
the newer syscall.

I will reopen this issue to track that.

**Comment by nbari** [comment]
Hi, I confirm that by recompiling the kernel with:

    options COMPAT_FREEBSD10

did the trick :-)

**Comment by reezer** [comment]
I don't know what Go's policy on supporting older systems is, but I want to mention that any release prior to 10.0 isn't supported anymore. In fact no release prior to 10.3 is supported anymore.

Therefor I think that pipe support can safely be dropped in favor of the pipe2 system, if Go doesn't plan to support EOLed releases of FreeBSD.

**Comment by glebius** [comment]
https://github.com/golang/go/pull/19640

**Comment by glebius** [comment]
Hi! I have created required patch.

https://github.com/golang/go/pull/19640

**Comment by glebius** [comment]
O, fsck, what a long process to contribute!

**Comment by bradfitz** [comment]
@glebius, sorry. The https://golang.org/doc/contribute.html document is too long but there's actually not many steps in it.

**Comment by glebius** [comment]
Which requires me to leak my personal information to Google or lie to them :(

**Comment by glebius** [comment]
https://go-review.googlesource.com/38422
