### ISSUE TITLE
x/mobile: gomobile bind looking for wrong file?

### ISSUE THREAD

**Issue by ekeskin** [golang/go#18876]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/ekeskin/Documents/Gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ekeskin/Documents/Gopath/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vc/p3yc91kj299bkcj0g9sr5z4h0000gn/T/go-build005903550=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
gomobile bind -target android golang.org/x/mobile/example/bind/hello/

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Succesful build of the aar.

### What did you see instead?
./bin/gomobile: loadExportData failed open /Users/ekeskin/Documents/Gopath/pkg/gomobile/pkg_android_arm/golang.org/x/mobile/example/bind/hello/.a: no such file or directory

When i examine the path "/Users/ekeskin/Documents/Gopath/pkg/gomobile/pkg_android_arm/golang.org/x/mobile/example/bind/", i realized there is a file named "hello.a" instead file named ".a" under directory "hello"

**Comment by ALTree** [comment]
Can you try with go1.8?

Possibly related: #17945

**Comment by eliasnaur** [comment]
Make sure you've run go install golang.org/x/mobile/cmd/... after go get'ing or otherwise updated gomobile. After that, make sure you've run gomobile init.

If all else fails, I'll need a (small) sample to reproduce the error.

**Comment by ekeskin** [comment]
the problem caused by '/' at the end of the

> gomobile bind -target android golang.org/x/mobile/example/bind/hello/

and it should be

> gomobile bind -target android golang.org/x/mobile/example/bind/hello
