### ISSUE TITLE
crypto/asn1: ASN.1 Marshal with application tag

### ISSUE THREAD

**Issue by kazkansouh** [golang/go#18873]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.6.2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

Not an error. I want marshal/unmarshal ASN.1 where the first byte is defined as an application tag, e.g. 0x60. However this is not possible because the encoding/asn1/Marshal function does not allow for the parameters to be configured.

I suggest adding a function "MarshalWithParameters" that allows for some of the parameters to be configured, such as setting the tag to `asn1:"application"` or adopting a solution similar to the xml encoding XMLName type that augments a given structure with meta data for the encoding.

**Comment by bradfitz** [comment]
I will let @agl decide what to do here. I think he may no longer be accepting changes to this package.

The right answer may be for somebody to start maintaining a fork of the asn1 package outside of the Go tree.

**Comment by agl** [comment]
I'm not adverse to this since I think the complexity cost would probably be quite small. (Brad is correct that, in general however, I regret the design of `encoding/asn1` and am hoping, over time, to internally move things onto a different ASN.1 parser.)

**Comment by hirochachacha** [comment]
Can I send a CL?
```go
func MarshalWithParams(val interface{}, params string) ([]byte, error)
```

**Comment by bradfitz** [comment]
@hirochachacha, feel free to send one so we know what it looks like.

**Comment by hirochachacha** [comment]
@bradfitz Thanks. I'll think about it.

**Comment by hirochachacha** [comment]
I found an another issue #20488.
