### ISSUE TITLE
cmd/go: no respect to group sticky bit

### ISSUE THREAD

**Issue by andrejsc** [golang/go#18878]
### What version of Go are you using (`go version`)?
```
go version go1.7.4 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/srv/test"
GORACE=""
GOROOT="/home/user/bin/go"
GOTOOLDIR="/home/user/bin/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build374787660=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
Notice the group sticky bit:
```bash
$ ls -la
drwxrwsr-x 7 user www-data 4096 Feb  1 10:33 .
drwxr-xr-x 5 root root     4096 Feb  1 10:55 ..
drwxrwsr-x 2 user www-data 4096 Dec  2 17:02 bin
drwxrwsr-x 8 user www-data 4096 Feb  1 10:31 .git
-rw-rw-r-- 1 user www-data  169 Dec  8 15:25 .gitignore
drwxrwsr-x 3 user www-data 4096 Jan 17 15:03 src
```
Build:
```bash
$ go build pkg_name
```

### What did you expect to see?
Produced binary respects group sticky bit, and correct group is set:
```bash
$ ls -la
drwxrwsr-x 7 user www-data     4096 Feb  1 10:33 .
drwxr-xr-x 5 root root         4096 Feb  1 10:55 ..
drwxrwsr-x 2 user www-data     4096 Dec  2 17:02 bin
drwxrwsr-x 8 user www-data     4096 Feb  1 10:31 .git
-rw-rw-r-- 1 user www-data      169 Dec  8 15:25 .gitignore
-rwxrwxr-x 1 user www-data 14693816 Feb  1 10:58 pkg_name
drwxrwsr-x 3 user www-data     4096 Jan 17 15:03 src
```

### What did you see instead?
Group sticky bit is not respected:
```bash
$ ls -la
drwxrwsr-x 7 user www-data     4096 Feb  1 10:33 .
drwxr-xr-x 5 root root         4096 Feb  1 10:55 ..
drwxrwsr-x 2 user www-data     4096 Dec  2 17:02 bin
drwxrwsr-x 8 user www-data     4096 Feb  1 10:31 .git
-rw-rw-r-- 1 user www-data      169 Dec  8 15:25 .gitignore
-rwxrwxr-x 1 user user     14693816 Feb  1 10:58 pkg_name
drwxrwsr-x 3 user www-data     4096 Jan 17 15:03 src
```

**Comment by ianlancetaylor** [comment]
This is happening because the go tool builds the binary elsewhere, in a temporary directory, and then moves it into place.

**Comment by andrejsc** [comment]
Of course, and I assume it uses `/tmp` for this purpose. But IMHO implementing this would not be a huge deal - instead of moving the file `go build` could create the file manually and just copy the content there`.

I'm haven't looked into the code, but in `bash` it is as simple as `cat /tmp/binary > binary` instead of `mv /tmp/binary .`.

**Comment by ianlancetaylor** [comment]
Yes, the code to change is `builder.moveOrCopyFile` in cmd/go/build.go.  If the destination directory has the `ModeSetgid` bit set, we should copy rather than move.
