### ISSUE TITLE
runtime/cgo: linker warning on FreeBSD 11

### ISSUE THREAD

**Issue by davecheney** [golang/go#18879]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.8rc3

### What operating system and processor architecture are you using (`go env`)?

freebsd/amd64

### What did you do?

./make.bash

### What did you expect to see?

No warnings

### What did you see instead?

# runtime/cgo
runtime/cgo/gcc_amd64.S:47:1: warning: DWARF2 only supports one section per compilation unit
.section .note.GNU-stack,"",@progbits

**Comment by ianlancetaylor** [comment]
Dup of #14705.
