### ISSUE TITLE
cmd/cgo: link error when binding C.malloc to a Go variable

### ISSUE THREAD

**Issue by bcmills** [golang/go#18889]
This program fails to build at the linking step:

src/mallocvar/mallocvar.go:
```go
package main

/*
#include <stdlib.h>
*/
import "C"
import "fmt"

var malloc = C.malloc

func main() {
        fmt.Println("%T", malloc)
}
```

```
bcmills:~$ go version
go version devel +c47df7ae17 Tue Jan 31 13:01:31 2017 -0500 linux/amd64
bcmills:~$ go build mallocvar
# mallocvar
/tmp/go-build119669921/mallocvar/_obj/_cgo_main.o:(.data.rel+0x0): undefined reference to `_CMalloc'
collect2: error: ld returned 1 exit status
```

If the program is invalid, it should be rejected earlier and produce a more helpful error message.  (For example, changing `C.malloc` to `C.monkeypants` produces the message `could not determine kind of name for C.monkeypants`, which is arguably more helpful.)

If the program is valid, it should link successfully.

(attn: @ianlancetaylor)

**Comment by ianlancetaylor** [comment]
Note that it works if you don't use the magic function `malloc`, and if you use a function that is actually defined.

**Comment by bcmills** [comment]
Hmm, interesting!  Didn't occur to me that `malloc` would be a magic function, since I included `stdlib.h` explicitly...

**Comment by amenzhinsky** [comment]
cgo converts `malloc` to the `_CMalloc`  built-in and none of [built-ins](https://github.com/golang/go/blob/release-branch.go1.8/src/cmd/cgo/out.go#L1438) can be used not in a function call now because technically they're go functions, opposed to C's `unsafe.Pointer`.

Should we support them or an error message would be enough?

**Comment by bcmills** [comment]
An error message would probably suffice.

IMO it's odd that we wrap `malloc` at all, given that it doesn't refer to any Go types.  From https://github.com/golang/go/issues/3403#issuecomment-66065481 it appears that the original reason was to work around the function having a non-standard signature on OS X, but it seems like a simpler fix would have been to hard-code the standard signature instead of shimming in a function, or only shim in the function on the platform(s) that have a nonstandard `malloc`, or name the shim with something other than the name of the standard function.  But I'm guessing it's probably too late to change any of that in Go 1.

**Comment by ianlancetaylor** [comment]
At this point, I know of two reasons for the continued special wrapping of `C.malloc`:

1. So that it works even if the magic C comment doesn't `#include <stdlib.h>`.
2. So that it never returns `nil`.
