### ISSUE TITLE
gdb: Python Exception <type 'exceptions.OverflowError'> signed integer is greater than maximum

### ISSUE THREAD

**Issue by tamird** [golang/go#18886]
See https://github.com/cockroachdb/cockroach/issues/12875#issuecomment-274557519

I haven't been able to produce a simple test case for this; it occurred using Go 1.7.4's `src/runtime/runtime-gdb.py`.

**Comment by bradfitz** [comment]
Closing until there's a concrete and self-contained bug report. Let me know if you have that simple test case.
