### ISSUE TITLE
cmd/compile: don't mark heap-shadowed variables live

### ISSUE THREAD

**Issue by randall77** [golang/go#18904]
```
func f(x *int) (t *int) {
	defer func() {}()
	t = x
	sink = &t
	return
}

var sink **int
```

Because `t` escapes, we need to allocate it on the heap.  What happens to the stack copy in `f`'s arg area?
Currently, we zero the stack copy at the start of the function, and mark that value as live throughout the function.  That's safe, but probably better to mark it dead throughout the function (except during the post deferreturn code which copies the values back to the stack?) and then not bother zeroing it.

@rsc

**Comment by cherrymui** [comment]
Seems we are not generating the zeroing now. CL https://go-review.googlesource.com/c/go/+/38133 fixes this.
