### ISSUE TITLE
x/mobile/cmd/gomobile: unable to vendor x/mobile/app package

### ISSUE THREAD

**Issue by kardianos** [golang/go#18903]
go get -u github.com/kardianos/garage/gclient
cd $GOPATH/src/github.com/kardianos/garage/gclient
gomobile build
gomobile: github.com/kardianos/garage/gclient does not import "golang.org/x/mobile/app"

When verifying that main imports `x/mobile/app`, gomobile fails to allow for the package to be within a vendor folder.

**Comment by eliasnaur** [comment]
I believe this was fixed by https://golang.org/cl/102095.
