### ISSUE TITLE
Unexpect result,while pass array params or struct type to the windows dll using (syscall  NewLazyDLL  NewProc) 

### ISSUE THREAD

**Issue by waleson** [golang/go#18913]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.7beta1 windows/386`

### What operating system and processor architecture are you using (`go env`)?

`set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dell

\AppData\Local\Temp\go-build778175466=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
`

### What did you do?

```
package main

import (
	"fmt"
	"syscall"
	"unsafe"
)

var (
	dll       = syscall.NewLazyDLL("abc.dll")

	proc_add  = dll.NewProc ("myadd")
	proc_aadd = dll.NewProc("foo")
)

func add(x, y int) int {
	r, _, _ := proc_add.Call(uintptr(x), uintptr(y))
	return int(r)
}

func foo(x *byte) uintptr {
	r, r2, e := proc_aadd.Call(uintptr(unsafe.Pointer(x)))
	fmt.Println(r, r2, e)
	return r
}

func main() {
	a := make([]byte, 3)
	a[0] = 20
	fmt.Println(add(6, 11))       // int type ,-----as expected ,out put 17
	fmt.Println(byte(foo(&a[0]))) //byte array ----------not  as expected--failed
}
```

--------------------------
this is the add.dll  src:   delphi 7.0
-------------------------------
```
library abc;


{$R *.res}

function myadd(a,b:integer):integer;stdcall;
begin
  result:=a+b;
end;

function foo(m:byte):byte;stdcall;
begin
  result:=m
end;

exports myadd,foo;

begin
end.
```

### What did you expect to see?
should like this:
//17
//**20** 303447572 The operation completed successfully.
//**20**

### What did you see instead?
but:
//------------------------result-------------------
//17
//**22** 303447572 The operation completed successfully.
//**22**
`
or other random number

**Comment by waleson** [comment]
here is the src file ,please help me ,thank  you
[testdll.zip](https://github.com/golang/go/files/749948/testdll.zip)

**Comment by minux** [comment]
it seems you're asking a question.

Please seek helps using other mediums as the issue tracker is for bug
reports and proposals.
See https://golang.org/wiki/Questions.

Does "function foo(m:byte):byte;stdcall;" really take a pointer as argument?

**Comment by waleson** [comment]
thanks for your proposal. 

this is my first time asking for help in github.com
in fact,I am using a third party dll,which  really take a pointer as argument,but i cant get the result expected.

but the document for "syscall NewLazyDLL NewProc" is very pool. 
Do you know where can i find some example? thank you .@minux

**Comment by alexbrainman** [comment]
> Does "function foo(m:byte):byte;stdcall;" really take a pointer as argument?

It does not. There are two ways to pass pointer as parameter:
```
function foo(var m:byte):byte;stdcall;
begin
  result:=m
end;
```
or literally
```
type pbyte = ^byte;

function foo(m:pbyte):byte;stdcall;
begin
  result:=m^
end;
```
Alex

**Comment by waleson** [comment]
yes,it works well,Thanks you.  Sorry to interrupt.  Alex.
