### ISSUE TITLE
git-codereview: check copyright headers on pre-commit hook

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#18917]
missing copyright header is a common mistake.
If the tool check it automatically, that would be nice.

One simple solution is extending codereview.cfg.
For example:
```
header: "^// Copyright 20\d\d The Go Authors\. All rights reserved\."
```

If the tool cannot get "header" key, no actions are performed, otherwise, it uses regex matching to target files.
Target files are got by something like `git diff --cached --name-only | grep -E "\.go$|\.s$"`

Thoughts? Thank you.

**Comment by bradfitz** [comment]
We plan to do this via #18548 instead of git-codereview.
