### ISSUE TITLE
Why Order/Priority of Map item is Different?!

### ISSUE THREAD

**Issue by questionpython** [golang/go#18916]
Hi,
Why Order/Priority of Map item is Different and is Random?!
How can it be fix?

Demo : https://play.golang.org/p/OW73ueaz_l

**Comment by myitcv** [comment]
@questionpython per [the spec](https://golang.org/ref/spec#Map_types), maps are not defined as ordered containers. Hence the results you see are not unexpected. Also [this section](https://golang.org/ref/spec#For_statements) regarding for loops:

> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next....

In short you will need to create an ordered slice of the keys and iterate that.

Please also consider asking questions like this in the go-nuts mailing list [or other help forums](https://golang.org/help/) as a first port of call. If the behaviour you are seeing is then confirmed as a bug/issue it can easily be re-raised here in the issue tracker.

**Comment by questionpython** [comment]
example this code : https://play.golang.org/p/OrDQaA_ua9
i want fix this. what do?

**Comment by minux** [comment]
Get a slice of map keys, sort the slice and then retrieve the map values
using the ordered keys.

Please ask questions on other mediums, see https://golang.org/wiki/Questions
.
