### ISSUE TITLE
FCGI docs link to  http://www.fastcgi.com which is offline

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#18928]
### What version of Go are you using (`go version`)?

Go 1.7.4 

### What did you do?
```
$ go doc fcgi
package fcgi // import "net/http/fcgi"

Package fcgi implements the FastCGI protocol. Currently only the responder
role is supported. The protocol is defined at
http://www.fastcgi.com/drupal/node/6?q=node/22
```

### What did you expect to see?
A non-dead link.

### What did you see instead?
http://www.fastcgi.com/drupal/node/6?q=node/22 is a dead link as of Feb. 3, 2017.

### Suggested resolution
[Wikipedia](https://en.wikipedia.org/wiki/FastCGI) links to a [FastCGI-Archives repo](https://github.com/FastCGI-Archives/FastCGI.com).

**Comment by ALTree** [comment]
Dup of #17815, already fixed on tip. See https://tip.golang.org/pkg/net/http/fcgi/
