### ISSUE TITLE
time: time.Parse day range inconsistency.

### ISSUE THREAD

**Issue by stakhiv** [golang/go#18921]
### What version of Go are you using (`go version`)?
`go version go1.7.5 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?
Parsing of `"February 99"` returns an error - https://play.golang.org/p/A2vCJo_oS9
But there's no error on parsing `"February 00"` - https://play.golang.org/p/AbcCMQ4xIo

https://golang.org/pkg/time/#Parse documentation seems to be outdated too.
```
No checking is done that the day of the month is within the month's valid dates; any one- or two-digit value is accepted. For example February 31 and even February 99 are valid dates, specifying dates in March and May. This behavior is consistent with time.Date.
```

### What did you expect to see?
https://play.golang.org/p/AbcCMQ4xIo should return `"day out of range"` error for `"February 00"`.

### What did you see instead?
No error and previous day instead `0000-01-31 00:00:00 +0000 UTC`

**Comment by bradfitz** [comment]
Fixed in Go 1.8: https://beta.golang.org/doc/go1.8#time
