### ISSUE TITLE
path/filepath: EvalSymlinks gives error for Windows's symbolic links with \\?\ prefix

### ISSUE THREAD

**Issue by grv87** [golang/go#18924]
For Windows's symbolic links with `\\?\` prefix `filepath.EvalSymlinks` gives error:
`GetFileAttributesEx \?: The filename, directory name, or volume label syntax is incorrect.`

Working example:
https://gist.github.com/grv87/6be3c9d7e1c795636a65283c5187d724

go version go1.7.5 windows/amd64

go env:
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Basil\gocode
set GORACE=
set GOROOT=C:\root\Go
set GOTOOLDIR=C:\root\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Basil\AppData\Local\Temp\go-build732003834=/tmp/go-build
set CXX=g++
set CGO_ENABLED=1
```

This error causes issue https://github.com/mitchellh/packer/issues/4323.

**Comment by bradfitz** [comment]
Please try Go 1.8. A lot of work happened on Windows UNC paths during the Go 1.8 dev cycle.

Go 1.7 is no longer maintained except for security fixes.

**Comment by grv87** [comment]
No error in `go1.8rc3`. Thank you!
