### ISSUE TITLE
cmd/gofmt: `gofmt -d` output confuses `diffstat`

### ISSUE THREAD

**Issue by LukeShu** [golang/go#18932]
### What version of Go are you using (`go version`)?

    go version go1.7.5 linux/386

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="386"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="386"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/usr/lib/go"
    GOTOOLDIR="/usr/lib/go/pkg/tool/linux_386"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/tmpdir/go-build106664000=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"

### What did you do?

Given a non-gofmt-formatted `.go` file (or files), I piped the output of `gofmt -d` to `diffstat`.  Rather than seeing the name of the file in the diffstat output, I see a garbage temporary filename.

For the below examples, this the input:

    $ cat hello.go
    package main
    
    import (
    "fmt"
    )
    
    func main() {
            fmt.Println("Hello, playground")
    }
    

### What did you expect to see?

    $ gofmt -d hello.go
    diff hello.go gofmt/hello.go
    --- a/hello.go        2017-02-03 19:13:00.280468375 -0500
    +++ b/hello.go        2017-02-03 19:13:00.280468375 -0500
    @@ -1,7 +1,7 @@
     package main
     
     import (
    -"fmt"
    +       "fmt"
     )
     
     func main() {
    
    $ gofmt -d hello.go | diffstat
     hello.go |    2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

### What did you see instead?

    $ gofmt -d hello.go
    diff hello.go gofmt/hello.go
    --- /run/user/1000/tmpdir/gofmt316145376        2017-02-03 19:13:00.280468375 -0500
    +++ /run/user/1000/tmpdir/gofmt617882815        2017-02-03 19:13:00.280468375 -0500
    @@ -1,7 +1,7 @@
     package main
     
     import (
    -"fmt"
    +       "fmt"
     )
     
     func main() {
    
    $ gofmt -d hello.go | diffstat
     gofmt254562456 |    2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by haya14busa** [comment]
I tried to fix this problem in https://golang.org/cl/36374 by simply replacing temporary filename with actual one.
It seems it works as expected with `diffstat` now.

```
$ gofmt -d cmd/gofmt/testdata/import.input | diffstat
 import.input |   47 +++++++++++++++++++++--------------------------
 1 file changed, 21 insertions(+), 26 deletions(-)
```

**Comment by LukeShu** [comment]
That's exactly what I expected the fix to look like!

**Comment by haya14busa** [comment]
we can also use "patch" command if it will be properly fixed.

we can use gofmt -w in most cases, but I think it's useful to keep in mind that output of `gofmt -d` can be applyed by patch command.
