### ISSUE TITLE
x/build/devapp: frequent rate limiting

### ISSUE THREAD

**Issue by kevinburke** [golang/go#18934]
When running the server outside of an App Engine context, all issues have to be fetched into RAM when the server starts, usually by hitting the `/update` endpoint. 

Frequently this yields 403 errors from Github and the following message:

```
GET https://api.github.com/repos/golang/go/issues/9669/events?page=1&per_page=100: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again. []
```

We should sleep and retry in these cases.

**Comment by quentinmit** [comment]
Or just cache the data on disk somewhere so you don't need to refetch everything.

**Comment by quentinmit** [comment]
(To clarify, their rate limit resets once/hour, so sleeping and retrying is not very effective)

**Comment by kevinburke** [comment]
@bradfitz thoughts? IIRC you were against a disk cache before; happy to add one or implement any other solution.

**Comment by bradfitz** [comment]
devapp no longer uses GitHub API calls (as of https://github.com/golang/build/commit/6990c3464a1c3e3eee126837ae82da93d56fd70e in July 2017) so we can close this.

/cc @andybons @dmitshur
