### ISSUE TITLE
proposal: in net/rpc, allow receivers to recieve the connection for the request with context

### ISSUE THREAD

**Issue by pengux** [golang/go#18937]
Currently, there is no way for receiver methods to access the RPC connection or use per-connection context.

I propose to create a new interface `RWCContext` and a struct `rpc.Conn` with methods to get/set contexts, for example:

```go
// net/rpc/server.go

type RWCContext interface {
  io.ReadCloseWriter
  Context() context.Context
  WithContext(ctx context.Context) *Conn 
}

type Conn struct {
  io.ReadWriteCloser // the underlying connection
  ctx context.Context
}
func (c *Conn) Context() context.Context
func (c *Conn) WithContext(ctx context.Context) *Conn
```

A `rpc.Conn` can be created in the `Server.ServeConn` method and get passed to the `ServerCodec` that accepts it. For example:

```go
conn = &Conn{
  ReadWriteCloser: rwc,
  ctx: context.Background(),
}
// gobServerCodec can still use the conn as it is a io.ReadWriteCloser
srv := &gobServerCodec{
  rwc:    conn,
  dec:    gob.NewDecoder(conn),
  enc:    gob.NewEncoder(buf),
  encBuf: buf,
}
// fooServerCodec accepts a *rpc.Conn
srv := &fooServerCodec{
  conn:  conn, // This field is a *rpc.Conn
}
```

The `rpc.Register` methods can then accept receivers with method signatures such as:
```go
func (t *T) MethodName(argType T1, replyType *T2) error
func (t *T) MethodName(argType T1, replyType *T2, conn rpc.RWCContext) error
```

A new interface for ServerCodec would be needed to call methods with the second signature from above:

```go
type ServerCodecConn interface {
  ServerCodec
  Conn() RWCContext
}
```

This would not break existing code and still allow the receiver methods to work with connection scoped contexts.

**Comment by rhedile** [comment]
I have also been looking at context for RPC. I use it the PKG extensively.
Your suggestion is much better than mine. I had understood that the PKG was
"frozen". There has been no guidance as to what this exactly means. I don't
know whether to to fork or go through the contribution and submit
extensions or "bug fixes". Working under compliance, I have until Oktober
to convince the "Auditors" that we we have the in house skills to fork. or
that the PKG can be maintained.  We are are more worried above the
genererated code for the Gob in the light of "flavoured" type aliasing.

**Comment by bradfitz** [comment]
Sorry, as of Go 1.8, the package docs for net/rpc say:

https://beta.golang.org/pkg/net/rpc/

> The net/rpc package is frozen and is not accepting new features.

You're welcome to fork & maintain the net/rpc page elsewhere. If it gains a large following we can link to it from the stdlib's net/rpc package docs perhaps.

See also https://golang.org/doc/faq#x_in_std for some background.

**Comment by keegancsmith** [comment]
FYI I recently was wanting net/rpc with context. Its different to what you are asking for, since the context I added is per RPC call. The fork is at https://github.com/keegancsmith/rpc
