### ISSUE TITLE
playground: timezone problem

### ISSUE THREAD

**Issue by MaVo159** [golang/go#18948]
It seems that the playground doesn't deal with timezones correctly (or at all? I don't know...)

https://play.golang.org/p/RlJJTecSo7
 
Some of the code:
```
t1, e1 := time.Parse(format, "Nov 15 10:00 CET 2016")
t2, e2 := time.Parse(format, "Oct 15 10:00 CEST 2016")
fmt.Println(e1, e2)
fmt.Println("t1:", t1.Unix())
fmt.Println(t1.UTC())
fmt.Println("t2:", t2.Unix())
fmt.Println(t2.UTC())
```
Playground output:
```
<nil> <nil>
t1: 1479204000
2016-11-15 10:00:00 +0000 UTC
t2: 1476525600
2016-10-15 10:00:00 +0000 UTC
```
All lines in the playground output have fairly obviously wrong values. Furthermore there should be a one hour difference in UTC between the two (summer time and winter time).

I believe the correct output is what go does on my machine (go version go1.7.4 linux/amd64):
```
t1: 1479200400
2016-11-15 09:00:00 +0000 UTC
t2: 1476518400
2016-10-15 08:00:00 +0000 UTC
```

**Comment by bradfitz** [comment]
Your local machine is presumably in Europe.

https://play.golang.org/p/2YJOUc6xz7

https://golang.org/pkg/time/#ParseInLocation says: 

> Second, when given a zone offset or abbreviation, Parse tries to match it against the Local location; ParseInLocation uses the given location.

I think it's working as documented.

**Comment by MaVo159** [comment]
Maybe I'm just dense... ...whether explicitly stated zone abbreviations are actually applied depends on the location setting of my machine? Is that a bug we carry around for backwards compatibility or is this actually intentional?

**Comment by bradfitz** [comment]
> whether explicitly stated zone abbreviations 

For one, zone abbreviations are very often not "explicit":

Is WST the Western Sahara, or Western Australia, or Western Samoa?

Is PST the west coast of the US, or North Korea?

etc.
