### ISSUE TITLE
gccgo: Trouble cross-compiling to GOARCH=mips using gccgo

### ISSUE THREAD

**Issue by elimisteve** [golang/go#18942]
### What version of Go are you using (`go version`)?

go version go1.8rc3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

I tried cross-compiling a trivial "hello world" Go program -- namely https://github.com/elimisteve/hello/blob/master/hello.go -- with this command:

> $ GOOS=linux GOARCH=mips go1.8rc3 build -x -compiler=gccgo .

### What did you expect to see?

No output and a successfully-compiled 32-bit MIPS binary in my local directory.

### What did you see instead?

```
$ GOOS=linux GOARCH=mips go1.8rc3 build -x -compiler=gccgo .
WORK=/tmp/go-build262885004
mkdir -p $WORK/github.com/elimisteve/hello/_obj/
mkdir -p $WORK/github.com/elimisteve/hello/_obj/exe/
cd /home/ubuntu/go/src/github.com/elimisteve/hello
/usr/bin/gccgo -I $WORK -c -g -mabi=32 -march=mips32 -fgo-relative-import-path=_/home/ubuntu/go/src/github.com/elimisteve/hello -o $WORK/github.com/elimisteve/hello/_obj/_go_.o ./hello.go
# github.com/elimisteve/hello
gccgo: error: unrecognized argument in option ‘-mabi=32’
gccgo: note: valid arguments to ‘-mabi=’ are: ms sysv
```

This is using `gccgo` 6, which installed 'libgo9` as a dependency when I ran `apt-get install gccgo`.

At <https://tip.golang.org/doc/install/gccgo> it says,

> The GCC 6 releases include a complete implementation of the Go 1.6.1 user libraries. **The Go 1.6 runtime is not fully merged, but that should not be visible to Go programs.**

so I believe this is supposed to work? Thanks!

**Comment by cherrymui** [comment]
It looks like your gccgo isn't the cross compiler, i.e. it's targeting the host (amd64) instead of mips. I don't know how to cross compile with gccgo though. You probably needs to set up some environment variable.

**Comment by cherrymui** [comment]
Maybe `apt-get install gccg-mips-linux-gnu`?

**Comment by minux** [comment]
and you should use the go tool bundled with gccgo, not go tool bundled with
gc due to various version skew problems.

**Comment by elimisteve** [comment]
@minux Well the key line seems to be

> /usr/bin/gccgo -I $WORK -c -g -mabi=32 -march=mips32 -fgo-relative-import-path=_/home/ubuntu/go/src/github.com/elimisteve/hello -o $WORK/github.com/elimisteve/hello/_obj/_go_.o ./hello.go

which is using gccgo directly. Not sure if I should try xgo or whether building my own cross-compiling version of GCC, a la <https://github.com/golang/go/wiki/GccgoCrossCompilation#build-the-cross-compiler>, is necessary.

**Comment by minux** [comment]
I'm pretty sure /usr/bin/gccgo is not a mips cross gccgo.

As cherrymui mentioned, you need to install a cross gccgo, and then use the
go command bundled with cross gccgo.

**Comment by ianlancetaylor** [comment]
Setting `GOOS` and `GOARCH` when running the go tool works to do cross-compiling with the gc toolchain, but it does not work when using the gccgo toolchain.  It would be nice to make this work better, but it will never be as simple as it is with the gc toolchain.

**Comment by lucaswiechmann** [comment]
Anyone had to use eglibc instead of ulibc for successfully run go on mips?

**Comment by jsw-davidhuang** [comment]
1. sudo apt-get install gccgo-mipsel-linux-gnu
2. mipsel-linux-gnu-gccgo -o main main.go

**Comment by cherrymui** [comment]
@adonespitogo you're expected to use the `go` command that comes with `gccgo`, instead of the `gccgo` command directly. For cross-compilation, you might be able to do something like `GOOS=linux GOARCH=mips GCCGO=mipsel-linux-gnu-gccgo CC=<your-C-cross-compiler> go build -compiler=gccgo`

**Comment by adonespitogo** [comment]
Thanks for the advice @cherrymui . I tried `CGO_ENABLED=0 GOOS=linux GOARCH=mips GCCGO=mipsel-linux-gnu-gccgo go build -tags="mono dev" -compiler=gccgo` but now I have a different error:

```
package io/fs is not in GOROOT (/home/adonesp/.gvm/gos/go1.19.4/src/io/fs)
```

**Comment by ianlancetaylor** [comment]
Make sure that you are using the `go` command that comes with `gccgo`, not the one that comes with the usual gc distribution.

Make sure that `GOROOT` is not set in the environment.

**Comment by adonespitogo** [comment]
My `gccgo` installation from ubuntu apt repository does not seem to have go command installed with it. I'm now compiling gcc go from the source. Will report back with the result.

**Comment by adonespitogo** [comment]
I've built `gccgo` from scratch following https://go.dev/doc/install/gccgo and now I have the `go` command from gccgo. Now I encounter another problem:

```
export GOOS=linux                                                                                                                                                                                
export GOARCH=mips                                                                                                                                                                               
export GCCGO=mipsel-linux-gnu-gccgo                                                                                                                                                              
export prefix=/opt/gccgo                                                                                                                                                                         
export gccgo_version=13.0.0

/opt/gccgo/bin/go build -tags="mono dev" -compiler=/opt/gccgo/bin/gccgo -gccgoflags -Wl,-R,/opt/gccgo/lib64/ -static-libgo -o myapp.app main.go
/opt/gccgo/bin/go: error while loading shared libraries: libgo.so.21: cannot open shared object file: No such file or directory
```

```
❯ ls /opt/gccgo/lib64 | grep libgo.so
libgo.so
libgo.so.21
libgo.so.21.0.0
```

**Comment by adonespitogo** [comment]
It's working now, I guess. Here's my new env and build params:

```
export GOOS=linux
export GOARCH=mips
export GCCGO=/usr/bin/mips-linux-gnu-gccgo
export LD_LIBRARY_PATH=/opt/gccgo/lib64

/opt/gccgo/bin/go build -tags="mono dev" -compiler=gccgo -gccgoflags -Wl,-R,/opt/gccgo/lib64
```
Though I can't confirm it yet since I still have to update my go codes to use golang `go1.18` instead of `go1.19`.

**Comment by ianlancetaylor** [comment]
Thanks, closing for now.
