### ISSUE TITLE
cmd/compile: non-constant rotations are not emitted

### ISSUE THREAD

**Issue by rasky** [golang/go#18940]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version devel +34b455da44 Sat Feb 4 07:24:20 2017 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rasky/Sources/go"
GORACE=""
GOROOT="/Users/rasky/Sources/gosrc"
GOTOOLDIR="/Users/rasky/Sources/gosrc/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lw/jdbk7p_d4gj6qpydczpbw2080000gn/T/go-build646363960=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
```go
func testRotate_easy(op uint32, cnt uint) uint32 {
	cnt = cnt & 31
	return (op << cnt) | (op << (32 - cnt))
}

func testRotate_complex(op uint32) uint32 {
	rot := uint((op >> 7) & 0x1E)
	return ((op & 0xFF) >> rot) | ((op & 0xFF) << (32 - rot))
}
```

### What did you expect to see?
Rotate opcode emitted

### What did you see instead?
Rotate opcode not emitted

**Comment by randall77** [comment]
See also #18616 (add`bits.RotateLeft`).

**Comment by randall77** [comment]
I'm going to close this as done. The easy case is handled now as is, or using bits.RotateLeft.
The hard case seems less pressing, and you can get the rotate behavior by either adding an additional `&0x1f` or using bits.Rotateleft.
