### ISSUE TITLE
runtime: clearMarkedNonAtomic different than clearMarked

### ISSUE THREAD

**Issue by zhaozhiqianghw** [golang/go#18941]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
linux amd64

The function clearMarked and clearMarkedNonAtomic are defined:
func (m markBits) clearMarked() {
      atomic.And8(m.bytep, ^m.mask)
}

func (m markBits) clearMarkedNonAtomic() {
     *m.bytep ^= m.mask
}

From the definition, these two functions have different meaning, 
 *m.bytep ^= m.mask
should changed to
*m.bytep &^= m.mask

Although, clearMarkedNonAtomic never be used.

**Comment by ianlancetaylor** [comment]
Let's just remove `markBits.clearMarkedNonAtomic`, since, as you say, it has never been used.
