### ISSUE TITLE
sync/atomic: improve package docs

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#18955]
At the end of the API docs of sync/atomic, https://golang.org/pkg/sync/atomic/, it says:

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned. 

It could be improved as 

> The first word in a variable or in an allocated struct, array or slice can be relied upon to be 64-bit aligned.

The reason is there are many local variables and arrays which addresses are passed as the parameters atomic 64bit functions, in go project source.

And "the first word in an allocated slice" is not an accurate description, it should be the first element  in an allocated slice which elements are 64-bit words.

And the expvar package docs should warning that expvar.Int and expvar.Float are not safe to be embedded in other types on 32bit OSes.

Please see this thread for detail: https://groups.google.com/forum/#!topic/golang-nuts/_nHK6P8_lhw

**Comment by bradfitz** [comment]
@aclements, do you want to improve these docs for Go 1.9?

**Comment by aclements** [comment]
> The first word in a variable or in an allocated struct, array or slice can be relied upon to be 64-bit aligned.

I think this is fair.

> And "the first word in an allocated slice" is not an accurate description, it should be the first element in an allocated slice which elements are 64-bit words.

Can you expand on why you think this isn't an accurate description? It seems accurate to me.

(Really, this whole statement is somewhat inaccurate, as it's only true if the allocation itself is at least 8 bytes. But if that's not the case, then there's no way to use the 64-bit atomic ops anyway.)

**Comment by go101** [comment]
A slice is composed a header and an underlying array.
When we say "an allocated slice", we generally mean the header of the slice is allocated.
But we would never do 64-bit atomic operations on slice headers.
And for an allocated slice, its underlying array may be not allocated.
For example, its underlying array may be a field of a struct value.

> And "the first word in an allocated slice" is not an accurate description, it should be the first element in an allocated slice which elements are 64-bit words.

The above texts may be also not good. I prefer to use the following one:
> The first word in a variable or in an allocated struct and array can be relied upon to be 64-bit aligned. The elements of a slice are stored in an underlying array of the slice.
