### ISSUE TITLE
a latched channel experiment

### ISSUE THREAD

**Issue by glycerine** [golang/go#18951]
I would like to experiment with a variation on a buffered channel that I call a latched channel. 

The idea is to offer broadcast semantics, where a receive on a latched channel would not consume from the backing queue.

I wrote a proposal here, and I invite comments on the design and guidance (which files have the relevant code?) for how to prototype it in the Go runtime.

https://github.com/glycerine/latch

If the experiment proves successful in terms of usability and usefulness, then I would think of promoting the experiment to a Go proposal.

**Comment by ianlancetaylor** [comment]
If you want discussion it's probably best to raise this on the golang-dev mailing list.

The relevant code in the Go runtime is in chan.go and select.go.

**Comment by bradfitz** [comment]
Yeah, I'm going to close this. (We only use the issue tracker for tracking work items we can close, not for questions.)

But do bring it up on the mailing list. Thanks.

**Comment by glycerine** [comment]
> Yeah, I'm going to close this. (We only use the issue tracker for tracking work items we can close, not for questions.)

Fine with me. It's kind of a pre-proposal, but reason for the ticket was that the procedure for proposals specifically requests a github issue.

**Comment by bradfitz** [comment]
Oh, sorry, I thought it was a package you wanted to write, and not a language change proposal.

I'll note that language change proposals are notoriously unlikely to get approved at this stage of Go 1.x. Your best bet is to experiment on the side and wait for any Go 2 discussions to happen later.

**Comment by minux** [comment]
Before this reaches proposal stage, could you please show the rationale for
this feature and why it can't be solved by existing features?

**Comment by glycerine** [comment]
Hi Minux (@minux), I did write that up pretty thoroughly, and demonstrated it with the best work-around code I could come up with. Did you read the analysis? Since this ticket is closed, perhaps this is not the place for discussion now. Feel free to open a ticket on https://github.com/glycerine/latch to discuss.
