### ISSUE TITLE
net/http: Unclear if modifying http.Request.URL in ServeHTTP is legal.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#18952]
As of https://golang.org/cl/21530 (/cc @bradfitz), which resolved #14940, `http.Handler` doc says about `ServeHTTP(http.ResponseWriter, *http.Request)`:

```
// Except for reading the body, handlers should not modify the
// provided Request.
```

Yet here's what `http.StripPrefix` does:

```Go
return HandlerFunc(func(w ResponseWriter, r *Request) {
...
	r.URL.Path = p
```

Is modifying `http.Request.URL` not considered as modifying `http.Request` itself? If so, I believe the documentation needs to be more clear about that.

Or is there a bug in `http.StripPrefix`?

**Comment by bradfitz** [comment]
Yeah, I suppose StripPrefix should follow the rules (which were written after StripPrefix was).

Anybody want to send a CL?

**Comment by shurcooL** [comment]
So you're confirming that modifying req.URL is considered against the contract. I wonder if gorilla/mux and other libraries currently do that or not. If they do, they'll need to be updated.

I can send a CL if you want to help me understand the way you expect this resolved.

Would we need to make a shallow copy of `*http.Request`, and a copy of `*url.URL`, then modify the copied request's URL? Is there already a private helper for making a request copy I should use?

**Comment by quentinmit** [comment]
I'm reopening this because apparently there is code out there that will break as a result of creating a new `*http.Request` instead of editing the existing one. (Code that builds a `map[*http.Request]extraData`.)

Not that we necessarily need to revert, but someone needs to think about which state is worse.

**Comment by rsc** [comment]
ping @bradfitz

**Comment by bradfitz** [comment]
There used to be somewhat valid reasons to have `map[*http.Request]extraData` but with per-Request contexts and net/http/httptrace, there are better ways.

Let's see how it goes with the beta and see if people are actually affected.

But @quentinmit, if you know of concrete examples of such code, let me know and we can reconsider. But if this is just hypothetical, I'm inclined to wait and see. We already have code which modifies the passed-through *Request. This is just one more.
