### ISSUE TITLE
cmd/compile: speed up TestAssembly

### ISSUE THREAD

**Issue by josharian** [golang/go#18966]
TestAssembly is very slow, leading to it being skipped by default. This is not surprising--it separately invokes the compiler and parses the result many times. However, with some care, it should be possible to take all the test functions (all named `func f`), rename them, assemble a single file to compile out of it, and parse the results, correlating them back to the original. This should speed it up considerably.

No special knowledge of the compiler required, but will require some careful attention and thought. Might be good first hacking project for a patient person with Go experience who wants to see the awful guts of the toolchain in action. :)

**Comment by TocarIP** [comment]
Great idea! This will allow to avoid stuff like https://github.com/golang/go/commit/6317f92f#commitcomment-20779055 in the future

**Comment by rugginoso** [comment]
I'm working on this, just the time to clean-up the code and figure out how to submit the patch.
