### ISSUE TITLE
go1.8: merge CL 36417 to Go 1.8 branch

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#18969]
We need to merge CL 36417 to the Go 1.8 branch for #18968.

CC @crawshaw @bradfitz @broady

**Comment by bradfitz** [comment]
(ab067cde34b515172cf51b4c562b2b4ef3cbe587)

**Comment by odeke-em** [comment]
Since I didn't want to open a new issue for this one
[CL 36470](https://go-review.googlesource.com/36470) and commit https://github.com/golang/go/commit/3b68a647696ebfb61d199155f5f1faa5740e5c55

Perhaps we can repurpose this bug to track CLs that we need to merge for Go1.8?

**Comment by broady** [comment]
I think it's fine to open a new issue for anything that needs merging for 1.8. There shouldn't be many (if any at all).

Closing this (tracked in #18915).

**Comment by ianlancetaylor** [comment]
@broady Did you mean to close this issue?  This one was about CL 36417.  Reopening.

**Comment by broady** [comment]
@ianlancetaylor Nope, I'm just confused. @odeke-em can you open a separate issue for CL 36470?

**Comment by rsc** [comment]
https://go-review.googlesource.com/36421  for this issue.

**Comment by rsc** [comment]
https://go-review.googlesource.com/36422 for CL 36470.

**Comment by odeke-em** [comment]
Thanks @broady @rsc @griesemer, no need for me to file the issue, 
it's already been handled as @rsc mentioned.
