### ISSUE TITLE
net/http: TestServerDuplicateBackgroundRead flake

### ISSUE THREAD

**Issue by josharian** [golang/go#18967]
Happened on a freebsd/amd64 builder:

https://storage.googleapis.com/go-build-log/5a14b612/freebsd-amd64-gce101_645b41a7.log

**Comment by mvdan** [comment]
Spent 20 minutes on this one. Tried putting small sleeps in interesting places, but no luck. The race detector didn't help either with a few thousand runs.

Also did `stress -p 32 ./http.test -test.run TestServerDuplicateBackgroundRead`, still no failures on `linux/amd64` after some 50k runs.

Could this be related to freebsd in any way?

**Comment by bradfitz** [comment]
I can't reproduce this either. And I see nothing suspicious in the test code. Let's close & reopen if this recurs.
