### ISSUE TITLE
text/template, html/template: document Funcs must be called before Parse

### ISSUE THREAD

**Issue by zwass** [golang/go#18971]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.6+

### What operating system and processor architecture are you using (`go env`)?
Any

### What did you do?
https://play.golang.org/p/SeHjhOvCFZ (html/template)
https://play.golang.org/p/EeVfv5_IcQ (text/template)

### What did you expect to see?
I would expect that both `success()` and `fail()` successfully write the string "foo" to stdout

### What did you see instead?
The `fail` function panics with the error, `panic: template: :1: function "foo" not defined`. If possible, it would feel much more consistent for both of these functions to succeed. If that is not possible, updating the documentation to reflect the need for custom functions to be defined before the template is loaded would be very helpful to confused users.

See, for example:
- http://stackoverflow.com/questions/17570977/template-1-function-copyrightyear-not-defined
- http://stackoverflow.com/questions/17843311/template-and-custom-function-panic-function-not-defined

**Comment by paranoiacblack** [comment]
Just adding myself as a reviewer here; I'm not sure how to find the github account of the CL creator.

**Comment by odeke-em** [comment]
Ping @gulyasm if am not mistaken.

**Comment by gulyasm** [comment]
Yes, it's me.
