### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RUSshy** [golang/go#18978]
I wonder why you refuse to let us do that:

```go
package main

import "fmt"

func main() 
{
    fmt.Println("hello world")
}
```

For the love of god, don't treat this as an error, let me put the brackets on a new line, i do that for all my other projects, my brain refuse to accept this:

```go
func main() {
    fmt.Println("hello world")
}
```

**Comment by ianlancetaylor** [comment]
This is not the kind of change we are going to make to the language at this point.

**Comment by RUSshy** [comment]
Why? code style shouldn't be dictated by the compiler.. this is really counter productive imo

Just add a flag to disable that warning?

**Comment by ALTree** [comment]
This is in the FAQ: https://golang.org/doc/faq#semicolons

> For instance, the opening brace of a function cannot appear on a line by itself. 

that's because of automatic semicolon insertion.

> Just add a flag to disable that warning?

It's not a warning (there are no compiler warnings in go), it's a compile error. You can't fix compilation errors with a flag..

**Comment by RUSshy** [comment]
I find it just weird to tell me how i'm supposed to write my code..  it just looks like your decided to force it because of something you wasn't able to design correctly, other languages don't force that, i put brackets on new line on all my projects (JS/Java/C#/Swift) just weird to have an exception that break my habits

**Comment by ianlancetaylor** [comment]
This issue is closed.  If you want to discuss it, please use a forum; see https://golang.org/wiki/Questions .
