### ISSUE TITLE
cmd/asm: missing instruction PSRAD / PSRAW on AMD64

### ISSUE THREAD

**Issue by samuel** [golang/go#18972]
### What version of Go are you using (`go version`)?

go version go1.8rc3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH=amd64

### What did you do?

Unless I'm missing it due to being named something different, the PSRAD/W instruction is not implemented by the amd64 assembler. It's very useful when needing to sign-extend 16-bit integers to 32-bit integers and SSE4.1 isn't available (PMOVSXWD =  PUNPCKLWL + PSRAD)

**Comment by ALTree** [comment]
In the list I see a `PSRAL` and a `PSRAW`. 

Does `PSRAW` not work?
Is `PSRAL` PSRAD's name? Have you tried it?

**Comment by samuel** [comment]
Oh, sorry! Totally didn't see those but should have realized with the naming convention (Long=Word). Thanks
