### ISSUE TITLE
bytes: degradations in compareBytes benchmarks between 1.7 and 1.8

### ISSUE THREAD

**Issue by laboger** [golang/go#18986]
There are two benchmarks in the bytes test for IndexByte that degraded between 1.7 and 1.8 and possibly should be investigated.

BenchmarkCompareBytesIdentical-16                 6.91            11.4            +64.98%
BenchmarkCompareBytesToNil-16                     7.40            11.1            +50.00%

And this one!  I think it is crossing a page boundary or something.
BenchmarkCompareBytesBigIdentical-16              6.62            46511           +702483.08%

**Comment by bradfitz** [comment]
Did you mean to close this? Which OS/arch?

**Comment by mundaym** [comment]
Not sure about the others but the BenchmarkCompareBytesBigIdentical numbers indicate that the `bytes.Compare` function is missing a check for matching pointers. In other words it is probably missing a special case for this situation:

```go
a := [65536]byte{}
bytes.Compare(a[:], a[:])
```
