### ISSUE TITLE
doc: from contribute.html it is not clear what "CL" is

### ISSUE THREAD

**Issue by opennota** [golang/go#18989]
contribute.html uses the acronym "CL" without defining it first:

> If your change relates to an open issue, please add a comment to the issue announcing your proposed fix, including a link to your CL. 

Not understood or misunderstood words can block one's understanding of the document or even cause one to abandon the subject. It would be better to introduce the acronym immediately after the first occurrence of "change list", e.g.

> Unless explicitly told otherwise, such as in the discussion leading up to sending in the **change list (CL)**, it's better not to specify a reviewer

**Comment by rakyll** [comment]
I would just suggest replacing CL with change, given CLs are always referred as "change lists" through the contribute doc. Sending a change.
