### ISSUE TITLE
x/tools/cmd/guru: describe on os/file.go fails

### ISSUE THREAD

**Issue by Darren** [golang/go#18992]
### What version of Go are you using (`go version`)?
go version go1.7.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/darren/Sources/go"
GORACE=""
GOROOT="/Users/darren/.local/go1.7.5"
GOTOOLDIR="/Users/darren/.local/go1.7.5/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s0/xbktqfg94z35r7hf01wx11dc0000gn/T/go-build825769959=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
 $ cd /usr/local/go
 $ git show 
 commit 0c9325e13d5d9e2ab7459522e3556f6f44cbcb10
 $ guru describe src/os/file.go:#4115

### What did you expect to see?
should print the the syntax at offset 4115

### What did you see instead?
/usr/local/go/src/os/file.go:120.11-120.17: selector of type invalid type

**Comment by Darren** [comment]
I see what the problem is: it's because GOROOT does not point to /usr/local/go!

**Comment by alandonovan** [comment]
FYI: Go users rarely need to set GOROOT.  When you build the Go standard library, the runtime package embeds the value of $GOROOT, so the 'go' command and other tools can find the source tree without further information, so long as you didn't move it.

Glad you solved your problem.
