### ISSUE TITLE
time: add Duration.Truncate

### ISSUE THREAD

**Issue by cespare** [golang/go#18996]
See @rsc's comment at https://github.com/golang/go/issues/18991#issuecomment-278444680.

I was thinking of adding:

```
// Truncate returns the result of rounding d towards zero
// to a multiople of td.
func (d Duration) Truncate(td Duration) Duration
```

I'll send a CL but I want to make sure this looks good.

**Comment by cespare** [comment]
Do we need Round as well, then?

**Comment by rogpeppe** [comment]
Yeah, if we have Truncate, I reckon we should have Round too.

**Comment by rsc** [comment]
Yes, Duration and Round together please. Let's call the parameter some single letter, like m (as in "multiple of m").
