### ISSUE TITLE
os.Setenv not working on Windows 10 64 bit

### ISSUE THREAD

**Issue by MintyOwl** [golang/go#19009]
Windows 10 64bit (Version 1607  (KB3211320))

Go 1.7.5

I tried with `go run .\main.go` and not working. os.Getenv works perfectly but not os.Setenv
No error while running above command. Outputs Getenv successfully.

**Comment by MintyOwl** [comment]
Cannot set ENV from powershell either, so  I am closing it. Most likely problem with computer.

**Comment by wwalexander** [comment]
Can you post your code and the expected behavior?

I tested os.Setenv on the same version of Windows 10 and the same architecture:

```
package main

import (
	"os"
)

func main() {
	if err := os.Setenv("key", "value"); err != nil {
		panic(err)
	}
	if os.Getenv("key") != "value" {
		panic("wrong value")
	}
}
```

The program runs without panicking. Are you by any chance trying to access the variable you set via os.Setenv from outside the process?

**Comment by MintyOwl** [comment]
Thanks for the link...So os.Setenv is not persistent. Nevermind I am now issuing the exec.Command("SETX","key","value") powershell command instead and now its persisting on user variable environment. // +build windows...
