### ISSUE TITLE
x/mobile: some question

### ISSUE THREAD

**Issue by solua** [golang/go#19006]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
IOS, Android

### What did you do?
Generate a lib with gomobile

### What did you expect to see?
Function call completely

### What did you see instead?
Function not response

**Comment by solua** [comment]
Thanks gomobile team for amazing project.

I have used gomobile in 3 project. Generate lib for android and ios app.
I have no issues with android, but with ios.
Sometime I open a new thread and call function login in go lib but function didn't response.
This issue happen sometime and in some device not all (Iphone 7, Iphone 6).
My login function make a http request, it too simple too make problem.
Can you suggest me ?

**Comment by minux** [comment]
if you're asking a question, please see https://golang.org/wiki/Questions.

If you're reporting a bug, please include more information (iOS version,
XCode version, code, instruction to build and observed/expected results) so
that we can reproduce the bug.
Thanks.

PS: please try Go 1.8rc first.

**Comment by solua** [comment]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
IOS version 10.2.1
Xcode version 8.2
Swift 3.0

### What did you do?
Generate a share lib with gomobile.
gomobile bind -target=ios 

Bug happen sometime in some device not all.
App didn't crash but go function didn't response.

When user click Login button, Swift take event and make new thread. Thread call login function in go, and go have nerver response.

App ok almost time, bug happen some time and unpredictable.

**Comment by eliasnaur** [comment]
Have you tried to reproduce the hang while running from Xcode? In that case, you might be able to pause the app and see where it is stuck.

Is it possible to send me a small sample that exhibits the buggy behaviour?

**Comment by solua** [comment]
Hi Eliasnaur,

I tried it many time, if bug happen, function map from go nerver return.
For example, I checked debug at line 50, call go function at line 49, my debug point nerver hit. No expecption, no crash, no log( I insert log in go to make sure).
I , sometime, think thread run go was killed by os.

**Comment by minux** [comment]
please note that lldb is very bad at debugging Go programs.
You'd better use printf-style debugging to figure out why it's hang.

**Comment by solua** [comment]
This is my proxy struct:
type AppProxy interface {
	Log(logMess string)
	LoginNotify(code int)
}

Public function:

func Login(userName,pwd string,proxy AppProxy) {

proxy.Log("Begin login call")
result := login(userName,pwd)
if result {
proxy.LoginNotify(0)//login success
}else{
proxy.Log("Login fail")
}
proxy.Log("End login")
}

I implement AppProxy in Swift with swift log function (NSLog)
But no log appear in Xcode, no crash and my debug poiunt have never hit.

Thanks.

**Comment by eliasnaur** [comment]
If you want me to debug your issue, I'll need a complete sample I can run in Xcode.

**Comment by solua** [comment]
Hi Eliasnaur,

I think this issues because something wrong in IOS os, android is ok.
I will try it again in new project. 
If it happen again, I will push full source code.

Thank Eliasnaur,

**Comment by solua** [comment]
Hi Eliasnaur,

I think this issues because something wrong in IOS os, android is ok.
I will try it again in new project. 
If it happen again, I will push full source code.

Thank Eliasnaur,
