### ISSUE TITLE
cmd/compile: regression passing constants to mapaccess routines

### ISSUE THREAD

**Issue by randall77** [golang/go#19015]
```
func f(m map[int]int) int {
	return m[5]
}
```

Passing the `5` to `mapaccess1_fast64` used to be just a store of 5 to the stack.  Now it is a load of 5 from a global constant, then a store of that value to the stack.

In Go 1.8rc3:
```
	0x001d 00029 (tmp2.go:4)	LEAQ	type.map[int]int(SB), AX
	0x0024 00036 (tmp2.go:4)	MOVQ	AX, (SP)
	0x0028 00040 (tmp2.go:4)	MOVQ	"".m+48(FP), AX
	0x002d 00045 (tmp2.go:4)	MOVQ	AX, 8(SP)
	0x0032 00050 (tmp2.go:4)	MOVQ	$5, 16(SP)
	0x003b 00059 (tmp2.go:4)	PCDATA	$0, $1
	0x003b 00059 (tmp2.go:4)	CALL	runtime.mapaccess1_fast64(SB)
```

At tip:
```
	0x001d 00029 (tmp2.go:4)	LEAQ	type.map[int]int(SB), AX
	0x0024 00036 (tmp2.go:4)	MOVQ	AX, (SP)
	0x0028 00040 (tmp2.go:4)	MOVQ	"".m+48(FP), AX
	0x002d 00045 (tmp2.go:4)	MOVQ	AX, 8(SP)
	0x0032 00050 (tmp2.go:4)	MOVQ	"".statictmp_0(SB), AX
	0x0039 00057 (tmp2.go:4)	MOVQ	AX, 16(SP)
	0x003e 00062 (tmp2.go:4)	PCDATA	$0, $1
	0x003e 00062 (tmp2.go:4)	CALL	runtime.mapaccess1_fast64(SB)
```

@mdempsky 
Might be related to #18370.

This issue doesn't seem to occur for regular function calls - we marshal those arguments correctly.

**Comment by bradfitz** [comment]
Or @josharian's 03583675765933d4a5fb394cfa89fb41b274aaa7 or c682d3239e5aa05a77ad21f2267efc4e2e60c05f?

**Comment by cherrymui** [comment]
It is c682d32, CL https://go-review.googlesource.com/35554. Before this CL, it generates autotmp to make the constant addressable, after this CL it makes statictmp. It seems that we actually don't need to make it addressable though?

**Comment by josharian** [comment]
Looking into this
