### ISSUE TITLE
encoding/binary: varint functions could be better described

### ISSUE THREAD

**Issue by agl** [golang/go#19010]
The comments for the varint functions in [encoding/binary](https://godoc.org/encoding/binary) don't mention anything about _how_ the integer is encoded. Since there are quite a number of options, it should probably be more clear that it's a little-endian, base128 format.

**Comment by cznic** [comment]
Package documentation says:

> The varint functions encode and decode single integer values using a variable-length encoding; smaller values require fewer bytes. For a specification, see https://developers.google.com/protocol-buffers/docs/encoding.

**Comment by griesemer** [comment]
@cznic Thanks for the hint. I agree, that seems good enough (we don't want to repeat everything for each of the 4 functions, I assume).
