### ISSUE TITLE
link assumes that there is only one section symbol per section

### ISSUE THREAD

**Issue by espindola** [golang/go#19018]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.4, but the same code is on trunk.

### What operating system and processor architecture are you using (`go env`)?

freebsd x86_64

### What did you do?

Build go with lld (the llvm linker) installed as the system linker. The bootstrapped go executable crashes on startup.

The issue is that go's link assumes that there is only one section symbol:

https://go.googlesource.com/go/+/master/src/cmd/link/internal/ld/ldelf.go#1037

when using -r lld can produce a file with multiple section symbos. One for each input object section and each having different st_value:

% readelf -sW  lld.o | grep SECTI
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT    1
     5: 0000000000000000     0 SECTION LOCAL  DEFAULT    3
     6: 0000000000000000     0 SECTION LOCAL  DEFAULT    4
     7: 0000000000000000     0 SECTION LOCAL  DEFAULT    5
     8: 0000000000000000     0 SECTION LOCAL  DEFAULT    6
    14: 0000000000000140     0 SECTION LOCAL  DEFAULT    1
    15: 0000000000000008     0 SECTION LOCAL  DEFAULT    3
    16: 0000000000000028     0 SECTION LOCAL  DEFAULT    4
    17: 0000000000000053     0 SECTION LOCAL  DEFAULT    5
    18: 0000000000000078     0 SECTION LOCAL  DEFAULT    6

**Comment by thanm** [comment]
I can try to take a stab at this issue. I am not a linker expert, but I'll poke at it and see whether there is a simple fix. I see a comment here

https://go.googlesource.com/go/+/master/src/cmd/link/internal/ld/ldpe.go#264

that indicates this scenario comes up in other contexts.

**Comment by thanm** [comment]
I built a copy of lld (tip, 295052) along with clang, etc. I updated my PATH setting to pick up clang for 'cc' and lld for 'ld', and then did a bootstrap build (all.bash) of Go tip (revision 79fab70a63e03897db384fbf1b5fdeeb6f9f4b92).

I see test failures, but no crashing of the resulting go binary. Representative failure:

```
--- FAIL: TestCgoPprofPIE (8.91s)
  ld: error: go.go:(.rodata+0xA20): can't create dynamic relocation R_X86_64_64 
    against symbol 'type..eq.[11]string' defined in /tmp/go-link-336962965/go.o
```
Is this the same failure that you were seeing? If doesn't sound like it.

If you could give me some more detailed repro instructions that would be great. It would also help if you could point out the specific object file generated by lld that triggered the problem.

**Comment by espindola** [comment]
On 15 February 2017 at 10:06, Than McIntosh <notifications@github.com> wrote:
>
> I built a copy of lld (tip, 295052) along with clang, etc. I updated my PATH setting to pick up clang for 'cc' and lld for 'ld', and then did a bootstrap build (all.bash) of Go tip (revision 79fab70).
>
> I see test failures, but no crashing of the resulting go binary. Representative failure:

Looks like we just coded past each other.

I change lld in r294816 to create a single section symbol. That still
has some regressions on mips, so if it is convenient to change go
instead that would be very appreciated.


> --- FAIL: TestCgoPprofPIE (8.91s)
>   ld: error: go.go:(.rodata+0xA20): can't create dynamic relocation R_X86_64_64
>     against symbol 'type..eq.[11]string' defined in /tmp/go-link-336962965/go.o
>
> Is this the same failure that you were seeing? If doesn't sound like it.

No, it is not. How do I reproduce it?

> If you could give me some more detailed repro instructions that would be great. It would also help if you could point out the specific object file generated by lld that triggered the problem.

I was using the freebsd packages build (I am trying to build all ports
with lld). With that the reproduction is just "make build" in
freebsd-ports/lang/go. The build works, but the resulting go binary
always crashes.

Cheers,
Rafael

**Comment by thanm** [comment]
FreeBSD ports build -- I don't have easy access to a FreeBSD machine... I will see if I can experiment and come up with a reproducer on my own. Please stay tuned.

Reproducing the TestCgoPprofPIE test failure: here "TestCgoPprofPIE" is a testpoint within the Go runtime's package test, and it is a fairly complicated test (involves building and running various Go programs under pprof).

Here is a recipe that should work. This assumes that you already have a working copy of Go on your system (for bootstrapping). Assuming that the directory "/CONTAINSLLD" contains a link "ld" to the version of lld you are interested in testing:

```
  # Download and build Go.
  # Takes about 500mb of disk on my machine (Ubuntu, x64_64).
  cd /tmp
  git clone https://go.googlesource.com/go
  cd go/src
  bash make.bash

  # Set up path for test
  export PATH=/CONTAINSLLD:/tmp/go/bin:$PATH
  cd runtime

  # This runs the testpoint itself
  go test -test.v -run TestCgoPprofPIE .

  # This is a replay of the build invoked by the test above that fails.
  go build -x -work  -ldflags=-extldflags=-pie ./testdata/testprogcgo 1>transcript.txt 2>&1

```
If you look through "transcript.txt" you'll see the commands that were executed to do the build that is running into the errors. Let me know if this works for you.

**Comment by thanm** [comment]
I am not having any luck reproducing this. I cobbled together a FreeBSD system using a discarded disk and a home PC (freebsd-version reports 11.0-RELEASE-p1). I then created an LLVM repo an backed it up to Feb 10th, just before r294816, which reverts back to a single section symbol. Repo state:

```
llvm: svn 294794, git 53c27da76d919439867d4b5cdcfaeb8a13cc9e7d
llvm/tools/lld: svn 294776, git 1b7ee09bebd9eb907362bdac7cfe4bc308079df1

```
I was able to build lld using this, then I redid the /usr/ports/lang/go build with my path set to pick up lld in the proper way -- result seems fine, no problems executing the generated "go" binary.

I am going to go ahead and close this bug -- if you can post an easier reproducer of some sort I would be willing to take another look.

**Comment by emaste** [comment]
> I was able to build lld using this, then I redid the /usr/ports/lang/go build with my path set to pick up lld in the proper way -- result seems fine, no problems executing the generated "go" binary.

Sometimes it can be tricky to get the FreeBSD build infrastructure to use a non-default linker -- for testing I've just made /usr/bin/ld a symlink to my ld.lld to be sure I get the right one. LLD writes a .comment to the output file, so you should be able to check that the binary was indeed linked with LLD via a command like `% readelf --string-dump=.comment <binary>`

**Comment by emaste** [comment]
FreeBSD folks encountered an issue (presumably this issue) with the go port, when testing with the copy of LLD 4.0.0 included in the base system: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214864#c13

@thanm would it be sufficient if I can produce a VM image for you that could be used to reproduce?
