### ISSUE TITLE
reflect: multiple "reflect" packages results in "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by rbredlau** [golang/go#19028]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.4 linux/386

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/robert/workspace.go"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build941335608=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

$GOPATH/src/test/reflectCrash/main.go
```
// If the two lines commented BAD are commented out then there is no crash.
package main

import (
        "fmt"
        r "reflect"
        "test/reflectCrash/foo"
        "test/reflectCrash/reflect" // BAD
)

type A struct {
        r reflect.Type // BAD
        f foo.Type
}

func (a A) one() {
}

func (a A) One() string {
        return "Hello"
}

func (a A) Two() (int, bool, string) {
        return 100, false, "Hello"
}

func main() {
        var a A
        fmt.Println("Hello")
        typ := r.TypeOf(a)
        fmt.Printf("num methods %v\n", typ.NumMethod())
        for k := 0; k < typ.NumMethod(); k++ {
                fmt.Printf("method.%v\n", k)
                method := typ.Method(k)
                fmt.Printf("%T %T\n", method, 0)
        }
}
```

$GOPATH/src/test/reflectCrash/reflect/f.go
```
package reflect

import (
        "reflect"
)

type Type reflect.Type
```

$GOPATH/src/test/reflectCrash/foo/f.go
```
package foo

import (
        "reflect"
)

type Type reflect.Type
```

### What did you expect to see?
A program that doesn't crash.

### What did you see instead?
```
Hello
num methods 2
method.0
reflect.Method int
method.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x80a3160]

goroutine 1 [running]:
panic(0x80d4b20, 0x1840a010)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x331
reflect.(*rtype).Method(0x80dadc0, 0x1, 0x80c337f, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.7/src/reflect/type.go:839 +0x190
main.main()
        /home/robert/workspace.go/src/test/reflectCrash/main.go:33 +0x311
```

**Comment by ALTree** [comment]
It's in go1.8 too, so it's not a regression. Smaller reproducer:

---
`github.com/ALTree/test/foo/f.go`

```
package reflect
```
---
`github.com/ALTree/test/main.go`

```
package main

import (
	"fmt"
	r "reflect"

	_ "github.com/ALTree/test/foo"
)

type A struct{}

func (a A) One() {
}

func (a A) Two() (int, int) {
	return 1, 2
}

func main() {
	var a A
	typ := r.TypeOf(a)
	fmt.Println("TypeOf(a).NumMethods() =", typ.NumMethod()) // prints 2
	typ.Method(1)
}
```
---
Gives:

```
TypeOf(a).NumMethods() = 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x45df36]

goroutine 1 [running]:
reflect.(*rtype).Method(0x48f420, 0x1, 0x47a177, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/alberto/go/src/reflect/type.go:859 +0x1b6
main.main()
	/home/alberto/gocode/src/github.com/ALTree/test/main.go:23 +0x145
exit status 2
```

**Comment by ericlagergren** [comment]
Can reproduce on go1.7.5 darwin/amd64.

**Comment by ericlagergren** [comment]
Commenting out src/cmd/compile/internal/gc/bimport.go:249 fixes this issue.

(Issue that spurred 1f44643: https://github.com/golang/go/issues/16133)

**Comment by bradfitz** [comment]
@griesemer, the bisect (details above) points to you. Care to take a look?

**Comment by griesemer** [comment]
Thanks, @ericlagergren, for tracking this down. I can confirm that commenting out the line you mentioned makes the crash disappear. Investigating root cause.
