### ISSUE TITLE
plugin: building a plugin with a non main package produces no error

### ISSUE THREAD

**Issue by vimalk78** [golang/go#19023]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8rc3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vimal/gowork"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build128255364=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
tried building a plugin with a non main package
```
package junk

import "C"

func HelperFunc() string {
        return "help"
}
```

`$ go build -buildmode=plugin -o junk.so`

### What did you expect to see?

error that no main package found

### What did you see instead?
it produces a .so file, probably because of the -o flag.
if dont use -o flag, no output is produced.

```
$ file junk.so
junk.so: current ar archive
$ ls -al junk.so
-rw-r--r-- 1 vimal users 7266 Feb 11 00:43 junk.so


```

**Comment by crawshaw** [comment]
This was fixed in https://golang.org/cl/40691
