### ISSUE TITLE
Proposal: Variable scope within for loop

### ISSUE THREAD

**Issue by mrajashree** [golang/go#19026]
Hi,
Golang follows variable declaration, usage and scoping strictly and this is very helpful for a developer to avoid mistakes. But is it possible for a for-loop to check whether variables being declared within it are already declared oustide it in the same function?
For example this snippet of code
```
var str = "abc"
	for i :=0; i < 3; i++ {
		if i/2 == 1 {
			str := str + "d"
			fmt.Println(str)
		}
	}
	fmt.Println(str)
```
Within for loop, str would be "abcd", but outside it is only "abc". And I won't get any errors about redeclaring the variable `str` since its scope within for loop is only limited to it. So is it possible to check variable's previous declaration and give warnings/errors about redeclaration. I might be wrong about this so even if anyone can comment explaining why it can't be changed then that'll be helpful too. Thanks in advance

**Comment by bradfitz** [comment]
Coming from Python or JavaScript this might be confusing, but coming from other block-scoped languages, this is a feature and what people expect.

The vet/link tools at least warn about some cases that are likely wrong, and the compiler warns about some too.

https://golang.org/ref/spec#Return_statements

> Implementation restriction: A compiler may disallow an empty expression list in a "return" statement if a different entity (constant, type, or variable) with the same name as a result parameter is in scope at the place of the return.

Issue #377 tracks confusion about := in general. I'm going to close this as a dup of that.
