### ISSUE TITLE
whn I use gdb to debug go project ,some errors occurs.... 

### ISSUE THREAD

**Issue by fankeke** [golang/go#19038]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 linux/386 

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOHOSTOS="linux"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?

gdb version:
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6) 

File "/usr/local/go/src/runtime/runtime-gdb.py", line 205, in is_iface 
except gdb.error: 
AttributeError: 'module' object has no attribute 'error' 

Is my gdb error,or python module lost? 
what should i do ?  many thanks...

**Comment by ALTree** [comment]
This is likely a dup of #10359, and it's caused by the fact that your gdb version (7.2) is very old. 

It looks like "we don't support GDB < 7.3" (see Austin's comment on that issue), so this failure is expected. You'll need a newer version of gdb to debug go programs.

**Comment by fankeke** [comment]
@ALTree 
many thanks, I update my gdb to verison7.9 ,and it works well . 
thanks for reply so quickly ,it helps a lot. 
:)
