### ISSUE TITLE
when I use gdb to debug go project, gdb report errors...

### ISSUE THREAD

**Issue by fankeke** [golang/go#19037]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 linux/386 

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOHOSTOS="linux"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?

File "/usr/local/go/src/runtime/runtime-gdb.py", line 205, in is_iface 
except gdb.error:

**Comment by ALTree** [comment]
Same as #19038, closing this one.
