### ISSUE TITLE
x/mobile: document the requirements for running tests

### ISSUE THREAD

**Issue by 8tt** [golang/go#19046]
I'm trying to figure out why x/mobile tests are failing with my setup. Below is a list of failing tests, not sure what is the reason. 

go version go1.7.4 darwin/amd64
gomobile version +60b0aaa Tue Jan 31 20:25:16 2017 +0000 (android,ios); androidSDK=
macOS 10.12.3

### What did you do?
```
# rm -rf $GOPATH/pkg
# rm -rf $GOPATH/src/golang.org/x/mobile
go get golang.org/x/mobile/cmd/gomobile
gomobile init
go test golang.org/x/mobile/... > test-results.txt 2>&1
cat test-results.txt | grep FAIL
```

### What did you expect to see?
No failing tests.

### What did you see instead?
```
--- FAIL: TestGenJava (5.58s)

--- FAIL: TestGenGoJavaWrappers (4.73s)
FAIL
FAIL	golang.org/x/mobile/bind	16.650s
--- FAIL: TestObjcSeqBench (9.76s)
		** TEST FAILED **
		** TEST FAILED **
FAIL
FAIL	golang.org/x/mobile/bind/objc	45.692s
--- FAIL: TestGobind (3.73s)
    --- FAIL: TestGobind/ObjC-Testpkg (0.04s)
    --- FAIL: TestGobind/Java-Testpkg (0.05s)
    --- FAIL: TestGobind/Go-Testpkg (0.04s)
    --- FAIL: TestGobind/Java-Javapkg (1.44s)
    --- FAIL: TestGobind/Go-Javapkg (1.08s)
FAIL
FAIL	golang.org/x/mobile/cmd/gobind	3.740s
--- FAIL: TestInit (2.25s)
FAIL
FAIL	golang.org/x/mobile/cmd/gomobile	4.832s
FAIL	golang.org/x/mobile/exp/gl/glutil [build failed]
--- FAIL: TestImport (0.53s)
FAIL
FAIL	golang.org/x/mobile/internal/importers/java	0.537s
--- FAIL: TestImport (0.03s)
FAIL
FAIL	golang.org/x/mobile/internal/importers/objc	0.037s
```

Full output (7000 lines)
https://gist.github.com/8tt/996bac25dfd29f950e30a0f60c9cce81

/cc @eliasnaur @crawshaw @hyangah

**Comment by eliasnaur** [comment]
I'm not sure why the java_test.go:71 test is getting 2 classes instead of 1. Could you try

https://go-review.googlesource.com/c/37320/

and see if that fixes that particular test? If not, could you paste the output from `javap -J-Duser.language=en -s -protected -constants java.lang.Object` and `javap -J-Duser.language=en -s -protected -constants java.lang.Runnable` on the system that fails the java_test.go:71 test? Thanks.

**Comment by eliasnaur** [comment]
Also, please re-run the test suite after running `go install golang.org/x/mobile/cmd/...` (to make sure the gobind and gomobile binaries are up-to-date).

**Comment by 8tt** [comment]
Thanks, I've re-run the tests using https://go-review.googlesource.com/c/37320/ (184897121af27bc8e7d8edfd50f297e81db2f132).

The java test (java_test.go:71: got 2 classes, expected 1) finishes successfully.

Output of javap -J-Duser.language=en -s -protected -constants java.lang.Object and javap -J-Duser.language=en -s -protected -constants java.lang.Runnable
https://gist.github.com/8tt/9db6b9753f67e08820a5d3330a83fec7

Full test output:
https://gist.github.com/8tt/57750ee50cf2f69c1f9b53a090700ec6

```
--- FAIL: TestGobind (32.65s)
    --- FAIL: TestGobind/ObjC-Testpkg (0.04s)
    --- FAIL: TestGobind/Java-Testpkg (0.05s)
    --- FAIL: TestGobind/Go-Testpkg (0.03s)
FAIL
FAIL	golang.org/x/mobile/cmd/gobind	32.657s
--- FAIL: TestInit (1.97s)
FAIL
FAIL	golang.org/x/mobile/cmd/gomobile	4.221s
FAIL	golang.org/x/mobile/exp/gl/glutil [build failed]
--- FAIL: TestImport (0.03s)
FAIL
FAIL	golang.org/x/mobile/internal/importers/objc	0.037s
```

**Comment by eliasnaur** [comment]
Several tests have been fixed; can you try again and see if any still fail for you?

**Comment by 8tt** [comment]
All tests pass now. Thank you.
