### ISSUE TITLE
doc: FAQ versioning question out of date

### ISSUE THREAD

**Issue by robpike** [golang/go#19049]
https://golang.org/doc/faq#get_version mentions Go 1.5 and vendoring but not dep. It needs to be updated.

**Comment by bradfitz** [comment]
dep is still an experiment. I'm not sure it needs to be called out yet. That might overwhelm the dep developers.

But I'm fine with a qualified mention if they're fine with it.

/cc @sdboyer @carolynvs @jessfraz

**Comment by sdboyer** [comment]
I'm 👍 to a qualified mention. I think we can handle a wave.

**Comment by bradfitz** [comment]
Please send the change.

**Comment by sdboyer** [comment]
OK, I'll get set up for sending CLs and send one in the next day or two.
