### ISSUE TITLE
syscall: missing SYS_GETSOCKOPT in zsysnum_linux_386.go

### ISSUE THREAD

**Issue by riobard** [golang/go#19043]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.5

### What operating system and processor architecture are you using (`go env`)?

Darwin/amd64

### What did you do?

If possible, provide a recipe for reproducing the error.

    GOOS=linux GOARCH=386 go doc syscall.SYS_GETSOCKOPT

### What did you expect to see?

List of defined constants containing SYS_GETSOCKOPT.

### What did you see instead?

    doc: no symbol SYS_GETSOCKOPT in package syscall

**Comment by minux** [comment]
working as intended because there isn't a getsockopt syscall on linux/386.

Long answer:
linux/386 multiplexes all socket syscalls into a one syscall (probably
because there aren't enough registers to pass the arguments.)

https://golang.org/src/syscall/syscall_linux_386.go#L183

**Comment by riobard** [comment]
Thanks a lot for the explanation. In that case, how to implement `Getsockopt*` for structs not implemented in `syscall` or `unix`?  The following code works on linux_amd64. I'd like to know a way to do that on linux_386 as well.

```go
// Call getorigdst() from linux/net/ipv4/netfilter/nf_conntrack_l3proto_ipv4.c
func getorigdst(fd uintptr) (*syscall.RawSockaddrInet4, error) {
	const SO_ORIGINAL_DST = 80 // from linux/include/uapi/linux/netfilter_ipv4.h
	raw := syscall.RawSockaddrInet4{}
	siz := unsafe.Sizeof(raw)
	if _, _, errno := syscall.Syscall6(syscall.SYS_GETSOCKOPT, fd, syscall.IPPROTO_IP, SO_ORIGINAL_DST, uintptr(unsafe.Pointer(&raw)), uintptr(unsafe.Pointer(&siz)), 0); errno != 0 {
		return nil, errno
	}
	return raw, nil
}
```

**Comment by ianlancetaylor** [comment]
Questions are best directed to a forum, rather than the issue tracker; see https://golang.org/wiki/Questions.

On 386 GNU/Linux you'll need to call something along the lines of `Syscall6(syscall.SYS_SOCKETCALL, 15, /* socko pt arguments */)`.

**Comment by riobard** [comment]
Thanks a lot for the pointer! :)
