### ISSUE TITLE
Windows freeze

### ISSUE THREAD

**Issue by amienel** [golang/go#19044]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
i3 CPU , 2 core, 2ghz
4gb mem

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\projects\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
Run this code:

package main

import "fmt"

func counter(n int) {
	for i := 0; i <= n; i++ {
		println("i = ", i, " for n = ", n)
	}
}

func main() {

	for n := 0; n < 1000000; n++ {
		go counter(n)
	}
	var input string
	fmt.Scanln(&input)
}
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Program crash or termination with an error

### What did you see instead?
Windows/machine freeze
Must reset the computer

**Comment by odeke-em** [comment]
Hello @amienel, it looks like you exhausted your system's resources by running
1,000,000 goroutines that altogether count and print to standard output
500,001,500,001 times ie [x * (x+1)]/2 where x=1,000,001.

Just like almost every resource, goroutines aren't free and their control is left at the discretion of the programmer to pick from using synchronization primitives provided by Go, like sync.WaitGroup https://golang.org/pkg/sync/#example_WaitGroup or a buffered/bounded channel.

We use the issues page to track actual bugs in the standard library and family's code. For questions about Go, please see https://github.com/golang/go/wiki/Questions.

You can learn more about concurrency in Go and how to use/control it here https://tour.golang.org/concurrency. This might help you resolve your problem and get solutions
to taming and using concurrency in your code.
