### ISSUE TITLE
add link on non-english documentation

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#19045]
### What version of Go are you using (`go version`)?
go version go1.7.4

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/konstantin/Documents/GoProjects"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build033396211=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
Translate doc. "Effective Go" into Russian language
https://github.com/Konstantin8105/Effective_Go_RU

### What did you expect to see?
Please add link on page https://github.com/golang/go/wiki/NonEnglish

**Comment by ALTree** [comment]
Done. (btw anyone with a github account can edit that page).
