### ISSUE TITLE
cmd/compile: fix s390x load-combining rules

### ISSUE THREAD

**Issue by randall77** [golang/go#19059]
```
func f(b []byte) uint64 {
	return binary.LittleEndian.Uint64(b)
}
```

CL 33632 broke a bunch of the load-combining rules.
CL 36911 fixes the issue that broke them, at least for x86.  It also adds a test for s390x load combining.

Unfortunately, even with the CL 36911 fix, the s390x load-combining tests fail.  I haven't really looked into it yet, hoping an s390x expert can take a look.

**Comment by mundaym** [comment]
I had a quick look, the tests you added are little endian but the instructions you check for aren't the byte reversal instructions (MOVDBR, MOVWBR and MOVHBR). Is that the problem (s390x is big endian)?

**Comment by randall77** [comment]
The test might be wrong, but if you look at the generated assembly it is all 1-byte loads.

**Comment by mundaym** [comment]
OK, I'll take a look.
