### ISSUE TITLE
blog: publish 2016 survey results

### ISSUE THREAD

**Issue by davecheney** [golang/go#19050]
Hello,

It is now two months since the 2016 survey was announced, https://blog.golang.org/survey2016

When will the results be made available?

Thanks

Dave

**Comment by spf13** [comment]
We received an overwhelming amount of feedback which has taken me well over a month to review and analyze. I've finished the analysis and am currently working on a blog post to summarize the results. I hope to have it posted in the next few days.

**Comment by davecheney** [comment]
Thanks for the update.

**Comment by nomad-software** [comment]
Has this been published yet?

**Comment by davecheney** [comment]
It's been two weeks. How are those survey results coming?

**Comment by rsc** [comment]
Still on the way. I've spent probably 40+ hours over the past two weeks on this, as I am sure has Steve. We're not ignoring you! Next year we'll be set up better for a faster turnaround. Sorry.

**Comment by davecheney** [comment]
Thanks for the update Russ.

**Comment by rsc** [comment]
https://blog.golang.org/survey2016-results

**Comment by davecheney** [comment]
Thanks Russ.
