### ISSUE TITLE
tour: Markup error

### ISSUE THREAD

**Issue by Grogdunn** [golang/go#19066]
Contesto: https://go-tour-ita.appspot.com/methods/14

in italian version  ```_interfaccia vuota_``` is not interpreted as " _interfaccia vuota_"

**Comment by bradfitz** [comment]
I would file a bug at https://github.com/golang/tour/

We don't track tour bugs here, and definitely not non-English ones.

Thanks!

**Comment by Grogdunn** [comment]
Ok sorry wrong link.

**Comment by ALTree** [comment]
We should also close  #16880 then.
