### ISSUE TITLE
encoding/xml: bad type for comment field of "pointer to string"

### ISSUE THREAD

**Issue by awalterschulze** [golang/go#19063]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.8rc3

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/waschulze/code"
GORACE=""
GOROOT="/Users/waschulze/go1.8rc3"
GOTOOLDIR="/Users/waschulze/go1.8rc3/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vg/phjwfkn14tjdh3l838gn4q_c395_bf/T/go-build149844404=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

https://play.golang.org/p/AgMlZ8P4eN

### What did you expect to see?

Program exited

### What did you see instead?

panic: xml: bad type for comment field of main.A

**Comment by dsnet** [comment]
\cc @rsc @bradfitz

**Comment by odeke-em** [comment]
From empirical examination this seems to be the offending commit https://github.com/golang/go/commit/daa121167b6ce630aba00195f1c3872cda39a50c and CL https://go-review.googlesource.com/c/15684.

In particular the code patch from that CL is the one that causes it, so undoing it the bug goes away
```diff
diff --git a/src/encoding/xml/marshal.go b/src/encoding/xml/marshal.go
index abb078c..4fa1de0 100644
--- a/src/encoding/xml/marshal.go
+++ b/src/encoding/xml/marshal.go
@@ -760,14 +760,6 @@
 		}
 		vf := finfo.value(val)
 
-		// Dereference or skip nil pointer, interface values.
-		switch vf.Kind() {
-		case reflect.Ptr, reflect.Interface:
-			if !vf.IsNil() {
-				vf = vf.Elem()
-			}
-		}
-
 		switch finfo.flags & fMode {
 		case fCDATA, fCharData:
 			emit := EscapeText
@@ -800,6 +792,16 @@
 					continue
 				}
 			}
+			// Drill into interfaces and pointers.
+			// This can turn into an infinite loop given a cyclic chain,
+			// but it matches the Go 1 behavior.
+			for vf.Kind() == reflect.Interface || vf.Kind() == reflect.Ptr {
+				if vf.IsNil() {
+					return nil
+				}
+				vf = vf.Elem()
+			}
+
 			var scratch [64]byte
 			switch vf.Kind() {
 			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
```

**Comment by odeke-em** [comment]
Just an FYI: that CL was written in October 2015, but submitted a year later in October 2016. On first glance the dates might be confusing.

**Comment by rsc** [comment]
Will look later tonight.

**Comment by awalterschulze** [comment]
credit to @Civil for reporting.

**Comment by ianlancetaylor** [comment]
Reopening for backport of CL 36954 to Go 1.8 release branch.

CC @broady @bradfitz

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/c/37016

**Comment by rsc** [comment]
Merged.

**Comment by awalterschulze** [comment]
Thank you
