### ISSUE TITLE
Json Marshal considers value '0' as nil

### ISSUE THREAD

**Issue by mrajashree** [golang/go#19065]
Hi, during json.Marshal, a 0 value for an int is considered as empty, and the corresponding struct field isn't even made a part of the output. For example, if this is my struct
```
type some struct {
	Name string `json:"name,omitempty"`
	Value int64 `json:"value,omitempty"`
}
```
And this is where I'll marshal it:
```
someEx := &some{
	Name: "blah",
	Value: 0,
}
bodyContent, _ := json.Marshal(someEx)
```
The value of `string(bodyContent)` will be `{"name":"blah"}`. But when I use the following value
```
someEx := &some{
	Name: "blah",
	Value: 1,
}
```
Then the value of `string(bodyContent)` is `{"name":"blah","value":1}`.
I think that even if the value is 0, it can be needed by some applications, is it possible to pass it along?

**Comment by bradfitz** [comment]
Just drop the `,omitempty` part?

For questions about Go, see https://golang.org/wiki/Questions.

If this is a bug report, though, feel free to reopen this.

**Comment by mrajashree** [comment]
Ah my bad. Don't know how I didn't notice that
