### ISSUE TITLE
internal/poll: writeConsole discards error on windows

### ISSUE THREAD

**Issue by davecheney** [golang/go#19068]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +15c62e8 Mon Feb 13 20:10:19 2017 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

While reviewing 3792db5 I spotted this potential error

https://github.com/golang/go/blob/master/src/internal/poll/fd_windows.go#L625

### What did you expect to see?

                        err := syscall.WriteConsole(fd.Sysfd, &uint16s[0], uint32(len(uint16s)), &written, nil)
                        if err != nil {
                                return 0, err
                        }

### What did you see instead?

                        err = syscall.WriteConsole(fd.Sysfd, &uint16s[0], uint32(len(uint16s)), &written, nil)
                        if err != nil {
                                return 0, nil
                        }

**Comment by ianlancetaylor** [comment]
Thanks for spotting that.  The error was in fact faithfully copied into internal/poll from its previous existence in os, where it was added back in https://golang.org/cl/6488044 (18601f88fda8b037726b2e45a5032f680d47f713).

I sent CL 36935 to fix it.

**Comment by davecheney** [comment]
Thanks.

**Comment by alexbrainman** [comment]
Thank you everyone

Alex
