### ISSUE TITLE
cmd/compile: remove inl cost toolstash hacks

### ISSUE THREAD

**Issue by josharian** [golang/go#19081]
[CL 31674](https://go-review.googlesource.com/c/31674/) was reverted because it caused a Google internal test to fail. It really should not have; it probably indicates an existing latent compiler bug. And I'd like to remove these hacks for 1.9. I don't have access to the test; this is a request to extract a public version of the test so I can try to fix it.

cc @mdempsky @dsnet

**Comment by mdempsky** [comment]
FYI #18336.

**Comment by josharian** [comment]
Thanks! Closing as dup.
