### ISSUE TITLE
talks: 2017/State of Go, image on slide 2 is missing

### ISSUE THREAD

**Issue by davecheney** [golang/go#19083]
https://talks.golang.org/2017/state-of-go.slide/state-of-go/img/flying.png << 404

**Comment by campoy** [comment]
it looks good to me :-/

https://talks.golang.org/2017/state-of-go/img/flying.png

![screen shot 2017-02-14 at 1 49 28 pm](https://cloud.githubusercontent.com/assets/2237452/22951015/7f69cf46-f2bc-11e6-96f6-14b52b418e5d.png)

**Comment by davecheney** [comment]
Weird. They were all broken last night.

**Comment by campoy** [comment]
Where did you get that URL from? It's not a valid one

**Comment by davecheney** [comment]
That's the url in the source of the html for the slide.

**Comment by campoy** [comment]
Not on my browser!
![screen shot 2017-02-14 at 2 03 40 pm](https://cloud.githubusercontent.com/assets/2237452/22951545/77a666dc-f2be-11e6-847a-6f787ed03725.png)

**Comment by davecheney** [comment]
PEBKAC
