### ISSUE TITLE
cmd/compile: goto over type/const declarations is erroneously rejected

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19088]
The Go spec (section ["Goto statements"](https://golang.org/ref/spec#Goto_statements)) says "Executing the "goto" statement must not cause any variables to come into scope that were not already in scope at the point of the goto."

cmd/compile erroneously rejects this code:

    package p
    
    func f() {
    	goto out
    	type x int
    out:
    }

with

    /tmp/goto.go:4: goto out jumps over declaration of x at /tmp/goto.go:5

**Comment by mdempsky** [comment]
Also, go/types accepts the test case.

**Comment by dr2chase** [comment]
Can't we argue that there is a scope between "out:" and "}" ?

**Comment by mdempsky** [comment]
@dr2chase Sorry, I'm not sure I understand your question.

The issue is that the Go spec forbids gotos that jump over *variable* declarations such as:

      goto out
      var x int
    out:

But cmd/compile (and gccgo) are also rejecting gotos that jump over type and constant declarations.

**Comment by dr2chase** [comment]
Ah, oops, never mind.

**Comment by griesemer** [comment]
Probably not urgent since we lived with this forever. Yet also safe to fix because it will be backward-compatible with existing code (it's lifting a restriction).

**Comment by ALTree** [comment]
Exact dup of #13521 and #8042.

**Comment by mdempsky** [comment]
@ALTree Good finds. Closing as duplicate of #8042.
