### ISSUE TITLE
x/build: newer FreeBSD builders

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19097]
We don't have FreeBSD 11 builders (only 9 and 10).

Probably time to add them.

**Comment by paulzhol** [comment]
I'd like to help, is it just updating https://github.com/golang/build/blob/master/env/freebsd-amd64/make.bash and creating a FreeBSD 11.0 image?

**Comment by bradfitz** [comment]
Yes. I'd copy it to a new directory first so we don't delete the old one.

**Comment by paulzhol** [comment]
I was thinking on just adding another `11.0)` case to the switch. BTW should 10.1 be updated to 10.3?
Technically 9.3 is EOL since the start of 2017...

**Comment by bradfitz** [comment]
Oh, I missed that it has a switch. Great. Just continue that pattern.

You can update 10.1 to 10.3 but file a separate bug for me to deploy that first so we don't forget.

**Comment by paulzhol** [comment]
I've uploaded [freebsd-amd64-gce103.tar.gz](https://storage.googleapis.com/freebsd-buidlet-images/freebsd-amd64-gce103.tar.gz). While [freebsd-amd64-gce110.tar.gz](https://storage.googleapis.com/freebsd-buidlet-images/freebsd-amd64-gce110.tar.gz) should be done in the morning.

Seeing this on the serial console:
```
2017/02/22 23:41:48 buildlet starting.
2017/02/22 23:41:48 Not remounting root filesystem due to missing buildlet-host-type metadata.
2017/02/22 23:41:48 Will listen on :80
2017/02/22 23:41:48 Adjusted MTU.
2017/02/22 23:41:48 Listening on :80 ...
```
what should buildlet-host-type be set to? 

curl -v looks ok:
```
> GET / HTTP/1.1
> Host: 104.196.217.58
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 22 Feb 2017 23:43:28 GMT
< Content-Length: 34
< Content-Type: text/plain; charset=utf-8
< 
buildlet running on freebsd-amd64
```

**Comment by bradfitz** [comment]
I will rebuild the images once the CL is submitted. If you got that far, it looks like they worked.

**Comment by bradfitz** [comment]
Okay, this is now deployed: https://go-review.googlesource.com/37498
