### ISSUE TITLE
A nil assignment is not nil

### ISSUE THREAD

**Issue by corebreaker** [golang/go#19099]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\dev\go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
https://play.golang.org/p/ED-KGiUhHs

### What did you expect to see?
It prints: "false"

### What did you see instead?
It should print: "true", cause the `z` variable is nil.
By reflect package, it says that `z` is nil (https://play.golang.org/p/k_BlHfNXhp).

**Comment by griesemer** [comment]
Working as intended. The interface contains a pair (type, value) and while the value of type *int is nil, the type is present. So the interface is not nil.

**Comment by ianlancetaylor** [comment]
https://golang.org/doc/faq#nil_error

**Comment by griesemer** [comment]
Also relevant: https://groups.google.com/forum/#!topic/golang-nuts/wnH302gBa4I/discussion
