### ISSUE TITLE
net/http: use of Write method on Request/Response/Header is confusing

### ISSUE THREAD

**Issue by mvdan** [golang/go#19104]
I think the choice of `Write` as the method name for writing to an `io.Writer` in wire format is poor. `Write` is a well known method name coming from the `io.Writer` interface, so it can be confused with it.

But worse than that, while `Write([]byte) error` modifies the receiver, `Write(io.Writer) error` modifies the argument.

I understand that the signatures are different, but if I'm quickly reading code I want to be able to understand what's going on without keeping track of types and signtures. Right now, if I see this line, it's very hard to know which of the two it is without reading more code and some light investigation:

    r.Write(buf)

I think a better name would be `WriteTo` or `WriteToWire`. Suggestions welcome.

This can't be done in Go 1.x, so marking as Go2.

**Comment by mvdan** [comment]
@bradfitz reason behind closing?

**Comment by bradfitz** [comment]
Because it's Go2. We know where to find Go2 stuff later. We won't be searching for "is:open label:Go2" later.

I also don't want to encourage people to file Go2 bugs about everything they don't like. Hidden away is fine.
