### ISSUE TITLE
net/url: Parsing malformed URL does not result in error

### ISSUE THREAD

**Issue by lewisporter** [golang/go#19110]
### What version of Go are you using (`go version`)?

`go version go1.7.5 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

### What did you do?

https://play.golang.org/p/qcpF1Vz3sY

### What did you expect to see?

I expected the call to `url.Parse()` to raise an error. Otherwise, I would expect `testURL.Query()` to return an error, if the function signature allowed it.

### What did you see instead?

`testURL.Query()` silently drops malformed query parameters and `url.Parse()` raises no error.

**Comment by bradfitz** [comment]
I'm pretty sure this is working as intended.

The format of a URL is more permissive than the conventional formatting of key=value&key=value query args.

**Comment by lewisporter** [comment]
@bradfitz That makes sense - but then, shouldn't `testURL.Query()` be able to raise an error?

**Comment by bradfitz** [comment]
Looks intentional:

```go
func (u *URL) Query() Values {
	v, _ := ParseQuery(u.RawQuery)
	return v
}
```

And we can't change the signature at this point due to go1compat.

I suppose we could add a couple words of documentation to that method.
