### ISSUE TITLE
cmd/go: roll back StaleReason CL

### ISSUE THREAD

**Issue by rsc** [golang/go#19116]
CL https://go-review.googlesource.com/#/c/36944/ is for debugging the builders. It should be rolled back when done to avoid an API change.

**Comment by bradfitz** [comment]
Also https://go-review.googlesource.com/c/37332/ which didn't reference a bug.
/cc @laboger

**Comment by bradfitz** [comment]
Issue being debugged is #19062

**Comment by laboger** [comment]
I can roll back the StaleReason change and the crash_test.go change when we get this figured out.

**Comment by rsc** [comment]
Yes, no rush. I filed the bug so we wouldn't forget, but there's lots of time.
