### ISSUE TITLE
cmd/compile: Use SDIV and UDIV for ARM

### ISSUE THREAD

**Issue by benshi001** [golang/go#19118]
The UDIV and SDIV instructions are optional on ARM, so arm gcc generates __armeabi_udiv(a, b) for a/b by default, but it also emits "udiv a, b" while -march=armv7ve is specified.

Golang should also allow user to choose hardware or software division. Maybe by adding a GOARMHDIV environment variable?

**Comment by minux** [comment]
our division routine is very efficient, last time I benchmarked, it's even
faster than glibc's.
how much faster is the native div instruction?

I don't think we should add a new environment variable though. We can make
the div routine use the instruction automatically if the machine supports
it.

**Comment by benshi001** [comment]
A hardware divider is usually much faster than a software one.  However, there is no proper way to let the div routine decide in runtime.

1. A register of ARM shows whether hardware dividers are integrated. And this register is only accessible in PL1, while normal linux programs run in PL0.   
2.A PL0 program can read /proc/cpuinfo for "idiva idivt" flags, but a div routine should not involve a file operation.

**Comment by benshi001** [comment]
There is no proper way to let the div routine decide in runtime. Unless the user specifies it explicitly.

**Comment by randall77** [comment]
It is easy enough to check /proc/cpuinfo once on startup and cache the result.

**Comment by benshi001** [comment]
Check /proc/cpuinfo for "idiva" flag on startup might be a way, how are the core  developers' opinion?

**Comment by cherrymui** [comment]
Checking on startup sounds good to me.

**Comment by minux** [comment]
There are multiple ways to detect DIV instruction at runtime.

1. we can issue it and see if we get SIGILL,
2. we can use HWCAP auxv on Linux.

**Comment by benshi001** [comment]
I would vote for call getauxval() / AT_HWCAP at startup.

**Comment by davecheney** [comment]
Seconded, AT_HWCAP is useful for this.

**Comment by benshi001** [comment]
I have implemented this feature. 
https://go-review.googlesource.com/#/c/37496/

A rough test shows the performance improves 40-50%.

**Comment by benshi001** [comment]
For a rough test case

package main

import "fmt"
import "math/rand"
import "time"

func main() {
	var c, g int
	var a [70000000]uint32
	var b [70000000]uint32
	var d [70000000]uint32

	r := rand.New(rand.NewSource(time.Now().UnixNano()))

	for c = 0; c < cap(b); c++ {
		a[c] = uint32(r.Intn(0x7ffffff0))
		b[c] = uint32(r.Intn(0x3ffffff0))
	}

	for g = 0; g < 10; g++ {
		k := time.Now()
		for c = 0; c < cap(b); c++ {
			d[c] = a[c] / b[c]
		}
		w := time.Now()
		fmt.Println(w.Sub(k))
	}
}

The hardware divider outputs
5.4371964s
4.209324055s
4.205575531s
4.205909284s
4.205245892s
4.218614714s
4.210164271s
4.205585791s
4.205325164s
4.207941386s

And the software divider outputs
8.238922377s
5.943205893s
5.911372837s
5.914151872s
5.909159482s
5.933686273s
5.909419953s
5.90930063s
5.913579159s
5.909221097s

**Comment by benshi001** [comment]
How do we proceed in CL 37496? Keep the simulated DIV/DIVU/MOD/MODU, or remove them?

**Comment by benshi001** [comment]
In patch set 14 of CL 37496,
1. rebased to the newest master branch 
2. keep old DIV/DIVU/MOD/MODU while add DIVHW/DIVUHW

**Comment by benshi001** [comment]
Any conclusion for this issue? Whether keep simulated div/mod or not?
