### ISSUE TITLE
runtime/race: TestOutput flake on linux-amd64-race

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19115]
runtime/race.TestOutput flaked on the linux-amd64-race trybot for golang.org/cl/37102: https://storage.googleapis.com/go-build-log/a6236839/linux-amd64-race_6bbdcdcb.log

I don't see any similar issues previously reported.

    --- FAIL: TestOutput (25.32s)
    	output_test.go:66: failed test case external_cgo_thread, expect:
    		==================
    		WARNING: DATA RACE
    		Read at 0x[0-9,a-f]+ by main goroutine:
    		  main\.main\(\)
    		      .*/main\.go:34 \+0x[0-9,a-f]+
    		
    		Previous write at 0x[0-9,a-f]+ by goroutine [0-9]:
    		  main\.goCallback\(\)
    		      .*/main\.go:27 \+0x[0-9,a-f]+
    		  main._cgoexpwrap_[0-9a-z]+_goCallback\(\)
    		      .*/_cgo_gotypes\.go:[0-9]+ \+0x[0-9,a-f]+
    		
    		Goroutine [0-9] \(running\) created at:
    		  runtime\.newextram\(\)
    		      .*/runtime/proc.go:[0-9]+ \+0x[0-9,a-f]+
    		==================
    		got:
    
    NoRaceAtomicAddInt64                     .
    RaceAtomicAddInt64                       .
    NoRaceAtomicAddInt32                     .
    [...]
    NoRaceWaitGroupReuse2                    .
    RaceWaitGroupReuse                       .
    NoRaceWaitGroupConcurrentAdd             .
    
    Passed 347 of 347 tests (100.00%, 0+, 0-)
    0 expected failures (0 has not fail)
    FAIL
    FAIL	runtime/race	62.794s

/cc @dvyukov

**Comment by dvyukov** [comment]
dup of #14119
