### ISSUE TITLE
os/exec: tests doesn't build on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#19114]
Since CL [36800](https://golang.org/cl/36800), the os/exec tests doesn't build anymore on Plan 9.
It happens because poll.PollDescriptor is not defined on Plan 9.

```
# os/exec_test
go/src/os/exec/exec_test.go:380: undefined: poll.PollDescriptor
go/src/os/exec/exec_test.go:740: undefined: poll.PollDescriptor
FAIL	os/exec [build failed]
```

See https://build.golang.org/log/8dad14ea8ba744cda507490c6267a7665c6021d7

**Comment by ianlancetaylor** [comment]
CL 37106.
