### ISSUE TITLE
x/sys/unix: missing vmsplice on Linux

### ISSUE THREAD

**Issue by mdlayher** [golang/go#19125]
I'm doing some experiments and wanted to try out the `vmsplice` system call on Linux.  `unix.Splice` already exists, but it appears that there is no `unix.Vmsplice`.

A cursory search reveals it in the "unimplemented" section of `syscall_linux.go`.

I implemented it myself, and I'd like to send a CL, unless there is an explicit reason this system call (and others) are not implemented in `x/sys/unix`.

**Comment by ianlancetaylor** [comment]
Sure, send a CL.  Thanks.
