### ISSUE TITLE
Why the global variables are simply recorded in the compiled binary?

### ISSUE THREAD

**Issue by dongweigogo** [golang/go#19121]
go1.7, linux amd64

I set global variables for the username and the password. 
var user="AnyUserIsOk"  

var passwd="AnyWordIsOk"  

func main() {  

    ...  

}
When I compiled the code, the two strings appear in the binary file. 

Value addr= code= ctxt: curg= m->p= p->m= varp=, not 390625<-chanGOROOTSCHED SignalString[]byte    typeschan<-efenceerrno etypeshangupkilled[AnyUserIsOk]()objectsignalsinglestatusstringstructsweep systemuint16uint32uint64 (scan  (scan) MB in  Value> dying= locks= m->g0= nfree= s=nil
(PANIC=, goid=, sys: 19531259765625[AnyWordIsOk]()ChanDirGODEBUGSignal  defer   value=abortedcs     float32float64fs     gctracego1.7.4gs     invalidpanic: r10    r11    r12    r13    r14    r15    r8     r9     rax    rbp    rbx    rcx    rdi    rdx    reflectrflags rip    rsi    rsp    runningruntimesignal stoppedsyscalluintptrunknownwaiting goalÎ<94>= helpgc= is not  mcount= minutes nalloc= newval= nfreed= packed= pointer stack=[, found , idle: 48828125NumFieldZONEINFO[signal

I think that is not good, at least not safe. Is there anyway to avoid this recording behavior?

**Comment by ALTree** [comment]
> Is there anyway to avoid this recording behavior?

Yes: don't put secrets in the source code of your program.

**Comment by ALTree** [comment]
If you have further questions, please ask in one of the places listed here: https://github.com/golang/go/wiki/Questions; we only use the issue tracker for bugs and proposal.
