### ISSUE TITLE
cmd/go: go1.8 release binaries for linux_amd64 error when building test dependencies with race mode enabled.

### ISSUE THREAD

**Issue by heavenlyhash** [golang/go#19133]
In the 1.8 binary releases for linux, `go test -i -race` tries to re-build some packages from the standard library.  If your go install is not writable, it will error trying to open the `$pkg.a` files for writing.

### What version of Go are you using (`go version`)?

Today's release: `go version go1.8 linux/amd64`
Specifically, the binary release from: `https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz`
Sha384sum: `5cf34c2335341febb707008ede937729c5cf09f66c98e11065ecc58f945fc7d95e1ed10c1d8de765591de5cf20c16457  go1.8.linux-amd64.tar.gz`

### What operating system and processor architecture are you using (`go env`)?

linux_amd64

### What did you do?

Given a `reproducer_test.go` file:

```
package main

import "testing"

func Test(t *testing.T) {
	_ = 1
}
```
I run `go test in several different modes:

- `go test ./...` -- passes
- `go test -race ./...` -- passes
- `go test -i ./...` -- passes
- `go test -i -race ./...` -- FAILS

Go was installed by untar'ing the binary release.  All of its uids are 0; all of its mtimes are as given by the tar headers.
The tarball is extracted in `/installpath`, and `export GOROOT=/installpath/go` applied to the environment.
(Identical steps have been used to install a go1.7 binary release, which does not exhibit the problem.)

### What did you expect to see?

All four of these test commands should pass.  (All four commands work correctly on go1.7.)

### What did you see instead?

Test with `-i` and `-race`-mode gives the following error output:

```
go install internal/race: open /installpath/go/pkg/linux_amd64_race/internal/race.a: permission denied
go install errors: open /installpath/go/pkg/linux_amd64_race/errors.a: permission denied
go install unicode/utf8: open /installpath/go/pkg/linux_amd64_race/unicode/utf8.a: permission denied
go install unicode: open /installpath/go/pkg/linux_amd64_race/unicode.a: permission denied
go install math: open /installpath/go/pkg/linux_amd64_race/math.a: permission denied
```

and exits with a 1.

### Other notes

When encountering this on less minimal code, I've seen several other packages also listed as offenders, such as `crypto/subtle` for example.  The five listed above are what comes up with the minimal reproducer -- these five packages are dependencies of the `testing` package.

I thought perhaps this might be an issue from timestamps on the `.a` files being older than the relevant source files (I've made a mistake with an rsync command before that fubar'd that, and paid silly increases in compile time until I noticed and fixed it), but that doesn't appear to be the case, so I'm not sure what's going on here.

**Comment by amenzhinsky** [comment]
I added some debugging output what information is used to compute buildid to [computeBuildID](https://github.com/golang/go/blob/master/src/cmd/go/internal/load/pkg.go#L1633) function.

Here's what I got for the `errors` package:

```
$ go install -race errors

file errors.go
dep runtime 51c69445d7efe3df820352baa6e4847b749c7037
dep runtime/internal/atomic 812fcbb3b315b02f834932ddf0d767f87b435f38
dep runtime/internal/sys 9cd53b64a63f6fbdb1d94744178e63dcd846ffbc
dep unsafe f9f879f0869e26eb4f48b13b985c465e319e98ca
```

```
$ go test -race -i .

file errors.go
dep runtime 51c69445d7efe3df820352baa6e4847b749c7037
dep runtime/cgo ccefa1650c1e717f94656472e31519e1a5164a6d
dep runtime/internal/atomic 812fcbb3b315b02f834932ddf0d767f87b435f38
dep runtime/internal/sys 9cd53b64a63f6fbdb1d94744178e63dcd846ffbc
dep runtime/race 7e0d0b64d9bf634ad3b87c3668ad5f17a27dddb6
dep sync/atomic 0f3c254882f4f232509cf79b199b7f4449b0f54a
dep unsafe f9f879f0869e26eb4f48b13b985c465e319e98ca
```

**Comment by amenzhinsky** [comment]
Seems like it's caused by the default value of `-covermode` when `-race` is set 
https://github.com/golang/go/blob/master/src/cmd/go/internal/test/testflag.go#L198

And it affects package dependencies list:
https://github.com/golang/go/blob/master/src/cmd/go/internal/load/pkg.go#L963
