### ISSUE TITLE
cmd/godoc: var anchors are misplaced

### ISSUE THREAD

**Issue by bjkail** [golang/go#19136]
### What did you do?

Visited https://golang.org/pkg/context/#DeadlineExceeded from the Go 1.8 release notes.

### What did you expect to see?

A link to a description of the variable.

### What did you see instead?

A link to the declaration only (the description is scrolled off the screen).

**Comment by bradfitz** [comment]
This isn't a regression from Go 1.7, is it?

**Comment by bjkail** [comment]
I don't know, sorry.

**Comment by kevinburke** [comment]
Reading through the commit history I would be really surprised if this is a regression. Code that adds the `<span id` fields is in addStructFieldIDAttributes in x/tools/godoc/godoc.go. That needs to move to the `<p id>` field if and only if the exported variable has a docstring.

**Comment by dlespiau** [comment]
Seems like a duplicate has been filed and good progress made there: https://github.com/golang/go/issues/19894

**Comment by bradfitz** [comment]
@dlespiau, thanks. I'll close this one, even though it's older.
