### ISSUE TITLE
triage: go 1.8 cgo crash (lacking details)

### ISSUE THREAD

**Issue by toplinuxsir** [golang/go#19134]
runtime stack:
runtime.throw(0xbc6be4, 0x2a)
/home/lhs/soft/go/go1.8.0/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
/home/lhs/soft/go/go1.8.0/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 4 [syscall, locked to thread]:
runtime.cgocall(0xa50d60, 0xc42002d6c8, 0xbc5a59)
/home/lhs/soft/go/go1.8.0/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42002d688 sp=0xc42002d648
github.com/mattn/go-oci8._Cfunc_OCIHandleFree(0x1b2ebc8, 0x4, 0x0)
github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:479 +0x4d fp=0xc42002d6c8 sp=0xc42002d688
github.com/mattn/go-oci8.(*OCI8Stmt).Close.func1(0x1b2ebc8, 0xc400000004, 0x43155e)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/mattn/go-oci8/oci8.go:755 +0x68 fp=0xc42002d700 sp=0xc42002d6c8
github.com/mattn/go-oci8.(*OCI8Stmt).Close(0xc420163ef0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/mattn/go-oci8/oci8.go:759 +0x47 fp=0xc42002d728 sp=0xc42002d700
runtime.call32(0x0, 0xbd9aa8, 0xc420218000, 0x2000000020)
/home/lhs/soft/go/go1.8.0/go/src/runtime/asm_amd64.s:514 +0x48 fp=0xc42002d758 sp=0xc42002d728
runtime.runfinq()
/home/lhs/soft/go/go1.8.0/go/src/runtime/mfinal.go:208 +0x205 fp=0xc42002d7e0 sp=0xc42002d758
runtime.goexit()
/home/lhs/soft/go/go1.8.0/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42002d7e8 sp=0xc42002d7e0
created by runtime.createfing
/home/lhs/soft/go/go1.8.0/go/src/runtime/mfinal.go:142 +0x62

goroutine 1 [chan receive, 4 minutes]:
github.com/astaxie/beego.(*App).Run(0xc420011fc0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/app.go:186 +0x597
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/beego.go:67 +0x51
main.main()
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/main.go:31 +0x2f3

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
/home/lhs/soft/go/go1.8.0/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
/home/lhs/soft/go/go1.8.0/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
/home/lhs/soft/go/go1.8.0/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
/home/lhs/soft/go/go1.8.0/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc42012a0a0)
/home/lhs/soft/go/go1.8.0/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
/home/lhs/soft/go/go1.8.0/go/src/database/sql/sql.go:582 +0x212

goroutine 63 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c1c70, 0x72, 0xd)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201dd488, 0x72, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201dd488, 0xc420408000, 0x1000)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201dd420, 0xc420408000, 0x1000, 0x1000, 0x0, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4201e8010, 0xc420408000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
bufio.(*Reader).fill(0xc420192180)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc420192180, 0x1, 0xc40dded922, 0x111aca0, 0x0, 0x0, 0xc42004d950)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:129 +0x67
github.com/jackc/pgx.(*Conn).waitForNotification(0xc420206c00, 0xed0384062, 0xdded922, 0x111aca0, 0x1, 0x10e8700, 0xc42016dbf0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:833 +0x81
github.com/jackc/pgx.(*Conn).WaitForNotification(0xc420206c00, 0x3b9aca00, 0x10e8700, 0xc42016dbf0, 0xc42016db01)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:808 +0x342
jitsys/controllers.Listen(0xc4201684b0)
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:148 +0x1f3
created by jitsys/controllers.init.4
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:26 +0xa8

goroutine 61 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c1df0, 0x72, 0xb)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201dd418, 0x72, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201dd418, 0xc42024c000, 0x1000)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201dd3b0, 0xc42024c000, 0x1000, 0x1000, 0x0, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420246000, 0xc42024c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
bufio.(*Reader).fill(0xc42024a000)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc42024a000, 0x1, 0xc42a0e8c42, 0x111aca0, 0x0, 0x0, 0xc42004b950)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:129 +0x67
github.com/jackc/pgx.(*Conn).waitForNotification(0xc420206600, 0xed0384062, 0x2a0e8c42, 0x111aca0, 0x1, 0x10e8700, 0xc42016dbf0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:833 +0x81
github.com/jackc/pgx.(*Conn).WaitForNotification(0xc420206600, 0x3b9aca00, 0x10e8700, 0xc42016dbf0, 0xc42016db01)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:808 +0x342
jitsys/controllers.Listen(0xc4201682d0)
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:148 +0x1f3
created by jitsys/controllers.init.4
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:26 +0xa8

goroutine 62 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c1d30, 0x72, 0xc)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201de618, 0x72, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201de618, 0xc42024d000, 0x1000)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201de5b0, 0xc42024d000, 0x1000, 0x1000, 0x0, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4201e8000, 0xc42024d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
bufio.(*Reader).fill(0xc420192120)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc420192120, 0x1, 0xc412237f4a, 0x111aca0, 0x0, 0x0, 0xc420233950)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:129 +0x67
github.com/jackc/pgx.(*Conn).waitForNotification(0xc420236000, 0xed0384062, 0x12237f4a, 0x111aca0, 0x1, 0x10e8700, 0xc42016dbf0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:833 +0x81
github.com/jackc/pgx.(*Conn).WaitForNotification(0xc420236000, 0x3b9aca00, 0x10e8700, 0xc42016dbf0, 0xc42016db01)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/jackc/pgx/conn.go:808 +0x342
jitsys/controllers.Listen(0xc4201683c0)
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:148 +0x1f3
created by jitsys/controllers.init.4
/home/lhs/soft/go/go1.8.0/gopath/src/jitsys/controllers/pgsql_listen.go:26 +0xa8

goroutine 64 [chan receive, 4 minutes]:
github.com/astaxie/beego/logs.(*fileLogWriter).dailyRotate(0xc4200cd380, 0xed0383f59, 0x26571e07, 0x111aca0)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/logs/file.go:197 +0x17b
created by github.com/astaxie/beego/logs.(*fileLogWriter).initFd
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/logs/file.go:180 +0x208

goroutine 48 [select, 4 minutes]:
github.com/astaxie/beego/toolbox.run()
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/toolbox/task.go:417 +0x53b
created by github.com/astaxie/beego/toolbox.StartTask
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/toolbox/task.go:397 +0x51

goroutine 76 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fd1f67c1af0, 0x72, 0x10eb5c0)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42005b4f8, 0x72, 0x10e68c0, 0xc4200bdbe0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42005b4f8, 0xffffffffffffffff, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42005b490, 0x0, 0x10e99c0, 0xc4200bdbe0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc4202462b8, 0xc4200f6ed0, 0xc42003bd30, 0x57013d)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4202462b8, 0x69aea3, 0xc42003bd48, 0xc42003bd40)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4202462b8, 0xc4200f6ea0, 0xae01e0, 0x10d8230, 0xb3d800)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc42001e4d0, 0x10f11c0, 0xc4202462b8, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc42001e4d0, 0xc42001e4d0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0xc42028acf8, 0x5, 0x0, 0x0, 0x1, 0xc42028acf8)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2787 +0x7f
github.com/astaxie/beego.(*adminApp).Run(0xc42000e148)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/admin.go:396 +0x422
created by github.com/astaxie/beego.registerAdmin
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/hooks.go:86 +0x6f

goroutine 77 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fd1f67c1a30, 0x72, 0x10eb5c0)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42005b648, 0x72, 0x10e68c0, 0xc4201251c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42005b648, 0xffffffffffffffff, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42005b5e0, 0x0, 0x10e99c0, 0xc4201251c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc4202462d0, 0x7fd1f67fd000, 0x0, 0x42e72f)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4202462d0, 0x458501, 0xc4200f7530, 0xc420407d20)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4202462d0, 0x42e1ee, 0xc4200f7530, 0xae01e0, 0x10d8230)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:3044 +0x2f
crypto/tls.(*listener).Accept(0xc4201251a0, 0xc4200f7500, 0xae01e0, 0x10d8230, 0xb3d800)
/home/lhs/soft/go/go1.8.0/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc42001f290, 0x10efa80, 0xc4201251a0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServeTLS(0xc42001f290, 0xc420124200, 0x1c, 0xc420124220, 0x1d, 0xc42028ad70, 0x6)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2870 +0x31b
github.com/astaxie/beego.(*App).Run.func3(0xc420011fc0, 0xc42005b180)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/app.go:152 +0x157
created by github.com/astaxie/beego.(*App).Run
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/app.go:157 +0x60b

goroutine 78 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c1bb0, 0x72, 0x10eb5c0)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42005b2c8, 0x72, 0x10e68c0, 0xc420257220)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42005b2c8, 0xffffffffffffffff, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42005b260, 0x0, 0x10e99c0, 0xc420257220)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc4202462b0, 0xc42008c760, 0xadb320, 0xffffffffffffffff)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4202462b0, 0xc420041df8, 0xc420041e00, 0xc420041df0)
/home/lhs/soft/go/go1.8.0/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4202462b0, 0xbda7b0, 0xc42008c6e0, 0x10f1840, 0xc4200f6d20)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc42001f290, 0x10f11c0, 0xc4202462b0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc42001f290, 0xc42028aca0, 0xc4200297a0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2585 +0xb0
github.com/astaxie/beego.(*App).Run.func4(0xc420011fc0, 0xc42028ac68, 0x5, 0xc42005b180)
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/app.go:178 +0x393
created by github.com/astaxie/beego.(*App).Run
/home/lhs/soft/go/go1.8.0/gopath/src/github.com/astaxie/beego/app.go:184 +0x5e2

goroutine 304 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c1970, 0x72, 0x12)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42043c768, 0x72, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42043c768, 0xc420409000, 0x1000)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42043c700, 0xc420409000, 0x1000, 0x1000, 0x0, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420246298, 0xc420409000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc4201898c0, 0xc420409000, 0x1000, 0x1000, 0x2c0, 0xb459c0, 0xc4200110dc)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42024b6e0)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42024b6e0, 0xc4204c480a, 0xc4203f7040, 0xbdaf28, 0xc420162a50, 0x203659c0, 0xc420365a28)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42024b6e0, 0xc42044c700, 0x100, 0xf8, 0xb91fe0, 0xc4204c4840, 0x7fd1f67fde10)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc4202d8360, 0xc420365ac8, 0xc420365ac8, 0x4148f8, 0x100, 0xb91fe0)
/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc4202d8360, 0xc42044c700, 0x72, 0x8000000000000000, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc42024b6e0, 0x0, 0xc42044c700, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc4201cc280, 0x10f1780, 0xc420189880, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc4201cc280, 0x10f1780, 0xc420189880)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2668 +0x2ce

goroutine 522 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd1f67c18b0, 0x72, 0x11)
/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4203a08b8, 0x72, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4203a08b8, 0xc420418000, 0x1000)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4203a0850, 0xc420418000, 0x1000, 0x1000, 0x0, 0x10eb5c0, 0x10e68c0)
/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4202080e8, 0xc420418000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc420241c80, 0xc420418000, 0x1000, 0x1000, 0x0, 0x2, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc4201d5ec0)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc4201d5ec0, 0xa, 0x2, 0x0, 0x538237, 0xc420419094, 0x10e64a8)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc4201d5ec0, 0xc42033a400, 0x100, 0xf8, 0xb91fe0, 0xc420265600, 0xb78400)
/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc42018a0c0, 0xc420369ac8, 0xc420369ac8, 0x4148f8, 0x100, 0xb91fe0)
/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc42018a0c0, 0xc42033a400, 0x72, 0x8000000000000000, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc4201d5ec0, 0x0, 0xc42033a400, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc4205e43c0, 0x10f1780, 0xc420241c40, 0x0, 0x0, 0x0)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc4205e43c0, 0x10f1780, 0xc420241c40)
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
/home/lhs/soft/go/go1.8.0/go/src/net/http/server.go:2668 +0x2ce
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by bradfitz** [comment]
You didn't complete the bug template.

How can we reproduce this?

Which platform? linux/amd64 it looks like?

Where's the code?

Have you run with the race detector?

**Comment by ianlancetaylor** [comment]
You left out the most important part of the dump report, which is the part before the stack trace.

**Comment by bradfitz** [comment]
@mattn, does your cgo driver play by the rules?

**Comment by toplinuxsir** [comment]
What version of Go are you using (go version)?

Go 1.8.0 

What operating system and processor architecture are you using (go env)?

GOARCH="amd64"
GOBIN="/home/lhs/soft/go/go1.8.0/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lhs/soft/go/go1.8.0/gopath"
GORACE=""
GOROOT="/home/lhs/soft/go/go1.8.0/go"
GOTOOLDIR="/home/lhs/soft/go/go1.8.0/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072704070=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1

What did you do?

Use go-oci8 drive to query from oracle database 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

What did you expect to see?

What did you see instead?

**Comment by mattn** [comment]
@toplinuxsir you still not reply for trying to update go-oci8. And probably, this is not an issue of go.

https://github.com/mattn/go-oci8/issues/140

@bradfitz yes, already support context feature.

**Comment by toplinuxsir** [comment]
After i update vi cmd go get -u,
The problem stil exist

**Comment by mattn** [comment]
Please post comments to the issue of go-oci8 until we figure out that this is an issue of go.
