### ISSUE TITLE
cmd/compile: unable to compile a program on arm64 with 1.8 that compiles/runs fine on 1.7.5

### ISSUE THREAD

**Issue by jolan** [golang/go#19137]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8 linux/arm64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jolan/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build063485784=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

```
git clone https://github.com/decred/dcrd $GOPATH/src/github.com/decred/dcrd
cd $GOPATH/src/github.com/decred/dcrd
glide install
go install $(glide nv)
```

### What did you expect to see?

No compile errors (works with go 1.7.5)

### What did you see instead?

```
$ go install $(glide nv)
# github.com/decred/dcrd/blockchain/chaingen
blockchain/chaingen/generator.go:1861: offset out of range: 974
01460 (/home/jolan/go/src/github.com/decred/dcrd/blockchain/chaingen/generator.go:1595) MOVW    R2, ""..autotmp_529-146(SP)
# github.com/decred/dcrd
./version.go:74: offset out of range: 4302
16640 (/home/jolan/go/src/github.com/decred/dcrd/mining.go:2133)        MOVW   R1, ""..autotmp_2903-434(SP)
```

**Comment by josharian** [comment]
cc @cherrymui

**Comment by karalabe** [comment]
This error is happening on our systems too: https://travis-ci.org/ethereum/go-ethereum/jobs/202566418#L2526

Note, previously we used Go 1.8 RC3 and that worked flawlessly.

**Comment by karalabe** [comment]
Here's a repro for Ethereum on Ubuntu. It needs ARM64 C compilers so it may be a bit more involved, but figured a proper bug report should have the repro nontheless.

First up if you don't have the C compilers, install them:

```
$ sudo apt-get update
$ sudo apt-get install gcc-5-aarch64-linux-gnu g++-5-aarch64-linux-gnu libc6-dev-arm64-cross
```

The you can check out the source and watch it fail:

```
$ git clone https://github.com/ethereum/go-ethereum $GOPATH/src/github.com/ethereum/go-ethereum
$ cd $GOPATH/src/github.com/ethereum/go-ethereum/contracts/chequebook
$ CGO_ENABLED=1 GOARCH=arm64 CC=aarch64-linux-gnu-gcc-5 go build -v

[...]
# github.com/ethereum/go-ethereum/contracts/chequebook
./cheque.go:643: offset out of range: 364
00508 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:470)	MOVD	"".beneficiary+36(FP), R1
./cheque.go:643: offset out of range: 356
00512 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:470)	MOVD	"".beneficiary+28(FP), R2
./cheque.go:643: offset out of range: 564
00148 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:591)	MOVD	"".beneficiary+44(FP), R1
./cheque.go:643: offset out of range: 556
00152 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:591)	MOVD	"".beneficiary+36(FP), R2
./cheque.go:643: offset out of range: 556
00576 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:606)	MOVD	"".beneficiary+36(FP), R1
./cheque.go:643: offset out of range: 564
00580 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:606)	MOVD	"".beneficiary+44(FP), R2
./cheque.go:643: offset out of range: 564
01676 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:592)	MOVD	"".beneficiary+44(FP), R0
./cheque.go:643: offset out of range: 556
01680 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:592)	MOVD	"".beneficiary+36(FP), R1
```

```
$ go version
go version go1.8 linux/amd64
```

**Comment by cherrymui** [comment]
I think I know what's the problem, at least for the original post. It's Zero/Move lowering to unaligned stores. Will send a fix.

**Comment by cherrymui** [comment]
No, the Zero/Move rules are ok. It is the folding rules that have bad interaction with them.

**Comment by cherrymui** [comment]
With CL https://go-review.googlesource.com/c/37145/, @jolan's code can be built successfully.
@karalabe, could you try the patch? Right now I don't have a C cross-compiler on hand.

**Comment by karalabe** [comment]
Thanks! Will try in a few hours.

**Comment by cherrymui** [comment]
reopen for cherry-pick to Go 1.8 release branch.

**Comment by karalabe** [comment]
@cherrymui I cherry picked https://go-review.googlesource.com/37145 on top of the Go 1.8 release, rebuilt and tried compiling my code. It still fails with the exact same errors as reported in my posts above.

**Comment by karalabe** [comment]
@cherrymui Hey, so we've merged in a commit to allow building our code (at least this failing part) without CGO too, relying on a fallback package. It still exhibits the same error so you can try it without a C compiler too.

```
$ git clone https://github.com/ethereum/go-ethereum $GOPATH/src/github.com/ethereum/go-ethereum
$ golang.org/x/net/context
$ cd $GOPATH/src/github.com/ethereum/go-ethereum/contracts/chequebook
$ GOARCH=arm64 go build --tags=nocgo -v

[...]
# github.com/ethereum/go-ethereum/contracts/chequebook
./cheque.go:643: offset out of range: 364
00508 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:470)	MOVD	"".beneficiary+36(FP), R1
./cheque.go:643: offset out of range: 356
00512 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:470)	MOVD	"".beneficiary+28(FP), R2
./cheque.go:643: offset out of range: 564
00148 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:591)	MOVD	"".beneficiary+44(FP), R1
./cheque.go:643: offset out of range: 556
00152 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:591)	MOVD	"".beneficiary+36(FP), R2
./cheque.go:643: offset out of range: 556
00576 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:606)	MOVD	"".beneficiary+36(FP), R1
./cheque.go:643: offset out of range: 564
00580 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:606)	MOVD	"".beneficiary+44(FP), R2
./cheque.go:643: offset out of range: 564
01676 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:592)	MOVD	"".beneficiary+44(FP), R0
./cheque.go:643: offset out of range: 556
01680 (/tmp/src/github.com/ethereum/go-ethereum/contracts/chequebook/cheque.go:592)	MOVD	"".beneficiary+36(FP), R1
```

**Comment by cherrymui** [comment]
@karalabe thanks. Yeah, I found the problem. It's a different problem. Will have a fix later today.

**Comment by cherrymui** [comment]
reopen for fixing Go 1.8.

**Comment by aclements** [comment]
I'm pretty sure this is fixed on the release branch now. @cherrymui, please reopen if I misunderstood the cherry-picks.
