### ISSUE TITLE
sync: save 4 bytes memory allocation in WaitGroup struct

### ISSUE THREAD

**Issue by go101** [golang/go#19149]
The WaitGroup struct uses a field, state1, a byte array which length is 12 to assure WaitGroup.state() returns a 64-bit aligned pointer. There are 4 bytes wasted by using this trick.
It may be a good idea to use the 4 wasted bytes for the sema field.

Now:

	type WaitGroup struct {
		noCopy noCopy
		state1 [12]byte
		sema   uint32
	}

	func (wg *WaitGroup) state() *uint64 {
		if uintptr(unsafe.Pointer(&wg.state1))%8 == 0 {
			return (*uint64)(unsafe.Pointer(&wg.state1))
		} else {
			return (*uint64)(unsafe.Pointer(&wg.state1[4]))
		}
	}

the saving memory version:

	type WaitGroup struct {
		noCopy noCopy
		state1 [12]byte
	}

	func (wg *WaitGroup) state() *uint64 {
		if uintptr(unsafe.Pointer(&wg.state1))%8 == 0 {
			return (*uint64)(unsafe.Pointer(&wg.state1))
		} else {
			return (*uint64)(unsafe.Pointer(&wg.state1[4]))
		}
	}

	func (wg *WaitGroup) sema() *uint32 {
		if uintptr(unsafe.Pointer(&wg.state1))%8 == 0 {
			return (*uint32)(unsafe.Pointer(&wg.state1[8]))
		} else {
			return (*uint32)(unsafe.Pointer(&wg.state1))
		}
	}

Maybe, merging the two functions as one two-returns function is better.

**Comment by ianlancetaylor** [comment]
See #19057, which would make this idea (which is a good one) unnecessary.

**Comment by minux** [comment]
It won't save any memory because we don't have a 12-byte size class.
Allocating a 12-byte object will fall into the 16-byte size class.

**Comment by bradfitz** [comment]
@minux, what if the sync.WaitGroup were embedded in a larger struct?

**Comment by Go101** [comment]
btw, the trick used in WaitGroup here does indicate that compilers should guarantee the alignment of 64-bit words must be 4N. But I can't find the guarantee in Go specification. Other compilers may not enforce the 4N alignment guarantee. So this trick may make Go programs not portable.

**Comment by rsc** [comment]
The trick here is not valid. Something has to make the waitgroup 4-byte aligned, and that something is the uint32 field.

**Comment by rsc** [comment]
Actually, it would be fine (and clearer) to change the [12]byte into [3]uint32. Then the finding of the sema field doesn't even need to use unsafe (except to determine the alignment).
