### ISSUE TITLE
cmd/compile: too many LEAQ/LEAL instructions on amd64, 386

### ISSUE THREAD

**Issue by rsc** [golang/go#1914]
<pre>More can and should be gotten rid of.
They are making the range loop here less
efficient than the explicit for loop in 8g.
There are some lingering in 6g too, but fewer.

package main

import (
	&quot;fmt&quot;
	&quot;testing&quot;
)

var siz = 1024 * 1024
var buf []byte

func init() {
	buf = make([]byte, siz)
	for i := range buf {
		buf[i] = byte(i &amp; 0xFF)
	}
}

func BenchmarkRange(b *testing.B) {
	n := 0
	for i := 0; i &lt; b.N; i++ {
		for _, c := range buf {
			if c == 0 {
				n++
			}
		}
	}
}

func BenchmarkLoop(b *testing.B) {
	n := 0
	for i := 0; i &lt; b.N; i++ {
		for j := 0; j &lt; len(buf); j++ {
			if buf[j] == 0 {
				n++
			}
		}
	}
}

func main() {
	fmt.Println(testing.Benchmark(BenchmarkRange))
	fmt.Println(testing.Benchmark(BenchmarkLoop))
}</pre>

**Comment by randall77** [comment]
Fixed with the SSA compiler.

**Comment by rsc** [comment]
Hooray!
