### ISSUE TITLE
compile flag to disable 'use of internal package not allowed'

### ISSUE THREAD

**Issue by JavierZunzunegui** [golang/go#19144]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
linux
amd64

### What did you do?
I have a code generating tool which creates a main that imports (almost) all pkgs it inspects. 
This generated code is deliberately ignoring all "internal" boundaries otherwise respected in normal code, running into `imports XXX/internal/XXX: use of internal package not allowed` error when compiling.

I would like to add a flag to the go compile command to disable the "internal" check.

Disabling the use of [disallowInternal](https://github.com/golang/go/blob/2ac32b6360b47e3e5bb87ad8cbc51c3d91467c85/src/cmd/go/internal/load/pkg.go#L591-L594) is enough to stop the issue. 

I currently run a modified go build with this disabled but I imagine others would benefit from having this option - even if normally discouraged.

**Comment by bradfitz** [comment]
Sorry, we're not keen on adding flags to begin with, much less to support behavior that we don't want to encourage.

You clearly need something, but I don't understand your problem enough to suggest what it might be. This feature request sounds like it might be an XY problem (http://xyproblem.info/) Let's understand the problem before we jump to solutions.

The mailing list or slack (see https://golang.org/wiki/Questions) would be a better forum.

**Comment by JavierZunzunegui** [comment]
Thank you - presented my issue in further detail in the [Go Forum](https://forum.golangbridge.org/t/internal-getting-in-the-way-of-generated-code/4636)
