### ISSUE TITLE
encoding/pem: pem.Decode accepts PEM with trailing data

### ISSUE THREAD

**Issue by joeshaw** [golang/go#19147]
If PEM data passed to `pem.Decode()` includes data after the `-----END FOO-----` trailer on the same line, it quietly ignores it.

The fix for the related #16335 took care of too few dashes and of the type not matching, but did not handle extra trailing data (like an extra dash).  OpenSSL's PEM library refuses to open this data.

**Comment by odeke-em** [comment]
From the discussion in https://github.com/golang/go/issues/7042#issuecomment-66089753, seems like fixing this issue will fix that issue too.
