### ISSUE TITLE
x/tools: tests broken after 

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19150]
The x/tools repo tests are broken as of  c05b06a ("os: use poller for file I/O").

https://build.golang.org/?repo=golang.org%2fx%2ftools

@ianlancetaylor, can you look into it?

/cc @jayconrod @alandonovan

**Comment by ianlancetaylor** [comment]
Sorry, didn't check for subrepo breakage.

CL 37148.

**Comment by bradfitz** [comment]
Maybe trybots should certain weirdo tests like that.

But I'd prefer we don't have such weirdo tests.

**Comment by bradfitz** [comment]
Filed #19152

**Comment by ianlancetaylor** [comment]
Come to think of it, that CL is going to break the repo for Go 1.8.  That doesn't sound good.

@alandonovan Should I set that test to only run for 1.9?  It's just examples anyhow.
