### ISSUE TITLE
cmd/go: non-test race libraries are rebuilt by "go test -i -race" and vice-versa

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#19151]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.8 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build041564216=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

```
$ go install -v -race std
[... lots of libraries installed ...]
$ go test -race -i -v std
[... lots of libraries installed ...]
$ go install -v -race std
[... lots of libraries installed ...]
```

### What did you expect to see?
All commands after the first should not need to install anything.

It works correctly without `-race`:

```
$ go install -v std
[... lots of libraries installed ...]
$ go test -i -v std
$ go install -v std
```

### What did you see instead?

Libraries are rebuilt and reinstalled every time the `-race` flag is added or removed.

This is a problem because we ship our compiler with the race libraries prebuilt, install it system-wide where the builders don't have permission to write, and then always run `go test -i -race` before our tests to do incremental compilation of GOPATH packages. That now tries to install stdlib packages and fails.

This is a regression from 1.7.

**Comment by amenzhinsky** [comment]
#19133

**Comment by aclements** [comment]
Re-opening for cherry-pick to 1.8.1

@ianlancetaylor, do you consider this low enough risk for a point release?

**Comment by ianlancetaylor** [comment]
Does this really meet the criterion for a minor release?  It is an unfortunate regression, but it's also fairly easy to avoid using both `-i` and `-race` with `go test`.

**Comment by FiloSottile** [comment]
> but it's also fairly easy to avoid using both `-i` and `-race` with go test

That means no incremental builds for tests, and race builds are slow.

Worse, it means rebuilding the stdlib every time, assuming you used `go install -race` at any point.

**Comment by ianlancetaylor** [comment]
I think that https://golang.org/cl/37598 should be safe enough for the 1.8 release branch.  It will need to be tested, though.  Unfortunately I didn't think of a way to test that CL safely without modifying GOROOT.

**Comment by rsc** [comment]
Sent CL 39592 to add a test that we can cherry-pick at the same time.

**Comment by rsc** [comment]
Cherry-picked.
