### ISSUE TITLE
x/build/cmd/gitmirror: support serving unsubmitted commits

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19166]
The gitmirror should support downloading the *.tar.gz of any commit digest, even if it's not known.

It should just "git fetch" it first.

Then the coordinator could use it even for try runs.

**Comment by bradfitz** [comment]
@kevinburke, this one is probably higher priority than #11224

Right now we never use gitmirror for trybots since the mirror might not have the commit being tested. But that means the coordinator always gets the source from Gerrit, which doesn't support gitattributes at all (the temporary solution already done before #11224), which means the x/talks repo is 113 MB or so, and the limit is 50MB (just upped from 25MB). If we did this, at least we'd get trybots working for the talks repo again.

**Comment by kevinburke** [comment]
OK, I'll take a look
