### ISSUE TITLE
plugin: support Darwin again

### ISSUE THREAD

**Issue by kris-nova** [golang/go#19167]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.8 darwin/amd64`

### What did you do?

Tried to build a binary with `-buildmode=plugin` on Darwin

```
-buildmode=plugin not supported on darwin/amd64
```

### This is a known limitation

As it stands today the `Go` [documentation](https://beta.golang.org/pkg/plugin/) the plugin feature is only advertised on linux. 

> Currently plugins only work on Linux.

I am wondering if we could look at introducing native Darwin functionality for this feature as well? I know @crawshaw has done a lot of work on the existing `plugin` implementation. I also am interested in contributing to the project and wouldn't mind coding this myself (or helping out) if that was at all possible.

Thoughts?

**Comment by bradfitz** [comment]
Actually, dup of #18104

**Comment by kris-nova** [comment]
@bradfitz is this actually a dup of #18104? I noticed your comment https://github.com/golang/go/issues/18104#issuecomment-267375377

I am wondering if that comment suggests working on Darwin support for 1.9? If so I think it's a dup.. but otherwise #18104 looks like another case.

**Comment by bradfitz** [comment]
That was the main bug that prompted us to remove plugin support from darwin at the 11th hour. If/when that's fixed, we can reenable it.

**Comment by wmarbut** [comment]
In the comments for #18104, it is stated that this is fixed at HEAD. I have can confirm that it now works on my OS 10.12.5 machine.
