### ISSUE TITLE
cmd/compile: generic optimizations cannot remove load-hit-store on struct field

### ISSUE THREAD

**Issue by mundaym** [golang/go#19164]
On tip (ddb15cea4a02c403160c2d9772f85c122cbc8248) it looks like there is an opportunity for the generic optimizations to remove a load-hit-store of struct fields. They can't currently because for some reason the types of OffPtr are different for loads and stores. For example:

```go
type t struct {
        v int8
}

//go:noinline
func loadHitStore8(x int8, p *t) int32 {
        p.v = x
        return int32(p.v)
}
```
Compiles to:

```
  b1:
    v1 = InitMem <mem>
    v2 = SP <uintptr>
    v3 = SB <uintptr> DEAD
    v4 = Addr <*int8> {x} v2 DEAD
    v5 = Addr <**t> {p} v2 DEAD
    v6 = Addr <*int32> {~r2} v2
    v7 = Arg <int8> {x}
    v8 = Arg <*t> {p}
    v9 = Const32 <int32> [0] DEAD
    v10 = NilCheck <void> v8 v1
    v11 = OffPtr <*int8> [0] v8 <----------- type = *int8
    v12 = Store <mem> [1] v11 v7 v1
    v13 = NilCheck <void> v8 v12
    v14 = OffPtr <*t> [0] v8 <-------------- type = *t
    v15 = Load <int8> v14 v12
    v16 = SignExt8to32 <int32> v15
    v17 = VarDef <mem> {~r2} v12
    v18 = Store <mem> [4] v6 v16 v17
    Ret v18

```

Since the types of v11 and v14 are different the generic rules can't tell that they are really the same pointer, and so cannot turn v15 into a Copy.

**Comment by randall77** [comment]
Why isn't v14 being rewritten to v8?

(OffPtr <t> [0] x) && x.Type == t -> x

v11 is still a problem.

**Comment by mundaym** [comment]
It is later, this snapshot is before the optimization pass.
