### ISSUE TITLE
proposal: add reverse functionality to sort.Slice

### ISSUE THREAD

**Issue by ston1th** [golang/go#19174]
Hi gophers,

I would like to add the `sort.Reverse` functionality to the `sort.Slice` functions.

Example code:
```
type Less func(i, j int) bool

func ReverseLess(f Less) Less {
        return func(i, j int) bool {
                return f(j, i)
        }
}
```

Is this something that belongs in the stdlib or should people implement this themselves if needed?

**Comment by vcabbage** [comment]
What benefit does this bring over simply reversing the comparison operator?

Sort ascending:
```go
sort.Slice(people, func(i, j int) bool { return people[i].Name < people[j].Name })
```

Sort descending:
```go
sort.Slice(people, func(i, j int) bool { return people[i].Name > people[j].Name })
```

**Comment by bradfitz** [comment]
This was already discussed in the long thread at #16721 in which the current Go 1.8 API was decided upon. e.g. https://github.com/golang/go/issues/16721#issue-171324550 proposed sort.Slice integration with reverse and Russ's reply at https://github.com/golang/go/issues/16721#issuecomment-250783324 and other posts there.
