### ISSUE TITLE
Proposal: encoding/json: add new tag for numbers to be string or number literals for unmarshalling

### ISSUE THREAD

**Issue by b-s-a** [golang/go#19175]
Current implementation of json decoder (1.7) requires numbers be integers or strings only if string tag specified. Most web oriented languages (php for example) has no difference between types, so json produced by them can contain integers/floats/booleans as strings.
I suggest to create new tag which permits numbers as strings and ints at same time.
Example:
```go
struct {
    X int `json:"x,maystring"`
}
```
Can be unmarshalled from `{"x":"1234"}` and `{"x":1234}`

**Comment by vcabbage** [comment]
You can already handle this by implementing the [`json.Unmarshaller`](https://golang.org/pkg/encoding/json/#Unmarshaler) interface or using the [`json.Number`](https://golang.org/pkg/encoding/json/#Number) type. Example: https://play.golang.org/p/HGXCF0Bp1X

**Comment by bradfitz** [comment]
Closing since solutions already exist, and the json package is increasingly frozen for changes.
