### ISSUE TITLE
Compiler Failed Status 1

### ISSUE THREAD

**Issue by JetDanTe** [golang/go#19180]
I`m so sorry for my bad english and small experience with debian OS`es.

### What version of Go are you using (`go version`)?
Succes compile 1.4.3. 

### What operating system and processor architecture are you using (`go env`)?
Raspbian for OrangePi Pc, it uses the AllWinner H3 SoC.

### What did you do?
Trying install google cloud print connector.
When starting compile 1.6.3 version from 1.4.3, it ok for some time, but failed with status 1. 
Another OS and diffrent ways to install it fail with status 1.

### What did you expect to see?
Black magic?

**Comment by bradfitz** [comment]
Sorry, there's not enough info here to help you. The bug report is incomplete. I recommend you discuss this on the mailing list.
