### ISSUE TITLE
mime/multipart: "filename" Content-Disposition parameter should be optional

### ISSUE THREAD

**Issue by matiasanaya** [golang/go#19183]
### What version of Go are you using?

`go version go1.7.4 darwin/amd64`

### What operating system and processor architecture are you using?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/matias.anaya/go"
GORACE=""
GOROOT="/Users/matias.anaya/.goenv/versions/1.7.4"
GOTOOLDIR="/Users/matias.anaya/.goenv/versions/1.7.4/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

Tried to read a "file" in a `multipart/form-data` which did not have a `filename`.
* [https://play.golang.org/p/lOugQARAZ4](https://play.golang.org/p/lOugQARAZ4)

### What did you expect to see?

`multipart.File` and `multipart.FileHeader` being correctly built and returned.

### What did you see instead?

Error: `http: no such file`

### Thoughts?

[multipart ReadForm](https://golang.org/src/mime/multipart/formdata.go?s=592:649#L13) assumes a "filename" will be present. [RFC2388](https://tools.ietf.org/html/rfc2388) mentions that this parameter is optional.

Looks like `multipart.Form` (which has a `multipart.Form.Value` and a `multipart.Form.File` map) tries to figure out what's a "file" and what's a "value" at parse time without caller input. Is this a decision that can be revisited?

Also wouldn't it be more correct to have a `multipart.Form.Part` abstraction which can be used as a "Value" (`string`) or a "File" (`*FileHeader`)?

**Comment by odeke-em** [comment]
@matiasanaya if interested, please feel free to send a CL and we'll review it.

**Comment by matiasanaya** [comment]
@odeke-em perfect, I'll work on it.

**Comment by nilsmagnus** [comment]
How can we know if there is a file present? Is it enough to know that there is a Content-type header in the Part?

**Comment by ianlancetaylor** [comment]
I don't understand how you can expect to use `FormFile`, which requires a file name, to look up a multipart that doesn't have a file name.  Why not use `MultipartReader` instead?

**Comment by nilsmagnus** [comment]
I am not sure I understand your comment @ianlancetaylor , patch only changes the behaviour when a filename is not specified. From what I can see, the `multipart.Reader` is already beeing used.

**Comment by ianlancetaylor** [comment]
> I am not sure I understand your comment @ianlancetaylor , patch only changes the behaviour when a filename is not specified.

Is that true?  The original code tests `filename == ""`.  The new code does not.  With the new code, if `filename` is not the empty string, but there is a `Content-Type` header, then it seems like the behaviour changes.  What am I missing?

**Comment by nilsmagnus** [comment]
Thanks, I was thinking about this just before I went to sleep yesterday, but forgot to add it. I will revise the change.
