### ISSUE TITLE
runtime: inconsistent definition for func runtime.memclrNoHeapPointers during import

### ISSUE THREAD

**Issue by davidlazar** [golang/go#19185]
This is purposefully one commit behind 1f77db94f8 and what we would see after we fix #19184.
```
$ go version
go version devel +8833af3f4b Wed Feb 15 21:14:37 2017 +0000 linux/amd64
```

In the runtime directory:
```
$ go test -a -short -gcflags '-l=4'
# runtime_test
./callers_test.go:8: cannot import "runtime" due to version skew - reinstall package (inconsistent definition for func runtime.memclrNoHeapPointers during import
	func(*byte, uintptr)
	func(unsafe.Pointer, uintptr))
FAIL	runtime [build failed]
```

One potential solution is to mark `MemclrBytes` noinline, but it's not clear if that is the right long-term solution.

**Comment by cherrymui** [comment]
The compiler thinks `memclrNoHeapPointers` has signature `func(*byte, uintptr)` (https://go.googlesource.com/go/+/master/src/cmd/compile/internal/gc/builtin/runtime.go#130), whereas the actual function in runtime has signature `func(unsafe.Pointer, uintptr)`.
CL https://golang.org/cl/37257 changes the compiler's copy to match the runtime.
However, there are other functions marked as taking `*byte` or `*any` in the compiler, but actually takes a pointer to a specific runtime type, or arbitrary pointer type. There might be also problem if they get imported through inlining. Maybe we should let bimport's check allow this case?
