### ISSUE TITLE
cmd/go: should not depend on the existence of the default $GOROOT

### ISSUE THREAD

**Issue by opennota** [golang/go#19187]
### What version of Go are you using (`go version`)?

1.8

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

I downloaded `go1.8.linux-amd64.tar.gz` and extracted it into the home directory and did `export PATH="/home/user/go/bin:$PATH"`. Then I tried to run `go version`.

### What did you expect to see?

Go version number.

### What did you see instead?

`go: cannot find GOROOT directory: /usr/local/go`

None of the commands `build`, `fmt`, `generate`, `get`, `install`, `list`, `run`, `test`, `vet` etc. do work. They all print the same error.

When I create an empty `/usr/local/go`, they all by some magic start to work.

**Comment by ALTree** [comment]
Did you manually set `GOROOT`?

**Comment by opennota** [comment]
I didn't. The problem occurs without explicitly set GOROOT variable. And if I set it to `/home/user/go` (the location where I've unpacked the archive), things also work (unsurprisingly).

**Comment by ALTree** [comment]
Please post the output of `go env`. Also what does `echo $GOROOT` print?

**Comment by opennota** [comment]
> Please post the output of go env.

With unexported GOROOT:

```
$ export -n GOROOT
$ go env
go: cannot find GOROOT directory: /usr/local/go
```

With GOROOT set to `/home/opennota/go`:

```
$ export GOROOT=/home/opennota/go
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/opennota/go"
GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build941069124=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

> Also what does echo $GOROOT print?

Nothing, if GOROOT is not set. `/home/user/go`, it if is.

**Comment by ALTree** [comment]
I'm not sure there's anything do to here.

The `GOROOT` default value is baked in the executable, so if you download the precompiled binaries you'll always have `/usr/local/go` baked in. If you put go in another directory, if *must* set `GOROOT` (otherwise nothing will work). This is documented:

> $GOROOT [..]  Its value is built into the tree when it is compiled

and:

> It is possible to install the Go tools to a different location. In this case you must set the GOROOT  environment variable to point to the directory in which it was installed.

**Comment by ianlancetaylor** [comment]
Closing as dup of #17833.
