### ISSUE TITLE
x/tools/cmd/goimports: import grouping depends on which imports were already there

### ISSUE THREAD

**Issue by cespare** [golang/go#19190]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go 1.8

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

This is on the latest version of goimports (golang/tools@8e779ee0a4509783f6940db32d1a4e8df910cc8b).

Consider this test program:

```
package main

import (
	"time"
)

func main() {
	_ = snappy.Encode
	_ = unix.Mmap
	_ = time.Parse
}
```

It's missing two imports. If we run `goimports -w fmt.go`, we'll get

```
package main

import (
	"time"

	"github.com/golang/snappy"
	"golang.org/x/sys/unix"
)

func main() {
	_ = snappy.Encode
	_ = unix.Mmap
	_ = time.Parse
}
```

This is what I expect. However, if we delete the unix import:

```
package main

import (
	"time"

	"github.com/golang/snappy"
)

func main() {
	_ = snappy.Encode
	_ = unix.Mmap
	_ = time.Parse
}
```

and then run goimports again, we get this grouping:

```
package main

import (
	"time"

	"golang.org/x/sys/unix"

	"github.com/golang/snappy"
)

func main() {
	_ = snappy.Encode
	_ = unix.Mmap
	_ = time.Parse
}
```

In this second case, I'd expect the file to be the same as the first case instead of introducing a new grouping.

/cc @bradfitz

**Comment by bradfitz** [comment]
I don't have time to work on this myself.

**Comment by haya14busa** [comment]
Thank you for cc. I think I can work on it.

**Comment by haya14busa** [comment]
I explained what was the problem and how I fixed it in cl/37552, but the fix is a bit heuristic... It works better for most cases though.

cl/37552 works good as far as I know and the change is small, but I welcome better solution if you find more elegant solution.
