### ISSUE TITLE
cmd/go: cannot pre-install testing dependencies with the -race flag

### ISSUE THREAD

**Issue by amenzhinsky** [golang/go#19197]
### What version of Go are you using (`go version`)?
go1.8

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
Go is installed system-wide, so I install all `std` packages:
```
$ sudo install -a -race std
```

Then I try to pre-install my testing dependencies for empty library with just one file (the same happens to any package):
```
package foo
func Foo() {}
```

And it fails since current user has no privileges to copy files to `/usr/lib/go`
```
$ go test -a -race -i .
go install errors: open /usr/lib/go/pkg/linux_amd64_race/errors.a: permission denied
go install internal/race: open /usr/lib/go/pkg/linux_amd64_race/internal/race.a: permission denied
go install unicode/utf8: open /usr/lib/go/pkg/linux_amd64_race/unicode/utf8.a: permission denied
go install unicode: open /usr/lib/go/pkg/linux_amd64_race/unicode.a: permission denied
go install math: open /usr/lib/go/pkg/linux_amd64_race/math.a: permission denied
```

### What did you expect to see?
All std packages should be cached and reused since the're not updated.

**Comment by ALTree** [comment]
Dup of #19133
