### ISSUE TITLE
html/template: URL auto-escaper may produce invalid markup

### ISSUE THREAD

**Issue by moshee** [golang/go#19205]
### What version of Go are you using (`go version`)?

go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

Any environment.

### What did you do?

https://play.golang.org/p/vkxq91HMhf

### What did you expect to see?

The template produces fully valid markup, i.e. `<a href="http://www.example.com/%5B%5D">a</a>`, as if using url.PathEscape.

### What did you see instead?

The square brackets remain unescaped in the path. According to [the W3 Validator](https://validator.w3.org), this is invalid:

<img width="913" alt="screen shot 2017-02-20 at 11 04 59 am" src="https://cloud.githubusercontent.com/assets/936355/23138495/a6501896-f75c-11e6-845d-3954dad06e61.png">

**Comment by odeke-em** [comment]
@rsc do you think there might be some security implications in changing this?

**Comment by mikesamuel** [comment]
Square brackets are allowed in URIs as in IPv6 numeric hosts per [RFC 6874](https://www.rfc-editor.org/rfc/rfc6874.txt).

```abnf
IP-literal = "[" ( IPv6address / IPv6addrz / IPvFuture  ) "]"
```

so we ought not fix this by breaking https://play.golang.org/p/ZO713Uf8_Z

We could normalize URLs which would address the problem but, IIRC, that's a tricky operation without current core library support that requires making assumptions about the page encoding.

----

> The template produces fully valid markup

This is impossible for URIs without non-local reasoning.  For example,

```go
template.New("asdf")
    .Parse(`<a href="{{if .IsHost}}http://{{end}}{{.UrlPart}}{{if .IsHost}}/{{end}}">`)
```

In this instance, we would need to either

  *  have the escaping directive know about the context based on information available at runtime
  * do a second pass at the end of the href value to normalize the URL.

----

Unless there are security consequences to not validating here, I would leave as-is.

**Comment by ianlancetaylor** [comment]
It sounds like we shouldn't make any change here.  Closing.  Please comment if you disagree.
