### ISSUE TITLE
cmd/compile: miscompilation (missing BSWAPL) in go1.8

### ISSUE THREAD

**Issue by flyingmutant** [golang/go#19201]
### What version of Go are you using (`go version`)?
`go version go1.8 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build043674809=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

https://play.golang.org/p/O9a63D2aU4:

```go
package main

import (
        "encoding/binary"
        "fmt"
)

var (
        ch1 = make(chan int)
        ch2 = make(chan int)

        bin  = []byte("a\000\000\001")
        want = binary.BigEndian.Uint32(bin)

        c consumer = noopConsumer{}
)

type msg struct {
        code uint32
}

type consumer interface {
        consume(msg)
}

type noopConsumer struct{}

func (noopConsumer) consume(msg) {}

func init() {
        close(ch1)
}

func main() {
        var m msg
        m.code = binary.BigEndian.Uint32(bin)

        select {
        case <-ch1:
                c.consume(m)
                if m.code != want {
                        // can not use m.code here, or it will work
                        fmt.Printf("wrong msg %#v, want code 0x%x\n", m, want)
                } 
        case <-ch2:
        }
}
```

### What did you expect to see?

Nothing.

### What did you see instead?

`wrong msg main.msg{code:0x1000061}, want code 0x61000001`

**Comment by ALTree** [comment]
cc @TocarIP @randall77

**Comment by TocarIP** [comment]
Stepping through instructions in gdb shows that bswap + store are executed twice.  bswap(bswap(x)) == x, so this case fails. First execution of bswap is on normal path and the second is after runtime.selectgo sets pc to the basic block containing bswap. I suspect fuse pass, which puts shits/ors into the same block as newselect/selectrecv

**Comment by aclements** [comment]
Need to decide whether to move [CL 37376](golang.org/cl/37376) to the release branch or cherry pick [CL 37661](golang.org/cl/27661).

**Comment by aclements** [comment]
Created https://go-review.googlesource.com/c/38587 for the change to the release branch. @TocarIP, would you mind paring down the one for master (https://go-review.googlesource.com/c/37376) to just the test?
