### ISSUE TITLE
winsock listen error

### ISSUE THREAD

**Issue by carr123** [golang/go#19210]
### What version of Go are you using (`go version`)?
go1.8.windows-386

### What operating system and processor architecture are you using (`go env`)?
windows xp .  x86   32bit

### What did you do?
I start 500 server sockets, listening from TCP addr 127.0.0.1:17000 to 127.0.0.1:17500.
i only got 160 sockets listened ok, others failed.
error info :  " listen: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full".
but, i wrote another C++ program, do the same thing, and this C++ program can successfully listen on 500 sockets. 

i find a solution to the go grogram by setting registry:
[HKEY_LOCAL_MACHINE \System \CurrentControlSet \Services \Tcpip \Parameters]
TcpNumConnections = 65534
then the the Go program can listen on 500 TCP ports.
but this need to reboot the windows xp. and i don't want user to reboot.

**Comment by bradfitz** [comment]
Got a repro? Where's the source code?

For questions about Go, see https://golang.org/wiki/Questions.

I'm going to close this for now, for lack of anything we can help with at the moment. The mailing list is probably the best place to discuss this until a problem is identified.

**Comment by carr123** [comment]
func ListenMany() {
	for i := 0; i < 164; i++ {
		serverAddr, err := net.ResolveTCPAddr("tcp", fmt.Sprintf("127.0.0.1:%d", i+13000))
		if err != nil {
			return
		}

		_, err = net.ListenTCP("tcp", serverAddr)
		if err != nil {
			fmt.Println("listen ", serverAddr, "failed", err)
		}
	}
}

only 162 ports can be listened successfully on my windows xp running in virtualbox
