### ISSUE TITLE
cmd/compile: tighten pass moves value incorrectly

### ISSUE THREAD

**Issue by cherrymui** [golang/go#19217]
### What version of Go are you using (`go version`)?
go1.8

@funny-falcon reported in issue #19179 that the following code doesn't compile. It is a different bug than the original one in #19179 -- the problem happens in the tighten pass, instead of the writebarrier pass. I can reproduce it with Go 1.8. (But it compiles with Go 1.7)

```
package dbfile

import (
	"encoding/binary"
)

type DbBuilder struct {
	arr        []int
}

func (bld *DbBuilder) Finish() error {
	defer bld.Finish()

	var hash []byte
	for _, ixw := range bld.arr {
		for {
			if ixw != 0 {
				panic("ixw != 0")
			}
			ixw--
		insertOne:
			for {
				for i := 0; i < 1; i++ {
					if binary.LittleEndian.Uint16(hash[i:]) == 0 {
						break insertOne
					}
				}
			}
		}
	}

	return nil
}
```

**Comment by cherrymui** [comment]
The problem is that
(before tighten)
```
b9:
  v148 = Phi <int> v39 v64
  ...

(some other blocks)

  v64 = Add64 <int> v100 v148
  ...

(some other blocks)
(have an edge going back to b9)
```

tighten pass moves v64 to the predecessor block of b9.

**Comment by cherrymui** [comment]
Reopen for patching Go 1.8.

**Comment by aclements** [comment]
Cherry-picked to release.
