### ISSUE TITLE
Query: Is it possible to call functions of the plugin dynamically?

### ISSUE THREAD

**Issue by sinsharat** [golang/go#19214]
Go 1.8
Linux amd64
I am loading the plugins dynamically and caching them. 
I want to call the plugins function dynamically based on the function name provided.

Say i have a plugin named abc.so which has functions as below:

```
// args receiver
func Run() error{
       fmt.Println("Run function executed.")
	return nil
}

// multi-args receiver
func MultiArguments(value string, nos int) string {
	return value + fmt.Sprintf("%v", nos)
}
```

Now in order to call this via my code currently i am having to do the following:
```
func call(object string) error {
        p, err := plugin.Open(object)
	if err != nil {
		return fmt.Errorf("could not open %s: %v", object, err)
	}
	run, err := p.Lookup("Arguments")
	if err != nil {
		return fmt.Errorf("could not find Run function: %v", err)
	}
        // i am forced to know the type of function before hand to call this.
	runFunc, ok := run.(func() error)
	if !ok {
		return fmt.Errorf("found Run but type is %T instead of func() error", run)
	}
	if err := runFunc(); err != nil {
		return fmt.Errorf("plugin failed with error %v", err)
	}
	return nil
}
```
Is there any way to call the method names directly and simply passing the argumnets to it?:
```
func CallMethod(pluginName string, funcName string, args ...interface{}) interface{} {
// call the method directly by invoking the function name on the specified plugin and args for the function.
}
```

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions .  Thanks.

To do what you want, look at `reflect.ValueOf` and `reflect.Value.Call`; those work for any functions, including functions defined by a plugin.  But you'll still have to get the types right, so I don't really see how it will help your larger problem.

**Comment by sinsharat** [comment]
Thanks.
