### ISSUE TITLE
TLS verify off via environment variable

### ISSUE THREAD

**Issue by git001** [golang/go#19215]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Feature request for 1.7, 1.8 and following

### What operating system and processor architecture are you using (`go env`)?
ANY

I observed in enterprise environment very much a own PKI.
This PKI is used to sign the internal https certificates.

When I use some go application like (clair, hugo, ...) I get a lot of 'certificate authority not known'.

It would be nice to have a environment variable ala GO_TLS_VERIFY with which I can turn the tls verify off from outside the  builded go programm.

**Comment by davecheney** [comment]
I don't think this is the right approach. If your environment relies on a
private CA, you should distribute that root certificate via your
organisation's configuration management system.

**Comment by bradfitz** [comment]
Yeah, I agree with @davecheney. I don't think this is the right answer.

**Comment by git001** [comment]
Well sometimes you have not the permission to add this.
But okay that's your decision  :-(
