### ISSUE TITLE
runtime/cgo: s390x builder "pthread_create failed: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by mundaym** [golang/go#19228]
Seen once on the s390x builder:

```
--- FAIL: Test18146 (57.06s)
	issue18146.go:121: syscall.Exec failed: exit status 2
		runtime/cgo: pthread_create failed: Resource temporarily unavailable
		SIGABRT: abort
		PC=0x3ffa213a568 m=5 sigcode=4294967290
                ⋮
	issue18146.go:126: Failed 1 of 1000 attempts.
FAIL
```
https://build.golang.org/log/7f5772173ca4c3abbc402b95460e79f530a9551a

Perhaps an EAGAIN check should be added to gcc_linux_*.c.

**Comment by ianlancetaylor** [comment]
The `EAGAIN` check is already there.  The purpose of that particular test is to verify that it is working.  This failure means that `pthread_create` failed 20 times in a row with a steadily increasing timeout.  See https://golang.org/src/runtime/cgo/gcc_libinit.c, the `_cgo_try_pthread_create` function.

**Comment by mundaym** [comment]
Ah, thanks Ian. I think I'll close this for now then. I'll reopen if I see it happening again.
