### ISSUE TITLE
doc: error in effective_go.html#maps

### ISSUE THREAD

**Issue by davidflanagan** [golang/go#19223]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Just reading the current online docs

### What operating system and processor architecture are you using (`go env`)?

N.A.

### What did you do?

Read https://golang.org/doc/effective_go.html#maps

Notice that it says "empty string" where it should say something about "the value 0".

### What did you see instead?

This paragraph is incorrect:

> Sometimes you need to distinguish a missing entry from a zero value. Is there an entry for "UTC" or is that the empty string because it's not in the map at all? You can discriminate with a form of multiple assignment. 

### What did you expect to see?

It would be more correct if it read: 

> Sometimes you need to distinguish a missing entry from a zero value. Is there an entry for "UTC" or is `timeZone["UTC"] ` equal to `0` because "UTC" is not in the map at all? You can discriminate with a form of multiple assignment.

**Comment by bradfitz** [comment]
For the record, the text above with the declaration is:

```go
var timeZone = map[string]int{
    "UTC":  0*60*60,
    "EST": -5*60*60,
    "CST": -6*60*60,
    "MST": -7*60*60,
    "PST": -8*60*60,
}
```

**Comment by kevinburke** [comment]
On it
