### ISSUE TITLE
x/tools/cmd/goimports: hangs in uninterruptible sleep

### ISSUE THREAD

**Issue by tcoffee-google** [golang/go#19225]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/tcoffee/go"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build134362667=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

Run `goimports -w myfile.go`.

### What did you expect to see?

Program termination.

### What did you see instead?

The goimports process goes into uninterruptible sleep, blocking on disk I/O (status 'D') for at least 20 minutes, and hence cannot be killed without rebooting.

**Comment by kevinburke** [comment]
tcoffee-google, is there anything special or interesting about `myfile.go`?

**Comment by bradfitz** [comment]
Are you using one of Google's internal FUSE filesystems? If so I'd mail the Google internal mailing lists for tips.

**Comment by aeneasr** [comment]
I have the same issue on Windows, it's a larger project. Command `goimports $(go list -f {{.Dir}} ./... | grep -v vendor)` outputs files but is incredibly slow - probably 1-2 seconds per file? Running with flags `-d` or `-w` nothing happens and goimport just hangs. I'm not sure if it's just very slow to process everything or if it really hangs. This took at most 2 seconds some time back.

I recently did `go get -u golang.org/x/tools/cmd/goimports` and used your (@bradfitz ) version before that but I'm experiencing the same issue. I recently upgraded to Go 1.11.1

Also, `goimports` runs with almost zero resources used (CPU, Disk, Memory):

![image](https://user-images.githubusercontent.com/3372410/46684508-4d597580-cbf3-11e8-81bd-86ad6bcaff77.png)

Any ideas?

**Comment by aeneasr** [comment]
After a reboot the same issue persists. What's interesting though is that `gofmt` works perfectly, so I doubt that this is a OS issue.

**Comment by arnavsharma93** [comment]
I'm facing this too. `goimports` used to be much faster. Now, it hangs my editor for a second or two. Any idea how to fix it?

**Comment by bradfitz** [comment]
@arnavsharma93, this is a closed bug and we don't track closed bugs. If you want to open a new bug, please include a lot more info. Piling on this overloaded bug just gets distracting.
