### ISSUE TITLE
spec: clarify whether str[low : high] shares the underlying memory with str

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#19220]
The standard strings package has no Index(s, sep string, fromIndex int) function, which means we must use call Index(s[fromIndex:], sep) if the fromIndex is not zero.

If a third party compiler makes str[low : high] not share the underlying memroy with str, then the call Index(s[fromIndex:], sep) is not efficient.

**Comment by ianlancetaylor** [comment]
As I said on the mailing list (https://groups.google.com/d/msg/golang-nuts/lX66xDOnz1s/ranckvjJAAAJ) I think it would be a mistake to change the spec in this way.  There are valid cases where it is desirable for a string slice to make a copy.

It does not make sense to program defensively against an implementation that is theoretically possible but that no one will ever write.  You may as well say that the spec should specify that integer addition should be done using a machine instruction rather than calling a function that converts the integers to strings and adds them character by character.

**Comment by bradfitz** [comment]
It already says:

> If the sliced operand of a valid slice expression is a nil slice, the result is a nil slice. Otherwise, the result shares its underlying array with the operand.

**Comment by ianlancetaylor** [comment]
@bradfitz That is true but that only applies to slices, not strings.

**Comment by bradfitz** [comment]
@ianlancetaylor, it's in the same section that starts with:

> Slice expressions construct a substring or slice from a string, array, pointer to array, or slice.....

**Comment by ianlancetaylor** [comment]
@bradfitz But strings do not have an underlying array.  Only slices have that, so that paragraph can't possibly apply to strings.  But you're right that it's written in a confusing way.

**Comment by griesemer** [comment]
Note to self: Review if spec needs clarification.

**Comment by yaxinlx** [comment]
Another point needed to be clarified is whether or not compilers should guarantee that the two strings in a string assignment should share the underlying bytes.
I haven't found the confirmation in Go spec.

Now, much Go code assumes this is always true.

**Comment by griesemer** [comment]
@yaxinlx I don't think we want implementations to be constricted that way. For instance, I can imagine an implementation where short strings, say up to 7 or 8 bytes, are stored in a word that is copied as a whole each time. The sharing requirement would be an over-specification.

**Comment by yaxinlx** [comment]
@griesemer ok. But maybe it is good to mention string implementation is compiler specific in spec so that programmers can beware of this.

**Comment by griesemer** [comment]
@yaxinlx All implementation is compiler-specific - not sure there is anything meaningful that should be said here. What do you have in mind?

**Comment by Go101** [comment]
no problem.

My concern is just that there are many 3rd party packages use string as error, which may make error comparison inefficient if potential other Go compilers are used.

**Comment by yaxinlx** [comment]
My another concern is ranging over strings.
Ranging over a string will copy the string. If two strings don't share the underlying bytes, then the copy may be expensive.

**Comment by yaxinlx** [comment]
Aha, the original intention of this issue is to add an strings.IndexFrom(s, sep string, fromIndex int) API, :)
