### ISSUE TITLE
cmd/go: Canonical paths should be enforced on vendored imports

### ISSUE THREAD

**Issue by apilloud** [golang/go#19224]
I have a package which vendors packages with [Canonical Imports](https://golang.org/doc/go1.4#canonicalimports). Build worked fine when the imports were vendored but failed when the packages were moved into the GOPATH. This is because canonical import paths are not enforced on vendored packages.

### What version of Go are you using (`go version`)?

From vendor support merging to latest master (a355639c6046edae6b3a5190bc78260c2fe3b063)

### What did you do?

1. Wrote a package which imported 'github.com/rsc/pdf'
2. git cloned 'github.com/rsc/pdf' in the packages 'vendor' directory
2. Ran `go build .`

### What did you expect to see?

mypackage.go:8:2: code in directory $GOPATH/vendor/github.com/rsc/pdf expects import "rsc.io/pdf"

### What did you see instead?

Nothing. (Command exited with success.)

**Comment by apilloud** [comment]
Fix is here: https://go-review.googlesource.com/c/37371/

**Comment by bradfitz** [comment]
Leaving for @rsc. I'm not sure whether the current behavior is intentional. I guess not, though.

**Comment by rsc** [comment]
It's intentional that the code doesn't complain that rsc.io/pdf is found in foo.com/vendor/rsc.io/pdf. It was not strictly intentional that it also doesn't complain about foo.com/vendor/github.com/rsc/pdf, but maybe that's OK too. Not sure.

**Comment by rsc** [comment]
Every time I change the conditions under which this error triggers, it breaks someone. I am inclined to leave this alone. It's OK that we're not enforcing the import paths in the vendor dir: let's assume that's managed by a tool that knows what it's doing. In the long term we hope vendor dirs disappear.
