### ISSUE TITLE
net/http: TestTransportBodyReadError flake 

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#19231]
Seen from trybot:

https://storage.googleapis.com/go-build-log/dba99eff/openbsd-amd64-60_9893d709.log

    --- FAIL: TestTransportBodyReadError (0.01s)
    	client_test.go:1821: Got error: net/http: HTTP/1.x transport connection broken: some body read error; want Request.Body read error: some body read error
    FAIL
    FAIL	net/http	4.860s

**Comment by bradfitz** [comment]
(Others: feel free to debug this before I get to it.)
