### ISSUE TITLE
i found a golang debugging bug

### ISSUE THREAD

**Issue by trysh** [golang/go#19235]
I found a bug when I try to debug the golang code below:

```
package main

import "log"

type SA struct {
	dataint int
	datastr string
	datasi  []int
}

type SB struct {
}

func (sb *SB) sbfun(sa SA) {
}

func main() {
	log.Println(`start`)
	var sb *SB = nil //always nil
	if sb != nil { // always false
		log.Println(`flag 1`)
		sb.sbfun(SA{}) // I set breakpoint here
	}
	log.Println(`end`)
}
```

I set the breakpoint and debug(using gdb or Delve), but it always interrupted there, 
and no “flag 1” appeared on console, can anyone detail why such bug with this code? can anyone try to debug this code ?
many thanks.

https://github.com/trysh/golangBUG

chinese:

我发现了一个golang在debug时的BUG，对不起，我英文不好，请看以下代码：
```
package main

import "log"

type SA struct {
	dataint int
	datastr string
	datasi  []int
}

type SB struct {
}

func (sb *SB) sbfun(sa SA) {
}

func main() {
	log.Println(`start`)
	var sb *SB = nil //总是为nil
	if sb != nil { // 总是为false
		log.Println(`flag 1`)
		sb.sbfun(SA{}) // 我在这里设置断点
	}
	log.Println(`end`)
}
```

当我在那个地方设置断点，然后开始debug这个程序（使用gdb或Delve）,就会发现，
程序总是中断在那个地方，并且中断的时候在控制台看不到“flag 1”输出标记，
为什么会这样？大家可以用这段代码亲自试一试。十分感谢！
https://github.com/trysh/golangBUG

**Comment by mvdan** [comment]
Please see https://github.com/golang/go/wiki/Questions for more appropriate places to ask for help. Open an issue here if you come to the conclusion that there is a bug in Go itself.

Thanks!
