### ISSUE TITLE
Question: Would goroutine be as memory efficient as BEAM's light process?

### ISSUE THREAD

**Issue by kokizzu** [golang/go#19236]
I did a benchmark, go took about 100% to 200% more RAM than elixir/erlang counterpart
http://stackoverflow.com/questions/41894046

**Comment by mvdan** [comment]
What does "RAM" mean in that context, exactly?

Note that your goroutines exit immediately, so if you're trying to measure how much memory N goroutines use when idle, this is not it.

**Comment by kokizzu** [comment]
`alias time='/usr/bin/time -f "\nCPU: %Us\tReal: %es\tRAM: %MKB"'`

on that context it's maximum resident

**Comment by RLH** [comment]
This is an incomplete bug report.
What version of Go are you using, what machine is it running on and so
forth.
The link is also confusing. I can't tell what you are benchmarking, go run
mumble runs the compiler, is that what you intended to benchmark.

**Comment by kokizzu** [comment]
It's Go 1.7.4 on 64-bit Linux

**Comment by mvdan** [comment]
@kokizzu as @RLH said, when you do `time go run ...`, you're also measuring the memory that the compiler and linker use. Fix your benchmark first.

I also don't see the bug report or request here - this seems more like a question for golang-nuts. Have you seen https://github.com/golang/go/wiki/Questions?

**Comment by kokizzu** [comment]
The compiler and linker part doesn't really matter on >=500k benchmark:

`for k in 5 50 500; do echo -n $k; time go run test.go $k > /dev/null; done`
```
5
CPU: 0.19s      Real: 0.30s     RAM: 26808KB
50
CPU: 0.26s      Real: 0.26s     RAM: 26884KB
500
CPU: 5.08s      Real: 2.43s     RAM: 1114980KB
```

`go build test.go ; for k in 5 50 500; do echo -n $k; time ./test $k > /dev/null; done`
```
5
CPU: 0.01s      Real: 0.00s     RAM: 4192KB
50
CPU: 0.09s      Real: 0.04s     RAM: 16580KB
500
CPU: 4.85s      Real: 2.14s     RAM: 1086304KB
```

**Comment by RLH** [comment]
This bug is not actionable so I'm closing it for now. It seems more like a question and as such should discussed elsewhere as @mvdan suggests or reformulated as a actionable bug explaining why the program is not acting as expected.

**Comment by mattn** [comment]
@kokizzu FYI, you can avoid busy loop.
```go
package main

import (
    "fmt"
    "os"
    "runtime"
    "strconv"
    "sync"
)

func main() {
    var wg sync.WaitGroup
    if len(os.Args) < 2 {
        os.Exit(1)
    }
    k, ok := strconv.Atoi(os.Args[1])
    if ok != nil {
        os.Exit(2)
    }
    k *= 1000
    wg.Add(k)
    for z := 0; z < k; z++ {
        x := z
        go func() {
            defer wg.Done()
            fmt.Println(x)
        }()
        if z%100 == 0 {
            runtime.Gosched()
        }
    }
    wg.Wait()
}
```

go build test.go && for k in 5 50 500 5000; do echo -n $k; time ./test $k > /dev/null; done
```
5
CPU: 0.00s      Real: 0.03s     RAM: 2248KB
50
CPU: 0.05s      Real: 0.15s     RAM: 2768KB
500
CPU: 0.55s      Real: 1.54s     RAM: 6344KB
5000
CPU: 5.56s      Real: 5.87s     RAM: 11032KB
```

**Comment by RLH** [comment]
@mattn Nice. 
The schedule tree is a very wide (k) and very shallow (1). Your change reduces the breadth of the schedule tree by allowing (on average) the children to run and complete before the parent spawns more goroutines. This basically keeps the breadth at around 100. I have no idea what the schedule tree looks like in erlang though I am curious if they have incorporated something similar to your code to reduce the breadth of the schedule. If this interests anyone take a look at the Cilk papers.
