### ISSUE TITLE
cmd/compile: String() on structs containing empty structs has changed

### ISSUE THREAD

**Issue by heschik** [golang/go#19246]
Prior to 8958d8ce37fdae15693787019869ab21e7b8347a (cmd/compile: skip convT2E for empty structs), the below test didn't call B.String(). After that commit it does, breaking a test that compared the result. I think this is actually a bug *fix*, but since that commit was supposed to be a pure performance improvement, some investigation is probably warranted.

```
package test

import (
	"fmt"
	"testing"
)

type A struct {
	Cs []*C
}

func (a *A) String() string {
	return fmt.Sprintf("%+v", *a)
}

type B struct{}

func (b *B) String() string {
	return fmt.Sprintf("B.STRING WAS CALLED %+v", *b)
}

type C struct {
	Name string
	B    *B
}

func (c *C) String() string {
	return fmt.Sprintf("%+v", *c)
}

func TestString(t *testing.T) {
	a := A{
		Cs: []*C{{
			Name: "ae1",
		}},
	}
	want := "{Cs:[{Name:ae1 B:<nil>}]}"

	if g, w := a.String(), want; g != w {
		t.Errorf("got %q want %q", g, w)
	}
}
```

**Comment by heschik** [comment]
@randall77 @josharian

**Comment by cherrymui** [comment]
In fact, the String method *is* called both on tip and on Go 1.8 (and before). On Go 1.8, it panics with nil pointer (`*b`) and the fmt package recovers it and prints "<nil>". On tip, it doesn't panic, because `b` is *not* nil (but should be). A simple repro:

```
package main

type B struct{}

//go:noinline
func f(i interface{}) {}

func main() {
        var b *B
        f(*b)
}
```

On Go 1.8, this code panics on `f(*b)`. On tip, it doesn't.

**Comment by josharian** [comment]
Thanks for the bug report! Fix coming soon.
