### ISSUE TITLE
go/types: Named.Obj doc is wrong

### ISSUE THREAD

**Issue by willfaught** [golang/go#19249]
https://golang.org/pkg/go/types/#Named.Obj documentation is wrong:

```
TypeName returns the type name for the named type t.
```

**Comment by griesemer** [comment]
@willfaught How do you propose I change it?

**Comment by willfaught** [comment]
I'm not sure I understand your question. It should be:

><strike>TypeName</strike>Obj returns the type name for the named type t.

**Comment by griesemer** [comment]
@willfaught Of course. Obviously should have had my coffee first... - Thanks.
