### ISSUE TITLE
go get from private repo with git version after 1.8.3

### ISSUE THREAD

**Issue by alphayan** [golang/go#19251]
i use cenots with git 1.8.3 ,user alpine with git 2.11.0,
when i use the centos to go get somthing,it is ok.then i change the git version 2.11.0 on centos.it become something wrong.
i find that after the git version 1.8.3；use the golang's cmd go get -u -v from a private repos is return an error like:
package git.coding.net/alphayan/orionv2.git: cannot download, git.coding.net/alpha***/***** uses insecure protocol
and then i use go get -u -v -insecure it return an error like:
fatal: could not read Username for 'https://git.coding.net': terminal prompts disabled
i don't konw it's git's or golang's bug

**Comment by mvdan** [comment]
When you run `go get -v`, it lists the commands it runs, including the `git clone`. Have you tried running that separately?

If that fails, then it's likely a git problem, not a Go one.

Also, please see the issue template - this bug report is missing a lot of information, like the Go version you're using.

**Comment by alphayan** [comment]
@mvdan  thanks,i made a try and error. 
centos :go version 1.8; git version 1.8.3. it's right.

**Comment by mvdan** [comment]
This doesn't make much sense. What git command was run? Does it look correct? Does it work if you run it separately?

**Comment by alphayan** [comment]
@mvdan thanks,i made a try and error.
centos7 :go version 1.8; git version 1.8.3. it's right!
alpine3.5:go version 1.8;git version 2.11.0,it return an error.
when i change the centos's git version to 2.11.0. i use go get -u -v,it also return an error.
but both centos and alpine, i use git clone, it all right !
it throw me for a loss

**Comment by mvdan** [comment]
Seems like the issue is that when Go calls `git` it's not attached to a terminal, so it can't ask for a password. I'm pretty sure this is by design - `go get` is for users, not developers with advanced use-cases like private repos. They can `git clone` directly. See https://github.com/golang/go/issues/6968#issuecomment-66089347

As a workaround, you can set up password caching or ssh auth via a private key: https://gist.github.com/shurcooL/6927554

**Comment by alphayan** [comment]
@mvdan thank you very much~!
