### ISSUE TITLE
Why dose Go add the "transfer-encoding: chunked" header in a Put request when i set the "Content-Length" header?

### ISSUE THREAD

**Issue by chidaren** [golang/go#19257]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.71

### What operating system and processor architecture are you using (`go env`)?
Centos 6.7 32bit

### What did you do?
when i create a http client using: "client := &http.Client{}", and i execute "client.Do(req)" and the "req" is a http.Request ,it has "put" method,and req.body is a io.Reader, and i set the "Content-Length" header.

but when i caputre this request using tcpdump,i found the request has “transfer-encoding: chunked” header, has not  the "Content-Length" header . So how can i make it does't use "transfer-encoding: chunked"  header, and use "Content-Length" header.

### What did you expect to see?
When i make a Put request, Go won't add "transfer-encoding: chunked" and "User-Agent: Go-http-client/1.1" headers, and use the "Content-Length" header i set.

### What did you see instead?
Go remove  the "Content-Length" header, and add a "transfer-encoding: chunked" header, when i make a Put request.

There are  all my questions, and thank you!

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please see https://golang.org/wik/Questions for appropriate forums.
