### ISSUE TITLE
cmd/compile: complete all error-checking before SSA conversion

### ISSUE THREAD

**Issue by josharian** [golang/go#19250]
There are a handful of checks that occur during gc -> SSA conversion, such as goto scoping. This is non-ideal for two reasons:

* It will complicate making that conversion concurrent.
* It means that we must do the expensive conversion step to fully check some code. We might want to stop early ([CL 37384](https://golang.org/cl/37384)) for speed reasons ([CL 37385](https://golang.org/cl/37385)) or e.g. to speed up fuzzing cmd/compile vs go/types.

I'd like to consider adding a compilation phase after walk but before SSA conversion to do all these error checks that would otherwise happen during conversion, assuming that that phase is cheap/fast enough.

cc @mdempsky @randall77 for opinions

**Comment by dr2chase** [comment]
I ran into this while tinkering with loop backedge rescheduling -- I could not willy-nilly rewrite loops and add labels, because my compiler-generated labels were sometimes flagged as "unused" -- but aren't we also intending to deprecate walk into non-existence?

**Comment by josharian** [comment]
As I understand it, the plan for walk (and friends) is to be consumed from either side by the new parser and SSA. I'd like for us to ensure that any invalid code gets caught prior to doing the AST -> SSA conversion, whatever flavor the AST, and preserve that invariant. Step one is establishing that invariant. Sound ok?

**Comment by josharian** [comment]
As for compiler-generated labels being flagged as unused, see the Node flag introduced (reused) in https://github.com/golang/go/commit/d1faf3879ede9efc9f1907dfad04bac8ec08d598.

**Comment by dr2chase** [comment]
Your plan works for me.

**Comment by randall77** [comment]
Sounds good to me.
