### ISSUE TITLE
Add runtime.ReadSchedStat to get schedstat from runtime

### ISSUE THREAD

**Issue by stgleb** [golang/go#19256]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8

### What operating system and processor architecture are you using (`go env`)?

linux

Is it possible to collect schedtrace data from go by itself like runtime.ReadMemStat ? I want to collect and analyze this data somewhere like graphite etc.

**Comment by bradfitz** [comment]
Dup of #15490
