### ISSUE TITLE
internal/poll: Changed error string breaks user application

### ISSUE THREAD

**Issue by typeless** [golang/go#19252]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version devel +3792db5 Mon Feb 13 18:36:28 2017 +0000 linux/amd64`
*It works on Go 1.8*

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mura/devel/go"
GORACE=""
GOROOT="/home/mura/tools/go"
GOTOOLDIR="/home/mura/tools/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174238897=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
`make integration-test` for the code I am working on.
https://github.com/go-gitea/gitea/pull/741#discussion_r102649390
But I think that doesn't matter after all.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
All tests passed.

### What did you see instead?
All tests failed.

It turned out that one of the dependent libraries ( (See https://github.com/facebookgo/httpdown/blob/master/httpdown.go#L338) uses the exact error string to make its decision and the string in question was changed at some point of time (https://github.com/golang/go/commit/3792db518327c685da17ca6c6faa4e1d2da4c33c#diff-18782360650b1a2ccfee593591ff45bbR17). This may not be the fault of the error string changing but I'd like to know what the recommended solution (an idimatic way for differentiating errors)  is for the case. And maybe the possible impact can be prepared before the next production release.

**Comment by mvdan** [comment]
As far as I know, error strings are not under the Go1 compatibility contract. If your program depends on them, it might break in the future or not be portable at all (e.g. some `os` errors change between operating systems, I believe).

The way to do this in a portable and backwards/forwards compatible way is to check for error types, not error messages. Although that won't be possible if the package just uses `errors.New()`.

**Comment by ianlancetaylor** [comment]
This is related to #4373.

**Comment by bradfitz** [comment]
Marking for Go 1.9.

> This may not be the fault of the error string changing but I'd like to know what the recommended solution (an idimatic way for differentiating errors) is for the case

Indeed.
