### ISSUE TITLE
Suggest new function `memset`

### ISSUE THREAD

**Issue by corebreaker** [golang/go#19266]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\dev\go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
https://play.golang.org/p/CUDi8csrsx

### What did you expect to see?
Having that's function `memset` in builtin package. We have the `copy` function for copying a slice which seems be like `memmove` C function, but it would be interesting to have the `memset` function for quickly initilizing a slice. It would have that signature: `func memset(slice []Type, value Type)`.

In fact, I did it for byte slice, but i must do it for the other data type as `int`. `copy` function in builtin package works for any slice type, that's the reason why i would like having `memset` function for any slice type too.

**Comment by cznic** [comment]
- Just write the loop.
- Ask the compiler developers to recognize the loop and optimize it to an unexported runtime memset, if that's not already the case.

**Comment by corebreaker** [comment]
I have already a solution ! See that code: https://play.golang.org/p/CUDi8csrsx !

Plus, `copy` function can be done by a loop too.

I've just suggested that as in builtin function like `copy`, cause `copy` function is like `memmove` C function, and the memmove/memset is semanticly linked. Therefore `copy` is "sister" function of `memset`. My idea is why `copy` (which can be replaced by a loop) is in builtin function and so not `memset`.

**Comment by minux** [comment]
The copy builtin is different as memmove is non-trivial to implement and
generally useful.
memset isn't as common because Go variables are initialized to their zero
values by default and it's idiomatic to make the zero value useful as
default.

**Comment by corebreaker** [comment]
I understand.

However, `memset` can be useful in the case of reusing a `[]byte` buffer avoiding re-allocation, and in theses cases zeroing a buffer is sometimes necessary to have buffer in "initialized" state.

I've allocated a 100Mb buffer, and with a loop it were very slow even with optimizations. For that, i need doing fast zeroing.

**Comment by golang101** [comment]
memclr optimization has been implemented https://www.reddit.com/r/golang/comments/5t8km2/range_over_arrays_or_array_pointers/?ref=search_posts

**Comment by corebreaker** [comment]
Ok, thanks.

It works, i benchmarked it. I did not suspect such a thing.
