### ISSUE TITLE
cmd/vet: vet should recommend "os.IsNotExist(err)" over "err == os.ErrNotExist"

### ISSUE THREAD

**Issue by golang101** [golang/go#19267]
It looks the ErrNotExist variable in os package shouldn't be exported at all.

**Comment by corebreaker** [comment]
It's used by the function `IsNotExists` in os package that can be used to know if a file or a directory exists or not like in file https://github.com/siddontang/go/blob/master/ioutil2/ioutil.go (line 38).

**Comment by ianlancetaylor** [comment]
Is this mistake really common enough that it deserves a vet check?

**Comment by josharian** [comment]
@dominikh

**Comment by dominikh** [comment]
In my own corpus (most public Go packages), there are 229 matches for `[!=]= os\.ErrNotExist` and 36618 matches for `os\.IsNotExist\(`. 

Among the 229 results are matches in camlistore, rkt and docker.

**Comment by golang101** [comment]
@ianlancetaylor, I seldom write file io programs. I think it is so natural that use "err == os.ErrNotExist" to check if a file exists or not when I used the io.Open function the first time. But I was wrong.

**Comment by bradfitz** [comment]
> Among the 229 results are matches in camlistore, rkt and docker.

But in Camlistore we have interfaces documenting that os.ErrNotExist is the contract between our own interfaces and our own implementations.

A sample:

```
make.go:// The error is os.ErrNotExist if GOPATH is unset or the directory
make.go:                return path, os.ErrNotExist
make.go:        return path, os.ErrNotExist
pkg/blob/fetcher.go:    // os.ErrNotExist should be returned for the error (not a wrapped
pkg/blob/fetcher.go:    // offset or length is negative, or os.ErrNotExist if the blob
pkg/blobserver/b2/b2.go:                return nil, 0, os.ErrNotExist
pkg/blobserver/blobpacked/subfetch.go:// check. The returned error should be os.ErrNotExist if the blob
```

I think this vet check would be noisier than it would be helpful.

@robpike?

**Comment by robpike** [comment]
I don't think this merits a vet check. Remember it must satisfy the criteria specified in the readme of correctness, frequency, and precision. It fails for correctness and is marginal for frequency and precision.
