### ISSUE TITLE
crypto/tls: GetClientCertificate is not preserved by Clone

### ISSUE THREAD

**Issue by bhiggins** [golang/go#19264]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8 (this feature was introduced in 1.8)

### What operating system and processor architecture are you using (`go env`)?

Linux (but it doesn't matter here)

### What did you do?

Used tls.Dial (or tls.DialWithDialer) without setting ServerName in Config.

### What did you expect to see?

A successful connection.

### What did you see instead?

"remote error: tls: bad certificate" on the client and "tls: client didn't provide a certificate" on the server.

Workaround: set ServerName so that the config isn't cloned by tls.DialWithDialer.

(BTW, maybe it would be useful in unit tests to clone configs immediately before use.)

**Comment by bradfitz** [comment]
I thought I replied to this already, but I can't find it.

What makes you think this is not being cloned? The source code and this snippet sure suggests it is:

    https://play.golang.org/p/Hk6eSLa4-l

Please share some minimal code you expect to work and what it does instead. Thanks.

**Comment by bhiggins** [comment]
@bradfitz, this is regarding GetClientCertificate (added in 1.8), not GetCertificate. I took a look at Clone and GetClientCertificate was not included.

Here is an example: https://play.golang.org/p/6zbpqxY6U1

I expect it to print "Works for me" but instead line 16 panics.

**Comment by bradfitz** [comment]
Hey @agl, if you'd have accepted an earlier version of my CL (patchset 3: https://go-review.googlesource.com/c/28075/3/src/crypto/tls/tls_test.go#471) with the robust regexp-based test, we woudln't be here.  :-)

But our existing test for Config.Clone lets things slip through the cracks, like this.

**Comment by FiloSottile** [comment]
Ah, I had this in my TODO because it was encountered recently at Cloudflare.

Any chances this could be considered for 1.8.1?

**Comment by jefferai** [comment]
And in that vein any idea when such a release might be? This sadly makes this (otherwise exciting) new feature fairly unusable in real code, especially for any code wanting to use the `http2` package.

**Comment by mikedanese** [comment]
The kubernetes team was also greatly anticipating this feature in 1.8. As far as patches go, this one seems fairly safe. Any chance we could get it into 1.8.1? Otherwise we will likely have to build kubernetes with a patched go toolchain.

cc @cjcullen @jcbsmpsn

**Comment by bradfitz** [comment]
Would've been nice if Kubernetes had helped test Go 1.8 sooner back when I was asking  (https://github.com/kubernetes/kubernetes/issues/38228) and maybe found this bug before Go 1.8. Oh, well. Better late than never, I guess.

**Comment by bradfitz** [comment]
Reopening for Go 1.8.1.

**Comment by jefferai** [comment]
Just as a note, while I also badly hope this will be in 1.8.1, it's pretty trivial to work around this with a locally-patched vendored version of the `http2` library, if that's where you're running into this problem, in the file `go1.8.go`:
```go
func cloneTLSConfig(c *tls.Config) *tls.Config {
	// MODIFIED from upstream to work around Go bug
	ret := c.Clone()
	ret.GetClientCertificate = c.GetClientCertificate
	return ret
}
```
Perhaps this could make its way into `http2` for now?

**Comment by bradfitz** [comment]
@jefferai, done: https://go-review.googlesource.com/37944

**Comment by bradfitz** [comment]
Cherry-picked.
