### ISSUE TITLE
x/mobile silently fails to install

### ISSUE THREAD

**Issue by DanielJoyce** [golang/go#19272]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daniel/pkgs/go"
GORACE=""
GOROOT="/home/daniel/bin/go1.8"
GOTOOLDIR="/home/daniel/bin/go1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build318382580=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"                                                                                                      
PKG_CONFIG="pkg-config"                                                                                              
CGO_CFLAGS="-g -O2"                                                                                                  
CGO_CPPFLAGS=""                                                                                                      
CGO_CXXFLAGS="-g -O2"                                                                                                
CGO_FFLAGS="-g -O2"                                                                                                  
CGO_LDFLAGS="-g -O2"   
```

uname -a

```
Linux lnx-daniel 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux        
```

cat /etc/lsb-relase

```
DISTRIB_ID=LinuxMint                                                                                                 
DISTRIB_RELEASE=17.3                                                                                                 
DISTRIB_CODENAME=rosa                                                                                                
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

edited my bashrc to include the following:

``` bash
export GOPATH="$HOME/pkgs/go"
export GOROOT="$HOME/bin/go1.8"
export PATH=$PATH:$GOROOT/bin
```

Installed go. 

go runs fine. Compiled and ran a simple hello world.

when I run the command to install gomobile nothing happens:

```
~/scratch > go get golang.org/x/mobile/cmd/gomobile                            
~/scratch >                       
```

It immeadiately returns, producing no output or errors

If I then try and run gomobile, it says command not found

```
~/scratch > gomobile
gomobile: command not found                                                                                          
~/scratch > 
```

### What did you expect to see?

gomobile is installed and can be run

### What did you see instead?

Nothing, no errors, nada

**Comment by DanielJoyce** [comment]
If I try and install the git repo directly ( Should this be doable? ), I get the following

```
~/scratch > go get github.com/golang/mobile
can't load package: package github.com/golang/mobile: no buildable Go source files in /home/daniel/pkgs/go/src/github.com/golang/mobile
```

**Comment by DanielJoyce** [comment]
tested 1.7.5, doesn't work either.

**Comment by DanielJoyce** [comment]
Oh wait, it appears to install, but there is no message that it worked. Thats terrible feedback.

**Comment by DanielJoyce** [comment]
You need to add $GOPATH/bin to your path as well. Not documented.

**Comment by quentinmit** [comment]
@DanielJoyce There's nothing special about gomobile in this respect; `go get $anything` will install into `$GOPATH/bin`. This is documented at https://golang.org/doc/code.html#GOPATH

Unfortunately, this is WAI. If you have a suggestion for how to better improve the documentation, feel free to send a CL.
