### ISSUE TITLE
cmd/asm: support file-scoped symbols

### ISSUE THREAD

**Issue by josharian** [golang/go#19277]
See https://github.com/golang/go/issues/18225 for history and discussion. Once completed, roll back part of CL 34284.

**Comment by mwhudson** [comment]
I think this would require making cmd/internal/obj support more values for LSym.Version than just 0 and 1. Probably the approach used by the linker would work OK (having an array of LSym maps indexed by version). Some linker changes would also be required, it currently assumes each object file only consumes one potential value for version. Nothing that can't be changed, but not completely trivial.

**Comment by josharian** [comment]
Could this be done instead with some name mangling?

**Comment by mwhudson** [comment]
Yes probably

**Comment by rsc** [comment]
If we want to allow the assembler to process multiple files then we would need to do this.
But I don't think it's particularly important for the assembler to process multiple files:
it is fine to continue to call it once per file, and then this bug, and all other similar
bugs where files are not treated truly independently, will be impossible.
That really seems like the best strategy.
Having any assembly files is rare; having many is even rarer. Not worth the trouble.
