### ISSUE TITLE
math/bits: Reverse8, Reverse16 can use table lookup

### ISSUE THREAD

**Issue by rsc** [golang/go#19279]
bits.Reverse8 can use table lookup - the table is in compress/flate as reverseByte.

bits.Reverse16 can do reverseByte[(x>>16)&0xFF] | reverseByte[x&0xFF]<<16.

I experimented with these last week and they came out significantly faster than the current shifty implementations. Using table vs the current shifts for Reverse32 was almost exactly the same and probably not worth changing.

Probably worth doing, but I don't have time to do proper benchmarking at the moment.

/cc @griesemer

**Comment by griesemer** [comment]
@rsc I have experimented with this as well. It's true that the table lookups are quite a bit faster if measured alone. (I even have the generator code to create the tables for reverse, population count, and leading/trailing zeroes for 8 bit values.) But if the table is not in cache, I bet it's quite a bit slower. (On the other hand, if the table is not in cache, the function is probably not hot and thus it may not matter).

**Comment by rasky** [comment]
FWIW, the same applies to OnesCount8 and OnesCount16.
