### ISSUE TITLE
Make it possible to change the "json" key in package json

### ISSUE THREAD

**Issue by crgimenes** [golang/go#19271]
Make it possible to change the "json" key/tag in the json package, so other people can create packages that use different tag name simply by changing the string and extending the functionality.

Apparently it's just a matter of changing the constant "json" on the line below by a public variable
```
tag := sf.Tag.Get("json")
```

This line of code is in the following file:
https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L1107

go version go1.8 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cesar/Projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0s/p11dph4n2hv356yq969fxvwm0000gn/T/go-build150354871=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by kevinburke** [comment]
> other people can create packages that use different tag name simply by changing the string and extending the functionality.

I'm a little confused why this needs the tag name to be configurable. Can't you just implement json.Unmarshaler? Or have packages satisfy some other interface that interacts with your custom decoder?

**Comment by crgimenes** [comment]
Hello @kevinburke, I'm not trying to implement a decoder, I just do not want the user of my package that already uses a tag to have to define one more. If I can just change the tag name that the json package is using the problem would be resolved without duplicate code. 

I will investigate to find out if an unmarshal coton solves the problem but I believe it is not what I need.

**Comment by kevinburke** [comment]
It's unfortunate that they have to define an extra tag, but I'm guessing that changing the tag name is going to be a non-starter... among the problems, what if you rename the `json` tag to `xml`, what if you import a package that globally renames the `json` tag and wreaks havoc on code that isn't expecting it to be renamed, what if you redefine it in the midst of parsing a struct. 

You are certainly free to export the code in `src/encoding/json/*.go` to your own namespace and add code to it there...

**Comment by bradfitz** [comment]
Sorry, I'm going to decline this one. The json package is mostly frozen, especially for things like this that introduce extra complexity for everybody (code to maintain for us, godoc for everybody to read and understand) for marginal convenience for a few users.

**Comment by crgimenes** [comment]
Certainly, define the new tag name can not be global, so it not to affect the other parts of the code that is using the json package. But this would imply creating a struct to and returning a new instance of the configuration variables.

As you mentioned I could export this small part of the code and make the changes myself, but by default I prefer to try to use the official packages and try to reduce to the maximum duplicate code ... I will reserve this solution in case I can not find another solution.

I'm not sure if I'm being clear so let me show you what I'm trying to do.

This is the package I am trying to implement:
https://github.com/crgimenes/goConfig

Everything works perfectly well, I use the tag "cfg" except when I try to read the settings of a json file, in this case the user of the package must also define a json tag in the struct that It's moving on to my package to have the same changes in the field name.

**Comment by crgimenes** [comment]
ok @bradfitz I understand it.

Please if imagine some solution let me know.
