### ISSUE TITLE
cmd/compile: uint16 arithmetic results different on arm between go 1.8 and go 1.7.5

### ISSUE THREAD

**Issue by nsd20463** [golang/go#19270]
On 32-bit arm linux I've found some code that produces an incorrect result when compiled with go 1.8.
Go 1.8 on amd64, and go 1.7.5 on 32-bit arm, produce the correct result.

This is illustrated by the little example at 
  https://play.golang.org/p/ji1Jc-OozF
which prints the byte-swapped result of its input.

The correct output is 0x888e. But the executable produced by
  GOARCH=arm GOARM=7 go build test.go
prints 0xff8e.

**Comment by ianlancetaylor** [comment]
CC @randall77 @josharian

**Comment by cherrymui** [comment]
```
(Lrot16 <t> x [c]) -> (OR (SLLconst <t> x [c&15]) (SRLconst <t> x [16-c&15]))
```
This rule was wrong. It should zero-extend x before right shift. On the other hand, it should use rotation instruction at first place. This is already fixed in Go 1.9 (Keith's CL on moving rotation generation to SSA). For fixing Go 1.8, I'll add a zero-extension there.

**Comment by randall77** [comment]
You should check all the other architectures to make sure we don't have the same bug there.

**Comment by cherrymui** [comment]
> it should use rotation instruction at first place.

Correction: there is no sub-word rotation instruction. So lowering to left-shift OR right-shift (with zero-extension) is the right way.

> You should check all the other architectures to make sure we don't have the same bug there.

Other architectures are correct. 386/AMD64 uses rotation instruction; ARM64 has a similar rule as ARM but does have zero-extension; Lrot8/16 are not generated on other architectures.
