### ISSUE TITLE
crypto/rand: probably time to block in getrandom

### ISSUE THREAD

**Issue by agl** [golang/go#19274]
The 1.9 cycle might be the correct time to revisit #11833 now that getrandom has spread further, including into a Ubuntu LTS release.

**Comment by josephlr** [comment]
Some more info here.

1. [Patch submitted](https://go-review.googlesource.com/#/c/37570/) to x/sys/unix to add in the more recent syscalls and add bindings for getrandom(). This might allow cleanup of the [internal/syscall/unix](https://github.com/golang/go/tree/master/src/internal/syscall/unix) and [rand_linux.go](https://github.com/golang/go/blob/master/src/crypto/rand/rand_linux.go) code. 

2. According to [this search on distrowatch.com](http://distrowatch.com/search.php?pkg=linux&relation=greaterequal&pkgver=3.17&distrorange=InAny#pkgsearch), all of the 10 most popular distros + Arch Linux have releases with a new enough kernel to support this. As @agl mentioned, this includes Ubuntu 16.04 LTS, but also the LTS distros of Mint 17.3 (Rosa), Mint 18.1 (Serena), Fedora 21 and Later, and Manjoro 15-16. The big one missing is Debian which doesn't support it in 8 but will in 9 (which uses the 4.9 kernel) which will be out by Go 1.9.

3. Finally, should the new implementation block or fail when the appropriate read cannot be done? Failing seems to fit the go paradigm the best as all readers can return an error. However, there is also the danger that not checking for the returned error can lead to a buffer that has some zero bytes still in it, so blocking might be the safer option.

**Comment by bradfitz** [comment]
@agl, please do this this week if you want to get this in for Go 1.9.

**Comment by agl** [comment]
(No chance at the moment because of <Google-internal reason that you might be aware of>.)
