### ISSUE TITLE
cmd/compile: stack corruption in github.com/go-openapi/swag tests

### ISSUE THREAD

**Issue by heschik** [golang/go#19278]
Starting at commit 03583675765933d4a5fb394cfa89fb41b274aaa7, the runtime crashes inside of reflect.DeepEqual while running github.com/go-openapi/swag.TestBoolMap:
```
runtime: bad pointer in frame reflect.DeepEqual at 0xc42005bb98: 0x1
fatal error: invalid pointer found on stack
```

Full crash [attached](https://github.com/golang/go/files/800369/crash-03583675765933d4a5fb394cfa89fb41b274aaa7.txt). The crash changes at later revisions of the runtime, but I expect that it's a new symptom of the same underlying cause rather than a new problem.

For posterity, I checked out the code under test at the following revisions:
github.com/go-openapi/swag d5f8ebc3b1c55a4cf6489eeae7354f338cfe299e
github.com/stretchr/testify 4d4bfba8f1d1027c4fdbe371823030df51419987

@josharian

**Comment by josharian** [comment]
Possibly related to #19275.

**Comment by heschik** [comment]
Maybe, but I don't think so given that the breaking commit is different. Without having fully read the code of 03583675765933d4a5fb394cfa89fb41b274aaa7, I would guess that the stack map says that there should be a pointer to a heap-allocated interface in the stack slot, and instead we've allocated it directly on the stack? (That 0x1 is pretty suspicious.)

**Comment by dr2chase** [comment]
This appears to be closed by https://go-review.googlesource.com/c/37470/ .

**Comment by heschik** [comment]
Indeed. Guess I should have listened to the expert. Thanks!
