### ISSUE TITLE
cmd/compile: regression when combining load+op on AMD64

### ISSUE THREAD

**Issue by dsnet** [golang/go#19284]
21c71d77887733c02a7ae31b65b1b12041485ee5 caused a regression.

Using yuin/gopher-lua@eed1c7917d2f4a7bbed5e9bf6a0ce64cbd2918c5 it passes on the Go revision before 21c71d77887733c02a7ae31b65b1b12041485ee5, but fails afterwards.

```
$ go.dev test github.com/yuin/gopher-lua
--- FAIL: TestLua (5.72s)
	script_test.go:74: runtime error: slice bounds out of range
		stack traceback:
			[G]: in function 'match'
			pm.lua:12: in function 'f1'
			pm.lua:77: in main chunk
			[G]: ?
```

\cc @TocarIP @randall77

**Comment by randall77** [comment]
This is a bug in gopher-lua.  In github.com/yuin/gopher-lua/stringlib.go:365 we have
```
	mds, err := pm.Find(pattern, *(*[]byte)(unsafe.Pointer(&str)), offset, 1)
```
Where str is a `string`.  That's not a safe thing to do.  The pointer and length of the resulting `[]byte` slice are ok, but the capacity is junk.  That slice later gets subsliced at github.com/yuin/gopher-lua/pm/pm.go:591 and the junk capacity makes that slicing fail.

Pure luck that this used to work at all.
I'll open an issue against gopher-lua.
