### ISSUE TITLE
x/net/route: TestFetchAndParseRIB fails on IPv4-only or IPv6-only kernel

### ISSUE THREAD

**Issue by wheelcomplex** [golang/go#19298]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

cd ${HOME} && git clone https://go.googlesource.com/go && cd go/src && ./all.bash

#### What did you expect to see?

ALL PASS

#### What did you see instead?

<pre>
cmd/compile/internal/arm64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile

##### Testing packages.
ok  	archive/tar	0.065s
ok  	archive/zip	1.736s
ok  	bufio	0.134s
ok  	bytes	0.329s
ok  	compress/bzip2	0.106s
ok  	compress/flate	1.483s
ok  	compress/gzip	0.054s
ok  	compress/lzw	0.023s
ok  	compress/zlib	0.059s
ok  	container/heap	0.026s
ok  	container/list	0.037s
ok  	container/ring	0.027s
ok  	context	1.268s
ok  	crypto/aes	0.050s
ok  	crypto/cipher	0.027s
ok  	crypto/des	0.024s
ok  	crypto/dsa	0.029s
ok  	crypto/ecdsa	0.106s
.............
ok  	unicode	0.011s
ok  	unicode/utf16	0.010s
ok  	unicode/utf8	0.015s
ok  	vendor/golang_org/x/crypto/chacha20poly1305	0.084s
ok  	vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20	0.010s
ok  	vendor/golang_org/x/crypto/curve25519	0.044s
ok  	vendor/golang_org/x/crypto/poly1305	0.013s
ok  	vendor/golang_org/x/net/http2/hpack	0.019s
ok  	vendor/golang_org/x/net/idna	0.017s
ok  	vendor/golang_org/x/net/lex/httplex	0.023s
--- FAIL: TestFetchAndParseRIB (0.06s)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 0.0.0.0) (inet4 172.16.0.2) (inet4 0.0.0.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 127.0.0.1) (link 2 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 172.16.0.0) (link 1 <nil> <nil>) (inet4 255.255.255.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 172.16.0.3) (link 1 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: netmask|ifa|brd (inet4 255.255.255.0) (inet4 172.16.0.3) (inet4 172.16.0.255)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: netmask|ifa|brd (inet4 255.0.0.0) (inet4 127.0.0.1) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 0.0.0.0) (inet4 172.16.0.2) (inet4 0.0.0.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 127.0.0.1) (link 2 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 172.16.0.0) (link 1 <nil> <nil>) (inet4 255.255.255.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 172.16.0.3) (link 1 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: netmask|ifa|brd (inet4 255.255.255.0) (inet4 172.16.0.3) (inet4 172.16.0.255)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: netmask|ifa|brd (inet4 255.0.0.0) (inet4 127.0.0.1) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
	message_test.go:21: inet6 1 sysctl: address family not supported by protocol family
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
FAIL
FAIL	vendor/golang_org/x/net/route	0.073s
ok  	cmd/addr2line	1.434s
ok  	cmd/api	0.030s
ok  	cmd/asm/internal/asm	0.349s
...........
ok  	cmd/vendor/github.com/google/pprof/internal/elfexec	0.020s
ok  	cmd/vendor/github.com/google/pprof/internal/graph	0.031s
ok  	cmd/vendor/github.com/google/pprof/internal/report	0.020s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolizer	0.018s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolz	0.022s
ok  	cmd/vendor/github.com/google/pprof/profile	0.091s
ok  	cmd/vendor/github.com/ianlancetaylor/demangle	0.042s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.021s
ok  	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.017s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	0.229s
ok  	cmd/vet	3.398s
ok  	cmd/vet/internal/cfg	0.014s
2017/02/27 20:18:16 Failed: exit status 1
</re>

#### Does this issue reproduce with the latest release (go1.8)?
Yes, with go version go1.8 freebsd/amd64.
<pre>
cd ${HOME} && wget https://storage.googleapis.com/golang/go1.8.src.tar.gz && \
tar xfz go1.8.src.tar.gz && cd go/src && ./all.bash

ok  	vendor/golang_org/x/net/http2/hpack	0.020s
ok  	vendor/golang_org/x/net/idna	0.026s
ok  	vendor/golang_org/x/net/lex/httplex	0.015s
--- FAIL: TestFetchAndParseRIB (0.05s)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 0.0.0.0) (inet4 172.16.0.2) (inet4 0.0.0.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 127.0.0.1) (link 2 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 172.16.0.0) (link 1 <nil> <nil>) (inet4 255.255.255.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 172.16.0.3) (link 1 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: netmask|ifa|brd (inet4 255.255.255.0) (inet4 172.16.0.3) (inet4 172.16.0.255)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: netmask|ifa|brd (inet4 255.0.0.0) (inet4 127.0.0.1) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 0.0.0.0) (inet4 172.16.0.2) (inet4 0.0.0.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 127.0.0.1) (link 2 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: dst|gateway|netmask|ifp|ifa (pmtu=1500) (inet4 172.16.0.0) (link 1 <nil> <nil>) (inet4 255.255.255.0) (link 1 re0 40:16:7e:81:3d:3e) (inet4 172.16.0.3)
	message_test.go:30: dst|gateway|ifp|ifa (pmtu=16384) (inet4 172.16.0.3) (link 1 <nil> <nil>) (link 2 lo0 <nil>) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: netmask|ifa|brd (inet4 255.255.255.0) (inet4 172.16.0.3) (inet4 172.16.0.255)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: netmask|ifa|brd (inet4 255.0.0.0) (inet4 127.0.0.1) (inet4 127.0.0.1)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
	message_test.go:21: inet6 1 sysctl: address family not supported by protocol family
	message_test.go:30: ifp (type=6 mtu=1500) (link 1 re0 40:16:7e:81:3d:3e)
	message_test.go:30: ifp (type=24 mtu=16384) (link 2 lo0 <nil>)
	message_test.go:30: ifp (type=246 mtu=33160) (link 3 pflog0 <nil>)
	message_test.go:30: ifp (type=247 mtu=1500) (link 4 pfsync0 <nil>)
	message_test.go:30: ifp (type=6 mtu=1500) (link 5 vboxnet0 0a:00:27:00:00:00)
FAIL
FAIL	vendor/golang_org/x/net/route	0.070s
ok  	cmd/addr2line	1.055s

</pre>

#### System details

```
go version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 freebsd/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/david/home/sandspace/extpkg/"
GORACE=""
GOROOT="/home/david/home/sandspace/go"
GOTOOLDIR="/home/david/home/sandspace/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build899609558=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="0"
CGO_CFLAGS="-gdwarf-4"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 freebsd/amd64
GOROOT/bin/go tool compile -V: compile version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 X:framepointer
uname -v: FreeBSD 11.0-STABLE #72 9364f2f79a1(stable11): Sun Feb 26 21:28:08 NZDT 2017     root@david-n550jk.localdomain:/tank/cross/obj/amd64/home/david/sandspace/private-freebsd/sys/PREINIT-DEBUG
lldb --version: lldb version 3.8.0 clang revision 262564
gdb --version: GNU gdb 6.1.1 [FreeBSD]
```

**Comment by bradfitz** [comment]
We now have FreeBSD 11 builders running on the dashboard. Maybe that'll help.

@mikioh, you got this one?

**Comment by mikioh** [comment]
```message_test.go:21: inet6 1 sysctl: address family not supported by protocol family```

It also happens on IPv6-only kernel; see #5707 and #5708.
