### ISSUE TITLE
os/signal: tests run too long and fail on NetBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19295]
The new NetBSD 7.0 builders on GCE are now up and we're trying to get the build passing on NetBSD again.

The latest failure is:

```
*** Test killed: ran too long (4m0s).
FAIL	os/signal	273.238s
```

@ianlancetaylor, Mr. Signals, any ideas?

/cc @bsiegert @mdempsky

**Comment by ianlancetaylor** [comment]
No ideas.  Are they gomote-able?

**Comment by bradfitz** [comment]
Yes.

**Comment by bsiegert** [comment]
The last time this came up was #16511, though that was on 32-bit.

**Comment by bradfitz** [comment]
I updated the NetBSD builders to NetBSD 7.1.

Maybe something was fixed. We'll see.

**Comment by zoulasc** [comment]
Should be fixed in NetBSD head and with the latest netbsd package from pkgsrc.

**Comment by bradfitz** [comment]
Our continuous build system uses Go's source, not pkgsrc.

Were there NetBSD kernel fixes involved? (That is, do we need to update our base VM Image and update Go's https://golang.org/wiki/MinimumRequirements page to say you need NetBSD 7.2?

**Comment by krytarowski** [comment]
I guess that NetBSD 8-beta is sane minimum.
