### ISSUE TITLE
suggest ignore type name as calling func when the func's param has concrete type

### ISSUE THREAD

**Issue by imroc** [golang/go#19299]
if a function's param is not interface or pointer,has concrete type,then we must give the function a certain type param when we call it.for example:
``` go
func main() {
	test(map[string]string{
		"name": "roc",
		"age":  22,
	})
}
func test(m map[string]string) {
	fmt.Println(m)
}
```
the func receive a param which typed map[string]string,the compiler konws its' type in compile time,so why we can't ignore the param's type when we call that func?if we could,it will be very convenient,like this:
``` go
func main() {
	test({
		"name": "roc",
		"age":  22,
	})
}
func test(m map[string]string) {
	fmt.Println(m)
}
```

**Comment by bradfitz** [comment]
Dup of #12854
