### ISSUE TITLE
spec: clarify if a type with underlying unsafe.Pointer type can be used for unsafe conversions

### ISSUE THREAD

**Issue by griesemer** [golang/go#19306]
See also #6326 and https://github.com/golang/go/issues/18130#issuecomment-282803521 .

In the same vein, decide if `type P = unsafe.Pointer` should be allowed.

**Comment by rsc** [comment]
If gc and gccgo allow it today, it should continue to be allowed. We've passed the point of no return on a breaking change like that. The "audit" argument is fairly weak: the audit will find the initial definitions and then the people auditing can decide easily enough whether to expand their search.
