### ISSUE TITLE
x/build: failing FreeBSD 11.0 builders do not upload the entire build log

### ISSUE THREAD

**Issue by paulzhol** [golang/go#19309]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
[d53c02fdfc033740769ecf49ff6750834fa1829d](https://build.golang.org/log/d53c02fdfc033740769ecf49ff6750834fa1829d)
### What did you expect to see?
```
...
cmd/compile/internal/s390x
cmd/compile/internal/x86
cmd/compile


##### Testing packages.
ok  	archive/tar	0.069s
ok  	archive/zip	2.871s
...
```

### What did you see instead?
```
...
cmd/compile/internal/x86
cmd/compile
```

Nothing further indicating what caused the build to fail.

**Comment by bradfitz** [comment]
That is the entire build log.

It exited with a non-zero status and ends there.

The build failure info is in the middle:

```
# runtime/cgo
runtime/cgo/gcc_amd64.S:47:1: warning: DWARF2 only supports one section per compilation unit
.section .note.GNU-stack,"",@progbits
^
go build runtime/cgo: C compiler warning promoted to error on Go builders
```

There's an open bug for that already.

Closing, assuming I understand this bug correctly.

**Comment by paulzhol** [comment]
Sorry, I missed the `C compiler warning promoted to error on Go builders` bit. This behavior applies to buildlet builders only correct? Should GO_BUILDER_NAME be set for old-stype builders as well?

**Comment by bradfitz** [comment]
Probaby.
