### ISSUE TITLE
play: uses 1.6 formatter, which can produce invalid code

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#19310]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
play.golang.org

### What operating system and processor architecture are you using (`go env`)?
I don't know.

### What did you do?

I formatted the following program https://play.golang.org/p/MyGD0azump

```golang
package main

import (
	"fmt"
)

func main() {
	var i int
	fmt.Println(); /**/ i++
}
```

### What did you expect to see?

A program that compiles.

### What did you see instead?

`;` after `fmt.Println()` is dropped which is syntax error.

**Comment by rjammala** [comment]
seems to work ok at tip.

$ cat tf.go 
package main

import "fmt"

func main() {
	var i int
	fmt.Println() /**/
	i++
}

$ go version
go version devel +eae657e Mon Feb 27 15:18:44 2017 +0000 linux/amd64

**Comment by cespare** [comment]
I don't understand what the playground gofmt is doing. When I run my local Go 1.8 gofmt (linux/amd64), I get correct output:

```
￼package main

import "fmt"

func main() {
        var i int
        fmt.Println() /**/
        i++
}
```

**Comment by griesemer** [comment]
Same here. Works fine at tip, but on playground I get:
```
9:21: expected ';', found 'IDENT' i (and 1 more errors)
```
but the source is not even changed. Incorrect version of gofmt for the playground?

**Comment by cespare** [comment]
@griesemer I think you have "imports" checked on the playground.

I also got that error with goimports locally, but after I updated goimports it ran without error and gave the same output as gofmt.

**Comment by griesemer** [comment]
@cespare Indeed - thanks. This bug does exist in 1.7 (need to check 1.8). I believe this is an issue I have fixed a while back. We may need to update the playground.

**Comment by griesemer** [comment]
I believe this was fixed by https://go-review.googlesource.com/33016 .

**Comment by griesemer** [comment]
It looks like gofmt on the playground is not up-to-date. @broady ?

**Comment by broady** [comment]
It should be. It uses x/tools from the release branch. That CL should have made it in. I'll check.

**Comment by broady** [comment]
OK, this is a problem - App Engine is still on Go 1.6, and the playground imports `go/format` directly, which means we're stuck on Go 1.6's format package.

The best fix is probably to move the formatter from App Engine standard to the sandbox (which runs 1.8).

Other fixes:
* Vendor in the new formatter
* Move the entire frontend off App Engine standard.

**Comment by josharian** [comment]
Waiting for 1.8 on app engine seems sensible. This doesn't seem time-critical.

**Comment by bradfitz** [comment]
> Wait for 1.8 to be available on App Engine standard.

Moving off App Engine [standard] SGTM.

**Comment by bcmills** [comment]
> Wait for 1.8 to be available on App Engine standard.

Can this issue be fixed with a simple config change at this point?

Per https://cloud.google.com/appengine/docs/standard/go/release-notes#june_27_2017:
> This release adds beta support for `go1.8`. To use Go 1.8, set `api_version: go1.8` in your app.yaml configuration file.

**Comment by broady** [comment]
Yes, I'll re-deploy the playground tomorrow. Thanks for the ping.

**Comment by broady** [comment]
Done. Still correct to move everything off GAE standard.
