### ISSUE TITLE
go/runtime: go vet runtime output 174 errors messages and exit with code 1

### ISSUE THREAD

**Issue by wheelcomplex** [golang/go#19313]
I am sure that I'm not the first one found this.
Ian Lance Taylor told me to run go vet on the CL and make sure not report any additional errors.
Maybe worth to fire an issue.

Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

cd go/src/ && go vet runtime

#### What did you expect to see?

less output and exit with code 0

#### What did you see instead?

<pre>
runtime/atomic_pointer.go:57: possible misuse of unsafe.Pointer
runtime/cgocall.go:182: possible misuse of unsafe.Pointer
runtime/cgocall.go:256: possible misuse of unsafe.Pointer
runtime/cgocall.go:260: possible misuse of unsafe.Pointer
runtime/cgocall.go:265: possible misuse of unsafe.Pointer
runtime/cgocall.go:268: possible misuse of unsafe.Pointer
runtime/cgocall.go:271: possible misuse of unsafe.Pointer
runtime/cgocall.go:288: possible misuse of unsafe.Pointer
runtime/cgocall.go:292: possible misuse of unsafe.Pointer
runtime/cgocall.go:296: possible misuse of unsafe.Pointer
runtime/cgocall.go:335: possible misuse of unsafe.Pointer
runtime/cgocall.go:337: possible misuse of unsafe.Pointer
runtime/cgocall.go:584: possible misuse of unsafe.Pointer
runtime/cgocheck.go:22: possible misuse of unsafe.Pointer
runtime/hashmap.go:335: hash might be too small for shift of 56
runtime/hashmap.go:393: hash might be too small for shift of 56
runtime/hashmap.go:440: hash might be too small for shift of 56
runtime/hashmap.go:516: hash might be too small for shift of 56
runtime/hashmap.go:623: hash might be too small for shift of 56
runtime/hashmap.go:1026: hash might be too small for shift of 56
runtime/hashmap_fast.go:292: hash might be too small for shift of 56
runtime/hashmap_fast.go:399: hash might be too small for shift of 56
runtime/heapdump.go:220: possible misuse of unsafe.Pointer
runtime/heapdump.go:266: possible misuse of unsafe.Pointer
runtime/heapdump.go:271: possible misuse of unsafe.Pointer
runtime/heapdump.go:281: possible misuse of unsafe.Pointer
runtime/heapdump.go:326: possible misuse of unsafe.Pointer
runtime/heapdump.go:380: possible misuse of unsafe.Pointer
runtime/heapdump.go:418: possible misuse of unsafe.Pointer
runtime/heapdump.go:426: possible misuse of unsafe.Pointer
runtime/heapdump.go:429: possible misuse of unsafe.Pointer
runtime/heapdump.go:433: possible misuse of unsafe.Pointer
runtime/heapdump.go:436: possible misuse of unsafe.Pointer
runtime/heapdump.go:448: possible misuse of unsafe.Pointer
runtime/heapdump.go:485: possible misuse of unsafe.Pointer
runtime/lfstack_64bit.go:45: possible misuse of unsafe.Pointer
runtime/lfstack_64bit.go:47: possible misuse of unsafe.Pointer
runtime/malloc.go:292: uintptr(i) might be too small for shift of 40
runtime/malloc.go:294: uintptr(i) might be too small for shift of 40
runtime/malloc.go:296: uintptr(i) might be too small for shift of 40
runtime/malloc.go:298: possible misuse of unsafe.Pointer
runtime/malloc.go:339: possible misuse of unsafe.Pointer
runtime/malloc.go:395: possible misuse of unsafe.Pointer
runtime/malloc.go:416: possible misuse of unsafe.Pointer
runtime/malloc.go:424: possible misuse of unsafe.Pointer
runtime/malloc.go:429: possible misuse of unsafe.Pointer
runtime/malloc.go:435: possible misuse of unsafe.Pointer
runtime/malloc.go:456: possible misuse of unsafe.Pointer
runtime/malloc.go:470: possible misuse of unsafe.Pointer
runtime/malloc.go:477: possible misuse of unsafe.Pointer
runtime/malloc.go:640: possible misuse of unsafe.Pointer
runtime/malloc.go:653: possible misuse of unsafe.Pointer
runtime/malloc.go:676: possible misuse of unsafe.Pointer
runtime/malloc.go:678: possible misuse of unsafe.Pointer
runtime/malloc.go:689: possible misuse of unsafe.Pointer
runtime/mbitmap.go:159: possible misuse of unsafe.Pointer
runtime/mbitmap.go:366: possible misuse of unsafe.Pointer
runtime/mbitmap.go:603: possible misuse of unsafe.Pointer
runtime/mbitmap.go:611: possible misuse of unsafe.Pointer
runtime/mbitmap.go:612: possible misuse of unsafe.Pointer
runtime/mbitmap.go:644: possible misuse of unsafe.Pointer
runtime/mbitmap.go:648: possible misuse of unsafe.Pointer
runtime/mbitmap.go:696: possible misuse of unsafe.Pointer
runtime/mbitmap.go:697: possible misuse of unsafe.Pointer
runtime/mcache.go:65: possible misuse of unsafe.Pointer
runtime/mfinal.go:435: possible misuse of unsafe.Pointer
runtime/mfinal.go:437: possible misuse of unsafe.Pointer
runtime/mgcmark.go:1072: possible misuse of unsafe.Pointer
runtime/mgcmark.go:1174: possible misuse of unsafe.Pointer
runtime/mgcmark.go:1313: possible misuse of unsafe.Pointer
runtime/mgcsweep.go:240: possible misuse of unsafe.Pointer
runtime/mgcsweep.go:264: possible misuse of unsafe.Pointer
runtime/mgcsweep.go:267: possible misuse of unsafe.Pointer
runtime/mgcsweep.go:270: possible misuse of unsafe.Pointer
runtime/mgcsweep.go:344: possible misuse of unsafe.Pointer
runtime/mgcwork.go:40: possible misuse of unsafe.Pointer
runtime/mheap.go:364: possible misuse of unsafe.Pointer
runtime/mheap.go:431: possible misuse of unsafe.Pointer
runtime/mheap.go:632: possible misuse of unsafe.Pointer
runtime/mheap.go:700: possible misuse of unsafe.Pointer
runtime/mheap.go:822: possible misuse of unsafe.Pointer
runtime/mheap.go:839: possible misuse of unsafe.Pointer
runtime/mheap.go:983: possible misuse of unsafe.Pointer
runtime/netpoll.go:400: possible misuse of unsafe.Pointer
runtime/os_freebsd.go:97: possible misuse of unsafe.Pointer
runtime/panic.go:99: possible misuse of unsafe.Pointer
runtime/panic.go:101: possible misuse of unsafe.Pointer
runtime/panic.go:488: possible misuse of unsafe.Pointer
runtime/panic.go:504: possible misuse of unsafe.Pointer
runtime/plugin.go:75: possible misuse of unsafe.Pointer
runtime/plugin.go:76: possible misuse of unsafe.Pointer
runtime/proc.go:1579: possible misuse of unsafe.Pointer
runtime/proc.go:1607: possible misuse of unsafe.Pointer
runtime/proc.go:1614: possible misuse of unsafe.Pointer
runtime/proc.go:2879: possible misuse of unsafe.Pointer
runtime/proc.go:2884: possible misuse of unsafe.Pointer
runtime/proc.go:3021: possible misuse of unsafe.Pointer
runtime/proc.go:3024: possible misuse of unsafe.Pointer
runtime/runtime1.go:242: possible misuse of unsafe.Pointer
runtime/runtime1.go:244: possible misuse of unsafe.Pointer
runtime/runtime1.go:480: possible misuse of unsafe.Pointer
runtime/runtime1.go:483: possible misuse of unsafe.Pointer
runtime/runtime2.go:198: possible misuse of unsafe.Pointer
runtime/runtime2.go:219: possible misuse of unsafe.Pointer
runtime/runtime2.go:227: possible misuse of unsafe.Pointer
runtime/signal_amd64x.go:54: possible misuse of unsafe.Pointer
runtime/signal_amd64x.go:74: possible misuse of unsafe.Pointer
runtime/signal_amd64x.go:87: possible misuse of unsafe.Pointer
runtime/signal_amd64x.go:90: possible misuse of unsafe.Pointer
runtime/signal_unix.go:299: possible misuse of unsafe.Pointer
runtime/signal_unix.go:733: possible misuse of unsafe.Pointer
runtime/stack.go:221: possible misuse of unsafe.Pointer
runtime/stack.go:376: possible misuse of unsafe.Pointer
runtime/stack.go:397: possible misuse of unsafe.Pointer
runtime/stack.go:420: possible misuse of unsafe.Pointer
runtime/stack.go:605: possible misuse of unsafe.Pointer
runtime/stack.go:605: possible misuse of unsafe.Pointer
runtime/stack.go:669: possible misuse of unsafe.Pointer
runtime/stack.go:685: possible misuse of unsafe.Pointer
runtime/stack.go:692: possible misuse of unsafe.Pointer
runtime/stack.go:716: possible misuse of unsafe.Pointer
runtime/stack.go:767: possible misuse of unsafe.Pointer
runtime/stack.go:818: possible misuse of unsafe.Pointer
runtime/stack.go:818: possible misuse of unsafe.Pointer
runtime/stack.go:883: possible misuse of unsafe.Pointer
runtime/stack.go:883: possible misuse of unsafe.Pointer
runtime/stack.go:1084: possible misuse of unsafe.Pointer
runtime/stack.go:1086: possible misuse of unsafe.Pointer
runtime/stubs.go:128: possible misuse of unsafe.Pointer
runtime/symtab.go:284: possible misuse of unsafe.Pointer
runtime/symtab.go:285: possible misuse of unsafe.Pointer
runtime/symtab.go:462: possible misuse of unsafe.Pointer
runtime/sys_x86.go:20: possible misuse of unsafe.Pointer
runtime/sys_x86.go:23: possible misuse of unsafe.Pointer
runtime/trace.go:162: possible misuse of unsafe.Pointer
runtime/trace.go:343: possible misuse of unsafe.Pointer
runtime/trace.go:704: possible misuse of unsafe.Pointer
runtime/trace.go:861: possible misuse of unsafe.Pointer
runtime/traceback.go:180: possible misuse of unsafe.Pointer
runtime/traceback.go:183: possible misuse of unsafe.Pointer
runtime/traceback.go:253: possible misuse of unsafe.Pointer
runtime/traceback.go:258: possible misuse of unsafe.Pointer
runtime/traceback.go:349: possible misuse of unsafe.Pointer
runtime/traceback.go:406: possible misuse of unsafe.Pointer
runtime/traceback.go:530: possible misuse of unsafe.Pointer
runtime/type.go:180: possible misuse of unsafe.Pointer
runtime/type.go:235: possible misuse of unsafe.Pointer
runtime/type.go:292: possible misuse of unsafe.Pointer
runtime/type.go:490: possible misuse of unsafe.Pointer
runtime/type.go:512: possible misuse of unsafe.Pointer
runtime/asm_amd64.s:376: [amd64] morestack: use of 8(SP) points beyond argument frame
runtime/asm_amd64.s:378: [amd64] morestack: use of 16(SP) points beyond argument frame
runtime/asm_amd64.s:388: [amd64] morestack: use of 8(SP) points beyond argument frame
runtime/asm_amd64.s:421: [amd64] cannot check cross-package assembly function: call is in package reflect
runtime/asm_amd64.s:808: [amd64] stackcheck: function stackcheck missing Go declaration
runtime/asm_amd64.s:880: [amd64] aeshashbody: function aeshashbody missing Go declaration
runtime/asm_amd64.s:1356: [amd64] memeqbody: function memeqbody missing Go declaration
runtime/asm_amd64.s:1481: [amd64] cannot check cross-package assembly function: Compare is in package bytes
runtime/asm_amd64.s:1495: [amd64] cmpbody: function cmpbody missing Go declaration
runtime/asm_amd64.s:1696: [amd64] cannot check cross-package assembly function: supportAVX2 is in package strings
runtime/asm_amd64.s:1701: [amd64] cannot check cross-package assembly function: supportAVX2 is in package bytes
runtime/asm_amd64.s:1706: [amd64] cannot check cross-package assembly function: indexShortStr is in package strings
runtime/asm_amd64.s:1716: [amd64] cannot check cross-package assembly function: indexShortStr is in package bytes
runtime/asm_amd64.s:1730: [amd64] indexShortStr: function indexShortStr missing Go declaration
runtime/asm_amd64.s:1976: [amd64] cannot check cross-package assembly function: IndexByte is in package bytes
runtime/asm_amd64.s:1983: [amd64] cannot check cross-package assembly function: IndexByte is in package strings
runtime/asm_amd64.s:1995: [amd64] indexbytebody: function indexbytebody missing Go declaration
runtime/asm_amd64.s:2117: [amd64] cannot check cross-package assembly function: Equal is in package bytes
runtime/asm_amd64.s:2174: [amd64] addmoduledata: function addmoduledata missing Go declaration
runtime/duff_amd64.s:7: [amd64] duffzero: function duffzero missing Go declaration
runtime/duff_amd64.s:106: [amd64] duffcopy: function duffcopy missing Go declaration
runtime/sys_freebsd_amd64.s:279: [amd64] settls: function settls missing Go declaration
exit status 1
runtime/runtime_test.go:164: possible misuse of unsafe.Pointer
exit status 1
</pre>

#### Does this issue reproduce with the latest release (go1.8)?

yes, two lines+:

<pre>
runtime/cpuprof.go:218: h might be too small for shift of 56
runtime/sys_freebsd_amd64.s:146: [amd64] cannot check cross-package assembly function: now is in package time
</pre>

#### System details

```
go version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 freebsd/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/david/home/sandspace/extpkg/"
GORACE=""
GOROOT="/home/david/home/sandspace/go"
GOTOOLDIR="/home/david/home/sandspace/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build204404833=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="0"
CGO_CFLAGS="-gdwarf-4"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 freebsd/amd64
GOROOT/bin/go tool compile -V: compile version devel +4b2248527f Sun Feb 26 23:36:09 2017 +0000 X:framepointer
uname -v: FreeBSD 11.0-STABLE #73 9364f2f79a1(stable11): Mon Feb 27 16:42:29 NZDT 2017     root@david-n550jk.localdomain:/tank/cross/obj/amd64/home/david/sandspace/private-freebsd/sys/PREINIT-DEBUG
lldb --version: lldb version 3.8.0 clang revision 262564
gdb --version: GNU gdb 6.1.1 [FreeBSD]
```

**Comment by kevinburke** [comment]
I believe @josharian has been spearheading fixing/whitelisting vet errors in the standard library.

**Comment by josharian** [comment]
Yep. See cmd/vet/all, do 'go run main.go'. I'm still working with Brad to get this up on the trybots/builders—soon I hope—but it can be run manually in the meantime if desired. Fair warning: if run with -all, it takes minutes, maxes out your CPU, and drains your battery.
