### ISSUE TITLE
tls: first record does not look like a TLS handshake when connecting over ssl

### ISSUE THREAD

**Issue by Anoopgithub123** [golang/go#19317]
@freeformz @evanphx @bmizerany @uggedal @benburkert 
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.5 darwin

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/workspace/GO_CODE"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5g/xv46lbz53b73lpr3wjfqc9h00000gn/T/go-build665777701=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
I am trying to connect to kafka server which is enabled with ssl. I have created the tls configuration with necessary certs. But it fails with the error tls: first record does not look like a TLS handshake.
The same thing works with python client but not with go client.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
A successful handshake.

### What did you see instead?

tls: first record does not look like a TLS handshake.

**Comment by bradfitz** [comment]
Maybe your Kafka server is doing STARTTLS instead of TLS straight away.

In any case, there's not enough information in this bug report to help. This is almost certainly a configuration problem of some sort.

**Comment by evanphx** [comment]
Why did 5 of us get randomly ping'd at the start of this issue...?

**Comment by bradfitz** [comment]
Evan, good question. I'm going to close this.
