### ISSUE TITLE
misc/cgo/testcarchive: TestSIGPROF flakes with "signal: profiling timer expired"

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#19320]
I see this test failure from a trybot, in https://storage.googleapis.com/go-build-log/f8d7aae9/darwin-amd64-10_11_578453d9.log.

    ##### ../misc/cgo/testcarchive
    --- FAIL: TestSIGPROF (1.40s)
    	carchive_test.go:591: 
    	carchive_test.go:592: signal: profiling timer expired
    FAIL
    2017/02/28 07:44:16 Failed: exit status 1

**Comment by josharian** [comment]
Again just now, same message: https://storage.googleapis.com/go-build-log/bb8472a0/darwin-amd64-10_11_2bd97160.log

**Comment by crawshaw** [comment]
I see this once every ~200 runs of `go test -run=TestSIGPROF carchive_test.go`.

What I think may be happening:
- thread A has a pending SIGPROF
- thread B calls `setcpuprofilerate(0)` which turns off further SIGPROFs with `setitimer`, and then removes the handler using a special code path just for c-archive/c-shared
- thread A tries to deal with SIGPROF, and the default handler terminates the program.

If this is so, then I don't see a way to uninstall the SIGPROF handler.

https://golang.org/cl/42830 leaves the handler installed once it is installed. That's enough to fix the test, over several thousand runs. Is this good enough? Should we also forward SIGPROF in this case?

**Comment by bradfitz** [comment]
Kicking to Go 1.10.

@bcmills, feel free to take it over (soon) if you think this is important for Go 1.9.

**Comment by shurcooL** [comment]
It looks like this intermittent trybot failure masked a real failure in [CL 60530](https://golang.org/cl/60530), causing #21783.

**Comment by mvdan** [comment]
Happened on a freebsd-amd64-12_0 trybot run: https://farmer.golang.org/temporarylogs?name=freebsd-amd64-12_0&rev=f424e02578b25cb81ab055a6bd39e86b1f37855a&st=0xc455410000

```
##### ../misc/cgo/testcarchive
--- FAIL: TestSIGPROF (1.45s)
    carchive_test.go:670: 
    carchive_test.go:671: signal: profiling timer expired
FAIL
2019/03/22 12:26:23 Failed: exit status 1
```

**Comment by bcmills** [comment]
Another `freebsd-amd64-12_0`: https://build.golang.org/log/a3ac872ca62295e007cab9463a19c0f309a7b69b

**Comment by odeke-em** [comment]
@ianlancetaylor @bcmills, David Crawshaw seems very busy and had submitted CL https://go-review.googlesource.com/c/go/+/42830 which has been open for more than 2 years. Could someone please take over that CL giving him credit, we can submit the newly created one and abandon his old CL.

**Comment by bcmills** [comment]
I don't have the bandwidth to take this on at the moment, but if someone wants to make a run at this I could probably at least find the time to review a fix.

**Comment by bcmills** [comment]
`freebsd-amd64-12_0` TryBot again: https://storage.googleapis.com/go-build-log/51dfc8a7/freebsd-amd64-12_0_d1376bb9.log
