### ISSUE TITLE
crypto: use the named aliases crypto.PrivateKey and crypto.PublicKey as return types in sub-package APIs rather than bare interface{}

### ISSUE THREAD

**Issue by andrewmbenton** [golang/go#19328]
For clarity, it would be nice to have funcs like ```x509.ParsePKIXPublicKey(derBytes []byte) (pub interface{}, err error)``` and ```x509.ParsePKCS8PrivateKey(der []byte) (key interface{}, err error)``` return the named aliases ```crypto.PublicKey``` and ```crypto.PrivateKey``` rather than just ```interface{}```.

There are other spots in the crypto packages that could probably benefit from this as well. I'm wondering if there's a reason not to do this?

I have a simple patch that updates these APIs with all tests passing that I'd be happy to submit.

**Comment by cespare** [comment]
Unfortunately, this is a backwards-incompatible change that's forbidden by the [Go 1 compatibility promise](https://golang.org/doc/go1compat).

**Comment by andrewmbenton** [comment]
I read that document before submitting which almost prevented me from suggesting this. But it isn't exactly clear to me.

Is it really breaking an API compatibility rule to replace an empty interface return type with an alias to an empty interface? I couldn't see a specific way that this change would break any existing Go programs. But maybe I just wasn't thinking hard enough?

**Comment by cespare** [comment]
For example this program won't compile after your change:

https://play.golang.org/p/zcDwTjQkPx

**Comment by andrewmbenton** [comment]
Good point. Thanks for the guidance. Something to keep in mind for a possible go2 API refactor.
