### ISSUE TITLE
cmd/vet: switch to new srcimporter

### ISSUE THREAD

**Issue by josharian** [golang/go#19332]
Go 1.9 has a new source-based importer. I'd like to switch cmd/vet to it. This will resolve a host of open issues.

It should also make cmd/vet/all a lot faster, which would be good, since @bradfitz is a bit concerned about kubernetes CPU capacity at the moment.

cc @robpike @griesemer @valyala

**Comment by griesemer** [comment]
I'd like to complete this work first; i.e., also implement an "gc/auto" importer which automatically decides whether to use installed packages or source (whichever is newer). And then make this "auto" importer the default importer. As a consequence, programs that just use the default importer wouldn't have to change at all.

Any objections?

**Comment by josharian** [comment]
Sounds great.

**Comment by myitcv** [comment]
@josharian 

> It should also make cmd/vet/all a lot faster

I might be missing something here, but won't it do the opposite? i.e. make `cmd/vet` run slower?

**Comment by josharian** [comment]
See the numbers in https://go-review.googlesource.com/c/37691/.

cmd/vet/all currently has to do 'go install' in order to typecheck the files, which invokes cmd/compile, which is (unsurprisingly) heavier-weight than go/types. For cases in which the relevant packages have already been compiled, using the installed object files will be faster. That will remain the default for cmd/vet.

**Comment by myitcv** [comment]
Thanks for the link: I understand the context now.

> For cases in which the relevant packages have already been compiled, using the installed object files will be faster. 

That's what I was getting at. My concern here was that for situations where packages are up to date there would be a needless hit by vet being moved over to the source importer (the exact use case of the "auto" importer)

> ... That will remain the default for cmd/vet.

Thanks for clarifying.
