### ISSUE TITLE
runtime: convT2E called for function value 

### ISSUE THREAD

**Issue by cstockton** [golang/go#19335]
Go 1.8 amd64 linux when running the below program `convT2E` is called for `BenchmarkEfaceFnVal` but not for `BenchmarkEfaceFn`.

**Program:**
```Go
package main

import "testing"

func efaceFn(v interface{}) {
	return
}

func BenchmarkEfaceFnVal(b *testing.B) {
	b.ReportAllocs()

	efaceFnVal := efaceFn
	for i := 0; i < b.N; i++ {
		efaceFnVal(0x1)
	}
}

func BenchmarkEfaceFn(b *testing.B) {
	b.ReportAllocs()

	for i := 0; i < b.N; i++ {
		efaceFn(0x1)
	}
}
```

**Result:**

| Name | Iterations | ns/op | B/op | allocs/op |
| -- | -- | -- | -- | -- |
| BenchmarkEfaceFnVal-24 | 20000000 | 60.8 ns/op | 8 B/op | 1 allocs/op |
| BenchmarkEfaceFn-24 | 2000000000 | 0.48 ns/op | 0 B/op | 0 allocs/op |

**Comment by randall77** [comment]
This is fixed at tip.

In `BenchmarkEfaceFn`, the call gets inlined and the conversion get compiled completely away.

In `BenchmarkEfaceFnVal`, the call still has to happen (we have no devirtualization of calls at the moment), but the conversion to interface now happens statically at compile time.

```
BenchmarkEfaceFnVal-8   	1000000000	         2.33 ns/op	       0 B/op	       0 allocs/op
BenchmarkEfaceFn-8      	2000000000	         0.52 ns/op	       0 B/op	       0 allocs/op
```

**Comment by cstockton** [comment]
@randall77 Sorry I didn't check tip first, should have, thanks for the quick response
