### ISSUE TITLE
cmd/go: -gcflags and cached packages

### ISSUE THREAD

**Issue by aarzilli** [golang/go#19340]
[Delve](https://github.com/derekparker/delve/) builds its binaries using `-gcflags='-N -l'` to disable inlining and optimizations. This works well until the user separately does a `go install` or a `go build -i` at which point any subsequent build will pick up the cached version of all unchanged dependencies, built with optimizations turned on, leading to [surprising behavior](https://github.com/derekparker/delve/issues/738).

Attempting to circumvent this problem by passing `-a` to build fail because of #18774.

Considering that #18774 has existed for a while (the first reference I found is #12055) would it be possible to make build pick up cached packages only when compiler flags match, making an exception for runtime?

**Comment by ALTree** [comment]
This looks like a dup of the discussion in issue #14319, in particular [this comment](https://github.com/golang/go/issues/14319#issuecomment-260449589) about making `-N` part of the build signature:

> There's also the question of what should happen if you mix packages compiled with and without -N and whether -N should be part of the build signature. I think it's safe to mix packages as long as there are no "go:nosplit" functions in the user packages (auto-nosplit should be fine, since their bound is small and fixed) and user code can't directly call nosplit runtime functions with large frames (which I think is true). That's a lot of "if"s, and it's also strange that the same build command can result in different binaries depending on which packages are clean. To me, this indicates -N should be part of the build signature. I'm not sure if we do that for other flags.

**Comment by aarzilli** [comment]
That comment wouldn't fully solve the problem however, even if build didn't mix packages built with and without -N it still couldn't build runtime with -N.

**Comment by josharian** [comment]
Related (possible dup?): #18369

**Comment by rsc** [comment]
Work on better caching will fix this. I have a prototype. Not for Go 1.9 but probably for Go 1.10.

**Comment by aarzilli** [comment]
Great, thank you. I should mention that last week I've discovered that on tip now I can build with both `-a` and `-gcflags="-N -l"` together, which provides a workaround for this problem.

**Comment by jiebanghan** [comment]
# This Makefile is meant to be used by people that do not usually work
# with Go source code. If you know what GOPATH is then you probably
# don't need to bother with make.

.PHONY: geth android ios geth-cross evm all test clean
.PHONY: geth-linux geth-linux-386 geth-linux-amd64 geth-linux-mips64 geth-linux-mips64le
.PHONY: geth-linux-arm geth-linux-arm-5 geth-linux-arm-6 geth-linux-arm-7 geth-linux-arm64
.PHONY: geth-darwin geth-darwin-386 geth-darwin-amd64
.PHONY: geth-windows geth-windows-386 geth-windows-amd64

GOBIN = build/bin
GO ?= latest

geth:
        build/env.sh go run  build/ci.go  install ./cmd/geth
        @echo "Done building."
        @echo "Run \"$(GOBIN)/geth\" to launch geth."


how to modify the makefile above in order to show the variable?
