### ISSUE TITLE
html/template: predefined HTML escaper does not properly escape user input

### ISSUE THREAD

**Issue by stjj89** [golang/go#19345]
**version**: go version devel +4cce27a3fa Sat Jan 21 03:20:55 2017 +0000 linux/amd64
**env**: linux amd64

When we have
```
.X = `haha onclick=evil()`,
```
The following template
```
<a title={{.X}}>
```
evaluates to
```
<a title=haha&#32;onclick&#61;evil()>
```
which is properly escaped. However, the following template:
```
<a title={{.X | html}}>
```
evaluates to
```
<a title=haha onclick=evil()>
```
which is improperly escaped, and insecure.

This is happening because the html/template escaper considers the predefined global `html` function equivalent to its internal `_html_template_nospaceescaper` escaping directive. Since the former is already present in the pipeline, it does not insert the latter to prevent over-escaping (see original commit of this behavior [here](https://github.com/golang/go/commit/ce008f8c37e07190a27368f6e546617a40267fd1)). However, the above example shows that these two escaping functions are not equivalent.

We should thoroughly re-evaluate the [equivalency of predefined global escapers to internal escapers](https://github.com/golang/go/blob/master/src/html/template/escape.go#L66), or get rid of this logic entirely. If we go with the latter option, we could consider removing all user-supplied escapers before adding internal escaper directives, in order to prevent over-escaping.

See related issue [19336](https://github.com/golang/go/issues/19336) for another security issue related to this equivalent-escapers logic.

**Comment by mikesamuel** [comment]
nice catch!

> We should thoroughly re-evaluate the equivalency of predefined global escapers
> to internal escapers

> or get rid of this logic entirely. If we go with the latter option, we could consider
> removing all user-supplied escapers before adding internal escaper directives,
> in order to prevent over-escaping.

So 

```html
<a title={{.X | html}}>
```

would become

```html
<a title={{.X | htmlAttrNospace}}>
```

it seems that removing equivalents and upgrading sounds fine.


I'm a little leery of this in one instance

```html
<iframe srcdoc="{{.X | html | htmlAttr}}">
```

is semantically quite different from

```html
<iframe srcdoc="{{.X | htmlAttr}}">
```

**Comment by stjj89** [comment]
>  I'm a little leery of this in one instance
> ```
> <iframe srcdoc="{{.X | html | htmlAttr}}">
> ```
> is semantically quite different from
> ```
> <iframe srcdoc="{{.X | htmlAttr}}">
> ```

If I understand correctly, and `htmlAttr` refers to the [internal `_html_template_attrescaper` directive](https://github.com/golang/go/blob/master/src/html/template/escape.go#L49), then the scenario you highlighted won't ever occur. `_html_template_attrescaper` is hidden from the user, so the user can only call `html`. In my proposed solution, both
```html
<iframe srcdoc="{{.X | html}}">
```
and
```html
<iframe srcdoc="{{.X}}">
```
will be rewritten to
```html
<iframe srcdoc="{{.X | _html_template_attrescaper}}">
```
where in the former case, we remove the `html` directive before adding `_html_template_attrescaper`.

**Comment by bradfitz** [comment]
To @rsc for review.

**Comment by stjj89** [comment]
This is no longer an issue now that golang.org/cl/37880 has landed.

**Comment by stjj89** [comment]
I took a closer look at this, and determined that `html` and `_html_template_nospaceescaper` are not functionally different; the rest of the functions in the [equivEscapers](https://github.com/golang/go/blob/d2315fdc11ebdf5c0ae94f33cb01ffaab82c00b6/src/html/template/escape.go#L66) should be safe to use interchangeably.
