### ISSUE TITLE
encoding/base64: encoding doesn't support every possible alphabet

### ISSUE THREAD

**Issue by josselin-c** [golang/go#19343]
### What version of Go are you using (`go version`)?
Go 1.8

### What did you expect to see?
Some alphabets accepted by encoding/base64 NewEncoding cannot be decoded: alphabets containing "\n", "\r" or padChar.
See: https://play.golang.org/p/fNJfbH3QgA

Maybe NewEncoding documentation could state that we don't support theses cases or we should fix our implementation.

**Comment by ianlancetaylor** [comment]
We could have `NewEncoding` check for and reject `\n` or `\r`.  I don't see any way to handle `padChar` other than documentation, since one can call `WithPadding` after calling `NewEncoding`.
