### ISSUE TITLE
crypto: Remove redundant internal struct x509.rsaPublicKey and replace references with rsa.PublicKey

### ISSUE THREAD

**Issue by andrewmbenton** [golang/go#19355]
Just proposing a simple change to remove the apparently redundant ```x509.rsaPublicKey``` internal struct that's used in two places, preventing future accidental use.

I have a simple patch to submit and all tests pass.

**Comment by bradfitz** [comment]
I don't think it does any harm keep it as-is. In fact, it's defensive: it's documented as being the asn.1 structure, whereas the other one could have fields added or reordered safely and is the one for users.

**Comment by andrewmbenton** [comment]
Perhaps true. I had thought that its use was somewhat idiosyncratic, but it appears to be used only twice, in calls to asn1.Marshal(...) and asn1.Unmarshal.

So perhaps moving it into the asn1 package and possibly renaming it would better indicate its intended use?

**Comment by bradfitz** [comment]
We don't put the http2 encoder and decoder in the bytes package just because it's eventually encoded as bytes. I don't see why the asn1 package should contain anything about RSA or x509 or anything else that uses asn.1.

The layering seems good as it is. Closing, but feel free to argue otherwise.

**Comment by andrewmbenton** [comment]
Good point RE not including higher-level structs in codec packages. Wasn't thinking clearly on that.

I'd suggest finally then that the struct in question be renamed ```pkcs1PublicKey``` for consistency with the other ASN.1-compliant named types in the package (which I had missed before) and it should be moved to the top of ```x509/pkcs1.go``` with the other type declarations.

One of the reasons this was confusing to me was probably that it was just hanging out all alone down there at the bottom of the file.

Not going to argue too hard for this though. Handle as you see fit and thanks for taking the time to discuss. Easy enough for me to submit the CL if so desired.
