### ISSUE TITLE
cmd/internal/obj: wrong binary generated for TST instruction by the ARM assembler

### ISSUE THREAD

**Issue by benshi001** [golang/go#19357]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
the newest go master branch

### What operating system and processor architecture are you using (`go env`)?
GOARCH=arm
GOOS=linux

### What did you do?
test the arm assembler

### If possible, provide a recipe for reproducing the error.
Wrong 4-byte word assembled

TST     $255, R7: have encoding 000050e3, want ff0017e3
TST     $4278190080, R9: have encoding 000050e3, want ff0419e3
TST     R9<<30, R7: have encoding 000050e3, want 090f17e1
TST     R9>>30, R7: have encoding 000050e3, want 290f17e1
TST     R9->30, R7: have encoding 000050e3, want 490f17e1
TST     R9@>30, R7: have encoding 000050e3, want 690f17e1
TST     R9<<R8, R7: have encoding 000050e3, want 190817e1
TST     R9>>R8, R7: have encoding 000050e3, want 390817e1
TST     R9->R8, R7: have encoding 000050e3, want 590817e1
TST     R9@>R8, R7: have encoding 000050e3, want 790817e1

**Comment by benshi001** [comment]
All variants of TST are encoded to the same 000050e3. Actually TST have 3 different forms as CMP/CMN/TEQ have.

**Comment by benshi001** [comment]
I have committed a patch to fix this issue.

https://go-review.googlesource.com/#/c/37662/

**Comment by ALTree** [comment]
@benshi001 when filing issues, please start the title with the package path and a colon (in this case, "cmd/internal/obj:"). Thanks!

**Comment by benshi001** [comment]
OK. I learn it.  ^_^

**Comment by benshi001** [comment]
B is also wrongly assembled, I have reported in another #19419.
