### ISSUE TITLE
x/net/proxy: does not support dialing with a given Context

### ISSUE THREAD

**Issue by walken-google** [golang/go#19354]
The x/net/proxy package doesn't support dialing a proxy with a given Context.

This also impacts the net/http package because a Client can dial through a socks5 proxy if specified (usualy through ProxyFromEnvironment). If the socks5 proxy blocks before connecting the socket, the http Client could get stuck without a way to abort the connection by cancelling a Context.

**Comment by walken-google** [comment]
The net/http use of socks5 proxy is new in master - wasn't present in go 1.8 - sorry I forgot to mention that in the initial comment.

**Comment by mikioh** [comment]
From Go 1.11, the net/http package supports SOCKS dialing with contexts. This issue is just for the x/net/proxy package.

**Comment by mjgarton** [comment]
I updated the CL at https://go-review.googlesource.com/c/net/+/37641 to address this.

The required change is now much simpler, thanks to the new internal socks package that already supports Contexts, but the issue of full backwards compatibility still needs a definitive decision it seems.

**Comment by GongT** [comment]
What about `net.Dialer` ?
```golang
var d net.Dialer
d.DialContext(ctx, network, address)
```
