### ISSUE TITLE
go/types: parameterize SizesFor?

### ISSUE THREAD

**Issue by josharian** [golang/go#19351]
[CL 37583](https://golang.org/cl/37583/) added types.SizesFor. I'm delighted to see it.

If we add a GCSizes (#17586), will we need to also add a GCSizesFor? Do we want to parameterize SizesFor in some way to anticipate that change?

cc @griesemer @alandonovan

**Comment by griesemer** [comment]
I'm ok with adding a compiler parameter
```
func SizesFor(compiler string) Sizes
```
such that if the compiler is not recognized, it's some sensible default (perhaps what we have now). I would also be ok with just having SizesFor return the GC compiler's sizes (meaning underneath we'd do some extra work to match that).

But perhaps adding a compiler argument is the most future-proof and flexible approach. Comments?
