### ISSUE TITLE
x/build: make solaris/smartos builders use a tmpfs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19368]
The I/O performance on our Solaris builders seems slow.

(I just did a gomote push of a 42 MB tar.gz and it took much longer than I'm used to for it to unpack remotely.)

Investigate how to do a tmpfs-sorta thing on Solaris for its ephemeral $WORKDIR.

/cc @4ad

**Comment by binarycrusader** [comment]
/tmp is always the ram-backed filesystem on Solaris (tmpfs): http://www.c0t0d0s0.org/archives/5815-Less-known-Solaris-features-The-curious-case-of-the-tmp-in-Solaris.html

/var/tmp is the persistent-storage-backed filesystem on Solaris (typically ZFS).

For other custom uses, see 'man tmpfs' or here:

https://docs.oracle.com/cd/E53394_01/html/E54785/fscreate-34114.html

**Comment by bradfitz** [comment]
Our Joyent builder no longer exists, so closing.
