### ISSUE TITLE
Publish statically linked go binary

### ISSUE THREAD

**Issue by mcandre** [golang/go#19365]
I'm trying to install Go 1.7.5 on Alpine from the official binary tarball. However, `file` shows that this binary is dynamically linked to `/lib64/ld-linux-x86-64.so.2` (glibc), which makes it difficult to run this binary on embedded Linux systems.

Perhaps Go could publish these binaries as statically linked?

Perhaps Go could publish musl-linked binaries in addition to glibc-linked binaries?

**Comment by ALTree** [comment]
Thanks for the report. 

This is a dup of #18773 [Official Go binary does not work in Alpine Linux (not statically linked)], where they're asking pretty much the same thing:

> we thought it would be good to have a statically-linked binary available

You are also suggesting another alternative (publish musl-linked binaries), but I think it would be better to keep all the discussion related to this issue on #18773; so I'm closing this. Feel free to write about publishing musl-linked bins on that issue.
