### ISSUE TITLE
x/mobile: Failed to build aar when updated to golang1.8

### ISSUE THREAD

**Issue by XanthusL** [golang/go#19377]
### GOOS="darwin"

Tried to build [primitive](https://github.com/fogleman/primitive) to Android SDK app
'gomobile' finished with non-zero exit value 1

gomobile: loadExportData failed reading export data: /var/.../primitive.a: invalid encoding format in export data: got 'v'; want 'c' or 'd'

Then I tested with a hello-world-project created which was OK, failed too.

**Comment by themihai** [comment]
I've got the same error on iOS `gomobile: reading export data: /var/folders/96/xn9qmts104s1mcdqg31s66lh0000gn/T/gomobile-work-670052359/fakegopath/pkg/darwin_arm/bitbucket.org/themihai/tv/remote.a: invalid encoding format in export data: got 'v'; want 'c' or 'd'
`

**Comment by themihai** [comment]
go get -u golang.org/x/mobile/...
go install golang.org/x/mobile/cmd/...
Fixed the issue for me.
