### ISSUE TITLE
golang.org: pop out link on sample code page shows error dialog box

### ISSUE THREAD

**Issue by davecheney** [golang/go#19373]
Reported on twitter

https://twitter.com/ZahoOnIT/status/837410479941300225

Confirmed locally

![screen shot 2017-03-03 at 08 34 37](https://cloud.githubusercontent.com/assets/7171/23528030/63bc054c-ffec-11e6-9fcd-56065d506fb7.png)

/cc @broady

**Comment by AlekSi** [comment]
Error in console:
> Failed to load resource: the server responded with a status of 451 (HTTP/2.0 451) https://golang.org/share

**Comment by broady** [comment]
Ah, that's a bummer. Need to do region checking for the homepage.

At the very least, show a better error message for 451.

**Comment by broady** [comment]
Fixed (I cherry-picked 37881 into production while it's still pending).

**Comment by bradfitz** [comment]
@broady, status here? Is that minus-twoed CL still in production?

**Comment by broady** [comment]
It is, but it needn't be.

I'll remove the cherry-pick in the (currently internal) deployment script and abandon CL 37881 after I verify the underlying cause has been fixed.
