### ISSUE TITLE
strings.Trim sometimes trims incorrectly

### ISSUE THREAD

**Issue by asCii88** [golang/go#19371]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH=amd64

### What did you do?
I run this
```
aux := "PW/V2/C2/RQ/CMD/45465/44545"
fmt.Println(strings.Trim(aux, "PW/V2/C2/RQ/"))
```
[Playground](https://play.golang.org/p/G9BUTZpgNv)

### What did you expect to see?
Output should be CMD/45465/44545

### What did you see instead?
Output is MD/45465/44545

**Comment by cespare** [comment]
The second argument to Trim is a set of code points, not a prefix/suffix.

You probably want strings.TrimPrefix.

**Comment by asCii88** [comment]
Thank you, sorry.

Best way to get an answer on the Internet is to be wrong :)

**Comment by ianlancetaylor** [comment]
This mistake is practically a FAQ.  Perhaps we can clarify the docs somehow.

**Comment by bradfitz** [comment]
The docs at least say "cutset" these days:

https://golang.org/pkg/strings/#Trim

And there's an example that says **!!! Achtung! Achtung! !!!** which is only more alarming when it's shouted at you verbally.

**Comment by davecheney** [comment]
I offer that people don't know what cutset means, and are left to assume
that it means "fancy word for the string I want to trim off".

**Comment by bradfitz** [comment]
Dave, totally agree. I was only saying it used to be even worse. :)

**Comment by davecheney** [comment]
No argument there, mind if I take a stab at improving it?

**Comment by bradfitz** [comment]
🔪🔪🔪 stab away

**Comment by asCii88** [comment]
Yep, exactly. I Googled code points and I didn't even think about cutset.
I still have no idea what it does after seeing the example. I would assume it just cuts each time it finds the other string. 
Then again, I was trying at first with TrimLeft, and didn't realize there was a TrimPrefix.

**Comment by golang101** [comment]
http://www.tapirgames.com/blog/golang-unofficial-faq#trim :-)
