### ISSUE TITLE
time: Update tzdata to IANA release 2017b (March 2017)

### ISSUE THREAD

**Issue by SrihariThalla** [golang/go#19376]
Announcement: http://mm.icann.org/pipermail/tz-announce/2017-March/000046.html

Thanks!

**Comment by robpike** [comment]
These usually get updated as a release approaches.

**Comment by ALTree** [comment]
Note: whoever updates the vendored tzdata package will need to update the `TestFirstZone` test, which uses the vendored zip (instead of the system data) and I've verified fails with anything `>= tzdata-2017a` due to a timezones data update. 

Or can ping me and I'll do it.

**Comment by SrihariThalla** [comment]
`2017b` is just released.

Announcement - http://mm.icann.org/pipermail/tz-announce/2017-March/000046.html
