### ISSUE TITLE
How Build New Golang Console App in a Main Go App?

### ISSUE THREAD

**Issue by questionpython** [golang/go#19382]
Hello,Go Team.

How Build New Golang Console App in a Main Go App? mean on a system without go compilers with main app.

example :
>
`$go build main.go` //this is main app (i dont know how make this!)
`./main file.go`

and after this , build file.go and save as `file`.
## if can not,  available portable version of go?

http://stackoverflow.com/questions/42473834/how-build-new-golang-console-app-in-a-main-go-app

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
