### ISSUE TITLE
Sending from channel to channel isn't possible

### ISSUE THREAD

**Issue by purpleidea** [golang/go#19387]
It seems that sending directly from one channel to another isn't possible. Ref: https://golang.org/ref/spec#Select_statements

For example:

```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("Hello, playground")
	ch1 := make(chan error)
	ch2 := make(chan error)
	go func() {
		ch2 <- nil
		fmt.Println("sent to ch2")
	}()
	go func() {
		time.Sleep(time.Second * 3)
		<-ch1
		fmt.Println("received from ch1")
	}()
	select {
	// TODO: how to detect if stringChan is closed?
	case ch1 <- <-ch2: // recv and send
		fmt.Println("w00t")
	}
}
```

This is possible, but it has a major problem:
You actually receive from ch2 BEFORE ch1 is necessarily ready.
As a result, you can't maintain the backpressure on ch2 if that's an important signal!

I think this is something that should be possible in golang.
Cheers

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by purpleidea** [comment]
@bradfitz It's not a question, it's a RFE.

**Comment by purpleidea** [comment]
(spends time formulating a nicely phrased problem with golang including a code example, gets a quick close! -- wooo community!)

**Comment by groob** [comment]
@purpleidea https://invite.slack.golangbridge.org/ and the mailing list are both great places for discussing things like this, and these sort of discussions happen all the time. 

PS: I'm a mgmt fan!

**Comment by bradfitz** [comment]
Sorry, it looked like the typical Go questions we get here often.

The nicely phrased problem and code example can be copy/pasted into a more appropriate forum. They're not destroyed.

In any case, the language is pretty frozen at this point. If you're interested in making a formal proposal for consideration for Go2, see https://golang.org/s/proposal

**Comment by purpleidea** [comment]
@groob We'd have to have you as a contributor! Come join us in #mgmtconfig on Freenode IRC :)

@bradfitz That's okay-- indeed I would expect it to be a golang 2.x thing. The runtime would have to facilitate the sort of synchronization to both unblock the sender and receiver at the same time. I think it would be quite beneficial for glueing together different API's. If you like the idea and can run with it, please LMK. Happy to discuss further, just ping. Cheers

**Comment by bradfitz** [comment]
@purpleidea, I'll at least flag this bug as Go2 for consideration later.
