### ISSUE TITLE
gofmt formats differently similar slicings

### ISSUE THREAD

**Issue by udhos** [golang/go#19385]
### What version of Go are you using (`go version`)?

$ go version
go version go1.8 linux/386

### What operating system and processor architecture are you using (`go env`)?

$ go env
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lab/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build538768321=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

// Applied gofmt on this program:

https://play.golang.org/p/lZmBVxAM-E

package main

import (
	"fmt"
)

func main() {
	suffix := "dum-my"
	lastDash := 3
	pool := suffix[1 : lastDash-1] // why does gofmt format this line
	mode := suffix[lastDash+1:]    // differently than this one??
	fmt.Println(pool, mode)
}

https://play.golang.org/p/lZmBVxAM-E

### What did you expect to see?

gofmt applying same formatting to slicing on these lines:

	pool := suffix[1 : lastDash-1] // why does gofmt format this line
	mode := suffix[lastDash+1:]    // differently than this one??

### What did you see instead?

gofmt applied different formatting for those lines.
There are extra spaces surrounding ':' only in the first line.
Is such a behavior actually intended?

**Comment by griesemer** [comment]
The short answer is because that's how it's been decided early on.
gofmt is using various heuristics and - in this case - explicitly differentiates between the two cases.
This is working as intended.

**Comment by griesemer** [comment]
PS: The longer answer is that we introduce blanks around the ':' if we have expressions on either side to separate the expressions and make the more visible. That's similar to why binary expressions are formatted differently depending on context.
