### ISSUE TITLE
os/user: add non-cgo version GroupIds

### ISSUE THREAD

**Issue by kevinburke** [golang/go#19395]
This is slightly more complicated than the pure Go versions of LookupGroup, Lookup, LookupId, LookupGroupId, I think.

On Darwin machines, /etc/group does not contain a full or partial accounting of a user's groups. Instead the definitive information is stored in opendirectoryd and I'm not quite sure how to access that, apart from C libraries that we don't have access to.

If we wanted to do this in Go we would do:

- loop over every entry in /etc/group. 
- If the group name starts with a plus or minus, ignore it.
- If the group mentions the username in the secondary group list, or if the user's `Gid` matches the gid, add it to an array.
- return the array.

But this would miss many groups on Darwin and possibly any extensions that glibc also lets you check, which might be a more relevant concern when you are asking for _all_ groups instead of just the primary user/group.

I think that `exec.Command("groups", u.Username).Output()` would give the right answer, but the overhead is likely too high, a user's machine might not have groups or be able to run a subprocess, &c &c.

**Comment by rsc** [comment]
Why? Why not use cgo?

**Comment by kevinburke** [comment]
The common place I run into errors here is cross compiling; compiling for a Linux target from my Mac laptop.

I run into problems with user.LookupGroup and user.Lookup much more frequently than GroupIds(). I added non-cgo versions of those in recent CL's. For completeness I thought I would try to add this one as well.

**Comment by rsc** [comment]
CLs still welcome, of course.

**Comment by kevinburke** [comment]
OK. I think it's probably better to leave unimplemented than to return a response that may be only partially correct. 

I think it was OK to add cgo-free versions of Lookup(), LookupId() and friends because Mac/Linux may not use /etc/passwd, /etc/group as a source of truth but they at least try to keep them up to date for the purpose of id <=> name mappings. It seems like they're not reliable enough for "list a user's groups," though.
