### ISSUE TITLE
cmd/compile: 100 < 1 is true on GOARCH=arm

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#19403]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.8 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hajimehoshi/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build115404782=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

Compiled https://play.golang.org/p/BtBt5z7tgz with GOARCH=arm

```
GOARCH=arm go build -o test test.go
qemu-arm test
```

I used qemu here, but I confirmed the same problem happens on actual ARM devices like ZenFone Go using gomobile.

### What did you expect to see?
No panics

### What did you see instead?
Panic:

```
100 < 1 = true
panic: 100 < 1

goroutine 1 [running]:
main.vertices(0xa0080, 0xae450, 0x10, 0x10, 0x10333fa0, 0x6, 0x6)
        /home/hajimehoshi/test/test.go:61 +0x4a8
main.main()
        /home/hajimehoshi/test/test.go:72 +0x64

```

**Comment by josharian** [comment]
cc @cherrymui

**Comment by cherrymui** [comment]
The assembler back end uses F15 as a temporary register for int-float conversion (which I didn't notice before). The value happens to live in F15 and get clobbered. Will send a fix.

**Comment by josharian** [comment]
Reopening for 1.8.1 cherry-pick.

**Comment by aclements** [comment]
Cherry-picked to release.
