### ISSUE TITLE
x/tools/cover: allow reading from an io.Reader

### ISSUE THREAD

**Issue by peterebden** [golang/go#19404]
The only interface available now is ParseProfiles which accepts a filename to read from. In cases where that data has already been read or is coming from somewhere other than a filesystem, it'd be nice to be able to parse it in-place rather than having to reread a file (or in the worst case write a file first).

Our use case is that we have a build tool that handles coverage across multiple languages, and so we read the data in and perform some simple heuristics to figure out how to parse it. That works fine for common JSON or XML formats, it'd be nice not to incur this inefficient re-read for Go.
I'm happy to send a pull request implementing this.

## Compatibility
It will be easy to implement this while preserving the old interface as well.

**Comment by rsc** [comment]
Leaving review of CL for @robpike.

**Comment by rsc** [comment]
Note that changes made in x/tools should be brought back into cmd/cover once completed.
