### ISSUE TITLE
crypto: ChaCha20 and Poly1305

### ISSUE THREAD

**Issue by DemiMarie** [golang/go#19414]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7.4

### What operating system and processor architecture are you using (`go env`)?
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/home/dobenour/archives/go"
    GOTOOLDIR="/home/dobenour/archives/go/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build590610773=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"

### What did you do?
Checked the docs for the crypto package

### What did you expect to see?
Support for ChaCha20 and Poly1305

### What did you see instead?
No ChaCha20 or Poly1305 support

**Comment by josharian** [comment]
They are there:

https://godoc.org/golang.org/x/crypto/chacha20poly1305

See also #6914.

Please upgrade to Go 1.8.
