### ISSUE TITLE
bytes/strings: add optimized countByte

### ISSUE THREAD

**Issue by josharian** [golang/go#19411]
(migrated from #19402)

`bytes.Count` and `strings.Count` are commonly called with a single-byte separator, both independently and as part of a `Split` call. Currently they call `Index` and then `IndexByte` in a loop. `IndexByte` uses SSE tricks. I suspect that an assembly implementation of `countByte` usng similar SSE tricks would run much more quickly than calling `IndexByte` in a loop. We could dispatch to `countByte` in `Count` when sep has length one.

@TocarIP @randall77

**Comment by josselin-c** [comment]
I'll try to write something for 1.9. I have a first draft that still needs some love.

**Comment by josselin-c** [comment]
I still need to change the string package

**Comment by mvdan** [comment]
Kudos to all for getting this done without any extra API :)
