### ISSUE TITLE
go build error gcc 6.3.0

### ISSUE THREAD

**Issue by DmitryHetman** [golang/go#19428]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
git-version and 1.8 amd64

### What operating system and processor architecture are you using (`go env`)?
Doesn't matter for this issue.

### What did you do?
emerge -av go

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Compiling and installing go.

### What did you see instead?
find /usr/x86_64-pc-linux-gnu/gcc-bin/*/go-5 : No such file or directory
ERROR: dev-lang/go-9999 

### How to fix problem
GCC contains /usr/x86_64-pc-linux-gnu/gcc-bin/6.3.0/go-6 file
You should search for go-6 or go-* instead.

**Comment by ianlancetaylor** [comment]
What is emerge?

**Comment by DmitryHetman** [comment]
#ianlancetaylor
Gentoo package manager.

**Comment by bradfitz** [comment]
The Go project doesn't maintain or support distro build scripts (Debian, Gentoo, etc).

You should file a bug with your distribution.

If you have a repro using only `$GOROOT/src/make.bash` or `$GOROOT/src/all.bash` (make.bash + running test), then feel free to reopen.
