### ISSUE TITLE
website: 'share' link broken in examples

### ISSUE THREAD

**Issue by rsc** [golang/go#19433]
Visit https://golang.org/pkg/encoding/json/#example_Unmarshal.
Click "Share".

I get a popup that says:

**golang.org says:**
Server error; try again.

Trying again does not help.

/cc @broady @campoy

**Comment by broady** [comment]
Bummer. Same as #19373. Looks like the geo detection is probably broken, since I'm seeing this from the US.

**Comment by broady** [comment]
Fixed (I cherry-picked 37881 into production while it's still pending).
