### ISSUE TITLE
crypto/x509: honor OS X certificate trust settings possible regression

### ISSUE THREAD

**Issue by dharmapunk82** [golang/go#19436]
Thanks in advance.  Terraform is an amazing product/tool.

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/redacted/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jn/j5dcc0w96ls4p6hcg6kd_0gr6p4nnj/T/go-build370212292=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
We have two projects using remote state with s3 back end.  One I am new to, the other I wrote myself and have been using for months.  My old project worked fine a week ago when I was on 0.8.7, but this week I get x509 certificate errors as described in https://github.com/golang/go/issues/18141 when running from my 10.12.3 mac.  A colleague on 10.11.x (I'm not sure his exact version) also sees the x509 issue, however one on OS X 10.10.x does not.  I suspect, therefore, this is affecting only newer OS X versions.

I tried running both projects from an ubuntu 16.04 system, and had no issues with either.  Remote config and plan operations complete without issue from linux on terraform 0.8.8 (although I did see a similar issue before upgrading from 0.8.0rc1 to 0.8.8 on linux).

### What did you expect to see?
Remote state pulled and configured successfully.

### What did you see instead?
terraform plan
Error reloading remote state: RequestError: send request failed
caused by: Get https://redacted-s3-redacted.aws.com/redacted/terraform.tfstate: x509: certificate signed by unknown authority

I can and am happy to provide additional details, just will need more time to redact necessary identifiers.  Please let me know any specifics that would be helpful.

**Comment by bradfitz** [comment]
> Thanks in advance. Terraform is an amazing product/tool.

Wrong bug tracker?

I'm not sure there's not enough information here to help you, especially with thing redacted.

**Comment by dharmapunk82** [comment]
Yeah, wrong tracker, and confirmed this is an internal network issue.  Please close, thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
