### ISSUE TITLE
Problem of install llvm on go 1.8

### ISSUE THREAD

**Issue by questionpython** [golang/go#19444]
hi
i can not, install llvm on go 1.8.
os: ubuntu 16.10-64bit

>`$~/go/src/github.com/go-llvm/llgo$ go version`
go version go1.8 linux/amd64

>`$ go get -insecure -d -v llvm.org/llvm/bindings/go/llvm`
Fetching https://llvm.org/llvm/bindings/go/llvm?go-get=1
Parsing meta tags from https://llvm.org/llvm/bindings/go/llvm?go-get=1 (status code 404)
package llvm.org/llvm/bindings/go/llvm: unrecognized import path "llvm.org/llvm/bindings/go/llvm" (parse https://llvm.org/llvm/bindings/go/llvm?go-get=1: no go-import meta tags ())

>`$ go get -tags byollvm github.com/go-llvm/llvm`
github.com/go-llvm/llvm
could not determine kind of name for C.LLVMDisposeMessage

**Comment by ianlancetaylor** [comment]
You need to report this to whoever maintains llvm.org/llvm/bindings/go.  That isn't us.

**Comment by thanm** [comment]
It looks as though maybe you are using the old (stale) installation instructions for llgo (there is a note on that page saying that the project has moved to LLVM). Have you tried the instructions in http://llvm.org/svn/llvm-project/llgo/trunk/README.TXT?

**Comment by questionpython** [comment]
http://stackoverflow.com/questions/43438219/how-get-llvm-library-in-go
