### ISSUE TITLE
build: make.bash creates $GOROOT/bin/pprof

### ISSUE THREAD

**Issue by DmitryHetman** [golang/go#19441]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +def5e36917 Tue Mar 7 03:26:47 2017 +0000 linux/amd64
### What did you do?
Try to install google-perftools when go installed, or try install go when google-perftools installed.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
succesful installing
### What did you see instead?
error, package collision /usr/bin/pprof
### How fix?
Remove google-perftools from go, or /usr/bin/pprof, use dependecy instead.

**Comment by bradfitz** [comment]
Go doesn't install /usr/bin/pprof, so you must be talking about some other system.

You should file a bug report against your package manager or distro. Your bug report doesn't say which distro you're using.

**Comment by DmitryHetman** [comment]
Gentoo GNU/Linux nomultilib experimental

**Comment by DmitryHetman** [comment]
Are you sure it's not install pprof? I'm sure it does.
https://golang.org/pkg/runtime/pprof/

**Comment by DmitryHetman** [comment]
https://github.com/gentoo/gentoo/blob/master/dev-lang/go/go-9999.ebuild
ebuild doesn't do anything related to pprof, just installs from git repo.

**Comment by bradfitz** [comment]
Yes, this is a Gentoo problem. Looks like it's installing Go's private tool/pprof binary into /usr/bin (https://github.com/gentoo/gentoo/blob/master/dev-lang/go/go-9999.ebuild#L220), which isn't where Go puts it.

Please report a bug to Gentoo instead.

**Comment by DmitryHetman** [comment]
Isn't it a same binary?

**Comment by williamh** [comment]
Is pprof supposed to end up in $GOROOT/bin? That is where we are picking up binaries we want to make accessible to the user; it would be the same as adding $GOROOT/bin to your path. I could skip this specific binary, but if I do that and users need to access it at some point, there will be an issue. Also, there will be an issue for anyone who adds $GOROOT/bin to their path and has the other package installed on their distro because they will get a different pprof binary unexpectedly.

**Comment by williamh** [comment]
It looks like there are quite a number of new binaries in $GOROOT/bin if Go is built from git. Are all of these meant to be available to the user by adding $GOROOT/bin to their path?

benchcmp
bundle
callgraph
colcmp
digraph
eg
fiximports
go
godex
godoc
gofmt
goimports
gomvpkg
gorename
gotype
guru
html2article
oracle
pprof
present
ssadump
stress
stringer
tip


Some of those names seem pretty generic, so there could end up being more collisions later.

**Comment by bradfitz** [comment]
pprof should not end up in bin. It should be accessible via "go tool pprof" only.

And most of that other stuff is noise. You should not put the `tip` binary in `/usr/bin`. There is only one user of that: us, running https://tip.golang.org/. And I don't even know what `colcmp` is off the top of my head. etc.

**Comment by williamh** [comment]
If you do a normal source build, I just noticed that a large number of binaries end up in $GOROOT/bin even for go 1.8. The list for go 1.8 is:

benchcmp
bundle
callgraph
colcmp
digraph
eg
fiximports
go
godex
godoc
gofmt
goimports
gomvpkg
gorename
gotype
guru
html2article
oracle
present
ssadump
stress
stringer
tip

Those should end up in $GOROOT/bin if you do a normal build from source.

**Comment by williamh** [comment]
ok, nvm, a number of those got left behind from the git merge. I'll take a look at my live ebuild tomorrow and update you.

**Comment by williamh** [comment]
I just ran a couple of manual builds by following your build instructions  and found a quirk in the build system that I'm not sure how to debug.
The first time I ran the build, pprof was not installed in $GOROOT/bin, but I did a fresh clone and it was installed there after the second build.

**Comment by bradfitz** [comment]
@williamh, who are you talking to? And are you the Go package maintainer for Gentoo?

This bug is closed, so is unlikely to get much if any attention from the Go team.

**Comment by williamh** [comment]
@bradfitz yes, I am the Go package maintainer for Gentoo. I am talking to whoever can help me figure out why pprof is ending up in $GOROOT/bin. Since this is closed, do I need to open another issue?

**Comment by ianlancetaylor** [comment]
There is a problem here, so reopening.  When I run `$GOROOT/src/make.bash` in a clean directory, it does indeed create `$GOROOT/bin/pprof`.

**Comment by ianlancetaylor** [comment]
It's being installed from `cmd/vendor/github.com/google/pprof`.

**Comment by ianlancetaylor** [comment]
CC @rauls5382

**Comment by rauls5382** [comment]
Yes, the vendored package builds its own version of pprof, which is not the same as the pprof used by go tool pprof (whose main is on sec/cmd/pprof). Skipping it is the right thing to do. Thanks,
