### ISSUE TITLE
encoding/asn1: add explicit support for ASN.1 NULL

### ISSUE THREAD

**Issue by andrewmbenton** [golang/go#19446]
I've been working on cleaning this up but wanted to start a discussion here about the proper approach before I get too deep.

There are a couple of places in crypto/x509/x509.go that use hardcoded byte slices representing the DER-encoding of ASN.1 NULL. See [x509.go#L421](/golang/go/blob/2a26f5809e4e80e7d8d4e20b9965efb2eefe71c5/src/crypto/x509/x509.go#L421) and [x509.go#L932](/golang/go/blob/2a26f5809e4e80e7d8d4e20b9965efb2eefe71c5/src/crypto/x509/x509.go#L932).

Additionally, there are four places in crypto/x509/x509.go where identical asn1.RawValue structs representing the unmarshaled ASN.1 NULL type are used. See [x509.go#L72](/golang/go/blob/2a26f5809e4e80e7d8d4e20b9965efb2eefe71c5/src/crypto/x509/x509.go#L72) and [x509.go#L359](/golang/go/blob/2a26f5809e4e80e7d8d4e20b9965efb2eefe71c5/src/crypto/x509/x509.go#L359) for instance.

My thought was to consolidate these usages around two new funcs in the asn1 package that would return the desired explicit values, so signatures would be:

```go
func Null() RawValue
```
```go
func NullBytes() []byte
```

I think this approach makes sense and I already have it written up with tests, but I'm interested in feedback. I was trying to figure a way to create an asn1.Null type as an alias of asn1.RawValue but it didn't seem to make much sense since the NULL type in practice can only ever have one value.

Are there other approaches that make more sense?

**Comment by agl** [comment]
This seems like a reasonable cleanup. I'm not too keen on adding more to `encoding/asn1` (which I consider to have been a mistake), but this seems small enough.

**Comment by andrewmbenton** [comment]
I'll submit the very simple patch I have and reference this discussion.

**Comment by rsc** [comment]
The commit seems to have forgotten the magic word Fixes.

**Comment by andrewmbenton** [comment]
My b, thanks for cleaning up. Will remember next time.
