### ISSUE TITLE
strconv: consider speeding up formatting of small integers with cache

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#19445]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8

### What operating system and processor architecture are you using (`go env`)?

```
GOOS=darwin
GOARCH=amd64
```

### What, why, etc.

While profiling an ORM-like program, I discovered most of the 100+ allocs/op were from calls to strconv.Itoa. By implementing a simple cache in front of strconv.Itoa, the number of allocs dropped by over half and so did the runtime of the function (7 to 3 μs). I looked at some other of our projects and noticed most of the Itoa-like calls were used to format smaller numbers (i.e., < 100). I'd imagine other project that generate SQL or graph query code and need to format parameters ($1, $2, ...) would see decent performance improvements as well.

A small test I ran shows no appreciable difference when the majority of N is > 99 or N is a pseudo-random number in [0, b.N), but runs in 1/10 the time where N < 100 and doesn't incur any allocations.

My issues with this idea:

- Small range of numbers (assumes that most calls are < 100)
- Only works with base 10
- Negative numbers need their own cache or an alloc needs to be made to contact the number with "-"

FWIW the cache only needs to be a 190-byte long string.

```
name             old time/op    new time/op    delta
SmallItoaAll-4     45.8ns ± 0%    47.4ns ± 0%   ~     (p=1.000 n=1+1)
SmallItoaRand-4    90.9ns ± 0%    90.5ns ± 0%   ~     (p=1.000 n=1+1)
SmallItoa-4        31.4ns ± 0%     3.4ns ± 0%   ~     (p=1.000 n=1+1)

name             old alloc/op   new alloc/op   delta
SmallItoaAll-4      8.00B ± 0%     8.00B ± 0%   ~     (all equal)
SmallItoaRand-4     7.00B ± 0%     7.00B ± 0%   ~     (all equal)
SmallItoa-4         1.00B ± 0%     0.00B        ~     (p=1.000 n=1+1)

name             old allocs/op  new allocs/op  delta
SmallItoaAll-4       1.00 ± 0%      1.00 ± 0%   ~     (all equal)
SmallItoaRand-4      1.00 ± 0%      0.00        ~     (p=1.000 n=1+1)
SmallItoa-4          1.00 ± 0%      0.00        ~     (p=1.000 n=1+1)
```

**Comment by josharian** [comment]
I recently looked into doing something similar but lower level. When calling string(b) where b is a byte slice of length exactly one, construct a string using the recently introduced runtime.staticbytes, thus avoiding an allocation. This would eliminate the allocation for single-digit numbers.

I gave it up because I wasn't convinced it was worth the impact on other []byte to string conversions, but in the meantime, I saw some other optimizations, leading to [CL 37791](https://golang.org/cl/37791). It is possible that the other optimizations would pay for a "single digit" code path.

What do you think, @randall77 @mdempsky?

**Comment by ericlagergren** [comment]
Here's a sample implementation (from the ORM-project):

```
const smallInts = "0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899"

func itoa(i int64) string {
	if i < 10 {
		return smallInts[i : i+1]
	}
	if i < 100 {
		return smallInts[2*i-10 : 2*i-8]
	}
	return strconv.FormatInt(i, 10)
}
```

**Comment by bradfitz** [comment]
Your SQL database and network is fast enough that you notice a  7μs to 3μs drop when formatting SQL queries?

I'm not totally against this, and I usually like to help fight the allocation battles, but I'm a little surprised this comes up often enough to matter. Does it help on any of our existing benchmarks?

**Comment by ericlagergren** [comment]
@bradfitz of course not. I wish it was, though. 😉 I just happened to run
pprof (as part of tests after making a change) and notice strconv came up a
lot. That's all.

It doesn't really affect many existing strconv benchmarks because they deal
with too many numbers > 99. And I haven't tested the entire stdlib.

**Comment by dlsniper** [comment]
Sorry if this will sound bad, but will we now start seeing and accepting patches that further add numbers to this? Why stop at 99 and not at 2147483648? That seems to cover a lot more of the frequent use-cases where timestamps are converted from strings to numbers.

**Comment by mvdan** [comment]
@dlsniper do you think that's worth the large amount of binary data and compiler work? 99 numbers, in comparison, is a tiny amount.

**Comment by bradfitz** [comment]
@mvdan, what's wrong with a 20 GB binary? Disk space is cheap. We could avoid allocations! :)

**Comment by bradfitz** [comment]
Actually it'd only be about 18 GB. Even better.

**Comment by ericlagergren** [comment]
since I'm not sure if I can comment on the CL: why a 2.4k array instead of a 190 byte const string? Just to save two subtractions?

**Comment by bradfitz** [comment]
@ericlagergren, you can comment on the CL.

I don't see a 2.4k array.

Let me turn your question around: why a 190 byte const string over the existing code?

**Comment by ericlagergren** [comment]
@bradfitz cool, didn't know that–thanks!

I typoed that number. I meant ~1.7k (16 bytes for each string header * 100 elements + the strings' data).

The const string is smaller.

**Comment by mvdan** [comment]
@ericlagergren if you come up with a CL that doesn't complicate the code and keeps performance, I don't see why it wouldn't get merged.

**Comment by bradfitz** [comment]
@ericlagergren, it was originally a const string. Presumably the code review discussion explains why it was changed. I stopped following at some point.

**Comment by mvdan** [comment]
This seems to be the reason by gri:

> For one, have you tried actually creating the slice of strings:
> var smallInts = []string{"0", "1", "2", ...} ? Then you don't need an extra if and you can just index into it. You don't even need the formatSmallInt function and all the conversion stuff around it.

**Comment by ericlagergren** [comment]
@bradfitz yeah, I read through it and it seems like the idea was trading 1.5kb for two subtractions (-10 and -8). Thus my question.

@mvdan right, I was just asking why the CL went that direction. :-)

**Comment by bradfitz** [comment]
It's possible @griesemer didn't consider the binary size bloat when making his decision if there was no discussion of it previously.

**Comment by ericlagergren** [comment]
@bradfitz That was my concern that sparked the question–I know in the past y'all have made decisions with binary bloat in mind, so I was surprised the CL went with a larger array vs a smaller string. Which led to me wondering if there were other reasons.

**Comment by griesemer** [comment]
1) choosing 100 numbers (0-99)  has the advantage that it might be used to
further optimize conversions (by dividing in steps of 100 instead of 10) -
see https://go-review.googlesource.com/#/c/38255/ as a starting point
2) choosing a slice of strings led to simpler code

Re: 2 I was aware of the extra bloat, but it's kind of hard to judge the
actual impact. If somebody wants to go back and go to a string constant
(the original code didn't have that, it used a initialized byte array
converted to a string), I'm ok with that. It should be trivial to have a
little function that extracts the right substring and use it instead of the
direct access to the slice.

And yes, I'm not too eager to add more tables or complexity to this code
w/o significant gains throughout (at least 5% or more for relevant
benchmarks).
- gri

**Comment by ericlagergren** [comment]
@griesemer thanks for clarifying it for me.

I'll submit a CL if you want, but if CL 38255 is gonna go through then it doesn't seem like there's any point to change it to a const string since it'll just get changed back.

**Comment by griesemer** [comment]
CL (which I'm not convinced yet) can still work just fine if you have a
const string. Please send your CL and we'll take it from there.
