### ISSUE TITLE
cmd/compile: broken := operator generates bizarre error

### ISSUE THREAD

**Issue by StScAllen** [golang/go#19440]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoWork\;C:\GoWork\src\github.com\user\character
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\all
st\AppData\Local\Temp\go-build641294366=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

### What did you do?
https://play.golang.org/p/Nk92HWr1YX

For loop generates error that opening { brace is missing. Rather than 
informing user the := operator is severed.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
unexpected token ':' on line 7 
(or something like that)
Really anything but the missing { comment, as the brackets are all correct.

### What did you see instead?
syntax error: missing { after for clause

**Comment by klingtnet** [comment]
@StScAllen `:=` is not broken, your example contained a redundant space between the colon `:` and equal sign `=`. Here is a link to a working [example](https://play.golang.org/p/oPKdW7eHWj).

PS: You can wrap multiple lines of code in triple backticks so it is rendered in a monospaced font.

**Comment by klingtnet** [comment]
Can be closed because of a non issue.

**Comment by ALTree** [comment]
Why was this closed? The OP is reporting the fact that the **error message** that you get when you mis-type ":=" as ": =" is misleading. That's a valid complaint.

**Comment by ALTree** [comment]
Ah, it was #17328. The typo is different, but the misleading message was the same: a not-very-informative " missing { after for clause".

**Comment by ALTree** [comment]
On tip, the error message is:

> syntax error: unexpected :, expecting { after for clause

a little better (at least it mentions `:`).

**Comment by klingtnet** [comment]
@ALTree You're right I overlooked this sentence:

> For loop generates error that opening { brace is missing. Rather than
informing user the := operator is severed.

**Comment by griesemer** [comment]
I'll take a look - it's not hard to recognize this case, but it's unclear it's worth it. The better thing might be to print column/offset information in error messages (we do have that information now), as it would point much more clearly at the place where the error occurred (rather than just mentioning a line).

**Comment by robpike** [comment]
What's a column?

**Comment by klingtnet** [comment]
I think with _column_ he means the index/position in the line.

**Comment by ALTree** [comment]
For more arguing about columns: https://github.com/golang/go/issues/10324#issuecomment-89643834. :^)

**Comment by griesemer** [comment]
At tip, the error reported is:
```
tmp.go:7: syntax error: unexpected :, expecting { after for clause
```
which is pretty clear. That is, this has been fixed as part of another issue.
Furthermore, once the compiler reports column information (#10324), the reported error is:
```
tmp.go:7:8: syntax error: unexpected :, expecting { after for clause
```
pin-pointing the offending token exactly. Once 1.9 is out, the playground will behave the same.

Closing as there's nothing else to do here.
