### ISSUE TITLE
fmt: wording error in fmt.Print docs?

### ISSUE THREAD

**Issue by golang101** [golang/go#19442]
The docs https://golang.org/pkg/fmt/#Print says:

> Spaces are added between operands when neither is a string.

Maybe my English is not good. I interpret as "Spaces are added between operands when both of them are not string." If my interpretation is right, then the docs is wrong. It should be "Spaces are added between operands when at least one of them is not a string."

**Comment by griesemer** [comment]
I suspect this is correct but leaving for @robpike to decide.

**Comment by robpike** [comment]
Your interpretation is wrong and the docs are correct.

Spaces are added between operands unless either one or both is a string.

The original wording is fine.

**Comment by golang101** [comment]
yes, my impression for print behavior was wrong. I though a space will be added between a string and a non-string.
