### ISSUE TITLE
time: TestParseInLocation fail

### ISSUE THREAD

**Issue by reusee** [golang/go#19457]
#### What did you do?
cd src/time
go test

#### What did you expect to see?
test pass

#### What did you see instead?
```
--- FAIL: TestParseInLocation (0.00s)
	format_test.go:264: ParseInLocation(Feb 01 2013 AST, Baghdad) = 2013-02-01 00:00:00 +0000 AST, want 2013-02-01 00:00:00 +0300 +03
FAIL
exit status 1
FAIL	time	8.438s
```

#### System details

```
go version devel +2bd6360e3b Wed Mar 8 03:24:44 2017 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/reus"
GORACE=""
GOROOT="/home/reus/go"
GOTOOLDIR="/home/reus/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build381570872=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +2bd6360e3b Wed Mar 8 03:24:44 2017 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +2bd6360e3b Wed Mar 8 03:24:44 2017 +0000 X:framepointer
uname -sr: Linux 4.9.11-1-ARCH
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.24, by Roland McGrath et al.
gdb --version: GNU gdb (GDB) 7.12.1
```

**Comment by ALTree** [comment]
Here we go again.

The tzdata 2017a release changed the Baghdad abbreviation:

>  Changes to past and future time zone abbreviations
>  Similarly, switch from invented to numeric time zone
>  abbreviations for [..] **Iraq** [..]

We'll need to update the test, I'll send a patch.

**Comment by ianlancetaylor** [comment]
Setting milestone to 1.8.1.  If I understand this, this is going to have to ripple back through all the previous releases.

**Comment by marxenegls** [comment]
FAIL: TestParseInLocation  compile go1.5 on armv7 using go1.4 bootstrap  


### What version of Go are you using (`go version`)?
1.4  bootstrap

### Does this issue reproduce with the latest release?
1.5 src 

### What operating system and processor architecture are you using (`go env`)?
raspbian armv7l pi3 - 4.4.50-hypriotos-v7+

### What did you do?
followed Dave Cheney's advice set ulimits added swap space even cleared page cache before compiling had a clear 600M ram and 1023 swap free 
 
$ cd go/src
$ env GO_TEST_TIMEOUT_SCALE=10 GOROOT_BOOTSTRAP=$HOME/go-linux-arm-bootstrap ./all.bash

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.


### What did you expect to see?
success exit status 0 :)
### What did you see instead?

ok      text/template/parse     0.141s
--- FAIL: TestParseInLocation (0.02s)  : p
        format_test.go:202: ParseInLocation(Feb 01 2013 AST, Baghdad) = 2013-02-01 00:00:00 +0000 AST, want 2013-02-01 00:00:00 +0300 +03
--- FAIL: TestLoadFixed (0.01s)
        time_test.go:943: Now().In(loc).Zone() = "-01", -3600, want "GMT+1", -3600
FAIL
FAIL    time    5.582s
ok      unicode 0.027s
ok      unicode/utf16   0.021s
ok      unicode/utf8    0.062s
ok      cmd/addr2line   13.514s
ok      cmd/api 0.065s
ok      cmd/asm/internal/asm    0.274s
ok      cmd/asm/internal/lex    0.027s
ok      cmd/compile/internal/big        87.227s
ok      cmd/cover       25.510s
ok      cmd/doc 0.335s
ok      cmd/fix 0.130s
ok      cmd/go  301.585s
ok      cmd/gofmt       1.007s
ok      cmd/internal/goobj      0.018s
ok      cmd/internal/obj        0.018s
ok      cmd/internal/obj/x86    0.275s
ok      cmd/internal/rsc.io/arm/armasm  0.069s
ok      cmd/internal/rsc.io/x86/x86asm  3.826s
ok      cmd/nm  14.115s
ok      cmd/objdump     37.316s
ok      cmd/pack        28.801s
ok      cmd/pprof/internal/profile      0.067s
ok      cmd/vet 51.834s
2018/07/03 01:30:39 Failed: exit status 1

**Comment by ianlancetaylor** [comment]
@marxenegls This issue was closed long ago.  Go 1.5 is no longer supported.

**Comment by marxenegls** [comment]
fixed i skipped the tests  used  ./make.bash 
i wasn't aware , .. if i were i would'av avoided the issue the begin with.

**Comment by marxenegls** [comment]
@ianlancetaylor " This issue was closed long ago. Go 1.5 is no longer supported." 
closed long ago ? there are two open remarks .. 
 well technically this issue is an old one not fixed .. from your reply i presumed i was using both an old tutt (https://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi) and an older version of Go .. which was not exactly the case but i had to find that out for myself .. trying to build 1.10 on arm was a futile attempt ..so maybe you aren't aware of what runs on arm at this point in time .. 
miscommunication .. 
and i keep making the same mistake in presuming the latest version is somehow better

**Comment by ianlancetaylor** [comment]
If the latest version (1.10.3) does not build on ARM, please file an issue about that.  We don't support 1.5 but we do support 1.10 (and 1.9).

**Comment by davecheney** [comment]
It's unlikely that ./all.bash will complete successfully on a stock
raspberry pi, but ./make.bash should complete successfully, and using the
tarball provided on golang.org you can skip that process entirely.
