### ISSUE TITLE
runtime: add GOPATH() string

### ISSUE THREAD

**Issue by willfaught** [golang/go#19451]
Since Go v1.8 no longer requires setting GOPATH, does it make sense to add a `GOPATH() string` function to runtime, like there is for GOROOT?

**Comment by bradfitz** [comment]
Note that:

* the runtime knows nothing about $GOPATH. The concept of GOPATH is a cmd/go, go/types.Importer thing.
* GOPATH is multi-valued, so `GOPATH() string` is the wrong signature.

**Comment by bradfitz** [comment]
Oh, it even says that at the top of the runtime package docs:

> The GOARCH, GOOS, GOPATH, and GOROOT environment variables complete the set of Go environment variables. They influence the building of Go programs (see https://golang.org/cmd/go and https://golang.org/pkg/go/build). GOARCH, GOOS, and GOROOT are recorded at compile time and made available by constants or functions in this package, but they do not influence the execution of the run-time system.

What are you trying to do? Does build.Default.Import (https://golang.org/pkg/go/build/#Context.Import) solve your problem?

**Comment by willfaught** [comment]
Ah, right, so the result would be []string.

GOROOT() returns the compile time value if there isn't a run time value.
Seems like a GOPATH() could have the same utility.

In my particular case, I'm writing a lightweight dotfiles package manager.
The repo remains on disk to pull updates made across multiple development
machines. There are dot files in the repo not built into the executable
that need to be read, relative to GOPATH.

**Comment by bradfitz** [comment]
Okay, sounds like go/build and friends are what you're looking for then.

This isn't something we want to add to the runtime package, since it's not a runtime thing.

**Comment by willfaught** [comment]
Doesn't that also apply to runtime.GOROOT()?

**Comment by bradfitz** [comment]
Perhaps. But any historical mistakes are locked-in at this point.

**Comment by willfaught** [comment]
OK. It seems that's the core issue, not that go/build can be used instead.
