### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by staticmukesh** [golang/go#19461]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go1.8 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mmukesh/Desktop/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6y/8j7rkrsj20b99b1s6m2ckx7hvs24z2/T/go-build624100664=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
I tried to run executable created by `go build`, but it showed the error.

### What did you expect to see?
It should have worked.

### What did you see instead?
```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x10b58c5, 0x21)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff770 sp=0x7fff5fbff750
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbff7a0 sp=0x7fff5fbff770
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff7e0 sp=0x7fff5fbff7a0
runtime.rt0_go(0x7fff5fbff818, 0x1, 0x7fff5fbff818, 0x0, 0x0, 0x1, 0x7fff5fbff960, 0x0, 0x7fff5fbff967, 0x7fff5fbffae7, ...)
	/usr/local/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff7e8 sp=0x7fff5fbff7e0
```

### Details

I wrote sample hello world [program](https://play.golang.org/p/v3rrZLwEUC), for which the binary created by `go build` showed above mentioned error. And when I imported `net/http` package in the same [program](https://play.golang.org/p/KcPuWiCXJS), then it worked fine. 

I checked [other](https://groups.google.com/forum/#!topic/Golang-Nuts/HtcZc3wO-rw) posts with same issue. And, it seems like Websense Endpoint installed on my work machine is the issue, but why did it work after including `net/http` module ?

**Comment by bradfitz** [comment]
Dup of #18171 (and #8801?).
