### ISSUE TITLE
sync: confusing documentation for RWMutex

### ISSUE THREAD

**Issue by Lexicality** [golang/go#19460]
[sync#RWMutex](https://golang.org/pkg/sync/#RWMutex)
> An RWMutex is a reader/writer mutual exclusion lock. The lock can be held by an arbitrary number of readers or a single writer. RWMutexes can be created as part of other structures; the zero value for a RWMutex is an unlocked mutex.
>
>An RWMutex must not be copied after first use.
>
>If a goroutine holds a RWMutex for reading, it must not expect this or any other goroutine to be able to also take the read lock until the first read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock. 

The third paragraph "_If a goroutine holds a RWMutex for reading, it must not expect this or any other goroutine to be able to also take the read lock until the first read lock is released._" appears to contradict the first paragraph "_The lock can be held by an arbitrary number of readers or a single writer._"

After reading #7576 I think I understand this to mean that subsequent calls to `RWMutex.RLock()` will block if a call to `RWMutex.Lock()` has taken place (even if the write lock is currently not held), however that is not apparent from the rest of the documentation.

If this is the case can the forward for `RWLock` and the documentation for `RWLock.RLock` be updated to match please?

**Comment by ianlancetaylor** [comment]
Pedantically, you say "subsequent calls to `RWMutex.RLock()` will block" but it would be more correct to say "subsequent calls to `RWMutex.RLock()` may block."

**Comment by Lexicality** [comment]
Oh? Looks like I'm still confused then. 😛  
It was my understanding that if you did something similar to this:
```go
rw := sync.RWMutex{}
rw.RLock()
go rw.Lock()
rw.RLock() // :(
```
You would always* end up with a deadlock (*assuming 'favourable' scheduling)

**Comment by ianlancetaylor** [comment]
I'm sorry, I misread your comment.  I think you're right.

**Comment by bradfitz** [comment]
This was already fixed once in #15418 by b3f98d7a42d04f6f173cd61ce3fe2106e4877496.

I just tried to say more in https://golang.org/cl/45697 but it's unclear how much better my updated text is.

I'll let @ianlancetaylor or @dvyukov decide.

**Comment by dvyukov** [comment]
> The third paragraph "If a goroutine holds a RWMutex for reading,
> it must not expect this or any other goroutine to be able to also take
> the read lock until the first read lock is released." appears to contradict
> the first paragraph "The lock can be held by an arbitrary number of
> readers or a single writer."

Are you sure they are contradicting? What exactly is the contradiction?

**Comment by bradfitz** [comment]
The contradiction is only in a world with no goroutines calling Lock.

It says "an arbitrary number of readers" **or** "a single writer".

The arbitrary number of readers part is actually true if there's no goroutine ever calling Lock. Then anybody's free to call RLock without fear of deadlocks. The deadlock only happens if anybody's calling Lock.

The CL I sent above the words:

> ... and another goroutine might call Lock, ...

**Comment by dvyukov** [comment]
@bradfitz right

**Comment by Lexicality** [comment]
👍, though I still think `RLock()` should specify that it blocks.
Eg

> RLock locks rw for reading. If another goroutine has or is trying to lock for writing, RLock blocks until the write has completed.

**Comment by dvyukov** [comment]
RLock _may_ block until (at least for the "is trying to lock for writing" case)

**Comment by bradfitz** [comment]
I've added a small note to the `RLock` method referencing the type comment. PTAL.
