### ISSUE TITLE
net/url: should Parse accept hostnames with leading hyphens?

### ISSUE THREAD

**Issue by Xeoncross** [golang/go#19462]
### What version of Go are you using (`go version`)?

    go version go1.7.4 darwin/amd64

### What did you do?

I have tested with multiple invalid strings and found that `url.Parse()` and `url.ParseRequestURI()` allow invalid URL strings without an error.

    u, err := url.Parse("http://-10:10/foobar")

https://play.golang.org/p/_qvse6f4C9

### What did you expect to see?

An Error. `-10:10` is not a URL, an IP 4/6, or a CIDR.

### What did you see instead?

`net/url` allows invalid hostnames

**Comment by bradfitz** [comment]
This looks like a joke or meme instead of a bug report.

Feel free to re-file if you want to be serious.

**Comment by Xeoncross** [comment]
I removed the photo. I don't think a new issue is needed. I'll just leave this here for future google searches.

**Comment by bradfitz** [comment]
So the question is whether url.Parse should be strict about enforcing that a DNS name can't begin with a hyphen (and can only contain hyphens in the middle/end)?

But those rules only apply to certain schemes.

The URL spec says:

```
      host        = IP-literal / IPv4address / reg-name
...
   reg-name      = *( unreserved / pct-encoded / sub-delims )
...
   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

So it seems like hyphens are valid anywhere.

Do you have a counterargument?

**Comment by Xeoncross** [comment]
No counterargument.
