### ISSUE TITLE
go/build: matchFile parameter returnImports is actually unused

### ISSUE THREAD

**Issue by mvdan** [golang/go#19474]
And has been ever since it was introduced in 2013 by @rsc. The godoc says:

```
// If returnImports is true and name denotes a Go program, matchFile reads
// until the end of the imports (and returns that data) even though it only
// considers text until the first non-comment.
```

Should the method actually use the bool parameter, or should it be removed from the signature and godoc? The func is currently called called with both `true` and `false`.

Found by https://github.com/mvdan/unparam.

**Comment by rsc** [comment]
You can delete the parameter. The code uses the file suffix instead, which is a better source of truth.
