### ISSUE TITLE
x/crypto/bn256: document that bn256 is weak

### ISSUE THREAD

**Issue by davidlazar** [golang/go#19479]
Due to recent improvements in calculating discrete logs [1], the BN-256 curve provides less than 128 bits of security. One estimate is that BN-256 provides closer to 96 bits of security. Trevor wrote a good summary of the situation [2]. The package comment for x/crypto/bn256 should note this weakness.

[1] https://eprint.iacr.org/2015/1027
[2] https://moderncrypto.org/mail-archive/curves/2016/000740.html

cc @agl @trevp

**Comment by dgryski** [comment]
I'm trying to remember a discussion where it was decided against adding a warning that TEA/XTEA similarly "Bad" block ciphers.

**Comment by DemiMarie** [comment]
IIRC TEA is actually secure (it is XTEA and XXTEA that are broken).
