### ISSUE TITLE
Build fails at tip with go tool dist: FAILED

### ISSUE THREAD

**Issue by rjammala** [golang/go#19488]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +a4a3d63 Fri Feb 17 23:41:16 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rajanikanth/gocode"
GORACE=""
GOROOT="/home/rajanikanth/go"
GOTOOLDIR="/home/rajanikanth/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build887089948=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
 git pull && ./make.bash 
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

Build succeeds.
### What did you see instead?
bootstrap/cmd/compile/internal/ssa
go build bootstrap/cmd/compile/internal/ssa: /home/rajanikanth/go1.4/pkg/tool/linux_amd64/compile: signal: killed
bootstrap/cmd/compile/internal/syntax
bootstrap/cmd/internal/gcprog
bootstrap/debug/pe
bootstrap/cmd/link/internal/ld
bootstrap/cmd/link/internal/amd64
bootstrap/cmd/link/internal/arm
bootstrap/cmd/link/internal/arm64
bootstrap/cmd/link/internal/mips
bootstrap/cmd/link/internal/mips64
bootstrap/cmd/link/internal/ppc64
bootstrap/cmd/link/internal/s390x
bootstrap/cmd/link/internal/x86
bootstrap/cmd/link
go tool dist: FAILED: /home/rajanikanth/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go -v bootstrap/cmd/...: exit status 1

**Comment by bradfitz** [comment]
Run out of memory? Kernel kill you? Anything in dmesg?

**Comment by rjammala** [comment]
Thanks. Will increase the memory and retry.

[  199.060424] Out of memory: Kill process 3385 (compile) score 717 or sacrifice child
[  199.068240] Killed process 3385 (compile) total-vm:440956kB, anon-rss:427348kB, file-rss:4368kB
