### ISSUE TITLE
cmd/asm: add missing s390x branch/move on condition suffixes and improve consistency

### ISSUE THREAD

**Issue by mundaym** [golang/go#19483]
I'd like the compiler to be able to generate test-under-mask instructions (TMLL, TMLH, TMHL and TMHH) for s390x. To do this properly the SSA backend needs to be able to deal with (and be able to reverse) all 14 useful condition codes, rather than just the 9 it currently handles. We don't currently have suffixes for all these condition codes and in the process of adding them I'm wondering whether to also try and make the existing ones more consistent with their GNU assembler (GAS) equivalents.

The exact meaning of the bits set in the condition code vary from instruction to instruction. For example, bit 3 set by test-under-mask means 'selected bits are all ones'. However in general they correspond to the following (big endian, so 0 is MSB, 3 is LSB):

0. equal
1. less than
2. greater than
3. overflow (also commonly used to represent 'unordered' for floating point comparisons)

Here are my proposed changes:

<table>
<tr><th>Condition Code</th><th>GAS Suffix</th><th>Current Go Suffix</th><th>Proposed Go Suffix</th></tr>
<tr><td>0x0</td><td></td><td>VC</td><td></td></tr>
<tr><td>0x1</td><td>o</td><td>VS</td><td>O (overflow)</td></tr>
<tr><td>0x2</td><td>h</td><td>GT</td><td>GT (greater than)</td></tr>
<tr><td>0x3</td><td>nle</td><td></td><td>NLE (not less than and not equal)</td></tr>
<tr><td>0x4</td><td>l</td><td>LT</td><td>LT (less than)</td></tr>
<tr><td>0x5</td><td>nhe</td><td>LTU</td><td>NGE (not greater than and not equal)</td></tr>
<tr><td>0x6</td><td>lh</td><td></td><td>LG (less or greater than)</td></tr>
<tr><td>0x7</td><td>ne</td><td>NE</td><td>NE (not equal)</td></tr>
<tr><td>0x8</td><td>e</td><td>EQ</td><td>EQ (equal)</td></tr>
<tr><td>0x9</td><td>nlh</td><td></td><td>NLG (not less than and not greater than)</td></tr>
<tr><td>0xa</td><td>he</td><td>GE</td><td>GE (greater than or equal)</td></tr>
<tr><td>0xb</td><td>nl</td><td></td><td>NL (not less than)</td></tr>
<tr><td>0xc</td><td>le</td><td>LE</td><td>LE (less than or equal)</td></tr>
<tr><td>0xd</td><td>nh</td><td>LEU</td><td>NG (not greater than)</td></tr>
<tr><td>0xe</td><td>no</td><td></td><td>NO (no overflow)</td></tr>
<tr><td>0xf</td><td></td><td></td><td></td></tr>
</table>

I also like the idea of making each suffix exactly two characters long, but I suspect it is better to stick more closely to GAS. If every suffix were to be two characters, I would substitute as follows:

* `O`  -> `OV` (overflow)
* `NGE` -> `LO` (less than or overflow)
* `NLE` -> `GO` (greater than or overflow)
* `NLG` -> `EO` (equal or overflow)

We'd need to decide whether to keep the current mnemonics around as aliases or not. I think we should keep `BVS` but the rest can probably go.

We could replace `GT` with `H`, `EQ` with `E` and so on but that feels like a step too far. These suffixes are more widely used than the overflow ones and `H` would conflict with our uses of `H` for half-word.

**Comment by bradfitz** [comment]
@mundaym, this breaks s390x assembly code in the wild, right? The go1compat promise doesn't cover that, so if you're all cool with this at IBM, it's up to you.

**Comment by mundaym** [comment]
The only s390x assembly that I know of lives in the Go standard library, so it can be updated at the same time. We'll probably add some to x/crypto at some point, but there isn't any there yet. So I don't think s390x asm compatibility is currently that important in practice, particularly for the less heavily used mnemonics. Having said that I might just keep the old mnemonics around anyway when/if I do eventually get round to submitting this change, just in case.

I've held off on this because allowing the compiler to use all these modes adds a lot of complexity to the SSA rules and it isn't completely clear to me that it is worth it yet. I'll move this to the unplanned milestone for now.

**Comment by bradfitz** [comment]
SGTM. Feel free to make the "breaking" change & remilestone to Go 1.10 if you'd like.

**Comment by mundaym** [comment]
[CL 196558](https://golang.org/cl/196558) adds mnemonics for these instructions that allow the condition code mask to be manually specified (e.g. rather than using the `EQ` suffix you can supply the equivalent condition code mask ,`$8`). This is just as flexible as the extended mnemonics so I don't think it is worth adding the extended mnemonics at this time.
