### ISSUE TITLE
runtime: vlop_arm.s symbols aren't in package runtime

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19507]
runtime/vlop_arm.s declares a bunch of global symbols outside of the Go symbol namespace:

    $ grep ^TEXT runtime/vlop_arm.s
    TEXT _mulv(SB), NOSPLIT, $0
    TEXT _sfloat(SB), NOSPLIT, $68-0 // 4 arg + 14*4 saved regs + cpsr + return value
    TEXT runtime·_sfloatpanic(SB),NOSPLIT,$-4
    TEXT udiv(SB),NOSPLIT,$-4
    TEXT _divu(SB), NOSPLIT, $16-0
    TEXT _modu(SB), NOSPLIT, $16-0
    TEXT _div(SB),NOSPLIT,$16-0
    TEXT _mod(SB),NOSPLIT,$16-0
    TEXT runtime·_mul64by32(SB), NOSPLIT, $0
    TEXT runtime·_div64by32(SB), NOSPLIT, $0

It seems like these functions should all be consistently "runtime·" prefixed.

**Comment by alexbrainman** [comment]
See https://github.com/golang/go/issues/19198#issuecomment-281539187 for more of the same.

Alex

**Comment by aclements** [comment]
@mdempsky's change was pretty aggressive. Should we instead simply prefix these symbols? Are we concerned about assembly code calling them directly?
