### ISSUE TITLE
mime/multipart: add 'Size int64' to FileHeader struct

### ISSUE THREAD

**Issue by itsjamie** [golang/go#19501]
When receiving a file from a form upload, it is sometimes required to be able to grab the individual file content length, rather than limiting the size of the entire request body.

However, when using `http.Request.FormFile()` you are given a `multipart.File`, which is implemented as either an `io.SectionReader` or `os.File` depending on whether the file was larger than the defined max multipart memory size. The SectionReader is wrapped in a little struct `sectionReadCloser` for a no-op close.

After looking at and implementing this size check. I was wishing to have a simpler method to implement checking the size, where right now to check, you can upgrade the sectionReadCloser into a "sizer". When it's a os.File, you could either Stat() and check the size or seek to the end, grab the number of bytes read, seek to the start, and then proceed.

Example:
```
func uploadHandler(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(); err != nil {
		http.Error(w, http.StatusText(http.InternalServerError()), http.InternalServerError())
		return
	}

	file, _, err := r.FormFile("fileupload")

	type sizer interface {
		Size() int64
	}

	var size int64
	sz, ok := file.(sizer)
	if !ok {
		// we likely have a os.File here
		// we can Stat()
		//   - FileInfo has Size()
		// alternatively
		//   - size, err = Seek(0, 2) (bytes to end)
		//   - _, err = Seek(0, 0)
	} else {
		size = sz.Size()
	}

	// use the size for setting Content-Length when forwarding upload to a object store
	// use it for logging time/size ratio to determine upload connection
	// etc...
}
```

If possible, adding Size() directly to the multipart.File interface would be great, but in some conversation on Gopher Slack, it was pointed out this would violate the Go 1 Compat. Since this is the case, I'd be open to other ideas here, but at the very least I would like to propose wrapping the os.File that is returned in a private struct similar to sectionReadCloser to add a Size() method to make `multipart.File` a single interface upgrade to get the file size.

**Comment by rsc** [comment]
It seems like the first thing we'd need to do is decide whether we're going to enumerate the possible interfaces in a multipart.File. To date, the only thing we've guaranteed is that when it's on disk it is a *os.File:

```
$ go doc multipart.File
package multipart // import "mime/multipart"

type File interface {
	io.Reader
	io.ReaderAt
	io.Seeker
	io.Closer
}
    File is an interface to access the file part of a multipart message. Its
    contents may be either stored in memory or on disk. If stored on disk, the
    File's underlying concrete type will be an *os.File.
```

It's guaranteed to be a Seeker, so you can Seek to the end and look at the resulting offset. That's what http.ServeContent does.

**Comment by itsjamie** [comment]
Yeah, using Seek in a style similar to http.ServeContent is what I ended up doing for the actual code I wrote for what triggered the proposal. So that is how I handled the case where the underlying implementation doesn't already have a Size() method that would be quicker.

I don't think we need to enumerate every possible interface of `multipart.File`. The intention here was that I had a case where knowing the Content-Length for a subsequent request ahead of time was going to prevent having to read the data from one buffer into another purely to get the length.

**Comment by bradfitz** [comment]
Seems like a `Size int64` field could be added to https://golang.org/pkg/mime/multipart/#FileHeader ?

Somebody want to try that?

**Comment by rsc** [comment]
Approving for adding Size int64 to FileHeader.

**Comment by itsjamie** [comment]
@rsc @bradfitz Thank you!
