### ISSUE TITLE
regexp `\s*` doesn't match string "asdf  \t\nkkk" (but `\s+` works)

### ISSUE THREAD

**Issue by fishy** [golang/go#19505]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
darwin-amd64

### What did you do?
https://play.golang.org/p/6uXcuL3iyF

### What did you expect to see?
Both `\s*` and `\s+` should match the substring of "  \t\n"

### What did you see instead?
`\s+` works, but `\s*` doesn't match.

**Comment by bradfitz** [comment]
You only requested one match, and the `\s*` matched first at the beginning, with length 0.

Try the `All` matching variants.

**Comment by bradfitz** [comment]
That is, https://play.golang.org/p/7_wcF8hqJA
