### ISSUE TITLE
proposal: round-out complex number operator support by adding ordering.

### ISSUE THREAD

**Issue by splace** [golang/go#19500]
when i try to drop-in support for another built-in type, in this case from floatXX to complexXX, it fails due to lack of support for ordering complex numbers.

from reading around i see some mathematicians saying they have, and some say they don't have, this property, I’m not sure, but it seems to me that the real issue is that there are several, so its mathematically undefined, but that practically you could make a decision and just define what you were using. (if you need something else then use a library.)

and for me, practically and simply, you could compare their absolute squares;

ie   (x+yi) [<|>] (a+bi)   ===   x*x+y*y [<|>] a*a+b*b

(so ordered by the distance, in the complex plane, from origin.)

i think because complex numbers are built-in makes them having uniform operator support really desirable, so much so that having something is better than having a perfect answer, which, in this case, i think really just doesn't exist anyway.

**Comment by ALTree** [comment]
Note that this was rejected in the past; see #9681 ("spec: Complex number types should support " > < <= >=" operators").

**Comment by splace** [comment]
didn't see that, but yes its EXACTLY what i'm saying, seems to of been dismissed very quickly though.

**Comment by josharian** [comment]
The complex numbers are not ordered. True, one can define orderings on them, but that doesn't mean any one of those ordering should be built into the language.

**Comment by griesemer** [comment]
@josharian said is all. There's nothing dismissive about that, it's simply a mathematical fact (that they don't have a natural ordering).

Any ordering imposed will depend on the specific use case and thus needs to be implemented explicitly. We will not add a default ordering for complex numbers to the language.

**Comment by splace** [comment]
"complex numbers are not ordered. True, one can define orderings on them"

sure about that?

"ordering imposed will depend on the specific use case and thus needs to be implemented explicitly"

so if complex numbers were library(s) then this wouldn't be an issue.

**Comment by griesemer** [comment]
https://en.wikipedia.org/wiki/Complex_number#Ordering

Because there is no natural linear ordering for complex numbers, Go doesn't define some (essentially arbitrary) ordering.

I don't know that there's anything else to say about this here. If you want a specific ordering, you will have to define it yourself.

**Comment by splace** [comment]
OK, never-mind, complex numbers aren't really worth significant effort to support for me. i'll just drop them.
