### ISSUE TITLE
net: TestVariousDeadlines is flaky

### ISSUE THREAD

**Issue by fuzxxl** [golang/go#19519]
### What version of Go are you using (`go version`)?

    go version go1.8 freebsd/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/fuz/src/go"
GORACE=""
GOROOT="/home/fuz/go"
GOTOOLDIR="/home/fuz/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build535249256=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-I/home/fuz/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/fuz/lib"
```

`uname -a` output:

    FreeBSD miso 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

`ifconfig` output:

```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4019b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,VLAN_HWTSO>
	ether 34:e6:d7:60:b2:c5
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 1c:65:9d:0d:70:31
	inet 10.53.43.185 netmask 0xffff0000 broadcast 10.53.255.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: IEEE 802.11 Wireless Ethernet MCS mode 11na
	status: associated
	ssid clt channel 100 (5500 MHz 11a ht/40+) bssid fc:5b:39:f6:fa:e9
	regdomain 106 indoor ecm authmode WPA2/802.11i privacy ON
	deftxkey UNDEF AES-CCM 2:128-bit AES-CCM 3:128-bit txpower 30 bmiss 7
	mcastrate 6 mgmtrate 6 scanvalid 60 ampdulimit 64k ampdudensity 8
	shortgi wme burst roaming MANUAL bintval 102
	groups: wlan 

```

`sysctl hw.model` output:

    hw.model: Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz

### What did you do?

I tried to update my Go 1.6 installation to Go 1.8 by removing the Go installation, downloading the source code from [here](https://storage.googleapis.com/golang/go1.8.src.tar.gz) and running `all.bash`.

### What did you expect to see?

A successful build followed by a successful pass through the test suite.

### What did you see instead?

A successful build followed by `TestVariousDeadlines` failing:

```
--- FAIL: TestVariousDeadlines (8.01s)
	timeout_test.go:877: 1ns run 1/1
	timeout_test.go:902: for 1ns run 1/1, good client timeout after 53.221µs, reading 0 bytes
	timeout_test.go:916: for 1ns run 1/1, timeout waiting for server to finish writing
FAIL
FAIL	net	9.515s
```

**Comment by josharian** [comment]
Not just freebsd. Just failed locally on darwin/amd64:

```
--- FAIL: TestVariousDeadlines (5.03s)
	timeout_test.go:878: 1ns run 1/1
	timeout_test.go:903: for 1ns run 1/1, good client timeout after 38.928µs, reading 0 bytes
	timeout_test.go:913: for 1ns run 1/1, server in 177.208µs wrote 32768: readfrom tcp4 127.0.0.1:59054->127.0.0.1:59055: write tcp4 127.0.0.1:59054->127.0.0.1:59055: write: broken pipe
	timeout_test.go:878: 2ns run 1/1
	timeout_test.go:903: for 2ns run 1/1, good client timeout after 4.776µs, reading 0 bytes
	timeout_test.go:913: for 2ns run 1/1, server in 89.252µs wrote 32768: readfrom tcp4 127.0.0.1:59054->127.0.0.1:59056: write tcp4 127.0.0.1:59054->127.0.0.1:59056: write: broken pipe
	timeout_test.go:878: 5ns run 1/1
	timeout_test.go:903: for 5ns run 1/1, good client timeout after 8.099µs, reading 0 bytes
	timeout_test.go:917: for 5ns run 1/1, timeout waiting for server to finish writing
FAIL
FAIL	net	6.371s
```

**Comment by josharian** [comment]
This continues to be one of the more common flakes on the dashboard. Moving the milestone back to 1.11.

**Comment by mvdan** [comment]
Any hints to reproduce this issue? I just failed to do so on my linux/amd64 laptop, reaching 5000 successful runs with:

    stress -p 256 ./net.test -test.run TestVariousDeadlines$ -test.cpu 1

Might be useful to start pasting builder failure logs here, to see if there is a pattern. For example, this might show up only on BSDs.

**Comment by josharian** [comment]
https://github.com/aclements/go-misc/tree/master/greplogs might be helpful.

**Comment by Mic92** [comment]
Also confirmed for nixpkgs on macOS.

**Comment by bcmills** [comment]
Here's a repro in the builders:
https://build.golang.org/log/2f56b2bc471c2d8d68f862238d750ffcfc88c34d

**Comment by millerresearch** [comment]
The plan9_386 failure is very frequent but slightly different - it's always "timeout (5s) waiting for client to timeout  (...) reading" where the reported freebsd and darwin failure is "timeout waiting for server to finish writing".

On plan9_386, I have never observed the failure on real hardware, or on qemu running on an otherwise idle server.  This weekend I have managed to reproduce it (very intermittently) by simulating a busy server, by running qemu in parallel with many cpu-bound "nice --10" processes.  My hypothesis is that it's the measurement of time that's flawed, not the network implementation.

@fuzxxl and @josharian , are your observed failures on real hardware or on virtual machines?

**Comment by fuzxxl** [comment]
@millerresearch The failure was observed on real hardware (a Dell Precision M4800 running FreeBSD 11.0 I think).  I am currently not able to reproduce it using Go 1.10 on the same machine now running FreeBSD 11.2.

**Comment by bcmills** [comment]
Another occurrence on FreeBSD: https://storage.googleapis.com/go-build-log/54e5f909/freebsd-amd64-12_0_325e1e39.log

**Comment by bcmills** [comment]
`linux-s390x-ibm`: https://build.golang.org/log/c82cf7bb1f5da349bf7b69f741d30eb89b13d143

```
--- FAIL: TestVariousDeadlines (0.00s)
    --- FAIL: TestVariousDeadlines/750ns-1 (0.00s)
        timeout_test.go:445: client Copy = 8192, read |0: not pollable; want timeout
```

**Comment by bcmills** [comment]
FreeBSD 11.2:
https://build.golang.org/log/749dfbe61f52812dffb3374d94ee16020e9145d8
https://build.golang.org/log/be70f2984f697598c0f4bcfa2e118afc7e5701e7

**Comment by bcmills** [comment]
FreeBSD 11.2 again:
https://build.golang.org/log/5d61406d94aa144131e106cb2bc89c2f4f19e949

**Comment by katiehockman** [comment]
This is flaking for darwin-amd64-nocgo as well:
https://build.golang.org/log/671f5a8fc07f8d33a418dd2966c660389e4e230f

/cc @mikioh

**Comment by bcmills** [comment]
More FreeBSD 11.2:
https://build.golang.org/log/567d0bbf7699b74402755b8e2f8f8aa46729b0a3
https://build.golang.org/log/cfa8864b7f6294342f0649b49e43baa944426ae8

**Comment by bcmills** [comment]
The `linux-s390x-ibm` failure mode in https://github.com/golang/go/issues/19519#issuecomment-472460209 is different, but the `darwin-amd64-nocgo` failure mode seems to be the same as for FreeBSD. IIRC, macOS is also derived from BSD — perhaps the `net` package (or the test) is relying on assumptions about system calls that don't hold for BSD flavors of those syscalls?
