### ISSUE TITLE
test: issue10958 test flaky (especially plan9/arm)

### ISSUE THREAD

**Issue by 0intro** [golang/go#19521]
Since CL [36206](https://golang.org/cl/36206) has been merged, [issue10958](https://github.com/golang/go/blob/d71f36b5aa1eadc6cd86ada2c0d5dd621bd9fd82/test/fixedbugs/issue10958.go) test (#10958) has been enabled and is regularly failing on plan9/arm builder.

```
##### ../test
# go run run.go -- fixedbugs/issue10958.go
exit status: 'go 70591: kill'

FAIL	fixedbugs/issue10958.go	10.568s
2017/03/10 11:26:08 Failed: exit status: 'runtest.exe 66696: 1'
skipped due to earlier error
```

See https://build.golang.org/log/a02c4878ff9accc2a149e3d9fb902ba04debcaf9

**Comment by ALTree** [comment]
Likely not plan9's fault: the test is just flaky. I sometimes can reproduced the failure on linux/amd64

```##### ../test
# go run run.go -- fixedbugs/issue10958.go
signal: killed

FAIL	fixedbugs/issue10958.go	10.012s
2017/03/13 09:35:37 Failed: exit status 1
skipped due to earlier error
```

**Comment by ALTree** [comment]
General flakiness of `issue10958.go` is also tracker in #18589

**Comment by bradfitz** [comment]
Okay, we can close this one in favor of #18589.
