### ISSUE TITLE
encoding/json: Wrong type in a field breaks decoding of following fields

### ISSUE THREAD

**Issue by Hunsin** [golang/go#19526]
### What version of Go are you using (`go version`)?
1.7.3 and 1.8

### What operating system and processor architecture are you using (`go env`)?
amd64 linux

### What did you do?
[Go Playground link](https://play.golang.org/p/NX2BkP15hU)

### What did you expect to see?
Type of Age in go struct is string, it will return {Name: "John", Age: "", Gen: "M"} and error message.
Output:
json: cannot unmarshal number into Go struct field person.age of type string
JohnM

### What did you see instead?
In raw json, "gen" field shows after "age", it seems wasn't touched by decoder.
Output: 
json: cannot unmarshal number into Go struct field person.age of type string
John

**Comment by bradfitz** [comment]
I suppose we could document this, but it's been like this forever so I don't see a good reason to change it.
