### ISSUE TITLE
fmt.Printf("%T), prints wrong type

### ISSUE THREAD

**Issue by noypi** [golang/go#19528]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=D:\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=M:\gopath
set GORACE=
set GOROOT=D:\dev\go
set GOTOOLDIR=D:\dev\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
Run the code below:
```
package main

import(
	"fmt"
)

type SomeError error

func main(){
	var e SomeError = SomeError(fmt.Errorf("the error message"))
	fmt.Printf("%T: %v", e, e)
}

```

### What did you expect to see?
should print:
main.SomeError: the errormessage

### What did you see instead?
*errors.errorString: the error message

**Comment by opennota** [comment]
I think fmt.Printf is right. SomeError is an interface, so the real type is printed.

See also https://divan.github.io/posts/misusing_error_interface/

**Comment by noypi** [comment]
error is an interface, didn't know that. =)
