### ISSUE TITLE
strings package

### ISSUE THREAD

**Issue by pjebs** [golang/go#19527]
What is the difference between: `ToUpper( )` and `ToTitle( )`.
They appear to be the same.

In PHP, 
the builtin titlecase function capitalizes every word in string and NOT every letter.
Perhaps this is a bug.

**Comment by pjebs** [comment]
Then to make things more confusing there is a `Title( )` function which appears to do what the php titlecase function does (bar the documented bug)

**Comment by pjebs** [comment]
Then to make things more confusing there is a `Title( )` function which appears to do what the php titlecase function does (bar the documented bug)

**Comment by pjebs** [comment]
http://stackoverflow.com/questions/18559587/confusing-toupper-and-totitle

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by bradfitz** [comment]
http://unicode.org/faq/casemap_charprop.html#4
