### ISSUE TITLE
Use dlv attach PID and it tells error

### ISSUE THREAD

**Issue by yingqin678** [golang/go#19531]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\isource\go-workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?
package main

import (
	"fmt"
	"sync"
	"time"
)

func dostuff(wg *sync.WaitGroup, i int) {
	fmt.Printf("goroutine id %d\n", i)
	time.Sleep(300 * time.Second)
	fmt.Printf("goroutine id %d\n", i)
	wg.Done()
}

func main() {
	var wg sync.WaitGroup
	workers := 10

	wg.Add(workers)
	for i := 0; i < workers; i++ {
		go dostuff(&wg, i)
	}
	wg.Wait()
}
### What did you expect to see?
I use  'go build' or '$ go build -ldflags="-linkmode=internal"' to generate the binary file 
run the binary file
$ ./go.exe
goroutine id 1
goroutine id 0
goroutine id 3
goroutine id 2
goroutine id 6
goroutine id 7
goroutine id 8
goroutine id 5
goroutine id 9
goroutine id 4
goroutine id 1
goroutine id 0
goroutine id 3
goroutine id 2
goroutine id 9
goroutine id 5
goroutine id 8
goroutine id 7
goroutine id 6
goroutine id 4

another console :
$ ps
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
    12984   12408   12984      12920  pty1     4344533 19:48:22 /d/isource/go-workspace/src/go_test/src/mian/go/go
    11736    1844   11736       9112  pty0     4344533 19:48:27 /usr/bin/ps
    12408   12068   12408       7920  pty1     4344533 17:29:46 /usr/bin/bash
     1844   10948    1844      11424  pty0     4344533 17:19:16 /usr/bin/bash
    12068       1   12068      12068  ?        4344533 17:29:46 /usr/bin/mintty
    10948       1   10948      10948  ?        4344533 17:19:16 /usr/bin/mintty
$ dlv  attach 12984
could not attach to pid 12984: decoding dwarf section info at offset 0x0: too short

### What did you see instead?
i wish to succeed to attach to the program

**Comment by AlekSi** [comment]
That issue should go to [delve](https://github.com/derekparker/delve) issue tracker.

**Comment by bradfitz** [comment]
Yeah, as @AlekSi said, we don't maintain delve so there's nothing we can help with here. Please contact the delve issue tracker or forums.

**Comment by yingqin678** [comment]
sorry,i just took the wrong page
