### ISSUE TITLE
cmd/internal/obj/arm: BX is assembled incorrectly by ARM assembler

### ISSUE THREAD

**Issue by benshi001** [golang/go#19530]
As ARM architecture reference manual described,

BX.EQ (R0) should be assembled to 0x012fff10
BX.CS (R2) should be assembled to 0x212fff12

but they are assembled to quite strange values.

This issue is due to line 2153 - 2171 of cmd/internal/obj/arm/asm5.go

I will commit a patch to fix it later.

**Comment by benshi001** [comment]
Fixed in patch set 4 of CL 37662.

**Comment by cherrymui** [comment]
If I recall correctly BX is used specifically for NaCl. It shouldn't be used in general. I am not sure this can be changed. I'd have to take a another look.

**Comment by benshi001** [comment]
I do not know the special use of BX. Maybe we need not it become general, since thumb is not supported currently.
