### ISSUE TITLE
crypto/x509.ParseCertificate use too many memory when run websocket with TLS, how can I reduce it.

### ISSUE THREAD

**Issue by timezstyle** [golang/go#19539]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
Centos 6
linode 2G

### What did you do?
websocket server
https://play.golang.org/p/5GYW-5VoJD

crypto/x509.ParseCertificate used over 500M of memory when connected with 1.5k clients.

### Question
Any suggestion to reduce memory usage ?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

I would start a thread on golang-nuts about this. Be sure to post your pprof output.

If you find a concrete suggest of something Go could do better, feel free to file specific bug(s). But we don't keep general questions about how to optimize code open.
