### ISSUE TITLE
Uninitialized map

### ISSUE THREAD

**Issue by mrajashree** [golang/go#19549]
When creating a map in Golang, if it's not initialized before using, is it possible to first alert the programmer through an error after `go build`, instead of a runtime error?

**Comment by jimmyfrasche** [comment]
Reading from a nil map is valid https://play.golang.org/p/kCGe4djrlA

**Comment by mrajashree** [comment]
@jimmyfrasche Oh I see

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
