### ISSUE TITLE
cmd/gofmt: Unexpected formatting with one line functions/methods.

### ISSUE THREAD

**Issue by nsf** [golang/go#19544]
### What version of Go are you using (`go version`)?

go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

Doesn't matter.

### What did you do?

gofmt the following code:

```go
package main

func OneLineFunc() {}
func FuncWithVeryLongName() { // comment
}

func main() {
}
```

### What did you expect to see?

```go
package main

func OneLineFunc() {}
func FuncWithVeryLongName() { // comment
}

func main() {
}
```

### What did you see instead?

```go
package main

func OneLineFunc()            {}
func FuncWithVeryLongName() { // comment
}

func main() {
}
```

----

Discovered this case by accident. It looks a bit unexpected to me. Whether it can be considered as a bug or not is obviously up to you. I don't write code like that, so it's not a critical issue for me, but I thought it's worth reporting.

In case you didn't notice the problem. Braces of the one-line function are weirdly aligned with the comment on the next line. Or if the first function is longer than the second one, comment section will be weirdly aligned with braces.

**Comment by griesemer** [comment]
I agree this is a bit odd. Not urgent but we should probably address this. Thanks for the report.

**Comment by fraenkel** [comment]
Seems to be caused by

https://github.com/golang/go/blob/master/src/go/printer/nodes.go#L1626
`p.funcBody(p.distanceFrom(d.Pos()), vtab, d.Body)`

If the vtab is replaced with blank, all is well. But was there a reason?

**Comment by griesemer** [comment]
The vtab controls the column layout. We want one here because if we have multiple one-line functions w/o empty lines between them, we want the function bodies to align (at least that's what they are doing now).

The assumption was that there would be an empty line before and after any multi-line function, and then the issue you're seeing doesn't occur. (That's also the work-around in this case).
