### ISSUE TITLE
x/tools/cmd/gotype: undefined: types.SizesFor

### ISSUE THREAD

**Issue by lurkermike** [golang/go#19545]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

Linux amd64

### What did you do?

```
> git pull
Already up-to-date.

> git rev-parse HEAD
381149a2d6e5d8f319ccf04bfefc71e03a78b868

> go build
# golang.org/x/tools/cmd/gotype
./gotype.go:285: undefined: types.SizesFor

```

I believe this is caused by the following commit:

```
commit 381149a2d6e5d8f319ccf04bfefc71e03a78b868
Author: Robert Griesemer <gri@golang.org>
Date:   Mon Mar 13 10:28:12 2017 -0700

    cmd/gotype: re-introduce gotype command at traditional location
```

**Comment by griesemer** [comment]
1.8 doesn't support types.SizesFor yet.
