### ISSUE TITLE
Go 1.8 Shutdown without closing listener

### ISSUE THREAD

**Issue by matthewmueller** [golang/go#19556]
The shutdown feature is a great addition, but it seems to do 2 things:

1) drain existing connections
2) close the listener

It'd be nice to be able to drain existing connections without closing the listener. This would allow graceful reloads.

**Comment by bradfitz** [comment]
net.Listener is an interface. You can write this yourself with your own net.Listener wrapper type.

Let's start with that (and you can put it on github somewhere) and if we later find that many users want it, then we can discuss promoting it by putting it into the standard library. That's how Shutdown got started. (The primitives were there, but it wasn't provided pre-assembled.)

**Comment by matthewmueller** [comment]
Sounds good – thanks for the quick response!
