### ISSUE TITLE
hcigvjrjir

### ISSUE THREAD

**Issue by natefinch** [golang/go#19557]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ianlancetaylor** [comment]
hcigvjrjir

**Comment by natefinch** [comment]
Damn, sorry, toddler.

**Comment by ianlancetaylor** [comment]
No worries, at least it wasn't the cat.
