### ISSUE TITLE
x/tools/cmd/ssadump: doesn't compile

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19550]
The x/tools build is broken across the board:

https://build.golang.org/log/5caa4ff768a880d6f306a9546cb060eb5e592c29 etc:
```
# golang.org/x/tools/cmd/ssadump
2017/03/14 14:27:21 duplicate symbol golang.org/x/tools/go/ssa.(*BuilderMode).String (types 1 and 1) in main and $WORK/golang.org/x/tools/go/ssa.a(_go_.o)
```

**Comment by ianlancetaylor** [comment]
I think that this was broken by https://golang.org/cl/38139 and I think that the fix is in https://golang.org/cl/38156.

**Comment by ianlancetaylor** [comment]
CC @dr2chase @philhofer

**Comment by philhofer** [comment]
Confirmed dupe of #19548.

**Comment by josharian** [comment]
Closing as dup.
