### ISSUE TITLE
cmd/compile: ctz rules on s390x

### ISSUE THREAD

**Issue by randall77** [golang/go#19551]
I don't think these rules do the right thing if the input argument is 0.
What does FLOGR return if the input is 0?
Ctz64 should return 64 if the input is 0, and Ctz32 should return 32 if the input is 0.  But FLOGR is used for both, one of them at least has to be wrong.

It probably doesn't matter at the moment as the runtime probably never calls Ctz with a 0 argument.  But I'm about to make math/bits use the intrinsic, and there it matters.

@mundaym

**Comment by mundaym** [comment]
I can see why the rules looks dubious but they are correct. I've created a little program to demonstrate:

https://play.golang.org/p/LFdFii1YQC

Thanks for opening the issue though, always worth double checking these things :).

**Comment by randall77** [comment]
Ok, I was confused about the bit twiddling.  (CtzX 0) doesn't actually pass 0 to FLOGR.
Thanks for looking into it.
