### ISSUE TITLE
x/crypto/ssh: expose channel IDs

### ISSUE THREAD

**Issue by jaksi** [golang/go#19568]
Currently there is no way to identify channels. Sessions can be identified by the `SessionID` method of `ConnMetaData`, but there's no such thing for channels.
Internally, a local and a remote ID is stored for each channel, either of which could be used for this.
This would be useful for correlating logs by sessions and channels.

**Comment by hanwen** [comment]
this has been discussed before, but the short answer is: no, the local/remote IDs can't be used for this. 

The meaning of those IDs is tied to the map in which they are administrated. The map is protected by a mutex

https://go.googlesource.com/crypto/+/459e26527287adbc2adcc5d0d49abff9a5f315a7/ssh/mux.go#23

so you can't use those IDs unless you also hold the mutex.

**Comment by hanwen** [comment]
you can build your own channel ID mechanism by using the extra data payload in OpenChannel/Accept.
