### ISSUE TITLE
net/http: request context is not propagating deadlines

### ISSUE THREAD

**Issue by rakyll** [golang/go#19562]
Consider the following program:

```
go func() {
    req, _ := http.NewRequest("GET", "http://localhost:8080", nil)
    ctx, cancel := context.WithDeadline(req.Context(), time.Now().Add(5*time.Second))
    defer cancel()

    req = req.WithContext(ctx)
    _, err := http.DefaultClient.Do(req)
    if err != nil {
        log.Println(err)
    }

}()

http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    fmt.Println(r.Context().Deadline())
    select {
    case <-r.Context().Done():
        fmt.Fprintln(w, "done")
    }
})
http.ListenAndServe(":8080", nil)
```

The output of this program is:
```
0001-01-01 00:00:00 +0000 UTC false
2017/03/15 10:44:55 Get http://localhost:8080: context deadline exceeded
```

Instead, I expected to see a non-zero deadline and "done" written to the response body after 5 seconds.

Any plans to inject the deadline in a preserved header to the outgoing requests, so the handler can automatically extract them and construct the incoming request context from there.

/cc @bradfitz

**Comment by bradfitz** [comment]
I am unaware of any standards in this area and am reluctant to invent a Go-specific one.

**Comment by rakyll** [comment]
Agreeing with not inventing one if there is not an established standard.
