### ISSUE TITLE
Use fmt output colorized string on windows console is abnormal

### ISSUE THREAD

**Issue by Baozisoftware** [golang/go#19566]
### What version of Go are you using (`go version`)?
go1.8.windows-amd64

### What operating system and processor architecture are you using (`go env`)?
All use default.

### What did you do?
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("\033[32;49;1m [Test] \033[39;49;0m")
}
```

### What did you expect to see?
output:
`[Test]`(colorized)

### What did you see instead?
`[32;49;1m [Test] [39;49;0m`

**Comment by mattn** [comment]
use https://github.com/mattn/go-colorable

```go
package main

import (
	"fmt"

	"github.com/mattn/go-colorable"
)

func main() {
	out := colorable.NewColorableStdout()
	fmt.Fprintln(out, "\033[32;49;1m [Test] \033[39;49;0m")
}
```
![color on cmd.exe](http://go-gyazo.appspot.com/cba8ebea8d7ea38a.png)

This code works on Linux, Darwin, etc.

**Comment by Baozisoftware** [comment]
ありがとうございました。
