### ISSUE TITLE
cmd/link: request backport of CL 38131 to go 1.8

### ISSUE THREAD

**Issue by laboger** [golang/go#19578]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8

### What operating system and processor architecture are you using (`go env`)?
RH 7 ppc64le

I'd like to request a backport of https://go-review.googlesource.com/c/38131/ to go1.8.  This patch is needed to fix a problem in the Kubernetes build when using go 1.8.

**Comment by bradfitz** [comment]
Sounds fine to me. @ianlancetaylor?

**Comment by ianlancetaylor** [comment]
SGTM

**Comment by laboger** [comment]
Sorry not sure of the process here, should I create a CL against go 1.8?

**Comment by ianlancetaylor** [comment]
@laboger Sure, that would help.  Thanks.

**Comment by aclements** [comment]
Closing since committed to release branch.
