### ISSUE TITLE
Question About string & []byte

### ISSUE THREAD

**Issue by dingkaich** [golang/go#19585]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dingkai/windows/HelloWorld/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
freshman about program

### What did you expect to see?
more golang doc in chinese

=======below is my issue =========
golang code:	
      str := "mycgomain1111"
      bytestr := []byte(str)
      C.output((*C.char)(unsafe.Pointer(&bytestr1[0])))

C code:
      void output(char * str)
      {
	int len=strlen(str);
	printf("%s,len=%d,last=%d\n",str,len,str[len]);
      }

When I change sting to []byte , and then change []byte to pointer char * ,
should I need to append '\x00'  in the last []byte ?

I have do some test , if i don't append ,it work well ! I want to know why ?
I am worried that it will make access  wrong memery address!

Could you help me ? Please !

**Comment by cznic** [comment]
Please see [wiki/Questions](https://github.com/golang/go/wiki/Questions).

**Comment by ALTree** [comment]
Yep, we don't use the issue tracker for questions, so closing this.
