### ISSUE TITLE
hex.Encode utf-8

### ISSUE THREAD

**Issue by LEGOlord208** [golang/go#19589]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOOS="linux"
GOARCH="amd64"

### What did you do?
So, I saw the hex.EncodeToString method took a byte array.  
I have made something in Java a while ago, and remembered that had to take take a char array to correctly do UTF-8.

So I tried UTF-8 in Go's EncodeToString...  
https://play.golang.org/p/ezGLPIhuEd 

### What did you expect to see?
Well, I sort of expected the error.  
But, it *should* have given 48616c6ce5 (Hallå).

### What did you see instead?
It gave 48616c6cc3a5 (HallÃ¥).

This is because you use a byte array, and the 'å' character gets stored as two separate bytes. When converted byte-by-byte, it also converts the 'å' to separate bytes.

Online test tool: http://www.rapidtables.com/convert/number/hex-to-ascii.htm  
My Java program: https://krake.one/software#crypter

EDIT: The `strconv.FormatInt` is not affected by this, at it takes an int and not a byte.  
See https://play.golang.org/p/SoMY-gNbDN

**Comment by cznic** [comment]
> But, it should have given 48616c6ce5 (Hallå).

Why should be an arbitrary rune encoded as a single byte in the first place? How would that work for runes > 255? Moreover, `hex.EncodeToString` should never interpret its `[]byte` argument to be of any particular encoding, it's just a string of bytes which gets hex encoded. How would otwerwise be binary data correctly hex encoded? And the result *is* correct: [playground](https://play.golang.org/p/Y9eYpoyc8X).

**Comment by LEGOlord208** [comment]
Hmm... good points.

I am still confused why every single online tool I try give `48616c6ce5` though...

**Comment by ianlancetaylor** [comment]
The other tools you are looking at are presumably using Latin-1 encoding rather than UTF-8.

Closing because I don't see a bug here.

**Comment by LEGOlord208** [comment]
Thanks! That makes sense! Sorry for disturbing
