### ISSUE TITLE
website: put download buttons on install page

### ISSUE THREAD

**Issue by broady** [golang/go#19583]
The buttons at the top of golang.org/dl/ should be on golang.org/doc/install

**Comment by fgm** [comment]
Is this about the top menu or the featured downloads, or even something else no longer there after the site relooking ? At this point the top menu is the same, only the page width differs, with dl/ being width constrained and doc/install being fluid.

**Comment by changkun** [comment]
@ALTree Looks like this can be closed? Did I misread something here?

**Comment by ALTree** [comment]
Yeah I think it's about the "Download Go for Windows" button which is now present on https://golang.org/doc/install too. I think we can close.
