### ISSUE TITLE
crypto/cipher: aesGcm: customize the size of the Tag

### ISSUE THREAD

**Issue by gleroi** [golang/go#19594]
#### What did you do?
https://play.golang.org/p/3lHakDk4WV

i'm working on AES GCM encrypted data from the DLMS/Cosem protocol.
This protocol use AES GCM 128 bits but only keep the 12 bytes of the tag

I you look in the code of crypto/cipher/gcm.go:gcm.Open, you'll see that the 12 leftmost bytes are identical, i just need a way to limit the comparison to 12 bytes.

#### What did you expect to see?

I expect to be able to configure the size of the tag.

#### System details

```
go version go1.8 windows/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="D:\Projets\go"
GORACE=""
GOROOT="D:\Go"
GOTOOLDIR="D:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\GL262BEN\AppData\Local\Temp\go-build100801603=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.8 X:framepointer
gdb --version: GNU gdb (GDB) 7.6.1
```

**Comment by bradfitz** [comment]
To @agl for decision.

**Comment by agl** [comment]
This is a reasonable request. The different tag size should be exposed as a different AEAD, i.e. something like `NewGCMWithTagSize`.

**Comment by gleroi** [comment]
Im going to look at the contributor guidelines to propose a pull request on monday if it is ok.

**Comment by bradfitz** [comment]
The CL mailed above doesn't compile, so bumping this to Go 1.10.

**Comment by conradoplg** [comment]
I had a shot at this in a new CL (I was not sure if I could/should change the other one).
