### ISSUE TITLE
runtime: chanrecv funcs don't actually use the *chantype parameter

### ISSUE THREAD

**Issue by mvdan** [golang/go#19591]
func chanrecv(t *chantype, c *hchan, ep unsafe.Pointer, block bool) (selected, received bool)

The `t *chantype` parameter isn't actually used. I assume it could be removed, but the entry point magic scares me a bit and I don't dare do a CL myself.

Unless the parameter is actually used/needed for a reason that's not obvious given the implementation?

Found with https://github.com/mvdan/unparam.

**Comment by mvdan** [comment]
Also worth noting that `chansend` does use its `t *chantype` parameter, but only if either `raceenabled` or `msanenabled` are true. Would either of those need the type parameter at some point in the future?

**Comment by mdempsky** [comment]
The chantype is stored as a field in the hchan anyway. I think we can get rid of the parameters.

Do you want to send a CAL?

**Comment by mvdan** [comment]
Sure, I'll get on that.

> The chantype is stored as a field in the hchan anyway.

So you mean get rid of it in `chansend` too?

**Comment by mdempsky** [comment]
> So you mean get rid of it in chansend too?

Correct.

**Comment by mvdan** [comment]
Having some issues with panics, I'm likely missing some change to make the compiler and/or runtime fully aware of the new func signature. I'll post the CL on monday in any case, asking for pointers if I'm still stuck.

**Comment by mvdan** [comment]
Ah, found it - a missing `mkcall1` tweak in `gc`.
