### ISSUE TITLE
Deallocate memory issue

### ISSUE THREAD

**Issue by e4stw00d** [golang/go#19600]
### What version of Go are you using (`go version`)?
go version go1.8 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?
https://play.golang.org/p/rQQNmIs5QI

### What did you expect to see?
Expected that the memory will be deallocated.

### What did you see instead?
But after clearing slice i've got 1GB still using memory.

**Comment by bradfitz** [comment]
You didn't paste the output of your program.

But FWIW, I get:

```
39976 1740800
10000000
84821400 178833656
0
41456 178833656
```

I assume you mean MemStats.Sys is still high? The documentation suggests that's just virtual address space, which isn't necessarily even backed by physical memory after your debug.FreeOSMemory call.

But the first number (MemStats.Alloc) went down fine.

And if you print out MemStats.HeapReleased, I see `169893888` with your program. Looks like it's working fine.

Did you read all the docs on MemStats fields?

I'm going to close this, but feel free to file another bug if the docs are not accurate.

**Comment by e4stw00d** [comment]
Well, the problem was in ACTUALLY allocated amount of memory. And nothing can clean this. I'am talking about 1G memory, which just floating... Can't be used by other programs and OS.

**Comment by ianlancetaylor** [comment]
How are you measuring the memory use?  How much time are you measuring it over.  The Go runtime periodically releases unused memory back to the OS.

**Comment by e4stw00d** [comment]
Lookin in my process monitor, actually. Something about 5 minuts? I guess that's should be enough to run releasing memory.
