### ISSUE TITLE
goimports import the shortest package. But most of the time we need the relative-shortest package.

### ISSUE THREAD

**Issue by pihao** [golang/go#19615]
env:

* go version go1.8 darwin/amd64
* amd64
* Mac mini, macOS 10.12.3

There are two packages:

    github.com/longlong/bytes  # long
    github.com/short/bytes     # short

I am working in package: 

    github.com/longlong/work   # work

`goimports` import the short package when I use bytes in working package. [Playground](https://play.golang.org/p/MH_bWctES2)

But I expect import the long one, Because the are under same path `github.com/longlong`. [Playground](https://play.golang.org/p/RojAxA643V)

[goimports source code](https://github.com/golang/tools/blob/4f8578d2c095328e9192e9d0b0ea335c6ea3e9a5/imports/fix.go#L356-358)

**Comment by mvdan** [comment]
Dup of #17557.
