### ISSUE TITLE
fmt.Println fails to print math.MaxUint64

### ISSUE THREAD

**Issue by alsamylkin** [golang/go#19621]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
play.golang.org

### What operating system and processor architecture are you using (`go env`)?
play.golang.org

### What did you do?
```golang
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.MaxUint64)
}

```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/5GARX4Q2Tc

### What did you expect to see?
Successful compilation and math.MaxUint64 in standard output 

### What did you see instead?
`main.go:9: constant 18446744073709551615 overflows int`

**Comment by bradfitz** [comment]
Working as intended per the language spec: https://golang.org/ref/spec#Constants

https://play.golang.org/p/-TM6jBzFpV

See also: https://blog.golang.org/constants

**Comment by robpike** [comment]
This is just a minor confusing property of the constants defined in the math package. They are all untyped constants (see blog.golang.org/constants), so by default they promote to type `int` in a call to `Println`.

**Comment by odeke-em** [comment]
I too was once surprised by the same error message, some 2 years ago https://twitter.com/odeke_et/status/664360654875267073 but someone(Matt Siegel) educated me.
