### ISSUE TITLE
cmd/go: -compiler=gccgo: fork/exec no such file or directory

### ISSUE THREAD

**Issue by xuqingsz** [golang/go#19628]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build038947788=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
A simple helloworld.go program. GC compiler compiled ok. 
For some reason, instead, I need to compile with gccgo, but could never get it to compile. 
Any insights are appreciated. 
I also have a follow up question on whether gccgo would compile the program statically, or dynamically.

```
% cat helloworld.go 
package main
import "fmt"
func main() {
    fmt.Println("hello world")
}
```

```
%  go build -compiler gccgo helloworld.go 
go build command-line-arguments: : fork/exec : no such file or directory
% go build -compiler gccgo -gccgoflags '-static' helloworld.go
go build command-line-arguments: : fork/exec : no such file or directory
% go build -compiler gccgo -gccgoflags '-static-libgo' helloworld.go
go build command-line-arguments: : fork/exec : no such file or directory
```

With the -x option:
```
% go build -compiler gccgo -gccgoflags '-static-libgo' -x helloworld.go
WORK=/tmp/go-build148131806
mkdir -p $WORK/command-line-arguments/_obj/
mkdir -p $WORK/command-line-arguments/_obj/exe/
cd /root/tmp
"" -I $WORK -c -g -m64 -fgo-relative-import-path=_/root/tmp -o $WORK/command-line-arguments/_obj/_go_.o -static-libgo ./helloworld.go
go build command-line-arguments: : fork/exec : no such file or directory
```

```
% gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
```

### What did you expect to see?
Program compiles and generates an executable.

### What did you see instead?
'no such file or directory'

**Comment by ianlancetaylor** [comment]
Do you actually have gccgo installed on your system?

This looks like a very bad error message, but even if we fix that it still won't work for you.

**Comment by cwedgwood** [comment]
@xuqingsz I've seen this when gcc[go] isn't in PATH.

What does

> gccgo --version

say?

**Comment by xuqingsz** [comment]
I did put this issue off for some time. But you are right! This did the fix for me. Thanks.

**Comment by ianlancetaylor** [comment]
Thanks for the update.  I'm going to reopen this to get a better error message.
