### ISSUE TITLE
x/text/unicode/collate/build: docs out of date

### ISSUE THREAD

**Issue by alercah** [golang/go#19626]
The [docs](https://godoc.org/golang.org/x/text/collate/build) for (* Builder).Build() say "TODO: return Weighter instead", but the method does indeed return a Weighter. The docs should be updated.

**Comment by shurcooL** [comment]
I was curious when this was introduced, so I did some code archeology.

I had to jump from x/text, through a rename, to x/exp, to main repo, and I found it in https://github.com/golang/go/commit/f38da96755cea4fde703b4601d5959150587eab4. It looks like a TODO comment that was added during development, the task was completed, and the comment was left behind by accident.
