### ISSUE TITLE
cmd/link: binaries packed with UPX run into segfault with 1.8

### ISSUE THREAD

**Issue by unclejack** [golang/go#19625]
### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build006597881=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
foo.go:
```
package main

import "fmt"

func main() {
        fmt.Println("asd")
}
```
https://play.golang.org/p/4tyqhiibb5

```
$ go build foo.go
$ upx foo
$ ./foo
Segmentation fault (core dumped)
```

### What did you expect to see?
I expected to see "asd" printed.

### What did you see instead?
Segmentation fault (core dumped)

**Comment by bradfitz** [comment]
Have you filed a bug against upx?

**Comment by unclejack** [comment]
@bradfitz: I haven't filed a bug against UPX because this was working properly with Go 1.7.5. I don't have a strong opinion related to this. Some use UPX to get smaller binaries. It seemed to be a good idea to bring this up since Go 1.8.1 is the next release. I didn't know whether this was a known issue or not.

Please feel free to close this immediately if it's not considered an issue or a bug.

**Comment by bradfitz** [comment]
We don't maintain UPX. If things worked or didn't work at some point, that's either luck or it's because UPX did or didn't support something at one point.

I'll close this until there's any evidence that Go is violating some ELF spec or something.

**Comment by krzysztofantczak** [comment]
@unclejack FYI - just had the same problem, but i was using the same GO version on my old app and new one which was very similar to yours - simple "hello world". It seems that it throws core dump when GO binary is too small ;-)

Go binary size: 3,7M - after UPX: 897K - core dumped
Go binary size: 22M - after UPX: 4,7M - works perfectly fine.

No idea where's the actual border line for UPX to make things work, i had not that much time to play with it.

Tested with:
go1.8 linux/amd64
upx 3.91
