### ISSUE TITLE
runtime: backport CL 38012 to 1.8.1

### ISSUE THREAD

**Issue by aclements** [golang/go#19637]
https://golang.org/cl/38012 fixes #19494.

**Comment by bradfitz** [comment]
Is this worthy of a backport? It doesn't appear to be a regression from Go 1.7? At least #19494 doesn't say so.

Ask @rsc if he's sitting there.

**Comment by aclements** [comment]
It's not a regression, but it has interfered with debugging runtime issues in 1.8. The fix is trivial and obviously correct (though the test is mighty hairy).

**Comment by aclements** [comment]
Cherry-picked to release.
