### ISSUE TITLE
const type deduction

### ISSUE THREAD

**Issue by zzwind** [golang/go#19630]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?

```
func main() {
	const abc = 8
	fmt.Printf("%t\n", abc)
	fmt.Println(math.Pi * abc)
	fmt.Printf("%t", math.Pi)
}
```
result:
%!t(int=8)
25.132741228718345
%!t(float64=3.141592653589793)

```
func main() {
	const abc int8 = 8
	fmt.Printf("%t\n", abc)
	fmt.Println(math.Pi * abc)
	fmt.Printf("%t", math.Pi)
}
```
result:
constant 3.14159 truncated to integer

Why when i typed abc int8 ,the compiler will error.
But,first example tell me on runtime the **abc** type is **int8**.

**Comment by davecheney** [comment]
The error tells you the type is an `int`, with the value `8`.

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
