### ISSUE TITLE
Modifications to string Compare

### ISSUE THREAD

**Issue by mrajashree** [golang/go#19645]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 darwin/amd64

Is it possible to add functions like CompareN and CompareCase to strings package?
CompareN would compare first N characters, CompareCase would accept a bool and based on that would do case sensitive/insensitive comparison

**Comment by mvdan** [comment]
> CompareN would compare first N characters

`s1[:n] == s2[:n]`

> CompareCase

`s1 == s2` or `strings.EqualFold(s1, s2)`

In the future, for questions please use https://github.com/golang/go/wiki/Questions. If you'd like to propose additions to the standard library, open a proposal issue with more details.

**Comment by bradfitz** [comment]
> s1[:n] == s2[:n]

Well, technically that's `n` bytes, not runes.

There's no func (that I know of) to easily get the first N runes of a string of []byte.

**Comment by mvdan** [comment]
That would probably go in `unicode/utf8`. Trying to think of a way to do it given the existing stuff in there, but can't figure out a simple way.

**Comment by mvdan** [comment]
Perhaps something like `DecodeRunes(p []byte, n int) string`, that would attempt to decode up to n runes.

**Comment by bradfitz** [comment]
@mvdan, there's no reason for the []byte to string conversion (allocation). If anything were added, there should be one variant for []byte and one for string.

**Comment by bradfitz** [comment]
But saying "N runes" is kinda useless without considering unicode normalization and other fun stuff. This is more of a job for the golang.org/x/text repo. It's probably already in there. (/cc @mpvl)

**Comment by mvdan** [comment]
Ah, this is where my unicode-fu ends :)
