### ISSUE TITLE
runtime: panic(x) prints garbage if x is an integer other than 'int'

### ISSUE THREAD

**Issue by alandonovan** [golang/go#19658]
The statement `panic(int(8))` causes a panic whose message starts with `panic: 8`.  However, a panic operand of any other integer type causes output of the form `panic: (uint) (0x999a0,0x1040a040)`, which suppresses the most crucial piece of information, the numeric value `8`.

It would be more helpful it if printed `panic: uint: 8`.

**Comment by ianlancetaylor** [comment]
The code in question is https://golang.org/src/runtime/error.go#L77 .
