### ISSUE TITLE
x/tools/imports: Process does not handle nil src properly

### ISSUE THREAD

**Issue by raphael** [golang/go#19676]
Go 1.8

The [header comment](https://github.com/golang/tools/blob/master/imports/imports.go#L45) of `Process` implies that the use of the `src` parameter is optional. However providing a nil value always results in the error:
```
expected 'package', found 'EOF'
```
This is because the value is a nil `[]byte` but the go `parser` [ParseFile](https://github.com/golang/go/blob/master/src/go/parser/interface.go#L84) function which is called internally expects `src` to be of type `interface{}`. This in turns causes readSource to return nil because the comparison with (`interface{}`) nil [fails](https://github.com/golang/go/blob/master/src/go/parser/interface.go#L26).

Either the header comment of `Process` should be updated or the code modified so that giving a nil `src` actually works (presumably the intended and better behavior). This requires tweaking the [call to ParseFile](https://github.com/golang/tools/blob/master/imports/imports.go#L123) to cast `src` to a `nil` `interface{}` if it's a nil `[]byte`.

**Comment by haya14busa** [comment]
replacing []byte(nil) to nil solves the problem but parse() expects non-nil src and we cannot support option.Fragment by this solution.

I fixed it by reading the data from filename before passing src to parse() function.
it's similar to src/cmd/gofmt.
