### ISSUE TITLE
cmd/compile: internal compiler error: no witness for reachable phi

### ISSUE THREAD

**Issue by ALTree** [golang/go#19678]
`go version devel +e95989c1c1 Thu Mar 23 17:57:25 2017 +0000 linux/amd64`

The following program:

```
package p

var f func(int)

func Crash() {
l1:
	i := 0
	goto l1
l2:
	f(i)
	goto l2
}
```

crashes the compiler on tip, but not in go1.8 and older.

```
./2.go:5:6: internal compiler error: no witness for reachable phi v8

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/alberto/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0xace2fc, 0x1f, 0xc420014d70, 0x1, 0x1)
	/home/alberto/go/src/cmd/compile/internal/gc/subr.go:175 +0x230
cmd/compile/internal/gc.(*ssafn).Fatalf(0xc4202d87e0, 0x50600000001, 0xace2fc, 0x1f, 0xc420014d70, 0x1, 0x1)
	/home/alberto/go/src/cmd/compile/internal/gc/ssa.go:4892 +0x67
cmd/compile/internal/gc.(*state).Fatalf(0xc4200f60e0, 0xace2fc, 0x1f, 0xc420014d70, 0x1, 0x1)
	/home/alberto/go/src/cmd/compile/internal/gc/ssa.go:286 +0x98
cmd/compile/internal/gc.(*simplePhiState).insertPhis(0xc4203097e0)
	/home/alberto/go/src/cmd/compile/internal/gc/phi.go:499 +0x4a9
cmd/compile/internal/gc.(*state).insertPhis(0xc4200f60e0)
	/home/alberto/go/src/cmd/compile/internal/gc/phi.go:34 +0x172
cmd/compile/internal/gc.buildssa(0xc4200b2140, 0x0)
	/home/alberto/go/src/cmd/compile/internal/gc/ssa.go:185 +0x8a3
cmd/compile/internal/gc.compile(0xc4200b2140)
	/home/alberto/go/src/cmd/compile/internal/gc/pgen.go:302 +0x119
cmd/compile/internal/gc.funccompile(0xc4200b2140)
	/home/alberto/go/src/cmd/compile/internal/gc/dcl.go:1172 +0xb7
cmd/compile/internal/gc.Main(0xada2d8)
	/home/alberto/go/src/cmd/compile/internal/gc/main.go:511 +0x230c
main.main()
	/home/alberto/go/src/cmd/compile/main.go:49 +0x95
```

**Comment by josharian** [comment]
These are great. Thanks, @ALTree. Out of curiosity, are these from fuzzing with gofuzz, or...?

**Comment by josharian** [comment]
Anyone want to bisect this?

**Comment by ALTree** [comment]
I'm using Dmitry's gosmith (github.com/dvyukov/gosmith).

I've found a few more, but it takes time to reduce them in minimal form.

**Comment by josharian** [comment]
Cool. It may be easier to reduce them if you bisect first--the commit might help provide clues about which parts are important, and the bisection info is super useful anyway.

Also, cc @mvdan who I believe has been working on an automated reducer. Maybe you could test drive it!

**Comment by ALTree** [comment]
This was introduced in 4e428907c5d34b31e5d21c17917f70b0d1f0e4f6 (cmd/compile: avoid generating some dead blocks).

@josharian

**Comment by mvdan** [comment]
@josharian I did see this issue, but unfortunately the program has already been reduced (afaik fully) by hand :)

**Comment by josharian** [comment]
@mvdan I was think of your reducer more for @ALTree's comments: "I've found a few more, but it takes time to reduce them in minimal form."

**Comment by mvdan** [comment]
Ah, sure; current status is available at https://github.com/mvdan/goreduce. See the open issues though, it's missing some important bits like inlining of vars and funcs.

**Comment by ALTree** [comment]
Nice.

For now we're done: the other 3 I had are actually dups, they just crashed the compiler with different messages. I ran the latest tip on them and they are all fixed.

**Comment by josharian** [comment]
For now. :) I'm glad you're running it, and I hope you continue to do so; bugs spring eternal, and it's nice to know about them quickly.
