### ISSUE TITLE
net: make Buffers methods on value receivers

### ISSUE THREAD

**Issue by zombiezen** [golang/go#19680]
`net.Buffers` methods are on pointer receivers and it seems like the implementation of the methods immediately dereferences it.  This seems odd since a slice is already a reference.  I think this can be done without breaking compatibility.  Concretely, this becomes frustrating if converting from an existing `[][]byte`:

```go
var w io.Writer
var x [][]byte
err := (*net.Buffers)(&x).WriteTo(w)
```

Although I realize it could be written as:

```go
var w io.Writer
var x [][]byte
y := net.Buffers(x)
err := y.WriteTo(w)
```

**Comment by agnivade** [comment]
As I understand, is this a matter of convenience ? Or is there some performance benefit to gain out of this ?

/cc @bradfitz

**Comment by bradfitz** [comment]
The methods mutate the slice. Look at the consume method, for instance.

That wouldn't work with a value receiver.
