### ISSUE TITLE
spec: does not cover the case where a map composite literal contains multiple copies of the same key at runtime

### ISSUE THREAD

**Issue by alercah** [golang/go#19689]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
[November 18, 2016](https://golang.org/ref/spec)

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
The Go spec states "For map literals, all elements must have a key. It is an error to specify multiple elements with the same field name or constant key value.", however, it is silent as to what happens whem multiple elements with the same non-constant key value are present, as in this link: https://play.golang.org/p/53kQ9rF8a2

As you can see, it appears that the later one wins in this example, but I don't know if this always holds.

**Comment by bradfitz** [comment]
https://golang.org/ref/spec#Order_of_evaluation has a bit more and says:

```go
a := 1
m := map[int]int{a: 1, a: 2}  // m may be {2: 1} or {2: 2}: evaluation order between the two map assignments is not specified
```

I think that's the answer to this bug.

**Comment by griesemer** [comment]
The spec does cover this case but the respective section in the spec could be clearer about it. Will add reference. CL forthcoming.
