### ISSUE TITLE
doc: How to get cgo to work on windows 64 bit?

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#19686]
See https://www.reddit.com/r/golang/comments/60xr8t/how_to_get_cgo_to_work_on_windows_64_bit/ for details.

Maybe we can be more helpful here. Maybe better documentation. Maybe we could provide more precise instructions about installing gcc on windows.

Thank you.

Alex

**Comment by brandonryan** [comment]
Took a shot at this as first contribution. Please let me know if it needs anymore changes.  
In the future it might be a good idea to have a "supported cgo compilers" page, because I know that msvc support is being worked on. I've also had success with http://tdm-gcc.tdragon.net/
