### ISSUE TITLE
byte.split works against expectations

### ISSUE THREAD

**Issue by hyj-kim** [golang/go#19693]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.5

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hyejung/go-workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build491697192=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

I splited []byte _strTest_ and assigned one of it to a new []byte _value_.
Then i appended []byte to variable _value_.
Unexpectedly the []byte _strTest_ was changed.
I attached code and its result.

Code:
`
package main

import (
	"bytes"
	"fmt"
)

func main() {

	value := []byte("")
	strTest := []byte("ab:dc.efg.hig")

        idx := len(strTest)
	
	labels := bytes.Split(strTest[0:idx], []byte("."))
	fmt.Printf("%s\n",string(strTest))
	
	for i := range labels {
		label := labels[i]
		fmt.Printf("%d:%s\n",i,string(label))
		if bytes.Contains(label, []byte(":")) {
			pair:= bytes.Split(label, []byte(":"))
			value = pair[1]
		}
		value = append(value,[]byte("|append")...)
		fmt.Printf("value: %s\n",string(value))	
		fmt.Printf("origin sentense: %s\n",string(strTest))	
	}

}
`

Result:

ab:dc.efg.hig
0:ab:dc
value: dc|append
origin sentense: ab:dc|appendg
1:app
value: dc|append|append
origin sentense: ab:dc|appendg
2:ndg
value: dc|append|append|append
origin sentense: ab:dc|appendg

I expected []byte _strTest_ was same as before.
Only "|append" was added to  _value_.
is it bug?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by robpike** [comment]
This is working as intended, if not quite as you intended. Split returns slices into the original array, and append will use existing memory if it can, so the code you have will modify the underlying array. You will need to make explicit copies to avoid this problem.

I suggest reading one of the blog posts about slices and append. This one might be a good place to start: https://blog.golang.org/slices
