### ISSUE TITLE
easy way to upgrade the golang

### ISSUE THREAD

**Issue by RajeshKumar1990** [golang/go#19690]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.4 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

May i know an easy way to upgrade from my current version of golang  to the latest stable version in windows.I have researched online.everyone was saying to uninstall current version  and install the latest stable version.
If this function is not there will it be possible to add this functionality in future versions.
May be can provide the command line tool like go upgrade or go update.
 Thanks.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

But yes, this is something we're thinking about. For the last release we did https://godoc.org/golang.org/x/build/version/go1.8rc3 etc to make go-gettable versions, etc.
