### ISSUE TITLE
syscall: TestUnshareMountNameSpace failed in linux-arm64 builder with permission denied

### ISSUE THREAD

**Issue by cherrymui** [golang/go#19698]
After CL https://go-review.googlesource.com/c/38471/, linux-arm64 builder failed in TestUnshareMountNameSpace with permission denied.
https://build.golang.org/log/a2fd112da23e96e2c5ea00840544a1ddb6f45a2c

Not sure whether it is the builder configuration, or the test should be skipped in certain conditions.

**Comment by ianlancetaylor** [comment]
CC @rminnich

**Comment by vielmetti** [comment]
Any progress on this? I see a steady state of `fail` on arm64-linux on https://build.golang.org

**Comment by vielmetti** [comment]
With this test skipped, we finally get an "ok" build for arm64. Thanks to @bradfitz

**Comment by rminnich** [comment]
I'd like to fix this but I need root access to an arm64 machine, which I'm working to get. Thanks for the workaround.

**Comment by vielmetti** [comment]
@rminnich - did you get root access to the arm64 machine that you were looking for?

**Comment by vielmetti** [comment]
Thanks @bradfitz did this problem get sorted out, was it real or an artifact?

**Comment by bradfitz** [comment]
We made the test skip when it has insufficient permissions. Fixed as far as I'm concerned.

And timeout waiting for @rminnich.
