### ISSUE TITLE
x/crypto/acme: badNonce errors should be retried automatically

### ISSUE THREAD

**Issue by fastest963** [golang/go#19703]
When a call to the Let's Encrypt server returns `urn:acme:error:badNonce`, it should be retried with the nonce returned with that error. Currently it's up to the caller to handle this and automatically retry, which can be tedious since you'd have to wrap or add code around every call to a `acme.Client` method.

The reason why you get this error is explained in https://github.com/certbot/certbot/issues/2244#issuecomment-274625263:

> Many nonces go unused, which means we have to expire them after a while. More importantly, we currently keep track of nonces per-frontend and therefore per-DC. When we switch traffic between DCs, any inflight sessions will get badNonce errors.

I propose that the `postJWS` method in acme handle this and automatically retry once if a `badNonce` error is returned, like what was done for certbot/certbot. It looks like all the calls that utilize nonces use that method. When quickly prototyping a solution, I ran into the issue that `postJWS` just returns the response and relies on the caller to notice an error and call `responseError`. To make things easy, I had 4XX and 5XX errors automatically handled inside `postJWS` and then the `badNonce` error is checked in there.

According to the spec, the error should be `urn:ietf:params:acme:error:badNonce` but the error that Let's Encrypt returns is `urn:acme:error:badNonce`, I wasn't sure which is correct, so in my prototype I just looked for the suffix matching.

Prototype patch: https://github.com/fastest963/crypto/commit/957374cd44bc571ad441a0d05cbf5ac61529e96d

**Comment by marktheunissen** [comment]
@fastest963 we're running this patch in production, it fixed the issues well when we first deployed it on Monday, but ever since April 6th (coinciding with Let's Encrypt maintenance), we are seeing `"400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce xxxxxxx"` again on a regular basis. Are you also encountering the problem again? Any idea if there is a regression on their side?

**Comment by FiloSottile** [comment]
The feature LGTM. I'd submit the patch to Gerrit for core review. A test would be great.

Also, curious about @marktheunissen's issue. Maybe need to retry more times?

**Comment by fastest963** [comment]
@marktheunissen I haven't seen the same problem. What could be happening is that there's still stored invalid nonces. I've updated my patch above in the summary to clear out any stored nonces after we get a `badNonce` error. Can you let me know if that fixes your issue?

@FiloSottile thanks for checking it out! I'll add a test and submit to Gerrit after I hear back from @marktheunissen.

**Comment by marktheunissen** [comment]
Thanks! Will give it a try on Monday.

**Comment by marktheunissen** [comment]
We now think it might be something to do with our usage of the lib, rather than a change in Boulder (Let's Encrypt) ... still looking into it.

**Comment by fastest963** [comment]
I created the following CL https://go-review.googlesource.com/c/40130/
