### ISSUE TITLE
net/http/httputil: NewSingleHostReverseProxy overwrites Director header transformations when hop headers occur

### ISSUE THREAD

**Issue by CSEMike** [golang/go#19706]
### What version of Go are you using (`go version`)?
go version go1.8.typealias linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/piatek/gopath"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329872370=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
Modified http headers in an httputil.ReverseProxy Director.

### What did you expect to see?
The modification applied to the outgoing request.

### What did you see instead?
The modifications are reverted when copying hop headers.

As the docs describe, the Director field of an httputil.ReverseProxy is for modifying the request to be sent by the proxy. Headers are a natural thing to change in a Director. This works fine, unless there are hop by hop headers, in which case the ReverseProxy will undo the edits before sending the request.

The problems are here and here:
https://golang.org/src/net/http/httputil/reverseproxy.go#L173
https://golang.org/src/net/http/httputil/reverseproxy.go#L188

The ReverseProxy makes a shallow copy of the request to be sent to the origin. Then, the Director is called, possibly modifying headers. Then, if the ReverseProxy itself decides to modify headers, it copies them from the original request, req.Header, rather than the request passed to the Director, outreq.

My view is that a fix will require an unconditional deep copy of outreq. The existence of the Director API in ReverseProxy seems in conflict with the http.Handler API and a shallow copy. The http.Handler docs prohibit modification of the *http.Request passed to ServeHTTP. Yet, the Director API offers for modification a shallow copy of the *http.Request given to ReverseProxy via ServeHTTP.

The program below reproduces the failure precisely.

```
package proxy_test

import (
  "net/http"
  "net/http/httptest"
  "net/http/httputil"
  "net/url"
  "testing"
)

func copyHeader(dst, src http.Header) {
  for k, vv := range src {
    for _, v := range vv {
      dst.Add(k, v)
    }
  }
}

func TestHeaders(t *testing.T) {
  // An origin, which should receive a request modified by our reverse proxy director.
  srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    if got, want := r.Header.Get("X-Want-Dropped"), ""; got != want {
      t.Errorf("%s: origin request header: X-Want-Dropped: got: %q want: %q", r.URL.Path, got, want)
    }
  }))
  defer srv.Close()
  parsed, err := url.Parse(srv.URL)
  if err != nil {
    t.Fatalf("url.Parse(%q): %v", srv.URL, err)
  }
  // The reverse proxy.
  rp := httputil.NewSingleHostReverseProxy(parsed)
  origDirector := rp.Director
  rp.Director = func(r *http.Request) {
    origDirector(r)
    // Copy header, since r.Header is a shallow copy of the original request
    // headers, and  calls rp.Director for an http.Handler, and http.Handlers
    // aren't permitted to modify the original request.
    h := make(http.Header)
    copyHeader(h, r.Header)
    r.Header = h
    r.Header.Del("X-Want-Dropped")
  }
  rpSrv := httptest.NewServer(rp)
  defer rpSrv.Close()

  tests := []struct {
    label, path      string
    connectionHeader string
  }{
    {"header is dropped with empty connection header", "/without_connection_header", ""},
    {"header is dropped with Connection: close", "/with_connection_header", "close"}, // bug repro.
  }
  for _, test := range tests {
    func() {
      req, err := http.NewRequest(http.MethodGet, rpSrv.URL+test.path, nil)
      if err != nil {
        t.Errorf("%s: http.NewRequest: %v", test.label, err)
        return
      }
      req.Header.Set("X-Want-Dropped", "1")
      if test.connectionHeader != "" {
        req.Header.Set("Connection", test.connectionHeader)
      }
      resp, err := http.DefaultTransport.RoundTrip(req)
      if err != nil {
        t.Errorf("%s: RoundTrip: %v", test.label, err)
        return
      }
      resp.Body.Close()
    }()
  }
}
```

**Comment by bradfitz** [comment]
> My view is that a fix will require an unconditional deep copy of outreq. 

That happened in 3c0f69a52101c69b5a8288195fa74c7ecfa2fa43

And confirmed that your test passes now:

```
bradfitz@gdev:~/src/issue_19706$ go test -v
=== RUN   TestHeaders
--- PASS: TestHeaders (0.00s)
PASS
ok      issue_19706     0.005s
```
