### ISSUE TITLE
cmd/vet: remove Peek from methods check

### ISSUE THREAD

**Issue by josharian** [golang/go#19719]
vet's methods check ensures that methods with a canonical name have the right signature. This includes:

```go
	"Peek":          {[]string{"=int"}, []string{"[]byte", "error"}},                   // image.reader (matching bufio.Reader)
```

But it's not clear to me why the unexported `image.reader` interface is important enough to set the canonical interpretation of Peek.

I see three Peeks in the standard library:

```go
// bufio
func (b *Reader) Peek(n int) ([]byte, error)

// cmd/internal/obj
func (a *AsmBuf) Peek(i int) byte

// text/scanner
func (s *Scanner) Peek() rune
```

Of these, only `bufio.Reader` matches. Another `Peek` that comes to mind is from Russ's article [Off to the Races](https://research.swtch.com/gorace):

```go
// Peek reads and returns the word at address addr.
func (m *Mem) Peek(addr uintptr) uintptr
```

I think we should remove `Peek` from the list of canonical method names.

The CL is trivial; this issue is to ask for approval.

@robpike

**Comment by robpike** [comment]
Fine with me.
