### ISSUE TITLE
spec: why not allow arrays for copy func?

### ISSUE THREAD

**Issue by willfaught** [golang/go#19731]
For example:

```go
copy([2]int{}, [2]int{})
```

causes:

```arguments to copy must be slices; have [2]int, [2]int```

Same code: https://play.golang.org/p/ptNtSKB2WQ

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions

To submit a formal proposal, see https://github.com/golang/proposal but be aware that changes to the language are no longer being considered for Go 1.x.

**Comment by willfaught** [comment]
This wasn't a question, although I admit it looks like one.

We should do this. I see no reason why not.

>changes to the language are no longer being considered for Go 1.x.

Is this a new policy? Wasn't struct equality just changed in the latest
release?

**Comment by bradfitz** [comment]
> Is this a new policy?

Yes. We just closed a bunch of language change proposals in the past month.

You're more than welcome to write up a proposal using the formal process, but I'm just saying your chances are close to zero for Go 1.x. It could be considered for Go 2.x, but in that case, closed bugs tagged "LanguageChange" will do just as well to jog people's memories of things to consider. I'll tag this LanguageChange.

**Comment by willfaught** [comment]
OK, thanks.

**Comment by griesemer** [comment]
@willfaught As an aside, arrays can be copied directly (e.g., https://play.golang.org/p/g8rqqq4T1b). No need for calling copy.

**Comment by willfaught** [comment]
Very good point! No need then. :)
