### ISSUE TITLE
deadlock in websocket server (gorilla) on linux/arm (raspberry pi) with crosscompile

### ISSUE THREAD

**Issue by eidmanna** [golang/go#19730]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8 windows/amd64 
with crosscompile GOOS: "linux", GOARCH: "arm"

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

with crosscompile for
GOOS: "linux", 
GOARCH: "arm"

### What did you do?

I did a cross compile of this websocket code (with gorilla lib) for arm/linux:
https://gist.github.com/tmichel/7390690 --> ws.go

copy server part (ws) to raspberry pi (arm/linux)
start websocket server and call of ws client (index.html) from remote

### What did you expect to see?
Call of this line without lock:
conn, err := websocket.Upgrade(w, r, w.Header(), 1024, 1024)

### What did you see instead?
A deadlock in this line:
example code:
-->
conn, err := websocket.Upgrade(w, r, w.Header(), 1024, 1024)

golang lib:
-->
goroutine 4 [semacquire]:
sync.runtime_notifyListWait(0x10810508, 0x0)
C:/Go/src/runtime/sema.go:297 +0x138

see heap dump

Hints:
With golang version 1.7.5 everything works fine.

For details and heapdump see:

https://github.com/gorilla/websocket/issues/232

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

Notably, we don't maintain the Gorilla Websocket code.

As @garyburd said in the linked bug:

> You should fix the defect in your application and test before reporting an issue on net/http.

Do that first.
