### ISSUE TITLE
regexp: needless allocations when compiling onepass regex

### ISSUE THREAD

**Issue by haya14busa** [golang/go#19735]
#### What did you do?
I ran benchmark of my program which contains compiling onepass regex and noticed that we  can specify onePassProg.Inst capacity.

https://github.com/golang/go/blob/73912a1b914251d29eb60c8e85262d931f895b90/src/regexp/onepass.go#L222-L228

#### What did you expect to see?
Allocation by append() will be reduced by specifying cap.

#### What did you see instead?
cap is not specified and it leads needless allocation.

#### System details

```
go version go1.8 linux/amd64
GOARCH="amd64"
GOBIN="/home/haya14busa/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/haya14busa"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567867684=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.8 X:framepointer
uname -sr: Linux 4.4.48-1-MANJARO
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	16.10
Codename:	Fringilla
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.24, by Roland McGrath et al.
gdb --version: GNU gdb (GDB) 7.12.1
```
Also, go version devel +73912a1 Mon Mar 27 23:36:36 2017 +0000 linux/amd64

I'll send a CL soon.

**Comment by dongweigogo** [comment]
Good, the Go regex engine does need improvements. Its current performance is too weak.
