### ISSUE TITLE
Apple LLVM 8.1 breaks CGO?

### ISSUE THREAD

**Issue by RXminuS** [golang/go#19742]
Still investigating but seems to be the following issue:

Today's apple update for LLVM 8.1 seems to break CGO. We were importing a C library and after the update it started to give a `signal: killed` error when importing the module and running the program. We've tried building for mac using xgo and that works fine. We're trying to roll-back the LLVM compiler and retry running but it's going to take some time.

Wanted to give an early heads-up and possibly get some help making this issue reproducible / validated.

(Note, system details below are from a machine before it breaks. Break seems to happen if you update from here to Apple LLVM 8.1)

#### System details

```
go version go1.8 darwin/amd64
GOARCH="amd64"
GOBIN="/Users/rik/go/bin/"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rik/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qg/jljvch4s63jf6m0wgtgtm7j40000gn/T/go-build945685700=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.8 X:framepointer
uname -v: Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
lldb --version: lldb-360.1.70
```

**Comment by RXminuS** [comment]
Possible duplicate of #19734

**Comment by ALTree** [comment]
Likely a dup of #19741 and #19734, let's track this there.
