### ISSUE TITLE
x/sys/unix: copy ParseDirent fixes from CL 23780

### ISSUE THREAD

**Issue by cespare** [golang/go#19754]
[CL 23780](https://go-review.googlesource.com/c/23780/) fixed unsafe use of unsafe in syscall.ParseDirent (see #15653). This patch never made it to x/sys/unix.

---

Side note: is there any automated process to ensure patches migrate from syscall to x/sys/unix? I had been moving all my code away from syscall, but this sort of thing makes me wonder if that's a bad idea because syscall might get more scrutiny than x/sys/unix.

**Comment by bradfitz** [comment]
> Side note: is there any automated process to ensure patches migrate from syscall to x/sys/unix?

No, but with the latest progress in x/build/maintner it seems pretty easy to write a tool to find candidates that didn't get moved over. I'll write more about that tool ~next week. But on the other hand, there aren't too many such changes.

**Comment by niconegoto** [comment]
@cespare  @bradfitz I can work on it.Should I wait for the automation process to be completed?

**Comment by bradfitz** [comment]
@niconegoto, no, don't wait. Any automation would only find missing work, but not do the work.
