### ISSUE TITLE
x/build/owners: convert owners doc into a package

### ISSUE THREAD

**Issue by rakyll** [golang/go#19757]
We are planning to build a Gerrit assigner bot based on the package owners document  at [golang.org/s/owners](https://golang.org/s/owners). Convert this document into a package and enable bots and other programs can consume the data.

We should also make the owners package the source of truth, and generate a /s/owners page by using `x/build/owners` if a web listing is required.

/cc @jessfraz @spf13 @bradfitz

**Comment by bradfitz** [comment]
That's one option. The other option is making the spreadsheet the source of truth and reading from it where needed.

Working with Go (and using Go code review tools and versioned history) is probably more consistent, though.

The dev.golang.org app could have an /owners page.

/cc @kevinburke @quentinmit

**Comment by rakyll** [comment]
Rendering a page from this package will be quite trivial, and it will be possible to use Gerrit to open CLs to modify the owners data.

dev.golang.org/owners sounds great.

**Comment by kevinburke** [comment]
(For what it's worth, as of today or thereabouts Github has begun adding "suggested reviewers" to pull requests in the sidebar, which suggests they also have thoughts about this problem and maybe some good ideas or data about how to solve it)

**Comment by rakyll** [comment]
@kevinburke, there is already another issue for auto-assigning reviewers based on activity at https://github.com/golang/go/issues/17555. Let's keep the conversation there. Our first step can be assigning based on the owners, we can always add more magic if a concrete proposal.

**Comment by jessfraz** [comment]
sweet, I added myself to be cc-ed on that CL so once it is in I can work on #17555

**Comment by ALTree** [comment]
This is done (https://golang.org/x/build/devapp/owners) and reviewers are now automatically added, so I'm closing this issue.
