### ISSUE TITLE
website: tip.golang.org presents content over HTTP

### ISSUE THREAD

**Issue by kevinburke** [golang/go#19759]
If I request http://golang.org, http://dev.golang.org or http://build.golang.org, I get redirected to the HTTPS versions of those pages. However, tip.golang.org is available over HTTP.

We should redirect those pages to HTTPS. Even though the pages in question don't contain very sensitive data, a list of reasons to upgrade to HTTPS can be found here: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

https://tip.golang.org has a valid HTTPS certificate so we just need to detect HTTP and redirect those connections to HTTPS.

See also #16442.

**Comment by bradfitz** [comment]
Actually, I'll let somebody else do this.

@kevinburke, you want it?

One place to fix it is in x/tools/cmd/godoc itself, even if that's a bit lazy and awkward. Just check whether the Request.Host == "tip.golang.org" and Request.TLS == nil, and then do the redirect. Then we don't need to redeploy tip.golang.org since it'll do so itself. 

But if people are grossed out by that, we can redeploy tip.golang.org itself.

**Comment by kevinburke** [comment]
Sure I'll take it. So golang.org/x/tools/cmd/tip has this code:

```go
// httpsOnlyHandler redirects requests to "http://example.com/foo?bar"
// to "https://example.com/foo?bar"
type httpsOnlyHandler struct {
	h http.Handler
}

func (h httpsOnlyHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Header.Get("X-Appengine-Https") == "off" {
		r.URL.Scheme = "https"
		r.URL.Host = r.Host
		http.Redirect(w, r, r.URL.String(), http.StatusFound)
		return
	}
	if r.Header.Get("X-Appengine-Https") == "on" {
		// Only set this header when we're actually in production.
		w.Header().Set("Strict-Transport-Security", "max-age=31536000; preload")
	}
	h.h.ServeHTTP(w, r)
}
```

Which I am guessing is broken now since tip.golang.org runs in the flexible environment.

According to this page: https://cloud.google.com/appengine/docs/flexible/go/how-requests-are-handled we should now be using `X-Forwarded-Proto: http` to detect http or HTTPS.
