### ISSUE TITLE
x/net/http2/hpack: lookup maps for the dynamic table leak despite evictions

### ISSUE THREAD

**Issue by rodaine** [golang/go#19756]
### What version of Go are you using (`go version`)?

```
go version go1.8 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```sh
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chrisroche/go"
GORACE=""
GOROOT="/Users/chrisroche/.gimme/versions/go1.8.darwin.amd64"
GOTOOLDIR="/Users/chrisroche/.gimme/versions/go1.8.darwin.amd64/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7s/kv_f_g112gq5gl7zt_lyt2zr0000gp/T/go-build079652742=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

Adding the following test to the current master of [x/net/http2/hpack/tables_test.go](https://github.com/golang/net/blob/bce15e71618b27abb281288615ab0881d8a04433/http2/hpack/tables_test.go):

```go
func TestHeaderFieldTable_LookupMapEviction(t *testing.T) {
	table := &headerFieldTable{}
	table.init()
	table.addEntry(pair("key1", "value1-1"))
	table.addEntry(pair("key2", "value2-1"))
	table.addEntry(pair("key1", "value1-2"))
	table.addEntry(pair("key3", "value3-1"))
	table.addEntry(pair("key4", "value4-1"))
	table.addEntry(pair("key2", "value2-2"))

	// evict all pairs
	table.evictOldest(table.len())

	if l := table.len(); l > 0 {
		t.Errorf("table.len() = %d, want 0", l)
	}

	if l := len(table.byName); l > 0 {
		t.Errorf("len(table.byName) = %d, want 0", l)
	}

	if l := len(table.byNameValue); l > 0 {
		t.Errorf("len(table.byNameValue) = %d, want 0", l)
	}
}
```

And running `go test -v -run TestHeaderFieldTable_LookupMapEviction` from that directory

### What did you expect to see?

```
PASS
```

### What did you see instead?

```
=== RUN   TestHeaderFieldTable_LookupMapEviction
--- FAIL: TestHeaderFieldTable_LookupMapEviction (0.00s)
	tables_test.go:110: len(table.byName) = 4, want 0
	tables_test.go:114: len(table.byNameValue) = 6, want 0
FAIL
exit status 1
FAIL	golang.org/x/net/http2/hpack	0.006s
```

### More context

When the load to a gRPC service was recently ramped up, we were alerted to a memory leak which took approximately 24hrs to consume all the RAM and die. Getting the heap profile off the running service, the vast majority of the objects were originating from [`hpack.(*dynamicTable).add`](https://github.com/golang/net/blob/bce15e71618b27abb281288615ab0881d8a04433/http2/hpack/hpack.go#L170-L174) and [`hpack.(*Decoder).readString`](https://github.com/golang/net/blob/bce15e71618b27abb281288615ab0881d8a04433/http2/hpack/hpack.go#L456-L490):

```
(pprof) top100 -cum
718.97MB of 721.98MB total (99.58%)
Dropped 442 nodes (cum <= 3.61MB)
      flat  flat%   sum%        cum   cum%
         0     0%     0%   721.98MB   100%  runtime.goexit
         0     0%     0%   720.97MB 99.86%  github.com/example/pkg/vendor/golang.org/x/net/http2.(*Framer).ReadFrame
         0     0%     0%   720.97MB 99.86%  github.com/example/pkg/vendor/google.golang.org/grpc/transport.(*framer).readFrame
         0     0%     0%   720.47MB 99.79%  github.com/example/pkg/vendor/golang.org/x/net/http2.(*Framer).readMetaFrame
         0     0%     0%   720.47MB 99.79%  github.com/example/pkg/vendor/golang.org/x/net/http2/hpack.(*Decoder).Write
         0     0%     0%   720.47MB 99.79%  github.com/example/pkg/vendor/golang.org/x/net/http2/hpack.(*Decoder).parseHeaderFieldRepr
         0     0%     0%   719.97MB 99.72%  github.com/example/pkg/vendor/golang.org/x/net/http2/hpack.(*Decoder).parseFieldLiteral
         0     0%     0%   719.09MB 99.60%  github.com/example/pkg/vendor/google.golang.org/grpc.(*Server).handleRawConn
         0     0%     0%   719.09MB 99.60%  github.com/example/pkg/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport
         0     0%     0%   718.57MB 99.53%  github.com/example/pkg/vendor/google.golang.org/grpc.(*Server).serveStreams
         0     0%     0%   718.57MB 99.53%  github.com/example/pkg/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams
  448.06MB 62.06% 62.06%   448.06MB 62.06%  github.com/example/pkg/vendor/golang.org/x/net/http2/hpack.(*Decoder).readString
  270.90MB 37.52% 99.58%   271.90MB 37.66%  github.com/example/pkg/vendor/golang.org/x/net/http2/hpack.(*dynamicTable).add
```

Digging into that code, there was [a performance change](https://github.com/golang/net/commit/bce15e71618b27abb281288615ab0881d8a04433) made last month that improved lookup times considerably by caching the header IDs in [`byName` and `byNameValue` maps](https://github.com/golang/net/blob/bce15e71618b27abb281288615ab0881d8a04433/http2/hpack/tables.go#L32-L38). Unfortunately, it doesn't appear that the map entries are evicted, but instead [set to zero](https://github.com/golang/net/blob/bce15e71618b27abb281288615ab0881d8a04433/http2/hpack/tables.go#L71-L76):

```go
if t.byName[f.Name] == id {
	t.byName[f.Name] = 0
}
if p := (pairNameValue{f.Name, f.Value}); t.byNameValue[p] == id {
	t.byNameValue[p] = 0
}
``` 

This eventually (but somewhat slowly) grows huge for variable headers like request IDs, timings, etc. Rolling back the package to the [prior SHA](https://github.com/golang/net/commit/bb807669a61aca6092d8137da1fab2150bb96ad7) immediately rectified the problem. I'm working on a patch to replace the above to use `delete()` instead. Curious if there is a reason to not?

**Comment by bradfitz** [comment]
@rodaine, thanks for the debugging!

If you want to send a fix, please do. Otherwise @tombergan or I can handle it too. Let us know.

**Comment by rodaine** [comment]
No sweat! Pushing the patch momentarily :)

**Comment by bradfitz** [comment]
I trust you've discovered https://golang.org/doc/contribute.html ?

(Sorry in advance for the wall of words. It tries to be comprehensive but it might be intimidating. There aren't many steps in the end.)

**Comment by rodaine** [comment]
Yessir!

**Comment by rodaine** [comment]
https://go-review.googlesource.com/38781
