### ISSUE TITLE
time.Sleep ( 5ms) in goroutine will cause not running after a short time

### ISSUE THREAD

**Issue by indescribable** [golang/go#19758]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8
gogland /liteIDE

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\04 infodatas\GoSource
set GORACE=
set GOROOT=D:\03 Mytools\go
set GOTOOLDIR=D:\03 Mytools\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

func sendd(port serial.Port) {
	var cnt ,n int
	//var err error
	for true {
		//n, err = port.Write(send[:9])
		//
		//		if err != nil {
		//			log.Fatal(err)
		//		}
		cnt++
		if cnt % 1000 == 0 {fmt.Printf("\r\nSent %v bytes, ser:%d\n", n, cnt) }
		time.Sleep(time.Millisecond * 5)
	}

}

func main(){
...
go sendd()
...
for true{}
}

### The Problem is:
after a not very long time running.
the sendd goroutine will stuck there.

the printf is used as a checker to see if it is stopped.

when i test it stop .after i see cnt is 10000+  the most cnt i see is 59000
mostly wil  happen  between 1minute to 4minutes

and 
import (
	"fmt"

	"log"

	"time"

	"go.bug.st/serial.v1"
)

that's all includes, i donno if it matter with this problem.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
