### ISSUE TITLE
why dosen't logger's Println function return error when l.output() goes wrong

### ISSUE THREAD

**Issue by elaron** [golang/go#19782]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.6.3

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="linux"

### What did you do?
I use logger to log some information in xxx.log file.
Then I keep the go process running, and remove the xxx.log file.
After that, xxx.log file cannot be create automatically, and nothing error was report!

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I expect that, if a logger is writing fail, some error should be return. Like:
func (l *Logger) Println(v ...interface{}) **error** {
         **return** l.Output(2, fmt.Sprintln(v...)) 
}

### What did you see instead?
I do nothing yet.

**Comment by mattn** [comment]
I suggest you to read `man 2 unlink` if you don't know this behavior.

> unlink()  deletes  a  name  from the file system.  If that name was the
> last link to a file and no processes have the file  open  the  file  is
> deleted and the space it was using is made available for reuse.
> 
> If  the  name  was the last link to a file but any processes still have
> the file open the file will remain in existence  until  the  last  file
> descriptor referring to it is closed.
> 
> If the name referred to a symbolic link the link is removed.
> > 
> If  the  name  referred  to a socket, fifo or device the name for it is
> removed but processes which have the object open may  continue  to  use
> it.

So you need to reopen the file (if you want to create new log file). One of the way to do, implement logger which open/close the file every logger.Println (etc).

In generally, utilities for rotating log files (ex: logrotate) send SIGHUP to the processes which open the file. If you want to handle the rotate of the file by them, you can catch the SIGHUP to re-open log files.

**Comment by bradfitz** [comment]
Checking errors for all log prints would be too tedious. The log system should be reliable. (What would you do if log returned an error? Log about it? Kill the program? Then just make the log sink kill the program on error.)

In any case, we can't change the API now, even if we wanted to.

Let's move discussion of log rotation & log implementations to golang-nuts or other forums. (https://golang.org/wiki/Questions)

**Comment by elaron** [comment]
thanks @mattn , I will try your suggestion.

thanks @bradfitz .
