### ISSUE TITLE
wiki: broken link on Mobile wiki page

### ISSUE THREAD

**Issue by WillyWinkel** [golang/go#19795]
in [here](https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios) this link: [signing identity and download provisioning profiles](https://developer.apple.com/library/ios/recipes/xcode_help-accounts_preferences/articles/obtain_certificates_and_provisioning_profiles.html) seems broken.
I think you wanted to redirekt to information like [these here](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html).

**Comment by nathanmp** [comment]
This should be fixed now, just edited the wiki.

**Comment by ALTree** [comment]
Yep, it's fixed. Closing.
