### ISSUE TITLE
cmd/link: TestDWARF failing on non-cgo platforms

### ISSUE THREAD

**Issue by 0intro** [golang/go#19793]
TestDWARF has been added in CL [38855](https://golang.org/cl/38855) and is failing on Plan 9. This is happening because Plan 9 executable don't have a DWARF symbol table.

```
--- FAIL: TestDWARF (3.40s)
    --- FAIL: TestDWARF/testprog (1.40s)
    	dwarf_test.go:71: no DWARF data in Plan 9 file
    --- FAIL: TestDWARF/testprogcgo (0.79s)
    	dwarf_test.go:44: go build -o /tmp/go-link-TestDWARF336257136/testprogcgo.exe ../../runtime/testdata/testprogcgo: exit status: 'go 5236: 2'
    		# _/tmp/workdir/go/src/runtime/testdata/testprogcgo
    		../../runtime/testdata/testprogcgo/dropm_stub.go:11:6: missing function body for "runtime_getm_for_test"
FAIL
FAIL	cmd/link	3.436s
```
See https://build.golang.org/log/f37d663d3b605d05dfbd599a3ceedc1fd8f135a6

**Comment by cherrymui** [comment]
The test also fails on other no-cgo platforms:
linux-amd64-nocgo builder: https://build.golang.org/log/8380330b9d0d32bc1493a677f7fc6126c0398507
big-endian PPC64 builder: https://build.golang.org/log/e1c9310c4f3712b78e63d60e5510ea1ac4658672

**Comment by bradfitz** [comment]
Non-cgo tracked in #19796
