### ISSUE TITLE
os: Process.Exited returns false after exiting on signal

### ISSUE THREAD

**Issue by bombela** [golang/go#19798]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bombela/u/go"
GORACE=""
GOROOT="/home/bombela/u/go/go1.7.5"
GOTOOLDIR="/home/bombela/u/go/go1.7.5/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build016673509=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

```go
package main

import (
	"fmt"
	"os"
	"os/exec"
	"syscall"
	"time"
)

func main() {
	cmd := exec.Command("sleep", "10")
	if err := cmd.Start(); err != nil {
		panic(err)
	}
	time.Sleep(time.Second * 2)
	cmd.Process.Signal(os.Interrupt)
	err := cmd.Wait()
	fmt.Println(err) // prints signal interrupt error
	fmt.Printf("ProcessState: Exited=%v, Success=%v\n", cmd.ProcessState.Exited(),
		cmd.ProcessState.Success()) // Exited should be true.
	waitstatus := cmd.ProcessState.Sys().(syscall.WaitStatus)
	fmt.Printf("WaitStatus:   Exited=%v, Signaled=%v\n",
		waitstatus.Exited(), waitstatus.Signaled())
}
```

### What did you expect to see?

```sh
$ go run main.go 
signal: interrupt
ProcessState: Exited=true, Success=false
WaitStatus:   Exited=false, Signaled=true
```

### What did you see instead?

```sh
$ go run main.go 
signal: interrupt
ProcessState: Exited=false, Success=false # I expect exited == true here,
WaitStatus:   Exited=false, Signaled=true    # and here
```

It looks like `Exited()` returns true only if the process exited via `exit()`, not when it exited via `signal`. It could be that `Exited()` should return `true` on signal.

Casting to `syscall.WaitStatus` allows to check for both `Exited()` and `Signaled()`, making it possible to know if the process is running or not. It seems to be impossible to know if the process is still running via the `Command` abstraction.

Naive suggestion: maybe a `IsRunning()` should be provided on `Command`.

**Comment by ianlancetaylor** [comment]
I'm not sure we can change `Exited` now.

Perhaps we should simply add `Signaled`.

**Comment by andybons** [comment]
This needs to be a formal proposal (https://golang.org/s/proposal) before we can move forward.
