### ISSUE TITLE
not `nil` `error` value, when return `nil` value of type, which implements `error`

### ISSUE THREAD

**Issue by weirdgiraffe** [golang/go#19802]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

While working on json-rpc communication, I've stumbled upon interesting situation. Lets assume following types

```go
type Err struct {
        Code int
        Message string
}

func (e *Err) Error() string {
        return fmt.Sprintf("code=%d desc=%s", e.Code, e.Message)
}

type Response struct {
        Result int
        Error  *Err `json:"omitempty"`
}
```

Now, if I want to deserialize json `{"Result":101}` into `Response` and return `Error` field as `error` (because `Error` implements `error`), I got `error` which is not `nil` but is `<nil>` when printed.

Full code on Go Playground: https://play.golang.org/p/f9afzE69t7

#### What did you expect to see?

- `Error` field to be `nil` 
- When return `Error` field as `error` I expect `error` to be `nil` also

#### What did you see instead?

- `Error` field is `nil` 
- When return `Error` field as `error`, `error` is not `nil` but is `<nil>` when printed

#### System details

```
go version go1.8 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build491112895=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.8 X:framepointer
uname -sr: Linux 4.4.0-31-generic
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.9) stable release version 2.19, by Roland McGrath et al.
gdb --version: GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
```

**Comment by myitcv** [comment]
For questions about Go, see https://golang.org/wiki/Questions

In this case you should look at: https://golang.org/doc/faq#nil_error
