### ISSUE TITLE
runtime/pprof: blocking profile time totals are off by several orders of magnitude

### ISSUE THREAD

**Issue by josharian** [golang/go#19822]
I ran cmd/compile with the block profiler enabled (see CL 39208), and examined the results with pprof. The header in the pdf says: "Showing nodes accounting for 28.16mins, 99.72% of 28.24mins total". And the biggest node in the pdf showed: "28.16mins (99.72%)". But the total compilation tool less than 5 seconds of real time. Unless I'm holding it wrong, it appears that there's a unit error somewhere in block profiling / pprof.

cc @matloob @rsc

**Comment by josharian** [comment]
Hmmm. Actually, I suppose with enough goroutines all blocked at the same point, the cumulative execution could add up that high.

**Comment by rsc** [comment]
At a fundamental conceptual level, it's hard to extract signal from noise in the blocking profile model.

If your blocking is coming from mutexes, try the mutex profile instead. It does a better job because it knows more about the structure of the blocking.
