### ISSUE TITLE
go/parser: example for ParseFile fails on golang.org (playground)

### ISSUE THREAD

**Issue by aaash99999** [golang/go#19823]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
n/a (error is on golang.org)

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
Visit https://golang.org/pkg/go/parser/#example_ParseFile (specifically, the example for ParseFile).
Click Run to run the example.

### What did you expect to see?
Output of the program.

### What did you see instead?
open example_test.go: No such file or directory

Program exited.

**Comment by sgen** [comment]
The example is being run in the (Go Playground)[https://play.golang.org/]
 which is run with various restrictions, including (filesystem restrictions)[https://blog.golang.org/playground#TOC_3.2.]. I dont think this example is supposed to run in the playground.

Does the example work when you copy it to a new package and include a valid 'example_test.go' file?

**Comment by mvdan** [comment]
The example depends on its own file in the `go/parser` package: https://golang.org/src/go/parser/

I guess a way to make it work in the playground would be for the example to first write a file to disk, or to use a buffer/string as the source.

**Comment by mvdan** [comment]
I'll write up a quick CL doing that.

**Comment by sgen** [comment]
In (Inside the Go Playground)[https://blog.golang.org/playground] its mentioned that zip files may be uploaded for the purpose of examples. Perhaps uploading `example_test.go` is a better solution?

**Comment by mvdan** [comment]
I think that's a bit overkill. If the purpose of the example was precisely to use a file via `filename` and not a string/bytes/reader via `src`, then we can just make the example write the sample source to disk first.
