### ISSUE TITLE
How to restart self?

### ISSUE THREAD

**Issue by Baozisoftware** [golang/go#19833]
### What version of Go are you using (`go version`)?
go1.8.linux-amd64

### What operating system and processor architecture are you using (`go env`)?
All use default.

### What did you do?
I have code:
```go
package main

import (
	"os"
	"fmt"
)

func main() {
	if len(os.Args) == 2 {
		fmt.Print("input:")
		var s string
		for {
			fmt.Scanln(&s)
			if s != "" {
				break
			}
		}
		fmt.Printf("output:%s", s)
	} else {
		restart()
	}
}

func restart() {
	procAttr := new(os.ProcAttr)
	procAttr.Files = []*os.File{os.Stdin, os.Stdout, os.Stderr}
	os.StartProcess(os.Args[0], []string{"", "test"}, procAttr)
}
```

### What did you expect to see?
restart after input "test",output "output:test"

### What did you see instead?
input "test" after,app exit.
but,use "./xxxx test" to start this app,everything is normal.

**Comment by sgen** [comment]
It looks as though you are not calling (Process.Release)[https://golang.org/pkg/os/#Process.Release]. Normally unreleased child processes are killed when their parent process is killed, this is probably occurring at the end of main(). Does calling (Process.Release)[https://golang.org/pkg/os/#Process.Release] or (Process.Wait)[https://golang.org/pkg/os/#Process.Wait] fix your problem?

**Comment by Baozisoftware** [comment]
No,call StartProcess, there will be a new process to create, or even output is normal, but can not get input, that is, in addition to the new process can not live outside the input, the other functions are normal operation, and call the wait method , There will be two processes at the same time, do not meet my needs.

**Comment by mvdan** [comment]
If this is a question and not a bug report, please use https://github.com/golang/go/wiki/Questions instead.

**Comment by Baozisoftware** [comment]
I can use this method in the Windows GUI program to achieve an automatic restart after the update, but in the Linux-like restart after the terminal output and similar HTTP Server services can work properly, but can not get input from the terminal.

**Comment by Baozisoftware** [comment]
Indeed, for the procedures do not need to receive the terminal input, this method is no problem, but need to restart can still receive input from the terminal information, this method is not applicable, I would like to know whether this is a system or other reasons? After all, after the restart the program output information and port monitoring and so can work properly.

**Comment by bradfitz** [comment]
For questions about using Go, see https://golang.org/wiki/Questions.

We don't use our bug tracker for general questions.

**Comment by Baozisoftware** [comment]
Thanks, I will go to the forum to ask questions.
