### ISSUE TITLE
gddo: consider adding support for 'IMAGE:'

### ISSUE THREAD

**Issue by sbinet** [golang/go#19847]
like for the `tour` and the `playground` which have support for displaying images, it would be great if `gddo` and `godoc -http` had support for displaying images (PNG,JPEG and, possibly, SVG).

this would be extremely useful for examples.

see:
 https://play.golang.org/p/cDHAf2FuFa

**Comment by sbinet** [comment]
@eaburns @kortschak @btracey

**Comment by adams-sarah** [comment]
Hey @sbinet, the gddo project has its own issue tracker at https://github.com/golang/gddo/issues, mind moving this proposal there?

**Comment by sbinet** [comment]
sure. this is now golang/gddo#517
