### ISSUE TITLE
cmd/compile: do more optimizations for ARMv6/V7

### ISSUE THREAD

**Issue by benshi001** [golang/go#19843]
More ARMv6 & ARMv7 instructions are already merged into branch master. The compiler can use them to do further optimization.

Such as
(Mul16 x y) -> (MULBB x y)
(ADD z (MULBB x y) -> MULABB(x y z)
(SUB x (MUL y z) -> MULS(x y z) and so on.

I have prepared a optimization CL for all these MULA like instructions. But the final form depends on 
 how issue #19141 is fixed.

**Comment by benshi001** [comment]
Unfortunately the go1 benchmark shows no improvement with such optimization.

(Mul16 x y) -> (MULBB x y)
(ADD z (MULBB x y) -> MULABB(x y z)
(SUB z (MUL x y) -> MULS(x y z)

**Comment by randall77** [comment]
go1 benchmarks (or any benchmark, really) aren't always useful.  Their performance is a useful signal when:

1. You think your change should make them faster, and it doesn't.
2. You think your change should not make them slower, and it does.

For instance, I suspect the go1 benchmarks never do a 16-bit multiply.  So only #2 is in play.

If you have an optimization you think is useful but doesn't affect the go1 benchmarks, write your own benchmark which is helped by your change.

**Comment by benshi001** [comment]
1. MULBB, MULABB
2. MULS
3. MMUL, MMULA, MMULS

Try them again in Go1.10.

**Comment by benshi001** [comment]
Please also change milestone to go1.10

**Comment by benshi001** [comment]
MULBB/MULABB have no improvement compared to MUL/MULA.

**Comment by benshi001** [comment]
MULAF, MULSF, MULAD, MULSD did not always improve code quality, since
they required resultInArg0 set to true. So they benefited
a = a + b*c
but not
a = b + c*d especially b is still in use.
