### ISSUE TITLE
cmd/compile: building mips* hangs

### ISSUE THREAD

**Issue by josharian** [golang/go#19842]
Reproduce:

```bash
$ GOOS=linux GOARCH=mipsle go build runtime
```

Introduced by https://go-review.googlesource.com/38801 (cmd/compile: automatically handle commuting ops in rewrite rules). Also shows up on build.golang.org as a blank mipsle column. I presume there's an infinite loop somewhere in one of the mips build rules.

This is currently blocking me, so I'll take a look now.

cc @randall77

**Comment by josharian** [comment]
Looks like the builder is still wedged, based on build.golang.org. Re-opening until the dashboard is functional again. I still can't remember who runs the mipsle builder, and https://github.com/golang/go/wiki/DashboardBuilders doesn't say.

Whoever runs the mipsle builder, can you kill all the old compilation processes that are spinning, and please update the wiki so I can find you in the future? Thanks.

cc @minux because maybe he knows who runs the builder.

**Comment by bradfitz** [comment]
@josharian, the page you linked to references http://farmer.golang.org/builders at the top, and http://farmer.golang.org/builders says who owns it. (Brendan Kirby, imgtec.com)

**Comment by cherrymui** [comment]
The owner of the builder is @MIPSbkirby, as per comments in #19641.

**Comment by josharian** [comment]
Thanks @bradfitz. I edited the wiki to make that section stand out a bit more and filed #19848 as a follow-up.

Thanks, @cherrymui, for pinging Brendan.

**Comment by MIPSbkirby** [comment]
I'm killing the build processes that are building commits before fc327a1 to get this cleaned up.  When it starts builds at or after that commit, I'll leave it alone.

**Comment by josharian** [comment]
Thanks, @MIPSbkirby! Looks like the build dashboard is slowly recovering.
