### ISSUE TITLE
build: add github handles to farmer.golang.org/builders

### ISSUE THREAD

**Issue by josharian** [golang/go#19848]
When something goes wrong with a builder (such as #19842 or #19641), it is usually reported in an issue, and the easiest way to notify the owner of the builder is to @-mention them. It would be helpful for farmer.golang.org/builders (and https://github.com/golang/go/wiki/DashboardBuilders) to have that information readily available. Even when the owner is golang-dev, it'd be useful to have a primary point of contact listed.

cc @bradfitz

**Comment by bradfitz** [comment]
CLs welcome. x/build/dashboard/builders.go

**Comment by josharian** [comment]
CL 39553 adds Brendan's github handle in plain text. It's a start.

**Comment by jessfraz** [comment]
is there a list of all the owners somewhere and I can add them?

**Comment by bradfitz** [comment]
It's kinda commented in English on the wiki and in dashboard/builders.go.

Otherwise you might need to venture into searching golang-dev threads.

But please!

**Comment by jessfraz** [comment]
gotcha gotcha... i realized after i said it _if_ there was a nifty list someone probably would have already done it haha, will investigate
