### ISSUE TITLE
proposal: go get/build/install Makefile support

### ISSUE THREAD

**Issue by saschagrunert** [golang/go#19849]
Hey Gophers, I have a proposal for a more flexible build environment:

If I run `go get` or `go build` then would it be great if it executes `make` if a `Makefile` exists in the current directory. It could also work via a configuration flag:

```
go build --backend=make
```

Furthermore it would be good to use such options via a configuration file (like a `Go.toml` inside the main directory, our [Rust brothers already do this](http://doc.crates.io/manifest.html)), to tell the compiler to apply package specific settings during a simple execution of `go build`.

This has the benefit that I can create more flexible build environments, like downloading artifacts from certain place during the build. What do you think?

**Comment by bradfitz** [comment]
This would not be portable (won't work on Windows), won't work if you don't have the tools in general, and means a "go get" suddenly can run arbitrary code on your machine, which has never been the case before.

We tend to check in auto-generated build artifacts instead (see https://blog.golang.org/generate).

Sorry, I'm going to decline this.
