### ISSUE TITLE
cmd/compile: address calculation before write barrier check

### ISSUE THREAD

**Issue by randall77** [golang/go#19853]
```
type T struct {
	a, b *int
}

func f(p *T, q *int) {
	p.b = q
}
```
Compiles to
```
	0x001d 00029 (/Users/khr/go/tmp1.go:8)	MOVQ	"".p+32(SP), AX
	0x0022 00034 (/Users/khr/go/tmp1.go:8)	TESTB	AL, (AX)
	0x0024 00036 (/Users/khr/go/tmp1.go:8)	MOVL	runtime.writeBarrier(SB), CX
	0x002a 00042 (/Users/khr/go/tmp1.go:8)	LEAQ	8(AX), DX
	0x002e 00046 (/Users/khr/go/tmp1.go:8)	TESTL	CX, CX
	0x0030 00048 (/Users/khr/go/tmp1.go:8)	JNE	69
	0x0032 00050 (/Users/khr/go/tmp1.go:8)	MOVQ	"".q+40(SP), CX
	0x0037 00055 (/Users/khr/go/tmp1.go:8)	MOVQ	CX, 8(AX)
	0x003b 00059 (/Users/khr/go/tmp1.go:9)	MOVQ	16(SP), BP
	0x0040 00064 (/Users/khr/go/tmp1.go:9)	ADDQ	$24, SP
	0x0044 00068 (/Users/khr/go/tmp1.go:9)	RET
	0x0045 00069 (/Users/khr/go/tmp1.go:8)	MOVQ	DX, (SP)
	0x0049 00073 (/Users/khr/go/tmp1.go:8)	MOVQ	"".q+40(SP), AX
	0x004e 00078 (/Users/khr/go/tmp1.go:8)	MOVQ	AX, 8(SP)
	0x0053 00083 (/Users/khr/go/tmp1.go:8)	PCDATA	$0, $1
	0x0053 00083 (/Users/khr/go/tmp1.go:8)	CALL	runtime.writebarrierptr(SB)
	0x0058 00088 (/Users/khr/go/tmp1.go:8)	JMP	59
```
Note the LEAQ instruction at offset 42.  It is only used by the store at offset 69.  We should move it to just before 69 so it only has to execute if write barriers are on.

The tighten pass is responsible for this kind of move, but unfortunately it runs before lowering.  Before lowering there is a use of the LEAQ (at that time, an OffPtr) on both sides of the branch.  It is used by the non-write-barrier store, but that use goes away during lowering because the OffPtr gets folded into the store.

Another tighten run after lowering would fix this, but that's an awfully big hammer.

**Comment by philhofer** [comment]
We could consider encoding constant offsets in `Load/Store/StoreWB` ops, which would presumably make lots of `OffPtr` ops dead. Presumably lowered CSE would take care of the degenerate case in which we couldn't fuse the memory access and the displacement.
