### ISSUE TITLE
cmd/compile: Could make better use of "bimm64" on ARM64

### ISSUE THREAD

**Issue by dr2chase** [golang/go#19857]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9devel

### What operating system and processor architecture are you using (`go env`)?
ARM64

### What did you do?
Compiled `x & ((1<<63)-1)`

We currently convert this to a
`(LSR 1 (LSL 1 x))`
because that is more efficient than loading the immediate.

However, 64-bit AND apparently takes a "bimm64" operand which can contain some not entirely well specified runs of 0 and 1, that happens to include `((1<<63)-1)`.  This came from an investigation into whether the problematic idiom described in #19809 might occur in code compiled from C or C++.  I discovered that it does not, and that the operand can be expressed compactly as an immediate to logical operations.

I don't yet know if the Go assembler handles bimm64; the bug is filed so as not to forget this.

**Comment by cherrymui** [comment]
Generic rule rewrites certain AND to shifts
```
// Rewrite AND of consts as shifts if possible, slightly faster for 64 bit operands
// leading zeros can be shifted left, then right
(And64 <t> (Const64 [y]) x) && nlz(y) + nto(y) == 64 && nto(y) >= 32
  -> (Rsh64Ux64 (Lsh64x64 <t> x (Const64 <t> [nlz(y)])) (Const64 <t> [nlz(y)]))
```
and we didn't undo this in ARM64 rules. Should we?

**Comment by dr2chase** [comment]
We could, it would be easy, just augment the (new) rule that converts (LSR k(LSL k x)) into (ROR k (LSL k x)) into one that uses the AND.  I think no need to check the usage of the LSL because if it's > 1 that means the instruction count remains the same.

**Comment by cherrymui** [comment]
Yeah, I did this. It also reveals a (performance) bug in the assembler backend that some constants did not get encoded into instruction although it could. CLs are coming.
