### ISSUE TITLE
x/build: move beta.golang.org to GKE

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19867]
tip.golang.org runs on GKE (see x/tools/cmd/tip *.yaml)

beta.golang.org runs on a manually-managed GCE VM.

This bug is about migrating beta.golang.org to GKE also.

I suppose it could just be the the same as the tip codebase, but with a flag that makes it use the latest tagged beta or rc.

e.g. every 15 minutes, look at go.googlesource.com or github remote tags,

https://go.googlesource.com/go/+refs

And look at anything containing "beta" or "rc" in the tag name.

Then find the thing with the most recent date, and make the "tip" binary switch to that.

Once maintner is deployed (#19866) soon here, the tip binary could just poll maintner to ask that question about which version is the latest beta.

**Comment by mxplusb** [comment]
@bradfitz cool, I can take a look at this once #19866 is done, so I can see what changed.

**Comment by agnivade** [comment]
There is no separate beta.golang.org now. It points to the same IP as tip.golang.org. Closing this. Feel free to reopen if this was a mistake.
