### ISSUE TITLE
x/build: productionize maintner

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19866]
Move maintner to GKE & give it a hostname.

**Comment by jessfraz** [comment]
does this: https://github.com/golang/build/blob/master/maintner/maintnerd/maintnerd.go need a Dockerfile then? 😇

**Comment by bradfitz** [comment]
Yup!

It'll likely look similar to https://github.com/golang/build/blob/master/cmd/gitmirror/Dockerfile which you'll probably gag looking at.

But so far that's the best mechanism I've found to pin versions of Go deps in container images.

**Comment by jessfraz** [comment]
I saw it cringed and then realized it was actually an inventive way to do a versioning system lol

**Comment by bradfitz** [comment]
Really there should be one Dockerfile to build the binary, and then a Makefile (cringe?) or other driver tool to copy the binary out of Dockerfile 1 into super-minimal Dockerfile 2 that lacks the go compiler or any go source code.

**Comment by jessfraz** [comment]
eventually we can use this new feature for nested builds: https://github.com/docker/docker/pull/32063

BUT I have a makefile technique for other repos with the one dockerfile to build, one to actually use song and dance

**Comment by jessfraz** [comment]
can you assign this one to me so i close it when i make them all minimal :)

**Comment by bradfitz** [comment]
Thanks for the Dockerfile. I'll try to productize this soon. Still fighting a Github sync issue that's easier to debug locally for now.

**Comment by AlekSi** [comment]
There are data races that should be fixed. Noticed with
```
go get -u -v -race golang.org/x/build/maintner/...
maintnerd -config=go
```

**Comment by bradfitz** [comment]
@AlekSi, thanks! I sent out https://go-review.googlesource.com/c/42615/

**Comment by AlekSi** [comment]
Another thing: there is no handling of termination signals in maintnerd. Ctrl+C instantly kills the processes without any graceful context cancelations. If I understand correctly, this greatly increases the chances of data corruption (cache becoming out-of-sync), especially during initial sync.

I'm interested in helping with this if dust is settled enough in this place.

**Comment by bradfitz** [comment]
Lack of graceful shutdown is not a problem because all robust programs must be able to also survive un-graceful shutdowns, which maintnerd should. It has a pretty paranoid on-disk record format.
