### ISSUE TITLE
strconv.Unquote:  invalid syntax

### ISSUE THREAD

**Issue by imkos** [golang/go#19864]
```go
s := `"{\"a\":\"https:\/\/golang.org\"}"`
//s1 := strings.Replace(s, `\/`, `/`, -1)
s1 := s
ss, err := strconv.Unquote(s1)
fmt.Println(ss, err)

err: invalid syntax
```

**Comment by bradfitz** [comment]
This is not structured like a bug report. Because you deleted our standard template, I don't know what you were expecting.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by imkos** [comment]
this is "s" string from php json_encode()

**Comment by bradfitz** [comment]
This is a question for the forums, not the bug tracker.
