### ISSUE TITLE
macos10.12.4 terminal go run xx.go  out put  signal: killed

### ISSUE THREAD

**Issue by jjjachyty** [golang/go#19863]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.3 darwin/amd64
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/DATA/Work/CODE/GO/GOPATH"
GORACE=""
GOROOT="/DATA/Work/CODE/GO/GOROOT/go"
GOTOOLDIR="/DATA/Work/CODE/GO/GOROOT/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b8/zzns3gv54gxbdgz0_fxb1hjh0000gn/T/go-build092432085=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
go run xxx.go

### What did you expect to see?

run my app
### What did you see instead?
signal: killed

**Comment by ALTree** [comment]
If you are using Xcode 8.3, this is likely a dup of #19734. Are you?

**Comment by ALTree** [comment]
Assuming this is a dup of #19734. Closing.
