### ISSUE TITLE
cmd/internal/obj: delete Cputime and all its uses

### ISSUE THREAD

**Issue by josharian** [golang/go#19865]
obj.Cputime is used to print elapsed time in various places in the assemblers. It is protected by ctxt.Debugvlog. However, `toolstash -cmp` sets Debugvlog to true, causing rare spurious timing-based failures. They are rare because the elapsed time is basically always ~0. We could introduce a special flag to turn on/off this timing printing, but I'd rather just wipe it all out. We have good profiling and benchmarking tools; we should use them instead, if/when the assemblers ever become an actual performance bottleneck.

Objections? Not sure who quite who to cc here for input, but maybe: @minux @cherrymui @randall77

**Comment by cherrymui** [comment]
IIRC `obj.Cputime` is also used in the linker when -v is set.
Just curious, why `toolstash -cmp` needs to set `Debugvlog`?

**Comment by josharian** [comment]
> Just curious, why toolstash -cmp needs to set Debugvlog?

Debugvlog is pretty heavily overloaded. toolstash -cmp uses it to ask the compiler to emit much more detailed versions of the generated assembly, to better confirm that it is identical.

Why does the linker need obj.Cputime? Any reason we couldn't use pprof instead?

**Comment by cherrymui** [comment]
> Why does the linker need obj.Cputime? Any reason we couldn't use pprof instead?

I believe it is just historical reason.

**Comment by cherrymui** [comment]
At long time, we probably should get rid of obj.Cputime and use pprof.
As a workaround, could `toolstash -cmp` filter out Cputime outputs?

**Comment by josharian** [comment]
I guess the question is: Why not now?

**Comment by josharian** [comment]
Slight misdiagnosis: It's not that variance in the timing *causes* toolstash -cmp failures. Rather, when toolstash -cmp fails, it causes the output to be about timing rather than about something useful.

I'll send a note to golang-dev to see whether anyone is actively using this.

**Comment by mdempsky** [comment]
Yeah, those timing lines are obnoxious when diffing toolstash log files. I for one wouldn't miss them.

**Comment by cherrymui** [comment]
> I guess the question is: Why not now?

No problem with me, if you want to take it :)

**Comment by josharian** [comment]
CL 39914 deletes all the assembler usages, which are the ones currently driving me crazy. If no one speaks up on behalf of the linker usages in the next few days, I'll do them too.

**Comment by thanm** [comment]
@josharian  are you still interested in this CL? I can take a closer look and +2 if so.

**Comment by josharian** [comment]
Yes please.

**Comment by thanm** [comment]
Ok, SGTM. I am in transit at the moment, will take a closer look tomorrow.
