### ISSUE TITLE
cmd/compile: non-deterministic build blocking use of toolstash-check

### ISSUE THREAD

**Issue by mdempsky** [golang/go#19872]
At master, running toolstash-check on a CL that just adds a comment to cmd/compile causes this failure:

    # html/template
    toolstash: compiler output differs, even with optimizers disabled (-N)

    inconsistent log line:
    /tmp/go-build151744301/html/template.a.log:84904:
            type..namedata.**template.Template. t=8 dupok size=22
    /tmp/go-build151744301/html/template.a.stash.log:84904:
            type..namedata.*[]uint8. t=8 dupok size=11

@griesemer is seeing the same thing. It appears to be from CL 39710.

@josharian It looks like LongString isn't a total ordering either. :(

**Comment by josharian** [comment]
I'm an idiot. I missed the obviously correct ordering, which is to do what the actual export code (dtypesym) does.
