### ISSUE TITLE
Unexpected behaviour when append

### ISSUE THREAD

**Issue by DamiaPoquet** [golang/go#19876]
### What version of Go are you using (`go version`)?
`go version go1.8 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
`GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build924327302=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"`

### What did you do?
I'm opening a text file which contains a random string in each line. Then using the bufio's scanner to get the []byte of each line and append it in to a [][]byte.

Code: https://play.golang.org/p/yp4dh0UiEV
Text file: [test.txt](https://github.com/golang/go/files/905385/test.txt)

### What did you expect to see?
I expect to see always the same content on data[0].

### What did you see instead?
The content of data[0] is changing when appending new elements in to the slice.

**Comment by dongweigogo** [comment]
I'm guessing it's a reference to the internal buffer

**Comment by martisch** [comment]
This seems working as intended and documented:
https://golang.org/pkg/bufio/#Scanner.Bytes

"Bytes returns the most recent token generated by a call to Scan. The underlying array may point to data that will be overwritten by a subsequent call to Scan. It does no allocation."

Therefore a copy of the byte slice from Bytes() is needed for data[0] to not change.

Also see: https://blog.golang.org/go-slices-usage-and-internals

For questions about Go, see https://golang.org/wiki/Questions.
