### ISSUE TITLE
cmd/go: go install doesn't recognize changes to c code in another directory

### ISSUE THREAD

**Issue by alexd765** [golang/go#19883]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
``go version devel +a8b2e4a Fri Mar 31 21:24:09 2017 +0000 linux/amd64``

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alex/gopath"
GORACE=""
GOROOT="/home/alex/go"
GOTOOLDIR="/home/alex/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build681403283=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

* ``go install -v`` program with c code
* make changes to c code in different directory
* ``go install -v`` again

If possible, provide a recipe for reproducing the error.

```
cat main.go:
package main

import "fmt"

/*
#include "test/test.h"
*/
import "C"

func main() {
	fmt.Println(C.x)
}
```

```
cat test/test.h:
int x=1;
```

[on github](https://github.com/alexd765/cgo-issue)

### What did you expect to see?
```
go install -v
github.com/alexd765/cgo-issue
```
change to x=2 in test/test.h
```
go install -v
github.com/alexd765/cgo-issue
```

### What did you see instead?
```
go install -v
github.com/alexd765/cgo-issue
```
change to x=2 in test/test.h
```
go install -v
```

* go install thinks the code didn't change.
* It works if the c code is in the same directory.
* it doesn't work if the c code is in another directory (outside or subdirectory).

**Comment by bradfitz** [comment]
Of note: cmd/go is a Go build system and not a C build system. But I'll let @rsc decide what to do here, if anything.

**Comment by alexd765** [comment]
That makes sense.

This is obviously a minimal example. I want to give a little bit more context how I ran into this:

We have a not-so-thin wrapper around a C library that is a mix of Go and C code that we install with go install (without the -v). When we make changes to go code and c code at the same time everything works.
When we made only changes to the C Code it was quite surprising that the new version didn't get installed.

The workaround is to force rebuilding with go install -a.

**Comment by rsc** [comment]
The Go command essentially requires that your C code be in the same directory as the Go package using it, not in a subdirectory or other directory. This is by design: package directories are meant to be completely self-contained, although obviously this is difficult/impossible to enforce in all cases.
