### ISSUE TITLE
runtime: deltimer in time.go doesn't update the last after removing a timer

### ISSUE THREAD

**Issue by ghasemloo** [golang/go#19887]
https://github.com/golang/go/blob/master/src/runtime/time.go#L148
We remove the timer `t` at location `i` from the heap `timers.t` by replacing `timers.t[i]` with the last timer in the heap slice and then shrinking the slice. Then we need to shift it up/down to its correct location in the heap. In line 148 there is a short path that checks if it is already the last item in the heap slice.

We have not updated the value of the variable `last` so this `if` will always fail and we will perform shift up/down even if it is the last item in the updated slice. If we want to avoid shift up/down in that case we should either update the value of the variable `last` by `last--` after line 147 or use `if i != last-1 {` instead of `if i != last {`; 

However I think the short path might not actually work. The last item in the heap slice is not the largest item, even if its new location is the new last item of the slice it doesn't mean it is in the right location because it may need to move up, consider [0, 5, 2, 6, 7, 4] and assume we remove 7. if we don't perform a shift up/down we will end up with [0, 5, 2, 6, 4] which doesn't have the heap property as 4 is a child of 5 but is smaller than it. So I think we should just remove the `if` for the short path and always do shift up/down.

**Comment by ianlancetaylor** [comment]
It's true that we haven't updated the variable `last`, but we also haven't updated the variable `i`.  If the condition `i != last` was true a few lines up, it will still be true.  This code looks correct to me.

**Comment by ghasemloo** [comment]
I see. So this if is not a short path for checking if the last timer is still the last in the slice but for checking if we moved a timer in which case we need a shift up/down and otherwise we don't need to.
