### ISSUE TITLE
doc: Website build instructions incomplete

### ISSUE THREAD

**Issue by dagelf** [golang/go#19892]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
Debian 8

### What did you do?
wget https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
tar -zxvf go1.8.1.linux-amd64.tar.gz
mv go go1.8.1
git clone https://go.googlesource.com/go
cd go
git checkout go1.8.1
cd src
export GOROOT_BOOTSTRAP=/usr/src/go1.8.1/bin/
export GOROOT=/usr/src/go1.8.1/bin/
GOOS=linux GOARCH=amd64 ./bootstrap.bash
Copying to ../../go-linux-amd64-bootstrap

Cleaning ../../go-linux-amd64-bootstrap

Building ../../go-linux-amd64-bootstrap

Building Go bootstrap tool.
cmd/dist
go tool dist: $GOROOT is not set correctly or not exported
	GOROOT=/usr/src/go-linux-amd64-bootstrap
	/usr/src/go-linux-amd64-bootstrap/src/all.bash does not exist

### What did you expect to see?
all.bash to build go with

### What did you see instead?
see above. 

Any other variables or commands just gives more error messages. A really ugly welcome to newcomers trying to build / install an up to date go.

**Comment by dagelf** [comment]
The main Golang website and build instructions for building from source.

**Comment by ALTree** [comment]
Is there any reason you're not using the precompiled linux-amd64 binaries? ("the website didn't tell me this was the recommended way" is a valid answer.)

**Comment by dagelf** [comment]
Linux has a bad track record with precompiled binaries. I know go can help
change that ;-) I come form the Gentoo world so if the packaged version is
outdated I usually head straight for the source to get to know the
community and start figuring out why the packaged versions are so far
behind... Debian is on 1.3. And a developer who has to spend an hour or two
extra just to get to a first build because of quirky environmental
dependencies has an hour or two less of his/her precious time to keep their
distro package up to date, so I'm keen and willing to help make sure
newcomers can always hit the ground running. Is there a suggested
development environment, or one an official Golang docker tag?

**Comment by ALTree** [comment]
No, no, wait. I'm not talking about the Linux packages (e.g. the `apt-get install` ones). We have precompiled, always-up-to-date binaries for linux on the website. It literally as simple as

```
# get the archive
$ wget https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz

# extract in /usr/local
$ sudo tar -C /usr/local -xzf go1.8.1.linux-amd64.tar.gz

# add to PATH
$ export PATH=$PATH:/usr/local/go/bin
```

and now you have the latest go version on your machine.

The download page says:

> After downloading a binary release suitable for your system, please follow the installation instructions. 

and `installation instructions` point at this page: https://golang.org/doc/install.

Maybe we should make more clear (in the download page) that unless you have a very good reason to build from source you should use the binaries.

**Comment by mikioh** [comment]
@dagelf,

```
export GOROOT_BOOTSTRAP=/usr/src/go1.8.1/bin/
export GOROOT=/usr/src/go1.8.1/bin/
  :
go tool dist: $GOROOT is not set correctly or not exported
```

Both GOROOT and GOROOT_BOOTSTRP must specify the root of the Go tree as described in https://golang.org/doc/install/source.

**Comment by bradfitz** [comment]
The GOROOT* variables also should not contain the `bin` element.

**Comment by dagelf** [comment]
That is the page I followed. /bin or without doesn't matter.

$ export GOROOT=/usr/src/go1.8.1/
$ export GOROOT_BOOTSTRAP=/usr/src/go1.8.1/
$ /usr/src/go1.8.1/bin/go version
go version go1.8.1 linux/amd64
$ rm -rf ../../go-linux-amd64-bootstrap
$ GOOS=linux GOARCH=amd64 ./bootstrap.bash
Copying to ../../go-linux-amd64-bootstrap

Cleaning ../../go-linux-amd64-bootstrap
Removing src/cmd/dist/dist

 Building ../../go-linux-amd64-bootstrap

Building Go bootstrap tool.
cmd/dist
go tool dist: $GOROOT is not set correctly or not exported
GOROOT=/usr/src/go-linux-amd64-bootstrap
../../go-linux-amd64-bootstrap/src/all.bash does not exist
../../go/src/all.bash does not exist

I will try it in a docker tomorrow.

**Comment by ALTree** [comment]
You are not following the instructions on that page. It says:

> To cross-compile a bootstrap tool chain from source, which is necessary on systems Go 1.4 did not target (for example, linux/ppc64le), install Go on a different system and run bootstrap.bash. 

emphasis: 

> **which is necessary on systems Go 1.4 did not target**

you don't need to call ` ./bootstrap.bash` on linux/adm64.

**Comment by josharian** [comment]
> $ export GOROOT_BOOTSTRAP=/usr/src/go1.8.1/

GOROOT_BOOTSTRAP needs to be set to an existing, fully functional Go toolchain. You can use a precompiled binary for that, or you can use Go 1.4, which can be compiled with just a c compiler. (Same repo remote, use release-branch.go1.4 instead.)

These instructions are definitely not clear enough. Once you get everything working, if you want to circle back around and look at them again with your hard-won understanding, suggestions would be welcome.

**Comment by dagelf** [comment]
On this page: https://golang.org/doc/install/source - may I suggest moving the section that  on cross-compilation (starting with "To cross-compile..." until the end of that section) down to just underneath the sections that says "Install Go", perhaps to its own section "Cross Compiling Go", instead of so close to the top.

That would logically make more sense. The mere name "bootstrap" doesn't allude to cross-compilation, and one would expect the most straightforward build commands to come before the more complex ones, and unfortunately we don't live in an ideal world where everyone has time to read all the instructions when the solution seems obvious :-)

_I_ have gotten a few steps further just running **./all.bash**... but still failing to build (1.8.3 with 1.8.3 on Ubuntu 16.04, looks like just one test failing through (FAIL: TestUnshare)... 

To answer the question "why don't I just do a binary install"  - many Linux distributions ship with packages and are installed off-line. (80% of the planet still doesn't have internet, I'm at the forefront of rolling out internet to areas that doesn't have any, which somewhat ironically sees me needing to work in an offline environment quite often). Having a different installation method creates a special case - a package that needs to be handled differently from all the others. Not being able to automate a build of said package (because of random build errors that need manual troubleshooting) causes the shipped packages to fall behind because our time is a rare commodity. Having clear build instructions that can be skimmed over quickly, or builds that don't require special provisions, really helps distributions stay up-to-date.

**Comment by dagelf** [comment]
Quick note on my unrelated build error - the test has been patched, builds fine with the patch: https://go-review.googlesource.com/c/48571/2/src/syscall/exec_linux_test.go#186
