### ISSUE TITLE
Trouble using ssh package

### ISSUE THREAD

**Issue by farhatnawaz** [golang/go#19898]
### What version of Go are you using (`go version`)?
1.8.1
### What operating system and processor architecture are you using (`go env`)?
Mac
### What did you do?
I am trying to use the ssh package but I get an error on the import. I am using `import "golang.org/x/crypto/ssh"`
I get the error that "can't find package 'golang.org/x/crypto/ssh' in any of the root paths". Is there something I am doing wrong??

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

It's not clear that you even ran `go get` to download it.

**Comment by farhatnawaz** [comment]
I did run `go get` but the problem persists.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
