### ISSUE TITLE
x/mobile: make it easier to publish on appstore

### ISSUE THREAD

**Issue by fastfading** [golang/go#19904]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
macos

### What did you do?
gomobile build ios app and want to pubulish on appstore
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
ios app could be publish on appstore

### What did you see instead?
ios app need a lot of steps to make it publish on appstore

**Comment by eliasnaur** [comment]
I think this issue is too vague. Please describe what steps gomobile should help you with. Please also state whether you're using gomobile bind or gomobile build apps.

**Comment by fastfading** [comment]
I  am using  gomobile build a native apps.
but this app was unable to upload to itunesconnect.
too many errors,    so , yes, this issue is too vague.
But the go is very simple,  to make gomobile build apps publish on appstore.
It seems it is impossible now.

2018-03-16 18:58 GMT+08:00 Elias Naur <notifications@github.com>:

**Comment by eliasnaur** [comment]
Ok, I'll close this as a dup of #20241, since that issue is more specific.
