### ISSUE TITLE
misc/cgo/testcarchive: Go 1.7 test failure: got signal: broken pipe; expected SIGSEGV

### ISSUE THREAD

**Issue by EndlessIdea** [golang/go#19905]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7.4

### What operating system and processor architecture are you using (`go env`)?
linux

### What did you do?
I downloaded go1.8, tar zxvf it, then sh src/all.bash. But I didn't install successfully.

##### ../misc/cgo/testcarchive
--- FAIL: TestSignalForwarding (0.79s)
	carchive_test.go:265: 
	carchive_test.go:266: got signal: broken pipe; expected SIGSEGV
FAIL
2017/04/10 16:19:13 Failed: exit status 1

### What did you expect to see?
I expect to see install succefully.

### What did you see instead?
Fail

**Comment by bradfitz** [comment]
Can you try Go 1.8? We no longer maintain Go 1.7, except for critical/security issues.

**Comment by ianlancetaylor** [comment]
Don't forget to tell us what type of processor you are using.  It matters.

**Comment by EndlessIdea** [comment]
@bradfitz Sorry, I can't use Go 1.8, because what I was trying to do is to update Go 1.7 to Go 1.8. I came to this problem when I was running src/all.bash to update Go version to 1.8.

**Comment by EndlessIdea** [comment]
@ianlancetaylor OK. Here's my processor info.
model name	: Intel Xeon E312xx (Sandy Bridge)
stepping	: 1
cpu MHz		: 2094.950
cache size	: 4096 KB

**Comment by ALTree** [comment]
Go1.7 is no longer maintained and we never received others reports of this test failure, so I think it's safe to assume that this is no longer a problem. Closing here.
