### ISSUE TITLE
Golang not detecting vendor folder

### ISSUE THREAD

**Issue by ajmichaels** [golang/go#19919]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/aaronmichaels/Developer/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hm/nb7xhr9961v06dsc9jsm95m80000gn/T/go-build516539570=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
I used the glide tool (`https://github.com/Masterminds/glide`) to install a dependency (`github.com/appliedgo/perceptron/draw`) at `/Users/aaronmichaels/Developer/go/src/github.com/ajmichaels/misc/appliedgo/perceptron.`

 Under this directory, I have a glide.yaml file, a glide.lock file, a main.go file, and a vendor/ folder.  Within the main.go file, I have `"github.com/appliedgo/perceptron/draw"` imported.  However, when I try to go build my main.go file, I get this error:  

main.go:8:2: cannot find package "github.com/appliedgo/perceptron/draw" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/appliedgo/perceptron/draw (from $GOROOT)
	/Users/aaronmichaels/Developer/go/src/github.com/appliedgo/perceptron/draw (from $GOPATH)

My gopath is `/Users/aaronmichaels/Developer/go`, so the error is not related to not being within my gopath.  Also, projects with dependencies installed via `go get` work fine.

### What did you expect to see?
From what I've seen online, the go build command should have run with no errors.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by ajmichaels** [comment]
Hi @bradfitz I'm not asking a question, this is a bug report.

**Comment by bradfitz** [comment]
Please start with the mailing list. This looks like user error instead of a clear bug report.

If you have a problem with glide, please file a bug report against glide.

**Comment by ajmichaels** [comment]
@bradfitz I will ask on the mailing list, but I consulted with the go-nuts irc channel and it looks like a bug.  Also https://github.com/golang/go/issues/19916 seems to a similar (same?) bug.

**Comment by bradfitz** [comment]
#19916 also looks like a question instead of a bug report.

**Comment by ajmichaels** [comment]
How do I make it look like a bug report instead of a question?

**Comment by bradfitz** [comment]
The mailing list can help solve your problem and/or help you file a bug report.

But in general, we don't have the resources to help debug external tools.

**Comment by laboger** [comment]
This is probably the same as https://github.com/golang/go/issues/15628 since vendoring has never really worked with gccgo AFAIK.  I just posted a CL in that issue to fix the problem when using the go tool built for gccgo (not golang yet).

Another suggestion is for you to explicitly add the -I option(s) to your GCCGOFLAGS to identify the vendor paths of the missing packages.

**Comment by javasgl** [comment]
when has multi GOPATH, It can`t detect the vendor folder.
```
go env
....
GOPATH="/go/codes/path1:/go/codes/path2"
....
```

**Comment by lafolle** [comment]
Hi @ajmichaels ,

`github.com/appliedgo/perceptron/draw` is what you intend to import,  but in `src` folder your pkg is `github.com/ajmichaels/misc/appliedgo/perceptron`.  

Note "misc".
