### ISSUE TITLE
x/build: linux/arm64 builder is missing

### ISSUE THREAD

**Issue by rsc** [golang/go#19929]
linux/arm64 builder is gone, would like it to come back.

**Comment by bradfitz** [comment]
Deployed. There are now 20 `linux-arm64-packet` buildlets available via gomote, etc. 

Thanks to packet.net for the beefy server (https://www.packet.net/bare-metal/servers/type-2a/) which runs the 20 buildlets.

Code & config in https://go-review.googlesource.com/40392
