### ISSUE TITLE
runtime: makemap should treat the size parameter as a hint and not panic if it's too big

### ISSUE THREAD

**Issue by gruszczy** [golang/go#19926]
This  came up during work on https://go-review.googlesource.com/c/40113/. Currently when the hashmap receives a size hint it can't use (for example because it's too big), it panics. Instead, it should treat purely as a hint about the required size and adjust it to what is possible.

**Comment by gruszczy** [comment]
I would be happy to make the changes too.

**Comment by rsc** [comment]
Sure, contributions welcome @gruszczy. Thanks.

**Comment by josharian** [comment]
SGTM. Please add khr and josharian as reviewers on the CL.

**Comment by josharian** [comment]
@gruszczy also, feel free to ask implementation questions here if you need any pointers. If you haven't already discovered this, you'll want to look at runtime/hashmap.go, func makemap, pretty near the beginning of the function.

**Comment by griesemer** [comment]
See also #19903.
