### ISSUE TITLE
cmd/go: remove go get's hostname check?

### ISSUE THREAD

**Issue by lon-yang** [golang/go#19923]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
windows and amd64

### What did you do?
When using `go get` command to get a package from private gitlab repo like `https://gitlab2`, this repo's url not contains `.` . Then i got the error `import path does not begin with hostname`.

### What did you expect to see?
Can we remove the hostname check? [https://github.com/golang/go/blob/master/src/cmd/go/internal/get/vcs.go#L659-L662](https://github.com/golang/go/blob/master/src/cmd/go/internal/get/vcs.go#L659-L662)

**Comment by mvdan** [comment]
I think this is by design throughout `go get`. See the "remote import paths" section in `go help importpath`. Are you suggesting to change `go get`'s design?

**Comment by bradfitz** [comment]
gitlab1 didn't work out well? :)

Did you consider using names like "git.yourcorp.com"? That's more idiomatic Go.

**Comment by lon-yang** [comment]
Yes. The hostname like 'git.yourcorp.com' is more idiomatic. But sometimes this is not what we can decide, especially in the internal network. And the check rule just checked that whether the hostname contains '.'. simple?

@mvdan , @bradfitz  Thanks anyway!

**Comment by garethwarry** [comment]
This has also impacted my workplace. For a local server, the hostname "sw" isn't permitted but is a valid import path for a hosted gitlab server. I would like to see this check and the [redirection check](https://github.com/golang/go/issues/19760) on the import path removed. I don't get why there are so many unnecessary checks on "go get".

**Comment by mattn** [comment]
If removing dot, the name will be treated as standard package. If you write hostname `encoding` into your `/etc/hosts`, go will have to `git clone encoding/json` with importing `encoding/json`.

**Comment by lon-yang** [comment]
So at present, the only way is use `git clone` then run `go install`？

**Comment by mattn** [comment]
Yes, but I can't say for sure if you use anothor tools.

**Comment by lon-yang** [comment]
Most tools is also use `go get` to get packages. It's not easy. But thanks anyway!
