### ISSUE TITLE
runtime/pprof: -runtime flag support missing

### ISSUE THREAD

**Issue by josharian** [golang/go#19927]
In Go 1.8, if I wanted to see where in the runtime allocations came from, I could use memory profiling and then run go tool pprof with the -runtime flag. The -runtime flag is absent on tip, and it appears (from trying out the 1.8 pprof tool on the tip profiles) that the data is not being recorded either. This is an impediment to optimizing the runtime.

Perhaps unrelatedly, the 1.8 pprof tool usefully lists the heap profile display modes in its help text:

```
Sample value selection option (for heap profiles):
  -inuse_space      Display in-use memory size
  -inuse_objects    Display in-use object counts
  -alloc_space      Display allocated memory size
  -alloc_objects    Display allocated object counts
```

The tip pprof tool does not.

cc @rsc @matloob

**Comment by rsc** [comment]
Pprof has moved responsibility for this filtering into the profile generators, which is where it belongs. (Pprof shouldn't have a list of magic Go runtime symbols in its source code.) Unfortunately, this means we can't support the -runtime flag.

For your own debugging you can change src/runtime/pprof/protomem.go to say `hideRuntime := false`. I'm not sure whether we should introduce new API to make that possible to trigger without patching.

**Comment by josharian** [comment]
Good to know. Given that this need is mainly for contributors, and it's a single-line patch, I'm ok just patching as needed.

**Comment by rsc** [comment]
OK, will close for now.
