### ISSUE TITLE
go help information shouldn't be sent to stderr

### ISSUE THREAD

**Issue by bruceauyeung** [golang/go#19939]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 windows/amd64
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
~~~
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\GOPATH\EXT
set GORACE=
set GOROOT=D:\Go
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\10079130\AppData\Local\Temp\go-build964560747=/tmp/go-build -gno-record-gcc-switche
s
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
~~~

~~~
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go-ext-path"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build111001386=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
~~~
### What did you do?
here is my code:
helpstderr.go
~~~
package main

import (
	"flag"
)

func main() {
	flag.Parse()
}
~~~
go build helpstderr.go
run  `helpstderr --help 1>nul`  or `helpstderr --help 1>/dev/null` , i can still get help msg printed.
and echo `%errorlevel%` or `$?` , i got `2`

### What did you expect to see?
when running  `helpstderr --help 1>nul`  or `helpstderr --help 1>/dev/null`, i expect help msg not printed
exit code should be `0`

### What did you see instead?

run  `helpstderr --help 1>nul`  or `helpstderr --help 1>/dev/null` , i can still get help msg printed.
and echo `%errorlevel%` or `$?` , i got `2`

**Comment by bradfitz** [comment]
https://golang.org/pkg/flag/#FlagSet.SetOutput documents the current behavior:

> SetOutput sets the destination for usage and error messages. If output is nil, os.Stderr is used.

And it's been like this (going to stderr) since the beginning of Go.

Regardless of whether stderr or stdout is correct, [go1compat](https://golang.org/doc/go1compat) precludes us changing this, especially after 5+ years of Go 1.x.
