### ISSUE TITLE
runtime: preallocate some overflow buckets when map size hint provided

### ISSUE THREAD

**Issue by josharian** [golang/go#19931]
When populating a large map, there will ~always be overflow. Currently, the map size hint is used to allocate an initial set of buckets, but not to allocate any overflow buckets. As a result, even if you provide a perfect hint to the runtime, populating a large map allocates a lot of times. A quick simulation suggests that adding 100,000 ints to a perfectly-hinted map allocates about 2700 overflow buckets.

Work require to implement this:

* Come up with a good estimator for the number of expected overflow buckets based on hint.
* Find a place to track those pre-allocated overflow buckets, preferably without growing hmap.

cc @randall77

**Comment by griesemer** [comment]
See also #19903.

**Comment by josharian** [comment]
Started on this. Getting a good estimator is proving to be non-trivial; it depends on both the absolute size and how close the resulting map is to loadFactor.

**Comment by josharian** [comment]
This is partly done in CL 40979, insofar as the hint guides the number of buckets, and the number of buckets now guides the number of preallocated overflow buckets. It could be refined further, using the mechanisms of CL 40979, by estimating more precisely the number of overflow buckets needed for the hint, rather than taking the midpoint of the sizes for that its bucket range.

**Comment by randall77** [comment]
Josh, anything else to do here?

**Comment by josharian** [comment]
We could improve the estimation (along the lines of https://github.com/golang/go/issues/19931#issuecomment-295277705), but it's a low enough priority that I think we can call this done.
