### ISSUE TITLE
cmd/compile: incorrect handling of uint64 function parameters(?) on s390x

### ISSUE THREAD

**Issue by jcajka** [golang/go#19940]
### What version of Go are you using (`go version`)?
go version devel +5a45a15 Fri Mar 31 05:02:02 2017 +0000 linux/s390x
also observed with go1.8+

### What did you do?
Following reproducer fails on s390x, https://play.golang.org/p/ktGF0Uev_0

### What did you expect to see?
`PASSED`

### What did you see instead?
```
FAILED
0
1999999999999999999
>=
18446744073709551557
```

**Comment by josharian** [comment]
@mundaym

**Comment by mundaym** [comment]
I think I've found the problem. @jcajka thanks a lot for the reproducer, can you see if [CL 40433](https://go-review.googlesource.com/#/c/40433/) fixes your original issue? In the meantime I'll work on a test.

You can apply the CL by executing the following command in your Go checkout:

`git fetch https://go.googlesource.com/go refs/changes/33/40433/1 && git checkout FETCH_HEAD`

**Comment by jcajka** [comment]
@mundaym seems to fix the issue, thanks for quick fix :)

**Comment by mundaym** [comment]
Reopening: [CL 40433](https://golang.org/cl/40433) is not on release branch.

**Comment by mundaym** [comment]
I can't reopen this, can you @josharian? Based on the [golang-dev discussion](https://groups.google.com/d/msg/golang-dev/peguIwvauvY/DjSz3mtDCwAJ), I think we are supposed to reopen issues that have been fixed in master but not in the release branch for the milestone.

**Comment by josharian** [comment]
@mundaym you should request github access! See https://github.com/golang/go/wiki/GithubAccess.
