### ISSUE TITLE
gotour: fallthrough: ui is unclear

### ISSUE THREAD

**Issue by mh-cbon** [golang/go#19945]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
✖,

### What operating system and processor architecture are you using (`go env`)?
✖,

### What did you do?

I was trying
https://tour.golang.org/flowcontrol/9

### What did you expect to see?

I found it surprising i don t have a button to validate.
There is not an useful link to the related spec, i think it is missing.

note: i suspect some cases are hairy to check as you may have many valid answers?
that example does not fall into that case.
though even for hairy ones, their should be some kind of solutions introduction.

### What did you see instead?

a better ui.

**Comment by bradfitz** [comment]
The tour's bug tracker is https://github.com/golang/tour

Could you report this there?

**Comment by rakyll** [comment]
It is my fault that I suggested @mh-cbon to file the issue here, create another one at https://github.com/golang/tour/issues/199.
