### ISSUE TITLE
how can i contribute golang?

### ISSUE THREAD

**Issue by knightXun** [golang/go#19942]
golang is so exciting，it's honor for me to contribute for this project.my question is how can i contribute to golang.thx all.

**Comment by kevinburke** [comment]
Thanks for writing! A good start would probably be to read the [CONTRIBUTING.md](https://github.com/golang/go/blob/master/CONTRIBUTING.md) for this repository, along with the [Go Contribution Guidelines](https://golang.org/doc/contribute.html). There should be links there to next steps about where to ask for help.

**Comment by knightXun** [comment]
very helpful,but i think this ppt help me most: 2016-11-18-GothamGo-Go-Open-Source-Innards/GothamGo-2016-11-18-Go-Proj-Innards.pdf
