### ISSUE TITLE
x/build/cmd/gomote: add ssh access to builders

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19956]
People have long been requesting ssh access to gomote-creatable builders.

The idea being it'd be something like:

```
you@laptop$ gomote create <instance-type>
user-bradfitz-inst-type0
you@laptop$ gomote ssh user-bradfitz-inst-type0
```

And then you're in bash or whatever (let's ignore Windows and Plan 9 for version 1):

```
gopher@user-bradfitz-inst-type0$ 
```

Architecturally, the connections would be like:

```
    [ Client ]  <-----> [ farmer.golang.org ] <-----> [ ephemeral buildlets ]
```

We'd modify the x/build/cmd/buildlet code to have auth-less ssh support (they're network-isolated), and then modify the x/build/cmd/coordinator (farmer.golang.org) to have an ssh server (well, an additional one on a different port) that did the authentication and proxied to the buildlet's ssh.

I haven't used the x/crypto/ssh package much. I imagine on the buildlet it needs to create a pty (?) or something and run bash.

On the coordinator side, I'm not exactly sure what I need to do in that ssh server after authenticating the client. I'm only vaguely aware of the ssh protocol. At some level I proxy it to the buildlet.

Help wanted. What I'd love to see is:

1. Go ssh server on localhost:2200 that has no auth and drops into bash.
2. Go ssh server on localhost:2201 with auth, proxying to the localhost:2200 ssh server.

(no openssh server; just Go is most deployable in our current environments where we can update the buildlet binaries quickly but the OS images are often more baked)

Alternative I considered: only one ssh server (on the buildlet) with a random password, and have the coordinator only be a TCP proxy. But then I'd still know how to route incoming TCP connections to different backends, implying some protocol there anyway, and I think it can just be ssh.

/cc @hanwen @aclements @ianlancetaylor

**Comment by hanwen** [comment]
there is no standard SSH server in crypto/ssh, because it would have to interact with all the nasty platform bits (process control, ptys, etc.)

I think the fastest solution would be: run openssh on the buildlet (configure it for authless login), and use the coordinator as proxy at the channel level: the proxy passes on all OpenChannel requests. The x/cprypto/ssh/test show how you can start opensshd (but you'll probbably want to run it in daemon mode). 

The proxying takes the input from NewClientConn and passes it into the NewServerConn output and vice versa.

**Comment by bradfitz** [comment]
@hanwen, if I wanted to take advantage of the machines' existing ssh servers, could I do that?

Can the OpenChannel dialer do the ssh client auth (mix of fixed passwords & keys), establish the channel, and then stitch them together?

**Comment by hanwen** [comment]
Yes, that should work. 

I would avoid passwords if you can. Public keys are easier to manage: you have to protect the secret in just one place, and they're immune to MITM attacks.

**Comment by bradfitz** [comment]
A lot of our build VM images have fixed passwords. e.g. gopher/gopher:

https://github.com/golang/build/blob/9412838986dd9e33dcc936f994012a6941c55bbf/env/openbsd-amd64/make.bash#L99

We're not exactly secret about those. They're one-off VMs and run on isolated networks.

But good to hear using the existing ssh server should work. I'll play.
