### ISSUE TITLE
I fixed the Gopher SVG illustration

### ISSUE THREAD

**Issue by jeroenransijn** [golang/go#19950]
Hi there Go community. This might be the absolute wrong place to post about this, but I am not sure where I should put this. The SVG Gopher for Go, which is used around the web can't be resized properly. If you look around official resources of Google you can see the resized Gophers with thick borders (the border is always a certain width, even if you resize it). We are using the Gopher in our app and I fixed the SVG Gopher:

[Go.svg.zip](https://github.com/golang/go/files/917639/Go.svg.zip)

I am not sure where to put this, but thought the community might now where.

**Comment by odeke-em** [comment]
Thank you @jeroenransijn!
/cc @campoy @bradfitz @broady, might y'all have some input on how to move forward here?

**Comment by bradfitz** [comment]
We can't take contributions on the bug tracker.

To send a change, see https://golang.org/doc/contribute.html

But actually, this svg isn't in the Go repo, so I don't think this is the right place. I guess you could announce it on the golang-nuts@ mailing list?
