### ISSUE TITLE
vendor/golang_org: update /x sub-repo packages

### ISSUE THREAD

**Issue by aead** [golang/go#19967]
Some work was and will be done to make the /x sub-repos better, faster, cleaner, ...
This work should be included - so the vendor/golang_org packages should be updated within the Go1.9 development cycle / before the Go1.9 release. This could be done just before freeze.

Maybe the imagination of forgetting this is ridiculous but there are already "updated" as well as "not-updated" packages in /vendor/golang_org.

**Comment by bradfitz** [comment]
> This could be done just before freeze.

Early and often might be better. It might catch bugs earlier.

**Comment by bradfitz** [comment]
I think we've done enough for Go 1.9. At this point it's on an as-needed basis for fixing open bugs.
