### ISSUE TITLE
cmd/compile: confusing error message "shift of type float64"

### ISSUE THREAD

**Issue by josharian** [golang/go#19963]
https://play.golang.org/p/UntLLbfSoY

```go
package main

func main() {
	var b uint8
	var _ float64 = 1.5 * (1 << b)
}
```

generates the error message

`main.go:5: invalid operation: 1 << b (shift of type float64)`

But there's no shift of type float64. There's a shift of type uint8. The problem is that the result of that shift needs to be converted into a float64 before multiplying.

**Comment by josharian** [comment]
Should this code be valid?

```go
	var b uint8
	_ = float64(1 << b)
```

Currently go/types and cmd/compile both reject it.

**Comment by ALTree** [comment]
> If the left operand of a non-constant shift expression is an untyped constant, it is first converted to the type it would assume if the shift expression were replaced by its left operand alone

So i believe the error "shift of type float64" is correct because what the spec says we do is

```
float64(float64(1) << b)
```

so it's true that you are shifting a float.

**Comment by josharian** [comment]
Yeah. I guess you're right. It'd be nice to make the error message a bit clearer--it happened to me in the context of a much more complex expression, but I don't really see how to. Closing for now; thanks, @ALTree .

**Comment by griesemer** [comment]
Yes, this is correct: The type of the `1` in `(1 << b)` is the type if would have if the shift wasn't there. Would be nice to have a clearer explanation in the error but I think that will require some work. Let's leave this for the "ponies" list once we have a compiler that's all neat and clean.

**Comment by josharian** [comment]
A neat and clean compiler should show up somewhere around Go 1.x. Where I am assuming that this release will be called 1.9, the following one 1.a, then 1.b, and so on. :P
