### ISSUE TITLE
x/build: clang missing on some builders

### ISSUE THREAD

**Issue by josharian** [golang/go#19960]
The linux-386-clang and linux-amd64-clang builders just started failing, with the message:

```
go tool dist: cannot invoke C compiler "/usr/bin/clang": fork/exec /usr/bin/clang: no such file or directory
```

Doesn't appear related to the commits it is testing. Maybe a recent config change?

cc @bradfitz @adams-sarah

**Comment by bradfitz** [comment]
Jess, looks like your new clang Docker image is missing clang. Maybe its binary name is something else and it needs an env update in builders.go?

**Comment by bradfitz** [comment]
I bashed into the container and did the apt-get install from the Dockerfile:

```
# apt-get install clang-3.9
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-clang-3.9' for regex 'clang-3.9'
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
```

**Comment by jessfraz** [comment]
wowwww

**Comment by jessfraz** [comment]
opened https://go-review.googlesource.com/c/40576/
