### ISSUE TITLE
gob package fails to work correctly if non-exported fields when storing to a file

### ISSUE THREAD

**Issue by willauld** [golang/go#19970]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.8 

### What operating system and processor architecture are you using (`go env`)?

see the playground env.

### What did you do?

I was trying to save data to a file using the Gob package. However, I was getting a EOF and no data returned. I was having a very hard time seeing what the issue was and why it was not working. Once, I understood that it the fields in the array of j might have to be exported I try that and found a second problem; both of which can be reproduced with the code in the playground. Lines 10-12 of the playground code (url below) are the only differences between three cases. Case one (1), uncomment line 10 with 11 and 12 commented out. In this case I get the EOF returned for the load operation. I believe this should return the strings from the User struct along with an empty array rather than the EOF. For case two (2), exporting only one of j's fields results in both of them being transferred. I believe that only the exported field should actually be transferred base on the docs. Case three seems to be correct. 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/KMPdYXniat

### What did you expect to see?

Case 1: &{Donald DuckPass []}
Case 2: &{Donald DuckPass [{ 2} { 1}]}
Case 3: &{Donald DuckPass [{1 2} {2 1}]}

### What did you see instead?

Case 1: Check Error:  EOF
                       &{  []}
Case 2: &{Donald DuckPass [{0 2} {0 1}]}
Case 3: &{Donald DuckPass [{1 2} {2 1}]}

**Comment by bradfitz** [comment]
The docs say:

"Structs encode and decode only exported fields."

I think this is working as intended. Let me know if I don't understand.

**Comment by willauld** [comment]
This may represent a dup of 19969 but they do have different behavior for case 1. Here we complete the encoding without an error returned while in 19969 an error is returned for virtually the same input data.

**Comment by bradfitz** [comment]
You're ignoring the error return value to `encoder.Encode(object)` (as well as the `os.Create`-created `*os.File.Close` call)

**Comment by willauld** [comment]
OK, I reworked the example: https://play.golang.org/p/SvdAQPJblm to check the Encode() err and cleaned up the Close() but am still ignoring its error return. Given the error response from Encode(), I am happy to close this issue. Thanks
