### ISSUE TITLE
cmd/objdump: amd64 popcnt disassembled as rep popcnt

### ISSUE THREAD

**Issue by rasky** [golang/go#19986]
```
	return uint(bits.OnesCount16(val))
  0x4286bda		0fb635f27c3800		MOVZX 0x387cf2(IP), SI
  0x4286be1		4084f6			TESTL SI, SI
  0x4286be4		0f84f8000000		JE 0x4286ce2
  0x4286bea		0fb7f1			MOVZX CX, SI
  0x4286bed		f30fb8f6		REP POPCNT SI, SI
```

**Comment by randall77** [comment]
I think this is intentional. Those opcodes really are encoded with a REP prefix.
A lot of the SSE instructions are in the same boat (e.g. SQRTSS).
We even have tests that make sure the "REP" is there.

@rsc, any reason why we do this?

**Comment by rsc** [comment]
If the REP is implied by the opcode, then it shouldn't be printed. Tests requiring it are likely just buggy tests.

**Comment by randall77** [comment]
Dup of #17410.  It's been fixed in the x repo, it just needs to be pulled into master.  I'm going to leave this issue open until that happens.
