### ISSUE TITLE
x/mobile/gl: invalid constant

### ISSUE THREAD

**Issue by donomii** [golang/go#19997]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jprice/Desktop/GoProgs/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/70/k2sr6gz55pl37sh53_qmldn8w28b70/T/go-build054519315=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

Wrote a program using golang.org/x/mobile/gl

go build -tags gldebug .

### What did you expect to see?

A compiled program

### What did you see instead?

# golang.org/x/mobile/gl
../../../golang.org/x/mobile/gl/gldebug.go:1126: constant 18446744073709551615 overflows Enum

**Comment by egonelbre** [comment]
It looks like this might have been fixed by https://go-review.googlesource.com/53531

**Comment by mvdan** [comment]
@egonelbre nice catch - that also makes this issue a dup of #17075. Closing.
