### ISSUE TITLE
x/crypto/ssh/knownhosts: doesn't match any host when known_hosts has more than one host

### ISSUE THREAD

**Issue by mcuadros** [golang/go#19994]
### What version of Go are you using (`go version`)?
`go version go1.8 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mcuadros/workspace/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build177755887=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
[`knownhosts.Host` ](https://godoc.org/golang.org/x/crypto/ssh/knownhosts#New) with a known_hosts generated by the standard openssh

### What did you expect to see?
Validate a known host.

### What did you see instead?
Doesn't validate and reports as matched the last line.

**Comment by mcuadros** [comment]
https://go-review.googlesource.com/c/40911/

**Comment by odeke-em** [comment]
@bradfitz check this out: isn't this weird that by just mentioning this issue in a repo that we don't own, the issue gets closed? Should we be filing a bug with Github, otherwise anyone can close Go/other project issues just by cross reference, which might be the unintended case for people that make Go repo mirrors on Github and commit here.

**Comment by mcuadros** [comment]
@odeke-em yep, this is weird, I guess that this happened because I am the author of the issue and also the owner of the organization where the PR was merged.

**Comment by artyom** [comment]
I believe this is fixed with golang/crypto@efac7f277b17c19894091e358c6130cb6bd51117

**Comment by odeke-em** [comment]
@mcuadros could you try with the latest crypto code, to confirm that the CL referred to by @artyom https://go-review.googlesource.com/c/40937 fixes the problem?

The code in the fixing CL looks quite identical to yours @mcuadros.

**Comment by mcuadros** [comment]
yup is fixed, thanks
