### ISSUE TITLE
cmd/vet all variants in switch-case

### ISSUE THREAD

**Issue by rekby** [golang/go#19990]
Add check for switch statement check all branches and have default.

for example:

	package main
	
	import (
		"fmt"
	)
	
	type T int
	
	const (
		A T = iota
		B
		C
		D
	)
	
	func main() {
		v := A
	
		switch v {
		case A:
			fmt.Println("A")
		case B:
			fmt.Println("B")
		case C:
			fmt.Println("C")
	    }
    }

Will be excellent if vet will warn about switch:
1. Doesn't check D value
2. Have no default.

**Comment by ALTree** [comment]
This is a dup of #5469 and it looks like it was decided not to do that (see discussion in that issue).

Closing this.
