### ISSUE TITLE
cmd/go: buildmode ignored when using -o

### ISSUE THREAD

**Issue by multun** [golang/go#20017]
### What version of Go are you using (`go version`)?
`go version go1.8.1`

### What operating system and processor architecture are you using (`go env`)?
`adm64 Archlinux`

### What did you do?
hello.go:
```
package notmain

import "fmt"

func main() {
	fmt.Println("42")
}
```
```
$ go build -buildmode=exe -o hello
$ file hello
hello: current ar archive
```

### What did you expect to see?
An error, as the documentation states:
```
	-buildmode=exe
		Build the listed main packages and everything they import into
		executables. Packages not named main are ignored.
```
However, I feel like the buildmode pkgFilter was ignored because of -o being used:
https://github.com/golang/go/blob/58908114a860908bdff775d7d4a0223554896dcb/src/cmd/go/internal/work/build.go#L432

### What did you see instead?
An archive named `hello` was produced.

**Comment by multun** [comment]
Does it make sense not to reuse [the package list](https://github.com/golang/go/blob/58908114a860908bdff775d7d4a0223554896dcb/src/cmd/go/internal/work/build.go#L449) that was [loaded here](https://github.com/golang/go/blob/58908114a860908bdff775d7d4a0223554896dcb/src/cmd/go/internal/work/build.go#L400) ?

**Comment by multun** [comment]
@odeke-em @rsc @ianlancetaylor so, what do you think ?

**Comment by ianlancetaylor** [comment]
I think it's a bug but it doesn't seem like a very important one.  @multun I don't know offhand if that is the right place to fix; if you can write a patch with a test case we can review it for 1.10.  Thanks.
