### ISSUE TITLE
Spec does not fully define map/struct assignment

### ISSUE THREAD

**Issue by alercah** [golang/go#20016]
After looking carefully through the spec, myself and several others in #go-nuts were unable to find detailed explanation of the behaviour of map and struct assignment.

In particular, it's well-understood that in the following example, `m[1] == 1`

    m := make(map[int]int)
    n := 1
    n[1] = 1

Likewise that in the following example, `s.i == 0`

    s := struct{ i int }
    t := s
    t.i = 1

But nowhere in the spec does there appear to be language clearly distinguishing the behaviours here.

**Comment by randall77** [comment]
Dup of #5083
