### ISSUE TITLE
cmd/go: go test -timeout flag behavior doesn't match test binary -timeout flag behavior

### ISSUE THREAD

**Issue by josharian** [golang/go#20025]
Running a test binary with -h prints:

```
  -test.timeout d
    	fail test binary execution after duration d (0 means unlimited)
```

But that doesn't seem to work:

```go
package p

import (
	"testing"
	"time"
)

func BenchmarkSlow(b *testing.B) {
	for i := 0; i < b.N; i++ {
		time.Sleep(15 * time.Minute)
	}
}
```

Running this with `go test -bench=. -timeout=0 x_test.go` results (eventually) in `*** Test killed with quit: ran too long (10m0s).`

**Comment by josharian** [comment]
Ick. Looks like this is implemented correctly in package testing, but that this timeout comes from 'go test', so to disable timeouts you need to use 'go test -c' and then execute. It'd be much nicer if test binaries and cmd/go agreed on behavior, and there was a way to disable timeouts directly via 'go test'.

I guess a workaround is 'go test -timeout=1000h'.

**Comment by ianlancetaylor** [comment]
It's really just a bug in cmd/go.  Explicitly passing `-test.timeout=0` should disable `testKillTimeout` in cmd/go/internal/test/test.go.

In fact this is #18490.

**Comment by ianlancetaylor** [comment]
And I have to respect the fact that you did a thumbs up on my suggestion in #18490 which would also fix this issue....

**Comment by josharian** [comment]
Hahaha. My mental github issue index clearly failed me. Thanks, Ian. :)
