### ISSUE TITLE
cmd/internal/obj: stop using as a dumping ground for shared code

### ISSUE THREAD

**Issue by josharian** [golang/go#20026]
cmd/internal/obj is already imported by the compiler, linker, assemblers, etc., so it is a convenient place to put shared helpers, such as Bool2int, SortSlice, and PathToPrefix, even though they don't really belong there. It might be time to do a bit of cleanup.

cc @tzneal @mdempsky

**Comment by mdempsky** [comment]
I'm going to extract the common constants and helper functions into a new objabi package.
