### ISSUE TITLE
x/crypto/ssh: add hash support for known_hosts

### ISSUE THREAD

**Issue by jdoklovic** [golang/go#20034]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux / amd64

### What did you do?
Tried to use hashed entries in known_hosts

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
An ssh connection

### What did you see instead?
an error saying: "knownhosts: hashed hostnames not implemented"

**Comment by jdoklovic** [comment]
I've implemented this, see: https://go-review.googlesource.com/40984

**Comment by hanwen** [comment]
fixed by https://go.googlesource.com/crypto/+/64205593f25ab0ca0ac8f40914760074bf246f65
