### ISSUE TITLE
cmd/go: reject use of PIE with -race

### ISSUE THREAD

**Issue by aaronjwood** [golang/go#20038]
### What version of Go are you using (`go version`)?
1.7.4

### What operating system and processor architecture are you using (`go env`)?
OS: CoreOS 1010.6.0 (Linux 4.5.7)
Arch: x86_64

### What did you do?
Built a binary with `-race` in our CI environment (also x86_64 Linux but not CoreOS), ran it on CoreOS, immediately got a segfault.

### What did you expect to see?
No segfault :) Building this same binary without the race detector and running it on CoreOS works just fine.

### What did you see instead?
```
==45515==ERROR: ThreadSanitizer failed to allocate 0x2790000 (41484288) bytes at address 1775919824880 (errno: 12)
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x55d645f23ea5]

goroutine 1 [running, locked to thread]:
runtime.throw(0x0, 0x7fff2385c478)
/usr/local/go/src/runtime/panic.go:566 +0x97 fp=0x7fff2385c408 sp=0x7fff2385c3e8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

One other important detail: this binary was run under Mesos 1.0.3. The only resource restrictions in place (applied via cgroups) were 4 GB of memory and 4 (relative) CPU shares.

**Comment by davecheney** [comment]
My gut says quarduple the amount of memory assigned to that container.

**Comment by dvyukov** [comment]
How much memory does the program use without race detector?

**Comment by aaronjwood** [comment]
@dvyukov I was doing some load testing (nothing too crazy) the other day and I found that it never reached 15 MB.

**Comment by aaronjwood** [comment]
@davecheney does it sound strange that the race detector would require 8-16 GB of memory for a program that takes 15 or maybe 20 MB at the very most?

**Comment by bradfitz** [comment]
@aaronjwood, is your container limiting actual memory usage or also allocating virtual memory addresses?

**Comment by aaronjwood** [comment]
@bradfitz I don't believe so:
https://github.com/apache/mesos/blob/master/src/slave/containerizer/mesos/isolators/cgroups/subsystems/memory.cpp#L188
https://github.com/apache/mesos/blob/master/src/slave/containerizer/mesos/isolators/cgroups/subsystems/memory.cpp#L203

**Comment by dvyukov** [comment]
Please provide repro instructions.

**Comment by aaronjwood** [comment]
@dvyukov actually I have some updates on this. I found that it's not the race detector that's causing the issue, it's when we build the binary as a PIE executable AND use the race detector. Before when we were building we passed `-buildmode=pie -race`. I had taken both of those out when testing with and without the race detector so I wrongly assumed it was the race detector. This seems to be a combination of a PIE executable with the race detector. Building with `-buildmode=pie` by itself works just fine.

**Comment by dvyukov** [comment]
Uh, that's not supported. Race runtime assumes that executable is loaded at around 0 address. I guess we need to prohibit this combination for now.

**Comment by aaronjwood** [comment]
I see, I didn't realize that. If that's the case then I guess we can simply close this. Maybe some docs or a change like you suggested would help others that may run into this in the future.

**Comment by bradfitz** [comment]
Rejecting that combination in cmd/go SGTM.

**Comment by dajoo75** [comment]
I uploaded a fix for review: https://go-review.googlesource.com/c/41335/

**Comment by ALTree** [comment]
Is the gopherbot sick? It's not crossreferencing CLs, I uploaded a patch hours ago but it didn't post on the issue.

**Comment by dajoo75** [comment]
Maybe on sick leave? ;-). Anyway, please ignore my fix if there was already one in the works.

**Comment by bradfitz** [comment]
@ALTree, two problems with gopherbot. One was already known (not yet productionized properly) and the other is new with a fix+test coming.
