### ISSUE TITLE
x/crypto/acme/autocert: expired cached cert never renewed

### ISSUE THREAD

**Issue by x1ddos** [golang/go#20035]
From elsewhere:

> the problem that restarting a server with an expired cached cert results in the cert never being renewed.
> Looking through the code I see the following call graph:
>
>     m.GetCertificate -> m.cert -> m.cacheGet -> validCert
>
>The error from validCert is constructed if the cert is already expired: errors.New("acme/autocert: expired certificate").
> That error gets passed up to GetCertificate which just errors out if the resulting error is not ErrCacheMiss.
> The result is that a new cert is never created since renewal only works if a valid cert was fetched originally.

Creating this bug mostly for myself to track and fix it.

**Comment by robpike** [comment]
This is related to the Upspin bug:

https://github.com/upspin/upspin/issues/367
