### ISSUE TITLE
encoding/json: float output change breaks BigQuery API

### ISSUE THREAD

**Issue by jba** [golang/go#20033]
This isn't a bug in Go, but it does cause breakage elsewhere. I'm not sure what the fix should be (if any).

### What version of Go are you using (`go version`)?

1.7.5, 1.8

### What operating system and processor architecture are you using (`go env`)?
Linux amd64

### What did you do?
Ran this program:
```go
package main

import (
    "encoding/json"
    "fmt"
    "log"
)

func main() {
    b, err := json.Marshal(5e20)
    if err != nil {
        log.Fatal(err)
    }
    fmt.Println(string(b))
}
```
In 1.7.5, the output is `5e+20`. 

In 1.8, the output is `500000000000000000000`.

Both are legal JSON, but the latter breaks BigQuery: 
```
InsertAll googleapi: Error 400: Invalid JSON payload received. Unable to parse number.
[{"json":{"MyFloat":50000000000000000000
                    ^, badRequest
```

**Comment by bradfitz** [comment]
Seems like a BigQuery bug. That is how Chrome formats it too. We explicitly switched formatting so we'd behave like Node.js & Chrome etc.

In Chrome:
<img width="246" alt="screen shot 2017-04-18 at 5 17 49 pm" src="https://cloud.githubusercontent.com/assets/2621/25158145/f8891740-245a-11e7-98c7-b48d6322df5c.png">
