### ISSUE TITLE
time library does not have a constant defined for golang time string

### ISSUE THREAD

**Issue by jwoomitek** [golang/go#20045]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
Use time.Parse()
Time string is in the default go format. There is no constant defined in the time library for go's native format.

2006-01-02 15:04:05.999999999 -0700 MST

```
const longFormat = "2006-01-02 15:04:05.999999999 -0700 MST"
createTimeStamp, err := time.Parse(longFormat, timeStringToParse)
```

### What did you expect to see?
-A constant defined like one of the RFC standards or UnixDate.
-A way to call time.Parse() without passing in a format so that it defaults to the default format.

### What did you see instead?
I have to define the format like the code snippet above. I want to know if there will be support for this. I would like to avoid defining my own custom wrapper library.

**Comment by bradfitz** [comment]
Dup of #6587 (and #9596), both of which were closed with the decision that we're not going to add this.

@robpike said previously:

> The default format string is a clumsy one whose sole merit is that it represents all the
pieces of the value. Few uses need that property alone. A better approach is to choose a
format that meets your needs (say, RFC3999Nano) and use that explicitly. The only reason
to publish this as a constant is to parse a default value again. If you're parsing, it's
better to be clear about what you're printing too.

Closing.
