### ISSUE TITLE
encoding/base32: The decoder returned by NewDecoder sometimes drops errors

### ISSUE THREAD

**Issue by akalin-keybase** [golang/go#20044]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8.1

### What operating system and processor architecture are you using (`go env`)?

darwin amd64

### What did you do?

When passing an `io.Reader` to `base32.NewDecoder`, if that reader emits valid base32 input and an error, I would expect that error to be propagated. Instead, it is dropped.

Example: https://play.golang.org/p/Ex-8nNLiZk

In this case, it's because `io.ReadAtLeast` drops errors if the minimum is reached (another surprising thing), but it looks like other encoders (ascii85, base64) exhibit similar behavior, perhaps on purpose. If it is on purpose, it should be documented somewhere.

**Comment by bradfitz** [comment]
Multiple potential issues: use of io.ReadAtLeast drops errors if it reads enough, and base32.go stores into d.err from ReadAtLeast but overwrites it without consulting it d.nbuf >= 8.

**Comment by markdryan** [comment]
@bradfitz Any objections if I take a look at this?

**Comment by bradfitz** [comment]
@markdryan, all yours.

**Comment by markdryan** [comment]
I've created a patch that addresses this issue:

https://go-review.googlesource.com/c/42094/

The patch fixes the error propagation issues and adds some new unit tests.

**Comment by akalin-keybase** [comment]
Looks like that patch needs some reviewers...

**Comment by akalin-keybase** [comment]
ascii85, base64 have similar bugs -- should I file new bugs for those?

**Comment by bradfitz** [comment]
We shouldn't reuse this bug.
