### ISSUE TITLE
net/http: ugly docs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20043]
https://golang.org/pkg/net/http/#Client in HTML looks ugly.

**Comment by cespare** [comment]
Is this about the way "bullet list" / pre section works specifically, or something else?

**Comment by bradfitz** [comment]
Yeah, whoops, hit submit a bit too early.

Currently it looks like:

<img width="670" alt="screen shot 2017-04-19 at 1 53 01 pm" src="https://cloud.githubusercontent.com/assets/2621/25201714/90eb95ba-2507-11e7-8a87-8a3a55258d65.png">

**Comment by dsnet** [comment]
Sorry for the ugly comments 😐. My fault

**Comment by bradfitz** [comment]
@dsnet, I didn't even know who wrote it because I hadn't even read the text itself yet. :) I assumed it was my fault (or really godoc's fault).

**Comment by dlespiau** [comment]
https://go-review.googlesource.com/c/41212/

One can try to use unicode bullets. Not a super great render, but probably better.

![screenshot-issue-20043](https://cloud.githubusercontent.com/assets/7986/25229936/379fa3d4-25ca-11e7-854d-32c54564c4ba.png)
