### ISSUE TITLE
math/big: AKS Test for Int.ProbablyPrime

### ISSUE THREAD

**Issue by pjebs** [golang/go#20052]
There seems to be a relatively new test that is 100% correct:

It's called the AKS Test: https://www.cse.iitk.ac.in/users/manindra/algebra/primality_v6.pdf

More Info: https://www.youtube.com/watch?v=HvMSRWTE2mI

**Comment by mvdan** [comment]
The current test has been changed recently, see https://github.com/golang/go/commit/37d078ede386b5d0dff0bb1f3ea77e47122730d0.

Would switching to this test make the method noticeably slower?

cc @rsc @griesemer

**Comment by dgryski** [comment]
It appears that AKS is substantially slower in practice than BPSW: https://cs.stackexchange.com/questions/23260/when-is-the-aks-primality-test-actually-faster-than-other-tests

**Comment by mvdan** [comment]
I wonder if 100% correctness is useful for a method that is called `ProbablyPrime`, especially if it comes at such high performance cost.

**Comment by pjebs** [comment]
There is a simplified version of the test highlighted at 2:10 in the youtube video. In the simplified version, it is faster at the expense of some accuracy (I think).

**Comment by pjebs** [comment]
According to this: http://probableprime.org/images/primality-times.png, AKS test is crap in practice.

**Comment by ALTree** [comment]
The algorithm is only interesting from a theoretical point of view (deterministic primality test in polynomial time was a breakthrough); I don't think anyone uses AKS in practise.

Closing this.

**Comment by rsc** [comment]
For me the main reason to add BPSW was that there were easy-to-find inputs that ProbablyPrime was demonstrably (and consistently) wrong about. For example, big.NewInt(443*1327).ProbablyPrime(1) == true before that change.

If you can find inputs that the current test gets wrong but that AKS gets right, I'd be happy to look into changing the implementation. And lots of others would be interested too: there are no known counterexamples to BPSW.

**Comment by danaj** [comment]
The Youtube video is very misleading in a number of ways.  What it describes is a preliminary lemma of AKS that is obviously horrendously slow.  Worse than the most naive trial division by every integer up to n-1.  The real AKS is certainly better than that, but it is still much slower than other known methods, even after improvements by Lenstra, Pomerance, Voloch, Bernstein, et al.

BPSW if implemented correctly has *no* counterexamples under 2^64.  No probably about it.  You can extend this using deterministic Miller-Rabin to something like 80 bits.  So we'd definitely not care about this until that point.

If you really want something better, I'd recommend one of

- Add additional probable prime tests for numbers larger than the deterministic threshold.  E.g. Frobenius and/or random-base Miller-Rabin tests.
- APR-CL
- ECPP

The latter two tests are also 100% correct.  APR-CL has a smaller exponent than the current best deterministic AKS for any number computable within the next 100 years.
