### ISSUE TITLE
os, syscall: Seek on pipe on windows doesn't return ESPIPE 

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#20066]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

According to http://pubs.opengroup.org/onlinepubs/009695399/functions/lseek.html:
lseek returns ESPIPE on pipe.

However, current implementation use EPIPE instead.
https://github.com/golang/go/blob/eaa198f3d16e76a58711eb0e8cc9d57d1fdcf7fd/src/syscall/syscall_windows.go#L350-L352

### What did you expect to see?
ESPIPE

### What did you see instead?
EPIPE

**Comment by ianlancetaylor** [comment]
It's hard to get too excited about this, since we made up EPIPE anyhow for Windows.  But if you want to send a patch I suppose it's OK with me.
