### ISSUE TITLE
compress/gzip: Header.OS defaults to FAT

### ISSUE THREAD

**Issue by kortschak** [golang/go#20074]
### What version of Go are you using (`go version`)?
go1.8.1

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

This likely breaks the Go1 promise, so this is a query/Go2 issue.

RFC1952 specifies that the OS field of the GZIP header is 0xff for unknown OS and 0x0 for FAT file systems. This leads to the unfortunate situation where probably the vast majority of GZIP files written by compress/gzip are lying about their OS (FWIW some readers actually care about this).

**Comment by kortschak** [comment]
It seems to me that this is arguably a bug and it is also not clear that a change to `NewWriterLevel` that set `z.Header.OS = 0xff` would not break valid programs (or at least it would be nice to see evidence for that here).

**Comment by dsnet** [comment]
We could probably just have NewWriter and NewWriterLevel set `z.Header.OS = 0xff` before returning the `gzip.Writer` object without breaking compatibility. Any user that cared about actually setting the `Header.OS` most likely did it after the `Writer` object was returned by `NewWriterX`.

**Comment by kortschak** [comment]
I'm happy to send a CL for that (for go1.10 presumably).

**Comment by kortschak** [comment]
Well, [this](https://github.com/golang/go/commit/cc9ed447#diff-d8064b1421cf4a5a677d49ab80afe086R67) is embarrassing.

**Comment by dsnet** [comment]
Ha. I didn't see that either :P
