### ISSUE TITLE
x/sys/windows: Some VirtualX syscalls missing

### ISSUE THREAD

**Issue by awnumar** [golang/go#20086]
### What did you expect to see?

On https://godoc.org/golang.org/x/sys/windows I expected to see the `VirtualAlloc` and `VirtualFree` syscalls, and also the `VirtualProtect` one.

### What did you see instead?

Only the `VirtualLock` and its unlocking counterpart.

These are quite important from a security perspective, are there any plans to have them added?

**Comment by alexbrainman** [comment]
@libeclipse would something like https://github.com/alexbrainman/winapi/commit/c959b37223f62e4581a4a58da7816cf962aeb906 do?

Alex

**Comment by libeclipse** [comment]
@alexbrainman That's a cool little library you have there. Of course it would be nice to have the calls in /x/ eventually, but for now that will do perfectly.

**Comment by mxplusb** [comment]
@alexbrainman are you going to make those changes into `x/sys/windows`?

**Comment by alexbrainman** [comment]
> @alexbrainman are you going to make those changes into x/sys/windows?

I was not planing to.
There is too much code in x/sys/windows as is. I do not want to add even more unless it is useful to many people.
Feel free to copy the code anywhere you like.

Alex

**Comment by mxplusb** [comment]
Shouldn't `x/sys/windows`, in theory, contain all the syscalls for Windows, even if they are only marginally used?

**Comment by alexbrainman** [comment]
> Shouldn't x/sys/windows, in theory, contain all the syscalls for Windows

No. I think it is impossible to have ALL Windows APIs in x/sys/windows. As you can see (https://github.com/golang/go/issues/20086#issuecomment-296499022), it is very easy do add whatever APIs you desire to your own package.

Alex
