### ISSUE TITLE
Dynamic type assertion for interface

### ISSUE THREAD

**Issue by RajeshKumar1990** [golang/go#20093]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.4 windows/amd64
### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Please do note that the structs in this example is a sample.My struct is complex than this.
https://play.golang.org/p/_t7gx3javb
Here I have a function where i will be using lot of times.Each time i will be passing object of different struct  types.So i use the parameter arguments as  interface{}.
So to solve the  error  i need to do type assertion.But here the interface can be of any struct type.So i am looking if there is any possible way to do the dynamic type assertion based on the reflect.TypeOf value.
### What did you expect to see?
Copy of the struct

### What did you see instead?
Error

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by RajeshKumar1990** [comment]
oh sorry and thanks for your info....New to golang....I will post it in the golang wiki.

**Comment by bradfitz** [comment]
No, the wiki is not the place to ask questions. See the link above.
