### ISSUE TITLE
cmd/objdump: can not disassemble ARM DIVUHW / DIVHW

### ISSUE THREAD

**Issue by benshi001** [golang/go#20096]
Wtih a simple test file arm.s
TEXT	foo(SB), 4, $0
	DIVHW	R0, R1, R2
	DIVUHW	R0, R1, R2
	DIVHW	R0, R1
	DIVUHW	R0, R1
	ADD	$ 0xfff9, R0
	END

Here are what I do and the results,
pi@raspberrypi:~ $ cat arm.s
TEXT	foo(SB), 4, $0
	DIVHW	R0, R1, R2
	DIVUHW	R0, R1, R2
	DIVHW	R0, R1
	DIVUHW	R0, R1
	ADD	$ 0xfff9, R0
	END
pi@raspberrypi:~ $ GOROOT= ~ /go PATH=$GOROOT/bin:$PATH  go tool  asm arm.s
pi@raspberrypi:~ $ GOROOT= ~ /go PATH=$GOROOT/bin:$PATH go tool objdump arm.o
TEXT foo(SB) gofile../home/pi/arm.s
  arm.s:4		0x85			e712f011		?			
  arm.s:5		0x89			e732f011		?			
  arm.s:7		0x8d			e711f011		?			
  arm.s:8		0x91			e731f011		?			
  arm.s:10		0x95			e30fbff9		MOVW $65529, R11	
  arm.s:10		0x99			e080000b		ADD R11, R0, R0		

The DIVHW/DIVUHW are not disassembled .

**Comment by cherrymui** [comment]
The disassembler comes from `x/arch` subrepo (https://go.googlesource.com/arch), which contains a table generated by parsing the PDF of the hardware manual. It looks like these instructions are not in the table.

@benshi001 would you like to update the table with a newer version of the manual that includes these instructions? (I don't have one.)

**Comment by benshi001** [comment]
OK. I will do it later. Thank you.

**Comment by benshi001** [comment]
Questions,

1. https://github.com/golang/go/tree/master/src/cmd/vendor/golang.org/x/arch/arm/armasm is much older than https://github.com/golang/arch/tree/master/, which one should I follow?
2. Which tool is used to generate arm.csv? Or I have to edit it by hand?
3. Any more instructions ?

**Comment by benshi001** [comment]
[arm.csv.zip](https://github.com/golang/go/files/960992/arm.csv.zip)

1. I checked the newest arm manual against the arm.csv, UDIV/SDIV/UDF are new added, and others are not used by go. (Such as VCLZ is SIMD, CHKA is ThumbEE)

2. I added UDIV/SDIV/UDF to the attached arm.csv and got tables.go by "go run ../armmap/map.go -fmt=decoder ../arm.csv >_tables.go && gofmt _tables.go >tables.go && rm _tables.go".

3. I committed https://go-review.googlesource.com/c/41890/, now DIVHW and DIVUHW can be disassembled correctly.

 // DIVHW R0, R1, R2: R1 / R0 -> R2
	DIVHW	R0, R1, R2           // 11f012e7
	DIVUHW	R0, R1, R2           // 11f032e7
// DIVHW R0, R1: R1 / R0 -> R1
	DIVHW	R0, R1               // 11f011e7
	DIVUHW	R0, R1               // 11f031e7

  arm.s:8		0x8f			e712f011		SDIV R0, R1, R2		
  arm.s:9		0x93			e732f011		UDIV R0, R1, R2		
  arm.s:11		0x97			e711f011		SDIV R0, R1, R1		
  arm.s:12		0x9b			e731f011		UDIV R0, R1, R1

**Comment by benshi001** [comment]
The UDF is not supported by the assembler, so it is not tested.

**Comment by benshi001** [comment]
A bug is found,

"MULS R1, R2, R3, R4" is dissambled to "MLS R3, R1, R2, R4", which should be "MLS R1, R2, R3, R4"

Patch set 3 of CL https://go-review.googlesource.com/#/c/41891/ fixes it.

**Comment by benshi001** [comment]
https://go-review.googlesource.com/#/c/41891/ fixes the DIV/DIVU issue.
https://go-review.googlesource.com/#/c/42171/ fixes the MLA issue.

**Comment by benshi001** [comment]
QADD is also not decoded correctly.

0xe1086055 should be decoded to "QADD R6, R8, R5" in GNU syntax, but actually "QADD R6, R5, R8".

**Comment by benshi001** [comment]
There same error of wrong register list also exists in QDADD/QSUB

**Comment by benshi001** [comment]
fixed in https://go-review.googlesource.com/c/41891/
