### ISSUE TITLE
Unknown symbols after concatenating regular expression results

### ISSUE THREAD

**Issue by Aukstkalnis** [golang/go#20107]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I wrote simple version check program that reads data from serial port, searches for version with regular expression, concatenate regular expression groups and check if it is equal with given version in json file. If equal, then PASS is printed, else - failed is printed.
I used win 7 x64 to cross compile for x86.

#### What did you expect to see?
That my program finds good version.

#### What did you see instead?
For my colleagues that uses x86 windows 7 version sometimes found version contains unknown symbols like 01.01.20.Rev.05**I[AE** (This is not the real symbols that was seen but something like that). The same symbols where seen on few computers but only with win7 x86. I can't reproduce this program for more info. I attached source.
[Reflasher.7z.txt](https://github.com/golang/go/files/954011/Reflasher.7z.txt)

#### System details

go version go1.8.1 windows/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="D:/gopath"
GORACE=""
GOROOT="c:\go"
GOTOOLDIR="c:\go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\AUKSTK~1.DE\AppData\Local\Temp\go-build617008819=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.1 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.8.1 X:framepointer
gdb --version: GNU gdb (GDB) 7.6.1
```

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
