### ISSUE TITLE
Multipart part reader read operation often returns EOF WITH n != 0

### ISSUE THREAD

**Issue by amits1995** [golang/go#20101]
### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
windows/amd64 i7 920@3.7GHZ and i7 2600  
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Amit\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### What did you do?
I wrote a file upload server whose handle func runs some checks on the request and then  
wraps the upload request with a struct that contains some metadata and a stream to the file's data  
then it sends the data to another component and waits for it to finish reading the whole file.  
  
here's a snippet of my program - with a test file that sometimes fails.  
[link to github repo](https://github.com/amits1995/go-bugreport)

### What did you expect to see?
I used multipart reader to streamingly read the file from the network while proccessing it.  
I expect the read to stop with io.EOF error (or a network error of some sort).

### What did you see instead?
sometimes (when CPU is high) I get both io.EOF and n!=0 from the last read.  
for example - there are 2 bytes left to read and I emit ```read, err := r.Read(buffer)``` and I get:  
```n!=0 && err == io.EOF```

**Comment by bradfitz** [comment]
That's valid io.Reader behavior. See:

https://golang.org/pkg/io/#Reader

> An instance of this general case is that a Reader returning a non-zero number of bytes at the end of the input stream may return either err == EOF or err == nil. The next Read should return 0, EOF.
