### ISSUE TITLE
x/build: make misc-compile-all trybot type check tests too

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20119]
The "misc-compile-*" Trybot builders try to at least compile & type check every GOOS/GOARCH pair, even when we don't have sufficient hardware to run the tests.

But they apparently don't compile or type check tests.

https://go-review.googlesource.com/c/41691/ broke Plan 9 without any warnings.

Fix that.

/cc @mvdan @kevinburke @adams-sarah @cybrcodr

**Comment by bradfitz** [comment]
Notes:

The misc builders are defined here:
https://github.com/golang/build/blob/60446e188e72edd4658dc6d9f6e3c1b9f5227014/dashboard/builders.go#L809

They use buildall.bash to run: (ignore the typo in docs that says `buildall.sh`)
https://github.com/golang/build/blob/60446e188e72edd4658dc6d9f6e3c1b9f5227014/dashboard/builders.go#L578
https://github.com/golang/go/blob/master/src/buildall.bash

All that basically does (from a fast linux-amd64 kubernetes container) is:

```
$ GOOS=something GOARCH=something build -a std cmd
```

We'd also need a way to also make buildall.bash run "go test -c $PKG" for each $PKG. That is #15513.

**Comment by paranoiacblack** [comment]
Yeah, I tried just modifying buildall.bash to run `$GOPATH/bin/go tool dist test --compile-only --rebuild` to avoid having to particularly solve #15513. However, it seems that `--compile-only` does not seem to actually compile the tests? I tried reintroducing the same error you removed in https://golang.org/cl/41752 but `--compile-only` passes just fine. Maybe I'll just go fix #15513 instead, though, since it would make this trivial.

**Comment by bradfitz** [comment]
Note that `dist test`'s `--compile-only` is not a promise but just a hint from the builders as an optimization to skip tests if convenient. It would be a bit more work to make sure `--compile-only` had stronger guarantees.

Alternatively, `buildall.bash` could just loop over `$(go list std cmd)` and run `go test -c $PKG`

**Comment by bradfitz** [comment]
Packages with tests:

```bash
$ for PKG in $(go list -f "{{.ImportPath}} {{.TestGoFiles}}" std cmd | \
   grep -v ' \[\]$' | perl -npe 's/ .+//'); do \
       echo $PKG; \
   done
```

**Comment by paranoiacblack** [comment]
Until #15513 is resolved, would it be okay to use the `go test -run=^$ std cmd` workaround? Since ideally, `go test -c std cmd` should just work anyways.

**Comment by bradfitz** [comment]
@paranoiacblack, no, because buildall.bash always runs on linux-amd64 and `go test -run` runs the (cross-) compiled binary.
