### ISSUE TITLE
path: make path/filepath suggestion more visible

### ISSUE THREAD

**Issue by rakyll** [golang/go#20117]
Forking from https://github.com/golang/go/issues/18581#issuecomment-294511925, it is not clear that `path/filepath` needs to be used for operating system path manipulation and path is only for slash-separated. Make it easier for users to see the `path/filepath` suggestion.

**Comment by bradfitz** [comment]
From #18581 it sounds like we don't want to add redundant text on each method, so I just sent CL 45653 to at least cross-link the path and path/filepath package docs to each other.
