### ISSUE TITLE
cmd/cgo: build typedef fail in clang but ok in gcc

### ISSUE THREAD

**Issue by fastfading** [golang/go#20129]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8

### What operating system and processor architecture are you using (`go env`)?
mac os 10 & ubuntu 16.04

### What did you do?

```
package main

/*
#include <stdlib.h>
#include <stdio.h>
typedef void GLvoid;
GLvoid Foo() {
   printf("foo");
}
*/
import "C"

func main() {
   C.Foo()
}
```

CC=clang CGO_ENABLE=1 go build -v void.go             **-->fail**
command-line-arguments
# command-line-arguments
./void.go:47:10: error: field has incomplete type 'GLvoid' (aka 'void')

CC=gcc CGO_ENABLE=1 go build -o void -v void.go      **-->ok**
command-line-arguments

### What did you expect to see?
all build ok in both gcc and clang

### What did you see instead?
clang build fail  but gcc ok

**Comment by fastfading** [comment]
gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
but build fail on mac
 gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 8.0.0 (clang-800.0.42.1)

Target: x86_64-apple-darwin15.5.0

Thread model: posix

**Comment by ianlancetaylor** [comment]
For some reason clang seems to be emitting ` DW_TAG_typedef` without actually saying what it is a typedef for.

    <1><6a>: Abbrev Number: 6 (DW_TAG_typedef)
        <6b>   DW_AT_name        : (indirect string, offset: 0x8c): GLvoid
        <6f>   DW_AT_decl_file   : 1
        <70>   DW_AT_decl_line   : 2

Perhaps it does that for any typedef of `void`?
