### ISSUE TITLE
 syscall: fix documentation typo

### ISSUE THREAD

**Issue by dtgoitia** [golang/go#20133]
At [https://gowalker.org/syscall#StringToUTF16Ptr](https://gowalker.org/syscall#StringToUTF16Ptr):
_(...) with a terminating **NUL** #added. **If s If s** contains (...)_
* _If s_ is duplicated.
* Along all the page ([https://gowalker.org/syscall](https://gowalker.org/syscall)) you can find repeatedly _NUL_ instead of _NULL_.

**Comment by bontibon** [comment]
> NUL instead of NULL.

The is the correct usage; it is referring to the [Null character](https://en.wikipedia.org/wiki/Null_character).

**Comment by dtgoitia** [comment]
My apologies, is the first time I saw it written as `NUL`. Thanks for the info!
