### ISSUE TITLE
cmd/go: -pkgdir doesn't respect -installsuffix or its variants

### ISSUE THREAD

**Issue by tamird** [golang/go#20137]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.8.1 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tamird/src/go"
GORACE=""
GOROOT="/Users/tamird/src/go1.8"
GOTOOLDIR="/Users/tamird/src/go1.8/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sw/d6165ghx7jx3cdl7cggxzbx00000gn/T/go-build026752780=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

```

### What did you do?
main.go:
```golang
package main

func main() {
}
```
```
$ go install -pkgdir ~/foobarpkgdir
$ ls ~/foobar*
total 3264
drwxr-xr-x   4 tamird  staff   136B Apr 26 13:28 .
drwxr-xr-x+ 33 tamird  staff   1.1K Apr 26 13:28 ..
drwxr-xr-x   3 tamird  staff   102B Apr 26 13:28 runtime
-rw-r--r--   1 tamird  staff   1.6M Apr 26 13:28 runtime.a
$ go install -race -pkgdir ~/foobarpkgdir
$ ls ~/foobar*
total 3344
drwxr-xr-x   4 tamird  staff   136B Apr 26 13:29 .
drwxr-xr-x+ 33 tamird  staff   1.1K Apr 26 13:29 ..
drwxr-xr-x   5 tamird  staff   170B Apr 26 13:29 runtime
-rw-r--r--   1 tamird  staff   1.6M Apr 26 13:29 runtime.a
$ go install -installsuffix baz -pkgdir ~/foobarpkgdir
$ ls ~/foobar*
total 3264
drwxr-xr-x   4 tamird  staff   136B Apr 26 13:31 .
drwxr-xr-x+ 33 tamird  staff   1.1K Apr 26 13:31 ..
drwxr-xr-x   5 tamird  staff   170B Apr 26 13:29 runtime
-rw-r--r--   1 tamird  staff   1.6M Apr 26 13:31 runtime.a
```

### What did you expect to see?

I expected `-pkgdir` to specify the "base" package directory, akin to `$GOPATH/pkg`, so that race builds and builds specifying an install suffix are separately cached.

### What did you see instead?

`-pkgdir` caused `-race` and `-installsuffix` to not affect the package cache directory.

`-pkgdir` was implemented this way in https://github.com/golang/go/issues/10210. Unfortunately, behaviour makes it extremely cumbersome to implement cross compilation toolchains that use cgo since handling of `-race` and `-installsuffix` must be reimplemented outside of the go tool.

If it is not feasible to change the behaviour of `-pkgdir`, perhaps a new flag `-rootpkgdir` could be added that would place nice with installsuffixes.

@rsc

**Comment by rsc** [comment]
For Go 1.9 I'm inclined to leave this alone; Go 1.10 will probably make it unnecessary to exercise this kind of control.

**Comment by tamird** [comment]
On Mon, Jun 5, 2017 at 7:00 AM, Russ Cox <notifications@github.com> wrote:

> Go 1.10 will probably make it unnecessary to exercise this kind of control.


Can you elaborate? Is this tracked somewhere?

**Comment by benesch** [comment]
@rsc seems to be planning an overhaul of build caching ([source 1](https://github.com/golang/go/issues/17571#issuecomment-310483210), [source 2](https://github.com/golang/go/issues/18981#issuecomment-310482869), [source 3](https://groups.google.com/d/msg/golang-dev/fI4wH-EFSes/7ltNwsGjAwAJ)) for Go 1.10, though I can't seem to turn up more information about the project. I too would be quite interested to hear more about what's in store! Build/test caching is one of our bigger pain points over at CockroachDB.

**Comment by rsc** [comment]
Go 1.10 has in fact made it unnecessary to exercise this kind of control. I can't quite tell from the original report why you thought -pkgdir was needed, but it is not needed anymore.
