### ISSUE TITLE
x/sys/unix: fchmodat under linux silently fails when passing flags

### ISSUE THREAD

**Issue by darkliquid** [golang/go#20130]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.1

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?
Using `syscall.Fchmodat` and setting the `AT_SYMLINK_NOFOLLOW` flag, e.g.

```go
import (
	"syscall"
	"golang.org/x/sys/unix"
)

func main() {
	syscall.Fchmodat(unix.AT_FDCWD, "/tmp/file", 0755, unix.AT_SYMLINK_NOFOLLOW)
}
```

### What did you expect to see?
Expected to see an error, as according to the [kernel source][1] the syscall doesn't accept the flags parameter and the [glibc source][2] returns an ENOTSUP.

### What did you see instead?
Instead, the call silently drops the flags parameter and follows the symlink, applying the fchmodat to the destination (or failing if the destination file can not be altered).

[1]:http://lxr.free-electrons.com/source/include/linux/syscalls.h#L776
[2]:https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/fchmodat.c.html

**Comment by stevenh** [comment]
The cause of this the prototype for the syscall generator is wrong as while the libc version supports flags the syscall version doesn't:
http://lxr.free-electrons.com/source/include/linux/syscalls.h#L776

**Comment by tklauser** [comment]
FYI, there is a patch for adding a fchmodat2() syscall to the Linux kernel which will support a flags parameter with `AT_SYMLINK_NOFOLLOW` set (currently still under discussion): https://patchwork.kernel.org/patch/9596301/
