### ISSUE TITLE
os: TestClosedPipeRaceWrite fails on ppc64x

### ISSUE THREAD

**Issue by mundaym** [golang/go#20134]
This new test, added in e3d7ec006f25385972c89f771d5d577adce3f024, seems to have broken the ppc64x builders.

```
--- FAIL: TestClosedPipeRaceWrite (0.00s)
	pipe_test.go:157: I/O on closed pipe unexpectedly succeeded
FAIL
FAIL	os	0.341s
```

**Comment by laboger** [comment]
Kind of odd that this passed the buildbots but fails everywhere else?

**Comment by mundaym** [comment]
@laboger I could be wrong but I think the trybots only check that the distribution compiles when targeting ppc64(le?), I don't think they actually run the tests on ppc64x. Does it fail for you locally?

**Comment by bradfitz** [comment]
Correct. Trybots (pre-submit tests) only compile ppc64x but don't run the tests. Post-submit builds run the tests on ppc64x hardware. We need lots of hardware to support trybots.

**Comment by ianlancetaylor** [comment]
What does `getconf PIPE_BUF /tmp` print on your system?

**Comment by bradfitz** [comment]
```
$ gomote create linux-ppc64-buildlet
user-bradfitz-linux-ppc64-buildlet-0
$ gomote run -system user-bradfitz-linux-ppc64-buildlet-0 getconf PIPE_BUF /tmp
4096

$ gomote create linux-ppc64le-buildlet
user-bradfitz-linux-ppc64le-buildlet-0
$ gomote run -system user-bradfitz-linux-ppc64le-buildlet-0 getconf PIPE_BUF /tmp                                                                                                              
4096
```

**Comment by ianlancetaylor** [comment]
OK, that is just weird.  This should not be processor dependent.
