### ISSUE TITLE
net: segmentation violation calling C getaddrinfo

### ISSUE THREAD

**Issue by eragnoli** [golang/go#20132]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
[root@fabcoin bcp]# go version
go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/bcp/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build441318668=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
run a go script on
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
no segmentation violation, the same code run on

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseWorkstation
Description:    Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo

works.

### What did you see instead?
see file attached
[_signal_SIGSEGV__segmentation_violation_code_0x1_addr_0x63_pc_0x7fa8cda23259_.txt](https://github.com/golang/go/files/958047/_signal_SIGSEGV__segmentation_violation_code_0x1_addr_0x63_pc_0x7fa8cda23259_.txt)

**Comment by mvdan** [comment]
Do you have a small program that reproduces the crash that you can share?

Does the crash happen on tip?

**Comment by ianlancetaylor** [comment]
Does this happen every time you run the program?

**Comment by ianlancetaylor** [comment]
The line numbers in your stack trace match the Go 1.7 sources, not the Go 1.8 sources.  Are you sure that you are running Go 1.8.1?

**Comment by eragnoli** [comment]
You are actually correct, the container is running
go version
go 1.6
Are there any known segment violation issues with that version?

**Comment by mvdan** [comment]
@eragnoli Go 1.6 is no longer supported - it's not even getting security fixes. Please use 1.8.x instead.

I'm going to close this, as this would be digging up bugs that were probably fixed in 1.7 or 1.8.
