### ISSUE TITLE
gofmt inconsistent behavior while formatting arithmetic operations

### ISSUE THREAD

**Issue by maxim-rstor** [golang/go#20140]
### What version of Go are you using (`go version`)?

```
go1.8 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?

```
gofmt -w .
```

### What did you expect to see?

```
searchByte = (searchPointStart + buddy.bitLevelOffset[level]) / 8
mask = setMap[(searchPointStart + buddy.bitLevelOffset[level]) % 8]
```

### What did you see instead?

```
searchByte = (searchPointStart + buddy.bitLevelOffset[level]) / 8
mask = setMap[(searchPointStart+buddy.bitLevelOffset[level])%8]
```

The second line doesn't have spaces around arithmetic operators at all. While the first one gets formatted correctly.

**Comment by mvdan** [comment]
This is likely by design. `gofmt` does not always space operators, but I don't remember the exact rules right now.

**Comment by bradfitz** [comment]
This is by design. There are heuristics about when to use spaces to help make precedence more clear. If it's not what you want in some particular case, the best advice is to not worry about it and go back to writing code.

**Comment by maxim-rstor** [comment]
The thing is that we'd like to have the code style consistent across all the same patterns. And it doesn't seem to work with `gofmt` in this case. You add spaces for the second line manually, and they all get removed when running `gofmt`. This looks like a bug actually...

CC @doug-rstor

**Comment by bradfitz** [comment]
Things like this come up periodically. See #19385 for the last case in which @griesemer said:

> The short answer is because that's how it's been decided early on.
gofmt is using various heuristics and - in this case - explicitly differentiates between the two cases.
This is working as intended.
> 
> PS: The longer answer is that we introduce blanks around the ':' if we have expressions on either side to separate the expressions and make the more visible. That's similar to why binary expressions are formatted differently depending on context.
