### ISSUE TITLE
playground: old 16x16 root favicon on play.golang.org

### ISSUE THREAD

**Issue by gaal** [golang/go#20149]
There are inconsistent faviocons on different Go web properties.

https://play.golang.org/favicon.ico has a small 16x16 image.

Would be nicer to see a larger image which displays nicer on high DPI devices, like the one served in https://golang.org/favicon.ico.

**Comment by kennygrant** [comment]
I think CL https://golang.org/cl/37591 fixes this issue.

**Comment by ysmolsky** [comment]
@bradfitz, it was resolved by the CL above. Can you please close this issue?

**Comment by bradfitz** [comment]
Done.
