### ISSUE TITLE
runtime/pprof: mips/mipsle may deadlock

### ISSUE THREAD

**Issue by vstefanovic** [golang/go#20146]
On mips/mipsle, 64bit atomics are emulated with spinlocks, in runtime/internal/atomic. If SIGPROF arrives while the program is inside a critical section, it creates a deadlock (when writing the sample).

This happens on the buildbot occasionally, e.g.:
https://build.golang.org/log/72ddc31061eb792759a7837e40cc4e38ed47d8ab
https://build.golang.org/log/53aed14580842bdf20a4ece60bae5c0d0b60c3bc
https://build.golang.org/log/0eb6d5078bf128e497aa27d406fe573e7dd79583

*** Test killed: ran too long (13m0s).
FAIL	runtime/pprof	785.041s

If nothing else, I'll send a patch that ignores SIGPROF in this case.

**Comment by cherrymui** [comment]
ARM also uses spinlocks. Why doesn't it deadlock?

**Comment by vstefanovic** [comment]
ARM has lock striping, with 57 spinlocks, so the probability for a deadlock is much lower, although not zero.

**Comment by cherrymui** [comment]
Ok, this is probably true. You can send you fix. Thanks!

Is there a simple test for this? Say running atomics in a loop and profiling it?

**Comment by andybons** [comment]
Closing since the CL appears to fix the issue. Please re-open if that's not the case.
