### ISSUE TITLE
program crashes: concurrent map read and map write

### ISSUE THREAD

**Issue by yangyuqian** [golang/go#20143]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.6.2

### What operating system and processor architecture are you using (`go env`)?

Redhat 5, and since there is no go tools installed on those host, no info on go env.

### What did you do?

I created following struct acting as a in-memory cache and expected it to work

```
type BadMap struct {
	cache map[string]int
	mu    sync.RWMutex
}

func (m *BadMap) Add(k string, v int) (err error) {
	if m.cache == nil {
		return errors.New("can not add element to a nil cache")
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	m.cache[k] = v

	return
}

func (m *BadMap) Get(k string) (v int, err error) {
	if m.cache == nil {
		return -1, errors.New("can not get element from a nil cache")
	}

	m.mu.RLock()
	defer m.mu.RUnlock()

	if v, ok := m.cache[k]; ok {
		return v, nil
	}

	return -1, errors.New("element not found")
}
```

After looking into the monitoring and logs, i realized that i used a bad key for the map, and this map will grow into gigabytes when running in hours.

Is there any possibility that map can be write and read concurrently with a RWMutex? hashGrow?

### What did you expect to see?

I've read this [post](https://blog.golang.org/go-maps-in-action#TOC_6.)

Cache still working since i added mutex on it

### What did you see instead?

it's correctly on my PC and testing environments, but on the server, program crashes with following error:

```
fatal error: concurrent map read and map write
goroutine 68124 [running]:
runtime.throw(0x89a040, 0x21)
    /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8209c51f8 sp=0xc8209c51e0
runtime.mapaccess2_faststr(0x7271e0, 0xc82007f260, 0xc8217b2180, 0x2a, 0x47a448, 0xc820f22050)
    /usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8209c5258 sp=0xc8209c51f8
```

Any help will be appreciated.

**Comment by davecheney** [comment]
Several things

1. Rhel5 is not a supported operating system, the kernel is too old.
2. You should upgrade to go 1.8.1, 1.6.x is no longer supported.
3. Please build your application with the -race flag, which will tell you
where the data races in your code are occurring.

**Comment by bradfitz** [comment]
This fatal error has no false positives, which means you have a real data race. As @davecheney said, use the race detector to see the details.

See https://blog.golang.org/race-detector etc
