### ISSUE TITLE
proposal: void safety

### ISSUE THREAD

**Issue by henryas** [golang/go#20142]
Hi,

I wonder about the possibility of introducing [void safety](https://en.wikipedia.org/wiki/Void_safety) in Go. When you call obj.Method() or dereference *obj, the compiler makes a guarantee that obj is not null, or else it will not compile. At the moment, in Go 1.8, the problem won't be detected until runtime. In a more complex situation, the issue may escape detection until the software is run in the production environment. Tony Hoare calls this a billion dollars mistake.

I am not a programming language expert, but I think this is worth implementing and it may potentially prevent many bugs.

**Comment by bradfitz** [comment]
Thanks for the suggestion but the Go 1.x language is frozen at this stage. I'm going to close this but rest assured that the language folk are well aware of the issues here and it will remain under consideration for any future language update.
