### ISSUE TITLE
doc/play: make fib.go example start with 0?

### ISSUE THREAD

**Issue by amller** [golang/go#20147]
By changing [go/doc/play/fib.go](https://github.com/golang/go/blob/master/doc/play/fib.go) line 8 from: `a, b := 0, 1` to `a, b := 1, 0` we get a more flexible example:
By definition the sequence starts with 0 or 1.
With this change we can simply switch if we want to include 0 or not by just changing the returned variable in line 11 between `a` or `b`. (`a` will include the 0. `b` won't)

Code: https://play.golang.org/p/lSHLBunWAB

**Comment by bradfitz** [comment]
The examples are supposed to give people a flavor of Go and let them start tinkering. They seemed to have worked. :-)

Is your bug report that the sequence should start with 0?

**Comment by amller** [comment]
No, it's not a bug report. It is an suggestion to improve the example

**Comment by bradfitz** [comment]
I'll let @broady decide.
