### ISSUE TITLE
x/net/ipv[46]: ControlMessage unimplemented on Windows

### ISSUE THREAD

**Issue by tmm1** [golang/go#20153]
Both x/net/ipv4 and x/net/ipv6 return `EWINDOWS` and have "TODO: implement this" comments:

https://github.com/golang/net/blob/master/ipv4/control_windows.go
https://github.com/golang/net/blob/master/ipv6/control_windows.go

It appears that Windows has a [`WSARecvMsg`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741687(v=vs.85).aspx) which provides access to the underlying control messages:

> For datagrams received by the WSARecvMsg function over IPv4, the Control member of the WSAMSG structure received will contain a WSABUF structure that contains a WSACMSGHDR structure. The cmsg_level member of this WSACMSGHDR structure would contain IPPROTO_IP, the cmsg_type member of this structure would contain IP_PKTINFO, and the cmsg_data member would contain an in_pktinfo structure used to store received IPv4 packet address information. The IPv4 address in the in_pktinfo structure is the IPv4 address from which the packet was received.

I couldn't find any mentions of `WSARecvMsg` in the golang source. Indeed, it appears that `netFD.readMsg` is unimplemented as-well on windows: https://github.com/golang/go/blob/12c286c149583edbb08045cc8f518f0c90c7dc85/src/net/fd_windows.go#L233

So I guess the first step would be to add a syscall wrapper for `WSARecvMsg` and then implement `netFD.readMsg` on top of it?

cc @mikioh

**Comment by mikioh** [comment]
Sure, #9252, then #7174 and #7175.

**Comment by alexbrainman** [comment]
@tmm1 feel free to send me CLs for review.
I will help in whatever way I can.

Alex

**Comment by mikioh** [comment]
I'll merge this issue into #7175.
