### ISSUE TITLE
cmd/go: TestTestRaceInstall is too slow to run when -short specified

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#20158]
I was investigating why running "go test -short cmd/go" is slow on my computer, And I noticed TestTestRaceInstall was added recently. TestTestRaceInstall takes a while to run:
```
c:\>go test -v -run=TestTestRaceInstall cmd/go
=== RUN   TestTestRaceInstall
--- PASS: TestTestRaceInstall (27.30s)
        go_test.go:269: running testgo [install -race -pkgdir=C:\Users\Alex\AppData\Local\Temp\gotest749145327\pkg std]
        go_test.go:269: running testgo [test -race -pkgdir=C:\Users\Alex\AppData\Local\Temp\gotest749145327\pkg -i -v empty/pkg]
PASS
ok      cmd/go  31.923s
```

But TestTestRaceInstall is run when -short flag is provided. I wonder if we should skip this test for -short.

Alex

PS: My computer is slow, but it is not slowest in the world.

**Comment by mvdan** [comment]
Even on my new-ish laptop with an SSD, it takes ~15s. Agreed on making it be skipped on `-short`.

**Comment by alexbrainman** [comment]
> Agreed on making it be skipped on -short.

Thank you @mvdan for support :-), but I doubt you and me could make that decision.
Leaving it for others.

Alex

**Comment by mvdan** [comment]
Oh, sure - was more meant as "sounds like a good idea" more than "let's do that".

**Comment by ianlancetaylor** [comment]
SGTM

**Comment by alexbrainman** [comment]
@ianlancetaylor my computer says thanks to you.
(So it doesn't have to work as hard.)

Alex
