### ISSUE TITLE
x/build/cmd/gomote: list subcommand does not work

### ISSUE THREAD

**Issue by josharian** [golang/go#20151]
`gomote list` returns successfully but with no results. The call to `/buildlet/list` is getting a 200 OK with body of `[]` (empty json array). At rev 3aa399bf508e849ab953e8fed179aedd600c9f0e (Wed Apr 26 2017 22:51:10 GMT-0700 (PDT)).

Who do I cc for this? @bradfitz @adams-sarah @quentinmit maybe?

Short of fixing this, where should I look for a static list of builders? I'm (still) trying to reproduce #20144 and thinking maybe I need a linux box for it...

**Comment by bradfitz** [comment]
`gomote list` lists your current alive buildlet instances. I guess the docs suck.

Run `gomote create` with no argument to get a list of buildlets.

Once you create one, it'll then appear in `gomote list`

**Comment by josharian** [comment]
Oh yeah, that's a docs problem. Ok, I'll fix that somewhere/somehow.
