### ISSUE TITLE
database/sql: Need to fetch Multiple Resultset using MSSQL Stored Procedure

### ISSUE THREAD

**Issue by NileshYendhe** [golang/go#20157]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 LTS

### What did you do?
Working as a Developer

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Need to fetch multiple result sets by calling sql stored procedure at a one single time

**If you can provide one simple example to get multiple result sets using SQL Stored Procedure at a one single time I would be very happy. 

Thanks....**

### What did you see instead?
Getting only 1 result set

**Comment by matipan** [comment]
This issue is poorly formatted. Please read the [contributing section](https://github.com/golang/go/wiki#contributing-to-the-go-project) before creating issues.

If you want examples, you should check out [this issue](https://github.com/golang/go/issues/12382) where the `NextResultSet` feature was implemented.

For questions about Go, see https://golang.org/wiki/Questions

Since this is not an issue with Go or the library, you should close it.

**Comment by bradfitz** [comment]
@matipan, "poorly formatted" might be a little harsh... this uses the recommended template, after all.

@NileshYendhe, this was added in Go 1.8.

See https://golang.org/doc/go1.8#database_sql

I don't know whether the MSSQL driver supports it, though. Maybe @kardianos knows.

**Comment by kardianos** [comment]
It supports it. Also direct execution of procs is about to got better, no more need for exec, just proc name, pending PR.

**Comment by NileshYendhe** [comment]
Thanks @kardianos, For your information. I'll check.

**Comment by matipan** [comment]
Sorry @bradfitz if it sounded harsh, I was referring to the title not having the package it was referring to. I could have explained it better, will do the next time :)

**Comment by bradfitz** [comment]
@matipan, no worries. We can't expect users to follow all of our conventions. If you want to help garden, you can get access and then you can just edit subject lines to match Go's style.

**Comment by matipan** [comment]
@bradfitz, that's true
I've just requested access, thank you!
