### ISSUE TITLE
AddDate return error result

### ISSUE THREAD

**Issue by LouisYuBin** [golang/go#20155]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8

### What operating system and processor architecture are you using (`go env`)?
ubuntu kylin 16.04 LTS

### What did you do?

`package main

import (
	"time"
	"fmt"
)

func main() {

	userTime, err := time.Parse("2006-01-02", "2017-12-31")
	if err != nil {
		fmt.Println(err)
	}
	lastMonthTime := userTime.AddDate(0, -1, 0)

	fmt.Println(lastMonthTime)
	lastMonthMonth := int(lastMonthTime.Month())
	fmt.Println(lastMonthMonth)

}
`

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
2017-11-30 00:00:00 +0000 UTC
11

### What did you see instead?

2017-12-01 00:00:00 +0000 UTC
12

**Comment by ianlancetaylor** [comment]
This is behaving as documented.  Subtracting one month from "December 31" produces "November 31".  Since there is no such date, it is normalized to "December 1".  See https://golang.org/pkg/time/#Time.AddDate .
