### ISSUE TITLE
No way to catch errors from goroutines automatically

### ISSUE THREAD

**Issue by muravjov** [golang/go#20161]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

$ go version
go version go1.7.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/opt/programming/golang/git"
GOTOOLDIR="/opt/programming/golang/git/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build930744821=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?

Thanks to `go` keyword it is easy to write concurrent algorithms, but also it is easy to make errors, which one cannot catch. For example:

```
package main

func main() {
	go func(){
		// = panic() = exit(2) + print(stacktrace)
		i := 0
		i = 1 / i
	}()
}

```

And you cannot catch it unless you manually add defer to every `go` invocation, like that:

```
func main() {
	go func(){
		defer func() {
			err := recover()
			...
			panic(err)
		}()

		// = panic() = exit(2) + print(stacktrace)
		i := 0
		i = 1 / i
	}()
}
```
You may catch such errors only by reading stderr from target process and guessing it is a Go stacktrace. Which is a hack.

### What did you expect to see?

I need a mechanism to catch errors and send them with tracebacks (e.g. into [https://sentry.io](Sentry) ). Like postmortem library [Breakpad](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/getting_started_with_breakpad.md) for C++ .

But there is no way to _hook_ a defer to every new goroutine. It may be realized via special API to call `newdefer/deferproc` internal function from runtime/panic.go .

P.S. Similar discussion is about  [atexit](https://groups.google.com/forum/#!topic/golang-nuts/qBQ0bK2zvQA/discussion) , where Ian Lance Taylor writes that 
"The only fully reliable mechanism is a wrapper program ..."

**Comment by ianlancetaylor** [comment]
This has been discussed before.  It is not going to change at this point.

You can fix it in your own code, for your own goroutines, by using a function like

func Go(f func()) {
    defer func() {
        if r := recover(); r != nil {
            // do something
        }
    }()
    go f()
}

For the general case, use a wrapper program.

If you want to raise a proposal with a specific suggestion for how to address this general problem, please feel free to use the proposal process described at https://github.com/golang/proposal/blob/master/README.md .  I don't personally think that such a proposal is likely to be accepted, but we are always open to good new ideas.

This issue has no specific suggestion for how to fix this, so I am going to close this.

**Comment by iigorr** [comment]
@ianlancetaylor: Your suggestion does not work. The Go function would not recover the a panic in `f()`. This is the acutual problem here. See https://play.golang.org/p/YP5n7-lzcz

**Comment by cznic** [comment]
@iigorr Try https://play.golang.org/p/kuMqW29Ja1

**Comment by President** [comment]
This "func Go" wrapper is not a solution - we may have many functions with very different parameters - so we need to create many Go-wrappers? It is not usable at all. 
We need easy way to wrap catch all panics from all goroutines!

**Comment by ofux** [comment]
Why was this issue closed without any further discussion?

**Comment by randall77** [comment]
Because this issue really needs a proposal for it to be actionable.

**Comment by calixwu** [comment]
So is there a proposal now?

**Comment by President** [comment]
FYI: We finally end up with  wrapper and prohibiting the team to  use "go" operator directly. 
However I  still dislike this solution. Language should provide a way to catch  all errors w/o wrapping every "go" operator.

```
recovery.SafeGo(logger, func() {
              method(all parameters)
	})

func SafeGo(logger logging.ILogger, f func()) {
	go func() {
		defer func() {
			if panicMessage := recover(); panicMessage != nil {
				stack := debug.Stack()

				logger.Errorf("RECOVERED FROM UNHANDLED PANIC: %v\nSTACK: %s", panicMessage, stack)
			}
		}()

		f()
	}()
}
```

**Comment by ianlancetaylor** [comment]
@calixwu There is no proposal here.  If somebody has a proposal, please open a new issue.  See https://golang.org/s/proposal.  But it is very unlikely that the language will change.  People who want to use `SafeGo` as in the previous comment can already write it.

**Comment by calixwu** [comment]
@ianlancetaylor ok...

**Comment by avivmag** [comment]
> FYI: We finally end up with wrapper and prohibiting the team to use "go" operator directly.
> However I still dislike this solution. Language should provide a way to catch all errors w/o wrapping every "go" operator.
> 
> ```
> recovery.SafeGo(logger, func() {
>               method(all parameters)
> 	})
> 
> func SafeGo(logger logging.ILogger, f func()) {
> 	go func() {
> 		defer func() {
> 			if panicMessage := recover(); panicMessage != nil {
> 				stack := debug.Stack()
> 
> 				logger.Errorf("RECOVERED FROM UNHANDLED PANIC: %v\nSTACK: %s", panicMessage, stack)
> 			}
> 		}()
> 
> 		f()
> 	}()
> }
> ```

I just want to add a note that although it really is a nice workaround, whoever use that must keep in mind about the common mistake of ['Using goroutines on loop iterator variables'](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables)

**Comment by mangelajo** [comment]
It's sad there is no way to have a global panic capture embedded in the language,.... this issue may be re-opened and considered.

**Comment by ianlancetaylor** [comment]
@mangelajo I'm sorry, but this issue is closed.  Please see the comment above: https://github.com/golang/go/issues/20161#issuecomment-561699692.
