### ISSUE TITLE
Add debug option (-X) to compiler so it won't complain about unused variables

### ISSUE THREAD

**Issue by HaraldNordgren** [golang/go#20182]
I don't expect this ticket to stay open, but I want to post it anyway. I just got into Go and I already have a major issue with programming efficiency.

If I comment one line of code when debugging (because it is malfunctioning or what not), I often need to comment more lines because a variable is suddenly unused and the Go code won't run. Commenting a previous line requires me to comment yet another one.

I am perfectly capable of keeping that of unused variables and imports. Yes, it's useful to have these things enforced when taking your code to production. But it terrible when debugging.

**Comment by ALTree** [comment]
> But it terrible when debugging.

You get used to it after a while. There are several workarounds. You can for example disable code by wrapping the section with an `if false {` (bind to a macro in your editor if that's annoying to type).

If you want to comment, you can add `_, _ = now-unused1, now-unused2` etc... just after the commented line. This will keep the change local (no need to jump in the file to comment other lines).

It's highly unlikely this proposal will be accepted. The project has always followed a quite strict "no compiler knobs/flags unless is absolutely necessary" policy.

**Comment by mvdan** [comment]
There are even projects that automate this: https://github.com/elazarl/gosloppy

I agree that it can be annoying at first, but you get used to it and it forces you to write better code right from the start.

**Comment by bradfitz** [comment]
In addition to what others have said, see https://golang.org/doc/faq#unused_variables_and_imports
