### ISSUE TITLE
Proposal: Create method on defined struct using reflection

### ISSUE THREAD

**Issue by apoloa** [golang/go#20189]
It would be good create functions using reflection inside the struct already defined. 

Like this:

``` Go
package main

import (
	"fmt"
	"reflect"
)

type Manager struct{}

func main() {

	swap := func(in []reflect.Value) []reflect.Value {
		return []reflect.Value{in[1], in[0]}
	}

	makeSwap := func(fptr interface{}) {
		fn := reflect.ValueOf(fptr).Elem()
		v := reflect.MakeFunc(fn.Type(), swap)
		fn.Set(v)
	}

	var intSwap func(int, int) (int, int)
	makeSwap(&intSwap)

	var floatSwap func(float64, float64) (float64, float64)
	makeSwap(&floatSwap)

	manager := &Manager{}
	st := reflect.ValueOf(manager).Elem()
	st.MethodByName("IntSwap").Set(reflect.ValueOf(intSwap))
	st.MethodByName("FloatSwap").Set(reflect.ValueOf(floatSwap))
	fmt.Println(intSwap(0, 1)) // 1 0
	fmt.Println(manager.IntSwap(0,1)) // 1 0
	fmt.Println(floatSwap(2.72, 3.14)) // 3.14 2.72
	fmt.Println(manager.FloatSwap(2.72, 3.14)) // 3.14 2.72
}
```

**Comment by ianlancetaylor** [comment]
As a general rule, the reflect package should provide exactly the capabilities of the language.  In the language you can not define a method on an existing struct, so reflect shouldn't let you do it either.

Also, if you could define a struct in one package and add methods in another the general handling of interface conversion would be inconsistent, depending on whether the methods had been added or not.

I think that reduces this to a dup of #16522.

I'm going to close this, but please comment if you disagree.
