### ISSUE TITLE
net/http: connReader.bgErr is read but never set

### ISSUE THREAD

**Issue by mvdan** [golang/go#20196]
`bgErr` in `connReader` (`server.go` line 626) is read in line 735, but it's never assigned to.

Do we want to write to it in the `handleReadError` method, or should we get rid of the field and the dead code? (I assume the former, but opening an issue just in case)

Found via https://github.com/mvdan/unparam, which noticed that the `handleReadError` is unused.

CC @bradfitz

**Comment by bradfitz** [comment]
Haven't looked into it, but I assume we should just delete unused things.
