### ISSUE TITLE
json.RawMessage `json:"omitempty" - always omitted ?

### ISSUE THREAD

**Issue by SjonHortensius** [golang/go#20194]
Not sure if this is a bug; but when combining json.RawMessage with omitempty, the property is never properly unmarshalled, even when there is data

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
irrelevant; also reproducible on play.golang.org

### What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
	"log"
)

func main() {
	type Color struct {
		Space string
		Point json.RawMessage `json:"omitempty"` // TOGGLE ME 
	}

	var j = []byte(`[
		{"Space": "YCbCr", "Point": "test"},
		{"Space": "RGB"}
	]`)
	var colors []Color
	err := json.Unmarshal(j, &colors)
	if err != nil {
		log.Fatalln("error:", err)
	}

	for _, c := range colors {
		fmt.Printf("%v\n", c)
	}
}
```

### What did you expect to see?
Both with and without omitempty:
> {YCbCr [34 116 101 115 116 34]}
> {RGB []}

### What did you see instead?

Without omitempty:
> {YCbCr [34 116 101 115 116 34]}
> {RGB []}

With omitempty:
> {YCbCr []}
> {RGB []}

**Comment by bradfitz** [comment]
I think you're missing the comma before `omitempty`.

**Comment by SjonHortensius** [comment]
That is correct, thanks. I noticed options aren't validated, is this intentional? Something like this also fails:

```
`json:abc` /* should be `json:"abc"` */
```

**Comment by bradfitz** [comment]
`go vet` checks that.
