### ISSUE TITLE
x/build/cmd/gomote: don't push gitignored files

### ISSUE THREAD

**Issue by josharian** [golang/go#20197]
Broken out from https://github.com/golang/go/issues/13834#issuecomment-272524137.

I have a lot of gitignored files in my GOROOT. (Don't ask, please.) gomote pushes them all, which is slow and pointless. I'd like gomote not to do this. I would implement by starting a [`git check-ignore`](https://git-scm.com/docs/git-check-ignore) process running concurrently and feeding it paths as part of the filepath walk.

This issue is to ask for approval before putting in the time to implement.

@bradfitz

**Comment by bradfitz** [comment]
Sure.
