### ISSUE TITLE
playground: play.golang.org > About > Version links to script "Unavailable For Legal Reasons"

### ISSUE THREAD

**Issue by SjonHortensius** [golang/go#20193]
While attempting to find out the version of play.golang.org; I followed the link to https://play.golang.org/p/1VcPUlPk_3 as described on the About page. Instead of useful output, I get:

`<h1>Unavailable For Legal Reasons</h1><p>If you believe this is in error, please <a href="https://golang.org/issue">file an issue</a>.</p>`

**Comment by ianlancetaylor** [comment]
Hmmm, works for me.  What IP address are you connecting from?

**Comment by SjonHortensius** [comment]
I connect via IPV6: 2a02:27f8:3020:1:xxx

**Comment by bradfitz** [comment]
@SjonHortensius, either Google's geolocation data is buggy, or your server is in China.

@broady, can you file an internal bug about this, like the previous ones you've done?

**Comment by SjonHortensius** [comment]
@bradfitz My address range is known to route to the Netherlands

**Comment by electricface** [comment]
I have also encountered the same problem.

**Comment by bradfitz** [comment]
@electricface, if you're in China, it's expected. It's unavailable in China for legal reasons.

**Comment by broady** [comment]
@SjonHortensius do you still see this? I expect so. Looks like 2a02:27f8:: was classified as Netherlands until late last year, then for a few weeks this year.

Can you give a more specific address/range? Feel free to mail it to me - cbro at golang dot org.

I've reported it, so if it gets classified back to NL, then you'll see it live in a couple weeks.

**Comment by SjonHortensius** [comment]
@broady actually it's working now; not sure what changed as I'm still in the same range. If this happens again I'll reopen / mail you the exact ipv6 address
