### ISSUE TITLE
sync: TestPool failure on windows-amd64-2016

### ISSUE THREAD

**Issue by josharian** [golang/go#20198]
Noticed on build.golang.org.

https://build.golang.org/log/a3f357b132ef8cb703e42085a50c8c4499e64301

```
##### sync -cpu=10
--- FAIL: TestPool (0.00s)
	pool_test.go:29: got "b"; want a
FAIL
FAIL	sync	0.412s
```

First showed up after CL 42090, although that seems unlikely to be the cause.

cc @valyala @dvyukov

**Comment by josharian** [comment]
@dlespiau

**Comment by dlespiau** [comment]
It seems unlikely to be caused by [CL 42090](https://go-review.googlesource.com/c/42090/) indeed. That (SSE) instruction isn't generated by the compiler and not present in any of the `.s` files in the go project (well, apart from the testdata file checking its correctness).

**Comment by dvyukov** [comment]
Perhaps the goroutine was rescheduled to another P (due to preemption?).
`runtime.GOMAXPROCS(1)` should with against that.

**Comment by bradfitz** [comment]
Also openbsd-386:
https://build.golang.org/log/71a13d246b73925bd56923c0a706a95cbaf74e74
and others

**Comment by bradfitz** [comment]
@aclements, this started happening pretty frequently. Do you know what changed?

**Comment by josharian** [comment]
The only recent sync.Pool change I can think of is [CL 40913](https://golang.org/cl/40913).

**Comment by bradfitz** [comment]
That one *seems* safe.

**Comment by josharian** [comment]
Oh, also [CL 40918](https://golang.org/cl/40918).

**Comment by aclements** [comment]
I'm only seeing three failures ever. Did I grep this wrong?

`$ greplogs -dashboard -E "FAIL: TestPool" -md -l`
[2017-04-29T04:14:36-b225396/linux-386](https://build.golang.org/log/2f47ec66601609840f150c25307c635af00a262d)
[2017-05-02T20:03:30-9f6fde3/nacl-amd64p32](https://build.golang.org/log/8fdb34e365cfa5c179f51c29e52e335d304e9a79)
[2017-05-04T21:55:36-8d63408/openbsd-386-60](https://build.golang.org/log/71a13d246b73925bd56923c0a706a95cbaf74e74)

**Comment by bradfitz** [comment]
@aclements, I've seen a number of trybot failures too, and those three URLs are all of the form used by non-trybot failures.

**Comment by aclements** [comment]
Okay. If it's failing fairly regularly on the trybots, can we bisect this?

**Comment by dvyukov** [comment]
Note that the test is formally broken/incorrect. So any innocent change can suddenly cause increased failure rate it in. Does cl/42770 help? We could also use procPin/procUnpin around the test, that should reflect the intention of the test -- within same P reuse order is LIFO.

**Comment by ianlancetaylor** [comment]
Just saw this on nacl-386: https://storage.googleapis.com/go-build-log/b9150e2c/nacl-386_6f3075c2.log
