### ISSUE TITLE
doc: CLA instructions are out of date

### ISSUE THREAD

**Issue by mprobst** [golang/go#20207]
https://golang.org/doc/contribute.html#cla suggests to navigate to Settings -> Agreements in gerrit. There is no menu entry called "Agreements" for me on https://go-review.googlesource.com/settings.

**Comment by ALTree** [comment]
We could link directly to https://go-review.googlesource.com/settings/agreements, that page will inform you that you'll need to switch to the old UI if you are using polygerrit.
