### ISSUE TITLE
x/crypto/ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc 3des-cbc aes128-cbc]

### ISSUE THREAD

**Issue by CameronGo** [golang/go#20201]
Please answer these questions before submitting your issue. Thanks!

We onboarded a new client with a new SFTP endpoint and are seeing an error message we never encountered.  I saw another issue about setting up other cipher support in a config file.  If that is indeed what I need to do, I'm unsure how best to do that.  The app in this case is a single binary deployed into a "from scratch" Docker image, so there is no real SSH client config file to refer to.  

Error
ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc 3des-cbc aes128-cbc]

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"

from the current golang docker image

### What did you do?
Attempting connection to SFTP host

### What did you expect to see?
Successful authentication and connection

### What did you see instead?
ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc 3des-cbc aes128-cbc]

**Comment by hanwen** [comment]
works as intended. 3DES is deprecated, and the CBC ciphers have weaknesses, so they're disabled by default.

**Comment by CameronGo** [comment]
@hanwen - can I allow the CBC cipher using the ssh.ClientConfig options, or does this require forking the package as discussed here? https://github.com/golang/go/issues/13776

**Comment by hanwen** [comment]
just try it. it should work.

**Comment by CameronGo** [comment]
Is it possible to just _add_ the cbc ciphers to the already default ciphers?  I don't want to explicitly define the ciphers such that, when there are changes to the default ciphers, I don't get those changes.  Can anyone point me to a code sample doing this b/c I haven't been able to find a single example of this anywhere.

**Comment by CameronGo** [comment]
Ended up finding an example of how to use this from one of the unit tests:
https://gondolaweb.com/doc/src/golang.org/x/crypto/ssh/test/session_test.go

**Comment by Mebus** [comment]
hm. This doesn't work for me. Is this correct?

<code>
	var sshconfig ssh.Config
	sshconfig.SetDefaults()
	cipherOrder := sshconfig.Ciphers
	cipherOrder = append(cipherOrder, "aes128-cbc", "3des-cbc")

	// Authentication
	config := &ssh.ClientConfig{
		Config: sshconfig,
		User:   "ciscouser",
		//Auth: []ssh.AuthMethod{SSHAgent()},
		//alternatively, you could use a password
		Auth:            []ssh.AuthMethod{ssh.Password("blablabla")},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
	}
</code>

I think I am going to have to use telnet instead of ssh...

Mebus

**Comment by hanwen** [comment]
you're not changing the slice inside sshconfig

**Comment by Mebus** [comment]
What do I have to change?

Mebus

**Comment by hanwen** [comment]
config.ciphers = append(config.ciphers, ...)

**Comment by Mebus** [comment]
It's in there, but the github is formatting it badly:

cipherOrder = append(cipherOrder, "aes128-cbc", "3des-cbc")

Like this?

Mebus

**Comment by hanwen** [comment]
you're not changing config.Ciphers, you're just changing cipherOrder

**Comment by Mebus** [comment]
aaaahh!!! My fault. Working now :-)

sshconfig.Ciphers = append(cipherOrder, "3des-cbc")

Thanks. :-) 

Mebus

**Comment by thinkt4nk** [comment]
is there documentation somewhere that lists supported ciphers?
