### ISSUE TITLE
cmd/link: inline and simplify dosymtype

### ISSUE THREAD

**Issue by josharian** [golang/go#20205]
Per @mwhudson's comment at https://go-review.googlesource.com/c/40864/5/src/cmd/link/internal/ld/data.go#1143.

**Comment by quasilyte** [comment]
I'll try encouraging someone to tackle this issue tomorrow on the go contributors workshop.
That function is still there and has only 1 usage.

**Comment by quasilyte** [comment]
I believe this issue should be closed since mentioned function is inlined and removed. :)

**Comment by josharian** [comment]
@mwhudson's comment referenced in the OP was:

> Seems to me that this function can now be deleted and replaced with 

```go
switch Buildmode {
	case BuildmodeCArchive, BuildmodeCShared:
		s := ctxt.Syms.ROLookup(*flagEntrySymbol)
		if s != nil {
			addinitarrdata(ctxt, s)
		}
}
```

CL 171733 inlined the code but did not do the simplification suggested. This issue was left open to do that simplification, if possible. I don't know enough about the linker to say whether that simplification is correct.

cc @cherrymui @thanm @jeremyfaller

**Comment by thanm** [comment]
These sorts of loops over ctxt.Syms.Allsym hunting for a specific symbol by name are one of the many things that we're trying to eliminate in the new linker.  I'll send a CL on the dev.link branch.

**Comment by thanm** [comment]
I've submitted https://golang.org/cl/209838 ... it might be a bit premature (given that the dev.link branch is not yet merged into master) but I'm going to close out the bug, with the expectation that we'll be doing the merge in the 1.15 timeframe.
