### ISSUE TITLE
x/crypto/ssh: Failed to open ssh connection to the server: ssh: must specify HostKeyCallback

### ISSUE THREAD

**Issue by CameronGo** [golang/go#20200]
Please answer these questions before submitting your issue. Thanks!

No code changes were made, but I did my first code rebuild since Mar 22.  Now the application is broken and getting the cited error message.  My build environment uses the latest golang docker image and always does a go get -u.  

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?
I just did a code rebuild today and then the application attempted an SFTP connection using username and password credentials.

### What did you expect to see?
A successful file transfer

### What did you see instead?
This error: Failed to open ssh connection to the server: ssh: must specify HostKeyCallback

**Comment by bradfitz** [comment]
Yes, this was a breaking change made for security reasons.

You need to specify one. See #19767.

**Comment by jilieryuyi** [comment]
the correct way to use ssh, then fix it . https://github.com/jilieryuyi/ssh-simple-client/blob/master/main.go
