### ISSUE TITLE
cmd/compile: iota can be shaddowed in functions, but can't in top level.

### ISSUE THREAD

**Issue by go101** [golang/go#20219]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.1 linux/amd64

### What did you do?

```golang
package main

const iota = iota // constant definition loop

func g() {
	const iota = iota // ok
}

func main(){}
```

**Comment by mdempsky** [comment]
`const x = x` isn't valid at package scope. What would `x`'s value be?

**Comment by go101** [comment]
iota is predeclared in builtin package.

**Comment by mdempsky** [comment]
The scope of package level const declarations is the entire package. The scope of function-level const declarations begins after the declaration.

After explicit renaming, your code is:

    package main

    const iota.0 = iota.0 // constant definition loop

    func g() {
	const iota.1 = iota.0 // ok
    }

**Comment by go101** [comment]
The program in my first comment is two programs in fact

1:
```golang
package main

func g() {
	const iota = iota // ok
}

func main(){}
```
2:
```golang
package main

const iota = iota // constant definition loop

func main(){}
```

**Comment by mdempsky** [comment]
That's correct. gccgo and go/types emit the same errors.

This is working according to spec.

**Comment by go101** [comment]
Which paragraph in spec?

**Comment by mdempsky** [comment]
[Declarations and scope](https://golang.org/ref/spec#Blocks)

> 2. The scope of an identifier denoting a constant, type, variable, or function (but not method) declared at top level (outside any function) is the package block.

> 5. The scope of a constant or variable identifier declared inside a function begins at the end of the ConstSpec or VarSpec (ShortVarDecl for short variable declarations) and ends at the end of the innermost containing block.

**Comment by go101** [comment]
but iota is a predeclared constant.

**Comment by mdempsky** [comment]
Please see https://github.com/golang/go/wiki/Questions.

**Comment by go101** [comment]
```
package main


func g() {
	const iota = iota // ok
	
	const a = a // undefined: a

	// they should be consistent if iota is viewed as undeclared.
}

func main(){}
```

**Comment by griesemer** [comment]
@go101 iota is predeclared, but in your program you're not referring to it:
```
package p
const iota = iota
```
The first thing that happens is that you declare a new identifier `iota` in the package (right after the const keyword) and that identifier is shadowing the predeclared `iota`. Afterwards you use that same one as initial value (not the predeclared one), hence the cycle.

**Comment by cznic** [comment]
> const iota = iota // ok

Because RHS is defined.

> const a = a // undefined: a

Because RHS is undefined.

**Comment by go101** [comment]
ok, this is really subtle.
