### ISSUE TITLE
x/net/http2: incomplete list of bad HTTP/2 cipher suites causes a TLS server to not start up with a correct cipher suite list

### ISSUE THREAD

**Issue by gotwarlost** [golang/go#20213]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.8 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ananthk"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037787161=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

https://play.golang.org/p/ucaLECZznh

### What did you expect to see?

Server should start correctly

### What did you see instead?

Server produces error:

```
http2: TLSConfig.CipherSuites index 7 contains an HTTP/2-approved cipher suite (0x003c), but it comes after unapproved cipher suites. With this configuration, clients that don't support previous, approved cipher suites may be given an unapproved one and reject the connection.
```
My explanation in the code comments in the playground link.

**Comment by dmitris** [comment]
confirmed also with go1.8.1.  With the diff below, I am not getting the TLSConfig.CipherSuites error in the test program:
```
$ git diff
diff --git a/src/net/http/h2_bundle.go b/src/net/http/h2_bundle.go
index 57bc0a5..859752c 100644
--- a/src/net/http/h2_bundle.go
+++ b/src/net/http/h2_bundle.go
@@ -2175,6 +2175,7 @@ func http2isBadCipher(cipher uint16) bool {
                tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
                tls.TLS_RSA_WITH_AES_128_CBC_SHA,
                tls.TLS_RSA_WITH_AES_256_CBC_SHA,
+               tls.TLS_RSA_WITH_AES_128_CBC_SHA256,
                tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
                tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
                tls.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
```

**Comment by dmitris** [comment]
With the change https://golang.org/cl/42510 imported into go master, getting a different, expected error on the test program: 
```
2017/05/03 12:50:19 open cert.pem: no such file or directory
exit status 1
```

**Comment by dmitris** [comment]
@bradfitz - should I make another change to import the current x/net into stdlib's net/http (h2_bundle.go), or does it happen automatically at some point?  When I run `go generate`, I'm getting a generated file where all references to the current `http` package are prepended with `http.` - https://github.com/dmitris/go/compare/master...tlscerts - am I doing something wrong with the `go generate` invocation?

**Comment by bradfitz** [comment]
@dmitris, I already sent you the CL. You can approve https://go-review.googlesource.com/c/42494/
