### ISSUE TITLE
database/sql: cherry-pick CL 42139 to Go 1.8 branch?

### ISSUE THREAD

**Issue by freedombird9** [golang/go#20217]
@kardianos Hi,  I wonder when Commit 2133d63 is planned to be merged to release 1.8?  I'm also experiencing this issue in many of our programs due to a recent upgrade to Go 1.8.1. Thanks.

**Comment by ALTree** [comment]
I see no indication on the CL, in the issue it fixes or in the github milestone that the patch is being considered for inclusion in go1.8.2.

Are you requesting the inclusion of the patch in go1.8.2?

**Comment by bradfitz** [comment]
@kardianos, is this something that qualifies for a minor release cherrypick?

**Comment by kardianos** [comment]
This is not a security issue. It may cause a panic.

Regardless, in the meantime if this affects you, you can vendor database/SQL and database/sql/driver and apply the patch locally.

It is a one line patch.

**Comment by bradfitz** [comment]
That's a lot of work for a user to do to fix a panic.

Are you comfortable with the patch being backported to 1.8.x? It looks small at least.

**Comment by kardianos** [comment]
Yep. It would need to be a new CL. I'll get one ready in case of a 1.8.2.

**Comment by freedombird9** [comment]
A coworker once played around with the Go runtime and it's a pain in the ass to compile it, took a long time to figure out how to build it properly.

**Comment by kardianos** [comment]
@freedombird9 You wouldn't need to compile it, just copy (database/sql and database/sql/driver) in to the vendor folder. But a CL is coming.

**Comment by bradfitz** [comment]
@freedombird9, you just run "./make.bash" in the "src" directory and wait about 45 seconds. This is all documented at https://golang.org/doc/install/source

**Comment by freedombird9** [comment]
Sounds easy enough. You know when it's gonna released to 1.8.2? If soon, I'll probably just wait and won't bother to build a docker image out of it myself.
