### ISSUE TITLE
cmd/internal/obj/x86: backport "cmd/internal/obj/x86: use LEAx rather than ADDx" to 1.8 branch

### ISSUE THREAD

**Issue by mwhudson** [golang/go#20226]
Backport golang.org/cl/41821 to 1.8 branch

This fixes an issue with shared libraries / plugins on 386.

(Hope I'm doing this right)

**Comment by bradfitz** [comment]
I don't think this qualifies for a Go 1.8 backport.

a) there wasn't even a bug for https://golang.org/cl/41821
b) and it was never declared whether this was a regression from Go 1.7.
c) there was never a test

Feel free to disagree.

/cc @broady

**Comment by mwhudson** [comment]
I didn't file a bug because I found the fix before I got around to filing the bug. It is a regression from 1.7. It is an issue that I don't know how to write a test.

(I've been on leave, hence the late reply).

**Comment by rsc** [comment]
There really should be a bug and a test but I trust the CL since it went through the Go 1.9 release process. 

CL 41821 OK for Go 1.8.5.

**Comment by rsc** [comment]
CL 41821 does not apply.
CL 70871 OK for Go 1.8.5.

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 70871](https://golang.org/cl/70871) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:48 UTC
