### ISSUE TITLE
x/build: don't run racecompiler builder if commit doesn't include -c change

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20222]
We shouldn't run the racecompiler builder if the commit being tested isn't a descendent of 22f1b56dab29d397d2bdbdd603d85e60fb678089

(Noticed from a Go 1.8 release branch trybot failure: https://go-review.googlesource.com/c/42532/ failed with: https://storage.googleapis.com/go-build-log/c8c86992/linux-amd64-racecompile_6fb68b46.log)

/cc @josharian @kardianos

**Comment by bradfitz** [comment]
(The issue adding the racecompile builder was #19962)

**Comment by josharian** [comment]
You can use git merge-base --is-ancestor. merge-base docs: https://git-scm.com/docs/git-merge-base
