### ISSUE TITLE
go/types: missing err message in "could not import" error

### ISSUE THREAD

**Issue by josharian** [golang/go#20230]
Using `importer.Default`, run go/types on:

```go
package p

import "t"
```

Result:

```
	x.go:3:8: could not import t (can't find import: )
```

Seems like there is something missing before the closing parens.

Discovered (by accident) by go-fuzz.

@griesemer

**Comment by stemar94** [comment]
In go/internal/gcimporter/gcimporter.go line 46 function FindPkg returns before setting the return variable id string, which is later used for the error message.
Thats what I found out, but I don't know, what the correct behavior or output should be. Maybe it is as simple as setting id before exiting.

**Comment by stemar94** [comment]
also see https://github.com/golang/go/issues/14215

**Comment by griesemer** [comment]
@stemar94 Setting the id is good enough.
