### ISSUE TITLE
image/gif: EncodeAll panics when a palette is too large to encode

### ISSUE THREAD

**Issue by pivotal-topher-bullock** [golang/go#20249]
### What version of Go are you using (`go version`)?
`1.8.1`

### What operating system and processor architecture are you using (`go env`)?
darwin / amd64

### What did you do?
Created a gif image with a palette ( either global or local color table for a frame ) containing > 256 colors.

https://play.golang.org/p/xfDZCcSIFF 

### What did you expect to see?
The `EncodeAll` function returns errors when image blocks are too large, on a zero-length gif, etc. As such, in this case since we know the gif can't be encoded due to the palette length being > 256, I would expect a similar error, along the lines of `errors.New("gif: image palette is too large to encode")` to match the style [here](https://github.com/golang/go/blob/master/src/image/gif/writer.go#L194)

### What did you see instead?
It panics [here](https://github.com/golang/go/blob/master/src/image/gif/writer.go#L165) trying to read `log2Lookup[-1]` [defined here](https://github.com/golang/go/blob/master/src/image/gif/writer.go#L25-L34)

I have a change-set ready with the proposed functionality and accompanying tests.

**Comment by bradfitz** [comment]
Go 1.9 is fine too if trivial/safe.

/cc @nigeltao

**Comment by pivotal-topher-bullock** [comment]
@gopherbot Ah, okay. Welp, that looks a lot like what I was going to submit, so LGTM :D

**Comment by nigeltao** [comment]
Ah, I didn't read your final line that said you had a change-set ready. Sorry.

**Comment by pivotal-topher-bullock** [comment]
@nigeltao No worries 😄
