### ISSUE TITLE
x/mobile: go_seq_go_to_refnum on objective-c objects is not permitted

### ISSUE THREAD

**Issue by karalabe** [golang/go#20254]
We've received a [bug report](https://github.com/ethereum/go-ethereum/issues/14421) that recently (2+ weeks at least) iOS builds have been erroring out with a strange error. Any ideas about it?

```
* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'go_seq_go_to_refnum on objective-c objects is not permitted'
```

**Comment by sashabaranov** [comment]
Also experiencing this

**Comment by ArEnSc** [comment]
I don’t understand how this works can you clearify ? With a full example ?

**Comment by zgramana** [comment]
I noticed the error when I implemented the generated class declared by gomobile from my Go interface which included the `_ref` property. When I declared my own class and implemented the protocol which mapped directly to my Go interface (without `_ref`) it worked as expected.

**Comment by gabriel** [comment]
You can't use alloc/init to make a go struct.. You have to create a constructor in go code and call that.

```objc
MyObject* obj = [[MyObject alloc] init];
```

Yes:
```go
func NewMyObject() *MyObject {
  return &MyObject{...}
}
```

```objc
MyObject* obj = TheFrameworkNewMyObject();
