### ISSUE TITLE
net/http: client do not set Content-Length: 0 with an io.Reader with no bytes.

### ISSUE THREAD

**Issue by SunRunAway** [golang/go#20257]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

I called http.NewRequest and explicitly set req.ContentLength to 0.

```go
package main

import (
	"io"
	"log"
	"net/http"
	"os"
)

type nilbody struct{}

func (nilbody) Read(p []byte) (int, error) {
	return 0, io.EOF
}

func main() {
	body := nilbody{}
	req, err := http.NewRequest("POST", "http://httpbin.org/post", body)
	if err != nil {
		log.Fatal(err)
	}
	req.ContentLength = 0
	resp, _ := http.DefaultClient.Do(req)
	io.Copy(os.Stdout, resp.Body)
}
```

### What did you expect to see?

server should get a header with Content-Length: 0

### What did you see instead?

With go1.8.1, server get a chunked request body, but older version get a explicit Content-Length header.

```bash
[sunrunaway:/tmp]$ go run nilbody.go
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "Transfer-Encoding": "chunked", 
    "User-Agent": "Go-http-client/1.1"
  }, 
  "json": null, 
  "origin": "180.168.57.238", 
  "url": "http://httpbin.org/post"
}
[sunrunaway:/tmp]$ /usr/local/Cellar/go/1.7.3/bin/go run nilbody.go 
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Connection": "close", 
    "Content-Length": "0", 
    "Host": "httpbin.org", 
    "User-Agent": "Go-http-client/1.1"
  }, 
  "json": null, 
  "origin": "180.168.57.238", 
  "url": "http://httpbin.org/post"
}
```

I know this is documented that 'a value of 0 means unknown if Body is not nil', but could it be possible to do some fix and not break our old code.

**Comment by bradfitz** [comment]
Use nil or the new Go 1.8 http.NoBody to send a Content-Length of 0 if your peer is sensitive to the difference between chunked zero and content-length zero.

This was intentionally changed during Go 1.8.

See https://golang.org/doc/go1.8#net_http

Some background can be found in git log (search for NoBody) or starting from b992c391d4aae64e147fc64c77ad41d61be8e2e7 and https://golang.org/cl/31445 and #17480 and #17071

**Comment by SunRunAway** [comment]
This changes breaks our code in many places.

We have many interface like below, and every implement with http package should be fixed up for the compatibility unless we know exactly which server is sensitive to the explicit content-length.

```go
type Sender interface {
    Send(r io.Reader, n int64)
}
```

Is it a good change for the go1 compatibility?

**Comment by bradfitz** [comment]
@SunRunAway, we considered this a lot during the past cycle, weighing various trade-offs. In the end we decided this was the best thing to do. If you want to be involved in such decisions in the future, please test the beta & rc releases. That's when we can still make changes. Now that Go 1.8 is out, things aren't changing.
