### ISSUE TITLE
cmd/cgo: #include relative to current directory broken since Go 1.8

### ISSUE THREAD

**Issue by gooid** [golang/go#20266]
### What version of Go are you using (`go version`)?
go version devel +4b2f7b4 Sat May 6 01:28:38 2017 +0000 windows/amd64

### What did you do?
main.go 
```
package main

//#cgo CFLAGS: -Iinc
//#include "foo.h"
import "C"

func main() {
	println(C.FOO)
}
```
inc\foo.h
```
#define FOO	5
```

go build main.go
.\main.go:4:10: fatal error: foo.h: No such file or directory
 //#include "foo.h"
          ^~~~~~~
compilation terminated.

**Comment by davecheney** [comment]
Put main.go into a package a use

go build github.com/you/yourproject

To build the package, rather than the file.

Explanation: when you involve go build (or run, or text) with a set of
file, rather than a package, the source code is compiled in a synthetic
package constructed in /tmp, which is why the file foo.h is not found.

**Comment by bradfitz** [comment]
If Go 1.8 is okay and tip is not, though, I want to make sure this was intentional.

/cc @rsc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Works for me using both Go 1.8 and Go 1.9.

For the failing case please show us the output of `go build -x main.go`.

**Comment by alexbrainman** [comment]
> please show us the output of go build -x main.go.

Fails for me on the tip on both windows-amd64 and linux-amd64:

```
c:\Users\Alex\dev\src\issues\issue20266>dir
 Volume in drive C has no label.
 Volume Serial Number is F0C8-6DFE

 Directory of c:\Users\Alex\dev\src\issues\issue20266

07/05/2017  11:40 AM    <DIR>          .
07/05/2017  11:40 AM    <DIR>          ..
07/05/2017  11:40 AM    <DIR>          inc
07/05/2017  11:38 AM               105 main.go
               1 File(s)            105 bytes
               3 Dir(s)  82,081,398,784 bytes free

c:\Users\Alex\dev\src\issues\issue20266>type main.go
package main

//#cgo CFLAGS: -Iinc
//#include "foo.h"
import "C"

func main() {
        println(C.FOO)
}
c:\Users\Alex\dev\src\issues\issue20266>type inc\foo.h
#define FOO     5

c:\Users\Alex\dev\src\issues\issue20266>go version
go version devel +5300362 Sun May 7 01:26:02 2017 +0000 windows/amd64

c:\Users\Alex\dev\src\issues\issue20266>go build -x
WORK=C:\Users\Alex\AppData\Local\Temp\go-build643016190
mkdir -p $WORK\issues\issue20266\_obj\
mkdir -p $WORK\issues\issue20266\_obj\exe\
cd c:\users\alex\dev\src\issues\issue20266
CGO_LDFLAGS="-g" "-O2" "c:\\users\\alex\\dev\\go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\" -importpath issues/issue20266 -- -I "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\" -g -O2 -Iinc main.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd $WORK\issues\issue20266\_obj
gcc -I "c:\\users\\alex\\dev\\src\\issues\\issue20266" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\" -g -O2 -Iinc -o "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\_cgo_export.o" -c _cgo_export.c
gcc -I "c:\\users\\alex\\dev\\src\\issues\\issue20266" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\" -g -O2 -Iinc -o "C:\\Users\\Alex\\AppData\\Local\\Temp\\go-build643016190\\issues\\issue20266\\_obj\\main.cgo2.o" -c main.cgo2.c
# issues/issue20266
.\main.go:4:17: fatal error: foo.h: No such file or directory
compilation terminated.

c:\Users\Alex\dev\src\issues\issue20266>
```
Alex

**Comment by hirochachacha** [comment]
It seems that https://github.com/golang/go/commit/8ae60dc1bb5183a8e8cd1fe86985ca354904447f is the cause.
https://github.com/golang/go/commit/8ae60dc1bb5183a8e8cd1fe86985ca354904447f converts `-o relpath` to `-o abspath`.
But it doesn't handle `-I relpath` and `-L relpath` well.

**Comment by ianlancetaylor** [comment]
Oh, I see.  It should work to write

`-I ${SRCDIR}/inc`

See https://golang.org/cmd/cgo/ .

I'm not sure whether we have introduced a new bug or whether your code is relying on undocumented behavior.  I mean, you are definitely using undocumented behavior, and there is a documented workaround, but if a lot of people do what you are doing then perhaps we shouldn't change it.

**Comment by aarzilli** [comment]
> you are definitely using undocumented behavior, and there is a documented workaround

what's the documented workaround? Using `go build pathtopackage`, like @davecheney said, doesn't work either, at least not for me.

**Comment by davecheney** [comment]
What didn't work? Could you show what you tried and what happened what you
did, please.

**Comment by aarzilli** [comment]
@davecheney never mind, I didn't read all of @ianlancetaylor's message.

**Comment by rsc** [comment]
This worked as recently as Go 1.8. Seems like we should keep it working for Go 1.9.
