### ISSUE TITLE
cmd/compile: code inside unsafe.Sizeof expression not evaluated

### ISSUE THREAD

**Issue by josharian** [golang/go#20262]
https://play.golang.org/p/5VUF7XrYjp

```go
package main

import (
	"unsafe"
)

var x int

const sz = unsafe.Sizeof(func() int { x++; return 0 }())

func main() {
	println(x)
}
```

My reading of the spec says this should print 1, but it prints 0.

Relevant bits of the spec:

> The functions Alignof and Sizeof take an expression x of any type and return the alignment or size, respectively, of a hypothetical variable v as if v was declared via var v = x.

So we should be evaluating the function expression, as if it were the RHS of an expression, at which point const sz should be evaluated before var x, thus incrementing x.

Seems low priority. If we investigate fixing, we should test handling of iota inside function bodies.

Related: #20260

**Comment by griesemer** [comment]
Closing as dup of #12946.
