### ISSUE TITLE
cmd/vet: copylock false positive where sync.Mutex gets immediately reassigned on the following line

### ISSUE THREAD

**Issue by kevinburke** [golang/go#20261]
Here's some code that triggers an error in `go vet` (initially found in go-mgo/mgo#435):

```go
	scopy := *session
	scopy.m = sync.RWMutex{}
	scopy.creds = creds
	s = &scopy
```

Basically, give me a new object that has all of the same fields as the old one, minus these two that I want to give new values to. This triggers a vet error:

```
session.go:555: assignment copies lock value to scopy: mgo.Session contains sync.RWMutex
```

You can see it gets overwritten on the next line. Since `scopy` is only live in the function, the code seems like it's correct.

We could copy over all of the fields in the struct, but that would be cumbersome as it's pretty large.

```go
type Session struct {
	m                sync.RWMutex
	cluster_         *mongoCluster
	slaveSocket      *mongoSocket
	masterSocket     *mongoSocket
	slaveOk          bool
	consistency      Mode
	queryConfig      query
	safeOp           *queryOp
	syncTimeout      time.Duration
	sockTimeout      time.Duration
	defaultdb        string
	sourcedb         string
	dialCred         *Credential
	creds            []Credential
	poolLimit        int
	bypassValidation bool
}
```

Wondering if you had thoughts here.

**Comment by josharian** [comment]
Yes, that's a false positive. Fixing vet would involve doing some non-trivial analysis, which I'm not sure we want to do (?). I don't see a workaround other than copying over all the fields in the struct (probably inside a helper method).

cc @robpike @valyala in case they have ideas

**Comment by cespare** [comment]
You can change the Session type by putting most of its fields (but not m) in a nested struct. See the fix for the same issue in Regexp.Copy: https://go-review.googlesource.com/c/20841/.

**Comment by cespare** [comment]
By the way, I wrote this exact same kind of code originally for Regexp.Copy in https://go-review.googlesource.com/c/16110 and the consensus of the discussion in https://go-review.googlesource.com/c/20841 seemed to be that it's not actually safe. (Or at least, the race detector will complain.) So I don't think it's just a vet issue.

**Comment by cespare** [comment]
Perhaps the reasoning is: `*session` reads the mutex possibly concurrent to some write (e.g. Lock) and that's a race even if the result of the read isn't observed.

**Comment by valyala** [comment]
IMHO, the copylock check works as intended in this case due to the reason @cespare mentioned above

**Comment by robpike** [comment]
I agree, you're copying a lock and that's what it's complaining about.

The simplest workaround would be to make m a pointer, and then say

scopy := *session
scopy.m = &sync.RWMutex{}

although that does allocate more. Alternatively, copy all fields but the mutex in a copy method.
