### ISSUE TITLE
x/tools/cmd/guru: panic after 39 minutes of pointer analysis

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#20279]
go version devel +d5dc490 Thu Mar 16 02:44:16 2017 +0000 linux/amd64
golang.org/x/tools version 9862c35773a14ca029b7da49c410111ba13830a0

with github.com/juju/juju at 223b8db274268e2ae655a71d4596f2a8f981344a.
To reproduce:

     go get -d github.com/juju/juju
     git checkout 223b8db274268e2ae655a71d4596f2a8f981344a
     cd $GOPATH/src/github.com/juju/juju
     go get github.com/rogpeppe/godeps
     godeps -u dependencies.tsv
     guru -scope github.com/juju/juju/... callers ./api/controller/controller.go:#7425,#7425

I got this result:

	Internal panic in pointer analysis:
	goroutine 1 [running]:
	runtime/debug.Stack(0x24, 0x0, 0x0)
		/home/rog/go/src/runtime/debug/stack.go:24 +0x79
	runtime/debug.PrintStack()
		/home/rog/go/src/runtime/debug/stack.go:16 +0x22
	golang.org/x/tools/go/pointer.Analyze.func1(0xc420bc5c00)
		/home/rog/src/go/src/golang.org/x/tools/go/pointer/analysis.go:227 +0x124
	panic(0x71bde0, 0xc5503766d0)
		/home/rog/go/src/runtime/panic.go:489 +0x26a
	golang.org/x/tools/go/ssa.(*Program).LookupMethod(0xc46f403220, 0x94f3e0, 0xc4b5159ad0, 0x0, 0x796a15, 0x5, 0x64)
		/home/rog/src/go/src/golang.org/x/tools/go/ssa/methods.go:49 +0x1f3
	golang.org/x/tools/go/pointer.(*invokeConstraint).solve(0xc4ec901e70, 0xc4b4f18700, 0xc60125a800)
		/home/rog/src/go/src/golang.org/x/tools/go/pointer/solve.go:326 +0x11a
	golang.org/x/tools/go/pointer.(*analysis).solveConstraints(0xc4b4f18700, 0xc4d4c8cae0, 0xc60125a800)
		/home/rog/src/go/src/golang.org/x/tools/go/pointer/solve.go:165 +0x14e
	golang.org/x/tools/go/pointer.(*analysis).solve(0xc4b4f18700)
		/home/rog/src/go/src/golang.org/x/tools/go/pointer/solve.go:59 +0x2ed
	golang.org/x/tools/go/pointer.Analyze(0xc4851f30e0, 0x0, 0x94d6a0, 0xc5503766e0)
		/home/rog/src/go/src/golang.org/x/tools/go/pointer/analysis.go:331 +0x5da
	main.ptrAnalysis(0xc4851f30e0, 0xc4988b4000)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/guru.go:316 +0x2b
	main.callers(0xc4200d0230, 0x7, 0x797178)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/callers.go:72 +0x5c6
	main.Run(0x7fffc459ef65, 0x7, 0xc4200d0230, 0x1, 0xc4200d4200)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/guru.go:88 +0x3b5
	main.main()
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/main.go:212 +0x3c8
	panic: internal error in pointer analysis: *github.com/juju/juju/state/multiwatcher.MachineInfo has no method Error (please report this bug)
	
	goroutine 1 [running]:
	main.ptrAnalysis(0xc4851f30e0, 0xc4988b4000)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/guru.go:318 +0x62
	main.callers(0xc4200d0230, 0x7, 0x797178)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/callers.go:72 +0x5c6
	main.Run(0x7fffc459ef65, 0x7, 0xc4200d0230, 0x1, 0xc4200d4200)
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/guru.go:88 +0x3b5
	main.main()
		/home/rog/src/go/src/golang.org/x/tools/cmd/guru/main.go:212 +0x3c8
	Command exited with non-zero status 2
	2622.37user 18.06system 38:50.13elapsed 113%CPU (0avgtext+0avgdata 8532512maxresident)k
	77808inputs+1336outputs (6191major+3478260minor)pagefaults 0swaps

**Comment by dsnet** [comment]
\cc @alandonovan

**Comment by adonovan** [comment]
x/tools/go/pointer was deleted; see #59676.
