### ISSUE TITLE
fatal error: concurrent map read and map write  - by high traffic

### ISSUE THREAD

**Issue by i5heu** [golang/go#20270]
Hi,
if i run my code and benchmark it with apachebench this error (error is unter Title error) appears.
[CODE](https://github.com/i5heu/wiki_cannon/tree/973496cee231b9c41e7db101a7dbe09d3c618fdb)
the main func is in [wikicannon.go](https://github.com/i5heu/wiki_cannon/blob/973496cee231b9c41e7db101a7dbe09d3c618fdb/wikicannon.go)
and i have testet this problem with the [DesktopHandler](https://github.com/i5heu/wiki_cannon/blob/973496cee231b9c41e7db101a7dbe09d3c618fdb/wc-desktop.go) function 

yes i know the code is creepy but it should work, so maybe this is a bug?

#### thanks 4 your time and work, golang is awesome!

# go version
`go version go1.8.1 linux/amd64
`

# go env
```
GOARCH="amd64"
GOBIN="/home/her/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/her/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build917169791=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

# ERROR
```
START
fatal error: concurrent map read and map write

exit status 2
1: running [Created by http.(*Server).Serve @ server.go:2668]
    runtime   panic.go:596                throw(0x827a3a, 0x21)
    runtime   hashmap_fast.go:217         mapaccess1_faststr(*maptype(0x7af4a0), *hmap(0xc42018b0e0), string(#4, len=13), 0xc420416bb0)
    main      wc-tool.go:85               timer(string(#4, len=13), 0x8)
    main      wc-desktop.go:28            DesktopHandler(ResponseWriter(0x9d2e80), *Request(#1))
    http      server.go:1942              HandlerFunc.ServeHTTP(ResponseWriter(0x832d48), *Request(#2), #1)
    http      server.go:2238              (*ServeMux).ServeHTTP(*ServeMux(0xa04c20) ...
```

[err.txt](https://github.com/golang/go/files/981155/err.txt)

**Comment by cznic** [comment]
> fatal error: concurrent map read and map write

The error is caused by a data race. Please try to pin-point the cause using the -race option. That will hopefully indicate the exact place of the bug.

**Comment by i5heu** [comment]
error with -race option:


[err2.txt](https://github.com/golang/go/files/981161/err2.txt)
`START
==================
WARNING: DATA RACE
Read at 0x00c4201af560 by goroutine 23:
  runtime.mapaccess1_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:208 +0x0
  main.timer()
      /home/her/CODE/wiki_cannon/wc-tool.go:85 +0x74
  main.DesktopHandler()
      /home/her/CODE/wiki_cannon/wc-desktop.go:28 +0x15d
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1825 +0x71a

Previous write at 0x00c4201af560 by goroutine 22:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:485 +0x0
  main.timer()
      /home/her/CODE/wiki_cannon/wc-tool.go:86 +0x240
  main.DesktopHandler()
      /home/her/CODE/wiki_cannon/wc-desktop.go:28 +0x15d
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1825 +0x71a
`

**Comment by cznic** [comment]
The above seems to suggests the date race is in user code.

**Comment by tzneal** [comment]
As @cznic indicated, there's a data race in your code. Specifically on the global timemap in your wc-tool.go See https://blog.golang.org/race-detector
