### ISSUE TITLE
x/net/http2: bidirection streams, let HTTP/2 server send response once it receives request header.

### ISSUE THREAD

**Issue by JimmyCYJ** [golang/go#20287]
I am trying to set up a test environment client--HTTP/2-->proxy--HTTP/2-->server.  The client sends a POST request that contains a large body, and the response also contains a large body. I need the server to start sending response as soon as it receives POST request header, so that both sides are sending data to each other concurrently. Is it possible to add a function into server to support sending early response?

@bradfitz

**Comment by bradfitz** [comment]
This already works. See #13444 etc. In particular https://github.com/golang/go/issues/13444#issuecomment-161115822 has a demo.

There's a live demo at https://http2.golang.org/ (see the /ECHO handler linked there) that streams its input back capitalized.

That demo code is https://github.com/golang/net/blob/master/http2/h2demo/h2demo.go (search for "echo").
