### ISSUE TITLE
cmd/go: TestExecutableGOROOT fails if GOROOT_FINAL is set

### ISSUE THREAD

**Issue by mwhudson** [golang/go#20284]
### What version of Go are you using (`go version`)?

$ ../bin/go version
go version devel +88672de Mon May 8 19:52:30 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux/amd64 but it doesn't really matter here.

### What did you do?

$ GOROOT_FINAL=/foobar ./all.bash

### What did you expect to see?

Tests passing.

### What did you see instead?

--- FAIL: TestExecutableGOROOT (0.05s)
	go_test.go:3974: copied go tool failed exit status 2: go: cannot find GOROOT directory: /foobar
FAIL
FAIL	cmd/go	51.515s

I think this is the

{{{
	// Missing GOROOT/pkg/tool, the go tool should fall back to
	// its default path.
}}}

case from the test. The nature of the failure makes me wonder if it is really testing what it thinks it's failing though. cc @crawshaw

**Comment by bradfitz** [comment]
Reopening for Go 1.10, since the test still fails when @broady runs cmd/release.

**Comment by ptribble** [comment]
I'm seeing this (or something close) fail for 1.9beta2 (and 1.9beta1). This is on solaris_amd64 but that shouldn't make any difference.

GOROOT_BOOTSTRAP=/usr/versions/go-1.8 GOROOT_FINAL=/usr/versions/go-1.9 ./all.bash

results in

--- FAIL: TestExecutableGOROOT (0.09s)
    --- FAIL: TestExecutableGOROOT/RelocatedExe (0.01s)
    	go_test.go:4047: /tmp/gotest187550508/new/bin/go env GOROOT: exit status 2, go: cannot find GOROOT directory: /usr/versions/go-1.9

**Comment by davecheney** [comment]
If it's any consolation, you do not need to set GOROOT_FINAL any more,
even when moving your go install after building it

zapf(~/go/src) % mktemp -d
/var/folders/lv/028ssy8n19v56_k2q43kkb5r0000gn/T/tmp.UkpoJoSu
zapf(~/go/src) % cd
zapf(~) % cp -rp go/*
/var/folders/lv/028ssy8n19v56_k2q43kkb5r0000gn/T/tmp.UkpoJoSu
zapf(~) % /var/folders/lv/028ssy8n19v56_k2q43kkb5r0000gn/T/tmp.UkpoJoSu/bin/go
env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dfc"
GORACE=""
GOROOT="/var/folders/lv/028ssy8n19v56_k2q43kkb5r0000gn/T/tmp.UkpoJoSu"
GOTOOLDIR="/Users/dfc/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics
-Qunused-arguments -fmessage-length=0
-fdebug-prefix-map=/var/folders/lv/028ssy8n19v56_k2q43kkb5r0000gn/T/go-build158555772=/tmp/go-build
-gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by ptribble** [comment]
Ah. That does appear to be the case.

So perhaps the installation instructions and/or release notes need to be updated?

**Comment by bradfitz** [comment]
We need to disable that test for Go 1.9. Will send a CL.

**Comment by rsc** [comment]
You _do_ need to set GOROOT_FINAL in order to get the right default value for runtime.GOROOT.
