### ISSUE TITLE
text/scanner parses numbers strangely

### ISSUE THREAD

**Issue by skybrian** [golang/go#20292]
### What version of Go are you using (`go version`)?

go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

MacOS 10.12.4

### What did you do?

Parse "1.2.3"

Example code:

```
https://play.golang.org/p/Hyvni1JdC_
```

### What did you expect to see?

Expected Scan() to return a single characters for '1' and '.', since it's not a valid number.

### What did you see instead?

It's parsed as two valid number tokens, 1.2 and .3

It seems that for number-like tokens, Scan() quits early before reading the entire token.

If the algorithm can't be changed, perhaps update the docs? It should explain that the caller has to handle this case by checking that there is whitespace between two consecutive number tokens.

**Comment by griesemer** [comment]
This is working as expected. Scan() doesn't "quit early", it reads the longest sequence of characters that makes a valid token and then returns that token. The first longest valid sequence of characters is "1.2" since anything longer is invalid. The next longest sequence is ".3". Hence you get two tokens, exactly as desired.

Note that the Go compiler behaves the same way: https://play.golang.org/p/XYkbgQLp04 correctly reads the first token 1.2 and then sees an unexpected 1.3. This is standard behavior for programming language scanners.

**Comment by skybrian** [comment]
Okay, thanks!

FYI, I'm attempting to scan a space-separated list of items (like in Lisp). It seems I'll have to write my own code to match whitespace.

**Comment by griesemer** [comment]
@skybrian You don't if you have in fact a space-separated list. Only if you want to recognize `1.2.3` as a single yet invalid token. Also, if you're actually trying to parse Lisp expressions, the dot has special meaning and will require spaces around it in many cases anyway. Finally, `text/scanner` allows you to look at the character after a token, so if you got `1.2` that is not followed by a blank but by a `.` (from the `.3`) your parser could complain. I've used text/scanner successfully for Lisp-like input.

**Comment by griesemer** [comment]
@skybrian Finally, you can customize `text/scanner` in various ways, including which tokens should be recognized or not and what is considered whitespace.

**Comment by skybrian** [comment]
This probably should be a separate issue but I'll ask here first: it seems that text/scanner makes it easy to get the position at the end of the current token (by calling Position) but getting the position at the start of the current token (which is just as likely to be needed when reporting an error) is harder. If the scanner skipped whitespace, saving the previous position won't help.

I suppose I could call TokenText(), count the runes, and subtract the length, but it seems fiddly. Perhaps better done inside Scanner?

**Comment by griesemer** [comment]
@skybrian https://golang.org/pkg/text/scanner/#Scanner contains the position of the most recently scanned token

**Comment by skybrian** [comment]
@griesemer It contains the position of the end of the token, not the start of the token. There's a difference.

**Comment by griesemer** [comment]
@skybrian No. Scanner.Position contains the start position of the most recently scanned token. Scanner.Pos() returns the end. The example (https://golang.org/pkg/text/scanner/#pkg-examples) is incorrect. Will file an issue.

**Comment by griesemer** [comment]
@skybrian See https://golang.org/cl/43450 for the fixed example. Please refer to golang-nuts etc. for further discussions on the use of text/scanner. Thanks.
