### ISSUE TITLE
test: chan/select3.go build failure on linux-386-387 

### ISSUE THREAD

**Issue by josharian** [golang/go#20299]
https://build.golang.org/log/5eddfcb8a4f68a2d3e1b2cbaddcacdc83d37ce5f

One and only failure; occurred first after CL 41820 (enabling concurrent compilation). Investigating.

**Comment by josharian** [comment]
```
##### ../test
# go run run.go -- chan/select3.go
exit status 1
panic: function did block

goroutine 1 [running]:
main.testBlock(0x80a9dd4, 0xc, 0x80ae3c8)
	/tmp/workdir/go/test/chan/select3.go:50 +0x140
main.main()
	/tmp/workdir/go/test/chan/select3.go:153 +0x34b
exit status 2

FAIL	chan/select3.go	1.843s
```

**Comment by josharian** [comment]
I've been running select3.go in a loop on a gomote for the last two hours. No failures. Reading the code for this particular test, I notice that it depends on timing:

```go
func testBlock(signal string, f func()) {
	c := make(chan string)
	go func() {
		f()
		c <- never // f didn't block
	}()
	go func() {
		time.Sleep(1e8) // 0.1s seems plenty long
		c <- always     // f blocked always
	}()
	if <-c != signal {
		panic(signal + " block")
	}
}
```

Maybe due to other noise on the machine, 0.1s wasn't plenty long enough. Maybe concurrent compilation, which generally uses CPU more intensely, increased the noise and contributed.

Out of ideas, and can't reproduce. Going to wait to see whether it occurs again.

**Comment by josharian** [comment]
It is possible that #20250 isn't just a pessimization but is the source of a real problem. It does affect package cmd/link/internal/ld.

**Comment by josharian** [comment]
I've been running this in a loop again and still can't get a failure. I'm hesitant to bump up the blocking time, since the test takes 10*sleeptime to run, and we've only seen a single failure, ever.

I'm going to close this as not worth more effort; if it happens again, we can re-open and bump up the timeout and/or investigate.

**Comment by ianlancetaylor** [comment]
It happened again: https://storage.googleapis.com/go-build-log/0a0e8fbd/linux-386_56a2d1b0.log .

**Comment by josharian** [comment]
I think the most likely culprit here is CPU availability / scheduling. We could refactor the test so that all "should block" cases happen concurrently and bump up the timeout. Objections to that?

**Comment by bradfitz** [comment]
No objections. You have time to do that, @josharian?

**Comment by josharian** [comment]
I'll try to make time, but I'm at a family reunion / on vacation for the next two weeks. If it is important or time critical, someone else should step in.
