### ISSUE TITLE
cmd/internal/obj/x86: add ADDSUBPS/PD

### ISSUE THREAD

**Issue by dlespiau** [golang/go#20293]
I'm going through extensions 1 by 1 fixing little things here and there, this time it's SSE3 turn. Only a couple of instructions were missing: ADDSUBPS and ADDSUBPD.

While finding what's missing or not tested [is automated](https://github.com/dlespiau/x86db), generation of the Optab entries isn't (yet!).

```
$ x86db-gogen list --extension SSE3 --not-known
ADDSUBPD xmmreg,xmmrm [rm: 66 0f d0 /r] PRESCOTT,SSE3,SO
ADDSUBPS xmmreg,xmmrm [rm: f2 0f d0 /r] PRESCOTT,SSE3,SO
```

**Comment by Quasilyte** [comment]
Is there a reason CL42990 is not merged yet?
With this one inside, I believe whole SSE will be complete [with exceptions of some MMX instructions].
CC @TocarIP
