### ISSUE TITLE
cmd/compile: "import path contains space character" for imports without spaces

### ISSUE THREAD

**Issue by griesemer** [golang/go#20306]
`cmd/compile` complains if an import path contains a space character. More so, it also complains if a package path (import path after resolving it) contains a space character. This seems overly zealous.

For instance, for a small experiment, I had put two .go files `main.go` and `lib.go` in a local directory that happens to be under my `Google Drive` directory, with the `main` package containing the local import `"./lib"`. Because this resolves to an absolute path containing `"Google Drive"` as a component, the import gets rejected.

It's probably useful to reject arbitrary Unicode spaces, but a regular blank `' '` (0x20) character should be ok. Independent of Google Drive, on OS X it is not uncommon to have blanks in folder names.

**Comment by robpike** [comment]
The spec forbids the import path containing a space and I don't think that should change. What you're asking for is the fully-qualified path name to be allowed to have spaces, and that seems fine.

**Comment by griesemer** [comment]
@robpike Yes, that is what I am asking for.

**Comment by rsc** [comment]
Fixing this (but still disallowing actual imports with actual spaces) seems fine.
