### ISSUE TITLE
os/exec: add convenient, portable way to execute "./foo" (foo in working directory)

### ISSUE THREAD

**Issue by alercah** [golang/go#20308]
`exec.Command` documentation states: "If name contains no path separators, Command uses LookPath to resolve name to a complete path if possible. Otherwise it uses name directly as Path."

`filepath.Join` documentation states: "Join calls Clean on the result"

`filepath.Clean` documentation states: "2. Eliminate each . path name element (the current directory)."

The result is that the most obvious way to execute a command in the working directory, `exec.Command(filepath.Join(".", cmd))` is buggy. The result of `Join` is just `cmd`, and therefore `exec.Command` will do a `PATH` lookup before running the command.

There are four reasonable workarounds. The first is to specify the "/" explicitly and just write `exec.Command("./" + cmd)` and hope it works. The second is to use `filepath.Separator` manually, writing `exec.Command("." + string(filepath.Separator) + cmd)` which is hideous. The third is to create the `Command` directly. The fourth is to use an absolute path via `filepath.Abs`, but it requires adding an extra error check.

There should be some facility somewhere to let you do this with less of a headache. Whether this is a new method in the filepath package which allows for creation of paths with a leading "./" or a function in exec to create a Command that does not do `PATH` resolution, I don't think it is important.

**Comment by vcabbage** [comment]
What about `filepath.FromSlash("./"+cmd)`?

**Comment by alercah** [comment]
Ooh, missed that one. Still feels a little hacky, but it's better than the others!

**Comment by vcabbage** [comment]
Another option, which I just now noticed, is to create the `*exec.Cmd` without the the use of `exec.Command()`, since the purpose of that function is to resolve the path.

`&exec.Cmd{Path: cmd}`

From https://golang.org/pkg/os/exec/#Cmd:
>         // Path is the path of the command to run.
>         //
>         // This is the only field that must be set to a non-zero
>         // value. If Path is relative, it is evaluated relative
>         // to Dir.
>         Path string
>
>        ...
>
>         // Dir specifies the working directory of the command.
>         // If Dir is the empty string, Run runs the command in the
>         // calling process's current directory.
>         Dir string

**Comment by tejasmanohar** [comment]
Personally, I don't feel like we need a helper function in os/exec that depends on os.Getwd

**Comment by mvdan** [comment]
I've only needed to do this a few times and I just used a full path with a directory like `os.Getwd`. That's at most a few extra lines, and in my opinion it's self-explanatory and simple.

I feel like adding extra API or magic to `os/exec` to avoid a bit of typing is unnecessary.

**Comment by rsc** [comment]
This seems like a non-problem. People can write "./foo", which works everywhere already, or they can use a full path with os.Getwd, as @mvdan suggests. If this really happens a lot, then instead of 

    "." + string(filepath.Separator) + cmd

define

    const dotSlash = "." + string(filepath.Separator)

and write `dotSlash + cmd`.
