### ISSUE TITLE
reflect.ArrayOf(...).String() missing opening square bracket

### ISSUE THREAD

**Issue by cpcallen** [golang/go#20311]
### What version of Go are you using (`go version`)?

go version go1.8.1 darwin/amd64 
plus playground current version ([reported as go1.8](https://play.golang.org/p/1VcPUlPk_3))

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cpcallen/src/go"
GORACE=""
GOROOT="/Users/cpcallen/homebrew/opt/go/libexec"
GOTOOLDIR="/Users/cpcallen/homebrew/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g3/lx1ncp096_z6g_j8ms50jcgm0022ny/T/go-build368613208=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

    fmt.Printf("%s\n", reflect.ArrayOf(3, reflect.TypeOf(0)).String())

[Try it on play.golang.org](https://play.golang.org/p/MMwRTVDTIb).

### What did you expect to see?

    [3]int

### What did you see instead?

    3]int

**Comment by mvdan** [comment]
Confirming on `go version devel +ae373b671f Wed May 10 10:50:40 2017 +0200 linux/amd64`.

**Comment by cpcallen** [comment]
Interestingly, [if the program separately declares a variable of the constructed type the output is as expected](https://play.golang.org/p/nE-1TyMl3R).

I'm pretty sure the problem is something to do with [this conditional in `(t *rtype) String()`](http://localhost:6060/src/reflect/type.go?#L744):

```go
	if t.tflag&tflagExtraStar != 0 {
		return s[1:]
	}
```

But I don't understand enough about the internals of reflect to understand what is going wrong.

**Comment by mvdan** [comment]
Yeah, something is fishy - I think I got to the right fix :) Working on a test, CL incoming soon.

**Comment by mvdan** [comment]
@cpcallen if you're curious, I ran into the same issue when trying to reproduce the bug - sometimes I would get the correct string. This is because the bug only appears when `reflect` creates a new type. If it reuses a cached one, the buggy code doesn't get executed. I made sure to write the test in a way that would not use the cache.
