### ISSUE TITLE
reflect: ArrayOf panics on zero-size elem

### ISSUE THREAD

**Issue by mvdan** [golang/go#20313]
### What version of Go are you using (`go version`)?

Both 1.8.1 and tip affected.

### What operating system and processor architecture are you using (`go env`)?

not relevant

### What did you do?

While working on a test for the fix for #20311, I tried an `ArrayOf(x, TypeOf(T{}))` where T was a zero-size struct.

Play link: https://play.golang.org/p/YERNCUD6ZG

### What did you expect to see?

No panic.

### What did you see instead?

`panic: runtime error: integer divide by zero`

The question is whether this is a documentation issue in reflect (to clarify elem must be of non-zero size), or a bug since it should accept that.

I'm inclined towards the latter since the following is a valid program: https://play.golang.org/p/C2rvlrYjkX

Happy to work on a CL either way.

CC @crawshaw @bradfitz

**Comment by mvdan** [comment]
CL incoming doing the latter, since I've convinced myself.

**Comment by bradfitz** [comment]
If this hasn't affected anybody so far, it's probably not worthy of a backport to 1.8, but seems worth fixing for 1.9.

**Comment by mvdan** [comment]
Agreed - I didn't even know arrays of empty structs were possible. I've used them in maps, though.
