### ISSUE TITLE
misc/cgo: segmentation fault flake on darwin-amd64

### ISSUE THREAD

**Issue by mvdan** [golang/go#20314]
https://storage.googleapis.com/go-build-log/7da47d96/darwin-amd64-10_11_d625077a.log

```
##### Testing race detector
ok  	runtime/race	3.387s
ok  	flag	1.022s
ok  	os	1.087s
ok  	os/exec	3.103s
PASS
scatter = 0x41e9160
hello from C
sqrt is: 0
ok  	_/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/misc/cgo/test	2.608s
ok  	flag	1.081s
ok  	os/exec	3.203s

##### ../misc/cgo/testso

##### ../misc/cgo/testsovar

##### ../misc/cgo/testcarchive
--- FAIL: TestInstall (3.22s)
	carchive_test.go:152: [clang -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/go-build737724035=/tmp/go-build -gno-record-gcc-switches -fno-common -framework CoreFoundation -framework Foundation -I pkg/darwin_amd64 -o ./testp1 main.c main_unix.c pkg/darwin_amd64/libgo.a]
	carchive_test.go:161: 
	carchive_test.go:162: signal: segmentation fault
FAIL
2017/05/10 05:01:02 Failed: exit status 1
```

Seen in https://go-review.googlesource.com/c/43131/, which is a tiny and seemingly safe patch.

/cc @josharian - potentially related to your recent concurrent compiler work, since we haven't seen this flake before.

**Comment by josharian** [comment]
Thanks, @mvdan. Definitely a possibility. There's one known outstanding concurrent compiler issue, which could have caused this--#20250--and an outstanding CL for it (CL 42853). I'd like to get that CL in before burning too many cycles on this.

**Comment by bradfitz** [comment]
@josharian, do you think this was a concurrent compiler bug at the time?

Has anybody seen this more than once? @aclements, could you look at your logs?

**Comment by aclements** [comment]
I don't see this on the dashboard at all: `greplogs -dashboard -E "carchive.*seg"`

**Comment by bradfitz** [comment]
Thanks, Austin. I'll close this for now until it comes up again.
