### ISSUE TITLE
Support registering arbitrary file descriptors with the runtime poller

### ISSUE THREAD

**Issue by DemiMarie** [golang/go#20317]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
    go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/dobenour/go"
    GORACE=""
    GOROOT="/home/dobenour/archives/go"
    GOTOOLDIR="/home/dobenour/archives/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build801431881=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"

### What did you do?
Looked for a way to register an externally-provided `Fd` with the runtime poller.

### What did you expect to see?
Such an API exists

### What did you see instead?
No such API.

In general, file descriptors can appear from sources outside of the standard library (such as C libraries).  So it should be possible to register them with the runtime poller.

**Comment by bradfitz** [comment]
Dup of some of:

#6817.
#7903.
#15021.
#18507.
#19093.
#19098.

/cc @ianlancetaylor
