### ISSUE TITLE
html/template: predefined escaper "html" disallowed in template with no "html"

### ISSUE THREAD

**Issue by bep** [golang/go#20323]
On current tip

```go
package tpl

import (
	"bytes"
	"html/template"
	"testing"
)

func TestDisallowedEscaper(t *testing.T) {
	data := map[string]string{
		"html": "<h1>Hi!</h1>",
	}

	tpl := `{{ .html | print }}`

	var buf bytes.Buffer
	tmpl, err := template.New("").Parse(tpl)
	if err != nil {
		t.Fatal(err)
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		t.Fatal(err)
	}

	if buf.String() != `&lt;h1&gt;Hi!&lt;/h1&gt;` {
		t.Fatalf("Got %q", buf.String())
	}

}
```

Fails with

```
predefined escaper "html" disallowed in template
FAIL
```

This was probably introduced as a fix to #19952 -- and while I do understand the motivation behind the error in _that_ issue, the above example is obviously correct and should just work.

Also note that even if the above example looks constructed, the error comes from a real world application. Having a JSON property named `html` is common enough in the wild, Twitter and Instagram being two examples.

https://github.com/spf13/hugo/issues/3454

**Comment by ianlancetaylor** [comment]
CC @stjj89
