### ISSUE TITLE
cmd/compile: reordering regular loads over atomic add

### ISSUE THREAD

**Issue by aclements** [golang/go#20335]
### What version of Go are you using (`go version`)?
Tested on both `go version go1.8.1 linux/amd64` and `go version devel +8c49c06b48 Mon May 8 15:16:21 2017 +0000 linux/amd64`.

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
`runtime.gchelper` ends with the following few lines:
```go
	nproc := work.nproc // work.nproc can change right after we increment work.ndone
	if atomic.Xadd(&work.ndone, +1) == nproc-1 {
		notewakeup(&work.alldone)
	}
```

### What did you expect to see?
I expected the `atomic.Xadd` to act as a memory fence and force the regular load of `work.nproc` to happen before the atomic.

### What did you see instead?
The compiler reorders the regular load to occur after the `atomic.Xadd`. I believe this is leading to #19305.

/cc @dr2chase @cherrymui

**Comment by randall77** [comment]
Minimal repro:
```
package main

import "sync/atomic"

func f(p, q *int32) bool {
	x := *q
	return atomic.AddInt32(p, 1) == x
}
```
The `*q` occurs after the atomic.  Something is wrong with the schedule pass

```    v9 = XADDLlock <uint32,mem> v12 v7 v1
    v5 = Select0 <uint32> v9
    v14 = Select1 <mem> v9
    v11 = MOVLload <int32> v8 v1
```
There's more than one memory variable live before v11 (v1 and v14).

**Comment by randall77** [comment]
Reopen for 1.8.2.
