### ISSUE TITLE
Slice Syntax Allows Access Beyond Last Item

### ISSUE THREAD

**Issue by theory** [golang/go#20334]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/Users/david/dev/go"
    GORACE=""
    GOROOT="/usr/local/go"
    GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
    GCCGO="gccgo"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zb/_t6g74x117qb5yq9tpqd259r0000gq/T/go-build477207325=/tmp/go-build -gno-record-gcc-switches -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"

### What did you do?

Created a new slice with len 3 and re-sliced it using `[3:]` and got no error.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

No error, more curious as to whether the decision to allow creating a new slice one index beyond the length or capacity of the slice was intentional. In [this playground](https://play.golang.org/p/FufTzT3uWU), note that the length and capacity of the slice are both 3, so the max index should be 2, but I'm able to subspace using `parts[3:]`. Shouldn't that panic? `parts[4:]` does panic. Perhaps this is intentional? If so, should it be documented?

### What did you expect to see?

A panic on slicing one index beyond the length and capacity of the slice.

### What did you see instead?

No panic.

**Comment by cespare** [comment]
The high index of a slice expression just needs to be <= len(s). See https://golang.org/ref/spec#Slice_expressions for more info.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by theory** [comment]
Oh, missed this:

> For slices, the upper index bound is the slice capacity cap(a) rather than the length

Sorry about that; I'd skipped that paragraph before because I thought it only covered arrays and strings. Should have kept reading. Thank you!

**Comment by theory** [comment]
No wait, that doesn't say it, either. Your answer is helpful, but it's the low index I'm talking about. If it's also allowed to be `<= len(s)`, then documentation of that fact would be useful.

**Comment by cespare** [comment]
> For arrays or strings, the indices are in range if 0 <= low <= high <= len(a), otherwise they are out of range.

low and high are both len(parts) in your case.

**Comment by theory** [comment]
Oh I see. Tricky to parse, though I get that it's a language spec more than documentation. Thanks.

**Comment by theory** [comment]
Looks like that @gopherbot mention is due to a typo. It references 978af9c2db, but that commit fixes #20335, not this report.
