### ISSUE TITLE
cmd/go: TestExecutableGOROOT fails on windows

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#20336]
### What version of Go are you using (`go version`)?

go version devel +482da518037 Fri May 12 01:10:11 2017 +0000 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\brainman\go
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

```
c:\>set GOROOT=c:\go

c:\>set GOROOT_BOOTSTRAP=c:\go1.4

c:\>set CGO_ENABLED=0

c:\>set PATH=%PATH%;%GOROOT%\bin

c:\>cd %GOROOT%\src

c:\go\src>make
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using c:\go1.4.
...
...
...
---
Installed Go for windows/amd64 in c:\go
Installed commands in c:\go\bin

c:\go\src>go test -v -run=TestExecutableGOROOT cmd/go
```

### What did you expect to see?

I expect test to PASS.

### What did you see instead?

```
=== RUN   TestExecutableGOROOT
--- FAIL: TestExecutableGOROOT (0.20s)
        go_test.go:3986: C:\Users\brainman\AppData\Local\Temp\1\gotest650109735\newgoroot\bin\go.exe env GOROOT = "c:\\go", want "C:\\go"
FAIL
exit status 1
FAIL    cmd/go  5.226s
```

I suspect this fails because my GOROOT drive letter is small ("c"), but the test expect it to be big ("C"). I think we should adjust the test to allow for either.

Alex

**Comment by ianlancetaylor** [comment]
As far as I can see, the "c:\\go" is coming from `GetModuleFileNameW`, and the "C:\\go" is coming from `set GOROOT=%CD%` in src/make.bat.
