### ISSUE TITLE
x/sys/unix: dup2 syscall is missing on mips64*

### ISSUE THREAD

**Issue by jcowgill** [golang/go#20340]
### What version of Go are you using (`go version`)?
go version go1.8.1 linux/mips64le

### What operating system and processor architecture are you using?
Debian Stretch mips64el

### What did you do?
Run x/sys/unix testsuite.

### What did you expect to see?
It passes

### What did you see instead?

```
# golang.org/x/sys/unix_test
./syscall_unix_test.go:326: undefined: unix.Dup2
FAIL    golang.org/x/sys/unix [build failed]
```

It appears the Dup2 syscall is missing on mips64 and mips64le.

**Comment by binarycrusader** [comment]
So why is it ok that Dup2 was missing on mips64 and therefore added, but we aren't able to add it for Solaris as seen in issue 17042?

**Comment by jcowgill** [comment]
Didn't you add it here? golang/sys@68a71b6be5774eece23e35475fc28514a84297a3

**Comment by ianlancetaylor** [comment]
#17042 was originally opened for the syscall package (the topic line was changed later), and we said that we shouldn't add a new function to the syscall package.  This issue is about the x/sys/unix package.

**Comment by binarycrusader** [comment]
Yes, sorry, I missed that subtlety.
