### ISSUE TITLE
unable to build go1.8 using go1.4 due to import cycle

### ISSUE THREAD

**Issue by ericomali** [golang/go#20345]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.4-bootstrap-20161024 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/jradmin/go"
GOTOOLDIR="/home/jradmin/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
GOOS=linux GOARCH=amd64 ./bootstrap.bash 

### What did you expect to see?
A build.

##### Building Go bootstrap tool.
cmd/dist
import cycle not allowed
package ./cmd/dist
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime

**Comment by bradfitz** [comment]
I don't think `bootstrap.bash` is the tool you're looking for. Your bug report does not suggest you're cross-compiling.

You just want `make.bash`. Set `$GOROOT_BOOTSTRAP` to your Go 1.4 installation or put it at `$HOME/go1.4`

This is all documented at https://golang.org/doc/install/source#go14
