### ISSUE TITLE
Failed to load xxx.dll: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by xjjrocker** [golang/go#20341]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\work\mygo\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\work\mygo
set GORACE=
set GOROOT=C:\work\Go
set GOTOOLDIR=C:\work\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
syscall.MustLoadDLL(xxx.dll) failed to load xxx.dll

$ go run testdll.go
panic: Failed to load TdxHqApi.dll: %1 is not a valid Win32 application.

goroutine 1 [running]:
syscall.MustLoadDLL(0x4d0891, 0xc, 0x5)
        C:/work/Go/src/syscall/dll_windows.go:77 +0x73
main.Hq_Connect(0x4d06c9, 0xc, 0x1e1d)
        C:/work/mygo/src/testkdj/testdll.go:45 +0x4f
main.main()
        C:/work/mygo/src/testkdj/testdll.go:23 +0x46
exit status 2

### What did you expect to see?
when go version go1.8.1 windows/386, It's run successful, but amd64!

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

There's not enough information here for this to be considered a bug report. We would need something reproducible with code & commands to run.
