### ISSUE TITLE
still unable to build go1.8 using go1.4 due to import cycle

### ISSUE THREAD

**Issue by ericomali** [golang/go#20347]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.4-bootstrap-20161024 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/jradmin/go"
GOTOOLDIR="/home/jradmin/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
GOOS=linux GOARCH=amd64 ./make.bash

### What did you expect to see?
A build.

##### Building Go bootstrap tool.
cmd/dist
import cycle not allowed
package cmd/dist
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime

**Comment by bradfitz** [comment]
Dup of #20345

There is not enough information here to identify a bug. You say you're using "go1.4-bootstrap-20161024" but is that version at $HOME/go1.4? What version of Go are you running `make.bash` in? Did you read the instructions at https://golang.org/doc/install/source#go14? 

For questions about Go, see https://golang.org/wiki/Questions.

If you just want to use Go, it'd be easier for you to download the binaries.
