### ISSUE TITLE
Large constant parameter to Printf causes integer overflow

### ISSUE THREAD

**Issue by sybrandy** [golang/go#20344]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8 (Discovered and tested using play.golang.org)

### What operating system and processor architecture are you using (`go env`)?

Unknown (See prev.)

### What did you do?

I was trying to figure out a bug and I was getting an integer overflow error when using a constant vs. a variable in a Printf or when using json.Marshal.  Below is the minimal code to make this happen.

https://play.golang.org/p/pJmDXboQfH

If you comment out the last Printf, the program works correctly.

### What did you expect to see?

Value: 1493302327000
Value: 1493302327000

### What did you see instead?

tmp/sandbox290752816/main.go:10: constant 1493302327000 overflows int

**Comment by bradfitz** [comment]
Working as intended. See https://blog.golang.org/constants

This comes up periodically. See #20108 for the last explanation.

**Comment by sybrandy** [comment]
Apologies for the bug report.  I realized after you replied that I forgot to check closed issues. :(
