### ISSUE TITLE
all: release-branch.go1.8 failing on linux-amd64-racecompile

### ISSUE THREAD

**Issue by aclements** [golang/go#20342]
release-branch.go1.8 is failing on the new(ish) linux-amd64-racecompile builder: https://build.golang.org/log/5b8925f19734068319b79c66326a6b02e6d49cfa

It's also failing on some of the other builders, but this one is included in the trybot set, so it's causing trybots to fail on cherry-picks to the release branch.

**Comment by bradfitz** [comment]
Dup of #20222

It's not hard, but I've been traveling for two weeks.
