### ISSUE TITLE
Perf builders graphs returning 500

### ISSUE THREAD

**Issue by campoy** [golang/go#20359]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```bash
go version devel +e6eacbf762 Sat May 13 14:58:35 2017 -0700 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

<details><pre>
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/campoy"
GORACE=""
GOROOT="/Users/campoy/src/golang.org/x/go"
GOTOOLDIR="/Users/campoy/src/golang.org/x/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yt/3jw3ts594kd9w6t6dw7rp6y40043p6/T/go-build892583349=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

I visited https://build.golang.org/perf then clicked on `Graphs`.

### What did you expect to see?

Some graphs

### What did you see instead?

<img width="722" alt="screen shot 2017-05-13 at 4 08 25 pm" src="https://cloud.githubusercontent.com/assets/2237452/26029912/68b663f2-37f6-11e7-85f6-7cf9338cc157.png">

**Comment by bradfitz** [comment]
Dup of #8930
