### ISSUE TITLE
x/tools/godoc: Use "IsPredeclared" of go/doc

### ISSUE THREAD

**Issue by 178inaba** [golang/go#20357]
### What version of Go are you using (`go version`)?

```
go version go1.8.1 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/i178inaba/work/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8b/5j9t64vs0sg_n1jjfkkrg88m0000gn/T/go-build740177373=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

I saw the following comments.
https://github.com/golang/tools/blob/ce1291533bf047e29f9e188b3f697d3a5157d142/godoc/linkify.go#L196

```go
// The predeclared map represents the set of all predeclared identifiers.
// TODO(gri) This information is also encoded in similar maps in go/doc,
//           but not exported. Consider exporting an accessor and using
//           it instead.
var predeclared = map[string]bool{
```

I knew that there was a function called ["IsPredeclared"](https://golang.org/pkg/go/doc/#IsPredeclared) in go/doc.
Fixed it to use it.

### What did you expect to see?

None.

### What did you see instead?

None.

**Comment by bradfitz** [comment]
I'll reopen this, but it can't really be fixed until Go 1.10 probably.

**Comment by 178inaba** [comment]
I would like to continue to take charge of this issue.

**Comment by 178inaba** [comment]
I have sent change again because go1.9 was released.
https://go-review.googlesource.com/c/tools/+/58890
