### ISSUE TITLE
Go Json Parser have an issue with the special caracter  ` inside a string 

### ISSUE THREAD

**Issue by jonathanulco** [golang/go#20366]
Go 1.8 linux_amd64

Go using the special caracters 

> `

 Go Json Parser have an issue with the special caracter 

> `

  inside a string 
you can see an exemple of the issue here : https://play.golang.org/p/INLuBGyc6A

I know a fix with escape  `\`  but i would be nice to find a trick because GO use ` for the string.

Thx,
PS : excuse for my «froggy english» :)

**Comment by bontibon** [comment]
This is not an issue with the JSON parser, but with your [string literal](https://golang.org/ref/spec#String_literals). As noted in the spec, you cannot have a back quote inside a back quoted literal:

> Raw string literals are character sequences between back quotes, as in \`foo\`. Within the quotes, any character may appear except back quote.

**Comment by mvdan** [comment]
Indeed, this is a compiler error, not a run-time error.
