### ISSUE TITLE
cmd/go: TestExecutableGOROOT fails if goroot is a symbolic link

### ISSUE THREAD

**Issue by aarzilli** [golang/go#20365]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version devel +1d44c4e Mon May 15 06:16:19 2017 +0000 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/a/n/go/"
GORACE=""
GOROOT="/usr/local/go-tip"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build278802526=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Ran ./all.bash in `/usr/local/go-tip/src/` with `/usr/local/go/` being a symbolic link to `/usr/local/go-tip/`.

### What did you expect to see?

Everything passes.

### What did you see instead?

```
--- FAIL: TestExecutableGOROOT (0.03s)
	go_test.go:3993: /tmp/gotest592236170/newgoroot/bin/go env GOROOT = "/usr/local/go", want "/usr/local/go-tip"
```

**Comment by ianlancetaylor** [comment]
@aarzilli Can you see if https://golang.org/cl/43550 fixes the problem?  Thanks.
