### ISSUE TITLE
hash/crc32: optimize arm64 crc32 implementation 

### ISSUE THREAD

**Issue by vielmetti** [golang/go#20370]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.1 linux/arm64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build806539295=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

See https://github.com/cockroachdb/cockroach/issues/15868, "TestConcurrentBatch takes 20s+ on arm64".  This code which does a lot of CRC32 functions on arm64 is not yet accelerated.

### What did you expect to see?

Performance fast enough to pass CockroachDB's test.

### What did you see instead?

Slow performance, 8x the time of a laptop.

It looks like this commit

https://github.com/golang/go/commit/ab636b899cbfe40ad310d7b50d1a443724f5970a

will substantially address the performance issue on arm64.

**Comment by ALTree** [comment]
That commit was merged and it'll be in go1.9. Can we close this issue then?

**Comment by vielmetti** [comment]
Yes, OK to close (you might want to label it such that it goes into the 1.9 release notes).

**Comment by ALTree** [comment]
I believe we have a script that automatically recognizes performance improvements from commit messages so we should be fine!
