### ISSUE TITLE
runtime, syscall: Plan 9 ARM assembly code should use "SWI $0" instead of "SWI 0"

### ISSUE THREAD

**Issue by cherrymui** [golang/go#20378]
On other systems it is all written as `SWI $const`. We should do the same on Plan 9.
Found by CL https://go-review.googlesource.com/c/43552/.

Leave for Go 1.10.

**Comment by bradfitz** [comment]
I think this is safe enough to fix for Go 1.9, especially if it unblocks that other CL (assuming people want it in for Go 1.9). Your call.

**Comment by cherrymui** [comment]
Changed the CL targeting Go 1.9.
