### ISSUE TITLE
Why golang's garbage collector not implement Generational and Compact gc ?

### ISSUE THREAD

**Issue by shenlanse** [golang/go#20373]
To be honest, it's a "ASK FOR HELP" issue .    
As is known to us, Generational and Compact gc have already proven to be successful practices. But golang not implement it until now. Who can tell me the reason. Thanks.

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by davecheney** [comment]
I recommend asking this question on golang-nuts, the Go authors, including the garbage collector authors read that mailing list.

**Comment by shenlanse** [comment]
@davecheney Thanks.
