### ISSUE TITLE
AddDate returns wrong result when used outside main()

### ISSUE THREAD

**Issue by scroveez** [golang/go#20374]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.1

### What operating system and processor architecture are you using (`go env`)?

CentOS Linux release 7.3.1611 (Core)
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

https://play.golang.org/p/Ldn92AdcbD

### What did you expect to see?
2017-05-15 10:43:18.66663326 +0300 +03

### What did you see instead?
2017-05-16 10:43:18.66663326 +0300 +03

**Comment by drmarduk** [comment]
AddDate() returns a time.Time variable, you are not using it in your example
See: https://play.golang.org/p/5oTGW3kRPF

**Comment by ALTree** [comment]
Yeah as drmarduk said `AddDate` does not change the receiver. You have to assign the returned new date to a variable. Closing, since there's no bug.
