### ISSUE TITLE
cmd/go: slow builds on ARM (go build doesn't install deps?)

### ISSUE THREAD

**Issue by dertarr** [golang/go#20372]
### What version of Go are you using (`go version`)?
1.8.1 (and 1.7.5 to compare with)

### What operating system and processor architecture are you using (`go env`)?
RaspberryPi model 3B with raspbian OS
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mkk/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329748828=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
My code is using sqlx library and SQLite3 driver. I'm using `go test` command with `--cover` argument.
Here is a repo to clone: https://dertarr@bitbucket.org/dertarr/wfrp3-data-fork.git
To reproduce the issue, clone the repository at commit a40a933, CD to `cd almacen`, go get all external libraries and `make test`.
```
$ git clone https://dertarr@bitbucket.org/dertarr/wfrp3-data-fork.git
$ git reset --hard a40a933
$ cd wfrp3-data/almacen
$ go get github.com/op/go-logging github.com/gorilla/mux github.com/jmoiron/sqlx github.com/mattn/go-sqlite3 github.com/stretchr/testify/assert
$ make test
```
There will be several errors in the output - this is expected:
```
# _/mkk/wfrp3-data/almacen/whdbobj
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:258: undefined: err
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:291: multiple-value json.Marshal() in single-value context
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:297: cannot use ca.cons.MainText (type string) as type []string in field value
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:298: cannot use ca.reck.MainText (type string) as type []string in field value
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:300: no new variables on left side of :=
/tmp/go-build545648482/_/mkk/wfrp3-data/almacen/whdbobj/_test/_obj_test/cardaction.go:309: missing return at end of function
?       _/mkk/wfrp3-data/almacen        [no test files]
FAIL    _/mkk/wfrp3-data/almacen/whdbobj [build failed]
Makefile:33: recipe for target 'test' failed
make: *** [test] Error 2
```
Another side issue is that line numbers in error messages are not correct. For example, the first error states that there is an undefined "err" at line 258 of file "cardaction.go", but line 258 returns an empty string and does not mention "err". Version 1.7.5 was displaying different line numbers for the same error messages, but not correct either: it complains about undefined "err" on line 261, which is a comment line. This happens probably due to presence of multi-line strings enclosed in backticks.

### What did you expect to see?
  * The command executes is just a several seconds (as in version 1.7.5)
  * (Side issue) Error messages display correct line numbers. For example, the undefined "err" is on line 216.

### What did you see instead?
  * It takes a couple of minutes to execute `make test` on version 1.8.1 ARMv6.
  * Incorrect line numbers in the output

**Comment by pkourganov-infoblox** [comment]
I was using 1.7.5 and was used to the performance I had. When I downloaded 1.8.1 to replace 1.7.5, I notices vast performance drop: from some 12 seconds to about 3 minutes. 

The slow thing is compiling. This is the command that executes slow:
`$ go build --ldflags '-extldflags "-static"' -v .`
Here is the output:
```
github.com/jmoiron/sqlx/reflectx
github.com/gorilla/mux
golang.org/x/net/context
github.com/op/go-logging
github.com/mattn/go-sqlite3
github.com/jmoiron/sqlx
_/mkk/wfrp3-data/almacen
```
The execution "halts" for almost 3 minutes after `github.com/jmoiron/sqlx` is printed and before `_/mkk/wfrp3-data/almacen` is printed. The presence of flags does not impact the performance, so the following command takes just the same time (~3 minutes) to execute.
`go build -v .`

PS. I'll file a separate issue about line numbers a bit later.

**Comment by dertarr** [comment]
I was using 1.7.5 and was used to the performance I had. When I downloaded 1.8.1 to replace 1.7.5, I notices vast performance drop: from some 12 seconds to about 3 minutes. 

The slow thing is compiling. This is the command that executes slow:
`$ go build --ldflags '-extldflags "-static"' -v .`
Here is the output:
```
github.com/jmoiron/sqlx/reflectx
github.com/gorilla/mux
golang.org/x/net/context
github.com/op/go-logging
github.com/mattn/go-sqlite3
github.com/jmoiron/sqlx
_/mkk/wfrp3-data/almacen
```
The execution "halts" for almost 3 minutes after `github.com/jmoiron/sqlx` is printed and before `_/mkk/wfrp3-data/almacen` is printed. The presence of flags does not impact the performance, so the following command takes just the same time (~3 minutes) to execute.
`go build -v .`

PS. I'll file a separate issue about line numbers a bit later.

**Comment by ALTree** [comment]
Please try with `go install` (instead of `go build`) and test again.

**Comment by bradfitz** [comment]
Yeah, this is almost certainly because `go build` doesn't do any caching, which we have existing bugs open for. If you run `go install` or `go test -i` then subsequent builds will not have to rebuild all the dependencies. (This is not ARM-specific)

**Comment by dertarr** [comment]
Ok. I had to copy "almacen" directory to under GOPATH. My GOPATH is `/mkk/gopath`, so the full application path is now `/mkk/gopath/src/bitbucket.org/dertarr/wfrp3-data/almacen`.
Executed the following (with the output) on version 1.8.1:
```
pi@raspberrypi:/mkk/gopath/src/bitbucket.org/dertarr/wfrp3-data/almacen $ go install -v .
github.com/gorilla/mux
github.com/op/go-logging
github.com/jmoiron/sqlx/reflectx
golang.org/x/net/context
github.com/mattn/go-sqlite3
github.com/jmoiron/sqlx
bitbucket.org/dertarr/wfrp3-data/almacen
```
It took 3 minutes to complete. Executing the same command for the second time takes almost no time. Then I updated a string literal inside my code and executed the command for the third time. The output is shorter, and the command completes in about 5 seconds, as it doesn't need to rebuild all libraries:
```
pi@raspberrypi:/mkk/gopath/src/bitbucket.org/dertarr/wfrp3-data/almacen $ go install -v .
bitbucket.org/dertarr/wfrp3-data/almacen
```

Then I switched to version 1.7.5. and deleted `/mkk/gopath/pkg/linux_arm/github.com/jmoiron` directory. Executed the command:
```
```
It took the same 3 minutes to complete (it was rebuilding all libraries, not just the sqlx). I reverted the changes in the string literal and repeated `go install -v .` - the command completed in some 5 seconds.

**Comment by dertarr** [comment]
So, the issue appeared in `go build` with version 1.8.1?

**Comment by bradfitz** [comment]
Sounds like this is just the build caching issue, which is known. The meta bug of sorts is #4719 which is partially about removing the need to "install" built deps and just always cache them. We've been making progress towards this over the past few releases, making the buildid in object files more inclusive. But more remains.

I'm going to close this issue. For now, keep in mind that you need to run `go install` or `go test -i` to install deps when switching versions if you want `go build` or `go test` to be fast.
