### ISSUE TITLE
os: File.Write cannot return io.ErrShortWrite

### ISSUE THREAD

**Issue by dominikh** [golang/go#20386]
### What version of Go are you using (`go version`)?
go version devel +13cdd814ea Tue May 16 21:01:42 2017 +0000 linux/amd64

(*os.File).Write is supposed to return an error on short writes. The assignment in https://github.com/golang/go/blob/13cdd814ea0e8ef165ab54802f9f102b8b690df7/src/os/file.go#L145 however has no effect, because `e` is the error being returned, not `err`.

Making the obvious fix will break a bunch of tests in pipe_test.go, which suggests it might also change the behaviour of real programs. Is it just a matter of calling epipecheck before checking for a short write?

**Comment by ianlancetaylor** [comment]
I think it's just a bug I introduced in the internal/poll work.  Will fix.
