### ISSUE TITLE
doc: add an editor guide

### ISSUE THREAD

**Issue by rakyll** [golang/go#20398]
This is a tracking bug for the new editor guide for golang.org.

We will create a page that summarizes the feature set of the most popular Go editor plugins/IDEs to help new gophers pick a well-supported tool.

Initially, we are planning to feature the top-3 most popular plugins/IDEs:
- vim-go (https://github.com/fatih/vim-go) https://github.com/golang/go/issues/20402
- VSCode Go (https://github.com/Microsoft/vscode-go) https://github.com/golang/go/issues/20399
- IntelliJ Go (https://github.com/go-lang-plugin-org/go-lang-idea-plugin) https://github.com/golang/go/issues/20401
- Atom go-plus (https://atom.io/packages/go-plus) https://github.com/golang/go/issues/20569

Use the following info card template to summarize the editor and its features, and include 1280x640 screencast gifs to highlight a few of the top features.
```
Name
[link to homepage]

Description

Editing
Formatting on save (gofmt), automatic imports, identifier completion, vetting on save, linting on save, rename refactoring, templated refactoring (eg).

Navigation
Godoc lookup, jumping to definition and referrers, looking up for interface implementations, searching for callers and callees.

Testing and Debugging
Running package tests, running single test case, displaying test coverage, generating test cases from package/file/function, Delve debugger integration.
```

**Comment by bep** [comment]
>Initially, we are planning to feature the top-3 most popular plugins/IDEs:

Where are the numbers to back this statement?

**Comment by dlsniper** [comment]
>Where are the numbers to back this statement?

https://blog.golang.org/survey2016-results#TOC_4.

**Comment by dlsniper** [comment]
@rakyll I'll ask the questions here as I think they are general enough to be seen by others as well.

Regarding the screencast, can it be an YouTube video instead of gif?

**Comment by rakyll** [comment]
@dlsniper, we wanted to go with gifs because we expect these screencasts to be 4-5 seconds of overview rather than a big screencast that demonstrates the editor plugin/IDE comprehensively. We want to be able to display a visual once you hover on a few features from the info card. A Youtube video is very heavy-weight for this specific case.

**Comment by joefitzgerald** [comment]
As the maintainer of the predominant package used by Atom users to work with go, I feel a bit disappointed by this decision to work on the "top 3" editors. I am both willing to contribute and would like to contribute, and feel excluded by this decision that was made without consultation.

I also feel that the initial exclusion of other popular editors will perpetuate the current ordering of popularity, simply via the act of omission.

Could you please reconsider this @rakyll - both @zmb3 and I wish to contribute this content for Atom.

**Comment by rakyll** [comment]
@joefitzgerald, I am happy to add atom if you can contribute content. Please feel free to take https://github.com/golang/go/issues/20569 which I recently filed to track.

**Comment by dlsniper** [comment]
@rakyll quick question. Do you think we should have something like this:
- vim (with vim-go plugin) 
- VS Code (with Go plugin)
- Gogland (standalone IDE)
- Atom (with Go-Plus plugin)

So that people can go to the editor page as well as the plugin if they are separate?

**Comment by rakyll** [comment]
@dlsniper, sounds like a better representation. I was about to open a CL to make a similar change but go for it if you are interested to contribute the change.

**Comment by dlsniper** [comment]
That's fine, please go ahead. I'm still not accustomed to the contributing process (I'll try to get better at it in the future).

**Comment by joefitzgerald** [comment]
@dlsniper 🔤, a minor nit: it's `go-plus`, not `Go-Plus`.
