### ISSUE TITLE
doc: add Go for IntelliJ editor guide

### ISSUE THREAD

**Issue by dlsniper** [golang/go#20401]
This is a tracking bug for #20398 Go for IntelliJ.

### Name:
Gogland (codename, not final)
Homepage: https://www.jetbrains.com/go/
Help: https://www.jetbrains.com/help/go/1.0/getting-started-with-gogland.html

### Description:
Distributed as standalone IDE or plugin for IntelliJ Platform based IDEs.

- Editing:
  - smart code completion and type based completion
  - postfix completion and live (user defined) templates
  - formatting on save (gofmt / goimports) and as you type
  - automatic imports and disambiguation resolution for multiple-options
  - vetting, linting and code analysis as you type and on-demand
  - rename, move packages, implement interface, extract variable/method refactoring, interface stubbing
  - support for SQL and other languages features in string literals

- Navigation:
  - builtin documentation display
  - jump to definition or usage / implementation
  - interface matching for method (display which interfaces implement a method)

- Testing and Debugging:
  - run / debug / display coverage for all tests in a project, all tests in a package or a specific test in a specific package
  - Delve integration

**Comment by dlsniper** [comment]
@rakyll can you please assign this to me? Thank you.

**Comment by dlsniper** [comment]
@rakyll I've updated the issue, what are the next steps?

**Comment by rakyll** [comment]
@dlsniper, thanks!

Can we also have some screencast gifs that demonstrates some features? Screencasts need to be 1280x640 gifs. Pick top 3-5 feature and record a screencast gif for each please.

Once we have it all, I will move them to a golang.org page and will CC you on the CL.

**Comment by cheptsov** [comment]
@rakyll 

I can record some GIFs. Just to confirm, if we want to have them in Retina, does it mean we'll need their actual size to be twice bigger, i.g. 2560 x 1280?

**Comment by rakyll** [comment]
@cheptsov I don't think we will maintain retina sizes for all screencast gifts, so downsizing them to 1280x640 would be perfect if you are recording from a Retina display.

**Comment by cheptsov** [comment]
@rakyll 
will [this one](https://cloud.githubusercontent.com/assets/1612143/26541745/4a858c6a-4457-11e7-9245-7c0f3cbf542d.gif) work?

**Comment by rakyll** [comment]
@cheptsov, yes, it looks great!

**Comment by cheptsov** [comment]
There are five GIFs prepared:

[Smart completion](https://blog.jetbrains.com/go/files/2017/06/Screen-Shot-2017-05-26-at-16.30.37.gif)
[Create function quick-fix](https://blog.jetbrains.com/go/files/2017/06/Screen-Shot-2017-05-31-at-10.43.16.gif)
[Extract function & rename refactorings](https://blog.jetbrains.com/go/files/2017/06/Screen-Shot-2017-05-31-at-10.43.17.gif)
[Go to class & Go to implementations](https://blog.jetbrains.com/go/files/2017/06/Screen-Shot-2017-05-31-at-10.43.18.gif)
[Implement interface quick-fix](https://blog.jetbrains.com/go/files/2017/06/Screen-Shot-2017-05-31-at-10.43.19.gif)

**Comment by rakyll** [comment]
Closed via 77ee861ca208fd7f5a674ac0c442f92009ae42d7.
