### ISSUE TITLE
Cross-Compiling Toolchain Overwrites CC/CXX/GOGCCFLAGS for Host

### ISSUE THREAD

**Issue by rittneje** [golang/go#20408]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7.5

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I ran the make.bash script to cross-compile the toolchain for various architectures, setting CC_FOR_TARGET and CXX_FOR_TARGET for each of them.

$ GOOS=linux GOARCH=amd64 CC_FOR_TARGET=gcc CXX_FOR_TARGET=g++ ./make.bash
$ GOOS=linux GOARCH=386 CC_FOR_TARGET=gcc CXX_FOR_TARGET=g++ ./make.bash
$ GOOS=windows GOARCH=amd64 CC_FOR_TARGET=gcc CXX_FOR_TARGET=g++ ./make.bash
$ GOOS=windows GOARCH=386 CC_FOR_TARGET=gcc CXX_FOR_TARGET=g++ ./make.bash
$ GOOS=darwin GOARCH=amd64 CC_FOR_TARGET=clang CXX_FOR_TARGET=clang++ ./make.bash

### What did you expect to see?
I expected each of the compiled toolchains to list the correct CC and CXX when running go env.

### What did you see instead?
The version of the toolchain matching the host's GOOS/GOARCH incorrectly uses the CC, CXX, and GOGCCFLAGS from whichever toolchain was compiled last.

**Comment by bradfitz** [comment]
> What did you see instead?
>
> The version of the toolchain matching the host's GOOS/GOARCH incorrectly uses the CC, CXX, and GOGCCFLAGS from whichever toolchain was compiled last.

How do you see that?

**Comment by rittneje** [comment]
I ran bin/go env.

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jrittner/multi-server-etpk"
GORACE=""
GOROOT="/home/jrittner/toolchain/go"
GOTOOLDIR="/home/jrittner/toolchain/go/pkg/tool/linux_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0"
CXX="clang++"
CGO_ENABLED="1"

**Comment by ianlancetaylor** [comment]
I think this is a dup of #8161.

**Comment by bradfitz** [comment]
Yup, looks like. Will close this one. @rittneje, correct us if that's not right.

**Comment by rittneje** [comment]
I'm not sure if it is a duplicate. 8161 seems to indicate that the reporter expected that when they used the Linux compiler to cross-compile for Windows, it would have known to use the special i686-w64-mingw32-gcc C compiler. The issue here is that when using the host's version of the compiler for a native build (not cross-compile), it uses the wrong CC.

Looking at the output of make.bash, I'm not sure why it re-compiles for the host when I am trying to cross-compile the toolchain.

**Comment by ianlancetaylor** [comment]
@rittneje Seems like the same underlying cause, though: whatever was the last build you run, that is the `CC` you get.

**Comment by rittneje** [comment]
It might be the same underlying cause, but the results are different. You have a comment on that bug that says:

> Once they are built, you can just set GOOS and GOARCH to cross-compile Go code; you don't need to run make.bash again. You do need to set CC to cross-compile C code, CXX to cross-compile C++ code, etc.

However, you also might need to set CC to natively compile C code.
