### ISSUE TITLE
doc: add vim-go editor guide

### ISSUE THREAD

**Issue by rakyll** [golang/go#20402]
This is a tracking bug for an editor guide on vim-go, see #20398 .

Create a brief info card based on the template at #20398 and create screencast for a few top features as 1280x640 gifs.

/cc @matryer

**Comment by fatih** [comment]
Fortunately we have a very lengthy and detailed tutorial already: https://github.com/fatih/vim-go-tutorial It aim both beginners and advance users as it starts from the beginning and tries to cover all important topics.

 I'm happy to to fill the template based on the information here (which I've wrote my self initially) . I'm currently abroad, will tackle it probably next week :)

**Comment by rakyll** [comment]
@fatih, thanks! The tutorial looks great, we should link to it from the info card.

Is it possible for you to suggest a few screencasts that demonstrates a few critical features? Anything that looks good in 1280x640 would work.

**Comment by rakyll** [comment]
/cc @pisush (She was originally planning to work on the info card and videos.)

@fatih, could you collaborate with @pisush on the screencasts and the info card if any help is required please?

**Comment by fatih** [comment]
@rakyll sure thing! Happy to pass it to any other contributor @Pisush let me know if you want to tackle the info card, the gifs or both. I'm happy to guide and give any kind of feedback.

**Comment by rakyll** [comment]
Closed via 77ee861ca208fd7f5a674ac0c442f92009ae42d7.
