### ISSUE TITLE
vendor folder ignore on run

### ISSUE THREAD

**Issue by avelino** [golang/go#20406]
`run` option to ignore `vendor` folder

Example:
My software uses a package that I'm developing called `X`, how do I give priority to the GOPATH not for vendor folder?

This example common in software development.

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/avelino"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y_/dp3lnjh12y9c2xt4hyds9jq80000gn/T/go-build222815123=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by davecheney** [comment]
How are you building your software? Can you show the command(s) you use?

There probably isn't much that can be done if the project contains a vendor
folder and that vendor folder contains copies of the packages required to
build the project. That is, apart from deleting the vendor folder after
checkout.

Can you describe the underlying problem you are trying to solve. Maybe we
can suggest a different solution.

**Comment by go101** [comment]
@avelino
is your main package located under GOPATH?

Vendor works for my project which is under GOPATH.

**Comment by bradfitz** [comment]
We have repeatedly made the decision not to add many options to `go run`, which is intended only for super basic tasks.

For any real development, we expect people to be using `go install` / `go build` and running the resulting binary.

I'm going to close this, since I don't see us adding more options. The mailing list might be the best place to discuss alternatives.
