### ISSUE TITLE
cmd/go, cmd/cgo: cgo includes with dots cause file not to found error

### ISSUE THREAD

**Issue by odeke-em** [golang/go#20405]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +f700f89 Thu May 18 00:05:25 2017 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/emmanuelodeke/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/emmanuelodeke/go"
GORACE=""
GOROOT="/Users/emmanuelodeke/go/src/go.googlesource.com/go"
GOTOOLDIR="/Users/emmanuelodeke/go/src/go.googlesource.com/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-build506069945=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
Tried to run
```shell
$ go get -u -v github.com/ethereumproject/go-ethereum/cmd/geth
```

### What did you expect to see?
Successful go getting and compilation

### What did you see instead?
```shell
github.com/ethereumproject/go-ethereum (download)
github.com/ethereumproject/go-ethereum/crypto/secp256k1
# github.com/ethereumproject/go-ethereum/crypto/secp256k1
In file included from ../../../../../../go/src/github.com/ethereumproject/go-ethereum/crypto/secp256k1/secp256.go:30:
../../../../../../go/src/github.com/ethereumproject/go-ethereum/crypto/secp256k1/./libsecp256k1/src/secp256k1.c:9:10: fatal error: 'include/secp256k1.h' file not found
```

However, this problem doesn't exist with
* Go1.7
* Go1.8
just on tip

I don't yet have a minimal reproducer nor have I bissected, as am working on something else
but I am tracking it at https://github.com/ethereumproject/go-ethereum/issues/237.

**Comment by ianlancetaylor** [comment]
Probably a dup of #20266.

**Comment by odeke-em** [comment]
Thank you @ianlancetaylor, yes in deed, seems like it. I can no longer reproduce the bug after the dup issue was fixed.
