### ISSUE TITLE
doc: Issue with Codewalk: Share Memory By Communicating

### ISSUE THREAD

**Issue by salnoob** [golang/go#20410]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.3 
### What operating system and processor architecture are you using (`go env`)?
Centos 7 / amd64
### What did you do?
Found an issue with the example code given at : 
   https://golang.org/doc/codewalk/sharemem/

### What did you expect to see?
I expected to see the Poll function being called at a fairly regular interval.

### What did you see instead?
Dead lock between the pending and complete channels. It seems that the second case in the select statement was never getting hit after the first three status updates. The code just continues to print the same status as it started with. I came up with a partial solution by creating a ticker object to write garbage status to the status channel in main. I am incredibly new with Go and don't know what the intended solution should be.  Here is the original code with my fix.

## CODE ##
// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
 "log"
 "net/http"
 "time"
)

const (
 numPollers     = 2                // number of Poller goroutines to launch
 pollInterval   = 60 * time.Second // how often to poll each URL
 statusInterval = 10 * time.Second // how often to log status to stdout
 errTimeout     = 10 * time.Second // back-off timeout on error
)

var urls = []string{
 "http://www.google.com/",
 "http://golang.org/",
 "http://blog.golang.org/",
}

// State represents the last-known state of a URL.
type State struct {
 url    string
 status string
}

// StateMonitor maintains a map that stores the state of the URLs being
// polled, and prints the current state every updateInterval nanoseconds.
// It returns a chan State to which resource state should be sent.
func StateMonitor(updateInterval time.Duration) chan<- State {
 updates := make(chan State)
 urlStatus := make(map[string]string)
 ticker := time.NewTicker(updateInterval)
 go func() {
   for {
     select {
     case <-ticker.C:
       logState(urlStatus)
     case s := <-updates:  // Only gets called three times
       urlStatus[s.url] = s.status
     }
   }
 }()
 return updates
}

// logState prints a state map.
func logState(s map[string]string) {
 log.Println("Current state:")
 for k, v := range s {
   log.Printf(" %s %s", k, v)
 }
}

// Resource represents an HTTP URL to be polled by this program.
type Resource struct {
 url      string
 errCount int
}

// Poll executes an HTTP HEAD request for url
// and returns the HTTP status string or an error string.
func (r *Resource) Poll() string {
 resp, err := http.Head(r.url)
 if err != nil {
   log.Println("Error", r.url, err)
   r.errCount++
   return err.Error()
 }
 r.errCount = 0
 return resp.Status
}

// Sleep sleeps for an appropriate interval (dependent on error state)
// before sending the Resource to done.
func (r *Resource) Sleep(pending chan<- *Resource) {
 time.Sleep(pollInterval + errTimeout*time.Duration(r.errCount))
 pending <- r
}

func Poller(pending <-chan *Resource, complete chan<- *Resource, status chan<- State) {
 /* Seems like we cannot write again due to need to write to status */
 for r := range pending { // WATING HERE
   s := r.Poll()
   status <- State{r.url, s}
   complete <- r
 }
}

func main() {
 // Create our input and output channels.
 pending, complete := make(chan *Resource), make(chan *Resource)

 // Launch the StateMonitor.
 status := StateMonitor(statusInterval)

 // Launch some Poller goroutines.
 for i := 0; i < numPollers; i++ {
   go Poller(pending, complete, status)
 }

 // Send some Resources to the pending queue.
 go func() {
   for _, url := range urls {
     pending <- &Resource{url: url}
   }
 }()

  /* MY TEMP FIX */
  go func() {
    ticker := time.NewTicker(5 * time.Second)
   for {
    select {
     case <-ticker.C:
        log.Println("Writing garbage to status")
        status <- State{"example.com" , "all is garbage"}
    }
   }
  }()
  /* END MY TEMP FIX */

 for r := range complete { // WAITING HERE
   go r.Sleep(pending)
 }
}

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by ianlancetaylor** [comment]
I took a look at the code, and it seems fine to me.  The URLs are polled every `pollInterval`, which is every 60 seconds.
