### ISSUE TITLE
x/build: more logs when something goes wrong

### ISSUE THREAD

**Issue by josharian** [golang/go#20419]
https://build.golang.org/log/16f4dca098af2d81699f154757b5f6b77ada1d3f

Occurred at CL 40095, which definitely touched a lot of the compiler. Frustratingly, there is no indication in the logs whatsoever what failed, and I don't see anything obviously racy in that CL. Running a bunch of race-enabled builds locally has yet to generate a failure. I'll keep at it.

cc @mdempsky @bradfitz for ideas

**Comment by bradfitz** [comment]
That looks more like the builder's (my) fault than yours.

Maybe the new RPC just added for #20222 failed but something up the chain didn't handle the temporary error nicely.

In any case, those logs suck. I had assumed an RPC failure would result in a retry, but perhaps that's only for trybots. It should write more debug info the build log on failures, just in case it's not retried.

I wouldn't worry about this.

**Comment by josharian** [comment]
OK. I've gotten no failures locally either, so I'm going to switch this to be a builders bug about the logs.

**Comment by josharian** [comment]
This happened again today, at `495f55d	mvdan	19 May 18:11`: https://build.golang.org/log/5ca06376c703c8190614928d381ffa7c67346b9e

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/c/43774/ today might've fixed it.

**Comment by josharian** [comment]
Oh I see—those were both very old commits, pre-dash-c. Thanks!

**Comment by bradfitz** [comment]
I think this is done.
