### ISSUE TITLE
cmd/compile: wrong line number in redeclaration error

### ISSUE THREAD

**Issue by rsc** [golang/go#20415]
```
$ n zz_test.go
    1	package z
    2	
    3	func f() {
    4		_ = g[:]
    5	}
    6	
    7	var g [1]byte
    8	
    9	func f2() {
   10		for g := 0; g < 2; g++ {
   11			go func(g int) {
   12			}(g)
   13		}
   14	}
   15	
   16	var g interface{}
$ go test zz_test.go
# command-line-arguments
./zz_test.go:4:7: cannot slice g (type interface {})
./zz_test.go:16:5: g redeclared in this block
	previous declaration at ./zz_test.go:11:13
FAIL	command-line-arguments [build failed]
$ 
```

The conflicting "previous declaration" is at line 7, not line 11.

This is reduced from a much larger example; I was very confused for a bit as to how one global declaration could possibly be conflicting with a closure parameter name. I had to guess to look for a different global variable by hand.

/cc @griesemer @mdempsky

**Comment by odeke-em** [comment]
At least it doesn't happen on Go1.8 as per https://play.golang.org/p/WNexAimVXU
<img width="822" alt="screen shot 2017-05-20 at 2 46 10 am" src="https://cloud.githubusercontent.com/assets/4898263/26274401/8bdeddea-3d06-11e7-9fd8-1eee530cdf6d.png">
but happens on tip at 2d20ded

**Comment by odeke-em** [comment]
And according to the code Maury, eaf02e1fc9d5f22415233783c02bb0b687d216ec seems to be the father of the regression:
Commit:
* Before it: e52d317d2476acc0a9985fab7068ee5c2971807b doesn't have the problem
* After it: 1e72bf62183ea21b9affffd4450d44d994393899 has the problem
as on page https://github.com/golang/go/commits/master/src/cmd/compile/internal/gc?after=2d20ded584cc840bf35054b2a5f840fdefb12767+69

**Comment by griesemer** [comment]
Thanks, @odeke-em for tracking this down.

**Comment by griesemer** [comment]
Simpler repro-case:
```
package p

var g byte

func f(g int) {}

var g interface{}
```
