### ISSUE TITLE
x/build: clean download fails

### ISSUE THREAD

**Issue by kevinburke** [golang/go#20423]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Tip, though I'm also able to reproduce on Go 1.8

### What operating system and processor architecture are you using (`go env`)?

Mac or Linux

### What did you do?

For some reason there's a problem with the go4.org package root.

```
rm -rf $GOPATH/src/go4.org
go get golang.org/x/build/...
```

### What did you expect to see?

I expected the program to check out and compile

### What did you see instead?

The following error:

```
$ go get golang.org/x/build/...
package go4.org/syncutil: /Users/kevin/src/go4.org exists but /Users/kevin/src/go4.org/.git does not - stale checkout?
package go4.org/types: cannot find package "go4.org/types" in any of:
	/Users/kevin/go/src/go4.org/types (from $GOROOT)
	/Users/kevin/src/go4.org/types (from $GOPATH)
```

See related Travis builds, which you should be able to use to verify a patch as well.

https://travis-ci.org/kevinburke/build/jobs/234034579

Here's the travis.yml file I'm using: https://github.com/kevinburke/build/blob/travis/.travis.yml

**Comment by kevinburke** [comment]
Here's the verbose output from `go get`:

```
$ go get -v golang.org/x/build/...
Fetching https://go4.org/grpc?go-get=1
Parsing meta tags from https://go4.org/grpc?go-get=1 (status code 200)
get "go4.org/grpc": found meta tag get.metaImport{Prefix:"go4.org/grpc", VCS:"git", RepoRoot:"https://github.com/go4org/grpc"} at https://go4.org/grpc?go-get=1
go4.org/grpc (download)
Fetching https://go4.org/syncutil?go-get=1
Parsing meta tags from https://go4.org/syncutil?go-get=1 (status code 200)
get "go4.org/syncutil": found meta tag get.metaImport{Prefix:"go4.org", VCS:"git", RepoRoot:"https://github.com/camlistore/go4"} at https://go4.org/syncutil?go-get=1
get "go4.org/syncutil": verifying non-authoritative meta tag
Fetching https://go4.org?go-get=1
Parsing meta tags from https://go4.org?go-get=1 (status code 200)
go4.org (download)
package go4.org/syncutil: /Users/kevin/src/go4.org exists but /Users/kevin/src/go4.org/.git does not - stale checkout?
Fetching https://go4.org/types?go-get=1
Parsing meta tags from https://go4.org/types?go-get=1 (status code 200)
get "go4.org/types": found meta tag get.metaImport{Prefix:"go4.org", VCS:"git", RepoRoot:"https://github.com/camlistore/go4"} at https://go4.org/types?go-get=1
get "go4.org/types": verifying non-authoritative meta tag
package go4.org/types: cannot find package "go4.org/types" in any of:
	/Users/kevin/go/src/go4.org/types (from $GOROOT)
	/Users/kevin/src/go4.org/types (from $GOPATH)
```

**Comment by kevinburke** [comment]
Once I get in that state, all further package downloads fail

```
$ go get go4.org/types
package go4.org/types: /Users/kevin/src/go4.org exists but /Users/kevin/src/go4.org/.git does not - stale checkout?
```

**Comment by bradfitz** [comment]
I put go4.org/grpc in its own git repo, separate from go4.org/...

I guess cmd/go doesn't like that.

**Comment by bradfitz** [comment]
FWIW, it "works" if you go get go4.org/ANYTHINGELSE before go4.org/grpc.

**Comment by bradfitz** [comment]
I'm going to consider this effectively a dup of #26872 (migrating x/build to using modules).

We'll be better at monitoring & testing deps after that.

**Comment by dmitshur** [comment]
@bradfitz I think this is closer to https://github.com/go4org/go4/issues/30, which has been resolved a year ago.
