### ISSUE TITLE
release-branch.go1.8 rewound yesterday?

### ISSUE THREAD

**Issue by tianon** [golang/go#20426]
I've got an automated task which scrapes https://github.com/golang/go/blob/release-branch.go1.8/VERSION to figure out what the latest "1.8" release version is, and sometime yesterday between 4:23pm and 10:23pm PDT the `release-branch.go1.8` branch appears to have been changed to no longer include a4c18f0, which is the commit that bumps the `VERSION` file to `go1.8.1` (can be seen more easily via https://github.com/golang/go/compare/release-branch.go1.8...go1.8.1).

Any ideas what might have happened?  (Should I adjust my processes, or was this an oversight that ought to be corrected?  Is there a better place I should report this sort of thing in the future and/or redirect this report?)

Thanks for your work! :pray: :heart:

**Comment by cespare** [comment]
https://groups.google.com/d/msg/golang-dev/YJm6XebFj60/wrYAGYEjBQAJ

**Comment by ALTree** [comment]
Thanks for the report.

This was announced on golang-dev. See https://groups.google.com/forum/#!topic/golang-dev/YJm6XebFj60

Closing, since this is not an issue.

**Comment by tianon** [comment]
Doh!  Thanks for pointing me to the obvious place I should've checked. :face_with_head_bandage: :heart:
