### ISSUE TITLE
reflect: fmt did not invoke Kind.String method on MacOS

### ISSUE THREAD

**Issue by xgz123** [golang/go#20438]
### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
macOS Sierra

~~~bash
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="***/go"
GORACE=""
GOROOT="***/go"
GOTOOLDIR="***/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bl/s4qsyy7s6cx4wj6tnhw2mb6w0000gn/T/go-build081416673=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
~~~

### What did you do?

```go
package main

import (
	"fmt"
	"reflect"
)

type X int

func main() {
	var a X = 100
	t := reflect.TypeOf(a)
	fmt.Println(t.Name(), t.Kind())
}
```

### What did you expect to see?
play.golang.org has the right output:`X int`

### What did you see instead?
my result: `X 2`

**Comment by ianlancetaylor** [comment]
The problem is not that `reflect.Kind` returned the wrong value.  The problem is that `fmt.Println` did not invoke the `String` method of `reflect.Kind`.  The value of `Int` is in fact `2`.

Are you sure that you ran the exact program you show on MacOS?  For example, you did not change `fmt.Println` to simply `println`?

**Comment by xgz123** [comment]
@ianlancetaylor ...You are 100% right!
