### ISSUE TITLE
text/template: cannot index with literal integer from map[int32]string 

### ISSUE THREAD

**Issue by BupjaeLee** [golang/go#20439]
### What version of Go are you using (`go version`)?
go1.8

### What operating system and processor architecture are you using (`go env`)?
(go playground)

### What did you do?
https://play.golang.org/p/dMKNy4pTnb

### What did you expect to see?
```
[ ok] Element 0 is zero
[ ok] Element 0 is zero
[ ok] Element 0 is zero
```

### What did you see instead?
```
[ ok] Element 0 is zero
[ ok] Element 0 is zero
[err] template: :1:15: executing "" at <index . 0>: error calling index: value has type int; should be int32 
```

I think "untyped" integer in template should become not only "int", but also "int32", "int64", ......

**Comment by odeke-em** [comment]
/cc @robpike @rsc

* text/template documents this
as predefined global function
```
index
	Returns the result of indexing its first argument by the
	following arguments. Thus "index x 1 2 3" is, in Go syntax,
	x[1][2][3]. Each indexed item must be a map, slice, or array.
```
<img width="843" alt="screen shot 2017-05-20 at 11 49 33 am" src="https://cloud.githubusercontent.com/assets/4898263/26278242/da272ec0-3d52-11e7-92c9-8fcf93a80b2c.png">

must be a `map` so no restriction on the typing, IMO should be fixed as per this bug report.

* Also an additional note is that "html/template" has the same functionality but predefined global functions are not documented for "html/template" as per https://play.golang.org/p/Gf9Ez_QEyY.

**Comment by rsc** [comment]
This is just a bug. Constants are supposed to be ideal-like and should convert to int32 here.

**Comment by bradfitz** [comment]
Or, if somebody has an easy fix this week, Go 1.9 is fine too.

**Comment by odeke-em** [comment]
Cool, thanks for the information, for starters, I've mailed https://go-review.googlesource.com/43850.

**Comment by odeke-em** [comment]
I mailed a CL for Go1.9 on that day as per https://github.com/golang/go/issues/20439#issuecomment-303209362. Should we instead mark it as for Go1.10?
