### ISSUE TITLE
"go run" should be able to run a directory

### ISSUE THREAD

**Issue by ahmetb** [golang/go#20432]
### What version of Go are you using (`go version`)?

1.8.1

### Problem

When I want to run a Go program that is in `./app/` directory in my dev/test cycle, I have the following options:

1. **`go build -o a.out ./program && ./a.out`**: I don't want to have binary files laying around
2. **`go install ./program && $GOPATH/program`**: it takes two steps and too long to type.
3. **`cd program; go run *.go`**: this doesn't work when I have `_test.go` files. (#5164)

I think we should be able to point `go run` to a directory, as an alternative to a list of `gofiles...`, and run the whole directory.

It would be great if `go run ./program` or just `go run .` to execute the program in current working directory. go tool can easily detect if an argument is a go file or directory specification, then it can discover the go source files (excl. _test.go files) on the directory and then pass it as the `gofiles...` arg to the actual `go run`.

This has been previously reported at various forums:

- https://github.com/golang/go/issues/5164
- http://stackoverflow.com/questions/23695448/golang-run-all-go-files-within-current-directory-through-the-command-line-mul
- https://groups.google.com/forum/#!topic/Golang-Nuts/1mPYyilpmV0
- https://groups.google.com/forum/#!msg/golang-nuts/sdeUC2VQjfU/d83BCYTYmzgJ 

I am opening a new issue to see if there is interest, or if the feasibility of making this change has changed in the meanwhile.

**Comment by bradfitz** [comment]
Sorry, it has been repeatedly decided in the past not to extend the functionality of `go run` beyond basic "Hello, World" sorts of uses.

You can create aliases or wrapper scripts around `go install` (or Up+Enter) to ease the typing burden.
