### ISSUE TITLE
doc: docs mention non-existent yacc

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#20431]
Hello,
If you open page https://golang.org/doc/cmd and choose at the end of page, then on page https://golang.org/cmd/yacc/ you will see

../../go/src/cmd/yacc: file does not exist

**Comment by Konstantin8105** [comment]
FYI , page https://blog.golang.org/generate have link to page yacc

**Comment by bradfitz** [comment]
@Konstantin8105, I filed #20434 for the blog links. Спасибо!
