### ISSUE TITLE
blog: fix yacc links

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20434]
As repoted by @Konstantin8105, https://blog.golang.org/generate has dead links to since-removed `go tool yacc`.

**Comment by odeke-em** [comment]
Double drat, that article is gonna require a massive rewrite since it seemed to rely mostly on yacc for examples. Could this be something the DevExp group might be interested in? /cc @rakyll

**Comment by bradfitz** [comment]
It doesn't need a rewrite. Just add a `go get golang.org/x/tools/cmd/goyacc` step. That makes the argument for "only developers run `go generate`, not users" even stronger, demonstrating that the developer might have tools available that the user doesn't.

**Comment by odeke-em** [comment]
My bad, I hadn't realized that `golang.org/x/tools/cmd/goyacc` existed and that yacc hadn't been deleted to oblivion. Thanks for the explanation.

**Comment by pravj** [comment]
@bradfitz 
I would like to fix this by pointing to the current location of yacc tool (goyacc).
Am I allowed to do it?

**Comment by bradfitz** [comment]
@pravj, that'd be great. Thanks! See https://golang.org/doc/contribute.html

**Comment by pravj** [comment]
@bradfitz 
I have submitted a change list.
Do I need to add you as a reviewer from the UI?
