### ISSUE TITLE
x/sys/windows/svc/mgr: Documentation of args argument to CreateService incorrect. 

### ISSUE THREAD

**Issue by helloPiers** [golang/go#20440]
The "args" passed to Mgr.CreateService are distinct from the arguments passed to Service.Start (or  via the "Start parameters" field in the service's Properties dialog box). The documentation implies they are the same. The args passed to Service.Start appear as the args on Svc.Handler.Execute, but the args passed to CreateService end up as command line arguments (os.Args). 

I have a doc fix which I plan to submit as a way to learn the contribution process.

**Comment by alexbrainman** [comment]
> The "args" passed to Mgr.CreateService are distinct from the arguments passed to Service.Start (or via the "Start parameters" field in the service's Properties dialog box).

Distinct in what way? And so what? Why should we care?

> The documentation implies they are the same.

Both args are passed to svc.Handler.Execute. That is the only "same" thing. Is that a problem?

> The args passed to Service.Start appear as the args on Svc.Handler.Execute, 

Correct.

> ... but the args passed to CreateService end up as command line arguments (os.Args).

Maybe. I did not check.

I do not understand what is the problem here. I suspect you are unhappy about some documentation. Which documentation is invalid and why? Thank you.

Alex

**Comment by helloPiers** [comment]
Hi Alex,

(I've submitted a small doc fix CL which Brad has merged.)

The windows API call StartService takes some arguments, and these are passed to the windows API callback ServiceMain. (This is what the Go package makes available as the args parameter to svc.Handler.Execute.)

When you register a service with the windows API call CreateService, you are allowed to include in lpBinaryPathName some command-line arguments. These get passed to the service's executable program as standard command line args, e.g. as argv to main().  
 
These two things are distinct.

The Go package's Mgr.CreateService()'s args parameter ends up in the second, i.e. they are string appended to lpBinaryPathName.
```
        s := syscall.EscapeArg(exepath)
        for _, v := range args {
                s += " " + syscall.EscapeArg(v)
        }
```

This caught me out because the doc comment for Mgr.CreateService said they will end up as the arguments to svc.Handler.Execute, but, they will not.

Hope it's clear what I mean, it took me a good while to work out what was happening yesterday while trying to pass some args to a service.

thanks
Piers

**Comment by alexbrainman** [comment]
> "... args will be passed to svc.Handler.Execute". But, they won't be. (They're in os.Args.)

I was mistaken about that. Thank you for explaining.

Alex

**Comment by helloPiers** [comment]
No problem - this was a pretty minor thing overall. That the svc package exists and functions so well has been a huge boost to our project. Cheers.
