### ISSUE TITLE
x/tools/imports: packages used only in function signatures are not auto-imported

### ISSUE THREAD

**Issue by odeke-em** [golang/go#20442]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go1.8 running on the playground at https://play.golang.org/

### What operating system and processor architecture are you using (`go env`)?
Irrelevant

### What did you do?
* Start with https://play.golang.org/p/U6hAK5MYrF
<img width="750" alt="screen shot 2017-05-20 at 1 13 20 pm" src="https://cloud.githubusercontent.com/assets/4898263/26278705/28a7dbd4-3d5e-11e7-8cd7-fbfe8a953392.png">

* Hit format to perform the auto-importing then run
<img width="828" alt="screen shot 2017-05-20 at 1 17 29 pm" src="https://cloud.githubusercontent.com/assets/4898263/26278729/bc384d3e-3d5e-11e7-8dd3-3c82545cdd83.png">

### What did you expect to see?
All packages auto-imported including "reflect" and a successful run

### What did you see instead?
Notice that it didn't import "reflect" as that package in used only in the function signature, but successfully imported the rest of the packages, thus it failed to compile and I had to manually go import "reflect".

**Comment by mvdan** [comment]
I just ran `goimports -l -w` on that code and it works fine, on x/tools `bf4b54dc687c73b6ef63de8b8abf0ad3951e3edc` and `go version devel +495f55d27d Fri May 19 18:11:51 2017 +0000 linux/amd64`.

I tried with a `goimports` built with Go 1.8.1, but still no luck. Maybe it's the playground having an old `goimports`?

**Comment by odeke-em** [comment]
Interesting, /cc @broady

**Comment by mvdan** [comment]
Smaller repro: https://play.golang.org/p/t10VJFbmgC

Note that if you make the argument a `reflect.Value` it suddenly starts working. Both types have been in Go since 1.0, so I'm not sure why that would be.

@broady any information on how `goimports`/`imports` is being run in the Playground, or what version of it is being used?

**Comment by agnivade** [comment]
Seems to be working now. Closing.
