### ISSUE TITLE
encoding/gob: decode map not eqaul encode value

### ISSUE THREAD

**Issue by niubaoshu** [golang/go#20449]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 windows/amd64
### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\work\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build270790435=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/tDnbqdYOF2
### What did you expect to see?
map[1:1]
### What did you see instead?

this is a bug?

**Comment by odeke-em** [comment]
Hello there @niubaoshu, is the bug you are reporting that `mm map[int]string{"2": 2}` when passed into `dec.Decode(&mm)` should have been entirely reset thus making it `map[int]string{"1": 1}` after decoding?

If so, my personal opinion is that that would be unexpected unless you have conflicting keys(in which that's implicit with a map for clashing keys); decoding values into a receiver is setting them in the receiver, and I don't see any promises of the proposed behavior in the encoding/gob docs
<img width="786" alt="screen shot 2017-05-22 at 12 41 07 am" src="https://cloud.githubusercontent.com/assets/4898263/26295497/685c6306-3e87-11e7-8d95-9bffac5946eb.png">


Let me ping some of the owners of the package @robpike @bradfitz, to give some input.

**Comment by niubaoshu** [comment]
@odeke-em if slice , https://play.golang.org/p/DS6udqMR4B

**Comment by odeke-em** [comment]
Hmm, interesting. For comparison with other encoding/ packages, I've made https://play.golang.org/p/rQyWHKZhIS.

I'll defer to the decisions of the folks that I pinged earlier as I don't fully understand the correct behavior. Thank you for reporting the bug!

**Comment by robpike** [comment]
Working as intended. The decoder does not zero out the object before storing the values.
