### ISSUE TITLE
windows: exec.Cmd.Wait returns an error when the process exits without reading stdin

### ISSUE THREAD

**Issue by jstarks** [golang/go#20445]
### What version of Go are you using (`go version`)?
go 1.8.1

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
```go
package main

import (
	"fmt"
	"os/exec"
	"runtime"
)

type infiniteReader struct{}

func (r infiniteReader) Read(b []byte) (int, error) {
	// If this is uncommented, it fails with ERROR_NO_DATA instead of ERROR_BROKEN_PIPE
	//time.Sleep(time.Second)
	for i := range b {
		b[i] = '\n'
	}
	return len(b), nil
}

func main() {
	var args []string
	if runtime.GOOS == "windows" {
		args = []string{"cmd", "/c", "echo test"}
	} else {
		args = []string{"sh", "-c", "true"}
	}
	c := exec.Command(args[0], args[1:]...)
	c.Stdin = infiniteReader{}

	err := c.Start()
	if err != nil {
		panic(err)
	}
	err = c.Wait()
	if err != nil {
		panic(fmt.Sprintf("%#v", err))
	}
}
```

### What did you expect to see?
Program should exit without error.

### What did you see instead?
On Linux, the program exits without error. On Windows, the program panics with:
```
panic: &os.PathError{Op:"write", Path:"|1", Err:0x6d}

goroutine 1 [running]:
main.main()
        C:/tmp/repro.go:36 +0x1d5
exit status 2
```

This occurs because the `exec.skipStdinCopyError` ignores `EPIPE` from `Write`, but for Windows, `WriteFile`, and thus `os.File.Write`, returns syscall.ERROR_BROKEN_PIPE instead of `syscall.EPIPE` when the other end of the pipe  is closed while the write was outstanding, and ERROR_NO_DATA (0xe8) when the other end of the pipe is already closed before the write was initiated.

I think the fix is just to specialize skipStdinCopyError for Windows to also consider these two extra error codes. The other alternative would be to change `os.File.Write` to translate `ERROR_BROKEN_PIPE` and `ERROR_NO_DATA` to `EPIPE`.

**Comment by ianlancetaylor** [comment]
I think in an ideal world we would change the syscall package to set `EPIPE` to be `ERROR_BROKEN_PIPE`, but that would not be Go 1 compatible.  So I think we should change the os/exec package to check for `ERROR_BROKEN_PIPE` in `skipStdinCopyError` on Windows.

**Comment by jstarks** [comment]
That makes sense. To reiterate, though, I think we need to check for both `ERROR_BROKEN_PIPE` _and_ `ERROR_NO_DATA`, as Windows distinguishes between these two cases that probably should not be distinguished. In almost all cases, the specific error you get is timing-dependent and not under the caller's control.

**Comment by alexbrainman** [comment]
We even have TestIgnorePipeErrorOnSuccess for this. But the test is skipped on windows.
I will try to fix this.

Alex
