### ISSUE TITLE
syscall: add mechanism to steal the controlling terminal from a different session group on Linux

### ISSUE THREAD

**Issue by devimc** [golang/go#20454]
### What version of Go are you using (`go version`)?
go version devel +5e79787 Mon May 22 13:44:12 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/X/gopath/"
GORACE=""
GOROOT="/home/X/gopath/src/github.com/golang/go-linux-amd64-bootstrap"
GOTOOLDIR="/home/X/gopath/src/github.com/golang/go-linux-amd64-bootstrap/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build111441286=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
```
cmd := exec.Command(config.Path)
cmd.Env = os.Environ()
f, err = os.OpenFile(params.Console, os.O_RDWR, 0660)
if err != nil {
	return -1, err
}
cmd.Stdin = f
cmd.Stdout = f
cmd.Stderr = f
cmd.SysProcAttr = &syscall.SysProcAttr{
	// Create Session
	Setsid: true,
	// Set Controlling terminal to Ctty
	Setctty: true,
	Ctty:    int(f.Fd()),
}
if err := cmd.Start(); err != nil {
	return -1, err
}
```

### What did you expect to see?
A processes running using the assigned terminal

### What did you see instead?
```
fork/exec X: operation not permitted
```

### Solution
Allow spawned processes steal the terminal

**Comment by devimc** [comment]
proposed fix https://github.com/devimc/go/commit/559e40cd92c0fa447d997d680adf170aec2295ae

**Comment by bradfitz** [comment]
To @ianlancetaylor for decision.

@devimc, we can't review code outside of Gerrit, which enforces that a CLA has been submitted. See https://golang.org/doc/contribute.html

But you can wait until Ian decides whether this is something we want.

**Comment by devimc** [comment]
@bradfitz great! thanks

**Comment by ianlancetaylor** [comment]
Being able to steal the controlling TTY makes sense.

I think the only thing that really needs to be decided is whether we should always steal the TTY, or whether we should have a new field in `syscall.SysProcAttr` saying whether to steal the TTY.  My inclination is to always steal the TTY if possible--that is, always pass `1` as the argument to `TIOCSCTTY`.

**Comment by devimc** [comment]
I think we can't always pass ```1``` as the argument to ```TIOCSCTTY``` because if the process has not the capability to steal the tty (CAP_SYS_ADMIN) this call will fail, for that reason I think the best way to address this is allowing user/developer to decide when steal or not a tty

**Comment by ianlancetaylor** [comment]
As far as I can see in the Linux kernel sources, the argument to `TIOCSCTTY` is only checked if the tty is already the controlling terminal of some other session.  Do you see something else?

**Comment by devimc** [comment]
Hi @ianlancetaylor  you're right, I sent a PR https://golang.org/cl/44343
thanks
