### ISSUE TITLE
math/big: add Float.Sqrt

### ISSUE THREAD

**Issue by ALTree** [golang/go#20460]
From #14102

Add a `Float` method to compute square roots:

```
// Sqrt sets z to the square root of x, and returns z.
func (z *Float) Sqrt(x *Float) *Float
```

**Comment by rsc** [comment]
Thanks for creating the issue. If you'd like to work on this, I highly recommend Brent and Zimmerman, _Modern Computer Arithmetic_, available online at https://members.loria.fr/PZimmermann/mca/mca-cup-0.5.9.pdf. This is what I used for integer square root and some other things, and it looks like floating-point square root is covered as well.

As far as the API is concerned, I'm OK with the addition but will leave the final decision to Robert.

/cc @griesemer

**Comment by griesemer** [comment]
I'm ok with sqrt for big.Floats. @ALTree if you plan to work on this, please implement this in a new file. Also, it may take a while before I get to reviewing it.

**Comment by ALTree** [comment]
Thanks for the suggestions.

@griesemer no problem, there's plenty of time before the go1.10 freeze.
