### ISSUE TITLE
net: DNS doesn't work on Windows if environment is empty?

### ISSUE THREAD

**Issue by shhsu** [golang/go#20473]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath181
set GORACE=
set GOROOT=D:\go181
set GOTOOLDIR=D:\go181\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\shhsu\AppData\Local\Temp\go-build529806931=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
I created a go program that makes http requests. I want to be able to call that program from another go program. When calling the callee, the caller wants to be able to set an environment variable to modify its behavior

Example callee:
```
func main() {
	thing := os.Getenv("SOMETHING")
	fmt.Printf("something: %s\n", thing)

	var resp *http.Response
	var err error
	if resp, err = http.Get("http://www.google.com"); err != nil {
		fmt.Fprintf(os.Stderr, "Error reaching www.google.com, error: %s\n", err)
	}

	if resp == nil {
		fmt.Printf("resp is nil\n")
	} else {
		fmt.Printf("resp Status code %d\n", resp.StatusCode)
	}
	fmt.Print("Done\n")
}
```

Example caller:
```
func main() {
	programCmd := exec.Command(filepath.Join("..", "http"))
	pwd, _ := os.Getwd()
	if len(os.Args) < 2 {
		programCmd.Env = []string{fmt.Sprintf("%s=%s", "SOMETHING", pwd)}
	}
	programCmd.Stderr = os.Stderr
	programCmd.Stdout = os.Stdout
	if err := programCmd.Run(); err != nil {
		fmt.Printf("%s\n", err)
	}
	fmt.Printf("Done")
}
```

### What did you expect to see?
http requests are successfully made

### What did you see instead?
If I call `caller noEnv` everything is fine, the http request was successfully made with 200 status code
If I call `caller`, the caller would pass the environmental variable `SOMETHING={pwd}`, causing the following error on the callee

`Error reaching www.google.com, error: Get http://www.google.com: dial tcp: lookup www.google.com: getaddrinfow: A non-recoverable error occurred during a database lookup.`

[Example project on VSCode](https://github.com/golang/go/files/1023984/http.zip)

**Comment by shhsu** [comment]
@SajayAntony
This is a minor blocker for a feature for Azure Docker Registry

**Comment by bradfitz** [comment]
You're replacing the entire environment of the child process with exactly 1 environment variable pair, removing all the standard Windows environment variables. Windows things are probably not happy if they lack their entire standard environment.

You should use:

```go
   programCmd.Env = append(programCmd.Env, fmt.Sprintf("%s=%s", "SOMETHING", pwd))
```

I bet that fixes it.

I don't think we need to guarantee that Go programs work flawlessly in an empty environment.

@alexbrainman, thoughts?

**Comment by shhsu** [comment]
@bradfitz 
Thanks for the quick response. Actually that `append(...)` was the first thing I tried. However, that was not the issue. Appending `programCmd.Env` does not fix the issue,

**Comment by bradfitz** [comment]
Please post a complete but minimal self-contained repro.

**Comment by shhsu** [comment]
[http.zip](https://github.com/golang/go/files/1023984/http.zip)
(Ah... Just figured out how to post attachment...)

**Comment by alexbrainman** [comment]
> Actually that append(...) was the first thing I tried. However, that was not the issue. Appending programCmd.Env does not fix the issue,

programCmd.Env is set to nil at the start, so appending 1 string to it, makes your environment have 1 environment variable - and that (as @bradfitz suggested) is not acceptable under Windows - some Windows APIs use these environment variables that you delete. Try this instead:
```
d:\a\src\issues\issue20473\caller>type program.go
package main

import (
        "fmt"
        "os"
        "os/exec"
        "path/filepath"
)

func main() {
        programCmd := exec.Command(filepath.Join("..", "http"))
        pwd, _ := os.Getwd()
        programCmd.Env = append(os.Environ(), fmt.Sprintf("%s=%s", "SOMETHING",pwd)) // []string{fmt.Sprintf("%s=%s", "SOMETHING", pwd)}
        programCmd.Stderr = os.Stderr
        programCmd.Stdout = os.Stdout
        if err := programCmd.Run(); err != nil {
                fmt.Printf("%s\n", err)
        }
        fmt.Printf("Done")
}

d:\a\src\issues\issue20473\caller>type ..\program.go
package main

import (
        "fmt"
        "net/http"
        "os"
)

func main() {
        thing := os.Getenv("SOMETHING")
        fmt.Printf("something: %s\n", thing)

        var resp *http.Response
        var err error
        if resp, err = http.Get("http://www.google.com"); err != nil {
                fmt.Fprintf(os.Stderr, "Error reaching www.google.com, error: %s\n", err)
        }

        if resp == nil {
                fmt.Printf("resp is nil\n")
        } else {
                fmt.Printf("resp Status code %d\n", resp.StatusCode)
        }
        fmt.Print("Done\n")
}

d:\a\src\issues\issue20473\caller>go build -o %GOPATH%\src\issues\issue20473\http.exe issues/issue20473 && go build -o a.exe && a
something: d:\a\src\issues\issue20473\caller
resp Status code 200
Done
Done
d:\a\src\issues\issue20473\caller>

```

Alex

**Comment by bradfitz** [comment]
Oh, whoops, thanks @alexbrainman. That's what I meant to write above but I was spacing out.

Closing this since it looks like program error and/or something not fixable on Windows anyway.

Comment if you disagree.
