### ISSUE TITLE
encoding/ascii85: The decoder returned by NewDecoder sometimes drops errors

### ISSUE THREAD

**Issue by akalin** [golang/go#20475]
Please answer these questions before submitting your issue. Thanks!

What version of Go are you using (go version)?

1.8.2

What operating system and processor architecture are you using (go env)?

darwin amd64

What did you do?

When passing an io.Reader to ascii85.NewDecoder, if that reader emits valid ascii85 input and an error, I would expect that error to be propagated. Instead, it is dropped.

Example: https://play.golang.org/p/b53MrmCtSX

In this case, it's because d.readErr isn't being returned in the branch that handles copying from d.out and then returns.

This is another instance of https://github.com/golang/go/issues/20044 .

**Comment by markdryan** [comment]
This one doesn't actually look like a bug to me.  Although the read error is not returned on the initial call to decoder.Read it is saved in d.readErr and neither lost or overwritten.  It will be returned on the next call to decoder.Read.  This behaviour is compatible with the io.Reader specification.

> When Read encounters an error or end-of-file condition after successfully reading n > 0 bytes, it returns the number of bytes read. It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call.

If we insert a second call to decoder.Read directly after the first, e.g.,

```
  n, err := decoder.Read(buf)
+ n, err = decoder.Read(buf)
  if err != fakeErr {
```

the (test)[https://play.golang.org/p/b53MrmCtSX] passes as fakeError is returned.

**Comment by akalin** [comment]
Ah, you're right! Here's an updated test: https://play.golang.org/p/hhXbOMm5Ew
