### ISSUE TITLE
crypto/elliptic: Unmarshal is not compliant with ANSI X9.62

### ISSUE THREAD

**Issue by reyzin** [golang/go#20482]
### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
play.golang.org

### What did you do?

[https://play.golang.org/p/170Bs007WQ](https://play.golang.org/p/170Bs007WQ)

### What did you expect to see?
Umarshaling an invalid elliptic curve point should result in nil

### What did you see instead?
x coordinate not nil, but instead greater than curve.Params().P

### Explanation
Unmarshal takes a byte string containing x and y coordinates and creates an elliptic curve point. ANSI X9.62 says that if x or y coordinate are greater than or equal to curve.Params().P, the conversion should return an error (see ANSI X9.62:2005 Section A.5.8 Step b, which invokes Section A.5.5, which does the check and rejects when x or y are too big; since this is behind a paywall, [here's an earlier draft that says the same in Section 4.3.4](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.202.2977&rep=rep1&type=pdf)). Documentation at https://golang.org/pkg/crypto/elliptic/#Marshal says Marshal is compliant with ANSI X9.62, and therefore one naturally assumes that Unmarshal is also compliant with ANSI X9.62.

### Additional problems with the documentation: 
The reference to ANSI X9.62 in the [documentation](https://golang.org/pkg/crypto/elliptic/#Marshal) has two problems: the referenced section is not correct (it refers to a very early draft), and ANSI X9.62 itself is hidden behind a paywall. You may wish to reference essentially the same standard that is not behind a paywall: http://www.secg.org/sec1-v2.pdf, sections 2.3.3 and 2.3.4. Also, please indicate that point compression is not used in Marshal and not supported in Unmarshal.

**Comment by aead** [comment]
@reyzin If I understood the draft correctly it's not only required that the x-coordinate is < than P but also the y-coordinate, right? Of course if y is greater than P the IsOnCurve() check would fail, so I guess we can omit the check for the y coordinate?!
Then a simple 
```
if x.Cmp(curve.Params().P) != -1 { 
     x, y = nil, nil
}
```
would make Unmarshal ANSI X9.62 compliant again...

**Comment by reyzin** [comment]
@aead I don't think it's true that if y >= P then IsOnCurve would fail, because https://github.com/golang/go/blob/master/src/crypto/elliptic/elliptic.go#L58 will reduce y2 mod P and you won't know if y was >= P . So seems to me one needs to implement the same check for the y coordinate also, because the standard requires y<P.

**Comment by aead** [comment]
@reyzin Hm, your actually right we must check that both coordinates are smaller than P - thanks for the hint.

**Comment by aead** [comment]
@bradfitz To prevent the following scenario:
```
encoded := Marshal(curve, invalidX, y) // succeed
x, y := Unmarshal(curve, encoded) // fails
``` 
Marshal should reject invalid (to large) coordinates - what should we do here? panic?

**Comment by reyzin** [comment]
@aead The right thing to do is probably have an EC point as a type rather than simply a pair of integers. Because a pair of integers can be too big, too small, or not on the curve.

**Comment by aead** [comment]
@reyzin That's not possible because switching to an EC point type would break backward compatibility...
The best I can imagine here is:
```
if x >= P { panic(...) }
if y >= P { panic(...) }
if !curve.IsOnCurve(x,y) { panic(...) } // this check is missing anyway
```

**Comment by reyzin** [comment]
@aead Then I have no opinion on whether these checks should be performed. One could instead argue that Marshal should not get invalid curve points in the first place. Not also that x and y could be negative, so that's two more checks to perform in Marshal if you wish to perform them. (Not a problem in Unmarshal, because byte strings correspond always to nonnegative integers.)

**Comment by aead** [comment]
@reyzin 
> One could instead argue that Marshal should not get invalid curve points in the first place

Hm, I don't like this argument very much - Why should Unmarshal check the point and Marshal not - Why checking anyway? As a naive user I would expect to be able to successfully unmarshal a previous marshaled point - so Unmarshal should be the reverse of Marshal and the other way around...

>  Note also that x and y could be negative, so that's two more checks to perform in Marshal if you wish to perform them.

Good point! In general I can see two possible solutions:
1. Verify that (x,y) is valid (on the curve AND not smaller than P AND greater than or equal to 0)
2. Try to "repair" the user point: e.g. if x >= P than set x = x mod P

I would prefer the first solution because I don't like the idea of silently "fixing" bad user input and furthermore we must fail (panic) anyway if the point is not the curve.

**Comment by reyzin** [comment]
@aead:  

> Why should Unmarshal check the point and Marshal not?

Because Unmarshal takes data the comes over the wire and thus is untrustworthy, while Marshal takes data that has been internally computed and better be right in the first place. But I don't have a strong opinion here.
