### ISSUE TITLE
math/big: wrong answer from Float.Sub

### ISSUE THREAD

**Issue by soniakeys** [golang/go#20490]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +daa0ddd Wed May 24 22:28:33 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?
Called Float.Sub.  Passed arguments of opposite sign and used the second argument for the receiver.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/NdNWBZDJBv

### What did you expect to see?
-5
-5

### What did you see instead?
-5
-3

**Comment by randall77** [comment]
@griesemer

**Comment by ALTree** [comment]
I thought this was my fault (cda633b39b1353d23965337fb3118a3fc532a0c1) but apparently not, since I can reproduce this in go1.7

I have sent a (tentative) very small fix here: https://go-review.googlesource.com/c/44150/
