### ISSUE TITLE
lowercase environment variable goroot is not accepted

### ISSUE THREAD

**Issue by retsyo** [golang/go#20502]
It seems that windows (at least on my win7 64bits), lowercase environment variable and uppercase environment variable can not be set at the same time. So can we let go read environment variable and change it to disired lowercase or uppercase? thnaks

this shows that lowercase environment variable is not accepted:
```bash
R:\>set goroot=r:\go

R:\>%goroot%\bin\go list
go: cannot find GOROOT directory: c:\go

R:\>%goroot%\bin\go
Go is a tool for managing Go source code.

Usage:

        go command [arguments]
```
        
this shows that lowercase and upper environment variable cannot co-exist:
```bash
R:\>set GOROOT=r:\go

R:\>%goroot%\bin\go list
go: cannot find GOROOT directory: c:\go

R:\>%goroot%\bin\go
Go is a tool for managing Go source code.

Usage:

        go command [arguments]
```        

so we have to switch this way
```bash
R:\>set goroot=
R:\>set GOROOT=r:\go

R:\>%goroot%\bin\go list
can't load package: package .: no buildable Go source files in R:\

R:\>%goroot%\bin\go
Go is a tool for managing Go source code.

Usage:

        go command [arguments]
```

**Comment by mvdan** [comment]
If fixing the environment variable on your system works, why do you propose that Go accomodate for both uppercase and lowercase versions?

**Comment by andybons** [comment]
Closing due to no response.

**Comment by mvdan** [comment]
@andybons thanks for following up. My bad for not setting the WaitingForInfo label.
