### ISSUE TITLE
cmd/gofmt: unaligned fields when a short field name is followed by a long field name

### ISSUE THREAD

**Issue by hyangah** [golang/go#20500]
The following is gofmt'd code.

<pre>
	a := &A{
		Cell: 2,
		F01234567890123456789: 3,
	}
</pre>

Visit https://play.golang.org/p/t6fy24Nb-g and run "Format" button.

### What version of Go are you using (`go version`)?
go1.8.1

**Comment by bradfitz** [comment]
This is intentional and has come up periodically in the past. (e.g. #20258, #10392, etc)

gofmt has heuristics to not make large jumps if one field is much longer than the others.
