### ISSUE TITLE
cmd/internal/obj/arm: .S is silently ignored in MOVW.S

### ISSUE THREAD

**Issue by benshi001** [golang/go#20509]
For "MOVW $0xaaaaaaaa, R1", the constant pool is used and actually it is assembled to "LDR Reg <- off(PC)". And in this case a .S suffix is not supported.

But the current assembler silently generated the right binary code without giving any error message.

**Comment by cherrymui** [comment]
What does `MOVW.S` even mean? I don't think any form of MOVW should take a `.S` bit.

**Comment by benshi001** [comment]
There is a mov instruction "MOV R1, R2" can take .S suffix.

**Comment by benshi001** [comment]
Now CL 44335 has nothing to do with this issue.

**Comment by benshi001** [comment]
"MOVW $0xffffffaa, R0" is assembled to "MVN $0x55, R0", and MVN can also take a .S suffix.

**Comment by benshi001** [comment]
But I do not find MOVW.S is really used, shall we disable .S for all "MOVW, MOVH, MOVB"?

**Comment by cherrymui** [comment]
> "MOVW $0xffffffaa, R0" is assembled to "MVN $0x55, R0", and MVN can also take a .S suffix.

The assembler chooses different hardware instructions to materialize constant, which might change (e.g. for better optimization). Sometimes it doesn't take `.S` bit. The semantic of `.S` shouldn't depend on the value of the constant.

**Comment by benshi001** [comment]
We have two ways:
1. Check .SWP by optab index instead of by instruction, and warn invalid .S for MOVW
2. Create a new MOVWS along with MOVW

Any better solutions?

**Comment by benshi001** [comment]
This bug can also be assigned to me.

**Comment by odeke-em** [comment]
@benshi001 done ;)

**Comment by cherrymui** [comment]
I don't think it is necessary to change the existing checking mechanism. It can be checked at corresponding cases of MOVW in asmout.

I don't think creating a new instruction is a good idea. It is not compatible with existing code.

**Comment by benshi001** [comment]
"It can be checked at corresponding cases of MOVW in asmout."

If so, we need not wait to go1.10, it can be done soon in each case of optab.

**Comment by cherrymui** [comment]
It is not where to make the check. The question is among the many variations of MOVW, which should accept the .S bit. For example, I don't think the MVN case you mentioned above should.

This is not a critical bug, nor a regression. Let's wait for Go 1.10.

**Comment by benshi001** [comment]
Now in "func checkBits", the PWS suffixes are checked via (instruction, bit flags), how about change to (Optab.type_, bit flags). For example,

Case 1 MOVW accepts .S, but case 12 does not. So the 
var mayHaveSuffix = map[obj.As]uint8{
	AMOVW: T_SBIT | T_WBIT | T_PBIT,
	...
} is changed to
var mayHaveSuffix = map[int8]uint8{
	1:   T_SBIT | T_WBIT | T_PBIT,
	12: T_WBIT | T_PBIT,
	...
}

**Comment by benshi001** [comment]
MOVW.P	FPSR, R9   is also silently accepted.
