### ISSUE TITLE
x/net/http2: panics after updating to commit 1a26cf06691746ee35aa7113c9b37289afc7ea28

### ISSUE THREAD

**Issue by uthark** [golang/go#20501]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.1

### What operating system and processor architecture are you using (`go env`)?
linux, amd64

### What did you do?
After recent x/net/http2 update I'm getting panics in http2 code.

I'm using kubernetes client-go, version 2.0, so this is the sources:

https://github.com/kubernetes/client-go/blob/release-2.0/rest/request.go

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

No panic.

### What did you see instead?

```
clustermgr 2017/05/25 20:15:11 runtime error: invalid memory address or nil panic(0x187a980, 0x2736260)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
controller/vendor/golang.org/x/net/http2.(*pipe).Read(0xc4207b5428, 0xc420164000, 0x800, 0x2000, 0x0, 0x0, 0x0)
        controller/vendor/golang.org/x/net/http2/pipe.go:53 +0xa8
controller/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc4207b5400, 0xc420164000, 0x800, 0x2000, 0x0, 0x0, 0x0)
        controller/vendor/golang.org/x/net/http2/transport.go:1588 +0xae
io.(*LimitedReader).Read(0xc420632ba0, 0xc420164000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:436 +0x6c
io/ioutil.devNull.ReadFrom(0x0, 0x26ea7a0, 0xc420632ba0, 0x18adb60, 0x1, 0x7fcbcb4cc550)
        /usr/local/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0x2770fb0, 0x26ea7a0, 0xc420632ba0, 0x7fcbcb4cc550, 0x2770fb0, 0x35c5b79b101)
        <autogenerated>:6 +0x61
io.copyBuffer(0x26ed1a0, 0x2770fb0, 0x26ea7a0, 0xc420632ba0, 0x0, 0x0, 0x0, 0x1916660, 0x0, 0x7fcbcb4d2c98)
        /usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0x26ed1a0, 0x2770fb0, 0x26ea7a0, 0xc420632ba0, 0xc4207b5400, 0x1b267f8, 0xc420620000)
        /usr/local/go/src/io/io.go:360 +0x68
controller/vendor/k8s.io/client-go/rest.(*Request).request.func2.1(0xc42011a750)
        controller/vendor/k8s.io/client-go/rest/request.go:822 +0xe9
controller/vendor/k8s.io/client-go/rest.(*Request).request.func2(0xc42011a750, 0xc4206112c8, 0xa, 0xc420600000, 0xc420611348, 0xc420284f00, 0xc4208aaf00, 0x22, 0x1)
        controller/vendor/k8s.io/client-go/rest/request.go:843 +0xe0
controller/vendor/k8s.io/client-go/rest.(*Request).request(0xc420600000, 0xc420611348, 0x0, 0x0)
        controller/vendor/k8s.io/client-go/rest/request.go:844 +0x3c1
controller/vendor/k8s.io/client-go/rest.(*Request).Do(0xc420600000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        controller/vendor/k8s.io/client-go/rest/request.go:865 +0xc0
controller/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*nodes).List(0xc42074dd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        controller/vendor/k8s.io/client-go/kubernetes/typed/core/v1/node.go:130 +0x112
```

Downgrading to commit https://github.com/golang/net/commit/5961165da77ad3a2abf3a77ea904c13a76b0b073 resolves the issue.

https://go-review.googlesource.com/c/43810/ - This was the change which introduced panic.

I checked source of `Read` method - it looks like after setting `p.b` to `nil` in [pipe.go:61](https://github.com/golang/net/blob/master/http2/pipe.go), consequent calls to `Read` should check if `p.b` is nil.

**Comment by fraenkel** [comment]
Write also needs a guard.

**Comment by bradfitz** [comment]
It looks like the invariant was originally supposed to be that `p.b` is only nil if `p.breakErr` was non-nil, and `breakErr` was already checked before use of `p.b`, but then the other `p.b = nil` was added in https://go-review.googlesource.com/c/43810/6/http2/pipe.go#61

@tombergan?
