### ISSUE TITLE
x/build/maintner: git: argument list too long

### ISSUE THREAD

**Issue by AlekSi** [golang/go#20518]
```
$ maintnerd -config=go -debug
[…]
2017/05/28 15:25:28 gerrit go.googlesource.com/go: git directory exists.
2017/05/28 15:25:28 gerrit go.googlesource.com/go: fixing indexing of 20806 missing commits
2017/05/28 15:25:28 gerrit go.googlesource.com/go: fetching 20806 hashes...
2017/05/28 15:25:29 error fetching 20806 hashes from gerrit project go.googlesource.com/go:
2017/05/28 15:25:29 gerrit go.googlesource.com/go: sync: fork/exec /usr/local/bin/git: argument list too long
2017/05/28 15:25:29 IS TEMP ERROR? *os.PathError fork/exec /usr/local/bin/git: argument list too long
2017/05/28 15:25:29 Temporary error from gerrit go.googlesource.com/go: fork/exec /usr/local/bin/git: argument list too long
```
I hacked code a little to add logging and found that `git fetch` is really [called](https://github.com/golang/build/blob/2d2dfd477a455e875ed6c5b090b63dbf574bcebd/maintner/gerrit.go#L839) with 20k hashes:
```
fetch --quiet origin b3f1dfd7e02b0685f87572d536742300140ed8ee 634af4c052f9570ce59a377bf83b760b28a1d33d […]
```

I guess `syncMissingCommits` should use batches too. Maybe batching should be moved from `syncOnce` to `fetchHashes`.

**Comment by AlekSi** [comment]
I don't think this is a problem anymore. @bradfitz please correct me if I'm wrong.

**Comment by bradfitz** [comment]
@AlekSi, I don't remember fixing this, so I'm not sure. But I also never this problem, and 2-3 other people setup maintner for their projects and didn't report hitting this, so maybe it got fixed.
