### ISSUE TITLE
Add DreamList to the GoUsers

### ISSUE THREAD

**Issue by deftworker** [golang/go#20522]
DreamList.com ( https://www.dreamlist.com ) is written in Go. Please add it to the list of companies using Go: https://github.com/golang/go/wiki/GoUsers

**Comment by odeke-em** [comment]
@deftworker done
<img width="598" alt="screen shot 2017-05-28 at 9 47 23 pm" src="https://cloud.githubusercontent.com/assets/4898263/26536794/44b9ba12-43ef-11e7-8c15-ea172a4fd253.png">

In the future, the wiki page is editable by anyone https://github.com/golang/go/wiki/GoUsers
