### ISSUE TITLE
cmd/link: outdated reference to ../gc/reflect.c in comments

### ISSUE THREAD

**Issue by dmitris** [golang/go#20525]
https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/decodesym.go#L15-L17 contains references to gc/reflect.c which must be leftovers from the C compiler:
```
// Decoding the type.* symbols.	 This has to be in sync with
// ../../runtime/type.go, or more specifically, with what
// ../gc/reflect.c stuffs in these.
```

@rsc - should it be changed to `more specifically, with what ../../../compile/internal/gc/reflect.go stuffs in these`, or something else?

**Comment by ianlancetaylor** [comment]
The correct reference is to replace gc/reflect.c with cmd/compile/internal/gc/reflect.go.
