### ISSUE TITLE
database/sql/driver: someting is wrong in driver.ColumnConverter

### ISSUE THREAD

**Issue by djadala** [golang/go#20538]
The ColumnConverter  interface  does not have anything common with columns and  column index.
Column index is actually bind argument index.
If driver implements this interface, and called with query like:
```go
st.Exec(`select a from table where table.a in(?,?,?,?,?,?,?,?)`,1,2,3,4,5,6,7,8)
```
ColumnConverter is called with indexes from 1 to 8, but result have only 1 column.

For reference current godoc:

type ColumnConverter

ColumnConverter may be optionally implemented by Stmt if the statement is aware of its own columns' types and can convert from any type to a driver Value.
```
type ColumnConverter interface {
        // ColumnConverter returns a ValueConverter for the provided
        // column index. If the type of a specific column isn't known
        // or shouldn't be handled specially, DefaultValueConverter
        // can be returned.
        ColumnConverter(idx int) ValueConverter
}
```

**Comment by djadala** [comment]
just reveal that on tip,  ColumnConverter interface is deprecated and  NamedValueChecker is introduced, 
I'm not sure what to do with this issue.
Close ?

**Comment by ALTree** [comment]
cc @kardianos

**Comment by kardianos** [comment]
ColumnConverter is used for input args for stmts. It was really limited. As you noted i recommend implementing named value checker, which again operates on arguments, not output columns.
