### ISSUE TITLE
release: when installing via the the MSI installer the default installation directory is always being used

### ISSUE THREAD

**Issue by pfeiferbit** [golang/go#20532]
* fresh installation of the current stable package, 1.8.3 with the MSI installer
* try to change the installation directory from `C:\Go` to anything else
* __observed:__ everything is still installed in `C:\Go`
* __expected:__ that everythign is being installed in the location I chose

While just moving everything after installation works there are then dead registry keys and the uninstaller won't work.

Honestly, I would prefer a simple archive to an installer.

**Comment by alexbrainman** [comment]
> observed: everything is still installed in C:\Go

I just installed Go 1.8.3 from https://storage.googleapis.com/golang/go1.8.3.windows-amd64.msi into C:\MyGo. No problem:
```
C:\Users\brainman>go version
go version go1.8.3 windows/amd64

C:\Users\brainman>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\brainman\go
set GORACE=
set GOROOT=C:\MyGo
set GOTOOLDIR=C:\MyGo\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

C:\Users\brainman>
```
Perhaps you should provide more information.

> Honestly, I would prefer a simple archive to an installer.

You could download zip file https://storage.googleapis.com/golang/go1.8.3.windows-amd64.zip from https://golang.org/dl/

Alex

**Comment by pfeiferbit** [comment]
Thanks for the reply. I'm not sure I know which kind of information you want. I can provide the same as you:

    C:\Users\pfeifer>go version
    go version go1.8.3 windows/amd64
    
    C:\Users\pfeifer>go env
    set GOARCH=amd64
    set GOBIN=
    set GOEXE=.exe
    set GOHOSTARCH=amd64
    set GOHOSTOS=windows
    set GOOS=windows
    set GOPATH=H:\Projekte\Go
    set GORACE=
    set GOROOT=G:\Programme\Go
    set GOTOOLDIR=G:\Programme\Go\pkg\tool\windows_amd64
    set GCCGO=gccgo
    set CC=gcc
    set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
    set CXX=g++
    set CGO_ENABLED=1
    set PKG_CONFIG=pkg-config
    set CGO_CFLAGS=-g -O2
    set CGO_CPPFLAGS=
    set CGO_CXXFLAGS=-g -O2
    set CGO_FFLAGS=-g -O2
    set CGO_LDFLAGS=-g -O2
    

I have tried reinstalling again with the same result as in my OP - Go has been installed to `C:\Go` although stated otherwise. After that I moved everything (to `G:\Programme\Go`), ran the uninstaller and then CCleaner to get rid of dead registry keys. Go of course still remained in the directory to which I have moved it. Then I manually set up `GOROOT` as a system env var and `GOPATH` as a user env var, and added `%GOROOT%\bin` to `PATH`. I also sometimes use MSYS2 (for example to use mingw-w64 for a C dependency) and set the same env vars there. It works and it's probably the same as extracting the archive you mentioned. Thanks for that too, I will use that it in the future.

If I'd had to make a guess some artifacts from previous versions of Go remained in the registry preventing me to use any other directory than the default. I use Go since 1.1.

I consider this solved, at least until I experience the same problem after a clean Windows installation.

Greetings

**Comment by alexbrainman** [comment]
> If I'd had to make a guess some artifacts from previous versions of Go remained in the registry preventing me to use any other directory than the default. I use Go since 1.1.

Yes, it could be that. I am glad it works for you now.

> I consider this solved, at least until I experience the same problem after a clean Windows installation.

Sounds good. I will close this issue. Please comment, if this should not be closed.

Alex
