### ISSUE TITLE
reflect: Type.Implements matches unexported methods

### ISSUE THREAD

**Issue by abhinav** [golang/go#20541]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.8.1 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/abg/dev/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8z/qdzjsr3n5l72vdg67zr6xkjc0000gn/T/go-build505967484=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

If you create an interface with an unexported method in one package, types
outside that package cannot implement that method. However,
`reflect.Type.Implements(..)` still indicates that they do.

https://play.golang.org/p/h8sLOg_0Ge demonstrates this with a type that
`reflect` claims implements [`"go/ast".Expr`](https://golang.org/pkg/go/ast/#Expr).

### What did you expect to see?

```
Can cast: false
Implements: false
```

### What did you see instead?

```
Can cast: false
Implements: true
```

**Comment by ianlancetaylor** [comment]
Works correctly in Go 1.6, broken in Go 1.7 and 1.8.

**Comment by go101** [comment]
btw, a question: if "go/ast".Expr can't be implemented by outer packages, then why exports it?

**Comment by dominikh** [comment]
@go101 So that you can declare variables (and arguments, return types, …) of type ast.Expr
