### ISSUE TITLE
x/net/ipv4: batch.go syntax error

### ISSUE THREAD

**Issue by kinghrothgar** [golang/go#20543]
x/net/ipv4 and ipv6 batch.go has synatx errors

### What version of Go are you using (`go version`)?
1.8

### What did you do?
src/golang.org/x/net/ipv4/batch.go:59:14: expected type, found '='
src/golang.org/x/net/ipv4/batch.go:78:2: expected declaration, found 'if'
src/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '='
src/golang.org/x/net/ipv6/batch.go:69:2: expected declaration, found 'if'

**Comment by mikioh** [comment]
As the build constraint line in the source files say it requires the new language feature called ```type alias``` introduced in Go 1.9. You didn't mention what's the tool, I guess that the tool might be kinda syntactic tool and does not support build constraints which are lines start with ```+build:```. FYI, released Go toolchains from the Go team support the build constraints: see https://build.golang.org.

So this is not an issue for x/net/{ipv4,ipv6} packages. Perhaps fixing the tool you are using might be the best. If it's gonna happen you need to tweak the stuff that invokes the tool to avoid from the undesirable behavior of the tool.

**Comment by mastercactapus** [comment]
Perhaps worth noting (just had a coworker run into this): `gofmt` in 1.8.3 has this same behavior (does not support build constraints) and we see the errors manifest when it attempts to format vendored dependencies.

**Comment by mikioh** [comment]
@mastercactapus,

Then it's better to file a new issue for cmd/gofmt.
