### ISSUE TITLE
cmd/go: go test -race can't create $WORK/net.a

### ISSUE THREAD

**Issue by starius** [golang/go#20560]
### What version of Go are you using (`go version`)?

go version go1.8.3 linux/amd64

This go version was compiled from source using make.bash.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bnagaev"
GORACE=""
GOROOT="/home/bnagaev/go"
GOTOOLDIR="/home/bnagaev/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build015631019=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

```
$ go get -t github.com/starius/racesync
$ go test -race github.com/starius/racesync/...
# net
can't create $WORK/net.a: open $WORK/net.a: no such file or directory
```

Output of `go test -x -race github.com/starius/racesync/...`
https://gist.github.com/4c41db39b692b8f50ec8bd0d20910b1b

This issue was factored out from https://github.com/golang/go/issues/20512#issuecomment-305872589

**Comment by ianlancetaylor** [comment]
How repeatable is this for you?

The error message is coming from the compiler.  The compiler is saying that it can not create the output file because of a `ENOENT` error.  As far as I can see this can only mean that the directory `$WORK` does not exist.  And that makes no sense at all.

**Comment by starius** [comment]
I found this error on my machine and then verified it on a clean GCP machine. Both machines run Debian.

**Comment by ianlancetaylor** [comment]
This is happening because of your test, which is

    	dir := os.TempDir()
    	defer os.RemoveAll(dir)

The test removes the entire temporary directory while the go tool is using.  The failure occurs because the temporary directory is gone when the Go compiler expects it to exist.

Don't do that.

**Comment by starius** [comment]
Ahhh! I was so stupid doing `dir := os.TempDir()`. It was intended to create (and remove) a temp directory but instead just removed `/tmp`.
