### ISSUE TITLE
runtime/pprof: ReadMemStats before writing heap profile

### ISSUE THREAD

**Issue by josharian** [golang/go#20565]
```
$ compilebench -run=Flate -alloc
BenchmarkFlate 1 174337267 ns/op 203717000 user-ns/op 24668880 B/op 238572 allocs/op
$ compilebench -run=Flate -alloc -memprofilerate=128
BenchmarkFlate 1 5448433394 ns/op 5393039000 user-ns/op 153120624 B/op 4721861 allocs/op
$ compilebench -run=Flate -alloc -memprofilerate=256
BenchmarkFlate 1 2914825084 ns/op 2869159000 user-ns/op 109857056 B/op 3202958 allocs/op
```

The allocs/op numbers should be more or less unchanged by memprofilerate. All that compilebench does is read the Mallocs number printed by the compiler, and the compiler's Mallocs number comes directly from runtime.ReadMemStats.

My simple attempts to reproduce directly using only runtime.ReadMemStats in a simple program have failed, though, and I'm out of time to investigate.

I'd be delighted if anyone reading this was willing to investigate enough to at least rule out a bug in runtime.ReadMemStats.

**Comment by nussjustin** [comment]
`runtime.ReadMemStats` works as expected. It's the pprof package that could be considered as wrong.

The problem you see is that [`writeHeap`](https://github.com/golang/go/blob/c99483feb816856da1d8f3fc5a59467c0e359f3f/src/runtime/pprof/pprof.go#L478) allocates some memory itself before [reading the memstats](https://github.com/golang/go/blob/c99483feb816856da1d8f3fc5a59467c0e359f3f/src/runtime/pprof/pprof.go#L541). The amount of memory allocated basically only depends on the number of profile records, which depend on `runtime.MemProfileRate`. 

When calling `compilebench` without `-memprofilerate`, `compile` uses the default `runtime.MemProfileRate` of 512KB, which will result in **much** less records in the profile as when setting it to 128 or 256. So with a factor of 4096 in difference between the profiling rates, it's clear that the allocations will be way higher.

If you move the call to `runtime.ReadMemStats` to the top, the resulting memstats will not include those extra allocations.

**Comment by josharian** [comment]
Thanks, Justin!

Marking as 1.10, since this doesn't appear to be a regression from 1.8.
