### ISSUE TITLE
doc: add atom editor guide

### ISSUE THREAD

**Issue by rakyll** [golang/go#20569]
This is a tracking bug for an editor guide on atom, see #20398 .

Create a brief info card based on the template at #20398 and create screencast for a few top features as 1280x640 gifs.

/cc @joefitzgerald

**Comment by zmb3** [comment]
## [Go-Plus](https://atom.io/packages/go-plus)

Makes working with Go in Atom awesome.

### Editing
- Format on save (gofmt, goimports, or goreturns)
- gocode completion with automatic snippet generation
- Compile, lint (gometalinter), and test on save 
- Integration with third party tools:
   - gorename for rename refactoring
   - [gomodifytags](https://github.com/fatih/gomodifytags) for quick struct tag generation

### Navigation
- godoc lookup via [gogetdoc](https://github.com/zmb3/gogetdoc)
- go to definition (via guru or godef)
- support for many guru features
   - "same IDs" highlighting
   - find usages
   - find interface implementations

### Testing and Debugging
- automatically run package tests on save
- highlight covered/uncovered code in editor
- view test output in a panel (supporting ANSI color codes and and automatic linking of 'file:line[:col]' text
- support for Delve debugging provided as a [separate package](https://atom.io/packages/go-debug) /cc @lloiser

**Comment by rakyll** [comment]
@zmb3, could you also please contribute some screencast in the format of  https://github.com/golang/go/issues/20401#issuecomment-306401400?

**Comment by zmb3** [comment]
Yep, its on my list.  Will get to it later this week!

**Comment by rakyll** [comment]
@zmb3, could you please edit the feature matrix on "doc/editors.html" to include Atom?

**Comment by zmb3** [comment]
Sure @rakyll, I'd be happy to. Sorry for the delay on the screen casts. Feeling a bit burnt out lately and some upcoming changes might result in a new UI.
