### ISSUE TITLE
New idea to  auto get binary package

### ISSUE THREAD

**Issue by scsi** [golang/go#20577]
we know that golang can get package's source code automatic when compile. 
But it can not get binary package.
I have a idea to get binary package automic simply

Now golang get pacakge source in below:
>src/{package path}/package_src1.go
 src/{package path}/package_src2.go

If  package is shared in binary mode. The package can be below: 
> src/{package path}/package.a
 src/{package path}/package_head1.go
 src/{package path}/package_head2.go

thx..

**Comment by mvdan** [comment]
I honestly don't understand what you're trying to say. Is this a proposal? If so, please provide more details and an example.

**Comment by bradfitz** [comment]
Sorry, it was an explicit decision that the go tool's binary-only support does not include fetching binary-only dependencies via `go get`.
