### ISSUE TITLE
x/crypto/acme/autocert: NewListener does not enable HTTP2.

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#20572]
### What version of Go are you using (`go version`)?
`go version go1.8.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/home/johan/gows/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/johan/gows"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build589265406=/tmp/go
-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
I deployed a server using `autocert.NewListener` to acquire a certificate. I was surprised to see the server did not have HTTP2 enabled.

### What did you expect to see?
I expected the server to have HTTP2 enabled.

### What did you see instead?
The server did not have HTTP2 enabled.

There's a fairly simple fix for this, simply adding
```go
NextProtos:     []string{"h2"},
```
after [line 72 in `listener.go`](https://github.com/golang/crypto/blob/e1a4589e7d3ea14a3352255d04b6f1a418845e5e/acme/autocert/listener.go#L71) enables HTTP2 support on the server.

**Comment by johanbrandhorst** [comment]
If this is indeed considered a bug worth fixing, I would like to fix it.

**Comment by bradfitz** [comment]
While that would work for you, I wonder if it would break

(1) anybody not expecting HTTP/2 (people not using net/http?) or whether

(2) there are net/http paths where the http2.ConfigureServer path isn't invoked. I worry about the case where the client thinks it can do h2 but the server isn't wired up to accept h2.

For (1), we can just document it. It's new enough and I imagine everybody is using net/http for it. And if you're running, say, an SMTP server, the client won't be trying to do h2.

For (2), I'd just want to audit the various paths again. I forget how the auto-http2.ConfigureServer code works.

But yeah, no real objections.

**Comment by johanbrandhorst** [comment]
I will work on this

**Comment by johanbrandhorst** [comment]
Just to clarify what needs to be done for (2), would you like me to audit all `net/http` functions accepting `net.Listener` to verify that they all call to `http2ConfigureServer` at some point?

**Comment by bradfitz** [comment]
Yes.

**Comment by johanbrandhorst** [comment]
`Serve` in `net/http/fcgi` accepts a `net.Listener` but does not appear to call to `http2ConfigureServer`, is this a case we should be concerned about? All other exported functions in `net/http` and subpackages call to `http2ConfigureServer`.
