### ISSUE TITLE
Proposal: discriminated union representational optimizations

### ISSUE THREAD

**Issue by DemiMarie** [golang/go#20570]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

    go version go1.8.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/dobenour/go"
    GORACE=""
    GOROOT="/home/dobenour/archives/go"
    GOTOOLDIR="/home/dobenour/archives/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build651590031=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"

### What did you do?
Noticed that one can implement a discriminated union (enum) type in Go using interfaces with an unexported method, and wondered if the compiler could optimize their representation.

### What did you expect to see?
Some way to trigger an optimized (flat) representation.

### What did you see instead?
No such way.

**Comment by dsnet** [comment]
This proposal is lacking sufficient information to be able to make a decision on what is even supposed to happen. My understanding is that you are not proposing a language change, but an optimization change.

One issue I see is that adding a private method does not prevent others from implementing that interface. For example, the `testing.TB` interface contains an unexported method, but I could still trivially implement that interface by just embedding the interface in my struct. E.g.,
```go
type MyTB struct {
    testing.TB
}
```
