### ISSUE TITLE
cmd/link: loading N packages takes O(N²) time

### ISSUE THREAD

**Issue by rsc** [golang/go#20578]
There are some deduplication scans in the linker to avoid loading the same package (same import path) multiple times. These use a linear scan over all packages already loaded, so loading N packages takes O(N²) time (even with no duplicates). These scans should be replaced by map checks, cutting the time for N packages to O(N).

I have a CL and will send it.

**Comment by odeke-em** [comment]
Hmm, how come gobot didn't close this issue when CL https://go-review.googlesource.com/c/44852/ was merged into master as https://github.com/golang/go/commit/51711d1429cb592c9ddc772e6362e74ac8545dc8.

**Comment by bradfitz** [comment]
Maybe because Github has been having problems today? https://status.github.com/messages

**Comment by odeke-em** [comment]
Ah, gotcha.
