### ISSUE TITLE
cmd/go: permission denied on macOS, with `go install` command when I set GOOS=linux

### ISSUE THREAD

**Issue by gszecsenyi** [golang/go#20571]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3 

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
export GOOS=linux
go install

### The error message is:
go install runtime/internal/sys: mkdir /usr/local/go/pkg/linux_amd64: permission denied

I also have this issue. On OSX, go1.8.3 darwin/amd64. If I set GOOS=linux, then it fails, because it want to create the pkg directory on GOROOT and not on GOPATH.
This is the error message:
go install runtime/internal/sys: mkdir /usr/local/go/pkg/linux_amd64: permission denied

GOPATH is "/Users/xxx/Documents/GitHub/developments/go/"

**Comment by gszecsenyi** [comment]
If I set back GOOS to darwin with export GOOS=darwin command, then it works again, it uses the GOPATH variable as deployment destination, again.

**Comment by davecheney** [comment]
See the section on "go build vs go install" in the blog post.  https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

**Comment by matthewcummings** [comment]
I'm seeing this same issue but with exporting GOOS=windows on Linux and running go get, which in turn calls go install.  I have GOPATH set to a local directory but go install appears to be ignoring it.  My workaround is to just run go get before changing GOOS in my build scripts.

Probably obvious but my CI job is building Windows and Linux binaries on a Linux build machine.

**Comment by davecheney** [comment]
@matthewcummings can you please open a new issue including all the required information in the template. Please also include the output of adding the -x flag to go get/install which will show us the commands the Go tool executed. 

If this turns out to be a duplicate then we’ll merge the issues. Thanks.

**Comment by agnivade** [comment]
@gszecsenyi - Please use `go build` instead of `go install` when cross-compiling. The reasons are clearly laid out in Dave's blog post. I suggest closing this issue.

**Comment by andybons** [comment]
>Using go build vs go install
>When cross compiling, you should use go build, not go install. This is the one of the few cases where go build is preferable to go install.

>The reason for this is go install always caches compiled packages, .a files, into the pkg/ directory that matches the root of the source code.

>For example, if you are building $GOPATH/src/github.com/lib/pq, then the compiled package will be installed into $GOPATH/pkg/$GOOS_$GOARCH/github.com/lib/pq.a.

>This logic also holds true for the standard library, which lives in /usr/local/go/src, so will be compiled to /usr/local/go/pkg/$GOOS_$GOARCH. This is a problem, because when cross compiling the go tool needs to rebuild the standard library for your target, but the binary distribution expects that /usr/local/go is not writeable.

>Using go build rather that go install is the solution here, because go build builds, then throws away most of the result (rather than caching it for later), leaving you with the final binary in the current directory, which is most likely writeable by you.

Closing for now given this (very good) explanation from @davecheney’s post.
