### ISSUE TITLE
x/build: change trybot success message

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20585]
Trybots used to say they were happy on Gerrit with just:

```
TryBots are happy.
```

But now it says:

```
TryBots are happy.
Benchmark results for linux-amd64 are available at:
https://perf.golang.org/search?q=cl:44870+try:Tcacc944a2
```

That almost implies that Trybots only ran on linux-amd64. (In reality, it was only benchmarks that just ran on linux-amd64).

If we're not going to be concise anymore, we should perhaps just make the message also include all the trybot builders which passed.

**Comment by josharian** [comment]
Suggest: s/for linux-amd64//. The benchmarks page can give the details about platform. And hopefully someday there'll be more.

**Comment by Kinghack** [comment]
maybe it is a good start for contributing by change text message like this?

**Comment by josharian** [comment]
Yes, simple changes like this are a good way to get started. Go for it.
