### ISSUE TITLE
doc: go1.8.txt

### ISSUE THREAD

**Issue by mikioh** [golang/go#20591]
See https://golang.org/doc/go1.8.txt.
```
This file lists things yet to be moved into go1.8.html or deemed too
minor to mention. Either way, delete from here when done.
```

**Comment by bradfitz** [comment]
Reopened for possible cherry-pick later if we have a Go 1.8.4+.

**Comment by rsc** [comment]
CL 45015 OK for Go 1.8.5.

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 45015](https://golang.org/cl/45015) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:49 UTC
