### ISSUE TITLE
io/ioutil: document that WriteFile does not do a f.Sync

### ISSUE THREAD

**Issue by prashanthpai** [golang/go#20599]
### What version of Go are you using (`go version`)?
```sh
$ go version
go version go1.8 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```sh
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ppai/work"
GORACE=""
GOROOT="/home/ppai/go"
GOTOOLDIR="/home/ppai/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build569018824=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
Use [ioutil.WriteFile](https://golang.org/pkg/io/ioutil/#WriteFile).

### What did you expect to see?
I'm sorry if the expectation is wrong but I expected the [source](https://golang.org/src/io/ioutil/ioutil.go?s=2518:2586#L66) of [ioutil.WriteFile](https://golang.org/pkg/io/ioutil/#WriteFile) to have a call to 
[f.Sync()](https://golang.org/pkg/os/#File.Sync)

### What did you see instead?
No call to `f.Sync()` was made internally

If fixing this is acceptable, I'll be glad to send a small patch 👍

**Comment by mvdan** [comment]
Out of curiosity, why? In general, if you're writing to a file, you want to check for an `f.Close()` error. As long as you do that, I don't think a call to `f.Sync()` is necessary.

**Comment by dominikh** [comment]
@mvdan Closing a file doesn't issue a sync. At the same time, there are plenty of files for which you won't care, and syncing unnecessarily will incur a performance cost. Maybe this is a documentation issue and no change to the code should be made.

**Comment by mvdan** [comment]
My bad - I thought closing a file meant syncing it too, but I must have gotten confused. It's a bit bizarre that you could care about close errors but not about sync errors, though.

**Comment by dsnet** [comment]
Some discussion about `f.Sync` in `WriteFile` has been discussed in the past. See #17869.

While it may seem reasonable for `f.Sync` to be called in your use case, it not reasonable to inflict the cost of `f.Sync` upon every use of it.

This is indeed a documentation issue.

**Comment by bradfitz** [comment]
We can document the lack of fsync for Go 1.10 unless somebody sends a change for Go 1.9 which would be fine too.

**Comment by ianlancetaylor** [comment]
That is an odd sort of documentation to write.  There are all kinds of functions that do not call `os.File.Sync`.  Perhaps my expectations are wrong, but I would expect the reverse: I would expect that if `ioutil.WriteFile` called `Sync`, that that would be called out in the documentation.  I would not expect the documentation to explicitly say that it does not call `Sync`.

**Comment by bradfitz** [comment]
I would agree, but this keeps coming up, so it makes me wonder if my expectations are wrong.

But I'm also fine not doing anything here again.

**Comment by robpike** [comment]
Lots of things don't call sync. This is not one worth singling out. I say stet.

**Comment by bradfitz** [comment]
Okay, fair enough. Closing.
