### ISSUE TITLE
x/sys/windows/svc/mgr: Ability to enumerate services

### ISSUE THREAD

**Issue by mappu** [golang/go#20596]
Feature request.

The `x/sys/windows/svc/mgr` package can create a new service, and delete or perform other operations on existing services. But there's no function to list the existing installed services.

I know it's only an `/x/` package. But i think it's a functionality gap.

It can be implemented via the [`EnumServicesStatusEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682640(v=vs.85).aspx) function.

**Comment by alexbrainman** [comment]
Sounds reasonable.

How are you planing to use it? I am asking because EnumServicesStatusEx has some parameters to filter the list. I am trying to decide what new API will look like?

Thank you

Alex

**Comment by mappu** [comment]
Ideally, as little filtering as possible should be done by the package, then the application developer can do it themselves.

In normal Windows `services.msc` or Task Manager you can see all services of type `SERVICE_WIN32`, so i think this is the expected enumeration filter type.

The existing `CreateService` function in this package does use the `SERVICE_WIN32_OWN_PROCESS` type, which is a subset of `SERVICE_WIN32`, so, the round-trip behavior will work as expected.

**Comment by alexbrainman** [comment]
@mappu what do you think about https://golang.org/cl/45711 ?

Alex

**Comment by mappu** [comment]
I think it looks good, a nice simple API.

In the line `t.Errorf("ListServices failed to find $q service", name)` should `$q` instead be `%q`?

**Comment by alexbrainman** [comment]
> I think it looks good, a nice simple API.

Cool. Thank you.

> In the line t.Errorf("ListServices failed to find $q service", name) should $q instead be %q?

Fixed. You can actually review code at  https://golang.org/cl/45711 if you like.

Alex
