### ISSUE TITLE
CL 44335 broke nacl/arm

### ISSUE THREAD

**Issue by dcheney-atlassian** [golang/go#20595]
Since https://go-review.googlesource.com/c/44335/ was merged, the nacl/arm build has been consistently failing.

https://build.golang.org/log/c3abc34b727032ba4381419495d55a2cc0c3df82

/cc @cherrymui @benshi001

**Comment by benshi001** [comment]
That is quit strange. Where can I get nacl ? Can it run on Raspberry Pi 2? Or if there is a VM image for it?

Why it passed the Try-Bots? My changes should behave all same on linux and other platforms.

**Comment by benshi001** [comment]
Could you please try if change line 1069 of cmd/internal/obj/arm/asm5.go,

"if immrot(v) != 0 {" change it to if "immrot(v) == 0 {" and see what will happen?

**Comment by dcheney-atlassian** [comment]
On Wed, Jun 7, 2017 at 3:37 PM, Ben Shi <notifications@github.com> wrote:

> That is quit strange. Where can I get nacl ? Can it run on Raspberry Pi 2?
> Or if there is a VM image for it?
>
https://golang.org/misc/nacl/README

This might be out of date, I admit that i've been carrying around a tarball
of a working nacl/arm configuration for several years.


> Why it passed the Try-Bots? My changes should behave all same on linux and
> other platforms.
>
There are probably no nacl trybots, there are definitely no nacl/arm
trybots as the only build.golang.org dashboard builder runs on a machine at
home.

**Comment by benshi001** [comment]
I will try to build the environment and check what's wrong.

**Comment by cherrymui** [comment]
This is a validation error. The new binary now does not pass NaCl's validator.

NaCl requires each instruction updating SP followed by a `BIC $0xc0000000, SP` to make sure high bits are not set (so it is within NaCl managed address space, presumably). We insert such `BIC` instruction for each SP-updating instruction in the assembler backend. But this happens before `asmout`. Now that an `ADD $xxx, SP` can be decomposed into two `ADD`s or `ADD`/`SUB` pair that both change SP, but we only insert one `BIC` (after both), so the validator is not happy.
