### ISSUE TITLE
filepath.Clean breaks with too many /../../

### ISSUE THREAD

**Issue by sargun** [golang/go#20592]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8

### What operating system and processor architecture are you using (`go env`)?
amd64p32/nacl

### What did you do?
I ran the following:
https://play.golang.org/p/ugrjAFV9yQ

Specifically, the call: `filepath.Clean("/foo/../..")`

### What did you expect to see?
It should return `/..`

### What did you see instead?
It returns `/`

**Comment by bradfitz** [comment]
This is working as intended and as documented:

https://golang.org/pkg/path/filepath/#Clean

```
4. Eliminate .. elements that begin a rooted path:
   that is, replace "/.." by "/" at the beginning of a path,
   assuming Separator is '/'.
```
