### ISSUE TITLE
encoding/xml can NOT analysis hex uint/int

### ISSUE THREAD

**Issue by pacepi** [golang/go#20607]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
1, edit test.xml with hex number
```
<test type="test" index="0x1">
</test>
```

2, edit xml.go
```
package main

import "encoding/xml"
import "io/ioutil"
import "fmt"

type testxml struct {
	Type   string `xml:"type,attr,omitempty"`
	Index  uint   `xml:"index,attr,omitempty"`
}

func (d *testxml) Unmarshal(doc string) error {
	return xml.Unmarshal([]byte(doc), d)
}

func main() {
	xml, err := ioutil.ReadFile("test.xml")
	if err != nil {
		return
	}

	fmt.Printf("read xml : \n%s\n", xml)
	testXml := testxml{}
	if err := testXml.Unmarshal(string(xml)); err != nil {
		fmt.Printf("testXml.UnmarshalXML:\n%s\n", err.Error())
		return
	}

	return
}
```

3, run go
go run xml.go

### What did you expect to see?
encoding/xml can analysis **hex** uint/int.

### What did you see instead?
encoding/xml report a error : strconv.ParseUint: parsing "0x1": invalid syntax

### And I tried to fix this bug...
modify **go/src/encoding/xml/read.go**
`itmp, err := strconv.ParseInt(string(src), 10, dst.Type().Bits())`
--> `itmp, err := strconv.ParseInt(string(src), 0, dst.Type().Bits())`

I run the same test code, and it works well.

**Comment by bradfitz** [comment]
This is working as intended & documented.

The "0x" prefix is only respected in the bits==0 auto-detect mode. If you specify 10 or 16, the "0x" prefix is not allowed and it's your job to strip it first. See `strings.TrimPrefix`. Or just use `s[2:]` if you've validated that it's present already.

**Comment by romdarom** [comment]
Does it mean you can't parse hex values as int or uint using the standard xml.Decoder ?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
