### ISSUE TITLE
cmd/go: go get hangs when credential.helper cache is set

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#20604]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.8.3

### What operating system and processor architecture are you using (`go env`)?
CentOS 7 / Debian 8 linux/amd64

### What did you do?
```
$ git config --global credential.helper cache
$ go get -u github.com/private/private-repo
github.com/private/private-repo (download)
Username for 'https://github.com': OneOfOne
Password for 'https://OneOfOne@github.com': 
^C
```

Trying to `go get` a private repo while `git credential.helper` is set to `cache` hangs after asking for the username/password.

### What did you expect to see?
`go get`  to finish downloading the repo and all its deps.

### What did you see instead?
The void, it spoke to me in ways that can't be fully explained.

**Comment by ianlancetaylor** [comment]
Can you show us the output of `go get -x -u github.com/private/private-repo` ?  That will at least show us the exact git command that is hanging.

**Comment by OneOfOne** [comment]
```
$ go get -x -u ./...
cd /home/private/src/github.com/private/private-repo
git config remote.origin.url
cd /home/private/src/github.com/private/private-repo
git pull --ff-only
Username for 'https://github.com': OneOfOne
Password for 'https://OneOfOne@github.com':
```

Here's the thing though, git isn't even stuck, it exits after entering the password (after successfully pulling any updates to that repo) then nothing, `go get` just hangs there.

I verified that by ssh'ing in and running `ps aux | grep git`.

**Comment by OneOfOne** [comment]
Ok something weird just happened, I had forgotten `go get`  running since earlier, it resumed and checked few repos then got stuck again when I had to enter the user/pass again.

Not sure how long it was stuck for but at least 10 minutes, it might be something to do with having to do with entering the user/pass.

**Comment by OneOfOne** [comment]
Random thought, is this somehow related to #20865?

**Comment by bcmills** [comment]
@OneOfOne, next time you get the hang, could you kill `cmd/go` with `SIGQUIT` and attach the goroutine dump that it (hopefully) produces?

**Comment by agnivade** [comment]
@OneOfOne - It seems like this is happening reliably for you. Could you attach the goroutine dump that @bcmills wanted ? Thanks.

**Comment by OneOfOne** [comment]
I can't reproduce it anymore, closing.
