### ISSUE TITLE
does len(map) race with map writes?

### ISSUE THREAD

**Issue by Codefor** [golang/go#20615]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go/threeparty"
GORACE="history_size=7"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build449371707=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
I've encountered the bellowing situations:
> fatal error: concurrent map iteration and map write;
> fatal error: concurrent map writes

But does len(map) race with concurrent map writes? and why?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ALTree** [comment]
> But does len(map) race with concurrent map writes? and why?

Because a write can change the map size so you have concurrent accesses on the `len` map attribute and at least one of them is a write, which is the definition of data race.

**Comment by ALTree** [comment]
Also: the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process. Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking this kind of questions.

**Comment by bradfitz** [comment]
Note that the `fatal error: concurrent map` crashes are best effort. The lack of crash does not mean that you're free of data races. IIRC, `len(m)` compiles to a single memory load and doesn't take any locks or make any calls (including that fatal crash `throw` call).

But I think the race detector should detect such problems.
