### ISSUE TITLE
os: Create not working on windows network mapped drive

### ISSUE THREAD

**Issue by chrislearn** [golang/go#20619]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Projects\GO\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
I created a network mapped drive in my windows pc, when I use os.Create to create a new file in that drive, it always report this error:
```
The system cannot find the path specified
```

### What did you expect to see?
os.Create create a new file.

### What did you see instead?
```
The system cannot find the path specified
```

![image](https://user-images.githubusercontent.com/5874864/26956868-9eb52616-4cf3-11e7-9844-d52572481eb0.png)
![image](https://user-images.githubusercontent.com/5874864/26956886-b3aa639c-4cf3-11e7-8a40-70b24896e04b.png)

**Comment by mattn** [comment]
s/os.Create now working/os.Create not working/ ?

**Comment by ianlancetaylor** [comment]
Are you sure that all the directories exist?

Please show us your code.  Thanks.

**Comment by bradfitz** [comment]
This was reported against "go version go1.8.3", so it's not a regression from 1.8 -> 1.9. Retargeting to 1.10.

**Comment by chrislearn** [comment]
Sorry, maybe this is my network error, it can not reproduce anymore.
