### ISSUE TITLE
cmd/go: make test -list prints everything when passed no regex

### ISSUE THREAD

**Issue by ALTree** [golang/go#20612]
CL 41195 added a new `-list` flag to `go test` that can be used to list all the Tests, Benchmarks and Examples without running them. It takes a regex argument:

```
-list regexp
    List tests, benchmarks, or examples matching the regular expression.
```

but the default behaviour when passed no arguments it's unhelpful and frustrating: it says

```
$ gotip test -list
go test: missing argument for flag list
```

and exits.

It would be nice if `go test -list` could, when passed no regex, just print everything without forcing me to type `gotip test -list .`

**Comment by cznic** [comment]
How to define 'no regex'? What is 'foo' in `go test -list foo`? An Import path or a regexp?

**Comment by ALTree** [comment]
If there's anything after the flag, that thing is the regex. If you need to
specify a path then you'll need to spell it out and in that case using .
for the regex is not that annoying (it's just one character more).

What I'm proposing is just that "go test -list", literally that string and
nothing else, does something useful. Because I feel that is how the flag
will be often used.

I understand this may raise concerns about consistency.

**Comment by mvdan** [comment]
I'm concerned about consistency, in particular how this would confuse people using `go test -list` alone. For example, `-bench` requires you to use a silly regex like `.` if you want to run all benchmarks. And I'd say `go test -bench=.` is way more common than `go test -list=.`.

**Comment by ALTree** [comment]
Yeah I thought about this a little more and it is probably not a good idea.
Especially introducing inconsistent behaviour with bench and test.

Thanks for the feedback.

**Comment by mvdan** [comment]
Perhaps keep it open in case ayone agrees with the general idea. If there's a time to change how `-test` works, it's definitely before 1.9 is released.

**Comment by bradfitz** [comment]
How about we think about this for Go 1.10? If we wanted to add this support, we can add it later, and we can also modify `-bench` to act like `-bench=.` at the same time if it's decided to add bare `-list`.

**Comment by ALTree** [comment]
Sounds good. I would love to get rid of the `-bench=.` curse.

**Comment by rsc** [comment]
No. Currently `go test -bench . strings` means to run all the benchmarks in the strings package. Redefining as suggested would change it to mean all the benchmarks in the current directory (dot) and the strings package. That's not something we can change at this point. The same is true of list.
