### ISSUE TITLE
plugin: add Windows support in GoLang 1.8.3!

### ISSUE THREAD

**Issue by questionpython** [golang/go#20620]
```
$ go version
go version go1.8.3 linux/amd64
```

-----------------

old issues : https://github.com/golang/go/issues/19282

pkg page : https://golang.org/pkg/plugin/

`Currently plugins only work on Linux.`

When this be complete and work for apple-mac,windows and more?

**Comment by ianlancetaylor** [comment]
Closing as dup of #19282.

We do not use the issue tracker for questions.  Please see https://golang.org/wiki/Questions .  Thanks.

As far as I know, nobody is working on this, so there is no way to know when, or if, it will be done.
