### ISSUE TITLE
cmd/compile: error positions are verbose in cgo-using files

### ISSUE THREAD

**Issue by aclements** [golang/go#20628]
### What version of Go are you using (`go version`)?
go version devel +11c61eb6af Fri Jun 9 04:38:37 2017 +0000 linux/amd64

### What did you do?
Build a file that imports "C" and has compile errors in it.

### What did you expect to see?
Go 1.8 printed out succinct error messages that were the same whether or not the package imported "C". Eg.,

```sh
$ go build
./model.go:89: invalid operation: i < n (mismatched types int and C.uint)
```

### What did you see instead?
At tip, the error positions are much more verbose and include a reference to a temporary path generated by the cgo tool that doesn't even exist after the go tool exits:

```sh
$ go build
./model.go:89[/tmp/go-build298567481/github.com/aclements/go-z3/z3/_test/_obj_test/model.cgo1.go:110:25]: invalid operation: i < n (mismatched types int and _Ctype_uint)
```

/cc @griesemer @mdempsky

**Comment by ALTree** [comment]
Introduced in 2a5cf48f91c0a59eeb01b97ca6afaca311324206.

**Comment by odeke-em** [comment]
Repro for a test when fixing it:
```go
package main

import "C"

func main() {
	n := C.uint(10)
	i := 1
	if i < n {
	}
}
```

**Comment by griesemer** [comment]
This may be due to a regex not matching anymore when the position information contains column info. It may be as easy as disabling the printing of column info when invoking the compiler.
