### ISSUE TITLE
database/sql: golang.org/cl/44956 regresses lxd tests

### ISSUE THREAD

**Issue by mwhudson** [golang/go#20631]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
$ go version
go version devel +b7c51c5 Wed Jun 7 21:00:42 2017 +0000 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

```
$ go get github.com/lxc/lxd/lxd
$ go test -c github.com/lxc/lxd/lxd
$ for i in `seq 10`; do ./lxd.test; done
```

### What did you expect to see?

PASS

### What did you see instead?

Failures like this:

```
--- FAIL: TestContainer_IsPrivileged_Privileged (0.00s)
        Error Trace:    container_test.go:198
	Error:      	Expected nil, but got: &errors.errorString{s:"No such object"}
--- FAIL: TestContainer_findIdmap_mixed (0.02s)
        Error Trace:    container_test.go:293
	Error:      	Expected nil, but got: sqlite3.Error{Code:9, ExtendedCode:9, err:"interrupted"}
--- FAIL: TestContainerTestSuite (7.48s)
```

(it's not completely consistent, rarely it passes, sometimes details differ).

Bisect fingered ef0f7fb92b9458d7d35ee3c10ae853e3dc3077eb

**Comment by bradfitz** [comment]
Like what?

/cc @kardianos

**Comment by mwhudson** [comment]
Like I clicked submit too soon, updated now.

**Comment by bradfitz** [comment]
https://golang.org/cl/44956 is ef0f7fb92b9458d7d35ee3c10ae853e3dc3077eb ("database/sql: Use Tx.ctx in Tx non-context methods")

**Comment by mwhudson** [comment]
Fix by the revert.
