### ISSUE TITLE
Variable is "declared and not used" inside for cycle

### ISSUE THREAD

**Issue by kissgyorgy** [golang/go#20638]
### What version of Go are you using (`go version`)?
Whatever is the current version is at Go Playground: https://blog.golang.org/strings

### What operating system and processor architecture are you using (`go env`)?
Same as above.

### What did you do?
I tried to modify the example like this:
```go
const nihongo = "日本語"
for i, w := 0, 0; i < len(nihongo); i += w {
    runeValue, w := utf8.DecodeRuneInString(nihongo[i:])
    fmt.Printf("%#U starts at byte position %d\n", runeValue, i)
}
```
### What did you expect to see?
The code working the same as the original version.

### What did you see instead?
`tmp/sandbox079374017/main.go:20: w declared and not used`

The variable `w` is clearly defined it has type `int` it's used (`i += w`).
This should work in my opinion.

**Comment by davecheney** [comment]
This is working as intended. W is being declared at the inner scope inside the for loop body.

**Comment by kissgyorgy** [comment]
I found [your blog post about scopes](https://dave.cheney.net/2016/12/15/declaration-scopes-in-go). It's interesting and helps, thanks!
Also by understanding scopes, the following works:
```go
const nihongo = "日本語"
var runeValue rune
for i, w := 0, 0; i < len(nihongo); i += w {
    runeValue, w = utf8.DecodeRuneInString(nihongo[i:])
    fmt.Printf("%#U starts at byte position %d\n", runeValue, i)
}
```
Now I only have to find something about the `:=` operator. 😄
