### ISSUE TITLE
x/build: make gopherbot leave review comments on Gerrit for common mistakes

### ISSUE THREAD

**Issue by mdlayher** [golang/go#20648]
A common mistake when adding a new Go source file to the Go project is to omit the license header.

This means that a human has to point out the mistake every time, and for each file.

I think it makes sense to have the trybots do this instead. It'll save a bit of time and effort for reviewers, and help catch an easy mistake earlier in the review process for the author of the CL.

Thoughts?

/cc @bradfitz

**Comment by ianlancetaylor** [comment]
This might be a better fit for the codereview plugin, which I believe already has a check that all Go files are gofmt-compliant.

**Comment by mdlayher** [comment]
That would be fine with me as well.  I suppose I haven't ever run into that check since my editor takes care of formatting for me.

Either way, I think some automation could be very helpful.

**Comment by bradfitz** [comment]
@ianlancetaylor, once we accept Github PRs, it's no longer a good assumption that all users use `git-codereview`. We want to build something like Google's Tricorder where bots leave comments on the CLs (in Gerrit) instead, so it doesn't matter which tool they used to send a change.

**Comment by bradfitz** [comment]
@andybons, this bug is about doing a Tricorder-style thing for Go, where gopherbot looks at pending CLs and runs plugins and drops review comments in Gerrit.

Start of work for it is in pending CL https://go-review.googlesource.com/c/build/+/38285

**Comment by bradfitz** [comment]
Dup of #18548
