### ISSUE TITLE
cmd/internal/obj/arm: broken form of MOVW

### ISSUE THREAD

**Issue by benshi001** [golang/go#20644]
According to ARM's manual,

	MOVW R0>>28(R1), R2

The final address can be either R1+R0>>28 (bit 23 set to 1) or R1-R0>>28 (bit 23 set to 0).

But current ARM assembler only accept addition. And will complaint

	MOVW -(R0>>28)(R1), R2

with 

	unexpected R0 evaluating expression

**Comment by cherrymui** [comment]
`MOVW.U R0>>28(R1), R2`

**Comment by benshi001** [comment]
It is my mistake.
