### ISSUE TITLE
Change {{ end }} to {{ endif }}, {{ endrange }} or {{ endwith }}

### ISSUE THREAD

**Issue by Lego2012** [golang/go#20658]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Hugo 0.22

### What operating system and processor architecture are you using (`go env`)?
macOS Sierra

### What do I wish?
Don't know if this is an easy thing but it would make coding life much easier. If you have an if statement with another if statement inside and a range or two inside as well it can get weird with all those {{ end }}. Advantage also would be that you can search for all e.g. {{ endif }} in the code for commenting further.

**Comment by bradfitz** [comment]
Are you filing a Go bug report or a Huge bug report?

We can't change the text/template or html/template package per https://golang.org/doc/go1compat

**Comment by Lego2012** [comment]
Sorry for the confusion - no bug report. I posted this already in hugo but they redirected me to you. It’s just the idea/question to rename the different {{ end }} to better differentiate them (like {{ endif }}, {{ endwith }} or {{ endrange }}). I used to work with Jekyll and in Liquid this is solved with {% endif %} and {% endfor %}.

Best regards,
Leo

 

Leo Merkel
Buchhorststr. 13 | 31860 Emmerthal
T +49 5286 990922 | M +49 176 248 248 48 

leo.merkel@confidea.de <mailto:leo.merkel@confidea.de> | www.confidea.de <http://www.confidea.de/> 

Diese E-Mail kann vertrauliche und/oder rechtlich geschützte Informationen enthalten. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte den Absender und vernichten diese Mail. Vielen Dank.

This e-mail, including attachments, is intended for the person(s) or company named and may contain confidential and/or legally privileged information. Unauthorized use, disclosure or copying of this information may be unlawful and is prohibited. If you are not the intended recipient, please delete this message and notify the sender. Thank you for your cooperation.

**Comment by bradfitz** [comment]
This isn't something we can change in the standard library. But tools built on top of Go can do whatever they want and fork the template package at will.
