### ISSUE TITLE
cmd/internal/obj/arm: optimize type promotion

### ISSUE THREAD

**Issue by benshi001** [golang/go#20653]
Currently 
var a int32
var b int8
a = int32(b) is built to MOVBS, which actually is 
tmp = SLL b, 24
a = SRA tmp, 24

That is quite inefficient.

I suggest use single instruction SXTB which was introduced in ARMv6.
"Signed Extend Byte extracts an 8-bit value from a register, sign-extends it to 32 bits, and writes the result to the destination register."

So do int16->int32(SXTH), uint8->uint32(UXTB), uint16->uint32(UXTH)

It can be done in go1.10 and assigned to me.

**Comment by randall77** [comment]
Sounds fine to me. The only tricky part would be conditioning it for GOARM>=6.

**Comment by benshi001** [comment]
Cherry @cherrymui suggeusts in https://go-review.googlesource.com/c/53690. More work is needed to introduce XTB/XTBU/XTH/XTHU to golang. Adding a new field in []optab for selecting different instructions for different GOARM version is a good way.

**Comment by benshi001** [comment]
@cherrymui 
Cherry, I do not think XTB/XTBU/XTH/XTHU can be attributed to MOVB/MOVBU/MOVH/MOVHU,

since there are more complex forms, such as
	XTH Rd, Rm, ROR # 8

which means signed extension of Rm(23:8) to Rd.
