### ISSUE TITLE
sending to Buffered and Unbuffered channel behaviour

### ISSUE THREAD

**Issue by kamal-github** [golang/go#20652]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)?
Mac OS 10.11/amd64

Please refer below examples - 
### In ex 1 I do no not understand why after sending fourth value (i.e 8) to the buffered channel it gets deadlock, Should it even allow last value to channel of cap 4, as sending operations are not in new goroutine in contrast to **ex 2** which is using unbuffered channel, it gets block or go into deadlock as soon as it send data to channel.

```
##Ex.1  
func main() { 
   ch := make(chan int, 4) 
   ch <- 2 
   ch <- 4 
   ch <- 6 
   ch <- 8 
 
   fmt.Println(<-ch) 
   fmt.Println(<-ch) 
   fmt.Println(<-ch) 
   fmt.Println(<-ch) 
    
} 
```

Ex 2 -
```
func main() { 
   ch := make(chan int) 
   ch <- 12 // blocks   
   fmt.Println(<-ch) 
} 
```

Please help me to understand this. Thanks!

**Comment by mvdan** [comment]
See https://play.golang.org/p/w6u3Wc_jf8 - your example works just fine as you would expect.

For further questions, see https://github.com/golang/go/wiki/Questions. The issue tracker is not for them.
