### ISSUE TITLE
download: `golang.org/dl/` is not available on safari

### ISSUE THREAD

**Issue by lzm7455** [golang/go#20665]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Tried 1.8.3 and other version too.  Finally success on Chrome.

### What operating system and processor architecture are you using (`go env`)?
MAC

### What did you do?

Just download the pkg.

### What did you expect to see?

Fix the link so someone wanna to learn Go as a backup choice  will not give up.

**Comment by bradfitz** [comment]
I just downloaded it using Safari. It works fine for me.

How doesn't it work for you? What do you see?

Which version of macOS and which of Safari?

**Comment by lzm7455** [comment]
Thank you.
       Sorry for the late response.
       My env: macOs Sierra 10.12.5 (16F73)  ;   Safari  10.1.1 (12603.2.4);
       I tried it in China.
       When I click the link,  download won't act auto.

**Comment by bradfitz** [comment]
Sorry, we try our best to keep Go available in China but its accessibility can vary daily due to the GFW. I can't advise you how to bust through your firewall.

**Comment by lzm7455** [comment]
Thx for your time.
