### ISSUE TITLE
website: Command Documentation

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#20662]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
konstantin@debian:~$ go version
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
debian

### What did you do?

Read documentation on web site https://golang.org/doc/cmd

### What did you expect to see?

Not clear organization of "command":
* some ...
* full command reference

### What did you see instead?

Merge 2 list of commands to one solid list, like we see in page https://golang.org/pkg/ for packages and . Preliminary :
* go                | Descriptions for go
    * go commands | Descriptions for go commands
    * go build | Descriptions for go build
    * go clean | Descriptions for go clean
...

But I want to clarify some points:
1. If we open link **go** on page https://golang.org/doc/cmd, then we will see big good information about **go doc**. But, If we open on link **full command reference** https://golang.org/doc/cmd, after that link **doc** - then we see short information.
2. On page https://golang.org/doc/cmd link **cover** ---> result documentation from X tools. But on page https://golang.org/cmd/ link **cover** ---> result looks nice.

Please separate page https://golang.org/cmd/go/ to single small parts.

### The reason

Simple organization of documents is clear and easy to translate.

**Comment by Konstantin8105** [comment]
Hello!
May be I can help, if you clarify to understood- how you see the result?

**Comment by bradfitz** [comment]
Run the godoc binary locally:

```
$ godoc -http=:6060
```

And go to http://localhost:6060/doc/cmd

**Comment by Konstantin8105** [comment]
Yes, thanks. I know about that option.
I mean - I can help to change official /doc/cmd.html. 
If you agree, I will follow in according to Contribution Guide.

**Comment by bradfitz** [comment]
Go for it.

**Comment by Konstantin8105** [comment]
Could you clarify - May I continue that issue if you close the issue?

**Comment by bradfitz** [comment]
@Konstantin8105, you were the one who closed the issue, not us.

You wrote the word "Fixes" in your commit message, which is the Github magic word for closing issues: https://help.github.com/articles/closing-issues-via-commit-messages/

I can reopen this for you.

**Comment by Konstantin8105** [comment]
All task from that issue are closed. So, we can close.
