### ISSUE TITLE
Change the output of the command go test to include the test file names

### ISSUE THREAD

**Issue by thibaultfalque** [golang/go#20673]
### What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1

### What did you do?
I developed the [sonarqube](https://github.com/uartois/sonar-golang) plugin for golang.
In sonarqube we must associate the tests with the test file.
For my plugin I use the `go-junit-report` for parse the ouput of `go test -v`. 
But `go-junit-report` can't ouput the filename because `go test -v` not display this. 

This issue is associate with this issue https://github.com/jstemmer/go-junit-report/issues/57
and this https://github.com/uartois/sonar-golang/issues/8

But the problem is there is not the filename in the `go test` output. 

### What did you expect to see?
A different output for `go test` included the filename for a test function. 

### What did you see instead?
The current output of the command `go test`

Thanks.

**Comment by bradfitz** [comment]
A Go test package can span many different files. There is not a single file.

**Comment by bradfitz** [comment]
You can use `go list -json PACKAGE_NAME` to list the files in the test.

**Comment by thibaultfalque** [comment]
hi @bradfitz 
Thanks for your answer. 
Yes I know but is it not possible to associate the test function with this file ?

But actually if I have a package for example: 
util

- util.go

- util_test.go

There isn't a problem because `go-junit-report` list all function for a package util. It's perfect. 

util

- util.go
- util2.go
- util_test.go
- util2_test.go

I have a problem because all the file is associate with the package name util. So in sonarqube I have only the test file util_test.go ...

**Comment by bradfitz** [comment]
Sorry, the go tool won't do that out of the box, and it's too niche of a use case for us to add.

But fortunately the go/* packages in the standard library make it easy to write your own tool to discover the files in a package and parse them. Then you just need to walk the AST of the parsed functions and print out the associated filename for funcs starting with "Test".
