### ISSUE TITLE
Windows installer silently uninstalls the previous Go version

### ISSUE THREAD

**Issue by dlsniper** [golang/go#20679]
### What version of Go are you using (`go version`)?
1.9beta1

### What operating system and processor architecture are you using (`go env`)?
Windows 10 / amd64

### What did you do?
I've downloaded the latest and greatest Go version, 1.9beta 1 from the website, via this link: https://storage.googleapis.com/golang/go1.9beta1.windows-amd64.msi

When I've installed Go 1.9beta1, it silently uninstalled the previous Go version, 1.8.3, without prompting me if I wanted to do that or not, or without having at least a warning about removal of the previous version.

### What did you expect to see?
Keep my previous Go installation while I try the latest and greatest.

Actually, the best thing would be to install the new version and just ask me if I want to uninstall the previous version or not. Then ask me if I want to update anything else to point to the newest release or not. My IDE can deal with multiple Go versions, the Go should deal with multiple Go versions as well.

### What did you see instead?
Current stable release went away. Luckily I've made a copy of the Go 1.8.3 folder before installing 1.9beta1 as I remember the same thing happening from 1.7 to 1.8

Please let me know if you need further details and thank you all for the hard work on the Go project.

**Comment by bradfitz** [comment]
Dup of #16305.
