### ISSUE TITLE
build: upstream OpenBSD patches to master and/or Go 1.4 branch

### ISSUE THREAD

**Issue by henryas** [golang/go#20672]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go1.4.3

### What operating system and processor architecture are you using (`go env`)?
OpenBSD 386

### What did you do?
I downloaded Go1.4.3 source from Go's website and failed to build Go's toolchain (Go1.4.3) in my OpenBSD/386 machine. I made a post in [Golang Nuts](https://groups.google.com/forum/#!topic/golang-nuts/-SW8q-YHVp8) and Dave Cheney suggested to look for possible patches in OpenBSD's ports. It turned out that there are patches that exist in OpenBSD's version that do not exist in Go's official version.

The OpenBSD's version builds just fine on my machine, but the official version does not. 

I have included the OpenBSD port for Go1.4.3 for your reference and perhaps someone could integrate their patches into the official version.

Thanks

Henry
[go.tar.gz](https://github.com/golang/go/files/1075325/go.tar.gz)

**Comment by bradfitz** [comment]
This is probably an easier way to look at them:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/go/patches/

Looks like Joel (@4a6f656c) is the author or maintainer of them.

Joel, do you want to upstream them? We'd prefer if they were upstream.

**Comment by ALTree** [comment]
> I downloaded Go1.4.3 source from Go's website

This may be a silly question but... why? If you are bootstrapping, you should use  go1.4-bootstrap, *not* go1.4.3

**Comment by bradfitz** [comment]
@ALTree, I assumed the issue is that they're not on the 1.4 release branch, hence the necessary changes are not in the go1.4-bootstrap tarball.

**Comment by ALTree** [comment]
Ah, so you're asking them to upstream the changed to go1.4-bootstrap and then we'll publish a new bootstrap release? 

I thought you were asking them to apply the patches to go1.4.3 (which is unmaintained and it's not usable for bootstrapping, even on many linux system), that's why I was confused.

**Comment by bradfitz** [comment]
> Ah, so you're asking them to upstream the changes to go1.4-bootstrap and then we'll publish a new bootstrap release?

Yes.

**Comment by 4a6f656c** [comment]
@bradfitz - I did not realise that go1.4-bootstrap tarball existed and just stumbled across this issue. I'm more than happy to upstream the changes - what's the process for targeting the release-branch.go1.4 branch (I don't seem to be able to find any references re this)?

**Comment by ianlancetaylor** [comment]
Contributing to the 1.4 release branch is the same as the usual contribution process, but first run `git pull; git checkout release-branch.go1.4`.  Then you can `git change`, `git mail` as usual.

Note that the trybots do not work for the 1.4 release branch.  In fact, there's not much automated testing at all.

And, of course, patches must be minimal and completely safe.

**Comment by 4a6f656c** [comment]
@ianlancetaylor - ack, thanks.

**Comment by 4a6f656c** [comment]
@bradfitz I believe a new go1.4-release tarball can be rolled and this can then be closed out.

**Comment by 4a6f656c** [comment]
@bradfitz any chance of getting a new go1.4-release tarball spun?

**Comment by bradfitz** [comment]
Done. https://storage.googleapis.com/golang/go1.4-bootstrap-20171003.tar.gz

**Comment by bradfitz** [comment]
@broady, can you update the website with this?

Cherry-pick 79276 and 79936 to the release branch?

**Comment by bradfitz** [comment]
Looks like this is sufficiently done.

Let me know if I'm mistaken.
