### ISSUE TITLE
cmd/link: request backport for ppc64le linker fix to go 1.8

### ISSUE THREAD

**Issue by laboger** [golang/go#20670]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8.3

### What operating system and processor architecture are you using (`go env`)?
Ubuntu ppc64le

A fix went upstream related to linking programs on ppc64le, affecting the build of very large programs as are found in Kubernetes and openshift.  I'm requesting to backport this fix to the go 1.8 branch so it is in a go1.8.x, since many builds are still using go 1.8.x and will continue to use that version for a while.

The issue is #20497 fixed by CL  45130.  If this is approved, I can take care of doing the backport.

**Comment by bradfitz** [comment]
I'll let @ianlancetaylor decide.

But we may be closed enough to Go 1.9 that the answer might be to wait.

**Comment by ianlancetaylor** [comment]
I think it's OK to backport the CL for 1.8, but it's not enough to trigger a 1.8.4 release.  We may never do a 1.8.4 release.  I would suggest preparing the CL at your leisure, but don't commit it to the branch.

**Comment by laboger** [comment]
@jcajka The above CL is the Go 1.8 backport of the fix for openshift on ppc64le.

**Comment by rsc** [comment]
CL 45130 OK for Go 1.8.5.
It won't apply cleanly but this will be a good test.

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 70837](https://golang.org/cl/70837) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:49 UTC
