### ISSUE TITLE
encoding/xml: StartElement and EndElement should not match if prefix does not match

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#20685]
### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
StartElement and EndElement should not match if prefix does not match

go program used to test: (https://play.golang.org/p/3hUyUhbK5D)
~~~go
package main

import (
	"encoding/xml"
	"fmt"
	"io"
	"strings"
)

func main() {
	data := `<x:book xmlns:x="abcd" xmlns:y="abcd">one</y:book>`
	decoder := xml.NewDecoder(strings.NewReader(data))
	for {
		_, err := decoder.Token()
		if err != nil {
			if err != io.EOF {
				fmt.Println(err)
			}
			return
		}
	}
}
~~~

### What did you expect to see?
`XML syntax error on line 1: element <x:book> closed by </y:book>`

### What did you see instead?
``

Tested the same with xmllint program:

~~~bash
$ cat test.xml
<x:book xmlns:x="abcd" xmlns:y="abcd">one</y:book>
$ xmllint test.xml
test.xml:1: parser error : Opening and ending tag mismatch: book line 1 and book
<x:book xmlns:x="abcd" xmlns:y="abcd">one</y:book>
                                                  ^
~~~

**Comment by rsc** [comment]
Can you point to something in the XML spec that says that's invalid? It's certainly weird, but it seems possibly valid to me. x:book and y:book mean the same thing.

**Comment by santhosh-tekuri** [comment]
from https://www.w3.org/TR/REC-xml/#sec-starttags

~~~
[Definition: The end of every element that begins with a start-tag must be marked by an end-tag containing a name that echoes the element's type as given in the start-tag:]
~~~
 and name of start-tag is (https://www.w3.org/TR/REC-xml/#NT-STag)
~~~
STag	   ::=   	'<' Name (S Attribute)* S? '>'
~~~
similarly name of end-tag is (https://www.w3.org/TR/REC-xml/#NT-ETag)
~~~
ETag	   ::=   	'</' Name S? '>'
~~~

It means `Name` should literally match exactly in start and end tags

**Comment by santhosh-tekuri** [comment]
element's type means from spec:

~~~
The Name in the start- and end-tags gives the element's type
~~~

**Comment by santhosh-tekuri** [comment]
most straight forward mention (https://www.w3.org/TR/REC-xml/#sec-logical-struct)

~~~
Well-formedness constraint: Element Type Match

The Name in an element's end-tag must match the element type in the start-tag.
~~~

**Comment by santhosh-tekuri** [comment]
you can also test with https://validator.w3.org/#validate_by_input+with_options, to confirm

**Comment by opennota** [comment]
xmllint from libxml2 agrees:

``` xml
<r xmlns:x="http://example.org/ns" xmlns:y="http://example.org/ns">
	<x:a></y:a>
</r>
```

```
1.xml:2: parser error : Opening and ending tag mismatch: a line 2 and a
        <x:a></y:a>
                   ^
```

**Comment by iWdGo** [comment]
Push/pop of elements name must be done using the eventual prefix together with the tag name.
 The operation is moved before the translation of prefix into its URI.
 One end element of a test is fixed as expecting the last used namespace is incorrect.
 After closing a tag using a namespace, the valid namespace must be taken from the opening tag.
 Several tests added in the submitted fix.

**Comment by lelvisl** [comment]
may be it's time to review?

**Comment by lelvisl** [comment]
@rsc may be it's time to review https://golang.org/cl/109855 ?
