### ISSUE TITLE
Launchpad hosted backport for Ubuntu Xenial has terribly slow networking

### ISSUE THREAD

**Issue by tobiasmuehl** [golang/go#20683]
When installing go using the backport (`ppa:longsleep/golang-backports`) the download takes 10-30 mins because the network bandwith is terribly slow. This is the output from a DigitalOcean singapore VPS:

<img width="1250" alt="mintty_2017-06-15_13-37-04" src="https://user-images.githubusercontent.com/3341826/27168651-db2cc978-51d0-11e7-851e-3ff844993918.png">

**Comment by ALTree** [comment]
We don't distribute ubuntu packages and that ppa repository is not owned by the go project. I suggest opening an issue to launchpad.

**Comment by davecheney** [comment]
I'm going to close this, as @ALTree said, the ubuntu ppa archive is not something we control.
