### ISSUE TITLE
net: dial should not fail for legitimate urls that work in other languages e.g Redis URLs

### ISSUE THREAD

**Issue by joelpresence** [golang/go#20688]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?

Go cannot connect to a valid url like `redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:45678`.  This is a perfectly valid URL that conforms to [the redis scheme](https://www.iana.org/assignments/uri-schemes/prov/redis) and works just fine in other languages like Ruby.  Go fails to connect to this using Dial with an error like `"dial tcp: address redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:45678: too many colons in address` which seems to come from [ipsock.go](https://golang.org/src/net/ipsock.go).

Any suggestions as to how to fix go to connect to this URL?  Or how I can fix the url so that go can dial connect to it? I have tried using `[]` all over the place to no avail.

Thanks!  :-)

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by odeke-em** [comment]
@joelpresence here is how @garyburd connects to Redis in his project redigo https://github.com/garyburd/redigo/blob/master/redis/conn.go#L214-L266. He might have some input on this as well, if you please, @garyburd.

**Comment by vcabbage** [comment]
The example URL parses fine with [`url.Parse()`](https://golang.org/pkg/net/url/#Parse).

[`net.Dial()`](https://golang.org/pkg/net/#Dial) doesn't accept URLs:
> For TCP and UDP networks, addresses have the form host:port.

I'm going to go ahead an close this since it's not a bug.

**Comment by joelpresence** [comment]
Thanks. We're looking into it.  I see lots of issues around this with Go Lang failing on urls that look like this and the failures happen with many other services besides redis.  Also, Ruby handles this exact URL without issue ...

Any ideas?

Thanks!  :-)

Sent from my iPhone

On Jun 15, 2017, at 12:28 PM, Emmanuel T Odeke <notifications@github.com<mailto:notifications@github.com>> wrote:


@joelpresence<https://github.com/joelpresence> here is how @garyburd<https://github.com/garyburd> connects to Redis in his project redigo https://github.com/garyburd/redigo/blob/master/redis/conn.go#L214-L266. He might have some input on this as well, if you please, @garyburd<https://github.com/garyburd>.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by joelpresence** [comment]
Fixed using DialURL.  Thanks.
