### ISSUE TITLE
encoding/json: decoding performance regression in 1.9beta1

### ISSUE THREAD

**Issue by cespare** [golang/go#20693]
This is with these Go versions:

go version go1.8 linux/amd64
go version go1.9beta1 linux/amd64

The following benchmark unmarshals a JSON object which has a large sub-object that's irrelevant (it's associated with a key that isn't in the destination struct):

```
package main

import (
	"encoding/json"
	"fmt"
	"testing"
)

type T0 struct {
	Foo map[string]string
}

type T1 struct {
	Bar string
}

func Benchmark19Regression(b *testing.B) {
	junk := make(map[string]string)
	for i := 0; i < 100; i++ {
		junk[fmt.Sprintf("key%d", i)] = fmt.Sprintf("value%d", i)
	}
	input, err := json.Marshal(T0{Foo: junk})
	if err != nil {
		b.Fatal(err)
	}
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		var t T1
		if err := json.Unmarshal(input, &t); err != nil {
			b.Fatal(err)
		}
	}
}
```

It gets about 30% slower for me in Go 1.9.beta1:

```
name            old time/op    new time/op    delta
19Regression-4    20.8µs ± 3%    27.2µs ± 4%  +30.90%  (p=0.001 n=7+7)

name            old alloc/op   new alloc/op   delta
19Regression-4      336B ± 0%      328B ± 0%   -2.38%  (p=0.001 n=7+7)

name            old allocs/op  new allocs/op  delta
19Regression-4      5.00 ± 0%      4.00 ± 0%  -20.00%  (p=0.001 n=7+7)
```

You can also see that it's not due to increased allocations; they went down in 1.9.

**Comment by cespare** [comment]
I can investigate this later if nobody else gets to it first.

**Comment by cespare** [comment]
(Added to the 1.9 milestone since it was discovered while testing the 1.9 beta. Please fix it if that's not right.)

**Comment by vcabbage** [comment]
Appears to be https://github.com/golang/go/commit/df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7, the commit that removes the allocation, which causes this benchmark to be slower.

**Comment by bradfitz** [comment]
Thanks for the report @cespare and investigation @vcabbage.

I suppose we could just revert df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7 but then we lose some performance in some case too. But it'd at least be equivalent to Go 1.8. @cespare, could you locally do a manual revert and see what happens performance wise?

**Comment by bradfitz** [comment]
@pascaldekloe, could you investigate too?

**Comment by pascaldekloe** [comment]
Sorry guys, my holidays lasts till the 26th and there are no computers around. If the issue can wait then I'm happy to resolve this once home.

**Comment by cespare** [comment]
Yeah, reverting df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7 makes the performance hit go away and then some (but also makes allocations become equal again).

This benchmark compares 1.8 vs. [tip with df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7 reverted].

```
name            old time/op    new time/op    delta
19Regression-4    20.7µs ± 3%    19.0µs ± 5%  -8.47%  (p=0.008 n=5+5)

name            old alloc/op   new alloc/op   delta
19Regression-4      336B ± 0%      336B ± 0%    ~     (all equal)

name            old allocs/op  new allocs/op  delta
19Regression-4      5.00 ± 0%      5.00 ± 0%    ~     (all equal)
```

I wonder if there's some fix for the CPU time which can maintain the alloc improvement.

**Comment by cespare** [comment]
By the way, if it comes down to keeping or reverting df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7 for 1.9, I'd vote to keep it. This benchmark isn't critical for us and the benefit of reduced allocs helps us as well.

**Comment by pascaldekloe** [comment]
The root of the problem lies in that function `json.decodeState.value` leaves the state to as it was on the last applicable character. Such functionality requires read ahead for some literals. As a result we have workaround `json.decodeState.nextscan` with function `next` and `nextValue` [(original)](https://github.com/golang/go/commit/df68afd07ce67727bcc2ad8e4afaa42dbcbf58e7#diff-4299c3082a8bb7e546723132c992fa4cL366) in place. I'll try to eliminate the workaround.

**Comment by bradfitz** [comment]
@pascaldekloe, thanks.

**Comment by pascaldekloe** [comment]
Starting to work now. Probably too big of a change for the 1.9 beta release.

```
pascal@kloeq:~/code/go/src/encoding/json$ ~/go/bin/benchcmp -best old.txt new.txt
ignoring BenchmarkSkipValue-4: before has 1 instances, after has 0
benchmark                          old ns/op     new ns/op     delta
BenchmarkCodeEncoder-4             7255649       7435279       +2.48%
BenchmarkCodeMarshal-4             8206221       8677725       +5.75%
BenchmarkCodeDecoder-4             37897974      36089106      -4.77%
BenchmarkDecoderStream-4           399           396           -0.75%
BenchmarkCodeUnmarshal-4           38996655      38837326      -0.41%
BenchmarkCodeUnmarshalReuse-4      37276244      36200043      -2.89%
BenchmarkUnmarshalString-4         387           341           -11.89%
BenchmarkUnmarshalFloat64-4        356           308           -13.48%
BenchmarkUnmarshalInt64-4          317           256           -19.24%
BenchmarkIssue10335-4              448           407           -9.15%
BenchmarkUnmapped-4                1391          1043          -25.02%
BenchmarkNumberIsValid-4           30.5          29.2          -4.26%
BenchmarkNumberIsValidRegexp-4     920           929           +0.98%
BenchmarkEncoderEncode-4           246           253           +2.85%

benchmark                    old MB/s     new MB/s     speedup
BenchmarkCodeEncoder-4       267.44       260.98       0.98x
BenchmarkCodeMarshal-4       236.46       223.62       0.95x
BenchmarkCodeDecoder-4       51.20        53.77        1.05x
BenchmarkCodeUnmarshal-4     49.76        49.96        1.00x

benchmark                    old allocs     new allocs     delta
BenchmarkIssue10335-4        3              3              +0.00%
BenchmarkUnmapped-4          4              4              +0.00%
BenchmarkEncoderEncode-4     0              0              +0.00%

benchmark                    old bytes     new bytes     delta
BenchmarkIssue10335-4        312           184           -41.03%
BenchmarkUnmapped-4          344           216           -37.21%
BenchmarkEncoderEncode-4     0             0             +0.00%
pascal@kloeq:~/code/go/src/encoding/json$ git diff --stat HEAD
 src/encoding/json/decode.go       | 206 +++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------
 src/encoding/json/scanner.go      |  57 +---------------------------
 src/encoding/json/scanner_test.go |  37 -------------------
 3 files changed, 113 insertions(+), 187 deletions(-)
```

**Comment by rsc** [comment]
Please revert the change in question. Reducing allocated bytes by 2% (8 out of 336) is not worth a 30% CPU performance regression. Thanks.
