### ISSUE TITLE
gofmt doc, tab width=8

### ISSUE THREAD

**Issue by pierrre** [golang/go#20690]
### What version of Go are you using (`go version`)?
Not relevant

### What operating system and processor architecture are you using (`go env`)?
Not relevant

### What did you do?
Go to https://golang.org/cmd/gofmt/

### What did you expect to see?
A tab is just a tab, there is not width.

### What did you see instead?
> It uses tabs (width = 8) for indentation

**Comment by griesemer** [comment]
Fixed and duplicate of #19618.

**Comment by griesemer** [comment]
https://tip.golang.org/cmd/gofmt/ shows the corrected version.

**Comment by pierrre** [comment]
Sorry for the duplicate.
