### ISSUE TITLE
Set LD_LIBRARY_PATH while executing go test

### ISSUE THREAD

**Issue by lakb** [golang/go#20696]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.5.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/imsgit_local/work/lakb/CSCF/ims_common/icm/dashboard/rest/golang/"
GORACE=""
GOROOT="/imsgit/Tools/go_15/go_64"
GOTOOLDIR="/imsgit/Tools/go_15/go_64/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
### What did you do?

If possible, provide a recipe for reproducing the error.
I'm trying to run go test for main package using this command "go test -tags test". It is failing as it is not able to find some shared library. Is it possible to pass the relative path to shared libraries in command line? 

### What did you expect to see?
Go test should be executed successfully 

### What did you see instead?

/tmp/go-build732719419/server/_test/server.test: error while loading shared libraries: libDbi.so: cannot open shared object file: No such file or directory
exit status 127

**Comment by bradfitz** [comment]
Could you try Go 1.8 or Go 1.9beta1?

Go 1.5 is pretty old at this point.

Also, Go doesn't use libDbi.so, so this is something that your code is doing. Is your code available somewhere?

**Comment by lakb** [comment]
The module test is written for a CGO project. These are the libraries needed to compile the main package of the project.

**Comment by bradfitz** [comment]
> Is it possible to pass the relative path to shared libraries in command line?

No, sorry. You can use pkg-config, though.

For questions about Go, see https://golang.org/wiki/Questions.
