### ISSUE TITLE
archive/tar: Writer should not accept empty Xattrs values

### ISSUE THREAD

**Issue by cyphar** [golang/go#20698]
```
% go version
go version go1.8.3 linux/amd64
% go env
GOARCH="amd64"
GOBIN="/home/cyphar/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cyphar/.local"
GORACE=""
GOROOT="/usr/lib64/go/1.8"
GOTOOLDIR="/usr/lib64/go/1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build495773064=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

You can verify this at https://play.golang.org/p/T9jR4DO492. Here's the contents of the paste:

```go
package main

import (
	"archive/tar"
	"fmt"
	"io"
)

func main() {
	reader, writer := io.Pipe()

	tw := tar.NewWriter(writer)
	tr := tar.NewReader(reader)

	go func() {
		tw.WriteHeader(&tar.Header{
			Name: "somefile",
			Mode: 0777,
			Xattrs: map[string]string{
				"user.emptyvalue": "",
				"user.nonempty":   "some value",
			},
		})
		tw.Close()
	}()

	hdr, err := tr.Next()
	if err != nil {
		panic(err)
	}

	if value, ok := hdr.Xattrs["user.emptyvalue"]; !ok {
		fmt.Printf("expected user.emptyvalue to exist\n")
	} else if value != "" {
		fmt.Printf("expected user.emptyvalue to be '', got %q\n", value)
	}

	if value, ok := hdr.Xattrs["user.nonempty"]; !ok {
		fmt.Printf("expected user.nonempty to exist\n")
	} else if value != "some value" {
		fmt.Printf("expected user.nonempty to be 'some value', got %q\n", value)
	}
}
```

### What did you expect to see?
No output.

### What did you see instead?
```
expected user.emptyvalue to exist
```

This is happening on the reading, not writing side (which you can verify by dumping the generated `tar` archive to stdout). According this section of `archive/tar` it looks like this is intentional:

```go
		default:
			// According to PAX specification, a value is stored only if it is
			// non-empty. Otherwise, the key is deleted.
			if len(value) > 0 {
				extHdrs[key] = value
			} else {
				delete(extHdrs, key)
			}
		}
```

Which begs the question, should we be generating `xattrs` that aren't valid according to PAX or should we accept such headers? I don't really mind either way, but it seems quite odd that we are liberal in what we generate but strict in what we accept.

**Comment by dsnet** [comment]
The PAX "specification" says the following:
> If the <value> field is zero length, it shall delete any header
> block field, previously entered extended header value, or
> global extended header value of the same name.

Which means that zero-length values have a very specific meaning: deletion. So the correct solution is to prevent the `tar.Writer` from generating these bogus entries.

A lot of work happened on the `tar.Reader` in the Go1.8 cycle, and I was planning on vastly improving the writer in Go1.9, but really dropped the ball this cycle. Will attempt to [get the fix](https://github.com/dsnet/tar/blob/1a52fefb8040a4c8015c88bdc197afb134ed2562/strconv.go#L257) in Go1.10.
