### ISSUE TITLE
“<” in unquoted attr issues

### ISSUE THREAD

**Issue by MarsYong** [golang/go#20699]
When I use 1.7rc6 version of the time, my project is no problem. When I upgraded from 1.7rc6 to 1.8.3 ver,There is a problem
my OS is Ubuntu 16.04 , GOARCH=amd64 GOOS=linux
i'm use the gin web framework.
The Panic:  html/template:product.html: "<" in unquoted attr: "<#=hardwares[i].DeviceCode#"
and else
html/template:product.html: "<" in attribute name: " <#if(j==statuses[i].Value_type)"
Why in the 1.7rc6 version of the normal? How can i solve it?

**Comment by mvdan** [comment]
This issue doesn't contain enough information. Can you provide a program to reproduce the issue?

Have you brought this up with the gin project? This could well be a bug in there and not in Go itself.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

To use the bug tracker, you must use the bug template (which you deleted) and provide us with complete, reproducible information.

**Comment by MarsYong** [comment]
OK，thank you for the answer!
      I'm not sure that this is not related to gin, but certainly with the template rendering or symbol filtering has a relationship, I do not know the template rendering the underlying code is in gin or in the go itself. The same gin project I did not change any data, but in the 1.7rc6 version of the very good work.
      I guess this should not be caused by gin, this should be caused by the GC.

#go version
go version go1.8.3 linux/amd64

#go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mars/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build425550925=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

the panic (copy the console):

2017/06/17 06:43:46 [Recovery] panic recovered:
GET /product/id/11 HTTP/1.1
Host: 192.168.110.236
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8
Connection: keep-alive
Cookie: mysession=MTQ5NzY1MzAxMdfdfdsjkdjkKkjJKJKNsSkKKSJKJSjkJSWFJsVmFVak5YVVU5TlFWazNTVFpNTlZaWFdsZEpVVXBhU1RNMFZGWXpWRVJSU0VwVVdGRldOVkU9fOijIk3QpNWNVqZdB-nEMgXnCaaX0wh9BR3_7FfFnDfm; user_sess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc3Mzk0MTgsInkkjkJLKhhjHJHKKhkLjkjbSIsGFGFGVvbvvgInR5cGUiOiJzZXNzIn0.zF3jAfaqnHX0TyrbohxpKtpQ5LbDL9k97qF3QjhGRbQ
Referer: http://192.168.110.236/user/workspace
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0


html/template:product.html: "<" in attribute name: " <#if(j==statuses[i].Value_type)"
/usr/local/go/src/runtime/panic.go:489 (0x42bd9f)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:428 (0xa06c8f)
	(*Context).Render: panic(err)
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:437 (0xa06d30)
	(*Context).HTML: c.Render(code, instance)
/home/mars/golang/src/github.com/PandoCloud/pando-cloud/services/wwwhost/actions.go:259 (0xa4023f)
	GetProductById: r.HTML(http.StatusOK, "product.html", prod)
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/PandoCloud/pando-cloud/services/wwwhost/middleware.go:112 (0xa4f8f9)
	ValidateProductBelong.func1: r.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/PandoCloud/pando-cloud/services/wwwhost/middleware.go:253 (0xa50cf2)
	MustUser.func1: c.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/PandoCloud/pando-cloud/services/wwwhost/middleware.go:205 (0xa50a65)
	SetUser.func1: c.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/gin-contrib/sessions/sessions.go:65 (0xa175a4)
	Sessions.func1: c.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/gin-gonic/gin/recovery.go:45 (0xa1468a)
	RecoveryWithWriter.func1: c.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/gin-gonic/gin/logger.go:72 (0xa1395f)
	LoggerWithWriter.func1: c.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/context.go:97 (0xa052ea)
	(*Context).Next: c.handlers[c.index](c)
/home/mars/golang/src/github.com/gin-gonic/gin/gin.go:284 (0xa0b480)
	(*Engine).handleHTTPRequest: context.Next()
/home/mars/golang/src/github.com/gin-gonic/gin/gin.go:265 (0xa0ad9b)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2568 (0x68ca62)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1825 (0x688c62)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45a791)
	goexit: BYTE	$0x90	// NOP

the go code:
func GetProductById(r *gin.Context) {
	authUser := GetCUser(r)
	authProdouct := GetCProduct(r)
	prod := &ProductResponse{}
	prod.Navi.Workspace = true
	prod.Navi.Username = authUser.Username
	prod.Navi.UserAvatar = authUser.Avatar
	prod.Product = *authProdouct
	prod.Csrf, _ = token.New(token.CsrfToken, authUser.Username).Sign(authUser.AppKey)
	//fmt.Println(prod.Product)
	r.HTML(http.StatusOK, "product.html", prod)
	return
}
the html code:
<script>
            template.config('openTag','<#');
            template.config('closeTag','#>');
 </script>
<script id="template-custom-statuses" type="text/html">
<#for(var i in statuses){#>
	<div class="widget-status horizontal">
		<div class="input-wrap">
			<input class="input-status-name" placeholder="name" value="<#=statuses[i].Name?statuses[i].Name:''#>">	</div>
<select class="select-status">
	<#for(var j=1;j<id2type.length;++j){#>															       <option value="<#=j#>" <#if(j==statuses[i].Value_type){#>selected="selected"<#}#> > <#=id2type[j]#> </option><#}#>
</select>
</div>
<#}#>
 bodyDom.delegate('.btn-custom-addstatus','click',function(){
	 var parent=$(this).parent();
	 $(this).remove();     
	var data={{.prod.status}}
	 parent.append(template('template-custom-statuses',data));
	   parent.append(template('template-custom-addstatus',{}));
   });
Because the code is too much, I just did a sample process。

**Comment by MarsYong** [comment]
Because the code too much, I just made a sample process, hoping to give you help
