### ISSUE TITLE
x/build/devapp: migrate to GKE or Flex

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20691]
https://dev.golang.org/ is currently on App Engine classic and that's holding us back in a number of ways.

For one, it's Go 1.6 only.

But mostly it doesn't let us use maintner.

Before we do a number of other things we want to do, we need to migrate it to Flex or a GKE service.

According to @broady, we can't currently run an App Engine Flex app on *.golang.org due to some Google-internal configuration issues with our *.golang.org setup. See http://b/62618033 for details.

But we can run a Go webserver on GKE and route to that instead, like we do for:

https://maintner.golang.org/
https://pubsubhelper.golang.org/

That is my preference. We can always move to Flex later if it buys us anything.

/cc @andybons

**Comment by bradfitz** [comment]
Note that https://dev.golang.org/ has several dashboards, but we only need to work on porting the one that's often used for the initial migration.

The important one is:
https://dev.golang.org/release

The ones that can (and should) wait until later are:
https://dev.golang.org/cl
https://dev.golang.org/dash#all

Those last two are redundant and should be merged, be prettier, and use maintner to have live & better data.

And https://dev.golang.org/stats is not very useful at the moment. We can port it at some point, though. But don't let it block you.

**Comment by andybons** [comment]
dev.golang.org now points to the GKE app
