### ISSUE TITLE
 cmd/internal/obj/arm64: golang assembler handles arm64 instruction ldxp incorrectly.

### ISSUE THREAD

**Issue by zhangfannie** [golang/go#20697]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +59051da Fri Jun 16 06:05:57 2017 +0000 linux/arm64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fanzha02/go"
GORACE=""
GOROOT="/home/fanzha02/work/asm_test/golang_us/golang_1/golang"
GOTOOLDIR="/home/fanzha02/work/asm_test/golang_us/golang_1/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build468264647=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
cd src/cmd/asm/internal/asm
add arm64enc.s test file
enable the ARM64Encoder test command 
go test -run "ARM64Encoder"

arm64enc.s test file and endtoend_test.go you can load from this patch:
https://go-review.googlesource.com/c/45850/

### What did you expect to see?
go test successfully

### What did you see instead?
the ldxp/ldxpw test cases are failed

**Comment by bradfitz** [comment]
Did it work in Go 1.8?

If no, this is Go 1.10 material.
If yes, we could fix it for Go 1.9.

**Comment by zhangfannie** [comment]
Go 1.8 still does not work.
