### ISSUE TITLE
go1.9beta1: Time.String() format change not mentioned in the release notes

### ISSUE THREAD

**Issue by gottwald** [golang/go#20702]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
$ go1.9beta1 version
go version go1.9beta1 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/igottwald/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build074936866=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
```go
fmt.Println(time.Now())
```

### What did you expect to see?
`2017-06-16 14:09:27.033492377 +0200 CEST`

### What did you see instead?
`2017-06-16 14:09:27.033492377 +0200 CEST m=+0.000181181`

We had some old buggy code, that at some point relied on the `fmt.Stringer` representation of `time.Time` which is of course completely our fault and is now replaced by a proper `time.Format()`.
But maybe it should be mentioned in the release notes that the default string representation format of time.Time changes and should generally not be relied on.

**Comment by ALTree** [comment]
This may be too uninteresting to mention at the top of the page in the section dedicated to the new monotonic clock support but we could mention this in the 'minor changes' section. 

I sent https://go-review.googlesource.com/c/46011 (if we decide we want to do this).

cc @bradfitz
