### ISSUE TITLE
cmd/compile: "go", "type" excluded as import paths - still needed?

### ISSUE THREAD

**Issue by griesemer** [golang/go#20708]
Reminder issue. Investigate/document rationale for exclusion (see subr.go, func isbadimport). If implementation restriction, document in spec.

**Comment by odeke-em** [comment]
@griesemer you documented the reserved import paths in `cmd/compile`, however initially you mentioned that we should document this in the spec as per
> If implementation restriction, document in spec.

Should we reopen this issue and document this in the spec or am I interpreting the usage of the word "spec" literally, yet you meant document it in `cmd/compile/internal/gc/subr.go`?

**Comment by griesemer** [comment]
No. This is just an implementation detail because the compiler happens to use these link symbols. It could use anything else but doesn't at the moment.

**Comment by odeke-em** [comment]
Gotcha gotcha, thanks.
