### ISSUE TITLE
Website. Documentation

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#20716]
Please clarify the language for Go comments, Git comments in
*Contribution Guide*
https://golang.org/doc/contribute.html

In my point of view, the Go project expected - English language.

**Comment by mvdan** [comment]
If the documentation is in English, what other language would you expect?

**Comment by bradfitz** [comment]
I agree with @mvdan. If the site and docs and code are all in English, the answer as to what language the project uses is pretty obvious, even if implicit.

But maybe we both misunderstand the question.

Let us know if so.
