### ISSUE TITLE
x/tools/cmd/benchcmp: Add -tolerance flag

### ISSUE THREAD

**Issue by nicholasjackson** [golang/go#20726]
Running benchcmp on a CI server to detect anomalies relies on the user to parse the output from the command in order to pick up any deltas.  To make this process simpler I propose adding an additional flag to benchcmp `-tolerance=[Float64]` which would cause benchcmp to return a status code 1 when any of the delta percentages are greater than the tollerance.

```go
var (
	changedOnly = flag.Bool("changed", false, "show only benchmarks that have changed")
	magSort     = flag.Bool("mag", false, "sort benchmarks by magnitude of change")
	best        = flag.Bool("best", false, "compare best times from old and new")
	tolerance   = flag.Float64("tolerance", math.MaxFloat64, "return error if a delta is outside given value")
)
```

The state would be tracked across multiple deltas and types of benchmark under comparison i.e:

```go
if delta := cmp.DeltaAllocsPerOp(); !*changedOnly || delta.Changed() {
    if toleranceExceeded(delta, *tolerance) {
      tolerance_exceeded = true
    }
```

And if any delta is greater than the tolerance then exit code 1 and an error message would be returned.

```go
if tolerance_exceeded {
	fatal(fmt.Sprintf("Tolerance %.2f%% for one or more benchmarks exceeded", *tolerance))
}
```

An example of the implementation can be found on my fork of the tools [https://github.com/golang/tools/compare/master...nicholasjackson:nic/tollerance_flag](https://github.com/golang/tools/compare/master...nicholasjackson:nic/tollerance_flag)

Kind regards,

Nic

**Comment by ALTree** [comment]
`benchcmp` is pretty much deprecated in favour of `benchstat`, which is what you should use to compare benchmark results.

**Comment by nicholasjackson** [comment]
Ok, cheers, the situation with benchstat is the same regarding an exit code and CI, shall I close this and re-open on benchstat?

**Comment by ALTree** [comment]
How would this work for `benchstat`?

Note that `benchstat` has an `-alpha` flag that you can use to set the change significance threshold. Are you proposing that `benchstat` exits with code 1 everytime at least one benchmark is marked as 'changed in a statistically significant way'?

**Comment by nicholasjackson** [comment]
Yes, exactly, that would work, however that might cause unexpected behaviour for backward compatibility?

**Comment by ALTree** [comment]
I don't know if it'll be accepted, but sure. Please open a new issue with your updated request. Thanks!

**Comment by ALTree** [comment]
(I don't think we guarantee backward compatibility on things like the exit code of this kind of helper tool).

**Comment by nicholasjackson** [comment]
Thank you, I will open a new issue
