### ISSUE TITLE
blog: document Code generated convention in the Generating code blog post

### ISSUE THREAD

**Issue by mewmew** [golang/go#20720]
As the Go community has reached consensus on the convention to use for distinguishing machine-generated code (i.e. https://golang.org/s/generatedcode), it would be good if the [Generating code](https://blog.golang.org/generate) article on the Go blog was updated to reflect this. Preferably a link could also be added from the Generating code article to https://golang.org/s/generatedcode

In particular, the Generating code article is still using the convention `// generated by stringer -type Pill pill.go; DO NOT EDIT`. Since the blog post is the first hit (for me at least) on Google which searching for *generate code golang*, the article should in my opinion be updated so that new Gophers learn the newly established convention.

**Comment by bradfitz** [comment]
Sounds good. Feel free to send.

But I wouldn't link to https://golang.org/s/generatedcode, at least until we have a better target URL for that shortlink.

**Comment by mewmew** [comment]
Ok, I'll skip adding the link, but will send a CL for

```diff
-// generated by stringer -type Pill pill.go; DO NOT EDIT
+// Code generated by stringer -type Pill pill.go; DO NOT EDIT.
```

@bradfitz How far away is [maintner](https://github.com/golang/build/tree/master/maintner) from being able to convert GitHub pull requests to Gerrit CLs? I'd be happy to beta-test ;)

**Comment by bradfitz** [comment]
Far.

**Comment by agnivade** [comment]
@mewmew - PRs work now. Want to send one ?

**Comment by mewmew** [comment]
> @mewmew - PRs work now. Want to send one ?

@agnivade Done :)
