### ISSUE TITLE
cmd/link: slow on large inputs

### ISSUE THREAD

**Issue by gopherbot** [golang/go#2073]
by **remigius.gieben**:

<pre>This is *not* with the latest Go version, but with 1b38d90eebcd (release-branch.r58)
release/release.r58
For completeness I add the full p.6, I hope I find the time to narrow it down a bit.

What steps will reproduce the problem?
1. Take the p.6
2. Try to link it '6l p.6

What is the expected output?
An executable.

What do you see instead?
The linker takes a long time instead of being lightning fast. In fact I had to kill it,
because it just takes too long.

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
Linux (Ubuntu 11.04)

Which revision are you using?  (hg identify)
(release-branch.r58) release/release.r58

Please provide any additional information below.
I use Ragel to output Go code for a parser I'm creating. This parser works, but now I
run into this problem. It depends on my dns package, so for completeness I'll add that
too.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/2073/0/p.6">p.6</a> (9113 bytes)
2. <a href="https://storage.googleapis.com/go-attachment/2073/0/dns.a">dns.a</a> (4399774 bytes)

**Comment by josharian** [comment]
There's no source code here to reproduce with, and the object file format has changed, so testing with the attached object files is not possible. Closing as not reproducible. If you have continuing performance issues with the compiler or linker, please file a new issue with reproduction steps.
