### ISSUE TITLE
cmd/compile: slow bitmap generation for large array of zero-size elements

### ISSUE THREAD

**Issue by mdempsky** [golang/go#20739]
This (nonsense, but valid) program takes a very long time to compile because of stack bitmap generation:

    package f

    func F() {
        var x struct {
                x *int
                w [1e10][1e10][1e10][0]*int
                y *int
        }
        println(&x)
    }

The easy fix is to short-circuit generating stack bitmaps for zero-size types.

**Comment by meggamind** [comment]
Can I pick this issue ?

**Comment by mdempsky** [comment]
@meggamind Thanks, but I already have a fix + general cleanup for the issue. I would suggest another issue.

You're of course welcome to still look into it if you're just looking for practice working on the compiler.
