### ISSUE TITLE
runtime: use rwmutex for execLock

### ISSUE THREAD

**Issue by aclements** [golang/go#20738]
[CL 43713](https://golang.org/cl/43713) introduces a mutex around thread creation. We wanted to use rwmutex to avoid serializing thread creation, but rwmutex depends on semaphores, which depend on sudogs, which require allocation and write barriers, so we can't use them from `runtime.newm`.

We should try to figure out a way to fix this, possibly by rewriting rwmutex to not depend on semaphores.

/cc @ianlancetaylor @chipaca

**Comment by bcmills** [comment]
Broken link: [CL 43713](http://golang.org/cl/43713)
