### ISSUE TITLE
cmd/go: running get on a custom repo no longer works when upgrading to go 1.8.3

### ISSUE THREAD

**Issue by joegrasse** [golang/go#20731]
I ran the following with custom urls.

```go get -u -d customurl.com/lib/platform/genlog```
```get -u -d customurl.com/ext/daemon-example```

This worked with go 1.7.4 and fails with go 1.8.3.

With go 1.8.3, the first command works, but the second command fails with the following error.

Error: Get Failed: package customurl.com/lib/platform/genlog: customurl.com/lib/platform/genlog is a custom import path for https://mysvnrepo.com/PIM/golang/customurl.com/lib/platform/genlog/trunk, but /gopath/src/customurl.com/lib/platform/genlog is checked out from https://mysvnrepo.com/PIM

The package is actually downloaded though.

When doing a ```svn info https://mysvnrepo.com/PIM/golang/customurl.com/lib/platform/genlog/trunk```

I get the following.

```
Path: trunk
URL: https://mysvnrepo.com/PIM/golang/customurl.com/lib/platform/genlog/trunk
Repository Root: https://mysvnrepo.com/PIM
Repository UUID: 71ba88c3-99bc-4787-b7e4-f6bc34d7c3e8
Revision: 34403
Node Kind: directory
Last Changed Author: username
Last Changed Rev: 33154
Last Changed Date: 2017-01-27 09:05:49 -0600 (Fri, 27 Jan 2017)
```

I am guessing that the commit https://github.com/golang/go/commit/17ad60b8a4b92ee36f5b14c609ad1d0b5805b886 broke it.

/cc @rsc

**Comment by bradfitz** [comment]
We're currently frozen and wrapping up Go 1.9. If this was broken through the whole Go 1.8 cycle, it can probably wait until Go 1.10.

/cc @rsc though in case he has time to investigate.

**Comment by joegrasse** [comment]
I'm thinking line https://github.com/golang/go/blob/1363eeba6589fca217e155c829b2a7c00bc32a92/src/cmd/go/get.go#L405 should be changed from
```
if remote != repo && rr.isCustom {
```
to 
```
if ! strings.HasPrefix(repo, remote) && rr.isCustom {
```

/cc @rsc

**Comment by rsc** [comment]
What does `curl https://customurl.com/lib/platform/genlog` show as far as meta tags?

**Comment by joegrasse** [comment]
I am going to assume you mean ```curl https://customurl.com/lib/platform/genlog?go-get=1```.

```
<html>
<head>
<meta name="go-import" content="customurl.com/lib/platform/genlog svn https://mysvnrepo.com/PIM/golang/customurl.com/lib/platform/genlog/trunk">
</head>
<body>
go get customurl.com/lib/platform/genlog
</body>
</html>
```

**Comment by joegrasse** [comment]
@rsc Is there anything else you need from me? It would be really awesome if a fix didn't have to wait till go 1.10.

**Comment by rsc** [comment]
The relevant parts of the go command docs read:

> The meta tag has the form:
> 
>     <meta name="go-import" content="import-prefix vcs repo-root">
> 
> The import-prefix is the import path corresponding to the repository root. It must be a prefix or an exact match of the package being fetched with "go get". If it's not an exact match, another http request is made at the prefix to verify the &lt;meta> tags match.
> 
> The vcs is one of "git", "hg", "svn", etc.
>
> The repo-root is the root of the version control system containing a scheme and not containing a .vcs qualifier.
>
> For example,
> 
>     import "example.org/pkg/foo"
> 
> will result in the following requests:
>
>     https://example.org/pkg/foo?go-get=1 (preferred)
>     http://example.org/pkg/foo?go-get=1  (fallback, only with -insecure)
>
> If that page contains the meta tag
>
>     <meta name="go-import" content="example.org git https://code.org/r/p/exproj">
> 
> the go tool will verify that https://example.org/?go-get=1 contains the same meta tag and then git clone https://code.org/r/p/exproj into GOPATH/src/example.org.

The problem here is that the &lt;meta> tag being served does not name a Subversion repository root. Subversion is different from Git and Mercurial (and like CVS) in that you can check out a subtree, and it appears that that's what is being directed here. This is not really supported, at least according to the docs.

Whether we should support it, since it mostly works, is a different question. It looks like perhaps we should change the go/src/cmd/go/internal/get/vcs.go from looking for `"\nRepository Root: "` to look instead for `"\nURL: "`.
@joegrasse, can you try that and see if it fixes your use case?

I'm a bit reluctant to make a change at this point in the Go 1.9 cycle, but maybe it's OK if we can establish that (1) all recent subversions do print URL lines, and (2) if you do check out the repository root instead of a subdirectory, the URL and Repository Root lines say the same thing.

**Comment by joegrasse** [comment]
@rsc Making changes to vcs.go worked. Here is what i did.

```
$ git clone https://go.googlesource.com/go
$ cd go
$ git checkout go1.8.3
$ patch src/cmd/go/vcs.go ../issue-20731.patch
$ cd src
$ GOROOT_BOOTSTRAP=/usr/local/go ./all.bash
```

(1) I have svn version 1.7.21 and 1.8.14 and they both print out the URL.
(2) On my test of checking out the repo root, the URL and Repository Root lines said the same thing.


Contents of issue-20731.patch
```diff
--- vcs.go.old  2017-06-21 14:06:15.166391000 -0500
+++ vcs.go.new  2017-06-21 14:22:56.566029000 -0500
@@ -299,14 +299,14 @@

        // Expect:
        // ...
-       // Repository Root: <URL>
+       // URL: <URL>
        // ...

-       i := strings.Index(out, "\nRepository Root: ")
+       i := strings.Index(out, "\nURL: ")
        if i < 0 {
                return "", fmt.Errorf("unable to parse output of svn info")
        }
-       out = out[i+len("\nRepository Root: "):]
+       out = out[i+len("\nURL: "):]
        i = strings.Index(out, "\n")
        if i < 0 {
                return "", fmt.Errorf("unable to parse output of svn info")
```

**Comment by joegrasse** [comment]
@rsc I see that a patch has been committed. Will this end up making go 1.9?

**Comment by rsc** [comment]
Yes (unless a problem is discovered with it and it's rolled back).

**Comment by joegrasse** [comment]
Ok, thanks.
