### ISSUE TITLE
cmd/compile: missing "out of bounds" error slicing [0]T

### ISSUE THREAD

**Issue by josharian** [golang/go#20749]
```go
package p

func f() {
	var b [0]struct{}
	_ = b[2:]
}
```

gotype says:

```
x.go:5:8: index 2 (constant of type int) is out of bounds
```

cmd/compile gives no error. If you change b's type to `[1]struct{}`, the error from cmd/compile is:

```
x.go:5: invalid slice index 2 (out of bounds for 1-element array)
```

Reproduces with (at least) 1.7 and 1.8 and 1.9beta1.

**Comment by josharian** [comment]
Found with go-fuzz.

**Comment by ianlancetaylor** [comment]
gccgo says

```
foo8.go:5:8: error: array index out of bounds
  _ = b[2:]
        ^
```

**Comment by griesemer** [comment]
This is clearly a cmp/compile bug. Interestingly, the compiler complains for an index expression (`b[2]`) rather than a slice expression (`b[2:]`).

**Comment by griesemer** [comment]
Trivial fix. Moving to 1.9.
