### ISSUE TITLE
A unexpected result for integer channel 

### ISSUE THREAD

**Issue by lioasdfghjkl** [golang/go#20743]
### What version of Go are you using (`go version`)?

go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

windows/amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
etc.

### What did you do?

I test integer channel for my other service, than I got the unexpected result, this is example:

```go
package main

import (
	"fmt"
	"time"
)

var c chan int = make(chan int, 1)

func run() {
	a := 1 + <-c
	c <- a
}

func main() {
	c <- 0
	start := time.Now()
	for i := 0; i < 1000000; i++ {
		go run()
	}
	fmt.Println(time.Now().Sub(start), <- c)
}
```

Oh, I know this code can be using `atomic`, but I would been writing a service, it need integer channel.

### What did you expect to see?

I think it is thread-safe, than I will get a `time.Duration`, and a number that be 1000 000.

### What did you see instead?

I found results are sometimes wrong. Sometimes, It is less to 1000 000.

### Thanks

Thank you very much for seeing to here, if you know what happened to this code, please help me.

**Comment by mvdan** [comment]
This seems like a question or a request for help - I don't see a particular bug in Go or the standard library.

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by ALTree** [comment]
There's no guarantee that by the time your main reaches the `fmt.Println` statement all the 1000000 goroutines are done. In fact, the reason that you're seeing numbers < 1000000 is exactly that you're printing the number before all the 1000000 goroutines had a chance to run (and increment the number).
