### ISSUE TITLE
x/mobile: Build binaries for android.

### ISSUE THREAD

**Issue by jcgruenhage** [golang/go#20755]
It would be nice if we could build executable binaries for android using gomobile.

**Comment by cosmosgenius** [comment]
is the any article on how to do this?...I am able to build binary for android by using GOOS=linux GOARCH=arm go build. The binary works, but and libc api has problem since the default is to link with glibc i guess and android uses bionic. Is there a way to create a go binary linking to bionic?

**Comment by Festum** [comment]
+1
I'm seeking the way developing on Android too:)

**Comment by cosmosgenius** [comment]
Ok sort of figured out...
I am first building the ndk-toolchain using 
`$(ANDROID_NDK_ROOT)/build/tools/make_standalone_toolchain.py --arch ${ARCH} --api 19 --install-dir ${TOOLCHAIN_DIR}`

Then i needed to cross compile the golang std itself. 
`CC=$(TOOLCHAIN_DIR)/bin/clang CXX=$(TOOLCHAIN_DIR)/bin/clang GOOS=android GOARCH=$(ARCH) go install std`

Then build my own tool using.
`CC=$(TOOLCHAIN_DIR)/bin/clang CXX=$(TOOLCHAIN_DIR)/bin/clang GOOS=android GOARCH=$(ARCH) go build`

for anyone looking to do same for ios.
`CC=$(GOROOT)/misc/ios/clangwrap.sh CXX=$(GOROOT)/misc/ios/clangwrap.sh GOOS=darwin GOARCH=arm64 go build`

Hope it helps

**Comment by eliasnaur** [comment]
I'm going to close this. Building regular executables is out of scope for gomobile and can be done by setting up your own toolchains as demonstrated by @cosmosgenius.
