### ISSUE TITLE
net: duplicated code of resolution of hosts in `internetAddrList`

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#20767]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
master

### What did you do?

`Resolver. internetAddrList()` trying first to resolve the host as IPv4 then as IPv6 and only then to parse it with `Resolver. LookupIPAddr()`. *Although*, that's exactly what `Resolver. LookupIPAddr()` do anyway.

https://github.com/golang/go/blob/d8a7990ffad9aebfb7261df7afb3049da4a09986/src/net/ipsock.go#L253

### What did you expect to see?
`Resolver. internetAddrList()` should reuse the code by resolving the host only by `Resolver. LookupIPAddr()`

**Comment by mikioh** [comment]
I think it's fine to consolidate the code with the fix for #20790.
