### ISSUE TITLE
cmd/internal/obj/arm64: golang assembler handles arm64 instruction hlt/hvc/smc/brk/clrex incorrectly.

### ISSUE THREAD

**Issue by zhangfannie** [golang/go#20765]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +59051da Fri Jun 16 06:05:57 2017 +0000 linux/arm64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fanzha02/go"
GORACE=""
GOROOT="/home/fanzha02/work/asm_test/golang_us/golang_1/golang"
GOTOOLDIR="/home/fanzha02/work/asm_test/golang_us/golang_1/golang/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build468264647=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
cd src/cmd/asm/internal/asm
add arm64enc.s test file
enable the ARM64Encoder test command
go test -run "ARM64Encoder"

arm64enc.s test file and endtoend_test.go you can load from this patch:
https://go-review.googlesource.com/c/46438/1

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
go test successfully

### What did you see instead?
the hlt/hvc/smc/brk/clrex test cases are failed

**Comment by cherrymui** [comment]
> cd src/cmd/asm/internal/asm
add arm64enc.s test file
enable the ARM64Encoder test command
go test -run "ARM64Encoder"

Instead of throwing a big test in a pending CL, could you describe what the correct encoding should be, and what wrong encoding it currently generates? Thanks!

**Comment by zhangfannie** [comment]
@cherrymui  The test result of current assembly is as below.
--- FAIL: TestARM64Encoder (0.01s)
        endtoend_test.go:186: illegal combination 00172 (testdata/arm64enc.s:60)        BRK     $35943 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00268 (testdata/arm64enc.s:84)        CLREX   $4 ABCON0 NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00432 (testdata/arm64enc.s:130)       DCPS1   $11378 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00436 (testdata/arm64enc.s:131)       DCPS2   $10699 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00440 (testdata/arm64enc.s:132)       DCPS3   $24415 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00500 (testdata/arm64enc.s:147)       HLT     $65509 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00504 (testdata/arm64enc.s:148)       HVC     $61428 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00940 (testdata/arm64enc.s:306)       SMC     $37977 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00172 (testdata/arm64enc.s:60)        BRK     $35943 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00268 (testdata/arm64enc.s:84)        CLREX   $4 ABCON0 NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00432 (testdata/arm64enc.s:130)       DCPS1   $11378 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00436 (testdata/arm64enc.s:131)       DCPS2   $10699 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00440 (testdata/arm64enc.s:132)       DCPS3   $24415 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00500 (testdata/arm64enc.s:147)       HLT     $65509 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00504 (testdata/arm64enc.s:148)       HVC     $61428 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00940 (testdata/arm64enc.s:306)       SMC     $37977 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00172 (testdata/arm64enc.s:60)        BRK     $35943 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00268 (testdata/arm64enc.s:84)        CLREX   $4 ABCON0 NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00432 (testdata/arm64enc.s:130)       DCPS1   $11378 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00436 (testdata/arm64enc.s:131)       DCPS2   $10699 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00440 (testdata/arm64enc.s:132)       DCPS3   $24415 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00500 (testdata/arm64enc.s:147)       HLT     $65509 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00504 (testdata/arm64enc.s:148)       HVC     $61428 MOVCON NONE NONE, 4 0
        endtoend_test.go:186: illegal combination 00940 (testdata/arm64enc.s:306)       SMC     $37977 MOVCON NONE NONE, 4 0
        endtoend_test.go:228: 00172 (testdata/arm64enc.s:60)    BRK     $35943: have encoding 000020d4, want e08c31d4
        endtoend_test.go:228: 00268 (testdata/arm64enc.s:84)    CLREX   $4: have encoding 5f3f03d5, want 5f3403d5
        endtoend_test.go:228: 00432 (testdata/arm64enc.s:130)   DCPS1   $11378: have encoding 0100a0d4, want 418ea5d4
        endtoend_test.go:228: 00436 (testdata/arm64enc.s:131)   DCPS2   $10699: have encoding 0200a0d4, want 6239a5d4
        endtoend_test.go:228: 00440 (testdata/arm64enc.s:132)   DCPS3   $24415: have encoding 0300a0d4, want e3ebabd4
        endtoend_test.go:228: 00500 (testdata/arm64enc.s:147)   HLT     $65509: have encoding 000040d4, want a0fc5fd4
        endtoend_test.go:228: 00504 (testdata/arm64enc.s:148)   HVC     $61428: have encoding 020000d4, want 82fe1dd4
        endtoend_test.go:228: 00940 (testdata/arm64enc.s:306)   SMC     $37977: have encoding 030000d4, want 238b12d4
