### ISSUE TITLE
cmd/go: rethink 'go get' skipping test-only packages

### ISSUE THREAD

**Issue by rsc** [golang/go#20760]
Issue #15093 complained that go get x.com/y/... can match (via the wildcard) a directory x.com/y/z that only has tests in it, and then the 'go get' fails, because it cannot run 'go install x.com/y/z'. A fix was made for that CL, which silences the reporting of the "no Go files" error in x.com/y/z during 'go get', provided there are test files in that directory.

That fixes the problem reported, but it introduces other problems:

1. It makes go get behave differently from go install, even though get is defined as download + install.
2. go get x.com/y/z probably _should_ report the error, while 'go get x.com/y/...' might reasonably omit it.
3. If x.com/y/p incorrectly imports x.com/y/z, the error building z is not reported, and p silently fails to build, and the overall go get exits 0 as if everything was OK.
4. The fix was considered only TestGoFiles and not XTestGoFiles.

A pending CL of mine will address 3 and 4; we should reconsider 1 and 2 at some later point.

**Comment by jessfraz** [comment]
sorry i made the fix for the original "bug" let me know if I can help
