### ISSUE TITLE
Cross Compile Error 

### ISSUE THREAD

**Issue by phoenix043030** [golang/go#20761]
Please answer these questions before submitting your issue. Thanks!

Cross Compile Error 

### What version of Go are you using (`go version`)?

bootstrap version 1.4.2

go version 1.7.4

### What operating system and processor architecture are you using (`go env`)?

macOS Sierra

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Error Msg:

go/build
cmd/go
unexpected fault address 0x24388ffe88d
fatal error: fault
[signal 0xb code=0x1 addr=0x24388ffe88d pc=0x2c9ac1]

goroutine 1 [running]:
runtime.gothrow(0x5a8ac0, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc209539ba8 sp=0xc209539b90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:29 +0x261 fp=0xc209539bf8 sp=0xc209539ba8
bootstrap/compile/internal/ssa.decomposeUser(0xc20b153770)
	/usr/local/go/src/cmd/compile/internal/ssa/decompose.go:181 +0xe1 fp=0xc209539e80 sp=0xc209539bf8
bootstrap/compile/internal/ssa.Compile(0xc20b153770)
	/usr/local/go/src/cmd/compile/internal/ssa/compile.go:64 +0x510 fp=0xc20953d580 sp=0xc209539e80
bootstrap/compile/internal/gc.buildssa(0xc209863710, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:232 +0x14cd fp=0xc20953d8e0 sp=0xc20953d580
bootstrap/compile/internal/gc.compile(0xc209863710)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:405 +0x8a2 fp=0xc20953db30 sp=0xc20953d8e0
bootstrap/compile/internal/gc.funccompile(0xc209863710)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x1be fp=0xc20953dba8 sp=0xc20953db30
bootstrap/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:467 +0x27fe fp=0xc20953de80 sp=0xc20953dba8
bootstrap/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:93 +0x668 fp=0xc20953dec0 sp=0xc20953de80
main.main()
	/usr/local/go/src/cmd/compile/main.go:33 +0x17b fp=0xc20953df98 sp=0xc20953dec0
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20953dfe0 sp=0xc20953df98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20953dfe8 sp=0xc20953dfe0
failed MSpanList_Insert 0x2cc970 0x243896531b0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x27050b)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0xc20802dc98 sp=0xc20802dc68
runtime.MSpanList_Insert(0x28b818, 0x2cc970)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f fp=0xc20802dcc0 sp=0xc20802dc98
MHeap_FreeSpanLocked(0x28b5a0, 0x2cc970, 0x101)
	/usr/local/go/src/runtime/mheap.c:581 +0x147 fp=0xc20802dd00 sp=0xc20802dcc0
runtime.MHeap_FreeStack(0x28b5a0, 0x2cc970)
	/usr/local/go/src/runtime/mheap.c:518 +0x9f fp=0xc20802dd20 sp=0xc20802dd00
poolfree(0xc20817c000, 0x296901)
	/usr/local/go/src/runtime/stack.c:113 +0xe0 fp=0xc20802dd48 sp=0xc20802dd20
runtime.stackcache_clear(0x2c6000)
	/usr/local/go/src/runtime/stack.c:180 +0x74 fp=0xc20802dd78 sp=0xc20802dd48
flushallmcaches()
	/usr/local/go/src/runtime/mgc0.c:1225 +0x6f fp=0xc20802dda0 sp=0xc20802dd78
markroot(0xc208010000, 0x4)
	/usr/local/go/src/runtime/mgc0.c:536 +0x20a fp=0xc20802de00 sp=0xc20802dda0
runtime.parfordo(0xc208010000)
	/usr/local/go/src/runtime/parfor.c:76 +0xb2 fp=0xc20802de80 sp=0xc20802de00
gc(0xc20802dfb8)
	/usr/local/go/src/runtime/mgc0.c:1442 +0x25e fp=0xc20802df98 sp=0xc20802de80
runtime.gc_m()
	/usr/local/go/src/runtime/mgc0.c:1371 +0xe0 fp=0xc20802dfd0 sp=0xc20802df98
runtime.onM(0xc208012000)
	/usr/local/go/src/runtime/asm_amd64.s:257 +0x68 fp=0xc20802dfd8 sp=0xc20802dfd0
runtime.mstart()
	/usr/local/go/src/runtime/proc.c:818 fp=0xc20802dfe0 sp=0xc20802dfd8

goroutine 12 [garbage collection]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc2081a3500 sp=0xc2081a34f8
runtime.gogc(0x0)
	/usr/local/go/src/runtime/malloc.go:469 +0x1cf fp=0xc2081a3538 sp=0xc2081a3500
runtime.mallocgc(0x20, 0x17a880, 0xc200000000, 0x20000000001)
	/usr/local/go/src/runtime/malloc.go:341 +0x391 fp=0xc2081a35e8 sp=0xc2081a3538
runtime.newobject(0x17a880, 0xc2081a364c)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0xc2081a3610 sp=0xc2081a35e8
os.(*Process).wait(0xc20af8d9a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:32 +0x2ab fp=0xc2081a36c0 sp=0xc2081a3610
os.(*Process).Wait(0xc20af8d9a0, 0xc20aef6900, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a fp=0xc2081a36e8 sp=0xc2081a36c0
os/exec.(*Cmd).Wait(0xc208066780, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c fp=0xc2081a37b8 sp=0xc2081a36e8
os/exec.(*Cmd).Run(0xc208066780, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:246 +0x71 fp=0xc2081a37e8 sp=0xc2081a37b8
main.run(0xc20af8ce60, 0x18, 0x3, 0xc20aef66c0, 0x22, 0x24, 0x0, 0x0)
	/usr/local/go/src/cmd/dist/util.go:101 +0x328 fp=0xc2081a3900 sp=0xc2081a37e8
main.install(0x1a3490, 0x6)
	/usr/local/go/src/cmd/dist/build.go:703 +0x2f71 fp=0xc2081a3fd0 sp=0xc2081a3900
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2081a3fd8 sp=0xc2081a3fd0
created by main.cmdbootstrap
	/usr/local/go/src/cmd/dist/build.go:1063 +0x7a4

goroutine 1 [chan receive]:
runtime.gopark(0x65240, 0xc208062478, 0x1afaf0, 0xc)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20817eb58 sp=0xc20817eb28
runtime.goparkunlock(0xc208062478, 0x1afaf0, 0xc)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20817eb80 sp=0xc20817eb58
runtime.chanrecv(0x1337e0, 0xc208062420, 0x0, 0xf201, 0xc208040000)
	/usr/local/go/src/runtime/chan.go:410 +0x452 fp=0xc20817ec20 sp=0xc20817eb80
runtime.chanrecv1(0x1337e0, 0xc208062420, 0x0)
	/usr/local/go/src/runtime/chan.go:311 +0x2b fp=0xc20817ec50 sp=0xc20817ec20
main.cmdbootstrap()
	/usr/local/go/src/cmd/dist/build.go:1065 +0x828 fp=0xc20817ed80 sp=0xc20817ec50
main.xmain()
	/usr/local/go/src/cmd/dist/main.go:43 +0x240 fp=0xc20817ee90 sp=0xc20817ed80
main.main()
	/usr/local/go/src/cmd/dist/util.go:496 +0x51b fp=0xc20817ef98 sp=0xc20817ee90
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20817efe0 sp=0xc20817ef98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20817efe8 sp=0xc20817efe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x65240, 0x27dbd0, 0x1b0e50, 0xf)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x27dbd0, 0x1b0e50, 0xf)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/usr/local/go/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x65240, 0x2850d0, 0x1abb90, 0xd)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x2850d0, 0x1abb90, 0xd)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/local/go/src/runtime/mgc0.c:1386

goroutine 4 [finalizer wait]:
runtime.gopark(0x65240, 0x2850c8, 0x1b0850, 0xe)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208019730 sp=0xc208019700
runtime.goparkunlock(0x2850c8, 0x1b0850, 0xe)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc208019758 sp=0xc208019730
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:727 +0xba fp=0xc2080197e0 sp=0xc208019758
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
created by runtime.createfing
	/usr/local/go/src/runtime/malloc.go:707 +0x5e

goroutine 5 [select]:
runtime.gopark(0x47750, 0xc208018748, 0x1a75f0, 0x6)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208018560 sp=0xc208018530
runtime.selectgoImpl(0xc208018748, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:366 +0xb2c fp=0xc2080186f8 sp=0xc208018560
runtime.selectgo(0xc208018748)
	/usr/local/go/src/runtime/select.go:183 +0x12 fp=0xc208018718 sp=0xc2080186f8
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:150 +0x148 fp=0xc2080187e0 sp=0xc208018718
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:143 +0x58

goroutine 6 [select]:
runtime.gopark(0x47750, 0xc208018f48, 0x1a75f0, 0x6)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208018d60 sp=0xc208018d30
runtime.selectgoImpl(0xc208018f48, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:366 +0xb2c fp=0xc208018ef8 sp=0xc208018d60
runtime.selectgo(0xc208018f48)
	/usr/local/go/src/runtime/select.go:183 +0x12 fp=0xc208018f18 sp=0xc208018ef8
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:150 +0x148 fp=0xc208018fe0 sp=0xc208018f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:143 +0x58

goroutine 7 [select]:
runtime.gopark(0x47750, 0xc208019f48, 0x1a75f0, 0x6)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208019d60 sp=0xc208019d30
runtime.selectgoImpl(0xc208019f48, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:366 +0xb2c fp=0xc208019ef8 sp=0xc208019d60
runtime.selectgo(0xc208019f48)
	/usr/local/go/src/runtime/select.go:183 +0x12 fp=0xc208019f18 sp=0xc208019ef8
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:150 +0x148 fp=0xc208019fe0 sp=0xc208019f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fe8 sp=0xc208019fe0
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:143 +0x58

goroutine 8 [select]:
runtime.gopark(0x47750, 0xc20801af48, 0x1a75f0, 0x6)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801ad60 sp=0xc20801ad30
runtime.selectgoImpl(0xc20801af48, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:366 +0xb2c fp=0xc20801aef8 sp=0xc20801ad60
runtime.selectgo(0xc20801af48)
	/usr/local/go/src/runtime/select.go:183 +0x12 fp=0xc20801af18 sp=0xc20801aef8
main.bghelper()
	/usr/local/go/src/cmd/dist/util.go:150 +0x148 fp=0xc20801afe0 sp=0xc20801af18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe8 sp=0xc20801afe0
created by main.bginit
	/usr/local/go/src/cmd/dist/util.go:143 +0x58

**Comment by phoenix043030** [comment]
bootstrap version 1.4.2 -> 1.7.4  Fixed

**Comment by mikioh** [comment]
Dup of #16570, see https://github.com/golang/go/wiki/Darwin
