### ISSUE TITLE
net: `Resolver.resolveAddrList()` should be public

### ISSUE THREAD

**Issue by AlmogBaku** [golang/go#20783]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
master

### What did you expect to see?
This function is very useful therefore it should be public.

### What did you see instead?
`Resolver.resolveAddrList()` is private

**Comment by bradfitz** [comment]
Being subjectively useful to one person is not the bar for making something public.

If you want to push this forward, please go through the proposal process (https://golang.org/s/proposal) and file a new bug with a more substantive proposal and try to quantify the benefit and that it outweighs the costs of extra API bloat & docs. Approximately how many existing users in the Github corpus would benefit? Which existing bugs would this fix? What features would this enable?

Anything more than "is very useful [to me] therefore it should be public".

I'm going to close this for now, but feel free to reply or file a new issue if you collect more data.
