### ISSUE TITLE
Go 1.8.3 function redeclared

### ISSUE THREAD

**Issue by jeffguorg** [golang/go#20798]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```go version go1.8.3 windows/amd64```

### What operating system and processor architecture are you using (`go env`)?
go env
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
```
Windows build: 
    ```Win10 Pro Insider Preview 1703(16215.1000)```

### What did you do?

>If possible, provide a recipe for reproducing the error.
>A complete runnable program is good.
>A link on play.golang.org is best.

Tried to run a hello world after installing go. 

### What did you expect to see?
A compiled executable binary program 

### What did you see instead?
I installed Go on my Win today. I found it weird that VS Code cannot install packages correctly so I tried to write a simplest hello world. But the problem is still there. And this is the compiler's output:
```
# runtime
D:\Go\src\runtime\lfstack_amd64.go:16: lfstackPack redeclared in this block
	previous declaration at D:\Go\src\runtime\lfstack_64bit.go:37
D:\Go\src\runtime\lfstack_amd64.go:20: lfstackUnpack redeclared in this block
	previous declaration at D:\Go\src\runtime\lfstack_64bit.go:41
D:\Go\src\runtime\os_windows.go:14: _NSIG redeclared in this block
	previous declaration at D:\Go\src\runtime\os2_windows.go:18
D:\Go\src\runtime\os_windows.go:96: _AddVectoredExceptionHandler redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _CloseHandle redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _CreateEventA redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _CreateIoCompletionPort redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _CreateThread redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _CreateWaitableTimerA redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: _DuplicateHandle redeclared in this block
	previous declaration at D:\Go\src\runtime\os1_windows.go:92
D:\Go\src\runtime\os_windows.go:96: too many errors
github.com/nsf/gocode (download)
runtime
```

**Comment by ALTree** [comment]
This usually happens when you have borked your go installation by mixing toolchains with different versions. Please try to remove all the toolchains and pkg folders you have and reinstall go from scratch.

> If you are upgrading from an older version of Go you must first remove the existing version.
To remove an existing Go installation from your system delete the go directory. This is usually /usr/local/go under Linux, Mac OS X, and FreeBSD or c:\Go under Windows.

**Comment by ianlancetaylor** [comment]
The file runtime/lfstack_amd64.go existed in Go 1.6 but was removed in Go 1.7 and Go 1.8.  Something has gone wrong with your source tree.

Closing because there is nothing we can do to fix this.
