### ISSUE TITLE
flag: better support for multi-line help messages

### ISSUE THREAD

**Issue by chmike** [golang/go#20799]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?
```
myParam1 := flag.Int("param1", 0, "parameter 1 line 1\nparameter 1 line2")
myParam2 := flag.Int("param2", 0, "parameter 2")
```
### What did you expect to see?
```
Usage of xxx:
   -param1 int
    	parameter 1 line 1
        parameter 1 line 2
   -param2 int
    	parameter 2
```

### What did you see instead?
```
Usage of xxx:
   -param1 int
    	parameter 1 line 1
parameter 1 line 2
   -param2 int
    	parameter 2
```

**Comment by rsc** [comment]
/cc @robpike 

We already do something similar for testing.T.Logf and friends. Maybe it would be OK to do here too.
