### ISSUE TITLE
net/http: DetectContentType does not detect ttf fonts

### ISSUE THREAD

**Issue by watermelonjuice** [golang/go#20808]
Go's DetectContentType is detecting ttf fonts as application/octet-stream. Acceptable content types for tff fonts would be:
font/ttf
application/ttf
application/x-ttf
application/truetype
application/font
application/font-sfnt

Related: https://github.com/mholt/caddy/issues/1729
Tagging: @mholt

**Comment by bradfitz** [comment]
It does seem that the mimesniff spec includes fonts:
https://mimesniff.spec.whatwg.org/#matching-a-font-type-pattern

/cc @odeke-em

**Comment by odeke-em** [comment]
Thanks @watermelonjuice and @bradfitz, I'll work on it.

**Comment by odeke-em** [comment]
@watermelonjuice @mholt could someone help me with an MS FontObject sample?
