### ISSUE TITLE
database/sql/driver: ErrBadConn hides underlying error message

### ISSUE THREAD

**Issue by captncraig** [golang/go#20807]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go 1.8.3

### What did you do?

`database/sql/driver` defines `ErrBadConn` that a driver should return if a connection is rendered unusable. The mssql driver [recently merged a pr](https://github.com/denisenkom/go-mssqldb/pull/269) to use this in more instances. It corrected a few intermittent issues I was having with bad connection reuse, it now gives error messages that are almost completely unhelpful.

Where I used to have things like "IO timeout" returned to the user code, I now only get "driver: bad connection". This seems unavoidable at present because `ErrBadConn` is defined simply as:

`var ErrBadConn = errors.New("driver: bad connection")`

Ideally, the driver would be able to return any error message it likes, while still being able to signal to the database/sql package to not reuse this connections. 

I have a couple of ideas for this perhaps:

1. Allow drivers to return an error that implements some other interface. Perhaps `interface{ IsBadConn() bool}` or something. Could be exported or unexported. 
2. Have a wrapper type available in the `driver` package. Maybe something like `type BadConnError struct{ error }`. Or perhaps an unexported type with a `func WrapAsBadConn(err error) error` to create them.

In either case, the usages of `err == driver.ErrBadConn` would likely be replaced with a call to `driver.IsBadConn(err)` or similar, which would perform the additional type checks.

Does this make any sense? Would you be likely to consider a change to this effect for go 1.10? 

I don't envision it being a largely impactful change, except perhaps if someone outside the std lib is ever checking errors for equality with `driver.ErrBadConn`. It is a possibility I suppose.

**Comment by kardianos** [comment]
@captncraig Thanks for filing this here.

The other alternative is to return the original error while marking the connection internally as a bad connection. Then when it is requested again, from the pool the driver.ErrBadConn is returned. I would however prefer to avoid that. It prevents the connection pool from making intelligent decisions and introduces latency on the hot query path.

If we did this, I would be okay with either solution. I'd probably go with the one that could be implemented more efficiently at runtime (which test is more efficient). Though all else equal I'd lean towards the IsBadConn interface.

**Comment by captncraig** [comment]
I guess yet another alternative would be something on the context that the driver can interact with to signal a connection is bad.

So driver could do something like:

```
if err != nil{
   // instead of 
   // return driver.ErrBadConn
   driver.GetBadConnThing(ctx).MarkBad()
   return err
}
```

I kinda like that as well, but it has some odd complexity. And I have no idea what to call it.
