### ISSUE TITLE
cmd/compile: unexpected "slice bounds out of range" panic on GOOS=nacl with inlining

### ISSUE THREAD

**Issue by shurcooL** [golang/go#20811]
The following program panics on the playground (and the playground only):

https://play.golang.org/p/XXdD7dPPc4

```
4398046511104
0
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()
	/tmp/sandbox960033620/main.go:13 +0x1c0
```

But it shouldn't. On a 32-bit environment, `int(i)` is 0, so `v[n : n+3]` should be an okay slice of length 3.

It does not panic for me locally with Go 1.8.3, nor 1.9beta2, when running with `GOARCH=386`.

It also doesn't panic if either of the two commented lines are uncommented. Feels related to inlining.

Is it a bug on the playground?

**Comment by mvdan** [comment]
Perhaps related to `GOOS=nacl`? https://play.golang.org/p/czys1gPicX

**Comment by cherrymui** [comment]
I guess it is more due to GOARCH=amd64p32 than GOOS=nacl. I'll take a look.

**Comment by mdempsky** [comment]
Yeah, I think amd64p32 bug as well. Somewhat more minimized test case:

https://play.golang.org/p/7TrGkx7nM9

It looks like we're not correctly handing int64 => int conversions on amd64p32 in some cases.

**Comment by mdempsky** [comment]
@cherrymui It looks like an SSA bug to me, so I'm happy to let you take it from here.

**Comment by cherrymui** [comment]
Yeah, it looks like an SSA bug. `IsInBounds` is lowered to `CMPQ`, which should be `CMPL`.

Thank you for minimizing test case!
