### ISSUE TITLE
x/build/cmd/gopherbot: auto-remove old Needs labels

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20819]
Feature request from @rsc:

When gopherbot sees a Needs-Foo label added, remove any earlier Needs-Bar label.

**Comment by bradfitz** [comment]
Okay, between https://golang.org/cl/47134 and https://golang.org/cl/47133, this now reacts immediately, subsecond.

**Comment by rsc** [comment]
Awesome, thanks.
