### ISSUE TITLE
make.bash issue with 'GOROOT="$GOROOT_BOOTSTRAP" GOOS="" '

### ISSUE THREAD

**Issue by burkett123** [golang/go#20815]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3 from tar file, go1.8.3.src.tar.gz

### What operating system and processor architecture are you using (`go env`)?
RHEL 7.3, x86_64

### What did you do?
run the following, with 'yum install golang to get go 1.6 as bootstrap', GOROOT_BOOTSTRAP=/ ./all.bash

Added two lines for debugging to source:
echo '##### Building Go bootstrap tool.'
echo cmd/dist
export GOROOT="$(cd .. && pwd)"
#!#
echo GOROOT: $GOROOT
#!# 
GOROOT_BOOTSTRAP=${GOROOT_BOOTSTRAP:-$HOME/go1.4}
#!#
echo GOROOT_BOOTSTRAP: $GOROOT_BOOTSTRAP
#!#
if [ ! -x "$GOROOT_BOOTSTRAP/bin/go" ]; then

OUTPUT IS:
[root@gogs src]# GOROOT_BOOTSTRAP=/ ./all.bash
##### Building Go bootstrap tool.
cmd/dist
GOROOT: /opt/repo/golang-1.8.3/src
GOROOT_BOOTSTRAP: /
cmd/dist/build.go:8:2: cannot find package "bytes" in any of:
	/src/bytes (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:9:2: cannot find package "encoding/json" in any of:
	/src/encoding/json (from $GOROOT)
	($GOPATH not set)
cmd/dist/test.go:9:2: cannot find package "errors" in any of:
	/src/errors (from $GOROOT)
	($GOPATH not set)
cmd/dist/build.go:10:2: cannot find package "flag" in any of:
	/src/flag (from $GOROOT)
	($GOPATH not set)

If possible, provide a recipe for reproducing the error.
repoduce with standard build process I believe.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
the compile run.

### What did you see instead?
Errors shown above, GOROOT is overwritten on the command line in make.bash here:

rm -f cmd/dist/dist
GOROOT="$GOROOT_BOOTSTRAP" GOOS="" GOARCH="" "$GOROOT_BOOTSTRAP/bin/go" build -o cmd/dist/dist ./cmd/dist

Don't hink that GOROOT should be set to GOROOT_BOOTSTRAP.

**Comment by davecheney** [comment]
I'm sorry, the version of Go shipped with your operating system
distribution is not suitable for bootstrapping.

I suggest downloading the go 1.8 tarball, unpacking it somewhere, and using
that as the bootstrap version.

**Comment by bradfitz** [comment]
Yeah, GOROOT_BOOTSTRAP must point to a valid GOROOT path.

Let's move this discussion to the mailing list if you're still having problems compiling Go. See https://golang.org/wiki/Questions.
