### ISSUE TITLE
Website documentation

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#20828]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=Z:\GoPath
set GORACE=
set GOROOT=E:\Program Fles\Go
set GOTOOLDIR=E:\Program Fles\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?

Try to find documentation on website about:
"go:integrate"
"go:generate"
and etc...

### What did you expect to see?

Don`t foud one atricle or one part of documentation about all allowable features.

### What did you see instead?

Special part on page https://golang.org/doc/ with common and clear information about that annotations.

**Comment by cznic** [comment]
I don't know what `"go:integrate"` is but googling for `go generate` or even for `"go:generate"` actually gives me the result within golang.org domain as the very first result. Another search term working perfectly is, for example, `go generate site:golang.org`.

What search queries have you actually used?

**Comment by bradfitz** [comment]
go generate is documented at https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source

go integrate does not exist.

Can you explain more what the problem is?

**Comment by Konstantin8105** [comment]
Excu me, I mean // +build integration

**Comment by bradfitz** [comment]
The "integration" in "+build integration" is also not special. It's just an arbitrarily tag.

That is documented at https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by Konstantin8105** [comment]
Excuse me , ow it is clear.
Close.
