### ISSUE TITLE
syscall, os: Chmod doesn't support long paths on Windows

### ISSUE THREAD

**Issue by ibrasho** [golang/go#20829]
### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

GOOS=windows
GOARCH=amd64

### What did you do?

`os.Chmod` returns an unexpected error when passed a path that is longer than `MAX_PATH` (260) characters.

### What did you expect to see?

Similar behavior to [other file functions in `os`](https://github.com/golang/go/blob/master/src/os/file_windows.go). Calling `os.fixLongPath` on the path before passing the pointer to `GetFileAttributesW` and `SetFileAttributesW`.

https://github.com/golang/go/commit/231aa9d6d7e942ac43130356ba3554972251f015 fixed the issue with long paths (>=260 chars) by introducing a new function, `os.fixLongPath`, which converts the path to an [extended-length path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) on Windows.

### What did you see instead?

`chmod C:\Users\ibrahim\go\src\github.com\ibrasho\deptest\vendor\github.com\prometheus\procfs\sysfs\fixtures.src\devices\pci0000_@colon@_00\0000_@colon@_00_@colon@_0d.0\ata4\host3\target3_@colon@_0_@colon@_0\3_@colon@_0_@colon@_0_@colon@_0\block\sdb\bcache\dirty_data: The system cannot find the path specified.`

Applying the same logic from `os.fixLongPath` before passing the path to `os.Chmod` resolves this issue.

**Comment by ibrasho** [comment]
I've found this issue while investigating https://github.com/golang/dep/issues/774.

I've found multiple other file related functions implemented outside `os` (in `syscall`) that are also affected. According to [Naming Files, Paths and Namespaces on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath):
> These are the directory management functions that no longer have MAX_PATH restrictions if you opt-in to long path behavior: CreateDirectoryW, CreateDirectoryExW GetCurrentDirectoryW RemoveDirectoryW SetCurrentDirectoryW.
> These are the file management functions that no longer have MAX_PATH restrictions if you opt-in to long path behavior: CopyFileW, CopyFile2, CopyFileExW, CreateFileW, CreateFile2, CreateHardLinkW, CreateSymbolicLinkW, DeleteFileW, FindFirstFileW, FindFirstFileExW, FindNextFileW, GetFileAttributesW, GetFileAttributesExW, SetFileAttributesW, GetFullPathNameW, GetLongPathNameW, MoveFileW, MoveFileExW, MoveFileWithProgressW, ReplaceFileW, SearchPathW, FindFirstFileNameW, FindNextFileNameW, FindFirstStreamW, FindNextStreamW, GetCompressedFileSizeW, GetFinalPathNameByHandleW.

Here is a list of **possible** occurrences of this issue (where these functions were called without running the path through `os.fixLongPath` first:
* [`syscall.Open`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L249-L293): calls `CreateFileW`
* [`syscall.Chdir`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L388-L394): calls `SetCurrentDirectoryW`
* [`syscall.Mkdir`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L396-L402): calls `CreateDirectoryW`
* [`syscall.Rmdir`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L404-L410): calls `RemoveDirectoryW`
* [`syscall.Unlink`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L412-L418): calls `DeleteFileW`
* [`syscall.Rename`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L420-L430): calls `MoveFileW` (`os.Rename` works fine)
* [`syscall.UtimesNano`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L500-L518): calls `CreateFileW`
* [`syscall.Chmod`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L524-L542): calls `GetFileAttributesW` and `SetFileAttributesW`
* [`syscall.FullPath`](https://github.com/golang/go/blob/master/src/syscall/exec_windows.go#L132-L149): calls `GetFullPathNameW`

It could possibly occur in [`os.SameFile`](https://github.com/golang/go/blob/master/src/os/types_windows.go#L63-L95) since it ends up calling `os.*fileStat.loadFileId` which attempts `CreateFileW` without using `os.fixLongPath`.

**Comment by bradfitz** [comment]
I think we previously decided that we aren't adding magic UNC path mangling to the low-level syscall package. If users are using syscall, they can read MSDN docs.

Let's keep this bug specifically about Chmod.

**Comment by ibrasho** [comment]
I'm can work on a fix. But I've some questions:
* Since these functions are implemented in `syscall`, how are they exposed in `os`? Can we just create a wrapper around them in `os` that fixes this bug?
* [`syscall.Rename`](https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L420-L430): is duplicated in [`internal/syscall/windows.Rename`]([`syscall.Rename`](https://github.com/golang/go/blob/master/src/internalsyscall/windows/syscall_windows.go#L134-L144). Is there a reason? (Technically there is a difference. `internal/syscall/windows.Rename` replaces the destination if it exists, while `syscall.Rename` fails in that case).

**Comment by ibrasho** [comment]
@bradfitz In that case, even `os.Remove` needs the same fix. I'll submit a CL in a couple of minutes.

**Comment by bradfitz** [comment]
Remove was already done in 231aa9d6. I see:

```go
// Remove removes the named file or directory.                                                                                                                                                                  
// If there is an error, it will be of type *PathError.                                                                                                                                                         
func Remove(name string) error {                                                                       
        p, e := syscall.UTF16PtrFromString(fixLongPath(name))                                          
        if e != nil {                                                                                  
                return &PathError{"remove", name, e}                                                   
        }                                                                                              
...
```

And Chmod should be just:

```patch
diff --git a/src/os/file_posix.go b/src/os/file_posix.go
index 6ee7eeb..5ac0acd 100644
--- a/src/os/file_posix.go
+++ b/src/os/file_posix.go
@@ -48,7 +48,7 @@ func syscallMode(i FileMode) (o uint32) {
 // If the file is a symbolic link, it changes the mode of the link's target.
 // If there is an error, it will be of type *PathError.
 func Chmod(name string, mode FileMode) error {
-       if e := syscall.Chmod(name, syscallMode(mode)); e != nil {
+       if e := syscall.Chmod(fixLongPath(name), syscallMode(mode)); e != nil {
                return &PathError{"chmod", name, e}
        }
        return nil
```
