### ISSUE TITLE
net/http: Document change in cookie sanitization in the release notes?

### ISSUE THREAD

**Issue by lucas-clemente** [golang/go#20834]
[This](https://github.com/golang/go/commit/8f6d68ebaa660c6db8a87d418e95f8c0d3a221e4) change to sanitizeCookieValue (to fix #18627) broke the quic-go unit tests going from 1.8 to 1.9b2. I don't know about the policy for mentioning bugfixes there, but maybe this should be mentioned in the release notes for net/http? I'd be happy to write a CL if you feel like it's worth it.

**Comment by bradfitz** [comment]
Feel free to send a doc change. Thanks.

Be sure to add the  like elsewhere in the file.
