### ISSUE TITLE
debug/pe: Missing IMAGE_FILE_MACHINE_ARM64 machine magic constant

### ISSUE THREAD

**Issue by mattimo** [golang/go#20849]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64 but also checked tip.golang.org/pkg/debug/pe

### What did you do?

Tried to load a arm64 linux kernel image to inspect the PE header (used to UEFI) using `pe.Open()`

see https://play.golang.org/p/FFjD3r8M6N

### What did you expect to see?

Loads fine

### What did you see instead?

```
Could not open file: Unrecognised COFF file header machine value of 0xaa64.
```

At least one of the problems is that the `IMAGE_FILE_MACHINE_ARM64` that was added with Revision 10 of the "[Microsoft Portable Executable and Common Object File Format Specification](https://www.microsoft.com/en-us/download/details.aspx?id=19509)" (also known pecoff.docx), constant is not defined.

**Comment by alexbrainman** [comment]
> At least one of the problems is that the IMAGE_FILE_MACHINE_ARM64 that was added with Revision 10

I think it is OK to add IMAGE_FILE_MACHINE_ARM64 and use it in debug/pe.

@mattimo is there way to test this new code? Is there a simple way to create arm64 PE object file?

Alex
