### ISSUE TITLE
os: why must Chmod mode be non-zero on Windows?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20858]
From the beginning of Go until at least Go 1.9, the os.Chmod mode parameter must be non-zero on Windows.

I don't see why, though. syscall.Chmod returns EINVAL otherwise. Can we remove that?

I documented this in CL 47254 at least.

/cc @alexbrainman @ianlancetaylor

**Comment by bradfitz** [comment]
@rsc, the @golang/proposal-review NeedsDecision queries aren't working if old things like this are still open.

Bumping to Go 1.11.

**Comment by rsc** [comment]
Let's try changing this at the start of Go 1.13 and see what breaks. I can't explain it.

**Comment by odeke-em** [comment]
Great question @bradfitz!

I just looked at https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/chmod?view=vs-2017 which points to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/chmod-wchmod?view=vs-2017 and there is seems to have a relaxed opinion and by allusion that *mode can be zero by using "simply ignores those". Quoting that page:
<img width="848" alt="Screen Shot 2019-03-11 at 4 20 29 PM" src="https://user-images.githubusercontent.com/4898263/54164388-a125f000-4419-11e9-8e4e-fe48778c676b.png">

*"If pmode is not a combination of one of the manifest constants or incorporates an alternate set of constants, the function simply ignores those. "*

Kindly paging @jordanrh1 @alexbrainman @brendandburns, what do y'all think?

**Comment by alexbrainman** [comment]
I don't have strong opinion on this.

I believe @mattn added that code in https://golang.org/cl/4175049 Maybe he remembers why the code worked that way.

Alex

**Comment by mattn** [comment]
Sorry, I don't remember why I ignored 0. Probably, I read the part of doc here:

> This function validates its parameters. If pmode is not a combination of one of the manifest constants or incorporates an alternate set of constants, the function simply ignores those. If filename is NULL, the invalid parameter handler is invoked, as described in Parameter Validation. If execution is allowed to continue, errno is set to EINVAL and the function returns -1.

And added the check. Now I confirmed chmod(filename, 0) works fine.

```c
#include <stdio.h>
#include <fcntl.h>
#include <io.h>
#include <errno.h>
#include <error.h>

int
main(int argc, char* argv[]) {
  int r;
  r = open("dummy", O_CREAT);
  if (r < 0) {
    fprintf(stderr, "creat: %s\n", strerror(errno));
	return 1;
  }
  close(r);

  r = _chmod("dummy", 0);
  if (r < 0) {
    fprintf(stderr, "chmod: %s\n", strerror(errno));
	return 1;
  }

  unlink("dummy");
  return 0;
}
```

So we can change this behavior.
