### ISSUE TITLE
encoding/base32: cannot decode nonpadded encodings

### ISSUE THREAD

**Issue by bobjalex** [golang/go#20854]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
>go version
go version go1.9beta2 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoLib_beta
set GORACE=
set GOROOT=C:\Go_beta
set GOTOOLDIR=C:\Go_beta\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Bob\AppData\Local\Temp\go-build247706827=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
Tried to decode a base32 nonpadded encoding.

If possible, provide a recipe for reproducing the error.

The attached little program demonstrates the bug:
[base32_bug.go.txt](https://github.com/golang/go/files/1113422/base32_bug.go.txt)

### What did you expect to see?
A proper decoding.

### What did you see instead?
The error: decoding not padded: illegal base32 data at input byte 8
Even though WithPadding(base32.NoPadding) was specified.

**Comment by bradfitz** [comment]
That was added in 5f4f7519b6c038ab6771e6c7111bcd29967f2750. @zegl, can you take a look?

**Comment by zegl** [comment]
@bradfitz: Sure. It was a mistake to not modify Decode to allow non- or custom-padding.

Do you think that the message needs to be padded with the same character as specified by WithPadding(), or should we allow any type of padding (or none at all)? I'd pick the latter option, but it might not be as safe.

**Comment by bobjalex** [comment]
How would you know what padding character to strip for "padded" encoded
strings that don't have any padding? Zero padding characters is allowable
if padding is not needed.

**Comment by zegl** [comment]
@bobjalex: The case where the input is a valid base32 encoded message (with = as padding), but no padding is necessary is already covered in the Decode() method shipped in the existing go1.9 betas. (Example: `"fooba"` => `"MZXW6YTB"`).

In the other case you could look for a character that is not a part of the base32 alphabet, and infer that the first char like that is the one that is the padding char.

**Comment by bobjalex** [comment]
A downside to inferring the padding char is that it would somewhat limit the ability to detect corruption. RFC 4648 says

   A 33-character subset of US-ASCII is used, enabling 5 bits to be
   represented per printable character.  (The extra 33rd character, "=",
   is used to signify a special processing function.)

That would mean that any character outside of the 33 allowable would indicate corruption. The fact that encoding/base32 allows a "special processing" character other than "=" doesn't matter, since the set of allowable characters is still 33.

**Comment by ALTree** [comment]
@biexiang if you believe you have found a bug, please open a new issue. Don't forget to include a reproducer.
