### ISSUE TITLE
cmd/asm: optimize "AND $0xffff, Rx" with BFC

### ISSUE THREAD

**Issue by benshi001** [golang/go#20860]
Currently "AND $0x7fff, R9" is assembled to

	ldr	r11, [pc, # offset]
	and	r9, r9, r11

It can be optimized to a single instruction on ARMv7.

	bfc	r9, # 15, # 17

It can be done in Go1.10 and assigned to me.

**Comment by benshi001** [comment]
add it to Go1.10?

**Comment by odeke-em** [comment]
@benshi001 done.

**Comment by benshi001** [comment]
a &= 0xff00ffff is assembled to 
        a.go:13 0x812f0 e3e0b8ff        MVN $16711680, R11              
        a.go:13 0x812f4 e000000b        AND R11, R0, R0

Actually a more efficient way is
BIC $0x00ff0000, R0

**Comment by benshi001** [comment]
package main
	
	import (
	        "fmt"
	        "time"
	)
	
	var a, b, c uint32
	
	//go:noinline
	func ss() {
	        a &= 0xff00ffff
	        b &= 0xff8000ff
	        c &= 0xff007f00
	        a &= 0xff01ffff
	        b &= 0xff00007f
	        c &= 0xfe00ff00
	        a &= 0xff00ffff
	        b &= 0xfe0000ff
	        c &= 0xff80ff00
	        a &= 0xff80ffff
	        b &= 0xfc0000ff
	        c &= 0xff01ff00
	}
	
	func main() {
	        start := time.Now()
	        for i := 0; i < 8192; i++ {
	                ss()
	        }
	        d := time.Now().Sub(start)
	        fmt.Println(d)
	}

The above test program showed that BFC even cost more time than using constant pool. On my RP2 board, BFC cost 1.39ms while old way cost 1.315ms.

**Comment by benshi001** [comment]
Though 
"AND $0xFF00FFFFF, R0" is assembled to
MVN $16711680, R11
AND R11, R0, R0

a &= 0xff00ffff is compiled to
BIC $0x00ff0000, R0

by a SSA rule
(AND x (MVN y)) -> (BIC x y)
