### ISSUE TITLE
testing: Benchmark shows zero allocations

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#20863]
testing.Benchmark does not seem to produce valid memory stats any more:

The following program:

	package main
	
	import (
		"fmt"
		"testing"
	)
	
	var global *int
	
	func main() {
		r := testing.Benchmark(func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				global = new(int)
			}
		})
		fmt.Printf("creating filter: %v\n", r.MemString())
	}

always prints:

	       0 B/op	       0 allocs/op

I'd expect it to print

           8 B/op	       1 allocs/op

like previous Go versions.

go version devel +eab99a8 Mon Jun 26 21:12:22 2017 +0000 linux/amd64

**Comment by rogpeppe** [comment]
It turns out that it prints memory statistics when b.ReportAllocs is called.
As this is a behaviour change, perhaps this should be documented in
the Go 1.9 release notes.

**Comment by ALTree** [comment]
This is already documented

> MemAllocs and MemBytes may be zero if memory benchmarking is not requested using B.ReportAllocs or the -benchmem command line flag. 

http://tip.golang.org/pkg/testing/#BenchmarkResult

**Comment by ALTree** [comment]
The change was introduced in https://go-review.googlesource.com/c/36791/

**Comment by bradfitz** [comment]
@ALTree I would rather revert CL 36791 now that ReadMemStats is fast (see https://tip.golang.org/doc/go1.9#gc).

I'll send a CL.

**Comment by aclements** [comment]
I thought this was fixed a few days ago by https://golang.org/cl/46612?

**Comment by bradfitz** [comment]
Yeah, I was just about to point that out. Looks like that only reverted 1 of the 3 spots.

**Comment by ALTree** [comment]
Ah, thanks for noticing. I didn't notice that change was partly reverted.
