### ISSUE TITLE
misc/cgo/test: out of memory running test

### ISSUE THREAD

**Issue by awnumar** [golang/go#20887]
### What version of Go are you using (`go version`)?

```
go version go1.8.3 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/awn/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build571398585=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

I ran `./all.bash` at `src/` from `https://go.googlesource.com/go`.

### What did you expect to see?

I expected to see it compile and pass properly.

### What did you see instead?

> When `echo 0 > /proc/sys/vm/overcommit_memory`:

```
Compilation hangs at `##### ../misc/cgo/testsanitizers`.
```

> When `echo 1 > /proc/sys/vm/overcommit_memory`:

```
Compilation hangs at `##### ../misc/cgo/testsanitizers`.
```

> When `echo 2 > /proc/sys/vm/overcommit_memory`:

```
##### Testing race detector
ok  	runtime/race	4.406s
ok  	flag	1.029s
ok  	os	1.062s
ok  	os/exec	3.040s
--- FAIL: Test18146 (0.32s)
	issue18146.go:108: cannot allocate memory
FAIL
exit status 1
FAIL	_/home/awn/github/go/misc/cgo/test	2.241s
2017/07/02 23:37:07 Failed: exit status 1
ok  	flag	1.022s
ok  	os/exec	3.028s

##### ../misc/cgo/testgodefs
2017/07/02 23:37:07 FAILED
```

**Comment by davecheney** [comment]
How much physical memory and or swap does your system have?

**Comment by awnumar** [comment]
I have 16GB of RAM and 8GB swap.

**Comment by davecheney** [comment]
This should be sufficient but Linux tends to behave very conservativly when
overcommit is disabled.

Why do you want to disable overcommit while compling? What problem are you
trying to solve by doing so?

**Comment by awnumar** [comment]
I'm trying to get it to compile.

Those are the only three options, right? Zero is the default and at the default setting it fails to compile.

**Comment by davecheney** [comment]
IME most distributions default this value to 1, which enables overcommit.

What operating system and version are you running?

**Comment by awnumar** [comment]
@davecheney I'm running Arch Linux.

```
Linux blackbox 4.11.7-1-ARCH #1 SMP PREEMPT Sat Jun 24 09:07:09 CEST 2017 x86_64 GNU/Linux
```

**Comment by awnumar** [comment]
@davecheney This is what happens to resource utilisation when that test starts.

![screenshot from 2017-07-05 11-54-17](https://user-images.githubusercontent.com/8942495/27861449-d5b15056-6178-11e7-9f8e-ea164816568f.png)

This is with `overcommit_memory = 1`. After exiting the compilation, that utilisation doesn't change so the test is pretty much stalled. What does that specific test do?

**Comment by andybons** [comment]
@awnumar does this still reproduce on the latest release?

/cc @ianlancetaylor @josharian

**Comment by ianlancetaylor** [comment]
This was reported as a compile bug, but as far as I can see it is a bug while running the test, not while compiling it.

**Comment by ianlancetaylor** [comment]
We already reduce the size of `test18146` based on `RLIMIT_NPROC`.  Perhaps we also need to reduce it based on `RLIMIT_DATA`.

**Comment by awnumar** [comment]
@andybons Nope, can't reproduce this again on a fresh pull, but I have gone through a few OS reinstalls since then so I can't say whether this is because of a specific system issue or because it was patched.

`/proc/sys/vm/overcommit_memory` is set to its default: `0`.

**Comment by andybons** [comment]
OK. In that case, closing for now. Please re-open if this pops up again.

Thanks.
