### ISSUE TITLE
OSX - fatal error: MSpanList_Insert

### ISSUE THREAD

**Issue by andrewoh531** [golang/go#20888]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)?
Macbook Pro Sierra 10.12.5
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/AndrewOh/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6g/1n50_rgn0yb3_s8q6n4yg7h00000gn/T/go-build078413845=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
In terminal pressed enter a few times

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
No errors

### What did you see instead?

```
failed MSpanList_Insert 0x2d6000 0x63769450433aa 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x279a4b)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad fp=0x7fff5fbff060 sp=0x7fff5fbff030
runtime.MSpanList_Insert(0x298e28, 0x2d6000)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f fp=0x7fff5fbff088 sp=0x7fff5fbff060
MHeap_FreeSpanLocked(0x295a20, 0x2d6000, 0x100)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:583 +0x163 fp=0x7fff5fbff0c8 sp=0x7fff5fbff088
MHeap_Grow(0x295a20, 0x8, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:420 +0x1a8 fp=0x7fff5fbff108 sp=0x7fff5fbff0c8
MHeap_AllocSpanLocked(0x295a20, 0x1, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:298 +0x365 fp=0x7fff5fbff148 sp=0x7fff5fbff108
mheap_alloc(0x295a20, 0x1, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:190 +0x121 fp=0x7fff5fbff170 sp=0x7fff5fbff148
runtime.MHeap_Alloc(0x295a20, 0x1, 0x10000000012, 0x1f2e9)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66 fp=0x7fff5fbff1a8 sp=0x7fff5fbff170
MCentral_Grow(0x29d798, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:197 +0x8b fp=0x7fff5fbff210 sp=0x7fff5fbff1a8
runtime.MCentral_CacheSpan(0x29d798, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:85 +0x167 fp=0x7fff5fbff248 sp=0x7fff5fbff210
runtime.MCache_Refill(0x2d2000, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcache.c:90 +0xa0 fp=0x7fff5fbff270 sp=0x7fff5fbff248
runtime.mcacheRefill_m()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.c:368 +0x57 fp=0x7fff5fbff290 sp=0x7fff5fbff270
runtime.onM(0x1f3ff8)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:273 +0x9a fp=0x7fff5fbff298 sp=0x7fff5fbff290
runtime.mallocgc(0x120, 0x198de0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:178 +0x849 fp=0x7fff5fbff348 sp=0x7fff5fbff298
runtime.newobject(0x198de0, 0x2d2000)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:353 +0x49 fp=0x7fff5fbff370 sp=0x7fff5fbff348
runtime.newG(0x3645a)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:233 +0x2a fp=0x7fff5fbff388 sp=0x7fff5fbff370
allocg(0x288380)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:925 +0x1f fp=0x7fff5fbff398 sp=0x7fff5fbff388
runtime.malg(0x8000, 0x288420)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:2106 +0x1f fp=0x7fff5fbff3c8 sp=0x7fff5fbff398
runtime.mpreinit(0x2887e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:137 +0x27 fp=0x7fff5fbff3e0 sp=0x7fff5fbff3c8
mcommoninit(0x2887e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:201 +0xc9 fp=0x7fff5fbff408 sp=0x7fff5fbff3e0
runtime.schedinit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:138 +0x55 fp=0x7fff5fbff430 sp=0x7fff5fbff408
runtime.rt0_go(0x7fff5fbff468, 0x3, 0x7fff5fbff468, 0x0, 0x0, 0x3, 0x7fff5fbff658, 0x7fff5fbff65f, 0x7fff5fbff666, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbff438 sp=0x7fff5fbff430
```

I've had this error for quite some time. Looking through existing issues it seems to be specific to certain application versions. Is it possible to trace this error to the specific application/utility that is causing the error?

I've gone through and updated all my brew packages and still get this error.

**Comment by davecheney** [comment]
1.4.2 cannot be used to bootstrap on osx. Brew should have the special
version of 1.4.2 that is patched to work on osx, otherwise use 1.8.3 to
bootstrap

**Comment by andrewoh531** [comment]
Hi @davecheney, what would I need to do?

I've tried removing old versions of go. Current version being used is 1.8.3:
```
go version
go version go1.8.3 darwin/amd64
```

**Comment by davecheney** [comment]
It looks like the panic you posted was build by Go 1.4.2.

**Comment by bradfitz** [comment]
In addition to upgrading Go, you need to recompile any old binaries with the new Go.

Also, this is not a complete bug report.

You say:

> What did you do?
>
> In terminal pressed enter a few times

But that is not what you actually did. There are a number of details missing.

Things will work once you update Go.

**Comment by andrewoh531** [comment]
Hi, I've actually removed version 1.4.2 and currently have version 1.8.3. I don't know what application is actually causing the error. If you can point me to how I can find what app might be causing the error I'd greatly appreciate it.

**Comment by davecheney** [comment]
The app that panic'd with references to /usr/local/cellar/go1.4.2 is the
one that needs to be rebuilt.

**Comment by andrewoh531** [comment]
Hi @davecheney, I guess that's where I'm stuck at. I don't know what the app that's referencing the old version is. Any pointers to how I might be able to track it down?

**Comment by davecheney** [comment]
What command did you run that generated the message you reported in your
original issue report?

**Comment by andrewoh531** [comment]
That's the thing...I didn't run any commands. If I continually press enter on my OSX terminal the stacktrace comes out.

**Comment by davecheney** [comment]
Can you please paste the contents of ~/.profile, you may have placed some
kind of completion helper in your path, then upgraded you operating system.

**Comment by andrewoh531** [comment]
Contents of ~/.profile:

```
  1
  2 expor tPATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
  3
  4 [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
  5
~
```

**Comment by davecheney** [comment]
I'm sorry, I don't think I can help you. You have a program on your system,
probably a plugin to rvm, whatever that is, that is compiled with a version
of Go that recent updates to osx broke.

**Comment by andrewoh531** [comment]
Np. I'll keep digging. Cheers

**Comment by Skoda091** [comment]
@andrewoh531 whether you have made any progress on this issue? I have exactly the same error but with a path for go1.4:
```
...
/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff5c0 sp=0x7ffeefbff590
...
```
On my machine, this error occurs when I enter a new shell.

**Comment by ianlancetaylor** [comment]
@Skoda091 This issue is closed.  Let's please try to keep discussion to a forum rather than on the issue tracker.  See https://golang.org/wiki/Questions .  Thanks.
