### ISSUE TITLE
tls Accept() problem

### ISSUE THREAD

**Issue by chowyu08** [golang/go#20889]
### What version of Go are you using (`go version`)?
1.8.3
### What operating system and processor architecture are you using (`go env`)?
ubuntu14.04

### What did you do?
create a tls server, and read client's ConnectionState

### What did you expect to see?
error is:   tlsconfig.ConnectionState undefined (type *tls.Config has no field or method ConnectionState)

// Accept waits for and returns the next incoming TLS connection.
  // The returned connection is of type *Conn.
  func (l *listener) Accept() (net.Conn, error) {
  	c, err := l.Listener.Accept()
  	if err != nil {
  		return nil, err
  	}
  	return Server(c, l.config), nil
  }

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
