### ISSUE TITLE
documentation: Effective_GO#functions duplicate code error

### ISSUE THREAD

**Issue by desertpunk12** [golang/go#20891]
[https://golang.org/doc/effective_go.html#functions](url)
on this code

```
func nextInt(b []byte, i int) (int, int) {
    for ; i < len(b) && !isDigit(b[i]); i++ {
    }
    x := 0
    for ; i < len(b) && isDigit(b[i]); i++ {
        x = x*10 + int(b[i]) - '0'
    }
    return x, i
}
```

I think

```
 for ; i < len(b) && !isDigit(b[i]); i++ {
    }
```

is a duplication mistake

**Comment by crvv** [comment]
That isn't duplication mistake.
The first loop finds first digit in `b` and stores its index in variable `i`.
The second loop parses `b` from index `i` and calculate the value.

**Comment by ALTree** [comment]
What @crvv said. Note that the first loop has condition `!isDigit` while in the second is not negated (`isDigit`).

Closing, since the code snippet is correct.
