### ISSUE TITLE
How to convert empty interface to other interface? the empty interface is just return value of functions.

### ISSUE THREAD

**Issue by RaymondReddington** [golang/go#20890]
### What did you expect to see?

v = types.Types.CreateType(typename)
return Client(v)

which  types.Types.CreateType returns interface{} and Client is an interface

### What did you see instead?
cannot convert v (type interface {}) to type Client:
	interface {} does not implement Client (missing CreateClient method)

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
