### ISSUE TITLE
runtime: unexpected fault address 0x0 from inside assertI2I2

### ISSUE THREAD

**Issue by whyrusleeping** [golang/go#20901]
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/whyrusleeping/gopkg"
GORACE=""
GOROOT="/home/whyrusleeping/go"
GOTOOLDIR="/home/whyrusleeping/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build194663187=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
Was running a go program and it crashed with this stack trace: https://gist.github.com/whyrusleeping/680bb5d41a762eac6a48cf5b4ea99e66

### What did you expect to see?
I'm fine if my code panics, but generally seeing 'fault' in a stack trace makes me think that its a go issue.

Its worth noting that i was experimenting with plugins. the plugins were working great, and plugin code was not being run when the crash happened.

ref: https://github.com/ipfs/go-ipfs/issues/4031

**Comment by ianlancetaylor** [comment]
I agree that this should not happen.

Is this repeatable at all?

**Comment by whyrusleeping** [comment]
I havent been able to reproduce this again, but i can try. Anything in particular i should try and gather to help debug?

**Comment by aclements** [comment]
@whyrusleeping, any luck reproducing this?

Looking at the code, I don't see how could possibly happen. The only dereference on this line is of `m`, and we just checked if `m` was nil.

It's worth noting that this code has been completely rewritten for 1.10, so even we if do track this down in 1.8 (or 1.9), it likely doesn't apply to 1.10.

**Comment by whyrusleeping** [comment]
@aclements I havent been able to. My only hint was that I was using plugins at the time, and maybe even replacing the file of a plugin that was in use.

**Comment by aclements** [comment]
Thanks for the quick reply. I'm going to go ahead and close this as unreproducible.
