### ISSUE TITLE
cmd/cover: go test coverprofile wrong path at panic backtrace 

### ISSUE THREAD

**Issue by minaevmike** [golang/go#20909]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.8.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/prog/GO"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build530360851=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
i make a simpe code to reproduce
file `i.go`
```
package sample
type I interface {
	Test()
}

type iI struct {

}

func (_ *iI) Test() {
	panic("t")
}
```
file `sample_test.go`
```
package sample

import "testing"

func Test_Panic(t *testing.T) {
	I := &iI{}
	I.Test()
}
```

### What did you expect to see?

if i run this test without coverage i have normal panic backtrace
```
root@mike:~/prog/GO/src/github.com/minaevmike/sample/ss# go test
--- FAIL: Test_Panic (0.00s)
panic: t [recovered]
	panic: t

goroutine 5 [running]:
testing.tRunner.func1(0xc420072410)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x50ad40, 0xc42000ee40)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/minaevmike/sample/ss.(*iI).Test(0x5ef6a0)
	/root/prog/GO/src/github.com/minaevmike/sample/ss/i.go:11 +0x64
github.com/minaevmike/sample/ss.Test_Panic(0xc420072410)
	/root/prog/GO/src/github.com/minaevmike/sample/ss/sample_test.go:7 +0x3b
testing.tRunner(0xc420072410, 0x5422e8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/minaevmike/sample/ss	0.003s
```

### What did you see instead?
but if i run this test with coverprofile i have 
```
root@mike:~/prog/GO/src/github.com/minaevmike/sample/ss# go test -v -coverprofile=c.out
=== RUN   Test_Panic
--- FAIL: Test_Panic (0.00s)
panic: t [recovered]
	panic: t

goroutine 5 [running]:
testing.tRunner.func1(0xc420072410)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x50bde0, 0xc420012e40)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/minaevmike/sample/ss.(*iI).Test(0x5f06c0)
	github.com/minaevmike/sample/ss/_test/_obj_test/i.go:12 +0x6e
github.com/minaevmike/sample/ss.Test_Panic(0xc420072410)
	/root/prog/GO/src/github.com/minaevmike/sample/ss/sample_test.go:7 +0x3b
testing.tRunner(0xc420072410, 0x5434c8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/minaevmike/sample/ss	0.003s
```
So from this backtrace i can't undestand the line of code where panic was throw.
As i can undestand this path `github.com/minaevmike/sample/ss/_test/_obj_test/i.go:12` is relative path to `/tmp/go-build*` dir. But it's impossible to detect the right folder. And this only happens when i run go test with coverprofile

**Comment by robpike** [comment]
I'm not sure I understand. Are you saying that it says line 12 rather than line 11? That's the only difference I can see. That is a known and documented issue: The line numbers for crashes and test reports are incorrect when covering is enabled.

**Comment by minaevmike** [comment]
Yes, you're right. line 12 rather then line11. This behaviour make tests harder to debug in case of panic. I don't know how go test works inside, but mb it's possible to print full path to the file like `/tmp/go-build123/github.com/minaevmike/sample/ss/_test/_obj_test/i.go:12`  or recover this panic and map this path to the source path.

**Comment by robpike** [comment]
As "go help testflag" says,

 BUG: If a compilation or test fails with coverage enabled,
            the reported line numbers may be incorrect.

It's all but impossible to fix because of the way the go/ast package handles comments.

Unfortunate but unfixable.
