### ISSUE TITLE
spec: some "base type" (of pointer types) occurrences are not used consistently

### ISSUE THREAD

**Issue by go101** [golang/go#20900]
From the three occurrences:

> A pointer type denotes the set of all pointers to variables of a given type, called the base type of the pointer. 

> Two pointer types are identical if they have identical base types.

> ignoring struct tags (see below), x's type and T are unnamed pointer types and their pointer base types have identical underlying types. 

I can get a conclusion that only unnamed pointer types can have a base type.
So I think the following occurrence of "base type" should be "underlying type" instead.

```
// The method set of the base type of PtrMutex remains unchanged,
// but the method set of PtrMutex is empty.
type PtrMutex *Mutex
```

**Comment by griesemer** [comment]
Any pointer type can have a base type; it's the type of the object the pointer points to. But named pointer types are rare and probably should be avoided in the first place.

The example comment here is correct, but arguably in this case it would make more sense to talk about the underlying type. I'll rephrase.

**Comment by go101** [comment]
@griesemer 

> Any pointer type can have a base type; it's the type of the object the pointer points to.

If this is true, then the following line in spec is problematic:

> Two pointer types are identical if they have identical base types.

But two named pointer types will never be identical.

**Comment by griesemer** [comment]
@go101 https://tip.golang.org/ref/spec#Type_identity is very clear about type identity. There's no need to be overly pedantic and repeat this in every section.

**Comment by go101** [comment]
sorry, I didn't notice the above paragraph. :)
