### ISSUE TITLE
bytes: Buffer.ReadString  Not expect EOF 

### ISSUE THREAD

**Issue by gooid** [golang/go#20917]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What did you do?
https://play.golang.org/p/GfynWFmLTW

### What did you expect to see?
```
[97 98 99 10] <nil>
[100 101 102 10] <nil>
[103] <nil>
[] EOF

[97 98 99 10] <nil>
[100 101 102 10] <nil>
[103] <nil>
[] EOF
```

### What did you see instead?
```
[97 98 99 10] <nil>
[100 101 102 10] <nil>
[103] <nil>
[] EOF

[97 98 99 10] <nil>
[100 101 102 10] <nil>
[103] EOF
```

**Comment by davecheney** [comment]
This is working as intended and documented, https://golang.org/pkg/bufio/#Reader.ReadString

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
