### ISSUE TITLE
net/http: wrong detected MIME type with UTF-8 BOM

### ISSUE THREAD

**Issue by unixpickle** [golang/go#20912]
### What version of Go are you using (`go version`)?

```
go version go1.8.3 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/Documents/Code/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/23/qy5hclf52mdfnx7xgn1ddk6r0000gn/T/go-build891556908=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
```

### What did you do?

Run this code, which is on the [playground](https://play.golang.org/p/5HZGowUEZI):

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	document := "<!DOCTYPE html><html></html>"
	bom := "\xef\xbb\xbf"
	fmt.Println(http.DetectContentType([]byte(document)))
	fmt.Println(http.DetectContentType([]byte(bom+document)))
}
```

### What did you expect to see?

```
text/html; charset=utf-8
text/html; charset=utf-8
```

### What did you see instead?

```
text/html; charset=utf-8
text/plain; charset=utf-8
```

It seems from [sniff.go](https://github.com/golang/go/blob/b5240daa2f56e7dd778cfbab17adecbf50a62674/src/net/http/sniff.go#L81) that a BOM automatically triggers a text/plain MIME type. Ideally, `htmlSig` would detect UTF-8 BOMs and skip past them.

**Comment by bradfitz** [comment]
1) UTF-8 BOMs are unnecessary and often cause pain for little to no benefit. You should avoid them.

2) http.DetectContentType implements https://mimesniff.spec.whatwg.org/ which does not seem to suggest that any textual content type can have a UTF-8 BOM in front of it.

So it looks like this is working as intended.

Let me know if I misread the mimesniff spec, though.
