### ISSUE TITLE
Override function couldnt be called in base struct?

### ISSUE THREAD

**Issue by RaymondReddington** [golang/go#20916]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
Write some struct.
    
    package main              
                          
    import (                  
        "fmt"                 
    )                         
    type T interface{         
        Test()                
        Test2()               
    }                         
                              
    type A struct {           
    }                         
    func (a *A)Test(){        
        fmt.Println("A-Test") 
    }                         
    func (a*A)Test2(){        
        a.Test()              
    }                         
    type B struct {           
        A                     
    }                         
                              
    func (b *B)Test(){        
        fmt.Println("B-Test") 
    }                         
                              
    func main(){              
        var a T               
        a = &B{}              
        a.Test2()             
        }          
run go run test.go

### What did you expect to see?

B-Test

### What did you see instead?

A-Test

**Comment by davecheney** [comment]
This is working as expected. Go does not implement inheritance or virtual dispatch. When you call a.Test2() that is shorthand for `a.A.Test2()` because the type of the receiver for `Test2` is `*A`.

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by RaymondReddington** [comment]
thank you

**Comment by RaymondReddington** [comment]
could this be improved? or a option could be set?

**Comment by RaymondReddington** [comment]
package main              
                          
    import (                  
        "fmt"                 
    )                         
    type T interface{         
        ToChild() T           
        Test()                
        Test2()               
    }                         
                              
    type A struct {           
        T                     
    }                         
    func (a *A)Test(){        
        fmt.Println("A-Test") 
    }                         
    func (a *A)Test2(){       
        a.ToChild().Test()    
    }                         
    // func (a *A)ToChild()T{ 
    //     return a           
    // }                      
    type B struct {           
        A                     
    }                         
                              
    func (b *B)Test(){        
        fmt.Println("B-Test") 
    }                         
    // func (b *B)Test2(){    
    //     b.Test()           
    // }                      
    func (b *B)ToChild()T{    
        return b              
    }                         
                              
                              
    func main(){              
        var a T               
        a = &B{}              
        a.Test2()             
    }            

go run test.go:



[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47b739]

goroutine 1 [running]:
main.(*A).Test2(0xc42000e230)
	/root/e/source/device_map/src/device_map/test2.go:19 +0x29
main.main()
	/root/e/source/device_map/src/device_map/test2.go:42 +0x4e
exit status 2

**Comment by dominikh** [comment]
Your issue still lies with learning the language, not a bug in Go. I warmly recommend asking for help in a place more suited to your questions. Please see https://golang.org/wiki/Questions for good places to ask

**Comment by RaymondReddington** [comment]
ok, thank you .
