### ISSUE TITLE
cmd/go: short commands description in 'go help' too vague for some command

### ISSUE THREAD

**Issue by ensonic** [golang/go#20918]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
```
$ go help
Go is a tool for managing Go source code.
...
The commands are:

	build       compile packages and dependencies
	clean       remove object files
	doc         show documentation for package or symbol
	env         print Go environment information
	bug         start a bug report
	fix         run go tool fix on packages
	fmt         run gofmt on package sources
	generate    generate Go files by processing source
	get         download and install packages and dependencies
	install     compile and install packages and dependencies
	list        list packages
	run         compile and run Go program
	test        test packages
	tool        run specified go tool
	version     print Go version
	vet         run go tool vet on packages
...
```

### What did you expect to see?

The help output for the `fix` and `vet` is not helpful. Is is just `("run go tool %s on packages", toolname)`. Also the `fmt` output could be improved.

### What did you see instead?

The help-output should say what the command will effectively do (like for `vet`: check the source code for potential issues).

**Comment by ALTree** [comment]
I guess we could change them adding a very short parenthetical like:

> run gofmt (a source code formatter) on package sources

**Comment by rsc** [comment]
The quoted output is misleading. The full output is:

	The commands are:
	
		build       compile packages and dependencies
		clean       remove object files
		doc         show documentation for package or symbol
		env         print Go environment information
		bug         start a bug report
		fix         run go tool fix on packages
		fmt         run gofmt on package sources
		generate    generate Go files by processing source
		get         download and install packages and dependencies
		install     compile and install packages and dependencies
		list        list packages
		run         compile and run Go program
		test        test packages
		tool        run specified go tool
		version     print Go version
		vet         run go tool vet on packages
	
	Use "go help [command]" for more information about a command.

Note the last line, which is omitted in the bug report. And indeed `go help fmt`, `go help fix`, and `go help vet` do provide more information. 

Given this, the current short summaries seem fine.

**Comment by ensonic** [comment]
As you wish, but I would expect that the summary would help to tell me what the fmt/fix and vet tools do in general. Like e.g.
```patch
-fmt         run gofmt on package sources
+fmt         use gofmt to reformat source files
-fix         run go tool fix on packages
+fix         automatically fix mistakes
```

**Comment by rsc** [comment]
I like those specific suggestions. I'll send a CL. Thanks.

**Comment by ensonic** [comment]
Please also do this for 'vet' because that was what as a native speaker I was mostly wondering what it would be good for. Description could be "check code for suspicious constructs".

**Comment by ensonic** [comment]
Thanks!
