### ISSUE TITLE
Can go test ./... with exclude some dir

### ISSUE THREAD

**Issue by zh794390558** [golang/go#20919]
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/work/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build183196056=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

Can `go test ./...` with exclude some dirs, e.g. ./vendor

### What did you expect to see?
Can have a -r option to excluding some directories.

### What did you see instead?
`go test ./... -r ./vendor

**Comment by ALTree** [comment]
If the vendor folder is what you care about, you're lucky: in go1.9 (the next go release) `./...` will ignore it:

> By popular request, ./... no longer matches packages in vendor directories in tools accepting package names, such as go test.

http://tip.golang.org/doc/go1.9#vendor-dotdotdot


Was 'ignore vendor' the main use case you had in mind? If yes, I guess we can close this as it's fixed.

**Comment by zh794390558** [comment]
@ALTree Thanks
