### ISSUE TITLE
net/url: should *User methods return zero values when called with a nil receiver?

### ISSUE THREAD

**Issue by kindlychung** [golang/go#20924]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.8.1 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kaiyin/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build230264726=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

https://play.golang.org/p/3yO2OL-XTq

### What did you expect to see?

I would like to have something like `username, err := url.User.Username()` and handle the error if there is no username in the url. 

### What did you see instead?

A panic.

**Comment by bradfitz** [comment]
I could see some argument for `(*Userinfo).Password` and `(*Userinfo).Username` to return zero values when called with a nil receiver instead of panicking.

Leaving open to decide during Go 1.10.

**Comment by bradfitz** [comment]
Has CL, so added `release-blocked` label.

**Comment by bradfitz** [comment]
@rsc, thoughts? I'm fine with this but don't feel strongly.
