### ISSUE TITLE
x/build/cmd/coordinator: use --no-cache on docker build commands

### ISSUE THREAD

**Issue by cybrcodr** [golang/go#20936]
This is related to issue #20747 .  I think @bradfitz is unable to reproduce the issue due to docker builds using cache.  Use --no-cache to guarantee that steps are done fresh.

I think we may need to do this for other binaries as well.

**Comment by bradfitz** [comment]
I'd really rather not use --no-cache. The speed is nice.

I'd rather fix it by specifying the exact hash of all deps, including transitive ones.

**Comment by cybrcodr** [comment]
How about if I make it an optional variable to be passed in?

Default w/o --no-cache param ...
$ make build0

To force --no-cache param ...
$ make build0 NO_CACHE=1

Wdyt?

**Comment by bradfitz** [comment]
I do not want a --fast vs a --correct flag. That's the wrong knob to give a user.

In the Gerrit CL you wrote:

> There's definitely no one correct way to go about this with current approach.

But I think there is a correct approach. We can ask Go to give us the transitive list of deps (`go list -f '{{.Deps}}' golang.org/x/build/cmd/coordinator`) and then mark all their hashes in the Dockerfile.

I'll write a little tool.

**Comment by cybrcodr** [comment]
Fair enough.

> But I think there is a correct approach. We can ask Go to give us the transitive list of deps (go list -f '{{.Deps}}' golang.org/x/build/cmd/coordinator) and then mark all their hashes in the Dockerfile.

What I meant to say is that if we use the current approach of manually doing a go get of only a few packages and reset at the repo for some, it becomes arbitrary on which packages you choose to pin vs not.

Agree that it requires a tool to pin all dependencies down.

**Comment by cybrcodr** [comment]
Closing this as it's better to use a tool for version pinning and not having to switch between cache and no cache.

**Comment by bradfitz** [comment]
FTR, little tool was in https://go-review.googlesource.com/c/47971/
