### ISSUE TITLE
gccgo: new gotools testcase failures starting in r249799 on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#20931]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 gccgo (GCC) 8.0.0 20170706 (experimental) linux/ppc64le
(Latest from gcc trunk)

### What operating system and processor architecture are you using (`go env`)?
ppc64le Ubuntu

### What did you do?
Found some new failures in gcc-testresults for ppc64le under "gotools".

	=== gotools tests ===

FAIL: TestCgoExternalThreadSIGPROF
FAIL: TestCgoExternalThreadSignal
FAIL: TestCgoCallbackGC
FAIL: TestInstall
FAIL: TestEarlySignalHandler
FAIL: TestSignalForwarding
FAIL: TestSignalForwardingExternal
FAIL: TestOsSignal
FAIL: TestSigaltstack
FAIL: TestPIE

		=== gotools Summary ===
# of expected passes		284
# of unexpected failures	10
# of untested testcases		117
/home/gccbuild/build/nightly/build-gcc-trunk/./gcc/gccgo version 8.0.0 20170629 (experimental) [trunk revision **249803**] (GCC)

This is from https://gcc.gnu.org/ml/gcc-testresults/2017-06/msg03088.html

### What did you expect to see?
Results as found in the gcc-testresults from the previous gcc build with no gotools testcase failures.

		=== gotools tests ===

		=== gotools Summary ===
# of expected passes		135
# of untested testcases		74
/home/gccbuild/build/nightly/build-gcc-trunk/./gcc/gccgo version 8.0.0 20170629 (experimental) [trunk revision **249791**] (GCC)

### What did you see instead?
New failures.

**Comment by laboger** [comment]
I didn't notice before that the before and after test counts are different before and after so these are probably new tests.  I tried to manually run some of them and got inconsistent results, I see that some that show up as failures in the log are supposed to be skipped but that doesn't always happen.

**Comment by ianlancetaylor** [comment]
With the changes I just committed, all the gotools tests pass for me.  But you are seeing some failures that I never saw.  Can you update to the current sources and see how it looks now?  Thanks.

**Comment by ianlancetaylor** [comment]
When I say that all the tests pass for me, I mean that they pass for me on a powerpc64le-unknown-linux-gnu machine, specifically gcc112.fsffrance.org in the GCC compile farm.

**Comment by laboger** [comment]
If I look at the latest gcc-testresults, the Cgo tests are now passing but the rest are not.
I'll try some different distros.

**Comment by laboger** [comment]
Actually in looking at the logs from our gcc-testresults runs I see this:

FAIL: TestInstall
        carchive_test.go:160: [/home/gccbuild/build/nightly/build-gcc-trunk/gcc64 -fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build546181855=/tmp/go-build -gno-record-gcc-switches -I pkg/gccgo_linux_ppc64le_fPIC -o ./testp1 main.c main_unix.c pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a -lgo]
        carchive_test.go:162: pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o): In function `main.AN7_uintptr32e$hash':
                /home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: undefined reference to `__morestack'
                pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o): In function `main.AN7_uintptr32e$equal':
                /home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: undefined reference to `__morestack'
                pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o): In function `main.AN6_uint64256e$hash':
                /home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: undefined reference to `__morestack'
                pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o): In function `main.AN6_uint64256e$equal':
                /home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: undefined reference to `__morestack'
                pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o): In function `main.S4_SizeN6_uint327_MallocsN6_uint645_FreesN6_uint64e$hash':
                /home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: undefined reference to `__morestack'
                pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a(a.out.a.o):/home/gccbuild/build/nightly/build-gcc-trunk/gotools/carchive-test-dir/misc/cgo/testcarchive/src/libgo/libgo.go:45: more undefined references to `__morestack' follow
                collect2: error: ld returned 1 exit status

All the tests that fail gets link errors with undefined references to __morestack.

BTW -- shouldn't the testname be TestSignalStack instead of TestSigalStack?

**Comment by ianlancetaylor** [comment]
Is it possible that the link command is picking up the wrong libgcc?  Not the newly built one, but one installed on the system?  It looks like you have the command there, so you should be able to run it with `-Wl,-t` to see precisely which libgcc file the linker opens.

(The test name isn't `TestSigalStack` it's `TestSigaltstack`, and that name is right because it is testing the use of the alternate signal stack installed by the `sigaltstack` system call.)

**Comment by laboger** [comment]
I've built my own gccgo from trunk, how do I just run the tests for gotools?  I expected this to work if I do this from my build directory:

make check-gotools

But during that the invocation of check-gccgo always fails with errors like this:

/home/boger/gccgo.work/trunk/bld/gotools/check-gccgo: 2: /home/boger/gccgo.work/trunk/bld/gotools/check-gccgo: -fgo-compiling-runtime: not found
Keeping gotest29413

I've always been able to do these from the build directory:

make check-go
make check-target-libgo

**Comment by ianlancetaylor** [comment]
`make check-gotools` does work for me.

That error implies that something is wrong with the file `gotools/check-gccgo`.  What does it look like on your system?  On mine it looks like this:

```
#!/bin/sh
/home/iant/gcc/gccgo3-objdir/./gcc/gccgo -B/home/iant/gcc/gccgo3-objdir/./gcc/ -B/home/iant/gcc/go-install/x86_64-pc-linux-gnu/bin/ -B/home/iant/gcc/go-install/x86_64-pc-linux-gnu/lib/ -isystem /home/iant/gcc/go-install/x86_64-pc-linux-gnu/include -isystem /home/iant/gcc/go-install/x86_64-pc-linux-gnu/sys-include   -g -O2 "$@" -I /home/iant/gcc/gccgo3-objdir/x86_64-pc-linux-gnu/libgo -L /home/iant/gcc/gccgo3-objdir/x86_64-pc-linux-gnu/libgo -L /home/iant/gcc/gccgo3-objdir/x86_64-pc-linux-gnu/libgo/.libs
```

**Comment by ianlancetaylor** [comment]
By the way, `check-gccgo` is a generated file that should be created in the build directory.

**Comment by laboger** [comment]
Here's what I see:

/home/boger/gccgo.work/trunk/bld/./gcc/gccgo -B/home/boger/gccgo.work/trunk/bld/./gcc/ -B/usr/local/gccgo.trunk/powerpc64le-linux/bin/ -B/usr/local/gccgo.trunk/powerpc64le-linux/lib/ -isystem /usr/local/gccgo.trunk/powerpc64le-linux/include -isystem /usr/local/gccgo.trunk/powerpc64le-linux/sys-include   -g -O2 "$@" -I /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo -L /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo -L /home/boger/gccgo.work/trunk/bld/powerpc64le-linux/libgo/.libs

**Comment by laboger** [comment]
In my own build, I can see that CC=gcc appears in gotools/Makefile and gotools/config.log.  When I do this build I am not explicitly setting CC to anything and I haven't updated my PATH to include this newly built gcc.  So that means the testcases are just using the installed gcc if the PATH is not updated; after I change PATH to search the install directory for the gcc I just built, then the testcases work.

Here is the command that is displayed when running the test:
gcc -fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build364260689=/tmp/go-build -gno-record-gcc-switches -I pkg/gccgo_linux_ppc64le_fPIC -Wl,-t -o ./testp1 main.c main_unix.c pkg/gccgo_linux_ppc64le_fPIC/liblibgo.a -lgo

I don't see how CC is supposed to be set to refer to the gcc that was just built.

**Comment by laboger** [comment]
I see someone else reported this problem and it got fixed.  Here is the patch.  Closing.
https://gcc.gnu.org/ml/gcc-patches/2017-08/msg01747.html
