### ISSUE TITLE
net/http: fix panic error message on Request.Body read after Hijack

### ISSUE THREAD

**Issue by jlhawn** [golang/go#20933]
### What version of Go are you using (`go version`)?

```
go version go1.8.3 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOOS="darwin
```

> nit: Isn't this already in the `go version` output above?

### What did you do?

If  `(*http.Request).Body` is read *after* the connection is hijacked, a `backgroundRead` operation is triggered once EOF of the body is encountered. This background read will read from the underlying connection when it shouldn't (because the connection has been hijacked).

### What did you expect to see?

I would expect this program to *not* fail: https://play.golang.org/p/QUXm31VhCr

Note that if I change that program to *always* read from the hijacked connection buffer, it will panic instead: https://play.golang.org/p/E7UyjfgkdS

```
http: panic serving 127.0.0.1:3: invalid concurrent Body.Read call
```

### What did you see instead?

The `backgroundRead` callback happens unconditionally and will read a byte from the connection that is lost if you then try to read directly from the `conn` and will result in a panic if you try to read from the buffered reader.

The programs above worked as expected in go1.7

--------

The bug seems to be introduced here: https://github.com/golang/go/blob/faf882d1d427e8c8a9a1be00d8ddcab81d1e848e/src/net/http/server.go#L1683-L1684

cc @bradfitz 

Before calling `ServeHTTP(w, r)`, if `requestBodyRemains` then a callback is registered which will begin a `backgroundRead` once the body is fully read. The background read probably should not occur if the connection has been hijacked.

A proposed fix would be to change `startBackgroundRead` to check if `cr.conn.hijacked()` immediately after acquiring the lock and return early if the connection has been hijacked.

**Comment by bradfitz** [comment]
Yes, this was changed in Go 1.8.

After your call to Hijack, you're not supposed to read from Request.Body anymore. I'll keep this bug open to fix that error message. 

After a hijack, you're expected to read from the returned bufio.Reader:

https://golang.org/pkg/net/http/#Hijacker

>  // The returned bufio.Reader may contain unprocessed buffered
> // data from the client.

(That includes the 1 byte)

BTW, the time for Go 1.8 feedback was in December. We're currently wrapping up Go 1.9, which is almost out. If you could test Go 1.9beta2, that'd b egreat.

**Comment by jlhawn** [comment]
> After your call to Hijack, you're not supposed to read from Request.Body anymore.

Is that explicitly documented anywhere?

I can confirm that rearranging the example so that it Hijacks only after fully reading the request seems to fix it: https://play.golang.org/p/akmrJbBnN6

**Comment by odeke-em** [comment]
Hello @bradfitz, @jihawn replied asking if we've documented that "After your call to Hijack, you're not supposed to read from Request.Body anymore." -- it doesn't seem like that's documented AFAIK from https://tip.golang.org/pkg/net/http
<img width="896" alt="screen shot 2017-07-20 at 9 51 31 pm" src="https://user-images.githubusercontent.com/4898263/28448487-a096f302-6d95-11e7-997d-390c95284f90.png">

**Comment by bradfitz** [comment]
Okay, it's now documented for Go 1.9 in c522b2b. We can panic more nicely in Go 1.10.
