### ISSUE TITLE
os: Getwd doesn't return canonical case of current directory on macOS

### ISSUE THREAD

**Issue by glinton** [golang/go#20947]
### What version of Go are you using (`go version`)?
`go version go1.8.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/src/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build179514568=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
This may very well be an issue for mac regarding the case sensitivity of their nfs server, but here goes. We have a utility that adds an entry to `/etc/exports` by grabbing the current directory: `os.Getwd()`. Window's case insensitivity is handled because `os.Getwd()` returns `syscall.Getwd()` on a mac, however, we get whatever the user typed on their `cd`.

On a darwin machine:
```sh
mkdir /tmp/TestDir

cd /tmp/testdir
# fails, as 'PWD' is '/tmp/testdir'
# run playground code here

cd /tmp/TestDir
# works, as 'PWD' is '/tmp/TestDir'
# run playground code here
```
Build and run this code: ~~https://play.golang.org/p/Yqk90j5ud5~~ https://play.golang.org/p/QmTFAiLcL4

For the next two expect/result sections, this:
```
package main

import "os"

func main() {
	cwd, _ := os.Getwd()
	os.Stdout.WriteString(cwd + "\n")
}
```

### What did you expect to see?
Output of printing os.Getwd()
```
/tmp/TestDir
```

### What did you see instead?
Output of printing os.Getwd()
```
/tmp/testdir
```

**Comment by bradfitz** [comment]
I cannot reproduce.

```
ward5k:foobar bradfitz$ mkdir /tmp/FooBar
ward5k:foobar bradfitz$ cd /tmp/FooBar/
ward5k:foobar bradfitz$ curl --silent https://play.golang.org/p/Yqk90j5ud5.go > getwd.go
ward5k:FooBar bradfitz$ go run getwd.go 
/private/tmp/FooBar
/tmp/FooBar
ward5k:FooBar bradfitz$ cd /tmp/foobar
ward5k:foobar bradfitz$ go run getwd.go 
/private/tmp/FooBar
/tmp/foobar
ward5k:foobar bradfitz$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

It's not clear from your bug report which output you expect from which directory.

**Comment by glinton** [comment]
I've updated the original comment with a more straightforward example - https://play.golang.org/p/QmTFAiLcL4.

I expect it to return the same actual filepath regardless of the way it is `cd`d to

**Comment by davecheney** [comment]
Both answers are equally correct, osx's hfs+ is by default case preserving
case insensitive.

**Comment by henvic** [comment]
@glinton have you ran into a, possibly, edge case where this is an issue?

**Comment by glinton** [comment]
@henvic (from the 'What did you do?' section of the original issue)
>This may very well be an issue for mac regarding the case sensitivity of their nfs server, but here goes. We have a utility that adds an entry to `/etc/exports` by grabbing the current directory: `os.Getwd()`. Window's case insensitivity is handled because `os.Getwd()` returns `syscall.Getwd()`. On a mac, however, we get whatever the user typed on their `cd`.

So we end up getting `permission denied` when trying to mount, because the directory is `/tmp/ExportedDir` but `/etc/exports` (and the client) only has `/tmp/exporteddir`. Our current workaround is to use `syscall.Getwd()` to populate the exports file and provide the client with a target.

**Comment by ifarobi** [comment]
I have the same issue. I used Go version 1.9.
But my in my case, `os.Getwd()` not returning the working directory as the projects folder, but it return the temporary build folder, such as `var/folders/7d/b5gjzcc15cg04vtgz1xd6fth0000gn/T/go-build340557118/.../.../`.

**Comment by ianlancetaylor** [comment]
I think this is enough of a special case that we aren't going to try to address it.  Using ` $PWD` is often the right thing to do.  In this case, it apparently isn't, but there is a workaround.
