### ISSUE TITLE
x/build/devapp: dummy issue. Please ignore.

### ISSUE THREAD

**Issue by andybons** [golang/go#20945]
![giphy](https://user-images.githubusercontent.com/365204/27967788-5e47452a-6312-11e7-84de-7fe82ea0da5b.gif)

**Comment by andybons** [comment]
Gerrit ID: 10660

**Comment by stamblerre** [comment]
16140

**Comment by andybons** [comment]
Gerrit ID: 22285

**Comment by ashleymcnamara** [comment]
22515

**Comment by spf13** [comment]
14840

**Comment by samccone** [comment]
22400 :goat:

**Comment by andybons** [comment]
Closing this. It has served its purpose.
