### ISSUE TITLE
Go's for loop is too slow

### ISSUE THREAD

**Issue by nilsocket** [golang/go#20958]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux, amd64

### What did you do?
A simple for loop,
     
     package main

     import "fmt"

     func main(){
         for i := 0; i < 1000000; i++ {
             fmt.Println(i)
         }
    }

### What did you expect to see?
time taken to be around, 1 or 2 seconds

### What did you see instead?
time taken is 6 seconds.

I have written the same in python,

    for i in range(1,1000000)
        print(i)

time taken for python is around 2.3 seconds.
Since, printing to screen takes time, I have redirected output to files, in both programs.

Another point is, go.txt file is 2 bytes more in size compared to py.txt

Here's the screen shot,

![slow_for_loop](https://user-images.githubusercontent.com/29815708/27993321-5309cd9e-64c6-11e7-970b-95ec765109cf.png)

**Comment by davecheney** [comment]
This is not a bug. Go's stdout is _not_ buffered, where pythons is. 

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
