### ISSUE TITLE
cmd/compile: use SBFX / UBFX instructions for bit extraction on ARMv7

### ISSUE THREAD

**Issue by benshi001** [golang/go#20966]
(SLLconst (SRAconst x [d]) [c]) -> SBFX
(SRAconst (SLLconst x [d]) [c]) -> SBFX
(SLLconst (SRLconst x [d]) [c]) -> UBFX
(SRLconst (SLLconst x [d]) [c]) -> UBFX

SBFX and UBFX are available on ARMv7.

**Comment by benshi001** [comment]
Please also assign it to me. ^_^

**Comment by ALTree** [comment]
@benshi001 Can you change the title to "cmd:compile: use SBFX / UBFX instructions for XXX on ARMv7" (where XXX is the operation you're optimizing, I think it's "bit extraction"(?)).
