### ISSUE TITLE
spec: define minimum set of types panic will print?

### ISSUE THREAD

**Issue by pjebs** [golang/go#20987]
I have a custom struct that satisfies error interface.

```
type ErrorCollection struct {
	RemoveDuplicates bool
	Errors           []error
}
```

If I call `panic( )` with it and is not recovered, it prints out:
`{%!!(MISSING)s(bool=false) [[code]: 1 [error]: Square root of negative number is prohibited [message]: Please make number positive or zero error 1 error 2]}`

ErrorCollection itself satisfies error interface, and returns a nice formatted string.

Internally, can the `func panic(v interface{})` function be changed so that if the `v` satisfies error interface, then it prints out `v.Error( )` instead?

**Comment by pjebs** [comment]
If ErrorCollection is newly initialized and I panic on it, then output is:
`{%!s(bool=false) []}`

**Comment by bradfitz** [comment]
Please post a complete program demonstrating the issue.

**Comment by bradfitz** [comment]
> Internally, can the func panic(v interface{}) function be changed so that if the v satisfies error interface, then it prints out v.Error( ) instead?

Sorry, I don't think that's going to happen at the moment.

But I realize that the panic docs don't really say which types are supported:

https://golang.org/ref/spec#Handling_panics
https://golang.org/pkg/builtin/#panic

@griesemer, @ianlancetaylor?

**Comment by bradleyfalzon** [comment]
Just to clarify, does it not do this already?

https://play.golang.org/p/FCz5_Wu7F8
https://github.com/golang/go/blob/286599f27026f5c4001f1da25b35aa1243f51d08/src/runtime/panic.go#L413-L414
https://github.com/golang/go/blob/286599f27026f5c4001f1da25b35aa1243f51d08/src/runtime/error.go#L77-L84

**Comment by bradfitz** [comment]
In any case, it's not documented AFAIK.

Let's see @pjebs's complete program.

**Comment by ianlancetaylor** [comment]
The builtin function panic supports all types.  This is documented at https://golang.org/ref/spec#Handling_panics .

The suggestion for exactly what to print if a panic is not recovered is not part of the language spec.  The spec says only "At that point, the program is terminated and the error condition is reported, including the value of the argument to panic."  The spec deliberately does not say precisely how this happens or precisely how the value passed to `panic` is reported, just as the spec deliberately does not say precisely how a stack trace is printed.  Different implementations of Go may choose to act differently in this regard.

That said, if I call `panic(v)` where `v` has a type that has an `Error` method, the result of the `Error` method will be printed.  So as far as I can tell there is nothing to fix here.

Example: https://play.golang.org/p/P4TN15NU1x

**Comment by pjebs** [comment]
Here is a truncated example of my program (https://github.com/pjebs/jsonerror):

https://play.golang.org/p/3LIB5bCJNj

**Comment by bradleyfalzon** [comment]
Only `*T` (pointer to T) implements error in that example:

```go
func (t *T) Error() string
```

But you're passing panic `t` which is of type `T`. If you try `panic(&t)` (passing `*T` to panic) then the argument satisfies the error interface, and the output is:

```
panic: 
0:error 1
1:error 2

goroutine 1 [running]:
main.main()
	/tmp/sandbox371120381/main.go:31 +0x1a0
```

**Comment by bradfitz** [comment]
You panicked with a `T` value, not a `*T` value.

Working as intended.
