### ISSUE TITLE
flag: global Usage func disregards FlagSet.SetOutput

### ISSUE THREAD

**Issue by vearutop** [golang/go#20998]
### What version of Go are you using (`go version`)?
```
go version go1.8.2 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vpoturaev/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/fnl90gfx5_5f9599s3hpthfw0000gq/T/go-build760766867=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
```go
package main

import (
	"flag"
	"io/ioutil"
	"os"
)

func main() {
	var i int
	flag.IntVar(&i, "i", 2, "sample int")
	flag.CommandLine.SetOutput(ioutil.Discard)
	os.Args = []string{"app", "-i=1", "-unknown"}
	flag.Parse()
}
```
https://play.golang.org/p/05pwqQu-3-
### What did you expect to see?

No output

### What did you see instead?

STDERR:
```
Usage of app:
```

`/usr/local/Cellar/go/1.8.2/libexec/src/flag/flag.go`
```go
var Usage = func() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	PrintDefaults()
}
```
`Usage` function disregards `f.Out()` in favour of `os.Stderr`.

The correct code should be:
```go
var Usage = func() {
	fmt.Fprintf(f.out(), "Usage of %s:\n", os.Args[0])
	PrintDefaults()
}
```

**Comment by bradfitz** [comment]
The flag.Usage global variable was in the original Go 1.0:

```go
var Usage = func() {
        fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
        PrintDefaults()
}
```

Go 1.2 introduced the `CommandLine` global variable:

```go
var CommandLine = NewFlagSet(os.Args[0], ExitOnError)
```

The documentation of FlagSet.SetOutput says:

https://golang.org/pkg/flag/#FlagSet.SetOutput
> SetOutput sets the destination for usage and error messages. If output is nil, os.Stderr is used.

The problem @vearutop hits is modifying `flag.CommandLine` which uses the implicit `flag.Usage`, even though `Usage` is not associated with `CommandLine`.

> The correct code should be:

I think you mean:

```go
var Usage = func() {
	fmt.Fprintf(CommandLine.out(), "Usage of %s:\n", os.Args[0])
	PrintDefaults()
}
```
