### ISSUE TITLE
encoding/json: Unmarshal replaces interface{} types instead of acting on the underlying type

### ISSUE THREAD

**Issue by ghost** [golang/go#20994]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

Unmarshal to existing `map[string]interface{}` that is hidden behind an `interface{}`:
https://play.golang.org/p/kgaRznDOwb
```golang
var test interface{}
if err := json.Unmarshal([]byte(`{"A": "B"}`), &test); err != nil {
	panic(err)
}
fmt.Printf("First:\n %+v\n", test)

if err := json.Unmarshal([]byte(`{"C": "D"}`), &test); err != nil {
	panic(err)
}
fmt.Printf("Second:\n %+v\n", test)
```

### What did you expect to see?

First:
 map[A:B]
Second:
 map[A:B C:D]

According to docs: 

> To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:
> ...
> map[string]interface{}, for JSON objects

> To unmarshal a JSON object into a map, Unmarshal first establishes a map to use. If the map is nil, Unmarshal allocates a new map. Otherwise Unmarshal reuses the existing map, keeping existing entries. 

I expect unmarshal to reuse the existing map, instead of replacing it.

### What did you see instead?
First:
 map[A:B]
Second:
 map[C:D]

**Comment by cespare** [comment]
The target value is an interface, not a map (even though the concrete type happens to be a map for the second call). Therefore only the first bit of documentation you quoted applies, not the second.

I think the behavior is as intended, but the documentation could be a bit more explicit.

**Comment by alsamylkin** [comment]
I was confused about `first establishes a map to use` and thought that it actually reuses the existing map, because it is not nil. I do see from the source code that this behavior is intentional.

**Comment by rsc** [comment]
The behavior is intended and I think pretty explicit. The text says "Unmarshal stores one of these in the interface value:" and so it does. I don't think there's more to say here that's useful.
