### ISSUE TITLE
user: No Symlink of /usr/local/go/bin/go to /usr/bin/ in Getting Started page.

### ISSUE THREAD

**Issue by skwid999** [golang/go#21006]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8.3
### What operating system and processor architecture are you using (`go env`)?

Linux amd64
### What did you do?
Installing it, the link "go" didn't get me to /usr/local/go because it has to have a symlink to /usr/bin

user@computer:~$ go
bash: /usr/bin/go: No such file or directory

### What did you expect to see?
On the website, adding a command after the "export PATH" line in the "Linux install"

### What did you see instead?
euh... no line of a symlink like "sudo ln -s /usr/local/go/bin/go /usr/bin/" ?

**Comment by bradfitz** [comment]
I'm confused.

How did you install it?

What commands did you run, and from where?

**Comment by skwid999** [comment]
I was installing go language in my Linux amd64, and the error shown was that my system found the "go" command but not the "go" program... I had to symlink it in /usr/bin.
I introduce this "error" for you to add it on the "Getting Started" "Linux Install' section of you website...

Thanks.
Skwid.

**Comment by skwid999** [comment]
https://golang.org/doc/install

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

I think the mailing list is the best place to resolve this.
