### ISSUE TITLE
wiki: add Experience Report on Go Dependencies

### ISSUE THREAD

**Issue by FLGMwt** [golang/go#21002]
(killing template b/c this is a wiki request, hope that's alright)

Just read https://blog.golang.org/toward-go2. Exciting stuff!

I was interested in the Experience Report call to action, as our team just published something that may fit the bill around our experience with dependency management:

[Docker => Moby: Go Dependencies](http://engineering.rallyhealth.com/go/golang/dependencies/package-managers/2017/06/28/go-and-dependencies.html)

This was our first Go project so the perspective is pretty fresh/unindoctrinated.

It doesn't seem like it fits in any of the existing sections so could we maybe add a "Dependencies" section?

CC: @patrick-bohan @mattbrown

**Comment by ALTree** [comment]
Sounds reasonable. The page says

> Add new sections as appropriate.

so adding a new section is certainly allowed, too.

**Comment by ianlancetaylor** [comment]
Sure, adding a new section is fine.  Go ahead.

Closing this issue since there is nothing to do.
