### ISSUE TITLE
ReadPassword seems to be broken when running within IntelliJ with Go plugin

### ISSUE THREAD

**Issue by iwillneverstop** [golang/go#21009]
version go1.8.3 windows/amd64 with golang.org/x/crypto/ssh/terminal

ReadPassword seems to be broken when running within IntelliJ. 

Reproduction Case:

package main

import (
  "fmt"
  "golang.org/x/crypto/ssh/terminal"
)

func main() {
  fmt.Print("password: ")
  password, err := terminal.ReadPassword(int(syscall.Stdin))

  if err != nil {
    fmt.Println(err)
  }

  fmt.Println(string(password))
}

I got an error "The handle is invalid.".

The same code works well if I build it into an EXE file and run the EXE file from the Terminal.

**Comment by dlsniper** [comment]
Hi, 

This error has nothing to do with Go. It's caused by the fact that the IDE doesn't run the process in a pty. For more details please see (and watch) https://youtrack.jetbrains.com/issue/PY-19938

This issue can be closed. 


Thank you
