### ISSUE TITLE
reflect: Type.Comparable returns incorrect values for some types obtained via reflection

### ISSUE THREAD

**Issue by alsamylkin** [golang/go#21011]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rk/3wxxpsdj3kx052390hbwxk0h0000gn/T/go-build181924434=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```golang
package main

import (
	"reflect"
)

func main() {
	var i interface{} = func() { println("Hello world") }
	v := reflect.Indirect(reflect.ValueOf(&i))
	if v.Type().Comparable() {
		m := map[interface{}]string{}
		m[v.Interface()] = "this will panic"
	} else {
		println("v is not comparable")
	}
}
```

A link on play.golang.org is best.
https://play.golang.org/p/l7rmrLiGvY

### What did you expect to see?
```
v is not comparable
```

### What did you see instead?
```
panic: runtime error: hash of unhashable type func()

goroutine 1 [running]:
main.main()
	/tmp/sandbox040073154/main.go:12 +0x1e0
```

**Comment by bradfitz** [comment]
Nice. But because this is not a regression, there's no time (or risk) budget for Go 1.9, due out shortly.

**Comment by ianlancetaylor** [comment]
I think this is correct behavior.  If you print `v.Type().String()`, you will see that it has type `interface {}`.  Interface types are comparable.  It just happens that this interface value holds a value that can not be compared.

In other words, this is approximately equivalent to

```
package main

func main() {
	var i interface{} = func() { println("Hello world") }
	println(i == i)
}
```

which will also panic.

**Comment by bradfitz** [comment]
Whoops, I overlooked the type interface {} after "var i". 

I agree this looks fine.

**Comment by alsamylkin** [comment]
That's fine, but if interface{} is comparable, why can't I use it in the map then?

**Comment by alsamylkin** [comment]
Also everything works as expected if I remove pointer: `v := reflect.Indirect(reflect.ValueOf(_&_i))`

**Comment by ianlancetaylor** [comment]
You can use an `interface{}` in a map.

What you can't do is use an `interface{}` in a map if you store a func value in the interface.

If you remove the pointer, then the value you get in `v` has type `func()`, which is not comparable.  In both cases, try printing `v.Type().String()` to see what is going on.
