### ISSUE TITLE
go/types: unset GOPATH before running tests

### ISSUE THREAD

**Issue by bradfitz** [golang/go#21013]
I was just debugging a mysterious test failure at d5da104294cd449a6588dac26c52f221a60357ff (almost Go 1.9).

I was getting:

```
bradfitz@gdev:~/go/src$ go test -short go/types
--- FAIL: TestFailedImport (0.26s)
        api_test.go:1328: for source importer, got unexpected error: src:6:11: undeclared name: foo
        api_test.go:1328: for source importer, got unexpected error: src:7:10: undeclared name: foo
        api_test.go:1328: for source importer, got unexpected error: src:9:24: undeclared name: foo
        api_test.go:1328: for source importer, got unexpected error: src:4:8: "foo" imported but not used as main
        api_test.go:1351: for source importer, got "main", want "foo"
FAIL
FAIL    go/types        0.694s
```

After debugging, it turns out it was because I had a `$GOPATH/src/foo` directory with a `package main` in it that I was previously using to debug something else.

I don't expect that go/types (or any other test in std) should respect or be affected by the user's `$GOPATH`.

/cc @griesemer @alandonovan

**Comment by dlsniper** [comment]
As part of the GopherCon Contrib Workshop, I've managed to find that this got broken by: 2ad7453bf42654a6a1615fa1cc867123570c4595

Hope it helps.

**Comment by jessfraz** [comment]
so `make.bash` unsets the GOPATH so this only happens when called by `go test`
should that test just unset the GOPATH in the beginning as well?
