### ISSUE TITLE
net/mail: ParseAddress: unclear error message

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21018]
When parsing this address:

```go
mail.ParseAddress("Foo (middle) Bar <foo@example.com>")
```

you get the following error:

```
mail: no angle-addr
```

That's confusing because an angle-addr is present in the input.

The email address _should_ be formatted with quotes as: 

```go
mail.ParseAddress(`"Foo (middle) Bar" <foo@example.com>`)
```

But we could probably be clearer about the error there.

**Comment by xmudrii** [comment]
Errors seems quite easy to fix. I would like to give it a try, but before, does somebody want to comment on the format.

Should we show how it should be, such as:
```
incorrect address format, expected `"Foo (middle) Bar" <foo@example.com>`
```
or just drop a more precise message about error:
```
incorrect address format
```

/cc @kevinburke @bradfitz

**Comment by ianlancetaylor** [comment]
I think neither option is quite right here.  It would be best if we could say that the error with the example is a missing quote.

**Comment by xmudrii** [comment]
@ianlancetaylor i'll try to write some code and push cl, if tests pass, you can expect it.

**Comment by xmudrii** [comment]
@ianlancetaylor I hope you've thought about something like this one

**Comment by xmudrii** [comment]
If anybody wants to take on this, feel free to do. Sorry, I'm out of time for next few days.

**Comment by guilhermebr** [comment]
Calling parseAddres for:
`Foo middle Bar <foo@example.com>` returns 
`"Foo middle Bar" <foo@example.com>`

 and:
`"Foo (middle) Bar" <foo@example.com>` returns
`"Foo (middle) Bar" <foo@example.com>` 

so I made a change that calling for:
`Foo (middle) Bar <foo@example.com>` returns
`"Foo (middle) Bar" <foo@example.com>` 
instead of error

**Comment by burakguven** [comment]
Should this be closed? Since @guilhermebr's change the example given in OP no longer returns an error.

**Comment by mvdan** [comment]
Sounds like it to me. If anyone disagrees or has any other examples to be fixed, feel free to reopen or open a new issue.
