### ISSUE TITLE
x/build/gerrit: client is unwieldy

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21010]
Using the Gerrit client, it feels like things are routinely more difficult than they should be. There are some points of friction that it would be nice to paper over:

- Authentication: there are several methods of authentication. Gerrit tries to push you to git cookies auth, which isn't great for bots/logic that just talks to the REST API, and if you want to do basic auth you have to awkwardly parse out the username/password out of the gitcookies auth UI. `NewClient` should default to BasicAuth, you shouldn't have to figure out which method of authentication is appropriate and how to get tokens

- Posting comments: You have to know 1) Gerrit treats line by line comments differently from on-the-totality-of-the-review comments and 2) which patch set you want to leave a comment on. If you are writing a bot all you need/want to do is post a comment on the latest patch set. This should be simpler to do in the Gerrit client.

- Inconsistent verbs: you QueryChanges but you ListProjects and you GetChangeDetails.

- Query parameters are annoying: Gerrit lets you ask for more data by specifying `o=MESSAGES&o=CURRENT_COMMIT` etc, in Go this turns into

    ```go
    QueryChangesOpt{
        Fields: []string{"MESSAGES", "CURRENT_COMMIT"},
    }
    ```

These structs make it sort of difficult to go back and forth between the API description on https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-changes and the abstraction that hides this in the client. It might be easier as just a `url.Values{}`.

I wouldn't underestimate how much of Github/Slack's success is due to API's that make them easy to interact with, it's not fair to ask Gerrit to get to that level but it would probably help people create interesting things around Gerrit if it was easier to get started with the API's and the clients.

**Comment by bradfitz** [comment]
> Inconsistent verbs.

The method names match the API names on purpose. https://godoc.org/github.com/andygrunwald/go-gerrit does the same.

I have no plans of redoing our Gerrit client to flesh it out or change its feel. Its goal is to be the minimum we need for the Go build system.

**Comment by kevinburke** [comment]
Sure, I guess the cost is it's going to be harder at the margin to write code to interact with our code review tool.
