### ISSUE TITLE
encoding/json: indentation of raw strings in examples looks suboptimal in godoc

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21026]
### Motivation

There are two ways a Go [example](https://godoc.org/testing#hdr-Examples) can be read:

1. In the source code of a _test.go file.
2. Via `godoc` command or the web interface it provides.

In most cases, examples look equally good in both interfaces. However, in some cases, there may be two alternative ways to write an example, such that one of them looks better inside source code, and the other looks better in the godoc interface.

My understanding is that it's better to prioritize the godoc interface over the source code, since most people will be reading examples via godoc (be it locally, or via https://godoc.org, or https://golang.org/pkg/). If that is not correct, the rest of this issue is not valid.

## Issue

I found that there are 5 examples in `encoding/json` package that have raw strings with indentation which is suboptimal when seen via the godoc interface.

They are:

- [ ] https://tip.golang.org/pkg/encoding/json/#example_Decoder:

    ![image](https://user-images.githubusercontent.com/1924134/28241824-68a28366-6959-11e7-89d7-2c74dab82d11.png)

- [x] https://tip.golang.org/pkg/encoding/json/#example_Decoder_Decode_stream:
    (Resolved by CL [48910](https://golang.org/cl/48910).)

    ![image](https://user-images.githubusercontent.com/1924134/28241827-75ee5496-6959-11e7-9944-f7ddb66308dd.png)

- [ ] https://tip.golang.org/pkg/encoding/json/#example_Decoder_Token:

    ![image](https://user-images.githubusercontent.com/1924134/28241828-7f1f46ec-6959-11e7-9512-b77c36adfec0.png)

- [ ] https://tip.golang.org/pkg/encoding/json/#example_Unmarshal:

    ![image](https://user-images.githubusercontent.com/1924134/28244990-79478be4-69b8-11e7-931c-8110289ec0ed.png)

- [ ] https://tip.golang.org/pkg/encoding/json/#example_RawMessage_unmarshal:

    ![image](https://user-images.githubusercontent.com/1924134/28245003-b28835f2-69b8-11e7-81e9-14ff04275f5b.png)

Their readability in godoc interface can be improved by dedenting the contents of the raw string by 1 tab.

**Comment by mvdan** [comment]
It seems that someone took a stab at the changes. I assume this issue is to confirm your suspicion on godoc formatting being more important than source code formatting, before the patches are applied.

If that's so, I agree.

**Comment by shurcooL** [comment]
@mvdan, I filed the issue for posterity and to confirm that prioritizing godoc view is the right thing to do.

I suggested it to someone as their first Go CL. We're doing it as part of a [Go Contributor Workshop](https://golang.org/s/gophercon2017) at GopherCon.

**Comment by mvdan** [comment]
Ah, makes sense - was missing the workshop context :)
