### ISSUE TITLE
blog, all: easier links to the source code for a given project

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21038]
I was trying to figure out where the source code for the blog lived; I was thinking it would be nice to have a link in the footer where the license currently is.

But then, where is the best place to link to? 

- We could link to https://github.com/golang/blog, which is the easiest way to clone the project. But the import path you want is `golang.org/x/blog`, not `github.com/golang/blog`. Also there are no issues or PR's there, or description of how to get to those. 

- We could link to https://go-review.googlesource.com/admin/projects/blog but that doesn't explain where to clone the source to, what the project is, where the issues are, how to run it locally.

- We could link to https://godoc.org/golang.org/x/blog but that page is really Go-centric (where are the articles, for example?) and doesn't show how to build/start the server.

I'd propose the following:

- link people from the blog footer to the Github repo. This is the page that people are most familiar with, and the easiest way to browse the source code.

- Update the README to explain where to file issues, where to send patches, and how/where to check out the code ("go get -u golang.org/x/blog").

If that works I can update the README's on a lot of the x/ projects

**Comment by kevinburke** [comment]
cc @hanwen, could we embed README's on that Gerrit page, or add a better "project homepage"?

**Comment by hanwen** [comment]
why not link to https://go.googlesource.com/blog/ ?
it renders README.md like github does, eg. https://go.googlesource.com/go/

**Comment by kevinburke** [comment]
Oh interesting! That could work. We'd still need to explain where in your source tree you should clone the project to, and how to report issues, and how to contribute changes, but we could put those in the README.

**Comment by ianlancetaylor** [comment]
Is there anything to do here?

**Comment by kevinburke** [comment]
Nope - I'm pretty happy with the CL merged above.
