### ISSUE TITLE
wiki: add section on commit messages to CodeReviewComments

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21030]
The current CodeReviewComments page does not mention commit messages. Here's a useful explainer about directory prefixes from git-codereview:

```go
Your CL description appears not to use the standard form.

The first line of your change description is conventionally a one-line summary
of the change, prefixed by the primary affected package, and is used as the
subject for code review mail; the rest of the description elaborates.

Examples:

	encoding/rot13: new package

	math: add IsInf, IsNaN

	net: fix cname in LookupHost

	unicode: update to Unicode 5.0.2
```

I think we should add that and maybe some more:

- try to keep opening line below 50 chars

- please check spelling - we can fix typos in source code after the fact, but not in commit messages

- use present tense

- if you amend commits, the new commit should still describe the entire commit (instead of whatever you just amended it to add)

also some more useful discussion here: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

(Opening a ticket first because the page specifically asks you not to edit it willy nilly)

**Comment by xmudrii** [comment]
What do you think about creating new page just for commit and before CLCreate stuff? To me, it sounds good, especially because CodeReviewComments is focused on the point once you actually create CL and more on Go code itself.

What could we add onto the page:
* What should be commit message
* What should be commit description
* Common practices
* Examples

**Comment by bcmills** [comment]
It would also be helpful to clarify the convention for x/ repos.  (Should commits to x/sync/syncmap start with `syncmap`, or `x/sync/syncmap`?)

**Comment by ianlancetaylor** [comment]
There is a section on commit messages at https://golang.org/doc/contribute.html.  That seems like a better place anyhow.
