### ISSUE TITLE
build: default GOROOT_BOOTSTRAP to `go env GOROOT`

### ISSUE THREAD

**Issue by vcabbage** [golang/go#21037]
Currently, developers wanting to build Go from source need to either have a Go install at `$HOME/go1.4` or explicitly set `GOROOT_BOOTSTRAP`. I frequently recommend prefixing the build scripts with `GOROOT_BOOTSTRAP=$(go env GOROOT)`, this has worked well in the cases I've helped with. I believe baking this into the script would simplify the process for many developers.

To retain backward compatibility, I suggest the following precedence:
1. Explicitly set `GOROOT_BOOTSTRAP`
2. `$HOME/go1.4`
3. `go env GOROOT`

**Comment by ianlancetaylor** [comment]
Good idea.  I'll note that if `go env GOROOT` == `GOROOT` (that is, the `GOROOT` we are about to use for the build), then we shouldn't use it.

**Comment by crvv** [comment]
This is a duplicate of https://github.com/golang/go/issues/14339

**Comment by mvdan** [comment]
@crvv if this is indeed a duplicate, this issue should be closed and the CL should only mention the original issue.

@vcabbage could you confirm this is a dup?

**Comment by vcabbage** [comment]
It does appear to be a dup. Though #14339 specifically refers to `make.bash`, I would hope that the other make scripts would be updated to follow the same logic. I'll go ahead an close this issue.
