### ISSUE TITLE
cmd/compile: unaligned stores to global variables on s390x (causes SIGILL or relocation error)

### ISSUE THREAD

**Issue by mundaym** [golang/go#21048]
### What version of Go are you using (`go version`)?

go1.9beta2 (also present in go1.8.3)

### What operating system and processor architecture are you using (`go env`)?

linux/s390x

### What did you do?

```go
package main

type T struct {
	a [1]byte
	b [2]byte
}

var x T

//go:noinline
func newT() T {
	return T{[1]byte{1}, [2]byte{1,2}}
}

func main() {
	x.b = newT().b
}
```

(https://play.golang.org/p/jXSguFs4Hk)

### What did you expect to see?

Successful execution.

### What did you see instead?

```
main.main: main.x+1054942 is not 2-byte aligned
```

</hr>

While not strictly a regression from the last release, this bug does cause the docker tests to fail when using go1.9beta2. I have a somewhat ugly fix, will send a CL shortly.

**Comment by bradfitz** [comment]
If this was present in Go 1.8.x, it's not a candidate for holding up Go 1.9. Sorry. But if you get a safe fix out in the next 24-48 hours, maybe, depending on reviewer feedback.

We're already a couple weeks overdue releasing the Go 1.9rc1 due to other issues.
