### ISSUE TITLE
cmd/go: go build fails with linker error when using clang v4.0.1

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#21042]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
➤ git describe --tags
go1.9beta2-129-g504deee608
```

### What operating system and processor architecture are you using (`go env`)?
Arch Linux 64bit

### What did you do?

`$ env GOROOT_BOOTSTRAP=/usr/src/go1.4 CC=clang GOGC=off bash make.bash`

Note that using `CC=gcc` works fine.

### What did you expect to see?

Successful compile of the go toolset

### What did you see instead?

```
............
cmd/vet
# runtime/cgo
/usr/bin/ld: -r and -pie may not be used together
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
cmd/go/internal/envcmd
............
```

**Comment by ALTree** [comment]
The GCC issue was  #20276. It looks like the fix ([CL 18359](https://www.golang.org/cl/18359)), which was also backported to go1.4-bootstrap ([CL 42910](https://www.golang.org/cl/42910)) does not cover clang.

**Comment by ALTree** [comment]
cc @ianlancetaylor

**Comment by ALTree** [comment]
@OneOfOne I'm assuming you are using the latest bootstrap archive, i.e.  [go1.4-bootstrap-20170531.tar.gz](https://storage.googleapis.com/golang/go1.4-bootstrap-20170531.tar.gz).

**Comment by OneOfOne** [comment]
@ALTree I'm using the `release-branch.go1.4` branch, trying to recompile it however absolutely fails, with both clang and gcc.

https://gist.github.com/OneOfOne/a9116d4c85c32141282fcf9a2973fbd2

**Comment by ALTree** [comment]
Ok so the clang issue is the `-r and -pie may not be used together` issue, for GCC, and it's the topic of this issue. 

Can you file another issue for the **other** problem? The fact that compiling go1.4-bootstrapping fails with 

```
# net
cannot load DWARF output from $WORK/net/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
# os/user
cannot load DWARF output from $WORK/os/user/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
```

on your system.

**Comment by ALTree** [comment]
> I still can't build go with clang even with go1.8 as bootstrap.

Wait, does this also affect go1.8? i.e. you can't build go1.8 from source with clang?

**Comment by OneOfOne** [comment]
@ALTree I hadn't tried until you mentioned it, no I can't build 1.8 from source either.

**Comment by ianlancetaylor** [comment]
Does clang support a `-no-pie` option?

**Comment by ALTree** [comment]
@ianlancetaylor looks like it does, but it's called `-nopie` (link: https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-nopie)

**Comment by ianlancetaylor** [comment]
Well, that sucks.  This is not an area where we need gratuitous differences.

**Comment by ianlancetaylor** [comment]
Does https://golang.org/cl/49711 fix the problem?  You may need 49710 too--49711 applies to Go 1.4, 49710 applies to tip.

**Comment by OneOfOne** [comment]
I can confirm it fixes the problem.
