### ISSUE TITLE
cmd/trace: when using 'go tool trace trace.out', the memory got 100%

### ISSUE THREAD

**Issue by ansencumt** [golang/go#21062]
When using 'go tool trace trace.out', the memory got 100%, and the PC blocked.

### What version of Go are you using (`go version`)?
go 1.8.3

### What operating system and processor architecture are you using (`go env`)?
![image](https://user-images.githubusercontent.com/5181385/28304396-fb417534-6bc9-11e7-87de-694ab61ba455.png)

### What did you do?

![image](https://user-images.githubusercontent.com/5181385/28304372-de19aabc-6bc9-11e7-87b4-12448bc843b2.png)

**Comment by ianlancetaylor** [comment]
Would it be possible to attach a copy of the trace.out file?

**Comment by ansencumt** [comment]
@ianlancetaylor Yes, the trace file is a copy from server. The server`s system is Ubuntu.

**Comment by ianlancetaylor** [comment]
@ansencumt I'm asking you to attach the trace file to this issue, so that we can try to recreate the problem ourselves.

**Comment by ansencumt** [comment]
OK. But the file is too big.So I have to send it with email. The target email is the personal email ian@airs.com. I can`t find the communal email, sorry.

**Comment by hyangah** [comment]
How big is the trace? The trace tool loads the entire trace into the memory.

**Comment by rsc** [comment]
@ianlancetaylor did ian@airs.com receive any trace? Maybe it's just too big and there's no bug here?

**Comment by ianlancetaylor** [comment]
Neither of us received a trace.

**Comment by ianlancetaylor** [comment]
@ansencumt If this is still a problem, please send the trace to iant@golang.org.  Thanks.
