### ISSUE TITLE
gddo: redirect to HTTPS

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21068]
You can visit content at http://godoc.org, but I think we should redirect all traffic from that domain to https://godoc.org. There are lots of reasons to want privacy while browsing godoc.org depending on the software you are reading about.

**Comment by bradfitz** [comment]
gddo bug tracker is https://github.com/golang/gddo/issues

**Comment by kevinburke** [comment]
Whoops, this is a dupe of golang/gddo#493.
