### ISSUE TITLE
x/talks: possible mix-up of semantic and syntactic

### ISSUE THREAD

**Issue by stemar94** [golang/go#21065]
The 2012/splash.article says:

>  The first example was a -r (rewrite) flag on gofmt itself, which uses a simple pattern-matching language to enable expression-level rewrites. For instance, one day we introduced a default value for the right-hand side of a slice expression: the length itself. The entire Go source tree was updated to use this default with the single command:
>
> gofmt -r 'a[b:len(a)] -> a[b:]'
>
> A key point about this transformation is that, because the input and output are both in the canonical format, the only changes made to the source code are semantic ones. 

### What did you expect to see?

the only changes made to the source code are ~~semantic~~ syntactic ones. 

For me this sentence feels like there should be stated "syntactic" instead of "semantic" since the semantics of the code doesn't change by applying the transformation.

**Comment by robpike** [comment]
No! The original is correct. Syntax is preserved is the point.

**Comment by stemar94** [comment]
I'm confused.
Then why are language features like these called syntactic sugar?
Probably we just have different view points concerning the transformation and how this should map to the sentence in the article.

**Comment by robpike** [comment]
The point is that the process guarantees correct syntax (and formatting) before and after. Any substantive change reflects deeper issues.
