### ISSUE TITLE
os: remove duplicate check from windows os.Stat

### ISSUE THREAD

**Issue by markus-oberhumer** [golang/go#21075]
There is a duplicate check for `file == nil` in the windows version of os.Stat().

Seems like an oversight in git commit 11c7b4491bd2cd1deb7b50433f431be9ced330db by @ianlancetaylor .

### What version of Go are you using (`go version`)?

Current go git master 1.9.x 73d02735734e1ed1e4d1f5a7c534206596f3903a .

### What did you do?

```
$ git diff 73d02735734e1ed1e4d1f5a7c534206596f3903a
diff --git a/src/os/stat_windows.go b/src/os/stat_windows.go
index 667b99905d..f9d8904bc4 100644
--- a/src/os/stat_windows.go
+++ b/src/os/stat_windows.go
@@ -16,9 +16,6 @@ func (file *File) Stat() (FileInfo, error) {
        if file == nil {
                return nil, ErrInvalid
        }
-       if file == nil {
-               return nil, syscall.EINVAL
-       }
        if file.isdir() {
                // I don't know any better way to do that for directory
                return Stat(file.dirinfo.path)
```

Please feel free to fix this trivial issue by yourself - I don't have a Gerrit account and a CLA (yet).

**Comment by johnnyluo** [comment]
I would like to work on this
