### ISSUE TITLE
x/build: run github.com/golang/gddo as part of Trybots

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21071]
I think this should be possible now since github.com/golang/gddo vendors all of its dependencies, and ported to App Engine Flex, so it should just run. 

That said, the gddo build is currently failing (https://github.com/golang/gddo/issues/499), so adding this would block successful trybots builds, I think.

cc @shantuo @broady

**Comment by kevinburke** [comment]
Because I just looked this up and so I don't forget, if we do want to turn this on I believe the correct place to add the change is in app/build/dash.go as an entry in the `goPackages` array

**Comment by bradfitz** [comment]
@dmitshur @katiehockman, is there interest in hooking up gddo to Go's test infrastructure or do y'all have some other plan for testing?

**Comment by dmitshur** [comment]
I think the interest is low. The current testing strategy is the person submitting a CL runs tests locally before submitting.

The volume of development in gddo is very low right now, and we're heading towards freezing it after some time. Parts of its codebase are unused and in poor/very outdated state, so it might cause extra effort to get it to a point where trybots can succeed. It's also using a somewhat unusual import path setup (see issue https://github.com/golang/gddo/issues/470). I don't think it'd be worthwhile.

**Comment by bradfitz** [comment]
> The current testing strategy is the person submitting a CL runs tests locally before submitting.

I guess that works when the number of supported platforms is 1. :-)

Okay, will close.

**Comment by dmitshur** [comment]
@bradfitz I've remembered that we also have post-submit builders via Travis CI on that repo. I.e., https://travis-ci.org/golang/gddo/builds.
