### ISSUE TITLE
x/tools/cmd/godoc: {tip,beta}.golang.org should redirect to https

### ISSUE THREAD

**Issue by dmitshur** [golang/go#21073]
http://golang.org redirects to https://golang.org (as do blog, tour, etc., subdomains), but http://beta.golang.org and http://tip.golang.org do not redirect to their https equivalent.

Is this an oversight? Or is it intentional (e.g., because it's needed for testing, or because it's too hard to redirect those domains)?

Unless there's a good reason for it, they should redirect to https. It's inconvenient and uses up people's time having to manually modify URLs to https form when visiting or sharing/pasting URLs.

**Comment by bradfitz** [comment]
No reason.

Because it was easiest, perhaps.

**Comment by kevinburke** [comment]
previously: https://github.com/golang/go/issues/19759

**Comment by agnivade** [comment]
Just wanted to mention that tip.golang.org redirects to https now. I can send a CL to make the change for beta.golang.org also, if somebody can point out where to make that change.

For tip, there is a special `x/tools/cmd/tip`, I don't see anything like that for `beta.golang.org`. There is just this comment inside `cmd/godoc/autocert.go` though.

```
// TODO: make this the default? We're in the Go 1.8 freeze now, so
// this is too invasive to be default, but we want it for
// https://beta.golang.org/
```
