### ISSUE TITLE
encoding/xml: marshaling/unmarshaling with namespace produces different results

### ISSUE THREAD

**Issue by syphoxy** [golang/go#21079]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.6.4 linux/amd64
```

_**Note:** I did try this with go 1.8.3 and the issue still persists._

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/spyroboy/.go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

I'm trying to Marshal and Unmarshal XML data but it appears that there are discrepancies between how XML is parsed and how XML is generated.

### What did you expect to see?

I expect that generating data is the same as parsing data.

### What did you see instead?

https://play.golang.org/p/Rex8DuLaTZ

**Comment by syphoxy** [comment]
modifying the input string here to remove the attributes produces interesting results as well

https://play.golang.org/p/NSA4p4USVF

**Comment by mvdan** [comment]
I'm fairly sure this is a dup of #13400.

**Comment by syphoxy** [comment]
yeah it appears to be. sorry about that. I hope my playground example will help in finding a solution.
