### ISSUE TITLE
net/http/httputil: ReverseProxy.ErrorLog should accept an interface

### ISSUE THREAD

**Issue by kedare** [golang/go#21082]
### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
Tried to use a custom logger on ReverseProxy.ErrorLog (like logrus)

### What did you expect to see?
A program compiling fine and logging going through my logger from logrus

### What did you see instead?
Compilation failed as ReverseProxy.ErrorLog has to be bound to a log.Logger.

ReverseProxy.ErrorLog should accept an interface instead, to allow using any compliant logging system.

Related to : https://github.com/sirupsen/logrus/issues/588

**Comment by mvdan** [comment]
Backwards compatibility can't be broken, so marking as Go2.

**Comment by bradfitz** [comment]
https://golang.org/pkg/log/#Logger.SetOutput

**Comment by kedare** [comment]
mvdan: But we use an interface that log.Logger matches, in theory it should not break anything, right ?

**Comment by mattn** [comment]
Possibly breaking compatibility.

```
proxy.ErrorLog = makeLogger()
```
makeLogger should have return typed `*log.Logger`.

**Comment by mvdan** [comment]
If the signature changes, that breaks the Go1 compatibility promise. @mattn showed the outline of a reasonable program that would break.

**Comment by ian-kent** [comment]
could we do something similar to how `Cancel` was deprecated in favor of `Context` in `net/http.Request`?

e.g., `Logger.SetOutput` maintains backwards compatibility and something like `Logger.SetOutputFunc(f func(format string, args ...interface{}))` with a new conditional to handle it here:
https://github.com/golang/go/blob/5ea2360b6643ec53018b1c080f4824b8238bff3a/src/net/http/httputil/reverseproxy.go#L325

**Comment by ianlancetaylor** [comment]
This should be handled as part of #5465.  Closing in favor of that issue.
