### ISSUE TITLE
net/mail: typo in ReadMessage doc

### ISSUE THREAD

**Issue by yansal** [golang/go#21089]
The doc at https://golang.org/pkg/net/mail/#ReadMessage says `ReadMessage reads a message from r. The headers are parsed, and the body of the message will be available for reading from r.`

The last part should be `the body of the message will be available for reading from msg.Body.` instead.

(I would be happy to send a CL to practice the contribution process.)

**Comment by bradfitz** [comment]
@yansal, go for it. I've marked it as Go 1.10, but if you do it very soon, it might be in Go 1.9.
