### ISSUE TITLE
debug/dwarf: StructField.ByteSize not set

### ISSUE THREAD

**Issue by randall77** [golang/go#21093]
The fields StructField.ByteSize is not set.  (ByteOffset is set.)
Demonstration:
```
package main

import (
	"debug/dwarf"
	"debug/elf"
	"fmt"
	"os"
)

func main() {
	binary := os.Args[0]
	f, err := os.Open(binary)
	if err != nil {
		panic(err)
	}
	e, err := elf.NewFile(f)
	if err != nil {
		panic(err)
	}
	d, err := e.DWARF()
	if err != nil {
		panic(err)
	}
	r := d.Reader()
	for e, err := r.Next(); e != nil && err == nil; e, err = r.Next() {
		if e.Tag != dwarf.TagStructType {
			continue
		}
		t, err := d.Type(e.Offset)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%s\n", t)
		s := t.(*dwarf.StructType)
		for _, f := range s.Field {
			fmt.Printf("  %d %d %s\n", f.ByteOffset, f.ByteSize, f.Name)
		}
	}
}
```
Build with `go build` and run it with no args.  It reads its own DWARF info and prints out the info for all the struct fields.
Start of output:
```
struct runtime._type
  0 0 size
  8 0 ptrdata
  16 0 hash
  20 0 tflag
  21 0 align
  22 0 fieldalign
  23 0 kind
  24 0 alg
  32 0 gcdata
  40 0 str
  44 0 ptrToThis
struct runtime.typeAlg
  0 0 hash
  8 0 equal
struct runtime.interfacetype
  0 0 typ
  48 0 pkgpath
  56 0 mhdr
```

I think this is a bug with debug/dwarf, not the DWARF writer in the toolchain.  I get the same behavior when reading DWARF from a C binary. (Or perhaps the C writer has the same issue?)

ByteSize might be kind of useful (or is .Type.Size() the recommended fallback instead?). At the very least, we should document that it isn't provided.

@heschik @derekparker

**Comment by heschik** [comment]
I don't think this is a bug in debug/dwarf, and probably isn't a bug at all. DW_TAG_member can optionally have a DW_AT_byte_size, but it's not required. From dwarf4:

```
If the size of a data member is not the same as the size of the type given for the data member, the
data member has either a DW_AT_byte_size or a DW_AT_bit_size attribute whose integer
constant value (see Section 2.19) is the amount of storage needed to hold the value of the data
member.
```

I'm not sure what circumstances would cause that to happen in any language, but it can't in Go AFAIK. So  I think the short story is you should be looking at f.Type.Size().

**Comment by ianlancetaylor** [comment]
Not important here, but to answer the question: the size of a data member differs from the size of the data member's type for a C/C++ bitfield.

**Comment by heschik** [comment]
@randall77 : anything further here?

**Comment by randall77** [comment]
@heschik I think we should either add a comment to debug/dwarf, or better modify the code so that it does the StructField.ByteSize = Type.Size() for you.
The DWARF representation doesn't include the size when it is redundant with the type size because it is optimized to save space.  But the debug/dwarf API doesn't have that constraint.
