### ISSUE TITLE
debug/dwarf: funcs have size -1

### ISSUE THREAD

**Issue by randall77** [golang/go#21097]
The DWARF type of a func has size -1.  That's wrong.  It should be pointer sized.
The problem compounds: [4]func() has size -4.

**Comment by meggamind** [comment]
hey @randall77 : Can I work on this issue? I'm fairly new. I may need your help. Thanks

**Comment by ALTree** [comment]
@meggamind It looks like Keith already mailed a fix for this issue (look at the gopherbot post above you)

**Comment by meggamind** [comment]
:+1:  my bad
