### ISSUE TITLE
syscall: Add to Token to Windows syscall.SysProcAttr

### ISSUE THREAD

**Issue by pquerna** [golang/go#21105]
### What version of Go are you using (`go version`)?

go1.9beta2

### What did you do?

[`syscall.SysProcAttr`](https://github.com/golang/go/blob/go1.9beta2/src/syscall/exec_windows.go#L221-L225) on Windows is currently very limited. On Linux/Unixes, it has been [extended to include many features like UID Mapping, chroot, etc](https://github.com/golang/go/blob/go1.9beta2/src/syscall/exec_linux.go#L22-L43).

Adding `Token syscall.Handle` field to `SysProcAttr` and using it as a parameter to `CreateProcessAsUser` would enable many use cases on Windows, including:
 - Launching processes as a different user
 - Setting [Windows Integrity Level (see "Starting a process at low integrity")](https://msdn.microsoft.com/en-us/library/bb625960.aspx) to run a child process with reduced privileges

Besides the new struct field, `syscall.StartProcess` would need to call [CreateProcessAsUser instead of CreateProcess](https://github.com/golang/go/blob/go1.9beta2/src/syscall/exec_windows.go#L324)

The equivalents of these are already possible on Linux.

We have maintained a partial internal fork of `os/exec` since go1.4 where we pass in a Token, and use `CreateProcessAsUser`, but some of our tests broke in go1.9beta2 (our fault), but we would love to see this go into upstream at some point.

**Comment by alexbrainman** [comment]
I think it is good idea. And will not be too complicated to implement.
@pquerna, please, ping us if you won't get decision soon. Thank you.

Alex

**Comment by pquerna** [comment]
@alexbrainman decision on this feature?  Thanks!

**Comment by alexbrainman** [comment]
> @alexbrainman decision on this feature?

Like I said before, this sounds good to me. But I don't do deciding here, @rsc makes desisions. What do you think, Russ?

If we want this implemented for go1.10, we need to do it quickly - freeze for go1/10 is about to start https://groups.google.com/d/topic/golang-dev/csSLMsd7SF4/discussion

If we decide to do it, the change would have to include some test that demonstrates / verifies new feature. @pquerna do you have any suggestion for the test? Do you want to implement whole thing. if it is approved? Thank you.

Alex

**Comment by pquerna** [comment]
The actual changes are small:

https://github.com/golang/go/compare/master...pquerna:windows_add_token_to_sys_proc_attr

Making a test case that launches a process at a lower integrity level is hard to do without a few hundred lines of new code (needs new bindings to CreateWellKnownSid, DuplicateTokenEx, SetTokenInformation, along with a few new structs/enums). Most of these could go into x/sys/windows, but that another whole set of CRs for a test case.

**Comment by bradfitz** [comment]
Seems reasonable to me.

But the freeze for new features was today. (I just got back today)

Do you want to send a Gerrit change? If you can do it within this week and it looks safe, it might still make it to Go 1.10. Otherwise it'll likely be a Go 1.11 thing.

**Comment by alexbrainman** [comment]
> Making a test case that launches a process at a lower integrity level is hard to do without a few hundred lines of new code (needs new bindings to CreateWellKnownSid, DuplicateTokenEx, SetTokenInformation, along with a few new structs/enums). Most of these could go into x/sys/windows, but that another whole set of CRs for a test case. With that dance, your test would look something like this: https://gist.github.com/pquerna/04f1933e5f6ced7f66f1f181d1c21ebf

Yes I had something like that in mind. And we need to test your new code, so I would like to see that test before we discard it as "too many lines". We cannot put all that code into x/sys/window, because it needs to be part of main repo, so internal/syscall/windows is the place. Maybe we can use some of our existing code from syscall/security_windows.go. If you want to to another CR (or CRs) for the test that is fine too. Thank you.

Alex
