### ISSUE TITLE
encoding/pem: unexpected segfault in darwin/amd64 TryBot run

### ISSUE THREAD

**Issue by bcmills** [golang/go#21103]
### What version of Go are you using (`go version`)?

darwin-amd64-10_11 at cb1917994cf16b221ac82a5ea8331e2a80b8f1a6

### What did you do?

Ran TryBots for https://golang.org/cl/50371.

### What did you expect to see?

All tests pass, or any failures are related to my change.

### What did you see instead?

https://storage.googleapis.com/go-build-log/cb191799/darwin-amd64-10_11_f6d4a343.log

```
darwin-amd64-10_11 at cb1917994cf16b221ac82a5ea8331e2a80b8f1a6

[…]

##### Testing packages.
[…]
ok  	encoding/binary	0.019s
ok  	encoding/csv	0.027s
ok  	encoding/gob	0.056s
ok  	encoding/hex	0.016s
ok  	encoding/json	0.334s
signal: segmentation fault
FAIL	encoding/pem	1.021s
ok  	encoding/xml	0.041s
ok  	errors	0.013s
2017/07/20 11:12:54 Failed: exit status 1


Error: tests failed: dist test failed: go_test:encoding/csv: exit status 1
```

**Comment by bcmills** [comment]
There are two weird features in the log: one is the `signal: segmentation fault`, and the other is that the last line reports the error as `go_test:encoding/csv`, but the summary block above shows `encoding/csv` as passing and `encoding/pem` as failing.

**Comment by bradfitz** [comment]
The csv-vs-pem is probably due to test sharding. The build coordinator gives out chunks of test units to different machines and stitches together the output. The name of that test unit was probably "encoding/csv" because that was the first in the chunk or something.

/cc @andybons @cybrcodr @adams-sarah

**Comment by rsc** [comment]
Timed out.
