### ISSUE TITLE
net/http: extra space in panic message

### ISSUE THREAD

**Issue by kanata2** [golang/go#21102]
In net/http/server.go,
```go
if pattern == "" {
    panic("http: invalid pattern " + pattern)
}
```

I think the last space of `"http: invalid pattern "` and `+ pattern` are unnecessary because pattern is an empty string, so please review this 🙏 
I'll send a change request if there is no problem.

**Comment by bradfitz** [comment]
Yeah, that looks like a copy/paste oversight from a few lines later.

Sure, send a change.
