### ISSUE TITLE
Issue with Removing Item from Slice when iterating

### ISSUE THREAD

**Issue by pjebs** [golang/go#21109]
I'm not sure if this is a bug or due to the memory arrangement in the backing array.

If I iterate backwards on a slice, I can remove a particular item in slice with no problems.
The issues seems to be when there is a nested slice and I do the same thing in the nested slice.

https://play.golang.org/p/yuMLiXH5RC

In the example provided, you can see from the output:

`[{P0 false [{D0 false} {D2 false} {D2 false}]}`

You can see that D1 was removed, but it has now been replaced with a copy of D2 instead.

If this is due to a bug, it is definitely major.

**Comment by smasher164** [comment]
In your example, when you define
```
person := people[i]
```
Go copies the struct for the Person at that index. So later when you assign
```
person.Dogs = append(person.Dogs[:j], person.Dogs[j+1:]...)
```
`person.Dogs` and `people[i].Dogs` refer to different slices. To see the change reflected on the original slice, instead assign
```
people[i].Dogs = append(person.Dogs[:j], person.Dogs[j+1:]...)
```

**Comment by ianlancetaylor** [comment]
Closing because there is no bug here.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
