### ISSUE TITLE
How to get value's type 'const char * MyFunc' from dll export

### ISSUE THREAD

**Issue by yanghuxiao** [golang/go#21110]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/386

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Go\projects\
set GORACE=
set GOROOT=D:\Go\bin\go
set GOTOOLDIR=D:\Go\bin\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
The dll export function like  `const char * MyFunc()`
the C include file like this
```
extern "C" __declspec(dllexport) const char * MyFunc()
{
//....
}
```
When I use python,I can do like this 
```
dll =  CDLL('MyDLL')
MyFunc = loadFun('MyFunc',c_char_p)
result = MyFunc()
```
the vals return the value I want.
When I use go
```
MyDLL := syscall.MustLoadDLL("MyDLL")
MyFunc := DllNLPIR.MustFindProc("MyFunc")
result, _, _ := MyFunc.Call()
fmt.Println(result)
fmt.Println(reflect.TypeOf(result))
```

### What did you expect to see?
the MyFunc return `const char * MyFunc`

### What did you see instead?
830541584
uintptr

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
