### ISSUE TITLE
build: update 1.4 release for -nopie fix

### ISSUE THREAD

**Issue by josharian** [golang/go#21116]
#21042 fixed an issue in the 1.4 release branch. We should update the 1.4 source release tarball and docs.

@broady @bradfitz

**Comment by ALTree** [comment]
Tangential, but I'd suggest changing the milestone name to `go1.4-bootstrap` and the milestone description, it's quite misleading

> We will likely never make a Go 1.4.4 release. The only reason to do so would be to ease bootstrapping of newer Go releases

a) we regularly publish new go1.4-bootstrap releases to "ease bootstrapping" b) they're not called go1.4.4, they're called go1.4-bootstrap

**Comment by josharian** [comment]
> I'd suggest changing the milestone name to go1.4-bootstrap and the milestone description

Huh. Apparently I can edit milestones (!). Done. Anyone who cares about the text there should review. cc @kevinburke in case maintner cares. I left the capital "G" in the milestone name to match the others for now.

**Comment by ALTree** [comment]
> Huh. Apparently I can edit milestones

@josharian me too. I think it's normal (for users marked as **Member**). 

I asked (instead of changing it myself) because I wasn't sure people would be fine with it.

**Comment by josharian** [comment]
> I asked (instead of changing it myself) because I wasn't sure people would be fine with it.

Guess I'll ask forgiveness instead of permission then. :) I wish GitHub had all this config in the repo itself, so this could be codereviewed.

**Comment by josharian** [comment]
@ALTree yes, thanks.
