### ISSUE TITLE
x/playground: add syntax highlighting

### ISSUE THREAD

**Issue by mapeiqi** [golang/go#21123]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
any

### What operating system and processor architecture are you using (`go env`)?
any

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

open any go playground link, such as https://play.golang.org/

### What did you expect to see?
highlighted go source code, or have a button called sth like "syntax highlight"

### What did you see instead?
go source code is not syntax highlighted, and have no button to do that.

**Comment by odeke-em** [comment]
I think I've previously seen this discussed either on Github or on Twitter.

Let me ping some folks who might know better /cc @rakyll @campoy @spf13 @kevinburke @adg

**Comment by dsnet** [comment]
https://groups.google.com/forum/#!searchin/golang-nuts/syntax$20highlighting$20playground|sort:relevance/golang-nuts/hJHCAaiL0so/X4rKDXbuLH8J

**Comment by ALTree** [comment]
@mapeiqi this alternative playground frontend: https://goplay.space has syntax highlighting. It's just a frontend, so your program will be forwarded to the official playground and executed and stored there.

**Comment by mapeiqi** [comment]
@ALTree Actually I have done a google search after @dsnet 's reply, and found the goplay.space website. That is why I close the issue. But thanks for the reply.
