### ISSUE TITLE
Go compile exe with Filecoder.NKZ trojan inside 

### ISSUE THREAD

**Issue by evgeniybutenko** [golang/go#21125]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Yevhenii\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
When I'm compiling for adm64 - everythink is ok, but whem I change GOARCH for 386 my antivirus alert to me that my compiled exe file contain a WIN32/Filecoder trojan!
Also I create discussion on StackOverflow, please visit this link, you find more information there  https://stackoverflow.com/questions/45246031/golang-compile-exe-with-trojan-inside?noredirect=1#comment77464937_45246031

### What did you expect to see?
32x windows exe file 

### What did you see instead?
exe file with trojan inside

**Comment by davecheney** [comment]
This is very likely a false positive caused by your AV software. This happens quite often. You should report this to your AV software vendor.

**Comment by evgeniybutenko** [comment]
But look, like I wrote on SO before -  I scanned everything twice, and reinstall Go twice, so even if some malware was exist, it's gone after reinstalling. For 64x system compilation works fine, no problem, no viruses, only for 386.

**Comment by davecheney** [comment]
It's not a trojan, you AV software is faulty.

**Comment by davecheney** [comment]
This is a common problem with windows anti virus programs, https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20antivirus

**Comment by bradfitz** [comment]
What @davecheney said. File a bug with your AV vendor. Or you already have a virus on your machine infecting your binaries and it only knows how to attach itself to 386 binaries.
