### ISSUE TITLE
x/crypto/ed25519: document whether Verify is constant time

### ISSUE THREAD

**Issue by kevinburke** [golang/go#21137]
There [have been some questions](https://github.com/kevinburke/nacl/issues/1) whether this function runs in constant time or not. I assume it does, otherwise there would be no reason to call subtle.ConstantTimeCompare on the last line of the function, but it would be good to double check, and/or document this.

**Comment by agl** [comment]
It does not, since it operates only on public data. The use of `ConstantTimeCompare` at the end is just out of habit and is misleading. I'll change that.
