### ISSUE TITLE
gccgo: libgo/mksigtab.sh broken on ppc64le with upstream glibc change affecting _NSIG

### ISSUE THREAD

**Issue by laboger** [golang/go#21147]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
gccgo from gcc 7

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 ppc64le

### What did you do?
We have a build team attempting to build gccgo from the gcc-7 branch using upstream glibc which will be 2.26.

### What did you expect to see?
Successful build.

### What did you see instead?
Runtime errors when using the built gccgo.  This happens when attempting to do:
go version

panic: runtime error: index out of range

Through debugging it was found that the problem occurs in
libgo/go/runtime/signal_unix.go:85
Inside function initseg is this loop:

     for i := uint32(0); i < _NSIG; i++ {
                    t := &sigtable[i]        <----- error occurs here because len(sigtable) and _NSIG don't match
                    if t.flags == 0 || t.flags&_SigDefault != 0 {
                            continue
                    } 
                    fwdSig[i] = getsig(i)

                    if !sigInstallGoHandler(i) {
                            // Even if we are not installing a signal handler,
                            // set SA_ONSTACK if necessary.
                            if fwdSig[i] != _SIG_DFL && fwdSig[i] != _SIG_IGN {
                                    setsigstack(i)
                            }
                            continue
                    }

                    t.flags |= _SigHandling
                    setsig(i, getSigtramp())
            }

Further debugging shows that the sigtab.go file is generated incorrectly.  The value of _NSIG ends up being 65 but there are only 34 entries put into the sigtable.

The reason for this is this line in mksigtab.sh:

nsig=`grep 'const _*NSIG = [0-9]*$' gen-sysinfo.go | sed -e 's/.* = \([0-9]*\)/\1/'`

But _NSIG in gen-sysinfo.go now looks like this so doesn't match:

const __NSIG = (___SIGRTMAX + 1)

The glibc patch that causes the issue is https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=8082d91e1c449e0cb137468b731004a5e605c8c6.

@ianlancetaylor If you have a workaround to suggest, that would be appreciated.

**Comment by ianlancetaylor** [comment]
What is the definition of `___SIGRTMAX` in the generated file gen-sysinfo.go?

**Comment by ianlancetaylor** [comment]
@laboger Could you see if https://golang.org/cl/52611 fixes the problem?  Thanks.

**Comment by ianlancetaylor** [comment]
@tuliom Thanks, I updated the CL.
