### ISSUE TITLE
cmd/go: a program that does not invoke testing package features has test flags added into CLI flags

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#21141]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
Linux on x86-64

### Code sample

<pre>
package main

import (
	"testing"
	"flag"
)

func main() {
	println("hi")
	flag.Parse()
}

func a(t *testing.T) {
}
</pre>

Observe that, once compiled, test flags are added into the executable:

<pre>
> go build -o main
> ./main -help   
hi                        
Usage of ./main:     
  -test.bench regexp      
        run only benchmarks matching regexp
  -test.benchmem
        print memory allocations for benchmarks
......
......
</pre>

### What did you expect to see?
The function `a` uses `testing` package, however, since the function is dead code to the entire program, the `testing` package features are never utilised and test flags should never have been compiled into the executable.

**Comment by cznic** [comment]
The init function in package testing is not dead code. Working as intended.

**Comment by mvdan** [comment]
See @cznic's answer.

**Comment by HouzuoGuo** [comment]
For future readers: you can work around this issue by making a stub interface definition that works just like a `testing.T`: https://github.com/HouzuoGuo/laitos/blob/master/testingstub/testingstub.go
