### ISSUE TITLE
Proposal: Algebraic Data Types

### ISSUE THREAD

**Issue by henryas** [golang/go#21154]
## Overview

Go currently supports grouping data types by their behavior. For instance, the Writer interface below supports any type that implements the _Write_ behavior.
````
type Writer interface {
        Write(p []byte) (n int, err error)
}
````
and you can do as follows because bytes.Buffer implements the Writer interface.
````
var buffer bytes.Buffer
fmt.Fprint(&buffer, "Hello")
````

However, there are times when we need to group data by their domain relevance instead of their behavior. For example, we may need to group certain documents as _sales document_ and others as _cash document_ and some may belong to more than one group. Each document may exhibit different behavior and may not have anything in common with one another at all. For instance:
````
type SalesDocument = Invoice, SalesReturn, PaymentReceipt
type CashDocument = PaymentReceipt, CashReimbursement
````
Now we can do this:
````
//given the following definition
sales.Process(doc SalesDocument)
cash.Process(doc CashDocument)

sales.Process(invoice) //where invoice is of Invoice type
sales.Process(cashReimbursement) //illegal: wrong type
````

## Benefits

How is this different from Go's current approach? 
````
sales.Process(doc interface{})
````
The difference is that the compiler can now enforce _static type checking_ and have the error caught during compile time. The definition of SalesDocument and CashDocument are clear and known during compile time.

How about this? 
````
sales.Process(doc Document) //where Document is the generic interface for all document
````
The problem with the above approach is that you can pass non-sales document into the function and the error will not be caught until run time.

The complete sales.Process function may be something like this.
````
package sales

func Process(doc SalesDocument) {
    match d := doc.(type) {
        case Invoice:
            //....
        case SalesReturn:
            //....
        //etc.
    }
}
````

## Optional: Null Safety

There are two options. First, we can have the algebraic data type have _nil_ as its default value. It will act like a normal Go interface type.

Second, we can have the algebraic data type allows only the explicitly stated types. This second option will improve null safety. 
````
type NonNullableDocument = Doc1, Doc2, Doc3      //non-nullable
type NullableDocument = Doc1, Doc2, Doc3, nil       //nullable

func ProcessDocument(doc NonNullableDocument) {
    //there is no need for nil-checking here ... 
}

ProcessDocument(nil) //illegal: will not compile.
````
Since the definition of _NonNullableDocument_ and _NullableDocument_ are explicit, it should be enforceable by the compiler.

## Closing

Let me know what you think. 

Thanks

Henry

**Comment by mvdan** [comment]
This sounds exactly like sum types: https://github.com/golang/go/issues/19412

Closing as a duplicate. Even if your proposal is slightly different, it would probably be best to keep discussion in that thread and make your suggestions there.
