### ISSUE TITLE
net/url: resolvePath should not collapse leading slashes in the path component

### ISSUE THREAD

**Issue by marktheunissen** [golang/go#21158]
### What version of Go are you using (`go version`)?

master

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

Using Go's `net/http` DefaultClient, make a  GET request that returns a redirect to a fully formed Location URI.

```
GET /foo
Host: example.com
```
```
HTTP/1.1 301 Moved Permanently
Location: http://example.com//foo/bar
```

### What did you expect to see?

The `http.Client` should redirect to`http://example.com//foo/bar`, as instructed by the Location header.

### What did you see instead?

The `http.Client` redirected to `http://example.com/foo/bar`, which is a cleaned-up URL, with a single slash instead of double.

The `http.Client.Do()` code is using `req.URL.Parse()` on the Location header here: https://github.com/golang/go/blob/master/src/net/http/client.go#L529-L538

### Behaviour of other clients

`curl` will use the Location header byte-for-byte, and correctly redirect to the double-slash:

```
$ curl -Lv http://example.com/foo
> GET /foo
...
< HTTP/1.1 301 Moved Permanently
< Location: http://example.com//foo/bar
...
* Issue another request to this URL: 'http://example.com//foo/bar'
...
> GET //foo/bar HTTP/1.1
```

### Playground

Here is an example of the incorrect behavior:

https://play.golang.org/p/ZgPpXddu2G

**Comment by marktheunissen** [comment]
Patch: https://go-review.googlesource.com/c/51050/

**Comment by rsc** [comment]
If I make the example be https://play.golang.org/p/NNfbZF_Yd_ with the URL being example.com//foo//bar, we preserve the second //; we should preserve the first too. This is just a bug on my part. I probably wrote the code using strings.TrimLeft before strings.TrimPrefix existed, and I was lazy. Thanks for fixing it.
