### ISSUE TITLE
x/crypto/acme/autocert: expose cacheDir function

### ISSUE THREAD

**Issue by bradrydzewski** [golang/go#21151]
I would like the ability to use the default cache directory logic in situations where I have to create a custom cert manager, however, it is currently a private function. Would a change to expose this logic be accepted?

Reference code: https://github.com/golang/crypto/blob/6914964337150723782436d56b3f21610a74ce7b/acme/autocert/listener.go#L142

**Comment by bradfitz** [comment]
I'd rather not.

This is an ACME cert package, not a filesystem path package.

Stuff like https://godoc.org/go4.org/xdgdir exists to return conventional paths.

**Comment by bradrydzewski** [comment]
Thanks for the quick reply!

> This is an ACME cert package, not a filesystem path package.

To clarify I am less interested in the path value, and more interested in obtaining a `DirCache`  using default path logic when I am unable to use `NewListener`.

Something like this:

```diff
manager := autocert.Manager{
	Prompt:     autocert.AcceptTOS,
	HostPolicy: autocert.HostWhitelist(address.Host),
+	Cache:      autocert.DefaultDirCache(),
}
```

The `cacheDir` function includes some additional logic for windows and falls back to the home directory. I was looking for a consistent way to cache certificates regardless of how `autocert.Manager` is created, but certainly understand this is a nice to have.

> Stuff like https://godoc.org/go4.org/xdgdir exists to return conventional paths.

Thanks for the link, I will investigate further to see if I can use in my project.

**Comment by ALTree** [comment]
It appears we're not going to do this, so I'm closing this issue.
