### ISSUE TITLE
x/crypto/ssh: panic: handshake failed: ssh: host key mismatch

### ISSUE THREAD

**Issue by Mester19** [golang/go#21166]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mester/.go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build052168145=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
I'm trying to connect to my server using ssh client created in Golang.
Here is the code: https://play.golang.org/p/0y6hzwg7Lz
### What did you expect to see?
The terminal of my server

### What did you see instead?
I see a panic lol

**Comment by ianlancetaylor** [comment]
Please show us the complete panic output.

**Comment by Mester19** [comment]
Solved. I create another function with the callback:
func check(hostname string, remote net.Addr, key ssh.PublicKey) error {
  return nil
}

func HostKeyCallback(key ssh.PublicKey) ssh.HostKeyCallback {
  return check
}

And it works.

**Comment by ianlancetaylor** [comment]
Closing.
