### ISSUE TITLE
cmd/go: cannot build go binary on Windows

### ISSUE THREAD

**Issue by nedn** [golang/go#21169]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\admin\projects\chromium\src\third_party\catapult\web_page_replay_go;C:\Users\admin\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
Install https://mingw-w64.org/doku.php
git clone https://github.com/catapult-project/catapult (in this case I already have this folder in C:\Users\admin\projects\chromium\src\third_party\)
cd web_page_replay_go
Follows the instructions in https://github.com/catapult-project/catapult/blob/master/web_page_replay_go/README to fetch required dependencies.

Run `go build src\wpr.go` to build wpr-go binary.

### What did you expect to see?
Be able to build wpr.exe binary.

### What did you see instead?
```
PS C:\Users\admin\projects\chromium\src\third_party\catapult\web_page_replay_go> go build .\src\wpr.go
# command-line-arguments
C:\Go\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1
C:\Users\admin\AppData\Local\Temp\go-link-156760755\go.o: file not recognized: File format not recognized
collect2: ld returned 1 exit status
```

**Comment by sajattack** [comment]
I was not able to reproduce this bug.

**Comment by nedn** [comment]
My colleague cannot reproduce this either. so probably my windows instance has some problem.

We currently find a way to work around this by remove go libs that are not purely go. So this is not a blocker for us anymore. Thanks for taking a look anyway!
