### ISSUE TITLE
reflect: promoted methods or fields should be detectable

### ISSUE THREAD

**Issue by notzippy** [golang/go#21162]
### What version of Go are you using (`go version`)? 
1.8.3

### What operating system and processor architecture are you using (`go env`)? 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/work/go1.8.3/global"
GORACE=""
GOROOT="/mnt/work/go1.8.3"
GOTOOLDIR="/mnt/work/go1.8.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build193876869=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### Issue

Currently promoted fields and methods are indiscernible in reflection, this causes issues encoding and decoding issues because doing a deep dive into the struct it is impossible to determine if a field or method is associated with the parent struct or inherited from the embedded structure. There is scattered references to this issue across github, like #17609 where the ambiguity between the top struct and embedded struct causes issues.

Here is a small example demonstrating the issue with methods, though the same can be said for fields as well.
https://play.golang.org/p/hGgtJLJJPI

And another demonstrating how the json encoding mechanism fails to fully encode data because of this 
https://play.golang.org/p/2oOXH2uzWy

### What would you like to see
Likely easiest to add a method to reflect.Value so that you can check to see if a field/method was promoted. At the root of it they must both reference the embedded field or method.

### What did you see instead?
Confusion chaos and guessing

**Comment by rsc** [comment]
These are indistinguishable in the language and should probably also be indistinguishable to reflect. In fact, if anything I would lean toward making reflect expose _less_ about structs, not more. Anything we expose with reflect becomes something that's nearly impossible to fix in a refactoring, even though from a language level you'd expect no one could tell the difference.

**Comment by Steve-hyas** [comment]
I disagree with the statement that Go makes inherited fields indistinguishable from other fields.  For example [this](https://play.golang.org/p/0he3gt4k-E) shows that the language allows for directly referencing the variable through the embedded type name. Since the language does allow for this then, following your above logic, reflect should be able to do the same.

**Comment by notzippy** [comment]
I disagree with the statement that Go makes inherited fields indistinguishable from other fields.  For example [this](https://play.golang.org/p/0he3gt4k-E) shows that the language allows for directly referencing the variable through the embedded type name. Since the language does allow for this then, following your above logic, reflect should be able to do the same.

**Comment by ianlancetaylor** [comment]
The reflect package does permit doing that.  https://play.golang.org/p/6OWqt9wNVR .
