### ISSUE TITLE
cmd/go: doc returns wrong error message about missing package, where just the function name is wrong.

### ISSUE THREAD

**Issue by ikrabbe** [golang/go#21176]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +df91b8044d Tue Jul 25 20:31:25 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux-amd64

### What did you do?

> go doc github.com/aws/aws-sdk-go/service/opsworks SomeTypo
doc: cannot find package "github.com/aws/aws-sdk-go/services/opsworks" in any of:
	/home/ingo/src/go.local/src/github.com/aws/aws-sdk-go/services/opsworks (from $GOROOT)
	/home/ingo/go/src/github.com/aws/aws-sdk-go/services/opsworks (from $GOPATH)

### What did you expect to see?

doc: package "github.com/aws/aws-sdk-go/services/opsworks"  does not contain a symbol named "SomeTypo".

### What did you see instead?

The error statement is just wrong, because actually there *is such a package* in my environment.
Such error statements make fixing local installations confusing and time consuming.

**Comment by ALTree** [comment]
I can't reproduce this with go1.8.3 or go tip.

```
$ go get github.com/aws/aws-sdk-go
$ go doc github.com/aws/aws-sdk-go/service/opsworks SomeTypo
doc: no symbol SomeTypo in package github.com/aws/aws-sdk-go/service/opswork
```

There must be something wrong with your environment. 

Also you wrote (in **What did you do?**) that you run

`go doc github.com/aws/aws-sdk-go/service/opsworks SomeTypo`

but then why the error message you posted says:

> doc: cannot find package "github.com/aws/aws-sdk-go/service**s**/opsworks

with "services" with an "s" ?

**Comment by ikrabbe** [comment]
sorry, you are right, I was wrong.
