### ISSUE TITLE
x/playground: missing output in Playground example

### ISSUE THREAD

**Issue by bcmills** [golang/go#21170]
The example program from #21168 (https://play.golang.org/p/XPEU7FoTes) can only exit early if it panics, and ends with an unconditional call to `fmt.Println` with an `int64` argument.

Oddly, with the current Playground version of the Go compiler, it appears to print a blank line instead of the final number:
![screenshot 2017-07-25 at 17 24 43](https://user-images.githubusercontent.com/5200974/28594648-b8ada9c8-715e-11e7-9580-7c435242aa2f.png)

The gray (rather than red) text at the bottom and lack of a panic dump suggest that the program did, in fact, run to completion, but where is the output?

**Comment by opennota** [comment]
`fmt.Println(n+1)` works the same way. With `fmt.Println(1)`, `fmt.Println(n*1)` or `fmt.Println(n,n)` I get either "process took too long" or "Error communicating with remote server." It's funny.

**Comment by ysmolsky** [comment]
Right now this program reports "took too long" on play.golang.org. 

I ran this program on local playground and it was able to execute in 2 seconds some of the launches. Sometimes it returned "too too long".

**Comment by andybons** [comment]
I too see this as being reported as “process took too long”. When reducing the constant `maxInt` so that it returns in under 2 seconds, the output it printed as expected.
