### ISSUE TITLE
release: windows MSI installer minor UI bug

### ISSUE THREAD

**Issue by pinebit** [golang/go#21180]
### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
Ran MSI installer.

### What did you expect to see?
Properly displaying file and folder names in the status string.

### What did you see instead?
![go-msi-bug](https://user-images.githubusercontent.com/6468078/28638431-83856688-724d-11e7-886c-a362e97a64a5.png)

**Comment by johnsonj** [comment]
What version/build of windows? Ctrl+R `winver`

**Comment by pinebit** [comment]
@johnsonj It is Windows 10 Pro (1703)
Let me know if you need more input.
