### ISSUE TITLE
runtime: blocked channel operations starvation

### ISSUE THREAD

**Issue by johnsnow4514** [golang/go#21187]
### What version of Go are you using (`go version`)?
1.8.0

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
Related to #11506  
I have a messaging app that generates messages and passes them using a channel to  
go-routines whose job is to transform those messages into small packets of data which then passes  
using another channel to go-routines whose job is to read the packets and send them using a socket.  

### What did you expect to see?
packets that are generated at some point in time should be sent around the same time.  
there shouldn't be more than a few milliseconds between sending a packet to a channel and receiving it  
on the receiving go-routine.

### What did you see instead?
In some cases a go-routine might starve for like 30 seconds while other packets are transferred just fine.  
This causes problems in my app and I had to implement my own wrap around a channel to insure FIFO  
ordering which fixed the problem.  
is there any plans to fix #11506 ? @rsc @randall77  
it really causes weird and rare behaviors in production environments  
Here's my implementation for FIFO channeling if anyone is facing the same problem...

```
package utils

import (
	"sync"
	"sync/atomic"
)

type FifoChannel struct {
	innerChan                       chan interface{}
	conditions                      map[uint64]*sync.WaitGroup
	mapLock                         *sync.RWMutex
	currentPriority, latestPriority *uint64
}

func NewFifoChannel(innerChan chan interface{}) *FifoChannel {
	zero1 := uint64(0)
	zero2 := uint64(0)
	return &FifoChannel{
		innerChan:       innerChan,
		currentPriority: &zero1,
		latestPriority:  &zero2,
		conditions:      make(map[uint64]*sync.WaitGroup),
		mapLock:         new(sync.RWMutex),
	}
}

func (fc *FifoChannel) Add(item interface{}) {
	myPriority := atomic.AddUint64(fc.latestPriority, 1) - 1
	if myPriority != atomic.LoadUint64(fc.currentPriority) {
		gate := new(sync.WaitGroup)
		gate.Add(1)
		fc.mapLock.Lock()
		fc.conditions[myPriority] = gate
		fc.mapLock.Unlock()
		if myPriority != atomic.LoadUint64(fc.currentPriority) {
			gate.Wait()
		}
		fc.mapLock.Lock()
		delete(fc.conditions, myPriority)
		fc.mapLock.Unlock()
	}
	fc.innerChan <- item
	atomic.AddUint64(fc.currentPriority, 1)
	fc.mapLock.RLock()
	if gate, exist := fc.conditions[myPriority+1]; exist {
		gate.Done()
	}
	fc.mapLock.RUnlock()
}

func (fc *FifoChannel) Get() interface{} {
	return <-fc.innerChan
}
```

**Comment by mvdan** [comment]
Have you tried on 1.9rc1? What about other operating systems, like Linux?

Also CC @aclements

**Comment by johnsnow4514** [comment]
@mvdan not yet. I find it hard to reproduce in my program.  
The thing is, I am using my FIFO channel only with the packets producer/consumer logic  
After 6 months in production the problem occurred on some higher level channel (on messages channel, instead of the packets channel).  
The symptom was that some messages starved for around 30-40 seconds and created some kind of a timeout.  
Fortunately I also found this issue #6205 which linked to a reproducible [playground code](https://play.golang.org/p/06bz6Td0Mg)  
I'll soon test this code on 1.9rc1 and linux

**Comment by ianlancetaylor** [comment]
I don't see a bug in the playground code in the last comment.  It's true that the number of values sent on the different channels can be very unequal, but that is not a bug.  It also doesn't seem to directly correspond to the original problem description, which was about multiple receiving goroutines rather than multiple sending goroutines.

With multiple receiving goroutines, it's still not a bug if one of them is starved.  Why does it matter as long as all the values sent on the channel are being delivered to some goroutine?

**Comment by johnsnow4514** [comment]
@ianlancetaylor I was talking about multiple sending go-routines. One can starve and it's message  
will not be passed on for a long time.

**Comment by ianlancetaylor** [comment]
Your playground example does show that if the sending goroutines do a busy loop, then one or more them can starve sending a value.  I'm not sure what, if anything, we can do about that.  As you say above, it's possible to restructure the program to avoid the problem.  Other than that, it's usually a good idea for a single processor to keep running the same set of goroutines, and it's usually a good idea to start the goroutine receiving from a channel when a channel is full (though I'm not sure the current scheduler actually does this).  For an example like your playground example, it's possible for the sending and receiving goroutine to be on the same processor, and for that processor to keep flipping back and forth and, apparently, to tie up the channel sufficiently that no other goroutine gets in.  But anything we do to change that will tend to slow down the scheduler and may penalize other programs.  It's not obvious to me that we want to optimize for the case of multiple goroutines sending to the same channel in a busy loop.  Of course if you have any suggestions I would like to hear them.

**Comment by johnsnow4514** [comment]
I think @rsc derscribed it best  (#11506)

> Especially since so many Go programs care about latency, making channels first come, first served seems worth doing. And it looks to me like it can be done trivially and at no performance cost. The current behavior looks more like a bug than an intended result.  

I believe that a channel should be FIFO when multiple senders are blocked.  
The first sender to get blocked should be the first to be released.

**Comment by RLH** [comment]
#11506 <https://github.com/golang/go/issues/11506> was not implemented due
to the last two comments on that issue. Neither this thread nor the
literature has added any additional performance numbers, throughput or
latency, to warrant reconsideration. On the other hand the conjecture that
other schedules can be built on top of drive-by/barging has been confirmed
with the simple code provided above.

**Comment by ianlancetaylor** [comment]
As far as I can tell there is nothing to do here.  Please comment if you disagree.
