### ISSUE TITLE
play.golang legal reasons

### ISSUE THREAD

**Issue by ghuser1234567** [golang/go#21186]
The play.golang.org is the worst.

Clicking on any link provided anywhere, the result is

`<h1>Unavailable For Legal Reasons</h1><p>If you believe this is in error, please <a href="https://golang.org/issue">file an issue</a>.</p>`

So i don't even get proper html or anything useful. Apparently you bulk block certain countries?

### What did you expect to see?
I expect, to be able to look at example code just like everybody else.

**Comment by mvdan** [comment]
See the many previous issues about this - like https://github.com/golang/go/issues/20193.

If your IP is not chinese, then you should ping @broady. But without more information, that is the likely case.

**Comment by ghuser1234567** [comment]
Hello @broady, I'm not in china, please help, thx

**Comment by broady** [comment]
What IP address are you on, and where are you?

Feel free to e-mail me it if you don't want to publish it here.

**Comment by ghuser1234567** [comment]
Still no change! Google thinks i am in the evil empire...

**Comment by broady** [comment]
I reported it, no response from the geolocation bug team. I'll update here when I know more.

**Comment by ghuser1234567** [comment]
Hi, any news on this? It is really hampering my work, because I can't see any code samples, because they all are provided as a link to the playground.

**Comment by ianlancetaylor** [comment]
Is this still a problem?

**Comment by xflxfl** [comment]
@ghuser1234567 Change Your Browser's Language
