### ISSUE TITLE
i used "(?:re)" regex but found maybe it's capturing-group but as describe in package

### ISSUE THREAD

**Issue by yingqin678** [golang/go#21185]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\isource\go-workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?

Ihttps://play.golang.org/p/AgklWl8CWw

### What did you expect to see?
i want it come out to be "1234", as "|" is not capturing

### What did you see instead?
"1234|"

**Comment by bradleyfalzon** [comment]
Is this a case of needing to use a raw string instead of string literal as it appears the backslash is being escaped?

```go
regexp.Compile(`^1234(?:\\|)`)
```

Instead of:

```go
regexp.Compile("^1234(?:\\|)")
```

**Comment by yingqin678** [comment]
@bradleyfalzon yeah,it's effective;but why when i code like this "regexp.Compile(`^123(?:4)`)", it come out "1234"  ?https://play.golang.org/p/jB7FmxWz9r**

**Comment by bradleyfalzon** [comment]
In quoted string literal a `\` is used as a part of a escape sequence, a `\\` escapes this. See https://golang.org/ref/spec#String_literals (and https://golang.org/ref/spec#Rune_literals)

To see this behaviour:

```go
fmt.Println(`^1234(?:\\|)`) // outputs: ^1234(?:\\|)
fmt.Println("^1234(?:\\|)") // outputs: ^1234(?:\|)
```

You wanted the first behaviour, and therefore should use raw string.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
