### ISSUE TITLE
godoc: function docs should strip "//go:" annotations

### ISSUE THREAD

**Issue by gaal** [golang/go#21193]
The docs here do not strip the "go:nosplit" annotation present on (the tip version of) a function, resulting in awkward docspam:
https://tip.golang.org/pkg/runtime/#Gosched

I haven't had a chance to check if this bug is present in 1.8 (the 1.8 version of Gosched doesn't happen to have a //go:nosplit annotation)

**Comment by ianlancetaylor** [comment]
In cases where this is a problem, the go:nosplit or other annotations can be moved to a comment before the doc comment.  I don't think any godoc change is necessary.

**Comment by kevinburke** [comment]
@ianlancetaylor can you clarify? Something like this?

```go
// go:nosplit

// Gosched ...
func Gosched() { ... }
```

**Comment by ianlancetaylor** [comment]
@kevinburke Yes.  (But see also the comments in #22022.)

**Comment by ianlancetaylor** [comment]
Nothing to do.
