### ISSUE TITLE
Result assertion should be nil, while get a nonexist  value from map[string]*<struct type>

### ISSUE THREAD

**Issue by xtudouh** [golang/go#21198]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="linux"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/eSymnOiMNN

### What did you expect to see?
<nil> true

### What did you see instead?
<nil> false

**Comment by dominikh** [comment]
This is working as intended. Please see the associated FAQ entry at https://golang.org/doc/faq#nil_error (don't be misled by its reference to errors, the same applies to any typed nils in interfaces)
