### ISSUE TITLE
x/build/cmd/builder: delete

### ISSUE THREAD

**Issue by bradfitz** [golang/go#21191]
We have very few users of the old-style builder left:

https://github.com/golang/go/wiki/DashboardBuilders#old-style-builders

Of the ones I see running, to migrate we have:

- [X] plan9-386-ducolombier (@0intro)
- [X] plan9-amd64-9front (@0intro)
- [x] plan9-arm (@0intro)
- [x] ~nacl-arm-cheney (@davecheney)~ no longer running
- [X] dragonfly-amd64 (@fupjack)
- [X] freebsd-arm-paulzhol (@paulzhol)

If we can migrate those few users to `cmd/buildlet` instead we can then delete `x/build/cmd/builder`.

**Comment by 0intro** [comment]
There is also:

plan9-arm (@0intro)

plan9-386-ducolombier is a temporary builder. It will go away once GCE is fixed.

**Comment by bradfitz** [comment]
David, can you start migrating at least plan9-arm and plan9-amd64-9front to the new system? I can get you new host keys and send you a CL for the dashboard/builders.go CL if so.

**Comment by cybrcodr** [comment]
How does one migrate from old-style builder to using the buildlet?  Are these the instructions ...

https://github.com/golang/go/wiki/DashboardBuilders#how-to-set-up-a-builder

Is the key (.gobuildkey) used for initial buildlet run only or is it permanent for all future runs?

Step 6.  Have golang-dev deploy it. -- does "it" here pertain to dashboard or do we also need to redeploy coordinator and others?

**Comment by bradfitz** [comment]
Yes, those are the instructions.

The build key is required whenever the buildlet wants to register itself with the coordinator, which happens once per run, or whenever one of them restarts.

**Comment by bradfitz** [comment]
> Step 6. Have golang-dev deploy it. -- does "it" here pertain to dashboard or do we also need to redeploy coordinator and others?

Only the coordinator. The dashboard doesn't need updates currently. If #19930 gets fixed, though, then restarting the dashboard would be nice but not required.

**Comment by paulzhol** [comment]
@bradfitz how do I 
> get a builder host type & hash

Is the `builder=freebsd-arm` query param to the https://build-dot-golang-org.appspot.com/key endpoint supposed to work for with my gmail account?
What should I do with my current hash in `.gobuildkey` file?

**Comment by bradfitz** [comment]
@paulzhol, email me (bradfitz golang) and I'll get you keys.

**Comment by bradfitz** [comment]
Actually, I might have a new plan. I think I can just modify the buildlet a bit to work with your existing files & keys unmodified. That'd be easier for everybody.

**Comment by paulzhol** [comment]
Great! I'll take the opportunity to upgrade to FreeBSD-11.1 while waiting for the new buildlet.

**Comment by tdfbsd** [comment]
I think I have succeeded in switching dragonflybsd to the new builder. Note that that fupjack has not maintained the builder for some time now, so please update your list.

**Comment by bradfitz** [comment]
@tdfbsd, I see "dragonfly-amd64" connected now, thanks. But it won't get any work without some config on our side.

Are you running it in a loop so it'll re-run on process exit? (ideally in a container with a fresh filesystem)

Also, are you the new owner of that builder? Thanks!

**Comment by tdfbsd** [comment]
I've been running it for a year now. I can run it in a loop if that's the preferred way. I don't know what "container with a fresh filesystem" means.

**Comment by paulzhol** [comment]
@bradfitz can you see `freebsd-arm-paulzhol` as well? I'm running buildlet with the following parameters:
`-coordinator farmer.golang.org -halt=false -reverse-type freebsd-arm-paulzhol`

```
2017/08/05 20:51:04 buildlet starting.
2017/08/05 20:51:04 Not on GCE; not remounting root filesystem.
2017/08/05 20:51:04 Dialing coordinator farmer.golang.org:443 ...
2017/08/05 20:51:05 Doing TLS handshake with coordinator (verifying hostname "farmer.golang.org")...
2017/08/05 20:51:05 Registering reverse mode with coordinator...
2017/08/05 20:51:05 Connected to coordinator; reverse dialing active
```
Not building anything though.

**Comment by bradfitz** [comment]
@tdfbsd, where is your GOROOT_BOOTSTRAP directory? With the new system, that's set on our side. (The new system didn't really consider 1-off builders in its design, but I suppose we could make some changes to make this easier if it becomes tedious.)

And yes, you'll need to run the loop yourself. After each build, the buildlet process will terminate. (Or it will halt the machine by default, unless `--halt=false` is given.)

By fresh filesystem I mean that ideally each build would run in a hermetic environment so any changes it makes are undone when the process ends and starts anew. Whether that's something like a Docker container or an overflay filesystem or a VM varies by builder. Some of our builders don't do that, and that's okay. For the most part it tries to be well-behaved. The fresh-filesystem-per-build is just paranoia.

@paulzhol, same question about where your GOROOT_BOOTSTRAP is. But I see freebsd-arm-paulzhol connected.

**Comment by paulzhol** [comment]
@bradfitz I haven't set it to anything, so it defaults to `$HOME/go1.4` I think. 
What about other environment variables, the old builder had `GOARM=7 CGO_ENABLED=1 GO_TEST_TIMEOUT_SCALE=32`. Will they be inherited by the buildlet process?

**Comment by bradfitz** [comment]
Actually, I was wrong. The environment of commands executed under the buildlet includes (unless overridden) all of its initial environment.

**Comment by bradfitz** [comment]
Okay, the three remaining are:

plan9-arm (@0intro)
plan9-amd64-9front (@0intro)
nacl-arm-cheney (@davecheney)

@0intro, can you kill the plan9-amd64 builder? That is #19388. And I've mailed you a host key for migrating plan9-arm.

@davecheney, that leaves your nacl-arm builder as the last cmd/builder user to migrate.

**Comment by 0intro** [comment]
The plan9-arm-0intro buildlet is now running.

**Comment by 0intro** [comment]
The plan9-amd64-0intro buildlet is now running.

**Comment by bradfitz** [comment]
And I've now restarted the coordinator at https://github.com/golang/build/commit/2446fb35d2c9f18c3a32584f2fc8865112bbf98b

**Comment by dmitshur** [comment]
Based on https://github.com/golang/go/issues/21191#issuecomment-320476321, [CL 53417](https://golang.org/cl/53417), and https://github.com/golang/go/issues/21191#issuecomment-320517229, it sounds like all the 3 remaining old-style builders have been migrated. Is that so? Is anything left to be able to remove `cmd/builder` and close this issue?

**Comment by 0intro** [comment]
Yes, the plan9-amd64 and plan9-arm builders are not using `cmd/builder` anymore.

**Comment by dmitshur** [comment]
Thanks @0intro.

@davecheney Can you please update me on status of the `nacl-arm-cheney` builder? Based on [CL 53417](https://golang.org/cl/53417), it looks like it should be migrated. However, on https://farmer.golang.org/, I see:

```
host-nacl-arm-davecheney: 0/0 (1 missing)
```

So it's not connected right now.

**Comment by davecheney** [comment]
It’s no longer running , sorry.

**Comment by andybons** [comment]
Updated the checklist. Looks like we can move forward.

**Comment by dmitshur** [comment]
I followed up by [removing the old-style builder section](https://github.com/golang/go/wiki/DashboardBuilders/_compare/5134752ac102b78d09b5a3cd2d00dd7531421a08...fc308971ff06504290f34bc6d58bae59fe613380) from the DashboardBuilders wiki page.

**Comment by bsiegert** [comment]
It turns out the `netbsd-arm-bsiegert` builder is still running the old `builder` command. I was not aware of this issue when I set it up in March 2018.

**Comment by dmitshur** [comment]
It looks like we missed the `openbsd-arm` builder in this issue. /cc @4a6f656c @bradfitz @bcmills

It was mentioned in the now-deleted "Old-style builders" section of [golang.org/wiki/DashboardBuilders](https://github.com/golang/go/wiki/DashboardBuilders/_compare/5134752ac102b78d09b5a3cd2d00dd7531421a08...fc308971ff06504290f34bc6d58bae59fe613380).

@4a6f656c, are you interested in migrating the `openbsd-arm` builder to use `cmd/buildlet` (the general process is described [here](https://golang.org/wiki/DashboardBuilders#how-to-set-up-a-builder))?
