### ISSUE TITLE
x/tools/cmd/getgo: warn if user already have a Go installation

### ISSUE THREAD

**Issue by rakyll** [golang/go#21217]
```
$ getgo
Welcome to the Go installer!
Downloading Go version go1.8.3 to /Users/jbd/.go
This may take a bit of time...
Downloaded!
Setting up GOPATH

One more thing! Run `source /Users/jbd/.zshrc` to persist the
new environment variables to your current session, or open a
new shell prompt.
```

Then when I do a `which go` in a new shell, it points to the earlier installation. We should probably warn the user if there is already a Go installation available (at a different location) on the system and recommend user to remove it before proceeding.

/cc @broady

**Comment by ZekeLu** [comment]
https://go-review.googlesource.com/51930 has been merged and I think this issue can be closed. (the referenced issue in the Fixes line is `Fixes #21217`).
