### ISSUE TITLE
cmd/go/pkg.go: `func disallowInternal` does not permit import from code rooted **below** the parent of the “internal” directory.

### ISSUE THREAD

**Issue by GoLangsam** [golang/go#21215]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
windows_386

### What did you do?
My [test prog](https://github.com/golangsam/internal/blob/master/cmd/dotpath/main.go) is in package
- "github.com/golangsam/internal/cmd/dotpath"
and (tries to) import
- "github.com/golangsam/internal/container/ccsafe/dotpath"

The parent of the "internal" directory at "github.com/golangsam" and common to both.
Note: the importing prog / package is **not** rooted outside the tree rooted at github.com/golangsam"

Another [prog](https://github.com/golangsam/dotgo/blob/master/cmd/dotgo/dotgo.go) is in package
- "github.com/golangsam/dotgo/cmd/dotgo"
and (tries to) import
- "github.com/golangsam/dotgo/internal/dottmpl"

The parent of the "internal" directory at "github.com/golangsam/dotgo" and common to both.
Note: The importing prog / package is **not** rooted outside the tree rooted at "github.com/golangsam"

### What did you expect to see?
no error, as the importing package is **not** outside the tree rooted at the parent of the “internal” directory."

### What did you see instead?
error "use of internal package not allowed" - see build results @ [Travis-CI](https://travis-ci.org/GoLangsam/internal) and [here](https://travis-ci.org/GoLangsam/dotgo) 

---
The error seems to originate in `cmd/go/pkg.go` @ `func disallowInternal` - lines 566 ff, where it says:

	// [golang.org/s/go14internal]():
	// An import of a path containing the element “internal”
	// is disallowed if the importing code is outside the tree
	// rooted at the parent of the “internal” directory.

Looking at [golang.org/s/go14internal](https://golang.org/s/go14internal) by @rsc 
(or [here](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit)) I see:

- "Update, September 2015: Go 1.5 expanded internal to GOPATH as well."

and the conceptual definition:

- "An import of a path containing the element “internal” is disallowed if the importing code is outside the tree rooted at the parent of the “internal” directory."

and a slightly more restrictive wording in the examples:
- "$GOPATH/src/mypkg/internal/foo can be imported only by code in $GOPATH/src/mypkg"

where the **only** seems to exclude e.g. `$GOPATH/src/mypkg/cmd/mycommand`
But it's just an example, and e.g. `$GOPATH/src/mypkg/cmd/mycommand` is definitivly **not** "outside the tree rooted at the parent of the “internal” directory"

And - long before I found that one, I learned e.g. from [here](https://github.com/campoy/go-tooling-workshop/blob/master/1-source-code/1-workspace/2-tooling.md#the-internal-directory): "The packages inside of an `internal` directory are only accessible to those packages that are siblings of that internal package or are contained by one of those siblings."

Please advise.

And please don't tell me that I should delete my [`internal` repo](https://github.com/GoLangsam/internal/blob/master/README.md) - look [here](https://github.com/GoLangsam/internal/blob/master/Daryl.md) first ;-)
and help me to make the magic happen :-)

**Comment by GoLangsam** [comment]
Afternote: Originally, I checked for open issues only. Now I see some old closed issues related to this phenomenon. e.g.
- [#10479](https://github.com/golang/go/issues/10479) - "cmd/go: apply internal restriction outside $GOROOT" by @rsc
- [#11055](https://github.com/golang/go/issues/11055) - "cmd/go: internal imports fail across repo boundaries"
- [#11307](https://github.com/golang/go/issues/11307) - "cmd/go: "go get -u" handles internal imports incorrectly"
- [#11477](https://github.com/golang/go/issues/11477) - "cmd/go: internal package errors only when using `go get -u`" - Note: @bradfitz closed this as being dupe of #11307
- [#12217](https://github.com/golang/go/issues/12217) - "cmd/go: internal package is importable to the packages which is not rooted in the same subtree."

Just: they are all ("FrozenDueToAge") - and I doubt they'll help ... :-(

**Comment by GoLangsam** [comment]
Pondering about the source of `cmd/go/pkg.go` I cannot stop wondering about the line

`parent := p.Dir[:i+len(p.Dir)-len(p.ImportPath)]`

where `ì` has been adjusted to point at the end of the last node before the last "internal" of p.ImportPath.
So I'd expect `parent := p.ImportPath[:i]` would do. That must be prefix of srcDir.

The use of p.Dir instead, and then offset adjusted by diff of length of p.Dir and p.ImportPath confuses me - especially when the diff is not zero. (But I'm still easy to be confused by golang ;-) )

**Comment by GoLangsam** [comment]
And I forgot to mention: build results can be seen @ [Travis-CI](https://travis-ci.org/GoLangsam/internal) and [here](https://travis-ci.org/GoLangsam/dotgo)

**Comment by ianlancetaylor** [comment]
Looking at the repo, I suspect the problem has to do with inconsistent casing of GoLangsam.  It seems to sometimes be GoLangsam and sometimes golangsam.  Go package paths are case sensitive and in general need to be consistent, even if the underlying file system is case insensitive.

I'm going to close this, but please comment if you disagree.  It would help to point us to a repo that fails.
