### ISSUE TITLE
doc/editors: mention that Gogland can be distributed as part of Jetbrains paid IDEs

### ISSUE THREAD

**Issue by jerome-laforge** [golang/go#21213]
### What version of Go are you using (`go version`)?
n/a

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
on http://tip.golang.org/doc/editors.html, this sentence is not totally true:
```text
Gogland: Gogland is distributed either as a standalone IDE or as a plugin for the IntelliJ Platform IDEs
``` 
I prefere this one:
```text
Gogland: Gogland is distributed either as a standalone IDE or as a plugin for Intellij IDEA Ultimate and other Jetbrain paid IDEs.
```

### What did you expect to see?
n/a

### What did you see instead?
n/a

**Comment by odeke-em** [comment]
@jerome-laforge I've updated the title a little. Let me page some folks who might be concerned @spf13 @rakyll

**Comment by spf13** [comment]
@jerome-laforge your change isn't accurate. It's available for all of the IntelliJ Platform IDEs including the open source community ones. Please leave the text as it is.

**Comment by dlsniper** [comment]
@spf13 I can clarify some things here.

The plugin offering the equivalent functionality to Gogland is only available in the paid JetBrains IDEs.

The community plugin is not currently maintained and already doesn't support the latest versions of the IDEs, based on the 2017.2 Platform. The reason is simple, there are no other people willing to send PRs to make it work.

**Comment by jerome-laforge** [comment]
@spf13 you can find the origin of this defect here:
https://groups.google.com/forum/#!msg/golang-dev/KRpmMzb-hH4/k3qdQsP1AwAJ

**Comment by jerome-laforge** [comment]
> The community plugin is not currently maintained and already doesn't support the latest versions of the IDEs, based on the 2017.2 Platform. The reason is simple, there are no other people willing to send PRs to make it work.

@dlsniper even if someone else will take in charge this evolution, you can't said that Goglang supported by IntelliJ Platform IDEs. As Goglang is more featured than open source one.

**Comment by rakyll** [comment]
Can we simply say "Gogland: Gogland is distributed either as a standalone IDE or as a plugin for JetBrains Ultimate IDEs."?

Is Ultimate a shared terminology among JetBrains IDEs?

**Comment by spf13** [comment]
Thanks for the clarification. Is @rakyll 's last text accurate?

**Comment by dlsniper** [comment]
No, sorry. Ultimate is just for IDEA, the others have their own names. I'll ping someone from JetBrains for this and come back asap. Thank you.

**Comment by dlsniper** [comment]
And back with a suggestion.

> Gogland: Gogland is distributed either as a standalone IDE or as a plugin for the paid IntelliJ Platform IDEs

This should address any uncertainty about which IDEs get it or not while informing the readers about the paid part.

**Comment by ignatov** [comment]
I suppose that "Gogland: Gogland is distributed either as a standalone IDE or as a plugin for the paid IntelliJ Platform IDEs."

If you want you could add some clarification: "e.g. PyCharm, RubyMine, PhpStom, etc."
