### ISSUE TITLE
`go install` report GOBIN not set

### ISSUE THREAD

**Issue by beary** [golang/go#21212]
### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/beary/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/beary/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ms/ytrwlccj47j89_knrz_qxr4m0000gn/T/go-build783820727=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
I open `/User/beary/go` and run `go install demo/demo.go`. it's work well and generate a `demo` file on `/User/beary/go/bin`.

But when I run `go install github.com/golang/lint/lint.go`, the result is `go install: no install location for .go files listed on command line (GOBIN not set)`

This is my environment setting
```vim
export GOROOT="/usr/local/go"
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOROOT/bin:$GOBIN"
```
My os is macOS Sierra 10.12.6

**Comment by cznic** [comment]
> But when I run go install github.com/golang/lint/lint.go, the result is go install: no install location for .go files listed on command line (GOBIN not set)

That's expected. The correct command is `go install github.com/golang/lint/golint`, ie. an import path, not a file path.

**Comment by beary** [comment]
@cznic Thank you!
