### ISSUE TITLE
net/rpc: possible mistake in comment

### ISSUE THREAD

**Issue by by-zhang** [golang/go#21239]
In  line 303  of  the file net/rpc/server.go, the comment is inconsistent with the code below.

**Comment by bradfitz** [comment]
"line 303" of what version?

**Comment by bradfitz** [comment]
There is no comment on line 303 of Go 1.8.x.

So I guess you mean master (currently 623e2c4603053c8e2ecf4cd7ed5f8242a7a02226).

Here's a useful link:

https://github.com/golang/go/blob/623e2c4603053c8e2ecf4cd7ed5f8242a7a02226/src/net/rpc/server.go#L303

**Comment by by-zhang** [comment]
sry, I'm now little experienced with github. And you did the right job.

**Comment by enrichman** [comment]
I'm not sure if I had to claim the issue, but since it was a really small fix I submitted it: https://go-review.googlesource.com/c/53750 :)

**Comment by ianlancetaylor** [comment]
As noted on the CL, I think the comment is actually correct.  The comment is not inconsistent with the code, it is meant to be read with the later comment.

I'm going to close this since I don't think there is a problem here.  Please reply if you disagree.
