### ISSUE TITLE
net: DialContextTCP()

### ISSUE THREAD

**Issue by gobwas** [golang/go#21231]
Hello! I've search for some similar issues and found [this one](https://github.com/golang/go/issues/3097) but looks like it is stale now.

My issue points to inability to dial via tcp with custom `context.Context` passed.

[Current implementation](https://github.com/golang/go/blob/bf4cd98c8b5b61f53b98333564f343ec54386acd/src/net/tcpsock_posix.go#L54-L59) of `net.DialTCP()` (actually `net.dialTCP`) is absolutely ready to receive context for dial, but has no exported wrapper that can receive it.

**Comment by fraenkel** [comment]
Did you miss https://golang.org/pkg/net/#Dialer.DialContext ?

**Comment by gobwas** [comment]
@fraenkel no. 

```go
conn, err := dialer.DialContext(...)
```

Does not allow me to setup local address for connection.

**Comment by fraenkel** [comment]
Sure it can. Set the LocalAddress in the Dialer.

**Comment by gobwas** [comment]
@fraenkel wow. Thanks! Seems like I really missed this. 👍 
By the way, should the `net.DialContextTCP()` appear?

**Comment by fraenkel** [comment]
I don't think so. We just need to adequately highlight the proper APIs that people should use. The original ones were modified to leverage the Context based ones but cannot be removed for compatibility reasons.

**Comment by ianlancetaylor** [comment]
Closing since there doesn't seem to be anything to do here.
