### ISSUE TITLE
x/tools/cmd/godoc: /cl/XXXX redirecting to go-review.googlesource.com/r/XXXX

### ISSUE THREAD

**Issue by andybons** [golang/go#21235]
It should be redirecting to go-review.googlesource.com/XXXX

**Comment by bradfitz** [comment]
Gerrit changes its URLs every few months. Is there really a canonical one? I thought they all redirected anyway.

(Actually curious.)

**Comment by andybons** [comment]
I never actually knew about `/r/NNNN`. All I knew of is `/NNNN` and `/c/NNNN`. I’ll ask.

**Comment by andybons** [comment]
No urls should have stopped working. Filed a bug with the team. In the meantime I’ll change it to /NNNN so that things work again.

**Comment by andybons** [comment]
This actually is a PolyGerrit bug: https://bugs.chromium.org/p/gerrit/issues/detail?id=6888

**Comment by broady** [comment]
Deployed
