### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ldynia** [golang/go#21233]
I found annoying error handling in go. Namely, when you read below code you have to vocalize it to `if error not nil then` -which translates to `if there is an error then`.
```GO
if err != nil {
    // handle error
}
```
I would like to have abbility of expresing above code in such way -which in my opinion is more readable.
```GO
if err {
    // handle error
}
```
Just my humble suggestion :)

**Comment by ALTree** [comment]
Thanks for the report. 

Language support of more ergonomic error handling is the topic of issue #21161 (there are already a few ideas posted); let's keep all the discussion about this in that thread.

Closing this as a dup of #21161.
