### ISSUE TITLE
database/sql: add documentation about Context methods

### ISSUE THREAD

**Issue by carl-mastrangelo** [golang/go#21244]
### What version of Go are you using (`go version`)?
Go 1.9

### What did you expect to see?
Documentation about Context propagation for the new database context methods.   For example, it isn't clear what happens in the following cases:

* Does   `DB.BeginTx`  result in a `Tx` that has a context, or is the context only applied to the creation of the Tx?  
*  Does `DB.PrepareContext` result in a `Stmt` that uses the passed in context?  Phrased differently: does calling `stmt.Exec()`  use the context passed to  `DB.PrepareContext` ?
* Similar to the above question, does `Stmt.QueryContext` use the context that was used to create it?
* Does `Tx.Prepare` use the context that was used to create it?  (

Reading the code clarifies that context is usually not passed around, but this isn't obvious from the docs.  Furthermore, this does not make it clear if this is an implementation detail, or a part of the API.   
Ideally, The database docs could include something along the lines of:

```
func (s *Stmt) Exec(args ... interface{}) (Result, error)

This is equivalent to

func (s *Stmt) ExecContext(context.Background(), args ...) (Result, error)
```

**Comment by odeke-em** [comment]
@carl-mastrangelo thanks for the issue report, I am going to mark this for Go1.10 since it seems too late for Go1.9
/cc @kardianos

**Comment by kardianos** [comment]
@carl-mastrangelo This would be for go1.10.

We may be able to clarify these points, but I'm fairly certain that the documentation does in fact state all of these facts. Are you able to suggest better wording to clarify these details?

**Comment by kardianos** [comment]
No clarification has been provided. Closing.
