### ISSUE TITLE
website: missing version 1.8 in release notes list on /project

### ISSUE THREAD

**Issue by buchanae** [golang/go#21245]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
N/A

### What operating system and processor architecture are you using (`go env`)?
N/A (website)

### What did you do?

Go here: https://golang.org/project/

### What did you expect to see?

Go 1.8 in the bulleted list in "Release History"

### What did you see instead?

Go 1.8 is missing

**Comment by bradfitz** [comment]
Wow, thanks for noticing that.

@broady, can you fix, and add Go 1.9 too?

**Comment by broady** [comment]
Weird. It's here:
https://go.googlesource.com/go/+/release-branch.go1.8/doc/contrib.html#37

I'm really confused. The site deploys from HEAD on the 1.8 release branch, and I only just deployed the site today, so it should be up-to-date.

**Comment by broady** [comment]
I screwed up. I erroneously thought that the workspace I deployed the website from today was clean and at HEAD, but it was actually old and for 1.7.

So, I'd released the site at release-branch.go1.7. It's been like that for about 12 hours.

Not good. Some tooling to prevent mistakes like this in the future is probably wise.

**Comment by broady** [comment]
It's back.

https://golang.org/project/
