### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by trusktr** [golang/go#21242]
NPM uses it for packages. Go needs something like it.

http://semver.org

Related: https://github.com/golang/go/issues/13700

**Comment by bradfitz** [comment]
I don't think this bug adds anything substantial or unique over #13700. Let's just use #13700.

**Comment by trusktr** [comment]
Yes, it bumps the priority 7,542 posts later. That's quite significant! ;) It would be sweet though.

**Comment by ALTree** [comment]
@trusktr dependency management for Go is work-in-progress here: https://github.com/golang/dep (still experimental), and yes, it uses semver. Merging the tool into the toolchain is on the roadmap (possibly), but first it needs to be completed.
