### ISSUE TITLE
x/tools/cmd/getgo: Create a page for get.golang.org

### ISSUE THREAD

**Issue by spf13** [golang/go#21259]
We need to create a web page to live at get.golang.org that has directions on installing go via the one line installer. 

It would also be good to have additional directions on obtaining and using the installer as it does more than just the one-liner installation.

**Comment by olingern** [comment]
@spf13 I'd like to help. A couple of questions:
1. Where do you see this living in the repo?
2. Should it pull in the existing golang.org template / styling?

**Comment by spf13** [comment]
Cc @broady

**Comment by spf13** [comment]
I'm fine with it having a one pager style instead (see http://vim.spf13.com
for an example of what I'm talking about). No need to overthink it though.
Whatever is easiest and effective is good.

**Comment by broady** [comment]
Should live under cmd/getgo/server (a separate file). No need for templating it, but I'm OK if you hotlink the CSS from golang.org.

**Comment by olingern** [comment]
@broady @spf13 Got it. I'll get started on a rough draft, and open a PR.for something basic to go under `cmd/getgo/server`

**Comment by SCKelemen** [comment]
@olingern Are you still working on this? Please let me know if you need help.

**Comment by psampaz** [comment]
@spf13 this is tagged as abandoned here https://golang.org/cl/115775. Is it really abandoned?
It seems very useful especially combined with Go modules.

**Comment by hyangah** [comment]
Closing - `getgo` is deprecated.  #60951
