### ISSUE TITLE
net/mail: ParseAddress ignore comment in parentheses after email address

### ISSUE THREAD

**Issue by minaevmike** [golang/go#21257]
### What version of Go are you using (`go version`)?
`go version go1.8.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/prog/GO"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build728818306=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

https://play.golang.org/p/3OTryRCHf8
### What did you expect to see?

`mark@cbosgd.ATT.COM` as parsed email
### What did you see instead?

error with `mail: expected single address, got "(Mark Horton)"`

at [rfc 5322](https://www.ietf.org/rfc/rfc5322.txt) 
` mailbox         =   name-addr / addr-spec`
`name-addr       =   [display-name] angle-addr`
` angle-addr      =   [CFWS] "<" addr-spec ">" [CFWS] /obs-angle-addr`
`CFWS            =   (1*([FWS] comment) [FWS]) / FWS)`
so `CFWS` can contian comment in parentheses and i think that it must be ingored

**Comment by smasher164** [comment]
RFC 5322 also mentions under section 3.2.2 that "comments may nest," and that "there are several places in this specification where comments and FWS may be freely inserted." Implementing this feature would probably require implementing folding white space (FWS). Please specify

1. The level of nesting needed, or whether fully nested comments are required.
2. The parts of `angle-addr` that need comments. Looking under section 3.4.1, `addr-spec` also allows comments.
```
addr-spec       =   local-part "@" domain
local-part      =   dot-atom / quoted-string / obs-local-part
domain          =   dot-atom / domain-literal / obs-domain
domain-literal  =   [CFWS] "[" *([FWS] dtext) [FWS] "]" [CFWS]
```
3. The usage and importance of having comments in an email address. Email addresses are often parsed from network requests, and inefficient parsing could be insecure. Sources of inefficiency include the indefinite nesting, dealing with escape characters inside the comments, and interpreting multiple runs of whitespace as a single character.

**Comment by minaevmike** [comment]
I am not sure that i understand correclty but all spaces already ignored https://github.com/golang/go/blob/master/src/net/mail/message.go#L272 .
Also i should notice that documentation give wrong information https://golang.org/src/net/mail/message.go#L147 because this parser not full rfc5322 compatiable.
As for me one of possible decision of this problem is to add function that will skip this comments, if i understand corretly after `skipSpace` we should skip data between `(` and `)`. It's not very inefficient.
I use this fucntions to parse email addresses from emails and some MTA form addresses like that because it's consistent with rfc.

**Comment by smasher164** [comment]
>  but all spaces already ignored 

Whitespace is currently not folded (consuming runs of carriage returns and newlines), but I suppose single-line comments are enough.

> Also i should notice that documentation give wrong information https://golang.org/src/net/mail/message.go#L147 because this parser not full rfc5322 compatible.


Nowhere does the parser say that ParseAddress is fully RFC 5322 compliant. In fact it explictly documents otherwise, notably [L287: Groups](https://github.com/golang/go/blob/master/src/net/mail/message.go#L287), [L221: FWS](https://github.com/golang/go/blob/master/src/net/mail/message.go#L221), and [L376: domain-literal](https://github.com/golang/go/blob/master/src/net/mail/message.go#L376).

> after skipSpace we should skip data between ( and )

Assuming that the level of nesting is bounded, and that comments are allowed before and after the address, this sounds like a reasonable request. Though in practice, I don't think more than one level is necessary.

**Comment by minaevmike** [comment]
Hi.
I create review about 1.5 month ago and nobody watch it.
What should I do to be seen by someone?

**Comment by ianlancetaylor** [comment]
You sent the CL during the freeze, sorry.  We will eventually sweep it up, but pinging, as you just did, is a good idea too.  Sorry for the delay.
