### ISSUE TITLE
net/http/httputil: httputil.ReverseProxy does not call ModifyResponse on failed requests

### ISSUE THREAD

**Issue by sebsprenger** [golang/go#21255]
### What version of Go are you using (`go version`)?
```go version go1.8.3 darwin/amd64```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sprengers/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/71/lrpk1tm559gbz8rbgym9nwbw0000gp/T/go-build165819743=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
I setup a `httputils.ReverseProxy` with a `ModifyResponse` method:
https://play.golang.org/p/U7R9-oxBfq

### What did you expect to see?
I expected that the `EYE-CATCHER ON RESPONSE` log entry would appear when calling `/invalid` as well.

### What did you see instead?
The `EYE-CATCHER ON RESPONSE` log entry only came up on `/google` but not on `/invalid`.

Looking at the code of `httputil.ReverseProxy`: If there is a proxy error then `ServeHTTP` immediately returns without applying `ModifyResponse`:
https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L202

`ModifyResponse` is only applied in the good case:
https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L222

**Comment by smasher164** [comment]
```
res, err := transport.RoundTrip(outreq)
merr := p.ModifyResponse(res)
```
which one should be logged? merr, err, or both?

**Comment by sierraechobravo** [comment]
There is the `Director` to modify the *input* request and there is `ModifyResponse` to modify the *output* response.  IMHO `ModifyResponse` ought to be ultimately responsible, because otherwise what's the point?

It would be good though, if `ModifyResponse` had access to some sort of feedback from the actual proxy to take that into consideration (e.g. error as argument).

**Comment by smasher164** [comment]
> to take that into consideration (e.g. error as argument).

The api for `ModifyResponse` can't change, so a simpler solution might be to just log the other error before checking this one.
However it would have to be `ModifyResponse`'s responsibility to return an error for a nil `*http.Response`.

If no one minds, I can submit a CL for this. /cc @bradfitz

**Comment by smasher164** [comment]
Any update on this CL? /cc @mvdan
