### ISSUE TITLE
website: https://tip.golang.org returns TLS alert{fatal, certificate_unknown}

### ISSUE THREAD

**Issue by mikioh** [golang/go#21251]
Not sure when it started, right now a TLS handshake to tip.golang.org, which means SNI=tip.golang.org, fails caused by TLS alert{fatal, certificate_unknown}.

**Comment by davecheney** [comment]
Confirmed using curl

lucky(~) % curl -v https://tip.golang.org/ >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0*   Trying 130.211.180.236...
* Connected to tip.golang.org (130.211.180.236) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--
  0
* Closing connection 0
curl: (60) server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

However chrome doesn't have a problem with the cert.

**Comment by smasher164** [comment]
Chrome shows that the cert expired Monday, July 31, 2017 at 8:36:00 PM Eastern Daylight Time under devtools->Security->View Certificate.

![image](https://user-images.githubusercontent.com/12636891/28809401-39988282-7651-11e7-8684-e5411cc1f7a1.png)

**Comment by davecheney** [comment]
[ insert dramatic chipmonk ]

**Comment by bradfitz** [comment]
Well, that's interesting.

@x1ddos, any known issues with golang.org/x/crypto/acme/autocert not auto-cert-ing?

**Comment by smasher164** [comment]
In #20035, expired/invalid certs were never renewed, and https://github.com/golang/crypto/commit/0e4becf93e416602ac28708cc8fab681fe79fdc7 fixed this by treating invalid entries as nonexistent.

upspin/upspin#367 is faced this issue but closed it b/c upstream was closed.

**Comment by bradfitz** [comment]
@smasher164, thanks. That's probably what we just hit.

**Comment by x1ddos** [comment]
@bradfitz sorry, I'm late but yeah, what @smasher164 said is probably it. I should've reminded you.

Do you guys have an email in autocert config, registered with Let's Encrypt? I found it useful, some sort of a warning. If you get an email, something went wrong and the cert wasn't renewed in due time.

upspin should be fine - they've rebuilt their binaries after that commit.
