### ISSUE TITLE
cmd/compile: detect and optimize slice-extending idiom append(a, make([]T, n)...)

### ISSUE THREAD

**Issue by faiface** [golang/go#21266]
Hi!

In [Slice tricks](https://github.com/golang/go/wiki/SliceTricks) we read that in order to extend a slice by `j` new elements, we should do this:

```go
a = append(a, make([]T, j)...)
```

As far as I know, this is the only one-liner way to do it anyway. However, this code most likely does more than required, because this is usually faster:

```go
for i := 0; i < j; i++ {
    a = append(a, 0)
}
```

It's obvious that in the former code, allocating the `make([]T, j)` slice is not required. As this is an often and useful pattern, I suggest this construct should be specially optimized by the compiler, so that no extra allocations are required.

Thanks,

Michal Štrba

**Comment by randall77** [comment]
Seems reasonable if we can detect it easily.

**Comment by faiface** [comment]
Detection can be very easy, just look for anything that matches `append(a, make([]T, n)...)` for any `a` and any `n` and that's it.

**Comment by dsnet** [comment]
@faiface, if you believe it's a very easy fix, perhaps you would be willing to make the change and contribute a fix?

**Comment by josharian** [comment]
cc @martisch

**Comment by martisch** [comment]
I was already looking at some other growslice performance optimizations for go1.10 and have worked on that code in the past. While at it i would be happy to have a go at this if faiface does not have preference to contribute a CL for it himself?

It might turn out not be as very easy as it first looks - we first need to investigate if the information that appends second argument is a make(...) is still directly present once the frontend/ssa backend gets to the part where it inserts the growslice runtime call. If that info has already been obstructed by ordering and evaluating arguments we might need to insert some detection code for it earlier.

**Comment by faiface** [comment]
@dsnet @martisch I'll be happy to leave this to someone more experienced in the Go compiler. If needed, I can try and implement it, but it will probably take unreasonably long, since I've never worked with the Go compiler source before and there might be unexpected troubles as mentioned by @martisch. So, if anyone wants to have a go, my preference is to leave it to them ;)

**Comment by josharian** [comment]
@martisch the easiest place to implement this is probably walk. I’ll volunteer to review. And please let me know if this falls off your list and I’ll pick it up.

**Comment by bradfitz** [comment]
More discussion and example benchmarks in #23906

**Comment by martisch** [comment]
yes, was just today looking at teaching the order pass not to mess with node structure when its needed to detect the pattern in walk later for this and another cl. Should have a cl sometime next week for you to review.
