### ISSUE TITLE
x/build/gerrit: Add TimeStamp.MarshalJSON

### ISSUE THREAD

**Issue by lann** [golang/go#21261]
I have a patch to add build/gerrit.TimeStamp.MarshalJSON, mirroring TimeStamp.UnmarshalJSON. This is the only change I have found necessary to support building a mock gerrit server for testing. I am aware that the API is generally unstable and am vendoring appropriately, but it would be convenient to upstream this change.

**Comment by bradfitz** [comment]
Sure.
