### ISSUE TITLE
cilogon.org should be added to the list of broken auth header oauth2 providers

### ISSUE THREAD

**Issue by dimm0** [golang/go#21265]
### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
Used oauth2 library to authenticate against CILogon.org oauth2 OIDC

### What did you expect to see?
Authenticate successfully by sending client_id and client_secret in the request fields

### What did you see instead?
The fields were not sent, cilogon complained.

Pull request: https://github.com/golang/oauth2/pull/243

**Comment by dimm0** [comment]
Oops, it probably should be in oauth2 project

**Comment by mikioh** [comment]
Yup, please open an issue via https://github.com/golang/oauth2/issues.
