### ISSUE TITLE
crypto/cipher: use SIMD to improve xor performance

### ISSUE THREAD

**Issue by templexxx** [golang/go#21269]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.8
### What operating system and processor architecture are you using (`go env`)?
arch=amd64
os=darwin

### What did you expect to see?

SIMD ( SSE2 SSSE3 or AVX2) will help xor's performance a lot.

I think I can make it

**Comment by FiloSottile** [comment]
Hi @templexxx, thanks for offering to make this.

I'll be happy to review a [CL](https://golang.org/doc/contribute.html). Performance changes usually come with a [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat).

You might want to have a look at #20967, too.

**Comment by ALTree** [comment]
Implemented in 5168fcf63f5001b38f9ac64ce5c5e3c2d397363d. Closing here.
