### ISSUE TITLE
x/tools/cmd/getgo: Various comments on shell assumptions

### ISSUE THREAD

**Issue by RalphCorderoy** [golang/go#21274]
From browsing the source it uses the expansion of $HOME, but doesn't escape the value.

    line := fmt.Sprintf("export %s=%s", strings.ToUpper(name), value)

It appends to .bash_profile, but bash will read .profile if .bash_profile doesn't exist, and some bash users do that so they've one file read by different shells.  Actually, bash uses the first of these it finds: .bash_profile, .bash_login, .profile, so it might be .bash_login that needs modifying.

zsh reads from .zprofile, but zshConfig is .zshrc;  that's for interactive shells, akin to .bashrc, and the wrong place.

Speaking of different shells, `FOO=bar; export FOO' doesn't do any harm.

I don't see why that function uppercases name each time it's used?

> curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x 
> go_installer && ./go_installer && rm go_installer

When presenting this, you might want to consider wrapping it to multiple physical lines so it doesn't break awkwardly, is more readable, and users paste in the break at a harmful place.  No backslashes are required.

    curl -LO https://get.golang.org/$(uname)/go_installer &&
    chmod +x go_installer &&
    ./go_installer &&
    rm go_installer

Re-running go_installer upgrades go, so I might like to keep it around?  It's going to stay anyway if it fails.

**Comment by hyangah** [comment]
Closing - `getgo` is deprecated.  #60951
