### ISSUE TITLE
x/tools/cmd/getgo: error "go: cannot find GOROOT directory: /usr/local/go"

### ISSUE THREAD

**Issue by Deleplace** [golang/go#21271]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

none

### What operating system and processor architecture are you using (`go env`)?

(no go env)
Linux SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64

### What did you do?

Created a new small GCE instance (1 vcpu, 4GB memory)
Opened SSH access
Copy-pasted and executed the one-liner go installer : 
```
curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x go_installer && ./go_inst
aller && rm go_installer
```
And then
```
go version
```

### What did you expect to see?

Some recent go1.8.3 version number

### What did you see instead?

```
go: cannot find GOROOT directory: /usr/local/go
```

Same error message for `go doc fmt` or `go get github.com/gorilla/mux`.
See [this gist](https://gist.github.com/Deleplace/bfaff085b813cd8c602a253ca45e46ac) for complete terminal trace.

**Comment by seankhliao** [comment]
[https://golang.org/doc/install#tarball_non_standard](From the docs)

Your Install as a local user (to `$HOME/.go`) counts as a custom location and as such `GOROOT` and `GOPATH` should be manually set

```
export GOROOT=$HOME/go1.X
export PATH=$PATH:$GOROOT/bin
```

**Comment by Deleplace** [comment]
Hello Sean Liao
The relevant doc is here : [cmd/getgo](https://go.googlesource.com/tools/+/master/cmd/getgo/)
With this issue I was following instructions from [this thread](https://groups.google.com/forum/#!topic/golang-nuts/ZFqZkGYX4x8)

The one-liner installer project is specifically designed "to both install Go as well as do the initial configuration of setting up the right environment variables and paths" so I don't have to do it myself.

I expect that all upcoming new issues with subject starting with "tools/cmd/getgo" (followig link given by Steven Francia) will be about this new tool and thus the official doc/install page won't apply for them.
Cheers

**Comment by Deleplace** [comment]
This seems to be fixed!
The exact same actions today give correct results:
```
$ go version
go version go1.9 linux/amd64
```
