### ISSUE TITLE
strconv: ParseUint() always returns MaxUint64 on overflow (ErrRange)

### ISSUE THREAD

**Issue by tillulen** [golang/go#21278]
The documentation for [ParseUint()](https://godoc.org/strconv#ParseUint) is terse: “ParseUint is like ParseInt but for unsigned numbers.”

The documentation for [ParseInt()](https://godoc.org/strconv#ParseInt) suggests that when the input string represents a number that is too big to fit in bitSize bits, ParseInt returns the most extreme value that still fits in bitSize bits:

> ...if the value corresponding to s cannot be represented by a signed integer of the given size, err.Err = ErrRange and the returned value is the maximum magnitude integer of the appropriate bitSize and sign.

One would expect that ParseUint behaves in a similar way and that the following call would return 255 and ErrRange:

```go
u, err := strconv.ParseUint("256", 10, 8)
fmt.Println(u, err)
```

ParseUint in Go 1.8 actually disregards the provided bitSize and always returns MaxUint64 along with ErrRange. The above prints

```18446744073709551615 strconv.ParseUint: parsing "256": value out of range```

Please find a runnable example on the [Go Play Space](https://goplay.space/#f79NXwQEDg) or the [Go Playground](https://play.golang.org/p/f79NXwQEDg).

For consistency, it’s better to fix ParseUint to match the docs and the behavior of ParseInt. For backward compatibility, it is safer to leave ParseUint as is and update its documentation.

**Comment by tillulen** [comment]
Going over the release notes of the latest Go releases, I noticed that there were quite a few fixes that could potentially break user code dependent on the incorrect behavior. So I’m in favor of fixing ParseUint, for what it’s worth.

**Comment by rsc** [comment]
The docs seem clear. Given that, let's fix the bug.

**Comment by griesemer** [comment]
Assigned to @martisch per discussion with him.
