### ISSUE TITLE
x/crypto/salsa20/salsa: confusing docs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#21279]
The docs for `XORKeyStream` say:

```go
// XORKeyStream crypts bytes from in to out using the given key and counters.
// In and out may be the same slice but otherwise should not overlap. Counter
// contains the raw salsa20 counter bytes (both nonce and block counter).
func XORKeyStream(out, in []byte, counter *[16]byte, key *[32]byte) {
```

What does this even mean: ?

> may be the same slice but otherwise should not overlap

If they're the same slice (same 3-tuple ptr/len/cap) then they by definition overlap.

Fix this and any copy/pastes of this wording we find.

**Comment by ALTree** [comment]
I think the key word is *otherwise*

> In and out may be the same slice but otherwise should not overlap.

Same slice is ok, and it that case they'll overlap (obviously), but *otherwise* they shouldn't overlap.

**Comment by bradfitz** [comment]
Huh? I don't think that helps.

**Comment by FiloSottile** [comment]
How about

> in and out must overlap entirely or not at all.

**Comment by kreichgauer** [comment]
> if in and out overlap, they must be identical

is how it's usually worded in BoringSSL

**Comment by agl** [comment]
The intent is to describe that there are only two valid situations:

1. `in` and `out` are the same slice.
1. `in` and `out` do not alias at all.

Other configurations (i.e. `in` and `out` partially overlap) may not produce the correct result. As Martin notes, we often use a slightly different wording in BoringSSL. I fear that I'm too close to the trees to have a valid judgement about what would be clearer so someone else is free to pick something and change the wording.

**Comment by FiloSottile** [comment]
Weak -1 on the BoringSSL wording, because I can see in and out having different len being useful and correct.

Not that my wording makes it clear that's OK, but at least it does not rule out.

**Comment by crvv** [comment]
Maybe
`out[0:1]` and `in[1:]` must not overlap.

I think this is accurate but a little obscure.

**Comment by FiloSottile** [comment]
We should also put that text in the `cipher.Stream.XORKeyStream` docs.

The current text probably means this, but leaves too much open to interpretation, and implementations are already more strict anyway:

> Dst and src may point to the same memory.

For the sake of breaking the bikeshed, I'm going to CL "must overlap entirely or not at all" tomorrow unless anyone objects.
