### ISSUE TITLE
x/build: flesh out READMEs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#21285]
@andybons had some ideas for improving our README.md files in https://golang.org/cl/52856

> I feel like this should be a block that one can keep within the README since it’s useful to have it automatically update, but the author should also be able to update the contents outside the block.

So, do that. And also go through each README.md and add useful content if warranted.

And/or look at @davecheney's https://github.com/davecheney/godoc2md and maybe use that too, to put more of the package doc into the Markdown. I was only able to get the synopsis easily, but it'd be nice to have the whole package comment.

(I don't need to see the API, though. That's what godoc.org is for.)

**Comment by shurcooL** [comment]
> I was only able to get the synopsis easily, but it'd be nice to have the whole package comment.

You can use [`go/doc`](https://godoc.org/go/doc) package for that. Its API is not pleasant to use, but it works.

See https://godoc.org/go/doc#Package.Doc, that's the whole package comment, not just synopsis.

**Comment by dmitshur** [comment]
> [...] it’s useful to have it automatically update, but the author should also be able to update the contents outside the block.

That was implemented in [CL 300229](https://go.dev/cl/300229); I forgot about this issue otherwise would've included a "Fixes" line in it, so I'll close this now. (I've considered other README improvements that were mentioned here, but I think by this point it'll be better to file new issues if there's a specific need.)
