### ISSUE TITLE
cmd/internal/obj/x86: invalid zoffset for ymmxmm0f38[1]

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#21286]
**Problem**:
I think there is a bug inside `cmd/internal/obj/x86/asm6.go`.

Suspicious lines:
```go
var ymmxmm0f38 = []ytab{
	{Ymm, Ynone, Ymr, Zlitm_r, 3},
	{Yxm, Ynone, Yxr, Zlitm_r, 5}, // <-- Here
}
```
[link to sources](https://github.com/golang/go/blob/master/src/cmd/internal/obj/x86/asm6.go#L879)

The `zoffset` field of 2-nd element of `ymmxmm0f38` seems incorrect.

Here is `optab` item for additional context:
```go
//                                                      Pe byte (may be important)
//                                                      |
APHADDD, ymmxmm0f38, Px, [23]uint8{0x0F, 0x38, 0x02, 0, 0x66, 0x0F, 0x38, 0x02, 0}
//                                 |                 |  |                       |
//                                 |                 |  4 bytes+Z
//                                 3 bytes+Z
```
[link to sources](https://github.com/golang/go/blob/master/src/cmd/internal/obj/x86/asm6.go#L1284)

**Potential solution**:
`5` should be replaced with `4` (If I get it right).

**Severity**:
This bug never triggers because `zoffset` does not matter
for last `ytab` entry.
Affects only code clarity and correctness, I guess.

**Comment by Quasilyte** [comment]
It may have something with `0x66` byte which is actually `Pe` byte.

Code seems overly complex, identifier names are unhelpful and inconsistent.

**Comment by ALTree** [comment]
> Code seems overly complex, identifier names are unhelpful and inconsistent.

IIRC it was mechanically translated from c code. Definitely not the most pleasant part of the toolchain to work on.

**Comment by Quasilyte** [comment]
Ok, it really needs "investigation", because simple expectations does not work.
```go
// works
var ymmxmm0f38 = []ytab{
	{Ymm, Ynone, Ymr, Zlitm_r, 3},
	{Yxm, Ynone, Yxr, Zlitm_r, 5},
}
{0x0F, 0x38, 0x02, 0, 0x66, 0x0F, 0x38, 0x02, 0}

// does not work
var ymmxmm0f38 = []ytab{
	{Yxm, Ynone, Yxr, Zlitm_r, 5},
	{Ymm, Ynone, Ymr, Zlitm_r, 3},
}
{0x66, 0x0F, 0x38, 0x02, 0, 0x0F, 0x38, 0x02, 0}

// also does not work
var ymmxmm0f38 = []ytab{
	{Ymm, Ynone, Ymr, Zlitm_r, 4},
	{Yxm, Ynone, Yxr, Zlitm_r, 5},
}
{0x0F, 0x38, 0x02, 0, 0x66, 0x0F, 0x38, 0x02, 0}
```

**Comment by Quasilyte** [comment]
My guess is:
"You always count all `op` bytes, except `0x0f` for `op[0]`".
If that is true, this issue can be closed because there is no bug there.

**Comment by randall77** [comment]
Even if there is no bug, it would be really nice to condense what you learned down to some comments in the code.

**Comment by Quasilyte** [comment]
There is no bug.
The way `ytab` tables are reused are somewhat error-prone and sometimes *look like* invalid, but this is another issue.
