### ISSUE TITLE
cmd/go: list -json outputs concatenated JSON documents, not one single one

### ISSUE THREAD

**Issue by stevekuznetsov** [golang/go#21280]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.7.5 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/skuznets/Documents/go"
GORACE=""
GOROOT="/home/skuznets/.gvm/gos/go1.7.5"
GOTOOLDIR="/home/skuznets/.gvm/gos/go1.7.5/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build979771774=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
I ran `go list -json` on a project with multiple packages.

### What did you expect to see?
A JSON list:

```json
{
  "Packages": [
    {
      "Dir": "whatever"
    },
    {
      "Dir": "whatever/else"
    }
  ]
}
```

### What did you see instead?
Concatenated JSON documents:

```json
{
  "Dir": "whatever"
}
{
  "Dir": "whatever/else"
}
```

**Comment by bradfitz** [comment]
We can document this for Go 1.10 but I don't think we should change it. That would unnecessarily break  existing tools consuming this. For instance, encoding/json.Decoder will consume multiple concatenated JSON objects.

**Comment by shurcooL** [comment]
Another way of describing "multiple concatenated JSON documents" is a that it's a JSON stream of objects. They are easy to parse.

**Comment by stevekuznetsov** [comment]
> For instance, encoding/json.Decoder will consume multiple concatenated JSON objects.

I was not aware of this -- there isn't really an issue, then, if it's simple to decode into `[]type` from a concatenated document.

**Comment by shurcooL** [comment]
@stevekuznetsov, see https://godoc.org/encoding/json#example-Decoder for an example.

**Comment by stevekuznetsov** [comment]
Right on, using that `encoding/json.Decoder.More()` pattern now. Feel free to close this -- the issue here was really that I thought it was going to be super difficult to get an API into the really awesome output of `go list` -- while this is still the case (`os.Exec` + `json.Decoder` is not the best), it's not not totally impossible. I would love to see the functions that resolve packages recursively be exported from some other utility package, but I understand to some extent why the backing logic for `go list` is private.

**Comment by dominikh** [comment]
@stevekuznetsov There is github.com/kisielk/gotool which contains an exported copy of the Go tools resolution of package paths (`...` and so on)
