### ISSUE TITLE
x/crypto/ssh/terminal: terminal using syscall.TCGETS (wrong for ppc64le)

### ISSUE THREAD

**Issue by clnperez** [golang/go#21293]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
master

### What operating system and processor architecture are you using (`go env`)?
``` 
go env
GOARCH="ppc64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/christy/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build365776170=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

This surfaced via logrus with https://github.com/sirupsen/logrus/pull/604

I hit this when revendoring logrus into `moby/moby`. I don't have a reproducer but it's a known issue that syscall.TCGETS and syscall.TCSETS are incorrect for ppc64le. I've been slowly trying to move projects over to use x/sys/.

I have a hacky test fix here: https://github.com/moby/moby/pull/34332. Specifically, the windows bits were tricky (for me) to test because I don't have easy access to Windows.

When I have more time I can upstream the go bits unless someone else can get to it first.

**Comment by bradfitz** [comment]
At crypto's master I see:

```
$ git grep TCGETS
ssh/terminal/util_linux.go:const ioctlReadTermios = 0x5401  // syscall.TCGETS
ssh/terminal/util_solaris.go:   val, err := unix.IoctlGetTermios(fd, unix.TCGETS)
ssh/terminal/util_solaris.go:   oldTermiosPtr, err := unix.IoctlGetTermios(fd, unix.TCGETS)
ssh/terminal/util_solaris.go:   oldTermiosPtr, err := unix.IoctlGetTermios(fd, unix.TCGETS)
```

It looks like util_linux.go uses a hard-coded value. I guess that's wrong on ppc64le?

```
$ git grep -E '\bTCGETS\b'
zerrors_linux_386.go:   TCGETS                               = 0x5401
zerrors_linux_amd64.go: TCGETS                               = 0x5401
zerrors_linux_arm.go:   TCGETS                               = 0x5401
zerrors_linux_arm64.go: TCGETS                               = 0x5401
zerrors_linux_mips.go:  TCGETS                               = 0x540d
zerrors_linux_mips64.go:        TCGETS                               = 0x540d
zerrors_linux_mips64le.go:      TCGETS                               = 0x540d
zerrors_linux_mipsle.go:        TCGETS                               = 0x540d
zerrors_linux_ppc64.go: TCGETS                               = 0x402c7413
zerrors_linux_ppc64le.go:       TCGETS                               = 0x402c7413
zerrors_linux_s390x.go: TCGETS                               = 0x5401
zerrors_linux_sparc64.go:       TCGETS                           = 0x40245408
zerrors_solaris_amd64.go:       TCGETS                        = 0x540d
```

Oh, yup.

That's easy. CL on its way.

/cc @tklauser

**Comment by tklauser** [comment]
Should be fixed by https://golang.org/cl/51690 (commit 558b6879de74bc843225cde5686419267ff707ca) already.

**Comment by bradfitz** [comment]
@tklauser, hah. Whoops.

And now I see Gerrit said for mine:

> Marking change merged without cherry-picking to branch, as the resulting commit would be empty.

I guess I hadn't synced either when I sent my change. Whoops.
