### ISSUE TITLE
x/build/cmd/gomote: ssh breaks with github usernames including a "-"

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#21294]
gomote splits on "-" in order to determine the "gomoteUser" (https://github.com/golang/build/blob/master/cmd/gomote/ssh.go#L38).

My github username has a hyphen (adams-sarah).
So..
```
$ gomote -user=adams-sarah ssh user-adams-sarah-linux-arm64-packet-0
$ ssh -p 2222 user-adams-sarah-linux-arm64-packet-0@farmer.golang.org 
# auth using https://github.com/adams.keys
```

Though it should be trying to auth with `https://github.com/adams-sarah.keys`

Will send a CL.

**Comment by bradfitz** [comment]
Your gomote username shouldn't contain a hyphen.

Your github username may, though.

You'll need to add a mapping for yourself to https://github.com/golang/build/blob/4eceee2/internal/gophers/gophers.go#L1549

**Comment by adams-sarah** [comment]
ok. so if anyone in the future has a github username with a hyphen, we need to create a mapping for them instead of them using -user=adams-sarah. Even though that would work for a github user without a hyphen in their username? Is that correct?
Or am I just doing things wrong.

**Comment by bradfitz** [comment]
Yes.

If gomoteUser != sshUser, it needs a mapping.

And gomoteUser cannot contain a hyphen.

Thus any github user will need a different gomote username and thus will need a mapping.

There will be like 10-15 people with access to this. I expect maybe 5 mappings.

**Comment by adams-sarah** [comment]
Okk sounds good.
Thanks Brad.

**Comment by bradfitz** [comment]
See https://go-review.googlesource.com/c/53190 for an example of adding a mapping for Ian.
