### ISSUE TITLE
runtime: sweep increased allocation count

### ISSUE THREAD

**Issue by heschik** [golang/go#21297]
We have reports inside Google of crashes like:
```
runtime: nelems=34 nalloc=2 previous allocCount=1 nfreed=65535
fatal error: sweep increased allocation count
```
I've reproduced the problem and I have some confidence that it's a runtime or compiler bug, so I wanted to make sure that we had an external issue to represent the problem and track it as a release blocker. I'll update this as soon as we have detail that can be shared publicly.

**Comment by ianlancetaylor** [comment]
CC @aclements

**Comment by ianlancetaylor** [comment]
Current analysis suggests a bug in https://golang.org/cl/38091.  That adds a fast path for map assignment, and uses it for pointers among other values.  When a pointer is stored in the map, no write barrier is used.

**Comment by randall77** [comment]
I have another fix which just uses typedmemmove to write the keys. It's just a  2-line change.

**Comment by andreimatei** [comment]
FWIW, I've encountered a similar crash with `go version go1.8 darwin/amd64`:
```
runtime: nelems=9 nfree=0 nalloc=9 previous allocCount=1 nfreed=65528
fatal error: sweep increased allocation count
runtime: nelems=256 nfree=12 nalloc=244 previous allocCount=223 nfreed=65515
fatal error: sweep increased allocation count
```
https://golang.org/cl/38091 seems to have been committed in March, so after go 1.8 was released.

**Comment by ianlancetaylor** [comment]
@andreimatei If you are seeing a problem with Go 1.8, then it is a different problem.  Please open a new issue with reproduction instructions.  Thanks.
