### ISSUE TITLE
ref/mem: no discussion of happens before relationships via atomic operations

### ISSUE THREAD

**Issue by jacobsa** [golang/go#21302]
The [memory model](https://golang.org/ref/mem) document is careful to define how various synchronization operations affect the happens before relationship. For example:

> A send on a channel happens before the corresponding receive from that channel completes.

And:

> For any sync.Mutex or sync.RWMutex variable l and n < m, call n of l.Unlock() happens before call m of l.Lock() returns.

However, there's no discussion in this section of writes and reads via the sync/atomic package. I've always assumed that they carry a happens before edge in the way that you would expect from release store and acquire load pairs in the C++ memory model, but it's not actually defined here as far as I can tell.

Can we assume that an atomic write of a value happens before an atomic read of that value from the same location? If so, should this be in the documentation?

**Comment by ianlancetaylor** [comment]
I think this is a dup of #5045.

**Comment by jacobsa** [comment]
Agreed, although that one seems to have gone a bit off-topic. :-/

**Comment by ianlancetaylor** [comment]
Closing as dup
