### ISSUE TITLE
cmd/go: -pkgdir does not always work with relative paths

### ISSUE THREAD

**Issue by yunabe** [golang/go#21309]
### What version of Go are you using (`go version`)?
`go version go1.8.3 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yunabe/local/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mp/xzsxb5nn0_j5406pjg8ttsq00000gn/T/go-build252110473=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
I cross compiled Go into Linux binary on MacOSX.

    // hello.go
    package main
    
    import "fmt"
    
    func main() {
      fmt.Println("Hello Go!")
    }

I compiled this hello.go with `GOOS=linux GOARCH=amd64 go build hello.go`. This worked perfectly but it was a little bit slow. It takes 2 to 3 secs to build this simple program because this command always builds all dependencies from source code.

So, I tried [-pkgdir](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies) option of go build. I expected the cross-compiled packages will be stored and reused from `-pkgdir`.

I ran the following command

    GOOS=linux GOARCH=amd64 go build -i -v -pkgdir cache hello.go

and just got an error message

    runtime/internal/sys
    runtime/internal/atomic
    runtime
    # runtime
    /usr/local/go/src/runtime/alg.go:8: can't find import: "runtime/internal/sys"

### What did you expect to see?
`-pkgdir` works with `GOOS=linux GOARCH=amd64` environment variables and improves build speed.

### What did you see instead?
It seems go build failed to load `runtime/internal/sys.a` from -pkgdir when it compiled `runtime`.

**Comment by crawshaw** [comment]
It looks like the bug occurs when there are no cross-compilation .a files in the GOROOT and you pass a relative path to `-pkgdir`. Testing here on macOS:

```
cd /tmp
$ GOOS=linux go build -i -pkgdir /tmp/mycache main.go   # works
$ rm -rf mycache
$ GOOS=linux go build -i -pkgdir mycache main.go
runtime/internal/sys
runtime/internal/atomic
runtime
# runtime
/Users/crawshaw/go/src/runtime/alg.go:8:2: can't find import: "runtime/internal/sys"
```

(As an aside, you describe using -pkgdir to get cross-compilation caching. You don't need -pkgdir for that if your GOROOT is writable. Just use -i. The intermediate stdlib packages are saved in $GOROOT/pkg/GOOS_GOARCH/.)
