### ISSUE TITLE
proposal: net/http/fs.go make private helper functions public

### ISSUE THREAD

**Issue by sisp** [golang/go#21308]
I've been wondering if it makes sense to expose many of the helper functions in ``net/http/fs.go`` publicly, e.g. ``setLastModified``, ``serveContent`` (the one that takes content via the ``io.ReadSeeker`` interface). I think many of the helper functions are generally useful for building a custom file server. Opinions?

**Comment by bradfitz** [comment]
Sorry, we're not going to expose and support and document every little implementation detail and overwhelm the godoc users need to read through to find the actual net/http bits they want.

If you find them useful, feel free to copy/paste them into your own package on GitHub and you can provide support for them.
