### ISSUE TITLE
x/tools/containers/intsets: use the Sparse root block

### ISSUE THREAD

**Issue by RaduBerinde** [golang/go#21311]
`Sparse` has a root block but that block doesn't store any element information. So even very small sets (e.g. single element) will need to allocate another block on the heap. So (on a 64-bit arch) we have 56 bytes in the structure and another 56 bytes on the heap, just to represent a single value.

There is no reason to not use the root block itself to store bits. It could be always the block with the smallest offset.

**Comment by josharian** [comment]
@alandonovan

**Comment by RaduBerinde** [comment]
I can try to find some time to take a stab at this if folks agree it's a good idea.

**Comment by alandonovan** [comment]
Please do; it would certainly be a worthwhile optimization.  I tried this at some point in the past but the logic got rather messy so I abandoned it.

**Comment by dongweigogo** [comment]
what about [bitsets](https://github.com/willf/bitset), a high performance pkg.

**Comment by RaduBerinde** [comment]
@dongweigogo - the usecase is different: `Sparse` supports arbitrary integers, `bitsets` looks like it allocates `X` bits if it contains value `X`.
