### ISSUE TITLE
x/tools/containers/intsets: request for a "lower bound" function for Sparse

### ISSUE THREAD

**Issue by RaduBerinde** [golang/go#21310]
It would be useful if `Sparse` provided a primitive to find the smallest element in the set that is `>=` to some given value.

```go
// LowerBound returns the first element greater than or equal to x, or MaxInt if there is no such element.
func (s *Sparse) LowerBound(x int) int
```

A use case for this is iterating through the elements when you know you have a small set and want to avoid allocating memory for `AppendTo`.

**Comment by josharian** [comment]
@alandonovan

**Comment by RaduBerinde** [comment]
I can try to find some time to work on this if the proposed API is accepted.

Another proposal is an API for iterating through a set:

```go
type IterationState struct {
  block *block
  value int
}
func (IterationState) Valid()
func (IterationState) Value() int

func (s *Sparse) StartIteration() IterationState
func (s *Sparse) Next(IterationState) IterationState
```

Sample usage:
```
for (i := s.StartIteration(); i.Valid(); i = s.Next(i) {
  fmt.Println(i.Value())
}
```

**Comment by alandonovan** [comment]
Let's start with the LowerBound operation if that addresses your needs.
