### ISSUE TITLE
runtime: map{assign,delete}_fast routines should return ptr to key

### ISSUE THREAD

**Issue by randall77** [golang/go#21321]
The _fast routines need to use typedmemove and typedmemclr to update the keys and values.  Instead, we should return a pointer to the key and value and have the caller update them.  That way, the caller can just do a direct write in the case where the key or value has no pointers.

... and maybe the non-fast versions also?

See #21297 

@josharian @aclements

**Comment by martisch** [comment]
As an alternative could the map functions themselfs check if the value has pointer and only use typedmemmove if writeBarrier.needed?
This would keep additional code outside the map functions small.

**Comment by josharian** [comment]
@martisch I've had a change implementing that locally for a while. (IIRC, it led to me filing https://github.com/golang/go/issues/20934.) I'll experiment a bit with alternatives here before sending anything.

**Comment by aclements** [comment]
The reason I suspect returning the key pointer may be faster is because then the caller could use a more specialized write in the pointer case. For example, if it's a pointer key, the fast path would be just a few instructions. But it would probably be worth trying out both and comparing them.
