### ISSUE TITLE
doc: document the lack of support for symlinks under GOPATH

### ISSUE THREAD

**Issue by ncantelmo** [golang/go#21320]
Quick back story:
I've spent much longer than I should publicly admit developing Go with go guru half working. Whenever I tried to jump to a symbol in the current package outside the current file, go guru would fail to find the identifier. This was annoying, but I've become accustomed enough to broken tooling that I didn't think too much of it after a search of the vim-go issue tracker didn't mention anything.

Today I got annoyed enough by the issue that I searched a bit harder and came across #20981 which in turn led me to #15507. Since I had been symlinking my privately hosted repo into my GOPATH, I immediately understood what was wrong. Fixing the issue was as simple as swapping the source and destination of my symlink. Now go guru finds all my symbols, which is great.

Anyway, the main issue here is that a lot of developers use symlinks for perfectly valid reasons, but GOPATH doesn't support them. This causes some elements of the go tooling to break without warning, and should therefore be prominently documented in `go help gopath` and https://golang.org/doc/code.html#GOPATH.

I can go ahead and submit a change, but I wanted to create an issue first to make sure this was fine.

**Comment by ALTree** [comment]
Seems reasonable. I would send a gerrit change so we can bikeshed there about the exact wording where in the page put the warning.
