### ISSUE TITLE
gccgo: math: Ldexp mishandles exp larger than 32-bit

### ISSUE THREAD

**Issue by cherrymui** [golang/go#21323]
### What version of Go are you using (`go version`)?
Go tip (~1.9), gccgo `gccgo (GCC) 8.0.0 20170725 (experimental)`

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
```
package main

import (
        "fmt"
        "math"
)

var i int64 = 1<<32 + 1

func main() {
        fmt.Println(math.Ldexp(1.0, int(i)))
}
```

### What did you expect to see?
With gc toolchain, the program above prints `+Inf` on linux/amd64. I believe this is the expected result.

### What did you see instead?
With gccgo, the program above prints 2 on linux/amd64.

gccgo's math.Ldexp uses libc_ldexp, which is defined in C as `double ldexp(double x, int exp)`. On linux/amd64, C's int is 32-bit whereas Go's int is 64-bit, causing this problem.

@ianlancetaylor

**Comment by thanm** [comment]
Cherry, I can take a shot at fixing this if you don't already have a CL -- let me know.

**Comment by cherrymui** [comment]
@thanm, thank you.
No, I don't have a CL.

**Comment by thanm** [comment]
Fix by https://go-review.googlesource.com/c/54250
No sure why, but gopherbot didn't auto-close.

**Comment by ianlancetaylor** [comment]
It didn't auto-close because it wasn't written as "golang/go#21323".  Sorry I didn't catch that.

**Comment by thanm** [comment]
Ah ok, thanks. I'll try to remember.
