### ISSUE TITLE
os.Getpagesize() should return correct page size on 4K_PAGES arm64 machine like Ubuntu 16.04 LTS with Cavium ThunderX1 SoC

### ISSUE THREAD

**Issue by baiyz** [golang/go#21349]
### What version of Go are you using (`go version`)?
go version go1.6.2 linux/arm64

### What operating system and processor architecture are you using (`go env`)?
go env
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/lib/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
On 4K_PAGES Ubuntu 16.04 LTS
getconf PAGE_SIZE
4096

However, os.Getpagesize() returned 65536
because hardcoded page size: syscall/syscall_linux_arm64.go:func Getpagesize() int { return 65536 }

### What did you expect to see?
Getpagesize() should return correct page size at compile time and runtime.

### What did you see instead?
Hardcoded 65536 page size may not be the correct page size.

**Comment by bradfitz** [comment]
This was fixed in Go 1.8 in 1b9499b06989d2831e5b156161d6c07642926ee1
See https://golang.org/doc/go1.8#syscall
(which only says syscall, but it was also os which uses syscall)
