### ISSUE TITLE
 Two-dimensional slice with append operation will change the slice  unexpected

### ISSUE THREAD

**Issue by minping111111** [golang/go#21342]
![image](https://user-images.githubusercontent.com/9964047/29076314-bc76a62a-7c87-11e7-9523-1664dd4ee03c.png)
see the screenshot above,I used the  Two-dimensional slice as the first param of the append operation, and use another variable to receive the apppend result,but, I found before and after the append operation,the original variable res had changed!!!why??

**Comment by mvdan** [comment]
Please read https://blog.golang.org/go-slices-usage-and-internals. For questions about Go, see https://golang.org/wiki/Questions.
