### ISSUE TITLE
Go binaries don't run on the VMWare ESXi shell

### ISSUE THREAD

**Issue by ncw** [golang/go#21347]
According to wikipedia [ESXi](https://en.wikipedia.org/wiki/VMware_ESXi) runs a modifed Linux kernel which provides the ESXI shell and ssh services.

Some rclone users have been attempting to run go binaries on that kernel which seems reasonable since it supplies a Linux OS.

However the binaries segfault immediately.

### What version of Go are you using (`go version`)?

    go version devel +123fd4640a Sun Jul 9 19:23:41 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

The target OS is VMWare ESXi  6.5

I compiled the binary on Ubuntu 17.04 amd64

### What did you do?

I compiled a [hello world program ](https://play.golang.org/p/sqjFommznr) and ran it on VMWare ESXi 6.5

### What did you expect to see?

    Hello, World!

### What did you see instead?

It produced this

```
[root@localhost:~] ./hello 
Segmentation fault (core dumped)
```

I tried compiling with CGO_ENABLED=0 and  CGO_ENABLED=1 with no difference.

I copied a binary (`xz`) from the ESXi platform and it ran fine on my Ubuntu 17.04 amd64 laptop indicating that the platforms aren't a million miles apart.

I tried to statically compile gdb but failed, and the coredumps I could make are in zdump format which I haven't managed to decode, so I haven't made any progress debugging this.

The desire for this originally came from https://github.com/ncw/rclone/issues/1578 where some rclone users were wanting to use it on ESXi.

The whole idea of running go on ESXi may be out of scope for the Go project as the VMWare linux kernel is clearly heavily customized.

I managed to set up VMWare ESXi on VirtualBox if anyone wants to have a go.  Here are some hints..

  * Install VMWare latest in Virtualbox
  * Make sure you give it 2 CPUs and 4 GB of ram
  * Disable USB otherwise it panics - you'll have to change the default pointing device to PS/2 from tablet
  * Start it in Virtualbox with host networking
  * When installed
    * Press F2, log in with the password you put in during the installation process
    * Enable ssh so you can log in from your laptop under Troubleshooting options

**Comment by vcabbage** [comment]
It may be possible to get a Go binary to run on ESXi since some statically linked Linux binaries do, but according to VMware the kernel is proprietary and not based on Linux.

**Comment by vcabbage** [comment]
Also, the Service Console was a sort of hidden Linux VM used in ESX. ESX was discontinued years ago. The Service Console doesn't exist in ESXi which instead provides users a BusyBox shell running directly on vmkernel.

**Comment by ncw** [comment]
@vcabbage wrote:
> It may be possible to get a Go binary to run on ESXi since some statically linked Linux binaries do, but according to VMware the kernel is proprietary and not based on Linux.

The binaries I looked at (specifically `/bin/xz`) were dynamically linked.  `/bin/xz` worked on my ubuntu laptop, but the one from my ubuntu laptop didn't work on ESXi complaining about GLIBC versions.

> Also, the Service Console was a sort of hidden Linux VM used in ESX. ESX was discontinued years ago. The Service Console doesn't exist in ESXi which instead provides users a BusyBox shell running directly on vmkernel.

Yes it seems to be called "ESXi Shell" in the config options - I'll update the issue with that name.  I know nothing about ESXi so thanks for the note!

**Comment by davecheney** [comment]
To the best of my knowledge the ESXi hypervisor is based on kernel
2.4.something and probably lacks the expected 2.6.27 or later syscalls.

**Comment by ianlancetaylor** [comment]
If @davecheney is correct then there is nothing we can reasonably do here.  Sorry.
