### ISSUE TITLE
x/build: linux-arm-arm5spacemonkey build stalled: no space left on device

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#21351]
ERRORs in stackdriver:
2017/08/08 19:36:18 {linux-arm-arm5spacemonkey e0e7c03d14d3235864400ad29aa02dfa540d2089 } failed: failed to put snapshot to buildlet: 500 Internal Server Error; body: error writing to /home/builder/stage0scratch/tmp/workdir/go/test/fixedbugs/bug338.go: write /home/builder/stage0scratch/tmp/workdir/go/test/fixedbugs/bug338.go: no space left on device

Logs: https://farmer.golang.org/temporarylogs?name=linux-arm-arm5spacemonkey&rev=c4e29bbd3813be43b3905e17a2796cea23dd66d4&st=0xc44a7c8600

go-builder-3 (10.240.0.18:56501) version 11, host-linux-arm5spacemonkey: connected 2h57m50.4s, working for 2h57m50.4s

cc @bradfitz @jessfraz @cybrcodr @zombiezen @shantuo

**Comment by jessfraz** [comment]
bigger disks or more cleanup of disk space?

**Comment by bradfitz** [comment]
None of the cced people own these machines. See the farmer builders page for the owner.

**Comment by adams-sarah** [comment]
@zeebo

**Comment by bradfitz** [comment]
@zeebo, let us know what you find. The buildlet should be cleaning up after itself after (or rather, before) each build.

But it's possible you're not setting the `-workdir` flag, which means it's picking a new temp dir out of /tmp for each build, and then if your builds fail midway though (or rather, we restart the coordinator mid-build and your buildlet process restarts) then it might be picking a new workdir and keeping the old one around if your system /tmp dir doesn't clean or clean fast enough.

I think the best fix is for your builder looper to pass an explicit `-workdir` flag.

**Comment by zeebo** [comment]
We set TMPDIR to something, and yep it's full of things.

I'll change the scripts to pass `-workdir` and clean it up.

**Comment by zeebo** [comment]
Ok I've looked in to this some. I don't see a way that I can from my environment pass `-workdir` to the `buildet` command. the `stage0` command handles running the `buildet` for me, and I see no way in either `stage0` or `buildet` pass it the flag.

Is the next step to modify one of these two binaries to allow me to pass it in through some environment variable or something? Is my setup wacky?

I've temporarily cleaned out the directories.

**Comment by adams-sarah** [comment]
@zeebo sorry for my delay.
yes, please submit a CL to modify cmd/buildlet/stage0/stage0.go.
there is a switch towards the bottom of main() (L167) which would be appropriate to add to.

LMK if you have questions. please add me as the reviewer when your cl is up.

**Comment by zeebo** [comment]
I'm going to attempt to move the conversation here vs the above CL to keep the conversation together. After updating the `stage0` binary, it seems to me that other changes to the infrastructure have caused problems, requiring a rebuild of the hosted `buildlet` binary. After that, the build key seems to be invalid.

    bad key for mode "host-linux-arm5spacemonkey"

In case it helps figure out the issue sooner, I had to rename the `/.gobuildkey` to `/.gobuildkey-host-linux-arm5spacemonkey` to get that far. 

I assume I just need to get a new key sent to me? I don't know how public these keys are, but just in case since it's called a "key", I'm available at the email in my github profile or as @zeebo on the gophers slack.

**Comment by adams-sarah** [comment]
Hey @zeebo sending you a new key via email now.

**Comment by zeebo** [comment]
Alright, they're all running with the new key, and the flag is being passed.

Thanks!

**Comment by adams-sarah** [comment]
excellent. np.
