### ISSUE TITLE
flag how to using multiple single flags

### ISSUE THREAD

**Issue by jinfagang** [golang/go#21359]
I write 2 flag say -d -f all are bool value, -d -f means enable -d and -f, but how to using flag let user can type: -df to enable both?

Trying to figure out but failed, flag try to parse as a param df which not defined. Any idea would be appreciated!

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by jinfagang** [comment]
If flag doesn't support this feature please let me know.
