### ISSUE TITLE
cmd/compile/ssa/arm64: emit bit-test-and-branch instructions

### ISSUE THREAD

**Issue by philhofer** [golang/go#21361]
ARM64 supports bit-test-and-branch-if-(not-)zero instructions (TBZ and TBNZ), but the ssa backend doesn't know how to emit them yet. (Those instructions do appear to be known to the assembler, though.)

As a prerequisite to adding these block types, an immediate field will have to be added to `ssa.Block` to work along with `ssa.Block.Control`, and that immediate will need to be accessible through the usual rewrite rule syntax (`[imm]`).

Then, most of what needs to be done is
```
(Z (ANDconst [c] x) yes no) && oneBit(c) -> (TBZ  [bitIndex(c)] x yes no)
```
and so forth.

I have a draft of this that I intend to polish and mail shortly.

**Comment by randall77** [comment]
Sounds fine.

You could use the existing aux field, like:
```
(Z (ANDconst [c] x) yes no) && oneBit(c) -> (TBZ  {bitIndex(c)} x yes no)
```
A bit clunky as you would need to do b.Aux.(int) to get the result out. But it avoids adding fields to Block.

**Comment by philhofer** [comment]
Good idea. I'll do that.
