### ISSUE TITLE
ExperienceReport/Proposal on := syntax issues

### ISSUE THREAD

**Issue by BrianWill** [golang/go#21368]
I'd like this report/proposal added to the ExperienceReport wiki:

https://gist.github.com/BrianWill/671ce51e6ef6a9f0caa27272a9a0637f

**Comment by davecheney** [comment]
Be the change you seek, anyone can edit the wiki (as far as I know)

**Comment by ALTree** [comment]
Looks like you added it, so I'm closing this.
