### ISSUE TITLE
Non go files issue

### ISSUE THREAD

**Issue by alkesh26** [golang/go#21366]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.1

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alkesh/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5k/bdptwfgd4dl4zwvlg0xlvd8h0000gp/T/go-build527398333=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
1. We are adding non go files in our go repo. Eg lets say I add a `test.json` file which has following content
```
{
    a : 1,
    b: "abc"
}
```
I read this file in our program and get the keys (`a`, `b`) value. I am able to read file locally.

### What did you expect to see?
I commit this `test.json` file and push my code to staging.  I expect to get values of `a` and `b`.

### What did you see instead?
I get error `no such file or directory`

I am new to GO and not able to figure out what the error is. Does go exclude non .go files?
Or we have to upload these files (`test.json`) on production?

**Comment by davecheney** [comment]
@alkesh26 please include in your report a sample program which demonstrates the issue so that others can verify the problem and offer a solution or explanation.

**Comment by mvdan** [comment]
I understand you're pushing the JSON file to your git repo, but not to staging/production? If so, this is expected. When you read the file from disk, it has to be on disk - that is, whereever your process is running.

And, for questions about Go, remember to use https://golang.org/wiki/Questions.

**Comment by alkesh26** [comment]
@mvdan We are pushing that file to staging/production.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
