### ISSUE TITLE
MOVQ 0, AX optimisation

### ISSUE THREAD

**Issue by xigh** [golang/go#21369]
### What version of Go are you using (`go version`)?

go version go1.8 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xigh/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1p/fl56f8416hzc5_lkcf65tlp00000gn/T/go-build894248986=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

I was trying to implement DCAS (or CAS2) atomic instruction (see https://gist.github.com/xigh/062fcca51b090ebb675c5486349a75f9) in x64 assembly. In order to remove the banches, I tried to use CMOVcc instruction. I thus wrote this:

TEXT ·CompareAndSwapDPointer(SB),4,$0
	MOVQ		addr+0(FP), SI
	MOVQ		old+8(FP), AX
	MOVQ		old+16(FP), DX
	MOVQ		new+24(FP), BX
	MOVQ		new+32(FP), CX
	// CMPXCHG16B 	(SI)
	BYTE $0x48; BYTE $0x0F; BYTE $0xC7; BYTE $0x0E
	MOVQ		$0, AX
	MOVQ		$1, DX
	// CMOVZ	DX, AX
	BYTE $0x48; BYTE $0x0F; BYTE $0x44; BYTE $0xC2
	MOVQ		AX, ret+40(FP)
	RET

### What did you expect to see?

MOVQ implemented as MOVQ, not XORQ AX, AX

### What did you see instead?

MOVQ has been optimised with XORQ. I think it's fine and I'm not sure it is a bug. But in this case, the XORQ updates the RFLAGS register and this the code above does not work. I can either use branches or use another register and move the MOVQ instruction before CMPXCHG16B.

XORQ is obviously shorter and maybe more efficient. That's why I'm not sure we can say it is a bug. But Dave Cheney suggested me to report this here.

**Comment by ALTree** [comment]
This is #20986.

**Comment by ALTree** [comment]
And see Josh comment https://github.com/golang/go/issues/20986#issuecomment-314639291 for some background. Closing this as a dup so we can keep all info in one place. Hope #20986 will be looked at during the go1.10 cycle.
