### ISSUE TITLE
x/crypto/ssh: docs for SignCert omit mention of nonce

### ISSUE THREAD

**Issue by cryslith** [golang/go#21384]
The documentation for [`Certificate.SignCert`](https://godoc.org/golang.org/x/crypto/ssh#Certificate.SignCert) should note that it automatically sets `c.Nonce` to a 32-byte random nonce before signing.

**Comment by jakob223** [comment]
Add the relevant lines to the doc: https://go-review.googlesource.com/57051

**Comment by meirf** [comment]
@tklauser any interest in reviewing this small change? I actually think jakob223's change is good as is - I think ["random" ](https://go-review.googlesource.com/c/crypto/+/57051#399)is useful since it implies that it's using the `rand io.Reader` argument.

**Comment by tklauser** [comment]
@meirf thanks. I'm not familiar with this code, but I've added @FiloSottile as a reviewer to have a look at the CL.

**Comment by cryslith** [comment]
Hi, I'd like to fix this.  Is there a way for me to "adopt" the change that @jakob223 started, or should I create a new changeset?

**Comment by tklauser** [comment]
> Hi, I'd like to fix this. Is there a way for me to "adopt" the change that @jakob223 started, or should I create a new changeset?

@cryslith feel free to send a new CL, I don't think there is a way to adopt a CL.
