### ISSUE TITLE
Spec missing translation.

### ISSUE THREAD

**Issue by NCSantos** [golang/go#21385]
Hi,

On the last example of https://golang.org/ref/spec#Struct_types a translation is missing, it says:
   "ceci n'est pas un champ de structure"
and it should say:
"This is not a struct field".

Or is this a pun?

**Comment by ALTree** [comment]
Considering that AFAIK the spec *wasn't* originally written in French, I'd say this is not a missing translation, it must be intentional.

**Comment by griesemer** [comment]
Il n'y a pas de plaisir à écrire tout dans la même langue.
