### ISSUE TITLE
cmd/compile,math: improve performance for some math functions for ppc64x

### ISSUE THREAD

**Issue by laboger** [golang/go#21390]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go tip

### What operating system and processor architecture are you using (`go env`)?
Ubuntu (or any) ppc64le

Making some improvements to several math functions by writing some in asm and implementing some as intrinsics.

I will be creating multiple CLs to do this, so instead of opening multiple issues, I would like to assign them all to this one.

The first change will be to implement the trunc, floor, and ceil functions as intrinsics.

**Comment by ALTree** [comment]
This is (a subset of) #8913 (math, crypto, hash: Write power64 versions of assembler routines where applicable)

**Comment by laboger** [comment]
I have merged all the math changes I had planned for go 1.10, so will close this one.
