### ISSUE TITLE
crypto/x509: SystemCertPool() can return nil,nil

### ISSUE THREAD

**Issue by champtar** [golang/go#21405]
### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
debian9 lxc (no certificates on the system) / amd64

### What did you do?
https://play.golang.org/p/9uFYp2M6PT

### What did you expect to see?
I expected to have either an error or an empty certPool

### What did you see instead?
both CertPool and error are nil when there is no certificates found on the system
If you think this is the correct behavior maybe add a small warning in the documentation

Regards
Etienne

**Comment by nussjustin** [comment]
This only affects [Unix](https://github.com/golang/go/blob/adc28cb/src/crypto/x509/root_unix.go#L87) and [Plan9](https://github.com/golang/go/blob/adc28cb/src/crypto/x509/root_plan9.go#L36), all other operating systems will return an empty pool when no certificates are found from what I see.

**Comment by shreyas1996** [comment]
![certpool](https://user-images.githubusercontent.com/30974958/29248991-936c2196-8043-11e7-956b-1b1b3979b067.png)
As you can see,this is the output we get when we run it on a windows based system..
Here is the source code for  the function you used..
https://golang.org/src/crypto/x509/cert_pool.go?s=730:770#L22
there it is.. 
i hope u got the doubt.. if not please help me understand it using a suitable use case
Regards 
Shreyas

**Comment by nussjustin** [comment]
@shreyas1996 Using SystemCertPool under Windows is issue #16736, see the issue description in #18609 for the basic problem with it unter windows. This issue is about a (nil, nil) return value under Unix (and Plan 9)

**Comment by shreyas1996** [comment]
oh okay.. i will check that too
But as stated above by @champtar  used that function.. i thought maybe he/she was concerned as to why such an output was displayed when the expected one is different.
anyways,thanks for pointing it out @nussjustin
