### ISSUE TITLE
link is dead

### ISSUE THREAD

**Issue by rbucker** [golang/go#21408]
http://gosexy.org/db

**Comment by cespare** [comment]
Is "gosexy.org" supposed to be owned by the Go project?

**Comment by davecheney** [comment]
Thanks for your issue report. It's very hard to know how to address it, or even if this is something that can be addressed without more context. Can you please explain where you found that link?

**Comment by rbucker** [comment]
Sorry. It's a link in the wiki.

**Comment by davecheney** [comment]
What is the link to the wiki page?

**Comment by cznic** [comment]
https://github.com/golang/go/wiki/Projects#multiple-wrappers

**Comment by davecheney** [comment]
Deleted

**Comment by rbucker** [comment]
thanks.  Sorry for the poor quality of the report.

**Comment by davecheney** [comment]
That's ok. Im 80% sure that anyone can edit the wiki, so you can probably
do this gardening yourself in the future.
