### ISSUE TITLE
crypto/x509: TestSystemRoots failure

### ISSUE THREAD

**Issue by martisch** [golang/go#21416]
go tip 23cd87eb0a2d49a3208824feaf34d8b852da422f and earlier in 1.9 candidates

while running ./all.bash i have a reproducible test error on darwin:
--- FAIL: TestSystemRoots (1.41s)
	root_darwin_test.go:31:     cgo sys roots: 443.728642ms
	root_darwin_test.go:32: non-cgo sys roots: 964.424609ms
	root_darwin_test.go:44: got 169 roots
	root_darwin_test.go:44: got 453 roots
	root_darwin_test.go:73: insufficient overlap between cgo and non-cgo roots; want at least 226, have 168
FAIL

macOS Sierra 10.12.6 but i have seen that failure on macOS 10.11 too since i just upgraded.

Darwin ender 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

another similar report here:
https://groups.google.com/forum/#!topic/golang-nuts/LZvj2N_8gs4

**Comment by martisch** [comment]
```
a005a8d1b4 html/template: use the same escaper across multiple template executions
go test -run=TestSystemRoots
PASS
ok  	crypto/x509	0.214s
4dbcacda96... crypto/x509: load all trusted certs on darwin (nocgo)
ender:x509 martisch$ go test -run=TestSystemRoots
--- FAIL: TestSystemRoots (0.74s)
	root_darwin_test.go:31:     cgo sys roots: 124.339674ms
	root_darwin_test.go:32: non-cgo sys roots: 614.074109ms
	root_darwin_test.go:44: got 169 roots
	root_darwin_test.go:44: got 453 roots
	root_darwin_test.go:73: insufficient overlap between cgo and non-cgo roots; want at least 226, have 168
FAIL
exit status 1
FAIL	crypto/x509	0.752s
```

/cc @dsnet @ianlancetaylor

**Comment by martisch** [comment]
adding authors and more reviewers from the CL
/cc @mastercactapus @josharian

**Comment by martisch** [comment]
I tagged this Go1.9 since i traced it to a CL merged at end of 1.9 cycle and it would be nice to have a working test suite on darwin with 1.9 release and also counter confusion and issue tickets from any others that will encounter the above failure when compiling 1.9 from source on darwin.

**Comment by mastercactapus** [comment]
I suspect this is due to the cgo counterpart to that fix not having made it into 1.9 (as it's still in-progress)
https://go-review.googlesource.com/c/36942

**Comment by adamryman** [comment]
If this is a release blocker why did 1.9 get released without this?

**Comment by martisch** [comment]
Because the label was a suggestion by me but the decision was made by the go team that the issue should not hold up the release of 1.9. It can be considered for 1.9.x.

**Comment by ianlancetaylor** [comment]
If I'm reading this correctly, the fix for this test failure is to disable the test.

I guess that is OK for a backport to 1.9.

**Comment by rsc** [comment]
Sure, we can disable the test that non-cgo works here. 

CL 57830 OK for Go 1.9.2.

**Comment by rsc** [comment]
I'm going to remilestone this to Go 1.10 for a proper fix, since there is good context in this thread, and I created #22256 for the Go 1.9.2 cherry-pick.

**Comment by martisch** [comment]
reopening because after submission of https://golang.org/cl/117055
./all.bash on tip is broken again on my private macbook pro (Darwin ender 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
):

$ git checkout 2642df9a2c82b9de3e2868321cd109085d6910d3
$ ./all.bash
...
--- FAIL: TestSystemRoots (4.97s)
    root_darwin_test.go:31:     cgo sys roots: 420.836945ms
    root_darwin_test.go:32: non-cgo sys roots: 4.545627256s
    root_darwin_test.go:44: got 177 roots
    root_darwin_test.go:44: got 467 roots
    root_darwin_test.go:73: insufficient overlap between cgo and non-cgo roots; want at least 233, have 172
FAIL
FAIL	crypto/x509	6.895s

@bradfitz 
can we rollback cl/117055 until the underlying issue is fixed (happy to provide more information until root cause of problem is found)?

**Comment by adamdecaf** [comment]
@martisch Could you try with these CL's and see if the test is fixed?

https://github.com/golang/go/issues/24652#issuecomment-401421022

**Comment by martisch** [comment]
applied 3 patches from #24652 to tip:
ec09ea9fa4 (HEAD -> x509test) crypto/x509: on darwin verify-cert with ssl policy
54a3bdbe1e crypto/x509: collect keychain certs without explicit usage constraints
a6f6cfa570 crypto/x509: check darwin keychain policy in cgo path
8a330454dc (origin/master, origin/HEAD, master) net/url: don't escape sub-delims in fragment

result:
--- FAIL: TestSystemRoots (1.58s)
    root_darwin_test.go:31:     cgo sys roots: 126.320357ms
    root_darwin_test.go:32: non-cgo sys roots: 1.44816439s
    root_darwin_test.go:44: got 177 roots
    root_darwin_test.go:44: got 467 roots
    root_darwin_test.go:73: insufficient overlap between cgo and non-cgo roots; want at least 233, have 171

any other CLs i should apply?

**Comment by adamdecaf** [comment]
@martisch 400+ roots seems like a lot compared to my system. I only have two custom CA's installed. 

I tried from [`8a33045`](https://github.com/golang/go/commit/8a330454dc1502091dba2c890f5f6d0c095034de) (in your comment) and [`ebdba42`](https://github.com/golang/go/commit/ebdba42d9e1de46ebf611baec98d53f01c534cac) with both examples passing: 

```
// https://github.com/golang/go/commit/ebdba42d9e1de46ebf611baec98d53f01c534cac
$ ../bin/go test -v -count 1 -run TestSystemRoots crypto/x509 
=== RUN   TestSystemRoots
--- PASS: TestSystemRoots (3.03s)
    root_darwin_test.go:31:     cgo sys roots: 1.467407679s
    root_darwin_test.go:32: non-cgo sys roots: 1.5584415s
    root_darwin_test.go:44: got 169 roots
    root_darwin_test.go:44: got 173 roots
PASS
ok  	crypto/x509	3.043s
```

Could you explain more about the certificates picked up in the non-cgo route? Adding `GODEBUG=x509roots=1` will list them out as they're picked up. (Please from from tip as there's better debugging.)

**Comment by martisch** [comment]
I have a lot of email certificates in my login key chain from smime signed emails from a common authority (e.g. DFN-PKI) . AFAIK apple mail adds them automatically to my keychain. I just deleted one of those and the number of "got roots" decreased by one. The trust on those certificates is system default.

**Comment by adamdecaf** [comment]
It's been mentioned `crypto/x509` is just for the web PKI, so we could probably exclude these certs from the SystemCertPool() result.

Do these certificates only have SubjectAltNames's for emails or Extended KeyUsage for email?

**Comment by martisch** [comment]
The certificates have:
X509v3 Key Usage:  Digital Signature, Non Repudiation, Key Encipherment
X509v3 Extended Key Usage: TLS Web Client Authentication, E-mail Protection, Microsoft Smartcardlogin

and:
X509v3 Subject Alternative Name: 
email: X, email:Y .....

(Where X and Y are placeholders here for actual email addresses)

**Comment by adamdecaf** [comment]
@FiloSottile Should we ignore picking up certs that only have email SANs? 

Also, I don't really see crypto/x509 documented as "web pki only", but should we?

**Comment by bcmills** [comment]
This is failing again on the 10.11 builders (but not the other darwin builders) as of https://golang.org/cl/128117.

```
--- FAIL: TestSystemRoots (0.30s)
    root_darwin_test.go:34:     cgo sys roots: 66.259292ms
    root_darwin_test.go:35: non-cgo sys roots: 201.101857ms
    root_darwin_test.go:76: signed certificate only present in non-cgo pool (acceptable): CN=Developer ID Certification Authority,OU=Apple Certification Authority,O=Apple Inc.,C=US
    root_darwin_test.go:103: expired certificate only present in cgo pool (acceptable): OU=Equifax Secure Certificate Authority,O=Equifax,C=US
    root_darwin_test.go:107: certificate only present in cgo pool: CN=Thawte Premium Server CA,OU=Certification Services Division,O=Thawte Consulting cc,L=Cape Town,ST=Western Cape,C=ZA
    root_darwin_test.go:103: expired certificate only present in cgo pool (acceptable): CN=GTE CyberTrust Global Root,OU=GTE CyberTrust Solutions\, Inc.,O=GTE Corporation,C=US
    root_darwin_test.go:107: certificate only present in cgo pool: CN=Thawte Server CA,OU=Certification Services Division,O=Thawte Consulting cc,L=Cape Town,ST=Western Cape,C=ZA
    root_darwin_test.go:107: certificate only present in cgo pool: OU=Class 3 Public Primary Certification Authority,O=VeriSign\, Inc.,C=US
```

**Comment by FiloSottile** [comment]
I'm working on it. I have so far not figured out where those three certificates come from.

**Comment by katiehockman** [comment]
Just a note that this is still failing the darwin 10.11 builds.
