### ISSUE TITLE
godoc: godoc -http is broken in 1.9rc2

### ISSUE THREAD

**Issue by maruel** [golang/go#21413]
### What version of Go are you using (`go version`)?
1.9rc2

### What operating system and processor architecture are you using (`go env`)?
Ubuntu

### What did you do?
godoc -http=:6060

### What did you see instead?
```
template: main:6:10: executing "main" at <$.GoogleCN>: GoogleCN is not a field of struct type godoc.Page
```

It was likely caused by https://go-review.googlesource.com/c/53051

**Comment by maruel** [comment]
Paging @andybons

**Comment by ianlancetaylor** [comment]
Is it possible that https://golang.org/cl/52872 didn't make it into 1.9rc2?

**Comment by maruel** [comment]
Sorry for the noise, a clean build fixed it. For an unknown reason, I had a stale `godoc` in my `$GOROOT/bin`.
