### ISSUE TITLE
golang 1.7 6g issue - When trying to "go run mk.go install - for godag instalation from source

### ISSUE THREAD

**Issue by avi301** [golang/go#21438]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7
### What operating system and processor architecture are you using (`go env`)?
centos linux 7

### What did you do?
install golang through yum and trying to install godag from source after that.
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
complete

### What did you see instead?
[ERROR] fork/exec /usr/local/go/pkg/tool/linux_amd64/6g: no such file or directory exit status 1

**Comment by ALTree** [comment]
This is godag fault:

```
    case "amd64":
        S = ".6"
        C = "6g"
        L = "6l"
    [...]
    path_C := filepath.Join(R, "pkg", "tool", (O + "_" + A), C)
```

Last godag commit was 4 years ago, but the tool is now no longer called `6g`, it's called `tool compile`. So unless the godag maintainer fixed its tool, you won't be able to use it with go1.7

**Comment by mvdan** [comment]
As @ALTree mentioned, this is a bug in the project you're trying to compile, not in Go. Try their issue tracker. You could always try building it with an earlier Go version that used the old tool names.
