### ISSUE TITLE
cmd/compile: multiplication strength-reduction rules hurting performance

### ISSUE THREAD

**Issue by ALTree** [golang/go#21434]
I noticed that certain strength-reduction rules for multiplication seem to harm performance on my machine.

Take the following rule  in AMD64.rules (that reduces `c * n`, when `c` is a constant one less of a power of 2):

```
(MULQconst [c] x) && isPowerOfTwo(c+1) && c >= 15 -> (SUBQ (SHLQconst <v.Type> [log2(c+1)] x) x)
```

Two silly benchmarks:

```
package main

import "testing"

//go:noinline
func F1(n int) int {
	return 15 * n
}

var arr = []int{
	2, 3, 5, 7, 11, 13, 18, 19, 23, 29, 31, 37, 41, 43,
}

func F2() int {
	sum := 0
	for i := range arr {
		sum += 15 * arr[i]
	}

	for i := range arr {
		sum += 31 * arr[i]
	}
	return sum
}

var sink int

func BenchmarkF1(b *testing.B) {
	for i := 0; i < b.N; i++ {
		sink = F1(i)
	}
}

func BenchmarkF2(b *testing.B) {
	for i := 0; i < b.N; i++ {
		sink = F2()
	}
}
```

The generated code for `F1` with and without the strength reduction rule:

```
"".F1 STEXT nosplit size=21 args=0x10 locals=0x0
        [...]
	0x0000 00000	MOVQ	"".n+8(SP), AX
	0x0005 00005	MOVQ	AX, CX
	0x0008 00008	SHLQ	$4, AX
	0x000c 00012	SUBQ	CX, AX
	0x000f 00015	MOVQ	AX, "".~r1+16(SP)
	0x0014 00020	RET
```

```
"".F1 STEXT nosplit size=15 args=0x10 locals=0x0
        [...]
	0x0000 00000	MOVQ	"".n+8(SP), AX
	0x0005 00005	IMULQ	$15, AX
	0x0009 00009	MOVQ	AX, "".~r1+16(SP)
	0x000e 00014	RET
```

A single `IMULQ` instruction is replaced by a `MOVQ`, a `SHLQ`, and a `SUBQ`; the reduced code also uses one more register. The reduction seems to harm performances. Benchmarks results with tip vs tip+rule-disabled

```
name  old time/op  new time/op  delta
F1-4  2.34ns ± 2%  2.33ns ± 0%     ~     (p=1.000 n=5+5)
F2-4  23.2ns ± 2%  17.2ns ± 3%  -26.08%  (p=0.008 n=5+5)
```

The rule makes no difference on the microbenchmark, and strongly hurts performances on the more realistic second benchmark.

This is on an Haswell machine, where the rule-of-thumb currently used for this kind of reduction (`addq`, `shlq`, `leaq`, `negq` all cost 1, `imulq` costs 3) should be valid. And yet, the reduced code is either as fast or significantly slower than the one using `imul`.

**Comment by josharian** [comment]
@TocarIP @randall77

**Comment by ALTree** [comment]
Ah, the rules are for latency. Thanks for the explanation.

> I think latency is more important than throughput, so we should keep the rewrite

Well, most of the C compilers I looked at (GCC, Clang, intel) seem to optimize for latency, so I guess that's a point in favour of keeping those rewrites rules.

**Comment by randall77** [comment]
Ok, I'll close this issue then.  Feel free to reopen if you want to continue discussing.
