### ISSUE TITLE
os/signal: TestAtomicStop fails

### ISSUE THREAD

**Issue by dsnet** [golang/go#21433]
Just saw this failure on the `darwin-amd64` builders:
```
--- FAIL: TestAtomicStop (1.12s)
	signal_test.go:324: iteration 0: output 
	signal_test.go:324: iteration 1: output 
	signal_test.go:324: iteration 2: output 
	signal_test.go:324: iteration 3: output 
	signal_test.go:324: iteration 4: output 
	signal_test.go:324: iteration 5: output 
	signal_test.go:324: iteration 6: output 
	signal_test.go:324: iteration 7: output lost signal on iterations: 3
	signal_test.go:331: iteration 7: lost signal
	signal_test.go:324: iteration 8: output 
	signal_test.go:324: iteration 9: output 
FAIL
FAIL	os/signal	5.514s
```

Full log:
https://storage.googleapis.com/go-build-log/eefc42f3/darwin-amd64-10_11_7a763c87.log

\cc @bcmills

**Comment by bcmills** [comment]
That test was added in https://golang.org/cl/46003. I assume we've only seen a failure on Darwin so far? (Would be good to know whether it's flaky everywhere or just on Darwin.)

(CC: @ianlancetaylor)

**Comment by ianlancetaylor** [comment]
Was that a trybot run?  I don't see the git hash on tip.  The failure could have been caused by a Darwin-specific bug in https://golang.org/cl/49590 (5500c9ce27128ab26aa23bafddce7dd512ce72ea), fixed last Friday by https://golang.org/cl/55032 (057a34a281a52b474184614ac63b808974e22549).  Was the trybot run based on tip in between those two commits?

**Comment by dsnet** [comment]
It's a try-boy run and seems to still be happening very close to tip.

On https://build.golang.org/, you [can see it happen on 17fa5a7](https://build.golang.org/log/d3515f0f6c947d0e29489496fa8307a8af67c953), so it seems flaky.

**Comment by Quasilyte** [comment]
Executed trybots in https://go-review.googlesource.com/#/c/go/+/63490/ and TestAtomicStop failed on Darwin again.
Second trybots run does not caused it to happen (patch set 3 passes without any code changes).

https://storage.googleapis.com/go-build-log/11750b86/darwin-amd64-10_11_83471050.log
```
--- FAIL: TestAtomicStop (1.09s)
	signal_test.go:324: iteration 0: output 
	signal_test.go:324: iteration 1: output lost signal on iterations: 6
	signal_test.go:331: iteration 1: lost signal
	signal_test.go:324: iteration 2: output 
	signal_test.go:324: iteration 3: output 
	signal_test.go:324: iteration 4: output 
	signal_test.go:324: iteration 5: output 
	signal_test.go:324: iteration 6: output 
	signal_test.go:324: iteration 7: output 
	signal_test.go:324: iteration 8: output 
	signal_test.go:324: iteration 9: output 
```

**Comment by tombergan** [comment]
One more: https://storage.googleapis.com/go-build-log/4f6f7c65/darwin-amd64-10_11_491fb13d.log

```
--- FAIL: TestAtomicStop (1.14s)
	signal_test.go:324: iteration 0: output 
	signal_test.go:324: iteration 1: output 
	signal_test.go:324: iteration 2: output lost signal on iterations: 6
	signal_test.go:331: iteration 2: lost signal
	signal_test.go:324: iteration 3: output 
	signal_test.go:324: iteration 4: output 
	signal_test.go:324: iteration 5: output 
	signal_test.go:324: iteration 6: output 
	signal_test.go:324: iteration 7: output 
	signal_test.go:324: iteration 8: output 
	signal_test.go:324: iteration 9: output 
```

**Comment by bradfitz** [comment]
More:
https://storage.googleapis.com/go-build-log/39f9af3b/linux-386_d50c7f23.log

**Comment by bradfitz** [comment]
Oh, Ian's CL isn't submitted.
