### ISSUE TITLE
cmd/compile: improve DCE when inlining empty functions

### ISSUE THREAD

**Issue by josharian** [golang/go#21440]
```go
package p

func f(e interface{}) {}

func g() {
	var s string
	f(s)
}
```

`g` compiles to:

```
"".g STEXT nosplit size=41 args=0x0 locals=0x18
	0x0000 00000 (y.go:5)	TEXT	"".g(SB), NOSPLIT, $24-0
	0x0000 00000 (y.go:5)	SUBQ	$24, SP
	0x0004 00004 (y.go:5)	MOVQ	BP, 16(SP)
	0x0009 00009 (y.go:5)	LEAQ	16(SP), BP
	0x000e 00014 (y.go:5)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x000e 00014 (y.go:5)	FUNCDATA	$1, gclocals·f207267fbf96a0178e8758c6e3e0ce28(SB)
	0x000e 00014 (y.go:7)	MOVQ	$0, ""..autotmp_4(SP)
	0x0016 00022 (y.go:7)	MOVQ	$0, ""..autotmp_4+8(SP)
	0x001f 00031 (y.go:8)	MOVQ	16(SP), BP
	0x0024 00036 (y.go:8)	ADDQ	$24, SP
	0x0028 00040 (y.go:8)	RET
```

It should compile to nothing. In general, when inlining an empty function, all that should remain is evaluating its arguments for side-effects.

Related but slightly different: Replace the body of g with `f("abc")`. Then `g` compiles to nothing, but we still emit a vestigial `"abc"` string symbol.

This kind of code commonly shows up as a result of disabling features with build tags. See #21424.

cc @gstupp

**Comment by martisch** [comment]
partially related - reminds me of 
cmd/compile: compiler generates calls to empty functions #4563
cmd/compile: inlining of empty functions computes arguments #4204

**Comment by randall77** [comment]
Also related, issue #13095. It also requires the ability to get rid of autotmps that are assigned to but are otherwise unused.

**Comment by AlexRouSg** [comment]
There are cases where you would want the arguments to not be evaluated, like when calling a debug function that slows the entire program that you don't want to be running in release builds. e.g

`Log.Assert(SomeLongBlockingFunction())`

**Comment by gstupp** [comment]
It would be great to be able to disable features with empty functions!

Please keep in mind that for a scenario as described in #21424 the statement given by @griesemer is really necessary because it allows me to depend on this functionality (in that specific case to define the scope of support to constant expressions, assert that this is the idiomatic way to solve the problem and guarantee future support).

**Comment by randall77** [comment]
This is fixed by CL 38746.
Thanks @mundaym !

@josharian We still do emit the go.string."abc" symbol.  Maybe open a different issue for that.
The string symbol will be removed by the linker so I'm not too worried about it.
