### ISSUE TITLE
Bootstrapping fails on MIPS64

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#21444]
### What version of Go are you using (`go version`)?
`go version devel +c8e9fd5 Mon Aug 14 01:38:08 2017 +0000 linux/mips64`

From go version go1.8.3 linux/amd64 `GOOS=linux GOARCH=mips64 ./bootstrap.bash`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="mips64"
GOBIN="/home/myusername/go/bin"
GOEXE=""
GOHOSTARCH="mips64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/home/myusername/go"
GOTOOLDIR="/home/myusername/go/pkg/tool/linux_mips64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -mabi=64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build798056280=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

`"$GOTOOLDIR"/dist env -p`
```
CC="gcc"
CC_FOR_TARGET="gcc"
GOROOT="/home/myusername/go"
GOBIN="/home/myusername/go/bin"
GOARCH="mips64"
GOOS="linux"
GOHOSTARCH="mips64"
GOHOSTOS="linux"
GOTOOLDIR="/home/myusername/go/pkg/tool/linux_mips64"
PATH="/home/myusername/go/bin:/home/myusername/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

### What did you do?
I tried to run `GOROOT_BOOTSTRAP=~/go-linux-mips64-bootstrap ./all.bash`. It was failing. I ran `./all.bash --dist-tool` and then started manually going through the commands in `./make.bash`.

I ran `CC=$CC_FOR_TARGET "$GOTOOLDIR"/go_bootstrap install $GO_FLAGS -gcflags "$GO_GCFLAGS" -ldflags "$GO_LDFLAGS" -v std cmd || echo "Oh noes! $?"`

### What did you expect to see?
A successful completion of `go_bootstrap install std cmd`.

### What did you see instead?
`go_bootstrap install std cmd` failed with exit code 2 and the following output:
```
...
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
unicode
sync
io
unicode/utf8
math
bytes
bufio
syscall
strconv
reflect
time
internal/poll
os
strings
fmt
sort
path/filepath
flag
log
cmd/internal/src
encoding/binary
cmd/internal/objabi
cmd/internal/goobj
cmd/internal/sys
container/list
path
math/bits
debug/dwarf
compress/flate
hash
hash/adler32
compress/zlib
debug/gosym
debug/elf
debug/macho
debug/pe
debug/plan9obj
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
cmd/vendor/golang.org/x/arch/x86/x86asm
io/ioutil
regexp/syntax
regexp
text/tabwriter
archive/tar
cmd/internal/objfile
hash/crc32
archive/zip
cmd/addr2line
compress/bzip2
compress/gzip
compress/lzw
container/heap
container/ring
context
crypto
crypto/subtle
crypto/cipher
math/rand
crypto/aes
crypto/des
math/big
crypto/sha512
crypto/hmac
crypto/internal/cipherhw
crypto/md5
internal/syscall/unix
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/base64
encoding/pem
internal/nettrace
internal/singleflight
go/token
go/scanner
go/ast
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
crypto/rsa
crypto/ecdsa
crypto/x509/pkix
os/exec
go/parser
go/printer
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/crypto/chacha20poly1305
vendor/golang_org/x/crypto/curve25519
database/sql/driver
cmd/cgo
database/sql
encoding
encoding/ascii85
encoding/base32
encoding/csv
encoding/gob
unicode/utf16
encoding/json
runtime/cgo
# runtime/cgo
_cgo_export.c:2:20: fatal error: stdlib.h: No such file or directory
compilation terminated.
encoding/xml
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/text/transform
vendor/golang_org/x/text/unicode/bidi
vendor/golang_org/x/text/unicode/norm
vendor/golang_org/x/text/secure/bidirule
net/url
mime
mime/quotedprintable
net/http/internal
vendor/golang_org/x/net/idna
text/template/parse
go/constant
text/template
go/format
go/types
go/doc
go/build
text/scanner
hash/crc64
hash/fnv
html
html/template
go/internal/gccgoimporter
go/internal/gcimporter
go/internal/srcimporter
image/color
go/importer
image
image/color/palette
index/suffixarray
internal/cpu
internal/syscall/windows
internal/syscall/windows/registry
internal/syscall/windows/sysdll
runtime/debug
runtime/trace
testing
image/internal/imageutil
image/draw
image/gif
image/jpeg
image/png
internal/testenv
internal/trace
math/cmplx
runtime/pprof
net/internal/socktest
os/signal
runtime/pprof/internal/profile
runtime/race
testing/internal/testdeps
testing/iotest
testing/quick
vendor/golang_org/x/text/secure
vendor/golang_org/x/text/unicode
cmd/api
cmd/internal/dwarf
cmd/internal/obj
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/internal/bio
cmd/compile/internal/types
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/compile/internal/ssa
cmd/asm
cmd/compile/internal/syntax
cmd/internal/gcprog
cmd/compile/internal/test
cmd/internal/browser
cmd/cover
cmd/dist
cmd/doc
go build cmd/compile/internal/ssa: /home/myusername/go/pkg/tool/linux_mips64/compile: signal: killed
cmd/fix
cmd/go/internal/cfg
cmd/go/internal/str
cmd/go/internal/base
cmd/go/internal/buildid
cmd/go/internal/load
cmd/go/internal/doc
cmd/go/internal/help
cmd/go/internal/work
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/cmdflag
cmd/go/internal/tool
cmd/go/internal/version
cmd/gofmt
cmd/go/internal/envcmd
cmd/go/internal/clean
cmd/go/internal/generate
cmd/go/internal/list
cmd/go/internal/run
cmd/go/internal/test
cmd/go/internal/vet
cmd/link/internal/ld
cmd/nm
cmd/objdump
cmd/pack
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/vendor/github.com/google/pprof/profile
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/x86
cmd/vendor/github.com/google/pprof/internal/plugin
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/link
cmd/vendor/github.com/google/pprof/internal/measurement
cmd/vendor/github.com/google/pprof/internal/graph
cmd/vendor/github.com/google/pprof/internal/binutils
cmd/vendor/github.com/google/pprof/internal/report
cmd/vendor/github.com/google/pprof/internal/symbolz
cmd/vendor/github.com/google/pprof/third_party/svg
cmd/vendor/github.com/google/pprof/internal/proftest
cmd/vet/internal/cfg
cmd/vet/internal/whitelist
cmd/vet
Oh noes! 2
```

**Comment by cherrymui** [comment]
> ```
> # runtime/cgo
> _cgo_export.c:2:20: fatal error: stdlib.h: No such file or directory
> ```

This seems there is no system headers installed. Either install them, or try setting CGO_ENABLED=0.

> ```
> go build cmd/compile/internal/ssa: /home/myusername/go/pkg/tool/linux_mips64/compile: signal: killed
> ```

This is probably OOM-killed. How much memory does the machine have? Try set up some swap, or set GOGC=50 or some smaller number (and expect longer time to finish).

**Comment by firelizzard18** [comment]
I installed `libc6-dev` and got the following result (partial build?):
```
cmd/addr2line
runtime/cgo
# runtime/cgo
In file included from /usr/include/stdlib.h:25:0,
                 from _cgo_export.c:2:
/usr/include/features.h:323:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.
cmd/api
cmd/asm
cmd/compile/internal/ssa
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/link
go build cmd/compile/internal/ssa: /home/firelizzard/go/pkg/tool/linux_mips64/compile: signal: killed
cmd/nm
cmd/objdump
cmd/pack
cmd/vet
Oh noes! 2
```

**Comment by firelizzard18** [comment]
I'm on an EdgeRouter Lite, which has <0.5GB of RAM. I'll try `GOGC=50`

**Comment by AlexRouSg** [comment]
You need gcc-multilib if you are crosscompiling

**Comment by davecheney** [comment]
That's unlikely to be enough, IME on a 64 bit system you need 768mb of ram
per core.

**Comment by firelizzard18** [comment]
Oh joy. Is there any way I can cross-compile the entire toolchain from a different machine? Would it be safe to use `go_bootstrap` as if it were just `go`?

I'm trying to do this because I want to build `github.com/elastic/beats/tree/master/packetbeat` for the ERL but that requires some CGO stuff and I've had a hell of a time trying to get my gentoo box's GCC to cross-compile for MIPS.

I tried installing `gcc-multilib`, but installing things isn't working well because of some weird BS with aptitude and the fact that my system has an ever so slightly newer version of libc and libc-bin than the newest available MIPS version of libc6-dev (lots of complaints about wanting `some-pkg ...deb7u10` but having `some-pkg ...deb7u11`).

**Comment by cherrymui** [comment]
> ```
> # runtime/cgo
> In file included from /usr/include/stdlib.h:25:0,
>                  from _cgo_export.c:2:
> /usr/include/features.h:323:26: fatal error: bits/predefs.h: No such file or directory
> compilation terminated.
> ```
I think you also need linux-headers or like. (Or, set CGO_ENABLED=0)

> I'm on an EdgeRouter Lite, which has <0.5GB of RAM. I'll try GOGC=50

I have a Loongson 2E with 512 MB RAM. I set up ~1 GB swap, and it works even with default GOGC=100.

**Comment by AlexRouSg** [comment]
@firelizzard18 
https://golang.org/doc/install/source

> To cross-compile a bootstrap tool chain from source, which is necessary on systems Go 1.4 did not target (for example, linux/ppc64le), install Go on a different system and run bootstrap.bash.

**Comment by davecheney** [comment]
On Tue, Aug 15, 2017 at 9:01 AM, Ethan Reesor <notifications@github.com>
wrote:

> Oh joy. Is there any way I can cross-compile the entire toolchain from a
> different machine? Would it be safe to use go_bootstrap as if it were
> just go?
>
That probably won't have the right cgo parts enabled. I don't know for
sure, I've never tried.

**Comment by ianlancetaylor** [comment]
If there are still issues here, they are better discussed on a forum, not on the issue tracker.  See https://golang.org/wiki/Questions .
