### ISSUE TITLE
strings: fix Title function

### ISSUE THREAD

**Issue by GwynethLlewelyn** [golang/go#21442]
First of all: no, this is **not** #6801!

Instead, I just wanted to point out that the current `strings.Title()` implementation is a 'quick & dirty' way of dealing with titles; it does not respect proper English rules for title naming (although it might be appropriate for _some_ languages, I don't know).

A suggestion was made on the [Go Cookbook](http://golangcookbook.com/chapters/strings/title/) to implement it thusly:

```
func properTitle(input string) string {
	words := strings.Fields(input)
	smallwords := " a an on the to "

	for index, word := range words {
		if strings.Contains(smallwords, " "+word+" ") {
			words[index] = word
		} else {
			words[index] = strings.Title(word)
		}
	}
	return strings.Join(words, " ")
}
```
This is a clever and neat trick, and could be used for other languages as well (ex. in Portuguese the `smallwords` would have to include " de do da dos das " but possibly exclude "a" since that is by coincidence also a definite article, etc.).
The authors of the Go Cookbook did not seem to add a suggestion here, so I'm doing it 🙂

**Comment by ianlancetaylor** [comment]
Can you give an example of an input that would change under your proposal?

CC @mpvl

**Comment by GwynethLlewelyn** [comment]
Sure, the best example is on the [Go Cookbook](http://golangcookbook.com/chapters/strings/title/) itself:

`strings.Title("welcome to the dollhouse!")` gives `Welcome To The Dollhouse!`

while

`properTitle("welcome to the dollhouse!")` gives `Welcome to the Dollhouse!`

which is grammatically correct (while the result from `strings.Title()` is not)

**Comment by bep** [comment]
As I suspect changing the existing `strings.Title` would be a hard sell, I wanted to point to a great third-party Go lib with both AP style and Chicago style titles:

https://godoc.org/github.com/jdkato/prose/transform

**Comment by ianlancetaylor** [comment]
Ah, I understand now.  No, I don't think we can or should change `strings.Title` in that way.  `strings.Title` acts as documented.  Changing it would make it a different function, and would break backward compatibility.  I agree that the sort of function you describe is useful, but it's not `strings.Title`.  Also the function you describe is language-specific, and there are no such functions in the strings package.

Closing.

**Comment by GwynethLlewelyn** [comment]
I agree that `strings.Title` works exactly as described, it's just that the name of the function that is misleading! On the other hand, you're totally right that this is language-specific, and none of the other functions in `strings` have such a limitation (one thing is handling with runes — which _are_ language-specific but easy to handle — the other thing is handling with _grammar_, so I get your point!).
Aye, there are plenty of ways of doing it 'the right way' and while I hadn't come across the `prose` series of packages, implementing 'proper' title capitalisation is not exactly rocket science. Also, I now understand that 'Title Case' (which is what `strings.Title` implements...) may [mean something significantly different](https://www.snappysentences.com/sentence-case-v-title-case/) in the software development environment compared to the grammatical definition. So I should have done my research _before_ making a suggestion here! Sorry about that.
