### ISSUE TITLE
regexp: add examples for all methods on regex.Regexp

### ISSUE THREAD

**Issue by shoenig** [golang/go#21450]
Something I've been wanting to do for a while is provide complete example coverage for methods defined on regexp.Regex. There are 36 methods, 11 of which have examples. Unless this isn't desired, I'd like to finish the other 25.

**Comment by odeke-em** [comment]
All yours @shoenig, thank you!

**Comment by agnivade** [comment]
Thank you @cn007b for adding more examples. Here are some remaining ones for which I think examples would be good to have to keep it consistent with the other examples.

https://tip.golang.org/pkg/regexp/#Regexp.FindAllIndex
https://tip.golang.org/pkg/regexp/#Regexp.FindSubmatchIndex
https://tip.golang.org/pkg/regexp/#Regexp.ReplaceAll
https://tip.golang.org/pkg/regexp/#Regexp.NumSubexp
https://tip.golang.org/pkg/regexp/#Regexp.Longest

I think once these are done, we can close this bug. The remaining ones are just simple variants of other methods which already have examples.

**Comment by Windsooon** [comment]
@agnivade I created a PR for it. I didn't add an example for `Regexp.Longest()`. I think that is the default behavior for the RE module and I can't find a function to unset it.

**Comment by agnivade** [comment]
It's not the default. https://tip.golang.org/pkg/regexp/#Compile is leftmost-first. https://tip.golang.org/pkg/regexp/#CompilePOSIX is the one which is leftmost-longest.

**Comment by psampaz** [comment]
@agnivade #33489 #33497 #33490 cover all 5 missing examples

**Comment by agnivade** [comment]
All of the examples that I outlined have been submitted. I will go ahead and close this now. Thank you everyone who contributed to the examples.
