### ISSUE TITLE
missing or invalid package binary for binary-only package when  buildmode=plugin

### ISSUE THREAD

**Issue by jerrybean** [golang/go#21451]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/root/work/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work/go"
GORACE=""
GOROOT="/usr/local/go1.8.3"
GOTOOLDIR="/usr/local/go1.8.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build055567438=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

1. I have one file in /root/work/go/src/say named say.go
```golang
package say
import "fmt"
func Say(s string) string {
	return fmt.Sprintf("hello %s", s)
}
```

2. I try to build it to .a file `go build -i -o $GOPATH/pkg/linux_amd64/say.a`

3. change /root/work/go/src/say/say.go to 

``` golang
//go:binary-only-package

package say
```

4. another file /root/work/go/src/say/work/v1.go
```golang
package v1
import (
	"fmt"
	"say"
)
func SayToBob() {
	fmt.Println(say.Say("Bob"))
}
```

5. the main file /root/work/go/src/say/work/main.go
```golang
package main
import (
	"say/work/v1"
)
func main() {
	v1.SayToBob()
}
```

6. run main.go `go run  /root/work/go/src/say/work/main.go`
```
go run main.go
hello Bob
```
   that's right

7. but in fact, i need to build SayToBob as plugin to hot reload,run 
`go build -buildmode=plugin -o /root/work/go/src/say/work/v1/plugin.so /root/work/go/src/say/work/v1/v1.go`

`missing or invalid package binary for binary-only package say`

### What did you expect to see?
can build plugin

### What did you see instead?
can't build plugin
`missing or invalid package binary for binary-only package say`

did I do something wrong? thanks!

**Comment by ianlancetaylor** [comment]
In general don't run commands like `go build -i -o $GOPATH/pkg/linux_amd64/say.a`.  Instead, run `go install say`.

The error `binary-only package say` implies that some .go file in that directory has a comment `//go:binary-only-package`.

Closing because I don't think there is a Go bug here.  For questions about using Go, please see https://golang.org/wiki/Questions .

**Comment by twyvip** [comment]
I had the same problem
my golang version is 1.9.2
How can I solve this problem

**Comment by twyvip** [comment]
go build -buildmode=plugin -o test.so *.go
missing or invalid package binary for binary-only package

**Comment by twyvip** [comment]
hello jerrybean
Have you solved the problem

**Comment by twyvip** [comment]
hello jerrybean
Have you solved the problem
I had the same problem
my golang version is 1.9.2
How can I solve this problem
go build -buildmode=plugin -o test.so *.go
missing or invalid package binary for binary-only package

**Comment by ianlancetaylor** [comment]
@twyvip This issue is closed.  To ask questions, please use a forum; see https://golang.org/wiki/Questions.   Thanks.
