### ISSUE TITLE
build: dragonflybsd-amd64 random build failure

### ISSUE THREAD

**Issue by tdfbsd** [golang/go#21456]
### What version of Go are you using (`go version`)?
Go 1.8

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="dragonfly"

There is a random recurring build failure for the dragonflybsd builder. An example of this is in the builder log for 22cfe24aca80653b0e8efdd4a1aba1df00e8e72d:
 
crypto
encoding/base64
reflect
/tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/type.go:22:2: can't find import: "unicode"
crypto/sha1
go tool dist: FAILED: /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/pkg/tool/dragonfly_amd64/compile -pack -o /tmp/go-tool-dist-976677949/reflect/_go_.a -p reflect /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/deepequal.go /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/makefunc.go /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/swapper.go /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/type.go /tmp/workdir-host-dragonfly-amd64-tdfbsd/go/src/reflect/value.go: exit status 2
can't create /tmp/go-tool-dist-976677949/crypto/sha1/_go_.a: open /tmp/go-tool-dist-976677949/crypto/sha1/_go_.a: no such file or directory
can't create /tmp/go-tool-dist-976677949/unicode/_go_.a: open /tmp/go-tool-dist-976677949/unicode/_go_.a: no such file or directory
can't create /tmp/go-tool-dist-976677949/syscall/_go_.a: open /tmp/go-tool-dist-976677949/syscall/_go_.a: no such file or directory

I've been assuming that this was a problem with my build machine, but I'm raising the issue to find out if there's anything I can do to track this down

**Comment by ianlancetaylor** [comment]
Builder log is at https://build.golang.org/log/30f7def3977874b964826994148eb6d74e155fea .

How many processors does the builder machine have, as reported by `runtime.GOMAXPROCS()`?

The log doesn't make a lot of sense to me.  It seems that `/tmp/go-tool-dist-976677949` is disappearing while the build is going on.  But even then I don't understand why the reflect package would be built before the unicode package build is complete.

**Comment by tdfbsd** [comment]
GOMAXPROCS is 1

**Comment by tdfbsd** [comment]
Note that two builds after 22cfe24aca80653b0e8efdd4a1aba1df00e8e72d succeeded, so the random nature of this failure makes it difficult to troubleshoot.

**Comment by ianlancetaylor** [comment]
If `GOMAXPROCS` is 1, this is flag out peculiar.  It means that the unicode package must have completed building.  So how can we see, at the end of the log,

```
can't create /tmp/go-tool-dist-976677949/unicode/_go_.a: open /tmp/go-tool-dist-976677949/unicode/_go_.a: no such file or directory
```

**Comment by ianlancetaylor** [comment]
Hmmm, wait, "unicode" is missing from the dependencies of "reflect" in cmd/dist/deps.go.

**Comment by tdfbsd** [comment]
I see that 127 /tmp/go-tool-dist-* folders are hanging around. Aren't those supposed to be removed?

**Comment by ianlancetaylor** [comment]
@tdfbsd In the normal course of events, yes.  They will be left behind if cmd/dist crashes for some reason.

**Comment by ianlancetaylor** [comment]
I think I've convinced myself that https://golang.org/cl/55971 will fix the problem.  Let's try it and see.
