### ISSUE TITLE
build: TestBuildmodePIE failed on linux

### ISSUE THREAD

**Issue by choleraehyq** [golang/go#21452]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
use go 1.9 rc2 to compile go tip `58cb8a3c8fdc9b83cb8630f17d0ee641eb0327cc`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cholerae/gopath"
GORACE=""
GOROOT="/home/cholerae/gopath/go"
GOTOOLDIR="/home/cholerae/gopath/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build447838512=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
`GOROOT_BOOTSTRAP=/home/cholerae/gopath/go ./all.bash`

### What did you expect to see?
all tests passed.

### What did you see instead?
```
--- FAIL: TestBuildmodePIE (2.15s)
	go_test.go:312: running testgo [build -buildmode=pie -o /tmp/gotest833919002/main /tmp/gotest833919002/main.go]
	go_test.go:325: standard error:
	go_test.go:326: # command-line-arguments
		/home/cholerae/test/go/pkg/linux_amd64_shared/runtime/cgo.a(_go_.o): object is [linux amd64 devel +adc28cb1e0 Fri Aug 11 18:00:53 2017 +0000 X:framepointer] expected [linux amd64 devel +58cb8a3c8f Tue Aug 15 07:19:25 2017 +0000 ]
		/home/cholerae/test/go/pkg/linux_amd64_shared/runtime/cgo.a(asm_amd64.o): object is [linux amd64 devel +adc28cb1e0 Fri Aug 11 18:00:53 2017 +0000] expected [linux amd64 devel +58cb8a3c8f Tue Aug 15 07:19:25 2017 +0000 ]
		
	go_test.go:335: go [build -buildmode=pie -o /tmp/gotest833919002/main /tmp/gotest833919002/main.go] failed unexpectedly: exit status 2
FAIL
FAIL	cmd/go	67.917s
```

**Comment by ALTree** [comment]
Same on my Linux system.

I bisected this to b7c600d6ba8828dbdc6a047aac240d40b4fc44a7

cc @hirochachacha @ianlancetaylor

**Comment by hirochachacha** [comment]
I didn't change anything about Linux.
Could you compile a trivial program with buildmode=pie ?
e.g. 
```
$ cat main.go
package main; func main() { print("hello") }
$ go build -buildmode=pie -o main main.go
```

Thank you.

**Comment by ALTree** [comment]
```
$ cat test.go
package main

func main() {
	print("hello")
}

$ gotip version
go version devel +583a941d4e Tue Aug 15 10:10:42 2017 +0000 linux/amd64

$ gotip build -buildmode=pie test.go
# command-line-arguments
/home/alberto/go/pkg/linux_amd64_shared/runtime/cgo.a(_go_.o): object is [linux amd64 devel +ae24c167c7 Mon Aug 14 14:52:00 2017 +0200 X:framepointer] expected [linux amd64 devel +583a941d4e Tue Aug 15 10:10:42 2017 +0000 ]
/home/alberto/go/pkg/linux_amd64_shared/runtime/cgo.a(asm_amd64.o): object is [linux amd64 devel +ae24c167c7 Mon Aug 14 14:52:00 2017 +0200] expected [linux amd64 devel +583a941d4e Tue Aug 15 10:10:42 2017 +0000 ]
```

Ah, it bisected to your change because that's the one that *added* that PIE test... but `-buildmode=pie` was already broken. I checked out the commit before yours and it gives the same error.

**Comment by hirochachacha** [comment]
I see. It seems the compiler should recompile dependent packages if it is necessary, instead of error. I don't know where that logic is defined though.

**Comment by hirochachacha** [comment]
Anyway, thank you for your confirmation.

**Comment by ALTree** [comment]
Oh, bad news: `build -buildmode=pie` also fails with go1.9rc2

```
$ gotip version
go version go1.9rc2 linux/amd64

$ cat test.go
package main

func main() {
	print("hello")
}

$ gotip build -buildmode=pie test.go
# command-line-arguments
/home/alberto/go/pkg/linux_amd64_shared/runtime/cgo.a(_go_.o): object is [linux amd64 devel +ae24c167c7 Mon Aug 14 14:52:00 2017 +0200 X:framepointer] expected [linux amd64 go1.9rc2 ]
/home/alberto/go/pkg/linux_amd64_shared/runtime/cgo.a(asm_amd64.o): object is [linux amd64 devel +ae24c167c7 Mon Aug 14 14:52:00 2017 +0200] expected [linux amd64 go1.9rc2 ]

```

**Comment by ALTree** [comment]
Cleaning out manually the old pkgs works as a workaround to fix `all.bash`. Anyway it would be nice if the toolchain could figure this out by itself.

**Comment by ianlancetaylor** [comment]
I think this is basically a bug in cmd/go: it doesn't take relevant flag settings into account when deciding whether it needs to rebuild a package.

Until cmd/go is fixed we can fixed `TestBuildmodePIE` by using an `-installsuffix` option in the test.

**Comment by jessfraz** [comment]
I can fix the test

**Comment by ianlancetaylor** [comment]
I see the problem, it's in cmd/go.  Will send a CL.
