### ISSUE TITLE
Reverse floating point code samples to match text

### ISSUE THREAD

**Issue by filoxo** [golang/go#21467]
I'll admit that I stared at the FlowControls samples too long before realizing they're reversed in relation to the text before it. Reversing them to match the text would be great! ([example](https://github.com/golang/tour/pull/285/commits/12d1c551955211eb73a6004b0debf772d8a2b9af)) Thanks!

**Comment by mvdan** [comment]
You probably want to open this issue over at the tour repository.

**Comment by filoxo** [comment]
🤦 yes, that was me intension... Not s how you're I overlooked this. Thanks!
