### ISSUE TITLE
Proposal for init method

### ISSUE THREAD

**Issue by ZaniaDeveloper** [golang/go#21468]
Hello,

I'm suggesting about an `init` method which initialize a struct type:
```go
package my_initialized_type

type AType struct {
    ExportedField string

    privateField int
}

func (v *AType) init() {
    if v.ExportedField == "value" {
        v.privateField = 1234
    } else {
        v.privateField = 4321
    }
}

func (v *AType) Get() int { return v.privateField }
```

The `init` method will be called when an instance if created. I think that sometimes it's useful non-exported field can be initialized without another user of the package have to call a method explicitly.

Like this:
```go
package main

import "fmt"
import "my_initialized_type"

func main() {
    val := &my_initialized_type.AType{ExportedField:"value"}
    fmt.Println("Value=", val.Get())
}
```

I know it can be resolved with a function used as a constructor like this:
```go
package my_initialized_type

func NewValue(exportedField) *AType {
    res := &AType{ExportedField:exportedField}
    if res.ExportedField == "value" {
        res.privateField = 1234
    } else {
        res.privateField = 4321
    }

    return res
}
```

But it's more fun to create an instance by struct initialization than by a function, plus the lib user can do like he want, if he want initialize empty with `new(my_initialized_type.AType)`, it's simpler than `my_initialized_type.NewValue("")`.

The `init` method is a true constructor.

**Comment by jaredborner** [comment]
Having an "init" method for a type is already quite simply (https://play.golang.org/p/6x52RIJ_rd)

Furthermore, this would allow the "init" method to explicitly override values given for struct initialization which is completely non obvious.
