### ISSUE TITLE
x/crypto/ssh: no simple way to implement efficient keep alives

### ISSUE THREAD

**Issue by nhooyr** [golang/go#21478]
In order to implement SSH Keep Alives, I'm currently doing something like this:

(conn is the net.Conn underlying the ssh client)
```go
func keepAlive(cl *ssh.Client, conn net.Conn, done <-chan struct{}) error {
        const keepAliveInterval = time.Minute
	t := time.NewTicker(keepAliveInterval)
	defer t.Stop()
	for {
		deadline := time.Now().Add(keepAliveInterval).Add(15 * time.Second)
		err := conn.SetDeadline(deadline)
		if err != nil {
			return errors.Wrap(err, "failed to set deadline")
		}
		select {
		case <-t.C:
			_, _, err = cl.SendRequest("keepalive@golang.org", true, nil)
			if err != nil {
				return errors.Wrap(err, "failed to send keep alive")
			}
		case <-done:
			return nil
		}
	}
}
```

However, this is inefficient in that it will always send a request after the interval, even if some other packet was received over the connection confirming that the connection is alive. I'd like a way to send keep alives only if no data has been received over the connection in X amount of time.

I could wrap the net.Conn with my own interface to implement this (create a timer and reset it every time some data is read, and if the timer hits 0, send a keep alive) but I think this is a feature that deserves a easy to use solution as part of the library.

**Comment by dsnet** [comment]
Related to #19338.

**Comment by hanwen** [comment]
can you point to some data that shows that the extra keepalive package is a performance problem?

**Comment by nhooyr** [comment]
Not sure if it's a significant problem, it's a matter of efficiency. I'll admit it's somewhat a premature optimization but network roundtrips are expensive and if we can easily avoid one, we should.

**Comment by hanwen** [comment]
network roundtrips are really cheap. Did you know that every SSH read actually incurs a network roundtrip due to flow control?

**Comment by nhooyr** [comment]
Nope, I did not know that. However, I still think we should add this because SSH is often used over a very poor connection where those extra roundtrips could become significant.

I know this is all highly hypothetical and I don't have the time right now to benchmark or get data on this so if you don't find my argument convincing, feel free to close.
