### ISSUE TITLE
x/tools/cmd/godoc: https://golang.org/{AUTHORS,CONTRIBUTORS} and other plain text files at root are giving 500 Internal Server Error

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21484]
The following URLs used to work okay, but are currently giving 500 Internal Server Error status code and no body:

- https://golang.org/AUTHORS
- https://golang.org/CONTRIBUTORS
- https://golang.org/LICENSE
- https://golang.org/PATENTS
- https://golang.org/CONTRIBUTING.md
- https://golang.org/README.md
- etc.

```
$ curl -i 'https://golang.org/AUTHORS'
HTTP/1.1 500 Internal Server Error
X-Cloud-Trace-Context: dc96cd82ab16c303d2cfe037e26c2a7d
Date: Wed, 16 Aug 2017 23:24:14 GMT
Content-Type: text/html
Server: Google Frontend
Content-Length: 0
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,35"

$ 
```

However, they work okay in plain text mode:

- https://golang.org/AUTHORS?m=text
- https://golang.org/CONTRIBUTORS?m=text

These domains are fine at this time:

- https://beta.golang.org/AUTHORS
- https://tip.golang.org/AUTHORS

**Comment by ianlancetaylor** [comment]
@shantuo

**Comment by shurcooL** [comment]
All those URLs are working okay now, so I understand this issue has been resolved.
