### ISSUE TITLE
cmd/internal/dwarf: emit DW_AT_artificial for synthetic functions

### ISSUE THREAD

**Issue by heschik** [golang/go#21483]
The compiler generates various functions and there isn't any indication that they weren't handwritten. The case where this came up was the top-level package init function, which is written out by `fninit` in `cmd/compile/internal/gc/init.go`. There are other generated functions (hashes come to mind) that could be marked. @aarzilli, @derekparker, is this of interest to Delve?

**Comment by aarzilli** [comment]
We could use it to filter the output of `funcs`, but I don't think it's useful and I don't remember any user complaining about this. Do you have something in mind?

**Comment by ianlancetaylor** [comment]
Marking as Go1.11 to fix or decide that it is unnecessary and close.

**Comment by heschik** [comment]
Seems unnecessary. Closing.
