### ISSUE TITLE
cmd/compile: allow inlining simple functions that use for.

### ISSUE THREAD

**Issue by OneOfOne** [golang/go#21490]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.8, 1.9rc2, master.

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
https://play.golang.org/p/jGYlhKirNX

```
go build -gcflags "-m -m"
```

### What did you expect to see?
```
./blah.go:8:6: can inline Fnv32
```

### What did you see instead?

```
./blah.go:8:6: cannot inline Fnv32: unhandled op for
./blah.go:18:6: can inline Fnv32Inline ..........
```

I feel like this a dup and I apologize if it is, my searching skills have failed me.

@josharian @dr2chase  @randall77

**Comment by ALTree** [comment]
That's #14768.

**Comment by mvdan** [comment]
Dup indeed.
