### ISSUE TITLE
cmd/compile/internal/ssa: optimize ARM SSA rules with indexed MOVB/MOVH

### ISSUE THREAD

**Issue by benshi001** [golang/go#21492]
There are indexed MOVW used  for ARM.

	{name: "MOVWloadidx", argLength: 3, reg: gp2load, asm: "MOVW"},                   // load from arg0 + arg1. arg2=mem
	{name: "MOVWloadshiftLL", argLength: 3, reg: gp2load, asm: "MOVW", aux: "Int32"}, // load from arg0 + arg1<<auxInt. arg2=mem
	{name: "MOVWloadshiftRL", argLength: 3, reg: gp2load, asm: "MOVW", aux: "Int32"}, // load from arg0 + arg1>>auxInt, unsigned shift. arg2=mem
	{name: "MOVWloadshiftRA", argLength: 3, reg: gp2load, asm: "MOVW", aux: "Int32"}, // load from arg0 + arg1>>auxInt, signed shift. arg2=mem
	{name: "MOVWstoreidx", argLength: 4, reg: gp2store, asm: "MOVW"},                   // store arg2 to arg0 + arg1. arg3=mem
	{name: "MOVWstoreshiftLL", argLength: 4, reg: gp2store, asm: "MOVW", aux: "Int32"}, // store arg2 to arg0 + arg1<<auxInt. arg3=mem
	{name: "MOVWstoreshiftRL", argLength: 4, reg: gp2store, asm: "MOVW", aux: "Int32"}, // store arg2 to arg0 + arg1>>auxInt, unsigned shift. arg3=mem
	{name: "MOVWstoreshiftRA", argLength: 4, reg: gp2store, asm: "MOVW", aux: "Int32"}, // store arg2 to arg0 + arg1>>auxInt, signed shift. arg3=mem

But corresponding ones for MOVB/MOVH are absent. Adding and using them can save bytes.

**Comment by daiweisong** [comment]
别他妈的发了傻逼




发自网易邮箱大师
On 08/28/2017 11:42, GopherBot wrote:

Change https://golang.org/cl/58450 mentions this issue: cmd/compile: optimize ARM with more efficient MOVB/MOVBU/MOVH/MOVHU
