### ISSUE TITLE
golang error bug

### ISSUE THREAD

**Issue by v8lab** [golang/go#21499]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOOS="darwin"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/--4N-9A4-8

### What did you expect to see?

i think, it shoud print 1

**Comment by bontibon** [comment]
[Go FAQ: Why is my nil error value not equal to nil?](https://golang.org/doc/faq#nil_error)

**Comment by ALTree** [comment]
Yep, not a bug. This is explained in detail in the FAQ entry linked by @bontibon. Closing the issue.

**Comment by v8lab** [comment]
@bontibon thanks
