### ISSUE TITLE
golang.org/x/crypto/ssh marshal/unmarshal errors

### ISSUE THREAD

**Issue by tobowers** [golang/go#21491]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### What operating system and processor architecture are you using (`go env`)?
amd64 darwin

### What did you do?
This program ( https://gist.github.com/tobowers/8118cd1a668926c40909639a2b2af195
 ) generates the output:
```
$ go run marshal.go 
2017/08/17 09:53:16 error unmaarshaling: ssh: unmarshal error for field Key of type Certificate: unsupported type: ssh.PublicKey
exit status 1
```
play.golang apparently doesn't have x/crypto/ssh so I couldn't have it runnable on there.

### What did you expect to see?
I expect an immediate call to Unmarshal from a marshaled certificate to succeed without error.

### What did you see instead?
The program errors with the output above.

**Comment by tobowers** [comment]
hmmm.... changing the code to: https://gist.github.com/tobowers/7df99bac5fb2cb30bb06e4ce4d540364#file-marshaled-fixed-go-L40-L48 works.

It's confusing that you need to use ParsePublicKey and then type assert into a certificate to have this work.

**Comment by hanwen** [comment]
ssh.Unmarshal is the mirror ssh.Marshal. 

If you want to send a clarification of the SSH package docs, that would be great.
