### ISSUE TITLE
crypto/x509: ParseCertificate fails for ECDSA certificate, gives asn1 unmarshal error

### ISSUE THREAD

**Issue by vickiniu** [golang/go#21502]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.8.3 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vd/th9v9qw93c3d2mb24ghf4q_r0000gn/T/go-build785283138=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

Decoding ECDSA certificate (fail)
https://play.golang.org/p/wHYxSA6JrN

Note: decoding this certificate using `openssl x509 -in devCA.crt -text -noout` produces correct output.

Decoding RSA certificate (success)
https://play.golang.org/p/fvcX76vbY5

### What did you expect to see?
Return `ok=true` from `certPool.AppendCertsFromPEM` on decoding ECDSA certificate

### What did you see instead?
```
asn1: structure error: tags don't match (6 vs {class:0 tag:16 length:247 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ObjectIdentifier @3
```

**Comment by slrz** [comment]
Your cert looks fishy. Replacing it with another one (ECDSA too, of course) leads to successful decoding.
https://play.golang.org/p/bf0nMxF5tw

**Comment by vickiniu** [comment]
These are the commands we used to generate the cert:

```
openssl ecparam -name prime256v1 -genkey -param_enc explicit -out dev-ca.key
openssl req -new -sha256 -x509 -days 10000 -key dev-ca.key -out dev-ca.crt -subj "/C=US/ST=California/L=San Francisco/O=Chain/OU=development/CN=Development Root Certificate Authority"
```

It looks like the `param_enc explicit` flag in `openssl ecparam` is what causes the error.

**Comment by jakob223** [comment]
Go seems to assume that an ECDSA curve is always going to be a named curve.

Named curves are only one of 3 valid ways of specifying a curve, according to [RFC 5480](https://tools.ietf.org/html/rfc5480#section-2.1.1), but **the only way to do so for x.509 certificates**:
>    The parameter for id-ecPublicKey is as follows and MUST always be
>    present:
> 
>    ECParameters ::= CHOICE {
>     namedCurve         OBJECT IDENTIFIER
>     -- implicitCurve   NULL
>     -- specifiedCurve  SpecifiedECDomain
>    }
>    **-- implicitCurve and specifiedCurve MUST NOT be used in PKIX.**
>    -- Details for SpecifiedECDomain can be found in [X9.62].
>    -- Any future additions to this CHOICE should be coordinated
>    -- with ANSI X9.

The failing certificate uses `param_enc explicit`, which translates to using a specified curve when encoding the `AlgorithmIdentifier`. 

`openssl` perhaps shouldn't be willing to generate this certificate. That said, maybe go should have a better error in the case of encountering such a certificate?

**Comment by jakob223** [comment]
https://go-review.googlesource.com/c/57050 makes a more useful error message here.
