### ISSUE TITLE
`go clean && go install` and `go get -u` not building new binaries

### ISSUE THREAD

**Issue by crunk1** [golang/go#21505]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9rc2_cl165246139 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/crunkleton/.go"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build429487363=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
Doing development on our project github.com/GoogleCloudPlatform/compute-image-tools/daisy.
I tried `go clean && go install` from the daisy src directory.
Also tried `go get -u github.com/GoogleCloudPlatform/compute-image-tools/daisy`

### What did you expect to see?
The daisy binary in .go/bin to be updated.

### What did you see instead?
The binary wasn't being installed in .go/bin. (At first, I was stuck at an old binary from Aug 1. Then I deleted that binary and tried to rebuild. No new binary was placed in .go/bin.)

**Comment by bradleyfalzon** [comment]
`github.com/GoogleCloudPlatform/compute-image-tools/daisy` is a non-main package `daisy`, I think you meant to use the path of the main package `github.com/GoogleCloudPlatform/compute-image-tools/daisy/daisy` (note the additional subdirectory).

**Comment by crunk1** [comment]
Yep, that seems like the issue. We reorganized the codebase, so that got changed underneath me.

**Comment by davecheney** [comment]
The -v flag to go build or go install will print out the name of each
package as it is compiled. I recommend this as a super cheap way of
discovering how much is being built (or rebuilt)
