### ISSUE TITLE
runtime: usleep() does not work on Linux 386

### ISSUE THREAD

**Issue by pvoicu** [golang/go#21518]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3 linux/386

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
It is internal function to the runtime package, so I cannot provide a test code to reproduce.
To reproduce, someone needs to compile any application for linux/386 and strace the second thread

### What did you expect to see?
pselect6(0, NULL, NULL, NULL, {0, 20000}, 0) = 0 (Timeout)

### What did you see instead?
I see pselect6(0, NULL, NULL, NULL, {0, 0}, 0) = 0 (Timeout)

runtime.usleep always sets the nanosecond parameter to 0. The fix is at line https://go.googlesource.com/go/+/master/src/runtime/sys_linux_386.s#103, it should be "MOVL	AX, 4(SP)".

**Comment by ALTree** [comment]
This change was not originally in go1.8, but it was cherrypicked here: https://go-review.googlesource.com/c/44002

It's also in go1.9rc2.

cc @aclements

**Comment by pvoicu** [comment]
This is the CL for the proposed fix: https://go-review.googlesource.com/c/56850

**Comment by aclements** [comment]
Re-opening for cherry-pick to release branch.

**Comment by aclements** [comment]
Cherry-pick to 1.8.4 is issue #21520.

Thanks for finding this @pvoicu!

**Comment by ALTree** [comment]
go1.9 cherrypick was merged: http://golang.org/cl/56891, so I'm closing this.

**Comment by tsuna** [comment]
Thanks for fixing this bug, I was going crazy over `runtime.sysmon` taking up to 50% of the CPU cycles in my profiles as of late, and I thought it was something stupid we did in our own code that caused it.  Today I realized the issue didn't exist in go1.8.2 and earlier, and didn't exist in go1.9 either, and traced it back to this issue.
