### ISSUE TITLE
types in `src/runtime/symtab.go` not show from nm

### ISSUE THREAD

**Issue by ibigbug** [golang/go#21514]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.7.6 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/someuser/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cy/b0lrq2m55js29jlf_hhm4xtc0000gn/T/go-build759502881=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

1. `$ cat symtab.go`

```
package main

import "fmt"

func main() {
        fmt.Println("vim-go")
}
```

2. `$ go build symtab.go`
3. `$ go tool nm main  | grep findfunc`

### What did you expect to see?

Something like `findfuncbucket` should be seen as defined in https://github.com/golang/go/blob/master/src/runtime/symtab.go#L498

### What did you see instead?

```
 47a00 T runtime.findfunc
  36e960 R runtime.findfunctab
```

Sorry for bothering guys, I'm just not sure if what I'm missing to see the types defined in the `src/runtime/symtab.go` via `nm` or is it by design? Or if is, how to inspect these types via debug tools like `nm` or `gdb` ?

Thanks!

**Comment by randall77** [comment]
`nm` isn't the tool you're looking for.  It just lists functions, not types.
The type information is in the DWARF debugging sections.  You could try a tool that can read DWARF, maybe debugger like [delve](https://github.com/derekparker/delve).
What are you trying to do, anyway?  Why do you need to read types (and runtime ones, at that) out of a binary?

**Comment by ibigbug** [comment]
ohh really.  thanks @randall77 I think you are right, `nm` is not for that.

Actually at first I used `gdb` and 

```(gdb) info types runtime.bucket
All types matching regular expression "runtime.bucket":

File go:
struct runtime.bucket;
typedef runtime.bucketType;
struct struct { F uintptr; p unsafe.Pointer; b *runtime.bucket };
```

I'm almost certainly that `bucket` is a `type` defined in https://github.com/golang/go/blob/master/src/runtime/mprof.go#L48 

but when I try

```
(gdb) info types findfunc
All types matching regular expression "findfunc":
```

I get nothing, should I also get the `findfuncbucket` right?

**Comment by ianlancetaylor** [comment]
Closing because there is nothing to fix.
