### ISSUE TITLE
x/crypto/ocsp: "OCSP response contains bad number of certificates" error

### ISSUE THREAD

**Issue by joeshaw** [golang/go#21527]
Currently in the `ocsp.ParseResponseForCert` function is a block:

```go
	if len(basicResp.Certificates) > 1 {
		return nil, ParseError("OCSP response contains bad number of certificates")
	}
```

I can't find any justification for this check (it dates back to @rsc's initial commit).  [RFC 6960 section 4.2.1](https://tools.ietf.org/html/rfc6960#section-4.2.1) says,

```
   The value for response SHALL be the DER encoding of
   BasicOCSPResponse.

   BasicOCSPResponse       ::= SEQUENCE {
      tbsResponseData      ResponseData,
      signatureAlgorithm   AlgorithmIdentifier,
      signature            BIT STRING,
      certs            [0] EXPLICIT SEQUENCE OF Certificate OPTIONAL }

   The value for signature SHALL be computed on the hash of the DER
   encoding of ResponseData.  The responder MAY include certificates in
   the certs field of BasicOCSPResponse that help the OCSP client verify
   the responder's signature.  If no certificates are included, then
   certs SHOULD be absent.
```

This leads me to believe that more than one cert is valid here, and in fact the http://sureseries-ocsp.cybertrust.ne.jp/OcspServer responder sends certs chaining up to a root.

The Go OCSP implementation doesn't verify the response certificate to a root, it just checks the signature against the issuer.  (Is this sufficient?  OpenSSL [seems to do more](https://wiki.openssl.org/index.php/Manual:Ocsp(1)#OCSP_Response_verification.).)  But it seems like it shouldn't be an error to receive more than one certificate; it could simply do the check it currently does against the first one in the list.

/cc @agl

**Comment by joeshaw** [comment]
Sorry, misattributed the initial commit to Russ.  He just moved it to a subrepo from the Go repo.  Initial commit was https://github.com/golang/go/commit/8286ee4c5b94d5245cae6a369cb3e417b1d622ee by Adam.

**Comment by kreichgauer** [comment]
> This leads me to believe that more than one cert is valid here

That is correct, the Go ocsp package is just a bit limited and doesn't have support for more complex responses. From https://godoc.org/golang.org/x/crypto/ocsp#ParseResponse:

> ParseResponse parses an OCSP response in DER form. It only supports responses for a single certificate.

/cc @agl

**Comment by joeshaw** [comment]
> From https://godoc.org/golang.org/x/crypto/ocsp#ParseResponse:
> 
> > ParseResponse parses an OCSP response in DER form. It only supports responses for a single certificate.

I interpreted this to mean a single certificate sent in the request.  Not a single OCSP response certificate.

**Comment by joeshaw** [comment]
@agl @FiloSottile I would love to get this in for 1.11 if the approach makes sense.  It causes us to get "OCSP response contains bad number of certificates" for any certificates that use cybertrust.ne.jp's various OCSP responders.  For example, https://www.superchoice.bet/

**Comment by joeshaw** [comment]
🤦‍♂️ duh, I forgot this was in x/crypto and doesn't follow the release process.  Still, please take a look once the 1.11 fury has died down!

**Comment by robstradling** [comment]
Just FYI, crt.sh now has this fix, and all of the "bad number of certificates" errors have disappeared.
