### ISSUE TITLE
runtime: usleep() does not work on Linux 386 [Go 1.8]

### ISSUE THREAD

**Issue by aclements** [golang/go#21520]
Go 1.8.3 included a change to use pselect6, but it was broken (https://golang.org/cl/44002).

[CL 56850](https://golang.org/cl/56850) fixes this.

/cc @pvoicu @ALTree @ianlancetaylor

**Comment by rsc** [comment]
CL 56850 OK for Go 1.8.5.

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 56850](https://golang.org/cl/56850) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:50 UTC
