### ISSUE TITLE
tools/cmd/getgo: cannot find GOROOT directory: /usr/local/go

### ISSUE THREAD

**Issue by phoebeclarke** [golang/go#21532]
Tried to use one line installer on mac, installed correctly, but running "go version" produces the following error:

go: cannot find GOROOT directory: /usr/local/go

**Comment by ALTree** [comment]
Dup of  #21271?

**Comment by spf13** [comment]
definitely a dupe. @phoebeclarke what OS are you using? It would be nice to know if it's the same or different from the existing reports. If you can share with us the output of `go env` (on the original issue) that would be very helpful.
