### ISSUE TITLE
doc: Install from source doc at golang.org/doc inconsistent with install output

### ISSUE THREAD

**Issue by rajathagasthya** [golang/go#21534]
### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
Installed Go from source after a `git clone` (in addition to a system Go).
```bash
$ cd ~/dev/go/src
$ ./make.bash
```

### What did you expect to see?
The docs at https://golang.org/doc/install/source#install says:

> If all goes well, it will finish by printing output like:

```
ALL TESTS PASSED

---
Installed Go for linux/amd64 in /home/you/go.
Installed commands in /home/you/go/bin.
*** You need to add /home/you/go/bin to your $PATH. ***
```
### What did you see instead?
It's really minor, but after a source install I don't see the `*** You need to add /home/you/go/bin to your $PATH. ***` line. Either there is a bug printing the line or the doc is outdated? I was making some standard library changes and building the source, but using my system go `/usr/local/bin/go` to test changes instead of the newly-built binary and wondering why the changes weren't applied :) The line helps to avoid this sort of beginner mistake, especially when you have multiple Go versions installed. 

Thanks!

**Comment by cznic** [comment]
> The docs at https://golang.org/doc/install/source#install says:

They say to execute `all.bash`, *not* `make.bash`.

**Comment by rajathagasthya** [comment]
Oh yes, my bad. Sorry for the false alarm! Please feel free to close the issue (although I think printing it for `./make.bash` wouldn't hurt too).
