### ISSUE TITLE
misc/cgo: testcshared leaves behind temp files

### ISSUE THREAD

**Issue by josharian** [golang/go#21531]
At `go version devel +def0ec1fba Fri Aug 18 21:17:40 2017 -0700 darwin/amd64`, run all.bash. I expect no new files to be present. But in `misc/cgo/testcshared/pkg/darwin_amd64_testcshared`, there are new several .h and .a files. I suspect the recently rewritten go version of the tests is failing to clean up some temporary files.

cc @bcmills

**Comment by bcmills** [comment]
@nadiasvertex ported that test to Go. (I did the same for the santizer tests.)

**Comment by nadiasvertex** [comment]
I will look at this.

**Comment by alexbrainman** [comment]
> I will look at this.

This is already taken care of in https://go-review.googlesource.com/#/c/go/+/57270/

Alex
