### ISSUE TITLE
x/tools/cmd/present: -base switch results in "can't evaluate field"

### ISSUE THREAD

**Issue by kaihendry** [golang/go#21549]
I want to modify present's default style sheet. AFAICT I need to override the base path.

### What version of Go are you using (`go version`)?

go version go1.9rc2 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

http://ix.io/zkH

### What did you do?

```
git clone https://github.com/golang/tools.git
cd tools/cmd/present
go build
curl -O https://s.natalian.org/2017-08-22/test.slide
./present -base .
curl http://127.0.0.1:3999/test.slide
```

### What did you expect to see?

test.slide render using locally available static/ & template/ dirs.

### What did you see instead?

```
2017/08/22 12:07:16 template: slides.tmpl:58:19: executing "root" at <$s.HTMLAttributes>: can't evaluate field HTMLAttributes in type present.Section
2017/08/22 12:07:16 http: multiple response.WriteHeader calls
```

**Comment by ianlancetaylor** [comment]
CC @campoy

**Comment by blainsmith** [comment]
I am experiencing the same thing, but using the default styles.

**Comment by schaki** [comment]
I'm getting the same error on `go version go1.9 darwin/amd64`, and without any options passed in. Seems to be working correctly on `go1.8.3`

**Comment by abuschmann** [comment]
I'm getting the same error message running go1.8.3 linux/amd64 on Fedora 26:
```
/usr/bin/go get golang.org/x/tools/cmd/present
/usr/bin/present
```
Regards

**Comment by abuschmann** [comment]
It works, if I install **go1.9.linux-amd64.tar.gz** from **https://golang.org/dl/** instead of using go and present as distributed by fedora.

**Comment by myself659** [comment]
the same as above with the go version go1.8 windows/amd64

**Comment by jonaz** [comment]
This happened to me when i had newer templates checked out and an older version of present tool installed. I just removed the present command go get -u the latest present command and then it worked. I have go 1.9 installed with arch linux packages.

**Comment by arxdsilva** [comment]
same here on a simple example, go 1.9.2 installed

**Comment by kaihendry** [comment]
I just retried and it's working now. :grin:  Must have been some mismatch with the templates.
