### ISSUE TITLE
 undefined: ArchInst

### ISSUE THREAD

**Issue by feifanyajun** [golang/go#21542]
![image](https://user-images.githubusercontent.com/19487214/29495817-6a123432-85f9-11e7-8db2-42277561aeb7.png)
![image](https://user-images.githubusercontent.com/19487214/29495819-7ed7497a-85f9-11e7-9120-0391f91e1519.png)
![image](https://user-images.githubusercontent.com/19487214/29495821-8c61fe78-85f9-11e7-8c5c-ad1cdd3267c0.png)
![image](https://user-images.githubusercontent.com/19487214/29495874-7f330d7c-85fa-11e7-95eb-2e31fff260fe.png)

**Comment by ALTree** [comment]
Hi,

this looks like a Delve issue, not a Go issue. This is the Go issue tracker, the Delve issue tracker is here: https://github.com/derekparker/delve/issues

It looks like the issue you're seeing has already been reported:

https://github.com/derekparker/delve/issues/656
https://github.com/derekparker/delve/issues/20

I'm closing this issue. You can comment on or follow the Delve issues I linked above.
