### ISSUE TITLE
x/net/http2: cancelling a request from the Client doesn't release its stream

### ISSUE THREAD

**Issue by BenPope** [golang/go#21543]
This is the second half of issue #21229 closed with change https://golang.org/cl/53250.  The leak isn't fixed because the stream is still referenced by `rl.activeRes`.

#### What did you do?

* An http2 client makes a request to a server with a cancellable context
* The server sends a response but waits for `req->Context().Done()`
* The client cancels its request context
* The server cleans up its stream
* The client leaks its stream

#### System details

```
go version go1.8.3 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ben/development"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build098570469=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.8.3 X:framepointer
uname -sr: Linux 4.12.4-041204-generic
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:printing-9.20160110ubuntu5-amd64:printing-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.24-9ubuntu2.2) stable release version 2.24, by Roland McGrath et al.
gdb --version: GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1.1) 7.12.50.20170314-git
```
@tombergan

**Comment by tombergan** [comment]
Note to self, related to #22413: It is confusing to me that transport.go has both `cc.streams` and `rl.activeRes`. The only purpose of the later is to check if we have any idle streams. I believe `rl.activeRes` is redundant and can be removed, to be replaced with `cc.streams`.

Then, we need to be more careful about when a stream is removed from `cc.streams`. The simplest approach, also suggested in #22413, is the following: a stream is removed from `cc.streams` atomically with the user calling Response.Body.Close(), except if the request fails or if Response.Body is noBody, in which case, the stream should be removed immediately before RoundTrip returns.
