### ISSUE TITLE
x/tools/cmd/goimports: does not import when package name has an underscore (and different path)

### ISSUE THREAD

**Issue by celrenheit** [golang/go#21545]
Hello,

### What version of Go are you using (`go version`)?
`go version go1.8.3 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```go
package main

func main() {
	grpc_prometheus.EnableHandlingTimeHistogram()
}
```

### What did you expect to see?

```go
package main

import "github.com/grpc-ecosystem/go-grpc-prometheus"

func main() {
	grpc_prometheus.EnableHandlingTimeHistogram()
}
```

### What did you see instead?

It did not import the package.

After digging a bit, I found that it is coming from [here]( https://github.com/golang/tools/blob/master/imports/fix.go#L880) and [here](https://github.com/golang/tools/blob/master/imports/fix.go#L904).

goimports currently compares the last two components while removing the hyphens but should it handle underscores too ?

**Comment by heschik** [comment]
The underscore in `grpc_prometheus` is unusual for a Go package, and generally we want to encourage directory names to match package names. Given that, and the age of this issue, I'm going to close this. Please comment if you're still having trouble.
