### ISSUE TITLE
x/build: automatically start building subrepos for new release branches

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#21556]
currently, a new release tag entity must be manually added to datastore before subrepos will be built and displayed on build.golang.org's index page.

this should be automated.

cc @rsc @broady

**Comment by dmitshur** [comment]
See also #34097.

This has been automated by now. When we released Go 1.14, we didn't have to do any manual work to get `release-branch.go1.14` to show up on [build.golang.org](https://build.golang.org), and for `release-branch.go1.12` to get hidden (/cc @cagedmantis @toothrot).

It was done in [CL 194643](https://golang.org/cl/194643) (/cc @bradfitz). Closing.
