### ISSUE TITLE
cmd/compile: for small objects, use constants directly instead of copying from statictmp

### ISSUE THREAD

**Issue by randall77** [golang/go#21561]
```
func f() []int {
	return []int{7}
}
```
generates:
```
0x001d 00029 (tmp1.go:3)  LEAQ    type.[1]int(SB), AX
0x0024 00036 (tmp1.go:4)  MOVQ    AX, (SP)
0x0028 00040 (tmp1.go:4)  CALL    runtime.newobject(SB)
0x002d 00045 (tmp1.go:4)  MOVQ    8(SP), AX
0x0032 00050 (tmp1.go:4)  MOVQ    "".statictmp_0(SB), CX
0x0039 00057 (tmp1.go:4)  MOVQ    CX, (AX)
```
Note that the `7` is written by loading from a readonly global and writing to the slice. We should just use a
```
MOVQ $7, (AX)
```
for the last 2 lines.
Up to some small constant in size, emitting the constants explicitly instead of copying them from a statictmp is better.

**Comment by josharian** [comment]
We do this a few places already. IIRC, the cutoff we have used for "up to some small constant in size" is whether it is SSA-able.

**Comment by cuonglm** [comment]
> Change https://golang.org/cl/199280 mentions this issue: `internal/reflectlite: add type mirror with reflect test`

Ops, this is wrong reference.
