### ISSUE TITLE
sync/atomic: atomic documentation does not mention mips

### ISSUE THREAD

**Issue by cetinsert** [golang/go#21573]
### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using (`go env`)?
`linux-mips`

### What did you do?
I was reading the [documentation on `atomic`](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) and realized there is no mention of MIPS. Does that mean `atomic` just works on 32-bit MIPS?

**Comment by cetinsert** [comment]
https://github.com/golang/go/blob/master/src/sync/atomic/asm_mipsx.s

---

What does this imply? Is `atomic` implemented in terms of Go's runtime-internal code?

**Comment by ianlancetaylor** [comment]
It means there are no known bugs on MIPS systems.

Note that the Go project does not use the issue tracker for questions.  Please ask questions in a forum as described at https://golang.org/wiki/Questions .  Thanks.

Closing because there is nothing to do.
