### ISSUE TITLE
spec: iota doesn't always reset when const appears in the source

### ISSUE THREAD

**Issue by as** [golang/go#21575]
https://golang.org/ref/spec#Iota

The spec states: ```[iota] is reset to 0 whenever the reserved word const appears in the source and increments after each ConstSpec.``` but this is not true if a constant named iota is declared in the package scope. The spec refers to ```source``` as if the behavior is independent of scope.

### What did you do?
https://play.golang.org/p/BNovrxyrr-

### What did you expect to see?
1 2 3

### What did you see instead?
5 5 5

**Comment by griesemer** [comment]
You are declaring a new iota constant which shadows the predeclared iota. Don't do that.
Working as intended.
