### ISSUE TITLE
bytes: Examples missing for some functions

### ISSUE THREAD

**Issue by clebs** [golang/go#21570]
The `bytes` package has examples in most functions, but some are missing.

I would like to contribute with examples for the `bytes` package for my first contribution and get some experience.

**Comment by griesemer** [comment]
Please go ahead, no need to ask for permission. Fine to mention this issue in the commits.

**Comment by clebs** [comment]
Thank you!! I thought about just going ahead, but I think it is wise to always at least talk to someone first.
I am on it.

**Comment by clebs** [comment]
Added tests at:
https://go-review.googlesource.com/c/go/+/58030
