### ISSUE TITLE
runtime: add mul intrinsic for overflow checks

### ISSUE THREAD

**Issue by martisch** [golang/go#21588]
*This is neither a language change nor introducing or changing a public api but discussing a runtime implementation detail.*

# Motivation
Profiling over production programs reveals that growslice and makemap are hot functions (even outside the malloc part). I am working on to improve their performance and correctness for go1.10.

One part of these functions is at least one check for ```len > _MaxMem/elemSize``` which contains a costly division and needs a previous check for ```elemSize != 0```.

(Update: the check can also have variants like ```len*elemSize > _MaxMem-smallAmount``` or ```roundup(len*elemSize) > _MaxMem``` with an overflow check like ```uintptr(size) > maxSliceCap(elemSize)``` before that in the general case involves a division ) 

We have resorted to switches with constant divisions in growslice to improve performance for common cases. This introduces branch mis predicts and a larger function size which is bad for icaches.

Elsewhere we use maxSliceCap with precomputed values (```_MaxMem/elemSize```) which introduces cache misses, uses additional memory and only works for small element sizes.

An alternative to the above optimizations that avoids data cache lookups and a division is to check ```len*elemSize > _MaxMem```. Care needs to be taken that  len*elemSize does not overflow.

To be able to check overflow quickly and safely i propose the following:

# Proposal
Add a new unexported runtime function runtime.mul:
```
func mul(a, b uint) (uint, bool) {
	return a * b, b != 0 && a > ^uint(0)/b
}
```

The function can be used like:

```
if n, overflow := mul(len, elemSize); overflow || n > _MaxMem {
   panic("Does not fit into Memory")
}
```

Let the compiler recognize runtime.mul as an intrinsic and replace it with optimized inline instructions where possible.

On architectures that provide overflow/carryflags this can be a mul and setting overflow according to the flag. Otherwise use the provided generic implementation. (Note that a*b is always returned also in the generic implementation to match optimizations in machine code.)

Thereby we can eliminate maxSliceCap and shrink the switch cases without loss of (much) performance but better branch prediction and cache use and shrinking the functions away from special cases again.

# Possible future directions and ideas for later extra proposals
* add a similar function for add (the name is already taken in the runtime namespace) or just optimize overflow checks for adds better if this is not already the case
* if runtime.mul provides nice code and performance improvements after evaluation of the implementation and use cases we could add such a function to math(.Bits) (and just let the compiler do the existing optimization to that name). Note that math.Bits are already intrinsics. 
* add detection of generic overflow checking in the ssa backend such that any overflow checking code is optimized

If the introduction of the above function and optimization looks ok i would like to work on implementing it and then replace existing runtime codepaths that would benefit from the new function.

/cc @khr @josharian @ianlancetaylor @stemar94

**Comment by rasky** [comment]
Related: #6815

**Comment by griesemer** [comment]
Independent of the merits of this proposal, why does this need to be in the runtime? Why not math/bits (or analogous)?

**Comment by rasky** [comment]
Also related: #18616 (search for carry)

**Comment by martisch** [comment]
@griesemer: As far as i know currently runtime can only import runtime, unsafe and runtime/internal/... not math. Since everything depends on runtime we would create an import cycle if we use math.mul in runtime. (https://github.com/golang/go/blob/master/src/cmd/go/internal/load/pkg.go)
Not using math in runtime e.g. avoids the issue of introducing a math import which could have inits now or in the future that do not play well with runtime not having fully initialized.

Being runtime only also avoids introducing a new public api for now and runtime.mul can be easily deleted again or changed since it is private to the runtime.

If we find it works well with runtime we can use the then existing compiler support to discuss a public api in another proposal.

**Comment by robpike** [comment]
Why not put the _Maxmem check in there as well?

**Comment by martisch** [comment]
@robpike i think keeping mul simple leaves it more generally applicable to other cases of overflow checking at the same time as being used for _Maxmem checks.

Not all checks in runtime are against _Maxmem but can also be _Maxmem-someAmount. Where someAmount is know to be smaller than _Maxmem. Some uses round up len*elemSize before checking against _Maxmem. These cases could be easier to cover by the mul even when not directly comparing against _Maxmem.

```
if n, overflow := mul(len, elemSize); overflow || n > _MaxMem-someAmount {
   panic("Does not fit into Memory")
}
```

**Comment by josharian** [comment]
Seems unobjectionable to add such a runtime function, although it should probably go in runtime/internal/sys, with the other runtime intrinsics.

If we decide to add something like it to math/bits as well, we might decide to give the runtime flavor looser semantics for performance (like we have done with other runtime intrinsics that also appear in math/bits). FWIW, I recently wanted math/bits to have something like `Mul128(x, y int64) (lo, hi int64)` for use with math/rand.

Longer term, though, it seems perhaps better to fix this either via:

* adding [u]int128 to the language (happy to write more about this if you want)
* adding arbitrary precision integers to the language (#19623)

Note that with either of these, we should be able to get equivalent performance, with enough compiler help. (1) In the arbitrary precision case, the compiler could in theory recognize that the integer is in use only in one expression, which bounds its range, and replace it under the hood with a 128 bit version. (2) Working with a 128 bit multiply, the compiler can recognize that the top half of a multiply is being checked against 0, so it can substitute a pure overflow check there.

**Comment by randall77** [comment]
Sounds ok to me.  I think our experience with using CTZ and friends in the runtime first before providing it generally in math/bits worked well.  It would be nice to replicate that experience.
