### ISSUE TITLE
spec: clarify that nil in a type switch is not a type

### ISSUE THREAD

**Issue by ainar-g** [golang/go#21580]
The language specification seems inconsistent about whether `nil` is a type. [It's not mentioned as a predeclared type](https://golang.org/ref/spec#Predeclared_identifiers), and instead has its own category of "Zero value"; throughout the specification, there are mentions of `nil` as a value. But in the [section on type switches](https://golang.org/ref/spec#Type_switches) there is this quote:

>The type in a case may be `nil`; that case is used when the expression in the TypeSwitchGuard is a `nil` interface value. (…)

This sentence seems to imply that `nil` is a type. It might be better to reword this into something like

>The <ins>identifier</ins> in a case may be `nil`; (…)

On a side note, other parts of the type switch section might need a rewrite as well. `case nil` seems rather problematic, because while other cases are checking types, `case nil` is a value check, as illustrated by the switch-to-if-else example, which kinda goes against the very first sentence of the section, "A type switch compares types rather than values.".

**Comment by griesemer** [comment]
A type switch switches on the runtime type stored in an interface variable; that runtime type is a value if you will. It's that value that is compared against nil.

I'll try to reformulate the nil case slightly. But I think the rest can stand as the intent is clear and trying to be overly precise here doesn't make it clearer, only makes it harder to read.

**Comment by griesemer** [comment]
PS: With "runtime type" I meant the dynamic type.
