### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tzohxo** [golang/go#21584]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.5

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
debian 8

### What did you do?
go get
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

done
### What did you see instead?

.gvm/pkgsets/go1.5/global/src/github.com/mattn/go-shellwords/util_posix.go:17: e                                                                             err.Stderr undefined (type *exec.ExitError has no field or method Stderr)

**Comment by tzohxo** [comment]
im trying to setup mirai to be a hacker pls help

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by tzohxo** [comment]
dick
