### ISSUE TITLE
syscall: constant overflows int for mips compile

### ISSUE THREAD

**Issue by yinheli** [golang/go#21596]
https://github.com/golang/go/blob/0b0cc4154e1defed07e73ca1304b9a68c7134577/src/syscall/zerrors_linux_mips.go#L1441

32bit system, int max value: 0x7fffffff (2147483647)

**Comment by cherrymui** [comment]
@yinheli what is the problem? Do you have any program that fails to compile due to this?

The constant itself is ok, because it is an untyped integer instead of int.

**Comment by yinheli** [comment]
@cherrymui  I'm using `github.com/songgao/water` to create tun device on mips (openwrt), go build reports:

```
vendor/github.com/songgao/water/syscalls_linux.go:73: constant 2147767498 overflows int
vendor/github.com/songgao/water/syscalls_linux.go:88: constant 2147767500 overflows int
vendor/github.com/songgao/water/syscalls_linux.go:93: constant 2147767502 overflows int
vendor/github.com/songgao/water/syscalls_linux.go:103: constant 2147767499 overflows int
```

env:
```
go version : 1.8.3

build env
GOOS=linux GOARCH=mips
```

https://github.com/songgao/water/blob/6b639456fceabd469cc76f5f4cec653b0cb7ce14/syscalls_linux.go#L86

You mean i have to convert the constant value to uint ?
thanks, i'll try to and do some tests

**Comment by ianlancetaylor** [comment]
It should normally work to change the request parameter of `ioctl` to be `uint`.  That's how the implementations in golang.org/x/sys/unix work.

Closing because I don't think there is anything to change in the main Go repo.
