### ISSUE TITLE
1.9\pkg\tool\windows_amd64\compile.exe: Access is denied.

### ISSUE THREAD

**Issue by gfoxiii** [golang/go#21608]
use powershell run as administrator , and setup golang 1.9 

> git clone -b release-branch.go1.9 https://github.com/golang/go.git ./1.9
> cd 1.9/src/
> make.bat

...

`
go install cmd/compile: open D:\workspace\github.com\go\1.9\pkg\tool\windows_amd64\compile.exe: Access is denied.
`

after that , I have try this

> clean.bat

> all.bat

...

`
go install cmd/compile: open D:\workspace\github.com\go\1.9\pkg\tool\windows_amd64\compile.exe: Access is denied.
`

#### System details

```
go version go1.9 windows/amd64
GOARCH="amd64"
GOBIN="D:\workspace\github.com\go\1.9\bin"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="D:\workspace\go"
GORACE=""
GOROOT="D:\workspace\github.com\go\1.9"
GOTOOLDIR="D:\workspace\github.com\go\1.9\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Rex\AppData\Local\Temp\go-build638822695=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 windows/amd64
gdb --version: GNU gdb (GDB) 7.9.1
```

**Comment by alexbrainman** [comment]
@gfoxiii I cannot reproduce your problem. I used administrator account to clone go repo and build it with make,bat, and then used my own user account to run clean.bar and all.bat. All commands successfully run to completion. Can you provide exact steps for me to reproduce your problem, please?

And also explain why use different accounts to install and use Go? Should this even work?

Thank you.

Alex

**Comment by gfoxiii** [comment]
I don't know why the compile.exe Access denied. may this information can help.
windows 10 Creator, 
using the Network Account. 
I use the msi package to installed at last.
it works.
