### ISSUE TITLE
net/http: update docs for LocalAddrContextKey

### ISSUE THREAD

**Issue by sabey** [golang/go#21603]
### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?

r is a *http.Request
r.Context().Value(http.LocalAddrContextKey)

### What did you expect to see?
Listener Addr

### What did you see instead?
Connection Local Addr

I replied to an older closed issue, I'm not sure if it will be seen or not so I am posting again: https://github.com/golang/go/issues/18686
It seems that the functionality of LocalAddrContextKey has changed to what it was possibly intended to do, if so it should be mentioned in the patch notes

source change: https://go-review.googlesource.com/c/go/+/35490/10/src/net/http/server.go

**Comment by ianlancetaylor** [comment]
What do you mean by the "patch notes"?  Do you mean the contents of https://golang.org/doc/go1.9?  Or do you mean the documentation of `LocalAddrContextKey` at https://golang.org/pkg/net/http/#pkg-variables ?

**Comment by sabey** [comment]
sorry, I meant release notes

**Comment by ianlancetaylor** [comment]
Thanks.  Not every change is mentioned in the release notes, only the ones that seem important or significant.

CC @tombergan Should this change be in the release notes?

**Comment by sabey** [comment]
ya I figure, it was a shock to me however to find that I now had access to it

**Comment by elico** [comment]
@ianlancetaylor sure! it should be documented and also mentioned in the release notes.
It's important for many web server's for stats or the ability to apply ACL's for services that apply different policies for different networks their clients have access from\to.
For example I have a service which face two different public ip addresses behind nat(each has it's own router) and I want to apply rate limiting only for connections coming on a specific internal ip address without running two different listening ports\services.

**Comment by tombergan** [comment]
Here is the documentation for LocalAddrContextKey:

```go
// LocalAddrContextKey is a context key. It can be used in
// HTTP handlers with context.WithValue to access the address
// the local address the connection arrived on.
// The associated value will be of type net.Addr.
LocalAddrContextKey = &contextKey{"local-addr"}
```

@sabey, that looks correct to me? #18686 fixed a bug where LocalAddrContextKey used the listen address instead of the actual accepted address (where they could differ if the listen address was a wildcard). The fixed behavior seems to match the above comment.

As to whether or not this belongs in the release notes, I don't feel strongly and am fine with adding it. It seems roughly at the same level as the ServeMux change called out in the release notes:
https://golang.org/doc/go1.9#net/http

**Comment by sabey** [comment]
@tombergan looks correct
