### ISSUE TITLE
x/tools/godoc: godoc failing on aliases when viewing pkg/builtin

### ISSUE THREAD

**Issue by empijei** [golang/go#21601]
This is not really an issue with the language but with golang.org

### What did you do?
Visited https://golang.org/pkg/builtin/

### What did you expect to see?
The doc

### What did you see instead?
A build error

![2017-08-24_17 35 02_crop_screenshot](https://user-images.githubusercontent.com/1256049/29694839-07e1e4ee-88f4-11e7-9218-a9f5e2a7db39.png)

**Comment by sheepbao** [comment]
the same problem

**Comment by odeke-em** [comment]
I can reproduce this even locally and interestingly godoc at https://golang.org says it is running on Go1.9
<img width="1139" alt="screen shot 2017-08-24 at 9 50 56 pm" src="https://user-images.githubusercontent.com/4898263/29698943-5c74cba8-8916-11e7-8080-854fe51448f3.png">


/cc @broady @griesemer @adams-sarah

**Comment by odeke-em** [comment]
I can reproduce this even locally and interestingly godoc at https://golang.org says it is running on Go1.9
<img width="1139" alt="screen shot 2017-08-24 at 9 50 56 pm" src="https://user-images.githubusercontent.com/4898263/29698943-5c74cba8-8916-11e7-8080-854fe51448f3.png">

where the failing code in question is
<img width="570" alt="screen shot 2017-08-24 at 9 52 22 pm" src="https://user-images.githubusercontent.com/4898263/29698977-911f26aa-8916-11e7-8e73-ae245f6e9c48.png">


/cc @broady @griesemer @adams-sarah

**Comment by bradfitz** [comment]
Works for me running x/tools/cmd/godoc locally.

Seems like the golang.org godoc is built weird. Maybe it's a mix of versions. (one version godoc, one version GOROOT?).

**Comment by bradfitz** [comment]
@odeke-em, what do you mean by you can "reproduce this even locally". You can make it fail? I can't. It works for me: http://gdev.bradfitz.com:6060/pkg/builtin/#byte

**Comment by odeke-em** [comment]
Good proposition @bradfitz actually that seems plausible, now I just re-ran `go get golang.org/x/tools/cmd/godoc` and now it works alright locally. Perhaps we need to do the exact same thing on production.

**Comment by ianlancetaylor** [comment]
CC @griesemer @broady

**Comment by broady** [comment]
golang.org should be running on the 1.9 release branch for tools. it probably isn't, though. either i made a mistake when deploying, or the 1.9 release branch for tools is missing something from master.

looks good on tip.golang.org: https://tip.golang.org/pkg/builtin/

**Comment by broady** [comment]
Oh, it's very likely because GAE is on Go <1.9. godoc uses the standard library.

I'm not really sure what to do here, other than move from GAE standard to GAE flexible (or GKE), where we'd have more control over that.

**Comment by griesemer** [comment]
The built-in package is a fake package anyway and only here for documentation. It seems fine to me to go back to 1.8 with that file for godoc only. Maybe:
```
type byte uint8 // really: type byte = uint8, but alias declarations are not supported in 1.8
```

**Comment by myitcv** [comment]
Could be unrelated, but godoc.org doesn't appear to be returning results as before.

The search https://godoc.org/?q=os doesn't return the `os` package itself.

**Comment by myitcv** [comment]
Ditto for `strings` - I'll now amend my previous comment with other packages that suffer the same problem

**Comment by kevinburke** [comment]
@myitcv, can you open a separate ticket?

**Comment by broady** [comment]
Please file godoc.org issues over on https://github.com/golang/gddo

**Comment by broady** [comment]
Fixed https://golang.org/pkg/builtin/

**Comment by bradfitz** [comment]
> I'm not really sure what to do here, other than move from GAE standard to GAE flexible (or GKE), where we'd have more control over that.

I strongly believe we need to move off GAE standard. We need control of the Go version going forward. We will by definition always be ahead of App Engine, and using GAE standard precludes us from ever using new Go features in godoc. This will just keep biting us. We should move to Flex or GKE.
