### ISSUE TITLE
syscall.Sysctl unable to read 64-bit integers

### ISSUE THREAD

**Issue by xor-gate** [golang/go#21614]
### What version of Go are you using (`go version`)?

go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Users/jerry/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jerry/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s5/x8wc0jqd387_sg4py6tg6xq00000gn/T/go-build941632692=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```go
	memsize, _ := syscall.Sysctl("hw.memsize")
	fmt.Println(len(memsize))
```

### What did you expect to see?

Last byte not to be truncated (len 8)

### What did you see instead?

Last byte truncated (len 7)

Currently the syscall.Sysctl interface returns a string instead of the allocated byte array and chomps the last byte which only works for strings types. Probably we could add `syscall.SysctlBytes` to get the raw bytes. Or add `sysctl.SysctlUint64` which can also handle uint64 (and uint32) reads.

**Comment by ianlancetaylor** [comment]
The syscall package is kind of frozen.  The place for these features is golang.org/x/sys.  And that package already has a range of Sysctl functions which do what you want.  Closing.

**Comment by xor-gate** [comment]
Hi @ianlancetaylor, I must have overlooked this. It has indeed

```go
func SysctlUint64(name string, args ...int) (uint64, error){}
func SysctlRaw(name string, args ...int) ([]byte, error){}
```

Thanks for pointing out.
