### ISSUE TITLE
Compiler report an error with named embedded field initialization where embedded struct is from another package

### ISSUE THREAD

**Issue by chmike** [golang/go#21617]
### What version of Go are you using (`go version`)?
go1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64, Darwin

### What did you do?

Providing a struct literal with an embedded struct and named fields works without problem when the structs are declared next to each other. [See this playground example](https://play.golang.org/p/y9k2irrqqw)

But the compiler reports an error when the embedded class is from another package. See the following example. I can't test it on the playground since it reject github packages.

    package main
    
    import 	jwt "github.com/dgrijalva/jwt-go"
    
    type Claims struct {
    	Name string `json:"name"`
    	jwt.StandardClaims
    }
    
    var a = Claims{Name: "toto", jwt.StandardClaims: jwt.StandardClaims{Issuer: "localhost:8080"}}

I get the error message `unknown field 'jwt.StandardClaims' in struct literal of type Claims`.

There is no compiler error anymore when I remove the field names in the literal assigned to a:

    package main
    
    import jwt "github.com/dgrijalva/jwt-go"
    
    type Claims struct {
    	Name string `json:"name"`
    	jwt.StandardClaims
    }
    
    var a = Claims{"toto", jwt.StandardClaims{Issuer: "localhost:8080"}}

Is this a compiler "feature" (bug) or is there a reason for that ? 

This example was inspired by [this code example](https://dinosaurscode.xyz/go/2016/06/17/golang-jwt-authentication/). I suppose the author didn't use named fields because of the above problem.

### What did you expect to see?

I expected I could write a literal with named fields as in the playground example.
The behavior seam inconsistent. 

### What did you see instead?

The compiler rejects literals with named fields forcing me to define all fields of the literal. 

  [1]: https://play.golang.org/p/y9k2irrqqw

**Comment by ianlancetaylor** [comment]
The name of the field is `StandardClaims`, not `jwt.StandardClaims`.

Closing because there is no bug here.

**Comment by chmike** [comment]
Sorry, I don't understand. `jwt.StandardClaims` is an **embedded struct**. So I expect I must put the embedded **struct type name**. 

It works for `sync.Mutex`. https://play.golang.org/p/MRIeAFNKPT.

Why doesn't it work for `jwt.StandardClaims` ?

Is the error in the litteral with names where I should have written the field name`StandardClaims` instead of `jwt.StandardClaims` ?
