### ISSUE TITLE
Inconsistent channel behaviour

### ISSUE THREAD

**Issue by probablytom** [golang/go#21610]
### What version of Go are you using?

Many -- see table below. But the issue mostly relates to:

```
go version go1.9 windows/amd64
```

### Does this issue reproduce with the latest release?

It does.

### What operating system and processor architecture are you using?

Windows (in a VM), on AMD64 -- but tested on lots, see the table below.

`go env` for that Windows machine:

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\pjw\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

I wrote an experiment to see how Go handles chaining channels together, and got some strange results: I've found I can run it on some platforms without error, but get deadlocks on others with the same code. It appears that different platforms are treating channels differently, so the code runs differently on different machines.

The question I wanted to answer was: if a channel is returning a value taken from a second channel, does it take the value from the second one when it stops blocking, or when it begins to block?

Say we have the (*syntactically valid!*) Go code:

```
x <- <- y
```

which passes a value from channel `y` onto a channel `x`. 

Let's also say that channel `y` *already* has a value on it.
We're interested in having someone eventually read from channel 'x', but controlling whatever value is on it from somewhere else. One use case for this might be a channel which blocks to put values onto, but returns a default value (populated by some goroutine) if the channel would otherwise be empty. This would give us a channel which would block feeding it new values, but would return a default value rather than blocking when reading from it if empty.
	
We're going to read from channel `x`, which is blocking. Before we do, we change the value on channel `y`.

If we get the updated value on `y`, then we know that the values served by the first value are taken from the second only after blocking. If not, it should reach a deadlock, because we can't take a value off `y` earlier, meaning the two processes are both waiting! One for a value to be taken from `x`, and the other for a value to be put on `y`.

[There's a gist with the experiment I was putting together yesterday](https://gist.github.com/probablytom/e29dfdf0f2ea988b8c15a3a2e2c6eeb6), and here's also a [Go playground you can run it in -- where it'll fail](https://play.golang.org/p/zhGPdlECoC). Note that play.golang.org currently runs go1.8, but when it updates to go1.9, it might run! This is because different architectures and go versions seem to treat this code differently; see below.

### What did you expect to see?

*Consistency* across platforms. If I run this on OSX, play.golang.org, Windows or Linux I should see the same behaviour everywhere, and on all architectures. Whether the code blocks or doesn't is irrelevant, but blocking/not blocking *inconsistently* very much does.

### What did you see instead?

This:

| Architecture | OS                                                 | go1.8 | go1.9 |
| ------------- |:------------------------------- |:-----:|:------:|
| amd64           | play.golang.org (runs on NaCl)  | ❌ | (not yet updated) |
| amd64           | macOS 10.12.4                            | 👍 | 👍 |
| amd64           | Windows 10                                 | ❌ | ❌ |
| amd64           | Ubuntu 16.04                              | 👍 | 👍 |
| arm                | Raspbian                                      | ❌ | 👍 |

(Where 👍 means the code completes, and ❌ means that the code reaches a deadlock.)

So it seems that the *intended* behaviour might be that the code should run, but under go1.9, on Windows, it doesn't. 

### Addendum

The way I see it, this is about semantics about lazy or eager evaluation with Go's channels. If they're evaluated lazily -- and a value's taken off `y` by the goroutine in the code only when it can be passed to `y` -- this should complete execution. If they're evaluated eagerly -- and the value's taken off `y`, stored, and the goroutine blocks waiting to pass it down `x` -- then it should deadlock.

Why is the behaviour here inconsistent? Is there ambiguity about how Go should handle channels in this use case, or is there a bug in the runtime on different platforms? Given 1.9 is just out, and there's almost uniform behaviour here, I've filed this as a Windows bug on 1.9, but clearly there's plenty of inconsistency in 1.8 also. The change when running on a Raspberry Pi from go1.8 to go1.9 is concerning too.

---

Edit: explained what the emoji in the table meant.

**Comment by cznic** [comment]
AFAICT, (from mobile), the playground code *must* deadlock on line 25 in every Go version/platform. Also, the time.Sleep statement cannot IMO change anything.

**Comment by probablytom** [comment]
Yep, that's the behaviour expected by the people I've shown this too as well. That said...

![image](https://user-images.githubusercontent.com/821635/29714260-49d9eab2-899a-11e7-8c55-7a6cc07b0579.png)

![image](https://user-images.githubusercontent.com/821635/29714312-92fbd44e-899a-11e7-8dd6-8a486873de3b.png)

The behaviour you expect *is* exhibited on play.golang.org, but not on my macOS machine.

**Comment by martisch** [comment]
On my darwin/amd64 tip go i also get:
"We take values after blocking, meaning when values on a blocking channel are requested from another routine." for the playground example.

**Comment by probablytom** [comment]
@martisch having tested with both I think you'd see it either way, but is that go1.8 or go1.9?

**Comment by martisch** [comment]
Neither. It is go tip (9515610).

**Comment by probablytom** [comment]
Oh, sorry! I wasn't aware that existed and thought it was a typo. Thanks for confirming it on your machine.

**Comment by p-j-w** [comment]
I also see the behaviour as described in this issue too. Did some tests looking at cross compilation for other platforms...

Compiled on ARM and executed on ARM - DEADLOCK
Compiled on OSX and executed on ARM - NO DEADLOCK
Compiled on OSX and executed on OSX - NO DEADLOCK
Compiled on OSX and executed on Windows - DEADLOCK
Compiled on Windows and executed on Windows - DEADLOCK

I had expected the Windows version that was compiled using the OSX compiler to work with no deadlocks - but it didn't.  Seems quite inconsistent, and I don't know which behaviour should be classed as correct.

**Comment by randall77** [comment]
`time.Sleep(1000)` only sleeps 1000 *nanoseconds*.  Change it to 1e9 and it always deadlocks.
Whether `time.Sleep(1000)` is enough time for the child goroutine to run and block is platform-dependent.

I don't think there is any bug here.  Closing.

**Comment by probablytom** [comment]
*Of course*. Thank you!

**Comment by randall77** [comment]
p.s. Always use `time.Sleep(1 * time.Second)`, that way you won't accidentally make a unit mistake.

**Comment by cznic** [comment]
Uh, `<- y` @25 is rx, not tx, silly me.
