### ISSUE TITLE
expvar: Go 1.9 changes expvar.Map.Init()

### ISSUE THREAD

**Issue by nurse** [golang/go#21619]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/naruse/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kj/8_qvvl6n4fb_p9554p99wcd40000gn/T/go-build576752229=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```go
# a.go
package main

import (
	"expvar"
	"fmt"
)

func main() {
	m := new(expvar.Map).Init()
	m.Add("foo", 1)
	fmt.Printf("%v\n", m.Get("foo"))
	m.Init()
	fmt.Printf("%v\n", m.Get("foo"))
```

### What did you expect to see?
```
% /usr/local/Cellar/go/1.8.3/bin/go run a.go
1
<nil>
```

### What did you see instead?
```
/usr/local/Cellar/go/1.9/bin/go run a.go
1
1
```

### Note
The behavior is changed at https://github.com/golang/go/commit/fb0fe4277d8393110569b66944dffb4b2c2c1687#diff-e4fb3a2d42311171535831443fb1fca2R128.
I want a way to clear expvar.Map.
I used it in tests.

**Comment by ianlancetaylor** [comment]
CC @bcmills 

The `Init` method is not documented.  In Go 1.8, it would reset the `expvar.Map` to contain no entries.  In Go 1.9 it has changed to not do that.  The question is whether we should restore the old behavior, or whether we should document the new behavior.

**Comment by bcmills** [comment]
> The question is whether we should restore the old behavior, or whether we should document the new behavior.

Either seems fine by me.

I have a slight preference for documenting `Init` as deprecated and leaving it as a no-op: it seems odd for an `Init` method to be anything other than a no-op on an already-initialized map, it was never documented to begin with, and it is out-of-place in a Go API (where we tend to have either `New` functions that return already-initialized objects, or meaningful zero-values).

Perhaps I am missing something, but what's the use-case for the old behavior? (Why does the test need to clear the existing map rather than allocating a new one?)

**Comment by nurse** [comment]
> Why does the test need to clear the existing map rather than allocating a new one?

 There's no way to replace a map registered by expvar.NewMap.

**Comment by bcmills** [comment]
This is fixed at head. @ianlancetaylor, are there instructions somewhere on how to backport a patch to the 1.9.1 branch?

**Comment by ianlancetaylor** [comment]
I am in no way a git export, and I don't know of any written instructions.  What I do is, after the CL has been committed to tip,

```
git checkout release-branch.go1.9
git codereview change mybranchname
git cherry-pick <SHA>
git codereview change
git codereview mail
```

Here <SHA> is the git revision number for the change to tip.  The second `git codereview change` seems to be necessary to create the CL properly for the branch.

There is probably some more clever way to do this.

**Comment by nurse** [comment]
thanks!

**Comment by rsc** [comment]
OK for Go 1.9.2.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 62370](https://golang.org/cl/62370) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:08 UTC
