### ISSUE TITLE
doc/go1.9.html: should go/types.Package.Imports behavior change be included?

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21622]
_(It's not quite clear to me what's the criteria for inclusion of a change to warrant being mentioned in the release notes under the "Minor changes to the library" section (is it documented somewhere?), that's why this is a question.)_

https://godoc.org/go/types#Package.Imports changed behavior slightly. In Go 1.8, it was documented as:

> Imports returns the list of packages directly imported by pkg; the list is in source order. Package unsafe is excluded.
>
> [...]

In Go 1.9:

> Imports returns the list of packages directly imported by pkg; the list is in source order.
>
> [...]

So package unsafe is no longer excluded.

Should this be mentioned in doc/go1.9.html? It would've been saved me some time debugging an unexpected behavior change if I saw it mentioned there, so maybe it'll be helpful to others too.

Related to #20587.
Related to [CL 37694](https://golang.org/cl/37694). /cc @griesemer @alandonovan

**Comment by shurcooL** [comment]
Friendly ping.

If the answer is that "no, it shouldn't be included," this issue can be closed (but I'd like to know why not).

**Comment by ianlancetaylor** [comment]
Ping @griesemer

**Comment by ianlancetaylor** [comment]
Whatever we should have done, the ship has sailed and sunk.
