### ISSUE TITLE
doc: builtin package documentation is broken both on golang.org and godoc.org

### ISSUE THREAD

**Issue by ainar-g** [golang/go#21626]
https://golang.org/pkg/builtin/ shows this:

> /src/builtin/builtin.go:88:11: expected type, found '=' (and 1 more errors)

https://godoc.org/builtin is a "Not Found" even though e.g. `runtime` docs are available: https://godoc.org/runtime.

Both of these pages should show the correct documentation for Go builtins.

**Comment by ianlancetaylor** [comment]
Dup of #21601 .
