### ISSUE TITLE
website: move to App Engine flexible

### ISSUE THREAD

**Issue by broady** [golang/go#21628]
Most of the time, the latest version of Go isn't available on GAE. That causes problems, like with #21601.

We should move it to GAE flexible and/or GKE, where we can just run a container and therefore have godoc built by the same version of Go as it is serving docs for.

/cc @bradfitz

**Comment by agnivade** [comment]
ping @dmitshur. AFAIU, the latest website runs on GAE flex. https://go.googlesource.com/website/+/refs/heads/master/cmd/golangorg/app.prod.yaml

**Comment by dmitshur** [comment]
This issue looks like a forgotten duplicate of #27205. Yes, the website runs on [App Engine Flexible Environment](https://cloud.google.com/appengine/docs/flexible/) as of https://github.com/golang/go/issues/27205#issuecomment-435172401, so this is done.
