### ISSUE TITLE
Background job Android

### ISSUE THREAD

**Issue by joaquinicolas** [golang/go#21629]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### Does this issue reproduce with the latest release?
It is not an issue.

### What operating system and processor architecture are you using (`go env`)?
amd64 
darwin

### What did you do?
I want to run a some go code as background job in android.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Hi! how can I do to run some go code as background job? it is possible?

**Comment by crawshaw** [comment]
Go doesn't use the issue tracker for questions. Please see http://golang.org/wiki/Questions.
