### ISSUE TITLE
testing: with race detector on, using TB.Helper yields the wrong line number

### ISSUE THREAD

**Issue by cespare** [golang/go#21631]
Using go1.9 linux/amd64.

If you call testing.TB.Helper (i.e., through the interface), it prints an autogenerated line number when running with -race:

```
package main

import (
	"testing"
)

func TestFoo(t *testing.T) {
	f(t)
	g(t)
}

func f(tb testing.TB) {
	tb.Helper()
	tb.Error("asdf")
}

func g(t *testing.T) {
	t.Helper()
	t.Error("asdf")
}
```

gives

```
$ go test x_test.go
--- FAIL: TestFoo (0.00s)
        x_test.go:8: asdf
        x_test.go:9: asdf
FAIL
FAIL    command-line-arguments  0.001s
$ go test -race x_test.go
--- FAIL: TestFoo (0.00s)
        <autogenerated>:1: asdf
        x_test.go:9: asdf
FAIL
FAIL    command-line-arguments  0.005s
```

Bug pointed out on golang-nuts by @lukasmalkmus.

**Comment by agnivade** [comment]
This is now fixed in latest master. Not sure which commit though :confused: I just tried on the latest master and it worked.

**Comment by cespare** [comment]
A bisect pointed, unsurprisingly, at e97209515ad8c4042f5a3ef32068200366892fc2.

Thanks @aclements!
