### ISSUE TITLE
archive/zip: support "end of central directory record comment" (not file header comment)

### ISSUE THREAD

**Issue by yanolab** [golang/go#21634]
ZIP formart has 2 types comment.
First, Central directory file header comment. This is already supported.
Second, End of central directory record comment. Read this comment is supported, but Write is not supported yet.

(more detail of zip format, see also: https://en.wikipedia.org/wiki/Zip_(file_format))

Not supported go source code is bellow.
https://github.com/golang/go/blob/master/src/archive/zip/writer.go#L185

I think following commit is mistake, because file header comment had been supported since Go1 released.
https://github.com/golang/go/commit/bcc349aecf7bb26d4430e8f8ab60d9362181d1a0

I propose to support "end of central directory record comment".

## Proposal:
Add SetComment method to zip.Writer, such as bellow.
```
def (w *Writer) SetComment(c string) error
```

I will send patch if this proposal is acceptable.

**Comment by dsnet** [comment]
For symmetry with `Reader`, it is probably better to add a `Writer.Comment` field with the documentation that it must be set before `Writer.Close` is called.

But the feature request sounds good to me.

**Comment by yanolab** [comment]
@dsnet 
Thank you for your reply.
Certainly, you're right that for symmetry.
I'll add a field with the document.
However, I think `Reader.Comment` should not be settable.
I wonder why `Reader.Comment` is a settable field.

**Comment by mattn** [comment]
If the magic number 'PK..' is in the comment as likely as 'end of central directory record comment', I wonder extract intended.
