### ISSUE TITLE
website: bad view of playground for mobile

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#21636]
### What version of Go are you using (`go version`)?
Website for Go1.9

### What operating system and processor architecture are you using (`go env`)?
ubuntu + chrome

### What did you do?

Open website www.golang.org
![1](https://user-images.githubusercontent.com/16690032/29740048-48a1f9d4-8a56-11e7-88f0-7c43d1618589.png)

After that open page "Project"
![2](https://user-images.githubusercontent.com/16690032/29740055-67a3a134-8a56-11e7-9c01-25ae0e86f471.png)

After that open page "Play". Playground open page in windows and not good look for mobile.
![3](https://user-images.githubusercontent.com/16690032/29740058-7e431f6e-8a56-11e7-932e-678de1011e73.png)

### What did you expect to see?

If you open golang.org and after that play page.
![4](https://user-images.githubusercontent.com/16690032/29740065-bf7e9832-8a56-11e7-9adc-0859c307507d.png)

**Comment by agnivade** [comment]
> After that open page "Play". Playground open page in windows and not good look for mobile.

I don't see any "Play" button in the "Project" page. How are you opening the page ?

If you are entering "play.golang.org" in the browser, then that means you are opening a new site altogether. And it shouldn't matter what page are you on previously. And rightly so, if I enter "play.golang.org" after "golang.org/project", the page displays fine as you show in "What you expect to see" section.

And the error screenshot that you have shown is not "play.golang.org", it is the home page overlayed on the project page - which I am unable to repro.

Please re-check and clarify the steps to reproduce the issue.

**Comment by Konstantin8105** [comment]
We have that bug. Please follow below instuction.
For simplification of checking, please use Chrome in DevepolerTools choose "Samsung S5" for  looking on web page like on phone. Or check on phone.
* Open website www.golang.org
* After that open page "Project"
* After that open page "Play"(in blue button right-up on page). Playground open page in windows and not good look for mobile.

**Comment by agnivade** [comment]
Weird, I swear I did not see the "Play" button earlier. I see it now. Thanks.
