### ISSUE TITLE
net/http: mention RegisterOnShutdown in Shutdown docs

### ISSUE THREAD

**Issue by artyom** [golang/go#21637]
[http.Server.RegisterOnShutdown](https://github.com/golang/go/commit/1a63f116c11acdbd1b11c38dbdcaeb4e4ba0a94e) was introduced in 1.9 cycle, but it's not mentioned in the release notes, so it's easy to miss, even if it's useful to you.

[Documentation for http.Server.Shutdown](https://golang.org/pkg/net/http/#Server.Shutdown) (that was introduced in 1.8) states:

> Shutdown does not attempt to close nor wait for hijacked connections such as WebSockets. The caller of Shutdown should separately notify such long-lived connections of shutdown and wait for them to close, if desired.

IMO this is a good place to mention the new RegisterOnShutdown method to increase awareness of its existence.

**Comment by odeke-em** [comment]
@artyom thank you for noticing and reporting this! Would you like to make a CL for this?

Meanwhile I'll ping @bradfitz @rsc @broady on whether we can retroactively update these docs.
