### ISSUE TITLE
playground: gofmt/goimports error out on type alias syntax (likely because compiled under Go 1.8 rather than 1.9)

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21645]
### What did you do?

Visit https://play.golang.org/p/mxWrzSFu_W.

Keep "Imports" checkbox unchecked, press the Format button.
Check the "Imports" checkbox, try pressing the Format button again.

### What did you expect to see?

Successful execution of gofmt/goimports each time.

### What did you see instead?

With gofmt:

```
3:9: expected type, found '='
```

With goimports:

```
prog.go:3:9: expected type, found '='
```

### Possible Cause

This is possibly related to the environment where gofmt/goimports runs still running Go 1.8 rather than 1.9. Perhaps related to what @bradfitz said in https://github.com/golang/go/issues/21601#issuecomment-325040166.

**Comment by andybons** [comment]
Formatting is done on App Engine classic which runs on 1.8. We’ll have to move the format call to the flex backend in order to have it work in this case.

**Comment by bradfitz** [comment]
Can we move it all to flex?

**Comment by andybons** [comment]
Sure.
