### ISSUE TITLE
crypto/rsa: pss.go contains now dead link to RSA v2.2 standard

### ISSUE THREAD

**Issue by FChris** [golang/go#21642]
The link to [pkcs-1v2-2-rsa-cryptography-standard](http://www.rsa.com/rsalabs/pkcs/files/h11300-wp-pkcs-1v2-2-rsa-cryptography-standard.pdf) in [crypto/rsa/pss.go](https://github.com/golang/go/blob/master/src/crypto/rsa/pss.go) (line 9) is not working anymore.

What is the correct link that should be in this comment?

**Comment by odeke-em** [comment]
Thanks for reporting this @FChris! Yeah that link is now dead I've pinged RSA via the Twitter blackhole https://twitter.com/odeke_et/status/901538219501563908.
In fact even trying to visit https://www.rsa.com/rsalabs gives a 404.

/cc @agl @FiloSottile for some ideas/alternatives.

**Comment by ulikunitz** [comment]
The new link seems to be:
 https://www.emc.com/collateral/white-papers/h11300-pkcs-1v2-2-rsa-cryptography-standard-wp.pdf

You can find it under the Wikipedia entry https://en.wikipedia.org/wiki/PKCS_1

**Comment by odeke-em** [comment]
Thank you @ulikunitz. Yeah, I saw that too and thought it made sense since EMC acquired RSA.
@FChris or @ulikunitz please feel free to send a CL updating it.

**Comment by ulikunitz** [comment]
I provided https://golang.org/cl/59351. I guess it requires a reviewer.
