### ISSUE TITLE
regexp: example for Regexp.Expand

### ISSUE THREAD

**Issue by MatejB** [golang/go#21649]
I found [Regexp.Expand](https://tip.golang.org/pkg/regexp/#Regexp.Expand) missing a simple example of use and would like to contribute one.

Although function has fair amount of documentation, it's usage was unclear to me at first passing through regexp package documentation. I find it very useful in everyday work.

The example would be similar to https://play.golang.org/p/Ok-F8RvwSO

**Comment by a-h** [comment]
Nice. I added a bit more text to the example to explain what's going on, is that helpful do you think? https://play.golang.org/p/JbEaidJtim

**Comment by MatejB** [comment]
@a-h good point. Most examples are minimal but in this case it could be useful to reader to have a bit of explanation.
