### ISSUE TITLE
cmd/compile: "offset too large" error

### ISSUE THREAD

**Issue by runner-mei** [golang/go#21655]
### What version of Go are you using (`go version`)?
go version go1.9 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\dev\go\meijing\;d:\dev\\tpt_vendor;d:\dev\Godeps\_workspace
set GORACE=
set GOROOT=d:\tools\go_amd64
set GOTOOLDIR=d:\tools\go_amd64\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxx\AppData\Local\Temp\go-build851261075=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
I compile my app, it is ok on go1.8 or go1.7
code is:

![default](https://user-images.githubusercontent.com/1052632/29757016-467c5efc-8bdb-11e7-9988-f1a82f763445.png)

### What did you expect to see?
it is compile ok.

### What did you see instead?
# cn/com/hengwei/poller
.\alert_action.go:448:2: offset too large in 02217 (d:\dev\meijing\src\cn\com\hengwei\poller\alert_action.go:428)     MOVQ    -17179868768(BX)(AX*8),BX
.\alert_action.go:448:2: offset too large in 03783 (d:\dev\meijing\src\cn\com\hengwei\poller\alert_action.go:430)     MOVQ    -17179868768(DX)(CX*8),DX
FAIL    cn/com/hengwei/poller [build failed]

**Comment by dsnet** [comment]
Hi. We're going to need something more than a screenshot to help debug this. At least paste a minimal reproduction of the problem.

\cc @randall77 @josharian

**Comment by runner-mei** [comment]
@dsnet this code is private,  if you can promise not to spread it, nor use it elsewhere, and delete it after finding out the problem,  I can send this code to your mail.

**Comment by dsnet** [comment]
Please don't send me anything. I have reported on compiler bugs before. You should be able to use process of elimination to eventually trim the problem down to a snippet that is safe to share. For example, #20333.

**Comment by runner-mei** [comment]
````go
package main

import (
	"math"
)

const current_status_internal_start = math.MaxInt32 - 50

func aaa(ss []*string, current int) string {
	if current > current_status_internal_start {
		tmpl_index := current - current_status_internal_start + 1

		if len(ss) > tmpl_index {
			s := ss[tmpl_index]
			if nil != s {
				return *s
			}
		}
	}

	switch current {
	case 0:
		return "a"
	default:
		return "b"
	}
}

````
[main.zip](https://github.com/golang/go/files/1257172/main.zip)

it is ok on the linux.

**Comment by opennota** [comment]
> it is ok on the linux.

It's not on my machine.

```
$ go build 
# github.com/opennota/a
./main.go:15:2: offset too large in 00039 (/home/opennota/gocode/src/github.com/opennota/a/main.go:10)       MOVQ    -17179868776(CX)(AX*8), CX

$ go version
go version go1.9 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/opennota/gocode"
GORACE=""
GOROOT="/home/opennota/go"
GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build906297495=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by runner-mei** [comment]
@opennota yes, I made a mistake, it is fail also on the linux.

**Comment by dsnet** [comment]
@runner-mei, thank you for producing a minimal repro.

**Comment by randall77** [comment]
Reopening for cherry pick for 1.9.1.

**Comment by rsc** [comment]
CL 59630 OK for Go 1.9.2.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 70981](https://golang.org/cl/70981) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:10 UTC

**Comment by runner-mei** [comment]
This bug is still exists in the go 1.9.2  on windows/386
````
c:\> go version
go1.9.2 windows/386
````

**Comment by ianlancetaylor** [comment]
Still happens on tip too, with `GOARCH=386`.  Reopening.

**Comment by randall77** [comment]
Reopening for go 1.9.3.

**Comment by andybons** [comment]
CL 82675 OK for Go 1.9.3.

**Comment by andybons** [comment]
go1.9.3 has been packaged and includes:

  - [CL 82675](https://golang.org/cl/82675) cmd/compile: fix large load/store offsets on 386

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Jan 22 21:02:53 UTC
