### ISSUE TITLE
x/mobile: gomobile bind fails when GOPATH=""

### ISSUE THREAD

**Issue by landsnail** [golang/go#21658]
use 1.8.3
gomobile build and install was success but fail with bind

the console log:

gomobile: loadExportData failed go install -pkgdir=/Users/landsnail/go/pkg/gomobile/pkg_android_arm -gcflags=-shared -ldflags=-shared test failed: exit status 2
go: GOPATH entry is relative; must be absolute path: "".
For more details see: 'go help gopath'

oh, i am using mac with OSX system.

if someone can repply?

**Comment by crawshaw** [comment]
Looks like gomobile may need to be updated to handle the new meaning of a missing GOPATH.

For now, you can make it work with: `export GOPATH=$HOME/go`.
