### ISSUE TITLE
website: Go 1.9 not listed in bucket contents at https://storage.googleapis.com/golang

### ISSUE THREAD

**Issue by joshwlewis** [golang/go#21667]
### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
`amd64`

### What did you do?

`curl https://storage.googleapis.com/golang | grep 'go1.9'`

### What did you expect to see?

Metadata about available go 1.9 downloads, such as `https://storage.googleapis.com/golang/go1.9.darwin-amd64.pkg`.

### What did you see instead?

No matches for 1.9.

**Comment by joshwlewis** [comment]
Note that the `asdf` go installer relies on the bucket contents here. More on that [here](https://storage.googleapis.com/golang/go1.9.darwin-amd64.pkg).

**Comment by bradfitz** [comment]
I believe this is intentional. We changed how and where downloads are hosted starting at Go 1.9.

This is not an interface we ever guaranteed as stable.

**Comment by andybons** [comment]
@joshwlewis your link is linking to the darwin 1.9 download instead of what, I think, you intended to link to.

**Comment by joshwlewis** [comment]
> I believe this is intentional. We changed how and where downloads are hosted starting at Go 1.9.
This is not an interface we ever guaranteed as stable.

Understandable. Is there a more stable reference to get a list of available versions?

**Comment by broady** [comment]
It's there. It's just paginated.

```
$ curl -s https://storage.googleapis.com/golang | sed -e 's/></'\\n'/g' | grep IsTruncated
IsTruncated>true</IsTruncated
```

Use gsutil, or the actual GCS API:
```
$ gsutil ls gs://golang/go1.9.* | wc -l
40
```

**Comment by joshwlewis** [comment]
> your link is linking to the darwin 1.9 download instead of what, I think, you intended to link to.

Thanks, fixed. I meant to link [here](https://github.com/golang/go/issues/21667).

**Comment by broady** [comment]
XML API:
https://cloud.google.com/storage/docs/xml-api/get-bucket-list

See the part about `NextMarker` and `IsTruncated`.

But yes, as @bradfitz says, there's no guarantees for this.

**Comment by joshwlewis** [comment]
> It's there. It's just paginated.

Oops, thanks!
