### ISSUE TITLE
database/sql: Drivers cannot deprecate Queryer and Execer

### ISSUE THREAD

**Issue by vmg** [golang/go#21663]
### What version of Go are you using (`go version`)?

```
~ $ go version
go version go1.9 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes, all releases since 1.8

### What operating system and processor architecture are you using (`go env`)?

```
~ $ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vmg/src/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build317274576=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

According to the docs in `database/sql/driver`, the `Queryer` interface for SQL drivers is deprecated and `QueryContext` should be implemented instead:

> Queryer is an optional interface that may be implemented by a Conn.
> If a Conn does not implement Queryer, the sql package's DB.Query will first prepare a query, execute the statement, and then close the statement.
> Query may return ErrSkip.
> Deprecated: **Drivers should implement QueryerContext instead** (or additionally).

I created a dummy SQL driver that implements `QueryerContext`, but **not** `Queryer`. I also implemented an identical dummy driver that implements both `Queryer` and `QueryerContext`.

I then ran a simple `SELECT` query using both drivers.

[Go Playground link](https://play.golang.org/p/wPP7Cu8Ti_)

### What did you expect to see?

I expected the `database/sql` library to call `QueryContext()` on _both_ my dummy drivers, and to print `Called QueryContext with 'SELECT 'foobar''` twice.

### What did you see instead?

The dummy driver that implements `Queryer` and `QueryerContext` works just fine, and calls `QueryContext()` to resolve the query.

The dummy driver that _only_ implements `QueryerContext` does _not_ work. It `panic`s because `database/sql` doesn't attempt to use `QueryContext()`, and instead falls back to preparing a statement and discarding it immediately.

### Further notes

I came across this bug when attempting to write a "wrapper" driver to instrument SQL queries in an app. The very first version showed a 100% slowdown when performing simple queries with a wrapped MySQL driver.

After some investigation, I noticed that the implementation for both `Query` and `Exec` in `database/sql` does not match the provided documentation.

The docs state that the `Queryer` and `Execer` interfaces are now deprecated, and new drivers should implement their Context-aware counterparts "instead". But this is not the case: if the original deprecated interfaces are not implemented, the following type checks will fail and the library will never call the new interfaces:

https://github.com/golang/go/blob/5d39af9d9bac91b84b9944b1edffc6fb332747fa/src/database/sql/sql.go#L1311-L1312

https://github.com/golang/go/blob/5d39af9d9bac91b84b9944b1edffc6fb332747fa/src/database/sql/sql.go#L1241-L1245

The end result is that any new SQL driver that implements _only_ the new `QueryContext()` and `ExecContext()` methods will not really work: these methods will never be called, and `database/sql` will fallback to the slow path of preparing and discarding a statement for the query.

The same situation will happen if any of the existing SQL drivers decide to truly deprecate `Query` and `Exec` in any future release by removing the two APIs altogether.

**Comment by kardianos** [comment]
Related #21084

**Comment by kardianos** [comment]
I agree that this should be done and will target go1.10. I haven't looked at the code in detail with this in mind, but I think it would be reasonable for anyone to do this.
