### ISSUE TITLE
doc: add checksum for go1.4-bootstrap

### ISSUE THREAD

**Issue by forskning** [golang/go#21662]
How about adding a Checksum in parentheses next to go1.4-bootstrap-20170531.tar.gz?

https://golang.org/doc/install/source

**Comment by nehaljwani** [comment]
FWIW, it's available at https://storage.googleapis.com/golang/go1.4-bootstrap-20170531.tar.gz.sha256

**Comment by broady** [comment]
There's also a GPG signature for every tar.gz download. "...tar.gz.asc"

**Comment by forskning** [comment]
@broady

In a 29-08-17 dated reply to an e-mail to security [at] golang [dot] org, @rsc wrote "We should probably get the bootstrap tar.gz listed on golang.org/dl, which already has checksums."

https://golang.org/doc/install/source

In the event that any additional fixes are added to go1.4-bootstrap, then the SHA256 Checksum provided by @nehaljwani would (of consequence) no longer be valid.

https://golang.org/dl/#featured

Under "Featured downloads" there is factually room for an additonal 'Bootstrap' button.

https://golang.org/dl/#stable

Under "Stable versions" could be then be added a 'go1.4-bootstrap' section, with the most recent bootstrap accompanying its valid SHA256 Checksum.

**Comment by ALTree** [comment]
> Under "Featured downloads" there is factually room for an additonal 'Bootstrap' button.

Please don't add 1.4-bootstrap to the "Featured downloads" section. There's no reason for it to be there. Last + source is what 99% of the users that land on that page needs to see.

**Comment by forskning** [comment]
It appears there are two sections with anchors on golang.org/dl, so rejecting the added Button as per the comment of @ALTree, would the Parties involved in this thread, then be amenable to having a third "Bootstrap" section with an anchor, thereunder an expandable go1.4 subsection, and then modifying the bootstrap tar.gz link on golang.org/doc/install/source to point to that new anchor, where clicking on that modified link would open the page in a new browser tab?

**Comment by forskning** [comment]
if https://golang.org/doc/install/source is to be edited

https://forum.golangbridge.org/t/compiling-go-cgo-enabled/6858

https://golang.org/doc/install/source#ccompiler

doesn't clarify that CGO_ENABLED=1 is default

make.bash, make.rc and make.bat

CGO_ENABLED: Controls cgo usage during the build. Set it to 1
to include all cgo related files, .c and .go file with "cgo"
build directive, in the build. Set it to 0 to ignore them. The
default is 1, and for cross-compiles is 0.

**Comment by forskning** [comment]
If there's a lack of interest in my e-mail to golang-dev dated 10 October 2017, @broady, not a fix per se, but time permitting, I suppose the changes, perhaps reworded according to developers' preferences, to the comments in make.bash, make.bat, and make.rc, could make their way into 1.9.2.

I'm aware that now edited https://github.com/golang/go/issues/21662#issuecomment-335366453 diverges from the original subject of this tread as pertaining to html documentation.

**Comment by ALTree** [comment]
@forskning 

> could make their way into 1.9.2.
I doubt so. From the [release policy](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance):

> A minor release is issued to **address one or more critical problem** for which there is no workaround (typically related to stability or security). The only code changes included in the release are the fixes for the specific critical problems. Important documentation-only changes [..] may also be included as well

Your proposal is definitely go1.10 material.

Also, I don't understand why are you proposing to change comments in the build scripts. (almost) nobody reads those script. Doc changes should go in documentation pages. You'll need to explain what kind of problem are we trying to solve, and in which doc page the change will go, and what to change.

**Comment by forskning** [comment]
https://github.com/bsbf2018/contrib

Maint sub-branch perl-5.26.1 contains changes in commenting in the win32 Makefile and makefile.mk files, slightly modified from patches made to perl blead, the commenting changes to perl blead having largely been superceded.

I don't see it as problematic to modify the commenting in make.bash, make.bat and make.rc prior to the next Go minor release, as 1.9.2, but again time permitting, and acknowledging that critical fixes are taking precedence in minor releases.

**Comment by forskning** [comment]
https://groups.google.com/forum/#!topic/golang-dev/naQlgeWVtvA

@alexbrainman and @rsc, any interest in chipping in on https://github.com/golang/go/issues/21662#issuecomment-335900634 and https://github.com/golang/go/issues/21662#issuecomment-335940582

**Comment by alexbrainman** [comment]
> any interest in chipping in on #21662 (comment) and #21662 (comment)

I have no opinion on these. Sorry.

Alex

**Comment by forskning** [comment]
@ianlancetaylor

confer: https://golang.org/cl/69430

Does one expect the reader of golang.org/doc/install/source#ccompiler who thereafter might run a grep for "CGO_ENABLED" on make.bash, make.bat and make.rc, to know to look in src/go/build/zcgo.go?

If the comments would be modified in make.bash, make.bat, and make.rc, that should be consistent with src/go/build/zcgo.go; obviously from that file defaultCGO_ENABLED = "" would be false for make.rc.

If golang.org/doc/install/source#ccompiler were modified, then  the reader should be referred to src/go/build/zcgo.go, e.g., something along the lines of the below.

"The file src/go/build/zcgo.go contains a list of platforms where CGO_ENABLED=1 is the default."

**Comment by ianlancetaylor** [comment]
@forskning I'm sorry, I don't really understand what you are getting at.

> Does one expect the reader of golang.org/doc/install/source#ccompiler who thereafter might run a grep for "CGO_ENABLED" on make.bash, make.bat and make.rc, to know to look in src/go/build/zcgo.go?

No.

I don't expect anyone other than a core Go developer to ever look at src/go/build/zcgo.go.

While the docs in make.bash, make.bat, and make.rc should be accurate, I don't expect anybody to read them.

**Comment by forskning** [comment]
make.bash/make.bat/make.rc

A.D.  

>  (almost) nobody reads those

I.L.T.

> don't expect anybody to read them

E.L.

> run a grep for "CGO_ENABLED" 

different _modi operandi_ I suppose

**Comment by forskning** [comment]
https://golang.org/doc/install/source

On the above page is listed

go1.4-bootstrap-20170531.tar.gz

hyperlinked to https://storage.googleapis.com/golang/go1.4-bootstrap-20170531.tar.gz

https://golang.org/dl/

expanding

Archived versions

and then

go1

one also finds listed
 
go1.4-bootstrap-20170531.tar.gz

accompanying a SHA256 Checksum, but

hyperlinked to https://redirector.gvt1.com/edgedl/go/go1.4-bootstrap-20170531.tar.gz

https://golang.org/dl/#stable

so, should the above expandable go1 be renamed to bootstrap and relocated under Stable versions?

FWIW, regarding https://github.com/golang/go/issues/21662#issuecomment-335366453, I wonder if someone might clarify the purpose of the presence of the CGO_ENABLED comment block in make.rc, my understanding is that noting Plan 9's C implementatation being a "dialect of ANSI C", that cgo is factually not supported on that OS.

**Comment by rsc** [comment]
I think it's overkill to add a checksum there.
