### ISSUE TITLE
encoding/csv: bare " in non-quoted-field

### ISSUE THREAD

**Issue by EltonSouza** [golang/go#21672]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Operating system: Linux
Architecture: amd64

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/8dJUQujmDQ

### What did you expect to see?
```
[[CNPJ/CPF Data_Compra Cod_Contribuinte Cod_Cidade Cod_Empresa  Cod_Divisão  Empreendimento Bloco Cod_Unidade Cod_Parcela Cod_Ano Tipo de documento Vencimento] [	  30103201006 SP1 1200 R.0329R.94.0021 1200 VISTA VERDE 1524897 021-4 7 2017  ] [	  17002302743 SP1 1192 R.0298R.01.0011 1192 IT"S 163 1524897 011-1 7 2017   0 -1]]
```

### What did you see instead?
```line 3, column 47: bare " in non-quoted-field```

problem character: `"`

```
package main

import (
	"encoding/csv"
	"fmt"
	"log"
	"strings"
)

func main() {
	in := `CNPJ/CPF,Data_Compra,Cod_Contribuinte,Cod_Cidade,Cod_Empresa ,Cod_Divisão ,Empreendimento,Bloco,Cod_Unidade,Cod_Parcela,Cod_Ano,Tipo de documento,Vencimento
	,,30103201006,SP1,1200,R.0329R.94.0021,1200 VISTA VERDE,1524897,021-4,7,2017,,
	,,17002302743,SP1,1192,R.0298R.01.0011,1192 IT"S 163,1524897,011-1,7,2017,, 0 -1`
	r := csv.NewReader(strings.NewReader(in))
	r.Comma = ','
	r.Comment = '#'

	records, err := r.ReadAll()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(records)
}
```

**Comment by ericlagergren** [comment]
You need to set `LazyQuotes` to true.

**Comment by avelino** [comment]
Like the @ericlagergren said in source:
https://play.golang.org/p/t7SePY6c6I

**Comment by davecheney** [comment]
Closing as there isn't a bug to b fixed.
