### ISSUE TITLE
x/tools/cmd/godoc: results page jumps during rendering

### ISSUE THREAD

**Issue by bcmills** [golang/go#21685]
Example page: https://tip.golang.org/search?q=testing

The results initially render with the (IMO) most useful package links,¹ then replace them a short time later with a long list of cross-references.² If you try to click on one of the package links, you're fairly likely to end up on an arbitrarily different page than you intended.

Ideally, the whole page should load instantly. However, if that is not possible, we should structure the page so that it does not jump around as it loads.

(CC: @alandonovan @stamblerre)

¹![rsec5dcglnt](https://user-images.githubusercontent.com/5200974/29841618-15de8604-8cd4-11e7-9747-ad802ff477df.png)

²![01paakzo3ju](https://user-images.githubusercontent.com/5200974/29841625-1b63f2e4-8cd4-11e7-8bf4-08be981e9768.png)

**Comment by jimmyfrasche** [comment]
For the layout itself, there's https://caniuse.com/#feat=multicolumn Despite having good support on paper, it's still kinda buggy. Even when everything's working right it never quite seems to work as well as advertised. It's always hard to say if it will work in a given situation, but, when it does, it works well and is simpler than the alternatives. So, even if it ultimately doesn't work, it's usually worth trying it first.

**Comment by agnivade** [comment]
Thanks. I have used it before. Will give it a shot.

**Comment by agnivade** [comment]
Nearly got it working. Only slight issue is that there is no notion of minimum column-height. So all elements will fill to all the columns. Therefore, it looks odd if the no. of elements is low.

![cc](https://user-images.githubusercontent.com/1774000/43830774-c9607296-9b1f-11e8-89fd-3f88631aa231.png)

In this case, it looks good if they are split into 2 columns. To fix this, I can add some heuristics and send an appropriate css class attached to the div from server side. But then, it would require 4 classes in the css file, each for a separate `column-count` value. I would really like a native css solution to this.

@jimmyfrasche - Any way to tackle this ?

paging other css wizards too @andybons

**Comment by jimmyfrasche** [comment]
You could inject custom properties into the dom with an appropriately placed `style="--max-cols: 2;"`  based on the server-side heuristics

**Comment by agnivade** [comment]
Hmm .. not the most elegant solution. But works. No way to make minimum column height I guess ?

**Comment by jimmyfrasche** [comment]
Not that I am aware of.
