### ISSUE TITLE
x/tools/cmd/godoc: show entities before cross-references

### ISSUE THREAD

**Issue by bcmills** [golang/go#21686]
(A follow-on from #21685.)

Arguably the most useful godoc results are packages, followed by entities defined within those packages (types, variables, functions, interfaces, and methods). Cross-references are sometimes helpful, but rarely what I'm looking for when I'm searching golang.org.

For example, if I search for [rand](https://tip.golang.org/search?q=rand), odds are good I'm looking for the package documentation for either `math/rand` or `crypto/rand`. Unfortunately, at the moment there are so many cross-references that the latter result doesn't even appear above the fold.¹

¹
![vaxrdmhgvxp](https://user-images.githubusercontent.com/5200974/29841914-350e23ee-8cd5-11e7-898d-3608e13e6dba.png)

**Comment by seankhliao** [comment]
pkgsite uses a different display layout.
