### ISSUE TITLE
cmd/compile: a[1.0 << s] should be accepted

### ISSUE THREAD

**Issue by griesemer** [golang/go#21693]
Per the fix for #14844, https://play.golang.org/p/fWbHLgkJ7Z should now be accepted by the compiler.

**Comment by bradfitz** [comment]
Ping Robert.

I assume this is a release-blocker, given the spec update?

**Comment by griesemer** [comment]
Will look into this tomorrow. It's not spec compliant anymore but I don't think it's a release blocker - after all there's a trivial work around (just write `a[1 << s]` instead). Leaving as is for now in case there's an easy fix.

**Comment by odeke-em** [comment]
I had started working on this at some ungodly hours of Saturday morning but I couldn't  get a proper cast/conversion to int in https://github.com/golang/go/blob/992ce90f662467f04dd93b3bb565bb0414f82999/src/cmd/compile/internal/gc/const.go#L262
so I'll defer to you @griesemer :)
