### ISSUE TITLE
x/crypto/ssh: session.Close() should unblock session.Wait()

### ISSUE THREAD

**Issue by nhooyr** [golang/go#21699]
The `session.Close` only sends the channel close message to the server. It's not until the server responds with a channel close message that `session.Wait()` returns because of the reqs channel being closed. `session.Wait()` should return immediately after `session.Close()`.

See #21423 for previous discussion.

**Comment by hanwen** [comment]
can you provide more details under what circumstances the Close takes longer to process than the roundtrip that the RFC prescribes for channel close?

I don't think we can trigger the channel close mechanics without receiving an ack from the remote side, as we wouldn't know where to deliver any messages, so it would lead to dropped data.

**Comment by hanwen** [comment]
ping.

**Comment by nhooyr** [comment]
I don't follow.

My issue is that a poorly implemented SSH server could potentially take forever to respond to a channel close which would cause session.Wait() to deadlock.

**Comment by hanwen** [comment]
the channel mechanism is not really suited for error handling/timeout, since both sides have to be in agreement on what to do with the channel. If the remote end can't do that, the proper course of action is shutdown the entire connection.

**Comment by nhooyr** [comment]
That's fine with me, if the server doesn't respond in a reasonable amount of time to the channel close, we should just close the connection.

**Comment by hanwen** [comment]
have you seen this problem in practice?

**Comment by nhooyr** [comment]
Nope.

**Comment by hanwen** [comment]
you can setup a keepalive. One does this by sending periodic requests (global or channel) with wantReply=true, and closing the connection if replies take too long.

Maybe the SSH client should provide this out of the box, though?

**Comment by nhooyr** [comment]
Nah, I think we're talking about different things. Even with SSH Keep Alive, a poorly implemented ssh server could take forever to respond to a channel close, which would cause session.Wait() to deadlock.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
