### ISSUE TITLE
Array types not invariant

### ISSUE THREAD

**Issue by thwd** [golang/go#21692]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="redacted"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build960338154=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/NcEMd9jcBH

### What did you expect to see?

"cannot use [1]bool{false} (type [1]bool) as type X"

### What did you see instead?

no type-checking error.

**Comment by martisch** [comment]
I think this is working as intended:
https://golang.org/ref/spec#Assignability
"x's type V and T have identical underlying types and at least one of V or T is not a defined type."

**Comment by thwd** [comment]
Thanks, seems you're right. Do assignability rules extend to the append function though?
https://play.golang.org/p/6ry5eMPLhn

**Comment by martisch** [comment]
https://golang.org/ref/spec#Passing_arguments_to_..._parameters
"...which all must be assignable to T"

**Comment by thwd** [comment]
Thank you, that resolves the issue.
