### ISSUE TITLE
cmd/cgo: overflow error on int64_t

### ISSUE THREAD

**Issue by reaperhulk** [golang/go#21708]
Under go 1.9 the following code no longer compiles due to an overflow:

```go
package main

/*
#include <stdint.h>
#define AV_NOPTS_VALUE   ((int64_t)UINT64_C(0x8000000000000000))
*/
import "C"

func main() {
	if C.int64_t(0) == C.AV_NOPTS_VALUE {
		// irrelevant
	}
}
```

`./main.go:10: constant 9223372036854775808 overflows C.int64_t`

Under go 1.8.3 and below this code compiles and works without error. Obviously 0x8000000000000000 does overflow an int64_t, but it seems like the (int64_t) cast in the C code should already have overflowed it to the value -9223372036854775808 before cgo sees it?

**Comment by hirochachacha** [comment]
This is a serious bug, could be a go1.9.1 candidate.

```
package main

/*
#include <stdint.h>
#define AV_NOPTS_VALUE   (int64_t)(-1)
*/
import "C"
import "fmt"

func main() {
	fmt.Println(C.AV_NOPTS_VALUE)
}
```

```
./x.go:11: constant 18446744073709551615 overflows int
```

```
$ go tool cgo -debug-gcc x.go
...
not-signed-int-const:1:11: error: token is not a valid binary operator in a preprocessor subexpression
#if 0 < (AV_NOPTS_VALUE)
          ^~~~~~~~~~~~~~
/Users/hiro/x.go:5:35: note: expanded from macro 'AV_NOPTS_VALUE'
#define AV_NOPTS_VALUE   (int64_t)(-1)
                         ~~~~~~~~~^
...
```

The problem is that current uint detection is too optimistic.
I'm not sure about the right solution here. But at least if the detection is failed,
it should fallback to int64, not uint64.

This is the second time I broke in this season, I'm really sorry about that.

**Comment by reaperhulk** [comment]
@hirochachacha It's okay, I appreciate the rapid diagnosis. It's easy to stay on go1.8.3 until this is resolved. Thanks for all that you do!

**Comment by hirochachacha** [comment]
@reaperhulk Thank you. I sent the fix. I hope that solve the problem

**Comment by odeke-em** [comment]
Reopening for cherry picking for Go1.9.1

**Comment by rsc** [comment]
CL 60810 OK for Go 1.9.2. 

I also tested that the new test in misc/cgo/test works with (int64_t)(0xFFFFFFFFFFFFFFFF) as well as it does with (int64_t)(-1), just in case it didn't.

**Comment by odeke-em** [comment]
Thank you @reaperhulk for reporting it, @hirochachacha for the fix and @rsc for testing and evaluating for the cherry pick.

**Comment by rsc** [comment]
CL 70970 OK for Go 1.9.2.

(Gerrit believes that a cherry-pick of 60810 has already happened on release-branch.go1.9 and will not allow a second. It doesn't appreciate that we wiped that from the Git history. CL 70970 is a straight cherry-pick but with the Change-Id incremented to break the cherry-pick association on Gerrit.)

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 70970](https://golang.org/cl/70970) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:11 UTC
