### ISSUE TITLE
json.Unmarshal did not work

### ISSUE THREAD

**Issue by kingangelAOA** [golang/go#21715]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
version : 1.9

### What operating system and processor architecture are you using (`go env`)?
mac 10.12

### What did you do?

             for index, url := range URLS {
		fmt.Println(index)
		iface.Hosts = []string{url}
		res, err := iface.Request()
		if err != nil {
			panic(err)
		}
		if res.StatusCode == 200 {
			body, err := ioutil.ReadAll(res.Body)
			if err != nil {
				panic(err)
			}
			var eleSoaResponse EleSoaResponse
			if err := json.Unmarshal(body, &eleSoaResponse); err != nil {
				panic(err)
			}
			var rankResponse RankResponse
			fmt.Println("begin json Unmarshal", len(eleSoaResponse.Result))
			if err := json.Unmarshal([]byte(eleSoaResponse.Result), &rankResponse); err != nil {
				fmt.Println("json Unmarshal err")
				panic(err)
			}
			fmt.Println("end json Unmarshal")
			if index == 0 {
				resMap["xg"] = rankResponse
			} else {
				resMap["wg"] = rankResponse
			}
		} else {
			body, err := ioutil.ReadAll(res.Body)
			if err != nil {
				panic(err)
			}
			panic(fmt.Errorf("request error, status: %d, body: %s", res.StatusCode, string(body)))
		}
          }

### What did you expect to see?

0
begin json Unmarshal 97997
end json Unmarshal
1
begin json Unmarshal 97997
end json Unmarshal

### What did you see instead?
0
begin json Unmarshal 97997
end json Unmarshal
1
begin json Unmarshal 97997

 it is pending  and  json.Unmarshal did not catch error

eleSoaResponse.Result is too big

**Comment by mvdan** [comment]
This is not a self-contained piece of code to reproduce the issue. Please provide one on play.golang.org.

I also don't understand what you think the issue is here - "did not catch error" and "Result is too big" are too vague.

**Comment by kingangelAOA** [comment]
var rankResponse RankResponse
                        var b bytes.Buffer
			fmt.Println("begin json Unmarshal", len(b.Bytes()))
			b.Write([]byte(eleSoaResponse.Result))
			fmt.Println(len(b.Bytes()))
			if err := json.Unmarshal(b.Bytes(), &rankResponse); err != nil {
				fmt.Println("json Unmarshal err")
				panic(err)
			}
			fmt.Println("end json Unmarshal")

result: 
begin json Unmarshal 0
97977
end json Unmarshal
begin json Unmarshal 0
97977

when run second
"end json Unmarshal" did not print

it is pending at  json.Unmarshal(b.Bytes(), &rankResponse)

run  first can  Unmarshal json

but secon can not

**Comment by kingangelAOA** [comment]
![2017-08-31 9 43 35](https://user-images.githubusercontent.com/15135537/29926310-a37692b4-8e95-11e7-921d-652a12cd4f27.png)

**Comment by mvdan** [comment]
This is still not a self-contained program. Please provide one on https://play.golang.org/. Without one, it's very hard to understand what's going on or what you believe the issue to be.

**Comment by kingangelAOA** [comment]
Sorry, I found the problem, third-party package caused the task to lock up
