### ISSUE TITLE
strconv: incorrect rounding to nearest even

### ISSUE THREAD

**Issue by griesemer** [golang/go#21714]
The following statements
```
fmt.Printf("x = %.1f\n", 0.35)
fmt.Printf("x = %.1f\n", 0.45)
fmt.Printf("x = %.1f\n", 0.55)
fmt.Printf("x = %.1f\n", 0.65)
```
produce
```
x = 0.3
x = 0.5
x = 0.6
x = 0.7
```
(https://play.golang.org/p/kLC7Ap0cpP).

However, assuming rounding to nearest even, one would expect the result to be
```
x = 0.4
x = 0.4
x = 0.6
x = 0.6
```
(The examples use fmt.Printf but the culprit is in the underlying strconv code. The documentation doesn't explicitly state that it rounds to nearest even, but that is definitively the intent of the implementation which contains code and comments to that effect.).

The problem of course is that these numbers cannot be accurately represented in binary form and when it comes to the rounding decision, what should be `.5` is sometimes below or above that value.

That said, the correct result could in fact be obtained if rounding were done on the shortest decimal representation that produces the incoming number, that is if rounding where done on the output of using the "%g" format (or `strconv.FormatFloat` with precision -1). Unfortunately, computing that representation is much more expensive than what happens now.

We can probably not fix this. For one, it's been like this forever. Also, a corresponding C program
```
#include <stdio.h>

int main() {
	printf("x = %.1f\n", 0.35);
	printf("x = %.1f\n", 0.45);
	printf("x = %.1f\n", 0.55);
	printf("x = %.1f\n", 0.65);
	return 0;
}
```
produces the same (incorrect) result. And so does `math/big.Float` formatting with the same arguments (since the code mirrors the strconv code).

But we should probably document it and perhaps even provide a "correct" routine for cases where this truly matters.

**Comment by bcmills** [comment]
I don't see what's “incorrect” about it. The spec gives exactly what happens: the arbitrary-precision constant 3.5 is rounded to its default type, which is then rounded to one digit.

The only reason to expect any different would be if floating-point constants converted to an arbitrary-precision floating-point type instead of a fixed-precision type.

**Comment by griesemer** [comment]
@bcmills This has little to do with arbitrary precision constants since we get the same results if we do everything in float64 arithmetic, starting from numbers that can be represented exactly.

But I'm wrong nevertheless: After an exact constant `f` (a fraction) such as 0.35 has been converted to a float64 value `x` (or after a float64 division of the exact values 35.0 and 100.0) there may be an error between `x` and `f` if `f` cannot be represented accurately as a float64.

In the case of `f` = 0.35 = 35.0/100.0, the resulting `x` = `float64(0.35)` is precisely 3152519739159347/9007199254740992, which is off by -1/45035996273704960 (= -2.2204460492503130809e-17) from the original `f`; i.e., it is smaller than 0.35.

At this point all we have is that float64 value `x`, and if we then round it to one decimal mantissa the result is correctly 0.3 and not 0.4 (because `x` is in fact smaller than 0.35).

The following [program](https://play.golang.org/p/jz8GEHgwzG) computes the exact errors as well as exact and strconv rounded values and it turns out that for my original example above, the strconv rounded results are less than 0.05 away from the actual float64 values which means that they are correctly rounded.

@mpvl I'm closing this as working as expected. You may need to revisit  https://golang.org/cl/60730.

**Comment by mpvl** [comment]
Will undo that CL and focus on allowing people to use their own numeric types.
