### ISSUE TITLE
cmd/vet: should not warn +build in raw string literal

### ISSUE THREAD

**Issue by cherrymui** [golang/go#21716]
After CL 60531 (https://go-review.googlesource.com/c/go/+/60531), the misc builder fails with

```
##### go vet std cmd
go run main.go -p freebsd/arm
go/types/hilbert_test.go:55: +build comment must appear before package clause and be followed by a blank line
exit status 1
```
(https://build.golang.org/log/890387a04a58201c9d1cf7d819dbe939e3e5d4b0)

The relevant line is https://go-review.googlesource.com/c/go/+/60531/2/src/go/types/hilbert_test.go#55
which is a +build in raw string literal.

**Comment by cznic** [comment]
I think this is intentional (ie. WAI), because some go tools are known to _not_ parse the source when looking for [certain?] magic comments.

The solution is to, for example

```
s/+build/+`+`build/
```

or to use any other way of hiding the directive in it's plain form _and_ starting at BOL.

**Comment by cherrymui** [comment]
If this is the case we probably need to change `go/types/hilbert_test.go` to work around it. Kind of unfortunate.

**Comment by mdempsky** [comment]
We've worked around this issue in hilbert_test.go for now to appease the vet builder. If we decide to fix in cmd/vet instead, we should undo the workaround.

**Comment by robpike** [comment]
Working as intended.
