### ISSUE TITLE
os: File.Seek does not work past EOF on NaCl

### ISSUE THREAD

**Issue by dsnet** [golang/go#21728]
Consider [the following snippet](https://play.golang.org/p/hTZXuQeNqX):
```go
f, err := ioutil.TempFile("", "")
if err != nil {
	log.Fatal(err)
}
// f.Truncate(1000)
if _, err := f.Seek(1000, io.SeekCurrent); err != nil {
	log.Fatal(err)
}
```

On NaCl, this current fails with:
```
seek /tmp/054003078: Invalid argument
```

If you uncomment the `Truncate`, then it works again. This is contrary to every other OS that Go supports, where you can seek past EOF and start writing and everything in-between is implicitly filled with zeros.

**Comment by bradfitz** [comment]
Closing nacl bugs, as we're removing nacl (#30439)
