### ISSUE TITLE
godoc: starting with -play option locally results in error

### ISSUE THREAD

**Issue by martisch** [golang/go#21725]
go tip e3f3adedcdbe3649e5de2980e85ab054e9d67acf

$ go get -u golang.org/x/tools/cmd/godoc
$ godoc -http=:8080 -play

godoc page does not load correctly.

2017/09/01 09:02:53 godoc.html.Execute: template: godoc.html:58:8: executing "godoc.html" at <$.Share>: can't evaluate field Share in type godoc.Page

if i go to: $GOPATH:src/golang.org/x/tools/godoc/static
$ go run makestatic.go
static.go gets updated which changes $.Share to $.GoogleCN.

It could be that in https://github.com/golang/tools/commit/4e70a1b26a7875f00ca1916637a876b5ffaeec59
static.go should have been updated which seems to not be updated automatically.

/cc @andybons

**Comment by silvernode** [comment]
This is still happening in 1.9.1

**Comment by andybons** [comment]
The change was not cherry-picked into the release branch: https://go.googlesource.com/go/+log/go1.9.1

@broady should we pull this in (amongst some of the other changes like the CDN stuff) for the next release? I’m not familiar enough with our release process to make the call :)

**Comment by tmc** [comment]
this still seems to be a problem in 1.9.2

**Comment by martisch** [comment]
This bug is closed so wont get noticed in the general issue list. To get attention for this for 1.9 it might be better to open a new bug (and reference this bug for a CL with fix on tip).
