### ISSUE TITLE
os/exec: extraneous quote escaping in argument received by spawned program, on Windows

### ISSUE THREAD

**Issue by thanhps42** [golang/go#21739]
I got wrong arg in exec.Command

### What version of Go are you using (`go version`)?
go version go1.8.3 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Code\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\thanh\AppData\Local\Temp\go-build383552903=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
Call exec.Command.
Code: https://play.golang.org/p/NHfMcWdh45

### What did you expect to see?
![](https://image.prntscr.com/image/ShZGA_W8R1KEx26r2z9VwA.png)

### What did you see instead?
![](https://image.prntscr.com/image/QHlwXy6aTqC6fTGG4nZPJg.png)

**Comment by odeke-em** [comment]
@thanhps42 I've updated the issue title to the best that I could make out of the images that you posted. Is the issue that os/exec extraneously escapes quotes in arguments? If not, please help me update the title.

I personally don't have access to a Windows computer but if anyone does, please feel free to reproduce and debug this bug.

**Comment by davecheney** [comment]
Please try

https://play.golang.org/p/Hju_Cl5m2Y

I suspect it will have the same result, but will be informative.

**Comment by thanhps42** [comment]
Yes, same result.
P/s: sorry for my bad English.

**Comment by davecheney** [comment]
That's what I thought, the escaping may be coming from something the windows version of the exec package is doing. Have you tried removing the quoting, it's probably not necessary

**Comment by thanhps42** [comment]
Yes, in my example, quoting is not necessary, but if argument is **--profile-directory="Profile 1"**, i need quoting because i have spacing.
Thanks.

**Comment by davecheney** [comment]
As an experiment, try without the quotes, see what happens.

**Comment by thanhps42** [comment]
I have update my problem (please see picture again), can't work without quotes

**Comment by davecheney** [comment]
Thank you. I'm not a windows expert so I'll have to hand it off here

Perhaps this is not supported, or maybe you have to pass it through cmd.exe
to properly escape the arguments.

Perhaps you're supposed to escape spaces with backslash rather than quoting
them.

Paging @bketelsen @brainman.

**Comment by alexbrainman** [comment]
> if argument is --profile-directory="Profile 1", i need quoting because i have spacing.

You do not need " to escape spaces inside the argument. When you use os/exec.Command to build Windows command, standard library should do all escaping you need. See makeCmdLine function in runtime package for details. So (I have not tested it)
```
cmd := exec.Command("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "--profile-directory=Profile 2")
```
should work. Please try it.

Alex

**Comment by thanhps42** [comment]
@alexbrainman Thanks for your help. It's work like a charm (y)

**Comment by wannaka** [comment]
ไม่เป็นไรคะ  ยินดีที่ได้ช่วย
Are you o.k.
Thank you respond 😘😍😘😍😘😍😘😍😘
