### ISSUE TITLE
regexp: syntax.wordRune() is a duplicate of syntax.IsWordChar()

### ISSUE THREAD

**Issue by sylvinus** [golang/go#21742]
Is there a valid reason for keeping both functions?

**Comment by odeke-em** [comment]
Hmm, there seems to be a difference, being that `IsWordChar` recognizes `_` but `wordRune` doesn't, as per the code pasted below:

### IsWordChar
https://github.com/golang/go/blob/03c3bb5f843cbda7382b5618de82a74adb779393/src/regexp/syntax/prog.go#L104-L109

### WordRune
https://github.com/golang/go/blob/03c3bb5f843cbda7382b5618de82a74adb779393/src/regexp/syntax/prog.go#L250-L257

I haven't examined the entire context of the functions but it seems like perhaps we shouldn't be removing `wordRune` before figuring out what cases it handles.

**Comment by odeke-em** [comment]
Oops, my biggest apologies, it is 5:25AM and I hadn't noticed that wordRune recognizes `_` too, so they are the same. You have my vote now :)
