### ISSUE TITLE
cmd/compile: failure to reject initialization loop

### ISSUE THREAD

**Issue by mdempsky** [golang/go#21752]
cmd/compile accepts this bit of code, while go/types and gccgo reject it as an initialization cycle ("A refers to A"):

    var A = func() int {
    	if false {
    		return A
    	}
    	return 0
    }()

https://play.golang.org/p/jpUoGbyJqX

Related #21750. The common issue here is probably that we're performing initialization order analysis based on the optimized/inlined functions rather than the original Go source.

/cc @griesemer

**Comment by griesemer** [comment]
Marking 1.10 so it stays on radar.

**Comment by odeke-em** [comment]
Commenting here to add this to my priority list or at least radar, for Go1.12.

**Comment by mdempsky** [comment]
This was fixed by switching to types2.
