### ISSUE TITLE
net: export writeBuffers() and buffersWriter

### ISSUE THREAD

**Issue by gobwas** [golang/go#21756]
Hello!

Looking at `net.Buffers.WriteTo()` implementation one can find that it uses type assertion to non-exported type `net.buffersWriter`. The proposal is to export this type and methods which implement it. 

Two things:
1) When someone wants to wrap `net.Conn` to get some i/o statistics, say:
```go
type ConnWatcher struct {
    c net.Conn
    n int64
}
func (c *ConnWatcher) Write(p []byte) (int, error) {
    n, err := c.conn.Write(p)
    c.n += int64(n)
    return n, err
}
```

It becomes impossible to use `writev()` syscall – `ConnWatcher` has no way to implement non-exported `net.buffersWriter` interface.

2) When someone wants to wrap concrete `*net.TCPConn` (rare case, but possible) to decorate some write behaviour:
```go
type CipherConn struct {
    *net.TCPConn                                
    Encode func([]byte) []byte
}
func (c CipherConn) Write(p []byte) (int, error) {
    return c.TCPConn.Write(c.Encode(p))
}

// Somewhere in the application.
var bs net.Buffers
var cc CipherConn
bs.WriteTo(cc) 
```
The last line of the example above `bs.WriteTo(cc)` will produce `cc.TCPConn.writeBuffers(bs)` call, sending raw data without encoding.

Regards,
Sergey.

**Comment by funny-falcon** [comment]
Hidden behavior that is difficult to use right.

**Comment by odeke-em** [comment]
Looks similar to https://github.com/golang/go/issues/21676 in which @zombiezen talks about how frustrating it is that writeBuffers is unexported.

**Comment by gobwas** [comment]
Sorry, for open/reopen spam ) Should I close it as a duplicate or keep it opened until Go1.11?

**Comment by ianlancetaylor** [comment]
The two seem slightly different, let's keep them both for now.

**Comment by ianlancetaylor** [comment]
After more thought, closing as dup of #21676 .
