### ISSUE TITLE
Bench timing is wrong by 1e9 on Windows

### ISSUE THREAD

**Issue by george-polevoy** [golang/go#21766]
### What version of Go are you using (`go version`)?
go version go1.9 windows/amd64

### Does this issue reproduce with the latest release?
YES
The same result for 1.8.3

### What operating system and processor architecture are you using (`go env`)?
go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\gp\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

Windows 10 Enterprise, 1703
Intel Core i7-6820HQ @ 2.7GHz 

### What did you do?
go get github.com/george-polevoy/go-bench-bug
cd $GOPATH/src/github.com/george-polevoy/go-bench-bug/popcount
go test -bench .

>> A link on play.golang.org is best.

Does not work, as there is no way to run bench online. I suspect it's windows only, and some of the timing code just hangs on play.golang.org

### What did you expect to see?
- I expect to see 20 ms/op, not 0.02 ns/op
and 100 ms/op, not 0.1 ns/op

- I expect to see the actual number of experiments

### What did you see instead?
Here is the log, it's supplied with custom timings using time.Now(), which seem more realistic.
`Started` and `Now` come from custom logging using `b.Logf(...)`

When the benchmark timing is below one second, it's timing is wrong (suspected multiplication by 1e9 (number of nanoseconds in sec) and the total count is always 2000000000, even there was no such number of actual experiments.

```
BenchmarkPopcountExpr-8         2000000000               0.02 ns/op
--- BENCH: BenchmarkPopcountExpr-8
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.0320259 -0500 CDT m=+0.006963700, Now: 2017-09-05 08:18:34.0670643 -0500 CDT m=+0.042002100, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.0680657 -0500 CDT m=+0.043003500, Now: 2017-09-05 08:18:34.1050641 -0500 CDT m=+0.080001900, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.1050641 -0500 CDT m=+0.080001900, Now: 2017-09-05 08:18:34.1420667 -0500 CDT m=+0.117004500, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.1420667 -0500 CDT m=+0.117004500, Now: 2017-09-05 08:18:34.1770712 -0500 CDT m=+0.152009000, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.1780789 -0500 CDT m=+0.153016700, Now: 2017-09-05 08:18:34.2131057 -0500 CDT m=+0.188043500, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.2140855 -0500 CDT m=+0.189023300, Now: 2017-09-05 08:18:34.2511749 -0500 CDT m=+0.226112700, Side Effect: 114434624
        popcount_test.go:34: Expr. Started: 2017-09-05 08:18:34.2511749 -0500 CDT m=+0.226112700, Now: 2017-09-05 08:18:34.2871388 -0500 CDT m=+0.262076600, Side Effect: 114434624
BenchmarkPopCountLoop-8         2000000000               0.10 ns/op
--- BENCH: BenchmarkPopCountLoop-8
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:34.2871388 -0500 CDT m=+0.262076600, Now: 2017-09-05 08:18:34.4866921 -0500 CDT m=+0.461629900, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:34.4872427 -0500 CDT m=+0.462180500, Now: 2017-09-05 08:18:34.6887537 -0500 CDT m=+0.663691500, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:34.6892646 -0500 CDT m=+0.664202400, Now: 2017-09-05 08:18:34.8942921 -0500 CDT m=+0.869229900, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:34.8952927 -0500 CDT m=+0.870230500, Now: 2017-09-05 08:18:35.0939308 -0500 CDT m=+1.068868600, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:35.0944107 -0500 CDT m=+1.069348500, Now: 2017-09-05 08:18:35.2929045 -0500 CDT m=+1.267842300, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:35.2934157 -0500 CDT m=+1.268353500, Now: 2017-09-05 08:18:35.4929294 -0500 CDT m=+1.467867200, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:35.4934214 -0500 CDT m=+1.468359200, Now: 2017-09-05 08:18:35.6944918 -0500 CDT m=+1.669429600, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:35.6954675 -0500 CDT m=+1.670405300, Now: 2017-09-05 08:18:35.8949589 -0500 CDT m=+1.869896700, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:35.89546 -0500 CDT m=+1.870397800, Now: 2017-09-05 08:18:36.0939904 -0500 CDT m=+2.068928200, Side Effect: 114434624
        popcount_test.go:44: Expr. Started: 2017-09-05 08:18:36.094459 -0500 CDT m=+2.069396800, Now: 2017-09-05 08:18:36.2935989 -0500 CDT m=+2.268536700, Side Effect: 114434624
        ... [output truncated]
PASS
ok      github.com/george-polevoy/go-bench-bug/popcount 2.295s
```

**Comment by cznic** [comment]
Your benchmarks ignores [b.N completely](https://github.com/george-polevoy/go-bench-bug/blob/aec399de59d61491cc7c5727390379d4be161b8d/popcount/popcount_test.go#L28). Please [check the documentation](https://golang.org/pkg/testing/#hdr-Benchmarks) on how to write benchmarks.
