### ISSUE TITLE
redeclation of variable

### ISSUE THREAD

**Issue by itairegev** [golang/go#21767]
### What version of Go are you using (`go version`)?
1.8.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
declared a function that returns two return values, the first is checked for redeclartion, the second is not...
https://play.golang.com/p/woNdx9l-FU

### What did you expect to see?
an error, "no new variable err"

### What did you see instead?
go allowed err to be re-declared

**Comment by mvdan** [comment]
`:=` can be used as long as any of the identifiers on the left are new. This is working as intended.

> Unlike regular variable declarations, a short variable declaration may redeclare variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-blank variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original.
