### ISSUE TITLE
1.9 - long time to compile

### ISSUE THREAD

**Issue by c0ldhell** [golang/go#21762]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.9 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Arch Linux, AMD Turion II P540 Dual-Core @ 2x 2.4GHz, 4 Gb RAM
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build490886913=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

My project writen on pure Go, without any C bindings. On previously release (1.8.3) time to compilation ~3 sec. Now I update compiler to 1.9 and time to compile has increased to 23-26 sec and the load on the processor reaches 100% of what was not before. Ok, well, I thought that the problem in the build of the package for my Linux distribution and download compiler from https://golang.org/dl But the problem did not disappear. 

Then I checked the compilation time on another project writen on pure Go and also the compilation time increased several times. 

And full build log https://gist.github.com/c0ldhell/22e820822075f8f9a3c7031f419c9de9

**Comment by cznic** [comment]
The build log is useful but you also need to share what do you mean by "compilation", ie. the comand that was invoked for other not to have to guess. Note that, for example, both `go install` and `go build` may involve "compilation", but in the first case all dependencies are installed while in the later case none; meaning next `go install` can perform quickly, but a subsequent `go build` may have to go through compilation of all dependencies  all over again.

**Comment by c0ldhell** [comment]
@cznic compilation I mean `go build`. Also I tried to recompile all dependencies with a command `go build -a`.

**Comment by cznic** [comment]
`go build` does not install any dependencies. Adding -a does even the opposite, it ignores any already installed ones. Use `go install`.

**Comment by mvdan** [comment]
As @cznic said, you want `go build -i` or `go install` to cache all the build artifacts. Otherwise you might be building from scratch every time, which is what `go build -a` forces.

**Comment by c0ldhell** [comment]
So, that is why such a slow compilation? But 1.8 compiles quickly and without all this.

**Comment by mvdan** [comment]
Possibly because with 1.8 you did run either of those commands at some point, and `go build` reuses them.

Have you tried the commands that I described?

**Comment by c0ldhell** [comment]
@mvdan Yes, after `go build -i` compilation stay fast. Maybe I need `go biuld -i` for all packages in $GOPATH?

**Comment by davecheney** [comment]
It's likely that you used go get when you had 1.8.3, go get by default also
caches build artifacts.

I cannot recommend strongly enough always using the -v flag to go build /
install. This will print out the name of each package as it compiles
allowing you to quickly assert how much work is being done by the length of
the output.

**Comment by mvdan** [comment]
This seems to have been just a misunderstanding of how `go build` currently works, so I'm going to close this.

**Comment by go101** [comment]
@c0ldhell maybe deleting the pkg folder under GOPATH helps.
