### ISSUE TITLE
strconv.FormatFloat:What exactly 'round' mean?

### ISSUE THREAD

**Issue by liaojianqi** [golang/go#21764]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/loin/mycode/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

ubuntu 16.04

### What did you do?
a := 1.1235
s := strconv.FormatFloat(a, 'f', 3, 64)
fmt.Println(s)

### What did you expect to see?
It's should be print "1.124"

### What did you see instead?
It's  print "1.123"

godoc said:

/ FormatFloat converts the floating-point number f to a string,
// according to the format fmt and precision prec.  It rounds the
// result assuming that the original was obtained from a floating-point
// value of bitSize bits (32 for float32, 64 for float64).

I think "round"  mean if the last number is less than or equal four should be discard,  if the last number is greater than or equal five should be add 1.
but in FormatFloat, it's not. It seems that if the last number is less than or equal five, it should be discard.
and if the last number is greater than or equal six it should be add 1.

**Comment by cznic** [comment]
The assumption that float64(1.1235) is >= realNumber(1.1235) is not true: https://play.golang.org/p/U9Scvvyrbp.
