### ISSUE TITLE
Can `gobin` be inferred as well?

### ISSUE THREAD

**Issue by zachgersh** [golang/go#21775]
### What version of Go are you using (`go version`)?

`1.9`

Hey all,

Now that we are automagically setting your `$GOPATH` for users would it be so bad if we also at the same time set your `$GOBIN` too?

A user would be able to see that both vars are set when using `go env`

I don't really see too much harm in it and it prevents people who don't set their `$GOBIN` from having to configure it when the attempt to do something like a `go install`

cc @campoy since I know he had a hand in the original PR for `$GOPATH`.

Wanted feedback before I attempted the change.

**Comment by davecheney** [comment]
Yes, just don't set GOBIN and it will default to $GOPATH/bin, which
defaults to $HOME/go, so add $HOME/go/bin to your $PATH is all you need to
do.

**Comment by zachgersh** [comment]
@davecheney strange - I don't see that as happening. I've left both my `$GOBIN` and `$GOPATH` intentionally unset (on darwin) and I get:

- `$HOME/go` as my `$GOPATH` (expected)
- `""` as my `$GOBIN` (sounds wrong)

This is reported by `go env`

**Comment by davecheney** [comment]
IMO, just ignore GOBIN, you can safely leave it unset and binaries will be
placed by go install in a bin subdirecty in the first element of your
GOPATH. Or simply put, $HOME/go/bin

**Comment by shurcooL** [comment]
> Now that we are automagically setting your `$GOPATH` for users would it be so bad if we also at the same time set your `$GOBIN` too?

@zachgersh That's already the case. It has been that way since Go 1.0 I believe.

`GOBIN` env var is documented at https://golang.org/cmd/go/#hdr-GOPATH_environment_variable as:

```
If the GOBIN environment variable is set, commands are installed to the
directory it names instead of DIR/bin. GOBIN must be an absolute path.
```

So, nothing needs to be done. Leave `GOBIN` unset. It exists to be able to override the default installation directory.

>  binaries will be placed by go install in a bin subdirectory in the first element of your GOPATH

Correction, when unset, binaries are placed in the bin directory of the workspace where the package main is located. Not neccessary the first.

For a given import path, `go list -f '{{.Target}}' import/path` prints where the binary would go.

```Go
Target        string // install path
```

**Comment by zachgersh** [comment]
@shurcooL / @davecheney,

Thanks for the replies. I am not seeing the behavior that you are bosh describing.

When (in go 1.9) I do something like this

`go install subdir/main.go` I get an error message:

`go install: no install location for .go files listed on command line (GOBIN not set)`

`go build` is of course fine with this sort of thing.

Am I doing something wrong here?

**Comment by cznic** [comment]
The argument of `go install` is an import path, not a file path.

**Comment by zachgersh** [comment]
@cznic - right, so why is this valid:

```
$GOBIN=$GOPATH/bin go install subdir/main.go
```
I know I almost always forget that I can do

```
go install github.com/myuser/myrepo
```
 due to the fact that I probably already have the repo on my machine.

**Comment by shurcooL** [comment]
> Am I doing something wrong here?

`go install` is a command that works best on import paths. You'll have a better experience if you use it with that. For example, if you want to install a Go package with import path `github.com/golang/example/hello`, all you have to do is:

```
go install github.com/golang/example/hello
```

You don't need to worry about specifying individual .go files inside that package, the build system takes care of that.

See https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies and https://golang.org/doc/code.html for more information.

**Comment by shurcooL** [comment]
> so why is this valid

From https://golang.org/cmd/go/#hdr-Description_of_package_lists:

> As a special case, if the package list is a list of .go files from a single directory, the command is applied to a single synthesized package made up of exactly those files, ignoring any build constraints in those files and ignoring any other files in the directory.

It's a special case. It's not the primary mode of operation and should be used in special situations when the consequences are well understood.

> I know I almost always forget that I can do `go install github.com/myuser/myrepo`

Try not to forget about it, it's a very useful command.

If you happen to be inside a directory that is close to where the package is, you can specify a [relative import path](https://golang.org/cmd/go/#hdr-Relative_import_paths) in the command line to achieve the same effect with less typing. E.g.:

```
$ go install github.com/golang/example/hello

$ cd $GOPATH/src/github.com/golang/example
$ go install ./hello

$ cd ./hello
$ go install
```

All 3 `go install`s above do the same thing, install the `hello` command.

**Comment by shurcooL** [comment]
It seems that it's not that there's an issue related to GOBIN, but that `go install` behavior was not understood. Hopefully the above answers have helped clear things up. I also highly recommend reading https://golang.org/cmd/go for more details, it describes the behavior in a very concisely and accurately.

I'll close this because Go doesn't use the issue tracker for questions, but if you have any further questions, please see http://golang.org/wiki/Questions.
