### ISSUE TITLE
docs/articles/wiki: example output for DataStructures has wrong capitalization for page

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#21773]
Mistake in caps "P".

### What did you do?
Learn example on page https://golang.org/doc/articles/wiki/
Execute code:
'''
func main() {
    p1 := &Page{Title: "TestPage", Body: []byte("This is a sample Page.")}
    p1.save()
    p2, _ := loadPage("TestPage")
    fmt.Println(string(p2.Body))
}
'''
### What did you expect to see?
This is a sample Page.

### What did you see instead?
On web page:
'''
$ go build wiki.go
$ ./wiki
This is a sample page.
'''

**Comment by odeke-em** [comment]
@Konstantin8105 thank you for reporting this. Would you like to submit a CL fixing this as per https://golang.org/doc/contribute.html (just in case you need the reference)? If not, no worries, either way great catch.

**Comment by Konstantin8105** [comment]
Yes I will fix that.
