### ISSUE TITLE
bytes.Replace only first

### ISSUE THREAD

**Issue by manland** [golang/go#21787]
#### What did you do?

https://play.golang.org/p/N0NCbVF4Q4

#### What did you expect to see?

Each line should be replaced. When i use only string (by converting bytes) all works https://play.golang.org/p/Zut2O5Waqk. I don't know if it's related to #21149 ?

#### What did you see instead?

Only first line is replaced

#### System details

```
go version go1.9 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/projects/go_workspace"
GORACE=""
GOROOT="/applications/go1.9"
GOTOOLDIR="/applications/go1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032382008=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.9
uname -sr: Linux 4.4.0-93-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.23-0ubuntu9) stable release version 2.23, by Roland McGrath et al.
gdb --version: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
```

**Comment by magical** [comment]
`regexp.FindAllMatches` returns slices of the original byte slice that you pass to it. When you later `append` to `result[1]`, this modifies the underlying slice, which is shared with `result[0]`, partially overwriting it.

https://play.golang.org/p/89QS0NGK3R

**Comment by ianlancetaylor** [comment]
Closing because there does not seem to be a bug here.  Please comment if you disagree.
