### ISSUE TITLE
cmd/go: TestBuildmodePIE, TestDuplicateGlobalAsmSymbols failing on tip

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21783]
The darwin-amd64-10_8 builds are currently failing, as seen at https://build.golang.org/#short, starting with commit 84188296e93dd4d26cb0a75a03a9096794e01e2f:

```
--- FAIL: TestBuildmodePIE (2.53s)
	go_test.go:4406: running testgo [build -buildmode=pie -o /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/gotest642204385/main /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/gotest642204385/main.go]
	go_test.go:4406: standard error:
	go_test.go:4406: # command-line-arguments
		/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/pkg/tool/darwin_amd64/link: /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
		Assertion failed: (linked_addr_pos != line_table_map.end()), function FixReferences, file /SourceCache/dwarf_utilities/dwarf_utilities-114/source/DWARFdSYM.cpp, line 3710.
		
		
	go_test.go:4406: go [build -buildmode=pie -o /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/gotest642204385/main /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/gotest642204385/main.go] failed unexpectedly: exit status 2
FAIL
FAIL	cmd/go	81.907s
```

_(Source: https://build.golang.org/log/137c0b0d8928d3c5dc0028c824c1d7491231ea37.)_

This was [CL 60530](https://golang.org/cl/60530). /cc @aarzilli @heschik

It looks like the legitimate failure was [missed](https://go-review.googlesource.com/c/go/+/60530#message-6f6332994309158b2b1ef3f11b73bd4c1fe8f5dc) there due to a false positive by an intermittent trybot failure, tracked in issue #19320.

**Comment by heschik** [comment]
I'll roll back, though for the record I don't think the failure in the trybot run is the same thing. Maybe something conflicted since they ran? My mistake for waiting so long to merge if so.
