### ISSUE TITLE
x/crypto/ssh: how do you parse the modelist of a ptyRequestMsg?

### ISSUE THREAD

**Issue by nhooyr** [golang/go#21781]
This is how the modelist is marshalled https://github.com/golang/crypto/blob/81e90905daefcd6fd217b62423c0908922eadb30/ssh/session.go#L192-L199

But how would one cleanly unmarshal it? You can't just unmarshal it into a slice or a struct so the only way I can think of is slicing the modelist into groups of the length of a single key value pair (5, but you'd have to know that before) and then individually marshalling each of those slices into their own structures. That's what I'm doing now and it works, but it's extremely janky because you need to know the length of a single key value pair preemptively.

Is there any better way to do it?

**Comment by jeffallen** [comment]
That message format is defined in the RFC: https://www.ietf.org/rfc/rfc4254.txt

See section 8. There are notes there saying parsing should happen pair by pair, and should stop on an unknown pair.

**Comment by nhooyr** [comment]
But in order to parse a pair, I need to know that the length of the pair is 5 bytes. It's kinda janky.

In that case, would you say my approach is correct?

If my approach is not clear, here is some example code:

```go
// pretend modelist is the slice of bytes of the modelist.
var modelist []byte
for {
	type mode struct {
		Key byte
		Val uint32
	}
	m := &mode{}
	err := ssh.Unmarshal(modelist[:5], m)
	if err != nil {
		panic(err)
	}
	println(m.Key)
	println(m.Val)
	println("====")

	modelist = modelist[5:]
	if len(modelist) == 1 {
		return
	}
}
```

**Comment by nhooyr** [comment]
Ah, I got it, I need to use `binary.Size`.

```go
// pretend modelist is the slice of bytes of the modelist.
var modelist []byte
type mode struct {
	Key byte
	Val uint32
}
var m mode
var lenMode = binary.Size(m)
for len(modelist) < lenMode {
	err := ssh.Unmarshal(modelist[:lenMode], m)
	if err != nil {
		panic(err)
	}
	println(m.Key)
	println(m.Val)
	println("====")
	modelist = modelist[lenMode:]
}
```

That LGTM so I'll close this issue.
