### ISSUE TITLE
x/crypto/nacl/auth: Use constants consistently in Verify

### ISSUE THREAD

**Issue by tv42** [golang/go#21788]
https://godoc.org/golang.org/x/crypto/nacl/auth has

```
const (
    // KeySize is the size, in bytes, of an authentication key.
    KeySize = 32
)
func Sum(m []byte, key *[KeySize]byte) *[Size]byte
func Verify(digest []byte, m []byte, key *[32]byte) bool
```
Is there a good reason `Verify` doesn't take `key *[KeySize]byte`? This seems like the existence of the constant was forgotten.

**Comment by ianlancetaylor** [comment]
CC @kevinburke

**Comment by kevinburke** [comment]
good question, thanks - will take a look tonight
