### ISSUE TITLE
net/http: document that it's illegal to reuse a Request concurrently from multiple goroutines

### ISSUE THREAD

**Issue by twmb** [golang/go#21780]
Incorrect `errRequestCanceled` errors occur when reusing `http.Request` structs.

There is a small race in reusing `Transport`'s `reqCanceler` map, where a finishing request can override an active request dial's canceler. I suspect this is what https://github.com/golang/go/issues/19653 was running into, and Brad hinted at this.

The problem:

The code centers around transport.go's `RoundTrip` block of code [here, L400-L413](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L400-L413).

For two requests **a** and **b** that execute back to back:
**a** sees a body's EOF: [L1622-L1624](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L1622-L1624),  
**b** begins, enters `RoundTrip`, tries to [`getConn`](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L400), no idle conns exist, **b** sets the request's canceler ([L940](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L940), important), and a large select happens: [L948-L986](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L948-L986)  
**a**'s `persistConn` running gets notified of the `bodyEOF`, sets its transport's request canceler for this request to nil ([L1656](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L1656)) overriding the canceler that was just set by B, and goes to `tryPutIdleConn` (assuming other conditions are successful): [L1655-L1661](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L1655-L1661)  
**a**''s `tryPutIdleConn` sees a `waitingDialer`: [L704-L706](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L704-L706)  
**b**'s dial select receives the `persistConn` that just ran **a**: [L976-L986](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L976-L986)  
**b**'s `RoundTrip` `getConn` returns successfully and goes into `pconn.roundTrip` ([L400-L413](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L400-L413), the main block)  
`roundTrip` tries to replace the transports request canceler for **b** with the `persistConn`'s `cancelRequest`: [L1889-L1891](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L1889-L1891)  
`replaceReqCancel` fails because the prior replacement deleted the request from the transport's `reqCanceler` map, and if the request does not exist in the map, the canceler for it cannot be replaced: [L856-L865](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L856-L865)  
This causes `roundTrip` to return `errRequestCanceled`: [L1893](https://github.com/golang/go/blob/6c102e141c5858d1b900afad8dd616370f6091bb/src/net/http/transport.go#L1893)

Also note that this is only the http1 stack and is harder to notice against URLs that have redirects.

### What version of Go are you using (`go version`)?
1.8.3, 1.9, tip

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/twmb/go"
GORACE=""
GOROOT="/home/twmb/go/go"
GOTOOLDIR="/home/twmb/go/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build465265467=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
https://play.golang.org/p/BP7YCP2D4J
`go test -bench . -benchtime 10s` (should happen quickly)

### What did you expect to see?
No panic.

### What did you see instead?
A panic.

**Comment by andybons** [comment]
@bradfitz

**Comment by odeke-em** [comment]
@twmb thank you for filling this issue!

I am currently at tip d4e936c
```shell
$ go version
go version devel +d4e936c Tue Apr 24 20:21:08 2018 +0000 darwin/amd64
```
and I can't reproduce this issue
<img width="585" alt="screen shot 2018-04-24 at 4 52 23 pm" src="https://user-images.githubusercontent.com/4898263/39219531-e617d1d8-47df-11e8-9095-19ace8861e16.png">

/cc @tombergan @bradfitz

**Comment by odeke-em** [comment]
Thanks for the check-in @twmb and run on Linux, apparently I am living in a bubble with my Darwin AMD64 environment.

**Comment by twmb** [comment]
I'm curious how this could be different on Darwin because none of the race is Darwin specific, but I'd have to dig back in.

**Comment by bradfitz** [comment]
This bug's title ("when reusing requests") made me think this was about back-to-back serial re-use of Requests, but the description and repro above (https://play.golang.org/p/BP7YCP2D4J) show that this is really about about concurrent use of the same request.

I suppose this could be made to work at least for GETs, but I'm not sure it's worth it. If it doesn't work for POSTs or things with bodies, I think I'd rather just document one consistent rule: that you can't use a Request concurrently by multiple goroutines.

**Comment by twmb** [comment]
Changing the benchmark to be serial reproduces this for me as well:

```
func BenchmarkDeadreq(b *testing.B) {
	req, err := http.NewRequest("GET", "http://www.example.com", nil)
	chk(err)
	client := new(http.Client)
	for i := 0; i < b.N; i++ {
		resp, err := client.Do(req)
		chk(err)
		go func() {
			_, err = io.Copy(ioutil.Discard, resp.Body)
			chk(resp.Body.Close())
			chk(err)
		}()
	}
}
```

As far as I can tell, this is still reusing a request serially back-to-back.

**Comment by bradfitz** [comment]
That still looks concurrent to me. You're not done with the request+response pair by the time of your next `Do` call.

**Comment by twmb** [comment]
Agreed, I was drafting a response along those lines. I would be fine with documentation that a request cannot be request until after the response body is closed.
