### ISSUE TITLE
spec: unclear whether int, bool, string are considered defined types

### ISSUE THREAD

**Issue by garvitjuniwal** [golang/go#21785]
As per the spec, one of the cases in which a value x is assignable to a variable of type T ("x is assignable to T") is

x's type V and T have identical underlying types and at least one of V or T is not a defined type.

Again, from the spec, 

A type definition creates a new, distinct type with the same underlying type and operations as the given type, and binds an identifier to it.
The new type is called a defined type. It is different from any other type, including the type it is created from.

Thus by definition int, string, bool are not defined types. But it is still an error to assign an int to another defined type with the same underlying type int.

```
type A int

var a A
var b int
a = b // this is an error
```
https://play.golang.org/p/bSE4nIzXhF

**Comment by myitcv** [comment]
From https://golang.org/ref/spec#Types:

> Named instances of the boolean, numeric, and string types are predeclared

I read this as  _"defined types are predeclared for the boolean, numeric and string types and are identified by `int`, `int32`, `bool`, `string` etc"_

Hence they are defined types.

But the sentence that follows in the spec confuses things:

> Other named types are introduced with type declarations

It is, I think, a hangover from pre-alias days, as was picked up in [this comment](https://github.com/golang/go/issues/21738#issuecomment-326733588)

@griesemer @mdempsky - should that reference to "named type" now be "defined type"?

**Comment by mdempsky** [comment]
Yes, `int`, etc are defined types.

As @myitcv points out, we used to just say "named" type. Now that there are type aliases (which have names but may refer to an underlying anonymous type literal), we instead say "defined" type to refer to named types that aren't aliases.

**Comment by griesemer** [comment]
We still have the notion of a "named type": Like before (the split into defined and alias types) it's a type that has a name. Unlike before, having a name alone doesn't give it special meaning; we also have to look at its declaration. We need the notion of a named type in other places, such as where a type name is needed.

The predeclared types are named types (they have a name), and most of them (expect for byte and rune) are defined types. It's true that they are somewhat special insofar as their underlying types are themselves.

We could call the predefined types but that would require yet another term to be introduced. Instead, I opted for simply stating explicitly which predeclared types are defined types and which ones are aliases. CL forthcoming.
