### ISSUE TITLE
database/sql: Conn's doc has a typo saying "rather a pool" instead of "rather than a pool"

### ISSUE THREAD

**Issue by odeke-em** [golang/go#21798]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Not Applicable

### What did you do?
Visited https://golang.org/pkg/database/sql/#Conn to read the docs for Conn

### What did you expect to see?
`Conn represents a single database session rather than a pool of database sessions.`

### What did you see instead?
`Conn represents a single database session rather than a pool of database sessions.`
<img width="934" alt="screen shot 2017-09-07 at 9 50 29 pm" src="https://user-images.githubusercontent.com/4898263/30195527-116ad394-9417-11e7-8cc5-e9f678b144f4.png">

Just requires us to add `than` after `rather`

**Comment by dvrkps** [comment]
I try to fix this.
