### ISSUE TITLE
go/constant: remove now-unnecessary import comment

### ISSUE THREAD

**Issue by willfaught** [golang/go#21791]
As in:

```go
package constant // import "go/constant"
```

It's the same as the only path. Same for go/types.

**Comment by dominikh** [comment]
Both packages originally lived in the x/tools subrepo. The import comments are a remnant of that. When the packages were moved, the comments were simply updated (likely automatically.)

**Comment by willfaught** [comment]
Interesting. I don't see x/tools/go/constant or x/tools/go/types, so is the import comment necessary?

**Comment by ianlancetaylor** [comment]
I've turned this into an issue.  Note that we don't use the issue tracker for questions; if you have questions in the future please use a forum.  See https://golang.org/wiki/Questions.  Thanks.
