### ISSUE TITLE
cmd/compile: println compiles to nothing

### ISSUE THREAD

**Issue by randall77** [golang/go#21808]
At tip,
```
package main

import "fmt"

func main() {
	fmt.Printf("A\n")
	println()
	fmt.Printf("B\n")
}
```
Should print
```
A

B
```
Instead prints
```
A
B
```

Looks like `println` is getting compiled to nothing. Or at least, nothing that prints.  Looking at the assembly there is a `printlock`/`printunlock` pair, but nothing in between.
Doesn't seem to affect any release, so labeling 1.10.

**Comment by odeke-em** [comment]
@randall77 I can confirm that CL https://go-review.googlesource.com/c/go/+/55097 is the one that changed this behavior.

**Comment by randall77** [comment]
@odeke-em Thanks, that helps a lot.
