### ISSUE TITLE
os/exec.Command does not respect sleep on Windows

### ISSUE THREAD

**Issue by Chhed13** [golang/go#21801]
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/arotchev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build931556897=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

1. Wrote and compile for Windows_amd64 `GOOS=windows GOARCH=amd64 go build main.go 
` put it on Windows machine:
``` 
package main
import (
	"os/exec"
)
func main() {
	exec.Command("C:/test.cmd").Run()
} 
```
2. Wrote test.cmd and put it C:/test.cmd
```
echo %time:~-11%  >> test.log
ping 127.0.0.1 -n 5
echo %time:~-11%  >> test.log
timeout 5 /nobreak
echo %time:~-11%  >> test.log
```
3. Run test.cmd directly
4. Run test.cmd via main.exe

### What did you expect to see?
Direct run and via go code did the same - execution took approximately 10 seconds. Content of test.log after direct run
```
11:02:09.71  
11:02:13.91 
11:02:18.16 
```

### What did you see instead?
Execution via go code took approximately 5 seconds. Content of test.log
```
11:02:01.89  
11:02:05.96 
11:02:06.04 
```
It respects `ping`, but trim `timeout`. Why I compare ping and timeout can be found [here](https://ss64.com/nt/timeout.html)

I tested it on:
* Windows 10 and on Windows server 2012 r2 machines
* Tried use .bat and .cmd extensions
* Tried run as `cmd /c C:/test.cmd`
Behavior was always the same.

I tried to debug this with logging and it leaded me to Syscalls:
```
exec.Run() 
-> exec.Wait() 
-> os.Process.Wait() //
-> os.wait()  //from exec_windows.go
-> s, e := syscall.WaitForSingleObject(syscall.Handle(handle), syscall.INFINITE)
```
Return from the last one happened earlier then expected all the time.

**Comment by alexbrainman** [comment]
The problem here is that timeout is crashing because it does not support stdin redirection. It also helps not to ignore commands stderr.
```
c:\Users\Alex\dev\src\issue\go\21801>type main.go
package main

import (
        "os/exec"
        "fmt"
)

func main() {
        out, err := exec.Command(`C:\Users\Alex\dev\src\issue\go\21801\test.cmd`).CombinedOutput()
        fmt.Printf("err=%v\n%s\n", err, out)
}

c:\Users\Alex\dev\src\issue\go\21801>type test.cmd
echo %time:~-11%  >> test.log
ping 127.0.0.1 -n 5
echo %time:~-11%  >> test.log
timeout 5 /nobreak
echo %time:~-11%  >> test.log

c:\Users\Alex\dev\src\issue\go\21801>go build -o a.exe && a.exe
err=<nil>

c:\Users\Alex\dev\src\issue\go\21801>echo 13:03:01.24   1>>test.log

c:\Users\Alex\dev\src\issue\go\21801>ping 127.0.0.1 -n 5

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 5, Received = 5, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

c:\Users\Alex\dev\src\issue\go\21801>echo 13:03:05.29   1>>test.log

c:\Users\Alex\dev\src\issue\go\21801>timeout 5 /nobreak
ERROR: Input redirection is not supported, exiting the process immediately.

c:\Users\Alex\dev\src\issue\go\21801>echo 13:03:05.32   1>>test.log


c:\Users\Alex\dev\src\issue\go\21801>

```
This is not Go problem.

Alex

**Comment by ianlancetaylor** [comment]
Closing based on above comment.  Please comment if you disagree.

**Comment by Chhed13** [comment]
Alex, thank you for shed light on this. 
We bumped with similar cases with .Net command-line utils too - utils can't understand whether it runs in interactive session or not and fail on "readKey" commands.
Sad that it's one more "thing" from Microsoft and it blocks us from wrapping our code with Go. 
@ianlancetaylor yes, it's closed
