### ISSUE TITLE
cmd/go: Windows: "go get ..." doesn't work: "The system cannot find the file specified."

### ISSUE THREAD

**Issue by bxqgit** [golang/go#21803]
### What version of Go are you using (`go version`)?

`go version go1.9 windows/amd64`

### Does this issue reproduce with the latest release?

`Yes`

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go
set GORACE=
set GOROOT=C:\bin\go
set GOTOOLDIR=C:\bin\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

I want to get "x/net/websocket" into my project via:

`go get golang.org/x/net/websocket`

### What did you expect to see?

I expected no errors.

### What did you see instead?

```
go get golang.org/x/net/websocket
# cd C:\Go\src\golang.org\x\net; git submodule update --init --recursive
package golang.org/x/net/websocket: chdir C:\Go\src\golang.org\x\net: The system cannot find the file specified.
```

**Comment by ianlancetaylor** [comment]
Please show us the complete output of  `go get -x golang.org/x/net/websocket`.
