### ISSUE TITLE
math: use Abs rather than if x < 0 { x = -x }

### ISSUE THREAD

**Issue by mundaym** [golang/go#21812]
Now that #13095 is closed we should consider using the `Abs` function where possible in the math library (and possibly elsewhere in the std lib).

For example, this statement in [j0.go](https://github.com/golang/go/blob/87dae58662c78c772cb210d685b354ae6916ef2d/src/math/j0.go#L102) could presumably be replaced:

```go
if x < 0 {
    x = -x
}
```

There are subtle differences between the `if` statement and `Abs` (NaN handling for example) but most of the math functions handle those cases explicitly anyway.

We should also be aware that don't fully optimize `Abs` on all architectures yet, but I think this will come with time. s390x and ppc64x, for example, can do `Abs` in a single instruction whereas the if statement is more difficult to optimize in the general case (because of NaN/-0.0 inputs mainly).

This could be a good issue for a first time contributor, though be aware that you should include before/after benchmarks and for some functions you may need to manually disable assembly implementations to exercise the Go code.

**Comment by Ch3ck** [comment]
I'll work on this one.

**Comment by laboger** [comment]
I have a change ready to be submitted to optimize the Abs and Copysign for ppc64x, because as you mention above, we have a single instruction for those.  Not your if statement however.

**Comment by Ch3ck** [comment]
@laboger I made some changes though using Abs following the suggestions of @mundaym above. You could find the PR here: https://go-review.googlesource.com/c/go/+/63050. I think we could synchronize our efforts to fix this.

**Comment by laboger** [comment]
Here is my CL to make Abs an intrinsic on ppc64x. https://go-review.googlesource.com/c/go/+/67130

**Comment by kishtatik** [comment]
Here is my CL:
https://go-review.googlesource.com/#/c/go/+/85095/
https://go-review.googlesource.com/#/c/go/+/85375/
