### ISSUE TITLE
When I debug step in breakpoint , it step in error gopath

### ISSUE THREAD

**Issue by friends110110** [golang/go#21815]
When I debug golang and make a breakpoint , click *F11* ,it step in ~/gopath/src/.../queryBlock.go , not /Users/friends/Documents/VirtualMachine/share/gopath/src/.../queryBlock.go
 but my gopath is correct in launch.json file        ` "env": { "CORE_LOGGING_LEVEL": "WARNING", "GOPATH": "/Users/friends/Documents/VirtualMachine/share/gopath" },`
 、     `"go.gopath": "/Users/friends/Documents/VirtualMachine/share/gopath",` and go env following:

#### System details

```
go version go1.9 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/friends/Documents/VirtualMachine/share/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cg/mwzlhrjs5y55ny553g6xz9tr0000gn/T/go-build404258059=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.9
uname -v: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
lldb --version: lldb-370.0.42
  Swift-3.1
```

**Comment by mvdan** [comment]
This report is incomplete. What debugger or IDE were you using? Most likely, you should be opening the issue in their issue trackers and not here - Go itself doesn't ship a debugger that I know of.

**Comment by friends110110** [comment]
delve debugger,  visual studio code IDE,

**Comment by davecheney** [comment]
Please open an issue on the delve issue tracker and reference this issue so both parties can keep track of the conversation.

**Comment by friends110110** [comment]
OK, thank you

**Comment by bradfitz** [comment]
I don't see anything concretely actionable here from Go's side, so closing.

We have plenty of bugs open related to debugger specifics, though.

Sounds like this should live in Delve's issue tracker.
