### ISSUE TITLE
math.Remainder returns negative value for two positive inputs

### ISSUE THREAD

**Issue by AmirAlavi** [golang/go#21813]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
Yes repros with latest, also checked on Go playground

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/amiralavi/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r2/zhqmj5x12mbfr_x06b1kltc80000gn/T/go-build863524845=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

https://play.golang.org/p/dEvbbsJ8kX

### What did you expect to see?

I expected to see math.Remainder(334455, 10) return 5 (the same as math.Mod and % operator). For a positive dividend and positive divisor, I expect all three functions to return the same value.

### What did you see instead?
math.Remainder(334455, 10) returns -5

**Comment by randall77** [comment]
This is as expected. The spec of `math.Remainder` says IEEE 754 remainder, and that is how it is specified.  Use `math.Mod` if you want (when both args are positive) the remainder to always be positive.
