### ISSUE TITLE
int(q * (1/q)) == 0  where q is float64

### ISSUE THREAD

**Issue by dtjm** [golang/go#21824]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?

https://play.golang.org/p/AImFqQXfJv

### What did you expect to see?

```
2009/11/10 23:00:00 q            = 0.911765
2009/11/10 23:00:00 1/q          = 1.096774
2009/11/10 23:00:00 q*(1/q)      = 1.000000
2009/11/10 23:00:00 int(q*(1/q)) = 1  // << this line 
```

### What did you see instead?

```
2009/11/10 23:00:00 q            = 0.911765
2009/11/10 23:00:00 1/q          = 1.096774
2009/11/10 23:00:00 q*(1/q)      = 1.000000
2009/11/10 23:00:00 int(q*(1/q)) = 0
```

**Comment by davecheney** [comment]
q*(1/q) == 1 prints false because this number is very close, but not quite
1, therefore converting it to and int truncates it to 0.

**Comment by dtjm** [comment]
@davecheney so you're saying that when it's printed as a float, it is rendered as "1.00000" even though internally it may actually be something like "0.999999999999".  Then when it's converted to int it gets truncated down to 0 ?

**Comment by davecheney** [comment]
Yup!

**Comment by davecheney** [comment]
https://play.golang.org/p/qk3RTsuvuy

**Comment by dtjm** [comment]
@davecheney thanks for the quick response
