### ISSUE TITLE
strconv.Atoi behavior

### ISSUE THREAD

**Issue by rbnsschmtz** [golang/go#21828]
### What version of Go are you using (`go version`)?
go version go1.9 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\r\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
graph package
https://play.golang.org/p/MRpFh6vNNH
the -1 at NewEdge is necessary because the input starts at 1

### What did you expect to see?
normal compiling

### What did you see instead?
graph\graph.go:21:24: multiple-value strconv.Atoi() in single-value context
graph\graph.go:22:24: multiple-value strconv.Atoi() in single-value context

(The two lines below NewEdge)

**Comment by ianlancetaylor** [comment]
Since `strconv.Atoi` returns two values, you can't write `strconv.Atoi(s) - 1`.  You have to assign the result to a variable, as you are doing, and then subtract one from the variable.

Closing because there is no bug here.
