### ISSUE TITLE
"go build -i -a"  Failed to compile

### ISSUE THREAD

**Issue by Antergone** [golang/go#21837]
### What version of Go are you using (`go version`)?
```shell
$  ~  go version
go version go1.9 darwin/amd64
```

### Does this issue reproduce with the latest release?
- 1.9
### What operating system and processor architecture are you using (`go env`)?

```shell
~  go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/data/golang/workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/go-build962802617=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
### What did you do?
I have four test case 

case 1:
```shell 
# args() it's ok~
/usr/local/go/bin/go build -o /private/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/Build_main_go_and_rungo -gcflags "-N -l"  /data/golang/workspace/src/antergone.com/pkgrepo/main.go 
``` 

case 2:
```shell 
# args( -a ) it's ok~
/usr/local/go/bin/go build -o /private/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/Build_main_go_and_rungo -gcflags "-N -l" -a /data/golang/workspace/src/antergone.com/pkgrepo/main.go
```

case 3:
```shell 
# args( -i ) it's ok~
 /usr/local/go/bin/go build -i -o /private/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/Build_main_go_and_rungo -gcflags "-N -l"  /data/golang/workspace/src/antergone.com/pkgrepo/main.go
```

case 4
```shell 
# args( -i  -a)have exception
/usr/local/go/bin/go build -i -o /private/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/Build_main_go_and_rungo -gcflags "-N -l" -a /data/golang/workspace/src/antergone.com/pkgrepo/main.go

go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied

```

### What did you expect to see?
no exception.

### What did you see instead?
if I change the `$GOROOT` owner, the 4th case is ok.
``` shell 
# root:wheel (default) /usr/local/go
sudo chown antergone:admin /usr/local/go
```
or
if I change the `$GOROOT` permissions to `0645`, the 4th case is ok.

**Comment by davecheney** [comment]
-a -i will try to reinstall all the packages in the stdlib causing the
permission error.

What problem caused you to want to use -a -i to solve it? If you can
explain the problem you are facing, perhaps we can suggest a different
solution.

**Comment by Antergone** [comment]
@davecheney 
Gogland will build application use this command (`/usr/local/go/bin/go build -o /private/var/folders/p5/cm2d7jc97p72z4m1jc1dj7j00000gn/T/Build_main_go_and_rungo -gcflags "-N -l" -a /data/golang/workspace/src/antergone.com/pkgrepo/main.go`) before debug.
If I add "-a" to build argument and Gogland is not remove "-a"

The same problem occurs in LiteIDE(https://github.com/visualfc/liteide) force build. But LiteIDE can setting all build args or not just add.

**Comment by Antergone** [comment]
@davecheney 
[Gogland Screenshot](http://picture.antergone.com/blog/ydfkv.jpg)
[LiteIDE Screenshot](http://picture.antergone.com/blog/1ajnc.jpg)

**Comment by davecheney** [comment]
Thank you for that information. The bug you raised is related to -a -i. In the screenshots you have provided -I is not being used.

**Comment by dlsniper** [comment]
Please upgrade to the latest version of Gogland or remove the ` -i ` from it, see: https://youtrack.jetbrains.com/issue/GO-4430 which was fixed in EAP 14.
This can be closed otherwise as it's the expected Go behavior.
