### ISSUE TITLE
runtime: lost non-Go profiling samples are overcounted

### ISSUE THREAD

**Issue by aclements** [golang/go#21836]
cpuProfile.addExtra is called from the Go profiling signal handler to flush any accumulated non-Go profiling samples. If we lost any non-Go profiling samples, it flushes this as a special `_LostExternalCode` sample. However, it *fails* to reset the lost sample count, so every subsequent `addExtra` call will record another `_LostExternalCode` sample.

This fix should be as simple as setting `p.lostExtra` to 0, but this should get back-ported to 1.9.1.

/cc @ianlancetaylor @matloob

**Comment by rsc** [comment]
CL 63270 OK for Go 1.9.2.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 70974](https://golang.org/cl/70974) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:14 UTC
