### ISSUE TITLE
cmd/compile: map literals are never allocated on the stack

### ISSUE THREAD

**Issue by martisch** [golang/go#21830]
go 1.9 and tip
```
package main

func main() {
	m := map[int]int{}
	m[0] = 0
}
```
./main.go:4:18: main map[int]int literal does not escape

However looking at the disassembly reveals that the hmap struct was not allocated on the stack.
Since the hmap pointer passed as argument to makemap is nil.

  main.go:4		0x104f6e4		48890424		MOVQ AX, 0(SP)				
  main.go:4		0x104f6e8		48c744240800000000	MOVQ $0x0, 0x8(SP)			
  main.go:4		0x104f6f1		48c744241000000000	MOVQ $0x0, 0x10(SP)	 <- *hmap		
  main.go:4		0x104f6fa		48c744241800000000	MOVQ $0x0, 0x18(SP)			
  main.go:4		0x104f703		e8d874fbff		CALL runtime.makemap(SB)

This is due to the escape information of the maplit not being copied to the OMAKE node
in maplit in cmd/compile/internal/sinit.go.

Found this while writing tests for a new makemap implementation CL.

Fix incoming.

**Comment by odeke-em** [comment]
@martisch since this is a regression from Go1.8, should we be backporting this to Go1.9.1?

**Comment by randall77** [comment]
@odeke-em , probably not.  I don't think performance regressions should be backported unless they are egregious.

**Comment by odeke-em** [comment]
Ahh I see, thanks @randall77 for this update on some criteria for backporting.

**Comment by martisch** [comment]
I agree with not backporting. The performance regression is not big since non escaping map literals do not come up that often as far as i have seen. It generates work and has potential to break other parts of the distribution. 

It is also not a regression from 1.8. I only tested it with 1.9 and not further back. I updated the original report.

**Comment by odeke-em** [comment]
Roger that @martisch, thanks.

**Comment by davecheney** [comment]
>  It generates work and has potential to break other parts of the
distribution.

Can you please explain what you mean by "breaks other parts of the
distribution". There was no issue associated with this CL so I don't know
what "breaks" means.

Thanks

Dave

**Comment by martisch** [comment]
The issue #21830 that the CL 62790 fixes and was referenced in the CL is explained above. Map literals were always allocated as if they were escaping even so the escape pass marked them as non escaping. This is not a correctness problem or will lead to corruption but there was a performance gain that was missed by not allocating map literals on the stack.

The important part before the "breaks" sentence is: "has potential to". I wanted to say that backporting any change in general from tip to e.g. 1.9 has potential of side effects that may not be present at tip due to other changes interacting with CLs at tip. I am not saying this is the case here but in general there is always a risk. So backporting in Cls in general creates additional testing work and risks introducing CLs themselfs introducing new regressions. Which means there should be enough reason to offset these risks. 

Since this issue is not an issue that could cause programs to behave wrong according to the spec (as far as i know) but more a performance benefit i do not think this performance improvement warrants a backport.

The possibility of having stack allocated map literals after the CL is submitted however might lead to an issue (i dont know of any but there always is a potential) that some compiler part or optimization that has never dealt with stack allocated map literals before in 1.9 interacts badly with the backport. Again i am not saying this is the case here i am just saying why risk a backport if there is no correctness problem in relation to this CL for 1.9 but the backport might risk some bad interactions whatever they might be.

**Comment by davecheney** [comment]
Thank you for your detailed explanation.
