### ISSUE TITLE
Confusion about C++ calling go

### ISSUE THREAD

**Issue by wolfkdy** [golang/go#21845]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.6

### What operating system and processor architecture are you using (`go env`)?
ceontos 7 x86-64

### What did you do?
By using cgo, I wrappered some complex code written by golang into a static-lib and call into the lib
from C++.
My question is: the process will run from a c++ main-entry. Will golang's gc-background thread work in this way? I'm worried that the entry is from C++ code and golang's vm-environment may not be complete so that there will be memory-leaks.

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please use a forum.  See https://golang.org/wiki/Questions.  Thanks.
