### ISSUE TITLE
go install unnecessarily rebuilding '.a' files.

### ISSUE THREAD

**Issue by alankm** [golang/go#21840]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?
```
go install -v
```

Run from the base directory on a large project with a substantial number of vendored dependencies (within the standard 'vendor' directory). 

### What did you expect to see?
As far as I can tell, there is no reason that vendored dependencies should be recompiled each time I build my project. 

### What did you see instead?
The verbose output tells me that every directory and subdirectory within the current project gets rebuilt, including packages within the vendor directory.

### Other thoughts
I notice that the '.a' files from vendored packages do exist within $GOPATH/pkg/(MY_PROJECT)/vendor/..., but for some reason they aren't ever being reused.

**Comment by davecheney** [comment]
Can you please check a few things

1. GOROOT is not set
2. GOPATH is set, or your source is in $HOME/go/src
3. There are no symlinks inside your GOPATH, or inside your vendored source.

**Comment by alankm** [comment]
GOROOT="/usr/local/go"
GOPATH="/home/alan/go"
Source is in: /home/alan/go/src/github.com/sisatech/vcli

Would you like me to unset GOROOT and try again?

Searching for symlinks, I turned up quite a few within my GOPATH. None within my vendored source however, and none between $GOPATH and the project folder. I can provide more specific information if you like, but what I'm seeing looks unhelpful to me.

**Comment by alankm** [comment]
Oh, I should clarify:

I'm not calling "go install -v" on the base directory for my project. My project has multiple binaries, so the layout is:
- ./cmd
- ./pkg
- ./vendor

I'm using a makefile that actually calls, as an example:
```
go install -v $GOPATH/src/github.com/sisatech/vorteil-services/cmd/cli
```

**Comment by davecheney** [comment]
Remove $GOPATH/src and try again. The paths provided to go install are relative to $GOPATH/src

**Comment by alankm** [comment]
Sorry, my mistake: I misinformed you. I wasn't calling it with $GOPATH/src, the first element in the path was "github.com". I ammended my previous comment to reflect this.

**Comment by davecheney** [comment]
Thank you. So the issue as I understand it is

go install -v github.com/sisatech/vorteil-services/cmd/cli

go install -v github.com/sisatech/vorteil-services/cmd/cli


The second time the command is invoked it produces the same amount of
output as the first time. If this is the case can you please run


go install -x github.com/sisatech/vorteil-services/cmd/cli

go install -x github.com/sisatech/vorteil-services/cmd/cli


And copy the full output into a gist and link it to this issue. Thank you.

**Comment by alankm** [comment]
I've just done some more testing and that doesn't seem to be quite the case.

Calling the following command twice in a row works exactly as expected:
```
go install -v github.com/sisatech/vorteil-services/cmd/cli
```
ie. Nothing recompiled the second time around.

There are a number of separate binaries to be built within the project, and my makefile tries to build all of them sequentially. If I run each of those commands myself separately they still all work as expected.

Somehow something I'm doing in the makefile seems to be triggering the problem. I'm not quite sure how, and I'm surprised that it matters considering that I'm definitely *not* modifying any of the files within the vendor directory.

I will investigate further and see if I can identify the cause, or provide a minimal example to reproduce the issue.

**Comment by alankm** [comment]
I believe I may have found the problem: one of the programs we were compiling needed CGO_ENABLED=0, the rest did not. It makes sense to me that this would cause problems.

If you're willing, I'd love an explanation of what you think is happening. Are the .a files all being discarded and remade whenever these environment variables change? Or, are the CGO_ENABLED=0 .a files being produced into a temporary folder somewhere, and cleaned up afterwards?

Is there a way to use the -pkgdir flag to avoid this issue, and have both sets of .a files available?

**Comment by davecheney** [comment]
CGO_ENABLED requires the entire runtime to be rebuilt, you can use
-install_suffix (not sure of the exact flag) to avoid overwriting the
runtime and avoiding the rebuilds.

**Comment by alankm** [comment]
That works brilliantly. Thank you for your help.
