### ISSUE TITLE
Go 1.10 Some way to prevent webservers from crashing due to rogue goroutines panicing

### ISSUE THREAD

**Issue by pjebs** [golang/go#21843]
See: https://github.com/urfave/negroni/issues/190

**Comment by kevinburke** [comment]
In the example cited,

```go
func Handler(w http.ResponseWriter, r *http.Request) {
   go func( ) {
      panic("ZZZ") //Negroni does not protect us. Application crashes.
   }()
}
```

I'd expect the caller to handle panic-able code with a recover, eg.

```go
func Handler(w http.ResponseWriter, r *http.Request) {
   go func( ) {
      defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered in f", r)
        }
      }()
      panic("ZZZ") //Negroni does not protect us. Application crashes.
   }()
}

**Comment by pjebs** [comment]
That works for my contrived example but not if we are using third party libraries etc that we have no control over.
Technically we can do that every time we call a method from a third party library but that will destroy the flow of the Go code.

**Comment by mvdan** [comment]
This seems unrelated to web servers, and more about goroutines and panics one doesn't control.

**Comment by pjebs** [comment]
@mvdan Precisely. I just used web servers as an example because my original complaint was in the Negroni library github.

**Comment by ianlancetaylor** [comment]
There are a lot of complexities here and I don't think this issue, which starts with a reference to an issue in a separate project, is the most productive way to address the general problem.  This should be addressed through the proposal process, or if you don't have a proposal it should be a discussion on golang-nuts (note that this general issue has been discussed on golang-nuts before).

That is, this is not an area where it helps to simply say "there is a problem."  We need to think about ways to fix the problem, and I don't think an unfocused discussion on the issue tracker will be an effective way to do that.

So, closing.

**Comment by pjebs** [comment]
For future reference:
https://groups.google.com/forum/#!topic/golang-nuts/3QRnU0xJVXg
https://groups.google.com/forum/#!topic/golang-nuts/AsGVVbeyEzs
https://groups.google.com/forum/#!topic/golang-nuts/Bi43JRE-c6w
http://grokbase.com/t/gg/golang-nuts/12apwxbj83/go-nuts-how-to-protect-against-panics-in-goroutine-started-in-http-handlefunc
http://grokbase.com/t/gg/golang-nuts/157yq74bkq/go-nuts-why-i-cant-to-catch-all-panics
