### ISSUE TITLE
x/build: builders and github push not working for new CLs

### ISSUE THREAD

**Issue by martisch** [golang/go#21849]
http://build.golang.org does not show builder runs for the last few CLs that were submitted (~24 hours)
and the github repo does not seem to have catched up on the last few commits that were submitted.

**Comment by kevinburke** [comment]
Last time this happened there was a stack trace in the maintner logs (which I think is powering a lot of the data sources here) but I don't have access to the production logs for that service. @adams-sarah ?

**Comment by adams-sarah** [comment]
+andy

Probably pubsubhelper:

2017/09/12 18:26:17 Client error: read error: EOF
2017/09/12 18:26:18 Client: "AUTH LOGIN\r\n", verhb: "AUTH"
2017/09/12 18:26:18 Client error: read error: EOF
2017/09/12 18:26:19 Client: "AUTH LOGIN\r\n", verhb: "AUTH"
2017/09/12 18:26:19 Client error: read error: EOF
2017/09/12 18:26:19 Client: "AUTH LOGIN\r\n", verhb: "AUTH"
2017/09/12 18:26:19 Client error: read error: EOF
2017/09/12 18:26:20 Client: "AUTH LOGIN\r\n", verhb: "AUTH"
2017/09/12 18:26:20 Client error: read error: EOF
2017/09/12 18:28:15 Client: "AUTH LOGIN\r\n", verhb: "AUTH"

**Comment by andybons** [comment]
Hm. https://pubsubhelper.golang.org/recent is indicating that new GitHub events are being processed, but not new Gerrit events...

**Comment by bradfitz** [comment]
Is the "AUTH LOGIN" coming from Google's MTA or just random spammers from the Internet finding a port 25 open? If the latter, it's a red herring.

But if Google has changed its delivery to now attempt AUTH, that's weird.

FWIW, our SMTP greeting is:

```
$ telnet pubsubhelper.golang.org 25
Trying 35.184.237.80...
Connected to pubsubhelper.golang.org.
Escape character is '^]'.
220  ESMTP gosmtpd
^]q
```

Maybe it needs to say something more or less to make clients not try to authenticate?

Or maybe we should just reply to any AUTH request with a success message.

But first I'd like to see if that's actually Google authenticating.

**Comment by adams-sarah** [comment]
subrepo commits are appearing in datastore cache, but not go main repo commits since 2d69e9e259ec0f5d5fbeb3498fbd9fed135fe869 yesterday

![datastore](https://user-images.githubusercontent.com/2741356/30345919-e582ac2c-97bb-11e7-842a-c8b6d40ceedd.png)

**Comment by andybons** [comment]
Found the issue. The bot that is set to receive the emails had all of its watches deleted from its Gerrit account. Re-added a watch on `All-Projects` and will follow up with the Gerrit team. Let’s see if this fixes the underlying problem.

**Comment by adams-sarah** [comment]
:tada: :tada: thanks andy

**Comment by bradfitz** [comment]
Pubsubhelper can't be the only problem. It's only a wake-up for maintner. Maintner polls Gerrit regularly as a fallback without any pubsubhelper. 

So what's the deeper problem?

**Comment by adams-sarah** [comment]
maintner is seeing the new commits over and over...
eg.

2017/09/12 18:21:19 mutation: gerrit:<project:"go.googlesource.com/go" commits:<sha1:"b86fae041baff7a7077c67060bc4282d78a2118b" raw:"tree 422b34aa8cbf67be5c17ff045cbbdb5bd5c12340\nparent 80b2ae5878c7b08b605128cc885305bf86bc5475\nauthor tbunyk <tbunyk@gmail.com> 1504627276 +0300\ncommitter Ian Lance Taylor <iant@golang.org> 1505239944 +0000\n\nencoding/json: update documentation for MarshalIndent\n\nMake arguments semantics clear without the need to look for\njson.Indent documentation.\n\nChange-Id: If9adfe9f477a30d426ae83790b0f2578c0a809b7\nReviewed-on: https://go-review.googlesource.com/61670\nRun-TryBot: Ian Lance Taylor <iant@golang.org>\nTryBot-Result: Gobot Gobot <gobot@golang.org>\nReviewed-by: Ian Lance Taylor <iant@golang.org>\n" diff_tree:<file:<file:"src/encoding/json/encode.go" added:2 > file:<file:"src/encoding/json/example_test.go" added:19 > > > > 
2017/09/12 18:21:19 wrote record; using existing flush timer.

could it be that something is off with `processGerritMutation()` (maintner/gerrit.go:483)?

have to run to a mtg but will keep looking at this after.

**Comment by adams-sarah** [comment]
ok they're back up.
i still have no idea what happened. but this seemed related to https://github.com/golang/go/issues/21555 so tried restarting gitmirror b/c i have to leave work now.
that worked...

... will look at this more tomorrow.

**Comment by adams-sarah** [comment]
Copy-pasting my update from #21555 :
[The root cause of this issue is that] the builders are set up such that if a commit is pushed to the dashboard, and the dashboard does not recognize the new commit's parent commit SHA, it will reject the new commit. This puts us in a place where, if we lose one commit, we can never recover (until we restart gitmirror).
