### ISSUE TITLE
cmd/compile: expand TestIntendedInlining to more packages and funcs

### ISSUE THREAD

**Issue by mvdan** [golang/go#21851]
#17566 is about improving the inlining cost model. Making changes to the compiler, especially touching the inlining heuristics, always has the risk of unintentionally making some funcs non-inlineable, potentially resulting in noticeable performance regressions.

That's why @josharian added `TestIntendedInlining`: https://go-review.googlesource.com/c/go/+/57410

It basically runs `go build -a -gcflags=-m runtime` and checks that certain funcs are printed in a line along with `can inline`.

However, the test is limited to the runtime. There are other small functions in the standard library that we want to be inlineable, and which we even tweak to appease the current heuristic. A recent example: https://go-review.googlesource.com/c/go/+/63332

I propose that we add a way to cover more funcs in other packages within `std`.

Thoughts:

* We probably want to focus on low-level and basic packages first, like `unicode/utf8` and `bytes`
* Should we modify `TestIntendedInlining`, or add a new test? (given how it uses `build -a`, I presume a single test would be the fastest)
* If it covers more than just `runtime`, I presume we would want the test out of the `runtime` package (where? cmd/compile?)

Suggestions of funcs/packages to add welcome. Happy to work on it if pointers on the above are given.

CC @TocarIP @josharian @martisch

**Comment by randall77** [comment]
You can modify that test and move it to cmd/compile if you want.
My only worry is that "build -a std" would be slow. Try to restrict to just the packages that want a test.

**Comment by mvdan** [comment]
Yes - this is partly why I mentioned focusing on certain packages first, e.g. the ones closest to `runtime` and with small dependency trees.

**Comment by TocarIP** [comment]
We can start with individual packages and switch to "build -a std"  once enough packages are covered

**Comment by mvdan** [comment]
@TocarIP I would assume that even after adding all the funcs we want, we still wouldn't need all of `std`. In any case, we can always look at that once the package list has grown large and we can measure the difference in test run time.

**Comment by stemar94** [comment]
In https://golang.org/cl/42813 we made a change to have a method of bytes.Buffer to be inlined. We also added a test for that. Would this also be a candidate here. And therefore remove the test in bytes package?

**Comment by mvdan** [comment]
Yes, that would be good. There is no need to duplicate the logic to determine whether or not a func is inlineable (and all the extras, such as reporting why it isn't so).

Then again, technically the tests are checking for different things. TestIntendedInlining checks if a func is inlineable, which is a decision made at compile-time. Your bytes test checks the binary to see if the symbol exists, so it checks if the func was inlined. Are all funcs that are inlineable always inlined? I honestly don't know the answer to that question.

If the answer is yes, then it's safe to merge with this test.

**Comment by mvdan** [comment]
I also grepped the Go repository, and did not find any other occurences of `go tool nm` to check if funcs are inlined.

**Comment by stemar94** [comment]
> I also grepped the Go repository, and did not find any other occurences of go tool nm to check if funcs are inlined.

I know of at least
https://golang.org/src/net/http/http_test.go#L80

**Comment by mvdan** [comment]
Well, I did see that one, but that checks for linker behavior - and it checks whether or not some funcs were linked into a binary, I assume because they should never be part of the binary in the first place (not even inlined).

**Comment by randall77** [comment]
Inlineable functions might still appear in the binary if a closure is made out of them.

**Comment by mvdan** [comment]
Thanks, @randall77. I'll assume it is fine to move the check then. CL incoming.

**Comment by mvdan** [comment]
I have run out of ideas to add to the table, so I'm going to close this issue for now. Of course, feel free to still add more to it - but an umbrella issue to expand the table is no longer useful.

I believe it was @aclements who suggested that we could use benchmarks to identify what runtime functions should always be inlineable, as opposed to human guesses. That could be a way forward if someone wants to look into it.
