### ISSUE TITLE
Playground's format button doesn't recognize type aliases

### ISSUE THREAD

**Issue by natefinch** [golang/go#21864]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9 (play.golang.org)

### Does this issue reproduce with the latest release?
yes

### What did you do?

https://play.golang.org/p/Mp9InSnQqa

Hit run and hit format

### What did you expect to see?

format should work

### What did you see instead?

Note that this runs just fine, but the format button returns an error about the type alias.

**Comment by cespare** [comment]
Duplicate of #21645.
