### ISSUE TITLE
strings.Trim does not return slice

### ISSUE THREAD

**Issue by komuW** [golang/go#21861]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
Read the documentation of strings.Trim; https://golang.org/pkg/strings/#Trim

### What did you expect to see?
The docs to say something like; 
`Trim returns a copy of the string s with all leading and trailing Unicode code points contained in cutset removed.`

### What did you see instead?
`Trim returns a **slice** of the string s with all leading and trailing Unicode code points contained in cutset removed.`

nb; emphasis is mine.

**Comment by gbbr** [comment]
I think this could potentially be a misunderstanding in terminology. In this case I would assume that "_slice_" is a synonym for "_part_". But I can see how this could be misleading.

**Comment by komuW** [comment]
@gbbr yeah, the docs could be meaning a `slice` in the english sense of the word. 
But even if they were, they shouldn't since `slice` already has a specific meaning in go

**Comment by gbbr** [comment]
AFAIK strings are also slices. In my opinion the description is correct.

**Comment by komuW** [comment]
@gbbr I see what you mean.
