### ISSUE TITLE
x/build/cmd/pubsubhelper: robot account should be subscribed in config, not manually

### ISSUE THREAD

**Issue by andybons** [golang/go#21869]
Gerrit removes watches from inactive accounts. The pubsubhelper bot is considered inactive so should have its watches changed from being profile-level to config-level:

an example entry:
```
[notify "pubsubbot"]
        email = gopherbot@blah.com
        type = all_comments
        type = submitted_changes
        type = ...
```

/cc @adams-sarah @bradfitz

**Comment by bradfitz** [comment]
Good to know! Thanks.

**Comment by andybons** [comment]
Pushed config change to `AllProjects`. We shouldn't have to log in to the bot account again. :tada:
