### ISSUE TITLE
all: avoid using exec.Command("go", ...) ?

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#21875]
In general, there are no guarantee that `go` command from $PATH has the same version as the one used in compile time or it exists.
We should get `go` command from $GOROOT/bin instead.
For test code, we could use `testenv.GoTool()`.
For other code, we could write similar code.
```
$ ag 'exec.Command\("go"' | wc -l
      57
```

**Comment by bcmills** [comment]
This probably also implies that we should avoid invoking the `go` command unqualified in the (few) remaining `test.bash` tests.

**Comment by Quasilyte** [comment]
Maybe [benchmarks/build](https://godoc.org/golang.org/x/benchmarks/build) is a good change candidate too. It is inconvenient (and not robust when there are other PATH dependencies) to execute a program with modified PATH just to compare 2 `go` binaries performance.

...and `benchmarks/build` has external dependencies in PATH.
[build.go:26](https://github.com/golang/benchmarks/blob/master/build/build.go#L26) calls [RunUnderProfiler](https://github.com/golang/benchmarks/blob/master/driver/driver_linux.go#L28) that will execute `perf` program.

**Comment by hirochachacha** [comment]
Thank you for your notes.
I'd like to start making a CL for the core repository. I'll handle bash scripts also.
I'm not sure about sub repos. If someone wants to do, that's nice.

**Comment by ianlancetaylor** [comment]
I'm not sure there is anything left to do here.  Most, perhaps all, of the bash scripts have been converted to Go code.  Any remaining cases can be handled as separate issues.
