### ISSUE TITLE
Is there any way to sort the http.Header by myself?

### ISSUE THREAD

**Issue by dcb9** [golang/go#21886]
Hi, Guys

I wanted to create a new sorter for http.Header, how can I do that without forking the whole http package?

Thank you so much!

**Comment by dsnet** [comment]
Hello, we try to keep the issue tracker only about actual issues with Go and items to work on. https://github.com/golang/go/wiki/Questions provides several ways to ask questions to the community.

That being said, http.Header is just a `map[string][]string`. You can manually flatten the map into `[][]string` and use `sort.Slice` to get what you want.
