### ISSUE TITLE
sort.SearchInts return incorrect on value not found

### ISSUE THREAD

**Issue by Zex** [golang/go#21885]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
Haven't upgraded it yet, this can be reproduce on play.golang.org

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zex/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build828632110=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
Try this out https://play.golang.org/p/oPnHXjlwgX

### What did you expect to see?

len: 8, x: 1, SearchInts return: 0
len: 8, x: 3, SearchInts return: 2
len: 8, x: 12, SearchInts return: 7
len: 8, x: 5, SearchInts return: 4
len: 8, x: 9, SearchInts return: 8
len: 8, x: 10, SearchInts return: 8

### What did you see instead?
len: 8, x: 1, SearchInts return: 0
len: 8, x: 3, SearchInts return: 2
len: 8, x: 12, SearchInts return: 7
len: 8, x: 5, SearchInts return: 4
len: 8, x: 9, SearchInts return: 7
len: 8, x: 10, SearchInts return: 7

**Comment by martisch** [comment]
The documentation says "The return value is the index to insert x if x is not present".
Inserting 9 and 10 at position 7 (0 index is start) sounds right to me.
