### ISSUE TITLE
Go tour Exercise: Maps bug

### ISSUE THREAD

**Issue by rahwang** [golang/go#21889]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

This is a bug in the Go Tour on the website, so latest version I assume.

### What operating system and processor architecture are you using (`go env`)?

Windows

### What did you do?

This word count code is "incorrect" according to the test suite which expects a value of 1 for all words.

func WordCount(s string) map[string]int {
	words := strings.Fields(s);
	
	fmt.Printf("%T, %d\n", words, len(words))
	fmt.Println(words)
	
	var result = make(map[string]int)
	for _, v := range words {
		result[v] = len(v)
	}
	return result
}

### What did you expect to see?

A test pass

### What did you see instead?

A test fail

**Comment by bontibon** [comment]
There's a bug in your code; replace `result[v] = len(v)` with `result[v]++`.

**Comment by ianlancetaylor** [comment]
I don't see problem here.

**Comment by rahwang** [comment]
Ah, I misunderstood. The tour asks for count of word instances, not count of characters per word
