### ISSUE TITLE
x/tools/present: Typo in doc.go

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#21891]
### What did you do?

See https://godoc.org/golang.org/x/tools/present. The line
"at the beginning of a line or else be preceded by a space or punctuation; similarly a closing marker must be at the end of the lineo"
appears just before the code box showing marker examples. It appears to be a duplicate of a line in the middle of the previous paragraph.

### What did you expect to see?
Nothing

### What did you see instead?
A duplicate line without a proper full stop.

**Comment by johanbrandhorst** [comment]
I will fix this.

**Comment by robpike** [comment]
Fixed
