### ISSUE TITLE
the progrom crash unexpectly

### ISSUE THREAD

**Issue by beyondzzk** [golang/go#21898]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 linux/386

### Does this issue reproduce with the latest release?
no reproduce in go 1.7.3 linux/386

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/gowork:/root/italk_go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build129125825=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
package main

import (
        "fmt"
        "sync/atomic"
)

type simple_service_manager struct {
        round_index        uint16
        peer_idx_base     uint64
}

func (sm *simple_service_manager) get_service_idx(offset uint16) uint64 {
        return atomic.AddUint64(&sm.peer_idx_base, uint64(1<<16)) + uint64(offset)
}

func main() {
        sm := &simple_service_manager{}
        var port int = 9900
        fmt.Println(sm.get_service_idx(uint16(port)))
}

if put peer_idx_base to the first member of simple_service_manager,  it can run normally

### What did you expect to see?
Program run and exist normally

### What did you see instead?
The program is crash

**Comment by randall77** [comment]
Read the last paragraph on this page: https://golang.org/pkg/sync/atomic/

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
