### ISSUE TITLE
crypto/tls Config.VerifyPeerCertificate

### ISSUE THREAD

**Issue by trueblacker** [golang/go#21900]
I have a question about VerifyPeerCertificate func in tls.Config, which can be used for custom server certificate validation. As far as I can see, there is a lack of context to do so, because there is no way for this function to find out the DNS name of the host to verifiy it by certificate chain. During "standard" implementation this is done by using c.config.ServerName field as value for x509.VerifyOptions.DNSName, but there is now way to do the same in the custom VerifyPeerCertificate function. Of course, this function can be used as additional verification step, but as far as I understand, it should be possible to use it as the only verification one (by specifying InsecureSkipVerify: true).

It seems to me that there must be an additional parameter in this function.

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux amd64

**Comment by FiloSottile** [comment]
What you would usually do here is define a closure that accesses context from the scope where you are defining the Config.

That is, you would define an anonymous function inline where you create the Config, and use variables that are available there.

**Comment by FiloSottile** [comment]
If you have more questions, please see https://golang.org/wiki/Questions

**Comment by trueblacker** [comment]
Thank you for reply and for link.

But client config can't always know what server will be used, consider http.Transport f.e. You can specify tls.Config for it without knowing, what servers will be used in http transactions later.

**Comment by titanous** [comment]
It's not possible to change the function signature due to the [compatibility promise](https://golang.org/doc/go1compat).

For a client, you'd want to provide a function in the `DialTLS` field of the `http.Transport` struct.

**Comment by maurice2k** [comment]
It's actually sad such a PR was accepted in the first place @`VerifyPeerCertificate`. But I understand the compatibility promise.

The following snippet is a sample implementation of `DialTLS` which then uses a closure for `VerifyPeerCertificate` as you suggested. @titanous 

It could have been easier if Transport would break up its `dialConn` method into smaller chunks that are publicly callable so that you don't find yourself re-implementing most of the code.
It gets even worse if you need proxies (this code is also in `dialConn`)

```golang
func verifyPeerCerts(serverName string, rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
	// some dummy code to check all certs available (not very useful and indeed a security issue if
	// InsecureSkipVerify is set to true and the server supplies arbitrary certs)
	for i := 0; i < len(rawCerts); i++ {
		cert, err := x509.ParseCertificate(rawCerts[i])

		if err != nil {
			fmt.Println("Error: ", err)
			continue
		}

		hash := sha1.Sum(rawCerts[i])
		fmt.Printf("Fingerprint: %x\n\n", hash)

		fmt.Println(hash, cert.DNSNames, cert.Subject, cert.VerifyHostname(serverName))
	}
	return nil
}

func tlsHost(targetAddr string) string {
	if strings.LastIndex(targetAddr, ":") > strings.LastIndex(targetAddr, "]") {
		targetAddr = targetAddr[:strings.LastIndex(targetAddr, ":")]
	}
	return targetAddr
}

func main() {
	link := "https://172.30.12.120:443/"

	tr := &http.Transport{
		DialTLS: func(network, addr string) (net.Conn, error) {
			dialer := &net.Dialer{
				Timeout:   30 * time.Second,
				KeepAlive: 30 * time.Second,
				DualStack: true,
			}

			conn, err := tls.DialWithDialer(dialer, network, addr, &tls.Config{
				InsecureSkipVerify: true,
				ServerName: addr,
				VerifyPeerCertificate: func(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
					return verifyPeerCerts(tlsHost(addr), rawCerts, verifiedChains)
				},
			})
			if err != nil {
				return conn, err
			}
			return conn, nil
		},

	}
	client := &http.Client{Transport: tr}
	response, err := client.Get(link)

	if err != nil {
		panic(err)
	}

	defer response.Body.Close()
}
```
