### ISSUE TITLE
proposal: net/http2: support proxy/socks for Client

### ISSUE THREAD

**Issue by packman80** [golang/go#21907]
Go has great http2 client, but it doesn't work through proxy/socks at all. Please, add it in further versions.

**Comment by ianlancetaylor** [comment]
CC @tombergan

**Comment by odeke-em** [comment]
Thank you for the request @packman80.
I am not too sure about this, but it seems like SOCKS5 support for clients was added in https://go-review.googlesource.com/c/go/+/35488 for Go1.9,
and then in the net repository there is https://godoc.org/golang.org/x/net/proxy#SOCKS5 from which I believe you can make a custom dialer to add to your transport.

For starters, could you please provide a code snippet reproducing what wasn't working? Also your Go version?

**Comment by packman80** [comment]
It's about http2 client (net/http2). net/http has support proxy/socks in transport.go, but net/http2 doesn't support it. I edited title.

**Comment by tombergan** [comment]
Can you explain why you need to use SOCKS with x/net/http2 instead of net/http? SOCKS is not part of HTTP/2 so I would lean towards not adding support there unless there is a good motivating use case.

Also, can you clarify whether you are talking about SOCKS or CONNECT?

**Comment by rsc** [comment]
Ping @packman80, can you reply to @tombergan's questions above? Thanks.

**Comment by rsc** [comment]
We believe that when you use HTTP2 via net/http, which is the suggested way, then the $HTTP_PROXY environment variable is respected and socks works fine as a way to create new connections to specific hosts (and then net/http runs HTTP2 over those as possible). 

Given lack of response above, closing.
