### ISSUE TITLE
encoding/json: Unexpected marshal behavior

### ISSUE THREAD

**Issue by alexandrevicenzi** [golang/go#21903]
I created a custom MarshalJSON for my struct and it outputs the wrong struct if I have customs MarshalJSON nested in my struct.

I'm trying to understand why it doesn't work as expected. I know that there are some limitations with type redefinition but it works well if I don't nest any struct with a custom MarshalJSON.

### What version of Go are you using (`go version`)?

1.8

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux

### What did you do?

[https://play.golang.org/p/Mp1ot20ILA](https://play.golang.org/p/Mp1ot20ILA)

This example is just to be able to reproduce the problem. I know it doesn't make any sense the custom Copy type, but in a real problem, I would extend Copy type by adding custom fields.

### What did you expect to see?

{"value":"A"}
{"value":"B","A":{"value":"A"}}
{"value":"C","A":{"value":"A"},"B":{"value":"B","A":{"value":"A"}}}

or at least

{"value":"A"}
{"value":"B"}
{"value":"C"}

### What did you see instead?

{"value":"A"}
{"value":"A"}
{"value":"C","A":{"value":"A"},"B":{"value":"A"}}

The first line is ok.
The second line is completely wrong.
The third line is almost ok.

C has two nested objects with a custom marshal and it works almost good.
B has just one and it prints the output of A.

**Comment by ianlancetaylor** [comment]
Note that we don't use the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions .

**Comment by alexandrevicenzi** [comment]
In my opinion, it's a bug since it works for some cases.

**Comment by dsnet** [comment]
I should note that Go 1.0 had the user's expected behavior:
```go
{"value":"A"}
{"value":"B"}
{"value":"C"}
```

The current output has been the case since Go1.1.

**Comment by go101** [comment]
Maybe Go 1.0 is buggy. I feel the results of the later version are right.

```golang
func (this *B) MarshalJSON() ([]byte, error) {
	type Copy B
	c := (*Copy)(this)
	return json.Marshal(c)
}
```

The type `Copy` declared in `(*B).MarshalJSON` has one method,
this method comes from `(*A).MarshalJSON`.
That is why the `json.Marshal(c)` in `(*B).MarshalJSON` will return a nil byte slice.

**Comment by AlexRouSg** [comment]
https://play.golang.org/p/3p1d50YSnd

If you did type conversion instead, the results are as the OP expected.
```
func (this *B) MarshalJSON() ([]byte, error) {
	type Copy B
	c := Copy(*this)
	return json.Marshal(c)
}
```

**Comment by AlexRouSg** [comment]
https://play.golang.org/p/ia8fM1zH9P

If you dereference the pointer before type conversion, the results are as the OP expected.

```
func (this A) MarshalJSON() ([]byte, error) {
	type Copy A
	c := (Copy)(this)
	return json.Marshal(c)
}

func (this B) MarshalJSON() ([]byte, error) {
	type Copy B
	c := (Copy)(this)
	return json.Marshal(c)
}

func (this *C) MarshalJSON() ([]byte, error) {
	type Copy C
	c := (Copy)(*this)
	return json.Marshal(c)
}
```

**Comment by ianlancetaylor** [comment]
Doesn't seem to be anything to do here.
