### ISSUE TITLE
goimports doesn't import packages that have the same name as a local function

### ISSUE THREAD

**Issue by zakkor** [golang/go#21919]
### What version of Go are you using (`go version`)?
`go version go1.9 linux/amd64`

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 16.04 amd64

### What did you do?

If you have a function with the same name as a package, goimports won't add that import

```
package main

func exec() {
}

func os() {
}

func main() {
	if len(os.Args) != 2 {
	}
	cmd := exec.Command("a")
}
```

### What did you expect to see?
the "os" and "os/exec" packages added as imports

### What did you see instead?
the "os" and "os/exec" packages not added as imports

**Comment by zakkor** [comment]
nvm this is a compile error, my bad

**Comment by griesemer** [comment]
Indeed. You cannot have an imported package have the same name as a package-level entity (function, variable, type, constant).
