### ISSUE TITLE
cmd/go: Windows 10 causes "GOPATH entry is relative" error due to extraneous semicolon

### ISSUE THREAD

**Issue by oliverjanik** [golang/go#21928]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes, freshly downloaded windows installer

### What operating system and processor architecture are you using (`go env`)?
Windows 10 64 bit

### What did you do?
```
C:\Users\Oliver>go env
go: GOPATH entry is relative; must be absolute path: "".
For more details see: 'go help gopath'

C:\Users\Oliver>echo %GOPATH%
C:\gopath;D:\work;D:\temp;
```

### What did you expect to see?
normal go env output

### What did you see instead?
an error

The issue seems to be the trailing semicolon. However that is what the env variable dialog in win 10 produces and I think go should deal with it.

![image](https://user-images.githubusercontent.com/2280140/30571933-26d0a78e-9d2e-11e7-9bdd-db1c011b566c.png)

**Comment by davecheney** [comment]
Are you sure there aren't 5 entries in the dialog box on the right hand
side?

**Comment by oliverjanik** [comment]
Yes I'm sure. Should be easy to replicate for anyone with Win 10.

**Comment by davecheney** [comment]
Thanks for confirming. It's pretty bad that windows terminates a list with
an empty atom. On unix terminating a PATH list with a : is very bad as it
is sometimes interpreted as ".", ie PATH=/bin:/usr/bin: (not trailing
colon) is the same as PATH=/bin:/usr/bin:.

**Comment by as** [comment]
It's application specific, Windows does not enforce or follow a standard. Here's part of my `%Path%` on windows right now:

```C:\Users\as\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Docker Toolbox```

**Comment by davecheney** [comment]
cc @cznic @alexbrainman I know we've had the discussion before about `filepath.SplitList` and `filepath.JoinList` and I know part of that discussion dealt with empty path elements.

**Comment by alexbrainman** [comment]
I can reproduce the issue on my Windows 10. And I agree that we should fix it.

> On unix terminating a PATH list with a : is very bad as it
> is sometimes interpreted as "."

Windows always check your current directory first even before looking at the PATH.

But we are talking about GOPATH here. I think we should ignore blank elements of GOPATH. We should ignore elements consisting of spaces only. What do you think?

Alex

**Comment by davecheney** [comment]
@alexbrainman yes, you're right. I think

- we should ignore empty path elements "" , ie `%GOPATH%=C:\go;`
- we should _not_ ignore blank path elements, `" "`, ie, `%GOPATH= ;D:\Go`

**Comment by alexbrainman** [comment]
@davecheney I do not see how path elements like " " are different from "". What do you propose to do with path elements like " "?

Alex

**Comment by davecheney** [comment]
" " is a mistake. For the record I consider "" as mistake, but the chances of windows 10 fixing their buggy tool are close to zero, so I guess we have to live with it.

**Comment by mattn** [comment]
I think the both should be ignored as below works. path-list is candidates for the PATHs.

```
C:\>set PATH=; ;%PATH%

C:\>some-command.exe
```

**Comment by davecheney** [comment]
Mattn, as Alex pointed out, we are no discussing PATH, but GOPATH. The rules for searching for a binary do not apply.

**Comment by alexbrainman** [comment]
> " " is a mistake.

SGTM. Thanks for explaining.

Alex

**Comment by AndrewWPhillips** [comment]
Workaround: In Windows 10 control panel "Edit environment variable" dialog select the "Edit text..." button and delete the trailing semicolon. (Took me a while to work out how to do this so I thought others might like to know.)

**Comment by rhelenagh** [comment]
Thanks!
