### ISSUE TITLE
golan

### ISSUE THREAD

**Issue by swissknife007** [golang/go#21927]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)? 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build279210773=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do? 

package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
	hello := make(chan int)
	
        go func() {
 		hello <- 1
	}()	

        go f(){
        	//hello <- 2
        }() 
	hello_value := <- hello
	fmt.Println(hello_value)
}

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
The code  should have compiled.

### What did you see instead?
Compilation error.

**Comment by swissknife007** [comment]
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
	hello := make(chan int)
	
        go func() {
 		hello <- 1
	}()	

        go f(){
        	//hello <- 2
        }() 
	hello_value := <- hello
	fmt.Println(hello_value)
}

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by swissknife007** [comment]
Hi Dave,

Not sure why this issue has been closed? It is a compilation error when it
is not supposed to be. Why did you assume this was a question?

**Comment by cespare** [comment]
It should be `go func() {`, not `go f(){`. The error message indicates the site of the problem.
