### ISSUE TITLE
cmd/go: add flag to show only test names, not other -test.v output

### ISSUE THREAD

**Issue by natefinch** [golang/go#21926]
I want to be able to show individual tests being run without printing out t.Log messages unless a test fails.  There's currently no way to do that AFAICT.

I use t.Log a lot to write debugging info to make it easier to figure out why tests fail, including dumping server log messages into t.Log.  Printing this out for passing tests makes the output far too noisy.  However, I really value being able to see the list of all individual tests that are run and their execution times.  This can make it easier to look back at old test runs and see if a test has gotten slower over time, etc. 

Adding a new flag that'll work like -v for the purposes of showing what tests are run would be super awesome IMO.

**Comment by davecheney** [comment]
Can you pipe the output through grep to filter out the lines you're not interested in?

**Comment by robpike** [comment]
I'm not completely opposed but it does sound a lot like featuritis to me. Grep is your friend. Let other tools do some of the lifting.

**Comment by natefinch** [comment]
I'd be happy to grep if there's some way to distinguish between log
messages written during a failing test and those written during a passing
test.  I just don't think there's any way to do that.  I'd be happy to be
proven wrong.

**Comment by davecheney** [comment]
How about this"
```
zapf(~/src/tt) % go test -v
=== RUN   TestSucceeding
--- PASS: TestSucceeding (0.00s)
=== RUN   TestFailing
--- FAIL: TestFailing (0.00s)
	test_test.go:10: whoops, about to fail
	test_test.go:11: ker-bham!
FAIL
exit status 1
FAIL	tt	0.006s
zapf(~/src/tt) % go test -v 2>&1 | grep "^=== RUN"
=== RUN   TestSucceeding
=== RUN   TestFailing
```

**Comment by davecheney** [comment]
Or this
```
% go test -list Test
TestSucceeding
TestFailing
ok  	tt	0.005s
```

**Comment by natefinch** [comment]
The former requires me to run my tests twice and still forces me to wade through masses of logs to find log output for the failing tests.  The second mostly works (if I then run go test without -v), it at least gives me the list of tests that'll run, but doesn't give me execution times of individual tests.

I just wish the two features were separated - the "always show logging" and "show individual tests being run".

**Comment by rsc** [comment]
Once we do machine-readable test output you can split this as many different ways as you want. Let's plan for that instead of adding more control knobs here.
