### ISSUE TITLE
log: race between SetFlag and Output

### ISSUE THREAD

**Issue by dsnet** [golang/go#21935]
[CL/38056](https://golang.org/cl/38056) introduced a regression where `l.flag` was accessed outside of the protection of `l.mu`, which can cause a race with `SetFlag`:
https://github.com/golang/go/blob/4cf19fb5a73a33f838efe21b3baa14167469ac83/src/log/log.go#L152-L154

A fix for this has been sent in [CL/64710](https://golang.org/cl/64710), but I'm opening an issue to consider cherry picking this into go1.9.1.

\cc @bogem

**Comment by dsnet** [comment]
Re-open for possible cherry-pick (for Go1.9 regression)

**Comment by bogem** [comment]
Sorry for this😰

**Comment by dsnet** [comment]
Mistakes happen. Most users probably never hit this issue. Hot-swapping the flag value is a rare use-case in my opinion.

**Comment by otoolec** [comment]
We just hit this.  Caused in our case by spawning a goroutine during `init` which called `log.Println` while the main goroutine continued running `init` functions, one of which called `log.SetFlag` at the same time.

```
WARNING: DATA RACE
Read at 0x00c42008c1a8 by goroutine 8:
  log.(*Logger).Output()
      /usr/local/go/src/log/log.go:152 +0x77
  log.Println()
      /usr/local/go/src/log/log.go:305 +0xa1

Previous write at 0x00c42008c1a8 by main goroutine:
  log.(*Logger).SetFlags()
      /usr/local/go/src/log/log.go:244 +0x76
  log.SetFlags()
      /usr/local/go/src/log/log.go:275 +0x54
```

**Comment by rsc** [comment]
CL 64710 is just reverting to the Go 1.8 code; OK for Go 1.9.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 64710](https://golang.org/cl/64710) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:15 UTC
