### ISSUE TITLE
strconv: ParseBool should also accept "on"

### ISSUE THREAD

**Issue by kristofferingemansson** [golang/go#21932]
HTML forms submit checkboxes as "on" when checked.
I think that `strconv.ParseBool` should return `true` for input str `"on"` as it would make parsing form data much easier.

https://github.com/golang/go/blob/release-branch.go1.9/src/strconv/atob.go#L12

I'm using: Go 1.8 on Windows

**Comment by mdempsky** [comment]
I think this is unlikely to change. Arguably it would be backwards incompatible, since the Go 1 docs specifically say inputs other than those enumerated will return an error.

**Comment by ianlancetaylor** [comment]
`ParseBool` is not intended for HTML form submit checkboxes.  it's easy enough to write your own function.  Closing.
