### ISSUE TITLE
More examples for crypto library usage

### ISSUE THREAD

**Issue by etsangsplk** [golang/go#21937]
Please answer these questions before submitting your issue. Thanks!
It is too brief and hard to understand. Can you add more explanation?
e.g.
https://golang.org/pkg/crypto/sha1/

### What version of Go are you using (`go version`)?
1.7.x
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by AlexRouSg** [comment]
Which part of sha1 do you not understand? Is the problem not knowing what does sha1 do?

For help you would be better off asking in one of the places linked in https://github.com/golang/go/wiki/Questions

**Comment by davecheney** [comment]
I'm going to gecko we this issue as there is no actionable information in this report. As @AlexRouSg said, we don't use the issue tracker for support questions.
