### ISSUE TITLE
cmd/go: accept git commit hash or tag in go get

### ISSUE THREAD

**Issue by ror6ax** [golang/go#21933]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9
### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
go get github.com/organization/repo

### What did you expect to see?
Ability to install specific version of the repo is needed.

go get in https://github.com/golang/go/blob/178307c3a72a9da3d731fecf354630761d6b246c/src/cmd/go/internal/get/vcs.go#L147 uses plain `git pull`.

 `git checkout` should be added afterwards to optionally checkout onto the commit provided in the following fashion:
`go get github.com/organization/repo commithash123456789`
`go get github.com/organization/repo v1.2.1`

**Comment by mvdan** [comment]
How exacly would this syntax work with multiple packages, while still keeping backwards compatibility?

Also note that such a large change should come in the form of a proposal with much more detail.

**Comment by ror6ax** [comment]
Well, as in case of other languages - if you are specifying exact thing to get - it's your problem that it does not work. I personally know many people who are using additional tools/dirty hacks to get this functionality.

Adding the naive matching is better that nothing in such scenario.

Sorry, this is my first work with golang codebase, I'll look up how to create proposals in more formal way.

**Comment by 243083df** [comment]
You should use https://github.com/golang/dep instead

**Comment by mvdan** [comment]
> Adding the naive matching is better that nothing in such scenario.

I don't see how. Doing `go get foo.com/foo bar.com/bar` means one thing currently and is completely unambiguous. How do you propose to keep backwards compatibility with that while adding the versions like you showed?

**Comment by ror6ax** [comment]
By parsing if the repo is followed by commit hash. No hash - no change in
behavior. If hash is present - checkout onto it.

**Comment by mvdan** [comment]
Perhaps I'm missing something very obvious, but it seems to me like the syntax is still ambiguous. In the original post you mentioned tags as well as hashes. How are you going to discern if a string is a tag or an import path? Note that both can be `foo.com/bar`.

**Comment by OneOfOne** [comment]
or you can use git submodules.

**Comment by ror6ax** [comment]
Ok, so now we have 

go get github.com/org/repo

**Comment by MauroMombelli** [comment]
The lack of this ability make impossible to install older version without becoming crazy. 

My use case: i need to install https://github.com/google/cloud-print-connector
But go 1.9 give segmentation fault, so i installed go 1.8, but the projet is using 1.9 in the last version.
Result:
i cant install what i need, and I blame go. Twice.

**Comment by ianlancetaylor** [comment]
@MauroMombelli This issue is closed, for good reasons.  There are some alternatives suggested above.  Another is to run `go get` and then `cd DIR; git checkout REV`.

**Comment by OneOfOne** [comment]
@MauroMombelli if you don't feel like using `dep`, I wrote a little tool for that https://github.com/OneOfOne/git-go-vendor, you should be vendoring your deps one way or the other anyway.

**Comment by MauroMombelli** [comment]
@ianlancetaylor is not checking out the correct version, is to make it complile with all dependency and such. I bring as example the https://github.com/google/cloud-print-connector, a official google product that break and i wanted to have.

@OneOfOne i would like to use it, but i tried some combinantion of parameter before giving up in frustration. I understand the "compile by yourself", but the "handle the dependency fun".. no thank you. I tryed to use another tool that supposely would give you a specific tag, but unfortunately it seems to use a different versioning schema that the project liked, thus making the build unsuccessfully.

**Comment by ianlancetaylor** [comment]
@MauroMombelli This issue is closed and will not be reopened.  If you want to discuss this further, please use a forum; see https://golang.org/wiki/Questions.  Thanks.

**Comment by johndpope** [comment]
glide seems to be path forward
after installing glide 
- just run **glide init**
just edit glide.yaml
![screen shot 2018-01-17 at 2 31 25 pm](https://user-images.githubusercontent.com/289994/35062743-22e42d4e-fb93-11e7-8d7a-6ac05638333a.png)

**Comment by mvdan** [comment]
Again, this issue is closed - please use one of the forums mentioned by @ianlancetaylor above to continue the discussion, or open a new issue if you have a specific proposal or suggestion in mind.
