### ISSUE TITLE
x/build: builders unable to build App Engine apps due to missing packages

### ISSUE THREAD

**Issue by andybons** [golang/go#21949]
All failures at https://go-review.googlesource.com/c/playground/+/64690#message-087a81db71034399093f315c9456bf468bcd006d

Example log from linux amd64 builder:
```
linux-amd64 at c100a0f6680318cb0511b0ecebccb1cdf0eae9b3 building playground at cc9bf7a3cda55e6694065cfbdbcb73b49ec24233

../../gopath/src/golang.org/x/playground/app/goplay/compile.go:12:2: cannot find package "google.golang.org/appengine" in any of:
	/tmp/workdir/go/src/google.golang.org/appengine (from $GOROOT)
	/tmp/workdir/gopath/src/google.golang.org/appengine (from $GOPATH)
../../gopath/src/golang.org/x/playground/app/goplay/edit.go:14:2: cannot find package "google.golang.org/appengine/datastore" in any of:
	/tmp/workdir/go/src/google.golang.org/appengine/datastore (from $GOROOT)
	/tmp/workdir/gopath/src/google.golang.org/appengine/datastore (from $GOPATH)
../../gopath/src/golang.org/x/playground/app/goplay/compile.go:13:2: cannot find package "google.golang.org/appengine/log" in any of:
	/tmp/workdir/go/src/google.golang.org/appengine/log (from $GOROOT)
	/tmp/workdir/gopath/src/google.golang.org/appengine/log (from $GOPATH)
../../gopath/src/golang.org/x/playground/app/goplay/compile.go:14:2: cannot find package "google.golang.org/appengine/urlfetch" in any of:
	/tmp/workdir/go/src/google.golang.org/appengine/urlfetch (from $GOROOT)
	/tmp/workdir/gopath/src/google.golang.org/appengine/urlfetch (from $GOPATH)


Error: tests failed: exit status 1
```

**Comment by adams-sarah** [comment]
So first off, it doesn't look as though trybots have ever been run for playground before (though, I only looked back two years).

Additionally, I cannot find another subrepo supported by gobot which has external dependencies (though I didn't look through all of them, just a few). Notably, oauth2 does not have support (see https://go-review.googlesource.com/#/c/oauth2/+/61050/).

LMK your thoughts @andybons, I can look further into this if you think it's important we have support for trybots for playground CLs.

cc @bradfitz

**Comment by bradfitz** [comment]
I believe there's an existing open bug to make the coordinator support non-golang.org/x/* dependencies.

**Comment by bradfitz** [comment]
Closing this as dup of #24823 as that bug has more detail.
