### ISSUE TITLE
cmd/compile: PPC64.rules for Zero are not checking alignment

### ISSUE THREAD

**Issue by rgdoliveira** [golang/go#21947]
### System information
Go version: 1.9
OS: Alpine Linux 3.6  (but it is not an Alpine specific issue)
Architecture: ppc64le

Seems that PPC64.rules for Zero are not checking alignment in the cases when they should be.
I reproduced this issue when tried to compile [geth](https://github.com/ethereum/go-ethereum) project and it failed with error:

compile: invalid offset for DS form load/store 00056 (/home/rdutra/repos/aports/community/geth/src/go-ethereum-1.7.0/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:452) MOVD R0, "".~r2+33(FP)

### Steps to reproduce the behaviour
Clone go-ethereum repository in a ppc64le distribution
run make (with go 1.9 installed)

**Comment by ianlancetaylor** [comment]
CC @laboger

**Comment by laboger** [comment]
When a MOVD instruction is used the offset field must be a multiple of 4. We had seen this problem a few months ago but MOVDstorezero did not get fixed at that time.

It can be reproduced when there is a function with something like this:

type Hash [32]byte

func testbool() (bool, Hash) {
        var h Hash
        return true, h
}

When there is a MOVDstorezero to data that is >= 8 bytes but not nicely aligned, you can hit this error.

**Comment by laboger** [comment]
This should be backported to go 1.9.

**Comment by laboger** [comment]
I saw there was an announcement about go 1.9.1. Will this make it in there?

**Comment by ianlancetaylor** [comment]
I think 1.9.1 is going to be a security releases, so all the 1.9.1 issues will be bumped to 1.9.2.

**Comment by ianlancetaylor** [comment]
But I'll reopen this one now so that it is considered for 1.9.2.

**Comment by funny-falcon** [comment]
Is it bound with #22047 in any way?

**Comment by laboger** [comment]
No, not related to #22047, the failure in this issue would show up as a compile time error, because in the rare case where the field being zeroed is not aligned to 4 bytes as required by the instruction, the assembler would issue an error message and fail the compile.

**Comment by rsc** [comment]
CL 64970 OK for Go 1.9.2.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 64970](https://golang.org/cl/64970) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:16 UTC
