### ISSUE TITLE
syscall, x/sys/unix: Select is not implemented on ppc64le

### ISSUE THREAD

**Issue by zhsj** [golang/go#21946]
### What version of Go are you using (`go version`)?
go version go1.9 linux/ppc64le

### Does this issue reproduce with the latest release?
yes, with go1.9

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="ppc64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/debian/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build188776017=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```
package main

import (
        "fmt"
        "syscall"
        "unsafe"
)

var nFdBits = uint(8 * unsafe.Sizeof(syscall.FdSet{}.Bits[0]))

func main() {
        fd := 11
        fs := &syscall.FdSet{}
        fs.Bits[uint(fd)/nFdBits] &= ^(1 << (uint(fd) % nFdBits))
        _, e := syscall.Select(fd+1, fs, nil, nil, &syscall.Timeval{Usec: 1})
        fmt.Println(e)
}
```

### What did you expect to see?

I hope it print `<nil>` which is the result on amd64.

### What did you see instead?

it prints `function not implemented`

BTW, gccgo works fine.

**Comment by mundaym** [comment]
/cc @laboger 

It looks like `syscall.Select` should be using the `newselect` system call. The runtime packages appears to have been modified to work around this, but not the syscall package:

runtime:
```
#define SYS_select               82     // always return -ENOSYS
#define SYS_newselect           142

```

**Comment by mundaym** [comment]
The `x/sys/unix` package looks like it is affected as well.

**Comment by laboger** [comment]
@ceseo

**Comment by ceseo** [comment]
I'll have a fix for this shortly.

**Comment by zhsj** [comment]
So I think the fix is merged and we can close this issue now
