### ISSUE TITLE
cmd/go: test should print the failure cases to stderr

### ISSUE THREAD

**Issue by rakyll** [golang/go#21944]
The `go test` output is quite noisy when -v is set. It would be great to be able to differentiate the failed cases and their details.

One differentiator would be writing the failure details to the stderr, then the tools can colorize or filter the stderr to highlight the failures:

![stderrtest](https://user-images.githubusercontent.com/108380/30632584-765cfc66-9d9d-11e7-9a27-4d3f871ad3a9.png)

/cc @rsc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Some way to colorize sounds good to me, but mixing stdout/stderr doesn't seem like the right approach.  I think there will be too many scenarios in which the output gets out of sync.

**Comment by rsc** [comment]
Writing to stderr is not right. Like Ian said, it's too easy to get stdout and stderr out of sync that way. They're not for fine-grained interleaving of the same output. Here there's just one output stream so it all goes to one output. (The canonical case for stdout/stderr would be something like cat, where the output goes to stdout but errors about not being able to open or read input files go to stderr.)

If you want to write a program to read a test's output and presents it in color, that seems easy to do with the current output, without any additional help from the go command or the testing package.

**Comment by rakyll** [comment]
I will write a tool to consume the `go test` output instead, thanks for the input.
