### ISSUE TITLE
debug/macho: parse relocations

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#21957]
I want to debug some relocations. Current library doesn't parse relocations.
So, users have to parse relocations themselves. It would be nice to add these feature in the standard library. debug/pe already have same feature.

**Comment by hirochachacha** [comment]
Hmm, I'm not sure that whether this change is conformance with Go1.0 compatibility rule.

**Comment by alexbrainman** [comment]
> I'm not sure that whether this change is conformance with Go1.0 compatibility rule.

I think your change is fine - you are adding new macho.Reloc type and Relocs filed to existing macho.Section. I did something similar to debug/pe before.

I just need to make sure your new additions are good to stay, because you won't be able to change them after go1.10 is released.

Alex

**Comment by hirochachacha** [comment]
Thanks! I'll take of it.
