### ISSUE TITLE
time: ParseTime layouts with underscores _

### ISSUE THREAD

**Issue by MaVo159** [golang/go#21966]
I suspect this has been mentioned before, but my searches came up empty.

https://play.golang.org/p/p9ZqFEcoJi

This `fmt.Println(time.Parse("2006-_1-_2", "2017-7-17"))` fails with this `0001-01-01 00:00:00 +0000 UTC parsing time "2017-7-17" as "2006-_1-_2": cannot parse "7-17" as "-_"
` output.

I naively expected `_`-parsing to be less greedy. I'm not sure if this is supposed to work, but maybe it is worth fixing anyway.

**Comment by robpike** [comment]
"Within the format string, an underscore _ represents a space that may be replaced by a digit if the following number (a day) has two digits; for compatibility with fixed-width Unix time formats."

I read that as "working as intended."

**Comment by MaVo159** [comment]
I misunderstood the meaning of the word space here. Sorry about that. That was a bit stupid, the docs are actually quite clear. Just removing the underscores has the desired effect.
