### ISSUE TITLE
archive/tar: Example_sparseAutomatic and TestSparseEntries fails on iOS

### ISSUE THREAD

**Issue by dsnet** [golang/go#21970]
The iOS builders are currently failing with: 
```
(lldb) --- FAIL: Example_sparseAutomatic (0.52s)
got:
Src MD5: 33820d648d42cb3da2515da229149f74
Dst MD5: 311175294563b07db7ea80dee2e5b3c6

want:
Src MD5: 33820d648d42cb3da2515da229149f74
Dst MD5: 33820d648d42cb3da2515da229149f74

FAIL
```

This test was added when implementing support for [sparse files hole detection and punching](https://golang.org/cl/60871). On OS+FS that do not support sparse files (such as iOS), `Example_sparseAutomatic` should still produce a non-sparse file, whose content matches the source file. However, the test is indicating that the contents differ for unknown reasons.

**Comment by dsnet** [comment]
@eliasnaur 

I'm trying to debug this issue, but I'm not sure how invoke the failing tests manually on iOS using gomote.

I tried doing the following:
```
$ gomote create darwin-arm64-a1457ios
user-joetsai-darwin-arm64-a1457ios-0

$ gomote push user-joetsai-darwin-arm64-a1457ios-0 
... copies my go root to the builder ...

$ gomote run user-joetsai-darwin-arm64-a1457ios-0 go/src/iostest.bash -restart
...
##### Testing packages.
lldb setup error: exited (lldb start: exit status 253)
start timeout, trying again
lldb setup error: exited (lldb start: exit status 253)
start timeout, trying again
lldb setup error: exited (lldb start: exit status 253)
start timeout, trying again
lldb setup error: exited (lldb start: exit status 253)
start timeout, trying again
lldb setup error: exited (lldb start: exit status 253)
go_darwin_arm_exec: failed to start test harness (retry attempted)
FAIL	archive/tar	12.281s
...
```

Do you have any ideas?

**Comment by eliasnaur** [comment]
I couldn't even get gomote as far as you did, so I debugged to issue manually. The problem seems to be that on darwin, the values of SEEK_HOLE and SEEK_DATA are swapped(!):

````
/usr/include/sys/_types/_seek_set.h:#define	SEEK_HOLE	3	/* set file offset to the start of the next hole greater than or equal to the supplied offset */
/usr/include/sys/_types/_seek_set.h:#define	SEEK_DATA	4	/* set file offset to the start of the next non-hole file region greater than or equal to the supplied offset */
````

I confirmed that this change fixes the build on darwin/arm64:

````
diff --git a/src/archive/tar/sparse_unix.go b/src/archive/tar/sparse_unix.go
index 4bc3482858..b55821d731 100644
--- a/src/archive/tar/sparse_unix.go
+++ b/src/archive/tar/sparse_unix.go
@@ -19,8 +19,8 @@ func init() {
 func sparseDetectUnix(f *os.File) (sph sparseHoles, err error) {
        // SEEK_DATA and SEEK_HOLE originated from Solaris and support for it
        // has been added to most of the other major Unix systems.
-       const seekData = 3 // SEEK_DATA from unistd.h
-       const seekHole = 4 // SEEK_HOLE from unistd.h
+       const seekData = 4 // SEEK_DATA from unistd.h
+       const seekHole = 3 // SEEK_HOLE from unistd.h
 
        // Check for seekData/seekHole support.
        // Different OS and FS may differ in the exact errno that is returned when

````

**Comment by dsnet** [comment]
You got to be freaking kidding me... Solaris invents SEEK_HOLE and SEEK_DATA and most Unix systems have since adopted the same convention with the same definition and semantics (for the most part). It seems utterly insane for Darwin to decide to change it up.

\cc @rasky, do you know if High Sierra has these same (reversed) definitions of SEEK_HOLE and SEEK_DATA? It seems like a major mistake for Apple to switch these values up. Almost seems like a typo on their part.

**Comment by rasky** [comment]
Confirmed, they're swapped in High Sierra as well. Example_sparseAutomatic was failing on High Sierra just like iOS. I mailed the fix.

**Comment by rasky** [comment]
FWIW, I could only reproduce the Example_sparseAutomatic failure on high sierra. I don't know if the patch also fixes TestSparseEntries on iOS.

**Comment by dsnet** [comment]
The [iOS builders are passing now](https://build.golang.org/), so I think it's safe to say it's fixed. Thanks.
