### ISSUE TITLE
archive/tar: TestSparseFiles failing on plan9/arm builder

### ISSUE THREAD

**Issue by 0intro** [golang/go#21977]
CL [60871](https://golang.org/cl/60871) added TestSparseFiles. This test is failing on the plan9/arm builder.

```
--- FAIL: TestSparseFiles (117.51s)
    --- FAIL: TestSparseFiles/EmptyFile (0.17s)
    	tar_test.go:844: unexpected ReadFrom error: tar: write too long
    --- FAIL: TestSparseFiles/BigHole (0.25s)
    	tar_test.go:844: unexpected ReadFrom error: tar: write too long
    --- FAIL: TestSparseFiles/DataFront (0.44s)
    	tar_test.go:844: unexpected ReadFrom error: tar: write too long
    --- FAIL: TestSparseFiles/HoleFront (1.43s)
    	tar_test.go:872: sparse files mismatch
    --- FAIL: TestSparseFiles/DataMiddle (0.39s)
    	tar_test.go:844: unexpected ReadFrom error: tar: write too long
    --- FAIL: TestSparseFiles/HoleMiddle (1.41s)
    	tar_test.go:872: sparse files mismatch
    --- FAIL: TestSparseFiles/Multiple (109.91s)
    	tar_test.go:872: sparse files mismatch
FAIL
FAIL	archive/tar	140.157s
```

See https://build.golang.org/log/6c62187355a860390505342ac82661184645f959

**Comment by 0intro** [comment]
The test is only failing on the plan9/arm builder because this builder use the Fossil file system for /tmp instead of ramfs.

It seems there is an issue with the handling of sparse files in the Fossil file system.

**Comment by dsnet** [comment]
I'll investigate why this is failing on Plan9. On OS without sparse file support, this test should still pass. It does however rely on being able to `Seek` beyond the EOF and write some data, with the assumption that the data in-between is filled with zeros (and on OS that support it, represented by a sparse hole).

**Comment by millerresearch** [comment]
TestSparseFiles was removed in 2017 by CL 78030.

**Comment by bcmills** [comment]
>  It does however rely on being able to `Seek` beyond the EOF and write some data, with the assumption that the data in-between is filled with zeros

That assumption does not hold for `io.Seeker` implementations in general anyway (see #48316). I am not sure whether it ought to always hold for `os.File` in particular.
