### ISSUE TITLE
cmd/ld: on Windows, make sure DWARF and .symtab PE sections are not in memory

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#2198]
<pre>As per summary.</pre>

**Comment by ianlancetaylor** [comment]
As far as I can tell, this is done.  I built a Go cross-compiler, built a hello, world program, and use objdump -h to look at the header flags.  The .text and .data sections have the ALLOC flag, the .symtab and DWARF sections do not.

@alexbrainman Please reopen if there is something else to do.

**Comment by alexbrainman** [comment]
Nothing to do here. I agree.

Alex
