### ISSUE TITLE
strip binaries

### ISSUE THREAD

**Issue by forskning** [golang/go#21986]
Do the Go developers have an opinion on stripping binaries and libraries?

http://nurmi-labs.blogspot.com/2017/08/bootstrapping-go.html

Generally SlackBuild scripts will contain lines like the following after the
executables and dynamic libraries are compiled. The go source however
already contains some executables, so if only the newly generated files
were to be stripped, I might modify the build adding code to strip those
files in bin and libstd.so.

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | \
 grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

NB: This question is intended to pertain solely to source downloads.

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
