### ISSUE TITLE
sort: change the main example to use Slice instead of Sort

### ISSUE THREAD

**Issue by agnivade** [golang/go#21989]
Hi,

The topmost example that we see if we open https://golang.org/pkg/sort/ uses the `sort.Sort` function. The use case it solves is the most common one which compares an attribute inside a struct.

I think its better to point people to the more comfortable and simple function `sort.Slice` for the most common case.

So, that would change -
```go
// ByAge implements sort.Interface for []Person based on
// the Age field.
type ByAge []Person

func (a ByAge) Len() int           { return len(a) }
func (a ByAge) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a ByAge) Less(i, j int) bool { return a[i].Age < a[j].Age }

func main() {
	people := []Person{
		{"Bob", 31},
		{"John", 42},
		{"Michael", 17},
		{"Jenny", 26},
	}

	fmt.Println(people)
	sort.Sort(ByAge(people))
	fmt.Println(people)

}
```

to 
```go
func main() {
	people := []Person{
		{"Bob", 31},
		{"John", 42},
		{"Michael", 17},
		{"Jenny", 26},
	}

	fmt.Println(people)
	sort.Slice(people, func(i, j int) bool {
		return people[i].Age < people[j].Age
	})
	fmt.Println(people)
}
```

I believe this would lead newcomers who don't know about the new `sort.Slice` function and have just opened the documentation page for the first time, to use a better and simpler option.

Would be happy to send a CL if you guys agree to this.

**Comment by mvdan** [comment]
This sounds like a good idea. But perhaps we should add a sort.Sort example then, showing a common case where sort.Slice isn't enough.

**Comment by agnivade** [comment]
Yep, there are 4 examples in the top section. All of them use sort.Sort. So, we would be just changing the most common use-case to sort.Slice. The remaining 3 will still use sort.Sort.

This was partly inspired by your CL which replaced lot of sort.Sort usages with sort.Slice. :smile:  I just happened to look up the definition of sort.Slice and this idea hit me.

**Comment by mvdan** [comment]
I see - it sounds like the package examples should mention `sort.Slice`, yes. Feel free to send a CL. I don't guarantee it will be merged, and I won't approve it since I'm not that familiar with the package, but it seems like a good idea to me.

**Comment by kennygrant** [comment]
There are already sort.Slice and sort.SliceStable example, they just aren't featured in the top 4 examples:

https://golang.org/pkg/sort/#Slice
https://golang.org/pkg/sort/#SliceStable

I agree they should have more prominence.

**Comment by agnivade** [comment]
Exactly. This is about getting sort.Slice some more love.
