### ISSUE TITLE
conda-forge package for go-lang

### ISSUE THREAD

**Issue by abhi18av** [golang/go#21998]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `Go-lang` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4023) 

I'm running into issues, could you help me get `go-lang` into the conda management space ?

**Comment by cznic** [comment]
Please `s/[Gg]o-lang/Go/g`, thanks.

**Comment by 0x434d53** [comment]
This is an issue tracker. 

Please use https://groups.google.com/forum/#!forum/golang-nuts or the gophers slack for questions

**Comment by abhi18av** [comment]
@cznic and @0x434d53 I understand. Thank you :+1:
