### ISSUE TITLE
cmd/build: wrong error on misspelled GOOS

### ISSUE THREAD

**Issue by dvyukov** [golang/go#21999]
go version devel +39983cf491 Wed Sep 20 18:11:52 2017 +0000 linux/amd64

package has 2 files: `test_linux.go`
```go
package test
```
and `test_windows.go`:
```go
package test
```

```
$ GOOS=windwos go build ./test
can't load package: package test: build constraints exclude all Go files in /gopath/test
```

should say:
```
$ GOOS=windwos go build ./test
cmd/go: unsupported GOOS/GOARCH pair windwos/amd64
```

**Comment by mvdan** [comment]
This seems to be because the build constraints error is thrown when loading a package, whereas the GOOS/GOARCH one is thrown when trying to build it.
