### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by younisshah** [golang/go#22006]
The following links are broken (at least):

1. [applied mux()ing: a LimitBuffer](http://gowithconfidence.tumblr.com/post/31797884887/limit-buffers)
2. [Just muxing about](http://gowithconfidence.tumblr.com/post/31431608488/muxing)
3. [Stacked channels ](http://gowithconfidence.tumblr.com/post/31426832143/stacked-channels)

**Comment by mvdan** [comment]
Sorry, where do these links appear?

If you're referring to that tumblr alone, it appears unrelated to the Go project.

**Comment by younisshah** [comment]
These links appear [here] (https://github.com/golang/go/wiki/Articles)

**Comment by younisshah** [comment]
These links appear [here](https://github.com/golang/go/wiki/Articles) on the golang wiki.

**Comment by opennota** [comment]
I've removed these.

**Comment by younisshah** [comment]
This one as well.

[An introduction to pointers for Go programmers not coming from C family languages](http://andlabs.lostsig.com/blog/2014/06/30/85/an-introduction-to-pointers-for-go-programmers-not-coming-from-c-family-languages)

**Comment by mvdan** [comment]
I believe that the wiki can be edited by any user. If you find broken links or other errors, you can fix them yourself without raising an issue asking for others to apply the changes.
