### ISSUE TITLE
spec: some wording need to be adjusted for embedding alias of pointer types

### ISSUE THREAD

**Issue by zigo101** [golang/go#22005]
Now, the wording is
> An embedded field must be specified as a type name T or as a pointer to a non-interface type name *T, and T itself may not be a pointer type.

However aliases of *T can also be embedded.

**Comment by go101** [comment]
btw, some wording in the <a href="https://golang.org/ref/spec#Method_declarations">Method declarations</a> may also need to be adjusted.

**Comment by griesemer** [comment]
I think those are still correct. We still have named types (any type that has a name); it's just that it may be a defined or an alias type.

The rules for embedding allow alias types.

The rules for method receivers explicitly say that the receiver type must be _defined_ in the same package.

Is there anything specific that you believe needs to be fixed (and why)?

**Comment by go101** [comment]
Maybe my English understanding is not correct, for embeddable types, spec says
> ..., and T itself may not be a pointer type.

However, T can be a pointer type (as an alias)
```golang
type T = *int
type S struct{
	T // T is a pointer
}
```

And for method receivers, `the receiver type must be defined in the same package.`.
However, aliases declared in the same package can also be used as receiver types.
```golang
type S struct{}
type T = S
type P = *S
func (T) f() {}
func (*T) g() {}
func (P) h() {}
```

**Comment by griesemer** [comment]
Hm, you have a point. I'll look into this. Thank you!

**Comment by myitcv** [comment]
> However, aliases (which are not defined) declared in the same package can also be used as receiver types.

...

> Maybe, mention that `declared methods on an alias of a type has the same effect as declaring methods on the type itself` would be better.

I think this is implicit in the definition of an alias itself; i.e. that an alias is just that, an alias for a defined type (recursive definition), not a type in and of itself.

So in your method examples the receiver types are:

```go
type S struct{}
type T = S
type P = *S
func (T) f() {}   // S
func (*T) g() {}  // *S
func (P) h() {}   // *S
```

it's just that we're using aliases to refer to those two types. 

Similarly with embedding:

```go
type T1 = *int
type S struct{
	T1 // *int; T = int in spec terms (i.e. the "may not be a pointer type" bit)
}
```

**Comment by daiweisong** [comment]
fuck  you r mother




At 2017-09-26 17:46:04, "Paul Jolly" <notifications@github.com> wrote:


However, aliases (which are not defined) declared in the same package can also be used as receiver types.

...

Maybe, mention that declared methods on an alias of a type has the same effect as declaring methods on the type itself would be better.

I think this is implicit in the definition of an alias itself; i.e. that an alias is just that, an alias for a defined type (recursive definition), not a type in and of itself.

So in your method examples the receiver types are:

typeSstruct{}
typeT = StypeP = *S
func(T) f() {}   // Sfunc(*T) g() {}  // *Sfunc(P) h() {}   // *S

it's just that we're using aliases to refer to those two types.

Similarly with embedding:

typeT1 = *inttypeSstruct{
	T1// *int; T = int in spec terms (i.e. the "may not be a pointer type" bit)
}

**Comment by go101** [comment]
@myitcv yes, no problems on the mechanism here. It is just that some terminologies and some wording need to be clarified. For example, what is a named type? Is alias of a defined type can also be called defined type? etc.

**Comment by go101** [comment]
I feel some wording for [the method documentations](https://golang.org/pkg/reflect/#Type) of the `refect.Type` type also need adjusted.

**Comment by go101** [comment]
Are the following descriptions accurate?
* A type name `T` can be embedded as an embedded field unless `T` denotes a pointer type which base type is either a pointer or an interface type.
* A pointer type `*T`, where `T` is a type name denoting the base type of the pointer type, can be embedded as an embedded field only if `T` doesn't denote a pointer or interface type.

**Comment by griesemer** [comment]
@go101 I believe those descriptions are still accurate; by type name we do mean a name denoting a type (and it could be an alias).

**Comment by go101** [comment]
> An embedded field must be specified as a type name T or as a pointer to a non-interface type name *T, and T itself may not be a pointer type.

The above shown current description excludes the following `T` alias.

```golang
type T = *int
type S struct{
	T // T is a pointer
}
```

**Comment by go101** [comment]
Or the following one?

> An embedded field must be specified as the form `T` or `*T`, where `T` is a type name and the embedded type may not be a pointer type whose base type is a pointer or interface type.

**Comment by go101** [comment]
A question, why pointer types whose base types are pointer and interface types can't be embedded?
If they can, the rule can be much simplified as `An embedded field must be specified as a type name or a type literal which can provide an identifier as the field name`.

**Comment by griesemer** [comment]
@go101 Originally, we wanted to avoid situations such as **T embeddings, etc. There are also interactions with lookup of embedded fields and methods. You're right that there are certainly unanswered questions here, and possibly inconsistencies. I'd love to simplify this, as it is only going to get more complex if we have generics as well. Thanks for pointing out the inconsistencies. We will get to this eventually; but at the moment it is not a high priority.

**Comment by go101** [comment]
I think I got why pointer types whose base types are pointer and interface types can't be embedded.
The reason is, except pointer and interface types, the each type `T` of other types, the method set of `*T` is always a super-set of `T`.

**Comment by go101** [comment]
Just found [my above description](https://github.com/golang/go/issues/22005#issuecomment-481392945) is not accurate. It missed the following highlighted case:

* A type name T can be embedded as an embedded field unless T denotes **a defined pointer type or** a pointer type which base type is either a pointer or an interface type.
* A pointer type *T, where T is a type name denoting the base type of the pointer type, can be embedded as an embedded field unless type name T denotes a pointer or interface type.

**Comment by go101** [comment]
I just noticed that, gc and gccgo have different behaviors on this inaccuracy.
For the following code, gc compiles it okay, but gccgo reports an error.

```golang
package main

type P = *bool
type T struct {
	P
}

func main() {}
```

**Comment by ianlancetaylor** [comment]
@go101 At first glance I think that is a gccgo bug.  Want to file an issue for that?  Thanks.

**Comment by griesemer** [comment]
Just FYI: go/types also accepts this code.

**Comment by ianlancetaylor** [comment]
Ping @griesemer .  This just came up again in #69460, q.v.

**Comment by griesemer** [comment]
This was fixed with https://go.dev/cl/406054 (duplicate issue #41687).

**Comment by zigo101** [comment]
> An embedded field must be specified as a type name T or as a pointer to a non-interface type name *T, and T itself may not be a pointer type or type parameter. 

It is still a little weird, because an alias name T to a pointer type can be embedded. But maybe it is not a big problem. Wording is hard.

In fact, I'm still some wondering why interface and pointer types are excluded here. If they are not, then the wording can be much simplified to "An embedded field must be specified as a type name T or as a pointer to type name *T."
