### ISSUE TITLE
Go Experience Report: Generic functions cannot be passed as values

### ISSUE THREAD

**Issue by awalterschulze** [golang/go#22003]
I would like to submit a Go Experience Report

https://gist.github.com/awalterschulze/e3999f8cfa29b246c35a651a2be4d121

**Comment by jimmyfrasche** [comment]
To submit an experience report, you just need to add it to this wiki page https://github.com/golang/go/wiki/ExperienceReports following the instructions at the top. I believe it is editable by anyone.

(I hope Go 2 fixes this at well—thank you for writing the report).

**Comment by awalterschulze** [comment]
Thanks.  I added it to the page.  I wrongly assumed it wasn't that open.
