### ISSUE TITLE
cmd/go: docs: document that main packages cannot be imported

### ISSUE THREAD

**Issue by elliott-beach** [golang/go#22011]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.9 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elliott/me/projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build792066057=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

A non-main package cannot import a main package. I discovered this when importing my main package by its canonical name, `github.com/e-beach/main-package-example`, in a test package. I also believe that main packages _can_ import other main packages, but did not test that here.

See https://github.com/e-beach/main-package-example for an example.
See https://groups.google.com/forum/#!topic/Golang-nuts/frh9zQPEjUk for the discussion that gave birth to the issue.

### What did you expect to see?
I expected `cd test && go test` to pass without error.

### What did you see instead?
```
# github.com/e-beach/main-package-example/test 
main_test.go:4:2: import "github.com/e-beach/main-package-example" is a program, not an importable package FAIL	github.com/e-beach/main-package-example/test [setup failed]
```

This behavior is reasonable, but is not in the spec and should be documented.

**Comment by go101** [comment]
This may be compiler dependent: https://github.com/golang/go/issues/21256#issuecomment-320954994

**Comment by ianlancetaylor** [comment]
The restriction you are describing is imposed by the go tool, so it should be in the go tool docs, not the language spec.

**Comment by ianlancetaylor** [comment]
It actually is documented at https://golang.org/cmd/go/#hdr-Description_of_package_lists but perhaps it could be documented elsewhere.  Any thoughts?

**Comment by elliott-beach** [comment]
I cannot name a better place, so I’ll close this.
