### ISSUE TITLE
crypto/x509: Truncate DSA signed data's hash before verification

### ISSUE THREAD

**Issue by Tasssadar** [golang/go#22017]
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
Yes

The [x509.Certificate's CheckSignature function](https://golang.org/pkg/crypto/x509/#Certificate.CheckSignature) does not truncate the signed data's hash ([as dsa's docs say should be done](https://golang.org/pkg/crypto/dsa/#Verify)), resulting in wrong check result. When I truncated the hash, the check passes, as can be seen below.

I'm not sure whether the hash should be truncated for *all* x509 certs. This is tested with Android APK signatures, which do require the truncation (the data in code below were [extracted from this apk](https://www.virustotal.com/#/file/01ecd220ed37e0e43fa044732f03741811fb59e0d0ad341e4980226ff5ec9858/detection) and there are more like it).

I can submit a pull request if you think it is correct to do the truncation.

[Raw full source of the code (~4k lines)](https://gist.githubusercontent.com/Tasssadar/8a28332cf2ed08370e53fae555b7c5d8/raw/a426058f677574c3d94584f272982e1df32e3fba/issue-repro.go)

```golang
package main

import (
	"fmt"
	"crypto/x509"
	"crypto/sha256"
	"crypto/dsa"
	"math/big"
	"errors"
	"encoding/asn1"
)

type dsaSignature struct {
	R, S *big.Int
}

func checkWithTruncatedHash(cert *x509.Certificate) error {
	hash := sha256.Sum256(signed)
	pub := cert.PublicKey.(*dsa.PublicKey)

	reqLen := pub.Q.BitLen() / 8

	if reqLen > len(hash) {
		return fmt.Errorf("Digest algorithm is too short for given DSA parameters.")
	}
	digest := hash[:reqLen]

	dsaSig := new(dsaSignature)
	if rest, err := asn1.Unmarshal(signature, dsaSig); err != nil {
		return err
	} else if len(rest) != 0 {
		return errors.New("x509: trailing data after DSA signature")
	}
	if dsaSig.R.Sign() <= 0 || dsaSig.S.Sign() <= 0 {
		return errors.New("x509: DSA signature contained zero or negative values")
	}
	if !dsa.Verify(pub, digest, dsaSig.R, dsaSig.S) {
		return errors.New("x509: DSA verification failure")
	}
	return nil
}

func main() {
	cert, _ := x509.ParseCertificate(rawCert)

	fmt.Printf("Result of check with original crypto/x509: %v\n", cert.CheckSignature(algo, signed, signature))
	fmt.Printf("Result of check with truncated hash: %v\n", checkWithTruncatedHash(cert))
}

var algo = x509.DSAWithSHA256

var rawCert = []byte { ... }
var signature = []byte { ... }
var signed = []byte { ... }
```

**Comment by agl** [comment]
(Man, I should never have supported DSA in that code.)

I'm not sure that it's valid to have the hash mismatch with the DSA key type, as you have here. DSA was originally specified only with SHA-1 and with 1024-bit keys. That's what you have in the certificate, but your signature algorithm is DSAWithSHA256. For that, you should have a 2048/256 key.

**Comment by Tasssadar** [comment]
Unfortunately, it's not really my key - I just need to verify the signature is correct. The signature check in Android passes without at problem, so it's "valid" in that way at least.

I'm fine with having that extra checkWithTruncatedHash function in my code, I just saw that dsa docs say the hash should be truncated, but it isn't in x509 and thought it might be a bug.

**Comment by FiloSottile** [comment]
Alright, I would like to let DSA rot in a corner, and using SHA-256 with 1024 bit keys is _weird_, but as far as I can tell we are indeed doing this wrong. I would take a PR to fix this with a test case that passes OpenSSL verification.
