### ISSUE TITLE
runtime: TestGdbConst output mismatch

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#22012]
### What version of Go are you using (`go version`)?

go version devel +45395b5ad6 Mon Sep 25 08:54:28 2017 +0000 windows/amd64

### Does this issue reproduce with the latest release?

It does not.

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\users\alex\dev
set GORACE=
set GOROOT=c:\users\alex\dev\go
set GOTOOLDIR=c:\users\alex\dev\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Alex\AppData\Local\Temp\go-build558249031=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

go test -v -run=TestGdbConst runtime

### What did you expect to see?

PASS

### What did you see instead?

=== RUN   TestGdbConst
--- FAIL: TestGdbConst (0.49s)
        runtime-gdb_test.go:55: gdb version 7.8
        runtime-gdb_test.go:436: output "No symbol \"startup\" in current context.\r\nBreakpoint 1 at 0x44d004: file C:/Users/Alex/AppData/Local/Temp/go-build229403255/main.go, line 9.\r\n[New Thread 9736.0x2280]\r\n[New Thread 9736.0x165c]\r\n[New Thread 9736.0x1e70]\r\n[New Thread 9736.0x824]\r\nwarning: Can not parse XML library list; XML support was disabled at compile time\r\n[New Thread 9736.0x63c]\r\n[New Thread 9736.0x228]\r\n[New Thread 9736.0x2220]\r\n[New Thread 9736.0x27e0]\r\n\r\nBreakpoint 1, main.main () at C:/Users/Alex/AppData/Local/Temp/go-build229403255/main.go:9\r\n9\t\tprintln(\"hello world\")\r\n$1 = 42\r\n$2 = 18446744073709551615\r\n$3 = -1\r\n$4 = 1 '\\001'\r\n"
        runtime-gdb_test.go:439: output mismatch
FAIL
exit status 1
FAIL    runtime 0.591s

**Comment by alexbrainman** [comment]
Looks like new test by @aarzilli expects gdb output strings delimited by \n, while my gdb delimits them by \r\n. Leaving it for others to decide how to adjust this if condition.

Alex

**Comment by aarzilli** [comment]
Are the windows try-bots not running gdb tests or is there a way to make gdb on windows terminate lines with \n only?

**Comment by alexbrainman** [comment]
> Are the windows try-bots not running gdb tests

Quite possible ( @andybons or @johnsonj do you know if windows trybots have gdb installed? Do any of runtime/runtime-gdb_test.go tests run on trybots? ). TestGdbConst calls checkGdbVersion which calls t.Skip if gdb is not found and for other reasons.

> is there a way to make gdb on windows terminate lines with \n only?

I would not know. Why don't we remove all \r from gdb output before comparing it with "sgot" variable? I can make that change, if you agree. Or you can do it yourself.

Alex

**Comment by aarzilli** [comment]
I went the other way with the CL because I was worried about the lone '\r' terminator being still alive somewhere, but maybe that's unfounded.

**Comment by johnsonj** [comment]
@alexbrainman Just checked and it looks like no. I've filed and self assigned golang/go#22021

**Comment by alexbrainman** [comment]
> I've filed and self assigned golang/go#22021

Sounds like a plan. Thank you.

Alex
