### ISSUE TITLE
all: WSL/Ubuntu: all.bash test failures

### ISSUE THREAD

**Issue by peterGo** [golang/go#22020]
Windows Subsystem for Linux/Bash on Ubuntu on Windows

Assign to Jessica Frazelle: https://groups.google.com/forum/#!topic/golang-dev/CXCntlhqrAo.

Installing from source, several tests fail when running all.bash.

﻿Microsoft Windows [Version 10.0.15063]
2017-09 Cumulative Update for Windows 10 Version 1703 for x64-based Systems

Bash on Ubuntu on Windows

```
~$ cd
~$ sudo apt update
All packages are up to date.
~$ git clone https://go.googlesource.com/go
~$ cd go/src
~/go/src$ ./all.bash

2017/09/25 15:11:18 startServer failed: listen unixgram /tmp/syslogtest751681628: setsockopt: invalid argument
FAIL    log/syslog      0.400s
--- FAIL: TestDialerDualStackFDLeak (2.40s)
        dial_test.go:90: got 1.241199s; want <= 95ms
--- FAIL: TestFilePacketConn (0.01s)
        file_test.go:243: listen unixgram /tmp/go-nettest784376401: setsockopt: invalid argument
--- FAIL: TestInterfaceMulticastAddrs (0.01s)
        interface_test.go:156: num IPv6 multicast route clones = 0; want >0; summary: &{loop:1 other:2}, &{ipv4:5 ipv6:7}, &{ipv4:0 ipv6:0}
--- FAIL: TestTCPListener (0.00s)
        listen_test.go:71: skipping tcp  test
        listen_test.go:71: skipping tcp 0.0.0.0 test
        listen_test.go:71: skipping tcp ::ffff:0.0.0.0 test
        listen_test.go:71: skipping tcp :: test
        listen_test.go:89: tcp 127.0.0.1 should fail
panic: test timed out after 3m0s
FAIL    net/http        180.384s
--- FAIL: TestMincoreErrorSign (0.00s)
        runtime_linux_test.go:40: mincore = -38, want -22
FAIL    runtime 42.456s
--- FAIL: TestCPUProfile (6.23s)
--- FAIL: TestCPUProfileMultithreaded (6.27s)
--- FAIL: TestCPUProfileInlining (6.23s)
--- FAIL: TestMathBigDivide (6.23s)
--- FAIL: TestCPUProfileLabel (6.23s)
--- FAIL: TestLabelRace (7.58s)
FAIL
FAIL    runtime/pprof   40.395s
--- FAIL: TestFcntlFlock (0.04s)
        syscall_unix_test.go:103: child process: "--- FAIL: TestFcntlFlock (0.00s)\n\tsyscall_unix_test.go:120: FcntlFlock got {1 0 [0 0 0 0] 0 0 1 [0 0 0 0]}, want {1 0 [0 0 0 0] 31415 271828 7200 [0 0 0 0]}\nFAIL\n", exit status 1
FAIL
FAIL    syscall 0.340s
panic: test timed out after 3m0s
FAIL    vendor/golang_org/x/net/nettest 180.118s
panic: test timed out after 3m0s
FAIL    cmd/go  194.075s
2017/09/25 15:18:45 Failed: exit status 1

~/go/src$ cd
~$ cd go/bin
~/go/bin$ ./go version
go version devel +5e92c41 Mon Sep 25 11:34:24 2017 +0000 linux/amd64
~/go/bin$ ./go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/home/peter/go"
GOTOOLDIR="/home/peter/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build174871302=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
~/go/bin$
```

Full Output:

[wsl.ubuntu.txt](https://github.com/golang/go/files/1330163/wsl.ubuntu.txt)

**Comment by cznic** [comment]
I'd guess that WSL is just broken. If so, the issue should be reported elsewhere (have no idea where).

**Comment by forskning** [comment]
As you have Creators Update (CU) installed any interest in looking at the pre-compiled download.

https://packages.ubuntu.com/xenial/golang-1.6

**Comment by peterGo** [comment]
@forskning:

As requested, I installed Go source from https://packages.ubuntu.com/xenial/golang-1.6 and ran all,bash on WSL/Ubuntu. Several tests failed. See the attached output.

[wsl.ubuntu.go1.6.txt](https://github.com/golang/go/files/1334222/wsl.ubuntu.go1.6.txt)

As a point of reference, the machine dual boots Windows 10 and Linux Mint 18.2 (Ubuntu 16.04). I've attached the output from Mint.

[wsl.mint.18.2.txt](https://github.com/golang/go/files/1334291/wsl.mint.18.2.txt)

**Comment by forskning** [comment]
https://msdn.microsoft.com/en-us/commandline/wsl/faq

https://github.com/Microsoft/BashOnWindows/issues

https://github.com/Microsoft/BashOnWindows/issues/2526

**Comment by jessfraz** [comment]
ok after I dig into these I'm gunna figure out how to add a WSL builder

**Comment by forskning** [comment]
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

Issues and Fixes  for various Builds, e.g., Build 14986 implemented timer_create used by ghc.

https://technet.microsoft.com/en-us/library/bb463220.aspx

The above link is possibly of interest historically regarding Microsoft® subsystems, i.e., D. Cutler's work on NT, therein described as "an architecture that is subsystem centric".

http://nurmi-labs.blogspot.com/2017/09/bootstrapping-go.html

Personally I regret the decision of MS® to deprecate the Interix subsystem.

**Comment by forskning** [comment]
Installing under Annniversary Update (AU) the pre-compiled trusty (14.04LTS) ghc exposed timer_create as not having been implemented. That's (primarily) why I suggested under Creators Update (CU) looking at the xenial (16.04LTS) pre-compiled golang-1.6, and running therefrom various pertinent go code samples.

**Comment by forskning** [comment]
@peterGo

Thanks for the 1.6 and mint output.

**Comment by peterGo** [comment]
The next feature release of Windows 10, Windows 10 Fall Creators Update, is imminent. Windows 10 Insider Preview Build 16299 is a close approximation,

Announcing Windows 10 Insider Preview Build 16299 for PC
https://blogs.windows.com/windowsexperience/2017/09/26/announcing-windows-10-insider-preview-build-16299-pc/

For Windows 10 Fall Creators Update:
Windows Subsystem for Linux is out of Beta!
https://blogs.msdn.microsoft.com/commandline/2017/07/28/windows-subsystem-for-linux-out-of-beta/

For Windows 10 Fall Creators Update:
Bash on Ubuntu in Windows 10 Store (WSL Linux)
https://aka.ms/wslstore
https://www.microsoft.com/store/apps/9NBLGGH4MSV6

Installing Go from source, several tests fail when running all.bash under WSL/Bash on Ubuntu in Windows 10 Store. See output:

[wsl.fallcreators.txt](https://github.com/golang/go/files/1345219/wsl.fallcreators.txt)

**Comment by johnsonj** [comment]
FYI #17365 tracks adding a WSL builder. We can't do it today on GCE. Maybe @jessfraz can do it on Azure?

**Comment by forskning** [comment]
@peterGo the above cited Microsoft/WSL issue I opened on 27 Sep 2017 had a comment added on 4 Dec 2017, and subsequently has been closed
