### ISSUE TITLE
runtime: runtime.GC() does not trigger GC if GOGC=off

### ISSUE THREAD

**Issue by aclements** [golang/go#22023]
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

Also happens on master.

### What did you do?
Attempt to manually trigger a GC using `runtime.GC()` while GOGC is set to off:
https://play.golang.org/p/vB6-urJJ7M

### What did you expect to see?
The GC should run.

### What did you see instead?
The GC does not run.

This is a regression from 1.8 caused by my rewrite of `gcShouldStart` into `(gcTrigger).test`. I've marked this for Go 1.9.1. I'm not sure how important it is, but it's also easy to fix.

/cc @RLH

**Comment by RLH** [comment]
The work around would be to set GOGC to some number large enough to exhaust
the machine's resources. This would have the same impact as GOGC=off.

**Comment by aclements** [comment]
Re-opening for cherry-pick to 1.9

**Comment by rsc** [comment]
OK for Go 1.9.2.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 65994](https://golang.org/cl/65994) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:17 UTC
