### ISSUE TITLE
compress/bzip2: read of zero bytes yields error

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#22028]
go version devel +6171d05 Sat Sep 23 09:24:02 2017 +0000 linux/amd64

The following program prints:

   bzip2 data invalid: block checksum mismatch

but it should not.

	package main
	
	import (
		"bytes"
		"compress/bzip2"
		"log"
	)
	
	var data = []byte{
		0x42, 0x5a, 0x68, 0x39, 0x31, 0x41, 0x59, 0x26, 0x53, 0x59, 0x36, 0xa9,
		0xc3, 0x7a, 0x00, 0x00, 0x9a, 0xfb, 0x84, 0xc0, 0x80, 0x00, 0x80, 0x40,
		0x00, 0xff, 0x80, 0x00, 0x22, 0x62, 0xe0, 0x1e, 0x00, 0x00, 0x01, 0x10,
		0x08, 0x20, 0x00, 0x94, 0x82, 0xaa, 0x32, 0x93, 0x35, 0x06, 0x8d, 0x36,
		0xa0, 0xd3, 0x20, 0x92, 0x49, 0xea, 0x69, 0xa0, 0xd0, 0x00, 0x33, 0xb3,
		0xc8, 0xe5, 0x27, 0xa0, 0x20, 0x68, 0x88, 0x48, 0x71, 0xc1, 0xa7, 0x02,
		0x43, 0x0e, 0x18, 0x0c, 0x24, 0x10, 0x18, 0x83, 0x64, 0x36, 0x4e, 0x46,
		0x8c, 0x4a, 0x6b, 0x7c, 0x94, 0x92, 0xaa, 0x9a, 0x55, 0x08, 0x82, 0xe8,
		0xa6, 0x33, 0x6b, 0x4f, 0x2a, 0x2f, 0x09, 0x4a, 0x33, 0x85, 0xb0, 0x45,
		0x8b, 0x98, 0x51, 0xaa, 0xab, 0xbe, 0x93, 0xa1, 0xc7, 0x1b, 0xbf, 0x29,
		0xbd, 0x1c, 0x3d, 0x5f, 0xd0, 0x98, 0x90, 0x54, 0x5d, 0xc9, 0x14, 0xe1,
		0x42, 0x40, 0xda, 0xa7, 0x0d, 0xe8,
	}
	
	func main() {
		r := bzip2.NewReader(bytes.NewReader(data))
		_, err := r.Read(nil)
		if err != nil {
			log.Fatal(err)
		}
	}

**Comment by dsnet** [comment]
Thanks for the succinct report.
