### ISSUE TITLE
Combining explicit arguments with slice expansion doesn't work

### ISSUE THREAD

**Issue by funny-falcon** [golang/go#22035]
Probably it is already discussed. But I didn't see description in Language Specification.

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64
play.golang.org

### Does this issue reproduce with the latest release?
I think, yes.

### What did you do?
https://play.golang.org/p/2Qm34TE-gn
```go
func main() {
	a := []interface{}{ 1, 2, 3 }
	fmt.Println(1, 2, 3)
	fmt.Println(a...)
	fmt.Println(-1, 0, a...)
}
```
### What did you expect to see?
```
1 2 3
1 2 3
-1 0 1 2 3
```

### What did you see instead?
```
tmp/sandbox223672132/main.go:11:13: too many arguments in call to fmt.Println
	have (number, number, []interface {}...)
	want (...interface {})
```

**Comment by robpike** [comment]
This is working as defined in the spec. The arguments to match a variadic argument may be a list of singletons or a slice followed by ..., not a combination. The main reason is to avoid ambiguity that can lead to errors.

Working as intended.

**Comment by mvdan** [comment]
The previous Go2 proposals are https://github.com/golang/go/issues/18605 and https://github.com/golang/go/issues/19218.

@robpike you might want to raise your point in the proposals, or when the time comes for Go2.
