### ISSUE TITLE
cmd/go: go run hangs for a few minutes from windows command line

### ISSUE THREAD

**Issue by dargopolis** [golang/go#22055]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\dglass\go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dglass\AppData\Local\Temp\go-build241023583=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

Windows 7 Enterprise
Service Pack 1
64-bit operating system

Intel(R)Core(TM)i5-5300U CPU @2.30GHz 2.30 GHz

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

From the Windows command line (CMD), I used go run to run a hello world program like https://play.golang.org/p/v3rrZLwEUC

go run hello.go

### What did you expect to see?
I expected the program to return to the command line immediately.

### What did you see instead?
The program hung for a few minutes after it appeared to be done (e.g. after the last output was written).
And, it could not be interrupted with Control-C.

Note that the problem (delay) does not seem to occur with a compiled version of the program, just with go run.

**Comment by ianlancetaylor** [comment]
CC @alexbrainman

**Comment by alexbrainman** [comment]
I tried reproducing your problem and I cannot:
```
c:\Users\Alex\dev\src\issue\go\22055>go version
go version go1.9 windows/amd64

c:\Users\Alex\dev\src\issue\go\22055>go run hello.go
Hello, playground

c:\Users\Alex\dev\src\issue\go\22055>
```

I have no bright ideas about why this is happening to you. Maybe get Process Explorer https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer and see which process is hanging. Maybe once you know the culprit , you could debug it with delve or gdb.

Alex

**Comment by cznic** [comment]
@dargopolis Please verify if AV SW is running and if so, if there's a difference when it's turned off.

**Comment by rsc** [comment]
Timed out waiting for information.
