### ISSUE TITLE
x/exp/io/i2c: expose Tx in *Device

### ISSUE THREAD

**Issue by kortschak** [golang/go#22058]
For [at least one device](https://www.dexterindustries.com/manual/dgps-2/), it would make sense to expose the underlying `Tx` method. This device writes 3 or 4 bytes to prepare for reads. This can be done with the i2c API as is stands with a pair of `Write` and `Read` `*Device` method calls, but since the underlying `Tx` method of the `driver.Conn` exists, it would be nice to be able to use that instead.

Would this be possible?

/cc @rakyll

**Comment by rakyll** [comment]
We are not maintaining these packages anymore. @maruel was able to take it further and published  https://periph.io/ instead. Please take a look at periph.io.

**Comment by kortschak** [comment]
Thanks.
