### ISSUE TITLE
gccgo: ICE on invalid pointer embedding

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22050]
I get `go1: internal compiler error: in bind_field_or_method, at go/gofrontend/types.cc:11876` compiling this (invalid) source file with gccgo:

    package p

    type s *struct{ C int }
    type t struct{ *s }

    func f(p *t) int {
            return p.C
    }

It should produce an error that embedding `s` into `t` is invalid because `s` is a pointer type.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
CC @thanm @cherrymui

**Comment by thanm** [comment]
I'll take a look tomorrow morning...

**Comment by thanm** [comment]
Tentative fix mailed. Error messages are as usual slightly different from the main Go compiler:

./bug22050.go:7:10: error: type has no field ‘C’
  return p.C
          ^
./bug22050.go:4:16: error: embedded type may not be a pointer
 type t struct{ *s }
                ^
