### ISSUE TITLE
fmt package does not correctly differentiate between an empty array and a nil array in a struct

### ISSUE THREAD

**Issue by MarkSRobinson** [golang/go#22054]
### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/msr/Uber/sync/msr0.dev.uber.com/home/uber/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4d/40b0g4416ldcsv2qdblghx800000gn/T/go-build267712829=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

https://play.golang.org/p/FdkZS14ROX

### What did you expect to see?

```
{(nil)} isNil: true 
{[]} isNil: false 
```

### What did you see instead?

```
{[]} isNil: true 
{[]} isNil: false 
```

**Comment by mvdan** [comment]
This has nothing to do with the `fmt` package - you are passing it a `bool`.

An array is nil if and only if it is actually uninitialised and nil. A slice with zero elements but an initialised backing array will be non-nil. Please read the https://blog.golang.org/go-slices-usage-and-internals and the spec.

**Comment by go101** [comment]
@MarkSRobinson this is a known problem for history reasons (said by Rob Pike).
The output string of nil slice and blank slice are the same, both are `[]`.

```golang
package main

import (
	"fmt"
)

type s  struct {
	str []string
}

func main() {
	a := s{}
	b := s{str:[]string{}}

	fmt.Println(a)
	fmt.Println(b)
}
```
