### ISSUE TITLE
x/gddo: "Uses" link is broken on some packages

### ISSUE THREAD

**Issue by dsnet** [golang/go#22067]
Go to the page for [`reflect.Copy`](https://godoc.org/reflect#Copy). Hover the mouse to the right of the "func Copy" heading and click the "Uses" link. This link brings me to an error 404 page. The target it tries to hit is: https://sourcegraph.com/go/reflect/-/Copy, which reports the 404.

Interestingly, it works on the ['`bytes.Compare`](https://godoc.org/bytes#Compare). For example, "func Compare" links to the target: https://sourcegraph.com/-/godoc/refs?def=Compare&pkg=bytes&repo=, which does work.

\cc @shantuo @shurcooL

**Comment by shurcooL** [comment]
@dsnet, the issue tracker for godoc.org is at https://github.com/golang/gddo/issues.

There was recently a regression of Uses link affecting standard library packages in issue https://github.com/golang/gddo/issues/511. But it was marked resolved.

I'll reopen that issue, close this and reference it there.
