### ISSUE TITLE
x/crypto/acme/autocert: handle RSA-only clients better

### ISSUE THREAD

**Issue by rsc** [golang/go#22066]
https://letsencrypt.org/docs/integration-guide/ says "Our recommendation is to serve a dual-cert config, offering an RSA certificate by default, and a (much smaller) ECDSA certificate to those clients that indicate support." 

Today, autocert can only use one kind of cert. I think we should fix that and make it manage both a cached ECDSA cert and a cached RSA cert, offering the RSA certificate to clients that don't support ECDSA. Otherwise you just get weird "no supported cipher suite" errors with older clients. I'm using ruby on an up-to-date Mac and it wants to do TLS 1.0 with RSA. I spent way too long debugging why it was failing, because the failures were very non-obvious. (I don't know why Ruby on my Mac wants TLS 1.0 with RSA, but surely there are other clients like mine out there. And maybe there are RSA-only TLS 1.2 clients out there too.)

I see the ForceRSA flag in the Manager, but that doesn't do what the integration guide suggests: it uses RSA always, not just when the client doesn't support ECDSA.

As a workaround, I am using two managers, with two separate clients and caches, and a custom GetCertificate that figures out which to use:

	m := autocert.Manager{
		Client:     &acme.Client{DirectoryURL: dir},
		Cache:      autocertcache.NewGoogleCloudStorageCache(client, "mycert"),
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist("my.host"),
	}
	mRSA := autocert.Manager{
		Client:     &acme.Client{DirectoryURL: dir},
		Cache:      autocertcache.NewGoogleCloudStorageCache(client, "mycert-rsa"),
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist("my.host"),
		ForceRSA:   true,
	}
	s := &http.Server{
		Addr:    ":https",
		Handler: handler,
		TLSConfig: &tls.Config{
			MinVersion:     tls.VersionSSL30,
			GetCertificate: fallbackSNI(mRSA.GetCertificate, m.GetCertificate, "my.host"),
		},
	}

	func fallbackSNI(getCertRSA, getCert func(*tls.ClientHelloInfo) (*tls.Certificate, error), host string) func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
		return func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
			saveHello(hello)
			if hello.ServerName == "" {
				h := *hello
				hello = &h
				hello.ServerName = host
			}
			var cert *tls.Certificate
			var err error
			if len(hello.SupportedVersions) > 0 && hello.SupportedVersions[0] >= tls.VersionTLS12 {
				cert, err = getCert(hello)
				if strings.HasSuffix(hello.ServerName, ".acme.invalid") && err != nil {
					cert, err = getCertRSA(hello)
				}
			} else {
				cert, err = getCertRSA(hello)
			}
			if err != nil {
				fmt.Fprintf(os.Stderr, "getCert: %v\n", err)
			}
			return cert, err
		}
	}

This code also includes a workaround for #18785, and the RSA decision is wrong (it should look at the supported ciphers etc) but was good enough for my purposes.

/cc @x1ddos @bradfitz

**Comment by x1ddos** [comment]
Hey Russ, why not just use `hello.ServerName != ""` to check whether the client supports SNI? This is what https://godoc.org/crypto/tls#ClientHelloInfo docs say:

> // ServerName indicates the name of the server requested by the client
> // in order to support virtual hosting. ServerName is only set if the
> // client is using SNI (see
> // http://tools.ietf.org/html/rfc4366#section-3.1).

But agree either way, autocert should handle RSA-only clients.

**Comment by rsc** [comment]
@x1ddos, maybe the code is just unclear with everything else going on, but that's the test I do use for SNI (the five lines starting at `if hello.ServerName == "" {`). I just jammed the RSA patch into it too because I already had a custom GetCertificate.

**Comment by bradfitz** [comment]
Some other discussion is in #23698.

**Comment by FiloSottile** [comment]
Obtaining two certificates off the bat sounds like a waste of quota, but how about we issue a RSA certificate automatically if a TLS handshake from a client that doesn't support ECDSA comes?

**Comment by bradfitz** [comment]
@FiloSottile, SGTM. But I also don't think 2 cert requests every 2-3 months per domain name is too bad either.

**Comment by x1ddos** [comment]
@niemeyer FYI because you've posted https://github.com/golang/go/issues/17744.

**Comment by primalmotion** [comment]
this commit broke our builds

`vendor/golang.org/x/crypto/acme/autocert/autocert.go:277:9: undefined: tls.ECDSAWithSHA1`

**Comment by FiloSottile** [comment]
Wow, that was fast.

And sorry, that symbol was added in Go 1.10. I'll fix it ASAP, in the meantime you can workaround by updating to 1.10 if that's possible for you.

**Comment by primalmotion** [comment]
Oh I see it's only for go 1.9. we haven't migrated our pipelines yet which explains why it works on my laptop :)

**Comment by FiloSottile** [comment]
Should be fixed now. @primalmotion can you confirm?

**Comment by primalmotion** [comment]
yep it works now, thanks, that was fast too ;)
