### ISSUE TITLE
compiler flagging negative index access despite it being const and protected by an 'if index >= 0'

### ISSUE THREAD

**Issue by nsd20463** [golang/go#22071]
go version 1.9 on linux amd64. Also happens on today's master branch[1], and in 1.8.3.

Code like

const C = -1
if C >=0 {
  ... slice[C] ...
}

doesn't compile. The compile errors with

    invalid slice index C (index must be non-negative)

The compile-time bounds check is triggering even though it should have realized the slice access was unreachable.

A full example is at

  https://play.golang.org/p/vB4LZEm9bf

I would expect the code to compile.

[1] 70bcd2c54e8f26ee67372dffa56a86ae9701e843

**Comment by mdempsky** [comment]
https://golang.org/ref/spec#Index_expressions:

> For `a` of array type A:
> * a constant index must be in range

-1 is a constant, but is not in range. This is working as intended.

For better or worse, there's no allowance in the Go spec for ignoring statically unreachable code.
