### ISSUE TITLE
reflect: inconsistent method indexing between Type.Method and Value.Method

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22073]
From @ianlancetaylor's example in #22053, this program prints "string int" but should print "string string": https://play.golang.org/p/Kw_V41dmX2

Possibly relatedly, this program segfaults when `int` is replaced by a local named type: https://play.golang.org/p/k45kuWP75S

/cc @crawshaw

**Comment by mdempsky** [comment]
Hm, this issue doesn't reproduce at master.

**Comment by mdempsky** [comment]
It looks like the issue is Type.Method uses (*rtype).exportedMethods, which sorts the methods so all of the exported ones come first. However, Value.Method just directly indexes into t.uncommonType().methods().

It seems unfortunate that package reflect needs to sort methods like this anyway. I would think the compiler could just statically order exported methods before unexported ones.

**Comment by crawshaw** [comment]
I believe we need the unexported method data for itabs in the runtime. But you're right that it could be statically partitioned.

**Comment by mdempsky** [comment]
@crawshaw Yeah, runtime itab construction and reflect.Implements both need non-exported methods.
