### ISSUE TITLE
go/types: "const _ string = 1" error message says integers can't be converted to strings

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22070]
Compiling this package with cmd/compile (or go/types) produces an error message that 1 cannot be "converted" to type string. In fact it can be converted, it just can't be assigned, which is the criteria required here by the language spec.

    package p
    const _ string = 1

/cc @griesemer

**Comment by go101** [comment]
The accurate message should be `cannot implicitly convert 1 to type string`.

There are many error messages are not very accurate.
```golang
type T *int
type S struct {
	T // error: embedded type cannot be a pointer
}
```
The accurate message should be `embedded type cannot be a defined pointer`

**Comment by mdempsky** [comment]
I think the correct wording is `cannot assign 1 to type string`. The only time the spec talks about "implicit conversions" is in the context of default type for untyped constants, which does not apply here.

The embedded type error message reads fine to me as is. `T` is still a pointer type.

**Comment by go101** [comment]
Yes, `T` is a pointer, that is why the message is not accurate.
In fact, embedded type can be a pointer.
It is just that embedded type cannot be a defined pointer.

```golang
type T *int
type S struct {
	T // error: embedded type cannot be a pointer
}
type S struct {
	*int // ok. 
}
```

**Comment by griesemer** [comment]
The error message is inaccurate, but we do get an error message. Not urgent.

**Comment by cuonglm** [comment]
With current [tip](https://github.com/golang/go/commit/5f3354d1bf2e6a61e4b9e1e31ee04b99dfe7de35), the error message:

```
$ go tool compile p.go
p.go:3:7: cannot use 1 (type untyped int) as type string
```

Should we close this @griesemer @mdempsky ?

**Comment by griesemer** [comment]
@cuonglm Thanks for noticing this. The compiler does the right think now. `go/types` still reports "cannot convert 1 (untyped int constant) to string". I will retitle the issue.

**Comment by findleyr** [comment]
The error message is now "cannot use 1 (untyped int constant) as string value in constant declaration", so I think this can be closed.
