### ISSUE TITLE
cmd/compile: generated DWARF inlining info

### ISSUE THREAD

**Issue by thanm** [golang/go#22080]
Tracking issue for adding DWARF inline info support to the compiler.
This issue is a placeholder -- a link to the design document will follow in the next day or two.

See also related:
[mid-stack inlining tracking issue #19348](https://golang.org/issue/19348)
[mid-stack inlining proposal](https://github.com/golang/proposal/blob/master/design/19348-midstack-inlining.md)

**Comment by thanm** [comment]
Update: it turns out that DW_AT_call_file and DW_AT_call_line attributes in the DW_TAG_inlined_subroutine DIE are more or less required by GDB (without them, it ignores the inlined call records). I am updating the proposal to reflect this requirement.

**Comment by ianlancetaylor** [comment]
Is there anything left to do here?

**Comment by thanm** [comment]
No, probably best to close this out.  I have a few ideas on how to improve testing, but those can be addressed separately.
