### ISSUE TITLE
x/crypto/scrypt: update recommended parameters

### ISSUE THREAD

**Issue by kevinburke** [golang/go#22082]
The documentation for the Go scrypt library states: 

> The recommended parameters for interactive logins as of 2009 are N=16384, r=8, p=1. They should be increased as memory latency and CPU parallelism increases. Remember to get a good random salt.

It is now 2017, so it may be good to update the documented parameters as CPU's have gotten more powerful.

https://godoc.org/golang.org/x/crypto/scrypt

**Comment by kevinburke** [comment]
cc @agl, @filosottile. I tried searching around the various scrypt websites and RFC's and didn't see any updated values for N, though the RFC mentions r=8 and p=1 are still acceptable.

**Comment by kevinburke** [comment]
@agl's `pond` library uses these values in `panda/panda.go`:

```go
scrypt.Key(serialised, nil, 1<<17, 16, 4, 32*3)
```

**Comment by agl** [comment]
Pond is extreme here, but things have changed since 2009. Anyone want to ask Colin Percival?

**Comment by kevinburke** [comment]
Sure, I'll send him an email.

**Comment by kevinburke** [comment]
> Hi Kevin,
> The RFC is correct.  For an updated value of N, check what you can run within
100 ms; I suspect that 32768 will be the right value now.  CPUs speeds haven't
increased very much in the past decade...
