### ISSUE TITLE
Performance issue for remove duplicate

### ISSUE THREAD

**Issue by ralic** [golang/go#22096]
### What version of Go are you using (`go version`)?
1.7
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
leetcode runtime 

### What did you do?
Most of time when I work on leetcode problems, go runs faster than Java .
However on the problem 26, Remove Duplicates from Sorted Array. The golang takes ~102ms compared to Java ~12ms. 10 times slower, when I am using almost the same logic.
Here attached the accepted solutions in the question. 

Question : 
https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/

Solution :
``` golang
func removeDuplicates(nums []int) int {
    lens := len(nums)
    if lens==0 {return 0}
    
    j := 0
	for i := 1; i < lens; i++ {
        if (nums[i]>nums[j]) {
            j=j+1;
            nums[j]=nums[i]
        }
	}
    return j+1;
}
```

``` Java
class Solution {
    public int removeDuplicates(int[] nums) {
        if(nums.length==0)
            return 0;
        int j=0;
        for(int i=0;i<nums.length;i++){
            if(nums[i]>nums[j])
                nums[++j]=nums[i];
        }
        return j+1;
    }
}
```

### What did you expect to see?
I hope to understand and highlight this to see if there is a possibility to find some improvement.

### What did you see instead?
There is a huge difference in the runtime in go compared to Java.

[Image](https://drive.google.com/file/d/0B2PC2QjV54CcQ2xvcmRqbWtuTVU/preview)

**Comment by davecheney** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
