### ISSUE TITLE
cmd/link: code cleanup

### ISSUE THREAD

**Issue by crawshaw** [golang/go#22095]
General tracking bug for `cmd/link` code cleanup.

This code base was converted from C it shows. Several contributors have made attempts at improving various parts of it, though there is more to be done.

In particular, there are a lot of global variables and a lack of documentation. In discussion on previous cleanup CLs the general agreement is that the global variables should become parameters passed to the parts of the linker that need them. To facilitate this, a lot of variables have been dumped into the `*ld.Link` structure, and it has been plumbed everywhere as `ctxt`. Over time, it should be decomposed into just the parameters the particular component needs.

There is also some duplication that needs dealing with (some of which is my fault). For example, there is a global variable `SysArch` which is the same as `ctxt.Arch`. I believe we should switch to using a passed version of the architecture structure where possible, and remove `SysArch`.

**Comment by crawshaw** [comment]
cc @ianlancetaylor

**Comment by crawshaw** [comment]
It would be nice to replace the concept of `Library` with `Package` if possible.

**Comment by ianlancetaylor** [comment]
I am going  to declare the code clean for now.
