### ISSUE TITLE
go1.7 gc-related runtime panic, "workbuf is empty"

### ISSUE THREAD

**Issue by bohdantrotsenko** [golang/go#22105]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.7 (judging from the panic's stackstrace)

### Does this issue reproduce with the latest release?
unknown

### What operating system and processor architecture are you using (`go env`)?

    $ uname -a
    Linux server26 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz GenuineIntel GNU/Linux
    (32 cores, 256GiB ram)

   the server didn't have go installed

### What did you do?

The issue has been observed on a running CoreOS 1409.6.0 instance, in containerd, version 0.2.4 commit: v0.2.5

    $ sha256sum containerd 
    c3061b5dd3f320ff8e1a3b62217b5ad01ba2f9c8db8a28ff359c6dfbc9280863  containerd

### What did you see instead?

sanitized logs of `journalctl -xu containerd`

    containerd[4145]: fatal error: workbuf is empty
    containerd[4145]: fatal error: workbuf is empty
    containerd[4145]: fatal error: workbuf is empty
    containerd[4145]: goroutine 130 [running]:
    containerd[4145]: runtime.throw(0x8853e3, 0x10)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/panic.go:566 +0x95 fp=0xc4202716a0 sp=0xc420271680
    containerd[4145]: runtime.(*workbuf).checknonempty(0x7fa713f99240)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgcwork.go:295 +0x4e fp=0xc4202716c0 sp=0xc4202716a0
    containerd[4145]: runtime.trygetfull(0xc420f00000)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgcwork.go:351 +0x45 fp=0xc4202716e8 sp=0xc4202716c0
    containerd[4145]: runtime.(*gcWork).tryGet(0xc42001d228, 0xc42001d228)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgcwork.go:153 +0x8f fp=0xc420271710 sp=0xc4202716e8
    containerd[4145]: runtime.gcDrain(0xc42001d228, 0x5)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgcmark.go:992 +0x2da fp=0xc420271748 sp=0xc420271710
    containerd[4145]: runtime.gcBgMarkWorker(0xc42001c000)
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgc.go:1460 +0x1d1 fp=0xc4202717b8 sp=0xc420271748
    containerd[4145]: runtime.goexit()
    containerd[4145]:         /usr/lib/go1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4202717c0 sp=0xc4202717b8
    containerd[4145]: created by runtime.gcBgMarkStartWorkers
    containerd[4145]:         /usr/lib/go1.7/src/runtime/mgc.go:1349 +0x98

I cannot do further investigation on that instance, but I may do additional pointed out step when the issue re-occurs.

**Comment by mvdan** [comment]
/cc @aclements 

I believe that, with 1.9 already out, 1.7 doesn't even have security updates support, though. See https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance

**Comment by aclements** [comment]
gHi @bohdantrotsenko. Thanks for the report, but Go 1.7 is no longer maintained. Are you able to reproduce this with a newer version of Go?

**Comment by bohdantrotsenko** [comment]
sadly, not yet. (namely, within a day)
although the significance of the issue, apparently, will change that.
