### ISSUE TITLE
x/mobile: Gomobile does not support ARMv5 builds for Android

### ISSUE THREAD

**Issue by Nutomic** [golang/go#22108]
When building an apk with `gomobile build`, the resulting apk only contains libraries for the following architectures: arm64-v8a, armeabi-v7a, x86, x86_64. I also tried the following commands:
```
gomobile build -o basic.apk -target=android/arm golang.org/x/mobile/example/basic
GOARCH=arm GOARM=5 gomobile build -target android -o basic.apk golang.org/x/mobile/example/basic
gomobile build -o o.apk -target=android/armeabi golang.org/x/mobile/example/basic
```
None of them resulted in an armeabi library, always armeabi-v7a. The same problem exists with the gomobile gradle plugin.

### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64
gomobile version +e095d65 Sun Sep 10 23:20:06 2017
gradle plugin: "gradle.plugin.org.golang.mobile.bind2:gobindPlugin:0.2.5"

[Original forum thread](https://forum.golangbridge.org/t/how-to-build-for-armv5-with-gomobile/6764)

**Comment by karalabe** [comment]
As far as I know, the minimum Android version gomobile supports is 4.0 (API 15), which requires ARMv7 already.

**Comment by Nutomic** [comment]
Is there a source for this? I found [this stackoverflow answer](https://android.stackexchange.com/a/34959), but it's not clear if the ARMv7 requirement starts at Android 4.0 or 4.4. 

Besides, these are the official specs, as mentioned in the answer, it would be possible to modify newer Android versions to run on ARMv5 (eg custom roms or hardware released without Google Play).

**Comment by davecheney** [comment]
Gomobile requires ARMv7. It may be possible that there exist android devices that are not ARMv7 compatible, but gomobile does not support them.
