### ISSUE TITLE
runtime: TestMemStats failure on Windows

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#22119]
Reporting a failure of `runtime.TestMemStats` on Windows while running a trybot.

https://storage.googleapis.com/go-build-log/88e9e458/windows-386-2008_768d5260.log

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
--- FAIL: TestMemStats (0.00s)
	malloc_test.go:75: GCCPUFraction = 1.199228591244373: insanely high value (overflow?); want <= 0.99
FAIL
FAIL	runtime	65.206s
2017/10/03 14:11:44 Failed: exit status 1
2017/10/03 14:11:44 FAILED
```

**Comment by aclements** [comment]
Another trybot failure: https://storage.googleapis.com/go-build-log/6e24f25f/windows-386-2008_5cdc0365.log

**Comment by ianlancetaylor** [comment]
Likely dup of #22696.  Closing optimistically.
