### ISSUE TITLE
x/net/internal/socket: (*ipv4.PacketConn).ReadFrom() returns nil source on go1.9 (android-arm64)

### ISSUE THREAD

**Issue by tmm1** [golang/go#22115]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
LD=aach64-linux-android-ld CC=aarch64-linux-android-gcc GOOS=android GOARCH=arm64

### What did you do?

I'm using this test program that prints out whenever mDNS broadcast packets are seen on the network:

```golang
package main

import (
	"log"
	"net"

	"golang.org/x/net/ipv4"
)

func main() {
	mdnsGroupIPv4 := net.IPv4(224, 0, 0, 251)
	mdnsWildcardAddrIPv4 := &net.UDPAddr{
		IP:   net.ParseIP("224.0.0.0"),
		Port: 5353,
	}

	udpConn, err := net.ListenUDP("udp4", mdnsWildcardAddrIPv4)
	if err != nil {
		log.Fatal(err)
	}

	pkConn := ipv4.NewPacketConn(udpConn)
	pkConn.SetControlMessage(ipv4.FlagInterface, true)

	ifaces, err := net.Interfaces()
	if err != nil {
		log.Fatal(err)
	}
	for _, iface := range ifaces {
		pkConn.JoinGroup(&iface, &net.UDPAddr{IP: mdnsGroupIPv4})
	}

	buf := make([]byte, 65536)
	for {
		n, _, from, err := pkConn.ReadFrom(buf)
		if err != nil {
			log.Fatal(err)
		}

		log.Printf("got %v bytes from %+v", n, from)
	}
}
```

### What did you expect to see?
This program works as expected on most platforms (linux, darwin, freebsd, windows, android) on golang 1.8.

Since upgrading to golang 1.9 (and upgrading x/net to master), it no longer works as expected on android/arm64.

### What did you see instead?

On golang 1.9 w/ golang/net@3470a06c1357df533e251f14d3a181f67396fe35:

```
2017/10/03 00:07:45 got 66 bytes from 10.0.1.136:5353
2017/10/03 00:07:46 got 66 bytes from 10.0.1.136:5353
```

On golang 1.9 w/ golang/net@b7a1f62a479cdecf85ac8652743f25dfc8dd493b:

```
2017/10/03 00:08:15 got 66 bytes from :5353
2017/10/03 00:08:16 got 66 bytes from :5353
```

For some reason, the source IP is no longer populated:

```
&net.UDPAddr{IP:net.IP(nil), Port:5353, Zone:""}
```

The same issue is present with `*ipv4.PacketConn` after golang/net@48359f4f600b3a2d5cf657458e3f940021631a56

cc @mikioh

**Comment by mikioh** [comment]
I'm not sure what's going on.
- Can you please try both go1.8- and go1.9-based executable on the same node; android (which version?) linux/arm64.
- When you try, please dump the address with default format like the following: s/log.Printf("got %v bytes from %+v", n, from)/log.Printf("got %v bytes from %#v", n, from)/

**Comment by tmm1** [comment]
I ran my tests on the same node, with golang 1.9 but two different revisions of x/net. Would you like me to try golang 1.8 as well? With which revision of x/net?

I'm seeing this behavior on an NVidia SHIELD android TV, running a variant of Android 7.1.1

>Linux localhost 3.10.96+ #1 SMP PREEMPT Fri Sep 22 18:32:54 PDT 2017 aarch64

**Comment by tmm1** [comment]
I tried `%#v` earlier and it outputs `&net.UDPAddr{IP:net.IP(nil), Port:5353, Zone:""}`

**Comment by mikioh** [comment]
> Would you like me to try golang 1.8 as well?  With which revision of x/net?

Yes, thanks. The same revision is fine because packages in x/net switch the codepath at run time.

> I tried %#v ...

Oh, I missed that, thanks. Then, there's probably something wrong on ```parseInetAddr``` in internal/socket/sys_posix.go. I'm not an Android user and have no Android stuff. Do you have a spare time for diving into the thing a bit? If you have a time, can you please dump and report back the raw socket address in parseInetAddr? Thanks.

**Comment by tmm1** [comment]
@mikioh Thanks for the pointer. `parseInetAddr()` has a `runtime.GOOS` switch statement. If I add `"android"` to the list, it fixes my issue. Probably it should be added to the switch statements in `marshalSockaddr()` as well.

**Comment by mikioh** [comment]
Good. Do you want to send a CL?

**Comment by tmm1** [comment]
I would prefer if you did it. Thanks!
