### ISSUE TITLE
len() reports incorrect length on some strings

### ISSUE THREAD

**Issue by Silvea12** [golang/go#22127]
### What version of Go are you using (`go version`)?
go version 1.9 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOOS="linux"
GOARCH="amd64"

### What did you do?
The below is MEANT to be 255 characters (at least, according to javascript) - instead, len() reports 459 chars
This did not happen in 1.8.2 (I did not check 1.8.3)
https://play.golang.org/p/2gFfz_zaUw

### What did you expect to see?
Rune count should be 255

### What did you see instead?
Rune count is 459

**Comment by dominikh** [comment]
This is working as intended. `len` returns the number of bytes in a string, not the number of runes. This has been true since at least Go 1.0 – I assert that Go 1.8.2 has the same behaviour as Go 1.9.

**Comment by randall77** [comment]
If you want to count runes in a string `s`, do:
```
	n := 0
	for _ = range s {
		n++
	}
```

**Comment by Silvea12** [comment]
@randall77 Easier to do `utf8.RuneCountInString(str)`
