### ISSUE TITLE
x/build: ask trybots to submit on pass

### ISSUE THREAD

**Issue by crawshaw** [golang/go#22123]
Right now we +1 trybots on gerrit to run the trybots.

We could have a feature where we +2 trybots and have the bots submit the CL when it passes. A human reviewer would have to have already +2ed the CL.

This is a potential alternative to #12482. It's less invasive, because instead of the reviewer triggering the submission, the author triggers it.

(We have this feature on fuchsia's gerrit and it is very useful.)

**Comment by bradfitz** [comment]
Dup of #12482 (from two years prior)
