### ISSUE TITLE
all: cherry-picks for Go 1.9.2

### ISSUE THREAD

**Issue by rsc** [golang/go#22130]
I'm about to rewind the release-branch.go1.9 to drop the cherry-picks of these original CLs:

https://go-review.googlesource.com/60510
https://go-review.googlesource.com/59710
https://go-review.googlesource.com/63270
https://go-review.googlesource.com/59530

This is to create a pristine base for the Go 1.9.1 security release. In the future we should not cherry-pick to the release branch until we are actively preparing a point release.

This issue is a note to remember to re-cherry-pick those for Go 1.9.2. The last one, https://go-review.googlesource.com/59530, is a doc change we'd like to appear on the golang.org web site, so we will restore that one immediately after the Go 1.9.1 release, but the others should wait until we're actively preparing Go 1.9.2.

**Comment by griesemer** [comment]
I assume that https://golang.org/cl/64830 (#21938) will be in 1.9.2?

**Comment by rsc** [comment]
Yes there needs to be a discussion of what goes into Go 1.9.2. The list above was not meant to be exhaustive. It was just to record things that had already been cherry-picked into the release branch that I was erasing from it, since they otherwise might be dropped.

**Comment by rsc** [comment]
The doc change is cherry-picked already for Go 1.9.1 and the others are attached to issues in the Go 1.9.2 milestone, so I don't think this bug adds any value anymore.
