### ISSUE TITLE
image/gif: decoding then encoding an animated GIF likely to increase its size

### ISSUE THREAD

**Issue by jeddenlea** [golang/go#22137]
image/gif decodes a `GIF`, which contains an `[]*image.Paletted` that holds each frame.  When decoded, if a frame has a transparent color and uses the global palette, a copy of the global `[]color.Color` is made, and the transparency color index is replaced with `color.RGBA{}`.

When encoding a `GIF`, each frame's palette is encoded to the form it might exist in a GIF, up to 768 bytes "RGBRGBRGBRGB...". If a frame's encoded palette is equal to the encoded global color table, the frame will be encoded with the flag set to use the global color table, otherwise the frame's palette will be included.

So, if the color in the global color table that matches the transparent index of one frame wasn't black (and it frequently is not), reencoding a GIF will likely result in a larger file because each frame's palette will have to be encoded inline.

A working CL will be posted shortly.

**Comment by dsnet** [comment]
\cc @nigeltao
