### ISSUE TITLE
reflect: Value.Call call on nil interface of T assignable to R

### ISSUE THREAD

**Issue by dsnet** [golang/go#22142]
I'm investing a bug report and I traced it down to the following discrepancy, and I've convinced myself that it is a bug, but would appreciate a 2nd opinion.

Consider the [following snippet](https://play.golang.org/p/5Q6va_JWYk):
```go

type Iface interface {
	Method()
}

type IfaceWrapper interface {
	Iface
}

type Struct struct {
	IfaceWrapper
}

func Func(x Iface) bool {
	return true
}

func main() {
	s := Struct{}

	v1 := s.IfaceWrapper
	fmt.Println(Func(v1))

	v2 := reflect.ValueOf(s).FieldByName("IfaceWrapper")
	fmt.Println(reflect.ValueOf(Func).Call([]reflect.Value{v2})[0])
}

```

\cc @ianlancetaylor @mdempsky

**Comment by cespare** [comment]
@dsnet did you intend to close this?

**Comment by cespare** [comment]
Hmm yes, looks like you opened #22143 instead.
