### ISSUE TITLE
reflect: Value.Call panic on nil T interface assignable to R interface

### ISSUE THREAD

**Issue by dsnet** [golang/go#22143]
I'm investing a bug report and I traced it down to the following discrepancy, and I've convinced myself that it is a bug, but would appreciate a 2nd opinion.

Consider the [following snippet](https://play.golang.org/p/bRzJ0dQ_0W):
```go
type Iface interface {
	Method()
}
type IfaceAlt interface {
	Method()
}

func Func(Iface) bool {
	return true
}

func main() {
	sa := struct{ X Iface }{}

	v1a := sa.X
	fmt.Println(Func(v1a))

	v2a := reflect.ValueOf(sa).FieldByName("X")
	fmt.Println(reflect.ValueOf(Func).Call([]reflect.Value{v2a})[0])

	sb := struct{ X IfaceAlt }{}

	v1b := sb.X
	fmt.Println(Func(v1b))

	v2b := reflect.ValueOf(sb).FieldByName("X")
	fmt.Println(reflect.ValueOf(Func).Call([]reflect.Value{v2b})[0])
}
```
We have two interfaces `Iface` and `IfaceAlt`, which are defined the exact same way.
We also have a function `Func` that takes `Iface` as an input and always reports true.
Since both interfaces are assignable to each other, we expect that you should be able to call `Func` with values of either type.

The `sa` and `sb` variables are structs where the `X` field is of type `Iface` or `IfaceAlt`. 

`v1a` and `v2a` shows that you can call `Func` directly in Go and also with reflection.
`v1b` and `v2b` shows that you can still call `Func` directly in Go, but the equivalent call with reflect panics with: `interface conversion: interface is nil, not main.Iface`

What I expected:
```
true
true
true
true
```

What I saw instead:
```
true
true
true
panic: interface conversion: interface is nil, not main.Iface
```

\cc @ianlancetaylor @mdempsky

**Comment by ianlancetaylor** [comment]
It's an interesting case.  I do think it's a bug.  The reflect package is trying to handle `Call` as it does any assignment: when assigning a value to a variable of interface type, it converts the value to an empty interface and does the assignment.  That works fine except when the value happens to itself be a nil interface.  When the value is a nil interface, converting to an empty interface produces simply the nil empty interface, and that can not be assigned to any non-empty interface.

I think we need to change `assignTo` to specially handle the case of assigning one interface type to another, much as there is a test for `src.Kind() == Interface` in `convertOp`.

**Comment by shurcooL** [comment]
Does this affect both `gc` and `gccgo` compilers (if it's easy to find out)?

**Comment by ianlancetaylor** [comment]
@shurcooL Yes, it affects both compilers.  I believe the key code here is `reflect.Value.assignTo`, which is the same for both compilers.
