### ISSUE TITLE
x/net/ipv4: NewRawConn now gives operation not supported when it worked in previous versions

### ISSUE THREAD

**Issue by kkirsche** [golang/go#22150]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.9.1 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/v832272/git/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8y/pj9zz4b12r37490xnlqb7gb13tt57z/T/go-build991994028=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
```go
logrus.WithField("function", "Send()").Debugln("Create connection.")
conn, err := net.ListenPacket("ip4:icmp", "127.0.0.1")
if err != nil {
    logrus.WithError(err).WithField("function", "Send()").Errorln("Net ListenPacket connection error")
    return err
}
defer conn.Close()
 
rawConn, err := ipv4.NewRawConn(conn)
if err != nil {
    logrus.WithError(err).Errorln("Send() Error: Raw connection creation")
    return err
}
```

If possible, provide a recipe for reproducing the error.
1.) OS CentOS Linux release 7.3.1611 (Core)
2.) With or without SELinux enforcing

Working on a small app which encapsulates this

### What did you expect to see?
No error and a new IPv4 raw connection as was supported in previous Golang builds. This only broke when recompiling an application that was last compiled 2017-07-13T11:34:03Z on the latest go version at that date.

### What did you see instead?
`ERRO[0030] Send() Error: Raw connection creation          error="operation not supported"`

on CentOS Linux release 7.3.1611 (Core) as the root user

**Comment by kkirsche** [comment]
https://github.com/kkirsche/golang_issue_22150/tree/master

This demonstrates the issue on 1.9.1 in the bin directory and not on 1.8.4 in the bin directory. Binaries for multiple distros included. Build makefile included

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by mikioh** [comment]
Go 1.9 or above requires at least the commit cabdc3af38bdc364f9b1ae4e0d8e4d51ec53f7e1 on ipv4 package. Unfortunately, the previous revision on x/net doesn't work with Go 1.9 or above. Can you please tell us which revision of x/net you are using, and what happens when you update your local snapshot of x/net?

**Comment by kkirsche** [comment]
I would guess this is the issue then. I'm in the process of updating my x/* dependencies and will update once I recompile.

**Comment by kkirsche** [comment]
This fixed it. It was due to an outdated x/net package. Sorry about this and thank you for the quick assistance.

**Comment by mikioh** [comment]
Dup of #19209.
