### ISSUE TITLE
x/build/cmd/coordinator: cannot compile with dependency tip

### ISSUE THREAD

**Issue by kevinburke** [golang/go#22153]
I think it's a good practice for x/build to be able to be built with tip of each dependency it uses. Currently that fails with this stack trace:

```
Fetching https://cloud.google.com/go/errors?go-get=1
Parsing meta tags from https://cloud.google.com/go/errors?go-get=1 (status code 200)
get "cloud.google.com/go/errors": found meta tag main.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at https://cloud.google.com/go/errors?go-get=1
get "cloud.google.com/go/errors": verifying non-authoritative meta tag
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
cloud.google.com/go (download)
package cloud.google.com/go/errors: cannot find package "cloud.google.com/go/errors" in any of:
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/cloud.google.com/go/errors (from $GOROOT)
	/home/travis/gopath/src/cloud.google.com/go/errors (from $GOPATH)
```

cmd/coordinator/gce.go attempts to load cloud.google.com/go/errors, which fails. I'll see if I can fix when I have time. https://travis-ci.org/kevinburke/build/jobs/283833651

(If you work at Google, it would be great if you could also have a word with the GCP team about not removing public API's).

**Comment by andybons** [comment]
> (If you work at Google, it would be great if you could also have a word with the GCP team about not removing public API's).

From looking at the previous API docs, it was very clear that they were experimental and subject to change. 🤷‍♂️
