### ISSUE TITLE
cmd/go: security fix broke bzr-inside-bzr repos

### ISSUE THREAD

**Issue by rsc** [golang/go#22157]
@arthursapek in https://github.com/golang/go/issues/22125#issuecomment-334556431 reports:

> This change seems to break `go get` on a nested `bzr` package called `labix.org/v2/mgo`.
> 
> Given command `go get labix.org/v2/mgo/bson`, we get this output:
> 
> ```
> package labix.org/v2/mgo/bson: directory "/home/emile/go/src/labix.org/v2/mgo" uses bzr, but parent "/home/emile/go/src/labix.org/v2" uses bzr
> ```
> 
> Same goes for this mirror: `go get gopkg.in/mgo.v2/bson`
> 
> Was the intent here to disable all nested VCS except for git?

Indeed it was, because we are confident about git protecting well enough against git-in-git. I am honestly not as confident in bzr, which seems to have far less attention paid to it. Anything we enable here ends up in the trusted computing base for cmd/go (that is, it allows attacks on cmd/go users), so I'm really pretty reluctant to add this back.

But creating the issue anyway.

**Comment by shurcooL** [comment]
> but parent "/home/emile/go/src/labix.org/v2" uses bzr

Is there really a Bazaar repository at the path corresponding to import path `labix.org/v2`?

Have you verified that the "go-import" tag is correctly served for that package?

When I do `curl -i 'https://labix.org/v2?go-get=1'`, I get 404.

**Comment by rsc** [comment]
OK for Go 1.9.2

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 69670](https://golang.org/cl/69670) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:21 UTC
