### ISSUE TITLE
net/http Client.Do() hangs when StdOut/StdErr redirected

### ISSUE THREAD

**Issue by ArcticSnowman** [golang/go#22165]
- Go Version 1.9.1
- Latest 
- OS: linux/amd64

Using https://github.com/VividCortex/godaemon in an application for daemon support disconnects the StdOut and StdErr.     The application uses https://github.com/bndr/gojenkins , which makes a http request using net/http Client.Do()...    Which hangs and never returns

If the stdout/stderr are captured and stored in a file then the Client.Do() works

**Comment by kevinburke** [comment]
@ArcticSnowman, it would help if there you could produce a reduced test case demonstrating what you expect to happen, and what actually happens. My guess is that `Do()` is hanging because it's trying to read from the io.Reader for the http request body, and that `Read()` call is blocking.

**Comment by dolftax** [comment]
@kevinburke If added a timeout like below, would `Do()` throw error and move on instead of hanging?

```
httpClient := &http.Client{
		Timeout: time.Second * 10,
}
```
