### ISSUE TITLE
net/mail: ParseAddress may be incorrectly flagging valid values as errors

### ISSUE THREAD

**Issue by kevinburke** [golang/go#22161]
I expect that `mail.ParseAddress("kev@inburke.com <kev@inburke.com>")` will parse to 

```go
&mail.Address{
    Name: "kev@inburke.com",
    Address: "kev@inburke.com",
}
```

It's weird, granted, but I am guessing that the RFC for email parsing allows email-like things to be present in the Name field?

Noticed when using maintner to parse Gerrit emails. I also found this one:

```
Author: Author: Kevin Burke <kev@inburke.com>
```

(actual person's name withheld) which choked on the second Author: call. 

It seems like it would be good to have a tool to validate the commit name/email before merge.

**Comment by ianlancetaylor** [comment]
According to RFC 5322, given a string like "kev@inburke.com <kev@inburke.com>", the first "kev@inburke.com" can only be parsed as a display-name.  An unquoted display-name can only contain what RFC 5322 calls "atoms", which can be alphanumeric characters or various special characters, but the list of special characters does not include '@'.  So I think that is not a valid address specification, and `mail.ParseAddress` is correct to reject it.

Similarly ':' is not permitted so I think your second string is also correctly rejected.

**Comment by kevinburke** [comment]
Gah, ignore me.
