### ISSUE TITLE
cmd/compile: incorrect syntax error cascade

### ISSUE THREAD

**Issue by rsc** [golang/go#22164]
Here's a bad program, boiled down from a larger case:

```
package p

func f() {
	x := f(g()
	y := 1
}

func g() {
}

func h() {
	x := f(g()
}
```

I forgot the closing paren on the first line of f's function body, and just for illustration I did it again in h.

The current compiler diagnoses those two problems but also gets confused by the beginning of g:

```
$ go tool compile /tmp/x.go
/tmp/x.go:4:12: syntax error: unexpected newline, expecting comma or )
/tmp/x.go:8:10: syntax error: unexpected { at end of statement
/tmp/x.go:12:12: syntax error: unexpected newline, expecting comma or )
```

In my bigger program there were more lines like the error at x.go:8. I'm not sure exactly why I had more but this example has only one, but one should be enough to illustrate. When I got this output I fixed the problem at (the equivalent of) line 4 and then moved on to line 8 and was a bit confused about where the syntax error was. It took me a moment to realize that there wasn't a syntax error on line 8 and that the parser was still confused about line 4. (But the error report at 12 is real, so it's not like it got totally lost.)

The old yacc parser correctly identified 4 and 12 without getting confused by 8:

```
$ go1.4 tool 6g /tmp/x.go
/tmp/x.go:4: syntax error: unexpected semicolon or newline, expecting )
/tmp/x.go:12: syntax error: unexpected semicolon or newline, expecting )
```

I think that the old yacc parser was getting back on its feet either because it assumed the newline started a new statement or because it assumed the closing braces matched so that f's closing brace reset things. I'm not sure of the exact confusion the new parser is in - at first I thought the error was what you'd get if 'func g() { }' appeared inside a function body, but that doesn't seem to be the case.

In passing, I will note:

```
$ gofmt /tmp/x.go
/tmp/x.go:4:12: missing ',' before newline in argument list
/tmp/x.go:5:4: missing ',' in argument list
/tmp/x.go:6:1: expected operand, found '}'
/tmp/x.go:13:3: missing ',' in argument list
```

Gofmt emits three errors inside f, doesn't get confused by g, and then reports the wrong line for the mistake in h. Overall the compiler is doing much better - one line in f, one line in g, one line (and the right one) in h - so thanks for those improvements there. It would just be even better for the compiler not to report g.

/cc @griesemer @mdempsky

**Comment by griesemer** [comment]
gofmt uses `go/parser` while the compiler uses the significantly improved parser in `cmd/compile/internal/syntax`. That explains the difference between gofmt and the compiler.

I'll look into better error recovery for this case.
