### ISSUE TITLE
Create Gerrit account and sign CLA using Github OAuth

### ISSUE THREAD

**Issue by ChimeraCoder** [golang/go#22160]
(continuing  an IRL discussion with @andybons)

It's clear that at least some would-be contributors to Go are interested in contributing to Go, but find creating a Gerrit account to be a barrier. Many of those do have Github accounts, though, and might find the onboarding process smoother if we could streamline it as an OAuth login flow.

Gitlab supports logging in with Github, and I'm imagining something similar for Gerrit. As an example flow, using `go-contrib-init`

1. Run `go-contrib-init create -github` (or whatever syntax we want)
2. Web browser automatically opens with a Github OAuth login screen
3. After allowing access, the user is presented with the CLA
4. User is then directed back to the CLI, which saves these new OAuth credentials in `~/.my_go_gerrit_github_credentials_place`
5. User now has a Gerrit account, despite never having had to interact with Gerrit directly at all. 

cc @jessfraz who I think wrote the original `go-contrib-init`

**Comment by jessfraz** [comment]
Ah I didn't make that Steve and Brad did

**Comment by andybons** [comment]
Will follow up with Gerrit team and post an update on feasibility.

**Comment by bradfitz** [comment]
@andybons, any update?

**Comment by andybons** [comment]
There are no immediate or mid-term plans for the team that manages go-review.googlesource.com to support GitHub logins.

#18517 will help a great deal with the underlying problem, though.

I think this specific issue isn’t feasible given the constraints internally. Sorry :-/
