### ISSUE TITLE
misc/cgo/testcshared: TestExportedSymbols is flaky

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#22176]
Failed during a trybot run:

##### ../misc/cgo/testcshared
--- FAIL: TestExportedSymbols (4.79s)
	cshared_test.go:287: command failed: [gcc -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072369167=/tmp/go-build -gno-record-gcc-switches -I pkg/linux_amd64_shared -o testp1 main1.c -ldl main0.c libgo.so]
		exit status 1
		main0.c:8:15: fatal error: p.h: No such file or directory
		 #include "p.h"
		               ^
		compilation terminated.
		
FAIL
2017/10/08 15:01:35 Failed: exit status 1

https://storage.googleapis.com/go-build-log/acef5720/linux-amd64_e3b29252.log

**Comment by alexbrainman** [comment]
Perhaps related. From our linux-amd64-ssacheck builder at 35483c8e2540a4ba731ded6b9f19b2f5244fe4fa

https://build.golang.org/log/9d0b05f7c9d6b2f2983de10c970b307cff2abe6e

```
##### ../misc/cgo/testcshared
--- FAIL: TestExportedSymbolsWithDynamicLoad (2.89s)
	cshared_test.go:312: command failed: [gcc -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build465521071=/tmp/go-build -gno-record-gcc-switches -I pkg/linux_amd64_shared -I pkg/linux_amd64_testcshared_shared -o testp0]
		exit status 4
		gcc: fatal error: no input files
		compilation terminated.
		
FAIL
```

Strange thing about this error message that it refers to "testp0" file, while cshared_test.go:312 at 35483c8e2540a4ba731ded6b9f19b2f5244fe4fa refers to TestExportedSymbolsWithDynamicLoad which uses "testp1" file name for its test.

Alex

**Comment by alexbrainman** [comment]
Another strange one from android-arm64-wiko-fever builder at e8a27daaef3ed931d4e8a78a7c784c7656dfbbf1

https://build.golang.org/log/9d37614500fe7682ac52d3be8aa087ac413d4d82

```
##### ../misc/cgo/testcshared
--- FAIL: TestMainExportedOnAndroid (0.20s)
	cshared_test.go:380: run: [/Users/elias/android-ndk-standalone-arm64/bin/clang -fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f6/d2bhfqss2716nxm8gkv1fmb80000gn/T/go-build190255492=/tmp/go-build -gno-record-gcc-switches -pie -fuse-ld=gold -I pkg/android_arm64 -o testp1 main1.c -ldl]
	cshared_test.go:164: adb command failed: exit status 1
		adb: error: cannot stat 'testp3': No such file or directory
		
FAIL
```

Note how TestMainExportedOnAndroid test binary is called "testp3", but the log of run command above says "-o testp1", while adb log says "cannot stat 'testp3'".

Alex

**Comment by ianlancetaylor** [comment]
@alexbrainman Thanks, looking at `runCC` shows the problem with parallel tests.  Sent CL 69230.
