### ISSUE TITLE
godoc: dev documentation is out of date

### ISSUE THREAD

**Issue by andybons** [golang/go#22186]
From following https://github.com/golang/gddo/wiki/Development-Environment-Setup, I’m unable to get a working local dev, with `dev_appserver.py $GOPATH/src/github.com/golang/gddo/gddo-server` spinning up a server, but returning a 503 when visiting http://localhost:8080/github.com/golang/gddo/gddo-server

**Comment by forskning** [comment]
Apologies in advance, `dev_appserver.py` is also mentioned on the below webpage.

http://slackbuilds.org/repository/14.2/development/google-appengine-gosdk/

**Comment by gbbr** [comment]
I hope I'm not wrong but shouldn't this issue go into the golang/gddo repo?

**Comment by andybons** [comment]
@gbbr ah you're right! Filed https://github.com/golang/gddo/issues/515
