### ISSUE TITLE
cmd/compile: ICE due to "Flag* ops should never make it to codegen"

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22198]
$ go build -gcflags=-l=4 k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto
    # k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto
    ../../../go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/text.go:344:27: internal compiler error: Flag* ops should never make it to codegen v1291 = FlagEQ <flags>

/cc @randall77

**Comment by mdempsky** [comment]
Not surprising, but it also repros with the original `github.com/golang/protobuf/proto` repo.

**Comment by mdempsky** [comment]
The seemingly relevant SSA ops are:

    v1291 = FlagEQ <flags>
    v932 = LoadReg <*bool> v2089 : DX
    v794 = SETEQmem <mem> v932 v1291 v789

These are generated by lower from:

    v449 = Const8 <byte> [10] (c[byte], c[byte], c[byte], c[byte], c[byte], c[byte])
    v791 = Eq8 <bool> v449 v449
    v794 = Store <mem> {bool} v742 v791 v789

I'm guessing the rewrite rules just need reordering so that we instead lower into moving constant 1 to memory.

**Comment by mdempsky** [comment]
Adding a rule for

    (SETEQmem [off] {sym} ptr (FlagEQ) mem) -> (MOVBstore [off] {sym} ptr (MOVLconst [1]) mem)

seems to fix the ICE. Not sure if that's the best solution.

/cc @cherrymui

**Comment by cherrymui** [comment]
Seems a regression from CL https://go-review.googlesource.com/c/go/+/67950. Indeed the handling of constant flags is missing. Adding @mdempsky's rule looks right to me.

cc @TocarIP

**Comment by cherrymui** [comment]
> all the other SETCC/FlagCC combinations.

There are already rules (around line 1487 of AMD64.rules) that handles non-mem version of SETCC and constant flags. Seems we should add the similar ones for SETCCmem.

**Comment by mdempsky** [comment]
Here's the best I've been able to minimize the test case so far:

    package p
    
    type T struct {
            a bool
            b bool
    }
    
    func f(p *T) {
            if p.b {
                    return
            }
            c := '\n'
            if p.b {
                    c = ' '
            }
            if !p.b && p.a {
                    p.a = false
            }
            p.a = c == '\n'
    }

**Comment by mdempsky** [comment]
Also, the repro happens even without -l=4. It just happens to have been discovered in the protobuf code using -l=4.
