### ISSUE TITLE
cmd/compile: inlining budget excludes cross-package calls

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22194]
In the example below, `p.G` and `q.H` are identical, except that `p.G` is in the same package as `p.F`, yet cmd/compile decides that `q.H` is inlineable whereas `p.G` is not.

This is because cmd/compile currently only computes `Inlcost` for locally defined functions. Calls to functions in external packages are effectively treated as free.

    $ go tool compile -m p.go
    p.go:3:6: can inline F
    p.go:13:3: inlining call to F

    $ go tool compile -m q.go
    q.go:5:6: can inline H
    q.go:6:5: inlining call to p.F

    $ cat p.go
    package p
    
    func F() {
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    }
    
    func G() {
        F()
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    }

    $ cat q.go
    package q
    
    import "./p"
    
    func H() {
        p.F()
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    }

**Comment by ALTree** [comment]
This is #19261, see josh comment: https://github.com/golang/go/issues/19261#issuecomment-282464401

**Comment by mdempsky** [comment]
@ALTree Indeed. Closing as duplicate.
