### ISSUE TITLE
net/url: UserInfo parse fail on '#' character

### ISSUE THREAD

**Issue by rvolykh** [golang/go#22195]
There is problem with url.Parse. According to https://tools.ietf.org/html/rfc3986:
```
reserved      = gen-delims / sub-delims
gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```
UserInfo should respect '#' character: https://tools.ietf.org/html/rfc3986#section-3.2.1

### What version of Go are you using (`go version`)?
1.8.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOOS="linux"

### What did you do?
https://play.golang.org/p/QtAItGCPez

### What did you expect to see?
`username:pass#word`

### What did you see instead?
`<nil>`

**Comment by bontibon** [comment]
I don't think you are reading that correctly. The spec defines userinfo as:
>     userinfo      = *( unreserved / pct-encoded / sub-delims / ":" )

Note **un**reserved.

**Comment by rvolykh** [comment]
Thanks for your quick answer
Yes, I've really messed up here
