### ISSUE TITLE
cmd/compile: trybot flake in TestNexting

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#22206]
From https://storage.googleapis.com/go-build-log/f7554b56/linux-amd64_e54e3ae9.log :

DID NOT MATCH [Inferior 1 (process 14469) exited normally]
(gdb) DID NOT MATCH [LWP 14528 exited]
[Inferior 1 (process 14528) exited normally]
(gdb) --- FAIL: TestNexting (9.86s)
	debug_test.go:160: step/next histories differ, diff=
		--- testdata/hist-opt.gdb-nexts	2017-10-10 22:06:01.000000000 +0000
		+++ /tmp/debug_test377474953/hist-opt-test.gdb-nexts	2017-10-10 23:30:16.642615273 +0000
		@@ -1,6 +1,8 @@
		   src/cmd/compile/internal/ssa/testdata/hist.go
		 35:	func main() {
		 35:	func main() {
		+35:	func main() {
		+35:	func main() {
		 36:		hist := make([]int, 10)
		 37:		var reader io.Reader = strings.NewReader(cannedInput) //gdb-dbg=(hist/A,cannedInput/A)
		 13:		"strings"
FAIL
FAIL	cmd/compile/internal/ssa	10.015s

**Comment by ianlancetaylor** [comment]
This test is designed to be a change detector (https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html).  Any number of things could cause this test to break, including minor changes to the fmt or bytes or strconv packages.  I do not think we should be running this test as part of our automated testsuite.  There will be too many unrelated breakages.

**Comment by dr2chase** [comment]
I'd like to figure out what causes that intermittent quadruple-stop on main().  The test is designed to be a "change detector" because our current behavior for debugging code is so inadequate.  I can write down a debugging correctness test that would not flake, because it would continuously fail.

**Comment by ianlancetaylor** [comment]
I agree that it's hard to write tests for debug info.  It's especially hard to write end-to-end tests that check how an external tool interprets the debug info.

But for the Go testsuite we really can't have tests that can change due to completely unrelated code changes, or that are flaky.  You can write a test like yours while still controlling for these changes by using a program that does not call into the standard library at all.

**Comment by dr2chase** [comment]
The standard library call isn't supposed to appear in correct output (it's TestNexting, not TestStepping), and in theory we're trying to fix this in 1.10 (as part of the get-inlining-debugging-right plan).  I could disable inlining for test.short till we get this fixed, that would do the job.

**Comment by dr2chase** [comment]
The observed flake is also not the library dependence -- gdb appears to be unprepared for a really fast typist and in certain cases this causes lines to repeat.  I made the test by-default tolerant of repeats in the line stream, and by-default disable inlining (but not other optimization) for testing with gdb which will also break that dependence (that we will not see anyway once we fix inlining).

**Comment by dr2chase** [comment]
I think this can be closed, between the short-mode disabled and because of https://github.com/golang/go/commit/e45e490296a514067144210e42d74d8f318014f1 (also mentioned above).
