### ISSUE TITLE
os: Windows: reading data from stdin hangs in 1.9

### ISSUE THREAD

**Issue by mappu** [golang/go#22207]
Hi,

### What version of Go are you using (`go version`)?
go1.9.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 amd64

### What did you do?
I have a program that
- uses github.com/Microsoft/go-winio to listen on a named pipe (maybe that's relevant, i don't know)
- uses CGO, using Cygwin's distribution of mingw-w64 gcc, but not targeting Cygwin, nor running under it
- expects to read some data from stdin shortly after it launches

### What did you expect to see?
The Go program should receive data on stdin, then go about its business, as expected.
This works as expected on Go 1.8.4.

### What did you see instead?
The Go program hangs at 0% CPU usage.
From the behaviour of the program i infer it is blocked on reading from stdin.
It hangs probably 5/10 attempts when launched via a Qt application, but interestingly it hangs 0/10 attempts when launched from cmd.exe.

This issue is almost identical to #22024, but my case is a bit different, because
- I am not targeting cygwin, nor running under cygwin
- The hang is intermittent (maybe a race condition?)
- I do not yet have a short reproducer

**Comment by ianlancetaylor** [comment]
CC @alexbrainman

**Comment by forskning** [comment]
https://github.com/Microsoft/go-winio

In the final paragraph of the Readme.md file is a citation to another Go named pipe implementation.

**Comment by as** [comment]
The issue seems to be converging on how Go (and perhaps the new poller) interacts with named pipes. Cygwin uses named pipes as a conduit for data the would flow in between two processes as anonymous pipes under certain conditions mentioned in #22024

**Comment by as** [comment]
@forskning The difference is that Microsoft package seems to support additional functionality.

On Windows, named pipes can transfer data in `message` mode or `byte` mode. The original `npipe` didn't support `message` more. Cygwin on the other hand, uses `message` mode.

@mappu

In lieu of a short reproducible snippet, Are you able to share any information on how the pipe is created using that package? Specifically, the mode used (`message` or `byte), and whether this affects your ability to reproduce the issue in your application.

**Comment by alexbrainman** [comment]
@mappu it is difficult to suggest anything without reproducible example. Even non reproducible example would be better than what you have provided - vague description of what you think your program does.

Alex

**Comment by alexbrainman** [comment]
@mappu can you, please, try https://golang.org/cl/69871 to see if it fixes your problem?

Thank you

Alex
