### ISSUE TITLE
should bad hostname panic `url.Parse`?

### ISSUE THREAD

**Issue by kzw** [golang/go#22205]
Please answer these questions before submitting your issue. Thanks!

https://play.golang.org/p/Vxyft5EGVq

### What version of Go are you using (`go version`)?

1.9, 1.7

### Does this issue reproduce with the latest release?
It was reproduced in 1.9

### What operating system and processor architecture are you using (`go env`)?
goplayground and go on macOS10.12.6, mac pro, intel

### What did you do?

https://play.golang.org/p/Vxyft5EGVq

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

I expect the `url.Parse` to return `err` on bad hostname

### What did you see instead?

Got the panic message

**Comment by davecheney** [comment]
This is working as intended. The panic is not coming from url.Parse, but from calling methods on `u` . url.Parse returned an error, so the state of `u` is unknown, and it is not safe to access it at all.

**Comment by mattn** [comment]
FYI: https://play.golang.org/p/Ci-X4Y9NR2

Go compler make it error.
>parse https:// . merchant-css.s3.com:7200/blad/dotla/a: invalid character " " in host name
