### ISSUE TITLE
x/sys/unix: Possible to create an RFCOMM socket?

### ISSUE THREAD

**Issue by dangerousHobo** [golang/go#22211]
Hello,

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.9.1 linux/386
```

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mjohn/workspaces/goprojects"
GORACE=""
GOROOT="/home/mjohn/software/go"
GOTOOLDIR="/home/mjohn/software/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build394932560=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

I'm trying to create an RFCOMM socket but not able to find a socket address type which works. Theres the Sockaddr... types available but none appear to support a Bluetooth RFCOMM socket. I'm assuming its possible because `unix.AF_BLUETOOTH` and `unix.BTPROTO_RFCOMM` are defined.
What am I missing?

```
package main

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"syscall"

	"golang.org/x/sys/unix"
)

// Bluetooth address string to byte array
func str2ba(addr string) [6]byte {
	a := strings.Split(addr, ":")
	var b [6]byte
	for i, tmp := range a {
		u, _ := strconv.ParseUint(tmp, 16, 8)
		b[i] = byte(u)
	}
	return b
}

func main() {
	fd, err := unix.Socket(syscall.AF_BLUETOOTH, syscall.SOCK_STREAM, unix.BTPROTO_RFCOMM)
	if err != nil {
		log.Fatalf("%v\n", err)
	}
	//addr := &unix.RawSockaddr?
       //addr := &unix.Sockaddr..?
	unix.Bind(fd, addr)
	unix.Write(fd, []byte("Hello"))
	var data []byte
	unix.Read(fd, data)
	fmt.Printf("Received: %v\n", string(data))
}
```

Thanks for your help!

**Comment by mdlayher** [comment]
You'd most likely have to implement a new sockaddr type, as I did here: https://github.com/golang/sys/commit/d67a3279aecd76a65c4c9e6c352c888f5b3a574a.

I don't have time to immediately dig in, but perhaps this can lead you in the right direction.

**Comment by dangerousHobo** [comment]
Thanks Matt, with that I was able to create a functioning socket.
I'll submit a PR after a few days of testing.

**Comment by simonswine** [comment]
@dangerousHobo how did you manage to get that working? Can't see something submitted in gerrit...

**Comment by mdlayher** [comment]
I'll reopen this for tracking, until a CL closes it.
