### ISSUE TITLE
cmd/go: compile environment variable into binary during `go get'

### ISSUE THREAD

**Issue by VojtechVitek** [golang/go#22216]
Hi gophers,

there are lots of "go get"-able CLI programs out there on Github but most of them don't have a built-in `version` flag/sub-command, just because it's almost impossible to compile an environment variable into a binary during the `go get -u <pkg/cmd>` invocation.

I wonder, are there any plans on making `go get` more robust and let it

1. Invoke `go:generate` automatically on `go get`?
2. Or set an environment variable during `go get`, an equivalent of explicit `-ldflags "-X main.Version=$(git describe --tags)"`?
3. Any other ideas?

I know this all can be "automated" in Makefile, but the question is if we can ever expect the `go get` command to get this right too?

This would naturally provide a simple solution for issues like https://github.com/golang/dep/issues/209#issuecomment-318517555

**Comment by ianlancetaylor** [comment]
There are no such plans.

Any discussion should take place on golang-dev.

This seems like a set of possible solutions rather than a problem.  Do you want to restate this in the form of a problem?

**Comment by VojtechVitek** [comment]
@ianlancetaylor thanks, let me try:

Problem:
There is no way to bake in `VERSION` string (such as `git describe --tags`) into a binary when installing the CLI tool via standard `go get -u <pkg/cmd>` command.

**Comment by ianlancetaylor** [comment]
I'm sure I'm missing something, but it seems to me that any version number ought to be set in the master source code.  I don't see why I would want the version to depend on the characteristics of the machine where the program happens to be built.

**Comment by VojtechVitek** [comment]
@ianlancetaylor I understand your point of view.

So, is the recommended practice to commit the `VERSION` string directly to the source code of the repository (master branch), rather than providing it on the build time?

**Comment by ianlancetaylor** [comment]
That is what I would do, yes.

**Comment by mvdan** [comment]
Likely a dup of #22147, which is a more narrow proposal and would not require running arbitrary code. Both seem to be looking at the same root problem.

**Comment by VojtechVitek** [comment]
You're right, I think it is dup of #22147.
