### ISSUE TITLE
x/build: build.golang.org should link to Gerrit, not GitHub commits

### ISSUE THREAD

**Issue by rsc** [golang/go#22217]
The left column of build.golang.org has Git commit hashes, and it links to 

	https://github.com/golang/go/commit/<COMMIT>
 
But all of us most commonly use Gerrit to view commits. We should probably do the same here. The URL should change to

	https://go-review.googlesource.com/q/<COMMIT>

Not sure who, if anyone, is in charge of build.golang.org these days.

/cc @andybons @adams-sarah

**Comment by adams-sarah** [comment]
I am responsible for fixing builder bugs. Features I'm pushing out 'til @bradfitz gets back. Lack of time.
Maybe Andy can take this.

**Comment by adams-sarah** [comment]
Thanks Andy.

**Comment by andybons** [comment]
This has been deployed to build.golang.org.

There is a bug where going back from the Gerrit change page via this shortcut is broken, but a fix for that was also submitted (https://gerrit-review.googlesource.com/132930) and should be live whenever Gerrit deploys next (week or two?).
