### ISSUE TITLE
net/url: stackoverflow in url.URL.String()

### ISSUE THREAD

**Issue by tevjef** [golang/go#22222]
## What version of Go are you using (`go version`)?
1.9.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
OSX 10.12 

```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?

https://play.golang.org/p/cZ-BjpkD6D

**Comment by ianlancetaylor** [comment]
This is not a bug.  Your `MyUrl.String` method simply calls itself.
