### ISSUE TITLE
cmd/compile: strange use of GOEXPERIMENT

### ISSUE THREAD

**Issue by rsc** [golang/go#22223]
cmd/compile/internal/gc/main.go looks at $GOEXPERIMENT and if it's non-empty disables concurrent compilation.
I can't tell why. GOEXPERIMENT is only meaningful during make.bash; after that the experiment set is baked into the toolchain and not reloaded from the environment.

I suspect this use of $GOEXPERIMENT should just be removed.

/cc @Josharian @mdempsky

**Comment by mdempsky** [comment]
It looks like there's a similar check in cmd/go/internal/work/build.go too.

I think the intent was that @josharian wasn't confident the non-standard code paths enabled by experiments were safe for concurrency.

Agreed the checks do not function as intended.

**Comment by bradfitz** [comment]
Reopening this, because GOEXPERIMENT is now broken since that CL.

I left comments on https://go-review.googlesource.com/c/go/+/80760 with details.

/cc @rsc

**Comment by ianlancetaylor** [comment]
As far as I can tell this is a valid issue, but there is no trivial fix, and things are working today, so rolling this forward to 1.11.

**Comment by mdempsky** [comment]
The original issue (that cmd/compile was erroneously checking the GOEXPERIMENT environment variable) is fixed, so I think this can be closed again. (I saw @bradfitz's comment on the CL, but didn't notice he reopened this issue.)
