### ISSUE TITLE
runtime: <autogenerated> elimination breaks some uses of `runtime.CallersFrames`

### ISSUE THREAD

**Issue by aclements** [golang/go#22231]
### What version of Go are you using (`go version`)?
go version devel +67388e9866 Thu Oct 12 01:03:14 2017 +0000 linux/amd64

### Does this issue reproduce with the latest release?
No. This was introduced on master after Go 1.9 by [CL 45412](https://golang.org/cl/45412), which fixed #16723.

### What did you do?
https://play.golang.org/p/3rfhN6rO-_

### What did you expect to see?
Prior to CL 45412, this would print the function information for the autogenerated wrapper `I.M`.

### What did you see instead?
On master, `Next` returns no frames because the stack consists solely of an autogenerated wrapper, which we now hide from stack traces.

We started hiding autogenerated wrappers because, in any real stack trace, the preceding entry would be the actual method that the user thought they were calling. In this case, this logic fails because the stack is synthetic and consists solely of the wrapper.

Perhaps we shouldn't hide wrappers if they're the first entry in the stack trace.

There is a simple workaround. Code like this should be using `runtime.FuncForPC` anyway. But we shouldn't needlessly break things.

**Comment by bcmills** [comment]
I suspect this could interact badly with embedded methods too.

For example, the program in https://play.golang.org/p/xeyW_fDeo9 dereferences a nil pointer in an autogenerated method (see #18617), which could result in a panic trace showing no frames.

**Comment by bcmills** [comment]
(And the workaround of using `runtime.FuncForPC` would not work for the nil-panic case.)

**Comment by aclements** [comment]
That's a good example. Amusingly, when run on tip we get a *larger* stack trace because the first attempt doesn't get any frames, so we retry with runtime frames enabled. But that's clearly not ideal. :)

**Comment by s4l1h** [comment]
I have some issue latest version.

1.9.2 => called from <autogenerated># 1


devel => called from # 0


▶ tree
.
├── main.go
└── runtimetest
    └── init.go

1 directory, 2 files



**main.go**
```
package main
import (
	"fmt"
	t "./runtimetest"
)
func main() {
	fmt.Println(t.File)
}
```


**runtimetest/init.go**

```

package runtimetest

import (
	"fmt"
	"runtime"
)

var File string

func init() {

	_, file, no, ok := runtime.Caller(1)
	if ok {
		fmt.Printf("called from %s#%d\n", file, no)
	}
	File = File
}
```
**brew install go**

```
▶ go version
go version go1.9.2 darwin/amd64
▶ go run main.go
called from <autogenerated>#1
```

**brew install --HEAD go**
```
▶ go version
go version devel +0153a4130d Mon Oct 30 19:55:02 2017 +0000 darwin/amd64
▶ go run main.go
called from #0
```

**Comment by aclements** [comment]
@s4l1h, what's the issue? `init` doesn't have a caller, so arguably HEAD is giving the right answer and 1.9 wasn't.

**Comment by s4l1h** [comment]
@aclements 
if change the caller skip param 1 to 0.  
1.8rc3, 1.9.2 and head version work perfect.

> runtime.Caller(1) => runtime.Caller(0)

**Comment by aclements** [comment]
> if change the caller skip param 1 to 0.

Right. I'm still unclear on what you were expecting. Using `Caller(1)` in an init function is definitely depending on an implementation detail that could easily change for any number of reasons. If you want to find out information on the function that calls `Caller()`, you should use a skip of 0.
