### ISSUE TITLE
an puzzle output problem

### ISSUE THREAD

**Issue by wlf92** [golang/go#22232]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
I don't sure, maybe

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vili/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nt/vtbfwxmj5q7fx5thc8ynbr200000gp/T/go-build626772251=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

If possible, provide a recipe for reproducing the error.
I just do online judge on leetcode (problem 216)

```
//////// my code /////////////

package main

import (
	"fmt"
)

func main() {
	fmt.Println(combinationSum3(8, 36)) // output2
}

var results [][]int

func getSum(nums []int) int {
	sum := 0
	for _, num := range nums {
		sum += num
	}
	return sum
}

func collect(nums []int, curr, k, n int) {
	sum := getSum(nums)
	count := len(nums)
	for num := curr; num < 10; num++ {
		newSum := sum + num
		if count+1 == k {
			if newSum == n {
				// nnnn := make([]int, len(nums))
				// copy(nnnn, nums)
				// nnnn = append(nnnn, num)

				nums = append(nums, num)
				fmt.Println(nums) // output1
				results = append(results, nums)
			}
		} else {
			if newSum < n {
				collect(append(nums, num), num+1, k, n)
			}
		}
	}
}

func combinationSum3(k int, n int) [][]int {
	results = make([][]int, 0)
	if k < n {
		collect([]int{}, 1, k, n)
	}
	return results
}

////////////////////////////////// out put////////////
[1 2 3 4 5 6 7 8]     // 1
[[1 2 3 4 5 9 9 8]]     // 2

```

why the results change?

**Comment by randall77** [comment]
We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.
