### ISSUE TITLE
time: remove unnecessary if condition segment Mon <= dec31wday since it is always true in ISOWeek()

### ISSUE THREAD

**Issue by msimonsson** [golang/go#22241]
Hi,

In ISOWeek() Mon is the first day of the week.

https://github.com/golang/go/blob/master/src/time/time.go#L565

```go
if dec31wday := (wday + 31 - day) % 7; Mon <= dec31wday && dec31wday <= Wed {
```

The condition `Mon <= dec31wday` is always true and the line can be changed to:

```go
if dec31wday := (wday + 31 - day) % 7; dec31wday <= Wed {
```

**Comment by ianlancetaylor** [comment]
I think the code is clear, and removing the condition won't make it clearer.
