### ISSUE TITLE
syscall: timeout parameter to Select is treated as Timespec instead of Timeval on linux/arm64

### ISSUE THREAD

**Issue by tklauser** [golang/go#22246]
### What version of Go are you using (`go version`)?

go version go1.9.1 linux/arm64

### Does this issue reproduce with the latest release?

Yes (reproduced on current tip).

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tklauser/gopath"
GORACE=""
GOROOT="/home/tklauser/go"
GOTOOLDIR="/home/tklauser/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build256498452=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Consider the following program which uses `syscall.Select` to unconditionally sleep for 2 milliseconds:

```golang
package main

import (
        "fmt"
        "syscall"
        "time"
)

func main() {
        t := syscall.Timeval{0 /*sec*/, 2000 /*usec*/}

        start := time.Now()
        _, err := syscall.Select(0, nil, nil, nil, &t)
        end := time.Now()

        if err == nil {
                fmt.Printf("select returned after %v\n", end.Sub(start))
        }
}
```

### What did you expect to see?

I'd expect the program to print something similar to `select returned after 2.0535ms` (the exact number may obviously vary, but should be around 2ms). Running the program e.g. on linux/amd64 indeed produces the expected output.

### What did you see instead?

Running the above program on linux/arm64 produces the output `select returned after 249.68µs`, i.e. the expired timeout is much less than 2ms.

The cause for this is that `syscall.Select` uses the `SYS_PSELECT6` on linux/arm64 (and linux/mips64 for that matter, but I didn't check there). `pselect6` expects the timeout argument of type `struct timespec` with nanosecond precision, while the classic select syscall expects a `struct timeval` with microsecond precision (see http://man7.org/linux/man-pages/man2/select.2.html, section "The timeout" for details).

Indeed, changing `t := syscall.Timeval{0 /*sec*/, 2000 /*usec*/}` to `t := syscall.Timeval{0 /*sec*/, 2000 * 1000 /*usec*/}` in the program above produces the expected output.

`SYS_SELECT` or `SYS__NEWSELECT` don't exist on linux/arm64, so the easiest solution is probably to add `syscall.pselect` and make `syscall.Select` a wrapper around it, converting the timeout argument. FWIW this is what glibc also does if neither `__NR_select` nor `__NR__newselect` is defined for a particular architecture.

Note that the same problem also exists in golang.org/x/sys/unix

**Comment by zx2c4** [comment]
The MIPS64 and ARM64 code in this commit introduced a breaking regression. Timespec is allowed to be nil on all other platforms, and that's how the syscall works. Passing nil means "does not timeout". However, on MIPS64 and ARM64, this will result in a null ptr reference.
