### ISSUE TITLE
os/signal: document how to forward all signals

### ISSUE THREAD

**Issue by kevinburke** [golang/go#22257]
I'm writing a command line wrapper that sets some state in the world, starts a child process, waits for it to complete, and then unsets some state in the world.

So basically something like

```go
doSomeStatefulThing()
cmd := exec.Command("subcmd", args...)
cmd.Stdin = os.Stdin
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
err := cmd.Run()
undoSomeStatefulThing()
return err
```

I missed the line in the `signal.Notify` docs that says 

>  If no signals are provided, all incoming signals will be relayed to c. Otherwise, just the provided signals will.

It might be good to provide a second Example for Notify where the args... list is empty, for people who are silly like me and miss the doc.

(It might also be good if it was easier to set up a proxied command - it seems like it's easy to miss some of the steps involved in proxying through all FD's/signals in both directions.)

**Comment by 92161898515** [comment]
👍

**Comment by bcmills** [comment]
I don't really understand how the proposed documentation relates to the code snippet you've provided as a use-case: what does the call to `signal.Notify` have to do with the subprocess?

**Comment by ianlancetaylor** [comment]
@bcmills: @kevinburke wants to forward all signals from the parent process to the child process, so the first step is a way to find out when the parent process receives an arbitrary signal.

**Comment by kevinburke** [comment]
Yes, apologies, I need to improve my understanding the signal forwarding
mechanisms better, and haven't had time to do that, which is why I've been
slow to respond.


--
Kevin Burke
925.271.7005 | kev.inburke.com
