### ISSUE TITLE
spec: unnecessary phrase in range loop description

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22258]
The spec currently says (emphasis added):

> The range expression is evaluated once before beginning the loop, with one exception: **if the range expression is an array or a pointer to an array** and at most one iteration variable is present, only the range expression's length is evaluated; **if that length is constant**, by definition the range expression itself will not be evaluated.

Arrays always have constant length though, so the second conditional seems redundant.

/cc @griesemer

**Comment by go101** [comment]
it is a `; `, instead of `,` before "if". The range expression may be a slice, string or map.

**Comment by mdempsky** [comment]
@go101 I don't think that interpretation holds. It says "that length," referring to "the range expression's length," which was predicated on the expression being an array or pointer to array. Also, slices, strings, and maps do not have constant length. Finally, if they're two separate exceptions, the "with one exception" wording is wrong.

**Comment by bcmills** [comment]
> Arrays always have constant length though

Arrays do not always have constant length.

“The expressions `len(s)` and `cap(s)` are constants if the type of `s` is an array or pointer to an array and the expression `s` does not contain channel receives or (non-constant) function calls”.

**Comment by griesemer** [comment]
By definition, an array has a constant length. The expression `s` may still contain channel receives and function calls, resulting in an array. No matter what, that array has constant length.

**Comment by mdempsky** [comment]
Arrays always have constant length:

> An array is a numbered sequence of elements of a single type, called the element type. The number of elements is called the length and is never negative.
>
> The length is part of the array's type; it must evaluate to a non-negative constant representable by a value of type int.

The expression `len(s)` is not always a constant expression though.

The distinction between those two ideas is the crux of this issue.
