### ISSUE TITLE
x/build: dev.golang.org/reviews has a link to a submitted CL

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#22259]
When I look at https://dev.golang.org/reviews today, I see this line:

    38634 encoding/base32: add Encoding.WithPadding, StdPadding, NoPadding

It has a link to https://golang.org/cl/38634, as it should.  But that CL was submitted on May 22.  I don't know why it is showing up in the list of CLs that need review.

**Comment by andybons** [comment]
Fixed in golang/build@ee6321b
