### ISSUE TITLE
cmd/link: regression introduced with golang.org/cl/69370 on ppc64le 

### ISSUE THREAD

**Issue by laboger** [golang/go#22250]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go tip

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le Ubuntu any

### What did you do?
Saw ppc64le failures on golang.org/build

### What did you expect to see?
ok

### What did you see instead?
Output from the log:

##### ../misc/cgo/testplugin
PASS
something
fatal error: runtime: plugin has empty pluginpath

goroutine 1 [running]:
runtime.throw(0x10151c61, 0x24)
	/tmp/workdir/go/src/runtime/panic.go:616 +0x68 fp=0xc420047a30 sp=0xc420047a00 pc=0x1008e5a8
plugin.lastmoduleinit(0x10130780, 0x0, 0x0, 0xc420068150, 0x1020bb20)
	/tmp/workdir/go/src/runtime/plugin.go:23 +0x9cc fp=0xc420047b60 sp=0xc420047a30 pc=0x1008f73c
plugin.open(0x1014ec73, 0x12, 0x100bcd50, 0x10069bfc, 0xc4200680f0)
	/tmp/workdir/go/src/plugin/plugin_dlopen.go:118 +0x32c fp=0xc420047e50 sp=0xc420047b60 pc=0x1011038c
plugin.Open(0x1014ec73, 0x15, 0x1010f510, 0x1014d129, 0x10111140)
	/tmp/workdir/go/src/plugin/plugin.go:32 +0x34 fp=0xc420047e98 sp=0xc420047e50 pc=0x1010f924
main.main()
	/tmp/workdir/go/misc/cgo/testplugin/src/issue22175/main.go:14 +0x3c fp=0xc420047f58 sp=0xc420047e98 pc=0x1011119c
runtime.main()
	/tmp/workdir/go/src/runtime/proc.go:195 +0x1fc fp=0xc420047fc0 sp=0xc420047f58 pc=0x100907ec
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_ppc64x.s:1353 +0x4 fp=0xc420047fc0 sp=0xc420047fc0 pc=0x100b7c94
2017/10/13 01:19:27 Failed: exit status 2
2017/10/13 01:19:27 FAILED

**Comment by crawshaw** [comment]
The failure is on the test case added in guilty commit, CL 69370. I am assuming the underlying cause of the failure was pre-existing on linux/ppc64le, we just didn't have a test to see it.

So if you need a quick fix for the builder, we can disable the test on ppc64le. Otherwise I'm going to keep staring at it and see if I can find the underlying problem. (Made a bit difficult by the fact I don't have one of these machines.)
