### ISSUE TITLE
cmd/compile: do not report internal compiler error after ordinary compiler error

### ISSUE THREAD

**Issue by rsc** [golang/go#22252]
For #21882, instead of checking in the actual fix, I'd like to just silence any "internal compiler error" that happens after a regular compiler error has already been printed. The old C version of the compiler did this and it was quite effective. This change would be very low risk, in contrast to trying to fix actual errors.

**Comment by mdempsky** [comment]
Currently, we have code in Fatalf to only print stack traces for dev builds, and to instead just print a message asking users to file a bug report for release builds.

Is the issue that behavior isn't working as intended, or that you don't think we should even do that if we've printed an actual error first?

**Comment by mdempsky** [comment]
Yeah, looks like that code is broken.

**Comment by mdempsky** [comment]
Changing Fatalf to check for "go" instead of "release" changes #21882 to print:

    /tmp/q.go:3:6: invalid recursive type N
    /tmp/q.go:3:6: internal compiler error: invalid alignment for N

    Please file a bug report including a short program that triggers the error.
    https://golang.org/issue/new

Is that desirable, or do you prefer we squelch the error altogether since there was a proper error?

**Comment by rsc** [comment]
Please silence the whole thing. If there was already an error reported and then the compiler shoots itself in the foot, better to just let the user fix the reported error and try again. If no error was reported yet, then of course print the internal error.

This logic was invaluable when Dmitriy was fuzzing the compiler. It just eliminates a whole class of mostly useless bug reports. :-)

**Comment by mdempsky** [comment]
Reopening for Go 1.9.x.

**Comment by rsc** [comment]
CL 22252 OK for Go 1.9.5.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 70850](https://golang.org/cl/70850) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:22 UTC
