### ISSUE TITLE
cmd/vet: unexpected package-level comment in dead.go

### ISSUE THREAD

**Issue by pto** [golang/go#22263]
The comments at the start of src/cmd/vet/dead.go don't have completely blank lines so they are treated as package-level documentation.

#### What did you do?
go doc vet

#### What did you expect to see?
Package-level documentation

#### What did you see instead?
The Go Authors copyright message and "Simplified dead code detector. Used for skipping certain checks on unreachable code (for instance, shift checks on arch-specific code)."

#### System details
master branch

**Comment by ianlancetaylor** [comment]
Thanks.  This was already fixed by https://golang.org/cl/65630.
