### ISSUE TITLE
cmd/go: fix TestImportMain not to write to current directory

### ISSUE THREAD

**Issue by raydac** [golang/go#22266]
Golang SDK 1.9.1 zip archives for Windows (both amd64 and i386) contain file  __/go/src/cmd/go/x.exe__ I could not find similar file in Linux distributive and in Go SDK 1.9 for Windows,  the issue is that [many antiviruses complain about the file](https://www.virustotal.com/#/file/ffb4f32afbb23131a68a55a3b3692299489d75ad12e82af72bc938c66023fb8f/detection)
what is the file?

**Comment by dlsniper** [comment]
For the amd64 at least, I have the same file but it has a different size / SHA256 and a different outcome in the [scan results](https://www.virustotal.com/#/file/d9c1b0aee3cc3f3a5cce0208438103e27664d18f53961e21f6c29f275ce01b94/detection) 
I've installed Go via the .msi installer. Looking at the archive it matches the file I have on my machine (both size/SHA256)

**Comment by cznic** [comment]
I've verified the file at https://storage.googleapis.com/golang/go1.9.1.windows-386.zip has the correct SHA256 and _does_ contain the x.exe file at the path OP listed.

**Comment by raydac** [comment]
my plugin loads archives through web api from  https://storage.googleapis.com/golang/
also I have checked both manually loaded archives from standard page https://golang.org/dl/

**Comment by dlsniper** [comment]
@raydac can you try on a third party system? Maybe from a Linux based OS?

**Comment by raydac** [comment]
@dlsniper what do you mean? I have loaded manually zip golang sdk archives 1.9.1 for windows under Ubuntu and x.exe is presented in both zip archives, calculated sha256 are the same like described on the main download page
ea9c79c9e6214c9a78a107ef5a7bff775a281bffe8c2d50afa66d2d33998078a  ./go1.9.1.windows-386.zip
8dc72a3881388e4e560c2e45f6be59860b623ad418e7da94e80fee012221cc81  ./go1.9.1.windows-amd64.zip

**Comment by dlsniper** [comment]
Cool, so now upload the exe files from the Ubuntu machine to that website and see what results you have. The sums for the archives seem to be correct, see if anything changes for that file, x.exe

**Comment by raydac** [comment]
@dlsniper 
[report for x.exe from amd64](https://www.virustotal.com/#/file/d9c1b0aee3cc3f3a5cce0208438103e27664d18f53961e21f6c29f275ce01b94/detection)
[report for x.exe from 386](https://www.virustotal.com/#/file/ffb4f32afbb23131a68a55a3b3692299489d75ad12e82af72bc938c66023fb8f/detection)

**Comment by thoellrich** [comment]
My `amd64` `x.exe` in the MSI installed tree has a `go.buildid` of `07f043544a1febd4867dcccd5eb032f2249449db`. Maybe a quick search for that in the official build logs will locate it?

All scans here says it's benign. Smells like an intermediate artifact that was packaged in error.

**Comment by mattn** [comment]
I checked go1.9.1.windows-amd64.zip downloaded from golang.org/dl on Ubuntu. 

![2017-10-14 22 56 07](https://user-images.githubusercontent.com/10111/31576305-ff1b0e96-b132-11e7-9a38-191398b83709.png)

But x.exe not exists.

**Comment by dlsniper** [comment]
@mattn the path is a bit incorrect, you need to run ` ls -la go/src/cmd/go ` not ` ls -la go/bin `.

**Comment by mattn** [comment]
Sorry, I found it on go/src/cmd/go. As far as I can see, it is built by go. And `C:\workdir\go\src\cmd\go` is cembeded in binary.

**Comment by mattn** [comment]
BTW, It seems that *_test.go in go/src/cmd/go have some string `x.go`.

**Comment by ianlancetaylor** [comment]
CC @broady

**Comment by mattn** [comment]
Specified download URL redirected from golang.org.

https://www.virustotal.com/#/url/be8bdf89ebaff51c56824ab6074db008e91161bdd5973af110140c4221cfb0ac/detection

https://www.virustotal.com/#/url/de7cb91aeb171dedeb9a3f56e77c6a6eaff4cc70f8a4d7b98f3a733a5e2ea952/detection

This seems not bad. One of the antivirus software seems to detect always.

**Comment by mattn** [comment]
And I uploaded x.exe contained the zip, but not detected.

https://www.virustotal.com/#/file/d9c1b0aee3cc3f3a5cce0208438103e27664d18f53961e21f6c29f275ce01b94/detection

The result page which I posted was redirected to the page which is already reported  by another user.

**Comment by mattn** [comment]
So, currently, what I can say is that x.exe I uploaded is not same file as x.exe uploaded by raydac.

**Comment by dlsniper** [comment]
@mattn this seems to be limited to the 386 distribution only. The file is present both in amd64 and 386 distros but only flagged as malicious in the 386 archive.

**Comment by raydac** [comment]
@mattn  a lot of antiviruses are red for version of x.exe from 386 version of golang sdk 1.9.1 and user of plugin also detected such signal for 32 bit version

**Comment by mattn** [comment]
@raydac I checked 386 zip file.

#### `https://storage.googleapis.com/golang/ go1.9.1.windows-386.zip`

https://www.virustotal.com/#/url/8704d418b889c02947d23530317fb1f14f039fbd1e81d9e6067826f5fdccc41e/detection

#### `https://storage.googleapis.com/golang/ go1.9.1.windows-386.msi`

https://www.virustotal.com/#/url/53e0087623755b8eb2962fa46496805b318422da9e1e4730978d73142777ef74/detection

#### x.exe extracted from go1.9.1.windows-386.zip

https://www.virustotal.com/#/file/ffb4f32afbb23131a68a55a3b3692299489d75ad12e82af72bc938c66023fb8f/detection

I wonder why the URL is not detected.

**Comment by coder543** [comment]
But... what _is_ x.exe?

**Comment by mattn** [comment]
I uploaded exe file that is compiled with GOOS=windows, GOARCH=386 on Ubuntu.

https://www.virustotal.com/#/file/96735a9738dab2e256067c5b1919220da6550203bef5f4391f59ffbb2d878969/detection

```
package main

import (
        "fmt"
        "log"
        "net/http"
)

func main() {
        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprint(w, "Hello Gopher")
        })

        log.Fatalln(http.ListenAndServe(":12345", nil))
}
```
It seems some antivirus ware detect binary compiled with GOOS=windows GOARCH=386 on Linux as malicious.

**Comment by rsc** [comment]
The binary is left over from running TestImportMain in cmd/go. It's harmless. We should remove it, but it's harmless. Any virus scanner that thinks the binary is a virus is wrong.

**Comment by forskning** [comment]
http://nurmi-labs.blogspot.com/p/gcc-fullbuild.html

FWIW, the SUA Interix 6.0 (for MS Vista) download contained the compressed source to compile gcc-4.2 plus dependencies, and the gcc_fullbuild text file reproduced in the above blog Page.

IIRC, AVG on the extracted 'binutils 2.17' had reported false positives on two separate text files.

The original golang-nuts 14 Oct 2017 mail of @raydac having referred to AVG.

**Comment by rsc** [comment]
CL 71410 OK for Go 1.9.5.

**Comment by rsc** [comment]
go1.9.2 has been packaged and includes:

  - [CL 71410](https://golang.org/cl/71410) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:24 UTC
