### ISSUE TITLE
net: windows tests fail due to changes to getmac [Go 1.8]

### ISSUE THREAD

**Issue by rsc** [golang/go#22276]
This was fixed in the Go 1.9 cycle and should be backported to make trybots happy when preparing point releases.

**Comment by rsc** [comment]
CL 41395 OK for Go 1.8.5.

**Comment by odeke-em** [comment]
Hehe, great filing this issue @rsc, getmac was giving the trybots hell when I ran them against your go1.8* release branches until we noticed the problem.

**Comment by rsc** [comment]
go1.8.5 has been packaged and includes:

  - [CL 41395](https://golang.org/cl/41395) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:52 UTC
