### ISSUE TITLE
wiki: Projects page is 404 but has links pointing to it.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#22284]
The following page is 404 at this moment:

https://github.com/golang/go/wiki/Projects

![image](https://user-images.githubusercontent.com/1924134/31598035-78cb0732-b219-11e7-92c2-61efd9078cce.png)

Is that intentional? (If so, where can I find rationale/history of discussion of the decision to remove/move that page? I [searched issues](https://github.com/golang/go/issues?q=is%3Aissue%20wiki%20projects), didn't find an answer.)

If not, it should be restored.

If yes, there's a link at https://github.com/golang/go/wiki that still points to it (and therefore results in 404):

![image](https://user-images.githubusercontent.com/1924134/31597974-31cff69e-b219-11e7-8f79-add33be89104.png)

As well as another link on [godoc.org](https://godoc.org) homepage, but I'll report that separately if needed.

**Comment by shurcooL** [comment]
According to https://github.com/golang/go/wiki/_history, the Projects page was removed yesterday, in commit [`d94bd06`](https://github.com/golang/go/wiki/_compare/e33c905b26a850ed59f62877f5a5ace600ed94d5...d94bd06b6820d6d378fc4ee35afe41115495cd89).

**Comment by ALTree** [comment]
Looks like vandalism to me. I suggest we revert the change. I see no reason to delete that page.

**Comment by cznic** [comment]
I tried to revert and got first a server error. On second attempt it seems to be back now.

**Comment by shurcooL** [comment]
> Is that intentional?

Ok, so it looks like this was a case of vandalism, unfortunately.

The Projects page has been restored. I'll close this since the issue is resolved.

**Comment by ianlancetaylor** [comment]
Is there any way to find out who did it, and report them to Github if it was done intentionally?

**Comment by shurcooL** [comment]
@ianlancetaylor Yes, the change is a commit complete with a git author. That git author has a GitHub account associated with it.

**Comment by ianlancetaylor** [comment]
@shurcooL Thanks.

@hwtang Why did you delete our Projects page?

**Comment by ianlancetaylor** [comment]
I filed an abuse report with Github.

**Comment by hwtang** [comment]
Sorry , due to operational errors, mistakenly deleted the page.
