### ISSUE TITLE
runtime: heapdump hasn't been updated for a while

### ISSUE THREAD

**Issue by zhaozhiqianghw** [golang/go#22286]
I find the `dumpstr` in `heapdump.go:617` hasn't been updated for a while. It means Go is preparing to remove this feature? Or just forget it? It's still "go1.7 heap dump"

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker to ask questions.  Please see https://golang.org/wiki/Questions .  Closing this one.

We only need to update that string when we change the format.  There is no intention to change the string with every Go release.
