### ISSUE TITLE
runtime: TestLldbPython test fails with lldb 3.8 on linux

### ISSUE THREAD

**Issue by hyangah** [golang/go#22299]
Verified the test passed with lldb 3.9 or higher, or if lldb is not installed at all.

--- FAIL: TestLldbPython (1.83s)
	runtime-lldb_test.go:178: Unexpected lldb output:
		Created target
		Created breakpoint
		Process launched
		Hit breakpoint
		Stopped at main.go:10
		Stopped in main.main
		no intvar
FAIL
FAIL	runtime	19.046s

Skipping the test if lldb is too ancient seems reasonable.

**Comment by mvdan** [comment]
The `lldb` tests are already skipped if it or python are not available. Would an additional version check to ensure version 3.9 or later is available be an OK fix for this?

**Comment by ianlancetaylor** [comment]
Yes, checking the lldb version sounds like a good fix.
