### ISSUE TITLE
plugin: crash when calling functions from plugins that have dots inside their names

### ISSUE THREAD

**Issue by AndreyNevolin** [golang/go#22295]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes, I'm using the latest release

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?
I use a plugin whose name has dots inside. The program that uses this plugin crashes when a function from the plugin is called. The problem disappears if I rename the plugin (e.g. remove dots) and recompile everything.

To reproduce, one needs to do the following:
1) create "plugin_error/plugin_error.go" with the following contents:

```
package main

import (
	"plugin"
)

func main() {
	plugin_handler, err := plugin.Open("plugin/p.l.u.g.i.n.so")

	if err != nil {
		panic("Cannot open plugin: " + err.Error())
	}

	plugin_entry_symb, err := plugin_handler.Lookup("Plugin_entry")

	if err != nil {
		panic("Cannot find symbol: " + err.Error())
	}

	plugin_entry := plugin_entry_symb.(func())

	plugin_entry()
}

```
2) create "plugin_error/vendor/another_package/another_package.go" with the following contents:
```
package another_package

import "fmt"

func init() {
	fmt.Println("CAN YOU SEE THIS MESSAGE?")
}

func FormalFunction() {
	fmt.Println("Formal message")
}
```

3) create "plugin_error/p.l.u.g.i.n/p.l.u.g.i.n.go" with the following contents:
```
package main

import (
	"another_package"
)

func Plugin_entry() {
	another_package.FormalFunction()
}
```

4) go to "plugin_error/p.l.u.g.i.n/p.l.u.g.i.n.go" and run "go build -buildmode=plugin"
5) create a directory called "plugin_error/plugin"
6) copy the compiled plugin to this directory
7) build "plugin_error" package
8) ./plugin_error

### What did you expect to see?
For the code above, I expect to see:
```
CAN YOU SEE THIS MESSAGE?
Formal message
```

### What did you see instead?
A program crash

**Comment by AndreyNevolin** [comment]
I forgot to mention one more issue with plugins of that kind.
When they are loaded, `init()` functions from imported packages (i.e. imported by the plugin) are not called. The provided reproducer demonstrates this issue also. The text "CAN YOU SEE THIS MESSAGE?" is not shown, while `plugin.Open()` successfully returns

**Comment by AndreyNevolin** [comment]
@gbbr , new bug name is a little bit incorrect. It's not functions who have dots inside their names, but plugins. The problem is with plugin names.
Sorry for confusion.

**Comment by edaniels** [comment]
Random finding: importing `os` in `plugin_error/plugin_error.go` eliminates the crash

**Comment by AndreyNevolin** [comment]
Awesome! Thank you for the quick response and timely fix!
