### ISSUE TITLE
database/sql: example usage for Out is incorrect

### ISSUE THREAD

**Issue by pieterlouw** [golang/go#22292]
Hi,
Small thing, but please change example usage code for sql.Out from:
`_, err := db.ExecContext(ctx, "ProcName", sql.Named("Arg1", Out{Dest: &outArg}))`
to:
`_, err := db.ExecContext(ctx, "ProcName", sql.Named("Arg1", sql.Out{Dest: &outArg}))`

[Line 288 in database/sql/sql.go](https://golang.org/src/database/sql/sql.go?s=7393:7789#L288)

### What version of Go are you using (`go version`)?
Go 1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
 linux/amd64 (Windows Subsystem for Linux)

### What did you do?
I copied the code in the example usage of the new Out parameter and the compiler complained about unknown type `Out`

### What did you expect to see?
N/A
### What did you see instead?
Compile error

**Comment by ianlancetaylor** [comment]
CC @kardianos

**Comment by kardianos** [comment]
You are correct @pieterlouw . I'll send a fix for the docs soon to add the `sql.` package to the Out identifier. Thanks for spotting that.
