### ISSUE TITLE
cmd/vet: vet XTestGoFiles without directory walk

### ISSUE THREAD

**Issue by dnephin** [golang/go#22296]
Problem exists with all versions of go.

`go tool vet` supports args as either:
1. files, all of which must be in the same package.
2. a single directory, recursively descends the directory, vetting each package it finds.

Using files causes errors when there are external packages in the directory (ex: `example_test.go` uses `pkg_test`). The error is something like `ExampleNewFilter refers to unknown identifier: NewFilter`.

Using a directory walks the entire tree, which makes it impossible to ignore specific paths.

I propose to fix this issue by adding a `--no-recurse` flag to prevent the directory walk.

**Comment by ianlancetaylor** [comment]
Why not simply use `go vet` to vet the exact packages you want to check?

**Comment by dnephin** [comment]
`go vet` does not support any of the flags (ex: `-shadow`, `-all`, etc).

**Comment by ianlancetaylor** [comment]
> go vet does not support any of the flags (-shadow, -all, etc).

That has been fixed as of the 1.9 release (see #19350).

**Comment by dnephin** [comment]
Ah, Thanks! I missed that. That should work I think.

**Comment by ianlancetaylor** [comment]
OK, I'm going to close this issue.  Please comment if you disagree.
