### ISSUE TITLE
cmd/cover: "comments are out of order" error on code that doesn't have a go: comment directive.

### ISSUE THREAD

**Issue by aphistic** [golang/go#22309]
### What version of Go are you using (`go version`)?
go version devel +58cf881c1c Tue Oct 17 17:00:15 2017 +0000 linux/amd64
(go tip on Travis CI)

### Does this issue reproduce with the latest release?
It's currently happening on the version of go tip running on Travis CI

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 14.04.5 LTS on x86_64 (running on Travis CI)

### What did you do?
I just made an update to a library of mine that I have building on Travis CI against go tip and it just failed with the following error:

2017/10/17 18:03:48 comments are out of order. /home/travis/gopath/src/github.com/aphistic/gomol/attrs.go:147:1 was before -.

The file it's mentioning hasn't changed in 2 months and I can't decipher what the error actually means in this context.  The build itself is at https://travis-ci.org/aphistic/gomol/jobs/289149613#L544. The code in question is at https://github.com/aphistic/gomol/blob/fallback-logger/attrs.go#L147.

I already commented on the PR that seems to have committed the code I'm running into: https://go-review.googlesource.com/c/go/+/69630

### What did you expect to see?
A successful coverage run.

### What did you see instead?
The error mentioned above.

**Comment by kramvan1** [comment]
+1 having this same issue
