### ISSUE TITLE
encoding/json: structs in Json Decode improperly applied

### ISSUE THREAD

**Issue by patientplatypus** [golang/go#22307]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 darwin/amd64
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/patientplatypus/Documents/golang"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0q/_p03fcl11012llbls0r0bwp00000gn/T/go-build986239688=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### The issue.

On the front I send a POST request with `{charactername: "Frodo"}`

```
type Character struct {
	Charactername string
}

function IO(r, w){
        var incomingjson Character
	log.Print("value of r.Body: ", r.Body)
	decoder := json.NewDecoder(r.Body)
	log.Print("after json decoder")
	err := decoder.Decode(&incomingjson)
        charactername = incomingjson.Character
        log.Print(charactername)
}
```

This prints "".

However if I use

```
type Character struct {
	Charactername string
        Garbagevariable whatevertype
}
```

It will print "Frodo".

This is an annoying bug that cost me time. Please fix this

**Comment by ALTree** [comment]
Would you be able to provide a runnable reproducer? Your report does not contain a valid go program.

**Comment by davecheney** [comment]
I’m sorry this is not a valid bug report. You haven’t handled the error from decode and the input data you provided is not valid json.
