### ISSUE TITLE
cmd/link: records absolute working directory in binary

### ISSUE THREAD

**Issue by aclements** [golang/go#22311]
The linker records the result of `os.Getwd()` in the DWARF compilation unit's `DW_AT_comp_dir` attribute. This is almost certainly wrong since we've been working to keep information like this out of the binary (for example, it's not affected by `-trimpath`). It's also additionally wrong because it records the *linker's* working directory, where it's supposed to record the compiler's working directory [1].

It would be nice if we could just omit it, but there's a comment in `writelines` that says "OS X linker requires compilation dir or absolute path in comp unit name to output debug info." We could perhaps always make the value "/". Or perhaps we could use the package's source directory (with `-trimpath` applied).

[1] DWARF4: A DW_AT_comp_dir attribute whose value is a null-terminated string containing the current
working directory of the compilation command that produced this compilation unit in
whatever form makes sense for the host system. See also @thanm's [comment](https://go-review.googlesource.com/c/go/+/69973/1/src/cmd/link/internal/ld/dwarf.go#1045).

/cc @rsc @thanm

**Comment by corona10** [comment]
@aclements I am interested in this issue. Can I work on?

**Comment by ianlancetaylor** [comment]
CC @heschik

**Comment by heschik** [comment]
Oh, this is an old bug. It's hardcoded to `.` now.

https://github.com/golang/go/blob/179909f20556262422a8b99c059eacdfcebc48ee/src/cmd/link/internal/ld/dwarf.go#L1104
