### ISSUE TITLE
net/smtp: add Noop function

### ISSUE THREAD

**Issue by cryptix** [golang/go#22321]
Hi,

I want to add the `NOOP` command to the smtp client.

I think it would be good to have this to check the status of a client connection.

It looks like a simple addition and I'd be willing to contribute this myself.

One thing I'm not sure about is how to test this. The examples use `smtp.example.com` but I don't think this is really functional?

**Comment by ianlancetaylor** [comment]
For testing, see net/mail/smtp_test.go and the `serverHandle` function.

**Comment by ianlancetaylor** [comment]
Sorry, I said net/mail/smtp_test.go but of course I meant net/smtp/smtp_test.go.
