### ISSUE TITLE
x/net: Update "net/context" documentation to point to context package

### ISSUE THREAD

**Issue by frojasg** [golang/go#22322]
I was trying to figure out the difference between the "golang.org/x/net/context" and "context, " and I couldn't find any, so I was a little bit confused. I had to dig into the release notes until I saw the release notes for [1.7](https://golang.org/doc/go1.7#context) where it says:

> Go 1.7 moves the golang.org/x/net/context package into the standard library as context.

It would be helpful to update the doc in "x/net/context" to point to the release note. Also, I notice that go tool fix help you to change imports of golang.org/x/net/context to context. It would be cool to reference that too. 

I would be happy to help with a patch if you think is worth it.

**Comment by ianlancetaylor** [comment]
Yes, it's worth it.  I don't think you should point to the release note; that is no longer particularly interesting.  You should just say something like "as of Go 1.7 this package is available in the standard library under the name context" and point to golang.org/pkg/context.  Thanks.
