### ISSUE TITLE
runtime: SIGSEGV crash

### ISSUE THREAD

**Issue by stemar94** [golang/go#22324]
I'm in a hurry, can give more infos if needed to a later point in time.

#### What did you do?
Run some go program.

#### What did you expect to see?
No failure

#### What did you see instead?
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41bacf]

runtime stack:
runtime.throw(0x4eb8b9, 0x2a)
	/home/marvin/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/home/marvin/go/src/runtime/signal_unix.go:360 +0x279
runtime.scanblock(0x56a060, 0x6e10, 0x0, 0xc420026560)
	/home/marvin/go/src/runtime/mgcmark.go:1071 +0x5f
runtime.markrootBlock(0x56a060, 0x6e10, 0x0, 0xc420026560, 0x0)
	/home/marvin/go/src/runtime/mgcmark.go:294 +0x7c
runtime.markroot(0xc420026560, 0x2)
	/home/marvin/go/src/runtime/mgcmark.go:195 +0xe7
runtime.gcDrain(0xc420026560, 0x5)
	/home/marvin/go/src/runtime/mgcmark.go:912 +0xd4
runtime.gcBgMarkWorker.func2()
	/home/marvin/go/src/runtime/mgc.go:1782 +0x80
runtime.systemstack(0x0)
	/home/marvin/go/src/runtime/asm_amd64.s:421 +0x79
runtime.mstart()
	/home/marvin/go/src/runtime/proc.go:1152

goroutine 92 [GC worker (idle)]:
runtime.systemstack_switch()
	/home/marvin/go/src/runtime/asm_amd64.s:375 fp=0xc42002d748 sp=0xc42002d740 pc=0x450b20
runtime.gcBgMarkWorker(0xc420025300)
	/home/marvin/go/src/runtime/mgc.go:1769 +0x1e7 fp=0xc42002d7d8 sp=0xc42002d748 pc=0x417ce7
runtime.goexit()
	/home/marvin/go/src/runtime/asm_amd64.s:2374 +0x1 fp=0xc42002d7e0 sp=0xc42002d7d8 pc=0x453571
created by runtime.gcBgMarkStartWorkers
	/home/marvin/go/src/runtime/mgc.go:1664 +0x79

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x1bc8, 0xc420041af8, 0x1000004, 0x0, 0x0, 0xc4200d08e0, 0x0, 0x571de0)
	/home/marvin/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4203dda70, 0xc420041c90, 0xc4203dda70, 0x0)
	/home/marvin/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc4203dda70, 0xc4200d4470, 0xc4200f6e40, 0xc42043c398)
	/home/marvin/go/src/os/exec_unix.go:22 +0x42
os.(*Process).Wait(0xc4203dda70, 0x0, 0x0, 0x4ecc80)
	/home/marvin/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc42043c2c0, 0x0, 0x0)
	/home/marvin/go/src/os/exec/exec.go:446 +0x62
os/exec.(*Cmd).Run(0xc42043c2c0, 0x4f9fe0, 0xc4200c8750)
	/home/marvin/go/src/os/exec/exec.go:289 +0x5c
main.main()
	/home/marvin/GOPATH/src/hiwi/rvhyper/eval/callByPipe.go:77 +0x59c

goroutine 5 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x1ad8, 0xc42002fd30, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/marvin/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420014420, 0x0, 0x0, 0x0)
	/home/marvin/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc420014420, 0x0, 0x0, 0x3)
	/home/marvin/go/src/os/exec_unix.go:22 +0x42
os.(*Process).Wait(0xc420014420, 0xc420026600, 0x44f630, 0x8)
	/home/marvin/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc420084000, 0x4ed098, 0xc4200161b0)
	/home/marvin/go/src/os/exec/exec.go:446 +0x62
main.main.func1(0xc4200161b0, 0xc420084000)
	/home/marvin/GOPATH/src/hiwi/rvhyper/eval/callByPipe.go:48 +0x6d
created by main.main
	/home/marvin/GOPATH/src/hiwi/rvhyper/eval/callByPipe.go:46 +0x1fc

goroutine 90 [IO wait]:
internal/poll.runtime_pollWait(0x7f6e6f228ea0, 0x72, 0x1)
	/home/marvin/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200d7be8, 0x72, 0xffffffffffffff01, 0x4f9dc0, 0x55c128)
	/home/marvin/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200d7be8, 0xc420460001, 0x8000, 0x8000)
	/home/marvin/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200d7bd0, 0xc420460000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/marvin/go/src/internal/poll/fd_unix.go:134 +0x17d
os.(*File).read(0xc4200d4460, 0xc420460000, 0x8000, 0x8000, 0xc420031650, 0x476f4c, 0xc4200d6bb8)
	/home/marvin/go/src/os/file_unix.go:218 +0x4e
os.(*File).Read(0xc4200d4460, 0xc420460000, 0x8000, 0x8000, 0x8000, 0x8000, 0xc4200317b0)
	/home/marvin/go/src/os/file.go:103 +0x6d
io.copyBuffer(0x7f6e6f228f70, 0xc4200c8750, 0x4f9ca0, 0xc4200d4460, 0xc420460000, 0x8000, 0x8000, 0xc4200d6b90, 0x0, 0x0)
	/home/marvin/go/src/io/io.go:441 +0x123
io.Copy(0x7f6e6f228f70, 0xc4200c8750, 0x4f9ca0, 0xc4200d4460, 0x403845, 0xc4200f65a0, 0xc4200317b0)
	/home/marvin/go/src/io/io.go:411 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc4200f65a0, 0xc4200317b0)
	/home/marvin/go/src/os/exec/exec.go:264 +0x44
os/exec.(*Cmd).Start.func1(0xc42043c2c0, 0xc4200c7180)
	/home/marvin/go/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/home/marvin/go/src/os/exec/exec.go:379 +0x5d6

goroutine 89 [IO wait]:
internal/poll.runtime_pollWait(0x7f6e6f228b60, 0x72, 0x1)
	/home/marvin/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200d7af8, 0x72, 0xffffffffffffff01, 0x4f9dc0, 0x55c128)
	/home/marvin/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200d7af8, 0xc420458001, 0x8000, 0x8000)
	/home/marvin/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200d7ae0, 0xc420458000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/marvin/go/src/internal/poll/fd_unix.go:134 +0x17d
os.(*File).read(0xc4200d4438, 0xc420458000, 0x8000, 0x8000, 0xc42002a650, 0x476f4c, 0xc4200d79c8)
	/home/marvin/go/src/os/file_unix.go:218 +0x4e
os.(*File).Read(0xc4200d4438, 0xc420458000, 0x8000, 0x8000, 0x8000, 0x8000, 0x4)
	/home/marvin/go/src/os/file.go:103 +0x6d
io.copyBuffer(0x7f6e6f228f70, 0xc420072180, 0x4f9ca0, 0xc4200d4438, 0xc420458000, 0x8000, 0x8000, 0xc4200d79a0, 0x0, 0x0)
	/home/marvin/go/src/io/io.go:441 +0x123
io.Copy(0x7f6e6f228f70, 0xc420072180, 0x4f9ca0, 0xc4200d4438, 0x403845, 0xc4200f6d20, 0xc42002a7b0)
	/home/marvin/go/src/io/io.go:411 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc4200f6d20, 0xc42002a7b0)
	/home/marvin/go/src/os/exec/exec.go:264 +0x44
os/exec.(*Cmd).Start.func1(0xc42043c160, 0xc4200c7100)
	/home/marvin/go/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/home/marvin/go/src/os/exec/exec.go:379 +0x5d6

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

#### Does this issue reproduce with the latest release (go1.9.1)?
No

#### System details

```
go version devel +a9afa4e Wed Oct 18 03:07:46 2017 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/marvin/GOPATH"
GORACE=""
GOROOT="/home/marvin/go"
GOTOOLDIR="/home/marvin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build175459851=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +a9afa4e Wed Oct 18 03:07:46 2017 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +a9afa4e Wed Oct 18 03:07:46 2017 +0000
uname -sr: Linux 4.4.0-96-generic
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.23-0ubuntu9) stable release version 2.23, by Roland McGrath et al.
lldb --version: lldb version 4.0.0 (git@github.com:apple/swift-lldb.git revision 70491313e5e2769ac79262a42062c85c05948905)
  Swift-4.0 (revision 3416108abd0df3997a533a14c5ad06de20ba8a60)
  clang revision b9d76a314c1e4c79217df9cd9d168d007e90a51c
  llvm revision 2dedb62a0bcb69354e15a54be89fb5dfa63275d2
gdb --version: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
```

**Comment by ALTree** [comment]
Usual questions
- does the program use cgo?
- does the program trigger the race detector?
- how easily can you trigger the crash?
- can you provide some kind of reproducer?

**Comment by stemar94** [comment]
> does the program use cgo?

no
> does the program trigger the race detector?

no
> how easily can you trigger the crash?

happens almost every time
> can you provide some kind of reproducer?

https://play.golang.org/p/eB0DSNQe7h

**Comment by ianlancetaylor** [comment]
Thanks for the test case.  Unfortunately, I can not recreate the problem.  Your test case always completes for me without error.

> close failed in file object destructor:
> sys.excepthook is missing
> lost sys.stderr

What does that mean?

**Comment by stemar94** [comment]
> What does that mean?

I think this is from the broken pipe I write in with a interpreted python script.

**Comment by stemar94** [comment]
I updated the stack traces for the reproducer.

**Comment by ianlancetaylor** [comment]
@stemar94 Are you able to reproduce this on a different system?  Are you sure you are running an unmodified Go install?

**Comment by stemar94** [comment]
Run make.bash again. Now I also can no longer reproduce it. Really strange.
