### ISSUE TITLE
cmd/compile: ICE: not lowered: v58, ITab PTR64 PTR64

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22327]
At tip, this package fails to compile with an ICE in SSA:

    package p
    func f() ([]interface{}, *int) {
        return nil, nil
    }
    var _ = append(f())

/cc @randall77

**Comment by randall77** [comment]
go1.2 reports `multiple-value f() in single-value context`, and doesn't ICE.
go1.4 compiles it successfully (!)
go1.[56] ICEs with `cgen_wb of type interface {}`
go1.[789] to current ICE with `not lowered: ITab PTR64 PTR64`

I think go1.2 is correct.  I think if we reported that error correctly, we'd never pass the bad code to the backend, and then we wouldn't ICE.

**Comment by randall77** [comment]
go1.4 generated code is "correct", in that it does convert the *int to an interface{} and appends it to a []interface{}.

**Comment by randall77** [comment]
Hmmm, looks like `append` of the result of a multi-return function does generally work.
Maybe go1.4 is correct?

**Comment by mdempsky** [comment]
Oh, yes, the code should compile correctly, like it did with go1.4.

go/types and gccgo accept the code. (Sorry, I should have mentioned that in the original report.)

**Comment by mdempsky** [comment]
Looking at cmd/compile's -W output, I think maybe this is an issue in walk instead. Currently we're rewriting `append(f())` into something like:

    t0, t1 := f()
    append([]interface{}(t0), t1)

I think what we actually mean to do is rewrite it to:

    t0, t1 := f()
    append(t0, interface{}(t1))

**Comment by ianlancetaylor** [comment]
Still happening with `go version devel +9761a162f0 Thu Mar 29 16:37:26 2018 +0000 linux/amd64`

**Comment by ianlancetaylor** [comment]
This has been broken for a while, so punting to 1.12, but marking as a release-blocker for that release.

**Comment by randall77** [comment]
Looks like there is a missing `CONVIFACE` here.
Before order:
```
.   AS l(7) tc(1)
.   .   NAME-_ a(true) l(7) x(0) tc(1) SLICE-[]interface {}
.   .   APPEND l(7) tc(1) SLICE-[]interface {}
.   .   APPEND-list
.   .   .   CALLFUNC l(7) tc(1) STRUCT-([]interface {}, *int)
.   .   .   .   NAME-p.f a(true) l(3) x(0) class(PFUNC) tc(1) used FUNC-func() ([]interface {}, *int)
```
After order:
```
.   AS2FUNC l(7) tc(1)
.   AS2FUNC-list
.   .   NAME-p..autotmp_2 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used SLICE-[]interface {}

.   .   NAME-p..autotmp_3 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used PTR-*int
.   AS2FUNC-rlist
.   .   CALLFUNC l(7) tc(1) STRUCT-([]interface {}, *int)
.   .   .   NAME-p.f a(true) l(3) x(0) class(PFUNC) tc(1) used FUNC-func() ([]interface {}, *int)

.   AS2 l(7) tc(1)
.   AS2-list
.   .   NAME-p..autotmp_0 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used SLICE-[]interface {}

.   .   NAME-p..autotmp_1 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used PTR-*int
.   AS2-rlist
.   .   NAME-p..autotmp_2 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used SLICE-[]interface {}

.   .   NAME-p..autotmp_3 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used PTR-*int
.   AS l(7) tc(1)
.   .   NAME-_ a(true) l(7) x(0) tc(1) SLICE-[]interface {}
.   .   APPEND l(7) tc(1) SLICE-[]interface {}
.   .   APPEND-list
.   .   .   NAME-p..autotmp_0 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used SLICE-[]interface {}
.   .   .   NAME-p..autotmp_1 a(true) l(7) x(0) class(PAUTO) esc(N) tc(1) assigned used PTR-*int
```
Nowhere is there a `CONVIFACE` to convert the second `append` arugment from `*int` to `interface{}`.
Normally the typecheck pass, even before order, inserts `CONVIFACE` and the like ops to convert function arguments to the right types. We just don't do that here.
I think `copyRet` in `order.go` needs to use temporaries corresponding to the outer function's required argument types instead of the inner function's result types. Then the `typecheck` call it does should insert the conversions required.
