### ISSUE TITLE
cmd/compile: erroneously rejects copy(f()) where f() is multi-valued

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22328]
At tip, cmd/compile rejects this package with "missing arguments to copy":

    package p
    func f() ([]byte, string) { return nil, "" }
    var _ = copy(f())

The same package is accepted by go/types and gccgo, and seemingly valid according to the spec.

**Comment by mdempsky** [comment]
Notably cmd/compile does handle `complex(func() (float64, float64) { return 0, 0 }())` correctly.

**Comment by ALTree** [comment]
This is #15992

**Comment by mdempsky** [comment]
Closing as dup.
