### ISSUE TITLE
Got "mkdir Access is denied" on Windows

### ISSUE THREAD

**Issue by DeepAQ** [golang/go#22339]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
Installed Go 1.9.1 for Windows.
When I run `go run test.go` , I get a message saying "mkdir C:\Users\adn55\AppData\Local\Temp\go-build105336363: Access is denied." However, running this command with administrator privilege works.
I ensure that `C:\Users\adn55\AppData\Local\Temp` is writable by my user account.

#### System details

```
go version go1.9.1 windows/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\adn55\go"
GORACE=""
GOROOT="C:\Go"
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\adn55\AppData\Local\Temp\go-build442581091=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9.1 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.9.1
gdb --version: GNU gdb (GDB) 7.10.1
```

**Comment by DeepAQ** [comment]
Probably caused by the lack of digital signature of `go.exe` . Installing Go in non-system partition solved the problem.

**Comment by mattn** [comment]
What code did you run?

**Comment by DeepAQ** [comment]
I tried to run a Hello World program. In fact, running any program gives the same "Access is denied" error.

**Comment by gbbr** [comment]
@DeepAQ you need to provide all of the information required by the issue template. You need to link here to the code that you ran, the output that you've expect and the actual output that you've received.

**Comment by gbbr** [comment]
> Probably caused by the lack of digital signature of go.exe . Installing Go in non-system partition solved the problem.

In this case I am closing the issue. Please re-open it if it happens again and provide more exact reproduction steps.
