### ISSUE TITLE
reflect.DeepEual returns false with two string slices are actually equal

### ISSUE THREAD

**Issue by leesper** [golang/go#22336]
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
Yes, I am using the latest go

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/likejun/go-proj"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build187650890=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
I write a function called "Map", this function takes an array/slice and a function, call this function on every element of array/slice, then returns the results as a new slice, as such:
```go
// Map accepts an array/slice and a function, call function on every element
// and returns a new slice of results.
func Map(series interface{}, f interface{}) (interface{}, error) {
	st := reflect.TypeOf(series)
	sv := reflect.ValueOf(series)
	ft := reflect.TypeOf(f)
	fv := reflect.ValueOf(f)

	switch {
	case st.Kind() != reflect.Slice && st.Kind() != reflect.Array:
		return nil, ErrNotArrayOrSlice
	case ft.Kind() != reflect.Func:
		return nil, ErrNotFunc
	case ft.NumIn() != 1 || ft.NumOut() != 1:
		return nil, ErrFuncParam
	case ft.In(0).Kind() != st.Elem().Kind():
		return nil, ErrNotCompatible
	}

	mapped := reflect.MakeSlice(reflect.SliceOf(ft.Out(0)), 0, 0)
	for i := 0; i < sv.Len(); i++ {
		mapped = reflect.Append(mapped, fv.Call([]reflect.Value{sv.Index(i)})...)
	}

	return mapped.Interface(), nil
}
```
Then some unit tests:
```go
func TestMapSquare(t *testing.T) {
	ints := []int{1, 3, 5, 7, 9}
	expected := []int{1, 9, 25, 49, 81}

	result, err := Map(ints, func(x int) int { return x * x })
	if err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(result, expected) {
		t.Errorf("returned: %v, expected: %v", result, expected)
	}
}

func TestMapSqrt(t *testing.T) {
	floats := []float64{0.25, 1.0, 4.0, 9.0, 16.0}
	expected := []float64{0.5, 1.0, 2.0, 3.0, 4.0}

	result, err := Map(floats, math.Sqrt)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(result, expected) {
		t.Errorf("returned: %v, expected: %v", result, expected)
	}
}

func TestMapUppercase(t *testing.T) {
	strs := []string{"foo", "bar", "baz"}
	expected := []string{"FOO", "BAR", "BAZ"}

	result, err := Map(strs, strings.ToUpper)
	if err != nil {
		t.Fatal(err)
	}
	if reflect.DeepEqual(result, expected) {
		t.Errorf("returned: %v, expected: %v", result, expected)
	}
}
``` 

### What did you expect to see?
The tests about sqrt and square are just fine, but TestMapUppercase failed. I expect to see all the tests above passed.

### What did you see instead?
--- FAIL: TestMapUppercase (0.00s)
	coll_test.go:230: returned: [FOO BAR BAZ], expected: [FOO BAR BAZ]
FAIL
coverage: 49.4% of statements
exit status 1
FAIL	github.com/leesper/fun	0.001s

It seems strange that the returned slice is equal to what I expected, but reflect.DeepEual() returns false, I checked slice length, all the elements, they are the same. Is it a bug?

**Comment by Ganners** [comment]
Your line:

```
if reflect.DeepEqual(result, expected) {
```

should be

```
if !reflect.DeepEqual(result, expected) {
```

**Comment by davecheney** [comment]
Closing as there is nothing to fix.

**Comment by leesper** [comment]
Thank you @Ganners, Apologize to @robpike, @davecheney, I made a stupid mistake...I am really sorry.
