### ISSUE TITLE
bradfitz: core go developer is a large type asshole

### ISSUE THREAD

**Issue by basictruth** [golang/go#22338]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Issue is OS independent

### What did you do?
Tried to use golang in a fairly basic way, contribute feedback and be taken seriously.

### What did you expect to see?
Expected to see feedback being appreciated and taken seriously as is done for 99% of open source projects.

### What did you see instead?
Brad Fitzpatrick immediately closes tickets with snarky messages and claims the underlying issues are not problems at all, pretending like he could possibly see every good use for a project as vast as a programming language. Brad exemplifies the self righteous and obnoxious brat that many people imagine Google employees to be. Is he James Damore in disguise? After one too many run-ins with Brad and being told why we are "wrong", we have given up and are slowly replacing all our go code with rust and ruby.

**Comment by ALTree** [comment]
Please be nice. If you can reformulate your issue with the way the project is managed in a nicer way, I suggest you do so and then post on the golang-dev mailing list. 

Closing here, since this is not a Go bug.
