### ISSUE TITLE
cmd/gofmt: make gofmt always insert a blank line between functions

### ISSUE THREAD

**Issue by qinhanlei** [golang/go#22337]
### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What did you do?
I did gofmt on golang code as below.
```go
package main
import "fmt"
func foo() {

	fmt.Println("this is foo!")
	// ...
	// may lots codes here
	// ...

}
func bar() {

	fmt.Println("this is bar!")
	// ...
	// may lots codes here
	// ...

}
func main() {

	fmt.Println("hello, world")
	foo()

	bar()

}


```

### What did you expect to see?
```go
package main

import "fmt"

func foo() {
	fmt.Println("this is foo!")
	// ...
	// may lots codes here
	// ...
}

func bar() {
	fmt.Println("this is bar!")
	// ...
	// may lots codes here
	// ...
}

func main() {
	fmt.Println("hello, world")
	foo()

	bar()
}

```

### What did you see instead?
```go
package main

import "fmt"

func foo() {

	fmt.Println("this is foo!")
	// ...
	// may lots codes here
	// ...

}
func bar() {

	fmt.Println("this is bar!")
	// ...
	// may lots codes here
	// ...

}
func main() {

	fmt.Println("hello, world")
	foo()

	bar()

}

```

**Comment by ALTree** [comment]
cc @griesemer

**Comment by mvdan** [comment]
I'm not sure on the "always" part. For example, this sort of thing is useful:

```
func (n *Node) Noescape() bool { return n.flags&nodeNoescape != 0 }
func (n *Node) Bounded() bool  { return n.flags&nodeBounded != 0 }
func (n *Node) Addable() bool  { return n.flags&nodeAddable != 0 }
func (n *Node) HasCall() bool  { return n.flags&nodeHasCall != 0 }
func (n *Node) Likely() bool   { return n.flags&nodeLikely != 0 }
func (n *Node) HasVal() bool   { return n.flags&nodeHasVal != 0 }
func (n *Node) HasOpt() bool   { return n.flags&nodeHasOpt != 0 }
func (n *Node) Embedded() bool { return n.flags&nodeEmbedded != 0 }
```

**Comment by mvdan** [comment]
However, I would agree that it makes little sense to allow no empty line between two funcs if either is multi-line.

**Comment by griesemer** [comment]
This is working as intended. We went back and forth on this many times. The conclusion here is that gofmt respects the decision of the source author. Sometimes you have a situation with multiple one-liners where one of them, in the middle, spans multiple lines. We don't want to break that grouping; i.e., we want to keep all these functions together to express that they belong together.

There's lots of if's and when's etc. and there's just no good way to capture intent well, automatically. Better to let the author decide.
