### ISSUE TITLE
cmd/compile: -l=4 triggers "write barrier prohibited by caller; oneNewExtraM"

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22342]
$ go build -a -gcflags=-l=4 runtime
    # runtime
    ../src/runtime/proc.go:1655:10: write barrier prohibited by caller; oneNewExtraM
            /home/mdempsky/wd/go/src/runtime/proc.go:1618:16: called by newextram
            /home/mdempsky/wd/go/src/runtime/proc.go:1200:11: called by mstart1
            /home/mdempsky/wd/go/src/runtime/proc.go:1170:9: called by mstart

It's complaining about the `mp.curg = gp` asignment in oneNewExtraM. This is a pointer assignment, and type `runtime.g` is not labeled `go:notinheap`.

mstart is labeled `go:nowritebarrierrec`, and none of mstart1, newextram, or oneNewExtraM are labeled `go:yeswritebarrierrec`.

I suspect there's also a compiler bug here that this isn't being detected at -l=0, but filing as a runtime bug first for investigation.

/cc @aclements

**Comment by mdempsky** [comment]
Oh, nevermind, there's an mstartm0 call in between, which is labeled yeswritebarrierrec.

This is a compiler bug.

**Comment by aclements** [comment]
I attempted, and failed, to fix the general issue with losing function annotations during inlining in [CL 41152](https://golang.org/cl/41152) by disallowing inlining that would break function-level analysis. Besides not working, this was sort of an unfortunate approach. It would be much nicer if we could push the function annotations into inlining points and still analyze them correctly.
