### ISSUE TITLE
test/bench/go1: the go1 benchmark has large noise on arm/arm64 linux

### ISSUE THREAD

**Issue by benshi001** [golang/go#22348]
I tested commit 378de1ae43c6406ae5159f235f834da73403a541 twice on my RP2 board, and the results showed big variation.
1. up to +/- 13% variation in Gzip4
2. up to 20% variation in JSONDecode-4
3. -2.29% drop in FmtFprintfString-4 and 2.17% improvement in HTTPClientServer-4

	name                     old time/op    new time/op    delta
	BinaryTree17-4              42.3s ± 3%     42.0s ± 2%  -0.71%  (p=0.015 n=20+20)
	Fannkuch11-4                24.3s ± 3%     24.2s ± 3%    ~     (p=0.369 n=20+20)
	FmtFprintfEmpty-4           840ns ±13%     833ns ± 1%    ~     (p=0.892 n=16+17)
	FmtFprintfString-4         1.39µs ± 2%    1.35µs ± 2%  -2.29%  (p=0.000 n=18+17)
	FmtFprintfInt-4            1.43µs ± 3%    1.44µs ± 1%  +0.63%  (p=0.002 n=17+17)
	FmtFprintfIntInt-4         2.09µs ± 2%    2.10µs ± 1%  +0.79%  (p=0.005 n=18+17)
	FmtFprintfPrefixedInt-4    2.35µs ± 2%    2.33µs ± 2%  -0.59%  (p=0.021 n=16+18)
	FmtFprintfFloat-4          4.44µs ± 1%    4.45µs ± 1%    ~     (p=0.942 n=17+18)
	FmtManyArgs-4              8.26µs ± 2%    8.23µs ± 1%  -0.36%  (p=0.047 n=18+17)
	GobDecode-4                 103ms ± 5%     103ms ± 5%    ~     (p=0.987 n=18+17)
	GobEncode-4                95.3ms ± 2%    95.5ms ± 1%    ~     (p=0.202 n=17+15)
	Gzip-4                      4.27s ±13%     4.15s ± 2%  -2.86%  (p=0.000 n=17+17)
	Gunzip-4                    597ms ± 1%     596ms ± 1%    ~     (p=0.077 n=17+18)
	HTTPClientServer-4          690µs ± 3%     705µs ± 4%  +2.17%  (p=0.001 n=18+17)
	JSONEncode-4                241ms ± 4%     241ms ± 1%    ~     (p=0.935 n=17+18)
	JSONDecode-4                929ms ±20%     908ms ± 8%    ~     (p=0.901 n=17+16)
	Mandelbrot200-4            41.8ms ± 1%    41.8ms ± 1%    ~     (p=0.163 n=18+17)
	GoParse-4                  46.9ms ± 2%    47.2ms ± 2%    ~     (p=0.184 n=18+17)
	RegexpMatchEasy0_32-4      1.27µs ± 1%    1.27µs ± 1%    ~     (p=0.699 n=16+19)
	RegexpMatchEasy0_1K-4      7.90µs ± 6%    7.89µs ± 6%    ~     (p=0.942 n=18+20)
	RegexpMatchEasy1_32-4      1.29µs ± 3%    1.31µs ±12%    ~     (p=0.187 n=17+17)
	RegexpMatchEasy1_1K-4      10.5µs ±13%    10.4µs ± 4%    ~     (p=0.988 n=18+18)
	RegexpMatchMedium_32-4     1.95µs ± 2%    1.95µs ± 1%    ~     (p=0.341 n=17+16)
	RegexpMatchMedium_1K-4      504µs ± 3%     503µs ± 2%    ~     (p=0.661 n=17+19)
	RegexpMatchHard_32-4       26.6µs ± 1%    26.6µs ± 1%    ~     (p=1.000 n=17+17)
	RegexpMatchHard_1K-4        802µs ± 2%     801µs ± 3%    ~     (p=0.684 n=17+18)
	Revcomp-4                  73.4ms ± 3%    73.4ms ± 2%    ~     (p=0.935 n=18+17)
	Template-4                  1.08s ± 1%     1.07s ± 2%    ~     (p=0.339 n=17+17)
	TimeParse-4                6.86µs ± 1%    6.91µs ± 3%    ~     (p=0.084 n=17+18)
	TimeFormat-4               13.5µs ± 3%    13.3µs ± 1%  -0.87%  (p=0.012 n=18+17)
	TypePro-4                  1.02ms ± 2%    1.01ms ± 1%  -0.55%  (p=0.012 n=17+17)
	[Geo mean]                  726µs          724µs       -0.27%

	name                     old speed      new speed      delta
	GobDecode-4              7.48MB/s ± 5%  7.48MB/s ± 5%    ~     (p=0.954 n=18+17)
	GobEncode-4              8.06MB/s ± 2%  8.04MB/s ± 1%    ~     (p=0.240 n=17+15)
	Gzip-4                   4.52MB/s ±14%  4.68MB/s ± 2%  +3.68%  (p=0.000 n=18+17)
	Gunzip-4                 32.5MB/s ± 1%  32.6MB/s ± 1%    ~     (p=0.084 n=17+18)
	JSONEncode-4             8.05MB/s ± 4%  8.07MB/s ± 1%    ~     (p=0.954 n=17+18)
	JSONDecode-4             2.10MB/s ±17%  2.14MB/s ± 7%    ~     (p=0.964 n=17+16)
	GoParse-4                1.23MB/s ± 2%  1.23MB/s ± 2%    ~     (p=0.294 n=18+17)
	RegexpMatchEasy0_32-4    25.3MB/s ± 1%  25.2MB/s ± 1%    ~     (p=0.676 n=16+19)
	RegexpMatchEasy0_1K-4     130MB/s ± 5%   130MB/s ± 6%    ~     (p=0.942 n=18+20)
	RegexpMatchEasy1_32-4    24.9MB/s ± 3%  24.5MB/s ±11%    ~     (p=0.183 n=17+17)
	RegexpMatchEasy1_1K-4    97.5MB/s ±11%  98.9MB/s ± 3%    ~     (p=0.988 n=18+18)
	RegexpMatchMedium_32-4    511kB/s ± 2%   516kB/s ± 1%    ~     (p=0.109 n=17+16)
	RegexpMatchMedium_1K-4   2.03MB/s ± 3%  2.04MB/s ± 2%    ~     (p=0.368 n=17+19)
	RegexpMatchHard_32-4     1.20MB/s ± 2%  1.20MB/s ± 1%    ~     (p=0.135 n=18+17)
	RegexpMatchHard_1K-4     1.28MB/s ± 2%  1.28MB/s ± 2%    ~     (p=0.788 n=17+18)
	Revcomp-4                34.6MB/s ± 3%  34.6MB/s ± 2%    ~     (p=0.929 n=18+17)
	Template-4               1.80MB/s ± 1%  1.81MB/s ± 1%    ~     (p=0.567 n=17+17)
	[Geo mean]               6.81MB/s       6.84MB/s       +0.42%

**Comment by benshi001** [comment]
I have to do many rounds of contrast test (usually a whole night) to know the real impact of my changes.

**Comment by ianlancetaylor** [comment]
CC @randall77 @mdempsky @josharian

**Comment by benshi001** [comment]
The go1 benchmark also has large voice on RPI3/ArchLinux, several test cases even vary up to 3%.

**Comment by josharian** [comment]
Does anything in https://groups.google.com/forum/#!topic/golang-dev/hRH25vzWYyA/discussion help?

Also, do any previous Go releases exhibit lower variances with the same setup?
