### ISSUE TITLE
net: ipStackCapabilities.probe creates sockets that can escape into child process

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#22349]
Perhaps I am mistake. But ipStackCapabilities.probe calls socketFunc (which is just a syscall.Socket). Returned socket is inheritable by child process on Windows, so it can escape, if we call Windows CreateProcess at the same time.

Maybe this is expected, but I decided to report. Just in case.

Thank you.

CC @ianlancetaylor @mikioh

**Comment by alexbrainman** [comment]
@ianlancetaylor you marked this with OS-Windows label, but this affects pretty much everyone.

Alex

**Comment by ianlancetaylor** [comment]
Ah, so it does.  Sorry.
