### ISSUE TITLE
crypto/ssh: banner support update breaks connectivity

### ISSUE THREAD

**Issue by paultyng** [golang/go#22359]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.8.3

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux / amd64

### What did you do?

Connect via ssh to SFTP server.

Configuration code as follows:

```go
conn, err := ssh.Dial("tcp", addr, &ssh.ClientConfig{
  User: username,
  Auth: []ssh.AuthMethod{
    ssh.Password(password),
  },
  HostKeyCallback: ssh.InsecureIgnoreHostKey(),
})
```

### What did you expect to see?

No error

### What did you see instead?

When I upgrade to the most recent commit of golang/crypto@ed5229da99e3a6df35c756cd64b6982d19505d86 on the SSH package, I started getting errors when connecting to my SSH server using Password authentication.

Only tried against my existing server, but server version is `SSH-2.0-1.82_sshlib Globalscape`

Code errors out with `ssh: handshake failed: ssh: parse error in message type 53`

As soon as I roll back to the previous commit, it succeeds.

**Comment by ALTree** [comment]
Something similar was also reported here this morning: https://github.com/golang/go/issues/19567#issuecomment-338162014

cc  @tucksaun @hanwen

**Comment by hanwen** [comment]
the change has been rolled back in 2509b14
