### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by stoneMan1982** [golang/go#22354]
Please answer these questions before submitting your issue. Thanks!

I have defined a variable X in a package ,but when I compile a project that imports the package,the compiler prints errors like this: X undefined！！！

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
