### ISSUE TITLE
cmd/compile: bad error message from undefined type

### ISSUE THREAD

**Issue by opennota** [golang/go#22351]
### What version of Go are you using (`go version`)?

1.9.1 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/gocode"
GORACE=""
GOROOT="/home/user/go"
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build435907256=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

https://play.golang.org/p/Wzqy73f_Vb

### What did you expect to see?

main.go:5:34: undefined: T

### What did you see instead?

main.go:5:17: constant -1000000000 overflows uint64
main.go:5:34: undefined: T

**Comment by ianlancetaylor** [comment]
CC @mdempsky
