### ISSUE TITLE
Go 1.9.1: On Linux x86-64, cross-compiling a Windows x86-64 binary fails with errors compiling dll_windows.go, syscall.go, and syscall_windows.go

### ISSUE THREAD

**Issue by jeffkayser2** [golang/go#22368]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.9.1

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jkayser"
GORACE=""
GOROOT="/usr/local/go1.9.1"
GOTOOLDIR="/usr/local/go1.9.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build479622674=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
On a Linux x86_64 VM, I tried to cross-compile a binary for 64-bit Windows.  Using "gb" to do builds.

The compile works fine generating a 64-bit Linux binary:

[jkayser@oel7latest ErpIntSvc]$ gb build
objects/ValueCache
objects/ErpIntSvc
cmd/ErpIntSvc
[jkayser@oel7latest ErpIntSvc]$ 

but fails to build a 64-bit Windows binary.  I have done cross compiles using previous versions of Go, and they worked OK.

[jkayser@oel7latest ErpIntSvc]$ rm -rf pkg/
[jkayser@oel7latest ErpIntSvc]$ GOOS=windows GOARCH=amd64 gb build
crypto/subtle
internal/nettrace
errors
internal/race
runtime/internal/sys
unicode
unicode/utf8
internal/syscall/windows/sysdll
unicode/utf16
math/bits
container/list
crypto/internal/cipherhw
vendor/golang_org/x/crypto/curve25519
internal/cpu
runtime/internal/atomic
sync/atomic
vendor/golang_org/x/crypto/poly1305
math
strconv
runtime
sync
# syscall
dll_windows.go:24:6: missing function body for "Syscall"
dll_windows.go:25:6: missing function body for "Syscall6"
dll_windows.go:26:6: missing function body for "Syscall9"
dll_windows.go:27:6: missing function body for "Syscall12"
dll_windows.go:28:6: missing function body for "Syscall15"
dll_windows.go:29:6: missing function body for "loadlibrary"
dll_windows.go:30:6: missing function body for "loadsystemlibrary"
dll_windows.go:31:6: missing function body for "getprocaddress"
syscall.go:101:6: missing function body for "Getpagesize"
syscall_windows.go:121:6: missing function body for "compileCallback"
syscall_windows.go:121:6: too many errors
internal/singleflight
io
math/rand
crypto/rc4
encoding/base64
hash
crypto/cipher
bytes
reflect
crypto
crypto/hmac
vendor/golang_org/x/text/transform
bufio
strings
sort
encoding/binary
hash/crc32
crypto/aes
path
encoding/pem
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
crypto/des
crypto/sha512
crypto/md5
crypto/sha1
crypto/sha256
vendor/golang_org/x/crypto/chacha20poly1305
FATAL: command "build" failed: exit status 2
[jkayser@oel7latest ErpIntSvc]$ 

### What did you expect to see?
Go to generate a 64-bit Windows binary.

### What did you see instead?
An error (see above).

**Comment by ianlancetaylor** [comment]
This works for me using `go build`.  Are you sure this isn't related to gb in some way?

CC @davecheney

**Comment by jeffkayser2** [comment]
It is an issue with gb.  Sorry.  I did a build with the regular build tools -- it worked fine (see below).  I also updated gb, and then it worked fine too.  My bad,  Sorry.

[jkayser@oel7latest ~]$ cd projects/jibe/general/ErpIntSvc/
[jkayser@oel7latest ErpIntSvc]$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jkayser"
GORACE=""
GOROOT="/usr/local/go1.9.1"
GOTOOLDIR="/usr/local/go1.9.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build846962228=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
[jkayser@oel7latest ErpIntSvc]$ pwd
/home/jkayser/projects/jibe/general/ErpIntSvc
[jkayser@oel7latest ErpIntSvc]$ GOPATH=/home/jkayser/projects/jibe/general/ErpIntSvc:/home/jkayser
[jkayser@oel7latest ErpIntSvc]$ export GOPATH
[jkayser@oel7latest ErpIntSvc]$ cd src/cmd/ErpIntSvc/
[jkayser@oel7latest ErpIntSvc]$ go build
[jkayser@oel7latest ErpIntSvc]$ ls -l 
total 6064
-rwxrwxr-x. 1 jkayser jkayser 6192348 Oct 21 16:07 ErpIntSvc
-rw-rw-r--. 1 jkayser jkayser   15133 Oct 20 13:38 main.go
[jkayser@oel7latest ErpIntSvc]$ GOOS=windows GOARCH=amd64 go build
[jkayser@oel7latest ErpIntSvc]$ ls -l 
total 11912
-rwxrwxr-x. 1 jkayser jkayser 6192348 Oct 21 16:07 ErpIntSvc
-rwxrwxr-x. 1 jkayser jkayser 5984768 Oct 21 16:07 ErpIntSvc.exe
-rw-rw-r--. 1 jkayser jkayser   15133 Oct 20 13:38 main.go
[jkayser@oel7latest ErpIntSvc]$

**Comment by ianlancetaylor** [comment]
Thanks for following up.

**Comment by Baldomo** [comment]
I am having this issue as well, just that I'm using the regular build tools. `go env` is as follows:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leonardo/Documents/Go/webapi-dav/"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build938527727=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
`go build`'s output:
```
# syscall
/usr/lib/go-1.9/src/syscall/dll_windows.go:24:6: missing function body for "Syscall"
/usr/lib/go-1.9/src/syscall/dll_windows.go:25:6: missing function body for "Syscall6"
/usr/lib/go-1.9/src/syscall/dll_windows.go:26:6: missing function body for "Syscall9"
/usr/lib/go-1.9/src/syscall/dll_windows.go:27:6: missing function body for "Syscall12"
/usr/lib/go-1.9/src/syscall/dll_windows.go:28:6: missing function body for "Syscall15"
/usr/lib/go-1.9/src/syscall/dll_windows.go:29:6: missing function body for "loadlibrary"
/usr/lib/go-1.9/src/syscall/dll_windows.go:30:6: missing function body for "loadsystemlibrary"
/usr/lib/go-1.9/src/syscall/dll_windows.go:31:6: missing function body for "getprocaddress"
/usr/lib/go-1.9/src/syscall/syscall.go:101:6: missing function body for "Getpagesize"
/usr/lib/go-1.9/src/syscall/syscall_windows.go:121:6: missing function body for "compileCallback"
/usr/lib/go-1.9/src/syscall/syscall_windows.go:121:6: too many errors
An error has occurred! Aborting the script execution...
```
