### ISSUE TITLE
builtin: the prototype of the make function should be more consistent with new instead of len

### ISSUE THREAD

**Issue by go101** [golang/go#22362]
The prototypes of the three functions are
```
    func len(v Type) int
    func make(t Type, size ...IntegerType) Type
    func new(Type) *Type
```
Although these prototypes are only for documentation purpose, the first argument of `make` is more like a value instead of a type.

An alternative suggestion is to define a fake `ContainerType` type and modify the prototype of `len` as `func len(v ContainerType) int`

**Comment by robpike** [comment]
The words immediately after the prototype for make says Type must be one of slice, map, or chan. Nothing needs to change. The word Type is in turn a stand-in. Yes, it is defined to be any type but the words for make immediately refine its use there.

It would be unwise to introduce the word Container for this, which is not part of the Go documentation. It's a word used by a different kind of language.

**Comment by griesemer** [comment]
The first argument of make is a type, not a value. There is no bug here, and this is not a proper proposal either. Closing.

**Comment by go101** [comment]
> I also don't understand what you mean by the doc for make being inconsistent with len and new. 

The first arguments of len and make are both `Type`.
They give people the first impression that they are the same thing.
However one represents a value, the other represents a type.

**Comment by go101** [comment]
My original proposal is to remove the `t` in the prototype of `make`. Otherwise, I think the prototype should be `func make(t Type, size ...IntegerType) t` instead of `func make(t Type, size ...IntegerType) Type`.

**Comment by go101** [comment]
In fact, I have a third suggestion:
```
    func make(T type, size ...IntegerType) T
    func new(T type) *T
```
Here the `type` indicates the argument is a type.

I admit that this is a big problem.
Just try to make it perfect from the academic view.  :)

**Comment by griesemer** [comment]
@go101 Removing `t` from the signature of `make` would be syntactically incorrect: Either all parameters have a name or none of them does.

The `Type` stands for a type, any type. Conceivably, there's a type representing types. It doesn't exist in Go, but this package is just for illustration and serves as a reminder when looking up these functions via godoc. The spec has the final word.

I really don't see much to do here.

**Comment by go101** [comment]
Yes, it is not a big problem.
It is just some weird to look at these prototypes.
The two `Type` in the `make` prototype even represent two different kinds of things,

However, I understand the situation, by lacking general generic support in Go, it is really hard to make these prototypes academic perfect. ;)
