### ISSUE TITLE
cmd/go: enable TestNoteReading on ppc64x

### ISSUE THREAD

**Issue by mundaym** [golang/go#22360]
Part of TestNoteReading is disabled on ppc64 and ppc64le but the issue it links to is now closed (#11184).

I think TestNoteReading should now be fully enabled on ppc64le. If ppc64 doesn't work yet (not clear from the issue) we should probably change the issue number it references.

**Comment by laboger** [comment]
ppc64le has external linking, ppc64 does not. I'll try enabling it for ppc64le.
