### ISSUE TITLE
cmd/go: go commands close the cmd window on Windows

### ISSUE THREAD

**Issue by earneet** [golang/go#22373]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

just `go build xxx.go` or any `go command` but `go help`

#### What did you expect to see?
build, or any 

#### What did you see instead?
cmd window disappear !!! with out any message, no log

#### System details

```
go version go1.9 windows/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\Administrator\go"
GORACE=""
GOROOT="C:\Go"
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build806374615=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.9
gdb --version: GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
```

**Comment by ALTree** [comment]
With had a similar report a few weeks ago (#22121) and apparently it was a git problem: https://github.com/golang/go/issues/22121#issuecomment-334218002.

Can you update git and try again?

**Comment by earneet** [comment]
my git version is 2.14.2.windows.2

 i just try 'go env' in git bash,it works well, but cmd and powershell not


2017年10月21日星期六，Alberto Donizetti <notifications@github.com> 写道：

**Comment by alexbrainman** [comment]
@earneet 'go env' does not use Git, so 'go env' should work regardless what version of Git you have. Did you see my comment https://github.com/golang/go/issues/22121#issuecomment-334049488 ? Does it help you?

Alex

**Comment by earneet** [comment]
go version go 1. 9windows/amd64 and os version 1703 win 10 ent

it is works now ! but i didnt do anything !
e... just run go in cygwin bash it works well


2017年10月24日星期二，Alex Brainman <notifications@github.com> 写道：

**Comment by alexbrainman** [comment]
@earneet please close the issue, if there is nothing else to do here.

Thank you.

Alex
