### ISSUE TITLE
doc: document how to build a release from source (with race libraries, etc)

### ISSUE THREAD

**Issue by phemmer** [golang/go#22372]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.9.1 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/home/phemmer/.go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/phemmer/.go:/tmp/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build939950170=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
Tried to build a package with `go build --race`

### What did you expect to see?
successful build

### What did you see instead?
```
go install container/heap: open /usr/lib/go/pkg/linux_amd64_race/container/heap.a: permission denied
go install encoding/csv: open /usr/lib/go/pkg/linux_amd64_race/encoding/csv.a: permission denied
go install html: open /usr/lib/go/pkg/linux_amd64_race/html.a: permission denied
go install database/sql/driver: mkdir /usr/lib/go/pkg/linux_amd64_race/database: permission denied
go install expvar: open /usr/lib/go/pkg/linux_amd64_race/expvar.a: permission denied
go install archive/tar: mkdir /usr/lib/go/pkg/linux_amd64_race/archive/: permission denied
go install text/template/parse: mkdir /usr/lib/go/pkg/linux_amd64_race/text/template/: permission denied
```

### Additional information
It appears this is because the standard source installation (as documented here: https://golang.org/doc/install/source) does not install the race detector enabled versions of several standard lib packages:
```
# ls /usr/lib/go/pkg/linux_amd64_race/container/
list.a
```

However when I download the pre-built release (https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz from https://golang.org/dl/), the libs are present:
```
# ls go/pkg/linux_amd64_race/container/
heap.a  list.a  ring.a
```

**Comment by davecheney** [comment]
Hi @phemmer it looks to me like there is some problems with your go installation. I suspect that you may have overwritten one install with another, or have GOROOT set and pointing to a version of Go that you didn't build from source.

You are correct that the source build does not build the race version by default. Once you've sorted out the permission errors from your current install, you can build the race version with this command
```
go install -race -a std
```
But, please fix the problems with your source install first.

**Comment by phemmer** [comment]
I neither overwrote one version with another, nor have GOROOT set to a different version. The issue is that `/usr/lib/go` is a system-wide installation. Normal users do not have permissions to write to this path. The reason why go is even trying to write to this path is why this issue is created. If those files were present, `go build --race` would not be trying to create them.

**Comment by davecheney** [comment]
You said that you installed Go from source.  Can you please show exactly how you did this as it is unlikely that installing Go from source would place it in /usr/lib/go

**Comment by phemmer** [comment]
```
export GOROOT_FINAL=/usr/lib/go
export GOROOT_BOOTSTRAP=/usr/lib/go
cd go/src
./all.bash
sudo mv /usr/lib/go{,.old}
sudo cp -r ../ /usr/lib/go
```

**Comment by davecheney** [comment]
Thank you, that explains how your go install ended up in /usr/lib/go. 

The short answer is you should build the race runtime before moving the files as the Go tool expects to be able to write those files.

**Comment by phemmer** [comment]
Shouldn't either the documentation explain this, or the `all.bash` build these files?
Some OS distributions follow the build documentation which is how I hit this issue. And then when I went to reproduce by building manually I still hit the issue.
It is confusing to follow the "building from source" documentation and end up with something different than the binary release.

**Comment by davecheney** [comment]
I can see that argument. From my POV the source install assumes that you continue to have permission to write files to that location in the future. 

I wonder if there should be a specific documentation for how to reproduce the binary distro as there are more pieces than the race detector that are not built by all.bash. /cc @broady

**Comment by forskning** [comment]
Citing the mention of go1.9.1.linux-amd64.tar.gz earlier in this thread, that binary distribution represents one build.

There may however be other builds that are linux distribution specific, as in the 2nd link below.

https://github.com/golang/go/wiki/FileTreeDocumentation

http://nurmi-labs.blogspot.com/p/filetreedoc.html
a somewhat clipped version with tree format added

**Comment by forskning** [comment]
http://slackbuilds.org/repository/14.2/development/google-go-lang/

The above contains a .SlackBuild script which I modified for a build.

Apologies in advance, it check permissions on the extracted source by the way.

http://nurmi-labs.blogspot.com/2017/08/bootstrapping-go.html

Of curiosity if you also have gcc-go-5.3.0 installed, what's the location where those files are placed?

**Comment by Barthalion** [comment]
@davecheney Yes, that would be really appreciated. I wouldn't mind other pointers either, for example a link to how official Go binaries are built or which distributions are the closest to your artifacts.

(I'm the maintainer of Go in Arch.)

**Comment by forskning** [comment]
https://github.com/golang/go/issues/22041#issuecomment-342016497 

https://github.com/golang/go/issues/21662#issuecomment-340273822 

https://github.com/golang/go/issues/21917#issuecomment-340259765

I've recently updated the 386 files below.

These however do miss some of the file present in the 386 binary downloads. 

And, of course not all the files are located in $GOROOT.

http://nurmi-labs.blogspot.com/2017/08/bootstrapping-go.html

http://nurmi-labs.blogspot.com/p/filetreedoc.html

**Comment by rsc** [comment]
It may be much better to just suggest that people don't overwrite an existing install. Create a fresh one (move the old one out of the way, etc). We should probably update the docs to make that clear.

**Comment by Barthalion** [comment]
For the record, Arch ships shared and race libraries now.

**Comment by phemmer** [comment]
Just for posterity:

> It may be much better to just suggest that people don't overwrite an existing install. Create a fresh one (move the old one out of the way, etc).

That's not the issue here. You can see up above in the reproduction steps that the old installation was moved. The issue was that distributions were following the build documentation, and thus ending up with an install that was not the same as the binary release.

I haven't encountered this issue in years, so it's obviously been fixed in my distribution. But might still be relevant in other distros or situations.
