### ISSUE TITLE
UDP port change after while

### ISSUE THREAD

**Issue by farzadi** [golang/go#22374]
I used UDP for send and receive between 8 devices and port, some of them changed and couldn't receive and send messages between other devices 

what can I do to manage ports ?how can I know which port changed?why did this happen?

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
