### ISSUE TITLE
spec: rule about methods declaration

### ISSUE THREAD

**Issue by frojasg** [golang/go#22386]
If you write the following method:

```go
func (i int) method() {
	fmt.Printf("number: %d\n", i)
}
```
You get the following compilation error: `cannot define new methods on non-local type`. 
I looked in the language specification, and I couldn't find any rule regarding where you can't define a method. I was wondering if it's something worth documenting in the spec. Thanks! 

p.s. Shouldn't the error message be "cannot define new methods on **a** non-local type"?

**Comment by griesemer** [comment]
The spec is clear about this: "The type denoted by T is called the receiver base type; it must not be a pointer or interface type and it must be defined in the same package as the method."
(https://golang.org/ref/spec#Method_declarations)

This is working as intended.

PS: The error message could say "on **a** non-local type" but what we have is fine and its somewhat customary to be shorter in error messages than in usual prose.

**Comment by frojasg** [comment]
Thanks!
