### ISSUE TITLE
runtime: nowritebarrierrec doesn't cross systemstack

### ISSUE THREAD

**Issue by aclements** [golang/go#22384]
When a function is marked go:nowritebarrierrec in the runtime, the compiler recursively disallows write barriers in functions called from it. However, this static check doesn't know that `systemstack` calls its argument. Since this is quite common in the runtime, we're actually failing to catch several write barriers in prohibited places (I found this the hard way when I made the write barrier a little more picky). I believe all of these are technically benign, but for subtle reasons. I don't like relying on subtle reasons.

We should fix this analysis to understand `systemstack` and fix the bad write barriers in the runtime. I have most of this done already, but some of the write barriers are proving difficult to remove, so this issue is to track this work.

**Comment by mdempsky** [comment]
@aclements Do you have any thoughts on moving the interprocedural checks to a go/types-based checker? I'm wondering if that would be easier to maintain since the go/types API is better documented and also more stable.

The intraprocedural stuff seems easy enough to keep in the compiler (e.g., nothing escaping to the heap, disallowing write barriers in nowritebarrier functions), but the interprocedural stuff seems to cause us trouble.

**Comment by aclements** [comment]
@mdempsky, I'm not sure how that would work since it needs to know exactly where the compiler inserted write barriers, which go/types wouldn't know.

**Comment by mdempsky** [comment]
@aclements Ah, right, I was thinking for a second that we explicitly mark "//go:nowritebarrier" on all functions that can't use write barriers, but I forgot the entire point of "//go:nowritebarrierrec" is to avoid that.

I suppose the go/types checker could use compile -m (or whichever flag) output to identify which functions have write barriers, and feed that into its analysis.

**Comment by aclements** [comment]
I thought of another reason doing this in go/types would be difficult: we want to see the implicit runtime calls that operations like copy, panic, etc. get lowered to.

**Comment by mdempsky** [comment]
Yeah, I'm not thinking an exclusively go/types-based checker, but one that runs "compile -m" to first determine which functions contain write barriers (or whatever other interesting properties), and then go/types is used for understanding and validating the call graph.
