### ISSUE TITLE
cmd/compile: internal compiler error: method receiver, when missing function type on anonymous function

### ISSUE THREAD

**Issue by anisus** [golang/go#22389]
### What version of Go are you using (`go version`)?
go1.9.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
Missed typing the parameter type for an anonymous function which is using the same parameter name as a variable defined in surrounding function.

It is reproducible in play.golang.org

https://play.golang.org/p/AP3xRF11H4

### What did you expect to see?
No internal compiler error

### What did you see instead?
internal compiler error: method receiver

**Comment by ALTree** [comment]
Appears to be already fixed on tip

```
$ go version
go version go1.9 linux/amd64

$ go build test.go
# command-line-arguments
./test.go:16:14: f is not a type
./test.go:16:8: internal compiler error: method receiver

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
cmd/compile/internal/gc.Fatalf(0xb5dd44, 0xf, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:181 +0x230
cmd/compile/internal/gc.typecheck1(0xc4202f3800, 0x1, 0xc4202f3680)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:1285 +0x4a5d
cmd/compile/internal/gc.typecheck(0xc4202f3800, 0x1, 0xc4202f3680)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:201 +0x782
cmd/compile/internal/gc.typecheckslice(0xc420046d30, 0x2, 0x2, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:55 +0x54
cmd/compile/internal/gc.Main(0xb73f90)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:480 +0x1fd0
main.main()
	/usr/local/go/src/cmd/compile/main.go:49 +0x95

$ gotip version
go version devel +378de1ae43 Tue Oct 17 04:03:16 2017 +0000 linux/amd64

$ gotip build test.go
# command-line-arguments
./test.go:16:14: f is not a type
```

**Comment by odeke-em** [comment]
@mdempsky your CL https://go-review.googlesource.com/c/go/+/70850 and commit https://github.com/golang/go/commit/f3d4ff7ddc86d2e5f3318fbf8a897edae6da1379#diff-4e8331dc0915d867dc05240b929434de inadvertently fixed this issue. I'll mail a CL locking in a test for this issue and then we can close this issue.

**Comment by odeke-em** [comment]
Alright, closed with CL https://go-review.googlesource.com/c/go/+/74630 and commit https://github.com/golang/go/commit/0ba4eba8645258f5f2a572ded7c673d2c24c881e. Thanks for the report @anisus and for tracking it @ALTree
