### ISSUE TITLE
syscall: fs_nacl.go: Link needs to check if target exists

### ISSUE THREAD

**Issue by tenortim** [golang/go#22383]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Go playground using GOOS=nacl

### What did you do?
I was actually testing for race conditions (both Link and Rename are missing calls to lock
the filesystem for which I will create a separate issue), but there's actually no need to
run concurrent goroutines here. Simply attempting to Link(a, b) twice will corrupt the
internal filesystem by leaving two files but a link count of three.

See the stat output https://play.golang.org/p/GfxaxuqQIt

### What did you expect to see?
Any attempt to link to an existing file should fail with EEXIST

### What did you see instead?
Corrupted filesystem (two files, link count = 3).

**Comment by tenortim** [comment]
Suggested change, here, cribbing from the open code. Add:
```
_, _, err := fs.dirlookup(dp, elem)
if err == nil {
        return nil, EEXIST
}
```
before the call to fs.dirlink() at line 639

**Comment by bradfitz** [comment]
@tenortim, do you want to send a change? (and include a new test)

**Comment by tenortim** [comment]
@bradfitz Will do. Any pointers on how to test this (since it only lives in the NACL code)?

**Comment by bradfitz** [comment]
@tenortim, just add tests in package "net", or "os", or "syscall", wherever's convenient. You can protect it with runtime.GOOS == "nacl" if needed.

See the src/nacltest.bash test file for how to run the tests.

**Comment by tenortim** [comment]
Fix submitted.
Test added first and verified that it fails.
Fix added to fs_nacl.go. It's not tied to GOOS since it's a valid test regardless (though unlikely to fail on any other platform). The test is a modified copy of part of the existing rename tests.
Verified that the test passes both for the NaCl build and for linux x64.
