### ISSUE TITLE
encoding/asn1: Unmarshaling NumericString (ASN.1 Tag 18) unsupported

### ISSUE THREAD

**Issue by WineGecko** [golang/go#22396]
### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH=amd64
GOHOSTARCH=amd64
GOHOSTOS=windows

### What did you do?
I'm trying to unmarshal certificate IssuerName to pkix.RDNSequence
https://play.golang.org/p/NceOK3kaxA

### What did you expect to see?
Value 1024001434049 in OID 1.2.643.100.1
Value 004029017981 in OID 1.2.643.3.131.1.1

### What did you see instead?
nil in both oids

**Comment by WineGecko** [comment]
I've tried to solve the problem locally and had some success.
I've just add const TagNumericString   = 18 in encoding\asn1\common.go to ASN.1 tags list and add new case to parseField function, using existing parsePrintableString function.

**Comment by ianlancetaylor** [comment]
CC @agl

**Comment by agl** [comment]
(Request is reasonable. Unclear whether it'll happen before 1.10 though.)
