### ISSUE TITLE
Can't compile magento 2.2.0 sample data

### ISSUE THREAD

**Issue by duongquyet** [golang/go#22393]
I'm using magento 2.2.0 with sample data and it work fine. After i installed it, I try to compile code. But after compile code frontend show empty page and backend can't load.

Backend:
http://prntscr.com/h0u26p
Frontend:
http://prntscr.com/h0u2fg

I use Windows 8.1 Pro  64-bit and xampp 3.2.2. Please help.

Best regards,

DuongQuyet

**Comment by davecheney** [comment]
I’m sorry, you’ve raised an issue on the wrong issue tracker.

**Comment by duongquyet** [comment]
Thank you. Sorry
