### ISSUE TITLE
x/build: move packet builders

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#22407]
From Ed @ Packet (ed@packet.net):

We're again reorganizing our donated build hardware, this time to move and consolidate servers into a new "Works on Arm" rack in our New Jersey (EWR1) data center. We're happy to have now dedicated facilities for use for sponsored projects, thanks to support from Arm.

I've created a new machine and reserved it for your account. Unlike the equipment you are currently using, it has 96 cores and 32GB of memory (the existing machine has 128G). We think that it will perform just fine, but be aware that there's less memory in it, and you should plan accordingly.

As soon as it's convenient for you, please move your builds to this new hardware, and release the old 128G machine back to the regular pool. I'm hoping that this will be possible to do before the end of the month.
cc @andybons

**Comment by bradfitz** [comment]
Did you decrease the number of builder containers running on this host, now that it has less memory?

**Comment by adams-sarah** [comment]
No, I did not.

**Comment by bradfitz** [comment]
32 GB / 20 builders = 1.6 GB per build. I think that's still acceptable. We run some of the GCE VMs with that much memory.

So, nothing to do here.
