### ISSUE TITLE
net/http: TestCloseIdleConnections_h2 didn't close connection

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#22413]
Seen on linux-arm trybot that Ian run against CL 72592

https://storage.googleapis.com/go-build-log/af50a7e4/linux-arm_10535f18.log

```
2017/10/23 18:13:51 Dialing 127.0.0.1:33539
2017/10/23 18:13:51 Dialing 127.0.0.1:43143
2017/10/23 18:13:52 Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>
--- FAIL: TestCloseIdleConnections_h2 (0.08s)
	clientserver_test.go:1304: didn't close connection
FAIL
FAIL	net/http	11.269s
```

Alex

CC @tombergan if you are interested

**Comment by ianlancetaylor** [comment]
Another instance: https://storage.googleapis.com/go-build-log/882d593d/freebsd-amd64-110_86b5d076.log

**Comment by tombergan** [comment]
The test flakes every ~2 of 100000 runs. This started happening after https://golang.org/cl/70510 (or more correctly, https://golang.org/cl/71611). Before that CL, we did:

1. Get HEADERS with END_STREAM
2. Remove stream from ClientConn
3. Generate a Response with Body = noBody

After that CL, we do:

1. Get HEADERS with END_STREAM
2. Generate a Response with Body = noBody
3. Remove stream from ClientConn

TestCloseIdleConnections_h2 flakes when we call CloseIdleConnections between steps 2 and 3. Ideally, we should not remove a stream from the ClientConn until the user calls Response.Body.Close.

**Comment by mvdan** [comment]
Another: https://storage.googleapis.com/go-build-log/fd2d9f3d/linux-amd64-race_9bf28e55.log

**Comment by bradfitz** [comment]
Another: https://build.golang.org/log/9a2ea5a6a70fc22f4f6561abb2d3229afca0a312
