### ISSUE TITLE
runtime: fatal error: span has no free stacks

### ISSUE THREAD

**Issue by carlory** [golang/go#22412]
docker daemon process crashed when creating a new goroutine.

- kernel: mm/memory.c:409: bad pmd ffff881055775210(80000006ad4008e7)
- dockerd: fatal error: span has no free stacks
- systemd: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT

### What version of Go are you using (`go version`)?

1.7.5

### What did you see instead?

[realted moby issue](https://github.com/moby/moby/issues/35266)

**Comment by carlory** [comment]
I don't know the reason why x.ptr is an empty pointer. Maybe this a hardware fault or other? 
 
```go
// Allocates a stack from the free pool. Must be called with
// stackpoolmu held.
func stackpoolalloc(order uint8) gclinkptr {
	list := &stackpool[order]
	s := list.first
	if s == nil {
		// no free stacks. Allocate another span worth.
		s = mheap_.allocManual(_StackCacheSize>>_PageShift, &memstats.stacks_inuse)
		if s == nil {
			throw("out of memory")
		}
		if s.allocCount != 0 {
			throw("bad allocCount")
		}
		if s.manualFreeList.ptr() != nil {
			throw("bad manualFreeList")
		}
		s.elemsize = _FixedStack << order
		for i := uintptr(0); i < _StackCacheSize; i += s.elemsize {
			x := gclinkptr(s.base() + i)
			x.ptr().next = s.manualFreeList
			s.manualFreeList = x
		}
		list.insert(s)
	}
	x := s.manualFreeList
	if x.ptr() == nil {
		throw("span has no free stacks")
	}
	s.manualFreeList = x.ptr().next
	s.allocCount++
	if s.manualFreeList.ptr() == nil {
		// all stacks in s are allocated.
		list.remove(s)
	}
	return x
}

```

**Comment by ianlancetaylor** [comment]
Is this reproducible?

Is it possible to try the 1.9.1 release?

**Comment by carlory** [comment]
Sorry, this issue happens only occasionally, so it's hard for me to reproduce.

tomorrow, I will check if the system RAM is faulty.

**Comment by carlory** [comment]
About kernel: mm/memory.c:409: bad pmd ffff881055775210(80000006ad4008e7)

@ianlancetaylor I found a similar unsolved issue in the [bugs list](https://bugs.centos.org/view.php?id=13742)

**Comment by aclements** [comment]
@carlory, this sounds like a kernel or hardware issue.

You gave several errors in your original report, and I'm not sure how to interpret that. Did these all happen at once? Or are these multiple failures that happened at different times?

What exact kernel version were you running?
