### ISSUE TITLE
x/build/cmd/gopherbot: properly link gddo CLs to the gddo issue tracker

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#22428]
It would be nice to have gerritbot also link gddo issues (in addition to golang/go issues).

Eg. a CL with the phrase:
Updates golang/gddo#520
in the commit message should have a link to 
https://github.com/golang/gddo/issues/520

But it does not. The current behavior is to link to golang/go#520.
See this CL as an example: 
https://go-review.googlesource.com/c/gddo/+/73031

If this is deemed unnecessary, we should at least remove the link to the golang/go#520.

cc @andybons @shantuo

**Comment by forskning** [comment]
https://go-review.googlesource.com/c/gddo/+/73031

https://go-review.googlesource.com/c/oauth2/+/24946

Try saving the above webpages, run a grep for 520 on the former, for 11811 on the latter, and see what happens.

**Comment by forskning** [comment]
CC @bradfitz

As you're the Owner of the 2nd CL is the last Comment perhaps you would be inclined to chip in.

cf: https://github.com/golang/scratch/issues/1

The scratch sub-repository by the way has a dummy issue.

Below is a presumed accurate list of sub-repositories, those with an Issues tab are marked. 

☐ sys
☒ dep
☐ build
☐ tools
☐ crypto
☐ proposal
☐ text
☐ net
☐ mobile
☒ scratch
☒ protobuf
☒ oauth2
☐ gofrontend
☒ mock
☒ tour
☐ blog
☒ gddo
☒ lint
☐ image
☒ appengine
☐ review
☒ cwg
☐ arch
☐ exp
☐ time
☐ term
☐ sync
☐ perf
☒ geo
☐ playground
☐ debug
☐ example
☒ snappy
☒ groupcache
☐ talks
☐ glog
☒ freetype
☒ sublime-build
☐ benchmarks
☒ leveldb
☒ winstrap
☒ sublime-config

**Comment by andybons** [comment]
> The scratch sub-repository by the way has a dummy issue.

This is OK as the scratch repo is used for testing with our infrastructure in some cases.

**Comment by forskning** [comment]
@andybons

https://help.github.com/articles/disabling-issues/

So the presumption is that for the unmarked subrepos that issues have been turned off.

**Comment by kevinburke** [comment]
This is a dupe of #21072.

**Comment by adams-sarah** [comment]
Thanks Kevin
