### ISSUE TITLE
cmd/compile: "can't find import" error due to race during concurrent build

### ISSUE THREAD

**Issue by bassam** [golang/go#22423]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```go version go1.9.1 linux/amd64```

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rook/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
on a machine with 16 cores (like a c4.4xlarge instance in EC2) I run the [`rook`](https://github.com/rook/rook) build system as follows:

```
git clone https://github.com/rook/rook
make distclean
build/run make -j16 build.all V=1 | tee build.log
```

### What did you expect to see?
I expect the build to succeed every time.

### What did you see instead?
Instead, I see intermittent errors that look like a race in the go build process. For example:

```
# github.com/rook/rook/vendor/k8s.io/api/autoscaling/v1
vendor/k8s.io/api/autoscaling/v1/types.go:20:2: can't find import: "github.com/rook/rook/vendor/k8s.io/api/core/v1"
mkdir -p /home/rook/go/pkg/linux_arm64_static/github.com/rook/rook/vendor/k8s.io/api/core/
cp $WORK/github.com/rook/rook/vendor/k8s.io/api/core/v1.a /home/rook/go/pkg/linux_arm64_static/github.com/rook/rook/vendor/k8s.io/api/core/v1.a
```

Note that the `cp` command happened after the `can't find import` error.

**Comment by bassam** [comment]
Note that our build system runs concurrent `go build` from the makefile. Not sure if this is causing `.a` packages to be removed form the file system and resulting in errors like the `can't import`

**Comment by ALTree** [comment]
Easy to test if this an issue in your makefile: [force sequential compilation](https://golang.org/doc/go1.9#parallel-compile) in the Go compiler. Does the error go away?

**Comment by bassam** [comment]
@ALTree with `export GO19CONCURRENTCOMPILATION=0` and after 5 builds I've not seen the build error. Note however that we are running concurrent `go build` commands for the same platform and they might be attempting to build similar import packages. Is this a supported scenario?

Looking at the [copyFile function](https://github.com/golang/go/blob/7dcf406cfea0dd1f84fed0c69d3472b21e1c490d/src/cmd/go/internal/work/exec.go#L770) I see that it attempts to remove the file before copying. I can't imagine this being safe to do when concurrent builds of `go build` are running and import the same packages.

I'm going to change our makefile to only run concurrently across build platforms, and sequentially within a build platform. I'll report back here.

**Comment by ianlancetaylor** [comment]
Running concurrent `go build` commands in the same `GOPATH` is clearly unsafe.  Don't do that.

**Comment by bassam** [comment]
@ianlancetaylor yes I see why now. Fixed our makefile to avoid that. Thanks!
