### ISSUE TITLE
go/doc: fails to strip RHS values from associated unexported identifier

### ISSUE THREAD

**Issue by dsnet** [golang/go#22426]
Consider the following snippet:
```go
const code = `package foo
const (
	c1, C2, c3 = 1, 2, 3
	C4, c5, C6 = 4, 5, 6
	c7, C8, c9 = 7, 8, 9
)`

fset := token.NewFileSet()
pkgFiles := make(map[string]*ast.File)
astFile, _ := parser.ParseFile(fset, "", code, parser.ParseComments)
pkgFiles[""] = astFile
astPkg, _ := ast.NewPackage(fset, pkgFiles, nil, nil)
docPkg := doc.New(astPkg, "foo", 0)
format.Node(os.Stdout, fset, docPkg.Consts[0].Decl)
```

This currently prints:
```
const (
	C2     = 1, 2, 3
	C4, C6 = 4, 5, 6
	C8     = 7, 8, 9
)
```

I expect this to print:
```
const (
	C2     = 2
	C4, C6 = 4, 6
	C8     = 8
)
```

Package `foo` contains 3 constants, only 1 of which is exported. When creating a `doc.Package`, the `doc` package fails to strip the values from the right hand side of the value, leading to a strange declaration.

\cc @griesemer

**Comment by griesemer** [comment]
Nice. An extra thing to consider when fixing this is the situation
```
var a, B, c = F()
```
where F returns three values (https://play.golang.org/p/qKhvm3E9rp). How do you want to handle that case? Maybe
```
var _, B, _ = F()
```
?

**Comment by dsnet** [comment]
> How do you want to handle that case? Maybe `var _, B, _ = F()`

That looks entirely reasonable.

**Comment by dsnet** [comment]
Pushing to Go1.11 since this bug has been present for a while.
