### ISSUE TITLE
cmd/compile: invalid instruction error for FMOVD when compiling for 387

### ISSUE THREAD

**Issue by TheTincho** [golang/go#22429]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.9.1 linux/386`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="387"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build059883492=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
### What did you do?

I did not try to isolate a minimal test case, as I have no idea what is going on. But at least one package in Debian is failing to build because of this (prometheus).

When compiling the tests, [this line](https://anonscm.debian.org/cgit/pkg-go/packages/prometheus.git/tree/storage/local/storage_test.go#n2026) fails with the following error:

```
$ GOPATH=$PWD/build go test -c -v github.com/prometheus/prometheus/storage/local
# github.com/prometheus/prometheus/storage/local
build/src/github.com/prometheus/prometheus/storage/local/storage_test.go:2026:26: invalid instruction: 01483 (/tmp/buildd/prometheus-1.8.1+ds/build/src/github.com/prometheus/prometheus/storage/local/storage_test.go:2027) FMOVD ""..autotmp_78+176(DX)(SP*1), F0
```

I can't reproduce this problem with go 1.7 or 1.8 from Debian. Disabling optimisations with `-gcflags=-N` seems to solve the issue.

Looking at #21860, I guess that this could something else than an "invalid instruction", but I have no idea :-)

**Comment by randall77** [comment]
@TheTincho I'm having trouble reproducing this.  There is no `local` directory in `github.com/prometheus/prometheus/storage`.
Could you make that available somehow?

**Comment by ALTree** [comment]
@randall77 

```
$ go get github.com/prometheus/prometheus/cmd/...
$ cd $GOPATH/src/github.com/prometheus/prometheus
$ git checkout release-1.8
$ cat VERSION 
1.8.1  # this is the version that appears in the error log above
```

I can't reproduce this, anyway:

```
$ GOARCH=386 go test -c -v github.com/prometheus/prometheus/storage/local
```

the command succeeds and the generated binary runs fine. Not sure what I'm doing wrong.

**Comment by randall77** [comment]
I can't reproduce yet, but I think I know what is wrong.
The compiler is using SP as an index register in an instruction.  That's a no-no in x86 world.
I've seen this before, and we have fixes for it.  Maybe those fixes aren't complete for 387?

Normally this happens for ops with indexed addressing mode, and scale==1.  Then the order of the base and index registers don't matter to SSA, so they can appear in either order.  We have code to swap them during assembly generation, like this (from amd64/ssa.go):
```
		r := v.Args[0].Reg()
		i := v.Args[1].Reg()
		if i == x86.REG_SP {
			r, i = i, r
		}
```
I'll prepare a CL.  It would be nice to be able to reproduce the OP's problem so we can be sure it is fixed.

**Comment by randall77** [comment]
@TheTincho I've uploaded a patch.  If you can, please try it and let us know if it fixes your issue.

**Comment by randall77** [comment]
I concocted a stand-alone repro and added it to the patch.

**Comment by randall77** [comment]
Reopening for 1.9.3.

**Comment by TheTincho** [comment]
Thank you all for looking at this so quickly!

@randall77: Like @ALTree said, this is from the 1.8 branch, that's why you were missing the package. And about the non-reproducibility, maybe something is slightly different because of our patches in Debian.. 

In any case, I am now rebuilding the golang-go Debian package with this patch, to see if the problem is solved.

**Comment by TheTincho** [comment]
Confirmed, this solves the issue. Thanks!!

**Comment by andybons** [comment]
go1.9.3 has been packaged and includes:

  - [CL 73551](https://golang.org/cl/73551) cmd/compile: make sure not to use SP as an index register

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Jan 22 21:02:54 UTC
