### ISSUE TITLE
io: flatten nested MultiWriters

### ISSUE THREAD

**Issue by crunk1** [golang/go#22431]
### What version of Go are you using (`go version`)?
1.9.1

The rest of the issue template questions aren't that relevant. 

The source code shows that nested MultiReaders flatten. Can we have the same for MultiWriters?

My use case is, without going into too much detail, sporadically adding io.Writers to a log.Logger. I have created an extendable Writer that can add new Writers, but it works by nesting MultiWriters. I don't anticipate having a ton of layers, but I think strategic flattening would save some computational overhead.

**Comment by ianlancetaylor** [comment]
I'm going to drop this out of the proposal process.  I think it's fine if someone wants to repeat https://golang.org/cl/17873 for `MultiWriter`.
