### ISSUE TITLE
x/net/http2: connection reused with DisableKeepAlives

### ISSUE THREAD

**Issue by benburkert** [golang/go#22441]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/benburkert"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qs/qkt9twmx4qg379d6f8kxl1vm0000gn/T/go-build568362356=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Send multiple requests to the same h2 server with keep alives disabled.

https://play.golang.org/p/sxjh2Yq-hg

### What did you expect to see?

no output because connections are not used across requests.

### What did you see instead?

```
connection reused: "[::1]:61658"
connection reused: "[::1]:61658"
connection reused: "[::1]:61658"
connection reused: "[::1]:61658"
connection reused: "[::1]:61661"
connection reused: "[::1]:61665"
connection reused: "[::1]:61668"
connection reused: "[::1]:61668"
connection reused: "[::1]:61668"
connection reused: "[::1]:61668"
connection reused: "[::1]:61671"
```

**Comment by ianlancetaylor** [comment]
CC @tombergan

**Comment by tombergan** [comment]
Might be related to #22413

**Comment by tombergan** [comment]
https://golang.org/cl/33153 was wrong. When keep alives are disabled, we don't start graceful shutdown (i.e., send GOAWAY) until the first request completes. We should actually start graceful shutdown on receiving the first request.

**Comment by tombergan** [comment]
Actually, this is WAI according to https://golang.org/cl/33153:
https://go-review.googlesource.com/c/net/+/33153/1/http2/server.go#1281

> > I don't think this gets all the cases. What if the client sends a second request before the first completes?
> 
> I think that's fine. It's supposed to be close-ish in behavior. I figure that the user's intention was probably to minimize open connections, closing them as soon as possible. So if their goal is to minimize conns, it's better to support reusing one conn for multiple requests.

@benburkert, what are you trying to achieve by disabling keep alives on HTTP/2? This feature happened in #17717 where Brad was trying to give meaning to SetKeepAlivesEnabled for HTTP/2. In all honesty it's kind of weird for the HTTP/2 library to support this option, since "keep alives" are an HTTP/1 that doesn't translate to HTTP/2.

**Comment by tombergan** [comment]
Removing the 1.10 milestone since there is no bug that I can see. I will leave this open in state WaitingForInfo in case @benburkert wants to respond to the above question.
