### ISSUE TITLE
os: misleading document

### ISSUE THREAD

**Issue by bronze1man** [golang/go#22454]
### What did you do?
review code in https://github.com/golang/go/blob/master/src/os/exec_posix.go#L13
https://github.com/golang/go/blob/master/src/os/exec_windows.go#L71

### What did you expect to see?
os.Interrupt can not send in windows system. it will return a error message with "not supported by windows" 

### What did you see instead?
```
// The only signal values guaranteed to be present on all systems
// are Interrupt (send the process an interrupt) and Kill (force
// the process to exit).
```
os.Process.Signal says:
```
// Signal sends a signal to the Process.
// Sending Interrupt on Windows is not implemented.
```

os.Process.Signal says about this,but it was not on the os.Interrupt which misleading me to think that os.Process.Signal(os.Interrupt) is working on windows.

**Comment by opennota** [comment]
There's a TODO: `// TODO(rsc): Handle Interrupt too?`

Does Windows support SIGINT?

/cc @rsc

**Comment by alexbrainman** [comment]
> Does Windows support SIGINT?

I searched this issue list for SIGINT and I find #7479 and #17608 that probably relate to this.

Alex

**Comment by crvv** [comment]
I think the document is not misleading.

```
// The only signal values guaranteed to be present on all systems
// are Interrupt ......
```
So Windows does support SIGINT.

```
// Sending Interrupt on Windows is not implemented.
```
Go doesn't support sending SIGINT on Windows.
It hasn't been implemented yet, and it may be supported in the future.
