### ISSUE TITLE
Version Discrepancy 

### ISSUE THREAD

**Issue by olekukonko** [golang/go#22453]
I guess the version was on updated on darwin/amd64

### What did you do?

```
➜  tmp wget https://redirector.gvt1.com/edgedl/go/go1.9.2.darwin-amd64.tar.gz
➜  tmp ls
go1.9.2.darwin-amd64.tar.gz
➜  tmp sudo tar -C /usr/local -xzf go1.9.2.darwin-amd64.tar.gz
➜  tmp go version
```

### What did you expect to see?
```
go version go1.9.2 darwin/amd64
```

### What did you see instead?
```
go version go1.9.1 darwin/amd64
```

<img width="569" alt="screen shot 2017-10-26 at 11 32 39 am" src="https://user-images.githubusercontent.com/2615393/32048645-1bbf1cd2-ba42-11e7-8edd-bb0ef8a0b8d3.png">

**Comment by dominikh** [comment]
Output of `which go`?

**Comment by myitcv** [comment]
I can't reproduce this. I suspect your `go version` command is picking up `go` from elsewhere on your `PATH` (it's unusual to have `$PWD` on your `PATH` so unless you added the `bin` directory of the untarred download to your `PATH` you're almost certainly running a different `go` binary):

```bash
cd `mktemp -d`
wget https://redirector.gvt1.com/edgedl/go/go1.9.2.darwin-amd64.tar.gz
tar -zxvf go1.9.2.darwin-amd64.tar.gz
./go/bin/go version
```

gives:

```
go version go1.9.2 darwin/amd64
```

**Comment by olekukonko** [comment]
@myitcv you are right they where 2 version one located 

- /usr/local/go/bin/go
- /usr/local/bin/go

Thanks ...
