### ISSUE TITLE
x/crypto/acme: Client.GetAuthorization should return also `Retry-After` value

### ISSUE THREAD

**Issue by tnozicka** [golang/go#22457]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tnozicka/go"
GORACE=""
GOROOT="/home/tnozicka/lib/go"
GOTOOLDIR="/home/tnozicka/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118198130=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Request
This function

https://github.com/golang/crypto/blob/541b9d50ad47e36efd8fb423e938e59ff1691f68/acme/acme.go#L355-L369

should return `Retry-After` as is used in

https://github.com/golang/crypto/blob/541b9d50ad47e36efd8fb423e938e59ff1691f68/acme/acme.go#L415

or there should be similar function that does return it.

I have a work queue and want to know at what time should I re-queue my object and I can't use active waiting as with the former function.

**Comment by x1ddos** [comment]
@tnozicka how would you propose for `GetAuthorization` method to return the  retry-after value?

**Comment by tnozicka** [comment]
@x1ddos A) seems nice but I don't really care that much except for having the value available

A) Extend `Authorization` struct (there is already `Status` inside)
```go
type Authorization struct {
    // ...
    RetryAfter *time.Duration
}
```
B) Change return type
```go
func (c *Client) GetAuthorization(ctx context.Context, url string) (*Authorization, error) {/* ... */}
// to
func (c *Client) GetAuthorization(ctx context.Context, url string) (*Authorization, retryAfter time.Duration, error) {/* ... */}
```
C) Second function if you want to avoid API change
```go
func (c *Client) GetAuthorizationWithRetryTime(ctx context.Context, url string) (*Authorization, retryAfter time.Duration, error) {
    /* ... */
}

func (c *Client) GetAuthorization(ctx context.Context, url string) (*Authorization, error) {
    a, _, err := GetAuthorizationWithRetryTime(ctx, url)
    return a, err
}
```

**Comment by x1ddos** [comment]
@tnozicka [acme.Client](https://godoc.org/golang.org/x/crypto/acme#Client) now has `RetryBackoff` field, which should allow for both access to `Retry-After` and have your own implementation of a retry backoff in methods like `WaitAuthorization`.

Would you now consider this issue fixed?

**Comment by andybons** [comment]
Closing since no response from original reporter.
