### ISSUE TITLE
text/template (and html/template) design is utterly ugly

### ISSUE THREAD

**Issue by z08840** [golang/go#22466]
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
I suppose so

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
First issue:
Let's say we want to initialize template with functions (Funcs) and parse and execute from file. First of all we can't do this:
```
t, _ := template.ParseFiles("example.tmpl")
t.Funcs(funcMap).Execute(wr, nil)
```
because Funcs should be set before Parse.
So, we do next:
`t, _ := template.New("test").Funcs(funcMap).ParseFiles("example.tmpl")`
but this will create two named templates - "test" and "example.tmpl" (it's already ugly since we don't need template "test"), so we can't just call Execute - it will attempt to execute not prepared "test" - we have to use ExecuteTemplate("example.tmpl") - and it's where arises the
Second issue:
ParseFiles creates templates with names as base filename of provided full path - this issue parts in two sub-issues -
first:
consider the file path was provided as an argument:
```
import "path"
....
t, _ := template.New("test").Funcs(funcMap).ParseFiles(file_path)
....
t.ExecuteTemplate(wr, path.Base(file_path), nil)
```
it's utterly ugly! Besides, if we want to execute template some later, we have to preserve either file_path or template name along with template object t - despite we use it with only one template. This situation can be mitigated a little bit like so:
```
import "path"
....
t, _ := template.New(path.Base(file_path)).Funcs(funcMap).ParseFiles(file_path)
....
t.Execute(wr, nil)
```
but again - it still ugly, and essentially New creates template with file base name, and then ParseFiles creates one more template, but since names are the same - it rewrites template created by New. And there comes sub-issue
second:
we cannot load multiple files from different directories but with the same base name:
`template.ParseFiles("example.tmpl", "aaa/example.tmpl", "bbb/example.tmpl")`
will create only one template from last file "bbb/example.tmpl" with name "example.tmpl" - it's utterly confusing.

### What did you expect to see?
Meaningful interface.

### What did you see instead?
Total disaster.

**Comment by ianlancetaylor** [comment]
This issue is not actionable.  The Go 1 compatibility guarantee means that we can't make fundamental changes to how these packages work.  I encourage you to write your own templating package that works as you prefer, and see if people will use that.  That should be discussed on a forum such as golang-nuts, not in the issue tracker.  See https://golang.org/wiki/Questions .

As a side note, if you want people to make changes, avoid using phrases like "total disaster."  If you just want to complain, please don't use the issue tracker.  Thanks.

Closing because there is nothing to do.
