### ISSUE TITLE
runtime: optimize write barrier

### ISSUE THREAD

**Issue by aclements** [golang/go#22460]
This issue is to track work on optimizing the write barrier.

Our current write barrier is fairly inefficient simply because not much effort has been put into optimizing it. For most applications, the write barrier has little overhead simply because it's rarely enabled. However, for some applications (e.g., the compiler) it consumes a few percent of the CPU. Furthermore, to fix #14951, we have to reduce the CPU consumed by GC, which necessarily means that GC and the write barrier will be enabled more of the time, increasing the impact of write barrier overhead.

I propose switching to a "buffered" write barrier, in which a fast path simply enqueues the necessary pointers to a per-P buffer. This fast path can be done without a normal Go call, avoiding the cost of spilling registers around the write barrier. When the buffer fills up, the write barrier will enter the slow path, which will spill *all* registers and enter the runtime to flush the buffer. We can disallow stack splits and safe-points during flushing so we don't need type information for the spilled registers.

I've already implemented this for the single pointer barrier on amd64. It's ~4X faster than the current barrier, speeds up GC-heavy applications by ~2%, and reduces binary size by ~1.5%. I haven't yet implemented it for other architectures, or used these techniques to improve the bulk write barriers.

/cc @RLH @josharian

**Comment by randall77** [comment]
I'm surprised this made the binaries smaller.  Instead of conditional + call, there's now two conditionals (WB enabled, queue full), enqueue, and call.
Is the space savings because the compiler no longer needs to insert spill/restore around the call?

**Comment by aclements** [comment]
There's still only one conditional in the generated code. The queue full test is in the runtime.

The space savings does appear to be from avoiding the spill/restore around the call.

**Comment by randall77** [comment]
Sorry, I thought you were going to enqueue in generated code.  Something like:
```
// slot in R0, ptr in R1, m in R2
CMP runtime.writeBarrier.needed(SB), $0
BEQ nowb
MOVQ qLen(R2), R3
CMPQ R3, $qLenMax
BEQ full
MOVQ (R0), R4
MOVQ R1, q(R2, R3*8)  // save ptr
MOVQ R4, q+8(R2, R3*8) // save old value in slot
ADDQ $2, R3
MOVQ R3, qLen(R2)
nowb:
MOVQ R1, (R0)
```
And `full` calls into the runtime.

**Comment by aclements** [comment]
That's certainly possible. I went with calling into the runtime for a few reasons: the fast path is still enough code that I was worried about binary bloat, without the spills or stack writes I figured the CALL was probably virtually free, and it was easier for me. :)

It could be worth revisiting, though at this point I think the write barrier might be fast enough that it doesn't matter.

**Comment by aclements** [comment]
Another possible optimization worth revisiting in the future: *always* enqueue to the buffer, even if the write barrier is disabled, and only check whether the write barrier is enabled in the slow path.

One possible complication with this would be during early runtime init, before there's a P. That would have to be nowrtiebarrierrec, and I found out this week (the hard way) that it definitely has some write barriers in it. We might be able to improve that complication by setting up a P just for its buffer really early during init. Or, I was considering caching a pointer to the buffer in the G anyway, and then it would be easy to point g0 to a temporary buffer during init.
