### ISSUE TITLE
Install go from offical pkg cannot work

### ISSUE THREAD

**Issue by Rukeith** [golang/go#22470]
### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Mac 10.13 High Sierra

### What did you do?
Install pkg from offical website, and run `go version`

### What did you expect to see?
show up golang version

### What did you see instead?
`zsh: command not found: go`

**Comment by mvdan** [comment]
Are you sure you installed Go properly? Exactly what method did you follow?

**Comment by liuzhiwang** [comment]
echo $PATH

**Comment by forskning** [comment]
https://golang.org/doc/install#osx

Does the package installer put the /usr/local/go/bin directory in your PATH environment variable for zsh?

**Comment by Rukeith** [comment]
@mvdan I sure I download the mac pkg from website and install it without error.
@forskning the PATH had set up, but when I run `go get`, it show `can't load package: package .: no Go files in /Users/RukeithTseng`

**Comment by forskning** [comment]
Typing go in the shell and pressing Return outputs the usage information for the executable.

In https://github.com/golang/go/issues/22470#issue-269150870 it's inferred that you had typed go with the command version, and that the shell you were using couldn't locate the go executable, in https://github.com/golang/go/issues/22470#issuecomment-340071497 it's inferred that you had typed go with the command get, but had not after the command entered any arguments.

https://golang.org/doc/install/source#testing

mkdir -p $GOPATH/src/hello

cd $GOPATH/src/hello

therein create a hello.go file

then run the go executable, command, and argument

go run hello.go

If you see the "hello, world" message, the install from the offical pkg work's (on Mac 10.13 High Sierra), and a Member can then close this issue.

NB: We don't use the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Comment by Rukeith** [comment]
@forskning Thank your reply, I am new to be a gopher. I use many ways to install go.
hello.go work, I will find the answer from forum.
