### ISSUE TITLE
cmd/go: implement gccgo support for content-based staleness

### ISSUE THREAD

**Issue by rsc** [golang/go#22472]
CL 73214 does not contain support for gccgo-based builds
and instead will cause cmd/go to fatal out if used with gccgo.
(The CL is a bit too large already.)

This issue is to make gccgo work again. The main work items are:

1. Figure out where to store build IDs in package archives and do so.

2. Write support for buildActionID/linkActionID/linkSharedActionID to record the relevant build configuration input for the gccgo toolchain.

**Comment by rsc** [comment]
Introduced in CL 73214:

	$ git grep -n issue/22472
	misc/cgo/testshared/shared_test.go:601:	t.Skip("golang.org/issue/22472")
	src/cmd/go/go_test.go:735:		t.Skip("golang.org/issue/22472")
	src/cmd/go/go_test.go:2655:	t.Skip("golang.org/issue/22472")
	$

**Comment by rsc** [comment]
With apologies for not doing this myself, I'm going to assign this to you @ianlancetaylor. Your CL is the lion's share I believe.

**Comment by ianlancetaylor** [comment]
As far as I can tell, this is done.  We can open new issues for any problems that arise.

**Comment by tklauser** [comment]
`TestIssue7573` and the gccgo specific part of `TestBuildComplex` in `src/cmd/go/go_test.go` are still skipped with this issue as a log message:

```
% git grep issue/22472
cmd/go/go_test.go:802:          t.Skip("golang.org/issue/22472")
cmd/go/go_test.go:3087: t.Skip("golang.org/issue/22472")
```

Should these skips be removed?

**Comment by ianlancetaylor** [comment]
Yes.  Sent https://golang.org/cl/120375.  Thanks.
