### ISSUE TITLE
spec: typo in the Go Spec

### ISSUE THREAD

**Issue by balkamm** [golang/go#22495]
There appears to be a typo in the go spec under https://golang.org/ref/spec#Type_identity.  Where it says "These types are identical" it lists:

B0, B0, and C0

Which should probably be:

B0, B1, and C0

Since later it says:

B0 and B1 are different because they are new types created by distinct type definitions; ...

**Comment by dsnet** [comment]
\cc @mdempsky @griesemer

**Comment by griesemer** [comment]
If B0 and B1 are different as it says later, it would be wrong to say B0, B1 and C0 are identical, wouldn't it? This is correct as stated, and on purpose. See also: #22202 and #9226.

**Comment by balkamm** [comment]
Sorry, I guess I misstated it slightly.  At the very least, B0 shouldn't be listed twice.

**Comment by griesemer** [comment]
That's the whole point: Who says that `B0` and `B0` are identical types? It needs to be spelled out. The types system is a formal system and it's up to the spec to state the rules. It's not as obvious as it may seem: For instance, for a floating-point value `x`, it's not a given that `x == x` (it's not true if `x` is `NaN`). Or, more closely related: We cannot write `nil == nil`. And so forth.

But given the number of bug reports this gets it looks like the point is not coming across, or perhaps it too academic.

**Comment by balkamm** [comment]
Okay, thanks for the explanation.  Sorry for the confusion.
