### ISSUE TITLE
sync.Map race conditions when calling Range() and Store()

### ISSUE THREAD

**Issue by blitzprog** [golang/go#22490]
### What version of Go are you using (`go version`)?
`go version go1.9.2 linux/amd64`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/eduard/workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build249817023=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Run the [race detector](https://blog.golang.org/race-detector) while parallely calling `Store()` for writing and `Range()` for reading.

### What did you expect to see?

No race conditions because the documentation mentioned that

```
// It is safe for multiple goroutines to call a Map's methods concurrently.
```

However, it is true that `Range` mentions:

```
Range does not necessarily correspond to any consistent snapshot of the Map's contents
```

### What did you see instead?

Race conditions.

If I use a `sync.RWMutex` on top of the `sync.Map` to `mutex.Lock` `Store()` and `mutex.RLock` `Range()` the race conditions are gone.

Is this intentional?

If it's not safe to iterate over a sync.Map while content is being stored, shouldn't the documentation of sync.Map reflect this?

```
// It is safe for multiple goroutines to call a Map's methods concurrently.
```

**Comment by davecheney** [comment]
Can you give please provide a runnable code sample that demonstrates the issue.

**Comment by blitzprog** [comment]
I apologize for the false alarm, upon writing the sample code I noticed that I was not **atomically** swapping a pointer in my database code which caused these race conditions.

The sync.Map library works perfectly fine.

Again, sorry for the false report.

**Comment by davecheney** [comment]
No worries. Glad you figured out it.
