### ISSUE TITLE
C source files not allowed when not using cgo or SWIG: y.tab.c

### ISSUE THREAD

**Issue by meghalidhoble** [golang/go#22492]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 and PPC64le architecture 
root:~ # go env
GOARCH="ppc64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/meghali/couchbase/ns_server/deps/gocode"
GORACE=""
GOROOT="/root/meghali/go"
GOTOOLDIR="/root/meghali/go/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build957891049=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
While building couchbase master source code, I am getting the go-build issue for this particular module "cbq-engine".

### What did you expect to see?
No errors.

### What did you see instead?
Building Go target cbq-engine using Go 1.9.1
**************** ENV_GOROOT : /root/meghali/go ***************
-- Executing: /root/meghali/go/bin/go install -pkgdir /root/meghali/couchbase/build/gopkg/go-1.9.1 -tags="community" -gcflags="" -ldflags=""   github.com/couchbase/query/server/cbq-engine
../../../../../../goproj/src/github.com/couchbase/query/expression/parser/parser.go:17:2: C source files not allowed when not using cgo or SWIG: y.tab.c
-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-- @ 'go install' failed! Re-running as 'go build' to help debug...
-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
WORK=/tmp/go-build190761458
../../../../../../goproj/src/github.com/couchbase/query/expression/parser/parser.go:17:2: C source files not allowed when not using cgo or SWIG: y.tab.c
CMake Error at /root/meghali/couchbase/tlm/cmake/Modules/go-install.cmake:85 (MESSAGE):
  Failed running go install

If anyone has observed the issue before, please let me know. Any pointers would help.
Thanks,
Meghali

**Comment by ianlancetaylor** [comment]
This does not look like an error in the Go toolchain or standard library.  We don't use our issue tracker for general discussion; see https://golang.org/wiki/Questions .  I'm going to close this since I think there is nothing for us to do.  Please comment if you disagree.
