### ISSUE TITLE
cmd/compile: improve PPC64.rules for loads and stores as found in encoding/binary ByteOrder interface functions

### ISSUE THREAD

**Issue by laboger** [golang/go#22496]
Use PPC64.rules to improve performance of statements that do multiple single byte loads or stores on consecutive bytes, such as is found in the encoding/binary ByteOrder interface. Instead do a single multi-byte load or store where possible, such as lhz, lwz, ld, sth, stw, std.

This improves functions that are found in encoding/binary:
        Uint16([]byte) uint16
        Uint32([]byte) uint32
        Uint64([]byte) uint64
        PutUint16([]byte, uint16)
        PutUint32([]byte, uint32)
        PutUint64([]byte, uint64)

The initial change for this will handle little endian cases.

**Comment by bradfitz** [comment]
Marking release-blocker (because it has a CL) and @randall77 as owner for review.
