### ISSUE TITLE
build: darwin/arm builders broken by content-based build CL

### ISSUE THREAD

**Issue by rsc** [golang/go#22509]
Looks like I broke the darwin/arm builders with my CL 73212. Investigating.

The log at https://build.golang.org/log/83cd0cb12afd4ff5069c6a9a72b124e02d21127c makes it look like there are two different make.bash runs, which maybe is part of the problem.

/cc @eliasnaur @crawshaw

**Comment by eliasnaur** [comment]
Thanks for putting up with the difficult mobile os'es. Off the top of my head:
- iostest.bash runs make.bash and then all.bash.
- cmd/dist test rebuilds runtime/cgo with the lldb tag.

Not sure if any is relevant.

**Comment by rsc** [comment]
I can reproduce locally without an ios device. One unrelated point: iostest.bash runs `all.bash --no-rebuild` but that's not a thing.  all.bash always rebuilds; perhaps that was supposed to be `run.bash --no-rebuild`.

The root cause appears to be that when you do a cross-compile build it looks like the CC_FOR_TARGET gets recorded as the default $CC for both host and target builds, so the host binaries look out of date during the run.bash half (because they were not built with CC=$CC_FOR_TARGET).

Related to #8161 in part.

**Comment by rsc** [comment]
Off to a meeting but will keep at this later.

**Comment by rsc** [comment]
Supposed to be fixed now. We will see.

**Comment by rsc** [comment]
@eliasnaur I did fix the failure we were seeing. Now we are seeing different failures. I am not sure what to make of them. Can you take a look and maybe file a new issue if you can see more?

**Comment by eliasnaur** [comment]
Thanks. It looks unrelated to the content-based caching. https://github.com/golang/go/issues/22612
