### ISSUE TITLE
error while insatlling the go 1.9 in any system "installation directory must be on local drive"

### ISSUE THREAD

**Issue by lokeshthathuru** [golang/go#22507]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9 for windows

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by davecheney** [comment]
I'm sorry this issue report does not meet the standard we need to help diagnose the issue. Please feel free to open a new issue if necessary.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by lokeshthathuru** [comment]
i solved the issue by using the command prompt this error occured because
the application file is in the form of msi file format

**Comment by lokeshthathuru** [comment]
thank you for reply me
