### ISSUE TITLE
cmd/compile (?): unexpected result

### ISSUE THREAD

**Issue by AlekSi** [golang/go#22512]
Sorry for the non-specific topic. Also, I'm sorry in advance if it turns out to be a question for a confusing situation, but not an issue. But I can't explain that result even with my years of experience of writing Go code commercially since Go 1.0.

### What version of Go are you using (`go version`)?
1.9.2, 1.4.3.

### What operating system and processor architecture are you using (`go env`)?
darwin, amd64.

### What did you do?
https://play.golang.org/p/NH3iAKIPeu, below is the copy for convenience:

```go
package main

import (
	"fmt"
	"reflect"
)

// type result = string // works as expected
type result = interface{} // value1 returns unexpected result

// sets data into *string or **string
func set(data string, i interface{}) error {
	val := reflect.Indirect(reflect.ValueOf(i).Elem())
	val.SetString(data)
	return nil
}

// value1, value2 set into *string
// pointer1, pointer2 set into **string
// value1 and value2, pointer1 and pointer2 are different in order of return values

func value1(data string) (result, error) {
	var res string
	return res, set(data, &res)
}

func value2(data string) (error, result) {
	var res string
	return set(data, &res), res
}

func pointer1(data string) (result, error) {
	res := new(string)
	return *res, set(data, &res)
}

func pointer2(data string) (error, result) {
	res := new(string)
	return set(data, &res), *res
}

func main() {
	fmt.Println(value1("value1"))
	fmt.Println(value2("value2"))
	fmt.Println(pointer1("pointer1"))
	fmt.Println(pointer2("pointer2"))
}
```

Note a few things about that code:

* There are no `nil` pointers. It is either a pointer to `string`, or pointer to non-nil pointer to `string`.
* `result` type is not used inside functions, only as a return value type.
* `string`s are always returned by values. Even when a string pointer is used, it is dereferenced before returning.

### What did you see?

With `type result = string`:

```
value1 <nil>
<nil> value2
pointer1 <nil>
<nil> pointer2
```

With `type result = interface{}`:

```
 <nil>
<nil> value2
pointer1 <nil>
<nil> pointer2
```

### What did you expect to see?

Consistent results for both types.

**Comment by randall77** [comment]
The spec says:

> ...when evaluating the operands of an expression, assignment, or return statement, all function calls, method calls, and communication operations are evaluated in lexical left-to-right order.
> ...the order of those events compared to [other non-call or communication] ... is not specified.
> 

So the ordering between the call to `set` and the evaluation of `res` or `*res` is not specified.

**Comment by AlekSi** [comment]
Thanks! That makes sense.
Do you think that _something_ should be fixed there? Like results be consistent even if not guaranteed by spec? `go vet` failing on that code?
If not, then feel free to close the issue.

**Comment by randall77** [comment]
I don't think there's anything to do here.
Certainly it is good practice to not exercise this part of the spec.  I always put my side-effecting expressions by themselves so there is no ambiguity.

We could change the compiler to observe a strict evaluation order.  Especially now that the compiler backend can easily get rid of extraneous copies, the cost would probably be less.
We could also update the spec.  That would be a harder sell, as part of the reason for the ambiguity is to make implementing Go easier (think, writing a new awesome compiler from scratch).

Vet rules need to have no false positives.  I don't see any obvious way to achieve that for this problem.
Consider the code `a[f()] + g()`.  Normally that's fine code; there's only an ambiguity when `g` might side-effect `a`.  I don't know how to detect that in a vet check.

I don't think this issue would be high priority for anyone.  The workaround is easy, the changes to the compiler would be tricky to get right, and those changes might also cause some performance loss.
