### ISSUE TITLE
go/vet: "func value, not called" on string-type struct field

### ISSUE THREAD

**Issue by gyuho** [golang/go#22517]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version devel +bc723cf340 Tue Oct 31 20:14:55 2017 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go"
GOTOOLDIR="/home/travis/.gimme/versions/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build130945276=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Run go vet with https://github.com/golang/go/commit/fc768da8b8030e6f344be6bbc86ae08c30f02849.

### What did you expect to see?

No error.

### What did you see instead?

```
Checking govet...
gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:94: Sprintf format %v arg cfg.Name is a func value, not called
gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:129: Errorf format %q arg cfg.Name is a func value, not called
gopath/src/github.com/coreos/etcd/etcdmain/config_test.go:525: Errorf format %v arg cfg.Name is a func value, not called
```

```go
// etcd.go:94: Sprintf format %v arg cfg.Name is a func value, not called
cfg.Dir = fmt.Sprintf("%v.etcd", cfg.Name)
```

```go
// etcd.go:129: Errorf format %q arg cfg.Name is a func value, not called
plog.Errorf("member %q has previously registered with discovery service token (%s).", cfg.Name, cfg.Durl)
```

```go
// config_test.go:525: Errorf format %v arg cfg.Name is a func value, not called
t.Errorf("name = %v, want %v", cfg.Name, wcfg.Name)
```

`cfg.Name` is `string` type, and this error message is confusing.

https://github.com/coreos/etcd/blob/9e509eb77f08ae950cd2082a70cc65f54f60d21e/etcdmain/config.go#L75-L77
https://github.com/coreos/etcd/blob/9e509eb77f08ae950cd2082a70cc65f54f60d21e/embed/config.go#L75-L85

Could anybody explain what's happening here?

Thanks!

**Comment by ianlancetaylor** [comment]
You have a bunch of embedding going on here.  It does seem that `config.Config.Name` is a string.  But https://golang.org/cl/70391 added a `Name` method to `flag.FlagSet`, and that type is also embedded in `config`, as `config.configFlags.FlagSet`.  `config.Name` winds up referring to the method, but you aren't calling it, so vet issues a warning.

Closing because I don't see anything we can do here.  Please comment if you disagree.

**Comment by gyuho** [comment]
Now the warning makes sense with https://go-review.googlesource.com/c/go/+/70391.

Thanks!
