### ISSUE TITLE
Cross-compiling for Darwin amd64 fails on Linux

### ISSUE THREAD

**Issue by Baldomo** [golang/go#22510]
### What version of Go are you using (`go version`)?
`go version go1.9 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

### What did you do?
I just ran `env GOOS=darwin GOARCH=amd64 go build` through the build script below

### What did you expect to see?
Successful build, so no output + resulting executables (Windows x64 + Linux x64 + Darwin x64)

### What did you see instead?
Succesful Windows and Linux build, error on the darwin one
```
# net
/usr/lib/go-1.9/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
# os/user
/usr/lib/go-1.9/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:
/usr/lib/go-1.9/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function ‘getgrouplist’ [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
```

### Other info:
Project structure:
```
webapi-dav/
├── build
├── config.toml
├── pkg/
├── src/
│   ├── builder.sh (build script, source below)
│   ├── github.com/ (external modules' sources etc)
│   ├── handlers_generic.go
│   ├── handlers_sezioni.go
│   ├── logger.go
│   ├── preferences.go
│   ├── router.go
│   ├── routes.go
│   ├── startup.go (this contains main)
│   ├── static/
│   │   └── index.html
│   └── utils.go
└── TODO.md
```
[Build script (builder.sh)](https://gist.github.com/Baldomo/165a77b58f75b6802133d394b68aa3e4)

Full `go env` for reference:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leonardo/Documents/Go/webapi-dav/"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build671788590=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by ianlancetaylor** [comment]
If you are going to cross-compile from Darwin to GNU/Linux and build a program that uses cgo, you must have a C Darwin -> GNU/Linux cross-compiler.

If you don't need cgo, set `CGO_ENABLED=0` in the environment when running `go build`.

Closing because there is nothing to do here and because this is a dup of #22462 among others.

**Comment by Baldomo** [comment]
Thank you for the support; looks like I'm going to need a cross-compiler
