### ISSUE TITLE
race: race tool does not work on Linux Mint

### ISSUE THREAD

**Issue by Dilshat** [golang/go#22523]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.9 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dilshat/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build336883168=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Build  any program with -race flag
for example, go build -race

### What did you expect to see?

no output

### What did you see instead?

# hello
runtime.raceinit: relocation target __tsan_init not defined
runtime.raceinit: relocation target __tsan_map_shadow not defined
runtime.racefini: relocation target __tsan_fini not defined
runtime.raceproccreate: relocation target __tsan_proc_create not defined
runtime.raceprocdestroy: relocation target __tsan_proc_destroy not defined
runtime.racemapshadow: relocation target __tsan_map_shadow not defined
runtime.racemalloc: relocation target __tsan_malloc not defined
runtime.racefree: relocation target __tsan_free not defined
runtime.racegostart: relocation target __tsan_go_start not defined
runtime.racegoend: relocation target __tsan_go_end not defined
runtime.raceacquireg: relocation target __tsan_acquire not defined
runtime.racereleaseg: relocation target __tsan_release not defined
runtime.racereleasemergeg: relocation target __tsan_release_merge not defined
runtime.racefingo: relocation target __tsan_finalizer_goroutine not defined
runtime.RaceDisable: relocation target __tsan_go_ignore_sync_begin not defined
runtime.RaceEnable: relocation target __tsan_go_ignore_sync_end not defined
runtime.raceread: relocation target __tsan_read not defined
runtime.racereadpc: relocation target __tsan_read_pc not defined
runtime.racewrite: relocation target __tsan_write not defined
runtime.racewritepc: relocation target __tsan_write_pc not defined
runtime.racereadrange: relocation target __tsan_read_range not defined
/usr/lib/go-1.9/pkg/tool/linux_amd64/link: too many errors

**Comment by odeke-em** [comment]
@dvyukov perhaps this issue can be bundled with #14481?

**Comment by AlexRouSg** [comment]
I'm on linux mint 18.2 and race works just fine.
go version go1.9 linux/amd64

Which exact version of linux mint are you on?

**Comment by Dilshat** [comment]
Linux Mint 18.2 Sonya Mate edition

**Comment by ALTree** [comment]
race doesn't work on alpine because race assumes glibc and Alpine ships with musl. Unless OP is using musl, this issue is not the same as #1448

**Comment by AlexRouSg** [comment]
@Dilshat 
Did you install build-essential?

**Comment by odeke-em** [comment]
@ALTree https://github.com/golang/go/issues/22523#issuecomment-341110341 I wasn't saying it is the same issue, I was just wondering if we can lump them together: `-race not working on some Linuxes` :)

**Comment by Dilshat** [comment]
@AlexRouSg
I didn't install anything 
I just installed Linux Mint and then installed go

**Comment by AlexRouSg** [comment]
@Dilshat 
I meant install it if you didn't

**Comment by Dilshat** [comment]
@AlexRouSg oh ok, thanks for the suggestion
I will try tomorrow and write here results, currently away from the offending computer

**Comment by Dilshat** [comment]
@AlexRouSg installing **build-essential** didn't help

**Comment by dvyukov** [comment]
It seems that the linker does not link race syso file.
+@ianlancetaylor

**Comment by AlexRouSg** [comment]
@Dilshat 
How did you install go then? I cannot imagine MATE to be much different from cinnamon other than the desktop environment. Like we have the same OS and go versions this is very strange...

**Comment by ianlancetaylor** [comment]
What is the output of `go build -race -x` and `go build -race -ldflags=-v`?  Thanks.

**Comment by Dilshat** [comment]
@AlexRouSg 
```sudo add-apt-repository ppa:gophers/archive
sudo apt update
sudo apt-get install golang-1.9-go
```
and then 
```sudo ln -s /usr/lib/go-1.9/bin/go /usr/bin/go
sudo ln -s /usr/lib/go-1.9/bin/gofmt /usr/bin/gofmt
```

**Comment by Dilshat** [comment]
@ianlancetaylor 
output of go `build -race -x`
[output.txt](https://github.com/golang/go/files/1439996/output.txt)

output of `go build -race -ldflags=-v`
[output2.txt](https://github.com/golang/go/files/1439997/output2.txt)

**Comment by AlexRouSg** [comment]
@Dilshat 
Thats the problem then, they did not include the files needed for race. You'd want to install go from https://golang.org/dl/ instead

**Comment by Dilshat** [comment]
@AlexRouSg Yes, reinstalling GO from https://golang.org/dl/  helped. Thanks a lot.

**Comment by cristim** [comment]
On my Ubuntu this did the trick: `sudo apt-get install golang-1.10-race-detector-runtime`
