### ISSUE TITLE
cmd/gofmt: incorrect alignment on two returned functions

### ISSUE THREAD

**Issue by leonklingele** [golang/go#22521]
If a function returns two or more functions, `go fmt` misaligns them as follows:

```go
func makeFuncs() (func(), func()) {
	return func() {
			// a
		}, func() {
			// b
		}
}
```

I'd expect the code to be aligned as such:

```go
func makeFuncs() (func(), func()) {
	return func() {
		// a
	}, func() {
		// b
	}
}
```

See this [playground snippet](https://play.golang.org/p/mvGAT8cjk9).

**Comment by griesemer** [comment]
This working as intended. If you returned a longer expression (https://play.golang.org/p/XeOqTapb6g) you wouldn't want the expression operands aligned with the return either. That's exactly what happens here.
