### ISSUE TITLE
x/tools/cmd/toolstash: broken after recent cmd/go changes

### ISSUE THREAD

**Issue by mvdan** [golang/go#22548]
### What version of Go are you using (`go version`)?

    go version devel +0d101d1a9f Thu Nov 2 09:01:40 2017 +0000 linux/amd64

### What did you do?

```
 $ go build -toolexec "toolstash -cmp" -a -v std cmd
go tool compile: exit status 1
toolstash: cannot determine output file for command: /home/mvdan/tip/pkg/tool/linux_amd64/compile -V=full
```

It's likely the new buildID stuff that is throwing it off:

```
 $ /home/mvdan/tip/pkg/tool/linux_amd64/compile -V=full
compile version devel +0d101d1a9f Thu Nov 2 09:01:40 2017 +0000 buildID=EdwHznUAy6Oxc4Hk-yFc/ale-_RqM8HqdtrWb1GOW/ikUIPRlBHr85fkjsgjLD/YuAYclRBSMsq5lIltNoC
```

/cc @rsc @mdempsky

**Comment by rsc** [comment]
Fixed by https://go-review.googlesource.com/c/tools/+/75672.

**Comment by mvdan** [comment]
Ah, I see we both submitted the same issue on the same day.
