### ISSUE TITLE
doc: reflect documentation doesn't show examples

### ISSUE THREAD

**Issue by ainar-g** [golang/go#22547]
Possibly a continuation of #21601. https://golang.org/pkg/reflect/ doesn't show examples, while https://godoc.org/reflect does.

**Comment by dsnet** [comment]
Seems to be working on tip, so it may be already fixed: https://tip.golang.org/pkg/reflect/

**Comment by ainar-g** [comment]
@dsnet I should've looked. Closing as fixed at HEAD.
