### ISSUE TITLE
cmd/go: -n and -x do not print all commands when using shared or c-shared buildmode

### ISSUE THREAD

**Issue by huawei-brice** [golang/go#22565]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/brice/go"
GORACE=""
GOROOT="/usr/local/go-1.9.2"
GOTOOLDIR="/usr/local/go-1.9.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build204618450=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

Create a simple go file with a non-main package, for example:
```go
package foo

func bar() {}
```

Build it with `-buildmode=shared` and `-n` or `-x` to see the build commands.

### What did you expect to see?

All of the build commands used to build the shared library.

### What did you see instead?

Only the link command:

```bash
$ go build -buildmode=shared -linkshared -n a.go
cd .
/usr/local/go-1.9.2/pkg/tool/linux_amd64/link -o $WORK/libcommand-line-arguments.so -L $WORK -installsuffix dynlink -buildmode=shared -linkshared -w -extld=gcc
$
```
```bash
$ go build -buildmode=shared -linkshared -x a.go
WORK=/tmp/go-build709785197
cd .
/usr/local/go-1.9.2/pkg/tool/linux_amd64/link -o $WORK/libcommand-line-arguments.so -L $WORK -installsuffix dynlink -buildmode=shared -linkshared -w -extld=gcc
$
```

**Comment by ianlancetaylor** [comment]
This is behaving as expected, though perhaps there is some way we can change the behavior.  The go tool is printing all the commands that it is executing.  The command you are looking for is actually being executed by the linker.  You can see it (along with other output) by running `go build -ldflags=-v ...`.  Perhaps we could arrange for `go build -x` to pass an option to the linker that tells it to output the external link command.  Or perhaps that would be more confusing, I'm not sure.

**Comment by huawei-brice** [comment]
Actually, what I was expecting to see was the `compile` commands before the `link` command, not the linker commands.

**Comment by ianlancetaylor** [comment]
Ah, sorry, I misunderstood.

I do see those commands myself.  Are you sure the package wasn't already installed, and therefore did not need to be recompiled?  Did you run `go install -buildmode=shared` at any point?  What do you see in $GOPATH/pkg/linux_amd64_shared?

**Comment by huawei-brice** [comment]
I don't have `$GOPATH/pkg/linux_amd64_shared`, but I do have a `linux_amd64_dynlink` directory. I just emptied it and got the same result.

**Comment by ianlancetaylor** [comment]
I have no explanation.  I can't recreate this at all.  I don't know what is happening.

**Comment by huawei-brice** [comment]
Ok sorry, I'm not sure what was happening before, but in a clean environment, I do see the compile command. Thanks Ian.
