### ISSUE TITLE
cmd/internal/obj/arm64: reduce verbosity of code in /obj/arm64/asm7.go

### ISSUE THREAD

**Issue by xyproto** [golang/go#22576]
Hi,

This is my first attempt at contributing to the Go source code, I am very open to suggestions to improving my process.

I submitted a patch to gerrit and was asked by Brad Fitzpatrick (who kindly reviewed the code) to create a corresponding bug.

This is the issue that I believed can be improved by my patch:

* `asm7.go` can be reduced with 38 lines of code, with increased clarity of code and the exact same behavior.

Here's the change: [75690](https://go-review.googlesource.com/c/go/+/75690/1)

**Comment by ALTree** [comment]
I've edited the title of the issue because based on your comments on the CL 

>  the intention is to increase the readability [of the code in asm7.go]

this is just about deciding whether it's worth changing the code to make it more readable, and you are not reporting compiler bug(?)

**Comment by xyproto** [comment]
@ALTree Thank you. That is correct, I do not consider this to be a compiler bug, only an improvement in readability and line count (every line of code has a certain percentagewise chance for bugs, so in theory, fewer lines = fewer bugs, right?).

**Comment by bradfitz** [comment]
> so in theory, fewer lines = fewer bugs, right?

No, many of us would argue strongly that that assumption is not true. For example, 5 tricky lines are more likely to hide a bug than 10 boring lines.

That said, your change might be an improvement, but I'll let others decide. I just wanted to clarify that reducing the number of lines is not a goal in and of itself.

**Comment by ALTree** [comment]
Decision seems to be: let's leave that code alone; OP has abandoned the proposed CL, so we can close here.
