### ISSUE TITLE
cmd/go: gccgo not recognized

### ISSUE THREAD

**Issue by brtzsnr** [golang/go#22589]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +e5f6051e77 Sun Nov 5 19:28:13 2017 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Not with the latest stable release 1.9. It reproduces at tip.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"

### What did you do?

$ go build --help 
        -compiler name
                name of compiler to use, as in runtime.Compiler (gccgo or gc).

$ go build -compiler gccgo -a .
buildActionID: unknown build toolchain "gccgo"

### What did you expect to see?

I expected the code to compile. It compiles with standard toolchain.

### What did you see instead?

Compiler error.  gccgo not recognized.

**Comment by rsc** [comment]
Yes, dup of #22472.
