### ISSUE TITLE
cmd/vet: vet should warn on possible mis-shaddows caused by short variable declarations.

### ISSUE THREAD

**Issue by go101** [golang/go#22582]
Many new gophers give up using Go when they ever fall into the famous trap in Go.

```
func f() int {
	var a = 1
	if a != 0 {
		a, b := 2, 3 // vet should consider here the "a" might be mis-shaddowed.
		if b == 2 {
			return a
		}
	}
	return a
}
```

Go vet should make a warning for such cases to get better user experience.

**Comment by cznic** [comment]
This example cannot be vetted.

**Comment by go101** [comment]
@cznic 
why?

**Comment by cznic** [comment]
Legitimate code.

**Comment by go101** [comment]
Yes, it is. But legitimate code can't be vetted?

**Comment by cznic** [comment]
What should vet say about it? 'Warning: legitimate code detected'?

**Comment by bontibon** [comment]
> Many new gophers give up using Go ...

That seems hyperbolic.

**Comment by go101** [comment]
> What should vet say about it? 'Warning: legitimate code detected'?

"possible mis-shaddow of a" is better.

**Comment by go101** [comment]
> That seems hyperbolic.

Not at all. I read many anti-Go articles, this trap is a must-have in them.

**Comment by dominikh** [comment]
This is already implemented and guarded by the `-shadow` flag:

```
$ go vet -shadow foo.go
foo.go:6: declaration of "a" shadows declaration at foo.go:4
exit status 1
```

This check cannot be enabled by default because it is noisy and produces false positives – not all shadowing is buggy, and a lot of shadowing is intentional.

**Comment by go101** [comment]
Great! Glad to know it is supported.
