### ISSUE TITLE
web: monitoring for *.golang.org properties

### ISSUE THREAD

**Issue by andybons** [golang/go#22603]
talks.golang.org was down for several hours, but there were no alerts.

We should do an inventory of our web properties and set up (at least) basic reachability checks, along with a plan for how we’d like to handle the alerts.

related issues:
https://github.com/golang/go/issues/21315
https://github.com/golang/go/issues/15760

/cc @bradfitz @adams-sarah

**Comment by adams-sarah** [comment]
cc @broady who has done the alerts for playground (and other sites?)

**Comment by andybons** [comment]
Alerts are now up for golang.org, play, and tour. Since we still run some services on the legacy `<version name>.golang.org` instead of putting them in their own modules, we can’t set up monitoring for those services.

We should move everything to services instead of versions of the godoc app.

**Comment by andybons** [comment]
Uptime monitoring has been added for

+ godoc.org
+ golang.org
+ blog.golang.org
+ build.golang.org
+ google.golang.org
+ perf.golang.org
+ perfdata.golang.org
+ play.golang.org
+ talks.golang.org
+ tour.golang.org
+ beta.golang.org
+ maintner.golang.org
+ tip.golang.org
+ dev.golang.org
+ farmer.golang.org
+ gerritbot.golang.org
+ http2.golang.org
+ pubsubhelper.golang.org
+ vcs-test.golang.org
+ sum.golang.org
+ proxy.golang.org
+ index.golang.org
