### ISSUE TITLE
cmd/go: vet printf attempts to validate flags on custom formatters

### ISSUE THREAD

**Issue by soniakeys** [golang/go#22608]
### What version of Go are you using (`go version`)?
go version devel +36323e4 Tue Nov 7 01:50:16 2017 +0000 linux/amd64

### Does this issue reproduce with the latest release?
In go vet 1.9, yes, but now it is an issue with the new go test on tip.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"
...

### What did you do?
custom_test.go:
```
package custom

import (
    "fmt"
    "testing"
)

type custom int

func (custom) Format(fmt.State, rune) {}

func Test(t *testing.T) {
    fmt.Printf("%z", custom(0))
    fmt.Printf("%#z", custom(0))
    fmt.Printf("%#s", custom(0)) // unrecognized flag
}
```
### What did you expect to see?
$ go test
PASS

### What did you see instead?
$ go test
\# custom
./custom_test.go:15: Printf format %#s has unrecognized flag #

Some code in okPrintfArg, in cmd/vet/print.go, handles custom formatters already.  This case might be handled similarly to the way it passes unrecognized verbs for custom formatters.

**Comment by ChrisHines** [comment]
This issue causes CI builds against tip to break for my package github.com/go-stack/stack, which supports the `%#s` format strings (as documented here: https://godoc.org/github.com/go-stack/stack#Call.Format).

**Comment by ChrisHines** [comment]
In my opinion this issue makes the printf checks not 100% reliable for purposes of #18085.

**Comment by rsc** [comment]
This report is great, thanks. We know we need to cut the printf check back just a bit; concrete details are very helpful.
