### ISSUE TITLE
doc/articles/wiki: move _ warning slightly higher at one point

### ISSUE THREAD

**Issue by sewi-cpan** [golang/go#22617]
Currently working myself through https://golang.org/doc/articles/wiki/ and got stuck at the first HTTP server example. It doesn't have any error handling but easily runs into a bad Go panic

`2017/11/07 20:08:24 http: panic serving 127.0.0.1:48718: runtime error: invalid memory address or nil pointer dereference`

Took me some time to find out that I was missing the test.txt file. Created a solution comment before noticing that pull requests to are not allowed but don't want to go through the full contributor process right now just to add few lines to the tutorial page.

You may copy from my commit or write something else, but there should be a hint for others running into the same problem:
https://github.com/sewi-cpan/go/commit/c47c0178da16780f73403adddd6f8242cdbd1686

**Comment by gbbr** [comment]
In my opinion no action is needed here, since it is clearly mentioned in the text:
> Again, note the use of _ to ignore the error return value from loadPage. This is done here for simplicity and generally considered bad practice. We will attend to this later.

There is even a special section in the very same wiki document dedicated specifically to this issue ([Handling non-existent pages](https://golang.org/doc/articles/wiki/#tmp_7))

**Comment by agnivade** [comment]
Agree. May be we can change this text `This is done here for simplicity and generally considered bad practice.` to bold ? So that there are less chances of getting tripped.

**Comment by rsc** [comment]
In the text:

> First, this function extracts the page title from r.URL.Path, the path component of the request URL. The Path is re-sliced with [len("/view/"):] to drop the leading "/view/" component of the request path. This is because the path will invariably begin with "/view/", which is not part of the page's title.
> 
> The function then loads the page data, formats the page with a string of simple HTML, and writes it to w, the http.ResponseWriter.
> 
> Again, note the use of _ to ignore the error return value from loadPage. This is done here for simplicity and generally considered bad practice. We will attend to this later.

Let's move the final ("Again...") paragraph above the first two.

**Comment by sewi-cpan** [comment]
The hint is ok, but the result of the "_" could be a problem: The unintended reader easily runs into what looks like a completely unrelated error while trying the source until this point. The "_" is perfectly ok at this place and also the reference to attend to this later.
I *read* the "_" warning. The consequences might be obvious for Go experts but not for newbies walking through the tutorial.

Another idea to reduce the risk of problems here: The first example (in "Data Structures") does create a "TestPage.txt", but the webserver example discussed here expects "test.txt". Why not just use the same name in both examples. Doing so would create the test file needed for part 2 in part 1.
