### ISSUE TITLE
cmd/vet: "Println call ends with newline" even when newline is escaped

### ISSUE THREAD

**Issue by sabey** [golang/go#22613]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu amd64

### What did you do?
`fmt.Println("\\n")`
go vet

### What did you expect to see?
I expect \\ to be seen as escaped

### What did you see instead?
\\n is seen as not escaped

**Comment by mvdan** [comment]
Thanks for the simple example to reproduce this.
