### ISSUE TITLE
go/types: types.aliases should be exported

### ISSUE THREAD

**Issue by willfaught** [golang/go#22628]
To be clear, this is:

```
$ go doc -u go/types aliases
var aliases = [...]*Basic{
	{Byte, IsInteger | IsUnsigned, "byte"},
	{Rune, IsInteger, "rune"},
}
```

Otherwise, there's no pre-defined way to get a Basic value whose `String()` is "rune". This means you can't get a type, convert it into an equivalent representation, and then convert it back into an equivalent types.Type with the same `String()`. Simulating the byte/rune types with Named types doesn't work in general because byte/rune can be underlying types, and Named.SetUnderlying will panic if you use a Named argument.

It's implied that all the Basic values are in Typ, but the Basic value you get for byte/rune types isn't. The Typ documentation should warn about this.

**Comment by alandonovan** [comment]
You can use `types.Universe.Lookup("rune").Type()`: https://play.golang.org/p/4saiCBPITd

**Comment by mvdan** [comment]
That was fast :)

**Comment by willfaught** [comment]
Thanks for the workaround. However, the documentation point has yet to be addressed.

**Comment by alandonovan** [comment]
Robert, how about something like this?

```
// The Typ array contains the canonical Basic type for a given kind.
//
// Because the aliases "rune" and "byte" existed prior to the addition
// of type aliases to the language, there is a single kind for Rune and Int32,
// and a single kind for Byte and Uint8. To obtain the Basic type
// representing one of the named aliases, look it up by name using
// Universe.Lookup(name).Type().
var Typ = ...
```

**Comment by griesemer** [comment]
Sure, sounds good.

What's also missing is a doc string for Universe (and Unsafe, while there).

Care to send a CL? Or should I do it?

**Comment by mvdan** [comment]
Apologies for closing early - had not noticed the point on the docs.

**Comment by willfaught** [comment]
Some suggestions for the doc wording:

>The Typ array

Typ is a slice, technically. The doc comment should start with the declaration's name.

>there is a single kind for Rune and Int32, and a single kind for Byte and Uint8

It would perhaps be clearer to say that Rune and Int32 are equal, and Byte and Uint8 are equal, and thus in Typ, Rune and Byte correspond with the Basics for Int32 and Uint8, respectively.

>To obtain the Basic type representing one of the named aliases

It might be unclear how these Basics don't represent the alias types, since they're technically equal and interchangeable from a type checking point of view. Perhaps it would help to point out how the names for those Basics won't match what's assumed for the Rune and Byte kinds.

---

Altogether, perhaps something like this:

```go
// Typ contains the canonical Basic for a BasicKind. Since Byte and Rune
// are aliases, the Basics they correspond to do not have matching names.
// To get the Basics for them with matching names, use Universe.Lookup(name).Type().
var Typ = []*Basic{ ...
```

---

In any case, thanks for documenting it!
