### ISSUE TITLE
x/blog/blog: fail more helpfully in root.tmpl file(s) not found

### ISSUE THREAD

**Issue by forskning** [golang/go#22622]
It appears necessary to access the template directory to run the blog executable.

Below are some suggested changes.

This repository holds the Go Blog server code and content.

Download

You can run `go get -u golang.org/x/blog`, or manually git clone the repository to $GOPATH/src/golang.org/x/blog.

Running Locally

Unix-like

cd go/src/golang.org/x/blog/blog
go install
cd ..
~/go/bin/blog

Windows

CD go\src\golang.org\x\blog
go.exe build ./blog
blog.exe

and then visit http://localhost:8080/ in your browser.

Note that the blog executable caches all content and you must kill it (Ctrl-C on Unix-like and Windows) and restart it after editing any files to view changes.

**Comment by forskning** [comment]
If one wants to separate the build from the running this also works.

Download/Install

Unix-like

$ export PATH=$PATH:$HOME/go/bin
$ go get -u golang.org/x/blog/blog

Windows

C:\>SET PATH=%PATH%;%USERPROFILE%\go\bin
C:\>go.exe get -u golang.org/x/blog/blog

Running Locally

Unix-like

$ cd $HOME/go/src/golang.org/x/blog
$ blog

Windows

C:\>CD %USERPROFILE%\go\src\golang.org\x\blog

C:\Users\UserName\go\src\golang.org\x\blog>blog.exe

**Comment by forskning** [comment]
@bradfitz

I suppose this could use a label.

**Comment by bradfitz** [comment]
I don't understand what your bug report is.

We're definitely not going to redundantly document how to use cmd/go and build binaries for every single repo & tool.

So your report is:

> It appears necessary to access the template directory to run the blog executable.

Can you expand on what you mean?

You jumped to a solution without fully stating the problem.

Did you get an error message?

**Comment by forskning** [comment]
the report infers that README files might be customised

but to answer your question root.tmpl is the file searched for

in order to run the blog executable

it appears that the current directory needs to be the parent of template

the current instructions for Windows suffice

but on *nix one can't colocate an executable named blog

in a directory where there's a sub-directory named blog

generally, is the reader of the documentation aware

that if $GOPATH contains a single value as $HOME/go

of information to add $HOME/go/bin to PATH, prior to running go get

**Comment by forskning** [comment]
FWIW, one should know all this by reading https://golang.org/doc/code.html#GOPATH, but IMHO it does't really help the reader to write "The easiest way to install is to run go get -u golang.org/x/blog.", when the resultant Windows Command Prompt output will something like the following.

package golang.org/x/blog: no Go files in C:\Users\Eric\go\src\golang.org\x\blog

I do not believe that adding to the golang/blog subrepo's code a message to the user, that the executable should be run from the top level blog directory, would address the purpose for which this issue was filed.

Currently when attempting to run the blog executable from other than the top level blog directory there is what appears to be console output informing that the path to template\root.tmpl cannot be found.

**Comment by forskning** [comment]
I liked the original title of this issue better.

**Comment by agnivade** [comment]
>  In order to run the blog executable it appears that the present working directory needs to be the parent of template.

Not really. If you do a `./binary -h`, you will see that the template folder location is a parameter which can be passed. So essentially, you can run it from anywhere.

However, I will send a CL to improve the error message.

P.S. - It appears that you have 2 issues here. One about the root.tmpl error message, and another about the README content. Let us focus on root.tmpl for this, since that is the title of the issue. I would advise you to open a new issue _just_ focusing on the README contents, if you still want it to be updated.
