### ISSUE TITLE
database/sql: NumInput check before CheckNamedValue could remove unwanted arguments

### ISSUE THREAD

**Issue by tgulacsi** [golang/go#22630]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
I've implemented an database/sql/driver for Oracle: gopkg.in/goracle.v2
The driver.Stmt.NumInput method returns the (proper) number of required unique arguments.

I'm calling Query with additional arguments, such as the prefetch row count:
`db.Query("SELECT :1 FROM DUAL", "arg", goracle.FetchRowCount(1024))`

### What did you expect to see?
No errors.

### What did you see instead?
error: "sql: statement expects 1 inputs; got 2"

### Investigation ###
As I see, the error is returned from https://golang.org/src/database/sql/sql.go#L2280, right before the driver could eliminate unwanted args (fetchRowCount) with CheckNamedValue returning driver.ErrRemoveArgument.

CheckNamedValue is called later, as the next call is to driverArgs, and in it the CheckNamedValue is called (https://golang.org/src/database/sql/convert.go#L191), and the argument number is checked, but this time _after_ CheckNamedValue - so this part is OK, but the previous check in sql.go is too early.

**Comment by tgulacsi** [comment]
ErrRemoveArgument has been introduced in a9bf3b2e by @kardianos

**Comment by kardianos** [comment]
@tgulacsi Tanks for the report. I'll look into and get a fix out soon.
