### ISSUE TITLE
cmd/compile: for loop prevents inlining 

### ISSUE THREAD

**Issue by TocarIP** [golang/go#22636]
### What version of Go are you using (`go version`)?
go version devel +ef0e2af Mon Nov 6 15:55:31 2017 +0000 linux/amd64

Go currently performs inlining of small functions, but if it encounters any explicit loop construct, such as for loop, function is never inlined. This causes code to use goto instead (e. g. tryWriteCopy in compress/flate/dict_decoder_test.go in standard library) to simulate loops.  Inlining functions with loops can significantly improve performance. For example  replacing for with goto in PutUvarint (in encoding/binary) results in 40% speed-up.
```
PutUvarint64-6     119ns Â± 0%       67ns Â± 1%  -43.91%  (p=0.000 n=8+10)
```
I'd prefer to get this speed-up  without uglyfing code with goto.

**Comment by huguesb** [comment]
Dup of #14768

**Comment by TocarIP** [comment]
Sorry, I've missed it somehow.
