### ISSUE TITLE
website: binary download links involve redirection

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22648]
We used to have really nice download links that just worked.

Now there's this HTTP redirection, making curl usage more annoying:

```
pi@raspberrypi:~ $ curl -O https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   2087      0 --:--:-- --:--:-- --:--:--  2100


pi@raspberrypi:~ $ cat go1.9.2.linux-armv6l.tar.gz 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://r13---sn-nx57yn7k.gvt1.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz?cms_redirect=yes&amp;expire=1510278830&amp;ip=2620:0:1009:fd00:e066:33c6:5590:624&amp;ipbits=0&amp;mm=28&amp;mn=sn-nx57yn7k&amp;ms=nvh&amp;mt=1510264098&amp;mv=u&amp;pl=56&amp;shardbypass=yes&amp;sparams=expire,ip,ipbits,mm,mn,ms,mv,pl,shardbypass&amp;signature=2E1506D41A75DC13E8293B0274C93AE43A6285FD.5C967816ABA01ED0CF2F7BB3DC6EBE673E3B2566&amp;key=cms1">here</A>.
</BODY></HTML>
```

We can't serve from the "edge" without all that stuff? We do for other things, and others on the Internet do too.

What is going on?

**Comment by andybons** [comment]
The old urls, while prettier and direct, are blocked in some countries. This not only allows us to serve faster downloads to our users more cheaply, but also reach the countries that block GCS.

I’m not sure how much of the internal guts I’m able to share publically as to why Goog’s edge cache behaves the way that it does, but I’ve asked.

In the meantime, `curl -O -L https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz`

**Comment by bradfitz** [comment]
Noted elsewhere, I see Chrome uses https://dl.golang.org/* URLs directly. What is different between Go and Chrome, that Chrome gets to use pretty & non-redirecting URLs?

**Comment by andybons** [comment]
+ These downloads are backed by GCS. We never stopped using it. You can access the payload in a few ways:
  + https://storage.googleapis.com/golang/go1.9.2.linux-armv6l.tar.gz
  + https://dl.google.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz
  + https://dl.google.com/go/go1.9.2.linux-armv6l.tar.gz
  + https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz
+ We picked the last one because 1) it is cheaper and more reliable and 2) the download URLs we choose _must_ be available to our users in countries that may block certain domains.

storage.googleapis.com is definitely blocked.

We can use dl.google.com. It's not blocked, but when I asked about this I was told that it costs more money and is less reliable.

**Comment by forskning** [comment]
pertaining to source downloads

https://github.com/golang/go/issues/21662#issuecomment-340273822

Oct 29, 2017

not pertaining to source downloads

https://github.com/golang/go/issues/22041#issuecomment-334496332

Oct 5, 2017

**Comment by bradfitz** [comment]
Let's switch to dl.google.com. If it's good enough for Chrome, it's good enough for us.

**Comment by andybons** [comment]
OK. Sounds good.

**Comment by shurcooL** [comment]
> We used to have really nice download links that just worked.

@bradfitz, what I've always used (for the last 4-6~ major releases) was:

```
curl -L https://golang.org/dl/go1.9.2.linux-amd64.tar.gz
```

I thought that was the "canonical nice download link". Is it not the canonical nice link, or were you not aware that it exists?

For reference, it currently redirects to `https://redirector.gvt1.com/edgedl/...`:

```
$ curl -i https://golang.org/dl/go1.9.2.linux-amd64.tar.gz
HTTP/2 302 
strict-transport-security: max-age=31536000; preload
location: https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
content-type: text/html; charset=utf-8
x-cloud-trace-context: 3e8ae52e754442ea42130692384f57e4
date: Sat, 11 Nov 2017 08:03:22 GMT
server: Google Frontend
content-length: 87
alt-svc: quic=":443"; ma=2592000; v="41,39,38,37,35"

<a href="https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz">Found</a>.
```

I guess this a question/comment... I want to find out if other people are aware of the `https://golang.org/dl/...` links and what is their status (canonical? alternative? deprecated?). Thanks.

**Comment by shurcooL** [comment]
Looking at https://github.com/golang/tools/commit/9c477bae194915bfd4bc8c314e90e28b9ec1c831 more closely, I see that what's been modified is the redirect URL that `https://golang.org/dl/...` returns (and I guess that change isn't live yet).

I guess that partially answers my question, but my followup question then is, have you considered using `curl -L https://golang.org/dl/...` and not caring what the underlying redirect URL it uses under the hood? (If the answer is "yes I've considered it", that's completely fine; I just want to confirm.)

**Comment by bradfitz** [comment]
@shurcooL, I don't want people to see URLs like "redirector.gvt1.com" in them. That says neither Google nor Golang in it and looks spammy.

**Comment by shurcooL** [comment]
@bradfitz Makes sense. Thanks for confirming!
