### ISSUE TITLE
website: add a "Latest Release" link to the downloads page and/or github releases

### ISSUE THREAD

**Issue by jeffreydwalter** [golang/go#22645]
It would be really handy to have a static url that pointed to the latest version of go.

Currently, the downloads page (https://golang.org/dl/) only has versioned links. I also don't see any "generic" link on the github releases page.

Does this already exist somewhere? I couldn't find it if it does.

Thanks!

**Comment by bradfitz** [comment]
For what platform? Or to get the source?

If you want a OS/arch-specific "latest" URL, we'd need one per platform.

If you want the source, we have git with a stable URL.

I guess I don't understand the motivation yet. Why would it be "really handy"?

**Comment by jeffreydwalter** [comment]
Ideally, it would be nice to have a permalink to the latest for each platform and the source.

It would be handy in my case because I have some automated build and development setup tools that require go to build stuff; I would like to always ensure I'm building with the latest version.

As it stands, I'm forced to either scrape the website to figure out what the latest version is, or just live, with a static version, or build from source.

**Comment by bradfitz** [comment]
I don't think we're going to start publishing a download URL with contents that change over time.

I'm going to close this in favor of #20892 to make a programmatic way for callers (like your automation) to find the latest version(s).
