### ISSUE TITLE
 x/tools/cmd/godoc: synopsis for subdirectories is always empty

### ISSUE THREAD

**Issue by Carpetsmoker** [golang/go#22646]
When using `godoc` the synopsis for the subdirectories is always empty.

For example:

    $ godoc -html github.com/jmoiron/sqlx | tail -n35
                                        <tr>
                                                <td class="pkg-name" style="padding-left: 0px;">
                                                        <a href="reflectx/">reflectx</a>
                                                </td>
                                                <td class="pkg-synopsis">

                                                </td>
                                        </tr>

                                        <tr>
                                                <td class="pkg-name" style="padding-left: 0px;">
                                                        <a href="types/">types</a>
                                                </td>
                                                <td class="pkg-synopsis">

                                                </td>
                                        </tr>

The same when leaving `-html` out, although I'm not sure if it's *supposed* to be displayed here?

```
$ godoc github.com/jmoiron/sqlx | tail -n6
SUBDIRECTORIES

        reflectx
        types
```

If I run `godoc -http :6061` and navigate to `http://localhost:6061/pkg/github.com/jmoiron/sqlx/` it does work as expected (like on e.g. https://www.godoc.org/github.com/jmoiron/sqlx).

This problem is not specific to the sqlx package; it happens with all packages. I just used this as an example.

Using Go 1.9.2 with most recent godoc (commit 05e91d0/Nov 7).

**Comment by agnivade** [comment]
Thanks, I am able to repro this. I know why this is happening. The http mode and the command line code paths are different. The http mode creates a dir tree for the entire GOPATH, whereas in command line mode, the dir tree for only that path is created with a depth of 1. Hence the synopses of sub-directories are not retrieved. We just need to go one level deeper.

Will send a CL when 1.11 cycle opens.
