### ISSUE TITLE
encoding/xml: cannot get array, only get the first element

### ISSUE THREAD

**Issue by AnotherGoogleFan** [golang/go#22657]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoProject
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
```
package main

import (
	"encoding/xml"
	"fmt"
)

type server struct {
	ServerName string `xml:"serverName"`
	ServerIP   string `xml:"serverIP"`
}

func main() {
	data := []byte(`
    <server>
        <serverName>Shanghai_VPN</serverName>
        <serverIP>127.0.0.1</serverIP>
    </server>
    <server>
        <serverName>Beijing_VPN</serverName>
        <serverIP>127.0.0.2</serverIP>
    </server>
`)
	var v []server
	err := xml.Unmarshal(data, &v)
	if err != nil {
		fmt.Printf("error: %v", err)
		return
	}

	fmt.Println(v)
}
```

### What did you expect to see?
[{Shanghai_VPN 127.0.0.1}  {Beijing_VPN 127.0.0.2}]

### What did you see instead?
[{Shanghai_VPN 127.0.0.1}]

**Comment by mvdan** [comment]
See the `Unmarshal` docs:

> UnmarshalXML decodes a single XML element beginning with the given start element.

You may decode multiple top-level elements by calling decode multiple times, as seen in https://stackoverflow.com/questions/27553274/unmarshal-xml-array-in-golang-only-getting-the-first-element.

Otherwise, instead of using `<elem></elem><elem></elem>`, you could use `<elems><elem></elem><elem></elem></elems>` to have a single top-level element.
