### ISSUE TITLE
x/build/devapp: reviews handler shows merged CLs

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22653]
https://dev.golang.org/reviews currently shows:

```
2017-05-22  Gustav Westling   38634 encoding/base32: add Encoding.WithPadding, StdPadding, NoPadding
```

But https://go-review.googlesource.com/c/go/+/38634 is merged so it shouldn't be listed as a TODO item.

**Comment by andybons** [comment]
Something is up with maintner’s data, since I’m using `ForeachOpenCL`: https://go.googlesource.com/build/+/master/devapp/reviews.go#116

**Comment by bradfitz** [comment]
Could you investigate? A good place to add tests (or just tests for debugging) is x/build/maintner/godata/godata_test.go, which works with the same live maintner data.

**Comment by bradfitz** [comment]
Oh, this got tricksy. I'm on it.
