### ISSUE TITLE
net/http/httputil: ReverseProxy does not close response body if ModifyResponse returns an error

### ISSUE THREAD

**Issue by edanbe** [golang/go#22658]
### What version of Go are you using (`go version`)?
`go version go1.9.2 linux/amd64`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build111677926=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
Return an error from `ReverseProxy`'s `ModifyResponse` function.
Test: https://play.golang.org/p/8N8zeMvox5

### What did you expect to see?
`ServeHTTP` should close the response body before returning.

### What did you see instead?
`ServeHTTP` does not defer the call to close the response body, in order to populate response trailers.
If `ModifyResponse` returns an error, `ServeHTTP` returns before closing the response body.

I'll prepare a CL if desired.

**Comment by odeke-em** [comment]
Thank you @edanbe for the detailed report and for volunteering a fix. Please do so.

@bradfitz am going to mark this as a Go1.10 bug, as it seems like a simple fix and non-invasive, please advise if otherwise.

**Comment by odeke-em** [comment]
Thank you very much @edanbe for the CL, I've added some feedback for a test on the CL, please take a look.
