### ISSUE TITLE
net/mail: missing date layout

### ISSUE THREAD

**Issue by wxdao** [golang/go#22661]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Playground:
https://play.golang.org/p/HRd4hDqXU2

Explanation:
In net/mail/message.go there is

`zones := [...]string{"-0700", "MST", "-0700 (MST)"}`

However, it leaves out the situation `-0700 (GMT:-07:00)`.

So, rewriting that line to

`zones := [...]string{"-0700", "MST", "-0700 (MST)", "-0700 (GMT:-07:00)"}`

would fix this issue.

### What did you expect to see?
It gets parsed successfully.

### What did you see instead?
`0001-01-01 00:00:00 +0000 UTC mail: header could not be parsed`

**Comment by ianlancetaylor** [comment]
Where did you see this date header?

From looking at RFC 5322 I suspect that the right fix is to remove `"-0700 (MST)"` from `dateLayouts` and to change `ParseDate` to skip CFWS at the end.

**Comment by wxdao** [comment]
I saw this in mails sent by gmail web. And yes, simply removing the (*) suffix before parsing will also do.

**Comment by odeke-em** [comment]
As per @ianlancetaylor's comments in the review of CL 117596, that this change is more complicated than permissible this late in the cycle, we are moving this to Go1.12.

**Comment by benburwell** [comment]
Is there any progress on getting this CL applied? I suppose at this point it will be going into 1.14, but it looks like it missed both 1.12 and 1.13, so I'm not sure if anything needs to happen to make sure it goes into 1.14.

**Comment by ianlancetaylor** [comment]
Bother, we've clearly dropped the ball on this one.  The best way would to ping the CL when we open the tree for 1.14.  I'll try to do that myself but clearly I've failed to do so in the past.

**Comment by benburwell** [comment]
Thanks, I'll keep an eye out for that!

**Comment by benburwell** [comment]
@ianlancetaylor I see Constantin has uploaded a new patchset on the CL a few days ago; not familiar enough with the Go dev process to know if that is sufficient as a ping?

**Comment by ianlancetaylor** [comment]
Yes, thanks, it's still on my list, I've just been swamped.  Thanks for checking.
