### ISSUE TITLE
Build tags does not work in main package

### ISSUE THREAD

**Issue by sammy007** [golang/go#22669]
I want to restrict whole project from compilation on go versions < 1.9 so I put this into `main.go`

```
// +build go1.9

package main

...
```

it does not work, meanwhile it's ok if specified in other package within project. Is it yet another "idiomatic" gem I am not aware of or there is another "canonical" way?

I am asking because in 1.8 the json deserializer just broke some projects in very weird way and caused edge cases so such crutches will be required because core library no longer can be trusted.

**Comment by artyom** [comment]
Seems to be working as expected:

```
example ¶ cat main.go 
// +build go1.10

package main

func main() {
	println("hello")
}
example ¶ go version
go version go1.9.2 darwin/amd64
example ¶ go build
can't load package: package .: build constraints exclude all Go files in /tmp/example
```

With Go 1.8:

```
example ¶ cat main.go 
// +build go1.9

package main

func main() {
	println("hello")
}
example ¶ go version
go version go1.9.2 darwin/amd64
example ¶ go build ; echo $?
0
example ¶ GOROOT=/tmp/go /tmp/go/bin/go version
go version go1.8.5 darwin/amd64
example ¶ GOROOT=/tmp/go /tmp/go/bin/go build
can't load package: package .: no buildable Go source files in /tmp/example
```

**Comment by sammy007** [comment]
With go 1.6

```
// +build go1.10

package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
}
```

```
go version
go version go1.6.2 linux/amd64
```

```
go build x.go
./x
Hello, playground

**Comment by sammy007** [comment]
Maybe works because source file given to build command, my bad. But why `go install` works if such tag given?

**Comment by sammy007** [comment]
Well, likely depends on my build scripts.
