### ISSUE TITLE
golang changes 0711 to 457

### ISSUE THREAD

**Issue by Shashwatsh** [golang/go#22671]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/shashwat/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build609445059=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```package main

import (
	"os"
	"text/template"
)

func main() {
	t := template.New("")
	t, _ = t.Parse("{{ . }}")
	t.Execute(os.Stdout, 0711)
}
```

### What did you expect to see?
output : ```0711```

### What did you see instead?
output ```457```

**Comment by davecheney** [comment]
This is not a bug, it's octal notation.

**Comment by Shashwatsh** [comment]
@davecheney How do i fix this?

**Comment by davecheney** [comment]
An octal literal starts with a `0`. replace `0711` with `711`.

https://golang.org/ref/spec#Integer_literals
