### ISSUE TITLE
encoding/json: RawMessage.MarshalJSON should error if it is nil

### ISSUE THREAD

**Issue by qJkee** [golang/go#22686]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?
Just opened source code :D

### What did you see instead?
Open encoding/json/stream.go at 250th line.
In function, MarshalJSON
```
func (m RawMessage) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	return m, nil
}
```
That means, that error always will be nil. But i think that `if m == nil `should return error that raw message is empty(or nill).
In that case, we have to ignore returned error(it's always nill), and check returned array for
`if arr == []byte("null")`

**Comment by mvdan** [comment]
What makes you think that `m == nil` should error? Note that the definition is `type RawMessage []byte`, and it's very common for uses of `[]byte` to also accept `nil` without any errors.

This seems more like a question than a bug report to me, unless there is an actual problem you ran into because of this behavior.

**Comment by qJkee** [comment]
So, if you always return nill error, maybe make func return only `[]byte` to avoid unnecessary error checking?

**Comment by mvdan** [comment]
Then it wouldn't implement the interface: https://golang.org/pkg/encoding/json/#Marshaler

**Comment by qJkee** [comment]
As a way,  we can return `m, nill` without checks, and don't allocate a new byte array with "null" word inside. It's will be strange, if I will be sure that my array is not empty, but it will contain "null" word instead of my data.

**Comment by mvdan** [comment]
Sorry, I don't understand what you're saying.

I still don't see a bug here, so I'm closing this. The issue tracker is not used for questions and discussion, so I suggest you take this to https://github.com/golang/go/wiki/Questions.
