### ISSUE TITLE
x/build: hide all-red builders

### ISSUE THREAD

**Issue by rsc** [golang/go#22689]
The columns of red on the dashboard should be fixed or removed from the default display. As things are now, the fact that we apparently expect some builders to be all red hides the fact that we don't expect other builders to be all red.

Right now, linux-amd64-alpine, linux-amd64-noopt, and linux-arm-arm5spacemonkey are all red. Apparently alpine and monkey are expected to be that way - there are long-term bugs open for fixing those - but noopt is not expected to be that. It looks like I broke noopt in CL 74470, but I didn't notice because it just added one more all-red column to the dashboard.

We should make it the case that all-red is always something that needs attention _now_, not a "would be nice" for the future.

/cc @bradfitz

**Comment by bradfitz** [comment]
Sounds good. But alpine and plan9-amd64 are the one two I'd expect to be read.

spacemonkey shouldn't be broken?

/cc @0intro @zeebo

**Comment by zeebo** [comment]
I also expect they should be working.

**Comment by 0intro** [comment]
I've fixed the plan9-amd64 builder a while ago, so it should be fine.

However, the plan9-arm is currently red because of an issue raised by TestHttpsInsecure after the update of the github.com/google/pprof/internal/driver package (issue #22691).

**Comment by randall77** [comment]
I suspect noopt breakage is issue 22444.

**Comment by bradfitz** [comment]
I've fixed all the red that shouldn't be red.

The remaining red is real or has outstanding CLs waiting to be approved.

Closing this in favor of the specific bugs. Now that I'm back full-time, I'll be watching build.golang.org as usual.
