### ISSUE TITLE
syscall: fs_nacl.go: Link and Rename missing fs mutex lock/unlock

### ISSUE THREAD

**Issue by tenortim** [golang/go#22690]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
Issue uncovered by inspection.

### What operating system and processor architecture are you using (`go env`)?
Go playground using GOOS=nacl

### What did you do?
Per comments at the head of fs_nacl.go:
```
// Since there is no I/O (everything is in memory),
// the global lock mu protects the whole file system state,
// and that's okay.
```
and
```
// Except where indicated otherwise, unexported methods on fsys
// expect fs.mu to have been locked by the caller.
```
but Link and Rename call these methods without locking fs.

### What did you expect to see?
fs calls should be serialized

### What did you see instead?
These two are not.
Fix is trivial. I'm happy the needed changes

**Comment by bradfitz** [comment]
Fine for Go 1.10, or whenever. Thanks.
