### ISSUE TITLE
runtime: TestMemStats fails after running tests and benchmarks for some time

### ISSUE THREAD

**Issue by mvdan** [golang/go#22696]
go version devel +79dbc1cc7b Sun Nov 12 13:25:35 2017 +0000 linux/amd64

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mvdan/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mvdan/go/land:/home/mvdan/go"
GORACE=""
GOROOT="/home/mvdan/tip"
GOTMPDIR=""
GOTOOLDIR="/home/mvdan/tip/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build917956427=/tmp/go-build -gno-record-gcc-switches"
```

```
$ go test -bench=Mem -count 10 runtime
--- FAIL: TestMemStats (0.00s)
        malloc_test.go:75: TotalAlloc = 108745353624: insanely high value (overflow?); want <= 1e+11
^Csignal: interrupt
FAIL    runtime 496.137s
```

Note that the test succeeds fine on its own, even when it's run thousands of times.

Also note that it took my laptop over 5 minutes to reach this point. Might be reached faster on a more powerful machine.

**Comment by mvdan** [comment]
The upper threshold seems to be applied in the test code, so labelling as a testing bug.

**Comment by ianlancetaylor** [comment]
CC @aclements @dvyukov

**Comment by aclements** [comment]
Hmm. It's not really clear what we can do about this. `TestMemStats` is just sanity checking a bunch of values and if you run the tests long enough they simply won't be sane any more. We could loosen the thresholds, but then it's not as useful in the normal case.

Maybe it should keep track of how many times it's run and start skipping after some N?

/cc @RLH
