### ISSUE TITLE
cmd/dist: dropped tests in CL 66870?

### ISSUE THREAD

**Issue by rsc** [golang/go#22708]
I just posted a (late) comment on merged CL 66870. It seems to have dropped some tests in cmd/dist. If I'm confused, then great, close this issue. But if we really dropped some tests unintentionally, we should restore them and make sure they still pass.

**Comment by laboger** [comment]
I'll check into it.

**Comment by laboger** [comment]
The original code in cmd/dist/test.go was using defaultcc and that was a string but was changed in the meantime to be a map of strings. I changed it to use defaultcc[""] but I'm not sure in all cases if that is correct.
