### ISSUE TITLE
cmd/vet: error when using unregistered errorf method

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#22715]
go version devel +fa1f52c Tue Nov 14 05:39:45 2017 +0000 linux/amd64

An example from our code base; we have an errorf method defined:

    func (i *idM) errorf(w http.ResponseWriter, status int, format string, a ...interface{})

and some code is calling it:

	i.errorf(w, http.StatusNotFound, "not found", "%s not found", req.URL.Path)

This produces an error from vet: `errorf call has arguments but no formatting directives`.
The vet -printfuncs flag seems to have lost the argument position of the first argument involved in the print, and anyway it would be better not to have to individually configure printf-like functions to get Go code to compile.

This is now a more pressing issue since tip changed to always run vet.

**Comment by rogpeppe** [comment]
At least until the vet checks become 100% reliable, it would be good to have the option to turn off the vet checking done by "go install", so that we can continue to use Go tip on packages like the above that trigger spurious vet errors.

**Comment by ianlancetaylor** [comment]
I don't think that `go install` runs any vet checks.  The change is that vet checks are now run by `go test`.  You can disable them by using `go test -vet=off`.

The intent is to not run all vet tests, but only those that are very likely to report errors.  #18085 is about pinning down that exact set.  I think that perhaps we should move this problem over to that issue and close this one as a dup.

**Comment by rogpeppe** [comment]
Ah, yes, I hadn't realised I just saw the issues running go test. I wasn't sure if this justified another card or not. Perhaps not. I'll close it.
