### ISSUE TITLE
internal/cpu: fix CRC32 on darwin/arm64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22720]
I suspect the https://go-review.googlesource.com/c/go/+/76490 I'm about to submit might break CRC32 detection on darwin/arm64.

It used to use runtime.supportsCRC32() but will now use Linux-provided info. Since Darwin doesn't provide it, we should make sure we still populate ARM64.CRC32 on Darwin.

/cc @zhangfannie @eliasnaur

**Comment by eliasnaur** [comment]
AFAICT, supportsCRC32 was never set and thus always false on darwin/arm64:

https://go-review.googlesource.com/c/go/+/76490/3/src/runtime/os_darwin_arm64.go#b7

So I don't think 76490 made it worse.

**Comment by bradfitz** [comment]
@eliasnaur, ah, thanks! I'll close this then.
