### ISSUE TITLE
cmd/go: test -json issues

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22734]
In https://github.com/golang/go/issues/2981#issuecomment-344317527 , @zolotov writes:

----

I've tried to apply this feature in GoLand and this is the list of issues I faced:

1. `-json` parameter doesn't work with `-c` argument
2. `-json` parameter doesn't work with `go bench`. The only json output for benchmarks is package-passed event (btw, it's incorrectly "failed", looks like a bug), no information about starting, ending benchmarks or about text in stdout in json format.

```
PASS
ok  	github.com/rcrowley/go-metrics	40.797s
{"Time":"2017-11-11T12:55:29.076331942+03:00","Action":"fail","Package":"github.com/rcrowley/go-metrics","Elapsed":40.797}
…
```
 
3. Some events have become a part of output of others, like this one:

```
/home/zolotov/dev/go/bin/go test -v -json ./... 
{"Time":"2017-11-11T13:05:28.267338195+03:00","Action":"run","Package":"github.com/rcrowley/go-metrics","Test":"TestCounterClear"}
{"Time":"2017-11-11T13:05:28.26745939+03:00","Action":"output","Package":"github.com/rcrowley/go-metrics","Test":"TestCounterClear","Output":"=== RUN   TestCounterClear\n"}
{"Time":"2017-11-11T13:05:28.267468575+03:00","Action":"output","Package":"github.com/rcrowley/go-metrics","Test":"TestCounterClear","Output":"{"Time":"2017-11-11T13:05:28.267472348+03:00","Action":"pass","Package":"github.com/rcrowley/go-metrics","Test":"TestCounterClear","Elapsed":0}
{"Time":"2017-11-11T13:05:28.267476892+03:00","Action":"run","Package":"github.com/rcrowley/go-metrics","Test":"TestCounterDec1"}
```

The third line is barely parseable.

**Comment by zolotov** [comment]
1. #22789
2. #22769
3. Cannot recreate on the latest sources.

Can be closed, I think
