### ISSUE TITLE
math/rand: revert Perm changes?

### ISSUE THREAD

**Issue by rsc** [golang/go#22744]
I encouraged Josh to change Perm to match Shuffle, but it's a potentially breaking change and while writing the release notes I am reluctant to describe it. We should probably revert the behavioral change in Perm.

**Comment by dsnet** [comment]
I support reverting `rand.Perm` changes. It is the cause of a few failures inside Google, and the fix for them is not easy.

**Comment by mvdan** [comment]
The CL in question is https://golang.org/cl/55972, if any was wondering (like myself).
