### ISSUE TITLE
Setting log_path in GORACE fails on Windows

### ISSUE THREAD

**Issue by innix** [golang/go#22756]
### What version of Go are you using (`go version`)?
```
$ go version
go version go1.9.2 windows/amd64
```

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\innix\Documents\dev\go-workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

1. Build a program with `-race` ([here's a minimal program with a race condition](https://play.golang.org/p/NOUnyPvdtL)).
2. Set the `GORACE` env var so that detected races are logged to a file instead of stderr.
3. Run program.

```
$ go build -race
$ GORACE='log_path=C:\reports\myprogram' ./test.exe
```

### What did you expect to see?
The Go data race detector should have logged a data race to a file called `C:\reports\myprogram.<pid>`.

### What did you see instead?
The program just outputs `ERROR: expected '='` then exits:

```
$ GORACE='log_path=C:\reports\myprogram' ./test.exe
ERROR: expected '='

$
```

### Other notes
This only happens when using absolute Windows paths. The following `GORACE` values with relative paths work as expected:
```
$ GORACE='log_path=myprogram' ./test.exe
$ GORACE='log_path=./myprogram' ./test.exe
$ GORACE='log_path=../../../myprogram' ./test.exe
```

Absolute paths still don't work if I use forward slashes instead, or if I use double backslash:
```
$ GORACE='log_path=C:\\reports\\myprogram' ./test.exe
$ GORACE='log_path=C:/reports/myprogram' ./test.exe
```

The directory `C:\reports\` already exists and the program has permission to write files into it.

I'm using Git Bash for Windows in these examples, but the same problem occurs if I use Windows native tools. It's not a Git Bash issue.

**Comment by alexbrainman** [comment]
@innix thank you very much for raising this issue. I can confirm it on windows/amd64. Unfortunetly the code for this lives in http://llvm.org/git/compiler-rt.git

I will let @dvyukov decide what to do here.

Alex

**Comment by ianlancetaylor** [comment]
Closing this issue in favor of google/sanitizers#884.  There isn't anything we can change in the Go distribution  to fix this.
