### ISSUE TITLE
build: trybots are missing in action

### ISSUE THREAD

**Issue by rsc** [golang/go#22763]
https://go-review.googlesource.com/c/go/+/78195 has a Run-TryBot +1 from 10:08 AM.
https://go-review.googlesource.com/c/go/+/78115/5 has one from 10:04 AM.
https://go-review.googlesource.com/c/go/+/78113/6 also has one from 10:04 AM.

No word from the farmer on any of these. The front page on the farmer does not mention them. Maybe whatever watches Gerrit has fallen over?

(And it's now 10:58 AM here.)

/cc @bradfitz

**Comment by bradfitz** [comment]
I'm having Internet connectivity issues this morning and then traveling back home, so sadly I won't get to investigate this for a bit.

I'll fix it, though.

**Comment by rsc** [comment]
Congratulations / condolences on building a piece of infrastructure that has become so essential. I really feel like I'm working in the past today.
