### ISSUE TITLE
cmd/internal/obj/x86: AVX512 design

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#22779]
Discussion started here: [golang-dev: AVX512 syntax](https://groups.google.com/forum/#!topic/golang-dev/DdQX1mN1Rd4)

This issue keeps track of all agreed implementation/design choices (though most things may change many times), as well as discussed alternatives.

If you can and/or want to participate, please leave the comment here or in the thread that is linked above.

----

**1. Accepted solutions:**

**1.1.** New registers:
* `X16-X31`
* `Y16-Y31`
* `Z0-Z31`
* `K0-K7` masking registers. *Exact operand syntax/position not yet decided.*

**1.2.** AVX512_4FMAPS register range operand:

Specified with ARM NEON-style register ranges syntax: `[Rx-Ry]`.
```asm
V4FMADDPS (CX), [Z4-Z7], Z1 // Proposed Go syntax

V4FMADDPS (CX), Z4+3, Z1    // Intel manual syntax
V4FMADDPS (CX), Z4, Z1      // GAS syntax
```

----

**2. Subjects under discussion:**

Special syntax like `{1toX}` and `{sae}` is avoided:

> We try to keep the syntax as regular as possible, meaning no special { } just for x86.

**2.1.** Masking register syntax.
```asm
VPSLLD $171, Z5, Z6, K7 // a) K after destination.
VPSLLD $171, Z5, K7, Z6 // b) K before the destination.
VPSLLD $171, Z5, Z6(K4) // c) K with addressing syntax.
VPSLLD $171, Z5, Z6&K4  // d) K as register modifier.
```

**2.2.** Zeroing syntax.
```asm
// Arbitrarily implies that 2.1.a is accepted..
VPSLLD.Z $171, Z5, Z6, K7   // a) ".Z" opcode suffix.
VPSLLD $171, Z5, Z6, K7(Z)  // b) Z with addressing syntax near K.
VPSLLD $171, Z5, Z6&K4.ZERO // c) Masking register modifier.
```

**2.3.** Encoding selection: VEX vs EVEX.

a) Always favor VEX encoding variants.
b) Some kind of flag to enable EVEX_ENCODING whenever beneficial.
c) Require explicit K operand for EVEX variants to give programmer full control over selected encoding.

**2.4.** Broadcast.

```asm
VPSLLD.1to16 $2, (AX), Z5, 2, Z6 // a) ".1toN" opcode suffix.
VPSLLD.B16 $123, 508(DX), Z6     // b) ".BN" opcode suffix.
VPSLLD $2, bcst (AX), Z5, 2, Z6  // c) "bcst" keyword.
```

**2.5.** Rounding.

```asm
VADDPD.RN.SAE Z4, Z5, Z6 // a) Opcode suffix.
```

**3. Key notes:**

<details>
<summary>Useful information about past/current trade-offs</summary>

* Suffix-based operand size approach is not used for `X/Y/Z` registers to make information search easier. This also implies that VEX/EVEX encoding should not be resolved by special suffix/prefix (there was no such problem with SSE vs VEX because most latter opcodes are prefixed with "V").
* CMP instructions operands are not in "special order" as legacy CMPs. This is consistent with AVX1/2.
* Some 32bit data size instructions have suffix in Intel manual. For example, `KADDD`. Go uses `L` suffix for 32bit operands, so `KADDL` opcode used instead.

</details>

**Comment by rasky** [comment]
**Masking**: ARM uses `R7>>R8` and `R7@>R8` for barrel shift/rotations. I think this is the closest concept to what AVX512 allows. My suggestion is to use a similar syntax, with a register modifier, like `Z6@K7` or `Z6/K7` or maybe `Z7&K7`, where the ampersand recalls the bitwise and operator which is basically what happens.

**Zeroing**: this is conceptually part of masking (at least in my view), so the zero modifier must be part of the masking syntax, not part of the opcode or elsewhere. If we go with `Z7&K7`, for instance, we can have `Z7&K7Z` or `Z7&K7.Z` or `Z7&K7&Z` or `Z7&K07` or `Z7&K7.ZERO`. It's unfortunate that the "Z" letter is used for the new set of registers as well, but I guess we have to live with this.

**Broadcast**: I think having an opcode suffix  `.Bn` is better than the eye-bleeding "1toN" moniker. If we keep masking/zeroing as a register modifier (as I suggest above), there is no composition issue and we can simply have `VPSSLD.B16 $123, 508(DX), Z6&K2` 

**Rounding**. Again, an opcode suffix is probably the best, and it doesn't overlap with broadcasting anyway. `VADDPD.RN.SAE`

**Comment by Quasilyte** [comment]
@rasky, I believe that rounding can't be specified without `SAE`.
`RN.SAE` looks like two separate suffixes, which raises additional questions: 
- are `SAE.RN` or `RN.B16.SAE` valid? ? 
- Can we omit `SAE` as it implied anyway?

Maybe `RN_SAE`/`RNSAE` is a viable alternative?
```asm
VADDPD.RN_SAE Z4, Z5, Z6
```

**Comment by Quasilyte** [comment]
For the reference that is related to "VEX vs EVEX" question:
XED enforces explicit **k** mask register to apply EVEX encoding.
```c
$ ./xed -64 -e VADDPD xmm0 xmm1 xmm2
Request: VADDPD MODE:2, REG0:XMM0, REG1:XMM1, REG2:XMM2, SMODE:2
OPERAND ORDER: REG0 REG1 REG2 
Encodable! C5F158C2
.byte 0xc5,0xf1,0x58,0xc2

// (basically) same operands, but with EVEX encoding.
$ ./xed -64 -e VADDPD xmm0 k0 xmm1 xmm2
Request: VADDPD MODE:2, REG0:XMM0, REG1:K0, REG2:XMM1, REG3:XMM2, SMODE:2
OPERAND ORDER: REG0 REG1 REG2 REG3 
Encodable! 62F1F50858C2
.byte 0x62,0xf1,0xf5,0x08,0x58,0xc2

// As a consequence, attempt to use High-16 registers
// without k0 will result in error.
$ ./xed -64 -e VADDPD xmm17 xmm18 xmm19
Request: VADDPD MODE:2, REG0:XMM17, REG1:XMM18, REG2:XMM19, SMODE:2
OPERAND ORDER: REG0 REG1 REG2 
Could not encode: VADDPD xmm17 xmm18 xmm19 
Error code was: GENERAL_ERROR
[XED CLIENT ERROR] Dying
```
Same trick is applicable for x86 asm.
It means that instruction tables for such instructions will be like this:
```
{X0-X15, X0-X15, X0-X15/MEM}     => VEX
{X0-X31, K0, X0-X31, X0-X31/MEM} => EVEX
```
Instead of:
```
// Note missing K0 in EVEX table.
{X0-X15, X0-X15, X0-X15/MEM} => VEX
{X0-X31, X0-X31, X0-X31/MEM} => EVEX
```
This simple change makes it possible for programmer to explicitly choose encoding to use.

Not sure it addresses that though (Frank Wessels):
> I guess quite some projects are using “dynamic” switching based on CPU capabilities, so if a subroutine has AVX512 (EVEX) instructions, it would be nice if the whole routine could take advantage of EVEX encoding.
Would adding a flag like “EVEX_ENCODING” in “text flag.h” make sense to enable this?

CC @TocarIP

**Comment by fwessels** [comment]
@Quasilyte I noticed the same behaviour in xed regarding the EVEX instructions (and explicit need of mentioning k register for registers >= 16).

Sticking to the same behaviour nicely addresses the issue (and even allow mixed mode routines which is a benefit).

**Comment by Quasilyte** [comment]
[golang-dev first message](https://groups.google.com/forum/#!topic/golang-dev/DdQX1mN1Rd4), 5th question (@TocarIP):

> 5) Currently `VCVTPD2PS` and some other instructions exists in 2 forms `VCVTPD2PSX` and `VCVTPD2PSY`,
because we can't distinguish beetween 128 and 256 bit versions in some cases:
`VCVTPD2PS (R11), X2` // Destination is 128 bit in both cases, so we need X/Y suffix
But if we add broadcasting we can distinguish those cases. 1to4 means 256, 1to2 means 128.
So should we add a version of `VCVTPD2PS` without X/Y suffix, but with mandatory broadcasting?

List of such instructions that is based on x86.csv v0.2:
```
$ grep VEX x86.v0.2.csv | egrep '"128"|"256"'
"VCVTPD2DQ xmm1, xmm2/m128","VCVTPD2DQX xmm2/m128, xmm1","vcvtpd2dqx xmm2/m128, xmm1","VEX.128.F2.0F.WIG E6 /r","V","V","AVX","","w,r","Y","128"
"VCVTPD2DQ xmm1, ymm2/m256","VCVTPD2DQY ymm2/m256, xmm1","vcvtpd2dqy ymm2/m256, xmm1","VEX.256.F2.0F.WIG E6 /r","V","V","AVX","","w,r","Y","256"
"VCVTPD2PS xmm1, xmm2/m128","VCVTPD2PSX xmm2/m128, xmm1","vcvtpd2psx xmm2/m128, xmm1","VEX.128.66.0F.WIG 5A /r","V","V","AVX","","w,r","Y","128"
"VCVTPD2PS xmm1, ymm2/m256","VCVTPD2PSY ymm2/m256, xmm1","vcvtpd2psy ymm2/m256, xmm1","VEX.256.66.0F.WIG 5A /r","V","V","AVX","","w,r","Y","256"
"VCVTTPD2DQ xmm1, xmm2/m128","VCVTTPD2DQX xmm2/m128, xmm1","vcvttpd2dqx xmm2/m128, xmm1","VEX.128.66.0F.WIG E6 /r","V","V","AVX","","w,r","Y","128"
"VCVTTPD2DQ xmm1, ymm2/m256","VCVTTPD2DQY ymm2/m256, xmm1","vcvttpd2dqy ymm2/m256, xmm1","VEX.256.66.0F.WIG E6 /r","V","V","AVX","","w,r","Y","256"
```

Planning to use X/Y/Z suffixes for now.

AVX512 introduces around 100 instructions that require suffix or explicit broadcast to disambiguate.

**Comment by Quasilyte** [comment]
Current WIP examples:
```asm
	// Embedded rounding.
	VADDPD.RU_SAE X3, X2, K1, X1   // 62f1ed5958cb or 62f16e5958cb
	VADDPD.RD_SAE X3, X2, K1, X1   // 62f1ed3958cb or 62f16e3958cb
	VADDPD.RZ_SAE X3, X2, K1, X1   // 62f1ed7958cb or 62f16e7958cb
	VADDPD.RN_SAE X3, X2, K1, X1   // 62f1ed1958cb or 62f16e1958cb
	VADDPD.RU_SAE.Z X3, X2, K1, X1 // 62f1edd958cb or 62f16ed958cb
	VADDPD.RD_SAE.Z X3, X2, K1, X1 // 62f1edb958cb or 62f16eb958cb
	VADDPD.RZ_SAE.Z X3, X2, K1, X1 // 62f1edf958cb or 62f16ef958cb
	VADDPD.RN_SAE.Z X3, X2, K1, X1 // 62f1ed9958cb or 62f16e9958cb

	// Embedded broadcasting.
	VADDPD.B2 (AX), X2, K1, X1    // 62f1ed195808
	VADDPD.B2.Z (AX), X2, K1, X1  // 62f1ed995808
	VADDPD.B4 (AX), Y2, K1, Y1    // 62f1ed395808
	VADDPD.B4.Z (AX), Y2, K1, Y1  // 62f1edb95808
	VADDPD.B8 (AX), Z2, K1, Z1    // 62f1ed595808
	VADDPD.B8.Z (AX), Z2, K1, Z1  // 62f1edd95808
	VMAXPD.B8 (AX), Z2, K1, Z1    // 62f1ed595f08
	VMAXPD.B8.Z (AX), Z2, K1, Z1  // 62f1edd95f08

	// Surpress all exceptions (SAE).
	VMAXPD.SAE   Z3, Z2, K1, Z1   // 62f1ed595fcb or 62f1ed195fcb
	VMAXPD.SAE.Z Z3, Z2, K1, Z1   // 62f1edd95fcb or 62f1ed995fcb
	VMAXPD (AX), Z2, K1, Z1       // 62f1ed495f08
	VCMPSD.SAE $0, X0, X2, K0     // 62f1ef18c2c000
	VCMPSD.SAE $0, X0, X2, K1, K0 // 62f1ef19c2c000

	// Multisource operands (4FMAPS/4VNNIW register range operand).
	VP4DPWSSD (AX), [Z0-Z3], K1, Z7   // 62f27f495238
	VP4DPWSSD 7(DX), [Z0-Z3], K1, Z7  // 62f27f4952ba07000000

	// K write mask.
	VADDPD X30, X1, X0               // 6291f50858c6
	VADDPD X2, X1, K1, X0            // 62f1f50958c2
```

Details:
- Signals error when rounding+broadcast suffixes are combined
- Zeroing suffix should be the last suffix
- Register range does not accept comma-separated lists. Only simple ranges.
- Can't use K0 as write mask.

**Comment by Quasilyte** [comment]
The "always prefer VEX over EVEX" rule combined with "no explicit K0" or any other way to enforce EVEX encoding lead to this:
```asm
// VEX -- OK.
VADDPD (BX), X9, X2

// Two possible outcomes:
// a) signal error: "instruction does not support zeroing".
// b) select EVEX-encoded form.
VADDPD.Z (BX), X9, X2
```
I do believe that `b` option is better, but it may require some woodoo in implementation, because most form matching is done over the operands. 
Both examples above have same operands, which complicates resolution a bit.

In my opinion, it's `+1` to "explicit K0" (XED-style).

**Comment by TocarIP** [comment]
I'm not sure that VADDPD.Z (BX), X9, X2 is an important case. As far as I understand this will use default write mask k0, so no element will be zeroed. However  we have the same problem with broadcasting, which can be useful without any masks.

**Comment by Quasilyte** [comment]
With a simple rule like "skip non-EVEX forms if instruction has any suffixes", we can solve those issues of operand based matching:
```asm
	// Forced EVEX encoding due to suffixes.
	VADDPD.B4 2032(DX), X0, X0         // 62f1fd185882f0070000
	VADDPD.B8 2032(DX), Y0, Y0         // 62f1fd385882f0070000
```

This is possible because x86 uses suffixes only for AVX512 features.
Even if this changes in future, it is possible to maintain such behavior in backwards-compatible way.

**Comment by Quasilyte** [comment]
@TocarIP, zeroing without masking is permitted by GAS, but rejected by, for example, XED.

It can be used to force EVEX encoding when VEX will be selected otherwise (see above).

**Comment by Quasilyte** [comment]
Up-to-date examples: https://golang.org/cl/107217.

**Comment by rsc** [comment]
Ping @cherymui. Please close this issue if you are happy with the decisions documented on the wiki page.

**Comment by cherrymui** [comment]
The wiki page looks ok to me. Closing.

For testing, there is #25724 still open. If we do anything there, it may affect the design and the wiki page. But we can discuss it the there.
