### ISSUE TITLE
strings: please improve documentation for strings.Builder

### ISSUE THREAD

**Issue by jech** [golang/go#22778]
I think that the documentation of `strings.Builder` could be improved by adding a few sentences that compare it to `bytes.Buffer`.  More exactly, I'd like to see:

  * a pointer to `bytes.Buffer`;
  * a list of the methods that `strings.Builder` is lacking as compared to `bytes.Buffer`.

**Comment by bradfitz** [comment]
We could do the first bullet, but I don't want to do the second bullet. That seems too verbose for its utility.

**Comment by jech** [comment]
You could at least mention that Builder lacks the Bytes method, which is the main point as far as I understand.

**Comment by MateusAmin** [comment]
I have read through the relevant discussions/changes/sources and would be happy to help improve the docs for strings.Builder. May I be assigned to this issue?

**Comment by bradfitz** [comment]
@MateusAmin, just send a change if you have one. We rarely use the GitHub assignee feature.

**Comment by rsc** [comment]
@bradfitz maybe it would make sense instead to put a note in bytes.Buffer that if you want to construct a string, using strings.Builder might be more efficient?
