### ISSUE TITLE
cmd/test2json: handle running command and processing output

### ISSUE THREAD

**Issue by rsc** [golang/go#22789]
The official way to get JSON output from a test binary foo.test is

	./foo.test -test.v 2>&1 | go tool test2json

but that's annoying on Unix and harder on Windows. Probably go tool test2json should accept a command to run and process:

	go tool test2json ./foo.test -test.v

**Comment by zolotov** [comment]
`go tool test2json ./foo.test -test.v` is the solution for cross-platform running.

Still, I would prefer something like `./foo.test -test.json`. It's consistent with the rest of the testing arguments and it's definitely debuggable with Delve. I'm not sure whether Delve will work fine with the `go tool test2json` tool.

**Comment by zolotov** [comment]
For some reason my comment was just ignored. Filed #23033
