### ISSUE TITLE
doc: GoLand is misspelled ("Gogland") at /doc/editors.html

### ISSUE THREAD

**Issue by wdrum** [golang/go#22784]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
N/A (documentation issue)

### Does this issue reproduce with the latest release?
N/A (documentation issue)

### What operating system and processor architecture are you using (`go env`)?
N/A (documentation issue)

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
"GoLand"

### What did you see instead?
"Gogland"

**Comment by cespare** [comment]
(Gogland was renamed to GoLand.)

**Comment by dlsniper** [comment]
This is addressed in https://golang.org/cl/75811/
