### ISSUE TITLE
net/url Not preserving raw URL with %25

### ISSUE THREAD

**Issue by theory** [golang/go#22783]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.1 darwin/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/david/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/h0_940zx2j38gfnkrt3xcc5c0000gn/T/go-build797957211=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

I want to get at a raw URL path that contains `%25`.  [This program](https://play.golang.org/p/Mvq1A411Oc) demonstrates the attempt.

### What did you expect to see?

I would expect the output to be:

    Path:    `/here%20there`
    RawPath: `/here%2520there`

### What did you see instead?

Instead, the output is:

    Path:    `/here%20there`
    RawPath: `

RawPath is not set. Should it be? Is there some other way to get back the original path with `%25` preserved?

**Comment by theory** [comment]
Ah-ha, `EscapedPath()` seems to return what I need. I find the various path-handling interfaces a bit confusing.

**Comment by mvdan** [comment]
So there isn't an issue to be fixed here?

**Comment by theory** [comment]
I do wish there was a way to get back the path exactly as it was in the parsed string, but using `EscapedPath()` solves my immediate problem. Thanks.
