### ISSUE TITLE
doc: add Go to the list of languages at syntax-across-languages-per-language

### ISSUE THREAD

**Issue by kasajian** [golang/go#22793]
Looks like Go is missing from the list:
http://rigaux.org/language-study/syntax-across-languages-per-language/what-is-missing.html

**Comment by awoodbeck** [comment]
My PR was merged.  Go is marked as "all done."  Please have a look when you get a chance and suggest tweaks, if any.

http://rigaux.org/language-study/syntax-across-languages-per-language/what-is-missing.html

**Comment by ianlancetaylor** [comment]
@awoodbeck Thanks for doing that.  Closing this issue.
