### ISSUE TITLE
html/template: tags are stripped in attributes for template.HTML type

### ISSUE THREAD

**Issue by opennota** [golang/go#22795]
Not sure if it's a bug, but it is certainly a little surprising. Reported [here](https://www.reddit.com/r/golang/comments/7dpkke/how_can_i_use_templatehtml_inside_a_tag/).

### What version of Go are you using (`go version`)?

1.9.2

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/opennota/gocode"
GORACE=""
GOROOT="/home/opennota/go"
GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build049660887=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

https://play.golang.org/p/sfuDrve8rZ

### What did you expect to see?

`<input value="<b>text</b>">` or `<input value="&lt;b&gt;text&lt;/b&gt;">`

### What did you see instead?

`<input value="text">`

**Comment by titanous** [comment]
This is working as intended. Use [`HTMLAttr`](https://golang.org/pkg/html/template/#HTMLAttr) to opt-in to the potentially unsafe behavior of including unescaped HTML in attribute values.
