### ISSUE TITLE
cmd/go: -outputdir being ignored by go test

### ISSUE THREAD

**Issue by lawrencewoodman** [golang/go#22804]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +e4a3043d1d Sun Nov 19 05:06:59 2017 +0000 linux/amd64

### Does this issue reproduce with the latest release?

No, it works fine with v1.9.2

### What operating system and processor architecture are you using (`go env`)?

amd64

### What did you do?

From the root of a package I wanted to test I ran:
`go test -covermode=count -coverprofile=profile.coverprofile -outputdir=/tmp/coverprofiles`

### What did you expect to see?

I expected to find the file `profile.coverprofile` in `/tmp/coverprofiles`.

### What did you see instead?

The directory `/tmp/coverprofiles` was empty and instead the file `profile.coverprofile` was in the current directory.

**Comment by odeke-em** [comment]
I can confirm that CL https://go-review.googlesource.com/76875
and commit 283558e42b88a6afa39da6ad4ae87558dc053776 is the cause of this regression.

In particular the lines
https://github.com/golang/go/commit/283558e42b88a6afa39da6ad4ae87558dc053776#diff-acaf53a9cd478507ebbcf85037940b4dR1231
or rather the merging in https://github.com/golang/go/blob/283558e42b88a6afa39da6ad4ae87558dc053776/src/cmd/go/internal/test/test.go#L1230-L1232 that breaks it.

**Comment by rsc** [comment]
What a strange flag.
