### ISSUE TITLE
go/ast: define value for the direction of bidirectional channel

### ISSUE THREAD

**Issue by nishanths** [golang/go#22815]
The value for the direction of a bidirectional channel isn't defined in the `go/ast` package [1]. The parser method,`(*go/ast.parser).parseChanType`, uses `ast.SEND | ast.RECV` as a substitute. 

The proposal is to either: 

1. Declare a constant in package ast: `BOTH = SEND | RECV`; or
2. Document in package ast that a bidirectional channel's direction has the value `SEND | RECV`.

Either option will provide a documented value that clients of package ast can use.

[1] https://tip.golang.org/pkg/go/ast/#ChanDir

**Comment by rsc** [comment]
Too late to add new API to Go 1.10.

**Comment by dominikh** [comment]
This should be a simple documentation fix. ChanDir is intended as a bit mask, shown by SEND's and RECV's definition as `1 << iota`, but ChanDir's documentation says that "The direction of a channel type is indicated by one of the following constants".
