### ISSUE TITLE
compile: version "go1.9" does not match go tool version "go1.9.2"

### ISSUE THREAD

**Issue by forging2012** [golang/go#22814]
```
 go get -u github.com/go-ego/gse
# github.com/go-ego/gse/vendor/github.com/go-ego/cedar
compile: version "go1.9" does not match go tool version "go1.9.2"


➜  ~ go version
go version go1.9.2 darwin/amd64

➜  ~ brew -v      
Homebrew 1.3.6
Homebrew/homebrew-core (git revision d3a09; last commit 2017-10-29)
```

**Comment by forging2012** [comment]
I try uninstall go 1.9.2 ，then, run go get OK!
Mac 10.13

➜  ~ brew uninstall go
Error: Refusing to uninstall /usr/local/Cellar/go/1.9.2
because it is required by glide 0.13.0, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies go
➜  ~ brew uninstall --ignore-dependencies go
Uninstalling /usr/local/Cellar/go/1.9.2... (7,646 files, 293.9MB)
go 1.9, 1.8.3 2 are still installed.
Remove all versions with `brew uninstall --force go`.
➜  ~ go version
go version go1.9 darwin/amd64
➜  ~ go get -u github.com/go-ego/gse        
➜  ~

**Comment by bradfitz** [comment]
The error is telling you that you have a weird mix of Go versions on top of one another, or mixed up together in your $PATH.

For questions about how to install Go, see https://golang.org/wiki/Questions.

**Comment by lindner** [comment]
I had this same problem recently.  I had a version of go in my $PATH that didn't match the data in $GOROOT

In my specific instance I had installed go by hand in /usr/local/go and then brew installed a different version in /usr/local/bin

**Comment by forging2012** [comment]
@lindner 

Just do  
brew uninstall --ignore-dependencies go
All fine!
