### ISSUE TITLE
build: run.bash fails in ../misc/swig/{stdio,callback}

### ISSUE THREAD

**Issue by dr2chase** [golang/go#22824]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +5f29a7a705 Mon Nov 20 20:29:43 2017 +0000 darwin/amd64
(Essentially tip as of this bug report)

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/drchase/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/drchase/GoogleDrive/work/gocode"
GORACE=""
GOROOT="/Users/drchase/GoogleDrive/work/go-quick"
GOTMPDIR=""
GOTOOLDIR="/Users/drchase/GoogleDrive/work/go-quick/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y4/90mx9nxx54bfvgh9jh0_410h0095tn/T/go-build662683396=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
./all.bash

### What did you expect to see?
Run to completion, successfully

### What did you see instead?
```
##### ../misc/swig/stdio
# _/Users/drchase/GoogleDrive/work/go-quick/misc/swig/stdio
:3: Error: Unable to find 'go.swg'
FAIL	_/Users/drchase/GoogleDrive/work/go-quick/misc/swig/stdio [build failed]
2017/11/20 17:35:58 Failed: exit status 2

##### ../misc/swig/callback
# _/Users/drchase/GoogleDrive/work/go-quick/misc/swig/callback
:3: Error: Unable to find 'go.swg'
callback.swigcxx:14: Error: Unable to find 'std_string.i'
FAIL	_/Users/drchase/GoogleDrive/work/go-quick/misc/swig/callback [build failed]
2017/11/20 17:35:59 Failed: exit status 2
```

I could not reproduce this on Linux; however, it seemed not to run the swig tests there at all.

**Comment by dr2chase** [comment]
More info, perhaps relevant (do we need a version check?)
```
~/GoogleDrive/work/go-quick/src$ which swig
/opt/local/bin/swig
~/GoogleDrive/work/go-quick/src$ swig -version
SWIG Version 3.0.12
Compiled with /usr/bin/clang++ [x86_64-apple-darwin16.4.0]
Configured options: +pcre
Please see http://www.swig.org for reporting bugs and further information
```

**Comment by dr2chase** [comment]
@rsc Any ideas?

**Comment by ianlancetaylor** [comment]
Sounds like something is broken with your swig installation.  3.0.12 is new enough.  But SWIG is complaining that it can't find go.swg, which should normally be available in INSTALLDIR/share/swig/3.0.12, in your care presumably /opt/local/share/swig/3.0.12.  Your SWIG is installed in /opt/local/bin; did you install it yourself?  Where did it come from?

**Comment by dr2chase** [comment]
It came from MacPorts, some other piece of software thought that it needed it.

**Comment by dr2chase** [comment]
"Workaround": sudo /opt/local/bin/port install swig-go

So perhaps the swig test could be a bit more discriminating, but the workaround is an easy one.

**Comment by laboger** [comment]
I also hit a problem like this on one of our systems. I didn't dig into too much but it looked like the swig install didn't agree with what the test required. I agree with the last comment by @dr2chase, the test could be more discriminating.
