### ISSUE TITLE
x/crypto/ssh/terminal: ReadPassword does not support umlauts on Windows

### ISSUE THREAD

**Issue by levrik** [golang/go#22828]
### What version of Go are you using (`go version`)?
`go version go1.9.2 windows/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\development\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

Execute this on Gist on Windows (https://gist.github.com/levrik/99210259065679da20c3c66ef383eea9) and enter some umlauts in the password prompt _(e.g. ö, ü or ä)_.

### What did you expect to see?

![image](https://user-images.githubusercontent.com/9491603/33065563-825c6df2-cea9-11e7-8e87-ee894c1ff49f.png)
_(Screenshot taken on `go version go1.9.2 darwin/amd64`)_

### What did you see instead?

![pasted image at 2017_11_21 10_39 am](https://user-images.githubusercontent.com/9491603/33065524-6a9767a8-cea9-11e7-9991-43d5f52bcee5.png)

This was discovered when a colleague tried to use a new version of an internal command line tool and it didn't accept the correct password anymore (password was supplied via command line flag before).

**Comment by levrik** [comment]
@bradfitz @alexbrainman Just looked a bit more into this issue. Basically the problem is that Go expects UTF-8 but the Windows console uses Code Page xxx. Which code page exactly depends on the configured language (for example US English uses 437, German uses 850).

**Comment by mattn** [comment]
As far as I can see, `x/crypto/ssh/terminal#ReadPassword` take string argument not int.

**Comment by mattn** [comment]
Oh, sorry. My bad. it is implemented in util_windows.go

**Comment by mattn** [comment]
This should fix the issue.

```diff
diff --git a/ssh/terminal/util_windows.go b/ssh/terminal/util_windows.go
index 60979cc..e7dc952 100644
--- a/ssh/terminal/util_windows.go
+++ b/ssh/terminal/util_windows.go
@@ -17,6 +17,8 @@
 package terminal
 
 import (
+	"os"
+
 	"golang.org/x/sys/windows"
 )
 
@@ -98,5 +100,5 @@ func ReadPassword(fd int) ([]byte, error) {
 		windows.SetConsoleMode(windows.Handle(fd), old)
 	}()
 
-	return readPasswordLine(passwordReader(fd))
+	return readPasswordLine(os.NewFile(uintptr(fd), "sysfile"))
 }
```

**Comment by egonelbre** [comment]
When you read from stdin it uses default codepage. Printing the byte-sequence verifies this.

GetConsoleCP (https://docs.microsoft.com/en-us/windows/console/getconsolecp) can be used to get the current code page. SetConsoleCP can be used to switch to code page 65001 (utf8) -- but, initial testing only resulted getting 0 for characters. One possibility is to lookup the active code-page and translate after reading the buffer. However, I suspect that Code Page can change during typing.

readPasswordLine seems to need adjusting for multi-byte characters as well.

**Comment by forskning** [comment]
Also on Windows codepage 850 using levrik 's code sample the Danish characters (æ,ø,å) do not render.

**Comment by levrik** [comment]
@forskning I think the German umlauts are included in the English code page so it works fine.

**Comment by bronze1man** [comment]
I think you should use windows api MultiByteToWideChar and GetConsoleCP to solve your problem.
Implement another MultiByteToWideChar in golang will make the binary very large if you include gbk support.

By the way `code page 65001 (utf8)` on chinese win7 is an useless stuff. It looks like code page 437. But it will crash the process(include ipconfig.exe) if you want to output some chinese char.

**Comment by alexbrainman** [comment]
@levrik did you try https://golang.org/cl/79335 ? Does it fixes your problem?
I think it should work for you.

Thank you.

Alex

**Comment by forskning** [comment]
@alex I confirm after applying CL 79335 and running cmd.exe set to Code Page 850

that with the keyboard layout set to DE that ö, ü, ä, and ß, all render

and with the keyboard layout set to DA that ä, ö, æ, ø, and å, all render

**Comment by levrik** [comment]
@alexbrainman sorry, didn't have the time to test yet. Will try it out this evening after work.

**Comment by alexbrainman** [comment]
> I confirm after applying CL 79335 and running cmd.exe set to Code Page 850
> 
> that with the keyboard layout set to DE that ö, ü, ä, and ß, all render
> 
> and with the keyboard layout set to DA that ä, ö, æ, ø, and å, all render

Thanks for checking.

> Will try it out this evening after work.

Sounds good. I will wait.

Alex

**Comment by forskning** [comment]
My circa 2009 Danish Windows XP defaults to cp850.

But I think cp850 has since been superseded by cp1252.

The below link is regarding Tcl. (one can search therein for 1252)

http://nurmi-labs.blogspot.com/2017/05/9pvfs.html

FWIW, a more specific title might be the following.

ReadPassword does not support Western European Code Page

**Comment by cznic** [comment]
Genuine question(s): What's the advantage of using code pages on Windows? Why do not people switch to UTF-8? Is that possible on Windows?

**Comment by forskning** [comment]
http://nurmi-labs.blogspot.com/2016/11/git.html

for git-bash.exe I have LANG=da_DK.UTF-8

but as it utilises the Windows console $LANG has no effect on the current code in question

for tcsh.exe, which I added to my system and I run in mintty.exe, I have LANG=en_US

https://en.wikipedia.org/wiki/Code_page_850

above is a wikipedia page including information as

"code page 850 is the primary code page and default OEM code page in many countries, including various English-speaking locales (e.g. in the United Kingdom, Ireland, and Canada)"

and,

"Systems largely replaced code page 850 with, first, Windows-1252 (often mislabeled as ISO-8859-1), and later with UCS-2, and finally with UTF-16."

**Comment by bronze1man** [comment]
> What's the advantage of using code pages on Windows?

It works.

> Why do not people switch to UTF-8?

`code page 65001 (utf8)` on chinese win7 is an useless stuff. It looks like code page 437. But it will crash the process(include ipconfig.exe) if you want to output some chinese char.

> Is that possible on Windows?

No. At least I can not solve a way to solve this problem by setting some stuff. It has a stuff called `code page 65001 (utf8)`, but `code page 65001 (utf8)` is not useful with chinese win7.(it may work with english win7)

**Comment by forskning** [comment]
There is S. Quinlan's 9pm which contains the 9term.exe dumb terminal.

NB: Some golang code is expected to run in an intelligent termnial, and
this being dated software some Chinese characters would not be expected 
to render.

https://9p.io/magic/webls?dir=/sources/extra
9pm051031.zip

https://github.com/nurmi-labs/9pm (copied to GitHub)

http://nurmi-labs.blogspot.com/2015/10/regexp.html (font settings)

And cognisant of different file permissions in a separate environment
subsystem, one could run an xterminal under WSL with VcXsrv.

http://nurmi-labs.blogspot.com/2017/03/p9p.html

NB: I haven't resolved some issues with the German keyboard layout for WeirdX.

**Comment by levrik** [comment]
@alexbrainman need to move my test to tomorrow. got a bit late today.

**Comment by levrik** [comment]
@alexbrainman Fix is working for me. Thanks!

**Comment by alexbrainman** [comment]
> @alexbrainman Fix is working for me. Thanks!

Thank you for confirming it.

Alex
