### ISSUE TITLE
cmd/go: go test -c does not apply specified gcflags to the test package

### ISSUE THREAD

**Issue by aarzilli** [golang/go#22831]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version devel +5f29a7a Mon Nov 20 20:29:43 2017 +0000 linux/amd64
```

### What did you do?

```
go get github.com/aarzilli/testflags
cd $GOPATH/src/github.com/aarzilli/testflags
go clean -cache && go test -c -gcflags '-N -l'
```
### What did you expect to see?

flags -N -l applied to the test package (i.e. the one defined in main_test.go)

### What did you see instead?

The flags are applied to `github.com/aarzilli/testflags` but not to the test package.

**Comment by rsc** [comment]
Indeed. Will fix.
