### ISSUE TITLE
cmd/go: scope of -gcflags

### ISSUE THREAD

**Issue by aarzilli** [golang/go#22833]
I see from the draft that:

> The go build -asmflags, -gcflags, -gccgoflags, and -ldflags options now apply by default only to the packages listed directly on the command line

I missed when this changed happened but I liked it a lot more when -gcflags applied to all packages that contributed to the executable. I was hoping delve could drop the `-a` command line option with 1.10 and take advantage of caching but with this behavior I don't think we can.

cc @derekparker @heschik @hyangah

**Comment by huguesb** [comment]
See #22527 for the discussion that lead to this change.

**Comment by aarzilli** [comment]
Alright, I see that `-gcflags=all=...` exists, that's good enough for me.
