### ISSUE TITLE
cmd/compile: add error if unsigned tested for negativity

### ISSUE THREAD

**Issue by SMerrony** [golang/go#22844]
### What version of Go are you using (`go version`)?
1.9,2

### Does this issue reproduce with the latest release?

Yes
### What operating system and processor architecture are you using (`go env`)?
amd64/windows and also amd64/linux

### What did you do?
Compiled this...
```package main
import "fmt"
import "time"
func main() {
	var uns uint32
	uns = uint32(time.Now().Weekday())
	if uns < 0 {
		fmt.Printf("Negative uns: %d\n", uns)
	}
}
```

### What did you expect to see?
Error when unsigned is tested for negative.

### What did you see instead?
Nothing

I believe it would be very useful if this error could be trapped at compile time.

**Comment by ALTree** [comment]
This has been proposed (and rejected) in the past. 

Ref: #8601.

Initially, the proposal said
>  the compiler should refuse to compile this statement.

but the commenters agreed that a vet check may be more appropriate.

Someone send a change to add a vet check, but it wasn't merged. Apparently, it didn't satisfy the 3 vet requirements (correctness, precision, frequency).

**Comment by ianlancetaylor** [comment]
Closing as dup.
