### ISSUE TITLE
math/big: r.Exp(x, 1, m) wrong if r is initially non-zero [Go1.9]

### ISSUE THREAD

**Issue by rsc** [golang/go#22842]
Go1.9.3 issue for #22830.

**Comment by andybons** [comment]
CL 81055 OK for Go 1.9.3.

**Comment by andybons** [comment]
go1.9.3 has been packaged and includes:

  - [CL 78995](https://golang.org/cl/78995) math/big: protect against aliasing in nat\.divLarge

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Jan 22 21:02:57 UTC
