### ISSUE TITLE
cmd/vet: does not report possible formatting directive with %v

### ISSUE THREAD

**Issue by rsc** [golang/go#22847]
I don't understand why vet reports no problems here:

```
$ cat x_test.go
package p

import (
	"log"
	"testing"
)

func Test(t *testing.T) {}

func f() {
	log.Fatal("error: %v", 1)
}
$ go test x_test.go
ok  	command-line-arguments	0.012s
$ 
```

**Comment by mvdan** [comment]
Having a look at this at the moment. Seems unrelated to test files, as this one fails too:

```
 $ cat f.go
package p

import "log"

func F() {
        log.Fatal("%v", 1)
}
$ go vet f.go
$ go1 vet f.go
f.go:6: possible formatting directive in Fatal call
exit status 1
```

Note how this seems to be a regression from 1.9, however, as it works fine there.

**Comment by mvdan** [comment]
It looks like this was a small regression in fc768da8b8030e6f344be6bbc86ae08c30f02849 - likely an issue in the regex. CL coming soon.
