### ISSUE TITLE
math/big: r.Exp(x, 1, m) wrong if r is initially non-zero [Go1.8]

### ISSUE THREAD

**Issue by rsc** [golang/go#22843]
Go1.8.6 issue for #22830.

**Comment by andybons** [comment]
CL 78995 OK for Go 1.8.6.

**Comment by andybons** [comment]
go1.8.6 has been packaged and includes:

  - [CL 78995](https://golang.org/cl/78995) math/big: protect against aliasing in nat\.divLarge

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Jan 23 05:08:34 UTC
