### ISSUE TITLE
net/textproto: allow manually register canonicalMIMEHeaderKey

### ISSUE THREAD

**Issue by j16sdiz** [golang/go#22864]
This is a feature request related to  #18476 #18196 #5022 #18495.
Instead of controlling each request/response, may we have a function to register my own canonicalMIMEHeaderKey  ?

The HTTP problem "will be" solved with HTTP/2, but MIME is more then just HTTP.
Instead of one-header at a time, may be we can have something easier to override?

**Comment by bradfitz** [comment]
What's the problem?

**Comment by j16sdiz** [comment]
Legacy, standard noncompliance client that do header in case sensitive way?

I am doing a mitm proxy for a binaryonly app to inject a auth header for our internal firewall.
When I get the header, the case is not preserved and broke the legacy app.

Apache mod_proxy, nginx, squid all do that in case preserving way. But there is no way to do this in go without rewriting the whole Round Tripper.

**Comment by opennota** [comment]
My IP camera wouldn't accept a canonicalized `CSeq` key (RTSP protocol). I did solve it, though.

**Comment by j16sdiz** [comment]
I saw the previous proposal to control the case of header have been rejected.
That's why I am proposing an alternative way to do this -- allow adding my own entry to the hardcoded list.

**Comment by ianlancetaylor** [comment]
We aren't going to add new API to the standard library to support legacy clients that are not standards compliant.  You will have to make your own copy of the net/textproto package, or run a transformation on the input stream.
