### ISSUE TITLE
x/crypto/acme: NameToCertificate is not used

### ISSUE THREAD

**Issue by winteraz** [golang/go#22869]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes.

### What operating system and processor architecture are you using (`go env`)?
linux, amd64

### What did you do?
I'm trying to create a server that serves encrypted traffic using ACME  for certain domains and using NameToCertificate for other domains  not in the ACME whitelist. In my use case I have several domain names whitelisted using acme (e.g. example.com, example1.com) and one served using NameToCertificate( *.example.com) due the fact the ACME provider(Letsencrypt) doesn't support wildcard. 
```


func CertificatesFromFile(crt, key string) (map[string]*tls.Certificate, error) {
	cer, err := tls.LoadX509KeyPair(crt, key)
	if err != nil {
		return nil, err
	}
	cfg := &tls.Config{Certificates: []tls.Certificate{cer}}
	cfg.BuildNameToCertificate()
	return cfg.NameToCertificate, nil
}

// this supports both acme and file based certificates
func ListenAndServeFileCert(hn http.Handler, port int, nameToCertificate map[string]*tls.Certificate, domain ...string) {

	m := autocert.Manager{
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist(domain...),
		Cache:      autocert.DirCache("/root/letsencrypt"),
	}

	config := &tls.Config{
		GetCertificate:    m.GetCertificate,
		NameToCertificate: nameToCertificate,
	}
	for k := range nameToCertificate {
		config.Certificates = append(config.Certificates, *nameToCertificate[k])
	}
	s := &http.Server{
		TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler)),
		Handler:      hn,
		Addr:         ":" + strconv.Itoa(port),
		TLSConfig:    config,
	}


	panic(s.ListenAndServeTLS("", ""))
}

```

### What did you expect to see?
When a domain that's not whitelisted in the acme config is requested I expected tls to range over NameToCertificate and selected a certificate matching the domain (in my case a wildcard certificate *.example.com)

### What did you see instead?
2017/11/24 11:11:00 http: TLS handshake error from x.x.x.x:34356: acme/autocert: host not configured

**Comment by winteraz** [comment]
As workaround I wrapped the expected behaviour in a GetCertificate. It works but I think this is still a bug that should be fixed.	
``
getCert := func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
		crt, err := m.GetCertificate(hello)
		if err == nil && crt != nil{
			return crt, nil
		}
		// look on nameToCertificate
		for domain, crt := range nameToCertificate {
			// expect wildcard
			ok, err := regexp.MatchString("."+domain, hello.ServerName)
			if err != nil {
				log.Error(err)
				continue
			}
			if ok {
				return crt, nil
			}
		}

		return nil, fmt.Errorf("No name cert found for %s", hello.ServerName)
	}
``

**Comment by x1ddos** [comment]
Not sure what it is exactly that the issue here describes as a bug in x/crypto/acme/autocert. The error "host not configured" means that the host is not allowed. You enforced with `autocert.HostWhitelist(domain...)`.

Perhaps, you just want a custom host policy?
 It is just a function which you can provide: https://godoc.org/golang.org/x/crypto/acme/autocert#HostPolicy.

If you look at the [HostWhitelist](https://godoc.org/golang.org/x/crypto/acme/autocert#HostWhitelist) docs, it says:

> Only exact matches are currently supported. Subdomains, regexp or wildcard will not match.

Is that what this bug is about, you'd like HostWhitelist to support wildcard?
