### ISSUE TITLE
fmt.Printf: unexpected behaviour of "%%" with index

### ISSUE THREAD

**Issue by octomarat** [golang/go#22867]
### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
macOS Sierra 10.12.6, darwin/amd64

### What did you do?
Run the following code

```
package main

import "fmt"

func main() {
	fmt.Printf("%%", 1, 2, 3, 4, 5, 6, 7)
	fmt.Printf("%[1]%", 1, 2, 3, 4, 5, 6, 7)
}

```

### What did you expect to see?

In both cases, error about extra arguments is printed.

### What did you see instead?

In the first case, I see expected error. In the second case I see '%' printed. So, adding index to '%%' leads to unexpected and misleading behaviour.

**Comment by martisch** [comment]
Note that not erroring on unused indexes once an index is used is not specific to %. Once an index is used with any verb there will be no error for unused verbs.

```
fmt.Printf("%[1]v", 1, 2, 3, 4, 5, 6, 7)
```

**Comment by robpike** [comment]
This is working as intended, although the reasoning is subtle and obscure. In general, a call to Printf might use various formats depending on the configuration. Think of an error message that is adjusted for each language in which the message is printed. Some of the arguments might be language-specific.
