### ISSUE TITLE
cmd/go:  main package in GoPath/src/ runs "go install" fail.

### ISSUE THREAD

**Issue by vipally** [golang/go#22863]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\gocode
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dai
zejun\AppData\Local\Temp\go-build824272051=/tmp/go-build -gno-record-gcc-switche
s
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
Create a hello world main package in GoPath/src.And run "go install"

package main
func main(){
    println("hello world!")
}

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
"go install" runs well, and install in GoPath/bin.

### What did you see instead?
go install: no install location for directory E:\gocode\\src outside GOPATH
	For more details see: 'go help gopath'

**Comment by davecheney** [comment]
Try removing the semicolon at the end of your %GOPATH% (mostly a guess)

**Comment by cznic** [comment]
For `go install` to work the package must live _under_, not _in_ `$GOPATH/src` which is what the error message  says.

**Comment by vipally** [comment]
I have made a patch to fix this case:
https://github.com/vipally/go/commit/fa56999475f5f9cd66d366987c58517fc6247411
https://github.com/vipally/go/tree/issue_22863
For your information, thanks.

**Comment by bradfitz** [comment]
This is working as intended. Its name can't be inferred if it's at the root of $GOPATH/src. It needs a directory under that to get a name.
