### ISSUE TITLE
cmd/compile: type alias error when compiled with assembly file including go_asm.h

### ISSUE THREAD

**Issue by zhaozhiqianghw** [golang/go#22877]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.9.2

### Does this issue reproduce with the latest release?
I don't know

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

I have two files, `main.go` and `asm_amd64.s`

```go
// main.go
package main

type S struct {
     i int
}

type SS = S

func Sub()

func main() {
     Sub()
}
```

and 

```go
#include "go_asm.h"
#include "textflag.h"

TEXT  ·Sub(SB), NOSPLIT, $0-16
       RET
```
### What did you expect to see?

I use `go build -o main`, expect a success compiling.

### What did you see instead?

```bash
# _/home/zhaozq/work/test/go/typealias
go_asm.h:6: redefinition of macro: S__size
make: *** [all] Error 2
```

The log tells me that the `go_asm.h` is wrong, so I use `go tool compile -o main.o -asmhdr go_asm.h main.go`, get `go_asm.h` as follows:
```go
// generated by compile -asmhdr from package main

#define S__size 8
#define S_i 0
#define S__size 8
#define SS_i 0
```

Actually, this is a wrong file. So when I remove the statement `#include go_asm.h` in `asm_amd64.s`, the compiling is successful. Because this error file doesn't been used.

And I find this file is generated in `cmd/compile/internal/gc/export.go:370`

```go
func dumpasmhdr() {
      b, err := bio.Create(asmhdr)
      if err != nil {
            Fatalf("%v", err)
      }
      fmt.Fprintf(b, "// generated by compile -asmhdr from package %s\n\n", localpkg.Name)
      for _, n := range asmlist {
            if n.Sym.IsBlank() {
                  continue
            }
            switch n.Op {
            case OLITERAL:
                  fmt.Fprintf(b, "#define const_%s %#v\n", n.Sym.Name, n.Val())

            case OTYPE:
                  t := n.Type
                  if !t.IsStruct() || t.StructType().Map != nil || t.IsFuncArgStruct() {
                        break
                  }
                  fmt.Fprintf(b, "#define %s__size %d\n", t.Sym.Name, int(t.Width))
                  for _, t := range t.Fields().Slice() {
                        if !t.Sym.IsBlank() {
                              fmt.Fprintf(b, "#define %s_%s %d\n", n.Sym.Name, t.Sym.Name, int(t.Offset))
                        }
                  }
            }
      }

      b.Close()
}
```

The code at `cmd/compile/internal/gc/export.go:389` is the error.
```go
 fmt.Fprintf(b, "#define %s__size %d\n", t.Sym.Name, int(t.Width))
```

Because the Sym `t` has been change at `cmd/compile/internal/gc/typecheck.go:3821`
```
n.Type = p.Ntype.Type
```

So the code at  `cmd/compile/internal/gc/export.go:389`  should be changed to

```go
 fmt.Fprintf(b, "#define %s__size %d\n", n.Sym.Name, int(t.Width))
```

When I changed this, the `go_asm.h` becomes

```go
// generated by compile -asmhdr from package main

#define S__size 8
#define S_i 0
#define SS__size 8
#define SS_i 0
```

Then the world becomes good.

**Comment by ianlancetaylor** [comment]
CC @mdempsky
