### ISSUE TITLE
Casting uint8 to byte

### ISSUE THREAD

**Issue by sinnlosername** [golang/go#22879]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04/amd64

### What did you do?
```GO
type Test []byte
func main() {
    	var in interface{}
	in = []uint8 {1,3,3,7}

	var array Test
	array = in.(Test) //panic
}
```

### What did you expect to see?
Per documentation uint8 is an alias for byte. So it should be able to cast []uint8 to a custom type which extends []byte. It also works if I cast it to []byte first. Like:

```GO
type Test []byte
func main() {
    	var in interface{}
	in = []uint8 {1,3,3,7}

	var array Test
	array = in.([]byte) //No problem
}
```
### What did you see instead?
It is unable to cast it. I need to cast it to []byte first before I can cast it to "Test".

**Comment by bradfitz** [comment]
> So it should be able to cast []uint8 to a custom type which extends []byte

No, that's not how the language works. See https://golang.org/doc/faq#convert_slice_with_same_underlying_type

For questions about Go, see https://golang.org/wiki/Questions.
