### ISSUE TITLE
latest build run fail in ubuntu 12.04

### ISSUE THREAD

**Issue by mathslimin** [golang/go#22884]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2.linux-386.tar.gz

### Does this issue reproduce with the latest release?

yes
### What operating system and processor architecture are you using (`go env`)?

ubuntu 12.04
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?

go build -o bin/agent/falcon-agent ./modules/agent
# runtime
/usr/local/go/src/runtime/os_linux.go:27:16: _FUTEX_WAIT redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:22:16
/usr/local/go/src/runtime/os_linux.go:28:16: _FUTEX_WAKE redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:23:16
/usr/local/go/src/runtime/os_linux.go:36:46: futexsleep redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:31:46
/usr/local/go/src/runtime/os_linux.go:67:36: futexwakeup redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:62:36
/usr/local/go/src/runtime/os_linux.go:83:21: getproccount redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:78:21
/usr/local/go/src/runtime/os_linux.go:112:26: _CLONE_VM redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:104:26
/usr/local/go/src/runtime/os_linux.go:113:26: _CLONE_FS redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:105:26
/usr/local/go/src/runtime/os_linux.go:114:26: _CLONE_FILES redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:106:26
/usr/local/go/src/runtime/os_linux.go:115:26: _CLONE_SIGHAND redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:107:26
/usr/local/go/src/runtime/os_linux.go:116:26: _CLONE_PTRACE redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:108:26
/usr/local/go/src/runtime/os_linux.go:116:26: too many errors

**Comment by davecheney** [comment]
This error is usually caused by untaring one version of Go over another. Is it possible something like that happened on your machine?

**Comment by mathslimin** [comment]
@davecheney  after install 1.8 version,this issues fixed
