### ISSUE TITLE
encoding/json: reference to obselete RFC

### ISSUE THREAD

**Issue by rajender** [golang/go#22888]
https://tip.golang.org/pkg/encoding/json/ mentions RFC 4627. The RFC 4627 is obsolete by [RFC 7159](https://tools.ietf.org/html/rfc7159).

It looks like current implementation already confirms to RFC 7159. https://play.golang.org/p/lY-b3Ia13k

Should we update the rfc no in the docs?

**Comment by bradfitz** [comment]
You showed that we treat "`2`" as valid JSON. Is that related to the spec diff between RFC 4627 and RFC 7159.

I'd like to see a list of actual changes between the RFCs and then tests for those before we update the docs.

**Comment by rajender** [comment]
Yes. RFC 4627 only allowed json text as either object oo array. RFC 7159 extended it's definition to include any value. Look at https://tools.ietf.org/html/rfc7159#page-15

Quoting that page, 
 "Changed the definition of "JSON text" so that it can be any JSON value, removing the constraint that it be an object or array."

**Comment by bradfitz** [comment]
Sounds good. Feel free to send a change.
