### ISSUE TITLE
net/http: parameterized Routes in Handle

### ISSUE THREAD

**Issue by AyushG3112** [golang/go#22887]
This is a feature request and not a bug. 

As is a basic requirement during path matching, can defining a path parameter be allowed in `http.Handle` and getting the value of the passed parameter in the request as a `map[string]string` be allowed?

**Comment by mvdan** [comment]
As far as I know, `http.ServeMux` is a simple router and should stay that way. If you want more advanced features, there are a ton of routers out there that you can use, such as https://github.com/go-chi/chi and https://github.com/gorilla/mux.

**Comment by AyushG3112** [comment]
I would agree if this was a use case which is not encountered often enough. While I can use 3rd party routers, they do a lot  more stuff under the wraps, causing some overhead. I would prefer not to go through that if possible.

Although if you or anyone could provide a router/Mux with comparable runtime performance, I would appreciate that too

**Comment by mvdan** [comment]
A feature that seems fundamental to one may seem useless to another. You can't have a router that is both useful and free of bloat to everyone's standards.

Have you measured performance on third-party routers to be orders of magnitude slower than that of ServeMux? I would be surprised if it were the case, or if it even mattered in most use cases. I also suspect that the introduction of path arguments and maps would incur extra work and a slow-down no matter what.

As said before, I don't know where the line is drawn for ServeMux. I'm simply trying to point out that adding more features can be a slippery slope, and you already have good alternatives elsewhere.

**Comment by bradfitz** [comment]
Sorry, http.ServeMux's feature set is frozen, at least for Go 1.

I'll leave this open to consider for later.

**Comment by xgfone** [comment]
I hope to add this feature in Go2.

If the std library supplies it, I don't need to import the third-party router.

**Comment by tj** [comment]
A router in stdlib would be sweet IMHO, they're honestly all pretty much the same, barring internal performance differences etc.

**Comment by ofabricio** [comment]
You think a simple util would help?

```go
http.HandleFunc("/users/", func (w http.ResponseWriter, r *http.Request) {
    a := r.VarPath(0) // given "/users/", a == "users"
    b := r.VarPath(1) // given "/users/123", b == "123"
    c := r.VarPath(2) // given "/users/123/something", c == "something"
})
```

At least you can manually check the value inside a handler and call another handler, and everything continues simple.

**Comment by audrenbdb** [comment]
It's pretty much the only thing that stops me and my team from using the default mux. 

Sure chi is fine, but it's stil la third-party to rely on.

**Comment by seankhliao** [comment]
see https://github.com/golang/go/discussions/60227 for the current discussions

**Comment by ianlancetaylor** [comment]
Closing in favor of #60227.
