### ISSUE TITLE
Project source in GOPATH but can't find vendor deps

### ISSUE THREAD

**Issue by tetriscode** [golang/go#22886]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Users/wesr/Development/Go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wesr/Development/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5z/j_4kts6s68bgy3k6_rpv1xt00000gp/T/go-build673464631=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

`$> go run main.go`

### What did you expect to see?

`Server binding to port 3000`

### What did you see instead?

app/app.go:6:2: cannot find package "_/Users/wesr/Development/Go/src/github.com/tetriscode/frwy-api/vendor/github.com/gorilla/sessions" in any of:
	/usr/local/go/src/_/Users/wesr/Development/Go/src/github.com/tetriscode/frwy-api/vendor/github.com/gorilla/sessions (from $GOROOT)
	/Users/wesr/Development/Go/src/_/Users/wesr/Development/Go/src/github.com/tetriscode/frwy-api/vendor/github.com/gorilla/sessions (from $GOPATH)

```
package app

import (
	"encoding/gob"

	"github.com/gorilla/sessions"
)

var (
	Store *sessions.CookieStore
)

func Init() error {
	Store = sessions.NewCookieStore([]byte("something-very-secret"))
	gob.Register(map[string]interface{}{})
	return nil
}
```

Projects are in the vendor directory
```
bash-3.2$ ls
LICENSE			doc.go			sessions.go		store.go
README.md		lex.go			sessions_test.go	store_test.go
bash-3.2$ pwd
/Users/wesr/Development/Go/src/github.com/tetriscode/frwy-api/vendor/github.com/gorilla/sessions
```

**Comment by cznic** [comment]
Does the problem persist if you use `go build` or `go install` instead of `go run main.go`?

**Comment by tetriscode** [comment]
@cznic Yes

**Comment by cznic** [comment]
OK, then please extract a small self-contained reproduction case. It can also be, for example, a Github repository.
