### ISSUE TITLE
Is the accumulation of byte which  more than 255 discarded anyaway?

### ISSUE THREAD

**Issue by diiyw** [golang/go#22898]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8 linux/amd64

### Does this issue reproduce with the latest release?

unknown

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ename/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build810154951=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
```go
package main
import "fmt"
func main(){
	b := []byte{1,255}
	b[1]++
	fmt.Println(b)
}
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

may be "[2 0]"

### What did you see instead?
output "[1 0]"

**Comment by bradfitz** [comment]
This is working as designed.

See https://golang.org/ref/spec#Integer_overflow

For questions about Go, see https://golang.org/wiki/Questions.
