### ISSUE TITLE
net: TestDialTimeout flake on linux-amd64-sid

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22896]
Is it supposed to be dialing 127.0.0.1:0 (the 0 port is weird):

https://build.golang.org/log/450b8cb212512d306aed03190d275f546c332715
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net	5.178s
```

/cc @mikioh

**Comment by ianlancetaylor** [comment]
I've looked through all the code and I've convinced myself that this can not happen.  I also have not been able to reproduce it.

That said, here is another instance:

https://build.golang.org/log/95a745a6f8fed78a9b854b3cbad5986275ffc0cd

**Comment by nilsmagnus** [comment]
```
if nerr, ok := err.(Error); !ok || !nerr.Timeout() {
				t.Fatalf("#%d: %v", i, err)
}
```

It looks to mee that there is an error in the log-message, it should have logged `nerr`, not `err` .

**Comment by nilsmagnus** [comment]
The `:0` port is for testing purposes and comes from line 71, at least according to (https://golang.org/src/net/timeout_test.go)

**Comment by ianlancetaylor** [comment]
@nilsmagnus Logging `err` rather than `nerr` is correct; if `!ok` then `nerr` will be `nil` so we want to log `err`, and if `ok` then logging `err` gives us the same value as logging `nerr` anyhow.

**Comment by agnivade** [comment]
Binding on port 0 is a request to the kernel to look for a free port and bind to it. It _actually_ does not bind to 0. Therefore, it should not be possible to connect to port 0. But that should not be an issue here since the socket filter will prevent the connection from happening in the first place.

However, in both the buildlet failures, the failure happens on item `#5` which has the following values - 

```
{
timeout - 50 * time.Millisecond, 
delta- 0, 
guard- 100 * time.Millisecond, 
max- time.Second
}
```

@bradfitz - Anything suspicious about these values that can cause a flake ? I tried very hard to reproduce but could not.

**Comment by ianlancetaylor** [comment]
ping @mikioh for above question.

**Comment by mikioh** [comment]
I guess that one possibility is that the buildbot, cmd/go or testing package did run the net.test process incorrectly, without the harness of net/internal/socktest package.

**Comment by ianlancetaylor** [comment]
@mikioh I don't see any way that that could happen.

**Comment by mikioh** [comment]
@ianlancetaylor,

I'm also not sure the mechanism, but the evidence, the test failed within 0.00s and attempted to connect to the literal port number zero (as a boobytrap set by me), leads me to the possibility.

**Comment by mikioh** [comment]
> not sure the mechanism

Hm, the harness is naively designed to be unstrapped before the execution of benchmarking, so it depends on the execution order of testing and benchmarking. It's likely that unstrapping happens if the testing goroutine is taken over by one of benchmarking goroutines, like #21090.

**Comment by ianlancetaylor** [comment]
Here are the cases I can find today.  It's perhaps interesting that it always seems to be case 5.

[2017-04-17T18:33:08-73f283f/linux-ppc64-buildlet](https://build.golang.org/log/9fe9ecaf1217678a9a547773692377da5afce5fa):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-04-21T23:43:59-49f54e8/linux-ppc64-buildlet](https://build.golang.org/log/43fef440e6c18f5e1cd919d2ae8c3f0e3ccf875e):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-04-22T00:53:51-c202d4d/linux-amd64-clang](https://build.golang.org/log/ab855f33c596403d5aa1b4e000cad26b6658197b):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-04-28T15:32:18-6511931/linux-ppc64-buildlet](https://build.golang.org/log/1ce4e8dee1ea77248195cd6928812ccf84cc0fef):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-08-28T05:26:59-eb07028/linux-amd64-alpine](https://build.golang.org/log/73669e95a234d84d32ce8ee7595192df2b4e82d1):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-09-23T09:24:02-6171d05/linux-amd64-alpine](https://build.golang.org/log/baa45de136d9d737be08d8def861ccc829d51c64):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-10-05T08:28:41-be272ec/linux-ppc64le-buildlet](https://build.golang.org/log/89a7df5f5305401d4c62e7dd48126e904017f85e):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-10-08T20:14:33-e285f39/linux-amd64-alpine](https://build.golang.org/log/e4d5d6ff806bc8abe7c5cf15cddef9d2376f4791):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-11-02T03:33:53-b66a294/linux-amd64](https://build.golang.org/log/2124b17fb9aa29b48d35dd85cea9c1c69ef915e8):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-11-03T17:45:11-14f2bfd/linux-amd64-clang](https://build.golang.org/log/49fcb8fe802a665683157ca376e2a5429792ea9f):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-11-10T04:40:13-17f35c6/linux-amd64-nocgo](https://build.golang.org/log/bbc2f5a11a122a048dc2a3d5e18c90936d91bb32):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-11-22T22:37:15-ecc8650/linux-amd64-sid](https://build.golang.org/log/95a745a6f8fed78a9b854b3cbad5986275ffc0cd):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

[2017-11-28T01:18:54-b5c7183/linux-amd64-sid](https://build.golang.org/log/450b8cb212512d306aed03190d275f546c332715):
```
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:87: #5: dial tcp 127.0.0.1:0: getsockopt: connection refused
FAIL
FAIL	net
```

**Comment by ianlancetaylor** [comment]
These failures are occurring on the builders, which as far as I know don't run the benchmarks, so I don't think the problem could be the benchmarks uninstalling the test hooks.

**Comment by mikioh** [comment]
Then, there might be a race on the callpath switch between test cases; enableSocketConnect? sounds plausible. Adding per-test case filter feature into socktest.Switch might be a solution.

**Comment by ianlancetaylor** [comment]
This has not happened since 2017-11-28.  I don't know what fixed it, but I think it must be fixed.
