### ISSUE TITLE
cmd/go: re-enable go/types requirement during vet during go test

### ISSUE THREAD

**Issue by rsc** [golang/go#22890]
@griesemer has some reports that go/types fails on some code during automatic vet-during-test. We should make a type-checking failure during vet-during-go-test a silent vet success instead (we know the code compiles, so we know vet is at fault), but vet-during-go-vet should still fail.

**Comment by griesemer** [comment]
For the reference: The offending go/types issue is #18395 (plus a few duplicates).

**Comment by mvdan** [comment]
Should a warning of some sort be printed? Otherwise, the user might get the wrong idea that there are no vet warnings at all.

**Comment by rsc** [comment]
The CL is in, so vet no longer dies. Repurposing this issue for removing the check once we believe go/types is safe to require (hopefully for Go 1.11).

**Comment by mvdan** [comment]
This is marked as early-in-cicle for 1.11 - do we still want to do this in the current cycle?

**Comment by ianlancetaylor** [comment]
This was done by https://golang.org/cl/108555, so closing.
