### ISSUE TITLE
cmd/compile: exit compilation earlier if type checking fails

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22909]
Issues like #22904 happen because the backend doesn't expect to deal with invalid code. Instead of having to kludge checks everywhere, we should just exit compilation at the end of type checking if we found any errors. (Analogously, we already exit after parsing if there are syntax errors.)

/cc @griesemer

**Comment by griesemer** [comment]
This should be easy to do and increase compiler stability. Marking release blocker.
