### ISSUE TITLE
goland 173.3727.96 x64  debuger failed

### ISSUE THREAD

**Issue by TeriMoni** [golang/go#22917]
the program crashed when i updated the goland to the latest version today,it can be started normally,but crashed in the debuger model.

![image](https://user-images.githubusercontent.com/29970733/33367838-d917c916-d52a-11e7-97e7-14bad77cd962.png)
I don't know what uses for the parameter -gcflags "-N -l" -a. I guess that's the cause of these parameters. Is there anybody helping to solve it?

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

The best place to ask is probably on the goland forums, /cc @dlsniper

**Comment by dlsniper** [comment]
This is actually a Go issue, not an editor issue.
To solve it, upgrade to Go 1.9.2 or newer, as discussed here https://golang.org/issues/14319

**Comment by dlsniper** [comment]
Furthermore, those parameters are needed in order to build the debugging binary, removing them would make debugging next to impossible / a really bad experience. The editor is doing the right thing here.

**Comment by TeriMoni** [comment]
@dlsniper After the upgrade, the problem has been solved, Thank you very much

**Comment by TeriMoni** [comment]
@davecheney I got it, thank you for your guidance
