### ISSUE TITLE
doc: flesh out Ports section for Go 1.10 release notes

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22911]
https://tip.golang.org/doc/go1.10#ports should provide updates on which OS versions are supported.

* FreeBSD 10.3+ (no more FreeBSD 9.3, as pre-announced in the Go 1.9 release notes)
* NetBSD 8+ (which is working again; the Go 1.9 release notes said NetBSD was broken)
* OpenBSD 6.0+ still, but this will be the last release supporting 6.0. Next release will be 6.2+.

/cc @bsiegert @paulzhol @4a6f656c @mikioh

**Comment by bradfitz** [comment]
And if #22914 isn't fixed (and maybe https://github.com/golang/go/issues/20852#issuecomment-347698956), we need to mention that NetBSD is only supported on amd64.

**Comment by mikioh** [comment]
Please don't forget to update https://github.com/golang/go/wiki#platform-specific-information too. Looks like the pages are the current central location for detailed information.

I'm not sure about the support for macOS 10.13 High Sierra. Does Go 1.10 support macOS 10.13? Or Go 1.9 already supports macOS 10.13?

**Comment by bradfitz** [comment]
I'm not too concerned about macOS (at least in terms of announcing a deprecation policy) because the current & two most recent Go versions will always work on all past 3 or 4 macOS releases, or we'll issue point releases so they do. But we could say something reassuring nonetheless.

**Comment by Fale** [comment]
Bug #18162 should also go there I think

**Comment by bradfitz** [comment]
Actually, I don't think NetBSD is not going to make this release. We can say something like "Go does not run on any released version of NetBSD, and has critical problems running on NetBSD 8-BETA."

/cc @bsiegert

**Comment by bsiegert** [comment]
I have trouble parsing this sentence. You mean "is not going to make this release"?

As for "does not run on any released version": it is unfortunate that NetBSD-8 is still not released. The main reason for suggesting -8 on the builders is that -7 does not work well on GCE. I'll try to install a machine with NetBSD-7 and run tests on that. AFAIR, there are some failures but it does run,

**Comment by bradfitz** [comment]
@bsiegert, sorry, I had an extra word "not" in there. What I meant, and edited above is:

> I don't think NetBSD is going to make this release. 

NetBSD 7 never fully worked, but updating to NetBSD 8-BETA fixed them (notably #20836 but also #20835, #16511, #19652, #10027, #10027, #10166, etc).

But NetBSD-8 BETA also doesn't work for different reasons. e.g. #22968

So there is no known version of NetBSD (released or unreleased) where things all work.

**Comment by bradfitz** [comment]
We should also announce that Go 1.10 will be the last release to support FreeBSD 10.x, which lines up well with their own EoL date: https://www.freebsd.org/security/security.html#sup ... so Go 1.11 will require FreeBSD 11+.
