### ISSUE TITLE
runtime: improve arm64 memmove

### ISSUE THREAD

**Issue by mrosier-qdt** [golang/go#22925]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/arm64

### Does this issue reproduce with the latest release?
yes

### What did you do?

Identified via inspection.

### What did you expect to see?

The implementation can be improved by unrolling loops and using sets of ldp and stp instructions.

**Comment by mrosier-qdt** [comment]
The intent of this bug report is to convey the fact that my team and I are developing an improved version of the memmove routine for arm64.  This is based on results from https://blog.cloudflare.com/arm-takes-wing/

**Comment by bradfitz** [comment]
The tree opens for performance work in early February. Please have code review(s) w/ benchstat performance numbers in the commits ready by then. The tree will close for performance work in early May.

**Comment by bradfitz** [comment]
(per https://golang.org/wiki/Go-Release-Cycle)

**Comment by mrosier-qdt** [comment]
Will do.  Thanks, Brad.
