### ISSUE TITLE
syscall: on linux 386 doesn't support syscalls that don't fail

### ISSUE THREAD

**Issue by chipaca** [golang/go#22924]
### What version of Go are you using (`go version`)?
1.6.2 and 1.9.2

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux/386 and linux/arm.

### What did you do?

with this built as `hightest`,

```go
package main

import (
	"fmt"
	"syscall"
)

func main() {
	r0, _, e := syscall.RawSyscall(syscall.SYS_GETUID32, 0, 0, 0)
	fmt.Println(uint32(r0), "/", e)
}
```

and a user with a high uid,
```bash
sudo useradd --uid "$(( 0xfffffffe ))" --shell /bin/sh hightest
```

(alternatively if you can't `useradd`, use `chown` to a numerical id, and `chmod u+s`, and change the code to use `GETEUID` instead of `GETUID`)

compare the output of `sudo -u hightest id -u` and `sudo -u hightest hightest`.

### What did you expect to see?
`4294967294 / errno 0`

### What did you see instead?
`4294967295 / no such file or directory`

The problem seems to be that in `syscall/asm_linux_386.s`, if the returned value is not less than 0xfffff001 it's treated as an error.

**Comment by ianlancetaylor** [comment]
The same thing happens on amd64 if there are any syscalls that can return a valid value larger than `0xfffffffffffff001`.

**Comment by ianlancetaylor** [comment]
OK, I see.  The code in the syscall package is correct for syscalls that can return an error.  However, there are certain syscalls that do not return an error.  For those, we should not check the result in this way.  Those syscalls are:

- `clock_gettime` (amd64 only, I think)
- `getegid`
- `getegid32` (386 only)
- `geteuid`
- `geteuid32` (386 only)
- `getgid`
- `getgid32` (386 only)
- `getpgrp`
- `getpid`
- `getppid`
- `getuid`
- `getuid32` (386 only)
- `personality` (386 only, I think)
- `setfsgid32` (386 only)
- `setfsuid32` (386 only)
- `umask`

**Comment by ianlancetaylor** [comment]
Clearly we should fix `Getuid`, et. al., in the syscall package.  It's less clear whether we should add a new API function such as `SyscallNoError` to the syscall package, or reserve that for x/sys/unix.

**Comment by bradfitz** [comment]
x/sys/unix for sure.

We can add [more] comments to syscall pointing to x/sys/unix where needed.

**Comment by tklauser** [comment]
I submitted https://golang.org/cl/84485 with a possible fix in syscall, marked for go 1.11 (but not ready for review yet). I'd like to add a test, but I couldn't yet figure out a proper way to add one based on the reproducer provided in this issue. Will hopefully find some time to work on that during the holiday season.

**Comment by tklauser** [comment]
Tested on linux/386 (via gomote) with https://golang.org/cl/84485 and the following program:

```go
package main

import (
	"fmt"
	"syscall"
)

func main() {
	// r0, _, e := syscall.RawSyscall(syscall.SYS_GETUID32, 0, 0, 0)
	// fmt.Println(uint32(r0), "/", e)
	u := syscall.Getuid()
	fmt.Println(uint32(u))
}
```
and indeed it returns `4294967294` as expected.

If anyone has an idea on how to turn the provided reproducer into a nice test, any hints would be appreciated.

I'll also work on a corresponding implementation for x/sys/unix, adding an exported `RawSyscallNoError` so the following program should also return `4294967294 / 0`

```go
package main

import (
	"fmt"
	"golang.org/x/sys/unix"
)

func main() {
	r0, _, e := unix.RawSyscallNoError(syscall.SYS_GETUID32, 0, 0, 0)
	fmt.Println(uint32(r0), "/", e)
}
```

**Comment by chipaca** [comment]
How is the syscall package tested? This isn't the only syscall that'd need special privileges to test the corner cases, I'm sure.

**Comment by tklauser** [comment]
The syscall is tested via the tests in `syscall/*_test.go` and some functionality is also implicitly tested via the os package tests. There are also some tests regarding syscall in `test/` (e.g. `test/fixedbugs/issue15002.go`). But all of these run as a non-privileged user AFAIK.

As for the syscall to use (from @ianlancetaylor's list in https://github.com/golang/go/issues/22924#issuecomment-347976254), I think only the `gete?[gu]id, the `personality` (which seems to be available on all GOARCHs btw) and the `umask` syscalls let userspace influence what value the kernel will return. And `umask`will probably not even allow us to set a high enough value to trigger the issue.

**Comment by bradfitz** [comment]
@chipaca, historically the syscall package has had few explicit tests. Most tests had been implicit ones, tested via upper layers working correctly. That's not ideal and has slowly changed, but there's still not a lot of explicit testing. It also doesn't change often, so manual testing has so far sufficed. (Again, not ideal.)

@tklauser, some of of builders do run as root, but most of our Linux ones run as a sort of "fake root" in Kubernetes that is UID 0 but with a lot fewer capabilities enabled. We could re-enable a Linux builder in a VM running as root if needed, and then we can test for being in that VM via testenv.Builder().

**Comment by tklauser** [comment]
Patchset 4 of https://golang.org/cl/84485 now implements the alternative geteuid test as suggested by @chipaca. Currently it only checks whether it is run as root via `if os.Getuid() != 0` but with a `TODO(tklauser)` to eventually change it as @bradfitz suggested, in case we need "non-fake" root. Let's see what the trybots think...

**Comment by tklauser** [comment]
The trybots look happy but I'm not sure how to check whether they actually ran the test in question (`TestSyscallNoError`). @bradfitz, is there a way to check?

FWIW, the test passes locally when run as root on linux/arm or linux/386.

**Comment by bradfitz** [comment]
@tklauser, I replied at https://go-review.googlesource.com/c/go/+/84485#message-586556e53a5403fa6b211cfccfcaef20ecdc8dc5
