### ISSUE TITLE
crypto/x509: VerifyHostname validating wrong SAN

### ISSUE THREAD

**Issue by rikatz** [golang/go#22922]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I'm using a program (NGINX Ingress Controller) that uses the ``VerifyHostname``.

While this function is called, it returns me an error about Certificate not containing a valid CommonName (``certificate is not valid for any names, but wanted to match server.domain.tld``).

Looking to the Certificate, it does contain the name server.domain.tld as a CommonName.

While investigating, I've faced that it's entering the if [here](https://github.com/golang/go/blob/2f1de1593e7993b233aa90ce874c407ae03741f8/src/crypto/x509/verify.go#L117).

This function verifies if the Certificate has an extension (and it does, an email, but not a DNSName) and if this is the case, it tries to add the value to the rest of the 'valid' string.

As my certificate does contain an extension, but not a DNSName, shouldn't this function be something like ``if len(c.DNSNames) > 0`` instead of ``c.hasSANExtension()``?

If this is the case, I can open a PR to fix this :) Anyway I'm going to ask the re-creation of the Certificate with the right SAN.

Thanks!

**Comment by bradfitz** [comment]
Have you tried Go master? (what will become Go 1.10 in early Feb)

There's been work in this space.

**Comment by amandahla** [comment]
I believe that this change here caused this behavior:

GO 1.6
https://github.com/golang/go/blob/aa1e69f3fc21795b6fab531a07008e0744ffe5bf/src/crypto/x509/verify.go#L427
```
if len(c.DNSNames) > 0 {
		for _, match := range c.DNSNames {
			if matchHostnames(toLowerCaseASCII(match), lowered) {
				return nil
			}
		}
		// If Subject Alt Name is given, we ignore the common name.
	} else if matchHostnames(toLowerCaseASCII(c.Subject.CommonName), lowered) {
		return nil
	}
```
GO 1.9 (master)
https://github.com/golang/go/blob/70ee9b4a07d356e9187dd23683ed2254c91984cd/src/crypto/x509/verify.go#L1010
```
if c.hasSANExtension() {
		for _, match := range c.DNSNames {
			if matchHostnames(toLowerCaseASCII(match), lowered) {
				return nil
			}
		}
		// If Subject Alt Name is given, we ignore the common name.
	} else if matchHostnames(toLowerCaseASCII(c.Subject.CommonName), lowered) {
		return nil
	}
```

**Comment by amandahla** [comment]
We had another problem related to changes in verifications too... :-(

https://github.com/cloudflare/cfssl/issues/827

**Comment by bradfitz** [comment]
Please file separate bugs for separate issues.

But keep in mind we don't fix old versions of Go. We mostly care about recent regressions, not long-standing bugs. We fix long-standing bugs in the next Go release (Go 1.10, in Feb). So please try Go master now and report any issues with that.

**Comment by titanous** [comment]
This is working as intended. commonName is deprecated and is intentionally not used if a SAN extension is present (whether or not it has dnsNames).

The [commit message](https://github.com/golang/go/commit/630e93ed2d8a13226903451a0e85e62efd78cdcd) for the change mentioned above makes this clear:

```text
crypto/x509: ignore CN if SAN extension present.

The code previously tested only whether DNS-name SANs were present in a
certificate which is only approximately correct. In fact, /any/ SAN
extension, including one with no DNS names, should cause the CN to be
ignored.
```

[This post](https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/IGT2fLJrAeo) explains the rationale for the complete removal of support commonName in Chrome, the same information is relevant in this case.
