### ISSUE TITLE
x/net/nettest: TestTestConn/UnixPacketPipe fails on netbsd/386

### ISSUE THREAD

**Issue by bradfitz** [golang/go#22927]
Tracking bug that TestTestConn/UnixPacketPipe fails on netbsd/386 (NetBSD 8-BETA).

It seems to work fine on netbsd/amd64 (NetBSD 8-BETA).

I'm going to disable this test for now and reference this issue. AFAIK, nothing in the Go core depends on Unix pipe datagrams, so it shouldn't affect anything.

/cc @bsiegert @mikioh

**Comment by bcmills** [comment]
This issue is very old. @golang/netbsd: do you want to try re-enabling this test and see if it is still broken?
