### ISSUE TITLE
cmd/compile: unnecessary error after "cannot refer to unexported type"

### ISSUE THREAD

**Issue by mvdan** [golang/go#22921]
https://play.golang.org/p/ZwFSxT9JCu

Output on both 1.9.2 and tip:

```
tmp/sandbox627872070/main.go:6:8: cannot refer to unexported name bytes.buffer
tmp/sandbox627872070/main.go:6:8: undefined: bytes.buffer
```

Is the second error really necessary? It seems redundant to me, unless there is a good reason for it to be there.

/cc @mdempsky @griesemer

**Comment by griesemer** [comment]
There's no need for two errors.

**Comment by mvdan** [comment]
Doesn't seem important enough to keep around for 1.12. Also, should @mdempsky still be assigned?

**Comment by ALTree** [comment]
Note: #36410 was recently opened reporting the same issue, and it was milestoned as 1.15.
