### ISSUE TITLE
os: SetDeadline doesn't work after an Fd() call

### ISSUE THREAD

**Issue by crvv** [golang/go#22934]
### What version of Go are you using (`go version`)?
go version devel +ed8b7dedd3 Thu Nov 30 01:46:50 2017 +0000 linux/amd64

### What did you do?
```
package main

import (
    "os"
    "time"
)

func main() {
    r, w, err := os.Pipe()
    if err != nil { panic(err) }
    println(r.Fd())
    go func() {
        time.Sleep(time.Second*2)
        _, err := w.Write([]byte("Hello, world!"))
        if err != nil { panic(err) }
    }()
    err = r.SetDeadline(time.Now().Add(time.Second))
    // expect an error at this line
    if err != nil { panic(err) }
    buffer := make([]byte, 16)
    n, err := r.Read(buffer)
    // or this line
    if err != nil { panic(err) }
    println(string(buffer[:n]))
}
```

### What did you expect to see?
A timeout error.
Or an error when `SetDeadline`.

The `Fd()` can also be called after `SetDeadline()`, so a timeout error is better.

### What did you see instead?
A successful Read and "Hello, world!".

The method `Fd()` put the file descriptor into blocking mode and the deadline doesn't work after it.
https://github.com/golang/go/blob/8064f82a158e4416e9f32ed7017642ace4280b4f/src/os/file_unix.go#L68

There is a similar issue with package `net`. https://github.com/golang/go/issues/21862

**Comment by bradfitz** [comment]
Ian, I assume this is also just a documentation thing?
