### ISSUE TITLE
cmd/asm: no PRFM support for ARM64 platform

### ISSUE THREAD

**Issue by mengzhuo** [golang/go#22932]
### What version of Go are you using (`go version`)?
go version devel +9a13f8e Tue Nov 28 06:47:50 2017 +0000 linux/arm64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/root/godev"
GOTMPDIR=""
GOTOOLDIR="/root/godev/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build946453649=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?

check  `cmd/asm/internal/asm/testdata/arm64enc.s`
I found PRFM is at TODO stage
```
273:   //TODO PRFM 0x6400(R7), PSTL2STRM          // f300b2f9
274:   //TODO PRFM -215799(PC), PLIL2KEEP         // 2aa196d8
```

### What did you expect to see?
PRFM works on arm64 platform

### What did you see instead?
PRFM not supported

### NOTE
I've already contacted Fannie Zhang who is a ARM employee and willing to import this inst for us :)

**Comment by zhangfannie** [comment]
@mengzhuo  the fix patch will be ready.
