### ISSUE TITLE
[LXC] bash: ./WebServer: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by albertoZurini** [golang/go#22945]
I've just finished my web server in Golang, so I moved the build from my PC (Ubuntu 17.04) to the server (Ubuntu 16.04 @ LXC container). The problem is that when I try to run the binary I get `Exec format error`.
I think it's an issue of LXC, because I've tried running the build on another computer (Ubuntu 17.04) and it runs.
So I've tried installing golang-go on the server too, but naturally nothing has changed. I've also tried building the package with the standard command (`go build main.go`) and with this other: `env GOOS=linux GOARCH=amd64 go build -v`, but none of the two has worked.

go env (my pc):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/Core/Desktop/WebServer"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build647576757=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```
go env (server): 
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

```

**Comment by bradfitz** [comment]
Are you sure your server is 64-bit? Run `uname -a`.

**Comment by albertoZurini** [comment]
Yes, it is 64 bit, Proxmox runs only on x64 CPUs.

**Comment by davecheney** [comment]
Can you please post the result of 

ldd $yourbinary

**Comment by albertoZurini** [comment]
```
root@webserver:/home/web# ldd main
ldd: exited with unknown exit code (135)
```

**Comment by bradfitz** [comment]
Sorry, your environment just seems screwed up. I would bring this to some LXC mailing list.

Closing as there's no evidence there's a Go bug here.
