### ISSUE TITLE
runtime: improve arm64 memclr

### ISSUE THREAD

**Issue by mrosier-qdt** [golang/go#22948]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/arm64

### Does this issue reproduce with the latest release?
yes

### What did you do?

Identified via inspection.

### What did you expect to see?

The implementation can be improved by unrolling loops and using sets of ldp and stp instructions.

**Comment by mrosier-qdt** [comment]
The intent of this bug report is to convey the fact that my team and I are developing an improved version of the memmove routine for arm64.  We understand the tree opens for performance work in early February.

**Comment by mrosier-qdt** [comment]
Thanks, @randall77.  I'm fairly new to github issue reporting.  Google seems to indicate only project owners can assign bugs, correct?

**Comment by bradfitz** [comment]
We don't really use the Github Assignee feature much. Don't worry about it. Just declare that you're working on it with text as you did above.

**Comment by mrosier-qdt** [comment]
SGTM. Thanks, Brad.
