### ISSUE TITLE
cmd/go: build fails parsing flags values

### ISSUE THREAD

**Issue by tophj-ibm** [golang/go#22943]
Hi. There seems to be a regression where flag values aren't being parsed correctly, leading to the build failing if you have any extra characters other than the flag. See below

### What version of Go are you using (`go version`)?
Latest master

### Does this issue reproduce with the latest release?
No (1.9.2)

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build258921016=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

build.sh
```
go build \
	-gcflags "
		-v" \
	test.go
```

test.go
```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}
```

### What did you expect to see?
Successful build.

```
$ ./build.sh 
$ 
```
### What did you see instead?
```
$ ./build.sh 
invalid value "\n\t\t-v" for flag -gcflags: missing =<value> in <pattern>=<value>
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```
Looks like the new implementation doesn't trim/ ignore tabs, spaces, newlines, etc. 

I've narrowed the commit down to the flag changes in 5993251c015dfa1e905bdf44bdb41572387edf90

**Comment by ianlancetaylor** [comment]
CC @rsc

**Comment by tophj-ibm** [comment]
thanks, all!
