### ISSUE TITLE
net/http: fix docs on Transport connection reuse specifics

### ISSUE THREAD

**Issue by liaojianqi** [golang/go#22954]
### What version of Go are you using (`go version`)?
go version go1.7 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What did you do?

```
package main

import (
	"time"
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    resp, err := http.Get("http://127.0.0.1:8588")
    
    if err != nil {
        panic(err)
    }
    _, err = ioutil.ReadAll(resp.Body)
    if err != nil {
        panic(err)
    }

    resp2, err := http.Get("http://127.0.0.1:8588")
    
    if err != nil {
        panic(err)
    }
    _, err = ioutil.ReadAll(resp2.Body)
    if err != nil {
        panic(err)
    }

    fmt.Println("before time sleep")
    time.Sleep(time.Second * 35)
}
```

in GO net/http Response Body annotation says:

> It is the caller's responsibility to close Body. The default HTTP client's Transport does not attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections ("keep-alive") unless the Body is read to completion and is closed.

yeah, it say we must read body complete AND close body.
in the above code, after read resp.Body I don't close the resp.Body. so, the http client should't reuse the tcp connection. so there will be two tcp connection handshark in wireshark, but I only see ONE.
so, maybe the net/http's comment has something wrong?
thank you.

**Comment by davecheney** [comment]
What answer would you like to see? Do you want to control the number of outgoing connections?

**Comment by liaojianqi** [comment]
What makes me wonder is resp2 should not reuse tcp connection because I don't call resp.Body.Close(). so I will see TWO tcp handshake. but I only see ONE. so resp reuse tcp connection created by resp, but i don't call resp.Body.Close().
and in net/http response says:

> The default HTTP client's Transport does not attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections ("keep-alive") unless the Body is read to completion and is closed.

**Comment by bradfitz** [comment]
I'll update it to something slightly vaguer and less promise-sounding.

The reality is that it'll do it if it can.
