### ISSUE TITLE
Marshal and Unmarshal a time.Time, I got diff value. It is work in golang 1.8, but golang 1.9

### ISSUE THREAD

**Issue by ZhijiaYang** [golang/go#22957]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

go test follow file

```
package simple_struct

import (
    "time"
    "encoding/json"
    "github.com/stretchr/testify/assert"
    "testing"
)

type SimpleStruct struct {
    CreateTime time.Time
    Other      string
}

func NewSimpleStruct() *SimpleStruct {
    return &SimpleStruct{
        CreateTime: time.Now(),
    }
}

func Test(t *testing.T) {
    s1 := NewSimpleStruct()
    data, err := json.Marshal(s1)
    assert.Nil(t, err)
    s2 := &SimpleStruct{}
    err = json.Unmarshal(data, s2)
    assert.Nil(t, err)

    assert.Equal(t, s2, s1)
    // this is not equal
    // output:
    /*

    Diff:
    --- Expected
    +++ Actual
    @@ -1,3 +1,3 @@
    (*simple_struct.SimpleStruct)({
        - CreateTime: (time.Time) 2017-12-01 14:54:53.948875421 +0800 CST,
        + CreateTime: (time.Time) 2017-12-01 14:54:53.948875421 +0800 CST m=+0.001827244,
    */
}


```

### What did you expect to see?
let this test pass just like on go 1.8

**Comment by ZhijiaYang** [comment]
Error Trace:	simple_test.go:28
	Error:      	Not equal: 
	            	expected: &simple_struct.SimpleStruct{CreateTime:time.Time{wall:0x1e13a63e, ext:63647709442, loc:(*time.Location)(0x871cc0)}, Other:""}
	            	actual: &simple_struct.SimpleStruct{CreateTime:time.Time{wall:0xbe805e609e13a63e, ext:2691802, loc:(*time.Location)(0x871cc0)}, Other:""}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1,3 +1,3 @@
	            	 (*simple_struct.SimpleStruct)({
	            	- CreateTime: (time.Time) 2017-12-01 15:17:22.504604222 +0800 CST,
	            	+ CreateTime: (time.Time) 2017-12-01 15:17:22.504604222 +0800 CST m=+0.002691802,

**Comment by bradfitz** [comment]
Yes, this was the change to time.Time in Go 1.9. You'll need to update your test to not test so deeply.

See:
https://golang.org/doc/go1.9#monotonic-time
https://golang.org/pkg/time/#hdr-Monotonic_Clocks

Notably, this part:

> The canonical way to strip a monotonic clock reading is to use t = t.Round(0).

Alternatively, for less brittle comparisons, see:
https://github.com/google/go-cmp

**Comment by ZhijiaYang** [comment]
thanks
