### ISSUE TITLE
x/crypto/ssh/terminal: build failing on linux/amd64: undefined: unix.IoctlGetTermios

### ISSUE THREAD

**Issue by Ullaakut** [golang/go#22963]
### What version of Go are you using (`go version`)?
`go version go1.9 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Alpine

### What did you do?
I start in a fresh context, from `golang:alpine` in a Docker container.
I install and run `glide`, which basically downloads all of my dependencies, one of which uses `golang.org/x/terminal`.
When trying to build, I get a few compile errors and my binary cannot be built.

### What did you expect to see?
Compilation successful.

### What did you see instead?
```
Step 6/12 : RUN go build -o cameradar
 ---> Running in 4d75c30fe5bc
# github.com/EtixLabs/cameradar/vendor/golang.org/x/crypto/ssh/terminal
../vendor/golang.org/x/crypto/ssh/terminal/util.go:30:12: undefined: unix.IoctlGetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:38:18: undefined: unix.IoctlGetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:54:12: undefined: unix.IoctlSetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:64:18: undefined: unix.IoctlGetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:75:9: undefined: unix.IoctlSetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:80:13: undefined: unix.IoctlGetWinsize
../vendor/golang.org/x/crypto/ssh/terminal/util.go:98:18: undefined: unix.IoctlGetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:107:12: undefined: unix.IoctlSetTermios
../vendor/golang.org/x/crypto/ssh/terminal/util.go:112:3: undefined: unix.IoctlSetTermios
The command '/bin/sh -c go build -o cameradar' returned a non-zero code: 2
```

See [TravisCI build logs](https://travis-ci.org/EtixLabs/cameradar/builds/310140604).
See [Dockerfile](https://github.com/EtixLabs/cameradar/blob/develop/Dockerfile).
See [glide.lock](https://github.com/EtixLabs/cameradar/blob/develop/glide.lock#L67).

Similar error logs as in https://github.com/golang/go/issues/22688

The version of `golang.org/x/crypto` that it uses is the commit `2509b142fb2b797aa7587dad548f113b2c0f20ce`.

**Comment by bradfitz** [comment]
Your version of x/sys is too old. You need to sync up to at least https://github.com/golang/sys/commit/4ed4d404df456f81e878683a0363ed3013a59003 where it was added.
