### ISSUE TITLE
Maps with time.Time keys

### ISSUE THREAD

**Issue by pjebs** [golang/go#22977]
If I have a map with a `time.Time` type as a key, or alternatively a struct with a `time.Time` type as a  field, with the struct used as a key, it appears as if the key comparisons use `==` instead of the `Equal` method as recommended by: https://golang.org/pkg/time/#Time.Equal

```
Equal reports whether t and u represent the same time instant. Two times can be equal even if they are in different locations. For example, 6:00 +0200 CEST and 4:00 UTC are Equal. See the documentation on the Time type for the pitfalls of using == with Time values; most code should use Equal instead.

```

**Comment by pjebs** [comment]
```
eg.

map[time.Time]int

OR 

type A struct {
t time.Time
}

map[A]int

**Comment by mvdan** [comment]
Maps don't call any functions or methods, they use equality as defined in the spec. What is your point here?

**Comment by pjebs** [comment]
https://github.com/golang/go/issues/21829

**Comment by go101** [comment]
@pjebs
You should use `Time.Sub(time.Time{})` as the struct field to make the struct values capable to act as map keys.

**Comment by go101** [comment]
filed a related issue: https://github.com/golang/go/issues/22978

**Comment by richardartoul** [comment]
@pjebs I have a linter for this issue if you're interested: https://github.com/m3db/build-tools/blob/master/linters/badtime/README.md
