### ISSUE TITLE
PyGO - PythonGO [NEW IDEA]

### ISSUE THREAD

**Issue by ManPython** [golang/go#22972]
1. Is this possible to modify GO language/compilator in direction to compile Python code similary like GO code?
a) any coders interested for this way?
b) any coders interested for this new project?

2. The main new idea is (maybe not so new), to create some port (other version) of GO for Python named PG/PyGO - PythonGO.

3. What is idea for this issue? Well.. there is many code of Python.. that looks similary like GO Langugae code but GO implemented brackets { } and other solutions.. (ok there is more differences.. but not about).
Soo.. mainly PYGO need in compiler parser to discover Indentation like in Python
a) I'm tired about thinking to re-write Python code to GO as a bether solutions in my head
    the way to change habits from Python (what are good) is hard way..
    the small count of line is comfy
b) the Pythons solutions about compile code to .exe like Py2Exe Niutka etc.. to c+ out or IronPython not  not satisfied, thats why we going to GO.. [but is this right way (re-writing)? Can be more easy? - Maybe?]

Experimental..
https://github.com/ManPython/PythonGo

**Comment by ianlancetaylor** [comment]
This isn't the kind of project we are going to track on the Go issue tracker.  There is no work to be done for this in the Go tools or standard library.  If you want to discuss it in conjunction with Go, please use a forum: see https://golang.org/wiki/Questions.

Closing.
