### ISSUE TITLE
sync/atomic: some words are redundant in package doc.

### ISSUE THREAD

**Issue by dotaheor** [golang/go#22974]
The doc for the function AddUint32:
```
AddUint32 atomically adds delta to *addr and returns the new value. To subtract a signed positive constant value c from x, do AddUint32(&x, ^uint32(c-1)). In particular, to decrement x, do AddUint32(&x, ^uint32(0)). 
```

I think here, `signed positive constant value` should be replaced with `positive value`.
`constant` and `signed` are redundant.

Same problems for other AddUxxxxx functions.

**Comment by ianlancetaylor** [comment]
It's not redundant, as the Go language rules make it harder than you think to subtract a signed positive constant value.  To subtract a variable value, you can simply write `AddUint32(&x, -v)`.  That doesn't work for constant values because the resulting untyped constant can not be assigned to `uint32`.

Closing because I don't think we should change this.

**Comment by dotaheor** [comment]
How is it possible to call `AddUint32(&x, -v)` call an `uint32` variable `v`?
Compiler will report error.

**Comment by dotaheor** [comment]
btw, there are many `a uintxxx` uses in `sync/atomic` doc.
Should they be `an uintxxx`?

**Comment by dotaheor** [comment]
@ianlancetaylor I still think `signed` is redundant.

**Comment by dotaheor** [comment]
Oh yeah, I found another way to subtract unsigned constant, if the unsigned constant is typed and its type is same as the second parameter type.
```
atomic.AddUint32(&n, ^(d - 1))
```

But if the type of the typed unsigned constant doesn't match he second parameter type, then the `^uint32(c-1)` way still needs to be used.

**Comment by dotaheor** [comment]
@ianlancetaylor 
> That doesn't work for constant values because the resulting untyped constant can not be assigned to uint32.

but the doc says `... subtract a signed positive constant value c ...`, a signed constant implies `c` is a typed constant, an operation with a typed constant `c` involved will always result a constant with the same type as `c`. So I think the reason of the trick `^uint32(c-1)` is not for `untyped constant can not be assigned to uint32`.

**Comment by ianlancetaylor** [comment]
Thanks for the comments.  Let's agree to disagree.

**Comment by go101** [comment]
ok. but the docs realy doesn't mention how to subtract an unsigned constant.

**Comment by ianlancetaylor** [comment]
Go doesn't really have the concept of an unsigned constant.  Go constants are untyped.  Numeric constants are positive or negative.  They are always signed.  See https://golang.org/blog/constants.
