### ISSUE TITLE
doc: type aware auto-completion in Visual Studio Code

### ISSUE THREAD

**Issue by ricklamers** [golang/go#22973]
### What did you expect to see?
Doesn't Visual Studio Code support Type aware auto-completion?

Should be Yes in the table.

### What did you see instead?
No

[https://github.com/golang/go/blob/master/doc/editors.html#L70](https://github.com/golang/go/blob/master/doc/editors.html#L70)

**Comment by ALTree** [comment]
Does the editor

> filter the autocompletion suggestions based on whether the code will compile once autocompleted.

? This is the wording in the commit msg that explained what `Type aware auto-completion` means. If the answer is yes, the doc should be fixed.

**Comment by ALTree** [comment]
To be fair I had to look at a commit message to understand what exactly it meant. A note at the bottom of the page maybe could help.
