### ISSUE TITLE
runtime: "non in-use span in unswept list" flake on darwin-amd64

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22987]
https://go-review.googlesource.com/c/go/+/81775 flaked on darwin-amd64 due to:

    # cmd/compile (testmain)
    runtime: bad span s.state=0 s.sweepgen=564617216 sweepgen=12
    fatal error: non in-use span in unswept list

https://storage.googleapis.com/go-build-log/5cf4a738/darwin-amd64-10_11_e7ffe203.log

/cc @aclements

**Comment by mdempsky** [comment]
That sweepgen value looks super bogus. I'm thinking it must be software memory corruption. (Hardware memory corruption would probably be just 1-bit off, rather than a completely different value.)

There was also #22988, which was also a darwin-amd64 flake. This makes me suspect there's something darwin-amd64-specific going on.

**Comment by ianlancetaylor** [comment]
@aclements Do you think this might be fixed, or should we kick it to 1.11?

**Comment by ianlancetaylor** [comment]
Actually I'm going to close this as a likely dup of #22988.  (The same questions arise on that issue: close or kick?)
