### ISSUE TITLE
net/http: add InactivityTimeout to http.DefaultClient

### ISSUE THREAD

**Issue by knightXun** [golang/go#22982]
https://github.com/golang/go/blob/1b9f66330b123b042e738eff5e47e869dd301a98/src/net/http/client.go#L110

Look at two code:
server.go:
```
package main

import "net/http"
import (
	"time"
	"fmt"
)


func main() {
	http.HandleFunc("/test", test)
	http.ListenAndServe(":9999", nil)
}

func test(w http.ResponseWriter, r *http.Request){
	fmt.Println("test func")
	time.Sleep(100000000000000)
}
```

client.go
```
package main

import (
	"net/http"
	"fmt"
)

func main() {
	resp, err := http.Get("http://127.0.0.1:9999/test")
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println(resp.StatusCode)
	}
}
```

when we run client.go, it will stuck. please notice it.

**Comment by mvdan** [comment]
What change in particular are you suggesting? That a timeout of 0 convert to some default, or that the `DefaultClient` declaration add one?

The former will break many programs, as there would be no way to disable the timeout. The latter would still break some, as they may depend on `DefaultClient` not having a timeout.

And there's always the question of what timeout to use. If it's too short, it will break far too many programs. If it's too long, to some people it will still "get stuck".

Why not use a custom `http.Client`? In your client program, it would be one extra line and you'd be able to use whatever timeout suits you.

**Comment by bradfitz** [comment]
Maybe we can do a 3 minute timeout or something high.

Enough other stuff breaks or times out around 3 minutes in the wild that this doesn't seem too invasive.

Thoughts, @tombergan?

**Comment by CAFxX** [comment]
I don't want to hijack this specific issue but I fully agree with all network operations (i.e. not just HTTP) by default having timeouts. We have been bitten so many times by components that don't allow to specify timeouts for network operations (or that have no sane default timeout) that is now one of the first things I check when evaluating the use of a new component/library.

**Comment by knightXun** [comment]
Can we remove DefaultClient?

**Comment by knightXun** [comment]
Maybe we can remove DefaultClient.Let user to decide which timeout is better.

**Comment by knightXun** [comment]
Maybe 3 minute is enough.

**Comment by bradfitz** [comment]
I sent CL 116356 to add a 5 minute timeout, but right after I mailed it I realized it would break people wanting to do long downloads.

I think the only conservative thing we could do by default is to add some sort of InactivityTimeout, but it's too late for that, so bumping to Go 1.12.

**Comment by knightXun** [comment]
thanks @bradfitz

**Comment by rsc** [comment]
Per discussion with proposal review, retitled with understanding that step 2 is to set it to a good default in #24138.

**Comment by imaai** [comment]
@bradfitz @rsc I'd like to try this one. Could you specify what do you mean by "Add InactivityTimeout" in terms of implementation?

**Comment by networkimprov** [comment]
This was closed without reference to a CL. Was it fixed?

**Comment by mvdan** [comment]
It doesn't look fixed, and I'm not sure why @knightXun closed the issue. It's their decision to close it, though.

**Comment by networkimprov** [comment]
cc @neild
