### ISSUE TITLE
database/sql: Support QueryerContext without Queryer or Prepare()

### ISSUE THREAD

**Issue by tejasmanohar** [golang/go#22980]
### What version of Go are you using (`go version`)?
go1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Irrelevant, reproducible on playground.

### What did you do?

I'm implementing a `database/sql.Driver` with the new context API for a database that doesn't support prepared statements.

In [my first attempt (playground)](https://play.golang.org/p/AagZOJk1Ev) where I only implemented the [QueryerContext](https://golang.org/pkg/database/sql/driver/#QueryerContext) interface, `database/sql` called `Prepare()` and my driver panic'd since it was unsupported. I expected QueryerContext to be sufficient to call `database/sql.DB.Query()` without `Prepare()` since the docs say

>If a Conn does not implement QueryerContext, the sql package's DB.Query will first prepare a query, execute the statement, and then close the statement.

After more investigation, it _seems_ like you need to implement the (deprecated) [Queryer](https://golang.org/pkg/database/sql/driver/#Queryer) interface, too, in order to skip prepared statements even though its methods are not called. See my [successful example (playground)](https://play.golang.org/p/qbE-QPrgIY). This was unexpected since the docs say

>Deprecated: Drivers should implement QueryerContext instead (or additionally).

Is this expected? Am I misunderstanding the docs? Happy to submit a patch if it's a bug :-)

**Comment by kardianos** [comment]
This is fixed for go1.10. Please test on the go1.10 beta.
