### ISSUE TITLE
Use "go get" don't know the download situation

### ISSUE THREAD

**Issue by bailehang** [golang/go#22997]
src/cmd/go/internal/get/vcs.go

```
431 431     var buf bytes.Buffer
432 432     cmd.Stdout = &buf
433 433     cmd.Stderr = &buf
    434 +   cmd.Stdout = os.Stdout
    435 +   cmd.Stderr = os.Stderr
434 436     err = cmd.Run()
435 437     out := buf.Bytes()
```
Excuse me, We want to see the download progress and net traffic. May I do this?

**Comment by adelowo** [comment]
Most likely not happening https://github.com/golang/go/issues/22800#issuecomment-345439319

**Comment by ALTree** [comment]
Yep, this was asked several times in the past. The tool will likely remain quiet be default, but see [Brad's comment](https://github.com/golang/go/issues/22800#issuecomment-345455997). If someone wants to prototype some kind of progress bar as it needs to be an external tool first. 

Closing this.
