### ISSUE TITLE
x/tools/cmd/goimports: neighboring files cause wrong import decision

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#23001]
go version devel +9a13f8e Tue Nov 28 06:47:50 2017 +0000 linux/amd64

If I run `goimports bar.go` with the following files under $GOPATH, it imports a/y, not b/y, even though only b/y exports the function G. It seems that the import in foo.go is causing goimports to ignore the constraints that the calls are imposing. I would expect the imported package to provide all the required names - that is, even though neighboring files might be good as a starting hint, I think that goimports should still verify that the required names exist in that package, perhaps only falling back to the starting hint only if no package at all is found that satisfies the requirements (because then it's likely to be a spelling mistake).

This is a particular issue when running goimports on a file in a directory with lots of random independent main packages (e.g. my $HOME/src directory where I keep hundreds of tiny scratch Go programs).

	==> src/x/bar.go <==
	package x
	
	func Q() {
		y.G()
	}
	
	==> src/x/foo.go <==
	package x
	
	import (
		"a/y"
	)
	
	func P() {
		y.F()
	}
	
	==> src/b/y/y.go <==
	package y
	
	func G() {
	}
	
	==> src/a/y/y.go <==
	package y
	
	func F() {
	}

**Comment by mvdan** [comment]
This is likely caused by #17557. /cc @henryas @fraenkel @bradfitz 

I agree that the prioritization of closer packages should still take into account whether or not all the required names are available.

**Comment by henryas** [comment]
I can't seem to replicate the problem. I copy-pasted your code and recreated the directories, goimports correctly inserts "b/y" into bar.go. 

Have you tried reinstalling goimports?

**Comment by fraenkel** [comment]
The problem is actually caused by
https://github.com/golang/tools/commit/e011c1062a41d0e2614279f1dc8cf7f1bf6aaac3

It seems there is no validation that the sibling's choice is actually valid. Once I remove the sibling check, the answer becomes b/y.

**Comment by bradfitz** [comment]
Hey @kazrakcom, could you look into this?

**Comment by mvdan** [comment]
I pointed at the wrong CL then - apologies.

**Comment by rogpeppe** [comment]
> I can't seem to replicate the problem. I copy-pasted your code and recreated the directories, goimports correctly inserts "b/y" into bar.go.

I just tried again with latest Go tip (9ce6b5c) and latest x/tools tip (7165768) and I still see the issue.

FWIW the problem is not exhibited if you run goimports with standard input, because then it doesn't take neighbouring files into account.

**Comment by fraenkel** [comment]
Can someone review the change?
