### ISSUE TITLE
x/build/maintner: CLs that switch branches remain on the original branch

### ISSUE THREAD

**Issue by bradfitz** [golang/go#23007]
I've noticed that Trybots run on this CL forever:

https://go-review.googlesource.com/c/go/+/33776

It has Run-TryBot=+1 set on it, so every time the coordinator restarts, it starts a TryBot run for it.

Then the TryBots pass, and it tries to leave a vote on Gerrit that TryBot-Result=+1, but Gerrit says 404:

```
2017/12/05 05:24:29 Starting new trybot set for {go dev.tls I6052695ece9aff9e3112c2fb176596fde8aa9cb2 1df669af17dbeee3930828e0ba543582209a3a1b}
2017/12/05 05:24:29 Error getting Gerrit comments on go~dev.tls~I6052695ece9aff9e3112c2fb176596fde8aa9cb2: HTTP status 404 Not Found; Not found: go~dev.tls~I6052695ece9aff9e3112c2fb176596fde8aa9cb2
```

and

```
2017/12/05 05:33:03 Failed to call Gerrit: HTTP status 404 Not Found; Not found: go~dev.tls~I6052695ece9aff9e3112c2fb176596fde8aa9cb2
```

Therefore it hangs around at the top of the coordinator status page forever, since it thinks it needs to be done, but it already has one running, which has nothing to do:

![screen shot 2017-12-05 at 3 29 48 pm](https://user-images.githubusercontent.com/2621/33636484-3a8ee1ca-d9d1-11e7-82f5-943c759c03d6.png)

I imagine the period in the branch name is bogus and confusing Gerrit?

@andybons, do you know?

From https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-id I see nothing special about `<branch>` escaping, but maybe I'm missing something.

**Comment by andybons** [comment]
That change's ID is `go~master~I6052695ece9aff9e3112c2fb176596fde8aa9cb2` since it's on the master branch.

dev.tls doesn't seem to be messing up in the API endpoints. `curl https://go-review.googlesource.com/changes/go~dev.tls~Ia1b06ae518a4b2821a584a420d99859a2666c8f0/detail` does just fine.

**Comment by bradfitz** [comment]
Oh, weird. So why is the coordinator getting confused and thinking it's `dev.tls`?

**Comment by andybons** [comment]
Good question. Let me take a quick look...

**Comment by andybons** [comment]
The maintner corpus thinks that it’s in the `refs/heads/dev.tls` branch. My guess is that when Filippo switched from dev.tls to master (https://go-review.googlesource.com/c/go/+/33776#message-60a9b48d3094de83bdcf1b5f838ef2c323d56603) that it didn’t take the switch into account.

**Comment by bradfitz** [comment]
Ah, okay. Thanks. I'll look into a fix.
