### ISSUE TITLE
crypto/x509: Trailing data in the IssuerAlternativeName extension value does not return an error when parsing certificate.

### ISSUE THREAD

**Issue by szank** [golang/go#23016]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
osx

### What did you do?
I was investigating some test certificates, and noticed this one: 
```
-----BEGIN CERTIFICATE-----
MIIGPjCCBSigAwIBAgIFBDFmk+0wCwYJKoZIhvcNAQELMFYxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1Nb3RoZXIgTmF0dXJlMRMwEQYDVQQLEwpFdmVyeXRoaW5nMRgw
FgYDVQQDEw9OYW1lIGNvbnN0cmFpbnQxADAiGA8yMDU1MTIwMTA2MDcwOFoYDzIw
NTYxMDA1MjM1MjU4WjCBmzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD0V4dHJlbWUg
RGlzY29yZDEOMAwGA1UECxMFQ2hhb3MxFDASBgNVBAcTC1RhbGxhaGFzc2VlMQsw
CQYDVQQIEwJGTDEcMBoGA1UECRMTMzIxMCBIb2xseSBNaWxsIFJ1bjEOMAwGA1UE
ERMFMzAwNjIxDzANBgNVBAMTBmdvdi51czEAMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA2lVo8m23yLGU5GBObxhGAMYJNfMxLXwmGaYDQGN/Zr82ZK+Y
5oYwDd8OpZmLxU1aRfWoLSs6JQ/LbftdvT5nns+xFD/ZpboeghlZvpA8espM5zDR
5i4Qs8pmfqbrARdKV1khTDfgFw6aGTmatdHcwfJ+U6jOaXPTI8S4olN4LsyV0sCa
JT/c1SBXOdfQjLGe2cxwIyBzvwxj07guuYzq3Kj72d9sKyWPAdTdBngtKH2jvVq9
XncFo+juD+nhQOsRPCqAaE5cdsdSF+YTuJF/ZrAe5ohY0UiyTg9FrxVe8hf3PB3r
h9yjHuC7J0D0M39+dmhmyfYrAzDp9NnXsWXVvQIDAQABo4ICyzCCAscwDgYDVR0P
AQH/BAQDAgCkMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdIwQHMAWAAwECAzBiBggrBgEFBQcBAQRWMFQwIQYIKwYB
BQUHMAGGFWh0dHA6Ly90aGVjYS5uZXQvb2NzcDAvBggrBgEFBQcwAoYjaHR0cDov
L3RoZWNhLm5ldC90b3RhbGx5dGhlY2VydC5jcnQwOAYDVR0RBDEwL4YgaXJyZWxl
dmFudGluZm8vL3VzZXJAMTkyLjE2OC4xLjGCC3d3dy5kbnMuY29tMAsGA1UdEgQE
MACCADAbBgNVHSAEFDASMAgGBmeBDAECAjAGBgQqAwQFMIIBqwYDVR0eBIIBojCC
AZ6ggc4wE4ERZ29vZF9lbWFpbEBnZy5jb20wCYEHTHVsTWFpbDAPgg1wZXJtaXR0
ZWQuY29tMIGOpIGLMIGIMQswCQYDVQQGEwJVUzENMAsGA1UEChMEVUlVQzEMMAoG
A1UECxMDRUNFMRIwEAYDVQQHEwlDaGFtcGFpZ24xCzAJBgNVBAgTAklMMRYwFAYD
VQQJEw02MDEgV3JpZ2h0IFN0MQ4wDAYDVQQREwU2MTgyMDERMA8GA1UEAxMIdWl1
Yy5uZXQxADAKhwhKfeBI//8AAKGByjASgRBiYWRfZW1haWxAZ2cuY29tMAmBB0x1
bE1haWwwDIIKYmFubmVkLmNvbTCBjqSBizCBiDELMAkGA1UEBhMCVVMxDjAMBgNV
BAoTBVVtaWNoMQswCQYDVQQLEwJDUzESMBAGA1UEBxMJQW5uIEFyYm9yMQswCQYD
VQQIEwJNSTEVMBMGA1UECRMMNTAwIFN0YXRlIFN0MQ4wDAYDVQQREwU0ODEwOTES
MBAGA1UEAxMJdW1pY2gubmV0MQAwCocIwKgBAf//AAAwCwYJKoZIhvcNAQELA4IB
AQDfA7wx83CZo+SG+revr32LacHA/EQFHGI4lyHQWbBdVsDCb6N7w9fNXCC3+MRo
cWYNNWctlvyEZfDoU/mshh2vpAQcL56toMJYCX8+6GeAJCGIS4yD7ks+j7GY+kzR
OnW1A3irglDycF3blQoaGJsLp94VjyOzESh0+nNwypfF1lGZFzjBpXGsL04hKzAR
7CAADZ7qSHvB39o8VdEX0toWk791G+yys7ugx/pAxWIpmYU68lco9S860KxA66ln
7s3g2KgdqC4kU9auUM3tvHFqdnXfbBYSYC1qvihKwmeFbCmAgsKH1rm4x4OuEohb
ewclEGevcJayEHyQjYNwtXfg
-----END CERTIFICATE-----
```

This looks strange, as the issuer alternative name looks malformed. 
Here is the asn.1 decoder [link](https://lapo.it/asn1js/#3082063E30820528A003020102020504316693ED300B06092A864886F70D01010B3056310B300906035504061302555331163014060355040A130D4D6F74686572204E617475726531133011060355040B130A45766572797468696E67311830160603550403130F4E616D6520636F6E73747261696E7431003022180F32303535313230313036303730385A180F32303536313030353233353235385A30819B310B300906035504061302555331183016060355040A130F45787472656D6520446973636F7264310E300C060355040B13054368616F73311430120603550407130B54616C6C61686173736565310B300906035504081302464C311C301A060355040913133332313020486F6C6C79204D696C6C2052756E310E300C060355041113053330303632310F300D06035504031306676F762E7573310030820122300D06092A864886F70D01010105000382010F003082010A0282010100DA5568F26DB7C8B194E4604E6F184600C60935F3312D7C2619A60340637F66BF3664AF98E686300DDF0EA5998BC54D5A45F5A82D2B3A250FCB6DFB5DBD3E679ECFB1143FD9A5BA1E821959BE903C7ACA4CE730D1E62E10B3CA667EA6EB01174A5759214C37E0170E9A19399AB5D1DCC1F27E53A8CE6973D323C4B8A253782ECC95D2C09A253FDCD5205739D7D08CB19ED9CC70232073BF0C63D3B82EB98CEADCA8FBD9DF6C2B258F01D4DD06782D287DA3BD5ABD5E7705A3E8EE0FE9E140EB113C2A80684E5C76C75217E613B8917F66B01EE68858D148B24E0F45AF155EF217F73C1DEB87DCA31EE0BB2740F4337F7E766866C9F62B0330E9F4D9D7B165D5BD0203010001A38202CB308202C7300E0603551D0F0101FF0404030200A4301D0603551D250416301406082B0601050507030206082B06010505070301300F0603551D130101FF040530030101FF300E0603551D23040730058003010203306206082B0601050507010104563054302106082B060105050730018615687474703A2F2F74686563612E6E65742F6F637370302F06082B060105050730028623687474703A2F2F74686563612E6E65742F746F74616C6C79746865636572742E63727430380603551D110431302F8620697272656C6576616E74696E666F2F2F75736572403139322E3136382E312E31820B7777772E646E732E636F6D300B0603551D12040430008200301B0603551D20041430123008060667810C010202300606042A030405308201AB0603551D1E048201A23082019EA081CE30138111676F6F645F656D61696C4067672E636F6D300981074C756C4D61696C300F820D7065726D69747465642E636F6D30818EA4818B308188310B3009060355040613025553310D300B060355040A130455495543310C300A060355040B130345434531123010060355040713094368616D706169676E310B300906035504081302494C311630140603550409130D36303120577269676874205374310E300C0603550411130536313832303111300F06035504031308756975632E6E65743100300A87084A7DE048FFFF0000A181CA301281106261645F656D61696C4067672E636F6D300981074C756C4D61696C300C820A62616E6E65642E636F6D30818EA4818B308188310B3009060355040613025553310E300C060355040A1305556D696368310B3009060355040B130243533112301006035504071309416E6E204172626F72310B3009060355040813024D49311530130603550409130C353030205374617465205374310E300C0603550411130534383130393112301006035504031309756D6963682E6E65743100300A8708C0A80101FFFF0000300B06092A864886F70D01010B0382010100DF03BC31F37099A3E486FAB7AFAF7D8B69C1C0FC44051C62389721D059B05D56C0C26FA37BC3D7CD5C20B7F8C46871660D35672D96FC8465F0E853F9AC861DAFA4041C2F9EADA0C258097F3EE867802421884B8C83EE4B3E8FB198FA4CD13A75B50378AB8250F2705DDB950A1A189B0BA7DE158F23B3112874FA7370CA97C5D651991738C1A571AC2F4E212B3011EC20000D9EEA487BC1DFDA3C55D117D2DA1693BF751BECB2B3BBA0C7FA40C5622999853AF25728F52F3AD0AC40EBA967EECDE0D8A81DA82E2453D6AE50CDEDBC716A7675DF6C1612602D6ABE284AC267856C298082C287D6B9B8C783AE12885B7B07251067AF7096B2107C908D8370B577E0): 

The issuer alt name AttributeTypeAndValue value contains two concatanated ASN.1 structs. 
One is an empty sequence (0x30,0x00) followed by empty primitive value (context specific tag) (0x82,0x00)

Here is the `openssl asn1parse` dump (relevant part):
```
857:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Issuer Alternative Name
  862:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:30008200
```
Shouldn't it return an error? Openssl doesn't complain, but it is very permissive anyway. Go is much more strict, so I thought you guys might want to guard against this kind of encoding errors. 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/SCivmG9m88

### What did you expect to see?
error

### What did you see instead?
no errors

**Comment by szank** [comment]
FWIW Issuer Alternative Names extension is not recognised/parsed by golang, so it ends up in Extensions slice.
As such go is not obliged to parse it or verify it.

**Comment by szank** [comment]
I think this issue can be closed after all.

**Comment by odeke-em** [comment]
@szank thanks for the investigation. For purposes of posterity and aiding @agl and others during determining what can be closed, could you please post perhaps a reference to where you got that information? Thank you!

**Comment by titanous** [comment]
@szank is correct: https://play.golang.org/p/-HbEmkotsS

Note the unparsed extension:

```go
pkix.Extension{Id:asn1.ObjectIdentifier{2, 5, 29, 18}, Critical:false, Value:[]uint8{0x30, 0x0, 0x82, 0x0}}
```

Since Go is not aware of the correct format of the extension and does not parse it, there is no reason to return an error. There is also no `Certificate.IssuerAltName` (or similar) field for this data to go in.

Closing as working as intended.
