### ISSUE TITLE
Add os.ModeExecutable

### ISSUE THREAD

**Issue by icholy** [golang/go#23018]
### What version of Go are you using (`go version`)?

go version go1.9 linux/amd64

### What did you do?

Tried to determine if a file is executable

``` go
info, _ := os.Stat(file)
isExecutable := info.Mode()&os.ModeExecutable == 0
```

### What did you expect to see?

`os.ModeExecutable` to equal `0111`

### What did you see instead?

`os.ModeExecutable` is not defined.

**Comment by bradfitz** [comment]
Executable for who?

We also don't have ModeReadable and ModeWritable, so why just executable?

**Comment by icholy** [comment]
@bradfitz makes sense
