### ISSUE TITLE
cmd/compile: inconsistent behaviour in multiple assignment

### ISSUE THREAD

**Issue by go101** [golang/go#23017]
### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

Two programs:

program 1:
```
package main

import "fmt"

func main() {
  var m = map[int]int{}
  var p *int
  
  defer func() {
    fmt.Println(recover())
    fmt.Println(len(m)) // 0
  }()
  m[2], *p = 1, 2
}
```

program 2:
```
package main

import "fmt"

func main() {
  var m map[int]int
  var a int
  var p = &a
  
  defer func() {
    fmt.Println(recover())
    fmt.Println(*p) // 5
  }()
  *p, m[2] = 5, 2
}
```

### What did you expect to see?

The behaviors of the two programs should be consistent.

### What did you see instead?

The behaviors of the two programs are not consistent.

program 1 finishes zero assignments.
but program 2 finishes one assignment.

**Comment by ianlancetaylor** [comment]
The order of evaluation rules for the language do not specify precisely when a pointer indirection occurs.  I think that either behavior is permitted by the language.

CC @griesemer

**Comment by randall77** [comment]
From the spec:
```
x := []int{1, 2, 3}
type Point struct { x, y int }
var p *Point
x[2], p.x = 6, 7  // set x[2] = 6, then panic setting p.x = 7
```
That sounds like program 1, we should set `m[2]=1` before panicking.

**Comment by griesemer** [comment]
@randall77 I think this example in the spec is wrong. The prose before says:

> The assignment proceeds in two phases. First, the operands of index expressions and pointer indirections (including implicit pointer indirections in selectors) on the left and the expressions on the right are all evaluated in the usual order. Second, the assignments are carried out in left-to-right order.

That is, we shouldn't get to the assignment if there's a nil-pointer exception. I'd conclude the behavior for program 1 is correct.

Secondly, I don't see anything in the spec stating when panics due to assignments to nil maps should happen in multiple assignments; I'd conclude that the behavior for program 2 is at least not incorrect.

We should a) fix the spec example, and b) decide if we want to say anything more about map assignments.

**Comment by griesemer** [comment]
Never mind; I misread. The operands are evaluated, but not the entire expression. So the spec example is correct, and program 1 should assign to m.

**Comment by mdempsky** [comment]
My understanding of the spec is that `m[2], *p = 1, 2` should be evaluated as:

    // First, the operands of index expressions and pointer indirections (including implicit pointer indirections in selectors) on the left and the expressions on the right are all evaluated in the usual order.
    t0, t1, t2, t3, t4 := m, 2, p, 1, 2

    // Second, the assignments are carried out in left-to-right order.
    t0[t1] = t3
    *t2 = t4

That is, program 1 should print 1.

**Comment by mdempsky** [comment]
Related discussion: #15620.

**Comment by mdempsky** [comment]
Program 1 is miscompiled by cmd/compile because order.go rewrites

    m[2], *p = 1, 2

into

    t0, t1 := m, 2
    t2, *p = 1, 2
    t0[t1] = t2

**Comment by mdempsky** [comment]
gccgo prints 1 and 5 for programs 1 and 2, respectively.

**Comment by randall77** [comment]
Right, the spec says:
```
The assignment proceeds in two phases. First, the operands of index expressions and pointer indirections (including implicit pointer indirections in selectors) on the left and the expressions on the right are all evaluated in the usual order. Second, the assignments are carried out in left-to-right order.
```
So I take that to mean that in the first phase, we evaluate the right hand side, plus any arguments of `*` or `[]` (or `.` that really mean C's `->`) on the left-hand side, but not the `*` or `[]` themselves.  Then we do the assignments left-to-right.  Both of OP's programs panic in phase 2, as the dereference on the left-hand side doesn't happen in phase 1.

See #22881 also.

**Comment by randall77** [comment]
OP's program 1 fails for all of go1.3-tip.  Go 1.2 gets it right!
1.11 sounds correct.

**Comment by randall77** [comment]
Punting again, too late for 1.13.

**Comment by cuonglm** [comment]
How about:

```
        var p *int
        m := map[int]int{}
        m[0], _ = append(m[0], 0), *p
```

Must `m[0]` modified?

I expected it does, but current test case indicate it is not modified.

**Comment by cuonglm** [comment]
> How about:
> 
> ```
>         var p *int
>         m := map[int]int{}
>         m[0], _ = append(m[0], 0), *p
> ```
> 
> Must `m[0]` modified?
> 
> I expected it does, but current test case indicate it is not modified.

Ah ok, it should not modify map, because we evaluate RHS first, but RHS panics.
