### ISSUE TITLE
cmd/go: go get error, remote: The project you were looking for could not be found.

### ISSUE THREAD

**Issue by businiaowyf** [golang/go#23015]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
MacOS High Sierra 10.13.1
amd64

### What did you do?
I have a repository whose path is **https://git.garena.com/gxx/liveserver/jupiter.git**, 
I run `go get git.garena.com/gxx/liveserver/jupiter` on my mac, and then I got an error:
```
wangyf@wyfs-MacBook-Pro:~/work/go/src/git.garena.com$ go get git.garena.com/gxx/liveserver/jupiter
# cd .; git clone https://git.garena.com/gxx/liveserver.git /Users/wangyf/work/go/src/git.garena.com/gxx/liveserver
Cloning into '/Users/wangyf/work/go/src/git.garena.com/gxx/liveserver'...
remote: The project you were looking for could not be found.
fatal: repository 'https://git.garena.com/gxx/liveserver.git/' not found
package git.garena.com/gxx/liveserver/jupiter: exit status 128
```

It seem that the "go get" can't parse the third directory after git.garena.com

### What did you expect to see?
go get succees

### What did you see instead?
can't go get the repository

**Comment by ianlancetaylor** [comment]
That error is coming from git, not the go tool.  If you run `go get` with the `-x` option, you will see the exact git command that it is running.

**Comment by businiaowyf** [comment]
I found the same issue here [#21859](https://github.com/golang/go/issues/21859)
Thank you ianlancetaylor

**Comment by ianlancetaylor** [comment]
@businiaowyf Does that help you fix the problem?  If so we can close this issue.

**Comment by businiaowyf** [comment]
Yes, you can close it. Although I haven't fix it, I think it helps. Thank you again.
