### ISSUE TITLE
Sub-Commands for flag Package

### ISSUE THREAD

**Issue by dc0d** [golang/go#23013]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04

[This](https://godoc.org/github.com/dc0d/clarg#example-Parse) is a simple and clean way to add sub-commands to `flag` package without changing anything or adding any new type; just by adding a function.

**Comment by bradfitz** [comment]
Sorry, but the flag package in the standard library isn't growing features at this point.

**Comment by dc0d** [comment]
:( That was fast!
