### ISSUE TITLE
why not add some grammatical sugar like return_if_err(err)?

### ISSUE THREAD

**Issue by SuperGod** [golang/go#23029]
why not add some grammatical sugar like "return_if_err(err)"?
There are many code in my project :

```
	if err != nil {
		return
	}
```
sometimes, this code take up too much lines.
So,why not add some grammatical sugar like return_if_err(err)?

### What version of Go are you using (`go version`)?
go 1.9

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ALTree** [comment]
Syntactic sugar for the `if err != nil` idiom is being discussed here: #21161. There are several proposals there, including a few similar to yours. Closing here, so we can keep the discussion in one place.
