### ISSUE TITLE
x/crypto/ssh: Is there a way to show detail msg for failed ssh command excu?

### ISSUE THREAD

**Issue by DeathPoem** [golang/go#23023]
Context: go version go1.9.2 linux/amd64, ubuntu 16.04.

[related issue](https://github.com/golang/go/issues/14251)

[related commit](https://github.com/golang/crypto/commit/de15db8e4b7d9627c2c0922002d1de9806af8564)

My Problem situation: 

I was going to run a command like 

``` go
command := "fio -direct=1 -iodepth 1 -thread -rw=randwrite -ioengine=psync -bs=16k -size=10M -numjobs=1 -runtime=1 -verify=md5 -group_reporting -name=mytest -filename=\\/dev\\/xxx | grep \\'bad\\'"
// read session.StderrPipe() and session.StdoutPipe()
_, err = session.Output(cmd)
```

What I got is err as 'Process exited with status 1' with stdoutput and stderr as empty.
What I want is to get detail why my command fails.
Due to 'related commit' it seems that this lib don't support more detail msg, how can I get over it? (Although I can work around it)

**Comment by bradfitz** [comment]
You can't use the Output or CombinedOutput methods while also StderrPipe and StdoutPipe.

Are you checking your errors?

Actually, where's your actual code? There's not enough context to help here.

But in general, questions about Go should go to https://golang.org/wiki/Questions.

**Comment by DeathPoem** [comment]
@bradfitz I would move to https://golang.org/wiki/Questions
