### ISSUE TITLE
website: can't download Go from downloads page

### ISSUE THREAD

**Issue by lukewatts** [golang/go#23030]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
na

### Does this issue reproduce with the latest release?
na

### What operating system and processor architecture are you using (`go env`)?
na

### What did you do?
1. Visit https://golang.org/dl/
2. Clicked any of the links (all OSes)
3. Get error:
```
This site can’t be reached

The webpage at https://storage.googleapis.com/golang/go1.9.2.windows-amd64.msi might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
```

### What did you expect to see?
Expect to get the download

### What did you see instead?
```
This site can’t be reached

The webpage at https://storage.googleapis.com/golang/go1.9.2.windows-amd64.msi might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
```

**Comment by ALTree** [comment]
cc @bradfitz @andybons

**Comment by lukewatts** [comment]
Seems to be working again now

**Comment by bradfitz** [comment]
We don't even link to those URLs anymore. Not sure how you found those storage.googleapis.com URLs.

Also, ERR_TUNNEL_CONNECTION_FAILED is proxy-related. Perhaps your proxy was down.
