### ISSUE TITLE
x/tools/playground: IP geolocation bug

### ISSUE THREAD

**Issue by montanaflynn** [golang/go#23038]
So I found some links on google groups that went to play.golang.org returned an error for me saying it's illegal to share code snippets in my country. I'm in SF USA, and can create new play links and share them myself without issue. 

Not sure if this is the best place but it's where the link sent me to create an issue.

Links in question:

https://play.golang.org/p/cJNuTP6nJN
https://play.golang.org/p/2JZOf1GhPT

Found on:

https://groups.google.com/forum/#!topic/Golang-nuts/FqUL7WZpM7w

### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Went to https://play.golang.org/p/cJNuTP6nJN from google groups discussion.

### What did you expect to see?

The google play code editor.

### What did you see instead?

Unavailable For Legal Reasons

Viewing and/or sharing code snippets is not available in your country for legal reasons. This message might also appear if your country is misdetected. If you believe this is an error, please file an issue.

**Comment by bradfitz** [comment]
What's your IP, if you don't mind sharing?

Otherwise email me at golang.org

/cc @broady

**Comment by broady** [comment]
Strange that you can create new links but not look at existing ones. That shouldn't happen.

**Comment by odeke-em** [comment]
These other bugs look like they are related:
* https://github.com/golang/go/issues/21186
* https://github.com/golang/go/issues/20866 in which I believe @broady got Google internally to add Canada https://github.com/golang/go/issues/20866#issuecomment-324103477
* https://github.com/golang/go/issues/17765

**Comment by montanaflynn** [comment]
@bradfitz here's my 136.24.32.109 (https://ipinfo.io/136.24.32.109)

@odeke-em thanks for the related issues, I somehow missed them

**Comment by bradfitz** [comment]
@montanaflynn, do you have IPv6 connectivity? Our IPv6 geolocation is relatively weak.

**Comment by montanaflynn** [comment]
@bradfitz yes, here is my ipv6 address: 2604:5500:c290:7b00:e9f3:2b21:a98a:c101

**Comment by bradfitz** [comment]
It's not a geolocation bug. Both that IPv4 and IPv6 address are being mapped to the correct location.

@broady, all yours.

**Comment by bradfitz** [comment]
Note to Googlers: see http://b/70346540

**Comment by bradfitz** [comment]
http://b/70346540 was closed as nothing to do.

@montanaflynn, can you try again? Is this still reproducing?
