### ISSUE TITLE
syscall: nacl can't Seek properly

### ISSUE THREAD

**Issue by bradfitz** [golang/go#23035]
See trybot failures from https://go-review.googlesource.com/c/go/+/82535 ...

https://storage.googleapis.com/go-build-log/6cb9912e/nacl-amd64p32_ce6fb3f2.log

Skipping those tests on nacl for now.

**Comment by dsnet** [comment]
Possibly related: #21728

**Comment by bradfitz** [comment]
@dsnet, yup, dup. Thanks.
