### ISSUE TITLE
cmd/go: running go test ./... elides most test results due to vet

### ISSUE THREAD

**Issue by stuartcarnie** [golang/go#23047]
### What version of Go are you using (`go version`)?

```
go version go1.10beta1 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stuartcarnie/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/stuartcarnie/projects/go/influxdata/influxdb"
GORACE=""
GOROOT="/Users/stuartcarnie/.gvm/versions/go1.10beta1.darwin.amd64"
GOTMPDIR=""
GOTOOLDIR="/Users/stuartcarnie/.gvm/versions/go1.10beta1.darwin.amd64/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/98/6s2bgx_x3vg8c9yrf1v4vp700000gn/T/go-build941673718=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

* download https://github.com/influxdata/influxdb
* restore dependencies: `gdm restore`
* `go test ./...`

### What did you expect to see?

Test results for all packages

### What did you see instead?

Test results stop at the `github.com/influxdata/influxdb/cmd` package

### Workaround

`go test -vet=off`

**Comment by ianlancetaylor** [comment]
Can you show us the output of `go test -x ./...`?

**Comment by stuartcarnie** [comment]
relevant gist of output https://gist.github.com/stuartcarnie/a9a703f73d368aa4b56b296258ce8e91

**Comment by rsc** [comment]
Reproduced. Thanks for the good report.
