### ISSUE TITLE
go/types: errors when declaring methods with type alias receivers

### ISSUE THREAD

**Issue by mdempsky** [golang/go#23042]
cmd/compile accepts this package:

    package p

    type T struct{}

    var _ = T.m
    var _ = T{}.m
    var _ interface{m()} = T{}

    type U = T
    func (U) m()

but go/types rejects it with:

    r.go:5:9: invalid operation: T (type) has no field or method m
    r.go:6:9: invalid operation: (T literal) (value of type T) has no field or method m
    r.go:7:24: cannot use (T literal) (value of type T) as interface{m()} value in variable declaration: missing method m

Notably, if you move the type alias and method declaration above the variable declarations, go/types accepts it.

It's worth noting that gccgo actually crashes on the method declaration with

    go1: internal compiler error: in add_method_declaration, at go/gofrontend/types.cc:9759

It makes me wonder a little if we should just require that methods be directly associated with the actual receiver type. Rationale:

  1. The spec says "The type denoted by T is called the receiver base type; it must not be a pointer or interface type and it must be defined in the same package as the method." It links to "defined type", which is disjoint from type aliases, so arguably the spec doesn't allow methods declared on type aliases anyway.

  2. Since we can only declare methods on types declared in the same package anyway, there's not much to be gained by allowed method declarations on type aliases.

/cc @griesemer @ianlancetaylor

**Comment by ianlancetaylor** [comment]
The alias proposal at https://github.com/golang/proposal/blob/master/design/18130-type-alias.md specifically permits declaring methods using either type.

> Since T1 is just another way to write T2, it does not have its own set of method declarations. Instead, T1’s method set is the same as T2’s. At least for the initial trial, there is no restriction against method declarations using T1 as a receiver type, provided using T2 in the same declaration would be valid. Note that if T1 is an alias for a type T2 defined in an imported package, method declarations using T1 as a receiver type are invalid, just as method declarations using T2 as a receiver type are invalid.

**Comment by griesemer** [comment]
I think the original intent for alias type names was that this should work. Since cmd/compile accepts it, I would say this is a go/types bug (and perhaps the spec could be clearer).

**Comment by griesemer** [comment]
@mdempsky Regarding the spec's prose: "The type denoted by T is called the receiver base type; it must not be a pointer or interface type and it must be defined in the same package as the method."
"Defined" refers to the type, not the type name. An alias (type name) may still denote a defined type. So I think the spec is correct here.

**Comment by mdempsky** [comment]
@griesemer I suppose these sentences are where my confusion really come from:

> That parameter section must declare a single non-variadic parameter, the receiver. Its type must be of the form T or *T (possibly using parentheses) where T is a type name.

The "possibly using parentheses" phrasing suggests to me the "form" we're talking about is syntactic, not structural. And so "T" appears to refer to the literal type name appearing in the method declaration's receiver parameter type.
