### ISSUE TITLE
go1.10 build c-shared for to windows dll

### ISSUE THREAD

**Issue by Baozisoftware** [golang/go#23052]
Glad to see go1.10 support compiled dll, but the following questions (suggestions):
1. The export function has unnecessary entries;
2. The output file should be added ". dll" suffix;
3. Hope that you can specify the value of cgocheck at compile time instead of the runtime specified;
4. Hope to get rid of symbolic information against static analysis.

Here's the old version of the implementation:
[disable cgocheck for golang default](https://github.com/Baozisoftware/go/blob/master/src/runtime/runtime1.go#L356)

[go build to windows dll](https://github.com/Baozisoftware/go-dll/wiki/%E7%94%9F%E6%88%90Go%E7%89%88DLL#makebat)

Thank golang team for their hard work.

**Comment by ianlancetaylor** [comment]
I'm sorry, I'm not really sure what you mean by any of this.  Can you be more specific?  Is there any connection between the four things you mention?

CC @nadiasvertex

**Comment by Baozisoftware** [comment]
Sorry, my English is poor.

## test.go
``` go
package main

import "C"

func main(){
}

//export Add
func Add(x,y int)int{
    return x+y
}

//export AddStr
func AddStr(x,y string)string{
    return x+y
}
```
Use the cmd to build(host:windows/amd64,go1.10b1):
> go build -ldflags="-s -w" -buildmode=c-shared test.go

Yes,i make it,but i have questions:
1. Output "test" file (**no ".dll" suffix**,here should be **"test.dll"**);
2. Use dumpbin view export functions, I found a lot of goruntime functions export, hoping to hide them.
3. If cgocheck=1(default value),call **"Add"** funcation is normal,but call **"AddStr"** is **crash**,and At the moment can only be set before the call
> GODBUG=cgocheck=0 

to solve, I hope we can compile this time instead of running to deal with this issue;

4. Use **-ldflags=-s -w** to build Seems to not be able to clear the symbolic information, you can still see a lot of goruntime symbols in IDA, although you can compile it with **"strip"** to manually clean it and hope it's built-in.

Thanks again.

**Comment by ianlancetaylor** [comment]
I think these problems will be easier to fix if you file separate issues for separate problems.

Regarding point 3, an exported Go function is not permitted to return a Go string.  See https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers .

**Comment by Baozisoftware** [comment]
Yes, these issues can be solved manually, but if the merger into the official code may have a better experience? I will modify the source code after the official version go1.10 released, thank you.

**Comment by shyandsy** [comment]
@Baozisoftware 
I tried this command to build dll library
```
set CGO_ENABLED=1
go build -ldflags="-s -w" -buildmode=c-shared test.go
```

when I use this in the VC++ project, VS said  "Warning	LNK4003	invalid library format; library ignored"

any solution?

**Comment by ianlancetaylor** [comment]
@shyandsy This issue is closed.  I recommend that you use a forum to ask your question.  Please see https://golang.org/wiki/Questions .
