### ISSUE TITLE
doc: editors.html uses Gogland (deprecated)

### ISSUE THREAD

**Issue by vvoody** [golang/go#23054]
Hi!

JetBrains renamed their Go IDE from [Gogland to Goland](https://blog.jetbrains.com/go/2017/11/02/announcing-goland-former-gogland-eap-18-final-product-name-templates-support-and-more/). It's time to update the page [Editor plugins and IDEs](https://golang.org/doc/editors.html) on main site.

Thanks.

**Comment by ALTree** [comment]
Thanks for the report. The doc page has already been fixed, you can see a preview here: https://tip.golang.org/doc/editors.html. It'll be deployed on the main domain for go1.10.

Closing here, since there isn't anything more to do.
