### ISSUE TITLE
all: remove funny tags

### ISSUE THREAD

**Issue by mikioh** [golang/go#23056]
The go repository now holds a few funny tags such as ```andybons/cachedir.mailed```; see https://go.googlesource.com/go/

/CC @andybons

**Comment by mvdan** [comment]
There's also `1.10beta1.mailed`. Perhaps there should be some way to keep `*.mailed` tags from being created, or a bot to remove them periodically. The tags get created by `git-codereview`, so it remains possible that others will push them by mistake.

**Comment by andybons** [comment]
Whoops! Sorry about that everyone. My first beta release. I’m keeping notes on gotchas so will add this to the list.

Thanks for the report! I’ve removed the tags.
