### ISSUE TITLE
reflect: StructOf allows creation of impossible types

### ISSUE THREAD

**Issue by dsnet** [golang/go#23063]
The validation logic in `reflect.StructOf` needs some work.

### Can embed an anonymous type
```go
t := reflect.TypeOf(struct{ Nobody string }{})
sf := reflect.StructField{Name: "Billy", Type: t, Anonymous: true}
t2 := reflect.StructOf([]reflect.StructField{sf})
t2.Field(0) // StructField{Name: "Billy", Type: t, Anonymous: true}
```
This is invalid because the Go language forbids embedding an anonymous type.

### Can rename an embedded type
```go
type Batman struct{ Banananananana string }
t := reflect.TypeOf(Batman{})
sf := reflect.StructField{Name: "Superman", Type: t, Anonymous: true}
t2 := reflect.StructOf([]reflect.StructField{sf})
t2.Field(0) // StructField{Name: "Superman", Type: t, Anonymous: true}
```
When a type is embedded, the field takes on the name of the type. However, I was able to rename the field to `Superman`, when it should have been `Batman`.

**Comment by jimmyfrasche** [comment]
Renaming is to support type aliases.

**Comment by dsnet** [comment]
> Renaming is to support type aliases.

Ah, you are correct. Type aliases actually make both cases possible.
