### ISSUE TITLE
runtime: signal stack change broke DragonflyBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#23061]
This CL (292558b) broke Dragonfly:

runtime: restore the Go-allocated signal stack in unminit
https://go-review.googlesource.com/c/go/+/81476

I emailed Austin & Ian details of how to access a VM I created.

**Comment by ianlancetaylor** [comment]
This most likely has to do with the fact that on DragonFly a newly created thread inherits the alternate signal stack of the creating thread.  See the comment in `minit` in runtime/os_dragonfly.go.

**Comment by ianlancetaylor** [comment]
Sorry, I was looking at an old source tree due to a complex accident.  DragonFly used to work that way, but it's been fixed.
