### ISSUE TITLE
crypto/x509/pkix: FillFromRDNSequence does not preserve multi-value RDNs

### ISSUE THREAD

**Issue by ramoas** [golang/go#23069]
### What version of Go are you using (`go version`)?
This issue affects Go 1.8 and later as a consequence of https://github.com/golang/go/commit/809a1de1ac1ccc76f7a4faf630017626f2f68231 to fix  [#16836](https://github.com/golang/go/issues/16836) (and #12342).

Prior to Go 1.8 and that change, Go did not process multi-value RDNs -- it always assumed just one attribute and value (the first) per RDN.

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
The OS and architecture should not matter.

### What did you do?
https://play.golang.org/p/7OIuhautCe

### What did you expect to see?
The multi-value nature of any RDN is preserved.  That is, the length of the subject (and issuer) RDNSequence before pkix.FillFromRDNSequence and after pkix.ToRDNSequence should match.

### What did you see instead?
The multi-value nature of any RDN is not preserved by pkix.FillFromRDNSequence.  That is, the length of the subject (and issuer) RDNSequence before pkix.FillFromRDNSequence and after pkix.ToRDNSequence do not match.

As previously noted in comments on https://github.com/golang/go/commit/809a1de1ac1ccc76f7a4faf630017626f2f68231, the [original Gerrit CR](https://go-review.googlesource.com/c/go/+/30810#message-a29d12cfb3550dc2ce212ec60ddf32bf86363f13), and #12342, if this will not be fixed, then the behavior should be documented at a minimum.

**Comment by ianlancetaylor** [comment]
CC @FiloSottile

**Comment by rsc** [comment]
Clearly missed for Go 1.11.

**Comment by FiloSottile** [comment]
This is bad, also because it will lead to a parse-serialize cycle returning a semantically different result, but I can't see how to fix this without making a whole new set of APIs, which is not an option for such rare certificates.

Unless anyone has any better idea, we should just document this behavior, maybe in FillFromRDNSequence.
