### ISSUE TITLE
x/tools/cover doesn't handle multiple sample from the same location in cover profile.

### ISSUE THREAD

**Issue by haya14busa** [golang/go#23076]
### What version of Go are you using (`go version`)?
N/A

### Does this issue reproduce with the latest release?
yes. This issue might be a problem with upcoming Go 1.10 release.

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?

Parse the test cover profile result with x/tools/cover package.

### What did you expect to see?

Multiple samples from the same location will be merged when parsing cover
profile in the same way as src/cmd/cover/profile.go[1].

[1]: https://github.com/golang/go/commit/f39050c8ebf894ccedc0b99de96f7412be97af89

### What did you see instead?

The implementation between x/tools/cover and src/cmd/cover/profile.go is
different and x/tools/cover won't handle multiple samples from the same location.

Now that go test supported -coverprofile with multiple packages (#6909),
x/tools/cover/profile should also handle multiple samples from the same
location.

Because go test -coverprofile with multiple packages just merges the cover
profile result by appending cover profile[2], if users specify -coverpkg flag, the
merged profile will contain the multiple samples from the same location.

#### How to reproduce

1. Run `go1.10beta1 test -v -coverprofile=coverage.out -coverpkg=./... ./...` under this directory https://github.com/haya14busa/goverage/tree/master/example/root

```
mode: count
github.com/haya14busa/goverage/example/root/root.go:8.24,10.2 1 1
github.com/haya14busa/goverage/example/root/root.go:8.24,10.2 1 0
github.com/haya14busa/goverage/example/root/root.go:12.17,15.2 2 1
github.com/haya14busa/goverage/example/root/root.go:12.17,15.2 2 0
github.com/haya14busa/goverage/example/root/sub/sub.go:3.23,5.2 1 0
github.com/haya14busa/goverage/example/root/sub/sub.go:3.23,5.2 1 1
github.com/haya14busa/goverage/example/root/sub/sub.go:7.24,9.2 1 1
github.com/haya14busa/goverage/example/root/sub/sub.go:7.24,9.2 1 0
github.com/haya14busa/goverage/example/root/sub/sub.go:11.30,13.2 1 1
github.com/haya14busa/goverage/example/root/sub/sub.go:11.30,13.2 1 1
```

2. Parse this profile using x/tools/cover

```go
package main

import (
	"fmt"

	"golang.org/x/tools/cover"
)

func main() {
	profile, _ := cover.ParseProfiles("./coverage.out")
	for _, p := range profile {
		fmt.Println(p.FileName)
		for _, b := range p.Blocks {
			fmt.Printf("StartLine:%v EndLine:%v Count:%v\n", b.StartLine, b.EndLine, b.Count)
		}
	}
}
```

Output:

```
github.com/haya14busa/goverage/example/root/root.go
StartLine:8 EndLine:10 Count:1
StartLine:8 EndLine:10 Count:0
StartLine:12 EndLine:15 Count:1
StartLine:12 EndLine:15 Count:0
github.com/haya14busa/goverage/example/root/sub/sub.go
StartLine:3 EndLine:5 Count:0
StartLine:3 EndLine:5 Count:1
StartLine:7 EndLine:9 Count:1
StartLine:7 EndLine:9 Count:0
StartLine:11 EndLine:13 Count:1
StartLine:11 EndLine:13 Count:1
```

Expect:

```
github.com/haya14busa/goverage/example/root/root.go
StartLine:8 EndLine:10 Count:1
StartLine:12 EndLine:15 Count:1
github.com/haya14busa/goverage/example/root/sub/sub.go
StartLine:3 EndLine:5 Count:1
StartLine:7 EndLine:9 Count:1
StartLine:11 EndLine:13 Count:1
```

I'll send a CL soon.

[2]: https://github.com/golang/go/commit/283558e42b88a6afa39da6ad4ae87558dc053776#diff-acaf53a9cd478507ebbcf85037940b4d

**Comment by JicLotus** [comment]
Did you add some test for this issue?
