### ISSUE TITLE
net: UDPConn.WriteMsgUDP fails on Windows XP

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#23072]
new windows-386-xp builder on https://build.golang.org fails at commit 29cb57c

https://build.golang.org/log/e18744bedc520329ee61476194bf5020a66ba706

with

```
--- FAIL: TestUDPConnSpecificMethods (0.02s)
	protoconn_test.go:142: write udp4 127.0.0.1:1138->127.0.0.1:1138: wsasendmsg: An invalid argument was supplied.
--- FAIL: TestWriteToUDP (0.00s)
	udpsock_test.go:168: write udp 127.0.0.1:1282: wsasendmsg: An invalid argument was supplied.
FAIL
FAIL	net	10.336s
```

As I explained at https://github.com/golang/go/issues/10267#issuecomment-350509122 I think we should just skip correspondent parts of the test on Windows XP.

Alex

**Comment by bradfitz** [comment]
What's the proper way to detect XP?

**Comment by alexbrainman** [comment]
> What's the proper way to detect XP?

Search for isWindowsXP in main repo.

I am going to send a fix for this in a little while. Please wait.

Alex

**Comment by alexbrainman** [comment]
@bradfitz do we have Windows XP trybot?

Alex

**Comment by bradfitz** [comment]
@alexbrainman, no trybot. We just have a single XP VM currently. Maybe @johnsonj will get Windows Server 2003 working on GCE and then we could have an opt-in Trybot or something.

**Comment by alexbrainman** [comment]
Cool, I will test my change here, and then we'll submit and see.

Alex

**Comment by alexbrainman** [comment]
I really do not know how to fix this - I am not even sure if it is possible to fix. I am just skipping broken tests for the moment.

Alex

**Comment by bradfitz** [comment]
@alexbrainman, that's fine.
