### ISSUE TITLE
Lot of heuristic antivirus detection with GOARCH=386 on Windows

### ISSUE THREAD

**Issue by crazy-max** [golang/go#23070]
### What version of Go are you using (`go version`)?

`go version go1.9.1 windows/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\dev\go;C:\dev\neard\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\username\AppData\Local\Temp\go-build
520536943=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### My issue

Hi, i have made a small wrapper written in Go to make [some apps portable](https://github.com/portapps) on Windows system. For example [slack-portable](https://github.com/portapps/slack-portable).

And i have an issue when the same code is compiled for 386 goarch. There are lot of heuristic antivirus detections (13 / 67), whereas if it's compiled in x64, there are far fewer (2 / 66).

Here is an example with slack-portable :

* [`slack-portable-ia32.exe`](https://www.virustotal.com/#/file/198e9e5a03948a2938f86624ba306fe191f124498ee39bca4fb82e5bfea0d77c/detection)
* [`slack-portable-x64.exe`](https://www.virustotal.com/#/file/529e145f8a12b4f50533884f31b436310897dc0443bc2e286217730da4ab80ce/detection)

Can you tell me the difference between compiling in 386 versus compiling in x64 and how antivirus scans this type of detection?

Thanks a lot!

**Comment by randall77** [comment]
An interesting observation.  However, this sounds like more of an issue with the antivirus than an issue with Go, directly at least.  We only use our bug tracker for tracking actionable bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions like this.

You can come back and reopen or refile this bug if there is something actionable that needs to be done in the compiler/linker/whatever.
