### ISSUE TITLE
doc: go1.10.html states that i386/amd64 executables fail on NetBSD amd64

### ISSUE THREAD

**Issue by krytarowski** [golang/go#23073]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

N/A

### What did you expect to see?

Removed note that 32-bit applications are broken on 64-bit NetBSD kernel.

### What did you see instead?

The reverse.

The breakage was a regression on HEAD.

Fix:

```
Module Name:    src
Committed By:   christos
Date:           Thu Dec  7 16:22:22 UTC 2017

Modified Files:
        src/sys/arch/amd64/amd64: netbsd32_machdep.c

Log Message:
Keep fs/gs the same for the signal context; otherwise calling things
like __lwp_getprivate_fast() from a signal handler (that uses %gs) die.

Merge context building code.


To generate a diff of this commit:
cvs rdiff -u -r1.113 -r1.114 src/sys/arch/amd64/amd64/netbsd32_machdep.c
```

http://mail-index.netbsd.org/source-changes/2017/12/07/msg090270.html

**Comment by bradfitz** [comment]
The typo was already fixed in https://github.com/golang/go/commit/38083c83a60aa7a1b71b072ea5ecf70a3721ef2e

So does this pass now on an amd64 NetBSD kernel:

```
$ cd $GOROOT/src
$ GOHOSTARCH=386 GOARCH=386 ./all.bash
```

?

Is there a pullup to the netbsd-8 branch pending?

**Comment by krytarowski** [comment]
http://netbsd.org/~kamil/golang/golang-i386-on-amd64-2017-12-11.txt

**Comment by bradfitz** [comment]
@krytarowski, you didn't set `GOHOSTARCH=386` in that log. Another way you can tell you didn't have that set is you can see this line in your output:

```
Building packages and commands for host, netbsd/amd64.
```

So it's auto-detecting that your host architecture is amd64 and the compiler/linker are 64-bit, even if it's producing 32-bit binaries in the end.

**Comment by krytarowski** [comment]
http://netbsd.org/~kamil/golang/golang-i386-on-amd64-2017-12-11-hosti386.txt

NetBSD-8 will receive the needed patches.

**Comment by bradfitz** [comment]
Thanks. Feel free to review https://golang.org/cl/82918

**Comment by krytarowski** [comment]
`Only <code>GOARCH</code> <code>amd64</code> and <code>386</code> are fully verified. The <code>arm</code> port has not been verified.`

**Comment by krytarowski** [comment]
The arm port is known to work, but I don't know offhand the status.

**Comment by krytarowski** [comment]
```
$ GOHOSTARCH=386 GOARCH=386 ./all.bash 

[...]

ALL TESTS PASSED
---
Installed Go for netbsd/386 in /public/go
Installed commands in /public/go/bin
*** You need to add /public/go/bin to your PATH.
$ uname -a
NetBSD chieftec 8.0_BETA NetBSD 8.0_BETA (GENERIC) #1: Mon Dec 11 01:50:05 CET 2017  root@chieftec:/public/netbsd-root-8/sys/arch/amd64/compile/GENERIC amd64
$ cd /public/src.git/                                                                                                        
$ git log -2 # two cherry-picked patches for the -8 kernel
commit 82377c2808264c8439af91c1eba3528ba4edc6e1 (HEAD -> netbsd-8)
Author: christos <christos@NetBSD.org>
Date:   Thu Dec 7 16:22:22 2017 +0000

    Keep fs/gs the same for the signal context; otherwise calling things
    like __lwp_getprivate_fast() from a signal handler (that uses %gs) die.
    
    Merge context building code.

commit ae911ba8cf4f25bf73c501b8994dff8477ced26d
Author: christos <christos@NetBSD.org>
Date:   Thu Dec 7 19:49:43 2017 +0000

    - Reset ignored or masked traps to avoid infinite loops
    - If sigpost fails don't add an SDT_PROBE
    ok (and author) chuq
```

**Comment by bradfitz** [comment]
> The arm port is known to work, but I don't know offhand the status.

If we haven't had a builder for it for years, we assume it doesn't work.

**Comment by krytarowski** [comment]
I will give it a try tomorrow on RPi1.

**Comment by krytarowski** [comment]
https://releng.netbsd.org/cgi-bin/req-8.cgi tickets 443 and 444

**Comment by krytarowski** [comment]
I've fired building go14 (with dependencies) natively on: armv6-unknown-netbsdelf*-eabihf

It will take a while.

**Comment by bradfitz** [comment]
@krytarowski, there's no need for that. Your GOROOT_BOOTSTRAP environment variable defaults to $HOME/go1.4 but that's just a default, and it doesn't need to be Go 1.4. It can be anything greater than that, too.

So you can use a fast machine to run master's $GOROOT/src/bootstrap.bash and set GOOS=netbsd GOARM=arm and build your $GOROOT_BOOTSTRAP from the fast machine.

**Comment by krytarowski** [comment]
I don't have enough RAM, and I don't want to use swap on this device. I will ask other developers with more advanced ARM hardware for a test.

**Comment by krytarowski** [comment]
OK, upstream golang/arm is broken - it works with floating patches. Part of them are in https://github.com/oshimaya/go/commits/go1.4-netbsd

**Comment by bradfitz** [comment]
Okay, then I can update the docs to say that netbsd/arm is definitely broken, unless you want to mail those patches soon.

**Comment by krytarowski** [comment]
I cannot fix it myself in close time, as I'm burdened by amd64 work.
