### ISSUE TITLE
access: golang/lint

### ISSUE THREAD

**Issue by avelino** [golang/go#23089]
golang/lint[1] project is not very active and I want to help maintain, revise PRs

[1] https://github.com/golang/lint

**Comment by bradfitz** [comment]
I see zero comments on that issue tracker from you and zero commits in that repo from you.

You're welcome to start contributing, but we're not ready to hand over maintainership to somebody that's new to the codebase & community and hasn't demonstrated their abilities & responsibilities.

It's true that it's not very maintained today, but that doesn't necessarily mean it's up for grabs. But if you start working on issues & reviews, you could quite easily become the maintainer.

**Comment by avelino** [comment]
Let's go to work, thanks for the feedback!
