### ISSUE TITLE
go/doc: examples that depend on top-level functions should be playable

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#23095]
See https://golang.org/pkg/go/types/#example_Info
The example isn't runnable because two functions
`func mode(tv types.TypeAndValue) string` and `func exprString(fset *token.FileSet, expr ast.Expr) string`
are declared outside of `func ExampleInfo()`.
Ideally, tools should consult this situation.

**Comment by dsnet** [comment]
> Ideally, tools should consult this situation.

I'm not sure I understand what  you mean by this.

**Comment by hirochachacha** [comment]
I'm not sure how godoc works, but I suppose
```
package xxx

import "fmt"

func b() {
  fmt.Println("B")
}

func ExampleA() {
  fmt.Println("A")
}

func ExampleB() {
  b()
}
```
godoc can construct complete program for A.
```
package main

import "fmt"

func main() {
  fmt.Println("A")
}
```
But, it cannot construct complete program for B. It should emit
```
package main

import "fmt"

func b() {
  fmt.Println("B")
}

func main() {
  b()
}
```

I guess?
