### ISSUE TITLE
x/build: netbsd-386 builds at go1.8 use a broken go binary

### ISSUE THREAD

**Issue by bsiegert** [golang/go#23102]
The "Sub-repositories at release-branch.go1.8" column for netbsd-386 is all red. The error is always

    go list error:
    
    tests failed: fork/exec /tmp/workdir/go/bin/go: exec format error

This indicates that there is a broken `go` binary that is being used. Does that builder compile go1.8 from scratch?

**Comment by bradfitz** [comment]
> Does that builder compile go1.8 from scratch?

If needed. If it's already built, it uses a cached version.

I'll just disable netbsd-* for Go 1.8. And maybe even Go 1.9, even though it's passing. It's kinda a waste of resources.
