### ISSUE TITLE
doc: prefer Delve over gdb

### ISSUE THREAD

**Issue by heschik** [golang/go#23108]
We have a couple documents that discuss debugging: [Debugging with GDB ](https://tip.golang.org/doc/gdb) and [Diagnostics](https://tip.golang.org/doc/diagnostics.html#debugging).

At this point Delve is a much better Go debugger than GDB is. It understands Go data structures better, it can handle expressions better, it doesn't get confused by goroutines, etc. GDB can be better for cgo, or debugging the runtime itself, but I think most users are much better served by Delve.

If everyone agrees, I would like to say so on the GDB document, and strengthen the wording on the diagnostics page a little.

cc @aarzilli @derekparker @ianlancetaylor @hyangah

**Comment by cherrymui** [comment]
Does Delve support all architectures now?

**Comment by laboger** [comment]
I don't believe Delve works on ppc64le.

**Comment by heschik** [comment]
That's a good point. Sorry for the Intel centrism. I'd still like to recommend it, but with that important caveat.

**Comment by dlsniper** [comment]
Unfortunately support for some BSD OSes is also not present and 32bit support is also missing. I'm not sure about the ARM support.

I wonder if the right people to help Delve get in a better shape on those platforms know about it?

**Comment by ianlancetaylor** [comment]
I agree with your proposal as amended.
