### ISSUE TITLE
gomobile: binding 'main' package () is not supported

### ISSUE THREAD

**Issue by C-ollins** [golang/go#23106]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2 linux/amd64
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
linux amd64
### What did you do?
I ran ` gomobile bind -target android`
If possible, provide a recipe for reproducing the error.
`git clone https://github.com/decred/dcrwallet`
` gomobile bind -target android`
### What did you expect to see?
I don't know what was supposed to show but all i wanted to do was to compile my project to an Android library so i can import it into my Android studio project
### What did you see instead?
`gomobile: binding 'main' package () is not supported`

**Comment by titanous** [comment]
This is working as intended, you should use `gomobile bind` against a non-main package (it will create bindings for the exported symbols)

For questions about Go, see https://golang.org/wiki/Questions
