### ISSUE TITLE
Spelling error at doc\editors.html containing "GogLand" instead of "GoLand"

### ISSUE THREAD

**Issue by peaches6** [golang/go#23104]
#####Website at https://golang.org/doc/editors.html contains "Gogland" instead of GoLand
![image](https://user-images.githubusercontent.com/31016869/33883563-2e7f528a-df34-11e7-905f-8fa74273fed7.png)
![image](https://user-images.githubusercontent.com/31016869/33883662-83e2a7f4-df34-11e7-93fe-c92b610fac2e.png)
yet in the docs https://github.com/golang/go/blob/master/doc/editors.html , it contains the correct spelling.

**Comment by ALTree** [comment]
https://golang.org/doc/editors.html has the 1.9 website. It'll be updated to serve the tip doc for go1.10. Until then, tip is served at https://tip.golang.org/doc/editors.html. As you noticed, the name is already fixed.

Nothing to do here, closing this.
