### ISSUE TITLE
plugin: add "buildmode=plugin" support on PowerPC

### ISSUE THREAD

**Issue by AndreyNevolin** [golang/go#23117]
Hi,

Do you have plans on supporting plugins on PowerPC?

ppc64le is of particular interest (at least for me and my company :))

**Comment by mundaym** [comment]
Looks like Lynn added it in [CL 55850](https://go-review.googlesource.com/c/go/+/55850) and it is also mentioned in the draft release notes for 1.10 (https://beta.golang.org/doc/go1.10#compiler). I think it should therefore be working in the beta1 version of 1.10. The final release should be available in February 2018. If you are able to try out the beta now then that would be great.

I'm going to close this issue as a duplicate of #20756. Feel free to open new issues if you run into bugs while using the beta.

**Comment by AndreyNevolin** [comment]
Thank you. I'll try the beta.
Sorry for producing a duplicate. I searched Opened issues only before submitting this one. Since the original one is closed, I didn't notice it.
