### ISSUE TITLE
x/crypto/ssh: ssh failed to connect: ssh: handshake failed: agent: failed to list keys

### ISSUE THREAD

**Issue by vitesse-ftian** [golang/go#23119]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.1, 1.9.2

### Does this issue reproduce with the latest release?
with 1.9.2 release

### What operating system and processor architecture are you using (`go env`)?
Unbuntu 16

### What did you do?
ssh was working, but suddenly I saw this,
ssh: handshake failed: agent: failed to list keys

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by titanous** [comment]
Please provide the code that you are using to make the SSH connection, and check that the SSH agent is configured properly and working with another client (for example OpenSSH).

**Comment by bradfitz** [comment]
There's not enough information here to help.

For questions about Go, see https://golang.org/wiki/Questions.

But lie @titanous says, your environment and/or agent are probably messed up. This doesn't smell like a Go problem. Closing as there's nothing actionable here for us.

**Comment by vitesse-ftian** [comment]
Just to confirm that it is environment/agent related.   I ran into this problem again and the following fixed it.
```
eval `ssh-agent -s`
ssh-add
```
