### ISSUE TITLE
internal/poll: ppc64le stuck waiting for semaphore

### ISSUE THREAD

**Issue by tophj-ibm** [golang/go#23111]
Note: I haven't finished debugging this, but discussing with @laboger, we thought it is important enough to raise an issue for the beta. This issue involves docker + go master (including 1.10beta1), and at the moment I'm thinking it's a go issue because it only occurs on ppc64le, and docker + main dependencies don't have much architecture specific code.

### What version of Go are you using (`go version`)?
go1.10beta1

### Does this issue reproduce with the latest release?
Yes beta, No 1.9.2

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04 host, Debian:Stretch container

GOARCH="ppc64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build571013459=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Testing upstream docker with go version 1.10beta1

Set GO_VERSION to go1.10beta1 in Dockerfile.ppc64le, and on ppc64le run 
`TESTFLAGS="-check.f DockerSuite.TestAttachClosedOnContainerStop" make test-integration`

(This runs this specific test https://github.com/moby/moby/blob/d65ab869e8712d08fb94a5337b83df5d247bf25b/integration-cli/docker_cli_update_unix_test.go#L272)

### What did you expect to see?

PASS

### What did you see instead?

FAIL / panic (test timed out)

https://gist.github.com/tophj-ibm/4049252d8ad8227c8aad45598d08750a

The test, and a few other tests, get stuck at cmd.Wait(), waiting indefinitely for a semaphore.

We've narrowed the commit down to https://github.com/golang/go/commit/382d4928b8a758a91f06de9e6cb10b92bb882eff. But seeing as that is basically a check to make sure fd's are closed, makes me think there is an underlying issue somewhere with an fd not being closed correctly.

Again, I'm still trying to trace what is happening, but if you have any ideas, all help is appreciated.

All the go tests pass.

**Comment by ianlancetaylor** [comment]
It's very unclear to me why anything around here would be ppc64le specific.  Does this test pass on other architectures?

**Comment by crvv** [comment]
There is a gorouting got stuck at this line, a `pty.Read()` call. `pty` is set to blocking mode by an `(*os.File).Fd()` call.
https://github.com/moby/moby/blob/d65ab869e8712d08fb94a5337b83df5d247bf25b/integration-cli/docker_cli_attach_unix_test.go#L54
https://github.com/kr/pty/blob/95d05c1eef33a45bd58676b6ce28d105839b8d0b/pty_linux.go#L35

An `(*os.File).Read()` call on a blocking mode file will block `(*os.File).Close()`.

On Linux, I guess this can be fixed by adding `syscall.SetNonblock(f.Fd(), true)` at somewhere.
If the file is not opened by `os.OpenFile`, setting non-block won't help.
https://github.com/kr/pty/blob/95d05c1eef33a45bd58676b6ce28d105839b8d0b/pty_freebsd.go#L11

I encountered this before so I opened https://github.com/golang/go/issues/22939.

**Comment by ianlancetaylor** [comment]
@crvv Thanks for the explanation.  I think I see the problem and I will send a CL.

**Comment by tophj-ibm** [comment]
I just tested the cl with commit c7a0e4b6ce and everything fails the same way. I should have mentioned that this test does pass on at least amd64, and I suspected go because we've had issues with syscalls being wrong in the past.

**Comment by ianlancetaylor** [comment]
@tophj-ibm Thanks for trying it.  I think the CL is still a good one, and it comes with a test case that it fixes, but I don't know what is happening here.  Are you able to debug this further?

**Comment by tophj-ibm** [comment]
I'm still looking at it, yes.

**Comment by tophj-ibm** [comment]
just re-tested with both cls cherry-picked into 1.10beta1 and these fix the issue. thanks guys 🎉  

I'm still going to look around because I'm not sure why the file would be blocking just on power and not on anything else, but I think it's safe to close this.
