### ISSUE TITLE
Documentation: type ResponseWriter interface

### ISSUE THREAD

**Issue by SickAustrian** [golang/go#23124]
I have found a small error in the `type ResponseWriter interface` documentation. As part of the `server.go` file the following is stated:
```
// To suppress implicit response headers (such as "Date"), set
// their value to nil.
Header() Header
```
However, `Header` is of type `type Header map[string][]string` which means headers can only be overritten using the empty string "". To avoid any confusion, the documentation should hence be changed accordingly:
```
// To suppress implicit response headers (such as "Date"), set
// their value to "" (empty string).
Header() Header
```

**Comment by bradfitz** [comment]
The docs are correct.

See https://play.golang.org/p/0FhjACxj0C
