### ISSUE TITLE
misc/git/pre-commit: complains about unformatted files that are not staged

### ISSUE THREAD

**Issue by ErinCall** [golang/go#23136]
### What version of Go are you using (`go version`)?

`go version go1.9.2 darwin/amd64`

### What did you do?

```Bash
cd some/project/using/misc/git/pre-commit
$EDITOR some/file.go
# make some changes with *valid* formatting
git add some/file.go
# make some more changes with *invalid* formatting
# (but don't add them)
git commit
```

(In short: have some staged changes with valid formatting and some unstaged changes with invalid formatting)

### What did you expect to see?

Everything's hunky-dunky; the changes I'm committing have valid formatting

### What did you see instead?

`Go files must be formatted with gofmt. Please run: ...`

**Comment by ErinCall** [comment]
I've given up on trying to figure out the preposterous prerequisites for using google's contribution system but ErinCall:precommit-staged-changes-only has a working fix and you can have it if you want

**Comment by odeke-em** [comment]
Hello there @ErinCall, thank you for filing this issue.

Please don't lose hope about contributing, it gets a whole lot better once we get over such humps :)
That precommit hook exists to ensure that we don't have un-gofmt'd files then accidentally submit a patchset, but I understand how frustrating that could be.
Given that you've already `git add`-ed that file, makes the file fair game for precommit scrutiny to help one not lose their changes.

With that said though, I'll ping some git experts for some ideas @rsc @bradfitz @ianlancetaylor.

**Comment by ianlancetaylor** [comment]
The Go project does accept GitHub pull requests now, if you feel like trying again.  Thanks.

**Comment by agnivade** [comment]
I dont think this file is even used anymore. My `.git/hooks/pre-commit` has `exec git-codereview hook-invoke %s "$@"`. Which means this is being handled by the [code-review](https://github.com/golang/review/tree/master/git-codereview) tool.

And it looks like this behavior is controlled by a flag which needs to be set for it to check unstaged changes also. https://github.com/golang/review/blob/master/git-codereview/gofmt.go#L53. If that is satisfactory behavior, I think this file can be deleted and the issue closed.

**Comment by agnivade** [comment]
This is done with https://github.com/golang/go/commit/0c7cdb49d89b34baf1f407135b64fd38876823e2. Closing.
