### ISSUE TITLE
x/perf/cmd/benchstat: documentation missing information about -alpha option

### ISSUE THREAD

**Issue by laboger** [golang/go#23138]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10beta1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le Ubuntu

### What did you do?
Tried to use benchstat for comparing benchmark results. Thought something was wrong on ppc64le because the delta column was always ~ even though I could see significant differences in the results columns.

Tried to use benchstat -h and found -alpha which I assumed is that I needed:
```
 -alpha a
    	consider change significant if p < a (default 0.001)
```
From this it was not clear what p is, so I went here:

https://godoc.org/golang.org/x/perf/cmd/benchstat
but this documentation doesn't even mention alpha.

So after trial and error I found an alpha value that would give me what I want.

**Comment by ALTree** [comment]
dup of  #20727

**Comment by mvdan** [comment]
Sure seems like it.
