### ISSUE TITLE
time: Parse does not parse format "1504059999"

### ISSUE THREAD

**Issue by tehsphinx** [golang/go#23134]
### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
go 1.9.2 is currently the latest release

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
I try to parse a time format without any punctuation. Date is not of importance here.
```
time.Parse("1504059999", "0244541440")
```

https://play.golang.org/p/-YxQX44J8F

### What did you expect to see?
```
0000-01-01 02:44:54.144 +0000 UTC
```

### What did you see instead?
```
parsing time "0244541440" as "1504059999": cannot parse "1440" as "9999"
```

**Comment by mvdan** [comment]
I could not find a good reason in your code nor in the `time` package godoc, so I digged into the code a bit.

In particular, after some debugging, I came to this comment:

    case '.': // .000 or .999 - repeated digits for fractional seconds.

In other words, any number of `9` digits to signal fractional seconds are only valid format if they follow a period.

Without knowing too much about how the `time` package works or what's the design behind these layouts, it seems to me like this restriction could be avoided. I'll play with it for a bit to see what I get. Would like some input from @rsc as per golang.org/s/owners.

**Comment by mvdan** [comment]
To clarify - `000` cannot be used in place of `.000` easily, as it introduces certain ambiguity with others like `01` or `02`. However, `999` doesn't seem to have that problem.

**Comment by ianlancetaylor** [comment]
Since you know the exact layout, it's easy enough to modify the input string to have the dot that the format requires.  I'm not sure this is worth changing.

**Comment by tehsphinx** [comment]
I'm already working around it by modifying the input string and adding a `.`.

I was just wondering that there is a `.` required and could not find or think of any good reason for it. Modifying the string gives me additional points of failure, e.g. if the string is not the format or length I was expecting.

Of course I can give it a try if you'd like a PR. Never done that for the go standard library though.

**Comment by mvdan** [comment]
I would say we first need to decide if we want this change or not. That is, to allow `9999` as well as `.9999`. The change itself isn't complicated - I have a working version stashed on my laptop.

**Comment by rsc** [comment]
A decimal point followed by one or more zeros represents a fractional
    second, printed to the given number of decimal places. A decimal point
    followed by one or more nines represents a fractional second, printed to the
    given number of decimal places, with trailing zeros removed. When parsing
    (only), the input may contain a fractional second field immediately after
    the seconds field, even if the layout does not signify its presence. In that
    case a decimal point followed by a maximal series of digits is parsed as a
    fractional second.

There is no decimal point here. This is probably working best as is.

**Comment by tehsphinx** [comment]
Just to throw in another argument:
The German language for example would not use a `.` but a `,` for separating fractional seconds. That case is also not covered by the current implementation.
