### ISSUE TITLE
x/build/maintner: Unknown fields in event

### ISSUE THREAD

**Issue by kevinburke** [golang/go#23151]
Code in question is here in github.go:

```go
		otherJSON, _ := json.Marshal(em)
		e.OtherJSON = string(otherJSON)
		if e.OtherJSON == "{}" {
			e.OtherJSON = ""
		}
		if e.OtherJSON != "" {
			log.Fatalf("Unknown fields in event: %s", e.OtherJSON)
		}
		evts = append(evts, e)
```

The unknown fields are "requested_reviewer" and "review_requester". 

I may take a crack at this as I have more free time now. Probably the way to trigger this is to create a Github pull request and assign someone to review it, maybe on the gddo repository.

**Comment by kevinburke** [comment]
cc @adams-sarah @andybons @bradfitz

**Comment by kevinburke** [comment]
More:

```
{
    "dismissed_review": {
        "dismissal_commit_id": null,
        "dismissal_message": "should add this to dev and prod",
        "review_id": 68794584,
        "state": 40
    }
}
```

**Comment by adams-sarah** [comment]
Hey @kevinburke, I'm not working w/ the Go team anymore, so not maintaining builders.
Please only ping me on these if you think I've got answers that nobody else does. I'm happy to share any knowledge I might have in this case :)
But in general, I'm hoping to keep away from the project for a while.
Thanks!

**Comment by bradfitz** [comment]
What is this impacting?

I don't see anything crashing in production.

How did you find this?

**Comment by kevinburke** [comment]
I found it while trying to locally cache several Github repositories for a company I have been working with. Unfortunately the repositories are private. I believe you can reproduce the issue by attempting to sync a Github repository that has a pull request with an assigned reviewer.

**Comment by kevinburke** [comment]
I believe I could trigger it by creating a pull request on e.g. github.com/golang/gddo and assigning it to someone, but I would rather not do this until we know it won't crash production.

**Comment by kevinburke** [comment]
Exact command was:

```
maintnerd --sync-and-quit --watch-github=OwnerName/RepoName,OwnerName/RepoName2
```

**Comment by bradfitz** [comment]
Gotcha.
