### ISSUE TITLE
playground: parse error when formatting a type alias

### ISSUE THREAD

**Issue by alandonovan** [golang/go#23169]
The Go playground can compile a program that uses a type alias, but cannot format it.
For example: https://play.golang.org/p/ZNNB8i24zR
Run prints: 42
Format prints: prog.go:4:9: expected type, found '=' (and 1 more errors)

**Comment by bradfitz** [comment]
@broady, can you show @andybons how to fix this?

**Comment by ALTree** [comment]
This is #21645

**Comment by bradfitz** [comment]
Thanks, closing this as a dup and metadata-ified that one.
