### ISSUE TITLE
cmd/go: go get fail with error "invalid abbreviation code" on mac

### ISSUE THREAD

**Issue by gaoxiangxyz** [golang/go#23176]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2 and 1.10beta1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
OSX 10.10.2 amd64

### What did you do?
do `go get -u github.com/derekparker/delve/cmd/dlv` on mac

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
install delve succeessful

### What did you see instead?
```
gaoxiangzydeMacBook-Pro gaoxiangzy$ go get -u github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/cmd/dlv
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
error: invalid abbreviation code [110] for DIE at 0x000003e7 in '/var/folders/3_/j6bfy2lj59z8p4rv6zpln2zr0000gn/T/go-link-286932600/go.o'
Assertion failed: (ref_addr_die != NULL), function AppendDependants, file /SourceCache/dwarf_utilities/dwarf_utilities-121.1/source/DWARFDebugInfoEntry.cpp, line 375.
```

**Comment by ALTree** [comment]
This looks like a dup of #23046, which was fixed by [CL 83675](https://go-review.googlesource.com/c/go/+/83675). The fix will be included in the next go1.10 beta, but in the meantime you could try with tip and see if the issue is fixed.

**Comment by ALTree** [comment]
cc @thanm @ianlancetaylor

**Comment by thanm** [comment]
Yes, this is the same problem. You're getting an error message instead of a crash, but it is definitely the same underlying issue.

**Comment by thanm** [comment]
Duplicate of #23046

**Comment by ianlancetaylor** [comment]
I'm tempted to close this as a dup but I'm confused by the report that this problem happens with 1.9.2.

**Comment by aarzilli** [comment]
IMHO this isn't a duplicate, IMHO this is something else and
* either it's specific to macOS 10.10 and it hasn't been fixed
* or it has been fixed by some of the other dsymutil-related fixes that happened in this cycle but @gaoxiangxyz thinks it hasn't been fixed because of the other bug that @thanm fixed since the beta

I don't have 10.10 so I can't investigate this (if it happened in 10.11 I'd see it as a travis failure for delve, but I don't).

**Comment by thanm** [comment]
Hmm, perhaps I was a bit hasty. @gaoxiangxyz , are you sure that both 1.9.2. and 1.10 beta are hitting the same error message?

**Comment by thanm** [comment]
See also similar [bug](https://github.com/mattn/go-oci8/issues/183) from back in October. For this the submitter was able to fix the issue by upgrading Xcode. @gaoxiangxyz , what do you see when you run "xcodebuild -version"?

**Comment by gaoxiangxyz** [comment]
@thanm 

Xcode 6.4
Build version 6E35b

Yes, I sure, and I tried 1.9, it has same issue, but 1.8 and 1.8.5 work fine.

**Comment by gaoxiangxyz** [comment]
I'm not sure whether it is a dup of #23046, it seems they have different error message.
I tried `go install` and it has same error, it can be fixed by with flag `-ldflags "-s"`.

**Comment by aarzilli** [comment]
You should try updating to Xcode 7.2.

**Comment by gaoxiangxyz** [comment]
@aarzilli OK, I will have a try later

**Comment by thanm** [comment]
@gaoxiangxyz any update on this? Is the issue there for Xcode 7.2?

**Comment by gaoxiangxyz** [comment]
@thanm sorry, I have not try it because I get some trouble to update Xcode, so I use go 1.8 now and it works

**Comment by thanm** [comment]
OK, thanks. I will close the issue; please re-open if needed.
