### ISSUE TITLE
mime/multipart: diagnose missing boundary string

### ISSUE THREAD

**Issue by flimzy** [golang/go#23170]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux amd64

### What did you do?

Instantiating a [multipart.Reader](https://golang.org/pkg/mime/multipart/#Reader) with an empty boundary, as might happen in the case of an invalid Content-Type header, such as the following:

    Content-Type: multipart/related

does not result in an error. My reading of [RFC 2046](https://www.ietf.org/rfc/rfc2046.txt) suggests that the boundary must be at least one character:

>    The only mandatory global parameter for the "multipart" media type is
   the boundary parameter, which consists of 1 to 70 characters from a
   set of characters known to be very robust through mail gateways, and
   NOT ending with white space.

### What did you expect to see?

I would have expected an error on the first call to `NextPart()`, as the reader was instantiated with invalid sate.

### What did you see instead?

No error.

Perhaps this isn't the right place to do such a check.  Of note, there is also no check that the `boundary` conforms to any of the other constraints defined in RFC 2046. In particular, non-ASCII data is not guarded against, nor are boundaries greater than 70 characters in length.

**Comment by rsc** [comment]
Seems fine to return an error on bad input.

**Comment by iWdGo** [comment]
NewReader cannot return an error. It could eventually return nil when boundary is empty but no reason would be given. The proposed fix returns a relevant error on the first call of NextPart.
