### ISSUE TITLE
cmd/go: go test -c does not apply specified gcflags to all packages

### ISSUE THREAD

**Issue by aarzilli** [golang/go#23180]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version devel +3aeb395 Mon Dec 18 20:24:12 2017 +0000 linux/amd64
```

### What did you do?

This is very similar to https://github.com/golang/go/issues/22831, that problem was fixed however if I run `go test -gcflags='all=-N -l'` with https://github.com/aarzilli/testflags I expect to see all the compile units in the resulting binary have the flags -N and -l applied to them, but one is spared:

```
 <0><8fc96>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <8fc97>   DW_AT_name        : github.com/aarzilli/testflags
    <8fcb5>   DW_AT_language    : 22    (Go)
    <8fcb6>   DW_AT_stmt_list   : 0x16b8d
    <8fcba>   DW_AT_low_pc      : 0x531650
    <8fcc2>   DW_AT_ranges      : 0x530
    <8fcc6>   DW_AT_comp_dir    : .
    <8fcc8>   DW_AT_producer    : Go cmd/compile devel +3aeb395 Mon Dec 18 20:24:12 2017 +0000
```

also all functions in that compile unit are assigned to the package `github.com/aarzilli/testflags` when really they were defined in `main`.

**Comment by aarzilli** [comment]
I looked a bit into this, it turns out that the flags are actually applied to all packages, the reason they are not reported in debug_info is because the compiler for testflags is called with `-p main` which means the producer symbol is called `go.cuinfo.producer.main`, but then the linker imports it as `github.com/aarzilli/testflags` which means the linker will look for `go.cuinfo.producer.github.com/aarzilli/testflags`.

This part:

> all functions in that compile unit are assigned to the package github.com/aarzilli/testflags when really they were defined in main.

isn't new to 1.10, 1.9 also did this.

**Comment by rsc** [comment]
Thanks for chasing this down. CL sent to fix the -p option in this case.
