### ISSUE TITLE
spec: clarification of method sets for non-interface types

### ISSUE THREAD

**Issue by griesemer** [golang/go#23186]
Per @alandonovan: `The spec for method sets says "The method set of any other [non-interface] type T consists of all methods declared with receiver type T" but forgets to exclude blank methods.  We should fix that.`

(We explicitly exclude blank methods from interface method sets.)

**Comment by jimmyfrasche** [comment]
@griesemer could you clarify "blank method"? Is that when the method name is `_`?

**Comment by alandonovan** [comment]
Yes, blank means named "_".

**Comment by griesemer** [comment]
The spec says in https://golang.org/ref/spec#Method_sets that `In a method set, each method must have a unique non-blank method name.` so we have a clear statement excluding blank names from these method sets. Furthermore, in the same section, the spec talks about methods being `declared` with a certain receive type, etc. But objects (package, consts, types, vars, funcs, etc.) with a blank name are never declared (see also https://golang.org/ref/spec#Declarations_and_scope ).

We could make this section more explicit and talk about `non-blank methods`, but it gets a bit cumbersome and overly legalistic. What we have right now is accurate, and the corner-case (blank methods) is covered as well. It doesn't need to be front and center.

Closing this.

**Comment by jimmyfrasche** [comment]
@griesemer you said you were going to close this issue but did not

**Comment by griesemer** [comment]
@jimmyfrasche Thanks for catching this. Closing now.
