### ISSUE TITLE
net: TestInterfaceHardwareAddrWithWmic fail on non-english Windows

### ISSUE THREAD

**Issue by mattn** [golang/go#23191]
### What version of Go are you using (`go version`)?

```
go version devel +3aeb3950a9 Mon Dec 18 20:24:12 2017 +0000 windows/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mattn\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:/dev/go
set GORACE=
set GOROOT=C:\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=...gg
```

### What did you do?

```
go test -run TestInterfaceHardwareAddrWithWmic on src/net.
```

### What did you expect to see?

pass ok

### What did you see instead?

not ok

This issue is related on https://github.com/golang/go/issues/23153. This test fail to match name of interface since wmic command output DBCS (double byte character set) when redirect to pipe. But wmic command output utf-16 when redirect to file. So the test should fix to get output from file.

**Comment by alexbrainman** [comment]
> not ok

Thank you for creating the issue. Please provide the output of the error message. Maybe provide a screen shot?

I will let @johnsonj decide what to about his CL 84696 before we deal with this issue.

Alex

**Comment by ianlancetaylor** [comment]
I believe this is fixed, in that the test no longer fails because it is no longer run.
