### ISSUE TITLE
cmd/go: "go test" command leaves go-build directory in current directory on Windows XP

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#23190]
### What version of Go are you using (`go version`)?

go version devel +9d5f8ea Fri Dec 15 02:48:35 2017 +0000 windows/386

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

I use Windows XP

```
set GOARCH=386
set GOBIN=
set GOCACHE=go-build
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Documents and Settings\aa\dev\
set GORACE=
set GOROOT=C:\Documents and Settings\aa\dev\go
set GOTMPDIR=
set GOTOOLDIR=C:\Documents and Settings\aa\dev\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\DOCUME~1\aa\LOCALS~1\Temp\go-build509878090=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

I run a test like that:
```
C:\Documents and Settings\aa\dev\go\src\os>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

C:\Documents and Settings\aa\dev\go\src\os>go test -short
PASS
ok      os      1.202s

C:\Documents and Settings\aa\dev\go\src\os>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        go-build/

nothing added to commit but untracked files present (use "git add" to track)

C:\Documents and Settings\aa\dev\go\src\os>
```

### What did you expect to see?

I did not expect to see go-build directory.

### What did you see instead?

I did see go-build directory.

Alex

**Comment by bradfitz** [comment]
Test cleanups are fine for Go 1.10 if you want to fix this.

**Comment by alexbrainman** [comment]
I am not sure this is a test clean-up. It creates go-build directory in any package directory. I suspect this has something to do with go command itself. But I didn't look properly.

**Comment by alexbrainman** [comment]
This is not happening anymore, because CL 85996 disabled caching on Windows XP altogether. Windows XP has different environment variable from `%LocalAppData%` - it is called `%APPDATA%`. So we can enable cache on Windows XP, if we want, but I am happy to leave it as is too.

I will let Ian or Brad decide what to do here.

Thank you.

Alex

**Comment by bradfitz** [comment]
Disabling build caching on XP was an accident and should probably be fixed.

**Comment by bradfitz** [comment]
Sent https://go-review.googlesource.com/#/c/go/+/87675
