### ISSUE TITLE
playground: inconsistent formatting of errors depending on whether gofmt, goimports, go build is being used

### ISSUE THREAD

**Issue by shurcooL** [golang/go#23201]
### What did you do?

Visit https://play.golang.org/p/kpQt2DJxEEp.

1. Keep "Imports" checkbox unchecked, press the Format button.
2. Check the "Imports" checkbox, try pressing the Format button again.
3. Press the Run button.

### What did you expect to see?

Consistent formatting of errors, and coloring the gutter of the problematic line in red in all 3 cases.

### What did you see instead?

1.	With gofmt:

	```
	3:1: expected declaration, found 'IDENT' problem
	```
	
	And line 3 gutter is not red:
	
	![image](https://user-images.githubusercontent.com/1924134/34234030-a51487b6-e5b6-11e7-8bb5-ce758855b871.png)

2.	With goimports:

	```
	prog.go:3:1: expected declaration, found 'IDENT' problem
	```
	
	Line 3 gutter is red, which helps spot where the issue is (more so in a larger file):
	
	![image](https://user-images.githubusercontent.com/1924134/34234053-d04cfd82-e5b6-11e7-857f-b3bf2419adf5.png)

3.	After pressing Run button:

	```
	tmp/sandbox892599086/main.go:3:1: syntax error: non-declaration statement outside function body
	```
	
	And line 3 gutter is not red:

	![image](https://user-images.githubusercontent.com/1924134/34234030-a51487b6-e5b6-11e7-8bb5-ce758855b871.png)

Notice how the filename is not consistent, and the red gutter only works in the goimports situation (but it's likely trivial to make it work in all 3 cases).

With gofmt, there's no filename at all. With goimports, it's "prog.go". But with `go build`, it's "main.go" and includes "tmp/sandbox892599086" prefix. (I would imagine ideal solution is using "main.go" as the filename in all 3 cases.)

**Comment by bradfitz** [comment]
All yours, @andybons.

**Comment by ysmolsky** [comment]
I have a CL prepared, but will submit it after playground tests.
