### ISSUE TITLE
plugin: Problem when using net/http with plugins

### ISSUE THREAD

**Issue by cosban** [golang/go#23205]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build540466892=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
### What did you do?

I'm attempting to use the plugin system (on linux) with the net/http package in both the plugin as well as the program that attempts to use the plugin.

See [http-plugin](https://github.com/cosban/http-plugin) for more details

### What did you expect to see?
The program should start and immediately exit gracefully

### What did you see instead?

```
panic: interface conversion: http.http2StreamError is not http.http2writeFramer: missing method writeFrame

goroutine 1 [running]:
plugin.lastmoduleinit(0x2184420, 0xc42000e038, 0x2185430, 0x12, 0xb940e0)
        /usr/local/go/src/runtime/plugin.go:60 +0x438
plugin.open(0x7f83b1, 0x11, 0x0, 0x0, 0x0)
        /usr/local/go/src/plugin/plugin_dlopen.go:113 +0x23a
plugin.Open(0x7f83b1, 0x11, 0xc420060750, 0x0, 0x0)
        /usr/local/go/src/plugin/plugin.go:31 +0x35
main.main()
        /go/src/github.com/cosban/http-plugin/src/host/host.go:10 +0x3a
```

**Comment by cosban** [comment]
From README of the [repository](https://github.com/cosban/http-plugin) I have linked in the description of the issue: 

> In order for this issue to be replicated, the dummy method (found in src/host/host.go) must be present. This leads me to believe that if the net/http package is used within the "host" AND "plugin", the issue will occur.

**Comment by bradfitz** [comment]
Please try the Go 1.10 beta or git master.

**Comment by cosban** [comment]
The issue does not appear to exist in the beta under these circumstances.

**Comment by bradfitz** [comment]
Thanks, we'll close this then. A bunch of plugin work seemed to happen during Go 1.10.
