### ISSUE TITLE
spec: informally explain what a terminating statement is

### ISSUE THREAD

**Issue by dakeshi** [golang/go#23215]
There's no definition about a terminating statement. Needs to be expanded. I find out some candidate in [Go 1.1 release note](https://golang.org/doc/go1.1#return)

> It introduces the concept of a terminating statement, a statement that is guaranteed to be the last one a function executes

**Comment by bradfitz** [comment]
The release notes you linked to themselves link to the answer: https://golang.org/ref/spec#Terminating_statements

It's already in there.

**Comment by dakeshi** [comment]
I already know there is a terminating statements section. What I want to say is I can not find out the meaning of a terminating statement. Currently, there are only the kinds of terminating statements and their requirements. But I'm having trouble to find out what they really do? 

> it is guaranteed to be the last one a function executes

That's what I want to know.

**Comment by bradfitz** [comment]
I'm not sure how to say this any other way: the information you want in the spec already exists in the spec. It's right here:

https://golang.org/ref/spec#Terminating_statements

I'll include a screenshot too:

<img width="847" alt="screen shot 2017-12-21 at 7 51 32 am" src="https://user-images.githubusercontent.com/2621/34263304-d09eca1e-e623-11e7-8f61-cc9a2945ef87.png">

**Comment by ianlancetaylor** [comment]
@bradfitz I think @dakeshi would like the spec to literally say something like "A terminating statement is a statement that prevents the execution any immediately following statement."  The current spec defines terminating statements precisely but never defines them colloquially.

CC @griesemer

**Comment by griesemer** [comment]
I'm not opposed to having a one sentence informal explanation to start this section, along the lines of what @ianlancetaylor mentioned. I think it's useful for many people reading the spec as it gives them an intuitive understanding for "terminating statement".

After all, it's that intuitive understanding which guided the formal specification. I'll give it a shot.
