### ISSUE TITLE
cmd/internal/obj/arm: wrong binary code generated for NMULA/NMULS

### ISSUE THREAD

**Issue by benshi001** [golang/go#23212]
In my previous commit https://github.com/golang/go/commit/074547a5ce60c70f450e5e624c9f5d8f9a3e1295

The NMULAF/NMULSF/NMULAD/NMULSD encoding are wrong. This is due to I was reading an old ARMv7 reference manual.

	"NMULAF		F5, F6, F7" should be encoding to 457a16ee, but currently 057a16ee
	"NMULAD		F5, F6, F7" should be encoding to 457b16ee, but currently 057b16ee
	"NMULSF		F5, F6, F7" should be encoding to 057a16ee, but currently 457a16ee
	"NMULSD		F5, F6, F7" should be encoding to 057b16ee, but currently 457b16ee

NMULA/NMULS are reversed due to a typo in older manual.

I have double checked with newer manual and gnu tool chain.

	ee167a45 	vnmla.f32		s14, s12, s10
	ee167b45 	vnmla.f64		d7, d6, d5
	ee167a05 	vnmls.f32		s14, s12, s10
	ee167b05 	vnmls.f64		d7, d6, d5

**Comment by ALTree** [comment]
Tentatively targeting to 1.10 since it fixes an issue that was introduced in the 1.10 cycle.
