### ISSUE TITLE
math: wrong result for Pow(±0, .5) contrary to documentation

### ISSUE THREAD

**Issue by majnemer** [golang/go#23224]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?

I believe go1.9.2 is the latest release.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/majnemer/go"
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build846653371=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

I ran the following program: https://play.golang.org/p/_lUAaRG9D-P

### What did you expect to see?

The [documentation for math.Pow](https://golang.org/pkg/math/#Pow) says the following:

> Pow(±0, y) = +0 for finite y > 0 and not an odd integer

.5 is finite and not an odd integer which means math.Pow should give back +0.

### What did you see instead?

math.Pow gave back -0.

**Comment by PeterWathall** [comment]
I think I've found the problem. In the Pow function because y is 0.5 it triggers a special case and returns Sqrt(x). The Sqrt function has a switch statement comparing x to 0 and because -0 equals 0 in this evaluation the Sqrt function just returns x which is -0.

So the final result is -0 because the functions are just passing back x.

**Comment by odeke-em** [comment]
Thank you for reporting this issue @majnemer, I'll loop in @griesemer.

**Comment by majnemer** [comment]
There is another, related bug.
Consider: Pow(-Inf, 0.5) == Pow(-0, -0.5) == Pow(±0, y) = +Inf

However, Go gives me back NaN.

I believe the original bug and the one I have just noted if we change the [line](https://github.com/golang/go/blob/12465661421f3598cb76a787fba75da8cabc220d/src/math/pow.go#L47):
```
return Sqrt(x)
```
into something along the lines of the following:
```
if IsInf(x, -1) {
  return Inf(1)
}
return Abs(Sqrt(x))
```
