### ISSUE TITLE
runtime: windows DLL mappings interfere with 32-bit memory allocation

### ISSUE THREAD

**Issue by gopherbot** [golang/go#2323]
by **zippoxer**:

<pre>Before filing a bug, please check whether it has been fixed since
the latest release: run &quot;hg pull&quot;, &quot;hg update default&quot;, rebuild, and
retry
what you did to
reproduce the problem.  Thanks.

What steps will reproduce the problem?
1. Installing gomingw installer for build of release r60.1
2. Executing make, then make install in the (attached to this issue) package's directory.
3. Testing the installed package by calling Now().

What is the expected output?
The x position of the cursor.

What do you see instead?
An error:
&gt;&gt; throw: runtime: cannot reserve arena virtual address space

Which compiler are you using (5g, 6g, 8g, gccgo)?
8g

Which operating system are you using?
Windows 7

Which revision are you using?  (hg identify)
I ran &quot;Installer for Win32 (experimental) build of release.r60.1&quot;
(hd identify doesn't cooperate, sorry)

Please provide any additional information below.</pre>

Attachments:
1. <a href="https://storage.googleapis.com/go-attachment/2323/0/somecgopackage.go">somecgopackage.go</a> (188 bytes)
2. <a href="https://storage.googleapis.com/go-attachment/2323/0/Makefile">Makefile</a> (122 bytes)

**Comment by mattn** [comment]
I tried this. not reproduced. prefer closing.

**Comment by rsc** [comment]
Closing per @mattn.
