### ISSUE TITLE
database/sql: Support SQL placeholder parameters inside array literals

### ISSUE THREAD

**Issue by myartsev** [golang/go#23238]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myartsev/go"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build978363477=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
```
v := 1
_, err := db.Exec("SELECT * FROM foo WHERE an_array @> '{$1}';", v)
```
  
  
### What did you expect to see?
Query successfully executes without an arror

### What did you see instead?
_pq: invalid input syntax for integer: "$1"_
  
  
**When inside an array literal, SQL placeholder parameters do not get evaluated and are passed as-is to the query.**  
I end up wrapping the query with fmt to make it work.

```
v := 1
_, err := db.Exec(fmt.Sprintf("SELECT * FROM foo WHERE an_array @> '{%d}';", v))
```

**Comment by dominikh** [comment]
Go does not look at the contents of the query. The query is passed to a driver, which itself usually just passes it to the database server. What you're seeing is a limitation by PostgreSQL.

Closing as not a Go issue.
