### ISSUE TITLE
I create more than CPU logical core number goroutine,and the demo is bomb

### ISSUE THREAD

**Issue by MrXionGe** [golang/go#23235]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
En……I do not know if there is any problem with the previous version

### What operating system and processor architecture are you using (`go env`)?
Windos10 amd64

### What did you do?
Well,I make a Bubble Sort Demo to test my CPU performance.
You can see the code inside the link,at line 24 and 27.
My Cpu Num are 4.
So,if I create 4 or over 4 "doBenchmar()" at line 24.This demo will always sleep at line 27(debug will bomb at line 27 too).If I add a print after line 27,it will not output.
If I create 3 or 2 "doBenchmar()" , There is not any problem.(Less than CPU logical core number)

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/aFtkiUOexgz

### What did you expect to see?
I want to know where is the problem.
The best result is a problem with my code.

### What did you see instead?
Oh,I saw my demo is bomb

**Comment by davecheney** [comment]
I’m sorry but this bug report is not valid as it contains a data race. Please consult the following links for more information. 

- https://golang.org/doc/articles/race_detector.html
- https://blog.golang.org/race-detector

 Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
