### ISSUE TITLE
gomobile install on mac OS Sierra 10.12

### ISSUE THREAD

**Issue by michaelmenon** [golang/go#23236]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.1
### What operating system and processor architecture are you using (`go env`)?

macOS Sierra 10.12
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

 I am trying to install gomobile on mac OS Sierra 10.12. I have go version 1.7.1 installed.

After doing the steps given below :

1) go get golang.org/x/mobile/cmd/gomobile

2) gomobile init

I get the following errors
gomobile init
gomobile: go install -pkgdir=/usr/local/mobgo/pkg/gomobile/pkg_darwin_arm std failed: exit status 2
# internal/poll
../go/src/internal/poll/fd_mutex.go:194:6: missing function body
../go/src/internal/poll/fd_mutex.go:195:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:17:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:19:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:20:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:21:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:22:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:23:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:24:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:25:6: missing function body
../go/src/internal/poll/fd_poll_runtime.go:25:6: too many errors

**Comment by AlexRouSg** [comment]
https://github.com/golang/go/wiki/Mobile
You need at least 1.7.4 for Sierra, update your go version.

**Comment by michaelmenon** [comment]
Thanks  very much, i fixed it by upgrading my go to go1.9.2
