### ISSUE TITLE
tools/present: Documentation link to sam documentation is dead

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/go#23247]
The documentation for the [`tools/present` tool](https://godoc.org/golang.org/x/tools/present) includes a link to http://plan9.bell-labs.com/sys/doc/sam/sam.html, which according to me and according to http://downforeveryoneorjustme.com/plan9.bell-labs.com cannot be reached.

This means it's hard to find out how the `.code` _address syntax_ works.

**Comment by dgryski** [comment]
Current location https://plan9.io/sys/doc/sam/sam.html

**Comment by johanbrandhorst** [comment]
I'll take a stab at fixing this.
