### ISSUE TITLE
reflect: add Type.PtrTo to convert T to *T instead of PtrTo

### ISSUE THREAD

**Issue by vipally** [golang/go#23240]
[reflect.Value](https://golang.org/pkg/reflect/#Value) has method [Addr](https://golang.org/pkg/reflect/#Value.Addr) to convert V to &V, and [Elem](https://golang.org/pkg/reflect/#Value.Elem) to convert &V to V
but [reflect.Type](https://golang.org/pkg/reflect/#Type) has Elem to convert *T to T only, we have to use [reflect.PtrTo](https://golang.org/pkg/reflect/#PtrTo) to achive the other work.
To corresponding with Value, Type should have a PtrTo method to convert T to *T.

**Comment by as** [comment]
There is no method because that would require every Type to implement that method to satisfy the Type interface. Instead, the package provides this functionality for all types that satisfy the interface automatically without any concrete types having to implement that method themselves.

**Comment by vipally** [comment]
A library shouldn't consider only about how to implements, but more about how to use it.
It's not too costly to call reflect.PtrTo on every type I guess, if it brings more convenience.
#### 1.   Compare with follw ways of converting T to ***T, the first way reads/writes clearer.
```
t.PtrTo().PtrTo().PtrTo()
reflect.PtrTo(reflect.PtrTo(reflect.PtrTo(t)))
```
#### 2.   If somelib.DeepType returns the deep type T for any pointer. Only the first way can get *T without depends on reflect.
```
somelib.DeepType(p).PtrTo()
reflect.PtrTo(somelib.DeepType(p))
```

**Comment by as** [comment]
>A library shouldn't consider only about how to implements, but more about how to use it. It's not too costly to call reflect.PtrTo on every type I guess, if it brings more convenience.

The importer of a go package has enough control of the namespace to make that fix trivial. 

```
var up = reflect.PtrTo // a sign of too much reflecting
up(up(up(t)))
```

>2. If somelib.DeepType returns the deep type T for any pointer. Only the first way can get *T without depends on reflect.

That's not an issue for most APIs from what I've seen. Baking a reflect.Type into an API is not a common practice (and probably for good reason). 



I don't think the API asymmetry was an accident. A reflect.Value represents something that exists at runtime. It makes sense for that to have a method because it has its own identity somewhere in memory. A reflect.Type is more of an abstract that represents the idea of a type rather than a living object, for it to have that method in its method set might confuse people to think that it has value semantics. That's just my take on it from what I've seen with first time users of reflect.

**Comment by vipally** [comment]
> var up = reflect.PtrTo // a sign of too much reflecting
> up(up(up(t)))

It's still not easy to read/write, isn't it?
`t.PtrTo().PtrTo().PtrTo()`

In fact, [reflect.PtrTo](https://github.com/golang/go/blob/master/src/reflect/type.go#L1420) is really implements on THE ONLY instance of Type([rtype.ptrTo](https://github.com/golang/go/blob/master/src/reflect/type.go#L1424))
That is to say, export method Type.PtrTo is just export an existing method rtype.ptrTo, there's nothing to do with "implements for every type".
```
func (t *rtype)PtrTo() Type {
	return t.ptrTo()
}
```
The main point of this issue is, how do we intend to use a Type as.

**Comment by ianlancetaylor** [comment]
`reflect.PtrTo` is a function because in some cases it creates a type that only exists at run time.  All the functions that do that are functions, not methods.  If `PtrTo` is a method, why not `SliceOf` and `ArrayOf` and `ChanOf`?

We aren't going to change this.  Closing.
