### ISSUE TITLE
playground: server errors when trying to share programs over 1500 bytes

### ISSUE THREAD

**Issue by ccdavis94303** [golang/go#23253]
### What operating system and processor architecture are you using (`go env`)?
Browser is Firefox Quantum 57.0.2 (64-bit)
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\me\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
This code  runs in Playground but does not save/share 
```
package main
import (
	"fmt"
	"strconv"
	//"math"
)
type matrix struct {
	value  [][]float64
	name string
}
func newMatrix(d1,d2 int) matrix {
	var n matrix
	n.name = strconv.Itoa(d1) + "X" + strconv.Itoa(d2)
	for i:= 0; i<d1 ; i++ {
		n.value = append(n.value, make([]float64, d2))
	}
	return n
}
func mmultiply(a,b matrix) matrix {
	di := len(a.value)
	dchk := len(a.value[0])
	dj := len(b.value[0])
	dk := len(b.value)
	if dchk!= dk {
		fmt.Println("Dimension mismatch")
	}
	c := newMatrix(di,dj)
	for i := 0; i<di ; i++ {
		for j := 0; j<dj ; j++ {
			for k := 0; k<dk ; k++ {
				c.value[i][j] += a.value[i][k] * b.value[k][j]
			}
		}
	}
	return c
}
func identity(d int) matrix {
	c := newMatrix(d,d)
	c.name = "identity"
	for i:= 0; i<d; i++ {
		for j := 0; j<d; j++ {
			if i == j {
				c.value[i][j] = 1.0
			}else {
				c.value[i][j] = 0.0
			}
		}
	}
	return c
}
func rot( d, v int) matrix {
	dimension := d
	change := newMatrix( dimension, dimension)
	change.name = "Rotation"
	for i:= 0; i < dimension; i++ {
		for j := 0; j< dimension; j++ {
			trigger := (dimension - (v%dimension) + i)%dimension
			//fmt.Println(i, j, trigger)
			if  j == trigger {
				change.value[i][j] = 1.0
			} else{
				change.value[i][j] = 0.0
			}
		}
	}
	return change
}
func main() {
	fmt.Println("AB(ij) =A(ik)B(kj), etc.")
	dimension := 11
	velocity  := -14				// right hard rule v>0 rotate right
	source := newMatrix(dimension , 1)			// vector == nX1 matrix
	source .name = "vector"
	for i:= 0; i<len(source.value); i++ {
		source .value[i][0] = float64(i)
	}
	change := rot( dimension, velocity )
	destination := mmultiply(change, source )
	destination .name = "destination"
	for i := 0; i< dimension ; i++ {
		fmt.Println(destination.value[i],"\t", change.value[i], source.value[i])
	}
	fmt.Println("\nRotates, in ", dimension," dimensions with velocity ", velocity,
		" bits per tick, or mod the dimension ", velocity%dimension)
}
```

I have a number of other files that fail too of approximately the same length or greater. All run but do not save/share.

### What did you expect to see?
a url link for a share

### What did you see instead?
a grey transparent overlay with a message box "Server error; try again." and an "ok" close button

**Comment by minaevmike** [comment]
hm, seems there is a limit in playground https://github.com/golang/playground/blob/master/share.go#L63 but it's 64KB not 1.5

**Comment by andybons** [comment]
Cloud Datastore is treating the Body byte slice as if it were indexed:

`putting Snippet: datastore: []byte property too long to index for a Property with Name "Body"`

Which limits it to 1500 bytes. However, []byte slices are automatically treated as unindexed according to https://cloud.google.com/appengine/docs/standard/go/datastore/indexes

From looking at our dashboard, we appear to have some string representations of the `Body` field in datastore (with indicated index sizes but no indexes showing up in the indexes tab). This is likely because we used a string type earlier in the code. Will investigate further.

**Comment by ccdavis94303** [comment]
Does this mean I will be able to save again sometime in the future?

**Comment by andybons** [comment]
@ccdavis94303 yes it does. It requires a deploy. I will update this bug when you can do so.

**Comment by ccdavis94303** [comment]
I am most grateful. Ty to all for the help.
 

    On Wednesday, December 27, 2017, 3:26:37 PM EST, Andrew Bonventre <notifications@github.com> wrote:  
 
 
@ccdavis94303 yes it does. It requires a deploy. I will update this bug when you can do so.

**Comment by andybons** [comment]
@ccdavis94303 this fix is now live.

**Comment by ccdavis94303** [comment]
awesome tyvm
 

    On Wednesday, December 27, 2017, 7:44:46 PM EST, Andrew Bonventre <notifications@github.com> wrote:  
 
 
@ccdavis94303 this fix is now live.

**Comment by ccdavis94303** [comment]
tested.
Tyvm
