### ISSUE TITLE
encoding/json did not return error when Unmarshal a string valued "null"

### ISSUE THREAD

**Issue by avence12** [golang/go#23269]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
$ go version
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin_amd64

### What did you do?
Try to Unmarshal a string of "null" and expect to get error because it is not a valid JSON string.

```
package main

import (
	"fmt"
	"encoding/json"
)
func main() {
	data:=map[string]interface{}{}
        str := "null"
        err :=json.Unmarshal([]byte(str),&data)
	fmt.Println(err)
	fmt.Println(data)
}
```

### What did you expect to see?
```
<nil>
map[]
```

### What did you see instead?
```
invalid character 'n' after top-level value
map[]
```

**Comment by bradfitz** [comment]
null is a valid JSON value. See json.org.

**Comment by avence12** [comment]
Looks like Unmarshal converts `null, true, or false` string values as the primitive data type. 
Thanks for your clarification.

```
func main() {
	data:=map[string]interface{}{}
        str := "true"
        err :=json.Unmarshal([]byte(str),&data)
	fmt.Println(err)
	fmt.Println(data)
}

json: cannot unmarshal bool into Go value of type map[string]interface {}
map[]
```

**Comment by avence12** [comment]
Finding that using `Decode` to handle string starts with "null" will be treated as null value without throwing error. 

```
func main() {
	document := map[string]interface{}{}
	dec := json.NewDecoder(bytes.NewReader([]byte("nullfoo")))
	err := dec.Decode(&document)
	fmt.Println(err)
	fmt.Println(document)
}

<nil>
map[]
```

**Comment by mvdan** [comment]
That is because a single json element is decoded - it stops as soon as it has read one, `null`.

For questions about Go, see https://golang.org/wiki/Questions. I'm going to close this, as there is no specific bug or enhancement being pointed out.
