### ISSUE TITLE
os.StartProcess doesn't pass the arguments

### ISSUE THREAD

**Issue by Litarvan** [golang/go#23277]
I tried everything, but os.StartProcess seems to not pass the given arguments

### What version of Go are you using (`go version`)?
```
go version go1.9.2 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/litarvan/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build281376345=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

**test_executable :**
```
#!/bin/bash
echo Args are : $@
```

**main.go :**
```go
package main

import (
	"os"
)

func main() {
	stdout, _ := os.Create("stdout.log")
	stderr, _ := os.Create( "stderr.log")
	
	processPath := "test_executable"
	args := "a_random_arg"
	
	println("Starting : " + processPath + " " + args)
	process, err := os.StartProcess(processPath, []string {args}, &os.ProcAttr{ Dir: ".", Files: []*os.File{stderr, stdout} })
	
	if err != nil {
		println(err.Error())
		return
	}
	
	process.Wait()
}
```

### What did you expect to see?
Output should be : `Starting : test_executable a_random_arg`
stdout.log should contain : `Args are : a_random_arg`, as it shows when i'm copy pasting the command `test_executable a_random_arg` in my terminal

### What did you see instead?
Output is : `Starting : test_executable a_random_arg`
stdout.log contains : `Args are :`, there is no args given

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by Litarvan** [comment]
It looks like at first, but the big code pasting is not my program, but a proof of the bug.
This is not a question, but an issue in the os.StartProcess function, it is an issue, no ?

**Comment by bradfitz** [comment]
For https://golang.org/pkg/os/#StartProcess, your argv must contain the binary name first, before the "actual" arguments.

But really nobody should use os.StartProcess. You should use the `os/exec` package instead.

**Comment by Litarvan** [comment]
Oh, thanks ! But, shouldn't this be written in the os.StartProcess doc ?

**Comment by bradfitz** [comment]
Well, it does say:

> StartProcess is a low-level interface.

And I guess people familiar with the low-level interface know the meaning of `argv` and that it includes the name of the process as it was invoked.

But sure, I'll send a change with a bit of docs.

**Comment by Litarvan** [comment]
Guess it's my bad, i only looked at the in-code doc, and i'm new to low-level programming, thanks tho !

**Comment by bradfitz** [comment]
No worries. I sent https://go-review.googlesource.com/#/c/go/+/85675

**Comment by davecheney** [comment]
As Brad mentioned, you probably don’t want to use this low level interface. 

Try 
https://golang.org/pkg/os/exec/#Cmd

**Comment by Litarvan** [comment]
I managed to do it using this, thanks !
