### ISSUE TITLE
net/http/cgi: don't show black terminal on Windows when CGI is run

### ISSUE THREAD

**Issue by minicase** [golang/go#23270]
cgi package in std lib
show balck terminal everytime when use a “cgi.ServeHTTP(ctx.ResponseWriter, ctx.Request)”

**Comment by davecheney** [comment]
I’m sorry there is not enough information in this issue report to determine if this is a bug in Go.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by bradfitz** [comment]
I imagine this is a Windows issue where we're not setting some windows flag to suppress the CMD.EXE box when running a child process?

**Comment by as** [comment]
For informational purposes here's a relevant experience I had with this problem:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx

Creating a process with CREATE_NO_WINDOW was a huge rat hole that didn't work, but using the DETACHED_PROCESS flag suppressed conhost.exe/cmd.exe on Windows 7 and Windows 2008R2. Conhost is the text buffer for things that spill into and out of the cmd.exe (this can be verified by changing the screen buffer size in cmd.exe to a large number and then running a command with a lot of output. The conhost.exe process will begin to use up more memory linear to the screen buffer size).

**Comment by minicase** [comment]
I have resolved the issue.

modify the std lib  \src\net\http\cgi\host.go

add a new line "cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}"   at line 231

then dont foget a rebuild
![tim 20171229123324](https://user-images.githubusercontent.com/9739133/34429549-af6bb5a6-ec94-11e7-9e35-c1a5a33b371b.png)

**Comment by as** [comment]
@minicase 

This doesn't prevent the Window from being created, on this particular Windows machine (2012R2), it just moves the window to an off-screen coordinate.

**Comment by alexbrainman** [comment]
> I imagine this is a Windows issue where we're not setting some windows flag to suppress the CMD.EXE box when running a child process?

I am not sure we want to do that.

@minicase how do I run your program to see the issue you are having? What code do I run? How do I run it?

Thank you.

Alex

**Comment by bradfitz** [comment]
ETIMEOUT.
