### ISSUE TITLE
range: address of copied struct

### ISSUE THREAD

**Issue by charlierudolph** [golang/go#23286]
### What version of Go are you using (`go version`)?

1.9

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

docker image of "golang:1.9-alpine"

### What did you do?

https://play.golang.org/p/nhuGyldm0eF

```go
package main

import (
	"fmt"
	"time"
)

type MyStruct struct {
	Timestamp time.Time `json:",omitempty"`
}

type MyStructP struct {
	Timestamp *time.Time `json:",omitempty"`
}

func main() {
	list := []MyStruct{
		{Timestamp: time.Unix(1095379198, 0)},
		{Timestamp: time.Unix(1095379199, 0)},
		{Timestamp: time.Unix(1095379200, 0)},
	}
	fmt.Println("Original", list)

	var copyList1 []MyStructP
	for i := range list {
		r := list[i]
		copyList1 = append(copyList1, MyStructP{Timestamp: &r.Timestamp})
	}
	fmt.Println("Copy 1  ", copyList1)

	var copyList2 []MyStructP
	for _, r := range list {
		copyList2 = append(copyList2, MyStructP{Timestamp: &r.Timestamp})
	}
	fmt.Println("Copy 2  ", copyList2)
}

// Output:
// Original [{2004-09-16 23:59:58 +0000 UTC} {2004-09-16 23:59:59 +0000 UTC} {2004-09-17 00:00:00 +0000 UTC}]
// Copy 1   [{2004-09-16 23:59:58 +0000 UTC} {2004-09-16 23:59:59 +0000 UTC} {2004-09-17 00:00:00 +0000 UTC}]
// Copy 2   [{2004-09-17 00:00:00 +0000 UTC} {2004-09-17 00:00:00 +0000 UTC} {2004-09-17 00:00:00 +0000 UTC}]
```

### What did you expect to see?

Copy 1 and 2 to be equal. 

Thus that the pointers into the copy of each element would be distinct. 

### What did you see instead?

Copy 1 and 2 are not equal

When creating copy 2 it appears the chunk of memory for `r` is overwritten at each array iteration. 

### Notes

This may be an intended optimization and if so I think it just needs to be called out somewhere. The use case here was converting a timestamp from a database row into a pointer, while converting values of zero to nil, so that when marshaling to JSON the value can be omitted using "omitempty"

**Comment by cespare** [comment]
Hi @charlierudolph. As you guessed, this is indeed intentional; it's how the language is specified -- there is only one iteration variable (`r`) and it's assigned to in every loop iteration. (So when you take the address of it, you'll get the same value each time.)

Read https://golang.org/ref/spec#For_statements if you want to know the details, or use one of the forums listed at https://github.com/golang/go/wiki/Questions if you have more questions about it.

Closing since there's no bug.
