### ISSUE TITLE
cmd/go: slightly confusing import cycle error when a package imports itself

### ISSUE THREAD

**Issue by mvdan** [golang/go#23295]
### What version of Go are you using (`go version`)?

    go version devel +f3f507b2d8 Fri Dec 22 21:13:38 2017 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Create the package `p` in my GOPATH, with a single file, then run `go install`:

```
package p

import "p"
```

### What did you expect to see?

Some sort of error, like "a package cannot import itself".

### What did you see instead?

```
$ go install
can't load package: import cycle not allowed
package p
        imports p
import cycle not allowed
package p
        imports p
```

This is a minimal example - I found this while merging package B into A, when B was importing A. This resulted in a couple of files in package A still importing package A.

I understand that the error is technically correct, but it's a bit confusing and it threw me off for a couple of seconds. The error message suggested above would have pointed me in the right direction faster.

It's also worth noting how the "import cycle not allowed" message is printed twice for some reason.

**Comment by griesemer** [comment]
This error is reported by go build/install, not the compiler. Reassigning.

**Comment by mvdan** [comment]
Do we care about GOPATH mode that much at this point? Module mode behaves better:

```
#!/bin/bash

docker run -i golang:1.13 <<-SCRIPT

        mkdir foo
        cd foo
        go mod init test.tld/foo
        go env GOMOD

        cat >foo.go <<-EOF
                package foo

                import "test.tld/foo"
        EOF

        go build

SCRIPT
```

```
$ ./repro.sh
go: creating new go.mod: module test.tld/foo
/go/foo/go.mod
can't load package: import cycle not allowed
package test.tld/foo
        imports test.tld/foo
```

The double error is gone, but I still think the message could be more helpful to humans. For example, pointing at how a package can never import itself. But if we decide that that's unnecessary, I think the issue can be closed.

**Comment by seankhliao** [comment]
The current error is:

```sh
$ go build
package go.seankhliao.com/testrepo0930
	imports go.seankhliao.com/testrepo0930 from main.go: import cycle not allowed
```

I feel like it's fine?

**Comment by mvdan** [comment]
I think it's fine. I might still want a clear message like "a package cannot import itself", but perhaps that's obvious enough.
