### ISSUE TITLE
mime/multipart: Header populated by Reader.NextPart() should not modify the order of the body headers

### ISSUE THREAD

**Issue by dawud-tan** [golang/go#23290]
[Reader.NextPart](https://golang.org/pkg/mime/multipart/#Reader.NextPart) sometimes alter the order of the headers of the body which cause [my app](https://github.com/dawud-tan/AS2-Golang/blob/master/as2_golang.go#L123) that utilize digital signature fail to verify because of message alteration.

**Comment by davecheney** [comment]
Header ordering has been raised several times over the years and the response has been that the http spec does not define a header order. 

If we were to change the order of headers to be ordered, which order should we choose? Unordered headers aren’t they helpful for your use, but neither are headers ordered in the wrong order for your application. You can see that promising _an_ order would lead to feature requests to alter that order. 

For you application I recommend that you sort the headers according to your requirement explicitly. Then you’re not reliant on an implant detail of the http package which may change.

**Comment by dawud-tan** [comment]
I mean, had the modified my data?
could it be make to leave the data intact?

**Comment by davecheney** [comment]
What is probably happening is data is being read into a map, which will remove any ordering. Based on similar issues raised in the past I don’t expect that this one will be accepted so my advice is to asset the ordering of headers you need explicitly.

**Comment by dawud-tan** [comment]
well, thanks for the info, so, the issue could be closed.

**Comment by bradfitz** [comment]
I don't understand what this bug report is about (the bug template was deleted and there's no repro or code snippet), but per the last comment, I will close this.
