### ISSUE TITLE
Nil Channels and Case Evaluation

### ISSUE THREAD

**Issue by dc0d** [golang/go#23292]
In this code:

```go
package main

import (
	"log"
	"time"
)

func main() {
	f()
}

func first() bool {
	select {}
}

func f() {
	// for demonstration purpose
	var rcvd chan bool = nil
	select {
	case rcvd <- first():
	case <-time.After(time.Second):
		log.Println("timeout")
	}
	log.Println("done")
}

func init() {
	log.SetFlags(0)
}
```

Since `rcvd` is `nil`, the expected output was `timeout` and then `done`.

Instead it blocks forever. It is working according to specs.

One would expect `nil` channels will get ignored by `select` statement. Does that sound logical?

Go 1.9.2 (release), Ubuntu 16.04 (amd64)

**Comment by davecheney** [comment]
This is working as expected. The right hand side of all cases are evaluated before the selection is made. This step is never finished because of the select {} statement blocking completion.

**Comment by dc0d** [comment]
@davecheney Thanks Dave, I've updated the code with a complete example.

**Comment by davecheney** [comment]
@dc0d I think it would be best if you closed this issue and continued your discussion on golang-nuts
