### ISSUE TITLE
fmt: document the behaviour of %p on slices

### ISSUE THREAD

**Issue by nhooyr** [golang/go#23291]
I was surprised by the following program's output:

```go
package main

import (
	"fmt"
)

func main() {
	foo := make([]int, 0, 1)
	fmt.Printf("same: %p\n", foo)

	foo = append(foo, 0)
	fmt.Printf("same: %p\n", foo)

	foo = append(foo, 0)
	fmt.Printf("different: %p\n", foo)
}
```

Example output:

```
same: 0xc420018060
same: 0xc420018060
different: 0xc420018070
```

I was expecting an error because there is no documentation regarding `%p` with slices in https://golang.org/pkg/fmt/ but it works fine.

I was surprised by the output as the printed address changed when the underlying array of the slice was modified. This is the expected behaviour because fmt is using the reflect package's Pointer() method on the slice, which will return the address of the first element of the slice. See https://github.com/golang/go/blob/38c561cb2caa8019e44059e2be71c909ceef30a6/src/reflect/value.go#L1267-L1269

There should be some documentation regarding this behaviour because it is unexpected imo.

**Comment by martisch** [comment]
The valid reflect types for the verb %p are listed here:
https://github.com/golang/go/blob/master/src/fmt/print.go#L495
If CL with documentation for %p on slices is created it could be expanded to cover all possible types that are not already documented.

**Comment by mewmew** [comment]
PR #24600 seeks to address this issue, by documenting that `%p` on a slice prints the address of its first element (rather than the address of the slice descriptor).
