### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6faae7]  goroutine 1 [running]:

### ISSUE THREAD

**Issue by nikkisaumya** [golang/go#23303]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
I see this issue with both 
go version go1.8 linux/amd64
and 
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
yes the same issue is there with go version go1.9 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH= --mygopath--
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/user/0/go-build822152838=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
### What did you do?
go run main.go
output 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6faae7]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0x1)
$GOPATH/src/github.com/jinzhu/gorm/main.go:715 +0x47
github.com/jinzhu/gorm.(*search).unscoped(...)
$GOPATH/src/github.com/jinzhu/gorm/main.go:262
github.com/jinzhu/gorm.(*DB).Unscoped(0x0, 0x4124e8)
$GOPATH/src/github.com/jinzhu/gorm/main.go:262 +0x2b
github.com/jinzhu/gorm.(*DB).CreateTable(0x0, 0xc42004dd50, 0x7, 0x7, 0xc4200958e0)
$GOPATH/github.com/jinzhu/gorm/main.go:513 +0x2f
main.initializeDataStores(0xc4201b8000)

exit status 2

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I expect the server to run on the specified port, even if i make slight changes in the code the server runs but the panic eror dont seem to stop , indicating gorm

### What did you see instead?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6faae7]

**Comment by cznic** [comment]
The trace shows that the DB methods were called with a nil receiver. Doesn't look like a Go issue to me.

**Comment by ianlancetaylor** [comment]
Does not look like a bug in the Go tools or library.  Closing.  Please comment if you disagree.

Note that we only use the issue tracker for bugs, not for questions about how to use Go.  See https://golang.org/wiki/Questions.  Thanks.

**Comment by nikkisaumya** [comment]
Thank you @cznic, it was a mysql connection issue.
