### ISSUE TITLE
x/perf/benchstat: html output renders garbled "µ" characters in Firefox

### ISSUE THREAD

**Issue by myartsev** [golang/go#23308]
In Firefox, the html output for benchstat renders garbled "µ" characters and the following warning:
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

![garbled](https://user-images.githubusercontent.com/4885345/34497154-5acfd638-efca-11e7-860d-8ad162cb8c3b.png)

One resolution would to be to specify the html encoding
`<meta charset="utf-8"/>`
![fixed](https://user-images.githubusercontent.com/4885345/34497215-9e483b4e-efca-11e7-9c67-04c908f65845.png)

**Comment by namusyaka** [comment]
Your solution looks reasonable to me. Actually, `go tool cover -html` output has specified html encoding which would be something like:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
....
```

Also, the output of benchstats seems not to be valid as w3c html5 specification.
I'm going to fix the problems.
