### ISSUE TITLE
cmd/go: go test -cover loses coverage of some inlined functions

### ISSUE THREAD

**Issue by soniakeys** [golang/go#23314]
### What version of Go are you using (`go version`)?
Bisected to ci ee4fbbc6, "stop creating nested temp directory trees".  Reproduces at tip as of Jan 2.

### Does this issue reproduce with the latest release?
with 1.9.2, No.

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
go get -t github.com/soniakeys/unit
go test -cover github.com/soniakeys/unit

(The issue happens on this package of mine, github.com/soniakeys/unit.  I'm very sorry I don't have a small test case at the moment.  I wanted to file the issue anyway to see if the information here was enough to spark some idea of the problem.)

### What did you expect to see?
With 1.9.2, or up to the ci noted above,
ok  	github.com/soniakeys/unit	0.003s	coverage: 100.0% of statements

### What did you see instead?
From the noted ci or later built in ~/pt,
$ ~/pt/bin/go test -cover github.com/soniakeys/unit
ok  	github.com/soniakeys/unit	0.003s	coverage: 63.4% of statements

The coverprofile showed the missing statements were one-liners, likely inlined.  Sure enough, with '-l':
$ ~/pt/bin/go test -cover -gcflags=-l github.com/soniakeys/unit
ok  	github.com/soniakeys/unit	0.003s	coverage: 100.0% of statements

**Comment by namusyaka** [comment]
Couldn't reproduce the issue in my local (osx) or linux/amd64.

go version:
```sh
$ go version
go version go1.9.2 linux/amd64
```

`go env`:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/namusyaka/go"
GORACE=""
GOROOT="/home/namusyaka/.goenv/versions/1.9.2"
GOTOOLDIR="/home/namusyaka/.goenv/versions/1.9.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build842395550=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
``` 

```sh
$ go test -cover github.com/soniakeys/unit
ok  	github.com/soniakeys/unit	0.009s	coverage: 100.0% of statements
```

Hope that helps.

**Comment by soniakeys** [comment]
Right.  It shows 100% with 1.9.2, but try it with tip and it shows 63%.

**Comment by mvdan** [comment]
Conservatively marking for 1.10, unless it is proven to not be a regression.

**Comment by agnivade** [comment]
Tried with 1.10beta and master. 63% with both and 100% with 1.9.2. Seems like a regression to me.
