### ISSUE TITLE
x/mobile/cmd/gomobile: log show twice in xcode

### ISSUE THREAD

**Issue by wpajqz** [golang/go#23319]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/Paul/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?
use log.Println("test"), xcode's terminal show twice test
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by agnivade** [comment]
@wpajqz - Can you provide us with a complete program along with the steps to reproduce this ? You mention that it is a `gomobile` issue. What is the `gomobile` command you are running ? Does it still happen with the latest version of `gomobile` as well as `go` ?

**Comment by wpajqz** [comment]
I am sorry，it's too long. the progrom is lost

**Comment by agnivade** [comment]
Got it. So IIUC, you are not facing this issue anymore ? Would you like to close the issue until you see this again the next time ? Then we can reopen this with the proper repro steps.
