### ISSUE TITLE
cmd/go: go build mixing tags when running builds in parallel

### ISSUE THREAD

**Issue by xudongzheng** [golang/go#23315]
### What version of Go are you using (`go version`)?

1.9.2

### What operating system and processor architecture are you using (`go env`)?

I've been able to reproduce this on both my Mac and Linux.

### What did you do?

- Package alfa (always built with tag alfa) uses package charlie.
- Package bravo (always built with tag bravo) uses package charlie.
- Package charlie behaves differently depending on the build tag (either alfa or bravo)

### What did you see instead?

When I run two "go build" processes in parallel, sometimes alfa (with alfa tag) will include charlie (with bravo tag). The opposite also happens: bravo (with bravo tag) with charlie (with alfa tag). I've constructed a minimal example to demonstrate this: https://github.com/xudongzheng/alfabravo. If you run loop.sh, it will build with parallel.sh 100 times.

Here it doesn't happen consistently but when building for a personal project, it happens on every other build (presumably because the package is larger, the build takes longer, and there is more time for the race to occur).

![screen shot 2018-01-02 at 22 07 37](https://user-images.githubusercontent.com/4230040/34507997-5ef1d204-f009-11e7-9b93-aa4a78e7c69a.png)

**Comment by bradfitz** [comment]
This is fixed in Go 1.10. See https://tip.golang.org/doc/go1.10#build

Let us know if you still have a problem.

**Comment by xudongzheng** [comment]
I'm getting the same issue with tip and 1.10 beta 1, where the issue actually occurs more consistently.

![screen shot 2018-01-02 at 22 18 33](https://user-images.githubusercontent.com/4230040/34509333-d460c77c-f016-11e7-9534-1f2ddee70e6c.png)

**Comment by xudongzheng** [comment]
I'm able to reproduce the issue at tip, although with a slightly modified charlie package (I've updated my repository). The previous one was compiling too quickly so I added a .c file and the issue continues to occur.

![screen shot 2018-01-03 at 00 29 15](https://user-images.githubusercontent.com/4230040/34509882-2c11eb76-f01d-11e7-9b77-a4b9c88dd7ce.png)

**Comment by bradfitz** [comment]
I haven't looked at your updated repro, but I'll reopen this.
