### ISSUE TITLE
SettingGOPATH wiki should be named Setting-GOPATH instead 

### ISSUE THREAD

**Issue by clydedacruz** [golang/go#23334]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
The "Setting GOPATH" wiki is named SettingGOPATH which looks off. It should be Setting-GOPATH instead in the title and all the docs referring to it https://github.com/golang/go/wiki/SettingGOPATH

We can use the https://github.com/golang/go/wiki/Setting-GOPATH page instead which is a copy of the existing page but with the title fixed

The link would have to be updated in the following files.   
- doc/code.html   
- doc/install.html   
- src/cmd/go/internal/help/helpdoc.go   
- src/cmd/go/alldocs.go

**Comment by bradfitz** [comment]
Doesn't seem worth it, as we'd have to maintain the old one anyway to avoid breaking links.
