### ISSUE TITLE
Go standard library tests dial google.com

### ISSUE THREAD

**Issue by R41z** [golang/go#23335]
That's a privacy issue because whenever I build Go on my local machine, tests will run and if google is listening to a specific set of packets, they could tell whether if someone is building Go on their machine.

https://github.com/golang/go/blob/master/src/crypto/tls/tls_test.go#L336
https://github.com/golang/go/blob/master/src/net/smtp/smtp_test.go#L207
https://github.com/golang/go/blob/master/src/net/external_test.go#L23
https://github.com/golang/go/blob/6c877e5da7ab14f0d8a206c09f24cf51fbbc393a/src/net/lookup_test.go
_there are more of course..._

**Comment by mvdan** [comment]
Note that you don't need to run the test suite to buid Go - simply use `make.bash` instead of `all.bash`. I would say that makes this issue invalid.

If you're talking about ways to run the entire test suite without internet, that's a different issue. It seems like the tests should pass if you're not connected to it - see `MustHaveExternalNetwork`.

**Comment by R41z** [comment]
So there is no way to run tests without dialing google.com other than disconnecting the whole system?

**Comment by mvdan** [comment]
That was my guess given the name. If you look into the code, you'll see:

```
// MustHaveExternalNetwork checks that the current system can use
// external (non-localhost) networks.
// If not, MustHaveExternalNetwork calls t.Skip with an explanation.
func MustHaveExternalNetwork(t testing.TB) {
        if testing.Short() {
                t.Skipf("skipping test: no external network in -short mode")
        }
}
```

So using `-short` would skip them. That will also skip lots of other slow tests that don't need the internet, though. If you would like to suggest an improvement or submit a patch, you're of course welcome to.

And there is no need to focus this issue around google.com. There are plenty of other tests that use other domains and hosts, such as `src/cmd/go/go_test.go` running `go get` on `vcs-test.golang.org`, `github.com/golang/go`, and `rsc.io`.

**Comment by bradfitz** [comment]
And all.bash runs tests in short mode anyway. So the default is to not use the external network.

**Comment by bradfitz** [comment]
Considering `all.bash` doesn't use the external network, and that's the default way to run all tests, I don't think there's anything to do here.

You have to go out of your way to run the full tests that hit the external network.

**Comment by ianlancetaylor** [comment]
Let me expand that answer slightly say that if running all.bash causes your machine to open a TCP connection to google.com, or, indeed to anywhere other than localhost, that is a bug that should be reported and fixed.

It is true that running `go test net` will open a connection to google.com, but running all.bash does not do that; it runs `go test -test.short net`.
