### ISSUE TITLE
crypto/tls:  no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by chowyu08** [golang/go#23330]
### What version of Go are you using (`go version`)?
golang1.9.2

### Does this issue reproduce with the latest release?
tls error: with no cipher suite supported by both client and server

### What operating system and processor architecture are you using (`go env`)?
broker:  ubuntu16.04
device:  no system

### What did you do?
I run a mqtt broker with tls  wirte by golang, for device connect. 
listener code :
` l, err = tls.Listen("tcp", addr, b.TLSConfig)
`

result:
paho mqtt client , mosquitto_sub, mosquitt_pub was ok,   but device was wrong with the error " no cipher suite supported by both client and server"

but when i use the same certs with mosquitto broker, device connect success.

### What did you expect to see?
wireshark message in the broker write by golang:
mosquitto client package
![image](https://user-images.githubusercontent.com/16483518/34548195-a82ac042-f13b-11e7-86a8-2263d3087c4b.png)

device package
![image](https://user-images.githubusercontent.com/16483518/34548259-ff66afce-f13b-11e7-99a7-3444296808c2.png)

the device miss some extensions, but mosquitto can accept connect, my broker was wrong.

**Comment by bradfitz** [comment]
What is "device"?

**Comment by chowyu08** [comment]
@bradfitz  "device" is a micro machine with a firmware,  support MQTT protocol, can connect to network.
I add a Haproxy in the front of my broker writted by golang,  TLS verificatie success and device connect success.

**Comment by bradfitz** [comment]
Your screenshot shows your device offering 85 cipher suites. Which ones?

The error you cited was "no cipher suite supported by both client and server", so apparently there's no overlap between what the server is offering and what your device supports.

You can probably change your server's *tls.Config to offer more cipher suites, but you'll need to figure out which ones your device supports.

It doesn't look like there's a Go bug here. You just need to configure your program to match what your device supports, which might be old & insecure.
