### ISSUE TITLE
x/oauth2: Add Spotify Endpoints

### ISSUE THREAD

**Issue by FenwickElliott** [golang/go#23338]
Adding Spotify endpoints as per documentation: https://developer.spotify.com/web-api/authorization-guide/

**Comment by odeke-em** [comment]
@FenwickElliott please feel free to mail a CL, just in case you haven't yet seen it, please see https://golang.org/doc/contribute.html and in particular, after setting up the initial Gerrit workflow, then https://golang.org/doc/contribute.html#subrepos -- that should take a couple of steps to setup, not too many.

I'll also tag @rakyll @broady

**Comment by FenwickElliott** [comment]
Thanks, I tried to be very deliberate about setting myself up correctly according to the Contribution Guide.

However when I run the global tests according to https://golang.org/doc/contribute.html#Testing I am getting failures (exactly the same errors with or without my contribution). And to be honest the fails are beyond my scope. Any advice on how I should proceed?

**Comment by bradfitz** [comment]
No need to run the global tests for contributing to the oauth2 repo. Just run the oauth2 tests.

**Comment by odeke-em** [comment]
Thank you @FenwickElliott for the feedback and congrats on making it that far! IMHO don't worry about them being "beyond my scope", soon they won't  be anymore ;) Let's try to isolate out the noise, those tests are relevant for the main Go project. For your contributions let's take a look instead at https://golang.org/doc/contribute.html#subrepos.

Seems like at this point, your Gerrit is correctly setup, so if you run
```shell
go get -d golang.org/x/oauth2/...
$GOPATH/src/golang.org/x/oauth2
```
you can then make your change following say what was done at https://github.com/golang/oauth2 with the respective directories for example for Paypal, there is a directory `paypal` and it's file https://github.com/golang/oauth2/blob/master/paypal/paypal.go

Once you've made a similar change, then please mail it with Gerrit and tag me, and I'll help out more there.

Please let me know if this makes sense or if at any point you need some clarification.

**Comment by odeke-em** [comment]
Aha @bradfitz you beat me to the response ;)

**Comment by FenwickElliott** [comment]
Great, thank you. That makes perfect sense and is a massive relief.

**Comment by FenwickElliott** [comment]
Thanks for all your help, really (both of you).

I've mailed to so hopefully we're all good. :)
