### ISSUE TITLE
runtime: TestGcSys does not really pass, should be fixed or removed

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#23343]
The runtime test `TestGcSys` no longer tests anything.  The test simply checks whether the function `GCSys` in runtime/testdata/testprog/gc.go prints `OK`.  It currently passes because the helper function  `workthegc` is inlined and the compiler discards the allocation of the slice.  If I change the code slightly to add `//go:noinline` before `workthegc`, the test fails, saying `using too much memory: 64086016 bytes` (the exact number of bytes reported varies).

We should either discard the test or fix it so that it actually tests something about the GC.

(I noticed this because the test fails consistently using gccgo, which does not currently discard the slice allocation.)

CC @aclements @RLH

**Comment by mvdan** [comment]
I am curious if there is any general good practice to detect whether tests silently stopped doing what they should be doing. It is fairly easy for that to go under the radar if the test continues to pass or is always skipped.

I can imagine "write good tests" and using metrics like coverage, but when thousands of tests are involved (such as in the standard library), things can get out of hand.

**Comment by ianlancetaylor** [comment]
We still need to fix the test to actually test something, but at least it seems to pass now.
