### ISSUE TITLE
issues in strconv package

### ISSUE THREAD

**Issue by tgg-manish** [golang/go#23347]
package main

import (
 "fmt"
 "strconv"

)

func main() {
 

 Count := 5.5
 fmt.Println(strconv.FormatFloat(Count , 'f', 0, 64))
}
//=====================================================

for Count  calue 6.5,  7.5
and see the result

**Comment by mvdan** [comment]
Please use the entire bug report template and provide a play.golang.org link.

**Comment by bontibon** [comment]
I believe what @tgg-manish is reporting is that 5.5 rounds to 6, 6.5 rounds to 6, and 7.5 rounds to 8.

**Comment by tgg-manish** [comment]
https://play.golang.org/p/SEh2vgBQchL

**Comment by dominikh** [comment]
This is working as intended and due to how IEEE 754 floating point numbers work. See https://github.com/golang/go/issues/21714 for a related issue and http://floating-point-gui.de/ for an explanation.
