### ISSUE TITLE
The JSON and Go blog entry from 2011 is out of date

### ISSUE THREAD

**Issue by timbray** [golang/go#23349]
The blog at https://blog.golang.org/json-and-go says: 
<<<<<
The json package uses map[string]interface{} and []interface{} values to store arbitrary JSON objects and arrays; it will happily unmarshal any valid JSON blob into a plain interface{} value. The default concrete Go types are:

bool for JSON booleans,
float64 for JSON numbers,
string for JSON strings, and
nil for JSON null.
<<<

In fact, now it also uses "int" when you have { "foo": 27 }

**Comment by bradfitz** [comment]
Got an example?

That's not what I see. https://play.golang.org/p/PwgBo_L7kEq

**Comment by timbray** [comment]
Oh crap, I had something in between the JSON and the test that screwed with the data, you're right.  Apologies.
