### ISSUE TITLE
x/sys: CPUSet addition breaks Go 1.8 compatibility by requiring math/bits

### ISSUE THREAD

**Issue by marklshep** [golang/go#23353]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
It should not.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go:/switchboard/utils/golang/:/switchboard/services/golang/"
GORACE=""
GOROOT="/opt/ecr/external/go"
GOTOOLDIR="/opt/ecr/external/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build826031598=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
Attempted to build a go program that uses affinity_linux.go.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

This should be reproducible with any program that will cause affinity_linux.go  to build while running go1.8.3 on a unix machine.

### What did you expect to see?
I expected the program to build.

### What did you see instead?
root@ubuntu:/myGoProject# bash /my/path/module-build.sh 
`package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)`

I believe that Go enforces backwards compatibility strictly, so the import should either not exist or be protected against older versions. I may be mistaken as I recently started using Go.

Sorry for not following any formatting rules y'all have. I was rushing to get it out to save other folks some time.

**Comment by bradfitz** [comment]
Yes, we still need to support Go 1.8 for another two weeks.

@tklauser, can you hide that file behind `+build go1.9`?

**Comment by bradfitz** [comment]
or copy the portable OneCount64 into that file behind a build tag. either way.
