### ISSUE TITLE
Documentation bug in gob

### ISSUE THREAD

**Issue by jaekwon** [golang/go#23358]
https://golang.org/pkg/encoding/gob/#Encoder.Encode says,

> Passing a nil pointer to Encoder will panic, as they cannot be transmitted by gob.

But it does not.  See: https://play.golang.org/p/9zffEMP_DQU

Same with https://golang.org/pkg/encoding/gob/#Encoder.EncodeValue.

We're working on yet another encoding library (this one handles Golang interfaces well) for [Tendermint](https://github.com/tendermint/tendermint) and found this discrepancy.

@odeke-em

**Comment by jaekwon** [comment]
Nevermind, bad example, no bug.

**Comment by odeke-em** [comment]
Ahh right, sorry about that @jaekwon -- the docs are right as you noted later on before closing.
