### ISSUE TITLE
Question regarding XOR and conversion to string

### ISSUE THREAD

**Issue by redmed666** [golang/go#23364]
### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pd/kj0fmnkn3j7_mw29rkwjnqkr0000gn/T/go-build238005088=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
https://play.golang.org/p/n2g1ZEktOMN

### What did you expect to see?
str4 having the same length as str3

### What did you see instead?
str4 has a length of 10 instead of 5

### Question
How is golang dealing with a conversion from a byte to a string when using string()? 
What I don't understand is that the character is 2 byte long instead of just 1 (because this operation: 
`byte(str1[i]) ^ byte(str2[i])` has an output of 1 byte.). 
Or maybe am I missing something?

Thank you for your time.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
