### ISSUE TITLE
Documentation glitch for package math/rand

### ISSUE THREAD

**Issue by vikramdurai** [golang/go#23363]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
I'm not sure.

### What operating system and processor architecture are you using (`go env`)?
I don't know.

### What did you do?
I ran the first example.
https://play.golang.org/p/nMDQEAaAnuX

### What did you expect to see?
I expected the first example to produce random answers.

### What did you see instead?
One answer ("As I see it yes") kept coming again and again.

**Comment by bradfitz** [comment]
This is working as intended. It's a pseudorandom number generator package. Given the same seed, it'll produce the same output. Use crypto/rand for actual randomness. But note that the playground caches runs, so you can't see randomness on the playground..
