### ISSUE TITLE
container/list: if list does not have any element, invoke Remove will panic

### ISSUE THREAD

**Issue by Hu-Jiang** [golang/go#23372]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Jiang_Hu/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t0/wz8wcf3s7_zfl024tzh3m0bc0000gn/T/go-build810890647=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
```
l := new(list.List)
l.PushFront(1)
fmt.Println("remove value:", l.Remove(l.Front()))
fmt.Println("remove value:", l.Remove(l.Front()))
```
code link: https://play.golang.org/p/8kwOyncS3_q

### What did you expect to see?
do not panic, just do nothing

**Comment by cznic** [comment]
I think this is working as intended. One should not pass nil to `Remove`. Putting the check into `Remove` will slow down all places where the test is not necessary.

**Comment by Hu-Jiang** [comment]
so when i want to remove a element, i need to judge whether it's nil？ This way is also slowly.

**Comment by cznic** [comment]
Yes, but now it's only where necessary: https://play.golang.org/p/JMngsvc22eq

**Comment by bradfitz** [comment]
@cznic is correct that this is working as intended. It also helps catch programmer errors. I've sent a documentation change at least.
