### ISSUE TITLE
cmd/go: go doesn't respect $GOPATH in windows system environment variable

### ISSUE THREAD

**Issue by eromoe** [golang/go#23387]
### What version of Go are you using (`go version`)?

go version go1.9.2 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

win7 x64

### doesn't respect $GOPATH in windows.

still install at user home.

![image](https://user-images.githubusercontent.com/3938751/34727117-ea00889a-f590-11e7-9508-1167875ab2b7.png)

![image](https://user-images.githubusercontent.com/3938751/34727068-c743e16c-f590-11e7-9c9d-608eca7cdef4.png)

PS:  Work with user environment variable

**Comment by bontibon** [comment]
What is the output of `go env`?

**Comment by as** [comment]
Is that a literal newline in the environment variable's name?

**Comment by as** [comment]
Can you provide relevant output from running:

`reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /s`

**Comment by rsc** [comment]
Pretty sure @as is right: set | grep GOPATH should show:

    GOPATH=D:\GOPATH\

NOT

    GOPATH
    =D:\GOPATH\

**Comment by eromoe** [comment]
I don't know why looks like this , it does show correct in windows env editor

![image](https://user-images.githubusercontent.com/3938751/34750961-d809deb2-f5e4-11e7-8aaf-1f3d0af63f7c.png)
