### ISSUE TITLE
cmd/doc: be context-sensitive when resolving package paths

### ISSUE THREAD

**Issue by robpike** [golang/go#23383]
If I

```
$ cd $GOPATH/upspin.io
$ go doc ./errors
```

what comes out is the package docs for the Go standard error package, which is not the right answer. Instead, the `./` should mean to look in `upspin.io/errors` first.

It's even possible that if I say

```
$ cd $GOPATH/upspin.io/path
$ go doc errors
```

(no `./`) it should prefer the local `errors` package from the `upspin.io` repo. Not sure about that.

But certainly `./` should mean something.

**Comment by mvdan** [comment]
@robpike should we milestone this for 1.11 if you're planning on working on it?

**Comment by sunbenxin** [comment]
![image](https://user-images.githubusercontent.com/5415802/34714305-0f92c104-f564-11e7-90cd-d7b437b93d71.png)
