### ISSUE TITLE
doc: document that Go 1.10 is the last release to support Windows XP

### ISSUE THREAD

**Issue by bradfitz** [golang/go#23380]
We plan to announce that Go 1.10 will be the last release of Go to support Windows XP.

We'd rather not support ancient operating systems forever.

Thoughts?

Alex, you don't actually use XP regularly anymore do you?

/cc @alexbrainman @raggi

**Comment by ko80** [comment]
My PC at work is still on Windows XP and it is fast enough to develop software for microcontroller systems running RTOS and desktop networking services. Some of our clients are small companies and are still using Windows XP at their sites. Excluding the support of this OS from Go will cancel our plans to continue development using Go and eventually we will need to switch back to C/C++ (awful future)... Please do not consider Windows XP as an ancient until at least 2020, when we are planning to complete our project!

**Comment by davecheney** [comment]
Windows XP support ended in 2014. I don’t think that it’s reasonable to expect that the small team of contributors to the go project support an operating system well after its vendor has officially ended support for it. 

https://www.microsoft.com/en-au/windowsforbusiness/end-of-xp-support

**Comment by ko80** [comment]
This is obviously reasonable. If so, I would appeciate if anyone could fix the issue https://github.com/golang/go/issues/23375 before ending the support of Windows XP.

**Comment by davecheney** [comment]
Thank you for raising that issue. Note that 1.10 will support windows XP so if that bug is fixed in the 1.11 cycle it _may_ be backported to a 1.10 point release, but I’m not the one who’d be doing that work so I cannot answer that authoritatively.

**Comment by ko80** [comment]
I can only hope it will be fixed

**Comment by kris-nova** [comment]
@ko80 interested in taking over the backport?

**Comment by raggi** [comment]
I still use it, but for specific use cases. I'd be ok with handling backports for the subset of packages I care about etc. What is the timeline for retiring distribution of the binaries?

**Comment by bradfitz** [comment]
We've never retired old binaries. (https://golang.org/dl/ has the "Archived versions" at the bottom)

**Comment by raggi** [comment]
Great! 👍

**Comment by alexbrainman** [comment]
SGTM retire away!

I don't use windows XP nowadays.

Alex

**Comment by mvdan** [comment]
Note that even if 1.10 is the last version to support XP, you'd get bugfix backports until 1.11 is out, and security backports until 1.12 is out. That means until January 2019 - see https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance.

It is also absolutely fine to use a certain Go version for a bit longer than its release cycle, especially if it is receiving security updates.

Something that hasn't been mentioned as opposed to "please don't retire XP yet" would be offers to help maintain that system. This is not to say that such an offer would definitely delay the drop in support, but I'm sure that the very few people interested in maintaining XP support for years to come is a factor.

**Comment by rsc** [comment]
And even after Go 1.12 comes out, you can keep using Go 1.10, we just won't fix bugs in it. But if you're happy with it (or Go 1.9 or whatever version), great. You won't get security fixes, but if you are running XP you're not worried about that.

**Comment by raggi** [comment]
>   but if you are running XP you're not worried about that

This is a nit picking comment, but one of the use cases for go on xp for me has been to have a modern TLS stack to exfil data from OEM supplied XP systems. In that regard I'm using go precisely because I'm worried about that. Personally what I'll be doing is watching the TLS and crypto packages for critical changes and evaluating if I need to back port. By contrast though, I won't be particularly concerned about back porting compiler/optimizer changes and so on.
