### ISSUE TITLE
os/exec: CombinedOutput() cannot receive contents from stdout on Server 2008

### ISSUE THREAD

**Issue by DennisMao** [golang/go#23397]
### What version of Go are you using (`go version`)?
go version go1.8 windows/amd64

### What did you do?
run executable binary and receive the message after execution from stdout on Server2008.

### What did you expect to see?
excpect output: SUCCESS=0 or FAILED=1  (user-defined)

### What did you see instead?
it runs normally on Win7 & Win10.
it runs exec.command() normally on Server 2008 (64bit) .
but i can not receive the return message from stdout.
otherwise,it can normally print the message when using the CMD
![1515566478 1](https://user-images.githubusercontent.com/15226239/34758975-5a5c70a8-f614-11e7-8b73-620d059318ef.png)

I have try to bind a  **bytes.Buffer** to the stdout,and call **Run()** .But it still nothing to receive.
```
cmd := exec.Command()
var buf bytes.buffer
cmd.Stdout = &buf   //  catched nothing 
``` 

test code :
```
package main

import (
	"log"
	"os/exec"
)

func main() {
	cmd := exec.Command("tts", "hello", "D:/test.wav")
	buf, err := cmd.CombinedOutput()
	if err != nil {
		log.Println("failed:", err)
		return
	}
	log.Println("success:", string(buf))
}
```

print log:
**run on win7 & win10**
>SUCCESS=0

**run on Server 2008**
>

**Comment by DennisMao** [comment]
@as i have tried common commands,it works.   **tts.exe** is an example  executed file,which written in C++.

**Comment by as** [comment]
@DennisMao can you post the output go `go env` and the windows `ver` command?

**Comment by DennisMao** [comment]
@as  thanks for you guidance,i find the reason that the standard output cannot be redirected on Server 2008 as the secure policy. Issue closed
