### ISSUE TITLE
Typing error in Go spec documentation

### ISSUE THREAD

**Issue by kasyauqi** [golang/go#23409]
First of all, I'm sorry if it's not a typing error, still learning Go.

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu amd64

### What did you do?
Reading Go specification. Section: Properties of types and values - Type Identities.
Noticed a typing error (maybe?):

> These types are identical:
> `B0, B0, and C0`

### What did you expect to see?
> These types are identical:
> `A0, B0, and C0`

### What did you see instead?
> These types are identical:
> `B0, B0, and C0`

**Comment by ALTree** [comment]
This is #22495
