### ISSUE TITLE
proposal: Add httputil.ParseAcceptHeader

### ISSUE THREAD

**Issue by urandom** [golang/go#23400]
Currently, there's no easy way of handling the various Accept* headers, which are quite useful for API servers. There's also no easy way of finding any third party parsers for these headers as well.

In fact, the only piece of code I found was in gddo: https://github.com/golang/gddo/blob/master/httputil/header/header.go#L172, but that's not quite usable as a library.

It would be nice to add that, or a similar function to httputil.

**Comment by bradfitz** [comment]
Dup of #19307 ?

**Comment by urandom** [comment]
@bradfitz 
Looks like #19307 already covers my request
