### ISSUE TITLE
x/sys: extract Unix includes into separate files

### ISSUE THREAD

**Issue by Androbin** [golang/go#23412]
I have already submitted a PR for this on the GitHub mirror:
https://github.com/golang/sys/pull/6

Unfortunately, I was unable to re-submit it via Gerrit.
Maybe someone else bothers to make the changes?

**Comment by ALTree** [comment]
Was this proposed change discussed anywhere? Is there a reference issue?

**Comment by Androbin** [comment]
There is no other ticket or discussion associated with the PR changeset.

**Comment by ALTree** [comment]
cc @ianlancetaylor @bradfitz

**Comment by bradfitz** [comment]
Sorry, we can't look at patches that are sent as PRs, without CLAs on file. Gerrit enforces CLAs.

Please describe the problem in English and we can decide whether somebody can fix the problem independently.

Or submit it via Gerrit.

Or wait for us to start accepting GitHub PRs, soonish. (with the Google CLA bot)

**Comment by Androbin** [comment]
I have signed the CLA a while ago (via the Google CLA bot) and Gerrit lists it under "Agreements".

**Comment by ianlancetaylor** [comment]
@Androbin What is the problem?  Please tell us the problem first, then the solution.  Thanks.

**Comment by Androbin** [comment]
The script `unix/mkerrors.sh` contains both
* inlined C code, mostly - but not limited to - includes
* Shell code, generating Go code

I have extracted the former into separate files.
The refactoring is supposed to separate concerns.
This also makes both of these easier to change.

**Comment by tklauser** [comment]
> The script unix/mkerrors.sh contains both
> 
> * inlined C code, mostly - but not limited to - includes
> * Shell code, generating Go code

I don't quite see a problem with that. FWIW I find it quite convenient to have the C code inlined in mkerrors.sh as the changes usually consist of adding a header and adjusting the regex in the same file. Splitting them out would mean having to remember to edit one (or even several) more files for each added/changed constant.

**Comment by rsc** [comment]
This doesn't seem to be solving a real problem. Why do you want to do this?

**Comment by Androbin** [comment]
As I said, I thought it would be more convenient to have them separated.
Since this doesn't seem to be the case here, I'm abandoning this suggestion.
