### ISSUE TITLE
cmd/compile: ++ counts as using a variable, shouldn't

### ISSUE THREAD

**Issue by heschik** [golang/go#23416]
### What version of Go are you using (`go version`)?
1.9.2, as seen on the playground.

### Does this issue reproduce with the latest release?
Yes.

### What did you do?

https://play.golang.org/p/2RuYMrSLjt3:

```
package main

func main() {
	x := 0
	x++
}
```

### What did you expect to see?
A compiler error saying that x is unused. For the purposes of removing useless code, ++ isn't any more of a reason to have a variable than the initial assignment. += behaves the same way.

### What did you see instead?
Nothing, apparently because x++ counts as using the variable. go vet also seems content.

It's hard to believe this has never been reported before, but the closest bug Alan and I could find is https://golang.org/issue/10989, which is rather different.

I don't know if it's worth catching this as a compile error, but it ought to at least be reported by vet?

**Comment by as** [comment]
Working as designed, because `x++` is equivalent to `x=x+1` and that reduces to `x=x`, which is coherent with the current definition of usage.

https://play.golang.org/p/jCqJ8XwMJhs

**Comment by mvdan** [comment]
One error that can be given is that the last assigned value is unused. For example, when one does `x := 0; x = x + 1`, @dominikh's staticcheck reports `this value of x is never used`. That is pointed at the second statement, not at the first, as it concerns the last assigned value and not the declaration.

It is a different error, but perhaps one that would be easier to integrate into vet and other static analysis tools.

**Comment by heschik** [comment]
That's #6072, which I personally feel is a weaker case than this. I suppose if the best way to implement this is an SSA analysis then both really are the same.
