### ISSUE TITLE
Gofmt short/anonymous tuples nicely

### ISSUE THREAD

**Issue by chewxy** [golang/go#23420]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?

yes 

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chewxy/workspace/fuckit/"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qb/_mgwq5hs5fb6wplt3g_xwdt80000gn/T/go-build837195213=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

Wrote an anonymous tuple:

```
func fst(anon struct {string; int}) string {return anon.string}

func main() {
	fmt.Println(fst(struct {string; int}{"foo", 100}))
}

```

https://play.golang.org/p/7WI-FNl3lmn

### What did you expect to see?

Gofmt to place nicely with short/anonymous tuples. Something like this:

```
func fst(anon struct {string; int}) string {
	return anon.string
}

func main() {
	fmt.Println(fst(struct {string; int}{"foo", 100}))
}
```

### What did you see instead?

Something hard to read:

```
func fst(anon struct {
	string
	int
}) string {
	return anon.string
}

func main() {
	fmt.Println(fst(struct {
		string
		int
	}{"foo", 100}))
}
```

**Comment by chewxy** [comment]
The gist of this issue is Gofmt should prefer fewer lines when it comes to anonymous struct types in functions.

**Comment by bradfitz** [comment]
Sorry, gofmt is not soliciting change requests on its format. Gofmt made a set of choices at one point, and everybody agrees to live with them, even if everybody might take issue with different individual choices.

**Comment by griesemer** [comment]
FYI: I believe this is consistent with how interfaces are formatted at the moment. If you have only one type in the struct (or only one method), it goes onto a single line. E.g.:
```
package p

type _ interface{ m() } // single line
type _ interface { // multiple lines
	m()
	n()
}
type _ struct { // multiple lines
	m int
	n int
}

type _ struct{ m, n int } // single line

var _ = struct{ m, n int }{1, 2} // single line
```
It's a trade-off. Leaving as for now.

**Comment by chewxy** [comment]
OK


On Fri, Jan 12, 2018 at 10:25 AM, Robert Griesemer <notifications@github.com

**Comment by splace** [comment]
in a very similar vein this seems like an issue, hopefully anyway because to me its significantly less readable;

https://play.golang.org/p/HSQxfXjScgL

(check out what happens when you format it)

**Comment by griesemer** [comment]
@splace One-line interfaces are formatted in one line with the latest gofmt, which will be in the Go 1.10 release. Once that release is out (sometime in February), we'll update the playground and it will behave the same. Specifically, your example will be formatted as:
```
package main

type dummy struct{}

func (d dummy) Dummy() {
}

func main() {
	check(dummy{})
}

func check(i interface{}) {
	if t, is := i.(interface{ Dummy() }); is {
		t.Dummy()
	}
}
```
which looks pretty good to me.

PS: As an aside, please don't comment on closed issues going forward. Chances are high that the comment will be ignored. Open a new issue instead, and perhaps link to an existing issue. Thanks.

**Comment by splace** [comment]
you didn't format it. try it.

**Comment by splace** [comment]
it's kind of the same issue reversed.

**Comment by splace** [comment]
so this is fixed in 1.10, its not in the notes i just read.

**Comment by splace** [comment]
don’t really understand, its currently wrong, yes. but is going to be fixed in the next release, but isn't in the release notes i just read.
and why show me what i typed in the playground, rather than what its formatted into?

```package main

type dummy struct{}

func (d dummy) Dummy() {
}

func main() {
	check(dummy{})
}

func check(i interface{}) {
	if t, is := i.(interface {
		Dummy()
	}); is {
		t.Dummy()
	}
}
```

**Comment by griesemer** [comment]
@splace The release notes don't necessarily mention every minor gofmt change, but I'll make sure it gets added. Also, I showed you what it's formatted into, not what you typed into the playground. It's almost the same but not quite (there's extra blanks around `Dummy()`).

**Comment by griesemer** [comment]
@splace I just double-checked, and the change _is_ actually mentioned in the release notes in `doc/go1.10.html`:
```
Second, single-method interface literals written on a single line,
which are sometimes used in type assertions,
are no longer split onto multiple lines.
```
If you have any other concerns, please create a new issue. I will not further reply on this closed issue. Thanks.

**Comment by splace** [comment]
yes, i see it now, i was thinking they would be refereed to as 'anonymous interface literals' in the notes.

but you are wrong about the formatting, what i showed is pasted from what its formatted too, surely there's no way the playground works differently for us?

but who cares now if its, shortly, going to be fixed.
