### ISSUE TITLE
x/crypto/acme/autocert: client should deactivate authzs that failed in a non-recoverable cases

### ISSUE THREAD

**Issue by costela** [golang/go#23426]
During [the TLS-SNI](https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188) incident, `autocert` generated a lot of dangling authorization requests because of "no supported challenge type found" errors. In this case, these authorization requests would never be fulfilled, because reference to the challenge gets discarded after the error and before anything gets put in the cache. These dangling authzs, in turn, lead to rate-limiting on the side of Let's Encrypt ("too many currently pending authorizations").

Since ACMEv1 AFAICT doesn't support querying pending authorization requests, there is no way to clean up these authzs, short of waiting for the rate limit window to pass. This may become less important after #21081, if ACMEv2 supports querying.

It would be nice if the client would [deactivate the authorization](https://tools.ietf.org/html/draft-ietf-acme-acme-07#section-7.5.2) requests in these unrecoverable cases . Even though the certificate wouldn't be generated, at least we would steer clear of this specific rate-limit.

**Comment by x1ddos** [comment]
Yeah, we should definitely delete unused authorizations.
acme.Client [supports it](https://godoc.org/golang.org/x/crypto/acme#Client.RevokeAuthorization). Just need to call it from autocert.Manager in the right place.

**Comment by costela** [comment]
hey @x1ddos, maybe you have a couple of minutes to go over the CL? :)
