### ISSUE TITLE
There so many strings, like "windows" in comparison, why not use constants?

### ISSUE THREAD

**Issue by jiajunhuang** [golang/go#23425]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
I'm reading go source code, I found there are so many strings like "windows" in comparison, why not use a constant?

links: https://github.com/golang/go/blob/c13e0e8ceed4395e9ec8176579346ca6a5db269f/src/runtime/runtime1.go#L67

by using `ack -Q '"windows"'`, you can see lots more.

### What did you expect to see?
Maybe use a constant?

```go
const (
    WINDOWS = "windows"
    LINUX = "linux"
)
```

**Comment by davecheney** [comment]
“windows” is a constant.

**Comment by bradfitz** [comment]
We find `"arm"` and `"netbsd"` perfectly readable, and there's little risk of silent screw-ups; if we screw those up, builds & tests fail.

Also, your proposed replacement is the wrong style. See https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps --- it would be just `Windows` or `windows`. But of course somebody would then propose moving those constants to a shared package, like `geese`, so then `"windows"` would be spelled `geese.Windows` and the 2 byte savings from this proposal is really a 4 byte loss.

**Comment by jiajunhuang** [comment]
got, thanks! :+1:
