### ISSUE TITLE
wiki: delete Setting-GOPATH

### ISSUE THREAD

**Issue by mikioh** [golang/go#23422]
See #22711 and #23334 for details. I was a bit confused when I saw SettingGOPATH and Setting-GOPATH pages; anyway, maintaining two duplicate pages doesn't make sense.

**Comment by mvdan** [comment]
Are you asking for input? The wiki is editable by any user - if you would like to change any links or delete a page, I believe you can already do so.

**Comment by dominikh** [comment]
The wiki being editable by any user is in fact how we got into this mess :-)

**Comment by mikioh** [comment]
> Are you asking for input?

Just processing along with the existing protocol; to me, there's no difference between add and delete.
```
If you would like to add a new page, please first open an issue in the Go issue tracker with the prefix 'wiki' to propose the addition. Clearly state why the content does not fit into any of the existing pages.
```

**Comment by mvdan** [comment]
Ah, I didn't know about that protocol - makes sense. Perhaps it should be adjusted to say "add, move, or delete".

**Comment by mikioh** [comment]
Will delete the page tomorrow.

**Comment by mikioh** [comment]
Done.
