### ISSUE TITLE
What does syscall.Sysinfo_t.Procs means?

### ISSUE THREAD

**Issue by k82cn** [golang/go#23438]
I'm a little confused about the output of following code, anyone can give a suggestion?

```go
package main

import (
	"fmt"
	"path/filepath"
	"syscall"
)

func main() {
	var info syscall.Sysinfo_t
	syscall.Sysinfo(&info)
	fmt.Println("procs : ", info.Procs)

	if files, err := filepath.Glob("/proc/[0-9]*"); err == nil {
		fmt.Println("procs : ", len(files))
	}
}
```

The output is:

```
root@ubuntu-xenial:/home/ubuntu# ./main
procs :  140
procs :  120
```

### What version of Go are you using (`go version`)?
`go version go1.9.2 linux/amd64`

### Does this issue reproduce with the latest release?
should be

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build248288577=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

xref https://github.com/kubernetes/kubernetes/pull/57136

**Comment by AlexRouSg** [comment]
It's the same as calling sysinfo in C. 
https://play.golang.org/p/X6OYwjQn0BU - will not run in playground

http://man7.org/linux/man-pages/man2/sysinfo.2.html

**Comment by agnivade** [comment]
Hi,

The Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions. Thanks!

**Comment by odeke-em** [comment]
@k82cn please check out the places that @agnivade recommended asking questions on and thank you @agnivade!

**Comment by k82cn** [comment]
@odeke-em , got that, thanks very much :).

**Comment by odeke-em** [comment]
Thank you @k82cn! Actually your issue reminded me of https://github.com/golang/go/issues/4318 --  an issue that's still open, focused on how under-documented the syscall package is. I believe that if we had documented it, you'd easily get the answer.

If interested in helping to solve that issue, once you get some answers, please feel free to send some patches documenting syscall.SysInfo and the struct; it would be a great contribution for future self and to others, we'll be grateful.

**Comment by k82cn** [comment]
sure; I'd like to help it :).
