### ISSUE TITLE
x/net/ipv4: operation not permitted on ipv4.PacketConn.SetTTL()

### ISSUE THREAD

**Issue by webfrank** [golang/go#23431]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/arm darwin/amd64

### What did you do?

Just try the simple.go example of https://github.com/kanocz/tracelib

### What did you expect to see?
Complete traceroute

### What did you see instead?
operation not permitted error

If I compile the same example with go 1.8.3 works perfectly

**Comment by mikioh** [comment]
You need to update your local copy of x/net because of #19209.
