### ISSUE TITLE
dist: one-line installer: additional safety/trust features

### ISSUE THREAD

**Issue by pciet** [golang/go#23430]
The one-line installer tracked in https://github.com/golang/go/issues/23381 is something many new and current Go programmers will use, likely downloaded from golang.org. In that issue I mentioned having a sensation of distrust when using the Go 1.10 beta installer, and this issue is to discuss any additional features that may reduce such distrust.

My opinion is the valid HTTPS link source is trustworthy enough (I still ran the Go 1.10 beta) and that this issue is a nice to have perception improvement. @broady mentions in the other issue that a GPG signature is provided for all downloads on golang.org already.

The sensation of distrust is due to thinking that the features provided in the downloaded binary could be easily replicated by a third party with deconstructive intent. Due to the open source of the tool I'm not sure there's much else that could be done there and the website seems to have just about every necessary security feature, but maybe documentation saying "only download from golang.org and check for the browser green certificate verification and verify the GPG key this way" could be part of the tool distribution.

**Comment by ianlancetaylor** [comment]
I'm sorry, I don't fully understand this bug report.  When you suggest some additional documentation that "could be part of the tool distribution," what do you mean?

**Comment by ianlancetaylor** [comment]
@cznic Since we control golang.org, we should be able to know for sure whether it is vulnerable as the article describes.

**Comment by as** [comment]
- [x] Responds on port 80
- [x] Not HTTPS
- [ ] Sets magic HSTS header

```
GET / HTTP/1.1
Host: golang.org

HTTP/1.1 302 Found
Location: https://golang.org/
Content-Type: text/html; charset=utf-8
X-Cloud-Trace-Context: redacted
Date: Sat, 13 Jan 2018 00:38:35 GMT
Server: Google Frontend
Content-Length: 42

<a href="https://golang.org/">Found</a>.
```

**Comment by bradfitz** [comment]
Let's fold this bug into #23381. Obviously whatever we do for #23381 should be secure. No need to track it separately.
