### ISSUE TITLE
Edited ReadMe

### ISSUE THREAD

**Issue by inidaname** [golang/go#23442]
The Go read me file. Just a single correction of English the letter
![A screen shot](https://user-images.githubusercontent.com/5090590/34912303-4e674cc4-f8de-11e7-9219-9c6ab9a54da0.png)
Using a third `,` is not necessary before the `and`

**Comment by bradfitz** [comment]
It's not necessary, and it's not wrong. And people have opinions.

See https://en.wikipedia.org/wiki/Serial_comma

There have also been many joke comics about why the Oxford comma is preferred: https://www.google.com/search?q=oxford+comma+comic&source=lnms&tbm=isch

I think we'll leave the comma. :)
