### ISSUE TITLE
"os.RemoveAll" sometimes returns error "remove files: directory not empty"

### ISSUE THREAD

**Issue by cwen0** [golang/go#23452]
I use `os.RemoveAll` remove dir, and program sometimes return "remove pd: directory not empty" 
``` 
drwx------. 5 xxx xxx 4.0K Jan 16 03:22 pd
```  
### What version of Go are you using (`go version`)? 

go version: go version go1.9.2 linux/amd64 

### What operating system and processor architecture are you using (`go env`)? 

os : CentOS Linux release 7.3.1611 (Core) 
kernel: 3.10.0-514.el7

### What did you expect to see?

I expect os.RemoveAll to delete all the files

### What did you see instead?

Sometimes the dir is not deleted and then an error is thrown. 

Thanks!

**Comment by ianlancetaylor** [comment]
Is it possible that some other goroutine, or some other process, is creating entries in the directory as you are trying to delete it?

**Comment by cwen0** [comment]
@ianlancetaylor you are true, I just found this problem, Thanks. Another process is using this dir. I delete this directory for the purpose of letting the program exit. When `os.RemoveAll` remove all other files in this dir and will exec `Remove(path)`， the process creates a new file in this dir to cause this error.   
@davecheney @ianlancetaylor Thanks.

**Comment by davecheney** [comment]
Thanks for confirming. Closing
