### ISSUE TITLE
misc/swig: installing macports swig on OSX causes all.bash to fail

### ISSUE THREAD

**Issue by martisch** [golang/go#23469]
tested on High Sierra 10.13.2 and Sierra 10.12.6 with go tip and swig installed from macports

replaced user names in some outputs:
### High Sierra Environment
go version devel +67fdf587dc Wed Jan 17 22:05:33 2018 +0000 darwin/amd64

go env
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/martisch/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/martisch/go"
GORACE=""
GOROOT="/Users/martisch/go-dev"
GOTMPDIR=""
GOTOOLDIR="/Users/martisch/go-dev/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b4/8plr28vn52v25w5tv_365z4800d4hw/T/go-
build713849379=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

swig -version
```
SWIG Version 3.0.12

Compiled with /usr/bin/clang++ [x86_64-apple-darwin17.0.0]

Configured options: +pcre
```

### What did you do?

install swig from macports: 
$ port install swig 

$./all.bash
```
...
##### ../misc/cgo/life

##### ../misc/swig/stdio
# _/Users/martisch/go-dev/misc/swig/stdio
:3: Error: Unable to find 'go.swg'
FAIL	_/Users/martisch/go-dev/misc/swig/stdio [build failed]
2018/01/18 14:30:34 Failed: exit status 2

##### ../misc/swig/callback
# _/Users/martisch/go-dev/misc/swig/callback
:3: Error: Unable to find 'go.swg'
callback.swigcxx:14: Error: Unable to find 'std_string.i'
FAIL	_/Users/martisch/go-dev/misc/swig/callback [build failed]
2018/01/18 14:30:35 Failed: exit status 2

##### ../misc/cgo/test
PASS
ok  	_/Users/martisch/go-dev/misc/cgo/test	1.119s
PASS
ok  	_/Users/martisch/go-dev/misc/cgo/test	1.124s
skipped due to earlier error
skipped due to earlier error
2018/01/18 14:30:52 FAILED
```

/cc @ianlancetaylor

**Comment by martisch** [comment]
ok found the workaround from @dr2chase in #22824:
```
sudo port install swig-go
```

Similar to notes by @dr2chase @laboger in #22824 to make the test more discriminative:
Any ideas how we can make this test more sensitive/informative so others do not have to find the workaround somewhere in the go issue tracker?

**Comment by ianlancetaylor** [comment]
Is there any difference in the output of `swig -version` or `swig -help` or `swig -go -help` if you don't  in stall the swig-go package?

Otherwise, if you run `swig -swiglib`, you should get a directory.  If you don't install the swig-go package, does that directory have a subdirectory named `go`?

**Comment by martisch** [comment]
```
$ swig -go -swiglib
/opt/local/share/swig/3.0.12
```

There is a go directory in /opt/local/share/swig/3.0.12 after installation of swig-go with macports but not before. Looking at "sudo port -v install -v swig-go" the swig-go installation mostly creates that directory including contents.

I have a go at crafting a CL that expands the test preconditions to take the above information into account when running on OSX.

**Comment by ianlancetaylor** [comment]
You'll want to edit `(*tester).hasSwig` in cmd/dist/test.go.  Thanks.

**Comment by ianlancetaylor** [comment]
(Don't worry about only testing on darwin, it would be reasonable to run the test on any GOOS.)
