### ISSUE TITLE
go 1.10 beta 2 test file access error

### ISSUE THREAD

**Issue by bhiestand** [golang/go#23465]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10beta2 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXXXXXXX\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\Users\XXXXXXXX\src\go
set GORACE=
set GOROOT=C:\opt\go
set GOTMPDIR=
set GOTOOLDIR=C:\opt\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXXXXXXX\AppData\Local\Temp\go-build526410426=/tmp/go-build -gno-record-gcc-switches

### What did you do?

go test -c

... sporadically shows this issue.  I am unable to determine a specific way to reproduce it.

### What did you expect to see?

Successful compilation.

### What did you see instead?
C:\Users\XXXXXXXX\AppData\Local\Temp\go-build709126526\b001\api.test.exe: The process cannot access the file because it is being used by another process.

**Comment by agnivade** [comment]
From the error, it seems unlikely that it's a Go specific error. Are you sure there is no other process accessing the file ? And does this issue not happen with 1.9.2 ?

**Comment by josharian** [comment]
I think @rsc changed the ETXTBUSY handling in 1.10, so this could definitely be a regression.

**Comment by alexbrainman** [comment]
> C:\Users\XXXXXXXX\AppData\Local\Temp\go-build709126526\b001\api.test.exe: The process cannot access the file because it is being used by another process.

Do you get this error message every time you run `go test -c`? Do you have more build log to show us?

What is you OS? Is that possible that you have antivirus program that try yo check api.exe as it gets built? What happens if you stop your antivirus program and try again?

Thank you.

Alex

**Comment by oiooj** [comment]
I also have the same problem. I met the error message `E:.loda-fs-detect: The process cannot access the file because it is being used by another process` when remove a file on Windows.

**Comment by LailaShreteh** [comment]
I have the same error :/ when try to remove temp dir which I do some processing files on it.

**Comment by agnivade** [comment]
Both are different issues. OP was seeing the issue during `go test -c`. You are getting the error message while removing some files. Ensure that you don't have any anti-virus program or anything else of that kind running . And please do a check with 1.9 version to ensure that this is a regression.

If you still see the issue, please file a new bug. Thanks.
