### ISSUE TITLE
Trying to check, if append works beyond initial capacity 

### ISSUE THREAD

**Issue by ninjaWithSuperHumanGifts** [golang/go#23481]
Please answer these questions before submitting your issue. Thanks!
-> Your Welcome ! :+1:  Hello, GO is awesome ! 

### What version of Go are you using (`go version`)?
-> $go version :+1: 
-> go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
-> I'm a new Go Programmer (Gopher). Only version i ever used is 1.9.2, i suspect this is the latest stable release.
-> I think i'm having trouble understanding the basic concepts of go and the issue i'm reporting might not be an issue, it may be a misunderstanding. But, i'm very much inspired/excited/interested in development using Go and development of Go (say, one day i'm able to contribute to Go in some way).

### What operating system and processor architecture are you using (`go env`)?
-> $go env :+1: 
[env.txt](https://github.com/golang/go/files/1645656/env.txt)

### What did you do?
-> I tried to understand "append function" and wrote a program to demonstrate.

If possible, provide a recipe for reproducing the error.
-> What recipe exactly, please specify if required ? 
-> I think this point is not applicable to this issue.
 
A complete runnable program is good.
-> sure :+1: 
-> complete runnable program -
![complete_program](https://user-images.githubusercontent.com/32152005/35140249-8d85740c-fd1c-11e7-86d2-a1cee6dad3e6.png)

A link on play.golang.org is best.
-> https://play.golang.org/p/FZMmu7uEccM

### What did you expect to see?
-> I want to know what i'm missing.
-> Is there any other way where i can discuss minor programs than reporting issues after 
referring to Documentation/Source Code
-> I'm open for suggestions to help me learn go better (any kind).
-> I thought cap and len would be equal (just before last NOTE print)

### What did you see instead?
-> A part of Program Output -
// ... 
len :  7 cap :  16
How come the capacity is more than length in this case ?
// .....

**Comment by Kyslik** [comment]
Post code instead of image mate.

**Comment by mvdan** [comment]
> Is there any other way where i can discuss minor programs than reporting issues after
referring to Documentation/Source Code

Yes - For questions about Go, see https://golang.org/wiki/Questions.
