### ISSUE TITLE
Import "github.com/abcd/xyz" is a program, not an importable package.

### ISSUE THREAD

**Issue by nikhilagrawal577** [golang/go#23483]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\ABC\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

I am trying to execute "GO TEST" in a folder where source code and test files are present.
I am using ginkgo here.

I found few people facing this error because "a non-main package cant import main package".
i made both as main package. Still getting this same error.

 
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Result of Test cases

### What did you see instead?

import "github.com/abcd/xyz" is a program, not an importable package.

**Comment by mvdan** [comment]
This bug report is lacking a way to reproduce the issue.

The problem here is likely because the package you're testing is importing a main package. The fix here is not to make both package main packages. The fix is to not import a main package, ever.

**Comment by nikhilagrawal577** [comment]
@mvdan I tried changing the name of the package (different than main).
If its a non-main package, it should be imported. But in my case, i got the same error.

**Comment by mvdan** [comment]
This is still lacking a way to reproduce the issue. I suggest you take this to one of the forums or mailing lists: https://github.com/golang/go/wiki/Questions

It can always be brought back as an issue in the tracker if you think this is a bug in Go. But without a way to tell or reproduce, this seems like a question more than a bug.
