### ISSUE TITLE
cmd/compile: duplicate error on operation with mismatched types

### ISSUE THREAD

**Issue by mvdan** [golang/go#23486]
### What version of Go are you using (`go version`)?

    go version devel +7e054553ad Tue Jan 16 15:11:05 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

https://play.golang.org/p/osxSXmoCG9N

### What did you expect to see?

    prog.go:4:15: invalid operation: true != 0 (mismatched types bool and int)

### What did you see instead?

    prog.go:4:15: cannot convert 0 to type bool
    prog.go:4:15: invalid operation: true != 0 (mismatched types bool and int)

The first error seems redundant, given the second. The second is also much clearer.

/cc @griesemer @mdempsky

**Comment by griesemer** [comment]
Not urgent.

**Comment by cuonglm** [comment]
@mvdan go1.15 now only print one error, we can close this issue.
