### ISSUE TITLE
x/image/font/gofont/gomedium: wrong shape for "l" letter

### ISSUE THREAD

**Issue by MichaelMonashev** [golang/go#23497]
### What version of Go are you using (`go version`)?
go version go1.8.3 windows/386

### Does this issue reproduce with the latest release?
I don`t know. I have not new os to install latest release. 

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\dev
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\1E86~1\AppData\Local\Temp\go-build017858111=/tmp/go
rd-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
Use golang.org/x/image/font/gofont/gomedium font for drawing.

Source code, that generate picture with wrong "l" letter shape: https://pastebin.com/eKaQJr0c
Picture: https://imagebin.ca/v/3ozP9RuDTh96

### What did you expect to see?
Perfect picture

### What did you see instead?
I see "l" letter with wrong shape.

**Comment by nigeltao** [comment]
Thanks for the bug report. I've passed it on to Bigelow & Holmes.

**Comment by duhok1** [comment]
Is there a rough ETA on a fix?

Also experiencing this with Go Medium letter "l" on Linux.

**Comment by nigeltao** [comment]
I'll poke Bigelow & Holmes again about it. If they're still busy, we (the Go team) may be able to issue our own fix to their fonts. I'll get back to you...

**Comment by barmadrid** [comment]
@nigeltao any response from Bigelow & Holmes on this?

**Comment by nigeltao** [comment]
They were busy, but have coincidentally become less so recently. We'll hopefully release a fix soon.

**Comment by barmadrid** [comment]
Hi @nigeltao just wondering if you are working on a fix anytime soon?

**Comment by nigeltao** [comment]
It would be B&H working on a fix. They were optimistic in February about finding some time but unfortunately COVID-19 ruined everyone's plans. I don't have a timeline. Sorry.

**Comment by barmadrid** [comment]
Hi @nigeltao Any progress on this yet?

**Comment by nigeltao** [comment]
I'll ask B&H again.
