### ISSUE TITLE
encoding/gob: mis-decodes pointers to int 0 to nil pointers

### ISSUE THREAD

**Issue by peterebden** [golang/go#23498]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pebers/go"
GORACE=""
GOROOT="/opt/tm/tools/go/1.9.2/usr/go"
GOTOOLDIR="/opt/tm/tools/go/1.9.2/usr/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="cc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build126697151=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
Round-tripped a struct with a pointer to an int with value 0 through gob (i.e. encoded then decoded).
e.g. https://play.golang.org/p/9LWD9cg04ni

### What did you expect to see?
Decoded struct has a pointer to int 0 and hence matches the original.

### What did you see instead?
Decoded struct has a nil pointer.

**Comment by ALTree** [comment]
gob doc:

> Pointers are not transmitted, but the things they point to are transmitted;

So you're encoding an `int` with value `0`,  not a pointer. You have to read the data back as `struct { int }`.

**Comment by ALTree** [comment]
see  #11119

**Comment by peterebden** [comment]
Thanks, I understand why that's the case, but it's surprising (to me at least) that gob doesn't round-trip the struct back to the same thing as the original. The obvious workaround indeed is to use another layer of struct, but while that's easy in this case, it'd have been nice not to have to work out why the two things weren't equivalant.

**Comment by ALTree** [comment]
It surely can be surprising but, as Rob noted in the old issue I linked above, changes to the gob model at this point are pretty unlikely and there's not much to do other that label this as `unfortunate`.
