### ISSUE TITLE
Round returns an int in a float64

### ISSUE THREAD

**Issue by Fale** [golang/go#23496]
As per documentation, the math.Round "returns the nearest integer" [1]. Why does it return it in a float? [2] Wouldn't make more sense to return it in an integer typed variable?

[1] https://github.com/golang/go/blob/61049394326c9c7424747801c136312ab72d0e07/src/math/floor.go#L58
[2] https://github.com/golang/go/blob/61049394326c9c7424747801c136312ab72d0e07/src/math/floor.go#L64

**Comment by dominikh** [comment]
The output of `math.Round` is most likely to be used with other functions in the math package, which all operate on floats. `math.Floor` exists for the same reason. It wouldn't be necessary if it returned `int`.

In the future, questions like these are best asked on one of the forums, see https://github.com/golang/go/wiki/Questions for more information.
