### ISSUE TITLE
x/net/html/atom: add "acronym" to 'extra' in gen.go

### ISSUE THREAD

**Issue by 16th-earl** [golang/go#23507]
### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
import "golang.org/x/net/html/atom"
atom.Acronym

### What did you expect to see?
Though the <acronym> tag is deprecated in HTML5, it was commonly used in [HTML4](https://www.w3.org/TR/1999/REC-html401-19991224/struct/text.html#edef-ACRONYM) and XHTML1. It should be one of 'extra' atom types, in the same way that atom.Strike and atom.Tt are still included.

### What did you see instead?
undefined: atom.Acronym

**Comment by namusyaka** [comment]
The `x/net/html` package implements an HTML5-compliant tokenizer and parser.
This package does not seem to officially support html-4 and xhtml.
