### ISSUE TITLE
defer recover()

### ISSUE THREAD

**Issue by wanglovesyang** [golang/go#23502]
It seems adopting "defer recover()" at the beginning of the function body won't hide any panic within the conducting of current function. Instead, 
defer func() {
    recover()
}()
will do the right job.

Any explanation?

**Comment by wanglovesyang** [comment]
Playground code can be found at https://play.golang.org/p/tLPkPQLuyW3

**Comment by davecheney** [comment]
Recover must be called _inside_ a defer function, not as the deferred function.

https://golang.org/ref/spec#Handling_panics

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

Closing as there is no bug to be addressed.
