### ISSUE TITLE
go1.9 does not properly process big integer

### ISSUE THREAD

**Issue by Codefor** [golang/go#23509]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build626720835=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

    package main

    import (
        "fmt"
    )

    func main() {
        var (
            a int64 = 83520398946977
            b int64 = 23200110818
            c int64 = 3600
        )

        //shows 3600, expected 3600
        fmt.Println(a / b)

        //shows 83520398944800, expected 83520398946977
        fmt.Println(b * c)

        //shows false, expected true
        fmt.Println(a == b*c)
    }

### What did you expect to see?
a = b*c

### What did you see instead?
a != b*c
c != a/b

**Comment by mvdan** [comment]
> shows 83520398944800, expected 83520398946977

Where did you get that "expected" value? I tried `calc` as well as Google and they both give 83520398944800.

This value is within the bounds of an int64, and these aren't really big ints, so I would be very surprised if Go was actually wrong here.

**Comment by randall77** [comment]
Yes, I would agree that your expectations are wrong.

**Comment by Codefor** [comment]
//shows 3600, expected 3600
    fmt.Println(a / b)

Here a/b = 3600, which c is 3600.So shouldn't b *c equals to a?

https://play.golang.org/p/1Y9wPCerkDd

@mvdan @randall77

**Comment by Codefor** [comment]
sorry，I see.

    a % b != 0

**Comment by mvdan** [comment]
Remember to use https://github.com/golang/go/wiki/Questions for questions - the issue tracker is just for bugs and proposals.
