### ISSUE TITLE
time: regression in Format

### ISSUE THREAD

**Issue by dsymonds** [golang/go#23505]
### What version of Go are you using (`go version`)?

go version devel +cd97aca3fd Mon Jan 1 03:45:23 2018 +0000 darwin/amd64

### Does this issue reproduce with the latest release?

`play.golang.org` (currently `go1.9.2`) does *not* show this issue.

### What did you do?

See https://play.golang.org/p/1VcPUlPk_3. Here's the relevant part:

```go
t := time.Date(2016, 8, 18, 16, 31, 33, 0, time.UTC)
fmt.Println(t.Format("20060102_1504"))
```

In previous versions of Go, and in the playground, it produces `20160818_1631`. In my dev version, it produces `20160818 83331`.

**Comment by dsymonds** [comment]
I just updated to tip, and it looks like it was already fixed.

**Comment by dsymonds** [comment]
Yep, 8776be1 broke it and 86cca11 fixed it.

**Comment by mvdan** [comment]
For completeness sake, this is a dup of #23259.
