### ISSUE TITLE
binary is crashing with errors : runtime: epollwait on fd 291 failed with 9 fatal error: runtime: netpoll failed

### ISSUE THREAD

**Issue by Durgababu** [golang/go#23517]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10beta2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
for building : ubutu 10 64-bit
running on centos 5.11 64-bit

### What did you do?
Creating service using github.com/kardianos/service

running binary as below
./binary-name agent install

`
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kardianos/service"
)

type program struct{}

func (p *program) Start(s service.Service) error {
	go p.run()
	return nil
}

func (p *program) Stop(s service.Service) error {
	return nil
}

func (p *program) run() {
}

func getCommandLineargs() (result []string) {
	var args []string = os.Args
	result = args[1:]
	return result
}

func main() {

	BinPath, _ := filepath.Abs(filepath.Dir(os.Args[0]))
	AgentPath := strings.Replace(BinPath, "/bin", "", -1)

	strCmdArg := getCommandLineargs()

	var serviceName, serviceAction string
	if len(strCmdArg) == 2 {
		serviceName = strCmdArg[0]
		serviceAction = strCmdArg[1]
	} else {
		fmt.Println("invalid arguments counts, arguments should be 2 ")
		os.Exit(0)
	}

	var sc = &service.Config{}

	switch serviceName {

	case "agent":
		sc.Name = "agent"
		sc.DisplayName = "agent"
		sc.Description = "Secure application for proactive manitanance and monitor remotely."
		sc.UserName = "sample"
		sc.Executable = AgentPath + "/agent"

	case "shield":
		sc.Name = "shield"
		sc.DisplayName = "shield"
		sc.Description = "Monitors the agent applications."
		sc.UserName = "sample"
		sc.Executable = BinPath + "/shield"

	default:
		fmt.Println("invalid service name")
		os.Exit(0)
	}

	prg := &program{}
	s, err := service.New(prg, sc)
	if err != nil {
		os.Exit(0)
	}

	switch serviceAction {

	case "install":
		s.Install()
		os.Exit(0)

	case "uninstall":
		s.Uninstall()
		os.Exit(0)

	case "start":
		s.Start()
		os.Exit(0)

	case "stop":
		s.Stop()
		os.Exit(0)

	case "restart":
		s.Restart()

	default:
		fmt.Println("invalid service action")
		os.Exit(0)
	}
}
`
### What did you expect to see?
creating a service using install option

### What did you see instead?

runtime: epollwait on fd 291 failed with 9
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x5d063e, 0x17)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x150c5d5e66f26000, 0x2b7700000000)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon(/sbin/init: invalid option -- -
Usage: init 0123456SsQqAaBbCcUu
)
        /usr/local/go/src/runtime/proc.go:4260 +0x424
runtime.mstart1(0x0)
        /usr/local/go/src/runtime/proc.go:1222 +0xe7
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1188 +0x76

**Comment by davecheney** [comment]
I'm very sorry but Go has never supported Centos/RedHat 5 as the kernel is below the minimum required version.

Closing: unfortunate.

**Comment by Durgababu** [comment]
We are using ubuntu 10 for building the binary and running the same binary in centos 5.11. Other sample binaries are working fine. Please check the error logs above once.

**Comment by davecheney** [comment]
The build host is not important. Go binaries are not supported on Centos 5 kernels irrespective of which operating system compiled them.

**Comment by Durgababu** [comment]
Hi davecheney,
But it is working fine in some 5.11 devices. In some devices only it is crashing.

**Comment by davecheney** [comment]
@Durgababu I'm sorry but Go is not supported on Centos 5 kernels. We cannot offer support when using Centos 5.

**Comment by davecheney** [comment]
https://github.com/golang/go/wiki/MinimumRequirements
