### ISSUE TITLE
x/crypto/ssh: Connections using "chacha20-poly1305@openssh.com" fail with "ssh: MAC failure"

### ISSUE THREAD

**Issue by mark-adams** [golang/go#23510]
### What did you do?

I work on an SSH server project for hosting Git repositories and we recently updated our `golang.org/x/crypto` to `a6600008915114d9c087fad9f03d75087b1a74df` to get support for the `chacha20-poly1305@openssh.com` cipher. During our testing, we discovered that our SSH sessions seem to fail when using `chacha20-poly1305@openssh.com`. Some of our internal users reported that short SSH commands didn't see the problem (i.e. commands that reply with a single line of text) but attempting to clone a repository over SSH would fail.

The server sees a `ssh: MAC failure` and the client sees `packet_write_wait: Connection to 10.192.25.108 port 22: Broken pipe`.

I'm using OpenSSH 7.4 (client) against a server running `golang.org/x/crypto` at a660000.

Failing logs from `ssh -vvv -c chacha20-poly1305@openssh.com`
[ssh-chacha20-poly1305.txt](https://github.com/golang/go/files/1652607/ssh-chacha20-poly1305.txt)

Successful logs from `ssh -vvv -c aes128-gcm`
[ssh-aes.txt](https://github.com/golang/go/files/1652606/ssh-aes.txt)

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build670065654=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you expect to see?
The SSH session did not fail.

### What did you see instead?
The SSH session failed. The client saw a disconnect error and the server saw a `ssh: MAC error`.

cc: @hanwen

**Comment by hanwen** [comment]
thanks for the report. Looking.
