### ISSUE TITLE
x/crypto: Repeats calls to terminal.ReadPassword causes scanner to produce "read /dev/stdin: The handle is invalid"

### ISSUE THREAD

**Issue by kettle11** [golang/go#23525]
### What version of Go are you using (`go version`)?
go1.9.1 windows/amd64

### Does this issue reproduce with the latest release?
I haven't tested this yet.

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\ikett\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
https://play.golang.org/p/zaYMheWt9fe

```
package main

import (
	"bufio"
	"fmt"
	"os"
	"syscall"

	"golang.org/x/crypto/ssh/terminal"
)

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	i := 0
	for {
		scanner.Scan()

		err := scanner.Err()
		if err != nil {
			fmt.Println(scanner.Err())
			return
		}

		fmt.Println("Test", i)
		i++
		terminal.ReadPassword(int(syscall.Stdin))
	}
}
```

Run this code and press enter about 30-60 times. Eventually the scanner produces the following error: read /dev/stdin: The handle is invalid.

In my actual project code this error occurred after fewer repetitions (3-4), but this minimum code set requires more repetitions for some reason.

### What did you expect to see?

I expected the scanner to continue to work and not produce an error.

### What did you see instead?

It produced " read /dev/stdin: The handle is invalid. " and stopped working.

**Comment by vcabbage** [comment]
I saw this question come up on Gopher's Slack and theorized that the use of `os.NewFile()` [here](https://github.com/golang/crypto/blob/3d37316aaa6bd9929127ac9a527abf408178ea7b/ssh/terminal/util_windows.go#L96) is causing a finalizer to be set and eventually closing stdin.

**Comment by kettle11** [comment]
I just verified vcabbage's hypothesis by manually calling runtime.GC() and the error immediately occurs after the first call to scanner.Scan() after terminal.ReadPassword and runtime.GC() are invoked.

Check out this new example code:

`package main

import (
	"bufio"
	"fmt"
	"os"
	"runtime"
	"syscall"

	"golang.org/x/crypto/ssh/terminal"
)

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	i := 0
	for {
		scanner.Scan()

		err := scanner.Err()
		if err != nil {
			fmt.Println(scanner.Err())
			return
		}

		i++
		terminal.ReadPassword(int(syscall.Stdin))
		runtime.GC()
	}
}`

**Comment by vcabbage** [comment]
Looks like this was broken in https://golang.org/cl/79335, which was a fix for #22828.

/cc @alexbrainman @mattn

**Comment by mattn** [comment]
Seems to be that the handle of STDIN is closed by GC. I'll send CL soon.

**Comment by alexbrainman** [comment]
@kettle11 does https://go-review.googlesource.com/#/c/crypto/+/89395/ fixes your problem?

Thank you.

Alex

**Comment by kettle11** [comment]
@alexbrainman @mattn I just applied and tested the fix locally and it works for me!

Thanks @mattn and @vcabbage for looking into it!

**Comment by alexbrainman** [comment]
> I just applied and tested the fix locally and it works for me!

Thanks for checking @kettle11 

Alex
