### ISSUE TITLE
cmd/compile: improve const expr if/else DCE

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#23521]
Suppose these two functionally identical definitions of `f`:
```go
func f1() T {
	if constX <= constY {
		return funcA() // cost(funcA) ~ 60
	} else {
		return funcB() // cost(funcB) ~ 60
	}
} // cost(f1) < 80

func f2() T {
	if constX <= constY {
		return funcA() // cost(funcA) ~ 60
	}
	return funcB() // cost(funcB) ~ 60
} // cost(f2) > 120 (or < 80 if condition is false)
```

`f1` can be inlined, but `f2` is only inlineable if `constX <= constY` is false.

The problem with `f1` is that it will trigger `go lint` warning (if block ends with a return statement, so drop this else and outdent its block).

Example of where it strikes: if you do a const-expression branching depending on the `bits.UintSize`, inlining may not happen if code does not follow exact pattern. And even if you know the pattern for `if/else`, it conflicts with `go lint`.

Related to https://github.com/golang/go/issues/17566.

This issue is only about pre-inlining DCE, which affects function cost.

I am going to link this issue in the upcoming CL that uses explicit else in this case to trigger dead code elimination before inlining.

Update: @josharian improved this change to also handle "else" branches,
so code like this stays inlineable as well:
```go
func f() {
	// Suppose deadcode sections contain panics or non-leaf calls.
	if !truth {
		// deadcode (eliminated before CL).
	} else {
		return // or panic
	}
	// deadcode (with this CL)
}
```

**Comment by Quasilyte** [comment]
If there is no objections, I would like to try solving this and send CL in near future (even though it's unlikely to be reviewed until 1.11).

**Comment by bradfitz** [comment]
@Quasilyte, go for it. The Go 1.11 tree opens soon (week?) anyway.

**Comment by Quasilyte** [comment]
This rule triggers few times during `$ ./make.bash` on linux/amd64.
Providing these cases for additional context.

```go
//=trigger= runtime/lfstack_64bit.go:41:6 lfstackUnpack
if GOARCH == "amd64" {
    return (*lfnode)(unsafe.Pointer(uintptr(int64(val) >> cntBits << 3)))
}
// Everything below is removed...

//=trigger= runtime/malloc.go:401:6 sysAlloc
// If using 64-bit, our reservation is all we have.
if sys.PtrSize != 4 {
    return nil
}
// Everything below is removed...

//=trigger= path/filepath/path.go:165:6 ToSlash
//=trigger= path/filepath/path.go:175:6 FromSlash
if Separator == '/' {
    return path
}
// Everything below is removed...

//=trigger= path/filepath/symlink.go:15:6 isRoot
if runtime.GOOS != "windows" {
    return path == "/"
}
// Everything below is removed...

//=trigger= path/filepath/symlink.go:29:6 isDriveLetter
if runtime.GOOS != "windows" {
    return false
}
// Everything below is removed...

//=trigger= math/big/float.go:353:6 validate
if !debugFloat {
    // avoid performance bugs
    panic("validate called but debugFloat is not set")
}
// Everything below is removed...

//=trigger= math/big/float.go:1179:6 validateBinaryOperands
if !debugFloat {
    // avoid performance bugs
    panic("validateBinaryOperands called but debugFloat is not set")
}
// Everything below is removed...
```
