### ISSUE TITLE
text/template: Documentation of block

### ISSUE THREAD

**Issue by gllmflndn** [golang/go#23520]
### What version of Go are you using (`go version`)?
[Current documentation](https://golang.org/pkg/text/template/#hdr-Actions): Build version go1.9.2.

### What did you see?
It is described that:
```
{{block "name" pipeline}} T1 {{end}}
```
is equivalent to:
```
{{define "name"}} T1 {{end}}
{{template "name" .}}
```

### What did you expect to see instead?
Shouldn't it be equivalent to:
```
{{define "name"}} T1 {{end}}
{{template "name" pipeline}}
```

**Comment by ysmolsky** [comment]
@gllmflndn documentation says:
```
{{block "name" pipeline}} T1 {{end}}
	A block is shorthand for defining a template
		{{define "name"}} T1 {{end}}
	and then executing it in place
		{{template "name" .}}
```
I think it is correct and does not require fixing.

**Comment by ysmolsky** [comment]
Thanks @gllmflndn !
