### ISSUE TITLE
http.Request.parseForm  gc too slow cause OOM?

### ISSUE THREAD

**Issue by djoylove** [golang/go#23527]
Please answer these questions before submitting your issue. Thanks!
when i use http.Request.parseForm() , i found the memory is grow too high and will not reduce after the request is over, finally it cause Out Of Memory issue?  how should i do to get rid of this? 
i try to remove the parseForm() line ,and the program work just fine.

### What version of Go are you using (`go version`)?
golang 1.9.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/1.9.1/libexec/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xiaod/workspace/php_work/wuxian/go_project"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n1/8k51kgd13fd8_k7d1yknfkhr0000gn/T/go-build910704619=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by mvdan** [comment]
This is a question, so please use https://github.com/golang/go/wiki/Questions.

I'm going to close this, as you did not use the issue template and this is lacking any information to see if there is a bug at all in Go.
