### ISSUE TITLE
problem for strings.Split()

### ISSUE THREAD

**Issue by IIInsomnia** [golang/go#23534]
if param `s` is an empty string,  the result of strings.Split() should be an empty slice. But not now.

eg:

```go
len(strings.Split("", ",")) // result: 1
```

**Comment by dominikh** [comment]
Working as intended, and clearly documented:

> If s does not contain sep and sep is not empty, Split returns a slice of length 1 whose only element is s.

Whether s itself is empty or not plays no role. This makes for a more robust API.
