### ISSUE TITLE
cmd/compile: type..eq function not generated

### ISSUE THREAD

**Issue by cherrymui** [golang/go#23546]
### What version of Go are you using (`go version`)?
tip (e72e69a3f6)

### Does this issue reproduce with the latest release?
Yes, reproducible with Go 1.9, but not with Go 1.8.

### What did you do?
https://play.golang.org/p/YoPVe0Td6KL
```
package main

func main() {
	a := f()
	println(a == f())
}

func f() [2]interface{} {
	var out [2]interface{}
	return out
}
```

This code does not build with Go tip:
```
$ go run x2.go 
# command-line-arguments
type..eq.[2]interface {}: call to external function
main.main: relocation target type..eq.[2]interface {} not defined
main.main: undefined: "type..eq.[2]interface {}"
```

It builds with Go 1.8 and gccgo.
```
$ go1.8 run x2.go 
true
$ go run -compiler=gccgo x2.go
true
```

**Comment by cherrymui** [comment]
If `[2]interface{}` is changed to `[0]interface{}` or `[1]interface{}`, it builds fine. It seems length >= 2 makes it fail.

**Comment by mvdan** [comment]
Not a regression in 1.10, so marking for 1.11.

**Comment by randall77** [comment]
Weird.  This works:
```
$ go build issue23546.go
$ ./issue23546
true
```
But this doesn't:
```
$ go run issue23546.go
```

**Comment by cherrymui** [comment]
Interesting.

This doesn't work:
```
$ go build -gcflags=-dwarf=false issue23546.go 
type..eq.[2]interface {}: call to external function
main.main: relocation target type..eq.[2]interface {} not defined
main.main: undefined: "type..eq.[2]interface {}"
```

`go run` invokes the compiler with DWARF disabled. So it seems when we skip DWARF, we skipped too much.
