### ISSUE TITLE
flag: PrintDefaults does not print default of "0" for String flags

### ISSUE THREAD

**Issue by spenczar** [golang/go#23543]
### What version of Go are you using (`go version`)?
go version go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64 

### What did you do?

https://play.golang.org/p/F1sa0z0p9V1:
```go
package main

import (
	"flag"
)

var (
	aaa = flag.String("aaa", "", "Set aaa")
	bbb = flag.String("bbb", "0", "Set bbb")
	ccc = flag.String("ccc", "1", "Set ccc")
)

func main() {
	flag.PrintDefaults()
}
```

### What did you expect to see?
```
  -aaa string
    	Set aaa
  -bbb string
    	Set bbb (default "0")
  -ccc string
    	Set ccc (default "1")
```

### What did you see instead?
```
  -aaa string
    	Set aaa
  -bbb string
    	Set bbb
  -ccc string
    	Set ccc (default "1")
```

This is fairly explicit in the relevant code, [`flag.isZeroValue`](https://golang.org/src/flag/flag.go#L382). The documentation says that "The parenthetical default is omitted if the default is the zero value for the type," but "0" is not the zero value of string.

**Comment by ianlancetaylor** [comment]
The handling of `"0"` dates back to https://golang.org/cl/7330 when the `isZeroValue` function was introduced.  It was preserved by https://golang.org/cl/23581 which added the reflect based code.

I would be OK with removing the switch.  It's not clear that it's needed any more.  CC @robpike

**Comment by robpike** [comment]
As Ian said, but I think in error, it's NOT clear that it's not needed any more. I do think it's safe to remove, though.

We can try it in 1.11 and see what breaks.
