### ISSUE TITLE
net/http: Request.WithContext should deep copy all pointer/map fields

### ISSUE THREAD

**Issue by taralx** [golang/go#23544]
Right now WithContext deep-copies URL only. At minimum, it should also deep-copy Headers for the same reason. For some reason the code distinguishes URL because it is "not a map", but maps are also pointer types.

**Comment by paranoiacblack** [comment]
Related to #20068, which added URL deep-copying.

**Comment by bradfitz** [comment]
Probably, but this is also getting a little sad in terms of copies/allocs.

It might be time for a new `NewRequest` constructor variant (`NewRequestContext`?) that takes a context. Currently all code that wants to make a request with contexts has to make their Request, and then copy/alloc everything again, just to set the context.

Unfortunately the name `NewRequestContext` isn't exactly beautiful.

**Comment by taralx** [comment]
Alternatively we could export the context. There's nothing special about it compared to the other mutable parts IMO.

Then add `Request.Clone()` and have proper separation of concerns.

**Comment by bradfitz** [comment]
> Alternatively we could export the context. There's nothing special about it compared to the other mutable parts IMO.

It was an explicit decision to make it unexported, so people don't shoot themselves in the foot. Russ described the problem in the original bug(s).

**Comment by tombergan** [comment]
I'm probably alone here: I am strongly opposed to turning `WithContext` into `Clone`. The vast majority of the time that I call `WithContext`, I don't need a deepy copy. If a deep copies are frequently needed, let's just add `Request.Clone`.

I also think https://golang.org/cl/41308 was a mistake. The CL description says "server.ServeHTTP mutates the request's URL", but net/http's server does not mutate `Request.URL` AFAIK. The original bug (#20068) is about net/http/httputil/reverseproxy and I think the change should have been restricted to that package.

**Comment by spf13** [comment]
ping @bradfitz @tombergan for decision

**Comment by bradfitz** [comment]
Punting to Go 1.12. But I think we do probably want to add a Clone and a new Context-accepting NewRequest. And maybe revert CL 41308.

But maybe this is all moot if we end up making a new http client interface. (#23707).

**Comment by odeke-em** [comment]
I am checking in here to remind myself to be involved with the decision to rollback CL 41308 which I authored but also to be involved in this conversation, for Go1.12

**Comment by rsc** [comment]
Punting to Go 1.13.

**Comment by drags** [comment]
@bradfitz I just came across `Clone` as a first time user of contexts within `net/http`. I had a question about this bit of documentation on `WithContext`:

> ...To change the context of a request (such as an incoming) you then also want to modify to send back out, use Request.Clone. Between those two uses, it's rare to need WithContext.

I wanted to ask if `Clone` should be preferred over `WithContext` in all situations. Specifically I'm writing a server middleware and only need to annotate a request (adding a logged in user) so it can be used by other handlers. 

Is `WithContext` not appropriate for this situation?

**Comment by bradfitz** [comment]
WithContext works there.
