### ISSUE TITLE
cmd/vet: false positive about recursive call to String method

### ISSUE THREAD

**Issue by octomarat** [golang/go#23550]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run `go vet` and `go run` on the following file:

```
package main

import "fmt"

type X string
func (x *X) String() string { return fmt.Sprint(">> ", &x) }

func main() {
	var x X = ""
	fmt.Println(x.String())
}
```

### What did you expect to see?

`go vet` reports no errors as program runs without problems, prints pointer address and exits normally.

### What did you see instead?

`go vet` reports `arg &x in Sprint call causes recursive call to String method`.

**Comment by mvdan** [comment]
This might be because, until recently, vet did not always have type information. Should be fairly easy to make the check precise.

**Comment by octomarat** [comment]
As far as I understand, check for print functions will be executed by default before tests in go 1.10. Check results will be treated as errors. Can this be a reason to fix this before 1.10 or, at least, disable the check for this particular case?

**Comment by mvdan** [comment]
That's a good point. Not a regression in vet, but could qualify as a regression in test. /cc @rsc

**Comment by mvdan** [comment]
Actually, I'm not 100% sure if fmt is right here. I know that the program does run, but I don't follow the logic as to why it doesn't crash with an infinite recursion. /cc @robpike

**Comment by jimmyfrasche** [comment]
@mvdan the address is taken twice (once implicitly then once explicitly) so it's a `**X` which has no method set

**Comment by robpike** [comment]
Vet should not complain here. The code is legal and should (and does) print the address of `x`, of type `**X`. The argument to `Sprint` has no method set.

**Comment by mvdan** [comment]
Thank you both. I do understand the double pointer - what still confuses me at times is what rules apply when a method of `*T` can be called on `T` (and vice versa). Thanks for confirming that the code is right before I looked into a fix.

**Comment by mvdan** [comment]
Indeed - the problem is that vet tracked only the types that had a `String() string` method declared on them, but it did not track whether the receiver in the method had a pointer type. With that extra information, we can now fix this false positive.
