### ISSUE TITLE
Why is "fmt" using the error interface when used with %v and %+v?

### ISSUE THREAD

**Issue by cvigo** [golang/go#23551]
### What version of Go are you using (`go version`)?
go1.9.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
https://play.golang.org/p/LiUkLY1e9c3

### What did you expect to see?
```
&{The Message 1 [a b c]}
&{Message:The Message Code:1 Details:[a b c]}
&main.MyError{Message:"The Message", Code:1, Details:[]string{"a", "b", "c"}}
&{The Message %!s(int=1) [a b c]}
```
### What did you see instead?
```
This is an error
This is an error
&main.MyError{Message:"The Message", Code:1, Details:[]string{"a", "b", "c"}}
This is an error
```

**Comment by ianlancetaylor** [comment]
This is working as documented.  Quoting https://golang.org/pkg/fmt/ :

> Except when printed using the verbs %T and %p, special formatting considerations apply for operands that implement certain interfaces. In order of application:
> ...
> 4. If an operand implements the error interface, the Error method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any).

Closing.

**Comment by cvigo** [comment]
I know is working as documented. Just wanted to point out that this makes sense for %s but at least not for %+v or %v (to my understanding)

Thanks anyway
