### ISSUE TITLE
cmd/vet: false positive about wrong argument for verb

### ISSUE THREAD

**Issue by octomarat** [golang/go#23552]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run `go vet` on the following file:

```
package main

import "fmt"

type T int

func (t T) String() string { return "t" }

func main() {
	fmt.Printf("%s", [1]T{0})
	fmt.Printf("%s", []T{0})
}
```

### What did you expect to see?

No errors.

### What did you see instead?

For the first line `go vet` reports `arg [1]T{0} for printf verb %s of wrong type: [1]main.T`. This is false positive as file executes normally and prints `[t][t]`.

**Comment by mvdan** [comment]
Thank you for taking the time to file these!
