### ISSUE TITLE
runtime: linux-mips-softfloat infinite loop before main() is called

### ISSUE THREAD

**Issue by jedisct1** [golang/go#23568]
### What version of Go are you using (`go version`)?

1.10rc1

### Does this issue reproduce with the latest release?

Yep

### What operating system and processor architecture are you using (`go env`)?

`GOOS=linux GOARCH=mips GOMIPS=softfloat`

### What did you do?

I compiled [github.com/jedisct1/dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) for `linux-mips-softfloat`.

I tried to run the resulting binary on OpenWRT/mips (CPU is a MIPS 74Kc V5.0, Qualcomm Atheros QCA9558).

The executable didn't even reach the `main()` function. RAM usage and CPU sage went to 500%. 

I replaced the `main()` function with one that just prints a Hello World. Same result.

### What did you expect to see?

Gorgeous log lines about DNS stuff.

### What did you see instead?

Not much.

**Comment by ALTree** [comment]
`softfloat` was introduced during the go1.10 cycle, so I'm tentatively putting this into the 1.10 milestone. 

cc @vstefanovic @cherrymui @aclements

**Comment by aclements** [comment]
Thanks for the report. Do you know if it reached an `init` function? What happens if you press Ctrl+\ (or send the process a SIGQUIT)?

**Comment by jedisct1** [comment]
Output after SIGQUIT : https://gist.github.com/c24d20cf070c3ae41587f07e29eb13b0

**Comment by jedisct1** [comment]
Ok, forget about it. Looks like the `github.com/kardianos/service` tries to execute `/sbin/init --version`, which is blocking on Busybox.

Unrelated to `softfloat` then. Sorry for the noise :(

**Comment by aclements** [comment]
No worries. Thanks for resolving!

**Comment by jedisct1** [comment]
Thanks for the Ctrl-`\` trick!
