### ISSUE TITLE
cmd/vet: false positive about wrong type in printf when struct with unexported field is printed

### ISSUE THREAD

**Issue by octomarat** [golang/go#23563]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.10rc1 darwin/amd64

### Does this issue reproduce with the latest release?

Not reproduced in the latest stable release (1.9.3), only in 1.10rc1

### What did you do?

Run `go vet` on the following file:

```
package main

import "fmt"

type unexportedError struct {
	e error
}

type errorer struct{ s string }

func (e errorer) Error() string { return "errorer" }

func main() {
	value := errorer{ s: "just field" }
	ue := unexportedError{ e: value }
	fmt.Printf("%s\n", ue)
}
```

### What did you expect to see?

No errors as file executes normally and prints `{{just field }}`.

### What did you see instead?

`go vet` reports `Printf format %s has arg ue of wrong type main.unexportedError`.

As `fmt` package doc states, `Error` method of `e` field cannot be used, as `e` is unexported. In this case, `fmt` just prints fields.

As far as I can see in `go vet` source code, it reports error if field has `Error` method but it is unexported. But the fact that `e` can be printed without `Error()` method invocation is not taken into account.

**Comment by mvdan** [comment]
This seems to be related to unexported interface fields - this is a smaller reproducer:

```
package main

import "fmt"

type T1 struct {
        t2 interface{}
}

func main() {
        v := T1{"foo"}
        fmt.Printf("%s\n", v)
}
```

**Comment by ianlancetaylor** [comment]
I'm going to redirect this to 1.10 because with 1.10 this occurs when running `go test` as well as when running `go vet`.

**Comment by mvdan** [comment]
@ianlancetaylor please see all the other recent vet issues that OP raised. These could all be considered regressions in 1.10, given how vet is now run as part of test. I have sent CLs for 4 of these already.

**Comment by ianlancetaylor** [comment]
As I more or less said on the CL, I'm not yet convinced that this is a bug.  The right way to print a value of type `error` is to call the `Error` method.  It's true that in this case fmt does the best it can and just prints the value, but I think that is not what people would reasonably expect.  People would reasonably expect a call to the `Error` method.  So this does seem worthy of a vet warning.

CC @robpike @martisch for other opinions.

**Comment by mvdan** [comment]
@ianlancetaylor you may be right. However, note that my CL affects all interfaces, not just error and fmt.Stringer. Perhaps the CL should keep the warning for those types.

**Comment by ianlancetaylor** [comment]
@mvdan Is that not how it works today?

**Comment by mvdan** [comment]
@ianlancetaylor not exactly - see my full example in https://github.com/golang/go/issues/23563#issuecomment-361209668. The `t2 interface{}` field gets flagged, when the user couldn't reasonably expect `String() string` or `Error() string` to be present.

So I agree that OP's example is working as intended (even if the program technically works), but I think that the current heuristic is too aggressive. It should only cover types that we know to have `String` or `Error`.

**Comment by ianlancetaylor** [comment]
Thanks, that sounds reasonable.  I guess we should also warn about uncallable `Format` and `GoString` methods.
