### ISSUE TITLE
Delayed output flushing for t.Errorf() makes debugging failures difficult in tests.

### ISSUE THREAD

**Issue by michaelsafyan** [golang/go#23567]
It appears that t.Errorf() doesn't actually write or flush the output to stderr/stdout until the completeion of the test. This is problematic if there are interleaved log-lines in the code invoked between t.Errorf() calls, since it is then impossible to see which logs belong to which assertion (since all of the assertion failures appear after the debug output associated with different test assertions).

**Comment by ALTree** [comment]
This is a dup of #23213  (`Errorf`, under the hood, just calls `Logf`). Closing this in favour of the older thread.
