### ISSUE TITLE
os: document that StartProcess inherits the caller's thread state

### ISSUE THREAD

**Issue by aclements** [golang/go#23570]
One of the new features of the Go 1.10 runtime is that `LockOSThread` can be used to reliably modify OS thread state. One of the main points of doing this was to make it possible to start a new process with a modified thread state, but right now we don't document that new processes created with, e.g., `os.StartProcess` will actually inherit the caller's thread state. This has [led to confusion](https://github.com/golang/go/issues/20395#issuecomment-360810662) and we should document this.

**Comment by aclements** [comment]
Re-opening for cherry-pick to 1.10 release branch.

**Comment by ianlancetaylor** [comment]
At the moment everything checked into the master branch is going to be cherry picked over to the release branch.  The master branch is not yet open for general changes.  So there is no need to keep this issue open for that purpose.

(That said, you might want to check that the release notes seem clear on this point.)

**Comment by aclements** [comment]
Okay. I'll close the issue.

> (That said, you might want to check that the release notes seem clear on this point.)

The exec behavior isn't actually changing; we're just guaranteeing that we'll keep doing what we're doing now. The release notes point to the changes to `LockOSThread`, which I think is enough (though I could be convinced otherwise).
