### ISSUE TITLE
unexpected fault address 0x7eff812df3ec

### ISSUE THREAD

**Issue by jingjing-wang** [golang/go#23581]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

### Does this issue reproduce with the latest release?
not sure.

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?
Enter the following.
go get golang.org/x/tour/gotour

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Nothing. 

### What did you see instead?
unexpected fault address 0x7eff812df3ec
fatal error: fault
[signal 0xb code=0x2 addr=0x7eff812df3ec]

goroutine 8 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [select]:
main.$nested27
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/http.go:57
main.httpsOrHTTP
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/http.go:65
main.repoRootForImportDynamic
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/vcs.go:498
main.repoRootForImportPath
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/vcs.go:362
main.downloadPackage
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/get.go:269
main.download
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/get.go:166
main.runGet
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/get.go:72
main.main
	/build/gccgo-go-6budhK/gccgo-go-1.2.1/src/cmd/go/main.go:161

goroutine 3 [syscall]:
	goroutine in C code; stack unavailable

goroutine 6 [chan receive]:

goroutine 7 [select]:
wjj@wjj-ThinkPad-X230:~/go/bin$ go get golang.org/x/tour/gotourgo get golang.org/x/tour/gotour
package golang.org/x/tour/gotourgo
	imports golang.org/x/tour/gotourgo
	imports golang.org/x/tour/gotourgo: cannot find package "golang.org/x/tour/gotourgo" in any of:
	/usr/src/pkg/golang.org/x/tour/gotourgo (from $GOROOT)
	/home/wjj/go/src/golang.org/x/tour/gotourgo (from $GOPATH)
package golang.org/x/tour/gotourgo
	imports get: unrecognized import path "get"
wjj@wjj-ThinkPad-X230:~/go/bin$ go get golang.org/x/tour/gotour
# golang.org/x/net/websocket
../src/golang.org/x/net/websocket/dial.go:18:19: error: reference to undefined identifier ‘tls.DialWithDialer’
   conn, err = tls.DialWithDialer(dialer, "tcp", parseAuthority(config.Location), config.TlsConfig)
                   ^
# golang.org/x/tools/imports
../src/golang.org/x/tools/imports/imports.go:269:4: error: reference to undefined field or method ‘Buffer’
  sc.Buffer(nil, maxScanTokenSize)
    ^

**Comment by ianlancetaylor** [comment]
You are running a very old version of gccgo, 4.9.3.  The current released version of gccgo is 7.3.  It seems to work fine today.  Closing because we can't support such an old release.
