### ISSUE TITLE
question: slow (to compile?) on Windows with Go 1.9.3

### ISSUE THREAD

**Issue by guppythegod** [golang/go#23583]
VERSION : 1.9.3

This problem does reproduce with the latest release
.
OS AND HARDWARE : Windows 10 AMD64

Im not sure why my go code is taking 8 or more seconds in run-time, for every file I have. I just installed the latest version (1.9.3), and a couple days ago my code was running at speeds that it should've been running at. The file im using for this example is just a generic `hello.go` file with this code:

```
package main

import "fmt"

func say(){
	fmt.Println("Hello")
}

func main(){
	say()
}
```

It shouldn't be taking 8 seconds to compile and run. Is there a fix to this problem? Is there something on my PC that might be slowing golang down?

Thank you.

**Comment by davecheney** [comment]
How did you install go 1.9.3? Reports of this nature are often traced to a corrupt Go installation.

Of course, if you’re using Windows, someone is going to tell you to disable your virus checker, so you should probably check that.

**Comment by bradfitz** [comment]
We need more information.

What is slow?

How are you compiling/running the program?

When are you measuring from?

What is the output if you add the `-x` flag to `go install` or `go build` or `go run`?

Have you tried Go 1.10rc1?

Do you have anti-virus installed?

**Comment by mdcnz** [comment]
Looks like [this](https://stackoverflow.com/questions/48480493/google-sheets-being-slow-in-golang) is the original stackoverflow question.

**Comment by guppythegod** [comment]
Im so sorry for not replying, I did some checks and turns out this is a result of an improper installation and something isnt working right with the tool chain

**Comment by guppythegod** [comment]
This issue can be closef
