### ISSUE TITLE
reflect.DeepEqual returns false for equal slice with two elements in different order

### ISSUE THREAD

**Issue by wgliang** [golang/go#23597]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wangguoliang/Documents/mos"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zd/20dl0mb523v4tjk_pf_hdscr0000gn/T/go-build586347653=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Does this issue reproduce with the latest release?

Yes
### What did you do?

I want to check two slice.
`
package main

import "fmt"

import "reflect"

func main() {
	a :=[]string{"name3","name4","name1","name2"}
	b :=[]string{"name1","name2","name3","name4"}
	fmt.Println(reflect.DeepEqual(a,b))
}
`

### What did you expect to see?
true

### What did you see instead?
false

**Comment by cznic** [comment]
The slices are not equal, this is working as intended.

**Comment by mvdan** [comment]
As @cznic said, order matters in arrays and slices.
