### ISSUE TITLE
mojibake in the golang-nuts description on google groups

### ISSUE THREAD

**Issue by davecheney** [golang/go#23596]
![screen shot 2018-01-29 at 2 00 39 pm](https://user-images.githubusercontent.com/7171/35491792-e2c5cb32-04fc-11e8-81b2-0a9015c45d87.png)

**Comment by bradfitz** [comment]
Fixed.

**Comment by mikioh** [comment]
Also golang-dev?

**Comment by bradfitz** [comment]
Done.
