### ISSUE TITLE
crypto/tls: X509KeyPair cannot parse OpenSSL generated ECDSA keys

### ISSUE THREAD

**Issue by chandra-ghub** [golang/go#23591]
Please answer these questions before submitting your issue. Thanks!

I am trying to get go's standard `tls` package accept my openssl generated keys (Prime 256 curve ECDSA). Generated key and cert using OpenSSL - 

```
# openssl ecparam -name prime256v1 -genkey -noout -out priv.pem -param_enc explicit
# openssl req -new -x509 -key priv.pem -out EC_server.pem -days 365
```

### What version of Go are you using (`go version`)?
Tested with 1.9 and on play.golang.org too.
https://play.golang.org/p/V9GzXsn1zoG (copied the function X509KeyPair() to be able to debug)
https://play.golang.org/p/22G1XNbU8at (direct call to the library)

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MACOS High Sierra

### What did you do?
here you go -
https://play.golang.org/p/V9GzXsn1zoG with the library copied to debug the error
https://play.golang.org/p/22G1XNbU8at (without go's library code)

### What did you expect to see?
A `&tls.Certificate{}` to have returned.

### What did you see instead?
`failed to parse private key` error from private function parsePrivateKey() in tls.go library.

**Comment by odeke-em** [comment]
Thank for reporting this issue @chandra-ghub.

Seems like the certificate centric version of this bug is https://github.com/golang/go/issues/21502, but am not sure.

I'll tag some crypto folks @agl @titanous @FiloSottile

**Comment by agl** [comment]
Drop this: `-param_enc explicit`

It causes OpenSSL to encode P-256 as if it were a random, arbitrary curve rather than specifying P-256 itself. The default (`named_curve`) is correct.

(For more details, see [the OpenSSL documentation](https://www.openssl.org/docs/man1.0.2/apps/ecparam.html).)

**Comment by FiloSottile** [comment]
As https://github.com/golang/go/issues/21502#issuecomment-323400475 says, `-param_enc explicit` is not legal for TLS certificates anyway.

I looked into making the error message more useful like in #21502 (which is indeed the same issue but with certificates) but `parsePrivateKey` does trial decryption of 3 formats, so we would have to guess at which is an error and which is a mismatch. I don't love that.

What we can do is move certificate parsing, which has more useful error messages, above private key parsing in `X509KeyPair`. I'll CL that.

**Comment by chandra-ghub** [comment]
thanks @agl and @FiloSottile for your time. Can confirm that dropping `-param_enc explicit` from openssl's flags does the trick - https://play.golang.org/p/dwuZXdlk7nM

Appreciate your acute diligence on the error messages, makes life so much easier for `tls` users going forward.
