### ISSUE TITLE
x/tools/cmd/stringer: warn or fail when multiple names have the same value

### ISSUE THREAD

**Issue by ecc1** [golang/go#23592]
When constant values of a type are declared in separate files, it's difficult to detect whether one has assigned the same value to more than one name.  The stringer command would be an ideal place to detect this, and issue at least a warning, or even fail (since one could argue that the String method is not well-defined for that value).

**Comment by robpike** [comment]
It's reasonable to have multiple values for a given constant, as the example in the command documentation states:

```
For example, given this snippet,

    package painkiller

    type Pill int

    const (
    	Placebo Pill = iota
    	Aspirin
    	Ibuprofen
    	Paracetamol
    	Acetaminophen = Paracetamol
    )
```

I think it would be a mistake, a category error, to have `stringer` become a diagnostic and analysis tool. It blurs its purpose, which is just to make it easy to print names of constants, not to check the correctness of your program.
