### ISSUE TITLE
cmd/vet: false positive about unrecognized printf flag '0'

### ISSUE THREAD

**Issue by octomarat** [golang/go#23598]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

o1.9.3 darwin/amd64

### What did you do?

Run `go vet` on the following file:

```
package main

import "fmt"

func main() {
	fmt.Printf("%08t", false)
}
```

### What did you expect to see?

No errors are reported as '0' flag is valid for 't' verb. Program prints `000false`, zeros are used for padding instead of spaces.

### What did you see instead?

`vet` reports `unrecognized printf flag for verb 't': '0'`.

**Comment by robpike** [comment]
I see a couple of problems in there.

**Comment by mvdan** [comment]
@robpike could you elaborate?

**Comment by octomarat** [comment]
Hm... `fmt` documentation states that: 
`Flags are ignored by verbs that do not expect them. For example there is no alternate decimal format, so %#d and %d behave identically.`
But `go vet` reports unrecognized flags as error. It this even correct? I understand that removing such redundancies from a source code is a good think. But what about `go vet` executed before tests in Go 1.10?

**Comment by octomarat** [comment]
Speaking about other problems of '0' flag processing by `go vet`.
```
fmt.Printf("%020p \n", &[]int{})
fmt.Printf("%020T \n", false)
fmt.Printf("%020U \n", 1234)
```
In all these cases '0' affects print result, but is reported by `go vet` as unrecognized.

**Comment by ianlancetaylor** [comment]
This does not seem like unreasonable `go vet` behavior to me.  The code is almost certainly mistaken even if fmt carries on as best it can.

**Comment by dolmen** [comment]
Here is an additional test case using fmt.Formatter to let you decide what should be the bahaviour of "go vet":
```go
package main

import (
	"fmt"
)

type t struct{}

func (_ t) Format(f fmt.State, c rune) {
	if f.Flag('0') {
		f.Write([]byte("GA"))
	} else {
		f.Write([]byte("BU"))
	}
}

func main() {
	fmt.Printf("%0s\n", t{})
}
```

**Comment by robpike** [comment]
https://go-review.googlesource.com/c/go/+/90695 was supposed to mention this issue but got the issue number wrong.

**Comment by ianlancetaylor** [comment]
Fixed by https://golang.org/cl/90695.
