### ISSUE TITLE
gccgo: go/build.Import(..., "archive/zip") doesn't work

### ISSUE THREAD

**Issue by tamird** [golang/go#23607]
This seems to affect all standard library packages since sources appear not to be shipped in gccgo.

### What version of Go are you using (`go version`)?
```
go version go1.10beta2 gccgo (GCC) 8.0.1 20180126 (experimental) linux/amd64
```
### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tduberstein/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tduberstein/local/go"
GORACE=""
GOROOT="/home/tduberstein/local/gcc/gcc"
GOTMPDIR=""
GOTOOLDIR="/home/tduberstein/local/gcc/gcc/libexec/gcc/x86_64-pc-linux-gnu/8.0.1"
GCCGO="/home/tduberstein/local/gcc/gcc/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build113750874=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
```

### What did you do?
cd $(go env GOPATH)/src/github.com/cockroachdb/cockroach
make test PKG=./pkg/cmd/cockroach-oss TESTS=TestNoLinkForbidden

### What did you expect to see?
Passing tests.

### What did you see instead?
```
--- FAIL: TestNoLinkForbidden (0.01s)
        build.go:76: cannot find package "archive/zip" in any of:
                        /usr/local/home/tduberstein/go/src/github.com/cockroachdb/cockroach/vendor/archive/zip (vendor tree)
                        /home/tduberstein/local/gcc/gcc/src/archive/zip (from $GOROOT)
                        /usr/local/home/tduberstein/go/src/archive/zip (from $GOPATH)
FAIL
FAIL    github.com/cockroachdb/cockroach/pkg/cmd/cockroach-oss  0.396s
make: *** [test] Error 1
```

**Comment by ianlancetaylor** [comment]
Unfortunately, in general this can not work with gccgo, because, as you say, gccgo does not include sources.  I'm open to argument but my inclination is to just close this as unfortunate.

**Comment by tamird** [comment]
Seems worse than unfortunate for `go/build` to not work for the standard library in gccgo. Is there a workaround?

**Comment by ianlancetaylor** [comment]
Try setting the `GOROOT` environment variable to point to a gc installation, which has the sources.

**Comment by tamird** [comment]
Yeah, that works.

**Comment by ianlancetaylor** [comment]
Closing as unfortunate.

**Comment by tamird** [comment]
@ianlancetaylor setting `GOROOT` to a gc installation doesn't work because some packages are different in gccgo:
```
cd $GOPATH/src/golang.org/x/sys/unix
go build honnef.co/go/tools/cmd/staticcheck
GOROOT=$(go1.10 go env GOROOT) ./staticcheck 
/home/tduberstein/local/go/src/golang.org/x/sys/unix/gccgo.go:21:2: Entersyscall not declared by package syscall
```

**Comment by ianlancetaylor** [comment]
I believe the state of "closing as unfortunate" is still the correct state for this issue.
