### ISSUE TITLE
Clarify meaning of mixed caps

### ISSUE THREAD

**Issue by fulldecent** [golang/go#23600]
In https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps, reference is made to mixed caps. As currently written, this leaves room for interpretation. Please clarify which of the following is preferred:

* xmlHttpRequest
* XMLHTTPRequest
* xmlHTTPRequest

**Comment by dominikh** [comment]
Is the existing documentation at https://github.com/golang/go/wiki/CodeReviewComments#initialisms not sufficient?

**Comment by fulldecent** [comment]
The definition for mixed caps is just:

> See https://golang.org/doc/effective_go.html#mixed-caps. This applies even when it breaks conventions in other languages. For example an unexported constant is maxLength not MaxLength or MAX_LENGTH.

and, by the URL reference:

> Finally, the convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword names.

The initialisms note is:

> Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case. For example, "URL" should appear as "URL" or "url" (as in "urlPony", or "URLPony"), never as "Url". Here's an example: ServeHTTP not ServeHttp.

---

So parsing this, I think: 

    # Step one: no casing

    xmlhttprequest
    --------------

    # Step two: mixed case rule says:
    xmlHttpRequest
    ---*---*------

    # Step three: initialism rule says to fix violation in word two:
    xmlHTTPRequest
    ----***-------

---

If this is correct, great, I think think this example would be good to put in the wiki (just the result).

**Comment by bradfitz** [comment]
Done: https://github.com/golang/go/wiki/CodeReviewComments/_compare/4434a5a7a148314500692797fed50c05a5f42b48...155654e370e17feb0d6bb654f38d6eca3ae5a102

**Comment by fulldecent** [comment]
Thank you!
