### ISSUE TITLE
gccgo: runtime/caller inconsistency

### ISSUE THREAD

**Issue by tamird** [golang/go#23608]
Seems that gccgo returns the caller's package with all periods and slashes replaced with underscores.

Here's the failing test: https://github.com/cockroachdb/cockroach/blob/ea613ef18b847a28c40d7cc930b2aba3e3a1eb60/pkg/util/caller/resolver_test.go#L52.

**Comment by tamird** [comment]
Other tests in that package also fail - gccgo seems to report different line numbers.

**Comment by ianlancetaylor** [comment]
It's simply not possible for gccgo to act precisely like the gc compiler in every single case.

If there are specific problems, I can look into fixing them.  But a general complaint of inconsistency can not easily be addressed.

Yes, it's true that the names returned by `runtime.Callers` are not identical.  You've found only one example.  They will be even more different if you do things like call `runtime.Callers` from a nested function literal.

**Comment by tamird** [comment]
It might be useful to export a constant delimiter for package paths so that downstream can use it instead of having to implement their own build-time switching.

**Comment by tamird** [comment]
In gc, the package path is .e.g. "github.com/foo/bar/baz"; in gccgo, the package path is e.g. "github_com_foo_bar_baz".

**Comment by ianlancetaylor** [comment]
Yes, that is true.  But I'm still not sure what you mean.

(It works this way because gccgo is constrained to emit symbol names permitted by the system assembler; gc, which does not use the system assembler, is not.)

**Comment by tamird** [comment]
Right; what I'm saying is that currently, in my code, I have to use build tags and my own constant (`"/"`/`"_"`) and string replacement logic `s/\./_/g` to deal with these differences; my suggestion above is that the standard library (perhaps the "runtime" package) expose this difference somehow.

**Comment by ianlancetaylor** [comment]
There are other Go implementations besides the gc and gccgo toolchains, and there will be more in the future.  I don't think we want to pin down the current logic in a runtime function.  Especially since there actually is no unambiguous translation.

If your tests require that `runtime.Callers` return exact strings, then skip the tests if `runtime.Compiler != "gc"`.  Or adjust the tests to be more flexible.

**Comment by tamird** [comment]
@ianlancetaylor it's not just tests - we have code that tries to trim some of the leading import path components. Anyway, I was able to adjust it to deal with the differences - I was only suggesting that exposing the inconsistency via some explicit implementation-specific facilities.

**Comment by ianlancetaylor** [comment]
At this point I don't see a reasonable way to do that.  Closing as unfortunate.
