### ISSUE TITLE
function passed by value cause unreasonable goroutine blocked(random)

### ISSUE THREAD

**Issue by vzex** [golang/go#23612]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.2 linux/386 |  go1.9.3 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux and windows

### What did you do?
```
package main

import (
        "time"
        "sync"
        "log"
)
type _time struct {
        time.Time
        sync.RWMutex
}

func (t _time) now() time.Time {
        t.RLock()
        n := t.Time
        t.RUnlock()
        return n
}


var timen _time
func f(j int, c chan struct{}) {
        for i := 1; i<=1000;i++{
                println(j, i, timen.now().Unix())
                time.Sleep(time.Millisecond*100)
        }
        go func() {c<-struct{}{}}()
}
func main() {
        t := time.Tick(time.Second)
        go func() {
                for _ = range t {
                        timen.Lock()
                        timen.Time = time.Now()
                        timen.Unlock()
                }
        }()
        t2 := time.NewTicker(time.Second * 15)
        defer func() {
                t2.Stop()
        }()
        go func() {
                for {
                        select {
                        case <-t2.C:
                                log.Println("begin check")
                                log.Println(timen.now().Unix())
                                log.Println("end check")
                        }
                }
        }()

        c := make(chan struct{})
        n := 300
        for i:=1; i<= n;i++ {
                go f(i, c)
        }
        f(0, c)
        for i := 0;i <=n;i++ {
                <-c
                println("recv", i)
        }
}

```

### What did you expect to see?
after about 100 seconds later, the program should quit normally. with the finally output 
`recv 300`

### What did you see instead?
`recv 296
recv 297
recv 298
2018/01/30 16:37:02 begin check
2018/01/30 16:37:02 1517301422
2018/01/30 16:37:02 end check
2018/01/30 16:37:17 begin check
2018/01/30 16:37:17 1517301437
2018/01/30 16:37:17 end check
`
and never quit

the result is random, normally all the goroutines should quit, but sometimes, one or two goroutines are just blocked, i did't check which line is blocked( t.RLock() or  t.RUnlock() I guess), but if I impl the code like this : (pass func argument by reference)
```
func (t *_time) now() time.Time {
        t.RLock()
        n := t.Time
        t.RUnlock()
        return n
}


var timen *_time
func f(j int, c chan struct{}) {
        for i := 1; i<=1000;i++{
                println(j, i, timen.now().Unix())
                time.Sleep(time.Millisecond*100)
        }
        go func() {c<-struct{}{}}()
}
func main() {
        timen = &_time{}
...
```
everything just work fine

**Comment by AlexRouSg** [comment]
https://golang.org/pkg/sync/#RWMutex

> An RWMutex must not be copied after first use.

By using a pass by value function, you are creating a copy of _time and thus a copy of sync.RWMutex. So either only use pass by pointer functions or use a pointer to a sync.RWMutex. The latter being the safer option.

**Comment by vzex** [comment]
@AlexRouSg thanks, understand now.
