### ISSUE TITLE
Build binary with wrong code

### ISSUE THREAD

**Issue by sah4ez** [golang/go#23618]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.9 linux/amd64
```

### Does this issue reproduce with the latest release?
Sorry, can't check on the latest release.

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sah4ez/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build569612487=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
I'm import and using my library from own repository.
Library contains the code:
```go
type Instance struct {
    msg chan string
    zmsSub *zmq.Socket
}
//....
func (in *Instance) Messages() <-chan string {
	for {
		message, err := in.zmqSub.Recv(0)
		if err != nil {
                     continue
                }
		in.msg <- message
	}
}
```
And using this method in this code:
```go
	for msg := range s.dt.Messages() {
                process(msg)
		runtime.Gosched()
	}

```

### What did you expect to see?
Expected fail to build and message that missing return.

### What did you see instead?
Binary file successful build and run.

### Example
[Playground](https://play.golang.org/p/hbBz4dw-4Xq)

**Comment by ianlancetaylor** [comment]
I'm not sure I understand, but I think that you are saying that compiling your `func (in *Instance) Messages() <-chan string` does not give an error message for a missing return statement.  That is working as expected: that function never terminates, so there is no need for a return statement.  This is described in the language spec at https://golang.org/ref/spec#Terminating_statements .

Closing as working as expected.

**Comment by sah4ez** [comment]
But I expected that `Messages()` function return `<-chan string`.
For example:
```go
func Message() string {
    fmt.Println("message")
}
```
This code don't build and not run. Because missing return statment.
And what the different between: 
```go
func Message() string {
    fmt.Println("message")
    for { }
}
```
And this code is valid? But I expected returned string too.

**Comment by bradfitz** [comment]
@sah4ez, you'll have to adjust your expectations after reading the link above, https://golang.org/ref/spec#Terminating_statements .

And note also:

https://golang.org/ref/spec#Function_declarations

Which says:

> If the function's signature declares result parameters, the function body's statement list must end in a terminating statement.

**Comment by ianlancetaylor** [comment]
> Or not terminating a function has highest priority above function with declares result parameters without terminating statement?

Basically, yes.  Consider, for example, a set of functions in `[]func() int`, where some of them need not return.  Or consider `interface { M() int }` where some implementations of `M` need not return.
