### ISSUE TITLE
syscall: wrong Dirent struct on mips64le

### ISSUE THREAD

**Issue by rfjakob** [golang/go#23624]
The maintainer of the Debian package just reported that gocryptfs is broken on mips64le: https://github.com/rfjakob/gocryptfs/issues/200 . The reason seems to be that `syscall.Dirent` does not match the used `getdents` syscall. Analysis below:

On mips64le, `getdents` is used instead of `getdents64`: https://github.com/golang/go/blob/bcc86d5f42fddc2eca1bb066668388aa6807c38c/src/syscall/syscall_linux_mips64x.go#L13
```
	_SYS_getdents  = SYS_GETDENTS
```

And `getdents` returns `linux_dirent`, which defined in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/readdir.c?h=v4.15#n147 :
```
struct linux_dirent {
	unsigned long	d_ino;
	unsigned long	d_off;
	unsigned short	d_reclen;
	char		d_name[1];
};
```

In Go mips64le, syscall.Dirent is defined here https://github.com/golang/go/blob/bcc86d5f42fddc2eca1bb066668388aa6807c38c/src/syscall/ztypes_linux_mips64le.go#L133 :
```
type Dirent struct {
	Ino       uint64
	Off       int64
	Reclen    uint16
	Name      [256]int8
	Type      uint8
	Pad_cgo_0 [5]byte
}
```
And this looks wrong, because it has a `Type` field, which the the `linux_dirent` struct has not.

**Comment by ianlancetaylor** [comment]
Hmmm, I can't  find a github user ID for the original Go author, Yao Zhang <lunaria21@gmail.com>.

CC @minux

**Comment by rfjakob** [comment]
PS: I believe this only affects people who parse the `Getdents` output themselves. gocryptfs does for performance, so does https://github.com/golang/tools/blob/master/imports/fastwalk_unix.go , but probably not much else. The fix for gocryptfs will be to switch over to `unix.Getdents` from `x/sys/unix`, which does not have this problem.

**Comment by cherrymui** [comment]
We should probably move to use getdents64 on MIPS64, just like all other architectures. At the time the code was written, getdents64 was rather new in MIPS64 Linux kernel. But it is not new anymore, and we probably do require newer kernels.

**Comment by cherrymui** [comment]
`x/sys/unix` also uses getdents64 on MIPS64.

**Comment by ianlancetaylor** [comment]
I would certainly encourage anybody who wants to call `Getdents` themselves to use golang.org/x/sys/unix rather than syscall.  But of course syscall should at least be internally consistent.

**Comment by minux** [comment]
Yeah, I think we can fix this (with a api-breaking change) now as 3.10 is
almost 6 years old.

I do think the syscall package should at least work for the most basic
things (e.g. not supporting bpf is fine, but Getdirent should work.)

**Comment by tklauser** [comment]
> Yeah, I think we can fix this (with a api-breaking change) now as 3.10 is
almost 6 years old.

According to https://github.com/golang/go/wiki/MinimumRequirements the minimum kernel version required for linux/mips64le is 4.8, so that shouldn't be a problem.

**Comment by lechner** [comment]
Hi, we use `syscall` in other places as well. Older documentation encourages external packages to use `x/sys/unix` instead. Is the recommendation still valid? Thank you!

**Comment by bradfitz** [comment]
@lechner, `x/sys/unix` is gets new stuff and is updated more regularly. You can use `syscall` if it meets your needs, but it doesn't change often (ideally never), and when it does it's tied to releases. So using `x/sys/unix` is almost always a better option.

**Comment by lechner** [comment]
@bradfitz, which module would you recommend for [Go-Fuse](https://github.com/hanwen/go-fuse), a package that provides the filesystem-in-userspace (FUSE) bindings used by [gocryptfs](https://github.com/rfjakob/gocryptfs), please? Thank you!

**Comment by bradfitz** [comment]
@lechner, whatever the Go-Fuse authors are using is fine, if their code is working. If they hit problems and they're using `syscall`, the answer might be to not use `syscall`.

**Comment by lechner** [comment]
@bradfitz Thank you!
