### ISSUE TITLE
gccgo: reflection-based type printing inconsistency

### ISSUE THREAD

**Issue by tamird** [golang/go#23620]
### What version of Go are you using (`go version`)?
`go version go1.10beta2 gccgo (GCC) 8.0.1 20180126 (experimental) linux/amd64`

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tduberstein/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tduberstein/local/go"
GORACE=""
GOROOT="/home/tduberstein/local/gcc/gcc"
GOTMPDIR=""
GOTOOLDIR="/home/tduberstein/local/gcc/gcc/libexec/gcc/x86_64-pc-linux-gnu/8.0.1"
GCCGO="/home/tduberstein/local/gcc/gcc/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build297122770=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
```

### What did you do?
```golang
package main

import (
	"fmt"
)

type e = struct{ error }

func main() {
	fmt.Printf("%T\n", e{})
}
```
https://play.golang.org/p/HRkuS74EjTu

### What did you expect to see?
`struct { error }`

### What did you see instead?
`struct { ? error }`

**Comment by odeke-em** [comment]
Thank you @tamird for this bug report.

/cc @paranoiacblack @ianlancetaylor @thanm.
