### ISSUE TITLE
gccgo: regression in os/exec and os/signal testcases starting with go1.10beta1 on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#23626]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10rc1 gccgo (GCC) 8.0.1 20180129 (experimental) linux/ppc64le

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le

### What did you do?
Build gccgo and ran the libgo testsuite on ppc64le

### What did you expect to see?
No new failures

### What did you see instead?
Some new failures after the upgrade to go 1.10beta1 front end and libgo.

Here are the failures. The failure in os/exec is consistent.
```
--- FAIL: TestExtraFiles (3.04s)
	exec_test.go:426: TestExtraFiles: Something already leaked - closed fd 3
	exec_test.go:426: TestExtraFiles: Something already leaked - closed fd 5
	exec_test.go:605: Run: exit status 1; stdout "leaked parent file. fd = 6; want 4\n", stderr ""
FAIL
Keeping gotest109408
FAIL: os/exec
Makefile:3320: recipe for target 'os/exec/check' failed
make: *** [os/exec/check] Error 1
```
The failure in os/signal happens only when the entire libgo testsuite is run:
```
--- FAIL: TestAtomicStop (1.97s)
        signal_test.go:325: iteration 9: output lost signal on tries: 9
        signal_test.go:333: iteration 9: lost signal
FAIL
Keeping gotest45888
FAIL: os/signal
```
But if the os/signal test is run by itself either using make or by running the a.out that was generated earlier, it doesn't fail.
```
make os/signal/check
PASS: os/signal
```

**Comment by ianlancetaylor** [comment]
I am not seeing these on amd64.  Not sure what is going on here.

**Comment by laboger** [comment]
The os/signal failure is not showing up in the gcc-testresults output now that the gccgo builds have been re-enabled on ppc64le so I won't worry about that one now.

I will look into the os/exec failure a bit more.

**Comment by thanm** [comment]
I saw the same failure (os/exec "Something already leaked") in a recent gccgo test run on Arm64.
I'll try running the test under strace...

**Comment by laboger** [comment]
I have been looking at some straces too...
I see that in the latest there are two files opened, followed by some lstat's and those are never closed.
For example, libm.so.6 is opened earlier in the strace, then closed, but then this appears again later:
```
open("/lib/powerpc64le-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0) = 0x3fff8e160000
munmap(0x3fff8e160000, 65536)           = 0
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0xd0000) = 0x3fff8e160000
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0xd0000) = 0x3fff8e150000
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0) = 0x3fff8e140000
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0xd0000) = 0x3fff8e130000
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0) = 0x3fff8e120000
mmap(NULL, 65536, PROT_READ, MAP_PRIVATE, 3, 0) = 0x3fff8e110000
munmap(0x3fff8e120000, 65536)           = 0
munmap(0x3fff8e160000, 65536)           = 0
munmap(0x3fff8e150000, 65536)           = 0
munmap(0x3fff8e140000, 65536)           = 0
lstat("/lib/powerpc64le-linux-gnu/libm.so.6", {st_mode=S_IFLNK|0777, st_size=12, ...}) = 0
readlink("/lib/powerpc64le-linux-gnu/libm.so.6", "libm-2.23.so", 128) = 12
lstat("/lib/powerpc64le-linux-gnu/libm-2.23.so", {st_mode=S_IFREG|0644, st_size=856616, ...}) = 0
```
After this 3 is never closed. It opens the file that this links to and closes it.
Same happens with another file that is a symbolic link.

This doesn't appear in an strace from gccgo before the go 1.10beta1 update.

**Comment by thanm** [comment]
@laboger  Are you passing "-f" to strace? I am not seeing quite the same thing you're seeing (for me there are other PIDs with file descriptor 3 open, but following the chain from the parent to the point of failure I don't see a smoking gun). try:

strace -f -o trace.txt ./a.out -test.v
egrep '(clone\(|TestExtraFiles|.*\) = 3$|close\(3\))' trace.txt  > reduced.txt

**Comment by laboger** [comment]
You're right, I didn't use -f.

Here's what I see in the good and bad. I ran using -test.run=TestExtraFiles to limit the output.
In the good case, the dependent .so files for a.out are all opened and closed before the test starts to run, but in the bad case they haven't all been opened before the execution starts.
good: (the bad file descriptor is what is expected)
```
59966 stat("./a.out", {st_mode=S_IFREG|0775, st_size=794472, ...}) = 0
59966 open("./a.out", O_RDONLY|O_CLOEXEC <unfinished ...>
59966 close(3)                          = 0
59966 open("/lib/powerpc64le-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 open("/usr/local/gccgo.trunk.p7/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 open("/lib/powerpc64le-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 open("/lib64/ld64.so.2", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 open("/lib/powerpc64le-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 open("/lib/powerpc64le-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 clone(child_stack=0x3fff8c62e8b0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x3fff8c62f0d0, tls=0x3fff8c636760, child_tidptr=0x3fff8c62f0d0) = 59991
59966 clone( <unfinished ...>
59991 clone( <unfinished ...>
59966 open("/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
59966 close(3)                          = 0
59966 write(1, "=== RUN   TestExtraFilesFDShuffl"..., 34) = 34
59966 write(1, "--- SKIP: TestExtraFilesFDShuffl"..., 42) = 42
59966 write(1, "=== RUN   TestExtraFiles\n", 25 <unfinished ...>
59966 close(3)                          = -1 EBADF (Bad file descriptor)
```
bad
```
130267 stat("./a.out", {st_mode=S_IFREG|0775, st_size=804328, ...}) = 0
130267 open("./a.out", O_RDONLY|O_CLOEXEC) = 3
130267 close(3)                         = 0
130267 open("/usr/local/gccgo.trunk/lib64/libgo.so.13", O_RDONLY|O_CLOEXEC) = 3
130267 close(3)                         = 0
130267 open("/lib/powerpc64le-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
130267 write(1, "=== RUN   TestExtraFilesFDShuffl"..., 34) = 34
130267 write(1, "--- SKIP: TestExtraFilesFDShuffl"..., 42) = 42
130267 write(1, "=== RUN   TestExtraFiles\n", 25) = 25
130267 close(3)                         = 0
```

**Comment by ianlancetaylor** [comment]
I wonder if this could have something to do with the recent changes I made to libbacktrace.  @laboger I assume that your good/bad are different SVN revisions?  Are there any changes to libbacktrace between those two revisions?

**Comment by laboger** [comment]
good: 256306
bad: 257147

Yes I can see differences between libbacktrace in those two trees.

**Comment by ianlancetaylor** [comment]
Actually, I bet it has to do with the presence or absence of debuginfo files for system libraries.

**Comment by ianlancetaylor** [comment]
I'm pretty sure this is fixed by https://gcc.gnu.org/ml/gcc-patches/2018-01/msg02498.html .  Optimistically closing.
