### ISSUE TITLE
Binary package download contains unrelated cruft

### ISSUE THREAD

**Issue by tmack0** [golang/go#23628]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Specifically 1.8.3, exists in all

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux amd64
checked other arch packages, found the same there too

### What did you do?
Browse to golang.org, click "Download Go (Binary distributions available for Linux, Mac OS, Windows, and More!)", click the go1.9.3.linux-amd64.tar.gz link to download the package, tar -xzvf go1.9.3.linux-amd64.tar.gz

### What did you expect to see?
Files necessary to run and/or compile go apps

### What did you see instead?
Files needed to run and/or compile go apps, a Blog full of content, source code, about 77Mb of extraneous stuff thats not needed to run/compile go and does not belong in a binary distribution.

Blog should be its own separate download
Src for the version already exist inherently since this is a git repo and should be left to git clone if wanted.

Relates to #21917  which has been altered into something else over the course of the comments.

**Comment by bradfitz** [comment]
Let's just keep using #21917.
