### ISSUE TITLE
gccgo: regression in net testcase starting with go1.9 front end

### ISSUE THREAD

**Issue by laboger** [golang/go#23623]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version
go version go1.9 gccgo (GCC) 8.0.0 20170914 (experimental) linux/ppc64le

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le

### What did you do?
Built gccgo on ppc64le and ran the go and libgo tests.

### What did you expect to see?
No new failures.

### What did you see instead?
The testcase for package net fails like this:
_testmain.go:9:20: error: incompatible type for field 2 in struct construction
  {"TestAddr6", net.TestAddr6},
                    ^
Keeping gotest118459
FAIL: net

I believe _testmain.go is generated when the tests are run and is supposed to generate a struct containing all the testcases being built for the package, but in this case it is putting TestAddr6 into the struct and that is not a function.

```
package main

import "./_gotest_"
import "testing"
import "testing/internal/testdeps"

var tests = []testing.InternalTest {
        {"TestSortByRFC6724", net.TestSortByRFC6724},
        {"TestAddr6", net.TestAddr6},   <--- this is not a function
        {"TestRFC6724PolicyTableClassify", net.TestRFC6724PolicyTableClassify},
        {"TestRFC6724ClassifyScope", net.TestRFC6724ClassifyScope},
        {"TestRFC6724CommonPrefixLength", net.TestRFC6724CommonPrefixLength},
        {"TestCgoLookupIP", net.TestCgoLookupIP},
        {"TestCgoLookupIPWithCancel", net.TestCgoLookupIPWithCancel},
        {"TestCgoLookupPort", net.TestCgoLookupPort},
        {"TestCgoLookupPortWithCancel", net.TestCgoLookupPortWithCancel},
        {"TestCgoLookupPTR", net.TestCgoLookupPTR},

```

TestAddr6 is found in dnsclient_unix_test.go:

```
// Test address from 2001:db8::/32 block, reserved by RFC 3849 for documentation.
var TestAddr6 = [16]byte{0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}

```

**Comment by laboger** [comment]
I should clarify: the above go version and test output was run using gcc commit 252775 to identify about where it started, but the same failure occurs on the latest trunk.

**Comment by ianlancetaylor** [comment]
This is happening because on ppc64 the libgo/testsuite/gotest script matches on data objects.  I do need to figure out a better mechanism here.
