### ISSUE TITLE
net/http: HTTP/1.x transport connection broken

### ISSUE THREAD

**Issue by KonradHolubek** [golang/go#23622]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
rclone v1.39
- os/arch: linux/arm
- go version: go1.9.2

I'm using a raspberry pi 2

### What did you do?

I am using rclone sync between my personal OneDrive folder and Backblaze bucket

### What did you expect to see?

All files synced

### What did you see instead?
I see 266 Errors, mostly saying: 
"Failed to copy: Post https://xxxxxx.backblaze.com/b2api/v1/b2_upload_file/xxxxxxxxxxxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=xxxx with Body length xxxxx"

Please advise. 

Konrad

**Comment by jinfagang** [comment]
@KonradHolubek Hi, how did'u solve this problem, I running into the same error.

**Comment by KonradHolubek** [comment]
@jinfagang This issue concerns actually rclone si I posted my case on their site... are you also experiencing this problem with rclone ? If so, head over to their github. I opened an issue there.
