### ISSUE TITLE
cmd/go: build fails when $HOME is not writeable

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#23638]
### What version of Go are you using (`go version`)?
```
go version devel +ebe38b8 Wed Jan 31 02:13:21 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?
Not Applicable (the issue is related to build cache)

### What operating system and processor architecture are you using (`go env`)?
Linux

### What did you do?

Attempted to compile when the home directory wasn't writable: `HOME=/non-existent go build foo.go`

```go
package main

import "fmt"

func main() {
        fmt.Println("Hello world!")
}
```

### What did you expect to see?
A binary to be generated.

### What did you see instead?
The following error:

```
initializing cache in $GOCACHE: mkdir /non-existent: permission denied
```

**Comment by bradfitz** [comment]
I dunno, this kinda feels like a feature. You told it to do something and it can't, so it fails and tells you it can't do that.

Or did this arise out of a less contrived case?

If we're setting GOCACHE implicitly to something unusable, that's another story.

**Comment by 0xmohit** [comment]
I guess that the title should have said $HOME instead of GOCACHE; essentially when the home directory is not writeable.  An option might be to ignore the build cache or provide a more helpful message.

**Comment by bradfitz** [comment]
@rsc, to you for decision. But I'm assuming we should do something here, even if it's a better error message. There are apparently a number of CI/build systems that have an unwritable $HOME.

**Comment by ianlancetaylor** [comment]
I think we should just disable it in this case.  Sent a CL.
