### ISSUE TITLE
x/build/version: prepend $PATH with $GOROOT/bin

### ISSUE THREAD

**Issue by dolmen** [golang/go#23635]
### What version of Go are you using (`go version`)?
go1.9.3, but trying go1.10rc1

### Does this issue reproduce with the latest release?
Yes: https://github.com/golang/build/commit/46a0bbc43b7379686f030f84611d23f80144685f

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?

```
$ go version
go version go1.9.3 darwin/amd64
$ go get golang.org/x/build/version/go1.10rc1
$ go1.10rc1 download
$ go get golang.org/x/tools/godoc
$ cd "$(go env GOPATH)/src/golang.org/x/tools/godoc/static"
$ go1.10rc1 generate
# runtime/internal/sys
compile: version "go1.10rc1" does not match go tool version "go1.9.3"
gen.go:7: running "go": exit status 2
```

### What did you expect to see?
`go1.10rc1 generate` should succeed.

### Workaround
```
$ PATH="$(go1.10rc1 env GOROOT)/bin:$PATH" go1.10rc1 generate
```

### Suggested fix
Prepend `$PATH` with `$GOROOT/bin` in [`golang.org/x/version Run`](https://github.com/golang/build/blob/master/version/version.go#L60)

**Comment by bradfitz** [comment]
Sorry, there's not enough information here. Before evaluating your solution, we need to understand the problem. It's nice that you provided a repo, but it doesn't include information about your environment.

Are you sure you included all the steps? Why is golang.org/x/version.Run even relevant here? I don't see you using the go1.10rc1 binary in your steps above.

**Comment by dolmen** [comment]
Sorry. My original submission had a typo: it mentioned `go generate` instead of `go1.10rc1 generate`. I have fixed it.

**Comment by bradfitz** [comment]
Looks like this was already fixed in https://go-review.googlesource.com/c/dl/+/143545 (dup of #28103).

/cc @dmitshur
