### ISSUE TITLE
Can I call a function that is ONLY a goroutine?

### ISSUE THREAD

**Issue by guppythegod** [golang/go#23631]
I'm working in golang 1.6.2 on linux/amd64. I just learned how to convert my go file into a shared library that can be used in python. I want to call a function that is ONLY a go routine IN my python code. Is this possible, would it interfere with the rest of my code (considering it is a go routine, it should just run in the background?) and can go routines only be called from go code?

Thank you so much

**Comment by 0xmohit** [comment]
This is an issue tracker.

Please use https://groups.google.com/forum/#!forum/golang-nuts or the [Go forum](https://forum.golangbridge.org/) for questions.
