### ISSUE TITLE
runtime: gobytes() initializes allocated memory unnecessarily

### ISSUE THREAD

**Issue by petermattis** [golang/go#23634]
I noticed this in the go1.9 sources, though this also applies to go1.10. `runtime.gobytes` currently uses `make([]byte, ...)` and then immediately overwrites the data in the slice:

```
func gobytes(p *byte, n int) []byte {
	if n == 0 {
		return make([]byte, 0)
	}
	x := make([]byte, n)
	memmove(unsafe.Pointer(&x[0]), unsafe.Pointer(p), uintptr(n))
	return x
}
```

The zero initialization of the slice by `make` is a small but noticeable performance hit when copying a large chunk of memory via `C.GoBytes`. The allocation can be replaced with `rawbyteslice(n)` which already exists for the purpose of allocating an uninitialized `[]byte`.

**Comment by josharian** [comment]
Want to send a change for 1.11?

**Comment by petermattis** [comment]
@josharian Sent https://go-review.googlesource.com/c/go/+/91075. Wasn't sure if you wanted it now or when go1.11 opens, but I'm likely to forget later.
