### ISSUE TITLE
cmd/compile: missing "declared but not used" error for assignment in closure.

### ISSUE THREAD

**Issue by rmmh** [golang/go#23659]
### What version of Go are you using (`go version`)?
go1.10rc1 linux/amd64

### Does this issue reproduce with the latest release?
Yes, and with tip. (851e98f0ee)

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04.

### What did you do?
Attempting to use `go/types` to do fast type checking of a [large repository](https://github.com/kubernetes/kubernetes) reveals a problem:

```go
func a() {
        var x int
        func() {
        	x = 3
        }()
}
```

Is reported as `x declared but not used` by `go/types`, but does not produce an error in the compiler.

Demo: https://play.golang.org/p/oi6haYy6cXt

### What did you expect to see?
I expected go/types to return identical type errors as actually compiling. 

### What did you see instead?
Different errors.

**Comment by ianlancetaylor** [comment]
Dup of #8560?

**Comment by rmmh** [comment]
More precisely, dupe of #14596.

**Comment by ianlancetaylor** [comment]
Closing as dup.
