### ISSUE TITLE
cmd/gofmt: strange indentation in slice literal

### ISSUE THREAD

**Issue by larhun** [golang/go#23655]
As shown in playground https://play.golang.org/p/QpLaytT2yia, the following code has strange indent, that depends on the order of the elements.

```golang
package main

var a = []string{
	"xxxxxxxxxxxxxxxxxxxxx", // comment
	"xxxxx",                 // comment
	"x",                     // comment
}

var b = []string{
	"xxxxxxxxxxxxxxxxxxxxx", // comment
	"x",     // comment
	"xxxxx", // comment
}

func main() {}
```

**Comment by bradfitz** [comment]
That's intentional. See previous bugs on this topic. This is a frequent duplicate. The main duplicate is #10392.

**Comment by bradfitz** [comment]
First rule of gofmt: don't worry about gofmt's choices.

**Comment by mvdan** [comment]
I wonder if this warrants a gofmt FAQ.

**Comment by bradfitz** [comment]
If we did, it should be of the form:

> Q: gofmt did something unexpected!
> A: Don't worry about it. Keep writing code.

:)
