### ISSUE TITLE
unexpected Result

### ISSUE THREAD

**Issue by veenutanwar** [golang/go#23652]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10beta2 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
X86 Windows 10

### What did you do?
        dr = dr+ 1000
	dr = dr+ 5.2
	dr = dr+ 5.2 
	fmt.Println(dr )
 

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
1010.4

### What did you see instead?
1010.4000000000001

**Comment by dominikh** [comment]
See http://floating-point-gui.de/.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. Please see https://github.com/golang/go/wiki/Questions for various places you could ask questions at.
