### ISSUE TITLE
time.ParseDuration does not accept types above hour on Windows

### ISSUE THREAD

**Issue by ivanjaros** [golang/go#23654]
I have a duration flag and when I use any larger type than hour, it will fail.
Looking at the

`var durationRE = regexp.MustCompile("^([0-9]+)(y|w|d|h|m|s|ms)$")`

it should support days, weeks and years. But it will fail. I tried even 30d0h but even that won't work.

I am running Windows 10x64 and Go 1.9.2

**Comment by bontibon** [comment]
I'm not sure where you're getting the `durationRE` value from, but `time.ParseDuration` does not support anything unit larger than hours. [This is documented](https://golang.org/pkg/time/#Duration):

> There is no definition for units of Day or larger to avoid confusion across daylight savings time zone transitions.

**Comment by mvdan** [comment]
Like @bontibon said, this is working as expected. I also don't know where you got that line from - it's never been in the Go tree.

**Comment by ivanjaros** [comment]
![duration](https://user-images.githubusercontent.com/3159095/35687950-5e927376-0770-11e8-8282-9fa28af02028.png)

**Comment by bontibon** [comment]
@ivanjaros That isn't from the Go standard library. Open an issue with the 3rd-party library that you're using.

**Comment by ivanjaros** [comment]
Aaah, I see. I just followed the Flag library for the duration variable and didn't notice there are multiple implementations of ParseDuration. In the core I see that only up to hour values are supported.
