### ISSUE TITLE
x/playground: link to the playground source code in the help page

### ISSUE THREAD

**Issue by josharian** [golang/go#23658]
I can never remember where it is. It's pretty standard nowadays to link back to the implementation of any open source website. IIRC, there are actually multiple playground moving parts. It'd be nice to link to all of them. I'd send a CL, but, um, I can't remember where the code is.

cc @andybons

**Comment by bradfitz** [comment]
> IIRC, there are actually multiple playground moving parts.

Actually it's got much simpler recently! @andybons collapsed it from a bunch of components to like 1.

But yeah, worth linking to.
