### ISSUE TITLE
Proposal for Go 2: disallow pre-declared types as variable names

### ISSUE THREAD

**Issue by glycerine** [golang/go#23668]
Go 1.9 compiles the following legal program
~~~
package main
func main() {
	var int int
        int = 3
        _ = int
}
~~~
The problem here is that it is highly confusing to have variable names that repeat the pre-declared types (int,uint, int64, uint64, int8, etc).  The full list, from https://golang.org/ref/spec#Predeclared_identifiers, is
~~~
bool byte complex64 complex128 error float32 float64
	int int8 int16 int32 int64 rune string
	uint uint8 uint16 uint32 uint64 uintptr
~~~

When you read code, it makes little sense to see `int = 3`, for example.

This is just a small bit of cleanup. 

As it is a breaking change, it would be a natural for Go 2 where such changes must be deferred to.

As a small, side benefit, if they are forbidden as left-hand-side assignment identifiers, then online type checkers for Go interpreters have an easier time recovering from syntax errors that involve the pre-declared types.

**Comment by dominikh** [comment]
Previous discussions and my argument for why I am against this: https://github.com/golang/go/issues/18193

**Comment by rsc** [comment]
We allow this exactly so that new pre-declared types can be introduced without invalidating old programs.

**Comment by glycerine** [comment]
The argument for backwards compatibility doesn't hold water when there is already going to be breaking changes at a major revision. The current set could still be forbidden. Am I hearing that Go 2 must be backwards compatible with Go 1?

**Comment by ianlancetaylor** [comment]
The concept of introducing new pre-declared types will still be valid in Go 2, just as it is in Go 1.  Why give up that idea?  Personally I think it's a great idea.

I would add that Go 2 should be as backward compatible as possible.  Breaking compatibility with Go 1 is a significant cost that requires a corresponding benefit.
