### ISSUE TITLE
go tool gocov-xml bad tool name

### ISSUE THREAD

**Issue by pirDOL** [golang/go#23665]
why 'The tool name must be lower-case letters, numbers or underscores.' ?

After go build github.com/AlekSi/gocov-xml , I have to mv executable gocov-xml to gocov_xml, in order to use it in go tool.

https://github.com/golang/go/blob/259f78f001c7f6e43063f06f25c9199f74c8c1d1/src/cmd/go/internal/tool/tool.go#L46

**Comment by bradfitz** [comment]
`go tool` is not for external use. You're not supposed to be able to add your own tools.

For questions about Go, see https://golang.org/wiki/Questions.
