### ISSUE TITLE
cmd/compile: for the similar bad codes, the error message for switch-block is not good as for if-block.

### ISSUE THREAD

**Issue by dotaheor** [golang/go#23664]
### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd6

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package main

func f() {}

func main() {
	if f() true { // syntax error: unexpected true, expecting { after if clause
	}
	
	switch f() true { // syntax error: missing { after switch clause
	}
}
```

### What did you expect to see?

```
./a.go:6:9: syntax error: unexpected true, expecting { after if clause
./a.go:9:13: syntax error: unexpected true, expecting { after switch clause
```

### What did you see instead?

```
./a.go:6:9: syntax error: unexpected true, expecting { after if clause
./a.go:9:13: syntax error: missing { after switch clause
```

**Comment by bradfitz** [comment]
Actually, this looks fixed with Go 1.10:

```
./x.go:6:9: syntax error: unexpected true, expecting semicolon or newline
./x.go:9:13: syntax error: unexpected true, expecting semicolon or newline
```

**Comment by dotaheor** [comment]
great!

**Comment by griesemer** [comment]
@bradfitz I'm going to reopen this for Go 1.11. It's true that the error messages are consistent, but they are not good: In both cases, we're (often) not expecting a semicolon (or newline) but the opening '{' of the block. I think this can be improved.
