### ISSUE TITLE
wiki: remove reference to `code.google.com` from section CodeReviewComments

### ISSUE THREAD

**Issue by dgryski** [golang/go#23678]
The sample code at https://github.com/golang/go/wiki/CodeReviewComments#imports still references an import path of `code.google.com`.

Suggest `bitbucket.org/user/project` instead.
(Alternatively, `google.golang.org/cloud`, `google.golang.org/grpc` , `rsc.io`, `go4.org`, `perkeep.org`,  ... )

Filing a bug due to the sensitive nature of CodeReviewComments.

**Comment by odeke-em** [comment]
Awesome, thank you @dgryski for reporting this. I've fixed it 
<img width="824" alt="screen shot 2018-02-03 at 1 08 22 am" src="https://user-images.githubusercontent.com/4898263/35765343-cf4f8e82-087e-11e8-8579-fe8ac4dd4c15.png">

Please feel free to close this issue if that wiki change that I've made is satisfactory.

**Comment by dgryski** [comment]
LGTM
