### ISSUE TITLE
cmd/vet: false positive about passing Go pointer to C

### ISSUE THREAD

**Issue by ericlagergren** [golang/go#23670]
1.9.2, linux/amd64

```
package main

func main() {
	A := F{}
	C := F{}
	C.Copy(&A)
}

type F struct{ b map[int]int }

func (f *F) Copy(f2 *F) { f.b = f2.b }
```

`go vet` warns: `foo.go:6: possibly passing Go type with embedded pointer to C`. Additionally, it prints the message twice.

Renaming `C` to `B` gets rid of the false positive.

**Comment by mvdan** [comment]
Dup of #20655, and already fixed in 1.10.
