### ISSUE TITLE
text/scanner: Allow users of ScanRawStrings to get a RawString

### ISSUE THREAD

**Issue by metaleap** [golang/go#23675]
Currently, even with `ScanRawStrings` enabled, all "raw" (delimited by backticks) strings will trigger `String` tokens rather than `RawString` tokens. From a `text/scanner`-only perspective, this could be fixed by changing L624 in `scanner.go` as outlined in this patch:

https://github.com/go-forks/go/commit/d869c9a9ed55a79cb626d223736ff1c40d172cce

Regrettably I don't have the time for the endless litany of steps outlined in https://golang.org/doc/contribute.html just to submit such a brazenly trivial PR, so whoever contributor wants to pick this up, please be my guest =)

**Comment by ianlancetaylor** [comment]
We now accept GitHub pull requests.  Want to send in your patch?
