### ISSUE TITLE
html/template: add break and continue

### ISSUE THREAD

**Issue by dgryski** [golang/go#23683]
https://github.com/golang/go/issues/20531 added `break` and `continue` to `text/template`, but these keywords are not available in `html/template`.

Running a simple template (https://github.com/campoy/gotalks/blob/master/go1.10/template/main.go) with `html/template` fails at runtime with 

`panic: escaping {{continue}} is unimplemented`

**Comment by ALTree** [comment]
Why do the 1.10 release notes say that `html/template` supports `{{break}}` and `{{continue}}`? Either we add them to `html/template` before the release, or we need to delete that paragraph from the 1.10 release notes. 

I've sent a [CL](http://golang.org/cl/91616) in case we decide to go with the latter.

**Comment by dgryski** [comment]
`html/template` is a wrapper around `text/template` that adds context-senstive escaping. The oversight in the original patch as that the html escaping logic needs to be updated to deal with the new template commands.

**Comment by ALTree** [comment]
The fix look quite simple but it's not up to me so labelling this as `NeedsDecision` for 1.10.

**Comment by rsc** [comment]
It sure is unfortunate that we never tested that break and continue work in html templates.

I don't believe CL 91815 is sufficient to add them. Break and continue stop the control flow midway through a range loop iteration. The flow-sensitive analysis of HTML context assumes that the loop body runs in full. It would need to be updated to take the early stop into account. I don't see an easy way to do that in the code. Go 1.10 was supposed to have shipped already. It seems to me far too late to add a change this subtle.

It seems like the safest course of action is to remove break and continue from both text/template and html/template for Go 1.10, and then add them back in Go 1.11, with appropriate attention spent on html/template.

Thoughts?

/cc @robpike @mikesamuel @stjj89

**Comment by robpike** [comment]
I agree, the change to text/template should be rolled back.

**Comment by stjj89** [comment]
CL 91815 actually looks fine to me. I don't html/template assumes that the loop body will run in full; it escapes the range loop so that it will always produce safe output, no matter how many times the body is executed, if any at all. Specifically, it unconditionally escapes the nodes in the [if](https://github.com/golang/go/blob/master/src/html/template/escape.go#L477) and [else](https://github.com/golang/go/blob/master/src/html/template/escape.go#L493) branches of a range loop, and [checks](https://github.com/golang/go/blob/master/src/html/template/escape.go#L479) that executing the body of the range loop multiple times does not change its escaping context.

I can't come up with an edge case involving continue or break that the current escaping logic will not handle. I might be missing something, though. It probably makes sense to delay this change to Go 1.11 so we have more time to consider and test this change.

**Comment by mikesamuel** [comment]
On Feb 5, 2018 2:29 PM, "Samuel Tan" <notifications@github.com> wrote:

> CL 91815 actually looks fine to me. I don't html/template assumes that the
> loop body will run in full; it escapes the range loop so that it will
> always produce safe output, no matter how many times the body is executed,
> if any at all. Specifically, it unconditionally escapes the nodes in the
> if
> <https://github.com/golang/go/blob/master/src/html/template/escape.go#L477>
> and else
> <https://github.com/golang/go/blob/master/src/html/template/escape.go#L493>
> branches of a range loop, and checks
> <https://github.com/golang/go/blob/master/src/html/template/escape.go#L479>
> that executing the body of the range loop multiple times does not change
> its escaping context.
>
> I can't come up with an edge case involving continue or break that the
> current escaping logic will not handle. I might be missing something,
> though. It probably makes sense to delay this change to Go 1.11 so we have
> more time to consider and test this change.
>
> So it's not a problem where a loop body does something like
    <script>{{if .C}}{{..}}{{else}}{{break}}{{end}}</script>

**Comment by rsc** [comment]
Exactly. This is why we're rolling it back.

**Comment by stjj89** [comment]
> <script>{{if .C}}{{..}}{{else}}{{break}}{{end}}</script>

Ah, that makes sense. We can probably fix this by storing the context whenever we see break or continue, and comparing that context with the end-of-loop context when we get there.

**Comment by mikesamuel** [comment]
On Wed, Feb 7, 2018 at 1:25 PM, Samuel Tan <notifications@github.com> wrote:

> <script>{{if .C}}{{..}}{{else}}{{break}}{{end}}</script>
>
> Ah, that makes sense. We can probably fix this by storing the context
> whenever we see break or continue, and comparing that context with the
> end-of-loop context when we get there.
>
> Yep.  I think just treating both break and continue as a jump to end of
body would do it since the loop increment does nothing to the output
buffer, and we already reconcile the loop body end context with the loop
start context.

**Comment by seankhliao** [comment]
This was added in 1.18
