### ISSUE TITLE
blog: fix code.google.com links

### ISSUE THREAD

**Issue by as** [golang/go#23688]
Source: https://blog.golang.org/introducing-gofix

Summary: The links in the article above (paragraph 4) redirect the user to the Go github repository landing page. 
See also: #8692

**Comment by gideondsouza** [comment]
is the blog part of this repo? are you accepting pr's ?

**Comment by bradfitz** [comment]
Yes: https://github.com/golang/blog/

We don't accept PRs via GitHub ... yet. Soon. Currently you need to use Gerrit, but wait maybe a week and we should accept PRs.

**Comment by ysmolsky** [comment]
@bradfitz, those links in the article point to sources which were deleted in this commit:
```
   cmd/fix: delete pre-Go 1 fixes
    
    Assume people who were going to update to Go 1 have done so.
    Those with pre-Go 1 trees remaining will need to update first
    to Go 1.0 (using its 'go fix') and then to Go 1.1.
```

Does it makes sense to point to different but actual examples in the repo?

**Comment by bradfitz** [comment]
Why don't you just change the links to point to source browser URLs linking into old branches?

**Comment by ysmolsky** [comment]
Alright, done. I have fixed all other broken links I could find.
