### ISSUE TITLE
about build-mode plugin、shared support windows

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#23697]
i need Plug-in design in project，but the go no support dynamic link lib on windows.
Do you have any good idea about Plug-in design？or what time support plugin on win？

**Comment by zhaoya881010** [comment]
go version go1.10rc1 windows/386

go build -buildmode=shared -o hello.dll hello.go
-buildmode=shared not supported on windows/386

go build -buildmode=plugin -o hello.dll hello.go
-buildmode=plugin not supported on windows/386

**Comment by bradfitz** [comment]
Dup of #19282. No plans.

**Comment by Fruchtgummi** [comment]
Now there are times customers that rely on Windows! How to realize the big projects here, especially in the on-premise area, when every function becomes a Herculean task? The support for plugins on windows is very important. Do not you want to understand that? 

At least to make a statement, if the support for Windows comes, would be enough to decide to start the development under Linux.

**Comment by ianlancetaylor** [comment]
@Fruchtgummi This issue is closed, so commenting here doesn't help.  And, to be honest, it doesn't help us to know that more people want this functionality.  This is an open source project; what we need are people willing to do the work.  Thanks.

**Comment by Fruchtgummi** [comment]
Ok! With their statement, open source projects are no longer serious. I have to thank!
