### ISSUE TITLE
cross compiling for freebsd/amd64 on macOSx using smtp.SendMail() fails

### ISSUE THREAD

**Issue by FrankStorbeck** [golang/go#23691]
```
go version
go version go1.9.2 darwin/amd64
```

```
go env
GOARCH="amd64"
GOBIN="/Users/franks/sandbox/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/franks/sandbox/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c_/yl_7m41s7mz3qc4g8888d6zw0000gn/T/go-build192879054=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

I wrote the following snippet to analyse a problem we have encountered:
(me@mydomain.tld, she@herdomain.tld, name, passwd, smtp.mailhost.tld
and port are placeholders for the values I used)

```
package main

import (
	"fmt"
	"net/smtp"
	"time"
)

func main() {
	s := "From: me@mydomain.tld\r\n" +
		"Date: " + time.Now().Format(time.RFC822) + "\r\n" +
		"To: she@herdomain.tld\r\n" +
		"Subject: TEST-smtp.SendMail\r\n" +
		"test smtp.SendMail\r\n"

	auth := smtp.PlainAuth("", uname, passwd, "smtp.mailhost.tld")
	err := smtp.SendMail("smtp.mailhost.tld:port", auth, "me@mydomain",
		[]string{"she@herdomain.tld"}, []byte(s))
	if err != nil {
		fmt.Printf("Error sending mail: %s", err)
	}
}
```

when compiling it and running it on MacOS:

```
go build -o tsmtp tsmtp.go
./tsmtp
```

I observed that  the e-mail was sent and recieved by she@herdomain.tld,
but after cross-compiling it on MacOS for a freebsd/amd64 host and then running it on
that host I got an error and the mail was not sent:

```
env GOOS=freebsd GOARCH=amd64 go build -o bsdtsmtp tsmtp.go
scp bsdtsmtp user@freebsd.tld:tsmtp
ssh user@freebsd.tld
freebsd> ./tsmtp
Error sending mail: x509: failed to load system roots and no roots provided freebsd>
```

Finally we installed the go compiler on the freebsd host and compiled the code there and ran it:

```
scp tsmtp.go user@freebsd.tld:
ssh user@freebsd.tld
freebsd> go build -o tsmtp tsmtp.go
freebsd>  ./tsmtp
freebsd>
```

Now the mail was sent and recieved by she@herdomain.tld

So it seems that the cross compilation on MacOs X didn't result in the right binary...

**Comment by bradfitz** [comment]
When you're cross-compile cgo is disabled by default, so the binary will be different, unless you have a cross-compiling C toolchain around for the target.

But that doesn't affect the crypto/x509 package on FreeBSD. 

Sure you don't have multiple Go compilers installed on your Mac and aren't using Go 1.8 for the cross-compile?

Which version of FreeBSD? Does it have one of:

```go
var certDirectories = []string{
        "/etc/ssl/certs",               // SLES10/SLES11, https://golang.org/issue/12139                                                                
        "/system/etc/security/cacerts", // Android                                                                                                      
        "/usr/local/share/certs",       // FreeBSD                                                                                                      
        "/etc/pki/tls/certs",           // Fedora/RHEL                                                                                                  
        "/etc/openssl/certs",           // NetBSD                                                                                                       
}
```

**Comment by FrankStorbeck** [comment]
We only use go version 1.9.3. (1.9.2 was phased out yesterday).

on my mac I get:
>  ls /etc/ssl/certs /system/etc/security/cacerts /usr/local/share/certs /etc/pki/tls/certs /etc/openssl/certs
ls: /etc/openssl/certs: No such file or directory
ls: /etc/pki/tls/certs: No such file or directory
ls: /system/etc/security/cacerts: No such file or directory
ls: /usr/local/share/certs: No such file or directory
/etc/ssl/certs:
>

on our freebsd system we get 
> ls /etc/ssl/certs /system/etc/security/cacerts /usr/local/share/certs /etc/pki/tls/certs /etc/openssl/certs
ls: /etc/openssl/certs: No such file or directory
ls: /etc/pki/tls/certs: No such file or directory
ls: /system/etc/security/cacerts: No such file or directory
/etc/ssl/certs:
mydomain.tdl.pem	cert.pem		intermediate.pem

/usr/local/share/certs:
ca-root-nss.crt
>

Note however that only usage of one routine (the one that uses smtp.Sendmail())  within our total project fails when cross-compiling. 
All other routines run perfectly (for as far as we observe).

Frank Storbeck <frank@storbeck.nl> 
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 7795 81B0 D4CF DADD 0EAC  2964 66C4 EC57 6AD1 6783

**Comment by FrankStorbeck** [comment]
on the macosX host I see that only 
	/etc/ssl/cert.pem 
is available:

>  ls /usr/local/share/certs/ca-root-nss.crt /etc/ssl/cert.pem /etc/openssl/certs/ca-certificates.crt
ls: /etc/openssl/certs/ca-certificates.crt: No such file or directory
ls: /usr/local/share/certs/ca-root-nss.crt: No such file or directory
/etc/ssl/cert.pem
>  ls /usr/local/etc/ssl/cert.pem /etc/ssl/cert.pem /usr/local/share/certs/ca-root-nss.crt /etc/openssl/certs/ca-certificates.crt
ls: /etc/openssl/certs/ca-certificates.crt: No such file or directory
ls: /usr/local/etc/ssl/cert.pem: No such file or directory
ls: /usr/local/share/certs/ca-root-nss.crt: No such file or directory
/etc/ssl/cert.pem
> 

On the freebsd host 
	/etc/ssl/cert.pem, 
	/usr/local/share/certs/ca-root-nss.crt, 
	/usr/local/etc/ssl/cert.pem 
are present:

> ls /usr/local/share/certs/ca-root-nss.crt /etc/ssl/cert.pem /etc/openssl/certs/ca-certificates.crt
ls: /etc/openssl/certs/ca-certificates.crt: No such file or directory
/etc/ssl/cert.pem			/usr/local/share/certs/ca-root-nss.crt
> ls /usr/local/etc/ssl/cert.pem /etc/ssl/cert.pem /usr/local/share/certs/ca-root-nss.crt /etc/openssl/certs/ca-certificates.crt
ls: /etc/openssl/certs/ca-certificates.crt: No such file or directory
/etc/ssl/cert.pem			/usr/local/etc/ssl/cert.pem		/usr/local/share/certs/ca-root-nss.crt
>

So on both platforms /etc/ssl/cert.pem is accessible. 


Frank Storbeck <frank@storbeck.nl> 
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 7795 81B0 D4CF DADD 0EAC  2964 66C4 EC57 6AD1 6783

**Comment by FrankStorbeck** [comment]
as of go1.10 the problem vanished.
