### ISSUE TITLE
plugin: init functions aren't run if plugin directory contains a dot character

### ISSUE THREAD

**Issue by Dirbaio** [golang/go#23695]
Init functions are not run when Open()-ing a plugin that has been compiled from a directory containing a dot in its name.

How to reproduce:
- Clone https://github.com/Dirbaio/pluginbug into the right folder in your gopath
- Run `go run ./plugin.v1/main.go`. You get `The int is: 42`, as expected
- Compile the plugin: `go build -buildmode=plugin -o plugin.so ./plugin.v1/`
- Run the plugin host: `go run host/main.go`. You get  `The int is: 0`, because the init function hasn't run.
- Rename `plugin.v1` to `pluginv1`, and everything works.

```
dirbaio@saturn:~$ go version
go version go1.9.3 linux/amd64
dirbaio@saturn:~$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dirbaio/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build594308222=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by 0xmohit** [comment]
This cannot be reproduced on tip.  Likely fixed in https://github.com/golang/go/commit/6355d6c7e2e8f4ea4cfd3fed8da6677106937f66.

**Comment by mvdan** [comment]
@Dirbaio could you please confirm that this is fixed on tip or on the latest RC for you?

**Comment by Dirbaio** [comment]
Just checked 1.10rc1, and it's fixed!

Thanks guys!
