### ISSUE TITLE
SO_REUSEPORT

### ISSUE THREAD

**Issue by cuisj** [golang/go#23696]
Does net.Conn support SO_REUSEPORT in linux platform in plan ?

**Comment by ericlagergren** [comment]
If you have questions you should check out https://github.com/golang/go/wiki/Questions.

**Comment by davecheney** [comment]
No, we don't currently use SO_REUSEPORT on linux. 

Can you please explain the problem you are trying to solve that having SO_REUSEPORT available would let you solve?

**Comment by mikioh** [comment]
Go 1.11 probably will fix #9661 instead of exposing a tangle of platform-specific socket options.

**Comment by mengzhuo** [comment]
@mikioh Noop, I build with master branch  25c3bb377ac455184cc9870e690df45fe3f6e1ab and it's still missing.

I tried to run src/syscall/mkall.sh on my Debian box to update SO_REUSEPORT but it change const and breaks API checker. Did I miss somethings? :/
```
-       AF_MAX                           = 0x27
+       AF_MAX                           = 0x2a
```

**Comment by mikioh** [comment]
@mengzhuo,

The site "godoc.org" is your friend.

https://godoc.org/golang.org/x/sys/unix
https://godoc.org/syscall

If your circumstances have no reachability to the site, unfortunately, https://github.com/golang/go/wiki/Questions could help you.

**Comment by mengzhuo** [comment]
@mikioh 
syscall
> This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository.

Thanks for your reply, please ignore it :)

**Comment by theclapp** [comment]
@mikioh's previous comment (https://github.com/golang/go/issues/23696#issuecomment-404072922) touches on this obliquely, but more directly: 

The `syscall.SO_REUSEPORT` constant does not exist under linux/amd64, and a few other OS/ARCHes.  You have to use golang.org/x/sys/unix.SO_REUSEPORT.
