### ISSUE TITLE
goroutine benchmark test

### ISSUE THREAD

**Issue by GanLuo96214** [golang/go#23690]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/source/go"
GORACE=""
GOROOT="/usr/local/go/1.9.2"
GOTOOLDIR="/usr/local/go/1.9.2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7r/sbjw5fn508900mg0nbd141_w0000gn/T/go-build611940204=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

```go
package main

import (
	"fmt"
	"time"
)

var counter uint64 = 0

func emit() {

	counter++

}

func start() {
	for {
		go emit()
	}
}

func end() {
	fmt.Printf("%d", counter)
}

func main() {

	for i := 0; i < 5; i++ {
		go start()
	}

	time.Sleep(1 * time.Second)

	defer end()

}
```

### What did you expect to see?

after one second, the program will exit.

### What did you see instead?

the program run over one second, I have to kill it.

**Comment by Stephn-R** [comment]
Please read through the golang description of the defer keyword here

https://tour.golang.org/flowcontrol/12

It specifies that a defer statement only executes when the surrounding function returns. Since main doesn't "return" I would assume that your programs behavior is to be expected.

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
