### ISSUE TITLE
syscall.IFF_MULTI_QUEUE is missing for amd64 arch

### ISSUE THREAD

**Issue by lukaszo** [golang/go#23702]
### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
I wanted to use syscall.IFF_MULTI_QUEUE in my program

https://play.golang.org/p/pWwjXFshnS7

### What did you expect to see?

Working code

### What did you see instead?

Go fails to compile my code on amd64 arch:
`undefined: syscall.IFF_MULTI_QUEUE`

**Comment by AlexRouSg** [comment]
https://golang.org/pkg/syscall/

> NOTE: This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository. That is also where updates required by new systems or versions should be applied. Signal, Errno and SysProcAttr are not yet available in golang.org/x/sys and must still be referenced from the syscall package. See https://golang.org/s/go1.4-syscall for more information.

golang.org/x/sys/unix is the package containing IFF_MULTI_QUEUE

**Comment by bradfitz** [comment]
Yup, please use `golang.org/x/sys/unix` instead.

**Comment by lukaszo** [comment]
Thx for clarifying.
