### ISSUE TITLE
x/tools/cmd/bundle: binary name conflicts with ruby bundle

### ISSUE THREAD

**Issue by jordimassaguerpla** [golang/go#23700]
Installing the x/tools package will install a binary called bundle, which conflicts which the bundle binary installed by the bundler ruby gem.

Could it be possible to rename bundle to go-bundle or something that will not clash?

Thanks

**Comment by bradfitz** [comment]
x/tools/cmd/bundle has approximately 1 user in the world, and that's an internal use by the Go project itself. And we don't use Ruby, so it's not a conflict. If it's a conflict for you, don't install it, or put them in different paths.

**Comment by jordimassaguerpla** [comment]
jfyi this is a "conflict" that arise while packaging x/tools in the openSUSE community

https://build.opensuse.org/request/show/573082

Go and Ruby coexist in a distribution and it is fair for users to expect that they could install both, and I am not only referring to go and ruby themselves, but also to the subpackages/modules/gems/. Thus, I would expect to be able to to install go x/tools and rubygem bundler.

However, if only 1 user in the world uses x/tools/cmd/bundle, I guess we could just rename it in our package to something like go-bundle.

**Comment by bradfitz** [comment]
Making the disto package per Go repo is a debatable choice by itself. But assuming you proceed (or continue) with that, I'd just not package x/tools/cmd/bundle. In fact, I'd move from a blacklist to a whitelist of what you package. You should define your "tools" distro package as a certain set of actually useful tools that users want. godoc, eg, gorename, etc.

**Comment by baiyunping333** [comment]
hi，you can use full path， like
```
// Code generated by golang.org/x/tools/cmd/bundle. DO NOT EDIT.
//go:generate ~/gopath/bin/bundle -o x_net_proxy.go golang.org/x/net/proxy
// Package proxy provides support for a variety of protocols to proxy network
// data.
//
```
