### ISSUE TITLE
cmd/compile: DW_AT_decl_line ignores //line directives

### ISSUE THREAD

**Issue by heschik** [golang/go#23704]
### What version of Go are you using (`go version`)?
go version devel +4558321eb2 Mon Feb 5 18:37:02 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?
No, 1.9 doesn't have DW_AT_decl_line

### What did you do?

```
$ cat > linedir.go
package main

func main() {
//line /foobar.go:200
	s := "hi world"
	println(s)
}

$ go build -gcflags="-N -l" linedir.go
$ readelf --debug-dump=info linedir
```

### What did you expect to see?
`DW_AT_decl_line 200`

### What did you see instead?

```
 <2><31721>: Abbrev Number: 9 (DW_TAG_variable)
    <31722>   DW_AT_name        : s
    <31724>   DW_AT_decl_line   : 5
    <31725>   DW_AT_type        : <0x23901>
    <31729>   DW_AT_location    : 2 byte block: 91 60   (DW_OP_fbreg: -32)
```
I verified that if I introduce a syntax error the compiler reports it at 200:
```
# command-line-arguments
/foobar.go:200: syntax error: unexpected ! at end of statement
```

@thanm Presumably this boils down to https://github.com/golang/go/blob/4558321eb2f412b39df515f508f831564af1c8fe/src/cmd/compile/internal/gc/pgen.go#L422 returning the wrong thing somehow; any ideas how to fix it?

**Comment by thanm** [comment]
I'd be happy to poke and it and see what I can find out. Off the top of my head I am not sure what the issue is (the code on line 422 is just picking the pos off the autom).

**Comment by heschik** [comment]
I was mostly just hoping you knew more about the way position information works than I did. Maybe @griesemer or @mdempsky can help?

**Comment by thanm** [comment]
It looks as though perhaps the DWARF code should be using 

```
			DeclFile:      declpos.RelFilename(),
			DeclLine:      declpos.RelLine(),
```
instead of the existing

```
			DeclFile:      declpos.Base().SymFilename(),
			DeclLine:      declpos.Line(),
```
?

**Comment by heschik** [comment]
Good call. I looked at DW_AT_decl_file for functions, and it seems that's already correct, though I don't see how it happens exactly. You want to send the CL or shall I?
