### ISSUE TITLE
cmd/compile: internal compiler error: no function definition for [0xc42181a5a0]

### ISSUE THREAD

**Issue by tamird** [golang/go#23701]
### What version of Go are you using (`go version`)?
`go version go1.10rc1 linux/amd64`

### Does this issue reproduce with the latest release?
This affects the release candidate.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tduberstein/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tduberstein/local/go"
GORACE=""
GOROOT="/home/tduberstein/local/go1.10"
GOTMPDIR=""
GOTOOLDIR="/home/tduberstein/local/go1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build297022879=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
```
go get -d github.com/cockroachdb/cockroach
cd $(go env GOPATH)/src/github.com/cockroachdb/cockroach
make build PKG=./pkg/sql/pgwire
```

### What did you expect to see?
Tests run.

### What did you see instead?
```
# github.com/cockroachdb/cockroach/pkg/sql/pgwire_test
pkg/sql/pgwire/pgwire_test.go:317:45: internal compiler error: no function definition for [0xc424862960] FUNC-method(*pgwire.Server) func() []context.CancelFunc


Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
FAIL    github.com/cockroachdb/cockroach/pkg/sql/pgwire [build failed]
make: *** [Makefile:773: test] Error 2
```

**Comment by mvdan** [comment]
I assume this does not affect 1.9?

**Comment by tamird** [comment]
Correct.

**Comment by mvdan** [comment]
Have you by any chance been able to come up with a small program/package to reproduce the same crash? That project is large and a bit complex to build, so it would help the compiler developers.

**Comment by tamird** [comment]
I tried, but was not able to produce a reduced case. The defining feature
of this code is a helpers_test.go file that adds a test-only exported
method to an exported structure, but there are many examples of this
pattern in CockroachDB and this is the only one that crashes so another
ingredient must be required.

**Comment by dgryski** [comment]
Note that adding methods in a `_test.go` file is https://github.com/golang/go/issues/6204

**Comment by tamird** [comment]
@dgryski that's incorrect - in this case we're not going across packages, and this pattern works in Go 1.9.

**Comment by remyoudompheng** [comment]
Same issue on my side with the following minimal example:

$ cat a/a.go
package a

import "b"

type Type struct {}

func (*Type) M() b.T { return 0 }
$ cat b/export_test.go
package b

func (*T) Method() *T { return nil }
$ cat b/b.go
package b

type T int

type I interface { M() T }

$ cat b/b_test.go
package b_test

import (
    "testing"
    "a"
    . "b"
)

func TestBroken(*testing.T) {
    x := new(T)
    x.Method()
    _ = new(a.Type)
}

**Comment by tamird** [comment]
`a/a.go`
```golang
package a

import "b"

type Type struct {}

func (*Type) M() b.T { return 0 }
```
`b/export_test.go`
```golang
package b

func (*T) Method() *T { return nil }
```
`b/b.go`
```golang
package b

type T int

type I interface { M() T }
```
`b/b_test.go`
```golang
package b_test

import (
  "testing"
  "a"
  . "b"
)

func TestBroken(*testing.T) {
  x := new(T)
  x.Method()
  _ = new(a.Type)
}
```

Ah, I guess a second package is required.

**Comment by ianlancetaylor** [comment]
Issue #6204 says that cmd/go is supposed to reject adding methods in a _test.go file, but that it currently does not.  And indeed the code in #6204 does compile today.  I don't understand how this issue differs from #6204.

**Comment by ianlancetaylor** [comment]
Oh, never mind, I do get the same error with the test case in #6204 when I use `go test p2`.

But I still don't see why this is different than #6204.

**Comment by dgryski** [comment]
@ianlancetaylor I think the problem is 1.10 breaks an unsupported feature.

**Comment by ianlancetaylor** [comment]
CC @mdempsky @randall77

**Comment by rsc** [comment]
I think it's OK to break this in Go 1.10 but we need a better error message.

**Comment by tamird** [comment]
Going to be incovenient for CockroachDB.
```
$ find . -name helpers_test.go
./pkg/storage/idalloc/helpers_test.go
./pkg/storage/helpers_test.go
./pkg/sql/jobs/helpers_test.go
./pkg/sql/pgwire/helpers_test.go
./pkg/sql/helpers_test.go
```
/cc @bdarnell @petermattis @spencerkimball

**Comment by rsc** [comment]
I still think that it's OK to reject methods in tests if we end up needing to do that, but that doesn't look fundamental here. This looks to me like the go command is not rebuilding dependencies of test packages correctly. There was a related bug in this code a few weeks ago, and this report looks like a variant of that. It should be possible to fix this new bug and leave the disposition of #6204 for a less hurried time. I'll take a look at this for 1.10rc2, which we are thinking about doing on Wednesday.

**Comment by rsc** [comment]
This was easy to make work after the simplifications done for the build cache: basically a 1/2-line change to cmd/go, simplifying an if condition. Given that we can now rebuild perfectly, I see no reason to go out of our way to disallow adding methods in test files, even though I might wish I had done that 5+ years ago.

**Comment by dgryski** [comment]
Should the release notes be updated  to mention adding methods in a test file is now "officially" supported?

**Comment by ianlancetaylor** [comment]
Before we put it in the release notes we need to put it in the docs.  Actually I'm not sure what the release notes would say.  "This thing that used to work still works."  Personally I think this is doc-worthy but not release-notes-worthy.

**Comment by bboozzoo** [comment]
The test case provided in https://github.com/golang/go/issues/23701#issuecomment-363187224 can still be reproduced with `go1.10 linux/amd64`.

With master (`go version devel +d32018a500 Wed Mar 14 08:36:15 2018 +0000 linux/amd64`) I get this:
```
# b_test
<unknown line number>: internal compiler error: no function definition for [0xc0003706c0] FUNC-method(*b.T) func() *b.T


goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /home/maciek/code/go/go-git/src/runtime/debug/stack.go:24 +0xa7
cmd/compile/internal/gc.Fatalf(0xc50b01, 0x24, 0xc0003bb498, 0x2, 0x2)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/subr.go:182 +0x1f7
cmd/compile/internal/gc.(*hairyVisitor).visit(0xc0003bb650, 0xc000412500, 0xc000074000)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/inl.go:291 +0x7b1
cmd/compile/internal/gc.(*hairyVisitor).visitList(0xc0003bb650, 0xc0004013c0, 0xc000407860)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/inl.go:238 +0x74
cmd/compile/internal/gc.caninl(0xc000001200)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/inl.go:160 +0x186
cmd/compile/internal/gc.Main.func6(0xc00000d7c8, 0x1, 0x1, 0xc000324100)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/main.go:557 +0x164
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc0003bb810, 0xc000001200, 0x1)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/esc.go:107 +0x230
cmd/compile/internal/gc.visitBottomUp(0xc00000d7a8, 0x1, 0x1, 0xc5bcb8)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/esc.go:63 +0x95
cmd/compile/internal/gc.Main(0xc5bb98)
        /home/maciek/code/go/go-git/src/cmd/compile/internal/gc/main.go:554 +0x2e05
main.main()
        /home/maciek/code/go/go-git/src/cmd/compile/main.go:49 +0x96
```

**Comment by FiloSottile** [comment]
@gopherbot please open a 1.10 backport tracking issue. We'll need to cherry-pick both CL 92215 by @rsc and CL 104315 by @benesch.
