### ISSUE TITLE
x/tools/cmd/gotype: fails on arrays with Cgo-defined lengths

### ISSUE THREAD

**Issue by rmmh** [golang/go#23712]
### What version of Go are you using (`go version`)?
1.10rc1

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04.

### What did you do?
Use gotype (or go/types) to typecheck code that includes C declarations. Reduced test case:
```go
package gonvml

// #cgo LDFLAGS: -ldl
/*
#include "nvml.h"

nvmlReturn_t (*nvmlSystemGetDriverVersionFunc)(char *version, unsigned int length);
nvmlReturn_t nvmlSystemGetDriverVersion(char *version, unsigned int length) {
  if (nvmlSystemGetDriverVersionFunc == NULL) {
    return NVML_ERROR_FUNCTION_NOT_FOUND;
  }
  return nvmlSystemGetDriverVersionFunc(version, length);
}
*/
import "C"

// SystemDriverVersion returns the the driver version on the system.
func SystemDriverVersion() {
	var driver [C.NVML_SYSTEM_DRIVER_VERSION_BUFFER_SIZE]C.char
	C.nvmlSystemGetDriverVersion(&driver[0], len(driver))
}
```

### What did you expect to see?
No errors.

### What did you see instead?
```
$ gotype nvml.go
nvml.go:21:39: index 0 (constant of type int) is out of bounds
```

**Comment by rmmh** [comment]
One fix: change typexpr.go:378 (arrayLength) to return -1 for non-constant arrays-- this seems to be the correct option for to indicate an "error/invalid-length" array and prevent cascading errors.

I can make a CL for that (with tests) if that's the correct route.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by griesemer** [comment]
@rmmh Setting the array length to -1 works here but it's a somewhat unintended consequence of how go/types handles `[...]T{}` array literals (note that arrays always should have a constant length). I'll make the change and will add respective comments. Thanks for looking into it.
