### ISSUE TITLE
cmd/bat go build -ldflags doesn't work

### ISSUE THREAD

**Issue by golangaccount** [golang/go#23713]
### What version of Go are you using (`go version`)?
go version go1.9.1 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\project\
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
cmd: go build -ldflags "-X assembly.GitBranch=$(git symbolic-ref --short -q HEAD) -X assembly.GitHead=$(git rev-parse HEAD) -X assembly.BuildTime=$(date -format yyyyMMddHHmmss)"
it work but i write it to a .bat file and run the bat file but it not work well

code:
assembly.go
package assembly

var (
	BuildTime     string = ""              
	GitRepository string = ""              
	GitBranch     string = ""             
	GitHead       string = ""             
	GoVersion     string = ""          
)

main.go
package main

import(
	"fmt"
	"assembly"
)

func main() {
	fmt.Println(assembly.BuildTime,assembly.GitBranch,assembly.GitHead,assembly.GoVersion)
}

**Comment by bradfitz** [comment]
> it work but i write it to a .bat file and run the bat file but it not work well

That's not enough to help. How doesn't it work well? What's it do instead?

For questions about Go, see https://golang.org/wiki/Questions.

Unless there's a specific bug to track, we don't use the bug tracker for general Q&A.

Does $(cmd ..) syntax even work in cmd.exe? That's likely the issue.
