### ISSUE TITLE
gccgo: goroutine starvation

### ISSUE THREAD

**Issue by chipaca** [golang/go#23721]
### What version of Go are you using (`go version`)?

Our test suite started failing on `linux/ppc`, and so that's where I started digging:

    go version go1.6.1 gccgo (Ubuntu 6.0.1-0ubuntu1) 6.0.0 20160414 (experimental) [trunk revision 234994] linux/ppc

then once I had a minimal reproducer I confirmed it on

    go version go1.6.1 gccgo (Ubuntu 6.0.1-0ubuntu1) 6.0.0 20160414 (experimental) [trunk revision 234994] linux/amd64

and

    go version go1.8.3 gccgo (Ubuntu 7.2.0-18ubuntu2) 7.2.0 linux/amd64

as well as on the playground.

### Does this issue reproduce with the latest release?

I think the last gccgo I mention is the latest. At least, it's what's in Ubuntu 18.04.

### What operating system and processor architecture are you using (`go env`)?

`linux/ppc`, `linux/amd64`, and `nacl/amd64p32` (the playground).

### What did you do?

https://play.golang.org/p/PC3a5mD-mg0
```go
package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"time"
)

type dumbReader struct{}

func (dumbReader) Read([]byte) (int, error) {
	return 1, nil
}

func f() {
	for i := 0; i < 20; i++ {
		time.Sleep(10 * time.Millisecond)
		fmt.Print(".")
	}
	fmt.Println("<")
	os.Exit(0)
}

func main() {
	fmt.Print(">")
	go f()
	fmt.Println(io.Copy(ioutil.Discard, dumbReader{}))
}
```

### What did you expect to see?

    >....................<

### What did you see instead?

    >

The issue goes away if you set `GOMAXPROCS` to any value bigger than 1.

**Comment by bradfitz** [comment]
Dup of #10958

**Comment by bradfitz** [comment]
Leaving for @ianlancetaylor to decide whether there's something gccgo-specific here.

**Comment by ianlancetaylor** [comment]
I see nothing gccgo-specific here.  The program fails in exactly the same way with the gc compiler if I set `GOMAXPROCS=1`.  I agree that this is a dup of #10958.  Closing as dup.  (#10958 is a real bug, it just hasn't been fixed yet.)

**Comment by chipaca** [comment]
For what it's worth, I can't reproduce it on linux/amd64 with 1.6.4, 1.7.6, 1.8.5, but it blocks in 1.9.3 and 1.10rc1.
