### ISSUE TITLE
website: cannot Ctrl-F for line numbers on golang.org/src pages

### ISSUE THREAD

**Issue by alexbecker** [golang/go#23724]
Ran into this trying to debug a panic where the stack trace included `crypto/tls/common.go:717`. Ctrl-F searching for `717` on the line-numbered source code at `https://golang.org/src/crypto/tls/common.go` gave no results, leading to brief confusion and forcing me to scroll manually until I found the right line, which is much slower than using Ctrl-F.

This is because the line number nodes have no actual content, and instead are implemented as a CSS pseudo-class rule:
```css
.ln::before {
    content: attr(data-content);
}
```
and setting the `data-content` property on each line number node. This seems user-hostile and i18n-unfriendly, not to mention needlessly complex. Why not just have a line number in the DOM?

**Comment by pciet** [comment]
That CSS pattern is also the cause of https://github.com/golang/go/issues/23500

**Comment by rasky** [comment]
I think the wanted side-effect is that you can copy&paste code without selecting the line numbers, but maybe there's another way that doesn't break CTRL+F.

**Comment by pciet** [comment]
There could be two inline-divs in a div, left with a div for each line number and right containing the pre. The pre could be rendered and the dimensions taken to calculate the height for the line number divs. There may be another idiomatic approach though, my experience hasn't been with text layout.

**Comment by andybons** [comment]
@rasky is correct. This is done to prevent line numbers from appearing when you cut and paste the code.

I agree that it’s a pain not to be able to ctrl-f to line numbers. We should find a solution.

> That CSS pattern is also the cause of #23500

That bug is due to a bug in Firefox. Our usage of the `::before` pseudo-element is a common pattern in CSS.

> The pre could be rendered and the dimensions taken to calculate the height for the line number divs.

This would Introduce even more complexity as you’re then reliant on JS for your layout. Something we’d like to avoid.

**Comment by ALTree** [comment]
I personally don't like when I search in a webpage and it finds line numbers and other "background" elements... also line number are sequential, so scrolling to the line you're looking for is really quick.

You can also append `?#L717` to the url to jump at the line, e.g.

https://golang.org/src/crypto/tls/common.go?#L717

**Comment by alexbecker** [comment]
@rasky @andybons But there is already a rule
```css
.ln {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
so either one of these rules isn't necessary, or this is some weird browser compatibility hack.

@ALTree Using the anchors for lines is certainly useful, but how is a user supposed to guess that each line number has been assigned an ID of the form `Lxxx`? In contrast I think almost all users expect to be able to reach content they can see with Ctrl-F.

**Comment by andybons** [comment]
@alexbecker The spec for `user-select` is ambiguous on the _required_ behavior:

> *This specification makes no normative requirement about the behavior of the clipboard.* However, UAs are encouraged to keep the visual selection consistent with what would get copied to the clipboard when copying. Copying text that does not appear to be selected, or vice versa, is highly confusing to users.

as a result, `user-select` (and its variants) do not behave consistently with the clipboard across all browsers. At the time this code was written, the behavior was not reliable _at all_.

Firefox and Chrome 64 (released two weeks ago) implement the behavior we want. Safari is still an open bug (https://bugs.webkit.org/show_bug.cgi?id=80159). Given our desktop usage, we should change to use `user-select: none` as you propose.

**Comment by agnivade** [comment]
So, just to be clear, this issue is about removing the 
```css
.ln::before {
    content: attr(data-content);
}
```
and putting the line numbers inside the span. Because `user-select: none` behavior is now implemented properly in FF and Chrome.

Did I get that right ?

**Comment by andybons** [comment]
@agnivade yes that's correct.

**Comment by agnivade** [comment]
Cool. Waiting for 1.11 to open :smile:
