### ISSUE TITLE
Unexpect deadlock on select multi channel

### ISSUE THREAD

**Issue by ariesdevil** [golang/go#23728]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ariesdevil/Dropbox/workspace/go_workspace"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h2/xl15t9g94tgfwclshzl086bh0000gp/T/go-build125147941=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

code:  https://play.golang.org/p/8rcO11QS8un

### What did you expect to see?

I think it should not deadlock.

### What did you see instead?
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
	/tmp/sandbox682002440/main.go:23 +0x80
```

**Comment by ianlancetaylor** [comment]
A select statement evaluates all values to be sent on a channel before choosing a case.  In this example this means that `<-source` is evaluated each time you enter the select.  After the first two times, the select blocks waiting for a value to arrive.  The other goroutine then tries to send on `idle`, but nothing is listening, so it blocks.  So all goroutines are asleep.

Closing because this is working as expected.

**Comment by ariesdevil** [comment]
@ianlancetaylor thx!

**Comment by ariesdevil** [comment]
But if I put it in a goroutine, the result is confused:

https://play.golang.org/p/oUmMr8TM2sz  success
https://play.golang.org/p/54eLI7x5FwD failed

notice line 25 when I use
```
case worker := <-source:
        idle <- worker
```
instead of:
```
case idle <- <-source:
```
it works.

**Comment by ianlancetaylor** [comment]
Unlike some other projects, we don't use the issue tracker for discussion.  We only use it for bug reports.  Please take any discussion to a forum; see https://golang.org/wiki/Questions.   Thanks.

**Comment by ariesdevil** [comment]
@ianlancetaylor OK.
