### ISSUE TITLE
cmd/cgo: add test for passing arguments with typedefs compatible in C

### ISSUE THREAD

**Issue by liggitt** [golang/go#23720]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10rc1 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jliggitt/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jliggitt/go"
GORACE=""
GOROOT="/Users/jliggitt/.gvm/gos/go1.10rc1"
GOTMPDIR=""
GOTOOLDIR="/Users/jliggitt/.gvm/gos/go1.10rc1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lw/0m4r59zx3_b56vbmr2j0zkbr0000gn/T/go-build814899031=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Tried to build/test a cgo package that compiled successfully under previous versions of go

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Seen in `github.com/apcera/gssapi`, but reproduceable with similar typedefs in this program:

```go
package main

/*
typedef int *A;

typedef const int *B;

int testfunc(B f) {
	return 1;
}
*/
import "C"

func main() {
	var x C.A
	C.testfunc(x)
}
```

### What did you expect to see?

with go1.9.2:
```
go version
go version go1.9.2 darwin/amd64

cd $GOPATH/src/github.com/apcera/gssapi

go test ./
ok  	github.com/apcera/gssapi	0.049s
```

### What did you see instead?

with go1.10rc1:
```
go version
go version go1.10rc1 darwin/amd64

cd $GOPATH/src/github.com/apcera/gssapi

go test ./
# _/Users/jliggitt/go/src/github.com/apcera/gssapi
./name.go:214: cannot use n.C_gss_name_t (type _Ctype_gss_name_t) as type _Ctype_gss_const_name_t in argument to func literal
FAIL	_/Users/jliggitt/go/src/github.com/apcera/gssapi [build failed]
```

the coercion of a `gss_name_t` (typedef `struct gss_name_struct`) to `gss_const_name_t` (typedef `const struct gss_name_struct`) previously worked as expected, but go1.10rc1 now complains about it and requires an explicit cast.

gss_name_t: http://www.gnu.org/software/gss/reference/gss-api.html#gss-name-t

gss_const_name_t: http://www.gnu.org/software/gss/reference/gss-api.html#gss-const-name-t

xref https://github.com/apcera/gssapi/issues/54

**Comment by ianlancetaylor** [comment]
I believe this is due to the fix for #19832.

**Comment by liggitt** [comment]
@ianlancetaylor many thanks for the quick response. Is it possible to add a test for the broken case to ensure it doesn't slip?

**Comment by ianlancetaylor** [comment]
@liggitt In 1.11, sure.
