### ISSUE TITLE
godoc does not work with play as an option

### ISSUE THREAD

**Issue by neophyt3** [golang/go#23730]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go-work
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\PRADEE~1\AppData\Local\Temp\go-build506488887=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
C:\Users\pradeepchauhan>godoc -http=:8555 -play

### What did you expect to see?
Go documentation with playground

### What did you see instead?
This is the error I get in console
C:\Users\pradeep>godoc -http=:8555 -play
2018/02/07 23:03:34 godoc.html.Execute: template: godoc.html:58:8: executing "godoc.html" at <$.Share>: can't evaluate field Share in type godoc.Page

**Comment by bradfitz** [comment]
I think you have a version mismatch. Try updating your godoc binary? Are you using the godoc binary from a release, or built yourself?

**Comment by neophyt3** [comment]
@bradfitz 
I tried both
First with the godoc binary which is pre-packaged with the latest release
and Second way I tried by intalling the binary by go get command
and executing the same command on this (GOPATH/bin/)new binary

I am still facing the same issue with both the binaries

**Comment by bradfitz** [comment]
Thanks for the reply.

It'd be helpful if somebody else could reproduce this too.

/cc @odeke-em

**Comment by pciet** [comment]
Seen on macOS 10.12.6, go version go1.9.4 darwin/amd64

godoc -http=:8555 -play
2018/02/07 15:27:12 godoc.html.Execute: template: godoc.html:58:8: executing "godoc.html" at <$.Share>: can't evaluate field Share in type godoc.Page

![screen shot 2018-02-07 at 3 29 25 pm](https://user-images.githubusercontent.com/7949131/35942586-c8504d88-0c1b-11e8-9455-bf65aa157e70.png)

**Comment by andybons** [comment]
Sorry for the trouble. This was me.

This is fixed in go1.10, though, which will be released very soon.
