### ISSUE TITLE
runtime/race: implement race detector for ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#23731]
### What version of Go are you using (`go version`)?
Planned for go 1.11

### What operating system and processor architecture are you using (`go env`)?
ppc64le any distro

/cc @dvyukov

**Comment by laboger** [comment]
@ceseo and I are working on this, we can build golang and get the race tests to pass but now trying to get the LLVM code upstream.

**Comment by laboger** [comment]
I have the golang changes, still waiting for the latest LLVM code to be submitted upstream so the syso can be built for ppc64le. (TSAN already works on ppc64le with Clang.)

**Comment by ceseo** [comment]
@laboger LLVM changes merged into revision [330122](http://llvm.org/viewvc/llvm-project?view=revision&revision=330122).

You can proceed with your changes.

**Comment by laboger** [comment]
We need to understand how to get the syso file built so it can be added to the runtime/race directory.

**Comment by laboger** [comment]
This is in.
