### ISSUE TITLE
doc: link to better fastcgi documentation

### ISSUE THREAD

**Issue by fbbdev** [golang/go#23748]
Since the original fastcgi website went down, the fcgi module documentation [links to a web archive page](https://github.com/golang/go/blob/104445e3140f4468839db49a25cb0182f7923174/src/net/http/fcgi/fcgi.go#L9) for the fastcgi spec.

Some time ago, being the maintainer of a major fastcgi library for nodejs, I created a dedicated GitHub [organization](https://github.com/fast-cgi), [repository](https://github.com/fast-cgi/spec) and [website](https://fast-cgi.github.io) hosting both [the old page](https://fast-cgi.github.io/original) from the web archive and [a new nicely formatted version](https://fast-cgi.github.io/spec) of the spec, converted to [markdown](https://github.com/fast-cgi/spec/blob/master/spec.md).

I'm just spreading the word wherever I see dead links or links to the web archive. You could link to the new website if you like. https://fast-cgi.github.io/spec

**Comment by bradfitz** [comment]
@fbbdev, great to hear! Thanks! I'll fix our doc links.

**Comment by fbbdev** [comment]
Great, thank you!
