### ISSUE TITLE
cmd/link: linking error when build  and executed go binary on 32 bit windows OS

### ISSUE THREAD

**Issue by Rajadeepan** [golang/go#23741]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2 windows/386

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
       windows and 32 bit architecture
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_LDFLAGS=-g -02
set GO386=sse2
set GCCGO=gccgo

### What did you do?
I wanted to compile a open-source code https://github.com/ServiceComb/go-chassis and execute example(/examples/discovery/server).
The code successfully get compiled and executed in the 64-bit windows system.
But in 32bit windows system it gets build (using go build) successfully but while running the binary it is giving linking error "error while loading shared library : : cannot open shared object file": No Such file or directory.

![test](https://user-images.githubusercontent.com/13465886/35966957-64f75a90-0ce5-11e8-88ce-ed6993a9234f.png)

### What did you expect to see?
       Compile and execution should be working fine on 32 bit windows system

### What did you see instead?
       Linking error

**Comment by ianlancetaylor** [comment]
This does not look like a Go error.  It looks like a missing shared library, or perhaps you need to update the path used to find shared libraries.
