### ISSUE TITLE
net/http/httptest: Server.Start shouldn't return until it really can Accept connections

### ISSUE THREAD

**Issue by hzxuzhonghu** [golang/go#23757]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

latest

### Does this issue reproduce with the latest release?

yes

### What did you do?

After call `httptest.Server.Start` or `StartTLS`, I want the server is ready to serve any request. But unfortunately it takes some time to be ready.

**Comment by bradfitz** [comment]
> I want the server is ready to serve any request. But unfortunately it takes some time to be ready.

Why?

That's not intentional, and I've never experienced that.

If there's a problem, the fix is to make `Start` do the right thing, and not to add more API like `Wait`.

Why do you think `Start` doesn't work immediately? Got a reproducible example of a failure? Or an idea of why the code is wrong?

**Comment by davecheney** [comment]
Why does the server take time to be ready? Is this delay your code or the http package?

**Comment by hzxuzhonghu** [comment]
Because it call `Server.goServer` which start a new goroutine, and t=in theory, it takes time.

**Comment by hzxuzhonghu** [comment]
@bradfitz I think we can notify the parent goroutine when the below goroutine is running.
```golang
func (s *Server) goServe() {
	s.wg.Add(1)
	go func() {
		defer s.wg.Done()
		s.Config.Serve(s.Listener)
	}()
}
```

**Comment by bradfitz** [comment]
But the `net.Listener` is already listening before that's called. So it'll still accept the connection, and then in a tiny amount of time (under milliseconds) it'll handle it.

I see no problem.

**Comment by hzxuzhonghu** [comment]
Oh, so i missed the listener.

**Comment by bradfitz** [comment]
No worries. Glad there's not a problem to fix. :)

**Comment by hzxuzhonghu** [comment]
Thank you .
