### ISSUE TITLE
cmd/go: go run: triggers Symantec malware alert.

### ISSUE THREAD

**Issue by chopraaa** [golang/go#23759]
### What version of Go are you using (`go version`)?

`go version go1.9.4 windows/amd64`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\-snip-\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?
I ran the following program:

```
package main

import "fmt"

func main() {
  fmt.Println("1 + 1 =", 1 + 1)
  fmt.Println("1 + 1 =", 1.0 + 1.0)
}
```

### What did you expect to see?
```
1 + 1 = 2
1 + 1 = 2
```

### What did you see instead?
```
exit status 3221225506
```
Symantec got triggered. https://www.symantec.com/security_response/writeup.jsp?docid=2017-032721-5748-99&vid=4294924267

**Comment by bradfitz** [comment]
Sorry, but there's nothing we can do about this. This is Symantec's fault. You should escalate with them.

**Comment by dsymonds** [comment]
@bradfitz: This issue has been coming up for years, and still keeps coming up (e.g. cayleygraph/cayley#696). Should it at least get a FAQ entry?

**Comment by bradfitz** [comment]
Like?

**Q: My virus scanner says there's a virus with the Go distribution or my compiled Go binary!**
*A: That's almost certainly a false positive. Virus scanners seem to get confused by Go programs. Please report a bug to your virus scanner vendor.*

/cc @robpike

**Comment by dsymonds** [comment]
Yes, that would certainly be a good improvement over the current state of affairs.
