### ISSUE TITLE
x/build/cmd/gerritbot: editing a title or description should update the Gerrit change

### ISSUE THREAD

**Issue by andybons** [golang/go#23756]
In [this change](https://go-review.googlesource.com/c/go/+/92997) the title needs to be adjusted, but it won't get imported unless the PR branch's HEAD SHA changes. We should detect differences in the title and import if need be.

**Comment by shurcooL** [comment]
This is also affecting PR https://github.com/golang/tools/pull/26#issuecomment-368262382.
