### ISSUE TITLE
database/sql: improve documentation for DB.Close() (graceful close or not)

### ISSUE THREAD

**Issue by pjebs** [golang/go#23753]
The documentation doesn't make clear what DB.Close() does.

Does it close the Pool immediately even if there are still queries happening in some of the connections, or does it wait for the queries to finish and gradually closes the connections and then closes the pool?

**Comment by ianlancetaylor** [comment]
It's generally best to ask questions in a forum, which is where more people will see them.  See https://golang.org/wiki/Questions .

I don't actually know the answer to this.

**Comment by kardianos** [comment]
That's reasonable doc request. I'll look into.

**Comment by pjebs** [comment]
I was wondering what the answer was to this question?

**Comment by kardianos** [comment]
@pjebs Can you inspect the above CL and see if that answers your question?

**Comment by pjebs** [comment]
Answers the question.
