### ISSUE TITLE
cmd/compile: crash on freebsd/386

### ISSUE THREAD

**Issue by yurivict** [golang/go#23763]
No error message:
```
/usr/local/go/pkg/tool/freebsd_386/compile -o $WORK/github.com/hashicorp/nomad/nomad/deploymentwatcher.a -trimpath $WORK -goversion go1.9.3 -p github.com/hashicorp/nomad/nomad/deploymentwatcher -complete -buildid d3001a508b685a6e0bc1f2ef258eec506bf37805 -importmap github.com/hashicorp/go-memdb=github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-memdb -importmap golang.org/x/time/rate=github.com/hashicorp/nomad/vendor/golang.org/x/time/rate -D _/wrkdirs/usr/ports/sysutils/nomad/work/nomad-0.7.1/src/github.com/hashicorp/nomad/nomad/deploymentwatcher -I $WORK -I /wrkdirs/usr/ports/sysutils/nomad/work/nomad-0.7.1/pkg/freebsd_386 -pack ./batcher.go ./deployment_watcher.go ./deployments_watcher.go
*** Error code 2
```

The easiest way to reproduce:
* Have FreeBSD i386 system
* cd /usr/ports/sysutils/nomad
* Comment out ONLY_FOR_ARCHS=        amd64
* make

**Comment by bradfitz** [comment]
You deleted the bug template so I have to ask some basic questions, like: which version of Go?

Which version of nomad? (which version is your ports at)

Which version of FreeBSD?

**Comment by yurivict** [comment]
Sorry:
* FreeBSD 10.3-RELEASE-p26 i386 (I suspect the same on other i386 versions)
* go-1.9.3,1
* nomad-0.7.1

**Comment by davecheney** [comment]
Does nomad compile successfully outside the ports system? Can you install it with the usual go get / go install dance (or however nether nomad docs instruct you to build it)

**Comment by yurivict** [comment]
> Does nomad compile successfully outside the ports system?

I can't try this easily, I run port builds in a i386 virtual machine.

**Comment by bradfitz** [comment]
How notable is i386 in this bug report? Does it pass on amd64 but only fail on i386?

**Comment by yurivict** [comment]
Yes, amd64 passes and only i386 fails.

**Comment by bradfitz** [comment]
> Yes, amd64 passes and only i386 fails.

If you can test it easily, what about 32-bit processes on 64-bit kernel?

That is, set `GOARCH=386` on an amd64 kernel and try to build it?

**Comment by yurivict** [comment]
> That is, set GOARCH=386 on an amd64 kernel and try to build it?

This crashes too.

**Comment by cherrymui** [comment]
I just tried `GOARCH=386 GOOS=freebsd go get -v github.com/hashicorp/nomad/nomad`, and it failed because `github.com/hashicorp/nomad/vendor/github.com/mitchellh/go-ps` doesn't build.

```
# github.com/hashicorp/nomad/vendor/github.com/mitchellh/go-ps
pp/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/go-ps/process.go:31:9: undefined: processes
pp/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/go-ps/process.go:39:9: undefined: findProcess
```

I think this is because it doesn't support freebsd/386: https://github.com/hashicorp/nomad/blob/master/vendor/github.com/mitchellh/go-ps/process_freebsd.go#L1, it is amd64 only.

I think the original error, `/usr/local/go/pkg/tool/freebsd_386/compile -o $WORK/github.com/hashicorp/nomad/nomad/deploymentwatcher.a ...`, is just happened to be the last action it did before failing.

**Comment by yurivict** [comment]
These messages:
```
vendor/github.com/mitchellh/go-ps/process.go:31:9: undefined: processes
vendor/github.com/mitchellh/go-ps/process.go:39:9: undefined: findProcess
```
are missing the usual "error:" label so that they can't be easily detected.

**Comment by yurivict** [comment]
https://github.com/mitchellh/go-ps/issues/28
