### ISSUE TITLE
text/scanner: add examples

### ISSUE THREAD

**Issue by awoodbeck** [golang/go#23768]
I recently worked with the text/scanner package and, although the documentation was straight forward, it could stand to use more [examples](https://golang.org/pkg/text/scanner/#pkg-examples).

I've been looking for opportunities to contribute to Go and I wouldn't mind working on improving the examples of the text/scanner package.  I would like to add examples detailing the use of white space modifiers and tokens, as well as the various scanner and position methods.  I would keep each example succinct, of course.

Are there particular guidelines to follow when it comes to examples?

**Comment by ALTree** [comment]
- for package-level examples, I would go with high-level, broad, well commented examples that show how to use the `text/scanner` package to *accomplish* something. Like the ones you can see for the sort package under the `Overview` section here: https://golang.org/pkg/sort/

- for function-level example, I would go with small, ideally auto-contained snippets that show how to setup and call the function. I suggest don't bothering to do this for functions that are extremely easy to use. An example that shows how to call a math function that take one argument, like this `sq := math.Sqrt(x)` is not useful.

**Comment by awoodbeck** [comment]
Is it most appropriate to post examples here for discussion before opening a CL?

**Comment by andybons** [comment]
You should just open a CL.

Generally we ask that people don’t send code reviews until it’s agreed upon that a proposal should be implemented (adding a new package, changing something non-trivial). For documentation changes like adding examples, it’s reasonable to simply send out the code review and have a discussion there.

**Comment by awoodbeck** [comment]
Is there anything I can do to facilitate a review of my CL?  I'm new to the Golang CL process and don't know really what to expect.

**Comment by ALTree** [comment]
According to the owners file, Robert owns the `text/scanner` package. Add him (gri@golang.org) as a reviewer in the CL on gerrit using the `ADD REVIEWER` button.
