### ISSUE TITLE
mime: should application/x-javascript be changed to application/javascript ?

### ISSUE THREAD

**Issue by romainmenke** [golang/go#23767]
https://github.com/golang/go/blob/829b64c1ead819bdf84d950581020c36f00cd02b/src/mime/type.go#L65

### What did you do?

Serve javascript files with go. The application runs in a docker container based on **golang:1-alpine**

What did you expect to see?

`Content-Type : application/javascript`

What did you see instead?

`Content-Type : application/x-javascript`

-------

Illustration did not fit in a playground : [runnable example](https://github.com/romainmenke/application-javascript)

relevant? [rfc4329](http://www.rfc-editor.org/rfc/rfc4329.txt)

As far as I can tell **golang:1-alpine** doesn't come with any registered mime types. This means that only the built in types are used for content type sniffing. `application/javascript` is not included in the built in types.

Should `application/javascript` be included and (separately) should `application/x-javascript` be removed?

**Comment by ALTree** [comment]
This is #7498, which is still open. There was a CL (https://codereview.appspot.com/73070043) but (from the old thread):

> According to Brad's comment on the CL, we need more proof that change is safe in the wild.

and then the discussion stalled and the change was not merged.

**Comment by ALTree** [comment]
I've moved the old thread to the 1.11 milestone and tentatively labelled as "NeedsDecision" to give it a chance to be looked at in the near future. I guess you can comment in the old thread if you have any insights on why this would be a needed (and safe) change, to keep all the discussion in one place. I suggest we close this as a dup of #7498.

**Comment by romainmenke** [comment]
@ALTree Yes this can be closed as it is indeed a duplicate (search failed me, or overlooked it). Thank you for the fast response.
