### ISSUE TITLE
sync/atomic: FreeBSD/ARM Load* Store* implementations missing memory barriers

### ISSUE THREAD

**Issue by paulzhol** [golang/go#23778]
https://github.com/golang/go/blob/829b64c1ead819bdf84d950581020c36f00cd02b/src/sync/atomic/asm_freebsd_arm.s#L58-L66

The runtime/internal/atomic version is using memory barriers correctly in the underlying armcas:
https://github.com/golang/go/blob/829b64c1ead819bdf84d950581020c36f00cd02b/src/runtime/internal/atomic/asm_arm.s#L21-L50

**Comment by ianlancetaylor** [comment]
CC @cherrymui

**Comment by bcmills** [comment]
I'm probably missing something, but why do we have so many `GOOS` variations for `atomic.{Load,Store}Uint32` in the first place?

(I understand why we have one for Linux (because it provides a built-in implementation), but why shouldn't the fallback implementation be the same for every other OS?)

**Comment by randall77** [comment]
@bcmills The fallback implementation is the same for all the other OSes.
(e.g. sys_netbsd_arm.s just redirects to asm_arm.s)

**Comment by bcmills** [comment]
> sys_netbsd_arm.s just redirects to asm_arm.s

That seems to be true for most of the functions, but not `atomic.{Load,Store}Uint32`:

https://github.com/golang/go/blob/04e6ae6bc3ac9739568b0f1225ee5e2d53cba919/src/sync/atomic/asm_freebsd_arm.s#L58-L66

...or am I missing something more subtle to it?

**Comment by randall77** [comment]
@bcmills Sorry, you are right.  I was looking at `runtime/internal/atomic`, not `sync/atomic`.

**Comment by cherrymui** [comment]
@bcmills I don't see a good reason not to unify those.
