### ISSUE TITLE
net/http: add 421 status codes into status.go

### ISSUE THREAD

**Issue by ryysud** [golang/go#23776]
The following HTTP status codes are registered in [the HTTP Status Code Registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml), but they are not defined in the net/http package ([status.go](https://github.com/golang/go/blob/master/src/net/http/status.go)) .

- 103 Early Hints [[RFC8297](https://tools.ietf.org/html/rfc8297)]
- 421 Misdirected Request [[RFC7540, Section 9.1.2](https://tools.ietf.org/html/rfc7540)]

Is there a reason not to define them?

**Comment by odeke-em** [comment]
Hello there @ryysud, thank you for raising this issue and welcome to Go!

Interesting, TIL. So from what I can quickly examine:
* 103 just got added in December 2017 and seems experimental https://tools.ietf.org/html/rfc8297
<img width="647" alt="screen shot 2018-02-11 at 1 58 20 am" src="https://user-images.githubusercontent.com/4898263/36072118-15dc8e94-0ecf-11e8-9204-20afcd5b02f8.png">

 * 421 Misdirected request, perhaps that's a complex interaction with crypto/tls and x/net/http2 so I'll page the wizards @tombergan @bradfitz @agl @rs

**Comment by bradfitz** [comment]
I'm fine adding 421. Let's wait on 103 until it's finalized.

**Comment by ryysud** [comment]
@odeke-em 
Thank you for your investigation.

@bradfitz 
Thank you for the review.
Should I remove 103 from the CL?

**Comment by meirf** [comment]
FWIW there is some discussion of 421 in https://github.com/golang/go/issues/18341.

**Comment by bradfitz** [comment]
> Should I remove 103 from the CL?

Yes.

**Comment by ryysud** [comment]
@bradfitz I removed 103 from the CL.
