### ISSUE TITLE
access: Trybot Access ("may-start-trybots")

### ISSUE THREAD

**Issue by namusyaka** [golang/go#23770]
See https://golang.org/wiki/GerritAccess

----

Requested access: Trybot Access ("may-start-trybots") https://go-review.googlesource.com/#/admin/groups/1030,members

All my gardening issues: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Anamusyaka+
All my participating CLs: https://go-review.googlesource.com/q/namusyaka%2540gmail.com

My gerrit name: Kunpei Sakai
My gerrit email: namusyaka@gmail.com

This is my second challenge.
And, in response to the previous @bradfitz's opinion, I am working not only to my specialty field but also bug fixes such as compiler, and I am going to keep interesting in the future.

/cc @bradfitz @ianlancetaylor @robpike  @rsc

**Comment by bradfitz** [comment]
Added.

**Comment by namusyaka** [comment]
@bradfitz I'm very pleased. Thank you!
