### ISSUE TITLE
cmd/compile: imperfect error message for too large index in slice composite literal

### ISSUE THREAD

**Issue by dotaheor** [golang/go#23781]
### What version of Go are you using (`go version`)?

go version go1.9.3 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
	const k int64 = 1 << 31
	_ = []int{k:1} // error: index must be non-negative integer constant
}
```

### What did you expect to see?

compile ok, or with error
```
./a.go:10:13: index is too large
```

### What did you see instead?

fail to compile, with error
```
./a.go:10:13: index must be non-negative integer constant
```

From Go spec. (in array and slice literals)
```
The key must be a non-negative constant representable by a value of type int;
and if it is typed it must be of integer type. 
```

`1 << 31` is representable by a value of type int on 64-bit OS, and it is non-negative.

**Comment by dotaheor** [comment]
And this:
```
package main

func f() {
	_ = []byte{1 << 31} // error: constant 2147483648 overflows byte
	// Here "overflows byte" should be "overflows int"?
}

func g() {
	_ = []int16{1 << 31} // error: constant 2147483648 overflows int16
	// Here "overflows int16" should be "overflows int"?
}

func main() {
	s := []byte{}
	_ = s[1 << 62] // compile ok
	_ = s[1 << 63] // error:  constant 9223372036854775808 overflows int
	// I think the rules for the indexes in literal and index in [] should be consistent.
}
```

**Comment by ALTree** [comment]
This happens because the `smallinstconst` function in `const.go` has the following code:

```
if !ok || vi.CmpInt64(0) < 0 || vi.Cmp(maxintval[TINT32]) > 0 {
	return -1
}
```

The key you used fails the last check (`vi.Cmp(maxintval[TINT32]) > 0`) because `maxintval[TINT32]` is `0x7fffffff` which is smaller than `1<<31`, so the function returns `-1` to signal a key error.

The problem here is that AFAIK we can't just easily remove the check above, because there are several places in the compiler (both the frontend and the backend) where those values are assumed to be `int32`s.

cc @griesemer @randall77

**Comment by ALTree** [comment]
I guess we could change `smallinstconst` to better signal the kind of errors it encounters, and make the callers actually check before returning a `must be positive` error. We could add a second error that says "too big". 

I'll send a patch for 1.11 if this sounds good.

**Comment by griesemer** [comment]
FWIW, both go/types and gccgo accept this code w/o problems. gccgo can also run it (again w/o problems).
