### ISSUE TITLE
x/tools/imports: consider exporting fixImports

### ISSUE THREAD

**Issue by eikenb** [golang/go#23782]
This is a 3 character change that  would make this module much more useful for people working on custom formatting solutions. Without this you need to format the code and then re-parse it to get the ast with the fixed imports which is very inefficient.

### What version of Go are you using (`go version`)?
1.9/tip

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
Wanted to fix the imports at the ast.File level using the x/tools/imports lib.

### What did you expect to see?
fixImports should be FixImports so it is public and can be used when working with ast's vs. files.

### What did you see instead?
It is not public and I am forced to fork the project to use it.

**Comment by bradfitz** [comment]
> This is a 3 character change

FWIW, the cost of this change isn't measured in characters or lines modified. It's a question of how much ongoing maintenance cost there is keeping this a stable interface for people to use long-term and whether that's even the API we want people using.

**Comment by eikenb** [comment]
I understand the trade-offs and for my case think it is worth it (obviously). It seems like it follows in the spirit of the module, just at a lower level and the API for that function is very direct to work with when dealing with ASTs. Thank you for considering it.

**Comment by eikenb** [comment]
If deemed a good change I'll be happy to submit a pull request with the change to help things along. I plan on maintaining this as a fork in the meantime, so I'll have it ready. Thanks again.

**Comment by eikenb** [comment]
Went ahead and created the Pull Request to facilitate the decision.

**Comment by shurcooL** [comment]
This issue seems related to #12696. Although I don't know how exporting only `FixImports` helps.

The PR doesn't seem to help facilitate the decision, because it doesn't communicate why `FixImports` being exported makes sense and how it helps. It just implements it, but this issue is still in NeedsDecision state.

It would help if you provided more information about how it'd be used, etc.

**Comment by eikenb** [comment]
The use case is when you want to update the imports in the AST without the text. For example I'm writing a custom formatter, to format code in a presentation like style, and wanted the import fix. I considered forking or just copying out the needed code, but thought it might be generally useful and it'd be better to not duplicate the functionality if unnecessary.

**Comment by heschik** [comment]
We have exposed an internal interface to the imports package that might suit your needs, but I don't think we're going to make it public. Feel free to fork `x/tools` to expose it, at your risk of course.
