### ISSUE TITLE
x/build: Android emulator builders sometimes fail with: go_android_exec: no exit code: ""

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#23795]
For example:

https://build.golang.org/log/f8a11e4d226addf61b7bb461663e63e34b699783 (android/amd64)
https://build.golang.org/log/a30de87209a4b63ed9fc511199bfcbe2aade16e9 (android/386)

I seems to be a bug in adb. I reported it here:

https://issuetracker.google.com/issues/73230216

**Comment by mvdan** [comment]
It seems like the upstream issue hasn't seen any activity, unfortunately. I count 6 occurrences just in the first page of build.golang.org, which makes it the most common flake on the Android builders by far.

**Comment by eliasnaur** [comment]
Yes, and the issue also blocks my hope of having android emulator builders in the trybot set. If it's not too inappropriate to ask, could someone at Google prod the Android team for progress on the upstream issue?
