### ISSUE TITLE
spec: type alias identity unclear

### ISSUE THREAD

**Issue by gbbr** [golang/go#23790]
In the "Type Alias" [proposal](https://github.com/golang/proposal/blob/master/design/18130-type-alias.md#proposal) by Russ Cox & Robert Griesemer it is specified that:
> After such a declaration, T1 and T2 are identical types.

Given the above, I think that this should be made more obvious within the spec in either the [_Type Identity_](https://golang.org/ref/spec#Type_identity) section or the [_Type Declarations_](https://golang.org/ref/spec#Type_declarations), _"Alias declarations"_ sub-section.

**Comment by griesemer** [comment]
@gbbr Can you be a bit more precise about what you are looking for? The Alias declaration sub-section seems pretty clear; there's even an example that emphasizes (with a comment) that the alias and the literal type on the right of the alias declaration are identical.

**Comment by gbbr** [comment]
You are right, sorry about that. Not sure how I've managed to miss that comment.

**Comment by griesemer** [comment]
@gbbr No worries! Thanks for closing the issue.
