### ISSUE TITLE
cmd/go: help list not ordered correctly

### ISSUE THREAD

**Issue by rsc** [golang/go#23791]
"go help" shows a list of commands that follows the list in the source code.
The one in the source code is meant to be kept sorted.
Clearly it is not: "go bug" appears between "go env" and "go fix"
in the "go help" output. We should fix that.

**Comment by nathanwilk7** [comment]
Fixed in https://go-review.googlesource.com/c/go/+/93416 and submitted for review.

Changed order of elements in base.Commands in main.go so that output is alphabetical.

This is my first PR for go, any feedback is appreciated, thanks.
