### ISSUE TITLE
cmd/go: duplicate vendored packages listed by go list -f {{.Deps}}

### ISSUE THREAD

**Issue by robpike** [golang/go#23802]
```
go version devel +8f7805f9ce Tue Jan 30 13:43:42 2018 +1100 darwin/amd64
```

I ran this command and got this output:

```
% go list -f '{{join .Deps "\n"}}' upspin.io/transports  | sort -u  | grep bidi
upspin.io/vendor/golang.org/x/text/secure/bidirule
upspin.io/vendor/golang.org/x/text/unicode/bidi
vendor/golang_org/x/text/secure/bidirule
vendor/golang_org/x/text/unicode/bidi
% 
```

It may just be a reporting problem, but I find it troubling that the same packages are listed twice, with the `vendor/...` ones not even being legal import paths.

**Comment by bradfitz** [comment]
That's correct output.

You have two copies of those packages in your program: the ones privately vendored by the standard library, and the ones you're using from upspin.

The illegal import paths are on purpose to work around a bug. #17326 is already open to track that.

Not sure there's anything to do here.

**Comment by robpike** [comment]
For some reason I checked to see if they were vendored by the Go repo and concluded they weren't; I clearly made an error. Closing.

Vendoring has got to go.
