### ISSUE TITLE
Exception 0xc0000005  

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#23810]
Exception 0xc0000005 0x0 0x0 0x203a62a2
PC=0x203a62a2

runtime: unknown pc 0x203a62a2
stack: frame={sp:0x2edfeec, fp:0x0} stack=[0x2de1f34,0x2edff34)
02edfe6c:  ba53fbbb  000001f5  66aa0a37  00000036
02edfe7c:  438d8e29  4025af7b  7ff6f69a  00000018
02edfe8c:  3a5d0521  000001dd  53a9f184  000001bf
02edfe9c:  7ff6f69a  00000018  3a5d0521  000001dd
02edfeac:  53a9f184  000001bf  03490e60  203a2000
02edfebc:  0050bf57  00000000  025c47e8  0050bf5e
02edfecc:  2036a300  2038ff28  203a6000  00000108
02edfedc:  00448644 <runtime.asmcgocall+84>  2038ff28  00000108  203a62a0
02edfeec: <00000001  01000000  203a6000  00447267 <runtime.mcall+71>
02edfefc:  203a6380  00000000  006c0000  0050cd9b
02edff0c:  00000000  00000000  006cd6d0  02edff80
02edff1c:  0050cd16  00429cb0 <runtime.mstart+0>  753926e0  75393ae8
02edff2c:  006ccdf0  02edff10
runtime: unknown pc 0x203a62a2
stack: frame={sp:0x2edfeec, fp:0x0} stack=[0x2de1f34,0x2edff34)
02edfe6c:  ba53fbbb  000001f5  66aa0a37  00000036
02edfe7c:  438d8e29  4025af7b  7ff6f69a  00000018
02edfe8c:  3a5d0521  000001dd  53a9f184  000001bf
02edfe9c:  7ff6f69a  00000018  3a5d0521  000001dd
02edfeac:  53a9f184  000001bf  03490e60  203a2000
02edfebc:  0050bf57  00000000  025c47e8  0050bf5e
02edfecc:  2036a300  2038ff28  203a6000  00000108
02edfedc:  00448644 <runtime.asmcgocall+84>  2038ff28  00000108  203a62a0
02edfeec: <00000001  01000000  203a6000  00447267 <runtime.mcall+71>
02edfefc:  203a6380  00000000  006c0000  0050cd9b
02edff0c:  00000000  00000000  006cd6d0  02edff80
02edff1c:  0050cd16  00429cb0 <runtime.mstart+0>  753926e0  75393ae8
02edff2c:  006ccdf0  02edff10

goroutine 19 [syscall]:
GoProxy/monicore._Cfunc_ReqProc(0x34816c2, 0x0, 0x25c47e8, 0x25c3488, 0x0)
        _cgo_gotypes.go:69 +0x3f
GoProxy/monicore.ReqProc.func1(0x34816c2, 0x0, 0x25c47e8, 0x25c3488, 0xe7ab1db0)

        C:/Users/zhaoya16975/go/src/GoProxy/monicore/pluginwin.go:55 +0xc7
GoProxy/monicore.ReqProc(0x203aba00, 0x0, 0x25c47e8, 0x25c3488, 0x0)
        C:/Users/zhaoya16975/go/src/GoProxy/monicore/pluginwin.go:55 +0x3c
GoProxy/monicore.(*Processer).run(0x203abe00)
        C:/Users/zhaoya16975/go/src/GoProxy/monicore/processer.go:110 +0x32b
created by GoProxy/monicore.(*Processer).OnStart
        C:/Users/zhaoya16975/go/src/GoProxy/monicore/processer.go:46 +0x33

goroutine 1 [select (no cases)]:
main.main()
        C:/Users/zhaoya16975/go/src/GoProxy/main/gseeproxy.go:51 +0x296
eax     0x0
ebx     0x448644
ecx     0x203a2030
edx     0x36c1848
edi     0x108
esi     0x2038ff28
ebp     0x203a2000
esp     0x2edfeec
eip     0x203a62a2
eflags  0x10246
cs      0x23
fs      0x53
gs      0x2b

code：
int ReqProc(TBizFunctionEntry lpfunc ,void * lpContext, void* lpRequest,void* lpAnswer){
	return lpfunc(lpContext, lpRequest,lpAnswer);
}
*/
import "C"

import "syscall"
import "fmt"
import "unsafe"

type FuncInfo struct {
	uwFuncNo      uint32
	iVersion      int
	sCaption      string
	lpReqProcFunc C.TBizFunctionEntry
	//lpReqProcFunc interface{}
}

var FuncList map[uint32]*FuncInfo

func ReqProc(lpdesc *FuncInfo, lpContext unsafe.Pointer, lpRequest unsafe.Pointer, lpAnswer unsafe.Pointer) int {
	proc := lpdesc.lpReqProcFunc
	return int(C.ReqProc(proc, lpContext, lpRequest, lpAnswer))
}

**Comment by bradfitz** [comment]
This isn't a complete bug report. It's not even clear what the question is, if any.

Please file a complete bug report using the default template (which you deleted), or ask your question in one of the forums. See https://golang.org/wiki/Questions.
