### ISSUE TITLE
spec: review/clarify uses of "slice of bytes"

### ISSUE THREAD

**Issue by griesemer** [golang/go#23814]
This is a follow-up issue for #23536: Comb through documentation (spec, builtins) to verify the use of the term "slice of bytes". The spec appears to mean by this any type whose underlying type is `[]byte`. But not all implementations agree.

**Comment by mdempsky** [comment]
I just ran into this issue. I think it's valuable to at least come to a shared agreement on what we think the right behavior is, so we can start aligning the implementations.

I think the spec cases relevant here are:

1. Conversions: string -> []byte, string -> []rune, []byte -> string, []rune -> string
2. copy([]byte, string)
3. append([]byte, string...)

My 2c is that this should type check allowed:

```
package p

type (
	String string
	Byte   byte
	Bytes  []Byte
	Rune   rune
	Runes  []Rune
)

var (
	_ = Bytes(String(""))
	_ = Runes(String(""))

	_ = String(Bytes(nil))
	_ = String(Runes(nil))

	_ = copy(Bytes(nil), String(""))
	_ = append(Bytes(nil), String("")...)
)
```

gccgo accepts this.

cmd/compile and go/types currently reject the `copy` call, claiming that `Bytes`'s element type (`Byte`) is different from `byte`.

go/types currently additionally rejects the `append` call too.

(Also notably, cmd/compile's typechecker allows `String(Bytes(nil))` and `String(Runes(nil))`, but then walk.go fails to generate the appropriate conversions when calling runtime.slicebytetostring and runtime.slicerunetostring, so compilation fails.)

**Comment by griesemer** [comment]
@rsc, @ianlancetaylor, @robpike Do you have any opinions here?

We're inconsistent at the moment and different implementations (cmd/compile, gccgo, go/types) differ for operations where this matters.

**Comment by bradfitz** [comment]
Personally, if there's any ambiguity that needs to be specified, I'd prefer to be a permissive as possible, letting copies/appends/conversions work as expected if the underlying representation is the same.

**Comment by ianlancetaylor** [comment]
I'm inclined to agree with @mdempsky 's comment https://github.com/golang/go/issues/23814#issuecomment-536082226 .   I don't see any particular reason to restrict operations on a "slice of bytes" to only the type `[]byte`.

**Comment by josharian** [comment]
I just rediscovered this in #36965.

Is there sufficient consensus here that I can fix cmd/compile’s implementation to use a maximally liberal interpretation of “byte slices?

Other things to check on once the desired direction is clear: is the spec clear enough? Do go/types, package reflect, cmd/compile, and gccgo agree?

**Comment by josharian** [comment]
(The reason I’d like to fix cmd/compile now/soon is that I’m touching this code anyway for #36890.)

**Comment by griesemer** [comment]
@josharian The reason for this issue is that [not all implementations](https://github.com/golang/go/issues/23814#issue-296848081) agree. @mdempsky 's [comment](https://github.com/golang/go/issues/23814#issuecomment-536082226) explains how they disagree.

I think we should first get the spec to be crystal clear before making changes. It sounds like we're leaning towards making the interpretation more liberal, so this should not break future code, but enable more. This is not urgent, either.

**Comment by griesemer** [comment]
Marking for Go 1.15.

**Comment by griesemer** [comment]
It looks like the consensus here is that "slice of bytes" should be maximally liberal, which would mean any slice of elements whose underlying type is bytes.

**Comment by ianlancetaylor** [comment]
@griesemer This issue has milestone 1.18; shall we move to 1.19 or backlog?

**Comment by griesemer** [comment]
This is documentation that we might be able to address. Prefer to leaving open for now.

**Comment by griesemer** [comment]
Moving to 1.19.

**Comment by griesemer** [comment]
The above CL adjusts the spec to interpret slice of bytes/runes in the most liberal way (underlying type of the slices' element types must be `byte`/`rune`) for _conversions_. This matches the current implementation (and closely matches 1.17 - see the CL description).

The behavior for `copy`/`append` is (and always was) more strict; also, also no explicit conversion happens in those cases, so the more strict behavior can be justified.

Since this issue is about "slice of bytes/runes", terminology that is only used in the Conversions section of the spec, the CL addresses only that aspect.

If we want to change the behavior for append/copy, we probably need to file a mini-proposal.

**Comment by go101** [comment]
Maybe, the reflect implementation should also be made consistent with this change: https://github.com/golang/go/issues/23536#issuecomment-1007877545

**Comment by griesemer** [comment]
@go101 Filed #53523.
