### ISSUE TITLE
cmd/compile: better error message for failed string conversion

### ISSUE THREAD

**Issue by griesemer** [golang/go#23813]
https://play.golang.org/p/8ADwHokqcK5 complains with:
```
prog.go:6:12: cannot use x (type []T) as type []byte in argument to runtime.slicebytetostring
```
The error message should not mention `runtime.slicebytetostring` which is an implementation detail.

(There are probably more error situations that expose runtime calls this way. Should handle them all uniformly.)

**Comment by griesemer** [comment]
Has been like this for a while. Moving to 1.12.

**Comment by griesemer** [comment]
We should wait with fixing this depending on the resolution of #23536. It's not just go/types. The compiler also seems not consistent.

**Comment by dominikh** [comment]
The error has gotten worse:

```
./prog.go:6:12: cannot use <node SPTR> (type *T) as type *byte in argument to runtime.slicebytetostring
```

**Comment by griesemer** [comment]
[This](https://go.dev/play/p/KYUrmSSDcgf) is now working without error in Go 1.18. Closing.
