### ISSUE TITLE
Feature request: profiling support for regular tests

### ISSUE THREAD

**Issue by dbkaplun** [golang/go#23811]
It would be great if I could profile tests (or code in general) without having to write new code.

Currently, to profile tests via `-cpuprofile`, I have to contort my tests to get picked up by the profiler. I have to change all `Test*` functions to be called `Benchmark*`. To do so, I run something like this:
```sh
find . \
  -iname '*_test.go' \
  -not -path '*/vendor/*' \
    | xargs sed -Ei 's/(func )Test(\w+[(]t \*testing\.)T/\1Benchmark\2B/g'
```
Clearly not ideal.

However, the output that this generates is **exactly** what I'm looking for. The function graph is perfectly generated as I would expect. It would be great if I could easily profile tests without jumping through hoops.

Thanks for considering!

**Comment by hyangah** [comment]
The -cpuprofile flag should work with Test* functions and there is no need to change them to be Benchmark functions. One caveat is that if the test function ends very quickly, it's possible that the execution is not sampled at all. (The current cpu profile rate is 100Hz.) 

Maybe that's why renaming Test functions to Benchmark functions cause to capture the samples - benchmark framework may call the benchmark functions multiple times under the hood, so some samples are captured.

**Comment by dbkaplun** [comment]
With `go tool pprof cpu.prof`, running `web` gives me this: (go version go1.9.2 darwin/amd64)
![screen shot 2018-02-13 at 5 36 56 pm](https://user-images.githubusercontent.com/1765130/36177693-85618028-10e4-11e8-995d-a562711325d7.png)

Exact command:
```sh
go test \
  -timeout 20m \
  -v \
  -coverprofile="coverage-\${pkg//\//-}.out" \
  -cpuprofile cpu.prof -bench .  "\$pkg";
```

**Comment by hyangah** [comment]
The -bench flag used in the profile makes only Benchmark* functions run. 
Also, see my previous comment - if the tested function is a trivial function to run, it's unlikely that any meaningful sample is collected.

**Comment by dbkaplun** [comment]
@hyangah have you tried it yourself? I get the exact same empty output with this command:
```sh
go test \
  -timeout 20m \
  -v \
  -coverprofile="coverage-\${pkg//\//-}.out" \
  -cpuprofile cpu.prof  "\$pkg";
```

The tests are non-trivial, many of which take a few seconds to run.

**Comment by hyangah** [comment]
Yes, here is the profile output from tests in src/runtime/trace 
![something](https://user-images.githubusercontent.com/4999471/36179086-fc152c8e-10e8-11e8-9cc3-8113cbfe99d6.png)

**Comment by dbkaplun** [comment]
The .prof file was being overwritten by another .prof for a package with no tests.
