### ISSUE TITLE
cmd/compile: crash on interface embedding cycles if a type alias is used

### ISSUE THREAD

**Issue by go101** [golang/go#23823]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10rc2 linux/amd64

### What did you do?

```golang
package main

type I = interface {
	I2
}

type I2 interface {
	I
}

func main() {
}
```

### What did you expect to see?

Compiler doesn't crash. An error message should be printed.

### What did you see instead?

Compiler crashes.

```
# command-line-arguments
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x9fec2c]

goroutine 1 [running]:
...
```

**Comment by mvdan** [comment]
Slightly smaller repro:

```
package p

type I = interface {
        I2
}

type I2 interface {
        I
}
```

If one removes the `=`, the compiler properly detects the recursive type and errors. It seems like it doesn't when a type alias is involved.

**Comment by griesemer** [comment]
Possibly related to #18640.

**Comment by go101** [comment]
Looks it was ever fixed Go 1.11.

**Comment by griesemer** [comment]
Hm, interesting. The previous CLs were known not to fix this completely (doing this correctly requires more changes in the compiler than we felt comfortable making during the various freezes); but there should not be a raw crash but a compiler-internal error with an error message.

**Comment by griesemer** [comment]
Filed reminder issue #31872 for fix of root cause.
