### ISSUE TITLE
cmd/compile: use strings.Builder

### ISSUE THREAD

**Issue by josharian** [golang/go#23828]
The main challenge here is ensuring everything still works when built with 1.4.

Probably build tag protected files, with something like

type buffer struct {
  bytes.Buffer
}

for pre-1.10 and

type buffer = strings.Builder

for 1.10+.

**Comment by mdempsky** [comment]
I've been thinking we should add a "cmd/internal/polyfill" (or however we want to spell the bikeshed) package that provides interfaces to sort.Slice, strings.Builder, and other recent stdlib additions that we want to use in the toolchain, while maintaining Go 1.4 compatibility.

**Comment by bradfitz** [comment]
@mdempsky, you could call the package just "util". *ducks*

**Comment by davecheney** [comment]
Why stop there? “common”, “shared”, or “base” are all perfectly cromulent package names.

**Comment by martisch** [comment]
cmd/internal/compat?

**Comment by pciet** [comment]
In cmd/compile/internal/gc there's these cases:

- fmt.Fprintln/fmt.Fprintf writing to a bytes.Buffer
- bytes.Buffer plugged into the output of exec.Command
- buf.WriteString()
- buf.WriteString(fmt.Sprintf())
- bufio.NewWriter(&a_bytes.Buffer)

I assume there might be cases of “str” + “str2” or fmt.Sprintf that may be more efficient as a strings.Builder.

https://github.com/golang/go/issues/18990 indicates there are no benchmarks for Builder. I see ```go tool compile -bench``` that would allow a comparison of compiler things in ns/op with these changes. Without a clear performance win I don't see a reason to do this.

**Comment by bradfitz** [comment]
In any case, the point behind my snark was to make sure that the package does NOT become a "util" package that itself depends on many things the caller of your package may not want.

It might be valid for the first few things, but it'll inevitably grow, and the util-ness bloat will sneak up on us.

It might be best to have N such packages under some "compat" or "future" directory.

**Comment by pciet** [comment]
cmd/internal/strbuf?

**Comment by mdempsky** [comment]
@bradfitz 

> In any case, the point behind my snark was to make sure that the package does NOT become a "util" package that itself depends on many things the caller of your package may not want.

I was imagining a package that's limited to just providing current standard library functionality, with backwards compatible implementations for bootstrapping under older Go releases. That is, for non-bootstrap builds, the packages don't do anything but pass through calls to the standard library.

It seems like you're suggesting that cmd shouldn't treat std as a single monolithic dependency, but instead should view each standard library package dependency individually. I understand why this is important within std, but it's not clear to me that it extends to cmd too.

**Comment by bradfitz** [comment]
> I understand why this is important within std, but it's not clear to me that it extends to cmd too.

I personally don't care too much. I'm mostly echoing the objections I've heard about "util" packages in the past.

Practically, it matters less here because this is an internal package and we can therefore audit the fixed number of users of the "util" package and verify they're not pulling in anything unnecessary via the util package they wouldn't depend on otherwise via other paths.

**Comment by dgryski** [comment]
At what point to we bite the bullet and say that you need something newer than 1.4 to build the latest Go release and add an extra step to bootstrapping from C?

**Comment by josharian** [comment]
> At what point to we bite the bullet

As late as humanly possible. Go 2, perhaps.

**Comment by pciet** [comment]
I can work on this.

I don’t like “util” packages but importing a few extra compatibility types isn’t going to be a big deal here, and we have to have a package since compile is split into horizontally dependent subpackages. I’d just add ```cmd/internal/compat``` and have a ```compat.StringBuffer```.

My previous comment is coming from ignorance, sorry about that. Obviously at least the linker is also required, and adjusting the bootstrap is outside the scope of this issue. I’ll assume other commands need the compatibility types too.

Again from ignorance, I’m not seeing package testing style benchmarking (with the stability feature) for the compiler. I was thinking I’ll write ```cmd/compile/bench_test.go``` that sets up by compiling the gc dependencies then benchmark loops on main() targeting package gc.

I only have an amd64/linux computer to benchmark on though, are there resources for trying things on other platforms? I’ll just email golang-dev asking for benchmarks with the change if not.

**Comment by josharian** [comment]
Compiler benchmarking:

https://godoc.org/golang.org/x/tools/cmd/compilebench

https://github.com/josharian/compilecmp

**Comment by josharian** [comment]
Oh, and I assume that the vast majority of compilation occurs on amd64, so I wouldn’t sweat that.

**Comment by pciet** [comment]
I’m not seeing a significant performance difference with compilebench+benchstat. I’ll try to modify the cases where a Reader or .Bytes() call is used next, so far I've only done the direct replacement cases.

**Comment by pciet** [comment]
Based on what I'm reading via Google Search I'll leave these small return concat cases alone:

```
// fmt.go
return "[]" + tmodeString(t.Elem(), mode, depth)

return t.Etype.String() + "-" + typefmt(t, flag, FErr, depth)

return "[" + strconv.FormatInt(t.NumElem(), 10) + "]" + tmodeString(t.Elem(), mode, depth)
```

**Comment by pciet** [comment]
time+alloc benchmarks: https://github.com/golang/go/issues/16897

**Comment by pciet** [comment]
I’ve submitted two patch sets that are both off what this change should be but I’ve shown that func tconv in cmd/compile/internal/gc/fmt.go is the only potentially worthwhile place to add in strings.Builder. I’m working on a fresh patch set now.

**Comment by pciet** [comment]
Here’s the time spent when ```compile``` (```devel +1b1c8b3 Feb 17```) is called on ```cmd/compile/internal/gc```:

<img width="1081" alt="screen shot 2018-03-01 at 11 02 45 am" src="https://user-images.githubusercontent.com/7949131/36859145-1b4d247e-1d43-11e8-9737-f509e6623f25.png">
<img width="1047" alt="screen shot 2018-03-01 at 11 03 12 am" src="https://user-images.githubusercontent.com/7949131/36859146-1b5ed7fa-1d43-11e8-9d9b-da74bf5f9e96.png">
<img width="282" alt="screen shot 2018-03-01 at 11 08 27 am" src="https://user-images.githubusercontent.com/7949131/36859147-1b6e3d58-1d43-11e8-9d69-2706f6b804e0.png">

The ```tconv``` things (```dumpobj1```) account for only 6.6% of the compile time in this case, but garbage collection (```runtime.gcDrain```) accounts for 18.7%. It’s possible that ```dumpobj``` recursive string concatenation generates a significant part of the garbage, so next I’ll try to show where garbage is left. ```gc.bottomUpVisitor.visitcode```, ```gc.compile```, and ```ssa.Compile``` are other places to look.

**Comment by bradfitz** [comment]
You want to look at memory (allocation) profiles, not CPU profiles, if your goal is to eliminate the creation of garbage. Reducing garbage reduces CPU.

**Comment by pciet** [comment]
@bradfitz for some reason the pprof heap profile doesn’t show any detail into gc.Main which is why I went to CPU, but I’ll keep trying.

**Comment by pciet** [comment]
With ```debug.SetGCPercent(-1)``` and ```runtime.MemProfileRate = 1``` compiling cmd/compile/internal/gc:

<img width="862" alt="screen shot 2018-03-01 at 3 40 45 pm" src="https://user-images.githubusercontent.com/7949131/36871265-573d5656-1d67-11e8-9427-ed89ccde1c63.png">

<img width="1026" alt="screen shot 2018-03-01 at 3 46 22 pm" src="https://user-images.githubusercontent.com/7949131/36871406-ccb9106e-1d67-11e8-8151-25687359fe78.png">

I'm not sure why the ```dumpobj``` string concats don't end up here.

**Comment by bradfitz** [comment]
I primarily look at `-alloc_space`. It's space that ultimately triggers collections.

**Comment by pciet** [comment]
Well I’m not convinced making small changes like replacing some bytes.Buffer use is worth it, for larger changes I think I’ll need a lot more time to understand the compiler and in-flight efforts, and I’m in the middle of some life changes.

I’m unable to work on this more for now.

**Comment by josharian** [comment]
Thanks for looking into it.
