### ISSUE TITLE
strconv: Unquote has custom for-loop-based `contains` implementation

### ISSUE THREAD

**Issue by dgryski** [golang/go#23821]
It should use one of the optimized assembly routines from `strings` (or I guess the runtime if you don't want to introduce a dependency on `strings` from `strconv`).

https://github.com/golang/go/blob/c10e61424f9c17c2972a438287ff9ac90d6b55a4/src/strconv/quote.go#L421

**Comment by josharian** [comment]
Probably depends on #19792
