### ISSUE TITLE
release: final Go 1.10 changes

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#23839]
This issue tracks the remaining CLs for the final Go 1.10 release.

- [x] [CL 93716](https://golang.org/cl/93716) : compiler fix for #23812 
- [x] [CL 94028](https://golang.org/cl/94028): compiler fix for #23812 on s390x
- [x] [CL 93836](https://golang.org/cl/93836): additions to compiler option whitelist
- [x] [CL 94018](https://golang.org/cl/94018): permit cgo_import_dynamic, because Solaris needs it
- [x] [CL 94158](https://golang.org/cl/94158): mention option whitelist in release notes
- [x] [CL 94159](https://golang.org/cl/94159): remove draft marker from release notes

As of this writing not all of these CLs are reviewed and committed.  Once that has happened, they need to be cherry picked to the 1.10 branch, and then we can make the release.

CC @andybons @bradfitz @randall77

**Comment by ianlancetaylor** [comment]
OK, we need someone to review https://golang.org/cl/94018, and another look at https://golang.org/cl/94158 would help.  Thanks.

**Comment by bradfitz** [comment]
Looking.

**Comment by ianlancetaylor** [comment]
The release is out.
