### ISSUE TITLE
access: Assignees and Editors

### ISSUE THREAD

**Issue by namusyaka** [golang/go#23840]
See https://golang.org/wiki/GithubAccess

----

I'm sorry, I should have asked you together at [the last issue](https://github.com/golang/go/issues/23770).
Since I often want to edit the issue on github, I apply for the following authority:

- https://github.com/orgs/golang/teams/go-assignees 
- https://github.com/orgs/golang/teams/go-approvers

Github username: namusyaka
Github email: namusyaka@gmail.com

Edited:

All my gardening issues: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Anamusyaka+
All my participating CLs: https://go-review.googlesource.com/q/namusyaka%2540gmail.com

**Comment by bradfitz** [comment]
Granted.

**Comment by namusyaka** [comment]
Thank you so much!
