### ISSUE TITLE
x/review/git-codereview: check for Signed-off-by lines before pushing to Gerrit

### ISSUE THREAD

**Issue by tklauser** [golang/go#23852]
Recently https://golang.org/cl/93935 was submitted where the commit message contained a Signed-off-by line (there are also a few cases of these lines in already submitted CLs). These SOB lines are not used by the Go project and https://golang.org/wiki/CommitMessage was thereupon updated by @bradfitz 

It would be nice if git-codereview would let the user know that these lines are unnecessary (with a link to the wiki page) or even refuse to push a CL containing such a line to Gerrit.

**Comment by bradfitz** [comment]
That would only help people using git-codereview. Now that we accept PRs, those lines will come in via GitHub anyway.

I don't think this is worth doing.

I think the right place to do this is in bots doing Gerrit reviews automatically, which is #18548

**Comment by tklauser** [comment]
#18548 is a lot nicer. Guess I didn't search hard enough for existing issues...
