### ISSUE TITLE
runtime: TestArenaCollision failing on Solaris

### ISSUE THREAD

**Issue by aclements** [golang/go#23862]
2b41554 broke Solaris. For example, https://build.golang.org/log/d32bb2fc9ace29dcdddd34f0df6361a4a2978fbb:

```
--- FAIL: TestArenaCollision (0.06s)
	malloc_test.go:175: === RUN   TestArenaCollision
		runtime: memory allocated by OS [0xfffffd7ff0000000, 0xfffffd7ff4000000) exceeds address space limit (0x1000000000000)
		fatal error: memory reservation exceeds address space limit
```

Apparently Solaris can allocate user address space in the upper portion of the amd64 virtual address space.

**Comment by ianlancetaylor** [comment]
There is a diagram of the Solaris memory map at http://www.oracle.com/technetwork/server-storage/solaris/solaris-memory-135224.html .  I haven't looked at this test, but Solaris will put the stack and shared objects above `0xFFFF8000 00000000`, and `mmap` can return address up there too.  Solaris doesn't get around the 48-bit limit, it just sign extends.

**Comment by aclements** [comment]
Thanks for the pointer; that's consistent with the builder failure. I'm already mapping enough metadata for 48 bit addresses because of arm64. I'll just have to close the hole either by masking off the sign extension or adding to rotate the hole around.
