### ISSUE TITLE
x/net/webdav: Doesn't interoperate with Windows 7 explorer

### ISSUE THREAD

**Issue by ncw** [golang/go#23871]
### What version of Go are you using (`go version`)?

`go version go1.9.2 linux/amd64` with the latest `golang.org/x/net/webdav`

### Does this issue reproduce with the latest release?

Yes.  

### What operating system and processor architecture are you using (`go env`)?

This is Windows 7 386 running on VirtualBox.

```
X:\go\src\github.com\ncw\rclone>go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Dev\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Dev
\AppData\Local\Temp\go-build996106411=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### What did you do?

Compiled [this program](https://gist.github.com/staaldraad/d835126cd46969330a8fdadba62b9b69) which is a very simple webdav server to serve a directory over webdav.

I ran this in a command window with `webdavd.exe -p 8081 -d c:\path\to\test\dir`

I then pointed windows explorer at it by putting in the url `\\localhost:8081\`.  Windows explorer sees all the directories but none of the files and an attempt to click on a directory gives a permissions error.

Source directory

![image](https://user-images.githubusercontent.com/536803/36313723-60a623ae-132a-11e8-998e-d7cb53da3cff.png)

Directory when viewed via the webdav server.  I expected to see all the files and the folders here.

![image](https://user-images.githubusercontent.com/536803/36313751-7e543ad0-132a-11e8-95e4-8462432b39f2.png)

And the error message you get when clicking on a directory

![image](https://user-images.githubusercontent.com/536803/36313767-984bd01a-132a-11e8-902b-55eaa659be55.png)

And here is the server running in the cmd window

![image](https://user-images.githubusercontent.com/536803/36313816-c6c34298-132a-11e8-8d94-8aa348b67a2b.png)

I originally discovered this while trying out `rclone serve webdav` which has exactly the same problem.

**Comment by alexbrainman** [comment]
Sorry I do not know much about webdav. But maybe @mattn can help you.

Alex

**Comment by mattn** [comment]
@ncw Sorry, I don't know the your way that refer location to the webdav.  (open \\localhost:8081\ on the Explorer)

The way I know is,

1. Open Explorer
2. Right-click on "This PC" (or "Computer" in Windows 7) and select "Add Network Location."
3. Click "Next" on the wizard
4. Select "Choose a custom network location" and click "Next."
5. Type in the address "http://localhost:8081/"

Then, you will see the Explorer opened the address.

![image](https://user-images.githubusercontent.com/10111/36340583-cb60c86c-1423-11e8-985e-cfbe51abdaaf.png)

**Comment by ncw** [comment]
@mattn - I can confirm that adding the WebDAV share the way you suggested works perfectly.

Sorry for inflicting my Windows incompetence on you all!

Thanks for your help.

I'm going to close this now.
