### ISSUE TITLE
Different results when using float64 constant vs float64(int) cast

### ISSUE THREAD

**Issue by klokare** [golang/go#23876]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.4 darwin/amd64

### Does this issue reproduce with the latest release?
yes. I can replicated this on play.golang.org

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
https://play.golang.org/p/o3I21mRFPt2

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Printf("CASE A: %0.20f\n", (1.0 + (4.0 * (1.0/7.0))/2.0) / 2.0)
	fmt.Printf("CASE B: %0.20f\n", (1.0 + (float64(4) * (1.0/7.0))/2.0) / 2.0)
	
	x := 4.0
	y := float64(4)
	fmt.Printf("CASE C: %0.20f\n", (1.0 + (x * (1.0/7.0))/2.0) / 2.0)
	fmt.Printf("CASE D: %0.20f\n", (1.0 + (y * (1.0/7.0))/2.0) / 2.0)
}
```
```text
CASE A: 0.64285714285714290472
CASE B: 0.64285714285714279370
CASE C: 0.64285714285714279370
CASE D: 0.64285714285714279370
```
### What did you expect to see?
All cases should be equal

### What did you see instead?
Case A is different. When using 4.0 vs float64(4) directly, I get different results (Case A vs Case B). If I assign the values to variables then I get the same result (Case C and D are the same result as Case B). There appears to be some optimisation that is affecting the 4.0 constant.

**Comment by cznic** [comment]
> There appears to be some optimisation that is affecting the 4.0 constant.

[Precision](https://golang.org/ref/spec#Constants), not optimisation is the culprit:

> Represent floating-point constants, including the parts of a complex constant, with a mantissa of at least 256 bits and a signed binary exponent of at least 16 bits.

**Comment by klokare** [comment]
After some good discussions on Slack (thanks everyone), this may be the correct albeit unexpected (to me and to a casual reader of the code): https://www.ardanlabs.com/blog/2014/04/introduction-to-numeric-constants-in-go.html

> Constants Are Mathematically Exact
> Regardless of the implementation, constants are always considered to be mathematically exact. This is something that makes constants in Go unique. This is not the case in other languages like C and C++.
> 

@cznic, you are correct in that its precision but the issues is deeper than just the typical issues of floating point precision. it's related, it seems, to "[in] your issue *all* the computations are done at the "ideal constant" level with effectively unlimited precision, and then afterwards converted down to a float64" (credit Damian G. with that phrasing). 

I'm left wondering about all the times I got this wrong. A typical use case for me would be using float64 constants in variable declarations à la:

```go
x := Foo {
    Mean: (x0 + x1 + x3 + x4) / 4.0,
}
```

From my new understanding, that is not the same as 
```go
cnt := float64(4)
x := Foo {
    Mean: (x0 + x1 + x3 + x4) / cnt,
}
```

**Comment by dgryski** [comment]
In this case, there are no other calculations to be done with the ideal `4` before it's needed as a `float64` for the division, so it ends up being the same.

**Comment by klokare** [comment]
yeah, it was a bad example case as, in this case, the answers are the same. But introducing more complex math, like the original post, shows how that *assumptions* in that last example break down. Just one more thing to keep in mind. Your explanation about the "ideal `4`" helps with dispelling the incorrect assumptions. Thanks.

**Comment by bradfitz** [comment]
Sounds like there's nothing to do here. Closing.
