### ISSUE TITLE
cmd/go: build does not allow for assembly output to be displayed on cached builds

### ISSUE THREAD

**Issue by dlsniper** [golang/go#23877]
### What version of Go are you using (`go version`)?
go version go1.10 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 / amd64

### What did you do?
Ran `  go build -gcflags -S file.go ` twice on a file that did not changed.

### What did you expect to see?
The assembly output should be displayed twice.

### What did you see instead?
First time this works, second time this doesn't because of the caching. I understand why this happens but I don't particularly like the effect it has or the workaround, especially since on Windows it's still not trivial to run the workaround as is on other operating systems.

The workaround is: ` GODEBUG=gocacheverify=1 go build -gcflags -S file.go `.

My apologies for finding this so late.

**Comment by bradfitz** [comment]
Yeah, we can probably disable caching for all such debug/printing flags. Want to make a list of them all?

**Comment by dlsniper** [comment]
I'm not sure if disabling the cache for the build or caching the output is the correct way to go forward.

I'll collect these in the issue and ping after it's done (should be this weeked).

**Comment by bradfitz** [comment]
Considering how rarely these are used, and how they're only used for development, disabling the build cache seems simplest and safest.

**Comment by dominikh** [comment]
> Considering how rarely these are used, and how they're only used for debugging or developing the Go compilers themselves

Neither of these statements are true. People use `-S` and `-m` for performance analysis of their own code.

**Comment by bradfitz** [comment]
I mean they're only used for
a) debugging
b) developing the Go compilers themselves
sure, we can add
c) performance analysis of your own code

My point remains: they're rarely used.

We can afford to give up the caching here.

**Comment by ALTree** [comment]
The workaround is using `go tool compile -S`, that will always print the asm. It's also 2 characters shorter, so you save time : )

**Comment by FiloSottile** [comment]
@gopherbot please open a backport tracking issue, as this is a 1.10 regression,

**Comment by rsc** [comment]
No flag whitelist needed. This is a variant of #22587. https://golang.org/cl/77110 should have fixed this but somehow did not. 

/cc @bcmills want to take a look?

**Comment by bcmills** [comment]
I'll look into it when I get a chance. Is this possibly a difference of `stderr` vs. `stdout`?

**Comment by ianlancetaylor** [comment]
In my testing the `-S` output is repeated as expected when building a non-main package.  It is not repeated when building a main package if the executable already exists.

@dlsniper Were you building a main package?
