### ISSUE TITLE
doc: go Path wiki link in https://golang.org/doc/code.html is blank

### ISSUE THREAD

**Issue by btalpers** [golang/go#23872]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
none

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
none

### What did you do?
Visited https://golang.org/doc/code.html, and clicked any of the locations that redirect to https://github.com/golang/go/wiki/SettingGOPATH , which asks me to Create a new page for `SettingGOPATH`

If possible, provide a recipe for reproducing the error.
See above

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
An actual documentation page.

### What did you see instead?
<img width="1041" alt="screen shot 2018-02-16 at 11 25 38 am" src="https://user-images.githubusercontent.com/11773535/36320534-276841da-130c-11e8-86c1-0826e897b50b.png">

**Comment by ALTree** [comment]
The wiki page was moved by someone... again:

https://github.com/golang/go/wiki/_compare/412b80a03b2d159207fd26027a34898be232876b...11b810add36f043f3985cf42600ef4cdcef79d74

**Comment by ALTree** [comment]
I've reverted the change. The link now works as before.

**Comment by btalpers** [comment]
Awesome!

**Comment by bradfitz** [comment]
I've emailed the renamer and asked them to stop.
