### ISSUE TITLE
constexpr() or custom preprocessor for go build

### ISSUE THREAD

**Issue by gitsomecrabs** [golang/go#23880]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes, because not part of the language or toolchain

### What operating system and processor architecture are you using (`go env`)?
OSX,Windows,LInux

### What did you do?
Had to hack the "go generate" command to preprocess source code, does not run automatically
as part of go build, must run explicity and separately, which is bad.  

Hack preprocessor has to edit original source code, also very bad.  Not like constexpr( ) which is compile time execution of C functions but leaves the source code untouched!

**Comment by bradfitz** [comment]
Sorry, but we're not adding code that runs automatically as part of building (that was a part of the design of "go generate"). And we're not modifying the language (e.g. constexpr) at this time.
