### ISSUE TITLE
cmd/cgo: please provide a way to set errno from a callback

### ISSUE THREAD

**Issue by jech** [golang/go#23890]
I'm interfacing with a C library that expects callbacks to return -1 with `errno` set upon error.  As far as I can tell, the only way to set errno in a go function is to call back into C:

```C
void
set_errno(int e)
{
    errno = e;
}
```

```Go
//export callback
func callback(...)  C.int {
    ...
    C.set_errno(C.int(syscall.EAGAIN))
    return -1
    ...
}
```

This is in contrast with retrieving `errno` in Go using multiple return values, which I find elegant and Go-like.  Please provide a similarly tasteful way to return from Go to C while setting `errno`.

**Comment by ianlancetaylor** [comment]
This is doable in principle--we could apply special handling to an //extern function that returns two values where the second one has type `int`, but it would be so rarely used that I don't think it's worth the additional complexity.

**Comment by craig65535** [comment]
I think go also needs the ability to set errno when calling into certain functions like `getgrent` and `getpwent`. These functions return NULL and set errno on error, but they may also return NULL and *not* set errno on success (when all the entries have been returned). So, users must explicitly set errno to 0 before calling these functions.

From the macOS man page for `getpwent`:
> RETURN VALUES
>      The functions getpwent(), getpwnam(), getpwuid(), and getpwuuid() return a
     valid pointer to a passwd structure on success or NULL if the entry is not
     found or if an error occurs.  If an error does occur, errno will be set.
     Note that programs must explicitly set errno to zero before calling any of
     these functions if they need to distinguish between a non-existent entry
     and an error.

It seems the only way to do this is to write a C function to set errno.

**Comment by ianlancetaylor** [comment]
As I said earlier, this case is so rarely used that I don't think it's worth the extra complexity in cgo.

For people who need this I recommend writing, in the cgo comment.

```Go
/*
#include <errno.h>
#include <sys/types.h>
#include <pwd.h>

static struct passwd *goGetpwent() {
    errno = 0;
    return getpwent();
}
*/
import "C"
```

Then change your code to call `goGetpwent` rather than `getpwent`.

**Comment by jech** [comment]
>  this case is so rarely used that I don't think it's worth the extra complexity in cgo.

I'm the original reporter, and with four years more experience, I fully agree with Ian.  Sorry for the noise.
