### ISSUE TITLE
x/perf/benchstat: support piping results to benchstat

### ISSUE THREAD

**Issue by kevinburke** [golang/go#23896]
I just want human-readable output for the number of allocations and the time taken. Currently I write this in a Makefile:

```
BENCHSTAT := $(GOPATH)/bin/benchstat

$(BENCHSTAT):
	go get -u golang.org/x/perf/cmd/benchstat

bench: $(BENCHSTAT)
	tmp=$$(mktemp); go list ./... | grep -v vendor | xargs go test -benchtime=2s -bench=. -run='^$$' > "$$tmp" 2>&1 && $(BENCHSTAT) "$$tmp"
```

It would be simpler if you could pipe the results of `go test -bench=.` directly to benchstat, instead of having to send it to a file first.

**Comment by davecheney** [comment]
Benchstat takes two files, how are you going to pipe the before and after output to it simultaneously?

**Comment by kevinburke** [comment]
If you run benchstat with a single file input, it prints the outputs in human readable format. Example go test -bench output:

```
BenchmarkUDist-4       	    1000	   1410040 ns/op
BenchmarkUDistTies-4   	     300	   4361164 ns/op
```

And the same file output run through benchstat:

```
$ benchstat benchstat.out
name         time/op
UDist-4      1.40ms ± 0%
UDistTies-4  4.34ms ± 0%
```

Perhaps a better solution would be add a human-readable flag to `go test -bench` but that seems like a more involved process.

**Comment by kevinburke** [comment]
We could also add a second command, `humanbench` or something, that translates Go bench output into human readable format, either from a file or from stdin.

**Comment by davecheney** [comment]
Wow, TIL, thanks

**Comment by rsc** [comment]
Replied on the CL; please use benchstat /dev/stdin for now. I don't think this is commonly needed enough to confuse people who just type 'benchstat'.

**Comment by kevinburke** [comment]
ah, neat, I didn't know about the /dev/stdin trick!

**Comment by kevinburke** [comment]
Alright, closing, fwiw I made github.com/kevinburke/humanbench to translate the benchmark results on the fly.
