### ISSUE TITLE
cmd/cgo: -Wl , -rpath in LDFLAGS throws invalid flag in #cgo LDFLAGS: -Wl,-rpath=$ORIGIN/lib

### ISSUE THREAD

**Issue by datNurd** [golang/go#23904]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 windows/386

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10, 64 bit

### What did you do?
`#cgo CFLAGS: -I${SRCDIR}/lib`
`#cgo LDFLAGS: -L${SRCDIR}/lib -Wl,-rpath=\$ORIGIN/lib -ltest`
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Compiled go program.

### What did you see instead?
go build command-line-arguments: invalid flag in #cgo LDFLAGS: -Wl,-rpath=$ORIGIN/lib

**Comment by hirochachacha** [comment]
use ',' instead of '='.
```
#cgo LDFLAGS: -L${SRCDIR}/lib -Wl,-rpath,$ORIGIN/lib -ltest
```

**Comment by ianlancetaylor** [comment]
Consolidating into #23937.
