### ISSUE TITLE
go/build: using #cgo CFLAGS: -I"C:/Program Files (x86)/somelib/include" throws malformed cgo

### ISSUE THREAD

**Issue by datNurd** [golang/go#23911]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 windows/386

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 64bit

### What did you do?
`#cgo CFLAGS: -I"C:/Program Files (x86)/somelib/include"`
`#cgo LDFLAGS: -L"C:/Program Files (x86)/somelib/lib" -lsomelib`

Loading headers and library files from 'Program Files (x86)' throws malformed cgo

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
A built program

### What did you see instead?
malformed #cgo argument: -IC:/Program Files (x86)/somelib/include

Loading headers and library from a library installed in Program Files (x86) throws an error. I've tried enclosing the path in quotes ("") but did not work

**Comment by ianlancetaylor** [comment]
We currently restrict the strings used in `#cgo CFLAGS` lines to a set of known safe characters.  Parentheses are not in that set.  See https://golang.org/src/go/build/build.go?#L1367.

**Comment by matiasinsaurralde** [comment]
I'm currently working on a cross platform CGO app and this will be really useful for my builds!

**Comment by ianlancetaylor** [comment]
I can't convince myself that parentheses are safe in general.  I'm going to close this.  Sorry.
