### ISSUE TITLE
x/talks: still using old version of present at talks.golang.org 

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#23926]
In https://github.com/golang/tools/commit/e00c182679a043c63cd52172ee2d9d3d8ad22e26 I fixed an issue with the CSS of present not scaling down on smaller displays. I assumed talks.golang.org would be updated along with 1.10, but when I look at https://talks.golang.org/2017/state-of-go-may.slide#1, it appears to be using the same old and busted CSS. What is the release cycle like for talks.golang.org?

**Comment by andybons** [comment]
Fixed in https://github.com/golang/tools/commit/5e776fee60db37e560cee3fb46db699d2f095386 and deployed.
