### ISSUE TITLE
CGO: invalid flag in #cgo CFLAGS: -w

### ISSUE THREAD

**Issue by Aukstkalnis** [golang/go#23938]
#### What did you do?
I tried to build simple gui app using sciter: https://github.com/sciter-sdk/go-sciter

#### What did you expect to see?
Successful build.

#### What did you see instead?
cgo error:
github.com/sciter-sdk/go-sciter: invalid flag in #cgo CFLAGS: -w
The terminal process terminated with exit code: 1

With 1.9.4 version there was no such error. I tried using CGO_CFLAGS_ALLOW = 1, but that didn't worked for me.

#### System details

```
go version go1.10 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="%USER%\AppData\Local\go-build"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="D:\Projects\Go_Projects"
GORACE=""
GOROOT="C:\go"
GOTMPDIR=""
GOTOOLDIR="C:\go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=D:\Temp\go-build589517054=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.10 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.10
lldb --version: lldb version 5.0.0
gdb --version: GNU gdb (GDB) 8.0
```

**Comment by AlexRouSg** [comment]
https://github.com/golang/go/wiki/InvalidFlag

> Set the environment variable CGO_CFLAGS_ALLOW (or CGO_LDFLAGS_ALLOW, CGO_CXXFLAGS_ALLOW, and so forth) to a regexp that matches the option.

`CGO_CFLAGS_ALLOW` Is not a boolean, it is a string regexp.

**Comment by ianlancetaylor** [comment]
Consolidating into #23937.
