### ISSUE TITLE
x/build: add instructions for when a new repo is added

### ISSUE THREAD

**Issue by andybons** [golang/go#23949]
When a new repository is added to go.googlesource.com, it need to be created in GitHub and whitelisted in gitmirror, gerritbot, and maintnerd. Document this somewhere.

/cc @bradfitz

**Comment by dmitshur** [comment]
I took notes while resolving #26949, which is going to come in handy now. Going to clean them up and add to a wiki page.

**Comment by dmitshur** [comment]
I've created a [CreatingSubRepository wiki page](https://golang.org/wiki/CreatingSubRepository) and documented the process there.
