### ISSUE TITLE
x/vgo: GitHub mirror missing, leading to 404s

### ISSUE THREAD

**Issue by mvdan** [golang/go#23945]
The source is available at https://go.googlesource.com/vgo, but not at https://github.com/golang/vgo. This leads to some links, such as godoc's, to be 404s.

For example, click on "main.go" in https://godoc.org/golang.org/x/vgo.

**Comment by bradfitz** [comment]
/cc @andybons 

Guess we'll need to add this to gitmirror.

**Comment by andybons** [comment]
Yep. On it.

**Comment by rsc** [comment]
Thanks very much. I was going to push an initial repo by hand but I forgot.

**Comment by andybons** [comment]
This is now live.
