### ISSUE TITLE
x/vgo: access to details of packages etc

### ISSUE THREAD

**Issue by dave** [golang/go#23951]
It would be great to have API access to some of the internals of the new `vgo` tool. 

I recently spent a good deal of time forking `go get` and replacing the calls to `git` with the `go-git` library, so I could get a package and dependencies to memory rather than the filesystem (see [here](https://github.com/dave/jsgo/tree/09cb2a95dc153635ee1c160f584dd745ed3f9f34/getter)). It was neither fun nor pretty.

The new architecture of removing the external tools and transferring zip files around over HTTP lends itself rather well to this... I'd love to be able to stream a module zip file to a io.Reader without having to fork internal packages.

**Comment by rsc** [comment]
Please don't fork internal packages. We're going to build out a good API for getting this stuff out of the go command directly. It's only day 1. :-)

**Comment by dave** [comment]
Wait - not sure you understand my request... I'd like to trigger the go commands from code, not a command line tool... 

e.g. 

```go
zipbuf := &bytes.Buffer{}
gotool.GetModule(zipbuf, "github.com/foo/bar")
// downloads module zip and writes to zipbuf
```

**Comment by dave** [comment]
> It's only day 1.

Totally understand it's just a prototype!

**Comment by rsc** [comment]
>  I'd like to trigger the go commands from code, not a command line tool...

Sorry, but I'm not willing to support Go API access, because then if you have a stale tool then your tool will do old things. In contrast if your tool runs the go command-line to find out what it needs, then it will not need to be updated after and stay in sync with each Go release.

We're going to work on command-line API, as I said.

**Comment by dave** [comment]
I understand. It's a whole different level of effort maintaining a backwards compatible API than a command line tool. Thanks for looking into this.
