### ISSUE TITLE
x/vgo: vgo objabi: cannot find GOMIPS

### ISSUE THREAD

**Issue by lrewega** [golang/go#23953]
### What version of Go are you using (`go version`)?

go version go1.9.1 darwin/amd64

### Does this issue reproduce with the latest release?

Nope, looks like it works with go1.10 ¯\\\_(ツ)\_/¯

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lrewega/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yl/x9t8hwnx75x8z9zhbywrq6cr0000gn/T/go-build923822116=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
```
$ go get golang.org/x/vgo
$ which vgo
/Users/lrewega/go/bin/vgo
$ vgo
vgo objabi: cannot find GOMIPS
$ echo $?
2
```

### What did you expect to see?

I expected `vgo` to print usage information.

### What did you see instead?

```
$ vgo
vgo objabi: cannot find GOMIPS
$ echo $?
2
```

**Comment by davecheney** [comment]
Why not upgrade to go 1.10. It was released last week.

**Comment by rsc** [comment]
Sorry, there's no plan to support Go 1.9 or earlier. This is a fork of the Go 1.10 cmd/go.

**Comment by lrewega** [comment]
I figured as much, but I didn't see that referenced in the documentation, and thought the error was surprising.

**Comment by lrewega** [comment]
Related to #23957
