### ISSUE TITLE
x/vgo: windows: cannot determine module path due to \r\n

### ISSUE THREAD

**Issue by tobiaskohlbau** [golang/go#23952]
### What version of Go are you using (`go version`)?
`go version go1.10 windows/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\tobias\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\tobia\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\tobias\AppData\Local\Temp\go-build013816286=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?
I've run vgo as suggested within the vgo-tour. It does not work as windows uses `\r\n` as file endings. I've located the cause which is a missing `\r?` within a regular expression [here]( https://github.com/golang/vgo/blob/b6ca6ae975e2b066c002388a896833851a9e54a9/vendor/cmd/go/internal/vgo/init.go#L296). I did a quick test of adding the missing peace to local copy. After adding `\r?` it just works fine.
If non empty module file exists vgo works as intended.

### What did you expect to see?
```
vgo: resolving import "rsc.io/quote"
vgo: finding rsc.io/quote (latest)
vgo: adding rsc.io/quote v1.5.2
```

### What did you see instead?
`vgo: cannot determine module path for legacy source directory C:\Users\tobias\hello (outside GOROOT, no import comments)`

**Comment by rsc** [comment]
I'm so sorry about this. Will fix.

**Comment by jasontconnell** [comment]
I got around it in the meantime by modifying the vgo src directly

golang.org\x\vgo\vendor\cmd\go\internal\vgo\init.go  line 297

**Comment by hypwxm** [comment]
in my mac, the same happend
