### ISSUE TITLE
x/vgo: package download process is stuck in an infinite loop when trying to go-get an appengine url

### ISSUE THREAD

**Issue by jaloren** [golang/go#23967]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Volumes/Repositories/go/bin"
GOCACHE="/Users/jlorenzini/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jlorenzini/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/7ndx_j6s36x9hm9dns67j21s3hynqn/T/go-build282875283=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

1. created an empty go.mod file.
2. ran vgo build.

### What did you expect to see?

vgo download all the package dependencies and then compile the binary.

### What did you see instead?

vgo build command never completes. It seems effectively stuck in an infinite loop. It looks like tries to import all the packages required by my module, then it prints this.

```
FindRepo: Get https://appengine?go-get=1: dial tcp: lookup appengine: no such host
FindRepo: Get https://appengine/cloudsql?go-get=1: dial tcp: lookup appengine: no such host
FindRepo: Get https://appengine_internal?go-get=1: dial tcp: lookup appengine_internal: no such host
FindRepo: Get https://appengine_internal/base?go-get=1: dial tcp: lookup appengine_internal: no such host
```

And then starts the importing process all over again.

**Comment by rsc** [comment]
Certainly the loop should be stopped.
