### ISSUE TITLE
cmd/go: no go test -h documentation for test caching 1.10

### ISSUE THREAD

**Issue by jadekler** [golang/go#23971]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.10 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

osx

### What did you do?

`go test -h`

### What did you expect to see?

Documentation for disabling test cachine.

### What did you see instead?

Nothing about test caching.

**Comment by jadekler** [comment]
Submitted a CL for this: https://go-review.googlesource.com/c/go/+/95582

My first one, sorry if I messed up!

**Comment by ianlancetaylor** [comment]
Test caching is documented in the `go help test` output.  I can't how important it is to also documented it in the `go test -h` output.

**Comment by jadekler** [comment]
I think it's a QOL thing. I reach for -h when I'm looking for a flag I need to pass; adding a brief ctrl+f-able note about caching and `-count=1` at the first place to look for flags seems like an easy win for developers.

That said, I'm not at all learned about the intention of the various forms of docs, so I defer to y'alls experience.
