### ISSUE TITLE
x/vgo: print auto-guessed module setting during go.mod init

### ISSUE THREAD

**Issue by davecheney** [golang/go#23978]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go 1.10

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

I'm trying vgo on heptio/contour, a moderate project which depends on the kubernetes client-go library.  My $GOPATH is set to $HOME
```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % echo > go.mod
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % vgo build
vgo: import "github.com/davecheney/contour" [/Users/dfc/src/github.com/heptio/contour]: no Go source files
```

### What did you expect to see?
```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % cat go.mod 
module "github.com/heptio/contour"
```

### What did you see instead?

```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % cat go.mod 
module "github.com/davecheney/contour"
```
This may be because I have renamed my origin branch to be my fork of contour
```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % git remote  -v
origin  git@github.com:davecheney/contour.git (fetch)
origin  git@github.com:davecheney/contour.git (push)
upstream        git@github.com:heptio/contour.git (fetch)
upstream        git@github.com:heptio/contour.git (push)
```

**Comment by rsc** [comment]
The auto-detection is not perfect. Probably it should print what it chose, so that if it's wrong maybe you avoid a debugging session. You can always write the module line yourself.
