### ISSUE TITLE
x/vgo: cannot require k8s.io/client-go v6.0.0

### ISSUE THREAD

**Issue by davecheney** [golang/go#23980]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go 1.10

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?
```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % cat go.mod
module "github.com/heptio/contour"

require (
        "k8s.io/client-go" v6.0.0
)

```

### What did you expect to see?

Build success (or at least fetching of the v6.0.0 tag) then probably blowing up with something else

### What did you see instead?
```
Daves-MacBook-Pro(~/src/github.com/heptio/contour) % vgo build ./cmd/contour
vgo: errors parsing go.mod:
/Users/dfc/src/github.com/heptio/contour/go.mod:4: invalid module: k8s.io/client-go should be v1, not v6 (v6.0.0)
```

**Comment by mvdan** [comment]
Possibly the same as https://github.com/golang/go/issues/23977? If that bug is correct, only v1 and v2 should currently work.

**Comment by mikkeloscar** [comment]
For anyone interested. A quick workaround is to use the commit:

```
require (
        "k8s.io/client-go" v0.0.0-20171206195300-78700dec6369ba22221b72770783300f143df150
)
```

**Comment by davecheney** [comment]
Duplicate of #23977 

There are many discussions on the inclusion of the /v_N_ component in the import path. There doesn't need to be another issue for the discussion to leak onto.
