### ISSUE TITLE
x/tools: fix dep install for x/tools?

### ISSUE THREAD

**Issue by mcandre** [golang/go#23981]
dep is currently unable to resolve Go's x/tools due to an issue with directories that lack Go source files. Could we add a `version.go` or similar nonce file at the top of golang.org/x/tools, as a workaround?

**Comment by bradfitz** [comment]
Is there an open dep bug about this?

**Comment by dominikh** [comment]
Sounds like https://github.com/golang/dep/issues/1272

**Comment by mcandre** [comment]
@gopherbot

Lol this is still an issue. just because I didn't respond to a not-question doesn't mean that this issue is magically resolved.

So dep appears to be a nascent state, unable to install even basic Go utliities, due to dep's requirement that all repositories feature Go code at the top directory level. I am proposing a workaround: Declare the utility version in a top level `version.go` file, or put some other kind of nonce there, so that dep can install these x/... components.

**Comment by ianlancetaylor** [comment]
I think we are waiting to see whether dep is going to fix the problem.  If dep makes a definitive decision that they will not support this kind of repo--which seems like an odd choice to me--then we can consider changing the repo here.

**Comment by rsc** [comment]
Top-level directories that don't have Go code in them are completely fine. We should not turn inadequacies in tools into changes forced into every repo in existence. Even tools we own like Dep.
