### ISSUE TITLE
x/vgo: vgo build fails on successive builds

### ISSUE THREAD

**Issue by adal-io** [golang/go#23984]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.10 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

darwin/amd64

### What did you do?

First `vgo build` command will build project properly. Successive `vgo build` commands will fail with a 404 error on certain packages.

### What did you expect to see?

Successful build.

### What did you see instead?

````
vgo: finding github.com/rs/cors v1.2.0
vgo: github.com/rs/cors v1.2.0: unexpected status (https://api.github.com/repos/rs/cors/git/refs/tags/v1.2.0): 404 Not Found
vgo: finding github.com/google/uuid v0.1.0
vgo: github.com/google/uuid v0.1.0: unexpected status (https://api.github.com/repos/google/uuid/git/refs/tags/v0.1.0): 404 Not Found
vgo: finding github.com/google/uuid v0.1.0
vgo: github.com/google/uuid v0.1.0: unexpected status (https://api.github.com/repos/google/uuid/git/refs/tags/v0.1.0): 404 Not Found
vgo: unexpected status (https://api.github.com/repos/google/uuid/git/refs/tags/v0.1.0): 404 Not Found
````

**Comment by flibustenet** [comment]
I believe it's the same issue #23954 when the tagged version is not three numbers

**Comment by adal-io** [comment]
After some further testing - if a package has no tags, it will pull from the HEAD and use the pseudo-version is used as defined in [vgo-intro - Defining Go Modules](https://research.swtch.com/vgo-intro). However if the package is tagged - but not with 3 numbers - it causes the 404 error when running `vgo build` or `vgo run`.

To remedy this, one can manually set the package's pseudo-version in the `go.mod` file using the commit hash:

````
require (
        "github.com/google/uuid" v0.0.0-20171129175443-dec09d7
	"github.com/rs/cors" v0.0.0-20180122175443-feef513
)
````
