### ISSUE TITLE
Gofmt can't format the structure if has comments between attributes

### ISSUE THREAD

**Issue by denismakogon** [golang/go#23999]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.10 darwin/amd64
```
### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/denismakogon/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=---filtered----
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lh/wxmjgcb14s37p3kq71l4bfrh0000gn/T/go-build627174261=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

Iinter (https://github.com/alecthomas/gometalinter) was complaining about one of the struct definitions formattings is totally messed up. Here's the struct definition:
```go
type API struct {
	ID           string `json:"id,omitempty"`
	Name         string `json:"name"`
	CreatedAt    int64  `json:"-"`
	UpstreamURL  string `json:"upstream_url,omitempty"`
	PreserveHost bool   `json:"preserve_host"`
	// kong 0.9.x and earlier
	RequestPath      string `json:"request_path,omitempty"`
	RequestHost      string `json:"request_host,omitempty"`
	StripRequestPath bool   `json:"strip_request_path,omitempty"`
	// kong 0.10.x and later
	Hosts    []string `json:"hosts,omitempty"`
	URIs     []string `json:"uris,omitempty"`
	StripURI bool     `json:"strip_uri,omitempty"`
}
```

So, i tried to do the following:
```sh
go fmt ./...
````

### What did you expect to see?
Here's what i was expecting to get?

```go
type API struct {
	ID               string   `json:"id,omitempty"`
	Name             string   `json:"name"`
	CreatedAt        int64    `json:"-"`
	UpstreamURL      string   `json:"upstream_url,omitempty"`
	PreserveHost     bool     `json:"preserve_host"`
	// kong 0.9.x and earlier
        RequestPath      string   `json:"request_path,omitempty"`
	RequestHost      string   `json:"request_host,omitempty"`
	StripRequestPath bool     `json:"strip_request_path,omitempty"`
	// kong 0.10.x and later
        Hosts            []string `json:"hosts,omitempty"`
	URIs             []string `json:"uris,omitempty"`
	StripURI         bool     `json:"strip_uri,omitempty"`
}
```

### What did you see instead?

After running `go fmt ./...` no changes were applied to the given struct. I assume that comments make fmt faulty somehow.

**Comment by ericmdantas** [comment]
The problem doesn't happen exclusively to comments. If you simply remove the comments and leave the spacing there, the properties won't be formatted either. Like this:

```go
type API struct {
	ID           string `json:"id,omitempty"`
	Name         string `json:"name"`
	CreatedAt    int64  `json:"-"`
	UpstreamURL  string `json:"upstream_url,omitempty"`
	PreserveHost bool   `json:"preserve_host"`

	RequestPath      string `json:"request_path,omitempty"`
	RequestHost      string `json:"request_host,omitempty"`
	StripRequestPath bool   `json:"strip_request_path,omitempty"`

	Hosts    []string `json:"hosts,omitempty"`
	URIs     []string `json:"uris,omitempty"`
	StripURI bool     `json:"strip_uri,omitempty"`
}
```


[Go playground](https://play.golang.org/p/__UQbzGPiJT).

**Comment by dominikh** [comment]
This is all working as expected. Fields are aligned per group. Comments, newlines or significantly different length identifiers all introduce new groups.

**Comment by denismakogon** [comment]
@dominikh excuse, but how is that expected? Is it documented? As far as i know, it is not documented or expected. No matter what you put inside the struct (no matter would that be comments, newlines, etc.), it should be formatted.

**Comment by dominikh** [comment]
It is formatted. You will notice that there are 3 distinct groups of fields. In each group, all fields are aligned. This has been covered before in https://github.com/golang/go/issues/5277 and https://github.com/golang/go/issues/10392

The style of gofmt is not documented explicitly; the implementation of gofmt defines the style. Sans bugs, what gofmt produces is the expected formatting, and this particular case isn't a bug.
