### ISSUE TITLE
Flutter but with Golang instead of Dart

### ISSUE THREAD

**Issue by kokizzu** [golang/go#24029]
It would be really nice if there is [Flutter](http://flutter.io) but with Go programming language, since Golang is somewhat simpler language in my opinion.

**Comment by AlexRouSg** [comment]
Why not just ask Flutter to support Go? 

The issue tracker is only used for bugs or proposals, since this is not a bug, is this a proposal or a general question/statement? For non bugs/proposal purposes please see https://github.com/golang/go/wiki/Questions

**Comment by andybons** [comment]
Closing as this was filed against the Flutter repo (https://github.com/flutter/flutter/issues/14816) which is a better place for it.
