### ISSUE TITLE
wiki: transfer label descriptions from wiki to labels themselves

### ISSUE THREAD

**Issue by dmitshur** [golang/go#24023]
Now that GitHub has [added descriptions to labels](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more), it would probably be helpful to transfer the label descriptions from https://github.com/golang/go/wiki/IssueLabels to the labels themselves.

I think it would make it easier for more people to discover what the labels mean.

If we do this, I think the wiki page should be removed (maybe not right away, and also having made a backup), to avoid having to maintain same information in two places.

This issue is to consider/discuss this opportunity.

**Comment by shurcooL** [comment]
An alternative to consider is to keep https://github.com/golang/go/wiki/IssueLabels as the source of truth, because it's easier to see who edited it and it has edit history. Then the label descriptions can be copied over from the wiki page to the labels.

**Comment by dgryski** [comment]
Can we label edits be detected somehow? Or maybe involve Gopherbot?

**Comment by bradfitz** [comment]
I'm not sure this changes enough to be worth automating. I think enough people have wiki + github edit access that we can just manually keep things in sync. Or we can change the wiki page to just link to https://github.com/golang/go/labels

I added one description at https://github.com/golang/go/labels to test how it renders. Seems fine to just move everything there. The one downside is there are length limitations, but maybe that's a feature.

**Comment by agnivade** [comment]
@bradfitz made the change couple of days ago.
