### ISSUE TITLE
website: deprecation comment examples link in go doc blog post is incorrect

### ISSUE THREAD

**Issue by nhooyr** [golang/go#24021]
https://blog.golang.org/godoc-documenting-go-code

> Sometimes a struct field, function, type, or even a whole package becomes redundant or unnecessary, but must be kept for compatibility with existing programs. To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation. There are a such few examples in [the standard library](https://golang.org/search?q=deprecated).

The link to the examples is https://golang.org/search?q=deprecated but it should be [https://golang.org/search?q=Deprecated:](https://golang.org/search?q=Deprecated:)

**Comment by andybons** [comment]
Fixed and live.
