### ISSUE TITLE
go/types: identifier resolved incorrectly

### ISSUE THREAD

**Issue by alandonovan** [golang/go#24026]
The type checker incorrectly resolves the reference in `f(0)` in the program below to the local variable f declared on the same line, not the package-level function f.

```$ go version
go version devel +a66af7280d Wed Feb 21 21:23:08 2018 +0000 linux/amd64
$ cat a.go
package main

func f(x int) string

func g() {
        f := func() string { return f(0) }
        f()
}
$ go run $GOROOT/src/go/types/gotype.go -- a.go
a.go:6:32: too many arguments
```

**Comment by griesemer** [comment]
This appears to only happen for short variable declarations; `var f = func() { ... f() ... }` seems to be ok. So there's at least a temporary work-around.

This bug was likely newly introduced with some of the 1.11 changes for go/types.
