### ISSUE TITLE
x/tools: rewrite history to remove 14.6 MB blob

### ISSUE THREAD

**Issue by andybons** [golang/go#24020]
Log of what was done:
On release-branch.go1.10:
+ `git reset --hard HEAD~4`
+ `git push -f <internal url for tools Gerrit repo> localbranch:release-branch.go1.10`
+ Resulted in `HEAD` at `25101aad - (godoc,cmd/getgo: update download links to dl.google.com)`

On master:
+ `git reset --soft HEAD~2`
+ `git add .`
+ `git commit`
+ `git push -f <internal url for tools Gerrit repo>`

The above (for master) was repeated three times due to commit message issues. At one point, HEAD was:
+ `25b48f88`
+ `84831f73`
+ `ab0261ad`

Until I completely reverted the commit and reset HEAD to `07fd8470d635b985c9c749fa83bdbc2f20b35d42 - godoc/dl: provide JSON feed of releases`

**Comment by bradfitz** [comment]
Original bad CL with 14.6 MB godoc binary:
https://go-review.googlesource.com/c/tools/+/96055

Added to x/tools master as 4a5950d5e6ace466ebfb8c804312e5da044e2feb
And chery-picked to release-branch.go1.10 as https://go-review.googlesource.com/c/tools/+/96056 (2b679cfe11e767351d90b4140efd41a892327422)

**Comment by bradfitz** [comment]
x/tools master was force-reset back to:
https://go.googlesource.com/tools/+/07fd8470d635b985c9c749fa83bdbc2f20b35d42

**Comment by bradfitz** [comment]
Bug to make sure this doesn't happen again: #10658

**Comment by bradfitz** [comment]
x/tools release-branch.go.10 was reset back to: https://go.googlesource.com/tools/+/25101aadb97aa42907eee6a238d6d26a6cb3c756

**Comment by andybons** [comment]
Updated comment with log.

**Comment by robpike** [comment]
I just knew in my heart this would lead back to a blunder I made.

**Comment by andybons** [comment]
Closing as there doesn’t appear to be any issues. Please reopen if anything pops up.
