### ISSUE TITLE
x/vgo: go get vgo error

### ISSUE THREAD

**Issue by runzexia** [golang/go#24030]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 windows/386

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\junwuhui\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\junwuhui\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\junwuhui\AppData\Local\Temp\go-build252696518=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
```
go get -u golang.org/x/vgo
```

### What did you expect to see?

install vgo successful

### What did you see instead?

# syscall
C:\Go\src\syscall\ztypes_windows.go:9:36: ERROR_FILE_NOT_FOUND redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:9:36
C:\Go\src\syscall\ztypes_windows.go:10:36: ERROR_PATH_NOT_FOUND redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:10:36
C:\Go\src\syscall\ztypes_windows.go:11:36: ERROR_ACCESS_DENIED redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:11:36
C:\Go\src\syscall\ztypes_windows.go:12:36: ERROR_NO_MORE_FILES redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:12:36
C:\Go\src\syscall\ztypes_windows.go:13:36: ERROR_HANDLE_EOF redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:13:36
C:\Go\src\syscall\ztypes_windows.go:14:36: ERROR_NETNAME_DELETED redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:14:36
C:\Go\src\syscall\ztypes_windows.go:15:36: ERROR_FILE_EXISTS redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:15:36
C:\Go\src\syscall\ztypes_windows.go:16:36: ERROR_BROKEN_PIPE redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:16:36
C:\Go\src\syscall\ztypes_windows.go:17:36: ERROR_BUFFER_OVERFLOW redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:17:36
C:\Go\src\syscall\ztypes_windows.go:18:36: ERROR_INSUFFICIENT_BUFFER redeclared in this block
        previous declaration at C:\Go\src\syscall\types_windows.go:18:36
C:\Go\src\syscall\ztypes_windows.go:18:36: too many errors

**Comment by mvdan** [comment]
This seems like an issue with your Go install. Make sure that you are running a working version of Go 1.10.

**Comment by runzexia** [comment]
sorry, I installed the wrong version.
