### ISSUE TITLE
Not sensitive to creating unsafe code by language grammar

### ISSUE THREAD

**Issue by okabbas** [golang/go#24037]
Hello . I noticed that the compiler does not check code at runtime for the safety of the values.
For example, consider the following code.

```
package main

import "fmt"

func main() {
  var a = make([]int, 0, 10)
  a = append(a, 1, 2, 3, 4)
  b := append(a, 5, 6, 7)
  c := append(a, 8, 9, 10, 111, 12, 13, 14)
  a[1] = 2222
  fmt.Println(b[1], "," , c[1])
}
```

> output : 2222 , 2

The output of this code is something that is not expected.

For example, consider the following code. This is the modified code in the example above.

```
package main

import "fmt"

func main() {
	slice := make([]int, 0, 10)
	slice = append(slice, 1,2,3,4,5,6,72,48,49,10,11,12,13,14,1455)
	slice[1] = 2222
	fmt.Println(slice[1], "," ,slice[1])
}
```

> output : 2222 , 2222

Do not you think it's better not to create an unsafe code before compiling the code and to solve these complexities so that novice programmers and ... do not face these problems?

**Comment by pciet** [comment]
I think the documentation accurately describes this behavior: https://golang.org/pkg/builtin/#append

The pattern I follow is assuming append invalidates the input slice.

**Comment by okabbas** [comment]
Look at the source code and outputs:
**source :** 
```
func main() {
  var a = make([]int, 0, 10)
  a = append(a, 1, 2, 3, 4)
  b := append(a, 5, 6, 7)
  c := append(a, 8, 9, 10, 111, 12, 13, 14)

  a[1] = 2222

  fmt.Println(a)
  fmt.Println(b)
  fmt.Println(c)
}
```
**output :** 
```
[1 2222 3 4]
[1 2222 3 4 5 6 7]
[1 2 3 4 8 9 10 111 12 13 14]
```

**source :** 
```
  var a = make([]int, 0, 10)
  a = append(a, 1, 2, 3, 4)
  a[1] = 2222
  b := append(a, 5, 6, 7)
  c := append(a, 8, 9, 10, 111, 12, 13, 14)

  fmt.Println(a)
  fmt.Println(b)
  fmt.Println(c)
```
**output:** 

> [1 2222 3 4]
> [1 2222 3 4 5 6 7]
> [1 2222 3 4 8 9 10 111 12 13 14]

What is the reason for these different outputs? Why does the variable "a" act for the variable "b" like the observerable design pattern, but does not do this for the variable "c" and solves the problem in the second source?

**Comment by pciet** [comment]
```
  var a = make([]int, 0, 10)
  // a = {} cap 10

  a = append(a, 1, 2, 3, 4)
  // a = {1, 2, 3, 4} cap 10

  b := append(a, 5, 6, 7)
  // b = {1, 2, 3, 4, 5, 6, 7} cap 10, b points to same start as a but has longer len

  c := append(a, 8, 9, 10, 111, 12, 13, 14)
  // c = {1, 2, 3, 4, 8, 9, 10, 111, 12, 13, 14} 
  // cap x, new allocation because len > cap, different memory than a and b

  a[1] = 2222
  // a[1] = 2222 also affects b
```

```
  var a = make([]int, 0, 10)
  // a = {} cap 10

  a = append(a, 1, 2, 3, 4)
  // a = {1, 2, 3, 4} cap 10

  b := append(a, 5, 6, 7)
  // b = {1, 2, 3, 4, 5, 6, 7}, cap 10, reslice, same memory as a

  c := append(a, 8, 9, 10, 111, 12, 13, 14)
  // c = {1, 2, 3, 4, 8, 9, 10, 111, 12, 13, 14} // cap x, new allocation, a/b left alone

  a[1] = 2222
  // since a and b point to the same memory writing a[1] also affects b[1]
```

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
