### ISSUE TITLE
x/vgo: add ability to report list of directly imported modules

### ISSUE THREAD

**Issue by skseth** [golang/go#24042]
A common pattern with the minimal version selection would be for each module owner to update to the latest applicable version of their direct dependencies, but accept the minimal version for any transitive dependency. 

For example, if my module A depends on B and C, which both in turn depend on D, i want the latest of B and C only, and then transitively pull in the minimal version D compatible with B and C. 

At this point i have a command "vgo get -u" which will get me the latest of B and C, but also D, which i may not want. The request is for something like "vgo get -u -directonly", which would restrict the upgradation to the latest versions of the direct dependencies B and C.

**Comment by rsc** [comment]
I think more generally we might want a way to list the modules imported directly from this one. Then you just want `vgo get -u <that list>`. Will think about that.

**Comment by rsc** [comment]
There's not a flag but after the CLs I have pending you can use

    vgo get $(vgo list -m -f '{{if and (not .Indirect) (not .Main)}}{{.Path}}{{end}}' all)
