### ISSUE TITLE
x/vgo: load does not look at -tags build flag

### ISSUE THREAD

**Issue by philpennock** [golang/go#24053]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.10 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pdp/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pdp/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vs/7q9nz5955_z7b7zxfz437zrm0000gn/T/go-build533554610=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Following on from issue #24052 I tried to make sure that my app built with added dependencies enabled via a build tag.  The "production" deploy of `go.pennock.tech/dummyapp` consists of building a scratch-based Docker image for pushing as an image to Heroku.  It is built with the `heroku` build-tag, which adds an extra package import, of Heroku's metrics exporter library.

In the same directory and setup (same shell instance) as the previous successful build for #24052 I tried to enable this extra dependency:

```
% vgo build -tags heroku
build go.pennock.tech/dummyapp: cannot find module for path github.com/heroku/x/hmetrics
```

What does vgo think the dependencies are?

```
% vgo list -m
MODULE                      VERSION
go.pennock.tech/dummyapp    -
github.com/sirupsen/logrus  v1.0.4
golang.org/x/crypto         v0.0.0-20180222182404-49796115aa4b
golang.org/x/sys            v0.0.0-20180222210305-c1138c84af3a
% vgo list -tags heroku -m
MODULE                      VERSION
go.pennock.tech/dummyapp    -
github.com/sirupsen/logrus  v1.0.4
golang.org/x/crypto         v0.0.0-20180222182404-49796115aa4b
golang.org/x/sys            v0.0.0-20180222210305-c1138c84af3a
```

### What did you expect to see?

A successful build.

### What did you see instead?

What looks like `vgo` not using the build tags when deriving the list of dependencies to be resolved, only when later selecting the files to be compiled.

**Comment by rsc** [comment]
Yes, probably cmd/go/internal/imports needs to change var Tags to func Tags() and make it look at cfg.Tags in addition to the initial list. Oops.
