### ISSUE TITLE
x/vgo: verify should ignore not-yet-downloaded dependencies

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#24067]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +104445e Wed Feb 7 19:22:09 2018 +0000 linux/amd64 vgo:2018-02-20.1

### What did you do?

    % vgo build ./...
    % vgo test ./...
    ok etc
    % vgo verify
    vgo: resolving import "github.com/pkg/errors"
    vgo: finding github.com/pkg/errors (latest)
    vgo: adding github.com/pkg/errors v0.8.0
    vgo: resolving import "launchpad.net/gocheck"
    vgo: import "launchpad.net/gocheck": unknown VCS, Repo: bzr, 
    https://launchpad.net/~niemeyer/gocheck/trunk

Ignoring the fact that vgo doesn't support bzr yet, it's arguably wrong that vgo verify verifies more than we've already chosen to depend on. I wished to verify my current build and its dependencies, but not necessarily the testing dependencies of those dependencies (which can be considerably more substantial, and might not be available).

I wasn't expecting verify to download or resolve any more dependencies than I'd already used.

**Comment by oiooj** [comment]
At https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/vgo/search.go#L165

 Default level is `levelTestRecursive `.

 Should we add an argument for func `AllPackages` and func `MatchPackages ` ? or use a global level var ?  @rsc
