### ISSUE TITLE
x/build: nacl-386 failed

### ISSUE THREAD

**Issue by dsnet** [golang/go#24089]
Just [saw this failure](https://storage.googleapis.com/go-build-log/3a5dede1/nacl-386_daf62e32.log) on [CL/96895](https://go-review.googlesource.com/c/go/+/96895):
```
** Signal 11 from trusted code: pc=5661f1d0
FAIL	runtime	2.837s
2018/02/23 23:22:24 Failed: exit status 1
2018/02/23 23:22:25 FAILED


Error: tests failed: dist test failed: runtime:cpu124: exit status 1
```

**Comment by bradfitz** [comment]
Closing nacl bugs, as we're removing nacl (golang/go#30439)
