### ISSUE TITLE
os.Lookup fails for LDAP user when cross compiled on darwin arch

### ISSUE THREAD

**Issue by jaloren** [golang/go#24083]
If I compile the same program on linux arch, the issue does not reproduce.

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/Volumes/Repositories/go/bin"
GOCACHE="/Users/jlorenzini/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/Repositories/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/7ndx_j6s36x9hm9dns67j21s3hynqn/T/go-build149608786=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

I cross compiled the following program on a mac and then ran it on linux VM. I first passed a local user that is /etc/passwd. I then passed in a user that is in openldap. The first run passed  while the second failed.

```
package main

import (
	"log"
	"os"
	"os/user"
)

func main() {
	u := os.Args[1]
	user, err := user.Lookup(u)
	if err != nil {
		log.Fatalf("failed to find user %s: %v", u, err)
	}
	log.Println(user)
}
```

### What did you expect to see?
When querying for an ldap user that exists, the Lookup func should actually return the user.

### What did you see instead?
Instead of returning the ldap user as expected, the Lookup func returned an error.

**Comment by bradfitz** [comment]
This is expected. When cross-compiling, cgo is disabled by default. To do your LDAP lookups, you need NSS via libc, which is only available when you use cgo. You can build from a Mac, but you'll need to set CGO_ENABLED=1 and then have the appropriate C toolchain installed on your Mac.
