### ISSUE TITLE
cmd/cgo: _GoString_ is unavailable

### ISSUE THREAD

**Issue by LionNatsu** [golang/go#24097]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.9.4 linux/amd64`

### Does this issue reproduce with the latest release?
I don't know.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lion/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build491035465=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
```
package main

/*
#include <stdio.h>
void do_something(_GoString_ go_string) {
    return;
}
*/
import "C"

func main() {
	C.do_something("example")
}
```

### What did you expect to see?
Go compiles it successfully.

### What did you see instead?
```
....go:12:2: could not determine kind of name for C.do_something

gcc errors for preamble:
....go:5:19: error: unknown type name '_GoString_'
 void do_something(_GoString_ go_string) {
                   ^~~~~~~~~~
```

### Documentation

https://golang.org/cmd/cgo/#hdr-Go_references_to_C
> A C function may be declared in the Go file with a parameter type of the special name `_GoString_`. This function may be called with an ordinary Go string value. The string length, and a pointer to the string contents, may be accessed by calling the C functions
>
>     size_t _GoStringLen(_GoString_ s);
>     const char *_GoStringPtr(_GoString_ s);
> These functions are only available in the preamble, not in other C files. The C code must not modify the contents of the pointer returned by `_GoStringPtr`. Note that the string contents may not have a trailing `NUL` byte.

**Comment by crvv** [comment]
It is a new feature added in Go 1.10.

https://golang.org/doc/go1.10#cgo

**Comment by LionNatsu** [comment]
@crvv Thank you...
