### ISSUE TITLE
x/vgo: decide how much to support gopkg.in

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#24099]
### What version of Go are you using (`go version`)?

go version devel +104445e Wed Feb 7 19:22:09 2018 +0000 linux/amd64 vgo:2018-02-20.1

### What did you do?

	% cat go.mod
	module "github.com/rogpeppe/xx"
	
	require "gopkg.in/yaml.v2" v2.1.0
	% vgo build
	vgo: errors parsing go.mod:
	/tmp/xx/go.mod:3: invalid module: gopkg.in/yaml.v2 should be v1, not v2 (v2.1.0)

If I change the module name in the requirements to "gopkg.in/yaml/v2", I see this output:

	% vgo build
	vgo: finding gopkg.in/yaml/v2 v2.1.0
	vgo: gopkg.in/yaml/v2: invalid gopkg.in/ path: "gopkg.in/yaml/v2"
	vgo: finding gopkg.in/yaml/v2 v2.1.0
	vgo: gopkg.in/yaml/v2: invalid gopkg.in/ path: "gopkg.in/yaml/v2"
	vgo: invalid gopkg.in/ path: "gopkg.in/yaml/v2"

**Comment by rogpeppe** [comment]
OK, I see what's happening now. It's not grokking the major-version-in-path of gopkg.in.
As an example, if I run `vgo build` on this program:

	package main // import "github.com/rogpeppe/xx"
	
	import (
		_ "gopkg.in/juju/charm.v4"
		_ "gopkg.in/juju/charm.v5"
		_ "gopkg.in/juju/charm.v6"
	)
	
	func main() {
	}

I get this go.mod file:

	module "github.com/rogpeppe/xx"
	
	require (
		"github.com/juju/names" v0.0.0-20180129205841-f9b5b8b7614d
		"gopkg.in/juju/charm.v4" v0.0.0-20150410205938-af4be7b079ac
		"gopkg.in/juju/charm.v5" v0.0.0-20161109084014-949f52b3948c
		"gopkg.in/juju/charm.v6" v0.0.0-20180119231043-96786fc3f869
		"gopkg.in/yaml.v1" v0.0.0-20140924161607-9f9df34309c0
	)

So I titled this issue wrong; it *is* possible to use gopkg.in with a major version > 1, although the behaviour is still not correct.

Interestingly, the go.mod file does not contain all the dependencies that I'd expect. For example, it contains `gopkg.in/yaml.v1` (used by `gopkg.in/juju/charm.v4`) but not `gopkg.in/yaml.v2` (used by `gopkg.in/juju/charm.v6`); it contains `github.com/juju/names` but not `gopkg.in/juju/names.v2`).

**Comment by tgulacsi** [comment]
require "gopkg.in/yaml.v2/v2"

works, sort of - it still includes the "gopkg.in/yaml.v2 v1.1.0-gopkg-v2.1.0" - see #24094

**Comment by rsc** [comment]
> support gopkg.in major versions properly

"Properly" is a loaded word, but it should work at least a little better than it does right now. In the original case the v2.1.0 should probably just be rewritten transparently to v1.1.0-gopkgin-v2.1.0, because we know this is gopkg.in.

I'm going to leave this bug open to track deciding what level of gopkg.in support we want. Maybe we should actually just allow v2.1.0 instead of the funny pseudo-version.

> Interestingly, the go.mod file does not contain all the dependencies that I'd expect. 

It contains a simplified list of dependencies, omitting those implied by the ones already listed. Because charm.v6's dependencies.tsv lists the exact version of gopkg.in/yaml.v2 that the build chose, it lists charm.v6 in the go.mod and stops there.

**Comment by primalmotion** [comment]
this is still happening to me

**Comment by markbates** [comment]
Agreed still doesn't work for me either

```
module github.com/gobuffalo/pop

require (
	github.com/cockroachdb/cockroach-go v0.0.0-20180212155653-59c0560478b7
	github.com/fatih/color v1.6.0
	github.com/go-sql-driver/mysql v1.0.3
	github.com/gobuffalo/envy v1.6.2
	github.com/gobuffalo/packr v1.11.0
	github.com/gobuffalo/uuid v1.2.0
	github.com/gobuffalo/validate v1.0.0
	github.com/jmoiron/sqlx v0.0.0-20180406164412-2aeb6a910c2b
	github.com/joho/godotenv v1.2.0
	github.com/lib/pq v0.0.0-20180327071824-d34b9ff171c2
	github.com/markbates/going v0.0.0-20170113214412-0576708c56ce
	github.com/markbates/inflect v0.0.0-20180405204719-fbc6b23ce49e
	github.com/mattn/anko v0.0.3
	github.com/pkg/errors v0.8.0
	golang.org/x/net v0.0.0-20180420171651-5f9ae10d9af5
	golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
	gopkg.in/yaml.v2 v2.2.1
)
```

```
vgo: errors parsing go.mod:
$GOPATH/src/github.com/gobuffalo/pop/go.mod:20: invalid module: gopkg.in/yaml.v2 should be v1, not v2 (v2.2.1)
````

**Comment by cmars** [comment]
Can we reopen this issue? I'm seeing the same issue as @kron4eg above.

**Comment by keltia** [comment]
I get the same with `yaml.v2`; the initial `go.mod` file was generated by `vgo build` but after that, it fails with the above error.  `yaml.v2` has no tags, does not use semver or anything.

**Comment by lelvisl** [comment]
same problem with elastic 
```
module modulename

require (
	github.com/BurntSushi/toml v0.3.0
	github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
	github.com/garyburd/redigo v1.6.0
	github.com/go-redis/redis v0.0.0-20160126235308-877867d2845fbaf86798befe410b6ceb6f5c29a3
.....
	gopkg.in/olivere/elastic.v3 v1.0.73-gopkgin-v3.0.73
)
```

```
→ vgo build
vgo: errors parsing go.mod:
.../App/go.mod:26: invalid module: gopkg.in/olivere/elastic.v3 should be v1, not v3 (v3.0.73)
```
And if I remove line with elastic from go.mod it builds.

**Comment by illegalnumbers** [comment]
I also see this issue.

**Comment by rsc** [comment]
Fixed by recent CL.

**Comment by krasi-georgiev** [comment]
I am still seeing this with go version go1.12.1 linux/amd64

```
go test github.com/jaegertracing/jaeger/plugin/storage/badger/dependencystore -run ^(TestDependencyReader)$ 

go: github.com/gocql/gocql@v0.0.0-20180506184654-181004e14a3f: parsing go.mod: go.mod:6: invalid module: gopkg.in/inf.v0 should be .v0, not v1 (v1.9.1-gopkgin-v0.9.1)
go: error loading module requirements
```
