### ISSUE TITLE
x/vgo: submodules are not downloaded

### ISSUE THREAD

**Issue by tgulacsi** [golang/go#24094]
### What version of Go are you using (`go version`)?
1.10

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
```
:gthomas@redpath: ~/src/github.com/tgulacsi/go/dbcsv/csvdump
$ vgo build -o /tmp/csvdump
vgo: resolving import "gopkg.in/goracle.v2"
vgo: finding gopkg.in/goracle.v2 (latest)
vgo: adding gopkg.in/goracle.v2 v1.1.15-gopkgin-v2.1.15
# gopkg.in/goracle.v2
../../../../../v/gopkg.in/goracle.v2@v1.1.15-gopkgin-v2.1.15/conn.go:20:10: fatal error: 'dpiImpl.h' file not found
#include "dpiImpl.h"
         ^~~~~~~~~~~
1 error generated.
```

One issue is that `vgo` resolves `gopkg.in/goracle.v2` as `gopkg.in/goracle.v2 v1.1.15-gopkgin-v2.1.15`, even if I put `gopkg.in/goracle.v2/v2 v2.1.15` into the go.mod file,

another issue is that though it downloads goracle.v2, it does not download its `odpi` submodule.
Will submodules be supported, or should we find a workaround?
(Workaround: use `go generate` to download the submodule and rsync into another dir)
If possible, provide a recipe for reproducing the error.

**Comment by tgulacsi** [comment]
I can confirm that copying the C source out from the submodule solves as a workaround.

**Comment by rsc** [comment]
Submodules will not be supported, sorry. That's getting back into the version control detail world that we're trying to get "go get" out of.

**Comment by myitcv** [comment]
Just updated the title here to confirm this discussion is about `git` submodules not being supported. As distinct from `vgo` Go modules (and submodules).
