### ISSUE TITLE
Windows 10 GOPATH 建议

### ISSUE THREAD

**Issue by lanmingle** [golang/go#24109]
在 Windows 10 下编辑环境变量是基于界面操作的，示例：（D:\GO;E:\GO; ）这里多出了（;），GO 中不能识别多出这个（;），很无奈只能手动修改，建议兼容这个值。

测试版本：1.8.3 1.9.2 1.10

**Comment by bradfitz** [comment]
> Editing environment variables under Windows 10 is based on the interface operation, example: (D: \ GO; E: \ GO;) Here more (;), GO can not identify more this Manual modification, it is recommended to be compatible with this value.
>
> Test Version: 1.8.3 1.9.2 1.10

Sorry, is this a bug report about Go, or a question about using Go?

For questions about Go, see https://golang.org/wiki/Questions.
