### ISSUE TITLE
x/vgo: replace directive does not work with modules that do not have a go.mod

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#24110]
### What version of Go are you using (`go version`)?

`go version go1.10 linux/amd64 vgo:2018-02-20.1`

### What operating system and processor architecture are you using (`go env`)?

`linux` `amd64`

</details>

### What did you do?

The root module, `github.com/leighmcculloch/today.bible` contains this go.mod file. None of its dependencies have a go.mod file.

```
module "github.com/leighmcculloch/today.bible"

require (
        "4d63.com/biblepassageapi" v0.0.0-20180105044528-9d5d1c7387b7
        "4d63.com/biblestats" v0.0.0-20180221070837-db3cb0a63ce6
        "4d63.com/collapsewhitespace" v0.0.0-20180206055443-697160e33fd4
        "4d63.com/static" v0.0.0-20180221054436-5af232ad25e5
        "4d63.com/youtubelength" v0.0.0-20180105163403-5f3917c3a5f1
)

replace (
        "4d63.com/biblepassageapi" v0.0.0-20180105044528-9d5d1c7387b7 => "../go-biblepassageapi"
)
```

### What did you expect to see?

```
$ vgo build
```

### What did you see instead?

```
$ vgo build
vgo: open /home/leighmcculloch/go-biblepassageapi/go.mod: no such file or directory
```

### Additional notes

- The `vgo build` command works when the replace directive is not present.
- The `vgo build` command works if a `go.mod` file is added to the version of `4d63.com/biblepassagepi` that I'm referencing with the replace.

**Comment by rsc** [comment]
I think this is working as intended. The idea behind replace is to drop in one module for another. Vgo needs that module's requirements and such.

**Comment by leighmcculloch** [comment]
@rsc So to replace a dependency it's working as intended that the dependency must have a go.mod file?

**Comment by anacrolix** [comment]
It seems unnecessary to have this requirement. In the issue I referenced, we're trying to use a dependency that has no go mod specifically to get go mod working.

**Comment by anacrolix** [comment]
I think this might actually work as I expected, no go.mod file is required, I just had a typo on the left side of the `=>` after `replace`. Perhaps there could be a warning if unused packages are replaced? That seems thematic for Go.
