### ISSUE TITLE
unsafe: wrong type mentioned in explanation

### ISSUE THREAD

**Issue by dotaheor** [golang/go#24115]
> In this usage hdr.Data is really an alternate way to refer to the underlying pointer in the **slice** header, not a uintptr variable itself. 

**slice** should be **string**

**Comment by FiloSottile** [comment]
The line should still say string, not slice, because `hdr.Data` refers to the string header.

However yeah there is also a phantom pointer `p` to an object (array?) of length `n` that the string is being redefined to, which makes the doc very hard to read. I would like to see an explicit p added.

**Comment by ianlancetaylor** [comment]
I can't come up with a reasonable way to define `p` and `n` in this example.  The only plausible case is calling a cgo function, but I don't want to have to refer to cgo here.
