### ISSUE TITLE
invalid flag in #cgo CFLAGS: -arch

### ISSUE THREAD

**Issue by W-B-S** [golang/go#24113]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

localhost:~ wsli$ go version
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wsli/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wsli/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0j/8lghc3kd7yx2c_1lp9zhc6_h0000gn/T/go-build160152071=/tmp/go-build -gno-record-gcc-switches -fno-common"
localhost:~ wsli$ cd /Users/wsli/go/

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
no error

### What did you see instead?
INFO[0118] installing full qt/core                      
ERRO[0118] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/core" env= error="exit status 1" func=RunCmdOptionalError name="install core"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0118] installing full qt/androidextras             
INFO[0118] installing full qt/gui                       
ERRO[0118] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/gui" env= error="exit status 1" func=RunCmdOptionalError name="install gui"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0118] installing full qt/network                   
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/network" env= error="exit status 1" func=RunCmdOptionalError name="install network"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/xml                       
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/xml" env= error="exit status 1" func=RunCmdOptionalError name="install xml"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/dbus                      
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/dbus" env= error="exit status 1" func=RunCmdOptionalError name="install dbus"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/nfc                       
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/nfc" env= error="exit status 1" func=RunCmdOptionalError name="install nfc"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/script                    
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/script" env= error="exit status 1" func=RunCmdOptionalError name="install script"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/sensors                   
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/sensors" env= error="exit status 1" func=RunCmdOptionalError name="install sensors"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/positioning               
ERRO[0119] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/positioning" env= error="exit status 1" func=RunCmdOptionalError name="install positioning"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0119] installing full qt/widgets                   
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/widgets" env= error="exit status 1" func=RunCmdOptionalError name="install widgets"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/sql                       
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/sql" env= error="exit status 1" func=RunCmdOptionalError name="install sql"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/macextras                 
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/macextras" env= error="exit status 1" func=RunCmdOptionalError name="install macextras"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/qml                       
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/qml" env= error="exit status 1" func=RunCmdOptionalError name="install qml"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/websockets                
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/websockets" env= error="exit status 1" func=RunCmdOptionalError name="install websockets"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/xmlpatterns               
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/xmlpatterns" env= error="exit status 1" func=RunCmdOptionalError name="install xmlpatterns"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/bluetooth                 
ERRO[0120] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/bluetooth" env= error="exit status 1" func=RunCmdOptionalError name="install bluetooth"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0120] installing full qt/webchannel                
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/webchannel" env= error="exit status 1" func=RunCmdOptionalError name="install webchannel"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/svg                       
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/svg" env= error="exit status 1" func=RunCmdOptionalError name="install svg"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/multimedia                
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/multimedia" env= error="exit status 1" func=RunCmdOptionalError name="install multimedia"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/quick                     
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/quick" env= error="exit status 1" func=RunCmdOptionalError name="install quick"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/help                      
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/help" env= error="exit status 1" func=RunCmdOptionalError name="install help"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/location                  
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/location" env= error="exit status 1" func=RunCmdOptionalError name="install location"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/scripttools               
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/scripttools" env= error="exit status 1" func=RunCmdOptionalError name="install scripttools"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/uitools                   
ERRO[0121] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/uitools" env= error="exit status 1" func=RunCmdOptionalError name="install uitools"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0121] installing full qt/webengine                 
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/webengine" env= error="exit status 1" func=RunCmdOptionalError name="install webengine"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/testlib                   
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/testlib" env= error="exit status 1" func=RunCmdOptionalError name="install testlib"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/serialport                
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/serialport" env= error="exit status 1" func=RunCmdOptionalError name="install serialport"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/serialbus                 
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/serialbus" env= error="exit status 1" func=RunCmdOptionalError name="install serialbus"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/printsupport              
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/printsupport" env= error="exit status 1" func=RunCmdOptionalError name="install printsupport"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/designer                  
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/designer" env= error="exit status 1" func=RunCmdOptionalError name="install designer"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/scxml                     
ERRO[0122] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/scxml" env= error="exit status 1" func=RunCmdOptionalError name="install scxml"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0122] installing full qt/gamepad                   
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/gamepad" env= error="exit status 1" func=RunCmdOptionalError name="install gamepad"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/purchasing                
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/purchasing" env= error="exit status 1" func=RunCmdOptionalError name="install purchasing"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/datavisualization         
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/datavisualization" env= error="exit status 1" func=RunCmdOptionalError name="install datavisualization"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/charts                    
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/charts" env= error="exit status 1" func=RunCmdOptionalError name="install charts"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/speech                    
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/speech" env= error="exit status 1" func=RunCmdOptionalError name="install speech"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/quickcontrols2            
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/quickcontrols2" env= error="exit status 1" func=RunCmdOptionalError name="install quickcontrols2"
github.com/therecipe/qt/quickcontrols2
go build github.com/therecipe/qt/quickcontrols2: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/sailfish                  
ERRO[0123] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/sailfish" env= error="exit status 1" func=RunCmdOptionalError name="install sailfish"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

INFO[0123] installing full qt/webview                   
ERRO[0124] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/webview" env= error="exit status 1" func=RunCmdOptionalError name="install webview"
github.com/therecipe/qt/webview
go build github.com/therecipe/qt/webview: invalid flag in #cgo CFLAGS: -arch

INFO[0124] installing full qt/remoteobjects             
ERRO[0124] failed to run command                         cmd="go install -p 4 -v github.com/therecipe/qt/remoteobjects" env= error="exit status 1" func=RunCmdOptionalError name="install remoteobjects"
github.com/therecipe/qt/core
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -arch

**Comment by nigec** [comment]
Yes I'm getting the same after updating go and trying to re install qt go

**Comment by ianlancetaylor** [comment]
Consolidating into #23937.
