### ISSUE TITLE
Shebang support 

### ISSUE THREAD

**Issue by hoshsadiq** [golang/go#24118]
I wanted to run golang using shebang and noticed it basically refused to work. With that I stumbled on a great [gist relating to this issue](https://gist.github.com/posener/73ffd326d88483df6b1cb66e8ed1e0bd). It goes to the ins and outs and shows workarounds. It would be nice to allow shebang support natively so we can both compile and run a main function.

Simply put, the following should be possible:

- new go executable (similar to the gorun in the aforementioned gist) that can be put in the shebang. This should handle exit codes correctly.
- go compiler should ignore shebang lines.

In the end, if we have the following script (this is from the gist mentioned earlier):
```
#!/usr/bin/env goexec

package main

import (
  "fmt"
  "os"
)

func main() {
  fmt.Println("Hello", os.Args[1])
  os.Exit(42)
}
```

And running it as:
```
$ ./example.go world
Hello world
exit status 42
$ echo $?
42
```

**Comment by bradfitz** [comment]
This has been proposed and rejected a number of times in the past.

Here is one of the earlier threads on the topic: https://groups.google.com/forum/#!topic/golang-nuts/iGHWoUQFHjg/discussion

Here are search results for `shebang` on the golang-nuts mailing list and the bug tracker:

https://groups.google.com/forum/#!searchin/golang-nuts/shebang%7Csort:date

https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+shebang
