### ISSUE TITLE
encoding/gob: not decodable from another instance of same program

### ISSUE THREAD

**Issue by pjebs** [golang/go#24126]
I have the same program running on 2 different nodes (kubernetes scaling).

I called `gob Register` and then `Encode` the `interface{}` struct and store the value in a common redis instance.

This works as intended and perfectly if the `Decode` occurs from the same instance that encoded it.

If the decode occurs from the other instance it fails.

I suspect the `Register` function is the culprit when dealing with encoding interfaces.

Is this a bug. If not, this greatly detracts from the portability of the gob package.

**Comment by pjebs** [comment]
@andizzle

**Comment by cznic** [comment]
Please add a minimal self-contained reproducer.

Side note: registering interface type assigns a number -> type mapping. The decoding process must register the same types in the same order otherwise the type numbers do not match. Is you program written in such a way that the type-registering order is deterministic and repeatable? I've had a similar problem in cznic/ql#67.

**Comment by pjebs** [comment]
I just use plain `Register`

**Comment by cznic** [comment]
That's the only option ;-) But the interesting information is if the're only a single call to `Register` in the whole program, or if there are more of them. In the later case, it's important to guarantee, that they always occur in the exact same order. Note that any package you import may also call `Register`. As long as the encoding and decoding programs are identical _and_ the calls to `Register` occur only in `init()` functions, this should be guaranteed. Is that the case in you failing program?

**Comment by andizzle** [comment]
@pjebs, @cznic could be right, we are not using `init()` to `Register`. The `Register` can occur multiple times in dynamic order in the current program. Let's investigate.

**Comment by pjebs** [comment]
Closing. Gob is working as intended.
Our situation was caused because the second instance, after decoding the encoded gob in redis, didn't have the struct registered.
