### ISSUE TITLE
url.Parse invalid userinfo 1.9 - > 1.10

### ISSUE THREAD

**Issue by deepch** [golang/go#24129]
func url.Parse

rtsp://admin:[kfljrjv,by@91.100.86.110:554/mpeg4

return

go 1.9

err = nil

go 1.10

err = parse rtsp://admin:[kfljrjv,by@91.100.86.110:554/mpeg4: net/url: invalid userinfo

error on char [ go 1.10

**Comment by namusyaka** [comment]
It's on purpose, I think.
See [the issue](https://github.com/golang/go/issues/23392) and [its CL](https://go-review.googlesource.com/c/go/+/87038).

If you want to do more productive report on this subject, please fill out the required information according to github template.

**Comment by deepch** [comment]
I did not find an answer to this behavior and how to fix it except rollback at 1.9
I realized that I have to tell all users not to use ], but I think this is a bad idea.

**Comment by namusyaka** [comment]
@deepch It works well for passing the escaped `]` (`%5B`).
Will this not be a solution?
