### ISSUE TITLE
missing type in strings package s

### ISSUE THREAD

**Issue by merodiro** [golang/go#24134]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
irrelevant

### What did you expect to see?
func Split(s string, sep string)

### What did you see instead?
func Split(s, sep string)

some functions in [Strings](https://github.com/golang/go/blob/master/src/strings/strings.go) doesn't specify the type of `s`

**Comment by merodiro** [comment]
thank you for clarification, I thought it's missing when I looked at the documentation of the package

**Comment by merodiro** [comment]
should I edit it to `TrimRight(s, cutset string) string` and edit other trim functions to keep it consistent?
or it's okay that way?

**Comment by dominikh** [comment]
Things are fine the way they are.

**Comment by merodiro** [comment]
okay, I'm still new in golang but it seems strange to me that some functions have string in both parameters and some have it only once, I know that both ways work the same but shouldn't it be consistent or there is no guidelines about that in golang?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

**Comment by dominikh** [comment]
> but shouldn't it be consistent or there is no guidelines about that in golang?

Consistency is nice, but minor cleanups like these don't usually warrant their own patches, as they only create churn. If one feels so inclined, one may clean it up when already working on the relevant code for other reasons.

As for the specific case of omitting repeated types: there's no guideline about when (not) to omit them, it's personal taste.
