### ISSUE TITLE
x/vgo: vgo does not resolve latest version of a module for an unknown import

### ISSUE THREAD

**Issue by piersy** [golang/go#24130]
### What version of Go are you using (`go version`)?
`go version go1.10 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/piers/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/piers/projects/testvgo/gopath"
GORACE=""
GOROOT="/home/piers/programs/go1.10"
GOTMPDIR=""
GOTOOLDIR="/home/piers/programs/go1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build762707113=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
1. Created the following go file `/home/piers/projects/testvgo/main.go`
```
package main // import "github.com/piersy/testvgo"

import jwt "github.com/dgrijalva/jwt-go"

func main() {
	println(jwt.MapClaims{})
}

```
2. Created an empty go.mod `> /home/piers/projects/testvgo/go.mod`
3. Ran `vgo build` from inside ` /home/piers/projects/testvgo`

### What did you expect to see?
```
vgo: resolving import "github.com/dgrijalva/jwt-go"
vgo: finding github.com/dgrijalva/jwt-go (latest)
vgo: adding github.com/dgrijalva/jwt-go v3.1.0
vgo: finding github.com/dgrijalva/jwt-go v3.1.0
vgo: downloading github.com/dgrijalva/jwt-go v3.1.0
```

### What did you see instead?
```
vgo: resolving import "github.com/dgrijalva/jwt-go"
vgo: finding github.com/dgrijalva/jwt-go (latest)
vgo: adding github.com/dgrijalva/jwt-go v1.0.2
vgo: finding github.com/dgrijalva/jwt-go v1.0.2
vgo: downloading github.com/dgrijalva/jwt-go v1.0.2
# github.com/piersy/testvgo
./main.go:6:10: undefined: jwt.MapClaims
```

vgo is not resolving the latest version `v3.1.0` of the [jwt-go](https://github.com/dgrijalva/jwt-go/releases) package. It seems like it is only resolving the latest `v1.x.x` version.

**Comment by fhs** [comment]
This works as intended. You need to import `github.com/dgrijalva/jwt-go/v3` instead of `github.com/dgrijalva/jwt-go` and also jwt-go needs a `go.mod` file. See https://research.swtch.com/vgo-module

**Comment by piersy** [comment]
Short of submitting a patch on `github.com/dgrijalva/jwt-go` is there any other way I can depend on the v3.1.0 tag?

**Comment by kardianos** [comment]
Yes. In your go.mod, us the v0-yyyymmdd-rev syntax I believe.

**Comment by piersy** [comment]
@kardianos thanks, that works :)
