### ISSUE TITLE
x/vgo: list -e doesn't continue after errors

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#24149]
go version devel +104445e Wed Feb 7 19:22:09 2018 +0000 linux/amd64 vgo:2018-02-20.1

When I run the `go list` command with the `-e` flag, it succeeds even if the package is erroneous (for example if there are no Go files in the package directory.

This does not seem to be the case with vgo.
For example:

    % vgo list -e database
    vgo: import "database" [/home/rog/go/src/database]: no Go source files

With the go command:

    % go list -e database
    database

This means that a standard idiom for finding out the root directory of a module (`go list -e -f '{{.Dir}}'`) does not work when the root directory of the module doesn't have any Go files in it.

**Comment by rsc** [comment]
Probably the loader needs a revamp first.

**Comment by rsc** [comment]
This is working for me at least. Perhaps it requires CL 121303 or one of my other pending CLs. I will send a CL adding a test and marking this fixed.
