### ISSUE TITLE
[QUESTION] Is it possible to retrieve BIOS/motherboard information with golang-1.10?

### ISSUE THREAD

**Issue by universonic** [golang/go#24146]
Hello, I want to read some hardware/firmware info from motherboard/BIOS, so I wonder if there is a way to do this without calling CLI commands. Thanks.

**Comment by bradfitz** [comment]
If you can get it from the operating system, you can do it from Go. But for questions about Go, see https://golang.org/wiki/Questions. There aren't many people answering questions in this forum.
