### ISSUE TITLE
x/crypto/acme: End polling on 400-series errors

### ISSUE THREAD

**Issue by jsha** [golang/go#24145]
In [x/crypto/acme's WaitForAuthorization](https://github.com/golang/crypto/blob/master/acme/acme.go#L416), polling continues until the response code is either StatusOK or StatusAccepted. However, 400-series errors, like 404 and 403, should generally not be considered retryable, and should result in an immediate error return.

At Let's Encrypt, we are seeing clients in the wild that continue polling their challenges long after those challenges have expired and started serving 404.

**Comment by bradfitz** [comment]
Whoops, sorry. Thanks for the report.

/cc @x1ddos

**Comment by titanous** [comment]
FYI, the [ACMEv2 implementation](https://golang.org/cl/86635) does not have this bug, as it currently errors on all HTTP errors.

@jsha Should clients retry on 5XX errors?

**Comment by jsha** [comment]
Yep, 5XXs should be retried, with the usual backoff.
