### ISSUE TITLE
x/vgo: confused by ./ imports

### ISSUE THREAD

**Issue by neild** [golang/go#24157]
When compiling a package containing `import "./sub"`:

```sh
$ vgo build .
vgo: resolving import "./sub"
FindRepo: Get https://./sub?go-get=1: dial tcp: lookup .: no such host
vgo: import "github.com/neild/test" ->
	import "./sub": Get https://./sub?go-get=1: dial tcp: lookup .: no such host
```

I have no opinion on whether vgo should support relative imports, but it probably should at least recognize them.

**Comment by bradfitz** [comment]
Or this could be the chance to kill them.

**Comment by bradfitz** [comment]
> but it probably should at least recognize them.

Agreed. Enough to say "no", rather than `tcp: lookup .: no such host`

**Comment by rsc** [comment]
They're definitely not supposed to work, but they're not supposed to fail that badly. :-)

(They don't work from within GOPATH today even with the standard go command.)
