### ISSUE TITLE
encoding/json: unmarshal does not correctly zero out slices

### ISSUE THREAD

**Issue by JeremyLoy** [golang/go#24155]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
1.10 is the latest release at the time of this submission

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
[play.golang example showing address reuse](https://play.golang.org/p/uD5ToIYO_tz)
1. Unmarshal or Decode JSON into a `MyStruct`
1. Unmarshal or Decode a second JSON into the same variable
1. Note how the address of the slice did not change

[play.golang example demoing bad behavior](https://play.golang.org/p/NHo3ywlPZli)
1. Unmarshal or Decode JSON into a `MyStruct`
1. Add that struct to a slice of `MyStruct`
1. Unmarshal or Decode a second JSON into the same variable
1. Note how the address of the slice did not change
1. Note how the underlying arrays have merged
1. Note how the `Name` field was deserialized correctly and was not overridden

### What did you expect to see?
`data1` and `data2` were deserialized into structs, and appended to a slice without overriding each other. 

### What did you see instead?
`data2`'s alphabet values overwrote elements in `data1`'s alphabet. This is in contrast to how `name` behaves.

**Comment by bradfitz** [comment]
This sounds familiar. Is this a dup of #21092?

**Comment by JeremyLoy** [comment]
@bradfitz Yes, I believe so. Thanks for pointing me towards that! Is there anything I can do other than a 👍 to bring more attention to #21092?

**Comment by bradfitz** [comment]
Nope. It's already marked as needing a fix for the next release. Thanks!
