### ISSUE TITLE
x/build/cmd/gopherbot: don’t comment referencing a GerritBot change

### ISSUE THREAD

**Issue by andybons** [golang/go#24166]
If a change originated from a PR, then you get two annotations saying the same thing. Example: https://github.com/golang/go/issues/24068#ref-pullrequest-299723365

<img width="782" alt="screen shot 2018-02-28 at 12 09 14 am" src="https://user-images.githubusercontent.com/365204/36771002-aa9f766e-1c1b-11e8-9017-1f91518a99ed.png">

/cc @bradfitz

**Comment by josharian** [comment]
But only the gopherbot one triggers an email, which I personally like receiving. I say we leave the duplicates.

**Comment by andybons** [comment]
@josharian I thought about that, too. Let’s consider this a semi-proposal then. I’ll keep it open and we can take some time to decide. This isn’t exactly high priority :)

/rant Also why doesn’t GitHub notify you via email of these metadata changes?

**Comment by andybons** [comment]
Meh. Let's just leave them so people get the emails.
