### ISSUE TITLE
x/vgo: wrong version parsing

### ISSUE THREAD

**Issue by douglarek** [golang/go#24167]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxx/.go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pq/lsz6sm8956vfcgd42rk4rfn00000gn/T/go-build856585928=/tmp/go-build -gno-record-gcc-switches -fno-common"
VGOMODROOT=""
```

### What did you do?

```
$ vgo get github.com/google/go-github@v15.0.0

$ vgo build
```

You can reproduce it by this repo: https://github.com/gorocks/gist

### What did you expect to see?
no errors happen

### What did you see instead?

```
vgo: errors parsing go.mod:
/xxx/xxx/go/gist/go.mod:4: invalid module: github.com/google/go-github should be v1, not v15 (v15.0.0)
```

**Comment by ALTree** [comment]
Thanks for the report.

This is  #23977. You have to append `/v15` to your package's import path. Closing as a dup.
