### ISSUE TITLE
runtime: don't allocate when converting a single byte to string

### ISSUE THREAD

**Issue by mvdan** [golang/go#24172]
For example:

```
var StringSink string

func Foo(bs []byte) {
    StringSink = string(bs[0])  // no allocation
    StringSink = string(bs[:1]) // no allocation
    StringSink = string(bs)     // no allocation if len(bs)==1
}
```

At the moment, all three allocate, easily measured with:

```
func BenchmarkFoo(b *testing.B) {
        bs := []byte("foobar")
        for i := 0; i < b.N; i++ {
                Foo(bs)
        }
}
```

There is some precedent to this, I believe. For example:

* strconv uses constant strings for small integers - https://go-review.googlesource.com/c/go/+/37963
* byte-sized values no longer allocate when put in interfaces - https://go-review.googlesource.com/c/go/+/35555

This was even briefly mentioned by @mdempsky in 2016, but as far as I can see it was never followed up on: https://github.com/golang/go/issues/17725#issuecomment-257671966

Another potential route would be for `string(bs[0])` and `string(bs[:1])` to not allocate thanks to the compiler, as it can statically know that len==1. However, that could be built on top of the runtime optimization, as a form of skipping the len check and calling the non-allocating runtime func directly.

If there is interest in investigating the performance penalty of such a change, I can work on a prototype CL to get some measurements. Unless this was already measured and discarded by someone, and I haven't been able to find a thread for it.

/cc @randall77 @josharian

**Comment by randall77** [comment]
Go ahead.  This is small enough I don't think we need the proposal process for it.

**Comment by josharian** [comment]
I had a chance sitting around in my tree from `Sat Mar 4 16:55:03 2017` to do this. Apparently I had decided at the time that it wasn't worth it? Unclear. Anyway, I mailed it. The perf numbers may be stale.

And to echo Keith, for small- to medium-sized optimization ideas, no proposal needed in general.

**Comment by mvdan** [comment]
Oh, awesome. I used a proposal in case there was a good reason not to do this that I wasn't aware of.
