### ISSUE TITLE
cmd/compile: internal compiler error: exporter: unexpected type alias in inlined function body

### ISSUE THREAD

**Issue by skipor** [golang/go#24173]
### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release? 
Yes

### What did you do?
```go
package main
type mapAlias = map[interface{}]interface{}
func main() {
	println(mapAlias{})
}
func Foo() {
	println(mapAlias{}) // Works when commented. 
}
```
https://play.golang.org/p/ukZwewCW0be

### What did you expect to see?
The program compiles and print result.

### What did you see instead?
```
<autogenerated>:1:0: internal compiler error: exporter: unexpected type alias mapAlias in inlined function body
```

**Comment by griesemer** [comment]
Slightly minimized reproducer:
```
package p

type notExported = struct{}

func Exported() {
	_ = notExported{}
}
```
