### ISSUE TITLE
syscall: regression in Select() nil timeout parameter

### ISSUE THREAD

**Issue by zhsj** [golang/go#24189]
### What version of Go are you using (`go version`)?

go1.10

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux, arm64 and mips64le

### What did you do?

```
package main

import "syscall"

func main() {
        syscall.Select(0, nil, nil, nil, nil)
}
```

### What did you expect to see?

No panic

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference

However it's fine in 1.9 and on other architectures.

The releated commit is https://github.com/golang/go/commit/bf237f534cc2a5ed23ae7ffa7deb38cbee64cae6

**Comment by bradfitz** [comment]
Indeed:

```go
func Select(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timeval) (n int, err error) {
        ts := Timespec{Sec: timeout.Sec, Nsec: timeout.Usec * 1000}
        return pselect(nfd, r, w, e, &ts, nil)
}
```

Per https://golang.org/doc/go1compat#operating_systems , the `syscall` package is not under the Go 1 compatibility rules, so technically this isn't a regression or worthy of a Go 1.10.1 point release cherry pick.

I suppose we should fix it, though.

In the meantime, you probably want to migrate away from the syscall package and use `golang.org/x/sys/unix` instead.

/cc @tklauser @ianlancetaylor

**Comment by tklauser** [comment]
Oops, sorry about that. CL is on the way.

And FWIW, `unix.Select` from `golang.org/x/sys/unix` also suffers from the same problem on `linux/{mips64x,arm64}`, though you can use `unix.Pselect` there directly. I'll send a CL there as well.
