### ISSUE TITLE
x/net, x/crypto: CONTRIBUTING.md still says GitHub pull requests are not accepted

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#24185]
### What did you do?

I opened a trivial pull request against golang.org/x/crypto, and gerritbot converted my PR to a CL as expected. 

### What did you expect to see?

CONTRIBUTING.md should not have said "We do not accept GitHub pull requests", but perhaps should have mentioned gerritbot.

### What did you see instead?

> We do not accept GitHub pull requests (we use Gerrit instead for code review).

I noticed the same message on x/net/CONTRIBUTING.md, but I did not check any other x/ repositories.

**Comment by jlburkhead** [comment]
Also found these in other golang org repos.
https://github.com/golang/gddo/blame/dcea65fd03382fd4f4df9ebdac117c6e0cde2594/CONTRIBUTING.md#L7
https://github.com/golang/oauth2/blame/2f32c3ac0fa4fb807a0fcefb0b6f2468a0d99bd0/CONTRIBUTING.md#L26
https://github.com/golang/review/blame/f5dbde0c1ab9393757674eb259f2de6e40f1a7b3/CONTRIBUTING.md#L26
https://github.com/golang/tools/blame/059bec968c61383b574810040ba9410712de36c5/CONTRIBUTING.md#L26
https://github.com/golang/blog/blame/bc40a4c35d3ac1807d228e6fabee47ff3ff81cae/CONTRIBUTING.md#L26
https://github.com/golang/crypto/blame/85f98707c97e11569271e4d9b3d397e079c4f4d0/CONTRIBUTING.md#L26
https://github.com/golang/exp/blame/83bc9a11ae1a00a79c4e59fc5d965d21fe14e6bb/CONTRIBUTING.md#L26
https://github.com/golang/image/blame/12117c17ca67ffa1ce22e9409f3b0b0a93ac08c7/CONTRIBUTING.md#L26
https://github.com/golang/mobile/blame/70bad68322f4b891e6b4081ab040469b793a9d4a/CONTRIBUTING.md#L26
https://github.com/golang/net/blame/07e8617a6db2368fa55d4616f371ee1b1403c817/CONTRIBUTING.md#L26
https://github.com/golang/sys/blame/349b81fb5c64ec1734eb6ee148df25459ea48517/CONTRIBUTING.md#L26
https://github.com/golang/talks/blame/ea635b6f98864feb9a06de8d160af885e5999f09/CONTRIBUTING.md#L26
https://github.com/golang/text/blame/b7ef84aaf62aa3e70962625c80a571ae7c17cb40/CONTRIBUTING.md#L26
https://github.com/golang/debug/blame/545543929d8ccc043f8e537de66eafa69c90e046/CONTRIBUTING.md#L26
https://github.com/golang/build/blame/a6dd626c4c4f2d14d483b08abde160f89a436ecd/CONTRIBUTING.md#L26
https://github.com/golang/playground/blame/e9fb1cd9b74f68b2dd4b1c91d359bfce02df60de/CONTRIBUTING.md#L26
https://github.com/golang/tour/blame/057704a6290c29d3b08f62f96d3e2db6932f2ef5/CONTRIBUTING.md#L47
https://github.com/golang/proposal/blame/56005301f39f4a46203ec263cdfe7cf1c4959ac4/CONTRIBUTING.md#L26
https://github.com/golang/arch/blame/23d99967d08deb692f2acbfa3c61a51aef94971e/CONTRIBUTING.md#L26
https://github.com/golang/sublime-config/blame/ed5ebc0a1b1f6621db5c912472c63cb78b9c361e/CONTRIBUTING.md#L28
https://github.com/golang/sublime-build/blame/1cba804ede9c49725dafaf2b0650d274dc5cb086/CONTRIBUTING.md#L28
https://github.com/golang/sync/blame/fd80eb99c8f653c847d294a001bdf2a3a6f768f5/CONTRIBUTING.md#L26
https://github.com/golang/time/blame/6dc17368e09b0e8634d71cac8168d853e869a0c7/CONTRIBUTING.md#L26
https://github.com/golang/term/blame/aa45bf8df010468bfb784c40129051b79cfd6e43/CONTRIBUTING.md#L26
https://github.com/golang/perf/blame/ea1fc7ea91ba64ca9b3d0d016e9627a931b6abf8/CONTRIBUTING.md#L26

**Comment by andybons** [comment]
The remaining notes about this have been removed. Thanks for collecting the instances, @jlburkhead!

**Comment by bontibon** [comment]
@andybons The notice PR in the oauth2 package is still open: https://github.com/golang/oauth2/pull/218

**Comment by andybons** [comment]
@bontibon closed. Thanks!
