### ISSUE TITLE
os OpenFile gives Error Invalid Argument for file path strings with padded null bytes

### ISSUE THREAD

**Issue by thiremani** [golang/go#24195]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?
https://play.golang.org/p/yVd9EYkhbo-

### What did you expect to see?
A more informative error which says file path too long.

This was hard to debug too, because printing the string did not show string was of length 255 bytes. (As shown in the link to reproduce the error). I had to print bytes from which the string was created to know the string was too long.

### What did you see instead?
Error of type *PathError, which says "Invalid argument"

**Comment by peczenyj** [comment]
Hello

The error came from this line
```

**Comment by thiremani** [comment]
I like both suggestions. E_PRECOND_FAIL seems better as ByteSliceFromString does exactly what it promises to do.

On a side note, why does ByteSliceFromString throw error for NUL bytes? A standard C string is NULL terminated, so once we hit the NULL byte, no need to go ahead. Then copy that string into a byte array and return.

**Comment by peczenyj** [comment]
I can imagine some reasons to prevent send an String with null bytes, like security. Go can be a proxy to a buffer-overflow attack, etc.

**Comment by thiremani** [comment]
Fair point

**Comment by bradfitz** [comment]
> On a side note, why does ByteSliceFromString throw error for NUL bytes? A standard C string is NULL terminated, so once we hit the NULL byte, no need to go ahead. Then copy that string into a byte array and return.

A C string does, yes, but a Go string does not, and ByteSliceFromString takes a Go string. If you give it a string with NULLs, it's a big signal that you're doing something wrong, and we'll by definition lose data when converting it to a C string, since `len(goString with null) != C.strlen(resulting C string)`. So returning invalid makes sense.

I don't think it's worth inventing new error codes like "E_PRECOND_FAIL" for this. The user will get an error, Fatalf("%q") their input string, see the null bytes, and fix their bug. Considering this is the first bug report in 6 years about this, it probably doesn't happen enough to warrant adding new API surface.

**Comment by slrz** [comment]
These would be breaking changes. Although the syscall package is not part of the Go1 promise, gratuitous API changes should be avoided, if reasonably possible.

That said, EINVAL seems to be a reasonable choice upon encountering an invalid argument. It's also what programs already know to check for.

**Comment by thiremani** [comment]
> I don't think it's worth inventing new error codes like "E_PRECOND_FAIL" for this. The user will get an error, Fatalf("%q") their input string, see the null bytes, and fix their bug. Considering this is the first bug report in 6 years about this, it probably doesn't happen enough to warrant adding new API surface.

Yes, I agree. Perhaps could be because I'm new to go, it took me a while to debug. What foxed me was fmt.Println(string) only printed the string without the padded 0 bytes. I see now that fmt.Printf("%q", string) actually shows the zero bytes.

Maybe changing the fmt.Println(string) function is an option here? The fact that Println could hide from the user certain aspects of the string is worrying. It gives a misleading impression of the length of the string. Though len(string) clears up that, a general user depends heavily upon the Print statement for his day-to-day debugging/information gathering

**Comment by bradfitz** [comment]
Sorry, we can't change fmt.Print.

Doing,

```go
	fmt.Print("foo\x00\x00")
```

Will literally the input.

If you redirect it to a file, you should get exactly those bytes. Changing fmt would break people's programs and corrupt data.

Changing the `log` package might be possible, though. You can file a proposal for that if you'd like.

Hope you're enjoying Go besides this. :)

**Comment by thiremani** [comment]
> If you redirect it to a file, you should get exactly those bytes. Changing fmt would break people's programs and corrupt data.

Tested this and you're perfectly right. Okay, so its only when Println goes to stdout it does not show the NUL bytes in the string. Not as important.

I actually quite like Go. It's amazingly quick to develop and test.

**Comment by cznic** [comment]
> Okay, so its only when Println goes to stdout it does not show the NUL bytes in the string. 

That's conflating data and their presentation. The zero/NUL bytes _are_ written to whatever is connected to `stdout` and can be seen/revealed when needed. It's just the terminal that may chose not to render them visible - but that's also true for other code points as well.

**Comment by thiremani** [comment]
My bad. Fully agree.
