### ISSUE TITLE
when golang new version support ReentrantLock ?

### ISSUE THREAD

**Issue by rfyiamcool** [golang/go#24192]
thank you. Wish go  better and better

**Comment by mvdan** [comment]
Is this a feature request? Are you suggesting that a new type be added to the `sync` package? Why aren't the existing types enough?

Please update the issue with more context and information.

**Comment by mvdan** [comment]
Also, if you're suggesting changing the language or adding new APIs, this should be a proposal: https://github.com/golang/proposal

**Comment by valyala** [comment]
@rfyiamcool, reentrant locks usually mean bad code. See https://stackoverflow.com/a/14671462

**Comment by davecheney** [comment]
I’m going to close this as it is neither a bug report or proposal by our standards.  

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
