### ISSUE TITLE
net/http: connReader.handleReadError doesn't use its error parameter

### ISSUE THREAD

**Issue by mvdan** [golang/go#24201]
This is the case since the func was added in October 2016, as it hasn't been touched since:

```
func (cr *connReader) handleReadError(err error) {
       cr.conn.cancelCtx()
       cr.closeNotify()
}
```

Should the func not receive the parameter, or make use of it?

I found this with a static analysis tool - I don't necessarily think this is a bug. I simply agree with the tool that the code is a bit suspicious.

/cc @bradfitz

**Comment by spf13** [comment]
ping @bradfitz for decision

**Comment by bradfitz** [comment]
@mvdan, @andybons and I were curious which static analysis tool found this, and whether it handles `_ error` okay now.

**Comment by mvdan** [comment]
@bradfitz @andybons it's https://github.com/mvdan/unparam, which should be ok-ish at avoiding false positives. In particular, it does ignore unnamed and underscore parameters. But as always, if you find a bug, please report it :)
