### ISSUE TITLE
math.Uint64  definition produce a compiler error

### ISSUE THREAD

**Issue by JamHamburg** [golang/go#24200]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Not tested yet

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/developer/go/external:/home/developer/go/internal:/home/developer/go/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build273634944=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
I declare a variable
x := math.Uint64 

### What did you expect to see?
I expect the compiler except the line

### What did you see instead?
the compiler comes up with:
Test_PropProtocol/main.go:11:4: constant 18446744073709551615 overflows int

if I switch the defintion for math.Uint64
from  
math.Uint64 = 1<<64 -1
to math.Uint64 = uint64(0xffffffffffffffff)
all work like expected. 
It seems the problem is that 1<<64 could not be calculated  (we have 64 bits, but the result need 65 )

**Comment by ALTree** [comment]
The constants in `math` are untyped constants, so they default to `int`. You can force the type by using

```
var x uint64 = math.MaxUint64
``` 

this will work. 

We already have a proposal that may fix this gotcha for go2: #23087, so I'm closing this issue.
