### ISSUE TITLE
x/vgo: A way to temporary NOT use a specific vendored package

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#24202]
currently I don't see any sane way to work on a vendored package without messing up the git workflow and confusing vscode.

Would it make sense to  add support for using an env variable to allow ignoring a specific vendored package  so that I could test an app using a different/modified dependency package?

I tried few workarounds like using .gitignore , --assume-unchanged etc , but none worked well so far when the vendored pakcages are tracked by git which is the case with all projects I have worked on.
On top of that vscode's  file tree colouring also gets confused.

**Comment by cznic** [comment]
Sounds more like a vscode issue, doesn't it?

**Comment by krasi-georgiev** [comment]
that was only an example, but any IDE will behave the same , the main problem is the git workflow though. 
The general rule is to never manually touch anything in the vendored folder, so the only way to do this and still make changes to a package would be like I suggested.

@cznic what is your git workflow when you make changes to a vendored package? I am happy to try any suggestions.

**Comment by cznic** [comment]
Never ever used vendoring. I have no need for it. Seems like with `vgo` the support for vendoring may get dropped anyway.

**Comment by krasi-georgiev** [comment]
without vendoring ,what happens if the source disappears  or changes names?

**Comment by cznic** [comment]
Nothing. It's on all my machines and in our Gitlab. But generally I try to avoid importing packages that may disappear or break.

**Comment by kardianos** [comment]
vendoring isn't going away as an option most likely: https://groups.google.com/forum/#!topic/golang-dev/FTMScX1fsYk

Are you familiar with the go.mod "replace" directive?
https://research.swtch.com/vgo-tour (under Replacing)

**Comment by krasi-georgiev** [comment]
@karalabe rock star! 
it seems to address exactly what I am describing. I will try it shortly

**Comment by cznic** [comment]
@kardianos Haven't yet read the `vgo` series except for part 1, unfortunately. But I thought I saw rsc expressed the intent to remove vendoring somewhere (reddit? ML discussion)? Not sure IIRC, though.

No difference for me anyway. Haven't used it before and I don't think that's going to change. I still consider vendoring a mistake.

**Comment by rsc** [comment]
Replace is definitely what you are looking for, not modifying vendored copies directly (at least not if you want to preserve the changes; that might be fine for debugging maybe).

**Comment by krasi-georgiev** [comment]
@rsc sorry I didn't understand what you meant by  `Replace is definitely what you are looking for` is this a library or you mean some manual replace script etc?

**Comment by krasi-georgiev** [comment]
I will read the full vgo proposal soon , but wouldn't vgo solve this use case?
