### ISSUE TITLE
cmd/go: build -v outputs nothing while changing the resulting binary

### ISSUE THREAD

**Issue by Luit** [golang/go#24214]
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
Yes (1.10 is latest, to my knowledge)

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOARCH="amd64"
GOOS="linux"

### What did you do?
Comparing Go 1.9 and 1.10 (using Docker), I do the following:
 1. In a folder (`/home/test` in this case) create a `main.go` containing the bare minimum:

        package main
    
        func main() {}

 2. Run `go build`
 3. Create `test.go` containing something visible:

        package main

        import "fmt"

        func init() {
                fmt.Println("test")
        }

4. Run `go build`
5. Remove test.go and run `go build -v`

### What did you expect to see?
I expected the same output as I get from Go 1.9

    root@b549b4931373:/home/test# go version
    go version go1.9.4 linux/amd64
    root@b549b4931373:/home/test# ./test
    test
    root@b549b4931373:/home/test# rm ./test.go
    root@b549b4931373:/home/test# go build -v
    _/home/test
    root@b549b4931373:/home/test# ./test
    root@b549b4931373:/home/test# 

### What did you see instead?
Instead, `go build -v` outputs nothing, but the resulting binary did actually change.

    root@3f5a7744d3ef:/home/test# go version
    go version go1.10 linux/amd64
    root@3f5a7744d3ef:/home/test# ./test
    test
    root@3f5a7744d3ef:/home/test# rm ./test.go
    root@3f5a7744d3ef:/home/test# go build -v
    root@3f5a7744d3ef:/home/test# ./test
    root@3f5a7744d3ef:/home/test# 

I created this test case after `go get -v` showed this behavior for me, so I expect build, install and get to all be affected by this.

**Comment by andybons** [comment]
@rsc

**Comment by ianlancetaylor** [comment]
The `-v` option is documented as printing the package when it is compiled.  In your case, the package is cached.  It is not being recompiled.  The go tool updates the modification time to partially hide the detail that the package was cached.  But  since the package was not recompiled, it is not printed by `-v`.
