### ISSUE TITLE
 cmd/cgo: value inconsistency on s390x when passing an int reference to a C function

### ISSUE THREAD

**Issue by freeekanayaka** [golang/go#24212]
### What version of Go are you using (`go version`)?

```bash
ubuntu@bionic:~$ go version
go version go1.9.4 linux/s390x
```

### Does this issue reproduce with the latest release?

Yes, same with 1.10.

### What operating system and processor architecture are you using (`go env`)?

```bash
ubuntu@bionic:~$ go env
GOARCH="s390x"
GOBIN=""
GOEXE=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_s390x"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build535251359=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```go
package main

/*

int foo(int *pValue) {
  *pValue = 1;
}
*/
import "C"
import "fmt"
import "unsafe"

func main() {
        value := 0
        pValue := (*C.int)(unsafe.Pointer(&value))
        C.foo(pValue)
        fmt.Println(value, *pValue)
```

(unfortunately it seems the Go playground does not support cgo)

### What did you expect to see?

```bash
free@x1:~$ go run foo.go
1 1
```

This is the output on Linux x86_64 (Ubuntu 18.04) .

### What did you see instead?

```
ubuntu@bionic:~$ go run foo.go
4294967296 1
```

This is the output on Linux s390x (Ubuntu 18.04) .

I think the code above respects all rules of cgo, and yet the variable ```value``` gets assigned a different integer than ```*pValue```.

**Comment by ALTree** [comment]
cc @mundaym

**Comment by slrz** [comment]
It's probably just that the size of a Go int is different from a C int. Conversions involving unsafe.Pointer are called that way for a reason.

**Comment by mundaym** [comment]
@slrz is correct. This appears to be a bug in the example code. You don't need to use `unsafe` for this, just allocate `value` as a `C.int` and then use a regular cast to convert it to an `int` if you need to.
