### ISSUE TITLE
x/vgo: hardlink local per project vendor with src/v

### ISSUE THREAD

**Issue by flibustenet** [golang/go#24228]
One little problem with vendoring in each projects is duplicating of the same files on each projects.
`vgo vendor` could have an option to hardlink the files from `$GOPATH/src/v` to project vendor.

edit: it can also help to prune `src/v` when a project is deleted.
We will also see a lot of duplicates files when each version of a package is kept.

**Comment by kardianos** [comment]
@flibustenet There are a few issues with this suggestion:

 1. Hardlinks aren't supported on Windows, which is a first class target.
 2. Part of the point of vgo is that you don't need to keep a vendor directory around.
 3. For those who do want to keep the vendor directory around for dependencies, part of the point is to physically duplicate the data. If you want to save disk space, I'd recommend you use a content addressable file system that automatically de-duplicates files.

**Comment by rsc** [comment]
What @kardianos said is exactly right.
