### ISSUE TITLE
fmt.Scanln/Scanf/Scan executes command if input doesn't match variable type

### ISSUE THREAD

**Issue by LuciferDev** [golang/go#24227]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOOS="darwin", GOARCH="amd64"

### What did you do?
I was trying to get input with fmt.Scan but it is not working

### Recipe to reproduce error

```
 func main() {
	fmt.Print("Enter text: ")
	var input string
	_, err := fmt.Scanln(&input)
	if err != nil{
		panic(err)
	}
	fmt.Print(input)
}
```

If I type _qwerty qwerty_ I get an error from go but I also get a "zsh: command not found: werty" because for some reason Go tries to execute werty

### What did you expect to see?
Not a "zsh: command not found"

### What did you see instead?
A "zsh: command not found"

**Comment by davecheney** [comment]
You haven’t explained how you are running this program or shown that it’s not some zsh quirk. 

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by dominikh** [comment]
This isn't Go trying to execute something, this is fmt.Scanln not consuming the whole input buffer, the process terminating, and your shell reading the rest of it.

You get the same effect with the following program

```
func main() {
	time.Sleep(5 * time.Second)
}
```

where you type something while the program is sleeping. If you don't press enter, you'll even see the input appear in your prompt, unexecuted.
