### ISSUE TITLE
test: locklinear.go constantly failing on arm5 builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#24221]
the `locklinear` test  (previously featured in #19276) is reliably failing on the `linux-arm-arm5spacemonkey` builder since... forever: https://build.golang.org.

I don't know if the test is too strict or the builder is just incapable of running it fast enough, but in any case is not useful to have a builder that always fails on the same test. Maybe the test should just be skipped there.

cc @bradfitz @aclements

**Comment by bradfitz** [comment]
I'd just skip it.

**Comment by rsc** [comment]
Just skip it.

**Comment by mvdan** [comment]
The test is skipped on all arm5 builders now. The builder now seems to be hitting other issues like #24695.

Should we keep this issue open until the builder goes green? Is there an underlying issue to be fixed, or is it not worth the effort to fix this test on the arm5 builder?

**Comment by aclements** [comment]
Since this issue is specific to locklinear and that should be fixed now, we should close this (and track further problems as other issues). Thanks!
