### ISSUE TITLE
x/text/language/display: Inconsistent cases of language names

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#24236]
Please answer these questions before submitting your issue. Thanks!

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Run https://play.golang.org/p/SfrZkuOzAgo

### What did you expect to see?

```
English
Français
Deutsch
Español
Español de España
Español latinoamericano // or, Español Latinoamericano?
```

### What did you see instead?

```
English
français
Deutsch
español
español de España
español latinoamericano
```

I'm not confident each language's rule, but should language names start with upper cases?

There might be other similar languages.

**Comment by spf13** [comment]
ping @mpvl for decision

**Comment by rsc** [comment]
Quoting the [language matching blog post](https://blog.golang.org/matchlang#TOC_4.5.):

> In the second column, note the differences in capitalization, reflecting the rules of the respective language.

So this is working as it should.
