### ISSUE TITLE
Multiple embedded struct fields can cause collisions

### ISSUE THREAD

**Issue by purpleidea** [golang/go#24235]
### What version of Go are you using (`go version`)?
go version go1.9.4 linux/amd64
(should also apply to 1.10.x)

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/james/code/gopath/"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build074257831=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

I've got a struct type `Foo` which I'd like to have fulfill an interface type called `MyThings`. It is composed of methods `A() string`, `B() bool`, `C() int`.

I also have a struct in package `bar` which contains a struct `Base` which implements `B() bool`
I also have a struct in package `baz` which contains a struct `Base` which implements `C() init`.

I'd like to build my struct `Foo` such that it gets the implementations from those two packages and implements the `MyThings` interface. You can usually do this with embedded struct fields. Eg:

```
import (
    "some/package/bar"
    "some/other/package/baz"
)

type Foo struct {
    bar.Base
    baz.Base

    x string
}
func (f Foo) A() string {
    return f.x
}
```

As a result, since the two packages (which might not be under my control) *happen* to name their struct the same thing, then this causes a compile error. I don't expect to need to be able to reference values in either of the two structs, but I would expect this to at least compile and fulfill the type.

You probably can workaround this with a type alias, but that is a hack.

### What did you expect to see?
No compiler error

### What did you see instead?
Compiler error: "duplicate field Base"

**Comment by artyom** [comment]
This works as intended. Embedding implicitly specifies field names, and all non-blank (not `_`) fields in a struct must be unique, irrespective whether they're explicit or implicit (embedding), and your example tries to set two fields named `Base`. Please see the spec on this: https://golang.org/ref/spec#Struct_types which even gives an example on expected behavior:

```
struct {
	T     // conflicts with embedded field *T and *P.T
	*T    // conflicts with embedded field T and *P.T
	*P.T  // conflicts with embedded field T and *T
}
```

**Comment by purpleidea** [comment]
@artyom I understand *why* it's happening, I'm pointing out that due to the way the implementation exists, and the limitation I described, this is a design bug.

**Comment by dotaheor** [comment]
@purpleidea 

```
type Bar = bar.Base
type Baz = baz.Base

type Foo struct {
    Bar
    Baz

    x string
}
```

**Comment by purpleidea** [comment]
@dotaheor Yeah, thanks :)

As mentioned:

> You probably can workaround this with a type alias, but that is a hack.

It's a cool hack though! Also doesn't work with any earlier golang versions.

I'm fortunate in that I first experienced this issue with a library that I write, so I was able to easily rename things, however others might not be able. Thought I'd mention it here as a bug since it felt like a design limitation, and those are fun to think about for future golang versions.

**Comment by dotaheor** [comment]
Beside type alias since 1.9, type definition is also ok for earlier versions.

What's your proposal to fix this "design bug"?

**Comment by purpleidea** [comment]
> What's your proposal to fix this "design bug"?

Good question. It seems to me that an embedded struct field should incorporate the package name (maybe hidden) into it's uniqueness. This is logical since we all know that the types are distinct.

If someone tries to access Foo.Base in a struct method, in a situation where it's ambiguous, then it should be a compile error. In most cases you'd probably be accessing embedded values via the unique function methods that they expose instead.

**Comment by dotaheor** [comment]
It is not bad if the two collided types are non-exported types,
but it is bad for exported types, like the ones in your case.
Even if it is not bad, the effort to support it is not worthy it.
Any bad for the workarounds?

**Comment by dotaheor** [comment]
Looks this case can never happen for non-exported types.
In fact, the best workarounds for this case is to define two non-exported types for the two collided types,
then embed the two non-exported types instead.

**Comment by ianlancetaylor** [comment]
It seems to me that this problem is entirely under your control.  This isn't a case where something is leaking through from some other package.  It just happens that two different packages choose the same name for their type.  You can see that the problem is going to occur when you write the names of the embedded types.  You can rename the type either by using type aliases or by using an intermediate type that embeds one of them.

**Comment by andybons** [comment]
This behavior is working as intended. If you’d like to propose a language change, then please follow the [Proposal process](https://golang.org/s/proposal).
