### ISSUE TITLE
cmd/compile: store combine not working on ppc64 and arm64 with global variables

### ISSUE THREAD

**Issue by rasky** [golang/go#24242]
While migrating the code generation tests for load/store combiners to to the top-level testsuite (fad31e51), I had to disable some tests for arm64 and ppc64le because it looks like that store combining is failing in some situations.

For instance:
https://github.com/golang/go/blob/fad31e513d721a36f2d881d99de54def805a8648/test/codegen/memcombine.go#L132-L137

It looks like the bug is related to the fact that the store is made from a global variable rather than a local variable (as was being previously tested).

**Comment by laboger** [comment]
I noticed this regression in combining little endian stores while testing my current change for combining loads and stores in big endian order on ppc64le. I have a fix that I was going to include with the big endian change, but could make it separate if that is preferred.
