### ISSUE TITLE
Round function seems inconsistant or is it the float64 conversion process?

### ISSUE THREAD

**Issue by JuniorFt** [golang/go#24243]
### What version of Go are you using (`go version`)?
I'm using Go 1.9 on my laptop and reproduce the same behavior on Go 1.10 (playground)

### What operating system and processor architecture are you using (`go env`)?
I'm running OSX High Sierra 10.13.3 on amd64 arch. I mostly run my go binaries in Docker container like [that one](https://hub.docker.com/r/centurylink/ca-certs/)
And I reproduce the behavior on go playground

### What did you do?

I was trying to round the result of some simple calculus using a Rounding function. First, I copy the math.Round() from go 1.10 to Go 1.9 and then tried directly from the math.Round() with Go 1.10.
[Look at it here](https://play.golang.org/p/FFuLBcNsQH7) (sorry I didn't have time to make it cleaner)

### What did you expect to see?
I was expecting to have consistant results when rounding numbers.

### What did you see instead?
I saw that by using the float64 conversion it could led to different result which are not consistant at all. Depending on the input number we can have two different results.

I had a really hard time to find from where this mistake was coming. 
It looks like the floating conversion is doing weird things or maybe I'm not aware enough of its limitation.
If anyone has an explanation I would really like to understand the part I'm missing here.

I couldn't find any issue that looks like that one. Hope it's not a duplicate.

**Comment by bradfitz** [comment]
This looks like it's just a question about math.Round or about how floating point numbers work (not a Go-specific question). Unless there's a concrete, minimized bug report, our standard answer is to suggest you discuss this in one of the forums. (See https://golang.org/wiki/Questions)

**Comment by JuniorFt** [comment]
The bug report is that calling a function with the same conversion logic return 2 different results which is inconsistant. Using math.Round(X.5) could return X or X+1, this is a dangerous behavior which could be damaging.
Sorry if I made it sounds like a question in my original post, it's just that I'm interested in understanding how it could happen.

**Comment by ALTree** [comment]
Go constants are untyped. Computations on constant are done in arbitrary precision. In Go, these:

```
x := float64(319.9/4) * 100.00
y := float64(319.9 / 4 * 100.00)
```

are not the same. Please see:

https://play.golang.org/p/J36LvvmIvEe

This explains why `Round` gives different results.

**Comment by JuniorFt** [comment]
Sorry I didn't spot that earlier.
In my real code I even have something different, need to divide a float64 by an int32.
And it's getting messy with conversion. The only (really dirty) trick I found so far is to convert to float32 to have the correct rounding (because of smaller precision) and cast back to float64 for my need: https://play.golang.org/p/A91MZ1AIxCV

Thanks for your time

**Comment by ALTree** [comment]
No problem. If I'm understanding you last message correctly, you are saying that there is not bug in Go and that we can close this issue. Correct? If no, please comment back and I'll re-open this.
