### ISSUE TITLE
cgo: wrapping a C pointer as uintptr gives "cgo argument has Go pointer to Go pointer" after some time

### ISSUE THREAD

**Issue by jtprobst** [golang/go#24269]
### What version of Go are you using (`go version`)?
`go version go1.10 linux/amd64`
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/home/jprobst/repo/gocode/bin"
GOCACHE="/home/jprobst/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jprobst/repo/gocode"
GORACE=""
GOROOT="/home/jprobst/software/go"
GOTMPDIR=""
GOTOOLDIR="/home/jprobst/software/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build729642085=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
I wrote a program which uses cgo to call a C library. That library exposes a type called `instance` which is actually a C pointer to an opaque struct. In the Go wrapper, this type is stored as `uintptr` such that it does not look like a pointer to the GC which would make it crash otherwise.

The program works in production quite well but very rarely I observe panics saying `cgo argument has Go pointer to Go pointer`. I am aware of the pointer passing rules in cgo and I believe that the program is correct in that regard. The only Go pointer is the `unsafe.Pointer` into which the `uintptr` is wrapped, such that it can be passed into C.

As an attempt to reproduce the behavior, I wrote the program below (unfortunately I cannot paste a link to play because of cgo). It shows the following behavior:
* with GODEBUG=cgocheck=1 (the default), the program panics when x reaches the value `0xc420000000`
* with GODEBUG=cgocheck=2 the behavior is the same as with 1
* with GODEBUG=cgocheck=0 the program finishes normally

The program generates a range `uintptr`s which just so happen to be in the range of where pointers usually are and calls into a trivial C function. If the range is adjusted, for example `0 <= x < 1000000`, the problem does not show.

I am not sure if this is a bug or a feature. However the failure of `cgocheck=2` to detect this situation immediately and the fact that it appears very late in the program made me think that this could be a bug, or unexpected behavior, or a misleading error message by the runtime.

`main.go:`
```go
package main

/*
// Create an opaque type to hide the details of the underlying data structure.
typedef struct instancePrivate* instance;

size_t f(instance x) {
	return (size_t)x;
}
 */
import "C"
import (
	"fmt"
	"unsafe"
)

type Instance uintptr

func (i Instance) get() C.instance {
	return C.instance(unsafe.Pointer(i))
}

func f_wrapper(x Instance) uintptr {
	cy := C.f(x.get())
	return uintptr(cy)
}

func main() {
	var x uintptr
	xPtr := unsafe.Pointer(&x)
	fmt.Printf("%v\n", xPtr)
	for x = uintptr(xPtr) - 1000000; x < uintptr(xPtr)+1000000; x++ {
		fmt.Printf("x: %x\n", x)
		f_wrapper(Instance(x))
	}
}
```
### What did you expect to see?
The program completes with without errors (exit code 0)

### What did you see instead?
```
[74869 lines omitted]
x: c420000000
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
main.f_wrapper.func1(0xc420000000, 0x0)
	/tmp/main.go:24 +0x48
main.f_wrapper(0xc420000000, 0x6)
	/tmp/main.go:24 +0x2b
main.main()
	/tmp/main.go:34 +0x120

Process finished with exit code 2
```

**Comment by bcmills** [comment]
The conversion to `unsafe.Pointer` in the call to `C.instance(unsafe.Pointer(i))` is not valid.

Per http://go/godoc/unsafe/#Pointer:
“Conversion of a uintptr back to Pointer is not valid in general.”
“Conversion of a Pointer to a uintptr and back[:] […] [n]ote that both conversions must appear in the same expression, with only the intervening arithmetic between them.”

Instead, do the conversion inside the preamble function:

```go
/*
…
#include <stdint.h>

static uintptr_t f_wrapper(x uintptr_t) {
	return f((instance)x);
}
*/
import "C"

…

type Instance uintptr

func f_wrapper(x Instance) uintptr {
	cy := C.f(C.uintptr_t(x))
	return uintptr(cy)
}

func main() {
	…
	for … {
		f_wrapper(Instance(x))
	}
}
```

**Comment by ianlancetaylor** [comment]
Not a cgo problem, not a problem we can fix in the Go toolchain.  Closing.
