### ISSUE TITLE
question: Two problems: Confusing Prompt -- unable to parse output of git config remote.origin.url

### ISSUE THREAD

**Issue by Justsoos** [golang/go#24277]
#What version of Go are you using (`go version`)?
```
go version go1.10 windows/amd64
git version 2.16.1.windows.4
```

- **first problem: confused prompt of go get **

`$go get -u github.com/sth`
if you've already run this command and downloaded the directory here:  `$GOPATH\github.com\sth`, then you must get such prompt with re-run this command:
`package github.com/sth unable to parse output of git config remote.origin.url
`
it is a very confusing prompt for beginner with golang. 
https://github.com/golang/go/issues/11457 

- **second problem: **

if I modify some go source file, like `$GOPATH\github.com\sth\hello\b.go` which is depended by main.go, and then re-build the main.go at `$GOPATH\github.com\sth\hello\main.go`, I have to keep watch on `$GOPATH\pkg\windows_amd64\github.com\sth\hello\b.a`, once I change the b.go and want to rebuild changes into main hello.exe I have to delete b.a first, if not so, no change to final rebuild exe. is it a nice way to taste golang? or just come after github project?

or with `go build -a` , it costs too long time and no need. what is the right way?

**Comment by bradfitz** [comment]
> package github.com/sth unable to parse output of git config remote.origin.url

What is your git config?

> if I modify some go source file, like $GOPATH\github.com\sth\hello\b.go which is depended by main.go, and then re-build the main.go at $GOPATH\github.com\sth\hello\main.go, I have to keep watch on $GOPATH\pkg\windows_amd64\github.com\sth\hello\b.a, once I change the b.go and want to rebuild changes into main hello.exe I have to delete b.a first, if not so, no change to final rebuild exe. is it a nice way to taste golang? or just come after github project?

That is not true, especially with Go 1.10. You don't need to manually manage your `*.a` files.

Why do you think that's necessary?

**Comment by Justsoos** [comment]
thx for reply, first, my .gitconfig file:
 ```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	required = true
[user]
	name = Justsoos
[user]
	email = Email
```

and second, I tried with `go build -x` to rebuild and watch , found all is in right way, the bad build experience above might cause by LiteIDE X33.2 qt5.

**Comment by ianlancetaylor** [comment]
I don't see anything to fix here.  For questions about using Go, please see https://golang.org/wiki/Questions.

**Comment by Justsoos** [comment]
added:
no with go, can not apply "-u", like:
```
go get -v -x -u github.com/iawia002/annie
cd E:\Users\Jerry\go\src\github.com\iawia002\annie
git config remote.origin.url
https://github.com/iawia002/annie
package github.com/iawia002/annie: unable to parse output of git config remote.origin.url
```
or do to some private repos, like:
```
go get -v -x -u v2ray.com/core/...
cd E:\Users\Jerry\go\src\v2ray.com\core
git config remote.origin.url
https://github.com/v2ray/v2ray-core
package v2ray.com/core: unable to parse output of git config remote.origin.url
cd E:\Users\Jerry\go\src\v2ray.com\core
git config remote.origin.url
https://github.com/v2ray/v2ray-core
package v2ray.com/core/app: unable to parse output of git config remote.origin.url
.......
```
all shows error result: **unable to parse output of git config remote.origin.url**， but works without "-u" option.
is it a bug of golang with Windows10?

**Comment by Justsoos** [comment]
add info:
I found "go get [without -u]" did not update repos, such as "git pull", I have to run "git pull" under "$gopath\src\REPOS" directory first, and then run "go get REPOS" to build the latest code.

**Comment by Justsoos** [comment]
update, git config:
after "go get -v -u -x github.com/iawia002/annie"
```
git config -l
core.symlinks=true
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=c:/tools/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=c:/tools/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
user.name=xxxx
user.email=xxxx
https.proxy='https://127.0.0.1:1080'
http.proxy='http://127.0.0.1:1080'
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=https://github.com/iawia002/annie
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```
