### ISSUE TITLE
x/tools/cmd/guru: change package referrers to show imports rather than qualified identifiers

### ISSUE THREAD

**Issue by josharian** [golang/go#24275]
cmd/guru's packageReferrers contains this [TODO](https://github.com/golang/tools/blob/059bec968c61383b574810040ba9410712de36c5/cmd/guru/referrers.go#L166):

```
			// TODO(adonovan): perhaps more useful would be to show imports
			// of the package instead of qualified identifiers.
```

This seems more useful, because there'd be fewer results, which means the user is less likely to drown in them. It also admits of a dramatically cheaper implementation, because it could be done entirely via go/parser, with parser.ImportsOnly.

@alandonovan how do you feel about pulling the trigger on this?

cc @keegancsmith -- see https://github.com/sourcegraph/go-langserver/blob/feba79e88e9cca61e450f5c15d2c01d597e2d46c/langserver/references.go#L59

**Comment by spf13** [comment]
ping @alandonovan for decision

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete. Incidentally, gopls gets this right.
