### ISSUE TITLE
C++ memory leak only when bound to go

### ISSUE THREAD

**Issue by sjiekak** [golang/go#24271]
### What version of Go are you using (`go version`)?
go1.9.3

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
I'm using Ubuntu 17.10 amd64

### What did you do?

I am using the popular [nlohmann](https://github.com/nlohmann/json) library in my c++ engine, which is wrapped using cgo. I noticed what looked like a memory leak, as the memory was ever increasing.
Valgrind did not detect any leak. Actually running the program with valgrind changed the behavior : The memory eventually converge

### What did you expect to see?
A constant memory usage

### What did you see instead?
A ever increasing memory usage

The following package contains a dockerfile, which once build and run, will consume more and more memory.
[goparsecpp.tar.gz](https://github.com/golang/go/files/1786099/goparsecpp.tar.gz)

How can the following snippet "leak" memory ?

parse.cpp
```
#include "parse.hpp"
#include "json.hpp" // master single file of nlohmann json

extern "C" void parse(char* value)
{
    try
    {
        nlohmann::json::parse(value);
    }
    catch (std::exception&)
    {}
}
```

leaker.go
```
package main

import (
	"unsafe"
)

// #include <stdlib.h>
// #include "parse.hpp"
// #cgo LDFLAGS: -lparse -lstdc++
import "C"

func main() {
	input := "{\"hello\": \"world\"}";
	for ;; {
		cinput := C.CString(input);
		defer C.free(unsafe.Pointer(cinput))
		C.parse(cinput)
	}
}


```

**Comment by randall77** [comment]
Those `defer`s will never run.  They are queued up until `main` exits, and `main` never exits.
