### ISSUE TITLE
Pass by value in struct not yielding expected result

### ISSUE THREAD

**Issue by bharathramh92** [golang/go#24276]
Please answer these questions before submitting your issue. Thanks!

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
However, this happens in play.golang.org env as well.

### What did you do? Software engineer

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/v6u7R_nbGRp

In the example, if the struct (`Document`) is not initialized at first, there is no place holder for future values pointing to same object. Is this intended?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.
