### ISSUE TITLE
x/build/DIR:kubernetes not compatible with go1.6

### ISSUE THREAD

**Issue by nolanmar511** [golang/go#24280]
I noticed in [kubernetes/dialer.go](https://github.com/golang/build/blob/master/kubernetes/dialer.go#L8) the package "context" is used, but in other locations (for example [here](https://github.com/golang/build/blob/master/kubernetes/client.go#L23)) "golang.org/x/net/context" is used. I think this is keeping the kubernetes package from working with go1.6 -- just wanted to check if this was intentional.

### What version of Go are you using (`go version`)?
go1.6

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
go get golang.org/x/build/kubernetes

### What did you expect to see?
No output, package should be retrieved.

### What did you see instead?
Saw output:
package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by adamdecaf** [comment]
Go 1.7 added the `context` yep, so that would be the minimum version required to compile that code.

The [go release policy](https://golang.org/doc/devel/release.html#policy) also mentions that right now only Go 1.9 and 1.10 are supported.

**Comment by andybons** [comment]
@adamdecaf is correct. We don’t support 1.6 anymore and users should migrate imports of `golang.org/x/net/context` to `context` where they can.
