### ISSUE TITLE
gofmt - struct blank lines,  spaces - replace by tabulation

### ISSUE THREAD

**Issue by code34** [golang/go#24281]
Hello 

There is 2 major issues with GOFMT that doesn't produce the result expected with -s flag.

### What version of Go are you using (`go version`)?
go 1.10

### Does this issue reproduce with the latest release?
yes and olders

### What operating system and processor architecture are you using (`go env`)?
windows

### What did you do?

use this struct declaration as test with 

type TestEvent struct {
	Time time.Time // encodes as an RFC3339-format string

	Action string

	Package string
	Test    string

	Elapsed float64 // seconds

	Output string
}

### What did you expect to see?

gofmt should delete the blank line and  add or delete space characters between Time and time.Time  to equivalent numbers to align them with other declarations.

Anyway, gofmt should replace the space characters by tabulation. Space characters are not used anymore in modern text editor to align declaration. The alignement works only on console mode.

### What did you see instead?

replace space character by tabulation.
delete useless blank line

**Comment by andybons** [comment]
Sorry, gofmt is not soliciting change requests on its format at this time. Gofmt made a set of choices at one point, and everybody agrees to live with them, even if everybody might take issue with different individual choices. (as Rob says: https://www.youtube.com/watch?v=PAAkCSZUG1c&t=8m43s) For Go 2, @griesemer may trawl through the issue tracker for all old gofmt style request bugs.

**Comment by code34** [comment]
I do not understand why the basic tools would not be maintained and corrected when necessary.

i'm not agree with that but do i have the choice ?

**Comment by griesemer** [comment]
@code34 We are absolutely trying our best to maintain the basic tools. That said, what you are describing is not a "bug" but a disagreement with the formatting. Plenty of people (including ourselves) have disagreements with the way gofmt formats certain things. If we'd change it all the time we'd get a lot of needless churn; while in the big picture it doesn't matter. There will be a future gofmt that will be better. And then it's trivial to just run all the code through it and be done with it. But that time is not now. There's simply more important things to worry about. Thanks.
