### ISSUE TITLE
io: Close and CloseWithError overwrite the error stored in a pipe

### ISSUE THREAD

**Issue by jbardin** [golang/go#24283]
Calling `Close` after `CloseWithError` (or `CloseWithError` multiple times) overwrites the stored error in `io.pipe`. 

Opening an issue for discussion first, since there is test coverage verifying this behavior, though it seems to only be there to check the `atomic.Value`, and it does subtly change the API. 

Since pipes are often used concurrently, and multiple calls to `Close` _usually_ have no effect, users would often expect the following code to be deterministic:

	pr, pw := io.Pipe()        
	go func() {
		defer pw.Close()
		_, err := io.Copy(pw, reader)
		if err != nil {
			pw.CloseWithError(err)
		}
		// more code
	}()

But in this case, if there is an error and the `PipeReader` executes `Read` immediately after `CloseWithError` it will get the stored error from the `Copy`, but once `defer pw.Close` executes the error is set back to `EOF`. 

Moving the error assignment into the `pipe.once` would make the above work, ~and probably also allow the removal of the `sync.Value` fields, since the errors are protected by the done chan and the `sync.Once`.~

**Comment by dsnet** [comment]
I'm fairly certain that this change will break many people. However, I do agree the proposed semantics is probably preferred. In generally, the first encountered error is more accurate than some later error. For example, [`errgroup`](https://godoc.org/golang.org/x/sync/errgroup) stores the first error, not the most recent error.

> probably also allow the removal of the `sync.Value` fields.

The `readCloseError` and `writeCloseError` methods have to read the other side's error value. The `sync.Once` provides synchronization for your own side, but provides no protection for the other side, so some form of race-safety is still needed.

**Comment by jbardin** [comment]
Hi @dsnet,

My hunch was that _most_ code which is hitting this case is probably unknowingly broken, and this is in effect fixing it. I guess we need to decide whether this would be considered a bug or not. 

Thanks, looking more closely I see that concurrent Read or Write calls still need mutual exclusion around the values, but that doesn't really matter much for the discussion of the error semantics.

**Comment by ianlancetaylor** [comment]
I would like to understand why we can't just change the code today.  Calling `Close` twice is an error.  I don't see why the second call to `Close` should modify the error stored by the first call.

**Comment by dsnet** [comment]
I can run a regression test to see measure the impact of this change.

**Comment by rsc** [comment]
Only the first Close should have any effect. Anything else is a bug.
