### ISSUE TITLE
runtime: heapdump16 and heapdump17 are missing

### ISSUE THREAD

**Issue by jeffallen** [golang/go#24295]
### What version of Go are you using (`go version`)?

1.10

### What did you do?

Trying to decode heap dumps. The godoc leads me to https://github.com/golang/go/wiki/heapdump15
, but heap dump version 1.6 and 1.7 exist as well:

1. 1.7: https://github.com/golang/go/commit/30f93f09944c54147bec9e5c39631f17addd94c7
1. 1.6: https://github.com/golang/go/commit/cedbbfaa45fac82a0088b3163c7137e814020a53 (but the code review in https://go-review.googlesource.com/c/go/+/18912 seems to indicate there was no actual change?)

It would be helpful to have the specification for heapdump16 and heapdump17 in the wiki.

**Comment by randall77** [comment]
1.5->1.6 had no changes other than the header.
1.6->1.7 has one very minor change to how to tell whether an interface is direct.

I'll update the wiki.

**Comment by randall77** [comment]
Done.
Let me know if my changes are clear.

**Comment by odeke-em** [comment]
For posterity, the new link is: https://github.com/golang/go/wiki/heapdump15-through-heapdump17
