### ISSUE TITLE
can we call c function pointer in CGO?

### ISSUE THREAD

**Issue by huangzhiran** [golang/go#24291]
GO version 1.8

```
typedef struct test {
    int c;
    int (*add)(int a, int b);
} test;

func main() {
	ctest := C.test{}
	C.init_test(&ctest)

	// can we call c function pointer in CGO? something like this ?
	a := ctest.add(C.int(1), C.int(1))

	fmt.Println(a)
}
```

**Comment by AlexRouSg** [comment]
The issue tracker is not normally used for questions so please ask in the proper place next time. https://github.com/golang/go/wiki/Questions

But to answer your question, no you cannot call a C function pointer in Go. You need to pass the C function pointer into a C function which then calls the function pointer. This is explained in https://golang.org/cmd/cgo

```
package main

// typedef int (*intFunc) ();
//
// int
// bridge_int_func(intFunc f)
// {
//		return f();
// }
//
// int fortytwo()
// {
//	    return 42;
// }
import "C"
import "fmt"

func main() {
	f := C.intFunc(C.fortytwo)
	fmt.Println(int(C.bridge_int_func(f)))
	// Output: 42
}
```

**Comment by ianlancetaylor** [comment]
There is nothing to fix here, so closing.
