### ISSUE TITLE
testing: report allocations in the BenchmarkResult struct Stringer

### ISSUE THREAD

**Issue by titpetric** [golang/go#24296]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Not applicable

### What did you do?

Call `testing.Benchmark` when using `b.ReportAllocs()` in the benchmark function.

### What did you expect to see?

```
New  1000000          1232 ns/op        0 B/op         0 allocs/op
A.New  1000000        1169 ns/op        0 B/op         0 allocs/op
```

### What did you see instead?

```
New  1000000          1171 ns/op
A.New  1000000        1115 ns/op
```

**Comment by davecheney** [comment]
This is not the expected behaviour. Can you please provide the code sample that produced the output above.

**Comment by titpetric** [comment]
Sure, here is the [playground link](https://play.golang.org/p/xKnapThDcui), crippled a bit to give you some output (ie, doesn't use `b.N`).

The sources for the `func (r BenchmarkResult) String() string` [here](https://golang.org/src/testing/benchmark.go?s=9060:9100#L324) basically don't give a call to `r.MemString()`, or have access to `B.showAllocResult`, because the `*B` or `showAllocResult` isn't copied into the struct.

**Comment by davecheney** [comment]
Can you demonstrate this failure with a normal _test.go test? You don't
need to use the playground.

**Comment by davecheney** [comment]
Sorry, ignore my last request. This isn't a bug, this is a feature request.

**Comment by titpetric** [comment]
Yes, feature request. It's an inconvenience with a work-around. Thanks for taking the time to understand it however :)

**Comment by andybons** [comment]
> Yes, feature request. It's an inconvenience with a work-around.

Can you outline what your workaround is? I’m having trouble seeing it :)

**Comment by titpetric** [comment]
@andybons it's `fmt.Println(result, result.MemString())` instead of just `fmt.Println(result)`.

**Comment by ianlancetaylor** [comment]
I don't think we should always print the memory results, and I don't think we should add a new field to `BenchmarkResult`, a struct that currently has only exported fields.  It's already possible to call `MemString`; adding the results to `String` would be a minor convenience in a few cases.  So all in all I don't think this is worth doing.  Sorry.
