### ISSUE TITLE
proposal: cmd/go: support CC_FOR_*

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#24294]
I'm working on generating standalone gomobile bindings, allowing you to first generate and then use regular go commands to build. For example, this works with my local version of gomobile:

````
$ gobind -outdir $GOPATH golang.org/x/mobile/example/bind/hello
$ GOOS=android GOARCH=arm64 CC=<ndk-arm64-dir>/bin/clang go build -buildmode=c-shared gomobile
````

Note that CC (and CXX) is GOARCH specific, so to build for all 4 android GOARCHs, a user have to go:

````
$ GOOS=android GOARCH=arm CC=<ndk-arm-dir>/bin/clang go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=arm64 CC=<ndk-arm64-dir>/bin/clang go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=386 CC=<ndk-386-dir>/bin/clang go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=amd64 CC=<ndk-amd64-dir>/bin/clang go build -buildmode=c-shared -o ... gomobile
````

It would be nice if the go command supported the CC_FOR_* environment variables like make.bash does, so the user could set  CC_FOR_android_arm, CC_FOR_android_arm64, CC_FOR_android_amd64 and CC_FOR_android_386 once and reduce the build to the much nicer:

 ````
$ GOOS=android GOARCH=arm go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=arm64 go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=386 go build -buildmode=c-shared -o ... gomobile
$ GOOS=android GOARCH=amd64 go build -buildmode=c-shared -o ... gomobile
````

I suppose for completeness, the go command has to support CC_FOR_TARGET and CXX_FOR_TARGET as well.

**Comment by ianlancetaylor** [comment]
To really work in the ecosystem, the whole set of environment variables would have to be reported by `go env`, whose output is already rather long.  It's sufficiently simple to write a shell script, or tiny Go program, or Makefile, that it doesn't seem necessary to add this to cmd/go itself.

Decision: we aren't going to add this.
