### ISSUE TITLE
access: go-approvers

### ISSUE THREAD

**Issue by iand** [golang/go#24292]
I'd like to help out with issue gardening would like to request access to the go-approvers team https://github.com/orgs/golang/teams/go-approvers 

See https://golang.org/wiki/GithubAccess

**Comment by ALTree** [comment]
It's not up to me and I hope this won't come out as me trying to be a gatekeeper, but please note that the wiki says

> If you've been regularly active in the Go community for some time

There are only [a dozen comments](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aiand) from you in the issue tracker and just one in the last 6 months. People are usually given gardening access after they've been visibly and regularly active in the tracker for some time.

Anyway cc @broady @bradfitz for a decision.

**Comment by andybons** [comment]
Hi @iand,
As you haven’t been very active recently we ask that you keep up with community work and we can revisit once you’ve had a more solid record of contributions.

Thanks
