### ISSUE TITLE
cmd/compile: reject -race and -msan on non-amd64 arches

### ISSUE THREAD

**Issue by mdempsky** [golang/go#24315]
cmd/compile currently allows using the -race and -msan flags on any architecture, but there's only runtime support on amd64. Further, -race support wouldn't current work on LR architectures even with runtime support, because racewalk.go hardcodes assumptions about where to find the caller's PC.

Another complication is there are a handful of regress tests that explicitly set `-race`. A recent refactoring (CL 99416) caused these tests to break, because I assumed no one would be using `-race` on an unsupported platform.

For comparison, the -dynlink and -shared flags are only usable on platforms where they're supported.

My personal preference would be to make setting -race or -msan an error on !amd64 arches.

@cherrymui suggested CL 99676 to make -race a silent no-op on !amd64.

/cc @aclements @ianlancetaylor

**Comment by cherrymui** [comment]
I agree with @mdempsky that we probably should reject it on non-supporting platforms.

I made CL https://golang.org/cl/99677 to let run.go not passing -race to non-AMD64.

**Comment by ianlancetaylor** [comment]
@mdempsky You wrote "My personal preference would be to make setting -race or -msan on a !amd64 arch."  Do you mean make it an error?

**Comment by mdempsky** [comment]
@ianlancetaylor Thanks for pointing that out. Yes, I meant making it an error. (Edited comment to fix that.)
