### ISSUE TITLE
x/vgo: lookup/fetch dependencies concurrently

### ISSUE THREAD

**Issue by awly** [golang/go#24316]
Ran vgo build for program that imports a large dependency tree (imports k8s.io/kubernetes/something).

It worked for several minutes, printing lines like this at a steady pace:
vgo: finding github.com/kr/pretty v0.0.0-20140723054909-088c856450c0

It looks like vgo works through list dependencies sequentially (recursively appending additional ones as they are discovered). Perhaps this could be parallellized?

**Comment by AlexRouSg** [comment]
How would you propose it process dependencies in parallel?   

If A depends on B and C 1.2 and B depends on C 1.4
There is no way to know to use C 1.4 until it got to B and it won't know to use B until it got to A. 

/cc @rsc

**Comment by awly** [comment]
For example A depends on B, C, D, E, F, G. D and F depend on X 1.1 and X
1.5 respectively.
Use worker pool of size 3. All "finalized" versions are kept in some
synchronized structure (or map)
- process A.
- process B, C, D, add X 1.1 to queue
- process E, F, G, add X 1.5 to queue
- process X 1.1, X1.5
    - if 1.1 gets the lock first, 1.5 overrides the picked version after
    - if 1.5 gets the lock first, 1.1 is ignored
If you have "blacklisted" versions, those are recorded in the store and get
handled if the dependency comes up again.

In my experience, many packages have >>2 dependencies and the transient
dependencies don't overlap too often.
Of course, that's from a limited sample size.

The implementation would certainly have more edge cases than serial
approach.
But so far I don't think it's too complex and would benefit some larger
projects.

**Comment by awly** [comment]
Hmm, got an email about someone commenting but perhaps they deleted the comment.
Anyway, the above description still stands.

**Comment by AlexRouSg** [comment]
Sorry about deleting it, shortly after posting I realized roughly the same thing you posted.

Also based on https://research.swtch.com/vgo-module
It defines a url to get the go.mod file
`GET baseURL/module/@v/version.mod fetches the go.mod file for that version.`

So maybe it could (not sure if it does already) just get all the mod files and build the dependency tree and then fetch all the source files completely in parallel. But yeah this wouldn't work with legacy packages so it have to revert to getting the entire package to figure out the dependency tree.

**Comment by ALTree** [comment]
Same request but for `go get` for reference: #11821.

**Comment by rsc** [comment]
Once we are happy with the rest of the code, yes, we should parallelize it. But I want to figure out what the code should do and make it correct before we make it fast.

**Comment by rsc** [comment]
Brad asked me to kill uses of NeedsFixButNotYet, so I'm going to call this NeedsInvestigation.
