### ISSUE TITLE
x/playground: support examples as tests

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#24311]
In continuation of #6511, I would like to address supporting examples as tests. Examples should be run as tests if they have a proper name and an output specified in the comment section: https://golang.org/pkg/testing/#hdr-Examples 

I have a CL almost ready. Before that I would like to address one question.

My CL has a flaw which I am not sure what to do with. If some user submits a program with example and does not import "testing" package in the code then playground does it for him. Problem arises when there is some error in the code and the error highlighter points to wrong line. It happens because we have added "testing" import and then applied format.Source(). Thus sources got transformed and the playground highlights wrong line. 

![screen shot 2018-03-08 at 17 34 09](https://user-images.githubusercontent.com/140245/37159634-0a82842c-22f7-11e8-8c50-14e1fe8b4173.png)

Should I fix this before posting a CL?

**Comment by andybons** [comment]
Yes I think you should fix this before proceeding with your other CL.

**Comment by ysmolsky** [comment]
Thanks, I have fixed that and the CL is ready for your review.

**Comment by ysmolsky** [comment]
@andybons, if you got some time please review https://golang.org/cl/99595. Thanks!
