### ISSUE TITLE
tour: wrong translation on https://go-tour-ita.appspot.com/concurrency/10

### ISSUE THREAD

**Issue by comio** [golang/go#24320]
Contesto: https://go-tour-ita.appspot.com/concurrency/10

Italian translation is wrong:

>WRONG: Modifica la funzione Crawl function **to** recuperare **dei** URL in parallelo senza recuperare lo stesso URL due volte. 

>CORRECT: Modifica la funzione Crawl function **per** recuperare **degli** URL in parallelo senza recuperare lo stesso URL due volte.

**Comment by ALTree** [comment]
"funzione Crawl function" è anche ridondante, "function" andrebbe probabilmente eliminato.

Anyway we don't maintain, control or deploy the tour translations. You should find out where the tour-ita maintainer keeps the repository (I couldn't find it) and report the issue there.
