### ISSUE TITLE
cmd/compile: illegal ARM64 assembly generated

### ISSUE THREAD

**Issue by benshi001** [golang/go#24333]
The following code

	func iri(a *[30]byte) {
        	*a = [30]byte{}
	}

is compiled to

	    00000 (3)       TEXT    "".iri(SB)
	    00001 (3)       FUNCDATA        $0, gclocals·a36216b97439c93dafebe03e7f0808b5(SB)
	    00002 (3)       FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	v10 00003 (3)       MOVD    " " .a(RSP), R0
	v3  00004 (4)       STP     (ZR, ZR), (R0)
	v7  00005 (4)       STP     (ZR, ZR), 14(R0)
	b1  00006 (5)       RET
	    00007 (?)       END

But the STP instruction only accepts an 8-aligned offset in range -512 <-> 504.

**Comment by ALTree** [comment]
Which Go versions are affected? Just tip? Tip and 1.10? 

When you report bad codegen issues please always include details about the Go versions that you believe are affected. If it's just tip is one thing, if a released version is affected then the issue may require a minor release to fix it.

**Comment by benshi001** [comment]
Sorry, it is my mistake, the "STP     (ZR, ZR), 14(R0)" is expanded to

	a.go:5                0x86818                 9100381b                ADD $14, R0, R27
	a.go:5                0x8681c                 a9007f7f                STP (ZR, ZR), (R27)

Which are legal.
