### ISSUE TITLE
cmd/compile: incorrect column reported for invalid struct field names

### ISSUE THREAD

**Issue by dhowden** [golang/go#24339]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOOS="darwin"
```

### What did you do?

Tried to compile this (incorrect code):

```go
package main

type Struct struct {}

func main() {
	x := Struct{
		InvalidName: 10,
	}
}
```

### What did you expect to see?
```
prog.go:7:3: unknown field 'InvalidName' in struct literal of type Struct
```
```go
	x := Struct{
		InvalidName: 10,
//		^
	}
```

### What did you see instead?
```
prog.go:7:14: unknown field 'InvalidName' in struct literal of type Struct
```
```go
	x := Struct{
		InvalidName: 10,
//		           ^
	}
```

Go Playground: https://play.golang.org/p/-UT1IgmXgQD

**Comment by mvdan** [comment]
This does not concern go/parser; rather, this is the compiler. The error comes from `gc`, and the position from `syntax`.

I also believe that this is working as intended, as the position of the key-value expression is the position of the colon token. There was an issue where @mdempsky suggested that, in the new syntax package, node positions shouldn't always be their start position. For example, in `x + y`, the position of the binary arithmetic expression should be the `+`. However, I can't seem to find that issue right now.

Having said that, I can understand that the error concerns the field name, not the entire key-value expression. Perhaps the error in this case should use the position for the field, and not the entire key-value expression.

Also cc @griesemer.

**Comment by mvdan** [comment]
Found the issue now; it's #16943.

**Comment by griesemer** [comment]
Package syntax provides all the relevant positions here. It's just a matter of using the right one. Will fix.
