### ISSUE TITLE
net/http: make Request.Form.Get call ParseForm automatically

### ISSUE THREAD

**Issue by Trion129** [golang/go#24338]
`req.ParseForm()` is needed to be called before accessing the form parameters using `param := req.Form.Get("param-name")` where req is a http.Request

Is there a reason behind this? 
I would like to add a feature to ParseForm automatically from Form.Get() on first execution and on next calls, check if Form is already parsed and work as usual.
What are your thoughts?

**Comment by mvdan** [comment]
How exactly would this work? `r.Form` is of type `url.Values`, so it can't possibly make a call back to `http.Request` - that would mean an import cycle.

**Comment by pciet** [comment]
This functionality is already implemented in one way as ```r.FormValue``` but the parse error is ignored and multiple values for a key isn't handled (POST/PUT body parameters take precedence over URL query values, and the first value is picked).

```
// Go 2 improvement?
func (r *Request) FormValue(key string) ([]string, error)
```

**Comment by Trion129** [comment]
Ah, I didn't know about `r.FormValue` 😋 That is indeed what I need! Most of form tutorials were using Parse and then Form.Get, so I thought maybe it doesn't exist.
What about an alias `GetFormValue`? because first time I tried to find the function in my IDE, I typed `req.Get` in hopes something like this will show up.

**Comment by mvdan** [comment]
Go2 changes are already being tracked in another issue, so I'm going to close this one.

Exposing the same method under two names is a bad idea in my opinion; especially since Go tends to not like getters: https://golang.org/doc/effective_go.html#Getters
