### ISSUE TITLE
cmd/test: false error reported

### ISSUE THREAD

**Issue by dotaheor** [golang/go#24342]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
// abc_test.go
package main

import (
	"fmt"
	"testing"
)

func Benchmark_SliceComparison(b *testing.B) {
    benchmarks := []func (a, b []int) bool {
    	nil,
    }
    
    for _, f := range benchmarks {
    	_ = fmt.Sprintf("%v", f) // Sprintf format %v arg f is a func value, not called
    }
}
```

```
go test -bench=.
```

### What did you expect to see?

No error reported.

### What did you see instead?

```
./abc_test.go:14: Sprintf format %v arg f is a func value, not called
```

If I put the code in a non-test file and use `go run` to run it, no errors are reported.

**Comment by dotaheor** [comment]
A simpler one:
```
package main

import (
	"fmt"
	"testing"
)

func Benchmark_SliceComparison(b *testing.B) {
	var f func (a, b []int) bool
	fmt.Printf("%v", f) // Sprintf format %v arg f is a func value, not called
}
```

**Comment by mvdan** [comment]
The warning seems correct to me; if what you're after is printing the pointer to the function, you should instead use `%p`. Unless I misread the fmt docs and `%v` on funcs is documented and supported.

**Comment by dotaheor** [comment]
But the error is only reported in for `go test`, not for `go run`.

**Comment by mvdan** [comment]
Yes; that is because since Go 1.10, test also runs vet by default. You can see the same warning via `go vet`.

**Comment by dotaheor** [comment]
But will `go vet' warnings prevent a benchmark running?
If yes, please close this issue.

**Comment by mvdan** [comment]
You can still skip vet via `go test -vet off`, I believe. For more information, see the Go 1.10 release notes.
