### ISSUE TITLE
[General] Can golang ever become something like C# / Java

### ISSUE THREAD

**Issue by rebootcode** [golang/go#24340]
I was just asking if golang can be seen any where near to become as powerful as C# or Java.

One programming language that can be used in 

- "Network programming with the best performance"
- "Web app programming with competitive performance"
- "Desktop app programming with competitive performance"
**IMPORTANTLY**
- "Mobile app programming"

**Network programming and Mobile app programming is very very crucial section for most of the people.**

**Comment by XenoAmess** [comment]
not so easy..java has jvm,c sharp has mono.as for go,he only have his compiler..

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
