### ISSUE TITLE
x/build: select newest build first (for at least iOS)

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#24348]
The darwin/arm and darwin/arm64 builds are very slow and currently only run one at a time for stability. Most of the time, at least in the weekdays when the Go tree is open, the builds don't catch up to the latest commit. That means that detection of potential build breakage will show up later than necessary. I wonder if it would be possible (and desirable) to always select the latest git revision when starting a build. At least for the very slow iOS builder. Today the builder will often select a build that is not even on the first page of build.golang.org.

**Comment by bradfitz** [comment]
Totally agreed, but dup of #19178.
