### ISSUE TITLE
x/mobile: No type or protocol named 'goSeqRefInterface'

### ISSUE THREAD

**Issue by alvatar** [golang/go#24343]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alvatar/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alvatar/go/"
GORACE=""
GOROOT="/Users/alvatar/go/go1.10"
GOTMPDIR=""
GOTOOLDIR="/Users/alvatar/go/go1.10/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mf/9y9xgfm910lg169q75sp1f5w0000gn/T/go-build610131228=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

Generate Go bindings with `gomobile bind -target ios <package>`, then import it, configure it, and call any of the Go functions from ObjC

### What did you expect to see?
A correct build

### What did you see instead?
Universe.objc.h:22:37: No type or protocol named 'goSeqRefInterface'

The solution was to include
`#include "ref.h"`
in Universe.objc.h, so I suppose the fix is just to add this to the code generator?

**Comment by eliasnaur** [comment]
Can you provide more specific steps to reproduce the problem? On my setup (mac mini, macOS 10.13, Xcode 9.2), this works and produces a Hello.framework:

````
$ go get -u golang.org/x/mobile/cmd/... && gomobile bind -target=ios golang.org/x/mobile/example/bind/hello
````

**Comment by alvatar** [comment]
Thanks @eliasnaur .
The generation works well, but just importing (in your case “Headers/Hello.h”) won’t be enough, you need to import ref.h too. This is minor, but I suspect it should be imported in Universe.objc.h instead, and be done already by the generated code.

**Comment by eliasnaur** [comment]
Are you importing with the module form: @import Hello? In any case, with current gomobile, replacing @import Hello with #include "Hello/Hello.h" in the golang.org/x/mobile/example/bind/hello project still works for me.

**Comment by alvatar** [comment]
I was importing with `#include ...`. That fails for me.
However, replacing that with the `@import` form fixes it without the need to manually include "ref.h".
Sorry, I'm actually pretty new to ObjC.
Thank you @eliasnaur !

**Comment by eliasnaur** [comment]
Please open a new issue with steps to reproduce the error. Thanks.
