### ISSUE TITLE
fmt: issues related to EUC-KR encoding string scanf

### ISSUE THREAD

**Issue by newro** [golang/go#24353]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
I didn't check it.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/newro/app/go"
GORACE=""
GOROOT="/home/newro/go1.9.1"
GOTOOLDIR="/home/newro/go1.9.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build985492979=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
Sample code : https://play.golang.org/p/-GtWnBxeDAB

fmt.Sscanf does not seem to work properly with the euc-kr charset.
I am working in an euc-kr environment, but I have not been able to perform an overall test on a multi-byte rune string.

### What did you expect to see?

When you work with the euc-kr string using fmt.Sscanf, the same character (euc-kr) string must be assigned to word, word2.

### What did you see instead?

Unknown string code set is assigned to string string by sscanf.

**Comment by robpike** [comment]
Scanf, like all the string routines in the standard library, assume UTF-8. It is working as intended, unfortunate though that may be for you. You will need help from another package to succeed here.

@mpvl

**Comment by mattn** [comment]
@newro As rob mentioned, the reader should read contents as utf-8. Please try below.

```go
r := korean.EUCKR.NewDecoder().Reader(strings.NewReader(str))
fmt.Fsscanf(r, "%d %d %s %s", &sp, &ep, &word, &word2)
```
