### ISSUE TITLE
x/crypto/nacl: add support for sign

### ISSUE THREAD

**Issue by FlorianUekermann** [golang/go#24350]
cc @agl

There was a ticket for this 2 years ago (#15222).
The reasoning for not adding sign in the comments on that ticket was to wait for NaCl to add Ed25519 support. However, there hasn't been an update to the original codebase since 2011, while other implementations have added Ed25519 support.

I don't really understand the hesitation in adding Ed25519 sign, given that both TweetNaCl (by the original NaCl authors) as well as libsodium (which is by far the most popular implementation) and several other implementations do exactly that (to my understanding, but I'm not an expert).
Furthermore it seems like the existing Ed25519 implementation contains all the necessary pieces.

Given the popularity of the NaCl interface supporting all of the core functionality seems quite important. Could you comment on the situation? If you want to move forward with this I'm happy to contribute some code.

**Comment by agl** [comment]
Agreed that NaCl is probably not going to add support for Ed25519. Now that the RFC is published, and we have Ed25519 in x/crypto, adding a small wrapper around it would be fine. One thing to keep in mind is that the RFC defines the signatures to be non-malleable by requiring _s_ to be minimal. We might want to standardise on that if things like libsodium have.

**Comment by FlorianUekermann** [comment]
I took a look at the libsodium signature checking code regarding the non-malleability question. It looks like it does check for non-malleability by default. I'll document the details here so you can have a look. The call chain looks like this [crypto_sign_open()](https://github.com/jedisct1/libsodium/blob/7d4976a304c777c2925f67a7df1a390ca8742f30/src/libsodium/crypto_sign/crypto_sign.c#L68l) -> [crypto_sign_ed25519_open()](https://github.com/jedisct1/libsodium/blob/e2581d91056fb1a7224c34aaa2e575099bbad163/src/libsodium/crypto_sign/ed25519/ref10/open.c#L67) -> [crypto_sign_ed25519_verify_detached()](https://github.com/jedisct1/libsodium/blob/e2581d91056fb1a7224c34aaa2e575099bbad163/src/libsodium/crypto_sign/ed25519/ref10/open.c#L14) -> [sc25519_is_canonical()](https://github.com/jedisct1/libsodium/blob/d5cb2e5af0e1757db4ba88274f6dc489be14ebbb/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c#L1881)

That last call only happens if ED25519_COMPAT is **not** defined.

[sc25519_is_canonical()](https://github.com/jedisct1/libsodium/blob/d5cb2e5af0e1757db4ba88274f6dc489be14ebbb/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c#L1881)
does the 0<=S<l check described in [RFC8032](https://tools.ietf.org/html/rfc8032#section-8.4) , at least it looks like that to me (someone double check those two lines in the do-while loop please) and is mostly identical the code introduced in jedisct1/libsodium@62911edb7ff2275cccd74bf1c8aefcc4d76924e0.

So it looks like libsodium does conform to the RFC. What does `golang.org/x/crypto/ed25519` do?

**Comment by agl** [comment]
I think `ed25519` should enforce canonical signatures too if libsodium is. Please see linked CL.

**Comment by FlorianUekermann** [comment]
Great. That makes nacl/sign fairly trivial. I have the code and tests, which I'll send as soon as the CL is merged.
