### ISSUE TITLE
runtime: make all waitReasons distinct?

### ISSUE THREAD

**Issue by josharian** [golang/go#24362]
Migrated from the discussion in CL 99078:

> There are a couple of places where some reasons are already re-used. Is it worth making them distinct (in a separate CL)? Another option for making them distinct, now that we have a waitReason uint8, is giving them different numerical values but stringify them the same.

Should we do this? If so, distinct ints only or also distinct strings?

The fix is pretty easy regardless. cc @aclements for opinions.

**Comment by aclements** [comment]
I don't think distinct ints are useful. That's a perfectly sensible encoding, but I don't ever want to show the ints to a user.

Do you have the re-used reasons handy?

**Comment by josharian** [comment]
```bash
$ grep -R -I "gopark" . | awk -F '"' '{print $2}' | grep -v "^$" | sort | uniq -c | sort -n -r | grep -v "\s*1 "
   3 wait for GC cycle
   2 semacquire
   2 GC sweep wait
```

**Comment by rsc** [comment]
Leaving this for @aclements to close.

**Comment by aclements** [comment]
> 3 wait for GC cycle

Probably these should actually get factored into a single function. It's three copies of very similar code.

> 2 semacquire

These could be distinct. One is for acquiring semaphores, the other is for `sync.Cond.Wait`.

> 2 GC sweep wait

These really are the same thing, but the control flow makes it a little tricky to bring them together, so this is fine.
