### ISSUE TITLE
runtime: remove g.gcscanvalid

### ISSUE THREAD

**Issue by josharian** [golang/go#24363]
@aclements commented in CL 99078:

> Yeah, we should probably remove gcscanvalid now that we don't rescan stacks.

This will also shrink the size of `struct g` a little bit.

**Comment by mvdan** [comment]
I wonder if we should mark these TODO issues on the easy side as help-wanted, to attract more first-time contributors.

**Comment by josharian** [comment]
I don’t know whether this is easy. :) But if so, definitely.
