### ISSUE TITLE
cmd/vet: failing on files with build tags in raw string literals

### ISSUE THREAD

**Issue by jayconrod** [golang/go#24365]
### What version of Go are you using (`go version`)?

Go 1.10

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/usr/local/google/home/jayconrod/go/bin"
GOCACHE="/usr/local/google/home/jayconrod/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/jayconrod/go"
GORACE=""
GOROOT="/usr/local/google/home/jayconrod/Code/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/jayconrod/Code/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build359663571=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```
$ go get -u -d github.com/bazelbuild/bazel-gazelle
$ go test github.com/bazelbuild/bazel-gazelle/internal/packages
```

### What did you expect to see?

No vet failures with the message `+build comment must appear before package clause and be followed by a blank line`.

### What did you see instead?

Several failures with that message. In particular, see [fileinfo_go_test.go:121](https://github.com/bazelbuild/bazel-gazelle/blob/c942db95fcf736f79c95e01cc342c31b260e2a0d/internal/packages/fileinfo_go_test.go#L121).

Gazelle extracts some build metadata from source files. That includes build tags. There are some unit tests with raw literal strings that include build tags, and vet is reporting errors for these.

vet should ignore strings for the purposes of this check and should only report errors on comments.

**Comment by josharian** [comment]
Duplicate of #13533

**Comment by jayconrod** [comment]
Thanks, I'll close this and comment on that issue.
