### ISSUE TITLE
fatal error: runtime: stack split at bad time

### ISSUE THREAD

**Issue by fighting520** [golang/go#24371]
runtime: newstack sp=0x7f730fffe6a0 stack=[0xc420022800, 0xc420023000]
	morebuf={pc:0x0 sp:0x7f730fffe6a8 lr:0x0}
	sched={pc:0x443092 sp:0x7f730fffe6a0 lr:0x0 ctxt:0x0}
fatal error: runtime: stack split at bad time

runtime stack:
runtime.throw(0xdb160a, 0x20)
	/opt/go/src/runtime/panic.go:596 +0x95
runtime.newstack(0x0)
	/opt/go/src/runtime/stack.go:989 +0xb26
runtime.morestack()
	/opt/go/src/runtime/asm_amd64.s:398 +0x86

goroutine 13 [syscall]:
created by runtime.addtimerLocked
	/opt/go/src/runtime/time.go:116 +0xed

goroutine 1 [select, 114 minutes]:
github.com/facebookgo/grace/gracehttp.Serve(0xc4203daa70, 0x1, 0x1, 0xc42001a040, 0xc42006c0cc)
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:162 +0x5e6
main.main()
	/dbdata/goworkspace/src/coding.net/wawa/main.go:34 +0xb0

goroutine 17 [syscall, 114 minutes, locked to thread]:
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive, 114 minutes]:
database/sql.(*DB).connectionOpener(0xc4200e1cc0)
	/opt/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
	/opt/go/src/database/sql/sql.go:582 +0x212

goroutine 6 [select, 114 minutes]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc4202d22a0, 0xc4202d2300)
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 7 [select, 114 minutes]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc4202d22a0, 0xc4202d2300)
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 8 [select, 114 minutes]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc4202d22a0, 0xc4202d2300)
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 9 [select, 114 minutes]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc4202d22a0, 0xc4202d2300)
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/dbdata/goworkspace/src/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 34 [syscall, 114 minutes]:
os/signal.signal_recv(0x435708)
	/opt/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/opt/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [select, 114 minutes]:
github.com/jakecoffman/cron.(*Cron).run(0xc4202b6800)
	/dbdata/goworkspace/src/github.com/jakecoffman/cron/cron.go:185 +0xa63
created by github.com/jakecoffman/cron.(*Cron).Start
	/dbdata/goworkspace/src/github.com/jakecoffman/cron/cron.go:160 +0x43

goroutine 35 [select]:
github.com/facebookgo/httpdown.(*server).manage(0xc4203e0210)
	/dbdata/goworkspace/src/github.com/facebookgo/httpdown/httpdown.go:204 +0xa2b
created by github.com/facebookgo/httpdown.HTTP.Serve
	/dbdata/goworkspace/src/github.com/facebookgo/httpdown/httpdown.go:96 +0x3df

goroutine 36 [IO wait]:
net.runtime_pollWait(0x7f7339b9c078, 0x72, 0x0)
	/opt/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42045f488, 0x72, 0x0, 0xc420570ce0)
	/opt/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42045f488, 0xffffffffffffffff, 0x0)
	/opt/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42045f420, 0x0, 0x13d57c0, 0xc420570ce0)
	/opt/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc4203daa78, 0xc420340eb0, 0x6c3c3e, 0x459870)
	/opt/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc4203daa78, 0xdeb238, 0xc420d0f2c0, 0x13dc4c0, 0xc42032f530)
	/opt/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc4203e00b0, 0x13db640, 0xc4203daa78, 0x0, 0x0)
	/opt/go/src/net/http/server.go:2643 +0x228
github.com/facebookgo/httpdown.(*server).serve(0xc4203e0210)
	/dbdata/goworkspace/src/github.com/facebookgo/httpdown/httpdown.go:277 +0x83
created by github.com/facebookgo/httpdown.HTTP.Serve
	/dbdata/goworkspace/src/github.com/facebookgo/httpdown/httpdown.go:97 +0x401

goroutine 37 [semacquire, 114 minutes]:
sync.runtime_Semacquire(0xc420456f6c)
	/opt/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420456f60)
	/opt/go/src/sync/waitgroup.go:131 +0x7a
github.com/facebookgo/grace/gracehttp.(*app).wait(0xc420380240)
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:85 +0x115
github.com/facebookgo/grace/gracehttp.Serve.func1(0xc4203805a0, 0xc420380240)
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:159 +0x51
created by github.com/facebookgo/grace/gracehttp.Serve
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:160 +0x3af

goroutine 38 [chan receive, 114 minutes]:
github.com/facebookgo/grace/gracehttp.(*app).signalHandler(0xc420380240, 0xc420456f60)
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:103 +0x121
created by github.com/facebookgo/grace/gracehttp.(*app).wait
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:76 +0x81

goroutine 39 [chan receive, 114 minutes]:
github.com/facebookgo/httpdown.(*server).Wait(0xc4203e0210, 0xdeb9c8, 0xc420456f60)
	/dbdata/goworkspace/src/github.com/facebookgo/httpdown/httpdown.go:283 +0x5b
github.com/facebookgo/grace/gracehttp.(*app).wait.func1(0xc420456f60, 0xc420380240, 0x13d87c0, 0xc4203e0210)
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:80 +0x5b
created by github.com/facebookgo/grace/gracehttp.(*app).wait
	/dbdata/goworkspace/src/github.com/facebookgo/grace/gracehttp/http.go:83 +0xdc

goroutine 21 [select, 114 minutes, locked to thread]:
runtime.gopark(0xdeb898, 0x0, 0xd944ad, 0x6, 0x18, 0x2)
	/opt/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42033cf50, 0x0, 0x18)
	/opt/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42033cf50)
	/opt/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/opt/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2197 +0x1

**Comment by agnivade** [comment]
A stack trace is not enough for us to debug. Please fill the complete issue template and provide a small and self-contained code which can be reproduced.

Thanks.

**Comment by mvdan** [comment]
In other words, please don't skip the issue template unless you really know what you're doing.

**Comment by davecheney** [comment]
This program almost certainly contains a data race. I’m going to close this issue and I welcome you to create a new issue. 

A. Once you’ve verified that your code, and any code that you code depends on is free from data races.
B. You follow the issue template and provide a mechanism to reproduce the crash you see.
