### ISSUE TITLE
compress/{gzip,zlib}: Writer documentation naming inconsistency

### ISSUE THREAD

**Issue by dpinela** [golang/go#24379]
The documentation for both gzip.NewWriter and zlib.NewWriter contains the sentence "It is the caller's responsibility to call Close on the WriteCloser when done", yet both functions return a type named Writer, and it is referred to by that name everywhere else it appears.

**Comment by ALTree** [comment]
I guess it says that because

```
type gzip.Writer

A Writer is an io.WriteCloser.
```

but it's true that it's just called "the Writer" everywhere else; it should probably called "Writer" there, too.
