### ISSUE TITLE
x/mobile: gomobile version unknown: binary is out of date, re-install it

### ISSUE THREAD

**Issue by udhos** [golang/go#24389]
### What version of Go are you using (`go version`)?

go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

lab@ubu1:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lab/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lab/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build147874781=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

```
lab@ubu1:~$ go get golang.org/x/mobile/cmd/gomobile
lab@ubu1:~$ gomobile init
lab@ubu1:~$ gomobile version
gomobile version unknown: binary is out of date, re-install it
lab@ubu1:~$

```
### What did you expect to see?

gomobile version should report its version.

### What did you see instead?

gomobile version unknown: binary is out of date, re-install it

**Comment by eliasnaur** [comment]
Reopened because CL 102794 didn't fix this issue as I expected. I'm sorry to have jumped the gun.
