### ISSUE TITLE
encoding/json: Marshal on []byte is not working

### ISSUE THREAD

**Issue by Inkeliz** [golang/go#24397]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.10 windows/amd64
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Inkeliz\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Documentos\GoProjects\
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Inkeliz\AppData\Local\Temp\go-build001441186=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Creating one type that is alias to `[]byte` will not trigger the `Marshal`, but triggers the `Unmarshal`, like:

```
type MyType []byte

type StructJSON struct {
	Name MyType
}

func (d *MyType) MarshalJSON() ([]byte, error) {   // << Never will be triggered
}

func (d *MyType) UnmarshalJSON(data []byte) (err error) { // << Working :)
}
```

See the demonstration at https://play.golang.org/p/FHOMVOq1oDD

### What did you expect to see?

I expect that the same result of `UnmarshalJSON`. In the demonstration the message of `Marshal is working` should be displayed.

### What did you see instead?

The `MarshalJSON()` are not beginning triggered and don't have the same behavior of `UnmarshalJSON`.

**Comment by Inkeliz** [comment]
Replacing `*MyType` to `MyType` will work.

**Comment by andybons** [comment]
In your playground example, replace `result, _ := json.Marshal(st)` with `result, _ := json.Marshal(&st)`

The Marshal method is defined on a pointer receiver. If you defined it as 

```
func (d MyType) MarshalJSON() ([]byte, error) {
  ...
}
```

Then `result, _ := json.Marshal(st)` would work, like you said.
