### ISSUE TITLE
cmd/go: go install -x -n is not empty even if nothing needs building

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#24396]
### What version of Go are you using (`go version`)?
go version devel +fdf5aaf555 Mon Mar 12 15:05:53 2018 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elias/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elias/dev/go"
GORACE=""
GOROOT="/home/elias/dev/go-tip"
GOTMPDIR=""
GOTOOLDIR="/home/elias/dev/go-tip/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build596110402=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
````
$ go install golang.org/x/mobile/cmd/gomobile
$ go install -x -n golang.org/x/mobile/cmd/gomobile
rm -r $WORK/b001/
````

### What did you expect to see?
Nothing output from the second command

### What did you see instead?
`rm -r $WORK/b001/`

This is the root cause for https://github.com/golang/go/issues/24389. gomobile version uses go install -x -n to determine if the gomobile binary is up to date by checking that its output is empty.

**Comment by andybons** [comment]
@ianlancetaylor @rsc

**Comment by ianlancetaylor** [comment]
I'll look into this, but couldn't you use `go list -f '{{.Stale}}'` instead?

**Comment by eliasnaur** [comment]
That option didn't occur to me. However, it doesn't seem to work in my case:

````
$ go version
go version devel +a44c72823c Tue Mar 27 15:06:53 2018 +0000 linux/amd64
$ go install golang.org/x/mobile/cmd/gomobile
$ go list -f '{{.Stale}}' golang.org/x/mobile/cmd/gomobile
true
$ go list -f '{{.StaleReason}}' golang.org/x/mobile/cmd/gomobile
stale dependency: golang.org/x/mobile/internal/binres
````

I can manually go install the dependency:
````
$ go install golang.org/x/mobile/internal/binres
$ go list -f '{{.Stale}}' golang.org/x/mobile/cmd/gomobile
false
````

But as soon as I blow away my $GOPATH/pkg dir, the problem reappears:

````
$ rm -rf $GOPATH/pkg
$ go install golang.org/x/mobile/cmd/gomobile
$ go list -f '{{.Stale}}' golang.org/x/mobile/cmd/gomobile
true
$ go list -f '{{.StaleReason}}' golang.org/x/mobile/cmd/gomobile
stale dependency: golang.org/x/mobile/internal/binres
````

Did I miss something?

**Comment by ianlancetaylor** [comment]
I don't think you missed anything.  Filed #24558.

**Comment by ianlancetaylor** [comment]
Reopening for 1.10.1, since it affects mobile builds.

**Comment by andybons** [comment]
CL 102619 OK for Go 1.10.1

**Comment by ianlancetaylor** [comment]
This doesn't fix the gomobile problem, so not important for 1.10.1, so closing again.
