### ISSUE TITLE
gccgo: "unsupported GOOS/GOARCH pair" using gccgo - regression

### ISSUE THREAD

**Issue by aykevl** [golang/go#24398]
It looks like issue #12272 is back in go 1.10, while it was still gone in go 1.9.4. It emits this error "unsupported GOOS/GOARCH pair" even when using `-compiler=gccgo`. As per https://github.com/golang/go/issues/12272#issuecomment-232113361, I think it should be fixed again.

Go version: go1.10 linux/amd64

Note: I'm trying to write a cross-compiler wrapper to the ESP32 (see [here](https://github.com/aykevl/tinygo)), which compiles with GOOS=esp32 and GOARCH=xtensa (I had to choose something for those values).

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
I can't recreate this.  Please show us the exact command that you are running and the exact output that you see.  Thanks.

**Comment by ianlancetaylor** [comment]
OK, I can recreate this if I use the gc version of the go tool, but not if I use the gccgo version of the go tool.  Is that what you are doing?

**Comment by ianlancetaylor** [comment]
Yes, there are two slightly different versions of the go command.  If you install gccgo, you will get a gccgo-specific version of the command, which will default to `-compiler=gccgo`.  If you do not install gccgo, you won't be able to use gccgo anyhow.  Simply downloading the gc toolchain from golang.org/dl will not make `-compiler=gccgo` work; you must also install gccgo.

**Comment by aykevl** [comment]
Actually, I have `gccgo` installed, from the Debian archive (Debian stretch). So that shouldn't be the problem.

Note that I have *used* `go build -compiler=gccgo`, with a version downloaded from golang.org, it's just that the latest version stopped working. As far as I can see, everything is equal in my configuration except for the `gc` tool version.

```
~$ which go
/usr/local/go/bin/go

~$ /usr/local/go/bin/go version
go version go1.10 linux/amd64

~$ /usr/local/go1.8/bin/go version
go version go1.8.3 linux/amd64

~$ GOOS=linux GOARCH=xtensa /usr/local/go/bin/go build -compiler=gccgo foobar
cmd/go: unsupported GOOS/GOARCH pair linux/xtensa

~$ GOOS=linux GOARCH=xtensa /usr/local/go1.8/bin/go build -compiler=gccgo foobar
can't load package: package foobar: cannot find package "foobar" in any of:
	/usr/local/go/src/foobar (from $GOROOT)
	/home/ayke/src/foobar (from $GOPATH)
```

**Comment by ianlancetaylor** [comment]
If you have installed gccgo, then in the same directory as the gccgo executable there is a go executable.  Run that instead of /usr/local/go/bin/go.

I'm not saying that there isn't a bug here.  There is a bug.  I'm just giving you a workaround.

**Comment by aisk** [comment]
I think the go command error message is a little bit misleading. In the issue's case, `-compiler=gccgo` specified gccgo as compiler, but it's not in PATH, but the actully error message is `cmd/go: unsupported GOOS/GOARCH pair darwin/xtensa`.

I think it's better to show something like this:

`cmd/go: gccgo: exec: "gccgo": executable file not found in $PATH`

**Comment by ianlancetaylor** [comment]
Yes, we agree there is a bug here.  Want to send a patch?  Thanks.

**Comment by aisk** [comment]
I took a dig and found that the root case is that before real `buildCmd` we ran the `MkEnv()` [here](https://github.com/golang/go/blob/master/src/cmd/go/main.go#L150) to have a guarantee.

But this leading to call [cmd/go/internal/work.Builder.Init](https://github.com/golang/go/blob/master/src/cmd/go/internal/work/action.go#L240), and this function will validate the OS/ARCH pair and may cause exit. And at that moment, the buildCmd is not executed and the `-compiler` flag is not set, so we can't check it at that time.

I thought we can add a `noexit` flag in the [cmd/go/internal/work.Builder.Init](https://github.com/golang/go/blob/master/src/cmd/go/internal/work/action.go#L240) to let ignore the validation, or just return an error and let the caller to decide should call exit.

@ianlancetaylor what do you think, or have other idea?

**Comment by ianlancetaylor** [comment]
Seems to me that we should just move the call to `CheckGOOSARCHPair` to later.  For example, perhaps we could call it from `BuildInit`.  But I haven't really looked at this.

**Comment by bcmills** [comment]
Is there anything more needed for this issue?

I'm seeing the following with a `go` command build from head:

```
$ go version
go version devel +59bfc18e3 Fri Jan 8 22:55:41 2021 +0000 linux/amd64

$ go mod init example.com
go: creating new go.mod: module example.com

$ /usr/bin/which gccgo

$ cat > main.go
package main

func main() {}

$ GOARCH=xtensa GOOS=linux go build -compiler=gccgo .
cmd/go: gccgo: exec: "gccgo": executable file not found in $PATH
```

That seems to match the desired behavior described in https://github.com/golang/go/issues/24398#issuecomment-627096007.

**Comment by aykevl** [comment]
FYI: I'm not using `GOARCH=xtensa go build ...` etc anymore, there are too many things that don't work with that configuration. So feel free to close this.
