### ISSUE TITLE
testing: failfast flag not working when prior test is aborted with t.Fatal

### ISSUE THREAD

**Issue by jdef** [golang/go#24412]
### What version of Go are you using (`go version`)?

1.10

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vagrant/workspace-failfast"
GORACE=""
GOROOT="/usr/local/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build473380735=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

https://github.com/jdef/failfast

### What did you expect to see?

I expected no tests to execute after the first test failed.

### What did you see instead?

The second test was executed, even though `-test.failfast` was specified.
Note, things work as expected if `t.Fatal` is changed to `t.Error`.

**Comment by fraenkel** [comment]
The issue is with FatalX which calls runtime.Goexit. This causes the failure counting to be skipped in tRunner.

**Comment by jdef** [comment]
Any chance that the fix for this could be backported to the 1.10.x stream?

**Comment by ianlancetaylor** [comment]
@jdef No, sorry.
