### ISSUE TITLE
crytpo/x509: MarshalPKCS8PrivateKey doc erraneously says ecdsa.PublicKey instead of ecdsa.PrivateKey

### ISSUE THREAD

**Issue by golangdaddy** [golang/go#24413]
Documentation error for x509.MarshalPKCS8PrivateKey...

Docs say this will marshal ecdsa.PublicKey but the author obviously meant ecdsa.PrivateKey.

ecdsa.PublicKey does not marshal: 

x509: unknown key type while marshalling PKCS#8: *ecdsa.PublicKey

**Comment by adamdecaf** [comment]
Thanks for catching that!
