### ISSUE TITLE
x/tools/cmd/guru: test broken for 1.10, 1.9 due to version issues

### ISSUE THREAD

**Issue by griesemer** [golang/go#24421]
Just a reminder issue to fix this better.

See https://go-review.googlesource.com/c/tools/+/101015 for details.

**Comment by griesemer** [comment]
Not sure if there's still something to do here. With 1.12 we will only support 1.11 and 1.10. Leaving to @alandonovan to decide.

**Comment by odeke-em** [comment]
Kindly paging you @alandonovan to follow-up on @griesemer's request in  https://github.com/golang/go/issues/24421#issuecomment-422248620

**Comment by stamblerre** [comment]
I think the only thing left is to delete the Go 1.9-specific tests - they were added when we still needed to support 1.8, but now all these tests can be recombined.

**Comment by odeke-em** [comment]
Great, thank you @stamblerre and @alandonovan for following up with the game plan! Sure, we'll leave this issue in for Go1.12.
