### ISSUE TITLE
go reflect

### ISSUE THREAD

**Issue by itgeniusshuai** [golang/go#24420]
Please answer these questions before submitting your issue. Thanks!

How I can list all structs and functions by package name, or create a struct instance by struct name,such as
package test
type User struct {
	Name string
}
func getStructNameByPackageName(packageName string) []string{
 ...
}
func createStructInstance(structName string) interface{}{
...
}
1. call function getStructNameByPackageName("test") we will get result: ['User']
2. call function createStructInstance("test.User") we will get result: a User instance
I scan many pages on the web,but most people say cann't do these. If can ,please tell me, thank you very much 
### What version of Go are you using (`go version`)?
1.7.3

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
