### ISSUE TITLE
sync: Cond WaitFor and/or WaitUntil method(s)

### ISSUE THREAD

**Issue by dfawley** [golang/go#24429]
I would like to block on a condition variable, but give up when a timeout/deadline is reached.  I.e.:

```go
func (c *Cond) WaitFor(d time.Duration) bool {}
func (c *Cond) WaitUntil(t time.Time) bool {}
```

This functionality can be implemented without a `sync.Cond` using channels and timers and a `select`, but I believe a `sync.Cond` would be more efficient and succinct.

FYI: #21165

**Comment by ianlancetaylor** [comment]
Dup of #23211, which was closed.
