### ISSUE TITLE
x/tools/godoc: Not all subrepos listed.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#24432]
This is a 2018 edition of issue #9081.

In #14304, a new x/perf subrepo was proposed and created. I noticed it wasn't listed at https://golang.org/pkg/#subrepo, and the feedback was that it should be added.

I also noticed that x/time subrepo was missing and filed #24430 for that, which got labeled with `NeedsFix`.

While working on a trivial fix, I realized there are even more subrepos not listed. The list of subrepos, as determined by the [source code](https://github.com/golang/tools/blob/39919aea0440ceb01a167207d6ec6eb6d48d8a42/cmd/godoc/x.go#L24-L51) for the /x/ handler, is:

```Go
var xMap = map[string]xRepo{
	"codereview": {"https://code.google.com/p/go.codereview", "hg"},

	"arch":       {"https://go.googlesource.com/arch", "git"},
	"benchmarks": {"https://go.googlesource.com/benchmarks", "git"},
	"blog":       {"https://go.googlesource.com/blog", "git"},
	"build":      {"https://go.googlesource.com/build", "git"},
	"crypto":     {"https://go.googlesource.com/crypto", "git"},
	"debug":      {"https://go.googlesource.com/debug", "git"},
	"exp":        {"https://go.googlesource.com/exp", "git"},
	"image":      {"https://go.googlesource.com/image", "git"},
	"lint":       {"https://go.googlesource.com/lint", "git"},
	"mobile":     {"https://go.googlesource.com/mobile", "git"},
	"net":        {"https://go.googlesource.com/net", "git"},
	"oauth2":     {"https://go.googlesource.com/oauth2", "git"},
	"perf":       {"https://go.googlesource.com/perf", "git"},
	"playground": {"https://go.googlesource.com/playground", "git"},
	"review":     {"https://go.googlesource.com/review", "git"},
	"sync":       {"https://go.googlesource.com/sync", "git"},
	"sys":        {"https://go.googlesource.com/sys", "git"},
	"talks":      {"https://go.googlesource.com/talks", "git"},
	"term":       {"https://go.googlesource.com/term", "git"},
	"text":       {"https://go.googlesource.com/text", "git"},
	"time":       {"https://go.googlesource.com/time", "git"},
	"tools":      {"https://go.googlesource.com/tools", "git"},
	"tour":       {"https://go.googlesource.com/tour", "git"},
	"vgo":        {"https://go.googlesource.com/vgo", "git"},
}
```

It's not clear to me whether absolutely all of them should be listed or not. This issue is about determining that.

Once a decision is made about which missing repos should be listed, the missing repos can either be manually added (as was done before in https://github.com/golang/tools/commit/06e42bd9eb281c80b8c04b1c38ece4e33e0df1f3), or, alternatively, we can consider reworking the `xMap` to serve both as a source for the /x/ handler as well as a list of subrepos that are displayed by `godoc`.

**Comment by spf13** [comment]
@shurcooL please send a CL with the addition of perf, review, sync, and time. 

We don't need to make this automatically generated as we infrequently add repos and many are more internal or experimental and shouldn't be included in the list.

**Comment by shurcooL** [comment]
> a CL with the addition of perf, review, sync, and time.

Ok, on it now.

> We don't need to make this automatically generated as we infrequently add repos

That's fair.

> many are more internal or experimental and shouldn't be included in the list.

Can we add a comment stating that then? Otherwise, it's unclear if a repo is not included because it's a bug, or because it's considered internal and its omission is intentional.

I can add the comments in my CL, it'll be easy to review.

I'm a bit surprised that we don't want to add `oauth2`, I thought `golang.org/x/oauth2` was a pretty popular subrepo (it has over 3000 public [importers](https://godoc.org/golang.org/x/oauth2?importers)). I'm okay with it, just wanted to point it out.
