### ISSUE TITLE
path/filepath: Abs("") produces inconsistent results across platforms

### ISSUE THREAD

**Issue by shurcooL** [golang/go#24441]
### What version of Go are you using (`go version`)?

```
go version go1.10 darwin/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Tested this on:

- `darwin/amd64` (macOS High Sierra 10.13.3)
- `linux/amd64`
- `nacl/amd64p32` (Go Playground)
- `windows/amd64` (Windows 7)
- `windows/386` (Windows XP)

### What did you do?

```Go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Abs("."))
	fmt.Println(filepath.Abs(""))
}
```

(https://play.golang.org/p/DHcNjkfcKx9)

### What did you expect to see?

I expected to see consistent behavior across all platforms, either:

```
/Users/Gopher <nil>
/Users/Gopher <nil>
```

Or:

```
/Users/Gopher <nil>
 some error
```

### What did you see instead?

Inconsistent behavior on Windows. For empty string input, it returned an error:

```
C:\Users\Gopher <nil>
 Filename, directory name or volume name syntax is incorrect.
```

All other OSes were consistent and returned nil error and current working directory for `filepath.Abs("")`, just like for `filepath.Abs(".")`.

Inconsistent behavior in `filepath.Abs` makes it hard to write cross-platform programs that operate consistently across platforms.

**Comment by shurcooL** [comment]
I believe this is a bug in `filepath.Abs` on Windows. Here's the evidence.

[`filepath.Abs`](https://godoc.org/path/filepath#Abs) is documented as:

> Abs returns an absolute representation of path. If the path is not absolute it will be joined with the current working directory to turn it into an absolute path. [...]

Both "." and empty string are *not absolute* paths. Both `filepath.IsAbs(".")` and `filepath.IsAbs("")` return `false` on all platforms, including Windows. See https://play.golang.org/p/TEfkzhrCt6f.

Joining either "." or "" element to the current working directory should return the current working directory. See https://play.golang.org/p/YUB2xJITVwD.

Therefore, I believe the correct and expected behavior of `filepath.Abs("")` is to be identical to `filepath.Abs(".")`. That means `filepath.Abs("")` behaves erroneously on Windows and this is a bug.

**Comment by alexbrainman** [comment]
> I believe this is a bug in filepath.Abs on Windows.

Sounds reasonable to me. Would you like to send a fix?

Thank you.

Alex

**Comment by JoshVarga** [comment]
I can send a fix for this if no one else is already working on it.

**Comment by shurcooL** [comment]
I started working on a fix, and in the process of doing so, I found some evidence that concerned me about making `filepath.Abs("")` return `nil` error on Windows and made me want to discuss this decision more before committing to the fix. Let me describe it here and move the issue back to `NeedsDecision` state (I'd like to hear from experts on this topic).

### Concern

The logic I used originally in https://github.com/golang/go/issues/24441#issuecomment-374014719 to come to the conclusion that `filepath.Abs("")` *should* work and this is a bug on Windows was by reading the documentation of `path/filepath` only. After looking at the code in `path/filepath` and its tests, I became less sure that's the right thing to do.

**My worry is that by making `filepath.Abs("")` return `nil` error on Windows, we're legitimizing empty string as a valid path that refers to the current directory (like `"."` path). Should we be doing that?**

I noticed that many other `os` methods that operate paths do not accept `""` as a valid path. It certainly is not the same as `"."` path, which refers to the current directory. Consider:

```
os.Open("")
os.Create("")
os.Stat("")
```

On macOS, they return `open : no such file or directory` or `stat : no such file or directory` error. They do not refer to the current directory.

I understand that `filepath.Abs` is meant to work on non-existing paths. If you provide a path to where a directory *could* be located, but isn't, it's expected for it to work:

```
os.Open("notexist") // error
os.Stat("notexist") // error
filepath.Abs("notexist") // ok
os.Create("notexist") // ok
```

The important distinction here is that `"notexist"` is a path that can succeed with either `os.Open` or `os.Create`. A file may or may not exist.

However, the empty string path can never succeed with `os.Open` nor `os.Create`. The file referred to with empty path can never exist.

### Alternative Fix

An alternative fix to make `filepath.Abs("")` behavior across platforms to consider is to make `filepath.Abs("")` return non-`nil` error on non-Windows as well.

The current implementation of `abs` on Windows is very simple and has no special cases:

```Go
func abs(path string) (string, error) {
	fullPath, err := syscall.FullPath(path)
	if err != nil {
		return "", err
	}
	return Clean(fullPath), nil
}
```

`syscall.FullPath` returns an error on empty string input, that's why `filepath.Abs("")` returns an error in Windows.

The reason `filepath.Abs("")` works on Unix is because the implementation of `unixAbs` gets the current working directory and uses `Join` (which operates on string paths):

```Go
func unixAbs(path string) (string, error) {
	if IsAbs(path) {
		return Clean(path), nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return Join(wd, path), nil
}
```

The potential benefit of this approach is that it makes it clear that to get the path to current directory, you can use `filepath.Abs(".")` but cannot use `filepath.Abs("")`. It makes `Abs` more consistent with other operations on paths, and `""` continues to not be a valid meaningful path (certainly not one that refers to current directory).

The downside is that it might affect more user code. I don't know how many people rely on `filepath.Abs("")` working on non-Windows OSes, but perhaps this is something that can be queried via the Go corpus to get an idea.

I wanted to bring this up and I'm looking forward to hear from experts on this topic.

**Comment by alexbrainman** [comment]
> An alternative fix to make filepath.Abs("") behavior across platforms to consider is to make filepath.Abs("") return non-nil error on non-Windows as well.

I am fine with that fix too, but I cannot make that decision. Leaving it for others to decide.

Thank you.

Alex

**Comment by ianlancetaylor** [comment]
The current docs say

```
// If the path is not absolute it will be joined with the current
// working directory to turn it into an absolute path.
```

The empty string is not an absolute path, so the docs suggest that the empty string should be joined with the current working directory to turn it into an absolute path.  Let's do that on Windows too.

**Comment by shurcooL** [comment]
@ianlancetaylor I'm not opposed to that decision, but there's something I want to check with you first.

I used the same logic, reading the docs and interpreting what they say, in my original issue report and came to that conclusion.

However, when I started working on the fix, after looking at the current implementation and its tests, it was when I encountered a concern that I described in https://github.com/golang/go/issues/24441#issuecomment-377984978. I just wanted to confirm, did you take that comment into account when making the decision?

In any case, I'd like to work on this, because I've already implemented this partially locally.

**Comment by ianlancetaylor** [comment]
@shurcooL Thanks, I read your comment but I don't see it as a problem.  I don't think `""` and `"."` are or should be the same thing.  I just think that we have an inconsistency in `filepath.Abs` today, so we have to pick one, and I'm inclined to pick the one that matches the documentation.  I don't think the handling of `""` implies anything about how it is handled by `os.Open`.
