### ISSUE TITLE
cmd/cgo: mark all the C functions as go:noescape

### ISSUE THREAD

**Issue by valyala** [golang/go#24450]
### What version of Go are you using (`go version`)?

go tip

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Build the following code with `go build -gcflags=-m`:

```go
package ff

// void f1(void *p) {}
import "C"
import "unsafe"

func f2(a []byte) {
        p := unsafe.Pointer(&a[0])
        C.f1(p)
}
```

### What did you expect to see?

`a` shouldn't escape when calling `C.f1`, since, according to [cgo rules](https://golang.org/cmd/cgo/#hdr-Passing_pointers), `C code may not keep a copy of a Go pointer after the call returns`.

This means that all the C functions may be safely marked as `//go:noescape` in order to prevent from useless memory allocations when the argument to C function escapes to heap.

### What did you see instead?

`a` escapes to heap, which leads to useless memory allocation:

```
./1.go:8: &a[0] escapes to heap
./1.go:7: leaking param: a
```

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by randall77** [comment]
I don't think this is safe.  `f1` can call back into Go, causing the Go stack to be copied.  Any subsequent use of `p` by `f1` would then be wrong.

**Comment by ianlancetaylor** [comment]
Yes, this is intentional and I don't see a way to avoid it.

Closing this bug since there is nothing we can do.  Sorry.

**Comment by valyala** [comment]
@ianlancetaylor , is there a possibility to manually mark `C.f1` with `go:noescape`?

**Comment by valyala** [comment]
Currently I use the following "trick" to avoid memory allocations when passing pointers to Go array to C function:

```go
func f3(a []byte) {
    sh := (*reflect.SliceHeader)(unsafe.Pointer(&a))
    C.f1(unsafe.Pointer(sh.Data))
}
```

Unfortunately, this leads to the issue #14210 unless `GODEBUG=cgocheck=0` is set.

**Comment by ianlancetaylor** [comment]
There is no way to manually mark it.  cgo is generating code that deliberately causes it to escape, to ensure that the value is not allocated on the stack.  I don't know whether there is any better approach that will work for your application.  This should probably be discussed on golang-nuts rather than in the issue tracker.
