### ISSUE TITLE
spec: an imperfect example

### ISSUE THREAD

**Issue by go101** [golang/go#24451]
```
primes := []int{2, 3, 5, 7, 9, 2147483647}
```
9 is not a prime.

**Comment by dgryski** [comment]
Previously https://github.com/golang/go/issues/2870

**Comment by andybons** [comment]
For posterity: 
> It's a reference to a legendary article from the Journal of Irreproducible Results.

— @robpike

**Comment by go101** [comment]
great reads: https://github.com/golang/go/issues/8830 https://github.com/golang/go/issues/10892 http://en.wikipedia.org/wiki/Paul_Erd%C5%91s (esp. the last one)
