### ISSUE TITLE
go/importer: backport importer.For("source") fixes for 1.10

### ISSUE THREAD

**Issue by griesemer** [golang/go#24452]
Tracking issue for 1.10 point release fix.
See #24392 and https://github.com/golang/go/issues/24392#issuecomment-373994843 for details.

**Comment by andybons** [comment]
CL 83415 OK for Go 1.10.1

**Comment by andybons** [comment]
@griesemer to save time in the future you can re-open the issue and put it in the appropriate milestone for backporting instead of going through the trouble of creating a new issue.

**Comment by griesemer** [comment]
@andybons ACK
