### ISSUE TITLE
cmd/doc: no error for invalid one-letter package path

### ISSUE THREAD

**Issue by willfaught** [golang/go#24462]
This felt vaguely familiar, like maybe I'd reported it before, but searched and couldn't find anything, so apologies if it's a dupe.

### What version of Go are you using (`go version`)?

```
go version go1.10 darwin/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/willfaught/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/willfaught/Developer/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_1/ggvd2t1x7hz_185crsb36zlr0000gp/T/go-build967928832=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

```
~ $ echo $GOPATH  
/Users/willfaught/Developer/go
~ $ ls $GOPATH/src
cloud.google.com      collectd.org          go.mercari.io         golang.org            gopkg.in              k8s.io                sourcegraph.com
code.cloudfoundry.org github.com            go.uber.org           google.golang.org     honnef.co             rsc.io                t
~ $ go doc z
```

### What did you expect to see?

```
~ $ go doc z
doc: no buildable Go source files in /Users/willfaught
exit status 1
~ $
```

### What did you see instead?

```
~ $ go doc z
package z // import "."

~ $
```

It seems to be related to the package path being one letter:

```
~ $ go doc zz # zz, not z
doc: no buildable Go source files in /Users/willfaught
exit status 1
~ $
```

**Comment by jimmyfrasche** [comment]
@willfaught does `go list` produce similar errors or is this specific to `go doc`?

**Comment by mvdan** [comment]
Seems to be exculsive to `go doc`. `go list`, `godoc` and all other tools error. I can reproduce it on my machine too.

**Comment by mvdan** [comment]
Ah, this is because of how `go doc` is designed. It will try to find a package by suffix, so that `go doc json` will match `encoding/json`.

However, this has a funny result; the Go tree has many one-letter packages. For example, the one that OP was finding was likely `/home/mvdan/tip/src/cmd/go/testdata/testvendor/src/q/z`. And if one uses `d`, it finds `/home/mvdan/tip/src/cmd/go/testdata/src/canonical/d`.

Seems like the easy fix here is to teach `go doc` the basics of when directories in $GOPATH cannot contain importable packages, such as those under `testdata` or under directories starting with `_`.

**Comment by willfaught** [comment]
It doesn't work for `go list z`:

```
~ $ go list z
can't load package: package z: cannot find package "z" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/z (from $GOROOT)
	/Users/willfaught/Developer/go/src/z (from $GOPATH)
```

>However, this has a funny result; the Go tree has many one-letter packages. For example, the one that OP was finding was likely /home/mvdan/tip/src/cmd/go/testdata/testvendor/src/q/z. And if one uses d, it finds /home/mvdan/tip/src/cmd/go/testdata/src/canonical/d.

That appears to be correct. y, w, x, v, a, b, c, d all work for me, but e does not:

```
~ $ go doc e                      
doc: no buildable Go source files in /Users/willfaught
exit status 1
```

The output doesn't indicate the absolute import path, so I have no idea where these one-letter packages are. Perhaps go doc should print the import path to disambiguate a partial match.

I didn't know about the pattern matching. If that's indeed correct behavior, then I guess this isn't a bug.

Thanks for looking into it!

**Comment by willfaught** [comment]
@mvdan I didn't see you assigned it to yourself until I closed it. Re-opening, sorry.

**Comment by mvdan** [comment]
> Perhaps go doc should print the import path to disambiguate a partial match.

Maybe. I simply added a debug print myself. That seems like a discussion/feature for another issue, though.

The fix is simple, but the tests rely on a package in the testdata directory, so keeping the tests working is being non-trivial. Will send a CL soon-ish.

**Comment by willfaught** [comment]
Are you planning to disable the suffix matching?

**Comment by mvdan** [comment]
Completely removing the suffix matching is unlikely what we want, as that's a useful feature. The point is fixing this in a way that will keep the tests working.

**Comment by mvdan** [comment]
@willfaught @jimmyfrasche I finally found a way to keep the tests working that I'm happy with. Reviews welcome.

**Comment by willfaught** [comment]
Thanks!

**Comment by mvdan** [comment]
Reverted, because I botched the test code and broke some builders. Will try again next week.
