### ISSUE TITLE
cmd/compile: bad error message when type switch assertion used outside of type switch

### ISSUE THREAD

**Issue by myitcv** [golang/go#24470]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10 linux/amd64
go version devel +5f0a9ba134 Tue Mar 20 22:46:00 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes, and tip

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build631842484=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

https://play.golang.org/p/5SSETQWcdrI

I typed something similar to this example by accident. I meant to assert a specific type, but instead used the special type-switch-form of a type assertion by accident.

### What did you expect to see?

An error message that clearly identifies the problem on line 10. e.g.

```
prog.go:10:15: use of .(type) outside type switch
```

### What did you see instead?

A number of error messages, the first of which is, to my mind, a derived/less significant error message:

```
prog.go:10:5: cannot assign 1 value to 2 variables
prog.go:10:15: use of .(type) outside type switch
prog.go:10:24: undefined: ok
prog.go:11:36: undefined: x
```

It's early-ish in the morning, but my eyes got fixed on the first error message... and it took longer than is perhaps sensible to get to the meat of the problem which is the second error message.

cc: @griesemer / @mdempsky 

Thanks to @mvdan for helping to confirm the issue.

**Comment by niktrix** [comment]
you cannot use (type) outside of switch statement.

**Comment by griesemer** [comment]
go/types gives a better error message:
```
$ gotype x.go
x.go:10:14: invalid AST: use of .(type) outside type switch
```
so it's conceivable that the compiler could do as well.

Marking for 1.11 in case we get to it, but definitively not urgent.

**Comment by myitcv** [comment]
> go/types gives a better error message:

Sorry, I should have included that result too. Thanks for doing the legwork.

> ... but definitively not urgent.

Agreed!

**Comment by griesemer** [comment]
This is a cmd/compile/internal/syntax error.

There's also inconsistency. For the following `if` statement
```Go
if x, ok = i.(type); ok {
	fmt.Println("Hello, playground", x)
}
```
using a `=` instead of a `:=` the syntax parser reports no error.

**Comment by griesemer** [comment]
Furthermore, the code:
```Go
switch x = i.(type) {
case T:
}
```
reports (in a syntax parser test):
```
parser_test.go:25: x.go:12:22: syntax error: assignment x = i.(type) used as value
```
while
```Go
switch x, ok := i.(type) {
case T:
}
```
reports (test case of issue):
```
parser_test.go:25: x.go:12:9: cannot assign 1 value to 2 variables
```
The problem is in the asymmetric handling of type switch guards in the syntax parser.

**Comment by myitcv** [comment]
Fantastic - thanks very much @griesemer!

For anyone following this issue, the output from my playground example is now:

```
./main.go:10:15: use of .(type) outside type switch
```
