### ISSUE TITLE
cmd/compile: duplicate blocks calling runtime.panicXXX in some procedures

### ISSUE THREAD

**Issue by laboger** [golang/go#24478]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
tip

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Tried ppc64le and x86

### What did you do?
While looking at some objdumps I noticed some functions that had several blocks of code at the end of the procedure with calls to runtime.panicXXX functions. In some cases there were many duplicate blocks calling the same function.

### What did you expect to see?
The blocks containing identical calls could be collapsed into a single block, with all predecessors branching to the same block.

### What did you see instead?
Here is an example on ppc64le from function runtime.selectgo. Similar code appears in the x86 objdump.
```
    100402a0:   81 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402a4:   00 00 00 00     .long 0x0
    100402a8:   79 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402ac:   00 00 00 00     .long 0x0
    100402b0:   71 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402b4:   00 00 00 00     .long 0x0
    100402b8:   69 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402bc:   00 00 00 00     .long 0x0
    100402c0:   61 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402c4:   00 00 00 00     .long 0x0
    100402c8:   59 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402cc:   00 00 00 00     .long 0x0
    100402d0:   51 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402d4:   00 00 00 00     .long 0x0
    100402d8:   49 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402dc:   00 00 00 00     .long 0x0
    100402e0:   41 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402e4:   00 00 00 00     .long 0x0
    100402e8:   39 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402ec:   00 00 00 00     .long 0x0
    100402f0:   31 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402f4:   00 00 00 00     .long 0x0
    100402f8:   29 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    100402fc:   00 00 00 00     .long 0x0
    10040300:   21 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    10040304:   00 00 00 00     .long 0x0
    10040308:   19 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    1004030c:   00 00 00 00     .long 0x0
    10040310:   11 b9 fe 4b     bl      1002bc20 <runtime.panicindex>
    10040314:   00 00 00 00     .long 0x0
```
Fixing this would reduce the size of the function, possibly enabling more inlining, and reduce the size of the binary.

**Comment by randall77** [comment]
There are multiple calls because each corresponds to a different source line.  We wouldn't get accurate line numbers in tracebacks if we coalesced all the `panicindex` calls in a function.

We do combine multiple identical panics from the same line.  For instance, `a[i] + b[j]` should only generate a single `panicindex` call.

**Comment by andybons** [comment]
@randall77 what is the next step, here? Are you saying this should be closed or is more investigation needed?

**Comment by randall77** [comment]
I guess we should close this unless someone comes up with a better way to encode line numbers during panic.
