### ISSUE TITLE
cmd/compile: mishandling of unsafe-uintptr arguments

### ISSUE THREAD

**Issue by mdempsky** [golang/go#24491]
When calling certain functions that take uintptr parameters with unsafe.Pointer arguments, the compiler rewrites the call to ensure the pointer is kept alive through the call. (See #13372 for more background.) For example, given

    func f() unsafe.Pointer
    func g(uintptr) int

the expression statement

    g(uintptr(f()))

gets rewritten during order into (roughly)

    tmp := f()
    g(uintptr(tmp))
    runtime.KeepAlive(tmp)    // actually OVARLIVE, but same idea

There are a handful of related issues with how this is currently implemented. (I expect some of these will be solved separately, so splitting them into separate issues may be appropriate. I'm just noting them all together for now in case it helps us think of a more holistic solution.)

1. If the caller directly returns the results, the KeepAlive statement is ineffectual because it's dropped by ssa.go as dead code. That's because

       return g(uintptr(f()))

   gets rewritten into

       tmp := f()
       return g(uintptr(tmp))
       runtime.KeepAlive(tmp)

   so tmp isn't actually kept alive through the call to g.

2. Because the KeepAlives are added after the statement, the pointer is kept alive longer than necessary. For example,

       h(g(uintptr(f()))

   gets rewritten into

       tmp := f()
       h(g(uintptr(tmp)))
       runtime.KeepAlive(tmp)

   so tmp is kept alive 

3. They don't work with `defer` or `go` calls. For example,

       go g(uintptr(f()))

   gets rewritten into

       tmp := f()
       newproc(8, g, uintptr(tmp))
       runtime.KeepAlive(tmp)

   which doesn't guarantee that tmp is still alive by time the g call is scheduled to run.

I expect 1 and 2 can be fixed by attaching the KeepAlives directly to the OCALLFUNC node, so that we can insert the OpVarLive immediately after the OpStaticCall/etc.

I expect 3 will need to be fixed by wrapping the calls in a closure.

/cc @ianlancetaylor @aclements

**Comment by mdempsky** [comment]
Also for context, these most likely only affect `syscall.Syscall*` and Window's `syscall.(*Proc).Call` and `syscall.(*LazyProc).Call`, which probably aren't commonly (if ever) used in these ways. So the risk of this being a problem in practice is probably pretty low.

**Comment by mdempsky** [comment]
Apparently, we do use `defer syscall.Syscall` in some runtime tests:

    https://github.com/golang/go/blob/master/src/runtime/memmove_linux_amd64_test.go#L46
    https://github.com/golang/go/blob/master/src/runtime/race/race_windows_test.go#L33

but neither includes a `uintptr` conversion, so they're safe.

And `(*Proc).Call` uses `return Syscall`, but also without `uintptr` conversions:

    https://github.com/golang/go/blob/master/src/syscall/dll_windows.go#L144

I couldn't find any obvious at-risk calls within Google's Go code base.

**Comment by josharian** [comment]
Mostly unrelated, but: It would be nice if `defer runtime.KeepAlive(x)` was as efficient as inserting a keep-alive of x on every exit path. This would avoid having to manually rewrite `return f(x)` into `tmp := f(x); return tmp` in cgo wrapper code. I mention it only because the underlying implementation mechanism might be similar. Apologies for the hijack.

**Comment by aclements** [comment]
Is there anything preventing us from recognizing this pattern when we lower call ASTs to SSA and inserting the keep-alives then? I think this is similar to your suggestion, but I'm proposing to take this out of "order" entirely.

Case 3 is interesting. I think you're right that the only option may be to wrap it in a closure, since (at least for `go`), nothing we do in the calling function can keep the pointer live long enough.

**Comment by mdempsky** [comment]
@josharian That sounds like an interesting issue, but seems pretty different in scope from this one to me. I suspect it overlaps more significantly with the ideas we've had to optimize exactly-once defer statements.

@aclements We might be able to move all of the work into `(*state).call`. The only issue I can see with that is walk.go will have already rewritten the argument list into explicit OINDREGSP assignments, so it just might be a little clumsy piecing things back together.

**Comment by dr2chase** [comment]
See also: https://go-review.googlesource.com/c/go/+/114797
Moving call construction into ssa ought to make this easier.

**Comment by odeke-em** [comment]
>I'd like to revisit if/when we get that CL in, fixes should be much cleaner.

Hello @dr2chase, CL https://go-review.googlesource.com/c/go/+/114797 was merged in October 2018,  I am just paging you to let you know as per your comment above. Thanks.

**Comment by mdempsky** [comment]
https://play.golang.org/p/KEf2cpdL_mA demonstrates the go/defer issue. (From #38581, which I closed as duplicate of this.)

**Comment by cuonglm** [comment]
> https://play.golang.org/p/KEf2cpdL_mA demonstrates the go/defer issue. (From #38581, which I closed as duplicate of this.)

It's interesting that as of go1.15, the program now sometimes print ok for defer (just run it several times on the playground link).

**Comment by mdempsky** [comment]
@cuonglm Interesting observation. It looks like the "go" test occasionally fails too. It looks like calling `runtime.GC()` twice in a row makes the failure reliable: https://play.golang.org/p/a4Na2EBF7nu

**Comment by mdempsky** [comment]
@cuonglm I think you just need an expression like:

    before(uintptr(setup())) + after()

And then we want to make sure the value is still alive in `before`, but has been garbage collected in `after`.

For example, this appears to work:

```
package main

import (
	"runtime"
	"unsafe"
	"sync/atomic"
)

var done uint32

func setup() unsafe.Pointer {
	s := "ok"
	runtime.SetFinalizer(&s, func(p *string) { atomic.StoreUint32(&done, 1) })
	return unsafe.Pointer(&s)
}

//go:noinline
//go:uintptrescapes
func before(p uintptr) int {
	if atomic.LoadUint32(&done) != 0 {
		panic("GC early")
	}
	return 0
}

func after() int {
	if atomic.LoadUint32(&done) == 0 {
		panic("GC late")
	}
	return 0
}

func main() {
	_ = before(uintptr(setup())) + after()
}
```

**Comment by dr2chase** [comment]
I worry this test could easily be flaky; finalizers are run in another thread, with no particular guarantee of timeliness.

**Comment by cuonglm** [comment]
> I worry this test could easily be flaky; finalizers are run in another thread, with no particular guarantee of timeliness.

Yes, it’s flaky, buy we end up with different one https://github.com/golang/go/commit/afb5fca25a6f59e9045317727f6899a58471d5f0

**Comment by mdempsky** [comment]
@dr2chase Yeah, I don't think there's any good way at the moment to block until all pending, runnable finalizers have run. I've filed #41362 as what I think would be the most robust solution here, but I'm open to other suggestions.
