### ISSUE TITLE
cmd/vendor/.../pprof/internal/binutils: TestMachoFiles fails

### ISSUE THREAD

**Issue by hyangah** [golang/go#24508]
https://build.golang.org/log/1cbedd8b8b11d1baadcbfabcf8d8809ece5ab307

New failures caused by cl/101736
Trybot run didn't detect this early.

**Comment by ALTree** [comment]
Sigh. I suggest reverting, opening an issue upstream, and then we can re-vendor again when it's fixed. IIRC the darwin trybots are down, we can't afford having the all the 3 darwin builders down too.

**Comment by hyangah** [comment]
Strange. I can't reproduce the test failure on my mac.

**Comment by mvdan** [comment]
Filed upstream: https://github.com/google/pprof/issues/342

**Comment by mvdan** [comment]
Yes; I meant to send this today but got sidetracked.
