### ISSUE TITLE
Unsupported GOOS/GOARCH pair linux/arm on windows

### ISSUE THREAD

**Issue by lunny** [golang/go#24501]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows amd64

### What did you do?
cross compile raspberry pi on windows 10 / amd64

set GOOS=linux
set GOARCH=arm
set GOARM=7
set CGO_ENABLED=0
go build

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
compile successfully

### What did you see instead?
show `Unsupported GOOS/GOARCH pair linux/arm on windows`

**Comment by ianlancetaylor** [comment]
I don't see that message anywhere in the Go sources.  Are you certain that that is the exact output of `go build`?  What is the output of `go build -x`?  Thanks.

**Comment by lunny** [comment]
@ianlancetaylor I think it should be at 
https://github.com/golang/go/blob/9745eed4fd4160cfbf55e9dbbfa99aca5563b392/src/cmd/go/internal/work/action.go#L236

**Comment by lunny** [comment]
@ianlancetaylor found the reason. maybe I `set GOOS=linux ` it should be `set GOOS=linux` not with blank charactor. But maybe the compile should trim the space automatically? Thanks anyway.
