### ISSUE TITLE
runtime: document that SetCgoTraceback silently does nothing on non-linux/amd64

### ISSUE THREAD

**Issue by benesch** [golang/go#24518]
Based on my read of the source code, runtime.SetCgoTraceback is only supported on linux/amd64. Ideally it would fail loudly if called on an unsupported platform, but just documenting the limitation would be a step forward. (At least, I don't see this documented anywhere.)

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
`SetCgoTraceback` should be effective on any platform, in that it can permit stack tracebacks to show C code when that C code calls Go code and the Go code asks for a stack trace.  What is only implemented on linux/amd64, linux/ppc64le, and (for 1.11) freebsd/amd64 is collecting a C stack traceback from a signal handler.

**Comment by benesch** [comment]
> SetCgoTraceback should be effective on any platform, in that it can permit stack tracebacks to show C code when that C code calls Go code and the Go code asks for a stack trace. What is only implemented on linux/amd64, linux/ppc64le, and (for 1.11) freebsd/amd64 is collecting a C stack traceback from a signal handler.

Ah, I see. Regardless, I think my point stands: that seems like something worth documenting!
