### ISSUE TITLE
x/sys/unix: Adding GetsockoptLinger() and GetsockoptTimeval()

### ISSUE THREAD

**Issue by lyuxuan** [golang/go#24515]
Currently, in the x/sys/unix package, there are SetsockoptLinger() and SetsockoptTimeval() for setting the Linger and Timeout options, however, there is no corresponding getter for them. 

Due to the lack of getters, there's no viable way to get those socket options (i.e. linger and timeout), unless doing syscalls myself, which is not preferable.

**Comment by tklauser** [comment]
I don't think this needs to be a proposal, especially since it is concerning `x/sys/unix`. Feel free to send a CL adding these two functions.
