### ISSUE TITLE
constant 18446744073709551615 overflows int

### ISSUE THREAD

**Issue by gercinojr** [golang/go#24523]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
yes -> go1.10 is the last release 

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gercino/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gercino/PROJETOS/GO"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build075735587=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

package main

import (
    "math"
    "fmt"
)

func main() {
    var n uint64 = math.MaxUint64   // line A
    //n := math.MaxUint64                     // line B
    fmt.Println(n)
}

### What did you expect to see?

If I uncomment line A and comment line B: 
go run test.go 
18446744073709551615

If I comment line A and uncomment line B:
go run test.go 
./test.go:10:7: constant 18446744073709551615 overflows int

This error also occurs in the https://play.golang.org/

**Comment by ALTree** [comment]
`math` constants are untyped and by default they are interpreted as `int` (line B). As you found out, you'll need to explicitly assign the `uint64` type (line A).

There's a proposal to change this for go2:  #23087. For now, this is WAI, so I'm closing this issue.

**Comment by kardianos** [comment]
Int is used as the default type from an "untyped" constant. The short declaration would work it you cast the right to a uint64 too. The var version would start failing if you remove the uint64 type.

This is working as expected.
