### ISSUE TITLE
regexp: document that in *All if n < 0 means return all matches

### ISSUE THREAD

**Issue by odeke-em** [golang/go#24526]
I was just working on a simple login router and while examining regexp.FindAllString, I had to use the common knowledge that usually when you ask for n<0, that means return all the matches. However, this isn't intuitive to everyone. Perhaps let's document it.

<img width="909" alt="screen shot 2018-03-25 at 2 45 03 pm" src="https://user-images.githubusercontent.com/4898263/37879778-3250fa64-303b-11e8-8b69-c2133d73b3ec.png">

Sharing this with my other team members who might not be experienced would definitely lead to confusion as in https://play.golang.org/p/5J4Me7dgNML

**Comment by odeke-em** [comment]
The package doc for All as recommended in the comments says that `if n >=0` it returns at most n matches, but doesn't say anything for `if n<0`
<img width="806" alt="screen shot 2018-03-25 at 2 47 44 pm" src="https://user-images.githubusercontent.com/4898263/37879806-98922fdc-303b-11e8-8906-c2f51993ed33.png">

**Comment by jimmyfrasche** [comment]
cc @rsc and @matloob by golang.org/s/owners
