### ISSUE TITLE
x/vgo: wrong error when x/go.mod tag v2.0.0 does not say module "x/v2"

### ISSUE THREAD

**Issue by kybin** [golang/go#24522]
I am developing a program which uses `russross/blackfriday` and of course it does not support vgo yet, so I tried fork and add go.mod myself for fun.

Because blackfriday reaches v2.0.0 and developed in v2 branch, I had to checkout to v2 branch.
I added go.mod file there but I didn't put version to it's module path by mistake.
So the file started with `module "github.com/kybin/blackfriday"` not `module "github.com/kybin/blackfriday/v2".`
Then I tagged it as v2.0.1.

When I ran `vgo get -u` from my repository, it panicked with `vgo: github.com/kybin/blackfriday/v2 v2.0.1: missing go.mod`. 
It confuses me because I know the file exists.

I checked vgo source and found `modfetch.codeRepo.findDir` returns wrong error when the module path does not have version info.

It would be better the error message is something like `go.mod's module path is not matched with it's tag version`.

Thank you.

**Comment by rsc** [comment]
I agree, the error should be fixed.

**Comment by rsc** [comment]
Thanks for the great explanation. I sent https://golang.org/cl/122399 to clear up this situation.
