### ISSUE TITLE
net/http: use top-level font media type in sniffer

### ISSUE THREAD

**Issue by agnivade** [golang/go#24524]
[RFC 8081](https://tools.ietf.org/html/rfc8081) declares a top level font media type for all types of fonts.

The same has been incorporated in https://github.com/whatwg/mimesniff/issues/23. Should we move too ?

The changes would require updating the following mime types - 

Obsolete | New
-- | --
application/font-ttf | font/ttf
application/font-cff | font/collection
application/font-off | font/otf
application/font-sfnt | font/sfnt
application/font-woff | font/woff
application/font-woff2  | font/woff2

/cc @bradfitz

**Comment by bradfitz** [comment]
Sure. If it doesn't break any browser's font parsing, but from that other bug it sounds like it doesn't.
