### ISSUE TITLE
How to generate map file or symbol file on windows

### ISSUE THREAD

**Issue by stillwarter** [golang/go#24520]
On linux, I can use "go tool nm" to get symbol file.
But on windows, it returns an error "cmd/go: unsupported GOOS/GOARCH pair windows/386".
It seems like nm is not supported on windows.

**Comment by alexbrainman** [comment]
@stillwarter it works for me:
```
c:\>go tool nm %GOROOT%\bin\go.exe | sed -n 1,10p
  90e9d4 T $f32.00000001
  90e9d8 T $f32.358637bd
  90e9dc T $f32.3f800000
  90e9e0 T $f32.4b189680
  90e9e4 T $f32.6258d727
  90e9e8 T $f32.7f800000
  90e9ec T $f32.80000000
  90e9f0 T $f32.80000001
  90e9f4 T $f32.cb189680
  90e9f8 T $f32.ff800000

c:\>
```

How can I reproduce your problem?

Alex

**Comment by stillwarter** [comment]
It looks my problem. I will close it.
