### ISSUE TITLE
net/http: Send 410 Gone client error with http.Error()

### ISSUE THREAD

**Issue by qboot** [golang/go#24530]
Hello! 

First, thanks for all your work, it's amazing.

I'm trying to properly send a `410 Gone` response with the `net/http` package.

I would like to do something like this `http.Error(w, "", http.StatusGone)`.

But after reading the `http.Error()` function code [here](https://github.com/golang/go/blob/master/src/net/http/server.go#L1957) we can see that the error response is written with `fmt.Fprintln()` which add a new line at the end and make the `Content-Length` header to be `1` instead of `0`.

Is there a particular reason here to not just use `fmt.Fprint()` ?

For now, I simply use:
```go
w.WriteHeader(http.StatusGone)
fmt.Fprint(w, "")
```

But it would be cleaner if I can just call the `http.Error()` which seems to be intended for this purpose.
WDYT ?

**Comment by agnivade** [comment]
I think that would be considered a breaking change. Unit tests will start to fail and clients expecting a newline at the end will break. 

If you are concerned about the `Content-Length` header, no need to even make the `fmt.Fprint` call. Just do a `WriteHeader` and return.

**Comment by qboot** [comment]
Thanks @agnivade for the explanation 👍.
Indeed `WriteHeader` then return is sufficient for my concern.
