### ISSUE TITLE
os: TestDevNullFile failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#24534]
CL [102457](https://golang.org/cl/102457) added TestDevNullFile. This test is failing on Plan 9.

```
--- FAIL: TestDevNullFile (0.00s)
	os_test.go:1813: f.Stat("/dev/null"): wrong file mode "Drw-rw-rw-": ModeCharDevice is not set
	os_test.go:1813: Stat("/dev/null"): wrong file mode "Drw-rw-rw-": ModeCharDevice is not set
	os_test.go:1813: Lstat("/dev/null"): wrong file mode "Drw-rw-rw-": ModeCharDevice is not set
FAIL
FAIL	os	1.586s
```

See https://build.golang.org/log/add543f3681f4c7f89e62c0d40c8eebfafd71b72

**Comment by alexbrainman** [comment]
Sorry for breaking the build. I looked at plan9-386 log

https://build.golang.org/log/ce0f0c918a1dc458c6f5913e1259f80f53f0f34d

and I did not see TestDevNullFile failure, so I assumed plan9 is OK. I will send a CL to adjust TestDevNullFile.

Alex

**Comment by 0intro** [comment]
Don't worry, I'll send a CL.

**Comment by alexbrainman** [comment]
I also need to fix Solaris.

Alex

**Comment by 0intro** [comment]
For Plan 9 specifically, I think we can change Stat to set ModeCharDevice on files served by the console device, like we did for ModeDevice. I'll propose a CL that does that.

I'll let you change the TestDevNullFile test for Solaris.

**Comment by 0intro** [comment]
I propose CL [102424](https://golang.org/cl/102424), but if that's not a good solution we'll just skip the ModeCharDevice test for Plan 9 in TestDevNullFile.

**Comment by alexbrainman** [comment]
> but if that's not a good solution we'll just skip the ModeCharDevice test for Plan 9 in TestDevNullFile.

Sounds like a plan.

I would just remove ModeCharDevice test in TestDevNullFile altogether. I have added ModeCharDevice test in CL 102456, because windows code had ModeCharDevice set for DevNull. I don't even know if that is intended. But if you think ModeCharDevice makes sense for DevNull, I am happy for you to change plan9 code.

Alex
