### ISSUE TITLE
x/vgo: report error when command line explicitly names excluded version

### ISSUE THREAD

**Issue by vedhavyas** [golang/go#24549]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/vedhavyas/Projects/Go/bin"
GOCACHE="/Users/vedhavyas/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vedhavyas/Projects/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k9/b4tsxqr95bz40d3y15b98m2h0000gp/T/go-build239118410=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
1. added an exclude directive to go.mod - `exclude "github.com/gorilla/mux" v1.6.0`
2. `vgo get github.com/gorilla/mux@v1.6.0`

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Some kind of error message about specific version being excluded

### What did you see instead?
`vgo` silently exists with return code `0`

**Comment by rsc** [comment]
I agree that if you ask explicitly on the command line for that version, you should get some kind of error. What probably happened is you got v1.6.1, but since the command line said v1.6.0 I think that substitution should have been reported.
