### ISSUE TITLE
runtime: support for cgo pprof is currently heavily Linux-dependent

### ISSUE THREAD

**Issue by tenortim** [golang/go#24545]
### What version of Go are you using (`go version`)?
go version go1.10 freebsd/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
freebsd/amd64

As suggested in CL 93875 "After this CL is in it would be worth seeing whether testCgoPprof in runtime/crash_test.go can be enabled for FreeBSD.", I have been looking into what it would take to enable the test. What I'm finding is that all of the cgo pprof tests fail and when I look at the pprof output, it's missing the header that details the executable and libraries, which causes the profile to be incomplete/incorrect.

Following the code, readMapping in runtime/pprof/proto.go is using /proc/self/maps which is Linux-specific. I'm looking for thoughts on how this might be extended to other platforms. It's not obvious that there's any portable equivalent here.

On FreeBSD there are at least two options. Code to parse /proc/curproc/map would be very easy to write based on the existing code, but the downside is that procfs isn't mounted by default on FreeBSD. The libprocstat code would work everywhere, but is sysctl-based and would require a fair bit more work, at least to convert it to Go code rather than relying on an external library.

On OSX, it's completely different again. There are Mach calls to get the info. Sample code can be found at e.g. http://www.newosxbook.com/src.jl?tree=listings&file=12-1-vmmap.c

Anyway, I'm curious if anybody has any ideas or opinions about this.

**Comment by andybons** [comment]
This seems like a better discussion to start on golang-dev@. You can then put together a proposal and refine this issue with concrete plans.

**Comment by ianlancetaylor** [comment]
CC @rauls5382

**Comment by tenortim** [comment]
Thank you @andybons starting a thread in golang-dev.

**Comment by mvdan** [comment]
Closing old issues that still have the WaitingForInfo label where enough details to investigate weren't provided. Feel free to leave a comment with more details and we can reopen.
