### ISSUE TITLE
net/url: add a "SetQuery" helper function

### ISSUE THREAD

**Issue by HaraldNordgren** [golang/go#24552]
Hi, I want to create a new helper function called "SetQueryParameters" in net/url. Is this something the community wants too?

Already from my first experience with Go, I was confused about the round-about way that we set query parameters:

```go
v := u.Query()
v.Set("a", 1)
v.Set("b", 2)
u.RawQuery = v.Encode()
```

So instead we could have a helper function

```go
u.SetQueryParameters(url.Values{
	"a": {"1"},
	"b": {"2"},
})
```

to hopefully make life a tiny bit easier for me and other developers.

**Comment by HaraldNordgren** [comment]
Possible implementation: https://github.com/golang/go/pull/24528

**Comment by mvdan** [comment]
It seems to me like your second piece of code could be:

```
u.RawQuery = url.Values{
	"a": {"1"},
	"b": {"2"},
}.Encode()
```

What are you trying to solve here? If it's less code, I think both ways to do it currently are fine. If it's about the code being confusing, then perhaps better documentation or an example could help. Or perhaps even a proposal to improve a future version of net/url, such as replacing `RawQuery` with something else.

**Comment by HaraldNordgren** [comment]
I think the problem with using RawQuery and Encode() is the amount of voodoo involved.

It feels strange to me that the _normal_ way to construct a URL with query parameters is to assign anything called `Raw…`. I would expect the internals to handle the "raw" stuff.

So I was trying to take something that confused and bewildered me about Go when I started writing it professionally a year ago (and still looks odd to me), and then simplify it for the next guy.

**Comment by ianlancetaylor** [comment]
CC @bradfitz @tombergan

**Comment by bradfitz** [comment]
There are no existing Setter functions on `net/url.(*URL)`, so I'm somewhat reluctant to start.

But if we added one, I'd name it `SetQuery`, to match the naming of https://golang.org/pkg/net/url/#URL.Query

And the implementation could be simpler. I replied on https://go-review.googlesource.com/c/go/+/102476

/cc @bcmills

**Comment by bcmills** [comment]
I don't have a strong opinion on whether we should add a `SetQuery` method, but there is a strange asymmetry between `RawQuery` and `RawPath`. If one assigns to `RawPath` without `Path`, it appears that the `EscapedPath` method will ignore it. That seems to support @HaraldNordgren's unease at setting the `RawQuery` field, even though it is safe to do.

That suggests a slightly broader change to bring `Query` and `Path` closer to parallel: two setters instead of one.

```go
func (u *URL) SetEscapedPath(rawPath string) error {
	path, err := PathUnescape(path)
	if err != nil {
		return err
	}
	u.RawPath = rawPath
	u.Path = path
	return nil
}

func (u *URL) SetQuery(Values) {
	[…]
}
```

**Comment by HaraldNordgren** [comment]
@bcmills Should there also be a `path` parameter to the `SetEscapedPath` function? I'm not exactly sure I follow the idea, but it seems like the underlying problem remains if you have to pass anything "raw" to the function to make it work.

**Comment by rsc** [comment]
Please, let's not start designing new API for url.URL. The URL struct is not set up for incremental modification. It's meant for _reading_ URLs, not to be a kitchen sink for writing them. There's a reason that APIs that consume URLs typically take type string.

**Comment by bradfitz** [comment]
Yeah, I'd prefer we keep URL as it is, without any setters.

We can rethink the URL type for Go 2, perhaps.
