### ISSUE TITLE
bytes: double call to tryGoByReslice in bytes.Buffer when writing

### ISSUE THREAD

**Issue by jgimeno** [golang/go#24550]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

Checking the Write and WriteString made me realize that we try to grow by reslicing first, but if it is not possible we call grow. But the grow function tries again to grow by reslice, making a second call to reslice. I think in this case it is not needed to call:

	m, ok := b.tryGrowByReslice(len(p))

Is enough to call directly grow function.

### What did you expect to see?
Call only grow function.

### What did you see instead?
Double call to tryGrowByReslice.

**Comment by jgimeno** [comment]
I can work on removing this if needed.

**Comment by ianlancetaylor** [comment]
This is intentional because of the current compiler's implementation of function inlining.  See #17857 and https://golang.org/cl/42813.
