### ISSUE TITLE
x509

### ISSUE THREAD

**Issue by paperx123** [golang/go#24554]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by davecheney** [comment]
Incomplete.

**Comment by adamdecaf** [comment]
@paperx123 you'll probably want this patch in your dependencies. 

https://github.com/google/certificate-transparency-go/commit/391726f8973ddb3521ab1a462bd55a35c6f67f0b

**Comment by paperx123** [comment]
@adamdecaf   thanks!  Indeed...
