### ISSUE TITLE
x/sys/windows/svc: servicemain argv pointer truncated

### ISSUE THREAD

**Issue by zhangyoufu** [golang/go#24575]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows x64

### What did you do?
review the code

### What did you expect to see?
``` go
// func servicemain(argc uint32, argv **uint16)
TEXT ·servicemain(SB),7,$0
	MOVL	CX, ·sArgc(SB)
	MOVQ	DX, ·sArgv(SB)
```

### What did you see instead?
``` go
// func servicemain(argc uint32, argv **uint16)
TEXT ·servicemain(SB),7,$0
	MOVL	CX, ·sArgc(SB)
	MOVL	DX, ·sArgv(SB)
```

**Comment by alexbrainman** [comment]
I am pretty sure this is a bug. But I would like to write a test before I fix this. I will try and do this when I have time.

Thank you.

Alex

**Comment by zhangyoufu** [comment]
@gopherbot please consider this for backport to 1.10.3

**Comment by katiehockman** [comment]
@alexbrainman @zhangyoufu Can you please clarify why this should be considered for backport? Per https://github.com/golang/go/wiki/MinorReleases it should be either a regression, security issue, or serious problem with no workaround.

**Comment by alexbrainman** [comment]
> Can you please clarify why this should be considered for backport?

I do not think this fix needs to be backported. How do we backport golang.org/x/sys repo?

Alex

**Comment by katiehockman** [comment]
Thanks, I'll close the backport issue then.

For future backports, the process is the same as it is for the go repo. It looks like golang.org/x/sys has a go1.11 release branch (https://go.googlesource.com/sys), so we would just cherry pick to that branch per the instructions here: https://github.com/golang/go/wiki/MinorReleases#making-cherry-pick-cls

**Comment by alexbrainman** [comment]
> For future backports, the process is the same as it is for the go repo. It looks like golang.org/x/sys has a go1.11 release branch

Fair enough, I did not know that. It is not surprising, I live on bleeding edge :-)

Alex
