### ISSUE TITLE
x/mobile: gomobile iOS bind error unknown GOARCH

### ISSUE THREAD

**Issue by janke99** [golang/go#24571]
### What version of Go are you using (`go version`)?
go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
mac mini
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jane/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jane/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9m/d0cqs4fj04j3sj8g28t40mv80000gn/T/go-build227436364=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

go get golang.org/x/mobile/cmd/gomobile
gomobile init
gomobile bind -target=ios golang.org/x/mobile/example/bind/hello

get this error:----

panic: unknown GOARCH: ""

goroutine 1 [running]:
main.archClang(0x0, 0x0, 0x1, 0x13050c2)
	/Users/jane/go/src/golang.org/x/mobile/cmd/gomobile/env.go:199 +0x27c
main.goIOSBind(0xc42018c260, 0x19, 0xc42019c020, 0x1, 0x1, 0x1, 0x0)
	/Users/jane/go/src/golang.org/x/mobile/cmd/gomobile/bind_iosapp.go:61 +0x85f
main.runBind(0x14a5ec0, 0x0, 0x0)
	/Users/jane/go/src/golang.org/x/mobile/cmd/gomobile/bind.go:134 +0x60a
main.main()
	/Users/jane/go/src/golang.org/x/mobile/cmd/gomobile/main.go:73 +0x34e

**Comment by lenlee** [comment]
I also encounter this problem, cannot resolve.

**Comment by eliasnaur** [comment]
I can't reproduce the panic. Are your version of golang.org/x/mobile up to date? For example, try `go get -u golang.org/x/mobile/cmd/gomobile` (with the -u flag) and bind again.

**Comment by lenlee** [comment]
@eliasnaur  Thanks for your help, i have solved this problem. @janke99 @odeke-em  The reason is that our pc donnot have xcode. Xcode is ios develop IDE. I downloaded it and this problem is solved. Read this:  https://godoc.org/golang.org/x/mobile/cmd/gomobile

**Comment by janke99** [comment]
@lenlee @eliasnaur  Thanks for your help, i have solved this problem
