### ISSUE TITLE
cmd/go: test cache does not detect environment variables used in TestMain

### ISSUE THREAD

**Issue by loderunner** [golang/go#24589]
### What version of Go are you using (`go version`)?

* go1.10 darwin/amd64
* go1.10 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

* GOOS="darwin" GOARCH="amd64"
* GOOS="linux" GOARCH="amd64"

### What did you do?

I use a `TestMain` function to perform setup and teardown in my test suites. Setup or teardown often looks up environment variables, as an easy way to parameterize tests in CI.

```go
package main

import (
	"os"
	"testing"
)

var fail bool

func TestMain(m *testing.M) {
	setUp()        // Setup for tests
	res := m.Run() // Run the actual tests
	tearDown()     // Teardown after running the tests
	os.Exit(res)
}

func setUp() {
	fail = (os.Getenv("FAIL_TEST") == "y")
}

func tearDown() {}

func TestExample(t *testing.T) {
	if fail {
		t.FailNow()
	}
}
```

### What did you expect to see?

```
$ go test .
ok  	_/Users/chrales/Desktop	0.008s
$ FAIL_TEST=y go test .
--- FAIL: TestExample (0.00s)
FAIL
FAIL	_/Users/chrales/Desktop	0.008s
```

### What did you see instead?

```
$ go test .
ok  	_/Users/chrales/Desktop	0.007s
$ FAIL_TEST=y go test .
ok  	_/Users/chrales/Desktop	(cached)
```

### Additional info

Environment variables looked up from the test itself are added to the cache. This means that if I call `setUp` and `tearDown` from `TestExample`, I get the expected behavior. However, since I am using `FailNow`, if the test fails, `tearDown` does not get called.

**Comment by mvdan** [comment]
This seems to be because `testlog`, the internal package that takes care of logging all of the calls like `os.Open` and `os.Getenv`, is set up as part of `m.Run`. And as you can see, one can run code as part of `TestMain` before that.

/cc @rsc

**Comment by mvdan** [comment]
From a quick look, it seems like we could move that to `MainStart`, which sets up the `*testing.M`. That way, once the user's `TestMain` runs, `testlog` has already been set up.

Though I'm not sure if this is a good solution, so marking as needing decision. Happy to work on a small patch if the solution seems fine.

**Comment by ianlancetaylor** [comment]
I  don't think we need a decision here as such.  If it's straightforward to start the testlog in `TestMain`, we should do that.

**Comment by mvdan** [comment]
I'll mail a change later today, and see if anything breaks.

**Comment by mvdan** [comment]
On second thought, moving the code to `MainStart` isn't as simple. The code depends on flags, so we'd have to move `flag.Parse()` too. But if we do that, we'd break `TestMain` funcs out there that call it too. Will wait to hear Russ's opinion.

**Comment by ianlancetaylor** [comment]
I think this is basically a dup of #24122.  Closing.
