### ISSUE TITLE
net: deflake more tests using backoff

### ISSUE THREAD

**Issue by josharian** [golang/go#24580]
In https://golang.org/cl/102397, I added some retry with backoff loops to some flaky net tests. It appears to have helped the build dashboard. I mentioned in the commit message that we could use the same approach for other flaky tests that we see. Looking at build.golang.org, it looks like TestLookupCNAME could use the same treatment.

This would be a great starter fix for someone looking to contribute. Or maybe @odeke-em? :)

**Comment by josharian** [comment]
Hmmm. Actually, looking at the dashboard, it appears that when the network gets really flaky, enough of these backoffs trigger that the package net tests time out instead. So it helps a little...but not enough. Sigh. We could increase the timeout for package net, perhaps? Better a slow pass than a fast flaky failure.

@bradfitz any opinions?

**Comment by mvdan** [comment]
If these individual tests take very long due to a flaky network, I wonder if a higher `-parallel` number would help. That is, making it so more tests that need to retry multiple times can run at once.

**Comment by mikioh** [comment]
The back off approach is fine. I'd also like to see some isolation between tests using the infrastructure and tests using the local system. FWIW, I have a plan to improve testing on DNS stub resolver after landing CL 102875, perhaps in Go 1.12 development cycle. It will use mock DNS servers for testing on connection setup and RR lookup APIs and will drop unnecessary dependence on the infrastructure.

**Comment by josharian** [comment]
@feliixx thanks for working on this. Are you up for diagnosing and fixing the data race?
