### ISSUE TITLE
cmd/vet: gives errors about import paths when used on test files in Windows

### ISSUE THREAD

**Issue by veqryn** [golang/go#24587]
### What version of Go are you using (`go version`)?
go version go1.10 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\cduncan\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\cduncan\workspace\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-IC:\Users\cduncan\workspace\programs\oracle\windows\instantclient_12_1\sdk\include
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-LC:\Users\cduncan\workspace\programs\oracle\windows\instantclient_12_1 -loci
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\cduncan\AppData\Local\Temp\go-build922471030=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I have a file and some tests.
All third party code has been vendored into the vendor directory using go `dep` version v0.4.1
The tests have these imports:
```go
import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"runtime/debug"
	"sync"
	"testing"
	"time"

	"github.com/ReturnPath/ecm/lib/util"
	"github.com/ReturnPath/ecm/lib/vendor_mocks/aws/mock_firehoseiface"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/firehose"
	"github.com/elodina/go-avro"
	"github.com/golang/mock/gomock"
	"github.com/valyala/fasthttp"
)
```

### What did you expect to see?
With Golang 1.9.2 (my previous version), `go vet` gave me an 'all clear'.
The files and the tests also compile and run perfectly fine.

### What did you see instead?
```powershell
C:\Users\cduncan>go vet C:\Users\cduncan\workspace\go\src\github.com\ReturnPath\ecm\services\pixel_server\pixel_server_test.go
# github.com\ReturnPath\ecm/vendor/github.com/aws/aws-sdk-go/aws
workspace\go\src\github.com\ReturnPath\ecm\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: import path contains backslash; use slash: "github.com\\ReturnPath\\ecm/vendor/github.com/aws/aws-sdk-go/aws/awserr"
workspace\go\src\github.com\ReturnPath\ecm\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: cannot import "github.com\\ReturnPath\\ecm/vendor/github.com/aws/aws-sdk-go/aws/credentials" due to version skew - reinstall package (bad package path "github.com\\ReturnPath\\ecm/vendor/github.com/aws/aws-sdk-go/aws/awserr" for package awserr)
# github.com\ReturnPath\ecm/vendor/github.com/valyala/fasthttp
workspace\go\src\github.com\ReturnPath\ecm\vendor\github.com\valyala\fasthttp\compress.go:10:2: import path contains backslash; use slash: "github.com\\ReturnPath\\ecm/vendor/github.com/klauspost/compress/flate"
workspace\go\src\github.com\ReturnPath\ecm\vendor\github.com\valyala\fasthttp\compress.go:10:2: cannot import "github.com\\ReturnPath\\ecm/vendor/github.com/klauspost/compress/gzip" due to version skew - reinstall package (bad package path "github.com\\ReturnPath\\ecm/vendor/github.com/klauspost/compress/flate" for package flate)
```

Also to note: `go tool vet` doesn't return anything.  I'm still not sure what the difference between them is.

And go vet on the non-test file (`go vet C:\Users\cduncan\workspace\go\src\github.com\ReturnPath\ecm\services\pixel_server\pixel_server.go`) returns an all clear

**Comment by veqryn** [comment]
`go vet` on test files also fails to find methods in other test files in the same directory and package:

```
# command-line-arguments
services\pixel_server\pixel_server_benchmark_test.go:30:62: undefined: setup
services\pixel_server\pixel_server_benchmark_test.go:45:3: undefined: Must
```
^ Those methods exist in a different test file in the same dir/package.  All my tests in all these files run and succeed perfectly fine.

**Comment by mvdan** [comment]
Is there a good and easy way to reproduce and test fixes for these things while on a different operating system? Other than running a virtual machine, that is.

**Comment by ianlancetaylor** [comment]
Is there a way that we can recreate the problems ourselves?

Are the vet errors correct?  Or do the files contain forward slashes although vet is complaining about backslashes?

**Comment by veqryn** [comment]
Sorry for not posting a short way to reproduce this, I did not have the time yesterday but wanted to put the bug in before I forgot.

Here is a short way to reproduce, even if it is a bit contrived:

Create the following files, then also download `github.com/aws/aws-sdk-go` to a `vendor` directory at or above the same level as these files.

`vet_bug.go`
```go
package vet_bug

func Add(a, b int) int {
	return a + b
}
```

`vet_bug_test.go`
```go
package vet_bug

import (
	"testing"
)

func TestAdd(t *testing.T) {
	inouts := []struct {
		a int
		b int
		r int
	}{
		{a: 0, b: 0, r: 0},
		{a: 1, b: 1, r: 2},
		{a: 3, b: 5, r: 8},
	}

	for _, inout := range inouts {
		AssertEqual(t, inout.r, Add(inout.a, inout.b))
	}
}
```

`util_test.go`
```go
package vet_bug

import (
	"fmt"
	"testing"

	"github.com/aws/aws-sdk-go/aws"
)

func AssertEqual(tb testing.TB, expected, actual int) {
	tb.Helper()

	// Pointless, but gives us an error in `go vet`
	config := aws.Config{}
	fmt.Println(config)

	if expected != actual {
		tb.Error("Expected:", expected, "; Got:", actual)
	}
}
```

When running `go vet` on the `util_test.go` file, I get:
```
# command-line-arguments
src\vet_bug\vet_bug_test.go:19:3: undefined: AssertEqual
src\vet_bug\vet_bug_test.go:19:27: undefined: Add
```

When running `go vet` on the `vet_bug_test.go` file, I get:
```
# github.com\veqryn\personal/vendor/github.com/aws/aws-sdk-go/aws
vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: import path contains backslash; use slash: "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr"
vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: cannot import "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/credentials" due to version skew - reinstall package (bad package path "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr" for package awserr)
```

Here are the contents of the file it is referencing: `github.com/aws/aws-sdk-go/aws/config.go`
```go
package aws

import (
	"net/http"
	"time"

	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/endpoints"
)
```

The tests pass.
The vet errors are obviously wrong, on both counts.

I would also love if someone could tell me what the difference is between `go vet` and `go tool vet`, and why both exist?

**Comment by ianlancetaylor** [comment]
The difference between `go vet` and `go tool vet` is documented at https://golang.org/cmd/vet (jump down to the bottom).  In general you will be fine if you forget that `go tool vet` exists.

After you follow the instructions you describe, what does the start of vendor\github.com\aws\aws-sdk-go\aws\config.go look like on your system?  On my system it does not contain any backslashes:

```Go
package aws

import (
	"net/http"
	"time"

	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/endpoints"
)
```

When you say "run go vet on the file x.go" what precisely are you typing?

**Comment by veqryn** [comment]
I have the exact same as you for the top portion of that config file.
I am running `go vet util_test.go`

Here is git-bash terminal showing the issue:
```bash
MinGW 04:40:14 ~/workspace/go/src/github.com/veqryn/personal/src/vet_bug$ go vet ./vet_bug_test.go
# command-line-arguments
.\vet_bug_test.go:19:3: undefined: AssertEqual
.\vet_bug_test.go:19:27: undefined: Add
MinGW 04:40:25 ~/workspace/go/src/github.com/veqryn/personal/src/vet_bug$ go vet ./util_test.go
# github.com\veqryn\personal/vendor/github.com/aws/aws-sdk-go/aws
..\..\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: import path contains backslash; use slash: "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr"
..\..\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: cannot import "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/credentials" due to version skew - reinstall package (bad package path "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr" for package awserr)
```

Here is good old cmd.exe showing the same issue:
```powershell
C:\Users\cduncan\workspace\go\src\github.com\veqryn\personal\src\vet_bug>go vet .\vet_bug_test.go
# command-line-arguments
.\vet_bug_test.go:19:3: undefined: AssertEqual
.\vet_bug_test.go:19:27: undefined: Add

C:\Users\cduncan\workspace\go\src\github.com\veqryn\personal\src\vet_bug>go vet .\util_test.go
# github.com\veqryn\personal/vendor/github.com/aws/aws-sdk-go/aws
..\..\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: import path contains backslash; use slash: "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr"
..\..\vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: cannot import "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/credentials" due to version skew - reinstall package (bad package path "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/awserr" for package awserr)

C:\Users\cduncan\workspace\go\src\github.com\veqryn\personal\src\vet_bug>
C:\Users\cduncan\workspace\go\src\github.com\veqryn\personal\src\vet_bug>cat ..\..\vendor\github.com\aws\aws-sdk-go\aws\config.go
package aws

import (
        "net/http"
        "time"

        "github.com/aws/aws-sdk-go/aws/credentials"
        "github.com/aws/aws-sdk-go/aws/endpoints"
)

// UseServiceDefaultRetries instructs the config to use the service's own
```

**Comment by ianlancetaylor** [comment]
In Go 1.10, you generally should not run `go vet file.go`.  You should run `go vet` on a package.  If you want to run vet on a single file, use `go tool vet file.go`.

But I am at a loss as to why you are seeing what you are seeing.  Can anyone else recreate the problem?

**Comment by veqryn** [comment]
If you run go vet on a package instead of a file, will it vet your test files too?

I believe this error would only occur on Windows, since it is related to the slash vs backslash.  go vet did work without these errors on 1.9.x
`cannot import "github.com\\veqryn\\personal/vendor/github.com/aws/aws-sdk-go/aws/credentials"`

**Comment by ianlancetaylor** [comment]
> If you run go vet on a package instead of a file, will it vet your test files too?

Yes.

**Comment by alexbrainman** [comment]
If I follow instructions as per https://github.com/golang/go/issues/24587#issuecomment-377388006 I can reproduce the problem:
```
c:\Users\Alex\dev\src\issue\go\24587>dir
 Volume in drive C has no label.
 Volume Serial Number is 9872-A123

 Directory of c:\Users\Alex\dev\src\issue\go\24587

02/04/2018  05:39 PM    <DIR>          .
02/04/2018  05:39 PM    <DIR>          ..
02/04/2018  05:35 PM               328 util_test.go
02/04/2018  05:39 PM    <DIR>          vendor
02/04/2018  05:35 PM                58 vet_bug.go
02/04/2018  05:35 PM               275 vet_bug_test.go
               3 File(s)            661 bytes
               3 Dir(s)  395,254,607,872,872,456 bytes free

c:\Users\Alex\dev\src\issue\go\24587>go vet util_test.go
# issue\go\24587/vendor/github.com/aws/aws-sdk-go/aws
vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: import path contains backslash; use slash: "issue\\go\\24587/vendor/github.com/aws/aws-sdk-go/aws/awserr"
vendor\github.com\aws\aws-sdk-go\aws\config.go:7:2: cannot import "issue\\go\\24587/vendor/github.com/aws/aws-sdk-go/aws/credentials" due to version skew - reinstall package (bad package path "issue\\go\\24587/vendor/github.com/aws/aws-sdk-go/aws/awserr" for package awserr)

c:\Users\Alex\dev\src\issue\go\24587>
```

I did not have time to investigate why this is happening.

Alex

**Comment by ianlancetaylor** [comment]
The error messages `import path contains backslash` is coming from the compiler, of all things.  I do not know why the compiler would be seeing backslash import paths when invoked via `go vet`, when presumably it does not see them when invoked via `go build` or `go test`.  It might possibly be interesting to see the output of `go vet -x`.  But I suspect that this will need to be debugged by somebody on a WIndows system.

**Comment by ianlancetaylor** [comment]
Optimistically closing as fixed based on previous comment.
