### ISSUE TITLE
access: may-start-trybots and go-approvers

### ISSUE THREAD

**Issue by myitcv** [golang/go#24596]
Whilst I wouldn't class myself a full-time contributor, I have tried to contribute here and there.

With the Github access I suspect my main contribution initially will be to help garden issues (close them where I currently cannot, e.g. https://github.com/golang/go/issues/24573, relabel etc)

With the Gerrit access I'd be looking to restart trybots (for example in the CL https://go-review.googlesource.com/c/go/+/103415)

Thanks for considering my request.

**Comment by myitcv** [comment]
Just for the avoidance of doubt, the "go-approvers" request (in the title) is a reference to the Github access group: https://github.com/golang/go/wiki/GithubAccess#editors

**Comment by ianlancetaylor** [comment]
CC @andybons @bradfitz

**Comment by bradfitz** [comment]
SGTM. @andybons, can you add Paul?

**Comment by andybons** [comment]
Done!

**Comment by myitcv** [comment]
Thanks @andybons and @bradfitz
