### ISSUE TITLE
x/build/version: 1.10.1: download failed: no binary release of 1.10.1

### ISSUE THREAD

**Issue by yansal** [golang/go#24597]
### What did you do?

```bash
$ go get -u golang.org/x/build/version/1.10.1
$ $GOPATH/bin/1.10.1 download
```

### What did you expect to see?

The file being downloaded

### What did you see instead?

```
1.10.1: download failed: no binary release of 1.10.1 for linux/amd64 at https://storage.googleapis.com/golang/1.10.1.linux-amd64.tar.gz
```

I suspect this is due to the package being named `1.10.1` instead of `go1.10.1`, as it is possible to download https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz

**Comment by FiloSottile** [comment]
@yansal Thanks for reporting this. It should be fixed now if you use `golang.org/x/build/version/go1.10.1` instead. Let us know if that still doesn't work.
