### ISSUE TITLE
cmd/go: linker parameter -v is not whitelisted

### ISSUE THREAD

**Issue by prog8** [golang/go#24593]
It seems "-v" is not whitelisted in linker parameters https://github.com/golang/go/commit/1dcb5836ad2c60776561da2923c70576ba2eefc6

It is sometimes useful to see what is going on underneath

**Comment by mvdan** [comment]
Have you tried with the latest version of Go, i.e. master? More flags have been added since 1.10.

**Comment by prog8** [comment]
Actually, I didn't try the latest Go but I went through the history of this file and didn't find anything that would give me a hope that it works now.  When I looked at the recent version of `security.go` (https://github.com/golang/go/blob/master/src/cmd/go/internal/work/security.go) I didn't find `-v` on the whitelist
