### ISSUE TITLE
cmd/gofmt: gofmt is inconsistent

### ISSUE THREAD

**Issue by cg31** [golang/go#24609]
In following code, both functions have argument `str`, and both functions are called with `"test"+str1`, go-fmt should have same behavior handling them. 

But the first case, there will be spaces inserted around `+`, in second case, the spaces will be removed around `+`.

```
package main

import "fmt"

func test1(str string) {
	fmt.Println(str)
}

func test2(str string, str2 string) {
	fmt.Println(str)
	fmt.Println(str2)
}
func main() {
	str1 := "1"
	str2 := "2"
	test1("test"+str1) // spaces will be inserted around '+'
	test2("test" + str1, str2) // spaces will be removed around '+'
}
```

**Comment by ysmolsky** [comment]
It's not a bug, but a feature: https://golang.org/doc/effective_go.html#formatting

> Parentheses
Go needs fewer parentheses than C and Java: control structures (if, for, switch) do not have parentheses in their syntax. Also, the operator precedence hierarchy is shorter and clearer, so
x<<8 + y<<16
means what the spacing implies, unlike in the other languages.


check out this: https://play.golang.org/p/JiiUb_kjcXC - it's already properly formatted.

**Comment by FiloSottile** [comment]
This is indeed intended behavior. Just like `(5 * 2)` has spaces around the `*`, but adding a `+` removes them (`(5*2 + 2)`) to provide visual grouping. Here the `,` has precedence, so the spaces are removed to provide visual grouping in the arguments.

It gets more useful in cases like `("test"+str1, "test"+str2)`, where you can clearly see there are two arguments.
