### ISSUE TITLE
x/vgo: go.mod files in subdirectories are ignored when building the whole directory

### ISSUE THREAD

**Issue by blueimp** [golang/go#24605]
### What version of Go are you using (`go version`)?
`go version go1.10 darwin/amd64 vgo:2018-02-20.1`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```sh
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/blueimp/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/blueimp/Development/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pp/2fr7691n1j741m0xfz7pklx00000gn/T/go-build670014762=/tmp/go-build -gno-record-gcc-switches -fno-common"
VGOMODROOT=""
```

### What did you do?
In a new directory, create a simple go file and a go.mod file and use vgo to build it:

```sh
mkdir main
cd main
nano main.go
```

```go
package main // import "example.org/main"
func main(){}
```

```sh
touch go.mod
vgo build
cat go.mod
```

The output is as expected:
```
module "example.org/main"
```

Next, in a subdirectory add another vgo module and build it:

```sh
mkdir sub
cd sub
nano sub.go
```

```go
package sub // import "example.org/main/sub"
import (
	"fmt"
	"rsc.io/quote"
)
func main() {
	fmt.Println(quote.Hello())
}
```

```sh
touch go.mod
vgo build
cat go.mod
```

The output is as expected:
```
module "example.org/main/sub"

require "rsc.io/quote" v1.5.2
```

Now back in the parent directory, execute `vgo build ./...` and retrieve the now unexpectedly changed contents of the go.mod file:

```sh
cd ..
vgo build ./...
cat go.mod
```

### What did you expect to see?
```
module "example.org/main"
```

### What did you see instead?
```
module "example.org/main"

require "rsc.io/quote" v1.5.2
```

**Comment by rsc** [comment]
Nice bug.

The problem is that each build always runs in the context of a single top-level repo. There's no direct connection between the parent dir and the sub dir (it's not like the parent dir mentions the sub dir in a replace directive or other connection). 

At least for now I think the answer is that ./... should stop matching when it finds a directory containing a go.mod. That is, ./... can only match packages in the module where "." is, and sub would therefore be excluded.

**Comment by blueimp** [comment]
Thanks for the quick response!

I think ideally, running `vgo build ./...` would build all the modules in the directory, with automatic dependency resolution for each module separately.

But I'm also not 100% sure what users expect as outcome for building this way with multiple modules in the directory.

**Comment by freddy33** [comment]
Same need here on this repo: https://github.com/JFrogDev/gofrog
Like to have a go.mod for each folder creating 5 separate modules.

**Comment by tcolgate** [comment]
Same here, don't want  deps for individual adapters to pollute the top level https://github.com/tcolgate/hugot. (will push go.mod attempt later today if I get a chance)
