### ISSUE TITLE
x/vgo go version check is too narrow

### ISSUE THREAD

**Issue by carstenorthbandt** [golang/go#24602]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTOS="linux"

### What did you do?
- cd ~
- wget https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz
- sudo tar -C /usr/local -xzf go1.10.1.linux-amd64.tar.gz
- go get -u golang.org/x/vgo
- mkdir hello
- cd hello
- curl -sS https://swtch.com/hello.go >hello.go
- echo >go.mod
- vgo build

If possible, provide a recipe for reproducing the error.
Follow steps above

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
vgo fetching and building away

### What did you see instead?
vgo requires Go 1.10

The version check in checkGoVersion() requires an exact match of "1.10".
I don't think that check is very scalable with semver (haha).

**Comment by kardianos** [comment]
This is a valid way to check for the minimum go version. The `build.Default.ReleaseTags` does not include point releases because it is for building. I can only assume you are actually using an older version of Go. Please run `go version` and then run `go get -u golang.org/x/vgo`. Perhaps your PATH needs adjusting?

**Comment by carstenorthbandt** [comment]
$ go version
go version go1.10.1 linux/amd64

Now what?
Also, the check is still buggy. What about go1.11? For a tool that supposedly puts semver into go that's just sloppy.

**Comment by carstenorthbandt** [comment]
I updated my local vgo and #103635 did fix the problem.

**Comment by kardianos** [comment]
@carstenorthbandt 
If you ensure you run `go get -u golang.org/x/vgo` with go1.10.1 it will work.

The check is not buggy. https://godoc.org/go/build#Context.ReleaseTags is a string array of all Go releases this release supports. So go1.11 will still have go1.10 in the array, just as go1.10 has go1.9 and so on.

**Comment by kardianos** [comment]
If you want to confirm what I say, put a print statement in check loop and remove the "return". It will print out all the releases without the point versions.

**Comment by carstenorthbandt** [comment]
Something is really odd here:

carsten@daos ~/vgohello $ more go.mod

	carsten@daos ~/vgohello $ more vgohello.go 
	package main

	import (
		"fmt"
		"go/build"
	)

	func main() {
		for _, tag := range build.Default.ReleaseTags {
			fmt.Printf("Tag: %v\n", tag)
		}
	}
	carsten@daos ~/vgohello $ go run vgohello.go 
	Tag: go1.1
	Tag: go1.2
	Tag: go1.3
	Tag: go1.4
	Tag: go1.5
	Tag: go1.6
	Tag: go1.7
	Tag: go1.8
	Tag: go1.9
	Tag: go1.10
	carsten@daos ~/vgohello $ vgo build
	vgo requires Go 1.10
	carsten@daos ~/vgohello $ go version
	go version go1.10.1 linux/amd64
	carsten@daos ~/vgohello $ go env
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/carsten/.cache/go-build"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/home/carsten/go"
	GORACE=""
	GOROOT="/usr/local/go"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build786840063=/tmp/go-build -gno-record-gcc-switches"
	carsten@daos ~/vgohello $

**Comment by kardianos** [comment]
I'd suggest to run `which vgo` and see if go get vgo is actually updating it.

**Comment by carstenorthbandt** [comment]
You're right. I don't thing go get -i did anything (took a while though). Updating everything now.

**Comment by carstenorthbandt** [comment]
OK, looks like vgo doesn't get updated and still uses the 1.9 binary:


	carsten@daos ~ $ go get -u golang.org/x/vgo
	# archive/tar
	/usr/local/go/src/archive/tar/stat_atim.go:14:36: statAtime redeclared in this block
		previous declaration at /usr/local/go/src/archive/tar/stat_actime1.go:14:36
	/usr/local/go/src/archive/tar/stat_atim.go:18:36: statCtime redeclared in this block
		previous declaration at /usr/local/go/src/archive/tar/stat_actime1.go:18:36

**Comment by carstenorthbandt** [comment]
Appears to be a conflict from updating 1.9 -> 1.10.
Killed /usr/local/go completely, reinstalled 1.10.1 and now go get and vgo work fine.

*crawls back under rock*
