### ISSUE TITLE
x/tools/godoc: package listing is sorted in two groups on golang.org

### ISSUE THREAD

**Issue by williamhanisch** [golang/go#24601]
Please answer these questions before submitting your issue. Thanks!

(Also see https://groups.google.com/forum/#!topic/golang-nuts/8L0Li5HBZAQ for more info.)

### What version of Go are you using (`go version`)?

This is an issue with the golang.org website, so the go version I'm using is not applicable.  However near the very bottom of the page in questions, it says: Build version go1.10.1.

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Perhaps more applicable here is the operating system and browser I'm using.  macOS Version 10.13.3 and Safari Version 11.0.3 (13604.5.6)

### What did you do?

In Safari I went to https://golang.org/pkg/

If possible, provide a recipe for reproducing the error.

Go to that URL.

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

The listing of packages in alphabetical order by import path.

### What did you see instead?

The list of packages are in two groups.  Within each group, they are displayed alphabetically.  Which packages are in the top and bottom group appear to be unstable: e.g., math (and it's subdirectories) sometimes appears in the top group, and, upon refreshing the page, sometimes appears in the bottom group.

**Comment by agnivade** [comment]
> The list of packages are in two groups. Within each group, they are displayed alphabetically.

Yes that is right. Is this not what you expect ?

> Which packages are in the top and bottom group appear to be unstable: e.g., math (and it's subdirectories) sometimes appears in the top group, and, upon refreshing the page, sometimes appears in the bottom group.

That is very strange. Can you provide a screenshot with what you see ? Also, just to be clear, by groups you mean "Standard library" and "Other packages" right ?

And you might want to change the title of the issue. "package listing is sorted in two groups" is correct behavior. Maybe you want to say "package randomly appearing in different group" ?

**Comment by yaxinlx** [comment]
yes, same for https://golang.google.cn/pkg/
I just prepared to report it.

@agnivade 
it is obviously that `bufio` should be listed before `unsafe`? right?

**Comment by ysmolsky** [comment]
![screen shot 2018-03-30 at 09 53 36](https://user-images.githubusercontent.com/140245/38127774-4b298696-3400-11e8-9efe-eda0af8de962.png)

**Comment by agnivade** [comment]
Understood. So this issue is about the package list not being sorted. And not about a package randomly appearing in different groups. Can you confirm ?

**Comment by andybons** [comment]
@agnivade Yes, that's correct.

**Comment by williamhanisch** [comment]
It's only correct insofar as resorting may fix the symptom, but I don't think it's accurate to state that the problem is that the list is not sorted.  The list _seems_ to be split into two groups.  I'm talking about the standard library packages, not the other packages.  There is a top group of standard library packages and a bottom group of standard library packages.  Within each group, the packages do seem to be sorted.  To be clear, look at the screenshot posted by @ysmolsky above; the top group ends with unicode and the bottom group starts with bufio.  The packages listed above unicode are in alphabetical order, and the packages below bufio are also sorted alphabetically.  Moreover, which standard library packages appear in which group is not stable.  For example, I've seen the math package sometimes be in the top group, and, upon refreshing the page, sometimes appear in the bottom group.

**Comment by agnivade** [comment]
Right. I have a fix for the package list being unsorted. It is actually a concatenation of multiple sorted lists because of reading from multiple dir channels. Hence, the observation that it is split into 2 groups.

But what I am unable to reproduce is the listing getting changed on every refresh. Something to do with the `(dir *Directory) iter(skipRoot bool)` function in dirtrees.go. Investigating further.

**Comment by yaxinlx** [comment]
@agnivade 

> But what I am unable to reproduce is the listing getting changed on every refresh

Do you test it on a single machine? "the listing getting changed on every refresh" for https://golang.org/pkg/ may be caused by the fact that the visits are load balanced to different servers.

**Comment by agnivade** [comment]
Ah, hadn't thought of that. @andybons - is that how golang.org is run in production ?

**Comment by andybons** [comment]
@agnivade yep it’s run on App Engine.

**Comment by agnivade** [comment]
Cool. Sending the CL. 

Label suggestions - NeedsFix.

**Comment by kevinburke** [comment]
Yikes, this is my fault.

Previously we would span a new goroutine each time we encountered a directory. In large GOPATHs the number of spawned goroutines would exceed 8192, the maximum available number for programs run with the race detector enabled.

Capping the number of goroutines fixed the issues with godoc under the race detector, and led to a performance boost, but also led to out-of-order writes to dirchs.

**Comment by agnivade** [comment]
No worries ! I've been there too. So it's the least I could do :smile:
