### ISSUE TITLE
syscall: Dup2 in fd_nacl.go calls files.Unlock more than once

### ISSUE THREAD

**Issue by shurcooL** [golang/go#24610]
This is an issue on tip, as of this issue creation time. It was originally spotted by @kybin in https://github.com/neelance/go/commit/0f87113e02724b2e0f45a5dbf0e4e354d3da8f6c#r27472464 (but not reported here as far as I can tell).

Consider the implementation of `Dup2` in `src/syscall/fd_nacl.go`:

https://github.com/golang/go/blob/4468b0bac156b76b2a591b3aa3a0aa4dd60a0fce/src/syscall/fd_nacl.go#L122-L148

Lines 123 and 124 do `files.Lock()` and `defer files.Unlock()` respectively.

Lines 126 and 127 do `files.Unlock()` and `return EBADF` respectively.

Lines 141 and 147 do `files.Unlock()` and `return nil` respectively.

### What did you expect to see?

Given that `Dup2` executes `files.Lock()` once at the top, it should execute `files.Unlock()` exactly once before returning.

### What did you see instead?

`files.Unlock()` is executed twice.

Looking at the other methods, it feels like a copy/paste error. Some methods use `defer files.Unlock()` only, while other methods use individual `files.Unlock()` calls before `return` without using `defer files.Unlock()`. `Dup2` does both.

**Comment by FiloSottile** [comment]
This indeed breaks on the Playground https://play.golang.org/p/zj2NzfP9iGQ

**Comment by kybin** [comment]
actually I created same cl. but it does not get reviewed.
I should've create issue here first.
anyway it's great to see this fixed.

**Comment by FiloSottile** [comment]
@kybin Sorry about that. CLs without tracking issues tend to fall off our radar.

**Comment by kybin** [comment]
@FiloSottile Never mind. I am happy with it. :)

**Comment by shurcooL** [comment]
One small positive aspect of it is the fact that two independent CLs ended up being identical means it’s more likely the fix is optimal. :)
