### ISSUE TITLE
runtime: gentraceback no longer skips stack frames when printing

### ISSUE THREAD

**Issue by odeke-em** [golang/go#24628]
I got some time today to finish up and add a rigorous test for CL https://go-review.googlesource.com/#/c/go/+/37222 which involves printing the top and bottom n frames for easy reading in case of a massive stackoverflow.

To detect that we are printing stackframes, we have this condition https://github.com/golang/go/blob/fdf33730e1f84a5f0cd13bcbf2efbdceedab1114/src/runtime/traceback.go#L142

and in order for it to work, we need to be able to skip a bunch of frames when printing the bottom n stack frames.

However, with code that we used to skip through physical frames previously, CL https://go-review.googlesource.com/37854 aka commit https://github.com/golang/go/commit/ee97216a1787a979911d43c0c5c582b5492a2205 changed that behavior assuming that we'd never use `skip` unless `pcbuf != nil`. However, we actually need to skip through physical frames when printing tracebacks otherwise on trying to print top and bottom stackframes, we always end up printing the top irrespective of our skip which is a regression that silently snuck in for an entire year as it wasn't used. 

The code that disabled proper skipping is https://github.com/golang/go/commit/ee97216a1787a979911d43c0c5c582b5492a2205#diff-5a2de8a1053d4e11fbc71407a5361e93L321
<img width="913" alt="screen shot 2018-04-01 at 1 59 10 am" src="https://user-images.githubusercontent.com/4898263/38171542-76a32de4-3550-11e8-8d84-1731f8c04976.png">
<img width="916" alt="screen shot 2018-04-01 at 2 07 18 am" src="https://user-images.githubusercontent.com/4898263/38171607-72e29afe-3551-11e8-8131-9d701bf40b2e.png">

/cc @davidlazar @aclements

**Comment by bcmills** [comment]
Is this a regression in a user-facing behavior, or just an internal function?

(I assume that it's blocking #7181; is that the only impact?)

**Comment by odeke-em** [comment]
@bcmills correct, it is only blocking #7181, but nonetheless a bug when skipping and printing -- something that hasn't yet been exposed though because we've been printing the entirety of stackframes.

**Comment by odeke-em** [comment]
I've mailed a fix for this issue, packaged in the the CL that it was blocking as per https://go-review.googlesource.com/c/go/+/37222.

**Comment by randall77** [comment]
CL was reverted.

**Comment by aclements** [comment]
This code has all been completely refactored as of [CL 468301](http://go.dev/cl/468301). Now that PC buffer filling and traceback printing are completely separate entry-points and printing doesn't take a skip count, there's no longer confusion about the skip count. (Though, joke's on me, I'm about to bring back the printing skip count. But it's much more localized now!)
