### ISSUE TITLE
test/fixedbugs: bug345 and bug248 do not properly check for regressions

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#24629]
Actions to reproduce issue:

1. Try to break bug345.go: remove ERROR directives or make them like `// ERROR "NO MATCH"`.
2. Run `go run run.go -v fixedbugs/bug345.go`

**Result**:
 `ok  	fixedbugs/bug345.go	0.269s` (test passed)

**Expected result**: test failed.

Test doesn't check for regression properly.

They do work on older Go versions, where such tests were executed with `run` script.
Closer look at [CL1774](https://golang.org/cl/1774):

```go
func run(name string, args ...string) {
	cmd := exec.Command(name, args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Println(string(out))
		fmt.Println(err)
		os.Exit(1)
	}
}
```

`errchk` script seems to exit with code 0 even if something went wrong.
`out` may contain error text, but `err` will be `nil`.

Removed `run` script checked command output for `^BUG` pattern,
so I think `run(name string, args ...string)` function above
should do something similar, too.

As a proof:
```
commit 34b277f046eb4b6ffffd524ff76c5fd264f82b87
Author: Russ Cox <rsc@golang.org>
Date:   Thu Jul 30 16:46:14 2009 -0700

    use errchk in more places.
    let errchk exit 0 even if it has reported a BUG.
    it echoed BUG and that's all that matters.
```

If we do check `out` for `bug345`, it has this content:
```
BUG: errchk: main.go:25: error messages do not match 'test/io|has incompatible type'
errchk: main.go:25: unmatched error messages:
> main.go:25:17: cannot use w (type "go/test/fixedbugs/bug345.dir/io".Writer) as type "io".Writer in argument to bufio.NewWriter:
	"go/test/fixedbugs/bug345.dir/io".Writer does not implement "io".Writer (missing Write method)
errchk: main.go:27: error messages do not match 'test/io|has incompatible type'
errchk: main.go:27: unmatched error messages:
> main.go:27:8: cannot use &x (type *"io".SectionReader) as type *"go/test/fixedbugs/bug345.dir/io".SectionReader in argument to "go/test/fixedbugs/bug345.dir/io".SR
```

There is a second issue.

Error directives do not match due to different package paths.
When bug345 was executed by old `run` script, the path was like `go/test/io`,
now it's `go/test/fixedbugs/bug345.dir/io`.
The `"test/io|has incompatible type"` pattern does not match error message due to that.

Possible solution:
First of all, check `out` for `BUG` line in addition to `err` check.
For the second part, there are multiple options:
- Make it so the path is similar to previous path so the pattern does match it again
- Update ERROR pattern so it matches new path

First solution seems superior.

`bug248` is also affected, but it doesn't suffer from different package path problem.

Planning to resolve this to make #20007 simpler.

**Comment by bcmills** [comment]
Sounds like you both have candidate fixes in mind. Somebody want to send one for review? 🙂

**Comment by odeke-em** [comment]
@bcmills, I believe @Quasilyte got dibs on this :)
> Planning to resolve this to make #20007 simpler.

so I'll defer to them

**Comment by odeke-em** [comment]
@Quasilyte please feel free to borrow ideas from my posting, and also to tag me in the CL if you need a review, all yours, thanks for working on it!
