### ISSUE TITLE
runtime: "invalid runtime symbol table" panic in sighandler

### ISSUE THREAD

**Issue by hkspirt** [golang/go#24634]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/devs/go"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build411484890=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
run with supervisor

### What did you expect to see?
no panic

### What did you see instead?
I see  "f=sync.runtime_notifyListCheck" too
runtime: invalid pc-encoded table f=syscall.runtime_AfterForkInChild pc=0x436228 targetpc=0x43622f tab=[0/0]0x0
    value=0 until pc=0x4361e4
    value=16 until pc=0x436227
    value=0 until pc=0x436228
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime.throw(0xbfa737, 0x1c)
    /opt/go/src/runtime/panic.go:605 +0x95
runtime.pcvalue(0xce1b58, 0xf96520, 0x54d9a, 0x43622f, 0xc42004b4a0, 0x1, 0x0)
    /opt/go/src/runtime/symtab.go:768 +0x515
runtime.funcspdelta(0xce1b58, 0xf96520, 0x43622f, 0xc42004b4a0, 0x0)
    /opt/go/src/runtime/symtab.go:820 +0x5f
runtime.gentraceback(0x45d657, 0x7fdd257a3d80, 0x0, 0xc420000900, 0x0, 0xc42004b6e8, 0x40, 0x0, 0x0, 0x6, ...)
    /opt/go/src/runtime/traceback.go:243 +0x1579
runtime.sigprof(0x45d657, 0x7fdd257a3d80, 0x0, 0xc420000900, 0xc420030400)
    /opt/go/src/runtime/proc.go:3374 +0x40f
runtime.sighandler(0xc40000001b, 0xc42004bbf0, 0xc42004bac0, 0xc420000900)
    /opt/go/src/runtime/signal_sighandler.go:33 +0x6b4
runtime.sigtrampgo(0x1b, 0xc42004bbf0, 0xc42004bac0)
    /opt/go/src/runtime/signal_unix.go:334 +0x25d
runtime.sigtramp(0x1, 0x0, 0xc420044000, 0x0, 0x8000, 0x0, 0x43622f, 0x0, 0x246, 0x0, ...)
    /opt/go/src/runtime/sys_linux_amd64.s:306 +0x43

**Comment by odeke-em** [comment]
Hello there @hkspirt, thanks for filing the issue and welcome to the Go project!

Could you please add some more detail to your issue? Some sample and runnable code to aid in easy reproduction and bug fixing. Some more information of how you were able to cause this panic. Thank you.

**Comment by bcmills** [comment]
@heschik and @aclements have been investigating a similar report. If you have steps to reproduce this issue fairly reliably, that would be really helpful.

**Comment by heschik** [comment]
Assuming Austin and I are right about the cause of our problem, this is different, because our problem was new in 1.10.

**Comment by heschik** [comment]
This probably was a dupe of #24925.
