### ISSUE TITLE
go/types: column reporting of "no field or method" seems wrong

### ISSUE THREAD

**Issue by rasky** [golang/go#24645]
When typechecking a selector, go/types reports the column corresponding to the begin of the selector expression, rather than name being selected:

```
       obj[whatever].missing(123)
       ^
       gotype reports here
```

The compiler instead reports the missing name:

```
       obj[whatever].missing(123)
                     ^
                     compiler reports here
```

The compiler version seems preferable, as it better highlights where the error probably lies. For instance, this is how my editor (that uses go/types) highlights a missing method:

<img width="682" alt="screenshot 2018-04-02 20 21 27" src="https://user-images.githubusercontent.com/1014109/38209087-7e47882e-36b3-11e8-84bc-d547ff7452ac.png">

I prepared a quick fix and this is how it looks like once go/types matches column info with the compiler:

<img width="682" alt="screenshot 2018-04-02 20 23 06" src="https://user-images.githubusercontent.com/1014109/38209140-aedab9de-36b3-11e8-9c86-e467cfaefec1.png">

I will submit a CL soon.

**Comment by griesemer** [comment]
@rasky I have assigned this issue for me simply so it stays on my radar. If you end up with a CL, please assign it to me for review; thanks.
