### ISSUE TITLE
x/vgo: make quotes optional in go.mod file

### ISSUE THREAD

**Issue by rsc** [golang/go#24641]
Here's a short go.mod:

```
module "github.com/you/hello"

require (
	"golang.org/x/text" v0.0.0-20180208041248-4e4a3210bb54
	"rsc.io/quote" v1.5.2
)
```

I propose to drop the distinction between a quoted string and a bare literal, with the restriction that literals must not include any kind of unicode space, nor U+0022 (") nor U+0060 (`). Then this file can be shortened to (and would be rewritten canonically as):

```
module github.com/you/hello

require (
	golang.org/x/text v0.0.0-20180208041248-4e4a3210bb54
	rsc.io/quote v1.5.2
)
```

Not quoting should make it easier to copy and paste from the command line or from substrings of import paths or from "go list -m" output. Backslashes are allowed in literals and stand for themselves, so that you can write

```
replace rsc.io/quote v1.5.2 => c:\work\quote
```

If you need a space in the path in that form then it's still necessary to quote:

```
replace rsc.io/quote v1.5.2 => `c:\rsc\my work\quote`
replace rsc.io/quote v1.5.2 => "/users/rsc/my work/quote"
```

**Comment by flibustenet** [comment]
Is `=>` mandatory for replace ? It could be more like require
`replace rsc.io/quote v1.5.2 c:\work\quote`

`exclude` also, i think you propose it also.

**Comment by rsc** [comment]
Yes, => is still mandatory for replace. I think replace is confusing enough to be worth having that separator.
