### ISSUE TITLE
cmd/vet: missing 'possible formatting directive in Fprintln call' warning

### ISSUE THREAD

**Issue by camarena** [golang/go#24646]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/camarena/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/camarena/go"
GORACE=""
GOROOT="/Users/camarena/homebrew/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/camarena/homebrew/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/22/p1vpwjb10wq7gcjp63w9ccdr00d83_/T/go-build934642368=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
I had this method:
func (ccp CommandParser) WriteHelp(w io.Writer) {
	fmt.Fprintln(w, "%T.WriteHelp Not implemented Yet", ccp)
}

it should be

func (ccp CommandParser) WriteHelp(w io.Writer) {
	fmt.Fprintf(w, "%T.WriteHelp Not implemented Yet\n", ccp)
}

### What did you expect to see?
I expect to see the message: "possible formatting directive in Fprintln call"
as it is reported in linux.

### What did you see instead?
no message and no error reported on macos

**Comment by bcmills** [comment]
What command line did you use to invoke `vet`?

**Comment by camarena** [comment]
I used the cl below.  It works ok in linux but it does not in Macos
go vet <package>
​
​
Hermán Camarena
Sr. Software Engineer
camarena@google.com
+1.561.716.2843



Of course it can be done.  It is just software!

**Comment by robpike** [comment]
Please provide a complete example.

**Comment by josharian** [comment]
A complete example is easy enough to construct from the original issue, and it appears to reproduce still:

```
package main

import (
	"fmt"
	"io"
)

type CommandParser int

func (ccp CommandParser) WriteHelp(w io.Writer) {
	fmt.Fprintln(w, "%T.WriteHelp Not implemented Yet\n", ccp)
}
```

**Comment by josharian** [comment]
Bad @gopherbot.

**Comment by mvdan** [comment]
Thanks for the complete reproducer, @josharian. I can reproduce the bug on Linux, so I'm going to look into a fix.
