### ISSUE TITLE
net/textproto: ReadLineBytes() returns strange []byte

### ISSUE THREAD

**Issue by Chipsterjulien** [golang/go#24642]
### What version of Go are you using (`go version`)?
1.10.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux on x86 (64 bits). Testing same code on android and it's ok

### What did you do?

with 1.9.4, it works

With my bot on irc, sometimes, it reads some things with the code as follow:
```
reader := bufio.NewReader(bot.conn)
tp := textproto.NewReader(reader)
line, err = tp.ReadLineBytes()
…
```

I try with tp.ReadLine() to get a string but it's the same error.

Sometimes, i have this:

> ircbot[1179]: [202B blob data]
> ircbot[1179]: [125B blob data]
> 

If possible, provide a recipe for reproducing the error.
yes and no. If my friend speaks yes, it's me, no:

As i said before, my code works with go-1.9.4

> 11:46:03.872 event ▶ DEBU 0a2 > :nheir!~nheir@died.re PRIVMSG #archlinux-fr :ça pourrait arriver en construisant une page web avec le bon titre par exemple
> panic: runtime error: slice bounds out of range
> ircbot[1049]: goroutine 11 [running]:
> ircbot[1049]: main.(*Bot).searchToManyHL(0xc42009e5a0, 0xc4203c6020, 0xc42004fd78, 0xc420056600)
> ircbot[1049]:         /home/julien/ircbot/event.go:465 +0x970
> ircbot[1049]: main.event(0xc42009e5a0, 0xc4200565a0, 0xc420056600, 0xc420056660, 0xc420060120, 0xc42004fef8)
> ircbot[1049]:         /home/julien/ircbot/event.go:153 +0xccd
> ircbot[1049]: main.eventManagement(0xc42009e5a0, 0xc4200565a0, 0xc420056600, 0xc420056660, 0xc420060120)
> ircbot[1049]:         /home/julien/ircbot/readWriteEventProcess.go:45 +0x1c9
> ircbot[1049]: created by main.main
> ircbot[1049]:         /home/julien/ircbot/app.go:52 +0x2ac
> systemd[1]: ircbot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> systemd[1]: ircbot.service: Failed with result 'exit-code'.

**Comment by agnivade** [comment]
> yes and no. If my friend speaks yes, it's me, no:

I'm sorry, what does that supposed to mean ?

Please post a self-contained working code which reproduces the issue. 

Also, the error message that you have posted shows a panic on slice bounds out of range. But the issue you have reported is about `ReadLineBytes()` returning unexpected output. So which is the issue ? the panic or the unexpected output ?

Label suggestions - `WaitingForInfo`

**Comment by Chipsterjulien** [comment]
My bad, i found my big mistake. Sorry for the inconvenience
