### ISSUE TITLE
strings: TestBuilderGrow test flake

### ISSUE THREAD

**Issue by josharian** [golang/go#24647]
https://build.golang.org/log/bc6b2519adffb638dbe8ad1fcd447d1737740e6d

```
--- FAIL: TestBuilderGrow (0.04s)
	builder_test.go:94: growLen=10000: allocation occurred during write
FAIL
FAIL	strings	5.487s
```

@aclements commented over in #24631 about alloc measurements in the testing package:

> I worry slightly that the random background allocations that aren't coupled to iterations (e.g., when a GC cycle runs) would almost always cause this number to be slightly above a whole number and that that could confuse people.

Perhaps that effect is responsible for this build failure. Note that the strings package has its own handrolled alloc count implementation, one which does no averaging and is thus more susceptible to such flakes.

cc @cespare @bradfitz

**Comment by bcmills** [comment]
Seems like the “no allocations” tests could just try that part of the test over again if there are unexpected allocs. (We do need to cut it off eventually, but we could run arbitrarily many iterations — or fall back to `testing.AllocsPerRun` — before we give up.)
