### ISSUE TITLE
x/playground: interleaving stdout and stderr is broken

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#24659]
The expected output of the program https://play.golang.org/p/5agzWi_tyrw is 
```
error 0
outpt 0
error 1
outpt 1
error 2
outpt 2
```
Actual output is
```
outpt 0
outpt 1
outpt 2
error 0
error 1
error 2
```
I see a way to fix this in playground by writing both `stderr` and `stdout` streams into one: `stdout`. Since playground does not display `stderr` any different than `stdout`, we can do this to make its behaviour consistent.

This issue affects tests executed in playground. If the test outputs anything to `stderr` then the order of lines is not consistent. See #24615

**Comment by bcmills** [comment]
(CC: @andybons @ysmolsky)

**Comment by ysmolsky** [comment]
Here is some debug output collected by using this: 
```
modified   play.go
@@ -55,7 +55,7 @@ type recorderWriter struct {
 func (w recorderWriter) Write(b []byte) (n int, err error) {
 	w.r.mu.Lock()
 	defer w.r.mu.Unlock()
-
+	fmt.Printf("W %v %q\n", w.kind, string(b))
 	// Append this write to the previous one if it has the same kind.
 	if len(w.r.writes) > 0 {
 		prev := &w.r.writes[len(w.r.writes)-1]
```

Running this program 
```
	fmt.Fprint(os.Stderr, "e1")
	fmt.Fprint(os.Stdout, "z1")
	fmt.Fprint(os.Stderr, "e2")
	fmt.Fprint(os.Stdout, "z2")
	fmt.Fprint(os.Stderr, "e3")
	fmt.Fprint(os.Stdout, "z3")
``` 
gives following recombinations of output:
```
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stderr "e1"
W stdout "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02e2\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02e3"
W stdout "z1\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02z2\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02z3"
```

```
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stderr "e1"
W stdout "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stdout "z1"
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stdout "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02z2\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02z3"
W stderr "e2\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02e3"
```

I have applied the [strict time patch](https://go-review.googlesource.com/c/go/+/105235) to the go and built playground, got following:
```
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x00\x00\x00\x00\x02"
W stderr "e1"
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x02\x00\x00\x00\x02e2"
W stdout "\x00\x00PB\x11t\xef\xed\xab\x18`\x01\x00\x00\x00\x02z1\x00\x00PB\x11t\xef\xed\xab\x18`\x03\x00\x00\x00\x02z2"
W stderr "\x00\x00PB\x11t\xef\xed\xab\x18`\x04\x00\x00\x00\x02"
W stdout "\x00\x00PB\x11t\xef\xed\xab\x18`\x05\x00\x00\x00\x02z3"
W stderr "e3"
```
We do get increments in header for every write operation. 

It is interesting to note that header and actual data are not passed as a single piece to `recordWriter.write`. Even with the work done by @bcmills, we have to take another step to solve this. We should aggregate writes of different kinds into separate slices, process them individually from bytes into events and then merge those events slices with a sorting by the `strict time` values. 

@bcmills, does it make sense?

**Comment by bcmills** [comment]
Nice analysis. Separate buffering sounds right. (And if we buffer the two streams separately, we can do an O(n) sorted merge instead of an O(n log n) sort!)
