### ISSUE TITLE
cmd/go: install foo/v2 as binary "foo"

### ISSUE THREAD

**Issue by rsc** [golang/go#24667]
If we're installing a binary with import path blah/blah/foo/v2, we should install it as foo, not v2.

**Comment by adamdecaf** [comment]
Would there be support for installing multiple versions of `foo`?

**Comment by myitcv** [comment]
> Would there be support for installing multiple versions of `foo`?

I am not sure what the target `bin` directory structure would look like (and therefore what my `PATH` would need to look like)

Alternatively @adamdecaf would support for [`go run` taking an import path](https://github.com/golang/go/issues/22726) suffice/be better?

**Comment by adamdecaf** [comment]
@myitcv Not really. I'm thinking more about being able to have a "foo v2" and "foo v3" binary around usable by programs wrapping the binary. No idea what `$GOPATH/bin` has to look like though. 

I understand that the last execution of `go install` wins that battle now, but if there was an option which allowed versioned binaries at `$GOPATH/bin` that would be nice. It's probably too big of a task to tackle initially though.

**Comment by rasky** [comment]
One option would be to install `foo.v2` and create a symlink `foo` -> `foo.v2`, with the latest `go install` winning the symlink race, but all versions available using the suffix.

On the other hand, what is the use case for an installable module having a major version number in the vgo world? It looks like the semantic version is used to express API breakage for libraries, so it doesn't look like it's so important for installable modules, nor it does necessarily convey some usable information; so maybe the above suggestion is just over-engineering a non-problem.

**Comment by mewmew** [comment]
What if the tool is actually called `v2` (or some other `vNUM`)?

On a related note, how does the Go tool handle internal paths in relation to the GitHub user https://github.com/internal?

The second questions is perhaps less serious, but the first one, I currently can't see how you'd differentiate between a tool actually being called `v2` from one of version 2. For say `github.com/user/repo/foo/bar/v2`, then `bar` may be a separate tool and not simply version 1 of the same tool as `v2`.

**Comment by bcmills** [comment]
> What if the tool is actually called `v2` (or some other `vNUM`)?

Don't do that?

But the module path should help to disambiguate, too: perhaps a binary package in subdirectory `foo/bar/v2` within a module with module path `github.com/user/repo` really should be named `v2`. The ambiguous cases occur when the module path itself ends with `/v2` and the package is located at the module root.
