### ISSUE TITLE
cmd/go: segmentation fault on macOS 10.13.4

### ISSUE THREAD

**Issue by fishcharlie** [golang/go#24679]
### What version of Go are you using (`go version`)?

Unknown

### Does this issue reproduce with the latest release?

Yes, just reinstalled

### What operating system and processor architecture are you using (`go env`)?

Unknown, macOS 10.13.4

### What did you do?

Run `go help`, or `go version`, or any `go` command in my Terminal

### What did you expect to see?

The command I ran.

### What did you see instead?

`Segmentation fault: 11`

**Comment by davecheney** [comment]
Please make sure you upgrade to go 1.10.1. Earlier versions of Go are
incompatible with changes to the kernel interface in Sierra and later.

**Comment by bcmills** [comment]
There is not enough information in this report for us to diagnose the issue. Please provide the specific steps you followed to reproduce the issue.

In particular, how did you install the Go toolchain in question, and where did you get it from?

**Comment by ianlancetaylor** [comment]
Timed out.
