### ISSUE TITLE
x/sys/unix: export Fcntl and make more POSIX compliant

### ISSUE THREAD

**Issue by ppbrown** [golang/go#24677]
go version go1.10 linux/amd64

This is related to issue #24649 and thus to code review
 https://go-review.googlesource.com/c/sys/+/104255

I am going to be attaching a new code PR to this issue. If accepted, I can then cancel the prior one.

It was discussed in 104255, how the potentially most clean approach is to finally export fcntl  as Fcntl.

Unfortunately, the existing x/sys/unix.fcntl is not standards compliant with its type. 
The third argument is declared as "int": however, sometimes, fcntl calls require the third argument to be a pointer.
This mandates that the third argument be changed to uintptr, rather than int.
Happily, it is currently an internal function only, so making the change does not require too many cascading updates.

**Comment by ppbrown** [comment]
Good news:
I have the new code, written, TESTED, and ready to commit.

Problem:
This touches multiple files, in small ways.
I made separate "git commit" calls locally, so that the details of the individual files would get commented. 
Then tried to do a unified "git change".
But it wont let me do that.

git-codereview: cannot amend change: multiple changes pending:
        fd3cb4e update type of fcntl to properly have 3rd arg as uintptr, to be fully standard compliant
        b33df1f update type of fcntl to properly have 3rd arg as uintptr, to be fully standard compliant
        8f2c662 New test based around flock_test.go, but using Fcntl directly, rather than FcntlFlock
        2594872 Exported fcntl as Fcntl
        4a0a565 Updated third arg to fcntl to match new definition (int -> uintptr)


So, how should I proceed?
It feels wrong to me to submit each of these file changes as a separate change, since if for example, only one were accepted, it would BREAK builds, until the rest were accepted.

**Comment by ppbrown** [comment]
PS: just so I dont forget, I'm noting here that if my code changes are accepted, there will need to be a robo-auto-update, to fix the autogenerated zsyscall_xxx files (since I was informed that may only happen on the official build farm)

**Comment by bradfitz** [comment]
Agree. Specific type-safe fnctl sounds good.
