### ISSUE TITLE
x/tools/cmd/present: notes mode causes different presentations in separate tabs/windows to advance in step

### ISSUE THREAD

**Issue by myitcv** [golang/go#24688]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10.1 linux/amd64
present at commit ac136b6c2db7c4d43955e4bc7174db36dc0539c0
```

### Does this issue reproduce with the latest release?

Yes, per above

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build270412448=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Open the following two presentations in Chrome in two separate tabs in the same window (could be any two presentations, these are just current examples):

https://talks.godoc.org/github.com/stmuk/go-unicode-examples/unicode.slide
https://talks.godoc.org/github.com/mvdan/talks/2018/benchstat.slide

Observe that both start on slide number 1.

Now click to advance the Unicode presentation forward by one slide. 

### What did you expect to see?

Only the Unicode presentation should advance.

### What did you see instead?

If you switch to the tab with the Benchstat presentation you will notice that has _also_ advanced to slide number 2.

This appears to happen because:

* [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) is used 
* both pages share the same origin 
* the stored values do not include `window.location.pathname` in their key
* hence [logic that updates values, e.g. current slide](https://github.com/golang/tools/blob/ac136b6c2db7c4d43955e4bc7174db36dc0539c0/cmd/present/static/slides.js#L226) in local storage causes both presentations to advance

Seemingly this behaviour is necessary for notes mode where the notes window and the main deck should advance _pari passu_ (and talks.godoc.org operates in notes mode)

But where there are two different presentations (this issue came up at the London Gophers meetup) then this is less than desirable.

Could the path (`window.location.pathname`) be used to distinguish the keys?

_As a postscript, if you try to advance the Benchstat presentation beyond slide 13 you will likely find that Chrome's CPU usage jumps because it gets into something of a loop. This appears to be because the Unicode presentation does not have 14 slides and so some loop is triggered._

**Comment by danicat** [comment]
Just submitted a fix for this. I was expecting to write some Go code, ended up writing javascript. 😂 

I'm a bit concerned about the lack of automated tests in this project, but I don't have enough JS knowledge to tackle this. Nevertheless, tested locally and it seems to do the job.

**Comment by myitcv** [comment]
> I'm a bit concerned about the lack of automated tests in this project

It was the lack of automated tests that alarmed you? It was the very presence of JavaScript that set alarm bells ringing for me 😄

**Comment by danicat** [comment]
Totally with you on that @myitcv ! I was just afraid to address the elephant in the room I guess... lol

I've just submitted a new patch with style fixes. I may try to add some test coverage to it, but I'm not sure if I'll have the time to do it anytime soon.
