### ISSUE TITLE
database/sql: add DB connection diagnostics

### ISSUE THREAD

**Issue by pjebs** [golang/go#24683]
Currently the `*DB` object (which represents a pool of connections) allows these settings:
    
- SetConnMaxLifetime(d time.Duration)
- SetMaxIdleConns(n int)
- SetMaxOpenConns(n int)

The aim of my proposal is to assist Go developers to tune these values.

Perhaps the `DBStats` object which currently only indicates how many open connections exist can indicate how many open connections are on average blocked and how long they are blocked for, for our typical application.

That will allow us to perhaps set a higher `SetMaxOpenConns` value.

**Comment by bcmills** [comment]
This issue in its current form does not have enough detail to be a [proposal](https://golang.org/s/proposal-process).

If you want to describe a general area for improvement, please add an [experience report](https://golang.org/wiki/ExperienceReports) instead.

Otherwise, please describe the specific changes you would like to see, including the motivation or background, syntax or API signatures, and concrete examples (ideally drawn from experience reports).

**Comment by kardianos** [comment]
Sorry, I mislabeled it. I attempted to choose labels that conveyed "yes, I agree this would be good, we can track this separately, but I'm not sure how to best achieve this yet."

**Comment by kardianos** [comment]
I would be interested to specifically add the following stats:


	// Pool Configuration.
	Capacity int              // The capacity of the connection pool.
	IdleTimeout time.Duration // Zero if no idle timeout should apply to the pool.

	// Pool Status
	Available int // The number of free connections within the pool.
	OpenConnections int    // The number of connections both in use and in the pool.
	InUse int     // The number of connections currently in use.

	// Counters
	WaitCount int64        // The total number of connections waited for.
	WaitTime time.Duration // The total time blocked waiting for a new connection.
	IdleClosed int64       // The total count of connections closed due to idle.

@pjebs Would these statistics work for you?

**Comment by pjebs** [comment]
LGTM

**Comment by pjebs** [comment]
maybe for WaitCount and WaitTime, `(avg) per time` might be better but not per time is still workable

**Comment by kardianos** [comment]
Couters play nice with systems like Prometheus and influx. We can derive averages from them at any interval.

**Comment by pjebs** [comment]
Some resources for future readers:
http://techblog.en.klab-blogs.com/archives/31093990.html
http://www.alexedwards.net/blog/configuring-sqldb
