### ISSUE TITLE
time: error handling for time.Month.String() and time.Weekday.String() is inconsistent

### ISSUE THREAD

**Issue by jaseemabid** [golang/go#24692]
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/j/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/j/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build714199702=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

When converting a month out of range to String, the function returns a debug string, but panics for Weekday.

Code sample at https://play.golang.org/p/3U4gRY5kRzc

### What did you expect to see?

Both should either panic, or return error string. 

### What did you see instead?

time.Month.String() returned debug string, time.Weekday.String() paniced.

**Comment by agnivade** [comment]
Indeed. 

Month.String() checks for range, and if outside it returns a stringified representation of it. 
```go
// String returns the English name of the month ("January", "February", ...).
func (m Month) String() string {
	if January <= m && m <= December {
		return months[m-1]
	}
	buf := make([]byte, 20)
	n := fmtInt(buf, uint64(m))
	return "%!Month(" + string(buf[n:]) + ")"
}
```
Whereas Weekday.String() does not.
```go
// String returns the English name of the day ("Sunday", "Monday", ...).
func (d Weekday) String() string { return days[d] }
```

We should probably fix to not panic on `(Weekday).String()`, or there might be a reason for this. Not sure. In any case, I think this might be on the verge of breaking Go1 compat. NeedsDecision.

/cc @rsc, @ianlancetaylor

**Comment by ianlancetaylor** [comment]
We should fix `Weekday.String` as we fixed `Month.String` for #17720.
