### ISSUE TITLE
cmd/compile: static itab construction fails when a type has multiple non-exported methods

### ISSUE THREAD

**Issue by mdempsky** [golang/go#24693]
In reflect.go:genfun, the code to walk method sets in parallel to compute itab entries doesn't take packages into account for finding the right non-exported method. This causes the code below to print `FAIL` instead of `ok`, because it selects U.m instead of T.m for the itab.

    $ cat z.go
    package z
    
    type T int
    func (T) m() { println("ok") }
    
    func F(i interface{ m() }) { i.m() }
    
    $ cat main.go
    package main
    
    import "./z"
    
    type U struct{ z.T }
    func (U) m() { println("FAIL") }
    
    func main() { z.F(U{}) }
    
    $ go tool compile z.go
    $ go tool compile main.go
    $ go tool link main.o
    $ ./a.out
    FAIL

**Comment by mdempsky** [comment]
Relatedly: when sorting method sets, we sort non-exported names by their package path. However, we always use `""` for the local package path, so I think there are cases where a method set will be sorted inconsistently across different compilation units.

We could sort according to the `-p` flag. We could also make it an error when -p is not set, and sorting a method set would depend on it. This is ugly, but better than miscompiling code.

**Comment by rsc** [comment]
We have not yet told people that -p is required when invoking the compiler. I'm not even sure if we do it ourselves consistently everywhere. Almost certainly not. If there's a way to avoid requiring -p that would be nice. That said I agree that the method tables are probably sorted wrong, which is bad. Maybe this is the last straw that pushes us over to requiring -p. Not sure.

**Comment by mdempsky** [comment]
Yeah, I'd really like to avoid requiring `-p` too. I expect we always set it for user builds, but I think it would be obnoxious for compiler development work. I also expect the regress tree would need some work.

Perhaps we could sort non-exported method symbols by package height (i.e., [height](https://en.wikipedia.org/wiki/Tree_(data_structure)#height_of_node) of the package node in the package dependency tree) and *then* package path.

The package under compilation is the only package whose path we might not know. It will also always have a unique height within that compilation unit (i.e., at least 1 more than every other package within the CU, by definition), so this ordering should be insensitive to `-p`.
