### ISSUE TITLE
Language is a platform, which golang still does not pay attention !!!

### ISSUE THREAD

**Issue by iamybj** [golang/go#24698]
Almost 10 years golang appear in the world. I think if it is not popular until 2020, it will never popular.

Golang is designed suitable for cloud and internet areas.  Really? 

The creators of golang have a lot of experiments in C and C++. And golang borrows features from C and C++. But C and C++ do not fit the requirements of cloud and internet.

Let's look at two popular programming languages java and php. What is the most important feature of these two languages? Simple, ugly but practical, and I find another feather: language is a platform. That's why java and php are very popular in recent days.

C and C++ is just programming languages, not platforms. In Unix and Windows, C and C++ are not the same. A developer of windows C++ can not write C++ code in Linux, and a Linux C developer can not write c code in Windows.

If golang wants to be widely used by developer all over the world before 2020,  it must be a programming-language-is-a-platform.

Until now, programs written in golang still does not have binary distribution format like jar, dll or so.  People have to share library by source code. It is so foolish.

Yes, Golang is very like C and C++, which are only pure programming language, But this times, we need "language as/is platform" technologies, just like php and java.

I have watched golang for many years, but never turn to this language. I think it is still semi-finished product. Creators of golang is researchers, they worked too slowly.

**Comment by mvdan** [comment]
This reads more like a rant or discussion than an actual bug report or feature proposal. I would suggest taking this to the mailing list or one of the other discussion forums: https://golang.org/wiki/Questions

Otherwise, if you have an actual proposal for the language or tools, see https://github.com/golang/proposal.

**Comment by iamybj** [comment]
Of course it is bug, huge bug, design bug!
