### ISSUE TITLE
question about `syscall` and the locked state for contributions

### ISSUE THREAD

**Issue by neolit123** [golang/go#24707]
### What version of Go are you using (`go version`)?
latest master

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows XP, 7, 10.
Intel i3, i7

### What did you see instead?

hello,
i spoke to @alexbrainman about this and he explained to me that the `syscall` package is locked for contributions and if i want to contribute missing features for a platform these would not be accepted - e.g. take a look at these calls for Windows:
https://github.com/golang/go/blob/master/src/syscall/syscall_windows.go#L987

would the `syscall` package enter a unlocked state at some point and what is the `golang` project mechanic for dealing with such missing features?

the idea behind my question is that i could eventually contribute some of the missing Windows features.

previous contributions:
https://github.com/golang/go/commits?author=neolit123

thanks
lubomir (vmware)

**Comment by rsc** [comment]
The syscall package in the standard library is only for routines needed by the standard library itself. Other "completeness" additions belong in golang.org/x/sys instead.

**Comment by neolit123** [comment]
@rsc 
thank for the response,

so i guess if i want to contribute for instance the `Chown()` family of functions i would need to submit it against this repository?:
https://github.com/golang/sys/blob/master/windows/syscall_windows.go#L1090
