### ISSUE TITLE
all: test failures after calling all.bat on Windows7

### ISSUE THREAD

**Issue by neolit123** [golang/go#24709]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version devel +e8aa9a53 Thu Apr 5 16:22:39 2018 +0000 windows/amd64`
latest master at the time.

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
OS: `Microsoft Windows [Version 6.1.7601]` (Windows 7)
CPU: Intel i3-2120

### What did you do?
```
pull golang/go from git
cd src
all.bat
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
no test errors

### What did you see instead?
test related errors

full log:
https://pastebin.com/gqhbAWh2

additional information:
`python -V`
`Python 2.7.3`

`gcc -v`
`gcc version 5.1.0 (tdm64-1)`

no antivirus software running on the machine ATM.

**comments:**
`chcp`  works, which i can verify by this small program:
```
package main

import "os/exec"
import "fmt"

func main() {
	_, err := exec.Command("chcp").Output()
	if err != nil {
		fmt.Println("err: ", err)
		return
	}
	fmt.Println("ok")
}
```

calling `exec.Command("cmd", "/c", "chcp")` also works.

i haven't looked at the `gdb` related failures.

report requested by @alexbrainman

**Comment by alexbrainman** [comment]
Thank you for the report:

```
--- FAIL: TestLookPath (0.95s)
        lp_windows_test.go:81: test={rootDir:C:\Windows\TEMP\TestLookPath7703041
39\d0 PATH:p1;p2 PATHEXT:.COM;.EXE;.BAT files:[p1\a.exe p2\a.exe p2\a] searchFor
:a fails:false}: "cmd /c a" command failed, but expected to succeed: exit status
 1 - 'chcp' is not recognized as an internal or external command,
                operable program or batch file.
                C:\Windows\TEMP\TestLookPath770304139\d0\p1\a.exe
FAIL
FAIL    os/exec 4.461s
```

Looks like your cmd.exe calls chcp program. Do you know why? TestLookPath calls "cmd.exe /c test.exe"  with no standard PATH, and I suspect cmd.exe could not find chcp program.

```
--- FAIL: TestWinSplitListTestsAreValid (0.30s)
        path_windows_test.go:88: 0,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
        path_windows_test.go:88: 1,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\n;\r\n"
        path_windows_test.go:88: 2,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na;b\r\n"
        path_windows_test.go:88: 3,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\n;\r\n"
        path_windows_test.go:88: 4,1: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\n;\r\n"
        path_windows_test.go:88: 5,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na;b\r\n"
        path_windows_test.go:88: 6,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
        path_windows_test.go:88: 7,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na;b\r\n"
        path_windows_test.go:88: 8,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
        path_windows_test.go:88: 9,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na;b\r\n"
        path_windows_test.go:88: 10,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
        path_windows_test.go:88: 11,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na;b\r\n"
        path_windows_test.go:88: 12,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
        path_windows_test.go:88: 13,0: execution error exit status 1
                "'chcp' is not recognized as an internal or external command,\r\
noperable program or batch file.\r\na\r\n"
FAIL
FAIL    path/filepath   0.985s
```

Looks the same as above.

```
--- FAIL: TestGdbBacktrace (5.29s)
...
```

No one on that I know of has gdb with Python support. Including our builders. So all these Gdb/python tests are skipped everywhere. You are welcome to fix these tests, but we should modify our builders so they have appropriate Gdb installed first. If you know how to install Gdb, I could show you where the code that configures builders lives. So you could adjust builders config.

Also this https://go-review.googlesource.com/#/c/go/+/102419/ is probably related. Feel free to review the CL.

```
--- FAIL: TestLocalImportsEasySub (0.64s)
        go_test.go:1168: running testgo [build -o ./easysub.exe testdata\local\e
asysub\main.go]
        go_test.go:1169: remove ./easysub.exe: Access is denied.
FAIL
FAIL    cmd/go  120.937s
```

Looks like a dup of #17245 and #23171
Does it fail every time? Even if it fails sometimes, maybe you could debug this. Because we cannot reproduce it often enough to debug it.

Alex

**Comment by neolit123** [comment]
> Looks like your cmd.exe calls chcp program. Do you know why? TestLookPath calls "cmd.exe /c test.exe" with no standard PATH, and I suspect cmd.exe could not find chcp program.

calling `chcp` from `cmd` works for me as mentioned in the first comment in this thread. i guess i need to look at what `lp_windows_test.go` is doing wrong.

> No one on that I know of has gdb with Python support. Including our builders. So all these Gdb/python tests are skipped everywhere. You are welcome to fix these tests, but we should modify our builders so they have appropriate Gdb installed first. If you know how to install Gdb, I could show you where the code that configures builders lives. So you could adjust builders config.

while i've been using `gdb` for 20ish years, i've never used its python features. so i would leave the fix of this to the `gdb + python` experts. i do not understand what `the builders` are.

> Looks like a dup of #17245 and #23171
Does it fail every time? Even if it fails sometimes, maybe you could debug this. Because we cannot reproduce it often enough to debug it.

i think i've seen this error before. i can try debugging this eventually.

thanks

**Comment by alexbrainman** [comment]
> calling chcp from cmd works for me as mentioned in the first comment in this thread.

Test, unlike you, modifies PATH.

> i guess i need to look at what lp_windows_test.go is doing wrong.

That is what I would do.

> while i've been using gdb for 20ish years, i've never used its python features.

Well, your gdb setup is different from mine.

> i do not understand what the builders are.

We have bunch of computers https://build.golang.org that run all.bat for every change we submit. Windows builders have some software installed to execute all.bat. For example gcc. I am certain builders do not have gcc with python setup - otherwise they would have failed the tests. Just like you.

> i can try debugging this eventually.

That would be nice.

Thank you.

Alex

**Comment by neolit123** [comment]
i was on PTO last week and quite busy this week, so i will try to find some time to debug some of the issues here next week.

**Comment by neolit123** [comment]
did a couple of fixes for the `chcp` issues. still not sure why `chcp` is needed though.

this one doesn't happen all the time:
```
--- FAIL: TestLocalImportsEasySub (0.64s)
        go_test.go:1168: running testgo [build -o ./easysub.exe testdata\local\e
asysub\main.go]
        go_test.go:1169: remove ./easysub.exe: Access is denied.
FAIL
FAIL    cmd/go  120.937s
```

and also i'm noticing an infinite loop if i run:
`go test cmd/go`

instead of:
`all.bat`.

**Comment by neolit123** [comment]
full output of:
`go test cmd/go`

`*** Test killed: ran too long (10m0s).`

https://pastebin.com/XNNAKhBW

i see a lot of failed tests in there.

**Comment by alexbrainman** [comment]
> this one doesn't happen all the time:

Does it happen often enough for you to debug? Can you see what the problem is?

> and also i'm noticing an infinite loop if i run:
> go test cmd/go

What do you mean by "infinite loop" ? I suspect no one runs this command. all.bat runs

go test -short cmd/go

so 'go test cmd/go' might take a while, but if takes 10-20 minutes, please create new issue and report which test is too long (by adding -v flag) and we will adjust tests.

> *** Test killed: ran too long (10m0s).

What I said before. Create new issue for that, and someone will adjust tests to make it pass.

Thank you.

Alex

**Comment by neolit123** [comment]
On 27 April 2018 at 13:17, Alex Brainman <notifications@github.com> wrote:

> this one doesn't happen all the time:
>
> Does it happen often enough for you to debug? Can you see what the problem
> is?
>

i didn't have the time to debug it.
maybe next week, but i'm traveling too.

it just happened again from `all.bat`:
```
--- FAIL: TestLinkXImportPathEscape (0.44s)
        go_test.go:4396: running testgo [build -o ./linkx.exe -ldflags
-X=my.pkg
.Text=linkXworked my.pkg/main]
        go_test.go:4405: remove ./linkx.exe: Access is denied.
FAIL
FAIL    cmd/go  101.878s
```

and also i'm noticing an infinite loop if i run:
> go test cmd/go
>
> What do you mean by "infinite loop" ? I suspect no one runs this command.
> all.bat runs
>
> go test -short cmd/go
>
> so 'go test cmd/go' might take a while, but if takes 10-20 minutes, please
> create new issue and report which test is too long (by adding -v flag) and
> we will adjust tests.
>

"infinite loop" - i though the tests are never ending at first, but i guess
they just take a lot of time.


> *** Test killed: ran too long (10m0s).
>
> What I said before. Create new issue for that, and someone will adjust
> tests to make it pass.
>

will do.
thanks.

**Comment by neolit123** [comment]
closing in favor of https://github.com/golang/go/issues/25300
failed tests are now only in `cmd/go`.
