### ISSUE TITLE
net/http.Request.UserAgent() string not a valid UTF-8

### ISSUE THREAD

**Issue by orian** [golang/go#24705]
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Linux, amd-64.

### What did you do?
Serving an HTTP request I've used a User-Agent., below example from a real world server:
https://play.golang.org/p/hyPt1AM19zO

Saved a User-Agent string and read in another programming language caused it to panic.
(check: https://github.com/golang/protobuf/issues/484)

### What did you expect to see?
A valid UTF-8 string to be produced.

### What did you see instead?
Invalid string as in an example.

**Comment by rsc** [comment]
In your example the hex-encoded data corresponds to the Go string literal:

"Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C153 [FBAN/FBIOS;FBAV/91.0.0.41.73;FBBV/57050710;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/11.2.1;FBSS/2;FBCR/OrangeEspa\xf1a;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/0]"

Note the "OrangeEspa\xf1a".

Probably the bytes received in the HTTP request were exactly those bytes and therefore were not valid UTF-8. The HTTP API records the bytes received. There is no guaranteed coercion to valid UTF-8 in this API. If you are going to use them as a protobuf string (or pass them to pickier languages in any other form), then it's true you may have to guard against invalid UTF-8. But that's not the HTTP request reader's job.

**Comment by orian** [comment]
Thanks for a reply and clarification. The example and hex encoding was hand generated by me (didn't know how to inline a incorrect rune).
I've deployed a validation but I thought it may be interesting for someone to leave trace of such problem.
