### ISSUE TITLE
go 1.9.3 failed to get the latest apache thrift package

### ISSUE THREAD

**Issue by ruiyang2015** [golang/go#24708]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ruiyang/Ascend.io/godep:/Users/ruiyang/Ascend.io/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/68/w0ck2sz15yd_zt73kx9x69d80000gn/T/go-build018641077=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-I/usr/local/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/usr/local/lib"
PKG_CONFIG="pkg-config"

### What did you do?
following the instruction on apache golang page: https://github.com/apache/thrift/tree/master/lib/go
trying to run `$ go get git.apache.org/thrift.git/lib/go/thrift/...`
getting ` fatal: repository 'https://git.apache.org/thrift.git/' not found` error
search the issue in golang issue, and found a similar one in 2015 for an earlier version, and that one is already resolved.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
go get successfully get the package

### What did you see instead?
fatal: repository 'https://git.apache.org/thrift.git/' not found

**Comment by AlexRouSg** [comment]
Shouldn't this be reported to thrift instead? If you go to git.apache.org/thrift.git it is a invalid URL even trying to use git on it fails.

**Comment by rsc** [comment]
@AlexRouSg is right. The go command knows about git.apache.org but it will try to git clone https://git.apache.org/thrift.git and that seems to be missing.

https://godoc.org/?q=thrift+apache suggests you should be importing "github.com/apache/thrift/lib/go/thrift". Maybe it moved.
