### ISSUE TITLE
cmd/cgo: invalid flag in #cgo CFLAGS: -fno-plt

### ISSUE THREAD

**Issue by pukapy** [golang/go#24703]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10
### Does this issue reproduce with the latest release?

yes
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/puka/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/puka/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build840200638=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
i installed qt and the bindings for go and i tried to run an example from github but i got this error.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Code for the code i was trying to run:
https://pastebin.com/RWK3aeEw

### What did you expect to see?
My qt application
### What did you see instead?
go build github.com/therecipe/qt/core: invalid flag in #cgo CFLAGS: -fno-plt

**Comment by minaevmike** [comment]
seems `CGO_CFLAGS_ALLOW` enviroment variable (https://github.com/golang/go/blob/master/src/cmd/go/alldocs.go#L1038) can help.

**Comment by AlexRouSg** [comment]
cc @ianlancetaylor

**Comment by bcmills** [comment]
(See also https://github.com/golang/go/issues/23749.)

**Comment by AlexRouSg** [comment]
You can leave this open if you want it to be added to the list so you don't have to use `CGO_CFLAGS_ALLOW`

**Comment by rsc** [comment]
no-plt is ok
