### ISSUE TITLE
parenthesis in the return clause of the function definition

### ISSUE THREAD

**Issue by samribeiro** [golang/go#24723]
### What version of Go are you using (`go version`)?
go1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
Don't think this is a bug, it is more of an enhancement. I am not too strong about it and I recognize I probably miss background, but:

I keep forgetting to add parenthesis to the return clause of the function definition:

```go
func FunctionName(arg argType) string, bool, int {
...
}
```
syntax error: unexpected comma after top level declaration

I am not sure why they are needed though.

**Comment by cznic** [comment]
> I am not sure why they are needed though.

`func f() func() int, int { ... }`

How many return values does `f` have?

**Comment by samribeiro** [comment]
well that is horrible, but is good enough to educate me thanks.
