### ISSUE TITLE
gccgo: crash when compiling code containing some type alias

### ISSUE THREAD

**Issue by dotaheor** [golang/go#24722]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

please view https://github.com/golang/go/issues/24721 for details.

```
$ go build -compiler gccgo
```

### What did you expect to see?

not crash

### What did you see instead?

crash

**Comment by tklauser** [comment]
Reproducing program extracted from #24721:

```go
package m3

import "time"

type t = time.Time
type T = time.Time

type A = struct{t}
type B = struct{T}
```

```go
import "m3"
import "time"

type t = time.Time
type T = time.Time

type A = struct{t}
type B = struct{T}

func main() {
   var a, b interface{} = m3.A{}, m3.B{}
   var x, y interface{} = A{}, B{}
   println(a == x) // true
   println(b == y) // true
   
   _ = A(m3.A{}) // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
   _ = B(m3.B{}) // ok
   
   println(a == b) // true
   println(x == y) // true
   _ = B(A{})       // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
   _ = m3.A(m3.B{}) // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
}
```

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
@dotaheor Are you saying that for you gccgo crashes?  It doesn't crash for me.  Which version of gccgo are you running?

**Comment by dotaheor** [comment]
```
$ gccgo a.go
gccgo (Debian 7.3.0-3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This command `go run -compiler gccgo a.go` also crash.

Here is another simple program for verifying.
```
package main

import (
	"fmt"
	"time"
)

type t = time.Time
type T = time.Time

type A = struct{ t }
type B = struct{ T }

func main() {
	var a A
	var b B
	fmt.Println(interface{}(b) == interface{}(a)) // true
	//fmt.Println(b == a)
}
```

BTW, the bug https://github.com/golang/go/issues/24721 also exists for gccgo 7.3.0.

**Comment by dotaheor** [comment]
I just upgraded gccgo to `gccgo (Debian 8-20180414-1) 8.0.1 20180414 (experimental) [trunk revision 259383]`, which doesn't crash and print the right result. Cool!

**Comment by ianlancetaylor** [comment]
Thanks for checking.
