### ISSUE TITLE
I am not able to use  standard library package.

### ISSUE THREAD

**Issue by JitinGuglani** [golang/go#24726]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
I do not know.

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\play-with-go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
I am developer.

If possible, provide a recipe for reproducing the error.
I am trying to use func MarshalPKCS8PrivateKey(key interface{}) ([]byte, error), but I got Error:
.\main.go:90:21: undefined: x509.MarshalPKCS8PrivateKey
A complete runnable program is good.

A link on play.golang.org is best.

### What did you expect to see?
The function I am trying to use the function which is defined in the x509 package. I should be able to use this.

### What did you see instead?

Error.

**Comment by dominikh** [comment]
x509.MarshalPKCS8PrivateKey was added in Go 1.10.

**Comment by JitinGuglani** [comment]
Thanks. Upgraded to Go 1.10. Its working now.

**Comment by yuanyunliang** [comment]
it works,thanks
