### ISSUE TITLE
cmd/compile: emit info about used types in local types section of export data, for checking by ld.

### ISSUE THREAD

**Issue by rsc** [golang/go#2474]
<pre>r:
i put in a print statement and then gotest wouldn't compile the program, which was
correct behavior: a function had changed signature
so before i touched the file gotest was somehow linking incorrectly. i can't explain it
and that's what was wrong

me:
there is one case where that can still happen
if you have an exported struct in one package and another package emits references to
fields in that struct, but it doesn't also emit a copy of that struct in its own export
data, then the linker can't tell if it saw the same definition as the other package
i have been meaning to emit as part of the read-only-by-the-linker export data 'these
are the struct definitions i used while generating code'</pre>

**Comment by thanm** [comment]
Pretty sure this bug is obsolete, closing it out.
