### ISSUE TITLE
x/vgo: include GOPROXY in output of vgo env

### ISSUE THREAD

**Issue by myitcv** [golang/go#24748]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10.1 linux/amd64 vgo:2018-02-20.1
```

Specifically `vgo` is as of 5db81b5cd6ab5ee1dd1b1b0ee0843f194ab7b908

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/.mountpoints/x"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build749051986=/tmp/go-build -gno-record-gcc-switches"
VGOMODROOT=""
```

### What did you do?

```
vgo env | grep GOPROXY
```

### What did you expect to see?

```
GOPROXY=""
```

(or whatever value is present in that environment variable)

### What did you see instead?

Nothing; `GOPROXY` is not included in the env output.

**Comment by vbmade2000** [comment]
Can I wok on this issue ?

**Comment by rsc** [comment]
SGTM.

**Comment by myitcv** [comment]
This has been started in https://go-review.googlesource.com/c/vgo/+/105335

**Comment by vbmade2000** [comment]
@myitcv Ok
