### ISSUE TITLE
cmd/go: TestLocalImportsEasy flake

### ISSUE THREAD

**Issue by josharian** [golang/go#24740]
https://build.golang.org/log/cadb4ff3677483c2818a2ec0fa8a3d6a08f73f6a

```
--- FAIL: TestLocalImportsEasy (0.58s)
	go_test.go:1162: running testgo [build -o ./easy.exe testdata\local\easy.go]
	go_test.go:1163: remove ./easy.exe: Access is denied.
FAIL
FAIL	cmd/go	165.352s
```

Looks like something like this happened before: https://github.com/golang/go/issues/11217

The fix there was to make sure that executable filenames are distinct. From a quick glance, it appears to me that `testLocalEasy` is called from two locations in cmd/go/go_test.go, and it appears superficially that both locations would end up using `easy.exe`. Similarly so for `testLocalEasySub`, `testLocalHard`, and maybe others. Maybe the same fix is called for here?

cc @alexbrainman @ianlancetaylor

**Comment by alexbrainman** [comment]
> From a quick glance, it appears to me that testLocalEasy is called from two locations in cmd/go/go_test.go, and it appears superficially that both locations would end up using easy.exe

Yes, testLocalEasy is called from TestLocalImportsEasy and TestBadImportsEasy, but TestBadImportsEasy is skipped on windows:
```
c:\>go test -v -run=TestBadImportsEasy$ cmd/go
=== RUN   TestBadImportsEasy
--- SKIP: TestBadImportsEasy (0.00s)
        go_test.go:1215: skipping test because "#$%:, &()*;<=>?\\^{}" is an invalid directory name
PASS
ok      cmd/go  9.270s

c:\>
```
So I don't see how this can be a problem. But I have been wrong before. :-)

For cross-reference TestLocalImportsEasySub is also mentioned on #24709

Alex

**Comment by josharian** [comment]
Thanks for the reference, Alex. Looks like this is a dup of #23171.
