### ISSUE TITLE
doc/install: mention how to update environment variables before testing the installation

### ISSUE THREAD

**Issue by agrinevich** [golang/go#24756]
go1.10.1 linux/amd64
debian 9
installing go
editing $HOME/.profile doesn't help but $HOME/.bashrc does.
---
There is a paragraph 
"Add /usr/local/go/bin to the PATH environment variable. You can do this by adding this line to your /etc/profile (for a system-wide installation) or $HOME/.profile"
 under "Install the Go tools" header. 
It would be nice to append "... or $HOME/.bashrc" there.
https://golang.org/doc/install

**Comment by bcmills** [comment]
If your `.profile` is idempotent, you don't even need to log out: you can just source it again in the current shell. (But I agree that we should mention that in the doc.)

**Comment by agnivade** [comment]
It would still be good to mention the bit about logging out and in. Would you like to send a PR ?

Since you encountered it first hand, you can probably write in a manner suited for people who can stumble into this issue again.

**Comment by agrinevich** [comment]
Probably someone more experienced can do it. Text to append on page (for Linux section):
---
For logging in with graphical display manager you should create or edit file ~/.xsessionrc and put there:
```
if [ -f ~/.profile ]; then
. ~/.profile
fi
```
Then log out and log in again.

**Comment by mvdan** [comment]
I think the advice should be more generic, or link to a page on the internet covering common issues with shell profile files. Otherwise, this advice is only going to apply to certain Linux systems that use X11, potentially further confusing users that don't have that setup.

**Comment by agrinevich** [comment]
Agree. I think it would be better someone Linux seasoned and with fluent english write this text because I'm new to Linux.

**Comment by forskning** [comment]
Debian based distros now have /etc/profile.d.

[bootstrapping go](http://nurmi-labs.blogspot.com/2017/08/bootstrapping-go.html)

The above is written for go-1.9.2 using gcc-4.7.1 , and I cited therein V. Batts' [.SlackBuild](http://slackbuilds.org/repository/14.2/development/google-go-lang/), which obviously in 2018 has been  updated.

[Linux, Mac OS X, and FreeBSD tarballs](https://golang.org/doc/install#tarball)

Using the path for the go executable from the above section, V. Batts `$GOROOT_FINAL` in the below would be` /usr/local/go`.

```
# Put the profile scripts for setting PATH and env variables
mkdir -p $PKG/etc/profile.d
cat > $PKG/etc/profile.d/go.csh << EOF
#!/bin/csh
setenv GOROOT ${GOROOT_FINAL}
setenv PATH \${GOROOT}/bin:\${PATH}
EOF
cat > $PKG/etc/profile.d/go.sh << EOF
#!/bin/sh
export GOROOT="${GOROOT_FINAL}"
export PATH="\${GOROOT}/bin:\${PATH}"
EOF

chmod 0755 $PKG/etc/profile.d/go.csh
chmod 0755 $PKG/etc/profile.d/go.sh
```
Such an executable shell script can also be sourced.
```
#!/bin/sh
export GOROOT=/usr/local/go
export PATH=${GOROOT}/bin:${PATH}
```

**Comment by forskning** [comment]
https://github.com/golang/go/wiki/SettingGOPATH

Perhaps the idea for the use of a shell's rc file came from the above Wiki Page.
