### ISSUE TITLE
net: listening on a local port for a test requires tedious boilerplate

### ISSUE THREAD

**Issue by glasser** [golang/go#24778]
In the stdlib alone, there are 6 functions called `newLocalListener` that do something roughly like

```
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		if l, err = net.Listen("tcp6", "[::1]:0"); err != nil {
			panic(fmt.Sprintf("httptest: failed to listen on a port: %v", err))
		}
	}
	return l
```

(there are admittedly differences in between them in how they handle errors, etc)

It would be nice (for consumers of the stdlib as well) if there was an easy way to do this with one line.

You might think that listening on the unspecified interface would help, but there are two downsides. First, you might not want your test server to be externally accessible! Second, if you listen on the unspecified interface then your listener.Addr() is like "0.0.0.0" or "::" which you may not be able to connect to in all environments (and you may run into issues like #24737 as well).

(Arguably this would go well in a net/nettest package like net/http/httptest, but that isn't a thing.)

**Comment by neild** [comment]
I presume there's a reason to not use `net.Listen("tcp", "localhost:0")`, but I'm not certain what it is.

**Comment by neild** [comment]
...oh, net.Listen requires that you specify "tcp" or "tcp6". That would be the reason. :)

**Comment by bradfitz** [comment]
Perhaps in the spirit of https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06 we should special case a lookup of "localhost" when the network is "tcp" (not "tcp4" or "tcp6") and just do the thing, rather than adding any new API.

That is, if your system's DNS says that "localhost" is "127.0.0.1" and you're on an IPv6-only system, then Go doesn't care about your DNS if you say `net.Listen("tcp", "localhost:0")` and we instead listen on `::1`, because that's what you *meant* by "localhost".

/cc @mikioh @ianlancetaylor

**Comment by neild** [comment]
Even without special casing, I believe "localhost" should do the right thing on any properly configured system. My `/etc/hosts` contains localhost entries for both `127.0.0.1` and `::1`, and `net.Listen("tcp", "localhost:0")` behaves reasonably if I comment out one or the other.

(My previous comment about "tcp" vs. "tcp6" is wrong; "tcp" happily resolves either v4 or v6 addresses.)

**Comment by bradfitz** [comment]
>  I believe "localhost" should do the right thing on any properly configured system

My proposal is we let localhost be localhost regardless of their config.

**Comment by rsc** [comment]
Closing as dup of #22826 but it seems like a good idea, provided we can get some insight into how close the draft is to being an RFC. Note that the draft in this issue is from August 2017 while the draft in the other issue is newer, from December 2017.

**Comment by neild** [comment]
#22826 (let localhost be localhost) SGTM, but I think it's reasonable to use `net.List("tcp", "localhost:0")` before we do that or even if we don't.
