### ISSUE TITLE
undefined: ssh.ClientAuth

### ISSUE THREAD

**Issue by nzoueidi** [golang/go#24777]
Hey folks,

I am having this error: undefined: ssh.ClientAuth while building my script.
I am importing this package "golang.org/x/crypto/ssh". However, I still experiencing the same behavior.

Refering to this thread[1] in google groups; the guy there have succeeded building/running the SSH func using the version 1.6 of go.

Besides, based on this thread in the maillist of go-nuts, the crypto/ssh go package was changed on April 9th 2016. Althoguh, I tried to update all the packages and its sub-packages by running the following go command:

go get -u -v golang.org/x/crypto/...

The update succeeded, but I am still having the same behavior.

My go version is 1.9.4
I am running this on Ubuntu 16.04 
This is the output of go env
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/local/nzoueidi/gobackup"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build895283673=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

I didn't tested on go 1.10.x so I don't know if it is reproducible or not there.

[1] https://groups.google.com/forum/#!topic/golang-nuts/MNSIwH1hiG8

**Comment by agnivade** [comment]
Your code is outdated. So it does not matter if you update your package, your code will still not compile. You need to use the old package `"code.google.com/gosshold/ssh"` if you want your existing code to compile.

Otherwise, if you are okay with changing your code, I think the equivalent alternative is to now use `ssh.AuthMethod` instead of `ssh.ClientAuth`.

**Comment by bradfitz** [comment]
code.google.com shut down some time ago.

But yes, you'll need to update your code. It seems you were using a very old version of the ssh package's API, which has apparently since changed.
