### ISSUE TITLE
syscall: TestPassFD fails on netbsd/arm

### ISSUE THREAD

**Issue by tklauser** [golang/go#24771]
```
--- FAIL: TestPassFD (0.13s)
	syscall_unix_test.go:210: child process ReadAll: "", invalid argument; want "Hello from child process!\n"
```

See the recent build logs:

https://build.golang.org/log/256ba2fefaa05e5bcf91e36e824a4aa7edda4e45
https://build.golang.org/log/6a716f8518326a60f291a7efad8884d27f6c4470
https://build.golang.org/log/fff5ee432875da78bd360ef7033fd85f26999a84

/cc @bsiegert @bradfitz

**Comment by katiehockman** [comment]
Note for future triaging, this is still failing for the same reason. More recent failure: https://build.golang.org/log/efdaf6aacac31822e9c3312a5e635a7102bc822b
