### ISSUE TITLE
x/build/maintner: two Gerrit CLs have unexpected Status value

### ISSUE THREAD

**Issue by shurcooL** [golang/go#24783]
[`maintner.GerritCL.Status`](https://godoc.org/golang.org/x/build/maintner#GerritCL.Status) is documented as:

```Go
// Status will be "merged", "abandoned", "new", or "draft".
Status string
```

That's mostly true, except for 2 CLs in the `go` repo:

```
2018/04/05 21:51:56 empty status for CL 44073
2018/04/05 21:51:56 empty status for CL 44072
```

Those 2 CLs have empty string value in `Status` field.

Either the documentation needs to be updated, or this is bug and those 2 CLs shouldn't have empty status.

**Comment by bradfitz** [comment]
Anything interesting about those CLs?

**Comment by FiloSottile** [comment]
They both 404 for me.

**Comment by andybons** [comment]
Both are 404’s, which means it’s likely that the CLs were deleted. We don’t account for deleted changes: #22635.

**Comment by billotosyr** [comment]
Previously mentioned: #22060

**Comment by shurcooL** [comment]
I'll close this as duplicate of #22060.
