### ISSUE TITLE
x/build/maintner: refactor out gcs and api from maintnerd

### ISSUE THREAD

**Issue by broady** [golang/go#24786]
I want to create a customized maintnerd (one feature is being able to add tracked repos while the daemon is running).

Here's a small proposal to make that more possible:

* move all of the GCS (gcslog.go) and API functions (api.go) to a new package: "maintnerapi". optional: move GCS functionality into its own package.
* ~~move the protos into a subpackage (currently named "apipb" but maybe "maintpb" is better?)~~ nevermind, there's already a maintpb for storage.

maintnerd then becomes a 500 line program that uses the maintnerapi package, which looks like this:

```
PACKAGE DOCUMENTATION

package maintnerapi
    import "."


FUNCTIONS

func NewAPIService(corpus *maintner.Corpus) apipb.MaintnerServiceServer

TYPES

type GCSLog struct {
    // contains filtered or unexported fields
}

func NewGCSLog(ctx context.Context, bucketName string) (*GCSLog, error)

func (gl *GCSLog) CopyFrom(src maintner.MutationSource) error
    CopyFrom is only used for the one-time migrate from disk-to-GCS code
    path.

func (gl *GCSLog) GetMutations(ctx context.Context) <-chan maintner.MutationStreamEvent

func (gl *GCSLog) Log(m *maintpb.Mutation) error

func (gl *GCSLog) ServeJSONLogsIndex(w http.ResponseWriter, r *http.Request)

func (gl *GCSLog) ServeLogFile(w http.ResponseWriter, r *http.Request)
```

**Comment by shurcooL** [comment]
Would this affect the users of [`golang.org/x/build/maintner/godata`](https://godoc.org/golang.org/x/build/maintner/godata) package?

**Comment by bradfitz** [comment]
Okay, SGTM. And I do like the idea of moving GCSLog to its own package.
