### ISSUE TITLE
syscall: ECONNRESET is not err.Temporary()

### ISSUE THREAD

**Issue by powerman** [golang/go#24808]
Issue #6163 result in adding ECONNRESET to list of temporary errors. While this may be correct for accept syscall (btw, this errno is not documented on accept(2) and maybe it was returned by accept in some Linux kernel versions by mistake), it's for sure wrong for write/send syscalls: https://stackoverflow.com/a/2979806/113120

Either ECONNRESET should be removed from list of temporary errors, or net.OpError should be modified to count ECONNRESET as Temporary() only when `Op=="accept"`.

**Comment by bradfitz** [comment]
@powerman, are you reporting a regression in Go 1.4?

The stackoverflow thread is about Python.

Is there some context I'm missing about why this is now relevant, years later?

Did this cause a bug somewhere, or were you just reading code?

**Comment by powerman** [comment]
@bradfitz Stackoverflow is about syscalls, python is just an example and should have no importance. Yes, I'm just reading the code and man pages - issue looks obvious, but if it's required I can try to implement example from stackoverflow in Go. Original issue was initiated by question in maillist: https://groups.google.com/forum/#!topic/golang-nuts/5Mcc-idtQcg

**Comment by bradfitz** [comment]
I'm reluctant to change this because it seems more likely to break more people than it fixes and it's been like this forever.

But if you have a good example of a Go program where the behavior is clearly wrong, we could try it out and see what the fallout looks like.

**Comment by powerman** [comment]
Actually it's enough to output Temporary() at end of example mentioned in maillist to see:
```
0
1
2
3
4
write tcp 127.0.0.1:43412->127.0.0.1:40447: write: connection reset by peer
temporary: true
```
Here is modified code: https://play.golang.org/p/Jphm_VSzM1H (run on Linux, not in playground).
Probably it can be simplified even more, but, as I said, issue is obvious: ECONNRESET means TCP RST packet was received, which is temporary error in accept() and fatal in write()/send().

**Comment by bradfitz** [comment]
Sure, we can try special-casing "accept". @ianlancetaylor?

**Comment by networkimprov** [comment]
Please add the Go 1.11 milestone to this issue.

I just encountered this in real-world use by reporting net.Error.Temporary() in logs, in hopes of seeing actually-recoverable errors :-)

**Comment by ianlancetaylor** [comment]
@networkimprov Done, but in general we don't promise that every issue has the milestone in which it was fixed.  It's a good idea but it's not something we have any way of doing reliably.

**Comment by dcormier** [comment]
> I'm reluctant to change this because it seems more likely to break more people than it fixes and it's been like this forever.

Confirmed. Broke something I had in place in a hard-to-notice way.
