### ISSUE TITLE
cmd/link: provide better error message than "relocation target main.main not defined" when no func main provided

### ISSUE THREAD

**Issue by josharian** [golang/go#24809]
There has been a recent spate of issues and noise on issues, in which people report that the linker is complaining: `relocation target main.main not defined`. This happens when the main package has no `func main`.

Since that is a common error mode, particularly for new Go programmers, we should provide a more useful error message.

I thought there was an existing issue open for this, but I can't find it.

**Comment by ALTree** [comment]
> I thought there was an existing issue open for this, but I can't find it.

That's #10978

**Comment by josharian** [comment]
Thanks. I think those are close enough that I'll close this as a dup.
