### ISSUE TITLE
net/http: request.Referer()

### ISSUE THREAD

**Issue by AnotherGoogleFan** [golang/go#24816]
In source code, the Referer() function is like this:
`func (r *Request) Referer() string {
	return r.Header.Get("Referer")
}`

But in many places, the referrer in header is Referrer, not Referer. So I guess this can be improved, for example, like this:
``func (r *Request) Referer() string {
	if referrer := r.Header.Get("Referer"); referrer != "" {
		return referrer
	}
	return r.Header.Get("Referrer")
}``

**Comment by dominikh** [comment]
> in many places

can you point to some of these places?

**Comment by vdobler** [comment]
The first document  https://w3c.github.io/webappsec-referrer-policy clearly states that the header still is called "Referer" and the new header "Referrer-Policy" does not duplicate that typo. The second document   https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-95229140 is not concerned at all with HTTP headers.
Can you provide supporting evidence that the HTTP Referer header is written as "Referrer" in the wild?

**Comment by bradfitz** [comment]
I don't think we're going to change this, so I'm going to close this for now. We can reopen if there's evidence that this is actually common in the wild, but I've never heard of it.
