### ISSUE TITLE
access: GitHub ("go-approvers")

### ISSUE THREAD

**Issue by agnivade** [golang/go#24829]
Hi,

I have been contributing for close to a year now. I started with various contributions to the standard library. But of late, have been focusing my attention on godoc.

I am much more active in the github issue tracker. My primary focus there is to go through old issues, following up with the issue creator and applying proper labels as necessary. There have been quite a number of scenarios which needed closing or proper re-labelling.

Hence, I am submitting my request to be a proper "Go Gardener" :). Thought you guys can do with an extra hand, and better coverage during non-US hours.

https://github.com/orgs/golang/teams/go-approvers 

**Github activity-** https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aopen+commenter%3Aagnivade
**Gerrit activity-** https://go-review.googlesource.com/q/owner:agniva.quicksilver%2540gmail.com

/cc @andybons @bradfitz

**Comment by andybons** [comment]
Done! 🎉 

Have a look at golang.org/wiki/Gardening if you haven’t already. Welcome to the (Gardening) team!

**Comment by agnivade** [comment]
Yep, I have :) Thanks !
