### ISSUE TITLE
x/build/devapp: per-release burndown chart for issues

### ISSUE THREAD

**Issue by andybons** [golang/go#24827]
We should have a burndown chart of remaining issues in a release so that we can track progress.

**Comment by bradfitz** [comment]
CL lacks a reference to this bug: https://go-review.googlesource.com/c/build/+/150639

**Comment by andybons** [comment]
Ah shoot. Forgot this even existed :(

Fixed with https://github.com/golang/build/commit/2b0e3d65700ec495249be516af5e5860cd090f2b
