### ISSUE TITLE
syscall: verify that windows uintptr structure fields are not pointers

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#24820]
Recently https://github.com/golang/go/issues/21376#issuecomment-379898563 we discovered that using uintptr structure fields to store pointers will confuse GC.

https://go-review.googlesource.com/#/c/go/+/106275/ converts all syscall code used by crypto/x509 package to use syscall.Pointer instead of uintptr. But there are other uintptr fields in syscall.

This issue is so we don't forget to check them all.

Alex

**Comment by ianlancetaylor** [comment]
ping @aclements
