### ISSUE TITLE
exp/inotify: Read hangs, AddWatch, RemoveWatch fail on recreated directories

### ISSUE THREAD

**Issue by ugorji** [golang/go#2483]
<pre>Before filing a bug, please check whether it has been fixed since
the latest release: run &quot;hg pull&quot;, &quot;hg update default&quot;, rebuild, and
retry
what you did to
reproduce the problem.  Thanks.

What steps will reproduce the problem?
- If I am watching a directory, and delete it, and recreate it, 
  and watch it again, any events after that are hosed:
  - the event.Name is incomplete, with the path stripped out e.g. 
    instead of /home/myname/a/b/c/d.txt, I get /d.txt
    instead of /home/myname/a/b/c/, I get &quot;&quot;
  - RemoveWatch fails with message: invalid argument
  - Close() doesn't really close. Most times, the reader goroutine hangs.

Which compiler are you using (5g, 6g, 8g, gccgo)?
8g

Which operating system are you using?
Ubuntu Linux 2.6.38-12-generic #51-Ubuntu SMP 32-bit GNU/Linux

Which revision are you using?  (hg identify)
6abf04c86097+ tip

Please provide any additional information below.</pre>

**Comment by rsc** [comment]
fsnotify has been removed from exp
