### ISSUE TITLE
doc/contribute.html: clarify commit-message conventions

### ISSUE THREAD

**Issue by bcmills** [golang/go#24852]
#24832 proposes that we auto-wrap commit messages when importing from GitHub.

It would probably also be a good idea to document our wrapping conventions: I don't currently see that detail on https://golang.org/doc/contribute.html#commit_changes, although the whole page is a bit difficult to skim as a reference anyway.

I initially had some difficulty with the package-prefix convention too: more examples would probably be helpful there. For example, it's not obvious what to do with the `x/` repos, or packages with nested paths, or things that are not importable Go packages.

(One can discover those conventions by reading the change history, but that seems like a high bar for a first-time contributor who may well just be fixing a typo in a doc comment.)

**Comment by myitcv** [comment]
> #24832 proposes that we auto-wrap commit messages when importing from Gerrit.

... from _Github_. At least that was my intention...

**Comment by bcmills** [comment]
Yep, I thinko'd it.

**Comment by mbj36** [comment]
@bcmills 

I am interested in taking up this issue, Am i missing something because i see https://github.com/golang/go/blob/master/doc/contribute.html is bit different from https://golang.org/doc/contribute.html ?

**Comment by agnivade** [comment]
The golang.org site does not reflect master. Try https://tip.golang.org/doc/contribute.html.

**Comment by mbj36** [comment]
@agnivade  How can i test the doc locally ?
