### ISSUE TITLE
cmd/go: invalid flag in #cgo LDFLAGS: -fopenmp

### ISSUE THREAD

**Issue by gao8954** [golang/go#24858]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version 1.10.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gaodong/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data1/commonData/gaodong/gowork/ad-ctr-service"
GORACE=""
GOROOT="/data1/commonData/gaodong/gowork/go"
GOTMPDIR=""
GOTOOLDIR="/data1/commonData/gaodong/gowork/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build992507118=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by agnivade** [comment]
Please fill up the complete issue template. Thanks.

**Comment by agnivade** [comment]
Thanks. @gao8954 - If this is about `-fopenmp` to be added to the whitelist, I would request you to close this issue and add a comment on #23749.

**Comment by tklauser** [comment]
FWIW, `-fopenmp` was whitelisted in https://golang.org/cl/93836 which was cherry-picked to the `go1.10` release branch in https://golang.org/cl/94676 which means it should be part of Go 1.10 as well as Go 1.10.1

@gao8954 please describe the steps you performed before seeing the error. Please also make sure you are really using Go 1.10.1 to compile.

**Comment by gao8954** [comment]
@agnivade yes but how  -fopenmp to be added to the whitelist ,i am try it still does not work

**Comment by gao8954** [comment]
@tklauser   i am use   // #cgo LDFLAGS: -L../lib -lstdc++ -lz -lrt -lm -lpthread -fopenmp  ,and use GO version 1.10.1   it is still invalid flag,Is my method wrong?

**Comment by AlexRouSg** [comment]
@tklauser `-fopenmp` is only whitelisted as a cflag not a ldflag.
