### ISSUE TITLE
runtime: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by iceooacai** [golang/go#24861]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 windows/amd64

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoPath\;D:\Server_正式服
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build259
987786=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I did nothing

### What did you expect to see?
Was expecting program could run fluently without any crash

### What did you see instead?

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x7ef0128 pc=0x450f79]

runtime stack:
runtime.throw(0xf94e32, 0x2a)
	C:/Go/src/runtime/panic.go:619 +0x88
runtime.sigpanic()
	C:/Go/src/runtime/signal_windows.go:161 +0x170
runtime.gentraceback(0x45c90e, 0x7eefe60, 0x0, 0xc047af9b00, 0x0, 0x88ef260, 0x40, 0x0, 0x0, 0x6, ...)
	C:/Go/src/runtime/traceback.go:280 +0x14f9
runtime.sigprof(0x45c90e, 0x7eefe60, 0x0, 0xc047af9b00, 0xc0422a6c00)
	C:/Go/src/runtime/proc.go:3707 +0x4aa
runtime.profilem(0xc0422a6c00)
	C:/Go/src/runtime/os_windows.go:839 +0xea
runtime.profileloop1(0x0, 0x0)
	C:/Go/src/runtime/os_windows.go:858 +0xe6
runtime.externalthreadhandler(0x88efb90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Go/src/runtime/sys_windows_amd64.s:263 +0x95

goroutine 1 [chan receive]:
MyEngine/routineevent.(*RoutineEvent).Run(0x14e5c40, 0xc0430e4000)
	D:/Server/src/MyEngine/routineevent/routineevent.go:119 +0x541
MyServer_Module/module_logic.Run()
	D:/Server/src/MyServer_Module/module_logic/module_logic.go:305 +0x132
MyServer_Module/module_run.Start(0xc042210fc0, 0x1, 0x1, 0x0, 0x0)
	D:/Server/src/MyServer_Module/module_run/module_run.go:31 +0xb7
main.main()
	D:/Server/src/MyServerAll/main.go:34 +0x35f

goroutine 17 [syscall, 1212 minutes]:
os/signal.signal_recv(0x0)
	C:/Go/src/runtime/sigqueue.go:139 +0xad
os/signal.loop()
	C:/Go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
	C:/Go/src/os/signal/signal_unix.go:28 +0x48
```

**Comment by ALTree** [comment]
> Was expecting program could run fluently without any crash

What program? There's no code in your message.

**Comment by iceooacai** [comment]
It's a large program , server part of an online game, too much code to attach, can't  position which part cost the crash right now

**Comment by ALTree** [comment]
1. Does the it cgo?
2. Does compiling and then running it with the race detector enabled (`-race`) prints any race warning?

**Comment by iceooacai** [comment]
1.No cgo
2.Hundreds of player online right now, can't use race detector in case of high CPU&RAM usage

**Comment by iceooacai** [comment]
Oh, it does use cgo, it imported a package "gopkg.in/mgo.v2" and this package use cgo

**Comment by ALTree** [comment]
This looks like it may be caused by memory corruption, either by erroneous cgo code or by a data race in your code. You should find a way to deploy a race-enabled version of the code on some subset of your servers or something like that.

I don't see how we could investigate (or do anything about) this, without having a reproducer or anything to work on.


cc @aclements in case he has something to say about the stack-trace

**Comment by iceooacai** [comment]
Thank you very much, I'll try to find one

**Comment by ianlancetaylor** [comment]
This looks like a profiling signal occurred on a stack with an invalid frame pointer.  That should in general be impossible; not sure what happened here.

**Comment by ianlancetaylor** [comment]
I think that to fix this we will need a way to reproduce this ourselves.

**Comment by agnivade** [comment]
Hey @iceooacai - just wanted to check if you were able to make any progress on this ? We would need a short reproducer to debug this further, or you can also try running a race-detection enabled version of your code.

As a last resort, please also try with 1.12beta2 if that makes any difference. Thanks.

**Comment by seanybaggins** [comment]
Hi, I think I have the same issue. I am duel booting GalliumOS and ChromeOS on an Asus Chromebook c302 flip. I am developing on GalliumOS. I am using the hedera hashgraph go sdk. I believe that one of their functions Public() is making a system service call that is causing a segmentation fault.

### What version of Go are you using (`go version`)?
```txt
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/Sean/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/Sean/Dropbox/Research"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451736839=/tmp/go-build -gno-record-gcc-switches"
```

### Does this issue reproduce with the latest release?
yes

### What did you do?
Attempted to run the following program using the hedera hashgraph go sdk.
```go
package main

import (
	"fmt"

	"github.com/hashgraph/hedera-sdk-go"
)

func main() {
	secret, _ := hedera.GenerateSecretKey()

	fmt.Printf("Proof this line is printing.\n")

	public := secret.Public()

	fmt.Printf("public   = %v\n", public)
}

```

### What did you expect to see?
```txt
Proof this line is printing.
public   = aBunchOfNumbers
```

### What did you see instead?
```txt
Proof this line is printing.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x652bd3]

runtime stack:
runtime.throw(0x6ae516, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x4910b0, 0xc000038640, 0x1)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000038610 sp=0xc0000385d8 pc=0x40ae7e
github.com/hashgraph/hedera-sdk-go._Cfunc_hedera_public_key_from_secret_key(0xc0000161e0, 0x62ad80abe23ed, 0x20dff79ceacd5, 0x1bc391460852d, 0x17de07be442d9)
        _cgo_gotypes.go:450 +0x4e fp=0xc000038640 sp=0xc000038610 pc=0x48fdae
github.com/hashgraph/hedera-sdk-go.SecretKey.Public(0x40964715b4e53414, 0x614e508bbaa7853f, 0x8276fd839d5589b6, 0x62cfae0d1f6003a9, 0x0, 0x0, 0x0, 0x0)
        puposelyOmmitedDirectoryName/src/github.com/hashgraph/hedera-sdk-go/crypto.go:49 +0x66 fp=0xc0000386b8 sp=0xc000038640 pc=0x490486
main.main()
        puposelyOmmitedDirectoryName/src/Generate Keys/keys.go:14 +0xa9 fp=0xc000038798 sp=0xc0000386b8 pc=0x490d99
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0000387e0 sp=0xc000038798 pc=0x431517
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000387e8 sp=0xc0000387e0 pc=0x4597c1
exit status 2
```
### Steps to reproduce
1. Create an environment that is using GalliumOS and Go
2. Follow the install instructions for the hedera go sdk up to and including the section **Installing the Hedera SDK for Go** [here](https://github.com/hashgraph/hedera-sdk-go)
Note: I had to use `sudo apt-get install git-lfs` rather than `sudo apt install git-lfs` specified in the instructions.
3. Copy and past the code I provided in the **What did you do?** section and run the code.
