### ISSUE TITLE
cmd/internal/obj/x86: imprecise "offset overflow" error message on AMD64

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#24871]
[CL59630](https://go-review.googlesource.com/c/go/+/59630) introduced additional offset overflow checks for AMD64. 

This issue reports regression in error message quality.

### What did you do?

Assemble this file with `go tool asm` on AMD64 platform:
```asm
TEXT badOffset(SB), 0, $0
        MOVL 999999999999(AX), AX
        RET
```

### What did you expect to see?

Error about offset (displacement) overflow.
Something like "offset too large".

### What did you see instead?

Generic "invalid instruction" error.
```
go tool asm foo.s
asm: invalid instruction: 00000 (foo.s:2)	MOVL	999999999999(AX), AX
asm: assembly failed
```

-----

**Note**: it works on `GOARCH=386` as expected:
```
GOARCH=386 go tool asm foo.s
asm: offset too large in 00018 (foo.s:2)	MOVL	999999999999(AX), AX
asm: assembly failed
```

Related to #21860.

**Comment by andybons** [comment]
@randall77
