### ISSUE TITLE
access: cflewis

### ISSUE THREAD

**Issue by cflewis** [golang/go#24886]
Hello there,
I have joined Google's team working on Go and would appreciate GitHub access, as well as Gerrit access and TryBot access.

The docs tell me I should reference https://go-review.googlesource.com/#/admin/groups/1030,members , so please consider it referenced :)

**Comment by andybons** [comment]
GitHub invite granted. Following up on which email to use for Gerrit.

**Comment by andybons** [comment]
Your @google.com account has been added. Just ping me directly when you’ve registered using your @golang.org account
