### ISSUE TITLE
x/crypto/acme/autocert: clarify usage of (*Manager).GetCertificate

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#24894]
Would be nice to have a example of `cert, err := m.GetCertificate(...)` so the certificates can be used in GRPC. I fail to come up with a solution.
```go
    m := &autocert.Manager{
        Cache:      autocert.DirCache("tls"),
        Prompt:     autocert.AcceptTOS,
        HostPolicy: autocert.HostWhitelist("example.com"),
    }
    go http.ListenAndServe(":http", m.HTTPHandler(nil))
    cert, err := m.GetCertificate(...)
    if err != nil {
        t.Fatalf("Failed to generate certificates %s", err)
    }
    creds := credentials.NewServerTLSFromCert(cert)
    srv := grpc.NewServer(grpc.Creds(creds))
    reflection.Register(srv)
```
https://godoc.org/golang.org/x/crypto/acme/autocert

https://stackoverflow.com/questions/49874945/acme-certificate-for-grpc

**Comment by x1ddos** [comment]
What's the `credentials`, `grpc` and `reflection` packages? Where are they coming from.

**Comment by gertcuykens** [comment]
grpc is my custom server package generated by the is proto file (should have named it mygrpc instead or something less confusing)
```
syntax = "proto3";

option go_package = "github.com/gertcuykens/tls/grpc";

package grpc;

message err {
    string msg = 1;
}

service tls {
    rpc test (err) returns (err) {}
}
```
And reflection is just for grpc build in service discovery 

Basically the last two lines are irrelevant

https://github.com/grpc/grpc-go/tree/master/examples

**Comment by agnivade** [comment]
I am not clear what is the issue about. Do you want an example to be added for the [GetCertificate](https://godoc.org/golang.org/x/crypto/acme/autocert#Manager.GetCertificate) method ?

**Comment by gertcuykens** [comment]
https://godoc.org/golang.org/x/crypto/acme/autocert#Manager.GetCertificate requires a `hello *tls.ClientHelloInfo` I have no idea how I should provide one, sorry

**Comment by agnivade** [comment]
I don't have much experience about the package, but from the documentation it seems this function serves as a hook for `tls.Config`.

```go
s := &http.Server{
    Addr:      ":https",
    TLSConfig: &tls.Config{GetCertificate: m.GetCertificate},
}
```

**Comment by gertcuykens** [comment]
Exactly and this makes it complicated for me because grpc needs the certificates, a grpc server has no TLSConfig hook. I need the return form the function GetCertificate itself.

**Comment by bradfitz** [comment]
Is there a bug against grpc about this too? It might be best handled by them.

Even if we were to documented some convoluted workaround to make the pieces all fit together, not everybody will read the docs and want to jump through those hoops.

It might be best if grpc made some API changes on their side to make this easy.

**Comment by gertcuykens** [comment]
issue created, feel free to collaborate on the issue above if you have suggestion what need to be changed in the grpc api itself

**Comment by FiloSottile** [comment]
Use NewTLS instead of NewServerTLSFromCert.

https://godoc.org/google.golang.org/grpc/credentials#NewTLS

We can't add examples for how to plug a tls.Config into all possible client libraries, but let us know if you have an idea of how we could have made that more clear.

**Comment by gertcuykens** [comment]
Thank you, feel free to paste answer in stackoverflow
