### ISSUE TITLE
cmd/go: poor error message when non-test Go file is in a xx_test package other than the directory name

### ISSUE THREAD

**Issue by stevenroose** [golang/go#24895]
### What version of Go are you using?
```
$ go version
go version go1.10 linux/amd64
```

### Does this issue reproduce with the latest release?
I guess this is the latest release.

### What operating system and processor architecture are you using?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/steven/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/steven/gocode"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build002363276=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
Using the [ginkgo](https://onsi.github.io/ginkgo/) cli tool, I created a test suite bootstrap. The folder name is `testsuite`, so the tool defaulted to a package name `testsuite_test`. 

I changed the package name in all files to `cbsproxy_test`, the package I'm testing, which is itself located in a different subdirectory on the same level as `testsuite`.

I ran both `go build` and `go test`.

### What did you expect to see?
`go build` to succeed normally and `go test` to produce test results for 0 tests.

### What did you see instead?
(newlines mine)
```
can't load package: package github.com/san-lab/cbsproxy-go/testsuite: 
found packages cbsproxy (cbsproxy_suite_test.go) and cbsproxy_test (common.go) 
in /home/steven/gocode/src/github.com/san-lab/cbsproxy-go/testsuite
```

Just to proof that all packages are named `cbsproxy_test`:
```
$ head -n 1 ./*.go
==> ./balance_test.go <==
package cbsproxy_test

==> ./cbsproxy_suite_test.go <==
package cbsproxy_test

==> ./common.go <==
package cbsproxy_test
```

### What solved the issue? 

Renaming `common.go` to `common_test.go` resolved the issue.  The error message was however not clear. As should it be possible to have both normal Go files and `_test` Go files with the same package name (as with any normal package that does not end in `_test`).

**Comment by davecheney** [comment]
Can you please create a git repo somewhere with broken and non broken versions of the packages as a reproduction. Thanks

**Comment by stevenroose** [comment]
@davecheney https://github.com/stevenroose/testing

**Comment by stevenroose** [comment]
Wait, non-test files don't need to have a package that matches the directory, right? 

I do understand that in this case, as `common.go` had `xx_test`, that `any_test.go` would be expected to have `xx_test_test`.

**Comment by Jubobs** [comment]
I've just got bitten by this. The behaviour is counterintuitive and the error message is misleading.

**Comment by ackratos** [comment]
> I've just got bitten by this. The behaviour is counterintuitive and the error message is misleading.

me too

**Comment by tonymet** [comment]
this is another case where the error message should suggest a solution. 
bad :  ` found packages regexpscanner_test (example_regexpscanner.go) and regexpscanner (regexpscanner.go) in /home/tonymet/sotion/sotion/go/regexpscanner`
better: `regexpscanner_test pkg should be in a file named regexpscanner_test.go`

**Comment by seankhliao** [comment]
The new error message seems fine. go generally does not try to guess what the user might want.

**Comment by tonymet** [comment]
> The new error message seems fine. go generally does not try to guess what the user might want.

Even if you prefer normative rather than prescriptive messages, the context could be better conveyed eg "found 2 packages and expected one" or "expected package xyz in xyz_test.go"
