### ISSUE TITLE
x/build: enable more builders for x/sys

### ISSUE THREAD

**Issue by tklauser** [golang/go#24893]
At the moment all `golang.org/x/*` sub-repositories are built/tested on a limited set of builders. For `golang.org/x/sys` it would be nice to enable builders for `dragonfly/amd64` and `solaris/amd64` at least (and maybe `freebsd/arm` and `netbsd/arm`) to increase test coverage. For now I run semi-regular build/tests of `x/sys` on these via gomote or on my local VMs/machines, but it would be nice to have it automated.

/cc @bradfitz

**Comment by bradfitz** [comment]
You mean trybots (pre-submit) or build.golang.org columns (post-submit) builders?

**Comment by krytarowski** [comment]
Were the patches for NetBSD/arm upstreamed? We used to have a long list of them.. perhaps mostly for the 1.4 version.

**Comment by tklauser** [comment]
@bradfitz Primarily, I mean post-submit builder. But pre-submit would of course also be nice, if it's possible to have them only for `x/sys`. I guess it doesn't make sense for most of the other `x/*` repos.
