### ISSUE TITLE
gerrit: restrict merging to release branches

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#24901]
The new minor release process has authors submit CLs to the release branches immediately: https://github.com/golang/go/wiki/MinorReleases

It should only be possible to submit changes to those branches with a +2 vote from the OSP team, as they need to meet the bar for inclusion in a minor release.

**Comment by mundaym** [comment]
Out of curiosity what is the OSP team? I can't see it defined anywhere.

**Comment by ianlancetaylor** [comment]
"OSP" is an exciting new TLA that means Open Source Project.  It means something like the set of people who try to keep the overall open source project moving, like @andybons and @bradfitz .  Really this issue should refer to "release managers" but we don't (yet) have any formal set of release managers.

**Comment by andybons** [comment]
This is done. Only members of the `release-managers` Gerrit group can submit changes to release-branches.
