### ISSUE TITLE
x/build/cmd/relui: ensure fully reproducible builds, including tar.gz/zip archives

### ISSUE THREAD

**Issue by bradfitz** [golang/go#24904]
Go already supports reproducible builds (with no action required), but our Go releases have .tar.gz/.zip archives that have timestamps.

We should probably make cmd/release also produce reproducible output and pin the archive file entry timestamps to the git commit time of the tagged commit we're building.

/cc @FiloSottile

**Comment by bradfitz** [comment]
@FiloSottile, were you going to do something here?

**Comment by FiloSottile** [comment]
I treated this as lower priority than the changes that would go in the release, but I am going to try to make the final tar.gz/zip reproducible.

**Comment by rsc** [comment]
Are we going out of our way to set time stamps in the archives?
I was pretty sure archive/tar and archive/zip do not add the time themselves anymore.

**Comment by bradfitz** [comment]
The buildlet sends a tarball to the x/build/cmd/release client.

The buildlet uses [tar.FileInfoHeader](https://golang.org/pkg/archive/tar/#FileInfoHeader).

The source on the buildlet ultimately comes from git (via git archive, via the gitmirror service, via the coordinator), but when the buildlet writes the git archive to disk, it clamps the file time to system time:

https://github.com/golang/build/blob/176bdadd9d93d520dfa53deede85bd81fdca6b81/cmd/buildlet/buildlet.go#L770

So it might all work for free today, assuming we have no files with future modtimes in the git repo.

But it's a little fragile.

It'd be nice if x/build/cmd/release enforced all the modtimes with something predictable, like using the same modtime for all files, picking the time of the git commit of the whole release.

/cc @andybons @dmitshur

**Comment by dr2chase** [comment]
This issue is currently labeled as early-in-cycle for Go 1.21, so this is a good time to revisit it.

**Comment by heschi** [comment]
Starting in 1.21 we'll use the `distpack` flag added above to issue fully reproducible tar.gz and zips. (Other than macOS, where the tar.gz contains non-reproducible signatures and notarizations.)
