### ISSUE TITLE
encoding/json: documented behavior unmarshaling JSON null into json.Unmarshaler is unclear

### ISSUE THREAD

**Issue by anzdaddy** [golang/go#24903]
### What version of Go are you using (`go version`)?

1.10.1

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

I read the documentation for `json.Unmarshal` and `json.Unmarshaler.UnmarshalJSON`, and the relevant code:

https://github.com/golang/go/blob/568d4848f672ecec3f9199452e9da1776a9fbba9/src/encoding/json/decode.go#L482-L494

### What did you expect to see?

A statement to the effect that `json.Unmarshal` will zero the value before calling `json.Unmarshaler.UnmarshalJSON`.

### What did you see instead?

According to the documentation, `json.Unmarshal` passes `null` to `json.Unmarshaler.UnmarshalJSON`. However, it doesn't explain that, prior to making the call, it sets the field to the zero value.

This is hinted at in the documentation for `json.Unmarshaler`, wherein it requires treating null inputs as a no-op, but this leaves the reader wondering what state the field is left in if it wasn't already the zero value.

**Comment by ianlancetaylor** [comment]
But it doesn't set the field to the zero value.  Consider:

https://play.golang.org/p/uNoEYH-UAqs

**Comment by anzdaddy** [comment]
:facepalm: Sorry, I misread the `if`.
