### ISSUE TITLE
reflect: documentation on NumMethod is incorrect

### ISSUE THREAD

**Issue by dsnet** [golang/go#24914]
[Consider the following](https://play.golang.org/p/rsC-F8IYO8w):
```go
type iface interface {
	private()
	Public()
}
t := reflect.TypeOf((*iface)(nil)).Elem()
for i := 0; i < t.NumMethod(); i++ {
	fmt.Println(t.Method(i))
}
```

This currently prints:
```
{Public  func() <invalid Value> 0}
{private main func() <invalid Value> 1}
```

The documented behavior of `reflect.Type.NumMethod` is:
> NumMethod returns the number of **exported** methods in the value's method set.

However, you can clearly see that `private` is included as part of the count.

It seems to me that for `reflect.Interface`, the `NumMethod` does include unexported methods, while it excludes them for all other kinds.

**Comment by ALTree** [comment]
This is #22075.

**Comment by dsnet** [comment]
Duplicate indeed. Thank you.
