### ISSUE TITLE
x/review: add an -m option 

### ISSUE THREAD

**Issue by jadekler** [golang/go#24912]
I'd love to be able to `git codereview change -m "some message"`, the same way that I can `git commit -m "some message"`.

**Comment by jadekler** [comment]
Naive attempt at https://go-review.googlesource.com/c/review/+/107625

**Comment by jadekler** [comment]
We (and many others) use the codereview tool to submit changesets to projects other than the Go project. In these other projects, one-liners are fairly frequent - example [here](https://code-review.googlesource.com/c/gocloud/+/26230).

The usecase for this is that we're automating our pipeline of producing and mailing out autogenerated code; it's a pain automating the `git codereview change` part of that since it defaults to using an editor. Being able to use `git codereview change -m "internal: regen code"` would simplify our lives greatly.

**Comment by ysmolsky** [comment]
@jadekler 
for example i have following hooks installed in gerrit repo:
```
exec git-codereview hook-invoke pre-commit "$@"
...golang.org/x/review (mail_prevent_backups>) % cat .git/hooks/commit-msg
#!/bin/sh
exec git-codereview hook-invoke commit-msg "$@"
```

actual change-id happens in commit-msg hook: https://github.com/golang/review/blob/master/git-codereview/hook.go#L181

**Comment by agnivade** [comment]
/cc @josharian according to owners. Josh - can you check if we should add the `-m` flag ?

@jadekler - Have you had a chance to look into the `commit-msg` hook and see if that works for you ?

**Comment by josharian** [comment]
git-codereview is intended to be generally useful, not just for the Go project (where, with @ysmolsky, I would usually expect longer commit messages). I am generally reluctant to add new flags, but this seems reasonable enough to me. I'll leave some comments on the outstanding CL.

**Comment by ysmolsky** [comment]
ping @jadekler. Could please fix the test in your CL?

**Comment by jadekler** [comment]
So I've run into a bit of an unspecified area. When `go test -bench=. -v` is used, what should the behavior be?

Currently, `-bench` causes the cursor to hang on the current line until the results are in, then prints the results, then prints the logs. E.x.:

```
# after .1s
$ go test -bench=. -v
BenchmarkFib10-8

# after 1s
$ go test -bench=. -v
BenchmarkFib10-8   	      10	 103238326 ns/op
--- BENCH: BenchmarkFib10-8
    foo_test.go:53: logging bench...
    foo_test.go:53: logging bench...
    foo_test.go:53: logging bench...
	... [output truncated]
PASS
```

However, with a very naive implementation, if we log immediately upon log receipt we'd get,

```
# after 1s
$ go test -bench=. -v
BenchmarkFib10-8
    foo_test.go:53: BenchmarkFib10: logging bench...
    foo_test.go:53: BenchmarkFib10: logging bench...
    foo_test.go:53: BenchmarkFib10: logging bench...
      10	 103553535 ns/op
PASS
```

What should this look like instead? Should the bench behavior be unchanged?

**Comment by jadekler** [comment]
Oh, wow. Whoops. Thanks @ianlancetaylor!

**Comment by jadekler** [comment]
@ysmolsky Done!
