### ISSUE TITLE
cmd/go: add minimal backwards-compatibility support for vgo

### ISSUE THREAD

**Issue by rsc** [golang/go#24916]
Copying from https://github.com/golang/go/issues/24301#issuecomment-377529520:

Define “new” code as code with a go.mod file in the same directory or a parent directory. The old go get must continue to download code exactly as it always has. I propose that the “go build” step adjust its handling of imports in “new” code. Specifically, if an import in new code says x/y/v2/z but x/y/v2/z does not exist and x/y/go.mod says “module x/y/v2”, then go build will read the import as x/y/z instead. We would push this update as a point release for Go 1.9 and Go 1.10.

**Comment by ALTree** [comment]
Exact dup of #25069, which has a CL. Closing here.
