### ISSUE TITLE
os: MkdirAll error has junk characters on Plan 9

### ISSUE THREAD

**Issue by petter9** [golang/go#24921]
### What version of Go are you using (`go version`)?
go version go1.10.1 plan9/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/p/lib/cache/go-build'
GOEXE=''
GOHOSTARCH='amd64'
GOHOSTOS='plan9'
GOOS='plan9'
GOPATH='/usr/p/go'
GORACE=''
GOROOT='/sys/go/1.10.1'
GOTMPDIR=''
GOTOOLDIR='/sys/go/1.10.1/pkg/tool/plan9_amd64'
GCCGO='gccgo'
CC='6c'
CXX='g++'
CGO_ENABLED='0'
CGO_CFLAGS='-g -O2'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-g -O2'
CGO_FFLAGS='-g -O2'
CGO_LDFLAGS='-g -O2'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build510394034=/tmp/go-build -gno-record-gcc-switches'

### What did you do?
```
package main

import (
        "fmt"
        "os"
)

func main() {
        fmt.Printf("%s\n", os.MkdirAll("foo/bar/baz", 0000))
        fmt.Printf("%s\n", os.MkdirAll("foo/bar/baz", 0000))
        fmt.Printf("%s\n", os.MkdirAll("foo/bar/baz", 0000))
        fmt.Printf("%s\n", os.MkdirAll("foo/bar/baz", 0000))
        fmt.Printf("%s\n", os.MkdirAll("foo/bar/baz", 0000))
}
```

### What did you expect to see?
mkdir foo/bar: 'foo/bar' does not exist
mkdir foo/bar: 'foo/bar' does not exist
mkdir foo/bar: 'foo/bar' does not exist
mkdir foo/bar: 'foo/bar' does not exist
mkdir foo/bar: 'foo/bar' does not exist

### What did you see instead?
mkdir foo/bar: 'foo/bar' does not exist existst
mkdir foo/bar: 'foo/bar' does not existes not ex
mkdir foo/bar: 'foo/bar' does not existon denied
mkdir foo/bar: 'foo/bar' does not existon denied
mkdir foo/bar: 'foo/bar' does not existon denied

**Comment by ianlancetaylor** [comment]
CC @0intro

**Comment by 0intro** [comment]
Thanks for reporting. I think this is related to issue #24767

**Comment by millerresearch** [comment]
In fact this is another case of issue #13770, where all syscall error strings in Plan 9 are aliased to the same underlying byte array.  The symptom in MkdirAll occurs when a Mkdir syscall fails, followed by an Lstat which fails and overwrites the Mkdir error string before it's used.
A local workaround would be to save a copy of the first error string.  But really we should get rid of the aliasing behaviour, which is contrary to Go string semantics, by reworking [this revision](https://github.com/golang/go/commit/a566deace1d96cd517e79227937e3036baca7ee2) which introduced it.
I had a tentative correction a while ago, but I wasn't entirely happy with it.  I'll make another attempt now.
