### ISSUE TITLE
runtime: use tgkill instead of tkill to keep Android happy

### ISSUE THREAD

**Issue by zx2c4** [golang/go#24924]
Go uses tkill in the panic routine. From the tkill man page:

       tkill() is an obsolete predecessor to
       tgkill().   It allows only the target
       thread ID to be specified, which  may
       result in the wrong thread being sig‐
       naled if a thread terminates and  its
       thread  ID  is recycled.  Avoid using
       this system call.

Android sets a seccomp filter that disallows tkill but allows tgkill. Therefore the solution is to switch Go to using tgkill. According to the man page, there are other good reasons for switching to tgkill too.

This is similar to https://github.com/golang/go/issues/23750 but is yet-another mole.

**Comment by ianlancetaylor** [comment]
CC @eliasnaur

**Comment by eliasnaur** [comment]
I have no objection to tgkill if it's better, but I do see tkill listed in the seccomp list from 23750:

https://android.googlesource.com/platform/bionic/+/master/libc/seccomp/arm64_app_policy.cpp

Do you have a small test case that breaks Android O?

**Comment by zx2c4** [comment]
Woah, actually, no, I can't reproduce in any of the emulators on any of the architectures. I sent this based on crash logs from some users who might be running strange/old/weirdvendor devices.

So, fine to close this issue. 

Sorry for the noise.
