### ISSUE TITLE
runtime: sigprof handler crashes backtracing runtime.nanotime [1.10 backport]

### ISSUE THREAD

**Issue by heschik** [golang/go#24931]
Original issue: #24925. It should be backported because it risks causing an unavoidable crash when CPU profiling is running.

**Comment by andybons** [comment]
+1

@ianlancetaylor?

**Comment by heschik** [comment]
We changed our minds, so I'll abandon the CLs. There's no CherryPickRejected label; should I just close the issue?

**Comment by andybons** [comment]
Yep just close it.
