### ISSUE TITLE
cmd/compile: incorrect recursive type error

### ISSUE THREAD

**Issue by griesemer** [golang/go#24939]
https://play.golang.org/p/GJoMVoB7adS
```
prog.go:11:6: invalid recursive type alias P
	prog.go:11:6: P uses <T>
	prog.go:11:10: <T> uses <T>
	prog.go:12:3: <T> uses M
	prog.go:7:6: M uses <T>
	prog.go:7:8: <T> uses <T>
	prog.go:8:3: <T> uses P
```
which seems incorrect. Moving the declaration of `T` to the end of the file eliminates the error:
https://play.golang.org/p/oGvZBMdw72A

(Simplified reproducer based on an error found  by @dsnet .)

**Comment by griesemer** [comment]
cc: @dsnet

**Comment by dsnet** [comment]
Sorry, just giving you more work ;)

**Comment by griesemer** [comment]
Possibly related to #18640.
