### ISSUE TITLE
Add fmt.Error()

### ISSUE THREAD

**Issue by hgdsraj** [golang/go#24954]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Amd X86-64 -> Darwin

### What did you do?
No error, just fmt.Error would be useful

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
An fmt.Error

### What did you see instead?
no fmt.Error

**Comment by ianlancetaylor** [comment]
Use `errors.New`.
