### ISSUE TITLE
cmd/compile: miscellaneous optimizations

### ISSUE THREAD

**Issue by benshi001** [golang/go#24958]
My optimization plan for arm64 in go-1.12:

1. further optimization for (shifted) register indexed load/store, especially interference with combined load/store. 
1.1 combination of load/store uint16/uint32 to upper type
1.2 BE/LE should be both supported for the same situation
1.3 load/store in the order of from/to high memory down to low memory (it is not BE, LE load/store can also happen from high-memory/upper-byte to low-memory/lower byte)

2. (shifted) register indexed load/store for FP. (assembler and compiler)

3. optimization with MADD/MSUB/MADDW/MSUBW
"MUL R1, R2, R3"
"ADD R3, R4" can be optimized to
"MADD R1, R2, R3, R4"
I expect to see both performance improvement and code size reduction with MADD/MSUB emitted.

4. optimize comparasion with ANDS/ADDS/SUBS

5. optimize atomic operations with SWPALD/SWPALW/SWPALH/SWPALB

6. STADD/STSUB/STEOR/STOR
those instructions directly operate on a memory operand atomically, I expect to see both performance improvement and code size reduction with them emitted.

7. BFC - bit field clear

8. constant pool
"ADD $0x00aaaaaa, Rx" is assembled to "LDR off(PC), Rtmp" + "ADD Rtmp, Rx", and a 4-byte item is stored in the constant pool, total 12 bytes are cost.
It can be optimized to "ADD $0xaaa, Rx" + "ADD $0xaaa000, Rx", and only 8 bytes are cost.
This optimization does not improve performance, but does reduce code size.

9. FMULA/FMULS
(FADD z:(FMUL x y) a) -> (FMULA x a y)
a restriction z.Uses==1 is needed to improve performance.

10. constant pool
use "MOV $0xaaaa, Rx" + "MOVK $0xbbbb0000, Rx" instead of loading a 32-bit 0xbbbbaaaa from constant pool;
use "MOV $0xaaaa, Rx" + "MOVK $0xbbbb0000, Rx" + "MOVK $0xcccc00000000, Rx" instead of loading a 64-bit 0xccccbbbbaaaa from constant pool;

11. LDP/STP for FP (assembler and compiler)

**Comment by benshi001** [comment]
3. optimization with MADD/MSUB
"MUL R1, R2, R3"
"ADD R3, R4" can be optimized to
"MADD R1, R2, R3, R4"

I have made this patch, but the go1 benchmark shows performance drop, which is quite strange. I am still debugging that part, it seems this optimization have to be postponed to go-1.12.

**Comment by benshi001** [comment]
4. STADD/STSUB/STEOR/STOR 
those instructions directly operate on a memory operand automatically, I expect to see both performance improvement and code size reduction with them emitted.

**Comment by benshi001** [comment]
A CL is committed for issue 2.

https://go-review.googlesource.com/c/go/+/108735

**Comment by benshi001** [comment]
updated! the optimization plan for arm64 in go-1.12
1. further optimization for indexed load/store
For source code

	func load_byte2_uint16_idx(s []byte, idx int) uint16 {
	       return uint16(s[idx]) | uint16(s[idx+1])<<8
	}

the following asm is generated,

		0x0028 00040 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:115)	MOVBU	(R2)(R0), R3
		0x002c 00044 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:115)	ADD	$1, R0, R0
		0x0030 00048 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:115)	CMP	R1, R0
		0x0034 00052 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:115)	BHS	76
		0x0038 00056 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:115)	MOVBU	(R2)(R0), R0

Actually it can be optimized to a combined "MOVHU (R2)(R0), R0"

2. constant pool
"ADD $0x00aaaaaa, Rx" is assembled to "LDR off(PC), Rtmp" + "ADD Rtmp, Rx", and an 4 bytes item is stored in the constant pool, total 12 bytes are cost.
It can be optimized to "ADD $0xaaa, Rx" + "ADD $0xaaa000, Rx", and only 8 bytes are cost.
This optimization does not improve performance, but does reduce code size.

3. optimization with MADD/MSUB
"MUL R1, R2, R3"
"ADD R3, R4" can be optimized to
"MADD R1, R2, R3, R4"

4. STADD/STSUB/STEOR/STOR
those instructions directly operate on a memory operand automatically, I expect to see both performance improvement and code size reduction with them emitted.

**Comment by benshi001** [comment]
Some optimization can also be done for ARM32:

1. register indexed FP load/store (assembler and compiler)
    they are referred as VLD1/VLD2/VST1/VST2

2. use BFI / BFC to simplify bit operations

3. use ORN to simplify a | ^b

**Comment by benshi001** [comment]
The reason why the following two MOVBs are not combined to a single MOVH, is that the first load (v23) is used twice.

	func ssg(s []byte, idx int) {
		s[(idx<<1)+0], s[(idx<<1)+1] = 0, 0
	}

This optimization seems can not be done by SSA rules only.

	  pass lower begin
	  pass lower end [16576 ns]
	ssg func([]byte, int)
	  b1:
	    v1 = InitMem <mem>
	    v7 = Arg <int> {idx}
	    v8 = MOVDconst <uint> [1] DEAD
	    v13 = MOVDconst <int> [1] DEAD
	    v15 = MOVDconst <byte> [0] DEAD
	    v30 = Arg <*byte> {s} (s[*byte])
	    v25 = Arg <int> {s} [8] (s+8[int])
	    v28 = SLLconst <int> [1] v7
	    v26 = MOVDconst <int> [0] DEAD
	    v3 = FlagLT_ULT <flags> DEAD
	    v6 = CMPshiftLL <flags> [1] v25 v7
	    v14 = ADDconst <int> [1] v28
	    v17 = GreaterThanU <bool> v6 DEAD
	    v24 = InvertFlags <flags> v6 DEAD
	    UGT v6 -> b2 b3 (likely)
	  b2: <- b1
	    v21 = ADDshiftLL <*byte> [1] v30 v7 DEAD
	    v23 = MOVBstorezeroidx <mem> v30 v28 v1
	    v12 = CMP <flags> v14 v25
	    v27 = LessThanU <bool> v12 DEAD
	    ULT v12 -> b4 b3 (likely)
	  b3: <- b1 b2
	    v18 = Phi <mem> v1 v23
	    v19 = CALLstatic <mem> {runtime.panicindex} v18
	    Exit v19
	  b4: <- b2
	    v29 = ADD <*byte> v30 v14 DEAD
	    v31 = MOVBstorezeroidx <mem> v30 v14 v23
	    Ret v31

**Comment by randall77** [comment]
This is because the bounds check might panic after assigning the `s[(idx<<1)+0]` but before assigning `s[(idx<<1)+1]`.  If you ensure the bounds check, if it fails, fails before the assignment, then it should work.
```
func ssg(s []byte, idx int) {
	_ = s[(idx<<1)+1]
	s[(idx<<1)+0], s[(idx<<1)+1] = 0, 0
}
```

**Comment by benshi001** [comment]
Thank you. Keith.

But such kinds of code looks odd. Is it possible to clobber the MOVBstore if it was only referred by a bound check? Or making bound check omits disappeared store/load ?

**Comment by randall77** [comment]
Combining the stores is not legal in the original example.  If the first array index succeeds but the second fails, the language semantics require that the first write happens and the second doesn't. That means that the first write must be just a single byte; it can't be combined with the second write.  The "in-between" memory state is observable if someone recovers the panic.

That requirement is realized in SSA by passing the results of the first store to the bounds check.

**Comment by benshi001** [comment]
Thank you. Keith. I see the key point.

**Comment by benshi001** [comment]
Though amd64 is more widely used today, 386 code is still useful in some mobile/embedded systems for smaller binary size and lower power consumption.

1. support more instructions use direct memory operands, such as CMP
2. improve ADDLload with register indexed form
3. check if there is something can be optimized in the 386 SSA backend when GO386=sse2 is specified.

**Comment by benshi001** [comment]
about 40% of them have been implemented via my recent commits, others do not improvement.
