### ISSUE TITLE
gccgo: build process should not be serial bottlenecked

### ISSUE THREAD

**Issue by ppbrown** [golang/go#24962]
this is for the gcc 7.3.0 codebase.

I have a 100 cpu-thread box.
I'm running with gmake -j 50

It hits some part of the go build stage.. and then grinds to a crawl.

here is a snippet of some of the crazy long output at this point:

f=`echo net/smtp.lo | sed -e 's/.lo$/.o/'`; gobjcopy -j .go_export $f net/smtp.s-gox.tmp; /bin/sh ../../../../libgo/mvifdiff.sh net/smtp.s-gox.tmp `echo net/smtp.s-gox | sed -e 's/s-gox/gox/'`
echo timestamp > net/smtp.s-gox

sorry I'm not a GNU makefile expert, so cant suggest a patch :(
I just know that when it builds normal C or C++ based libs, it does the nice massively parallel compiles, but when it hits that stage of compling, with
libtool (blahblah) gccgo blahblah..

suddenly, it seems to stop parallelizing for a long time, comparatively speaking

**Comment by ppbrown** [comment]
Eh... perhaps I was premature in opening this.
in rerunning the build, seems like there are other places where gcc isnt so parallel. 
So probably unfair to single out the libgo part of things.

**Comment by ianlancetaylor** [comment]
The way to approach this is to run `ps uwww` when the build seems to be stuck, to see which jobs are running.

Note that Go is not C/C++.  Although Go often compiles faster, it is more prone to serial bottlenecks.

**Comment by ppbrown** [comment]
oops.. well since you commented, seems fair to add a reply...
yes I understand that normally, go has its own build engine and rules.
However, the driver behind gccgo/libgo compilation appears to be more specifically GNUmake driven.
so my guess is that the slowdown area has more to do with gmake logic.
After all, there are 1137 non-test related ".go" files. 
So, even if there is some amount of required dependancy in the mix, it still seems like better parallelism should be achievable.
But.. meh. oh well.

**Comment by ianlancetaylor** [comment]
Whether building with gccgo or the go tool, the Go compilation model has serialization that the C/C++ model does not.  In C/C++ a dependency is expressed by #include a .h file.  In Go a dependency is expressed by importing a package.  In C/C++ the .h file is already present in the source tree.  In Go the imported package must be compiled.  The effect is that C/C++ compilation does much more work overall: the .h file is read and parsed many times.  But on the other hand the C/C++ compilation is more parallelizable, in that you can compile code immediately without having to wait for the dependencies to be compiled.

**Comment by ppbrown** [comment]
I think you are saying that using "the go compilation model", you may wish
to compile file A, but that depends on file B, which also depends on C and
D, which first need to be compiled. so there is blocking involved.
okay i get that.

however, unless there is a  VERY deep dependency chain that includes
practically every file, that shouldn't be a problem, for properly ordered
compile order.
if you have effectively unlimited cpus for parallelism, then in theory, the
entire set should be compilable in a number of compile cycles equal to the
deepest dependancy chain.

That is, lets say that files (A,B,C,D) all depend on some mix of (E,F,G,H).
And they all depend on some mix of (I,J,K L). and THEY all depend on (M,N,O
P)
That is a tree of depth 4. If you have unlimited cpus, then the whole lot
should theoretically be compilable in 4 rounds of parallel compiles.
I have 100 cpus. So, in theory, I should be able to compile the libgo part
of things very fast, with "gmake -j".
Even if there are multiple bottlenecks of (oh we need to group these sets
of files into libraryX.a first), it should be possible to paralellize those
builds.
So while the system is busy building library libfmt.a, it should ALSO be
building libflag.a, libcompress.a, etc. at the same time.
and yes I get that some of those libraries depend on other libraries :)

But you see my point. The library builds should be parallelizable as well,
if library dependancies are first mapped out.
Apparently, there are 169 library type files, judging by
$ find . -name '*.dep' |wc -l
     169

That is equivalent to the PACKAGES definition in the Makefile, I believe.
But I'm having difficult finding the build trigger for PACKAGES in the
Makefile, and whether it is parallel or serial.

**Comment by ianlancetaylor** [comment]
The libgo build is parallelizable and it is parallelized.  But you still hit a roadblock.  In my experience the problem is the net/http package, which is one of the most complex packages and also has a great deal of dependencies.  So you have to build most of libgo, and only then do you get to build net/http, and then you block until that specific build is complete, and then you build in parallel a few remaining packages that depend on net/http.

The build trigger for `PACKAGES` is simply that it appears in `$(libgo_go_objs)` which is an input to `libgo.la`.
