### ISSUE TITLE
net/http: get does not work

### ISSUE THREAD

**Issue by yyq2013** [golang/go#24970]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
C:\WINDOWS\system32>go version
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
win10 64bit
C:\WINDOWS\system32>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build873199622=/tmp/go-build -gno-record-gcc-switches

### What did you do?
http.Get(url) doesn't work with default transport, if I set a custom it works fine like following:

```
	tr := &http.Transport{}
	http.DefaultClient.Transport =tr
        http.Get(url)...
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```go
package main

import (
	"net/http"
	"io/ioutil"
	"fmt"
	"log"
)

func main() {
	//tr := &http.Transport{}
	//http.DefaultClient.Transport =tr
	res, err:= http.Get("https://www.github.com/")
	if err != nil {
		log.Fatal(err)
		return
	}

	defer res.Body.Close()

	body,err:=ioutil.ReadAll(res.Body)
	if err != nil {
		log.Fatal(err)
		return
	}

	fmt.Println(string(body))
}
```

### What did you expect to see?
Print the html content

### What did you see instead?
There is an error with less meaning.
Get https://www.github.com/: unexpected EOF

**Comment by adamdecaf** [comment]
I get a more descriptive error from this code. https://play.golang.org/p/_f2geOmnMzl 

```
	res, err := http.Get("github.com")
	if err != nil {
		panic(err)
	}
	fmt.Println(res)
```

```
panic: Get github.com: unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
	/tmp/sandbox333729466/main.go:11 +0xe0
```

Also, the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

**Comment by agnivade** [comment]
I was thinking how to categorize this. This wasn't technically a question per-se. OP raised an issue which wasn't working in his system. While it was clear that this cannot be a bug in Go because of the simplicity of the issue, I think it warranted a bit more than simply closing it.

**Comment by myitcv** [comment]
Apologies @agnivade (and @yyq2013) will re-open pending your update.

**Comment by yyq2013** [comment]
But same code works fine on linux OS.
[root@iZ2zef032vfaf0fdq8tcbuZ src]# cat > test.go
package main

import (
        "net/http"
        "io/ioutil"
        "fmt"
        "log"
)

func main() {
/*      tr := &http.Transport{}
        http.DefaultClient.Transport =tr*/
        res, err:= http.Get("https://www.github.com/")
        if err != nil {
                log.Fatal(err)
                return
        }

        defer res.Body.Close()

        body,err:=ioutil.ReadAll(res.Body)
        if err != nil {
                log.Fatal(err)
                return
        }

        fmt.Println(string(body))
}
^C
[root@iZ2zef032vfaf0fdq8tcbuZ src]# go run test.go






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">

**Comment by adamdecaf** [comment]
@yyq2013 I'm not seeing this work on Go 1.10 in a docker image. I don't have windows handy right now. 

```
root@76961f09bfe8:/go# go version
go version go1.10.1 linux/amd64

root@76961f09bfe8:/go# go run test.go 
2018/04/20 15:03:59 Get github.com: unsupported protocol scheme ""
exit status 1
```

**Comment by yyq2013** [comment]
@adamdecaf 
why do you remove the scheme?
res, err:= http.Get("**https://**www.github.com/")

my linux:
[root@iZ2zef032vfaf0fdq8tcbuZ src]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/data/code/"
GORACE=""
GOROOT="/root/data/go"
GOTMPDIR=""
GOTOOLDIR="/root/data/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build220856888=/tmp/go-build"


[root@iZ2zef032vfaf0fdq8tcbuZ src]# cat test.go
package main

import (
        "net/http"
        "io/ioutil"
        "fmt"
        "log"
)

func main() {
/*      tr := &http.Transport{}
        http.DefaultClient.Transport =tr*/
        res, err:= http.Get("https://www.github.com/")
        if err != nil {
                log.Fatal(err)
                return
        }

        defer res.Body.Close()

        body,err:=ioutil.ReadAll(res.Body)
        if err != nil {
                log.Fatal(err)
                return
        }

        fmt.Println(string(body))
}
[root@iZ2zef032vfaf0fdq8tcbuZ src]# go run test.go




<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">

**Comment by adamdecaf** [comment]
@yyq2013 Your example has it removed.

**Comment by yyq2013** [comment]
@adamdecaf maybe, I was updating it then

**Comment by yyq2013** [comment]
@agnivade
C:\WINDOWS\system32>curl -O https://www.github.com
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information

It's strange, on another win10 it works.

**Comment by agnivade** [comment]
Sorry, there has to be an path for -O. Try `curl -o file https://github.com`

**Comment by yyq2013** [comment]
I found the reason, there is a global socks5 proxy  on my win10 OS, the default transport use it by default.

Sorry for wasting your time, everyone here.
I will be more careful before post a bug.
Thanks for your patient guide, everyone.

Please close it.
