### ISSUE TITLE
x/crypto/sha3: add KMAC

### ISSUE THREAD

**Issue by conradoplg** [golang/go#24988]
The KMAC message authentication code specified in [NIST SP 800-185](https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-185.pdf) may be a useful MAC implementation.

In particular, it can be used as a KDF as specified by [NIST SP 800-56C](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr1.pdf).

I'm submitting a CL implementing it, in case there is interest. I can also add support for TupleHash and ParallelHash.

**Comment by agnivade** [comment]
This adds new API. Any new public API needs to go through a proposal and accepted first. Perhaps you can create a proposal citing proper reasons why this should be inside `x/crypto/sha3` and not in an external package ?

/cc @FiloSottile / @agl

**Comment by conradoplg** [comment]
> This adds new API. Any new public API needs to go through a proposal and accepted first. Perhaps you can create a proposal citing proper reasons why this should be inside x/crypto/sha3 and not in an external package ?

Sure. What's the proper procedure for that? Should I just add "proposal:" to the title of the issue?

Basically, the main reason is that KMAC is based on the underlying Keccak sponge implementation. If I were to create an external package, I'd have to duplicate the entire Keccak implementation from `x/crypto/sha3`.

**Comment by FiloSottile** [comment]
Relatedly, golang.org/cl/111281 implements cSHAKE.

**Comment by FiloSottile** [comment]
I'm inclined to accept both cSHAKE and KMAC, unless @agl has objections. SHA-3 has defined way too many functions, but making people reimplement them or roll their own MAC doesn't sound like the right answer.

**Comment by FiloSottile** [comment]
Ok on adding KMAC and cSHAKE. Docs should point to hmac.Equal.

**Comment by Scratch-net** [comment]
Please consider adding TupleHash too. It's the only way to hash multiple slices without collisions

**Comment by conradoplg** [comment]
I updated my CL with the new cSHAKE some time ago, but forgot to comment here...

I can add TupleHash if desired.

**Comment by Scratch-net** [comment]
That would be awesome

**Comment by conradoplg** [comment]
Not sure if there is still interest in this, but I finally added TupleHash to the CL :sweat_smile: 

I guess I should just add ParallelHash too; I'll add it soon.

**Comment by FiloSottile** [comment]
A few years have passed, and cSHAKE landed. Did KMAC end up used in any protocol we know of? There doesn't seem to be a lot of demand for it here, judging from comments and reactions.

**Comment by conradoplg** [comment]
> A few years have passed, and cSHAKE landed. Did KMAC end up used in any protocol we know of? There doesn't seem to be a lot of demand for it here, judging from comments and reactions.

Yeah I don't see any point in including KMAC if cSHAKE is available. One Day™️ I'll put my code in a separate project. I'll just go ahead and close this if it's OK.

**Comment by rautammi** [comment]
I beg your pardon for being late with my comment: https://doi.org/10.6028/NIST.SP.800-108r1 specifies KMAC as a KDF but not SHAKE. Shall I open a new issue about really adding KMAC support this time?
