### ISSUE TITLE
Type func signatures and interface bindings

### ISSUE THREAD

**Issue by l0k1verloren** [golang/go#24996]
I have asked in a couple of other places but it occurred to me this might be a good place to ask, as maybe this is a 'bug' of some sort.

When defining a function type, viz:

```go
type FunctionName func(Parametertype...) (Returntype...) 
```

the compiler flags a type mismatch if trying to assign a function that has otherwise identical signature except is prefixed with a binding to an interface. I could not find any information about specifying the binding type in this type of declaration. As such I worked out that it would be possible to implement a binding for a first class function by placing the primary code within one function, with the pointer to the type in the parameter list, and then calling this function, pretty much pass-through, as a wrapper, and then the function can be called as a child of the parent typed variable without having to explicitly pass the pointer to the struct or variable we want to bind to.

I am curious to know if there is some reason why this isn't in the syntax, or if simply I have gone a long way around to enable me to substitute a set of functions to operate on similar but comparable other types within a bigger library, with my hackish solution.

This is not a perfect example, as in fact in my code I also have a slice embedded into an `interface{}` variable in the struct, but this shows all the elements I am referring to and as to how I worked around this seeming limitation (I may just have not fully understood how composition and embedding work):

```go
type nullTester func(*Bast, uint32) bool

type Bast struct {
  ...
  isNull    nullTester
  ...
 }

func isNull(b *Bast, d uint32) bool {
  return d == 0
}

func NewBast() (b *Bast) {
  ...
  b.isNull = isNull
  ...
}

// IsNull - tests if a value in the tree is null
func (b *Bast) IsNull(d uint32) bool {
  return b.isNull(b, d)
}
```

As you can see, if I have assigned this function to a variable in the struct, and the type bound function will be in the same scope, I should thus be able to override a function through the use of first class functions in this way. It doesn't really break any typing rules, it's just that the declaration at the top does not match the function at the bottom and thus I can't put `b.isNull = IsNull` as the compiler says it can't find the name.

**Comment by bronze1man** [comment]
Do you mean `b.isNull = (*Bast).IsNull` ? It works. https://play.golang.org/p/Rgoc5zMezdb

**Comment by l0k1verloren** [comment]
That's what I was looking for! *whew* I knew about the postfixed .(type) for type assertion but I didn't know there was a prefix of any form. Thanks!

**Comment by l0k1verloren** [comment]
Ok, I seem to have finally 100% fixed the issue. I need to not use the `type Name func` syntax at all. The slot in the struct needs to be typed as `interface{}`

**Comment by l0k1verloren** [comment]
ok, I just want to leave this issue here, with a playground link that shows the first answer I proposed above is correct.

https://play.golang.org/p/FMvisWS9tuP

```go
package main

import "fmt"

type nullTester func(*Bast, uint32) bool

type Bast struct {
  isNull    nullTester
}

func isNull(b *Bast, d uint32) bool {
  return d == 0
}

func NewBast() (b Bast) {
  b.isNull = isNull
  return
}

// IsNull - tests if a value in the tree is null
func (b *Bast) IsNull(d uint32) bool {
  return b.isNull(b, d)
}

func main() {
  b := NewBast()
  fmt.Println("is 0 == 0 ?", b.IsNull(0))
  fmt.Println("is 1 == 0 ?", b.IsNull(1))
}
```

I don't know if my solution is idiomatic, and I simply have not been able to understand how to bind different functions in. The question of how to bind a slice in is not the bit that is challenging, as it can be defined as `interface{}` type in the struct, and then in the functions `.(*datatype)`, and I can then overload functions.

It's the fact that I have found a way to implement function overloading that makes me think this is not idiomatic but I see no way in which this violates type safety at all.

**Comment by myitcv** [comment]
@l0k1verloren I'm unclear from reading the above whether you think there is a problem here, or whether this is more of a discussion. I can't see an issue with the code you just posted; it functions as expected. 

Please can I ask you to continue the discussion outside the issue tracking system? The Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process. The [questions wiki page](https://github.com/golang/go/wiki/Questions) has a good list of places for everything else. 

Thanks

**Comment by l0k1verloren** [comment]
Simply that because I can't add a method binding to a `type Name func` required me to write the hack using a first class function (otherwise, apart from the implied passing of the pointer to the struct) matching the typespec, stored in the type struct, and invoke it from the actual type bound function.

The type syntax lacks the binding part that causes otherwise identical function signature to be 'not found'. There is no reason I can think of except OOP-phobia, and as you can see by my code, it works, it's not violating any type safety, and it's a useful construction for being able to generalise small parts of libraries to deal with a variety of types (it came up for me because I was working on a binary search tree, a clear case for the need of polymorphism to not require so much boilerplate).

It's a side thing but I also think the special exception for slices that do not behave consistently compared to every other Go type. I had to encapsulate a slice inside a struct in order to allow embedding into one library the ability to change a back-store. This is just a limited case, and very inconsistent, and very much in line with the subject of this issue as well. It does not in fact stop polymorphism, it just makes it cumbersome to implement, for absolutely no reason.
