### ISSUE TITLE
test/codegen: right arm64 test cases not pass

### ISSUE THREAD

**Issue by benshi001** [golang/go#25003]
The following test case does not pass which should do.
	
	func SubIndexed(arr0 []int64, arr1 []int32, arr2 []int16, idx int) (int64, int32, int16) {
		// arm64:`MOVD\s\(R[0-9]+\)\(R[0-9]+<<3\)`,`MOVW\s\(R[0-9]+\)\(R[0-9]+<<2\)`,`MOVH\s\(R[0-9]+\)\(R[0-9]+<<1\)`,`SUB`	
		return arr0[idx] - arr0[idx+1], arr1[idx] - arr1[idx+1], arr2[idx] - arr2[idx+1]
	}
	
With error like
	
	0x0074 00116 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/arithmetic.go:27)	MOVH	(R5)(R0<<0), R0
	0x005c 00092 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/arithmetic.go:27)	MOVW	(R3)(R4<<0), R2
	0x0038 00056 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/arithmetic.go:27)	MOVD	(R2)(R4<<0), R1

**Comment by cherrymui** [comment]
I think normally we don't file bug for ongoing developing CL. Any problem of the CL should be addressed in that CL. If you are saying an existing bug blocking a CL, please make it clear.

It looks to me that you're saying that you want to generate instructions like `MOVD	(R2)(R4<<3), R1`, but the assembler prints it as `MOVD (R2)(R4<<0), R1`. I checked the assembler and this is not the case.
```
$ cat a.s
TEXT	f(SB),4,$0-0
	MOVD	R0, (R1)(R2<<3)
	RET
$ GOARCH=arm64 GOOS=linux go tool asm -S a.s
f STEXT nosplit size=16 args=0x0 locals=0x0 leaf
	0x0000 00000 (a.s:1)	TEXT	f(SB), NOSPLIT|LEAF|NOFRAME, $-8-0
	0x0000 00000 (a.s:2)	MOVD	R0, (R1)(R2<<3)
	0x0004 00004 (a.s:3)	RET	(R30)
```
I commented on the CL about fixing the CL. Closing. Feel free to reopen if this is an actual bug.
