### ISSUE TITLE
x/vgo: import path is resolved to the wrong version

### ISSUE THREAD

**Issue by utrack** [golang/go#25007]
### What version of Go are you using (`go version`)?
```
» vgo version
go version go1.10.1 linux/amd64 vgo:2018-02-20.1
```

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/u/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/u/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build277438090=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
I've imported a package using versioned syntax: `import _ "github.com/gomodule/redigo/v2/redis"`

### What did you expect to see?
Version 2.0.0 of redigo imported;
```
» vgo list -t github.com/gomodule/redigo/v2                2018-04-23 12:55:36
github.com/gomodule/redigo/v2
        v2.0.0
```

### What did you see instead?
Path is resolved to version 1.6 with v2 subdir -
```
CGO_ENABLED=0 CC=gcc vgo build -a -tags netgo -o /home/u/gtl/bx/listing_api/bin/listing_api ./cmd/listing_api
vgo: resolving import "github.com/gomodule/redigo/v2/redis"
vgo: finding github.com/gomodule/redigo (latest)
vgo: adding github.com/gomodule/redigo v1.6.0
vgo: import "myrepo/listing_api/cmd/listing_api" ->
        import "github.com/gomodule/redigo/v2/redis" [/home/u/go/src/v/github.com/gomodule/redigo@v1.6.0/v2/redis]: open /home/u/go/src/v/github.com/gomodule/redigo@v1.6.0/v2/redis: no such file or directory
make: *** [Makefile:10: build] Error 1
```

**Comment by AlexRouSg** [comment]
Import path with a `/v2/` is only available for packages directly supporting vgo and has a go.mod file, redigo does not.

In addition to that, #24585 is about vgo incorrectly generating the go.mod file for legacy packages with versions >= v2.0.0

**Comment by rsc** [comment]
Yes, if github.com/gomodule/redigo does not opt into semantic import versioning by creating a go.mod that says 'module github.com/gomodule/redigo/v2', then you cannot import it using that path.

However, you can still import the old name under a pseudo-version. If you run

    vgo get github.com/gomodule/redigo@v2.0.0

then vgo will add to go.mod not v2.0.0 (that doesn't match the module path) but instead

    github.com/gomodule/redigo v0.0.0-20180314223443-9c11da706d9b

which is the same code.
