### ISSUE TITLE
cmd/link: -X requires the full import path for vendored packages

### ISSUE THREAD

**Issue by ckeyer** [golang/go#25011]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build528112336=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
```
$ find
main.go
vendor/github.com/ckeyer/commons/version/version.go

$ go build -a -v -ldflags="-X github.com/ckeyer/commons/version.version=v0.1.0" main.go version
```
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I want to see print the `version v0.1.0`

### What did you see instead?
none

I use `go build -a -v -ldflags="-X github.com/ckeyer/frog/vendor/github.com/ckeyer/commons/version.version=v0.1.0" main.go version` ,it works.

**Comment by FiloSottile** [comment]
Marking this as Documentation, because that behavior can't be practically changed. `github.com/ckeyer/frog/vendor/github.com/ckeyer/commons/version` and `github.com/ckeyer/commons/version` might be both present in a binary (even if it would be a bad idea).

**Comment by ckeyer** [comment]
@FiloSottile Thanks.

**Comment by vearutop** [comment]
Hopefully this issue can still be solved to make import resolution consistent across `-X` and actual build.

Otherwise it makes a build dependency on code source layout, also maybe affecting `go modules` concept.
