### ISSUE TITLE
Race Detector Not Getting Triggered

### ISSUE THREAD

**Issue by dc0d** [golang/go#25010]
### What version of Go are you using (`go version`)?
1.10.1

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="..."
GOCACHE="..."
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="..."
GORACE=""
GOROOT="..."
GOTMPDIR=""
GOTOOLDIR="..."
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build698559401=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

In this code a byte array is being accessed concurrently (but no single item in the array is being accessed concurrently).

Why `-race` is not showing an error? https://play.golang.org/p/IeA4npcemf5

### What did you expect to see?

An error shown by race detector.

### What did you see instead?

No error shown by race detector.

**Comment by cznic** [comment]
Please explain where and why do you think there's a race. I cannot find it.

**Comment by randall77** [comment]
> but no single item in the array is being accessed concurrently

This is the key point.  Each array element is its own variable.  There is no data race (two concurrent accesses to the same variable, at least one of which is a write).
