### ISSUE TITLE
golang.org/ref/spec is incorrect

### ISSUE THREAD

**Issue by natemara** [golang/go#25014]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

I accessed the go spec at https://golang.org/ref/spec in an attempt to create a parser for go code as a learning exercise. Based on the specification, semicolons are required in several places where they are actually not. For example, the [`SourceFile` rule](https://golang.org/ref/spec#Source_file_organization) states that a semicolon is required after a package clause, after each import declaration, and after each top level declaration. This is not true, and can be verified by the default Hello World program at [play.golang.org](https://play.golang.org/p/HmnNoBf0p1z). There is no semicolon after the `package main` line, nor the import, nor the main function. 

This makes it very frustrating, as I now need to go through the rules and verify that the real go compiler behaves as the spec says it does. I'm not sure what the point of a spec is if the compiler everyone uses does not follow the spec.

### What did you expect to see?

I expected a language specification that accurately reflected the requirements of a go parser.

### What did you see instead?

Parser rules that do not accurately reflect the behavior of the go compiler.

**Comment by x1ddos** [comment]
You should probably also check Semicolons section:
https://golang.org/ref/spec#Semicolons

> The formal grammar uses semicolons ";" as terminators in a number of productions. Go programs may omit most of these semicolons using the following ...

**Comment by bradfitz** [comment]
Yup, what @x1ddos said.
