### ISSUE TITLE
x/crypto/acme,autocert: add support for TLS-ALPN

### ISSUE THREAD

**Issue by x1ddos** [golang/go#25013]
This is an alternative to TLS-SNI challenge types.
Not sure when and how it'll be accessible on Let's Encrypt, but posting this here to keep an eye on the progress.

Draft: https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-01
Boulder impl: https://github.com/letsencrypt/boulder/pull/3654

/cc @bradfitz

**Comment by cpu** [comment]
Folks interested in working on support for this challenge type in `x/crypto/acme` can get a head start by targeting [Pebble](https://github.com/letsencrypt/pebble/) instead of Boulder. We'll be reviewing letsencrypt/boulder#3654 in the near future but Pebble's support for `TLS-ALPN-01` challenges is already merged and available: https://github.com/letsencrypt/pebble/pull/112

**Comment by x1ddos** [comment]
@cpu will this feature be available on Let's Encrypt in v1 or only in v2? Or you don't know yet...

**Comment by cpu** [comment]
@x1ddos I don't think it has been discussed yet.

**Comment by mdebski** [comment]
Thanks! Take a look at certificate generation at [0], I think not much more should be needed in x/crypto/acme itself, other than wiring

[0] https://github.com/mdebski/golang-alpn-example/blob/master/alpnexample.go#L50

**Comment by cpu** [comment]
> btw, I think it was discussed yet and I heard from Roland that it would likely be available in both.

Correct :+1: Thanks for sharing that news here @mdebski

**Comment by mpx** [comment]
FYI, Let's Encrypt has enabled `tls-alpn-01` in production:
https://community.letsencrypt.org/t/tls-alpn-validation-method/63814

**Comment by bradfitz** [comment]
Now that x/crypto/acme supports this, this bug is just still open waiting for x/crypto/acme/autocert support now?

**Comment by mdebski** [comment]
To my understanding, yes.

**Comment by x1ddos** [comment]
Ok, will hack on a CL now.

**Comment by x1ddos** [comment]
Writing an end-to-end test, so takes a bit longer. Should finish tonight CET.
