### ISSUE TITLE
x/tools/godoc: packages missing from golang.org/pkg/

### ISSUE THREAD

**Issue by docmerlin** [golang/go#25022]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

er, this is for the https://golang.org/pkg/

### Does this issue reproduce with the latest release?

tip.golang.org/pkg seems to be working

### What operating system and processor architecture are you using (`go env`)?
firefox

### What did you do?

Go to https://golang.org/pkg/

### What did you expect to see?

The packages for the std library.

### What did you see instead?

Empty space.

**Comment by docmerlin** [comment]
<img width="1680" alt="screen shot 2018-04-23 at 4 59 53 pm" src="https://user-images.githubusercontent.com/1236827/39155469-cb0fce18-4717-11e8-8f0e-2dc57735499b.png">

**Comment by andybons** [comment]
Fixed.
