### ISSUE TITLE
testing: handle panics in subtests in order to print errors and log info

### ISSUE THREAD

**Issue by stephens2424** [golang/go#25021]
### What version of Go are you using (`go version`)?

1.10.1

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

OS X, Windows, App Engine (playground)

### What did you do?

https://play.golang.org/p/4-VN_VdQnrc

### What did you expect to see?

I expected to see the error that occurred to be printed, and then the panic.

### What did you see instead?

I see only the panic.

The exact use case I have is a table test where each subtest is using a different version of an external resource (message queue). An early subtest fails to perform some setup and leaves an internal thing in a bad state, so I expect my tests to not work fully at this point. However, because the later subtest panics when it encounters that bad state, the whole test function aborts without my previous calls to `t.Error` or `t.Fatal` (in the previous subtest) having their contents printed. Because of this, I lost critical error information that would have pointed me to the real issue with the earlier subtest's setup. Since the earlier subtest didn't print anything, its problem was not apparent.

**Comment by meirf** [comment]
Subtests were introduced in [1.7](https://golang.org/doc/go1.7#testing), which has the same behavior described by the OP.
(That's not to say this behavior is okay -just that it's unlikely there's a recent commit that's causing this.)

**Comment by ianlancetaylor** [comment]
CC @mpvl

**Comment by andrewmed** [comment]
Hi. This is "help needed" and "needs fix". 
Last commit is from Emmanuel Odeke, it adds missing test, but it is from February.
If help is still needed and no one objects, I am glad to pick this up.

**Comment by hanyangtay** [comment]
Change https://golang.org/cl/214822/ has fixed this.
This can be marked as resolved once the change is released.

**Comment by ianlancetaylor** [comment]
Thanks.  We can close it now.
