### ISSUE TITLE
x/build/cmd/gopherbot: created multiple backport issues (and now offline)

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25031]
@gopherbot created multiple backport issues at https://github.com/golang/go/issues/23920#issuecomment-383748679.

While some lag is expected for the "done" comment to reach the corpus, it should not have created duplicated issues anyway.

**gopherbot is offline while this is being fixed.**

**Comment by FiloSottile** [comment]
Now it's really offline.

**Comment by FiloSottile** [comment]
Between the first and second issue being opened there were multiple cycles that didn't open an issue. My hypothesis is that an event updating an issue in the corpus at time > X arrived before the creation of the issue at time X in maintner. So the `since` parameter was moved past the issue creation date, disabling the live GitHub API check.

https://github.com/golang/build/blob/58ba60d65fdebb279bcf7990e5b51beeb62e5b89/cmd/gopherbot/gopherbot.go#L358

Either that, or the GitHub API showed an inconsistent rollbacked view, which would be much harder to fix.

/cc @bradfitz about events arriving out of order in maintner.

**Comment by FiloSottile** [comment]
Deploying 4c90f83a585e99d6c4442b6117e77d06a1a6f6d4 pending merge to bring @gopherbot back online.

**Comment by FiloSottile** [comment]
Deploying 31e3e5b991e909e2bf818bc6f1574aff9272c1e9 because 4c90f83 wasn't rebased on top of the #25024 fix.

**Comment by FiloSottile** [comment]
It should be possible to check my hypothesis by looking at the maintner log, assuming it is append-only. If there is an event that sets a issue Updated field to >= 22:56:24 (#25028 creation time), and it appears *before* the event that makes #25028 visible, we found the issue.

**Comment by bradfitz** [comment]
It's an append-only log.

**Comment by FiloSottile** [comment]
A scan of the log confirms that's probably what happened.

```
25028 seen! (Created: 2018-04-23 22:56:24 +0000 UTC)
Most recent Updated seen so far: 2018-04-23 22:57:04 +0000 UTC
```

The *since* value passed to the GitHub API progressed past the 25028 creation time (disabling the live deduplication check) before 25028 reached the log (disabling the log deduplication check).

Now trying to figure out if using Created instead of Updated to progress the *since* parameter is historically safe.

**Comment by FiloSottile** [comment]
Unfortunately, I also found out-of-order creation events. They seem to mostly match maintner crashes, but two recent ones look like they were nothing else than load.

```
Out of order creation event! 2018-03-27 21:38:55 +0000 UTC (seen now, issue #24568) is before 2018-03-27 21:41:09 +0000 UTC (seen earlier, issue #24569)
Out of order creation event! 2018-03-27 21:37:36 +0000 UTC (seen now, issue #24567) is before 2018-03-27 21:41:09 +0000 UTC (seen earlier, issue #24569)
```

So I'm afraid also using Created to advance *since* is not safe, and we'll have to add a hacky buffer to account for out of order events as in CL 108977.

**Comment by FiloSottile** [comment]
(Full source and output: https://gist.github.com/FiloSottile/aa24968d7fe30553047940e98221d51a)
