### ISSUE TITLE
cmd/go: build `-ldflags="-s -w"` invalid

### ISSUE THREAD

**Issue by gooid** [golang/go#25046]
### What version of Go are you using (`go version`)?
go version go1.10.1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\GoLang\go.ext
set GORACE=
set GOROOT=d:\GoLang\go1.10.1
set GOTMPDIR=
set GOTOOLDIR=d:\GoLang\go1.10.1\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=B:\TEMP\go-build911831290=/tmp/go-build -gno-record-gcc-switches

### What did you do?
go source path:  D:\GoLang\go.ext\src\github.com\gooid\demo\main.go
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello")
}
```

cmd:
```
d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=d:\GoLang\go.ext

d:\GoLang\go.ext\src\github.com\gooid\demo>go build -ldflags="-s -w"

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
...
2018/04/24  10:05         1,259,520 demo.exe
...

d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=D:\GoLang\go.ext

d:\GoLang\go.ext\src\github.com\gooid\demo>go build -ldflags="-s -w"

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
...
2018/04/24  10:05         2,051,584 demo.exe
...

d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=d:\golang\go.ext

d:\GoLang\go.ext\src\github.com\gooid\demo>go build -ldflags="-s -w"

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
...
2018/04/24  10:06         2,051,584 demo.exe
...
```

### What did you expect to see?
The size of all demo.exe is 1,259,520 

### What did you see instead?
Different GOPATH  (but effective in Window),  The size of all demo.exe is different， `-ldflags="-s -w"` invalid。

**Comment by davecheney** [comment]
Can you please repeat the experiment with

go build -x -ldflags="-s -w"

**Comment by gooid** [comment]
d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=d:\GoLang\go.ext

**Comment by davecheney** [comment]
Can you also do the dir check to confirm that the size is different between the first and second invocation.

**Comment by gooid** [comment]
```

d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=d:\GoLang\go.ext

d:\GoLang\go.ext\src\github.com\gooid\demo>go build -x -ldflags="-s -w"
WORK=B:\TEMP\go-build416612238
mkdir -p $WORK\b001\
cat >$WORK\b001\importcfg.link << 'EOF' # internal
packagefile github.com/gooid/demo=C:\Users\liukaizan\AppData\Local\go-build\47\4733598739e08c94536bddb42f3ea21d2560aaa91
5e6956fc187d7984cc30c98-d
packagefile fmt=d:\GoLang\go1.10.1\pkg\windows_amd64\fmt.a
packagefile runtime=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime.a
packagefile errors=d:\GoLang\go1.10.1\pkg\windows_amd64\errors.a
packagefile io=d:\GoLang\go1.10.1\pkg\windows_amd64\io.a
packagefile math=d:\GoLang\go1.10.1\pkg\windows_amd64\math.a
packagefile os=d:\GoLang\go1.10.1\pkg\windows_amd64\os.a
packagefile reflect=d:\GoLang\go1.10.1\pkg\windows_amd64\reflect.a
packagefile strconv=d:\GoLang\go1.10.1\pkg\windows_amd64\strconv.a
packagefile sync=d:\GoLang\go1.10.1\pkg\windows_amd64\sync.a
packagefile unicode/utf8=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf8.a
packagefile runtime/internal/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\atomic.a
packagefile runtime/internal/sys=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\sys.a
packagefile sync/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\sync\atomic.a
packagefile internal/cpu=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\cpu.a
packagefile internal/poll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\poll.a
packagefile internal/syscall/windows=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows.a
packagefile internal/testlog=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\testlog.a
packagefile syscall=d:\GoLang\go1.10.1\pkg\windows_amd64\syscall.a
packagefile time=d:\GoLang\go1.10.1\pkg\windows_amd64\time.a
packagefile unicode/utf16=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf16.a
packagefile unicode=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode.a
packagefile internal/race=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\race.a
packagefile internal/syscall/windows/sysdll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\sysdll.a
packagefile internal/syscall/windows/registry=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\registry.a
EOF
mkdir -p $WORK\b001\exe\
cd .
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\link.exe" -o "B:\\TEMP\\go-build416612238\\b001\\exe\\a.out.exe" -impor
tcfg "B:\\TEMP\\go-build416612238\\b001\\importcfg.link" -buildmode=exe -buildid=L1EghNmYHPcFlIdgYz6G/yPzdyeFwEV_BsjwB48
UU/H1bKbtQyW5GIYnlynryD/L1EghNmYHPcFlIdgYz6G -s -w -extld=gcc "C:\\Users\\liukaizan\\AppData\\Local\\go-build\\47\\47335
98739e08c94536bddb42f3ea21d2560aaa915e6956fc187d7984cc30c98-d"
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\buildid.exe" -w "B:\\TEMP\\go-build416612238\\b001\\exe\\a.out.exe" # i
nternal
cp $WORK\b001\exe\a.out.exe demo.exe
rm -r $WORK\b001\

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
 驱动器 D 中的卷是 work
 卷的序列号是 0001-FC75

 d:\GoLang\go.ext\src\github.com\gooid\demo 的目录

2018/04/24  11:04         1,259,520 demo.exe
               1 个文件      1,259,520 字节
               0 个目录  6,755,278,848 可用字节

d:\GoLang\go.ext\src\github.com\gooid\demo>del demo.exe

d:\GoLang\go.ext\src\github.com\gooid\demo>set GOPATH=d:\golang\go.ext

d:\GoLang\go.ext\src\github.com\gooid\demo>go build -x -ldflags="-s -w"
WORK=B:\TEMP\go-build032957018
mkdir -p $WORK\b001\
cat >$WORK\b001\importcfg.link << 'EOF' # internal
packagefile github.com/gooid/demo=C:\Users\liukaizan\AppData\Local\go-build\1a\1ad9f3359e4cdb3920b3af8f43bc60045a6085159
aa06563b27ca154fe5938cf-d
packagefile fmt=d:\GoLang\go1.10.1\pkg\windows_amd64\fmt.a
packagefile runtime=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime.a
packagefile errors=d:\GoLang\go1.10.1\pkg\windows_amd64\errors.a
packagefile io=d:\GoLang\go1.10.1\pkg\windows_amd64\io.a
packagefile math=d:\GoLang\go1.10.1\pkg\windows_amd64\math.a
packagefile os=d:\GoLang\go1.10.1\pkg\windows_amd64\os.a
packagefile reflect=d:\GoLang\go1.10.1\pkg\windows_amd64\reflect.a
packagefile strconv=d:\GoLang\go1.10.1\pkg\windows_amd64\strconv.a
packagefile sync=d:\GoLang\go1.10.1\pkg\windows_amd64\sync.a
packagefile unicode/utf8=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf8.a
packagefile runtime/internal/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\atomic.a
packagefile runtime/internal/sys=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\sys.a
packagefile sync/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\sync\atomic.a
packagefile internal/cpu=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\cpu.a
packagefile internal/poll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\poll.a
packagefile internal/syscall/windows=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows.a
packagefile internal/testlog=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\testlog.a
packagefile syscall=d:\GoLang\go1.10.1\pkg\windows_amd64\syscall.a
packagefile time=d:\GoLang\go1.10.1\pkg\windows_amd64\time.a
packagefile unicode/utf16=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf16.a
packagefile unicode=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode.a
packagefile internal/race=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\race.a
packagefile internal/syscall/windows/sysdll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\sysdll.a
packagefile internal/syscall/windows/registry=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\registry.a
EOF
mkdir -p $WORK\b001\exe\
cd .
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\link.exe" -o "B:\\TEMP\\go-build032957018\\b001\\exe\\a.out.exe" -impor
tcfg "B:\\TEMP\\go-build032957018\\b001\\importcfg.link" -buildmode=exe -buildid=vFlAC6JQmS8x59lELmg8/qg_0bj3bXd7YdjORSd
5z/m1v7ZVfaEClTlxcNo9dI/vFlAC6JQmS8x59lELmg8 -extld=gcc "C:\\Users\\liukaizan\\AppData\\Local\\go-build\\1a\\1ad9f3359e4
cdb3920b3af8f43bc60045a6085159aa06563b27ca154fe5938cf-d"
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\buildid.exe" -w "B:\\TEMP\\go-build032957018\\b001\\exe\\a.out.exe" # i
nternal
cp $WORK\b001\exe\a.out.exe demo.exe
rm -r $WORK\b001\

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
 驱动器 D 中的卷是 work
 卷的序列号是 0001-FC75

 d:\GoLang\go.ext\src\github.com\gooid\demo 的目录

2018/04/24  11:05         2,051,584 demo.exe
               1 个文件      2,051,584 字节
               0 个目录  6,754,488,320 可用字节
```

**Comment by davecheney** [comment]
I the first invocation `-s -w` is being passed to link.exe
```
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\link.exe" -o "B:\\TEMP\\go-build416612238\\b001\\exe\\a.out.exe" -importcfg "B:\\TEMP\\go-build416612238\\b001\\importcfg.link" -buildmode=exe -buildid=L1EghNmYHPcFlIdgYz6G/yPzdyeFwEV_BsjwB48UU/H1bKbtQyW5GIYnlynryD/L1EghNmYHPcFlIdgYz6G -s -w -extld=gcc "C:\\Users\\liukaizan\\AppData\\Local\\go-build\\47\\4733598739e08c94536bddb42f3ea21d2560aaa915e6956fc187d7984cc30c98-d"
```
In the second it is missing
```
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\link.exe" -o "B:\\TEMP\\go-build032957018\\b001\\exe\\a.out.exe" -importcfg "B:\\TEMP\\go-build032957018\\b001\\importcfg.link" -buildmode=exe -buildid=vFlAC6JQmS8x59lELmg8/qg_0bj3bXd7YdjORSd5z/m1v7ZVfaEClTlxcNo9dI/vFlAC6JQmS8x59lELmg8 -extld=gcc "C:\\Users\\liukaizan\\AppData\\Local\\go-build\\1a\\1ad9f3359e4cdb3920b3af8f43bc60045a6085159aa06563b27ca154fe5938cf-d"
```
/cc @rsc

**Comment by gooid** [comment]
Does it work if you run go build -ldflags=all="-s -w"?
d:\GoLang\go.ext\src\github.com\gooid\demo>go build -x -ldflags=all="-s -w"
WORK=B:\TEMP\go-build374060654
mkdir -p $WORK\b001\
cat >$WORK\b001\importcfg.link << 'EOF' # internal
packagefile github.com/gooid/demo=C:\Users\liukaizan\AppData\Local\go-build\1a\1ad9f3359e4cdb3920b3af8f43bc60045a6085159
aa06563b27ca154fe5938cf-d
packagefile fmt=d:\GoLang\go1.10.1\pkg\windows_amd64\fmt.a
packagefile runtime=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime.a
packagefile errors=d:\GoLang\go1.10.1\pkg\windows_amd64\errors.a
packagefile io=d:\GoLang\go1.10.1\pkg\windows_amd64\io.a
packagefile math=d:\GoLang\go1.10.1\pkg\windows_amd64\math.a
packagefile os=d:\GoLang\go1.10.1\pkg\windows_amd64\os.a
packagefile reflect=d:\GoLang\go1.10.1\pkg\windows_amd64\reflect.a
packagefile strconv=d:\GoLang\go1.10.1\pkg\windows_amd64\strconv.a
packagefile sync=d:\GoLang\go1.10.1\pkg\windows_amd64\sync.a
packagefile unicode/utf8=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf8.a
packagefile runtime/internal/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\atomic.a
packagefile runtime/internal/sys=d:\GoLang\go1.10.1\pkg\windows_amd64\runtime\internal\sys.a
packagefile sync/atomic=d:\GoLang\go1.10.1\pkg\windows_amd64\sync\atomic.a
packagefile internal/cpu=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\cpu.a
packagefile internal/poll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\poll.a
packagefile internal/syscall/windows=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows.a
packagefile internal/testlog=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\testlog.a
packagefile syscall=d:\GoLang\go1.10.1\pkg\windows_amd64\syscall.a
packagefile time=d:\GoLang\go1.10.1\pkg\windows_amd64\time.a
packagefile unicode/utf16=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode\utf16.a
packagefile unicode=d:\GoLang\go1.10.1\pkg\windows_amd64\unicode.a
packagefile internal/race=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\race.a
packagefile internal/syscall/windows/sysdll=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\sysdll.a
packagefile internal/syscall/windows/registry=d:\GoLang\go1.10.1\pkg\windows_amd64\internal\syscall\windows\registry.a
EOF
mkdir -p $WORK\b001\exe\
cd .
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\link.exe" -o "B:\\TEMP\\go-build374060654\\b001\\exe\\a.out.exe" -impor
tcfg "B:\\TEMP\\go-build374060654\\b001\\importcfg.link" -buildmode=exe -buildid=tVFezFwIGIsU1SmKsjHV/qg_0bj3bXd7YdjORSd
5z/m1v7ZVfaEClTlxcNo9dI/tVFezFwIGIsU1SmKsjHV -s -w -extld=gcc "C:\\Users\\liukaizan\\AppData\\Local\\go-build\\1a\\1ad9f
3359e4cdb3920b3af8f43bc60045a6085159aa06563b27ca154fe5938cf-d"
"d:\\GoLang\\go1.10.1\\pkg\\tool\\windows_amd64\\buildid.exe" -w "B:\\TEMP\\go-build374060654\\b001\\exe\\a.out.exe" # i
nternal
cp $WORK\b001\exe\a.out.exe demo.exe
rm -r $WORK\b001\

d:\GoLang\go.ext\src\github.com\gooid\demo>dir demo.exe
 驱动器 D 中的卷是 work
 卷的序列号是 0001-FC75

 d:\GoLang\go.ext\src\github.com\gooid\demo 的目录

2018/04/24  12:33         1,259,520 demo.exe
               1 个文件      1,259,520 字节
               0 个目录  6,755,270,656 可用字节

**Comment by alexbrainman** [comment]
I suspect cmd/go breaks on windows when os.Getwd returns path that differs from what %GOPATH% contains just in case of its characters. For example, c:\go and C:\GO - both paths are correct paths on Windows. And they refer to the same directory on Windows. But cmd/go treats them as different directories:
https://github.com/golang/go/blob/dev.boringcrypto.go1.10/src/cmd/go/internal/load/search.go#L285

I see no way to fix this but to convert these paths to upper case (or lower case) before comparing on windows. Please let me know, if there is a better way.

I think this is a dup of #19491 and #24232

Alex

**Comment by gooid** [comment]
https://github.com/golang/go/blob/dev.boringcrypto.go1.10/src/cmd/go/internal/load/search.go#L285

maybe :
```
	return func(p *Package) bool {
		if rel, err := filepath.Rel(p.Dir, dir); err != nil || rel != "." {
			return false
		}
		return true
	}
```
@alexbrainman

**Comment by alexbrainman** [comment]
> I think this is a dup of #19491 and #24232

My mistake, that was meant to say that this current issue is a dup of #19491 and #24750



> maybe :
> 
> 	return func(p *Package) bool {
> 		if rel, err := filepath.Rel(p.Dir, dir); err != nil || rel != "." {
> 			return false
> 		}
> 		return true
> 	}
> @alexbrainman

I would not know.

Alex
