### ISSUE TITLE
website: x/vgo, x/lint subrepos are 404

### ISSUE THREAD

**Issue by shurcooL** [golang/go#25048]
https://golang.org/x/vgo and https://golang.org/x/lint are 404 right now. That means godoc.org can't display their docs, and they can't be fetched with `go get`, etc.

```
$ curl https://golang.org/x/vgo
404 page not found
$ curl https://golang.org/x/lint
404 page not found

$ curl -H 'Accept: text/plain' https://godoc.org/golang.org/x/vgo
NOT FOUND
$ curl -H 'Accept: text/plain' https://godoc.org/golang.org/x/lint
NOT FOUND

$ export GOPATH=/tmp/empty
$ go get -d golang.org/x/vgo
package golang.org/x/vgo: unrecognized import path "golang.org/x/vgo" (parse https://golang.org/x/vgo?go-get=1: no go-import meta tags ())
$ go get -d golang.org/x/lint
package golang.org/x/lint: unrecognized import path "golang.org/x/lint" (parse https://golang.org/x/lint?go-get=1: no go-import meta tags ())
```

They used to work recently. I don't know when exactly they stopped working. The other subrepos are fine.

There are still entries for them at https://github.com/golang/tools/blob/c1def519f03ddf76f16b3e444ee1095d73afa01b/cmd/godoc/x.go#L35 and https://github.com/golang/tools/blob/c1def519f03ddf76f16b3e444ee1095d73afa01b/cmd/godoc/x.go#L50, so I'm guessing it's related to the version of godoc deployed right now.

/cc @andybons @bradfitz

**Comment by bradfitz** [comment]
Did the master branch get deployed, then the release branch deployed (reverting the x/link change)?

This needs to be cherry-picked back to release branch probably.

/cc @FiloSottile too.

**Comment by FiloSottile** [comment]
@andybons mentioned while fixing #25022 that he had to fix the deploy scripts to use the release branch, so probably yeah.

**Comment by oiooj** [comment]
Many CI test which use `x/lint` failed now.  

https://github.com/golang/lint/issues/397

**Comment by andybons** [comment]
On it.

**Comment by oiooj** [comment]
The service is normal now.

```

Sosaras-Air:build sosara$ go get -v golang.org/x/lint
Fetching https://golang.org/x/lint?go-get=1
Parsing meta tags from https://golang.org/x/lint?go-get=1 (status code 200)
get "golang.org/x/lint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at https://golang.org/x/lint?go-get=1
golang.org/x/lint (download)
golang.org/x/tools/go/ast/astutil
golang.org/x/tools/go/gcimporter15
golang.org/x/tools/go/gcexportdata
golang.org/x/lint

```

**Comment by andybons** [comment]
Fix has been deployed. I apologize for the downtime. Will follow up with monitoring so that we can catch this sooner in the future.

**Comment by FiloSottile** [comment]
@bradfitz from https://github.com/golang/lint/issues/397#issuecomment-383994496 with context, for anyone curious:

> The original lint & vgo redirects were accidentally deployed from the master branch. They were never cherry-picked to the release branch. When golang.org was redeployed later from the release branch (correctly), it effectively reverted the lint redirects.
>
> https://golang.org/cl/109095 does the necessary cherry-pick to the release branch.
