### ISSUE TITLE
x/tools/go/gcexportdata: broken tests since CL 106797

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25052]
https://go-review.googlesource.com/c/go/+/106797 broke golang.org/x/tools/go/gcexportdata and some other tests in x/tools.

https://build.golang.org/?repo=golang.org%2fx%2ftools

https://build.golang.org/log/6b1bda36613153b5c4fe514d34c2b351a38eeae9

**Comment by dsnet** [comment]
Is anyone working on getting this back-ported?

**Comment by bcmills** [comment]
@mdempsky, are you planning to fix this? The `x/tools` repo is currently still broken.

Should we roll back https://golang.org/cl/106797 in the meantime?

**Comment by alandonovan** [comment]
Rebecca has agreed to look into this.

**Comment by bradfitz** [comment]
This isn't milestone "Unreleased". Build breakages should be fixed soon because they impact everybody else trying to run tests in that tree. I'll repurpose this to Go 1.11 and send a test to disable those tests in the meantime.

**Comment by FiloSottile** [comment]
I think this is what the rarely-used Soon is for?

**Comment by bradfitz** [comment]
We don't use Soon and I think we should delete it and replace it with a label if anything.
