### ISSUE TITLE
x/crypto/internal/chacha20: improve performance for ppc64le

### ISSUE THREAD

**Issue by pfsmorigo** [golang/go#25051]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Using upstream.

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="ppc64le"
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"

### What did you do?

I opened this issue in order to submit a patch that adds asm implementation for chacha20 using vector instructions on ppc64le.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by laboger** [comment]
The heading should start with x/crypto/chacha20poly1305:

**Comment by pfsmorigo** [comment]
I renamed to "x/crypto/internal/chacha20" since chacha20 in not inside chacha20poly1305 directory anymore (see commit 49373064ff7c)

**Comment by pfsmorigo** [comment]
@dot-asm Hello Andy, can you add chacha/asm/chacha-ppc.pl to the cryptogams repository? Same as you did for https://github.com/golang/go/issues/22637 Thanks!

**Comment by pfsmorigo** [comment]
Any update @dot-asm?

**Comment by dot-asm** [comment]
For reference, the original implementation had face-lift, dramatically improving performance on POWER9, by ~80%. Trouble there is that POWER9 is kind of "allergic" to mixtures of scalar and vector instructions, which original fits-all-ppc is heavily relying on. Since 'go' doesn't seem to be concerned about anything pre-POWER8, it would be sensible to deploy new code path...

**Comment by dot-asm** [comment]
POWER9 was merely a trigger for *a* change, because it was observed to perform unexpectedly poorly. But the change itself is PowerISA 2.07-based, so that it works on POWER8 and forward. Is it faster on POWER8? Of course, just not as much as on POWER9, only by ~40%.

**Comment by laboger** [comment]
Due to the deadline for Go 1.13 we will submit it as is for now to get better performance, then convert to the vsx implementation in Go 1.14 to improve further.
