### ISSUE TITLE
test/codegen: brittle on multi-line go expressions that get coalesced into single instructions

### ISSUE THREAD

**Issue by benshi001** [golang/go#25061]
The following test passed with the very long line,

	func load_byte8_uint64_idx(s []byte, idx int) uint64 {
	// arm64:`MOVD\s\(R[0-9]+\)\(R[0-9]+<<3\)`,-`ORR\tR[0-9]+<<[0-9]+`
		return uint64(s[idx<<3]) | uint64(s[(idx<<3)+1])<<8 | uint64(s[(idx<<3)+2])<<16 | uint64(s[(idx<<3)+3])<<24 | uint64(s[(idx<<3)+4])<<32 | uint64(s[(idx<<3)+5])<<40 | uint64(s[(idx<<3)+6])<<48 | uint64(s[(idx<<3)+7])<<56
	}

But if the long line was broken two lines, the test would fail, though expected asm had been generated.

	func load_byte8_uint64_idx(s []byte, idx int) uint64 {
	// arm64:`MOVD\s\(R[0-9]+\)\(R[0-9]+<<3\)`,-`ORR\tR[0-9]+<<[0-9]+`
		return uint64(s[idx<<3]) | uint64(s[(idx<<3)+1])<<8 | uint64(s[(idx<<3)+2])<<16 | uint64(s[(idx<<3)+3])<<24 |
			uint64(s[(idx<<3)+4])<<32 | uint64(s[(idx<<3)+5])<<40 | uint64(s[(idx<<3)+6])<<48 | uint64(s[(idx<<3)+7])<<56
	}

with error message

	2018/04/25 13:02:09 "".load_byte8_uint64_idx STEXT size=176 args=0x28 locals=0x8
	0x0000 00000 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	TEXT	"".load_byte8_uint64_idx(SB), $8-40
	0x0000 00000 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	16(g), R1
	0x0004 00004 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	RSP, R2
	0x0008 00008 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	CMP	R1, R2
	0x000c 00012 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	BLS	160
	0x0010 00016 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD.W	R30, -16(RSP)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	FUNCDATA	ZR, gclocals·6b4b7e46e7c3e785dae149c064ae0142(SB)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	MOVD	"".s+8(FP), R0
	0x0018 00024 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	MOVD	"".idx+24(FP), R1
	0x001c 00028 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R1<<3, R0
	0x0020 00032 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BLS	152
	0x0024 00036 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	LSL	$3, R1, R2
	0x0028 00040 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$1, R2, R3
	0x002c 00044 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x0030 00048 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x0034 00052 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$2, R2, R3
	0x0038 00056 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x003c 00060 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x0040 00064 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$3, R2, R3
	0x0044 00068 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x0048 00072 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x004c 00076 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	ADD	$4, R2, R3
	0x0050 00080 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CMP	R0, R3
	0x0054 00084 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	BHS	144
	0x0058 00088 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	ADD	$5, R2, R3
	0x005c 00092 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CMP	R0, R3
	0x0060 00096 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	BHS	144
	0x0064 00100 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	ADD	$6, R2, R3
	0x0068 00104 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CMP	R0, R3
	0x006c 00108 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	BHS	144
	0x0070 00112 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	ADD	$7, R2, R2
	0x0074 00116 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CMP	R0, R2
	0x0078 00120 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	BHS	144
	0x007c 00124 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	MOVD	"".s(FP), R0
	0x0080 00128 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	MOVD	(R0)(R1<<3), R0
	0x0084 00132 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	MOVD	R0, "".~r2+32(FP)
	0x0088 00136 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	MOVD.P	16(RSP), R30
	0x008c 00140 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	RET	(R30)
	0x0090 00144 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	PCDATA	ZR, $1
	0x0090 00144 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CALL	runtime.panicindex(SB)
	0x0094 00148 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	UNDEF
	0x0098 00152 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	PCDATA	ZR, $1
	0x0098 00152 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CALL	runtime.panicindex(SB)
	0x009c 00156 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	UNDEF
	0x00a0 00160 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	NOP
	0x00a0 00160 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	PCDATA	$0, $-1
	0x00a0 00160 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	R30, R3
	0x00a4 00164 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	CALL	runtime.morestack_noctxt(SB)
	0x00a8 00168 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	JMP	0
	0x0000 81 0b 40 f9 e2 03 00 91 5f 00 01 eb a9 04 00 54  ..@....._......T
	0x0010 fe 0f 1f f8 e0 13 40 f9 e1 1b 40 f9 1f 0c 01 eb  ......@...@.....
	0x0020 c9 03 00 54 22 f0 7d d3 43 04 00 91 7f 00 00 eb  ...T".}.C.......
	0x0030 42 03 00 54 43 08 00 91 7f 00 00 eb e2 02 00 54  B..TC..........T
	0x0040 43 0c 00 91 7f 00 00 eb 82 02 00 54 43 10 00 91  C..........TC...
	0x0050 7f 00 00 eb e2 01 00 54 43 14 00 91 7f 00 00 eb  .......TC.......
	0x0060 82 01 00 54 43 18 00 91 7f 00 00 eb 22 01 00 54  ...TC......."..T
	0x0070 42 1c 00 91 5f 00 00 eb c2 00 00 54 e0 0f 40 f9  B..._......T..@.
	0x0080 00 78 61 f8 e0 1f 00 f9 fe 07 41 f8 c0 03 5f d6  .xa.......A..._.
	0x0090 00 00 00 94 00 17 a7 be 00 00 00 94 00 17 a7 be  ................
	0x00a0 e3 03 1e aa 00 00 00 94 d6 ff ff 17 00 00 00 00  ................
	rel 140+0 t=11 +0
	rel 144+4 t=10 runtime.panicindex+0
	rel 152+4 t=10 runtime.panicindex+0
	rel 164+4 t=10 runtime.morestack_noctxt+0
	# go run run.go -- codegen/memcombine.go
	codegen/memcombine.go:125: linux/arm64/: opcode not found: "^MOVD\\s\\(R[0-9]+\\)\\(R[0-9]+<<3\\)"

**Comment by ALTree** [comment]
If you split the OR sequence into two lines, the `MOVD   (R0)(R1<<3), R0` instruction you are matching gets a line number from the last line of Go code, so the regexp should go near the last line. This is what happens in this other codegen test:

```
1 func zero_byte_16(b []byte) {
2 	_ = b[15]
3	b[0], b[1], b[2], b[3] = 0, 0, 0, 0
4	b[4], b[5], b[6], b[7] = 0, 0, 0, 0
5	b[8], b[9], b[10], b[11] = 0, 0, 0, 0
6	b[12], b[13], b[14], b[15] = 0, 0, 0, 0 // arm64:"STP",-"MOVB",-"MOVH",-"MOVW"
7  }
```

We want all the zeroing to be coalesced into an `STP` on arm64, but when that happens the compiler assigns line number `6` (where the *last* assignment is) to the `STP` instruction, and for this reason the regexp needs to go near the last line.

It's a limitation of the current approach (if for some reason the compiler starts to assign line number `3` to the `STP`, we'll need to update the test); but I'm not sure how you would protect from this.

**Comment by benshi001** [comment]
I see the reason. Thank you.

**Comment by benshi001** [comment]
Sorry, still failed.

	func load_byte8_uint64_idx(s []byte, idx int) uint64 {
		return uint64(s[idx<<3]) | uint64(s[(idx<<3)+1])<<8 | uint64(s[(idx<<3)+2])<<16 | uint64(s[(idx<<3)+3])<<24 |
			uint64(s[(idx<<3)+4])<<32 | uint64(s[(idx<<3)+5])<<40 | uint64(s[(idx<<3)+6])<<48 |
			uint64(s[(idx<<3)+7])<<56 // arm64:`MOVD\t\(R[0-9]+\)\(R[0-9]+<<3\)`,-`ORR\tR[0-9]+<<[0-9]+`
		}

	0x0000 00000 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	TEXT	"".load_byte8_uint64_idx(SB), $8-40
	0x0000 00000 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	16(g), R1
	0x0004 00004 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	RSP, R2
	0x0008 00008 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	CMP	R1, R2
	0x000c 00012 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	BLS	168
	0x0010 00016 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD.W	R30, -16(RSP)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	FUNCDATA	ZR, gclocals·6b4b7e46e7c3e785dae149c064ae0142(SB)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0014 00020 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	MOVD	"".s+8(FP), R0
	0x0018 00024 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	MOVD	"".idx+24(FP), R1
	0x001c 00028 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	CMP	R1<<3, R0
	0x0020 00032 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	BLS	160
	0x0024 00036 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	LSL	$3, R1, R2
	0x0028 00040 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	ADD	$1, R2, R3
	0x002c 00044 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	CMP	R0, R3
	0x0030 00048 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	BHS	160
	0x0034 00052 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	ADD	$2, R2, R3
	0x0038 00056 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	CMP	R0, R3
	0x003c 00060 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	BHS	160
	0x0040 00064 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	ADD	$3, R2, R3
	0x0044 00068 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	CMP	R0, R3
	0x0048 00072 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	BHS	160
	0x004c 00076 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$4, R2, R3
	0x0050 00080 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x0054 00084 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x0058 00088 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$5, R2, R3
	0x005c 00092 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x0060 00096 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x0064 00100 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	ADD	$6, R2, R3
	0x0068 00104 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CMP	R0, R3
	0x006c 00108 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	BHS	152
	0x0070 00112 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	ADD	$7, R2, R2
	0x0074 00116 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CMP	R0, R2
	0x0078 00120 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	BHS	144
	0x007c 00124 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	MOVD	"".s(FP), R0
	0x0080 00128 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	MOVD	(R0)(R1<<3), R0
	0x0084 00132 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	MOVD	R0, "".~r2+32(FP)
	0x0088 00136 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	MOVD.P	16(RSP), R30
	0x008c 00140 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	RET	(R30)
	0x0090 00144 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	PCDATA	ZR, $1
	0x0090 00144 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	CALL	runtime.panicindex(SB)
	0x0094 00148 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:126)	UNDEF
	0x0098 00152 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	PCDATA	ZR, $1
	0x0098 00152 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	CALL	runtime.panicindex(SB)
	0x009c 00156 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:125)	UNDEF
	0x00a0 00160 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	PCDATA	ZR, $1
	0x00a0 00160 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	CALL	runtime.panicindex(SB)
	0x00a4 00164 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	UNDEF
	0x00a8 00168 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:124)	NOP
	0x00a8 00168 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	PCDATA	$0, $-1
	0x00a8 00168 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	MOVD	R30, R3
	0x00ac 00172 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	CALL	runtime.morestack_noctxt(SB)
	0x00b0 00176 (/home/local/SPREADTRUM/ben.shi/Desktop/go/test/codegen/memcombine.go:123)	JMP	0
	0x0000 81 0b 40 f9 e2 03 00 91 5f 00 01 eb e9 04 00 54  ..@....._......T
	0x0010 fe 0f 1f f8 e0 13 40 f9 e1 1b 40 f9 1f 0c 01 eb  ......@...@.....
	0x0020 09 04 00 54 22 f0 7d d3 43 04 00 91 7f 00 00 eb  ...T".}.C.......
	0x0030 82 03 00 54 43 08 00 91 7f 00 00 eb 22 03 00 54  ...TC......."..T
	0x0040 43 0c 00 91 7f 00 00 eb c2 02 00 54 43 10 00 91  C..........TC...
	0x0050 7f 00 00 eb 22 02 00 54 43 14 00 91 7f 00 00 eb  ...."..TC.......
	0x0060 c2 01 00 54 43 18 00 91 7f 00 00 eb 62 01 00 54  ...TC.......b..T
	0x0070 42 1c 00 91 5f 00 00 eb c2 00 00 54 e0 0f 40 f9  B..._......T..@.
	0x0080 00 78 61 f8 e0 1f 00 f9 fe 07 41 f8 c0 03 5f d6  .xa.......A..._.
	0x0090 00 00 00 94 00 17 a7 be 00 00 00 94 00 17 a7 be  ................
	0x00a0 00 00 00 94 00 17 a7 be e3 03 1e aa 00 00 00 94  ................
	0x00b0 d4 ff ff 17 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 140+0 t=11 +0
	rel 144+4 t=10 runtime.panicindex+0
	rel 152+4 t=10 runtime.panicindex+0
	rel 160+4 t=10 runtime.panicindex+0
	rel 172+4 t=10 runtime.morestack_noctxt+0
	# go run run.go -- codegen/memcombine.go
	
	codegen/memcombine.go:126: linux/arm64/: opcode not found: "^MOVD\\t\\(R[0-9]+\\)\\(R[0-9]+<<3\\)"

**Comment by benshi001** [comment]
Though there is a walkaround, I still expect to see the removal of such a limitation in the future.

**Comment by ALTree** [comment]
Can you include the line numbers in the Go code like I did above:

```
1 func zero_byte_16(b []byte) {
2 	_ = b[15]
3	b[0], b[1], b[2], b[3] = 0, 0, 0, 0
4	b[4], b[5], b[6], b[7] = 0, 0, 0, 0
5	b[8], b[9], b[10], b[11] = 0, 0, 0, 0
6	b[12], b[13], b[14], b[15] = 0, 0, 0, 0 // arm64:"STP",-"MOVB",-"MOVH",-"MOVW"
7  }
```

?

**Comment by benshi001** [comment]
123 func load_byte8_uint64_idx(s []byte, idx int) uint64 {
	124 	return uint64(s[idx<<3]) | uint64(s[(idx<<3)+1])<<8 | uint64(s[(idx<<3)+2])<<16 | uint64(s[(idx<<3)+3])<<24 |
	125 		uint64(s[(idx<<3)+4])<<32 | uint64(s[(idx<<3)+5])<<40 | uint64(s[(idx<<3)+6])<<48 |
	126 		uint64(s[(idx<<3)+7])<<56 // arm64:`MOVD\t\(R[0-9]+\)\(R[0-9]+<<3\)`,-`ORR\tR[0-9]+<<[0-9]+`
	127 	}

**Comment by ALTree** [comment]
Oh, so `MOVD	(R0)(R1<<3), R0` gets assigned to the middle line (125)? Is this expected? 

Anyway I suggest keeping the whole expression on one line and the regexp on the line above, for now.

**Comment by ALTree** [comment]
(I've changed the title to describe the general issue we're having here).

**Comment by benshi001** [comment]
It passed with a quite strange form

	123 func load_byte8_uint64_idx(s []byte, idx int) uint64 {
	124 	return uint64(s[idx<<3]) | uint64(s[(idx<<3)+1])<<8 | uint64(s[(idx<<3)+2])<<16 | uint64(s[(idx<<3)+3])<<24 |
	125 	uint64(s[(idx<<3)+4])<<32 | uint64(s[(idx<<3)+5])<<40 | uint64(s[(idx<<3)+6])<<48 | // arm64:`MOVD\s\(R[0-9]+\)\(R[0-9]+<<3\)`,-`ORR\tR[0-9]+<<[0-9]+`
	126 	uint64(s[(idx<<3)+7])<<56
	127 }

**Comment by rasky** [comment]
I think that the best solution in this case is simply to keep everything in one line. It's a little harder to read but it will be stable, with no surprises in the future.

Let's see how often it happens before designing a workaround.

**Comment by ianlancetaylor** [comment]
CC @randall77

**Comment by randall77** [comment]
I agree with @rasky , it's slightly painful to make it one long line, but probably simpler than complicating the matching algorithm.
I'll close for now, but feel free to reopen if it starts getting more painful, or you see a simple way of modifying the matching algorithm.
