### ISSUE TITLE
Debug stack variables value is not right when I test LinkedList

### ISSUE THREAD

**Issue by suyuanhxx** [golang/go#25063]
### What version of Go are you using (`go version`)?
`go version go1.10.1 windows/amd64`
### Does this issue reproduce with the latest release?
GoLand version `2018.1`, `Go build 181.4203.567, built on 3, 28 ,2018`
### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoWork
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build760791078=/tmp/go-build -gno-record-gcc-switches
```
### What did you do?
When I debug a singly linked list, build a singly linked list from an array. I find the debug Variables value  is not right. Then I run it. Find it works well. [This is my code](https://gist.github.com/8dcf0bc27030ae1a930bca6393168e1f.git)
### What did you expect to see?
I hope debug Variables value is right with run. Thanks
### What did you see instead?
[https://imgchr.com/i/C1iPfg](https://imgchr.com/i/C1iPfg)

**Comment by agnivade** [comment]
Please correct me if I am wrong, but as I understand this is a bug for GoLand and not the Go language.

**Comment by dlsniper** [comment]
I confirm this is a [known issue](https://youtrack.jetbrains.com/issue/GO-5180) in GoLand's side, the issue can be safely closed here. Thank you.

**Comment by ianlancetaylor** [comment]
Thanks for following up.
