### ISSUE TITLE
x/vgo: vgo depends on as-yet-unmerged cmd/go/internal/modfetch/gitrepo

### ISSUE THREAD

**Issue by flibustenet** [golang/go#25062]
### What operating system and processor architecture are you using (`go env`)?

go version go1.10.1 linux/amd64

### What did you do?

go get -u golang.org/x/vgo

### What did you see instead?

package cmd/go/internal/modfetch/gitrepo: unrecognized import path "cmd/go/internal/modfetch/gitrepo" (import path does not begin with hostname)

**Comment by myitcv** [comment]
cc @rsc - not sure how the trybots passed here.... because downloading https://go-review.googlesource.com/c/vgo/+/107657 locally failed for me:

```
cd $(go list -f "{{.Dir}}" golang.org/x/vgo)
git fetch https://go.googlesource.com/vgo refs/changes/57/107657/3 && git checkout FETCH_HEAD
go install
```

gives:

```
vendor/cmd/go/internal/modfetch/bitbucket/fetch.go:12:2: cannot find package "cmd/go/internal/modfetch/gitrepo" in any of:
        /home/myitcv/gostuff/src/golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo (vendor tree)
        /home/myitcv/gos/src/cmd/go/internal/modfetch/gitrepo (from $GOROOT)
        /home/myitcv/gostuff/src/cmd/go/internal/modfetch/gitrepo (from $GOPATH)
```

**Comment by myitcv** [comment]
cc @bcmills too

**Comment by oiooj** [comment]
It seems that it need CL https://go-review.googlesource.com/c/vgo/+/107656 merged first.

**Comment by rsc** [comment]
https://go-review.googlesource.com/c/vgo/+/107656 is now submitted,
along with the important fix https://go-review.googlesource.com/c/vgo/+/109336.

**Comment by myitcv** [comment]
Thanks - is it significant or not that the trybots passed for this, despite the build error? 

(I actually have no idea where to look to see what they're "try"-ing)
