### ISSUE TITLE
os/exec: Command("dir") not work in powershell on Windows

### ISSUE THREAD

**Issue by dfy167** [golang/go#25070]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=E:\project\go\gopath\bin
set GOCACHE=C:\Users\enen\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\project\go\gopath
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\enen\AppData\Local\Temp\go-build779536122=/tmp/go-build -gno-record-gcc-switches
### What did you do?
```
        cmd := exec.Command("dir")
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()
```

in windows cmd console:

```
go run datax.go
datax.exe  datax.go
```
in windows powershell console:
```
go run datax.go
```
nothing shows

### What did you expect to see?

datax.exe  datax.go

### What did you see instead?
nothing

**Comment by dwatley** [comment]
I can't reproduce this using your code snippet. What's your PowerShell version?

```
PS C:\Users\Dominic\Projects\Go\src\runtest> go run datax.go
datax.exe  datax.go

PS C:\Users\Dominic\Projects\Go\src\runtest> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17650  1001
````

**Comment by mattn** [comment]
"dir" is internal command of cmd.exe not "dir.exe". You can make sure `where dir`. If you have `dir.exe` on your environment, it probably be a command provided from msys2 or mingw commands. Maybe `cmd.Run()` return error.

FYI, If you want to run dir of cmd.exe, you must call like below.

```
cmd := exec.Command("cmd", "/c", "dir")
// snip
err := cmd.Run()
if err != nil {
    log.Fatal(err)
}
```
