### ISSUE TITLE
doc: unclear why the example code might be buggy

### ISSUE THREAD

**Issue by fhalde** [golang/go#25072]
In the [go doc](https://golang.org/doc/effective_go.html#concurrency) talking about concurrency, it's little unclear as to why the below code is buggy

```
func Serve(queue chan *Request) {
    for req := range queue {
        sem <- 1
        go func() {
            process(req) // Buggy; see explanation below.
            <-sem
        }()
    }
}
```

The doc says that the req is reused in the for loop. But the actual reason for the code to be buggy is because the anonymous `func()` forms a closure enclosing the req variable. Any changes to req will be visible to all the goroutines. I think mentioning closure can help in understanding this better

**Comment by agnivade** [comment]
>  But the actual reason for the code to be buggy is because the anonymous func() forms a closure enclosing the req variable.

Well, saying that `req` variable is shared across all goroutines is also not wrong.

Closure is indeed mentioned in the next line.
> Here's one way to do that, passing the value of req as an argument to the closure in the goroutine:

FWIW, it's pretty clear to me. ping @robpike for comments.

**Comment by fhalde** [comment]
@agnivade hmm. should've read the next line ;)
