### ISSUE TITLE
install: provide windows/arm64 binary releases

### ISSUE THREAD

**Issue by necrose99** [golang/go#25084]
go windows-arm64.msi would be a plus.

**Comment by necrose99** [comment]
https://forum.pine64.org/archive/index.php?thread-1939.html iot for rock64 .. 

https://developer.microsoft.com/en-us/windows/iot

**Comment by ALTree** [comment]
Go doesn't support windows/arm64 so an issue asking for an installer seems premature.. I'm sure that after someone ports Go to windows/arm64, there'll be an installer.

**Comment by necrose99** [comment]
Arm64 windows builds for iot was main point. 
So far trying to force a build on windows with arm64,  fails .. 
At any rate ive not seen any updates.. on arm64 windows.  

Honeytrap could be useful.. on iot.. it is windows...
It would put cheeze in a tempting rat trap.. if only golang had builds..
