### ISSUE TITLE
cmd/link: accepts nonsense ldflags

### ISSUE THREAD

**Issue by heschik** [golang/go#25085]
I don't think this should succeed:

```
~/go/bin/go build -ldflags=a=b hello.go  && ./hello
hi
```

I haven't checked the code, but from strace it looks like go build is swallowing ldflags that don't start with a `-`.

**Comment by ianlancetaylor** [comment]
The syntax `-ldflags=a=b` means "pass `b` to all packages that match the pattern `a`".  If there are no packages that match the pattern `a`, then the flag will never be passed.

**Comment by heschik** [comment]
Oh. That makes sense, I just didn't even consider that that syntax would apply to ldflags. I'm not sure what good it is, but it's not a bug. Thanks.
