### ISSUE TITLE
cmd/go: coverpkg broken behaviour in version 1.10.1

### ISSUE THREAD

**Issue by apremalal** [golang/go#25093]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ag/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ag/workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2t/8v5wp6zn36n2fgxf5qvd75zw0000gq/T/go-build821224783=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

My repo structure is like below, and I'm executing commands indie folder

```
<go-test-cov>
 |
  -<models>
 |
  -<models-test>
```
I have hosted the code in [github](https://github.com/apremalal/go-test-cov) for easy referencing.

models/math.go

```
package models

func Add(x,y int) int{
  return x+y
}
```
models_test/math_test.go

```
package models_test

import (
   "testing"
  "github.com/apremalal/go-test-cov/models"
)

func TestAdd(t *testing.T) {
    total := models.Add(5, 5)
    if total != 10 {
       t.Errorf("Sum was incorrect, got: %d, want: %d.", total, 10)
    }
}
```

I tried the following command which worked in golang 1.9.X versions. And gave me correct coverage results

`go test -v ./models_test -coverpkg=./models -coverprofile=c.out && go tool cover -func=c.out`

But with version 1.10.1 it throws a warning saying
```
no packages being tested depend on matches for pattern ./models
```

And the coverage is always 0% with the above command

### What did you expect to see?
100% test coverage

### What did you see instead?
0% test coverage

**Comment by imkos** [comment]
go test  add param: -count=1

**Comment by majewsky** [comment]
I can reproduce the issue with [package github.com/majewsky/schwift](https://github.com/majewsky/schwift) and Go 1.10.1. Downgrading to Go 1.9.4 fixes the problem for me.

**Comment by majewsky** [comment]
Still reproducible with Go 1.10.2. Furthermore, I noticed that the warning that @apremalal mentions also exists in 1.9.4 (where coverage is reported correctly), but is worded slightly differently. With Go 1.9.4:

```
$ go test -covermode count -coverpkg github.com/majewsky/schwift,github.com/majewsky/schwift/gopherschwift  -coverprofile cover.out github.com/majewsky/schwift/tests
warning: no packages being tested depend on github.com/majewsky/schwift
warning: no packages being tested depend on github.com/majewsky/schwift/gopherschwift
ok      github.com/majewsky/schwift/tests       14.399s coverage: 80.3% of statements in github.com/majewsky/schwift, github.com/majewsky/schwift/gopherschwift
```

Same command with Go 1.10.2:

```
warning: no packages being tested depend on matches for pattern github.com/majewsky/schwift
warning: no packages being tested depend on matches for pattern github.com/majewsky/schwift/gopherschwift
ok      github.com/majewsky/schwift/tests       12.036s coverage: 0.0% of statements in github.com/majewsky/schwift, github.com/majewsky/schwift/gopherschwift
```

This makes me think that e33794fbc2067515c7546ab3b35fe229eeec2a0b is where the error was introduced. I did not have the time to do a bisect, though.

**Comment by davecheney** [comment]
Go 1.11

**Comment by vaishalig2693** [comment]
Thanks @davecheney

**Comment by TACIXAT** [comment]
Sorry to bump this, but for the search indexers:

If you're really confused about how to get code coverage for an external package or imported package in golang, you might be running into this bug. Update to 1.11+, then `-coverpkg` will work with the package name.
