### ISSUE TITLE
x/vgo: fetching broken on older git versions

### ISSUE THREAD

**Issue by flibustenet** [golang/go#25102]
### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?

go get -u golang.org/x/vgo (just now)

### What did you do?

```bash
$ curl -sS https://swtch.com/hello.go >hello.go
$ echo > go.mod
$ vgo build

vgo: resolving import "rsc.io/quote"
vgo: import "github.com/you/hello" ->
	import "rsc.io/quote": git fetch --depth=1 https://github.com/rsc/quote c4d4236f92427c64bfbcf1cc3f8142ab18f30b22 in /home/wilk/go/src/v/cache/vcswork/af72e8eb60eb05152f7c8a104173245f2891ad0a76bf7d2886307ccb7b12ed20: exit status 128:
	error: no such remote ref c4d4236f92427c64bfbcf1cc3f8142ab18f30b22
```

The same with others imports.

Maybe @rsc could ping us for alpha releases where we can begin to test new improvements ? (we are so impatient !)

**Comment by utrack** [comment]
Same for me, but with `uber/zap` repo.
It can't find ref that's definitely there in the upstream.

**Comment by oiooj** [comment]
I can't reproduce @flibustenet 's issue. Everything is OK here, and the remote ref `[c4d4236f92427c64bfbcf1cc3f8142ab18f30b22](https://github.com/rsc/quote/commit/c4d4236f92427c64bfbcf1cc3f8142ab18f30b22)` exists.

**Comment by eraclitux** [comment]
I'm having same issue, @oiooj can you attach `git --version`?

**Comment by oiooj** [comment]
Sure. @eraclitux 

```
$ git version
git version 2.14.3 (Apple Git-98)
```

**Comment by eraclitux** [comment]
Thank you, with same version everything if fine even with me _but_ using `git version 2.11.0` shipped with `golang:latest` container I got:
```
git fetch --depth=1 https://github.com/aws/aws-sdk-go 1f8fb9d0919e5a58992207db9512a03f76ab0274
error: no such remote ref 1f8fb9d0919e5a58992207db9512a03f76ab0274
```
The ref exists and same command was working at least 5 days ago 🤔

**Comment by oiooj** [comment]
A release note from git [2.14.3](https://github.com/git/git/blob/master/Documentation/RelNotes/2.14.3.txt#L91):

```
   "git fetch <there> <src>:<dst>" allows an object name on the <src>
   side when the other side accepts such a request since Git v2.5, but
   the documentation was left stale.
```

**Comment by flibustenet** [comment]
on Debian Stretch 
```
$ git --version
git version 2.11.0
```
It was a good idea to remove the need of git !

**Comment by rsc** [comment]
I commented on the CL:

This is very incorrect. The form

    git fetch remote xxx:yyy

says fetch xxx from remote and give it the local name yyy.

If you omit xxx then you get the remote HEAD. 
So when you run

    git fetch remote :1234567890123456789012345678901234567890

that downloads the remote HEAD and then creates a local ref
for that commit named 1234567890123456789012345678901234567890,
no matter what its actual commit hash is.

Then if you try to use that name in a git command git will print
a warning like:

    warning: refname '1234567890123456789012345678901234567890' is ambiguous.
    Git normally never creates a ref that ends with 40 hex characters
    because it will be ignored when you just specify 40-hex. These refs
    may be created by mistake. For example,

      git checkout -b $br $(git rev-parse ...)

    where "$br" is somehow empty and a 40-hex ref is created. Please
    examine these refs and maybe delete them. Turn this message off by
    running "git config advice.objectNameWarning false"

Clearly this command is NOT what you want to use.
