### ISSUE TITLE
x/net/proxy: how to assert the underlying type from the returned value of Dialer.Dial

### ISSUE THREAD

**Issue by rhs** [golang/go#25104]
Something recent (it appears to be this commit: https://github.com/golang/net/commit/61147c48b25b599e5b561d2e9c4f3e1ef489ca41#diff-431387eb7262e1cfc79b125eb8a67c60) has broken the cast to *net.TCPConn. I don't know if this is intentional or not. If it is then I'd appreciate any advice on how to accomplish what I'm trying to do without the cast.

### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rhs/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rhs/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build051890453=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

This is slightly complicated to setup, so bear with me here. The reproducer program is available here: https://gist.github.com/rhs/7ed17d49dff7196c3539d2d1b01f6049

```
# the ssh will eat a terminal
ssh -D localhost:1080 -C -N -oExitOnForwardFailure=yes <host-you-have-ssh-access-to>

curl -o repro.go https://gist.githubusercontent.com/rhs/7ed17d49dff7196c3539d2d1b01f6049/raw/bacb83282856af91dc496b2864d0559c86371284/repro.go
# the go run will eat a terminal
go run repro.go

curl localhost:1234
```

### What did you expect to see?

Until recently this worked fine and connections were proxied:

```html
curl localhost:1234
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>No such app</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/no-such-app.html"></iframe>
	  </body>
	</html>
```

### What did you see instead?

Now the cast fails with a panic:

```
go run repro.go 
2018/04/26 08:34:59 Listening...
2018/04/26 08:35:03 CONNECTING: [::1]:45440 to 0xc4200102f0
panic: interface conversion: net.Conn is *socks.Conn, not *net.TCPConn

goroutine 5 [running]:
main.handleConnection(0xc42000e040)
	/home/rhs/repro.go:54 +0x2fa
created by main.main
	/home/rhs/repro.go:30 +0x16b
exit status 2
```

**Comment by mikioh** [comment]
> I don't know if this is intentional or not.

There's no guarantee that the returned interface always contains a specific concrete type, as the package description says that "for a variety of protocols." Otherwise, we cannot implement a bit complicated stuff like SOCKSv6 over TLS 1.3 in near future.

> how to accomplish what I'm trying to do without the cast.

A simple way would be using the 4th parameter of the SOCKS5 function like the following:
```
type sled struct { // or sledge
        tls *tls.Conn
        tcp *net.TCPConn
        udp *net.UDPConn
}

func (s *sled) Dial(network, address string) (net.Conn, error) { // satisfies proxy.Dialer interface
        switch network {
        case "tcp", "tcp4", "tcp6":
                c, err := net.Dial(network, address)
                if err != nil {
                        return nil, err
                }
                s.tcp = c.(*net.TCPConn)
                return c, nil
        }
        return nil, errors.New("not implemented yet")
}

var s sled
d, err := proxy.SOCKS5("tcp", "somewhere:1080", nil, &s)
if err != nil {
        // error handling
}
_, err = d.Dial(...)
if err != nil {
        // error handling
}
// Now you may use s.tcp safely.
```
PS: s/cast/type assertion/; the notation x.(T) is called a type assertion in the language specification. See https://golang.org/ref/spec#Type_assertions

**Comment by mikioh** [comment]
Also, it's fine to add both Close{Read,Write} methods to socks.Conn to allow to assert the behavior of close-read and -write, for example,
```
type closeReadWriter interface {
        CloseRead() error
        CloseWrite() error
}

c, err = d.Dial(...)
if err != nil {
        // error handling
}
if cc, ok := c.(closeReadWriter); ok {
        cc.CloseRead()
        cc.CloseWrite()
}
```
