### ISSUE TITLE
x/build: migrate off Kubernets buildlets back to VMs?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25108]
We've had a lot of flakiness with our Kubernetes-based buildlets. This seems to happen most during periods of high load, suggesting that we're still hitting isolation problems with Kubernetes, despite our various pod configuration knobs (requested CPU/mem + limit CPU/mem) being pretty paranoid and reviewed by various Kubernetes people.

Further, Kubernetes seems to get into a state where things are bad and then a cluster upgrade or nuke+recreate makes things good again.. for a bit.

I think it might be time to stop using Kubernetes for our buildlets (we'll still use them for all our misc services) and switch back to using VMs.

In the past, our Linux VMs were tedious because we had to prepare VM images for each config. We did this using a "docker2boot" tool I wrote that converted a container image (built from a Dockerfile) into a bootable GCE VM. But the whole process & testing was still slow & painful to iterate on.

When we moved to Kubernetes, we moved to more vanilla Dockerfiles with pushes & pulls to gcr.io. This was much less painful.

I don't propose we move back to custom VM images. I don't want to use docker2boot again (as cool of a hack as it was).

Instead, I think we should use GCE's container OS image (https://cloud.google.com/container-optimized-os/docs/) and use our existing buildlet containers.

The pros of moving to VMs:

* perfect isolation
* better scalability without fighting the managed instance group resizing
* faster scalability (new Kubelet nodes don't start up quickly).

The cons of moving to VMs:

* slower instance creation time. We'll have to wait 30-60 seconds for VMs to boot, which will be on par with all our other operating systems (all the BSDs, Mac, Windows, Plan 9, etc). But this will improve in the future as GCE continues to make VM boot-up faster. And this also wouldn't matter as much if we did #11107 which would benefit all builder types.
* more pulls from gcr.io, once per boot. But the network is ridiculous fast and we also aren't paying for it. But we can also reuse buildlets in the future to mitigate this.
* we have to write some code, but I think it's minimal.

I think this is worth trying. We can make it a flag and be able to revert easily. We don't delete the Kubernetes-based building code in case we want to switch back to it in the future.

/cc @andybons @FiloSottile

**Comment by andybons** [comment]
+1 for this. The flakiness of the builders under load was palpable and painful during the 1.10.1 release.

**Comment by bradfitz** [comment]
Note: after this is live, we'll probably want to remove the `IN_KUBERNETES` env from the image, and let those tests checking for it then try to test more.
