### ISSUE TITLE
cmd/compile: can not use statictmp_0 as variable name

### ISSUE THREAD

**Issue by aarzilli** [golang/go#25113]
### What version of Go are you using (`go version`)?

`go version go1.10.1 linux/amd64` and `go version devel +5f5168e Thu Apr 26 18:59:07 2018 +0000 linux/amd64`

### What did you do?

```
package main

var statictmp_0 string
var a []int

func init() {
	a = []int{ 7 }
}

func main() {
	println(a[0])
}
```

compiling this produces the error:

```
./teststatic.go:7:11: statictmp_0 redeclared in this block
	previous declaration at ./teststatic.go:3:5
```

**Comment by ianlancetaylor** [comment]
Also fails with Go 1.7 and 1.9.

**Comment by josharian** [comment]
I know compilers are supposed to implement the spec, but I have admit my first reaction to this is: “Then don’t do that.” Though I think the official way to spell that is: Low priority. :)

**Comment by agnivade** [comment]
Wow interesting. A shorter repro -

```go
package main

var statictmp_0 string

// Also fails with these
// type statictmp_0 struct{}
// type statictmp_0 interface{}

func main() {
	a := []int{7}
	println(a)
}
```

Also fails with structs and interfaces. Are there other reserved keywords like these ? 

Maybe good to document them in case this doesn't make it to 1.11.

**Comment by aarzilli** [comment]
@josharian: agreed. I only found this while looking at the symbols list in the linker.
