### ISSUE TITLE
x/net/internal/socket: "//go:linkname is only supported for functions" when using gccgo on solaris

### ISSUE THREAD

**Issue by ppbrown** [golang/go#25114]
go version go1.8.3 gccgo (GCC) 7.3.0 solaris/amd64

latest clone of x/net

errors follow:

# golang.org/x/net/internal/socket
internal/socket/sys_solaris.go:29:3: error: procGetsockopt is not a function; //go:linkname is only supported for functions
 //go:linkname procGetsockopt libc___xnet_getsockopt
   ^
internal/socket/sys_solaris.go:31:3: error: procRecvmsg is not a function; //go:linkname is only supported for functions
 //go:linkname procRecvmsg libc___xnet_recvmsg
   ^
internal/socket/sys_solaris.go:32:3: error: procSendmsg is not a function; //go:linkname is only supported for functions
 //go:linkname procSendmsg libc___xnet_sendmsg
   ^
internal/socket/sys_solaris.go:30:3: error: procSetsockopt is not a function; //go:linkname is only supported for functions
 //go:linkname procSetsockopt libc_setsockopt
   ^

**Comment by ppbrown** [comment]
This also stops x/net/ipv4 from compiling. Exact same errors.

**Comment by tklauser** [comment]
This should be fixed by https://golang.org/cl/366195
