### ISSUE TITLE
doc: "Go's New Brand" / Brand Book (pdf)

### ISSUE THREAD

**Issue by fgergo** [golang/go#25123]
Most probably it's a non-issue, though changing to Go proportionally-spaced font from Go monospaced on p19 in the Brand Book (pdf) might make the Brand Book more branded.
https://golang.org/s/brandbook

### What did you do?
Had a look at the pdf.

### What did you expect to see?
When I saw the Go font mentioned, I expected the text in proportionally-spaced font.

### What did you see instead?
Text in monospaced font.

**Comment by ianlancetaylor** [comment]
CC @spf13

**Comment by bcmills** [comment]
> why do you think gofmt assumes a monospaced font?

https://play.golang.org/p/449FGn_GKVu

**Comment by dsnet** [comment]
```go
type Foo struct {
	Short            io.ReadWriteCloser // comment
	LongLongLongLong int                // comment
}
```
When `gofmt` formatted this, it assumes monospacing for printable characters and whitespace.

**Comment by dsnet** [comment]
Although, the assumption breaks down with non-English characters, which tend not to be same length as space:
```go
type Foo struct {
	_               io.ReadWriteCloser // comment
	X敏捷的棕毛狐狸从懶狗身上跃过 int                // comment
}
```

**Comment by bcmills** [comment]
Fullwidth characters should be the same width as two spaces in a monospace font, although some browsers and platforms do not correctly align glyphs from fallback fonts for display (see https://crbug.com/807361 and  https://denisbider.blogspot.com/2015/09/when-monospace-fonts-arent-unicode.html), and a few characters have ambiguous widths.

If `gofmt` doesn't handle unambiguous fullwidth characters correctly, that's a separate bug we should file.

**Comment by bcmills** [comment]
But I'm pretty sure the `Go` font doesn't support any fullwidth characters anyway, so that problem is more-or-less moot when that font is involved.

**Comment by fgergo** [comment]
thanks!
It's funny, I just realised
1. for the last 8 years I've never needed to look at the first section of
golang.org/cmd/gofmt and
2. I've never cared for alignment, when grouping was rarely needed, I've
always grouped with explicitly descriptive names+descriptions.

**Comment by as** [comment]
I've gone back and forth, eventually settling on the proportional one. The `gofmt` has never even been a consideration for the decision--it seems to do its job well regardless.

Most people I've asked find `gomedium` most visually-appealing.

**Comment by spf13** [comment]
As the usage of the Go font is intended for source code and the monospaced version of the font is designed for source code we believe the brand book is correct in using the monospaced one.
