### ISSUE TITLE
x/sys/unix: expose signal and errno names as strings

### ISSUE THREAD

**Issue by AlekSi** [golang/go#25134]
[Currently](https://github.com/golang/sys/blob/cbbc999da32df943dac6cd71eb3ee39e1d7838b9/unix/zerrors_linux_amd64.go), signal and errno names are represented by the following generated Go code (abbreviated):
```go
const (
  SIGINT = syscall.Signal(0x2)
)

const (
  EAGAIN = syscall.Errno(0xb)
)

var signals = [...]string{
  2: "interrupt",
}

var errors = [...]string{
  11: "resource temporarily unavailable",
}
```
There is no way to get back signal or errno name (`SIGINT` and `EAGAIN`) from the number for, for example, nice logging messages.

I propose to expose them via two functions:
```go
func SignalName(s syscall.Signal) string { }
func ErrnoName(e syscall.Errno) string { }
```

That's something that annoyed me for years, but I finally decided to create an issue.

**Comment by tklauser** [comment]
Sounds fine to me. It would be nice if we had `unix.Errno` and `unix.Signal` types (not sure why these were not converted in the initial `x/sys` package split). We could then even have

```go
func (s Signal) Name() string { ... }
func (e Errno) Name() string {... }
```

@ianlancetaylor @bradfitz what do you think?

**Comment by ianlancetaylor** [comment]
I think we would still want `SignalName` and `ErrnoName`, for use with the standard library.  It seems a little confusing to require people to convert to `unix.Signal` or `unix.Errno`.

**Comment by kolyshkin** [comment]
@tklauser it seems that `zerrors_linux_sparc64.go` is not converted to the new format.

**Comment by tklauser** [comment]
@kolyshkin uh, I forgot to change it there because `linux/sparc64`is not integrated with the Docker-based build system. I sent https://golang.org/cl/139977 to fix it. Thanks.
