### ISSUE TITLE
Brand Book: Instead of the RGB color code for Pantone 669 C, the Fuchsia code is listed

### ISSUE THREAD

**Issue by bvanrijn** [golang/go#25136]
### What did you do?

I took a look at the Go [Brand Book](https://storage.googleapis.com/golang-assets/go-brand-book-v1.0.pdf) and saw an incorrect color code on page 16.

### What did you expect to see?

Under color [Pantone 669 C](https://www.pantone.com/color-finder/669-C) (under the "More colors" section on page 16), I expected to see the correct RGB color code, which is `63, 42, 86`.

### What did you see instead?

Instead, I saw the RGB code `200, 50, 98` listed underneath, which is the RGB code for Fuchsia.

**Comment by bcmills** [comment]
CC: @spf13

**Comment by spf13** [comment]
Thank you. We will fix this and republish.

**Comment by RalphCorderoy** [comment]
This area got mentioned on golang-dev about a week ago.  https://groups.google.com/d/msg/golang-dev/65ygkAOc9MM/C8lO5oR-AwAJ 
There, the issue was that the decimal and hex RGB amounts don't match on many of the pairings.
