### ISSUE TITLE
Using dashes in variables doesn't strip newlines (text/template package)

### ISSUE THREAD

**Issue by JordanKnott** [golang/go#25135]
### What version of Go are you using (`go version`)?
1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
``` bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nightwolf/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nightwolf/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build254649512=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?

Example program that shows the issue

The first data set contains no newlines and the second one does. The output should be the same for
both since the dashes should strip the newlines.

``` golang
package main

import (
“os”
“text/template”
“fmt”
)

type Data struct {
Content string
}

func main() {
validData := Data{“highlight: true”}

brokenData := Data{"\nhighlight: true"}

tmpl, err := template.New("test").Parse("{{- .Content -}}")
if err != nil { panic(err) }

fmt.Printf("Doesn't contain a new line\n")
err = tmpl.Execute(os.Stdout, validData)
if err != nil { panic(err) }

fmt.Printf("\nContains a new line but should be removed\n")
err = tmpl.Execute(os.Stdout, brokenData)
if err != nil { panic(err) }
}
```

### What did you expect to see?

Newlines should be stripped

### What did you see instead?

They are not stripped.

**Comment by bcmills** [comment]
Please use Playground links for runnable examples to ensure that they compile and run (and to make them easier to modify).
https://play.golang.org/p/LCG0tv2wdeH

**Comment by bcmills** [comment]
This seems to be working as documented. The `{{-` and `-}}` tokens strip preceding and following whitespace, not whitespace within the content itself. The intent is to allow the use of multi-line templates without introducing extraneous whitespace in the output, but for the content actually passed to the template you can do that preprocessing yourself.

And you can always inject `strings.TrimSpace` to do that explicitly within the template:
https://play.golang.org/p/7TaVb6eZjOm

**Comment by JordanKnott** [comment]
Hmmm, that behavior seems strange to me. Oh well, I'll just do something `strings.TrimSpace`
