### ISSUE TITLE
failure: go get -u golang.org/x/vgo

### ISSUE THREAD

**Issue by harkamals** [golang/go#25147]
### What version of Go are you using (`go version`)?
1.9.5

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64, mac os

### What did you do?
go get -u golang.org/x/vgo

### What did you expect to see?
vgo downloaded and installed

### What did you see instead?
go get -u golang.org/x/vgo
# golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo
/Users/hk/go/src/golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo/fetch.go:404:21: r.File[0].Modified undefined (type *zip.File has no field or method Modified)

**Comment by vic3lord** [comment]
vgo is supported with >= go 1.10

**Comment by ALTree** [comment]
> vgo is supported with >= go 1.10

^this.

Closing here, since 1.9 is not vgo-compatible.
