### ISSUE TITLE
Function request: built-in sleep function in http.HandleFunc

### ISSUE THREAD

**Issue by AnikHasibul** [golang/go#25144]
Is there any native support for disabling http.HandleFunc for a while in runtime?

For simulating this i have to do something like this:

```go
var ServerIsHealthy bool
func Index(w http.ResponseWriter, r *http.Request) {
    if ServerIsHealthy {
        fmt.Fprintln(w,"welcome")
    }
    // don't reply the user. I am on ddos or whatever! but i am cool
    return
}
// functions to make ServerIsHealthy true or false
```

it can be done with sync/atomic but is there any native way to do this like:

```go
for {
if fileReadErr != nil {
   http.CloseAllHandlers()
} else {
   http.OpenAllHandlers()
}
}
```

**Comment by davecheney** [comment]
The sample you have provided almost certainly contains a data race.  Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

Closing as there is nothing actionable in this issue.
