### ISSUE TITLE
go/types: erroneously accepts recursive type aliases

### ISSUE THREAD

**Issue by mdempsky** [golang/go#25141]
[18130-type-alias](https://github.com/golang/proposal/blob/master/design/18130-type-alias.md) explicitly states that `type T = *T` is invalid, but go/types accepts it:

    $ cat v.go
    package p
    type T = *T
    $ gotype v.go
    $ echo $?
    0

cmd/compile does not.

Notably though, I don't see any wording in the text actually added to the Go spec that precludes this.

/cc @griesemer

**Comment by mdempsky** [comment]
Tangentially, I'm questioning what the fundamental difference (if any) is between `type T = *T` and `type U interface { F() interface { U } }`. Why disallow one, but allow the other?

We sorta support the latter, but it's sketchy and a recurring thorn. I think if we properly fix support for it, it would make supporting the former trivial. But maybe it's just better to disallow both.

**Comment by go101** [comment]
Looks the difference is whether or not the declaration is an alias declaration.
 `type U = interface { F() interface { U } }` is also denied by gc, but `type T *T` is also accepted by gc.

**Comment by griesemer** [comment]
Somewhat related: https://github.com/golang/go/issues/23139 .

go/types has issues with detecting certain cycles. I hope to address this for 1.11.

Per the original type-alias design doc from @rsc, it must be possible to "expand out" type alias declarations; this wouldn't be possible for `type T = *T` without expanding endlessly. You are correct that the spec doesn't state that, though. I filed #25187.

I think it would be nice to accept all these, but our depth-first based type-checking approaches have troubles with them; and ad-hoc approaches tend to be incorrect. We need to either disallow these cases or have a sound way to describe what we allow and what we don't, and also a (understood and correct) way of type-checking them w/o incurring undue cost.

At the same time, these are probably not urgent.
