### ISSUE TITLE
security: consideration for compiled binary - it is possible to discover which packages were used to build binary

### ISSUE THREAD

**Issue by akamensky** [golang/go#25159]
### What version of Go are you using (`go version`)?
`go version go1.10 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```GOARCH="amd64"
GOBIN=""
GOCACHE="..."
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="..."
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j6/vhm757px2zz3jgvxy1w3gfzr0000gn/T/go-build752488733=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
```
go get -u github.com/viktomas/godu
cd ~/go/bin
strings godu
```

### What did you expect to see?
Minimal output of strings that are explicitly used in application

### What did you see instead?
Rather comprehensive list of every single package used for this application (direct dependencies and dependencies of dependencies etc) as well as structs definitions, variable names etc. The information still in place even if I use `-ldflags '-w'` which suppose to skip any debugging information as far as I know.

I consider this a security issue since this will leak information about any private packages used, where they located and point any would be attacker to where he need to look to obtain any proprietary code or even to self-hosted repositories etc. Structs and variables will assist in reverse engineering etc etc.

Not very clear why upon compilation these need to be kept as strings within binary.

**Comment by akamensky** [comment]
@dpinela 1st - for obvious reasons I cannot provide here an example of proprietary software to show that sensitive information IS being leaked. 2 - the security by obscurity is a widely used excuse for not doing security check. The application that is deployed to users desktop should not leak sensitive information. If you compile this godu on your personal computer for example and give for anyone to download people will at the very least see your username on your computer and other information that shouldn’t be there. Or if it is there - at least not in such obvious form as plain strings. Go is not the only language that has reflection. But somehow other ones don’t store this information in such easily recoverable form. That’s my whole point about this - even if this info needs to be there, then why strings? As if that is most optimal way of storing information that anyone have ever come up with

**Comment by dlsniper** [comment]
I too don't see what's the issue with these things:

- computer username is in plaintext: someone will now know your build machine has that username and nothing else. Not where it's located, not how to get to it, nothing of sorts.
- private repository import path is in plaintext: if you use github and the repository is private, they can't get to it anyway. If you host your own git solution, people will know the URL for it. Assuming this is not some webserver that's just opened to the internet without any authentication, again, no problem at all
- package/variable/identifiers names will be in plaintext: this would help people to figure out how to reverse engineer your custom protections quicker than normal, but it will only speed up a process, not make it possible.

The last one is the most "offensive" one of the three, clearly. But it would help to get in the mind-frame of someone who actually wants to target you and see what they could actually do with that information and how would they achieve the same thing if that information would not be present.

You can use something like [UPX](https://upx.github.io) as the majority of people will give up on seeing it. The more determined ones won't be stopped. Here's an example of [Denuvo](https://www.denuvo.com), a copy-protection system which is considered state of art in this field but was reverse engineered and bypassed in just 19 days by some very determined people, https://crackwatch.com/game/far-cry-5 (link does not contain illegal content).

**Comment by randall77** [comment]
If you build with `go build -gcflags="-trimpath=/home/username/foo"`, then that prefix in the filename paths in your application will be removed.
You can use that to fix one of your points.
Note that if you build your Go installation from source, you might also have to do something with the stdlib (GOROOT_FINAL env var to make.bash, I think).

**Comment by as** [comment]
It seems your definition of security is privacy within the context of your username and project structure on disk. The solution to this problem is to build the software on a machine containing no personal information. 

Even if you strip the path information, it is possible to deduce with certainty what third party packages you are using in the binary. This is true for almost any binary executable containing constants.

You can try to strip the symbol table from the binary--I don't know if Go supports that--but I vaguely remember people talking about it here with some success.

**Comment by andybons** [comment]
@FiloSottile

**Comment by FiloSottile** [comment]
Thanks for your report. Embedding file paths is an explicit trade-off to improve debug capabilities and tracebacks. Variable, function and package names are unavoidable for reflection to work. So removing them is not an option.

As for the format, Go is not going to add complexity to try and make it slightly harder to extract information that will have to be there anyway. There are tools for that, obfuscators, and we would have no chance of doing as good a job as a dedicated tool.
