### ISSUE TITLE
crypto/tls/generate_cert.go: Organization name and file names

### ISSUE THREAD

**Issue by gertcuykens** [golang/go#25157]
https://golang.org/src/crypto/tls/generate_cert.go
Can we have 3 more flags please for
```
Organization: []string{"Acme Co"},
"cert.pem"
"key.pem"
```
It will be more flexible for building scripts that can then use it directly instead of modifying a copy of that file.

**Comment by AlekSi** [comment]
What is your use case?
I _think_ this file is intended to be used only for Go testing, not by Go users.

**Comment by gertcuykens** [comment]
Can be made backward compatibel by using does entries above as default. My use case is to generate certificates for testing grpc services. Where organisation need to be localhost or a specific company name, and file names tls.key, tls.crt. I can copy this file and modify it but I think this go file can fill in plenty of test cases if does 3 fields have flags too.

**Comment by gertcuykens** [comment]
Still think it helps promote the use of tls more if you make it easier for user to generate certificates without the need of copying or use a third party repo. Also if for some reason a security bug is found in that code which is highly unlikely I know but i gives a fail safe for the users to get fixed immediately.

**Comment by FiloSottile** [comment]
`generate_cert.go` is not meant to be a production or full-featured tool, which is why it's not a stand-alone binary. I do agree the ecosystem needs a better way to generate certificates and manage a local CA than `openssl`, but that will not come by just expanding `generate_cert.go`.
