### ISSUE TITLE
-buildmode=c-shared not supported on windows/amd64

### ISSUE THREAD

**Issue by daoqiang** [golang/go#25155]
Please answer these questions before submitting your issue. Thanks!

-buildmode=c-shared not supported on windows/amd64
### What version of Go are you using (`go version`)?
go version go1.9.3 windows

**Comment by AlexRouSg** [comment]
Support was added in go 1.10 please update your go install

**Comment by daoqiang** [comment]
Wow, it's very cool.I see an example of golang generating a local binary file by introducing a "net" package, and then when c++ calls the DLL, it also needs to introduce a header file, which can not generate the same DLL as c++ with go, and do not need to introduce such types as "GoString" and so on.

**Comment by AlekSi** [comment]
You may want to set environment variable `CGO_ENABLED` to `0` to avoid C dependency:
* https://golang.org/cmd/cgo/
* https://golang.org/pkg/net/#hdr-Name_Resolution

Also, note that issue tracker is not for questions: https://github.com/golang/go/wiki/Questions.

**Comment by ALTree** [comment]
What AlekSi said. My suggestion is to ask for guidance in one of the places linked above. If it turns out this is a Go bug, comment here and we'll reopen.
