### ISSUE TITLE
cmd/gofmt: format regression

### ISSUE THREAD

**Issue by dvyukov** [golang/go#25161]
Here is snippet of code:

```go
package foo

var linuxOopses = []*oops{
	&oops{
		[]*regexp.Regexp{
			compile("INFO: lockdep is turned off"),
			compile("INFO: Stall ended before state dump start"),
			compile("INFO: NMI handler .* took too long to run"),
			compile("_INFO::"),                                       // Android can print this during boot.
			compile("INFO: sys_.* is not present in /proc/kallsyms"), // pkg/host output in debug mode
			compile("INFO: no syscalls can create resource"),         // pkg/host output in debug mode
		},
	},
}
```

With 1.10 formatting produces no diff, however with tip I am getting diff:

```
$ gofmt -d /tmp/format.go
diff -u /tmp/format.go.orig /tmp/format.go
--- /tmp/format.go.orig	2018-04-29 12:01:23.844573882 +0200
+++ /tmp/format.go	2018-04-29 12:01:23.844573882 +0200
@@ -6,7 +6,7 @@
 			compile("INFO: lockdep is turned off"),
 			compile("INFO: Stall ended before state dump start"),
 			compile("INFO: NMI handler .* took too long to run"),
-			compile("_INFO::"),                                       // Android can print this during boot.
+			compile("_INFO::"), // Android can print this during boot.
 			compile("INFO: sys_.* is not present in /proc/kallsyms"), // pkg/host output in debug mode
 			compile("INFO: no syscalls can create resource"),         // pkg/host output in debug mode
 		},
```

This breaks our CI.

go version devel +e0d37a33ab Sun Apr 29 09:38:32 2018 +0000 linux/amd64

**Comment by dvyukov** [comment]
To clarify the problem: we have several Go versions on CI and users using a mix of Go versions. CI checks that all code is formatted.

**Comment by agnivade** [comment]
bisected to https://github.com/golang/go/commit/542ea5ad91367d2b40589942cc5757a4d5f43f97

**Comment by jimmyfrasche** [comment]
@dvyukov see also the discussion in #22695

**Comment by griesemer** [comment]
Specific to this example: The "_INFO::" entry is just one char below the threshold. If it were "__INFO::" (for instance), the comment would be aligned. I'm not saying you should change it; but there's a threshold and this code simply is below (or above) it. This is simply "unfortunate" in this case.

Regarding the layout algorithm: It could be better, and perhaps in the future we will have a better approach (which is also why we don't want to freeze gofmt). We could trivially change the threshold but that simply moves the problem from this example to another example.

More generally: We do not want to freeze gofmt. See https://github.com/golang/go/issues/22695#issuecomment-344483632 .

I'm going to close this as "unfortunate".
