### ISSUE TITLE
cmd/go: go build -msan passes invalid option to GCC

### ISSUE THREAD

**Issue by daenney** [golang/go#25175]
### What version of Go are you using (`go version`)?
- 1.9.5
- 1.10.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux, amd64

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

### What did you do?
- Cloned a project that uses CGO, prometheus/node_exporter
- Attempted to build with `go build -msan`

### What did you expect to see?
One of:
- The build proceeding as normal
- The build outputting a user friendly error message notifying that `-msan` does not work with GCC (because GCC doesn't support `-fsanitize=memory`)

### What did you see instead?
```
# runtime/cgo
gcc: error: unrecognized argument to -fsanitize= option: 'memory'
```

Though `go env` correctly detected `CC=gcc` and `CXX=g++` it seems `go build` indiscriminately passes `-fsantize=memory` to the C compiler when calling `go build` with `-msan`. This should not be the case, as `-fsanitize=memory` is only available when using clang. Instead it should warn the invoker of `go build` about this with a friendly error message when `go env CC` is `gcc`.

The simple fix in this case was to `env CC=clang env CXX=clang++ go build -msan`.

```
$ gcc --version
gcc (GCC) 7.3.1 20180406
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

MemorySaniziter is only supported on Linux with amd64, arm64 and mips64 according to the LLVM documentation, which might be worth checking for too (at least `GOOS=linux` seems like a pretty safe check)

**Comment by andybons** [comment]
@ianlancetaylor @bcmills

**Comment by ianlancetaylor** [comment]
We should not ignore the `-msan` option with a compiler that does not support `-fsanitize=memory`, so it seems to me that all we are discussing is the possibility of a better error message.

What is your suggested fix?  Although current versions of GCC does not support `-fsanitize=memory`, later versions may support it.  Although current versions of clang only support `-fsanitize=memory` on amd64, arm64, mips64, and only on GNU/Linux, later versions of clang may support it on other targets.

**Comment by daenney** [comment]
I'm not quite sure what a good solution is here. It's indeed possible that in newer releases these features will be supported. Do GCC/clang have any facilities that would allow to check whether a specific option is supported for an argument?

Alternatively, is there a way we can wrap the error in this case with some more context? I don't think pattern matching on the error itself would be a very stable solution, but given that we know `-msan` can cause execution to fail, maybe it's enough to include that in the error message as a pointer to what might be the cause?

**Comment by bcmills** [comment]
@daenney, we do probe for a working sanitizer in some of the cgo tests today, but the check is somewhat involved and also adds latency to the test. (Also consider that it's possible for the compiler to accept `-fsanitize=memory` but fail to produce a working binary anyway, particularly if the result is linked against a different `libc`.)

https://github.com/golang/go/blob/7f6105f138b3836e9ad85b8da26d44c742bf217b/misc/cgo/testsanitizers/cc_test.go#L315-L353

**Comment by bcmills** [comment]
> I'm also fine with leaving it as is.

Since nobody has gotten to it since 1.10.1, I suspect that no one will in the near future; closing.
