### ISSUE TITLE
x/crypto/ssh/agent: non-constant time passphrase check

### ISSUE THREAD

**Issue by weingart** [golang/go#25173]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.1

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Look at: https://github.com/golang/crypto/blob/master/ssh/agent/keyring.go#L105

### What did you expect to see?
A comparison that was constant time.

### What did you see instead?
A comparison that could be used to divine the length of the passphrase.

### How to fix?
Use a constant time comparison, without a length check short-circuit.

Other option:
Stored a hashed via bcrypt (or similar) version of the passphrase instead.  The comparison
should then also hash the attempted passphrase and use a constant time compare (which the
hash would pretty much guarantee).  Note, this could make the implementation also more safe
from casual memory snooping.

**Comment by ALTree** [comment]
> Use a constant time comparison, without a length check short-circuit

I don't think it's possible to constant-time compare two arrays of different lengths.

cc @agl @FiloSottile to decide if this issue is actionable.

**Comment by as** [comment]
@weingart 

It's true that hashing the passphrase will create a bitstring comparable in constant time, but the suggestion of bcrypt sounds rather expensive. Is there a particular reason you would choose this function over another?

>Note, this could make the implementation also more safe
from casual memory snooping.

I would prefer to step away from such corollaries, it creates one more location in memory associated with the passphrase.

**Comment by nsajko** [comment]
> I don't think it's possible to constant-time compare two arrays of different lengths.
Would something like [0], but written in Go assembly, not be constant-time? It is supposed to be constant time with respect to length of *one* string (the attacker controlled one).
[0] https://nachtimwald.com/2017/04/02/constant-time-string-comparison-in-c/

**Comment by hanwen** [comment]
the bug here is that we're checking the lengths at all, as ConstantTimeCompare already does so

https://golang.org/src/crypto/subtle/constant_time.go?s=501:542#L2

see also https://go.googlesource.com/go/+/446bfffcd6cfcaca141988a9d844aac61a704866 and issue 
https://github.com/golang/go/issues/7304 (which coincidentally, I filed.)

**Comment by hanwen** [comment]
I've submitted the aforementioned change.

I don't think there is anything left to be done here.

**Comment by nsajko** [comment]
But the submitted fix does not address the issue: that comparing two strings of different lengths takes less time than comparing two strings of equal length. Can the code I linked to not address the issue?

**Comment by hanwen** [comment]
strings in Go are not null terminated, so the code you link to can't work.

you could make subtle.ConstantTimeCompare constant time for differently sized input strings, eg. by doing

```
l :=  len(x) - len(y)
var bs [4]byte
binary.PutInt(l, b[:])
byte v = bs[0] | bs[1] | bs[2] | bs[3]
for i := 0; i < len(x) && i < len(y); i++ {
  v |= x[i]^y[i]
}
```

but it will still leak the size of the smallest array, and it takes work to do this portably.

**Comment by josharian** [comment]
I am not a cryptographer, but it seems to me that the linked code could be ported straightforwardly to Go by replacing "byte is NULL" by "current index >= length of string".

**Comment by nsajko** [comment]
> I am not a cryptographer, but it seems to me that the linked code could be ported straightforwardly to Go by replacing "byte is NULL" by "current index >= length of string".

It is not that simple, just doing that would result in a read out of slice bounds in the first line of the loop.
