### ISSUE TITLE
x/mobile: Android example doesn't work in Android Studio

### ISSUE THREAD

**Issue by renatoathaydes** [golang/go#25184]
### What version of Go are you using (`go version`)?

`go version go1.10.1 darwin/amd64`

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/renato/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/renato/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vz/dnr6kc0d4z76tk0mjxdbswxh0000gp/T/go-build312264261=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

1. Checkout the [gomobile](https://github.com/golang/mobile) project.
2. Open the [example/bind/android](https://github.com/golang/mobile/tree/master/example/bind/android) project with Android Studio (latest version: 3.1.2) as instructed in the README.

### What did you expect to see?

The project should "Gradle sync" successfully when opened in Android Studio.
Furthermore, when editing the Android `MainActivity.java`, under the `app` dir, in Android Studio, the Go package-exported Java bindings (`import hello.Hello;`) should be reachable.

### What did you see instead?

Android Studio's sync failed with:

```
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
```

The package `hello` is not visible from the Java code in `MainActivity.java`.

**Comment by renatoathaydes** [comment]
Strangely, the build succeeds:

![image](https://user-images.githubusercontent.com/1901277/39441846-8aa5dd0c-4caf-11e8-8157-48ba3c5a3caf.png)

Only the sync fails:

![image](https://user-images.githubusercontent.com/1901277/39441852-9be20ab4-4caf-11e8-9007-4a56e7a0ab90.png)

Is this something I should report to Android Studio?

**Comment by sisyphsu** [comment]
meet same issue...

**Comment by golangwrt** [comment]
I found a temporary walk-around in my environment, use plugin 'com.android.tools.build:gradle:2.3.2' instead of "3.x.x" in build.gradle of top directory,  then, change the 'implementation' to 'compile' in app/build.gradle would work.

**Comment by wseternal** [comment]
I found a temporary walk-around in my environment, use plugin 'com.android.tools.build:gradle:2.3.2' instead of "3.x.x" in build.gradle of top directory, then, change the 'implementation' to 'compile' in app/build.gradle would work.
