### ISSUE TITLE
cmd/compile: throw instead of panic in runtime

### ISSUE THREAD

**Issue by josharian** [golang/go#25201]
For discussion; I don't know whether this is a good idea.

The runtime uses slices. Though the runtime contributors Never Make Mistakes, slice accesses can panic. Most such panics are very bad news. However, they might be caught by another package's recover. That's why we have throw.

We might want to have the compiler automatically insert throwindex instead of panicindex, throwslice instead of panicslice, etc. when compiling the runtime.

cc @aclements @randall77

**Comment by randall77** [comment]
So the only way to get a panicindex in the runtime is with an explicit panic call?
Seems reasonable.  I do worry about the slow buildup of more and more special cases in the compiler for runtime package, though.

**Comment by odeke-em** [comment]
@josharian sorry if am preaching to the choir but won't this technically violate the spec https://golang.org/ref/spec#Run_time_panics which requires panics with runtime.Error for slice access issues?

**Comment by josharian** [comment]
> won't this technically violate the spec 

I don't think so. That's for observable panics. These "panics" are failures of the language implementation, and this change just makes sure that those take down the process rather than letting it continue in a broken state.

**Comment by josharian** [comment]
Not going to do this. See the discussion in the CL.
