### ISSUE TITLE
access: may-start-trybots

### ISSUE THREAD

**Issue by meirf** [golang/go#25209]
I have a bit of code and commentary history in this project. I think it would be useful for reviewers (and myself) if I could catch issues on some builders before my reviewers and save them time. For example on https://go-review.googlesource.com/c/net/+/85577.

Code: https://go-review.googlesource.com/q/owner:meirfischer%2540gmail.com
Commentary: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Ameirf

Email: meirfischer@gmail.com
Group: https://go-review.googlesource.com/#/admin/groups/1030,members

**Comment by andybons** [comment]
Done
