### ISSUE TITLE
release: Windows installer has scary prompt

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25202]
I installed Go 1.10.1 on a Windows 10 machine, and a few clicks into the MSI installer, I get this prompt:

![msi](https://user-images.githubusercontent.com/2621/39482295-59afe214-4d23-11e8-81a3-5bf641cc17c3.jpg)

What is "429812a4.msi" ?

Can we make that string something less sketchy looking?

/cc @andybons @alexbrainman

**Comment by ancaemanuel** [comment]
I want to add that if you go to https://golang.org there is no link to an "download" or install section.
You need to search for google.com/search?q=golang+download to get to https://golang.org/dl

If you search for "golang one line downloader official"
first link is: https://golang.org/doc/install which point to the above link for install.
There is an proposal for a tool like rustup https://github.com/golang/go/issues/23320

**Comment by ancaemanuel** [comment]
First time used go, it was from the tutorial on the website.
I compiled go on my machine and this is my love after pascal.
But not everybody are ready to compile from source. Some want to click and install it.
And if you manage that, is not enough. Somebody new need an IDE, F1 to work for help from context, etc.

**Comment by agnivade** [comment]
> I want to add that if you go to https://golang.org there is no link to an "download" or install section.

There is a big "Download Go" button on the page.

Let us keep the discussion on the actual issue and not add extra noise.

**Comment by fgergo** [comment]
@bradfitz I believe it's this:
https://stackoverflow.com/questions/6863137/odd-program-name-when-installing-signed-msi-installer

I could not find where signing is done in github.com/golang, maybe it's done somewhere else?
(wix isn't doing it in github.com/golang/build/tree/master/cmd/release/releaselet.go )

This should work:
c:\>signtool.exe /d "Your Software Name"

**Comment by alexbrainman** [comment]
> I believe it's this:
> https://stackoverflow.com/questions/6863137/odd-program-name-when-installing-signed-msi-installer

Looks very similar, indeed. Thank you.

> I could not find where signing is done in github.com/golang, maybe it's done somewhere else?
> (wix isn't doing it in github.com/golang/build/tree/master/cmd/release/releaselet.go )

Same. I could not find signing code. I suspect it is done manually.

> This should work:
> c:>signtool.exe /d "Your Software Name"

Maybe @bradfitz or @andybons can help.

Alex

**Comment by fgergo** [comment]
@bradfitz @andybons Do you need anything else?

**Comment by andybons** [comment]
OK. In future releases we will have a non-shady-looking install prompt:
![249ad22f-ce1c-4a31-bddb-2d0957431762](https://user-images.githubusercontent.com/365204/43555264-2bbbbc06-95c7-11e8-8dd9-0ddeda39f96d.jpeg)
