### ISSUE TITLE
syscall: be more helpful with Windows DLLs fail to load due to missing environment variables

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25210]
I've been trying to get the Perkeep tests passing on Windows and just hit this flake with Go 1.10 that I've never seen before or found other reports of:

```
C:\Users\brad\go\src\perkeep.org>go test  ./pkg/test/integration
2018/05/01 20:47:44 Running make.go to build perkeep binaries for testing...
2018/05/01 20:47:47 Ran make.go.
2018/05/01 20:47:48 Running make.go to build perkeep binaries for testing...
2018/05/01 20:47:52 Ran make.go.
panic: CryptAcquireContext: Provider DLL failed to initialize correctly.

goroutine 1 [running]:
mime/multipart.randomBoundary(0x70, 0x9466a0)
        C:/Go/src/mime/multipart/writer.go:82 +0x147
mime/multipart.NewWriter(0xa4f2e0, 0xc04218c7e0, 0x30)
        C:/Go/src/mime/multipart/writer.go:30 +0x2d
perkeep.org/pkg/client.calculateMultipartOverhead(0x9c4770)
        C:/Users/brad/go/src/perkeep.org/pkg/client/upload.go:96 +0x52
--- FAIL: TestAndroidCamputFile (0.07s)
        camlistore_test.go:266: pk-put exited uncleanly: exit status 2
--- FAIL: TestCamputUploadOnce (0.19s)
        camput_test.go:125: wrong pk-put output; wanted sha1-381c42a63078ef49a2f1808318dbbafbb31a81d5, got sha1-68374998520d18899df837f7541d890fdf40d799
FAIL
FAIL    perkeep.org/pkg/test/integration        19.078s

C:\Users\brad\go\src\perkeep.org>go version
go version go1.10.1 windows/amd64
```

Any ideas?

/cc @alexbrainman

**Comment by bradfitz** [comment]
Actually, I'm hitting this reliably with Windows 10, Go 1.10.1, and Perkeep git rev https://camlistore.googlesource.com/camlistore/+/b9ab98d60de97f2e78913aecb587dd6013189eaa

**Comment by bradfitz** [comment]
Notably, that `calculateMultipartOverhead` runs at init time.

Is one not allowed to use crypto/rand on Windows at init time?

**Comment by bradfitz** [comment]
Ah, we had a child process that was being run in an integration test with an incomplete environment.

I discovered it because after I worked around this issue (by calculating the `calculateMultipartOverhead` lazily on first use with a `sync.Once` instead of at `init` time), then my test started failing with different but related errors about network initialization.

Could we repurpose this bug about making such Windows debugging adventures easier?

Can we log or return a better error somewhere when a DLL fails to load and we additionally have missing environment variables?

(sorry for talking to myself)

**Comment by alexbrainman** [comment]
> Can we log or return a better error somewhere when a DLL fails to load and we additionally have missing environment variables?

I suppose the problem here is that syscall.CryptAcquireContext requires some environment variable set. We could find out what it needs and then check syscall.CryptAcquireContext error number, and if error number matches and that particular environment variable set, we could return different error message. I am just not sure, if that would be OK to change error message returned, because other people could be expecting that error.

But really - passing nearly empty environment to you child process on Windows is looking for trouble. I wish our API would stop us doing that.

Alex

**Comment by bradfitz** [comment]
> But really - passing nearly empty environment to you child process on Windows is looking for trouble. I wish our API would stop us doing that.

Yeah, that's another possibility: on Windows we could force certain environment variables to be inherited in os/exec. Perhaps if they're not mentioned at all, we auto-add them, but if the user *really, really* wants to run the child process with an empty environment key, they can set it to the empty string?

**Comment by alexbrainman** [comment]
Perhaps it has been discussed before, but why does `os.Environ()` returns `[]string` ? Shouldn't it return `map[string]string` ? `map[string]string` would work on Unix. Unfortunately Windows does not distinguish between `PATH` and `path` environment variables, so `map[string]string` is not good for Windows.

Alex

**Comment by bradfitz** [comment]
@alexbrainman, let's leave such discussion to newly-opened https://github.com/golang/go/issues/25252

**Comment by rsc** [comment]
I don't think we should do anything in syscall but I think it would be appropriate for os/exec to take care of this and say that unless SYSTEMROOT (or SystemRoot, systemroot, etc) is specified explicitly on Windows, it's copied in implicitly.

**Comment by alexbrainman** [comment]
> I think it would be appropriate for os/exec to take care of this and say that unless SYSTEMROOT .... is specified explicitly on Windows, it's copied in implicitly.

Too much magic for me. If I don't include SYSTEMROOT in my environment, I expect os/exec not to put it there.

Also how do you know that SYSTEMROOT is what is missing to fix your failure? What about other environment variables? Different libs / packages installed on my computer adds different environment variables. How are you going to support these libs / packages?

I think it is much simpler, when creating child process, just copy parent environment and add / remove / modify whatever environment variables you like.

Alex

**Comment by bradfitz** [comment]
os/exec is a high-level helper package. It's quite common for people to forget to copy the parent environment, so I think it's fine to auto-add critical environment variables that aren't mentioned explicitly.

> Also how do you know that SYSTEMROOT is what is missing to fix your failure? What about other environment variables? Different libs / packages installed on my computer adds different environment variables. How are you going to support these libs / packages?

So far it's been implicated several times now. I think fixing the common ones is enough. We don't have to do all of them.

> I think it is much simpler, when creating child process, just copy parent environment and add / remove / modify whatever environment variables you like.

In retrospect that should've been the API from the beginning (a list of modifications, rather than the new environment completely), but that's not where we're at.
