### ISSUE TITLE
x/tools/imports: use /x/ import path for context

### ISSUE THREAD

**Issue by tbpg** [golang/go#25226]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.6.4 linux/amd64

### Does this issue reproduce with the latest release?
No.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/$USER/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

```
$ go get -u golang.org/x/tools/imports
package context: unrecognized import path "context" (import path does not begin with hostname)
```

### What did you expect to see?
No errors.

### What did you see instead?
An error.

Caused by https://go-review.googlesource.com/c/tools/+/109156. CL coming up.

**Comment by dominikh** [comment]
Go 1.6 is super old and no longer supported. Packages in the /x/ repos usually build with the current and previous version of Go.

**Comment by bradfitz** [comment]
Yeah, sorry, we no longer support Go 1.6, except in some rare cases for App Engine users, and even that support won't last much longer. And this tool doesn't apply to App Engine.
