### ISSUE TITLE
golang repo is down at googlesource from golang.org redirect

### ISSUE THREAD

**Issue by djchapm** [golang/go#25238]
$ go get
# cd .; git clone https://go.googlesource.com/net /Users/DJCHAPM/Projects/go/src/golang.org/x/net
Cloning into '/Users/DJCHAPM/Projects/go/src/golang.org/x/net'...
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/net/context: exit status 128
package golang.org/x/net/http2: cannot find package "golang.org/x/net/http2" in any of:
	/usr/local/go/src/golang.org/x/net/http2 (from $GOROOT)
	/Users/DJCHAPM/Projects/go/src/golang.org/x/net/http2 (from $GOPATH)
package golang.org/x/net/trace: cannot find package "golang.org/x/net/trace" in any of:
	/usr/local/go/src/golang.org/x/net/trace (from $GOROOT)
	/Users/DJCHAPM/Projects/go/src/golang.org/x/net/trace (from $GOPATH)
package golang.org/x/net/http2/hpack: cannot find package "golang.org/x/net/http2/hpack" in any of:
	/usr/local/go/src/golang.org/x/net/http2/hpack (from $GOROOT)
	/Users/DJCHAPM/Projects/go/src/golang.org/x/net/http2/hpack (from $GOPATH)

Double checked and go.googlesource.com seems to be down, hoping this go group has some relationship with repo provider as I imagine this is blocking issue for everyone?

**Comment by mvdan** [comment]
Seems to be working now; is it fixes for you?

**Comment by djchapm** [comment]
Yep - Seen a couple of these site down issues last few days - wonder what's up.  Might need a more formal backup plan such as the clone off golang.org.  Thanks.
