### ISSUE TITLE
runtime: opportunistically rotate map key seed

### ISSUE THREAD

**Issue by josharian** [golang/go#25237]
As further protection, when the size of a non-tiny map drops to zero, we should update its hash seed. This is a reminder issue.

See discussion in CL 110055.

cc @martisch @randall77

**Comment by CAFxX** [comment]
Just curious: why not do the same when the map grows? Is there something preventing the new/bigger map storage to use a different seed?

**Comment by randall77** [comment]
The way we grow the map, it isn't possible.  Each original bucket evacuates to just two new buckets.  The hashes need to agree on all the common bits.
There might be other growing algorithms where it could work.

**Comment by randall77** [comment]
Punting to unplanned. Pretty low priority.

**Comment by martisch** [comment]
While https://golang.org/cl/253020 resets the seed when the map clear idiom is used it doesnt reset the seed when maps are emptied to zero elements by just deleting elements without ranging over all the keys or when the pattern for map clear is not triggered.
