### ISSUE TITLE
cmd/vet: printf %q with pointer argument not detected

### ISSUE THREAD

**Issue by rudis** [golang/go#25233]
### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes. Also in Git master as of 2018-05-03.

### What did you do?

```go
package main
import (
        "fmt"
)
func main() {
        x := "hi"
        y := &x
        fmt.Printf("%q\n", y)
}
```
The programs prints `%!q(*string=0xc42000e1e0)` but `go vet` prints no error message.

### What did you expect to see?
`go vet` detects the error.

The problem seems to be the type classification which marks `%q` as `argRune|argInt|argString`, this causes the check in `cmd/vet/types.go` `matchArgTypeInternal()` (under `case *types.Pointer`) to consider `y` (from code above) as valid int, although this won't work with pointers for `%q`.

A potential patch could look like this. However it feels ugly and therefor wasn't submitted as pull request:
```diff
--- types.go.orig       2018-05-03 13:06:45.151615943 +0200
+++ types.go    2018-05-03 13:08:09.414532090 +0200
@@ -201,6 +201,10 @@
                if str, ok := typ.Elem().Underlying().(*types.Struct); ok {
                        return f.matchStructArgType(t, str, arg, inProgress)
                }
+               // %q can't print pointers.
+               if t == (argRune|argInt|argString) {
+                       return false
+               }
                // The rest can print with %p as pointers, or as integers with %x etc.
                return t&(argInt|argPointer) != 0
```

**Comment by ALTree** [comment]
cc @robpike @mvdan

**Comment by mvdan** [comment]
I've been poking around in the vet codebase for a bit, and I think it's simply inconsistent with fmt's documentation and code. I'm going to submit a CL soon, which solves the issue that @rudis is having, and I believe also fixes other inconsistencies with fmt. The patch is different from the one proposed above, though.
