### ISSUE TITLE
syscall: can't inherit fcntlFlock on linux after syscall.Exec

### ISSUE THREAD

**Issue by sakeven** [golang/go#25249]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64
go version go1.8.5 linux/amd64
go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chenlin/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build057651522=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

See code:
https://play.golang.org/p/jTMF5dejA74

### What did you expect to see?

Should inherit fcntlFlock on linux after syscall.Exec.

man 2 fcntl: 
> Record locks are not inherited by a child created via fork(2), but are preserved across an execve(2).

I test c code below. It can inherit fcntlFlock on linux after exceve.
```c
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

int main() {
    printf("begin %d\n", getpid());
    int fd = open("lock", O_WRONLY | O_CREAT | O_TRUNC , 0777);
    if (fd < 0 ) {
      printf("fail to open");
      return -1;
    }

    printf("fd %d\n", fd); 

    struct flock fl ;
    fl.l_type = F_WRLCK;
    fl.l_whence = SEEK_SET;
    fl.l_start = 0;
    fl.l_len = 0;
    
    int errno = fcntl(fd, F_SETLK, &fl);
    if( errno != 0) {
      printf("err %d", errno);
      return -1;
    }

    sleep(5);
    char *env[] = { NULL };
    char *argv[] = {"./test.sh", NULL};
    execve(argv[0], argv, env);
    return 0;
}
```
I also test go code on macOS. It can inherit fcntlFlock on macOS after syscall.Exec, too.

### What did you see instead?

Can't inherit fcntlFlock on linux after syscall.Exec.

**Comment by sakeven** [comment]
@ianlancetaylor I used `syscall.Open` rather than `os.Open`. I know  `os.Open`  will open files with O_CLOEXEC, but `syscall.Open` not.

**Comment by sakeven** [comment]
It seems that it's a problem with Linux kernel.
In a multi-threaded environment the fcntlFlock may be released when execve.

**Comment by ianlancetaylor** [comment]
Thanks for following up.  I'll close this issue since it sounds like there is nothing we can change in Go to fix it.  Please comment if you disagree.
