### ISSUE TITLE
x/build/status/statusserver: seemingly polar opposites of contentLength and error message

### ISSUE THREAD

**Issue by odeke-em** [golang/go#25246]
I was just studying the build system and noticed this code
https://github.com/golang/build/blob/8c46052de7fa644a592f162aa0ffeedd959a9701/status/statusserver/statusserver.go#L115-L118
that is
<img width="1121" alt="screen shot 2018-05-03 at 4 35 40 pm" src="https://user-images.githubusercontent.com/4898263/39607464-0c4b811c-4ef0-11e8-9364-b7ce776d8a8b.png">

Notice that it checks if `ContentLength > 0 && ContentLenght <= 1<<20` but then outputs an error `request requires explicit Content-Length under 1MB`

What's the intention here? Are we rejecting content of:
a) less than 1MB in which case we should fix the error message
b) more than 1MB in which case we should fix the condition from `<=` to `>=`

Here is a repro
```go
package main

import (
	"crypto/tls"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"golang.org/x/build/status/statusserver"
)

func TestStatusServer(t *testing.T) {
	h := statusserver.NewHandler()

	req := &http.Request{
		TLS: new(tls.ConnectionState), Method: "POST",
		Header:        map[string][]string{"Content-Type": []string{"application/x-www-form-urlencoded"}},
		URL:           &url.URL{Path: "/status/update"},
		ContentLength: 10,
	}

	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	res := rec.Result()
	_, err := ioutil.ReadAll(res.Body)
	if err != nil {
		t.Fatalf("Reading body unexpected error %v", err)
	}
	res.Body.Close()
	if g, w := res.StatusCode, http.StatusNoContent; g != w {
		t.Errorf("StatusCode got %d want %d", g, w)
	}
}
```

**Comment by bradfitz** [comment]
Thanks, will fix. That code isn't in use yet.
