### ISSUE TITLE
x/build/cmd/gopherbot: remove wait-author on new patchset uploaded

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25253]
gopherbot is supposed to remove the "wait-author" hashtag when the OP replies.

In this case it did not, because the OP is a GitHub PR, presumably:

https://go-review.googlesource.com/c/go/+/110561

Ideally we'd handle GitHub PRs better and know which Gerrit user == which GitHub user, but as a partial fix: at least handle new patchset uploads as meaning the OP replied too.

/cc @andybons @bcmills @FiloSottile

**Comment by bradfitz** [comment]
We should move to the more conservative heuristic that ANY activity in Gerrit on the CL past the event (magic comment) that added the "wait-author" hashtag is potential OP activity and should remove wait-author.

**Comment by agnivade** [comment]
Duplicate issue filed again at https://github.com/golang/go/issues/28510. That has some more context. I will go ahead and close this.
