### ISSUE TITLE
x/vgo: can't to build gin with vgo

### ISSUE THREAD

**Issue by Yprolic** [golang/go#25250]
If I want to only use the validator.v8,How can I do for it?

### What version of Go are you using (`go version`)?
go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/username/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build375004454=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
vgo get github.com/gin-gonic/gin

### What did you expect to see?
success

### What did you see instead?
vgo: finding github.com/gin-gonic/gin v1.1.4
vgo: finding github.com/gin-gonic/gin v1.1.4
vgo get: parsing downloaded go.mod: go.mod:12: invalid module: gopkg.in/go-playground/validator.v8 should be v1, not v8 (v8.0.0-20160110003959-c193cecd124b)

**Comment by ALTree** [comment]
Thanks for the report.

This was already reported in #25121. Let's keep all the discussion there. Closing this one as a dup.
