### ISSUE TITLE
crypto/tls: rotate session ticket keys

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25256]
When crypto/tls autogenerates session ticket keys, it should also automatically rotate them (with some window of overlap) for forward secrecy.

Split from #19199

**Comment by FiloSottile** [comment]
Let's do this, this is probably the biggest forward secrecy liability of a default crypto/tls server.

I am thinking of deprecating SessionTicketKey in favor of SetSessionTicketKeys, still randomizing it but not using it if it's zero and instead doing a periodic rotation, and of course still using it if set.

**Comment by katiehockman** [comment]
This has been fixed.
