### ISSUE TITLE
Unmarshaling into a map[string]interface{} never yields ints.

### ISSUE THREAD

**Issue by bimargulies** [golang/go#25259]
I expect json.Unmarshal to use an int type when it sees an integer as a number and it has a choice. It seems to always choose float64.

### What operating system and processor architecture are you using (`go env`)?

linux amd

### What did you expect to see?

an int in the map

### What did you see instead?

a float in the map

**Comment by fraenkel** [comment]
It is documented as such, see https://golang.org/pkg/encoding/json/
search for "for JSON numbers" and you will see:
```
To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:
float64, for JSON numbers
```
