### ISSUE TITLE
database/sql: inconsistent error messages

### ISSUE THREAD

**Issue by bontibon** [golang/go#25251]
The database/sql package exports the errors:

```go
var ErrConnDone = errors.New("database/sql: connection is already closed")
var ErrNoRows = errors.New("sql: no rows in result set")
var ErrTxDone = errors.New("sql: Transaction has already been committed or rolled back")
```

1. `ErrConnDone` has "database/sql" as a prefix while the others simply have "sql".
2. `ErrTxDone` uses an uppercase "T" in "Transaction", but shouldn't because `Transaction` is not a type.

**Comment by bontibon** [comment]
cc @kardianos

**Comment by kardianos** [comment]
Technically we are in the freeze, but my other cls haven't been reviewed yet and this is tiny. I'll probably suggest a cl. I'll need to review issue more on desktop.
