### ISSUE TITLE
line 381 at golang 1.10 src/runtime/malloc

### ISSUE THREAD

**Issue by AlaxLee** [golang/go#25276]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alax/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alax/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3j/h495qng92dbcsp8mf9w197mm0000gn/T/go-build957595739=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
read source code

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
	mheap_.arena_end = p1 + pSize

### What did you see instead?
	mheap_.arena_end = p + pSize

because at line 368 the pSize has changed by "	pSize -= p1 - p"
so I think mheap_.arena_end may be "p1 + pSize"

**Comment by randall77** [comment]
I think you are right.
This code is gone in 1.11, as part of the move to multiple arenas.
We might fix it for the next 1.10 point release, though.

@aclements

**Comment by ianlancetaylor** [comment]
The code has been this way since at least Go 1.3.  We should not consider changing it in a point release unless we have a test case that shows the problem.  Since this is fixed in 1.11 I'm going to close this.  Please comment if you disagree.
