### ISSUE TITLE
Conversion of array of bidirectional channels into directional fails

### ISSUE THREAD

**Issue by nerd2** [golang/go#25279]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10.1

go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

`GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/...../Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/...../go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sr/ljc7d6x12dd9872r0rzxw38r0000gn/T/go-build603898073=/tmp/go-build -gno-record-gcc-switches -fno-common"`

### What did you do?

`func fail(x []chan int) []chan<- int {
  return x
}`

https://play.golang.org/p/VPeStoH7PiL

### What did you expect to see?

Successful build

### What did you see instead?

cannot use x (type []chan int) as type []chan<- int in return argument

**Comment by kardianos** [comment]
@nerd2 This is how Go types (and slices) work. chan int and chan<-int are different types. Just like interface{} and int32 are different types. A int32 can satisfy an interface{} in the same way a chan int add direction, but they are different types.

For a similar example, see:
https://play.golang.org/p/trjuRvqRzHU

Questions should be directed to: https://github.com/golang/go/wiki/Questions
