### ISSUE TITLE
golang.org: suggestion for Go versions URL to enable automated downloads

### ISSUE THREAD

**Issue by jcmturner** [golang/go#25271]
Hi,

I wasn't sure where to raise this suggestion so please let me know if I should raise this elsewhere.

My suggestion is to have a machine parsable page for Go release versions. This is to enable automated downloads that may be performed as part of build pipelines, docker builds, to update versions of Go in use, etc.

For example a page that would return JSON in the form:
```json
{
  "version": {
    "major": 1,
    "minor": 10,
    "patch": 2
  },
  "releasedate": "2018-05-01",
  "releasenotes": "https://golang.org/doc/go1.10",
  "checksums": {
    "sha256": "4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff"
  },
  "url": "https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz",
  "os": "linux",
  "arch": "x86-64",
  "kind": "archive",
  "format": "tar.gz"
},
...
}
```

People can then write there own automation to download and test automatically with the latest and various versions of Go.

Setting a header on this page with the checksum of the page body would also enable people to pole in a lightweight way with a HEAD to check if the page has updated since last time they checked.

I searched to see if something like this already exists but I was unable to find anything. If it does exist, please let me know the link.

Thanks.

**Comment by ALTree** [comment]
https://golang.org/dl/?mode=json

**Comment by jcmturner** [comment]
Thanks! That's what I was looking for.
