### ISSUE TITLE
net/http: bundle invocation without -dst is fragile

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25285]
The bundle invocation in the net/http go:generate for h2 does not have a `-dst` flag. So it breaks when bundle was not built with the toolchain associated with the target net/http package, as the embedded GOROOT is wrong. When developing the standard library it's fairly common<sup>[citation needed]</sup> to use a different system compiler to go get binaries, so it's probably worth adding `-dst` at the next run.

/cc @bradfitz

**Comment by bradfitz** [comment]
I'm inclined to say that you're holding it wrong.

That tool has had approximately 1-2 users. Now maybe 1-3. I don't think it's worth the effort changing the tool to be more accommodating to more (uncommon?) configurations.

But if you want to, all yours.

**Comment by bradfitz** [comment]
Definitely not a Go 1.11 blocker by any means.

**Comment by FiloSottile** [comment]
The tool already has the feature, this is only here to remember to add `-dst net/http` next time one of us runs it, as it did not feel worth of its own CL.

**Comment by dmitshur** [comment]
I don't understand this issue. When the -dst flag is not specified, bundle uses the package in the current working directory. The `go generate` command always sets the working directory to that of the package which is being generated. So, not specifying -dst flag means to use the net/http package that's being processed. I don't see how it could ever use a different embedded GOROOT.

It's possible there was an issue here in the past, but I don't think there's anything to do here after #32031 is fixed (by [CL 189818](https://golang.org/cl/189818).

@FiloSottile I suggest we close this unless you think this still needs to be done (if so, please explain).

**Comment by FiloSottile** [comment]
Probably obsoleted, closing.
