### ISSUE TITLE
x/mobile: failed to transform file 'hello.aar' to match attributes 

### ISSUE THREAD

**Issue by QQMBR** [golang/go#25290]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using?
go 1.10.2 on arch linux

### What operating system and processor architecture are you using (`go env`)?
Arch Linux, amd64

### What did you do?
I'm trying to use go with Android Studio and have followed the introduction at [the go mobile wiki](https://github.com/golang/go/wiki/Mobile), importing the hello project, setting my GOPATH etc. and than building the project.

### What did you expect to see?
A successful build

### What did you see instead?
I got the errors 
```
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Unable to resolve dependency for ':app@release/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Failed to transform file 'hello.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
```

The same error presents itself when trying to import an already built .aar 
I'd be very thankful if anyone can point me in the right direction!

**Comment by eliasnaur** [comment]
Please provide the detailed steps to reproduce the problem. What version of Android Studio? Which commands are you running? And so on.

**Comment by QQMBR** [comment]
Using Android Studio 3.1.2 (latest). 
Ran
`go get -d golang.org/x/mobile/example/bind/...`
To get the example hello project, from then on importing it into Android Studio and editing the GOPATH and GO paths in the hello/build.gradle, as per the gomobile wiki.

After that, simply syncing gradle returns this error.

**Comment by eliasnaur** [comment]
It seems this is a dup of https://github.com/golang/go/issues/23307.

**Comment by eliasnaur** [comment]
The CL should fix the issue. Do note, that only gradle sync fails; running a gomobile project from Android Studio does work.
