### ISSUE TITLE
gccgo: internal compiler error for recursive variable declaration

### ISSUE THREAD

**Issue by griesemer** [golang/go#25299]
Compilation of the following (invalid) program crashes gccgo:
```
$ cat x.go
package p

var a [len(a)]int
```
```
$ gccgo x.go
gccgo: internal compiler error: Segmentation fault signal terminated program go1
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://go.ext.google.com/go/> for instructions.
```
```
$ gccgo --version
gccgo (google-gccgo-257955) 8.0.1 20180223 (experimental)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by griesemer** [comment]
Related: Compiling this program
```
package p

var a T

type T [len(a)]int
```
yields:
```
x.go:5:9: error: array bound is not constant
 type T [len(a)]int
         ^
```
which is better (no crash) but perhaps a bit misleading. Any constant size of the array would satisfy the program, were one chosen (e.g., 0). But the program should probably be simply invalid due to a cycle.

**Comment by griesemer** [comment]
For reference:
- cmd/compile reports a type-checking loop for the first program (no type T), and an "invalid argument a for len" error for the 2nd program (with type T).
- go/types reports a cycle error (initialization cycle for a) for the 1st program (no type T), and accepts the 2nd program (with type T) choosing an array length of 0.

I believe we should disallow both programs.

**Comment by ianlancetaylor** [comment]
CC @thanm

**Comment by thanm** [comment]
I'll take a look.

**Comment by griesemer** [comment]
FWIW: I don't think this is an urgent bug to fix; I am recording these mostly so we can get a better understanding of the limits of what we should/should not accept in terms of cycling definitions. But if there's a simple oversight causing the crash, yes, that should perhaps be addressed.

**Comment by thanm** [comment]
Related to https://github.com/golang/go/issues/25315, https://github.com/golang/go/issues/25677, https://github.com/golang/go/issues/25680. Should be able to fix them together.
