### ISSUE TITLE
cmd/vet: builtin calls now return hasSideEffects false

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25303]
https://golang.org/cl/111416 made `hasSideEffects` return false when `CallExpr.Fun` has a true `IsValue`, but "Builtins are not considered values."

This showed up in https://golang.org/cl/112255, where a call to `len` started being recognized as having no side-effects. `len` indeed has no side effects, and it's probably a useful change as shown by the spotted new issue.

However, I suspect not all built-ins are side-effects free.

/cc @griesemer @mvdan

**Comment by mvdan** [comment]
Thanks for noticing so quickly! This was indeed unintended behavior. I'll send a fix right away.
