### ISSUE TITLE
spec: EBNF incorrectly states Receiver can be multiple parameters

### ISSUE THREAD

**Issue by iivvoo** [golang/go#25307]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go 1.10.1 (and whatever play.golang.org runs)

### Does this issue reproduce with the latest release?

Unknown

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 18.04 amd64

### What did you do?

https://golang.org/ref/spec#Method_declarations states that a Method receiver is Parameters:

`Receiver   = Parameters .`

Parameters are defined as

```
Parameters     = "(" [ ParameterList [ "," ] ] ")" .
ParameterList  = ParameterDecl { "," ParameterDecl } .
ParameterDecl  = [ IdentifierList ] [ "..." ] Type .
```

Which would suggest the following is valid (though perhaps nonsensical):

https://play.golang.org/p/O_LHVTmvnJb
```
// https://golang.org/ref/spec#Method_declarations says Receiver = Parameters .

type Weird struct {}

type Weirder struct {}

func (w *Weird, ww *Weirder) Foo() {}

func (w ...*Weird) Foo2() {}

func (w,ww *Weird) Foo3() {}
```

The language spec *does* note that

> That parameter section must declare a single non-variadic parameter, the receiver. Its type must be of the form T or *T (possibly using parentheses) where T is a type name.

However this is something that can be enforced in the EBNF - refering to `Parameters` is simply incorrect and an implementation following the EBNF would provide different parsing.

I know I'm nitpicking here but I do like a language with a clear, unambiguous, well defined grammar defintion :)

### What did you expect to see?

Based on the EBNF I didn't expect to see compilation/syntax errors

### What did you see instead?

```
prog.go:13:30: method has multiple receivers
prog.go:15:6: invalid receiver type []*Weird ([]*Weird is an unnamed type)
prog.go:15:13: cannot use ... in receiver or result parameter list
prog.go:17:20: method has multiple receivers
```

**Comment by cznic** [comment]
The EBNF is just a _part_ of the specification. The EBNF per se describes only the syntax. The semantics of the accompanying text narrows down the the subset of valid programs. There are plenty of other examples where the EBNF is similarly insufficient. For example the [Arguments](https://golang.org/ref/spec#Arguments) production allows writing weird calls like `foo([]T, 1, 2, 3, 4...)` etc.

I believe this is working as intended.

**Comment by cznic** [comment]
> I know I'm nitpicking here but I do like a language with a clear, unambiguous, well defined grammar defintion :)

Wrt the above, note that the EBNF grammar is actually ambiguous. I don't think that qualifies for "well defined grammar". However, the specification text precisely defines how is the ambiguity [resolved](https://golang.org/ref/spec#Composite_literals).

**Comment by ianlancetaylor** [comment]
Agreed.  The spec must maintain a balance of readability and precision.  It is an intentional decision that the EBNF grammar accepts Go programs that the additional text rejects.  We believe that this makes the spec more readable overall.

**Comment by griesemer** [comment]
To add an example to what @ianlancetaylor said: By making the Receiver simply a ParameterList, a reader doesn't have to understand yet another (if small), different production; instead it's just the (familiar) parameter list. It's simpler to write down (in prose) that there can be just a single receiver.
