### ISSUE TITLE
cmd/go: long tests failing on Windows

### ISSUE THREAD

**Issue by neolit123** [golang/go#25300]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version devel +e0adc35c Tue May 8 21:15:48 2018 +0000 windows/amd64
```

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
>go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Lubo\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Lubo\go
set GORACE=
set GOROOT=c:\dev\go
set GOTMPDIR=
set GOTOOLDIR=c:\dev\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Windows\T
EMP\go-build598151490=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
> go test cmd/go -v
```

`cmd/go` passes when doing:
```
src/all.cmd
```

or:
```
go test -short -v cmd/go
```

### What did you expect to see?

passing tests for `cmd/go`.

### What did you see instead?

https://gist.githubusercontent.com/neolit123/b48fc27c8be1eb598fb41ce3cb2366f4/raw/06c1e91e076206574f4136a72aa238c3b1df878d/gistfile1.txt

with an older version i used to see this:

```
*** Test killed: ran too long (10m0s).
```
full log here:
https://pastebin.com/XNNAKhBW

requested by:
@alexbrainman 

refs:
https://github.com/golang/go/issues/24709

**Comment by ianlancetaylor** [comment]
Using `src/all.cmd` will run `go test -test.short cmd/go`.  What happens if you run `go test -short -v cmd/go`?  That is, is the problem due to adding `-v`, or is it due to omitting `-short`?

**Comment by rsc** [comment]
It looks from the transcript in the link that there are some failing tests in non-short mode. Unfortunately, that's true, or at least was in May. 

I don't see anything in the initial report about a 3-minute failure. Not sure why Brad put that in the title.

**Comment by neolit123** [comment]
updated and rebuild latest master:
```
go version devel +43530e6b Fri Oct 26 12:37:30 2018 +0000 windows/amd64
```

go env is same as OP.

`go test cmd/go -v`

https://gist.githubusercontent.com/neolit123/b48fc27c8be1eb598fb41ce3cb2366f4/raw/8dc9a4c812cc5a6e81c03112768083735afa15ac/october%25202018%2520run%25201

i ran the tests a 3-4 times and it seems to fail at a different location each time.

it prompts for github login in one of the tests and if one does not enters it too fast it can fail with a:
`*** Test killed: ran too long (10m0s).` error once.`

**Comment by bcmills** [comment]
It's not obvious to me whether tests are still failing on Windows, but I seem to have sent CLs to fix the ones I was aware of.

It seems to me that the appropriate long-term solution is to actually run all of the tests on a builder on a regular basis (#26529), which may require adding or configuring more tools on the builder image (see also #32430).

If specific tests are failing or regressing, please let us know which ones and in what configuration, or just send a CL to fix them. Otherwise, I don't think we need to keep an umbrella issue open.

**Comment by bcmills** [comment]
We are now running the long tests on the `windows-amd64-longtest` builder, and they are indeed failing (https://build.golang.org/log/1805b0fbce354f6ac6e08ca9196e418cb142171a).

Now that we have a builder that reproduces the failures, we can work on fixing them.
