### ISSUE TITLE
x/mobile: consider androidstudio gobind plugin retirement

### ISSUE THREAD

**Issue by hyangah** [golang/go#25314]
Working with the gradle plugins is a pain, we have no active maintainer for this plugin.
The release process is not well-established (#14690).
Maintenance burden seems to outweigh the benefit.

Users can manually build the .aar file with gomobile and import the .aar file into the studio without the plugin.

@eliasnaur

**Comment by prep** [comment]
Apologies for commenting in a closed ticket, but it's a bit unclear to me how the plugin-specific functionality (like databinding and R/layout generation) from the plugin is replaced. Is there an alternative way to go about this, or should I consider the removal of the plugin and the reverse example as a hint that Android support via reverse bindings is being depreciated?
