### ISSUE TITLE
strings.TrimLeft bug

### ISSUE THREAD

**Issue by DemoLiang** [golang/go#25328]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

### What did you do?
just for a demo
func main() {
	cfgs := "mongodb://off"
	cfgs = strings.TrimLeft(cfgs, "mongodb://")
	fmt.Printf("cfgs:%v\n",cfgs)	
        //output ==> cfgs:ff
}
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
//output ==> cfgs:off

### What did you see instead?
//output ==> cfgs:ff

**Comment by myitcv** [comment]
I think you want https://godoc.org/strings#TrimPrefix instead.

**Comment by DemoLiang** [comment]
Thanks
