### ISSUE TITLE
cmd/go/internal/cache: remove $GOCACHE/log.txt

### ISSUE THREAD

**Issue by mattn** [golang/go#25323]
In my $GOCACHE, file size of my log.txt is 5.7MB. Current implementation doesn't take care the size of log.txt. Some environment possibly have more large log file. How about to add a way to remove or rotating log file?

**Comment by japettyjohn** [comment]
I can confirm the possibility of a large file - I ran into one being 12 gigs and stretching back 4 months. This could be addressed either in the `go clean -cache` routine in [clean.go](https://github.com/golang/go/blob/f999576dd8df6e4d09e3c67c23ba4d8dc18d53d3/src/cmd/go/internal/clean/clean.go#L118) or added as another flag there, e.g. `go clean -cacheLog`.

**Comment by FiloSottile** [comment]
Mine is 451M, while the rest of the cache is 20M. I think we should limit its size automatically, not only when a specific "go clean" command is run.

**Comment by bradfitz** [comment]
It's pretty late to add new command line flags to cmd/go.

Bumping to Go 1.13.
