### ISSUE TITLE
question on license

### ISSUE THREAD

**Issue by luisapace** [golang/go#25331]
Hi, in the  **go/src/crypto/sha512/sha512block_ppc64le.s** module contained in go 1.10 I see:

**_// Based on CRYPTOGAMS code with the following comment:
// # ====================================================================
// # Written by Andy Polyakov <appro@openssl.org> for the OpenSSL
// # project. The module is, however, dual licensed under OpenSSL and
// # CRYPTOGAMS licenses depending on where you obtain it. For further
// # details see http://www.openssl.org/~appro/cryptogams/.
// # =======================================_**

Could you please tell me where is this module obtained from, so I can determine its license (OpenSSL or CRYPTOGAMS)?

Thanks.

**Comment by ALTree** [comment]
The answer should be "CRYPTOGAMS". 

See: https://go-review.googlesource.com/c/go/+/87315, the commit that added that notice. It says:

> crypto: clarify that some files come from CRYPTOGAMS
> and that they are covered by the CRYPTOGAMS license.

**Comment by luisapace** [comment]
Many thanks.

**Comment by ALTree** [comment]
NP. Since your question was answered, I'm going to close this issue.
