### ISSUE TITLE
cmd/compile: autogenerated wrapper is not inlined 

### ISSUE THREAD

**Issue by TocarIP** [golang/go#25338]
### What version of Go are you using (`go version`)?
Master:
```
go version devel +5bd88b0 Thu May 10 18:02:07 2018 +0000 linux/amd64
```

Running encoding/binary benchmarks I see significant slowdown (compared to 1.10):
```
WriteSlice1000Int32s-4                           9.51Âµs Â± 2%    12.83Âµs Â± 2%    +34.92%  (p=0.008 n=5+5)
ReadSlice1000Int32s-4                            9.34Âµs Â± 2%    12.60Âµs Â± 2%    +34.90%  (p=0.008 n=5+5)
```

This  is caused by compiler not inlining autogenerated binary.(*bigEndian).PutUint32, which does nothing but shuffles arguments and calls binary.bigEndian.PutUint32.

Bisect points to ca2f85fd3f32b2a4c863a2de602876bd31e9d956, which is IMHO strange, because it doesn't enable new export format by default.
@mdempsky  any ideas?

**Comment by TocarIP** [comment]
In genwrapper (cmd/compile/internal/gc/subr.go) I see:
```
        // TODO(mdempsky): Investigate why this doesn't work with
        // indexed export. For now, we disable even in non-indexed
        // mode to ensure fair benchmark comparisons and to track down
        // unintended compilation differences.
        if false {
                inlcalls(fn)
        }
```
Should we at least change false to flagiexport, since benchmarks are done?

**Comment by josharian** [comment]
@TocarIP I see you are systematically checking benchmarks and running down significant regressions. Just wanted to say a hearty thank you for doing this!

**Comment by agnivade** [comment]
> I see you are systematically checking benchmarks and running down significant regressions. 

Probably we should automate this through a nightly job so that offfending CLs are caught quicker.

**Comment by randall77** [comment]
I believe this is fixed now. The CL above, and possibly the slightly more aggressive mid-stack inlining makes the wrapper inline successfully.
Tip is still slower than 1.10, but only by a few percent.
