### ISSUE TITLE
encoding/base32: buffered decoder expects padding even when NoPadding is set

### ISSUE THREAD

**Issue by AxbB36** [golang/go#25332]
A decoder created with `NewDecoder` and `NoPadding` expects to find padding at the end of the input, which differs from the behavior of `Decode` and `DecodeString`.

This bug is separate from #25296, which fixed the error result for the non-`NoPadding` case.

### What version of Go are you using (`go version`)?

`go version devel +ef24fd739b Thu May 10 15:40:01 2018 +0000 linux/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

### What did you do?

https://play.golang.org/p/k9HrTwJM29c
```
package main

import (
	"encoding/base32"
	"fmt"
	"io/ioutil"
	"strings"
)

func main() {
	withoutPadding := base32.StdEncoding.WithPadding(base32.NoPadding)
	input := withoutPadding.EncodeToString([]byte("foobar"))
	fmt.Printf("input %q\n", input)
	r, err := withoutPadding.DecodeString(input)
	fmt.Printf("DecodeString: %q %v\n", r, err)
	r, err = ioutil.ReadAll(base32.NewDecoder(withoutPadding, strings.NewReader(input)))
	fmt.Printf("NewDecoder  : %q %v\n", r, err)
}
```

### What did you expect to see?

```
input "MZXW6YTBOI"
DecodeString: "foobar" <nil>
NewDecoder  : "foobar" <nil>
```

### What did you see instead?

```
input "MZXW6YTBOI"
DecodeString: "foobar" <nil>
NewDecoder  : "fooba" unexpected EOF
```

Before the fix for #25296:

```
input "MZXW6YTBOI"
DecodeString: "foobar" <nil>
NewDecoder  : "fooba" <nil>
```

**Comment by ianlancetaylor** [comment]
cc @zegl
