### ISSUE TITLE
access: Trybot Access ("may-start-trybots")

### ISSUE THREAD

**Issue by oiooj** [golang/go#25344]
With the Github access I suspect my main contribution initially will be to help garden issues , close them where I currently cannot.

See https://golang.org/wiki/GerritAccess

My github account: oiooj
My gerrit email: nototon@gmail.com
All my participating CLs: https://go-review.googlesource.com/q/owner:nototon%2540gmail.com

With the Gerrit access I'd be looking to run trybots.
I am very interested in project `vgo`. Thanks for considering my request.

@bradfitz @andybons

**Comment by bradfitz** [comment]
Done. You now have trybot access.

**Comment by oiooj** [comment]
Thanks. @bradfitz, Can I close some issues in vgo milestone like #25121 now? This issue already fixed by CL 112277.

**Comment by bradfitz** [comment]
No, because you only asked for Gerrit access.

You should go comment on #25121 and say why it's no longer relevant and what fixed it.

**Comment by oiooj** [comment]
@bradfitz Done. I filed a new issue #25502 for asking Github access.
