### ISSUE TITLE
error interface

### ISSUE THREAD

**Issue by biyoule** [golang/go#25346]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?

type TE struct{}

func (this *TE) Error() string {
	return "Test Error"
}

func Test() error {
	return TE{}
}

### What did you expect to see?

PASS
### What did you see instead?
cannot use TE literal (type TE) as type error in return argument:
	TE does not implement error (Error method has pointer receiver)

**Comment by robpike** [comment]
You need to return a pointer to a TE to satisfy the signature of the Error method:

```
func Test() error {
  return &TE{}
}
```

**Comment by biyoule** [comment]
TE{} contain mothod Error() string
PS:
func Test() {
	t := TE{}
	t.Error()
}

**Comment by biyoule** [comment]
@robpike

**Comment by mvdan** [comment]
@biyoule that is because a struct literal is not addressable, but a struct variable is. If the method requires a pointer receiver, it is going to implicitly grab the value's address.

**Comment by biyoule** [comment]
I see, Thank all .
