### ISSUE TITLE
x/build: failing test in x/sys/unix since Linux builder update

### ISSUE THREAD

**Issue by tklauser** [golang/go#25354]
TestSCMCredentials in `golang.org/x/sys/unix` fails on all linux builders:

https://build.golang.org/log/e3c1adc5394f1c8d24cf8eaffaac90b69105cccf
https://build.golang.org/log/221593d098a3343a7249689138ae3db458909cc4
https://build.golang.org/log/d03f8c8aa75e69e86d3527fe263ac16e6a291a1a

It already failed during the trybot runs for https://golang.org/cl/112696 but the CL is unrelated to the failing `TestSCMCredentials`.

Presumably this is caused by the recent Linux builder changes regarding #25108?

/cc @bradfitz

**Comment by bradfitz** [comment]
The test tries to send a message to its PID minus one and expect it to not have permissions? But we're root now (unlike our fake root in Kubernetes before), so we do have permissions, but the PID-minus-one just doesn't exist?

```go
                var ucred unix.Ucred
                ucred.Pid = int32(os.Getpid() - 1)
                ucred.Uid = uint32(os.Getuid())
                ucred.Gid = uint32(os.Getgid())
                oob := unix.UnixCredentials(&ucred)
                _, _, err = cli.(*net.UnixConn).WriteMsgUnix(nil, oob, nil)
                if op, ok := err.(*net.OpError); ok {
                        err = op.Err
                }
                if sys, ok := err.(*os.SyscallError); ok {
                        err = sys.Err
                }
                if err != syscall.EPERM {
                        t.Fatalf("WriteMsgUnix failed with %v, want EPERM", err)
                }
```

**Comment by bradfitz** [comment]
@hugelgupf, can you help us fix this failing test?

We moved Go's builders from Kubernetes pods to privileged Docker containers under GCE Contained-Optimized OS and now there are behavior differences in this test you added in https://github.com/golang/sys/commit/f67933eaf9e2f750f58a234209a11ebc1107be38

Thanks!

**Comment by hugelgupf** [comment]
Now that you are root, the test is somewhat moot. Both before and after I made that change, you were looking to elicit `EPERM` from the kernel -- once you have all capabilities, that's not going to happen. Essentially, you are testing the syscall here, not the Go logic.

You could add some logic where you spawn a new thread, lock it to an OS thread, drop capabilities and change user ID, and then try to elicit EPERM -- but I would say it's not really worth it unless you are trying to test the syscall itself.

My 2c: just delete it.

**Comment by bradfitz** [comment]
@hugelgupf, SGTM. I sent https://go-review.googlesource.com/#/c/sys/+/112738 ... care to review?
