### ISSUE TITLE
go/types: TestStdlib fails due failed import in vendored pprof

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25367]
### What version of Go are you using (`go version`)?

~/golang/src (master=) % go version
go version devel +6876447952 Sat May 12 16:26:36 2018 +0000 darwin/amd64

### How to reproduce
```
/golang/src % go test go/types
--- FAIL: TestStdlib (6.66s)
	stdlib_test.go:223: /Users/thorn/golang/src/cmd/vendor/github.com/google/pprof/pprof.go:24:2: could not import github.com/chzyer/readline (can't find import: "github.com/chzyer/readline")
	stdlib_test.go:223: /Users/thorn/golang/src/cmd/vendor/github.com/google/pprof/pprof.go:79:18: invalid operation: r.rl (variable of type *invalid type) has no field or method Stderr
	stdlib_test.go:223: /Users/thorn/golang/src/cmd/vendor/github.com/google/pprof/pprof.go:69:18: invalid operation: r.rl (variable of type *invalid type) has no field or method Stderr
	stdlib_test.go:223: /Users/thorn/golang/src/cmd/vendor/github.com/google/pprof/pprof.go:58:7: invalid operation: r.rl (variable of type *invalid type) has no field or method SetPrompt
	stdlib_test.go:223: /Users/thorn/golang/src/cmd/vendor/github.com/google/pprof/pprof.go:59:14: invalid operation: r.rl (variable of type *invalid type) has no field or method Readline
FAIL
FAIL	go/types	7.313s
```
Introduced in 46047e64479c30602f0fb42c6915638006d7335d by @hyangah 
Library "github.com/chzyer/readline" is not installed on my system and not vendored as well.

**Comment by agnivade** [comment]
Wonder how the try-bots passed this.

**Comment by ysmolsky** [comment]
Maybe this test is not run by try-bots?
```
% go test -short go/types
ok  	go/types	0.370s
```

**Comment by agnivade** [comment]
That's right. Try-bots just run `-short` tests if I am not mistaken.

**Comment by mvdan** [comment]
I was under the impression that Go's pprof vendor wouldn't use readline, so we wouldn't have to pull it in as a dependency. If so, this is hopefully just a mistake with an easy fix.

**Comment by hyangah** [comment]
We don't use the file, so we can delete it.

**Comment by hyangah** [comment]
Currently there is no formal procedure to update this, so I will just write a script for update.

**Comment by mvdan** [comment]
Do you mean that `vendor.json` has been getting updated manually? I assumed that it was done with a tool like `govendor`, but I failed to get that one to work properly.
