### ISSUE TITLE
net: LookupHost("nonexistentdomain.golang.org"): returns [173.194.74.141 2607:f8b0:4001:c14::8d]

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#25361]
Recent CL 111718 added TestLookupHostCancel that fails on plan9 builder

https://build.golang.org/log/63c5911a1ae08505472b57f58267a3f778b3eb5a
```
--- FAIL: TestLookupHostCancel (0.05s)
	lookup_test.go:941: LookupHost("nonexistentdomain.golang.org"): returns [173.194.74.141 2607:f8b0:4001:c14::8d], but should fail
FAIL
FAIL	net	26.834s
```

/cc @0intro 

Alex

**Comment by 0intro** [comment]
It looks like the Plan 9 resolver follows the CNAME, while it doesn't seem to be the case on the other builders.

```

**Comment by 0intro** [comment]
It looks like the Plan 9 resolver follows the CNAME, while it doesn't seem to be the case on the other builders.

**Comment by 0intro** [comment]
The `nonexistentdomain.golang.org` name returns a CNAME to  golang.org.

```
nonexistentdomain.golang.org. 86400 IN  CNAME   golang.org.
golang.org.             1800    IN      A       216.58.215.49
```

It looks like the Plan 9 resolver follows the CNAME, while it doesn't seem to be the case on the other builders.

Would it be possible to change TestLookupHostCancel to query a name that doesn't return a CNAME entry, like `nonexistentdomain.example.org` for example?

**Comment by 0intro** [comment]
After re-reading the change, I figured out it doesn't matter if the DNS request succeeds or not. What matter is that when the DNS request is canceled, LookupHost returns errCanceled.

This doesn't work on Plan 9 because DNS requests can't be canceled on Plan 9 currently. On Plan 9, DNS requests are done by writing to a file. Maybe this issue could be fixed by implementing cancellations in LookupHost on Plan 9.

**Comment by alexbrainman** [comment]
> This doesn't work on Plan 9 because DNS requests can't be canceled on Plan 9 currently. On Plan 9, DNS requests are done by writing to a file.

Same on Windows. DNS requests are answered by calling blocking API.

> Maybe this issue could be fixed by implementing cancellations in LookupHost on Plan 9.

That is what windows code does. CL 111718 fixed a bug in that code.

I will leave CL 112955 in, if you decide to submit it. After you convince Brad to remove -2.

Alex

**Comment by bradfitz** [comment]
I'll investigate the CNAME issue and make sure we're using a DNS name with no results too.

**Comment by bradfitz** [comment]
Please keep some bug open about CNAME for that domain if you close this one.

**Comment by 0intro** [comment]
I've opened #25370.
