### ISSUE TITLE
cmd/cover: improve html coverage report

### ISSUE THREAD

**Issue by kt3k** [golang/go#25368]
This is an issue for discussing the feature suggested in #25267 ([111647](https://go-review.googlesource.com/c/go/+/111647))

I think the current html coverage report has two problems.

1. It's hard to navigate through pages.
2. It's hard to get the overview of the entire coverage.

These are caused by the fact that we use the select box for navigating through pages. I think that is not a standard way to organize the multiple report pages.

My suggestion is that we should have the index page for the html coverage reports. The demo is available at https://kt3k.github.io/go-cover-html-improve-demo/coverage.html

This idea is inspired by the tools like istanbul, JaCoCo or simplecov. They all have the index page of the coverage report.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
CC @robpike

**Comment by robpike** [comment]
I think it's fine as is, so you need to ask someone else's opinion to support a change. We don't need visual wonder, we need accurate information in simple form without mounds of Javascript and CSS. The current situation is just fine.

**Comment by kt3k** [comment]
OK. This is probably something should be done in a 3rd party tool.
