### ISSUE TITLE
Node crash accidental

### ISSUE THREAD

**Issue by mohitsharma18** [golang/go#25377]
Geth

Expected behaviour

Actual behaviour

Steps to reproduce the behaviour**

miner.start()
waiting...

Backtrace

goroutine 57437 [IO wait]:
internal/poll.runtime_pollWait(0x7f7412de7ea0, 0x72, 0xc42034fe58)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422124898, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422124898, 0xc421936000, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422124880, 0xc421936011, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422124880, 0xc421936011, 0x1, 0x1, 0xc421f93c20, 0x0, 0xc4216c6e58)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734700, 0xc421936011, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421936000)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57438 [IO wait]:
internal/poll.runtime_pollWait(0x7f73fb67e930, 0x72, 0xc4f5ecde58)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422124998, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422124998, 0xc421936600, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422124980, 0xc421936641, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422124980, 0xc421936641, 0x1, 0x1, 0xc421f93c20, 0x0, 0xc4214bea98)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734708, 0xc421936641, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421936630)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57439 [IO wait]:
internal/poll.runtime_pollWait(0x7f74fc0a3110, 0x72, 0xc42034c658)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422124a98, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422124a98, 0xc421936f00, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422124a80, 0xc421936f11, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422124a80, 0xc421936f11, 0x1, 0x1, 0xc42155d200, 0x0, 0xc4214beed8)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734710, 0xc421936f11, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421936f00)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57440 [IO wait]:
internal/poll.runtime_pollWait(0x7f7412de8790, 0x72, 0xc4f1115658)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422124b98, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422124b98, 0xc421937400, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422124b80, 0xc4219374b1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422124b80, 0xc4219374b1, 0x1, 0x1, 0xc42203ac00, 0x0, 0xc4206fca18)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734718, 0xc4219374b1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc4219374a0)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57441 [IO wait]:
internal/poll.runtime_pollWait(0x7f7412de9080, 0x72, 0xc4209b4e58)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422124c18, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422124c18, 0xc421937900, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422124c00, 0xc421937931, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422124c00, 0xc421937931, 0x1, 0x1, 0xc421746d20, 0x0, 0xc42067bfd8)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734720, 0xc421937931, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421937920)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57474 [IO wait]:
internal/poll.runtime_pollWait(0x7f7412de7820, 0x72, 0xc4209b3658)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422125118, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422125118, 0xc421568700, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422125100, 0xc421568731, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422125100, 0xc421568731, 0x1, 0x1, 0x0, 0xc421981200, 0x6f1cd7)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734728, 0xc421568731, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421568720)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 57475 [IO wait]:
internal/poll.runtime_pollWait(0x7f73fb67fcb0, 0x72, 0xc4209b6658)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc422125198, 0x72, 0xffffffffffffff00, 0x10885c0, 0x178fca8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc422125198, 0xc421568d00, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc422125180, 0xc421568dc1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc422125180, 0xc421568dc1, 0x1, 0x1, 0xc4216fed20, 0x0, 0xc42067bed8)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc439734730, 0xc421568dc1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc421568db0)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

**Comment by davecheney** [comment]
I’m sorry you had this crash but we cannot help you, this looks like a problem with geth. 

I suggest you report this bug to the geth project and if necessary they will raise a bug here (although my spider senses tell me this is a data race).
