### ISSUE TITLE
cmd/compile: compiler array indexing improvements

### ISSUE THREAD

**Issue by rsc** [golang/go#2537]
<pre>CL 5449077 should not be necessary.

var x [4][256]byte
_ = x[1][i]

should be just as efficient as

var x0, x1, x2, x3 [256]byte
_ = x1[i]</pre>

**Comment by dgryski** [comment]
Is this still valid with the new SSA backend?

https://godbolt.org/g/h6w53Q seems to suggest it's generating the same code.

**Comment by randall77** [comment]
Yes, I think this is fixed.
