### ISSUE TITLE
x/vgo: vgo vendor must process all tags

### ISSUE THREAD

**Issue by wzshiming** [golang/go#25376]
### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
no

### What did you expect to see?

In MAC, Linux depends on the package vendor.

**Comment by rsc** [comment]
The problem here is that if you have a source file x.go that says `// +build linux` and you are on a Mac, then the default loader will ignore it. An import specific to that file will not be seen and not be explored for vendoring purposes. It needs to be.
