### ISSUE TITLE
net: nonexistentdomain.golang.org returns a CNAME to golang.org

### ISSUE THREAD

**Issue by 0intro** [golang/go#25370]
CL [111718](https://golang.org/cl/111718) added TestLookupHostCancel.

This test sends a DNS request to nonexistentdomain.golang.org. However, this
DNS request succeeds and return a CNAME record to golang.org.

```
nonexistentdomain.golang.org. 86400 IN  CNAME   golang.org.
golang.org.             1800    IN      A       216.58.215.49
```

@alexbrainman @bradfitz

**Comment by bcmills** [comment]
I've been seeing this from time to time in the TryBots, too:
https://storage.googleapis.com/go-build-log/2ef40d4f/windows-amd64-2016_5206ec72.log

**Comment by bradfitz** [comment]
Ian, could you check the golang.org DNS definitions in google3?

/cc @iangudger @mdempsky @dmitshur

**Comment by iangudger** [comment]
It looks like we have a wildcard *.golang.org to golang.org CNAME.

**Comment by bradfitz** [comment]
Does `*.golang.org` in our DNS config file also match two levels, like `not.exist.golang.org`?

**Comment by iangudger** [comment]
Yes, it seems to.

**Comment by bradfitz** [comment]
Per discussion elsewhere, this seems to be because golang.org has an HSTS policy and Google's servers add a *.golang.org CNAME record related to that.

So I guess we could move that test to use a different domain... `notexist.example.com` seems to work?
