### ISSUE TITLE
x/vgo: vgo thinks I'm outside my GOPATH

### ISSUE THREAD

**Issue by ardan-bkennedy** [golang/go#25372]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"
GOPATH="/Users/bill/code/go"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

This project is already on my machine inside the GOPATH
`https://github.com/ardanlabs/gotraining`

So I tried building it

```
$ cd $GOPATH/src/github.com/ardanlabs/gotraining
$ touch go.mod
$ vgo build
```

### What did you expect to see?

I expected the project to build.

### What did you see instead?

```
vgo: cannot determine module path for source directory /Users/bill/code/go/src/github.com/ardanlabs/gotraining (outside GOPATH, no import comments)
```

**Comment by OneOfOne** [comment]
There's a workaround: `echo module github.com/ardanlabs/gotraining > go.mod`, however it still fails for me with #25007.

**Comment by kardianos** [comment]
Please try cl https://golang.org/cl/111264 to see if it fixes it.

**Comment by ardan-bkennedy** [comment]
Hi @kardianos. How do I go about trying CL 111264? Never done this before.

**Comment by kardianos** [comment]
Go get vgo like normal. In cl click download. Then on first line in dialogue, click copy. Paste into terminal in vgo repo. Run go install to rebuild.

**Comment by ardan-bkennedy** [comment]
Brilliant. That patch worked.

**Comment by kardianos** [comment]
Duplicate issues are normally closed. I was contemplating leaving this open for a bit as the original issue wasn't found when reporting.
