### ISSUE TITLE
x/vgo: missing dependendency in go.mod file

### ISSUE THREAD

**Issue by ardan-bkennedy** [golang/go#25371]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Using this project
https://github.com/ardanlabs/service

I added an empty go.mod file at the root of the project.
I ran the `vgo build` command
Once that was done, the `go.mod` file contained the following

```
module github.com/ardanlabs/service

require (
	github.com/dimfeld/httptreemux v0.0.0-20180213074414-7f532489e773
	github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
	github.com/pkg/errors v0.8.0
	go.opencensus.io v0.9.0
	gopkg.in/go-playground/validator.v8 v8.18.2
	gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
)
```

### What did you expect to see?

There is a dependency in my vendor folder that is missing from the `go.mod` file that is being used.

`github.com/openzipkin/zipkin-go`

I expected to see that in the `go.mod` file.

When I run the `vgo list -m` command I do see this in the list.

```
$ vgo list -m -u
MODULE                                            VERSION                             LATEST
github.com/ardanlabs/service                      -                                   -
cloud.google.com/go                               v0.21.0 (2018-04-09 13:38)          v0.22.0 (2018-05-09 10:25)
github.com/beorn7/perks                           v0.0.0-20180321164747-3a771d992973  -
github.com/dimfeld/httptreemux                    v0.0.0-20180213074414-7f532489e773  -
github.com/golang/protobuf                        v1.0.0 (2018-01-25 13:43)           v1.1.0 (2018-04-30 11:52)
github.com/googleapis/gax-go                      v0.0.0-20170915024731-317e0006254c  v1.0.0 (2017-09-01 17:52)
github.com/matttproud/golang_protobuf_extensions  v1.0.0 (2016-04-23 10:36)           -
github.com/openzipkin/zipkin-go                   v0.1.0 (2018-02-27 02:13)           -
github.com/pborman/uuid                           v0.0.0-20180122190007-c65b2f87fee3  -
github.com/pkg/errors                             v0.8.0 (2016-09-28 18:48)           -
github.com/prometheus/client_golang               v0.8.0 (2016-08-17 08:48)           v0.9.0-pre1 (2017-08-31 06:19)
github.com/prometheus/client_model                v0.0.0-20171117100541-99fa1f4be8e5  -
github.com/prometheus/common                      v0.0.0-20180413074202-d0f7cd64bda4  v0.0.0-20180426121432-d811d2e9bf89
github.com/prometheus/procfs                      v0.0.0-20180408092902-8b1c2da0d56d  -
go.opencensus.io                                  v0.9.0 (2018-04-30 11:08)           -
golang.org/x/net                                  v0.0.0-20180406214816-61147c48b25b  v0.0.0-20180511174649-2491c5de3490
golang.org/x/oauth2                               v0.0.0-20180402223937-921ae394b943  v0.0.0-20180503012634-cdc340f7c179
golang.org/x/sync                                 v0.0.0-20180314180146-1d60e4601c6f  -
golang.org/x/text                                 v0.3.0 (2017-12-14 05:08)           -
google.golang.org/api                             v0.0.0-20180413000347-fca24fcb4112  v0.0.0-20180513000358-15aea8711db9
google.golang.org/appengine                       v1.0.0 (2016-09-29 13:31)           -
google.golang.org/genproto                        v0.0.0-20180409222037-51d0944304c3  v0.0.0-20180427144745-86e600f69ee4
google.golang.org/grpc                            v1.11.3 (2018-04-09 13:31)          v1.12.0 (2018-05-08 14:01)
gopkg.in/go-playground/validator.v8               v8.18.2 (2017-07-29 22:02)          -
gopkg.in/mgo.v2                                   v2.0.0-20160818020120-3f83fa500528  -
```

### What did you see instead?

I just expected all my vendored dependencies to show up in the `go.mod` file.

**Comment by oiooj** [comment]
There is a bug if your project and one of your imports have a common dep.

In your codebase, `github.com/ardanlabs/service` needs `github.com/openzipkin/zipkin-go`, and `go.opencensus.io` also needs `github.com/openzipkin/zipkin-go`. 

`go.opencensus.io` will be written into go.mod, but `github.com/openzipkin/zipkin-go` will not be.

Thanks.

**Comment by bcmills** [comment]
As @oiooj notes, the `go.mod` file only contains requirements that are not implied transitively.
(Also recall that `vgo build` ignores the `vendor/` directory in general.)

You should find that `vgo vendor` still copies the appropriate version into your `vendor/` directory.

We certainly do need to work on some concise documentation for these sorts of properties, but I think that's a separate matter from this issue itself. Please feel free to reopen if you disagree.

**Comment by rsc** [comment]
Actually, @bcmills realized that the build list algorithm assumes that direct dependencies are listed explicitly in go.mod, so we'll start doing that, even when the result is not minimal. Will send a CL probably tomorrow.
