### ISSUE TITLE
the result of sort.SearchString not expect

### ISSUE THREAD

**Issue by thinkerou** [golang/go#25382]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.10 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
`GOROOT="/usr/local/Cellar/go/1.10/libexec"`

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

code:
```go
func main() {
	s := []string{"c", "ca", "b", "d", "a"}

	sort.Strings(s)
	fmt.Println(s)

	i := sort.SearchStrings(s, "bx")
	println(i)
}
```

```
➜  ~ go run test.go
[a b c ca d]
2
```
### What did you expect to see?
it should return 5

**Comment by blyork** [comment]
The [docs](https://golang.org/pkg/sort/#SearchStrings) say that it will return the insertion index if the element is not found. 2 is the correct value because "bx" comes after "b" and before "c" and "b" is at index 1.

**Comment by dominikh** [comment]
Working as intended as per @blyork
