### ISSUE TITLE
sync: Map.Delete to return deleted value

### ISSUE THREAD

**Issue by localvar** [golang/go#25396]
I need to know if an item is actually deleted when call `Delete` of `sync.Map`, but the function returns nothing currently.

Is it possible for it to return the deleted value and/or a `bool` to indicate whether something is really deleted?

Thanks.

**Comment by agnivade** [comment]
It is not possible to do that without breaking Go1 compatibility. I assume that you don't want to make an extra `.Load` call to check whether the element is present in the map or not ?

**Comment by localvar** [comment]
@agnivade, thanks for the reply.  However, I don't think an extra `.Load` call works, because the item could be deleted in another go-routine between my call to `.Load` and `.Delete`.

I have little knowledge about Go1 compatibility, but in my understanding, add return value to `.Delete` won't break any existing code, because it currently returns nothing.

**Comment by davecheney** [comment]
@localvar 'fraid not, the current intpretation of the Go 1 contract assumes that someone has assigned a method as a function; eg
```
var m sync.Map
var del = m.Delete
```
Changing the signature of `sync.Map.Delete` could break code like this, depending on how `del` is used, hence this type of proposal is not acceptable under the Go1 contract.

**Comment by davecheney** [comment]
Duplicate of #23547 and closing as #23547 states that this change cannot be accepted.

**Comment by agnivade** [comment]
Ah I was pretty sure this was raised before but could not find anything when I searched. Thanks.

**Comment by localvar** [comment]
Is adding a new function (for an ugly example: `Delete2`) acceptable?

I checked the source code and find the internal `entry.delete` does have a return value.
