### ISSUE TITLE
x/crypto/sha3: add cSHAKE support

### ISSUE THREAD

**Issue by henrydcase** [golang/go#25395]
The code for cSHAKE is now ready here https://go-review.googlesource.com/c/crypto/+/111281/

Is there any chance to merge it soon?

**Comment by FiloSottile** [comment]
(This was approved in #24988.)

This week is the Go team summit so we are going to be a bit slow at reviewing, sorry about that.

**Comment by henrydcase** [comment]
Ok, thnx for update. No worries, have fun.

**Comment by odeke-em** [comment]
I'll also page @veorq, if you get bored or have some free time, please feel free to take a look at the CL above posted :)

**Comment by henrydcase** [comment]
Hi, is there something I can do, so that it can get merged?

**Comment by henrydcase** [comment]
This is already done:
https://go-review.googlesource.com/c/crypto/+/111281/
