### ISSUE TITLE
proposal: cmd/go/internal/get: go get can parse go-source meta 

### ISSUE THREAD

**Issue by bensonfx** [golang/go#25393]
for example: if you download a pacakge: `go get golong.org/x/sys`   
the URL GET Method `golong.org/x/sys?go-get=1`  return 
two meta tag go-import and go-source.

so can we parse both of the two tags? 
and if golang.org/x/sys can not be connected,then try the go-source ?

**Comment by rsc** [comment]
No, go-import is for "go get". If other tools want other tags, fine, but go get will keep using "go-import", as it always has. Among other problems go-source doesn't even say which version control system to use.
