### ISSUE TITLE
cmd/compile: 'unexpected source op' spam in GOSSAFUNC output

### ISSUE THREAD

**Issue by mundaym** [golang/go#25404]
### What version of Go are you using (`go version`)?

Tip (`go version devel +212c9479e3 Tue May 15 16:29:04 2018 +0000 darwin/amd64`).

### Does this issue reproduce with the latest release?

No (tested 1.10.1).

### What operating system and processor architecture are you using (`go env`)?

`darwin/amd64`, but probably a universal issue.

### What did you do?

go get -u golang.org/x/crypto
cd $GOPATH/src/golang.org/x/crypto/internal/chacha20
GOSSAFUNC=\\(*Cipher\\).XORKeyStream go test -c

### What did you expect to see?

No extra output.

### What did you see instead?

```
...
unexpected at 2721:load with unexpected source op v3278unexpected at 2775:load with 
unexpected source op v3281unexpected at 2249:load with unexpected source op 
v3289unexpected at 2875:load with unexpected source op v3278unexpected at 2232:load 
with unexpected source op v286unexpected at 2231:load with unexpected source op v3291unexpected at 2784:load with unexpected source op v3289unexpected at 2785:load 
with unexpected source op v3291
...
```

This appears to be generated by https://github.com/golang/go/blob/212c9479e3a855bee05ffedda92c9be4405abb62/src/cmd/compile/internal/ssa/debug.go#L480. The unexpected op in question appears to always be a Phi.

**Comment by randall77** [comment]
@heschik

**Comment by heschik** [comment]
Thanks. There are three issues here:

- I forgot the newline at the end of the log message.
- The debug information should definitely understand a load from a phi.
- There's no context for the log message.

Most of the unexpected() calls have gone by the wayside in refactoring passes, so I could probably just convert these to log statements now.
