### ISSUE TITLE
cmd/go: build caching failed to notice cgo header changes

### ISSUE THREAD

**Issue by minux** [golang/go#25419]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +3868a371a8 Tue May 15 20:47:43 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### Example
Two files t.go and t.h are needed. t.go just calls a static function defined in t.h.
```
// t.go
package main

// #include "t.h"
import "C"

func main() {
	C.hello()
}

// t.h
#include <stdio.h>
static void hello() {
	printf("hello\n");
}
```

### Reproduction steps
go build ignores changes to the cgo header file.
```
$ go build t.go
$ ./t
hello
$ sed -i -e 's/"hello/&, world/' t.h    # modify t.h without changing t.go
$ go build t.go  # nothing is rebuild
$ ./t
hello   # output unchanged.
$ GODEBUG=gocacheverify=1 go build a.go  # didn't catch the problem
$ go clean -cache && go build t.go && ./t
hello, world   # clearing the build cache finally fixes the bug
```

### Discussion
Of course, changes like this is arguably hard for the Go tool to detect, and in fact, sometimes, we
don't want the Go tools to read all transitively required header files just to determine whether
to rebuild a package that uses cgo. However, the current behavior is very confusing, as it quietly
disregards changes to the header files, even the one in the package's directory.

I think we either should handle this completely (i.e. tap into gcc's -MM and handle changes to any transitively included files), or at least handle the directly included header file in Go source files (and make this problem clear in release notes.)

**Comment by alexd765** [comment]
Related Issue: [#19883](https://github.com/golang/go/issues/19883)
There we decided against becoming a C build system (your first solution).
Detecting changes in the same directory used to work though.

**Comment by minux** [comment]
But imagine this scenario.

I build a Go wrapper for C library libXYZ, whose header files is in
/usr/include/xyz.
I tested the current Go package successfully and decided to try updating
the libXYZ to a new version.
I updated the XYZ development library & header using OS package manager.

I then go test again. Due to build caching, the go command doesn't
recognize the headers
are changed. I got all test pass, and so I assumed that updating libXYZ
didn't break anything.

However, when I later change my Go package, I suddenly got cgo build error
due to incompatibilities
introduced in the new libXYZ header.

I do understand that we don't want to build a C build system, but I think
we need a way to prevent
surprises like this. Therefore, I propose that we check the header files
directly included in the Go
file or any C source/header file in the package directory for changes.

**Comment by AlexRouSg** [comment]
I don't think just checking the direct includes is very useful, that would require one to include every single relevant header manually and missing even one would cause the "surprise".

I think it would be more piratical to make it a habit to invoke `go clean -cache -testcache` after changing the headers. So I would suggest changing the docs to include that (preferably in bold) instead.

**Comment by ianlancetaylor** [comment]
Closing as dup of #24355 .
