### ISSUE TITLE
getting error when i compile go 1.4

### ISSUE THREAD

**Issue by prashantvidja** [golang/go#25413]
Hello,

### What version of Go are you using (`go version`)?
go 1.4

### Does this issue reproduce with the latest release?
first time install

### What operating system and processor architecture are you using (`go env`)?
debian(9)

### What did you do?
i want to compile first go1.4 for compile go1.10.1 because it is dependency of go1.10.1.
 after download go1.4.tar.gz direct I going to /src dir and run all.bash script.

>  root@debian:/opt/go-go1.4/src# ./all.bash
>  Building C bootstrap tool.
> cmd/dist
> 
>  Building compilers and Go bootstrap tool for host, linux/amd64.
> lib9
> libbio
> liblink
> cmd/cc
> cmd/gc
> cmd/6l
> cmd/6a
> cmd/6c
> /opt/go-go1.4/src/cmd/6c/txt.c: In function 'gmove':
> /opt/go-go1.4/src/cmd/6c/txt.c:995:28: error: left shift of negative value [-Werror=shift-negative-value]
>      f->vconst |= (vlong)~0 << 32;
>                             ^~
> /opt/go-go1.4/src/cmd/6c/txt.c:1045:28: error: left shift of negative value [-Werror=shift-negative-value]
>      f->vconst |= (vlong)~0 << 32;
>                             ^~
> cc1: all warnings being treated as errors
> go tool dist: FAILED: gcc -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fmessage-length=0 -c -m64 -I /opt/go-go1.4/include -I /opt/go-go1.4/src/cmd/6c -o $WORK/txt.o /opt/go-go1.4/src/cmd/6c/txt.c
> 

### What did you expect to see?
all test succeed.

### What did you see instead?
getting upper error.

thanks

**Comment by mvdan** [comment]
See https://golang.org/doc/install/source#go14 - have you been building the bootstrap version of Go 1.4?

**Comment by prashantvidja** [comment]
@mvdan  bootstrap version of Go 1.4 working for me.
@ALTree i just testing in amd64 but my requirement is for different-different architecture. so binary is not work for me.
thanks to both of you
