### ISSUE TITLE
very wired slice problem

### ISSUE THREAD

**Issue by crazytaxi824** [golang/go#25415]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.2 

### What operating system and processor architecture are you using (`go env`)?
mac 
darwin/amd64

### What did you do?

A link on play.golang.org is best.

correct
https://play.golang.org/p/Wn0zfDRxada

correct
https://play.golang.org/p/vy0bQK1D_Mz

wrong
https://play.golang.org/p/uY3T9M_JQ6K

### What did you expect to see?
[[1 2 3 4] [1 2 3 5] [1 2 3 6] [1 2 3 7] [1 2 3 8] ... ]

### What did you see instead?
[[1 2 3 10] [1 2 3 10] [1 2 3 10] [1 2 3 10] [1 2 3 10] [1 2 3 10] [1 2 3 10] [1 2 4 10] [1 2 4 10] [1 2 4 10] [1 2 4 10] [1 2 4 10] [1 2 4 10] [1 2 5 10] [1 2 5 10] [1 2 5 10] [1 2 5 10] [1 2 5 10] [1 2 6 10] [1 2 6 10] [1 2 6 10] [1 2 6 10] [1 2 7 10] [1 2 7 10] [1 2 7 10] [1 2 8 10] [1 2 8 10] [1 2 9 10] [1 3 4 10] [1 3 4 10] [1 3 4 10] [1 3 4 10] [1 3 4 10] [1 3 4 10] [1 3 5 10] [1 3 5 10] [1 3 5 10] [1 3 5 10] [1 3 5 10] [1 3 6 10] [1 3 6 10] [1 3 6 10] [1 3 6 10] [1 3 7 10] [1 3 7 10] [1 3 7 10] [1 3 8 10] [1 3 8 10] [1 3 9 10] [1 4 5 10] [1 4 5 10] [1 4 5 10] [1 4 5 10] [1 4 5 10] [1 4 6 10] [1 4 6 10] [1 4 6 10] [1 4 6 10] [1 4 7 10] [1 4 7 10] [1 4 7 10] [1 4 8 10] [1 4 8 10] [1 4 9 10] [1 5 6 10] [1 5 6 10] [1 5 6 10] [1 5 6 10] [1 5 7 10] [1 5 7 10] [1 5 7 10] [1 5 8 10] [1 5 8 10] [1 5 9 10] [1 6 7 10] [1 6 7 10] [1 6 7 10] [1 6 8 10] [1 6 8 10] [1 6 9 10] [1 7 8 10] [1 7 8 10] [1 7 9 10] [1 8 9 10] [2 3 4 10] [2 3 4 10] [2 3 4 10] [2 3 4 10] [2 3 4 10] [2 3 4 10] [2 3 5 10] [2 3 5 10] [2 3 5 10] [2 3 5 10] [2 3 5 10] [2 3 6 10] [2 3 6 10] [2 3 6 10] [2 3 6 10] [2 3 7 10] [2 3 7 10] [2 3 7 10] [2 3 8 10] [2 3 8 10] [2 3 9 10] [2 4 5 10] [2 4 5 10] [2 4 5 10] [2 4 5 10] [2 4 5 10] [2 4 6 10] [2 4 6 10] [2 4 6 10] [2 4 6 10] [2 4 7 10] [2 4 7 10] [2 4 7 10] [2 4 8 10] [2 4 8 10] [2 4 9 10] [2 5 6 10] [2 5 6 10] [2 5 6 10] [2 5 6 10] [2 5 7 10] [2 5 7 10] [2 5 7 10] [2 5 8 10] [2 5 8 10] [2 5 9 10] [2 6 7 10] [2 6 7 10] [2 6 7 10] [2 6 8 10] [2 6 8 10] [2 6 9 10] [2 7 8 10] [2 7 8 10] [2 7 9 10] [2 8 9 10] [3 4 5 10] [3 4 5 10] [3 4 5 10] [3 4 5 10] [3 4 5 10] [3 4 6 10] [3 4 6 10] [3 4 6 10] [3 4 6 10] [3 4 7 10] [3 4 7 10] [3 4 7 10] [3 4 8 10] [3 4 8 10] [3 4 9 10] [3 5 6 10] [3 5 6 10] [3 5 6 10] [3 5 6 10] [3 5 7 10] [3 5 7 10] [3 5 7 10] [3 5 8 10] [3 5 8 10] [3 5 9 10] [3 6 7 10] [3 6 7 10] [3 6 7 10] [3 6 8 10] [3 6 8 10] [3 6 9 10] [3 7 8 10] [3 7 8 10] [3 7 9 10] [3 8 9 10] [4 5 6 10] [4 5 6 10] [4 5 6 10] [4 5 6 10] [4 5 7 10] [4 5 7 10] [4 5 7 10] [4 5 8 10] [4 5 8 10] [4 5 9 10] [4 6 7 10] [4 6 7 10] [4 6 7 10] [4 6 8 10] [4 6 8 10] [4 6 9 10] [4 7 8 10] [4 7 8 10] [4 7 9 10] [4 8 9 10] [5 6 7 10] [5 6 7 10] [5 6 7 10] [5 6 8 10] [5 6 8 10] [5 6 9 10] [5 7 8 10] [5 7 8 10] [5 7 9 10] [5 8 9 10] [6 7 8 10] [6 7 8 10] [6 7 9 10] [6 8 9 10] [7 8 9 10]]

**Comment by mvdan** [comment]
You're re-using the backing arrays of slices, hence you are overwriting the parent slices instead of copying them and creating new ones. You should read https://blog.golang.org/go-slices-usage-and-internals. And in the future, for questions, see https://github.com/golang/go/wiki/Questions.
