### ISSUE TITLE
cmd/internal/obj/x86: VPERMPD invalid encoding and too permissive argument types

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#25420]
During fix of #24378 new issues were introduced due to shared ytab list between `VPERMPD` and `VPERMQ`:
1. <s>Like in #25418, encoding is invalid due to missing optab bytes. </s> (already fixed)
2. Initial issue was with "signed only" immediate arguments. Now it accepts both. Could only accept unsigned. (Read rationale below.)

If someone used negative args after CL100475, they would get invalid encoding. Their code is broken and they would've noticed that and, hopefully, reported an issue. Seems no one did that, maybe no one relied on negative arguments in their hand-coded asm or their code is not executed anymore. We could reduce "special permissive instructions" baggage by omitting this one at least until someone notices and reports that negative arguments stopped to compile (at this point, they should be happy, because if it was compiled before, it would behave in unpredictable way).

Because VEX and EVEX optabs and ytabs may soon be fully auto-generated, it's quite unfortunate to add more and more exceptions that make instruction args more permissive (Russ Cox would use "sloppy" word here, I think).

I also have a plan of leveraging immediate arg checks into deeper part of encoder to make it possible to report better errors than "invalid instruction" for immediate arg overflow or invalid signedness, so regardless of what we decide, the minimal solution is just fixing the invalid encoding problem before auto-generated tables are updated and then addressing the second issue separately, in a more clean way.

**Comment by TocarIP** [comment]
FWIW negative immediate helps with porting code from gnu as, which accepts both.

**Comment by mvdan** [comment]
My knowledge of assembly and of the assembler are limited, so apologies for breaking stuff. Of course, feel free to revert my commit - but it would be nice if the original issue remained fixed.

**Comment by Quasilyte** [comment]
@mvdan, I've CCed you to the CL just in case.

<details>

<summary>Offtop</summary>

It's actually me who should say "apologies", since I've missed that in initial CL during review.
The deal with y-tables and op-tables is not that straightforward, nor pretty..

Better yet, no one gives apologies and we just get things fixed. :)

</details>

**Comment by Quasilyte** [comment]
For keeping things in sync in both tip and avx512-enabled branches, I've made VPERMPD accept negative arguments as in the CL above.

If there are objections, they will can affect this decision.

**Comment by ianlancetaylor** [comment]
What is left to do on this issue?

**Comment by Quasilyte** [comment]
I believe it's resolved.

**Comment by Quasilyte** [comment]
(Seems like it can be safely closed.)
