### ISSUE TITLE
Golang-1.10 GOROOT requires manual export on Ubuntu Xenial

### ISSUE THREAD

**Issue by hollowaykeanho** [golang/go#25421]
### What version of Go are you using (`go version`)?
`go version go1.10 linux/amd64`

### Does this issue reproduce with the latest release?
`Yes`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/home/holloway/bin"
GOCACHE="/home/holloway/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/holloway"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build607283709=/tmp/go-build -gno-record-gcc-switches"
```
> Ubuntu Xenial (Vanila)
>
> http://ppa.launchpad.net/gophers/archive/ubuntu xenial main

### What did you do?
```
$ sudo add-apt-repository ppa:gophers/archive
$ sudo apt update -y
$ sudo apt install golang-1.10 -y
$ export PATH="/usr/lib/go-1.10/bin:$PATH"
$ vi <a poor go source code> # save it and let go metalinter to perform validation

securekey_test.go|6 col 2 warning| unused struct field could not import testing (cannot find package "testing" in any of: (structcheck)                         
securekey_test.go|34 col 4 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Errorf (structcheck)
securekey_test.go|38 col 3 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Logf (structcheck)
securekey_test.go|6 col 2 warning| unused variable or constant could not import testing (cannot find package "testing" in any of: (varcheck)
securekey_test.go|41 col 4 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Errorf (structcheck)
securekey_test.go|34 col 4 warning| unused variable or constant invalid operation: t (variable of type *invalid type) has no field or method Errorf (varcheck)
securekey_test.go|66 col 3 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Logf (structcheck)
securekey_test.go|38 col 3 warning| unused variable or constant invalid operation: t (variable of type *invalid type) has no field or method Logf (varcheck)
securekey_test.go|72 col 4 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Errorf (structcheck)
securekey_test.go|41 col 4 warning| unused variable or constant invalid operation: t (variable of type *invalid type) has no field or method Errorf (varcheck)
securekey_test.go|95 col 3 warning| unused struct field invalid operation: t (variable of type *invalid type) has no field or method Logf (structcheck)

$ export GOROOT="/usr/lib/go-1.10"
$ export PATH="$GOROOT/bin:$PATH"
$ vi <the same poor go source code> # save it to let go metalinter to perform validation
# no more error
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
`Follow all the $ commands in the above`

### What did you expect to see?
Go 1.10 is setup correctly, with `GOROOT` properly exported after installation. User only need to set `GOPATH`, `GOBIN` etc.

### What did you see instead?
Need to set and export `GOROOT` explicitly to ensure the the standard packages are found.

**Comment by agnivade** [comment]
This is an issue with the debian package itself. Go distributions expect they will be installed in `/usr/local/go`. For other locations like `/usr/lib/go-1.10`, you have to set it up yourself.

From the docs - https://golang.org/doc/install

> The Go binary distributions assume they will be installed in /usr/local/go (or c:\Go under Windows), but it is possible to install the Go tools to a different location. In this case you must set the GOROOT environment variable to point to the directory in which it was installed.

**Comment by davecheney** [comment]
You should not need to set GOROOT. However this project does not manage the Ubuntu and Debian packages. You will have to raise the issue with them. Sorry.

**Comment by hollowaykeanho** [comment]
@davecheney, noted. Appreciate if this ticket to be reopened until I've transfer the ticket to launchpad please? 

I'll close the ticket once the transfer is completed. NOTE: I'm not the only person facing the issue.

**Comment by hollowaykeanho** [comment]
After working with Michael Hudson-Doyle, the ppa maintainer. We found that this issue is completely not related to the deb package.

1. the metalinter issue was caused by the metalinter package itself, and it requires https://github.com/alecthomas/gometalinter/commit/0725fc6d498fd2e3b633d24256604c2fbe161bbc which was committed 11 days ago from this post. Updating the metalinter package with that commit will solve the issue.

2. Unknown issue with `go get -u`. I'm no longer be able to reproduce the issue with go get update after performing a mass package update `go get -u $GOPATH/src/...`, including the issue above.

Since the guide in https://github.com/golang/go/wiki/Ubuntu only spells how to install but not on how to update, I'll list the notes here in case any ubuntu user wants to update their golang in the future.

```bash
$ sudo apt remove golang1.X # old version
$ sudo apt update -y
$ sudo apt install golang1.Y # new version
$ export PATH="/usr/lib/golang-1.Y/bin:$PATH"  # to get go and gofmt into your bin list
$ export GOROOT="/usr/lib/golang-1.Y" # temporarily for mass update.
$ go get -u "$GOPATH/src/..." # update all packages
```
This should prevent any future metalinter or linter issue that cause this problem at the first place.
Restart your terminal without the `export GOROOT`. Your go should be fine.

**Comment by hollowaykeanho** [comment]
@davecheney, the export listed here is meant for problem No. 2, and for other 3rd party packages carrying the same issue like metalinter did (until they fix the problem).

I'm currently using `go` without needing to export `GOROOT` after the mass update, AFAIK, from deb packaging standpoint, the go package is installed correctly with the custom path. I agree to you, that you don't need to export `GOROOT` explicitly.

However, I disagree not to export `GOROOT` temporarily before the mass updates because that's assuming all 3rd party tool packages are not repeating what metalinter did.

**Comment by dolmen** [comment]
I wonder if you have 2 different versions of Go and a mismatch between GOPATH and GOROOT.
The report should mention the output of the following commands before and after installing `golang-1.10`:
```
go env GOROOT
which go
```
