### ISSUE TITLE
panic in reflect/value.go:CanInterface

### ISSUE THREAD

**Issue by AlexStocks** [golang/go#25437]
**What version of Go are you using (go version)?**
go1.10.2(darwin/amd64)

**What did you do?**
https://github.com/golang/go/blob/c3d10e64b91652bf2a65411b2cac9ed7797fb53f/src/reflect/value.go#L934
The remark of function CanInterface says it will “without panicking”. However, the function used panic.

**What did you expect to see?**
delete the panic clause.

**Comment by cznic** [comment]
> delete the panic clause.

The panic is about an invalid zero value of the receiver. Removing it would make the method lie. Also, the "without panic" clearly documents the behavior of the `Interface` method, not of the `CanInterface` method.

**Comment by AlexStocks** [comment]
@cznic Thank you.
