### ISSUE TITLE
docs: document standard way to recognize machine generated files

### ISSUE THREAD

**Issue by nhooyr** [golang/go#25433]
in https://github.com/golang/go/issues/13560#issuecomment-288494154 bradfitz said the wiki would be edited but I can't seem to find anything on the wiki or even googling `golang standard comment on machine generated files`. Only the original issue comes up. We should document it somewhere appropriate.

Maybe https://blog.golang.org/generate could be updated to mention it?

**Comment by smasher164** [comment]
Additionally, I think the go tool documentation is a good place to mention this.
https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source
Something along the lines of:

> To convey to humans and machine tools that code is generated, outputted source should have a line in the file that matches the following regular expression (in Go syntax):
`^// Code generated .* DO NOT EDIT\.$`

**Comment by shurcooL** [comment]
> in #13560 (comment) bradfitz said the wiki would be edited but I can't seem to find anything on the wiki

He said:

> The wiki seems like it would just be edited by somebody without discussion.

Meaning that the wiki might not be an appropriate place to put it, since it can be edited by anyone.

The current canonical documentation is the comment by Rob Pike in that issue, with the https://golang.org/s/generatedcode link pointing to it.

**Comment by nhooyr** [comment]
> Meaning that the wiki might not be an appropriate place to put it, since it can be edited by anyone.

Ah, I interpreted it as the wiki would be edited to link to Rob's comment without any need for a discussion.

**Comment by robpike** [comment]
Closed by  https://golang.org/cl/118756
