### ISSUE TITLE
install: Can't see Go version on SUSE Linux 

### ISSUE THREAD

**Issue by SreekanthSimplyfi** [golang/go#25440]
Please answer these questions before submitting your issue. Thanks!

### What did you do?
Installed Go Lang

If possible
<img width="628" alt="screen shot 2018-05-17 at 6 18 20 pm" src="https://user-images.githubusercontent.com/25745802/40178297-bcb315a6-59fe-11e8-97ba-588a86e2478b.png">
, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Install Go Lang 

### What did you see instead?
While checking version it's showing error
**Error : -bash: /usr/local/go/bin/go: cannot execute binary file: Exec format error**

**Comment by agnivade** [comment]
How did you install Go ? Did you take the correct binary distribution from https://golang.org/dl/ ?

Please give output of `uname -a` and `file  /usr/local/go/bin/go`.

**Comment by SreekanthSimplyfi** [comment]
i installed following the official link.. but the final step tells me ive been facing a error of "binary execution error" .. and realistically im using on susi linux..

**Comment by agnivade** [comment]
Which distribution did you download from https://golang.org/dl/ page ?

Please give the output from `uname -a` and `file  /usr/local/go/bin/go`.

Thanks.

**Comment by SreekanthSimplyfi** [comment]
I have download GoLang from https://golang.org/dl/ .I'm following the official link https://docs.google.com/document/d/1Wm7eFA97HaXaoo98pI7t61rxmJXfKmrrJ7nIjRuo6BE/edit .. but the final step tells me i've been facing a error of "binary execution error" .
uname -a :- **Linux sfhyperledger 4.4.103-94.6-default #1 SMP Tue Jan 9 12:53:49 UTC 2018 (69ac2b4) s390x s390x s390x GNU/Linux**
file /usr/local/go/bin/go :- -bash: cd: /usr/local/go/bin/go: Not a directory

**Comment by agnivade** [comment]
Your arch is s390x. You have downloaded binaries for amd64. You have to download https://dl.google.com/go/go1.10.2.linux-s390x.tar.gz. 

Please follow https://golang.org/doc/install#install in future. Thanks.

**Comment by SreekanthSimplyfi** [comment]
@agnivade Thanks dude

**Comment by SreekanthSimplyfi** [comment]
When running the go build command it's getting exec: see below image
<img width="457" alt="screen shot 2018-05-21 at 5 13 55 pm" src="https://user-images.githubusercontent.com/25745802/40305954-65dd7b76-5d1a-11e8-96c7-4c57ab63b2f9.png">

**Comment by agnivade** [comment]
This looks like an an issue with your environment rather than a bug. We do not use the issue tracker for general discussions or questions like these. Please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.
