### ISSUE TITLE
cmd/go: cannot use map index special form in return statements

### ISSUE THREAD

**Issue by jamie-digital** [golang/go#25442]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
all

### What did you do?
When storing the results into two variables, the special form of a map index operation can return two parts. The same is not true in a return statement, even when the function signature makes this unambiguous.

https://play.golang.org/p/mmJ8ZlWC2yn

### What did you expect to see?
I would expect `CheckCache_works` and `CheckCache_shouldWork` to function identically.

### What did you see instead?
gc refuses to compile the return statement, saying:

```
prog.go:15:2: not enough arguments to return
	have (int)
	want (int, bool)
```

Apologies if this duplicates a previous issue. I found searching for and naming this issue pretty hard.

**Comment by ianlancetaylor** [comment]
That is how the language works, as defined by the language spec (https://golang.org/ref/spec).  The special `, ok` form of a map index is only available in an assignment or initialization, as documented at https://golang.org/ref/spec#Index_expressions .

If you want to propose that the language be changed, please follow the proposal process documented at https://github.com/golang/proposal/blob/master/README.md .  Thanks.
