### ISSUE TITLE
x/playground: running this program does not display output

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25455]
After introducing the "vet" tool into playground the program below does not work. It holds forever with the message:  `Waiting for remote server...`

```
package main

import (
	"fmt"
)

func main() {
	return
	fmt.Println("Hello, playground\n")
}
```

Both of endpoints (`/compile` and `/vet`) return responses. The problem lies in the JS code.

**Comment by ysmolsky** [comment]
PTAL @andybons

**Comment by andybons** [comment]
@ysmolsky I would ping me on the review itself, not the issue.

**Comment by ysmolsky** [comment]
Right on, next time I will do that. 
It's just from my experience that pings on reviews work worse :-)
