### ISSUE TITLE
Cgo: cannot access struct field called `type`

### ISSUE THREAD

**Issue by jech** [golang/go#25458]
go version go1.10.1 linux/amd64

I'm using a C library that manipulates a struct that has a field called `type`.  I see no way to access the field without going through a wrapper function written in C.

Here's a fairly minimal example that reproduces the problem:

    /*
    struct foo {
        int type;
    };
    */
    import "C"

    func foo_type (x *C.struct_foo) int
        return int(x.type);
    }

**Comment by AlexRouSg** [comment]
https://golang.org/cmd/cgo/

> Within the Go file, C's struct field names that are keywords in Go can be accessed by prefixing them with an underscore: if x points at a C struct with a field named "type", x._type accesses the field. C struct fields that cannot be expressed in Go, such as bit fields or misaligned data, are omitted in the Go struct, replaced by appropriate padding to reach the next field or the end of the struct.

**Comment by agnivade** [comment]
Working as intended.

**Comment by jech** [comment]
> Working as intended.

And there's no workaround, other than a wrapper in C?

**Comment by jech** [comment]
>     Within the Go file, C's struct field names that are keywords in Go can be
>     accessed by prefixing them with an underscore:

Thanks, that answers my issue.
