### ISSUE TITLE
Error getting FormValue in MultipartForm request in Go 1.10

### ISSUE THREAD

**Issue by itopt** [golang/go#25457]
Hello!
In version 1.9, I had no problem getting the FormValue in http request. 
After upgrading to version Go 1.10 of FormValue is empty. Did I find the error? in module:
mine/multipart/formdata.go
_before_:
_, hasContentTypeHeader := p.Header["Content-Type"]
if !hasContentTypeHeader && filename == "" 
_after_ 
_, hasContentTypeHeader := p.Header["Content-Type"]
if hasContentTypeHeader && filename == "" // del !
began to work as I need

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
