### ISSUE TITLE
x/playground: in About text, document that vet is used

### ISSUE THREAD

**Issue by meirf** [golang/go#25462]
Now that [vet is included in playground Run](https://github.com/golang/playground/commit/da85333e5bb1b5a5b219ea36384523c0a1e1e440#diff-8bf7e4af1b856e9316fc40acfe592c8a), the [About text](https://github.com/golang/playground/blob/da85333e5bb1b5a5b219ea36384523c0a1e1e440/edit.html#L134-L203) should mention it.

Current:

> The service receives a Go program, compiles, links, and runs the program inside a sandbox, then returns the output.

Maybe something like "... receives a Go program, compiles, links, [vet](https://golang.org/cmd/vet/)s and runs the program inside a sandbox..."

@ysmolsky 

One counterargument is that "go vet" is a pretty unique search query and goes straight to https://golang.org/cmd/vet anyway.

**Comment by ysmolsky** [comment]
I think we should do this. Preparing the patch.

**Comment by dmitshur** [comment]
I've deployed the new version. Thanks @ysmolsky!
