### ISSUE TITLE
x/website: blog, tour, and other sites not mirrored on golang.google.cn

### ISSUE THREAD

**Issue by ljhm** [golang/go#25466]
the content of “blog.golang.org”, “tour.golang.org” not found on golang.google.cn though.
can’t the whole golang.org be mirrored on golang.google.cn?

network traffic in china may get monitored if site names like google are keyed in browser address bar.
we just try the best to not doing that.

domain names like golang.cn, golang.org.cn will be better.

**Comment by jamalc** [comment]
Do the URLs "golang.google.cn/tour" and "golang.google.cn/blog" not work?
