### ISSUE TITLE
runtime/pprof: links to pprof documentation outdated

### ISSUE THREAD

**Issue by tumdum** [golang/go#25477]
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tumdum/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tumdum/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build079040877=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
Clicked link https://github.com/google/pprof/blob/master/doc/pprof.md on https://golang.org/pkg/runtime/pprof/

### What did you expect to see?

Documentation of pprof.

### What did you see instead?

Empty page (404).

Most likely the correct link should now be https://github.com/google/pprof/blob/master/doc/README.md

**Comment by ALTree** [comment]
@tumdum want to send a patch?

**Comment by tumdum** [comment]
I would like to, but I never built go from source and I don't have anything setup out of stuff described in [Contribution Guide](https://golang.org/doc/contribute.html) - it will most likely take me few days to set it all up.

**Comment by ALTree** [comment]
No problem, I'll do it.
