### ISSUE TITLE
cmd/doc: duplicated component in package path confounds partial package matching

### ISSUE THREAD

**Issue by splace** [golang/go#25478]
### What version of Go are you using (`go version`)?
1.10.2
### What operating system and processor architecture are you using (`go env`)?
linux/amd64
### What did you do?
go get github.com/go-gl/gl/v3.3-core/gl
go doc gl  
### What did you expect to see?
documentation for gl package
### What did you see instead?
doc: no buildable Go source files in ../go/src/github.com/go-gl/gl
exit status 1
(notice path truncated)

temp fixed by renaming /go/src/github.com/go-gl/gl -> /go/src/github.com/go-gl/GL

**Comment by AlexRouSg** [comment]
If you just call `go doc gl` there would be no way for it to know which gl package you meant so it just selects the first found "package" and that so happens to be `github.com/go-gl/gl` which contains no source files.

So the proper way to use `go doc` would be to use the full import path `go doc github.com/go-gl/gl/v3.3-core/gl`

**Comment by splace** [comment]
understood, and this isn't hugely important, but i do think go's tooling is one of its bright points, so..

"github.com/go-gl/gl" isn't even a package, there is only one package 'gl' installed, doesn't seem that hard for it to just keep going until it found a package, or, seems like a tree search leaf first would work, mostly.

also; if i already had a package 'gl' which was reporting documentation with 'gl', installing the above package, as a side-effect, breaks that, that's surprising to me, i would have hoped package installation was completely isolated. in some sort of shared development environment i might not be aware of other installs until it breaks.

**Comment by bcmills** [comment]
Seems like it should be a fairly simple fix: if the directory suffix matches but the path can't be imported, keep searching.

Some starting points, if you'd like to give it a try:
https://github.com/golang/go/blob/5776bd558fd0cfe40c71dac549db148ea16c0fce/src/cmd/doc/main.go#L242-L247
https://github.com/golang/go/blob/5776bd558fd0cfe40c71dac549db148ea16c0fce/src/cmd/doc/main.go#L341-L357
