### ISSUE TITLE
Feature: provide no-copy conversion from []byte to string

### ISSUE THREAD

**Issue by tliron** [golang/go#25484]
If you read bytes from an `io.Reader`, but need them as a `string`, then you're going to have to convert. And that will cost you memory as data is copied between quite different variables.

Annoyed by this waste, some of us has been doing things like this:
```
func BytesToString(bytes []byte) string {
	sliceHeader := (*reflect.SliceHeader)(unsafe.Pointer(&bytes))
	stringHeader := reflect.StringHeader{Data: sliceHeader.Data, Len: sliceHeader.Len}
	return *(*string)(unsafe.Pointer(&stringHeader))
}
```
Of course, proper use requires you to never change the original byte array, but that's a reasonable contract in many cases.

First, I would like to know if there are any repercussions to this usage. I'm always nervous about using `unsafe`, but in this case it seems to adhere to the spec, and also I can't foresee any problems with garbage collection. But maybe I'm missing something important. I've been using this a lot and have not seen any issues.

Second, assuming this code is A-OK, then why not provide something like this in the standard library? (Probably in the `bytes` package.) It could allow for significant memory savings for programs that read a lot of text.

**Comment by randall77** [comment]
That's not quite the right way to do it.  See the description at the end of package `unsafe`'s description. (TL;DR don't declare variables of type `reflect.SliceHeader` or `reflect.StringHeader`, use variables of type `*reflect.SliceHeader` and `*reflect.StringHeader` instead.) But in general, if you want to do this in your code, go for it.  #19367 is a proposal to make this a bit nicer/safer.

We don't want to provide this functionality (unsafe-converting a `[]byte` to `string`) in the standard library because it lets people create mutable strings.  Lots of packages assume strings are immutable, and may behave badly if the strings are mutable.  For instance, maps with mutable string keys will behave badly.  We'd rather not encourage those kinds of bugs, even if you can do it yourself.

If and when we do #19367, adding copy-free `[]byte` to `string` would be an easy additional `unsafe` operation.  But maybe we just keep letting people do that themselves.

**Comment by bcmills** [comment]
As @randall77 notes, this would have to live in the `unsafe` package (because it is unsafe in general). As such, closing as a dup of #19367.

**Comment by tliron** [comment]
I understand the concern, but this just seems to be such a common use case with very obvious gains. I understand that Go is focused more on engineering practicality than language correctness.

Since we already have an `unsafe` package, how about adding this function there? Is that the point of  #19367? By having it in `unsafe` users should be clear as to what they're getting into (*potentially* immutable strings).

Here's my new way to do it by avoiding an instance of `reflect.StringHeader`. Does this look right?
```
func BytesToString(bytes []byte) string {
	sliceHeader := (*reflect.SliceHeader)(unsafe.Pointer(&bytes))
	return *(*string)(unsafe.Pointer(&reflect.StringHeader{
		Data: sliceHeader.Data,
		Len:  sliceHeader.Len,
	}))
}
```
It's actually subtly tricky to ensure that the byte slice doesn't get GC'ed. I took into account the comment [here](https://github.com/m3db/m3x/blob/c84f0c59d87c038ff0a940c6d791cb2a85203b59/unsafe/string.go#L41) to do it all in one line.

**Comment by randall77** [comment]
I think this is safer.
```
func BytesToString(bytes []byte) (s string) {
	slice := (*reflect.SliceHeader)(unsafe.Pointer(&bytes))
	str := (*reflect.StringHeader)(unsafe.Pointer(&s))
	str.Data = slice.Data
	str.Len = slice.Len
}
```
That way you're never allocating an instance of `reflect.StringHeader`.

**Comment by tliron** [comment]
Thanks, but that doesn't compile in go1.10.2. Is it even possible to do `&` on implicit returns?

**Comment by randall77** [comment]
Ah, I forgot a final "return".
Yes, you can take the address of named return values.
Your version is fine as well.

**Comment by bcmills** [comment]
With the missing return, it seems to work:
https://play.golang.org/p/36sWGSvYFyV

FWIW, you can also write it without referring to `reflect.SliceHeader`:
https://play.golang.org/p/0if5Nj9RH1z

**Comment by tliron** [comment]
Thanks! Here's my final version with [one more little optimization](https://play.golang.org/p/GZZzpLa31NC).

See, the subtleties of getting this right are exactly why this should be a std func.

**Comment by go101** [comment]
The `BytesToString` function above is not safe under current unsafe rules.
It needs a `KeepAlive` line:

```golang
func BytesToString(bytes []byte) (s string) {
	slice := (*reflect.SliceHeader)(unsafe.Pointer(&bytes))
	str := (*reflect.StringHeader)(unsafe.Pointer(&s))
	str.Data = slice.Data
	str.Len = slice.Len
	runtime.KeepAlive(&bs) // this line is essential.
	return s
}
```

**Comment by go101** [comment]
@bcmills 
yes, the way used by string.Builder
```golang
func ByteSlice2String(bs []byte) string {
	return *(*string)(unsafe.Pointer(&bs))
}
```
is a more efficient way.
