### ISSUE TITLE
x/sys/windows: Get windows service process id

### ISSUE THREAD

**Issue by pytimer** [golang/go#25485]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
go environment

```sh
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
```

### What did you do?

I am call windows api to get the specified name service status, include service process id.

### What did you expect to see?

I expected golang/sys/windows package have QueryServiceStatusEx() function, it will return service status include process id.

### What did you see instead?

Now golang/sys/windows package only have QueryServiceStatus() function, it not return pid.

So i want to call  QueryServiceStatusEx()  get service process id, but no function to implement it currently.I am write code to implement in my project, this feature whether need to add golang/sys/windows package?

Thanks for any help! :)

**Comment by pytimer** [comment]
Thank you for your reply. 
I will try to do this. if it is hard, i will tell you. :)

**Comment by pytimer** [comment]
@alexbrainman I am already submit PR to fix this issue.

https://go-review.googlesource.com/#/c/sys/+/114215

It is my first submit PR for golang/go, is there a problem with the push operation?
If something wrong, i hope you can point out and i will fix it.

Thanks. :)

**Comment by alexbrainman** [comment]
> It is my first submit PR for golang/go, is there a problem with the push operation?
> If something wrong, i hope you can point out and i will fix it.

I just reviewed your CL, it was all fine. Please adjust your CL as per my instructions.

Thank you.

Alex

**Comment by pytimer** [comment]
Thanks. :)

I have some things for now, and i will fix it on this week.
Sorry.

**Comment by pytimer** [comment]
@alexbrainman . I fix my CL according to your and Tobias Klauser instructions.

Please check my CL if you have free time.
https://go-review.googlesource.com/#/c/sys/+/114215

Thanks.

**Comment by alexbrainman** [comment]
> I fix my CL according to your and Tobias Klauser instructions.

Cool.

> Please check my CL if you have free time.

Will do.

Alex
