### ISSUE TITLE
cmd/go: unable to get `golang.org/x/...` packages

### ISSUE THREAD

**Issue by GonchuB** [golang/go#25495]
I am unable to get packages hosted in go.googlesource.com, I can't even clone the repositories by hand, getting the same error.

### What version of Go are you using (`go version`)?
go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sanz/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sanz/go"
GORACE=""
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.10.2/libexec/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build001979355=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
```sh
$ go get -u golang.org/x/crypto/bcrypt
```

### What did you expect to see?
I expected to get crypto installed

### What did you see instead?

```sh
go get -u -v golang.org/x/crypto/bcrypt
Fetching https://golang.org/x/crypto/bcrypt?go-get=1
Parsing meta tags from https://golang.org/x/crypto/bcrypt?go-get=1 (status code 200)
get "golang.org/x/crypto/bcrypt": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/bcrypt?go-get=1
get "golang.org/x/crypto/bcrypt": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
# cd .; git clone https://go.googlesource.com/crypto /home/sanz/go/src/golang.org/x/crypto
Cloning into '/home/sanz/go/src/golang.org/x/crypto'...
fatal: unable to access 'https://go.googlesource.com/crypto/': Unrecognized content encoding type. libcurl understands identity content encodings.
package golang.org/x/crypto/bcrypt: exit status 128
```

**Comment by GonchuB** [comment]
@agnivade have the latest curl and git versions, no proxies. I can clone git repositories from github, but not from go.googlesource.com:

```sh
$ curl --version
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2o
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets HTTPS-proxy
```

```sh
$ git --version
git version 2.17.0

```

**Comment by davecheney** [comment]
> Other people in my company are getting the same issue since Sunday

Does the issue only occur inside your company? You may need to talk to your network administrators and check that they are not filtering your traffic.

**Comment by GonchuB** [comment]
@davecheney I am working remotely, we are in different countries/buildings. I am not filtering my traffice :)

**Comment by GonchuB** [comment]
Output of plain curl
```sh
$ curl https://golang.org/x/crypto
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="golang.org/x/crypto git https://go.googlesource.com/crypto">
<meta name="go-source" content="golang.org/x/crypto https://github.com/golang/crypto/ https://github.com/golang/crypto/tree/master{/dir} https://github.com/golang/crypto/blob/master{/dir}/{file}#L{line}">
<meta http-equiv="refresh" content="0; url=https://godoc.org/golang.org/x/crypto">
</head>
<body>
Nothing to see here; <a href="https://godoc.org/golang.org/x/crypto">move along</a>.
</body>
</html>
``

**Comment by ysmolsky** [comment]
@GonchuB what was the fix for you?

**Comment by GonchuB** [comment]
Some keg (using linuxbrew) installed git and curl as a dependency, so those binaries were being used instead of the system ones. Apparently they were not working correctly (it is odd, because they worked correctly with github repos and go packages) but not with go.googlesource ones. Uninstalled git and curl kegs and issue was solved

**Comment by ysmolsky** [comment]
I am glad to hear that you found the solution!

**Comment by agnivade** [comment]
Wow, weird indeed.

**Comment by the-codetrane** [comment]
@GonchuB Thank you for saving me hours of banging my head against the wall! Just had (and resolved) the same issue.
