### ISSUE TITLE
cmd/go: pkg-config's with "-D_THREAD_SAFE" are unbuildable

### ISSUE THREAD

**Issue by jmhodges** [golang/go#25493]
### What version of Go are you using (`go version`)?

1.10.2

### Does this issue reproduce with the latest release?

yep

### What operating system and processor architecture are you using (`go env`)?

macOS 10.13.4

### What did you do?

Building a package that requires the C implementation of protobuf with cgo and `// #cgo pkg-config: protobuf`. I installed protobuf using Homebrew and protobuf's pc file includes the line

```
Libs: -L${libdir} -lprotobuf -D_THREAD_SAFE
```

This seems to be added by the protobuf project's own configure scripts for protobuf 3.5.1. (Current protobuf master fixes this. I suspect it was fixed by the long-lived but only recently merged https://github.com/google/protobuf/pull/1333 patch)

### What did you expect to see?

A successful build

### What did you see instead?

```
go build github.com/jmhodges/gocld3/cld3: invalid flag in pkg-config --libs: -D_THREAD_SAFE
```

**Comment by jmhodges** [comment]
To close part of these loops, I confirmed that applying https://github.com/google/protobuf/pull/1333 did fix this issue for me. The very old autogen tooling that protobuf had was creating the no longer relevant flag.

If folks want to use it in homebrew themselves, while we wait for the 3.6 release that is [estimated to land later this month](https://groups.google.com/d/msg/protobuf/obDXg92GKxY/QTshedrsBgAJ), you can add


```
  patch do
    url "https://patch-diff.githubusercontent.com/raw/google/protobuf/pull/1333.diff"
    sha256 "80bd40e7aa561cf22a34ba3aa86d7cd55bc866e689d6e4a633049f17ecf3fbdc"
  end
```

to your `protobuf.rb` formula. (If you don't know where that is, hit `brew edit protobuf`.)

**Comment by bcmills** [comment]
Per https://github.com/golang/go/wiki/InvalidFlag, does it build with
`CGO_LDFLAGS_ALLOW=-D_THREAD_SAFE` set in the environment?

**Comment by ianlancetaylor** [comment]
Basically, we don't expect `pkg-config --libs` to contain a `-D` option.  There's no obvious reason for the option, since it won't affect linking.  If it's fixed on protobuf master then I don't think there is anything to do here.  The older package is usable with the environment variable.
