### ISSUE TITLE
access: GitHub ("go-approvers")

### ISSUE THREAD

**Issue by oiooj** [golang/go#25502]
See https://golang.org/wiki/GithubAccess

Since I often want to edit the issue on github, I apply for the following authority:

https://github.com/orgs/golang/teams/go-assignees
https://github.com/orgs/golang/teams/go-approvers

GitHub account: oiooj

With this accesse, I can help out with Gardening on GitHub issues related to vgo. 
@bradfitz @andybons

**Comment by ianlancetaylor** [comment]
Done.
