### ISSUE TITLE
cmd/go: vgo version shows incorrect version

### ISSUE THREAD

**Issue by komuw** [golang/go#25514]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.10 linux/amd64`

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="~/go"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build427797830=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
```bash
go get -u golang.org/x/vgo && \
vgo version
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I expected to see an updated vgo version

### What did you see instead?
`go version go1.10 linux/amd64 vgo:2018-02-20.1` 

the version displayed is the one hard coded at; https://github.com/golang/vgo/blob/b39cea3cb5353f4fc7f08919d32a0006ea3ed62a/vendor/cmd/go/internal/version/version.go#L16

**Comment by agnivade** [comment]
I am not sure whether this should be considered as a bug. Most probably, it was supposed to be a debug string to differentiate between go and vgo commands. It will anyways go away once vgo is integrated within go.

/cc @rsc , @kardianos

**Comment by myitcv** [comment]
Just for the record (not an opinion on whether this should be fixed or not), the canonical way we have been gathering more specific information to help debug issues in the `#vgo` Slack channel is via:

```
(command cd $(go list -f "{{.Dir}}" golang.org/x/vgo); git rev-parse HEAD)
```
