### ISSUE TITLE
runtime: gcWriteBarrier implementations assume argument slots are immutable

### ISSUE THREAD

**Issue by mundaym** [golang/go#25512]
`gcWriteBarrier` currently promises to preserve all general purpose registers. It does this by saving the general purpose registers to the stack. However it saves its arguments into the argument slots for `gcBufFlush` and then restores them from the same slots. This isn't technically correct. As @randall77 mentioned in [this post](https://groups.google.com/d/msg/golang-dev/8RywCWxHVYA/ET4NyOipCQAJ):

> The Go calling convention allows the callee to modify the argument slots on the stack.  The caller must not assume that they are unmodified across a call.
> The compiler does in fact use the argument slots for spill locations.  For example:
```go
func f(x int) int {
	x++
	runtime.GC()
	return x
}
```
> The x+1 value will be spilled to x's argument slot across the runtime.GC() call.

This should probably be fixed for correctness. We could either mark `gcWriteBarrier` as clobbering its argument registers and then not bothering to restore them at all or we can save them to the stack somewhere else.

Examples of unsafe restores:

amd64:

https://github.com/golang/go/blob/5776bd558fd0cfe40c71dac549db148ea16c0fce/src/runtime/asm_amd64.s#L1451-L1455

s390x:

https://github.com/golang/go/blob/5776bd558fd0cfe40c71dac549db148ea16c0fce/src/runtime/asm_s390x.s#L862-L865

**Comment by cherrymui** [comment]
I remember @aclements and I talked about this in the review of the buffered write barrier CL or somewhere. We decided this was ok. wbBufFlush was special enough and we can carefully code it so the argument slots are not clobbered. Probably still good to have a comment.
