### ISSUE TITLE
syscall: syscall.FD_CLOEXEC is not equal with syscall.O_CLOEXEC

### ISSUE THREAD

**Issue by hustcat** [golang/go#25515]
Why `syscall.FD_CLOEXEC` is not equal with `syscall.O_CLOEXEC`？However,  `FD_CLOEXEC` is equal with `O_CLOEXEC` in glibc.

In go:

```
    fmt.Printf("FD_CLOEXEC=%x\n", syscall.FD_CLOEXEC)
    fmt.Printf("O_CLOEXEC=%x\n", syscall.O_CLOEXEC)
    fmt.Printf("O_NONBLOCK=%x\n", syscall.O_NONBLOCK)

FD_CLOEXEC=1
O_CLOEXEC=80000
O_NONBLOCK=800
```

In glibc:

```
#include <sys/eventfd.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>

int main(int argc, char *argv[]){
    printf("EFD_NONBLOCK=%x\n", EFD_NONBLOCK);
    printf("O_NONBLOCK=%x\n", O_NONBLOCK);
    printf("EFD_CLOEXEC=%x\n", EFD_CLOEXEC);
    printf("O_CLOEXEC=%x\n", O_CLOEXEC);
}

EFD_NONBLOCK=800
O_NONBLOCK=800
EFD_CLOEXEC=80000
O_CLOEXEC=80000
```

And more, why `EFD_NONBLOCK` is not exist in go?

### What version of Go are you using (`go version`)?

```
# go version     
go version go1.7.1 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/go"
GORACE=""
GOROOT="/usr/local/go_1.7.1"
GOTOOLDIR="/usr/local/go_1.7.1/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build674153237=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by tklauser** [comment]
> And more, EFD_NONBLOCK is not exist in go.

`EFD_NONBLOCK` is part of `golang.org/x/sys/unix` which should be used instead of package `syscall`.

**Comment by tklauser** [comment]
Also, the given C program is checking the `EFD_*` constants while the Go program tests the `FD_*` constants. These are different things. As I see it, the current values of `FD_CLOEXEC` and `FD_NONBLOCK` match the respective values in glibc. `FD_CLOEXEC` is not the same value as `O_CLOEXEC` in glibc either, i.e. it matches the values in package `syscall`:

```
cat foo.c && gcc foo.c && ./a.out
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>

int main(int argc, char *argv[]){
	printf("FD_CLOEXEC=%x\n", FD_CLOEXEC);
	printf("O_CLOEXEC=%x\n", O_CLOEXEC);
}

FD_CLOEXEC=1
O_CLOEXEC=80000
```
