### ISSUE TITLE
x/sys/unix: TestDevices test fails on Solaris

### ISSUE THREAD

**Issue by hyangah** [golang/go#25528]
Discovered when the package was vendored and tested by builders.
This broke both Solaris builders.

https://build.golang.org/log/7c8e4f372950715426cac40c9a124602804df843

--- FAIL: TestDevices (0.00s)
    --- FAIL: TestDevices//dev/zero_134:12 (0.00s)
    	dev_solaris_test.go:41: for /dev/zero Major(0x840000000c) == 132, want 134
    	dev_solaris_test.go:47: for /dev/zero Mkdev(134, 12) == 0x860000000c, want 0x840000000c
    --- FAIL: TestDevices//dev/null_134:2 (0.00s)
    	dev_solaris_test.go:41: for /dev/null Major(0x8400000002) == 132, want 134
    	dev_solaris_test.go:47: for /dev/null Mkdev(134, 2) == 0x8600000002, want 0x8400000002
    --- FAIL: TestDevices//dev/ptyp0_172:0 (0.00s)
    	dev_solaris_test.go:41: for /dev/ptyp0 Major(0xa900000000) == 169, want 172
    	dev_solaris_test.go:47: for /dev/ptyp0 Mkdev(172, 0) == 0xac00000000, want 0xa900000000
    --- FAIL: TestDevices//dev/ttyp0_175:0 (0.00s)
    	dev_solaris_test.go:41: for /dev/ttyp0 Major(0xac00000000) == 172, want 175
    	dev_solaris_test.go:47: for /dev/ttyp0 Mkdev(175, 0) == 0xaf00000000, want 0xac00000000
    --- FAIL: TestDevices//dev/ttyp1_175:1 (0.00s)
    	dev_solaris_test.go:41: for /dev/ttyp1 Major(0xac00000001) == 172, want 175
    	dev_solaris_test.go:47: for /dev/ttyp1 Mkdev(175, 1) == 0xaf00000001, want 0xac00000001

**Comment by bradfitz** [comment]
I think we can just skip or delete those tests. They seem specific to one Solaris variant or version and I suspect it's not guaranteed that those device numbers are guaranteed stable over time.

**Comment by 4ad** [comment]
Yes, let's drop this, the only way to do this is by parsing `/etc/name_to_major`, which is harder and more work (so more error prone) than the thing being tested.

**Comment by hyangah** [comment]
Ok. I also noticed the same test with hardcoded numbers for other OSes (dev_*_test.go). What about them?

**Comment by 4ad** [comment]
I don't know how other operating systems are supposed to work.

**Comment by tklauser** [comment]
> Ok. I also noticed the same test with hardcoded numbers for other OSes (dev_*_test.go). What about them?

At least on Linux, these numbers are guaranteed to be stable between releases. I'm not sure about the BSDs. On Darwin most of the major/minor numbers are generated dynamically and the few static ones (which are used in the test) might change as well in future releases.

I'll send a CL removing these tests on *BSD and Darwin as well.
