### ISSUE TITLE
x/build/devapp: still shows CLs with wait-release or wait-author hashtags

### ISSUE THREAD

**Issue by tklauser** [golang/go#25521]
https://dev.golang.org still shows some CLs which have the `wait-release` or `wait-author` hashtag, e.g.

https://golang.org/cl/113776
https://golang.org/cl/113855
~~https://golang.org/cl/100315~~
https://golang.org/cl/111695

**Comment by tklauser** [comment]
None of the listed CLs seem to have a reply with `R=go1.12` in it, while others that are excluded from https://dev.golang.org do have it (along with one of the `wait-{author,release}` tags.

**Comment by dmitshur** [comment]
@tklauser Do you know if this is still an issue or if it's been resolved? Was it about the https://dev.golang.org/reviews dashboard, or another one?

**Comment by tklauser** [comment]
> @tklauser Do you know if this is still an issue or if it's been resolved? Was it about the https://dev.golang.org/reviews dashboard, or another one?

This was about the https://dev.golang.org/reviews dashboard, yes. It looks like this has been resolved, I cannot find any open CLs with `wait-release` or `wait-author` tags on that dashboard anymore.
