### ISSUE TITLE
Cast [n]rune to string

### ISSUE THREAD

**Issue by dkrisa** [golang/go#25533]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
go1.10.1 linux/amd64

### What did you do?
Convert a slice of 5 runes to a string.
https://play.golang.org/p/upYJo4tgf3b

### What did you expect to see?
Expected slice to convert to string.

### What did you see instead?
cannot convert aslice (type [5]rune) to type string

**Comment by mattn** [comment]
please use `string(aslice[:])` instead.
