### ISSUE TITLE
x/mobile/cmd/gobind: panic with go1.8.3

### ISSUE THREAD

**Issue by happyEgg** [golang/go#25536]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.3 

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/admin/workspace/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4j/wpx8_n613m9dc636mh072qfh0000gn/T/go-build754525254=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
gomobile: /Users/admin/workspace/golang/bin/gobind -lang=go,objc -outdir=/var/folders/4j/wpx8_n613m9dc636mh072qfh0000gn/T/gomobile-work-738554164 -tags=ios bt failed: exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12989ba]

goroutine 1 [running]:
main.run()
	/Users/admin/workspace/golang/src/golang.org/x/mobile/cmd/gobind/main.go:145 +0x98a
main.main()
	/Users/admin/workspace/golang/src/golang.org/x/mobile/cmd/gobind/main.go:45 +0x27

**Comment by bcmills** [comment]
Note that go1.8.3 is technically unsupported (because go1.10 is available).

https://golang.org/doc/devel/release.html#policy

**Comment by happyEgg** [comment]
ok，thank for you

**Comment by ntop001** [comment]
@happyEgg @bcmills   did this issue fixed? I have the same problem with go 1.8.1.
