### ISSUE TITLE
https://go.googlesource.com/go?format=TEXT is 400

### ISSUE THREAD

**Issue by BanzaiMan** [golang/go#25549]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Click on the "text" link at the bottom of https://go.googlesource.com/go

### What did you expect to see?

A valid text document

### What did you see instead?

A 400. https://go.googlesource.com/go?format=TEXT

**Comment by meirf** [comment]
This appears to be a problem with gitiles which I think powers the [format features](https://github.com/google/gitiles/blob/7c07a4a68ece6009909206482e0728dbbf0be77d/java/com/google/gitiles/FormatType.java#L26).

I've opened a separate issue with gitiles: https://github.com/google/gitiles/issues/139

I think this issue should be closed.

**Comment by agnivade** [comment]
Agree. This is not a Go bug. @BanzaiMan - please follow the newly opened bug.
