### ISSUE TITLE
"json" links on https://go.googlesource.com/ return invalid JSON documents

### ISSUE THREAD

**Issue by BanzaiMan** [golang/go#25548]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

    curl -s 'https://go.googlesource.com/go/+refs?format=JSON' | jq .

### What did you expect to see?

A valid JSON document retrieved by `curl` and `jq` displaying a pretty JSON data.

### What did you see instead?

```sh-session
$ curl -s 'https://go.googlesource.com/go/+refs?format=JSON' | jq .
parse error: Invalid numeric literal at line 1, column 2
```

The first line of returned document is:

```
)]}'
```

which is indeed invalid JSON.

**Comment by kardianos** [comment]
This is working as intended I believe. This prevents a certain class of cross site scripting attacks.

**Comment by BanzaiMan** [comment]
That is interesting. Do you have any idea where I can find out more about these concerns? Is there a reference to documents that led to this decision?

More generally, though, how is the consumer supposed to know that the JSON data thus returned are invalid and to figure out how to recover the valid data? Why should such document be advertised with `content-type: application/json` when it is obviously not?

**Comment by bradfitz** [comment]
Yes, this is by design and documented:
https://gerrit-review.googlesource.com/Documentation/rest-api.html#output

**Comment by BanzaiMan** [comment]
@bradfitz I am curious. How was I supposed to find that documentation from https://go.googlesource.com/go/?

**Comment by kardianos** [comment]
It is a common practice. The server is Gerrit, so search Gerrit docs for
that prefix.

**Comment by bradfitz** [comment]
@BanzaiMan, why are you trying to use the Gerrit API without reading the Gerrit API documentation?

**Comment by BanzaiMan** [comment]
@bradfitz 

I appreciate your effort to understand more.

Frankly, I was not aware that https://go.googlesource.com/go was served by Gerrit at all. I am not interested in contributing to Go itself; I'm not a Go programmer. I am simply interested in getting the canonical list of releases available. To me, a consumer of the Go lang's project data, what powers https://go.googlesource.com is an implementation detail.

I followed:
https://golang.org/ -- (The Project at the top navigation bar) -> https://golang.org/project/ -- (Source Code) -> https://golang.org/change -- (HTTP Redirect) -> https://go.googlesource.com/go/

At this point, https://go.googlesource.com/go/+refs seemed like a reasonable place for the information I need. Expecting the 'json' link to return valid JSON (when the server explicitly sets `Content-Type: application/json`) seemed perfectly reasonable to me, but I guess I was mistaken.

**Comment by bradfitz** [comment]
@BanzaiMan, ah! Now I understand. I'd never seen that link down there.

I'll pass this feedback on to the Gerrit team.
