### ISSUE TITLE
encoding/base64: with normal padding: input=>encode=>decode=>output (!=input)

### ISSUE THREAD

**Issue by jeffkayser2** [golang/go#25552]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
[jkayser@oel7latest ~]$ go version
go version go1.10.2 linux/amd64
[jkayser@oel7latest ~]$ 

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
[jkayser@oel7latest ~]$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jkayser/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jkayser"
GORACE=""
GOROOT="/usr/local/go1.10.2"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.10.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build522215723=/tmp/go-build -gno-record-gcc-switches"
[jkayser@oel7latest ~]$ 

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/-CtQL8ilWPK

### What did you expect to see?
The input and output being identical.

### What did you see instead?
input:   6162
output:  5957493d
decoded: 616200
input != decoded

**Comment by fraenkel** [comment]
If you actually checked the number of bytes written during decode and resize it, you will end up with the same value as input.

**Comment by opennota** [comment]
https://play.golang.org/p/OKp3jWYwTb7

**Comment by andybons** [comment]
Closing as @fraenkel and @opennota seem to have provided an answer to your issue. Please let me know if I should re-open.
