### ISSUE TITLE
cmd/go: go get -u golang.org/x/vgo: sys/socket.h not found on macOS 10.13.4

### ISSUE THREAD

**Issue by SergeyParamoshkin** [golang/go#25560]
Hi! I have the problem. I trying to get vgo as written in documentation, but I get error. what am i doing wrong? 

```
$ go version
go version go1.10.2 darwin/amd64
```
```
OS X High Sierra 10.13.4
```

```
$ go get -u golang.org/x/vgo
# net
In file included from /usr/local/go/src/net/cgo_bsd.go:11:
In file included from /usr/include/netdb.h:91:
/usr/include/netinet/in.h:81:10: fatal error: 'sys/socket.h' file not found
#include <sys/socket.h>
         ^~~~~~~~~~~~~~
1 error generated.
```

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

```
$ softwareupdate -i -r
Software Update Tool

Finding available software
No updates are available.
```
I try reinstall golang and vgo ( remove binary and sources), but it didn't help me.

**Comment by bcmills** [comment]
> I try reinstall golang and vgo ( remove binary and sources), but it didn't help me.

How did you install the Go toolchain? (The [official distribution](https://golang.org/dl/), `brew`, or something else?)

What is the output of the following commands on your machine?

* `which $(go env CC)`
* `$(go env CC) --version`

**Comment by SergeyParamoshkin** [comment]
Hi @bcmills, I use  [official distribution](https://dl.google.com/go/go1.10.2.darwin-amd64.pkg) for MacOS 

```
$ which $(go env CC)
/usr/bin/clang
```

```
$ $(go env CC) --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by bcmills** [comment]
I'm still not sure what the problem is here, but I haven't seen any further reports of this, and the `vgo` repository is mostly not needed now that Go 1.11 is released (with preliminary module support).

I don't think we'll be able to get to this. If you have a similar issue installing the Go toolchain itself, please file a new issue.
