### ISSUE TITLE
x/vgo:Can't get all github tag

### ISSUE THREAD

**Issue by ppmoon** [golang/go#25569]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10 darwin/amd64
### Does this issue reproduce with the latest release?

y
### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liuyunpeng/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/liuyunpeng/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x1/qshdgg7s5nd10068tdpqqjp80000gn/T/go-build415931633=/tmp/go-build -gno-record-gcc-switches -fno-common"
### What did you do?
vgo list -t github.com/gin-gonic/gin
github.com/gin-gonic/gin
        v1.1.1
        v1.1.2
        v1.1.3
        v1.1.4
I download the gin via vgo,But just get v1.1.4. It had release v1.2 why I can't get v1.2
<img width="991" alt="wx20180525-212952 2x" src="https://user-images.githubusercontent.com/3971390/40546810-ccc19e8a-6062-11e8-96e4-cbae29b7fea4.png">
I try to vgo get github.com/gin-gonic/gin@master or vgo get github.com/gin-gonic/gin@v1.2 is fail.It still is v1.1.4

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

I hope I can download the gin v1.2 via vgo

**Comment by ppmoon** [comment]
<img width="484" alt="wx20180525-213406 2x" src="https://user-images.githubusercontent.com/3971390/40547028-601c2952-6063-11e8-8ce1-fc61213fb25d.png">

**Comment by kardianos** [comment]
The v1.2 tag is missing the last point version.
The tag should be v1.2.0
