### ISSUE TITLE
x/text/cases: Is there memory leak in icu.go?

### ISSUE THREAD

**Issue by caoruidong** [golang/go#25562]
### What version of Go are you using (`go version`)?
$ go version
go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What did you do?

We take a look at golang/text/cases/icu.go. Find that cgo is used in this file.

### What did you expect to see?

 C.CString freed.

### What did you see instead?

loc and src are not freed.
https://github.com/golang/text/blob/5c1cf69b5978e5a34c5f9ba09a83e56acc4b7877/cases/icu.go#L29

    loc := C.CString(tag)
	cm := C.ucasemap_open(loc, C.uint32_t(0), &err)
	buf := make([]byte, len(input)*4)
	dst := (*C.char)(unsafe.Pointer(&buf[0]))
	src := C.CString(input)

**Comment by meirf** [comment]
@caoruidong, there does seem like a leak but the only way to know for sure is to profile it. I wasn't able to get the usecasemap* functions working but here are some tips if you are able to:

I do think you should run e.g. `doICU("lower", "af", "a\u05d0a")` in a loop and observe the memory usage of that process from the perspective of the OS. For example, when running just `C.CString` vs `C.CString` + `C.free` on my mac I was able to clearly see not freeing caused memory usage to balloon. (I happen to have used the built in osx Activity Monitor).

I do not think putting e.g. `doICU("lower", "af", "a\u05d0a")` in a Benchmark and then using `-benchmem` will show you memory usage for the same reason go isn't able to garbage collect those strings - these string allocations are not known to Go's memory manager.

**Comment by caoruidong** [comment]
When using cgo, memory is managed manually. From code, I don't see a call to free. But this only exists in test code, so close it.
