### ISSUE TITLE
reflect does not convert method to type

### ISSUE THREAD

**Issue by matsuev** [golang/go#25571]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/GoLang"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m8/n85089y93_z0z8h41phf0d7m0000gn/T/go-build681845547=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
https://play.golang.org/p/bqLrCjfOWlS

**Comment by andybons** [comment]
It's unclear what you expect to see as you've left that portion of the report blank.

It may be worth asking this on the various forums (golang.org/wiki/Questions).

**Comment by AlexRouSg** [comment]
@andybons Based on the topic and playground, I'm thinking he means methods obtained through reflect should be able to assert to named function types.

As in he expects this to compile:
```
type MyFunc func()
f := reflect.ValueOf(m).Method(0).Interface().(MyFunc)
```

I feel like I've seen a related issue before but I cannot seem to find it.

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by go101** [comment]
Why is it valid? `MyFunc` and `func()` are two distinct types. The type of `m.MyFunction` is `func()`.
```golang
func main() {
	m := &Obj{}
	fmt.Printf("%T \n", m.MyFunction) // func() 
}
```

**Comment by ianlancetaylor** [comment]
I agree with @go101.  You even have the correct code commented out in your example.  The fact that a value is assignable to a variable of the type `MyFunc` does not mean that it is the type `MyFunc`.  Type assertions require type identity, not type assignability.

Closing because I don't think there is a bug here.  Please comment if you disagree.

**Comment by matsuev** [comment]
I want to define function type once, then use reflect in many other functions.

For example:
```
type MyFunction func(arg []byte) error
```
Then use this code in other places:
```
var mf MyFunction
ft := reflect.TypeOf(mf)
...
if reflect.ValueOf(m).Method(n).Type().AssignableTo(ft) {
    f := reflect.ValueOf(m).Method(n).Interface().(MyFunction)
}
...
```
But... Because this code call panic, i write in each function
```
f := reflect.ValueOf(m).Method(n).Interface().(func(arg []byte) error)
```
If function type is changed, i will have to correct this code in each function

**Comment by go101** [comment]
you can use type alias instead:
```golang
type MyFunction = func(arg []byte) error
```

**Comment by matsuev** [comment]
@go101 Ok! It works perfectly.

Closed.
