### ISSUE TITLE
test: eliminate use of Perl in test/fixedbugs/...

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25586]
In cont. of #20032. 
These are the last users of Perl script `test/errchk`:

https://github.com/golang/go/blob/master/test/fixedbugs/bug248.go
https://github.com/golang/go/blob/master/test/fixedbugs/bug345.go

 Converting those tests to Go code will allow to remove `errchk` script completely.

**Comment by ysmolsky** [comment]
fix of bug345.go most probably depends on #25568, at least it blocks me.

**Comment by ysmolsky** [comment]
Bug345 fails on windows: https://build.golang.org/log/f2ce8c84cdd5abbb40225e1dad6245877e5e6006
Not sure why trybots didnt catch it.

Reopened.

**Comment by ysmolsky** [comment]
@ALTree can you help with fixing this test for windows?

**Comment by ALTree** [comment]
I don't use windows, sorry. I see that of the 4 windows builders only 2 are failing... so maybe it has something to do with the builders environment? Maybe @alexbrainman can help.

**Comment by ysmolsky** [comment]
It does not fail on builders which does not run tests in test/...: `ShouldRunDistTest: noTestDir`, meaning that it fails on all Windows builds running this test.

**Comment by ysmolsky** [comment]
Created a follow up: #25693

**Comment by bradfitz** [comment]
> Not sure why trybots didnt catch it.

Trybots are a fast subset of build configs that aim to be as broad as possible. Some things slip through.
