### ISSUE TITLE
doc: archive/zip: *Writer.Close wording

### ISSUE THREAD

**Issue by bontibon** [golang/go#25599]
The documentation for *Writer.Close states:

> Close finishes writing the zip file by writing the central directory. It does not (and cannot) close the underlying writer.

The "(and cannot)" seems unnecessary, and differs from the docs of other Close methods in the standard library.

**Comment by meirf** [comment]
"(and can not)" was originally recommended by rsc [here](https://codereview.appspot.com/4523077/diff/8004/src/pkg/archive/zip/writer.go#newcode38). Unclear if that was a commentary or was meant to be included in the final code.

**Comment by bcmills** [comment]
CC: @rsc
