### ISSUE TITLE
cmd/go: list of .Deps shows a mix golang.org and golang_org items

### ISSUE THREAD

**Issue by ahmetb** [golang/go#25592]
### What version of Go are you using (`go version`)?
go 1.10.2
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?

I'm running this command to find dependencies of my program that are located in `vendor/`:

```
go list -f '{{join .Deps "\n"}}' ./... | grep -Eo 'vendor/.*' | sort | uniq
```

(Output of this command is listed below.)

In this list, there's a mix of both `vendor/golang_org/...` (note the underscore), and `vendor/golang.org/...`. But in reality, there's only `vendor/golang.org/...` on my filesystem. 

```
vendor/golang.org/x/text/language
vendor/golang.org/x/text/runes
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/text/transform
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/time/rate
vendor/golang_org/x/crypto/chacha20poly1305
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/cryptobyte
vendor/golang_org/x/crypto/cryptobyte/asn1
vendor/golang_org/x/crypto/curve25519
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/net/idna
vendor/golang_org/x/net/lex/httplex
vendor/golang_org/x/net/proxy
vendor/golang_org/x/net/route
vendor/golang_org/x/text/secure/bidirule
vendor/golang_org/x/text/transform
vendor/golang_org/x/text/unicode/bidi
vendor/golang_org/x/text/unicode/norm
```

Looks like some special treatment of string `golang_org/x/` in the Go source tree:

- https://github.com/golang/go/blob/4258b43afe3d3c48010aeeae7c438e5a88c6b5ab/src/cmd/api/goapi.go#L440
- https://github.com/golang/tools/blob/a5b4c53f6e8bdcafa95a94671bf2d1203365858b/cmd/bundle/main.go#L109

I can't tell why it is taking effect but it is confusing, and probably should not happen.

### What did you expect to see?

- `vendor/golang_org/...` items in the `{{.Deps}}` should be listed as `vendor/golang.org/...` which is how they appear in the filesystem.

### What did you see instead?

- Dependencies listed as `vendor/golang_org/...` instead of`vendor/golang.org/...` for some reason I cannot figure out.

**Comment by ianlancetaylor** [comment]
The references to `vendor/golang_org` are coming from the standard library, where the name `golang_org` is used because of #16333.  Since you are asking for `.Deps` of all packages, which includes the standard library, I think this is correct behavior and that there is no bug here.

The reference to golang_org in cmd/api is irrelevant here.  That code is not being run by cmd/go.

**Comment by ahmetb** [comment]
That makes sense, we can close this. Feel free to keep it open if you'd like to use this for tracking.
