### ISSUE TITLE
[Go2 proposal] defer for for loops

### ISSUE THREAD

**Issue by pjebs** [golang/go#25600]
It would be an amazing feature to define a `defer` for just for loops.
That way when the for loop's current iteration ends, it calls the deferred function.

(eg. after break, continue and natural end of iteration)

**Comment by bontibon** [comment]
Duplicate #3978

**Comment by davecheney** [comment]
Closing as #3978 was not accepted

**Comment by pjebs** [comment]
I've created https://github.com/rocketlaunchr/igo to demo how it would work.
