### ISSUE TITLE
x/tools/cmd/guru: give an option to exclude test code from the search

### ISSUE THREAD

**Issue by vimalk78** [golang/go#25607]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.10.2 linux/amd64`

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vimal/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vimal/gowork"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build593363879=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

used guru to list callers of a function.

### What did you expect to see?
the callers of the function

### What did you see instead?
guru returns all the callers of the function, including test code.

Is it possible to give an option to exclude test code while doing the search? 
an option to exclude test code from search will not only reduce the time taken to complete the search, but also give lesser results to the editors to work with.

**Comment by vimalk78** [comment]
ping

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete. Incidentally, gopls gets this right.
