### ISSUE TITLE
Gofmt mangles channels of receive only channels (chan <-chan)

### ISSUE THREAD

**Issue by DejeroDaniel** [golang/go#25614]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
go version go1.10.2 linux/amd64

### What did you do?
https://play.golang.org/p/yfhps7BzoKe

Click on Run. Golang's compiler clearly accepts this.
Click on Format. Gofmt does not.

### What did you expect to see?
Gofmt to stick to formatting and not change the meaning of my code.

### What did you see instead?
Gofmt disallowing channels of receive only channels, ` chan <-chan ` instead converting them to incoming only channels of channels. ` chan<- chan `

**Comment by josharian** [comment]
I believe that `gofmt` here formats the code correctly. Note that this doesn't compile: https://play.golang.org/p/M9VY3pPsVon. If you really want a channel of receive only channels, you can parenthesize: https://play.golang.org/p/y0Xx2Nne19Q.

**Comment by DejeroDaniel** [comment]
Ok, playing around with your example I can see that the go compiler also does this transformation:
https://play.golang.org/p/vAK1uojT8Vg

Weird behaviour but I guess not a bug. Thanks for reminding me about parenthesizing, thought I was going to have to create a type.
