### ISSUE TITLE
x/vgo: Is it possible to vgo install a custom library outside of GOPATH?

### ISSUE THREAD

**Issue by TerrenceHo** [golang/go#25639]
Perhaps I missed this in rsc's vgo introduction, but how is vgo install supposed to work when you install a custom package outside of the GOPATH?  

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64
go version go1.10 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kho/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kho/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qj/y8h5yl817zg5lj742cndn67m0000gq/T/go-build401971324=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
I recreated the `stringutil` package from the "How to Write Go Code" in a directory outside of the GOPATH, but added import statements. The `stringutil2` is located in `~/Desktop/stringutil2`. File is below. 
```
package stringutil2 // import "github.com/TerrenceHo/stringutil2"
// Package stringutil contains utility functions for working with strings.

// Reverse returns its argument string reversed rune-wise left to right.
func Reverse(s string) string {
	r := []rune(s)
	for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
		r[i], r[j] = r[j], r[i]
	}
	return string(r)
}
```

I added an empty go.mod file.  I then attempted a vgo build in this directory.  The go.mod file has the module name correctly added.
```
$ vgo build
$ cat go.mod
module github.com/TerrenceHo/stringutil2
```

Now that it builds correctly, I attempt to use vgo and install it, still attempting to follow the tutorial.
```
$ vgo install
go install: no install location for directory /Users/kho/Desktop/stringutil2 outside GOPATH
	For more details see: 'go help gopath'
```
### What did you expect to see?
I expected this package to be installed under `$GOPATH/pkg/darwin_amd64/github.com/TerrenceHo/stringutil2.a`

### What did you see instead?
It errors out, saying it cannot locate the `GOPATH`.  The vgo proposal mentioned being able to write Go code anywhere, not just within the `GOPATH`.  As such, I thought this would succeed, since I had implemented the correct go.mod file.  Additionally, if you try installing a main package, i.e. an executable, `vgo install` succeeds.

**Comment by myitcv** [comment]
@TerrenceHo - is there a reason you need to `vgo install` this package? i.e. what dependency do you have on `$GOPATH/pkg/darwin_amd64/github.com/TerrenceHo/stringutil2.a`?

If you are writing code outside of `GOPATH` (as you are) then `vgo install` will indeed fail.

**Comment by TerrenceHo** [comment]
@myitcv  No, I just thought that writing a package outside of GOPATH would install into the correct directory in the GOPATH pkg tree based on the import module name, due to rsc's statement that vgo would deprecate GOPATH.  I was just experimenting with vgo.  So in the future, we should continue to write libraries inside the GOPATH/src tree?

@agnivade This is more of a question than an issue, although if vgo should support installing a non main package from outside GOPATH, then it could be considered an issue.

**Comment by myitcv** [comment]
> So in the future, we should continue to write libraries inside the GOPATH/src tree?

As I understand things, GOPATH is no longer a requirement; I'm not entirely clear that it will disappear entirely though. So, as per the vgo examples, you don't _need_ to develop within GOPATH, but you can (for now).

If you are developing _outside_ GOPATH, then `vgo install` should not be required (because otherwise what would the target of the install be?). 

If you are developing _inside_ GOPATH, the `vgo install` will (for now) behave like `go install` does.

Tools like [`gocode`](https://github.com/nsf/gocode) currently rely on the `$GOPATH/pkg` tree to function, and hence rely on code being developed inside GOPATH. But there is work underway that will help to sever the dependency of such tools on `$GOPATH/pkg` and hence allow you develop all of your Go code outside GOPATH.

**Comment by agnivade** [comment]
I believe Paul's answer clarifies things as working as intended. Hence closing this.

Feel free to comment if you disagree.
