### ISSUE TITLE
wiki: rename NoMeToo

### ISSUE THREAD

**Issue by josharian** [golang/go#25637]
The wiki page was created and named prior to the social movement. The name now has unwelcome connotations. Renaming it will break links, but I think it is worth it. I don't have a great replacement name. Suggestions welcome.

cc @andybons @bradfitz @spf13

**Comment by andybons** [comment]
+ NoPlusOne
+ NoPileOn
+ ConstructiveComments (this could also encapsulate much more than just +1s being bad)

**Comment by bradfitz** [comment]
Let's keep the page as a redirection stub at least, linking to this bug for context.

**Comment by as** [comment]
- NoMeThree

**Comment by josharian** [comment]
Given the current focused nature of the page, and the ease of spelling, I like NoPlusOne. I’ll wait another 24 hours and, if no alternative consensus arises, I will make it so (with redirect stub). Thanks.

**Comment by ianlancetaylor** [comment]
+1

**Comment by andybons** [comment]
Awesome. Thanks, @josharian :)

**Comment by mattn** [comment]
I feel that NoPlusOne mean Please Stop Voting. I don't have an another ideas but I sugges to note that mean stop commenting +1 or similars.

**Comment by OneOfOne** [comment]
+1 // pls don't ban me....

I vote for ConstructiveComments or UnneededComments.

**Comment by adamdecaf** [comment]
I vote for ConstructiveComments.

**Comment by pciet** [comment]
+1 NoPlusOne

**Comment by josharian** [comment]
Done. Thanks to all for the feedback.

**Comment by pciet** [comment]
Sorry about this extra comment, but NoVoteComments may be an option if an issue appears later about NoPlusOne going against Google’s plus one feature.

**Comment by bradfitz** [comment]
@pciet, this bug is closed. Josh's name was fine.
