### ISSUE TITLE
build: FreeBSD failed builds in AWS / works fine on physical hardware

### ISSUE THREAD

**Issue by rhavenn** [golang/go#25630]
I'm running FreeBSD port builds on a physical machine and in an AWS ec2 instance. The same exact environment fails to build Go in AWS. My FreeBSD jail versions are the same (11.1-p10) and the only package requirements are go14 and pkg. All other items come from the base OS (clang, etc..)

Go 1.10.2 is what I'm trying to build. It works fine across multiple poudriere build jails on the physical box and fails for all my poudriere build jails on the virtual box. Occasionally it will just hang for hours, but CPU usage is nill. Usually, it crashes.

My dmesg info for the physical box:

FreeBSD 11.1-RELEASE-p10 #0: Tue May  8 05:21:56 UTC 2018
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
VT(vga): resolution 640x480
CPU: Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz (2200.05-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x306e4  Family=0x6  Model=0x3e  Stepping=4
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x7fbee3ff<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,SMX,EST,TM2,SSSE3,CX16,xTPR,PDCM,PCID,DCA,SSE4.1,SSE4.2,x2APIC,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x1<LAHF>
  Structured Extended Features=0x281<FSGSBASE,SMEP,ERMS>
  XSAVE Features=0x1<XSAVEOPT>
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID,VID,PostIntr
  TSC: P-state invariant, performance statistics
real memory  = 25769803776 (24576 MB)
avail memory = 24902356992 (23748 MB)
Event timer "LAPIC" quality 600
ACPI APIC Table: <DELL   PE_SC3  >

My dmesg info for the AWS instance:
FreeBSD 11.1-RELEASE-p10 #0: Tue May  8 05:21:56 UTC 2018
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
VT(vga): text 80x25
XEN: Hypervisor version 4.2 detected.
CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2300.05-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x406f1  Family=0x6  Model=0x4f  Stepping=1
  Features=0x1783fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,HTT>
  Features2=0xfffa3203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,PCID,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x21<LAHF,ABM>
  Structured Extended Features=0x7a9<FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID>
  XSAVE Features=0x1<XSAVEOPT>
Hypervisor: Origin = "XenVMMXenVMM"
real memory  = 17179869184 (16384 MB)
avail memory = 16603602944 (15834 MB)
Event timer "LAPIC" quality 100
ACPI APIC Table: <Xen HVM>

go14 builds okay and runs, but when running the all.bash build script for 1.10.2 I get the following:

root@server-srv-PHP7-default:/wrkdirs/usr/ports/lang/go/work/go/src # ./all.bash
-ap: not found
go: not found
Building Go cmd/dist using /usr/local/go14/.
Building Go toolchain1 using /usr/local/go14/.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xa0 pc=0x473050]

runtime stack:
runtime.gothrow(0x5edb70, 0x2a)
	/usr/local/go14/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/go14/src/runtime/sigpanic_unix.go:14 +0x5e
globrunqget(0xc208012000, 0x0, 0x800000299)
	/usr/local/go14/src/runtime/proc.c:3245 +0xf0
findrunnable(0xc208012000)
	/usr/local/go14/src/runtime/proc.c:1400 +0xcf
schedule()
	/usr/local/go14/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc2080006c0)
	/usr/local/go14/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x46da94)
	/usr/local/go14/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [chan receive]:
main.install(0x5b4b10, 0x6)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.cmdbootstrap()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:1178 +0x913
main.xmain()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/main.go:178 +0x1a7
main.main()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/main.go:161 +0x5ad

goroutine 6 [select]:
main.bghelper()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:138 +0x148
created by main.bginit
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:131 +0x58

goroutine 7 [select]:
main.bghelper()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:138 +0x148
created by main.bginit
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:131 +0x58

goroutine 8 [select]:
main.bghelper()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:138 +0x148
created by main.bginit
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:131 +0x58

goroutine 9 [select]:
main.bghelper()
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:138 +0x148
created by main.bginit
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:131 +0x58

goroutine 26 [chan receive]:
main.install(0xc20a8222e1, 0x13)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0x5b4b10, 0x6, 0xc20803a180)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 34 [chan receive]:
main.install(0xc208138a61, 0x16)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a8222e1, 0x13, 0xc20803a5a0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 36 [chan receive]:
main.install(0xc208138101, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a822321, 0x15, 0xc20803a660)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 38 [chan receive]:
main.install(0xc2081383a1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a822361, 0x16, 0xc20803a720)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 39 [runnable]:
syscall.Syscall(0x3, 0x4, 0xc20a737348, 0x8, 0x0, 0x8, 0x0)
	/usr/local/go14/src/syscall/asm_freebsd_amd64.s:21 +0x5
syscall.readlen(0x4, 0xc20a737348, 0x8, 0x9, 0x0, 0x0)
	/usr/local/go14/src/syscall/zsyscall_freebsd_amd64.go:1298 +0x57
syscall.forkExec(0xc20a84a050, 0x41, 0xc20a768000, 0x8, 0x8, 0xc20a737550, 0x13598, 0x0, 0x0)
	/usr/local/go14/src/syscall/exec_unix.go:200 +0x5d0
syscall.StartProcess(0xc20a84a050, 0x41, 0xc20a768000, 0x8, 0x8, 0xc20a737550, 0x2, 0x4, 0x0, 0x0)
	/usr/local/go14/src/syscall/exec_unix.go:238 +0x72
os.startProcess(0xc20a84a050, 0x41, 0xc20a768000, 0x8, 0x8, 0xc20a84a0a0, 0x58ff20, 0x0, 0x0)
	/usr/local/go14/src/os/exec_posix.go:45 +0x47b
os.StartProcess(0xc20a84a050, 0x41, 0xc20a768000, 0x8, 0x8, 0xc20a84a0a0, 0x2, 0x0, 0x0)
	/usr/local/go14/src/os/doc.go:24 +0x72
os/exec.(*Cmd).Start(0xc20a802000, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:316 +0x92e
os/exec.(*Cmd).Run(0xc20a802000, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:243 +0x3a
main.run(0xc20a80a7c0, 0x3a, 0x3, 0xc20a6321c0, 0x8, 0xe, 0x0, 0x0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:89 +0x328
main.runInstall(0xc20a822381, 0x13, 0xc20803a780)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:795 +0x340b
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 40 [runnable]:
syscall.Syscall(0x5, 0xc208032550, 0x100000, 0x0, 0x5, 0x0, 0x0)
	/usr/local/go14/src/syscall/asm_freebsd_amd64.s:21 +0x5
syscall.Open(0x5bc610, 0x9, 0x100000, 0xc200000000, 0x0, 0x0, 0x0)
	/usr/local/go14/src/syscall/zsyscall_freebsd_amd64.go:819 +0xaa
os.OpenFile(0x5bc610, 0x9, 0x0, 0x0, 0x59f420, 0x0, 0x0)
	/usr/local/go14/src/os/file_unix.go:78 +0x6f
os.Open(0x5bc610, 0x9, 0x80067f840, 0x0, 0x0)
	/usr/local/go14/src/os/file.go:239 +0x55
os/exec.(*Cmd).stdin(0xc20a802280, 0x0, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:159 +0xab
os/exec.(*Cmd).Start(0xc20a802280, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:300 +0x345
os/exec.(*Cmd).Run(0xc20a802280, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:243 +0x3a
main.run(0xc20a80aa40, 0x3d, 0x3, 0xc20a6322a0, 0x8, 0xe, 0x0, 0x0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:89 +0x328
main.runInstall(0xc20a8223a1, 0x16, 0xc20803a7e0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:795 +0x340b
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 41 [chan receive]:
main.install(0xc2081387c1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a8223c1, 0x18, 0xc20803a840)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 42 [chan receive]:
main.install(0xc208138aa1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a8223e1, 0x13, 0xc20803a8a0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 44 [chan receive]:
main.install(0xc208138fa1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a822421, 0x14, 0xc20803a960)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 45 [chan receive]:
main.install(0xc2081390e1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a822441, 0x13, 0xc20803a9c0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 46 [chan receive]:
main.install(0xc208139341, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a822461, 0x14, 0xc20803aa20)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 49 [chan receive]:
main.install(0xc2081397a1, 0x14)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:567 +0x55
main.runInstall(0xc20a8224c1, 0x13, 0xc20803ab40)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:760 +0x24b3
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

goroutine 50 [syscall]:
syscall.Syscall(0x3, 0x7, 0xc20a447348, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go14/src/syscall/asm_freebsd_amd64.s:21 +0x5
syscall.readlen(0x7, 0xc20a447348, 0x8, 0x10, 0x0, 0x0)
	/usr/local/go14/src/syscall/zsyscall_freebsd_amd64.go:1298 +0x57
syscall.forkExec(0xc20a84a370, 0x41, 0xc20a7b44b0, 0xf, 0xf, 0xc20a447550, 0x13dd8, 0x0, 0x0)
	/usr/local/go14/src/syscall/exec_unix.go:200 +0x5d0
syscall.StartProcess(0xc20a84a370, 0x41, 0xc20a7b44b0, 0xf, 0xf, 0xc20a447550, 0x2, 0x4, 0x0, 0x0)
	/usr/local/go14/src/syscall/exec_unix.go:238 +0x72
os.startProcess(0xc20a84a370, 0x41, 0xc20a7b44b0, 0xf, 0xf, 0xc20a84a3c0, 0x58ff20, 0x0, 0x0)
	/usr/local/go14/src/os/exec_posix.go:45 +0x47b
os.StartProcess(0xc20a84a370, 0x41, 0xc20a7b44b0, 0xf, 0xf, 0xc20a84a3c0, 0x2, 0x0, 0x0)
	/usr/local/go14/src/os/doc.go:24 +0x72
os/exec.(*Cmd).Start(0xc20a8023c0, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:316 +0x92e
os/exec.(*Cmd).Run(0xc20a8023c0, 0x0, 0x0)
	/usr/local/go14/src/os/exec/exec.go:243 +0x3a
main.run(0xc20819e340, 0x3b, 0x3, 0xc20a7b43c0, 0xf, 0xf, 0x0, 0x0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/util.go:89 +0x328
main.runInstall(0xc20a8224e1, 0x14, 0xc20803aba0)
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:795 +0x340b
created by main.startInstall
	/wrkdirs/usr/ports/lang/go/work/go/src/cmd/dist/build.go:576 +0x114

**Comment by ianlancetaylor** [comment]
This looks like a problem running Go 1.4 to build Go 1.10.2.  Precisely where did you get the Go 1.4 sources that you are using?

**Comment by rhavenn** [comment]
Go 1.4 is built as a dependency by the FreeBSD build structure. It pulls it as source from http://golang.org/dl/  . I can try forcing a package rebuild of the 1.4.2, but the source tar ball matches the SHA hash from there.

**Comment by rhavenn** [comment]
Sorry, 1.4.3 is what it's using.

**Comment by rhavenn** [comment]
Not that it's the best example, but inside the jail I was able to use go14/bin/go to run, build and execute a "hello world", so the 1.4.3 binary is working at a very basic level.

**Comment by ianlancetaylor** [comment]
I don't know that this is the problem, but for your 1.4 sources you should currently be using  go1.4-bootstrap-20171003.tar.gz, not the 1.4.3 release.  The 20171003 file includes various fixes that we've found necessary.

**Comment by ianlancetaylor** [comment]
No clue, sorry.  I think you are going to have to debug this.  Happy to answer questions.

**Comment by bradfitz** [comment]
Our FreeBSD port was pretty stable, I thought, so that runtime error looks concerning. @aclements, @randall77, see anything interesting there?

**Comment by rhavenn** [comment]
I even pulled a SVN 11.1-RELEASE (no patches) into a test poudriere jail and it stills falls over randomly. It will either just spin on the ./cmd/dist/dist bootstrap -a for hours or crash in random places. At this point I'm thinking it's something Amazon did to the VM or host patch problems vs. the jail itself. It works perfectly fine over 3 different poudriere jails on the physical server I have and has been stable for months. I'm also having trouble with rust compiling on my AWS instance vs. my physical box, so it might not just be Go.

11.1-RELEASE-p6 worked fine for Go and Rust on 04/06 and then I updated to -p9 on 5/6 and it's been failing since for both Go and Rust.

So, either an issue with the host Spectre / Meltdown patches and AWS EC2 instances or something. I just rolled my host back to -p6 and we'll see what happens.

**Comment by rhavenn** [comment]
After rolling my host back from 11.1-p10 to 11.1-p6 I've successfully built lang/go 3 times in the 11.1-RELEASE temp jail I created. So, I'm guessing something in the Spectre / Meltdown patches is causing it.

**Comment by rhavenn** [comment]
Since this doesn't seem to be a Go issue I'll close this. Submitted a FreeBSD bug:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228620

**Comment by ianlancetaylor** [comment]
Thanks for following up.
