### ISSUE TITLE
unicode: can't specify rune(s) to be invariant under a SpecialCase case change.

### ISSUE THREAD

**Issue by splace** [golang/go#25636]
### What did you do?
built a unicode.CaseRange that specifies a rune(s) to be its own upper/lower case, by setting it to have a zero delta.

https://play.golang.org/p/u0fOaF41ah8

### What did you expect to see?
no case change for rune(s) in the range.

### What did you see instead?
special case ignored, rune changed according to default case change rules.

**Comment by bcmills** [comment]
CC @mpvl
