### ISSUE TITLE
cmd/go: go install failed

### ISSUE THREAD

**Issue by tharun-d** [golang/go#25642]
### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows 7 enterprise with service pack 1 architecture:AMD Athlon (tm) x2 B24 processor

### What did you do?
I downloaded .msi file and installed(didn't change any path) i created hello.go file using vscode and recommended me to install the things required when i did that i got this error

### What did you see instead?

```
> Installing github.com/sqs/goreturns FAILED

1 tools failed to install.

goreturns:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/sqs/goreturns
# cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns; git config remote.origin.url
package github.com/sqs/goreturns: remote origin not found
# cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns; git config remote.origin.url
package github.com/sqs/goreturns: remote origin not found
```

Only go returns is failed some other recommend tools got installed successfully

```
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
```

and many more 

I did this

```
_c:\Go>go get -v -u
package _/c_/Go: unrecognized import path "_/c_/Go" (import path does not begin
with hostname)_
```

**Comment by ianlancetaylor** [comment]
`go get` takes an argument.  What is the output of `get -u -v -x github.com/sqs/goreturns`?

**Comment by tharun-d** [comment]
C:\Users\hpadmin>**go get -u -v -x github.com/sqs/goreturns**
cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns
git config remote.origin.url
# cd C:\Users\hpadmin\go\src\github.com\sqs\goreturns; git config remote.origin.
url
package github.com/sqs/goreturns: remote origin not found

**Comment by davecheney** [comment]
You might have an old or misconfigured copy of that package. Delete

C:\Users\hpadmin\go\src\github.com\sqs\goreturns

And try again.

**Comment by davecheney** [comment]
Fundamentally go get is just a wrapper around git, and it looks like the git commands are failing.

I don't think that we can help you, your problems look like general networking or anti virus related -- something is either blocking or delaying your traffic.

**Comment by EvgenySerg** [comment]
I have the same problem.
There is noantivirus software on my pc. Windows 10. Go version 1.10.2.
The message i've got:
dlv:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
# cd C:\Users\fatboa\go\src\github.com\derekparker\delve; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/derekparker/delve/cmd/dlv: exit status 128
github.com/derekparker/delve (download)
# cd C:\Users\fatboa\go\src\github.com\derekparker\delve; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/derekparker/delve/cmd/dlv: exit status 128

C:\Users\xxx>go.exe get -u -v github.com/sqs/goreturns
# cd C:\Users\xxx\go\src\github.com\sqs\goreturns; git config remote.origin.url
package github.com/sqs/goreturns: remote origin not found

**Comment by agnivade** [comment]
Your issue is different. OP's issue seems to be networking related. 

`connectex: A connection attempt failed because the conne
cted party did not properly respond after a period of time, or established conne
ction failed because connected host has failed to respond.` - clearly shows that the connection has failed to establish.

Your issue seems to be due to a corrupted GOPATH or possibly something git related. Is this a new problem that you saw after upgrading to 1.10.2 ? Or did you just setup Go from scratch and saw this ? Are you able to clone the git repositories manually using raw git commands ?
