### ISSUE TITLE
blog: one sentence typo of blog go-maps-in-action

### ISSUE THREAD

**Issue by yelongyu** [golang/go#25647]
in blog

https://blog.golang.org/go-maps-in-action

section `Iteration order`

>When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation. If you require a stable iteration order you must maintain a separate data structure that specifies that order. This example uses a separate sorted slice of keys to print a map[int]string in key order:

may be the sentence should be below

```
Since Go in the runtime randomizes map iteration order
```

**Comment by robpike** [comment]
It's actually correct as written, though I see the ambiguity that confuses you. What it means is that the behavior of maps is like this, since the release of Go version 1. It is easy to fix the ambiguity: Just delete the "Since Go 1" preamble and move the sentence to the present tense.
