### ISSUE TITLE
suggestion for fmt.Sscanf

### ISSUE THREAD

**Issue by tskdsb** [golang/go#25640]
### What version of Go are you using (`go version`)?
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\workspace\go;D:\Go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build808753802=/tmp/go-build -gno-record-gcc-switches

### What did you do?
```
func main() {
  var (
    a string
    b string
  )
  fmt.Sscanf(`aa,bb`, "%s,%s", &a, &b)
  fmt.Printf("%q\n%q", a, b)
}
```
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
```
"aa"
"bb"
```
### What did you see instead?
```
"aa,bb"
""
```

**Comment by agnivade** [comment]
This is working according to documentation.

> Sscanf scans the argument string, storing successive space-separated values into successive arguments as determined by the format.

If you are proposing a change in behavior, please file a proposal following the process outlined here - https://golang.org/s/proposal. Be sure to outline the benefits of such a breaking change and practical scenarios where such a thing might be helpful.

Thanks.
