### ISSUE TITLE
net/http/httputil: allow error customization in reverse proxy

### ISSUE THREAD

**Issue by ramonnteixeira** [golang/go#25643]
I would like to customize the error handling by being able to redirect the other page

https://github.com/golang/go/blob/f5cf72d43ed1441d2e80654be5bde4b11f4cbcd1/src/net/http/httputil/reverseproxy.go#L208-L212

**Comment by meirf** [comment]
> redirect the other page

I assume you mean that when `ReverseProxy.Transport` returns an error you'd like to have a custom response (status code, body, headers, etc) written to the ResponseWriter.

But if you're setting `ReverseProxy.Transport` then you have total control of when errors are returned. You can just catch the error and `return customResponse, nil`. If you're not setting `ReverseProxy.Transport`, then you could wrap the DefaultTransport in your custom wrapper which catches the error.

So it seems like the code as is gives you as much control as you need and adding more API adds clutter.

**Comment by ramonnteixeira** [comment]
Sorry for my stubbornness, but my proposal is to manipulate the error return. 
I believe this part of the code would be ideal for doing this customization

**Comment by meirf** [comment]
“manipulate the error return”

I feel like we’re talking in circles. Can you please be more specific on what this means? Please show some code examples.

**Comment by ramonnteixeira** [comment]
sorry, I was really wrong, did not know that I can implement the Roundtrip method and set ReverseProxy.Transport

Thanks.
