### ISSUE TITLE
access: apply for TryBot Access

### ISSUE THREAD

**Issue by benshi001** [golang/go#25658]
My github account: benshi001
my googlesource account: powerman1st@163.com

I have been contributing to golang for 15 months, and made total 53 commits and  39,773 lines. 

https://github.com/golang/go/graphs/contributors
https://github.com/golang/go/commits?author=benshi001

I expect to make more contribution with Try-Bot access.

Thank you.

**Comment by ianlancetaylor** [comment]
I've added you to the may-start-trybots group on Gerrit.  Thanks!

**Comment by benshi001** [comment]
Thank you for your trust.

But how to start a Try-Bot? I only find a code-review+2 button on the top-right corner in each CL's page.

Really appreciate you.

**Comment by ALTree** [comment]
@benshi001 Click the blue "reply" button, you'll see a "Run-TryBot" line. Click on the `+1` button on that line and then on "Send".

**Comment by benshi001** [comment]
Thank you. I see the TryBot + 1. Really appreciate.
