### ISSUE TITLE
x/vgo: unknown module git.apache.org/thrift.git/lib/go/thrift: no go-import tags

### ISSUE THREAD

**Issue by sami9gag** [golang/go#25654]
### What version of Go are you using (`go version`)?

`go version go1.10.2 darwin/amd64 vgo:2018-02-20.1`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?

I'm trying to pull dependencies for a project using opencensus, which depends on thrift. The thrift dependency fails to pull due to missing import tags. This can be reproduced with the following snippet:

```go
package main

import (
	"go.opencensus.io/exporter/jaeger"
)

func main() {
	_ = jaeger.Options{}
}
```

When using `vgo get -u` on that snippet, the pull will fail with an error: `unknown module git.apache.org/thrift.git/lib/go/thrift: no go-import tags`

The failure appears to be caused by this line in one of the dependencies:
https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/jaeger/jaeger.go#L28

This works with `go get -u`

### What did you expect to see?

I expected `vgo get -u` to complete normally after pulling the dependencies. 

### What did you see instead?

```
[...]
vgo: resolving import "git.apache.org/thrift.git/lib/go/thrift"
vgo: import "github.com/sami9gag/vgo-break" ->
        import "go.opencensus.io/exporter/jaeger" ->
        import "git.apache.org/thrift.git/lib/go/thrift": unknown module git.apache.org/thrift.git/lib/go/thrift: no go-import tags
```

**Comment by rsc** [comment]
The problem is that vgo does not understand the .git name convention.
