### ISSUE TITLE
cmd/go: cc1: error: unrecognized command line option "-m32" during get

### ISSUE THREAD

**Issue by gbitten** [golang/go#25665]
### What version of Go are you using (`go version`)?

go version go1.10.2 linux/386

### Does this issue reproduce with the latest release?

Version 1.10.2 is the latest stable release, Anyway, It works normally with go version go1.9.6 linux/386.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="386"
GOBIN=""
GOCACHE="/home/rds/.cache/go-build"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rds/go"
GORACE=""
GOROOT="/home/rds/gotest/go"
GOTMPDIR=""
GOTOOLDIR="/home/rds/gotest/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
CC="arm-arago-linux-gnueabi-gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build804659883=/tmp/go-build"
```

### What did you do?

```
wget https://dl.google.com/go/go1.10.2.linux-386.tar.gz
sudo tar -C /usr/local -xzf go1.10.2.linux-386.tar.gz
echo export PATH=\$PATH:/usr/local/go/bin >> ~/.profile
source ~/.profile
go get github.com/gorilla/mux
```

### What did you expect to see?

No errors

### What did you see instead?

```
# runtime/cgo
cc1: error: unrecognized command line option "-m32"
```

**Comment by ianlancetaylor** [comment]
You are building for 386, but your `CC` environment variable points to what looks like an ARM compiler.  Don't set `CC` in the environment, or at least set it to an x86 compiler.

**Comment by gbitten** [comment]
This machine is used to cross compile with GCC, I didn't know that could affect Go.

**Comment by ianlancetaylor** [comment]
The `CC` environment variable sets the default C compiler to use with Go code that calls C code, as documented at https://golang.org/cmd/cgo and https://golang.org/cmd/go/#hdr-Environment_variables .

**Comment by frakman1** [comment]
I had the same error. It turns out the shell I was using was previously set up to cross compile (`source environ ...`) The fix was just to open a new, fresh shell so it didn't have the holdover environment variables from before.
