### ISSUE TITLE
test: remove Perl script errchk

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25669]
No test uses the perl script `errchk` anymore. We can remove it from the source tree. Is there any other place from which we should remove `Perl` as well?

**Comment by ianlancetaylor** [comment]
@ysmolsky You marked this as NeedsDecision but I'm not sure what decision you are looking for.

**Comment by josharian** [comment]
If no one in the tree uses errchk, it should be deleted. If it turns out that someone else (some x repo?) uses it, they can just make a copy for themselves.

I'm not aware of anywhere else in the tree that uses perl. You could confirm that by removing perl from your PATH and running all.bash.

**Comment by bradfitz** [comment]
> I'm not aware of anywhere else in the tree that uses perl. You could confirm that by removing perl from your PATH and running all.bash.

Better to make a Docker image with a fake perl in $PATH that returns an error, because some tests (net/http/cgi?) do a LookPath for Perl and skip if not found.

**Comment by ysmolsky** [comment]
Perl is still being used here:
src/net/http/cgi/testdata/test.cgi
src/regexp/syntax/make_perl_groups.pl
src/net/http/cgi/host_test.go
src/syscall/*.pl

I will stop here with Perl evictions, if anyone feels up to it, please go ahead with test.cgi and host_test.go.
