### ISSUE TITLE
cmd/go: GODEBUG=gocacheverify=1 ./all.bash fails on tip

### ISSUE THREAD

**Issue by martisch** [golang/go#25666]
### What version of Go are you using (`go version`)?
go tip

../bin/go version
go version devel +caf968616a Thu May 31 13:29:50 2018 +0000 linux/amd64

### What did you do?
go clean -cache
GODEBUG=gocacheverify=1 ./all.bash

### What did you expect to see?
no panic

### What did you see instead?
ok  	regexp/syntax	0.432s
panic: go: internal cache error: cache verify failed: id=7d1de7e02583755526739389bd6fc1974cfc37da58553b099fd623bd77a6f437 changed:<<<
compile
goos linux goarch amd64
import "cmd/cover"
omitdebug false standard true local false prefix ""
compile Z5KkeuwGD_YmlK9AKqhE [] []
GO$GOARCH=
file cover.go -HJGpdKieEMMOCO-mPxL
file doc.go q8cjgpxRyr-B4c0-BSxm
file func.go XsiVkomYxidS7PwWXQ2n
file html.go 4Y1BIbPC6AVLRyO7P_1x
file profile.go 0v22dDl9QjcWlQUwc8ke
import bufio x_-ZmcJaRE1-62HC7gEy
import bytes -ExnlBGGJxi4VZ5EqPw6
import cmd/internal/browser -OSlaIN89ju-lKeJTEtZ
import cmd/internal/edit eAcymmmTWYX7N48foFvc
import cmd/internal/objabi Wx6XuWtw8yzI2OUM-I1X
import flag Apc7KW-rM8Do39ESNy9L
import fmt IKr8q_ka3BkoAGXRW9vb
import go/ast 3lMn5Fnsr6X1r8KaWvmX
import go/build WEmUKvioE4gojuLKr7yC
import go/parser zgKhNbLoAKQRyd-wKYnd
import go/token pjlHSTQZQ8NEhm62LFhU
import html/template IZspSCnOsTK022SyxgwV
import io JUl0LPhkSJ8CDbdJmbME
import io/ioutil T5jUc1oEVPHnwKrVw-ew
import log qVNeFQ1akGgeIZX9TSVx
import math xYExcA8201vQyyZ9IGvw
import os 2N6oAGLW3b6OMDDak_Kv
import path/filepath Zw1gJYZoXyx4xrS4j8bU
import regexp t9sroldeoNMIbrsNDHls
import sort sPmY1SAx3P0TLUoaIIy8
import strconv QtFWYl284THTUEfpinB4
import strings 23Tj_-1ryGCvgpeL4R6K
import text/tabwriter qUQ4bN_UZwnU03hZEjys
import runtime v2qTneM1d0huhg0jpHvU

>>>
old: c802e90778868f599f331dc9c7967c87ff18c2e087b473ab9a126a5be6f1b242 217716
new: 300d198f10396404918e48056311287053936e1ef01988ff065235f01f0405ae 217700

**Comment by ianlancetaylor** [comment]
Do you know which test is failing?  I can't tell from the output.

**Comment by martisch** [comment]
`GODEBUG=gocacheverify=1 go test cmd/cover`

is a shorter reproduction of the above error. Found after a guess from the `import "cmd/cover"` statement in the output.

**Comment by ianlancetaylor** [comment]
I found two problems and sent two CLs.
