### ISSUE TITLE
crypto/x509: Certificate Subject UID not being parsed

### ISSUE THREAD

**Issue by Trane9991** [golang/go#25667]
### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

### What did you do?
Trying to get the UID from certificate attributes.

### What did you expect to see?
`pkix.Name` object with the `UID` field in it.

### What did you see instead?
OID for the UserID http://www.alvestrand.no/objectid/0.9.2342.19200300.100.1.1.html is not defined in the https://golang.org/src/crypto/x509/pkix/pkix.go, so it is not being parsed.

**Comment by adamdecaf** [comment]
cc @FiloSottile

**Comment by FiloSottile** [comment]
It should still be accessible unparsed in the Names field.

If you think we should add an entry to the struct for it, we'll need example certificates and the use cases of it. We intentionally only parse the most popular OIDs, and leave the rest to be parsed by applications in Names.

**Comment by Trane9991** [comment]
Yeah, I was able to get it this way: https://stackoverflow.com/questions/39125873/golang-subject-dn-from-x509-cert/50640119#50640119, but thanks for your reply, it is simple to get it from `Names` field (I will update my SO reply with this approach).

I'm using this to get the UID from Apple Push Notifications Certificates since app bundle id is stored there. But I think reading it from Names field is enough for my use case and I can close this issue. Let's reopen if there is more demand for this field.
