### ISSUE TITLE
exp/shiny: windriver: AccessDenied for DestroyWindow

### ISSUE THREAD

**Issue by ktye** [golang/go#25671]
### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?
That should be the case.

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
Trying to close a window programmatically by sending a lifecycle event.
I'll send a comment with a link to an example program.

### What did you expect to see?
The window to disappear.

### What did you see instead?
For the main window this works, but client windows are not destroyed.

### Description
This is a follow up to [CL 115515](https://golang.org/cl/115515).
It's a similar topic but an independent problem.

I tracked it down to `shiny/driver/internal/win32/win32.go:121`
Release calls DestroyWindow on the handle.
Adding a Printf shows that it returns AccessDenied.
I am not sure about the reason, it might be related to "running on the same thread".

### Proposed fix
`shiny/driver/internal/win32/win32.go:121`
Replace `_DestroyWindow(hwnd)` with `SendMessage(hwnd, _WM_CLOSE, 0, 0)`
It works for me.

If you agree that this is the right fix, I'll send a CL.
Should I also remove the TODO's from @andlabs around it? I'm not sure if they are appropriate anymore.

**Comment by ktye** [comment]
To run the example I promised:
`go get github.com/ktye/goissues/25671`

**Comment by andlabs** [comment]
Are you calling `Release` from a different OS thread? `DestroyWindow()` can only destroy windows on the same OS thread. And yeah, you can use `WM_CLOSE` for this; the TODO about `DefWindowProc()` can go away if you do since you'll want that behavior anyway (unless you do that yourself).

**Comment by ktye** [comment]
@andlabs: it might be.
I create the client window in a goroutine, as it should have it's own event loop:
https://github.com/ktye/goissues/blob/master/25671/main.go#L104

I haven't seen any other shiny examples where multiple windows are handled.
Maybe there are none, as this (and my last fix) have not been reported before.
I came across these issues implementing a shiny backend for mjl-/duit.

**Comment by ianlancetaylor** [comment]
CC @nigeltao

**Comment by alexbrainman** [comment]
I will debug this on weekend.

Alex

**Comment by alexbrainman** [comment]
> Release calls DestroyWindow on the handle.
> Adding a Printf shows that it returns AccessDenied.

That error was there all the time.

> I am not sure about the reason, it might be related to "running on the same thread".

I am certain you get that error because DestroyWindows is called on a different thread from the message pump thread. I added GetCurrentThreadId to check.

> Replace _DestroyWindow(hwnd) with SendMessage(hwnd, _WM_CLOSE, 0, 0)
> It works for me.

Sounds good to me.

> If you agree that this is the right fix, I'll send a CL.

Please, do.

> Should I also remove the TODO's from @andlabs around it? I'm not sure if they are appropriate anymore.

Please, remove whatever TODOs you think are inappropriate. We will make final decision once we review your CL.

Thank you.

Alex
