### ISSUE TITLE
gccgo: internal compiler error with cyclic function declaration (esoteric)

### ISSUE THREAD

**Issue by griesemer** [golang/go#25680]
With
```
$ gccgo --version
gccgo (google-gccgo-257955) 8.0.1 20180223 (experimental)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
compiling the following program:
```Go
$ cat x.go
package main

func g() [g()[0]]int { panic(0) }

func main() {
}
```
leads to an internal compiler error:
```
$ gccgo x.go
gccgo: internal compiler error: Segmentation fault signal terminated program go1
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://go.ext.google.com/go/> for instructions.
```

cc: @thanm

**Comment by ianlancetaylor** [comment]
I hope that program is not valid Go.

**Comment by griesemer** [comment]
I don't think it is. But it probably shouldn't crash. But certainly not important in any case. Just reporting another test case for the cycle test suite...

**Comment by thanm** [comment]
Related to https://github.com/golang/go/issues/25315, https://github.com/golang/go/issues/25677, https://github.com/golang/go/issues/25299. Should be able to fix them together (at least for gccgo).

**Comment by deanveloper** [comment]
> I hope that program is not valid Go.

It isn't. Array lengths are defined [as follows](https://golang.org/ref/spec#ArrayLength): 
```
The length is part of the array's type; it must evaluate to a non-negative constant representable by a value of type int.
```

Since `[g()[0]]int` is an array, and `g()[0]` is not a _constant_ this is not valid Go.
