### ISSUE TITLE
cmd/go: go get github.com/rsc/vgotest5 fails

### ISSUE THREAD

**Issue by rsc** [golang/go#25687]
go get github.com/rsc/vgotest5 should work with the latest Go 1.9 release branch yet does not. rsc to fix.

/cc @andybons

**Comment by rsc** [comment]
@gopherbot backport Go 1.9 Go 1.10

This is actually present everywhere; you just have to start with nothing in GOPATH and ask for vgotest5 directly (without doing vgotest4 first).

**Comment by rsc** [comment]
@gopherbot **PLEASE** backport Go 1.9 Go 1.10

**Comment by rsc** [comment]
(Seriously? We've gone [full-on Jurassic Park](https://www.youtube.com/watch?v=RfiQYRn7fBg)? What purpose does this serve?)

**Comment by andybons** [comment]
When the robot uprising inevitably occurs we can at least say we were polite.

**Comment by rsc** [comment]
Getting off-topic for this issue but the best technical rationale I can see is that having an indicator word beyond the @-reference avoids false triggering the bot, so that it wouldn't trigger on someone saying "why did (AT)gopherbot backport that CL?". Otherwise you're just playing simon says for no good reason.

**Comment by andybons** [comment]
@FiloSottile for the gopherbot semantics.

**Comment by FiloSottile** [comment]
I indeed came up with it as a false positive mitigation for such a high-touch action with cases like you mentioned in mind, but I'll admit I did not consider alternatives because I do like the idea of having to be nice in comments, even to the bot.

Opened #25700 for documenting @gopherbot actions.
