### ISSUE TITLE
proposal: Go 2:Providing more and more high performance CGO？

### ISSUE THREAD

**Issue by cjmxp** [golang/go#25681]
Providing more and more high performance CGO？

**Comment by AlbinoGeek** [comment]
@cjmxp What is that even supposed to mean?

Please read the [Contributing Guidelines](https://golang.org/doc/contribute.html)

**Comment by bradfitz** [comment]
Yeah, what @josharian said. This doesn't fit the form of a proposal. Existing bugs track cgo performance.
