### ISSUE TITLE
channel <- time.Now(). Program reached a deadlock

### ISSUE THREAD

**Issue by IanVinkHub** [golang/go#25685]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64

### Does this issue reproduce with the latest release?
Running latest, so yes.

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\NAME\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\NAME\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\NAME\AppData\..\Local\Temp\go-build444259750=/tmp/go-build -gno-record-gcc-switches

### What did you do?
When running the following code it wil never print after time.Now()
If I do not run channelHandler() in a goroutine it says it reached a deadlock.

```
package main

import (
	"fmt"
	"time"
)

func main() {
	go channelHandler()

	for {
	}
}

func channelHandler() {
	tickRunner := make(chan time.Time)

	fmt.Println("before time.now()")
	tickRunner <- time.Now()
	fmt.Println("after time.now()")

	select {
	case t := <-tickRunner:
		fmt.Println(t)
	}

}

```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
after time.Now() printed in console and it running the tickRunner once

### What did you see instead?
after time.Now() not printed in console

**Comment by davecheney** [comment]
tickRunner is an unbuffered channel so the send of time.Now cannot succeed without a receive reading in another goroutine. 

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
