### ISSUE TITLE
x/mobile: debug symbol for gomobile bind works if running on iOS simulator, but not on actual phone

### ISSUE THREAD

**Issue by biscottigelato** [golang/go#25704]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Tried both of the following:
go version devel +3363e98371 Mon Apr 23 16:00:55 2018 +0000 darwin/amd64
go version devel +161874da2a Fri Jun 1 21:52:00 2018 +0000 darwin/amd64

### Does this issue reproduce with the latest release?

No, latest release 1.10.2 does not have DWARF enabled for darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/biscottigelato/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/biscottigelato/gocode"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_6/47d5qynn28j8334nlr23wmnh0000gn/T/go-build592797820=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

$ gomobile bind -target=ios -v -o ios/hello.framework golang.org/x/mobile/example/bind/hello

### What did you see instead?

DWARF symbol for the framework built using gomobile works if running on an iOS simulator, but not on an actual phone. Is there any possible solutions here?

<img width="1143" alt="screen shot 2018-06-02 at 01 32 49" src="https://user-images.githubusercontent.com/24286268/40872568-53f71e46-6605-11e8-9ef6-f40bc1c0ae40.png">

<img width="1141" alt="screen shot 2018-06-02 at 01 33 13" src="https://user-images.githubusercontent.com/24286268/40872570-579819d8-6605-11e8-9c01-4aadb10253b6.png">

**Comment by phpmaple** [comment]
Can gomobile generate CocoaTouch dynamic framework? default static framework, maybe it conflicts with other static libs

**Comment by agnivade** [comment]
@steeve @hyangah

**Comment by steeve** [comment]
Try with 1.12.7, there were a lot of fixes done in the last year on DWARF.
