### ISSUE TITLE
x/net/html: Incorrect parsing of form elements within a template element

### ISSUE THREAD

**Issue by a9y** [golang/go#25703]
### What version of Go are you using (`go version`)?

go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"

### What did you do?

The current implementation of the html parser generates an invalid tree when it encounters a `form` element nested inside a `template` element. Every successive sibling to the form will be inserted as children instead.

I encountered this when parsing YouTube's new polymer design. A stripped down version of the section in question:

```html
<template>
  <yt-icon-button></yt-icon-button>
  <form>
    <paper-input></paper-input>
  </form>
  <style></style>
</template>
```

### What did you expect to see?

The following test inside `testdata/webkit/template.dat` to succeed:

```
#data
<body><template><yt-icon-button></yt-icon-button><form><paper-input></paper-input></form><style></style></template>
#errors
#document
| <html>
|   <head>
|   <body>
|     <template>
|       content
|         <yt-icon-button>
|         <form>
|           <paper-input>
|         <style>
```

### What did you see instead?

```
--- FAIL: TestParser (0.04s)
	parse_test.go:233: testdata/webkit/template.dat test #91 "<body><template><yt-icon-button></yt-icon-button><form><paper-input></paper-input></form><style></style></template>", got vs want:
		----
		| <html>
		|   <head>
		|   <body>
		|     <template>
		|       content
		|         <yt-icon-button>
		|         <form>
		|           <paper-input>
		|           <style>
		----
		| <html>
		|   <head>
		|   <body>
		|     <template>
		|       content
		|         <yt-icon-button>
		|         <form>
		|           <paper-input>
		|         <style>
		----
```

The issue can be resolved by applying the following patch. However, beyond passing the tests associated with the package, no other testing has been performed.

```diff
diff --git a/html/parse.go b/html/parse.go
index d23e05e..4739e28 100644
--- a/html/parse.go
+++ b/html/parse.go
@@ -1103,10 +1103,6 @@ func inBodyIM(p *parser) bool {
 					return true
 				}
 				p.generateImpliedEndTags()
-				if p.tok.DataAtom == a.Form {
-					// Ignore the token.
-					return true
-				}
 				p.popUntil(defaultScope, a.Form)
 			} else {
 				node := p.form
```

**Comment by meirf** [comment]
cc @nigeltao

**Comment by namusyaka** [comment]
Thanks for your report!
I'm going to take a look at the issue, in a few days.

**Comment by namusyaka** [comment]
@a9y Sorry for late response.
I have just mailed my patch for fixing this issue. Could you take a look?
