### ISSUE TITLE
net/url: URL should implement UnmarshalText, not just UnmarshalBinary

### ISSUE THREAD

**Issue by aviau** [golang/go#25705]
The URL struct of net/url only implements UnmarshalBinary.

I think that it should also implement UnmarshalText (it would be the same code)

There are parsers that depend on this.

net/url UnmarshalBinary's signature even names the []byte argument "text":
```golang
func (u *URL) UnmarshalBinary(text []byte) error
```

**Comment by mvdan** [comment]
Have you had a look at the source code?

```
// Marshaling interface implementations.
// Would like to implement MarshalText/UnmarshalText but that will change the JSON representation of URLs.

func (u *URL) MarshalBinary() (text []byte, err error) {
        return []byte(u.String()), nil
}

func (u *URL) UnmarshalBinary(text []byte) error {
        u1, err := Parse(string(text))
        if err != nil {
                return err
        }
        *u = *u1
        return nil
}
```

In particular, read the commit that added this code - 659570915481c87559f0197c9980e8cbac8e2c33. It seems like adding what you suggest would break existing code. Perhaps this can be left for Go2, or for any other opportunity where backwards compatibility can be broken in this package.

**Comment by bontibon** [comment]
Duplicate #10275

**Comment by mvdan** [comment]
Thanks, @bontibon. It indeed makes sense to group all of these under one umbrella issue for Go2.

**Comment by aviau** [comment]
I don't understand.

> Would like to implement MarshalText/UnmarshalText but that will change the JSON representation of URLs.

Only implementing UnmarshalText wouldn't change the JSON representation of URLs.

What is wrong with only implementing the parsing portion?
