### ISSUE TITLE
x/build/cmd/gopherbot: document gopherbot actions and commands

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25700]
As the @gopherbot skills grow more interactive, we need somewhere to document how the commands work.

**Comment by bradfitz** [comment]
A wiki page would be good.

/cc @dmitshur

**Comment by FiloSottile** [comment]
We have one! https://github.com/golang/go/wiki/gopherbot

Might be worth backfilling the automated operations as well, but it has the interactive ones.

**Comment by mark-rushakoff** [comment]
I was looking for Gopherbot's documentation today, and I clicked on its GitHub profile but I completely missed that the profile had a link to the wiki. Maybe it would be a little more helpful if Gopherbot had a profile that said something like "I help organize Go project issues. Visit my wiki link to learn how I can assist you."

**Comment by dmitshur** [comment]
@gopherbot's profile now has a link to its wiki page (https://golang.org/wiki/gopherbot).

I'll close this because everything that was mentioned here seems done, but feel free to reopen or make a new issue if there's more to do.
