### ISSUE TITLE
x/debug: setting debug breakpoints by file/line broken

### ISSUE THREAD

**Issue by fabxc** [golang/go#25715]
* go1.10.2
* linux/amd64

I tried to setup the GCP cloud debugger for a Go application but it fails to set breakpoints with: `error setting breakpoint at scrape/scrape.go:818: couldn't find file "scrape/scrape.go"`.

I reproduced this locally by loading a compiled Go program with `golang.org/x/debug/local.New`. Calling `Program.BreakpointAtLine("scrape/scrape.go", 818)` fails with the same error. Using more specific paths (e.g. full file path at compile time) does not change anything.  
Setting a breakpoint directly through symbol name with `Program.BreakpointAtFunction` works.

When re-compiling the debugged program with go1.9, `BreakpointAtLine` works without issues again.
In both cases the binary was compiled with `-gcflags='-N -l'` and `CGO_ENABLED=0`.

This [blog post](https://medium.com/google-cloud/stackdriver-error-reporting-part-2-826f40e00886) reported a similar problem some time ago. I could not find a matching issue though.

**Comment by heschik** [comment]
I thought this might be the change to DW_AT_comp_dir in  [CL 74790](golang.org/cl/74790) but looking at the code for LineToBreakpointPCs that's giving the error, it seems like it should be resilient to that.

https://github.com/golang/debug/blob/cb5e6d581c5b9d2e229187cecb199106564df20e/dwarf/line.go#L47-L94

So I'm not sure offhand. @fabxc, can you put your repro somewhere I can try it?

cc @zombiezen

**Comment by fabxc** [comment]
Thanks for looking into this. The following gist shows a minimal example: https://gist.github.com/fabxc/99c9f81adafda4969deafad94ed14224

**Comment by heschik** [comment]
Ouch. x/debug/dwarf (this code doesn't exist in pkg/debug/dwarf) assumes that there's only one CU:
https://github.com/golang/debug/blob/cb5e6d581c5b9d2e229187cecb199106564df20e/dwarf/cache.go#L146
and we switched to CU-per-package in 1.10.

Fixing it probably isn't too hard but requires more than a couple minutes of thought to do right.

**Comment by fabxc** [comment]
Seems like any related code was purged from `x/debug`. So this can probably be closed?

The Go cloud debugger agent vendored the former `x/debug` and took the bug with it. Any recommendations on how to address the issue there?

**Comment by jba** [comment]
Moving to GoogleCloudPlatform/google-cloud-go#1079.
