### ISSUE TITLE
net/http/httputil: ReverseProxy doesn't handle empty path

### ISSUE THREAD

**Issue by shellfly** [golang/go#25710]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hao/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hao/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wc/gl6jp38s3lqdprky1txx23mr0000gn/T/go-build181870961=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

```go
package main

import (
	"net/http"
	"net/http/httputil"
	"net/url"
)

func main() {
	url, _ := url.Parse("http://localhost:9000/b")
	http.Handle("/api/a", http.StripPrefix("/api/a", httputil.NewSingleHostReverseProxy(url)))
	http.ListenAndServe(":9001", nil)
}
```

### What did you expect to see?
proxy to `http://localhost:8000/b`

### What did you see instead?
proxy to `http://localhost:8000/b/`, adding an extra slash.

[this line](https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L95) add a slash even if url path is empty. is this expected behavior or a bug?

**Comment by meirf** [comment]
Here's a more complete reproduction:

origin server:
```
func main() {
	http.HandleFunc("/b", func(rw http.ResponseWriter, r *http.Request) {
		rw.Write([]byte("handle /b"))
	})
	http.HandleFunc("/b/", func(rw http.ResponseWriter, r *http.Request) {
		rw.Write([]byte("handle /b/"))
	})
	http.ListenAndServe(":9000", nil)
}
```
proxy:
```
func main() {
	url, _ := url.Parse("http://localhost:9000/b")
	http.Handle("/", httputil.NewSingleHostReverseProxy(url))
	http.ListenAndServe(":9001", nil)
}
```

request: 
`curl http://localhost:9001`

> this line add a slash even if url path is empty.

Actually url path is not empty. url path is "/". So it's joining: "/b" + "/" == "/b/".

**Comment by shellfly** [comment]
@meirf if you use `StripPrefix` it will generate an empty url Path ""

**Comment by meirf** [comment]
@shellfly Sorry I was wrong about your case. But I think the case I've included above is similar. In both cases users probably wouldn't expect a "/" suffix:

Your case: "/b" + "". Expect "/b", actual "/b/".
My   case  "/b" + "/". Expect "/b", actual "/b/".

**Comment by joekyo** [comment]
The empty url Path _""_ generated by StripPrefix is OK. If _"/"_ is generated instead, the request to _/b_ will become _/b/_ when it reach the backend server.
To make your code works as you expected, I guess the function `singleJoiningSlash(a, b string)` should check `b` first, and return `a` directly if `b` is an empty string.

**Comment by shellfly** [comment]
@joekyo yes, this is what I thought, or we can do this check before `singleJoiningSlash`, since the function itself doing the correct thing of joining two paths.

**Comment by seankhliao** [comment]
I believe this is working as intended. "" is never a valid path in http.
