### ISSUE TITLE
Unable to edit GOGCCFLAGS variable

### ISSUE THREAD

**Issue by EgeBalci** [golang/go#25711]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="386"
GOBIN=""
GOCACHE="/home/ege/.cache/go-build"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="windows"
GOPATH="/home/ege/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m32 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build225967565=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

I am trying to generate 32 bit PE file from a 64 bit linux machine with a custom PE image base address. I've tried to append related GCC parameter `-Wl,--image-base=0x500000` to existing GOGCCFLAGS variable with executing `export GOGCCFLAGS="-Wl,--image-base=0x500000 -m32 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build225967565=/tmp/go-build -gno-record-gcc-switches"` but apparently it does not work. I don't know if this is the right way to change the PE image base but i couldn't find any related linker parameters on the docs.

### What did you expect to see?

I was expecting to see the new GOGCCFLAGS value when i run `go env`

### What did you see instead?

GOGCCFLAGS didn't changed.

**Comment by alexbrainman** [comment]
> I don't know if this is the right way to change the PE image base but i couldn't find any related linker parameters on the docs.

I could be wrong, but I think you wanted to use -T linker flag (see `go tool link` for full flag list).

Unfortunately for you, I doubt -T flag works for PE executables. You are the first who asked for this.

Alex

**Comment by EgeBalci** [comment]
I am trying to think a workaround with using preprocessor commands inside the code like C/C++. Does go support such think ?

**Comment by ianlancetaylor** [comment]
This is an unfortunate inconsistency in the `go env` output.  What `go env` displays for `GOGCCFLAGS` is controlled by the `CC` environment variable.  Using `go env GOGCCFLAGS` is convenient for scripts. 
 The environment variables you can actually change are documented at https://golang.org/cmd/go/#hdr-Environment_variables .

But as @alexbrainman changing that seems unlikely to work anyhow.

I'm going to close this because I don't think there is anything for us to change in the Go sources.  To solve your problem you will likely get better answers on a forum; see https://golang.org/wiki/Questions .  Thanks.

**Comment by alexbrainman** [comment]
@ianlancetaylor what about my suggestion of using -T cmd/link flag? Isn't -T flag is designed just for such purpose? The code behind the flag is most likely broken. But we can fix it, if it is expected to work.

Thank you.

Alex

**Comment by EgeBalci** [comment]
@alexbrainman I have tried -T parameter in several ways but could not get it to work. And also it is not exactly what i am looking for it sets the .text segment address not the image base.

**Comment by EgeBalci** [comment]
After reading this [https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/pe.go](url) i found that  `PEBASE = 0x00400000` variable is constant and it seems to me that it is not possible to change image base address when linking PE files with go's internal linker. Did a little more research and solved this issue with using a external linker. Following command uses the MingW compiler tool-chain to link golang object files. `go build -o test.exe -ldflags "-v -H windowsgui -linkmode external -extld i686-w64-mingw32-g++-win32 -extldflags -Wl,--image-base,0x500000" test.go` But i think go internal linker needs a option to change image base address, this would be great if some one implements it.

**Comment by ianlancetaylor** [comment]
@alexbrainman As @EgeBalci notes, the cmd/link `-T` option is not the same as the external linker `--image-base` option.  The cmd/link `-T` option corresponds to the external linker `-Ttext` option.

I think that cmd/link's `-T` option is just a holdover from the Plan 9 support.  It's hard to use in any meaningful way in the modern multi-section world.

**Comment by alexbrainman** [comment]
@EgeBalci and @ianlancetaylor thanks for explaining. Sounds reasonable.

Alex
