### ISSUE TITLE
cmd/compile: using unexported identifier causes case mismatch suggestion

### ISSUE THREAD

**Issue by willfaught** [golang/go#25727]
Sorry if this is a dupe. GitHub phrase searches for "unknown field" or "but does have" seem to not return exact matches right now.

### What did you do?

https://play.golang.org/p/Kk_EIikQW8M

```go
var _ = http.Server{doneChan: nil}
```

### What did you expect to see?

```
prog.go:8:30: unknown field 'doneChan' in struct literal of type http.Server
```

### What did you see instead?

```
prog.go:8:30: unknown field 'doneChan' in struct literal of type http.Server (but does have http.doneChan)
```

This seems to be hitting code that mistakenly thinks there's a case mismatch, where I typed "doneChan" but really meant "DoneChan", or vice versa. This was very confusing and took about 10 minutes to understand (in a more complex context on my machine).

**Comment by fraenkel** [comment]
Why? http.Server does have a doneChan.

**Comment by willfaught** [comment]
Are you asking why the error message wrong? It's wrong because:

- Server is in a different package, and I tried to use its unexported "doneChan" field, and there's no exported "DoneChan" field, so trying to use doneChan is clearly wrong, with no possible alternative field worth suggesting. It should just say that there isn't a doneChan field.
- `but does have http.doneChan` makes no sense: doneChan isn't a package-scope var in package http; if anything, it should be `but does have http.Server.doneChan`

**Comment by FiloSottile** [comment]
A couple variations:

https://play.golang.org/p/eDHDcSIeCGa

```
s := http.Server{}
_ = s.DoneChan
```

`s.DoneChan undefined (type http.Server has no field or method DoneChan, but does have http.doneChan)` (also wrong)

```
s := http.Server{}
_ = s.doneChan
```

`s.doneChan undefined (cannot refer to unexported field or method doneChan)` (correct)

/cc @odeke-em @dr2chase

**Comment by griesemer** [comment]
Not urgent.

**Comment by odeke-em** [comment]
Thank you for the report @willfaught, thank you for the investigation and ping @FiloSottile  and thanks @fraenkel and @griesemer for taking a look too.

I hadn't seen, I've been quite swamped but I just got a chance to take a look at it and I've mailed a CL, PTAL.
