### ISSUE TITLE
html/template panics when {{ range }} has no arguments

### ISSUE THREAD

**Issue by watchforstock** [golang/go#25735]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### Does this issue reproduce with the latest release?
Yes (assuming playground is running latest)

### What operating system and processor architecture are you using (`go env`)?
Linux, AMD64

### What did you do?

I accidentally included a `{{ range }}` tag without a variable.

https://play.golang.org/p/a8inCrlhRzM

### What did you expect to see?

I was expecting to see an error returned from the execution

### What did you see instead?

The call panic'ed:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0x170de6]`

**Comment by mvdan** [comment]
I think this is just a typo in the code you pasted. Your error check should be `err != nil`, not `err == nil`. When corrected, `text/template` and `html/template` just error as expected, instead of panicking. The source of the panic was because you were executing a broken/nil template.
