### ISSUE TITLE
x/image/webp: non-Alpha VP8X is not implemented error

### ISSUE THREAD

**Issue by chhatanidinesh** [golang/go#25738]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.6.2

### Does this issue reproduce with the latest release?

Yes
### What operating system and processor architecture are you using (`go env`)?

Mac, amd64
### What did you do?
Resizing of an image.

If possible, provide a recipe for reproducing the error.
image.Decode(bytes.NewReader(bs))

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Image decoding should have worked without error

### What did you see instead?
webp: non-Alpha VP8X is not implemented

**Comment by nigeltao** [comment]
Can you attach an example .webp file that triggers the bug?

**Comment by chhatanidinesh** [comment]
Hi,
This is the webp image which gives this error
https://lh3.googleusercontent.com/Gd45GzTAsvX-JFkM-mBPYjJesdbTrVSrr6kR-rXELsa0i-uIBBg1-HWmQ_LXkQdnEKE=s180-rw

**Comment by pingooStar** [comment]
Same problem here, with https://res-2.cloudinary.com/ssenseweb/image/upload/b_white,c_lpad,g_center,h_960,w_960/c_scale,h_680/f_auto,dpr_1.0/182214F087001_1.jpg

**Comment by DarthSim** [comment]
Hi,
Same problem with this image: https://s3.amazonaws.com/sked-customer-uploads/564a433accc7c331440002f9/83324ed7d9f4291d49e9bba969687b66.orig.jpg

**Comment by totoleo** [comment]
+1

**Comment by jnvillar** [comment]
Any solution to this problem?

**Comment by agnivade** [comment]
Nobody is working on it.

Also, please note our policy on "+1" type comments - https://github.com/golang/go/wiki/noplusone.

**Comment by theoks** [comment]
Same issue here

**Comment by chhatanidinesh** [comment]
https://github.com/chai2010/webp should help
