### ISSUE TITLE
ioutil.ReadAll error when reading from gzip Reader

### ISSUE THREAD

**Issue by ismlsmile** [golang/go#25748]
### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

### What did you do?
This program panic:

package main

import (
	"io/ioutil"
	"bytes"
	"compress/gzip"
)

func main() {
	data := []byte("HelloWorld")

	var b bytes.Buffer
	w := gzip.NewWriter(&b)
	defer w.Close()
	w.Write(data)
	w.Flush()

	r, _ := gzip.NewReader(&b)
	defer r.Close()
	rawData, err := ioutil.ReadAll(r)
	println(string(rawData))
	if err != nil {
		panic(err.Error())
	}
}

The rawData is OK, but ioutil.ReadAll return an error : "unexpected EOF"

**Comment by davecheney** [comment]
Defer is executed at the end of the function call. w is not closed by the time you construct a reader. The reason you get unexpected EOF is the writer is not closed so the end of file marker is missing.
