### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by cre8andctrl** [golang/go#25747]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows Server

### What did you do?

Trying to create a file passing the readstring argument to a function.
Can anyone figure this out? I think the problem might be in the readstring() method when being passed to a function. Please help. Thank you

`//create file
//write to file
//read from file

package main

import (
	"fmt"
	"bufio"
    "log"
    "strings"
    //"io/ioutil"
    "os"
)
	
func main() {
    fmt.Print("Enter filename to create: ")

    reader := bufio.NewReader(os.Stdin)
   
    text, _ := reader.ReadString('\n')
    text = strings.TrimSuffix(text, "\n")
    

    if len(text) > 3 {
    	//newFile, err := os.Create(text)
    	fmt.Println("Name:"+text)
    	createFile(text)
    } else {
    	fmt.Println("invalid filename")
    }

}

func createFile(fileName string){
	var newFile *os.File
	var err error

	
	fmt.Println(fileName)

	newFile, err = os.Create(fileName)
	if err != nil {
        log.Fatal(err)
    }
    newFile.Close()
}
`

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by cre8andctrl** [comment]
Alright no problem.
