### ISSUE TITLE
plugin: intermittent SIGSEGV with plugins that use multiple goroutines with cgo on ppc64le

### ISSUE THREAD

**Issue by laboger** [golang/go#25756]
### What version of Go are you using (`go version`)?
tip, go 1.10 latest

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le

A problem was reported to me by someone trying to build an application that uses plugins which call C code through cgo. They were building and running in a container with many other dependencies but I was able to reproduce it in a smaller program. Their application works on x86 and also if they replace some of their Go code with C code instead of using plugins on ppc64le.

Based on panic traces and objdumps of other plugin objects, I can tell the segv occurs when trying to access data based on r2 within the plugin object. I am still debugging but at this point but it appears that on some path the wrong value of r2 is being restored, possibly after switching a goroutine or thread. I've been trying to debug this using gdb but that seems to also introduce some random behavior.

I will keep debugging my reproducer testcase and will post more information later, but wanted to open this in case there is any ideas on what might be happening.

I think my testcase is correct because it runs successfully on x86.

**Comment by bcmills** [comment]
CC: @laboger and @ceseo for PPC64, and @ianlancetaylor and @cherrymui for plugin.

More precise details would certainly be helpful.  🙂

**Comment by laboger** [comment]
I've been working on a reproducer and trying to understand what causes it to fail since it is intermittent and gdb causes different behavior. But I think I have narrowed it down to just plugins, the original problem used cgo but I have found cgo is not necessary to cause the issue.

In my reproducer, the main program calls a plugin which does some work with multiple goroutines. The testcase can be run multiple times without error but sometimes it gets a SIGSEGV on an instruction that depends on the value in r2 and it is obviously wrong. I think part of the problem is that when plugins are used, the main program is not compiled as PIC or at least it does not generate r2 or save it on the stack. The plugin code has been compiled to generate r2 and save it at 24(r1). However many of the functions in asm_ppc64x.s are expecting that 24(r1) contains the TOC address for r2 and loads it before returning back to its caller.

In theory I think this shoudl be OK because when main calls code in the plugin, it should generate the r2 value and save it. If it calls other functions in the plugin object, it might not regenerate r2 but should always save it on the stack. But obviously there is some scenario where it is reloading a bad r2.

I have a fix that seems to prevent the segv and a testcase to reproduce the problem and will post that shortly.

**Comment by bcmills** [comment]
Hmm, is this possibly related to the bug @ianlancetaylor addressed in https://golang.org/cl/43051?

**Comment by laboger** [comment]
Yes it is related because there are two instructions at the beginning of functions to compute the value for r2 when generating code in an object where it is needed, but if the linker knows it can skip those instructions, it will call function+8 to avoid them.

This problem has to do with ensuring that the value of r2 is always saved on the stack at r1+24 if it might need to be restored at some later point. What makes this case tricky is that some of the code is initializing and saving r2 (the plugin) and some isn't (main code calling plugin). I believe r2 only needs to saved if it is going to be needed so usually doesn't cause a problem but there must be some path that is bad.

**Comment by laboger** [comment]
Sorry I was wrong yesterday, it doesn't seem to reproduce unless the goroutines called by the plugin also use cgo. Some flaw in my testing process apparently. I will post the CL once the linker bug is fixed which breaks ppc64x testing.

**Comment by laboger** [comment]
This should be backported to go 1.10.

**Comment by bcmills** [comment]
@gopherbot, please backport to 1.10.
