### ISSUE TITLE
string([]byte]{128}) is not Ç

### ISSUE THREAD

**Issue by kbudde** [golang/go#25751]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kbudde\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\kbudde\projects\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kbudde\AppData\Local\Temp\go-build109976714=/tmp/go-build -gno-record-gcc-switches

### What did you do?

https://play.golang.org/p/w1B2mB8_JXw

I converted byte 128 to a string.

### What did you expect to see?
I expected a "Ç". 
http://www.theasciicode.com.ar/extended-ascii-code/majuscule-c-cedilla-uppercase-ascii-code-128.html

### What did you see instead?
A different character

**Comment by mvdan** [comment]
Go uses UTF8, not anything like "extended ASCII". https://play.golang.org/p/h4V7NpnK9xV

**Comment by kbudde** [comment]
Hi,

but should the conversion not be reversible?
https://play.golang.org/p/C9o_gVLSiGq
var i int //(0 <= i < 256)
[]byte(string(i)) -> [ i ] and not [ 194 i ]

**Comment by zegl** [comment]
@kbudde It is reversible, https://play.golang.org/p/cWNgFqWYVqE

**Comment by kbudde** [comment]
@zegl  It's not what I meant.

I need a way to print some characters (>=128) in a way that the saved byte is just one byte. So reading the data (from file/db) will retrieve the original byte. (Legacy protocol based on strings).

As you can see here (starting from 128) the conversion uses unicode.
https://play.golang.org/p/C9o_gVLSiGq

To workaround the problem I've created a map for the mapping what delivers the expected results
https://play.golang.org/p/02maWHAPydc
It is quite ugly and unexpected (caused a lot of pain :( )

```
var asciiMap map[byte]string = map[byte]string{
	byte(0):   "\x00",
	byte(1):   "\x01",
	byte(2):   "\x02",
	byte(3):   "\x03",
	byte(4):   "\x04",
	byte(5):   "\x05",
	byte(6):   "\x06",
//....
}

func EncodeToAscii(b []byte) string {
	var s string
	for _, b := range b {
		s = s + asciiMap[b]
	}
	return s
}

```

**Comment by mvdan** [comment]
Please read the spec, in particular the "Conversions to and from a string type" section.
