### ISSUE TITLE
cmd/cover: html renderer shows misleading coverage

### ISSUE THREAD

**Issue by mhilton** [golang/go#25767]
### What version of Go are you using (`go version`)?
go version devel +db49f76dc5 Tue Jun 5 20:31:21 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?
no, 1.10.2 works fine

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?
With the following package:
==> local/x/x.go <==
```
package x

import "fmt"

func X() {
	if false {
		fmt.Printf("Hello")
	}
}
```

==> local/x/x_test.go <==
```
package x_test

import (
	"testing"
	"local/x"
)

func TestX(t *testing.T) {
	x.X()
}
```
Run the following commands:
```
$ go test -coverprofile=/tmp/cover.tmp local/x
$ go tool cover -html=/tmp/cover.tmp
```

### What did you expect to see?
A code listing showing which statements have been executed.

### What did you see instead?
A code listing showing that all statements have been executed.

The relevant snippet of HTML shows:
```
func X() <span class="cov8" title="1">{
        if false <span class="cov0" title="0"></span>{
                fmt.Printf("Hello")
        }</span>
}
```

Using 1.10.2 the equivalent snippet is:
```
func X() <span class="cov8" title="1">{
        if false </span><span class="cov0" title="0">{
                fmt.Printf("Hello")
        }</span>
}
```

**Comment by robpike** [comment]
@dsymonds Is this due to your recent change?

**Comment by dsymonds** [comment]
It certainly sounds like 4fe688c, which fixed a different instance of segment boundaries at the same place being in the wrong order.

**Comment by dsymonds** [comment]
I've got some of the state still in my head; let me see if I can fix this.
