### ISSUE TITLE
Troubles with building cross-compiler for musl libc.

### ISSUE THREAD

**Issue by protonesso** [golang/go#25762]
Hi, everyone! I have some troubles with building golang cross-compiler for musl libc. I patched source with these pacthes:
```
https://git.alpinelinux.org/cgit/aports/tree/community/go/default-buildmode-pie.patch
https://git.alpinelinux.org/cgit/aports/tree/community/go/set-external-linker.patch
```
I'm building host golang(not native). Golang version is 1.10.2.
This is what commands I've used to compile host package:
```
CC_FOR_BUILD="gcc" \
CC_FOR_TARGET="x86_64-linux-musl-gcc" \
GOROOT_FINAL=$TOOLS/usr/lib/go \
GOOS=linux GOARCH=x86_64 ./make.bash -v
```

Here is the error message:
```
# cmd/compile
loadinternal: cannot find runtime/cgo
Building Go toolchain3 using go_bootstrap and Go toolchain2.
go tool compile: fork/exec /go/src/go/pkg/tool/linux_amd64/compile: no such file or directory
go tool compile: fork/exec /go/src/go/pkg/tool/linux_amd64/compile: no such file or directory
go tool compile: fork/exec /go/src/go/pkg/tool/linux_amd64/compile: no such file or directory
go tool dist: FAILED: /go/src/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -v -a -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

I've checked if `compile` linked with musl libc.
```
compile: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
```
As you can see it's linked with musl libc. I'm used Ubuntu 18.04 to build

**Comment by ianlancetaylor** [comment]
`GOARCH=x86_64` is not valid.  I'm surprised this worked at all.  It should be `GOARCH=amd64`.

As I'm sure you understand, in general we can't really support patched versions of the Go distribution.  I recommend that for any problems with this you ask on a forum, rather than on the issue tracker.  See https://golang.org/wiki/Questions .  You are more likely to find someone who can help on a forum than you are here.

**Comment by protonesso** [comment]
Lmao I've used amd64 but the general problem is **THE COMPILE TOOL LINKS
WITH MUSL LIBC BUT IT MUSTN'T**

**Comment by ianlancetaylor** [comment]
If the rest of your command line was accurate, then you told it to build using a musl cross-compiler.  That means that any code that uses cgo, and therefore can not be statically linked, will be built for musl.  You may want to take a look at https://golang.org/cl/112156.  I don't know if it applies to your situation or not.

I will say again that you are more likely to find people who understand this in a forum.
