### ISSUE TITLE
proposal: Go 2: net/http/httptest: Alter ResponseRecorder API to make it harder to misuse the header map

### ISSUE THREAD

**Issue by cespare** [golang/go#25764]
This is follow-up from #8857, #15560, #16717, and #25763.

To quote my summary from #25763:

> [If] you write a header after the body has been written and status has been set in an HTTP handler, that's a bug because it has no effect. If you're testing using an httptest.ResponseRecorder, its HeaderMap will record the header and might make you think that your code is working when it's not. This is #8857. In response to that bug the behavior was changed to snapshot the headers instead, but that caused another problem (#15560) so it was reverted.

For Go 2, we should change the ResponseRecorder API to make it impossible for the user to access any header map that may be mutated after Write/WriteHeader. Allowing that makes it too easy to accidentally think headers are being written when they're buggily being set after the body has already been written.

I haven't given the specifics much thought, but maybe ResponseRecorder should be more opaque and only expose its data via Result.

cc @bradfitz

**Comment by ianlancetaylor** [comment]
Folding into the general rethinking of net/http in #5465.
