### ISSUE TITLE
syscall: TOKEN_ALL_ACCESS inconsistency

### ISSUE THREAD

**Issue by Limard** [golang/go#25775]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
Windows 10
Windows SDK v7.0A
_WIN32_WINNT>0x400

### What did you do?

I'm using Golang to rewrite a C++ Program in Windows

syscall.TOKEN_ALL_ACCESS in golang is 0xF00FF, 
this value is the same as TOKEN_ALL_ACCESS_P in WinNT.h.

But TOKEN_ALL_ACCESS in WinNT.h is 0xF01FF (TOKEN_ALL_ACCESS_P|TOKEN_ADJUST_SESSIONID) when _WIN32_WINNT>0x400

The same name but different value, it is easily to make mistake.

### What did you expect to see?

The value of syscall.TOKEN_ALL_ACCESS is the same as TOKEN_ALL_ACCESS in WinNT.h

### What did you see instead?

syscall.TOKEN_ALL_ACCESS != TOKEN_ALL_ACCESS in WinNT.h

Thanks!

**Comment by ianlancetaylor** [comment]
We've decided that it's OK to change values in the syscall package if they are wrong (https://golang.org/doc/go1compat#operating_systems).

Does golang.org/x/sys/windows also need to be fixed?

**Comment by wingyplus** [comment]
I checked by writing tests

```
package syscall_test

import (
	"syscall"
	"testing"

	"golang.org/x/sys/windows"
)

func TestTOKEN_ALL_ACCESS(t *testing.T) {
	const expected = 0xF01FF
	
	t.Run("syscall", func(t *testing.T) {
		if syscall.TOKEN_ALL_ACCESS != expected {
			t.Errorf("syscall.TOKEN_ALL_ACCESS = %x, want %x", syscall.TOKEN_ALL_ACCESS, expected)
		}
	})

	t.Run("golang.org/x/sys/windows", func(t *testing.T) {
		if windows.TOKEN_ALL_ACCESS != expected {
			t.Errorf("golang.org/x/sys/windows.TOKEN_ALL_ACCESS = %x, want %x", windows.TOKEN_ALL_ACCESS, expected)
		}
	})
}
```
The result is 

```
$ go test -v
=== RUN   TestTOKEN_ALL_ACCESS
=== RUN   TestTOKEN_ALL_ACCESS/syscall
=== RUN   TestTOKEN_ALL_ACCESS/golang.org/x/sys/windows
--- FAIL: TestTOKEN_ALL_ACCESS (0.00s)
    --- FAIL: TestTOKEN_ALL_ACCESS/syscall (0.00s)
        syscall_std_test.go:13: syscall.TOKEN_ALL_ACCESS = f00ff, want f01ff
    --- FAIL: TestTOKEN_ALL_ACCESS/golang.org/x/sys/windows (0.00s)
        syscall_std_test.go:19: golang.org/x/sys/windows.TOKEN_ALL_ACCESS = f00ff, want f01ff
FAIL
exit status 1
FAIL    github.com/wingyplus/syscall_test       0.058s
```

I see implementation in `WinNT.h` is:

```
#define TOKEN_ALL_ACCESS_P (STANDARD_RIGHTS_REQUIRED  |\
                          TOKEN_ASSIGN_PRIMARY      |\
                          TOKEN_DUPLICATE           |\
                          TOKEN_IMPERSONATE         |\
                          TOKEN_QUERY               |\
                          TOKEN_QUERY_SOURCE        |\
                          TOKEN_ADJUST_PRIVILEGES   |\
                          TOKEN_ADJUST_GROUPS       |\
                          TOKEN_ADJUST_DEFAULT )

#if ((defined(_WIN32_WINNT) && (_WIN32_WINNT > 0x0400)) || (!defined(_WIN32_WINNT)))
#define TOKEN_ALL_ACCESS  (TOKEN_ALL_ACCESS_P |\
                          TOKEN_ADJUST_SESSIONID )
#else
#define TOKEN_ALL_ACCESS  (TOKEN_ALL_ACCESS_P)
#endif
```

It needs to add `TOKEN_ADJUST_SESSIONID` constant to both packages and `TOKEN_ALL_ACCESS` needs to or with this constant.

**Comment by alexbrainman** [comment]
> Does golang.org/x/sys/windows also need to be fixed?

Indeed.

Alex
