### ISSUE TITLE
[wasm]cmd/go: error while trying to overwrite a built binary

### ISSUE THREAD

**Issue by agnivade** [golang/go#25774]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version devel +33f1768 Thu Jun 7 01:19:13 2018 +0000 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/agniva/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/agniva/play/go"
GORACE=""
GOROOT="/home/agniva/play/gosource/go"
GOTMPDIR=""
GOTOOLDIR="/home/agniva/play/gosource/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build730496659=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Build any wasm binary with js/wasm env vars. Then build the same binary again.

`GOOS=js GOARCH=wasm gotip build -o binary file.go`
Update code.
Then again - `GOOS=js GOARCH=wasm gotip build -o binary file.go`

### What did you expect to see?
Binary builds fine. Overwrites existing binary. Just like it happens for normal builds for other platforms.

### What did you see instead?
```
go build command-line-arguments: build output "binary" already exists and is not an object file
```
This is annoying during the dev cycle, because now I have to delete the binary every time I need to re-build.

I think we just need to add the wasm magic header in the `objectMagic` slice in [cmd/go/internal/work/exec.go](https://github.com/golang/go/blob/master/src/cmd/go/internal/work/exec.go#L1460) .

Can send a CL if this sounds good.

**Comment by neelance** [comment]
> I think we just need to add the wasm magic header in the objectMagic slice in cmd/go/internal/work/exec.go .

Sounds good.
