### ISSUE TITLE
Case sensitive FileExists function?

### ISSUE THREAD

**Issue by Fookiwara** [golang/go#25786]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOOS: windows
GOARCH: 386

### What did you do?
From windows, I ask a Linux server if file exists?
There are two files inside a folder:
test.mov

I would like to verify if file test.MOV not exists (because case sensitivity is different).

Is it possible in golang?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by mvdan** [comment]
The Go project doesn't use its issue tracker to answer questions. For questions about Go, see https://golang.org/wiki/Questions.

**Comment by bontibon** [comment]
Related tickets worth reviewing: #5441, #18358.  It appears a decision hasn't been made yet on what the correct behaviour should be.
