### ISSUE TITLE
Go runtime error when using specific array type ([4]interface{})

### ISSUE THREAD

**Issue by icza** [golang/go#25780]
### What version of Go are you using (`go version`)?
go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04, amd64; also reproducible on the Go Playground.

### What did you do?

Attempt to run the following app using `go run`, available on the Go Playground: https://play.golang.org/p/zJ5XZMK1EGA

```
package main

import (
	"fmt"
)

func main() {
	a := [4]interface{}{1, 2, 3, 4}
	b := [4]interface{}{1, 2, 3, 4}
	//fmt.Println(a, b, a == b)
	if a == b {
		fmt.Println("ok")
	}
}
```

### What did you expect to see?
Expected to see `"ok"` printed.

### What did you see instead?

The output is the following error:

```
type..eq.[4]interface {}: call to external function
main.main: relocation target type..eq.[4]interface {} not defined
main.main: undefined: "type..eq.[4]interface {}"
```

### Notes:

Note that `go build` succeeds, and if I run the executable binary, it works as expected.

Also if I insert a `fmt.Println()` statement before the `if` statement, the error goes away with `go run` too (try it on the Go Playground: https://play.golang.org/p/wxXyD2D9-iZ):

```
package main

import (
	"fmt"
)

func main() {
	a := [4]interface{}{1, 2, 3, 4}
	b := [4]interface{}{1, 2, 3, 4}
	fmt.Println(a, b, a == b)
	if a == b {
		fmt.Println("ok")
	}
}
```

And output will be as expected:

    [1 2 3 4] [1 2 3 4] true
    ok

**Comment by ALTree** [comment]
I believe this may be a dup of #23546

**Comment by ianlancetaylor** [comment]
Agreed.  Closing as dup.
