### ISSUE TITLE
x/sys/windows: introduce Pointer type and use it instead of uintptr

### ISSUE THREAD

**Issue by perillo** [golang/go#25797]
Commit 4869ec00e8 (syscall: introduce Pointer type and use it instead of uintptr) has not been *backported* to the golang/x/sys/windows package.

I don't know if this is an oversight or a feature.

**Comment by bcmills** [comment]
CC: @aclements (commit author); @alexbrainman and @bradfitz for sys/windows.

This is closely tied to #24820.

**Comment by alexbrainman** [comment]
We need to careful about using newly introduced in go1.11 syscall.Pointer in golang.org/x/sys/windows package. Some people might decide to build the package with previous versions of Go, and that will fail.

Otherwise we should fix golang.org/x/sys/windows too.

Alex

**Comment by bcmills** [comment]
Perhaps a type alias with a build constraint would be appropriate?

**Comment by alexbrainman** [comment]
> Perhaps a type alias with a build constraint would be appropriate?

I just copied code from CL 106275. Hopefully this works for you too.

Alex
