### ISSUE TITLE
gomobile: -target=ios requires XCode

### ISSUE THREAD

**Issue by kiritoxcii** [golang/go#25799]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/douglas/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/douglas/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_g/qgpjv1nj307_crq5_mys9jr00000gn/T/go-build962983649=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
gomobile bind -target=ios -o EasyPGP.framework  github.com/encryptedtimeline/easypgp

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I tried to install this https://github.com/lastochkanetwork/EasyPGP
I have installed last Xcode stable version 'til date

### What did you expect to see?
EasyPGP.framework file

### What did you see instead?
gomobile: -target=ios requires XCode

**Comment by AlexRouSg** [comment]
Did you install the xcode command line tools?

https://github.com/golang/go/wiki/Mobile

> On OS X, you will need to have Xcode Command Line Tools installed.

> Note: target=ios requires the host machine running OS X. You need to obtain a signing identity and download provisioning profiles in order to continue.
