### ISSUE TITLE
net: freebsd-amd64 sendfile implementation is broken.

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#25809]
I was trying to come up with a variation of TestSendfile to reproduce issue #25722 on  our builder, and I end-up with

https://go-review.googlesource.com/c/go/+/117655/2

that fails on freebsd-amd64-11_1 builder with

--- FAIL: TestSendfile (0.00s)
    sendfile_test.go:74: have="ProProPro", but want="Produced "
FAIL

I could be wrong about that test, but all other builders are OK with it. So I suspect that freebsd-amd64 sendfile implementation is broken.

Leaving for others to decide.

Alex

**Comment by tklauser** [comment]
It also seems to be broken (probably in the same way) on dragonfly/amd64: https://build.golang.org/log/ee2bc4ad04e72093b84fbf7f2397f13b4d98e5ed

**Comment by alexbrainman** [comment]
And solaris builder is broken too

https://build.golang.org/log/170fc01900ba1c5c58d0a1caa8d1b3b0c708518f

Alex
