### ISSUE TITLE
Link to pprof documentation is broken

### ISSUE THREAD

**Issue by ijt** [golang/go#25803]
On https://golang.org/pkg/runtime/pprof/, the link to https://github.com/google/pprof/blob/master/doc/pprof.md is broken.
It should be changed to 
https://github.com/google/pprof/blob/master/doc/README.md.

**Comment by agnivade** [comment]
Fixed in master :) https://tip.golang.org/pkg/runtime/pprof/.

Sorry, you will have to wait till next release. Or use tip.golang.org for now.
