### ISSUE TITLE
syscall: arm64: epoll_wait syscall not implemented 

### ISSUE THREAD

**Issue by nplanel** [golang/go#25813]
Please answer these questions before submitting your issue. Thanks!

Seems I found a syscall not implemented in latest golang (and earlier), I assume this is not the only one.
I didn't found any related GH issue to arm64 syscall not implemented or missing, so I created this ticket.

### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Linux apm-mustang 4.16.14-300.fc28.aarch64 #1 SMP Tue Jun 5 16:00:29 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

GOARCH="arm64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/home/user/.gimme/versions/go1.10.3.linux.arm64"
GOTMPDIR=""
GOTOOLDIR="/home/user/.gimme/versions/go1.10.3.linux.arm64/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build763200214=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

package main

import (
	"fmt"
	"syscall"
)

func main() {
	maxEpollEvents := 10
	events := make([]syscall.EpollEvent, maxEpollEvents)

	epollFd, err := syscall.EpollCreate1(0)
	if err != nil {
		fmt.Printf("Failed to create epoll: %s", err)
	}

	_, err = syscall.EpollWait(epollFd, events[:], 200)
	if err != nil {
		fmt.Printf("Failed to  epoll wait: %s", err)
	}
}

### What did you expect to see?
no output

### What did you see instead?
Failed to  epoll wait: function not implemented

**Comment by nplanel** [comment]
syscall epoll_pwait and epoll_wait are supported / tested : fc28 ; glibc 2.27 ; kernel 4.16.14-300.fc28.aarch64

**Comment by ianlancetaylor** [comment]
Use gopath.org/x/sys/unix instead of syscall.

Leaving this open because I suppose we should fix the syscall package too.  But even then you should use gopath.org/x/sys/unix instead.

**Comment by nplanel** [comment]
I tested golang master and it's working fine, could you backport the fix ?

**Comment by tklauser** [comment]
In case we want to backport the fix in `syscall`, this was https://golang.org/cl/115735 (which will be part of the upcoming Go 1.11 release).

**Comment by bradfitz** [comment]
If this is coming in Go 1.11, that's sufficient to close this bug.

This doesn't warrant backporting since there's an obvious workaround: use golang.org/x/sys/unix, which is recommended anyway. The `syscall` package should not be used.
