### ISSUE TITLE
cmd/compile: ssa ARM64 LoweredAtomic[And|Or]8 generates architecturally unpredictable instruction

### ISSUE THREAD

**Issue by matt2909** [golang/go#25823]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +30a63ec Mon Jun 11 12:13:11 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/work/go/go/bin/"
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/work/user/go"
GORACE=""
GOROOT="/work/go/go"
GOTMPDIR=""
GOTOOLDIR="/work/go/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build897149026=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Compiled some code for arm64. Inspected or executed the code sequence generated by LoweredAtomic[And|Or]8. 

### What did you expect to see?

The code to run without generating an illegal instruction.

### What did you see instead?

This generated an illegal instruction panic.

**Comment by matt2909** [comment]
This appears to be due to the sequence emitted by the code in src/cmd/compile/internal/ssa/gen/ARM64Ops.go (from line 604):

`case ssa.OpARM64LoweredAtomicAnd8,
                ssa.OpARM64LoweredAtomicOr8:
                // LDAXRB       (Rarg0), Rtmp                                                                                                                                                                                                                                                                                                                               
                // AND/OR       Rarg1, Rtmp                                                                                                                                                                                                                                                                                                                                 
                // STLXRB       Rtmp, (Rarg0), Rtmp                                                                                                                                                                                                                                                                                                                         
                // CBNZ         Rtmp, -3(PC)                                                                                                                                                                                                                                                                                                                                
                r0 := v.Args[0].Reg()
                r1 := v.Args[1].Reg()
                p := s.Prog(arm64.ALDAXRB)
                p.From.Type = obj.TYPE_MEM
                p.From.Reg = r0
                p.To.Type = obj.TYPE_REG
                p.To.Reg = arm64.REGTMP
                p1 := s.Prog(v.Op.Asm())
                p1.From.Type = obj.TYPE_REG
                p1.From.Reg = r1
                p1.To.Type = obj.TYPE_REG
                p1.To.Reg = arm64.REGTMP
                p2 := s.Prog(arm64.ASTLXRB)
                p2.From.Type = obj.TYPE_REG
                p2.From.Reg = arm64.REGTMP
                p2.To.Type = obj.TYPE_MEM
                p2.To.Reg = r0
                p2.RegTo2 = arm64.REGTMP
                p3 := s.Prog(arm64.ACBNZ)
                p3.From.Type = obj.TYPE_REG
                p3.From.Reg = arm64.REGTMP
                p3.To.Type = obj.TYPE_BRANCH
                gc.Patch(p3, p)
`

The use of STLXRB is constrained unpredictable (according to the Arm Architecture Reference Manual for Armv8-A).

![image](https://user-images.githubusercontent.com/332254/41233800-5e6a0080-6d82-11e8-885e-11ec2168842a.png)

**Comment by matt2909** [comment]
Seems to be related to https://github.com/golang/go/commit/38d35e714a55f2e4bb67caadac7e61f8c1967d88

**Comment by matt2909** [comment]
If I compile something trivial like:

`hello.go:`
```golang
package main

func main() {
    println("Hello")
}
```

with `GOOS=linux GOARCH=arm64 go install hello.go` and then inspect the assembly I can see:

```
   260cc:       085ffc5b        ldaxrb  w27, [x2]
   260d0:       aa04037b        orr     x27, x27, x4
   260d4:       081bfc5b        stlxrb  w27, w27, [x2]
   260d8:       b5ffffbb        cbnz    x27, 260cc <runtime.greyobject+0x1bc>
   260dc:       17ffffc8        b       25ffc <runtime.greyobject+0xec>
   260e0:       f84307fe        ldr     x30, [sp], #48
   260e4:       d65f03c0        ret
```

These code snippets for And8 and Or8 are not guaranteed to work as expected (see above comments), when the s (source) and t (transfer) registers are the same register.

**Comment by odeke-em** [comment]
Thank you for the report @matt2909!

/cc @cherrymui @randall77

**Comment by cherrymui** [comment]
@williamweixiao Does any hardware disallow same src and dst registers for STLXRB?

**Comment by williamweixiao** [comment]
It’s not easy to answer this question since there are so many implementations for Arm designed CPU. So I’ve just consulted our hardware design department and their answer is:
> We can't be sure, but the Armv8-A architecture states that it is unpredictable, so even if it works on current hardware there's no guarantee that it will work on all future hardware. Furthermore it may be failing quietly even on existing hardware, since this incorrect usage is not required to generate a trap.

**Comment by williamweixiao** [comment]
It’s not easy to answer this question since there are so many implementations for Arm designed CPU. So I’ve just consulted our hardware design department and their answer is:
 We can't be sure, but the Armv8-A architecture states that it is unpredictable, so even if it works on current hardware there's no guarantee that it will work on all future hardware. Furthermore it may be failing quietly even on existing hardware, since this incorrect usage is not required to generate a trap.
