### ISSUE TITLE
cmd/nm: TestGoExec failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#25820]
CL [115975](https://golang.org/cl/115975) changed TestGoExec. This test is now failing on Plan 9.

```
--- FAIL: TestGoExec (1.49s)
    nm_test.go:161: want R type for runtime.epclntab symbol, but have D
    nm_test.go:161: want R type for runtime.erodata symbol, but have D
    nm_test.go:161: want R type for runtime.rodata symbol, but have D
FAIL
FAIL	cmd/nm	4.320s
```

See https://build.golang.org/log/b4bb61cd5942848398474e07807984e34817bceb

**Comment by 0intro** [comment]
CC @alexbrainman

**Comment by alexbrainman** [comment]
Sorry about braking plan9 builder. I did not even noticed.

> --- FAIL: TestGoExec (1.49s)
>     nm_test.go:161: want R type for runtime.epclntab symbol, but have D
>     nm_test.go:161: want R type for runtime.erodata symbol, but have D
>     nm_test.go:161: want R type for runtime.rodata symbol, but have D
> FAIL

It probably is not important if `runtime.epclntab` (and others) is "R" or "D". I do not know.

Maybe adjust the test to expect "D" for `runtime.epclntab` on plan9? Maybe just skip that part of the test?

I will let you decide.

Alex

**Comment by 0intro** [comment]
I think it should be fine if we expect "D" runtime.epclntab on Plan 9.
