### ISSUE TITLE
build: macOS builders broken

### ISSUE THREAD

**Issue by josharian** [golang/go#25827]
Broken by https://go-review.googlesource.com/c/go/+/117515.

**Comment by josharian** [comment]
cc @laboger @ianlancetaylor @randall77

**Comment by laboger** [comment]
Is this new test not legal on darwin?
The source files are almost the same as misc/cgo/life except that they were made into a plugin.
Ian asked me to remove the //skip line but I don't know what that does if anything.

**Comment by randall77** [comment]
This is the error we're getting:
```
Undefined symbols for architecture x86_64:
  "__cgoexp_1e283c4f53fb_GoStart", referenced from:
      _GoStart in 000000.o
  "__cgoexp_1e283c4f53fb_GoWait", referenced from:
      _GoWait in 000000.o
```

I'm not sure what is going on here.

```
$ grep _cgoexp_1e283c4f53fb_GoWait _obj/*.{c,h,go}
_obj/_cgo_export.c:extern void _cgoexp_1e283c4f53fb_GoWait(void *, int, __SIZE_TYPE__);
_obj/_cgo_main.c:int _cgoexp_1e283c4f53fb_GoWait;
_obj/_cgo_gotypes.go:func _cgoexp_1e283c4f53fb_GoWait(a unsafe.Pointer, n int32, ctxt uintptr) {
```
That missing identifier is sometimes declared as a function, and sometimes a global variable.
The recent CL didn't change this behavior, but it is strange.
I have no idea if this is related to the issue or not.  Getting "go build" of a plugin to show me all the intermediate artifacts is somewhat challenging...

**Comment by dr2chase** [comment]
Just on a whim, in inl.go, try increasing the cost of panic to 80.
The bug I'm working on might do something evil to the compiler or something similar -- inlined switch statements get slightly wedged, sometimes.

**Comment by ianlancetaylor** [comment]
The object file generated by cmd/link is defining the symbol `_cgoexp_1e283c4f53fb_GoStart`.  The C object file is referring to the symbol `__cgoexp_1e283c4f53fb_GoStart`.   So I think we have an underscore discrepancy, somehow.
