### ISSUE TITLE
cmd/compile: make alias decls work correctly under all circumstances

### ISSUE THREAD

**Issue by griesemer** [golang/go#25838]
[edit: This is now the umbrella issue for work on alias declarations. This includes parameterized alias declarations; see issue #46477. It also includes proper names for aliases in error messages.]

The original fix for #18640 was only partially correct. However, removing that incorrect code leads to another cycle related issue for the test case:
```Go
type (
	e = f
	f = g
	g = []h
	h i
	i = j
	j = e
)
```
~~Left the original, partially correct code in place for now as it's not wrong, it just doesn't cover the expected cases and it appears to circumvent this issue.~~

~~Marking for 1.11 if we get to it but it's not a showstopper.~~

Commented out this test case in test/fixedbugs/issue18640.go for now.

**Comment by griesemer** [comment]
Simpler reproducer:
```Go
type (
	e = []h
	h e
)
```
Yet, the equivalent code (after substituting e with []h) is accepted as expected:
```Go
type h []h
```

**Comment by griesemer** [comment]
(Slightly) simpler reproducer:

```Go
package pkg
type P = *T
type T P
```

The code is accepted if the order of the type declarations is swapped. The bug is likely in type-checking alias declarations that refer to defined type that have not yet been set up and which refer back to the alias type. We end up with an incorrect `type T T` and `dowith` goes belly up.

**Comment by griesemer** [comment]
This bug (and the related bugs) are due to an incorrect implementation of type aliases in the presence of cycles. The bug(s) can be made to disappear by re-ordering the code (though it may not be obvious, and it may not always be possible). Furthermore, the actual underlying problem was hidden by a typo in the cycle-detection code which left the code "surprisingly correct". Here's this first problem:

In function typecheck (typecheck.go), when we detect a typechecking look (n.Typecheck() == 2), in the case of n.Op == OTYPE where we are expecting a type, we check if the loop contains any (non-alias) type definition. If so, the cycle is permitted (for now, it may still be invalid when we compute the type size). However, if we find a non-alias type definition, instead of returning the incoming node, we return the node we found in the loop (because the loop iteration variable is also named n)! Thus we continue with the wrong type which happens to be a defined type node that has a TFORW type attached to it and then much of the rest "works" w/o blowing up, albeit incorrectly. Once we fix this, in code with alias cycles, the type-checker will simply crash.

To correctly fix this in all situations we (very likely) have to bite the bullet and introduce a TALIAS type which is simply a forwarder to the actual type, very similar to the existing TFORW, except that we won't be able to simply update the TALIAS type to the underlying type since in general we cannot have two versions of the (underlying) type - they must be the same type (pointer). To make this work, we must ensure that all accesses to a Type always forward to the aliased type if the type is a TALIAS.

So the fix is about as follows:

1) Introduce a new Etype TALIAS, update the Type data structure as needed.
2) Fix the "first" problem mentioned above.
3) When type-checking an alias declaration, introduce a TALIAS type which serves as the anchor when we run into a cycle.
4) Make sure that we always indirect through TALIAS types if we encounter them.

Much of 4) can be achieved my accessing Type information only via accessors and the accessors take care of the forwarding. Alternatively (and perhaps more efficiently), the accessors verify that we never access a TALIAS (which they already do by virtue of checking the Etype is correct), and making sure we resolve TALIAS types before calling accessors.

**Comment by ianlancetaylor** [comment]
Another example, reported to golang-nuts:

```Go
package main

func newA(c funcAlias) A {
	return A{c: c}
}

type B struct {
	a *A
}

type A struct {
	c funcAlias
}

type funcAlias = func(B)

func main() {}
```

**Comment by JakeMakesStuff** [comment]
Just had this issue crop up in my codebase: https://github.com/JakeMakesStuff/gommand/blob/90187b3d2f3c55ab8c433e6763321486e329956b/category.go#L8

If I make that line `[]PermissionValidator` it crashes with an internal error relating to this issue. I will try and make a simpler example later today.

**Comment by griesemer** [comment]
@JakeMakesStuff Thanks for the report - don't spend too much time on extracting a simpler example as we do have a pretty good idea why this is broken (but the fix requires some re-engineering). This is something we're trying to address, ideally for 1.16.

**Comment by ZenLiuCN** [comment]
I just get this error as well.
`.\blue-print.go:63:2: internal compiler error: cannot handle alias type declaration (issue #25838): Fragment`
And I found that there was a source file been named as `Runtime.go`, after rename it into `runtime.go` sames that everthing just fine.

**Comment by ianlancetaylor** [comment]
@ZenLiuCN That sounds like a different bug.  Would you mind opening a new issue with complete instructions for how to reproduce the problem?  Thanks.

**Comment by ZenLiuCN** [comment]
> @ZenLiuCN That sounds like a different bug. Would you mind opening a new issue with complete instructions for how to reproduce the problem? Thanks.

opening at #40655. It's really a wired thing, that only happened about the source file naming .

**Comment by dmitshur** [comment]
This issue is currently labeled as early-in-cycle for Go 1.16.
That [time is now](https://groups.google.com/d/msg/golang-dev/qtxOW0x4Rrw/0rB32h12BQAJ), so this is a friendly ping so the issue is looked at again.

**Comment by griesemer** [comment]
We have lived with this for a while now, it's unfortunate but seems not urgent. This will have to wait for the major type-checker overhaul that we hope to do if we go forward with generics.

**Comment by denisvolin** [comment]
I'm really sorry, I've tried to figure out the way to reproduce the same bug in a simpler version, yet, I fail in that task, which may have the connection to the bug itself.

I've got a library, which has an internal type alias for the internal type. There's bunch of constructor functions, which return either an original type or an alias and they work out fine, until I add a new function in a .go file inside the library, and that function returns a pointer to the aliased type, by calling one of the previously defined functions, returning the pointer to the aliased type with prepared arguments (a simplified constructor). 

If I rename new_file.go to new_file.gone the compilation goes through normally (go build in the library folder); if I keep the *.go extension, the compilation fails with the current issue (#25838); if I rename the used return type of the simplified constructor to the original type, whilst still calling the constructor, which returns the aliased type internally, compilation goes through normally either.

I've tried to mock a simple library to show the issue, yet, no matter how I try, I cannot reproduce it elsewhere.

For now, I just keep the returned argument type of the simplified constructor as the original type, not the aliased one, it's just the naming convenience alias only: Field (is the original type name), Argument (is the aliased type name), yet, the issue is really weird.

I'm open for deliverying any additional information necessary, yet, additional problem here, is that the source code is proprietary, and I just cannot publish it wherever I want =/

**Comment by griesemer** [comment]
Again too late for this cycle. Pushing to 1.18.

**Comment by OneOfOne** [comment]
I just ran into this.

**Comment by mdempsky** [comment]
I think at this point, we're not going to fix this in typecheck. But the switch to types2 should help.

types2 correctly handles the first two examples. It does not handle the [3rd example](https://github.com/golang/go/issues/25838#issuecomment-448746670) though: it looks like the `c funcAlias` field ends up with type `types2.Invalid` even though types2 doesn't report a type checker error.

**Comment by griesemer** [comment]
cc: @findleyr

**Comment by mdempsky** [comment]
Here's a minimized repro of the go/types failure: https://play.golang.org/p/oZ9S6AQ6p3F

It prints `struct{c invalid type}`. It should print `struct{c func(p.B)}` (or `struct{c p.funcAlias}`).

**Comment by cagedmantis** [comment]
This issue is currently labeled as early-in-cycle for Go 1.18.
That [time is now](https://groups.google.com/g/golang-dev/c/g2aGRJQIGzw/m/m7hkf2YiAAAJ), so this is a friendly ping so the issue is looked at again.

**Comment by griesemer** [comment]
With #46477 accepted, we will need to review handling of aliases during type checking, so moving this to 1.19.

**Comment by vellotis** [comment]
For awareness, I just ran into this bug.

**Comment by griesemer** [comment]
Moving this to 1.20. The 1.19 cycle is very short and we don't have a concrete plan for this yet.

**Comment by gqcn** [comment]
I just ran into this issue `internal compiler error: cannot handle alias type declaration (issue #25838): HandlerFunc`

**Comment by griesemer** [comment]
@gqcn You may be able to work around the issue with some clever reordering of the code. In any case, sadly we won't have the bandwidth to handle this before 1.20, I think.

**Comment by griesemer** [comment]
We're unlikely to get to this in this cycle. Moving forward again.

**Comment by griesemer** [comment]
We now have support for Alias nodes which can be enabled with `GODEBUG=gotypesalias=1` which addresses these issues.
Closing this in favor of more fine-grained issues related to outstanding alias problems when Alias nodes are enabled.
