### ISSUE TITLE
test: add test that we don't optimize string([]byte(string))

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25834]
From discussion with @golang/proposal-review related to #25805 but mostly unrelated,

We should verify that we have or add a test that `string([]byte(s))` doesn't reduce to just `s` ever. We should test that we always make a copy and return a new string with a new (internal) data pointer.

@rsc mentioned as a use case making a copy of a small part of a large string to prevent the GC from retaining the large string.

/cc @martisch @josharian

**Comment by josharian** [comment]
Echoing @rsc (over in #25805): Given that almost no one will know what `string([]byte(s))` does beyond being a no-op at first glance, it seems like a properly-named function would be a lot clearer than a magic compiler non-optimization.

Maybe adding package `strings` or `runtime` API instead would be better.

**Comment by bradfitz** [comment]
Except that `string([]byte(s))` already exists in the wild for this purpose. We don't want to break that old code.

**Comment by martisch** [comment]
I agree we can add a test to not accidentally break existing code.

But I also would say that a strings.Copy function or alike (that only allocates once instead of twice) would be nice to replace existing uses of string([]byte(s)) (which afaik the language spec does not mandate needs to allocate) and can be a new faster alternative. New proposal issue?

**Comment by bcmills** [comment]
> We should verify that we have or add a test that `string([]byte(s))` doesn't reduce to just `s` ever.

Well, to be precise, that should be allowed if (and only if) `s` is its complete allocation. (That is, it's fine to avoid constructing a new, minimal copy if `s` is already minimal.)
