### ISSUE TITLE
x/mobile: net.UDPConn.ReadFromUDP don't return error when i use net.UDPConn.Close()

### ISSUE THREAD

**Issue by happyEgg** [golang/go#25839]
Please answer these questions before submitting your issue. Thanks!
I'm trying to ship a golang binary inside a android app
conn, err := net.DialUDP("udp", nil, raddr)
if err != nil{
//xxxx
}

size, raddr, err1 := conn.ReadFromUDP(buffer[:])

It's working。but when i use conn.Close()，err1 don't return error，it's waiting for ReadFromUDP
iPhone is ok.

### What version of Go are you using (`go version`)?
go1.10.2

gomobile is last

**Comment by bcmills** [comment]
There is not enough information in this report to diagnose the issue. Please include a complete, self-contained code example if possible, ideally as a runnable program in the [playground](https://play.golang.org/).

**Comment by bcmills** [comment]
CC: @eliasnaur

**Comment by eliasnaur** [comment]
Apart from the self-contained example, is this reproducible on a regular Linux?

**Comment by happyEgg** [comment]
I also use it on android and iOS，iOS is ok，but android don't return error。I guess that the bottom of Android don't return error code
