### ISSUE TITLE
compress/flate: “corrupt input before offset” decompressing stream produced by zlib

### ISSUE THREAD

**Issue by slavablind91** [golang/go#25846]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
I try to decompress stream from zlib library(deflate compression rfc1951) with Go package compress/flate. I've got error: "corrupt input before offset".
If decompress same stream with zlib library, then it's ok.

Example code: https://play.golang.org/p/sPp3uqGuHzI

### What did you expect to see?
In example, byte array contains bytes from zlib deflate function output. An expected decompressed data is: "Hello Hello Hello Hello Hello Hello!"

### What did you see instead?
flate: corrupt input before offset

**Comment by bcmills** [comment]
> byte array contains bytes from zlib deflate function output

Can you give a command line or program that produces that output?

I get a different output using `zlib-flate` on my machine:
```
~$ echo -n 'Hello Hello Hello Hello Hello Hello!' | zlib-flate -compress | hexdump -v -e '/1 "%1u, "'
120, 156, 243, 72, 205, 201, 201, 87, 240, 192, 71, 42, 2, 0, 232, 207, 12, 122,
```

However, even with that input I can reproduce the “corrupt input before offset” error:
https://play.golang.org/p/ohVxnLuOact

**Comment by bcmills** [comment]
CC @dsnet @mdempsky for `compress/flate`.

**Comment by bcmills** [comment]
I can confirm that `zlib-flate -uncompress` interprets your original encoding as the expected string too:

```
~$ echo -ne 'x\xda\xf3H\xcd\xc9\xc9W\xf0\xc0G*2' | zlib-flate -uncompress
Hello Hello Hello Hello Hello Hello!
```

**Comment by dsnet** [comment]
This is not a [DEFLATE stream](https://www.ietf.org/rfc/rfc1951.txt), but rather is a [ZLIB stream](https://www.ietf.org/rfc/rfc1950.txt). Changing the decompressor from DEFLATE to ZLIB decompresses the data: https://play.golang.org/p/AJLlyc8H_jr

Both DELFATE and ZLIB lack magic numbers, so it is impossible to distinguish between the two with perfect accurancy. However, the data stream here starts with 0x78, which is a very common for a ZLIB stream as it indicates that the DEFLATE was used under the hood with a window size of 32KiB.
