### ISSUE TITLE
gccgo: duplicate write barrier for global

### ISSUE THREAD

**Issue by thanm** [golang/go#25867]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

gccgo tip:
go version go1.10.2 gccgo (GCC) 9.0.0 20180608 (experimental) linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"

### What did you do?

For this program:

```
package small

type S struct {
	N *S
	K int
}

var G *S = &S{N: nil, K: 101}

```

If you compile with gccgo and look at the AST generated for the preinit of the global G, the compiler has inserted a duplicate write barrier call. [Note: currently you have to use the debugger to see this, at the moment global preinits are not included in the AST dump]. Here is the tree:

```
// preinit block for var G
{
  tmp.55382992 = &(G)  // x.go:8
  tmp.55383408 = (.1go.small.S)(&((go.small.S){nil,101}))  // x.go:8
  if (runtime.writeBarrier == 0)  // x.go:8
  {
    tmp.55385344 = tmp.55382992 // x.go:8
    if (runtime.writeBarrier == 0)  // x.go:8
    {
      *(tmp.55385344)  = tmp.55383408 // x.go:8
    }
    else
    {
      writebarrierptr((.1.4void.5)(tmp.55385344) ,(.1.4void.5)(tmp.55383408) )  // x.go:8
    }
  }
  else
  {
    writebarrierptr((.1.4void.5)(tmp.55382992) ,(.1.4void.5)(tmp.55383408) )  // x.go:8
  }
}
```

### What did you expect to see?

Single write barrier call

### What did you see instead?

Nested/duplicate write barrier. For this specific example I think it won't impact the generated code (optimized will delete second call) but it seems as though it is worth cleaning up.

**Comment by ianlancetaylor** [comment]
Thanks for spotting that.
