### ISSUE TITLE
cmd/vet: should not complain about format %q used with []string

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25869]
In https://go-review.googlesource.com/c/tools/+/118557 @griesemer is adjusting valid code just to appease vet.

I suspect that vet is wrong here and it should permit %q with []string.

/cc @robpike

**Comment by andybons** [comment]
@alandonovan

**Comment by griesemer** [comment]
Minor correction: The argument is []interface{} not []string.

**Comment by bradfitz** [comment]
Ah, never mind then.

(Too) early morning here. Can't read apparently.
