### ISSUE TITLE
os: OpenBSD: TestFifoEOF hangs

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#25877]
On amd64 OpenBSD 6.2, the new os test `TestFifoEOF` simply hangs until the overall test times out.  I don't know why.  It seems to be true whether or not we poll on fifos, so it seems like a basic fifo problem. 
 I'm going to skip the test on OpenBSD.

**Comment by nmeum** [comment]
I can no longer reproduce the issue on OpenBSD 6.4 with go1.11. The `TestFifoEOF` test passes fine on OpenBSD 6.4. @ianlancetaylor could you confirm that this is the case, close this issue and reenable the test on OpenBSD?

**Comment by ianlancetaylor** [comment]
We still claim to support OpenBSD 6.2 (https://golang.org/wiki/OpenBSD).  Until we require OpenBSD 6.4, it seems to me that we should keep the test disabled.  (I have no opinion at all as to which versions of OpenBSD we should support.)

**Comment by nmeum** [comment]
OpenBSD 6.2 has been EOL for ages. Can this test be re-enabled on OpenBSD now?

**Comment by ianlancetaylor** [comment]
I'm not really sure who our OpenBSD maintainers are.  CC @mdempsky @4a6f656c in case they know.

**Comment by mdempsky** [comment]
OpenBSD upstream only supports the last two major releases, which at the moment is 6.7 and 6.6.

If TestFifoEOF is passing on 6.4 and newer, I think it makes sense to just re-enable it and close this issue.

**Comment by nmeum** [comment]
If we all agree that this is a good idea could someone remove the corresponding lines from `src/os/fifo_test.go`? I would submit such a patch myself but I don't have a google account and can therefore not sign the CLA.
