### ISSUE TITLE
x/build: freebsd-amd64-11_1 sometimes seeing timeouts testing the net package

### ISSUE THREAD

**Issue by mvdan** [golang/go#25887]
Two recent ones:

https://build.golang.org/log/69819f2e31f60a26531cc500a708a9fb8157fdfb
https://storage.googleapis.com/go-build-log/41f6ab0e/freebsd-amd64-11_1_236cf799.log

The fix may be to just bump the timeouts, like we did for a longtest builder in #25886.

Or perhaps the issue is that one of the net tests on `freebsd/amd64` is flaky, sometimes taking really long or hanging. I can't test, as I don't have a freebsd system at hand.

**Comment by bcmills** [comment]
Dup of #25289?

**Comment by bcmills** [comment]
Yep, I think it's a dup. (Please reopen if you disagree.)
