### ISSUE TITLE
net/http: call TCPConn.SetKeepAlive on Transport

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25883]
We enable TCP keep-alives by default for the http Server, but not the HTTP Client.

Seems like we should also enable it by default for the HTTP/1 and HTTP/2 clients.

(or perhaps just HTTP/1, and HTTP/2 can use PING frames with a timeout)

/cc @tombergan

**Comment by jasdel** [comment]
Would enabling TCP keep-alive by default on the HTTP Client be equivalent to using a `http.Transport`'s dialer with [net.Dialer.KeepAlive](https://golang.org/pkg/net/#Dialer.KeepAlive) > 0 behavior of using [SetKeepAlive](https://golang.org/pkg/net/#TCPConn.SetKeepAlive) and [SetKeepAlivePeriod](https://golang.org/pkg/net#TCPConn.SetKeepAlivePeriod) to set the keep-alive? Or would only `SetKeepAlive` be used by the updated HTTP Client's default behavior?

With this default behavior change, would omitting `net.Dialer.KeepAlive` or setting its value to 0, disable TCP keep-alive like the behavior the current `net.Dialer`?

**Comment by bradfitz** [comment]
Nevermind, I actually already did this in 2014 in 49beb23ba73 for #3362
