### ISSUE TITLE
Compile / parse error at `if variable == definedType{} {...}`

### ISSUE THREAD

**Issue by azuenko** [golang/go#25890]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
macOS 10.12.6
`go env` output:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/az/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/az/gopath"
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3f/gwdj7r7x1g509q7d33ly8p0w0000gn/T/go-build071944107=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
https://play.golang.org/p/mGhUQgF1ybF

Compilation error on comparison inside `if` block. 
```
package main

type structT struct{}

func main() {
	s1 := structT{}

	// compiles as expression
	_ = s1 == structT{}

	// does not compile with defined type
	if s1 == structT{} {
	}
	
	// compiles with underlying struct type
	if s1 == struct{}{} {
	}
}
```

### What did you expect to see?
If a boolean expression compiles being assigned to a variable, it should also compile inside `if` block.

### What did you see instead?
```
prog.go:12:21: syntax error: unexpected { at end of statement
prog.go:16:2: syntax error: non-declaration statement outside function body
```

**Comment by mvdan** [comment]
Please see the spec at https://golang.org/ref/spec#Composite_literals:

> A parsing ambiguity arises when a composite literal using the TypeName form of the LiteralType appears as an operand between the keyword and the opening brace of the block of an "if", "for", or "switch" statement, and the composite literal is not enclosed in parentheses, square brackets, or curly braces. In this rare case, the opening brace of the literal is erroneously parsed as the one introducing the block of statements. To resolve the ambiguity, the composite literal must appear within parentheses.
