### ISSUE TITLE
runtime/pprof: TestMapping failures on linux-arm-arm5spacemonkey builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#25891]
The `linux-arm-arm5spacemonkey` was previously broken by a debug/gosym test, but aclements fixed it and now it's failing a little later on the recently introduced `TestMapping` test from runtime/pprof.

Builder log:
https://build.golang.org/log/84f2e315572ca0987ae2da0394bcecdddcf2aaa1

Change that introduced the test:
https://go-review.googlesource.com/c/go/+/118275

cc @hyangah

**Comment by hyangah** [comment]
assumption in the test (there will be only one entry for the main binary) is wrong. 

1: 0x10000/0x162000/0x0 /home/builder/stage0scratch/tmp/go-build662113649/b001/exe/main 50f7cd36fd06f7cd6b5ccb333913714322dba361 [FN]
2: 0x171000/0x182000/0x151000 /home/builder/stage0scratch/tmp/go-build662113649/b001/exe/main 50f7cd36fd06f7cd6b5ccb333913714322dba361 

Fixing the test.
