### ISSUE TITLE
x/crypto/ssh: Support GSSAPI AuthMethod

### ISSUE THREAD

**Issue by quentinmit** [golang/go#25899]
As defined in [RFC 4462](https://www.ietf.org/rfc/rfc4462.txt)

This is commonly used for (MIT/Heimdal/Active Directory) Kerberos authentication, though other GSSAPI mechanisms exist.

There are several different GSSAPI implementations available for Go (e.g. https://gopkg.in/jcmturner/gokrb5.v5, https://github.com/apcera/gssapi). It probably doesn't make sense to bless one of these external packages in x/crypto/ssh, so I would instead suggest that a callback- or interface-based AuthMethod be defined, so the user can plug in the GSSAPI mechanism of their choice.

I think modern SSH servers only support the `gssapi-with-mic` auth method, though some patched SSH servers (Debian for instance) also support the `gssapi-keyex` auth method. The latter auth method is significantly more complicated, so I would suggest starting only with `gssapi-with-mic`.

**Comment by hanwen** [comment]
I don't want to add generic callbacks to the API either.

Is it possible to structure the code such that it effectively becomes a drop-in? Eg. a file that you would add to a local checkout that implements?

Is there a split in the structure that we could apply (eg. putting packetConn into an internal/ package) so you could add a separate gss/ subpackage, without affecting the rest of the SSH code?

**Comment by jorgemarey** [comment]
Hi,

I just saw this issue. We needed to use kerberos ssh authentication from a golang client.

I did this: https://github.com/golang/crypto/compare/master...jorgemarey:f-gssapi-auth (showing changes)

I don't know if it's ok. I could make some changes it you think the code needs it. I tested it with https://github.com/apcera/gssapi (by implementing the interface) and it worked fine.

**Comment by hanwen** [comment]
You can try to run this against an existing GSSAPI server.

The tricky bit is that for it to be promoted into the crypto library, I want to see a test. That means either writing a server side support too (which implies integrating with some existing kerberos package), or testing against an OpenSSH server configured to use Kerberos.

**Comment by yiya1989** [comment]
you can refer to these two:
https://github.com/yiya1989/sshkrb5/blob/main/examples/sshwithkrb5.go
https://github.com/nhywieza/sshgssapi

**Comment by seankhliao** [comment]
I believe this was done in [CL 170919](https://golang.org/cl/170919)
