### ISSUE TITLE
all: port to AIX/ppc64

### ISSUE THREAD

**Issue by trex58** [golang/go#25893]
We have started the port of golang v1.10/v1.11 to AIX / ppc64.
It will be available on AIX 7.2 first, maybe on AIX 7.1 too (probably with recent TLs).
Required hardware is Power8 or 9.
64bit only.

Bootstrap with GCC Go 8.1 has been done.
golang tests failures are now being fixed.

Port of golang.org/x has also being started.
First: sys/unix, It will work for both GCC Go and golang on AIX.

We plan to finalize the port in August/September. Available first as RPMs on BullFreeware.

**Comment by morya** [comment]
Wonderful! Will you guys consider AIX 6.1 ?

**Comment by trex58** [comment]
> Wonderful! Will you guys consider AIX 6.1 ?

No. Sorry. AIX 6.1 does not provide all the features required by Go (either GCC Go or golang).

**Comment by bcmills** [comment]
What should we say about the AIX port in the Go 1.12 release notes?
(CC @andybons)

**Comment by bcmills** [comment]
That's probably more information than we need for the release notes proper: most of the detail can probably go on an accompanying wiki page (e.g., https://golang.org/wiki/AIX). The release note itself should mostly just make people aware that it's an option.

For some idea of scale, see https://golang.org/doc/go1.11#ports and https://golang.org/doc/go1.8#ports.

**Comment by laboger** [comment]
Why are you listing crypto/aes as an unsupported feature? I think it should
work just like it does for linux/ppc64, it just doesn't have an optimized
asm implementation.

**Comment by Helflym** [comment]
Hi, 

I would said something like that: 
"Go is now available on AIX 7.2 on POWER8 architecture (aix/ppc64). External linking, cgo, pprof and race detector aren't yet supported. "

I don't know if you wish to be more precise about buildmode but we can add that only `-buildemode=exe` is available.

It can also be said that `golang.org/x/sys/unix` now supports aix/ppc64 on both gc and gccgo. 

I think this should be enough. Maybe, I'll add a word about gdb (even if there is an issue about that ?) but it should be available before the true release anyway. 

About the Wiki page, that's a good idea ! But does it need to be ready before 1.12 first beta ? Or can I made it after ?

**Comment by theonewolf** [comment]
@trex58 do we have documented anywhere the limitations preventing getting this off the ground for AIX 6.X?

**Comment by pinacoelho** [comment]
> > Wonderful! Will you guys consider AIX 6.1 ?
> 
> No. Sorry. AIX 6.1 does not provide all the features required by Go (either GCC Go or golang).

Hi, What's missing in 6.1 ?

**Comment by trex58** [comment]
@theonewolf  @pinacoelho  We have to build the complete list of requirements golang has on the AIX operating system.
On AIX 7.2, we see that golang works better (no more test failures) on: 7200-02-02-1810 compared to: 7200-00-02-1614 . See: https://build.golang.org/# ("aix" is on the right) for 7200-02-02-1810 .
Please remember that golang on AIX requires Power8 or 9. Do you have AIX 6.1 on P8 or P9 CECs? We have to check if the last AIX 6.1 TL provides what we need or not, probably no.
We could port golang on AIX 7.1, at least 3 months from now. However, we need to know which TLs do provide golang requirements, and there are other priorities.
What do you plan to do with Go on AIX? Why AIX 6.1?

**Comment by theonewolf** [comment]
@trex58 I am trying to produce a binary for some old servers that can not be upgraded to AIX 7.X, they are stuck on 6.X.

**Comment by pinacoelho** [comment]
1. The AES assembly code does require POWER8 or above, however there is also a pure golang implementation of those functions.
2. AIX 7.1 introduced the openat family of functions.  I'm still trying to figure out if golang needs them or just provides an interface to them.  (In the later case, their absence isn't critical - in any case, I'm trying to figure out if it's possible to reimplement them in golang)
3. There's still a **lot** of AIX 6.1 LPARs lying around (namely, the VIOS V2), and a lot of them are excluded from immediate upgrade considerations (for whatever factors).  Being able to build golang programs to run on all AIX LPARs (AIX 6.1, 7.1, 7.2 and VIOS V2, V3) would be a great step into bringing them into a DevOps world.

I'm currently in a dead-end situation: AIX 6.1 & 7.1 on POWER5+POWER6, I'm trying to bootstrap gcc/gccgo from the GCC V6, and "it ain't easy" isn't even in the picture yet.
Removing the POWER8&AIX 7.2 requirement would allow me to run the toolset on AIX7.1/POWER6 to build golang into a AIX6.1/POWER5.

Alternate option: build a cross-chain gccgo on linux/x86_64 to aix6.1/ppc64 (power5) to produce an initial golang for aix6.1/power5, but it's looking like a double effort for a half return.

**Comment by trex58** [comment]
AFAIK, porting golang on AIX 6.1 seems impossible, due to the lack of some DWARF features even in last TLs.
About AIX 7.1, our focus now is AIX 7.2 only (and there are still plenty things to do!).

**Comment by owlmind** [comment]
I understand it won't work on power7? What is the reason it's power8 or higher only?

**Comment by trex58** [comment]
@owlmind 
We are using a work done by IBM Linux/Power team which started to port golang on Linux/Power for Power8 or higher only: the assembler part, which is common for AIX and Linux/Power. Porting golang on AIX is a very very complex task and we still are improving the quality and we are working hard so that golang 1.12 will be officially available on AIX, including cgo & golang.org/x (March). And we develop on AIX 7.2 on Power8 only today for reducing the complexity. Maybe we'll port golang on AIX 7.1 ; not sure. Maybe that the Power8 requirements can be relaxed ; not sure ; however for now, we haven't yet looked at this. Maybe that P8 assembler code is used only for encryption (which is for now only available for LE platform, thus not for AIX) ; so maybe that being compatible with P7 is not very complex ; however, we may look at these possibilities later, in April probably, when golang works perfectly on AIX 7.2 & P8/9. That depends also on how many AIX users want golang on older environments. Probably that customers wanting to use Go are focused on new applications and are using recent environments (AIX 7.2 & P8/9), which means that porting golang on AIX 7.1 and older HW will not be useful for many AIX users though it will take a lot of work.
Why would you like to have golang on Power7?
Do you want to use existing applications written in Go or do you want to write new applications on AIX due to the qualities of the Go language?
Do you plan to use cgo? (Go -> C or C -> Go ?)

**Comment by owlmind** [comment]
@trex58 We have a lot of power7 systems and most likely will have to use them for at least 2-3 years. And end of life for AIX 7.1 is 30 April 2022.
We want to use existing applications, particularly filebeat in this case. I was really surprised to see app supported for 7.2 and not for 7.1. Have never seen that before, software on aix usually have pretty good backward compatibility.

**Comment by awilfox** [comment]
https://github.com/golang/go/issues/19074 details the (imo, extremely flimsy) reason that golang does not support POWER7 or lower.  There's been some community movement on getting a patchset to support down to POWER5, but it hasn't fully materialised yet.  Letting people know just how many of us have non-P8 hardware and want to run Go will help.

**Comment by zuraff** [comment]
My use-case is to run certain existing utilities written in Go on our customers' environments, which are AIX 7.1 and AIX 7.2. These utilities depend on existing C libraries, so lack of cgo is a blocker.

**Comment by Helflym** [comment]
@zuraff cgo is now available on master or in RPMs delivered by either us http://www.bullfreeware.com/affichage.php?id=4967 or by IBM on AIXToolBox. 
However, it's only available on AIX 7.2, as @trex58 said, 7.1 is not our priority for the moment.

**Comment by orz--** [comment]
My customers use POWER8, POWER7 for production's environments.
But many cases use POWER7, POWER6 for testing environments.

**Comment by awilfox** [comment]
I think at this point the only way to get support for stable, older POWER ISAs is GCC Go.  The Golang people are not receptive to us, the users of pre-P8 hardware, at all.

**Comment by trex58** [comment]
I have warned the guys who take decisions about the many people asking for golang on older Power machines with AIX 7.2.

Raw porting on Power7 (and lower maybe) with AIX 7.2 does not seem so complicated. But officially managing older Power versions may be a burden since it requires at first a lot of complementary tasks and it generates then more build/test/maintenance work. It has a cost.

Porting golang on AIX 7.1 seems much more difficult. No plan.

Moreover, now there are also work to be done on GCC Go for GCC v9 (v1.10 to v1.12 : lot of changes) and on golang.org/x (in order to make all golang packages aware of AIX).

The priority for now seems to finalize GCC Go v9 and a complete golang on AIX 7.2 / Power8.
Moreover some very rare issues have to be studied. A quick study of performance must be done too, in order to find the top bottle-necks vs Linux/Power.

Looks like there is an interesting discussion at: https://github.com/golang/go/issues/19074 . I need to read it completely.

**Comment by ALTree** [comment]
@trex58 aix/ppc64 support was merged a while ago; is there anything else that needs to be done here? Or can this issue be closed?

**Comment by trex58** [comment]
> @trex58 aix/ppc64 support was merged a while ago; is there anything else that needs to be done here? Or can this issue be closed?

Yes, it can be closed. It's OK for AIX 7.2 and Power >= 8. About AIX 7.1, we'll see if someone requires it for an important project.

**Comment by ALTree** [comment]
Nice, thank you. Closing.
