### ISSUE TITLE
x/vgo: "file not found" when fetching a repo without README, .gitignore, .gitattributes, or go.mod

### ISSUE THREAD

**Issue by Gobd** [golang/go#25895]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What did you do?
vgo build with a dependency that has none of the files listed [here](https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/modfetch/gitrepo/fetch.go#L340) and you get a "file not found" error. This error should be more descriptive or this requirement to have one of these files should be removed

**Comment by bcmills** [comment]
Could you give a more complete example? What `vgo` command did you run, and what was the complete (less-than-useful) output?

(CC @kardianos, who has been working on improving error reporting.)

**Comment by Gobd** [comment]
```
vgo get project
vgo get project: file not found
vgo: import "project" [/Users/user/code/src/project]: no Go source files
```

This is when you `vgo get` a project that only has *.go files, nothing else. There are clearly go source files, and I can `go get` the project just fine, also works with dep. The user has no indication that the fix to this problem is to add a file from the link the original issue.

**Comment by bcmills** [comment]
Thanks for the clarification. Since users can't add a file to a repo they don't own in general, we should probably fall back to a slower path, rather than failing with instructions that the user may not be able to follow.

**Comment by rsc** [comment]
That code is gone.
