### ISSUE TITLE
ERROR: -bash: vgo: command not found after having run go get -u golang.org/x/vgo

### ISSUE THREAD

**Issue by harvey93** [golang/go#25905]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.2 darwin/amd64

### Does this issue reproduce with the latest release?
Ran go get -u golang.org/x/vgo so should be the latest version

### What operating system and processor architecture are you using (`go env`)?
Running on OSX

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/harvey/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/harvey/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sc/90rl4f21239f0q36vqhc_b040000gp/T/go-build155696743=/tmp/go-build -gno-record-gcc-switches -fno-common"
### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

$ go get -u golang.org/x/vgo
$ cd $HOME
$ mkdir hello
$ cd hello
$ curl -sS https://swtch.com/hello.go >hello.go
$ echo >go.mod
$ vgo build

### What did you expect to see?

vgo: resolving import "rsc.io/quote"
vgo: finding rsc.io/quote (latest)
vgo: adding rsc.io/quote v1.5.2
vgo: finding rsc.io/quote v1.5.2
vgo: finding rsc.io/sampler v1.3.0
vgo: finding golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
vgo: downloading rsc.io/quote v1.5.2
vgo: downloading rsc.io/sampler v1.3.0
vgo: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c

### What did you see instead?
-bash: vgo: command not found

vgo command is not recognized at all, however the files seem to have been downloaded. When I look for the vgo folder in my $GOPATH it shows up

$ ls /Users/harvey/go/src/golang.org/x
tools	vgo

**Comment by mvdan** [comment]
Did you add $GOPATG/bin to your $PATH? Does $GOPATH/bin/vgo exist?

**Comment by harvey93** [comment]
I believe so.

This is in my bash_profile:

export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin

vgo seems to be in the $GOPATH/bin folder

$ ls $GOPATH/bin
godoc	vgo

**Comment by mvdan** [comment]
Have you tried running the binary directly? If it works, then this looks like an issue with your shell setup.

**Comment by harvey93** [comment]
In $GOPATH/bin 
if I run vgo -h I still get -bash: vgo: command not found

however if I run ./vgo -h 

I get this: 

Go is a tool for managing Go source code.

This is vgo, an experimental go command with support for package versioning.
Even though you are invoking it as vgo, most of the messages printed will
still say "go", not "vgo". Sorry.

It looks like the binary runs. Although when I run ./vgo version

The result is 

"cannot determine module root; please create a go.mod file there"

Im not really sure what would be the issue in the shell setup. The only thing go related are the 2 lines adding GOPATH to my PATH

**Comment by mvdan** [comment]
The issue with `vgo version` you saw is #25903.

Since the binary runs, this is an issue with your $PATH setup. If you're having issues with that, you can ask for help via https://golang.org/wiki/Questions. The issue tracker is only used to report bugs and propose changes at the moment.
