### ISSUE TITLE
x/crypto/acme/autocert: NewListener does not acquire new certificates

### ISSUE THREAD

**Issue by FlorianUekermann** [golang/go#25901]
Using `log.Fatal(http.Serve(autocert.NewListener("example.com"), handler))` as described by the documentation does not allow the server to acquire new certificates anymore, since Let's Encrypt disabled tls-sni-* validation.

This limitation should either be documented or the function removed. Could the listener be changed to listen to both http and https at the same time, so it can fulfill the role of autocert.Manager.HttpHandler as well?

Related: #21890

**Comment by x1ddos** [comment]
Re: fulfill the role of autocert.Manager.HttpHandler. There's a while discussion about this in the related issue you referenced.

Note that tls-alpn is coming, at which point http won't be required anymore, again. See https://github.com/golang/go/issues/25013 for me details.

**Comment by FlorianUekermann** [comment]
That sounds like a good plan. I don't understand the details well enough to have an opinion here.

However, until this works in practice, there needs to be at least a note in the documentation, because right now it simply doesn't work as advertised.

This stuff is too complex to hope that users just know what they have to do from the logged warnings.
