### ISSUE TITLE
cmd/compile: display the source code for inlined functions in ssa.html

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#25904]
[CL 119035](https://go-review.googlesource.com/c/go/+/119035) added displaying the source code of target function as the first column in ssa.html table. 

It would be great to handle inlined function correctly too, e.g. display their sources as well.

**Comment by ysmolsky** [comment]
`ssa.html` should contain declarations of all inlined functions in the sources column. 
When `GOSSAFUNC=f` for the following program
```golang
package main

import "encoding/binary"

var x uint16
var b [2]byte

func f() {
	x = g(x)
	binary.BigEndian.PutUint16(b[:], x)
}

func g(i uint16) uint16 {
	return i + 1
}
```
it should include sources for both `g()` and `binary.BigEndian.PutUint16()` functions.

**Comment by ysmolsky** [comment]
@randall77 @dr2chase  @josharian 

Does the screenshot below look right? 
Can you spot any problems with following representation of sources for inlined functions?

![screen shot 2018-07-25 at 19 56 42](https://user-images.githubusercontent.com/140245/43215774-c3eaec7c-9045-11e8-9055-92fb5fc4347c.png)

_Any feedback_ is very welcome!

**Comment by josharian** [comment]
On my phone, but my initial response is “Hooray! This is going to be super helpful!”

It might be nice to toposort, that is, put the main function at the top and inlined functions below (and functions inlined by the inlined functions below that, etc.).

**Comment by dr2chase** [comment]
This is quite nice.  Thank you for working on this.

**Comment by ysmolsky** [comment]
Fixed the order of functions in sources column per Josh request + cosmetics:

![screen shot 2018-07-28 at 10 46 14](https://user-images.githubusercontent.com/140245/43354357-896a4420-9253-11e8-8d72-ea5662cd1763.png)
