### ISSUE TITLE
cmd/link: Darwin build fails with "unknown load command" [1.9 backport]

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25915]
@mistydemeo requested issue #25908 to be considered for backport to the next 1.9 minor release.

> @gopherbot please consider this for backport to 1.9, it's a regression

**Comment by mistydemeo** [comment]
Ping - any chance this could get merged, please?

**Comment by ianlancetaylor** [comment]
@andybons Is there going to be another 1.9 release?

**Comment by andybons** [comment]
Likely not given how close we are to 1.11 final. Is there a particular reason you're running 1.9? That will help us with a decision.

**Comment by andybons** [comment]
@mistydemeo got it :)

We’ll be doing a 1.10.4 release for sure which should have this fix included. That should be soon.

**Comment by ALTree** [comment]
The 1.9.8 milestone is closed and we only backport two releases back (1.10 and 1.11 at the moment), so I'm closing this issue.
