### ISSUE TITLE
Outdated lib/time/zoneinfo.zip

### ISSUE THREAD

**Issue by zugl** [golang/go#25914]
### What version of Go are you using (`go version`)?

go version go1.10.3 windows/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

windows_amd64

### What did you do?

Got this randomly on automated tests.

The zone "Antarctica/Casey" is configured with utc offset `+1100` when it should be `+0800`.

https://play.golang.org/p/a-EDljzwckd

### What did you expect to see?

Zoneinfo for "Antarctica/Casey" with utc offset `+0800`.

### What did you see instead?

Zoneinfo for "Antarctica/Casey" with utc offset `+1100`.

### Fix

Running `lib/time/update.bash` with CODE and DATA set to `2018e` fixed the issue, but I'm unsure if a PR with this would be accepted. If there is no problem I'd be glad to submit it.

**Comment by ianlancetaylor** [comment]
Closing in favor of #22487.  Please comment if you think that is wrong.
