### ISSUE TITLE
x/scratch: make repo go-gettable

### ISSUE THREAD

**Issue by mvdan** [golang/go#25921]
I'm running a few Go contributor workshops, and the first goal is to have attendees submit a Scratch CL. The instructions currently start with:

```
cd $(go env GOPATH)/src/golang.org/x
git clone https://go.googlesource.com/scratch
cd scratch
```

It would be much better if they could just be:

```
go get -d golang.org/x/scratch
cd $(go list -e -f {{.Dir}} golang.org/x/scratch)
```

But that fails:

```
$ go get -d golang.org/x/scratch
package golang.org/x/scratch: unrecognized import path "golang.org/x/scratch" (parse https://golang.org/x/scratch?go-get=1: no go-import meta tags ())
```

This is also confusing because one can currently do it via `go get -d` for all of the X repos, but Scratch seems to be special. This, in my experience, can confuse new contributors.

Another advantage is that the existing method doesn't work well with multiple `GOPATH` directories.

The only reason I can imagine why this is disabled is that we don't want scratch packages to be importable or used in real code. Although I don't think that would ever be a problem in reality, as the repository only contains main packages anyway.

/cc @spf13 @rsc @rasky @myitcv

**Comment by mvdan** [comment]
Alternatively, if `golang.org/x/...` is reserved for real published packages, we could maybe use a different import path like `scratch.golang.org/...` or `golang.org/scratch/...`.

**Comment by bradfitz** [comment]
I don't think we want to bless the "golang.org" name anywhere in the import path for such a repo.

If anything, you can run a domain like "go-workshop.net" with the meta tags to make it go-gettable without golang.org in the name.

But really, I hope nobody ever depends on code in scratch for more than the duration of one workshop.

Maybe we should auto-nuke it ever 24 hours.

**Comment by mvdan** [comment]
All of those suggestions seem reasonable :) However, I'd not rewrite the history when nuking, as that can confuse new contributors if they're in the middle of a change.

**Comment by kevinburke** [comment]
Just ran into this. Dang

**Comment by kevinburke** [comment]
i have purchased goscratch.club for $1.17 and am configuring it now

**Comment by kevinburke** [comment]
```$ go get goscratch.club/...```
