### ISSUE TITLE
cmd/go: doc: no official explanation about GOCACHE=off ?

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#25928]
As far as I can see, I could not find the documentation about that.

**Comment by agnivade** [comment]
@ianlancetaylor - How about adding something like this

`You can set the variable to "off" if you want to bypass the cache`

at the end of https://github.com/golang/go/blob/master/src/cmd/go/internal/help/helpdoc.go#L659, which is the output of `go help cache`.
