### ISSUE TITLE
runtime: TestFreeBSDNumCPU fails

### ISSUE THREAD

**Issue by devnexen** [golang/go#25924]
### What version of Go are you using (`go version`)?

go devel

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

FreeBSD 11

### What did you do?

unit tests

### What did you expect to see?

num cpu test fails due to causer output

**Comment by martisch** [comment]
Please provide more information:
- what is the error reported and which command was run that lead to the error
- what is the output of "go env"

**Comment by devnexen** [comment]
an error output as
`FAIL: TestFreeBSDNumCPU (0.02s)
    numcpu_freebsd_test.go:13: expected "OK\n", but got:
        fail to launch child 'cpuset -l 0,1
        pid 77295 domain policy: first-touch mask: 0 /tmp/go-build095241536/testprog.exe FreeBSDNumCPUHelper', error: exit status 1, output: cpuset: Malformed list 0,1
        pid 77295 domain policy: first-touch mask: 0`

**Comment by devnexen** [comment]
proposed PR https://github.com/golang/go/pull/25920

**Comment by martisch** [comment]
Thanks. Changed the title as that test does not seem to be using or is part of internal/cpu but is in the runtime package.

**Comment by devnexen** [comment]
I run snapshot, witness, develop symbols and everything maybe that s why.

**Comment by ianlancetaylor** [comment]
@uvelichitel This issue is closed and we think it's been fixed.  Please open a new issue with the problem that you are seeing.  Thanks.
