### ISSUE TITLE
cmd/link: test failure in TestLldbPython from commit  594eae5 onward

### ISSUE THREAD

**Issue by siebenmann** [golang/go#25925]
### What version of Go are you using (`go version`)?

go version devel +b459e00454 Sat Jun 16 13:35:45 2018 +0000 linux/amd64

This is the current tip as I file this bug report, but this issue happens from 594eae5 onward; that commit is for issue #11799.

### What operating system and processor architecture are you using (`go env`)?

````
GOARCH="amd64"
GOOS="linux"
````

Specifically I'm using Fedora 27, which may matter for this particular failure.

### What did you do?

During an `all.bash` build, I get a test failure reporting unexpected lldb output.

````
ok      regexp/syntax   0.260s
--- FAIL: TestLldbPython (4.51s)
    runtime-lldb_test.go:178: Unexpected lldb output:
        Created target
        Created breakpoint
        Process launched
        Process state 10
FAIL
FAIL    runtime 23.172s
````

The Fedora 27 version of lldb appears to be 5.0.2. Based on poking around the Python lldb module, process state 10 appears to be `eStateExited` on my machine.

I'd be happy to add additional debugging information to the Python that runtime-lldb_test.go uses, or generally test changes.

**Comment by odeke-em** [comment]
Thank you @siebenmann for the report and for testing out the latest!

/cc @heschik @ianlancetaylor @aclements

**Comment by aarzilli** [comment]
LLDB only added support for zdebug sections last month: https://reviews.llvm.org/rL332162

**Comment by heschik** [comment]
We basically have three options: roll back compression, tell everyone to update lldb, or skip the test. I don't want to roll back compression. Updating lldb is going to be a hassle -- I'm not even sure if that change has hit a release yet. So I'm inclined to skip the test and we can re-enable it once lldb has released the change @aarzilli linked to.

**Comment by aclements** [comment]
I agree. Can we detect when we should skip the test so it's not just permanently skipped?

**Comment by heschik** [comment]
Okay, I skipped the test if the breakpoint doesn't match any locations. Not perfect but the best I could come up with.

@siebenmann, please try the above CL? I think it'll fix it but the test times out on my machine.

**Comment by siebenmann** [comment]
@heschik, your CL fixes the issue on my Fedora machine; all tests now pass and Go tip (+ the change) builds without problems.
