### ISSUE TITLE
cmd/link: GNU objdump for ppc64le binary errors: unable to get decompressed section .zdebug_abbrev

### ISSUE THREAD

**Issue by laboger** [golang/go#25948]
### What version of Go are you using (`go version`)?
tip

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le

### What did you do?
Used the GNU objdump on golang built binaries.

### What did you expect to see?
The objdump output with no errors/warnings. I've used this for a long time without seeing these messages.

### What did you see instead?
objdump: hello: unable to get decompressed section .zdebug_abbrev
objdump: hello: unable to get decompressed section .zdebug_line
objdump: hello: unable to get decompressed section .zdebug_frame
objdump: hello: unable to get decompressed section .zdebug_pubnames
objdump: hello: unable to get decompressed section .zdebug_pubtypes
objdump: hello: unable to get decompressed section .zdebug_info
objdump: hello: unable to get decompressed section .zdebug_loc
objdump: hello: unable to get decompressed section .zdebug_ranges

This happens on a simple hello program.
Seems to still generate the objdump OK.

**Comment by heschik** [comment]
What version of objdump? 2.30 is perfectly content on my workstation when I do objdump --dwarf.

**Comment by laboger** [comment]
This happens on an Ubuntu 16.04 with 2.26.1.
I can try some newer distros to see what happens.

**Comment by laboger** [comment]
I see this on the 16.04 Ubuntu with 2.26.1

objdump -D hello > /dev/null
objdump: hello: unable to get decompressed section .zdebug_abbrev
objdump: hello: unable to get decompressed section .zdebug_line
objdump: hello: unable to get decompressed section .zdebug_frame
objdump: hello: unable to get decompressed section .zdebug_pubnames
objdump: hello: unable to get decompressed section .zdebug_pubtypes
objdump: hello: unable to get decompressed section .zdebug_info
objdump: hello: unable to get decompressed section .zdebug_loc
objdump: hello: unable to get decompressed section .zdebug_ranges

No messages with objdump --dwarf hello on that system.
I don't see any messages with objdump with either option on Ubuntu 18.04 with binutils 2.30.

**Comment by heschik** [comment]
I doubt there's anything I can do, then. I could go find what changed, but odds are it was a bug in objdump and it's fixed, not anything we can work around short of rolling back DWARF compression.

**Comment by laboger** [comment]
I mainly opened this for your awareness, and suppose it's OK that it works in a later objdump, which I didn't think to check.

**Comment by heschik** [comment]
Cool. Thanks for the heads up.
