### ISSUE TITLE
fmt %% not working

### ISSUE THREAD

**Issue by pjebs** [golang/go#25954]
This works on Go playground.

I have version: go version go1.10.1 darwin/amd64

```
box1 := "StandardHrs"
box2 := "0000-2400"
box3 := "100"

fmt.Println(fmt.Sprintf("[%s][%s][%s%%]", box1, box2, box3))
```
It should output:
```
[StandardHrs][0000-2400][100%]
```

It actually outputs:
```
[StandardHrs][0000-2400][100%!](MISSING)
```

**Comment by meirf** [comment]
Works for me on go1.10.3 darwin/amd64. Upgrade to latest?

**Comment by pjebs** [comment]
I'm using `mac 10.3.4`

**Comment by davecheney** [comment]
@pjebs can you please provide a runnable code sample, play.golang.org is the best, that shows the complete program. It doesn't have to fail in the playground, but it must be the same program that does fail on your laptop.

**Comment by meirf** [comment]
(I get the correct output both in 1.10.1 and 1.10.3, but on mac 10.13.3, which is different than the OP's. So maybe the difference is due to different OS version or we are not running the same code.)

**Comment by pjebs** [comment]
When I make a standalone program that is simply:

```
package main

import (
	"fmt"
)

func main() {

	box1 := "StandardHrs"
	box2 := "0000-2400"
	box3 := "100"

	fmt.Println(fmt.Sprintf("[%s][%s][%s%%]", box1, box2, box3))
}

```

It works perfectly.

But in my code it doesn't.
In fact even:

```
	a := "[StandardHrs][0000-2400][100%]"
	fmt.Println(len(a))
	fmt.Print(a)
```
outputs:
```
30
[StandardHrs][0000-2400][100%!](MISSING)
```

**Comment by pjebs** [comment]
I'll close it because I agree it's hard for you to help. But my code is not doing anything else. It's very simple.

**Comment by pjebs** [comment]
I can confirm the bug is related to using fresh:
https://github.com/pilu/fresh
