### ISSUE TITLE
Says the GOPATH is not set, but it is.

### ISSUE THREAD

**Issue by SimsonExample** [golang/go#25952]
**Go Version : 1.6.2**

**OS: Ubuntu 16.04.1 LTS**

**go env:**
GOARCH="amd64"
GOBIN="/home/ubuntu/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

(Which also shows the GOPATH which I have set to $HOME/go)

### What did you do?
My go project imports _"import {..., _ github.com/jbarham/gopgsqldriver}"_
When I want to start my Project with "go run main.go" the console says: 

_app/model/general.go:8:2: cannot find package "github.com/jbarham/gopgsqldriver" in any of:
	/usr/lib/go-1.6/src/github.com/jbarham/gopgsqldriver (from $GOROOT)
	/home/ubuntu/go/src/github.com/jbarham/gopgsqldriver (from $GOPATH)_

Okay so I decided to do this: _"sudo go get github.com/jbarham/gopgsqldriver"_
Which on the other hand showed this error message:
_"package github.com/jbarham/gopgsqldriver: cannot download, $GOPATH not set. For more details see: go help gopath"_

Which says GOPATH is not set 
but "go env" also says that GOPATH=/home/ubuntu/go is set.

Does anyone know what to do here? I also tried to set the GOPATH to another dir but nothing changed.

Greetings

**Comment by ysmolsky** [comment]
There is not need to run `go get` under the `sudo`, just "go get ..."

**Comment by ysmolsky** [comment]
Irrelevant to your problem, but rather just a hint go 1.6 is old, try the newer version.

**Comment by ysmolsky** [comment]
https://golang.org/doc/devel/release.html#policy

Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

**Comment by bradfitz** [comment]
`sudo` is probably dropping that environment variable. But like @ysmolsky says, you shouldn't be using `sudo`.

For questions about Go, see https://golang.org/wiki/Questions.
