### ISSUE TITLE
wasm-wip  too many arguments in call to js.NewEventCallback when compiling against recent golangweekly lazyblogger wasmgo example

### ISSUE THREAD

**Issue by omac777** [golang/go#25960]
https://blog.lazyhacker.com/2018/06/go-with-webassembly-early-examples.html
https://github.com/lazyhacker/wasmgo
Sorry I meant lazyhacker.
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
 $ set|grep GO
GOPATH=/home/dma2/Code/go
GOROOT=/home/dma2/mywasmtest/go
 $ /home/dma2/mywasmtest/go/bin/go version
go version devel +1caa06299c Tue Jun 19 16:39:52 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?
no just the tip which is the only one with neelance's wasm-wip merges.

### What operating system and processor architecture are you using (`go env`)?
 $ /home/dma2/mywasmtest/go/bin/go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dma2/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dma2/Code/go"
GOPROXY=""
GORACE=""
GOROOT="/home/dma2/mywasmtest/go"
GOTMPDIR=""
GOTOOLDIR="/home/dma2/mywasmtest/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build962305173=/tmp/go-build -gno-record-gcc-switches"
VGOMODROOT=""

### What did you do?
export GOPATH=/home/dma2/Code/go
rm -rf go
git clone https://go.googlesource.com/go
cd go
cd src
GOROOT_BOOTSTRAP=/home/dma2/go1.10.3 ./make.bash
export GOROOT=/home/dma2/mywasmtest/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
cd $GOPATH/src/
rm -rf lazyhackergo.com/
go get lazyhackergo.com/wasmgo

cd $GOPATH/src/lazyhackergo.com/wasmgo
GOARCH=wasm GOOS=js go build -o test.wasm test.go

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
compile successfully.

### What did you see instead?
GO GET OUTPUT: lazyhackergo.com/browser/browser.go:7:2: build constraints exclude all Go files in /home/dma2/mywasmtest/go/src/syscall/js

GO BUILD OUTPUT:
# command-line-arguments
./test.go:51:26: too many arguments in call to js.NewEventCallback
	have (bool, bool, bool, func(js.Value))
	want (js.EventCallbackFlag, func(js.Value))

**Comment by agnivade** [comment]
Your code is incorrect.

Refer to the documentation here - https://tip.golang.org/pkg/syscall/js/?GOOS=js&GOARCH=wasm#NewEventCallback.

**Comment by omac777** [comment]
You are misunderstanding the situation.  I submitted a bug about this with neelance and he told me to submit it to golang/go.  Here I am.  Also, the error in question was not code that I wrote.  It is sample code I am familiarizing myself with in order to start using go js/wasm compiler for which I have no sample code for.  This sample will be one of first I have tried with the golang/go merged js/wasm compiler.  I thought it would be polite to alert you that code was was compiling with neelance wasm-wip as experienced by lazyhacker and blogged last week no longer compiles here.
I am not a js expert nor am I a WASM expert which is why I turned to golang/go compiler team about this.  Where are the golang/go wasm examples that work with this golang/go merged js/wasm compiler if this example does not work?

**Comment by AlexRouSg** [comment]
@omac777 I found your bug report https://github.com/neelance/go/issues/29
It wasn't `neelance` that told you to make a report here, it was `johanbrandhorst` and he was giving you a blanket statement without paying too much attention to your report.

The function has since been changed, you can see the process here https://go-review.googlesource.com/c/go/+/114197/1
WASM support has not been released so anything and everything can and will be subject to change until the release. 

> Where are the golang/go wasm examples that work with this golang/go merged js/wasm compiler if this example does not work?

You'll have to wait for the release if you want proper examples. Any examples written before the release will have a chance of breaking.

**Comment by agnivade** [comment]
> Also, the error in question was not code that I wrote.

I get that. I meant the code that you have posted as part of the issue.

> I thought it would be polite to alert you that code was was compiling with neelance wasm-wip as experienced by lazyhacker and blogged last week no longer compiles here. I am not a js expert nor am I a WASM expert which is why I turned to golang/go compiler team about this. 

Sure, but there is no issue here. lazyhacker's code was using neelance's branch. That code has changed during review. There is no guarantee at all that it will compile.

This is all the official documentation we have - https://tip.golang.org/pkg/syscall/js/?GOOS=js&GOARCH=wasm. Keep in mind, this is all in master, so things are expected to change and break. If you work with tip, it is assumed that you will have a rough experience.

I would request you to wait until Go 1.11 release to get 
> easy to build(with latest version) examples demonstrating the core web_to_go and go_to_web concepts
