### ISSUE TITLE
gofmt forgets to properly indent raw func values

### ISSUE THREAD

**Issue by purpleidea** [golang/go#25964]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Latest used in playground or 1.9+

### Does this issue reproduce with the latest release?

Yes, I think so.

### What operating system and processor architecture are you using (`go env`)?

GNU/Linux

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/93bYM6KZ3VF

As you can see, the `func` doesn't align itself correctly with the other fields. It does in the struct definition though!

### What did you expect to see?

Proper alignment with the other fields.

### What did you see instead?

Improper alignment.

Thanks!

**Comment by bontibon** [comment]
cc @griesemer

**Comment by griesemer** [comment]
This is working as intended: If the func would fit on a single line, it would be aligned (see https://play.golang.org/p/vyA0lpvt6n3 ). The same is true for any element that doesn't fit on a single line; see e.g. https://play.golang.org/p/8ECQMbrfex6 , where the slice is not aligned.

**Comment by purpleidea** [comment]
¯\_(ツ)_/¯

Well that was unexpected! I suppose it's not a bug then, but these "line length" rules, are not intuitive IMO. Here's a nice article about why it's not always a good idea to do this: http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/
I thought golang wouldn't start this game because it doesn't have an explicit requirement for 80 chars, etc...
