### ISSUE TITLE
x/tools/cmd/tip: migrate beta.golang.org to tip GKE service

### ISSUE THREAD

**Issue by bradfitz** [golang/go#25978]
beta.golang.org runs on a GCE VM in a somewhat ad-hoc config.

Now that tip.golang.org on GKE is stable (I think?), let's nuke the weird VM and just make tip.golang.org and beta.golang.org have the same IP and be served by the same place.

The difference between betas and tip is always tiny anyway, and there's basically never a case where we want beta.golang.org to serve something older than tip. If anything, it's been tedious logging into beta.golang.org regularly during the beta/rc cycle and running "git pull" and restarting systemd services when needed.

/cc @FiloSottile @bcmills

**Comment by shurcooL** [comment]
I have some comments/questions to understand this better. I'm not against this, you're in a better position to know if the work maintaining beta isn't justified.

If I understand this issue, once resolved, tip and beta will both always serve the exact same Go version, is that right?

> there's basically never a case where we want beta.golang.org to serve something older than tip

My understanding of beta was that it's supposed to be the latest beta or RC release, whereas tip is latest `master` branch commit. Sometimes it's helpful to be able to compare the two (and link to them).

FWIW, there were a few times in the last few years when tip was broken (for a few hours) but I could fall back to beta in the meantime. It's certainly rare though.

If my understanding is right and the plan is to have tip and beta always serve the exact same version, why not just drop beta completely and leave only tip?

**Comment by bradfitz** [comment]
This is done.
