### ISSUE TITLE
access: Gerrit Approver Access ("approvers")

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#25974]
See https://golang.org/wiki/GerritAccess

Request for +2 powers: https://go-review.googlesource.com/#/admin/groups/1005,members

gerrit name: Iskander Sharipov
gerrit email: iskander.sharipov@intel.com

CLs: https://go-review.googlesource.com/q/owner:iskander.sharipov%2540intel.com

Worked closely with:
`cmd/internal/obj`
`cmd/internal/obj/x86`
`cmd/asm/internal/...`
Touched several times:
`cmd/compile/internal/gc`
`cmd/compile/internal/ssa`
`cmd/lint/internal/ld`

**Raionale**: mostly for convenience on contributors workshops.
Organized myself: https://github.com/Quasilyte/kfu-go-2018
Planning to be available online for https://www.meetup.com/Go-London-User-Group/events/251046966/?_cookie-check=3YXhrv45XhjlkFMI
Hopefully, I'll be participating in other upcoming Go contributors workshop in https://www.gophercon.co.uk/ as a mentor ("live" this time).
There are also plans for other contributors workshop in Russia I'm going to organize this autumn.

Thank you.

CC @bradfitz @mvdan

**Comment by bradfitz** [comment]
Done. Use your newfound powers responsibly and feel free to ask golang-dev if you have any questions about policy/etc. Enjoy, and thanks!
