### ISSUE TITLE
doc: update gopherbot wiki to account for backporting command

### ISSUE THREAD

**Issue by andybons** [golang/go#25987]
In https://github.com/golang/go/wiki/gopherbot the section for backporting is currently empty. We should fill it out :)

/cc @filippo

@gopherbot needsfix

**Comment by FiloSottile** [comment]
Done :) also, sadly I don't have @ filippo on GitHub. ;)

**Comment by andybons** [comment]
D’oh. Too many namespaces to keep track of. 😆
