### ISSUE TITLE
syscall, x/sys/unix: ustat is deprecated and has been removed from glibc

### ISSUE THREAD

**Issue by fweimer** [golang/go#25990]
`src/syscall/types_linux.go` includes `<ustat.h>`.  The `ustat` system call was deprecated well before Go development started, and the [`ustat` manual page](http://man7.org/linux/man-pages/man2/ustat.2.html) said so since basically forever.

glibc 2.28 will remove the header file, so Go will no longer build.  Seen so far with `libgo` on the GCC branch `gcc-8-branch`.  Go 1.0.3 itself still appears to build.  However, I think it makes sense to remove this interface upstream as well.

**Comment by tklauser** [comment]
`<ustat.h>` is included in `src/syscall/types_linux.go` only to generate the syscall wrapper functions, types and constants. It's not used in the build it self, so the build won't break event if glibc remove the header. But we will no longer be able to (re-)generate the wrappers.

In `golang.org/x/sys/unix` (which should be used instead of `syscall` outside the standard library anyhow) https://golang.org/cl/119655 just recently deprecated `Ustat` for `linux/arm64` and I think we should do the same for all other `GOARCH`es.

About `syscall` I'm not sure. I think we might want to return `ENOSYS`, but removing the function would probably break the Go 1 compatibility promise. In any case, I'll let @ianlancetaylor decide on that one.

**Comment by tklauser** [comment]
We might even remove `Ustat` from `golang.org/x/sys/unix` altogether IMO. The Go 1 compatibility promise doesn't apply there.

**Comment by awilfox** [comment]
Just to chime in from the musl side, musl has never shipped a `<ustat.h>`, which did not break the build of GCC's libgo here, but caused an error during linking:

```
../powerpc-foxkit-linux-musl/libgo/.libs/libgo.so: undefined reference to `ustat'
```

I think that if glibc actually removes the symbol, not just the header, then there will be further pain in GCC libgo.

**Comment by fweimer** [comment]
glibc 2.28 will remove the symbol in the sense that new binaries can no longer link, so there's a link failure with `libgo.so` as well.

**Comment by awilfox** [comment]
Doesn't seem to remove it from Makefile.am/Makefile.in, so it just ends up with an error:

```
make[4]: *** No rule to make target 'go/syscall/libcall_linux_ustat.go', needed by 'syscall.lo'.  Stop.
```

The following patch fixes it:

```patch
--- gcc-6.4.0/libgo/Makefile.am.old     2016-02-03 15:58:02.419872000 -0600
+++ gcc-6.4.0/libgo/Makefile.am 2018-06-23 02:55:45.772611885 -0500
@@ -1,4 +1,3 @@
-# Makefile.am -- Go library Makefile.

 # Copyright 2009 The Go Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style
@@ -1989,17 +1988,6 @@
 syscall_lsf_file =
 endif

-# GNU/Linux specific ustat support.
-if LIBGO_IS_LINUX
-if LIBGO_IS_ARM64
-syscall_ustat_file =
-else
-syscall_ustat_file = go/syscall/libcall_linux_ustat.go
-endif
-else
-syscall_ustat_file =
-endif
-
 # GNU/Linux specific utimesnano support.
 if LIBGO_IS_LINUX
 syscall_utimesnano_file = go/syscall/libcall_linux_utimesnano.go
@@ -2051,7 +2039,6 @@
        $(syscall_uname_file) \
        $(syscall_netlink_file) \
        $(syscall_lsf_file) \
-       $(syscall_ustat_file) \
        $(syscall_utimesnano_file) \
        $(GO_LIBCALL_OS_FILE) \
        $(GO_LIBCALL_OS_ARCH_FILE) \
--- gcc-6.4.0/libgo/Makefile.in.old     2016-02-03 15:58:02.419872000 -0600
+++ gcc-6.4.0/libgo/Makefile.in 2018-06-23 02:56:04.842611681 -0500
@@ -2080,11 +2080,6 @@

 # GNU/Linux specific socket filters.
 @LIBGO_IS_LINUX_TRUE@syscall_lsf_file = go/syscall/lsf_linux.go
-@LIBGO_IS_ARM64_FALSE@@LIBGO_IS_LINUX_TRUE@syscall_ustat_file = go/syscall/libcall_linux_ustat.go
-
-# GNU/Linux specific ustat support.
-@LIBGO_IS_ARM64_TRUE@@LIBGO_IS_LINUX_TRUE@syscall_ustat_file = 
-@LIBGO_IS_LINUX_FALSE@syscall_ustat_file = 
 @LIBGO_IS_LINUX_FALSE@syscall_utimesnano_file = go/syscall/libcall_posix_utimesnano.go

 # GNU/Linux specific utimesnano support.
@@ -2122,7 +2117,6 @@
        $(syscall_uname_file) \
        $(syscall_netlink_file) \
        $(syscall_lsf_file) \
-       $(syscall_ustat_file) \
        $(syscall_utimesnano_file) \
        $(GO_LIBCALL_OS_FILE) \
        $(GO_LIBCALL_OS_ARCH_FILE) \
```

**Comment by tklauser** [comment]
@awilfox want to send the patch as a CL (https://golang.org/doc/contribute.html)?

**Comment by awilfox** [comment]
@tklauser I'd be happy to, but I'm going to have to actually manage to have Go binaries running properly on my development workstation before I can install `git-codereview`.

That might take some time; I have a friend who's already signed the CLA so I may let them submit it instead, assuming they approve of the change (it's simple, so I don't see why not).

**Comment by ianlancetaylor** [comment]
@awilfox I'm not maintaining the GCC 6 branch any more.  I'm not even sure that the branch is still open; it's been a year since the last GCC 6 release.

The Makefile patch you mention is not required on GCC 7 or newer.

**Comment by ianlancetaylor** [comment]
@awilfox Actually it turns out that there will be a 6.5 release, so I just committed the patch to the GCC 6 branch, including the Makefile change.
