### ISSUE TITLE
no Go files in /home/r3mb0/GoMobile/src/golang.org/x/mobile/example/bind/android

### ISSUE THREAD

**Issue by r3mb00** [golang/go#25997]
Hi.
My go version is:
go version go1.10.2 linux/amd64

Yes, it is.

My Go env:
OARCH="amd64"
GOBIN=""
GOCACHE="/home/r3mb0/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/r3mb0/GoMobile"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build517142902=/tmp/go-build -gno-record-gcc-switches"

go get golang.org/x/mobile/example/bind/android

Shows error 

![screenshot at 2018-06-21 15-01-08](https://user-images.githubusercontent.com/9653037/41730775-9c5e3990-754a-11e8-9785-54f3bb70c1ab.png)

package golang.org/x/mobile/example/bind/android: no Go files in /home/r3mb0/GoMobile/src/golang.org/x/mobile/example/bind/android

**Comment by AlexRouSg** [comment]
Where did you get the command `go get golang.org/x/mobile/example/bind/android`? `golang.org/x/mobile/example/bind/android` Is not a Go package so it will error.

The instructions from https://github.com/golang/go/wiki/Mobile say to run `go get -d golang.org/x/mobile/example/bind/...`

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions.  You will get better answers on a forum; see https://golang.org/wiki/Questions .
