### ISSUE TITLE
cmd/go: network error - all or nothing

### ISSUE THREAD

**Issue by millergarym** [golang/go#25995]
### What version of Go are you using (`go version`)?
1.10.3

The vgo process is very susceptible to network errors. Can it incrementally create the cache and record entries in the go.mod file. 

The go.mod file can have an entry recording the fact that the last command wasn't clean (complete).

**Comment by rsc** [comment]
Can you say a little more about the specific operation? In general vgo does cache what it downloads from the network to local disk, even before it updates go.mod, so it should mostly pick up where it left off.
