### ISSUE TITLE
x/vgo: "no Go source files" when importing package google.golang.org/api

### ISSUE THREAD

**Issue by millergarym** [golang/go#25994]
### What version of Go are you using (`go version`)?

go 1.10.3
vgo commit c07973ea63c163b154225425f63290d022df8650

### What operating system and processor architecture are you using (`go env`)?
windows

### What did you do?

```
package example // import "x.y/z/a"

import (
  _ "google.golang.org/api"
)
```

```
module x.y/z/a
```

### What did you see instead?
vgo build returned "no Go source files"

## vgo list 
`vgo list -f "{{.}}" google.golang.org/api` also return a message along the line of no Go source.

**Comment by AlexRouSg** [comment]
`google.golang.org/api` is not a package, you need to import one of the actual packages inside the folder

**Comment by bcmills** [comment]
Closing per @AlexRouSg's comment. (If you're having trouble importing specific subpackages, please reopen with more detail.)

**Comment by AlexRouSg** [comment]
@millergarym This issue is not about vgo supporting getting repo's with non go files. This is about importing a non go package and having a non go package in the mod file. That is not something vgo would allow you to do.

Currently when vgo gets a package it gets the entire repo. So you shouldn't need to specifically tell it to get the non go files folders.

**Comment by myitcv** [comment]
> This is about importing a non go package and having a non go package in the mod file.

@millergarym at present there is no concept of a "non go package": packages are defined by being just that, collections of Go (and related) code. See `go help list` for the full breakdown of what the `go` tool understands as the contents of a package. 

So whilst this might be a potential future extension of `vgo`/`go`, I don't personally see this as being something that will be supported in the short term. 

The workaround as described is to drop a single `.go` file along with a `go.mod` file as a container for the non Go files you want to package, or to side-step `vgo` altogether and manage the dependency yourself/using some other tool.
