### ISSUE TITLE
Adding Gomobile Gradle plugin to Android Studio

### ISSUE THREAD

**Issue by r3mb00** [golang/go#25996]
Hi.
My go version is: 
go version go1.10.2 linux/amd64 

Yes, it is.

My Go env:
OARCH="amd64"
GOBIN=""
GOCACHE="/home/r3mb0/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/r3mb0/GoMobile"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build517142902=/tmp/go-build -gno-record-gcc-switches"

I downloaded and installed android studio for linux (deb in my case).
I went to plugin section and type Golang, gomobile etc for ability to add gomobile gradle plugin to IDE.
I expected to see Gomobile Gradle Plugin for Android Studio and have ability to add it.
I don't see Gomobile Gradle Plugin for Android Studio and can't add it to IDE.

Can anyone help a nob like me, please ?

**Comment by AlexRouSg** [comment]
The gradle plugin has not been maintained and they are thinking of removing it altogether. See #25314

Also note that the bug tracker is not for questions, please see https://github.com/golang/go/wiki/Questions for better places to ask for help.

**Comment by ianlancetaylor** [comment]
Closing as this is not something that can be done by the Go team.
