### ISSUE TITLE
cmd/go: case mismatch on Windows

### ISSUE THREAD

**Issue by millergarym** [golang/go#25992]
### What version of Go are you using (`go version`)?
go 1.10.3
vgo commit c07973ea63c163b154225425f63290d022df8650

### What operating system and processor architecture are you using (`go env`)?
windows 

### What did you do?

example.go
``` go 
package vgot // import "some.package/p/vgot"

import (
	_ "github.com/docker/docker"
	_ "github.com/sirupsen/logrus"
)
```

go.mod
```
module some.package/p/vgot
```

`vgo build`

### What did you see instead?

```
			return nil, fmt.Errorf("downloaded %q and got module %q", mod.Path, mpath)
```

**Comment by bcmills** [comment]
Closely related to https://github.com/golang/go/issues/25878 and https://golang.org/cl/118738 (CC: @bradfitz).

**Comment by rsc** [comment]
I think what's going on here is that the (old) docker you got
has its own import of "github.com/Sirupsen/logrus",
and then your code has an import of "github.com/sirupsen/logrus",
and the two collide in the GOPATH/src/mod/cache/download tree.

Unfortunately, the layout of that tree was chosen to match the
HTTP REST API file tree, so it's not a purely internal detail we can
just change (using "_sirupsen" for "Sirupsen" for example).
