### ISSUE TITLE
x/vgo: Doesn't seem to be finding tags correctly

### ISSUE THREAD

**Issue by aarondl** [golang/go#26003]
### What version of Go are you using (`go version`)?

go version go1.10.2 linux/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?

Yes (of vgo, haven't updated Go if there's a new release of that).

### What operating system and processor architecture are you using (`go env`)?

Linux amd64.

### What did you do?

Tried several different ways to use v3.0.0-rc5 of my library: https://github.com/volatiletech/sqlboiler/tree/v3.0.0-rc5.

I imported:

```go
package main // import "github.com/aarondl/newproject"

import (
	"fmt"
	"os"

	"github.com/volatiletech/sqlboiler/v3/strmangle"
)

func main() {
	_ = strmangle.TitleCase
}
```

And then used a `go.mod` that specified `v3.0.0-rc5`.

I also tried to list the tags available in that repo:

```bash
$ vgo list -t github.com/volatiletech/sqlboiler
github.com/volatiletech/sqlboiler
	v1.0.0
```

### What did you expect to see?

I expected to see the tag v3.0.0-rc5 in the go.mod file (and I expected it to stay when I manually coerced it to the correct thing).
I expected to see it correctly list the v1, v2, and v3 tags that exist in that repository, here's some of the tags
that I expected to see:

```text
v1.0.0
v2.0.0
v2.7.1
v2.7.2
v3.0.0-rc4
v3.0.0-rc5
```

### What did you see instead?

I do not see a tag (though I do see the correct commit) in the vgo go.mod file:

```text
module github.com/aarondl/newproject

require (
	github.com/volatiletech/sqlboiler v0.0.0-20180620223943-64005efb0df2
)
```

I do not see the correct tags listed in the repository:

```text
vgo list -t github.com/volatiletech/sqlboiler
github.com/volatiletech/sqlboiler
	v1.0.0
```

**Comment by kardianos** [comment]
sqlboiler needs a go.mod file spevifiying a v3 module path. Add that and you should be golden.

**Comment by aarondl** [comment]
> go will not use any v2 or later tag in a source code repository without first checking that it has a go.mod with a module path declaration ending in that major version (for example, module "my/thing/v2"). Vgo uses that declaration as evidence that the author is using semantic import versioning to name packages within that module. This is especially important for multi-package modules, since the import paths within the module must contain the /v2/ element to avoid referring back to the v1 module.

Ugh. I guess I didn't read close enough. Answered my own question I suppose. The reasoning is unfortunately kind of sound too so I can't even nitpick it too much. Though I think it's definitely a very bad decision to have done it this way. How am I supposed to support non-vgo at the same time? If I change all these import paths to use /v3, it'll break my existing users that don't use vgo since that isn't an import path that can ever possibly exist.

**Comment by kardianos** [comment]
There are point releases for 1.10 and 1.9 that allow working with vX paths. For the this transition, some packages will need to continue to use the v0-rev notation to get versions larger then v1. What you discovered has already been addressed.
