### ISSUE TITLE
go file writing(os.OpenFile) mess with old content after os.Rename

### ISSUE THREAD

**Issue by devfans** [golang/go#26004]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
macOS amd64

### What did you do?
```
// backup old dir
if _, err = os.Stat(configDir); err == nil {
  err = os.Rename(configDir, configDir+string(time.Now().Format(time.RFC3339)))
  if err != nil {
    log.Fatalf("Failed to rename old config file %v.\n", configDir)
  }
  _ = os.Remove(configDir)
}
f, err := os.OpenFile(configDir, os.O_RDWR|os.O_CREATE, 0664)
checkError(err)
defer f.Close()
// write file content with f.WriteString
```

### What did you expect to see?
I expect no old file content in it

### What did you see instead?
new content messing with old content in the file

**Comment by devfans** [comment]
The line
```_ = os.Remove(configDir)
```
was added to try to get rid of the issue, but it does not help.

**Comment by davecheney** [comment]
Thank you for your error report. Can you please show us a complete runnable program which demonstrates the issue

**Comment by devfans** [comment]
It's a small package  [envconf](https://github.com/devfans/envconf)
Here's the code to reproduce the issue:
```
package main

import (
  "github.com/devfans/envconf"
)

func main() {
  url := ""
  conf := envconf.NewConfig("~/.ssh/store")
  conf.Put("store", "etcd")
	conf.Section = "etcd"
	if url == "" {
		url = conf.Get("ETCD_URL", "url")
	}

  conf.Put("url", url)
  conf.Save()
}
```
After run it twice, you will see some messing content in the file: .ssh/store

**Comment by devfans** [comment]
Seems the issue is not related with go. It's the logic in my codes. I found the reason. Thanks through!
