### ISSUE TITLE
net: JoinHostPort should not add [ ] when the host is ipv6 and it is surrounded by brackets

### ISSUE THREAD

**Issue by Sherlock-Holo** [golang/go#26006]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sherlock/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sherlock/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032343756=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
https://play.golang.org/p/faeZpo0P020

### What did you expect to see?
> `[fe80::2b4f:2681:f032:55fd]:80`

### What did you see instead?
> `[[fe80::2b4f:2681:f032:55fd]]:80`

I think JoinHostPort can identify this host is an ipv6 address, and we can use `strings.HasPrefix` and `strings.HasSuffix` to check if the ipv6 address already has the bracket. If it already has brackets, I think JoinHostPort should not add it again

**Comment by agnivade** [comment]
The function works as documented - 

>  If host contains a colon, as found in literal IPv6 addresses, then JoinHostPort returns "[host]:port".

Checking for `[` and `]` might be overdo when the user can do it themselves. And moreover, it is a breaking change, and might have unforeseen consequences.

/cc @bradfitz.

**Comment by ianlancetaylor** [comment]
CC @mikioh

**Comment by Sherlock-Holo** [comment]
@agnivade I wonder why it's a breaking change because no matter you give the ipv6 has `[` `]`, it returns the right string like `[fe08:xx:xx::x]:80`

**Comment by Sherlock-Holo** [comment]
@agnivade like you say the users can check by themselves, but if the `net` module in std can do it better, why users need to write an additional function to do this job

**Comment by bradfitz** [comment]
I don't think it's legal to have a hostname with brackets. I think they're only valid in the host:port form.

**Comment by Sherlock-Holo** [comment]
@bradfitz yeah but in golang, when we use `Dial` , if the address is `ipaddress:port`, the ipv6 address should be wrapped by the square brackets, if an address is wrapped by `[` `]` and it has more than one `:`, I think it must be an ipv6 address.

**Comment by agnivade** [comment]
@Sherlock-Holo - It's a breaking change because you want it to return `[fe80::2b4f:2681:f032:55fd]:80` whereas it returns `[[fe80::2b4f:2681:f032:55fd]]:80` currently. So programs expecting `[[..]]` will break.

**Comment by Sherlock-Holo** [comment]
@agnivade yes some programs check if `[[..]]` or not, but if `JoinHostPort` return `[fe80::2b4f:2681:f032:55fd]:80` ,the check will not break because we get the right address, and programs work well without `[[..]]` error

**Comment by bradfitz** [comment]
@agnivade, I'm not concerned about breaking people who depend on getting bogus `[[...]]`. I don't think such people exist, because that's already bogus. But I don't think we should make it easier for people to do bogus things.

I'm just not seeing how somebody ends up with brackets around an IPv6 literal without a port. Where do such values come from that you then need to call `JoinHostPort` with them?

**Comment by Sherlock-Holo** [comment]
for example, som people write `fe80::2b4f:2681:f032:55fd` into a  config file, some peolple write `[fe80::2b4f:2681:f032:55fd]`

**Comment by bradfitz** [comment]
@Sherlock-Holo, what other software accepts an IP (without a port) with brackets?

**Comment by rsc** [comment]
JoinHostPort joins a host and a port. [ipv6addr] is not a host. Sorry.

**Comment by Sherlock-Holo** [comment]
oh what is HOST? what is the definition of host？？？

Russ Cox <notifications@github.com> 于 2018年6月26日周二 04:05写道：
