### ISSUE TITLE
runtime/chan.go[func closechan()]  Why setting `c.closed` after `lock(&c.lock)`?

### ISSUE THREAD

**Issue by sipt** [golang/go#26011]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
any

### What did you do?
read the source

### What did you expect to see?
```go
// runtime/chan.go 
func closechan(c *hchan) {
	for {
		if atomic.CompareAndSwapUint32(&c.closed, 0, 1) {
			break
		}
		if c.closed != 0 {
			panic(plainError("close of closed channel"))
		}
	}
	lock(&c.lock)
	// release all readers
	// release all writers (they will panic)
	unlock(&c.lock)
	// Ready all Gs now that we've dropped the channel lock.
}
```

### What did you see instead?
```go
// runtime/chan.go 
func closechan(c *hchan) {
	lock(&c.lock)
	c.closed = 1
	// release all readers
	// release all writers (they will panic)
	unlock(&c.lock)
	// Ready all Gs now that we've dropped the channel lock.
}
```

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
