### ISSUE TITLE
x/build: add js/wasm trybot

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26015]
Add either a just-compile or a sharded testing js/wasm trybot.

Would've prevented #26014.

/cc @ianlancetaylor @neelance @andybons @bcmills @FiloSottile

**Comment by myitcv** [comment]
@bradfitz - I'm not so familiar with how the builders work, but would it be possible to have Node, Chrome and Firefox installed on the image/setup where the `js/wasm` tests then run? 

Headless tests via Chrome and Firefox at least would likely be a big help.

**Comment by bradfitz** [comment]
@myitcv, let's keep this bug about just TryBot-ifying the existing Node-based wasm builder. Creating a new Chrome and/or Firebox-based builder is possible I'm sure, but let's track that elsewhere.

**Comment by bradfitz** [comment]
This is deployed. I'll watch its performance.
