### ISSUE TITLE
mmap.Open panics on a file > 1GB 

### ISSUE THREAD

**Issue by ericrchr** [golang/go#26028]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

### What did you do?
Called mmap.Open() on a file that is 1.5GB in size

### What did you expect to see?
Normal return

### What did you see instead?
panic: runtime error: slice bounds out of range

goroutine 31 [running]:
golang.org/x/exp/mmap.Open(0xc04214c000, 0x26, 0x0, 0x0, 0x0)
	C:/pixelplow/Go/src/golang.org/x/exp/mmap/mmap_windows.go:111 +0x7d1

###
I am NOT a Go expert, but the line in question
	data := (*[1 << 30]byte)(unsafe.Pointer(ptr))[:size]
would appear to expect size to be less than 1 << 30  (1GB) which is not true.

**Comment by meirf** [comment]
I assume that is for portability - assuming the architecture is 32bit. Some discussion here: https://groups.google.com/forum/#!topic/golang-nuts/c6ufk6KbIk8.

**Comment by alexbrainman** [comment]
> My guess is that is for portability. I.e. the code conservatively assumes the architecture is 32bit.

I do not remember why we set it to 1 << 30. But you can make it as large as you like - as long as your GOARCH allows that. If you on amd64, make it 1 << 40, and that should be large enough for your 1.5GB file.

Alex

**Comment by mattn** [comment]
`1<<31-1` works with more large size.

@alexbrainman Should I fix with separate 32/64 bit architecture?

**Comment by alexbrainman** [comment]
> @alexbrainman Should I fix with separate 32/64 bit architecture?

Please, do. Thank you.

Alex
