### ISSUE TITLE
x/exp/io/spi: SPI on mipsle uses wrong IOCTL

### ISSUE THREAD

**Issue by svenschwermer** [golang/go#26026]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="mipsle"
GOBIN=""
GOCACHE="/Users/sven/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="linux"
GOPATH="/Users/sven/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
GOMIPS="softfloat"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -mabi=32 -march=mips32 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_j/ly_hzzjx5vjd2qbzd8qd2bch0000gn/T/go-build245470376=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
I used `golang.org/x/exp/io/spi` to write to an SPI device on a MIPS (32 bit, little endian) target.

The IOCTL used for writing the data (in `spi.(*devfsConn).Tx`) is wrong. The returned error message is `inappropriate ioctl for device`. `strace` prints `ioctl(3, _IOC(_IOC_READ, 0x6b, 0, 0x20), 0x8c33efc) = -1 ENOTTY (Not a tty)` instead of `ioctl(3, SPI_IOC_MESSAGE(32), 0x8933f20) = 2`.

If I'm not mistaken, the IOCTLs are offset on MIPS targets. See https://github.com/torvalds/linux/blob/master/arch/mips/include/uapi/asm/ioctl.h and https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/ioctl.h#L32

**Comment by ianlancetaylor** [comment]
CC @rakyll

**Comment by svenschwermer** [comment]
Here is a proposal for a fix: https://github.com/svenschwermer/golang.org-x-exp/commit/8026287ed771db5931f67f4b748bc9a81dfdf223
This should also fix #16551.

**Comment by maruel** [comment]
Thanks. I filed https://github.com/google/periph/issues/263 to correctly handle this in periph.io.

We don't plan to modify exp/io anymore.

**Comment by ALTree** [comment]
Since `x/exp/io` is no longer developed and essentially frozen, I'm closing this issue.
