### ISSUE TITLE
reflect: when creating anonymous fields, StructOf should attempt to compute the field name

### ISSUE THREAD

**Issue by jimmyfrasche** [golang/go#26035]
Creating an anonymous field with `reflect.StructOf` panics if not explicitly given a name.

A name must be provided when the embedded type is not defined or the name differs from the name of the defined type, to simulate embedding of an alias to a defined type. It is necessary to require an explicit name in these cases.

However, the common case, and hence user expectation, is that embedding a defined type creates a field with the same name as the defined type.

For any `T` representing a defined type, the following should be equivalent:
```
reflect.StructOf([]reflect.StructField{
  {
    Name: T.Name(), // Or T.Elem().Name()
    Type: T,
    Anonymous: true,
  },
})
```
and
```
reflect.StructOf([]reflect.StructField{
  {
    Type: T,
    Anonymous: true,
  },
})
```

Originally reported by @Merovius as part of #24781. I'm breaking it into a separate issue for easier tracking.

**Comment by jimmyfrasche** [comment]
cc @rsc @ianlancetaylor per golang/s/owners

**Comment by ianlancetaylor** [comment]
Probably a dup of #24781.

**Comment by jimmyfrasche** [comment]
@ianlancetaylor I forked this off that issue because it has 2 or 3 other things going on that may or may not be bugs (which may be a dupe of #24721 though this is not a dupe of that). This can be handled and tracked separately.

**Comment by rsc** [comment]
Given how difficult and subtle this all is, it seems better to require the caller to specify the name, as we always have. I'm already skeptical of StructOf, but more skeptical of more magic. Also we learned during alias that we may need to have the idea of anonymous fields with names different from types. The current behavior is more explicit, which is good.
