### ISSUE TITLE
x/sys/unix: TestUtimesNanoAt fails

### ISSUE THREAD

**Issue by jimmyfrasche** [golang/go#26034]
```
$ go test golang.org/x/sys/unix
--- FAIL: TestUtimesNanoAt (0.00s)
	syscall_linux_test.go:144: UtimesNanoAt: wrong atime: {1111 0}
	syscall_linux_test.go:147: UtimesNanoAt: wrong mtime: {3333 0}
FAIL
FAIL	golang.org/x/sys/unix	0.376s
```

I'm not entirely sure what UtimesNanoAt is, but looking at the test it appears my system doesn't record the nanoseconds.

This could be because of the hilariously old file system on this very old mount: 
```
/dev/sda2 on / type ext2 (rw,relatime,block_validity,barrier,user_xattr,acl,errors=remount-ro)
```

Since this is vendored in cmd, I can't build tip without adding a t.Skip() to the test

#### System details

```
go version go1.10.3 linux/amd64
GOARCH="amd64"
GOBIN="/home/jimmy/bin"
GOCACHE="/home/jimmy/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jimmy/code/go"
GORACE=""
GOROOT="/home/jimmy/ext/go"
GOTMPDIR=""
GOTOOLDIR="/home/jimmy/ext/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007543697=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.10.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
uname -sr: Linux 4.16.0-2-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.27-3) stable release version 2.27.
gdb --version: GNU gdb (Debian 7.12-6+b2) 7.12.0.20161007-git
```

**Comment by jimmyfrasche** [comment]
cc @tklauser

**Comment by tklauser** [comment]
I guess we should do the same as https://golang.org/cl/114616 did for TestStatx and just drop the atime comparison since not all filesystems support atime or it might be disabled by the `noatime` mount option. I'll send a CL, thanks.

**Comment by tklauser** [comment]
@ianlancetaylor @bradfitz should the vendored copy in cmd be updated as well to fix this? I can send another CL once https://golang.org/cl/120562 is reviewed and submitted.

**Comment by jimmyfrasche** [comment]
Thanks for the fast response, but now I'm getting
```
$ go get -u golang.org/x/sys/unix
$ go test golang.org/x/sys/unix
--- FAIL: TestUtimesNanoAt (0.00s)
	syscall_linux_test.go:146: UtimesNanoAt: wrong mtime: {3333 0}
FAIL
FAIL	golang.org/x/sys/unix	0.375s
```

That drive wasn't mounted noatime (though I'm sure somebody has such a set up so that was legitimate change, nonetheless).

That time struct is (seconds, nanoseconds). For both, my system is returning the correct seconds but 0 nanoseconds. It's truncating it. I'm guessing my fs doesn't record ns in timestamps.

**Comment by jimmyfrasche** [comment]
@tklauser there are a lot of file systems and they appear to have different time stamps resolution, though all the newer ones are quite precise. The LCD seems to be 1-second resolution so maybe the test should only test that?

**Comment by mvdan** [comment]
@tklauser do send a CL updating the vendored unix repo. This issue is keeping the linux-arm-arm5spacemonkey builder consistently red: https://build.golang.org/log/db415f5587cf146294712dad6ae50ef6e358544f
