### ISSUE TITLE
cmd/link: failed to set variable at build time if variable value is result from method call

### ISSUE THREAD

**Issue by Gnouc** [golang/go#26042]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cuonglm/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cuonglm/go"
GORACE=""
GOROOT="/home/cuonglm/sources/go"
GOTMPDIR=""
GOTOOLDIR="/home/cuonglm/sources/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build755255777=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
https://play.golang.org/p/M9xGmognyrl

run as:

```
go run -ldflags "-X main.X=y -X main.MyX=myY" main.go
```
### What did you expect to see?
```
y
myY
```

### What did you see instead?
```
y
myX
```

**Comment by ianlancetaylor** [comment]
I think that fixing this would require a completely different and less efficient approach to the implementation of the linker's `-X` option.  I'm inclined to just make this a documented limitation.

**Comment by ianlancetaylor** [comment]
Every global variable has memory allocated in the data section of the program.  The contents of the data section are set to the initial value of the variable.  For a variable initialized with a function call, the variable's value is set by an initialization function.  The `-X` option simply changes the initial value stored in the data section, but does not affect the initialization function.

The implementation of `-X` is the function `addstrdata` in cmd/link/internal/ld/data.go, which sets the global variable `strdata`, and then `dostrdata` which calls `addstrdata` for each element of `strdata`.

**Comment by Gnouc** [comment]
@ianlancetaylor Thanks. I went through those codes already but don't fully understand them.

/me will send the CL this morning
