### ISSUE TITLE
x/vgo: vgo mod support for -f and .Dir in -json output

### ISSUE THREAD

**Issue by myitcv** [golang/go#26044]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10.3 linux/amd64
vgo commit 0f3e556044ecbd8a0805d098e52a743a1d0e3566
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/tmp.7KXsauqfrA"
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build223819470=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```
cd `mktemp -d`
export GOPATH=$PWD
mkdir hello
cd hello
vgo mod -init -module example.com/hello
vgo mod -json
```

### What did you expect to see?

```json
{
        "Module": {
                "Path": "example.com/hello",
                "Version": "",
                "Dir": "/tmp/tmp.7KXsauqfrA/hello"
        },
        "Require": null,
        "Exclude": null,
        "Replace": null
}
```

### What did you see instead?

```json
{
        "Module": {
                "Path": "example.com/hello",
                "Version": ""
        },
        "Require": null,
        "Exclude": null,
        "Replace": null
}
```

Having `.Dir` be part of the output of `vgo mod -json` would allow other tools to use `vgo mod` to resolve the containing directory of a module ([context](https://groups.google.com/d/msg/golang-nuts/nX8f90H4Hv8/M4IYTnN2CgAJ)). Correspondingly, having a `-f` flag (equivalent of `(v)go list -f`) would be useful to programatically extract values returned from `-json`, including `.Module.Dir`.

**/cc** @rsc @bcmills

**Comment by bcmills** [comment]
Does the `list -m -json` and `list -m -f` support in https://golang.org/cl/120198 do what you need?

**Comment by myitcv** [comment]
I don't think so - that only gives me (building on the example above):

```
$ vgo list -m -json
{
        "Path": "example.com/hello",
        "Main": true
}
```

which looks to be a "subset" of the output from `vgo mod -json`?
