### ISSUE TITLE
x/vgo: `vgo build/install` default binary name for module versions >=2

### ISSUE THREAD

**Issue by mwf** [golang/go#26047]
### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64 vgo:2018-02-20.1

Latest `vgo`:
```
commit 0f3e556044ecbd8a0805d098e52a743a1d0e3566 (HEAD -> master, origin/master, origin/HEAD)
Author: Tim Cooper <tim.cooper@layeh.com>
Date:   Fri Jun 22 17:51:20 2018 -0300

    cmd/go/internal/modcmd: fix sorting
```

### What did you do?

Please refer to https://github.com/mwf/goplay/tree/master/vgo/hello_world

The same case as in #26046, a binary with major version 2.0.0.

go.mod:
```
module github.com/mwf/goplay/vgo/hello_world/v2
```

`cd` to hello_world module directory

### What did you expect to see?

`vgo build .` should produce binary named `hello_world`, as it should correspond with actual module **name** instead of the version.

### What did you see instead?

`vgo build .` produces binary named `v2`

The same thing if you use `vgo install`:

```
$ vgo install github.com/mwf/goplay/vgo/hello_world
vgo: resolving import "github.com/mwf/goplay/vgo/hello_world"
vgo: finding github.com/mwf/goplay/vgo/hello_world (latest)
vgo: adding github.com/mwf/goplay/vgo/hello_world v1.0.1

$ ls -al $GOPATH/bin
-rwxr-xr-x   1 ikorolev  staff   2093408 Jun 25 18:51 hello_world@v1.0.1
```

Compare to v2 installation:
```
$ vgo install github.com/mwf/goplay/vgo/hello_world/v2
vgo: resolving import "github.com/mwf/goplay/vgo/hello_world/v2"
vgo: finding github.com/mwf/goplay/vgo/hello_world/v2 v2.0.0
vgo: finding github.com/mwf/goplay/vgo/hello_world/v2 (latest)
vgo: adding github.com/mwf/goplay/vgo/hello_world/v2 v2.0.0
vgo: downloading github.com/mwf/goplay/vgo/hello_world/v2 v2.0.0

$ ls -al $GOPATH/bin
-rwxr-xr-x   1 ikorolev  staff   2093408 Jun 25 18:55 v2@v2.0.0
```

**Comment by oiooj** [comment]
duplicate of #24667

**Comment by mwf** [comment]
Thanks @oiooj, didn't manage to find it :) 

Closing this issue.
