### ISSUE TITLE
why the previous column is nil can affect the value of the next column?

### ISSUE THREAD

**Issue by krisai** [golang/go#26057]
```
$go version
go version go1.8.3 darwin/amd64
```
Assuming my table has two columns，`name(VARCHAR),sex(TINYINT)`
`select name,sex from mytable`
if the name has nil value, the next column sex will be zero even though is not zero,
have anybody this problem?

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
