### ISSUE TITLE
cmd/dist: enable all js/wasm tests that should pass in dist

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26050]
@neelance, please modify cmd/dist/test.go to enable all tests you expect to pass for js/wasm.

I disabled a bunch of tests in 7d50abf039 because I needed to finally see some black on the dashboard for the js-wasm column to be able to enable trybots and start catching regressions (like #26014)

/cc @cherrymui

**Comment by bradfitz** [comment]
Test:

```
$ GOOS=js GOARCH=wasm ./all.bash
```

... which ultimately calls `dist`. But yes, you can test it with `go tool dist test` too.

Note parts of https://github.com/golang/go/wiki/PortingPolicy mentioning all.bash:

> Once those conditions are satisfied, the Go team can accept the port and begin to merge the CLs. Once the CLs are all submitted, all.bash must pass, so that the builder reports "ok" in the dashboard.
>
> Any port started during a release cycle must be finished (all.bash passing, builder reporting "ok") before the corresponding release freeze, or else the code will be removed at the freeze.

**Comment by neelance** [comment]
@bradfitz Thanks!
