### ISSUE TITLE
cmd/cgo doesn't use CXXFLAGS

### ISSUE THREAD

**Issue by co11ter** [golang/go#26069]
### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

I want to call C code in Golang:
```
package main

// #cgo CFLAGS: -I/usr/include/c++/8.1.1/bits
// #cgo CXXFLAGS: -std=gnu++11
// #include "c++0x_warning.h"
import "C"

func main() {}
```
and run ```go build```
### What did you expect to see?
A successful build

### What did you see instead?
Get error:

```
$ go build
# trade
In file included from ./main.go:5:
/usr/include/c++/8.1.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~
```

### go env

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/co11ter/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/co11ter/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build083114149=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ianlancetaylor** [comment]
As documented at https://golang.org/cmd/cgo, `#cgo CXXFLAGS` directives are used to compile C++ files in the package directory.  They are not used to compile the preamble comment before the `import "C"`.  That preamble comment, including anything that it `#include`'s, must be written in C.

Closing because the tool is working as documented.
