### ISSUE TITLE
x/mobile: "URGENT: building for iOS simulator, but linking in object file"

### ISSUE THREAD

**Issue by OpenFibers** [golang/go#26064]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
macOS x86_64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/openthread/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8y/fl7bxlp163b8mtx9_v__6mxm0000gn/T/go-build723202614=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
running gomobile ios demo

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

build hello.framwork, then build xcode project

### What did you expect to see?
no warning 

### What did you see instead?
there is warning "URGENT: building for iOS simulator, but linking in object file (/Users/openthread/go/src/golang.org/x/mobile/example/bind/ios/Hello.framework/Hello(000001.o)) built for OSX. Note: This will be an error in the future."

**Comment by bcmills** [comment]
CC: @eliasnaur

**Comment by bcmills** [comment]
> build hello.framwork, then build xcode project

More detail would be helpful. What commands did you follow to build `hello.framework`? What version of Xcode are you using, and what commands did you use to build the Xcode project?

**Comment by eliasnaur** [comment]
I can't reproduce this with Xcode 9.4.1, Go 1.10.1 and the latest version of gomobile (rev. 6621de06e1e9d52c38a8c542770bdbeac9ecfef6). I built Hello.framework with

$ gomobile bind -target ios golang.org/x/mobile/example/bind/hello

and then I built (and ran) the hello Xcode project on the iPhone SE emulator. The only warning I saw was about updating the project settings.

**Comment by OpenFibers** [comment]
after I upgrade to go 1.10.3, remake hello.framework, warnings disappear

**Comment by OpenFibers** [comment]
@eliasnaur this issue resolved : ) 
Thank you for your help : )
