### ISSUE TITLE
release: virus checker Avast reported that trace.exe is infected with Win64:malware-gen

### ISSUE THREAD

**Issue by bobmacdonald** [golang/go#26065]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

#### System details

```
go version go1.10.3 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\bmac2\AppData\Local\go-build"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\bmac2\Go"
GORACE=""
GOROOT="C:\Go"
GOTMPDIR=""
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\bmac2\Go\src\bmac\go-build844975738=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.10.3 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
```

On installing the .msi, Avast reported that trace.exe is infected with Win64:malware-gen.  The file was quarantined.

**Comment by ianlancetaylor** [comment]
Historically these reports from virus checkers have always been false positives.

**Comment by ALTree** [comment]
Relevant FAQ: [Why does my virus-scanning software think my Go distribution or compiled binary is infected?](https://tip.golang.org/doc/faq#virus)

**Comment by ianlancetaylor** [comment]
In the absence of more information I'm going to close this as a false positive.
