### ISSUE TITLE
How to do IF/ELSE conditions inside LOOP in golang templates?

### ISSUE THREAD

**Issue by vzool** [golang/go#26068]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```shell
go version go1.9.6 darwin/amd64
```

### Does this issue reproduce with the latest release?

I think so

### What operating system and processor architecture are you using (`go env`)?

Mac OS X 10.13.4 on intel

```shell
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vzool/Workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l9/jrf3n4k12rb6kx0_cqs037680000gn/T/go-build243081593=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

I tried to parse this template:

```html
<h1>Country Index</h1>

<style>
.odd{
    background: orange;
    color: black;
    font-size: 1.5em;
}
.even{
    background: rgb(0, 121, 235);
    color: white;
    font-size: 1.5em;
}
</style>

<ul>
    {{ range $i, $x := .Tee }}
        {{ if $i % 2 == 0 }}
            <li class="even">{{ $i }} - {{ $x }}</li>
        {{ else }}
            <li class="odd">{{ $i }} - {{ $x }}</li>
        {{ end }}
    {{ end }}
</ul>
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I'm trying to test a golang to develop a complete WebApp, which is public [here](https://github.com:vzool/go-iris-app).

### What did you expect to see?

I should see `<li>` with different classes `odd`/`even`

### What did you see instead?

**unexpected "%" in operand**

**Comment by ianlancetaylor** [comment]
We don't use the issue tracker for questions about using Go.  For that, please use a forum; see https://golang.org/wiki/Questions .  Thanks.

The template language doesn't support general expressions, because templates are embedded in Go code.  You can use a function.
