### ISSUE TITLE
crypto/x509: macOS -framework Security produces link warning

### ISSUE THREAD

**Issue by rsc** [golang/go#26073]
See https://forums.developer.apple.com/thread/97850 for a bunch of people hitting a new link error in Xcode due to crypto/x509's use of the (apparently now deprecated?) `-framework` linker flag. 

We could just take Merchant.Of.Satire's word for it, but it would be nice to have confirmation that we're not supposed to use `-framework` anymore, as opposed to some Xcode just being buggy/misconfigured/something else.

/cc @robpike who just hit this too.

**Comment by robpike** [comment]
This is what the full build looks like:

```
% ./make.bash
Building Go cmd/dist using /usr/local/go.
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
---
Installed Go for darwin/amd64 in /Users/r/go
Installed commands in /Users/r/go/bin
% 
```

The offending invocation is in src/crypto/x509/root_cgo_darwin.go:

```
/*
#cgo CFLAGS: -mmacosx-version-min=10.10 -D__MAC_OS_X_VERSION_MAX_ALLOWED=101300
#cgo LDFLAGS: -framework CoreFoundation -framework Security

...
```

**Comment by meling** [comment]
FYI: I get this also with Go 1.10.3 and the macOS 10.13.6 (17G65).

```sh
% go version
go version go1.10.3 darwin/amd64
% go build
# github.com/autograde/aguis
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
% uname -a
Darwin blast.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by andybons** [comment]
The `-framework` linker flag isn’t deprecated from what I can tell.

This is due to an out-of-sync Xcode/command line tools installation. You can try updating Xcode (if you’re running an outdated version) and then launch it to install the latest command-line tools.

If you already have the latest Xcode (or the above doesn’t solve your issue), you can re-install the command-line tools forcibly per http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/:

```
$ sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.old
$ xcode-select --install
$ sudo rm -rf /Library/Developer/CommandLineTools.old
```

If this doesn’t work please re-open this bug and I’ll do more investigating.

**Comment by robpike** [comment]
Verified that those instructions resolved it for me.

**Comment by YoshikiShibata** [comment]
This morning, I just upgraded the XCode and Command Line Tools (see the attached screen shot: sorry for Japanese), and then this problem appears again when I run `all.bash` for the tip version to rebuild everything.

<img width="1246" alt="2018-09-18 8 35 08" src="https://user-images.githubusercontent.com/1514700/45656019-1923f500-bb1e-11e8-99b5-0c8d8ab72534.png">

**Comment by hhhizzz** [comment]
update the  Command Line Tools Just now, and similar issue
```
# command-line-arguments
ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Foundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//DiskArbitration.framework/Versions/A/DiskArbitration.tbd and library file /System/Library/Frameworks//DiskArbitration.framework/Versions/A/DiskArbitration are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/Versions/A/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/Versions/A/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//ServiceManagement.framework/Versions/A/ServiceManagement.tbd and library file /System/Library/Frameworks//ServiceManagement.framework/Versions/A/ServiceManagement are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory.tbd and library file /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS.tbd and library file /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS are out of sync. Falling back to library file for linking.
/private/var/folders/x4/qr3r88l91y960q88lyh7vlg80000gn/T/___go_build_main_go #gosetup
```

**Comment by mqy** [comment]
macOS 10.13.6 (17G65)
go version go1.10.4 darwin/amd64
After upgrade command line tools to 10.0, and upgrade xcode to 10.0:

go build a program (with CGO), got errors:

_ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking._

===

Tried fix with xcode-select --install, but the command line tools was installed as version 9.4.
Go build still those errors.  Restart machine does not work.

**Comment by syhlion** [comment]
10.13.6（17G65）
go version go1.11 darwin/amd64

I have the same error
```
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
```

**Comment by agnivade** [comment]
Re-opening as per @andybons' comment 
> If this doesn’t work please re-open this bug and I’ll do more investigating.

**Comment by kaidiren** [comment]
+1 😭

**Comment by monoflash** [comment]
+1

**Comment by agnivade** [comment]
Reminder on our +1 policy https://github.com/golang/go/wiki/NoPlusOne.

**Comment by andybons** [comment]
Can new reporters please confirm that reinstalling the command-line tools via

```
$ sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.old
$ xcode-select --install
$ sudo rm -rf /Library/Developer/CommandLineTools.old
```

Does NOT solve your issue?

One notable thing I do _not_ see in my App Store update list is the command-line tools as a separate item. I updated to Xcode 10.0, launched Xcode, then said yes when it asked to install additional components.

**Comment by calmh** [comment]
It might be OS dependent. My Mojave laptop acted exactly as you described above (Xcode 10, nothing specific about command line tools) and Go works fine there. My High Sierra desktop offers Xcode and a new Command Line Tools. (I've not accepted that upgrade there.)

**Comment by monoflash** [comment]
OS: macOS 10.13.6 (17G65) (High Sierra)
Solution with delete and reinstall CommandLineTools don't work!!!

I has disabled the warnings with environment variables:
```
export CGO_LDFLAGS="-g -O2 -w"
export WARNING_LDFLAGS=-w
export OTHER_LDFLAGS=-w
```

But this is not a solution, it's just postponing the problem "for later"!

**Comment by bahadir60** [comment]
SAME PROBLEM ;

ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are outof sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

**Comment by piisoftware** [comment]
OS: 10.13.6
golang version go1.9.2 darwin/amd64
XCode NOT currently installed, only the command-line tools

I'm seeing the same error; reinstalling command line tools had no effect.

**Comment by dmitshur** [comment]
As another data point, I am not seeing any ld warnings on the following configuration:

OS: macOS 10.13.6
Go version: current tip-1 (c6118af55864916c2c3b1bca8e216e627f232bf3)
Xcode: not installed
Xcode CLI tools: version 9.4.1.0.1.1528165917 (via `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables`)

**Comment by vassudanagunta** [comment]
@andybons confirmed: errors started after System Update updated CommandLineTools this morning and that fix doesn't fix.

**Comment by evelynocean** [comment]
same problem after mac system updated
so, sad......T_____________T
--
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.

**Comment by uppercaveman** [comment]
![image](https://user-images.githubusercontent.com/4667056/45744717-c2a7db00-bc31-11e8-9e72-eeac4ff09e6f.png)
me too

**Comment by lesce** [comment]
Same issue 
go version go1.9.5 darwin/amd64
Mac OS 10.13.6 (17G65)

Also the fix doesn't work .

**Comment by hilben** [comment]
```
ld: warning: text-based stub file 
/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
```
same issue for me
```
go version go1.11 darwin/amd64
Mac OS 10.13.6
```

**Comment by ArtieReus** [comment]
OS: macOS 10.13.6 (High Sierra)
XCode version 10.0
go version go1.11 darwin/amd64

Solution with delete and reinstall CommandLineTools don't work!!!

Any new findings??

**Comment by ArtieReus** [comment]
@Quesomora I tried your solution but didn't work for me. I even tried the version from may but still getting the same warnings.

**Comment by vdemario** [comment]
This started happening for me today. One thing that I haven't seen mentioned by anyone, might be unrelated: I had a prompt a few times when I plugged my iPhone asking to update tools (didn't say what exactly was updated). I'm assuming it's related to the release of iOS 12. I said "not now" a couple of times, but after accepting the linking error appeared.

@andybons @agnivade is there any specific debugging information you'd like us to get to help troubleshooting?

**Comment by slb5427** [comment]
I also tried @Quesomora's solution to no avail, however, I have colleagues that had not upgraded yet and have the version from June 12th, version: 9.4.1.0.1.1528165917, and it works for them.

**Comment by Baha-sk** [comment]
I opened a support ticket at Apple to fix this for future updates yesterday... not sure if/when they will fix it.. it is annoying to having to uninstall then reinstall the CLI tools every time there's a Mac dev tools update just to remove these warnings.

**Comment by kuba--** [comment]
Ultimately, to get rid of those nasty ld warnings I had to apply @Quesomora workaround:
https://github.com/golang/go/issues/26073#issuecomment-422823621
and downgraded CommandLineTools

**Comment by robpike** [comment]
This has indeed returned:

```
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
```

MacOS 10.13.6 after updating command-line tools. Re-install does not fix.

**Comment by andybons** [comment]
Locking due to the number of “me too” comments. https://golang.org/wiki/NoPlusOne

Thanks everyone. We’re aware this is an issue and are actively investigating.

The warnings are benign. They should not affect your day-to-day development work.

**Comment by andybons** [comment]
Developers of vim are also experiencing the same issue. Cross-linking for posterity.

https://github.com/vim/vim/issues/3445

**Comment by dmitshur** [comment]
Upgrading to macOS Mojave, which came out today, seems to fix the issue for me. I can no longer reproduce it on the following configuration:

**OS:** macOS Mojave, version 10.14 (18A391)
**Go versions:** current tip at 2018-09-25 01:17 (0ee8a559e5778b4dbfa20c524867112693ba607f), tip at 2018-09-18 21:34 (d24ec86e4f64302e91d8062eabfcd21296bb9b04)
**Xcode:** version 10.0 (10A255) (installed, but haven't done the "install additional required components" yet; version via `xcodebuild -version`)
**Xcode CLI tools:** seemingly no longer installed, getting `No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.`, although `git` and others are available in CLI (via `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables`)

However, it's not conclusive if the issue is completely resolved, because it seems upgrading to Mojave caused the Xcode CLI tools to no longer be installed by default, and running Xcode 10 asks to "install additional required components" again. I haven't done those steps yet.

Unlocking for now, but please keep https://github.com/golang/go/wiki/NoPlusOne in mind. Posting new comments is okay if there's new helpful information that hasn't been covered before; otherwise please use 👍 reactions.

Specifically, it'd be helpful to know if anyone can still reproduce this on macOS Mojave. If so, please include your exact configuration (macOS version/build number, Go version, Xcode version, Xcode CLI version, whether or not you've run Xcode and done the "install additional required components" step).

**Comment by zdebra** [comment]
I've just upgraded to macos Mojave and the issue remains.

**OS**: macOS Mojave, version 10.14 
**Go**: go1.11 darwin/amd64

I don't have Xcode installed, only Xcode CLI tools. I've tried to reinstall Xcode CLI tools with no success.

**Comment by dmitshur** [comment]
@zdebra Thanks. What version of Xcode CLI tools? You should be able to find out by running `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables` or so.

**Comment by zdebra** [comment]
@dmitshur 
```
package-id: com.apple.pkg.CLTools_Executables
version: 10.0.0.0.1.1535735448
volume: /
location: /
install-time: 1537947903
groups: com.apple.FindSystemFiles.pkg-group
```

**Comment by geomacy** [comment]
@Quesomora's solution works for me (thanks! the linker errors break `godog`, so this is a great help)

OSX 10.13.6
go version go1.10.4 darwin/amd64 (but the problem occurs for go 1.11 as well).

xcode command line utils before applying Quesomora's suggestion, problem exists:
```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 10.0.0.0.1.1535735448
```
xcode command line tools after applying the suggestion, problem gone:
```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.4.1.0.1.1528165917
```
Unfortunately I guess this is going to mean turning off auto-update on packages, until Apple fix this.

**Comment by vassudanagunta** [comment]
Confirmed @Quesomora's solution, exactly same environment and before/after as @geomacy with the excepton of `go version go1.11 darwin/amd64`.

**Comment by hilben** [comment]
@Quesomora solution was not working for me until I downgraded go 1.11 to go 1.9.2 (i did not try 1.10)
Currently running with:
```
go version 
go1.9.2 darwin/amd64
```

```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.4.0.0.1.1526532315
volume: /
location: /
install-time: 1538486245
groups: com.apple.FindSystemFiles.pkg-group
```
```
macOS 10.13.6
```

**Comment by requaos** [comment]
I am working in a cgo project, using `goconvey` regularly during development, and `goconvey` interprets the ld errors as build failure indications.
```
macOS 10.13.6
```
```
go version
go version go1.11 darwin/amd64
```
```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 10.0.0.0.1.1535735448
volume: /
location: /
install-time: 1538487003
groups: com.apple.FindSystemFiles.pkg-group 
```

**Comment by vassudanagunta** [comment]
@requaos you have `version: 10.0.0.0.1.1535735448` which if you search the comments above all point to it being a/the problematic version. Have you tried @Quesomora solution getting you to `version: 9.4.1.0.1.1528165917`? That seems to solve it for everyone that reported that version, including me.

**Comment by geomacy** [comment]
hi @Baha-sk,  regarding
> I opened a support ticket at Apple to fix this for future updates yesterday... not sure if/when they will fix it.. it is annoying to having to uninstall then reinstall the CLI tools every time there's a Mac dev tools update just to remove these warnings.

could you post a link to the ticket here so we could keep an eye on whether there appears to be any action on fixing this?

**Comment by xackery** [comment]
followed @Quesomora 's fix but still getting the warning.
```
$  pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.4.1.0.1.1528165917
volume: /
location: /
install-time: 1538424576
groups: com.apple.FindSystemFiles.pkg-group
```
9.4.1 seems to be applied, too.. Hmm.

**Comment by gabolaev** [comment]
This issue is no longer detected on my machine after updating to macOS 10.14 Mojave

``` bash
❯ xcodebuild -version
Xcode 10.0
Build version 10A255

❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391

❯ go version
go version go1.9.7 darwin/amd64
```

**Comment by kevinburke** [comment]
@gabolaev I don't think that the issue reproduces with go 1.9 under any hardware configuration - it's Go 1.10 and above.

**Comment by gazed** [comment]
Deleting the Xcode, the Xcode command line tools, and then **reinstalling macOS 10.14 from macOS Recovery** fixed the link warning problem for me. A bit drastic - but does this fix it for anyone else? Reinstalled the latest Xcode and Xcode command line tools after the OS reinstall. 

Note: I had also reinstalled go version go1.11.1 darwin/amd64 after trying go1.9 and go.10. Also used `go clean -cache`.

Historical Note: the link warning issue started happening for my go projects after updating to macOS 10.14. Various combinations of reinstalling Xcode command line tools and Xcode did not fix the issue.
At one point the link warnings were happening even when using clang command line to compile a c-test program that used frameworks (no go involved).

**Comment by ParityError** [comment]
> @requaos you have `version: 10.0.0.0.1.1535735448` which if you search the comments above all point to it being a/the problematic version. Have you tried @Quesomora solution getting you to `version: 9.4.1.0.1.1528165917`? That seems to solve it for everyone that reported that version, including me.

Nope, I don't think that is the issue because I have the exact same issue and this is my version:
```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 8.2.0.0.1.1480973914
volume: /
location: /
install-time: 1539050324
groups: com.apple.FindSystemFiles.pkg-group 

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

$ xcodebuild -version
Xcode 10.0
Build version 10A255

$ go version
go version go1.9.1 darwin/amd64
```

This problem has nothing to do with `go` either...

**Comment by gabolaev** [comment]
@kevinburke, i had that issue on the same go version (1.9.7) on High Sierra. it's gone just after system update.

**Comment by requaos** [comment]
After upgrade to Mojave and update of command line tools, linker warning is
gone for me.

**Comment by andybons** [comment]
Thanks everyone. We've filed a Radar (bug) with Apple and are awaiting their response.

This is not a Go-specific issue and is not dependent on the version of Go installed. We've provided the following reproduction steps to Apple:

```
Steps to Reproduce:
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
version: 10.0.0.0.1.1535735448
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ cat > issue.c 
int main() { return 0; }
^D
$ clang issue.c -framework CoreFoundation
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
```

Locking for now while we wait for Apple's response. Thanks again, everyone.

**Comment by rsc** [comment]
I sent a CL to filter out the warning in our tools. There's no point in continuing to have people hit what looks like a real problem when we know it's a harmless bug on Apple's end. We should probably have done this months ago, and probably the CL should be backported to Go 1.11.
