### ISSUE TITLE
No pkg installed

### ISSUE THREAD

**Issue by TaurusD** [golang/go#26079]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\p4446\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\XXXXX\Documents\go-work
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\XXXXX\AppData\Local\Temp\go-build121904390=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I followed the tutorial on https://golang.org/doc/code.html till the section **Your First Library**. 

### What did you expect to see?
When I run command **go install github.com/user/hello**, it's expected to install **hello.exe** in folder **bin** and pakage **stringutil.a** in folder **pkg**.

### What did you see instead?
I got only hello.exe in bin, but nothing in pkg.

**Comment by myitcv** [comment]
Thank you - this is indeed an error in the example at https://golang.org/doc/code.html

This behaviour changed in Go 1.10: https://golang.org/doc/go1.10#build

> The go install command now installs only the packages and commands listed directly on the command line. For example, go install cmd/gofmt installs the gofmt program but not any of the packages on which it depends. 

You can safely ignore the fact that `stringutil.a` is not in the `pkg` directory structure. To all intents and purposes it doesn't make any difference.

**Comment by myitcv** [comment]
Thanks @agnivade
