### ISSUE TITLE
Struct corrupted on windows while assigning struct field value

### ISSUE THREAD

**Issue by thetraveller** [golang/go#26086]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### windows:
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\<winuser>\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go\go-work
set GORACE=
set GOROOT=C:\go\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\<winuser>\AppData\Local\Temp\go-build401129270=/tmp/go-build -gno-record-gcc-switches

### Linux:
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/<linuxuser>/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/<linuxuser>/bin/go/libs"
GORACE=""
GOROOT="/home/<linuxuser>/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/<linuxuser>/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build638555522=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
https://play.golang.org/p/bBvLG8_PiGS
inputs:
testid
testname

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
{testid testname}

### windows:
}testname

### linux:
{testid testname}

**Comment by bcmills** [comment]
A `bufio.Reader` can read and buffer an arbitrary amount of data. When you call `read_string` twice, you construct two `bufio.Reader` instances, which means that you may lose some amount of data from `stdin` after the first read.

My guess is that the data you're losing is one of the two characters from the `\r\n` pair, leading to unexpected output when it is echoed to the terminal.

Can you reproduce this issue without using `bufio`, or using a single (global) `bufio.Reader` instead of one per call?

**Comment by forskning** [comment]
Windows XP Home SP3 (32-bit)

go 10.2

it occurs running go.exe from the Windows console

http://nurmi-labs.blogspot.com/2016/11/git.html

running in C Shell

% mintty.exe --version
mintty 2.4.2 (i686-pc-msys)
(C) 2013/2016 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.

% ./test.exe
testid
testname
{testid testname}
% exit

https://9p.io/magic/webls?dir=/sources/extra
9pm051031.zip

running in 9term (a dumb terminal)

% ./test.exe
testid
testname
{testid testname}
% exit
