### ISSUE TITLE
x/errgroup: does not respect a context with any sort of timeout on it

### ISSUE THREAD

**Issue by zachgersh** [golang/go#26099]
I had assumed that a context with a timeout provided to `errgroup` would have canceled the whole group when the timeout had elapsed but having a look at the code, there is no logic for it to do that:

https://github.com/golang/sync/blob/master/errgroup/errgroup.go

**Comment by zachgersh** [comment]
I'd be happy to PR this in.

**Comment by ianlancetaylor** [comment]
When using an `Errgroup` the functions are pretty much assumed to return when the context is canceled, so they will return when the context times out.  I don't see that anything special has to be done.

**Comment by dsymonds** [comment]
Yep, I'm pretty sure `errgroup` is fine here. If you're observing otherwise in your use case, most likely one of your `Go` funcs is not correctly respecting the context.

**Comment by fraenkel** [comment]
@zachgersh As far as the errgroup is concerned, you are correct, it will only care if an error appears. But if you have provided a WithDeadline or WithTimeout context as its parent, then the context code will handle the cancellation of the children.

**Comment by zachgersh** [comment]
@fraenkel - thanks! That is what I am passing. Feel like I should write a test for this. It hangs indefinitely due to the implementation right now.

**Comment by bcmills** [comment]
A concrete example of what you're trying to do would be helpful. If the functions you pass to `(*errgroup).Go` may block, they are expected to close over the relevant `context.Context` variable and use it to remain responsive to timeouts and cancellation.

`errgroup` doesn't do anything special to the goroutines themselves: it only manipulates the `Context` and waits for them to notice, same as any other API using the `context` package.

**Comment by dsymonds** [comment]
This sounds like errgroup is not at fault here, and there's just some difficulty using it. GitHub issues aren't really for support requests; follow-up can go to the golang-nuts mailing list.
