### ISSUE TITLE
cmd/compile: OpAMD64CMOV*EQF clobbers AX, doesn't tell regalloc

### ISSUE THREAD

**Issue by heschik** [golang/go#26097]
CL 98695 (commit 080187f4f72bd6594e3c2efc35cf51bf61378552) adds OpAMD64CMOV{Q,L,W}EQF. The generated assembly looks like: https://github.com/golang/go/blob/d144dd785f06300492754d49fb353ab9d5068919/src/cmd/compile/internal/amd64/ssa.go#L461-L463
That is, it uses AX as a scratch register so that it can check both equality and NAN-ness. (I think.) The problem is, regalloc doesn't know about this:
https://github.com/golang/go/blob/d144dd785f06300492754d49fb353ab9d5068919/src/cmd/compile/internal/ssa/gen/AMD64Ops.go#L400
`gp21` doesn't have `clobbers:ax`.

I don't have a public repro, but given the below assembly I'm pretty sure I'm in the neighborhood of the problem. The three MOVLs clearly don't make sense.

```
 v677  	00341 (287)	UCOMISD	X1, X0
 v292  	00342 (287)	MOVL	$2, AX
 v287  	00343 (287)	MOVL	$1, CX
 v456  	00344 (287)	MOVL	CX, AX
 v456  	00345 (287)	CMOVLNE	AX, AX
 v456  	00346 (287)	CMOVLPC	AX, AX
 v460  	00347 (287)	MOVL	AX, "".~r2+24(SP)
 b196  	00348 (35)	RET
```

cc @randall77 @TocarIP @rasky

This is Google-internal b/110810807.

**Comment by TocarIP** [comment]
Looks like we clobber AX for "ssa.OpAMD64CMOVQEQF, ssa.OpAMD64CMOVLEQF, ssa.OpAMD64CMOVWEQF", but only CMOVQEQF uses gp21pax regspec (which marks ax as clobbered)

**Comment by TocarIP** [comment]
Here is simple reporducer:
```
package main

//go:noinline
func foo1(v1, v2 int64, x1, x2 float64) int64 {
        r := v1
        if x1 == x2 {
                r = v2
        }
        return r
}

//go:noinline
func foo3(v1, v2 int16, x1, x2 float64) int16 {
        r := v1
        if x1 == x2 {
                r = v2
        }
        return r
}

//go:noinline
func foo2(v1, v2 int32, x1, x2 float64) int32 {
        r := v1
        if x1 == x2 {
                r = v2
        }
        return r
}

func main() {
//should print 1 1 1
        println(foo1(1, 2, 4.0, 5.0))
        println(foo2(1, 2, 4.0, 5.0))
        println(foo3(1, 2, 4.0, 5.0))
// prints 1 2 2
}
```
