### ISSUE TITLE
cmd/go: errors appear multiple times

### ISSUE THREAD

**Issue by robpike** [golang/go#26100]
Related to but distinct from https://github.com/golang/go/issues/24278

If there is a syntax or type error in a test, running `go test` causes each error to be reported multiple times, once by vet and once by either go test's internals or the compiler, depending on the particular error.

The go command should sequester errors from vet until the other process completes, and drop them on the floor if the main process generates an error. Or to put it another way, errors from vet should appear only if compilation of the test is otherwise successful.

**Comment by bcmills** [comment]
Same root cause as https://github.com/golang/go/issues/26102?

**Comment by bcmills** [comment]
Looks like #26102 is related but separate.

**Comment by bcmills** [comment]
(CC: @mvdan @rsc )

**Comment by bcmills** [comment]
Is this behavior present in 1.10, or is this a regression in 1.11?

**Comment by mvdan** [comment]
#26102 is unrelated, I'm afraid. That one is simply a vet bug.

The reason this issue is different from #24278 is explained by a comment of mine there:

> Actually, I was wrong - my particular case had nothing to do with vet. My problem was coming from `go test` using `go/parser` directly in `loadTestFuncs`. Skipping this error is a bit tricky, since this happens much earlier than the build action. I'm no longer sure that a change in test is the right fix.

That also explains why, in this case, errors appear multiple times.

> Is this behavior present in 1.10, or is this a regression in 1.11?

If the error is a type-check error, this is probably a regression in 1.11. @robpike do you have a working example we can test with?

**Comment by dsymonds** [comment]
@bcmills: I observed this the other day in my own work. It's a regression since Go 1.10.

**Comment by robpike** [comment]
Duplicate of #26125
