### ISSUE TITLE
doc: vet check included in gc needs to be documented

### ISSUE THREAD

**Issue by hyangah** [golang/go#26109]
vet check seems to be included in gc by default but not documented in go1.11 release note yet (sorry, I didn't search enough to find related issue/proposal/change to link yet).

This behavior change resulted in build-failures for codes that don't pass vet currently and could be misunderstood as a regression in go1.11. For example, with go1.11 (or tip), go test on 
github.com/spf13/cobra will fail due to failure to pass vet check.

<pre>
$ go version
go version devel +257d6c48e0 Thu Jun 28 03:12:01 2018 +0000 linux/amd64

$  go test github.com/spf13/cobra
# github.com/spf13/cobra
../github.com/spf13/cobra/command_test.go:1105:3: parentPersPreArgs declared but not used
../github.com/spf13/cobra/command_test.go:1109:3: parentPersPostArgs declared but not used
vet: typecheck failures
FAIL	github.com/spf13/cobra [build failed]
</pre>

BTW, the vet error message is confusing because the parentPersPreArgs and parentPersPostArgs in the test are 'used' (literally). But for the purpose of vet check, the vars are 'not used' because they are never read.

**Comment by ALTree** [comment]
That's not a vet error message. That file is failing the type-checking phase that precedes the vet checks.

The reason the file fails typecheking is that this:

```
var parentPersPreArgs string

PersistentPreRun: func(_ *Command, args []string) {
    parentPersPreArgs = strings.Join(args, " ")
},
```

doesn't count as using the `parentPersPreArgs` variable. The program should *not* compile, but it does because of #3059. But go/types, which is used by vet to type-check, correctly marks the variable as unused.

**Comment by ALTree** [comment]
Root cause is the decision taken on #21287 (cmd/vet: decide how to handle type checking failure). I quote:

> So the decision here is "go vet" will be fixed so that it can always typecheck, and then failure to typecheck will be a fatal error. 

This happened in go1.10, but AFAIK it wasn't documented in the release notes. I don't see it here:

https://golang.org/doc/go1.10#vet

 We could document this in the 1.11 release notes(?)

**Comment by hyangah** [comment]
Is the error message misleading?
<pre>
vet: typecheck failures
</pre>
anyway, regardless of where the origin of this change is, the changed behavior should be documented clearly.

**Comment by ALTree** [comment]
Ah, my bad. This is false:

> vet typechecks since 1.10

it was put it, disabled to fix a go/types issue, and the re-enabled again during the 1.11 cycle, here:

https://go-review.googlesource.com/c/go/+/108555

So it should be documented.

**Comment by therealplato** [comment]
Sorry, I'm experiencing this error and I'd like to know what I'm supposed to be doing instead of 
```
var parentPersPreArgs string

PersistentPreRun: func(_ *Command, args []string) {
    parentPersPreArgs = strings.Join(args, " ")
},
```

Why is this considered a failure?

**Comment by ALTree** [comment]
> Sorry, I'm experiencing this error

Where? When?

>  I'd like to know what I'm supposed to be doing

Use the `parentPersPreArgs` variable in some way, or remove it from the code.

 > Why is this considered a failure?

Because unused variables are not allowed in Go (at least in `gc` and in `go/types`), and `parentPersPreArgs` is an unused variable.

**Comment by therealplato** [comment]
@ALTree I'm experiencing it with the same closure usecase as you posted. By my reading, `parentPersPreArgs` is "used" when strings.Join assigns its result to it. I don't understand what makes it "unused."

**Comment by dominikh** [comment]
A value that is only ever written to but never read from is effectively unused. go/types (which vet uses) is more strict about this than the compiler.
