### ISSUE TITLE
strings

### ISSUE THREAD

**Issue by llonchj** [golang/go#26119]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/llonchj/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/llonchj/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x4/s1l6gz3x7b5fqvbnbfj80zn40000gn/T/go-build203784472=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

https://play.golang.org/p/MBSt8AIRWri

### What did you expect to see?

www.example
www.example
www.example

### What did you see instead?

www.example
www.exampl
www.example

**Comment by ianlancetaylor** [comment]
`strings.TrimRight` and `strings.TrimSuffix` are not the same function.  This is working as documented.

If you have questions about Go please consider using a forum; see https://golang.org/wiki/Questions .
