### ISSUE TITLE
x/build/devapp: duplicate CL lines on /release page

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26113]
I just noticed duplicate lines for an open CL:

![dup](https://user-images.githubusercontent.com/2621/42057273-aeaef788-7ad1-11e8-9fda-bf5259305475.png)

**Comment by dmitshur** [comment]
This seems to happen when the CL description mentions the same issue more than once. For example, here's a current occurrence of this bug:

![image](https://user-images.githubusercontent.com/1924134/43728804-30506752-9974-11e8-883c-59d40f83beaa.png)

Here's the commit message of [CL 26650](https://golang.org/cl/26650) mentioning that issue twice:

![image](https://user-images.githubusercontent.com/1924134/43728882-6f80d1fa-9974-11e8-9cd7-56f3d737ef06.png)

Seems like a straightforward thing to fix; I'll use it as a warm up.

**Comment by dmitshur** [comment]
[`maintner.GerritCL`](https://godoc.org/golang.org/x/build/maintner#GerritCL) has a field `GitHubIssueRefs` of type `[]GitHubIssueRef`. Currently, if the CL description mentions the same issue more than once, there will be multiple identical `GitHubIssueRef` entries in that slice. E.g.:

```Go
corpus, err := godata.Get(context.Background())
if err != nil {
	return err
}
proj := corpus.Gerrit().Project("go.googlesource.com", "sys")
cl := proj.CL(26650)
for _, ref := range cl.GitHubIssueRefs {
	fmt.Println(ref.Repo.ID(), ref.Number)
}

// Output:
// golang/go 14873
// golang/go 14873
```

While it's possible to deduplicate these lines in devapp-only, I suspect a better fix is to deduplicate them in `maintner`.

(At least at this time, `GitHubIssueRef` doesn't track anything other than repo and issue number, so multiple entries carry very little information. If we ever want to change that to also have a "character position" or something to make multiple entries non-unique, then we can stop deduplicating.)

**Comment by dmitshur** [comment]
I've deployed the new version and confirmed that the bug is fixed in production.

### Before

![image](https://user-images.githubusercontent.com/1924134/43805898-79d952de-9a6f-11e8-8b10-b77b258c573c.png)

### After

![image](https://user-images.githubusercontent.com/1924134/43805919-9ed6e5ba-9a6f-11e8-8bc2-8704b8a55e93.png)
