### ISSUE TITLE
cmd/go: simplify scheme lookup in internal/get/vcs.go

### ISSUE THREAD

**Issue by rsc** [golang/go#26123]
After CL 120998 is merged into the main tree, the vcs ping code will look like:

		if srv.ping {
			if scheme != "" {
				match["repo"] = scheme + "://" + match["repo"]
			} else {
				for _, scheme := range vcs.scheme {
					if security == web.Secure && !vcs.isSecureScheme(scheme) {
						continue
					}
					if vcs.pingCmd != "" && vcs.ping(scheme, match["repo"]) == nil {
						match["repo"] = scheme + "://" + match["repo"]
						goto Found
					}
				}
				// No scheme found. Fall back to the first one.
				match["repo"] = vcs.scheme[0] + "://" + match["repo"]
			Found:
			}
		}

I believe it can be simplified to:

		if srv.ping {
			scheme = vcs.scheme[0] // default to first scheme
			if vcs.pingCmd != "" {
				// If we know how to test schemes, scan to find one.
				for _, scm := range vcs.scheme {
				if security == web.Secure && !vcs.isSecureScheme(scm) {
					continue
				}
				if vcs.ping(scheme, match["repo"]) == nil {
					scheme = scm
					break
				}
			}
			match["repo"] = scheme + "://" + match["repo"]
		}

but I don't want to do that this late in the cycle. We should try the rewrite when the Go 1.12 cycle opens.

**Comment by bcmills** [comment]
This fell off my radar. Will put it on my list for early in 1.13.

**Comment by bcmills** [comment]
> Will put it on my list for early in 1.13.

[One release later...]

Fixed!
