### ISSUE TITLE
net/http: misleading description of Transport.DisableKeepAlives field

### ISSUE THREAD

**Issue by juhwany** [golang/go#26128]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/hanmail/gospace"
GORACE=""
GOROOT="/data1/hanadmin/go"
GOTOOLDIR="/data1/hanadmin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build037036632=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
http.Transport struct has DisableKeepAlives field and its description says it's related to TCP connection re-use like TCP Keep-alive.
```
type Transport struct {
...
	// DisableKeepAlives, if true, prevents re-use of TCP connections
	// between different HTTP requests.
	DisableKeepAlives bool
}
```

But  it's actually related to HTTP Keep-alive not TCP Keep-alive. I've found that if it is set to true, then HTTP request header will have "Connection:Close". 

net/http/transport.go around 1997 line.
```
...
	if pc.t.DisableKeepAlives {
		req.extraHeaders().Set("Connection", "close")
	}
...
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
The description about DisableKeepAlive field should be modified. It could make misunderstanding.

**Comment by ianlancetaylor** [comment]
CC @bradfitz

**Comment by bradfitz** [comment]
There are two types of keep-alives: HTTP keep-alives and TCP keep-alives. HTTP almost always runs on top of TCP, so it's not inaccurate to use "TCP" in the description of HTTP keep-alives. The docs you cite never said "TCP keep-alives". It says:

> prevents re-use of TCP connections

I really don't think there's any problem here, but I'll add a sentence.
