### ISSUE TITLE
net/url: Improve documentation for PathUnescape

### ISSUE THREAD

**Issue by tooolbox** [golang/go#26139]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.2

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
Looked at the godoc for [PathUnescape](https://golang.org/pkg/net/url/#PathUnescape)

### What did you expect to see?
> PathUnescape does the inverse transformation of PathEscape, converting each 3-byte encoded substring of the form "%AB" into the hex-decoded byte 0xAB. It returns an error if any % is not followed by two hexadecimal digits.
>
> PathUnescape is identical to QueryUnescape except that it does not unescape '+' to ' ' (space).

### What did you see instead?
> PathUnescape does the inverse transformation of PathEscape, converting each 3-byte encoded substring of the form "%AB" into the hex-decoded byte 0xAB. It also converts '+' into ' ' (space). It returns an error if any % is not followed by two hexadecimal digits.
>
> PathUnescape is identical to QueryUnescape except that it does not unescape '+' to ' ' (space).

### Commentary
It seems like the documentation for [PathUnescape](https://golang.org/pkg/net/url/#PathUnescape) was copied from [QueryUnescape](https://golang.org/pkg/net/url/#QueryUnescape), with the last line added.  However, it then contradicts itself about its behavior with `+` characters.

### Fix
Remove the line `It also converts '+' into ' ' (space).` from the PathUnescape comment.  I would submit a PR but the amount of hoops I'd have to jump through to contribute one line of code is a little much; I'd like to ask that someone who's already set up as Go contributor take care of this.

Thanks!

**Comment by ianlancetaylor** [comment]
@tooolbox In case you didn't know, we do accept Github pull requests now.

**Comment by conspicuousClockwork** [comment]
I shamelessly made the fix myself and opened a pull request. @tooolbox I'll close it myself if you would like to take credit for commit!

**Comment by tooolbox** [comment]
@ianlancetaylor Ah, good to know.

@conspicuousClockwork Ouch, wouldn't have minded.  I guess I got what I asked for in the first place ;)
