### ISSUE TITLE
x/vgo: failed to recognize formbuilder package in imported package list of context package in iris framework

### ISSUE THREAD

**Issue by MartinForReal** [golang/go#26130]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes
### What operating system and processor architecture are you using (`go env`)?

```shell
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shangxiangfan/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shangxiangfan/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lv/3tmd050s3h789cbwkgbp9ty40000gn/T/go-build648348552=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

``` go
package main

import "gopkg.in/kataras/iris.v6"

func main() {
	_ = iris.Framework{}
}
```

```shell
vgo build -v 
```

### What did you expect to see?
no error should be reported.

### What did you see instead?

```shell
# gopkg.in/kataras/iris.v6
../../../mod/gopkg.in/kataras/iris.v6@v6.0.0-20170518015654-76696083c385/context.go:23:2: imported and not used: "github.com/iris-contrib/formBinder" as formbinder
../../../mod/gopkg.in/kataras/iris.v6@v6.0.0-20170518015654-76696083c385/context.go:731:26: undefined: formBinder
```

**Comment by bcmills** [comment]
The only tag for `github.com/iris-contrib/formBinder` is `v4` and the only branch is `4.0.0`, neither of which is a valid semantic version (in the sense defined by https://semver.org/).

Instead, `vgo` gives you the most recent commit for the master branch (ad9fb86), at which the package is declared as `package formbinder`. (It was renamed in commit ed52a69.)

This is a great example of why we need versioning support in Go, but I think `vgo` is working as expected here.
