### ISSUE TITLE
x/build: test sub-repositories (golang.org/x/...) on s390x

### ISSUE THREAD

**Issue by mundaym** [golang/go#26131]
We currently have a spare s390x build machine which is idle (though it doesn't have much disk space so I might need to get that increased). I was thinking it might be a good idea to use it to run the sub-repo tests. They are currently only run on x86 AFAICT.

I'm happy to get it set up. Are there any major roadblocks?

/cc @bradfitz

**Comment by bradfitz** [comment]
Hm, we certainly used to run subrepo tests on ppc, mips, arm, etc. There's nothing x86-specific about the setup.

We might've disabled some during server availability issues (non-x86 are often in short supply) and maybe I forgot to re-enable them. I'll double check.
