### ISSUE TITLE
x/build/cmd/gomote: improve edit/push/test cycle

### ISSUE THREAD

**Issue by aclements** [golang/go#26137]
When using a gomote, I often want a tight edit/push/test cycle, but the current behavior of `gomote push` makes this difficult. Specifically, because `gomote push` deletes all files from the remote tree that aren't in the local tree, I have to re-run a full `make.bash` every time I edit something and push, rather than just re-running the one test I care about. In general, deleting these files is clearly the right behavior, so I'm not sure what the answer is. Perhaps it shouldn't delete the build-generated files, such as `go/src/runtime/internal/sys/zversion.go` and maybe `go/src/cmd/cgo/zdefaultcc.go` and `go/src/go/build/zcgo.go`. Or perhaps we need to tweak the build process to be more friendly to cleaning the tree. The `VERSION` file may also be involved.

/cc @bradfitz

**Comment by bradfitz** [comment]
It used to ignore certain files to enable such a fast cycle. (that's how I used it) but I never updated it after the build cache changes. Should be an easy fix. Will do.

**Comment by ianlancetaylor** [comment]
I always just run

```
gomote push TARGET
gomote run TARGET go/bin/go test package
```

and that works fine for me.  What doesn't work for you?  Is it possible that you need to sync your gomote sources past https://golang.org/cl/53070?

**Comment by aclements** [comment]
You're quite right, Ian. I updated my gomote and this appears to work fine now. Sorry for the noise!
