### ISSUE TITLE
x/review/git-codereview: add a flag to mail CLs with hashtags

### ISSUE THREAD

**Issue by mvdan** [golang/go#26149]
For example, when mailing changes during a freeze, it can be useful to add the `wait-release` hashtag. It would be helpful to be able to do:

    git-codereview -hashtag wait-release

To be consistent with other flags like `-r`, it should take a comma-separated list of strings.

The field can be passed onto Gerrit in a similar way to how the topic is passed: https://gerrit-review.googlesource.com/Documentation/user-upload.html#hashtag

Seems like a simple enough change, if someone wants to give it a go.

**Comment by jespino** [comment]
I would like to give it a try. :)
