### ISSUE TITLE
runtime: next release of OpenBSD requires MAP_STACK for stacks

### ISSUE THREAD

**Issue by aclements** [golang/go#26142]
As announced in http://openbsd-archive.7691.n7.nabble.com/stack-register-checking-td338238.html, the upcoming release of OpenBSD is going to start requiring that the SP points to memory that was mapped with `MAP_STACK` on system call entry, traps, and when switching to the alternate signal stack. This breaks with the current version of Go because we don't map any memory `MAP_STACK`.

Fixing this is somewhat tricky given how tightly we allocate stacks and that they are interwoven with heap memory. However, they're not interwoven below page granularity, so it should be possible to fix this by remapping memory whenever a span transitions to or from being used to allocate stacks.

**Comment by 4a6f656c** [comment]
Unfortunately this is not quite fixed - it still fails on OpenBSD -current (what will become 6.4) as soon as a new thread is created:

```
$ ./all.bash
Building Go cmd/dist using /home/joel/src/go1.4.
Building Go toolchain1 using /home/joel/src/go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
go tool dist: FAILED: /home/joel/src/go/pkg/tool/openbsd_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -a -i cmd/asm cmd/cgo cmd/compile cmd/link: signal: segmentation fault (core dumped)
```

I'll send a change to fix this.
