### ISSUE TITLE
strings: TestCompareStrings times out on the linux-arm* builders

### ISSUE THREAD

**Issue by mundaym** [golang/go#26155]
This test was extended in [CL 121495](https://go-review.googlesource.com/c/go/+/121495) and is now timing out on the linux-arm* builders. We could avoid running the longer test on the arm builder or we could look into optimizing the test a bit (it currently does quite a bit of repeated work).

/cc @bradfitz @billotosyr

**Comment by mvdan** [comment]
Perhaps a simpler short-term solution is to skip it in short mode.

**Comment by ianlancetaylor** [comment]
@mvdan The longer parts of the tests are currently skipped in short mode, but not on the builders.

**Comment by ianlancetaylor** [comment]
On my laptop the test does 23581 garbage collections.

**Comment by aclements** [comment]
This also is probably causing timeouts on openbsd-amd64-62.

**Comment by ianlancetaylor** [comment]
The test should now pass, so removing the release-blocker label and changing this into an investigation of why the test is so much slower on ARM than on amd64.

**Comment by millerresearch** [comment]
FYI, before the CL, the test was timing out on plan9_arm too.
