### ISSUE TITLE
x/vgo: vgo mod -verify fails because it checks non-existent cache directory

### ISSUE THREAD

**Issue by jaloren** [golang/go#26151]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
Yes, I built from source today.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/Volumes/Repositories/go/bin"
GOCACHE="/Users/jlorenzini/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/Repositories/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/7ndx_j6s36x9hm9dns67j21s3hynqn/T/go-build961467438=/tmp/go-build -gno-record-gcc-switches -fno-common"
VGOMODROOT="/Users/jlorenzini/repos/operator"
```

### What did you do?

vgo build $PKG_NAME
vgo mod -verify

### What did you expect to see?
The verify operation should succeed.

### What did you see instead?
The verify operation fails with the error. 

```
gopkg.in/yaml.v2 v2.2.1: missing ziphash: open /Volumes/Repositories/go/src/mod/cache/gopkg.in/yaml.v2/@v/v2.2.1.ziphash: no such file or directory
```
The issue is that source cache is stored in a downloads directory. So for example this directory does exist.

/Volumes/Repositories/go/src/mod/cache/download/gopkg.in/yaml.v2/@v/v2.2.1.ziphash

**Comment by bcmills** [comment]
Should be fixed by https://golang.org/cl/121659.

Please reopen if you can still reproduce this problem with a `vgo` built from commit 0e237a44ca5947b2341c0bf9d0b515f80808a832 or later.

**Comment by jaloren** [comment]
@bcmills i am seeing this issue even after that commit. I am on commit:

47daa39e820cb74d4206b6cd6c3a8f97a2f86086

**Comment by jaloren** [comment]
@bcmills I don't see a way to reopen the issue.
