### ISSUE TITLE
cmd/compile: "add some generic composite type optimizations" improperly discards writes to non-autos

### ISSUE THREAD

**Issue by heschik** [golang/go#26153]
[CL 106495](https://golang.org/cl/106495) (commit f31a18ded405bdbc7b44a011d1434c83e7c39347) adds a pass, "dead auto elim", that eliminates local variables that are only written, not read. Under certain circumstances, it can discard writes to non-autos. In this example:

```
package main

import "fmt"

func main() {
	var s string
	mangle(&s)
	fmt.Println(s)
}

//go:noinline
func mangle(ps *string) {
	if ps == nil {
		var s string
		ps = &s
	}
	*ps = "hello world"
}
```

The write on the last line to *ps will be discarded. I think the problem is that `elimDeadAutosGeneric` totally ignores non-autos, even when their existence is important. The phi op that unifies `ps` after the if takes two values, essentially `&s` and `ps`. Because the function doesn't care about non-autos, it ignores `ps`, and considers the phi to be dead if `s` is dead, which of course it is. Really the whole thing should be kept alive by the (potential) write through `ps`.

cc @randall77, @TocarIP, @mundaym

**Comment by mundaym** [comment]
Thanks for the bug report @heschik. I think [CL 121796](https://golang.org/cl/121796) should be enough to fix the problem.
