### ISSUE TITLE
os/signal: Ignore() causes `waitpid: no child process` error in *exec.Cmd's Wait().

### ISSUE THREAD

**Issue by yadkit** [golang/go#26172]
### What version of Go are you using (`go version`)?

> go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?
> No

### What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build367713696=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

The program works as expected and all I/O is well for out, err and in. However, `Wait()` returns an unexpected error.

https://play.golang.org/p/jyemjCDTFyQ

	package main

	import (
		"os"
		"os/exec"
		"os/signal"
	)

	func main() {
		signal.Ignore()

		cmd := exec.Command("uptime")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr

		if err := cmd.Start(); err != nil {
			panic(err)
		}

		if err := cmd.Wait(); err != nil {
			panic(err)
		}
	}

As far as I know, os/signal package is only supposed to deal with the incoming signals to the program itself. So why does it affect the progress of an externally executed program?

### What did you expect to see?
No errors returned by `cmd.Wait()`.

> 18:44:14 up 2 days,  9:12,  2 users,  load average: 0.47, 0.64, 0.71
### What did you see instead?
`cmd.Wait()` returned `waitpid: no child process`.

> 18:44:14 up 2 days,  9:12,  2 users,  load average: 0.47, 0.64, 0.71
panic: waitid: no child processes
>
> goroutine 1 [running]:
main.main()
          /home/me/go/src/WhoamiTest/main.go:21 +0x12f
exit status 2

**Comment by nussjustin** [comment]
This happens because SIGCHLD gets ignored. If you only ignore SIGCHLD the behaviour is still the same, but if you ignore any other signal (e.g. SIGTERM) everything works fine.

From the waitpid(2) man page:

```
ECHILD

(for waitpid() or waitid()) The process specified by pid (waitpid()) or idtype and id (waitid()) does not exist or is not a child of the calling process. (This can happen for one's own child if the action for SIGCHLD is set to SIG_IGN. See also the Linux Notes section about threads.)
```

and

```
POSIX.1-2001 specifies that if the disposition of SIGCHLD is set to SIG_IGN or the SA_NOCLDWAIT flag is set for SIGCHLD (see sigaction(2)), then children that terminate do not become zombies and a call to wait() or waitpid() will block until all children have terminated, and then fail with errno set to ECHILD. (The original POSIX standard left the behavior of setting SIGCHLD to SIG_IGN unspecified. Note that even though the default disposition of SIGCHLD is "ignore", explicitly setting the disposition to SIG_IGN results in different treatment of zombie process children.) Linux 2.6 conforms to this specification.
```

**Comment by yadkit** [comment]
@nussjustin I understand now. Whenever a child process terminates, a SIGCHLD is sent to the parent to notify it about the child's exit status.

https://docs.oracle.com/cd/E19455-01/806-4750/signals-7/index.html

> When a child process stops or terminates, SIGCHLD is sent to the parent process. The default response to the signal is to ignore it. The signal can be caught and the exit status from the child process can be obtained by immediately calling wait(2) and wait3(3C). This allows zombie process entries to be removed as quickly as possible. 
>
> SIGCHLD catchers are usually set up as part of process initialization. They must be set before a child process is forked. A typical SIGCHLD handler retrieves the child process's exit status.
