### ISSUE TITLE
strings: OpenBSD builders timing out running strings test

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#26174]
[2018-06-29T20:48:07-a5f8128/openbsd-amd64-62](https://build.golang.org/log/223c22f8ee92c09ff32019eb91c7816d26957bd0)
[2018-06-29T21:27:23-955cc07/openbsd-amd64-62](https://build.golang.org/log/13291cb50a4c471b88246fd97881e424fb467394)
[2018-06-29T23:01:49-3198b90/openbsd-amd64-62](https://build.golang.org/log/8cc7ddaeb19ba5b4d69818393bb9b51d802b1f80)
[2018-06-29T23:03:53-1b12a2c/openbsd-amd64-62](https://build.golang.org/log/016c2e05e4f44544a1f7b86fbaff74d54f2b9ba7)
[2018-06-30T01:04:30-0dc814c/openbsd-amd64-62](https://build.golang.org/log/36e6aaf2eb1027077b5ebbf0f843dab3a0794e0e)

**Comment by ianlancetaylor** [comment]
Most likely cause is https://golang.org/cl/121495 which started running much longer string comparison tests on the builders.

**Comment by ianlancetaylor** [comment]
But the full test only takes 9 seconds on my laptop so it's hard to understand how it could take 180 seconds on OpenBSD.

**Comment by ianlancetaylor** [comment]
See also #26155

**Comment by ianlancetaylor** [comment]
Using gomote and running `go test strings` without `-test.short`, I see that `TestCompareStrings` takes 213.40 seconds to run.

**Comment by ianlancetaylor** [comment]
Running the test with `-test.cpuprofile` gives me this from `go tool pprof`'s `top` command:

```
Showing nodes accounting for 21s, 94.13% of 22.31s total
Dropped 72 nodes (cum <= 0.11s)
Showing top 10 nodes out of 80
      flat  flat%   sum%        cum   cum%
     7.68s 34.42% 34.42%      7.68s 34.42%  runtime.nanotime
     5.59s 25.06% 59.48%      5.59s 25.06%  runtime.thrsleep
     2.36s 10.58% 70.06%      2.36s 10.58%  runtime.osyield
     2.08s  9.32% 79.38%      2.08s  9.32%  runtime.memmove
     1.36s  6.10% 85.48%      1.36s  6.10%  runtime.thrwakeup
     0.61s  2.73% 88.21%      0.61s  2.73%  memeqbody
     0.51s  2.29% 90.50%      0.51s  2.29%  cmpbody
     0.36s  1.61% 92.11%      0.36s  1.61%  runtime.procyield
     0.32s  1.43% 93.55%      0.40s  1.79%  runtime.scanobject
     0.13s  0.58% 94.13%      0.13s  0.58%  runtime.findObject
```

**Comment by josharian** [comment]
linux/arm too

**Comment by ianlancetaylor** [comment]
CL 121820 has been committed, which should let this test pass reliably, so removing the release-blocker label.  Leaving the issue open to investigate why the test is so much slower on OpenBSD compared to GNU/Linux.  It may be only that GNU/Linux gets the current time via a VDSO and sleeps on a futex, but it would be nice to know for sure.
