### ISSUE TITLE
syscall/js: panic: not a number

### ISSUE THREAD

**Issue by agnivade** [golang/go#26170]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version devel +6780042 Sun Jul 1 08:07:47 2018 +0000 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/agniva/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/agniva/play/go"
GOPROXY=""
GORACE=""
GOROOT="/home/agniva/play/gosource/go"
GOTMPDIR=""
GOTOOLDIR="/home/agniva/play/gosource/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build501975403=/tmp/go-build -gno-record-gcc-switches"
VGOMODROOT=""
```

### What did you do?

I tried to rebuild my [app](https://github.com/agnivade/shimmer) after all the new changes in master. The app responds to events from `input[type=range]` and acts accordingly. 

When I try to take the `.Float()` of the `js.Value`, I get the above-mentioned panic. The value is a perfectly fine float. And it even works fine if I take `.String()` and do a `strconv.ParseFloat` of it.

The problem goes away if I go back to the commit before https://github.com/golang/go/commit/8997ec1c4e01b01f9950f0869085ef5be6d45ef0 (syscall/js: use stable references to JavaScript values)

I believe this is an inadvertent mistake, please let me know if I am wrong.

### What did you expect to see?
The app to run successfully after moving to new API.

### What did you see instead?
```
panic: syscall/js: not a number
wasm_loader.js:39 
wasm_loader.js:39 goroutine 5 [running]:
wasm_loader.js:39 syscall/js.Value.Float(...)
wasm_loader.js:39 	/home/agniva/play/gosource/go/src/syscall/js/js.go:234
wasm_loader.js:39 main.main.func1(0x7ff8000000000020)
wasm_loader.js:39 	/home/agniva/play/go/src/github.com/agnivade/shimmer/repro.go:12 +0x11
wasm_loader.js:39 syscall/js.NewEventCallback.func1(0xc01e048, 0x1, 0x1)
```

Very minimal repro, without releasing callbacks -

```html
<label for="contrast">Contrast</label>
<input type="range" min="-1" max="1" value="0" step="0.1" id="contrast">
```

```go
// +build js,wasm

package main

import (
	"fmt"
	"syscall/js"
)

func main() {
	cb := js.NewEventCallback(js.PreventDefault, func(ev js.Value) {
		// This panics
		delta := ev.Get("target").Get("value").Float()
		fmt.Println(delta)

		// This works
		// deltaStr := ev.Get("target").Get("value").String()
		// delta, err := strconv.ParseFloat(deltaStr, 64)
		// if err != nil {
		// 	fmt.Println(err)
		// 	return
		// }
		// fmt.Println(delta)
	})
	js.Global().Get("document").
		Call("getElementById", "contrast").
		Call("addEventListener", "change", cb)

	select {}
}
```

**Comment by neelance** [comment]
The `value` of an `<input type="range">` is a string, not a number, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range.

**Comment by myitcv** [comment]
@neelance is there some way we can report the actual type in the error
message?

**Comment by agnivade** [comment]
I see. So it was a mistake earlier ? And `strconv.ParseFloat()` is the way to go ?

**Comment by neelance** [comment]
@agnivade The earlier version did implicit type conversions, which got removed. You can try the `valueAsNumber` mentioned on the MDN page or `strconv.ParseFloat()`.

@myitcv Yes, that's on my todo list.

**Comment by agnivade** [comment]
Thanks. Closing.
