### ISSUE TITLE
gofmt 1.11 fails for files that pass on 1.10

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#26180]
### What version of Go are you using (`go version`)?
1.10
1.11

our Travis CI runs the same tests agains 1.10 and 1.11 and since the last few days all test fail for some additional white space changes.

https://travis-ci.org/prometheus/prometheus/builds/399060443

If you notice the same passes under 1.10

the command that runs is 
`! gofmt -d $(find . -path ./vendor -prune -o -name '*.go' -print) | grep '^'`
on https://github.com/prometheus/prometheus

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/krasi/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/krasi"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build023296472=/tmp/go-build -gno-record-gcc-switches"

**Comment by agnivade** [comment]
I believe this is unfortunate. Please see https://github.com/golang/go/issues/25161.

@griesemer can confirm but I believe he is in vacation.

**Comment by krasi-georgiev** [comment]
yep that looks like it. closing now and will look for a solution in the CI pipeline.
