### ISSUE TITLE
cmd/link: linker memory use increase from 1.10 to 1.11

### ISSUE THREAD

**Issue by thanm** [golang/go#26186]
### What version of Go are you using (`go version`)?

tip:
go version devel +1e1bd239c5 Thu Jun 28 16:10:19 2018 -0400 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

When I build large Go programs, I note that memory consumption has increased during the link step, when moving from Go 1.10 to Go 1.11; it seems that the linker is taking more memory than it used to. The memory consumption increase varies from program to program, but looks on the order of 20-30%. Building "hyperkube" from kubernetes tip (1.11) is one example.  The 20% number is is derived from building a specific copy of "hyperkube" with 1.10 & 1.11 and comparing heap profiles collected via 

  go build -ldflags "-memprofile XXX -memprofilerate 1"

using "go tool pprof".  Link steps that use the external linker (for CGO) have larger increases.

The current theory is that this is related to additional DWARF symbols/sections/relocations that the compiler is emitting (for example, DWARF location lists are now enabled with 1.11, as are DWARF inline info records).

It would be worth doing some work to figure out exactly where the memory increase is coming from, and submitting fixes to bring down the overall usage if possible, so as to avoid having the linker run out of memory when linking very large Go programs.

**Comment by ianlancetaylor** [comment]
Should we move this issue's milestone to 1.12 at this point?

**Comment by thanm** [comment]
>>Should we move this issue's milestone to 1.12 at this point?

I suppose that make sense. Done.

**Comment by alevchuk** [comment]
I ran into this issue. Not able to build go 1.11 on raspberry pi with 433 MB of RAM: #26523 , go 1.10 builds fine

**Comment by goenning** [comment]
I think we've hit the same wall. I can't make our CircleCI build to pass with Go 1.11.1 due to link failures

```
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
```

**Comment by mark-rushakoff** [comment]
In the CircleCI case in particular, through https://groups.google.com/forum/?pli=1#!topic/golang-nuts/E9viXwCsHJA with @ianlancetaylor's help I found out that when running on Docker in Circle, Go thinks there are 36 CPUs, which means the default number of parallel build processes will be 36, so it's not very surprising to run into OOM errors.

 According to https://circleci.com/docs/2.0/configuration-reference/#resource_class, the default Docker container only has 2 CPUs available. So `-p=8` is probably reasonable, but maybe dropping to `-p=2` could be necessary.

**Comment by thanm** [comment]
Yes, I think we should close it out.  Austin has been collecting a list of more heavyweight things to do to improve linker performance (time and space) for post 1.12 development.
