### ISSUE TITLE
Unable to set `Useragent` Header for CONNECT requests.

### ISSUE THREAD

**Issue by qZanity** [golang/go#26188]
For HTTP CONNECT tunnels, the default Go useragent is always used.

> CONNECT www.target.com:443 HTTP/1.1
> Host: www.target.com:443
> User-Agent: Go-http-client/1.1

What's the best way to set this without hacking too much of net/http.

**Comment by bradfitz** [comment]
Sounds like https://golang.org/pkg/net/http/#Transport.ProxyConnectHeader is what you want.
