### ISSUE TITLE
x/vgo: use submodule's latest commit in pseudo versions

### ISSUE THREAD

**Issue by myitcv** [golang/go#26196]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10.3 linux/amd64
```

### Does this issue reproduce with the latest release?

n/a - this is a `git` and other VCS-related issue.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GORACE=""
GOROOT="/home/myitcv/dev/go"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/dev/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build592861713=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

At the time of writing, [commit `5e591d073e90`](https://github.com/myitcv/x/tree/5e591d073e90e8421d55c864aecc3e8965608387) is the `HEAD` of `master` for `myitcv.io` modules.

```
cd `mktemp -d`
export GOPATH=$PWD
mkdir hello
cd hello
vgo mod -init -module example.com/hello
vgo get myitcv.io/cmd/modpub
```

gives output:

```
vgo: finding myitcv.io/cmd/modpub latest
vgo: finding github.com/kr/fs v0.0.0-20131111012553-2788f0dbd169
vgo: downloading myitcv.io/cmd/modpub v0.0.0-20180702093358-5e591d073e90
vgo: downloading github.com/kr/fs v0.0.0-20131111012553-2788f0dbd169
```

We can see the pseudo version for `myitcv.io/cmd/modpub`, `v0.0.0-20180702093358-5e591d073e90`, corresponds to the `HEAD` of `master`.

But the latest commit within the `cmd/modpub` subdirectory (submodule) is actually [601ad1bf19](https://github.com/myitcv/x/tree/601ad1bf192257c6550c004a55b6f2c809f6f98b):

```
cd `mktemp -d`
git clone https://github.com/myitcv/x
cd x
git checkout 5e591d073e90
git log -1 cmd/modpub/
```

gives:

```
commit 601ad1bf192257c6550c004a55b6f2c809f6f98b
Author: Paul Jolly <paul@myitcv.io>
Date:   Mon Jul 2 09:20:47 2018 +0100

    ci: use latest vgo and remove soon-to-be-updated packages (#30)
```

### What did you expect to see?

It would be preferable to have the pseudo version for a submodule correspond to the commits relevant to that submodule. That way the pseudo version won't correspond to a commit that had nothing to do with that submodule (i.e. a commit that touched code elsewhere in the repo).

### What did you see instead?

As above; the pseudo version is calculated from the repo-level commit log.

**/cc** @rsc @bcmills

**Comment by bcmills** [comment]
It seems tricky (and inefficient) to decide which commits affect the submodule: for example, should we count commits that touch README files, or only Go source files?

On top of that, it's not obvious to me that we would gain much by bumping the pseudo-version back by a few commits. Are there cases where this results in a significant semantic change, or is it mostly aesthetic?

**Comment by myitcv** [comment]
> It seems tricky (and inefficient) to decide which commits affect the submodule: for example, should we count commits that touch README files, or only Go source files?

I might be missing something here, but is it not as simple of running `git log` or equivalent with an argument of the subdirectory, per above? By definition therefore it applies to all `git`-controlled files beneath that subdirectory. 

> Are there cases where this results in a significant semantic change, or is it mostly aesthetic?

There is no semantic change, but I think it's a more useful/relevant reference for the package author and consumer. Because a quick glance at the commit will then show either what last changed in that submodule.

**Comment by rsc** [comment]
In general we never run git log to poke around and look for commits. We only use tagged commits, or if someone specifies a commit then we'll look it up directly. But we don't go searching for commits beyond tags. I do not want to redefine "latest" on a subdirectory to have to fetch a git log.

If you want more control over which commits are addressed, I think the answer is to tag them, not make this logic more sophisticated.

**Comment by myitcv** [comment]
> I do not want to redefine "latest" on a subdirectory to have to fetch a git log.

Ah, that's the bit I'm missing, thanks. 

> If you want more control over which commits are addressed, I think the answer is to tag them, not make this logic more sophisticated

That makes sense, even for pre-releases. Sorry, feels like I missed this as an obvious solution to the problem.
