### ISSUE TITLE
x/net/http2: fragile TestServerHandlerConnectionClose

### ISSUE THREAD

**Issue by mikioh** [golang/go#26190]
See https://storage.googleapis.com/go-build-log/28f9b880/windows-386-2008_897ede7f.log and https://storage.googleapis.com/go-build-log/28f9b880/linux-amd64_0ac7746a.log; it's pretty easy to reproduce with the following:
```
go test -v -run TestServerHandlerConnectionClose -count 100
```

**Comment by fraenkel** [comment]
The test case asserts that GOAWAY will be seen before Headers. However, the code has racing channels which cannot guarantee this ordering.

**Comment by fraenkel** [comment]
@bradfitz This was a recent change you made. Are you trying to guarantee the GOAWAY before Headers?
