### ISSUE TITLE
x/vgo: won't compile a program that embeds a struct from another library

### ISSUE THREAD

**Issue by kevinmichaelchen** [golang/go#26198]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.10.2 darwin/amd64

$ vgo version
go version go1.10.2 darwin/amd64 vgo:2018-02-20.1
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevinchen/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kevinchen/golang"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2q/bsx7tl7d4tj4s6pb3gxflb2r0000gp/T/go-build691247737=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
I've reproduced the issue with 2 minimal repos
- [kevinmichaelchen/foo](https://github.com/kevinmichaelchen/foo), a library that contains a struct `Bar`
- [kevinmichaelchen/vgo-embedded-struct](https://github.com/kevinmichaelchen/vgo-embedded-struct), a program that contains a struct trying to embed `Bar`

Running `vgo install ./...` from inside `vgo-embedded-struct` gives the error
```
# github.com/kevinmichaelchen/vgo-embedded-struct
./main.go:7:2: undefined: foo.Cow
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I think I expected it to compile, unless I'm missing something.

### What did you see instead?
I saw `vgo install ./...` give the aforementioned error.

**Comment by AlexRouSg** [comment]
https://github.com/kevinmichaelchen/foo/blob/master/foo.go
```
package foo

type Bar struct {
}
```

Cuz there is no Cow type in package foo. This has nothing to do with vgo.

**Comment by kevinmichaelchen** [comment]
@AlexRouSg Yup, my bad. Fixed it and `vgo build -o woo_built_with_vgo .` now works.

I was trying (unsuccessfully) to reproduce an issue in [github.com/sfreiberg/gotwilio](https://github.com/sfreiberg/gotwilio):
```
# works
go build -o woo_built_with_go .

# fails
vgo build -o woo_built_with_vgo .
```

**Comment by AlexRouSg** [comment]
Check your go.mod file, jwt.StandardClaims was added in v3.0.0.

As vgo doesn't allow using > v1 without a go.mod file present, and since there is a v1.0.0 tag. I suspect it defaults to v1.0.0. As legacy packages would use either v1.0.0 or the pseudo version v0.0.0-date-hash, since v1.0.0 is "newer" than v0.0.0 it uses that.

I feel like I've seen a issue to fix the order, but I cannot find it. So if using the latest vgo is still showing the same behavior then what you can do is either get the package maintainer to add a go.mod file and change your import paths to use `/v3` or change your go.mod file to use the v0.0.0-date-hash syntax.

**Comment by kevinmichaelchen** [comment]
@AlexRouSg thanks, so this has nothing to do with vgo. I was just had wrong configurations.

This is what I ended up with:
```
require (
    github.com/dgrijalva/jwt-go v0.0.0-20180308231308-06ea1031745c
)
```
