### ISSUE TITLE
doc: Clarify support status of Windows Server 2008 (non-R2)

### ISSUE THREAD

**Issue by mappu** [golang/go#26191]
Hi,

`Go 1.10 is the last release that will run on Windows XP or Windows Vista. Go 1.11 will require Windows 7 or later.`

That's fine, XP and Vista are out of support by Microsoft anyway.

Windows Server 2008 R2 is based on Windows 7 and there is an active 2008 R2 builder (`host-windows-amd64-2008`).

Windows Server 2008 is based on Windows Vista and there is no active builder. But unlike Vista, it's still in "Extended Support" from Microsoft.

I assume that support for the original Server 2008 was dicey anyway (no builder) and with Vista being dropped, Server 2008 will probably experience the same issues as Vista will in 1.11, despite still being an actively supported OS by Microsoft.

Is that correct?

Can this be mentioned in the documentation?
- e.g. in https://github.com/golang/go/wiki/MinimumRequirements , statements such as "XP or later" could be clarified (it's also not clear if these requirements are for the compiler or for the compiled binaries; i assume the requirements the same).
- I wasn't able to find a summary of all currently supported OSes in the `doc/` directory - only a summary of the changes made by each release, in their release notes.

**Comment by bradfitz** [comment]
I've updated https://github.com/golang/go/wiki/MinimumRequirements#windows 

And yes, it's intentional that we're dropping the Vista-ish Windows Server 2008 (pre-R2) and requiring R2 there.
