### ISSUE TITLE
cmd/cgo: linux-{386,amd64}-clang and linux-arm builders failing

### ISSUE THREAD

**Issue by mundaym** [golang/go#26197]
Appears to have been triggered by [CL 89655](https://golang.org/cl/89655).

linux-386-clang: https://build.golang.org/log/0bef8033f7380e36756d6ce63cdec841108010de

```
# _/workdir/go/misc/cgo/test.test
/workdir/go/pkg/tool/linux_386/link: running /usr/bin/clang failed: exit status 1
/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../lib32/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAIL	_/workdir/go/misc/cgo/test [build failed]
```

linux-amd64-clang: https://build.golang.org/log/c233d2a2dd1486978f0030a3aec3a656340c5aa5

```
# _/workdir/go/misc/cgo/test.test
/workdir/go/pkg/tool/linux_amd64/link: running /usr/bin/clang failed: exit status 1
/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAIL	_/workdir/go/misc/cgo/test [build failed]
```

linux-arm: https://build.golang.org/log/d34739a782a08aed7a8ca08f130d35a7ec2767cb

```
# _/workdir/go/misc/cgo/test
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/5/crtbeginT.o: relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/arm-linux-gnueabihf/5/crtbeginT.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
FAIL	_/workdir/go/misc/cgo/test [build failed]
```

**Comment by ianlancetaylor** [comment]
The problem with clang is that passing `-rdynamic` clang is causing it to pass `-export-dynamic` to /usr/bin/ld which is causing the linker to report this error.

**Comment by ianlancetaylor** [comment]
And in fact there is code in cmd/link to handle exactly this case, but it only applies to -extldflags, not to CGO_LDFLAGS.

**Comment by zhangyoufu** [comment]
> When the glibc library is built with --enable-static-pie the resulting libc.a is usable with GCC 8 and above to create static PIE executables using the GCC option '-static-pie'.  This feature is currently supported on i386, x86_64 and x32 with binutils 2.29 or later, and on aarch64 with binutils 2.30 or later.
Any plan on support static pie executable?

**Comment by ianlancetaylor** [comment]
@zhangyoufu I don't think that has anything to do with this issue, which is about some failing tests.  Please ask on a forum; see https://golang.org/wiki/Questions .  Thanks.
