### ISSUE TITLE
x/mobile: 

### ISSUE THREAD

**Issue by jimmy9065** [golang/go#26239]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.3

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chadsong/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chadsong/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vn/nzgg4v_x5mz8mgy8z545w3v40000gn/T/go-build518845240=/tmp/go-build -gno-record-gcc-switches -fno-common

### What did you do?
I used gomobile bind to build a framework file for ios development.
When I try to import the file into xcode, I notice there is something wrong with including some headers.

Say my project is Xxx, and it created Xxx.framework.
1) In the framework file, the Xxx.objc.h include "Universe.objc.h". 
    In fact this file should be "universe.objc.h", which is also included by xxx.h file. And there is only one universe.objc.h file exists in the folder.
2) In universe.objc.h file, it shold include ref.h which it did not.

### What did you expect to see?
The program wont compile, and reporting missing package if I don't edit those header files.

### What did you see instead?
The program won't compile.

**Comment by eliasnaur** [comment]
Please describe the steps to reproduce the error. And make sure you're using the latest gomobile version .
