### ISSUE TITLE
Is it considered as a bug?

### ISSUE THREAD

**Issue by rafaelsq** [golang/go#26235]
### What version of Go are you using (`go version`)?
```
go version go1.11beta1 darwin/amd64
go version go1.10 darwin/amd64
go version go1.9 darwin/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rafael/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rafael/.gvm/pkgsets/go1.10/global"
GORACE=""
GOROOT="/Users/rafael/.gvm/gos/go1.10"
GOTMPDIR=""
GOTOOLDIR="/Users/rafael/.gvm/gos/go1.10/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f2/c44r_1xj6gn1pdfjl20ksmkh0000gp/T/go-build966899275=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

```golang
package main

import (
	"fmt"
)

type A struct {
	c chan struct{}
}

func (a *A) Add() {
	a.c <- struct{}{}
}

func (a *A) Listen() chan struct{} {
	c := make(chan struct{}, 1)

	go func() {
		select {
		case <-a.c:
			c <- struct{}{}
		}
	}()

	return c
}

func main() {
	q := A{c: make(chan struct{}, 1)}
	start := make(chan struct{}, 1)
	exit := make(chan struct{}, 1)

	go func() {
		for {
			select {
			case <-start:
				fmt.Println(" -start")
				q.Add()
			case <-q.Listen():
				fmt.Println(" -on.listen")
				close(exit)
			}
		}
	}()

	start <- struct{}{}
	<-exit
}
```

in this example, the application **will end with no error**.

```golang
func main() {
	q := A{c: make(chan struct{}, 1)}
	start := make(chan struct{}, 1)

	go func() {
		for {
			select {
			case <-start:
				fmt.Println(" -start")
				q.Add()
			case <-q.Listen():
				fmt.Println(" -on.listen")
			}
		}
	}()

	start <- struct{}{}
	time.Sleep(time.Millisecond)
}
```

### What did you expect to see?

```bash
$ go run bug.go
 -start
 -on.listen
```

### What did you see instead?

darwin always crash with`fatal error: all goroutines are asleep - deadlock!`.
in my real application, as it doesn't have the `exit` chan as in the example, it will end with no error.

when I run it on `go version go1.10.2 linux/amd64`(docker) **sometimes** it will works.

### Workaround

```golang
	// if I call the func beforehand, it will solve the problem.
	listen := q.Listen()

	go func() {
		for {
			select {
			case <-start:
				fmt.Println(" -start")
				q.Add()
			case <-listen:
				fmt.Println(" -on.listen")
			}
		}
	}()
```

**Comment by andyleap** [comment]
That's not a bug, you are making multiple channels and goroutines in the listen call.  Only one of those channels is being listened to in the select, and it's a tossup which goroutine gets it (and thus, if the wrong one gets it, you get a deadlock)

**Comment by mvdan** [comment]
Like @andyleap says, this seems like a bug in your code. In the future, for questions about Go, please use https://golang.org/wiki/Questions.

**Comment by rafaelsq** [comment]
The problem I mean is that the `select` statement doesn't evaluated the function `q.Listen()`.

**Comment by andyleap** [comment]
That's not the problem, the problem is that it evaluates it multiple times, which is expected.  Put a print in the q.Listen() function and see if it matches what you expect it to

**Comment by rafaelsq** [comment]
my bad, thanks @andyleap 😅
