### ISSUE TITLE
cmd/go: go test links and runs tests for packages with no tests

### ISSUE THREAD

**Issue by rsc** [golang/go#26242]
If asked to run "go test" on a directory with no \*_test.go files, I expect "go test" not to build and run a test binary. Go 1.10 and earlier did not. But the current Go 1.11 tree does. Surprise!

```
$ mkdir $GOPATH/src/zz
$ cd $GOPATH/src/zz
$ echo package zz >zz.go
$ go1.10 test -x 2>&1 | grep '\.test'
$ go test -x 2>&1 | grep '\.test'
packagefile zz.test=/Users/rsc/Library/Caches/go-build/d2/d295e08103bd5a774940e8d5caad0cf7e2daa7c33c648984212f91ddcf9aae69-d
/Users/rsc/go/pkg/tool/darwin_amd64/link -o $WORK/b001/zz.test -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=x_MweihetzP0Eun-VgUA/dX2Te_1YwK9j-BWgg7AH/tGS-MgIOLxh0lEea7iw_/x_MweihetzP0Eun-VgUA -extld=clang /Users/rsc/Library/Caches/go-build/d2/d295e08103bd5a774940e8d5caad0cf7e2daa7c33c648984212f91ddcf9aae69-d
$WORK/b001/zz.test
$ 
```

If you run 'go test -badflag' then you can see the difference quite clearly: if the test doesn't run, nothing detects the bad flag, so it succeeds.

A more reasonable example is if you have a test helper library you use for all your tests that defines some common flag. It used to work to run 

	go test my.tree/... -my.flag

assuming that all your tests imported the library defining -my.flag. But now if any packages in that tree have no tests at all, a dummy test binary gets run that of course does not know about -my.flag

This was originally reported as a bug against vgo in #26214.

**Comment by meirf** [comment]
Looks like this started with https://github.com/golang/go/commit/8396015e80afa4ddd4ea3c3f00373d22c3b45d6c

**Comment by ianlancetaylor** [comment]
@rsc This change was made to fix #24570.

We can roll it back if you like.

**Comment by ianlancetaylor** [comment]
CC @Kyroy

**Comment by ianlancetaylor** [comment]
Also #26157.
