### ISSUE TITLE
cmd/compile: optimize slice copy via make+copy

### ISSUE THREAD

**Issue by bontibon** [golang/go#26252]
go version devel +b0155e3424 Fri Jul 6 14:45:29 2018 +0000 linux/amd64

Two different slice copying techniques are mentioned on the [Slice Tricks wiki page](https://golang.org/wiki/SliceTricks):

-     b = make([]T, len(a))
      copy(b, a)
-     b = append([]T(nil), a...)

Benchmarking the two:

```go
package bin

import "testing"
import "bytes"

var src = bytes.Repeat([]byte("golang"), 1024*10)

func BenchmarkAppend(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = append([]byte(nil), src...)
	}
}

func BenchmarkMakeCopy(b *testing.B) {
	for i := 0; i < b.N; i++ {
		s := make([]byte, len(src))
		copy(s, src)
	}
}
```

```
goos: linux
goarch: amd64
BenchmarkAppend-8     	  200000	      9804 ns/op	   65536 B/op	       1 allocs/op
BenchmarkMakeCopy-8   	  100000	     12097 ns/op	   65536 B/op	       1 allocs/op
```

The `make` + `copy` call can probably be optimized to operate in the same way `append` does.

**Comment by josharian** [comment]
@martisch

**Comment by martisch** [comment]
Was already experimenting optimizing make+copy for go1.12 as followup of the append improvements for go1.11. Unfortunately the opportunity is not as directly detectable as the append optimizations.  If we want to do before ssa its likely we need to look at a slicemake followed immediately by a copy in a slice of statements during ordering. Which is a kind of lookahead in a statement list i dont think we yet have done an optimization for anywhere else. It will also not detect make+somestatements+copy but code could be rewritten to somestatements+make+copy+somestatements to make it match where performance matters.

**Comment by TocarIP** [comment]
Looks like this is https://github.com/golang/go/issues/23306

**Comment by martisch** [comment]
I see them as separate concerns. This issue in my view is about optimizing make+copy by e.g. avoiding memclr before the copy if it is not needed for e.g. non pointer containing slices (like growslice for append already does).

#23306 looks more about that a memclr (without the copy) has worse performance then a memcpy.

**Comment by ikkerens** [comment]
Looking into this issue, I've found similar performance to `BenchmarkMakeCopy` when running this benchmark:
```go
func BenchmarkMakeCapAppend(b *testing.B) {
	for i := 0; i < b.N; i++ {
		s := make([]byte, 0, len(src))
		s = append(s, src...)
	}
}
```

Assuming the performance drop is due to a memclr, why is memclr being called at all?

**Comment by martisch** [comment]
"Assuming the performance drop is due to a memclr, why is memclr being called at all in this particular scenario?" because the compiler has not been coded to detect that append will overwrite all the values in s after make and not doing memclr in make wont result in changed program behaviour. 

In general make needs to zero the contents of the newly created slice https://golang.org/ref/spec#The_zero_value. If we can avoid that without changing program behavior than thats a possible valid optimization. For e.g. slices with elements with pointers that wont be possible because the garbage collector could see pointers to weird memory locations in the created slice after make returns and before append runs.

**Comment by martisch** [comment]
With the current version of c/146719 the above benchmark changes to favor make+copy:
name      old time/op  new time/op  delta
Append    5.93µs ± 4%  5.82µs ± 5%   -1.79%  (p=0.047 n=20+20)
MakeCopy  9.75µs ± 2%  5.58µs ± 2%  -42.73%  (p=0.000 n=20+20)

**Comment by odeke-em** [comment]
I spoke to @martisch and we'll push this to Go1.15 as he didn't have time to get it in for Go1.14.
