### ISSUE TITLE
encoding/binary.ReadVarint does not follow spec

### ISSUE THREAD

**Issue by ilikebits** [golang/go#26258]
### What version of Go are you using (`go version`)?
`go version go1.10.3 linux/amd64`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/leo/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leo/src/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build048794147=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I tried to decode a Uvarint-encoded integer with `ReadVarint`. Program: https://play.golang.org/p/nRMSi3PRvi5

### What did you expect to see?

The documentation for `encoding/binary` says:

> The varint functions encode and decode single integer values using a variable-length encoding; smaller values require fewer bytes. For a specification, see https://developers.google.com/protocol-buffers/docs/encoding.

The specification says (emphasis added):

> Each byte in a varint, except the last byte, has the most significant bit (msb) set – this indicates that there are further bytes to come. The lower 7 bits of each byte are used to store the **two's complement representation** of the number in groups of 7 bits, least significant group first.

This would imply that, for positive numbers, `ReadVarint` and `ReadUvarint` would return the same result when given the same byte slice.

### What did you see instead?
`ReadVarint` does not return the same result as `ReadUvarint` when given a varint-encoded byte slice of a positive number. Instead, `ReadVarint` appears to do something completely different, which is not two's complement decoding at all:

```golang
// ReadVarint reads an encoded signed integer from r and returns it as an int64.
func ReadVarint(r io.ByteReader) (int64, error) {
	ux, err := ReadUvarint(r) // ok to continue in presence of error
	x := int64(ux >> 1)
	if ux&1 != 0 {
		x = ^x
	}
	return x, err
}
```

**Comment by ulikunitz** [comment]
Protocol buffers handles signed integers differently than normal integers. The are not stored in two's complement representation, but use a so called **ZigZag** encoding. The documentation of ReadVarInt cleary states that it reads an **encoded signed integer**, which according to the Protocol Buffer documentation uses the ZigZag encoding.

The rationale is that the two's complement representation requires always the maximum number of bytes for negative numbers. The ZigZag encoding avoids that problem.

**Comment by robpike** [comment]
Working as intended, and as described by @ulikunitz
