### ISSUE TITLE
all: avoid "Func always returns Value" in godocs

### ISSUE THREAD

**Issue by mvdan** [golang/go#26268]
This is a generic issue after a specific case was reported, #26267.

As an example:

```
// ...
// ListenAndServe always returns a non-nil error.
func ListenAndServe(addr string, handler Handler) error
```

What is meant here is that, when the func returns, the error is always non-nil. However, the wording can be misinterpreted, and one may infer that the func will always return, or that it will return shortly or without blocking.

In general, none of those are meant. For example, if calling a function ends up in a panic or an `os.Exit` call, the function may not return any values. And some functions block indefinitely until stopped, such as `http.ListenAndServe`.

I propose that we reword all the "always return" sentences in godocs, to remove ambiguity:

```
// The returned error is always non-nil.
```

We already use this form in some cases:

```
src/bytes/buffer.go:262:// The returned error is always nil, but is included to match bufio.Writer's
src/bytes/reader.go:34:// The returned value is always the same and is not affected by calls
src/math/big/rat.go:399:// Denom returns the denominator of x; it is always > 0.
src/runtime/malloc.go:508:// h.arenas metadata. The returned size is always a multiple of
src/strings/builder.go:89:// The returned error is always nil.
src/strings/reader.go:33:// The returned value is always the same and is not affected by calls
```

There are quite a few likely cases:

```
$ git grep '^//.*always return' src | wc -l
42
```

Happy to look into this if we agree that the wording change is an improvement.

**Comment by davecheney** [comment]
Thank you for suggesting this. 

Personally I don’t find the new wording any clearer than the previous. What is a non-nil error? Is it referring to a typed nil, or is it promising that the function always returns an error? Or if the function returns an error the value won’t be nil?

I’d like to suggest an alternative, which is to simply remove the line in the majority of cases. That might highlight the minority case where something very funky is happening and deserves careful wordsmithing.

**Comment by mvdan** [comment]
I haven't gone into the values themselves, because they tend to vary. This specific example was an interface type (an error), but others include functions and basic types.

> What is a non-nil error?

Do you have a suggestion for a better wording that is still concise? `typed non-nil error` doesn't seem particularly better to me.

> is it promising that the function always returns an error?

I think this is one of the main two ambiguities that the new wording fixes, as I explained above. The comment no longer says "F always returns", but rather "The returned X is always". That doesn't imply to me that the function always returns.

> simply remove the line in the majority of cases.

I'm not sure how well that would go for the dozens of existing cases. At least for the `net/http` ones, I do think the sentences are useful.

**Comment by davecheney** [comment]
Why don’t we fix the code so typed nil errors are not returned? Then we don’t need to document a case which does not occur.

**Comment by mvdan** [comment]
I haven't given any examples of a function with the mentioned godoc that returns typed nil errors, so I'm not sure what you're referring to. What `error is always non-nil` means is `error will never be equal to untyped nil`, or `err != nil`.

**Comment by davecheney** [comment]
In that case can we simply remove the line?

Instinctively all go programmers know that if a function returns an error they should check it. The comment as it stands now sort of suggests, this is always going to return an error - so maybe don’t check it because it was invevitable?

**Comment by mvdan** [comment]
I'm not convinced - I still find that documenting pre and post conditions can be useful. In this particular case, it means that one can simply handle the error directly, without first checking that it's non-nil.

**Comment by FMNSSun** [comment]
It'd probably be more clear if you mention `blocks forever unless an error is encountered in which case a non-nil error is returned` or `blocks forever unless an error is encountered in which case the non-nil error is returned`. It might also be useful if functions that panic are annotated as such (unless it's a truly unexpected panic such as out of memory) but some functions panic if 'wrong' arguments are supplied.

**Comment by mvdan** [comment]
Yes, perhaps the `net/http` godocs could be made clearer. But note that `ListenAndServe` is just an example, and this issue is exclusively about "always returns" sentences. I'd like it to remain scoped to that, as otherwise it could quickly become "fix all inaccurate godoc post-conditions".

**Comment by davecheney** [comment]
> On 9 Jul 2018, at 18:56, Roman Müntener <notifications@github.com> wrote:
> 
> It'd probably be more clear if you mention blocks forever unless an error is encountered in which case a non-nil error is returned or blocks forever unless an error is encountered in which case the non-nil error is returned.
> 
I don’t like this, it’s too close to “if an error occurs, the error value will be non-nil”, which is redundant. 

> It might also be useful if functions that panic are annotated as such (unless it's a truly unexpected panic such as out of memory) but some functions panic if 'wrong' arguments are supplied.
> 

Unless any of the functions under discussion do panic in this way, I’d like to see this question addressed in a seperate discussion. This scope of this issue is well constrained.

**Comment by smasher164** [comment]
It sounds like the goal is to relate a function's failure with a non-nil error. Assuming that the function hasn't panic'ed, and control flow has returned to the call-site, the error should be nil.
Possible wordings include:
```
// An error returned on failure is always non-nil.

// An error returned from a failure condition is always non-nil.

// The returned error is always non-nil on a failure condition.
```

**Comment by mvdan** [comment]
@smasher164 I still think my version above is clearer:

```
// The returned error is always non-nil.
```

Is there any particular reason you want to include "failure condition" in there? For a function that either returns a non-nil error or panics/exits, I'd assume either outcome to be a failure.

All I'm looking for with this issue is agreement that the comments should be changed, and what they should be changed with - hence my proposed wording in the first post :)

**Comment by smasher164** [comment]
@mvdan Looking at it again, any function that returns will result in this specific type of error. I now agree that the wording should be changed to what you suggested.

**Comment by rsc** [comment]
Changing active to passive voice does not seem like an improvement.
The modifier "always" is also useful.
I don't see why we have to throw away all instances of "always returns".
Reading the output of `git grep '^//.*always return'` these look fine to me.

With thanks for the suggestion, I think we should leave these as is,
and remember in the future that always != immediately.

**Comment by agnivade** [comment]
If that is the decision, we should close https://github.com/golang/go/issues/26267. That is from where the issue originated.

**Comment by mvdan** [comment]
I was personally never confused by these sentences - I was guided only by the experiences from other users. So I'm okay with dropping this. Will close the other issue too.
