### ISSUE TITLE
release: unable to install golang 1.9.7 or the latest version on windows 10

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [golang/go#26260]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.7

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
amd64,windows

### What did you do?
Trying to install go using .msi installer from official site.

If possible, provide a recipe for reproducing the error.
Attached the snapshot.

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Software should be atleast installed.

### What did you see instead?
Its not even installing and creating a very bad experience.
![golangerr](https://user-images.githubusercontent.com/20404158/42409527-10005db4-81f9-11e8-946d-c99a039c8eee.JPG)

**Comment by Prim3val** [comment]
Did you run the installer as administrator ? I don't use Windows, though I think you have to have the admin rights to install directly on `C:\ `

**Comment by davecheney** [comment]
Also double check your av software is not getting in the way. This is a very common problem on windows machines.
