### ISSUE TITLE
net/http: imprecise description of the return values of HTTP serve functions

### ISSUE THREAD

**Issue by yaojingguo** [golang/go#26267]
### What version of Go are you using (`go version`)?

go version go1.10.3 darwin/amd64

In `net.http` package, there are following fucntions/methods related to serve HTTP:

1. [http.Serve](https://golang.org/pkg/net/http/#Serve)
1. [http.ListenAndServe](https://golang.org/pkg/net/http/#ListenAndServe)
1. [http.ListenAndServeTLS](https://golang.org/pkg/net/http/#ListenAndServeTLS)
1. [http.Server.Serve](https://golang.org/pkg/net/http/#Server.Serve)
1. [http.Server.ListenAndServe](https://golang.org/pkg/net/http/#Server.ListenAndServe)
1. [http.Server.ListenAndServeTLS](https://golang.org/pkg/net/http/#Server.ListenAndServeTLS)

Except the first one, all docs for those functiosn/methods say something like `always returns a non-nil error`. But if such a function/method is terminated by a signal which is a common way to terminate a HTTP server, it will not return. For example, consider the following go code `http.go`:

```go
package main

import (
	"log"
	"net/http"
)

func main() {
	var srv http.Server
	srv.Addr = ":12345"

	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
		log.Printf("http error: %s", err)
	}
}
```

A `SIGINT` signal will terminate the program and `http.ListenAndServe` will not return.
```
➜  local go run http.go
^Csignal: interrupt
```
Only if `srv` is teriminated by [Server.Shutdown](https://golang.org/pkg/net/http/#Server.Shutdown), ` srv.ListenAndServe` will return.

I think that the descripion `always returns a non-nil error` should mention this behaviour. Otherwise, people will tend to write [the following code](https://github.com/coreos/etcd/blob/master/contrib/raftexample/raft.go#L467):

```go
	err = (&http.Server{Handler: rc.transport.Handler()}).Serve(ln)
	select {
	case <-rc.httpstopc:
	default:
		log.Fatalf("raftexample: Failed to serve rafthttp (%v)", err)
	}
```
They are hoping that `Serve` will return. But it will not since `Shutdown` is not used in a way descripted in `Shutdown`'s example code.

**Comment by meirf** [comment]
I think "always" is a description of the "non-nil" quality of the error as opposed to a description of the "return" of the error. But perhaps there's a way to phrase it with less ambiguity,

**Comment by mvdan** [comment]
Perhaps the sentences could be reworded, like:

> The returned error will always be non-nil.

**Comment by agnivade** [comment]
Yep, it just says that the returned error will always be non-nil. It does not say anything about the scenarios in which the function will return. Seems clear enough to me, but maybe we can be more explicit.

/cc @bradfitz

**Comment by mvdan** [comment]
I've sent a small CL above with the proposed change.

More broadly, I've filed #26268 to look into all the other cases of "always returns X" in the standard library.

**Comment by mvdan** [comment]
Closing, just like #26268. See Russ's point there. We didn't reach consensus, and it doesn't look like we found a wording that was considerably better.
