### ISSUE TITLE
bytes: WriteString, WriteByte and Write vary in performance

### ISSUE THREAD

**Issue by mvdan** [golang/go#26264]
This is probably a compiler enhancement issue, but since I haven't done much digging, I'm conservatively filing it against the bytes package.

```
$ cat f_test.go
package p

import (
	"bytes"
	"testing"
)

func BenchmarkBytes(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i%1024 == 0 {
			buf.Reset()
		}
		buf.Write([]byte("ab"))
	}
}

func BenchmarkString(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i%1024 == 0 {
			buf.Reset()
		}
		buf.WriteString("ab")
	}
}

func BenchmarkByteByte(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i%1024 == 0 {
			buf.Reset()
		}
		buf.WriteByte('a')
		buf.WriteByte('b')
	}
}
$ go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: mvdan.cc/p
BenchmarkBytes-4        100000000               18.0 ns/op             0 B/op          0 allocs/op
BenchmarkString-4       100000000               10.5 ns/op             0 B/op          0 allocs/op
BenchmarkByteByte-4     200000000                8.44 ns/op            0 B/op          0 allocs/op
```

The first surprise here is that `WriteByte('a'); WriteByte('b')` is slightly faster than `WriteString("ab")`. The latter is much nicer to read and write, so it would be nice if it was at least as fast. This was encountered while optimizing the `encoding.json` encoder: https://go-review.googlesource.com/c/go/+/122460/1/src/encoding/json/encode.go#650

The difference is just a few nanoseconds or ~20%, but in a hot loop like when JSON is encoding struct fields, this can be noticeable.

The second surprise is how `WriteString` is much faster than `Write`. I haven't come across this directly, but I'd also assume that both would be comparable in performance.

If I replace `bytes.Buffer` with `strings.Builder` the numbers are somewhat similar, but `String` is faster than `ByteByte`.

```
BenchmarkBytes-4        100000000               15.2 ns/op             7 B/op          0 allocs/op
BenchmarkString-4       300000000                4.49 ns/op            7 B/op          0 allocs/op
BenchmarkByteByte-4     200000000                6.87 ns/op            7 B/op          0 allocs/op
```

/cc @randall77 @josharian @kevinburke

**Comment by FMNSSun** [comment]
One thing I've noticed is that sometimes inlining a variable manually makes a difference. 
Using `buf.Write([]byte("ab"))` is slower (by a lot) compared to having a variable `s := []byte("ab")` and use `buf.Write(s)` but using `buf.Write([]byte{'a','b'})` is the fastest using `buf.Write`. We never thought about doing multiple single-byte writes or use WriteString and as it turns out `buf.Write([]byte{'a','b'})` is comparable to `buf.WriteString("ab")` although still a bit slower. 

```
func BenchmarkBytes2(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i%1024 == 0 {
			buf.Reset()
		}
		buf.Write([]byte{'a','b'})
	}
}
```

is faster than doing:

```
func BenchmarkBytes3(b *testing.B) {
	var buf bytes.Buffer
	s := []byte("ab")
	for i := 0; i < b.N; i++ {
		if i%1024 == 0 {
			buf.Reset()
		}
		buf.Write(s)
	}
}
```

not by a lot but it's still consistently faster by about 3 to 5% however, and of course if you do multiple writes it adds up.

**Comment by FMNSSun** [comment]
The Benchmark here may be flawed because `[]byte("ab")` doesn't appear to get constant folded and on each iteration there's a call to `runtime.stringtoslicebyte`  so you're not only measuring the performance of the `Write` call but also the conversion from `"ab" string` to `[]byte`.

```
0x0054 00084 (f_test.go:14)	MOVQ	$2, 16(SP)
0x005d 00093 (f_test.go:14)	PCDATA	$0, $1
0x005d 00093 (f_test.go:14)	CALL	runtime.stringtoslicebyte(SB)
0x0062 00098 (f_test.go:14)	MOVQ	40(SP), AX
0x0067 00103 (f_test.go:14)	MOVQ	32(SP), CX
```

**Comment by FMNSSun** [comment]
Generally speaking:
`[]byte("..")` and `string([]byte{...})` are not constant folded. The actual difference between `.Write` and `.WriteString` is tiny:

```
$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/FMNSSun/udpdb/d/t
BenchmarkBytes-8      	100000000	        15.6 ns/op
BenchmarkBytes2-8     	200000000	         8.86 ns/op
BenchmarkBytes3-8     	200000000	         8.86 ns/op
BenchmarkBytes4-8     	200000000	         8.35 ns/op
BenchmarkString-8     	200000000	         8.40 ns/op
BenchmarkString2-8    	200000000	         8.37 ns/op
BenchmarkByteByte-8   	200000000	         7.73 ns/op
```

On my machine `WriteString` with two characters is 2-3% faster but as soon as you increase this to `"abcdef"`/`[]byte{'a','b','c','d','e',f'}` it turns around and `Write` is becoming slightly faster than `WriteString`.

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/26264 for a case where using `Write` was noticeably faster than `WriteString`. That CL wasn't merged though, as the win was too small to warrant the extra quirkiness.

**Comment by FMNSSun** [comment]
@mvdan you've linked to this issue? But my observation is still that there are differences between these functions in specific circumstances and it even makes a difference whether you inline it or not but the difference is tiny and the benchmarks are so flaky that sometimes inlining it is better and sometimes not inlining it is better. Might have something to do with the size of the function that uses write or whatever. I haven't yet been able to pinpoint anything conclusive except what I've already mentioned above.

**Comment by FMNSSun** [comment]
Flaky because look for example at:

```
func Foo(i int) int {
	return i * 2
}

func Bar(i int) int {
	return i * 2
}

func BenchmarkFoo(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i % 1024 == 0 {
			buf.Reset()
		}
		buf.WriteByte(byte(Foo(3)))
	}
}

func BenchmarkBar(b *testing.B) {
	var buf bytes.Buffer
	for i := 0; i < b.N; i++ {
		if i % 1024 == 0 {
			buf.Reset()
		}
		buf.WriteByte(byte(Bar(3)))
	}
}
```

I can run this a dozen times on my machine and BenchmarkBar is consistently slower by 2-4% but both the tests and the functions are completely identical but there's nothing inherently slower about Foo/Bar and these Benchmarks. This might be simply some microarchitectural/layout/cache thing.

**Comment by Quasilyte** [comment]
[CL125796](https://go-review.googlesource.com/c/go/+/125796) does change the situation a little bit:
```
name        old time/op    new time/op    delta
Bytes-8       26.4ns ± 0%    14.9ns ± 0%  -43.56%  (p=0.002 n=7+8)
String-8      13.9ns ± 0%    14.2ns ± 0%   +1.87%  (p=0.000 n=10+10)
ByteByte-8    13.4ns ± 0%    13.4ns ± 0%     ~     (all equal)
```

That CL makes `[]byte("ab")` identical to `[]byte{'a', 'b'}`, removing the main reason of `Bytes` benchmark being slower than the other two. It makes difference for given example negligible.

Not sure why `String` benchmark become slightly slower. Need to dig into it. Although its generated code haven't changed, might be a side-effect.

**Comment by mvdan** [comment]
@FMNSSun apologies that I haven't replied to your comments directly so far. I had read them, I just hadn't sat down to write proper replies.

You're right that my thinking about `Write` vs `WriteString` was flawed - and that's fixed by @Quasilyte's CL above.

Two `WriteByte` calls is still faster I think, but likely not enough to warrant keeping this issue open. After all, I haven't done the legwork to investigate the reason why, or if the difference can be removed.

So all in all, happy to close the issue once the CL has been merged.

**Comment by mvdan** [comment]
@ianlancetaylor thanks for the ping; I indeed think this can be closed. It doesn't look like there's much else to do for now.
