### ISSUE TITLE
CentOS 7 cannot execute binary file

### ISSUE THREAD

**Issue by Nurlan199206** [golang/go#26272]
Hi

i'm trying to install Go 1.10.3 on CentOS 7 from this tutorial [https://golang.org/doc/install?download=go1.10.3.linux-amd64.tar.gz#install](url)

im unpacked from archive with command `tar -C /usr/local -xzf go1.10.3.linux-amd64.tar.gz`

created env and project folder with commands:

```
[root@osboxes ~]# export GOROOT=/usr/local/go
[root@osboxes ~]# export GOPATH=$HOME/go/app
[root@osboxes ~]# export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

OS version etc...
`3.10.0-693.2.2.el7.centos.plus.i686 #1 SMP Tue Sep 26 14:45:56 UTC 2017 i686 i686 i386 GNU/Linux`

after installation steps i am getting error: 

```
[root@osboxes ~]# go version
bash: /usr/local/go/bin/go: cannot execute binary file
[root@osboxes ~]# go bug
bash: /usr/local/go/bin/go: cannot execute binary file
```

**Comment by mattn** [comment]
> 3.10.0-693.2.2.el7.centos.plus.i686 

It seems your kernel is 32bit. But you installed 64bit executable.

**Comment by Nurlan199206** [comment]
@mattn fail :)

**Comment by agnivade** [comment]
@Nurlan199206 - Could you kindly clarify your response ?

Are you saying it is failing even after you installed the 32bit version ?

**Comment by davecheney** [comment]
Closing based on https://github.com/golang/go/issues/26272#issuecomment-403289352
