### ISSUE TITLE
compiler: math.NewFromFloat32 result cast to uint64 produces wrong values

### ISSUE THREAD

**Issue by klauspost** [golang/go#26285]
### What version of Go are you using (`go version`)?

`go version go1.10.3 windows/amd64`

### Does this issue reproduce with the latest release?

No, fixed in Go 1.11 beta.

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\klaus\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\gopath
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\klaus\AppData\Local\Temp\go-build142328914=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Run on amd64:

https://play.golang.org/p/YW7EvMPEHaG

### What did you expect to see?

Nothing

### What did you see instead?

```
...
impossible: 0xc07f4f29c1
impossible: 0xc07dca24e5
impossible: 0xc0fe274ff5
impossible: 0xc0fe82f182
impossible: 0xc0ff2da6f8
impossible: 0xc0fd8ad6f3
impossible: 0xc07f14c573
impossible: 0xc0ff6674fd
impossible: 0xc07f295515
impossible: 0xc07f39a87b
impossible: 0xc0ff271f61
...
```

Values are clearly impossible since they overflow uint32 returned from `math.NewFromFloat32`.

Even though this is fixed, it may warrant a test and possibly a backport to Go 1.10

**Comment by mundaym** [comment]
I think this a dup of https://github.com/golang/go/issues/25335. Feel free to reopen if you disagree.
