### ISSUE TITLE
Makefile:93: *** "No go in PATH: Check dependencies".  Stop.

### ISSUE THREAD

**Issue by wakchain** [golang/go#26289]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Does this issue reproduce with the latest release?
I'm using the latest release. 

### What operating system and processor architecture are you using (`go env`)?
Linux amd64

### What did you do?
Try to set up Hyperledger Fabric
*****@*****:/src/github.com/hyperledger/fabric$ sudo make dist-clean all
Makefile:93: *** "No go in PATH: Check dependencies".  Stop.

### What did you expect to see?
![image](https://user-images.githubusercontent.com/33892012/42459304-b556e230-839b-11e8-9cff-d0b2cf2611db.png)

### What did you see instead?
Makefile:93: *** "No go in PATH: Check dependencies".  Stop.

**Comment by mvdan** [comment]
This has indeed nothing to do with the Go project.
