### ISSUE TITLE
cmd/compile: prove doesn't know that integer extensions preserve bounds

### ISSUE THREAD

**Issue by mvdan** [golang/go#26292]
As discovered by @aclements on https://go-review.googlesource.com/c/go/+/122459:

> It's proving the second of two bounds-checks on that line, possibly because it's redundant with the first. I think it's not getting the first BCE because there's a ZeroExt8to64, and prove doesn't know that preserves the bounds of the original value:
>
> v33 is b; v39 is const 128:
>
> b8: ← b6
> v38 (+889) = ZeroExt8to64 <int> v33
> v40 (889) = IsInBounds <bool> v38 v39
> If v40 → b13 b14 (likely) (line 889)
>
> Prove knows that v33 < 128, but that fact doesn't flow through to v38.
>
> So, another way to fix this is to change "b < utf8.RuneSelf" to "int(b) < utf8.RuneSelf". At least for (*encodeState).string and (*encodeState).stringBytes, the only effect of this appears to be eliminating that one bounds check (and some register renaming).

(particular comment: https://go-review.googlesource.com/c/go/+/122459/1//COMMIT_MSG#21)

**Comment by agnivade** [comment]
CL is ready to go in for 1.14.
