### ISSUE TITLE
x/tools/cmd/goimports: lost line between package and import statements in output

### ISSUE THREAD

**Issue by rsc** [golang/go#26290]
```
$ cat x.go
package p // comment

import "math"

var _ = fmt.Printf
$ goimports x.go
package p // comment
import "fmt"

var _ = fmt.Printf
$ 
```

The blank line should not have been removed. This only happens when there is an end-of-line comment on the package statement.

/cc @bradfitz

**Comment by mvdan** [comment]
May be related to #26246. I assume that https://go-review.googlesource.com/c/tools/+/122538 won't fix this issue, as that CL only merges lines.

**Comment by fraenkel** [comment]
If you attempt to goimport the result
```
package p // comment
import "fmt"

var _ = fmt.Printf
```
no newline is inserted. I haven't found a commit that ever did insert the newline.

**Comment by Gnouc** [comment]
I think this is expected behavior, according to [this commit](https://github.com/golang/tools/commit/962c79ce9f0f7b5357affbc4384eb8522ac6f8f7)

But what happen when there're 2 or more comments:

```
package p // comment 1
                  // comment 2
import "math"

var _ = fmt.Printf
```

What's designed output?
