### ISSUE TITLE
x/playground: use "go version" instead of runtime.Version

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#26291]
In sandbox.go, `cacheKey` runs `runtime.Version` on the server to invalidate entries when the playground is upgraded. However, the compiler might get updated without the server version changing. Using `go version` would be correct in that case.

**Comment by ysmolsky** [comment]
I am sorry, but I fail to see the usefulness of this. We use only releases like 1.10, 1.10.2, etc in playground. And we do not use devel (tip) build of go there. `go version` does not contain anything different than `runtime.Version`:
```
$ go version
go version go1.11beta1 darwin/amd64
```
https://play.golang.org/p/Ztyu2FJaajl

cc: @andybons

**Comment by andybons** [comment]
@ysmolsky is correct. The version specified at https://go.googlesource.com/playground/+/master/Dockerfile#11 is the same one used to build the playground binary and the nacl go command used to run code.
