### ISSUE TITLE
strings: use Builder in Map

### ISSUE THREAD

**Issue by rsc** [golang/go#26304]
@robpike and I were just looking at strings.Map. It should use Builder to avoid a copy at the end in the conversion from []byte to string.

**Comment by fraenkel** [comment]
There is a performance issue that I ran across when trying to use the Builder. The last loop which copies by byte or rune should be able to to just use builder.WriteRune(r), however, it was always ~30% slower to do so.

**Comment by go101** [comment]
Builder is not always faster, in particular for this specified case: https://groups.google.com/forum/#!topic/golang-nuts/I6Ch7hMEQLk

**Comment by josharian** [comment]
@fraenkel want to file an independent issue?

**Comment by oryanmoshe** [comment]
Is this issue still relevant? Should I check it out?
