### ISSUE TITLE
strings: Map does not handle invalid UTF-8 correctly

### ISSUE THREAD

**Issue by rsc** [golang/go#26305]
Map's loop does:

	for i, c := range s {
		r := mapping(c)
		if r == c {

This is wrong if r is the error rune because s has invalid UTF-8. The loop should check this and flip to rewriting the string in that case.

**Comment by rsc** [comment]
bytes.Map is OK because it is defined to always make a copy.

/cc @robpike

**Comment by martisch** [comment]
"This is wrong if r is the error rune because s has invalid UTF-8" should this be "This is wrong if c is the error rune because s has invalid UTF-8"?
