### ISSUE TITLE
runtime/trace: broken package documentation

### ISSUE THREAD

**Issue by ainar-g** [golang/go#26309]
### What version of Go are you using (`go version`)?
+c78b769

### What did you do?
Go to the package docs or to https://tip.golang.org/pkg/.

### What did you expect to see?
    trace    Package trace contains facilities for programs to generate trace for Go execution tracer.

### What did you see instead?
    trace    go func() { trace.WithRegion(ctx, "steamMilk", steamMilk) milk  <- true }() go func() { trace.WithRegion(ctx, "extractCoffee",  extractCoffee) espresso <- true }() go func() { defer task.End() //  When assemble is done, the order is complete.

There are empty lines in the doc comment in src/runtime/trace/trace.go. Lines 85 and 88.

**Comment by ALTree** [comment]
Thanks for the report. I've sent a change to restore the doc summary.
