### ISSUE TITLE
net/http: set MaxResponseHeaderBytes in DefaultTransport?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26315]
Should we set MaxResponseHeaderBytes to something non-zero in http.DefaultTransport?

Even if it it's something insane, like 10MB? Just to put some protection on it for users.

**Comment by rsc** [comment]
Are there other protection defaults we missed? 10 MB seems OK. (Or check with Chrome team.)

**Comment by bradfitz** [comment]
@dmitshur points out that https://go-review.googlesource.com/c/go/+/21329/2/src/net/http/transport.go already defined the zero value to mean 10 MB.

So there's nothing to do here.
