### ISSUE TITLE
x/tools/godoc: firefox source highlighting issue

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26316]
Tracking bug on our side for fixing issue brought up in https://github.com/webcompat/web-bugs/issues/17530

/cc @ysmolsky

**Comment by agnivade** [comment]
Hmm .. isn't this a godoc issue ? The URL is from golang.org/src rather than play.golang.org.

**Comment by agnivade** [comment]
Found it. Dup of https://github.com/golang/go/issues/23500. This seems to be a bug with FF. We should re-open that bug and close this if we are to track this.

**Comment by agnivade** [comment]
Closing this once since @kevinburke wants to take a crack at it and the original issue was re-opened.
