### ISSUE TITLE
spec: possibly inaccurate description of untyped case expressions

### ISSUE THREAD

**Issue by octomarat** [golang/go#26313]
"Expression switches" section of [Switch statements](https://golang.org/ref/spec#Switch_statements) has the following note about untyped case expressions:
> If a case expression is untyped, it is first [converted](https://golang.org/ref/spec#Conversions) to the type of the switch expression.

I have the following code that is rejected by the compiler:
```
package main

func main() {
	var s string = "123"
	switch s {
	case 123: // error: invalid case 123 in switch on s (mismatched types int and string)
	}
}
```
`123` is untyped constant and it is possible to convert it to `string` type. This possibility is mentioned as a special case in [Conversions](https://golang.org/ref/spec#Conversions):
> As a special case, an integer constant x can be converted to a string type using the same rule as for non-constant x.

So, this makes me wonder if spec is inaccurate here and convertibility requirements for untyped case expressions should not include special cases? Sorry if I am missing something obvious.

**Comment by ianlancetaylor** [comment]
Nice example.

**Comment by rsc** [comment]
Needs fix but probably in the spec, not in the compilers. We don't want this conversion to happen automatically.

**Comment by griesemer** [comment]
This should definitively be fixed in the spec; ideally in the Conversions section. There are other places in the spec where it talks about (implicit) conversions, e.g., in assignments, and we don't want an implicit string conversion in those cases either. Will prepare a CL.
