### ISSUE TITLE
x/net/http2: h2spec violation generic 2/2 & 2/3

### ISSUE THREAD

**Issue by fraenkel** [golang/go#26326]
```
Generic tests for HTTP/2 server
  2. Streams and Multiplexing
    × 2: Sends a WINDOW_UPDATE frame on half-closed (remote) stream
      -> The endpoint MUST accept WINDOW_UPDATE frame.
         Expected: DATA frame
           Actual: HEADERS Frame (length:28, flags:0x05, stream_id:1)
    × 3: Sends a PRIORITY frame on half-closed (remote) stream
      -> The endpoint MUST accept PRIORITY frame.
         Expected: DATA frame
           Actual: HEADERS Frame (length:28, flags:0x05, stream_id:1)
```

**Comment by bradfitz** [comment]
Can we get repro details on these bugs too? What command did you run and against which code?

**Comment by fraenkel** [comment]
The command is `$ ./h2spec -S -k -t -h 127.0.0.1 -p 8080 generic/2`
I think its related to the "server" change I made in my set up which no longer sends any data back.
It expects a Data frame which assumes the server would send something back on a GET /.

If I change the server back to send back data, we pass. Which I assume is what this test assumes but the h2spec suite does not define how the Server should behave.

**Comment by fraenkel** [comment]
I would lean toward closing this since its working properly with a response.

**Comment by fraenkel** [comment]
Confirmed that the server is expected to send back some response therefore the test case does pass.
