### ISSUE TITLE
x/sys/unix: add constants from linux/net_namespace.h

### ISSUE THREAD

**Issue by squeed** [golang/go#26330]
I'd like to add the `NETNSA_` constants from [net_namespace.h](https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/net_namespace.h).

I want to use them in my PR for netlink[1] and I imagine they'd be used by other container libraries as well.

1:  vishvananda/netlink#370,

**Comment by ianlancetaylor** [comment]
Go ahead.  Thanks.
