### ISSUE TITLE
x/tools/go/packages: dependencies recompiled for external tests have IsTest == true

### ISSUE THREAD

**Issue by dominikh** [golang/go#26345]
### What did you do?
https://play.golang.org/p/0WYlebH-P3l

### What did you expect to see?
I expected to see the packages making up `strconv`'s tests

```
strconv.test
strconv_test [strconv.test]
```

### What did you see instead?
Instead I saw all packages imported by the test.

```
context [strconv.test]
path/filepath [strconv.test]
flag [strconv.test]
runtime/pprof [strconv.test]
sort [strconv.test]
regexp [strconv.test]
log [strconv.test]
testing [strconv.test]
io/ioutil [strconv.test]
fmt [strconv.test]
runtime/debug [strconv.test]
compress/flate [strconv.test]
encoding/binary [strconv.test]
strconv.test
strconv_test [strconv.test]
strconv [strconv.test]
testing/internal/testdeps [strconv.test]
regexp/syntax [strconv.test]
reflect [strconv.test]
runtime/trace [strconv.test]
compress/gzip [strconv.test]
```

I am aware that packages imported by external tests may be distinct and probably justify being marked so. But I think that IsTest isn't the right place for this, for two reasons:

1. The name of the field does not match what it actually means
2. Currently, there is no way to take a test wrapper and programmatically determine the packages defining the tests. This makes it difficult to write linters that given an import path lint the package and its tests, but not any of the dependencies.

/cc @alandonovan (who is on vacation)

**Comment by alandonovan** [comment]
Thanks for pointing that out. I made a hasty "simplification" to the isTest predicate that was obviously not thought through.

**Comment by suzmue** [comment]
Just to provide an update to this thread, IsTest is no longer a field in Package (removed by https://golang.org/cl/124388).

Here is a version of that program using the up to date go/packages API: https://play.golang.org/p/BKqQMw2whY3

**Comment by dominikh** [comment]
Closing as this is no longer relevant.
