### ISSUE TITLE
x/mobile: gomobile: -target=ios requires XCode

### ISSUE THREAD

**Issue by daiyangyang945** [golang/go#26348]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
> 1.10.3

### Does this issue reproduce with the latest release?
> YES

### What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/1.10.3/bin"
GOCACHE="/Users/sweet/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sweet/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hz/c90vc4k91n99vfw18dj38pp80000gn/T/go-build658100496=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
> gomobile bind -target=ios -o Ethereum.framework go-ethereum

### What did you expect to see?

> Ethereum.framework

### What did you see instead?

> gomobile: -target=ios requires XCode

_I have installed Xcode and Xcode command Line tools,but it still not work._

**Comment by daiyangyang945** [comment]
I solve it.
I use `sudo Xcode-select --switch /Applications/Xcode.app/Contents/Developer/` to reset Xcode path.

**Comment by ianlancetaylor** [comment]
Closing.
