### ISSUE TITLE
cmd/cgo: CL 123177 broke all darwin builders

### ISSUE THREAD

**Issue by mvdan** [golang/go#26355]
The error logs are all a bit different, but it looks like the CL is to blame.

```
# _/private/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/misc/cgo/test/issue24161e0
issue24161e0/main.go:19:2: could not determine kind of name for C.SecKeyCreateSignature
issue24161e0/main.go:19:29: could not determine kind of name for C.kSecKeyAlgorithmECDSASignatureDigestX962SHA1
# _/private/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/misc/cgo/test/issue24161e1
issue24161e1/main.go:22:2: could not determine kind of name for C.SecKeyCreateSignature
issue24161e1/main.go:22:29: could not determine kind of name for C.kSecKeyAlgorithmECDSASignatureDigestX962SHA1
# _/private/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/misc/cgo/test/issue24161e2
issue24161e2/main.go:24:2: could not determine kind of name for C.SecKeyCreateSignature
issue24161e2/main.go:24:29: could not determine kind of name for C.kSecKeyAlgorithmECDSASignatureDigestX962SHA1
FAIL	_/private/var/folders/6g/8k13h11n2zb8hxx99wk6f6y40000gn/T/workdir/go/misc/cgo/test [build failed]
2018/07/12 12:24:44 Failed: exit status 2
```

https://build.golang.org/log/3a95705141a8316a8c9e0514974378d0aaa8f866
https://build.golang.org/log/5c52fc2c58ad510449b5028c614c74ea4e82460f
https://build.golang.org/log/5940718e6731ee4f216d2fb3c6b5daeddaffd753

/cc @randall77 @ianlancetaylor

**Comment by bradfitz** [comment]
(Mac trybots are still down from a previous outage. I've been putting off restoring them until trybots handled disappearing machines better.)

**Comment by odeke-em** [comment]
@mvdan perhaps the builders are using a stale version of Go to run `./all.test`? I ask because locally I have run `./all.test` on my Mac with the latest Go tip and no failures locally
<img width="598" alt="screen shot 2018-07-12 at 3 04 09 pm" src="https://user-images.githubusercontent.com/4898263/42659223-dbb1ba2c-85e4-11e8-85b2-16bcf6a89492.png">

**Comment by mvdan** [comment]
@odeke-em I wouldn't know - I'm nowhere near a Mac machine to investigate this :)

**Comment by randall77** [comment]
Maybe the Security framework is not reachable?  I would expect the include of Security.h to fail in that case, though.
Seems to work on a gomote'd machine just fine.
Maybe an OS version thing?  Looks like the 10.12 builders are ok, but not the 10.10 and 10.11 ones.

**Comment by randall77** [comment]
Indeed, the functions used in the test are 10.12+.  Will fix.

**Comment by odeke-em** [comment]
>Maybe an OS version thing? Looks like the 10.12 builders are ok, but not the 10.10 and 10.11 ones.

@randall77 in deed, same thoughts here https://github.com/golang/go/issues/26355#issuecomment-404650277, thanks for the articulation that the builders are using a stale Go version i.e. 10.10 and 10.11 :)

**Comment by randall77** [comment]
@odeke-em It's not the Go version, it's the Mac OSX version.

**Comment by odeke-em** [comment]
Ahh I see, thanks!
