### ISSUE TITLE
Allow const func of named type

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#26351]
### What version of Go are you using (`go version`)?
Go 1.10

### Does this issue reproduce with the latest release?
Yes

### What did you do?

[Play link](https://play.golang.org/p/evWHiovvXDj):

```go
package main

type funky func()

const g funky = func() {}

func main() {
}
```

### What did you expect to see?
Succesful compilation.

### What did you see instead?

> prog.go:5:7: const initializer func literal is not a constant

### Comment

Being able to make constant functions with a named type would be useful for `http.HandlerFunc`.

**Comment by carlmjohnson** [comment]
[This](https://play.golang.org/p/_pzvIg6fxmv) is also not allowed:

```go
package main

type funky func()

func f() {}

const g funky = f

func main() {
}
```

**Comment by jimmyfrasche** [comment]
This isn't a bug: this is a proposal to change the language. As such, it needs to follow https://github.com/golang/proposal/blob/master/README.md I would recommend reading some existing issues with the Proposal label to get an idea of what sort of information you should include.

There needs to be a lot more information here. Are there differences in use between a const func and a var func? If you have a const func what can't you do with it. Is the only benefit http.Handlers or are there others? What are the downsides? Is `const f = decorator(anotherFunc)` legal?

I'm going to close this issue. Please create a new issue when you have a more fleshed out proposal or comment on one of the current issues for extending what can be const, such as #21130, and make an argument for including func as well.

**Comment by ianlancetaylor** [comment]
Related to #6386.
