### ISSUE TITLE
cmd/go: add -getmode=noauto

### ISSUE THREAD

**Issue by rsc** [golang/go#26361]
CI systems need a way to test what's in the go.mod and fail if something is missing instead of looking to satisfy dependencies automatically. We meant for -getmode=local to mean this, but it really means something a little bit different. We should add a -getmode that does mean "you can't change go.mod". Maybe -getmode=noauto.

/cc @bcmills

**Comment by NfNitLoop** [comment]
🚲 Don't want to get too far into painting the bike shed but a name like `-getmode=repeatable` or `-getmode=read-only` might make it more clear what that means.

I'm completely fine with it trying to *satisfy* dependencies by downloading them. I just want to make sure there's a mode that will only download the exact versions which are captured in the go.mod/go.sum files and doesn't do anything beyond that.

**Comment by bcmills** [comment]
> We meant for -getmode=local to mean this, but it really means something a little bit different.

There is an interesting non-orthogonal interaction between `GO111MODULE` and `-getmode`.

Currently, `GO111MODULE` determines whether we use modules and `-getmode` determines how we find them, except that with `-getmode=vendor` we sort of don't even use them.

(In particular, we assume that the module definition cannot change in `-getmode=vendor`, even though it would theoretically be possible to at least change whether indirect dependencies are implicit or explicit in the main module's definition.)

If I understand the behavior of `-getmode=local` correctly (which I'm not sure I do; see #26370), it should allow changes to the `go.mod` file but avoid network use.

**Comment by bcmills** [comment]
> We meant for -getmode=local to mean this, but it really means something a little bit different.

I'm not actually sure what it means at the moment (see #26370). But I agree that we probably do want separate modes for “use only modules that are available” and “don't modify my `go.mod` at all”.

**Comment by bcmills** [comment]
I don't think `noauto` fits in as a `-getmode` flag.

Currently, `GO111MODULE` determines whether we use modules and `-getmode` determines how we find them.

In contrast, CI systems may or may not care about how we find modules. (For example, CI system with a reliable connection to a `GOPROXY` should be happy to fetch the modules on demand.) The important property for CI testing is that the module configuration does not change, and to me that seems more like a `GO111MODULE` setting than a `getmode`.

So I would suggest instead a new `GO111MODULE` setting, `GO111MODULE=readonly`. That would mean “fetch the active modules according to `-getmode`, but do not adjust `go.mod` or resolve imports that it does not provide”.
