### ISSUE TITLE
cmd/go: improve diagnostics for mod subcommands within $GOPATH/src

### ISSUE THREAD

**Issue by davecheney** [golang/go#26365]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

% go version
go version devel +8a330454dc Fri Jul 13 03:53:00 2018 +0000 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
```
% go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dfc/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dfc"
GOPROXY=""
GORACE=""
GOROOT="/Users/dfc/go"
GOTMPDIR=""
GOTOOLDIR="/Users/dfc/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/by/3gf34_z95zg05cyj744_vhx40000gn/T/go-build891243944=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
```
Daves-MacBook-Pro(~/src/github.com/pkg/errors) % go mod -init -module github.com/pkg/errors
go: creating new go.mod: module github.com/pkg/errors
Daves-MacBook-Pro(~/src/github.com/pkg/errors) % cat go.mod 
module github.com/pkg/errors
Daves-MacBook-Pro(~/src/github.com/pkg/errors) % go mod -verify
go mod: cannot use outside module
```
### What did you expect to see?

Not a failure

### What did you see instead?

All `go mod` commands report
```
go mod: cannot use outside module
```

**Comment by myitcv** [comment]
@davecheney looks like you're running these commands from within your `GOPATH`?

In which case, take a look through @rsc's answer in golang-dev:

https://groups.google.com/d/msg/golang-dev/a5PqQuBljF4/tYBmxfF4BgAJ

You'll need to set `GO111MODULE=on` to force module mode if you want to work with modules inside your `GOPATH`.

**Comment by davecheney** [comment]
Fair enough. Thanks for the answer.

**Comment by myitcv** [comment]
@rsc @bcmills is it worth adding `GO111MODULE` to `go env` to help in these sorts of situations?

Feels like that might be a very common first question we'll ask people.

**Comment by davecheney** [comment]
Maybe a better answer is to expand the error text to explain that when inside gopath you need to set an extra env var.

**Comment by bcmills** [comment]
I suspect we should do both of those things. 🙂

**Comment by FiloSottile** [comment]
We should also show a helpful error for failed builds when a go.mod file was found and modules are off because of GOPATH.

**Comment by bcmills** [comment]
Should be much improved now. Please reopen if you still run into confusing behavior.
