### ISSUE TITLE
doc: add release notes for change in vet printf detection

### ISSUE THREAD

**Issue by myitcv** [golang/go#26372]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version devel +8a330454dc Fri Jul 13 03:53:00 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

No, working with Go tip.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/tmp.sI0jAUcdXy"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282886001=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Not a bug, but a suggestion for a release note.

Discovered whilst trying out the new `go` tool module support, upgrading https://github.com/gobuffalo/buffalo to be a Go module.

```
cd `mktemp -d`
export GOPATH=$PWD
mkdir -p src/example.com/hello
cd src/example.com/hello
cat <<EOD > main.go
package main

import "fmt"

type T struct{}

func (t *T) String(s string, args ...interface{}) string {
    v := s
    if len(args) > 0 {
        v = fmt.Sprintf(s, args...)
    }
    return v
}

func main() {
    var t *T
    t.String("<%=")
}
EOD
go test
```

### What did you expect to see?

A release note at https://tip.golang.org/doc/go1.11 giving details about the new `*printf` detection that now reports the above as an error:

```
# example.com/hello
./main.go:17: T.String format %= has unknown verb =
```

### What did you see instead?

No release notes 😄 

Not critical, but I suspect this will catch out a few people. Buffalo had a number of instances because of the templating language, Plush, it uses.

**/cc** @rsc

**Comment by ianlancetaylor** [comment]
CC @andybons
