### ISSUE TITLE
cmd/go: clarify -getmode=local

### ISSUE THREAD

**Issue by bcmills** [golang/go#26370]
Currently, the `-getmode` flag supports three values: `vendor`, `local`, and the empty string.
`-getmode=vendor` is documented in the output of `go help modules`, but `-getmode=local` is not.

I'm trying to remember exactly what it does. I had thought that it restricted imports and `go get` to the contents of the local module cache, but [this snippet](https://github.com/golang/go/blob/28502b5023b6ddbecf24c68f225762054882ebf5/src/cmd/go/internal/modload/import.go#L149-L151) in `modload.Import` seems to imply that it is further restricted to the active modules in the build list (even if other modules or versions are available in cache).

We should document the intended behavior of `-getmode=local`, and probably add some more tests to verify what happens for imports from cached-but-inactive modules.

(CC: @rsc)

**Comment by nightlyone** [comment]
I would even go as far as disabling this mode as a valid parameter for the release unless it is well defined again, what it does. It is such a good name.
