### ISSUE TITLE
text/scanner: Float tokens allow trailing 'e' or 'E' and sign (but Go literals don't)

### ISSUE THREAD

**Issue by benhoyt** [golang/go#26374]
The documentation for text/scanner says that it "recognizes all literals as defined by the Go language specification". However, it seems to break that and be a little more liberal in that it accepts floating-point literals with a trailing `e` or `E` and no digits. It also allows a trailing `+` or `-` sign after the `e`/`E`. Neither of these are valid Go floating point literals (nor as input to ParseFloat, which seems to match the [Go literal spec](https://golang.org/ref/spec#Floating-point_literals) here).

Here is a Playground link to a small program that reproduces the issue: https://play.golang.org/p/leS1zsI4Rfz

In short, scanning the string `"1.5e 1.5E 1e 1E 1e+ 1e- 1.0 1 1.5z"` gives the following sequence of tokens (third value on each line is whether it's valid according to Go/ParseFloat or not):

```
Float "1.5e" false
Float "1.5E" false
Float "1e" false
Float "1E" false
Float "1e+" false
Float "1e-" false
Float "1.0" true
Int "1" true
Float "1.5" true
Ident "z" false
```

However, what I'd expect according to the text/scanner docs is for the trailing `e`'s and signs to be not included in the float, but parsed as subsequent tokens, like so:

```
Float "1.5" true
Ident "e" false
Float "1.5" true
Ident "E" false
Int "1" true
Ident "e" false
Int "1" true
Ident "E" false
Int "1" true
Ident "e" false
"+" "+" false
Int "1" true
Ident "e" false
"-" "-" false
Float "1.0" true
Int "1" true
Float "1.5" true
Ident "z" false
```

Here's the relevant [scanner.go source code](https://golang.org/src/text/scanner/scanner.go#L367). scanExponent uses scanMantissa, which allows 0 or more digits instead of 1 or more digits (for this case).

I ran into this issue when using text/scanner and then passing the TokenText() return value for Float tokens to ParseFloat, and getting an unexpected error on strings like `1.5e`.

Go version and OS/arch: `go1.10 darwin/amd64`. Though from looking at the code it's not arch- or OS-specific. Yes, the issue reproduces with the latest release.

If folks (@griesemer?) agree that this is a bug, I'd be interested in contributing a fix. However, if it's decided that users may be depending on this behavior (seem unlikely as this apparently hasn't been reported yet -- I searched for issues) and it's too late to change it, then we'll want a documentation fix.

**Comment by benhoyt** [comment]
@ianlancetaylor What investigation does this need? Is it something I could tackle?

**Comment by ianlancetaylor** [comment]
The "investigation" that it needs is exactly the answer to your question in the last paragraph: do people like @griesemer agree that this is a bug?  @griesemer is on vacation this month and will no doubt take a look when he returns.

**Comment by griesemer** [comment]
This does look like a bug to me; and there doesn't seem to be a test expecting these erroneous constants either. If there was any intent behind this at some point, I don't remember.

It seems ok to fix this; I'd be surprised if existing code relies on this, especially because the respective constant literals wouldn't make it through the strconv routines anyway.

The fix might be as simple as:
```Go
diff --git a/src/text/scanner/scanner.go b/src/text/scanner/scanner.go
index 4e76664dc0..893a4edbaf 100644
--- a/src/text/scanner/scanner.go
+++ b/src/text/scanner/scanner.go
@@ -384,6 +384,9 @@ func (s *Scanner) scanExponent(ch rune) rune {
                if ch == '-' || ch == '+' {
                        ch = s.next()
                }
+               if !isDecimal(ch) {
+                       s.error("illegal exponent")
+               }
                ch = s.scanMantissa(ch)
        }
        return ch
```
(plus test cases, etc.)

**Comment by benhoyt** [comment]
Thanks, @griesemer. I'll see about writing up a CL with tests when I get back from vacation in a week or so.

**Comment by benhoyt** [comment]
@griesemer I added the fix you suggested and also tests to match: https://go-review.googlesource.com/c/go/+/129095

One of the things that was a bit unclear to me was how much data should be consumed when an error occurs. For example, parsing `0xg` gives "illegal hexadecimal number" and stops just before the `g`, whereas parsing `0183` gives "illegal octal number" but stops at the end after the 3 ([Playground link](https://play.golang.org/p/mWqrSDoZfGB)). What we have here for the exponent error is simple and greedy (it stops after the `e` and the `+`), which I guess is fine.

**Comment by griesemer** [comment]
@benhoyt The scanner should consume characters as long as they are possibly leading to a valid token, and stop as soon as an error is detected. (I'm not saying this is what happens consistently, but at least that's the idea.)

For `0xg`, `0x` clearly is a valid start, and the `g` is clearly invalid so we don't consume it. For `0183` we only know after looking at the next character if it is valid or not (`0183.` is a valid floating point number), so this seems consistent.
