### ISSUE TITLE
function string() convert different int get same result

### ISSUE THREAD

**Issue by Paladz** [golang/go#26386]
string(55304)==string(55302)
Plz tell me why this happen? 

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Mac, Linux

### What did you do?
string(55304)==string(55302)
Why??????????

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Tell me why it's happening, is it a bug? or what's the reason behind it

**Comment by ALTree** [comment]
`string(<number>)` does **not** convert `number` into its string representation.

Spec (https://golang.org/ref/spec#Conversions):

> Conversions to and from a string type
> Converting a signed or unsigned integer value to a string type yields a string containing the UTF-8 representation of the integer

The fact that this is bad is #3939, labelled go2 since it can't be changed now (because of the Go 1 compatibility promise).
