### ISSUE TITLE
runtime: wasm: all goroutines asleep and no JavaScript callback pending - deadlock

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26382]
I've seen a few trybot flakes on wasm like:

https://storage.googleapis.com/go-build-log/fd762fcb/js-wasm_280bcf2c.log (from wasm-unrelated https://go-review.googlesource.com/c/go/+/123779)

```
ok  	math/bits	1.768s
ok  	math/cmplx	1.762s
ok  	math/rand	4.233s
ok  	mime	1.705s
ok  	mime/multipart	6.236s
ok  	mime/quotedprintable	3.097s
ok  	net	2.596s
error: all goroutines asleep and no JavaScript callback pending - deadlock!
FAIL	net/http	15.608s
2018/07/13 22:17:40 Failed: exit status 1

```

**Comment by xudongzheng** [comment]
I think I ran into the same issue with https://play.golang.org/p/Ymt6QgfYH93. Not sure if I'm underestimating the complexity of the fix.

**Comment by neelance** [comment]
@xudongzheng Your issue is unrelated to the flake above. Please see https://tip.golang.org/pkg/syscall/js/#NewCallback on why it happens.

**Comment by agnivade** [comment]
@kaskavalci - You have successfully repeated the issue in https://github.com/golang/go/issues/26382#issuecomment-409898574. See the comment above.

**Comment by kaskavalci** [comment]
Oh 🤦‍♂️
For someone who is looking for a quick answer, just wrap your request in a go-routine because

>  A blocking callback should therefore explicitly start a new goroutine. 

```go
example := func(i []js.Value) {
	go func() {
		fmt.Println(http.Get("http://localhost:9276/"))
	}()
}
js.Global().Set("example", js.NewCallback(example))
select {}
```

**Comment by FiloSottile** [comment]
@gopherbot please file this to be considered for backport to 1.11.

**Comment by neelance** [comment]
@bradfitz Is there a way to search the trybot logs for this flake?

**Comment by josharian** [comment]
https://github.com/aclements/go-misc/tree/master/greplogs

**Comment by neelance** [comment]
According to the logs, the last time this happened was on 2018/07/19. I'd say we can close this.

**Comment by danaugrs** [comment]
I'm getting a similar error after upgrading from Go 1.12 to 1.13:
```
fatal error: all goroutines are asleep - deadlock!
```

**Comment by FiloSottile** [comment]
@danaugrs Please open a new issue, we don't track closed issues, and that's a pretty generic error.

**Comment by danaugrs** [comment]
@FiloSottile I figured it out, the problem was reading from the channel of a `time.Timer` inside the `requestAnimationFrame` callback. The behavior must have changed from 1.12 to 1.13 but I'm not sure which is correct. I'll open an issue if it turns out to be a blocker for me.

**Comment by pigfox** [comment]
I attempted the solution of wrapping the request in a go-routine.
The same errors appears:
fatal error: all goroutines are asleep - deadlock!
wasm_exec.js:47 goroutine 1 [select (no cases)]:

**go version go1.14.4 linux/amd64**

```
func query(this js.Value, args []js.Value) interface{} {
	var rv interface{}

	c1 := make(chan string)
	go func() {
		c1 <- makeRequest()
	}()

	target:= fmt.Sprintf("%s", args[0]) + "Result"

	select {
	case color := <-c1:
		js.Global().Get("document").Call("getElementById", target).Set("innerHTML", color)
	}
	return rv
}
```
Any pointers?

**Comment by WeiChieh-Chen** [comment]
if use goroutine, how return value to frontend ?

**Comment by loeffel-io** [comment]
this still happens to me with `go version go1.17 darwin/amd64`

```golang
package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"syscall/js"
)

func add(this js.Value, args []js.Value) interface{} {
	resp, err := http.Get("https://jsonplaceholder.typicode.com/posts")
	if err != nil {
		log.Fatalln(err)
	}
	//We Read the response body on the line below.
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}
	//Convert the body to type string
	sb := string(body)
	log.Printf(sb)

	return nil
}

func main() {
	c := make(chan struct{}, 0)
	js.Global().Set("add", js.FuncOf(add))
	<-c
}
```

result: https://github.com/golang/go/issues/26382#issuecomment-416918384

running this in a goroutine works: 

```golang
package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"syscall/js"
)

func add(this js.Value, args []js.Value) interface{} {
	go func() {
		resp, err := http.Get("https://jsonplaceholder.typicode.com/posts")
		if err != nil {
			log.Fatalln(err)
		}
		//We Read the response body on the line below.
		body, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			log.Fatalln(err)
		}
		//Convert the body to type string
		sb := string(body)
		log.Printf(sb)
	}()

	return nil
}

func main() {
	c := make(chan struct{}, 0)
	js.Global().Set("add", js.FuncOf(add))
	<-c
}
```

**Comment by neelance** [comment]
@loeffel-io Your issue is unrelated to the flake above. Please see https://pkg.go.dev/syscall/js@master#FuncOf on why it happens.

**Comment by loeffel-io** [comment]
My fault - thanks! @neelance
