### ISSUE TITLE
cmd/go: mod -sync should trim go.sum

### ISSUE THREAD

**Issue by ainar-g** [golang/go#26381]
### Does this issue reproduce with the latest release?

    go version devel +6f96cf2 Fri Jul 13 22:29:48 2018 +0000 linux/amd64

### What did you do?
```
$ mkdir /tmp/foo && cd /tmp/foo
$ echo 'package foo // import "foo"' > main.go
$ go mod -init
$ go get github.com/lib/pq
$ cat go.sum
github.com/lib/pq v0.0.0-20180523175426-90697d60dd84/go.mod h1:5WUZQaWbwv1U+lTReE5YruASi9Al49XbQIvNi/34Woo=
$ go mod -sync
$ cat go.sum
```

### What did you expect to see?
Nothing.

### What did you see instead?
    github.com/lib/pq v0.0.0-20180523175426-90697d60dd84/go.mod h1:5WUZQaWbwv1U+lTReE5YruASi9Al49XbQIvNi/34Woo=

**Comment by kardianos** [comment]
Files in go.sum are never intended to be removed. It keeps a list of all modules seen.

**Comment by ainar-g** [comment]
That approach (if indeed the defined behaviour) is (1) badly documented, (2) probably wouldn't scale very well, (3) raises questions.

Regarding (1) here is what `go help modules` had to say about `go.sum`:

>The go command *maintains,* in the main module's root directory alongside
>go.mod, a file named go.sum containing the expected cryptographic checksums
>of the content of specific module versions. Each time a *dependency is*
>*used,* its checksum is added to go.sum if missing or else required to match
>the existing entry in go.sum.

I added the emphasis. My assumptions from reading this section are:

* "Maintaining" means adding that is used and removing what is unused
* A dependency is "used" when one of packages in the module imports it.

By (2) I mean that when we consider a project like Hugo, with hundreds of dependencies being added, removed, and updated daily in several branches. `go.sum` would accumulate trash very quickly. (Ideally, `go mod -sync` would remove *any* line that is not a hash of a used package, so that resolving git conflicts is as easy as fixing `go.mod` and running `go mod -sync`.)

By (3) I simply mean that the "Go 1.11 Modules Experiment" comes with a number of tools to support modules in a project. So why not include a tool to maintain `go.sum`? Don't get me wrong, I can write an `awk` script to do that, but why, if almost any project will need something like that?

**Comment by myitcv** [comment]
**/cc** @rsc @bcmills for confirmation of the intended semantics here.

**Comment by FiloSottile** [comment]
I appreciate the fact that `go.sum` is append only. It secures the case of reintroducing a dependency and improves future cross-pollination experiments where hashes are learned from other repositories.

One way to look at this is that `go.sum` is just a way (currently, the only one) to check package integrity, not really bound to `go.mod`. In the future we might have system-wide `go.sum`, or remote auditable services instead.

For projects so big it becomes a problem, there can be an external tool to trim `go.sum`.
