### ISSUE TITLE
html template package renders escaped version of html (unexpected)

### ISSUE THREAD

**Issue by SandroRybarik** [golang/go#26392]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

### What did you do?
```go
// issue.go
package main
import (
	"html/template"
	"log"
	"net/http"
)

var templates = template.Must(template.ParseFiles("view_product.html"))
func RenderTemplate(w http.ResponseWriter, tmpl string, data interface{}) {
	err := templates.Execute(w, data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func controller(w http.ResponseWriter, r *http.Request) {
	viewer.RenderTemplate(w, "view_product", nil)
}
func main() {
	http.HandleFunc("/", controller)
	log.Fatal(http.ListenAndServe(":8080", nil))
}

```
```HTML
// view_product.html
<ul>
    <li>Hello</li>
</ul>
```
### What did you expect to see?
interpreted html by browser:
* Hello

### What did you see instead?
escaped version:
```HTML
<ul>
    <li>Hello</li>
</ul>
```

*But if we add `<h1>Hello</h1>` or `div` to 'view_product.html', browser renders correctly, (tested on chrome, firefox)

view_product.html -- working version which for some reason renders correctly
```HTML
<h1>Hello</h1>
<ul>
    <li>Hello</li>
</ul>
```

There is unexpected behavior, which is not consistent.

**Comment by mvdan** [comment]
Have you checked what output the `html/template.Template` renders to? Templates are simply templates - they do not know how a web browser will render them.

**Comment by carlmjohnson** [comment]
The issue is that the web browser doesn’t know that the page is HTML. You need to set the Content-Type header. Add `w.Header().Set("Content-Type", "text/html")‘. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type and

**Comment by crvv** [comment]
If you don't set `Content-Type` header. Go HTTP server will set it for you. 
https://golang.org/pkg/net/http/#ResponseWriter

> If the Header does not contain a Content-Type line, Write adds a Content-Type set to the result of passing the initial 512 bytes of written data to DetectContentType.

And `DetectContentType` thinks 
```
<h1>Hello</h1>
<ul>
    <li>Hello</li>
</ul>
```
is `text/html`.


But
```
<ul>
    <li>Hello</li>
</ul>
```
is `text/plain`

I don't think this is a bug. HTML should start with `<!DOCTYPE html>`

**Comment by SandroRybarik** [comment]
@crvv @carljohnson
thank you for explanation, that's enough to close this issue
