### ISSUE TITLE
image/png: unexpected behaviour while encoding paletted image with transparency

### ISSUE THREAD

**Issue by prl900** [golang/go#26395]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
...

### What did you do?

This simple program defines a palette with increasing alpha from 0 to 255 for the blue color. A paletted image using this palette is defined with a horizontal gradient from 0 to 255. This image is then encoded as a png on disk.

https://gist.github.com/prl900/b94fc4d71a25185ff962154e5209c563

### What did you expect to see?

![blue-white_gradient](https://user-images.githubusercontent.com/26432237/42743914-abb38e34-890b-11e8-803d-57e92dd65f1e.png)

### What did you see instead?

![test_paletted](https://user-images.githubusercontent.com/26432237/42743877-46db053c-890b-11e8-863c-47074ce9119d.png)

**Comment by nigeltao** [comment]
Your gist has this line:

```
palette[i] = color.RGBA{0x00, 0x00, 0xff, uint8(i)}
```

The `RGBA` should be `NRGBA`. As https://golang.org/pkg/image/color/#RGBA and https://golang.org/pkg/image/color/#NRGBA say, `RGBA` is alpha-premultiplied and that "An alpha-premultiplied color component C has been scaled by alpha (A), so has valid values 0 <= C <= A" and `NRGBA` is non-alpha-premultiplied.
