### ISSUE TITLE
cmd/go: clarify documentation for -replace flag

### ISSUE THREAD

**Issue by komuw** [golang/go#26417]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +b59b42cee8 Tue Jul 17 10:07:18 2018 +0000 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/go"
GOMOD="~/mystuff/meli/go.mod"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/56z0g6pj6dq0njc1n6wccz4r0000gn/T/go-build722725015=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
try to use a go module replacement to point to a local repository

`git clone https://github.com/pkg/errors to a place outside GOPATH`
`in your application's go.mod file add a replace directive to point to the cloned github.com/pkg/errors`
`cat go.mod`
```bash
replace github.com/pkg/errors => ../errors
```
`try to build your application`

### What did you expect to see?
- my application to build succefully without problem(using the cloned errors package)

### What did you see instead?
```bash
go: parsing ../errors/go.mod: open ~/mystuff/errors/go.mod: no such file or directory
go: error loading module requirements
```

However, if I manually add a go.mod file to the cloned errors package
```bash
echo 'module "github.com/pkg/errors"' >> ~/mystuff/errors/go.mod
```
I'm able to build my application using that local errors package.

**Comment by myitcv** [comment]
I think this is answered by https://github.com/golang/go/issues/25739#issuecomment-395256639. Please shout if not.

**Comment by myitcv** [comment]
Actually, @rsc @bcmills might we want to slightly enhance the `go help mod` documentation here?

```
The -replace=old@v=new@w and -dropreplace=old@v flags
add and drop a replacement of the given module path and version pair.
If the @v in old@v is omitted, the replacement applies to all versions
with the old module path. If the @v in new@v is omitted, the
new path should be a directory on the local system, not a module path.
Note that -replace overrides any existing replacements for old@v.
```

to read:

```
... the new path should be a directory on the local system that contains
a module, ...
```

or some such?

**Comment by komuw** [comment]
yeah, that would be helpful.

also the documentation has a typo( I think). it says
```bash
The -replace=old@v=new@w ...
```
and further down it says
```bash
If the @v in new@v is omitted,
```

I believe the former should read;
```bash
If the @w in new@w is omitted
```

**Comment by bcmills** [comment]
It should read, `If the @v in old@v is omitted,`.

**Comment by bcmills** [comment]
And maybe, `the new path should be a source directory for the module on the local system, not a module path`?

**Comment by komuw** [comment]
@bcmills 
I'm talking about this part;
```bash
If the @v in new@v is omitted, the new path should be a directory on the local system
```

shouldn't it read?
```bash
If the @w in new@w is omitted, the new path should be a directory on the local system
```

**Comment by mwf** [comment]
```
$ go mod -replace foo/bar
go mod: -replace=foo/bar: need old@v=new[@v] (missing =)
```
As we now allow `-replace foo/bar=../` without specifying **old** version - let's fix the error message accordingly.

`old@v=new[@v]` -> `old[@v]=new[@v]`
