### ISSUE TITLE
access: vangent@gmail.com (gerrit)

### ISSUE THREAD

**Issue by vangent** [golang/go#26429]
See https://golang.org/wiki/GerritAccess

 https://go-review.googlesource.com/#/admin/groups/1030,members

(my Google email is rvangent@google.com, but I think what this wants is my github account, which is vangent@gmail.com).

**Comment by davecheney** [comment]
Duplicate of #26428

**Comment by mvdan** [comment]
@davecheney it looks like the other issue is for github, and this one for gerrit. I'm not sure if the docs specify to open joint or separate issues.

**Comment by davecheney** [comment]
My mistake, I'll reopen this issue.

**Comment by vangent** [comment]
go-cloud is not using Gerrit, so closing this.
