### ISSUE TITLE
cmd/go: go clean -cache runs module load

### ISSUE THREAD

**Issue by saibing** [golang/go#26432]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +ce09ce4 Wed Jul 18 01:16:24 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
```bash
baas@cae-yun-03:~/bingo/bingo [develop]$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/data1/baas/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data1/baas/git/go"
GOPROXY="http://10.75.203.36:9090"
GORACE=""
GOROOT="/data1/baas/my/go"
GOTMPDIR=""
GOTOOLDIR="/data1/baas/my/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data1/baas/bingo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build793325640=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?

```bash
$ export GO111MODULE=on
$ go clean -cache
```

my go.mod as follow:
```go
module rnd-isource.huawei.com/baas/bingo
```

### What did you expect to see?

no any error

### What did you see instead?

```bash
baas@cae-yun-03:~/bingo/bingo [develop]$ go clean -cache
go: finding rnd-isource.huawei.com/baas/bingo/bingo latest
go: import "rnd-isource.huawei.com/baas/bingo/bingo": cannot find module providing package rnd-isource.huawei.com/baas/bingo/bingo
```

**Comment by rsc** [comment]
Nice. The problem is that "go clean" originally meant clean the current directory, and so as we've added flags we've kept the original behavior too. But in the case of modules the load is fairly expensive. We should either make the load use -getmode=noauto (#26361) or just skip it entirely when there are flags. Probably the former, once that exists.
