### ISSUE TITLE
go/build: Import() fails for packages using modules and version greater than 1

### ISSUE THREAD

**Issue by joshuarubin** [golang/go#26433]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
tip

### Does this issue reproduce with the latest release?
n/a

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?

`build.Import()` returns an error when trying to load a package from a module with version greater than 1.

```
cannot find package "github.com/foo/bar/v2" in any of:
...
```

I got to this indirectly through this:

```
import (
	"go/ast"
	"go/importer"
	"go/types"
)

func foo() {
	cfg := types.Config{
		Importer: importer.For("source", nil),
	}
	_, err := cfg.Check(...)
}
```

Where `cfg.Check` returned:
```
could not import github.com/foo/bar/v2 (cannot find package "github.com/foo/bar/v2" in any of:
...
```

### What did you expect to see?
The `go/*` packages in the stdlib work the same way as vgo with the ability to load packages from versioned modules.

### What did you see instead?
The errors listed above

**Comment by bcmills** [comment]
CC: @alandonovan @ianthehat @rsc

**Comment by rsc** [comment]
The answer is to use golang.org/x/tools/go/packages, under development now. If you find any problems using that package, please file new issues against it. Thanks very much.

**Comment by rsc** [comment]
I take it back - that's the long term answer but we can provide a short-term answer. I reopened this as #26504.
