### ISSUE TITLE
Advance bufio.Scanner when ErrTooLong is set.

### ISSUE THREAD

**Issue by jackxbritton** [golang/go#26431]
### What version of Go are you using (`go version`)?

`go version go1.10.2 darwin/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jack/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jack/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/st/1lzqj5wx7k7_8whfzn9w3dbm0000gn/T/go-build321294236=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

https://play.golang.org/p/COhZ7cIwMTL

### What did you expect to see?

I expected the scanner to advance, even when returning `bufio.ErrTooLong`.

### What did you see instead?

The scanner doesn't advance, so the program gets stuck in the loop.

### Comment.

This change would not affect existing code -- `Scan()` would still return `false` on an error, and the scanner error would still get set. But it would give devs the ability to skip very long tokens in readers if they wanted to.

**Comment by jackxbritton** [comment]
I've heard that breaking backwards compatibility will happen in version 2. Is that true? What are the next steps to take here?

**Comment by ianlancetaylor** [comment]
@jackxbritton Write a proposal for the change in behavior as described at https://github.com/golang/proposal/blob/master/README.md .

It sounds like the current code is behaving as documented, so closing this issue.  Thanks.

**Comment by outcoldman** [comment]
For folks who are looking for solution, it can be as simple, as copying ReadBytes function and changing it to something like


```

// Copy of bufio.Reader.ReadBytes but with maxSize
func ReadBytesWithLimit(b *bufio.Reader, delim byte, maxSize int) ([]byte, error) {
	// Use ReadSlice to look for array,
	// accumulating full buffers.

	cSize := 0

	var frag []byte
	var full [][]byte
	var err error
	for {
		var e error
		frag, e = b.ReadSlice(delim)
		if e == nil { // got final fragment
			break
		}

		if e != bufio.ErrBufferFull { // unexpected error
			err = e
			break
		}

		if cSize+b.Size() >= maxSize { // getting over the size
			err = bufio.ErrBufferFull
			break
		}

		cSize += len(frag)

		// Make a copy of the buffer.
		buf := make([]byte, len(frag))
		copy(buf, frag)
		full = append(full, buf)
	}

	// Allocate new buffer to hold the full pieces and the fragment.
	n := 0
	for i := range full {
		n += len(full[i])
	}
	n += len(frag)

	// Copy full pieces and fragment in.
	buf := make([]byte, n)
	n = 0
	for i := range full {
		n += copy(buf[n:], full[i])
	}
	copy(buf[n:], frag)
	return buf, err
}
```

I guess similar change can be done to the standard library to add methods like `ReadBytesWithLimit` and `ReadStringWithLimit`
