### ISSUE TITLE
runtime: add more verbose comments in Caller method

### ISSUE THREAD

**Issue by minaevmike** [golang/go#26437]
https://github.com/golang/go/blob/master/src/runtime/extern.go#L179
`1+skip-1` makes no sense, i think i can be converted to `skip` or some comments can be added to discribe why we make `+1-1`.

**Comment by ianlancetaylor** [comment]
For the record, the `-1` was added in https://golang.org/cl/4810054, when the code was changed to ask for two PC values.  At this point we should probably just drop it.

**Comment by wingyplus** [comment]
So we can remove +1-1 in L179. Am I right?

**Comment by ianlancetaylor** [comment]
Yes.
