### ISSUE TITLE
net/http/httptest: ResponseRecorder.Result comment gives incorrect guarantee about ResponseRecorder.Body non-nil-ness

### ISSUE THREAD

**Issue by adam-p** [golang/go#26442]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10.3

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Compare the `ResponseRecorder.Result` [documentation/comment](https://github.com/golang/go/blob/311ec41b5a394e53550c3feed2164b8f9930b5be/src/net/http/httptest/recorder.go#L162-L163)...
```
// The Response.Body is guaranteed to be non-nil and Body.Read call is
// guaranteed to not return any error other than io.EOF.
```

...to actual [behaviour](https://github.com/golang/go/blob/311ec41b5a394e53550c3feed2164b8f9930b5be/src/net/http/httptest/recorder.go#L185-L187):
```
if rw.Body != nil {
	res.Body = ioutil.NopCloser(bytes.NewReader(rw.Body.Bytes()))
}
...and then no case for when rw.Body _is_ nil...
```

It seems that guarantee doesn't apply if `Response.Body` was nil to begin with.

**Comment by jackxbritton** [comment]
I'll add a case for this.
