### ISSUE TITLE
x/net/http2: clientTrace has no field or method WroteHeaderField

### ISSUE THREAD

**Issue by kamilsk** [golang/go#26443]
### What version of Go are you using (`go version`)?

go version go1.11beta1 linux/amd64

### Does this issue reproduce with the latest release?

No, because it is related only to Go 1.11 (which beta) (https://github.com/golang/net/blob/master/http2/go111.go).

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.11beta1.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.11beta1.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build968009971=/tmp/go-build -gno-record-gcc-switches"
VGOMODROOT=""
```

https://travis-ci.org/kamilsk/click/jobs/405409835

### What did you do?

Import the latest `golang.org/x/net` and run tests on go1.11beta1.

### What did you expect to see?

Tests passed.

### What did you see instead?

```
vendor/golang.org/x/net/http2/go111.go:12:30: trace.WroteHeaderField undefined (type *clientTrace has no field or method WroteHeaderField)
vendor/golang.org/x/net/http2/go111.go:16:26: trace.WroteHeaderField undefined (type *clientTrace has no field or method WroteHeaderField)
vendor/golang.org/x/net/http2/go111.go:17:8: trace.WroteHeaderField undefined (type *clientTrace has no field or method WroteHeaderField)
```

As I see https://github.com/golang/go/blob/a12c1f26e4cc602dae62ec065a237172a5b8f926/src/net/http/httptrace/trace.go#L80-L159 `ClientTrace` doesn't have `WroteHeaderField` method.

**Comment by meirf** [comment]
https://github.com/golang/go/issues/19761 shows the history of the related changes. 1.11beta was released on June 26. The trace api change was merged on June 27. So you’ll need a release later than beta1 or use tip.

**Comment by kamilsk** [comment]
sorry, I see it on master https://github.com/golang/go/blame/master/src/net/http/httptrace/trace.go#L148. my fault

**Comment by ricketybridge** [comment]
Rolling back to 10.3 worked for me.
