### ISSUE TITLE
cmd/go: the go command converts uppercase characters to !+ lowercase characters.

### ISSUE THREAD

**Issue by saibing** [golang/go#26456]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +c54bc34 Thu Jul 19 00:23:07 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```bash
baas@SZX1000428520:~/git/go/src/go-langserver [master]$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/baas/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/baas/git/go"
GOPROXY="http://10.75.203.36:9090"
GORACE=""
GOROOT="/home/baas/my/go"
GOTMPDIR=""
GOTOOLDIR="/home/baas/my/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/baas/git/go/src/go-langserver/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build071732067=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
I am using the go 1.11 moudle function, I developed a [go module proxy](https://github.com/saibing/vgo) and used it by setting the environment variable GOPROXY

### What did you expect to see?

the go module proxy can work well.

### What did you see instead?
- client

```bash
$ go get github.com/SimpleMessageNotification/smn-sdk-go@latest
go get github.com/SimpleMessageNotification/smn-sdk-go@latest: cannot find module providing package github.com/SimpleMessageNotification/smn-sdk-go
```

- server

```bash
$ ./vgoproxy
0719 10:48:40.33 go config:
{
   "gopath": "/data1/baas/.gomod",
   "http": [
      "code.huawei.com",
      "rnd-isource.huawei.com",
      "rnd-github.huawei.com"
   ],
   "replace": {},
   "sortKeys": null
}
0719 10:48:40.33 start go proxy server at :9090
0719 10:49:23.565 GET /github.com/!simple!message!notification/smn-sdk-go/@v/list from 100.101.229.133:47174
0719 10:49:23.565 new url /github.com/!simple!message!notification/smn-sdk-go/@v/list
0719 10:49:23.566 go: list version failed: invalid github.com/ import path "github.com/!simple!message!notification/smn-sdk-go"
0719 10:49:23.58 GET /github.com/!simple!message!notification/@v/list from 100.101.229.133:47174
0719 10:49:23.58 new url /github.com/!simple!message!notification/@v/list
0719 10:49:23.58 go: list version failed: invalid github.com/ import path "github.com/!simple!message!notification"
0719 10:49:23.591 GET /github.com/@v/list from 100.101.229.133:47174
0719 10:49:23.591 new url /github.com/@v/list
0719 10:49:24.718 go: list version failed: unrecognized import path "github.com" (parse https://github.com?go-get=1: no go-import meta tags ())
```

**Comment by oiooj** [comment]
As @magical said, this appears to be working as intended. You need to decode the path before you use it.

https://github.com/golang/go/blob/c54bc3448390d4ae4495d6d2c03c9dd4111b08f1/src/cmd/go/internal/module/module.go#L455

**Comment by saibing** [comment]
@magical @magical 

Thank you very much. 

github.com/golang/vgo does not sync the latest code

**Comment by magical** [comment]
> github.com/golang/vgo does not sync the latest code

Correct. Per Russ's recent email to golang-dev,

> Work on the module support will now be done exclusively in the main repo. We will automatically export the main repo to the x/vgo repo when we have a snapshot we want to make available to people using "vgo".

https://groups.google.com/forum/#!topic/golang-dev/a5PqQuBljF4
