### ISSUE TITLE
x/tools/cmd/goyacc: "DO NOT EDIT" header missing trailing newline

### ISSUE THREAD

**Issue by jim-minter** [golang/go#26478]
Since https://github.com/golang/go/issues/26158 / https://golang.org/cl/122095 / goyacc adds a "DO NOT EDIT" header.  This is missing a trailing newline.  It breaks generations of the form

```
%{
package foo
%}
```

because the output becomes
```
// Code generated by goyacc -l -o foo.go -v /dev/null foo.y. DO NOT EDIT.package foo
```

when it should be
```
// Code generated by goyacc -l -o foo.go -v /dev/null foo.y. DO NOT EDIT.
package foo
```

Workaround is to add a new line
```
%{

package foo
%}
```
but it's pretty dumb to have to do that.

**Comment by jim-minter** [comment]
@kwoodson @kargakis fyi

**Comment by mvdan** [comment]
cc @vishen
