### ISSUE TITLE
cmd/go: short tests are not short enough

### ISSUE THREAD

**Issue by rsc** [golang/go#26472]
Running all.bash (which does go test -short std cmd), my target is usually that individual tests should run in under 1 second.

The cmd/go tests will never reach this target - cmd/go does more than perhaps the entire standard library combined, so it's fine to take more than 1 second. But my usual target is to keep it below 30s, if not 20s. Right now it's at 76s. We should keep bringing that down.

Converting more tests to scripts may help.

**Comment by oryanmoshe** [comment]
Would love to give it a shot, can you please explain what
> Converting more tests to scripts
Mean?

**Comment by bcmills** [comment]
See [`src/cmd/go/testdata/script`](https://github.com/golang/go/tree/master/src/cmd/go/testdata/script).

(The `.txt` files are pretty self-explanatory, but the `README` contains more detail about the format and supported commands.)

**Comment by shivakumargn** [comment]
There are several cmd/go tests in go_test.go. Will submit CL for three of the most time consuming tests listed below. Additionally, will make them non-short.

```
TestCpuprofileTwice (8.55s)
TestCoverpkgAllRuntime (27.87s)
TestAtomicCoverpkgAll (28.72s)
```

**Comment by iWdGo** [comment]
cmd/go times out on my Windows 10 but I noticed that `-vet off` could be set. During distribution, running vet has limited value and it is tested separately anyway. The fix seems elementary.

**Comment by bcmills** [comment]
We're currently at `37s` for `go test -short cmd/go` on my workstation. Getting better, but still not quite at the goal.

**Comment by bcmills** [comment]
As of [CL 267883](https://golang.org/cl/267883), we're back down to ~25s end-to-end wall time for the test on my workstation.

```
~/go-review/src$ time go test -short cmd/go
ok      cmd/go  19.888s

real    0m25.565s
user    1m15.674s
sys     0m25.297s
```

I'm going to close this issue as “resolved enough”, but we can of course keep improving the tests afterward.
