### ISSUE TITLE
cmd/go: `go test all` runs tests from std packages

### ISSUE THREAD

**Issue by mwf** [golang/go#26482]
### What version of Go are you using (`go version`)?
Latest go devel: `go version devel +d278f09333 Thu Jul 19 05:40:37 2018 +0000 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
cd `mktemp -d`
go mod -init -module=example.com/test
cat <<EOD > main_test.go
package main

import "testing"

func Test(t *testing.T) {}
EOD
go test all
```

### What did you expect to see?

The only project and dependency tests should run as described in https://research.swtch.com/vgo-tour

### What did you see instead?

Std lib tests are running. 
```
$ go test all
ok  	example.com/test	(cached)
ok  	testing	(cached)
ok  	bytes	2.515s
ok  	errors	(cached)
ok  	flag	0.037s
ok  	fmt	(cached)
?   	internal/race	[no test files]
ok  	io	(cached)
^Csignal: interrupt
```

**Comment by mvdan** [comment]
Seems like a duplicate of #26317.

**Comment by mwf** [comment]
Thanks! Didn't manage to find it, closing.
