### ISSUE TITLE
cmd/go: `go run` produces indirect dependencies in go.mod

### ISSUE THREAD

**Issue by mwf** [golang/go#26483]
### What version of Go are you using (`go version`)?
Latest go devel: `go version devel +d278f09333 Thu Jul 19 05:40:37 2018 +0000 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
cd `mktemp -d`
curl -sS https://swtch.com/hello.go >hello.go
go mod -init -module=example.com/test
go run hello.go
cat go.mod
```

### What did you expect to see?

go.mod
```
module example.com/test

require rsc.io/quote v1.5.2
```

### What did you see instead?

```
module example.com/test

require rsc.io/quote v1.5.2 // indirect
```

It's OK to see `// indirect` if we use `go get rsc.io/quote` but it's a little bit strange to see this artifact after `go run`. 

I believe `go run` should work exactly like `go build` and resolve the imports with `go mod -sync` implicitly.

**Comment by bcmills** [comment]
> I believe `go run` should work exactly like `go build` and resolve the imports with `go mod -sync` implicitly.

Note that `go build` does not do the same thing as `go mod -sync`: it will add modules as needed (because that can be done locally), but won't remove them (because that requires a broader analysis of transitive imports).

**Comment by mwf** [comment]
Oh, sure, I forgot about this difference :)

My point is it's better for `go run` to behave like `go build` as everyone assume it.

**Comment by bcmills** [comment]
`go run` allows you to run files that are not actually part of the package in normal use: for example, consider `src/cmd/go/testdata/addmod.go`:
https://github.com/golang/go/blob/c814ac44c0571f844718f07aa52afa47e37fb1ed/src/cmd/go/testdata/addmod.go#L5

It seems reasonable to update the `go.mod` file with whatever you needed to actually build those files, but they really are “indirect”, in the sense that they are not included by any possible build that imports packages from your module. If you happened to run a file that is also part of a package, `go mod -sync` should remove the `// indirect` comment. (If that doesn't happen today, please reopen.)

**Comment by mwf** [comment]
Perfectly makes sense, thank you!
