### ISSUE TITLE
gccgo: incorrect order of evaluation

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#26495]
This program should print `0`.  When built with current gccgo, it prints `1`.

The immediate problem is that the convert_shortcuts pass moves the function calls to `FV1` and `FV2` out of line so that they are executed before the call to `F`.

CC @cherrymui @thanm 

```Go
package main

type S struct{ a [16]string }

var V1, V2 S

func FV1() S { return V1 }

func FV2() S { return V2 }

func F() int {
	V1 = S{[16]string{"hi"}}
	return 0
}

func G(f bool) int {
	if f {
		return 1
	}
	return 0
}

func H() int {
	return F() + G(FV1() == FV2())
}

func main() {
	println(H())
}
```

**Comment by go101** [comment]
related: https://github.com/golang/go/issues/24448
