### ISSUE TITLE
cmd/go: misleading error message with mixed named and unnamed return values

### ISSUE THREAD

**Issue by opennota** [golang/go#26493]
### What version of Go are you using (`go version`)?

go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

I tried to `go build` the following file:

```
package a

func f() (int, int, named int) {
	return 0, 0, 0
}
```

### What did you expect to see?

Something like

```
./a.go:3:27: mixed named and unnamed return values
```

### What did you see instead?

```
./a.go:3:27: duplicate argument int
```

**Comment by bcmills** [comment]
The error message is correct. You're declaring three named integer return values, with the names `int`, `int`, and `named` respectively.
https://play.golang.org/p/I6m0NMX5f_M
