### ISSUE TITLE
cmd/go: get is broken, old git cannot accept --no-show-signature parameter

### ISSUE THREAD

**Issue by menems** [golang/go#26501]
### What version of Go are you using (`go version`)?
```bash
$ go version
go version go1.11beta2 darwin/amd64
```

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/blaz/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/blaz/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/blaz/src/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2r/wpj58rp17s56swkgt8c2r5nm0000gn/T/go-build234628957=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

A simple main.go with a dependency to test `go mod`

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
)

func main() {

	r := chi.NewRouter()
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hey"))
	})

	http.ListenAndServe(":9999", r)
}
```

### What did you expect to see?
no error on run

### What did you see instead?
```bash
$ go run -v main.go
go: finding github.com/go-chi/chi v3.3.2+incompatible
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go: import "github.com/go-chi/chi": cannot find module providing package github.com/go-chi/chi
```

thanks

I don't have this error on linux box

**Comment by bcmills** [comment]
This is a side-effect of https://golang.org/cl/123958 (the fix that went in for #26388).

CC @magiconair @rsc @dsymonds @oiooj

**Comment by rudis** [comment]
I stumbled over the same issue and I found the fact that go doesn't report anything about a failing command troublesome. I needed to use `strace` to figure out what's going on because even with `-v` nothing was printed about the failing command.

If possible please also extend `-v`'s output to include for example failing commands to help debugging such issues.

**Comment by rudis** [comment]
A possible fix for the original issue could be to use `-c log.showsignature=false` instead of `--no-show-signature` which works fine even on older Git versions

**Comment by ysmolsky** [comment]
-c paramater in "git log" means something different: https://git-scm.com/docs/git-log/2.6.5#git-log--c

--no-show-signature was introduced in git 2.10.0, roughly 2 years ago.

**Comment by oiooj** [comment]
git -c log.showsignature=false log ?

**Comment by zegl** [comment]
@ysmolsky This would be a parameter to `git`, not to `git-log`: https://git-scm.com/docs/git#git--cltnamegtltvaluegt

**Comment by trashhalo** [comment]
@ysmolsky 
```
@ysmolsky ysmolsky ... beta2 on osx to cmd/go: get does not work with old git 3 days ago

--no-show-signature was introduced in git 2.10.0, roughly 2 years ago.
```
Linux distros have long term support but hold back minor releases from users. Example https://packages.ubuntu.com/search?keywords=git on ubuntu unless you are on the latest LTS that was released April 26th, 2018 then you are on this "old" version of git.

**Comment by magiconair** [comment]
Oh wow. Sorry for this. Was moving across countries. Would have responded sooner otherwise. :(

**Comment by rogpeppe** [comment]
I encountered this issue today (I'm using a stock version of Ubuntu 16.04). It's made harder to diagnose by the fact that this TODO from src/cmd/go/internal/modload.go remains unaddressed:

	// TODO(rsc): It would be nice to return a specific error encountered
	// during the loop above if possible, but it's not clear how to pick
	// out the right one.

This means that we don't get to see the actual error encountered (`unknown revision refs/tags/v1.0.1`) in my case.

My git version is 2.7.4.

**Comment by trashhalo** [comment]
Im looking at the CL https://go-review.googlesource.com/c/go/+/125315

It looks like it just changes the param it sends to git without any test or CI changes.

Shouldn't this be paired with a test update so we can avoid shipping a bug that is this breaking in the future?

Example -- pin git in the CI environment to 2.7.4 (current git on ubuntu 16) so if someone introduces a change that depends on a new git feature it bombs before merging.

**Comment by rsc** [comment]
Sorry, we're simply not set up to test against all specific git versions. We depend on finding a sequence of commands that works with all git versions and sticking with it.
