### ISSUE TITLE
x/tools/go/packages: cannot specify build tags in Options

### ISSUE THREAD

**Issue by zombiezen** [golang/go#26509]
AFAICT, [`golang.org/x/tools/go/packages`](https://godoc.org/golang.org/x/tools/go/packages) does not provide any way to set what build tags are being used when finding files for the package.

/cc @ianthehat

**Comment by suzmue** [comment]
Fixed by golang.org/cl/125302

Build tags can be passed to golang.org/x/tools/go/packages by adding the "-tags" flag to Config.Flags
