### ISSUE TITLE
Go mod

### ISSUE THREAD

**Issue by jbrodriguez** [golang/go#26515]
I like the concept behind what was previously known as vgo, I'm pretty sure it's called go modules now (I may be wrong).

But there are at least two rough edges I'd like to bring forward:

(1) Dissension with the community
(2) Dissension within golang

The dissension is about some key decisions being made about the general forward path of the initiative.

It involves very knowledegeable people from the community (1) and very knowledgeable people from the inside (2).

Some are deep core issues, some are very trivial issues.

As a (small) go developer, it makes me take exception to the current course of actions: looks like we're in the middle of a (benevolent) dictatorship.

I don't know if this sponsored by higher ups, but I definitely don't like it.

I will start a deep dive on Rust, Crystal and Pony.

**Comment by ALTree** [comment]
> Dissension

Compromise is not always possible. If option A and option B are mutually exclusive, the only three possible courses of action are implementing A, implementing B, and doing nothing. 

> looks like we're in the middle of a (benevolent) dictatorship.

Which is a widely used form of government in programming languages communities. 

> I will start a deep dive on Rust, Crystal and Pony.

Those are all very interesting languages. You should definitely check them out.

**Comment by bcmills** [comment]
As @ianlancetaylor notes, this discussion is probably better suited to the mailing list: issues in the issue tracker need to be actionable.
