### ISSUE TITLE
Go 1.11beta2 and vgo:devel +88c76dcbab fails to fetch modules

### ISSUE THREAD

**Issue by vendion** [golang/go#26511]
### What version of Go are you using (`go version`)?
I've tested with various different configurations (detailed below) to try and narrow this down

go version go1.11beta2 linux/amd64 vgo:devel +88c76dcbab
go version go1.10.3 linux/amd64 vgo:devel +88c76dcbab
go version go1.10.3 linux/amd64 go:2018-02-20.1 (Git SHA cc75ec08d5ecfc4072bcefc2c696d1c30af692b9)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
From Go 1.10.3
```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/utiliflex/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/utiliflex/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build465742758=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Configuration B (Updated go, no vgo changes)

1.  Grabbed Go1.11Beta2 binaries for linux/amd64 from golang.org and set it up on my CI server.
2. Updated my CI configuration for a project changing `vgo` to `go`
3. Pushed updated CI config to my GitLab server
4. Watched tests fail because it wasn't able to fetch modules

Configuration B (Updated go, updated vgo)

1. While leaving the installed version of Go at 1.11beta2 I manually updated vgo `go get -u golang.org/x/vgo) to commit 88c76dcbab and tried again
2. Updated my CI configuration for same project changing `go` back to `vgo`
3. Push changes to GitLab server
4. Watched as tests still failed due to same error.

Configuration C (Downgrade go to 1.10.3, recomplied vgo)

1. Grabbed the linux/amd64 binaries from golang.org and downgraded my go install to it, then recompiled vgo at the same commit
2. Forced GitLab CI to retry last pipeline
3. Watched as tests continue to fail with same error.

Configuration D (Keep go at 1.10.3, downgrade vgo)

1. Under my _$GOPATH/src/golang.org/x/vgo_ directory I went back one commit (to cc75ec08d5ecfc4072bcefc2c696d1c30af692b9) and built `vgo` there
2. Forced GitLab CI to retry last pipeline
3. Watched vgo successfully fetch my 3rd-party modules as expected.

### What did you expect to see?

I expected to see my modules be successfully fetched
```
go: finding github.com/naoina/toml v0.1.1
go: finding go.uber.org/multierr v1.1.0
go: finding github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: finding github.com/naoina/go-stringutil v0.1.0
go: finding go.uber.org/zap v1.8.0
go: finding github.com/mattn/go-sqlite3 v1.9.0
go: finding go.uber.org/atomic v1.3.2
go: downloading go.uber.org/zap v1.8.0
go: downloading github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/naoina/toml v0.1.1
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/mattn/go-sqlite3 v1.9.0
```
(Output from configuration D)

### What did you see instead?

```
go: finding github.com/naoina/toml v0.1.1
go: finding github.com/naoina/go-stringutil v0.1.0
go: finding github.com/mattn/go-sqlite3 v1.9.0
go: finding github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: github.com/naoina/toml@v0.1.1: unknown revision refs/tags/v0.1.1
go: github.com/naoina/go-stringutil@v0.1.0: unknown revision refs/tags/v0.1.0
go: github.com/mattn/go-sqlite3@v1.9.0: unknown revision refs/tags/v1.9.0
go: finding go.uber.org/multierr v1.1.0
go: go.uber.org/multierr@v1.1.0: unknown revision refs/tags/v1.1.0
go: finding go.uber.org/zap v1.8.0
go: finding go.uber.org/atomic v1.3.2
go: go.uber.org/zap@v1.8.0: unknown revision refs/tags/v1.8.0
go: go.uber.org/atomic@v1.3.2: unknown revision refs/tags/v1.3.2
go: github.com/pborman/uuid@v0.0.0-20180122190007-c65b2f87fee3: unknown revision c65b2f87fee37d1c7854c9164a450713c28d50cd
```

Output was the same for configurations A-C

**Comment by ysmolsky** [comment]
Do you have an old git < 2.10?  If so see #26501

**Comment by bcmills** [comment]
Closing as duplicate. Please reopen if this is still an issue after #26501 is fixed.
