### ISSUE TITLE
cmd/go: go 1.11 beta2 linux unable to go get

### ISSUE THREAD

**Issue by trashhalo** [golang/go#26525]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11beta2 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stephen/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/stephen/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/stephen/dev/wall/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build886551842=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
downloaded beta2 on my linux box went to go get something. I cant seem to get any package.

### What did you expect to see?
I expected go get vgo.

### What did you see instead?
```
➜  wall go get -u golang.org/x/vgo
go: finding golang.org/x/vgo latest
go get golang.org/x/vgo: cannot find module providing package golang.org/x/vgo
```

**Comment by trashhalo** [comment]
Seems to be related to being in a directory with a go.mod
I can cd out of that directory and go get stuff. but if I am in it, nothing installs.

**Comment by davecheney** [comment]
Hmm. My uneducated guess is the module behaviour is stuck on. Do you have GO111MODULE set in your environment?

**Comment by trashhalo** [comment]
Not that I can see. The project was a module project. So it makes sense to try and use modules. Root issue seems to be `cannot find module providing package` when doing installs with module behavior turned on. Latest vgo seems to have the same problem. I switched the repo back to gopath/dep for now to keep moving.

**Comment by trashhalo** [comment]
@henryykt looks like thats its. 2.7.2. closing as dupe.

**Comment by nerdDan** [comment]
@henryykt My git version is new but still get this issue.

```
~/g/n/r/s/server (master↓1|●6) $ git --version
git version 2.19.2
~/g/n/r/s/server (master↓1|●6) $ go build
go: finding github.com/dgraph-io/badger/skl latest
go: finding github.com/dgraph-io/badger/y latest
go: finding github.com/dgraph-io/badger/protos latest
go: finding github.com/dgraph-io/badger/table latest
go: finding github.com/dgraph-io/badger/options latest
/home/dan/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/db.go:31:2: unknown import path "github.com/dgraph-io/badger/options": cannot find module providing package github.com/dgraph-io/badger/options
/home/dan/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:28:2: unknown import path "github.com/dgraph-io/badger/protos": cannot find module providing package github.com/dgraph-io/badger/protos
/home/dan/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/db.go:35:2: unknown import path "github.com/dgraph-io/badger/skl": cannot find module providing package github.com/dgraph-io/badger/skl
/home/dan/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/compaction.go:28:2: unknown import path "github.com/dgraph-io/badger/table": cannot find module providing package github.com/dgraph-io/badger/table
/home/dan/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:26:2: unknown import path "github.com/dgraph-io/badger/y": cannot find module providing package github.com/dgraph-io/badger/y
```
