### ISSUE TITLE
mime: ParseMediaType rejects valid boundaries

### ISSUE THREAD

**Issue by crawshaw** [golang/go#26521]
```
contentType := "multipart/alternative; boundary=(boundary)"
_, _, err := mime.ParseMediaType(contentType)

// err = mime: invalid media parameter
```

https://play.golang.org/p/tC-Ri26iiTo

Looking at RFC 2046, parentheses are valid boundary characters:

```
boundary := 0*69<bchars> bcharsnospace
bchars := bcharsnospace / " "
bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
                 "+" / "_" / "," / "-" / "." /
                 "/" / ":" / "=" / "?"
```

https://tools.ietf.org/html/rfc2046#section-5.1.1:

Indeed, the `SetBoundary` function in the multipart package checks the boundary is valid, and explicitly lets '(' and ')' pass through.

If someone else double-checks my work and confirms this is a bug, I'm happy to fix it.

**Comment by FMNSSun** [comment]
RFC 2045 mentions:

```
token := 1*<any (US-ASCII) CHAR except SPACE, CTLs,
                 or tspecials>

     tspecials :=  "(" / ")" / "<" / ">" / "@" /
                   "," / ";" / ":" / "\" / <">
                   "/" / "[" / "]" / "?" / "="
                   ; Must be in quoted-string,
                   ; to use within parameter values
```

according to RFC2045 special characters are only allowed within quoted-strings.

**Comment by crawshaw** [comment]
Thanks @FMNSSun. Closing as not-a-bug.

**Comment by FMNSSun** [comment]
Although it looks like there's not always quotes added in the multipart package:

```
// FormDataContentType returns the Content-Type for an HTTP
// multipart/form-data with this Writer's Boundary.
func (w *Writer) FormDataContentType() string {
	return "multipart/form-data; boundary=" + w.boundary
}
```

So it might be that FormDataContentType returns invalid parameters according to RFC 2045? Might be worth re-opening (maybe another issue) and someone else have a look at this because I'm just a random person on the internet.
