### ISSUE TITLE
runtime: out of memory while executing make.bash

### ISSUE THREAD

**Issue by alevchuk** [golang/go#26523]
Master (go1.11) build process is using more memory than go1.10.3

I was able to build go1.10.3 (June 6) on ARMv6 with 433 MB of RAM (Raspbery Pi Zero W) 
Yet, with the latest checkout of 48c7973 (July 10) the build crashes with

```
# com/compile/internal/ssa
fatal error: runtime: out of memory
```

The regression was introduces somewhere in the range from June 6 to July 10.

### What version of Go are you using (`go version`)?

48c7973 - bad version
[go1.10.3](https://github.com/golang/go/tree/go1.10.3) - good version

i was able to re-pro reliably 2 times on each version

### Does this issue reproduce with the latest release?

go1.10.3 is the latest release

### What operating system and processor architecture are you using (`go env`)?

arm

### What did you do?

Did building with `./make.bash`

### What did you expect to see?

build complete

### What did you see instead?

see error in screenshot

# Build successful on go1.10.3 (June 6)
![1 10 3 works](https://user-images.githubusercontent.com/64738/43040829-36920f12-8d03-11e8-9291-db102408b24f.jpg)

# Build runs out of memory on 48c7973 (July 10)
![48c7973 broken](https://user-images.githubusercontent.com/64738/43040825-32da178e-8d03-11e8-90a7-fb647341fc0d.jpg)

![img_8530 heic](https://user-images.githubusercontent.com/64738/43040843-7e5f5b7e-8d03-11e8-8d37-ffaeda4a82f4.jpg)

**Comment by agnivade** [comment]
A git bisect would be extremely helpful.

**Comment by ysmolsky** [comment]
On the side note, it would be cool to have builders automatically report and store with currently absent benchmarking data the memory it took to build the go.

**Comment by eliasnaur** [comment]
The Go 1.10.3 release might be from June 6, but it doesn't contain all the changes from Go 1.11. So the window of changes is the entire Go 1.11 development window, except for a few backports.

**Comment by eliasnaur** [comment]
Perhaps #26186 is relevant.

**Comment by agnivade** [comment]
Hi @alevchuk, could you try @randall77's suggestion and see if that helps ?
