### ISSUE TITLE
cmd/compile, cmd/link: doc: docs are incomplete

### ISSUE THREAD

**Issue by ainar-g** [golang/go#26533]
The documentation for those commands on the website ([compile](https://tip.golang.org/cmd/compile/), [link](https://tip.golang.org/cmd/link/)) lacks certain flags. For example, compile's page is missing the very useful `-m` flag, and link's page -- `-a`, `-buildid`, and others.

(Ideally, those sections would be generated from `go tool (compile|link) -h` output, but I don't know enough details to propose a full solution.)

**Comment by ianlancetaylor** [comment]
I don't think we should generate the docs from the `-h` output.  The docs and the `-h` output serve two different purposes.

**Comment by hellozee** [comment]
I would love to take a shot on it, but first I need to what things I need to add? would just adding the missing flags, do the task?

**Comment by agnivade** [comment]
@hellozee - The person who submitted the CL has not responded. You could look into that, incorporate @ianlancetaylor's comments and send a new CL.

**Comment by odeke-em** [comment]
Hello @yohei-takeda, Go1.12's release is just around the corner. Would you mind responding to Ian's comments on the CL? Thank you.

**Comment by yo-tak** [comment]
Hello @ianlancetaylor @odeke-em , thank you so much for your feedbacks! And I'm very sorry I didn't respond for a long time.
I'm proud that I made my first commit to Go, I'll try to do better next time.

**Comment by ianlancetaylor** [comment]
@yo-tak No worries, thanks for taking the time to fix this.
