### ISSUE TITLE
x/build: add MacOS builder for long tests

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#26530]
We should run long tests on all major platforms, not only on Linux. Whenever test is removed from the short mode, it gets neglected because long tests are not run automatically. 

#26473 might move even more tests to the long mode.

**Comment by bradfitz** [comment]
We have limited numbers of physical Macs, so this might be too expensive.

**Comment by dmitshur** [comment]
Merging this issue into #35678 (a duplicate issue).
