### ISSUE TITLE
runtime: bug with indexes while range in string

### ISSUE THREAD

**Issue by jflenero** [golang/go#26542]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What did you do?
https://play.golang.org/p/SGSiTfrzD3P

### What did you expect to see?
We should expect a range of 37, as there are 37 characters in the string.

### What did you see instead?
A range of 38, the special characters, in this case 'Ñ' make the indexes step further

**Comment by Gnouc** [comment]
I think it's intended, see https://blog.golang.org/strings

**Comment by myitcv** [comment]
This is not a bug:

https://golang.org/ref/spec#String_types
https://golang.org/ref/spec#For_statements (see the bit about range clauses, specifically for strings)
