### ISSUE TITLE
Slices of functions are not deep equal when they have the same contents

### ISSUE THREAD

**Issue by caervs** [golang/go#26548]
See https://play.golang.org/p/IIiZzDjXhN4 for minimally reproducing case

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.10.1 darwin/amd64`
go version go1.9.6 linux/amd64
go playground (see above)
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

`darwin/amd64` and `linux/amd64` (see above)

### What did you do?

See [playground link above](https://play.golang.org/p/IIiZzDjXhN4).

1. Create two empty slices of functions for the same interface
2. Verify the two slices **are** deeply equal
3. Create two slices of functions with the same contents (pointing to the same function)
4. Note the two slices are **not** deeply equal

What's going on here?

### What did you expect to see?

The two slices are deeply equal in step 4 (or at least some consistency with step 2)

### What did you see instead?

The two slices are not deeply equal

**Comment by FMNSSun** [comment]
The doc mentions:

```
Func values are deeply equal if both are nil; otherwise they are not deeply equal. 
```

`func` is only comparable to `nil`.

**Comment by mvdan** [comment]
As @FMNSSun says, this is working as intended.
