### ISSUE TITLE
cmd/cover: tool cover -html draws invisible file chooser

### ISSUE THREAD

**Issue by sblackstone** [golang/go#26554]
### What version of Go are you using (`go version`)?

go version go1.10.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sblackstone/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sblackstone/code/furious/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vv/1cv4dp094z5bvysrmzqmzjd00000gn/T/go-build060803460=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

go test ./... -coverprofile=cover.out && go tool cover -html=cover.out

### What did you expect to see?
There is a visible select box for choosing which file to look at.

### What did you see instead?
A missing-but-clickable file chooser in the profile...  (See screenshot w/ HTML)

![image](https://user-images.githubusercontent.com/131382/43104883-e93c5c96-8ea0-11e8-8986-720eed7d67a1.png)

**Comment by dsymonds** [comment]
I cannot reproduce this close to head, but I also can't see how this can happen from `cmd/cover`'s side. The HTML it generates for the `<select>` is quite simple.

Is it possible you have some Chrome extension hiding it? Can you try opening that `coverage.html` file in an incognito window to check?

**Comment by ianlancetaylor** [comment]
@sblackstone See questions above.

**Comment by dsymonds** [comment]
I'm fairly convinced this isn't a bug in `cmd/cover`. It's most likely some issue in the user's browser.
