### ISSUE TITLE
cmd/go: `go help proxy` is mentioned but not available

### ISSUE THREAD

**Issue by dmitris** [golang/go#26553]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +62f401bf18 Mon Jul 23 16:05:04 2018 +0000 darwin/amd64

### Does this issue reproduce with the latest release?
reproduces with go1.11beta2

### What operating system and processor architecture are you using (`go env`)?
GOOS="darwin"
GOARCH="amd64"

### What did you do?
- read https://tip.golang.org/cmd/go/#hdr-Environment_variables:
```
GOPROXY
	URL of Go module proxy. See 'go help goproxy'.
```
- tried to run `go help goproxy` - got an error: "Unknown help topic `goproxy`. Run 'go help'."

### What did you expect to see?
help documentation for goproxy

### What did you see instead?
Unknown help topic `goproxy`. Run 'go help'.

Note that `go help goproxy` is also mentioned close to the end of https://tip.golang.org/cmd/go/#hdr-Remote_import_paths ("Remote import paths") section:

> When using modules, downloaded packages are stored in the module cache. (See 'go help 
> modules-get' and 'go help goproxy'.)

**Comment by andybons** [comment]
@bcmills @rsc
