### ISSUE TITLE
access: GitHub ("go-approvers")

### ISSUE THREAD

**Issue by meirf** [golang/go#26557]
Hello,

I started contributing some code a few years ago. More recently, I've focused on the issue tracker in earnest. My contributions mostly fall into http, http2 and any previously unaddressed issues. I tend to work similar hours as @agnivade, with whom I sort of collaborate.

https://github.com/orgs/golang/teams/go-approvers

**Github activity**: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Ameirf
(For completeness, here is my Gerrit activity: https://go-review.googlesource.com/q/owner:meirfischer%2540gmail.com)

/cc @andybons @bradfitz

**Comment by bradfitz** [comment]
SGTM. I can grant permissions later if nobody beats me to it.

**Comment by andybons** [comment]
Done.

**Comment by meirf** [comment]
Thank y'all!

**Comment by meirf** [comment]
(@bradfitz @andybons I haven't been keeping up with the duties of an "approver" nor do I see a time in the near term when I will be able to so I've left the organization. I still hope to contribute patches. This has nothing to do with the Go community which I still love and everything to do with being able to juggle my day job + life. Cheers, @meirf.)
