### ISSUE TITLE
cmd/compile: internal compiler error: bvbulkalloc too big

### ISSUE THREAD

**Issue by meilihao** [golang/go#26560]
### What version of Go are you using (`go version`)?
go version go1.11beta2 linux/amd64

### Does this issue reproduce with the latest release?
using `go version go1.10.3 linux/amd6` gets the same error.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/chen/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chen/git/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build035443180=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
`go run github.com/meilihao/pinyin/blob/master/example/case.go`

### What did you expect to see?
`go run` or `go build` can work.

### What did you see instead?
```
# github.com/meilihao/pinyin
<autogenerated>:1: internal compiler error: bvbulkalloc too big: nbit=20900 count=877877 nword=654 size=574131558

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by meilihao** [comment]
@randall77 Thanks for your answer, i put it into `func init()`, and it works for now.

**Comment by agnivade** [comment]
@randall77 - Since OP has resolved the issue, do we want to track this separately or mark as dup of #26552 ?

**Comment by randall77** [comment]
Let's track this separately.  #26552 might fix it but I'm not sure.

**Comment by randall77** [comment]
This seems fixed at tip. CL 140301 helped, but even without that CL tip can compile the OP's code (which is now the commented-out initializer in that github repository, right?). So something else has helped also, not sure what.  It does still take ~4GB or so to compile, but the live variable map is not >2^31 any more.

I'm going to close this now.  #26552 might help some more, but we're ok for now.
