### ISSUE TITLE
Dead link on documentation

### ISSUE THREAD

**Issue by ihrimech** [golang/go#26569]
Hello,

On the pprof documentation link : 
https://golang.org/pkg/runtime/pprof/
There is a dead link that needs to be replaced:
https://blog.golang.org/profiling-go-programs instead of  https://github.com/google/pprof/blob/master/doc/pprof.md just before the index

**Comment by ALTree** [comment]
Thanks for the report.

This is already fixed on tip: https://tip.golang.org/pkg/runtime/pprof/

The new version of the doc will go up soon with the 1.11 release. Closing here, since it's already fixed.
