### ISSUE TITLE
x/net: html.Parse does not parse self closing token correctly

### ISSUE THREAD

**Issue by npchp110** [golang/go#26566]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

https://play.golang.org/p/fAXM0DtL6mW

```
package main

import (
	"os"
	"strings"

	"golang.org/x/net/html"
)

func main() {
	raw := `<video src="a.mp4"/><p>xx</p>`
	root, _ := html.Parse(strings.NewReader(raw))
	html.Render(os.Stdout, root)
}
```

### What did you expect to see?
```
`<p>xx</p>' parsed as child of body:
<html><head></head><body><video src="a.mp4"></video><p>xx</p></body></html>
```

### What did you see instead?
```
'<p>xx</p>' parsed as child of video:
<html><head></head><body><video src="a.mp4"><p>xx</p></video></body></html>
```

**Comment by artyom** [comment]
I think parser behaves correctly here. Your input is non-conformant — [spec](https://www.w3.org/TR/html5/semantics-embedded-content.html#elementdef-video) tells that for video element *"Neither tag is omissible"* — so your input is parsed as if html element holds `<p>` which is what you see in rendering.

This program prints parsed tree nesting: https://play.golang.org/p/jHCa0PEpHGC

```
.html
..head
..body
...video
....p
```

Note that browsers also parse such input in a similar fashion — here's what tree produced Safari:

![safari](https://user-images.githubusercontent.com/68182/43132871-c692f704-8f45-11e8-8e58-85a81b6533e2.jpg)
