### ISSUE TITLE
runtime: gcWriteBarrier requires g.m.p != nil even if g.m.dying > 0

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#26575]
A signal can occur on a thread with no p, that is, where `g != nil && g.m != nil && g.m.p == nil`.  Thus, the signal hander must not have any write barriers.  A signal can cause a panic, which the signal handler implements by calling `startpanic_m`.  The code in `startpanic_m` is permitted to have write barriers, because write barriers are permitted, even if `g.m.p == nil`, if `g.m.dying > 0`.  This check is made in `wbBufFlush`.

However, write barriers are currently implemented by calling `gcWriteBarrier`.  And that function, written in assembler, assumes that `g.m.p != nil`.  So when `startpanic_m` has a write barrier, which it does when setting `_g_.writebuf = nil`, we can get a segmentation violation while handling a signal.

I believe this can happen starting in the 1.10 release.

cc @aclements

**Comment by aclements** [comment]
Yuck. I can think of a few solutions:

1. Check if `g.m.dying > 0` in `gcWriteBarrier`. This is the obvious one, but adds more instructions and another memory load to the write barrier hot path.

2. Check if `g.m.p` is nil in `gcWriteBarrier` and jump to a slow path that checks `g.m.dying`. This adds two instructions to the hot path, but no more loads. The slow path could just be the flush path and we could do the detailed check in the Go code to keep the assembly simple.

3. The `_g_.writebuf = nil` write is the *only* write barrier in `startpanic_m`. We could change how that works and then disallow write barriers in `startpanic_m`.
    1. We could just do that write without a write barrier, since the GC can't possibly transition any more once we've reached this point.
    2. We could ignore `g.writebuf` if `g.m.dying > 0`.
    3. If we cleaned up tracebacking (which I started to do but got stuck on write barriers, coincidentally), we might be able to get rid of `g.writebuf`. The sole user is `runtime.Stack`. That would also shrink the g.
