### ISSUE TITLE
cmd/go: add ability to download info, mod and source zip

### ISSUE THREAD

**Issue by arschles** [golang/go#26577]
In the [Athens project](https://github.com/gomods/athens), the code that downloads code from VCS's and stores it in the database uses `go get` behind the scenes. We have to do some hacky things right now - like create a skeleton `go.mod` file and an empty `func main() {}` to get `go get` to work. 

Instead of doing that, we'd like to use a command - say, `go get $THING --artifacts-only` - that downloads the code from the appropriate VCS (still respecting redirects, etc... as it does now), creates the source zip, and then leaves just the info, mod, and source zip in the current directory.  and all of this without requiring that there is a valid `go.mod` and any go code in the cwd.

**Comment by bcmills** [comment]
Is this the same thing as #26609?

**Comment by marwan-at-work** [comment]
would this be in the scope of being able to do something like `go list -m -versions [module]@latest` from outside of a module directory?

**Comment by arschles** [comment]
@rsc what do you think about a `go list` command?

@marwan-at-work mentioned today at the athens dev meeting that we might have to duplicate `internal` code from `cmd/go` to get list working properly on the server

**Comment by marwan-at-work** [comment]
@arschles `go list -m -versions` already works. We just have to be inside a dummy go module, which is a bit hacky :)

**Comment by arschles** [comment]
I wonder if we can add “don’t require go list -m to be in a go module” to
the wishlist on this issue 😊

**Comment by marwan-at-work** [comment]
Should this be a release blocker just like its #26609 dup?

**Comment by marwan-at-work** [comment]
Also from Athen's perspective, it's okay to just do all three at the same time (info/mod/zip). As long as Go doesn't traverse the dependencies of what we're asking for and tries to download them and "go install" them. This has led to some failed builds. `go get github.com/gopherjs/gopherjs v0.0.0-20180315154859-97d8e769111c` for example fails, but if it's inside a mod file that doesn't need one of the dependencies that make it fail, then `go build` will work.
