### ISSUE TITLE
cmd/go: allow -getmode=vendor in environment variable

### ISSUE THREAD

**Issue by surajbarkale** [golang/go#26585]
### What version of Go are you using (`go version`)?
go1.11beta2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### Feature request

Can we please have an environment variable which would enable the relevant vgo operations to always use -getmode=vendor (or any other value)? Something like GOMODULE_GETMODE?

The reason is that while $enterprise borderline caching proxies are a good thing—in theory, in practice we here at $dayjob are not yet ready to deploy something like this and are already using vendoring as an almost perfect solution to combat both the different variants of the "left-pad problem" (including the "github is down" one) and the versioning problem—everyone get the set of vendored packages of blessed versions, and the vendored packages get upgraded by explicit manual intervention after much discussion and experimentation and tests.
We'd like this to be working as easy as it is now in perpetuity, if possible.

This issue is generated from a [unaddressed comment](https://github.com/golang/go/issues/25073#issuecomment-396832166) made on a closed issue.

**Comment by rsc** [comment]
To date we have never provided an environment variable that duplicates a command-line flag in the go command. I'm reluctant to start now.

**Comment by surajbarkale** [comment]
Even though I work in a large organisation, my team is the only one that uses go. We are unable to set up extra infrastructure (metadata servers, proxies) because of manpower required to maintain it is not available.

The `vendor` directory workflow has been instrumental in supporting go internally. We have following workflow:

1. New dependencies (or updates to existing once) are brought in by individual devs.
2. The resulting vendor folder is committed to git along with the lock files.
3. When building the code, no internet access is needed for individual developers or CI machines.

I am expecting modules to support this workflow without developers having to jump through hoops every time. 

Setting environment variable which can be overridden from command line is one option. Other option is to specify the default getmode in `go.mod` and override it from command line option.

In day-to-day operations, I want devs to be able to just execute `go build` or `go test` and not have to worry about dealing with missing dependencies.
