### ISSUE TITLE
syscall/js: build constraints exclude all Go files in C:\Go\src\syscall\js

### ISSUE THREAD

**Issue by PhilipMantrov** [golang/go#26598]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11.beta2

### Does this issue reproduce with the latest release?
On beta, yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOOS=windows

### What did you do?
just import "syscall/js"

### What did you expect to see?
No errors at all

### What did you see instead?
build constraints exclude all Go files in C:\Go\src\syscall\js

Probably this error only appears on 1.11.beta2

**Comment by andybons** [comment]
@neelance @bradfitz

**Comment by neelance** [comment]
What exactly did you do? Did you specify `GOOS=js` and `GOARCH=wasm`?

**Comment by PhilipMantrov** [comment]
@neelance 
Oh, forgot about this, thx and sorry for stupid issue.

**Comment by andybons** [comment]
@PhilipMantrov it's not a stupid issue. :)

if you see opportunity for an improvement in documentation please feel free to send a change to make it more clear.
