### ISSUE TITLE
cmd/go: module commands fail to resolve version tags that include metadata

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#26605]
Semver metadata are considered valid by the semver spec, however Go modules do not work when you try to `go get` a tag that has metadata. 

Although `cmd/go/internal/semver.IsValid` returns true when the input is `v1.2.3-alpha+mymeta` the cli does not work across `get`, `build`, and `list` commands. This is because Go strips all build metadata before issuing fetch commands. For example, if the tag in a git repo is `v1.2.3+meta`, Go will ask that git repo to give it `v1.2.3` which does not exist. 

Go version: tip 
Go env: all.

**Comment by rsc** [comment]
This is working as intended. There needs to be a single canonical tag we look for, and that tag is the tag with metadata stripped. Semver says that v1.2.3-alpha and v1.2.3-alpha+metadata should mean the same thing, so we look for v1.2.3-alpha.

Note that our mapping of git tags to go versions is not anticipated by nor controlled by the semver spec, of course.
