### ISSUE TITLE
x/mobile: Code Signing Error: No account for team "N22349G4YP"

### ISSUE THREAD

**Issue by idoor88** [golang/go#26615]
I got this error when I built gomobile basic for ios target, I googled around, but no solution found so far, could somebody help me? my go version is go1.10.1 darwin/amd64, and go env:

GOARCH="amd64"
GOBIN="/Users/t2349/workspace/go/bin"
GOCACHE="/Users/t2349/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/t2349/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/29/xcbl6q4d72v8y5wmrk12d64497njfc/T/go-build546510109=/tmp/go-build -gno-record-gcc-switches -fno-common"

The error message I got is:

gomobile build -target=ios golang.org/x/mobile/example/basic
gomobile: xcrun xcodebuild -configuration Release -project /var/folders/29/xcbl6q4d72v8y5wmrk12d64497njfc/T/gomobile-work-011020595/main.xcodeproj -allowProvisioningUpdates DEVELOPMENT_TEAM=N22349G4YP failed: exit status 65
2018-07-25 22:03:06.099 xcodebuild[73398:10119419] [MT] PluginLoading: Required plug-in compatibility UUID 426A087B-D3AA-431A-AFDF-F135EC00DE1C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Build settings from command line:
    DEVELOPMENT_TEAM = N22349G4YP

=== BUILD TARGET main OF PROJECT main WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: No account for team "N22349G4YP". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No profiles for 'org.golang.todo.basic' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.golang.todo.basic'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by eliasnaur** [comment]
Use the -bundleid to set a bundle ID that you have previously claimed. One way to do that is to create an empty iOS project in Xcode and set its bundle ID. Run the project on a device and gomobile build with that ID should work from then on.

The CL linked above makes the -bundleid parameter mandatory, which is less confusing.
