### ISSUE TITLE
x/mobile/cmd/gomobile: setup installation failed. when i run gomobile init it gives error in command line that gomobile: command not found

### ISSUE THREAD

**Issue by Smarty97** [golang/go#26619]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/usrname/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/usrname/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build802535089=/tmp/go-build -gno-record-gcc-switch

**Comment by andybons** [comment]
Can you outline the steps you took to install `gomobile`? is `$GOPATH/bin` present in your `$PATH`?

**Comment by MRDO5** [comment]
HI all! I can't install gomobile in feodra 29
go get golang.org/x/mobile/cmd/gomobile
running this nothing to du
i have added path for go in bashrc file.
How i can fix that ?
