### ISSUE TITLE
cmd/compile: change "multiple-value .. in single-value context" error message to be consistent with >1 case

### ISSUE THREAD

**Issue by techtonik** [golang/go#26616]
### What version of Go are you using (`go version`)?
1.10

### What did you do?

    bar := bufio.NewReader(...)
    line := bar.ReadString()

### What did you expect to see?

    1 of 2 return values of ReadString() is not handled

### What did you see instead?

    multiple-value bar.ReadString() in single-value context

---

The expected error text should be more clear for people without a university degree. =)

**Comment by techtonik** [comment]
I would still insist on `1 of 3 return values of foo() is not handled`.

**Comment by agnivade** [comment]
The error message is the same vein of how we write failure messages in test - `Got- %v, Expected- %v`. It says - Got 2 variables, but expected 3 values. It clearly mentions what was expected, and what it received. 

I am not sure why the single-value context is considered a special case.

/cc @josharian @mdempsky

**Comment by meirf** [comment]
@techtonik:

Regardless of whether the 1 vs >1 special case is changed, it sounds like you still have a problem with general case. I have a couple concerns with your alternative:

> I would still insist on 1 of 3 return values of foo() is not handled.

- "1 of 3 return values": This sounds like an ordering. People might think this means that the first of the three returned values doesn't have a variable to be assigned to but the others do. Whereas "1 variables but 3 values" is just about quantity.
- "is not handled": The word "handle" is a bit vague. Whereas "assignment mismatch" is more precise.

**Comment by mdempsky** [comment]
I think it's very unlikely we'd adopt the wording `1 of 2 return values of ReadString() is not handled`, for the reasons @meirf explained.

I'm sympathetic to changing the error message to `assignment mismatch: 1 variable but 2 values` though. I think the current error message can be attributed to an artifact of the compiler having OAS as a special case of the more general OAS2 node, rather than being intentionally inconsistent.

If anyone wants to dig into this, look at typecheckas and typecheckas2 in typecheck.go. In particular, Efnstruct (to suppress the "multi-value in single-value context" error) and IsFuncArgStruct (to distinguish a multi-value expression).

**Comment by techtonik** [comment]
> "1 of 3 return values": This sounds like an ordering. People might think this means that the first of the three returned values doesn't have a variable to be assigned to but the others do.

For ordering it should be `1st of 3 return values`, no? Also, does go syntax permit not to assign a variable to returned value? Because if it doesn't, ordering doesn't make sense.

> `assignment mismatch: 1 variable but 2 values`

This one is good. I would only specify that this are "2 return values".

**Comment by mdempsky** [comment]
>  would only specify that these are "2 return values".

The current wording for `x, y = three()` is "2 variables but 3 values," so the consistent wording for `x = three()` would be "1 variable but 3 values."

As I mentioned on the CL, I'm open to discussion about changing both instances to "3 return values" (or more precisely "3 result values"), but let's open a new issue for that. Personally, I think the current wording (as of f7a633a) is unambiguous.
