### ISSUE TITLE
encoding/json: add tag to support one-way operation for marshal/unmarshal

### ISSUE THREAD

**Issue by meilihao** [golang/go#26636]
### What did you do?
Now if the field tag is "-", the field is always omitted. sometime, we need one-way operation for marshal/unmarshal.

### What did you expect to see?
add `<-`  for unmarshal, omit marshal; add `->`  for marshal, omit unmarshal.

## tag "<-"
```json
{
    "name":"joy",
    "password":"123456"
}
```

```go
type User struct {
    Name string `json:"name"`
    Password string `json:"password,<-"`
}
```

```
u := new(User)

json.Unmarshal([]byte(raw), u)
fmt.Println(u)

data, _ := json.Marshal(u) // omit filed "Password"
fmt.Println(string(data))
```

output:
```
&{joy 123456}
{"name":"joy"}
```

## tag "->"
```json
{
    "name":"joy",
    "password":"123456"
}
```

```go
type User struct {
    Name string `json:"name"`
    Password string `json:"password,->"`
}
```

```
u := new(User)

json.Unmarshal([]byte(raw), u) // omit filed "Password"
fmt.Println(u)

u.Password = "123456"
data, _ := json.Marshal(u)
fmt.Println(string(data))
```

output:
```
&{joy}
{"name":"joy", "password":"123456"}
```

**Comment by ctriple** [comment]
how do we keep '-' means?

**Comment by mvdan** [comment]
This is a substantial change to the json package and should be a proposal: https://github.com/golang/proposal

Having said that, a couple of ways to do this without adding features come to mind:

* Have multiple versions of the same struct for marshaling and unmarshalilng, with different json field tags. Converting values between these is permitted. Will require some boilerplate if the fields in question are nested, though.
* Manually ignore the fields. If one wants to ignore the field when marshaling, set it as `omitempty` and temporarily zero it. If one wants to ignore the field when unmarshaling, reset the field to its previous value.

**Comment by meilihao** [comment]
@ctriple I think `-` is stay the same as before.

@mvdan :
1. `Have multiple versions of the same struct for marshaling and unmarshalilng, with different json field tags` is tedious.
1. `Manually ignore the fields` is tedious too.

**Comment by mvdan** [comment]
Most of the changes that would make the language more complex are to avoid some degree of code verbosity, so that's not a point that stands on its own. The advantages of this proposal must outweigh the disadvantages. To do that, this issue should be a proposal, like I suggested above.

**Comment by smyrman** [comment]
# Alternative syntax: two struct tags

Another syntax to achieve this, could be to introduce two new struct-tag prefixes, e.g.`"jsonMarshal"` and `"jsonUnmarshal"`. I.e.:


```go
type User struct {
	Name     string `json:"name"`
	Password string `jsonMarshal:"password" jsonUnmarshal:"-"``
}
```

This even allows using _different_ values for encode a decode, when desirable.

# Alternative syntax: `,nomarshal`, `,nounmarshal`

Yet another alternative, would be to allow  `,nomarshal` and `,nounmarshal` keywords (or some similar wording:


```go
type User struct {
	Name     string `json:"name"`
	Password string `json:"password,nounmarshal"`
}
```

# Use-case

With either method, this would be even more useful when using embedded structs as a mechanism for including fields into models on the client side of an API where the server has defined _read-only_ fields. In particular so, because custom marshal / unmarshal methods for structs used as embedded fields, does not have the desired effect.

Example:

```go
package modelprofile

type Model struct {
	ID   string `json:"id,omitmarshal"`
	ETag string `json:"_etag,omitmarshal"`
}

type WriteInfo struct {
	CreatedBy string     `json:"createdBy,nomarshal"`
	UpdatedBy string     `json:"updatedBy,nomarshal"`
	CreatedAt *time.Time `json:"createdAt,nomarshal"`
	UpdatedAt *time.Time `json:"updatedAt,nomarshal"`
}
```

```go
type User struct {
	modelprofile.Model
	modelprofile.WriteInfo

 	Name string      `json:"name"`
 	Password string `json:"password,nounmarshal"`
```
