### ISSUE TITLE
internal/cpu: ARM feature detection

### ISSUE THREAD

**Issue by smasher164** [golang/go#26630]
Similar to #26538, feature detection on ARM is useful for runtime specialization of code.

Knowing if VFPv4 is present on the hardware helps the implementation of intrinsics (like FMA) and other math operations. However, since VFPv4 is detected through the HWCAP bits from auxv, only the runtime has access to the this information. Given that ARM's hardware features don't map easily to GOARM values, more fine-grained detection is needed.

An additional benefit of including ARM feature detection into the package is that because pre-ARMv8 is so variable, having a single source of feature detection makes it easier to debug different codepaths (https://github.com/golang/go/commit/f045ddc624dea292257249a618e4ad1bd2bd5c6e).

Because Go does not support ARMv4 and lower,
- HWCAP_26BIT is always false, and thus unnecessary.
- HWCAP_SWP and HWCAP_HALF should always be enabled.

**Comment by martisch** [comment]
The first arm support for harddiv was already implemented in https://go-review.googlesource.com/c/go/+/114826 and is waiting for the freeze to go1.12 to lift.

**Comment by smasher164** [comment]
Sorry, I jumped the gun on that CL. I can withdraw it and comment on the hardDiv one if you'd like.

**Comment by martisch** [comment]
Np. I would be happy if you can comment on test on any improvements for the existing https://go-review.googlesource.com/c/go/+/114826. We can submit your CL (after review) ontop of that for any additional features needed for upcoming implementations needing other cpu features (in e.g. math) once they are ready for review.

**Comment by bradfitz** [comment]
What remains here? Looks like all the CLs above were merged?

Bumping to Go 1.13 but feel free to close if this is all done.

**Comment by smasher164** [comment]
The CL has been merged, so nothing remains for the internal/cpu portion of the ARM feature.
