### ISSUE TITLE
github: update organization logo

### ISSUE THREAD

**Issue by bontibon** [golang/go#26647]
The [golang organization on Github](https://github.com/golang) uses a Gopher as its logo:

![screenshot_2018-07-27_13-31-13](https://user-images.githubusercontent.com/110883/43333669-5d093ee8-91a1-11e8-8f10-287e0d90f6d5.png)

It should be updated to the new logo, as defined in the [Go branding](https://blog.golang.org/go-brand) documents.

**Comment by ianlancetaylor** [comment]
CC @spf13

**Comment by spf13** [comment]
I think it's totally fine and appropriate to leave the mascot as the icon for the project here.

**Comment by davecheney** [comment]
Thanks Steve.
