### ISSUE TITLE
No compilation error on assigning pointer to interface to an interface

### ISSUE THREAD

**Issue by nd** [golang/go#26641]
### What version of Go are you using (`go version`)?
```
go version go1.11beta2 linux/amd64
```

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nd/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nd/go"
GOPROXY=""
GORACE=""
GOROOT="/home/nd/sdk/go1.11beta2"
GOTMPDIR=""
GOTOOLDIR="/home/nd/sdk/go1.11beta2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build236360562=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

The following program compiles without an error (https://play.golang.org/p/Mp5uACzfE7X):

```
package main

type I interface {
	// foo()
}

type t int

func (t) foo() {
}

func main() {
	var v1 I = t(1)
	var v2 I = t(1)
	v2 = &v1
	_ = v2
}
```

If the `foo()` method is uncommented in the interface, a compilation rightfully fails with the error:
```
cannot use &v1 (type *I) as type I in assignment:
	*I is pointer to interface, not interface
```

### What did you expect to see?
I expected compilation to fail for the case when interface has no methods as well, because language spec doesn't seem to mention this as a special case.

### What did you see instead?
There is no compilation error and pointer to an interface is assigned to a variable of the interface type.

**Comment by FMNSSun** [comment]
`type I interface{}` is the empty interface and the spec mentions that

> every type implements the empty interface.

**Comment by mvdan** [comment]
Any value can be assigned to an empty interface, like @FMNSSun says.
