### ISSUE TITLE
proposal: function assignment syntax

### ISSUE THREAD

**Issue by yesuu** [golang/go#26659]
I want rename the function:

```
func sum(x, y int) int { return x + y }
var myfunc = sum
// func myfunc(x, y int) int { return sum(x, y) }
```

if we can change `var` to `func`:

```
func sum(x, y int) int { return x + y }
func myfunc = sum // or: func myfunc sum ?
```

don't use type derivation:

```
func sum(x, y int) int { return x + y }
func myfunc(x, y int) int = sum // or: func myfunc(int,int) int = sum ?
// var myfunc func(int,int) int = sum
```

the right is a method:

```
type mytype struct{}
func (_ mytype) sum(x, y int) int { return x + y }
var myobject = new(mytype)
func myfunc = myobject.sum
// var myfunc = myobject.sum
```

if the left is a method, I don't know what it should be.

The difference is that the `var` syntax can assign multiple times, and `func` can only assign once.

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
