### ISSUE TITLE
cmd/go: allow a module to be downloaded by go get without its dependencies

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#26683]
When go asks the GORPOXY for a zip file, it only wants that zip file and not its dependencies.

`go get`, however, attempts to recursively download all dependencies.

Is there a reason not to have a flag that makes `go get` just download the code (.info, go.mod, and .zip) of a package and not its dependencies? I saw that `-m` does not allow download/install, but it does not create a .zip file inside the mod/cache/download directory. 

### What version of Go are you using (`go version`)?
Tip

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
darwin

**Comment by marwan-at-work** [comment]
Actually, though the two issues are unrelated, Russ's comments in https://github.com/golang/go/issues/26600#issuecomment-407867646 potentially addresses my issue above.

**Comment by ianlancetaylor** [comment]
If you feel that there is nothing else to do here, please close the issue.  Thanks.

**Comment by marwan-at-work** [comment]
I believe https://github.com/golang/go/issues/26577 is the same as this one so I'll close for now and if they diverged I'll reopen. Thanks @ianlancetaylor !
