### ISSUE TITLE
vet: check for "+build" comment inconsistently reports error in package doc

### ISSUE THREAD

**Issue by kr** [golang/go#26681]
#### What version of Go are you using (`go version`)?

    go version go1.11beta2 darwin/amd64

#### Does this issue reproduce with the latest release?

Yes.

#### What did you do?

https://play.golang.org/p/xABgz0L94ig

#### What did you expect to see?

No error message, as in https://play.golang.org/p/v6DLrueUHqN.

#### What did you see instead?

    prog.go:5: +build comment must appear before package clause and be followed by a blank line

This makes it a little difficult to include example code in the package doc, when the example needs to show a build directive.

Note that it's not just interpreting the `+build ignore` as a build directive inside the package comment. If we alter that line so that line alone doesn't look like a Go comment, vet reports no error: https://play.golang.org/p/v6DLrueUHqN

**Comment by kr** [comment]
Oops, I think this is a duplicate of #26627.

**Comment by meirf** [comment]
@kr yea they look similar. I'm gonna close this, but please comment there if you feel the conversation/CLs in https://github.com/golang/go/issues/26627 are not addressing your exact concerns.
