### ISSUE TITLE
cmd/go: TestGoTestImportErrorStack fails if wanted output is indented with spaces

### ISSUE THREAD

**Issue by shivakumargn** [golang/go#26686]
### What version of Go are you using (`go version`)?

go version devel +5ad0a524d2 Sat Jul 28 09:06:26 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

### What did you do?

Apply the below patch and run the test on cmd/go (the tabs are changed to spaces).
In my case this happened accidentally due to text editor settings. The program was gofmt compliant since the code itself is a string inside the go file and gofmt does not interpret it.

[go_test.patch.txt](https://github.com/golang/go/files/2239703/go_test.patch.txt)

```
diff --git a/src/cmd/go/go_test.go b/src/cmd/go/go_test.go
index dc4bad4987..42d269f957 100644
--- a/src/cmd/go/go_test.go
+++ b/src/cmd/go/go_test.go
@@ -3682,8 +3682,8 @@ func TestGoTestRaceFailures(t *testing.T) {
 
 func TestGoTestImportErrorStack(t *testing.T) {
 	const out = `package testdep/p1 (test)
-	imports testdep/p2
-	imports testdep/p3: build constraints exclude all Go files `
+        imports testdep/p2
+        imports testdep/p3: build constraints exclude all Go files `
 
 	tg := testgo(t)
 	defer tg.cleanup()
```

### What did you expect to see?

Success
Even though tabs are the recommended indentation, space should not result in test failure.

### What did you see instead?

Failed test

**Comment by meirf** [comment]
> Even though tabs are the recommended indentation, space should not result in test failure.

The test is just verifying what the import stack error looks like. So it seems like this issue should be focused on the what the import stack error looks like as opposed to the test that verifies it. So perhaps you're saying that the import stack error should have spaces instead of tabs.

But it looks like it's standard practice to have tabs in error messages. For example, [this panic](https://play.golang.org/p/vEZ8fi1ajHw) uses a tab. (Highlight the empty space and compare to that of the spaces above to see that it is a tab.)

**Comment by mvdan** [comment]
I'm not sure what we could do here. It should be fine for a test to require specific output via a multiline literal string - why should an editor automatically modify these?

**Comment by shivakumargn** [comment]
The intent of the test is now clear that it is the expected output. From the code I was of the impression it is attempting to import/compile it.
The problem was accidental that when one types, visual code (and several editors) automatically give empty spaces and not tabs. One runs gofmt to fix it. In this case obviously that does not help.

Will close the ticket as not a bug.
