### ISSUE TITLE
sort: function names should be mixed caps

### ISSUE THREAD

**Issue by cia-rana** [golang/go#26693]
According to [Effective Go](https://golang.org/doc/effective_go.html#mixed-caps), function names should be mixed caps, but `*_func` including the underscore is used for the ones in [sort/zfuncversion.go](https://github.com/golang/go/blob/master/src/sort/zfuncversion.go) generated by [sort/genzfunc.go](https://github.com/golang/go/blob/master/src/sort/genzfunc.go). Thus when generating these functions,  we should use `Func` instead of `_func`.

**Comment by ALTree** [comment]
Thanks for the report.

The suggestions in the Effective Go document do not really apply to auto-generated code. In fact, I suspect the `_func` prefix was chosen exactly to make the functions look like they are auto-generated (as they are).

**Comment by robpike** [comment]
This is generated code. Such code is often non-conformant stylewise.
