### ISSUE TITLE
bvbulkalloc

### ISSUE THREAD

**Issue by GongFaxin** [golang/go#26705]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by agnivade** [comment]
Kindly fill the complete issue template with the problem you are experiencing.

**Comment by davecheney** [comment]
I'm going to close this as there is no actionable bug report here.

If this is a bug report, please file a _new_ issue completing the template as requested.

Alternatively, please see https://golang.org/wiki/Questions for good places to ask questions. If there is a bug, they'll redirect you back to here if necessary.

**Comment by ALTree** [comment]
My guess is that you wanted to report something similar to  #26560
