### ISSUE TITLE
cmd/go: test whether mkalldocs.sh generates a git diff

### ISSUE THREAD

**Issue by kevinburke** [golang/go#26735]
A common error is to check in a documentation change but fail to run mkalldocs.sh to compile this change into the public Go binary documentation.

It would be good if Gobot could run mkalldocs.sh and check whether the command generates a Git diff, i.e. whether all changes have been correctly checked in.

I have a shorthand tool for checking this - github.com/kevinburke/differ - that you invoke by running "differ ./mkalldocs.sh" - if you're interested.

**Comment by ianlancetaylor** [comment]
We don't need to do that in gobot, really.  We could write a test in cmd/go that does it.  Or we could just have cmd/dist build the file.
