### ISSUE TITLE
cmd/internal/obj/arm64: legal instruction is rejected by the assembler

### ISSUE THREAD

**Issue by benshi001** [golang/go#26736]
According to ARM64's manual, "BFI $0, R1, $30, R0" should copy bit 0-29 of R1 to R0, and other bits of R0 are left unchanged.

GCC does the expected operation, but go's arm64 assembler rejects it with error "illegal bit number'".

**Comment by bradfitz** [comment]
If this has been broken for several releases now it doesn't need to be in Go 1.11.

**Comment by bradfitz** [comment]
@cherrymui, I'll let you decide which release this is for. I don't think this is a regression from Go 1.10? @benshi001, let us know if it is.

**Comment by cherrymui** [comment]
No, it's not a regression. I can reproduce with Go 1.10. So, no need to be Go 1.11 milestone.

As there is a CL, and I think it is very low risk, the CL can go in Go 1.11 as well.
