### ISSUE TITLE
build: add support for macOS Installer Packages

### ISSUE THREAD

**Issue by jorng** [golang/go#26747]
GoReleaser currently can output Linux installers (`rpm` and `deb` formats), but not macOS installers. It would be nice if it could output installer packages for macOS as well.

This can be achieved, at least when running on macOS, by using the `pkgbuild` and `productbuild` commands. An example:

```sh
pkgbuild --quiet \
    --root "darwin_amd64" \
    --identifier "private.myname.myexecutable" \
    --version "1.0.2" \
    --install-location "/usr/local/bin" "myexecutable.pkg"
productbuild --quiet --package myexecutable.pkg myexecutable-v1.0.2.pkg
rm myexecutable.pkg
```

- `--root` is the path to the darwin binary folder.
- `--identifier` could be set in the config.  It is normally a reverse-dns style with the executable name at the end, so there could be a default of something like `private.$(whoami).{{ .ProjectName }}`
- `--install-location` could be set in the config with a default of `/usr/local/bin`

**Comment by agnivade** [comment]
IIUC, you are talking about [goreleaser](https://github.com/goreleaser/goreleaser), but this repo is for the Go source code. Probably you should raise an issue in that repo instead of here.

And if you are talking about providing macOS installer packages, we already do that https://golang.org/dl/.

**Comment by jorng** [comment]
Odd. Not sure how this ended up on the Go repo... closing and moving to GoReleaser
