### ISSUE TITLE
runtime: garbage collection crash in freebsd/386 runtime running on freebsd/amd64

### ISSUE THREAD

**Issue by dhobsd** [golang/go#2675]
<pre>Before filing a bug, please check whether it has been fixed since
the latest release: run &quot;hg pull&quot;, &quot;hg update default&quot;, rebuild, and
retry
what you did to
reproduce the problem.  Thanks.

What steps will reproduce the problem?
1. Attempt to build go on FreeBSD/i386

What is the expected output?
Successful build

What do you see instead?
cgo segfaults on pkg/net/cgo_unix.go

Which compiler are you using (5g, 6g, 8g, gccgo)?
8g

Which operating system are you using?
FreeBSD/386

Which revision are you using?  (hg identify)
cc0f39d02e93 (this is the earliest revision I was able to get the build to break using
hg bisect -- freebsd/386 has been broken for quite some time, it seems)

Please provide any additional information below.
(gdb) r
Starting program: /usr/home/dho/go-old/bin/cgo -- cgo_unix.go
warning: `/usr/libexec/ld-elf.so.1': Shared library architecture i386:x86-64 is not
compatible with target architecture i386.
warning: `/usr/libexec/ld-elf.so.1': Shared library architecture i386:x86-64 is not
compatible with target architecture i386.

Program received signal SIGSEGV, Segmentation fault.
umtx_unlock (l=void) at /usr/home/dho/go-old/src/pkg/runtime/freebsd/thread.c:72
72	umtx_unlock(Lock *l)
(gdb) p l
$1 = void
(gdb) l
67	
68		goto again;
69	}
70	
71	static void
72	umtx_unlock(Lock *l)
73	{
74		uint32 v;
75	
76	again:
(gdb) bt
#0  umtx_unlock (l=void) at /usr/home/dho/go-old/src/pkg/runtime/freebsd/thread.c:72
#1  0x08076177 in runtime.notesleep (n=void) at
/usr/home/dho/go-old/src/pkg/runtime/freebsd/thread.c:122
#2  0x08070fb1 in nextgandunlock () at /usr/home/dho/go-old/src/pkg/runtime/proc.c:403
#3  0x080713ba in schedule (gp=void) at /usr/home/dho/go-old/src/pkg/runtime/proc.c:572
#4  0x08066ec3 in runtime.mcall (fn=void) at
/usr/home/dho/go-old/src/pkg/runtime/386/asm.s:174
#5  0x38238480 in ?? ()
#6  0x00000000 in ?? ()
(gdb)</pre>

**Comment by mikioh** [comment]
Go 1.5 on FreeBSD from FreeBSD stable branches allows to run GOARHC=386 CGO_ENABLED=1 make.bash on freebsd/amd64 host. I just confirmed it on freebsd-amd64 10.1-RELEASE-p10  and freebsd9-amd64 9.3-RELEASE-p13.
