### ISSUE TITLE
Is gccgo/GPL included in go????

### ISSUE THREAD

**Issue by luisapace** [golang/go#26761]
Hi,
my team would like to use the packages GO:

go 1.10
go 1.6.3
go 1.6.4
go 1.7.5
go 1.7.6
go 1.8.6
go 1.8.7
go 1.9.3
go 1.9.4

(and imported by go-buildpack 1.8.20) and to approve that I've to analyze it's source code, to be sure that they don't have problematic licenses.

But, in all of the, at their file  /blob/master/doc/gccgo_install.html it's stated:

**_This document explains how to use gccgo, a compiler for
the Go language.  The gccgo compiler is a new frontend
for GCC, the widely used GNU compiler.  Although the
frontend itself is under a BSD-style license, gccgo is
normally used as part of GCC and is then covered by
the <a href="http://www.gnu.org/licenses/gpl.html">GNU General Public
License</a> (the license covers gccgo itself as part of GCC; it
does not cover code generated by gccgo)._**
</p>

Now, GPL is a license that we have to manage with care, and it's not clear to me if the component gccgo is included in GO packages and if it's under GPL or under BSD. 

Could you please clarify? 

Thanks a lot for your support.

**Comment by ALTree** [comment]
Hi,

there are two main compiler toolchains: `gc` and `gccgo`. 

They are distinct, and `gccgo` is **not** included in the go releases you can find on the golang.org website. So, if you're using the `gc` compiler by downloading from https://golang.org/dl/, you're using code released on a BSD-style license. AFAIK these go releases do not include any GPL code.

As the [Setting up and using gccgo ](https://golang.org/doc/install/gccgo) page explains, `gccgo` is a different compiler. It's distributed as part of gcc, and it's GLP'ed.

**Comment by luisapace** [comment]
Thanks for your answer; based on that, I'd like to have two other clarifications:

1. I assume that what is in github at https://github.com/golang/go is the same of https://golang.org/dl/, am I correct?
2. you said that go releases do not include any GPL code; so I assume (as I thought) that also gdb (that is under GPL), referenced at https://github.com/golang/go/blob/master/doc/debugging_with_gdb.html is not included in go but if someone wants to use it has to download it separately, am I correct?

Thanks again.

**Comment by luisapace** [comment]
thanks a lot for your quick follow-on!

**Comment by ALTree** [comment]
No problem. Closing here, since I've answered your questions.
