### ISSUE TITLE
path/filepath: filepath.Abs("") returned different results in windows and other systems

### ISSUE THREAD

**Issue by moonfruit** [golang/go#26763]
### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin,amd64 and windows,amd64

### What did you do?

```go
abs, err := filepath.Abs("")
```
[example code](https://play.golang.org/p/9Q7Iz1gnfVt)

### What did you expect to see?
`filepath.Abs("")` returns same results in all systems.

### What did you see instead?
In windows, `filepath.Abs("")` returned an error which is `The filename, directory name, or volume label syntax is incorrect.`
And in macOS, `filepath.Abs("")` returned current working directory.

**Comment by ALTree** [comment]
This is #24441 and it should be fixed on tip (to be released as Go1.11 soon).

**Comment by bcmills** [comment]
Closing as duplicate. Please let us know if this isn't fixed in go1.11beta2.
