### ISSUE TITLE
 x/text: message.MatchLanguage does not return desired language

### ISSUE THREAD

**Issue by kaskavalci** [golang/go#26766]
### What version of Go are you using (`go version`)?
`go version go1.10.3 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOOS="darwin"
GOARCH="amd64"
```

### What did you do?

Run the example on https://godoc.org/golang.org/x/text/message

Note: Slightly changed because example is not correct. Behavior is the same.

```go
p := message.NewPrinter(message.MatchLanguage("nl"))
p.Printf("Hoogte: %1.f meter\n", 1244.9) // Prints Hoogte: 1.244,9 meter
```

### What did you expect to see?

It should print the desired output, *comma* as decimal deliminator. 
Output is the following which is English formatting.

```
Hoogte: 1.244,9 meter
```

### What did you see instead?

```
Hoogte: 1,244.9 meter
```

MatchLanguage fallsback to English as can be seen from here:

```
base, _ := message.MatchLanguage("nl").Base()
fmt.Println(base.String()) // Prints en
```

**Comment by belimawr** [comment]
I'll start looking into this

**Comment by belimawr** [comment]
I found a issue with your example, the correct fmt string is: `Hoogte: %.1f meter\n`.

I fixed the documentation and it did work for me when I run it.

**What version of Go are you using (go version)?**
```
go version go1.9 darwin/amd64
```

**What operating system and processor architecture are you using (go env)?**
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tiago/Documents/devel/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jc/8sd7n5hd49bdl3008z2rmqgh0000gp/T/go-build755876682=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by kaskavalci** [comment]
@belimawr it's not only that unfortunately. What is the output? Comma should be used as decimal separator but dot is used instead. MatchLanguage is falling back to English. If I use `language.Dutch` it prints correctly but not with `message.MatchLanguage("nl")`.

```
 p = message.NewPrinter(language.Dutch)
 p.Printf("Hoogte: %.2f meter\n", 1244.9134) // Prints Hoogte: 1.244,91 meter
```

**Comment by kaskavalci** [comment]
OK, after reading the code and its tests it was more clear. We need to setup catalog otherwise it is always the default fallback language English. I think documentation should reflect this behavior. Following code works for English and Dutch with Dutch as the fallback language. It would be exteremly nice to have this in the sample code in documentation.

```go
c := catalog.NewBuilder(catalog.Fallback(language.Dutch))
c.SetString(language.Dutch, "", "")
c.SetString(language.English, "", "")
message.DefaultCatalog = c
```

**Comment by belimawr** [comment]
@kaskavalci I see your point. The thing is that the default catalog is empty and the fallback is English. I looked more at the code and documentation for catalog, and I'm not sure that the best method to get the language is `message.MatchLanguage` because it uses `message.DefaultCatalog` (that is empty by default) under the hood.

If the objective of that piece of documentation is to show how to use `message.NewPrinter` to get a printer that can print localised numbers, you could just use:
```golang
p := message.NewPrinter(language.Make("nl"))
p.Printf("Hoogte: %.1f meter\n", 1244.9) // Prints Hoogte: 1.244,9 meter
```
I created another issue #26767 before this investigation to improve the documentation, however now I'm not sure if it's a documentation issue, or a design issue.
