### ISSUE TITLE
google: cla.developers.google.com does not have account switcher

### ISSUE THREAD

**Issue by lukmdo** [golang/go#26764]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

.

### Does this issue reproduce with the latest release?

.

### What operating system and processor architecture are you using (`go env`)?

.

### What did you do?

1) tried to follow https://golang.org/doc/contribute.html#cla
2) found no google account switch on https://cla.developers.google.com/about/google-individual
3) used incognito tab as workaround 

<img width="1277" alt="screen shot 2018-08-02 at 13 26 25" src="https://user-images.githubusercontent.com/87109/43583710-412fd180-9658-11e8-9490-d9c1ce915cc3.png">

### What did you expect to see?

Standard Google account style switch 
<img width="373" alt="screen shot 2018-08-02 at 13 31 20" src="https://user-images.githubusercontent.com/87109/43583772-70b5829c-9658-11e8-9dbf-88a31835e1fc.png">

Or at least explain why/how it is this way on https://cla.developers.google.com/about

### What did you see instead?

No account switch

**Comment by myitcv** [comment]
@andybons - any idea who we can ping on this?

**Comment by bradfitz** [comment]
@willnorris owns that.

**Comment by willnorris** [comment]
Unfortunately, we don't have an ETA for that.  We know it's a pain, and we do intend to fix it, but can't say when.  In the meantime, I heard someone mention you can append "?authuser=1" to the URL to switch between users.  I haven't tried it myself, and it's not a feature we intentionally built-in to the system... I think it just comes for free with one of the libraries we're using.

**Comment by ALTree** [comment]
It seems to me that this issue in not really specific to the Go project (other Google OS project use the CLA), and it's not actually actionable specifically by members of the Go team or contributors to the Go project. The problem is also known to the maintainer of the page. I think we can close here.
