### ISSUE TITLE
encoding/xml: bulleted lists badly formatted in documentation

### ISSUE THREAD

**Issue by bcmills** [golang/go#26778]
The bulleted lists in the doc comments for Marshal, Unmarshal, and perhaps others are indented in a way that confuses the formatter for golang.org/pkg. (It thinks they're code instead of prose.)

![screenshot 2018-08-02 at 16 42 16](https://user-images.githubusercontent.com/5200974/43610070-46188316-9673-11e8-9f3b-f9314c1451e4.png)

**Comment by cespare** [comment]
Isn't this intentional, hacky workaround for #7873?

**Comment by bradfitz** [comment]
"Working as Compromised"

**Comment by bcmills** [comment]
Maybe, but to paraphrase a fashion tip: write for the formatter you have, not the formatter you want.

**Comment by bradfitz** [comment]
Um, that's exactly what we did. Did you get the quote backwards?

**Comment by cespare** [comment]
@bcmills btw you may find my examples listed at https://github.com/golang/go/issues/7873#issuecomment-326833843 to be interesting. In at least one place (net/http) we used a different workaround (unicode bullets). Maybe you will be motivated to add your voice  to #7873 :)

**Comment by bcmills** [comment]
> Um, that's exactly what we did.

I mean: if we can't render bulleted lists, don't use them at all. (Paragraphs‽)

**Comment by cespare** [comment]
@bcmills well, we have a lot of instances of this type of list in the stdlib; maybe this bug should be closed? Unless you want to try to make the change across the whole codebase (unlikely to be popular, I imagine).
