### ISSUE TITLE
doc: Contribution guidelines should specify git origin

### ISSUE THREAD

**Issue by ijt** [golang/go#26772]
I'm creating a duplicate of issue #10130, which was IMHO wrongly closed and then frozen. The contributing guide as it stands leaves out a key piece of information about how to contribute. Hunting around for it on the web isn't better than having it in the guide, even if including it makes the guide slightly more verbose.

Here is the text of the original issue, as valid now as when it was originally reported:

"The contribution guidelines don't mention that git origin should be https://go.googlesource.com/go.

git-codereview: git origin must be a Gerrit host, not GitHub: https://github.com/golang/go.git"

**Comment by bontibon** [comment]
The contribute page was updated in CL 117178 (dd0e7a95344a3ef959d9373235d250876c9a4475).

**Comment by ijt** [comment]
Looks good.
