### ISSUE TITLE
x/crypto/acme/autocert: allow caller to supply a Listener

### ISSUE THREAD

**Issue by kr** [golang/go#26780]
The current autocert API always opens a Listener on port 443, which is nice because there's no way to mess it up. But I'd like to run an autocert-using process with minimal privileges, including not being able to bind to low-numbered ports. Instead, I want to have it inherit its listen fd from the parent process.

Would it be reasonable to add a "TCPListener" field on Manager, something like:

```
type Manager struct {
    ...

    // TCPListener is the underlying TCP listener used by method
    // Listener to obtain TCP connections.
    // If nil, Listener opens a new listener on port 443.
    TCPListener net.Listener
}
```

Or is there some other more suitable way to do this?

I know I can drop privileges after starting autocert, but then it's more important to audit all the package initializers in all my dependencies. Of course I do that anyway, but it's nice to have the belt-and-suspenders protection of also not having privileges in the first place.

**Comment by FiloSottile** [comment]
Listener is the ultimate helper function, if you need something more complex, any reason you can't use `Manager.TLSConfig` and `tls.NewListener`, reimplementing `Manager.Listen`?

**Comment by kr** [comment]
Hah, yes I just did exactly that. It was much easier than I expected. Seeing the field `m` in wrapper type `listener` made me afraid it would be impossible to reimplement `Manager.Listener` (due to possibly accessing unexported things on `m`), but now I know `m` is completely unused! 😁

 The only sad part was having to reimplement the keepalive wrapper, but that was minor. (Should there be a helper for that piece somewhere in the stdlib, I wonder?)

Sorry for the noise!
