### ISSUE TITLE
blog: remove panic and recover example from panic recover defer entry

### ISSUE THREAD

**Issue by nhooyr** [golang/go#26799]
At https://blog.golang.org/defer-panic-and-recover

> For a real-world example of panic and recover, see the json package from the Go standard library. It decodes JSON-encoded data with a set of recursive functions. When malformed JSON is encountered, the parser calls panic to unwind the stack to the top-level function call, which recovers from the panic and returns an appropriate error value (see the 'error' and 'unmarshal' methods of the decodeState type in decode.go).

However, this is a poor example and a misuse of panic and recover as exceptions. See https://golang.org/doc/effective_go.html#panic

The example will be invalid soon with the release of go 1.11 as well. The panic/recover was removed from the unmarshal code. See master's https://github.com/golang/go/blob/65fa2b615b72c1fa61a718f2e3a756833f153cc3/src/encoding/json/decode.go#L170-L185 versus go 1.10's https://github.com/golang/go/blob/4c77cb3087363f2ebab565bd2b46935749ca7dd2/src/encoding/json/decode.go#L171-L191

Interesting and relevant article: https://about.sourcegraph.com/blog/go-when-is-it-ok-to-recover/

**Comment by meirf** [comment]
If the decision is to replace that reference with some other "real world" example, my vote is to have the link include the commit hash. But I don't think we should reference real world code at all since referencing old code can be confusing when someone tries to find that code in master.

**Comment by seankhliao** [comment]
fixed to point to encode (which still uses panic) in #30170,  https://golang.org/cl/176757
