### ISSUE TITLE
x/build: stop testing dev.boringcrypto branch on so many builders

### ISSUE THREAD

**Issue by bradfitz** [golang/go#26791]
We really only care about testing the dev.boringcrypto branch on linux/amd64, really. Right now we're testing it on *everything*.

**Comment by bradfitz** [comment]
Probably in cmd/coordinator's skipBranchForBuilder and/or x/build/dashboard/builders.go.

**Comment by FiloSottile** [comment]
I suggest testing it on at least *one* other builder, because the fallbacks are supposed to keep working.

**Comment by bradfitz** [comment]
If we need to pick another non-linux/amd64 builder, at least pick a GCE-based one where we have lots of capacity. So not Darwin, and not arm. windows/386 gets a different GOOS and a different GOARCH with one new builder. Or freebsd/386, but freebsd and linux might be too similar.

**Comment by dmitshur** [comment]
Sounds like the decision is to use `windows/386`. I'll proceed with that for now, but happy to change it if there's further feedback.
