### ISSUE TITLE
jumps over declaration of matched ? "goto" could not through this deep ?

### ISSUE THREAD

**Issue by jason-chang** [golang/go#26804]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

my code is here
https://play.golang.org/p/r5ucxB17EXS

### What did you expect to see?
some files remove from the filesystem.

### What did you see instead?
prog.go:68:10: goto RMFILE jumps over declaration of matched, err at prog.go:74:16

**Comment by ALTree** [comment]
The specs forbids doing that

> Executing the "goto" statement must not cause any variables to come into scope that were not already in scope at the point of the goto.

The `goto RMFILE` line jumps to a location where `matched` is in scope, but matched is declared after the `goto`, which is not allowed.

**Comment by ianlancetaylor** [comment]
This is working as documented and intended, so closing.

**Comment by jason-chang** [comment]
@ALTree 
Thank you, i resolved this problem by mv the define statements to above first "goto" statement . 
see:
https://play.golang.org/p/nKleD-AgDGr
