### ISSUE TITLE
/text/template/parse package should be move to /internal/templateparse

### ISSUE THREAD

**Issue by nhooyr** [golang/go#26805]
On https://golang.org/pkg/text/template/parse/ the docs say

> Package parse builds parse trees for templates as defined by text/template and html/template. Clients should use those packages to construct templates rather than this one, which provides shared internal data structures not intended for general use.

If they are shared internal data structures and not intended for general use, they shouldn't be available to be imported by Go programs and so the package should move to `/internal/templateparse`

**Comment by kardianos** [comment]
This has been discussed before. The parse package has many users, even if it was not intended to. It may break, but we still try not to.
