### ISSUE TITLE
net/http transport RoundTrip take a long time

### ISSUE THREAD

**Issue by xiaoxi1989** [golang/go#26819]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/xxxx/gopath"
GORACE=""
GOROOT="/root/xxxx/go"
GOTMPDIR=""
GOTOOLDIR="/root/cxx/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build860569280=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
req, err := http.NewRequest("GET", "https://xxxxxxxxxxxx:6443",strings.NewReader("name=cjb"))
if err != nil {
    fmt.Println("get request failed:", err)
    return
}
fmt.Println(time.Now().String())
if _,err := tr.RoundTrip(req);err != nil {
    fmt.Println("RoundTrip failed:", err)
    return
}
fmt.Println(time.Now().String())

**if host in hosts,it takes**
```
2018-08-06 02:50:12.696055215 +0000 UTC m=+0.002155049
2018-08-06 02:50:12.70712723 +0000 UTC m=+0.013227079
```

**if not**
```
2018-08-06 02:51:00.494583789 +0000 UTC m=+0.002135540
2018-08-06 02:53:07.789948661 +0000 UTC m=+127.297500213
```

it takes about 2 minutes，why?

### What did you expect to see?
curl -k  -w %{time_namelookup}::%{time_connect}::%{time_starttransfer}::%{time_total}::%{speed_download}"\n"   -XGET  'https://xxxx:6443/'
0.004::0.005::0.113::0.113::1140.000

dns response only 0.004s in curl request.

**Comment by xiaoxi1989** [comment]
trace log:
2018-08-06 03:20:52.051619477 +0000 UTC m=+0.002124773
GetConn: 2018-08-06 03:20:52.051897545 +0000 UTC m=+0.002402601
dns start: 2018-08-06 03:20:52.051978475 +0000 UTC m=+0.002483412
dns end: 2018-08-06 03:20:52.073871741 +0000 UTC m=+0.024376772
ConnectStart: 2018-08-06 03:20:52.073898531 +0000 UTC m=+0.024403457
ConnectDone: 2018-08-06 03:22:59.265916882 +0000 UTC m=+127.216421978
ConnectStart: 2018-08-06 03:22:59.265958567 +0000 UTC m=+127.216463501
ConnectDone: 2018-08-06 03:25:06.497907548 +0000 UTC m=+254.448412579
ConnectStart: 2018-08-06 03:25:06.497947231 +0000 UTC m=+254.448452288
ConnectDone: 2018-08-06 03:25:06.498662524 +0000 UTC m=+254.449167521
TLSHandshakeStart: 2018-08-06 03:25:06.498718558 +0000 UTC m=+254.449236211
TLSHandshakeDone: 2018-08-06 03:25:06.507852012 +0000 UTC m=+254.458357058
GotConn: 2018-08-06 03:25:06.507881687 +0000 UTC m=+254.458386702
2018-08-06 03:25:06.508901456 +0000 UTC m=+254.459406464

**Comment by meirf** [comment]
@xiaoxi1989 thanks for reporting a possible bug. To help us narrow down what the problem is, can you please include a complete and runnable code sample? For example, we can't see what `tr` is set to.

**Comment by ianlancetaylor** [comment]
What happens if you run the program with the environment variable `GODEBUG=netdns=cgo`?

**Comment by xiaoxi1989** [comment]
@meirf 

```
package main

import (
	"crypto/x509"
	"io/ioutil"
	"fmt"
	"crypto/tls"
	"net/http"
	"net/http/httptrace"
	"strings"
	"time"
)

func main() {
	pool := x509.NewCertPool()
	caCertPath := "./ca.pem"

	caCrt, err := ioutil.ReadFile(caCertPath)
	if err != nil {
		fmt.Println("ReadFile err:", err)
		return
	}
	pool.AppendCertsFromPEM(caCrt)

	cliCrt, err := tls.LoadX509KeyPair("./admin.pem", "./admin-key.pem")
	if err != nil {
		fmt.Println("Loadx509keypair err:", err)
		return
	}

	tr := &http.Transport{
		TLSClientConfig: &tls.Config{
			RootCAs:      pool,
			Certificates: []tls.Certificate{cliCrt},
		},
	}

	trace := &httptrace.ClientTrace{
		DNSStart: func(dnsInfo httptrace.DNSStartInfo) {
			fmt.Printf("dns start: %v\n", time.Now())
		},
		DNSDone: func(dnsDoneInfo httptrace.DNSDoneInfo) {
			fmt.Printf("dns end: %v\n", time.Now())
		},


		ConnectStart: func(network, addr string) {
			fmt.Printf("ConnectStart: %v\n", time.Now())
		},

		ConnectDone: func(network, addr string, err error) {
			fmt.Printf("ConnectDone: %v\n", time.Now())
		},


		TLSHandshakeStart: func() {
			fmt.Printf("TLSHandshakeStart: %v\n", time.Now())
		},

		TLSHandshakeDone: func(state tls.ConnectionState,err error) {
			fmt.Printf("TLSHandshakeDone: %v\n", time.Now())
		},

		GetConn :func(hostPort string) {
			fmt.Printf("GetConn: %v\n", time.Now())
		},

		GotConn : func(httptrace.GotConnInfo) {
			fmt.Printf("GotConn: %v\n", time.Now())
		},

	}



	//client := &http.Client{Transport: tr}
	req, err := http.NewRequest("GET", "https://xxxx:6443",
		strings.NewReader("name=cjb"))
	if err != nil {
		fmt.Println("get request failed:", err)
		return
	}

	req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))


	fmt.Println(time.Now().String())
	if _,err := tr.RoundTrip(req);err != nil {
		fmt.Println("RoundTrip failed:", err)
		return
	}

	fmt.Println(time.Now().String())

}
```

**Comment by xiaoxi1989** [comment]
@meirf  i mean url configuring in the /etc/hosts file

**Comment by meirf** [comment]
@xiaoxi1989 can you please log the error in ConnectDone? I assume there's some error since it keeps trying to redial.

(Also ideally, please log network/addr for both ConnectStart/ConnectDone. Feel free to anonymize them so long as you're consistent.)

**Comment by xiaoxi1989** [comment]
@meirf  thx,  the problem is connect timeout and retry in three times.
