### ISSUE TITLE
cmd/compile: poor error for constant using missing import 

### ISSUE THREAD

**Issue by dsymonds** [golang/go#26818]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Playground.

### Does this issue reproduce with the latest release?

I haven't checked, but the playground says it is running Go 1.10.3.

### What did you do?

https://play.golang.org/p/KDfoNw1JzXb

```go
package main

import (
	"fmt"
)

func main() {
	const delay = 5 * time.Second
	fmt.Println(delay)
}
```

### What did you expect to see?

One error, pointing out that I didn't import `"time"`.

### What did you see instead?

Two errors, one of which is misleading:

```
prog.go:8:8: const initializer 5 * time.Second is not a constant
prog.go:8:20: undefined: time
```

The first error is outright wrong if the `"time"` package was imported, yet it was printed, and worse, it came first. The only useful error there is the second message.

**Comment by ALTree** [comment]
This issue has been fixed, the reproducer above now only prints the second error message. Closing here, then.
