### ISSUE TITLE
Command line doesn't understand underscores '_' in filenames for .go files

### ISSUE THREAD

**Issue by madscientist42** [golang/go#26826]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9

### Does this issue reproduce with the latest release?

Don't know.  

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/frank/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build019925980=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

Pass a file with an underscore in the name as a valid golang entity to be compiled/built...

### What did you expect to see?

A built .go golang file to a linkable binary.

### What did you see instead?

No buildable go language candidates for that filename.

**Comment by cznic** [comment]
Which command (cf. 'command line') did you run? What does the file name look like? A concrete example of such a file name would be the best.

**Comment by ianlancetaylor** [comment]
As is documented at https://golang.org/cmd/go, files whose names begin with an underscore character are ignored by the go tool.  Closing this issue as working as documented and intended.  Please comment if you disagree.

**Comment by madscientist42** [comment]
Let me get back into work and past my morning meetings...  I'll push what I
had.  Was the weirdest thing, really...
