### ISSUE TITLE
syscall: StartProcess blocked at acquire lock

### ISSUE THREAD

**Issue by wushukai** [golang/go#26836]
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?

We have not tested yet. 

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build598025583=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

Our service will start subprocess periodically. 

And we found some goroutines hanged for competing ForkLock.Lock(), but none succeed. Stack of one blocked goroutine is listed below

>  goroutine 1526643 [semacquire, 8274 minutes]:
>  sync.runtime_SemacquireMutex(0x1a2aba4)
>  /usr/local/go/src/runtime/sema.go:62 +0x34
>  sync.(*Mutex).Lock(0x1a2aba0)
>  /usr/local/go/src/sync/mutex.go:87 +0x9d
>  sync.(*RWMutex).Lock(0x1a2aba0)
>  /usr/local/go/src/sync/rwmutex.go:86 +0x2d
>  syscall.forkExec(0xce1c2b, 0x7, 0xc426b93410, 0x3, 0x3, 0xc42019f9e8, 0x0, 0x0, 0x0)
>  /usr/local/go/src/syscall/exec_unix.go:185 +0x1fd
>  syscall.StartProcess(0xce1c2b, 0x7, 0xc426b93410, 0x3, 0x3, 0xc42019f9e8, 0x2, 0x4, 0xc4244941e0, 0xc42019f9b8)
>  /usr/local/go/src/syscall/exec_unix.go:240 +0x64
>  os.startProcess(0xce1c2b, 0x7, 0xc426b93410, 0x3, 0x3, 0xc42019fb90, 0xc426b93440, 0x3, 0x3)
>  /usr/local/go/src/os/exec_posix.go:45 +0x1a3
>  os.StartProcess(0xce1c2b, 0x7, 0xc426b93410, 0x3, 0x3, 0xc42019fb90, 0x0, 0x0, 0x28)
>  /usr/local/go/src/os/exec.go:94 +0x64
>  os/exec.(*Cmd).Start(0xc426e70580, 0xc42019fc01, 0xc424fca850)
>  /usr/local/go/src/os/exec/exec.go:359 +0x3d2
>  os/exec.(*Cmd).Run(0xc426e70580, 0xc424fca850, 0xc426e70580)
>  /usr/local/go/src/os/exec/exec.go:277 +0x2b

And besides the blocked groutines, there are not other stack containing function "forkExec".

The problem occurs sometimes among our production services, but I have not found any way to ensure reproducing this.

Please help provides some clue for debugging this problem...

**Comment by ianlancetaylor** [comment]
What you are describing sounds like a clear bug, but I do not recall any similar reports.  The fork lock is only held briefly and I do not know of any code path in which it could be left locked.  Is there any way that we can reproduce the problem ourselves?  Is it possible that the kernel is sometimes killing a single thread of your program?

**Comment by crvv** [comment]
The `ForkLock` is a public variable. It can be held by any code.
Maybe this isn't a bug of stdlib but some other libraries.

**Comment by wushukai** [comment]
@crvv 
I checked all source code under GOPATH, no other libs use this lock..

**Comment by odeke-em** [comment]
How's it going @wushukai? Any more returns of this bug? Able to perhaps isolate a reproduction?

**Comment by wushukai** [comment]
@odeke-em  The problem was gone after we upgraded to 1.10.3. we had have some experiments in our test environment using version 1.8.3, but had no luck to reproduce..

**Comment by odeke-em** [comment]
>@odeke-em The problem was gone after we upgraded to 1.10.3. we had have some experiments in our test environment using version 1.8.3, but had no luck to reproduce..

Thank you for the update @wushukai!

Given that this bug is elusive/no pulse yet to reproduce it after Go1.10, perhaps we could:
a) Move this issue to unplanned and out of the Go1.12 milestone
b) Close this issue as non-actionable

@ianlancetaylor what do you think we should do?

**Comment by ianlancetaylor** [comment]
It sounds like it can be reproduced in newer versions of Go, so I think we can close this.  Thanks.
