### ISSUE TITLE
cmd/go: modules: git fatal: unrecognized argument: --no-show-signature

### ISSUE THREAD

**Issue by lelvisl** [golang/go#26844]
git.go:381
```go
out, err := Run(r.dir, "git", "log", "-n1", "--format=format:%H %ct %D", "--no-show-signature", rev)
```
But some versions of git (2.4.0 and lower ) can't recognise argument --no-show-signature
This change was added in 
https://github.com/golang/vgo/commit/20939850793927db78c179dcfcd5d4d6f44f2c01#diff-67818c73dedcc22dbe195cd3afc253d8R381

Is it so necessary? Can it be disabled/removed?

**Comment by zegl** [comment]
@lelvisl Which version of go are you using? This bug should be fixed in go1.11beta3: #26501

**Comment by myitcv** [comment]
@lelvisl 

> Will it be fixed in vgo?

Yes: https://groups.google.com/d/msg/golang-dev/BizWQk-hfw4/JdhnnJdJDAAJ

Specifically: https://go-review.googlesource.com/c/vgo/+/127956

I'll close this because there is nothing to do here.
