### ISSUE TITLE
x/tools/go/packages: cannot load the standard library with Tests == true

### ISSUE THREAD

**Issue by dominikh** [golang/go#26847]
### What version of Go are you using (`go version`)?
go version devel +5a720d229d Sat Aug 4 16:37:47 2018 +0000 linux/amd64

### What did you do?
https://play.golang.org/p/BFlNtG5_s3-

### What did you expect to see?
No output

### What did you see instead?
2611 lines of error output by the default error handler, reporting type inconsistencies. An excerpt:

```
/tmp/go/src/archive/zip/struct.go:175:16: cannot use fi.ModTime() (value of type time.Time) as time.Time value in argument to fh.SetModTime
/tmp/go/src/archive/zip/register.go:114:42: cannot convert ioutil.NopCloser (value of type func(r io.Reader) io.ReadCloser) to Decompressor
/tmp/go/src/archive/zip/struct.go:142:9: cannot use (headerFileInfo literal) (value of type headerFileInfo) as os.FileInfo value in return statement: wrong type for method ModTime
/tmp/go/src/archive/tar/common.go:636:12: cannot use fi.ModTime() (value of type time.Time) as time.Time value in struct literal
/tmp/go/src/os/stat_unix.go:20:21: cannot use &fs.sys (value of type *syscall.Stat_t) as *syscall.Stat_t value in argument to f.pfd.Fstat
/tmp/go/src/os/file_posix.go:184:32: cannot use t (variable of type time.Time) as time.Time value in argument to f.pfd.SetWriteDeadline
```

Note that all of the reported errors seemingly don't make any sense. Also note that the issue goes away when setting Tests = false.

/cc @alandonovan @ianthehat

**Comment by suzmue** [comment]
This can be recreated with importing two packages from std lib:  https://play.golang.org/p/UFGZnKjm502

This issue comes from a regular package incorrectly importing the test variant of another package.

For example, in the import graph, "net/http" imports "crypto/tls [crypto/tls.test]", when it should just be importing "crypto/tls"
