### ISSUE TITLE
cmd/go: go1.11beta3 does not automatically resolve revision

### ISSUE THREAD

**Issue by swtch1** [golang/go#26843]
### (`go version`)
go version go1.11beta3 windows/amd64

### (`go env`)
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jxt82ty\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\jxt82ty\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Users\jxt82ty\sdk\go1.11beta3
set GOTMPDIR=
set GOTOOLDIR=C:\Users\jxt82ty\sdk\go1.11beta3\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\tmp\pcf_config_generator\pcfconfgen\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\jxt82ty\AppData\Local\Temp\1\go-build932205774=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I tried to resolve dependencies with `go mod tidy` where the required dependency of one of my dependencies was not the current revision.

### What did you expect to see?
I expected go mod to automatically find the revision of the dependency that was required as dep does.

### What did you see instead?
```bash
$ go mod tidy
~~~
go: import "pcf_config_generator/pcfconfgen/prometheus/promcfg" ->
        import "github.com/prometheus/prometheus/discovery/config" ->
        import "github.com/prometheus/prometheus/discovery/azure" ->
        import "github.com/Azure/azure-sdk-for-go/arm/compute": cannot find module providing package github.com/Azure/azure-sdk-for-go/arm/compute
```

The behavior was corrected by adding the following line to go.mod
```require github.com/Azure/azure-sdk-for-go v5.0.0-beta.0.20161028183111-bd73d950fa44+incompatible // indirect```

**Comment by ianlancetaylor** [comment]
CC @rsc @bcmills

**Comment by bcmills** [comment]
Most likely a dup of #26602.
