### ISSUE TITLE
cmd/compile: suboptimal error for &T{} literal mismatch

### ISSUE THREAD

**Issue by dsymonds** [golang/go#26855]
### Does this issue reproduce with the latest release?

In the playground, yes.

### What did you do?

https://play.golang.org/p/uQjX9qTwBz1

```go
package main

type S struct {
	Name T
}

type T struct {
	First string
}

func main() {
	_ = &S{
		Name: &T{First: "Rob"},
	}
}
```

### What did you expect to see?

An error message pointing out the `T` vs. `*T` type problem.

### What did you see instead?

```
prog.go:13:7: cannot use T literal (type *T) as type T in field value
```

The error message is there, but it is phrased oddly. `cannot use T literal` is confusing. I'm using a `&T literal`. If you put aside the parenthetical for a moment, the oddness is apparent: `cannot use T literal as type T in field value`. I think this error message could be improved.

**Comment by smasher164** [comment]
It is also odd because without the parentheses, the phrase `T literal as type T` compares a value with a type.
Would the following be a more clear message?
```
prog.go:13:7: cannot use literal of type *T for field value of type T.
```

**Comment by bcmills** [comment]
CC: @randall77 @griesemer

**Comment by rsc** [comment]
It should say `&T literal`.

**Comment by griesemer** [comment]
typecheckcomplit makes a copy  (typecheck.go:2915) of the complit node it type-checks and then modifies its Op in place. Because n.Orig points to n, this implicitly modifies also n.Orig. During printing, the original node doesn't have the correct Op anymore leading to this error.
