### ISSUE TITLE
encoding/xml: Issue with unmarshal of XML to struct when XML elements have namespace

### ISSUE THREAD

**Issue by rambhavaraju** [golang/go#26859]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
v 1.10

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?
Windows/linux

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/lFP3IBix_O5

### What did you expect to see?
I was expecting the XML to be converted to the struct definiton

### What did you see instead?
Error response.

**Comment by mvdan** [comment]
There's lots of previous issues about `encoding/xml`'s support of namespaces. Are you positive this is not a duplicate?

**Comment by rambhavaraju** [comment]
Thanks @mvdan for your response. I did search in all the issues reported and did try most of the things suggested but none seem to work. If you could point me to one very close to what i have listed here I would appreciate it. Namespace is pretty much there in every element on the xml i shared in my example and the problem is that unmarshal is not happening.

**Comment by mvdan** [comment]
Note that I'm not saying there is a fix or workaround for this. Namespaces have been known to be broken in `encoding/xml` for a while. My point is that this simple case is very likely covered by one of the existing issues on the tracker already.

**Comment by bcmills** [comment]
You have an extra space before the first `"` in `xml: "serv bodyContent"`.

Fixing that, it seems to unmarshal as expected: https://play.golang.org/p/MUFRZdWT1LK

Please let us know if that doesn't fix your issue.
