### ISSUE TITLE
cmd/go: 'go install mod/mainpkg' installs a binary with a version suffix

### ISSUE THREAD

**Issue by bcmills** [golang/go#26869]
As demonstrated in https://golang.org/cl/128137, the current behavior of `go get` and `go install` for main binaries appends a complete version suffix to the name of the binary.

This is somewhat related to #24667, but more severe. I'm not sure when the bug was introduced.

CC: @rsc @myitcv 

```
env GO111MODULE=on

go mod init example.com/m

# get of a binary should install it to $GOPATH/bin
# BUG: vgo-tour should be installed as vgo-tour, not vgo-tour@v1.0.0.
go get research.swtch.com/vgo-tour
exec $GOPATH/bin/vgo-tour@v1.0.0
stdout 'Hello, world.'
rm $GOPATH/bin/vgo-tour@v1.0.0

# install of a binary should install it to $GOPATH/bin
# BUG: vgo-tour should be installed as vgo-tour, not vgo-tour@v1.0.0.
go install research.swtch.com/vgo-tour
exec $GOPATH/bin/vgo-tour@v1.0.0
stdout 'Hello, world.'
```

**Comment by rsc** [comment]
This is because the directory where that command lives is called vgo-tour@v1.0.0 in the module cache. (Still a bug but that explains the bug.)

**Comment by myitcv** [comment]
This is also further complicated if you have a `replace` directive to a local directory, because then the directory name of the replacement is used. It took me ages to work out why I had `gopherjs` and `gopherjs@vx.y.z` in my `GOBIN`.
