### ISSUE TITLE
json unmarshal "null" to empty slice variable(etc: []string{} ) doesn't have err. But when marshal the variable, the value will be "null" instead of "[]"

### ISSUE THREAD

**Issue by Tron2016** [golang/go#26866]
### What version of Go are you using (`go version`)?
go version go1.10.2 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?

	ls := []string{}
	if err := json.Unmarshal([]byte("null"), &ls); err != nil {
		fmt.Println(err)
	}
	fmt.Println(ls)
	if result, err := json.Marshal(ls); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(string(result))
	}

### What did you expect to see?
output:
[]
[]

### What did you see instead?
output
[]
null

**Comment by mvdan** [comment]
This is a common misconception in the `encoding/json` package, but it is very clearly documented:

> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.

If you want to marshal a slice as an empty JSON array, you need to make the slice be non-nil. This has been covered at length before: https://stackoverflow.com/questions/33183071/golang-serialize-deserialize-an-empty-array-not-as-null
