### ISSUE TITLE
cmd/trace: generateTrace execute twice 

### ISSUE THREAD

**Issue by xuanjiazhen** [golang/go#26861]
the func  `generateTrace ` in go1.10.3  

https://github.com/golang/go/blob/go1.10.3/src/cmd/trace/main.go  line 124
```go
log.Print("Serializing trace...")
	params := &traceParams{
		parsed:  res,
		endTime: int64(1<<63 - 1),
	}
	data, err := generateTrace(params)   //first 
	if err != nil {
		dief("%v\n", err)
	}
```

https://github.com/golang/go/blob/go1.10.3/src/cmd/trace/trace.go line 183
```go
if goids := r.FormValue("goid"); goids != "" {
		// If goid argument is present, we are rendering a trace for this particular goroutine.
		goid, err := strconv.ParseUint(goids, 10, 64)
		if err != nil {
			log.Printf("failed to parse goid parameter '%v': %v", goids, err)
			return
		}
		analyzeGoroutines(res.Events)
		g := gs[goid]
		params.gtrace = true
		params.startTime = g.StartTime
		params.endTime = g.EndTime
		params.maing = goid
		params.gs = trace.RelatedGoroutines(res.Events, goid)
	}

	data, err := generateTrace(params)  //second
```

I got a 90M traceout file.when I run `go tool trace traceout.out ` ,this func will executed more than 10 seconds. When I click on the link  (view trace (0s-xxxxxs)), I will wait another 10 seconds. It will be executed again with the same params.  It only makes sense when goid!="".

when I changed the `generateTrace `func's return value to a global varible,the web browser speed improved significantly.

Is this designed to be this or a negligence? Is it better to change the return value to a global variable?

**Comment by hyangah** [comment]
The corresponding code path was changed a lot recently, so no longer relevant to Go1.12.

**Comment by xuanjiazhen** [comment]
@hyangah 
This problem seems to exist in another form on the latest branch. Although the situation is somewhat different, it is still twice.And The new change seems to make it difficult to solve this problem.
https://github.com/golang/go/blob/master/src/cmd/trace/main.go
```go
        log.Print("Splitting trace...")
	ranges = splitTrace(res)
	reportMemoryUsage("after spliting trace")
	debug.FreeOSMemory()
```
https://github.com/golang/go/blob/master/src/cmd/trace/trace.go line 288
```go
func splitTrace(res trace.ParseResult) []Range {
	params := &traceParams{
		parsed:  res,
		endTime: math.MaxInt64,
	}
	s, c := splittingTraceConsumer(100 << 20) // 100M
	if err := generateTrace(params, c); err != nil {    //first
		dief("%v\n", err)
	}
	return s.Ranges
}
```
https://github.com/golang/go/blob/master/src/cmd/trace/trace.go line 267
```go
if err := generateTrace(params, c); err != nil {
		log.Printf("failed to generate trace: %v", err)
		return
	}
```

**Comment by agnivade** [comment]
The code is entirely different now. Please let us know if you are still seeing the problem at tip. Thanks.
