### ISSUE TITLE
cmd/go: no such tool "vet" when running go test

### ISSUE THREAD

**Issue by mpetavy** [golang/go#26864]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.10.3 windows/amd64
Windows 7 64 bit
```

### Does this issue reproduce with the latest release?
It is the latest official release

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=d:\go\bin
set GOCACHE=C:\Users\ogmpetav\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ogmpetav\AppData\Local\Temp\go-build966645826=/tmp/go-build -gno-record-gcc-switches

```

### What did you do?
Run the tests with "go test -v"
Error is generated complaining about missing "vet"
Output of command line:
```
D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ go test -v
go tool: no such tool "vet"
```

### What did you expect to see?
Running tests

### What did you see instead?
`go tool: no such tool "vet"
`

### Workaround
Disable vet on testing with command line parameter "-vet off":
Sample:
`go test -vet off -v
`

**Comment by ALTree** [comment]
Possibly a problem with the windows installer? How did you install go?

 cc @alexbrainman @andybons

**Comment by ALTree** [comment]
Also: can you try with the 1.11beta?

https://groups.google.com/forum/#!msg/golang-announce/Q5N8mPD9dUM/VD3sCPV6BQAJ

**Comment by mpetavy** [comment]
Tested with `go1.11beta3 windows/amd64`: **worked**!

Unistalled `go1.11beta3 windows/amd64` and re-installed `go1.10.3 windows/amd64` ...

Tested again` go1.10.3 windows/amd64`: **failed**!
But my company installed virus scanner "McAfee Endpoint Security" complaint about a security issue when executed with `go1.10.3 windows/amd64` - see attached log file.

Virus scanners are a PITA ... :-)

```
D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ go version
go version go1.11beta3 windows/amd64

D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ go test -v
=== RUN   TestFilestorage
--- PASS: TestFilestorage (0.02s)
    filestorage_test.go:25: path: C:\Users\ogmpetav\AppData\Local\Temp\golang\591892611
=== RUN   TestCreatePath
--- PASS: TestCreatePath (0.00s)
PASS
ok      github.com/mpetavy/golang/tresor/service/storage        0.258s

D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ echo now installing the official golang 1.10.3 ...
now installing the official golang 1.10.3 ...

D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ go version
go version go1.10.3 windows/amd64

D:\go\src\github.com\mpetavy\golang\tresor\service\storage
$ go test -v
C:\Go\pkg\tool\windows_amd64\vet.exe: fork/exec C:\Go\pkg\tool\windows_amd64\vet.exe: Insufficient system resources exist to complete the requested serv
ice.
FAIL    github.com/mpetavy/golang/tresor/service/storage [build failed]

```

**Comment by mpetavy** [comment]
Verified the checksum: valid.
So I will create and exclusion on virtus detection for the GO tool.
Hopfully 1.11 will remain such as virus scanner compliant as it is now.
Thanks for the support.
--> Issue can be closed
