### ISSUE TITLE
brand: presentation theme: presenter photo should not be hard-coded

### ISSUE THREAD

**Issue by bcmills** [golang/go#26878]
I'm trying to use the Go presentation theme in a new presentation.

In the first slide, there is a presenter photo example (of @cassandraoid with a plush Gopher): https://golang.org/s/presentation-theme#slide=id.g33148270ac_0_143

That specific photo is currently embedded in the “Theme” layer, but it should not be: individual presenters (other than @cassandraoid herself) should always replace it with their own photo.

**Comment by cassandraoid** [comment]
the best solution as of now is to just put your photo over it (I have to do
that for my updated photo as well).

**Comment by bcmills** [comment]
@agnivade, once you've copied the theme to a new document you can customize it however you like. (I've been doing that to address a lot of these issues in my slides.)

The menu option to do it is not particularly discoverable, unfortunately.

![screenshot 2018-08-09 at 09 57 09](https://user-images.githubusercontent.com/5200974/43903534-ad30fb86-9bba-11e8-9db0-903968e24c19.png)

**Comment by agnivade** [comment]
Ah you can edit master ! Amazing. It felt so debilitating not to be able to edit a lot of preset settings. Thanks for the pointer. (I completely missed this option too)

**Comment by eliben** [comment]
I believe this has been fixed now. The presentation template linked from https://go.dev/s/presentation-theme no longer includes a hard-coded photo.
