### ISSUE TITLE
BUG: Can't change GOTOOLDIR environment variable on linux

### ISSUE THREAD

**Issue by Aukstkalnis** [golang/go#26886]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I installed go to /usr/local/go directory. I Added GOTOOLDIR in $HOME/.profile file like this:
export GOTOOLDIR=/media/aukstkalnisde/Disk/Projects/Go_Projects/bin
But that did not worked. So I added to /etc/profile file GOTOOLDIR like this:
export GOTOOLDIR=""

Then logged off and logged in. Then I opened terminal and executed go env command.

#### What did you expect to see?
I expected to see one of GOTOOLDIR I configured.

#### What did you see instead?
GOTOOLDIR="/usr/local/go/bin/pkg/tool/linux_amd64"

#### System details

```
go version go1.10.3 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aukstkalnisde/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/media/aukstkalnisde/Disk/Projects/Go_Projects"
GORACE=""
GOROOT="/usr/local/go/bin"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/bin/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692857751=/tmp/go-build -gno-record-gcc-switches"
uname -sr: Linux 4.15.0-30-generic
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1) stable release version 2.27.
gdb --version: GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
```

**Comment by AlexRouSg** [comment]
Quoting from https://github.com/golang/go/issues/10264#issuecomment-91394026

> GOTOOLDIR is printed by go env for use by things that want to get to the tool dir. It is explicitly NOT something that is pulled from the environment. This is working as intended.

**Comment by meirf** [comment]
@AlexRouSg thanks for finding that comment. I'm going to close this.
