### ISSUE TITLE
cmd/compile: unexpected NUL in input

### ISSUE THREAD

**Issue by sjuliper7** [golang/go#26888]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
i have golang program like this code
package main

import "fmt"

func main() {
	fmt.println("hello world")
}

but when i'm run..  "go run main.go"

C:\Go\src\fmt\print.go:10:2: read C:\Go\src\os\exec.go: unexpected NUL in input

#### System details

```
go version go1.8.3 windows/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="D:\Internship\Golang\Go\"
GORACE=""
GOROOT="C:\Go"
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.3 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.8.3 X:framepointer
gdb --version: GNU gdb 5.2.1
```

**Comment by mikioh** [comment]
Just tried the snippet on play.golang.org and got the following:
```
prog.go:6:1: cannot refer to unexported name fmt.println
prog.go:6:1: undefined: fmt.println
```
Is this what you want instead of "unexpected NUL in input"?

**Comment by cznic** [comment]
> C:\Go\src\fmt\print.go:10:2: read C:\Go\src\os\exec.go: unexpected NUL in input

Note that the code in the OP has only 7 lines but the error is reported for line 10. Perhaps there's something more to the source. Can you please paste the output of `hexdump -C your-file.go` or from any other equivalent program?

**Comment by agnivade** [comment]
The error is reported from line 10 of `fmt/print.go` I believe. In any case, this does sound like the source file is messed up somehow.

**Comment by cznic** [comment]
@agnivade You're right, and I'm sorry.
