### ISSUE TITLE
cmd/go: build produces a non-64bit version on Windows

### ISSUE THREAD

**Issue by iWdGo** [golang/go#26899]
While investigating more efficient ways to evaluate new test scripts, the following issue showed up. It looks related to similar cmd/go issues opened recently. I suppose that a module is produced and not an exe seen the size in dir `cantcompile` :
```
09-08-18  18:25    <DIR>          .
09-08-18  18:25    <DIR>          ..
09-08-18  18:25             2.902 cantcompile
09-08-18  18:23               106 cantcompile.go
```

### What version of Go are you using (`go version`)?
`go version go1.11beta3 windows/amd64`

### Does this issue reproduce with the latest release?
I did not try tip

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\()\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\()\Documents\Google\
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Costa\)\Local\Temp\go-build007169846=/tmp/go-build -gno-record-gcc-switches
```
### What did you do?
I tried several parameters configuration with always the same result where -x -v -work do not provide much information. Work directories are empty at best:
`go build -x -v -work -i -o cantcompile.exe`
`go build -x -v -work -o cantcompile -i`
and `go build -i` produces nothing.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
package cantcompile

import "fmt"

func main() {
	fmt.Println("can't compile if package is not main ?")
}
```
A link on play.golang.org is best.

### What did you expect to see?
Some error message during build probably.

### What did you see instead?
An executable is produced and if you try running it, you receive a message from very very old days.
![gobuild16bit](https://user-images.githubusercontent.com/19574010/43912237-fa4a1f14-9c01-11e8-8179-119dc28dbbb9.JPG)

**Comment by bcmills** [comment]
As @AlexRouSg notes, this seems to be working as designed.

**Comment by iWdGo** [comment]
I forgot to explain the inconsistency that the `go run` message is not displayed during `go build`:
```
C:\Users\()\Documents\Google\CloudSDK\sandbox\src\cantcompile>go run cantcompile.go
go run: cannot run non-main package
```
