### ISSUE TITLE
x/text/message: wrong number formatting for Dutch

### ISSUE THREAD

**Issue by pebbe** [golang/go#26895]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version devel +1b870077c8 Fri Aug 3 17:21:10 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/peter/go"
GOPROXY=""
GORACE=""
GOROOT="/my/opt/go"
GOTMPDIR="/tmp"
GOTOOLDIR="/my/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build550356529=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Compiled and run this program:

```go
package main

import "golang.org/x/text/message"

func main() {
	p := message.NewPrinter(message.MatchLanguage("nl"))
	p.Printf("Hoogte: %.1f meter", 1244.9)
}
```

### What did you expect to see?

Hoogte: 1.244,9 meter

### What did you see instead?

Hoogte: 1,244.9 meter

**Comment by mpvl** [comment]
MatchLanguage only allows Dutch to be selected the catalogue has entries for Dutch, which I reckon it doesn't. Use message.NewPrinter(language.Make("nl")) to get the desired effect.

This could be made clearer in documentation, which is being considered.

**Comment by pebbe** [comment]
This code is from the documentation.
https://godoc.org/golang.org/x/text/message
 It too shows the wrong result, but apparently means to demonstrates that this is the right answer. The answer is wrong.
