### ISSUE TITLE
Returning pointer to struct is allowed while its the struct that implements the given interface. Why? How does this work?

### ISSUE THREAD

**Issue by navgupta14** [golang/go#26901]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
1. https://play.golang.org/p/VJsb5wBoo-h  - struct implementing interface
2. https://play.golang.org/p/qpaScpD1jHd   - pointer to struct implementing interface

### What did you expect to see?
In 1.. when f := &Foo{}, return f should cause an error. My reason is that the struct implemented the interface not the pointer to the struct. Also, in 2., when f := Foo{}, return f causes an error. Why is there a discrepancy in behavior in the two cases. Does this have to do with the memory layout of interfaces, structs and pointers to them or some golang magic behind the scenes.

### What did you see instead?
Returning struct and pointer to it both works.

**Comment by as** [comment]
Pointer receivers imply that an object's state is mutable. An interface that stores a non-pointer type can not modify any fields in the original value, because each method call creates a copy of the value stored in the interface and operates on that. Allowing that to work would likely be very misleading.

**Comment by ianlancetaylor** [comment]
We don't use the issue trackers.  Please see https://golang.org/wiki/Questions .  Thanks.

I don't actually understand what you are asking.  The code does not match the comments.
