### ISSUE TITLE
GOCACHE=off is case-sensitive. GOCACHE=OFF creates a cache dir by name OFF

### ISSUE THREAD

**Issue by mohanraj-r** [golang/go#26908]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes also tested on go version go1.11beta3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/Users/mraj/go/bin"
GOCACHE="/Users/mraj/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mraj/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/742yxrrx0glg93s4z_rwyzkxm0whbv/T/go-build886713011=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
`GOCACHE=OFF go test ./...`

### What did you expect to see?
`GOCACHE` to be turned off 

### What did you see instead?
A dir `OFF` was created in the current dir with many files and folders 
```
# cat OFF/README
This directory holds cached build artifacts from the Go build system.
...
```

The root of the issue seems to be https://github.com/golang/go/blob/master/src/cmd/go/internal/cache/default.go#L39 
```go
	if dir == "off" {
		return
	}
```

I guess I won't be alone in trying out `GOCACHE=OFF` and wondering why its not working ?
Should `if dir == "off"` check be made case-sensitive?

**Comment by mohanraj-r** [comment]
> Should if dir == "off" check be made case-sensitive?

Also make empty value equivalent to `off` e.g. `GOCACHE= go test` would result in cache being turned off. 

Right now it seems empty value to GOCACHE results in using the default cache
```
$ GOCACHE= go env GOCACHE
/Users/mraj/Library/Caches/go-build
```

**Comment by ianlancetaylor** [comment]
Seems to me that this is all working as documented.  Why should we change it?  Permitting people to say either `off` or `OFF` provides no additional functionality.

**Comment by mohanraj-r** [comment]
> Permitting people to say either off or OFF provides no additional functionality.

I would tend to agree. 
Looking at output of `go env` I see the names are all caps (as expected of env vars) and values are all small case. So this would fit with `GOCACHE=off`. But then I also see empty string values of `""` used for some vars. Should `""` then mean that the corresponding setting is turned off e.g. in case of `GOCACHE`?

```
$ go env | grep \"\"
GOEXE=""
GORACE=""
GOTMPDIR=""
CGO_CPPFLAGS=""
```

**Comment by ianlancetaylor** [comment]
For an environment variable it's possible but rarely useful to distinguish between the variable being unset and the variable being set to an empty string.  For most purposes those are treated as the same condition, and I think that is fine.

I'm going to close this issue.

**Comment by mohanraj-r** [comment]
So you are saying that `GOCACHE=""` != `GOCACHE=off` is ok and expected / unambiguous behavior ?

**Comment by ianlancetaylor** [comment]
Yes.  `GOCACHE=""` is equivalent to not setting `GOCACHE` at all, which means using the default cache location.
