### ISSUE TITLE
cmd/link: Filepaths and importpaths are concatenated as-is, should FromSlash (can cause problems under Windows)

### ISSUE THREAD

**Issue by Xjs** [golang/go#26917]
Using [Bazel](https://bazel.build) and [rules_go](https://github.com/bazelbuild/rules_go), a combination of factors leads to `cmd/link` being executed with a `GOROOT` relative to the build workspace folder, whose path can become very long. This resulted in obscure linker error messages such as:

```
external\go_sdk\pkg\tool\windows_amd64\link.exe: cannot open file bazel-out\x64_windows-fastbuild\bin\external\io_bazel_rules_go\windows_amd64_pure_stripped\stdlib%\pkg\windows_amd64/vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20.a: open bazel-out\x64_windows-fastbuild\bin\external\io_bazel_rules_go\windows_amd64_pure_stripped\stdlib%\pkg\windows_amd64/vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20.a: The system cannot find the path specified.
```

Windows appears to be confused by a path that is relative, longer than 255 characters, AND a combination of backslashes and slashes. ([Some more info here.](https://docs.microsoft.com/en-gb/windows/desktop/FileIO/naming-a-file#maxpath))

A fix that worked for me locally would be to use the `filepath` functions in `src/cmd/link/internal/ld/ld.go`, e. g. like https://github.com/Xjs/go/commit/a9738aaeda9186826f3bb41e1e44f80ed348750e .

In experiments I have found that using an absolute `GOROOT` doesn't reproduce the error; I will suggest this workaround to the Bazel rules_go authors, too.

### What version of Go are you using (`go version`)?
`go version go1.10.3 windows/amd64`

### Does this issue reproduce with the latest release?
Last reproduced with https://github.com/golang/go/commit/a9dcbab0fd4b5adfb40cb924f14ee2af9c8938eb .

**Comment by alexbrainman** [comment]
> Using Bazel and rules_go, a combination of factors leads to cmd/link being executed with a GOROOT relative to the build workspace folder, whose path can become very long. This resulted in obscure linker error messages such as:
> 
> external\go_sdk\pkg\tool\windows_amd64\link.exe: cannot open file bazel-out\x64_windows-fastbuild\bin\external\io_bazel_rules_go\windows_amd64_pure_stripped\stdlib%\pkg\windows_amd64/vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20.a: open bazel-out\x64_windows-fastbuild\bin\external\io_bazel_rules_go\windows_amd64_pure_stripped\stdlib%\pkg\windows_amd64/vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20.a: The system cannot find the path specified.

How do I reproduce your problem here? Please, provide small program and instructions to reproduce. Thank you.

Alex

**Comment by alexbrainman** [comment]
> https://github.com/Xjs/go-link-path-concat-bug

There might be other problems.

But
```
SET GOROOT=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\Go
C:\\Go\\pkg\\tool\\windows_amd64\\link.exe -o test.exe test.a
```
GOROOT has to be absolute path, not relative.

Also relative paths on Windows cannot be longer than 255 characters.

I still do not understand what your problem is. What exactly are you trying to do?

Alex

**Comment by Xjs** [comment]
Actually, I'm trying a Bazel build under Windows. Bazel's [rules_go](https://github.com/bazelbuild/rules_go) set the GOROOT to a relative path. (I'm discussing this with the rules_go maintainers as well.) However, I tried to recreate this bug as-is. It would be a lot of overhead to recreate a Bazel build that exhibits this behaviour, so I tried to isolate it as much as possible. If you like, I can provide a Bazel example as well, of course.

My concrete bug report is that `findlib` (https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/ld.go#L106) constructs paths to object files by simply concatenating strings, one of which being the importpath that contains slashes. Under Windows, this results in a path like `very\long\path/fmt` which is not found because relative paths longer than 255 characters cannot have slashes as directory separator.

So I'm suggesting using the `filepath` functions in `findlib` in https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/ld.go#L106.

**Comment by alexbrainman** [comment]
> Actually, I'm trying a Bazel build under Windows.

Thank you for explaining.

> Bazel's rules_go set the GOROOT to a relative path.

I am pretty sure, you cannot have GOROOT set to a relative path. But I will let others to confirm.

> Under Windows, this results in a path like very\long\path/fmt which is not found because relative paths longer than 255 characters cannot have slashes as directory separator.

I do not believe any relative paths on Windows are allowed to be longer than 255 chars. So I don't see why expecting this to work.

Alex
