### ISSUE TITLE
cmd/go: support module path with port number

### ISSUE THREAD

**Issue by henryykt** [golang/go#26912]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

$ vgo version
go version go1.10.3 linux/amd64 vgo:devel +1b870077c8

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"

### What did you do?

Run "vgo build" on a project with a module pointing to an internal bitbucket repository.

go.mod contains the following line:

replace mycompany.com/mymodule v0.0.0 => bitbucket.mycompany:7990/lib/mymodule v0.0.0-20170726040925-aae89c28e061

### What did you expect to see?

Expected "vgo build" to succeed and produce an executable

### What did you see instead?

"vgo build" fails with:

import "mycompany.com/mymodule": malformed module path "bitbucket.mycompany.com:7990/lib/mymodule": invalid char ':'

The same fails in go1.11beta3.

Note: this used to work in vgo before commit 2093985.

**Comment by ianlancetaylor** [comment]
CC @rsc @bcmills

**Comment by bcmills** [comment]
If you're using `replace` directives to give the module location, everyone who uses your module will
https://tip.golang.org/cmd/go/#hdr-Remote_import_paths

**Comment by bcmills** [comment]
Module paths identify modules, which can be fetched by a number of different protocols (including proxies). Port numbers would put too much of the internals of the distribution mechanism in the path.

**Comment by henryykt** [comment]
ic. Thanks for the clarification.
