### ISSUE TITLE
x/tools/go/packages: document whether Package.GoFiles and Package.Syntax contain the files in the same order

### ISSUE THREAD

**Issue by kevinburke** [golang/go#26915]
The documentation for packages.Package.GoFiles says:

```go
    // GoFiles lists the absolute file paths of the package's Go source files.
    GoFiles []string
```

The documentation for packages.Package.Syntax says:

```go

    // Syntax is the package's syntax trees, for the files listed in GoFiles.
    //
    // Mode LoadSyntax set this field for packages matching the patterns.
    // Mode LoadSyntaxAll sets this field for all packages, including dependencies.
    Syntax []*ast.File
```

Are these always going to be in the same order?

Specifically, I'm trying to alter the contents of an `*ast.File` and write it back to disk. How can I get the filename of the abstract syntax tree I am trying to use?

**Comment by bcmills** [comment]
CC: @ianthehat @alandonovan

**Comment by alandonovan** [comment]
Yes, they will always be in the same order.  You can assume the correspondence, or you can obtain the filename from the syntax tree using `fset.Position(Syntax[i].Pos()).File`.

**Comment by adonovan** [comment]
The documentation added by https://go.dev/cl/375376 effectively addresses this issue.
