### ISSUE TITLE
encoding/csv bug?

### ISSUE THREAD

**Issue by FrankIT60** [golang/go#26919]
go version go1.10.2 darwin/amd64

I need to process a csv file that uses '|' as a separator,
The fields of the file contain several quotation marks character [ " ], evidently the result of an incorrect quoting.
The question is, why the parser goes into error considering the characters [ " ] if the separator is [ | ]?
is it a bug or is it correct?

Try this example.

https://play.golang.org/p/PsB8aOec9Rz

T.I.A.
Franco

**Comment by FMNSSun** [comment]
Regardless of the separator a `"` starts a quoted-field and inside a quoted-field `""` is treated as a single quote.  Thus `"Rob""|"Pike"|rob` is seen as `"Rob"|` I presume.

**Comment by bcmills** [comment]
The behavior you're seeing is correct.

`encoding/csv` follows the format described in [RFC 4180](https://tools.ietf.org/html/rfc4180). See §2c7 (emphasis mine):
> 7. If double-quotes are used to enclose fields, then a double-quote appearing inside a field **must** be escaped by preceding it with another double quote. […]
