### ISSUE TITLE
go/format: Source output is not idempotent 

### ISSUE THREAD

**Issue by dsnet** [golang/go#26930]
Consider the following:
```go
package main

import (
	"bytes"
	"go/format"
	"testing"
)

func Test(t *testing.T) {
	const src = `
package foo

var _ = foo{
F1: []string{
},
Field2: []string{},
}
`
	want, err := format.Source([]byte(src))
	if err != nil {
		t.Fatalf("format.Source() error: %v", err)
	}
	got, err := format.Source([]byte(want))
	if err != nil {
		t.Fatalf("format.Source() error: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("gofmt was not idempotent")
	}
}
```

Running `format.Source` on the output of itself should produce no changes. However, it does. Bisect traces the regression to https://go-review.googlesource.com/125260.

\cc @mvdan @griesemer

**Comment by mvdan** [comment]
Thanks - will take a look as soon as I can.

**Comment by griesemer** [comment]
I don't believe this is a release blocker. For one, there are other situations where gofmt is not idempotent, and they have been around for a long time. That is not to mean that we don't care; it just means that we have been able to live with it for now.  We do want to fix these but it doesn't warrant blocking a release.

In this case the problem arises only (as far as I can tell) if the (first) entry `[]string{}` is an empty slice/composite literal where the closing `}` is on a new line. It's uncommon. There's a manual work-around (write `{}` on a single line) which is the common way of writing it.

Marking for 1.12 until further evidence that this is more urgent.

**Comment by dsnet** [comment]
This is a regression that is breaking some tests.

**Comment by griesemer** [comment]
The change that was submitted 4 days ago also fixed a regression. Let's look at the broken tests (in person). And let's keep thinking about a possible fix for this.
