### ISSUE TITLE
tour: runtime error on slices section

### ISSUE THREAD

**Issue by KayvanMazaheri** [golang/go#26934]
### What did you do?

I tried to run the example on https://tour.golang.org/moretypes/8 and received an unexpected runtime error message.

I ran the example on my local machine and it produced the right output
I think this has something to do with source codes being cached on http://tour.golang.org

### What did you expect to see?
```
John Paul George Ringo]
[John Paul] [Paul George]
[John XXX] [XXX George]
[John XXX George Ringo]
```

### What did you see instead?
```
fatal error: runtime: out of memory
...
```

**Comment by ALTree** [comment]
Thanks for the report. 

This has been reported by several people in the past days, in https://github.com/golang/tour/issues/541. The underlying issue is https://github.com/golang/go/issues/26926. I'm closing this issue as a dup of that one.
