### ISSUE TITLE
Version does not match do tool version

### ISSUE THREAD

**Issue by helloyurii** [golang/go#26933]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I was learning Golang for the first time.

My problem is compile: `version "go1.10.3" does not match go tool version "go1.10.1"`
when I execute the command "`go build`"

#### Does this issue reproduce with the latest release (go1.10.3)?
Yes

#### System details

```
go version go1.10.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/helloyuri/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/helloyuri/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build764428078=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.10.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
uname -sr: Linux 4.15.0-30-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1) stable release version 2.27.
gdb --version: GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
```

**Comment by agnivade** [comment]
Please explain in further detail the exact steps that you performed.

**Comment by helloyurii** [comment]
I did -->
Download: go1.10.3.linux-amd64.tar.gz
$ sudo tar -C /usr/local -xzf go1.10.3.linux-amd64.tar.gz

**Comment by agnivade** [comment]
Perhaps I was not clear. I would like to know the exact steps that you did that resulted in the error that you saw. This is needed so that we can reproduce the issue and debug it if it is a real bug.

So far, you have mentioned you have extracted the tar archive. Does this give the error `version "go1.10.3" does not match go tool version "go1.10.1"` ? I don't believe so. Please mention the entire set of steps for us to see the error that you see.

Thank you.

**Comment by AlexRouSg** [comment]
@agnivade 

I found #22814 and a bunch of similar reports in a few places, all of them were either a bad install/update, or the user had multiple versions installed and the binary they were using did not match up with $GOROOT

**Comment by agnivade** [comment]
Looks like that is the case here. @helloyurii - can you confirm ?

**Comment by helloyurii** [comment]
Yes! I think so. I don't have the steps now. But, I think @AlexRouSg is right. I try to unistall Go and reinstall. What can I do? T.T

**Comment by agnivade** [comment]
Please reach out to the forums mentioned [Questions](https://github.com/golang/go/wiki/Questions) wiki page. Folks there will gladly help you out.

Thank you.
