### ISSUE TITLE
cgo: aa_change_hat with libapparmor shows inconsistent behaviour

### ISSUE THREAD

**Issue by gdemarcsek** [golang/go#26935]
Context: Trying to use libapparmor from Go using cgo (on Ubuntu 18.04/VirtualBox).
### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build813461694=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
I was hoping to use `cgo` to add support for AppArmor `aa_change_hat` API:

```go
package main

/*
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/apparmor.h>

int apparmor_change_hat(char* hat_name, unsigned long token) {
	printf("Changing hat to: %s (token: %ld)\n", hat_name, token);
	int r = aa_change_hat(hat_name, token);
	printf("aa_change_hat returned : %d\n", r);
	return r;
}
*/
// #cgo LDFLAGS: -lapparmor
import "C"
import "unsafe"
import "log"

func aa_change_hat(hat string, token uint64) error {
	cs := C.CString(hat)
	defer C.free(unsafe.Pointer(cs))
	retval, err := C.apparmor_change_hat(cs, C.ulong(token))
	log.Printf("%d\n", retval)
	if retval != 0 {
		return err
	}

	return nil
}

func main() {
	err := aa_change_hat("lolhat", 1234)
	if err != nil {
		log.Fatal(err)
	}
}
```

### What did you expect to see?
Since the hat `lolhat` does not exist and my binary is not even confined with AppArmor, I expect the `aa_change_hat` call fail and return `-1` (according to its specification: http://manpages.ubuntu.com/manpages/bionic/man2/aa_change_hat.2.html) so, I was expecting this output:

```
Changing hat to: lolhat (token: 1234)
aa_change_hat returned : -1
```

from inside the C function, as it does if I compile the C part separately using `gcc`:

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/apparmor.h>

int apparmor_change_hat(char* hat_name, unsigned long token) {
	printf("Changing hat to: %s (token: %ld)\n", hat_name, token);
	int r = aa_change_hat(hat_name, token);
	printf("aa_change_hat returned : %d\n", r);
	return r;
}

int main() {
	apparmor_change_hat("lolhat", 1234);
}
```

and I run it:

```
$ gcc tmp.c -o tmp -lapparmor
$ ./tmp
Changing hat to: lolhat (token: 1234)
aa_change_hat returned : -1
```

Notice that `aa_change_hat` returns `-1` as it should. 

### What did you see instead?
If you run the go app, the output will be:

```
Changing hat to: lolhat (token: 1234)
aa_change_hat returned : 0
2018/08/11 15:43:58 0
```

which is incorrect: I would expect the call to the C function `aa_change_hat` behave the same way, so the return value should be `-1` and `errno` should be set appropriately but that doesn't seem to happen.

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
I don't know what is happening here, but the output from your C code seems to show that it is happening entirely within C.  I don't know what AppArmor does or how it works.  It may be that it is somehow incompatible with Go, though I don't know why that would be.

I'm going to close this since I think it's unlikely to be fixed by any change to Go.
