### ISSUE TITLE
net/http: allow configuring read timeout of response body with transport

### ISSUE THREAD

**Issue by nhooyr** [golang/go#26941]
I'd like `ResponseHeaderTimeout` but for the response body.

**Comment by meirf** [comment]
I commented on your other issue here: https://github.com/golang/go/issues/26942#issuecomment-412361433. If you have the same response, let's just keep the convo there. Otherwise, could be better to have separate conversations.

**Comment by nhooyr** [comment]
Just realized I can just cancel the request context to make this work. All is good.
