### ISSUE TITLE
x/build: mirror the "dl" repo to GitHub

### ISSUE THREAD

**Issue by dmitshur** [golang/go#26949]
Issue #23223 has resulted in the creation of a new repository:

https://go.googlesource.com/dl

That new repository is currently not mirrored to GitHub, hence this is 404:

https://github.com/golang/dl (404)

Is that the result of a conscious decision? Or has the decision not been made yet, and this is a potential follow-up task? /cc @bradfitz @andybons

**Comment by agnivade** [comment]
If it's not an issue, I think its good to mirror it on github to be consistent with other repos. I wanted to take a look at the code one day and was surprised to not find it in github. 

https://github.com/golang/go/issues/26810 may be one such issue where a PR can be expected.

**Comment by rsc** [comment]
I'm amused about "It doesn't need to be on GitHub since there won't be any PRs" since until a few months ago all our repos were on GitHub and none of them accepted PRs. :-P

**Comment by dmitshur** [comment]
I agree with Brad's arguments, the value added is not very high. However, I think we should do it, for the following 2 reasons:

- Consistency and simplicity. "And probably better to not have any snowflake repos." Exactly. All other Go repos are mirrored, there's no good reason why this one shouldn't be. It's simpler just to mirror all. People won't run into the unexpected situation where one repo isn't mirrored and wonder why.
- It's a good chance for me to practice and learn how to do this. I'm sure we'll have some new repo in the future that we will actively want to mirror, and it'd be great if I can help with doing that.

**Comment by bradfitz** [comment]
All yours.

**Comment by dmitshur** [comment]
With [CL 133896](https://golang.org/cl/133896) merged, all relevant components redeployed, and some additional steps taken (to be documented), this is done. Mirroring the dl repo to GitHub, and its PRs back to Gerrit now works.

The last thing to confirm after this is that googlebot will apply the "cla: yes"/"cla: no" labels on future PRs.

**Comment by dmitshur** [comment]
> The last thing to confirm after this is that googlebot will apply the "cla: yes"/"cla: no" labels on future PRs.

Verified that it works well in https://github.com/golang/dl/pull/2:

![image](https://user-images.githubusercontent.com/1924134/45326936-723ec800-b523-11e8-8747-10326edad537.png)
