### ISSUE TITLE
net/http: document that cancelling a request unblocks reads on the response body

### ISSUE THREAD

**Issue by nhooyr** [golang/go#26947]
If you create a `*http.Request`, set a cancellable context on it, do the request and then begin reading the body, if you cancel the original context on the request, the read on the body will unblock. This is not documented anywhere afaik but is extremely useful behaviour.

**Comment by nhooyr** [comment]
Related https://github.com/golang/go/issues/26941

**Comment by meirf** [comment]
@nhooyr is this a dup of https://github.com/golang/go/issues/26101?

**Comment by nhooyr** [comment]
@meirf Yup, this is a dup of #26101

I will try and get in a CL for it.
