### ISSUE TITLE
net/http: Allow configuring write timeout of header/body on transport

### ISSUE THREAD

**Issue by nhooyr** [golang/go#26942]
Not sure how important this is but given `*http.Server` has fields for this, maybe `*httputil.ReverseProxy` should as well.

**Comment by meirf** [comment]
Have you considered setting whatever you want on http.Server and then using the reverse proxy as the Server's Handler? Do you see any concerns with that?

**Comment by nhooyr** [comment]
Just realized I can just cancel the request context to make this work. All is good.
