### ISSUE TITLE
x/playground: visual formatting options

### ISSUE THREAD

**Issue by pitust** [golang/go#26940]
Please answer these questions before submitting your issue. Thanks!

I am using go playground and there is default indenting (tabsize 8)
Why there is no tabsize 4?

**Comment by myitcv** [comment]
Simply because there is not an option in the playground to visually display a tab as anything other than the equivalent of 8 spaces. I suspect it's best to keep the playground this way; keeps the interface simple etc. But cc @andybons just in case.

**Comment by andybons** [comment]
Thanks for the feedback. Currently we’re not looking to provide options for text display on the playground at this time.
