### ISSUE TITLE
http/net exception - in dll context

### ISSUE THREAD

**Issue by code34** [golang/go#26952]
### What version of Go are you using (`go version`)?
go 1.10 windows / amd64

### Does this issue reproduce with the latest release?
i don't know

### What operating system and processor architecture are you using (`go env`)?
windows
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\code34\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\code34\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\code34\AppData\Local\Temp\go-build638089086=/tmp/go-build -gno-record-gcc-switches

### What did you do?
I have a C program wich call a GO dll. The GO dll use net/http to retrieve a distant json. You can retrieve the C program and the go source file at this URL:
https://www.dropbox.com/s/21k6nm75zlxn68q/armaws_x64.zip?dl=0

You only have to call it in powershell, it will load automatically the dll file
.\callextension_x64.exe .\test_script.sqf

### What did you expect to see?
The content of my http request. The same code source works when it's a simple .exe file.

### What did you see instead?
An exception crash

Exception log file is at this place: 
[log.txt](https://github.com/golang/go/files/2282151/log.txt)

**Comment by davecheney** [comment]
@code34 please include the full text of the crash you received (please do *not* include a screenshot of the text)

**Comment by code34** [comment]
done i just at the log file at the end of post

**Comment by davecheney** [comment]
Thank you. I don't understand where this exception is being produced. Is it possible to get the Go stack trace?

**Comment by code34** [comment]
yes of course. how can i retrieve it ?

**Comment by davecheney** [comment]
I'm sorry I don't know. Hopefully someone else can help you.

**Comment by agnivade** [comment]
You can send the `kill -ABRT` signal to the process to get goroutine stack traces.

**Comment by davecheney** [comment]
Looking at your program you are calling

memmove(output, result, len(output))

so if the length of output is larger than the result, memmove will copy
more bytes than is in result and cause an exception.

**Comment by code34** [comment]
for the memmove it has been tested, you can for exemple return:
data = "hello"

without http/net code it works, with http there is an exception.

how can i send kill -ABRT on windows ? is it a simple kill throught task manager ?

**Comment by code34** [comment]
i test again and effectively you are right. there is something relative to the memmove but i dont understand what. Cause when i use a very large ouput it doesn't create exception.

**Comment by davecheney** [comment]
@code34 is this the test you mean?
```
//export RVExtension
func RVExtension(output *C.char, outputsize C.size_t, input *C.char) {
	data:= "hello"
	result := C.CString(data)
	defer C.free(unsafe.Pointer(result))
	C.memmove(unsafe.Pointer(output), unsafe.Pointer(result), outputsize - 1)
}
```
Do you see that `C.memmove` will attempt to copy `outputsize - 1` bytes from `result` to `output` irrespective of the size of `data`?

**Comment by code34** [comment]
thanks you davecheney i better understand now 👍 

i only manage the long variable size not the short.
