### ISSUE TITLE
undefined: registry.OpenKey when cross compiling on Linux for Windows

### ISSUE THREAD

**Issue by larytet** [golang/go#26954]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04.1 LTS

### What did you do?
Corss-compile code for Windows
```
package main
import (
	"log"
	"golang.org/x/sys/windows/registry"
)
func getSystemDNS() {
	roots := `SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces`
	registryKey, err := registry.OpenKey(registry.LOCAL_MACHINE, roots, registry.ENUMERATE_SUB_KEYS|registry.QUERY_VALUE)
	if err != nil {
		log.Printf("Failed to read %s: %v\n", roots, err)
	}
	log.Printf("Failed to read %s: %v\n", roots, registryKey)
	defer registryKey.Close()
}
```
Command 
```
GOOS=windows GOARCH=386 go install 
```

### What did you expect to see?
A clean compilation

### What did you see instead?
```
agent/dns.go:16:22: undefined: registry.OpenKey
agent/dns.go:16:39: undefined: registry.LOCAL_MACHINE
agent/dns.go:16:70: undefined: registry.ENUMERATE_SUB_KEYS
agent/dns.go:16:98: undefined: registry.QUERY_VALUE
```

**Comment by agnivade** [comment]
Your code and the error message are not in sync. I am assuming you have redacted some of the original code. 

The current code that you have pasted compiles fine (as long as I add an empty `main()` function). Can you post a full self-contained code which reproduces the error ?

**Comment by larytet** [comment]
My bad. A bug in my shell script.
