### ISSUE TITLE
cmd/go: cannot find module providing package golang.org/x/crypto/bcrypt

### ISSUE THREAD

**Issue by mosout** [golang/go#26958]
### What version of Go are you using (`go version`)?
go version go1.11beta3 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?

```
go get golang.org/x/crypto/bcrypt
```

### What did you expect to see?
Successful information.
### What did you see instead?
```
go get golang.org/x/crypto/bcrypt: cannot find module providing package golang.org/x/crypto/bcrypt
```

**Comment by myitcv** [comment]
Unfortunately, you've run into a variant of https://github.com/golang/go/issues/26722

This will be fixed in the next beta/first release candidate.

Or else it's already fixed in `tip`, if you're happy to [build Go from source](https://golang.org/doc/install/source)

**Comment by mosout** [comment]
@myitcv Thank you very much！
