### ISSUE TITLE
x/website/internal/dl: go-import meta tag isn't served for golang.org/dl/internal/{version,genv}

### ISSUE THREAD

**Issue by dmitshur** [golang/go#26965]
https://golang.org/dl/internal/version?go-get=1 is 404.

It should be serving something similar to https://golang.org/x/tools/go/vcs?go-get=1, etc.

```
$ export GOPATH=/tmp/empty
$ go get golang.org/dl/internal/version
package golang.org/dl/internal/version: unrecognized import path "golang.org/dl/internal/version" (parse https://golang.org/dl/internal/version?go-get=1: no go-import meta tags ())

$ goexec 'vcs.RepoRootForImportPath("golang.org/dl/internal/version", false)'
(*vcs.RepoRoot)(nil)
(*errors.errorString)(&errors.errorString{
	s: (string)("unrecognized import path \"golang.org/dl/internal/version\""),
})
```

This causes https://godoc.org/golang.org/dl/internal/version to show not found, etc.

This affects `golang.org/dl/internal/genv` package too.

**Comment by bradfitz** [comment]
True, but kinda low priority, no? This only affects people trying to `go get` those internal packages directly, rather than go-getting the actual `go1.N.M` commands?

**Comment by dmitshur** [comment]
Yes, this is a very minor issue. Anyone just doing `go get golang.org/dl/gox.y.z` isn't affected. I just filed it because I ran into it (couldn't read the package's source code/docs).

**Comment by seankhliao** [comment]
this still 404s but no longer seems relevant due to module mode? doc is available at https://pkg.go.dev/golang.org/dl/internal/version

**Comment by dmitshur** [comment]
Yeah, as far as I can tell, because of how package → module resolution works (documented at https://go.dev/ref/mod#resolve-pkg-mod), in module mode it appears to be sufficient as long as ?go-get=1 works on the module root. At least I'm not aware of any concrete ways that this issue is a problem in module mode.

I can close this issue for now, and consider reopening if we find a good reason to.
