### ISSUE TITLE
About os package bug

### ISSUE THREAD

**Issue by wujunjie6120** [golang/go#26978]
Hi~ developer.

//this program run in Ubuntu 18.04 with WIN10

func main() {
    go testFileExist()
    time.Sleep(100e9)
}
func testFileExist(){
    for  a :=0 ;a<10;  a++{
        time.Sleep(5e9)
        _, existErr := os.Stat("./desfile/test.docx")
        println("&existErr",&existErr)
        println("existErr",existErr==nil)
        if (existErr == nil || os.IsExist(existErr)) {
            println("true")
        }else{
            println("false")
        }
    }

result:
&existErr 0xc42003efc0
existErr false
false
&existErr 0xc42003efc0
existErr false
false

// build the test.docx

&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true

//delete the test.docx

&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true
&existErr 0xc42003efc0
existErr true
true

I run again this program .the print always is true.but the file was deleted.

Thankyou 
WJJ

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
