### ISSUE TITLE
fail to access structure size in cgo

### ISSUE THREAD

**Issue by pkking** [golang/go#26981]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version
go version go1.10.2 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```bash
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\l00440707\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\l00440707\go
set GORACE=
set GOROOT=C:\tools\go
set GOTMPDIR=
set GOTOOLDIR=C:\tools\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\L00440~1\AppData\Local\Temp\go-build789554618=/tmp/go-build -gno-record-gcc-switches
```
### What did you do?
```go
package main

/*
typedef signed char            s8;
typedef unsigned char          u8;

typedef signed   short         s16;
typedef unsigned short         u16;

typedef signed   int           s32;
typedef unsigned int           u32;

typedef signed long long       s64;
typedef unsigned long long     u64;

typedef struct tagMsgS
{
    u32 uiMagicWord;         
    u8  ucHeaderLen;
    u8  ucVersion;          
    u8  ucMsgType;          
    u8  ucMsgPath;        
    u16 usClientID;          
    u16 usSenderNodeID;      
    u32 uiSerialNumber;      
    u32 uiParameterNByte;   
    u16 usSenderBID;        
    u16 usSenderPID;       
    u16 usReceiverBID;      
    u16 usReceiverPID;      
    u32 uiMsgOPCode;        
    u8  ucMsgState;       
    u8  ucReserve2;       
    u16 usReceiverNodeID;  
    u32 uiSessionKey;      
    u32 uiMsgTimeout;        
    u64 aucMsgParameter[0]; 
}MSG_S;
*/

import (
	"C"
	"fmt"
)

func main(){
	fmt.Println(C.sizeof_struct_tagMsgS)
}
```
code as above
as i read the [doc](https://github.com/golang/go/commit/505fa7b42338f0aba7e4235acbc8274a20f3c1f0#diff-698246470c58a0a25a3ec2020dd48133)
its possible to access the c struct size as C.sizeof_struct_xxx, but it fails with
```bash 
go run src\omm-go\main.go
# command-line-arguments
src\omm-go\main.go:52:14: could not determine kind of name for C.sizeof_MSG_S
src\omm-go\main.go:51:14: could not determine kind of name for C.sizeof_struct_tagMsgS
```
### What did you expect to see?
wana to know the size of struct MSG_S

### What did you see instead?
a compile error

**Comment by davecheney** [comment]
Your issue occurs because there is a blank link between the end of your C source code comment block and `import "C"`

Do this
```
/* 
... 
*/
import "C"
```

Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by pkking** [comment]
@davecheney thx for the advise, but still got a error after editing my code:
```go
package main
/*
typedef struct {
  int name;
} foobar;
*/
import (
	"C"
	"fmt"
)

func main(){
	fmt.Println(_C_sizeof_foobar)
}
```
then i compile
```bash
go run src\omm-go\main.go
# command-line-arguments
src\omm-go\main.go:13:14: could not determine kind of name for C.sizeof_struct_foobar
```

**Comment by davecheney** [comment]
Please reread my comment and the link I provided.  The syntax of the `import "C"` is very specific.

**Comment by pkking** [comment]
@davecheney my bad, `import "C"` must be a single line fellow the c block, thank you!
