### ISSUE TITLE
cmd/go: 'mod init' writes info message to stderr

### ISSUE THREAD

**Issue by mwf** [golang/go#26984]
### What version of Go are you using (`go version`)?

`go version devel +81555cb4f3 Tue Aug 14 09:19:38 2018 +0000 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes, latest master.

### What did you do?

```
cd `mktemp -d`
go mod init example.com/foo > /dev/null
```

### What did you expect to see?

I expect to see no output.

### What did you see instead?

```
$ go mod init example.com/foo > /dev/null
go: creating new go.mod: module example.com/foo
```
`go mod init` writes this message to Stderr.

I would prefer if it wrote to stdout instead, so I could ignore the output in my script. 

And I definitely don't want to ignore the stderr - in case of any error occurs.

**Comment by mvdan** [comment]
Using standard error for non-error messages is fine. For example, the `log` package uses standard error by default.

If you want to ignore output as long as no error happened, simply keep the output somewhere, and only use it if the exit code is non-zero.

**Comment by mwf** [comment]
Thanks, that makes sense. 
I just thought it's not an intended behaviour. 

Closing.
