### ISSUE TITLE
cmd/go: modules can't install a binary unless there is a go.mod in the current directory

### ISSUE THREAD

**Issue by markbates** [golang/go#26992]
When trying to install a binary using `go get` the installation fails when `GO111MODULE=on` and the directory you are in does not contain a `go.mod` file.

This only fails when `GO111MODULE=on`, otherwise the `go get` is successful and binary is installed.

### What version of Go are you using (`go version`)?
`go version go1.11rc1 darwin/amd64`
`GO111MODULE=on`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/markbates/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/markbates/Dropbox/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/vw2ck7mj32z5f63wpgfw5qk80000gn/T/go-build733373769=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

```bash
export GO111MODULE=on
go1.11.rc1 get -v github.com/gobuffalo/buffalo/buffalo
$GOPATH/bin/buffalo version
```

### What did you expect to see?

`v0.12.5`

### What did you see instead?

```
go: cannot find main module; see 'go help modules'
```

**Comment by myitcv** [comment]
This is, I think, a variant of https://github.com/golang/go/issues/24250

**Comment by andybons** [comment]
@rsc @bcmills @ianlancetaylor

**Comment by bcmills** [comment]
Yes, this is a dup of #24250.
