### ISSUE TITLE
runtime: TestMmapErrorSign failure on Mac OS Mojave 10.14 Beta (18A365a)

### ISSUE THREAD

**Issue by ajstarks** [golang/go#27004]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go 1.11rc1 darwin/amd64

### Does this issue reproduce with the latest release?

no

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nm55336/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nm55336/gowork"
GOPROXY=""
GORACE=""
GOROOT="/Users/nm55336/go"
GOTMPDIR=""
GOTOOLDIR="/Users/nm55336/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yl/jnvy7ycx5gjfjt5_5j4n_5gw0000gn/T/go-build968717385=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

$ GOROOT_BOOTSTRAP=$HOME/go1.9.2 ./all.bash
Building Go cmd/dist using /Users/nm55336/go1.9.2.
Building Go toolchain1 using /Users/nm55336/go1.9.2.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.

##### Testing packages.
ok  	archive/tar	0.068s
ok  	archive/zip	3.052s
ok  	bufio	0.067s
ok  	bytes	0.427s
ok  	compress/bzip2	0.087s
ok  	compress/flate	1.096s
ok  	compress/gzip	0.032s
ok  	compress/lzw	0.022s
ok  	compress/zlib	0.031s
ok  	container/heap	0.020s
ok  	container/list	0.012s
ok  	container/ring	0.026s
ok  	context	1.032s
ok  	crypto	0.016s
ok  	crypto/aes	0.040s
ok  	crypto/cipher	0.029s
ok  	crypto/des	0.018s
ok  	crypto/dsa	0.015s
ok  	crypto/ecdsa	0.237s
ok  	crypto/elliptic	0.565s
ok  	crypto/hmac	0.012s
ok  	crypto/internal/subtle	0.011s
ok  	crypto/md5	0.012s
ok  	crypto/rand	0.052s
ok  	crypto/rc4	0.128s
ok  	crypto/rsa	0.089s
ok  	crypto/sha1	0.025s
ok  	crypto/sha256	0.010s
ok  	crypto/sha512	0.018s
ok  	crypto/subtle	0.012s
ok  	crypto/tls	0.719s
ok  	crypto/x509	2.503s
ok  	database/sql	0.582s
ok  	database/sql/driver	0.010s
ok  	debug/dwarf	0.040s
ok  	debug/elf	0.055s
ok  	debug/gosym	0.360s
ok  	debug/macho	0.016s
ok  	debug/pe	0.030s
ok  	debug/plan9obj	0.014s
ok  	encoding/ascii85	0.018s
ok  	encoding/asn1	0.020s
ok  	encoding/base32	0.028s
ok  	encoding/base64	0.014s
ok  	encoding/binary	0.018s
ok  	encoding/csv	0.015s
ok  	encoding/gob	0.049s
ok  	encoding/hex	0.015s
ok  	encoding/json	0.553s
ok  	encoding/pem	0.045s
ok  	encoding/xml	0.033s
ok  	errors	0.011s
ok  	expvar	0.031s
ok  	flag	0.012s
ok  	fmt	0.257s
ok  	go/ast	0.014s
ok  	go/build	0.556s
ok  	go/constant	0.013s
ok  	go/doc	0.160s
ok  	go/format	0.017s
ok  	go/importer	0.209s
ok  	go/internal/gccgoimporter	0.026s
ok  	go/internal/gcimporter	0.653s
ok  	go/internal/srcimporter	2.122s
ok  	go/parser	0.039s
ok  	go/printer	0.469s
ok  	go/scanner	0.011s
ok  	go/token	0.037s
ok  	go/types	1.318s
ok  	hash	0.012s
ok  	hash/adler32	0.017s
ok  	hash/crc32	0.019s
ok  	hash/crc64	0.022s
ok  	hash/fnv	0.010s
ok  	html	0.012s
ok  	html/template	0.063s
ok  	image	0.166s
ok  	image/color	0.035s
ok  	image/draw	0.089s
ok  	image/gif	0.442s
ok  	image/jpeg	0.448s
ok  	image/png	0.055s
ok  	index/suffixarray	0.017s
ok  	internal/cpu	0.012s
ok  	internal/poll	0.039s
ok  	internal/singleflight	0.022s
ok  	internal/trace	2.565s
ok  	io	0.041s
ok  	io/ioutil	0.021s
ok  	log	0.014s
ok  	log/syslog	1.249s
ok  	math	0.014s
ok  	math/big	2.735s
ok  	math/bits	0.013s
ok  	math/cmplx	0.022s
ok  	math/rand	0.401s
ok  	mime	0.017s
ok  	mime/multipart	0.679s
ok  	mime/quotedprintable	0.125s
ok  	net	3.303s
ok  	net/http	4.100s
ok  	net/http/cgi	0.967s
ok  	net/http/cookiejar	0.040s
ok  	net/http/fcgi	0.037s
ok  	net/http/httptest	0.056s
ok  	net/http/httptrace	0.034s
ok  	net/http/httputil	0.113s
ok  	net/http/internal	0.008s
ok  	net/http/pprof	2.057s
ok  	net/internal/socktest	0.019s
ok  	net/mail	0.011s
ok  	net/rpc	0.055s
ok  	net/rpc/jsonrpc	0.025s
ok  	net/smtp	0.051s
ok  	net/textproto	0.017s
ok  	net/url	0.025s
ok  	os	0.882s
ok  	os/exec	2.100s
ok  	os/signal	6.703s
ok  	os/user	0.015s
ok  	path	0.010s
ok  	path/filepath	0.101s
ok  	reflect	0.203s
ok  	regexp	0.143s
ok  	regexp/syntax	0.760s
--- FAIL: TestMmapErrorSign (0.00s)
    runtime_mmap_test.go:22: mmap = <nil>, 566292468769751052, want nil, 12
FAIL
FAIL	runtime	29.362s
ok  	runtime/debug	0.066s
ok  	runtime/internal/atomic	0.215s
ok  	runtime/internal/sys	0.012s
ok  	runtime/pprof	9.824s
ok  	runtime/pprof/internal/profile	0.011s
ok  	runtime/trace	2.049s
ok  	sort	0.095s
ok  	strconv	1.560s
ok  	strings	0.593s
ok  	sync	0.409s
ok  	sync/atomic	0.046s
ok  	syscall	0.083s
ok  	testing	0.968s
ok  	testing/quick	0.168s
ok  	text/scanner	0.010s
ok  	text/tabwriter	0.015s
ok  	text/template	0.661s
ok  	text/template/parse	0.018s
ok  	time	2.673s
ok  	unicode	0.013s
ok  	unicode/utf16	0.010s
ok  	unicode/utf8	0.014s
ok  	vendor/golang_org/x/crypto/chacha20poly1305	0.097s
ok  	vendor/golang_org/x/crypto/cryptobyte	0.011s
ok  	vendor/golang_org/x/crypto/curve25519	0.026s
ok  	vendor/golang_org/x/crypto/internal/chacha20	0.066s
ok  	vendor/golang_org/x/crypto/poly1305	0.016s
ok  	vendor/golang_org/x/net/dns/dnsmessage	0.077s
ok  	vendor/golang_org/x/net/http/httpguts	0.016s
ok  	vendor/golang_org/x/net/http/httpproxy	0.017s
ok  	vendor/golang_org/x/net/http2/hpack	0.015s
ok  	vendor/golang_org/x/net/idna	0.014s
ok  	vendor/golang_org/x/net/nettest	0.822s
ok  	vendor/golang_org/x/net/route	0.022s
ok  	vendor/golang_org/x/text/transform	0.012s
ok  	vendor/golang_org/x/text/unicode/norm	0.010s
ok  	cmd/addr2line	2.941s
ok  	cmd/api	0.021s
ok  	cmd/asm/internal/asm	1.025s
ok  	cmd/asm/internal/lex	0.014s
ok  	cmd/compile	0.014s
ok  	cmd/compile/internal/gc	16.583s
ok  	cmd/compile/internal/ssa	0.597s
ok  	cmd/compile/internal/syntax	0.023s
ok  	cmd/compile/internal/test	0.012s [no tests to run]
ok  	cmd/compile/internal/types	0.011s
ok  	cmd/cover	5.043s
ok  	cmd/doc	0.062s
ok  	cmd/fix	8.624s
ok  	cmd/go	122.522s
ok  	cmd/go/internal/cache	4.459s
ok  	cmd/go/internal/dirhash	0.019s
ok  	cmd/go/internal/generate	0.051s
ok  	cmd/go/internal/get	0.053s
ok  	cmd/go/internal/imports	0.025s
ok  	cmd/go/internal/load	0.019s
ok  	cmd/go/internal/modconv	0.058s
ok  	cmd/go/internal/modfetch	0.046s
ok  	cmd/go/internal/modfetch/codehost	0.010s
ok  	cmd/go/internal/modfile	0.026s
ok  	cmd/go/internal/modload	0.046s
ok  	cmd/go/internal/module	0.010s
ok  	cmd/go/internal/mvs	0.015s
ok  	cmd/go/internal/par	0.039s
ok  	cmd/go/internal/search	0.013s
ok  	cmd/go/internal/semver	0.010s
ok  	cmd/go/internal/txtar	0.011s
ok  	cmd/go/internal/web2	0.031s
ok  	cmd/go/internal/work	0.030s
ok  	cmd/gofmt	0.126s
ok  	cmd/internal/buildid	0.273s
ok  	cmd/internal/dwarf	0.011s
ok  	cmd/internal/edit	0.051s
ok  	cmd/internal/goobj	1.223s
ok  	cmd/internal/obj	0.013s
ok  	cmd/internal/obj/arm64	0.065s
ok  	cmd/internal/obj/x86	0.625s
ok  	cmd/internal/objabi	0.010s
ok  	cmd/internal/src	0.011s
ok  	cmd/internal/test2json	0.153s
ok  	cmd/link	3.295s
ok  	cmd/link/internal/ld	13.525s
ok  	cmd/link/internal/sym	0.011s
ok  	cmd/nm	7.248s
ok  	cmd/objdump	4.684s
ok  	cmd/pack	3.599s
ok  	cmd/trace	0.062s
ok  	cmd/vendor/github.com/google/pprof/internal/binutils	0.037s
ok  	cmd/vendor/github.com/google/pprof/internal/driver	0.451s
ok  	cmd/vendor/github.com/google/pprof/internal/elfexec	0.010s
ok  	cmd/vendor/github.com/google/pprof/internal/graph	0.016s
ok  	cmd/vendor/github.com/google/pprof/internal/measurement	0.012s
ok  	cmd/vendor/github.com/google/pprof/internal/report	0.049s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolizer	0.033s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolz	0.029s
ok  	cmd/vendor/github.com/google/pprof/profile	0.104s
ok  	cmd/vendor/github.com/ianlancetaylor/demangle	0.028s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.023s
ok  	cmd/vendor/golang.org/x/arch/arm64/arm64asm	0.366s
ok  	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.016s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	0.132s
ok  	cmd/vendor/golang.org/x/crypto/ssh/terminal	0.015s
ok  	cmd/vendor/golang.org/x/sys/unix	0.395s
ok  	cmd/vet	4.312s
ok  	cmd/vet/internal/cfg	0.010s
2018/08/15 11:37:25 Failed: exit status 1

If possible, provide a recipe for reproducing the error.

run all.bash

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

All Test Passed

### What did you see instead?

2018/08/15 11:37:25 Failed: exit status 1

**Comment by mvdan** [comment]
I've re-titled this issue, since it seems to only concern a test in the `runtime` package.

Note that to build Go, you can simply use `make.bash` instead of `all.bash` - there's no strict need to run the tests to build Go.

**Comment by randall77** [comment]
Could you try 1.11 or tip?  This should have been fixed by moving to libc calls instead of raw system calls.

**Comment by randall77** [comment]
Sorry, you did do that. 1.9 was just the bootstrap compiler.

**Comment by ajstarks** [comment]
fix confirmed.  thanks for the quick response.
