### ISSUE TITLE
cmd/go: documentation typo in go help mod download

### ISSUE THREAD

**Issue by jasonkeene** [golang/go#27030]
### What version of Go are you using (`go version`)?
```
go version go1.11rc1 linux/amd64
```

### Does this issue reproduce with the latest release?
This is in RC release, running the official RC docker image.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/my-module/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build177831737=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
Run `go help mod download`

### What did you expect to see?
No expectations.

### What did you see instead?
At the bottom of the document that is printed out There is the statement:

```
See 'go help module' for more about module queries.
```

`go help module` does not work, I think it was meant to be `go help modules`

**Comment by bradfitz** [comment]
@gopherbot, please backport to 1.11.
