### ISSUE TITLE
proposal: reusable logic templates 

### ISSUE THREAD

**Issue by AndreiPiakhota** [golang/go#27035]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes, it does

### What operating system and processor architecture are you using (`go env`)?
Windows 10

GoLang is nothing like simple language. It seems simple because it is ingenious. Owing to lightweight goroutines and channels to share memory by communicating the language unfolds absolutely unique style of programming by orchestrating multiple goroutines. This uniqueness along with easiness of passing around functions and methods stages the playground for further enhancements in this vein. 

What would advance the language further on in this way is a possibility to create code templates to reuse them in different context 

For example we have this snippet of code:

```
func splitCandy(pcs int) map[string]int {

  type party struct {
     name string
     age  int
     schoolQ float32
  }

  mems := []party{
     {"Dany", 5, 0.0},
     {"Chloe", 12, 9.2},
     {"David", 14, 6.8},
     {"Ryan", 9, 4.2},
     {"Leah", 11, 8.5},
  }

  {{define "eqSplit"}}
  n := len(mems)

  var extra int
  var res = make(map[string]int, n)

  if n > pcs {
     extra = pcs
     pcs = 0
     goto splitLogic
  }

  for i := 0; i < n; i++ {
     if pcs %n == 0 {
        cnds := pcs / n
        for _, kid := range mems {
           res[kid.name] = cnds
        }
        break
     } else {
        pcs--
        extra++
     }
  }

  splitLogic:
  {{end}}

  for k, v := range res {
     if v > 5 {
        for _, m := range mems {
           if k == m.name {
              res[k]--
              extra++
           }
        }
     }
  }

  // very complicated logic here

  return res

}

func allotChoresHrs() {

  type party struct {
     name string
     age  int
  }

  mems := []party{
     {"Chloe", 12},
     {"David", 14},
     {"Ryan", 9},
     {"Leah", 11},
  }

  {{block "eqSplit" }}

  for k, v := range res {
     if v > 5 {
        for _, m := range mems {
           if k == m.name {
              res[k]--
              extra++
           }
        }
     }
  }
}
```
‘splitCandy’ function contains complicated logic tightly engrossed in function context which makes it difficult and ineffective to be split into several functions. Instead we might have an ability to reuse certain pieces of logic within different context. Notice some block of code surrounded with this block: 

```
{{define "eqSplit"}} 
     ...
{{end}} 
```

We then reuse this snippet of code in the second function (allotChoresHrs) by placing this reference: 
`
{{block "eqSplit" }}
`
What we have defined above the reference gets used as a context for the code snippet being referenced. Also injected block of code brings a set of new variables got accessible afterwards. 

Of cause there are issues with code readability and maintenance upon code changing but in my view it goes along pretty naturally with a new style of programming brought up by Go. And it is unique feature with no precedent in my mind. There are http and text templates where such logic templates might come in handy.

**Comment by andybons** [comment]
Thank you for the feature request.

Unless I'm misunderstanding your proposal, it sounds like what you're describing could be achieved by simply using functions. The benefits of this feature don't appear to outweigh the increased complexity it would bring to the language specification.

Thank you again for taking the time to write up this request, but we're going to pass.
