### ISSUE TITLE
cmd/gofmt: feature request: order methods

### ISSUE THREAD

**Issue by ivanivanyuk1993** [golang/go#27041]
When I run formatter, I expect all exported variables and methods to be in the beginning of file, ordered by name, followed by all not exported variables.

When I run formatter, methods and variables do not change their order, hence I have to order them manually

**Comment by bradfitz** [comment]
Sorry, this is an area where gofmt doesn't want to have opinions.

Fortunately Go makes it easy to write your own tools to do this using the go/* packages. For example, goimports and goreturns are other tools that rewrite code (like gofmt), but make difference choices.

I suggest you write a tool to do the thing you want and you can advertise it here.

**Comment by ivanivanyuk1993** [comment]
Ok, thank you
