### ISSUE TITLE
x/build/cmd/gopherbot: "please backport" doesn't know about future Go releases

### ISSUE THREAD

**Issue by dmitshur** [golang/go#27040]
In https://github.com/golang/go/issues/27030#issuecomment-413581102, @bradfitz said:

> @gopherbot, please back​port to 1.11.

@gopherbot instead back​ported for 1.10 and 1.9:

![image](https://user-images.githubusercontent.com/1924134/44232742-f2b21900-a16f-11e8-8283-c6e514735e13.png)

The reason it did so is because it doesn't know about 1.11 yet, it's a future release. `b.getMajorReleases(ctx)` returns 1.9 and 1.10 only. Since 1.11 wasn't recognized, the default behavior is to back​port to supported major releases (current and previous).

How do we want to fix this? Just add support for back​porting to the next major release (current+1)? Or something else?

/cc @bradfitz @andybons @FiloSottile

(I'm using a zero width space to prevent @gopherbot from back​porting this issue.)

**Comment by andybons** [comment]
> How do we want to fix this? Just add support for back​porting to the next major release (current+1)? Or something else?

I think this is a reasonable thing to do. If we encounter issues we can revisit.
