### ISSUE TITLE
x/build/cmd/gopherbot: label removed as requested but then immediately re-added

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#27058]
In https://github.com/golang/go/issues/27057, gopherbot automatically added the documentation label, presumably because I had "documentation" in the issue title. Then I asked gopherbot to remove the label, and it did remove the label, but it immediately re-added the label, as indicated in the issue history:

>  gopherbot added Documentation  and removed Documentation  labels

I'm guessing it re-added the label because of the issue title. I expected the "gopherbot please" message to take precedence over the issue title.

**Comment by ALTree** [comment]
General gopherbot stubbornness is tracked at  #21312. There are a few examples there, you could probably add yours and close here.

In general, he should be taught not to re-add a label that was previously deleted.
