### ISSUE TITLE
Unnessesary heap allocation when passing pointer to function variable.

### ISSUE THREAD

**Issue by eliothedeman** [golang/go#27067]
### What version of Go are you using (`go version`)?
go version devel +714c141c4f Sat Aug 18 03:02:40 2018 +0000 darwin/amd64
go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/eliot/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/eliot/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/eliot/go/src/github.com/golang/go"
GOTMPDIR=""
GOTOOLDIR="/Users/eliot/go/src/github.com/golang/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z2/y6lqx59x7lvgb0_mc0y3sl_r0000gn/T/go-build965150652=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
```go
package repro

import "testing"

type val struct {
	x, y int
}

func add(v *val) int {
	return v.x + v.y
}
func addNoRef(v val) int {
	return v.x + v.y
}

func noAlloc() int {
	var v val
	return add(&v)
}

func hasAlloc(f func(v *val) int) int {
	var v val
	return f(&v)
}
func noRef(f func(v val) int) {
	var v val
	f(v)
}

func BenchmarkRepro(b *testing.B) {
	b.Run("has-alloc", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			hasAlloc(add)
		}
	})
	b.Run("no-alloc", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			noAlloc()
		}
	})
	b.Run("no-ref", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			noRef(addNoRef)
		}
	})
}

```

### What did you expect to see?
None of these benchmarks should cause heap allocations. Passing a pointer down the stack should not cause a heap allocation.

### What did you see instead?
```
Running tool: /Users/eliot/go/src/github.com/golang/go/bin/go test -benchmem -run=^$ -bench ^BenchmarkRepro$

goos: darwin
goarch: amd64
BenchmarkRepro/has-alloc-12         	100000000	        21.0 ns/op	      16 B/op	       1 allocs/op
BenchmarkRepro/no-alloc-12          	2000000000	         0.50 ns/op	       0 B/op	       0 allocs/op
BenchmarkRepro/no-ref-12            	1000000000	         2.79 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	_/Users/eliot/Documents	6.230s
```

**Comment by rsc** [comment]
This function must allocate:

```
func hasAlloc(f func(v *val) int) int {
	var v val
	return f(&v)
}
```

What if you called it like:

```
var global []*val
save := func(v *val) int {
   global = append(global, v)
   return len(global)
}
hasAlloc(1)
hasAlloc(2)
hasAlloc(3)
```

In this case hasAlloc is not passing v "down the stack". It's escaping.
