### ISSUE TITLE
mime: TypeByExtension should not output charset=utf8

### ISSUE THREAD

**Issue by frostyplanet** [golang/go#27078]
### What version of Go are you using (`go version`)?

go1.10 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

linux ubuntu 16.04;  regardless LC_ALL env setting

complied code run on windows 2012 also has this issue;

### What did you do?

```
package main

import "mime"
func main() {
    println(mime.TypeByExtension(".html"))
}
```

### What did you expect to see?

expect "text/html",  

### What did you see instead?

"text/html; charset=utf-8"

the html content may not be utf8 after all.
using the result from mime.TypeByExtension() and return in Content-Type header of one http response will make browser believe the chraset is utf8

**Comment by andriisoldatenko** [comment]
For quick look in source code https://golang.org/src/mime/type.go?s=2698:2737#L63
```
var builtinTypesLower = map[string]string{
	".css":  "text/css; charset=utf-8",
	".gif":  "image/gif",
	".htm":  "text/html; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".jpg":  "image/jpeg",
	".js":   "application/javascript",
	".wasm": "application/wasm",
	".pdf":  "application/pdf",
	".png":  "image/png",
	".svg":  "image/svg+xml",
	".xml":  "text/xml; charset=utf-8",
}
```
and working example https://play.golang.org/p/SD93m9K93WD.
@josharian  Please let me know if we need to fix it.

**Comment by frostyplanet** [comment]
Although the doc specify function behavior, but it's no big deal for html and xml if not to include "; charset=utf-8", 
usually the content itself contain a charset declaration. Should at lease let user to opt out the behavior.

**Comment by andybons** [comment]
@bradfitz

**Comment by bradfitz** [comment]
This was an explicit decision when these APIs were made.

If you need a different charset (increasingly rare?), you can set it explicitly and not use the package.
