### ISSUE TITLE
x/*: Maintain version tags for all packages

### ISSUE THREAD

**Issue by networkimprov** [golang/go#27087]
When preparing to vendor x/net/ipv4 I could not find a version string for the package or x/net.

Could the maintainers start committing semver tags for each package (or at least submodule) in golang.org/x/* ?

This might benefit the imminent rush of _go mod_ users :-)

Apologies if there is already an issue for this; I did look.

@gopherbot add modules

**Comment by ALTree** [comment]
Thanks for the request.

This is a dup of #21324, so I'm closing this thread in favour of the older one.

**Comment by networkimprov** [comment]
Apologies for the noise. I posted this twice in golang-nuts last week, but no one responded.

**Comment by ALTree** [comment]
> I posted this twice in golang-nuts last week

In general, for things that directly concern the Go devs and/or repositories owners, golang-dev is the right place (that, or the issue tracker).
