### ISSUE TITLE
cmd/go: internal/modload TestImport stuck in infinite loop(?)

### ISSUE THREAD

**Issue by ALTree** [golang/go#27080]
```
$ gotip version
go version devel +bf80e3b564 Sat Aug 18 18:23:06 2018 +0000 linux/amd64
```

```
$ cd src/cmd/go/internal/modload

$ gotip test -run=TestImport -v
=== RUN   TestImport
=== RUN   TestImport/golang.org_x_net_context

```

and then it's stuck there, spinning at 100% cpu. I've let it run for about an hour on my machine, and it didn't finish. On the longtest builder it times out, and there's a stacktrace:  

https://build.golang.org/log/8b2c6c726faf3a87bc5862a0e3192d66df682810

**Comment by mvdan** [comment]
Every time we fix a long test, there's another one popping up :) Hopefully we'll have linux-amd64-longtest green soon.

**Comment by ALTree** [comment]
> Every time we fix a long test, there's another one popping up

That's how you know the longtest builder is doing its job :^)

**Comment by mvdan** [comment]
Now we just need brave heroes to do the same work with darwin and windows longtest builders.
