### ISSUE TITLE
why json.Unmarshal method convert number value (in json string) to float value (in golang)?

### ISSUE THREAD

**Issue by mthhk** [golang/go#27082]
BIAGT

**Comment by mvdan** [comment]
Please read the documentation carefully: https://golang.org/pkg/encoding/json/#Unmarshal

> To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:
> [...]
> float64, for JSON numbers

**Comment by dominikh** [comment]
Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
