### ISSUE TITLE
cmd/go: go.mod errors missing newlines on malformed replace blocks

### ISSUE THREAD

**Issue by shoenig** [golang/go#27081]
Having generated a malformed `go.mod` file**, an incorrect `replace` block produces error messages which appear to be missing newlines.

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.11rc1 linux/amd64
```

### What did you expect to see?
Better formatted error messages, similar to what my malformed `require` block produced.

### What did you see instead?
```
[k9 libconfig (master)] $ go build
go: errors parsing go.mod:
/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:4: usage: require module/path v1.2.3
/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:5: usage: require module/path v1.2.3
/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:6: usage: require module/path v1.2.3
/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:10: replacement module without version must be directory path (rooted or starting with ./ or ../)/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:11: replacement module without version must be directory path (rooted or starting with ./ or ../)/home/hoenig/Documents/go/src/indeed/gophers/libconfig/go.mod:12: replacement module without version must be directory path (rooted or starting with ./ or ../)
```
Seems like that last line should be 3 lines.

The bad `go.mod` file:
```
$ cat go.mod 
module code.corp.indeed.com/gophers/libconfig

require (
    code.corp.indeed.com/gophers/3rdparty
    code.corp.indeed.com/gophers/libtest
    code.corp.indeed.com/gophers/rlog
)

replace (
    code.corp.indeed.com/gophers/3rdparty => gophers/3rdparty
    code.corp.indeed.com/gophers/libtest => gophers/libtest
    code.corp.indeed.com/gophers/rlog => gophers/rlog
)
```

** I'm working out how to adapt our internal tooling to work with modules while migrating from our gross monstrosity of a dependency manager; never mind the malformed-ness.

**Comment by mvdan** [comment]
Thanks for reporting! It does seem like a few newlines were missed in `fmt.Fprintf` lines.

**Comment by zouyee** [comment]
<img width="709" alt="屏幕快照 2019-04-19 上午9 35 03" src="https://user-images.githubusercontent.com/5785605/56400432-759eec80-6286-11e9-8d83-0ebda176d83c.png">

**Comment by akshaybabloo** [comment]
I get this error in 1.12.* as well
