### ISSUE TITLE
x/tools/cmd/stringer: compile error "undefined: defaultImporter" on go1.10

### ISSUE THREAD

**Issue by temoto** [golang/go#27094]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.10.3 darwin/amd64`

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/temoto/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/temoto"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5s/j0nv22m55090n3x2h_pc17s80000gn/T/go-build087445163=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

`go get -u golang.org/x/tools/cmd/stringer && echo ok`

### What did you expect to see?
`ok`

### What did you see instead?
```
# golang.org/x/tools/cmd/stringer
../../../../src/golang.org/x/tools/cmd/stringer/stringer.go:286:21: undefined: defaultImporter
```

**Comment by mvdan** [comment]
Are you positive that you're on Go 1.10 and you're building a clean checkout of `stringer`? It builds fine for me on both 1.10.3 and tip, with `x/tools` at commit `7d1dc997617fb662918b6ea95efc19faa87e1cf8`.

**Comment by temoto** [comment]
Thank you. Fixed with `rm -rf $GOPATH/src/golang.org`
