### ISSUE TITLE
x/vgo weird issue with compiling github.com/satori/go.uuid

### ISSUE THREAD

**Issue by mgyong** [golang/go#27091]
### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

When compiling using vgo  the below program using "github.com/satori/go.uuid"
```
 CGO_ENABLED=0 vgo build -o main .
./main.go:11:18: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)
```
It should compile without issue
When i do go run main.go it compiles without issues

The full program below i am compiling
```
package main

import (
	"fmt"

	uuid "github.com/satori/go.uuid"
)

func UUID() string {
	//out := uuid.Must(uuid.NewV4())
	out := uuid.Must(uuid.NewV4())
	return out.String()
}
func main() {

	fmt.Println(UUID())

}

```

**Comment by agnivade** [comment]
vgo does not grab head. It grabs the latest tagged release. You have to ask vgo to get master.

Please use the forums for further questions.

**Comment by mgyong** [comment]
How do i get vgo to get master ?

**Comment by agnivade** [comment]
> Please use the forums for further questions.

**Comment by ALTree** [comment]
@agnivade It's better to link the [Questions wiki page](https://github.com/golang/go/wiki/Questions) when closing a question, otherwise OP may end up posting in the wrong place (e.g. golang-dev).

**Comment by agnivade** [comment]
Yeah, I always do that. This got missed out. :man_facepalming:
