### ISSUE TITLE
cmd/go:  go list -json -compiled -test -e upspin.io/test fails with non-zero exit status

### ISSUE THREAD

**Issue by dominikh** [golang/go#27097]
### What version of Go are you using (`go version`)?
go version devel +88aa208 Mon Aug 20 08:01:43 2018 +0000 linux/amd64

### What did you do?

```
conf := &packages.Config{
	Tests: true,
}
pkgs, err := packages.Load(conf, "upspin.io/test")
fmt.Println(pkgs, err)
```

### What did you expect to see?
No error; the test package(s) to be returned

### What did you see instead?
[] go list: exit status 1: go build upspin.io/test: no non-test Go files in /home/dominikh/prj/src/upspin.io/test

/cc @alandonovan @ianthehat @rsc

**Comment by dominikh** [comment]
Furthermore, this happens even for "upspin.io/...". 

When running `go list -json -compiled -test upspin.io/test`, this is the abridged output:

```
go build upspin.io/test: no non-test Go files in /home/dominikh/prj/src/upspin.io/test
{
        "Dir": "/home/dominikh/prj/src/upspin.io/test",
        "ImportPath": "upspin.io/test",
        "Name": "test",
        "Target": "/home/dominikh/prj/pkg/linux_amd64/upspin.io/test.a",
        "Root": "/home/dominikh/prj/",
        "Match": [
                "upspin.io/test"
        ],
        "Stale": true,
        "StaleReason": "build ID mismatch",
        "TestGoFiles": [
                "access_test.go",
                "all_test.go",
                "copy_test.go",
                "error_test.go",
                "group_test.go",
                "integration_test.go",
                "snapshot_test.go",
                "watch_test.go"
        ],
```
and the exit status is 1.

**Comment by matloob** [comment]
Even worse, `go list -json -compiled -test -e upspin.io/test` (with `-e`) fails. This should be fixed

**Comment by andybons** [comment]
@bcmills @ianlancetaylor @bradfitz

**Comment by alandonovan** [comment]
The result is independent of the -json flag; it's the -compiled flag that causes go list to attempt a build, and a build of a tests-only package fails ("no non-test Go files"). For golang.org/x/tools/go/packages, the desired outcome is that go list succeeds, reporting an empty Package.Target field and no errors.

(Ignoring the needs of go/packages, there would be a certain consistency if `go list` and `go list -test` were to pass and fail, respectively, on a tests-only package, but currently even `go list -test` fails where `go test` succeeds.)

Related: https://github.com/golang/go/issues/27101

**Comment by andybons** [comment]
@gopherbot please open a backport for 1.11
