### ISSUE TITLE
cmd/vet: enable windows/arm before Go 1.14 release

### ISSUE THREAD

**Issue by bradfitz** [golang/go#27103]
Reminder bug to re-enable windows/arm in cmd/vet/all before releasing Go 1.12.

(windows/arm is #26148)

/cc @jordanrh1

**Comment by bradfitz** [comment]
@jordanrh1, what's the status of the windows/arm port and this bug?

**Comment by ALTree** [comment]
This issue was opened as a reminder to remove some temporary code from` cmd/vet/all/main.go`, but that file no longer exists (vet is not run as part of `go test`); moreover the `windows/arm` port is currently inactive, so I think it's safe to close this issue.
