### ISSUE TITLE
x/tools/go/pointer: extended query tuple indexing does not take flattening into account

### ISSUE THREAD

**Issue by dominikh** [golang/go#27111]
For 

```
package main

type T struct {
	X *int
}

func id(x *int) (T, *int) { return T{new(int)}, x }

func main() {
	a := new(int)
	id(a)
}
```

with 

```
t1 = id(t0)                                                   (T, *int)
```

the extended query `x[1]` will refer to `T.X`, not the second return value. The extended query parsing assumes that tuple offsets match node offsets 1 to 1, not taking into consideration that structs will be flattened, effectively yielding the tuple `(T, *int, *int)`

I intend on fixing this myself, eventually, unless someone beats me to it.

**Comment by adonovan** [comment]
x/tools/go/pointer was deleted; see #59676.
