### ISSUE TITLE
runtime/pprof: go test report empty cpuprofile file on wsl

### ISSUE THREAD

**Issue by lsytj0413** [golang/go#27115]
### What version of Go are you using (`go version`)?
in wsl:

```
go version go1.10.1 linux/amd64
```

### Does this issue reproduce with the latest release?

unverified.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/soren/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/soren/workspace/golang/lib:/home/soren/workspace/golang"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144534119=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

i was learn [Go profile](https://github.com/bradfitz/talk-yapc-asia-2015/blob/master/talk.md), and follow this chapter's step. but the cpuprofile produce a empty output file and has nothing when use **go tool pprof prof** command.

with the same code and command i test on windows, it works fine.

**Comment by thunayyanabdullah** [comment]
Except

**Comment by lsytj0413** [comment]
@thunayyanabdullah sorry, i cann't understand what do you mean

**Comment by mikioh** [comment]
Dup of #22366, and looks like #22366 needs an expert on WSL and Windows internals and Linux.
