### ISSUE TITLE
cmd/go: build fails when setting linker to lld using ldflags

### ISSUE THREAD

**Issue by pcc** [golang/go#27110]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +0b30cf534a Mon Aug 20 23:12:45 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?
```
$ cat foo.c
void foo() {}
$ cat foo.h
void foo();
$ cat foo.go
package main

/*
#include "foo.h"
*/
import "C"

func main() {
	C.foo()
}
$ CC=clang CGO_LDFLAGS=-fuse-ld=lld go build 
```

### What did you expect to see?
Build succeeds

### What did you see instead?
```
# cgotest
[...]/link: running clang failed: exit status 1
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
ld.lld: error: unknown --compress-debug-sections value: zlib-gnu
ld.lld: error: --compress-debug-sections: zlib is not available
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The link command tries to detect whether the `-Wl,--compress-debug-sections=zlib-gnu` flag is supported here:
https://github.com/golang/go/blob/89d533e368395a5ba3157d9a89d346dd7b50ba51/src/cmd/link/internal/ld/lib.go#L1225
but does so incorrectly (it doesn't use the provided ldflags, and therefore checks whether the flag is supported by /usr/bin/ld instead of whichever linker the user selected). LLD doesn't currently support `-Wl,--compress-debug-sections=zlib-gnu`, so we get this error.

**Comment by rayvbr** [comment]
Just ran into a (possibly) related issue when using Go 1.11 to build a `--buildmode=c-shared` target for android/arm:

`/usr/local/go/pkg/tool/linux_amd64/link: running /home/root/android-ndk-linux/android-ndk-r14/toolchains/llvm/prebuilt/linux-x86_64/bin/clang failed: exit status 1
/home/root/android-ndk-linux/android-ndk-r14/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: --compress-debug-sections=zlib-gnu: must take one of the following arguments: none, zlib`

Is  6417e91 slated to be included in a future Go 1.11.1 release?

**Comment by ianlancetaylor** [comment]
@gopherbot please backport to 1.11

**Comment by qzmfranklin** [comment]
This issue is still out with golang 1.11.2, as described by https://github.com/kubernetes/kubernetes/issues/71996.

The problem is that the clang lld linker (as of 7.0.0) does not support `--compress-debug-sections=zlib-gnu` (see [this PR](https://reviews.llvm.org/D31941)).
