### ISSUE TITLE
cmd/cover: failing when the go command doesn't stay in $GOROOT/bin

### ISSUE THREAD

**Issue by mikioh** [golang/go#27113]
### What version of Go are you using (`go version`)?
+fc5107c, perhaps go1.11 too

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
no matter

### What did you do?
1. share the $GOROOT over network file system
2. move go command to $GOBIN from $GOROOT/bin, for example, set GOBIN=$HOME/bin/$GOOS_$GOARCH, after all.bash success on each $GOOS/$GOARCH
3. Run go test -coverprofile=covp && go tool cover -html=covp at some package directory

### What did you expect to see?
works well the same as go1.10 or below

### What did you see instead?
cover: cannot run go list: fork/exec $GOROOT/bin/go: no such file or directory

**Comment by mikioh** [comment]
Although, I think it's fine this is a newly introduced restriction on the versioning and module supported go command, as https://github.com/golang/go/blob/master/src/cmd/cover/func.go#L194 describes a bit.

/CC @rsc

**Comment by rsc** [comment]
Don't move the go command out of $GOROOT/bin.

**Comment by mikioh** [comment]
And don't rename the $GOROOT/bin/go command.
