### ISSUE TITLE
net/http: Data race in net/http in 1.10.3 [1.10 backport]

### ISSUE THREAD

**Issue by LK4D4** [golang/go#27129]
### What version of Go are you using (`go version`)?
go1.10.3

### Does this issue reproduce with the latest release?
No

### What did you do?

The race is between ServerMux.Handle and ServerMux.Handler, but it was fixed in https://github.com/golang/go/commit/2fd1b523952727b91e5eca76ff1f8b8af8746f7a
I just want to be sure that it'll be backported to 1.10.4, because it makes continuous race detection hard and also race is fatal because it's between map read and write.

**Comment by LK4D4** [comment]
People also were concerned about the performance hit which https://golang.org/cl/113996 mitigated. 
Not sure if it's worth to backport it too.

**Comment by bradfitz** [comment]
@LK4D4, we do not backport performance changes. People can move forward to Go 1.11 if they want new goodies.
