### ISSUE TITLE
x/build: vcs-test.golang.org is down

### ISSUE THREAD

**Issue by andybons** [golang/go#27127]
We are aware of the issue and are working on it.

**Comment by jasonkeene** [comment]
I am trying to run some git module tests right now and it appears to be down for me.

```
2018/08/30 20:05:52 git clone --mirror https://vcs-test.golang.org/git/gitrepo1 /var/folders/f2/8qjhqmss5ssb6ccx15bxvvl80000gn/T/gitrepo-test-403044532/gitrepo2 in : exit status 128:
        Cloning into bare repository '/var/folders/f2/8qjhqmss5ssb6ccx15bxvvl80000gn/T/gitrepo-test-403044532/gitrepo2'...
        fatal: unable to access 'https://vcs-test.golang.org/git/gitrepo1/': Failed to connect to vcs-test.golang.org port 443: Operation timed out
FAIL    cmd/go/internal/modfetch/codehost       75.182s

```

**Comment by jasonkeene** [comment]
@andybons Thanks for the update.

I don't have a lot of context on why these tests use `vcs-test.golang.org`. Do we need to have these tests talk to a vcs server on the internet or can the tests just start this server themselves? If the server can be ran locally I would think that would be better than having them rely on the availability of `vcs-test.golang.org`.

**Comment by FiloSottile** [comment]
vcs-test.golang.org is back up.

**Comment by andybons** [comment]
@jasonkeene I don’t know the history of vcs-test, so I’m unable to answer your question. Perhaps file a new issue specific to your question?
