### ISSUE TITLE
go/cmd: internal package rules are changed with go mod

### ISSUE THREAD

**Issue by shoenig** [golang/go#27126]
### What version of Go are you using (`go version`)?
$ go version
go version go1.11rc1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
 $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hoenig/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hoenig/Documents/indeed-go"
GOPROXY=""
GORACE=""
GOROOT="/opt/google/go"
GOTMPDIR=""
GOTOOLDIR="/opt/google/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/hoenig/Documents/indeed-go/src/indeed/systools/you-pass-butter/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build039206204=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Tried building a project with go modules turned on. Go compiler now rejects this project.
```
[p1 you-pass-butter (master)] $ export GO111MODULE=off
[p1 you-pass-butter (master)] $ go build 
[p1 you-pass-butter (master)] $ echo $?
0
[p1 you-pass-butter (master)] $ export GO111MODULE=on
[p1 you-pass-butter (master)] $ go build
main.go:9:2: use of internal package indeed/systools/you-pass-butter/internal/service not allowed
```

**Comment by shoenig** [comment]
I was able to reproduce (and fix) with a toy example - this will probably turn out to be working as intended, but it _feels_ like `go build` is conflating modules with packages.

```
[k9 mygo] $ echo $GOPATH
/tmp/mygo
[k9 mygo] $ tree src/
src/
└── mycorp
    └── myteam
        └── myproject
            ├── go.mod
            ├── internal
            │   └── mylib
            │       └── mylib.go
            ├── main.go
            └── myproject

5 directories, 4 files
```

With modules off:
```
[k9 myproject] $ GO111MODULE=off
[k9 myproject] $ go build
[k9 myproject] $ echo $?
0
```

With modules on and an evidently invalid `go.mod` file:
```
[k9 myproject] $ GO111MODULE=off
[k9 myproject] $ go build
[k9 myproject] $ echo $?
0

[k9 myproject] $ GO111MODULE=on
[k9 myproject] $ cat go.mod
module foo.bar.baz/mymodule

require mycorp/myteam/myproject v0.0.0

replace mycorp/myteam/myproject => ../../myteam/myproject
[k9 myproject] $ go build
main.go:4:8: use of internal package mycorp/myteam/myproject/internal/mylib not allowed
```

Forcing the go.mod file to conform to GOPATH:
```
[k9 myproject] $ cat go.mod 
module mycorp/myteam/myproject

require mycorp/myteam/myproject v0.0.0

replace mycorp/myteam/myproject => ../../myteam/myproject
[k9 myproject] $ go build
[k9 myproject] $ echo $?
0
```

We can certainly live with this requirement, but I was hoping to abuse arbitrarily named modules to help bridge my company from our existing non-conventional project layout to something more normal.

**Comment by bcmills** [comment]
`module foo.bar.baz/mymodule` declares that the packages in the current module have the import path prefix `foo.bar.baz/mymodule`, which is not a prefix of `mycorp/myteam/myproject/internal`.

This seems to be working as intended. (See [`src/cmd/go/testdata/script/mod_internal.txt`](https://github.com/golang/go/blob/master/src/cmd/go/testdata/script/mod_internal.txt).)
