### ISSUE TITLE
Support for unregistering individual SQL drivers

### ISSUE THREAD

**Issue by EmpireJones** [golang/go#27152]
In order to get access to a a particular underlying SQL driver connection object (to perform driver-specific operations) on that connection, the sqlite driver requires that you register a unique driver, such as in this example:
https://github.com/mattn/go-sqlite3/blob/4b0af852c17164dce48e6754e3094c55192e4934/backup_test.go#L27
```
	// This function will be called multiple times.
	// It uses sql.Register(), which requires the name parameter value to be unique.
	// There does not currently appear to be a way to unregister a registered driver, however.
	// So generate a database driver name that will likely be unique.
	var driverName = fmt.Sprintf("sqlite3_testBackup_%v_%v_%v", testRowCount, usePerPageSteps, time.Now().UnixNano())

	// The driver's connection will be needed in order to perform the backup.
	driverConns := []*SQLiteConn{}
	sql.Register(driverName, &SQLiteDriver{
		ConnectHook: func(conn *SQLiteConn) error {
			driverConns = append(driverConns, conn)
			return nil
		},
	})
```
Because the sql package doesn't have a function for unregistering drivers, this basically is just leaking memory.

The fakedb_test.go test in the sql package itself actually just calls a private unregisterAllDrivers() function to work around this, although this wouldn't be sufficient if you wanted to only unregister some drivers which were no longer being used.

Perhaps another solution would be to expose the driver connection(s) via some other strategy, so that this workaround wouldn't be needed.

**Comment by kardianos** [comment]
Database drivers should begin offering and using (in tests) https://golang.org/pkg/database/sql/#OpenDB to open a `driver.Connector`.
