### ISSUE TITLE
cmd/go: unexpected module path when using get on a repo with incorrect path casing

### ISSUE THREAD

**Issue by exts** [golang/go#27154]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11rc1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
windows 10 64bit

### What did you do?

- Create a module
- Upload module to bitbucket or github (I'm using bitbucket)
- Call `go get bitbucket.org/lowercase/reponame` (the user is upper cased, but I called it using all lower case)
- Let the execution call, watch the execution fail.

### What did you expect to see?
- If you run the command with the correct url case the error goes away and it properly grabs the latest module from the repo

### What did you see instead?

- `go: bitbucket.org/lowercase/vsc@v0.0.2: parsing go.mod: unexpected module path "bitbucket.org/LOWERCASE/vsc"

**Comment by thepudds** [comment]
@gopherbot, please add label modules

**Comment by 408445006** [comment]
@exts， have you solved the problem? i have i the problem
go version go1.11 windows/amd64

when i run
go mod init 
go get -u gitlab.haochang.tv/chenqiang/go-redlock@v1.0.0
go: gitlab.haochang.tv/chenqiang/go-redlock@v1.0.0: parsing go.mod: unexpected module path "redlock"

**Comment by agnivade** [comment]
I think the module path in a go.mod is case-sensitive. @bcmills for further comments.

@408445006 - Your issue is different. You are trying to get go-redlock, but you have redlock inside go.mod.

**Comment by bcmills** [comment]
The module path is case-sensitive and must match the path requested of `go get`.

(URLs are only specified to be case-insensitive as far as the domain, and in general we don't know whether a given server is case-sensitive or not, so we rely on the module declaration to clarify the intended module path.)
