### ISSUE TITLE
go mod: simultaneous imports of different casings for a dependency fails

### ISSUE THREAD

**Issue by voutasaurus** [golang/go#27157]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

See readme: https://github.com/voutasaurus/modtest

Using different cased characters in an import path for the same dependency.

#### What did you expect to see?
Resolution to the same dependency.

#### What did you see instead?
```
upper/upper.go:4:2: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

(See https://github.com/voutasaurus/modtest README for more info)

#### Does this issue reproduce with the latest release (go1.10.3)?
Applies to release candidate go1.11rc1, not go1.10.3.

#### System details

(from golang:rc docker image)

```
go version go1.11rc1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/src/github.com/voutasaurus/modtest/go.mod"
GOROOT/bin/go version: go version go1.11rc1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.11rc1
uname -sr: Linux 4.9.93-linuxkit-aufs
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.24-11+deb9u3) stable release version 2.24, by Roland McGrath et al.
```

**Comment by thepudds** [comment]
@gopherbot, please add label modules

**Comment by voutasaurus** [comment]
Looks like a duplicate of #26208 my bad
