### ISSUE TITLE
time: Timer.Stop documentation example easily leads to deadlocks

### ISSUE THREAD

**Issue by palsivertsen** [golang/go#27169]
I needed timeout functionality for one of my projects, so I looked in the `time` package. My timeouts where fallbacks in case a channel receive took too long. Most of the time the channel would receive before the timeout and I wanted to release the timeout resources when they where no longer needed. Documentation for [time.After()](https://golang.org/pkg/time/#After) says:
> [...] If efficiency is a concern, use NewTimer instead and call Timer.Stop if the timer is no longer needed.

So I used a [time.Timer](https://golang.org/pkg/time/#Timer) and according to the documentation for [time.Timer.Stop()](https://golang.org/pkg/time/#Timer.Stop) one should drain the channel if `time.Timer.Stop()` returns false:
```
if !t.Stop() {
	<-t.C
}
```

I later discovered that my threads got stuck on receive like in [this playground example](https://play.golang.org/p/24wBkSbuonN) when timer where triggered before I called stop:
```
t := time.NewTimer(time.Second * 3)
defer func() {
	if !t.Stop() {
		<-t.C
	}
}()
<-t.C
```

[Wrapping the drain](https://play.golang.org/p/UlG1TOSDNrM) in a select seems to do the trick:
```
t := time.NewTimer(time.Second * 3)
defer func() {
	t.Stop()
	select {
	case <-t.C:
	default:
	}
}()
<-t.C
```

Documentation should make it clear how to safely drain the channel.

**Comment by FMNSSun** [comment]
```
t := time.NewTimer(time.Second * 3)
defer func() {
	if !t.Stop() {
		<-t.C
	}
}()
<-t.C
```

Isn't this incorrect usage because you've already received from `t.C`. Isn't the point of the timer to fire after the delay except if you call Stop on it? `<-t.C` already waits for the timer to fire so the stop in the defered function is entirely useless because the timer has already fired anyway?

**Comment by FMNSSun** [comment]
`t.Stop()` returns false when the timer has already fired so the receive there should deadlock, yes. What the documentation suggests is really weird though because:

What's the problem with it firing? This is only a problem if there are other receivers and the documentation mentions that this is incorrect if there are concurrent receives. Wrapping it in a select

```
select {
  <-t.C..
  default..
}
```

wouldn't prevent anything unless `Stop` causes the timer to fire because you'd just immediately go into the `default` case and somebody later could still receive something from `t.C` because it hasn't been read yet. Also, the documentation mentions that you sholudn't use this `if !t.Stop()` if you've _already_ read from `t.C` so what you're doing is incorrect usage according to the documentation.

**Comment by FMNSSun** [comment]
FWIW: This would be an example of proper usage:

```
package main

import "time"
import "fmt"

func main() {
	t := time.NewTimer(time.Second * 3)
	foo := make(chan int)
	go func() { foo <- 1 }()
	select {
	case <-t.C:
		fmt.Println("timeout")
	case <-foo:
		fmt.Println("foo")
		if !t.Stop() {
			<-t.C
		}
	}
}

```

**Comment by artyom** [comment]
> My timeouts where fallbacks in case a channel receive took too long. Most of the time the channel would receive before the timeout and I wanted to release the timeout resources when they where no longer needed.

I believe you don't really need to drain the timer channel for this, calling Timer.Stop will suffice:

```
timer := time.NewTimer(3 * time.Second)
defer timer.Stop()
select {
case res := <- workChannel:
    return res, nil
case <-timer.C:
    return nil, ErrTimeout
}
```

You may find such pattern in use in standard library.

**Comment by palsivertsen** [comment]
@FMNSSun 
Thanks for the explanation. Your example looks somewhat like what I did in the first place. But I had more channels in my `select` and didn't like all the extra `t.Stop()` calls:
```
t := time.NewTimer(time.Second * 3)
bar := make(chan int)
chicken := make(chan int)
egg := make(chan int)
go func() { foo <- 1 }()
select {
case <-t.C:
	fmt.Println("timeout")
case <-foo:
	fmt.Println("foo")
	if !t.Stop() {
		<-t.C
	}
case <-chicken:
	fmt.Println("chicken")
	if !t.Stop() {
		<-t.C
	}
case <-egg:
	fmt.Println("egg")
	if !t.Stop() {
		<-t.C
	}
}
```

@artyom 
> I believe you don't really need to drain the timer channel for this, calling Timer.Stop will suffice

Looks scary. What if timer triggers between the `select` block and the defer? Won't you have a thread stuck on channel send?

**Comment by FMNSSun** [comment]
@palsivertsen No because timer uses a buffered channel with capacity 1 exactly for this reason: that it can't get stuck if there's nobody reading from it.

**Comment by palsivertsen** [comment]
> timer uses a buffered channel with capacity 1 exactly for this reason: that it can't get stuck if there's nobody reading from it.

Cool. I did not know that.

> Also... it might make sense in that case to move the t.Stop past the select instead of repeating it in every case.

Wouldn't that deadlock if `case <-t.C:` happens?

**Comment by FMNSSun** [comment]
@palsivertsen it would but you could set a flag in the `case <-t.C` case and then only invoke stop if that flag isn't already set. But

**Comment by ran-eh** [comment]
+1 this issue just cost me an hour :(  I also have the keep-alive scenario.  Perhaps the the docs should link to this discussion?

**Comment by ianlancetaylor** [comment]
I don't think we want to link to this discussion.

Does anyone have specific improvements to suggest?  Anyone want to send a pull request?  Thanks.

**Comment by palsivertsen** [comment]
Some suggestions/thoughts:
* Update the doc to underline that ignoring the value of the time.Timer.C channel is safe because the channel has a buffer length of one.
* Remove channel draining from time.Timer.Stop documentation. Are there any usecases where one would need/want to drain the channel when stopping (not resetting) the timer?
* Make time.Timer.Reset do the draining internally, thus no need to expose the drain concept in the docs.  This sadly changes the behaviour of time.Timer.Reset, possibly breaking existing code. Adding time.Timer.ResetAndDrain might be an alternative.

**Comment by MichaelSnowden** [comment]
> @palsivertsen No because timer uses a buffered channel with capacity 1 exactly for this reason: that it can't get stuck if there's nobody reading from it.
> 
> Also... it might make sense in that case to move the `t.Stop` past the select instead of repeating it in every `case`.

@FMNSSun do you have a source for this?

**Comment by rsc** [comment]
The documentation no longer gives this example, because it is no longer necessary.
