### ISSUE TITLE
x/tools/cmd/goimports: 21+ chars struct field breaks indentation for next lines

### ISSUE THREAD

**Issue by cixtor** [golang/go#27177]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (go version)?

go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes, as of today.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yorman/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yorman"
GORACE="log_path=stderr exitcode=66"
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gy/scj0933963ggbfdxcn5c91vw0000gn/T/go-build529046567=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Pay attention to lines 23 and 24 in the following code snippets:

• Correct formatting: https://play.golang.org/p/NHH57Ucegxa  
• Incorrect formatting: https://play.golang.org/p/MgCpu-Ux5B5

### What did you expect to see?

Values for the struct fields after line 23 should be placed in the same column as line 23.

### What did you see instead?

All values for the struct fields after line 23 _(which contains a field name with more than 21 characters)_ are using a different indentation as the previous lines, consequently breaking the formatting for the whole block of code.

**Comment by ianlancetaylor** [comment]
CC @griesemer

**Comment by mvdan** [comment]
This is expected in Go 1.10. In fact, 1.11 does this correctly, and all fields are aligned properly. See https://tip.golang.org/doc/go1.11#gofmt and https://github.com/golang/go/commit/542ea5ad91367d2b40589942cc5757a4d5f43f97 for details.

**Comment by mvdan** [comment]
To clarify - `goimports` uses `go/format` to format code, which uses the same logic as `gofmt`. So once you build `goimports` with Go 1.11, you'll get the correct behavior.

**Comment by kumarharsh** [comment]
Hi @mvdan. In the tip which you've linked to, it's written that 
> In general, systems that need consistent formatting of Go source code should use a specific version of the `gofmt` binary.

But the `gofmt` or `goimports` don't even have a `--version` or `-v` switch. How do I find the version of the binaries?
