### ISSUE TITLE
mkdir: permission denied

### ISSUE THREAD

**Issue by harshit777** [golang/go#27187]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04 LTS/amd64

### What did you do?
go get -u golang.org/x/review/git-codereview

GOARCH="amd64"
GOBIN="/home/user/workspace/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/workspace"
GORACE=""
GOROOT="/home/harshit/go"
GOTOOLDIR="/home/harshit/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build479770429=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config

### What did you expect to see?
package installation

### What did you see instead?
package golang.org/x/review/git-codereview: mkdir /home/user: permission denied

**Comment by meirf** [comment]
Your GOPATH points to "/home/user/workspace". Instead, can you set it to "/home/harshit/workspace" and try again?

**Comment by harshit777** [comment]
DID it ! got a new error>>>

# runtime/internal/sys
go/src/runtime/internal/sys/arch_wasm.go:8:24: ArchFamily redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:8:24
go/src/runtime/internal/sys/arch_wasm.go:8:24: undefined: WASM
go/src/runtime/internal/sys/arch_wasm.go:9:24: BigEndian redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:9:24
go/src/runtime/internal/sys/arch_wasm.go:10:24: CacheLineSize redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:10:24
go/src/runtime/internal/sys/arch_wasm.go:11:24: DefaultPhysPageSize redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:11:24
go/src/runtime/internal/sys/arch_wasm.go:12:24: PCQuantum redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:12:24
go/src/runtime/internal/sys/arch_wasm.go:13:24: Int64Align redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:13:24
go/src/runtime/internal/sys/arch_wasm.go:14:24: HugePageSize redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:14:29
go/src/runtime/internal/sys/arch_wasm.go:15:24: MinFrameSize redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:15:24
go/src/runtime/internal/sys/arch_wasm.go:18:6: Uintreg redeclared in this block
	previous declaration at go/src/runtime/internal/sys/arch_amd64.go:18:6
go/src/runtime/internal/sys/arch_wasm.go:8:24: too many errors

**Comment by harshit777** [comment]
I tried to uninstall go but it wont
Removed the path from profile, used auto-remove commands but the binaries are still there 
I can still see the version in the terminal.

**Comment by agnivade** [comment]
You seem to have multiple installations of Go. In the issue report, you have 1.9.1, but the errors are from arch_wasm.go (which is not in 1.9). I would guess the go binary that you are running points to a GOROOT of a different Go distribution.

>  used auto-remove commands but the binaries are still there

Um well, so why don't you delete them and have a clean slate ?

I am sorry, but you will have to debug this on your own. This is not a Go issue.

Please feel free to reach out to the forums at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions. Folks will gladly help you out.

Closing this since I don't believe this is a system installation issue. Please comment if you feel otherwise.

**Comment by harshit777** [comment]
Just to clear my doubt Actually go folder was locked until changed the permission 
sudo chown -R $USER: $HOME

Now the binaries got cleared. Done. Thnx for suggestions.

**Comment by souvikhaldar** [comment]
> Just to clear my doubt Actually go folder was locked until changed the permission
> sudo chown -R $USER: $HOME
Why did we have to assign permission? I too was facing this problem `chown` did the job but somehow this doesn't feel right!
