### ISSUE TITLE
cmd/compile: unused variable escapes to the heap

### ISSUE THREAD

**Issue by marigonzes** [golang/go#27188]
### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=...
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=...
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=...

### What did you do?
I compiled the following program using `go build -gcflags="-m -m" to check if any of the variables escaped to the heap.
https://play.golang.org/p/iZCz8oXRoi__h

### What did you expect to see?
I expected only y to escape.

### What did you see instead?
Instead, both x and y escaped to the heap.
In my opinion, only y should escape, because there is no way for x to leave the scope of this function. Alternatively, the assignment of the address of x to k should be entirely removed.

**Comment by ianlancetaylor** [comment]
CC @dr2chase

**Comment by dr2chase** [comment]
The algorithm we use is not that clever and just tracks flow by variable name.
If/when we get around to moving escape analysis into the SSA phase (there are several difficult prerequisites in the way of this happening -- and these are planned, e.g., moving call expansion into SSA) this will be fixed as a side-effect.

Since there's an easy workaround and big blockers for the proper fix, I would not commit to fixing this in 1.12.

**Comment by dr2chase** [comment]
One possible benefit, from talking to a guy at GopherCon (@cixel) who's interested in doing instrumentation for taint detection/analysis, is doing dataflow-informed instrumentation.  Idea is that we'd transform to SSA, do whatever instrumentation we want (that might, in some cases, have effects on escape analysis -- and might also have effects on stack frames), then run escape analysis etc.

This is still a little hand-wavy.  He's looking the code for tsan and msan, and modifying things at the AST level, but having the ability to do flow analysis would be helpful (I wonder if it might not also help tsan and msan)

**Comment by mdempsky** [comment]
Dup of #18300; TL;DR: escape analysis is not path sensitive.

See also #31501.
