### ISSUE TITLE
x/build: s390x builder not receiving/detecting new builds

### ISSUE THREAD

**Issue by billotosyr** [golang/go#27182]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
master tip (1.12)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="s390x"
GOBIN=""
GOEXE=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/data/golang/go"
GOTOOLDIR="/data/golang/go/pkg/tool/linux_s390x"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build637051903=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
loaded the build dashboard

### What did you expect to see?
s390x building with all the new CL's

### What did you see instead?
Since yesterday (Aug. 22) it's been silent. The buildbot is still running normally (as far as I can tell) but no builds are happening. Suggestions?

**Comment by billotosyr** [comment]
@mundaym

**Comment by dmitshur** [comment]
I see 23 entries of linux-s390x-ibm under [active builds](https://farmer.golang.org/#active). They're all started anywhere between 51 and 46 hours ago, and stuck on this step:

```
waiting_machine_in_use 
```

That might be related.

**Comment by dmitshur** [comment]
> The buildbot is still running normally (as far as I can tell) but no builds are happening. Suggestions?

@billotosyr @mundaym Can you try restarting it (the buildlet process)? Perhaps it's running but disconnected, and hasn't detected that.

You can also try updating to the latest version (i.e., `go get golang.org/x/build/cmd/buildlet`).

**Comment by billotosyr** [comment]
restarted buildlet process - doesn't seem to have had any effect.

**Comment by billotosyr** [comment]
I'm pretty sure its not a version thing -- as the buildlet was working up untl a benign unrelated CL yesterday ("skip TestGcSys on Windows").
Our machine had run out of space, we fixed it, and it started building again, but somehow the queue is too big perhaps? It just seems clogged. Any thoughts on getting it unclogged?

**Comment by dmitshur** [comment]
> Our machine had run out of space, we fixed it, and it started building again, but somehow the queue is too big perhaps? It just seems clogged. Any thoughts on getting it unclogged?

Great to hear that it's running again!

Do you know if the machine ran out of space due to the Go builder work, or was it for unrelated reasons?

About the queue, after talking to @bradfitz about it, I don't think there's an existing way to clear it out. Sorry about that. We have an open bug for a scheduler (#19178) and that would be helpful here (e.g., prioritize more recent commits). Let's keep an eye on how the builder runs, and I'll investigate what else can be done to help.

**Comment by billotosyr** [comment]
Specifically, it's build cache that is filling up the drive. My current workaround is to use 
'go clean -cache '
as root, frequently. Perhaps I will have to turn off the build cache.

**Comment by billotosyr** [comment]
Our buildlet doesn't do that. Maybe because it's an older version.

**Comment by bradfitz** [comment]
No, I was just misremembering. But if that helps your environment & wrapper process that's managing keeping it alive, we could add it to the buildlet.

**Comment by billotosyr** [comment]
Well, I think it would help us, yes. The build cache is consuming about 2GB per day, and the drive it's on is small enough that I am now cleaning it daily. (This is a new thing, as I never had to clean it before.)

**Comment by bradfitz** [comment]
Okay, this the new s390x buildlet binary is pushed.

I'll watch it for any new problems.

It'll keep itself cleaned for new stuff, but you might have to clean legacy messes.

**Comment by billotosyr** [comment]
Thank you! There may be an issue though:
https://build.golang.org/log/4972bb50dbc4c99c530bc3c9bea9edffb70d3430

**Comment by bradfitz** [comment]
Hmm, weird.

I'll debug in a few hours.
