### ISSUE TITLE
gccgo: reference to undefined identifier ‘syscall.Statfs_t’

### ISSUE THREAD

**Issue by amandeepgautam** [golang/go#27192]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 gccgo (GCC) 8.2.1 20180813 solaris/sparc

### Does this issue reproduce with the latest release?
Yes. Compiled from source.

### What operating system and processor architecture are you using (`go env`)?
amandeep@s113ldom1:~/workspace/main/magneto/agents/go/main$ go env
GOARCH="sparc"
GOBIN=""
GOCACHE="/home/amandeep/.cache/go-build"
GOEXE=""
GOHOSTARCH="sparc"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH="/home/amandeep/go"
GORACE=""
GOROOT="/usr/gnu"
GOTMPDIR=""
GOTOOLDIR="/usr/gnu/libexec/gcc/sparc-sun-solaris2.11/8.2.1"
GCCGO="/usr/gnu/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282896547=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

### What did you do?
tried to compile:

package main

import (
  "syscall"
)

func main() {
  temp := new(syscall.Statfs_t)
  syscall.Statfs("/home/amandeep", temp)
}

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
successful compilation

### What did you see instead?
compiler error:

./syscl.go:8:23: error: reference to undefined identifier ‘syscall.Statfs_t’
   temp := new(syscall.Statfs_t)
                       ^
./syscl.go:9:11: error: reference to undefined identifier ‘syscall.Statfs’
   syscall.Statfs("/home/amandeep", temp)
           ^
./syscl.go:8:23: error: expected type
   temp := new(syscall.Statfs_t)

**Comment by ianlancetaylor** [comment]
There is no `syscall.Statfs_t` on Solaris because Solaris has no `struct statfs` in C.  Solaris uses `struct statvfs` instead.  The syscall package is inherently not portable across systems.  Whatever package you are compiling is unlikely to work on Solaris.

Closing because I don't see anything to fix in the Go project.

**Comment by amandeepgautam** [comment]
@ianlancetaylor I need to get the size of different mounted file systems on Solaris. Is there a function in syscall for that in Solaris? I can ultimately parse the output for df if nothing works, but am looking for a better alternative.

**Comment by ianlancetaylor** [comment]
You should be able to use the golang.org/x/sys/unix package and call `unix.Statvfs`.

**Comment by ianlancetaylor** [comment]
To be clear, `unix.Statvfs` is only available on Solaris.  If your program is meant to be portable you'll need to use build tags.

**Comment by amandeepgautam** [comment]
Hi @ianlancetaylor,
   Thanks for the clarification. Yes, I have been using build tags as we support multiple platforms. I tried getting

**Comment by tklauser** [comment]
@amandeepgautam it seems you're using `solaris/sparc`, but the `golang.org/x/sys/unix` package currently only supports `solaris/amd64`.

**Comment by amandeepgautam** [comment]
@tklauser @ianlancetaylor also what would be the best way to get the size for solaris/sparc

**Comment by ianlancetaylor** [comment]
Unfortunately, the simplest way to move forward will be to use cgo (https://golang.org/cmd/cgo) instead of golang.org/x/sys/unix.
