### ISSUE TITLE
database/sql: confusing documentation for Rows.Columns

### ISSUE THREAD

**Issue by AlekSi** [golang/go#27202]
https://tip.golang.org/pkg/database/sql/#Rows.Columns says:

> Columns returns the column names. Columns returns an error if the rows are closed, **or if the rows are from QueryRow and there was a deferred error.**

That latter part does not make sense: it is not possible to convert Row (returned by QueryRow) to Rows.

Unless I miss something, that part should be removed.

**Comment by meirf** [comment]
If this is a mistake I'm surprised it hasn't been found yet. Your "not make sense" logic seems to apply equally to the original code: https://codereview.appspot.com/5483088/diff/4001/src/pkg/exp/sql/sql.go

**Comment by kardianos** [comment]
@AlekSi I believe you are correct. Feel free to send a CL to fix, or I will later.
