### ISSUE TITLE
doc: link to main entry point for modules documentation is not working and various module sections are not recognized as headers

### ISSUE THREAD

**Issue by thepudds** [golang/go#27209]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go 1.11 doc at golang.org:

https://golang.org/doc/go1.11

### Does this issue reproduce with the latest release?

Yes.

### Issue

Clicking on the modules link in the release notes (where the text is `new concept called “modules,”`) does not take you to the modules documentation because the fragment identifier does not exist any longer on the go command documentation page:

https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more

If you look at the sections present in the HTML documentation at https://golang.org/cmd/go, there are various sections that are not being treated as headers (including they don't show up in the table of contents, and they are not formatted as headers in the main body of the documentation). 

'Bad' sections include:

* The go.mod file
* Edit go.mod from tools or scripts
* Modules, module versions, and more

Interestingly, the documentation on tip.golang.org seems to not have this issue. For example, this works:

https://tip.golang.org/cmd/go/#hdr-Modules__module_versions__and_more

Perhaps some variation or re-occurrence of #26938 or similar...

**Comment by thepudds** [comment]
This is also a 'bad' / missing section header that is present on tip.golang.org but missing at golang.org:
* Gofmt (reformat) package sourcesGo

The 'bad' / missing section headers all seem to include at least one of `(`, `)`, or `.` characters, whereas the 'good' / present section headers do not have those characters.

It seems the golang.org doc might have been generated without either of these:

https://golang.org/cl/122407        // from ~2 months ago
https://golang.org/cl/129677        // from a ~week ago

Maybe the Go 1.10 or some other non-recent version was used to generate the Go 1.11 golang.org doc site?

**Comment by FiloSottile** [comment]
This is due to #27205.

**Comment by andybons** [comment]
This has since been resolved. Thanks.
