### ISSUE TITLE
cmd/compile: incorrect stack trace for nil dereference in inlined function

### ISSUE THREAD

**Issue by robfig** [golang/go#27201]
I believe that the stack trace for panics that occur when computing arguments to an inlined function are incorrectly attributed to the inlined function. I'm not sure if this is a known / expected consequence of inlining, but it caused a lot of confusion to see a line identified where a nil dereference is impossible. 

### What version of Go are you using (`go version`)?
Go 1.10.3

### Does this issue reproduce with the latest release?
Yes, it still exists in Go 1.11rc1

### What did you do?
https://play.golang.org/p/V5EzYYYSDjz

### What did you expect to see?
A panic with this stack trace, identifying the line of the nil dereference:
```
goroutine 1 [running]:
main.main()
	/tmp/sandbox722989325/main.go:10 +0x1a
```

### What did you see instead?
Incorrect attribution to an innocent function.

```
goroutine 1 [running]:
main.helperCall(...)
	/tmp/sandbox722989325/main.go:14
main.main()
	/tmp/sandbox722989325/main.go:10 +0x1a
```

**Comment by randall77** [comment]
I see what is happening now.

My last comment was incorrect, the MOVLQSX is indeed marked at line 14.
(My CL to change -S to report the innermost line number makes that obvious now.)

What's happening here is that two instructions are being merged, and the choice of line number is pretty arbitrary:
```
v7 (10) = Load <int32> v6 v1 (a[int32])
v10 (+14) = SignExt32to64 <time.Duration> v7 (~r1[time.Duration])
```
gets merged to
```
v45 (+14) = MOVLQSXload <time.Duration> v4 v1
```
Note that the load is line 10 and the sign extension is line 14. That's correct. The merged instruction ends up at line 14. That's not incorrect, but maybe not super helpful. In particular, I think the line number of the load (or any possibly faulting instruction really) should supercede the line number of the sign extension.
