### ISSUE TITLE
doc: website not showing Go1.11 release notes link

### ISSUE THREAD

**Issue by rajender** [golang/go#27206]
https://golang.org/project/ doesn't list Go1.11.

**Comment by marigonzes** [comment]
It is also not showing up in https://golang.org/doc/devel/release.html

**Comment by dmitshur** [comment]
Thanks, we're aware of this and it will be resolved soon.

As a workaround, in the meantime, you can refer to https://tip.golang.org/pkg. E.g.:

https://tip.golang.org/pkg/os/#UserCacheDir

**Comment by FiloSottile** [comment]
This is due to #27205.

**Comment by ALTree** [comment]
Fixed in [CL 138355](https://go-review.googlesource.com/c/go/+/138355), see: https://tip.golang.org/project/

Closing here.
