### ISSUE TITLE
redeclared constants in ld 

### ISSUE THREAD

**Issue by wsc1** [golang/go#27211]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
I can't build the latest release because of it.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/scott/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/scott/3p/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wv/qs6x44tj2bs8rm7fqw8p79yw0000gn/T/go-build683100334=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

Download the new go1.11, run ./all.bash from src.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
The build to work.

### What did you see instead?
⎣ ⇨ ./all.bash 
Building Go cmd/dist using /usr/local/go.
Building Go toolchain1 using /usr/local/go.
# bootstrap/cmd/link/internal/ld
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:97: IMAGE_SYM_TYPE_NULL redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:25
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:98: IMAGE_SYM_TYPE_STRUCT redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:33
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:99: IMAGE_SYM_DTYPE_FUNCTION redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:44
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:100: IMAGE_SYM_DTYPE_ARRAY redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:45
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:101: IMAGE_SYM_CLASS_EXTERNAL redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:49
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:102: IMAGE_SYM_CLASS_STATIC redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:50
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:104: IMAGE_REL_I386_DIR32 redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:77
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:105: IMAGE_REL_I386_SECREL redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:81
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:106: IMAGE_REL_I386_REL32 redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:84
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:108: IMAGE_REL_AMD64_ADDR64 redeclared in this block
	previous declaration at /Users/scott/Dev/go/src/cmd/link/internal/ld/ldpe.go:86
/Users/scott/Dev/go/src/cmd/link/internal/ld/pe.go:108: too many errors

**Comment by randall77** [comment]
There is no file `src/cmd/link/internal/ld/ldpe.go` in the go1.11 distribution (at least, in the source distribution).  Are you sure you didn't unpack it on top of an older distribution?

**Comment by randall77** [comment]
(That file was last in 1.9.7.)

**Comment by wsc1** [comment]
Thanks that must have been it.  Fixed
