### ISSUE TITLE
doc: downloads page claims that Go 1.11 supports unsupported operating systems

### ISSUE THREAD

**Issue by dominikh** [golang/go#27213]
Support for Windows XP was removed in Go 1.11, but golang.org/dl/ still claims that it's supported:

![2018-08-25-094036_485x239_scrot](https://user-images.githubusercontent.com/39825/44616160-fd913b80-a84a-11e8-8ff1-499b7625a2d6.png)

**Comment by marigonzes** [comment]
The same happens for macOS, where the minimum version is now 10.10:
![macos](https://user-images.githubusercontent.com/29440725/44616948-fd486e80-a851-11e8-9eda-b29cb5bee326.PNG)

**Comment by bradfitz** [comment]
Actually I think this partly yet another duplicate of #27205.

The website is running a mix of Go 1.9 and Go 1.10 and Go 1.11. It's kinda a mess.
 
The text above is coming from the x/tools Go 1.10 branch. But the text is wrong even at tip, but fixing it won't fix it on the website until we fix #27205 also. I suppose we could cherry-pick the fixes back to Go 1.10.

Will send a change.
