### ISSUE TITLE
os: Stat on a symlink fails when path has a trailing slash

### ISSUE THREAD

**Issue by AudriusButkevicius** [golang/go#27225]
### What version of Go are you using (`go version`)?

go version go1.11 windows/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10 with Developer mode enabled (allowing to create symlinks for unprivileged users)

### What did you do?

```
c:\temp>type test.go
package main

import (
  "os"
  "fmt"
)

func main() {
  fmt.Println(os.Lstat(`c:\temp\b`))
  fmt.Println(os.Lstat(`c:\temp\b\`))
}
```

```
c:\temp>mkdir a

c:\temp>mklink /D b a
symbolic link created for b <<===>> a

c:\temp>cmd /c "set GOROOT=c:\go1.10.4&& c:\go1.10.4\bin\go.exe run test.go"
&{b {1040 {477620318 30686378} {477620318 30686378} {477620318 30686378} 0 0} 0 {0 0} c:\temp\b 0 0 0 false} <nil>
&{b {1040 {477620318 30686378} {477620318 30686378} {477620318 30686378} 0 0} 0 {0 0} c:\temp\b\ 0 0 0 false} <nil>

c:\temp>cmd /c "set GOROOT=c:\go&& c:\go\bin\go.exe run test.go"
&{b 1040 {477620318 30686378} {477620318 30686378} {477620318 30686378} 0 0 2684354572 0 {0 0} c:\temp\b 0 0 0 false} <nil>
<nil> FindFirstFile c:\temp\b\: The system cannot find the file specified.
```

Same issue between Stat and Lstat

### What did you expect to see?

Stat to succeed, like it did in  Go 1.10.4

### What did you see instead?

Stat failed

**Comment by mvdan** [comment]
Does this only happen on Windows?

**Comment by AudriusButkevicius** [comment]
Yes, as far as I found.

**Comment by alexbrainman** [comment]
@AudriusButkevicius thank you for reporting the issue. I will investigate when I have time.

Alex

**Comment by AudriusButkevicius** [comment]
I won't be able to try it out as I have no pc access for 3-4 weeks. Ping @calmh, @imsodin who might be able to help.

**Comment by alexbrainman** [comment]
> I won't be able to try it out as I have no pc access for 3-4 weeks.

Never mind that. You will try when you can.

Alex
