### ISSUE TITLE
go version go1.10.3 windows/amd64 ztypes_windows.go missing

### ISSUE THREAD

**Issue by donskiba** [golang/go#27226]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by mvdan** [comment]
Empty issue.

**Comment by donskiba** [comment]
What version of Go are you using (go version)?
1.10.3 windows/amd64
Does this issue reproduce with the latest release?
This is the latest release
What operating system and processor architecture are you using (go env)?
C:\Users\don>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\don\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\don\AppData\Local\Temp\go-build704538162=/tmp/go-build -gno-record-gcc-switchesC:\Users\don>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\don\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\don\AppData\Local\Temp\go-build704538162=/tmp/go-build -gno-record-gcc-switches
What did you do?
go build github.com\golang\example\hello
If possible, provide a recipe for reproducing the error.
I Did an msi install from golang downloads
setup GOPATH to C:\Projects\Go

A complete runnable program is good.
A link on play.golang.org is best.

What did you expect to see?
Does this issue reproduce with the latest release?
What operating system and processor architecture are you using (go env)?
Windows 10 latest updates
What did you do?
After the build gave up, all the errors were looking for ztypes_windows.go
If possible, provide a recipe for reproducing the error.
Follow the "Getting Started on golang.org
A complete runnable program is good.
A link on play.golang.org is best.

What did you expect to see?
A file in the %GOPATH%/bin directory and NO errors.
