### ISSUE TITLE
 "go doc" can't work correct under module mode.

### ISSUE THREAD

**Issue by rocket049** [golang/go#27237]
The  "go doc" is very important. 

It should be always work correct.

**Comment by myitcv** [comment]
Please can you fill out the issue template with details?

**Comment by myitcv** [comment]
Actually, I'll close this issue. Please can you complete a new issue (https://github.com/golang/go/issues/new) filling out details in the template? 

Thanks

**Comment by rocket049** [comment]
I have fill the details.

At 2018-08-26 22:02:32, "Paul Jolly" <notifications@github.com> wrote:


Actually, I'll close this issue. Please can you complete a new issue (https://github.com/golang/go/issues/new) filling out details in the template?

Thanks
