### ISSUE TITLE
database/sql: why not check connection timeout in putConn

### ISSUE THREAD

**Issue by treeinlake** [golang/go#27241]
### What did you see instead?
In function `putConn`, there is no check driverConn timeout (which is set in `db.SetConnMaxLifetime`)
- https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1226

And in fuction `conn` there is `conn.expired(lifetime)`
- https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1103

### What did you expect to see?
Why not check the connection timeout before put it into the idle connection pool?
Maybe it will be late to check it when we really get it from pool and return a driver.ErrBadConn.

**Comment by kardianos** [comment]
Drivers should implement ResetConnection, if only to check the connection status before use.

I don't remember the reason off the top of my head.

**Comment by treeinlake** [comment]
I can't find the implementation of ResetConnection in [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql). May you point it out for me? thx
From my humble opinion, I think the current way of Sql.go is easy to trigger the driver.ErrBadConn (https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1105), and may let the driver ended in sth like below ( under settings like SetMaxOpenConns(1000) && set SetMaxIdleConns(1000) && set SetConnMaxLifetime(30)):
```
[mysql] ... packets.go:36: read tcp ip:port->ip2:port2: i/o timeout
err: invalid connection
```

**Comment by kardianos** [comment]
Looks like it is called ResetSession and is implemented here: https://github.com/go-sql-driver/mysql/blob/749ddf1598b47e3cd909414bda735fe790ef3d30/connection.go#L649 .

> From my humble opinion, I think the current way of Sql.go is easy to trigger the driver.ErrBadConn (https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1105),
and may let the driver ended in sth like below ( under settings like SetMaxOpenConns(1000) && set SetMaxIdleConns(1000) && set SetConnMaxLifetime(30)):

I'm not sure what you are trying to say here. Are you trying to avoid messages like "err: invalid connection"? Are you seeing this in your logs?

**Comment by dolmen** [comment]
https://golang.org/pkg/database/sql/driver/#SessionResetter

**Comment by kardianos** [comment]
You're chasing the wrong tree I think, if you are trying to get around `[mysql] ... packets.go:36: read tcp ip:port->ip2:port2: i/o timeout
`

Try to reproduce it locally in a test case. Try to adjust the sql.DB pool's settings, then try to adjust the MySQL server settings. It probably has to do with the connection string you are using would be my guess.

**Comment by methane** [comment]
ConnMaxLifetime and i/o timeout are totally unrelated.
You used [readTimeout](https://github.com/go-sql-driver/mysql#readtimeout), or writeTimeout or timeout of mysql.  That caused the i/o error.
And because of database/sql design, we can not return ErrBadConn for the i/o error.  (Otherwise, database/sql may execute non-idempotant queries again.  It's very bad bug.)

The connection returning i/o error is in bad state.  We can not reuse the connection.
That cause "err: invalid connection" log and ErrBadConn is returned.

I think this issue should be closed.
