### ISSUE TITLE
cmd/go: for go mod download, -dir option does not exist

### ISSUE THREAD

**Issue by mpl** [golang/go#27243]
### What version of Go are you using (`go version`)?

go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="linux"

### What did you do?

$ echo $PWD
/home/mpl/src/perkeep.org
$ echo $GOPATH
/home/mpl
$ echo $GO111MODULE
on
$ go mod download -dir github.com/gopherjs/gopherjs
flag provided but not defined: -dir
usage: go mod download [-dir] [-json] [modules]
Run 'go help mod download' for details.

### What did you expect to see?

I wanted to see what the -dir option does.
The longer answer is I was trying to find out where go get/download stores the downloaded sources, since I hadn't found it in the documentation. I now see with a more thorough read that it is in GOPATH/pkg/mod

**Comment by agnivade** [comment]
Seems like a genuine oversight. There seems to be only the json flag for download. https://github.com/golang/go/blob/master/src/cmd/go/internal/modcmd/download.go#L50.

**Comment by dolmen** [comment]
The bug seems in the documentation (`go help mod download`) that should not mention the inexistent `-dir` option.

**Comment by mark-rushakoff** [comment]
If this is just removing `-dir` from the output of `go help mod download`, it would be nice to backport to 1.11.

**Comment by bcmills** [comment]
@gopherbot, please backport to 1.11: this is a doc-only fix.
