### ISSUE TITLE
force location of package in go.mod

### ISSUE THREAD

**Issue by nhooyr** [golang/go#27253]
Example scenario for why I think this is a good idea (I ran into this today):

I've ran into a bug in package `github.com/example/x/bar` so I forked `github.com/example/x` to `github.com/nhooyr/x` and then fixed the bug in the sub package. The bug was in `github.com/example/x/bar/meow`.

However I cannot directly use `github.com/nhooyr/x` in my code because `github.com/nhooyr/x/bar` will import `github.com/example/x/bar/meow` and not my fixed `github.com/nhooyr/x/bar/meow`. I could rename the import paths but it'd be much cleaner if the go tool let me force the location of a package in `go.mod`. Another benefit is that I would only need one branch on my fork to create a PR on upstream and use internally. I wouldn't have to maintain two separate branches, one with import paths renamed and one without.

**Comment by kardianos** [comment]
Use the replace directive in the go.mod file.

**Comment by dolmen** [comment]
See `go help go.mod`.
