### ISSUE TITLE
wiki: Go WebAssembly

### ISSUE THREAD

**Issue by sumohammed** [golang/go#27252]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
 go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
 go1.11 linux/amd64 (ubuntu)

### What did you do?
i tried running the wasm example here https://github.com/golang/go/wiki/WebAssembly 

### What did you expect to see?
files generated for both html and js 

### What did you see instead?
files were generated but both had the same code base 

wasm_exec.html
![go1](https://user-images.githubusercontent.com/12893191/44634618-b1014980-a98b-11e8-81e7-879885ef95a8.png)

wasm_exec.js
![go2](https://user-images.githubusercontent.com/12893191/44634647-ee65d700-a98b-11e8-95f7-c45f1da2c3ba.png)

**Comment by bradfitz** [comment]
> > **What did you see instead?**
>
> files were generated but both had the same code base

What do you mean files were generated? We don't generate HTML or JS for you.

What did you specifically do?

**Comment by agnivade** [comment]
OP means both wasm_exec.html and wasm_exec.js has the same contents of wasm_exec.html.

@sumohammed - You have to copy the wasm_exec.html and wasm_exec.js from `$GOROOT/misc/wasm/` folder. The `cp $(go env GOROOT)/misc/wasm/wasm_exec.{html,js} .` command does that.

It looks like you have made some mistake in copying the files.

**Comment by sumohammed** [comment]
@bradfitz all i did was run this command 
GOARCH=wasm GOOS=js go build -o test.wasm main.go 

@agnivade i thought i did a mistake at first but after running the command several times then i went into this directory (/misc/wasm/) to see the files i was copying but the contents were still the same even in the directory (/misc/wasm/)

**Comment by bradfitz** [comment]
@sumohammed, "go build" does not generate the HTML or JS files, so you must've done something else to get those into your directory.

**Comment by sumohammed** [comment]
@bradfitz so what does this do ( GOARCH=wasm GOOS=js go build -o test.wasm main.go ) because  apparently thats whats in your tutorial ( https://github.com/golang/go/wiki/WebAssembly ). And i all i did was removed my previous go version and replace it with the latest version which is (go1.11) just to try the webassembly tutorial

**Comment by bradfitz** [comment]
That line generates the output file ("-o") test.wasm.

Let's move this to https://golang.org/wiki/Questions.
