### ISSUE TITLE
cmd/compile: internal compiler error: name too long

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#27256]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.11, darwin/amd64

### What did you do?

https://play.golang.org/p/WNDetHOIGt3

```
$ cat x.go
package tmp

type Q interface {
	Foo()
	Bar()
	Baz()
}

type B interface {
	B() Q
}

type O interface {
	O() interface {
		O
		B
		Q
	}
}

type W interface {
	W() interface {
		O
		B
		Q
	}
}

type S interface {
	S() interface {
		S
		W
		Q
	}
}
```

```
# _/tmp
<autogenerated>:1: internal compiler error: name too long: *interface { Bar(); Baz(); Foo(); S() interface { Bar(); Baz(); Foo(); S() interface { Bar(); Baz(); 
[ ... ]
Baz(); Foo(); O() interface { B() tmp.Q; Bar(); Baz(); Foo(); O() interface { B() tmp.Q; Bar(); Baz(); Foo(); O() interface { B<...>; Bar<...>; Baz<...>; Foo<...>; O<...> } } } } } } } } 
[ ... ]

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

If you remove `S`, it compiles just fine.

Related, if only tangentially, to https://github.com/golang/go/issues/26863.

**Comment by elagergren-spideroak** [comment]
Doesn't seem to be a regression from 1.10.3 or 1.9.7

**Comment by josharian** [comment]
@griesemer @mdempsky

**Comment by griesemer** [comment]
A typical case of infinite interface expansion when creating the type name during object file generation. Not related to exports. Related to #26863 only insofar that in both cases an recursive algorithm stack-overflows (but the code is completely unrelated).

**Comment by griesemer** [comment]
@mdempsky Added you only in case you feel so inclined.

**Comment by griesemer** [comment]
Too late for 1.12.

**Comment by elagergren-spideroak** [comment]
FYI, the original (proprietary) code that triggered this problem _can't_ be reproduced on 1.11.5, but the code in the playground link _can_.

**Comment by yagotome** [comment]
Is there any update on this issue? I'm facing the same error for large nested struct types definition on `go version go1.14.2 linux/amd64`.

**Comment by mdempsky** [comment]
No updates other than what's been commented here. Anonymous, cyclic interfaces continue to be troublesome.

**Comment by randall77** [comment]
This might have been fixed with CL 214239.
I believe that CL made it into 1.14. 1.14 fixes the OP's example for me.

**Comment by mdempsky** [comment]
@randall77 Thanks, I missed that CL.

**Comment by griesemer** [comment]
This appears to be working fine with Go 1.18 ([adjusted test](https://go.dev/play/p/lyOJUAGRvgj)). Closing.
