### ISSUE TITLE
Global Prepared Statement not recognized as used.

### ISSUE THREAD

**Issue by deef0000dragon1** [golang/go#27263]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\koehlerjj\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\koehlerjj\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\koehlerjj\Desktop\workspace\golang-workspace\src\StreamState\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\KOEHLE~1\AppData\Local\Temp\go-build032737686=/tmp/go-build -gno-record-gcc-switches

### What did you do?
Used a global Prepared statement. 

### What did you expect to see?

When using an sql prepared statement that is stored externally so that the statement is only prepared once but can be executed multiple times, the code
```
externalStatement, err := db.Prepare("text")
if err != nil{
fmt.Printf("error")
}
```
results in externalStatement not being recognized as used. (both linter and go build)

however, 
```prep, err := db.Prepare("text")
externalStatement = prep
if err != nil{
fmt.Printf("error")
}
```
 does compile, as does
```
prep, _= db.Prepare("text")
externalStatement = prep
if err != nil{
fmt.Printf("error")
}
```
playground link
https://play.golang.org/p/3m7a3F5s0SF

**Comment by dominikh** [comment]
Working as intended; your use of `:=` in the if body is shadowing the global variable.
