### ISSUE TITLE
Race detector tests fail on netbsd-amd64

### ISSUE THREAD

**Issue by bsiegert** [golang/go#27268]
The netbsd-amd64 builder currently fails every build because the `exitcode` test case in the Race detector tests is failing.

A representative log is at https://build.golang.org/log/ccd6b1b37fe12e4ec1399381b8b83e0d391b6a23; the interesting part is this:

```
##### Testing race detector
--- FAIL: TestOutput (12.61s)
    output_test.go:76: failed test case exitcode, expect:
        exit status 13
        got:
        ==================
        WARNING: DATA RACE
        Write at 0x00c0000160e8 by goroutine 5:
          main.main.func1()
              /tmp/go-build795352810/main.go:7 +0x38
        
        Previous write at 0x00c0000160e8 by main goroutine:
          main.main()
              /tmp/go-build795352810/main.go:10 +0xb5
        
        Goroutine 5 (running) created at:
          main.main()
              /tmp/go-build795352810/main.go:6 +0xa7
        ==================
        Found 1 data race(s)
        exit status 66
FAIL
FAIL	runtime/race	12.621s
2018/08/26 22:06:36 Failed: exit status 1
```

/cc @krytarowski

**Comment by krytarowski** [comment]
Is this something new? We were passing of 98% race tests, but we have not enabled them in the tests.

I propose to keep it disabled.

I'm working now on improving the C and C++ runtime of sanitizers on NetBSD.

**Comment by bsiegert** [comment]
Looks like 7e64377903b3abd922150e35601e0df597a8af9f added netbsd to the list of supported architectures. Are you proposing we remove it from there, so as not to run the race detector tests in a normal build?

**Comment by krytarowski** [comment]
I propose to not run the race detector tests in a normal build. There was already a meta ticket for TSan/NetBSD in this repo.

**Comment by bsiegert** [comment]
See #26403 for the umbrella bug.

I don't think it is a regression, it's just that the change above makes the race detector test run as part of `all.bash`. The failure can be reproduced by running

```
go test -race runtime/race
```
