### ISSUE TITLE
cmd/go: go1.11 does not work on Alpine Linux

### ISSUE THREAD

**Issue by michilu** [golang/go#27264]
### What version of Go are you using (`go version`)?

go version go1.11 linux/amd64
(This is my handprint, the reason is below.)

### Does this issue reproduce with the latest release?

Yes. Installed by `go get golang.org/dl/go1.11`.

### What operating system and processor architecture are you using (`go env`)?

`go1.11`: It was silently done with status 1.
`go1.10.3`:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build312539232=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```console
docker run --rm -it --cap-add sys_ptrace golang:1.10.3-alpine3.8
```
Then in the Docker container:
```console
apk add --update git strace
go get -v golang.org/dl/go1.11 && go1.11 download
...
```

### What did you expect to see?

```console
go1.11 version
go version go1.11 linux/amd64
```

### What did you see instead?

```console
go1.11 version
echo $?
1
```
It was silently done with status 1.

---

I submit the results of `strace go1.11 version`.

- `go1.11`: https://gist.github.com/michilu/131116bf3cd43abc5fe14256b3fc178d#file-strace-go1-11-txt
- `go1.10.3`: https://gist.github.com/michilu/131116bf3cd43abc5fe14256b3fc178d#file-strace-go1-10-3-txt

**Comment by michilu** [comment]
I seem to like the `futex` call is never return.
```
futex(0x810448, FUTEX_WAIT, 0, NULL)    = 0
```
This line: https://gist.github.com/michilu/131116bf3cd43abc5fe14256b3fc178d#file-strace-go1-11-txt-L170

**Comment by bradfitz** [comment]
The official Go binaries are known to not work on Alpine because we assume glibc. That is #18773 and #19938.

Are you saying that the Go binary from `go get golang.org/dl/go1.10.3` but not from `go get golang.org/dl/go1.11`? Or did you get your go1.10.3 from somewhere else? (e.g. from Alpine apk)

**Comment by michilu** [comment]
The go1.10.3 was already installed from Alpine apk.

OK. I understood Golang needs the glibc for itself.
So could not install by `go get`.

Thanks!
