### ISSUE TITLE
x/dl: go get -u golang.org/dl/... finds two main functions

### ISSUE THREAD

**Issue by elagergren-spideroak** [golang/go#27262]
### What did you do?

`go get -u golang.org/dl/...`

### What did you see instead?

```
$ go get -u golang.org/dl/...
# golang.org/dl/go1.10
gopath/src/golang.org/dl/go1.10/main.go:22:6: main redeclared in this block
	previous declaration at gopath/src/golang.org/dl/go1.10/go1.10.go:22:6
```

https://go.googlesource.com/dl/+/master/go1.10/ indicates there's both a `main.go` and `go1.10.go`, both of which contain (nearly) the same content. No other `dl/` packages have a `go1.xx.go` file.

**Comment by agnivade** [comment]
Looks like gopherbot doesn't close issues from dl repos. Closing it since CL has been merged.

**Comment by dmitshur** [comment]
> Looks like gopherbot doesn't close issues from dl repos.

For posterity, it does now, because #26949 is resolved.
