### ISSUE TITLE
Wrong size when mixing uint32 and uint64 in a struct

### ISSUE THREAD

**Issue by solosrbija** [golang/go#27270]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sodsman/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sodsman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build575482715=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Link : https://play.golang.org/p/pcHhNsI8K1p

```
package main

import (
        "fmt"
        "reflect"
)

type T struct {
        f1 uint32
        f2 uint64
}

var b T

func main() {
        t := reflect.TypeOf(b)
        fmt.Printf("Sizeof(T) = %d Byte\n", t.Size())
}
```

### What did you expect to see?
12

### What did you see instead?
16

**Comment by dolmen** [comment]
Alignment of `uint64` is `8` on play.golang.org (https://play.golang.org/p/HbnSlLbhlmo), so padding is required between the `uint32` and `uint64` fields.
See https://go101.org/article/memory-layout.html

**Comment by dominikh** [comment]
Alignment is indeed a thing, and this is working as intended.

**Comment by solosrbija** [comment]
Thank you for clarifying.
