### ISSUE TITLE
x/tools/godoc: copying source code in Firefox adds two newlines between lines

### ISSUE THREAD

**Issue by kevinburke** [golang/go#27291]
If I open Firefox copy text from eg. https://golang.org/src/encoding/csv/reader.go?s=3304:5704#L96 (any code page will work), the text gets pasted with a beginning newline and two newlines in between lines, like this:

```

func (e *ParseError) Error() string {

	if e.Err == ErrFieldCount {

		return fmt.Sprintf("record on line %d: %v", e.Line, e.Err)

	}
```

I can reproduce with `godoc` tip. I cannot reproduce in Chrome. I am running the latest Firefox on a new-ish Mac.

I would appreciate if people could comment if they can reproduce with Firefox on Windows or a Linux machine.

I may post this to https://github.com/webcompat/web-bugs as well since the behavior is different between Chrome and Firefox.

**Comment by agnivade** [comment]
Reproduced on FF(60.0.2)+Linux.

**Comment by kevinburke** [comment]
Tracking bug, it's an issue in the browser it seems. https://bugzilla.mozilla.org/show_bug.cgi?id=1273836

**Comment by ALTree** [comment]
It seems to me that this issue is caused by a Firefox bug, and it's thus not really actionable on the Go side. For this reason, I think we can close here (usually we only keep open issues that are actually actionable); but feel free to comment if you disagree.
