### ISSUE TITLE
os/exec: TestExitCode failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#27294]
CL [125443](https://golang.org/cl/125443) added TestExitCode. However, this test is failing on Plan 9, because Plan 9 programs return a string and not an exit code.

```
--- FAIL: TestExitCode (0.05s)
    exec_test.go:178: ExitCode got 1, want 42
    exec_test.go:186: ExitCode got 1, want 2
    exec_test.go:194: ExitCode got 1, want 255
FAIL
FAIL	os/exec	1.426s
```

See https://build.golang.org/log/8411cb50158709f843f78d9c6634bf005b6dc1fb

**Comment by fhs** [comment]
It should just accept those results on Plan 9. It doesn't seem worth it to parse the int out. Even then, `exit "0"` would be a special case.
