### ISSUE TITLE
bufio.NewWriter() is not checking the file mode

### ISSUE THREAD

**Issue by riccardo1991** [golang/go#27305]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
I was writing into a writer, no errors and even got the number of byte written, but the file was not updated.
I discovered later I didn't have the permission to write: the file pointer was coming from a os.Open, and not from a os.OpenFile with the RW permission.

```
	file, fileErr := os.Open(path.Join(usrFolder, fileName))
	if fileErr != nil {
		logger.Error("Error opening the file " + fileName)
	}

	defer func() {
		if err := file.Close(); err != nil {
			logger.Error("Error closing the file " + fileName)
		}
	}()

	fileWriter := bufio.NewWriter(file)

	bw, writeErr := fileWriter.WriteString(fileContent)
	if writeErr != nil {
		logger.Error("Error writing the file " + fileName)
	}

	logger.Debug("Byte written: " + strconv.Itoa(bw))
	fileWriter.Flush()
```

Could be a good idea check to have the write permission inside NewWriter(w io.Writer), so inside NewWriterSize(w io.Writer, size int)?

**Comment by davecheney** [comment]
I don’t think this is a bug. In the error check after you open the file you must return from the function, logging the error and then continuing is not appropriate because `file` is not valid at that point.

**Comment by riccardo1991** [comment]
I have a return (after all the three logger.Error), I have omitted here to make the code more readable. Anyway I am not going inside that error check .

**Comment by dominikh** [comment]
You're also ignoring the error returned by Flush, which will likely be the first time Go actually attempts writing to the file.

Either way, bufio works with generic io.Writers, it doesn't know anything about files, and it shouldn't have to.

**Comment by riccardo1991** [comment]
Yes, my mistake was ignoring the error from Flush, in fact now I checked and it's complaining `bad file descriptor`.
