### ISSUE TITLE
os: invalid tmp dir for GOARCH=wasm, GOOS=js when GOHOSTOS=windows 

### ISSUE THREAD

**Issue by thesyncim** [golang/go#27306]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
https://play.golang.org/p/e5sTf5-QdnM
//steps to reproduce  (GOHOSTOS= windows)
set GOOS=js
set GOARCH=wasm
set CGO_ENABLED=0
go test -c -o test.wasm
node wasm_exec.js test.wasm
#### What did you expect to see?
test succeed 

#### What did you see instead?
--- FAIL: TestTmpFileGOARCH_wasm_GOHOSTOS_windows (0.00s)
    issue_test.go:27: open /tmp/wasm514931654: No such file or directory

#### Does this issue reproduce with the latest release (go1.11)?
yes

#### System details

```
go version devel +76c45877c9 Tue Aug 28 09:26:45 2018 +0000 windows/amd64
GOARCH="wasm"
GOBIN=""
GOCACHE="C:\Users\thesyncim\AppData\Local\go-build"
GOEXE=".exe"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="js"
GOPATH="C:\Users\thesyncim\go"
GOPROXY=""
GORACE=""
GOROOT="C:\Go"
GOTMPDIR=""
GOTOOLDIR="C:\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +76c45877c9 Tue Aug 28 09:26:45 2018 +0000 windows/amd64
GOROOT/bin/go tool compile -V: compile version devel +76c45877c9 Tue Aug 28 09:26:45 2018 +0000
gdb --version: GNU gdb (GDB) 7.9.1
```

possible solution 

```
diff --git a/src/os/file_unix.go b/src/os/file_unix.go
index cb90b70735..4c2a6e3792 100644
--- a/src/os/file_unix.go
+++ b/src/os/file_unix.go
@@ -11,6 +11,7 @@ import (
        "internal/syscall/unix"
        "runtime"
        "syscall"
+       "syscall/js"
 )

 // fixLongPath is a noop on non-Windows platforms.
@@ -330,11 +331,15 @@ func Remove(name string) error {
 func tempDir() string {
        dir := Getenv("TMPDIR")
        if dir == "" {
-               if runtime.GOOS == "android" {
+               switch runtime.GOOS {
+               case "android":
                        dir = "/data/local/tmp"
-               } else {
+               case "js":
+                       dir = js.Global().Get("require").Invoke("os").Call("tmpdir").String()
+               default:
                        dir = "/tmp"
                }
+
        }
        return dir
 }
```

**Comment by thesyncim** [comment]
also the os path separator should reflect GOHOSTOS value

**Comment by thesyncim** [comment]
@neelance

**Comment by bradfitz** [comment]
Does this only affect running tests?

If so, one answer is that we're fine with the Linux-based builders only.

As long as Windows users can still generate working *.wasm files that run in browsers, we might be fine without tests.

But then again, the fix might also be simple enough. It might not be okay for the os package to depend on syscall/js, though.

**Comment by thesyncim** [comment]
no,

Let me give you some context:

I'm currently working on a "bridge" between go http handlers and nodejs request listeners.

This allow us to use regular [http Handlers](https://golang.org/pkg/net/http/#Handler) as node [requestListener](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener),
it can be useful to extend old js services with new functionalities written 100% in go.
I know that browsers represent 99% of wasm use case, but it would be nice to have nodejs support for writing files using os tmpdir.


yes, this is probably a bad idea but is fun and powerful

**Comment by neelance** [comment]
@thesyncim What about modifying `wasm_exec.js` so it sets `TMPDIR` to `require("os").tmpdir()` if running with Node.js and `TMPDIR` is not already set? Would you mind creating a CL for it?

**Comment by neelance** [comment]
@thesyncim If you need any help with the setup for sending a CL, feel free to talk to me on the Gophers slack. Alternatively you could use the pull request integration: https://golang.org/doc/contribute.html#sending_a_change_github

**Comment by ali2210** [comment]
![Capture](https://user-images.githubusercontent.com/20568079/65820422-12a47f00-e242-11e9-86f4-97d96c41b13c.JPG)
When I run env command at my command prompt
It show me GOOS="linux" GOARCH="amd64" How to execute wasm
