### ISSUE TITLE
golang script suddenly crashing, need help to verify code and add recovery

### ISSUE THREAD

**Issue by mrcg** [golang/go#27304]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Raspbian v9.4 Stretch

### What did you do?
I am trying to find solution for system crash which is caused in github code ("status.go" file) for the following project:
https://github.com/mcuadros/OctoPrint-TFT/blob/master/ui/status.go

**Issue is repored here:**
https://github.com/mcuadros/OctoPrint-TFT/issues/34

### What did you expect to see?
a) VERIFY GOLANG Code
I need golang expert to verify if there is any wrong code in this lines which are causing spradic crashed to the system. Without this function the issue is not happening.

```
func (m *statusPanel) updateTemperature() {
	s, err := (&octoprint.StateRequest{Exclude: []string{"sd"}}).Do(m.UI.Printer)
	if err != nil {
		Logger.Error(err)
		return
	}

	m.doUpdateState(&s.State)

	m.tool1.Hide()
	for tool, s := range s.Temperature.Current {
		text := fmt.Sprintf("%s: %.0f°C / %.0f°C", strings.Title(tool), s.Actual, s.Target)
		switch tool {
		case "bed":
			m.bed.Label.SetLabel(text)
		case "tool0":
			m.tool0.Label.SetLabel(text)
		case "tool1":
			m.tool1.Label.SetLabel(text)
			m.tool1.Show()
		}
	}
}
```
Is there anything wrong in this code?
Something which could be improved?

b) ADD RECOVERY TO THE CODE
Based on the following webpage i tried to add recovery function:
https://stackoverflow.com/questions/25356602/golang-panic-crash-prevention

But unfortunately this code (i have added " err := recover();") is causing issues when doing the compilation:
`if err := recover(); err != nil {`

### What did you see instead?
System crashing because of above mentioned function (updateTemperature).
Many thanks for any support from golang expert!

**Comment by dominikh** [comment]
Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
