### ISSUE TITLE
wiki: keeping a check on wiki page creation/edits

### ISSUE THREAD

**Issue by mfrw** [golang/go#27313]
All must have noticed in the past few days attempts by people to create a random page on the wiki.
I was wondering if there was a way we could check this.
Although this is not an issue related to the language, I thought of raising it here as all of us can not religiously follow the mailing list.

**Comment by ianlancetaylor** [comment]
Does GitHub provide any way to subscribe to changes in the wiki?

**Comment by ALTree** [comment]
> Does GitHub provide any way to subscribe to changes in the wiki?

AFAIK you can subscribe to the whole repo and you'll get everything that happens (PR, issues and changes on the wiki), but you can't just subscribe to the wiki.

**Comment by ianlancetaylor** [comment]
I "watch" the repo.  Is that how you subscribe?  I get e-mail for every pull request and every issue, but I don't get anything about changes to the wiki.

**Comment by ALTree** [comment]
Yes I was talking about "watch repo". Mmh. Maybe I'm wrong about the wiki emails. I thought you could get emails about everything you see in https://github.com/orgs/golang/dashboard and I see wiki changes there (under "All activity") but if you don't receive emails then maybe that's not true.

**Comment by FiloSottile** [comment]
The wiki is a git repo, so we can run a cron fetching and diffing.

**Comment by crvv** [comment]
The wiki is a git repo, but it doesn't have other features of a normal GitHub repo.
There is a workaround.
https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

Create a new repo, like `github.com/golang/go-wiki` and use pull request to edit.
In `github.com/golang/go`, enable `Restrict editing to collaborators only` in the wiki settings.
And set up a CI(travis-ci in the link) to sync the new repo and `github.com/golang/go.wiki`.

I think this is a good solution.
This can prevent #29738.

**Comment by dmitshur** [comment]
I think we should take a first step of making it possible to subscribe/watch for wiki page creation/edits, before considering adding barriers to wiki page edits.

We currently have a [golang-codereviews](https://groups.google.com/forum/#!forum/golang-codereviews) mailing list where all new CLs and CL comments are copied to. People can use it to subscribe to notifications for CLs.

We can create a similar golang-wikichanges mailing list where new wiki pages and existing page edits are copied. I discussed this idea with @ianlancetaylor and it sounded okay to him. /cc @bradfitz

In addition to the wiki being a git repo, GitHub API v3 has an endpoint to list all events for a repository:

https://developer.github.com/v3/activity/events/#list-repository-events

One of the events is a wiki page creation/edit event:

https://developer.github.com/v3/activity/events/types/#gollumevent

If there are no objections or improvement suggestions, I can look into setting up a service (or add to an existing one) that watches for wiki events and mails a new golang-wikichanges mailing list.

**Comment by bradfitz** [comment]
The wiki is also in git, so we could have our maintnerd config start mirroring the metadata for:

https://github.com/golang/go.wiki.git

Not sure if that helps here, but we should probably do it for the future anyway, as it's cheap, and it's nice to have all the contributions in one place for querying.

**Comment by andybons** [comment]
I have no objections. Am I correct that this would manifest itself as (to start):

**Every wiki page change is emailed to golang-wikichanges@ as a diff** ?

**Comment by dmitshur** [comment]
That's my understanding.

I think it'll be nice if each page is grouped in a email thread. That means using the same email title. Using the page title both for "page created" and "page edited" events should achieve that.

**Comment by andybons** [comment]
I have something up and running sending emails to golang-wikichanges@googlegroups.com. Example email: https://groups.google.com/forum/#!topic/golang-wikichanges/c25X5t0-8b0

**Comment by agnivade** [comment]
@andybons - Looks like the mailing list is up and running. Is there anything pending here ?

**Comment by andybons** [comment]
I don't believe so. Closing.
