### ISSUE TITLE
regression test failed on android

### ISSUE THREAD

**Issue by benshi001** [golang/go#27327]
##### Testing packages.
	ok  	archive/tar	2.402s
	ok  	archive/zip	7.800s
	ok  	bufio	2.313s
	ok  	bytes	4.165s
	ok  	compress/bzip2	2.756s
	ok  	compress/flate	5.625s
	ok  	compress/gzip	2.774s
	ok  	compress/lzw	2.606s
	ok  	compress/zlib	2.077s
	ok  	container/heap	2.062s
	ok  	container/list	1.960s
	ok  	container/ring	1.844s
	ok  	context	2.961s
	ok  	crypto	1.849s
	ok  	crypto/aes	1.967s
	ok  	crypto/cipher	2.028s
	ok  	crypto/des	1.676s
	ok  	crypto/dsa	1.773s
	ok  	crypto/ecdsa	2.769s
	ok  	crypto/elliptic	2.144s
	ok  	crypto/hmac	1.904s
	ok  	crypto/internal/subtle	1.861s
	ok  	crypto/md5	2.080s
	ok  	crypto/rand	2.364s
	ok  	crypto/rc4	2.266s
	ok  	crypto/rsa	3.025s
	ok  	crypto/sha1	1.946s
	ok  	crypto/sha256	2.015s
	ok  	crypto/sha512	2.109s
	ok  	crypto/subtle	1.995s
	ok  	crypto/tls	7.837s
	ok  	crypto/x509	6.723s
	ok  	database/sql	3.016s
	ok  	database/sql/driver	1.705s
	ok  	debug/dwarf	2.007s
	ok  	debug/elf	2.046s
	ok  	debug/gosym	2.182s
	ok  	debug/macho	2.275s
	ok  	debug/pe	2.692s
	ok  	debug/plan9obj	2.068s
	ok  	encoding/ascii85	1.742s
	ok  	encoding/asn1	1.965s
	ok  	encoding/base32	1.907s
	ok  	encoding/base64	1.823s
	ok  	encoding/binary	1.914s
	ok  	encoding/csv	1.846s
	ok  	encoding/gob	2.164s
	ok  	encoding/hex	1.786s
	ok  	encoding/json	5.862s
	ok  	encoding/pem	2.749s
	ok  	encoding/xml	2.693s
	ok  	errors	2.233s
	ok  	expvar	2.965s
	ok  	flag	1.757s
	ok  	fmt	2.122s
	ok  	go/ast	1.874s
	ok  	go/build	4.655s
	ok  	go/constant	1.947s
	ok  	go/doc	2.737s
	ok  	go/format	2.055s
	ok  	go/importer	2.920s
	ok  	go/internal/gccgoimporter	2.272s
	ok  	go/internal/gcimporter	3.311s
	ok  	go/internal/srcimporter	7.095s
	ok  	go/parser	2.236s
	ok  	go/printer	3.274s
	ok  	go/scanner	2.159s
	ok  	go/token	2.207s
	ok  	go/types	4.201s
	ok  	hash	1.777s
	ok  	hash/adler32	2.070s
	ok  	hash/crc32	2.385s
	ok  	hash/crc64	2.483s
	ok  	hash/fnv	1.951s
	ok  	html	1.827s
	ok  	html/template	2.496s
	ok  	image	2.271s
	ok  	image/color	1.960s
	ok  	image/draw	2.346s
	ok  	image/gif	3.690s
	ok  	image/jpeg	2.816s
	ok  	image/png	2.217s
	ok  	index/suffixarray	1.969s
	ok  	internal/cpu	1.751s
	ok  	internal/poll	1.861s
	ok  	internal/singleflight	1.713s
	ok  	internal/trace	6.651s
	ok  	io	1.894s
	ok  	io/ioutil	1.846s
	ok  	log	1.626s
	ok  	log/syslog	3.152s
	ok  	math	1.631s
	ok  	math/big	10.732s
	ok  	math/bits	1.639s
	ok  	math/cmplx	1.721s
	ok  	math/rand	3.514s
	ok  	mime	2.106s
	ok  	mime/multipart	3.755s
	ok  	mime/quotedprintable	2.355s
	ok  	net	8.089s
	ok  	net/http	19.347s
	ok  	net/http/cgi	3.384s
	ok  	net/http/cookiejar	3.518s
	ok  	net/http/fcgi	3.361s
	ok  	net/http/httptest	3.570s
	ok  	net/http/httptrace	3.848s
	ok  	net/http/httputil	3.945s
	ok  	net/http/internal	1.997s
	ok  	net/http/pprof	9.712s
	ok  	net/internal/socktest	3.440s
	ok  	net/mail	3.787s
	ok  	net/rpc	5.961s
	ok  	net/rpc/jsonrpc	5.338s
	ok  	net/smtp	2.514s
	ok  	net/textproto	1.682s
	ok  	net/url	2.023s
	ok  	os	3.662s
	ok  	os/exec	6.355s
	ok  	os/signal	5.436s
	ok  	os/user	1.941s
	ok  	path	1.620s
	ok  	path/filepath	1.942s
	ok  	reflect	5.216s
	ok  	regexp	2.264s
	ok  	regexp/syntax	3.673s
	ok  	runtime	12.196s
	ok  	runtime/debug	1.757s
	ok  	runtime/internal/atomic	2.273s
	ok  	runtime/internal/sys	2.088s
	ok  	runtime/pprof	10.187s
	ok  	runtime/pprof/internal/profile	2.258s
	ok  	runtime/trace	6.896s
	ok  	sort	2.362s
	ok  	strconv	3.437s
	ok  	strings	2.960s
	ok  	sync	2.839s
	ok  	sync/atomic	1.729s
	go_android_exec: adb shell mkdir -p /data/local/tmp/syscall.test-21958
	go_android_exec: adb push /tmp/go-build217432634/b979/syscall.test /data/local/tmp/syscall.test-21958/syscall.test-21958-tmp
	2116 KB/s (2839029 bytes in 1.310s)
	go_android_exec: adb shell cp '/data/local/tmp/syscall.test-21958/syscall.test-21958-tmp' '/data/local/tmp/syscall.test-21958/syscall.test-21958'
	go_android_exec: adb shell rm '/data/local/tmp/syscall.test-21958/syscall.test-21958-tmp'
	go_android_exec: adb shell export TMPDIR="/data/local/tmp/syscall.test-21958"; export GOROOT="/data/local/tmp/goroot"; export GOPATH="/data/local/tmp/gopath"; cd "/data/local/tmp/goroot/src/syscall"; '/data/local/tmp/syscall.test-21958/syscall.test-21958' -test.short=true -test.timeout=18m0s; echo -n exitcode=$?
	--- FAIL: TestAmbientCaps (0.00s)
	    exec_linux_test.go:543: user: Lookup not implemented on android
	--- FAIL: TestSyscallNoError (0.11s)
	    syscall_linux_test.go:358: expected 4294967295 / 2 / 4294967294, got 0 / 0 / 0
	FAIL
	exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/syscall.test-21958
	FAIL	syscall	3.058s
	ok  	testing	3.173s
	ok  	testing/quick	2.604s
	ok  	text/scanner	1.941s
	ok  	text/tabwriter	1.687s
	ok  	text/template	2.998s
	ok  	text/template/parse	1.845s
	ok  	time	5.861s
	ok  	unicode	1.873s
	ok  	unicode/utf16	1.796s
	ok  	unicode/utf8	1.624s
	ok  	vendor/golang_org/x/crypto/chacha20poly1305	3.178s
	ok  	vendor/golang_org/x/crypto/cryptobyte	1.793s
	ok  	vendor/golang_org/x/crypto/curve25519	2.307s
	ok  	vendor/golang_org/x/crypto/internal/chacha20	2.002s
	ok  	vendor/golang_org/x/crypto/poly1305	1.757s
	ok  	vendor/golang_org/x/net/dns/dnsmessage	2.103s
	ok  	vendor/golang_org/x/net/http/httpguts	1.760s
	ok  	vendor/golang_org/x/net/http/httpproxy	1.987s
	ok  	vendor/golang_org/x/net/http2/hpack	2.032s
	ok  	vendor/golang_org/x/net/idna	1.847s
	ok  	vendor/golang_org/x/net/nettest	3.649s
	ok  	vendor/golang_org/x/text/transform	1.776s
	ok  	vendor/golang_org/x/text/unicode/norm	1.926s
	ok  	cmd/addr2line	2.406s
	ok  	cmd/api	2.674s
	ok  	cmd/asm/internal/asm	5.421s
	ok  	cmd/asm/internal/lex	1.720s
	ok  	cmd/compile	4.311s
	ok  	cmd/compile/internal/gc	4.988s
	ok  	cmd/compile/internal/ssa	8.441s
	ok  	cmd/compile/internal/syntax	1.911s
	ok  	cmd/compile/internal/test	1.669s [no tests to run]
	ok  	cmd/compile/internal/types	1.686s
	ok  	cmd/cover	2.189s
	ok  	cmd/doc	2.338s
	ok  	cmd/fix	2.473s
	ok  	cmd/go	5.650s
	ok  	cmd/go/internal/cache	4.284s
	ok  	cmd/go/internal/dirhash	1.833s
	ok  	cmd/go/internal/generate	5.565s
	ok  	cmd/go/internal/get	5.108s
	ok  	cmd/go/internal/imports	2.690s
	ok  	cmd/go/internal/load	2.370s
	ok  	cmd/go/internal/modconv	5.299s
	ok  	cmd/go/internal/modfetch	5.205s
	ok  	cmd/go/internal/modfetch/codehost	2.929s
	ok  	cmd/go/internal/modfile	2.257s
	ok  	cmd/go/internal/modload	5.070s
	ok  	cmd/go/internal/module	1.880s
	ok  	cmd/go/internal/mvs	2.275s
	ok  	cmd/go/internal/par	1.945s
	ok  	cmd/go/internal/search	2.389s
	ok  	cmd/go/internal/semver	1.858s
	ok  	cmd/go/internal/txtar	1.776s
	ok  	cmd/go/internal/web2	3.913s
	ok  	cmd/go/internal/work	3.426s
	ok  	cmd/gofmt	2.328s
	ok  	cmd/internal/buildid	3.482s
	ok  	cmd/internal/dwarf	1.792s
	ok  	cmd/internal/edit	1.613s
	ok  	cmd/internal/goobj	1.785s
	ok  	cmd/internal/obj	1.676s
	ok  	cmd/internal/obj/arm64	1.945s
	ok  	cmd/internal/obj/x86	1.926s
	ok  	cmd/internal/objabi	1.697s
	ok  	cmd/internal/src	1.853s
	ok  	cmd/internal/test2json	2.398s
	ok  	cmd/link	2.427s
	ok  	cmd/link/internal/ld	2.644s
	ok  	cmd/link/internal/sym	1.666s
	ok  	cmd/nm	2.985s
	ok  	cmd/objdump	3.050s
	ok  	cmd/pack	2.252s
	ok  	cmd/trace	4.562s
	ok  	cmd/vendor/github.com/google/pprof/internal/binutils	3.629s
	ok  	cmd/vendor/github.com/google/pprof/internal/driver	6.644s
	ok  	cmd/vendor/github.com/google/pprof/internal/elfexec	1.973s
	ok  	cmd/vendor/github.com/google/pprof/internal/graph	1.899s
	ok  	cmd/vendor/github.com/google/pprof/internal/measurement	1.692s
	ok  	cmd/vendor/github.com/google/pprof/internal/report	4.457s
	ok  	cmd/vendor/github.com/google/pprof/internal/symbolizer	3.566s
	ok  	cmd/vendor/github.com/google/pprof/internal/symbolz	3.293s
	ok  	cmd/vendor/github.com/google/pprof/profile	2.373s
	ok  	cmd/vendor/github.com/ianlancetaylor/demangle	2.121s
	ok  	cmd/vendor/golang.org/x/arch/arm/armasm	2.094s
	ok  	cmd/vendor/golang.org/x/arch/arm64/arm64asm	2.685s
	ok  	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	1.879s
	ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	2.526s
	ok  	cmd/vendor/golang.org/x/crypto/ssh/terminal	1.780s
	ok  	cmd/vendor/golang.org/x/sys/unix	2.718s
	ok  	cmd/vet	3.186s
	ok  	cmd/vet/internal/cfg	1.925s
	2018/08/29 10:35:55 Failed: exit status 1

**Comment by cherrymui** [comment]
Could you share the exact command you run? On which architecture?

I think you probably should run androidtest.bash instead of all.bash.

**Comment by benshi001** [comment]
CC_FOR_TARGET=~/android/ndk-standalone-r17b/aarch64/bin/clang GOARCH=arm64 ./androidtest.bash
