### ISSUE TITLE
x/tools/cmd/godoc: some line-heights became less readable

### ISSUE THREAD

**Issue by beaubrueggemann** [golang/go#27321]
[https://go-review.googlesource.com/c/tools/+/94935](https://go-review.googlesource.com/c/tools/+/94935) changed some line-height values in godoc/static/style.css, dropping the em unit specifier.

It appears these line-height changes weren't meant to have any visible changes.  The reasoning in the CL states:
> If the line-height is specified in em, you can just drop the em (it's the default unit for line-height). So here "line-height: 1.4;" would be the right thing.

But em is not the default unit for line-height (see [https://developer.mozilla.org/en-US/docs/Web/CSS/line-height](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)).

On my system (Arch Linux,  Firefox), this results in visible changes.  As an example, here are 2 screenshots.  First, we have the original em behavior (taken from the index for package fmt):
![original](https://user-images.githubusercontent.com/1686655/44753230-fd12d200-aae2-11e8-8e45-fd6e3e4952a8.png)

And here is the newer behavior following the removal of the ems:
![harder-to-read](https://user-images.githubusercontent.com/1686655/44753364-64308680-aae3-11e8-8dd4-a1299fa64b80.png)

The computed line-height went from 20.8px to 18.2px.

I find the original em version to be more readable.  Since it looks like this visible change was inadvertent, could we add the em units back to lines 5 and 15?

**Comment by jimmyfrasche** [comment]
This is my fault. I gave @agnivade bad advice because I confidently mis-remembered how line-heights work and didn't notice the visual difference. Sorry!

**Comment by agnivade** [comment]
Right, there is indeed a difference. Good catch.

The MDN docs do recommend the line-height to be unitless however. https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values.

Perhaps, we can re-calculate the required line-height, and give a slightly higher number and still keep it unitless ?
