### ISSUE TITLE
tour: error in functions tutorial (hebrew)

### ISSUE THREAD

**Issue by bshlomo** [golang/go#27325]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Don't know
I am here
https://go-tour-he.appspot.com/#8

### What did you do?
Learning the lang

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
פונקציות מקבלות משתנים.

### What did you see instead?
פונקציות מקבלות משתים.

**Comment by meirf** [comment]
I agree this needs a fix, but these translations appear to be entirely maintained outside of any official go repo.
See https://github.com/golang/tour/blob/master/TRANSLATE

In terms of fixing, I think the maintainer of the tour would have to make the change.
@adg, do you have results from [this](https://github.com/golang/go/issues/15693#issuecomment-219849430) anywhere or at least hebrew version?

**Comment by adg** [comment]
@meirf nope I have no idea who maintains it because any correspondence I had with its maintainer has disappeared from my mailbox.
