### ISSUE TITLE
go/build: document when Context.BuildTags is used/populated

### ISSUE THREAD

**Issue by bradfitz** [golang/go#27320]
Context.BuildTags is not set when you read go/build.Default.BuildTags.

It's only used by (*BuildTags).Import, etc.

Document that.

**Comment by mfrw** [comment]
Can I take a shot on this

**Comment by ianlancetaylor** [comment]
But why would you expect `BuildTags` to be set?  Note that `BuildTags` is not `ReleaseTags`.

**Comment by ianlancetaylor** [comment]
I see.  The go/build package is about building other packages.  It doesn't tell you anything about your own program.  Even `go/build.DefaultContext` is populated from `GOARCH` and `GOOS` in the environment (though naturally the default is the values used to build your program).

**Comment by bradfitz** [comment]
> The go/build package is about building other packages. It doesn't tell you anything about your own program.

It kinda does, though, in that people use ReleaseTags to see which version of Go it was built with.
