### ISSUE TITLE
Section markup missing for gofmt in https://golang.org/cmd/go/

### ISSUE THREAD

**Issue by porridge** [golang/go#27334]
### What did you do?

1. Go to https://golang.org/cmd/go/#hdr-Update_packages_to_use_new_APIs
1. Scroll down a little bit

### What did you expect to see?

`Gofmt (reformat) package sources` to be formatted as a section heading

### What did you see instead?

It's just regular text, see attached screenshot.
![gofmt](https://user-images.githubusercontent.com/489420/44772558-7c011c80-ab6e-11e8-892e-b1d6c8380c26.png)

**Comment by agnivade** [comment]
Fixed at tip https://tip.golang.org/cmd/go/#hdr-Update_packages_to_use_new_APIs.

So it should be when #27205 is fixed.
