### ISSUE TITLE
[RFC] go2 error handling best reference

### ISSUE THREAD

**Issue by netroby** [golang/go#27330]
I read the https://github.com/golang/proposal/blob/master/design/go2draft-error-handling.md
The new go2 error handling design paper.
Sorry for create this issue, ( i can not find any place to submit my thought and worry about the doc)

This issue is to talk my thought about the go2 error handler.

The go2draft error handling design a ugly error handle proccess way.

I can not agree with the design.

And I would like to suggest some good error handling 

1. C# [https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/)
2. F# [https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/exception-handling/](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/exception-handling/)

these two exception handling design , provided us a clean interface, and easy to deal , easy to track problems.

the Go2Draf handler Check seems too complicated and not well structed

And here some other article talk about exception handler, very well document .

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions

https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

    Exception handling has many advantages over return-value-based error reporting. 
    Good framework design helps the application developer realize the benefits of exceptions. 
    This section discusses the benefits of exceptions and presents guidelines for using them effectively.

    A well-designed app handles exceptions and errors to prevent app crashes.

**Comment by ianlancetaylor** [comment]
Discussion about the error handling design is welcome.  But it would help quite a bit if you could be more specific.  What exactly is ugly?  What exactly do you not agree with?

Referring to exception handling is a non-starter.  We are not going to implement C# style exception handling in Go, for the reasons explained at https://go.googlesource.com/proposal/+/master/design/go2draft-error-handling-overview.md .  While alternative suggestions are welcomed, a general pointer to other languages that use exceptions is not going to be adopted.  Sorry.

**Comment by netroby** [comment]
The handler and check not match , you have to write a lot check , check check, and define lot's of handler.
This stupid idea.

for Exception handler,
you can 
```
Try {

} catch (NullPointException e) {
  //TODO: handler Null Point errors
 } catch (OverflowException e) {
  //TODO handler Overflow errors
}
```


Very clean and tidy.

did you see it ?

**Comment by netroby** [comment]
Your check and handler was nosense. Check what ? handler what?
nothing to know, no problem resolved. you just make things worse and worse

**Comment by agnivade** [comment]
> ( i can not find any place to submit my thought and worry about the doc)

This is the place - https://github.com/golang/go/wiki/Go2ErrorHandlingFeedback.

Please feel free to outline all your thoughts in a post,gist,google doc and add a link in the wiki. It looks like you have more of a feedback, rather than a concrete proposal. So I will close the issue and request you to use the wiki page.

Thank you.
