### ISSUE TITLE
x/net: slow streaming with http2 due to MaxConcurrentStreams

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#27338]
The k8s go client doesn't behave well since the change in https://github.com/golang/net/commit/1c05540f6879653db88113bc4a2b70aec4bd491f

What happens is that when the client hits the MaxConcurrentStreams of the server any updates after that take very long time (1-2 minutes) so on k8s clusters with constant changes the client can never catch up. 
The fix in that commit seems valid, but shouldn't the retry interval can be configurable or provide an option to open a new connection like with the old behaviour.

More on the issue: https://github.com/kubernetes/client-go/issues/456

go version go1.11 linux/amd64

**Comment by krasi-georgiev** [comment]
cc @tombergan

**Comment by krasi-georgiev** [comment]
I will try to make a reproducible  test, but in the meanwhile some initial input would be useful.

**Comment by meirf** [comment]
This looks like a dup of https://github.com/golang/go/issues/27044 so I'm closing, but tagging @bradfitz due to the urgency that usually comes with k8s issues.
