### ISSUE TITLE
go/types: assertion failure setting up composite literal with incomplete element type

### ISSUE THREAD

**Issue by griesemer** [golang/go#27346]
This the std lib issue for https://github.com/golang/lint/issues/411 . Small reproducer by @randall77:
```Go
package main

var x = [][n]int{
	0: {},
}
```

Issue: Checker.recordTypeAndValue called with nil argument. Need to determine where best to guard against this.

**Comment by FiloSottile** [comment]
@gopherbot please file this for backport against 1.11. This is a regression.
