### ISSUE TITLE
cmd/go: `go help build` mentions -mod=release, which is not supported

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#27354]
Using go 1.11.

```
$ go help build | grep -A2 -- -mod
	-mod mode
		module download mode to use: readonly, release, or vendor.
		See 'go help modules' for more.

$ go test -mod=release
-mod=release not supported (can be '', 'readonly', or 'vendor')

$ go build -mod=release
-mod=release not supported (can be '', 'readonly', or 'vendor')
```

**Comment by mark-rushakoff** [comment]
@gopherbot please add labels documentation, modules

**Comment by FiloSottile** [comment]
@gopherbot please file this to be considered for backport to 1.11, as a modules doc bug.

@mark-rushakoff please [make a cherry-pick CL](https://github.com/golang/go/wiki/MinorReleases#making-cherry-pick-cls) once your change is merged in master.
