### ISSUE TITLE
net: testSpliceReaderAtEOF closed connection: got err = splice: invalid argument

### ISSUE THREAD

**Issue by mikesmitty** [golang/go#27355]
When running tests against the new splice code in the net package from 1.11 the syscall appears to be returning an error on CentOS 6.

### What version of Go are you using (`go version`)?
`go version go1.11 linux/amd64`

### Does this issue reproduce with the latest release?
Yes, it appears to have been introduced with 1.11

### What operating system and processor architecture are you using (`go env`)?
The error appears to only occur on CentOS 6 with the standard 2.6.32 kernel. The test passed successfully in a CentOS 6 chroot under a CentOS 7 kernel however, so it seems like it may be related to the older kernel. Also passed on a variety of newer CentOS/Fedora distros without issue.

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mockbuild/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build794142517=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
`./run.bash --no-rebuild -v -v -v -k`

### What did you expect to see?
All tests pass successfully

### What did you see instead?
```
--- FAIL: TestSplice (0.02s)
    --- FAIL: TestSplice/readerAtEOF (0.00s)
        splice_test.go:228: closed connection: got err = splice: invalid argument, handled = false, want handled = true
FAIL
FAIL	net	2.046s
```

**Comment by acln0** [comment]
I'm a little confused. Does 92bdfab795a1245d8b81a6e841d5e5aa52f3a790 not handle this correctly by disabling splice on old kernels, or am I reading that commit incorrectly? I don't understand if 2.6.29 or 2.6.35 is the cut-off.

Perhaps @benburkert could clarify?

**Comment by joenall** [comment]
I am seeing the same issue.

**Comment by acln0** [comment]
I'm currently investigating on CentOS 6, and I can reproduce the issue.

When I run the `readerAtEOF` test cold, I get `closed connection: got err = fcntl: invalid argument, handled = false, want handled = true`. If I run other tests before it, I get `closed connection: got err = splice: invalid argument, handled = false, want handled = true` as originally reported.

I'll continue investigating.
