### ISSUE TITLE
x/sync/semaphore: newWeighted why n is int64

### ISSUE THREAD

**Issue by Sherlock-Holo** [golang/go#27363]
Please answer these questions before submitting your issue. Thanks!
https://github.com/golang/sync/blob/master/semaphore/semaphore.go#L25

### What version of Go are you using (`go version`)?
1.10.4

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/sherlock/.cache/go-build"
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/sherlock/go"
> GORACE=""
> GOROOT="/usr/lib/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build083961696=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

use `semaphore.NewWeighted`

### What did you expect to see?
`n` should be uint64, because uint64 is large enough

### What did you see instead?
`n` is int64

**Comment by FiloSottile** [comment]
I imagine the advantages of switching to `uint64` are not worth breaking the API compatibility, but @jba might have more info on why.

**Comment by Sherlock-Holo** [comment]
I discussed it with my friends, we suppose we almost won't use a number larger than maxint64. however uint64 can smaller than 0 and wet won't make n smaller than 0 so it won't panic

**Comment by ianlancetaylor** [comment]
In general numbers should be signed unless it is important that they be unsigned.  All computer integers have strange behavior at some points.  Signed integers have strange behavior at very large absolute values.  Unsigned integers have strange behavior at zero.  Zero is much more common in real life, so on average we minimize surprises by using signed integers.
