### ISSUE TITLE
strings.Trim has unexpected behavior sometimes

### ISSUE THREAD

**Issue by andyafter** [golang/go#27360]
Hey I get unexpected behaviours when I'm using strings trim
```
strings.Trim("VariableManage", "Manage")
strings.Trim("VariableAManage", "Manage")
strings.Trim("VariablManage", "Manage")
```
I get `Variabl`  for the above three lines as a result, which is unexpected. 

but for 
```
strings.Trim("VariabldManage", "Manage")
```
I get `Variabld`, is this a bug?

**Comment by ianlancetaylor** [comment]
I think you are looking for `strings.TrimSuffix`.  `strings.Trim` takes a set of characters to remove, not a string.
