### ISSUE TITLE
x/build/version/go1.10.4 doesn't exist yet

### ISSUE THREAD

**Issue by Deleplace** [golang/go#27369]
### What version of Go are you using (`go version`)?
`go version devel +b8669ef1ce linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

```
$ go get golang.org/x/build/version/go1.10.4
```

### What did you expect to see?

No output (go1.10.4 successfully go got)

### What did you see instead?

```
package golang.org/x/build/version/go1.10.4: cannot find package "golang.org/x/build/version/go1.10.4" in any of:
	/usr/lib/google-golang/src/golang.org/x/build/version/go1.10.4 (from $GOROOT)
	/home/deleplace/go/src/golang.org/x/build/version/go1.10.4 (from $GOPATH)
```

**Comment by FiloSottile** [comment]
Hi! Thanks for opening an issue.

`x/build/version` is deprecated, the new path is `golang.org/dl/go1.10.4`.

(Did you find that command somewhere we forgot to fix, or just tried it out?)

**Comment by laurentroyerkubity** [comment]
I just tried it out.

**Comment by Deleplace** [comment]
I just tried it out.
