### ISSUE TITLE
cmd/go: build fails to parse GOFLAGS

### ISSUE THREAD

**Issue by mhr3** [golang/go#27368]
### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What did you do?
Running `GOFLAGS="-ldflags '-w -s'" go build pkgname` produces an error with go 1.11 (used to work fine with 1.10):
```
go: parsing $GOFLAGS: non-flag "'-w"
```

The flag still works when passed directly to go build, but if the env var is set, the compilation fails.

**Comment by myitcv** [comment]
cc @bcmills

**Comment by agnivade** [comment]
You are setting the flags incorrectly. https://tip.golang.org/cmd/go/#hdr-Environment_variables

Each flag need to be space-separated and standalone. `GOFLAGS="-ldflags=-w -ldflags=-s"`.

Also see - https://github.com/golang/go/issues/27282
