### ISSUE TITLE
x/vgo: vgo list -m doesn't list dependencies

### ISSUE THREAD

**Issue by huydinhle** [golang/go#27386]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
```
go env
GOARCH="amd64"
GOHOSTARCH="amd64"

```

### What did you do?
i follow this guide https://research.swtch.com/vgo-tour till the `vgo list -m` command

### What did you expect to see?
vgo list -m
github.com/huydinhle/vgo-example
golang.org/x/text     v0.0.0-20170915032832-14c0d48ead0c  v0.3.0 (2017-12-14 08:08)
rsc.io/quote          v1.5.2 (2018-02-14 10:44)           -
rsc.io/sampler        v1.3.0 (2018-02-13 14:05)           v1.99.99 (2018-02-13 17:20)

### What did you see instead?
vgo list -m
github.com/huydinhle/vgo-example

**Comment by FiloSottile** [comment]
I hear from @bcmills that we roll changes from the go tool to x/vgo on every release.

@huydinhle can you share your `go.mod`, and test if `go list -m` with Go 1.11 also has the same issue?

**Comment by huydinhle** [comment]
### go.mod
```
module github.com/you/hello

require rsc.io/quote v1.5.2
```
### go version go1.10.3 linux/amd64 vgo:devel +1b870077c8
```
vgo list -m
github.com/you/hello
```
### go version go1.11 linux/amd64

```
go/bin/go list -m
go list -m: not using modules
```

**Comment by bcmills** [comment]
Try `go list -m all`. I think `go list -m` only lists the main module.

**Comment by FiloSottile** [comment]
(You might need to set `GO111MODULE=on` for `go list` to work.)
