### ISSUE TITLE
github: clean up open issue on closed milestones

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#27392]
Some of the closed milestones here have open issues. They shouldn't.

https://github.com/golang/go/milestones?state=closed

**Comment by agnivade** [comment]
@FiloSottile - Related to this, there are also backport issues which keep getting pushed back to the next minor release milestone.

If we aren't going to backport a fix, shouldn't we just close the issue ? Is there a reason, a fix should _not_ be in 1.11.1, but in 1.11.2 ?

**Comment by FiloSottile** [comment]
@agnivade If we decided we are not backporting something, yes we should close the issue. But reasons to push to the next release include: the fix is not ready, the cherry-pick is not finished, and a decision wasn't made. Then the issue is useful to keep track of it.

There is a gap in the process in that we did not have a process to go through the open issues and make decisions for the ones that are ready. We'll address that soon.

**Comment by FiloSottile** [comment]
On second thought, this is not worth automating.
