### ISSUE TITLE
runtime/trace: incorrect WithRegion usage in code snippet

### ISSUE THREAD

**Issue by ondrej-fabry** [golang/go#27406]
### What version of Go are you using (`go version`)?
* 1.11

### Does this issue reproduce with the latest release?
* yes (go1.11)

### What did you do?
* Read code snippet in docs for https://golang.org/pkg/runtime/trace/#NewTask

### What did you expect to see?
```
...
trace.WithRegion(ctx, "preparation", prepWork)
// preparation of the task
go func() {  // continue processing the task in a separate goroutine.
    defer task.End()
    trace.WithRegion(ctx, "remaining", remainingWork)
}()
```

### What did you see instead?
```
...
trace.WithRegion(ctx, prepWork)
// preparation of the task
go func() {  // continue processing the task in a separate goroutine.
    defer task.End()
    trace.WithRegion(ctx, remainingWork)
}
```

---

The `trace.WithRegion` requires 3 parameters (`ctx`, `regionType`, `fn`) however in the code snippet for [trace.NewTask](https://golang.org/pkg/runtime/trace/#NewTask), it seems to be missing some parameter. 

It depends what `prepWork` and `remainingWork` represent here, but if they represent function (`fn` parameter) then this code snippet is misisng `regionType` parameter.

The code snippet is also missing `()` for the `go func() ...` call.

**Comment by Charliekenney23** [comment]
I'll take this
