### ISSUE TITLE
os/user: cannot pick up sss users in nocgo mode

### ISSUE THREAD

**Issue by fmd** [golang/go#27412]
### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### Problem:
the `os/user` package has moved off of using cgo system commands to find users. On our system (and many others), there are several users that don't appear in `/etc/passwd`, but on the system we can see them fine with `getent passwd <USER>` (because sssd handles this). 

So, as the `os/user` package uses only `/etc/passwd` to look for users, go doesn't have a way (as far as i know) to get all the users without using `getent` or `id` directly. 

How can we make Go able to find all of the users like `getent` or `id` can?

**Comment by dominikh** [comment]
> the os/user package has moved off of using cgo system commands to find users

What makes you say that? Go still uses the libc for os/user, when building with cgo support enabled.

See for example https://github.com/golang/go/blob/master/src/os/user/cgo_lookup_unix.go.

**Comment by kevinburke** [comment]
Maybe you are cross compiling binaries? IIRC that causes the library to use pure Go instead of cgo.
