### ISSUE TITLE
cmd/go: should go get deduce semantic import versioning when GO111MODULE is off?

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#27430]
#### What version of Go are you using (`go version`)?
1.11

#### Does this issue reproduce with the latest release?
Yes

#### What operating system and processor architecture are you using (`go env`)?
All 

#### What did you do?
`GO111MODULE=off go get github.com/google/go-github/v18/github`

#### What did you expect to see?
Go downloads the library into my GOPATH ignoring the v8 suffix. 

#### What did you see instead?
```
package github.com/google/go-github/v18/github: cannot find package "github.com/google/go-github/v18/github" in any of:
	/usr/local/go/src/github.com/google/go-github/v18/github (from $GOROOT)
	/Users/me/go/src/github.com/google/go-github/v18/github (from $GOPATH)
```

#### Summary 

1. Go's import paths are smart enough to ignore the v18 when GO111MODULE is turned off.
2. `go install` is also smart enough to remove vX when installing a go binary. 

What makes go-get an exception? 

#### Impact 

If things stay the same way, all libraries like github.com/google/go-github will have to have **two** instructions for their users to download their library. Something like this: 

```
### Installation
With Go Modules: 
go get github.com/google/go-github/v18/github
import "github.com/google/go-github/v18/github" 

Without Go Modules: 
go get github.com/google/go-github/github
import "github.com/google/go-github/github"
```

Of course, you don't need to do go-get with Go Modules but the point is all the same: having two different installation/import instructions.

**Comment by myitcv** [comment]
This is effectively the library equivalent of https://github.com/golang/go/issues/24250 (from both an implementation and docs perspective)

**Comment by bcmills** [comment]
I don't think this actually has much to do with #24250: that issue is about what happens in module mode (and does not modify `GOPATH/src`), whereas this one is about what happens in `GOPATH` mode (and doesn't really affect the semantics of module mode).

**Comment by bcmills** [comment]
FWIW, there is already a difference in instructions: users of a library in module mode will generally not need to run `go get` at all. So the documentation would be more like:

```
### To use:
import "github.com/google/go-github/v18/github"

### To install:
(Only necessary if Go modules are not enabled.)
go get -u github.com/google/go-github/github
```

**Comment by bcmills** [comment]
One final note: any change here would either require backports or introduce behavior in `GOPATH` mode that only affects versions of the `go` command that also support module mode. The latter option seems a little strange to me.

**Comment by myitcv** [comment]
@bcmills 

> > This is effectively the library equivalent of #24250
>
> I don't think this actually has much to do with #24250:

I honestly can't tell you what I was thinking when I wrote that!

**Comment by rsc** [comment]
The module vs non-module import path magic is necessarily incomplete. You cannot use a go command in GOPATH mode and pretend to have full support for semantic import paths. The special case we added is limited, to avoid ambiguity. The limitation is:

> In module-aware code (a .go file within a tree with a go.mod file), an unresolvable import with a version number will be tried again after removing the version number.

This does _not_ apply to anything else but that special case. In particular it does not apply to _any_ command line usage, not to go get, not to go list, not to go anything. 

It's just not a goal to try to make GOPATH mode "more like" module mode. I think that will lead to more confusion than anything. The GOPATH-mode name for that package does not have a v18 in it.
