### ISSUE TITLE
cmd/go: What should the new semver tag be for +incompatible modules? 

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#27432]
### Summary 
When a +incompatible module decides to introduce a go.mod file and updates all of its import paths to include vX, what should their new `git tag` be? Should they bump their patch, minor, or major? 

### What version of Go are you using (`go version`)?
1.11

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
All

### What did you do?
Introduce go.mod to a +incompatible package: https://github.com/google/martian/pull/262

### What did you expect to see?
A clear instruction on how to migrate such libraries.

### What did you see instead?
I'm not sure if google/martian should go from `v2.0.0` to `v2.0.1` or `v2.1.0` or `v3.0.0`

**Comment by marwan-at-work** [comment]
I briefly discussed this with Go team members at GopherCon but the question has come up a few times from library owners so I thought I'd create an issue for it. 

cc: @bcmills

**Comment by bcmills** [comment]
Closing as a dup of (the newly-reopened) #25967.
