### ISSUE TITLE
x/tools/go/packages: incorrect documentation

### ISSUE THREAD

**Issue by AlekSi** [golang/go#27449]
https://godoc.org/golang.org/x/tools/go/packages currently says:

> NOTE: THIS PACKAGE IS NOT YET READY FOR WIDESPREAD USE:
>
> - The interface is still being revised and minor changes are likely.
> - The implementation depends on the Go 1.11 go command;
>  support for earlier versions will be added soon.
> - We intend to finalize the API before Go 1.11 is released.

Go 1.11 is released. Probably the last sentence should mention Go 1.12?

**Comment by agnivade** [comment]
The documentation is fixed now.
