### ISSUE TITLE
x/tools/go/ssa: wrapper function for embedded type has invalid variadic parameter

### ISSUE THREAD

**Issue by aykevl** [golang/go#27453]
Go version: `go1.11 linux/amd64`
Package "x/tools/go/ssa" version: master (https://github.com/golang/tools/commit/7ca132754999accbaa5c1735eda29e7ce0f3bf03)

See this code ([play](https://play.golang.org/p/woi4_hJNBXg)):

```go
package main

type Foo int

type Bar struct {
	Foo
}

func (f Foo) Call(args ...interface{}) {
}

func main() {
	var f Foo
	var itf interface{} = f
	_ = itf
}
```

It produces the following SSA (shortened). I've also printed the actual parameters just before printing the SSA, for debugging.

```
arg: parameter f : Foo
arg: parameter args : []interface{}
# Name: (examples/varargbug.Foo).Call
# Package: examples/varargbug
# Location: src/examples/varargbug/main.go:9:14
func (f Foo) Call(args ...interface{}):
0:                                                                entry P:0 S:0
	return

arg: parameter f : *examples/varargbug.Foo
arg: parameter args : [][]interface{}
# Name: (*examples/varargbug.Foo).Call
# Synthetic: wrapper for func (examples/varargbug.Foo).Call(args ...interface{})
# Location: src/examples/varargbug/main.go:9:14
func (f *examples/varargbug.Foo) Call(args ...interface{}):
0:                                                                entry P:0 S:0
	t0 = ssa:wrapnilchk(f, "examples/varargbu...":string, "Call":string) *examples/varargbug.Foo
	t1 = *t0                                         examples/varargbug.Foo
	t2 = (examples/varargbug.Foo).Call(t1, args...)                      ()
	return

# Name: examples/varargbug.main
# Package: examples/varargbug
# Location: src/examples/varargbug/main.go:12:6
func main():
0:                                                                entry P:0 S:0
	; var f examples/varargbug.Foo @ 13:6 is 0:examples/varargbug.Foo
	; var f examples/varargbug.Foo @ 14:24 is 0:examples/varargbug.Foo
	t0 = make interface{} <- Foo (0:Foo)                        interface{}
	; var itf interface{} @ 14:6 is t0
	; var itf interface{} @ 15:6 is t0
	return
```

As you can see, `(*examples/varargbug.Foo).Call` somehow has type `[][]interface{}` for the variadic arguments, which I believe is incorrect. It should be `[]interface{}`, as that's what is used in other places for variadic arguments. The result is that when the wrapper calls the underlying function, there is a type mismatch.

One place in the standard library where this happens is in "syscall/js". The `Error` type embeds the `Value` type so the SSA translation creates a wrapper function called `(*syscall/js.Error).Call()`, leading to this issue.

**Comment by ianlancetaylor** [comment]
CC @alandonovan

**Comment by alandonovan** [comment]
> As you can see, (*examples/varargbug.Foo).Call somehow has type [][]interface{} for the variadic arguments, which I believe is incorrect. It should be []interface{}, as that's what is used in other places for variadic arguments.

The usual output from the SSA package looks correct to me. The part that is inconsistent is the `arg: parameter args : [][]interface{}` line, which came from the print statement you added, which I cannot see.  I tried printing the types of the formal parameters [sic; not 'actual'] but nothing was amiss.

Could you send me the patch that added the print statement?

**Comment by aykevl** [comment]
It is not a patch (to the ssa package), it is a program that prints the generated SSA form.

I will post a better sample soon, but it is something like:

```go
    for _, fn := range package.Members {
        for _, param := fn.Params {
            println("arg:", param.String())
        }
        fn.WriteTo(os.Stdout)
    }
```
