### ISSUE TITLE
encoding/json: custom UnmarshalTypeError no longer has struct context

### ISSUE THREAD

**Issue by stephane-moreau** [golang/go#27464]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Works with: go version go1.10.3 windows/amd64
Fail with: go version go1.11 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\steph\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\dev\source\catapult/go
set GORACE=
set GOROOT=C:\dev\tools\go1.10.3
set GOTMPDIR=
set GOTOOLDIR=C:\dev\tools\go1.10.3\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\steph\AppData\Local\Temp\go-build387032470=/tmp/go-build -gno-record-gcc-switches

(tested too on Mac OSX)

### What did you do?
This used to wokr when using go.lang prior to version 1.11
https://play.golang.org/p/kbRsWxsQwE0

Looks like the way error handling changed in json.Unmarshal did change the errorContext for custom unmarshaller

### What did you expect to see?
```shel
PS C:\dev\source\test\marhsal> $env:GOROOT="c:\dev\tools\go1.11"
PS C:\dev\source\test\marhsal>  C:\dev\tools\go1.11\bin\go version
go version go1.11 windows/amd64
PS C:\dev\source\test\marhsal>  C:\dev\tools\go1.11\bin\go run .\main.go
FIRST: An error was detected when parsing field:
-----------
SECOND: An error was detected when parsing field:
```

### What did you see instead?
```shell
PS C:\dev\source\test\marhsal> $env:GOROOT="c:\dev\tools\go1.10.3"
PS C:\dev\source\test\marhsal>  C:\dev\tools\go1.10.3\bin\go version
go version go1.10.3 windows/amd64
PS C:\dev\source\test\marhsal>  C:\dev\tools\go1.10.3\bin\go run .\main.go
FIRST: An error was detected when parsing field: foo_tag
-----------
SECOND: An error was detected when parsing field: foo_tag
```

**Comment by myitcv** [comment]
cc @mvdan

**Comment by iand** [comment]
Looking at this in more detail, I have doubts about the severity of the problem. It is only caused when the custom `UnmarshalJSON` method returns an empty `UnmarshalTypeError`. Changing the error type returned results in no regression from 1.10.1 (based on running in playground compared with tip): https://play.golang.org/p/PfSrNduIVmY

**Comment by iand** [comment]
Returning an `UnmarshalTypeError` only seems to have worked by accident in 1.10.3. The error returned by Unmarshal has mostly empty field values with only the Struct and Field fields populated. See https://play.golang.org/p/B6g9HMMmOQ4

**Comment by stephane-moreau** [comment]
Thanks all for your inputs, 

@iand: This was a simplified code sample where other fields where populated
I was only expecting Struct and Field name to be populated by the json decoder, 

as a side note : I Just tested this in 1.9.2 and 1.10 on windows released versions and both gave foo_tag as the field being the culprit of the unmarshaling error

If there is another mean to get the errorContext from decoder, I would be more than happy to use it instead of this.

**Comment by andybons** [comment]
@dsnet

**Comment by mvdan** [comment]
@gopherbot please backport to 1.11.
