### ISSUE TITLE
Unable to decode some PNG files

### ISSUE THREAD

**Issue by nicolaselkhoury** [golang/go#27467]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ubuntu 16.04

### What did you do?

I have a code that downloads images from AWS S3, decodes them, and resizes them. The code supports images with PNG and JPG/JPEG formats. 

Here is how I download the images from AWS S3:

    //downloads an image from S3
    func downloadImage(bucket string, item string) error {
	file, err := os.Create(strings.Split(item, "/")[len(strings.Split(item, "/"))-1])
	if err != nil {
		fmt.Println("Unable to open file", err)
		return err
	}
	//create a new AWS session
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String("eu-west-1")},
	)
	//create the s3 downloader
	downloader := s3manager.NewDownloader(sess)

	defer file.Close()
	//download the image from S3
	numBytes, err := downloader.Download(file,
		&s3.GetObjectInput{
			Bucket: aws.String(bucket),
			Key:    aws.String(item),
		})
	if err != nil {
		fmt.Println("Unable to download item", item)
		fmt.Println(err)
		return err
	}

	fmt.Println("Downloaded", file.Name(), numBytes, "bytes")
	return nil
    }

Here is how I decode the images: 
    
    file, err := os.Open(image)
	if err != nil {
		fmt.Println(err)
		return err
	}
    if strings.Split(image, ".")[len(strings.Split(image, "."))-1] == "jpg" ||
		strings.Split(image, ".")[len(strings.Split(image, "."))-1] == "jpeg" {
		img, err := jpeg.Decode(file)

		if err != nil {
			fmt.Println(err)
			return err
		}
		file.Close()
    }
    else if strings.Split(image, ".")[len(strings.Split(image, "."))-1] == "png" {
		img, err := png.Decode(file)

		if err != nil {
			fmt.Println(err)
			return err
		}
		file.Close()
    }

The images are downloaded, decoded, and resized successfully. A problem arises when the code downloads some PNG images (not all), and tries to decode them. It can't.

it generates the following error:

    png: invalid format: not a PNG file

I am running everything on top of an Ubuntu 16.04. What is weird is that if I open this image using Image viewer, it generates the same error. However, if I open using any other program, such as: ImageMagick, the image opens without any complaint.

How can I overcome this issue in the Golang code?

### What did you expect to see?

An unexpected error
### What did you see instead?
The file to be opened

**Comment by agnivade** [comment]
Are you sure the image is actually a PNG file and not anything else ? ImageMagick might detect the underlying image magic header and detect the real format.

It may be such that your file extension is png, but it has been compressed to webp or other such formats. You can use the `image.Decode` function directly and do not need to check for the file extension at all. Just register all the possible image decoders that you expect your image to have.

Something like this - 

```go
import (
 "image"
 "image/png"
 "io"

 _ "code.google.com/p/vp8-go/webp"
 _ "image/jpeg"
)

func main() {
 img, _, err := image.Decode(file)
 if err != nil {
  return err
 }
}
```

**Comment by nicolaselkhoury** [comment]
Thank you for your quick response. To be extremely clear, no I am not 100% sure that it is a PNG format. In fact, these images are uploaded by customers on our service. I am actually counting on the file extension and Content-Type to determine the type of the image.

Moreover, I did use the `image.Decode` function to overcome the issue and it worked. I was just surprised by the error, and wanted to find out where the issue is

**Comment by agnivade** [comment]
There can be cases where file extension and content-type are incorrect. Sniffing the magic header is the only reliable way to decode an image. Since you seem to have solved the issue, I am guessing the the file extension was incorrect for the actual image type.

Closing it. If you find an actual png image which does not decode, please raise another issue with the given image which causes the failure so that we can debug the issue. Thank you.
