### ISSUE TITLE
"go build ./..." doesn't build binaries

### ISSUE THREAD

**Issue by pd93** [golang/go#27463]
Could find any documentation on this. Is this by design, broken or not implemented? 

### What version of Go are you using (`go version`)?
v1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Windows amd64

### What did you do?
Ran `go build ./…` in a directory with 3 folders - each containing a Go project that produces a binary.

### What did you expect to see?
Three executables in my cwd

### What did you see instead?
No executables in my cwd

**Comment by kardianos** [comment]
I think a duplicate of https://github.com/golang/go/issues/14295

**Comment by pd93** [comment]
@kardianos Thanks, I tried searching, but couldn't find an open issue - shall subscribe there 😃
