### ISSUE TITLE
cmd/go: go1.11 failed to derive $GOPATH in container environment

### ISSUE THREAD

**Issue by rockmenjack** [golang/go#27468]
### What version of Go are you using (`go version`)?
go 1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?
go test/build a module in a container

### What did you expect to see?
command shall run without any issue

### What did you see instead?
go complains "missing $GOPATH"

I have checked go env output in the container:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""             <--  empty here!!!
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build579993932=/tmp/go-build -gno-record-gcc-switches"
```

go env looks ok in the host:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rockmen1/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rockmen1/go"    <--   however this dir does not exist
GOPROXY=""
GORACE=""
GOROOT="/tmp/go"
GOTMPDIR=""
GOTOOLDIR="/tmp/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build691156100=/tmp/go-build -gno-record-gcc-switches"
```

Can be easily reproduce with below Dockerfile:
```
#FROM centos:7
FROM debian:9

ADD go1.11.linux-amd64.tar.gz /root

CMD GOROOT=/root/go /root/go/bin/go env
```

older go version runs fine.

**Comment by mfrw** [comment]
The issue https://github.com/golang/go/issues/17262 might help you in understanding why `host` shows $GOPATH as a non-existent directory.

**Comment by andybons** [comment]
@bcmills

**Comment by bcmills** [comment]
> go test/build a module in a container

> older go version runs fine.

These can't both hold, can they? Older go versions don't support modules.

**Comment by bcmills** [comment]
In Go 1.12, you will need to set either `$HOME`, or both `$GOCACHE` and `$GOPATH` (see #29267).

Environments without `$HOME` are pretty clearly in power-user territory, so the need for a bit of configuration should not come as a big surprise.
