### ISSUE TITLE
cmd/go: migrate tests from `vcs-test.golang.org` to a test-local server

### ISSUE THREAD

**Issue by jasonkeene** [golang/go#27494]
There are a few tests that rely on `vcs-test.golang.org`. Do we need to have these tests talk to a vcs server on the internet or can the tests just start this server themselves? If the server can be ran locally I would think that would be better than having them rely on the availability of `vcs-test.golang.org`.

Follow up from: https://github.com/golang/go/issues/27127#issuecomment-417939775

cc/ @FiloSottile

**Comment by andybons** [comment]
@bcmills @rsc
