### ISSUE TITLE
x/sys/unix: TestPpoll and TestPoll fail a `test all`

### ISSUE THREAD

**Issue by hdonnay** [golang/go#27492]
### What version of Go are you using (`go version`)?
    go version go1.11 linux/amd64

### What did you do?

```
cd $(mktemp -d)
cat >ex.go <<.
package main

import (
	"fmt"

	_ "golang.org/x/sys/unix"
)

func main() {
	fmt.Println("example")
}

.
go mod init example && go test all; echo $?
```

### What did you expect to see?
    0

### What did you see instead?
    1

The tests fail, presumably because it's run in a non-writable place.
```
--- FAIL: TestPpoll (0.00s)
    syscall_unix_test.go:613: mktmpfifo: failed to create FIFO: permission denied
--- FAIL: TestPoll (0.00s)
    syscall_unix_test.go:613: mktmpfifo: failed to create FIFO: permission denied
FAIL
FAIL	golang.org/x/sys/unix	0.171s
```

With modules, is there a place that tests can write to?

**Comment by bcmills** [comment]
Fixed by [CL 162987](https://golang.org/cl/162987).
