### ISSUE TITLE
cmd/go: invalid flag when importing bimg

### ISSUE THREAD

**Issue by tssajo** [golang/go#27496]
### What version of Go are you using (`go version`)?
```
# go version
go version go1.11 linux/amd64
```
### Does this issue reproduce with the latest release?
Yes, and I can reproduce the issue with Go 1.10.x too.
However the build works just fine with Go 1.9.6 on an Ubuntu 14.04 system.

### What operating system and processor architecture are you using (`go env`)?
```
# lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie
```
```
# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tss/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414295438=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
Wrote a program using h2non/bimg.v1 that begins like this:
```
package main

import (
	bimg "gopkg.in/h2non/bimg.v1"
)
```
and then tried to build it:
```
go build
```

### What did you expect to see?
A successful build.

### What did you see instead?
```
# go build
go build gopkg.in/h2non/bimg.v1: invalid flag in pkg-config --libs: -Wl,--export-dynamic
```

Any help would be highly appreciated!

Note: Because of the above issue, I'm stuck with Go 1.9.6 for quiet a while now... :(

**Comment by andybons** [comment]
@ianlancetaylor looks like another flag to add to the whitelist?

**Comment by AlexRouSg** [comment]
@tssajo As a temporary workaround there is a `CGO_LDFLAGS_ALLOW` environmental flag which accepts a regex.
