### ISSUE TITLE
 atomic.Xchg

### ISSUE THREAD

**Issue by zhuzy-xys** [golang/go#27490]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by andriisoldatenko** [comment]
@zhuzy-xys please remove duplicate https://github.com/golang/go/issues/27491 or add more info.

**Comment by ALTree** [comment]
If you are asking for something like the `xchg` instruction in x86, it's already in `atomic`, called [Swap](https://golang.org/pkg/sync/atomic/#SwapInt64).
