### ISSUE TITLE
plugin: test fails for debug sections on Darwin

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#27502]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Rebuild the lastest tip version with all.bash

#### What did you expect to see?

All tests pass.

#### What did you see instead?

```
##### ../misc/cgo/testso

##### ../misc/cgo/testsovar

##### ../misc/cgo/testcarchive
PASS

##### ../misc/cgo/testcshared
PASS

##### ../misc/cgo/testplugin
error opening DWARF: decoding dwarf section info at offset 0x0: too shortexit status 1
2018/09/05 07:43:23 Failed: exit status 1
2018/09/05 07:43:24 FAILED
```

#### Does this issue reproduce with the latest release (go1.11)?
N/A
#### System details

```
go version devel +b444215116 Tue Sep 4 20:41:58 2018 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki.shibata/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki.shibata/gocode"
GOPROXY=""
GORACE=""
GOROOT="/Users/yoshiki.shibata/tools/go"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki.shibata/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +b444215116 Tue Sep 4 20:41:58 2018 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +b444215116 Tue Sep 4 20:41:58 2018 +0000
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by heschik** [comment]
This was 9c833831b2bdaa465349194797cf3894cb85f9c4. Sorry, I thought that the Mac trybots were enabled again so I didn't test it manually. I'm not in a position to do anything until tomorrow, maybe @aarzilli can take a look.

**Comment by juhwany** [comment]
@ianlancetaylor 

I can't debug plugin on mac even in Go 1.13. 
@aarzilli said debugging section is missing in plugin.  https://github.com/go-delve/delve/issues/1628

Is there any progress?

**Comment by ianlancetaylor** [comment]
@juhwany As far as I know nobody is working on this.  Sorry.

**Comment by juhwany** [comment]
It's really hard to code plugin without supporting debugging. Hope next Go release will fix this.

**Comment by ianlancetaylor** [comment]
It remains true that as far as I know nobody is working on this.  This issue is marked "help wanted" and I hope that someone can help here.

**Comment by thanm** [comment]
I am working on a related bug [21647](https://github.com/golang/go/issues/21647) and at this point I think I am getting close to getting this fixed. The patch I created to address the problems is:  [1829590](https://go-review.googlesource.com/c/go/+/1829590)

If anyone wants to try testing it, that might be helpful. Thanks, Than

**Comment by aarzilli** [comment]
The other impediment to debugging plugins on macOS is https://github.com/golang/go/issues/25841, I don't know if it has been fixed in the meantime (I suspect it hasn't).
