### ISSUE TITLE
x/build/cmd/gerritbot: comments occasionally not posted to GitHub PR

### ISSUE THREAD

**Issue by odeke-em** [golang/go#27504]
Over the past couple of days I've been involved with at least two separate issues with bodies that were updated on Github but Gopherbot did not mirror them on Gerrit yet posted up messages on Gerrit.

Those issues are:
* CL https://go-review.googlesource.com/c/go/+/132479 aka PR https://github.com/golang/go/pull/27409
### Got
<img width="1168" alt="screen shot 2018-09-04 at 6 25 52 pm" src="https://user-images.githubusercontent.com/4898263/45065789-074b4800-b070-11e8-98c8-c26e7cb539ec.png">
<img width="799" alt="screen shot 2018-09-04 at 6 26 06 pm" src="https://user-images.githubusercontent.com/4898263/45065792-0a463880-b070-11e8-9806-6ddad2b901b2.png">

### Want
<img width="1011" alt="screen shot 2018-09-04 at 6 25 14 pm" src="https://user-images.githubusercontent.com/4898263/45065778-ec78d380-b06f-11e8-9d26-72658a7b33a8.png">

* CL https://go-review.googlesource.com/c/go/+/132781 aka PR https://github.com/golang/go/pull/27446
### Got
<img width="963" alt="screen shot 2018-09-04 at 6 27 15 pm" src="https://user-images.githubusercontent.com/4898263/45065841-3497f600-b070-11e8-8b84-b43c2b895134.png">
<img width="753" alt="screen shot 2018-09-04 at 6 27 27 pm" src="https://user-images.githubusercontent.com/4898263/45065843-382b7d00-b070-11e8-99c7-4f74f46436d8.png">

### Want
<img width="1007" alt="screen shot 2018-09-04 at 6 28 08 pm" src="https://user-images.githubusercontent.com/4898263/45065855-4e393d80-b070-11e8-9c7c-7fa9baefc354.png">

and also there have been a couple of PRs for which a Gerrit CL wasn't opened, perhaps the problem is related? For example:
* https://github.com/golang/go/pull/26932#issuecomment-418000373
* https://github.com/golang/go/pull/26777#issuecomment-418001138

**Comment by dmitshur** [comment]
Something along these lines happened in https://github.com/golang/dl/pull/1 as well. The PR was mirrored (to https://go-review.googlesource.com/c/dl/+/134117) but no corresponding "PR has been imported to Gerrit" comment was created.

I filed #27561 with more details for that particular instance, but I suspect there's overlap with this issue.

**Comment by dmitshur** [comment]
Now that https://github.com/golang/go/issues/27561#issuecomment-420072789 is resolved, at least a part of this issue should be resolved too. Perhaps all of it.

If there are further occurrences of this, please let us know. Otherwise, we can probably close this after some time passes.
