### ISSUE TITLE
cmd/compile: 387 quietens signalling NaNs during compilation

### ISSUE THREAD

**Issue by mundaym** [golang/go#27516]
The compiler, when built using `GOARCH=386 GO386=387`, is generating the wrong code for this test. It is still quietening float32 signalling NaNs that are constant folded (see issue #27193). We are either still relying on floating point behavior somewhere in the compiler that is undefined or (less likely) there is a bug in the 387 backend.

**Comment by cherrymui** [comment]
The mipsle builder is also failing, with a different error though.
https://build.golang.org/log/453d116005d8a95c02b773e969674ddd9f74a6c6

**Comment by milanknezevic** [comment]
The error on mipsle is caused by `NaN` value of `7FF7FFFFFFFFFFFF` which causes this condition to be true. https://github.com/golang/go/blob/9facf35592457f0cdd1a9da665fd946002123007/src/cmd/compile/internal/ssa/check.go#L515
Maybe `!math.isNaN(x)` check should be added to the condition.

**Comment by randall77** [comment]
@milanknezevic What function is being compiled when this happens?  Where is it getting that NaN value from?

**Comment by milanknezevic** [comment]
@randall77 

> What function is being compiled when this happens?

This is the error message: `./map.go:515:31: internal compiler error: 'testfloat': panic during opt while compiling testfloat`, but the same behavior on mipsle can be reproduced with [this test case](https://play.golang.org/p/cXE7r3J9hyC). 

> Where is it getting that NaN value from?

After constant folding (`Cvt64Fto32F`) of value returned by `math.NaN()`, `AuxInt` field contains `0x7FF7FFFFFFFFFFFF`.
Just to mention, `0x7FF8000000000001` which is returned by `math.NaN()` is signaling NaN on mips, not quiet NaN as on other architectures. So when we do this constant folding on mips hardware we actually get `0x7FF7FFFFFFFFFFFF`.

**Comment by mundaym** [comment]
@milanknezevic Does [CL 134855](https://golang.org/cl/134855) help at all? It should stop ones being appended to NaN values after a float64 -> float32 conversion.

**Comment by mundaym** [comment]
The 387 failure seems to exist even when constant propagation is disabled. So I guess even just loading a float32 into the 387 unit quietens the NaN? Does anyone know why this happens with 387?

I applied the following patch to the generic rules (at CL 134855):

```diff
diff --git a/src/cmd/compile/internal/ssa/gen/generic.rules b/src/cmd/compile/internal/ssa/gen/generic.rules
index cdf425a7e0..ec25dc10ba 100644
--- a/src/cmd/compile/internal/ssa/gen/generic.rules
+++ b/src/cmd/compile/internal/ssa/gen/generic.rules
@@ -44,8 +44,8 @@
 (Trunc64to8  (Const64  [c])) -> (Const8   [int64(int8(c))])
 (Trunc64to16 (Const64  [c])) -> (Const16  [int64(int16(c))])
 (Trunc64to32 (Const64  [c])) -> (Const32  [int64(int32(c))])
-(Cvt64Fto32F (Const64F [c])) -> (Const32F [f2i(extend32Fto64F(float32(i2f(c))))])
-(Cvt32Fto64F (Const32F [c])) -> (Const64F [c]) // c is already a 64 bit float
+//(Cvt64Fto32F (Const64F [c])) -> (Const32F [f2i(extend32Fto64F(float32(i2f(c))))])
+//(Cvt32Fto64F (Const32F [c])) -> (Const64F [c]) // c is already a 64 bit float
 (Cvt32to32F  (Const32  [c])) -> (Const32F [f2i(extend32Fto64F(float32(int32(c))))])
 (Cvt32to64F  (Const32  [c])) -> (Const64F [f2i(float64(int32(c)))])
 (Cvt64to32F  (Const64  [c])) -> (Const32F [f2i(extend32Fto64F(float32(c)))])
@@ -571,10 +571,10 @@
        -> x
 
 // Pass constants through math.Float{32,64}bits and math.Float{32,64}frombits
-(Load <t1> p1 (Store {t2} p2 (Const64  [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 8 && is64BitFloat(t1) -> (Const64F [x])
-(Load <t1> p1 (Store {t2} p2 (Const32  [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 4 && is32BitFloat(t1) -> (Const32F [f2i(extend32Fto64F(math.Float32frombits(uint32(x))))])
-(Load <t1> p1 (Store {t2} p2 (Const64F [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 8 && is64BitInt(t1)   -> (Const64  [x])
-(Load <t1> p1 (Store {t2} p2 (Const32F [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 4 && is32BitInt(t1)   -> (Const32  [int64(int32(math.Float32bits(truncate64Fto32F(i2f(x)))))])
+//(Load <t1> p1 (Store {t2} p2 (Const64  [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 8 && is64BitFloat(t1) -> (Const64F [x])
+//(Load <t1> p1 (Store {t2} p2 (Const32  [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 4 && is32BitFloat(t1) -> (Const32F [f2i(extend32Fto64F(math.Float32frombits(uint32(x))))])
+//(Load <t1> p1 (Store {t2} p2 (Const64F [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 8 && is64BitInt(t1)   -> (Const64  [x])
+//(Load <t1> p1 (Store {t2} p2 (Const3https://play.golang.org/p/W8Su1EmcRjc2F [x]) _)) && isSamePtr(p1,p2) && sizeof(t2) == 4 && is32BitInt(t1)   -> (Const32  [int64(int32(math.Float32bits(truncate64Fto32F(i2f(x)))))])
 
 // Float Loads up to Zeros so they can be constant folded.
 (Load <t1> op:(OffPtr [o1] p1)
```

A smaller example is here: https://play.golang.org/p/W8Su1EmcRjc

This code compiles into this 387 assembler (with the patch above applied and the rules regenerated):

```asm
    00000 (8) TEXT "".main(SB)
    00001 (8) FUNCDATA $0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
    00002 (8) FUNCDATA $1, gclocals·cab29d17fa8bdbfaac1234d7f8bbe386(SB)
    00003 (8) FUNCDATA $3, gclocals·df4642631589a950a30d9cb77310f3ae(SB)
b3
    00004 (+10) PCDATA $2, $0
    00005 (+10) PCDATA $0, $0
    00006 (+10) MOVL $2140003454, math.b-36(SP)
    # $GOROOT/src/math/unsafe.go
    00007 (+14) FMOVF math.b-36(SP), F0
    # /home/michael/Development/go/scratch/f32.go
    00008 (+10) FMOVD F0, F0
    00009 (10) FMOVFP F0, math.f-40(SP)
    # $GOROOT/src/math/unsafe.go
    00010 (10) MOVL math.f-40(SP), CX
    # /home/michael/Development/go/scratch/f32.go
    00011 (+11) CMPL CX, $2140003454
    00012 (11) FMOVDP F0, F0
    00013 (11) JNE 17
    00014 (?) PCDATA $2, $-2
    00015 (?) PCDATA $0, $-2
    00016 (?) RET
    # $GOROOT/src/math/unsafe.go
    00017 (10) PCDATA $2, $0
    00018 (10) PCDATA $0, $0
    00019 (10) MOVL CX, "".got-44(SP)
    # /home/michael/Development/go/scratch/f32.go
    00020 (12) PCDATA $2, $1
    00021 (12) PCDATA $0, $1
    00022 (+12) LEAL ""..autotmp_6-32(SP), DI
    00023 (12) XORL AX, AX
    00024 (+12) PCDATA $2, $0
    00025 (12) DUFFZERO $120
    00026 (12) PCDATA $2, $2
    00027 (12) LEAL type.uint32(SB), CX
    00028 (12) PCDATA $2, $0
    00029 (12) MOVL CX, (SP)
    00030 (12) MOVL "".got-44(SP), DX
    00031 (12) MOVL DX, 4(SP)
    00032 (12) CALL runtime.convT2E32(SB)
    00033 (12) PCDATA $2, $2
    00034 (12) MOVL 12(SP), CX
    00035 (12) MOVL 8(SP), DX
    00036 (12) MOVL DX, ""..autotmp_6-32(SP)
    00037 (12) PCDATA $2, $0
    00038 (12) MOVL CX, ""..autotmp_6-28(SP)
    00039 (12) PCDATA $2, $2
    00040 (12) LEAL type.uint32(SB), CX
    00041 (12) PCDATA $2, $0
    00042 (12) MOVL CX, (SP)
    00043 (12) MOVL "".got-44(SP), DX
    00044 (12) MOVL DX, 4(SP)
    00045 (12) CALL runtime.convT2E32(SB)
    00046 (12) PCDATA $2, $2
    00047 (12) MOVL 12(SP), CX
    00048 (12) MOVL 8(SP), DX
    00049 (12) MOVL DX, ""..autotmp_6-24(SP)
    00050 (12) PCDATA $2, $0
    00051 (12) MOVL CX, ""..autotmp_6-20(SP)
    00052 (12) PCDATA $2, $2
    00053 (12) LEAL type.uint32(SB), CX
    00054 (12) PCDATA $2, $0
    00055 (12) MOVL CX, (SP)
    00056 (12) MOVL $2140003454, 4(SP)
    00057 (12) CALL runtime.convT2E32(SB)
    00058 (12) MOVL 8(SP), CX
    00059 (12) PCDATA $2, $3
    00060 (12) MOVL 12(SP), DX
    00061 (12) MOVL CX, ""..autotmp_6-16(SP)
    00062 (12) PCDATA $2, $0
    00063 (12) MOVL DX, ""..autotmp_6-12(SP)
    00064 (12) PCDATA $2, $2
    00065 (12) LEAL type.uint32(SB), CX
    00066 (12) PCDATA $2, $0
    00067 (12) MOVL CX, (SP)
    00068 (12) MOVL $2140003454, 4(SP)
    00069 (12) CALL runtime.convT2E32(SB)
    00070 (12) PCDATA $2, $2
    00071 (12) MOVL 12(SP), CX
    00072 (12) MOVL 8(SP), DX
    00073 (12) MOVL DX, ""..autotmp_6-8(SP)
    00074 (12) PCDATA $2, $0
    00075 (12) MOVL CX, ""..autotmp_6-4(SP)
    00076 (12) PCDATA $2, $2
    00077 (12) LEAL go.string."got %#v (%x), want %#v (%x)\n"(SB), CX
    00078 (+12) PCDATA $2, $0
    00079 (12) MOVL CX, (SP)
    00080 (12) MOVL $28, 4(SP)
    00081 (12) PCDATA $2, $2
    00082 (12) LEAL ""..autotmp_6-32(SP), CX
    00083 (12) PCDATA $2, $0
    00084 (12) MOVL CX, 8(SP)
    00085 (12) MOVL $4, 12(SP)
    00086 (12) MOVL $4, 16(SP)
    00087 (12) CALL fmt.Printf(SB)
    00088 (13) PCDATA $2, $2
    00089 (13) PCDATA $0, $0
    00090 (+13) LEAL type.string(SB), CX
    00091 (+13) PCDATA $2, $0
    00092 (13) MOVL CX, (SP)
    00093 (13) PCDATA $2, $2
    00094 (13) LEAL "".statictmp_0(SB), CX
    00095 (13) PCDATA $2, $0
    00096 (13) MOVL CX, 4(SP)
    00097 (13) CALL runtime.gopanic(SB)
    00098 (13) UNDEF
    00099 (?) END
```

**Comment by mundaym** [comment]
Looks like the `fld` instruction (`FLDS` in Go) is extending the float32 to float80 to put it on the x87 stack and in the process quietens the NaN. Not sure what we want to do about this...

**Comment by randall77** [comment]
This is a problem for both `float32` and `float64`.  My repro:
```
package main

import (
	"fmt"
	"unsafe"
)

var x32, y32 float32

//go:noinline
func copy32() {
	y32 = x32
}
func test32() {
	var want uint32 = 0x7f800001
	*(*uint32)(unsafe.Pointer(&x32)) = want
	copy32()
	got := *(*uint32)(unsafe.Pointer(&y32))
	if got != want {
		fmt.Printf("got=%x, want=%x\n", got, want)
	}
}

var x64, y64 float64

//go:noinline
func copy64() {
	y64 = x64
}
func test64() {
	var want uint64 = 0x7ff0000000000001
	*(*uint64)(unsafe.Pointer(&x64)) = want
	copy64()
	got := *(*uint64)(unsafe.Pointer(&y64))
	if got != want {
		fmt.Printf("got=%x, want=%x\n", got, want)
	}
}

func main() {
	test32()
	test64()
}
```
```
$ GOARCH=386 GO386=387 ~/go1.11/bin/go run tmp1.go
got=7fc00001, want=7f800001
got=7ff8000000000001, want=7ff0000000000001
```

**Comment by randall77** [comment]
Fixing this is going to be tough.  Both loads and stores need to be fixed.  I'm inclined to just declare that 387 doesn't do signaling NaNs correctly, and leave it at that.  We can disable the tests for 387.

**Comment by TocarIP** [comment]
@randall77 wont this cause different code gen due to use of Float32frombits in compiler and result in different behavior of binaries built on 387 and all others?

**Comment by randall77** [comment]
@TocarIP : yes.  Both running on 387 and compiling on 387 would be broken.
I don't think anyone is cross-compiling *from* 387.

**Comment by milanknezevic** [comment]
@mundaym Yes, it fixes the issue on mipsle.

**Comment by randall77** [comment]
Pretty easy to trigger this issue in C:
```
#include <stdio.h>

float x;
float y;

typedef unsigned long uint32;

int main(int argc, char* argv[]) {
  uint32 want = 0x7f800001;
  *(uint32*)(&x) = want;
  y = x;
  uint32 got = *(uint32*)(&y);
  if (want != got) {
    printf("%x %x\n", want, got);
  }
  return 0;
}
```
Compile with `-m32 -march=i386`.

**Comment by randall77** [comment]
Here's a [very interesting read](https://stackoverflow.com/questions/25050133/are-the-bit-patterns-of-nans-really-hardware-dependent) about this problem in Java.

`java.lang.Double.longBitsToDouble` says this:

> Note that this method may not be able to return a double NaN with exactly same bit pattern as the long argument. IEEE 754 distinguishes between two kinds of NaNs, quiet NaNs and signaling NaNs. The differences between the two kinds of NaN are generally not visible in Java. Arithmetic operations on signaling NaNs turn them into quiet NaNs with a different, but often similar, bit pattern. However, on some processors merely copying a signaling NaN also performs that conversion. In particular, copying a signaling NaN to return it to the calling method may perform this conversion. So longBitsToDouble may not be able to return a double with a signaling NaN bit pattern. Consequently, for some long values, doubleToRawLongBits(longBitsToDouble(start)) may not equal start. Moreover, which particular bit patterns represent signaling NaNs is platform dependent; although all NaN bit patterns, quiet or signaling, must be in the NaN range identified above.

**Comment by TocarIP** [comment]
It is even worse in C, due to ABI mandating x87 for returning values [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57484)
