### ISSUE TITLE
x/build/internal/gophers: first email must be Gerrit email

### ISSUE THREAD

**Issue by andybons** [golang/go#27517]
x/build/cmd/devapp/owners uses the first email returned by `gophers.GetPerson` as the Gerrit email. Perhaps we should be more specific about this in the gophers package, but for now we should ensure that the first email is the Gerrit email. You cannot add a person to a review using their Gerrit ID email, for instance.

**Comment by dmitshur** [comment]
Am I understanding this bug correctly?

```Go
p := gophers.GetPerson("@FiloSottile")
got := p.Gerrit // "6195@62eb7196-b449-3ce5-99f1-c037f21e1705"
want := "filippo@golang.org"
```

@andybons Do you know how many people, other than Filippo, are affected? Is it a part of resolving this issue to find that out?

I think it can be checked in bulk by iterating over all the people in `gophers` and seeing if the Gerrit server  at https://go-review.googlesource.com recognizes the `p.Gerrit` email value.

**Comment by andybons** [comment]
yes that's correct.

as for others affected, that's part of this bug, yes.

**Comment by dmitshur** [comment]
> You cannot add a person to a review using their Gerrit ID email, for instance.

@andybons Could you please provide more information about that. I'd like to get a better understanding of the complete high-level picture here, so I can find the most effective way to resolve the underlying issue. Answering the "What did you do? / What did you expect to see? / What did you see instead?" questions would be very helpful.

I want to be able to test my changes, and I might want to use Gerrit in the same way to verify whether my fix is complete.

**Comment by andybons** [comment]
A Gerrit user has an email associated with their account (https://go-review.googlesource.com/settings/#Profile). When assigning a reviewer, the email used must match this (or another email that the user has entered in settings).

When I say Gerrit user ID emails, I'm referring to those that look like `6195@62eb7196-b449-3ce5-99f1-c037f21e1705`. These are used internally by Gerrit in the refs/meta data model and cannot be used to assign reviews to someone. Meaning I can't send a review using `git mail -r 6195@62eb7196-b449-3ce5-99f1-c037f21e1705`.

To start, we should at least be treating the Gerrit user ID "emails" as definitely not elligible when specifying what someone's Gerrit email is (the one others should be using to assign a review to someone).

You could theoretically use https://gerrit-review.googlesource.com/Documentation/rest-api-accounts.html to check whether an ID is a valid one to determine which email to associate with an individual as well.

**Comment by dmitshur** [comment]
I understand the issue fully now. I have a fix in mind that I think will be good, and will send a CL (with a commit message that explains everything) soon.

I also want to follow up by improving the `gophers` package, see #27631.
