### ISSUE TITLE
net: empty DNS answers should fail fast

### ISSUE THREAD

**Issue by iangudger** [golang/go#27525]
With Go 1.11, DNS queries which are responded to with an empty answers section will be tried on all name servers. This was not the case with Go 1.10. This is mostly an issue if one of the name servers is broken and results in a timeout.

This issue was first reported here: https://github.com/golang/go/issues/21906#issuecomment-416809879

I am filing a new issue because this is a regression in Go 1.11 and https://github.com/golang/go/issues/21906 was filed prior to Go 1.10.

**Comment by iangudger** [comment]
This is similar to #25336.

**Comment by bcmills** [comment]
> I am filing a new issue because this is a regression in Go 1.11

Should this issue have a backport, then?

**Comment by iangudger** [comment]
I think backporting the fix would be a good idea.

**Comment by bcmills** [comment]
@gopherbot, please backport to 1.11: this is a regression of a previously-fixed issue.

**Comment by ssrikant20** [comment]
What is the ETA for this issue? This is slowing down DNS responses back to the client causing context deadline to exceed.

**Comment by iangudger** [comment]
I have been having trouble getting the fix reviewed. Brad is on vacation. Two different people have stated their intent to review it soon, so hopefully the fix will go in next week.

**Comment by ssrikant20** [comment]
> I have been having trouble getting the fix reviewed. Brad is on vacation. Two different people have stated their intent to review it soon, so hopefully the fix will go in next week.

Thank you
