### ISSUE TITLE
runtime: timeouts in os/signal tests

### ISSUE THREAD

**Issue by randall77** [golang/go#27520]
From @mwf on issue #25696 :

Hi! I ran into a similar problem here: #26317 (comment)

$ time go test all
...

*** Test killed: ran too long (10m0s).
FAIL	os/signal	605.012s
...
go test all  1521.37s user 69.95s system 228% cpu 11:35.33 total
It hangs even with -short flag passed.
The test passes without any problem in go1.10.3.
```
$ go version && go test os/signal
go version go1.10.3 darwin/amd64
ok  	os/signal	7.701s
```
The most interesting thing that `go test -short os/signal` test passes OK, if you've never run `go test os/signal` after installing go. Once you run it, short tests also hang, even `go clean -testcache` doesn't help.
```
$ go test -short os/signal
ok  	os/signal	4.742s
$ go clean -testcache
$ go test os/signal
signal: killed
FAIL	os/signal	59.544s
$ go test -short os/signal
signal: killed
FAIL	os/signal	132.764s
```
Sorry, even the -short sometimes hangs.

Please try running this:
```
for i in {1..20}
do
    go test -short os/signal;
    go clean -testcache;
done
signal: killed
FAIL	os/signal	26.467s
ok  	os/signal	4.735s
ok  	os/signal	4.716s
ok  	os/signal	4.719s
signal: killed
FAIL	os/signal	25.518s
ok  	os/signal	4.705s
signal: killed
FAIL	os/signal	13.824s
^C^C^C%
```
I killed the hanging tests manually with `ps aux | grep signal.test | grep -v "grep" | awk '{print $2}' | xargs kill -9`

So it has nothing to do with short/non-short difference.

**Comment by randall77** [comment]
I traced this into a bug in semasleep in runtime/os_darwin.go.
When the condition variable wait has a spurious wakeup (due to signals in this test, I believe) we retry the wait with the same timeout again, instead of subtracting the time used so far.  For this test, this ends up with a `time.Sleep` taking forever, as it gets spurious wakeups at a faster rate than the timeout.

**Comment by randall77** [comment]
@gopherbot, please open an issue for backport to 1.11.1.

**Comment by odeke-em** [comment]
>When you use go run, you're sending the signal to the cmd/go process, not to your program. Use go build and run the program directly rather than via go run.

@ianlancetaylor awesome, thank you for pointing that out! In deed, that was my problem.

With that update, this standalone Go repro below can now reliably serve as a regression test
```go
//+build !windows

package main

import (
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"
)

func main() {
	tempDir, err := ioutil.TempDir("", "signal-refresh")
	if err != nil {
		log.Fatalf("Failed to create the temp directory: %v", err)
	}
	defer os.RemoveAll(tempDir)

	// Given the simple program below
	repro := `
    package main

    import "time"

    func main() {
        <-time.After(2 * time.Second)
    }
    `
	mainPath := filepath.Join(tempDir, "main.go")
	if err := ioutil.WriteFile(mainPath, []byte(repro), 0755); err != nil {
		log.Printf("Failed to create temp file for repro.go: %v", err)
		return
	}
	binaryPath := filepath.Join(tempDir, "binary")

	out, err := exec.Command("go", "build", "-o", binaryPath, mainPath).CombinedOutput()
	if err != nil {
		log.Printf("Failed to compile the binary: err: %v\nOutput: %s\n", err, out)
		return
	}
	if err := os.Chmod(binaryPath, 0755); err != nil {
		log.Printf("Failed to chmod binary: %v", err)
		return
	}

	// Now run the binary
	cmd := exec.Command(binaryPath)
	if err := cmd.Start(); err != nil {
		log.Printf("Failed to start command: %v", err)
		return
	}
	doneCh := make(chan error)
	go func() {
		doneCh <- cmd.Wait()
	}()

	// Now that we've started the repro, we
	// can continuously send to it signal SIGIO.
	unfixedTimer := time.NewTimer(4 * time.Second)
	for {
		select {
		case <-time.After(600 * time.Millisecond):
			// Send the pesky signal that toggle spinning
			// till infinity if #27520 is not fixed!!
			cmd.Process.Signal(syscall.SIGIO)
			log.Println("Sent SIGIO")

		case <-unfixedTimer.C:
			log.Println("Unfortunately the issue hasn't yet been fixed!")
			cmd.Process.Signal(syscall.SIGKILL)
			return

		case err := <-doneCh:
			if err != nil {
				log.Printf("The program returned but unfortunately with an error: %v", err)
			} else {
				log.Println("Hooray, the issue is fixed!!")
			}
			return
		}
	}
}
``` 

## Results
* On unpatched versions of Go
```shell
$ go run main.go 
2018/09/12 11:48:33 Sent SIGIO
2018/09/12 11:48:34 Sent SIGIO
2018/09/12 11:48:35 Sent SIGIO
2018/09/12 11:48:35 Sent SIGIO
2018/09/12 11:48:36 Sent SIGIO
2018/09/12 11:48:36 Sent SIGIO
2018/09/12 11:48:37 Unfortunately the issue hasn't yet been fixed!
```

* On patched versions of Go
```shell
$ go run main.go 
2018/09/12 11:49:03 Sent SIGIO
2018/09/12 11:49:04 Sent SIGIO
2018/09/12 11:49:04 Sent SIGIO
2018/09/12 11:49:05 Hooray, the issue is fixed!!
```

With that, I've mailed https://go-review.googlesource.com/c/go/+/135015

**Comment by mikesmitty** [comment]
Not sure if this is the right place for it, but on go1.13 I'm seeing this issue pop up again. In a CentOS 6 chroot on CentOS 7 x86_64 (using mock with the epel-6-x86_64 target).
```
--- FAIL: TestSpuriousWakeupsNeverHangSemasleep (2.86s)
    semasleep_test.go:51: Program failed to return on time and has to be killed, issue #27520 still exists
FAIL
FAIL    runtime 99.958s
```

**Comment by ianlancetaylor** [comment]
@mikesmitty This issue has been closed for almost a year and we think it is fixed.  Please open a new issue will full details.  Thanks.
