### ISSUE TITLE
strconv.ParseUint always returns a uint64

### ISSUE THREAD

**Issue by jmelchio** [golang/go#27522]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.11 on Darwin

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jorismelchior/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jorismelchior/devel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wv/tht2c2pn3md0dn1k5kncyrmr0000gn/T/go-build670195788=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
I was trying to convert a string to a uint using strconv.ParseUint and regardless of the bitsize I pass into the function the result is a uint64

If possible, provide a recipe for reproducing the error.
[playground sample](https://play.golang.org/p/ulcBKYu9AHi)

### What did you expect to see?
I expected to get a uint that matches the bitsize that I pass into the function

### What did you see instead?
I got a uint64 in each case

**Comment by dominikh** [comment]
The signature of strconv.ParseUint is `func ParseUint(s string, base int, bitSize int) (uint64, error)` – and it can only have that single signature; Go doesn't have function overloading. The bitSize argument limits the range of values, it doesn't affect the return type. Use an explicit type conversion if you need a type other than uint64.

**Comment by jmelchio** [comment]
Thanks, that makes sense. I did the conversion to to get to `uint` to get my code to work and conveniently forgot that overloading is not a thing in Go. I'll put more thought into it before opening an issue in the future.
