### ISSUE TITLE
cmd/go: vgo repository has stale snapshot - update, or indicate it is stale in README

### ISSUE THREAD

**Issue by thepudds** [golang/go#27530]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

vgo:
```
$ vgo version
go version go1.11 windows/amd64 vgo:devel +1b870077c8
```
### What did you expect to see?

vgo tracking go releases, as described here:

https://groups.google.com/d/msg/golang-dev/BizWQk-hfw4/JdhnnJdJDAAJ

> The main repo is now the source of truth for Go module support.
> The vgo repo is now auto-generated from the main repo by running update.bash.
> 
> The vgo command is meant to allow Go 1.10 users to try modules.
> It should behave exactly the same as the Go 1.11 go command,
> except that GO111MODULE defaults to on (not auto), and it does
> not run 'go vet' during 'go test' when using a Go 1.10 GOROOT.
> 
> We intend to run update.bash at each release milestone, but we missed
> last week's update for go1.11beta3. I'll send that out shortly, along with
> an update to the README.md.
> 
> I expect that vgo will continue to be updated alongside point releases of Go 1.11,
> to continue to allow Go 1.10 users to try modules as they exist in Go 1.11.

### What did you see instead?

Latest vgo commit:
`cmd/go: import from main repo at go1.11beta3`

```
$ go get -u golang.org/x/vgo

# 'go mod fix' still present in vgo, other newer commands missing:
$ vgo help mod
...
The commands are:

        edit        edit go.mod from tools or scripts
        fix         make go.mod semantically consistent
        graph       print module requirement graph
        init        initialize new module in current directory
        tidy        add missing and remove unused modules
        vendor      make vendored copy of dependencies
        verify      verify dependencies have expected content
```
Ideally vgo would be updated to align with the official 1.11 release. If not, ideally the README would be updated to indicate people should not use it for now.  Beta3 had some significant issues.

**Comment by myitcv** [comment]
cc @bcmills

**Comment by bcmills** [comment]
> Ideally vgo would be updated to align with the official 1.11 release.

Done.
