### ISSUE TITLE
doc/effective_go.html: select is not mentioned in control structures section

### ISSUE THREAD

**Issue by MaerF0x0** [golang/go#27549]
### What version of Go are you using (`go version`)?
N/A ,  see https://golang.org/doc/effective_go.html#control-structures 

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
opened effective go and searched for `select`

### What did you expect to see?
documentation about the nuances and patterns of usage for select:
* Frequently used within a "while loop" (`for {`) 
```go
 for  {
    select {
        case o := <-one:
           fmt.Println("one", o)
        case o := <- two:
           fmt.Println("two", o)
     }
}
```
* Chooses at random if multiple available
```go
one := make(chan bool)
two := make(chan int)
go func() { one <- true }
go func() { two <- 13 }
select {
   case o := <- one:
        fmt.Println("one", o)
   case o := <- two:
        fmt.Println("two", o)
}
// Output: will randomly output either "one true" or "two 13"
```

* timeout pattern: https://gobyexample.com/timeouts
* wait for N channels to close pattern: https://stackoverflow.com/a/13666733/1114274

personally, i prefer: 
```go
for o != nil && e != nil {
	select {
	case i, ok := <-o:
		if !ok {
			o = nil
		}
		fmt.Println("o", i)
	case i, ok := <-e:
		if !ok {
			e = nil
		}
		fmt.Println("e", i)
	}
}

```

### What did you see instead?
only one example in "Leaky Buffer" section? https://golang.org/doc/effective_go.html#leaky_buffer

**Comment by bcmills** [comment]
CC: @robpike @rsc

**Comment by MaerF0x0** [comment]
I didnt realize effective go was in the source! LMK if a PR is welcome as I could write something. 

This was brought to my attention as I've been mentoring a new go developer in my workplace and I was like "Just read effective go everything you need is there...".

**Comment by bcmills** [comment]
Yeah, not everything. (See also #25107.)

**Comment by robpike** [comment]
If any of the ideas mooted for Go 2 come to pass, the document will likely get a massive rewrite. Until then I'd prefer to leave the document alone. There are a number of outstanding issues but none pressing enough to worry about now.

It's not "everything". It's just the basics, with some style and background.
