### ISSUE TITLE
cmd/go: go.info.golang_org/x/crypto/curve25519.mladder: relocation target go.inf/.uint8 not defined

### ISSUE THREAD

**Issue by fancygo** [golang/go#27550]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jun.fan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jun.fan/gopkg:/home/jun.fan/fancy.game:/home/jun.fan/fancy.ws"
GOPROXY=""
GORACE=""
GOROOT="/home/jun.fan/go"
GOTMPDIR=""
GOTOOLDIR="/home/jun.fan/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jun.fan/testmode/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build618708293=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I use "github.com/gorilla/websocket" to build my server code by mod. But it failed and report a err.

### What did you expect to see?
build success

### What did you see instead?
go.info.golang_org/x/crypto/curve25519.mladder: relocation target go.inf/.uint8 not defined

**Comment by agnivade** [comment]
It seems like you are not pulling in the correct version of dependencies.

We need detailed repro steps to investigate this. How are you exactly getting the dependency ? Are you running in module mode ? Are there other dependencies ?

If possible kindly create a test repo with exact steps so that we can clone and get this error. Thank you.

**Comment by fancygo** [comment]
I am running in module mode, when I use other dependence, it can build. When I only use this websocket dependence, it can't build.

**Comment by agnivade** [comment]
Sorry, perhaps I wasn't clear. Without the code it is very difficult for us to debug and understand what is going on. Please give the sample code (or create a repo with it), and mention the _exact_ steps to get your error.

**Comment by akavel** [comment]
Got similar error, but cannot provide more info, as it is an internal product (even have to censor some stuff out, sorry...):

```
# foo/bar/baz.test
foo/bar/baz.Test_Something: relocation target go.builtin.error.Error not defined
foo/bar/baz.Test_Something_Else: relocation target go.builtin.error.Error not defined
```

This was in a `GO111MODULE=on go test -mod=vendor` in go1.11.3. Other tests in the 

For now I'm reporting after first noticed occurrence of this. Don't know yet if it'll repeat when running tests again. Will add if I know something more.
