### ISSUE TITLE
expvar: RemoveAll is used for tests only

### ISSUE THREAD

**Issue by wfernandes** [golang/go#27555]
### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

https://github.com/golang/go/blob/3e5b5d69dcdb82494f550049986426d84dd6b8f8/src/expvar/expvar_test.go#L21-L30

The comment for `expvar.RemoveAll()` says `This is for tests only.` So at the very least this function should be made private.

On the other hand, it would be useful to be able to remove a metric and perhaps "Reset" all metric variables. I understand that the underlying `sync.Map` is optimized for many reads and infrequent writes but we could add godoc to make it clear that the "Reset" or "RemoveAll" would be expensive and should be used infrequently.

**Comment by bcmills** [comment]
> So at the very least this function should be made private.

It's only defined in the test itself, so nobody outside that test should be ably to use it anyway. Why does it matter whether it's exported?

**Comment by wfernandes** [comment]
At first I thought that too, but since the test is referencing the global `vars` variable, the tests are actually in the `expvar` package and not the `expvar_test` package. 
Maybe I'm misunderstanding something because I don't see it in the godoc as well. Maybe having it defined inside a `_test.go` file is enough to hide it away.

On the other hand it would be nice to have the ability to reset the `vars` entirely.

**Comment by ianlancetaylor** [comment]
A function defined in a x_test.go file is not added to the package, and is not available to code that imports that package.  This is true even if the x_test.go is part of the package.

I don't think there is anything to do here, so closing.
