### ISSUE TITLE
os: TestClosedPipeRaceWrite fails on solaris-amd64-smartosbuildlet

### ISSUE THREAD

**Issue by tklauser** [golang/go#27566]
```
--- FAIL: TestClosedPipeRaceWrite (0.00s)
    pipe_test.go:140: using pipe write limit of 65537
    pipe_test.go:176: I/O on closed pipe unexpectedly succeeded
panic: Fail in goroutine after TestClosedPipeRaceWrite has completed
```
https://build.golang.org/log/ecf3e947caaa3976539a524f6b63f12fac0ea3a4

It used to pass occasionally in the past, but now it seems to fail on every build.

FWIW, `PIPE_BUF` is 512 on illumos/SmartOS: https://github.com/illumos/illumos-gate/blob/b075503f221374dd0495c40e8811d229cb9fdc74/usr/src/head/limits.h#L97

/cc @ianlancetaylor

**Comment by bradfitz** [comment]
I suspect there are just spinning processes in the background.

That builder isn't created & destroyed per build (in either a container or VM). It's just a process running in a loop.

/cc @dmitshur

**Comment by bradfitz** [comment]
I logged into our two Joyent SmartOS VMs and they seem fine. (nothing obviously spinning or disks full, etc)

**Comment by tklauser** [comment]
Seems to be fixed by https://golang.org/cl/152164 but the commit message did not reference this issue. Thus closing manually.

**Comment by ianlancetaylor** [comment]
Thanks.  Sorry about that.  I should have checked for an open issue.
