### ISSUE TITLE
cmd/gofmt: insert space between : and = when syntax error

### ISSUE THREAD

**Issue by jingyugao** [golang/go#27576]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
Yes,always.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gao/go:/Users/gao/xng/xngo"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9m/_jx550mn55x8mjzz6tgtnjph0000gn/T/go-build384560299=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
format *.go which is like this

```
package utils

func init() {
	a := 1
	_ = 
}
```

Yes,there is an syntax error.

### What did you expect to see?
I expect to see gofmt does nothing 

### What did you see instead?

```
package utils

func init() {
	a: = 1
	_ = 
}
```

gofmt insert a space between : and = .Sometimes when i open a big file with a syntax and press save，gofmt will change the code.Then i have to replace : = with := .

**Comment by ALTree** [comment]
Mh, I can't reproduce this:

```
$ cat test.go
package utils

func init() {
a := 1
_ =
}

$ gofmt test.go
test.go:6:1: expected operand, found '}'
test.go:7:2: expected ';', found 'EOF'

$ cat test.go 
package utils

func init() {
a := 1
_ =
}
```

What am I missing? Are you sure it's gofmt that is doing this?

**Comment by dav-m85** [comment]
I resolved my issue: it was a conflict between two formatting extensions in Visual Studio Code: ryannaddy.vscode-format and ms-vscode.go. I opened [an issue](https://github.com/TheColorRed/vscode-format/issues/11) for the first.

**Comment by jingyugao** [comment]
@dav-m85 Thank you for your hint,I got the annswer.I use vscode-format extension. Gofmt is running ok after I remove the vscode-format.Thanks!

**Comment by jingyugao** [comment]
I got why. Because I use vscode-format which ii conflicted with gofmt. Now gofmt is runniing well after I remove vscode-format
