### ISSUE TITLE
golang google cla checker is reporting ✅incorrectly

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#27575]
### What did you do?

I opened golang/scratch#29 with commit [678ef4683d36dc2c5e1ee7d5fb6b5d73e6276b2c](https://github.com/golang/scratch/commit/678ef4683d36dc2c5e1ee7d5fb6b5d73e6276b2c). That commit accidentally had it's author email set to `leigh@mcchouse.com`, which is not the email I use to contribute to Go.

<img width="823" alt="screen shot 2018-09-08 at 11 50 05 pm" src="https://user-images.githubusercontent.com/351529/45261991-f2e5b300-b3c1-11e8-9946-ac609e07cba8.png">

### What did you expect to see?

I expected to see the Google CLA checker to 🔴.

### What did you see instead?

The Google CLA checker responded with ✅.

<img width="789" alt="screen shot 2018-09-08 at 11 43 23 pm" src="https://user-images.githubusercontent.com/351529/45261985-ce89d680-b3c1-11e8-958f-d1ac59e42dfa.png">

### Note

I've updated golang/scratch#29 so that it has the email address I use to contribute to Go projects, but if you pull that commit or look at the [commit on Gerrit](https://go.googlesource.com/scratch/+/b8c2b3abd646415e76b7bc4f2444f357a9f825bc), you can see the original email.

**Comment by FiloSottile** [comment]
Your CLA on file has your GitHub username on it, and I assume that your @mcchouse.com email address is linked to your GitHub account, so the CLA bot connected the dots.
