### ISSUE TITLE
cmd/test2json: bad parsing of subtest names with quotes leads to bad "run" events

### ISSUE THREAD

**Issue by andreimatei** [golang/go#27582]
With this test:
```
func TestXXX(t *testing.T) {
	for _, name := range []string{`"a"`, `"b"`} {
		t.Run(fmt.Sprintf("foo:%s", name), func(t *testing.T) {
		})
	}
}
```

If the output is piped to `go tool test2json`, the output starts with:
```
{"Action":"run","Test":"TestXXX"}
{"Action":"output","Test":"TestXXX","Output":"=== RUN   TestXXX\n"}
{"Action":"run   testxxx/foo","Test":"\"a\""}
{"Action":"output","Test":"\"a\"","Output":"=== RUN   TestXXX/foo:\"a\"\n"}
{"Action":"run   testxxx/foo","Test":"\"b\""}
```

Notice the bad action (`run   testxxx/foo`) and test name.

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
Have not tried.

### What operating system and processor architecture are you using (`go env`)?
OSX.

**Comment by ALTree** [comment]
Reproducible on 1.11. Tentatively putting in the 1.12 milestone but maybe the fix should be considered for backports. This is similar to #23920 and the patch for that one was backported.

**Comment by ALTree** [comment]
Actually on tip I get:

```
{"Action":"run","Test":"TestXXX"}
{"Action":"output","Test":"TestXXX","Output":"=== RUN   TestXXX\n"}
{"Action":"run","Test":"TestXXX/foo:\"a\""}
{"Action":"output","Test":"TestXXX/foo:\"a\"","Output":"=== RUN   TestXXX/foo:\"a\"\n"}
{"Action":"run","Test":"TestXXX/foo:\"b\""}
{"Action":"output","Test":"TestXXX/foo:\"b\"","Output":"=== RUN   TestXXX/foo:\"b\"\n"}
{"Action":"output","Test":"TestXXX","Output":"--- PASS: TestXXX (0.00s)\n"}
{"Action":"output","Test":"TestXXX/foo:\"a\"","Output":"    --- PASS: TestXXX/foo:\"a\" (0.00s)\n"}
{"Action":"pass","Test":"TestXXX/foo:\"a\""}
{"Action":"output","Test":"TestXXX/foo:\"b\"","Output":"    --- PASS: TestXXX/foo:\"b\" (0.00s)\n"}
{"Action":"pass","Test":"TestXXX/foo:\"b\""}
{"Action":"pass","Test":"TestXXX"}
{"Action":"output","Output":"PASS\n"}
{"Action":"output","Output":"ok  \tcommand-line-arguments\t(cached)\n"}
{"Action":"pass"}
```

**Comment by mvdan** [comment]
@andreimatei have you tried using Go 1.11?

**Comment by andreimatei** [comment]
I had not tried it. I tried go1.11 now and indeed it seems to work (@ALTree you originally said 1.11 didn't work for you and now you say tip does, but it seems to you too that 1.11 work too, right? As in, I'm not fooling myself).
I should have tried go1.11 before, sorry about that
Feel free to close as far as I'm concerned if there's nothing to backport.

**Comment by ALTree** [comment]
> (@ALTree you originally said 1.11 didn't work for you and now you say tip does, but it seems to you too that 1.11 work too, right? As in, I'm not fooling myself

Yes, sorry. The first time I actually used the wrong toolchain and I mistakenly concluded the bug was in 1.11 too.

> Feel free to close as far as I'm concerned if there's nothing to backport.

Closing here, then.
