### ISSUE TITLE
x/tools/imports: does not know about "syscall/js"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#27590]
I've recently sent [CL 134176](https://golang.org/cl/134176) to update [zstdlib.go](https://github.com/golang/tools/blob/af9b995e7e6da8c597674d7f4d22b5fa47b7c3cb/imports/zstdlib.go) (the generated file that contains information about the Go standard library) to include the new Go 1.11 API additions.

However, `syscall/js` package wasn't added to the [GOROOT/api/go1.11.txt](https://github.com/golang/go/blob/3a18f0ecb5748488501c565e995ec12a29e66966/api/go1.11.txt) file that is used to generate zstdlib.go, so that's not enough to get `syscall/js` support into `goimports`.

Does anyone know if excluding `syscall/js` package from api/go1.11.txt was an intentional decision (because `syscall/js` is considered experimental and exempt from the Go compatibility promise), or an unintentional outcome?

If the latter, we should resolve this issue by first updating api/go1.11.txt, then regenerating `imports`.

If the former, then we need to make a decision of whether `x/tools/imports` should know about `syscall/js` anyway. If so, we can do some custom work here to get it in. I've done similar stuff for a [copy of `imports`](https://github.com/gopherjs/gopherjs.github.io/blob/0a9e241fc82d9a26d186bacf98daaa4a8c6bd7d0/playground/internal/imports/gen.go#L1) used by the GopherJS Playground, so I'm happy to do it.

/cc @neelance @bradfitz @josharian @andybons

**Comment by bradfitz** [comment]
I tried to add it to API/go1.11.txt but it was after the freeze and it ended up nontrivial so I didn't rush it.

For now I'd hard code the entries in goimports.
