### ISSUE TITLE
API for disabling Windows cmd QuickEdit mode 

### ISSUE THREAD

**Issue by suoigwg** [golang/go#27609]
If Windows quick edit mode is on,  If you have a batch script running, selecting text in the console will pause the script execution until the text is deselected. This can be a problem if the script is expected to continue without pause.[source](https://stackoverflow.com/questions/21805712/windows-batch-how-to-disable-quickedit-mode-for-individual-scripts)

According to another post on stackoverflow,  C# provides api for disabling quick edit mode from console programmatically. Dose/will go have such apis?
[C# api](https://stackoverflow.com/questions/13656846/how-to-programmatic-disable-c-sharp-console-applications-quick-edit-mode)

**Comment by davecheney** [comment]
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by as** [comment]
This question has an (unintentionally) misleading synopsis: The script "pausing" behavior does *not* actually suspend the process. 

It instead puts the console in a hold mode where write it refuses to read from the process's standard file descriptors. This _may_ block your program on a write to the console depending on how you're logging the output, but it will not prevent other goroutines and the process from doing other things.
