### ISSUE TITLE
all: drop support for FreeBSD 10

### ISSUE THREAD

**Issue by tklauser** [golang/go#27619]
This came up during the review of https://golang.org/cl/114826. Deprecation of support for FreeBSD 10 was supposed to be announced in the Go 1.10 release notes according to https://github.com/golang/go/issues/22911#issuecomment-349171799

So I guess this means we should announce deprecation of FreeBSD 10 support in Go 1.12 and drop it in Go 1.13

/cc @bradfitz @paulzhol

**Comment by bradfitz** [comment]
This bug was titled "drop support for FreeBSD 10" but it was marked fixed by a CL that just documented that we plan to do this.

I'm going to reopen this and assign to Go 1.13.

**Comment by tklauser** [comment]
This was closed again due to the git history rewrite (https://groups.google.com/forum/#!topic/golang-dev/8JmYrD3DWY0). Reopening.

**Comment by andybons** [comment]
Nothing left to be done it seems.
