### ISSUE TITLE
cmd/go: 'go get github.com/Azure/azure-sdk-for-go@v5.0.0-beta' silently gets 'v20.1.0' instead

### ISSUE THREAD

**Issue by bcmills** [golang/go#27627]
Found while investigating #27457.

```
$ cd $(mktemp -d)

$ go mod init example.com
go: creating new go.mod: module example.com

$ go get github.com/Azure/azure-sdk-for-go@v5.0.0-beta

$ go list -m all
example.com
github.com/Azure/azure-sdk-for-go v20.1.0+incompatible

$ go version
go version go1.11 linux/amd64

$
```

**Comment by thepudds** [comment]
@bcmills  I don’t know if you’ve had a chance to look at this much yet, but do you have an initial guess or sense of what might be going on here, or maybe a guess around possible correlating factors, etc.?

**Comment by bcmills** [comment]
The underlying cause here is the same as #29121: if the requested package isn't found in the requested version, we're falling back to `latest` instead of emitting an error as we should.
