### ISSUE TITLE
runtime: TestGcSys fails on arm64

### ISSUE THREAD

**Issue by erifan** [golang/go#27636]
13:10:32 --- FAIL: TestGcSys (0.06s)
13:10:32     gc_test.go:30: expected "OK\n", but got "using too much memory: 71401472 bytes\n"
13:10:32 FAIL

This failure occurs randomly on arm64, skipping this test just like Windows does.

**Comment by ianlancetaylor** [comment]
CC @aclements

**Comment by mknyszek** [comment]
This should be fixed now as of aae0b5b.
