### ISSUE TITLE
cmd/go: "go mod vendor: malfored file path: invalid char '|'"

### ISSUE THREAD

**Issue by moul** [golang/go#27642]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.11 darwin/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/moul/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/moul/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/moul/go/src/github.com/moul/test2-go-mod-malformed-path/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v_/8mtm991n3wn4f688btpc0mbw0000gn/T/go-build185240075=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

1. create a repo with valid go files + non-go files containing `|` chars in filenames: https://github.com/moul/test-go-mod-malformed-path
2. create another repo that depends on the first one: https://github.com/moul/test2-go-mod-malformed-path
3. without `go mod`, you can `go build`
4. with `go mod`:
    ```console
    $ go mod vendor
    go: finding github.com/moul/test-go-mod-malformed-path latest
    go: extracting github.com/moul/test-go-mod-malformed-path v0.0.0-20180912153824-5c1104fa0b94
    -> unzip /Users/moul/go/pkg/mod/cache/download/github.com/moul/test-go-mod-malformed-path/@v/v0.0.0-20180912153824-5c1104fa0b94.zip: malformed file path "non-go-file-with-pipe|char.txt": invalid char '|'
    go: no dependencies to vendor
    ```

### What did you expect to see?

`go mod vendor` should success

### What did you see instead?

`go mod vendor` failing with the above message

**Comment by myitcv** [comment]
cc @bcmills
