### ISSUE TITLE
os: ModeType is missing os.ModeCharDevice

### ISSUE THREAD

**Issue by somersf** [golang/go#27640]
### What version of Go are you using (`go version`)?
go1.11

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"
and
GOARCH="amd64"
GOOS="linux"

### What did you do?
I stat-ed a character device and analyzed the returned mode.

The `os/stat_linux.go` and `os/stat_darwin.go` implementations map a system stat value of `S_IFCHR` to `ModeDevice | ModeCharDevice`.  I did not check other platforms.

However, the `ModeType` mask defined in `os/type.go` (https://golang.org/pkg/os/#FileMode) doesn't include the `ModeCharDevice` bit.
Masking a mode with `ModeType` in order to recover the type from the mode doesn't allow `ModeDevice | ModeCharDevice` to be recovered.

```
package main

import (
    "fmt"
    "os"
)

func main() {
    path := "/dev/zero"
    info, err := os.Lstat(path)
    if err != nil {
        fmt.Printf("stat failed; %v\n", err)
        return
    }
    mode := info.Mode()

    const charDev = os.ModeDevice | os.ModeCharDevice
    if mode & charDev == charDev {
        fmt.Printf("%s has character device bits set\n", path)
    }

    if mode & os.ModeType == charDev {
        fmt.Printf("%s type is character device\n", path)
    } else if mode & os.ModeType == os.ModeDevice {
        fmt.Printf("%s type is other device\n", path)
    }
}
```
https://play.golang.org/p/lcciw1JFCtj

### What did you expect to see?
```
/dev/zero has character device bits set
/dev/zero type is character device
```

### What did you see instead?
```
/dev/zero has character device bits set
/dev/zero type is other device
```

**Comment by tklauser** [comment]
FWIW, in [`archive/zip.fileModeToUnixMode`](https://golang.org/src/archive/zip/struct.go#L322) this also leads to the character device bit not represented correctly.

`os.ModeCharDevice` was added by @rsc in https://golang.org/cl/5531052, but nothing indicates why it was omitted from `os.ModeType`. Maybe just an oversight?
