### ISSUE TITLE
cmd/go: go get fails when fetching large repo

### ISSUE THREAD

**Issue by ryandbump** [golang/go#27646]
### What version of Go are you using (`go version`)?
```
go version go1.11 darwin/amd64
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details>
<summary>go env</summary>
<pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ryanbump/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ryanbump/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ryanbump/code/devolate/test-oversize/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fn/lp9kz_ms6k353f9ml2j49rlw0000gn/T/go-build776699926=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

### What did you do?
I created a repo `github.com/ryandbump/test-oversize` to recreate an issue I ran into when using `go get`. The`test-oversize` repo has 600M of junk txt files in it to increase it's size. There are also a few branches (`junk-580M`, `junk-560M`, etc.) that have different amounts of these junk text files to allow for testing with variable size repo.

In a module aware project run the following steps to reproduce.
- run `go get github.com/ryandbump/test-oversize`
- run `go get` for each of the different size branches.

### What did you expect to see?
I expected to see the package downloaded and cached for use with my project.

### What did you see instead?
An error was raised that implied there was a GOPATH issue despite using `go get` in a module aware context. The command would only succeed once the repo was below 500M in size. 
```
$ go get github.com/ryandbump/test-oversize
go: finding github.com/ryandbump/test-oversize latest
go: downloading github.com/ryandbump/test-oversize v0.0.0-20180912214615-996567b1f368
go get: no install location for directory  outside GOPATH
	For more details see: 'go help gopath'
```

**Comment by agnivade** [comment]
@bcmills @myitcv

**Comment by myitcv** [comment]
@ryandbump please can you report the output with `-x` added?

**Comment by ryandbump** [comment]
```
$ go get -x github.com/ryandbump/test-oversize
# /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869 for git2 https://github.com/ryandbump/test-oversize
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git ls-remote -q https://github.com/ryandbump/test-oversize
0.296s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git ls-remote -q https://github.com/ryandbump/test-oversize
go: finding github.com/ryandbump/test-oversize latest
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' 996567b1f368c1a266b531d0dbbdf78423702b06
0.027s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' 996567b1f368c1a266b531d0dbbdf78423702b06
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git cat-file blob 996567b1f368c1a266b531d0dbbdf78423702b06:go.mod
0.019s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git cat-file blob 996567b1f368c1a266b531d0dbbdf78423702b06:go.mod
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git tag -l
0.016s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git tag -l
go: downloading github.com/ryandbump/test-oversize v0.0.0-20180912214615-996567b1f368
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' 996567b1f368
0.011s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' 996567b1f368
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git cat-file blob 996567b1f368c1a266b531d0dbbdf78423702b06:go.mod
0.011s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git cat-file blob 996567b1f368c1a266b531d0dbbdf78423702b06:go.mod
cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 996567b1f368c1a266b531d0dbbdf78423702b06
3.225s # cd /Users/ryanbump/go/pkg/mod/cache/vcs/6d6322ff4148cd25804c23b7a0d9203f2ab1b2e7468d2f12c3b9b65900cf8869; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 996567b1f368c1a266b531d0dbbdf78423702b06
go get: no install location for directory  outside GOPATH
	For more details see: 'go help gopath'
```

**Comment by hyangah** [comment]
https://github.com/golang/go/blob/808186203b9786c11073c7056767fdf82f49def6/src/cmd/go/internal/modfetch/codehost/codehost.go#L30

The error message is not very helpful. It seems to be reached the internal limit.

**Comment by bcmills** [comment]
> I created a repo `github.com/ryandbump/test-oversize` to recreate an issue I ran into when using `go get`.

What is the real issue you ran into? (Did the Go source files and testdata for the module overrun the 500MiB limit, or was our `git` command producing a zip archive containing irrelevant data?)
