### ISSUE TITLE
x/crypto/acme/autocert: Safari cannot access the server when enabling http/2 by default

### ISSUE THREAD

**Issue by mkfsn** [golang/go#27651]
### What version of Go are you using (`go version`)?

```
go version go1.10.3 linux/amd64
```

Also I'm using docker `golang:1.10`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOOS="linux"
```

### What did you do?

I'm using [go-gin](https://github.com/gin-gonic/gin) and [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) to serve my website (using letsencrypt for https cert), and suddenly I cannot access my website after updating the autocert package (I used govendor to fetch the latest).

I got `NSPOSIXErrorDomain:100` from Safari on my macbook(10.13.6):

![image](https://user-images.githubusercontent.com/667169/45472825-f2556f80-b767-11e8-8af7-ff66e54b2c14.png)

which most likely a HTTP/2 problem as I found some discussions:

- https://help.poralix.com/articles/iphone-does-not-open-https-site-safari-nsposixerrordomain

Also, I didn't install any plugin in my Safari on macbook, and my Chrome on iPhone doesn't work.

Then I found this commit (https://github.com/golang/crypto/commit/850760c427c516be930bc91280636328f1a62286) which leads to the problem I have, and if I use the previous commit then there's no problem.

### What did you expect to see?

I can use Safari to view my website (I'm using Safari `11.1.2`).

Or I can configure the tls.Config rather then seeing it's hardcoded.

### What did you see instead?

I cannot use Safari to view my website.

**Comment by x1ddos** [comment]
Does it work with Safari on desktop?

Anyway, not sure about iphone. @bradfitz?

**Comment by bcmills** [comment]
(CC @FiloSottile)

**Comment by mkfsn** [comment]
@x1ddos Sorry I didn't describe it correctly.

My Safari on my macbook (10.13.6), and Chrome on my iPhone didn't work.

**Comment by x1ddos** [comment]
> My Safari on my macbook (10.13.6), and Chrome on my iPhone didn't work.

Ah ok  but some others browsers did work for you, right? Just to make sure your server works.

**Comment by mkfsn** [comment]
@x1ddos Yes, Chrome 69 and Firefox 62 on macbook did work for me.

**Comment by FiloSottile** [comment]
Does your go-gin setup cause HTTP/2 to be disabled? From the autocert docs:

```
// The returned listener uses a *tls.Config that enables HTTP/2, and
// should only be used with servers that support HTTP/2.
```

**Comment by mkfsn** [comment]
Here's how I use autocert to serve HTTP:

```go
// handler := gin.New()
// And I'm using go-gin `v1.1.4`.
http.Serve(autocert.NewListener(config.Domains...), handler)
```

If I read it correctly, [http.Serve](https://godoc.org/net/http#Serve) will enable HTTP/2 support if the Listener returns *tls.Conn connections which autocert Listener do provide it.

Now I'm starting to get confused - if the http server, autocert, and the browser (Safari) do support HTTP/2, why's that commit breaks my Safari? I was thinking that the problem was because I didn't enable HTTP/2 by default while  autocert enable HTTP/2 by default ...

Do you have any suggestion or advice?

**Comment by mkfsn** [comment]
Ah, sorry for the unclear "not working" situation in the description, my apologies.

Actually the main problem is triggered by a redirect - I can access my website but if I tried to login, I'll get a redirect to another domain, in this case Safari doesn't work.

For example, I have two domains:

- example.com
- admin.example.com

and here's the flow:

1. Access https://example.com/
2. Sign in
3. Server send redirect to https://admin.example.com/ if success
4. Access https://admin.example.com/

Using Chrome and Firefox on my macbook, I have no problem with this flow. But using Safari, I just get `NSPOSIXErrorDomain:100` in step 3.

---

I also did specify all domains in `config.Domains`:

```golang
http.Serve(autocert.NewListener(config.Domains...), handler)
```

**Comment by mkfsn** [comment]
Just checked that if I remove "h2" in autocert package then there's no problem, so it must be something http/2 related.

I think it would be better that `autocert` could provide a method that won't enable http/2 by default.

**Comment by x1ddos** [comment]
> Actually the main problem is triggered by a redirect - I can access my website but if I tried to login, I'll get a redirect to another domain, in this case Safari doesn't work.

Feels more like an application layer to me?

> Using Chrome and Firefox on my macbook, I have no problem with this flow. But using Safari, I just get NSPOSIXErrorDomain:100 in step 3.

Sounds more like a bug in Safari maybe?

> I think it would be better that autocert could provide a method that won't enable http/2 by default.

But there is! https://godoc.org/golang.org/x/crypto/acme/autocert#example-Manager

**Comment by mkfsn** [comment]
@x1ddos The example you provide doesn't work for me. The TLSConfig() method is returning a config that contains "h2" in the `NextProtos`:

https://sourcegraph.com/github.com/golang/crypto/-/blob/acme/autocert/autocert.go#L210

which then enable http/2, if I read it correctly. Also it works if I remove the "h2" in the `NextProtos`.

---

But yes, it might be a webkit problem as only the following browsers don't work:
- Safari 11.1.2 on macOS 10.13.6
- Chrome (latest) on iOS 11.3.1

while the following browsers do work:
- Chrome (latest) on Android 8.0.0
- Firefox (latest) on Android 8.0.0
- Chrome 69 on macOS 10.13.6
- Firefox 62 on macOS 10.13.6

**Comment by mkfsn** [comment]
@x1ddos Ah sorry, I think I had some misunderstandings, it works for me now if I configure the TLSConfig myself, thanks!

**Comment by mkfsn** [comment]
I think I found the root cause of this issue, it's actually a gzip problem led Safari shows that error. Closing this as this is not related to go, thank you for your help and sorry for the misunderstanding.
