### ISSUE TITLE
A = nil, A = B, B != nil with pointers and interface (explanation required)

### ISSUE THREAD

**Issue by andreasph** [golang/go#27654]
### What version of Go are you using (`go version`)?
the one on go playground

### Does this issue reproduce with the latest release?
if the go playground has the latest release yes

### What operating system and processor architecture are you using (`go env`)?
not applicable

### What did you do?
https://play.golang.org/p/jM2mOSkKo-a

### What did you expect to see?
either be printed:
```
interfaceSlice[1] == ps[1]
ps[1] == nil
interfaceSlice[1] == nil
```

or only:
```
ps[1] == nil
```

### What did you see instead?
printed:
```
ps[1] == nil
interfaceSlice[1] == ps[1]
```

I'd like to have some explanation about the reason for this

**Comment by dominikh** [comment]
https://golang.org/doc/faq#nil_error

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Comment by andreasph** [comment]
sorry @dominikh , thanks for the guidelines
