### ISSUE TITLE
cmd/go: go mod tidy removes an in-use indirect dependency from go.mod

### ISSUE THREAD

**Issue by zombiezen** [golang/go#27664]
### What version of Go are you using (`go version`)?

go version go1.11 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/light/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/light"
GOPROXY=""
GORACE=""
GOROOT="/home/light/sdk/go1.11"
GOTMPDIR=""
GOTOOLDIR="/home/light/sdk/go1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/light/src/github.com/google/go-cloud/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build947809198=/tmp/go-build -gno-record-gcc-switches"
```

It should be noted I'm running with `GO111MODULE=on`.

### What did you do?

```
export GO111MODULE=on
git clone https://github.com/google/go-cloud.git
cd go-cloud
git checkout 64759c9ac3d4068c1e322814b088ba08a8ee360f
go mod tidy
```

### What did you expect to see?

`go mod tidy` keeps `gopkg.in/yaml.v2`, an indirect dependency.

### What did you see instead?

`go mod tidy` removes `gopkg.in/yaml.v2` from go.mod, but not from go.sum.

Intriguingly, running `go mod why gopkg.in/yaml.v2` yields:

```
# gopkg.in/yaml.v2
github.com/google/go-cloud/internal/testing/replay
github.com/dnaeon/go-vcr/cassette
gopkg.in/yaml.v2
```

/cc @bcmills

**Comment by bcmills** [comment]
Do the other dependencies in the `go.mod` file imply any version of `gopkg.in/yaml.v2`?

**Comment by zombiezen** [comment]
`github.com/dnaeon/go-vcr` seems to, as it includes Gopkg.{lock,toml}. But it was my understanding/expectation that `go mod tidy` should include all indirect dependencies now, regardless of whether they could be inferred from other dependencies. (I forget where I gained this notion.)

**Comment by bcmills** [comment]
No, `go mod tidy` includes
* all of the *direct* dependencies, plus
* the subset of indirect dependencies that have been upgraded past their otherwise-implied versions.

**Comment by bcmills** [comment]
I think this is working as designed, but please reopen if you disagree.

**Comment by zombiezen** [comment]
Very possibly. I could have sworn @rsc said that a go.mod file after `go mod tidy` would reflect all the dependencies (so you wouldn't have to run `go list` etc.), but I can't find a citation now.

**Comment by leighmcculloch** [comment]
@bcmills Could you elaborate on what you mean by `otherwise-implied versions`? I don't understand what that means, what is an implied version in the context of minimal version selection?

I'm interested in this because I'm seeing this same thing happen specifically with the same yaml package. When I was dependent on `github.com/stretchr/testify@976c720a22c8` my `go.mod` has `gopkg.in/yaml.v2 v2.2.2 // indirect` in it. When I upgrade to `github.com/stretchr/testify@v1.4.0` the yaml lines is removed from `go.mod`, but remains in `go list -m all` output.

**Comment by bcmills** [comment]
@leighmcculloch, `github.com/stretchr/testify` `v1.4.0` explicitly `require`s `gopkg.in/yaml.v2 v2.2.2` ([here](https://github.com/stretchr/testify/blob/221dbe5ed46703ee255b1da0dec05086f5035f62/go.mod#L7)).

In contrast, `github.com/stretchr/testify` `976c720a22c8` does not even have a `go.mod` file, so it imposes no requirements on the module graph, and your own module's `go.mod` file has to fill in `// indirect` entries for the missing dependencies.

**Comment by leighmcculloch** [comment]
@bcmills Thanks, that makes a lot of sense. In theory then as modules become the norm if all modules were to have a `go.mod` file, no `go.mod` file would have an `// indirect` entry? And this also is the reasoning behind why it's important for us to use `go list -m all` and `go mod graph` to validate what dependencies we have?

**Comment by bcmills** [comment]
Over time the `// indirect` entries should drop to only those requirements that are actually _increased_ by the main module. And yes, this is why it's important to use `go list` or `go mod graph` instead of treating the `go.mod` file as a complete list of dependencies.
