### ISSUE TITLE
runtime: TestSpuriousWakeupsNeverHangSemasleep doesn't build on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#27662]
CL [135015](https://golang.org/cl/135015) added TestSpuriousWakeupsNeverHangSemasleep. This test is failing on Plan 9 because syscall.SIGIO is not defined.

```
# runtime_test [runtime.test]
go/src/runtime/semasleep_test.go:74:23: undefined: syscall.SIGIO
FAIL	runtime [build failed]
```
See https://build.golang.org/log/a16a3aa8831cb7b424c37ccb0ce84a88ca27b5dc

**Comment by odeke-em** [comment]
Thanks for catching that @0intro! Interestingly though yesterday it built successfully https://go-review.googlesource.com/c/go/+/135015#message-01bdd240e139e50a967331d9c6095945f2ce702f

**Comment by 0intro** [comment]
Unfortunately, the plan9 trybot has been disabled a while ago. The misc-compile-plan9 trybot only builds Go, without running the tests. However, the tests are only built when executed.
That's why this oversight hasn't been catched by the trybot.

**Comment by odeke-em** [comment]
Gotcha, thanks for the fix @0intro!
