### ISSUE TITLE
x/tools/godoc: type Cookie (net/http) doesn't generate a header

### ISSUE THREAD

**Issue by nickkeets** [golang/go#27674]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin, amd64

### What did you do?

1. Go to: https://tip.golang.org/pkg/net/http/
2. Click on the index link for `type Cookie`: https://tip.golang.org/pkg/net/http/#Cookie

### What did you expect to see?
Go down to the anchor point for type Cookie

### What did you see instead?
Link doesn't work and if you manually scroll down to find it, there is no header generated.

This doesn't seem to be a problem with the doc comment itself. If I change the type name (and respectively the doc comment) to something else (e.g. Cookie2), godoc works.

**Comment by agnivade** [comment]
Works for me. When you say "there is no header generated", do you mean you are not seeing the `type Cookie` in a light blue background at all ?

**Comment by nickkeets** [comment]
Yes, the blue background would not generate at all and thus the <a> anchor would not work at all. It didn't occur to me that it would be a browser issue, but after your comment I investigated more and realized that this was caused by uBlock origin on my browser!

Apologies for the noise.
