### ISSUE TITLE
that Struct I want to ..（just a suggestion）

### ISSUE THREAD

**Issue by lluck42** [golang/go#27676]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9
### What did you do?
is just a suggest,
let's see thus,

type struct Foo {
     Mywork struct bar{
         Name string
     }
}
var mywork Foo  #this is true
var mywork Foo.Mywork #this is false

### What did you expect to see?

var mywork Foo.Mywork #this is true
I think it's so cool to use struct like 'json'
like this:
type struct Fo{
    struct Foo{
       struct Fooo
    }
} 
var bar Fo.Foo.Fooo

**Comment by agnivade** [comment]
Hi @lluck42 ,

What you are suggesting is a language change. Typically these have to go through the proposal process (https://golang.org/s/proposal). You have to write up a proposal which is then evaluated and accepted/rejected.

I would request you to see the link above and write a proper proposal if you want your request to be accepted. Thank you.
