### ISSUE TITLE
wire: types get lowercased to generate var names, which can conflict with keywords

### ISSUE THREAD

**Issue by landism** [golang/go#27688]
#### What did you do?
Attempted to use wire to inject an object of type `rest.Interface` (from k8s client-go).
Repro available here https://github.com/landism/go-cloud/tree/landism/keyword_bug/wire/bug
(cd wire and run `wire ./bug`)

#### What did you expect to see?
wire successfully create a file named wire_gen.go that constructs a `Foo`.

#### What did you see instead?
```
$ wire ./bug
11:2: expected expression (and 5 more errors)
wire: generate failed
```

1. wire generates code containing `interface := ProvideInterface()`. Since `interface` is a go keyword, go fails to parse this when wire tries to fmt its output.
2. aside from the problems with selecting the name `interface`, it might also be worth fixing the error output (not sure if this is worth a separate issue). To figure out why wire wasn't working for me, I modified wire to output the pre-formatted source, which I then fed directly into gofmt which gave me all five errors instead of just the first, though they still wouldn't have been actionable if I hadn't modified wire to get the unformatted source.

#### Does this issue reproduce with the latest release (go1.11)?
I repro'd when building wire from HEAD of master, but I haven't tried with go1.11.

#### System details

```
go version go1.10.3 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/matt/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/matt/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0t/c8t9m67j7qs4y021nl5_3_yr0000gp/T/go-build546913191=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.10.3 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by ianlancetaylor** [comment]
What is wire?  Where does it come from?

**Comment by landism** [comment]
Apologies. The go-cloud's project's new issue form instructed me to run `go bug` to pre-populate an issue with a template, and I failed to notice which repo it was opening an issue against. Closing this and reopening there.
