### ISSUE TITLE
cmd/go: add a 'go mod tidy' mode that only verifies whether changes are needed

### ISSUE THREAD

**Issue by bcmills** [golang/go#27682]
Maintainers of large projects will often want to ensure that their module definitions are both complete and minimal at commit time (example: https://github.com/golang/go/issues/27643#issuecomment-421201463).

`go mod tidy` is the obvious command to verify that a definition is complete and minimal, but it makes changes even when `-mod=readonly` is set (#26850). As far as I am aware, there is no way to verify (nondestructively) that a definition is minimal — only that it is complete (`go list all -mod=readonly`), and even then only subject to the current `GOOS`, `GOARCH`, and build tags.

If we decide not to change the behavior of `go mod tidy -mod=readonly`, I think it's important that we provide some other command that would be suitable for use in a commit hook (along the lines of `gofmt -l`).

**Comment by kaedys** [comment]
I rather like the idea of simply adding the `-l` flag to `go mod tidy` and have it work the exact same as it does for `gofmt` (and `goimports`).

**Comment by rsc** [comment]
`go mod tidy -n` seems fine. (The go command already uses -n for these things.)

**Comment by rsc** [comment]
Dup of #27005?

**Comment by bcmills** [comment]
> Dup of #27005?

Yep, looks like it.
