### ISSUE TITLE
x/build: build.golang.org dashboard with “show only first-class ports” checked displays more than just first-class ports

### ISSUE THREAD

**Issue by bcmills** [golang/go#27689]
When I check “show only first-class ports” on https://build.golang.org/#short, the list of matching builders is still quite long:

![screenshot 2018-09-14 at 14 51 23](https://user-images.githubusercontent.com/5200974/45569558-d916f680-b82d-11e8-85ee-4febda541e44.png)

----

I had assumed that it would be restricted to the list of ports on https://golang.org/wiki/PortingPolicy#first-class-ports, but in fact that list is much, much shorter:

![screenshot 2018-09-14 at 14 51 46](https://user-images.githubusercontent.com/5200974/45569595-f51a9800-b82d-11e8-83c6-2b8cbd912577.png)

----

To avoid confusion, they should be made consistent: if the ports in the builder really are first-class, they should be listed on (or linked from) the wiki page, and if they aren't, they should be filtered out of the dashboard view.

(Discovered via https://github.com/golang/go/issues/27686#issuecomment-421446809.)

**Comment by bcmills** [comment]
(CC @dmitshur @bradfitz)

**Comment by dmitshur** [comment]
I can fix the discrepancy, but I'll need the decision of which are to be considered first-class vs not.

Here's the current first-class port list from build.golang.org in text form:

darwin/386:
- [ ] darwin-386-10_11

darwin/amd64:
- [ ] darwin-amd64-10_10
- [ ] darwin-amd64-10_11
- [ ] darwin-amd64-10_12

darwin/arm:
- [ ] darwin-arm-mg912baios

darwin/arm64:
- [ ] darwin-arm64-mn4m2zdaios

freebsd/386:
- [ ] freebsd-386-10_3
- [ ] freebsd-386-11_1

freebsd/amd64:
- [ ] freebsd-amd64-10_3
- [ ] freebsd-amd64-11_1

freebsd/arm:
- [ ] freebsd-arm-paulzhol

linux/386:
- [ ] linux-386
- [ ] linux-386-387
- [ ] linux-386-clang
- [ ] linux-386-sid

linux/amd64:
- [ ] linux-amd64
- [ ] linux-amd64-clang
- [ ] linux-amd64-longtest
- [ ] linux-amd64-nocgo
- [ ] linux-amd64-noopt
- [ ] linux-amd64-racecompile
- [ ] linux-amd64-sid
- [ ] linux-amd64-ssacheck
- [ ] linux-amd64-stretch

linux/arm:
- [ ] linux-arm
- [ ] linux-arm-arm5spacemonkey
- [ ] linux-arm-nativemake

linux/arm64:
- [ ] linux-arm64-packet

linux/mips:
- [ ] linux-mips

linux/mipsle:
- [ ] linux-mipsle

linux/ppc64:
- [ ] linux-ppc64-buildlet

linux/ppc64le:
- [ ] linux-ppc64le-buildlet

linux/s390x:
- [ ] linux-s390x-ibm

windows/386:
- [ ] windows-386-2008

windows/amd64:
- [ ] windows-amd64-2008
- [ ] windows-amd64-2012
- [ ] windows-amd64-2016

windows/arm:
- [ ] windows-arm

race:
- [ ] darwin-amd64-race
- [ ] freebsd-amd64-race
- [ ] linux-amd64-race
- [ ] windows-amd64-race
- [ ] android-386-emulator
- [ ] android-amd64-emulator
- [ ] android-arm-wiko-fever
- [ ] android-arm64-wiko-fever

**Comment by dmitshur** [comment]
/cc @toothrot In https://github.com/golang/go/issues/38874#issuecomment-625301840, you said:

> Somewhat related, as part of work to move the build dashboard into the coordinator (#34744), and have the "first-class ports" checkbox do the right thing on the UI, I hard-coded this field:
https://go.googlesource.com/build/+/refs/heads/master/cmd/coordinator/internal/dashboard/handler.go#29.

Based on that analysis, I understand that the "show only first-class ports" displaying more ports than are listed at https://golang.org/wiki/PortingPolicy#first-class-ports is simply a UI bug. If that's right, I understand we should be able to move this issue into NeedsFix state with the goal of fixing the UI bug on build.golang.org. Do you agree? Or do you think there is more that needs to be decided here?

**Comment by toothrot** [comment]
@dmitshur That is being fixed as part of #34744 (and is in-fact already fixed in the new UI, that is not yet feature complete)

**Comment by dmitshur** [comment]
Great!
