### ISSUE TITLE
cmd/compile: extra (confusing) error message after shift error

### ISSUE THREAD

**Issue by griesemer** [golang/go#27712]
```Go
package main

func main() {
	var s uint
	var _ interface{} = 1.0 << s
}
```
produces
```
prog.go:5:6: cannot use 1 << s as type interface {} in assignment
prog.go:5:26: invalid operation: 1 << s (shift of type float64)
```
on the playground (https://play.golang.org/p/lZceKWg78OH). The first error message is misleading and unnecessary. Should suppress once we know that the shift is invalid.

Not urgent.

**Comment by ALTree** [comment]
This appears to be fixed, the reproducer above now generates a single error line:

```
./prog.go:5:6: invalid operation: 1 << s (shift of type float64)
```

Closing here.
