### ISSUE TITLE
image.Decode doesn't work as expect 

### ISSUE THREAD

**Issue by MaeThird** [golang/go#27728]
I'm testing `image.Decode` with a truly **PNG file** with these pieces of code:

	logo,err := ioutil.ReadFile(os.Args[1]) 
	if err != nil{
		fmt.Println(err)
	}
	_ ,_ , err = image.Decode(bytes.NewReader(logo))
	if err != nil {
		fmt.Println(err)
	}
	_,err = png.Decode(bytes.NewReader(logo))
	if err != nil{
		fmt.Println(err)
	}

with **_,err = png.Decode(bytes.NewReader(logo))** appended the `image.Decode` **works well**,but when I commented out it like this : 

	logo,err := ioutil.ReadFile(os.Args[1]) 
	if err != nil{
		fmt.Println(err)
	}
	_ ,_ , err = image.Decode(bytes.NewReader(logo))
	if err != nil {
		fmt.Println(err)
	}

it errors and output is "**image: unknown format**"
**Why should this be happened ? Should I register all the decoder by hand so** `image.Decode `**can work correctly** ?

**Comment by bcmills** [comment]
See https://tip.golang.org/pkg/image/:

> Registration is typically automatic as a side effect of initializing that format's package so that, to decode a PNG image, it suffices to have
> 
> ```go
> import _ "image/png"
> ```
>
> in a program's main package. The _ means to import a package purely for its initialization side effects.

**Comment by MaeThird** [comment]
@bcmills Thanks.
