### ISSUE TITLE
runtime: TestCgoExecSignalMask flaky on s390x builder due to EAGAIN from fork/exec

### ISSUE THREAD

**Issue by mundaym** [golang/go#27731]
Seen a few times on the s390x builder:

https://build.golang.org/log/a1f9b5a3f3653242254a132003fbe000ce7ab8df
https://build.golang.org/log/8c8066abee8ba3c074a55593f936c4cff930f0b8
https://build.golang.org/log/a1c7bfaac1333926ec21f1ecbcc605872b582b99

**Comment by ianlancetaylor** [comment]
Let's just ignore `EAGAIN`.  I'll send a CL.
