### ISSUE TITLE
x/crypto/ssh/terminal: GetSize returns incorrect results

### ISSUE THREAD

**Issue by egazz** [golang/go#27743]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.11 windows/amd64

### Does this issue reproduce with the latest release?

Yes (since as far as I know this is the latest release).

### What operating system and processor architecture are you using (`go env`)?

Windows 10, amd64.  

### What did you do?

```
package main

import (
	"fmt"
	"os"
	"golang.org/x/crypto/ssh/terminal"
)

func main() {

	termID := int(os.Stdout.Fd())
	termWidth, termHeight, termSizeErr := terminal.GetSize(termID)
	
	if termSizeErr != nil {
	
		panic(termSizeErr)
		
	}
	
	fmt.Printf("Width: %v, height: %v", termWidth, termHeight)

}
```

### What did you expect to see?

Accurate height and width of the terminal.

### What did you see instead?

Height is way off.  My terminal window is 30 lines tall, but this returns a height of **9001**.  Width was correct, however.

In addition, I noticed that [this issue](https://github.com/golang/go/issues/20388) remains.  On Windows, getting the terminal handle via ```os.Stdin.Fd()``` results in an error, while ```os.Stdout.Fd()``` results in the above.  However, on Linux, using ```Stdin``` works properly.

**Comment by alexbrainman** [comment]
I think, it kind of works

![image](https://user-images.githubusercontent.com/9796621/45911995-32021280-be5e-11e8-9a37-2cc7eb635bc4.png)

There are many definitions of `terminal height and width`.

I looked at the code, and GetSize uses GetConsoleScreenBufferInfo Windows API. What should this package use instead? Why?

Thank you.

Alex

**Comment by alexbrainman** [comment]
> I don't know if it'd work on Windows, though.

That code does not run on Windows - note how first line of that source file says
```go
// +build !windows
```

Alex

**Comment by egazz** [comment]
That was my concern.  It looks, then, like the only way to get this information is sending a command such as ``stty`` via ``os.Stdin``?

But back to my original issue, at the least it seems like the documentation should make it clearer that ``GetSize`` in fact gets the *buffer* size, not the window size.  It's also worth noting that this behavior is different on Linux, where on at least some terminal emulators (such as urxvt) it returns the window size.

**Comment by alexbrainman** [comment]
> It looks, then, like the only way to get this information is sending a command such as `stty` via `os.Stdin`?

There is no stty command on Windows, if that is what you are suggesting.

Alex
