### ISSUE TITLE
Redundant handler call

### ISSUE THREAD

**Issue by msvarin** [golang/go#27745]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.11

### Does this issue reproduce with the latest release?
y

### What operating system and processor architecture are you using (`go env`)?
win 10 amd

### What did you do?

func main() {
	http.HandleFunc("/", h.Root)
	http.HandleFunc("/auth", h.Auth)
	http.HandleFunc("/page", h.Page)
	http.ListenAndServe(":8080", nil)
}

in Root handler:
log.Printf("LOG Root handler start")

browser: http://localhost:8080/page

and get message in console from both Page and Root handlers

(in browser only Page)

### What did you expect to see?
no message from Root handler

### What did you see instead?
have message

**Comment by davecheney** [comment]
This is not a bug, your browser is requesting /favicon.ico which is falling through to your root handler. 

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
