### ISSUE TITLE
cmd/compile: investigate proper use of Node.copy (reminder issue)

### ISSUE THREAD

**Issue by griesemer** [golang/go#27765]
Node.copy doesn't do anything special with Node.Orig. This can cause problems when the original node (n) is modified and n.Orig == n (that is, when n.Orig points to itself).

The code takes care of this at the call site at (cmd/compile/internal/gc/) const.go:1203 and also typecheck.go:2926 ( https://go-review.googlesource.com/c/go/+/136395 ). See also #26855.

Making the appropriate change in Node.copy (and remove the special handling outside) appears to introduce failures. Investigate.

cc: @mdempsky

**Comment by griesemer** [comment]
FWIW, cmd/compile/internal/types/type.go:725 (Type.copy) does exactly the expected Orig update for Type structs.

**Comment by mvdan** [comment]
This method originated from a cleanup: 19ee2ef9502795dd9517b6b7fa789922241d2a03

At the time, I simply did the bare minimum to simplify the code. Most of the old pieces of code left Node.Orig alone, so that wasn't changed.

**Comment by griesemer** [comment]
@mvdan Yes, I have seen that. I think your change was fine. This is a pre-existing problem.
