### ISSUE TITLE
x/image/bmp: unsupported BMP image

### ISSUE THREAD

**Issue by electricface** [golang/go#27767]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOOS="linux"
GOARCH="amd64"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```go
package main

import (
	"image"
	"log"
	"os"

	_ "golang.org/x/image/bmp"
)

func main() {
	f, err := os.Open("/path/to/desktop.bmp")
	if err != nil {
		log.Fatal(err)
	}
	img, str, err := image.Decode(f)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(img, str)
}
```

### What did you expect to see?
exit code is 0

### What did you see instead?
2018/09/20 10:45:39 bmp: unsupported BMP image
exit status 1

----------------
Because github does not support bmp, package bmp image files into compressed files.
[desktop.bmp.tar.gz](https://github.com/golang/go/files/2399400/desktop.bmp.tar.gz)

**Comment by yorelog** [comment]
the implement of bmp reader  [Package golang.org/x/image/bmp](https://github.com/golang/image/blob/e1a1ede6891c997b81b830dbc6f4d2850b9392a4/bmp/reader.go#L139-153) shows that bitmap info header size is fixed to 40, while  the header size can set by file header. 
```go
func decodeConfig(r io.Reader) (config image.Config, bitsPerPixel int, topDown bool, err error) {
	// We only support those BMP images that are a BITMAPFILEHEADER
	// immediately followed by a BITMAPINFOHEADER.
	const (
		fileHeaderLen = 14
		infoHeaderLen = 40
	)
	var b [1024]byte
	if _, err := io.ReadFull(r, b[:fileHeaderLen+infoHeaderLen]); err != nil {
		return image.Config{}, 0, false, err
	}
	if string(b[:2]) != "BM" {
		return image.Config{}, 0, false, errors.New("bmp: invalid format")
	}
	offset := readUint32(b[10:14])
	if readUint32(b[14:18]) != infoHeaderLen {
		return image.Config{}, 0, false, ErrUnsupported
	}
```
so, maybe we can implement the reader like this
```go
func decodeConfig(r io.Reader) (config image.Config, bitsPerPixel int, topDown bool, err error) {
    // We only support those BMP images that are a BITMAPFILEHEADER
    // immediately followed by a BITMAPINFOHEADER.
    const (
        fileHeaderLen = 14
    )
    var infoHeaderLen uint32 = 40 // infoHeaderLen can be a variable
    var b [1024]byte
    if _, err := io.ReadFull(r, b[:fileHeaderLen+infoHeaderLen]); err != nil {
        return image.Config{}, 0, false, err
    }
    if string(b[:2]) != "BM" {
        return image.Config{}, 0, false, errors.New("bmp: invalid format")
    }
    offset := readUint32(b[10:14])
    infoHeaderLen = readUint32(b[14:18]) // set infoHeaderLen from file header other than force compare with 40 
```

**Comment by bcmills** [comment]
CC @nigeltao

**Comment by nigeltao** [comment]
Yeah, x/image/bmp needs to speak more versions of the BMP file format.

I don't have a lot of spare time to look at this soon, but if anybody else wants to have a crack, here's a couple of spec-like documents:

http://www.digicamsoft.com/bmp/bmp.html
https://www.fileformat.info/format/bmp/egff.htm

Translating from Win32 to Go types:
SHORT = int16
LONG = int32
BYTE = uint8
WORD = uint16
DWORD = uint32

**Comment by mlesniak** [comment]
@yorelog Any progress? You haven't assigned yourself. If you are not actively working on it, I might give it a try, too ;-)

**Comment by yorelog** [comment]
@mlesniak  try it please .  I don’t have spare time this days .  But it seems someone else have this issue fixed . 
Also, you can compare this with Pillow package (python ) to improve it . 
Sorry for the inactive

**Comment by yorelog** [comment]
> Change https://golang.org/cl/141799 mentions this issue: `image/bmp: support v4 and v5 info header versions`

@mlesniak
