### ISSUE TITLE
Read len on a closed channel in a go routine is a Data Race

### ISSUE THREAD

**Issue by NBR41** [golang/go#27776]
### What version of Go are you using (`go version`)? 
go1.11 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"

### What did you do?

With this code :
https://play.golang.org/p/CjxvLH6cHut

### What did you expect to see?

As in the go1.10, no race detected.

### What did you see instead?

A race is detected : 

```
==================
WARNING: DATA RACE
Write at 0x00c0000a8000 by goroutine 7:
  runtime.closechan()
      /home/prod/go1.11/src/runtime/chan.go:327 +0x0
  main.main.func2()
      /tmp/test.go:23 +0x79

Previous read at 0x00c0000a8000 by goroutine 6:
  main.main.func1()
      /tmp/test.go:13 +0xbe

Goroutine 7 (running) created at:
  main.main()
      /tmp/test.go:18 +0x8b

Goroutine 6 (running) created at:
  main.main()
      /tmp/test.go:11 +0x69
==================
```

**Comment by randall77** [comment]
Dup of #27070
