### ISSUE TITLE
cmd/compile: panic in cmd/compile/internal/gc.typecheck1

### ISSUE THREAD

**Issue by CmdrVasquess** [golang/go#27771]
#### What did you do?
Working on my project BCplus (here on github) I changed the code then 'go build'

#### What did you expect to see?
Generally the build completes (sometimes with errors in my code, sometimes with success;)

#### What did you see instead?
I see ICE:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xb7bbae]

goroutine 1 [running]:
cmd/compile/internal/gc.typecheck1(0xc00048c300, 0x2, 0xa8c9bb)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:1270 +0x3ece
cmd/compile/internal/gc.typecheck(0xc00048c300, 0x2, 0xc000489701)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:238 +0x6ad
cmd/compile/internal/gc.typecheck1(0xc00048c480, 0x2, 0x5002000000005)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:584 +0x2c8a
cmd/compile/internal/gc.typecheck(0xc00048c480, 0x2, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:238 +0x6ad
cmd/compile/internal/gc.typecheck1(0xc00048c280, 0x1, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:2051 +0xaaf9
cmd/compile/internal/gc.typecheck(0xc00048c280, 0x1, 0xb8f17f)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:238 +0x6ad
cmd/compile/internal/gc.typecheckslice(0xc000058140, 0x5, 0x8, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:68 +0x50
cmd/compile/internal/gc.Main(0xcc0f50)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:518 +0x2059
main.main()
	/usr/local/go/src/cmd/compile/main.go:51 +0x96

#### System details

```
go version go1.11 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/marcus/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/marcus/gows"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
uname -sr: Linux 4.9.0-8-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.24-11+deb9u3) stable release version 2.24, by Roland McGrath et al.
gdb --version: GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
```

**Comment by agnivade** [comment]
It helps greatly if you link to the exact project or mention the exact steps to build it.

Is it this https://github.com/CmdrVasquess/BCplus ?

What are the exact steps to clone and build it ?

**Comment by CmdrVasquess** [comment]
https://github.com/CmdrVasquess/BCplus is the project that produces the crash. Take the commit f2593416ec5faa5155d1b0de256771b9abf088cb into a clean go environment. Then 'go build' makes the compile crash – at least on my machine.

**Comment by CmdrVasquess** [comment]
Could it be the return parameter name `len` that collides with the built-in function `len()`? See `webui/tpc_missions.go` line 87. With another name the thing compiles again!

**Comment by ALTree** [comment]
Smells like #27356 and #27433. Closing here as a dup.

**Comment by CmdrVasquess** [comment]
Just added some information as comment to the issue: Project Link, Git
commit label, go.mod
Am Donnerstag, den 20.09.2018, 01:14 -0700 schrieb Agniva De Sarker:
