### ISSUE TITLE
x/sys/unix: replace Perl scripts with Go programs

### ISSUE THREAD

**Issue by kevinburke** [golang/go#27779]
It would be good to remove the dependency on Perl in our core projects. It should also be easy to determine when a Go script is compatible with the existing Perl script, since it shouldn't generate a Git diff.

**Comment by randall77** [comment]
Also package `syscall` and `regexp/syntax`.

**Comment by kardianos** [comment]
Adding information if someone decides to start on this:
This has already been done for windows syscalls, the script for windows can be found here: `$GOROOT/src/syscall/mksyscall_windows.go`.

**Comment by bontibon** [comment]
Removing the Perl implementation of mksyscall was turned down in #3977.  Not sure if the feeling is still the same.

**Comment by randall77** [comment]
I don't think the argument there applies any more. The argument was "we don't want to depend on Go for bootstrapping". But that ship has sailed, we now depend on Go for bootstrapping in myriad ways.

**Comment by ebati** [comment]
Can i work on this?

**Comment by cherrymui** [comment]
Does it make porting to new platforms any harder? If Go hasn't work on the target machine, we cannot run Go program on it. Maybe it is enough to run the program on any host machine, with a cross C compiler and header files?

**Comment by tklauser** [comment]
`mksyscall.pl` doesn't necessarily need to be run on the `GOOS`/`GOARCH` for which to generate the new syscalls. So I think we wouldn't be making bootstrapping any harder if we rewrote `mksyscall.pl` in Go. Same goes for `mksysnum_*.pl` and `mksysctl_openbsd.pl` AFAICS.

/cc @ianlancetaylor @bradfitz

**Comment by bradfitz** [comment]
SGTM. I suspect we just didn't really have Go when it was written. There's no reason to keep it in Perl today.

**Comment by kevinburke** [comment]
@ebati I don't think anyone is working on this currently

**Comment by darkLord19** [comment]
I would love to work on this if no one is working on it. What is the function of mksyscall.pl currently in codebase? Besides any pointers about task would be very appreciated.

**Comment by kevinburke** [comment]
It generates the files in the golang.org/x/sys/unix package that have "DO NOT EDIT" written at the top of them.

**Comment by viswesr** [comment]
I am starting to work on this. I will refer the $GOROOT/src/syscall/mksyscall_windows.go implementation by @kardianos.  I understand no one is working on this. If there are any concerns, please let me know.

**Comment by viswesr** [comment]
The work in progress is maintained here: [mksyscall.go](https://github.com/viswesr/sys/blob/master/unix/mksyscall.go). Please read the daily [LOG](https://github.com/viswesr/fpl/blob/master/go-x-sys-unix-mksyscall-go-27779.md) . I will create a CL once complete.

**Comment by viswesr** [comment]
I have ported mksyscall.pl and few other Perl scritpts to Go programs. Please refer the CLs above. 

Could you please take a decision on the following Perl scripts if they need to be Ported as well:

**SYS:**

\#  | File | Comments/Status | Decision to Port
-----|------|----------|----------------------
1 | sys/unix/mksyscall.pl | Already ported. https://golang.org/cl/150217  | Accepted
2 | sys/plan9/mksyscall.pl | Not started/Same as mksyscall.pl? | Needs decision
3 | sys/unix/mksyscall_solaris.pl | Not started | Needs decision
4 | sys/unix/mksyscall_aix_ppc64.pl | Not started | Needs decision
5 | sys/unix/mksyscall_aix_ppc.pl | Not started | Needs decision
 |  |  | 
6 | sys/unix/linux/mksysnum.pl | Already ported.  https://golang.org/cl/151377 | Needs decision
7 | sys/unix/mksysnum_freebsd.pl | Not started | Needs decision
8 | sys/unix/mksysnum_netbsd.pl | Not started | Needs decision
9 | sys/unix/mksysnum_openbsd.pl | Not started | Needs decision
10 | sys/unix/mksysnum_dragonfly.pl | Not started | Needs decision
11 | sys/unix/mksysnum_darwin.pl | Not started | Needs decision
| | |
12 | sys/unix/mksysctl_openbsd.pl | Not started | Needs decision

**GO:**

\#   | File | Comments/Status | Decision to Port
-----|-----|-------------------------|----------------------
13 | go/src/regexp/syntax/make_perl_groups.pl |  https://golang.org/cl/151138 | Rejected. To retain existing Perl script. See CL 151138 for more information.
14 |go/src/syscall/mksyscall_libc.pl | Not started | Needs decision
15 |go/src/syscall/mksyscall.pl | Copy from sys repo  | Needs decision
| | |
16 |go/src/syscall/mksysnum_freebsd.pl | Copy from sys repo?  | Needs decision
17 |go/src/syscall/mksysnum_linux.pl | Copy from sys repo?  | Needs decision
18 |go/src/syscall/mksysnum_netbsd.pl | Copy from sys repo?  | Needs decision
19 |go/src/syscall/mksysnum_openbsd.pl | Copy from sys repo?  | Needs decision
20 |go/src/syscall/mksysnum_dragonfly.pl | Copy from sys repo?  | Needs decision
21 |go/src/syscall/mksysnum_darwin.pl | Copy from sys repo?  | Needs decision
| |
22 |go/src/syscall/mksysctl_openbsd.pl | Copy from sys repo?  | Needs decision

24. Bash scripts
sys/plan9/mkerrors.sh
sys/unix/mkerrors.sh
sys/plan9/mksysnum_plan9.sh

Thanks.

/cc @tklauser @ianlancetaylor @bradfitz

**Comment by ianlancetaylor** [comment]
I think all the scripts in sys/unix should be ported.  I wouldn't worry about the scripts in the syscall package; we're never going to run them again anyhow.

**Comment by deiga** [comment]
@viswesr 
I'm not entirely sure if this is the right place for this, but I just updated my dependencies and I started seeing:
`golang.org/x/crypto/ssh/terminal/util.go:20:2: found packages unix (aliases.go) and main (mksysnum.go) in vendor/golang.org/x/sys/unix`

This might as well be related to `x/ssh` package, but I'm not entirely sure.

**Comment by tklauser** [comment]
@deiga Thanks for reporting this. It should be fixed by golang/sys@c6cbdbf9e68a68b19802a5c44e537c284b9c8e1a (https://golang.org/cl/155748)

**Comment by viswesr** [comment]
@deiga Thanks for reporting and @cyphar for quick fix.
