### ISSUE TITLE
cmd/compile: race detector detects race with close(chan) and len(chan) [1.11 backport]

### ISSUE THREAD

**Issue by randall77** [golang/go#27778]
Considering backporting the fix for #27070 to 1.11.

This was an issue introduced in 1.11. The race detector reported a race between close(chan) and len(chan), where previously (in 1.10) it didn't.

The spec is silent on this issue, so it's technically ok to report a race here, but consensus was that it was worth fixing.  But is it worth backporting?
The fix is pretty simple. https://go-review.googlesource.com/c/go/+/135698

**Comment by randall77** [comment]
@andybons : What's the process for going from CherryPickCandidate to CherryPickApproved?

**Comment by andybons** [comment]
@randall77 someone on the OSP team reviews and marks whether it should be approved. Since @ianlancetaylor already said as much in https://github.com/golang/go/issues/27070#issuecomment-414101301, approving...
