### ISSUE TITLE
cmd/go: go mod download doesn't do anything if you give it a module without a version

### ISSUE THREAD

**Issue by natefinch** [golang/go#27783]
So, I didn't realize that go mod download required an `@version` at the end... I presumed it would default to `@latest` just like it would if you `import` a library without specifying a version in your go.mod.  However, instead, `go mod download` just silently fails.  

#### What did you do?
(in a directory outside GOPATH with a go.mod that did not include github.com/lib/pq)
`go mod download github.com/lib/pq`

#### What did you expect to see?
some version of lib/pq downloaded, or an error

#### What did you see instead?
nothing happened and no error

#### System details

```
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/finchnat/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/finchnat"
GOPROXY=""
GORACE=""
GOROOT="/Users/finchnat/sdk/go1.11"
GOTMPDIR=""
GOTOOLDIR="/Users/finchnat/sdk/go1.11/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/finchnat/dev/test/go.mod"
GOROOT/bin/go version: go version go1.11 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by natefinch** [comment]
Notably, I'd prefer "no version" to default to `@latest` ... but it at the very least should tell me I gave it something invalid.

**Comment by hyangah** [comment]
'go mod download' should report errors and failure if any. 
<pre>
$ go mod download somethingveryfake.com/fake
$
</pre>

**Comment by iWdGo** [comment]
Issue is related to #31237, an error message displays with the submitted fix which seems to solve the issue:
```
$GOPATH\src\mymod>set GO111MODULE=on

$GOPATH\src\mymod>goissue mod download rsc.io/doesnotexist
go: cannot find main module; see 'go help modules'
```
