### ISSUE TITLE
x/mobile: loadExportData failed go install 

### ISSUE THREAD

**Issue by rajkotraja** [golang/go#27781]
gomobile: loadExportData failed go install -p=1 -pkgdir=/go/pkg/gomobile/pkg_android_arm -tags OPEN            SSL -v -x -ldflags -X github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common.buildDate=2018-09-            20T18:09:38+00:00 -X github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common.buildRepo= -X githu            b.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common.buildRev= -X github.com/Psiphon-Labs/psiphon-            tunnel-core/psiphon/common.goVersion=go1.8 -X github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/c            ommon.gomobileVersion=+320ec40 -X github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common.depend            encies={"github.com/Psiphon-Inc/bolt":"c6e046a","github.com/Psiphon-Inc/crypto/curve25519":"22f3a6a            ","github.com/Psiphon-Inc/crypto/ed25519":"22f3a6a","github.com/Psiphon-Inc/crypto/ed25519/internal            /edwards25519":"22f3a6a","github.com/Psiphon-Inc/crypto/nacl/box":"22f3a6a","github.com/Psiphon-Inc            /crypto/nacl/secretbox":"22f3a6a","github.com/Psiphon-Inc/crypto/poly1305":"22f3a6a","github.com/Ps            iphon-Inc/crypto/salsa20/salsa":"22f3a6a","github.com/Psiphon-Inc/crypto/ssh":"22f3a6a","github.com            /Psiphon-Inc/dns":"d23cdaf","github.com/Psiphon-Inc/goarista/monotime":"d002785","github.com/Psipho            n-Inc/goptlib":"18963be","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon":"","github.com/Psiph            on-Labs/psiphon-tunnel-core/psiphon/common":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon            /common/osl":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/protocol":"","github.co            m/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/tls":"","github.com/Psiphon-Labs/psiphon-tunnel-c            ore/psiphon/common/tls/cipherhw":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/tls            /crypto/chacha20poly1305":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/tls/crypto            /chacha20poly1305/internal/chacha20":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common            /tls/crypto/curve25519":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/tls/crypto/p            oly1305":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/transferstats":"","github.com/Psip            hon-Labs/psiphon-tunnel-core/psiphon/upstreamproxy":"","github.com/Psiphon-Labs/psiphon-tunnel-core            /psiphon/upstreamproxy/go-ntlm/ntlm":"","github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/upstre            amproxy/go-ntlm/ntlm/md4":"","github.com/codahale/sss":"0cb9f6d","github.com/creack/goselect":"5885            4f7","github.com/juju/ratelimit":"59fac50","github.com/spacemonkeygo/openssl":"a66df3e","github.com            /spacemonkeygo/openssl/utils":"a66df3e","github.com/spacemonkeygo/spacelog":"2296661","github.com/z            ach-klippenstein/goregen":"795b5e3","golang.org/x/net/internal/socks":"26e67e7","golang.org/x/net/p            roxy":"26e67e7"}  -gcflags=-shared -ldflags=-shared github.com/Psiphon-Labs/psiphon-tunnel-core/Mob            ileLibrary/psi failed: exit status 2

**Comment by bcmills** [comment]
Please answer the questions from the issue template.
### What version of Go are you using (`go version`)?
### Does this issue reproduce with the latest release?
### What operating system and processor architecture are you using (`go env`)?
### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best
### What did you expect to see?
### What did you see instead?
