### ISSUE TITLE
database/sql: SetConnMaxLifetime may be ignored

### ISSUE THREAD

**Issue by AlekSi** [golang/go#27793]
https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime says:

> SetConnMaxLifetime sets the maximum amount of time a connection may be reused.
> Expired connections may be closed lazily before reuse.
> If d <= 0, connections are reused forever.

After reading that one can expect that `db.SetConnMaxLifetime(time.Nanosecond)` will prevent connection reuse. Yes, there is a "lazy" in the second sentence, but the first one is straightforward. 

But `SetConnMaxLifetime` silently rises to duration to `time.Second`: https://github.com/golang/go/blob/ce58a39fca067a19c505220c0c907ccf32793427/src/database/sql/sql.go#L890-L896

I propose to change the documentation to use a weaker language.

**Comment by kardianos** [comment]
A nanosecond is great then 0, so you get the lazy verbage. Maybe I'm wrong. I'll look at it more.

**Comment by kardianos** [comment]
@AlekSi I'm reading the documentation again, and I'm not sure I see your point of confusion. Do you have a suggestion for the language that would be clearer to you? If anything I would make the language stronger to state the 1s minimum timer.

**Comment by kardianos** [comment]
I think the documentation as it stands is correct. Also I think that the exact method we use may change in the future, so I'm happy with how it is.
