### ISSUE TITLE
net/http/cgi: TestEnvOverride fails with non-standard 'perl' command

### ISSUE THREAD

**Issue by LeGEC** [golang/go#27790]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

`go version go1.11 linux/amd64`

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gvarouchas/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gvarouchas/golib"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build117805775=/tmp/go-build -gno-record-gcc-switches"
```

Operating system is Ubuntu xenial 16.04.5

### What did you do?

From the go source directory, run the tests for "net/http/cgi" package

### What did you expect to see?

$ ../bin/go test net/http/cgi
ok    net/http/cgi

### What did you see instead?

```
# "../bin/go" is the built go command :
$ ../bin/go version
go version go1.11 linux/amd64

$ ../bin/go test net/http/cgi

2018/09/21 10:20:51 cgi: copy error: write tcp 127.0.0.1:33176->127.0.0.1:47778: write: connection reset by peer
/usr/bin/env: 'bash': No such file or directory
2018/09/21 10:20:51 cgi: no headers
--- FAIL: TestEnvOverride (0.00s)
    host_test.go:84: for key "env-REQUEST_URI" got ""; expected "/foo/bar"
    host_test.go:84: for key "env-PATH" got ""; expected "/wibble"
    host_test.go:84: for key "cwd" got ""; expected "/home/gvarouchas/go/src/net/http/cgi"
    host_test.go:84: for key "env-SCRIPT_FILENAME" got ""; expected "/home/gvarouchas/go/src/net/http/cgi/testdata/test.cgi"
2018/09/21 10:20:51 cgi: copy error: past write limit
2018/09/21 10:20:51 cgi: no headers
2018/09/21 10:20:51 cgi: missing required Content-Type in headers
2018/09/21 10:20:51 cgi: no headers
FAIL
FAIL	net/http/cgi	0.206s
```

I guess this issue is linked to the setup of my local machine (especially the "connection reset by peer" on a local connection), but I don't know where to start looking ?

**Comment by bcmills** [comment]
CC @bradfitz

**Comment by bcmills** [comment]
Any idea whether it is also failing in 1.10?

**Comment by bcmills** [comment]
@dmitshur, do/should we have a Xenial builder?

**Comment by agnivade** [comment]
I am unable to reproduce it. Using 16.04 too. From the error, it looks like you don't have `bash` ? That is strange because ubuntu comes with bash.

**Comment by LeGEC** [comment]
Should I update the issue's title ?

**Comment by bcmills** [comment]
@LeGEC, if you can reasonably update the test to work with your `perl` variant (or vice-versa), you're welcome to send a fix.

Since the rest of us don't have that wrapper, we can't test the potential fix against it — so I don't think anyone else will work on this if you don't.

**Comment by lufia** [comment]
*Plenv*'s *perl* is implemented in bash script that starts with `#!/usr/bin/env bash`.
And TestEnvOverride sets *PATH* to **/wibble**.
Thus path to a *perl* command is resolved to points to *plenv*'s *perl* in TestEnvOverride, but that *perl* can't find *bash* command because *PATH* is overwritten.
