### ISSUE TITLE
variadic parameter not work well

### ISSUE THREAD

**Issue by archever** [golang/go#27795]
### What version of Go are you using (`go version`)?
go1.10.3

### What operating system and processor architecture are you using (`go env`)?
the same to macbookpro2015

### What did you do?
<https://play.golang.org/p/tyV3T-pkUy6>

```golang
func test(i ...interface{}){}

a := []int{1,2,3}
test(a...)
// cannot use a (type []int) as type []interface {} in argument to test
```

why it can't be complied?  `a...` is not equal to `a[0], a[1], a[2]` ???

### What did you expect to see?
i suppose that ellipsis operator really split the slice and pass to the function as variadic parameter.
so make  code like above success to be complied

**Comment by robpike** [comment]
This is a variant of the topic explained here: https://golang.org/doc/faq#convert_slice_of_interface
