### ISSUE TITLE
cmd/link: temporary empty symbols are being stored in the ELF symbol table

### ISSUE THREAD

**Issue by grantseltzer** [golang/go#27800]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
`go version go1.10.3 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/grant/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/grant/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build731681085=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I was doing disassembly related research and noticed that there's a whole bunch of empty symbols in the symbol table that seem to have been for temporary purposes. Things like: `unicode.statictmp_103`

[gist of the go program and its output](https://gist.github.com/grantseltzer/35642d262f18a2c26588facc8e1d488d)

### What did you expect to see?

No temporary empty symbols being part of the compiled ELF symbol table

### What did you see instead?

Temporary empty symbols being part of the compiled ELF symbol table

**Comment by odeke-em** [comment]
Kindly paging some linker folks @ianlancetaylor @heschik @thanm @aclements

**Comment by cherrymui** [comment]
What's the problem with 0-sized symbols? For a C program compiled with GCC, there are also a bunch of 0-sized symbols.
