### ISSUE TITLE
x/build: add darwin-10_14 builder

### ISSUE THREAD

**Issue by dmitshur** [golang/go#27806]
[macOS Mojave](https://www.apple.com/macos/mojave/) (version 10.14) is going to be released on September 24th, which is the coming Monday.

As I understand, we should add a builder for it after its release. /cc @bradfitz

This is the tracking issue. Somewhat related to #23011.

**Comment by bradfitz** [comment]
It did not go smoothly.

I started with macOS 10.12 and click click clicked through the App Store recommended upgrade and it did its thing and then rebooted into unbootable unhappiness:

<img width="1136" alt="screen shot 2018-10-04 at 4 29 22 pm" src="https://user-images.githubusercontent.com/2621/46508550-d424e180-c7f2-11e8-8b79-a0c2f504c87f.png">
<img width="1136" alt="screen shot 2018-10-04 at 4 29 33 pm" src="https://user-images.githubusercontent.com/2621/46508557-dab35900-c7f2-11e8-8088-8f868ea63ca2.png">
<img width="1136" alt="screen shot 2018-10-04 at 4 29 09 pm" src="https://user-images.githubusercontent.com/2621/46508560-df780d00-c7f2-11e8-9be6-38422c72cafb.png">

**Comment by dmitshur** [comment]
Which VMware product is that, and what version is it? We should find out whether it's a version recent enough to support Mojave (if such a version exists by now).

**Comment by randall77** [comment]
It would be nice to get this going. I ran into a 10.14 issue that doesn't reproduce on 10.12 in CL 168479.

**Comment by bradfitz** [comment]
I started a support ticket with MacStadium 13 days ago to upgrade us to the latest VMWare release that supports recent macOS releases. (It also supports an HTML5 web UI instead of Flash) But no update yet. I pinged them yesterday.
