### ISSUE TITLE
pprof: allow grabbing a "super" profile for all profiles

### ISSUE THREAD

**Issue by nhooyr** [golang/go#27819]
If I'm debugging a performance issue, it'd be convenient to grab every kind of profile I can instead of manually trying CPU, memory, block, tracing etc.

**Comment by davecheney** [comment]
This sounds useful, but in practice you just end up profiling the runtime
profiling code rather than your code under test.

**Comment by hyangah** [comment]
Some of the profiles interfere with each other (for example, tracing will add a lot of noise to your cpu profile). It's better to run profile separately if we want the profile to be useful for optimization.

**Comment by davecheney** [comment]
@nhooyr thank you for raising this issue. As several people have noted, collecting multiple profiles at once is not a good idea. As such, we're unlikely to add an API to do this as it would only lead to confusing results.
