### ISSUE TITLE
cmd/go: Confused about error comparison

### ISSUE THREAD

**Issue by tr3ee** [golang/go#27815]
### What version of Go are you using (`go version`)?

go version go1.9.2 windows/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GORACE=
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

### What did you do?

https://play.golang.org/p/cmkSo7H8qSo

### What did you expect to see?

`NIL`

### What did you see instead?

`NOT NIL`

### Is this a bug?

**Comment by tevjef** [comment]
Please see https://golang.org/doc/faq#nil_error for why it is not nil. Also, the issue tracker is for issues and features only. 

Please use one of the forums (https://golang.org/help/) for asking for help.

**Comment by tr3ee** [comment]
> Please see https://golang.org/doc/faq#nil_error for why it is not nil. Also, the issue tracker is for issues and features only.
> 
> Please use one of the forums (https://golang.org/help/) for asking for help.

thanks for help.
