### ISSUE TITLE
flag.PrintDefaults() displays double backslash in path argument's default value

### ISSUE THREAD

**Issue by claudiofelber** [golang/go#27827]
### What version of Go are you using (`go version`)?

go1.11 windows/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10, Intel Core i7-4790

### What did you do?

https://play.golang.org/p/V_KbsT8sDs8

### What did you expect to see?

```
-dir string
     The directory that contains the data (default "bin\data")
```

### What did you see instead?

```
-dir string
     The directory that contains the data (default "bin\\data")
```

flag.PrintDefaults() should not escape a backslash or a double quote inside an argument's default value. Command line tools are used by a lot of non-programmers which are not necessarily familiar with escaped characters and the extra backslashes will most certainly confuse them.

Inside flag.PrintDefaults() the default value of a string argument is printed using the following line:
```go
s += fmt.Sprintf(" (default %q)", flag.DefValue)
```

Why not simply use this code instead?
```go
s += fmt.Sprintf(" (default \"%s\")", flag.DefValue)
```

Or maybe this one?
```go
s += fmt.Sprintf(" (default: %s)", flag.DefValue)
```

**Comment by cznic** [comment]
I think the `%q` verb is used in this case intentionally, to avoid the help output become confusing when the defaults contain some special runes.

**Comment by ianlancetaylor** [comment]
Yes, this is working as intended even if the result is not ideal for your use case.  You can define your own flag type, or your own mechanism for printing default values, or use `"bin/data"`.  We aren't going to change the default here.
