### ISSUE TITLE
x/mobile: expose RunOnJVM to gobind targets

### ISSUE THREAD

**Issue by steeve** [golang/go#27831]
### What version of Go are you using (`go version`)?
```
go version go1.11 darwin/amd64
```

### Feature Request
It would be nice to expose `RunOnJVM` to libraries using `gobind` as well.

### Links
1. https://github.com/golang/mobile/commit/507816974b79c76a5fe70f9580265cd57dc78bbe

**Comment by xfxdev** [comment]
Need this too, otherwise we can't write functions like asset/audio packages in mobile.

**Comment by xfxdev** [comment]
Why close?

**Comment by steeve** [comment]
Oh sorry, I just worked around it by c/c the code in my app
