### ISSUE TITLE
testing: test example missing from beginning of package doc

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#27839]
### What version of Go are you using (`go version`)?
`go version go1.11`

### What did you do?

I went to the [testing package documentation](https://golang.org/pkg/testing/) to find an example to share with another person.
### What did you expect to see?

I expected to be see a simple few line example demonstrating how to write a test function and how to write an expectation.

### What did you see instead?

Full examples for benchmarks, and example tests, and even an example of how to skip a test, but no examples of how to write a test with a simple expectation.

### CL

I can open a small CL adding an example to the package documentation unless anyone feels like that'd be a bad idea.

**Comment by leighmcculloch** [comment]
Screenshots from the CL ☝️ 

#### The example in the beginning section of the overview:

<img width="528" alt="screen shot 2018-09-24 at 10 59 48 pm" src="https://user-images.githubusercontent.com/351529/45995635-be265c80-c04d-11e8-8b8b-d76cdba1a493.png">

#### The existing skipping example moved to a later section:

<img width="531" alt="screen shot 2018-09-24 at 11 00 02 pm" src="https://user-images.githubusercontent.com/351529/45995637-c1214d00-c04d-11e8-9cbe-4be13cb3030b.png">

**Comment by andybons** [comment]
@robpike
