### ISSUE TITLE
go mod vendor is not copying all files to the vendor folder

### ISSUE THREAD

**Issue by nomad-software** [golang/go#27832]
`go mod vendor` is not copying all files to the vendor folder. This leaves an incomplete repository, missing many tests, examples and in some cases C include files. My expectation would be a complete copy of the repository because this is not only for building a package but a backup in case the original repository is taken offline.

### What version of Go are you using (go version)?

go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (go env)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gary/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/media/Data/Projects/Go"
GOPROXY=""
GORACE=""
GOROOT="/home/gary/Applications/go"
GOTMPDIR=""
GOTOOLDIR="/home/gary/Applications/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build971255390=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Execute `go mod vendor` on a project using the new module support.

### What did you expect to see?

A complete repository backup installed in the vendor folder.

### What did you see instead?

Only `*.go` files.

**Comment by myitcv** [comment]
As I mentioned in https://groups.google.com/d/msg/golang-nuts/_GWRF1KIvFw/r0HOTKvBCwAJ, this is a dup of https://github.com/golang/go/issues/26366.
