### ISSUE TITLE
gnu-ld unknown option "pagezero_size"

### ISSUE THREAD

**Issue by Pixdigit** [golang/go#27855]
### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
Yes, with the latest official build

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOCACHE="/home/me/.cache/go-build"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build020687925=/tmp/go-build -gno-record-gcc-switches"

Note:_All empty variables omitted_

### What did you do?
I tried to cross compile a program with `env GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build`. It is noteworthy that it relies on go-sdl2 which uses cgo as this does not reproduce when only using the standard library.
In this case I tried to build [alienSignal](https://github.com/Pixdigit/alienSignal).

### What did you expect to see?
Not a fail.

### What did you see instead?
`# github.com/Pixdigit/alienSignal`
`/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1`
`/usr/bin/x86_64-linux-gnu-ld: unknown option »-pagezero_size«`
`/usr/bin/x86_64-linux-gnu-ld: Use the option --help for help`
`collect2: error: ld returned 1 exit status`

### Relevant piece of code
[src/cmd/link/internal/ld/lib.go](https://github.com/golang/go/blob/b84a58095f11ba3122b88847d1b0a73c57c1632c/src/cmd/link/internal/ld/lib.go#L1123)

**Comment by ianlancetaylor** [comment]
You are trying to build code on GNU/Linux that will run on Darwin, and that code uses C.  You need to use a C cross-compiler, not the native GNU/Linux C compiler.

If you don't want to use C, you will need to set `CGO_ENABLED=0`, which is the default when cross-compiling.

Closing because this is not something we can fix in the Go tools.

**Comment by ianlancetaylor** [comment]
Yes.  It's not easy, though.  There's no simple or standard way to interrogate the compiler, or linker, to find out what target it supports.  But if you or anyone have any ideas on how to implement that, patches to support it would be great.
