### ISSUE TITLE
go/internal/gccgoimporter: nil type when decoding a type alias

### ISSUE THREAD

**Issue by alandonovan** [golang/go#27856]
The export data produced by gccgo for this Go package, when decoded by the gccgoexportdata package in x/tools, contains a nil type for the type alias, E.  I'm not sure if the problem is on the encoding or decoding side, but it is breaking the blaze build for gccgo (b/116516363).

```
// test/lib.go
package lib

type M struct {
        E E
}
type F struct {
        _ *M
}
type E = F
```

I have attached a standalone Go program containing the export data file produced by Blaze (as a string literal) to exercise the decode side:
[gccgoimport.txt](https://github.com/golang/go/files/2415936/gccgoimport.txt)

Excerpt:
```
	r, err := gccgoexportdata.NewReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	imports := make(map[string]*types.Package)
	pkg, err := gccgoexportdata.Read(r, nil, imports, "lib")
	if err != nil {
		log.Fatal(err)
	}

	E := pkg.Scope().Lookup("M").Type().Underlying().(*types.Struct).Field(0)
	fmt.Println(E, E.Type()) // "field E", <nil>
```

I'm not sure how to isolate the encode side, outside of Blaze.

**Comment by alandonovan** [comment]
cc @ianlancetaylor, @paranoiacblack

**Comment by thanm** [comment]
I can take a look at this. Looking at the export data in the object file I see

```
package lib;
pkgpath test;
type <type 1 "E" = <type 2 "F" <type 3 struct { .test._ <type 4 *<type 5 "M" <type 6 struct { E <type 1>; }>>>; }>>>;
type <type 2>;
type <type 5>;
```

which as far as I can tell includes the alias 'E' in the right way (assuming that I'm not missing some other problem). I'll poke around on the decode side.

**Comment by griesemer** [comment]
@thanm Please let me know if you want me to look at this - I'm leaving this alone unless I hear otherwise from you.

**Comment by thanm** [comment]
OK, I am fairly certain this is a bug in the decoder/parser (e.g. gccgoimporter/parser.go).

Here is the type of interest:

type <type 1 "E" = <type 2 "F" <type 3 struct { .test._ <type 4 *<type 5 "M" <type 6 struct { E <type 1>; }>>>; }>>>;

parseNamedType() has code that looks for the '=' token (indicates an alias) in parser.go line 390:

```
	if p.tok == '=' {
		// type alias
		p.next()
		typ := p.parseType(pkg)  // line 393
		if obj := scope.Lookup(name); obj != nil {
			typ = obj.Type() // use previously imported type
			if typ == nil {
				p.errorf("%v (type alias) used in cycle", obj)
			}
		} else {
			obj = types.NewTypeName(token.NoPos, pkg, name, typ)
			scope.Insert(obj)
		}
		p.typeMap[n] = typ
		return typ
	}
```

The problem here is that the parseType call on line 393 (marked above) can include types that refer to the index of the alias type -- at that point there won't yet be an entry in typeMap for the type. There has to be some sort of entry in the map for "n" before this call is made.

**Comment by thanm** [comment]
@griesemer looks like our comments crossed. Yes, if you could please look at it that would be great.

**Comment by griesemer** [comment]
For the record, to get the export data (.gox file) outside blaze, for a file x.go:
```
gccgo -c x.go
objcopy -j .go_export x.o x.gox
```
with x.gox containing the export data.

**Comment by griesemer** [comment]
Definitively a parser bug (which was not written with aliases in mind...). But the problem is on line parser.go:206 in parser.parseField, when reading the type for field E of struct M. That type E is not yet set up, and thus is nil.

**Comment by griesemer** [comment]
The fix above is for the std library. This needs to be back-ported to x/tools afterwards.
