### ISSUE TITLE
doc: broken link in FAQ

### ISSUE THREAD

**Issue by magical** [golang/go#27860]
Under the question "[Why do garbage collection? Won't it be too expensive?][1]", there is a link to https://talks.golang.org/2018/ismmkeynote, which does not exist. It should link to https://blog.golang.org/ismmkeynote.

[1]: https://golang.org/doc/faq#garbage_collection

**Comment by ALTree** [comment]
The blog entry is probably better than a `talks` link anyway, since it has more text and the slide's accompanying notes. I've sent a CL.
