### ISSUE TITLE
Go 1.11 inappropriately trying to http fetch local repository

### ISSUE THREAD

**Issue by bjm88** [golang/go#27869]
Moving from Go 1.10 to go 1.11 I setup a go.mod which references cached/downloaded 3rd part libs like normal, but I also reference a shared common lib within our codebase.  We have monolithic repo setup so 3 projects
```
./workspace/
  ./identity_service
 ./chat_service
 ./api_service
 ./common_lib  (other 3 go modules reference this locally)
```

Example go.mod
```
module company.com/project1/identity_service

require (
	cloud.google.com/go v0.28.0 // standard 3rd party lib
        company.com/project1/common_lib v0.0.0 . //local lib
)

replace company.com/project1/go_common => ../go_common
```

Go build works, but is slow.  Doing go run with -v reveals the issue, its trying to actually call company.com with go get and timing out and then continues without issue.  Is there a better way to set this up in go.mod so it understands to only get it locally ?

go run -v main.go 
Fetching https://company.com/project1/go_common?go-get=1
https fetch failed: Get https://mountsinai.org/consumer/go_common?go-get=1: dial tcp 146.203.125.245:443: connect: connection refused

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ben/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ben/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8_/b0g1vb392ws98pthb2vcf5nr0000gn/T/go-build903710899=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bcmills** [comment]
Almost certainly the same underlying cause as #27859.
