### ISSUE TITLE
x/image: riff: missing RIFF chunk header

### ISSUE THREAD

**Issue by acim** [golang/go#27873]
### What version of Go are you using (`go version`)?

1.11

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```sh
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/acim/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/acim/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/acim/Projects/shit/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build158015811=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```go
	file, err := os.Open("1.webp")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	image, err := webp.Decode(file)
	if err != nil {
		panic(err)
	}
       ...
```

### What did you expect to see?

Image gets decoded.

### What did you see instead?

Panic from  webp.Decod:

`riff: missing RIFF chunk header`

I tried several webp images at this happens with all of them. However, webp.DecodeConfig works well with the same files.

**Comment by bcmills** [comment]
CC @nigeltao

**Comment by bcmills** [comment]
Can you attach (or give a link to) an image file that triggers the issue?

**Comment by acim** [comment]
Here is one.

**Comment by acim** [comment]
https://files.fm/u/9gqueavn

**Comment by acim** [comment]
My bad, had to open file again because io.Reader has been emptied by DecodeConfig. Thank you, you can close this.
