### ISSUE TITLE
x/crypto/openpgp: Implement opaque DSA keys

### ISSUE THREAD

**Issue by Merovius** [golang/go#27883]
I'm writing a package to use gpg-agent for private key operations, implementing the `crypto.Signer` and `crypto.Decrypter` interfaces. Currently, the `openpgp` package doesn't support that for DSA. This would be analogous to https://go-review.googlesource.com/c/crypto/+/23802

[edit] I just sent out the CL for this one, as it's independent and more important for me to get in soon-ish :) Will file separate issues for other things.

**Comment by FiloSottile** [comment]
See #27905
