### ISSUE TITLE
mime/multipart: empty filename leads to loss of part headers

### ISSUE THREAD

**Issue by shilkin** [golang/go#27893]
### What version of Go are you using (`go version`)?
1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alx/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alx/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build697396012=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I send form-data part with Content-Type header and without filename parameter.
Due to this [fix](https://github.com/golang/go/commit/f69ad10377b1817e3db57851226a23973caa584e) we lose all headers from part.

```
POST / HTTP/1.1
Content-Length: 730349
Content-Type: multipart/form-data; boundary=adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9

--adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9
Content-Disposition: form-data; name="field"
Content-Type: image/png

some_data_730349
--adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9--
```
### What did you expect to see?
I want to get headers from part, so what I can suggest is to introduce method ```r.FormHeaders("name") *mutlipart.FileHeader```. This will alow us to preserve original ```http.Request``` interface, and to make part headers accessible.

### What did you see instead?
Now I can get only form value without headers.

Thank you!

**Comment by mattn** [comment]
You can use http.ReadRequest()

```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
	"strings"
)

var text = `POST / HTTP/1.1
Content-Length: 730349
Content-Type: multipart/form-data; boundary=adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9

--adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9
Content-Disposition: form-data; name="field"
Content-Type: image/png

some_data_730349
--adeb81d8e78682facad3ce26db9333753b045e42bd67e0ae18f3cc2284f9--
`

func main() {
	b := bufio.NewReader(strings.NewReader(text))
	req, err := http.ReadRequest(b)
	if err != nil {
		log.Fatal(err)
	}
	mr, err := req.MultipartReader()
	if err != nil {
		log.Fatal(err)
	}
	for {
		part, err := mr.NextPart()
		if err != nil {
			break
		}
		fmt.Println(part.Header)
	}
}
```

**Comment by shilkin** [comment]
@mattn thank you or reply!
Of course I can do so.  Furthermore, I can set filename in http middleware and work with this form as if it has a filename. But it looks as something inconsistent.

**Comment by katiehockman** [comment]
@bradfitz

**Comment by bradfitz** [comment]
I wasn't involved in these changes. Redirecting to @andybons & @hcliff.

**Comment by ianlancetaylor** [comment]
See #24041.  As far as I know the current 1.11 behavior is consistent with 1.9 and 1.10.4 and all earlier releases (but not 1.10 through 1.10.3).  I would very much prefer to not have to change this again.

**Comment by shilkin** [comment]
I mean if we use ```filename``` we should use ```FormFile``` to get headers, and if ```filename``` is missing there is complitely different way to get headers,  as @mattn mentioned above. This is what I called 'inconsistecy'.

Anyway I can deal with it, but it's a standard library, and I think all of us want to use clear interface.

**Comment by mattn** [comment]
As far as the part in multipart has not a filename,it should not be called File. So `FormFile` don't have to return anything for empty filename. (since it's not a file)

**Comment by shilkin** [comment]
Thanks to all. I'm closing the issue.
