### ISSUE TITLE
proposal / suggestion / idea: GPM

### ISSUE THREAD

**Issue by sandorvasas** [golang/go#27897]
# GPM - Go Package Manager

Please change the existing dependency management and release something like npm!
Go Package Manager, with which the user can
```
gpm init
gpm install github.com/some/dependency@some.version
```
generates deps folder locally, along with a project descriptor file e.g. project.yml providing some basic project info and listing dependencies just like npm does with package.json. 

## Why?
Having to put all go projects in a single folder is crazy, making go really hard to use for language-heterogenous projects. I don't want to mix up my go home folder with a project containing JS, TS, Python, Java sources of different services.

It doesn't matter if we have multiple copies of the same dependencies in each folder, disks space is cheap nowadays.

**Comment by bontibon** [comment]
Have you seen [modules in Go 1.11](https://github.com/golang/go/wiki/Modules) yet?

**Comment by rsc** [comment]
See https://golang.org/doc/go1.11#modules.

**Comment by sandorvasas** [comment]
Wonderful!
