### ISSUE TITLE
debug/pe: test failing for Windows-arm

### ISSUE THREAD

**Issue by katiehockman** [golang/go#27904]
See [build.golang.org](http://build.golang.org) windows-arm build failures.
Example build: https://build.golang.org/log/b861d37d4bb477daf73ed0b8b9de6dee5d44ef20

```
--- FAIL: TestDWARF (7.93s)
    file_test.go:399: main.main not found
--- FAIL: TestImportTableInUnknownSection (0.09s)
    file_test.go:544: unable to locate required file "atmfd.dll" in search path: exec: "atmfd.dll": executable file not found in %PATH%
FAIL
FAIL	debug/pe	12.391s
```

**Comment by alexbrainman** [comment]
> --- FAIL: TestDWARF (7.93s) file_test.go:399: main.main not found --- FAIL: TestImportTableInUnknownSection (0.09s) file_test.go:544: unable to locate required file "atmfd.dll" in search path: exec: "atmfd.dll": executable file not found in %PATH% FAIL FAIL	debug/pe	12.391s

I am sure, the fix for this is part of #26148. Leaving for @jordanrh1 

Alex

**Comment by jordanrh1** [comment]
I'll take a look.

**Comment by katiehockman** [comment]
@jordanrh1 just a friendly ping. Any updates on this?

**Comment by bradfitz** [comment]
Looks like we can just skip that test. I'll send a CL. I don't think windows/arm has that DLL.

**Comment by jordanrh1** [comment]
Correct, Windows IOT Core does not have atmfd.dll. Thank you for fixing.

**Comment by jordanrh1** [comment]
`TestDWARF` is failing because of relocations. The test is expecting the runtime address of `main.main` to match the link-time address, but this does not hold up with relocatable binaries. You'll get a different address printed from `a.exe` each time you run it due to ASLR.

@alexbrainman What do you think about having `a.exe` subtract the module base address from the address of `main.main`, i.e. print the relative offset of `main.main` from module start?

**Comment by alexbrainman** [comment]
> @alexbrainman What do you think about having `a.exe` subtract the module base address from the address of `main.main`, i.e. print the relative offset of `main.main` from module start?

Sounds reasonable to me. Would like to send a change?

I am reopening this issues to track TestDWARF failure.

Alex

**Comment by tobiaskohlbau** [comment]
I get the same error on Windows 10, Version 1809, Build 17763.134. Does this test need additional packages installed?

```
--- FAIL: TestImportTableInUnknownSection (0.02s)
    file_test.go:613: unable to locate required file "atmfd.dll" in search path: exec: "atmfd.dll": executable file not found in %PATH%
FAIL
FAIL    debug/pe        5.053s
```

**Comment by jordanrh1** [comment]
atmfd.dll is the Adobe Type Manager Font Driver. It may be present in an optional package.
@Alexbrainman is there another DLL that would work?

**Comment by tobiaskohlbau** [comment]
Thanks for your fix. I can confirm that your fix works on my machine, too.

```Powershell
PS C:\go> git show
commit ed7176e50b44567370d487796c02903a70f1f222 (HEAD)
...

PS C:\go\src> .\all.bat
Building Go cmd/dist using C:\go1.11
Building Go toolchain1 using C:\go1.11.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for windows/amd64.


##### Testing packages.

...
ok      debug/dwarf     1.400s
ok      debug/elf       0.649s
ok      debug/gosym     2.650s
ok      debug/macho     0.860s
ok      debug/pe        4.871s
... 

ALL TESTS PASSED

---
Installed Go for windows/amd64 in C:\go
Installed commands in C:\go\bin
```

**Comment by alexbrainman** [comment]
> I can confirm that it works on my machine, too.

SGTM. Thanks for checking. I just submitted 151137.

Alex

**Comment by alexbrainman** [comment]
> Now I realised that kernel32.dll should work too.

@jordanrh1 it looks like windows/arm builder still fails on TestImportTableInUnknownSection

https://build.golang.org/log/e37627b9aa1c02a85c1d9d6ba6123052184cdee0
```
--- FAIL: TestImportTableInUnknownSection (0.06s)
    file_test.go:610: unable to locate required file "atmfd.dll" in search path: exec: "kernel32.dll": executable file not found in %PATH%
FAIL
FAIL	debug/pe	12.768s
```

It appears that os/exec.LookPath could not find "kernel32.dll" in the %PATH%. I wonder why? kernel32.dll functions are used by Go in many places. Why it could not be found in the %PATH%? Perhaps os/exec.LookPath is broken? Can you investigate, please.

Thank you.

Alex

**Comment by jordanrh1** [comment]
With the onecore refactoring effort, kernel32.dll was split into a multitude of other DLLs, two of which are kernelbase.dll and kernel32legacy.dll. kernel32.dll does not exist on onecore editions, except as a virtual entity for backwards compatibility. Some candidate DLLs that exist across all flavors of windows are combase.dll, cfgmgr32.dll, and ws2_32.dll.

**Comment by alexbrainman** [comment]
> Some candidate DLLs that exist across all flavors of windows are combase.dll, cfgmgr32.dll, and ws2_32.dll.

ws2_32.dll works for me. Please, try https://go-review.googlesource.com/c/go/+/151480

Thank you.

Alex

**Comment by jordanrh1** [comment]
Verified that it works on ARM.
```
>pe.test.exe -test.v -test.run TestImportTableInUnknownSection
=== RUN   TestImportTableInUnknownSection
--- PASS: TestImportTableInUnknownSection (0.05s)
PASS
```

**Comment by alexbrainman** [comment]
> Verified that it works on ARM.

Thanks for checking. Just submitted CL 151480.

Alex
