### ISSUE TITLE
wiki: CodeReviewComments does not specify where to discuss changes

### ISSUE THREAD

**Issue by dmitshur** [golang/go#27913]
[golang.org/s/style](https://golang.org/s/style) currently says:

> **Please discuss changes before editing this page,** even _minor_ ones.

I think we should specify _where_ the changes should be discussed.

The reason to have it specified is to make it clear when a change was or wasn't discussed. This way, we can more easily revert a change to CodeReviewComments if it doesn't have a corresponding discussion. It also makes it easier to look up the history and rationale for a given change.

We can use the issue tracker for this. Here's my proposed change to the wiki page:

<del>**Please discuss changes before editing this page**, even _minor_ ones.</del>
**Please [discuss changes](https://golang.org/issue/new?title=wiki%3A+CodeReviewComments+change) before editing this page**, even _minor_ ones.

/cc @bradfitz @ianlancetaylor

**Comment by bradfitz** [comment]
SGTM.

**Comment by dmitshur** [comment]
Resolved via [wiki@1c58cd10](https://github.com/golang/go/wiki/CodeReviewComments/_compare/f22d526c92037bbc06d20e687b21f71cb386e26a...1c58cd10dc1e6e92ef2f0bc9887ba7c466a419e0).
