### ISSUE TITLE
.github: hide text for issue author in ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by dmitshur** [golang/go#27914]
The current [issue template](https://github.com/golang/go/blob/75f4aa86bacb668348e788692974aa554cc61915/.github/ISSUE_TEMPLATE) contains some text that is meant for the issue author to read, internalize, and hopefully delete (since it's usually not relevant to the issue).

That text includes:

> Please answer these questions before submitting your issue. Thanks!

And:

> If possible, provide a recipe for reproducing the error.
> A complete runnable program is good.
> A link on play.golang.org is best.

Some issues that are submitted include answers to all the questions, but they don't delete that text. It can happen either because the author didn't realize they're supposed to delete it, or overlooked it.

The result is that the final issue is valid and actionable, but includes text that is distracting.

I have a potential .github/ISSUE_TEMPLATE change in mind that resolves this issue. It places the author-facing text inside HTML comments, so even if left behind, it will not appear when the issue is rendered.

Additionally, the potential .github/ISSUE_TEMPLATE change makes use of <detail> HTML tag to make it so that `go env` by default is collapsed, but can be expanded when needed. I think this is helpful because in most issues, seeing detailed `go env` output isn't something that needs to be done often. We still want the information to be available, and this adjustment tweaks only the default presentation, it doesn't remove it.

### Screenshots

[Before](https://user-images.githubusercontent.com/1924134/46179619-2497be80-c28a-11e8-9641-bc8e50f1395b.png) -> [After](https://user-images.githubusercontent.com/1924134/46179691-59a41100-c28a-11e8-921f-50f29a7a0bfb.png)

Expanding the `go env` output element works [as expected](https://user-images.githubusercontent.com/1924134/46179741-adaef580-c28a-11e8-8275-a09a2af0f818.png).

/cc @bradfitz @ianlancetaylor @katiehockman

**Comment by dmitshur** [comment]
One possible counter-argument against this is that template text showing up in the submitted issue can be used as a signal for issue report quality. High quality issue reports are less likely to include text that isn't relevant.

I would argue that's not a strong reason. It's still possible to tell whether the issue report is high quality and actionable even if that text never shows up, by looking at the content of the issue.

**Comment by dmitshur** [comment]
It's hard to post the diff for that file in this issue, so I sent a do-not-submit CL [138295](https://golang.org/cl/138295) with the diff. It's there to augment this issue only, and not meant to be submitted unless we decide doing this is a good idea.

**Comment by justinclift** [comment]
Using the (javascript?) tags like that `<!--` `-->` is a good idea.  We've been doing similar with the [DB4S](https://github.com/sqlitebrowser/sqlitebrowser/tree/master/.github) repo for a while now, and for us it's helped.

It's not foolproof, as sometimes people still manage to muck things up... but on the whole this should be a good improvement. :smile:

**Comment by andybons** [comment]
I don't have a problem with this. Go for it.

**Comment by dmitshur** [comment]
Sounds good. I'll apply the change just before my next triaging rotation, and make sure it has a positive effect on the new issue reports.
