### ISSUE TITLE
go 1.11 compiled binary doesn't contain dwarf symbols

### ISSUE THREAD

**Issue by Lewiskong** [golang/go#27918]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nirvana/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nirvana/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jq/df33742x14q1s88pl24hv5m80000gn/T/go-build361440849=/tmp/go-build -gno-record-gcc-switches -fno-common"

gdb version : 8.0.1

### What did you do?

I compiled a simple hello world go program using `go compile -gcflags '-N -l' -o test test.go` and use gdb to debug it. But gdb reports `Reading symbols from learn...(no debugging symbols found)...done.`
Then i downgrade go version to 1.9 and recompile, it works as expected. 

To confirm the problem is about go1.11 i execute `objdump -h test` and it prints :
Idx Name          Size      Address          Type
  0 __text        0004cf70 0000000001001000 TEXT 
  1 __rodata      00029344 000000000104df80 DATA 
  2 __symbol_stub1 000000c6 00000000010772e0 TEXT 
  3 __typelink    000006b8 00000000010773c0 DATA 
  4 __itablink    00000008 0000000001077a78 DATA 
  5 __gosymtab    00000000 0000000001077a80 DATA 
  6 __gopclntab   0003da69 0000000001077a80 DATA 
  7 __nl_symbol_ptr 00000108 00000000010b6000 DATA 
  8 __noptrdata   00000c28 00000000010b6120 DATA 
  9 __data        00001990 00000000010b6d60 DATA 
 10 __bss         0001c370 00000000010b8700 BSS
 11 __noptrbss    00002518 00000000010d4a80 BSS
 12 __zdebug_abbrev 00000112 00000000010d7000 DATA 
 13 __zdebug_line 0000c5d4 00000000010d7112 DATA 
 14 __zdebug_frame 00003977 00000000010e36e6 DATA 
 15 __zdebug_pubname 00000b3a 00000000010e705d DATA 
 16 __zdebug_pubtype 00001fd4 00000000010e7b97 DATA 
 17 __debug_gdb_scri 0000002a 00000000010e9b6b DATA 
 18 __zdebug_info 00018a81 00000000010e9b95 DATA 
 19 __zdebug_loc  00009fb5 0000000001102616 DATA 
 20 __zdebug_ranges 000037d6 000000000110c5cb DATA

Apparently there is not `__debug_info` as i execute the same cmd to go1.11 compiled binary.
And i execute `dwarfdump test`, It prints :
----------------------------------------------------------------------
 File: learn (x86_64)
----------------------------------------------------------------------
.debug_info contents:
< EMPTY >

my gdb version is 8.0.1
os is mac os sierra 10.12.6

### What did you expect to see?
gdb work normally

### What did you see instead?
Reading symbols from learn...(no debugging symbols found)...done.

**Comment by agnivade** [comment]
In your gdb command, I think you may be passing the wrong binary. You mention - `Reading symbols from learn...(no debugging symbols found)...done.`. So you are reading from `learn`, but your binary is `test`.

Also, there is no command like `go compile`. How did that succeed ?
```
go  compile -gcflags '-N -l' -o test test.go
go compile: unknown command
Run 'go help' for usage.
```

**Comment by davecheney** [comment]
See also, https://groups.google.com/forum/#!topic/golang-nuts/LlgN1qpbRE8

**Comment by agnivade** [comment]
Looks like this is WAI. @Lewiskong - you have to  set "-ldflags=-compressdwarf=false" to use gdb in osx to read dwarf. Or use delve, which can read compressed dwarf just fine.

Closing it. Please comment if the issue still persists for you.

**Comment by Lewiskong** [comment]
> In your gdb command, I think you may be passing the wrong binary. You mention - `Reading symbols from learn...(no debugging symbols found)...done.`. So you are reading from `learn`, but your binary is `test`.
> 
> Also, there is no command like `go compile`. How did that succeed ?
> 
> ```
> go  compile -gcflags '-N -l' -o test test.go
> go compile: unknown command
> Run 'go help' for usage.
> ```

Oh sorry that's my description's fault.
I actually used `go build -gcflags '-N -l' -o test test.go` and it's the same with binary's name. I've update the issue description.
The problem still exist.

**Comment by Lewiskong** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> ### What version of Go are you using (`go version`)?
> go version go1.11 darwin/amd64
> 
> ### Does this issue reproduce with the latest release?
> yes
> 
> ### What operating system and processor architecture are you using (`go env`)?
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/nirvana/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/nirvana/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jq/df33742x14q1s88pl24hv5m80000gn/T/go-build361440849=/tmp/go-build -gno-record-gcc-switches -fno-common"
> 
> gdb version : 8.0.1
> 
> ### What did you do?
> I compiled a simple hello world go program using `go build -gcflags '-N -l' -o test test.go` and use gdb to debug it. But gdb reports `Reading symbols from test...(no debugging symbols found)...done.`
> Then i downgrade go version to 1.9 and recompile, it works as expected.
> 
> To confirm the problem is about go1.11 i execute `objdump -h test` and it prints :
> Idx Name Size Address Type
> 0 __text 0004cf70 0000000001001000 TEXT
> 1 __rodata 00029344 000000000104df80 DATA
> 2 __symbol_stub1 000000c6 00000000010772e0 TEXT
> 3 __typelink 000006b8 00000000010773c0 DATA
> 4 __itablink 00000008 0000000001077a78 DATA
> 5 __gosymtab 00000000 0000000001077a80 DATA
> 6 __gopclntab 0003da69 0000000001077a80 DATA
> 7 __nl_symbol_ptr 00000108 00000000010b6000 DATA
> 8 __noptrdata 00000c28 00000000010b6120 DATA
> 9 __data 00001990 00000000010b6d60 DATA
> 10 __bss 0001c370 00000000010b8700 BSS
> 11 __noptrbss 00002518 00000000010d4a80 BSS
> 12 __zdebug_abbrev 00000112 00000000010d7000 DATA
> 13 __zdebug_line 0000c5d4 00000000010d7112 DATA
> 14 __zdebug_frame 00003977 00000000010e36e6 DATA
> 15 __zdebug_pubname 00000b3a 00000000010e705d DATA
> 16 __zdebug_pubtype 00001fd4 00000000010e7b97 DATA
> 17 __debug_gdb_scri 0000002a 00000000010e9b6b DATA
> 18 __zdebug_info 00018a81 00000000010e9b95 DATA
> 19 __zdebug_loc 00009fb5 0000000001102616 DATA
> 20 __zdebug_ranges 000037d6 000000000110c5cb DATA
> 
> ## Apparently there is not `__debug_info` as i execute the same cmd to go1.11 compiled binary.
> And i execute `dwarfdump test`, It prints :
> ## File: test (x86_64)
> .debug_info contents:
> < EMPTY >
> 
> my gdb version is 8.0.1
> os is mac os sierra 10.12.6
> 
> ### What did you expect to see?
> gdb work normally
> 
> ### What did you see instead?
> Reading symbols from test...(no debugging symbols found)...done.
