### ISSUE TITLE
text/template/parse: remove truncated error context or add an template.Option

### ISSUE THREAD

**Issue by draeron** [golang/go#27930]
### What version of Go are you using (`go version`)?
go1.11 windows/amd64

### Problem
When an error is thrown because a template is missing a value (`"missingkey=error"`), the error sent will truncate the context upon which the field is evaluated.

```executing "someTemplateName" at <.k8s.clusters.someCl...>: map has no entry for key "someField"```

Sample code to demontrate : https://play.golang.org/p/h3_fgkbUo_S

This is where the string gets truncated : 
https://github.com/golang/go/blob/7dda5123d8753cfd1f041e1d1537bb5493cd5e5d/src/text/template/parse/parse.go#L151

### Why is that a problem

I'm pretty sure this has been met by many users using tools that use the `text/template` engine (hello helm users). Once the context is deep enough, it become excitedly difficult to understand _where_ in the data tree something is missing. If the field is dynamically accessed, say through a variable, it become pretty much impossible to know what exactly is wrong and how to fix the template.

My particular use case is that i'm trying to list all accessed values in a template, since it is impossible to access the internal structure of the parse.Tree, i though i could execute a template, catch missing value errors and construct a list through error messages.

### Proposal for a solution

There are multiple solutions

- add more specific error (parse.ValueNotFound ?) which give detailed informations which include the context
- modify _func ErrorContext_ to remove truncation
- enable some option to keep the behavior backward compatible

**Comment by adamdecaf** [comment]
Removing the truncating is likely fine. Can you submit a CL and verify? (On those nested helm charts.)

**Comment by draeron** [comment]
i'm not sure what you mean by CL, you mean a merge request?

**Comment by ianlancetaylor** [comment]
Yes, a CL (a Change List) is the same as GitHub pull request.  For more on contributing see https://golang.org/doc/contribute.html.  Thanks.

**Comment by draeron** [comment]
just bumping the issue, my request for the CLA got stuck in my employer's legal black hole

**Comment by robpike** [comment]
This is not a compelling example. The problem is clearly visible in the error message. Even this variant: 
  https://play.golang.org/p/7VcbyRpWxNt
shows all you need to know.

Let's not decide what to do here until we have actual demonstration of an issue.

**Comment by draeron** [comment]
How about this example ?

https://play.golang.org/p/pydq1PHVmQr

it become hard to figure out that the map `value` is missing the key `is` with `.some.super.deep.acc...`  as context in the message.
