### ISSUE TITLE
Is there plan to make closure serializable?

### ISSUE THREAD

**Issue by zhiqiangxu** [golang/go#27932]
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
mac osx, amd64

Recently I found rdd(resilient distributed dataset) to be a genius idea to handle big data problems in a unified programing way, so I invested how spark is implemented, one of the core features it depends on is that the host language needs to be able to serialize/unserialize closures:

`Scala represents each closure as a Java object, and these objects can be serialized and loaded on another node to pass the closure across the network. `

Python has this feature so there is a spark clone in python: [dpark](https://github.com/douban/dpark)

I've contacted the author of [gopark](https://github.com/mijia/gopark), he confirms that one of the biggest trouble to implement something like rdd is in serializing closures...

**Comment by adamdecaf** [comment]
This proposal needs to be more specific. There's a lot involved in serializing closures as the scala [papers talk about](https://arxiv.org/pdf/1602.03598.pdf) in [detail](https://infoscience.epfl.ch/record/191239/files/spores_1.pdf).  

Can you work out a concept or design with the community? This was rejected before in the stdlib, see https://github.com/golang/go/issues/5514.

**Comment by RLH** [comment]
How would Go deal with free variables? 
    Are free variables immutable? 
    Is the closure / func idempotent? Associative and Commutative? 
How should Go express such facts?

**Comment by ianlancetaylor** [comment]
To answer the question: no, there are no current plans to make closures serializable.

This is not an actionable issue, so I'm going to close it.  This would be best discussed on golang-nuts.
