### ISSUE TITLE
os/exec: exec.Command("cat", "/proc/uptime") memory leak in golang 1.9

### ISSUE THREAD

**Issue by yxdming** [golang/go#27934]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using (`go env`)?
SuSE

### What did you do?

When i use exec.Command("cat", "/proc/uptime") in my programe, i found that there is a memory leak in this call. The memory used by program goes high after 2 hours from initial 20MB to 105MB and increasing continuously unless i restart the programe. The code as below.

```
func GetSecondFromSystemStart() int {
	out, err := exec.Command("cat", "/proc/uptime").Output()
	if(err != nil){
		logger.ErrorLog(MODULE_NAME, "get time from start fail:%s", err.Error())
	}else{
		vTimeString := strings.Split(string(out), ".")
		if(len(vTimeString) == 0){
			logger.ErrorLog(MODULE_NAME, "get time from start fail")
		}else{
			sed, e := strconv.Atoi(vTimeString[0])
			if(e != nil){
				logger.ErrorLog(MODULE_NAME, "get time from start fail:%s", e.Error())
			}else{
				logger.DebugLog(MODULE_NAME, "get time from start:%d", sed)
				return sed
			}
		}
	}
	return 0
}
```

**Comment by ALTree** [comment]
Can you reproduce this with Go 1.11 (https://golang.org/dl)? Go1.9 is quite old and it's no longer maintained.

**Comment by mvdan** [comment]
Also please check your pprof memory profiles. If the number of in-use heap objects keeps increasing over time, it will tell you where the allocations are coming from.

**Comment by bradfitz** [comment]
Unrelated: it's much more efficient to use ioutil.ReadFile to read /proc/uptime instead of starting a child process.

But in any case, the code above shouldn't leak anything. Please provide a minimal repro to demonstrate the problem.

**Comment by yxdming** [comment]
@ALTree 
When i use Go 1.11, it seam that everything works better. I will test more times and close this issue if the memory doesn't increase any more.
