### ISSUE TITLE
unicode: support version 11

### ISSUE THREAD

**Issue by fgm** [golang/go#27945]
see http://blog.unicode.org/2018/06/announcing-unicode-standard-version-110.html for the announcement and further information about what changed.

What version of Go are you using (go version)?
go version go1.11 darwin/amd64

What operating system and processor architecture are you using (go env)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fgm/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fgm/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/p780bc554njc4qj110_8rmbr0000gn/T/go-build464389101=/tmp/go-build -gno-record-gcc-switches -fno-common"

What did you do?
println(unicode.Version)

as in https://play.golang.org/p/k69zvpQ97S

What did you expect to see?
11.0.0

What did you see instead?
10.0.0

This is a followup to #21471

**Comment by odeke-em** [comment]
Thank you for filing the feature request report @fgm and welcome to the Go project!

We didn't get to work on this for Go1.12 so I'll move it to Go1.13 (or even Unreleased) as it is presumably a big change but also @mpvl is quite occupied.

**Comment by odeke-em** [comment]
@mpvl just recently mailed https://go-review.googlesource.com/c/text/+/154440/ so we can say the work has began.

**Comment by mpvl** [comment]
@odeke-em Just bear with me. This is going to be a very large change with CLs across core and x/text this time.

**Comment by odeke-em** [comment]
>@odeke-em Just bear with me. This is going to be a very large change with CLs across core and x/text this time.

@mpvl great and thank you! No rush at all :)

**Comment by mpvl** [comment]
This concludes the Unicode 11 upgrades.

Feel free to open a new one for Unicode 12. :)

**Comment by odeke-em** [comment]
Thank you and well done @mpvl!
