### ISSUE TITLE
cmd/objdump: add -file-offset option

### ISSUE THREAD

**Issue by mmcloughlin** [golang/go#27941]
GNU binutils version of `objdump` offers a [`[-F|--file-offsets]` flag](https://sourceware.org/binutils/docs/binutils/objdump.html#index-object-file-offsets)

> When disassembling sections, whenever a symbol is displayed, also display the file offset of the region of data that is about to be dumped. If zeroes are being skipped, then when disassembly resumes, tell the user how many zeroes were skipped and the file offset of the location from where the disassembly resumes. When dumping sections, display the file offset of the location from where the dump starts.

Example output on a Go binary:

```
...
000000000102e6c0 <runtime.schedule> (File Offset: 0x2e6c0):
 102e6c0:	65 48 8b 0c 25 30 00 	mov    %gs:0x30,%rcx
 102e6c7:	00 00
 102e6c9:	48 3b 61 10          	cmp    0x10(%rcx),%rsp
 102e6cd:	0f 86 3f 03 00 00    	jbe    102ea12 <runtime.schedule+0x352> (File Offset: 0x2ea12)
 102e6d3:	48 83 ec 40          	sub    $0x40,%rsp
 102e6d7:	48 89 6c 24 38       	mov    %rbp,0x38(%rsp)
 102e6dc:	48 8d 6c 24 38       	lea    0x38(%rsp),%rbp
...
```

This was useful for something I've been working on, and I think it would be fairly easy to add something like this to `go tool objdump`. Thoughts? If there's interest I could work on a CL.

**Comment by ALTree** [comment]
cc @randall77 for decision

**Comment by randall77** [comment]
> This was useful for something I've been working on

Could you describe how it would be useful?

Darwin objdump (Apple LLVM version 9.0.0 (clang-900.0.38)) does not have this option. My linux objdump does, but it didn't make the cut for the binary's one-page help page.

**Comment by mmcloughlin** [comment]
> There are other interfaces that programs can use to access this information.

I think the only problem with this is that the package you need to access `objdump`-like functionality is in an `internal` package.

Actually occurs to me that this feature may have been more useful in `nm`, for my use case at least. Then the script to do this is a simple combination of `go tool nm` and `dd`.

**Comment by randall77** [comment]
This works on public interfaces only (but ELF only):
```
package main

import (
	"debug/elf"
	"fmt"
	"os"
)

func main() {
	file := os.Args[1]
	e, err := elf.Open(file)
	if err != nil {
		panic(err)
	}
	syms, err := e.Symbols()
	if err != nil {
		panic(err)
	}
	for _, s := range syms {
		if elf.ST_TYPE(s.Info) != elf.STT_FUNC {
			continue
		}
		sect := e.Sections[s.Section]
		fmt.Printf("%16x %16x %s\n", s.Value-sect.Addr+sect.Offset, s.Size, s.Name)
	}
}
```
It should be easy to grab the actual instruction bytes using the elf.Section.ReaderAt.

**Comment by mmcloughlin** [comment]
Nice. Of course the benefit of the internal package is the abstraction layer over the object file format.

Feel free to close the ticket, it's not something I feel strongly about.
