### ISSUE TITLE
x/tools/godoc/vfs/zipfs: remove zipfs package

### ISSUE THREAD

**Issue by broady** [golang/go#27959]
Once golang.org/cl/133355 is in, and #27205 is resolved, I don't think we need the zipfs package for godoc anymore.

As far as I know, it was created as a workaround for Google App Engine restrictions on number of files allowed in an app deployment.

**Comment by dmitshur** [comment]
Such a change would affect [its users](https://godoc.org/golang.org/x/tools/godoc/vfs/zipfs?importers).

Do we have a policy to follow to removing non-internal subrepo packages? How do we decide when to do it? How to do it (perhaps deprecate first, remove after some pre-determined time; or something else)?

**Comment by SamWhited** [comment]
Can we move this to the subrepos? I use this package heavily in several products.

**Comment by dmitshur** [comment]
By now we have answers to those questions from 6 years ago: removing a golang.org/x package involves deprecating it, isolating it to its own nested module, tagging that, and then deleting from main branch. See past examples like #57051, #56783, #59676, #70229, and so on (also see #60557 which is about documenting the process better).

This issue would need to go through the proposal process, though.
