### ISSUE TITLE
crypto/x509: MaxConstraintComparisions typo: "Comparisions" should be "Comparisons"

### ISSUE THREAD

**Issue by alexkohler** [golang/go#27969]
[x509.MaxConstraintComparisions](https://github.com/golang/go/blob/master/src/crypto/x509/verify.go#L208) has a typo in "Comparisions". I don't think this can be fixed in the immediate future, but perhaps in Go 2.0?

**Comment by ALTree** [comment]
cc @agl @FiloSottile

**Comment by rsc** [comment]
Sorry, nothing we can do (exposed in Go 1.10). Maybe if some day we add field aliases we can fix it.
