### ISSUE TITLE
wasm: node.js wiki example fails; syntax error in wasm_exec.js reported

### ISSUE THREAD

**Issue by dtenenba** [golang/go#27972]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.11.1 darwin/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
$ go env | egrep "GOOS|GOARCH"
GOARCH="amd64"
GOOS="darwin"
```

macOS 10.14

### What did you do?

I followed the [wiki example](https://github.com/golang/go/wiki/WebAssembly). 
I ran every step on that page, up to and including the first command in the
[node.js section](https://github.com/golang/go/wiki/WebAssembly#executing-webassembly-with-nodejs-for-go-run-go-test). 

### What did you expect to see?

I expected to see the output:

```
Hello, WebAssembly!
```

### What did you see instead?

```
$ GOOS=js GOARCH=wasm go run -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec" .
/usr/local/go/misc/wasm/wasm_exec.js:215
						));
						^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
exit status 1
```
It's not clear that there really is a syntax error in wasm_exec.js. The linter `eslint` does not report any problems with that file.

**Comment by dmitshur** [comment]
I can't reproduce this with Go 1.11.1:

```
$ go version
go version go1.11.1 darwin/amd64
$ cat main.go 
package main

import "fmt"

func main() {
	fmt.Println("Hello, WebAssembly!")
}
$ go run .
Hello, WebAssembly!
$ GOOS=js GOARCH=wasm go run -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec" .
Hello, WebAssembly!
```

What version of node are you using? I have:

```
$ node --version
v10.6.0
```

**Comment by dmitshur** [comment]
Also, can you run this command and make sure you get the same output?

```
$ shasum -a 256 /usr/local/go/misc/wasm/wasm_exec.js
46ea07e1b594c1d5b163d875c54fac43b5d878f109c4e9ed5801bce20355b3c2  /usr/local/go/misc/wasm/wasm_exec.js
```

**Comment by dtenenba** [comment]
The file had the same checksum. But I was running node 6.7.0. I upgraded to the same version as you and the example worked! For anyone coming across this, this is how I upgraded:

```
sudo npm install n -g
sudo n 10.6.0
```

That was just for comparison with @dmitshur 's environment. Then I went ahead and upgraded to the latest stable version and the example still worked:

```
sudo n stable
```
