### ISSUE TITLE
Command 'go' not found...

### ISSUE THREAD

**Issue by 712Jefferson** [golang/go#27984]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11.1

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04

### What did you do?
I had previously installed 1.11 according the doc instructions and could use go commands without issue through terminal.  Yesterday, I replaced 1.11 with 1.11.1 and initially could use go commands.  However, upon restarting the computer, I suddenly have been completely unable to execute any go command.  I keep getting the message that "command go not founc, but can be installed with", etc.  Extremely frustrating.  I have tried reinstalling, editing path variables, removing, replacing, etc.  Nothing has fixed this issue and I simply cannot figure it out.  Any thoughts?

**Comment by bradfitz** [comment]
For questions about Go, see https://golang.org/wiki/Questions.

When you email golang-nuts, be sure to include more details, like your environment, where it was installed before, etc.
