### ISSUE TITLE
go/importer: remove support for (now defunct) binary export format (reminder issue)

### ISSUE THREAD

**Issue by griesemer** [golang/go#27999]
The compiler only generates the new indexed export format, and any support for the old binary export format has been removed.

We can eliminate the support from go/importer as well.

(Before we do, double-check that the latest version of that code is ported to x/tools where it needs to survive for another 3 release cycles - until 1.14.)

**Comment by alandonovan** [comment]
We can't fix this bug until we've done https://github.com/golang/go/issues/28260, otherwise there will be no export data format that go/types can both read and write.

**Comment by griesemer** [comment]
Moving to 1.13 - depends on #28260.

**Comment by griesemer** [comment]
#28260 has been fixed.

Verify that we don't need the binary export format anywhere before taking action on this.

cc: @stamblerre

**Comment by griesemer** [comment]
Moving tentatively to 1.14.

**Comment by dmitshur** [comment]
This issue is currently labeled as early-in-cycle for Go 1.15. That [time is now](https://groups.google.com/d/msg/golang-dev/y0yM_Xi665Q/mk35pLnjCAAJ), so friendly ping. If it no longer needs to be done early in cycle, that label can be removed.

**Comment by bcmills** [comment]
This broke current tests in `x/tools`, so it either needs to be reverted or those tests need to be updated or removed ASAP.

**Comment by griesemer** [comment]
The x/tools breakage has been fixed. Closing again.
