### ISSUE TITLE
runtime: throw in sweepone

### ISSUE THREAD

**Issue by mdempsky** [golang/go#27997]
I got a bizarre-looking misc-vet-all flake on CL 76311: https://storage.googleapis.com/go-build-log/46b1d0b9/misc-vet-vetall_0e3975bb.log

Looks like it must be the "non in-use span in unswept list" throw.

**Comment by cherrymui** [comment]
https://build.golang.org/log/4f04cd589f5f368ae6cdfa6f1e48de64387eef99 on darwin-amd64_10_10 builder encountered "non in-use span in unswept list" throw.

cc @aclements

**Comment by ianlancetaylor** [comment]
Another instance in #28003.

CC @aclements @RLH

**Comment by aclements** [comment]
Trybot failure on golang.org/cl/139459: https://storage.googleapis.com/go-build-log/02ba3822/windows-386-2008_e8e78a47.log

**Comment by aclements** [comment]
This is almost certainly related to 873bd47dfb34ba4416d4df30180905250b91f137 (https://golang.org/cl/134783)
