### ISSUE TITLE
net: accept <addr>: use of closed network connection

### ISSUE THREAD

**Issue by jadekler** [golang/go#27998]
### What version of Go are you using (`go version`)?

`go version go1.11 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

amd64/darwin

### What did you do?

`server, err := net.Listen("tcp", "localhost:0")` followed by several `conn, err := server.Accept()` / `conn.Close()` pairs in a row.

### What did you expect to see?

No errors.

### What did you see instead?

Once in every ~10 tests or so, `server.Accept()` returns something like `accept tcp 127.0.0.1:49613: use of closed network connection`. I'm not sure what this error means: how can Accept state that the "network connection" is closed when its job is to _establish_ (not use) a connection? Is the listener dead somehow? How is that possible without me having called `server.Close()`?

**Comment by ianlancetaylor** [comment]
Can you show us the complete program that demonstrates the problem?

**Comment by jadekler** [comment]
So sorry - in the process of making the repro, we found out that the server does indeed get closed and then hides the underlying failure. Shoot. Sorry for wasting y'alls time!
