### ISSUE TITLE
cmd/go: output of 'go build' in module mode is the major version

### ISSUE THREAD

**Issue by hyangah** [golang/go#28004]
If the module version is vN (N > 1) and the main package is defined in the root of the module,
the binary name is 'vN'.

<pre>
$ git clone https://github.com/hyangah/foo.git /tmp/foo
$ cd /tmp/foo
$ cat go.mod
module github.com/hyangah/foo/v2
$ ls
go.mod	lib	main.go
$ go build
$ ./v2
version 2
</pre>

**Comment by agnivade** [comment]
Looks like in module mode, the binary name is taken from package name instead of the dir name.

@bcmills

**Comment by mvdan** [comment]
Would this not have been fixed with https://github.com/golang/go/issues/24667? Or is this case different?

**Comment by agnivade** [comment]
Duh .. mistakenly marked it as 1.11.2.

**Comment by hyangah** [comment]
@mvdan 'install' works as intended in #24667. Didn't look into the code path carefully and I am guessing 'build' picks the default output name in a different way.

**Comment by bcmills** [comment]
Dup of #27283.
