### ISSUE TITLE
cmd/go: make -trimpath a list

### ISSUE THREAD

**Issue by hugelgupf** [golang/go#28002]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11rc2

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
go build -gcflags=-trimpath=/tmp/foo:/tmp/bar

I'd like to be able to trim multiple paths for fully reproducible multi-GOPATH builds in different users' environments.

> For now you can only trim one prefix. We could plausibly make -trimpath take a list for Go 1.7. If that's useful to you please file a new issue. Thanks. - @rsc in #13809

**Comment by bcmills** [comment]
Dup of #22382, I think.
