### ISSUE TITLE
go/fmt: `go fmt` formats two maps with same key/value pair differently depending on how the key is placed

### ISSUE THREAD

**Issue by a4abhishek** [golang/go#28010]
### What version of Go are you using (`go version`)?
go version go1.9.3 linux/amd64

### Does this issue reproduce with the latest release?
I am not sure, but I think it will be reproduced because it is getting reproduced in Go-Playground.

### What operating system and processor architecture are you using (`go env`)?
Operating System: Linux
Processor architecture: AMD64
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/abhishek/GoWorkspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build268663230=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
I have created two maps with same key-value pairs, just written them in different order. One gets formatted correctly while other doesn't.

Here is the Go-Playground link: https://play.golang.org/p/UV1HXJMp3f6

### What did you expect to see?
Both maps in the above sample should be formatted in the same way (the way second sample gets formatted).

### What did you see instead?
Both maps formats differently.

**My Observation:** It depends more on the length of the surrounding (above/below) key than on the difference in the length of the "victim" key and surrounding key. (but affected by both)

**Comment by agnivade** [comment]
playground is still running 1.10.3. This is fixed in 1.11.

If you still have issues after using 1.11, feel free to comment.
