### ISSUE TITLE
x/sys/unix: add SignalNum() to convert signal name to a number

### ISSUE THREAD

**Issue by kolyshkin** [golang/go#28027]
A `SignalName()` method was recently (https://github.com/golang/go/issues/25134) added to x/sys/unix to convert a numeric signal id to a name. It uses `signalList` array which contains names and numeric values for all known signals on every platform.

This is a proposal to add a complementary method to convert a string representation to a number.

```go
// SignalNum returns the syscall.Signal for signal named s,
// or an error if a signal with such name is not found.
func SignalNum(s string) (syscall.Signal, error)
```

For example, `SignalNum("SIGTERM")` is to return `15, nil`, and it should probably do the same for `SignalNum("TERM")` and `SignalNum("term")`.

**Update**: `s/SignalId/SignalNum/`

**Comment by ianlancetaylor** [comment]
Now that we have `SignalName`, you can write this yourself.  Is this really a common enough desire to put it in the package?

**Comment by kolyshkin** [comment]
Currently quite a few packages have to implement it, here are a few examples:

* [`x/crypto/ssh`](https://github.com/golang/crypto/blob/e3636079e1a4c1f337f212cc5cd2aca108f6c900/ssh/session.go#L22)
* [Docker](https://github.com/moby/moby/blob/192ff56d879238ecd6af8895a7ebe820a4a57a49/pkg/signal/signal_linux.go#L14)
* [containerd](https://github.com/containerd/containerd/blob/master/signal_map_unix.go#L27)
* [runc](https://github.com/opencontainers/runc/blob/master/signalmap.go#L12)

**Comment by kolyshkin** [comment]
An alternative would be to expose `signalList`, which I think is much less maintainable long term.

**Comment by tklauser** [comment]
@ianlancetaylor I don't think we can use `SignalName` to implement that as it maps a signal number to a string. But what's proposed here is the reverse operation (string to signal number). Or am I missing something?

@kolyshkin I'd propose to name the proposed function `SignalNum` instead of `SignalId`, as the `signal(2)` and `signal(7)` use the term _signal number_ to refer to the numeric signal id.

**Comment by ianlancetaylor** [comment]
```Go
func SignalNum(s string) syscall.Signal {
	for i := syscall.Signal(1); ; i++ {
		sn := unix.SignalName(i)
		if sn == s {
			return i
		}
		if sn == "" {
			return 0
		}
	}
}
```

**Comment by tklauser** [comment]
Are signal number guaranteed to be contiguous? At least on linux they seem to be. But looking at the recently added `zerrors_aix_*.go` I see:

```Go
var signalList = [...]struct {
        num  syscall.Signal
        name string
        desc string
}{
// ...
        {39, "SIGWAITING", "signal 39"},
        {48, "SIGSYSERROR", "signal 48"},
        {49, "SIGCAPI", "signal 49"},
        {58, "SIGRECONFIG", "signal 58"},
        {59, "SIGCPUFAIL", "CPU Failure Predicted"},
        {60, "SIGGRANT", "monitor mode granted"},
        {61, "SIGRETRACT", "monitor mode retracted"},
        {62, "SIGSOUND", "sound completed"},
        {63, "SIGMAX32", "secure attention"},
        {255, "SIGMAX", "signal 255"},
}
```

so on aix something like

```Go
num := SignalNum("SIGSYSERROR")
```

wouldn't work.

**Comment by tklauser** [comment]
We could add `unix.NSIG` though and then do:

```go
func SignalNum(s string) syscall.Signal {
	for i := syscall.Signal(1); i < syscall.Signal(unix.NSIG); i++ {
		sn := unix.SignalName(i)
		if sn == s {
			return i
		}
	}
	return 0
}
```

**Comment by ondrej-fabry** [comment]
@tklauser It also needs some check if `s == ""` otherwise it will return first undefined signal.

**Comment by tklauser** [comment]
@ondrej-fabry oops, right. Thank you. The proposed `SignalNum` is supposed to be implemented outside of `golang.org/x/sys/unix` (see https://github.com/golang/go/issues/28027#issuecomment-427187147) thus we cannot use `signalList` directly.

**Comment by ondrej-fabry** [comment]
@tklauser right, got that

btw, loop could start from 0 to eliminate need for extra check of `s == ""` and go until 255 for maximum possible signal number.

```go
func SignalNum(s string) syscall.Signal {
	for i := syscall.Signal(0); i < syscall.Signal(255); i++ {
		sn := unix.SignalName(i)
		if sn == s {
			return i
		}
	}
	return 0
}
SignalNum("") // will return 0
```

**Comment by kolyshkin** [comment]
As previous comments demonstrate, it is slightly less than trivial to write `SignalNum()` implementation based on `unix.SignalName()`. Perhaps it is easier to add `SignalNum()` right into the package?

**Comment by kolyshkin** [comment]
I have updated title and description to use `SignalNum()` rather than `SignalId()` as per @tklauser suggestion at https://github.com/golang/go/issues/28027#issuecomment-427269612

**Comment by tklauser** [comment]
@kolyshkin I agree, it might be better to just add `SignalNum` to the package. Want to send a CL?
