### ISSUE TITLE
Sophos anti virus issue in Windows OS at compile time

### ISSUE THREAD

**Issue by surya-rakanta** [golang/go#28031]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.11.1.windows-386

### What operating system and processor architecture are you using (`go env`)?

Windows 7 Intel IA 64 bit

### What did you do?

When I try to compile the helloworld.go in the test folder, Sophos anti virus detects it as Mal/Zbot-FG.

Detailed article as follows:

https://excellentcorner.com/2018/10/05/exploration-of-golang-in-windows-environment/

**Comment by agnivade** [comment]
This has come up before. Please see - https://golang.org/doc/faq#virus.

You can match the checksums to verify that the file is correct.
