### ISSUE TITLE
Where are the dependencies saved when we use go mod

### ISSUE THREAD

**Issue by pprasanthi** [golang/go#28048]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pprasanthi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pprasanthi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pprasanthi/gomodtry/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/43/hr2mln315bgdqfyr9_bcr38r0000gn/T/go-build737361379=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

1. cd /tmp/gomodtry/tests/src/hello/hello_test.go
package tests

import (
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

func GetEnv(key string, fallback string) string {
        envVariable := os.Getenv(key)
        if envVariable == "" {
                return fallback
        }
        return envVariable
}

func TestHello(t *testing.T) {
	val := GetEnv("check", "ok")
	assert.Equal(t, "ok", val, "val is not equal to ok")
}

func TestHello1(t *testing.T) {
	val := GetEnv("check", "ok")
	assert.Equal(t, "ok", val, "val is not equal to ok")
}

2. export GO111MODULE=on

3. go test ./...
This created go.mod and go.sum files in  cd /tmp/gomodtry/ location
When I executed go test ./... -v again , it executed the tests successfully.

QUESTION:
1. Where is the dependent `github.com/stretchr/testify/assert` downloaded - I dont see it downloaded any where. Before go mod concept when we set GOPATH and then go get dependency, it used to download physically. Can you please explain how the test is resolving dependency with it physically not present.

2. In previous version, when we go get dependencies, some times we used to get 500 error because the host where dependency exists will be down temporarily. Do we still face this kind of issues with go mod concepts? How is it handled? [we did not like vendoring of dependencies, so we end up doing go get for every test run, which made of tests runs unstable when the host went down]

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by agnivade** [comment]
Hi @pprasanthi ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

You might want to take a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.
