### ISSUE TITLE
cmd/pprof: web and -web isn't working properly

### ISSUE THREAD

**Issue by xibz** [golang/go#28059]
### What version of Go are you using (`go version`)?
1.11.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Mac OSX

### What did you do?
`go tool pprof -web cpu.profile binary`
or
`pprof> web`

### What did you expect to see?
Expected to see a web browser to view my benchmarks

### What did you see instead?
Gimp attempting to open

**Comment by meirf** [comment]
@xibz can you give more detail on what you are seeing?

Pprof visualizations each have external dependencies so we'd like to make sure this is something wrong with go as opposed to your local installation of one the visualization dependencies.

**Comment by meirf** [comment]
See this comment here: https://github.com/golang/go/issues/11729#issuecomment-122527070

> On a side note: "web" seems a misnomer for the current implementation. It uses xdg-open on Linux and at least on some systems xdg-open doesn't launch a browser but gimp to view the svg.

I recommend asking more about this on go nuts since this seems somewhat expected and has been around for a while. Thought one oddity is that comment says this happens on linux whereas you claim to be using mac osx.

**Comment by xibz** [comment]
Ah, figured out the issue. `pprof` uses macs `/usr/bin/open` command so it will use whatever default it opens too. I recently uninstalled my default browser for another and it made the default gimp. Sorry for the noise. Cheers.
