### ISSUE TITLE
semver/mod for golang.org/x/net?

### ISSUE THREAD

**Issue by marcosrmendezthd** [golang/go#28056]
Please answer these questions before submitting your issue. Thanks!

More of a question than an actual issue. Are we planning on creating a module or at least having semver tags for this repo?

### What version of Go are you using (`go version`)?
1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/go/bin"
GOCACHE="/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sp/rhgzbyts4g79g0wxjz6hym1m0000gn/T/go-build378388908=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

go get -u golang.org/x/net

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ALTree** [comment]
>  Are we planning on creating a module or at least having semver tags for this repo?

Yes. This is issue #21324. Brad wrote:

> On hold until Go 1.11 and/or Go 1.12. At least until we have tooling ready and some experience with said tooling.

So it'll happen, in the near future. Hope this answer your question. Closing here, since we already track this in #21324.
