### ISSUE TITLE
cmd/go: compiler crash on uncomparable map keys

### ISSUE THREAD

**Issue by go101** [golang/go#28058]
### What version of Go are you using (`go version`)?

go version go1.11.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```golang
package main

var x map[func()]int

func main() {
}
```

### What did you expect to see?

not crash

### What did you see instead?

crash
```
# command-line-arguments
<autogenerated>:1: internal compiler error: unsupported map key type for map[func()]int

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by meirf** [comment]
It looks like this also crashed in go1.10, but not in go1.9. Labeling as 1.12 since not a regression from 1.10.

/cc @griesemer

**Comment by mvdan** [comment]
For reference, this is what Go 1.9.7 prints:

```
$ go build f.go
# command-line-arguments
./f.go:3:7: invalid map key type func()
```

**Comment by odeke-em** [comment]
Thanks for the report @go101 and @meirf @mvdan for the discernment.

I believe this was introduced by CL https://go-review.googlesource.com/61035 aka commit https://github.com/golang/go/commit/bb31217579974587871a6b7d278ec186f93df126 which moved the order of those checks /cc @martisch @randall77

**Comment by odeke-em** [comment]
Thanks for the correction and investigation @mvdan!
