### ISSUE TITLE
Proposal: Go 2: database/sql: Do what ever is required to make mysql queries truly cancellable.

### ISSUE THREAD

**Issue by pjebs** [golang/go#28074]
The way `database/sql` is designed is currently flawed. I found out the issue is more serious that I previously thought.

This proposal is a deferment to higher minds to solve this issue because I don't have expertise to even explain it here:

See: https://github.com/go-sql-driver/mysql/issues/863#issuecomment-427809493

See: https://github.com/golang/go/issues/27962

**Comment by kardianos** [comment]
I'm aware of this issue. With connectors, adding a single dedicated canceller connection is possible now. However, the fundamental problem is MySQL problem, not database/sql .
