### ISSUE TITLE
time: test failure TestParseInLocation

### ISSUE THREAD

**Issue by westrength** [golang/go#28075]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
    go version go1.4-bootstrap-20170531 linux/amd64

### Does this issue reproduce with the latest release?
    Yes. go 1.8.1 and 1.11.1 has the same issue.

### What operating system and processor architecture are you using (`go env`)?

    GOARCH="amd64"
    GOBIN=""
    GOCHAR="6"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH=""
    GORACE=""
    GOROOT="/home/hello/go1.4"
    GOTOOLDIR="/home/hello/go1.4/pkg/tool/linux_amd64"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -fmessage-length=0"
    CXX="g++"
    CGO_ENABLED="0"

### What did you do?

    If possible, provide a recipe for reproducing the error.

### What did you expect to see?

    ALL TESTS PASSED 
    ---
    Installed Go for linux/amd64 in /home/hello/git/go
    Installed commands in /home/hello/git/go/bin
    *** You need to add /home/hello/git/go/bin to your PATH.

### What did you see instead?

    ok  	testing/quick	0.142s
    ok  	text/scanner	0.018s
    ok  	text/tabwriter	0.016s
    ok  	text/template	0.137s
    ok  	text/template/parse	0.055s
    --- FAIL: TestParseInLocation (0.02s)
	    format_test.go:263: ParseInLocation(Feb 01 2013 AST, Baghdad) = 2013-02-01 00:00:00 +0000 
    AST, want 2013-02-01 00:00:00 +0300 +03
    FAIL
    FAIL	time	3.796s
    ok  	unicode	0.011s
    ok  	unicode/utf16	0.010s
    ok  	unicode/utf8	0.018s
    ok  	cmd/addr2line	9.702s
    ok  	cmd/api	0.188s
    ok  	cmd/asm/internal/asm	1.721s
    ok  	cmd/asm/internal/lex	0.036s
    ok  	cmd/compile/internal/big	2.845s
    ok  	cmd/compile/internal/gc	1.905s
    ok  	cmd/cover	12.484s
    ok  	cmd/doc	0.338s
    ok  	cmd/fix	0.029s
    ok  	cmd/go	116.629s
    ok  	cmd/gofmt	0.817s
    ok  	cmd/internal/goobj	0.015s
    ok  	cmd/internal/obj	0.006s
    ok  	cmd/internal/obj/x86	0.011s
    ok  	cmd/internal/unvendor/golang.org/x/arch/arm/armasm	0.052s
    ok  	cmd/internal/unvendor/golang.org/x/arch/x86/x86asm	0.872s
    ok  	cmd/nm	5.160s
    ok  	cmd/objdump	12.139s
    ok  	cmd/pack	9.844s
    ok  	cmd/pprof/internal/profile	0.020s
    ok  	cmd/vet	11.229s
    2018/10/08 22:24:00 Failed: exit status 1

**Comment by agnivade** [comment]
I am unable to reproduce this in latest master.

Can you post the _exact_ steps that you performed to get the failure ? Including the download and build steps.

**Comment by westrength** [comment]
@agnivade ,This is detail:
<pre><font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$ go version
go version go1.4-bootstrap-20170531 linux/amd64
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$   wget -c https://storage.googleapis.com/golang/go1.11.1.linux-amd64.tar.gz -P ~/Downloads/
--2018-10-08 22:10:56--  https://storage.googleapis.com/golang/go1.11.1.linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.199.112, 2404:6800:4005:806::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.199.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 127205934 (121M) [application/octet-stream]
Saving to: ‘/home/hello/Downloads/go1.11.1.linux-amd64.tar.gz’

go1.11.1.linux-amd64.tar.gz         100%[=================================================================&gt;] 121.31M  1.81MB/s    in 97s     

2018-10-08 22:12:33 (1.26 MB/s) - ‘/home/hello/Downloads/go1.11.1.linux-amd64.tar.gz’ saved [127205934/127205934]

<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$  tar -xzf ~/Downloads/go1.8.1.linux-amd64.tar.gz -C ~/
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$  which go
/home/hello/go1.4/bin/go
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$  mv ~/go ~/go1.11.1
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$  GOROOT_BOOTSTRAP=/home/hello/go1.11.1 ./all.bash
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/hello/go1.11.1.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/compile/internal/big
bootstrap/internal/gcprog
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/mips
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/link/internal/ld
bootstrap/compile/internal/gc
bootstrap/asm/internal/arch
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/mips64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/mips64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/x86
bootstrap/compile

##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
unicode/utf16
internal/race
encoding
errors
sort
math
sync/atomic
internal/syscall/windows/sysdll
unicode
unicode/utf8
container/heap
sync
internal/singleflight
syscall
io
hash
hash/adler32
bytes
strings
strconv
bufio
path
internal/syscall/windows
internal/syscall/windows/registry
time
encoding/base64
regexp/syntax
reflect
crypto
crypto/sha1
os
regexp
encoding/binary
os/signal
fmt
path/filepath
os/exec
io/ioutil
debug/dwarf
go/token
compress/flate
flag
net/url
text/template/parse
encoding/json
log
go/scanner
go/ast
compress/zlib
text/template
debug/macho
debug/elf
go/parser
go/doc
go/build
cmd/go

##### Building packages and commands for linux/amd64.
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
unicode
unicode/utf8
math
sync
sort
io
syscall
hash
hash/adler32
hash/crc32
container/heap
container/list
container/ring
crypto/subtle
crypto/cipher
strconv
bytes
strings
bufio
time
reflect
path
regexp/syntax
text/tabwriter
compress/bzip2
crypto
crypto/aes
os
math/rand
regexp
crypto/sha512
crypto/hmac
crypto/md5
encoding/binary
internal/syscall/unix
crypto/rc4
fmt
path/filepath
crypto/des
crypto/sha1
crypto/sha256
encoding/base64
internal/singleflight
io/ioutil
encoding/pem
os/exec
encoding
encoding/ascii85
encoding/base32
unicode/utf16
hash/crc64
hash/fnv
html
image/color
flag
log
cmd/internal/unvendor/golang.org/x/arch/arm/armasm
cmd/internal/unvendor/golang.org/x/arch/x86/x86asm
cmd/internal/obj
compress/flate
compress/zlib
debug/dwarf
debug/gosym
cmd/internal/goobj
debug/plan9obj
archive/tar
archive/zip
compress/gzip
compress/lzw
math/big
debug/elf
debug/macho
debug/pe
encoding/hex
go/token
database/sql/driver
go/scanner
cmd/internal/objfile
database/sql
go/ast
crypto/dsa
crypto/elliptic
encoding/asn1
cmd/addr2line
crypto/rand
go/parser
crypto/ecdsa
crypto/x509/pkix
crypto/rsa
go/printer
encoding/csv
encoding/gob
encoding/json
cmd/cgo
encoding/xml
internal/golang.org/x/net/http2/hpack
mime
mime/quotedprintable
net/http/internal
net/url
text/template/parse
go/constant
go/format
text/scanner
image
go/types
text/template
image/color/palette
image/internal/imageutil
image/draw
image/gif
go/doc
html/template
go/build
runtime/cgo
image/jpeg
image/png
go/internal/gccgoimporter
go/internal/gcimporter
index/suffixarray
internal/syscall/windows/sysdll
runtime/debug
runtime/pprof
go/importer
runtime/trace
internal/trace
math/cmplx
testing
net/internal/socktest
os/signal
internal/testenv
runtime/race
testing/iotest
testing/quick
cmd/api
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/x86
net
os/user
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/asm/internal/arch
cmd/compile/internal/big
cmd/internal/gcprog
cmd/cover
cmd/asm/internal/asm
cmd/asm
cmd/compile/internal/gc
cmd/dist
cmd/doc
crypto/x509
net/textproto
mime/multipart
log/syslog
crypto/tls
net/mail
cmd/fix
cmd/gofmt
net/http
net/smtp
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
expvar
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/httputil
net/http/pprof
net/http/fcgi
net/rpc
cmd/compile/internal/x86
cmd/go
cmd/link/internal/ld
cmd/compile
net/rpc/jsonrpc
cmd/nm
cmd/objdump
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/pack
cmd/pprof/internal/profile
cmd/link
cmd/pprof/internal/svg
cmd/pprof/internal/tempfile
cmd/pprof/internal/plugin
cmd/pprof/internal/symbolz
cmd/pprof/internal/report
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/trace
cmd/vet/internal/whitelist
cmd/vet
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof
cmd/yacc


##### Testing packages.
ok  	archive/tar	0.875s
ok  	archive/zip	0.314s
ok  	bufio	0.157s
ok  	bytes	0.215s
ok  	compress/bzip2	0.289s
ok  	compress/flate	0.682s
ok  	compress/gzip	0.600s
ok  	compress/lzw	0.071s
ok  	compress/zlib	0.064s
ok  	container/heap	0.009s
ok  	container/list	0.027s
ok  	container/ring	0.069s
ok  	crypto/aes	0.117s
ok  	crypto/cipher	0.052s
ok  	crypto/des	0.027s
ok  	crypto/dsa	0.048s
ok  	crypto/ecdsa	0.254s
ok  	crypto/elliptic	0.243s
ok  	crypto/hmac	0.015s
ok  	crypto/md5	0.019s
ok  	crypto/rand	0.107s
ok  	crypto/rc4	0.404s
ok  	crypto/rsa	0.601s
ok  	crypto/sha1	0.022s
ok  	crypto/sha256	0.058s
ok  	crypto/sha512	0.022s
ok  	crypto/subtle	0.033s
ok  	crypto/tls	3.860s
ok  	crypto/x509	6.786s
ok  	database/sql	0.195s
ok  	database/sql/driver	0.023s
ok  	debug/dwarf	0.072s
ok  	debug/elf	0.193s
ok  	debug/gosym	1.584s
ok  	debug/macho	0.066s
ok  	debug/pe	0.073s
ok  	debug/plan9obj	0.050s
ok  	encoding/ascii85	0.026s
ok  	encoding/asn1	0.044s
ok  	encoding/base32	0.027s
ok  	encoding/base64	0.019s
ok  	encoding/binary	0.011s
ok  	encoding/csv	0.021s
ok  	encoding/gob	0.225s
ok  	encoding/hex	0.032s
ok  	encoding/json	0.936s
ok  	encoding/pem	0.033s
ok  	encoding/xml	0.044s
ok  	errors	0.021s
ok  	expvar	0.012s
ok  	flag	0.008s
ok  	fmt	0.472s
ok  	go/ast	0.027s
ok  	go/build	2.343s
ok  	go/constant	0.017s
ok  	go/doc	0.516s
ok  	go/format	0.096s
ok  	go/internal/gccgoimporter	0.077s
ok  	go/internal/gcimporter	0.785s
ok  	go/parser	0.171s
ok  	go/printer	1.317s
ok  	go/scanner	0.019s
ok  	go/token	0.101s
ok  	go/types	3.487s
ok  	hash/adler32	0.032s
ok  	hash/crc32	0.013s
ok  	hash/crc64	0.009s
ok  	hash/fnv	0.024s
ok  	html	0.027s
ok  	html/template	0.136s
ok  	image	0.581s
ok  	image/color	0.436s
ok  	image/draw	0.392s
ok  	image/gif	0.361s
ok  	image/jpeg	0.737s
ok  	image/png	0.236s
ok  	index/suffixarray	0.090s
ok  	internal/golang.org/x/net/http2/hpack	0.052s
ok  	internal/singleflight	0.045s
ok  	internal/trace	0.063s
ok  	io	0.063s
ok  	io/ioutil	0.067s
ok  	log	0.080s
ok  	log/syslog	2.065s
ok  	math	0.024s
ok  	math/big	1.499s
ok  	math/cmplx	0.011s
ok  	math/rand	0.491s
ok  	mime	0.081s
ok  	mime/multipart	1.762s
ok  	mime/quotedprintable	1.008s
ok  	net	3.160s
ok  	net/http	15.427s
ok  	net/http/cgi	2.914s
ok  	net/http/cookiejar	0.094s
ok  	net/http/fcgi	4.210s
ok  	net/http/httptest	4.213s
ok  	net/http/httputil	0.145s
ok  	net/http/internal	0.014s
ok  	net/internal/socktest	0.016s
ok  	net/mail	0.015s
ok  	net/rpc	0.088s
ok  	net/rpc/jsonrpc	0.030s
ok  	net/smtp	0.099s
ok  	net/textproto	0.023s
ok  	net/url	0.014s
ok  	os	1.184s
ok  	os/exec	0.731s
ok  	os/signal	4.389s
ok  	os/user	0.015s
ok  	path	0.005s
ok  	path/filepath	0.215s
ok  	reflect	0.258s
ok  	regexp	0.910s
ok  	regexp/syntax	1.223s
ok  	runtime	105.567s
ok  	runtime/debug	0.027s
ok  	runtime/internal/atomic	0.237s
ok  	runtime/pprof	2.664s
ok  	runtime/trace	7.658s
ok  	sort	0.179s
ok  	strconv	1.375s
ok  	strings	0.184s
ok  	sync	0.284s
ok  	sync/atomic	1.100s
ok  	syscall	0.156s
ok  	testing	1.550s
ok  	testing/quick	0.142s
ok  	text/scanner	0.018s
ok  	text/tabwriter	0.016s
ok  	text/template	0.137s
ok  	text/template/parse	0.055s
--- FAIL: TestParseInLocation (0.02s)
	format_test.go:263: ParseInLocation(Feb 01 2013 AST, Baghdad) = 2013-02-01 00:00:00 +0000 AST, want 2013-02-01 00:00:00 +0300 +03
FAIL
FAIL	time	3.796s
ok  	unicode	0.011s
ok  	unicode/utf16	0.010s
ok  	unicode/utf8	0.018s
ok  	cmd/addr2line	9.702s
ok  	cmd/api	0.188s
ok  	cmd/asm/internal/asm	1.721s
ok  	cmd/asm/internal/lex	0.036s
ok  	cmd/compile/internal/big	2.845s
ok  	cmd/compile/internal/gc	1.905s
ok  	cmd/cover	12.484s
ok  	cmd/doc	0.338s
ok  	cmd/fix	0.029s
ok  	cmd/go	116.629s
ok  	cmd/gofmt	0.817s
ok  	cmd/internal/goobj	0.015s
ok  	cmd/internal/obj	0.006s
ok  	cmd/internal/obj/x86	0.011s
ok  	cmd/internal/unvendor/golang.org/x/arch/arm/armasm	0.052s
ok  	cmd/internal/unvendor/golang.org/x/arch/x86/x86asm	0.872s
ok  	cmd/nm	5.160s
ok  	cmd/objdump	12.139s
ok  	cmd/pack	9.844s
ok  	cmd/pprof/internal/profile	0.020s
ok  	cmd/vet	11.229s
2018/10/08 22:24:00 Failed: exit status 1
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$   go version
go version go1.4-bootstrap-20170531 linux/amd64
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$  go env
GOARCH=&quot;amd64&quot;
GOBIN=&quot;&quot;
GOCHAR=&quot;6&quot;
GOEXE=&quot;&quot;
GOHOSTARCH=&quot;amd64&quot;
GOHOSTOS=&quot;linux&quot;
GOOS=&quot;linux&quot;
GOPATH=&quot;&quot;
GORACE=&quot;&quot;
GOROOT=&quot;/home/hello/go1.4&quot;
GOTOOLDIR=&quot;/home/hello/go1.4/pkg/tool/linux_amd64&quot;
CC=&quot;gcc&quot;
GOGCCFLAGS=&quot;-fPIC -m64 -fmessage-length=0&quot;
CXX=&quot;g++&quot;
CGO_ENABLED=&quot;0&quot;
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$ 
<font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~/git-my/go/src</b></font>$ 
</pre>

**Comment by ianlancetaylor** [comment]
I don't understand why the error message says line 263.  That error is on line 282 of format_test.go in Go 1.8, Go 1.11, and tip.  Where is the 263 coming from?  What does `TestParseInLocation` look like in your copy of time/format_test.go?

**Comment by ALTree** [comment]
Also what's the version of `tzdata` on your system? E.g.

```
$ apt-cache policy tzdata

tzdata:
  Installed: 2018e-1
  Candidate: 2018e-1
```

**Comment by westrength** [comment]
@ALTree 
<pre><font color="#8AE234"><b>hello@hello</b></font>:<font color="#729FCF"><b>~</b></font>$  apt-cache policy tzdata
tzdata:
  Installed: 2018e-0ubuntu0.18.04
  Candidate: 2018e-0ubuntu0.18.04
  Version table:
</pre>

**Comment by westrength** [comment]
Thank you for your reminder.I fixed it by add " t.Skip("skipping test for Go 1.4; Issue 19457") " at 187.
more detail: https://go-review.googlesource.com/c/go/+/66073/2/src/time/format_test.go#187

**Comment by agnivade** [comment]
Wait, so you were trying to compile 1.4 ? Using 1.11 and 1.8 as the bootstrap version ?

> Yes. go 1.8.1 and 1.11.1 has the same issue.

So then this is incorrect. Because the issue is in 1.4, not 1.8 or 1.11. You are just using those to bootstrap the build.

In any case, we do not accept fixes to the 1.4 branch anymore. Cherry picks are only done to the last 2 major releases.

**Comment by westrength** [comment]
@agnivade Ok.Thank you.

**Comment by westrength** [comment]
@agnivade Can you help me that you git clone https://go.googlesource.com/go and send to me by email.Because I am in china that GWF interference git .Thank you very much.

**Comment by agnivade** [comment]
I think the best way is to reach out for help in the various forums that we have - https://github.com/golang/go/wiki/Questions. Folks will gladly help you out.

Thanks.
