### ISSUE TITLE
sort: Strings should use 3-way radix quicksort

### ISSUE THREAD

**Issue by jordancurve** [golang/go#28071]
"3-way radix quicksort is the method of choice for sorting strings" – Robert Sedgewick (https://www.cs.princeton.edu/~rs/AlgsDS07/18RadixSort.pdf , slide 29)

In my tests, 3-way radix quicksort is about twice as fast as Go 1.11's sort.Strings.

Rough demo code: https://play.golang.org/p/KGVIX6Cwha8

**Comment by agnivade** [comment]
Please do share your benchmark numbers. We already have tests for those in the standard library. And if you already have a working version, why not send a CL ? ;)

@vdobler @griesemer

**Comment by vdobler** [comment]
@jordancurve Please also pay attention to pathological (or even malicious) inputs. Average runtime is very important but pathological inputs must not result in e.g. quadratic runtime or large space (here stack) overhead.

**Comment by agnivade** [comment]
From the comment in the CL - 

> I am withdrawing this proposal until the performance regression with sorting long identical strings is resolved. I would like to thank the reviewers for their attention and suggestions. The radix sorting code is available as a stand-alone library at https://github.com/jordancurve/radix.
