### ISSUE TITLE
cmd/go: reference to v2 module incorrectly using subdirectory of module 

### ISSUE THREAD

**Issue by hyangah** [golang/go#28083]
In the source tree of the queried package (and its module)

<pre>
$ cd /tmp
$ git clone https://github.com/hyangah/explist2
$ cd explist2
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}}' github.com/hyangah/explist2
github.com/hyangah/explist2 in github.com/hyangah/explist2@
</pre>

vs.

<pre>
$ mkdir /tmp/temp
$ cd /tmp/temp
$ go mod init temp
go: creating new go.mod: module temp
$ go get github.com/hyangah/explist2
go: finding github.com/hyangah/explist2 v1.0.0
go: downloading github.com/hyangah/explist2 v1.0.0
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}}' github.com/hyangah/explist2
github.com/hyangah/explist2 in github.com/hyangah/explist2@v1.0.0
</pre>

**Comment by myitcv** [comment]
In the first case you are asking for the version of a module within the source tree for that module. To my mind the version of a module in this situation is undefined.

```
$ cd /tmp
$ git clone https://github.com/hyangah/explist2
Cloning into 'explist2'...
$ cd explist2
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}} [{{.Module.Dir}}]' github.com/hyangah/explist2
github.com/hyangah/explist2 in github.com/hyangah/explist2@ [/tmp/explist2]
```

In the second case you are querying a module as a dependency (that is present within the readonly-module cache). In this situation the module has been resolved via MVS and hence has a version associated with it.

```
$ mkdir /tmp/temp
$ cd /tmp/temp
$ go mod init temp
go: creating new go.mod: module temp
$ go get github.com/hyangah/explist2
go: finding github.com/hyangah/explist2 v1.0.0
go: downloading github.com/hyangah/explist2 v1.0.0
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}} [{{.Module.Dir}}]' github.com/hyangah/explist2
github.com/hyangah/explist2 in github.com/hyangah/explist2@v1.0.0 [/root/pkg/mod/github.com/hyangah/explist2@v1.0.0]
```

What version would you expect to be returned in the first instance out of interest?

**Comment by hyangah** [comment]
Thanks for the explanation @myitcv . That makes sense.
I thought the above was a simple repro case for what I originally wanted to report. But clearly, that is not the case. 

<pre>
$ pwd
/tmp/explist2
$ tree
.
├── f.go
├── go.mod
├── go.sum
└── v2
    ├── f.go
    ├── go.mod
    └── go.sum
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}}' github.com/hyangah/explist2/v2
github.com/hyangah/explist2/v2 in github.com/hyangah/explist2@
</pre>

The v2 is set up following the major subdirectory model. I expect querying v2 from the repo root directory to return the same result as the query outside the repo. But it's not. Moreover, it doesn't seem to recognize the `v2` as the major version mark.

If I query from the v2 directory, at list the go list seemed to recognize `v2` as a version mark.
<pre>
$ cd v2
$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}}' github.com/hyangah/explist2/v2
github.com/hyangah/explist2/v2 in github.com/hyangah/explist2/v2@
</pre>

**Comment by myitcv** [comment]
> If I query from the v2 directory, at list the go list seemed to recognize v2 as a version mark.

I don't think the `"v2"` in `"github.com/hyangah/explist2/v2"` can be considered a version per se, rather a convention on import paths. Indeed that import path comes entirely from the `go.mod`, not the fact that the `go.mod` is in a directory called `v2` within `github.com/hyangah/explist2`.

cc @bcmills who will undoubtedly be tighter on the wording/definitions here than I am.

**Comment by hyangah** [comment]
I should've used better wording.  
The confusing part is the go.mod file in the subdirectory is not recognized.
The go list command considers any package under subdirectory to be part of the main module.

Even when I added a dependency on v2 from v1, the result is same. 

<pre>
$ cat f.go
package explist2

import "github.com/hyangah/explist2/v2"

var Name = explist2.Name

$ cat go.mod
module github.com/hyangah/explist2

require github.com/hyangah/explist2/v2 v2.0.1

$ go list -f '{{.ImportPath}} in {{.Module.Path}}@{{.Module.Version}}' github.com/hyangah/explist2/v2
github.com/hyangah/explist2/v2 in github.com/hyangah/explist2@
</pre>

**Comment by bcmills** [comment]
I don't know what was going on before, but as far as I can tell this is working as designed with `go1.12beta2`.

The `v2/go.mod` file prevents `go` from finding `v2` in the main module, so it fetches from the tagged `v2.0.1` instead:

```
explist2$ cat f.go
package explist2

import _ "github.com/hyangah/explist2/v2"

var Name = "explist2"

explist2$ go list -f '{{.ImportPath}} (from {{with .Module}}{{.Path}}@{{.Version}}{{end}}) {{.Dir}}' all
github.com/hyangah/explist2 (from github.com/hyangah/explist2@) /tmp/tmp.dhjf2me7MN/explist2
github.com/hyangah/explist2/v2 (from github.com/hyangah/explist2/v2@v2.0.1) /tmp/tmp.bNoat8kDP6/_gopath/pkg/mod/github.com/hyangah/explist2/v2@v2.0.1
```
