### ISSUE TITLE
x/talks: cannot deploy to GAE using gcloud app deploy

### ISSUE THREAD

**Issue by andybons** [golang/go#28080]
App Engine requires that the Go files be in the same directory as app.yaml, but the current instructions say to copy the `present/` dir from `x/tools/cmd/` into the root of the x/talks repo. Since that still leaves no Go source files in the same directory as `app.yaml` it fails with: `no buildable Go source files in $GOPATH/src/golang.org/x/talks`

Plan is to merge App Engine and "local" logic into one binary without build tags, then run it on GAE Flex.

/cc @bradfitz @dmitshur

**Comment by bradfitz** [comment]
When did this break?

**Comment by andybons** [comment]
At least before summer. The same thing happened to the blog and it was easy enough to move the go files up a directory so they were in the same place as app.yaml. x/talks just hasn't been deployed in a while.

**Comment by dmitshur** [comment]
> merge App Engine and "local" logic into one binary without build tags

🎉 👍
