### ISSUE TITLE
Please publish 1.11.1 snap

### ISSUE THREAD

**Issue by zfil** [golang/go#28093]
go snap 1.11.1 is still not available.

@mwhudson could you please publish it ?

Thanks

**Comment by ALTree** [comment]
Hi, Snaps (or any other kind of OS package) are not managed and published by the Go Project. Please contact Michael at the email address on https://snapcraft.io/go. 

Closing here, since this is not a Go bug.

**Comment by mwhudson** [comment]
FWIW, it's published now.
