### ISSUE TITLE
x/tools/cmd/godoc: search not work locally

### ISSUE THREAD

**Issue by adals** [golang/go#28090]
What version of Go are you using (go version)?

go version go1.11.1 darwin/amd64

Does this issue reproduce with the latest release?

yes

What operating system and processor architecture are you using (go env)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adelalharbi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/adelalharbi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q2/fh5rkr2n0mxdzfvb3h0zw4j40000gn/T/go-build796831401=/tmp/go-build -gno-record-gcc-switches -fno-common"

What did you do?

    open terminal
    ran godoc -http=:6060
    looking at http://localhost:6060/search?q=html

What did you expect to see?
information related to html

What did you see instead?
NOTHING

**Comment by dmitshur** [comment]
From `godoc -help` output:

```
  -index
    	enable search index
```

By default, the search index isn't enabled. You'll need to explicitly enable it if you want it to be available:

```
godoc -index -http=:6060
```

Then `http://localhost:6060/search?q=html` should display some results after indexing is complete (which takes some time, especially if you have many packages locally).

**Comment by adals** [comment]
it works right now thanks
