### ISSUE TITLE
x/dl/internal/version: add $GOROOT/bin to $PATH when running go run/generate

### ISSUE THREAD

**Issue by jimmyfrasche** [golang/go#28103]
Tools run by go run/generate sometimes need to execute the go command, for example when using `go/packages`.

Adding $GOROOT/bin to $PATH ensures that the appropriate version of the go/gofmt commands are run when using a go command wrapper generated by x/build/version.

edit: and `test`. Anything that runs go code could exec the go tool.

See #28043 for background and discussion, specifically https://github.com/golang/go/issues/28043#issuecomment-427969204.

cc @bcmills

**Comment by SamWhited** [comment]
New CL isn't being linked for some reason, see: https://golang.org/cl/143545
