### ISSUE TITLE
gccgo: erroneously accepts duplicate constant keys in map literal

### ISSUE THREAD

**Issue by mdempsky** [golang/go#28104]
Under [Composite literals](https://golang.org/ref/spec#Composite_literals), the Go spec says "It is an error to specify multiple elements with the same field name or constant key value."

However, gccgo erroneously accepts this code:

    package p
    
    var _ = map[int]int{0: 0, 0: 0}

cmd/compile and go/types correctly emit an error.

/cc @ianlancetaylor

**Comment by dotaheor** [comment]
It looks this has been fixed for non-bool keys in the latest gccgo versions.

Duplicate bool keys are still allowed: https://github.com/golang/go/issues/35945
