### ISSUE TITLE
Go language should become an ANSI and ISO standard.

### ISSUE THREAD

**Issue by beoran** [golang/go#28117]
In certain environments, such as for government contracting in certain countries, or for certain large corporations, or for developing safety critical applications using certain international standards, only programming languages that are officially standardized may be used. While Go would be an excellent language for such government or safety critical applications, it's acceptance is hampered due to the lack of an official standard.

While this is in essence a formality, which would entail submitting the current Go language specification with the ANSI, and then have it propagate to the ISO, I do appreciate that will take quite some time and effort. But to further the acceptance of Go language, I would propose that Google invests the necessary resources to make this happen, with support from the community to edit the standard document if needed. 

The standard should probably be based on Go 1, since Go 2 is still largely undecided and probably 5 years in the future.

**Comment by agnivade** [comment]
Issues like these are not usually tracked in the issue tracker. It is just for bugs and proposals to the language.

But I am not sure where should they be tracked. @bradfitz  ?

**Comment by beoran** [comment]
Yes, you are right, but I didn't quite see where too raise this suggestion. Maybe on the mailing list in stead?

**Comment by bcmills** [comment]
> or for developing safety critical applications using certain international standards

Note that according to the Go license:
https://github.com/golang/go/blob/f776d51bf7fe90926f8b929aee65d802a9091d5e/LICENSE#L17-L27

I would not advise its use in safety critical applications.

**Comment by beoran** [comment]
It is rare that the compiler builder gives any warrantees, although there are some safety certified C compilers. But for such certified Go compilers to be developed, we need an official standard first.

Even if the compiler is not certified, you can still use it if you validate it yourself. This implementation of go has extensive unit tests which simplifies such validation a lot.

I know of some safety critical software that is implemented in C and compiled with GCC. As a language, Go is far safer than that, and that is why we need a standard, to be able to get away from C for safety applications.

**Comment by ianlancetaylor** [comment]
This should be discussed on golang-nuts, not the issue tracker.  Thanks.

**Comment by beoran** [comment]
Ok, I will. Sorry for the noise.
