### ISSUE TITLE
cmd/go: allow go mod edit a go.mod from stdin

### ISSUE THREAD

**Issue by keegancsmith** [golang/go#28118]
### What version of Go are you using (`go version`)?

go version go1.11.1 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/Users/keegan/go/bin"
GOCACHE="/Users/keegan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/keegan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l7/htgnc72s5bz3lfw9882n_5yw0000gn/T/go-build766629131=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

No way to pass in a go.mod file via stdin to `go mod edit -print`. We want to run a git filter which removes a replace, to prevent devs accidentally committing it. We tried to work around it via bash tricks of redirecting stdin to a file. What ended up working was quite verbose

```
# bash
$ GOMOD=<(/dev/stdin) go mod edit -print -dropreplace=github.com/my/example
go: cannot find main module; see 'go help modules'
# also tried GOMOD=-
# this works, but isn't ideal
cp /dev/stdin $TMPDIR/go.mod; cd $TMPDIR; GO111MODULE=on go mod edit -print -dropreplace=github.com/my/example
```

### What did you expect to see?

An option for doing edits on a file via stdin, given you can output via stdout.

**Comment by bcmills** [comment]
I think I'm missing somethnig. `go mod edit -dropreplace` should be a no-op if there is no such replacement. Why do you need to process it from stdin for that?

**Comment by keegancsmith** [comment]
> We want to run a git filter which removes a replace, to prevent devs accidentally committing it.

See filter section on https://git-scm.com/docs/gitattributes. You specify a command which takes the file via stdin and output the contents to actually commit over stdout. We often use replace to a relative directory since we have two closely coupled repos. We are wanting to try out a git filter to avoid accidental commits of the replace one uses in local development.

Additionally, I expected `go mod edit` would not need to read anything but the `go.mod` file, so wouldn't need the context of the rest of the modules files, etc. An example where this would be needed outside of our specific use case is editor integration and running `go mod edit -fmt` on an unsaved file.

**Comment by bcmills** [comment]
I'm curious: why a `filter` attribute rather than a `pre-commit` hook?

**Comment by keegancsmith** [comment]
heh, good question. I'm not actually sure, I didn't ask that was just trying to help a co-worker acheive that. cc @felixfbecker

**Comment by myitcv** [comment]
@keegancsmith @felixbecker - any update here?

**Comment by keegancsmith** [comment]
We no longer are needing to do this. This still seems like a useful feature to have w.r.t. other tooling, but not important. So I'm happy to just close out this issue. Re-open if you think its useful to track.
