### ISSUE TITLE
ECDSA implementation is terrible

### ISSUE THREAD

**Issue by sorenvonsarvort** [golang/go#28139]
### What version of Go are you using (`go version`)?

```go version go1.11.1 linux/amd64```

### What did you do?

Tried to use a `secp256k1` as a curve in `ecdsa.GenerateKey()`.

### What did you expect to see?

Configurable `a` parameter.

### What did you see instead?

`elliptic.CurveParams` has a hardcoded `a` parameter. Very hardcoded.

```go

threeX := new(big.Int).Lsh(x, 1)
threeX.Add(threeX, x)

```

```go

	u1 := new(big.Int).Mul(x1, z2z2)
	u1.Mod(u1, curve.P)
	u2 := new(big.Int).Mul(x2, z1z1)
	u2.Mod(u2, curve.P)
	h := new(big.Int).Sub(u2, u1)
	xEqual := h.Sign() == 0
	if h.Sign() == -1 {
		h.Add(h, curve.P)
	}
	i := new(big.Int).Lsh(h, 1)
	i.Mul(i, i)
	j := new(big.Int).Mul(h, i)

	s1 := new(big.Int).Mul(y1, z2)
	s1.Mul(s1, z2z2)
	s1.Mod(s1, curve.P)
	s2 := new(big.Int).Mul(y2, z1)
	s2.Mul(s2, z1z1)
	s2.Mod(s2, curve.P)
	r := new(big.Int).Sub(s2, s1)
	if r.Sign() == -1 {
		r.Add(r, curve.P)
	}
	yEqual := r.Sign() == 0
	if xEqual && yEqual {
		return curve.doubleJacobian(x1, y1, z1)
	}
	r.Lsh(r, 1)
	v := new(big.Int).Mul(u1, i)

	x3.Set(r)
	x3.Mul(x3, x3)
	x3.Sub(x3, j)
	x3.Sub(x3, v)
	x3.Sub(x3, v)
	x3.Mod(x3, curve.P)

	y3.Set(r)
	v.Sub(v, x3)
	y3.Mul(y3, v)
	s1.Mul(s1, j)
	s1.Lsh(s1, 1)
	y3.Sub(y3, s1)
	y3.Mod(y3, curve.P)
```

Are You kidding? Can You even figure out how it should look with `a` other than `-3`? How can I fix it? I believe it is better to reimplement this useless piece of shit.

**Comment by bradfitz** [comment]
I'm going to close this bug. I don't expect any good answers on this one at this point now that the tone has been set.

I invite you to review https://golang.org/conduct and then try again with a normal, polite bug report.
