### ISSUE TITLE
doc: add wasm, aix to golang.org/doc/install/source#environment

### ISSUE THREAD

**Issue by kevinburke** [golang/go#28142]
There are a list of valid GOOS and GOARCH settings in golang.org/doc/install/source, but this list does not include wasm (or presumably aix, which is in the process of being added.)

It would be good to add these!

**Comment by ainar-g** [comment]
(I don't think that this deserves a separate issue, so I'll leave it here.)

Plan9 on ARM seems to be a perfectly valid target (at the very least, it is listed as OK on https://build.golang.org/), but it isn't mentioned there either.
