### ISSUE TITLE
x/tools/godoc, x/tools/cmd/godoc, gddo: module support

### ISSUE THREAD

**Issue by andybons** [golang/go#28151]
This is a top-level bug to track module integration with godoc.org and golang.org documentation rendering code.

**Comment by agnivade** [comment]
Umm .. I had already filed https://github.com/golang/go/issues/26827, which is exactly for this purpose. Probably that got missed.

I would request that we add gddo and use that issue to track since it already has some context and ideas.

**Comment by andybons** [comment]
Ah yes it did. Thanks @agnivade.

**Comment by andybons** [comment]
Duplicate of #26827
