### ISSUE TITLE
x/sys/unix: missing SOL_TIMESTAMPING_RX_HARDWARE constant(s)?

### ISSUE THREAD

**Issue by xuesongbj** [golang/go#28173]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go version 1.10.4  linux/amd64

### Does this issue reproduce with the latest release?
No(1.10.4)

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/David/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/David/data/go/go.deps:/Users/David/data/go/go.test"
GORACE=""
GOROOT="/Users/David/data/go1.10"
GOTMPDIR=""
GOTOOLDIR="/Users/David/data/go1.10/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
```

### What did you do?
The system call does not support the SO_TIMESTAMPING setting. Unable to get the socket to return the raw unmodified packet timestamp generated by the hardware.

No SOF_TIMESTAMPING_RX_HARDWARE constant found.
```
syscall.SetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SOF_TIMESTAMPING_RX_HARDWARE, 1)
```

### What did you expect to see?
Able to support this feature.

### What did you see instead?
```
undefined: syscall.SOF_TIMESTAMPING_RX_HARDWARE
```

**Comment by agnivade** [comment]
I can see `SO_TIMESTAMPING                  = 0x25` in https://golang.org/pkg/syscall/#pkg-constants.

Is this not what you want ?

**Comment by bradfitz** [comment]
The syscall package is frozen.

If we're missing a constant, it can be added to `golang.org/x/sys/unix`.

/cc @tklauser
