### ISSUE TITLE
cmd/compile: racecompile builder failures on multiple packages

### ISSUE THREAD

**Issue by ALTree** [golang/go#28170]
The racecompile builder has been very flaky for the past two days:

https://build.golang.org/#

failures are reported on many different packages:

https://build.golang.org/log/706e3c506500ddd44b3c7f2a303aff6dc2d415f3
https://build.golang.org/log/68197029863f12197c4d34d1f7eb5a9eec553176
https://build.golang.org/log/eb23684cf4d9315e388a78d84f972daaa1a8b9ee
https://build.golang.org/log/e71a2d04359d9b57b7aa6725ce03edbbcaad9f03

and others. The first failure happened right after https://go-review.googlesource.com/c/go/+/140698 was committed.

cc @randall77

**Comment by randall77** [comment]
Yeah, that could be my CL. I'll look in a bit.
Might also be the cause of #28159, now that I think about it.

**Comment by josharian** [comment]
Glancing at that CL on my phone, the only possible suspect I see is init.Append calls; might need addinit instead?
