### ISSUE TITLE
syscall/js: zero Value is interpreted as NaN instead of Undefined

### ISSUE THREAD

**Issue by dennwc** [golang/go#28174]
### What version of Go are you using (`go version`)?
```
go version go1.11.1 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes (same on `tip`)

### What operating system and processor architecture are you using (`go env`)?
```
GOOS=js
GOARCH=wasm
```

### What did you do?
```golang
var v js.Value
fmt.Println(v == js.Undefined())
```

### What did you expect to see?
```
true
```

### What did you see instead?
```
false
```

### Description

Currently, `ref` type codes of JS values in `wasm` are arranged in a way that makes a zero value a `NaN` number instead of `undefined`.

This breaks established Go semantics where a zero pointer value of a type is assumed to have a `nil` value (JS default value is `undefined`).

To illustrate the difference, consider the case:
```golang
var a *Obj // a == nil

var m map[string]*Obj
b := m["non existent"] // b == nil

a == b // true
```

However, this code does not work in the current implementation:

```golang
var a js.Value // NaN !

m := js.Global()
b := m.Get("non existent") // undefined

a == b // false !
```

### Proposed solution

Remap JS value type enum to list `undefined` as a first type code (`= 0`) and move `NaN` to a different type code.

CC @neelance

**Comment by neelance** [comment]
Yes, the zero value is intentionally unspecified atm, since I did not decide yet if this is worth a special case. It probably is.

**Comment by cherrymui** [comment]
See #27592. Closing this as a dup.
