### ISSUE TITLE
gccgo: crash on implicit duplicate array/slice index

### ISSUE THREAD

**Issue by go101** [golang/go#28186]
### What version of Go are you using (`go version`)?

```
$ gccgo --version
gccgo (Debian 8.2.0-7) 8.2.0
```

### Does this issue reproduce with the latest release?

maybe

### What did you do?

```golang
package main

var f = [...]bool{3: false, 2: true, true} // the implicit index for the third element is 3

func main() {
}
```

### What did you expect to see?

report error without crashing

### What did you see instead?

crash

```
$ go run -compiler=gccgo aa.go
# command-line-arguments
go1: internal compiler error: in output_constructor_regular_field, at varasm.c:5142
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
```

**Comment by mdcnz** [comment]
Playground reports the error: prog.go:3:38: duplicate index in array literal: 3
https://play.golang.org/p/_fVK5DNyb2G

**Comment by benshi001** [comment]
gccgo does crash with "gccgo aa.go", but doesn't with "gccgo aa.go -O2"
