### ISSUE TITLE
os/user: TestGroupIds fails on windows-arm

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#28183]
Our windows-arm builder fails https://build.golang.org/log/024228bdaccb0c0f92bc505bdfc1f2287b9ef818 in

```
--- FAIL: TestGroupIds (0.02s)
    user_test.go:141: &{Uid:S-1-5-18 Gid:S-1-5-18 Username:NT AUTHORITY\SYSTEM Name:SYSTEM HomeDir:C:\Data\Users\System}.GroupIds(): The user name could not be found.
FAIL
FAIL	os/user	0.614s
```

I looked at os/user.TestGroupIds windows implementation.

It appears that os/user.Current() returns `NT AUTHORITY\SYSTEM`. @jordanrh1 why? I expect it return some real user. Are you running builder as a service or something?

Also GroupIds() function fails with `The user name could not be found.` error. This is too general error to guess what happened. @jordanrh1 do you mind debugging to see what happened there?

Thank you.

Alex

**Comment by jordanrh1** [comment]
Hi Alex,

The builder currently runs as System account. I'll look into running it under a normal user account.

I'll debug the GroupIds function. Could be related to running as System account.

Jordan

**Comment by jordanrh1** [comment]
I restarted the builder under DefaultAccount (a standard user account), and the os/user tests are now passing :)

```
ok  	os/user	0.655s
```

**Comment by alexbrainman** [comment]
> I restarted the builder under DefaultAccount (a standard user account), and the os/user tests are now passing :)
> 
> ```
> ok  	os/user	0.655s
> ```

Indeed they are. Thank you very much. Closing this now.

Alex
