### ISSUE TITLE
net/http: DefaultClient.Get is painfully slow

### ISSUE THREAD

**Issue by opennota** [golang/go#28188]
### What version of Go are you using (`go version`)?

go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/opennota/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/opennota/gocode"
GOPROXY=""
GORACE=""
GOROOT="/home/opennota/go"
GOTMPDIR=""
GOTOOLDIR="/home/opennota/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build055651916=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

``` Go
package main

import (
	"fmt"
	"net/http"
	"time"
)

func main() {
	const url = "https://gufo.me/dict/epithets/%D0%B0%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F"
	start := time.Now()
	_, err := http.DefaultClient.Get(url)
	if err != nil {
		panic(err)
	}
	fmt.Println(time.Since(start))
}
```

```
$ go build -o main main.go
$ ./main
10.813319159s
```

### What did you expect to see?

The request is completed in 1 second at most.

### What did you see instead?

The request takes almost 11 seconds: `10.813319159s`

wget does the same request in under 1 second.

**Comment by agnivade** [comment]
This may be due to the DNS resolution issues that we have been having. Probably a dup of #21906

Can you check with 1.11.1 ? [This](https://github.com/golang/go/issues/27525) got backported.

Also, please run with httptrace (https://github.com/golang/go/issues/21906#issuecomment-332116942) so that we know which part of the request is slow.

**Comment by opennota** [comment]
That was it, thanks. With Go 1.11.11 it's 600-700ms.
