### ISSUE TITLE
os: TestUserHomeDir fails on windows-arm

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#28182]
Our windows-arm builder fails https://build.golang.org/log/024228bdaccb0c0f92bc505bdfc1f2287b9ef818 in

```
--- FAIL: TestUserHomeDir (0.00s)
    os_test.go:2340: UserHomeDir returned an empty string
FAIL
FAIL	os	16.058s
```

I looked at os.UserHomeDir windows implementation, and it just returns
```go
return Getenv("HOMEDRIVE") + Getenv("HOMEPATH")
```

So, obviously, windows-arm builder process does not have %HOMEDRIVE% and %HOMEPATH% set. Is that because the process was configured that way, or windows-arm does not have these variables set? If variables are not set on all windows-arm computers, how do we determine what HOME directory is?

Questions for @jordanrh1

Thank you.

Alex

**Comment by jordanrh1** [comment]
Hi Alex, I think it would be better to use `%userprofile%`. `USERPROFILE` is the equivalent of $HOME on linux.
