### ISSUE TITLE
profile: How to profile a go program base on wall time instead of cpu time?

### ISSUE THREAD

**Issue by ppggff** [golang/go#28203]
As I know, go profile use SIGPROF to sample call stacks N times per second in cpu time.
It will ignore idle time, waiting time since these time doesn't consume cpu.

To profile a go program with mix load, I want to profile it base on wall time:  samples
call stacks N times per second in wall time. And it will show the result in same UI of cpu time.

For example, poor man's profiler (https://poormansprofiler.org/) sampling program by running gdb per second(or minute). 

How to do it with current go prof? or some others tools?

**Comment by ianlancetaylor** [comment]
I don't think there is a way.

Note that we don't use the issue tracker for questions.  See https://golang.org/wiki/Questions .  I'm going to close this issue report because there is no clear way to fix it.

**Comment by ppggff** [comment]
Thanks. I create a topic at Go Forum: https://forum.golangbridge.org/t/profile-how-to-profile-a-go-program-base-on-wall-time-instead-of-cpu-time/10990

And I am trying to make it work by:

* Set cpu sample rate to 1Hz
* Start at time ticker (100Hz) to send SIGPROF to self
