### ISSUE TITLE
encoding/base64: make decoding more lenient (?)

### ISSUE THREAD

**Issue by koggle** [golang/go#28205]
Please answer these questions before submitting your issue. Thanks!

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
win

### What did you do?

package main
import (
	"fmt"
	"encoding/base64"
)
func main() {
	fmt.Println(base64.RawStdEncoding.DecodeString("abc "))  //decoding error
}
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
//print [105,183] nil

### What did you see instead?
//print [] illegal base64 data at input byte 3

**Comment by zegl** [comment]
@koggle Remove the trailing space in the `DecodeString` call, and it will work as expected. Whitespace is not a valid base64 character.

**Comment by womgit** [comment]
no

**Comment by mvdan** [comment]
The template is still not complete. Please re-read what @ianlancetaylor and myself requested in https://github.com/golang/go/issues/28185.

In particular, fill in `go version` and `go env`, and clearly explain *why* you think this is broken. As far as I can see, this is working as intended, just like @zegl said.

**Comment by koggle** [comment]
This has nothing to do with go version and go env, thanks
