### ISSUE TITLE
cmd/go: No `// indirect` dependency for imports in example files

### ISSUE THREAD

**Issue by flibustenet** [golang/go#28216]
### What version of Go are you using (`go version`)?

go 1.11.1

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

I import `github.com/go-ole/go-ole` in my app
This lib currently has no `go.mod` file and `import github.com/gonuts/commander` in an example file https://github.com/go-ole/go-ole/blob/master/example/itunes/itunes.go

I run `go mod tidy` in my app
```Go
package main

import (
	"fmt"

	ole "github.com/go-ole/go-ole"
)

func main() {
	fmt.Println(ole.VT_EMPTY)

}

```

### What did you expect to see?
```
module t

require github.com/go-ole/go-ole v1.2.1
require github.com/gonuts/commander v0.1.0 // indirect
```

### What did you see instead?

```
module t

require github.com/go-ole/go-ole v1.2.1
```

No line with `require github.com/gonuts/commander v0.1.0 // indirect`

**Comment by bcmills** [comment]
The _package_ `github.com/go-ole/go-ole` doesn't import `go-ole/example/itunes`, so `github.com/gonuts/commander` isn't in the package-import graph of your module. That's why `go mod tidy` doesn't try to resolve it, and why it doesn't add a requirement for it.
