### ISSUE TITLE
website: Update "How to Write Go Code" with go modules

### ISSUE THREAD

**Issue by mdwhatcott** [golang/go#28215]
Now that go modules are a thing, is it time to update ["How to Write Go Code"](https://golang.org/doc/code.html) with information about modules?

**Comment by elliotforbes** [comment]
I wouldn't mind giving this one a shot?

**Comment by ianlancetaylor** [comment]
CC @robpike

**Comment by thepudds** [comment]
@andybons @bcmills This might be somewhat stuck with some type of CLA-related issue? See for example https://github.com/golang/go/pull/28218#issuecomment-430628733.  Is there someone you could suggest who could help unstick the CLA issue? Or is there some other approach you might recommend like deleting the PR and trying again in the hopes of avoiding whatever tripped up the CLA bot?

**Comment by andybons** [comment]
I’ve responded on the Pull Request.

**Comment by elliotforbes** [comment]
Ok, I can update the code to remove the GOPATH explanations and focus purely on using modules. This could then be tagged to go live with the 1.12 release in February? 

Does this sound like a plan?

**Comment by andybons** [comment]
Generally, documentation fixes are permitted during the freeze so it’s feasible this will get in by the time 1.12 stable is released. No need to worry about that.

Let’s wait for @bcmills to respond. Many people are out this week for the holidays so we’ll need to be a bit patient. Thanks.

**Comment by andybons** [comment]
After discussion with the team, we don't believe we should be removing references to `GOPATH` as modules are not on by default (and even then, `GOPATH` will be around for some time).

**Comment by elliotforbes** [comment]
Cool, should I leave as-is then? Or are there more actions for me to take at this point?

**Comment by andybons** [comment]
The current doc changes replace `GOPATH` with modules. Ideally we'd want them both to be there.

**Comment by elliotforbes** [comment]
I've taken an initial stab at explaining how both work in the same document, I'll be going over it more once I have a bit of free time this weekend, but it's up if you want to critique the approach used.

**Comment by bcmills** [comment]
There is realistically no way this will land for 1.12, but we should make sure it is updated for 1.13.

I think that discussion of `gohack` and broader resources are probably better kept elsewhere: “How to Write Go Code” is a quick-start document, currently standing at only ~6 pages of text, and I'd like to keep it that way. (A link to the Modules wiki page alongside the other reference links at the end is probably a good idea, though.)

I would rather see `GOPATH` and modules as separate sections (or separate views) than interspersed: someone getting started in module mode mostly shouldn't care about `GOPATH`, and we don't want to make a lot of work to disentangle them again when `GOPATH` mode goes away.

**Comment by amnonbc** [comment]
This document should target beginners.
So all vestiges to the legacy GOPATH, keeping all your code in a single workspace etc. should be removed.

**Comment by jadekler** [comment]
FYI this is underway at https://go-review.googlesource.com/c/website/+/199417.
