### ISSUE TITLE
database/sql: remove commented debug prints

### ISSUE THREAD

**Issue by minaevmike** [golang/go#28234]
there are some commented debug prints in database/sql package(like https://github.com/golang/go/blob/master/src/database/sql/sql.go#L600 and https://github.com/golang/go/blob/master/src/database/sql/sql.go#L570) , i think they can be deleted.

**Comment by FiloSottile** [comment]
Permalinks: 
https://github.com/golang/go/blob/e861c3e003b37622603ff690aba5e62c0ddb31c2/src/database/sql/sql.go#L600
https://github.com/golang/go/blob/e861c3e003b37622603ff690aba5e62c0ddb31c2/src/database/sql/sql.go#L570

**Comment by abhijitherekar** [comment]
@FiloSottile  Hi, Can I pick this?

**Comment by Gnouc** [comment]
@abhijitherekar just send a CL
