### ISSUE TITLE
cmd/go: merge coverage profiles from subprocesses

### ISSUE THREAD

**Issue by bcmills** [golang/go#28235]
According to this snippet, `initCoverProfile` clears the coverage profile on every run:
https://github.com/golang/go/blob/4b36e129f865f802eb87f7aa2b25e3297c5d8cfd/src/cmd/go/internal/test/cover.go#L23-L24

That seems counterproductive when we're collecting coverage from a test that runs a binary multiple times (such as the tests for `cmd/go` itself), or from a test that invokes itself as a subprocess.

Instead, I suspect that we should use OS-level file locking so that we can merge coverage from multiple invocations.

If we do that, I'm not entirely sure when we should remove the previous profile, though.

(CC: @ianlancetaylor @rsc)

**Comment by bcmills** [comment]
CC @julieqiu

**Comment by fgm** [comment]
This is also annoying when testing exiting code using a subprocess, as in this technique by @adg https://talks.golang.org/2014/testing.slide#23

**Comment by bcmills** [comment]
@thanm, is this done automatically with the new coverage support enabled?

**Comment by thanm** [comment]
At least in the cmd/go case, yes, this is already taken care of by the new implementation, yes.
