### ISSUE TITLE
net/http: SameSite description is grammatically incorrect

### ISSUE THREAD

**Issue by taylorza** [golang/go#28244]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.11.x

### Does this issue reproduce with the latest release?
The issue is with the documentation for net/http/SameSite documentation which was added in go 1.11

### What did you expect to see?
I believe the following captures the intended description, without restructuring it too significantly

**SameSite allows a server to define a cookie attribute making it impossible for the browser to send this cookie along with cross-site requests. The main goal is to mitigate the risk of cross-origin information leakage and provide some protection against cross-site request forgery attacks.**

### What did you see instead?
SameSite allows a server define a cookie attribute making it impossible to the browser send this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage, and provides some protection against cross-site request forgery attacks.

**Comment by bradfitz** [comment]
Want to send a change?

**Comment by taylorza** [comment]
@bradfitz, I will send the change in.

**Comment by mbj36** [comment]
@bradfitz I am new contributor to golang and i am slightly confused about the master branch....I have built my docs using `godoc -http:=6060` and my `master` branch doesn't reflect what is present here - https://golang.org/pkg/net/http

Am i missing something, can you please point me to the right direction ?

**Comment by bradfitz** [comment]
@mbj36, I don't know what you've done or what your environment is so it's hard to help. I suspect the godoc you're running is using the wrong GOROOT. You can explicitly set the GOROOT environment variable to point to your master checkout path.

Also perhaps of help: https://golang.org/doc/contribute.html and the #gocontributing channel on the Gophers Slack.

**Comment by mbj36** [comment]
@bradfitz Thanks for the reply. 
This issue has been already fix here - https://tip.golang.org/pkg/net/http/#SameSite

**Comment by agnivade** [comment]
If you want, you can still fix it by removing the `s` from `provides`.

The main goal is to mitigate the risk of cross-origin information leakage, and provide~s~ some protection against cross-site request forgery attacks.

**Comment by mbj36** [comment]
@agnivade Fixed
