### ISSUE TITLE
interface{} == nil comparison returns false instead of true

### ISSUE THREAD

**Issue by ston1th** [golang/go#28241]
### What version of Go are you using (`go version`)?
go version go1.11.1 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

https://play.golang.org/p/bwmjw0Rt_wk

### What did you expect to see?

`n2 == nil` should be true (`reflect.ValueOf(n2).IsNil()` reports true correctly)

### What did you see instead?

`n2 == nil` is false

**Comment by deanveloper** [comment]
Intended behavior. An interface consistshttps://golang.org/doc/faq#nil_error

**Comment by ston1th** [comment]
Ahh, thanks for clearing things up.
