### ISSUE TITLE
why use fmt.Println in Read function produce twice output

### ISSUE THREAD

**Issue by CodeisCold** [golang/go#28263]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/vagrant/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build800851283=/tmp/go-build"

### What did you do?

code:
https://play.golang.org/p/BJeMXgI2Kw1

### What did you expect to see?
test
azAZLbh penpxrq gur pbqr!

### What did you see instead?
test
azAZLbh penpxrq gur pbqr!test

**Comment by CodeisCold** [comment]
It also happen when change stdout to stderr or bytes.Buffer

**Comment by ianlancetaylor** [comment]
`io.Copy` calls `Read` once to get some data, and copies that to `os.Stdout`.  Then it calls `Read` again to see if there is any more data.  The second call returns an error of `io.EOF`, so `io.Copy` stops.

This is working as expected.

**Comment by CodeisCold** [comment]
Thanks
