### ISSUE TITLE
syscall/js: Add Truthy() and Falsy() to Value methods

### ISSUE THREAD

**Issue by theclapp** [golang/go#28264]
### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
js/wasm

---

JS has the concept of ["truthy" and "falsy"](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).  It'd be nice if these were part of syscall/js, either as part and parcel of Value.Bool(), or failing that something along the lines of

```go
func (o Value) Falsy() bool {
	return !o.Truthy()
}

func (o Value) Truthy() bool {
	switch o.Type() {
	case TypeUndefined, TypeNull:
		return false
	case TypeBoolean:
		return o.Bool()
	case TypeNumber:
		if math.IsNaN(o.Float()) {
			return false
		}
		return o.Float() != 0
	case TypeString:
		return o.String() != ""
	case TypeSymbol, TypeObject, TypeFunction:
		return true
	}
	return true
}
```

**Comment by neelance** [comment]
I'm not yet sure if it would be good to include it in `syscall/js`. For which APIs would you need the concept of "truthy"? Could you provide examples please?

**Comment by theclapp** [comment]
I've been updating my Vue.js wrapper to use your wasm-sync-callbacks tree.  I was trying to replicate an example from the Vue Guide ([here](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax), the bit that starts with "This will render the same result. We can also bind to a computed property that returns an object.")  The JS in question is

```javascript
function () {
    return {
      active: this.isActive && !this.error,
      'text-danger': this.error && this.error.type === 'fatal'
    }
}
```

So for `this.isActive` and `this.error` I wanted "truthy", for `!this.error` I wanted "falsy".  I implemented that part of that example like [this](https://github.com/HuckRidgeSW/hvue/blob/work-with-sync-callbacks/examples/05-class-and-style-bindings/main.go#L86-L90):

```go
return hvue.Map2Obj(hvue.M{
	"active": hvue.Truthy(data3.Get("isActive")) &&
		hvue.Falsy(data3.Get("error")),
	"text-danger": hvue.Truthy(data3.Get("error")) &&
		data3.Get("error").Get("type").String() == "fatal",
})
```

where `hvue.Map2Obj(hvue.M{...})` is similar to how GopherJS automagically transforms a GopherJS `js.M{}` into a JS object, and `hvue.Truthy()` and `Falsy()` are similar to the example code I posted at the top of this issue, except obviously not methods on `js.Value`.  (See [here](https://github.com/HuckRidgeSW/hvue/blob/555fc07bd117358d4b42cc25248429facf07fadf/util.go#L55-L79).)

One could certainly argue that the _absence_ of such a vague concept as "truthiness" in Go is (one of the reasons) _why we use Go_ and not JavaScript, and I could certainly understand that, and agree that in most cases you shouldn't do it.  But pragmatically I think there are clear use-cases for it.

So to sum up, when transliterating JavaScript to Go, since JavaScript uses truthiness a lot, I think it'd be handy and pragmatic for JS-transliterated-to-Go to be able to do the same, "out of the box".

I could see that you might not want `Value.Truthy()/Falsy()` in `syscall/js` (although obviously _I_ think having them as methods on `Value` would be the most useful).  There are other utility-functions that might also be handy, that shouldn't be in `syscall/js`.  So perhaps a `syscall/js/jsutil` or top-level `jsutil` package would be appropriate?  We discussed this a bit in the Gophers #webassembly channel (starting [here](https://gophers.slack.com/archives/C4GU6CHSQ/p1539616835000100)), and one library with some nice utilities was pointed out: https://github.com/dennwc/dom/tree/master/js ([permalink](https://github.com/dennwc/dom/tree/236586f4e30ab4a5f7135b0ef528ae5332feaeba/js)).

**Comment by myitcv** [comment]
> I'm not yet sure if it would be good to include it in syscall/js

I'd tend to agree; the implementation of "truthy" or "falsey" feels like something that should be left to the JavaScript VM; we would be reimplementing that logic which feels wrong.

**Comment by theclapp** [comment]
> we would be reimplementing that logic

Not necessarily.  It could be

```javascript
// Global JavaScript function
function isTruthy(o) {
  if (o) { return true } else { return false }
  // or even: return !!o
}
```

```go
func (o Value) Truthy() bool {
   return Global().Call("isTruthy", o).Bool()
}
```

---

That said, the concept of "truthy", while admittedly a bit general, is actually pretty well-defined: "All values are truthy unless they are defined as falsy (i.e., except for false, 0, "", null, undefined, and NaN)".  (In fact in my initial implementation of Truthy() & Falsy() I had Falsy() checking for false/0/etc, and Truthy was !Falsy, but then I inverted them.)  My point being, I suspect that a pure-Go version would be faster and just as accurate as trampolining to JavaScript.

**Comment by DonMcNamara** [comment]
>  I suspect that a pure-Go version would be faster and just as accurate as trampolining to JavaScript.

It might be useful to have some hard numbers here. It seems like [a lot of work](https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/) is being done to speed up these types of calls.

**Comment by theclapp** [comment]
> It might be useful to have some hard numbers here

Happy to give it a shot, if @neelance (et al) think this is a reasonable feature in the first place.  If they don't want to do it, it doesn't matter how fast it is.  :)

**Comment by bradfitz** [comment]
If the JS-inclined people generally agree this is a good idea, I don't object to adding one method. Two seems overkill, though. (e.g. we have [utf8.ValidString](https://golang.org/pkg/unicode/utf8/#ValidString) but we don't also have utf8.InvalidString for the opposite)

**Comment by neelance** [comment]
I am quite sure that the pure-Go version will be faster.

In JS, using truthiness is common, but I think this is mostly because it has the simplest syntax. Not using truthiness in JS just looks ugly quite often.

I've seen truthiness hiding bugs. Having a strong expectation about a type of a value is usually safer. However, there are use cases with legacy code that need truthiness.

I don't object to adding just `Truthy` either. I just hope it will get used sparingly.

**Comment by neelance** [comment]
@theclapp Mind creating a CL? :)

**Comment by theclapp** [comment]
@neelance Will do.  It may be a few days.  This'll be my first Go code contribution, so there's that first-timer learning curve to climb.
