### ISSUE TITLE
go/types: export a function for representability

### ISSUE THREAD

**Issue by jba** [golang/go#28267]
Export something like the `representableConst` function for testing whether a `constant.Value` is representable by a type.

My use case: I'm writing an API compatibility checker, and I want to report whether a changed constant value can still be used with all the types that it was previously.

**Comment by mvdan** [comment]
@jba I presume you meant this for `go/types`?

/cc @griesemer

**Comment by jba** [comment]
Yes, sorry, `go/types`. I edited the issue title.

I don't see how those functions could help, since they both take only types. 
`const c1 = 1` and `const c2 = -1` have the same type, so asking if that type is assignable to `uint8` must give the same answer for both. But `var u uint8 = c1` compiles while `var u uint8 = c2` doesn't.

I haven't looked at the std lib checker yet. I will.

**Comment by griesemer** [comment]
Ah, yes, I forgot that the exported AssignableTo doesn't take the value of a constant into account (the internal version operand.assignableTo does). Fair enough, seems like a reasonable request. Is this urgent (for 1.12)?

**Comment by jba** [comment]
Not urgent.

**Comment by jba** [comment]
I no longer need this. Closing the issue, since there are no other requests.
