### ISSUE TITLE
time: location data always falls back to UTC in js/wasm

### ISSUE THREAD

**Issue by eternal-flame-AD** [golang/go#28265]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ef/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ef/code/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build929309457=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Build and run the following snippet both in `linux/amd64`(local architecture) and `wasm/js`
```golang
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(time.Now().Location())
}
```

### What did you expect to see?
The results should be consisitent with the following javascript [code](https://stackoverflow.com/questions/1091372/getting-the-clients-timezone-in-javascript), which should return the OS timezone info:

```javascript
console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)
```

### What did you see instead?

On native architecture(linux/amd64):
```bash
Asia/Shanghai
```
On browser javascript:
```bash
Asia/Shanghai
```
On wasm:
```bash
UTC
```

**Comment by agnivade** [comment]
zoneinfo_unix.go seems to contain js,wasm. Hence in a browser environment, it falls back to UTC. I think it should be possible to have a zoneinfo_js.go and call into wasm_exec.js to get the browser/node timezone.

**Comment by eternal-flame-AD** [comment]
Yep, I think it require at least a bit of refactoring on the time package as the current infrastructure of the time package is not designed to handle handle timezone operations using syscall
