### ISSUE TITLE
runtime: unexpected fault address 0x14000

### ISSUE THREAD

**Issue by EmpireJones** [golang/go#28278]
I'm not sure if there is enough info here to go off of, but thought I'd report it in case something can be derived...

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
Untested (I have only seen this issue once so far)

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?
I don't have a small reproducible example yet (I've only seen the issue once), but the output mentions grpc.
Race detection was enabled.

### What did you expect to see?
Nothing.

### What did you see instead?

```
unexpected fault address 0x14000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14000 pc=0x110428c]
goroutine 11840 [running]:
runtime: unexpected return pc for runtime.throw called from 0x29da3f0
stack: frame={sp:0x7fb1abffed40, fp:0x7fb1abffed70} stack=[0xc000f53000,0xc000f54000)
runtime.throw(0x7fb1abffedb8, 0x471a7f)
    /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0x7fb1abffed70 sp=0x7fb1abffed40 pc=0x449482
created by google.golang.org/grpc.(*Server).handleRawConn
    /home/kevin/project/src/google.golang.org/grpc/server.go:643 +0x6f9
goroutine
```

**Comment by agnivade** [comment]
Hi @EmpireJones,

This is very little info for anybody to debug the issue. We need instructions on how to reproduce the issue and a working code sample is preferred.

Otherwise, you will get better help in the various forums at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page.

**Comment by EmpireJones** [comment]
ok, I'll close, as the golang error doesn't provide enough info for me to dig into further either.

grpc version appears to be at 1.16.0-dev
