### ISSUE TITLE
cmd/compile: intrinsify more of math/bits on amd64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28273]
Now that more API has been added to math/bits (#24813), this is a tracking bug to intrinsify more of it in the compiler for amd64.

As @randall77 said in https://github.com/golang/go/issues/24813#issuecomment-430817068 ...

> Only Mul has been intrinsified so far.
> I think we want Add/Sub intrinsified also (or better, recognize the Go code and generate the add-with-carry instruction).

**Comment by randall77** [comment]
I'm ok with defining it to panic.
Divides are expensive enough that a compare and branch before each isn't a big overhead.

We should fix this for 1.12 before the API is set in stone.

**Comment by randall77** [comment]
Actually, probably deserves its own issue.
