### ISSUE TITLE
Possible bug in parsing of InitStmt expression of for-loop.

### ISSUE THREAD

**Issue by thaewrapt** [golang/go#28275]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11.1 linux/amd64
(Though, seems more versions are affected since it's present in Playground, see below)

### Does this issue reproduce with the latest release?
Haven't checked yet, though no open or closed issue regarding InitStmt was found.

### What operating system and processor architecture are you using (`go env`)?
Irrelevant, see below.

### What did you do?
First, this code, which may show some weird-yet-valid use of for-loop but still works:
https://play.golang.org/p/YRAkTiXiUIb

Then, the same code but using empty struct declaration directly in InitStmt of for-loop, not working:
https://play.golang.org/p/jNQCiG-2oL1

### What did you expect to see?
Both code snippets working (or not working) alike.

### What did you see instead?
Results differ (I believe due to parser bug misinterpreting '{' in "struct{}" for initial '{' of loop body).

**Comment by ianlancetaylor** [comment]
Search for "parsing ambiguity" in https://golang.org/ref/spec#Composite_literals .

**Comment by thaewrapt** [comment]
Sorry, the above-mentioned solution seems to apply to conditions only and therefore can't be used for InitStmt.

**Comment by thaewrapt** [comment]
So, the parsing ambiguity — yes, it certainly is, but I can't see how it can be resolved without using a factory like in my first playground snippet.

**Comment by adamdecaf** [comment]
```
for i:= (SomeStruct{}); i.somefield == nil; i = SomeMoreFactory() {
```
