### ISSUE TITLE
encoding/json: duplicate struct tags cause json.Marshal to silently fail

### ISSUE THREAD

**Issue by is8ac** [golang/go#28288]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
Marshal a struct containing duplicate struct tags silently produces an empty json struct.

Example:
```
package main

import (
	"encoding/json"
	"fmt"
)

type demoStruct struct {
	Foo uint8 `json:"baz"`
	Bar uint8 `json:"baz"`
}

func main() {
	fooStruct := demoStruct{Foo: 1, Bar: 2}
	fmt.Println(fooStruct)
	jsonBytes, err := json.Marshal(fooStruct)
	fmt.Println(err)
	fmt.Println(string(jsonBytes))
}
```

#### What did you expect to see?
`json.Marshal` gives an error.

#### What did you see instead?
`json.Marshal` silently returns an empty json struct.

#### System details

```
go version go1.11.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/isaac/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/isaac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11.1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.11.1
uname -sr: Linux 4.18.14-arch1-1-ARCH
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.28.
```

**Comment by agnivade** [comment]
FWIW, running it through vet does throw an error.

Paging @mvdan @dsnet for further comments.

**Comment by mvdan** [comment]
This is documented, so it cannot be changed - https://golang.org/pkg/encoding/json/:

> 3) Otherwise there are multiple fields, and all are ignored; no error occurs.

The same issue has been raised before, too. See https://github.com/golang/go/issues/17913 for example.

**Comment by is8ac** [comment]
Thank you for your comments.
As you say, `go vet` would have alerted me to this issue. I shall be sure to use on my code it in future.
