### ISSUE TITLE
invalid Cookie.Domain "localhost:3000"; dropping domain attribute   - Which is valid!

### ISSUE THREAD

**Issue by latdev** [golang/go#28297]
>>> Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64
NEXT STEP :: sudo port install go
go version go1.11.1 darwin/amd64

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

**NAME**  -  Is my username

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/**NAME**/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/**NAME**/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/local/lib/go"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lc/2r1wlzgn6jb12zmbjk0syyh40000gn/T/go-build259772903=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

If possible, provide a recipe for reproducing the error.

http - is import "net/http"
wr - is http.ResponeWriter

http.SetCookie(wr, &http.Cookie{
	Name: "sid",
	Value: cookie.Value, <------- Some Md5 value
	Expires: expires, <----- NOW+1h
	Domain: self.ConfGet("server.domain"),       // <------  self.ConfGet returns string  "localhost:3000"
	Path: "/",
	HttpOnly: true,
})

### What did you expect to see?
Hmmm...  localhost:3000 is valid domain for any browser!!!!   "localhost" domain and "localhost:3000" are different domains!!!

### What did you see instead?
2018/10/21 02:14:17 net/http: invalid Cookie.Domain "localhost:3000"; dropping domain attribute
2018/10/21 02:14:17 [::1]:53538 GET /static/ 200
2018/10/21 02:14:17 [::1]:53548 GET /echo 101
2018/10/21 02:14:17 net/http: invalid Cookie.Domain "localhost:3000"; dropping domain attribute

**Comment by kardianos** [comment]
> "localhost" domain and "localhost:3000" are different domains!!!

This is not accurate. A browser today shares cookies on localhost, regardless of the port.
