### ISSUE TITLE
cmd/compile: "invalid recursive type" should abort

### ISSUE THREAD

**Issue by bep** [golang/go#28294]
This seems to be similar to #21273 (fixed in Go 1.10).

```bash
▶ go version
go version go1.11 darwin/amd64
```

```go
package main

func main() {
	type int int
	type I int

	const i I = 1
}
```

The above fails with

```bash
./main.go:4:7: invalid recursive type int
./main.go:5:7: invalid recursive type I
./main.go:7:8: invalid constant type I
```

The above is clear enough in this small case, but I had this happen to me (again, an automatic refactoring gone wrong) in a bigger program and all I saw was a list of `invalid constant type` (that looked valid), and then `too many errors`.

**Comment by meirf** [comment]
Maybe this case should follow the same logic as [here](https://github.com/golang/go/issues/21273#issuecomment-340578806):

> There's no need to tell me T is an invalid map key after telling me it's an invalid anything.

This case is trickier though since I is `type`d of the original error type.

cc @griesemer

**Comment by griesemer** [comment]
This is [now](https://go.dev/play/p/OtqTfTOzDUa) (Go 1.18) reporting:
```
./prog.go:4:7: invalid recursive type int
	./prog.go:4:7: int refers to
	./prog.go:4:7: int
```
which seems reasonable. Closing as working as expected.
