### ISSUE TITLE
Failed to append string to []byte & append []byte to []byte

### ISSUE THREAD

**Issue by Iflier** [golang/go#28292]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Output from command go version:
go version go1.11 windows/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
OS: GOOS=windows (10)

### What did you do?
Go code as the follopwing:
var writeCommand []byte

func main() {
	fmt.Println(string(append(writeCommand, "github")))
	fmt.Println(string(append(writeCommand, []byte("com"))))
}
After go run the above code, I got:
Output from terminal:
 command-line-arguments
.\exam.go:10:42: cannot use "github" (type string) as type byte in append
.\exam.go:11:27: cannot use ([]byte)("com") (type []byte) as type byte in append

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
When I lookup for GoLang's document, they said that, I can do this:
**As a special case, it is legal to append a string to a byte slice, like this:**

**slice = append([]byte("hello "), "world"...)**
and this:
**slice = append(slice, anotherSlice...)**

But, when I try the above pasted code, all of the operation failed, I got the above mentioned error.

### What did you see instead?
As the document say, I except the following code work:
**slice = append([]byte("hello "), "world"...)**
**slice = append(slice, anotherSlice...)**
Anybody can give me a hand, thanks in advanced :-).

**Comment by robpike** [comment]
The "..." that you quote is important, but you left it out. It works if you do that:

https://play.golang.org/p/Ta_c7bboMbG

The ... says that single slice or string argument is to be treated as individual elements, which is what append expects.

**Comment by Iflier** [comment]
@robpike Oh, I think "..." is a ellipsis, so I made such a mistake. Thanks for your help, again :-).
