### ISSUE TITLE
proposal: spec: user-defined map keys

### ISSUE THREAD

**Issue by gopherbot** [golang/go#283]
by **jbamsterdam**:

<pre>The valid types for map keys are limited. User-defined types that meet the 
appropriate criteria (e.g. having Hash and Equals functions) should be 
permitted.

Alternatively, consider a library package that exposes the internal map 
implementation in a general way.</pre>

**Comment by rsc** [comment]
Moving priority-someday to the Unplanned milestone.

**Comment by tv42** [comment]
You could maybe use https://tip.golang.org/pkg/reflect/#StructOf instead of a map, to make compound keys.

**Comment by ianlancetaylor** [comment]
I'm going to close this.  If we had generics (#15292) that would be a better approach to this.  Or, write your own wrapper functions that use a map[uint64][]T and write a hash function from T to uint64 and code that uses your equals function on each element in the slice.  Or something like that.  Anyhow, we aren't going to add this particular case to the language itself, except via generics.
