### ISSUE TITLE
math/big: cannot calculate log16 of a 256 bit integer 

### ISSUE THREAD

**Issue by thisismohitgupta** [golang/go#28300]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
how it works in python...
```python
import math 
a = 0xc6d86e5a2cb4bc532361c2d4940f0b1a0138066e25d65c1c530d080b11f8ca24
a>>89940344608680314083397671686667731393131665861770496634981932531495305005604L
math.log(a)/math.log(16.0)
```
63.908875905794794
### What did you see instead?
does not work for Big Ints
```go
s := "c6d86e5a2cb4bc532361c2d4940f0b1a0138066e25d65c1c530d080b11f8ca24" // Hex value
i := new(big.Int)
i.SetString(s, 16)
// how to get the log with base 16 for a math/big Int variable.
```

**Comment by thisismohitgupta** [comment]
Thank You. That was exactly what I was looking for.

**Comment by cznic** [comment]
[Alternative solution](https://godoc.org/github.com/cznic/mathutil#example-BinaryLog)
