### ISSUE TITLE
database/sql/sql.go: Row Scan function rs.closemu.RUnlock has no defer 

### ISSUE THREAD

**Issue by chenyoufu** [golang/go#28307]
line 2922，no use a **defer** before RUnlock，thanks！

https://github.com/golang/go/blob/3bf9b77c0c8f123728fcfc802599232e9bd95476/src/database/sql/sql.go#L2910-L2923

**Comment by cznic** [comment]
Same as in #28305. Where and why a is a `defer` missing?

**Comment by kardianos** [comment]
Is there a reason to use defer in this case?

Please note, that Scan is designed to be called in a tight loop, so while defer is indeed much cheaper then before, it isn't free.
