### ISSUE TITLE
Misuse of `new` as variable causes compiler panic

### ISSUE THREAD

**Issue by AaronReboot** [golang/go#28301]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/KmBf4D8pEOn

#### What did you expect to see?

"cannot call non-function new (type int)"
Cf https://play.golang.org/p/-qTgmEn7pud

#### What did you see instead?

The compiler panics.

#### System details

```
go version go1.11.1 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/aaron/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11.1
uname -v: Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
lldb --version: lldb-1000.11.37.1
  Swift-4.2
```

**Comment by ctriple** [comment]
new is a builtin function, not a language keyword, it can be reused as any valid identifier.
for your situation, you have defined a int var named 'new' (initialized to int 0 by default).
and you use it as a function, which leads to nil pointer dereference panic.

**Comment by ctriple** [comment]
p@win64 MINGW64 ~
# cat /tmp/t.go
package main

func main() {
        var new int
        new()
}

p@win64 MINGW64 ~
# go build /tmp/t.go
# command-line-arguments
..\..\tmp\t.go:5:5: cannot call non-function new (type int)

p@win64 MINGW64 ~
# go run /tmp/t.go
# command-line-arguments
..\..\tmp\t.go:5:5: cannot call non-function new (type int)

p@win64 MINGW64 ~
# go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/msys64/home/Administrator/go
set GORACE=
set GOROOT=C:\msys64\mingw64\lib\go
set GOTMPDIR=
set GOTOOLDIR=C:\msys64\mingw64\lib\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\msys64\tmp\go-build602107274=/tmp/go-build -gno-record-gcc-switches

p@win64 MINGW64 ~
# go version
go version go1.10.1 windows/amd64

**Comment by ctriple** [comment]
i got what you want with go1.9.0 on linux amd64. maybe it's a compiler regression bug?
@griesemer

**Comment by agnivade** [comment]
Thanks for reporting.

This is fixed in tip. And will be backported to 1.11.2.
