### ISSUE TITLE
x/build/maintner: reports incorrect Hashtags for some CLs

### ISSUE THREAD

**Issue by dmitshur** [golang/go#28318]
CL https://go-review.googlesource.com/c/gddo/+/135536 (36 days old) has a `no-owners` hashtag:

![image](https://user-images.githubusercontent.com/1924134/47282821-a68bb680-d5ae-11e8-8f6d-7f4bd0cd682e.png)

However, the current `maintner` corpus reports that it does not have any hashtags:

```Go
package main

import (
	"context"
	"fmt"
	"log"

	"golang.org/x/build/maintner/godata"
)

func main() {
	corpus, err := godata.Get(context.Background())
	if err != nil {
		log.Fatalln(err)
	}
	proj := corpus.Gerrit().Project("go.googlesource.com", "gddo")
	cl := proj.CL(135536)
	tags := cl.Meta.Hashtags()
	const tagNoOwners = "no-owners"
	fmt.Println(tags.Contains(tagNoOwners))

	// Output: false
}
```

It should print `true`.

This also affects some other CLs, including (not an exhaustive list):

- https://go-review.googlesource.com/c/gddo/+/135537 (36 days old)
- https://go-review.googlesource.com/c/go/+/120215 (5 days old)

So far, I haven't found the pattern of which CLs are affected. It seems to affect CLs in main repo and subrepo, and affects quite recent CLs as well as older ones. Many other CLs have correct hashtags.

/cc @bradfitz

**Comment by Skarlso** [comment]
@dmitshur Hi! :)

I'm a first time contributor here. I have experience with Go and would very much like to investigate, go down a rabbit hole and find out what's happening and fix it. :)

I've read the surrounding issues and have a vague idea of where to start. I have very little knowledge yet, but I seek to understand things better and be a contributor to Go in the long run. This is the first programming language I love to use for years and I would like to give back to it!

If you don't mind, I would like to take a stab at this. I've read the contribution guideline and did setup my environment.

**Comment by bradfitz** [comment]
@Skarlso, go for it. This is a nice self-contained problem so it'd be a good starter bug. Thanks!

**Comment by Skarlso** [comment]
Awesomesauce!

On it. :) Thanks!

**Comment by Skarlso** [comment]
Okay, I had time a little to play with this. What's happening is, that this thing is parsing the commit message to access the last entry like this: 

```go
// Footer returns the "key: value" lines at the base of the commit.
func (m *GerritMeta) Footer() string {
	i := strings.LastIndex(m.Commit.Msg, "\n\n")
	if i == -1 {
		return ""
	}
	return m.Commit.Msg[i+2:]
}
```

Looking for a thing called Hashtag in here. 

What's happening is, that on some issues, the commit message is updated, and the LAST entry in the list of commit messages will not be something that contains a Hashtag entry, but rather a message like, `Uploaded patch set 5: Commit message was updated.`.

Which in turn will no longer have this entry:

```
DEBUG: Message:  Update patch set 1

Hashtag added: wait-author
```

I'm not sure yet what the fix will be, but I'm on the right path, I think.

It's getting later however, so I'll be continuing this tomorrow.

**Comment by Skarlso** [comment]
The fix will probably involve parsing out the hashtag from somewhere else maybe, or something like, if it's encountered, save it and always display it unless a remove is encountered. Not sure yet.

Also, I need to fully understand what's happening in the display code under gerrit.go. :)

**Comment by Skarlso** [comment]
I have a failing unit test!

```go
		commit: `Update patch set 1

Hashtag added:   bar

Patch-set: 1
Hashtags:
Tag: autogenerated:gerrit:setHashtag

Update patch set 2
`,
		wantAdd: "bar",
	},
```

The exact problem is that this line:

```go
Tag: autogenerated:gerrit:setHashtag
```

... is missing from the consecutive update. Which makes things more interesting. If this line would be sent along the update, things would work.

**Comment by Skarlso** [comment]
I think I understand what's going on. The parser parses the messages backwards then reverses the commits messages so we get the last one. But the last one in this case will be a newPatchSet and will not contain the setHashtag action.

So, I'm wondering. Is this something that you (@dmitshur) tried to address with your change set here: https://go-review.googlesource.com/c/build/+/145258/ ?

**Comment by Skarlso** [comment]
Yeah no. That only seems to be an update on displaying things. Doesn't change anything relevant to this issue if I understand it correctly

**Comment by Skarlso** [comment]
I have a working fix 🎉 

Need to write some unit tests around it first.

**Comment by Skarlso** [comment]
Yay! I'm looking forward to working together with you guys @dmitshur  @bradfitz to get this solved. I hope the solution suits the needs and is in alignment with the rest of the project. If not, please let me know and I will address any issues that might come up.

Cheers,
Gergely.
