### ISSUE TITLE
go/types doesn't support go module?

### ISSUE THREAD

**Issue by Hexilee** [golang/go#28328]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
darwin_amd64

### What did you do?
I am using go module and have set env variable `GO111MODULE=on`.

```
- root
   - main.go
   - go.mod
   - go.sum
```

This is the `main.go`

```go
import (
    _ "github.com/xxx/yyy"
    "go/ast"
    "go/build"
    "go/importer"
    "go/parser"
    "go/token"
    "go/types"
    "log"
)

var fileSet  = token.NewFileSet()
func main() {
    file, err := parser.ParseFile(fileSet, "main", nil, parser.ParseComments)
    if err != nil {
        log.Fatal(err.Error()) // type error
    }
    conf := types.Config{Importer: importer.Default()}
    pkg, err := conf.Check(".", fileSet, []*ast.File{file}, nil)
    if err != nil {
        log.Fatal(err.Error()) // type error
    }
}
```

This is the `go.mod`

```
module github.com/me/myproject

require github.com/xxx/yyy v0.0.0-20160315200505-970db520ece7
```

I can execute `go build` successfully. But when I run it, it complain `could not import github.com/xxx/yyy`

### What did you expect to see?
The `go/types` can keep the same behavior with `gc` compiler. 

### What did you see instead?
No

**Comment by agnivade** [comment]
Please see @myitcv's comment https://github.com/golang/go/issues/27556#issuecomment-419468978.

Going forward, please use `go/packages` to type check modules.

I am going to close the issue. Please feel free to comment on https://github.com/golang/go/issues/24661 if you have any module specific questions with tooling. Or use any of the [forums](https://github.com/golang/go/wiki/Questions) to get further info on go/packages. 

Thanks.
