### ISSUE TITLE
cmd/go: 'go mod download $(go list -m)' fails silently

### ISSUE THREAD

**Issue by JohnTitor** [golang/go#28338]
### What version of Go are you using (`go version`)?

go1.11 windows/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10, amd64

### What did you do?

`go mod download` doesn't work well when `go mod init` without version.
(If you run `go mod download something.com/something@latest`, doesn't work well too.)

### What did you expect to see?

Display message (e.g. `go mod init: must be set version`)

### What did you see instead?

Nothing.
Displaying no message isn't user-friendly I think.

**Comment by bcmills** [comment]
> when `go mod init` without version.

What do you mean? `go mod init` does not normally accept a version.

Please post a complete trace of the commands that you ran and the output they produced.

**Comment by diplozoon** [comment]
Please excuse my poor English.

The command as follow:
- `go mod init github.com/lib/pq`
  - run this, cannot download modules even if run `go mod download github.com/lin/pq@latest`.
- `go mod init github.com/lib/pq@latest`
  - run this, can download modules if run `go mod download github.com/lib/pq@latest`.

**Comment by bcmills** [comment]
> - `go mod init github.com/lib/pq`
>   - run this, cannot download modules even if run `go mod download github.com/lib/pq@latest`.

That may be a bug, but it's a very strange sequence of commands to run.

* `go mod init github.com/lib/pq` tells the `go` command, “this module contains the source code for `github.com/lib/pq`.
* `go mod download github.com/lib/pq@latest` tells it “download the latest source code for `github.com/lib/pq`”.

Since the module itself (by its own definition) contains the source code you requested, in some sense `go mod download` has no work left to do.

> - `go mod init github.com/lib/pq@latest`

If that command works at all, that's arguably a bug: the `@latest` is normally a version specification, not part of the module path, but `go mod init` takes only a module path.

I'll open a separate issue for that.

**Comment by bcmills** [comment]
The lack of a useful error message is closely related to #27783.

**Comment by iWdGo** [comment]
Issue seems solved
```
$GOPATH\src\mymod>go version
go version go1.12.2 windows/amd64

$GOPATH\src\mymod>go mod init github.com/lib/pq@latest
go mod init: module path must not contain '@'
```

**Comment by bcmills** [comment]
@iWdGo, we could still use a better diagnostic for `go mod download` with the name of the main module and `@latest`. It should either download the latest upstream version, or emit some kind of useful diagnostic; today it still does neither:

```
pq$ gotip mod init github.com/lib/pq
go: creating new go.mod: module github.com/lib/pq

pq$ gotip version
go version devel +a4c82515 Mon Aug 5 23:12:39 2019 +0000 linux/amd64

pq$ gotip mod download github.com/lib/pq@latest

pq$ find $GOPATH/pkg/mod
/tmp/tmp.doY4ctA1kP/_gopath/pkg/mod
/tmp/tmp.doY4ctA1kP/_gopath/pkg/mod/cache
/tmp/tmp.doY4ctA1kP/_gopath/pkg/mod/cache/lock
```

**Comment by iWdGo** [comment]
The fix is a marginal improvement for an unknown or non-existent dependency. A complete solution requires to get a relevant message from the list of modules as described in [#26152](https://github.com/golang/go/issues/26152#issuecomment-516468145).
