### ISSUE TITLE
archive/zip: FileHeader.FileInfo().ModTime() should use Modified

### ISSUE THREAD

**Issue by Xjs** [golang/go#28350]
Since Go 1.10, `archive/zip.FileHeader` contains a `Modified` field supporting extended timestamps. However, `FileHeader.FileInfo()` returns a `os.FileInfo` implementation whose `ModTime()` method still returns the legacy mod time. This should be changed to return Modified. A hint documenting that `FileInfo()` uses legacy fields would be nice for the time being.

As far as I can tell, `headerFileInfo` has direct access to the `Modified` field. Is there a reason why it wasn't included that I am missing, or was it just an oversight?

**Comment by mattn** [comment]
As far as I remember, this is discussed in https://github.com/golang/go/issues/18359

**Comment by bcmills** [comment]
CC @dsnet @bradfitz

**Comment by dsnet** [comment]
Already commented on the CL. I believe the change is in the right direction, but needs to have a fallback for the legacy timestamp fields.
