### ISSUE TITLE
cmd/compile: value converted to uintptr escapes to heap

### ISSUE THREAD

**Issue by ainar-g** [golang/go#28369]
```
go version go1.11 linux/amd64
go version devel +5538ecadca Wed Oct 24 20:08:18 2018 +0000 linux/amd64

$ nl -b a foo.go 
     1	package foo
     2	
     3	import "unsafe"
     4	
     5	var top uintptr
     6	
     7	func f(n int) int {
     8		if n == 0 {
     9			top = uintptr(unsafe.Pointer(&n))
    10			return n
    11		}
    12	
    13		return 1 + f(n-1)
    14	}
$ go build -gcflags "-m" foo.go
# command-line-arguments
foo.go:9:32: &n escapes to heap
foo.go:7:8: moved to heap: n
```

Playground: https://play.golang.org/p/AP4_XYd5tFX.

`n` here shouldn't escape, since its address is only taken for debugging purposes. The usage of `unsafe.Pointer` is correct, see [(2)](https://golang.org/pkg/unsafe/#Pointer). If I comment out line 9, cmd/compile doesn't move `n` to heap, as it should.

**Comment by randall77** [comment]
@dr2chase

**Comment by dr2chase** [comment]
One of the places where this wrong-fix causes a difference in allocation behavior is test/gogcrt.go, line 174
```
				a[new(bool)] = false
```

Putting this off (unless someone else is interested) till after the freeze.

**Comment by odeke-em** [comment]
Hello @dr2chase @randall77, shall we punt this to Go1.13? If for Go1.13, @dr2chase let's team up and work on this issue during the cycle.

**Comment by dr2chase** [comment]
Definitely punt to 1.13, this is not a crash, and I don't think this is a regression, either.
@mdempsky is working on (mostly done with) a rewrite of the escape analysis code, his new code might handle this more nicely (or at least more understandably).

I don't much like the the bit about my change passing escape analysis tests, yet producing a sometimes-crashing build.

**Comment by mdempsky** [comment]
My escape analysis rewrite keep n allocated on the stack.

**Comment by ainar-g** [comment]
@mdempsky I'm on version 13b7c04d3f, and it seems fixed. Should I close the issue, or is there something else to do here, like adding test cases?

**Comment by mdempsky** [comment]
@ainar-g A regress test case CL would be great!

**Comment by ainar-g** [comment]
This is my first change to test/, so I'm not entirely sure I've done it correctly.
