### ISSUE TITLE
misc/wasm: isNodeJS does not work with Parcel

### ISSUE THREAD

**Issue by SamWhited** [golang/go#28364]
The Go webassembly loader that ships in `misc/wasm/wasm_exec.js` currently detects Node.JS using the following:

    const isNodeJS = typeof process !== "undefined";

However, if you attempt to bundle it with some other code, for example, with [Parcel](https://parceljs.org/), it adds a shim which breaks the previous check:

    // shim for using process in browser
    var process = module.exports = {}; // cached from whatever global is present so that test runners that stub it
    // don't break things. …

This means that `TextEncoder` and the like are redefined to undefined and everything breaks.

I don't know anything about JavaScript or the JavaScript ecosystem, so I'm not sure if there's a better way to detect Node.JS, but maybe it would be better to detect individual features instead of trying to check what platform we're running on. Eg. instead of setting up TextEncoder if isNodeJS is false, check if `global.TextEncoder` is null and `util.TextEncoder` is not null.

**Comment by bcmills** [comment]
CC @neelance

**Comment by neelance** [comment]
@SamWhited Would this work with Parcel?
```
const isNodeJS = typeof process !== "undefined" && process.title === "node";
```
