### ISSUE TITLE
x/image/font/sfnt: horizontal metrics table (hmtx) validation is incorrect

### ISSUE THREAD

**Issue by dennwc** [golang/go#28379]
### What did you do?

Parse an embedded TTF font from [PDF object](https://github.com/unidoc/unidoc/blob/v3/pdf/model/testdata/font/townes.txt).

### What did you expect to see?

no error

### What did you see instead?

```
sfnt: invalid hmtx table
```

### Details

It seems that the validation code for `hmtx` table is incorrect. The library assumes `2*numGlyphs + 2*numHMetrics`, while the [spec](https://www.microsoft.com/typography/OTSPEC/hmtx.htm) describes it as `4*numHMetrics [+ 2*(numGlyphs-numHMetrics)]`.

**Comment by dennwc** [comment]
Values in the font: `numHMetrics=183, numGlyphs=3415, hmtx.length=732`.

**Comment by nigeltao** [comment]
In case anyone else was confused, the square brackets in @dennwc's original post: `4*numHMetrics [+ 2*(numGlyphs-numHMetrics)]` means optional. In different words, the bug report argues that the sfnt package should accept either of `4*nHM` or `4*nHM+2*(nG-nHM)`. Note that the latter form simplifies to `2*nHM+2*nG`, which is what the package implements today.

The original bug report also claimed that the spec allows for just `4*nHM`, but I don't think the spec actually says that.

Still, a comment in [the freetype library's ttload.c](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/sfnt/ttload.c#n226) says:

```
/* Some tables have such a simple structure that clipping its     */
/* contents is harmless.  This also makes FreeType less sensitive */
/* to invalid table lengths (which programs like Acroread seem to */
/* ignore in general).                                            */
if ( table.Tag == TTAG_hmtx || table.Tag == TTAG_vmtx ) etc
```

and also, eyeballing its [tt_face_get_metrics function in ttmtx.c](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/sfnt/ttmtx.c#n302) suggests that FreeType doesn't enforce that the hmtx table is exactly `2*nHM + 2*nG` long.
