### ISSUE TITLE
cmd/go: reject module path beginning with slash

### ISSUE THREAD

**Issue by rsc** [golang/go#28389]
Re #28336, we should 

1. Reject `go mod init /absolute/path`.
2. Refuse to load any `go.mod` that says `module /absolute/path`.

If we'd done either of those (we should do both), then the confusing build errors in #28336 would not have happened.

**Comment by tandr** [comment]
To me it seems that denying full path in mod or init it would be counterproductive for people willing (or have no choice but) to specify a full path because thats how they have their build system set up

I would not surprised to have expect this in a bootstrap script
 ```
go mod init /bigdisk/buildmount/$USER/$REPO/some/path
```

**Comment by jayconrod** [comment]
For reference, `cmd/go/internal/module.CheckPath` is the function `go get` uses to validate module paths. It performs a number of checks, not just for leading slashes.

In tests, I think we're using module paths that don't satisfy this check (e.g., the module path is a single word without a `.`). It's likely other people are taking advantage of this as well, both in tests and in monorepos that are never fetched with `go get`.

**Comment by wselwood** [comment]
Trailing slashes should probably also be blocked. It works as long as you don't have sub packages. As soon as you try to import a sub package you get errors like 
`build github.com/satappscatapult/warmconsidering/: cannot find module for path github.com/satappscatapult/warmconsidering/message`

which is mighty confusing 

series of comands
```
go mod init github.com/satelliteapplicationscatapult/warmconsidering/
code .
# write some things and create a submodule
go build
build github.com/satappscatapult/warmconsidering/: cannot find module for path github.com/satappscatapult/warmconsidering/message
```
edit the go.mod file to remove the trailing slash from the build starts to work as expected.

**Comment by seankhliao** [comment]
This is now rejected with `go: malformed module path "/example": empty path element` in both cases
