### ISSUE TITLE
fatal: morestack on g0 on win10

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#28381]
i found error in windows 10：
2018-10-25 14:27:15 [INFO] gseeproxy ok ......!
2018-10-25 14:27:15 [INFO] Hello World!
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0

i used go call c++ func and have a fatal error！
used go version：
go version go1.10.3 windows/386

**Comment by zhaoya881010** [comment]
the question already  resolve？i found in issues？

**Comment by agnivade** [comment]
Also, please try with 1.11.1. Thanks.

**Comment by zhaoya881010** [comment]
@agnivade  1.11.1 is ok

**Comment by zhaoya881010** [comment]
@agnivade very thanks!

**Comment by agnivade** [comment]
Sounds like this is resolved.
