### ISSUE TITLE
x/image/font/sfnt: support trimmed table mapping cmap format 

### ISSUE THREAD

**Issue by dennwc** [golang/go#28380]
### What did you do?

Parse an embedded TTF font from [PDF object](https://github.com/unidoc/unidoc/blob/v3/pdf/model/testdata/font/tesseract.txt).

### What did you expect to see?

no error

### What did you see instead?

```
sfnt: unsupported cmap encodings
```

### Details

The cmap in this file uses [Format 6: Trimmed table mapping](https://docs.microsoft.com/ru-ru/typography/opentype/spec/cmap#format-6-trimmed-table-mapping) which is [not supported](https://github.com/golang/image/blob/master/font/sfnt/cmap.go#L78) by the library.

**Comment by sbinet** [comment]
this was fixed w/ https://github.com/golang/image/commit/183bebdce1b249c42a7cf6772817e8c2e873b966
