### ISSUE TITLE
library encoding/binary ignores int parameters without error

### ISSUE THREAD

**Issue by pschlump** [golang/go#28392]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/corwin/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/corwin/go:/Users/corwin/Projects"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tq/wcgskp_n1w13k3_233v6j2rw0000gp/T/go-build172545901=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

I looked at the source for the encoding/binary.  It uses reflection to determine the type of the
parameter.  There is no code to catch and report an error.  If you do not supply the
types that it is expecting then it just ignores the parameter.   The work-acrount/fix is to
type case `int` to `int64(var)` and then it works.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
package main

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

// See: /usr/local/go/src/encoding/binary/binary.go : 352 - missing default in switch - no error reported.

func main() {
	// Fails silently (no error, no output)
	a := TestWriteOfInt(22)
	b := TestWriteOfInt(23)
	fmt.Printf("a = %x\n", a)
	fmt.Printf("b = %x\n", b)

	// Works
	c := TestWriteOfInt64(22)
	d := TestWriteOfInt64(23)
	fmt.Printf("c = %x\n", c)
	fmt.Printf("d = %x\n", d)
}

func TestWriteOfInt(AnInt int) []byte {
	var buf bytes.Buffer
	binary.Write(&buf, binary.BigEndian, AnInt)
	s := buf.Bytes()
	return s
}

func TestWriteOfInt64(AnInt int64) []byte {
	var buf bytes.Buffer
	binary.Write(&buf, binary.BigEndian, AnInt)
	s := buf.Bytes()
	return s
}
```

### What did you expect to see?

I expect either an error if the type passed is invalid - or - some code for handling every type
that makes any sense.

### What did you see instead?

No data written, no error reported.

I am willing to make a patch to the library (pull request) and fix this.

**Comment by bcmills** [comment]
> No data written, no error reported.

No error is reported because you are missing an error check.
(https://play.golang.org/p/zU4VFxX8Pf6)

#20803 would make that a compile-time error.
