### ISSUE TITLE
x/build/env/openbsd: set sysctl hw.smt=1

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28403]
The OpenBSD images should disable Spectre/Meltdown protections and set `sysctl hw.smt=1` per

https://go-review.googlesource.com/c/build/+/144777#message-b10c10646c34b670194db8c9d72ac8a551d3ab80

**Comment by dmitshur** [comment]
For reference, I tried `sysctl hw.ncpuonline` on a `openbsd-386-64` builder, and it reported `hw.ncpuonline=4` despite not having `hw.smt` (compared to `hw.ncpuonline=2` which `amd64` builder reports until you set `hw.smt=1`).

I understand that to mean that SMT is not disabled on 32-bit OpenBSD.
