### ISSUE TITLE
x/exp/utf8string: rename NewString to New

### ISSUE THREAD

**Issue by ainar-g** [golang/go#28415]
I am not sure what's the policy on `x/exp` API stability, so feel free to close or make into a proposal if needed.

There are `container/list.New`, `text/template.New`, `log.New`, etc. I think that `utf8string.NewString` shouldn't stutter either and should become `utf8string.New`.

**Comment by agnivade** [comment]
/cc @robpike @adg 

I did not see any owners in the doc. Figured you guys would be able to answer from the commit history.

**Comment by mpvl** [comment]
This is a leftover from when this functionality was in core, pre 1.0.  In general, I would not break the API gratuitously, even when in exp. If anything, New could be added and NewString marked as deprecated.

I'm interested to know what kind of use cases people have for this package, btw.

**Comment by ainar-g** [comment]
I don't have a use case for it to be honest. I just stumbled upon it while looking at stuff in `x/exp`.

If the response is "Don't touch it, it's basically frozen", I guess this issue can be closed, although a notice in the package doc saying

>This is a leftover from when this functionality was in core, pre 1.0. Please don't use.

would be nice.

**Comment by mpvl** [comment]
It is fine to use this package, but my suspicion was it would not be used in practice much. So I'm just always curious about actual use cases. But it is okay to leave it as is.
