### ISSUE TITLE
all: freebsd/ppc64 not supported

### ISSUE THREAD

**Issue by pkubaj** [golang/go#28442]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
freebsd/amd64

### What did you do?
I tried to bootstrap Go for freebsd/ppc64.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I expected to see bootstrapped Go for freebsd/ppc64.

### What did you see instead?
```
cmd/go: unsupported GOOS/GOARCH pair freebsd/ppc64
go tool dist: FAILED: /usr/local/go-freebsd-ppc64-bootstrap/pkg/tool/freebsd_amd64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2
```

**Comment by ianlancetaylor** [comment]
We would be happy to accept patches to support this, following the requirements listed at https://golang.org/wiki/PortingPolicy.

**Comment by pkubaj** [comment]
Since I don't have the resources necessary to maintain a port, I'm closing this.
