### ISSUE TITLE
virustotal warnings

### ISSUE THREAD

**Issue by macvk** [golang/go#28457]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.11.1 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
amd64 windows

### What did you do?
here is my program source code
file dnsleaktest.go

package main
func main() {
}

I built it with this command line
go build -o dnsleaktest.exe dnsleaktest.go

### What did you expect to see?
I've expected to see the green rating on virustotal.com

### What did you see instead?
https://www.virustotal.com/#/file/af6bc9900800a41c10338edfae19066b49f919df0e49892f1d25010324e4d729/detection

**Comment by agnivade** [comment]
Hi @macvk - Thank you for reporting the issue. Unfortunately issues like this are seen frequently with Windows systems. Please see - https://golang.org/doc/faq#virus

To confirm whether your GO distribution is affected or not, you can always check the checksum from the site.

Thank you.

**Comment by macvk** [comment]
Hi, @agnivade 

The checksum is match. I've used travis-c for building and the result is the same. Sorry, I am not going to email every of antivirus vendor because it will take a lot of time which I don't have. This is totally your issue and you should sort it out. Moving this issue to FAQ - is the worst scenario. MS visual studio, mingw, borland c haven't experienced such issue.

**Comment by macvk** [comment]
is it possible to not close the unresolved issues?

**Comment by macvk** [comment]
I've built the binary on Linux rather than Windows.

**Comment by dominikh** [comment]
This issue is with the vendor of your virus scanner, not Go. If a third party decides that some arbitrary pattern in Go binaries means that Go binaries are evil, then that is nothing we can reasonably do about. It is on the vendor to not use patterns that produce false positives.

**Comment by macvk** [comment]
But you can go this way. Remove all the modules from golang and try to build the empty application without any modules. Then add modules one by one and test them on virustotal. All in all you can find out which module bring about the antivirus warnings. I think you understand my idea.

**Comment by corganfuzz** [comment]
using avira antivrus, Created an exception on c:\users\[yourusername]\appdata\local\temp... or specifically where the build happened. which fixed the warnings and also the slowness every time go built anything.
