### ISSUE TITLE
access: approvers

### ISSUE THREAD

**Issue by ceseo** [golang/go#28469]
I would like to request approver access, understanding that it would primarily be for changes related to ppc64x.

Gerrit e-mail: cseo@linux.vnet.ibm.com
Gerrit contributions: https://go-review.googlesource.com/q/owner:cseo%2540linux.vnet.ibm.com
Ref: https://go-review.googlesource.com/#/admin/groups/1005,members

**Comment by katiehockman** [comment]
Done. Thanks for your contributions!
