### ISSUE TITLE
wiki: CodeReviewComments change

### ISSUE THREAD

**Issue by cn007b** [golang/go#28468]
Is it possible to add disclaimer or label or something like this
which will help figure out is this page related only to `go` core repository
or it's related to `go` code all over the world and it's list of `go` best practices.

Prerequisites:
I'd used this page as reference in [my answer](https://stackoverflow.com/a/52421001/3612353) on stackoverflow but after some time I've found next comment to my answer: 
> the document is actually a set of rules to write "core" Go code

**Comment by katiehockman** [comment]
@cn007b Could you clarify a bit more about what you are suggesting for this? What part of the documentation is unclear, and what do you expect for it to say instead?

It looks like you link to http://go/gh/golang/go/wiki/CodeReviewComments#receiver-names in your Stackoverflow answer, is that the wiki page you are referring to in this issue?

**Comment by dgryski** [comment]
Most people use the Code Review Comments as guidelines for all Go code, not only the Go compiler and standard library.  I don't think it needs a comment explaining this.

**Comment by cn007b** [comment]
Maybe it make sense just add one more additional line into description in top of this page which says:
> guidelines for all Go code, not only the Go compiler and standard library
or something like this...

**Comment by bcmills** [comment]
As noted, the guidelines are intended to be widely applicable. A disclaimer would not be appropriate.
