### ISSUE TITLE
gofmt: Convert to and from named fields for struct initialization

### ISSUE THREAD

**Issue by mamaso** [golang/go#28473]
I'd love for gofmt to provide the ability to convert to and from named fields in struct initialization, e.g.

```go
testCases := []struct {
  name string
  wantErr bool
}{
  { "test1", true },
}
```
becomes
```go
testCases := []struct {
  name string
  wantErr bool
}{
  {  
    name: "test1",
    wantErr: true, 
  },
}
```

**Comment by ianlancetaylor** [comment]
The gofmt tool doesn't convert to and from different kinds of output.  That's not the kind of tool that it is.  That said, `gofmt -s` does simplify some code like this.  And it would not be hard to write a different tool to do what you want, perhaps using the gofmt code as a base.

**Comment by mamaso** [comment]
@ianlancetaylor thanks for the quick response, appreciate it.

This seems similar in style to a `gofmt -r 'rule'` command, which does some output conversion.
Agreed that it wouldn't be too difficult to write a different tool for this (IDE refactoring tool, vim commands, etc), but I'd love to see this in common tooling.

**Comment by mamaso** [comment]
For anyone else running into this, it looks like the [keyify](https://github.com/dominikh/go-tools/tree/master/cmd/keyify) package provides the functionality I'm looking for.
