### ISSUE TITLE
wiki: CodeReviewComments change in Receiver Names section

### ISSUE THREAD

**Issue by rillig** [golang/go#28475]
The [Receiver Names](https://github.com/golang/go/wiki/CodeReviewComments#receiver-names) section states:

> Don't use generic names such as "me", "this" or "self", identifiers typical of object-oriented languages that place more emphasis on methods as opposed to functions.

As a reader, I'd like to know _why_ this rule exists and what its purpose is. But the above text only states the rule, it doesn't offer an explanation.

I also don't get the _more emphasis_ part. Does it refer to some insider joke? It confused me more than it helped.

(Background: JetBrains' GoLand has an inspection that refers to this rule, and I'd like to add one or two sentences explaining the _reason_ behind this rule. From the existing description of the rule, I could not extract the reason for its existence.)

**Comment by ianlancetaylor** [comment]
There is no joke here.  A language like Java emphasizes methods.  The closest that Java gets to what Go calls a function is a static method.

The point of this rule is that the receiver of a method is just another parameter, and it should be named accordingly.  The receiver is not special.

**Comment by agnivade** [comment]
I have updated the wiki.
