### ISSUE TITLE
x/playground: store code between sessions in user's browser 

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#28476]
What do you think about adding this feature?

The most recently entered code will be automatically saved in your browser's local storage. This allows you to recover your last work even if you close the browser.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

What puzzles and prevents me from drafting a patch is a need to add a new button for resetting the program code.

@andybons @bradfitz

**Comment by andybons** [comment]
I don’t think adding another caching layer to the playground (that we don’t control and is pretty opaque) is worth it. Without the proper UI it would be very confusing to have things saved in perpetuity using `localStorage`. Aside from this issue, has this been reported as a common problem people run into? I worry that it’s a solution in search of a (more widespread) problem.

**Comment by ysmolsky** [comment]
This was rather brainstorming and seeing if this resonates with the others. The other day I was editing the code in playground and suddenly closed the tab, losing some work. But again, this happened only twice and playground is like a throw away sketch pad for many. 

Unless this bug attracts attention of some part of community, I will close it in 2 weeks.

**Comment by andybons** [comment]
SGTM. Thanks, Yury.

**Comment by ysmolsky** [comment]
Closing it down due the lack of resonance.
