### ISSUE TITLE
x/build/cmd/genbootstrap: bootstrap with go1.4 fails on certain builders

### ISSUE THREAD

**Issue by tklauser** [golang/go#28483]
The build on some builders using go1.4 to bootstrap fails with:

```
Building Go cmd/dist using /tmp/workdir/go1.4.
Building Go toolchain1 using /tmp/workdir/go1.4.
../../../go1.4/src/text/template/funcs.go:12:2: cannot find package "net/url" in any of:
	/tmp/workdir/go1.4/src/vendor/net/url (vendor tree)
	/tmp/workdir/go1.4/src/net/url (from $GOROOT)
	/tmp/workdir/go/pkg/bootstrap/src/net/url (from $GOPATH)
go tool dist: FAILED: /tmp/workdir/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: exit status 1
```

openbsd-386-64: https://build.golang.org/log/c79fb02ba46df875ad35c621f96172d474d3ff4c
openbsd-amd64-64: https://build.golang.org/log/f50eaf129492daeedc42387ff93b3bcd6fbc6e41
solaris-amd64-smartosbuildlet: https://build.golang.org/log/5e7398620b2c542aa89c257c72f58d064c9ece49

However, building locally on OpenBSD 6.4 with the go1.4 tarball from https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz works just fine. Is there something wrong with go1.4 on these builders?

/cc @bradfitz @dmitshur

**Comment by tklauser** [comment]
Some more:

linux-arm64-packet: https://build.golang.org/log/975387f8c49361772b9f565010a51538dee442dc
linux-ppc64le-buildlet: https://build.golang.org/log/9a0bfa707bf89e0695f7aad6b9586a9551ac10a1

**Comment by ianlancetaylor** [comment]
That's weird, Go 1.4 definitely has net/url.

**Comment by bradfitz** [comment]
Also plan9-386:
https://build.golang.org/log/e63681117fca9b0a6d9b2b4c8580750213c4cd62

They all started failing at @ianlancetaylor's https://go-review.googlesource.com/c/go/+/144340 ("cmd/compile: add -lang flag to specify language version").

That CL did alter which imports were needed during bootstrap.

It makes `cmd/compile/internal/gc` depend on `go/build` which implicitly depends on `net/url`.

So maybe we just need to add `net/url` to some bootstrap slice/map in `cmd/dist`?

**Comment by bradfitz** [comment]
To `var bootstrapDirs` probably. Will try.

**Comment by bradfitz** [comment]
Actually, it gets messy quickly. `go/build` depends on a ton of things and many of them reach into the runtime for private symbols. I'm not able to find a set of additions to `bootstrapDirs` that successfully bootstraps. (I'm testing on a plan9-386 gomote somewhat arbitrarily, but any failing builder should do)

**Comment by ianlancetaylor** [comment]
But since Go 1.4 does have net/url, and, for that matter, go/build, I don't understand what the problem is.  Also, of course, it works for me, and I'm bootstrapping with Go 1.4.  And it works on some of the builders but not others.  So what is the difference?

**Comment by bradfitz** [comment]
New theory is that the problem is genbootstrap removing too much stuff. (We never previously needed "net" and it was removing "net/...")

**Comment by katiehockman** [comment]
The CL doesn't look like it fixed the issues. Still seeing the same errors for darwin arm64. Here's the latest build: https://build.golang.org/log/e8488a7ffa9a2c554c57606d2503653f2dbdaf12

**Comment by katiehockman** [comment]
Ah thanks for the correction. I'm triaging a lot of build-related issues, so I must have gotten them mixed up.
Sure I'd be interested! I think @dmitshur was showing some build-related release processes to me recently, but I haven't deployed them before.

**Comment by bradfitz** [comment]
Actually I forgot how the packet builders were configured so in the process of reading the README, I just re-ran the build.sh Docker script and restarted the docker & rundockerbuildlet systemd services and fixed it. (And also ran a hacked-up cmd/retrybuilds with a new flaky phrase substring to retry those entries on the dahsboard)

But you may want to log into that host and look around if you're curious. The info is in the env/linux-amd64/packet README.
