### ISSUE TITLE
NOT SUPPORT send SIGINT  to other process on windows?

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#28498]
i has a bug:
code:
p,_ :=os.FindProcess(**)
p.Signal(syscall.SIGINT)
error:
not supported by windows

go version 1.11.1 32bit on windows.

**Comment by agnivade** [comment]
Please check the documentation - https://golang.org/pkg/os/#Process.Signal.

> Signal sends a signal to the Process. Sending Interrupt on Windows is not implemented.

I am going to close this as WAI. If you would like this to happen, kindly open a new issue. Thank you.

**Comment by zhaoya881010** [comment]
@mattn thanks，it‘s ok！
