### ISSUE TITLE
multiple http requests

### ISSUE THREAD

**Issue by SavostinVladimir** [golang/go#28501]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.2 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
Hello! I am trying to download a large volume of data divided into blocks. The blocks are of the same type, but for each block it is necessary to do the http-request. I try to break all the data into portions and download each portion in a separate gorutine. Then I can download 3600 blocks per minute if I use 80 gorutines.
I have an instance "Collector" with `httt.Client`:

    type Collector struct {
	DB     *pg.DB
	Blocks chan Block
	client        *http.Client
	maxErrorCount int
	apiKey        string}
So, I tried to initialized a one collector for all gorutines, and to initialize one collector for each gorutine. The result is the same!
This my netstat output (there are 4 gorutines for simplicity)
![screenshot from 2018-10-31 14-06-14](https://user-images.githubusercontent.com/27097483/47774091-41eefb00-dd16-11e8-87b0-d1c4e09cc6dd.png)

if I start not 80 gorutines, but 80 separate main processes, it turns out to pump out 16,000 blocks per minute, why so
this is my netstat output in this case (there are 4 ./main.go is started for simplicity)
![screenshot from 2018-10-31 14-09-50](https://user-images.githubusercontent.com/27097483/47774467-51bb0f00-dd17-11e8-9748-0bc2c6ff74e7.png)

How can I establish a individual connection for each gorutine, and get result such on the second image...?

**Comment by mattn** [comment]
please put minimal example code to reproduce.

**Comment by agnivade** [comment]
> So, I tried to initialized a one collector for all gorutines, and to initialize one collector for each gorutine. 

Yes, because the `http.Client` is still shared across multiple goroutines.

I don't see this as a Go issue. Most probably you need a custom `Transport` with proper `MaxIdleConnsPerHost` and other settings.

I would request you to reach out to the [forums](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.

**Comment by mvdan** [comment]
Let's take this to a forum like Agniva says, and return to the issue tracker once there's a specific bug or suggestion. And next time, please provide a small program to reproduce the problem.
