### ISSUE TITLE
n,_:=time.Parse("2006-01-02 15:04:05","2018-10-31 15:04:05") 	fmt.Println(n.AddDate(0,  1, 0))

### ISSUE THREAD

**Issue by xiaolongn100** [golang/go#28504]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8  1.11

### Does this issue reproduce with the latest release?
2018.10.31

### What operating system and processor architecture are you using (`go env`)?
linux windows

### What did you do?

n,_:=time.Parse("2006-01-02 15:04:05","2018-10-31 15:04:05")
	fmt.Println(n.AddDate(0,  1, 0))  //2018-12-01 15:04:05 +0000 UTC

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by mvdan** [comment]
Read the docs.

> AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31.
