### ISSUE TITLE
unrecognized import path "math/bits" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by wa1one** [golang/go#28507]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version 1.11.1

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
MacOS Mojave 10.14.1
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vladimirkovalcuk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vladimirkovalcuk/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jf/xk5v_2zn0vg3kj22d_920j_m0000gn/T/go-build844675261=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

ran command

make deps

`go get \
		golang.org/x/crypto/ripemd160 \
		golang.org/x/crypto/sha3 \
		github.com/gogo/protobuf/jsonpb \
		github.com/gogo/protobuf/proto \
		google.golang.org/grpc \
		github.com/spf13/cobra \
		github.com/hashicorp/go-plugin \
		github.com/stretchr/testify/assert \
		github.com/go-kit/kit/log \
		github.com/pkg/errors \
		github.com/miguelmota/go-solidity-sha3`

### What did you expect to see?
successful go get

### What did you see instead?
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

**Comment by ianlancetaylor** [comment]
Was that the only thing printed?  I hope not.  Please show us everything that was printed.  Thanks.

**Comment by wa1one** [comment]
Output of the command:
`package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)`

**Comment by ianlancetaylor** [comment]
Are you completely certain that you are using Go 1.11.1?  That is an error message I would expect to see with Go 1.8 or earlier.

**Comment by wa1one** [comment]
`vladimirkovalcuk@Vladimirs-MacBook-Pro:~/go/src/github.com/loomnetwork/go-loom$ go version
go version go1.11.1 darwin/amd64`

How to check version?

**Comment by ianlancetaylor** [comment]
You suggested that you ran `make deps` to produce this error message.  Can you check that that command is running Go 1.11.1?

I really don't see how this could possibly happen using Go 1.11.1.

**Comment by wa1one** [comment]
Ok, sorry, there was second homebrew go version 1.8.1 :(
