### ISSUE TITLE
Tests in main package don't work with GO111MODULE=on

### ISSUE THREAD

**Issue by onitake** [golang/go#28514]
### What version of Go are you using (`go version`)?
```
go version go1.11.1 linux/amd64
```
After initially encountering the issue, I reproduced it with the official golang:1.11-alpine Docker container.

### Does this issue reproduce with the latest release?
Yes, it is Go 1.11 specific.
I didn't test with a development build directly from the Git tree.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build838179380=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
The following is a minimal test case that doesn't actually use any external modules.

It fails in exactly the same way if the source file imports other modules that are not part of the Go distribution. It is also not relevant if `go build` or `go tidy` were ran beforehand.

Create `x_test.go` with the following contents, in a directory outside the GOPATH:
```go
package main
import "testing"
func TestMain(t *testing.T) {
        t.Log("Test successful")
}
```
Create a placeholder `go.mod` file:
```go
module main
```
Run the test without Go module support:
```bash
$ GO111MODULE=off go test
PASS
ok      _/root/test     0.001s
```
Run the test with Go 1.11 module support:
```
$ GO111MODULE=on go test
# main.test
/tmp/go-build011410304/b001/_testmain.go:12:2: cannot import "main"
FAIL    main [build failed]
```

### What did you expect to see?
That the test would succeed in both cases, with or without module support.

### What did you see instead?
The compiler complains about a missing main package when GO111MODULE=on is set:
```
# main.test
/tmp/go-build011410304/b001/_testmain.go:12:2: cannot import "main"
FAIL    main [build failed]
```

**Comment by bcmills** [comment]
When you run the test using `GO111MODULE=off`, the effective import path is the relative path from your `GOPATH` root. (I'm not sure what the effective import path is outside of `GOPATH`, but I'm guessing it's not just `main`.)

When you run the test using `GO111MODULE=on`, the effective import path is whatever the `go.mod` file declares it to be.

So, what happens if your `go.mod` file declares a real module path rather than `module main`?

**Comment by bcmills** [comment]
The module path is a prefix of the package import path. The first component of the module path should always be a name that you control — typically a domain name.

You don't have to reproduce the whole `GOPATH` to run tests in module mode. All you need is the module that you want to build, with a `go.mod` file declaring the correct module path. (The final name of the package is `<module path>/<relative path within module>`.)

**Comment by onitake** [comment]
So you're saying I should put my tests on the `$GOPATH/my.package/prefix`, then run `go test my.package/prefix`, and it will work even though the package is called "main"?
Ok, I can try that.

But still: I don't see why it shouldn't work otherwise. It did without enabling Go module handing, and `go build` works fine too.

**Comment by onitake** [comment]
After experimenting some more, I don't think your suggestion is the right solution.
As stated before, I'm building an application where all source code is in the main package, as are tests related to the application. Putting a prefix in front of the package makes no sense.
I also tested a few other go tools, and the only one that doesn't support this use case is `go test`.

So: Instead of discussing on how to use go tools correctly, could we focus on why `go test` tries to import the main package from an invalid location?

**Comment by onitake** [comment]
Ok, it seems I simply misunderstood what you meant and what the documentation said.
I was under the impression that the module would have the same name as the package.

The error went away when I replaced the package name (`main`) in `go.mod` with the module path (`my/project`).
Now I can build and test out-of-tree without problems.
It's just a bit confusing that every other go tool except `go test` works with the incorrect module path.

Anyway, thanks for the help!

**Comment by grantbow** [comment]
Thank you for the questions and explanations above. I have been struggling with this same problem. I forked a project on github. I am using go.mod files to adjust the submodule names for the fork I'm editing.

I found a bunch of older explanations that all pointed to using 'module main' in main_test.go. When using GO111MODULE=on this changes. For me I could leave main.go as 'module main' without a problem. Then in main_test.go I changed from 'module main' to 'module github.com/grantbow/<pkg>/main' and it worked!

So `go build` will find the module path (github.com/grantbow/<pkg> for me) and module name (main for me) and join them with a /. However `go test` does not? We need to specify the module differently in main.go and main_test.go? Isn't that a bug?

**Comment by grantbow** [comment]
Thank you for the questions and explanations above. I have been struggling with this same problem. I forked a project on github. I am using go.mod files to adjust the submodule names for the fork I'm editing.

I found a bunch of older explanations that all pointed to using 'module main' in in_test.go and main.go. When using GO111MODULE=on this changes. For me I could leave main.go and main_test.go as 'module main' without a problem. `go build` was fine. `go test` failed. Then in go.mod I had to change from 'module main' to 'module github.com/grantbow/<project>/main' and it worked!

So with go.mod set to `module main` go build will not find the module path (github.com/grantbow/ for me) and module name (main for me) and join them with a / like it does with main.go and main_test.go. So `go test` doesn't find it's own location from go.mod? We need to specify the module differently in go.mod from main.go and main_test.go? Isn't that a bug?

**Comment by onitake** [comment]
Not a bug. If anything, the documentation is a bit misleading if you don't pay close attention.

You need to take into account that **package name** and **module name** are two different things in Go. That's not a new thing in 1.11, it has been like this forever.

What you import is the **module**, but what you use as namespace is the **package**.
For example, you would
```go
import "net/http"
```
but
```go
http.ListenAndServe(":80", nil)
```
Mind that the import namespace can be changed at import time, so the package name would only provide a default if nothing is specified.

In `go.mod`, you would name the **module**, while the `package` statements in each source file would name the **package**.

**Comment by bcmills** [comment]
> You need to take into account that package name and module name are two different things in Go.
> […]
> What you import is the module, but what you use as namespace is the package.

@onitake, to be clear, there are actually *three* things involved here: the **module path**, the **package import path**, and the **package name**.

The module path is a prefix of the package import path, for every package in that module.

The package name is *conventionally* the last component of the package import path, possibly omitting a `/vN` suffix, but *can* be any arbitrary identifier. (See also proposal #29036.)

**Comment by grantbow** [comment]
It still feels something is wrong or I am missing something. If `go build` works then `go test` should work. Why should the two tools require something different? Which part of what documentation is a bit misleading and needs a close reading?
