### ISSUE TITLE
go/doc: example for syscall/js.NewCallback doesn't run

### ISSUE THREAD

**Issue by opennota** [golang/go#28526]
Following https://github.com/golang/go/issues/28492: the example for `NewCallback` (https://golang.org/pkg/syscall/js/#NewCallback) has the Run button but doesn't run, because

`prog.go:5:2: build constraints exclude all Go files in /usr/local/go/src/syscall/js`

**Comment by neelance** [comment]
Did you set `GOOS=js` and `GOARCH=wasm`?

**Comment by opennota** [comment]
@neelance Nope. I don't have access to golang.org (which is presumably runs the examples).

https://i.imgur.com/SAOCopY.png

**Comment by neelance** [comment]
Oh sorry, I jumped to conclusions without reading the issue closely enough (there have been other issues caused by missing `GOOS` and `GOARCH`). Yes, this example shouldn't have a "Run" button.

**Comment by dmitshur** [comment]
I noticed something in [`os/exec`](https://godoc.org/os/exec) package documentation related to this issue. Namely, it includes the following paragraph in the package documentation:

> Note that the examples in this package assume a Unix system. They may not run on Windows, and they do not run in the Go Playground used by golang.org and godoc.org.

It seems `os/exec` went with another way of handling a similar problem.

/cc @neelance @bradfitz
