### ISSUE TITLE
doc: contribute: sending a change gerrit: incorrect language

### ISSUE THREAD

**Issue by tkivisik** [golang/go#28528]
### What did you do and see?
https://golang.org/doc/contribute.html#sending_a_change_gerrit

There is a sentence:

> It's different but powerful and familiarity with help you understand the flow.

### What did you expect to see?

> It's different but powerful and familiarity with it will help you understand the flow.

**Comment by tklauser** [comment]
Fixed by 21d2e15ee1bed44a7a1b8f775aff4a57cae9533a (https://golang.org/cl/142879). The issue was not referenced in the commit message, thus closing manually. Thanks.
