### ISSUE TITLE
database/sql: Documetation: Connection Pool with reverse proxy

### ISSUE THREAD

**Issue by pjebs** [golang/go#28524]
I have created a connection pool for the purposes of multiple read replicas.

I have HAProxy being used as a reverse proxy which provides a host url which links to multiple host urls (randomly allocated).

When I create the connection pool, If I type in the host name to be the HAProxys host name, will there be any weird side-effects in how the connection pool works.

In common connetion pools such as in Java, this approach works fine.

**Comment by kardianos** [comment]
I don't think there will be a problem. If it works in Java it will probably work here.
