### ISSUE TITLE
website: all examples on tip.golang.org cannot be run

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#28536]
I expected to be able to run examples on tip.golang.org. But all of them are not runnable.

I'd like to see how changes in `/x/tools/godoc` and in `go/doc` affect the website before deploying (releasing) new version of go.

**Comment by bradfitz** [comment]
I approved & submitted the CL, but this also needs to be deployed.

@dmitshur?

**Comment by agnivade** [comment]
As I understand, tip gets auto-redeployed every few minutes. So playground is already enabled now. Is there anything pending here ?

**Comment by ysmolsky** [comment]
I created this when I was fixing this example https://tip.golang.org/pkg/image/png/#example_Decode
Example can be played and fix works, so I consider this done too.
