### ISSUE TITLE
x/net/icmp: wrong size for if-index in InterfaceIdent object

### ISSUE THREAD

**Issue by uhei** [golang/go#28530]
### What version of Go are you using (`go version`)?
go1.11.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
Build a ICMP ExtendedEchoRequest message with typeInterfaceByIndex.

### What did you expect to see?
if-index field being 4 bytes long (as defined in RFC7223 Sec 3 and RFC8335 Sec 2.1)

### What did you see instead?
if-index field with 8 bytes

Will open a PR to fix this issue.

**Comment by mikioh** [comment]
@uhei,

> if-index field being 4 bytes long (as defined in RFC7223 Sec 3 and RFC8335 Sec 2.1)

IIRC, the conclusion is as described in RFC 8335:
```
If the Interface Identification Object identifies the probed interface by index, the length is equal to 8 and the payload contains the if-index [RFC7223].
```
The protocol provides enough space for containing any representation of interface-index, practically from 32-bit to 64-bit integer for both classical and modern network control and management stuff.

**Comment by mikioh** [comment]
Oh, sorry, you are correct. I've been misunderstood the format w/ mixing another discussion. Thanks for sending the fix.
