### ISSUE TITLE
cmd/internal/obj/arm64: wrong encoding for instruction BICW

### ISSUE THREAD

**Issue by benshi001** [golang/go#28548]
"BICW $0x3ff00000, R2" is expected to encoded to 

	0x12025442:   "ANDW $0xc00fffff, R2"

but actual result is

	0x1202d442:   "ANDW $0xcfcfcfcf, R2"

**Comment by benshi001** [comment]
cc @zhangfannie

**Comment by zhangfannie** [comment]
@benshi001  I will look into it.
