### ISSUE TITLE
os: TestRemoveDevNull fails on openbsd and netbsd builders

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#28549]
I submitted https://go-review.googlesource.com/c/go/+/145220 and it broke all openbsd and netbsd builders. From https://build.golang.org/log/0f1815b49113f97b32f8858e590fd50701fc6eb1
```
--- FAIL: TestRemoveDevNull (0.00s)
    build_test.go:29: Lstat(/dev/null).Mode().IsRegular() = true; expected false
    build_test.go:34: mayberemovefile(/dev/null) did remove it; oops
FAIL
FAIL	cmd/go/internal/work	0.061s
```

But CL 145220 did not changed TestRemoveDevNull or code that it calls. I do not even know how to debug this. Perhaps my new test_devnull.txt somehow interfers with TestRemoveDevNull.

I am looking for help. If nothing else I will skip the test or revert CL 145220 tomorrow.

Thank you.

Alex

**Comment by ianlancetaylor** [comment]
It's a bug in `go test -o /dev/null -c` when run as root.

**Comment by alexbrainman** [comment]
> It's a bug in `go test -o /dev/null -c`

Thank you for fixing that.

In my sleep, I remembered we had some code to handle os.DevNull in `go build`, but not in `go test`. Now we have 2 copies of that code.

Alex
