### ISSUE TITLE
cmd/go: go get fails with git version 1.7.1 on CentOS 6.9 

### ISSUE THREAD

**Issue by adam8157** [golang/go#28550]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 linux/amd64
</pre>

### What did you do?

Just `go get` something with the Modules mode

### What happened?

```
go: unknown revision xxxxxxxx
go: error loading module requirements
```

### Root cause

git command below is what `go get -x` shows.

```
$ git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' xxxxxxxx
Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]

$ git version
git version 1.7.1

$ cat /etc/*issue
CentOS release 6.9 (Final)
```

**Comment by agnivade** [comment]
Actually, we added the `-c log.showsignature=false` to support git versions lower than 2.10. https://github.com/golang/go/commit/90066bf06a9b10b3b222a289934b93723bb788d6

Most recent systems have 2.7.4. Git 1.7 seems to have been released on 2010. Not sure how far back are we willing to go to support git versions. Perhaps it goes back to @bcmills' comment [here](https://github.com/golang/go/issues/26653#issuecomment-409601947) to explicitly specify a minimum git version.

/cc @bcmills @rsc

**Comment by thepudds** [comment]
#26746 tracks defining a minimum support version of git (or perhaps instead a set of supported distro versions).

One comment from there:
> The table at https://en.wikipedia.org/wiki/Git#Release says that Git 2.12 and older are themselves no longer maintained.

1.7 is pretty old.

@adam8157 are you able to upgrade your version of git?

**Comment by rasky** [comment]
FWIW, `git -c` was added in git 1.7.2:
https://github.com/git/git/commit/8b1fa778676ae94f7a6d4113fa90947b548154dd

**Comment by bcmills** [comment]
According to the table at https://wiki.centos.org/About/Product, CentOS6 is currently on version 6.10. Any idea whether that comes with a newer Git?

**Comment by ianlancetaylor** [comment]
Looks like it is still git 1.7.1.

Since CentOS is intended to be long term stable, they are unlikely to update anything except to fix bugs.,

**Comment by adam8157** [comment]
This happens on my testing env which is the same as my deployment env, it's OK to upgrade. However, I guess CentOS/RHEL 6 is still a big player, especially as the production OS, in the Linux world.

**Comment by bcmills** [comment]
As a workaround, note that you can set `GOPROXY=https://proxy.golang.org` to fetch using HTTPS instead of Git.

**Comment by seankhliao** [comment]
I believe this can be closed with CentOS 6 having reached EOL on 2020-11-30

Current policy is at https://github.com/golang/go/issues/26746#issuecomment-1169102174
