### ISSUE TITLE
Cannot find module providing package

### ISSUE THREAD

**Issue by alwindoss** [golang/go#28552]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alwin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/devsandbox/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/alwin/Programming/golang/pull/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build274013903=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I use the golang aws sdk [http://github.com/aws/aws-sdk-go](url)
I have a piece of code that uses the following import paths

```
import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/awserr"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/aws/service/dynamodb"
)
```
However, when I build my project, which is outside the GOPATH I get the following error
```
$ go build
go: finding github.com/aws/aws-sdk-go/aws/service/dynamodb latest
go: finding github.com/aws/aws-sdk-go/aws/service latest
go: finding github.com/aws/aws-sdk-go/aws latest
pkg/dao/ddb.go:9:2: unknown import path "github.com/aws/aws-sdk-go/aws/service/dynamodb": cannot find module providing package github.com/aws/aws-sdk-go/aws/service/dynamodb
```

### What did you expect to see?
I expected the code to build as expected

### What did you see instead?
I saw the following error and the code does not build
```
go: finding github.com/aws/aws-sdk-go/aws/service/dynamodb latest
go: finding github.com/aws/aws-sdk-go/aws/service latest
go: finding github.com/aws/aws-sdk-go/aws latest
pkg/dao/ddb.go:9:2: unknown import path "github.com/aws/aws-sdk-go/aws/service/dynamodb": cannot find module providing package github.com/aws/aws-sdk-go/aws/service/dynamodb
```

#### Contents of the go.mod file
```
module github.<enterprise>.com/<organization>/pull

require (
	github.com/aws/aws-lambda-go v1.6.0
	github.com/aws/aws-sdk-go v1.15.67
	github.com/buger/jsonparser v0.0.0-20181023193515-52c6e1462ebd
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af // indirect
	github.com/lib/pq v1.0.0
	github.com/magefile/mage v1.7.1
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/stretchr/testify v1.2.2 // indirect
)
```

**Comment by agnivade** [comment]
Hi @alwindoss, the error is clear enough - 

The path should be - "github.com/aws/aws-sdk-go/service/dynamodb".

You have - "github.com/aws/aws-sdk-go/aws/service/dynamodb"

https://godoc.org/github.com/aws/aws-sdk-go/service/dynamodb

I will close the issue now. Please feel free to comment if the issue persists. Thank you.
