### ISSUE TITLE
x/build: trybot-result-changers Gerrit group doesn't allow removing TryBot-Result votes

### ISSUE THREAD

**Issue by dmitshur** [golang/go#28565]
I am a member of this group, yet I can't remove TryBot-Result votes right now. E.g.:

<img width=297 src="https://user-images.githubusercontent.com/1924134/47936453-07bb6000-deb4-11e8-9e7c-8b5a9d5bad26.png">

This is needed to be able to force a trybot re-run.

**Comment by dmitshur** [comment]
I think @andybons has resolved the issue of some of us not being able to remove TryBot-Result votes recently, see https://github.com/golang/go/issues/29285#issuecomment-454962865.

Do we still need the trybot-result-changers Gerrit group for anything? I don't believe @andybons's solution used it.

I'll leave this issue open to decide what to do with trybot-result-changers group, but otherwise I believe this is resolved now.

**Comment by FiloSottile** [comment]
@dmitshur Is this still not working as intended?

**Comment by dmitshur** [comment]
The current status of the issue is:

> I'll leave this issue open to decide what to do with trybot-result-changers group, but otherwise I believe this is resolved now.

If we don't need an open issue to track that task, this can be closed.
