### ISSUE TITLE
os: return an error from UserHomeDir to match UserCacheDir

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#28562]
`os.UserHomeDir` will be new in Go 1.12, added in https://golang.org/cl/139418 with the signature `func UserHomeDir() string`.  The existing function `UserCacheDir` has the signature `func UserCacheDir() (string, error)`.  Should we change `UserHomeDir` to return an error as `UserCacheDir` does?

**Comment by andybons** [comment]
My vote is yes. Originally `UserCacheDir` returned a string but an empty string could lead to bugs that are hard to track down. I'm happy to send a CL if that's what we'd like to do.

**Comment by bradfitz** [comment]
I think an error makes its use kinda tedious.

I'd prefer to just return "/" if the env is unset and let things fail with a permission error later.

But I don't object if everybody else prefers an error.

**Comment by stapelberg** [comment]
One benefit of not returning an error: that allows for flag definitions to easily default to a location relative to $HOME:
```go
var configPath = flag.String("config",
  filepath.Join(os.UserHomeDir(), ".config", "i3"),
  "path to write configuration file to")
```

Of course, the above expression is not portable and should probably be replaced by os.UserConfigDir, which should respect $XDG_CONFIG_DIR on Linux? :)

Aside from that, I agree with @bradfitz in that $HOME is so rarely unset that not caring much about that case is an okay trade-off, and users who work in such strange environments will easily be able to make the connection between the error and the lack of a $HOME variable.

What about returning "$HOME is unset"? That way, the error message would be “plumbed through”.

**Comment by andybons** [comment]
> What about returning "$HOME is unset"? That way, the error message would be “plumbed through”.
At that point we should just return an error in my opinion.

That said, I don't know enough about the circumstances of when $HOME would not be set (and whether this is a valid error condition). My vote was for API consistency going forward.

**Comment by rsc** [comment]
Discussed with @bradfitz and @andybons. The missing error was mainly for convenience but hopefully the work on error handling will address that instead of losing the ability in the API to tell whether it succeeded.
