### ISSUE TITLE
unexpected padding byte when convert from net.IP to []byte

### ISSUE THREAD

**Issue by leslie-qiwa** [golang/go#28571]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/go/src/github.com/pensando/test-infra/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build092800278=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/gtcQZajAmBN

package main

import (
	"fmt"
	"net"
)

func main() {
	myIP, _, _ := net.ParseCIDR("127.0.0.1/24")
	fmt.Printf("%v\n", []byte(myIP))
}

### What did you expect to see?

[127 0 0 1]

### What did you see instead?

[0 0 0 0 0 0 0 0 0 0 255 255 127 0 0 1]

**Comment by dominikh** [comment]
From the documentation:

> Note that in this documentation, referring to an IP address as an IPv4 address or an IPv6 address is a semantic property of the address, not just the length of the byte slice: a 16-byte slice can still be an IPv4 address. 

In particular, you're seeing an IPv4 address embedded in an IPv6 address.

If you want a 4-byte representation, use the To4 method.

This is working as intended.
