### ISSUE TITLE
cmd/compile: Compiler crash

### ISSUE THREAD

**Issue by liuxingbaoyu** [golang/go#28579]
### What version of Go are you using (`go version`)?

go version go1.11 windows/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows x64

### What did you do?

[https://play.golang.org/p/VibGqakQ-8v](https://play.golang.org/p/VibGqakQ-8v)

### What did you expect to see?

Some error tips

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xb7c7ee]

goroutine 1 [running]:
cmd/compile/internal/gc.typecheck1(0xc00032e080, 0x1, 0xca41c5)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:1270 +0x3ece
cmd/compile/internal/gc.typecheck(0xc00032e080, 0x1, 0x3)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:238 +0x6ad
cmd/compile/internal/gc.typecheckslice(0xc00000c588, 0x1, 0x1, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:68 +0x50
cmd/compile/internal/gc.Main(0xcc2180)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:518 +0x2059
main.main()
	/usr/local/go/src/cmd/compile/main.go:51 +0x96
```

**Comment by ALTree** [comment]
Thanks for the report.

This is fixed on tip and the fix was backported in 1.11.2 (#27973). Please upgrade to 1.11.2. Closing here, since there's nothing more to do.
