### ISSUE TITLE
x/build: trybots testing subrepos against previous Go releases UI improvements

### ISSUE THREAD

**Issue by dmitshur** [golang/go#28580]
This is a follow up to #17626. The functionality is there, but some of the UI can be tweaked to be better.

Specifically, see these comments:

- [ ] https://github.com/golang/go/issues/17626#issuecomment-435615887
- [ ] https://github.com/golang/go/issues/17626#issuecomment-435616051

/cc @bradfitz

**Comment by bradfitz** [comment]
Deployed.
