### ISSUE TITLE
x/build: reconsider NaCL builders on subrepos

### ISSUE THREAD

**Issue by dmitshur** [golang/go#28582]
I'm not seeing an issue about this, so filing one to track this.

NaCL builders got added to subrepo trybots as part of changes in [CL 145157](https://golang.org/cl/145157), which got deployed a few days ago. Brad noticed it earlier and told me:

> also I need to remove nacl trybots from x/net etc
> that was a mistake I think

They seem to be failing on many x/tools trybot runs, e.g., https://go-review.googlesource.com/c/tools/+/147317#message-0b65ea2ab17f9e28f0519d84b8bb646345441b6a, making the real failures harder to see.

Adding NeedsDecision because I'm not 100% confident what's the best resolution here, and looking for confirmation.

/cc @bradfitz @heschik

**Comment by bradfitz** [comment]
Decision: don't run nacl for subrepos. There's no mechanism to package their testdata files up anyway.

**Comment by bradfitz** [comment]
Deployed.

Farmer was:

> 21h27m35s. Version 906dcfd58886df4b3156fd9fa9d51f9767bd66f6.

Now:

> Uptime 1s. Version 9f6998b87f0ce9198930a0a7eb5e5b86ae8b7802
