### ISSUE TITLE
unmarshal json

### ISSUE THREAD

**Issue by FatChou** [golang/go#28597]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/popeye/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/popeye/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/92/f7tk0g155dd3_dgx542w8m9c0000gn/T/go-build288582485=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I have a config.pb.go file that is like this:

```go
type Config struct {
	Inbound []*InboundHandlerConfig `protobuf:"bytes,1,rep,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound []*OutboundHandlerConfig `protobuf:"bytes,2,rep,name=outbound,proto3" json:"outbound,omitempty"`
	App []*serial.TypedMessage `protobuf:"bytes,4,rep,name=app,proto3" json:"app,omitempty"`
	Transport *transport.Config `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	Extension            []*serial.TypedMessage `protobuf:"bytes,6,rep,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
```

I use gomobile build --target=ios ... After compiling into objc file, use 

```
Config *config = [[Config alloc] init];
NSError *error;
[config XXX_Unmarshal:jsonData error:&error];//jsonData from Bundle file
```

Then, the following error happens:
1.Error Domain=go Code=1 "proto: can't skip unknown wire type 7"
2.Error Domain=go Code=1 "unexpected EOF"

```
gomobile version:
gomobile version +a27dd33 Fri Oct 26 06:21:14 2018 +0000 (android,ios); androidSDK=
```

### What did you expect to see?

How do I use gomobile to compile a class into objc? Is this my jsonfile incorrect?

**Comment by ianlancetaylor** [comment]
Unfortunately I don't understand the question.  You seem to be mixing protobuf code and JSON code.

In general we do not use the issue tracker for questions about how to use Go.  It is likely that you will get a better answer in a forum; see https://golang.org/wiki/Questions .

**Comment by dsnet** [comment]
The generated messages from protobufs do not work well with the `encoding/json` package. Instead, there is a separate [`jsonpb`](https://godoc.org/github.com/golang/protobuf/jsonpb) to perform JSON serialization for protobufs. That said, the error you are seeing seems to indicate that you are performing binary unmarshaling on the JSON input.

Feel free to re-file on the [golang/protobuf tracker](https://github.com/golang/protobuf/issues) if the problem persists and I'd be happy to help you there.
