### ISSUE TITLE
time: RFC3339Nano returns different results of different OS.

### ISSUE THREAD

**Issue by 3timeslazy** [golang/go#28598]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
Mac OS:
- GOARCH="amd64"
- GOOS="darwin"

Linux:
- GOARCH="amd64"
- GOOS="linux"
```
### What did you do?

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	t := time.Date(2018, time.November, 5, 0, 54, 15, 5125, time.Local)
	fmt.Println(t.Format(time.RFC3339Nano))
}
```

### What did you expect to see?
I expect to see the same result on all OS. Ex. ```2018-11-05T00:54:15.000005125+03:00```

### What did you see instead?
On Mac OS: ```2018-11-05T00:54:15.000005125+03:00```
On Linux: ```2018-11-05T00:54:15.000005125Z```

**Comment by ianlancetaylor** [comment]
The Go standard library just takes the system's setting for `time.Local`.  Your MacOS system is in +03:00, your GNU/Linux system is in UTC (or more likely simply unconfigured).  This isn't something we can fix in Go.
