### ISSUE TITLE
$GOPATH value not being recognized during build

### ISSUE THREAD

**Issue by andrewinfosec** [golang/go#28593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

I believe go version go1.11.2 darwin/amd64 is the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/Google Drive/programming/golang/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hb/9lrqhggd35qcrfsgfvgc4gcm0000gn/T/go-build297024427=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

$ echo $GOPATH
/Users/me/Google Drive/programming/golang/workspace
$ go run foo.go 
foo.go:4:2: cannot find package "github.com/google/gopacket" in any of:
	/usr/local/Cellar/go/1.11.2/libexec/src/github.com/google/gopacket (from $GOROOT)
	/Users/me/go/src/github.com/google/gopacket (from $GOPATH)

### What did you expect to see?

A successful build.

### What did you see instead?

$GOPATH is set but is not being recognized. $GOPATH is defaulting to /Users/me/go even though it has a set value.

**Comment by bradfitz** [comment]
What does `diskutil  list` say? Does it work if you use a path that's not under `Google Drive`? Does it work for a path not containing spaces?
