### ISSUE TITLE
gccgo: etcd reportedly doesn't compile on gccgo

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28601]
Pulling this into its own issue from https://github.com/golang/go/issues/19074#issuecomment-435929915 where @glaubitz says:

> gccgo doesn't build all packages that golang builds. I know it's supposed to be compatible, but it isn't. I can provide a list of Debian packages which don't build.
>
> See, for example, etcd: https://buildd.debian.org/status/fetch.php?pkg=etcd&arch=ppc64&ver=3.2.18%2Bdfsg-1&stamp=1539989343&raw=0
>
> Fails with:

```
# github.com/coreos/etcd/pkg/cpuutil
src/github.com/coreos/etcd/pkg/cpuutil/endian.go:31:13: error: array bound is not constant
  if v := (*[intWidth]byte)(unsafe.Pointer(&i)); v[0] == 0 {
             ^
src/github.com/coreos/etcd/pkg/cpuutil/endian.go:31:51: error: array index out of bounds
  if v := (*[intWidth]byte)(unsafe.Pointer(&i)); v[0] == 0 {
                                                   ^
```

**Comment by ianlancetaylor** [comment]
This is now fixed on GCC 7 branch, GCC 8 branch, and tip.  Sorry for the trouble.

@glaubitz: Please do report cases where the gc toolchain works and gccgo does not.  That's the only way we will know to fix the problems.  Thanks.

**Comment by glaubitz** [comment]
> This is now fixed on GCC 7 branch, GCC 8 branch, and tip. Sorry for the trouble.

Thanks. That was a very quick fix.

> Please do report cases where the gc toolchain works and gccgo does not. That's the only way we will know to fix the problems. Thanks.

This has been on my TODO list forever. I will try to take care of this this week. There are a couple of packages left that have issues.

**Comment by glaubitz** [comment]
@ianlancetaylor There are a couple of packages which actually build but where the testsuite fails:

> https://buildd.debian.org/status/fetch.php?pkg=golang-github-ugorji-go-codec&arch=ppc64&ver=1.1.1-1&stamp=1539998621&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=golang-github-spf13-cobra&arch=ppc64&ver=0.0.3-1&stamp=1539989839&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=golang-golang-x-tools&arch=ppc64&ver=1%3A0.0%7Egit20180501.d3e4ceb5%2Bds-1&stamp=1539989961&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=golint&arch=ppc64&ver=0.0%2Bgit20161013.3390df4-2&stamp=1539990009&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=govendor&arch=ppc64&ver=1.0.9%2Bds1-1&stamp=1539990039&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=ppc64&ver=0.47.1-2&stamp=1539990488&raw=0

**Comment by ianlancetaylor** [comment]
@glaubitz Do you know if they fail with gccgo on amd64 also, or also on PPC64?  Is there a way that I could find out?

There are of course various possible reasons for this to happen, ranging from a gccgo bug to a non-portable test.  I guess we'll just have to examine each one to see what is going on.

**Comment by glaubitz** [comment]
@ianlancetaylor Tested all these packages on amd64 with gccgo-8 instead of gc. They all fail the testsuite with gccgo but pass it with gc.

**Comment by bradfitz** [comment]
@glaubitz, feel free to file as many new bugs as you'd like. But reusing this one risks it being ignored, because our dashboard don't track closed issues.

**Comment by glaubitz** [comment]
> @glaubitz, feel free to file as many new bugs as you'd like. But reusing this one risks it being ignored, because our dashboard don't track closed issues.
> 
Sure, I‘m aware of that. This was just a quick check and you see there is actually a noticable amount of build issues with gccgo.

I have requested Debian‘s Go packaging team now to fix all their packages which have a hard build dependency to switch that to „golang-any“ such that these packages can attempt to build on the gccgo-only architectures. I expect around 50-60 packages which won’t build with gccgo out that. We‘ll see.

**Comment by bradfitz** [comment]
>  I expect around 50-60 packages which won’t build with gccgo out that. We‘ll see.

We look forward to the reports.

When you do report, though, be sure to note exactly what failed: actually building (e.g. compilation failures) vs test failures. The latter is often due to things like tests assuming certain gc-specific behaviors, like naming of symbols in stack frames. In any case, I assume you'll post links to failure logs, so it should be obvious.
