### ISSUE TITLE
path/filepath: always validate full Glob patterns

### ISSUE THREAD

**Issue by fstab** [golang/go#28614]
The functions `filepath.Match(pattern, name)` and `path.Match(pattern, name)` return `ErrBadPattern` if the pattern is invalid, but due to lazy evaluation the error may or may not occur depending on what you match.

Example:

```golang
_, err := filepath.Match("a[", "a") // err is nil
_, err := filepath.Match("a[", "abc") // err is "syntax error in pattern"
```

As patterns are often user input, it would be handy to be able to validate the pattern. If the validation is successful, it should be guaranteed that `filepath.Match()` will not return an error.

I created a PR for this [here](https://go-review.googlesource.com/c/go/+/143477) and was asked to open a proposal issue first.

Other programming languages seem to either not validate the pattern at all (like Python's `glob.glob('a[')`), or always validate the pattern (like Java's `FileSystems.getDefault().getPathMatcher("glob: a["))`). I couldn't find an example where validation depends on what name is matched.

**Comment by opennota** [comment]
An alternative: make Match evaluate pattern non-lazily. That way there would be no risk that the implementations will diverge and Match will return an error for pattern which passes IsPatternValid.

**Comment by andybons** [comment]
Per discussion with @golang/proposal-review, we believe that the `Match` function should evaluate non-lazily (@opennota's suggestion) so that one can use `Match` to validate a Glob without adding a new function.

**Comment by rillig** [comment]
@andybons I certainly like that the current implementation is as efficient as possible. I just miss the option to validate a pattern. Maybe calling `path.Match(pattern, "")` could be a special case that evaluates the complete pattern. This string is unlikely to be used in normal situations, therefore it shouldn't hurt much when the whole pattern is analyzed.

Alternatively there could be `path.Compile(pattern)` that just compiles a path expression. This would also allow for common special cases to be matched much faster (prefix, suffix), like I did it in [a project of mine](https://github.com/rillig/pkglint/blob/19a1f435f36c6d7ec5fae343be9bc6b5daac508c/util.go#L1221) for the subset of path patterns that I really needed.

**Comment by jmartin82** [comment]
Hi, I've been checking this issue and I would like to work on it if no one else is doing it right now as my first contribution.

I see two possible implementations using the same functions.

1. Adding some extra checks to the current implementation, keeping the laziness but ensuring a consistent repose in case of an invalid pattern (almost no overhead over the current implementation).

2. Adding a guard clause to check the whole pattern validity straight away (with a small overhead over the current implementation)

As per your previous conversation, you seem more inclined to the second option, right?

Thanks,

**Comment by ianlancetaylor** [comment]
We want to make sure that implementation is simple, efficient, and always detects an invalid pattern.  I would tend to think that the second option you list is likely to be the better approach, but I think we're open to any implementation that meets those goals as best as possible.  Thanks.

**Comment by jmartin82** [comment]
@ianlancetaylor  I've created a PR (https://go-review.googlesource.com/c/go/+/186937) with a possible implementation for `path.Match(pattern, name)` function (it's a mix between option 1 and 2 😄  ) let me know what do you think about, before applying the same solution to the `filepath.Match`

Thanks,
