### ISSUE TITLE
net/http/httptest: serve flag not read when not running as a test; remove flag in that case?

### ISSUE THREAD

**Issue by pwfcurry** [golang/go#28619]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<user>/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/<user>/go"
GORACE=""
GOROOT="/usr/local/Cellar/go@1.10/1.10.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.10/1.10.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wj/3cmxv_m511z7cz93jw81kkv00000gp/T/go-build676852346=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go main.go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
)

func main() {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	fmt.Println(server.URL)
}
```

```
go run main.go -httptest.server=localhost:12345
```

The URL printed is `127.0.0.1:random port`.

However, importing `"flag"` and running `flag.Parse()` before creating the server will ensure flag is read as expected.

Surely the `httptest` server should ensure `.Parse()` has run (via `.Parsed()`, & run if not)?

### What did you expect to see?

URL specified by flag should be used.

```
localhost:12345
```

### What did you see instead?

Random port is used.

```
127.0.0.1:61234
```

**Comment by pwfcurry** [comment]
Thanks @bradfitz, makes sense.

I was surprised this couldn't be passed as a parameter when creating a new test server - do you know if this was intentionally omitted?

**Comment by bradfitz** [comment]
> I was surprised that the host/port couldn't be passed as an optional parameter when creating a new test server - do you know if this was intentionally omitted?

If you want to specify an explicit port, there's a whole package for running HTTP servers:

https://golang.org/pkg/net/http/

The httptest package is for making it easy to write tests, and in a test you shouldn't need to worry about little details like IPs or port numbers.
