### ISSUE TITLE
strings.Split on space weird behavior, but only with a slice

### ISSUE THREAD

**Issue by jpttsn** [golang/go#28620]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Debugged this as far as I could, and got a minimal failing test.

```golang
    //When passing in a string literal, split manages.
	y := strings.Split("xx xx", " ")
	t.Logf("len(%v) = %v", y, len(y))
	if len(y) != 2 {
		t.Fatal("split failed and we got back one value", x[0])
	}

  //But if I pass in the same exact string via a slice, it doesn't
  //This took a while to figure out because it was originally in a for-range over the groups slice
	groups := []string{
		"xx xx",
	}
	group := groups[0]
	x := strings.Split(group, " ")
	t.Logf("len(%v) = %v", x, len(x))
	if len(x) != 2 {
		t.Fatal("split failed and we got back one value", x[0])
	}
```

#### What did you expect to see?

I expect strings.Split to split my string, or maybe fail to split it (if the separator can't be found).

#### What did you see instead?

Split works if I pass in a string literal, but fails if I pass the same string from a slice.

I might be missing something. Seems to me Split should split or fail to split depending on the contents of the string, regardless if it comes form a literal or from a slice.

Tested some other separators, and it works consistently with comma etc. But with a single space as `sep` the inconsistency appears.

#### Does this issue reproduce with the latest release (go1.11.2)?

Yup. Upgraded after I generated this bug report and confirmed it.

#### System details

Recent Macbook, Go installed via homebrew.

```
go version go1.11.1 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/joel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/joel/Developer/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/joel/Developer/dinnerbot/go.mod"
GOROOT/bin/go version: go version go1.11.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11.1
uname -v: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
lldb --version: lldb-1000.11.38.2
  Swift-4.2
```

**Comment by martisch** [comment]
im not seeing the issue adjusting the program to work on the playground:
https://play.golang.org/p/HSDrsI1758A

**Comment by ianlancetaylor** [comment]
Please show us a complete program that demonstrates the problem.  Thanks.

**Comment by jpttsn** [comment]
Maybe it occurs only under go test?

**Comment by martisch** [comment]
Then please post the complete minimal program that is run with go test and reproduces an issue.

**Comment by jpttsn** [comment]
'''golang
package muhtest

import (
	"strings"
	"testing"
)

func TestSplit(t *testing.T) {

	y := strings.Split("xx xx", " ")
	t.Logf("len(%v) = %v", y, len(y))

	if len(y) != 2 {
		t.Fatal("split failed and we got back one value", y[0])
	}

	groups := []string{
		"xx xx",
	}
	group := groups[0]
	x := strings.Split(group, " ")
	t.Logf("len(%v) = %v", x, len(x))

	if len(x) != 2 {
		t.Fatal("split failed and we got back one value", x[0])
	}
}
'''

'''
--- FAIL: TestSplit (0.00s)
    bug_test.go:11: len([xx xx]) = 2
    bug_test.go:22: len([xx xx]) = 1
    bug_test.go:25: split failed and we got back one value xx xx
FAIL
FAIL	command-line-arguments	0.005s
'''

**Comment by jpttsn** [comment]
Probably wasted your time with this, think it's a different space character

**Comment by martisch** [comment]
Could be: copy pasting the above code and testing with either go1.11.1 or go tip does not reproduce an error for me.
