### ISSUE TITLE
in my project go vet report a mistake, origData declared but not used, but i declare and use it

### ISSUE THREAD

**Issue by orange-jacky** [golang/go#28630]
env
go1.11 darwin/amd64
macos

in my project go vet report a mistake, origData declared but not used, but i declare and use it

func a(){
	var qqMapResp QQMapResp
	var origData []byte
	err = common.HttpDo(ctx, req,
		func(resp *http.Response, err error) error {
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			//parse the json result
			if orig, err := ioutil.ReadAll(resp.Body); err != nil {
				return err
			} else {
				origData = orig //指向原始数据
				//找到有用字符串
				start := bytes.IndexByte(orig, '{')
				end := bytes.LastIndexByte(orig, '}')
				if start != -1 && end != -1 { //兼容返回错误格式数据
					data := orig[start : end+1]
					if err := json.Unmarshal(data, &qqMapResp); err != nil {
						return err
					}
				}
			}
			return nil
		})
}

//The HttpDo function runs the HTTP request and processes its response in a new goroutine.
//It cancels the request if ctx.Done is closed before the goroutine exits:
func HttpDo(ctx context.Context, req *http.Request, f func(*http.Response,
	error) error) error {
	// Run the HTTP request in a goroutine and pass the response to f.
	tr := &http.Transport{}
	client := &http.Client{Transport: tr}
	c := make(chan error, 1)
	go func() { c <- f(client.Do(req)) }()
	select {
	case <-ctx.Done():
		tr.CancelRequest(req)
		<-c // Wait for f to return.
		return ctx.Err()
	case err := <-c:
		return err
	}
}

macbookpro:lonlat fredlee$ go env
GOARCH="amd64"
GOBIN="/Users/fredlee/Documents/develop/go/workspace/bin"
GOCACHE="/Users/fredlee/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fredlee/Documents/develop/go/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fredlee/Documents/develop/go/workspace/src/huoli/lonlat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/34/z2z_vp1573g5014m8k7wys100000gn/T/go-build130645327=/tmp/go-build -gno-record-gcc-switches -fno-common"
macbookpro:lonlat fredlee$

**Comment by ianlancetaylor** [comment]
In the code you showed us, you assign a value to origData, but you never use it for anything.  This is working as intended.

**Comment by orange-jacky** [comment]
i use it , you can look at  the code 

var origData []byte
	err = common.HttpDo(ctx, req,
		func(resp *http.Response, err error) error {
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			//parse the json result
			if orig, err := ioutil.ReadAll(resp.Body); err != nil {
				return err
			} else {
				### **origData = orig //指向**原始数据
				//找到有用字符串
				start := bytes.IndexByte(orig, '{')
				end := bytes.LastIndexByte(orig, '}')
				if start != -1 && end != -1 { //兼容返回错误格式数据
					data := orig[start : end+1]
					if err := json.Unmarshal(data, &qqMapResp); err != nil {
						return err
					}
				}
			}
			return nil
		})

**Comment by orange-jacky** [comment]
> In the code you showed us, you assign a value to origData, but you never use it for anything. This is working as intended.

i use it , you can look at the code

var origData []byte
err = common.HttpDo(ctx, req,
func(resp *http.Response, err error) error {
if err != nil {
return err
}
defer resp.Body.Close()
//parse the json result
if orig, err := ioutil.ReadAll(resp.Body); err != nil {
return err
} else {
### origData = orig //指向原始数据
//找到有用字符串
start := bytes.IndexByte(orig, '{')
end := bytes.LastIndexByte(orig, '}')
if start != -1 && end != -1 { //兼容返回错误格式数据
data := orig[start : end+1]
if err := json.Unmarshal(data, &qqMapResp); err != nil {
return err
}
}
}
return nil
})

**Comment by ianlancetaylor** [comment]
The statement `origData = orig` is not a use of `origData`.  It is an assignment to `origData`.  It doesn't use the value in `origData` for anything.  It only sets `origData` to a value.  The vet tool is telling you that you aren't using `origData`.
