### ISSUE TITLE
x/build/env/linux-arm64: add race builder for linux/arm64

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28637]
https://go-review.googlesource.com/c/go/+/138675 adds support for the race detector on linux/arm64.

Setup a builder for it.

/cc @cherrymui @dmitshur

**Comment by bcmills** [comment]
Given that it's a first-class port, a `linux-arm64-longtest-race` builder is probably a good idea too, assuming we can find the resources for it.

**Comment by cagedmantis** [comment]
This work has been completed.
