### ISSUE TITLE
proposal: net/mail: special error for empty group address

### ISSUE THREAD

**Issue by neganovalexey** [golang/go#28638]
Empty group address is often used to hide email recipients, for example,
```
To: undisclosed-recipient:;
```
(http://www.postfix.org/postconf.5.html#undisclosed_recipients_header)

The mail.ParseAddress() function returns nil and error on such inputs now, and this error ("mail: empty group") is not exported. Hence it is difficult to parse a wide range of emails.
I suggest to declare an exported error variable that could be used to detect the case. It will not change behavior of any existing Go program, but it will significantly help for email parsing.

**Comment by rsc** [comment]
If you parse

   To: undisclosed-recipient:;
   To: Joe <joe@joe.com>
   To: Joe <joe@joe.com>, Jane <jane@jane.com>

with ParseAddress, then only the second case will succeed. ParseAddress means 1 address. So don't you want ParseAddressList anyway, which accepts both 0 and 2 addresses? And then you shouldn't need this error to be exported.
