### ISSUE TITLE
'go mod tidy' removes entries related to the 'replace' instruction

### ISSUE THREAD

**Issue by edwingeng** [golang/go#28632]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.2
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gengbing/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gengbing/Workspace/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gengbing/Workspace/tmp/gomodbug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z5/hn4wg1jd1pb5z2wl3x8y9ng40000gn/T/go-build233013232=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
mkdir gomodbug
cd gomodbug

cat << EOF > go.mod
module gomodbug

replace (
	github.com/mailru/easyjson => github.com/edwingeng/easyjson v0.0.0-20180909112517-9ee4e6945130
)
EOF

cat << EOF > stub.go
// +build untouchable

package gomodbug

import (
        _ "github.com/mailru/easyjson/easyjson"
)
EOF

cat << EOF > x.go
package gomodbug

type Foo struct {
	A int
	B string
}
EOF

go install github.com/mailru/easyjson/easyjson
easyjson -omit_empty -all x.go

echo
cat go.sum
echo

go mod tidy
cat go.sum
</pre>

### What did you expect to see?

'go mod tidy' should not change go.sum.

### What did you see instead?

The 'cat go.sum' before 'go mod tidy' outputs:
<pre>
github.com/edwingeng/easyjson v0.0.0-20180909112517-9ee4e6945130 h1:Ke1vi7wBhQv5uramtBfIIJ00crorqtiDAdcqzfJ3/B0=
github.com/edwingeng/easyjson v0.0.0-20180909112517-9ee4e6945130/go.mod h1:8Db6a8b4MGQg08ypk+IK5qQDIGPdVGGp+9RlA1FFRnE=
</pre>
The 'cat go.sum' after 'go mod tidy' outputs:
<pre>
github.com/edwingeng/easyjson v0.0.0-20180909112517-9ee4e6945130/go.mod h1:8Db6a8b4MGQg08ypk+IK5qQDIGPdVGGp+9RlA1FFRnE=
</pre>

**Comment by myitcv** [comment]
Dup of https://github.com/golang/go/issues/27868
