### ISSUE TITLE
cmd/go: go mod vendor some replace pkg didn't inside vendor

### ISSUE THREAD

**Issue by lizihuai** [golang/go#28633]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.11 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
GO111MODULE=on go mod download
GO111MODULE=on go mod vendor

  I use "replace" in go.mod file . like `replace golang.org/x/crypto v0.0.0-20180820150726-614d502a4dac => github.com/golang/crypto v0.0.0-20180820150726-614d502a4dac`  use `go mod download `  ，downloaded package in “src/pkg” directory   , but when   use `go mod vendor`  some pkg didn't inside the vendor

**Comment by ianlancetaylor** [comment]
CC @bcmills

**Comment by lizihuai** [comment]
for example ,`go.mod` like (fake code)

module github.com/lizihuai/test

require (
	 golang.org/x/net v0.0.0-20180824152047-4bcd98cce591
	 google.golang.org/grpc v1.14.0
	 k8s.io/api v0.0.0-20180925152912-a191abe0b71e // indirect
	 k8s.io/apimachinery v0.0.0-20180823151430-017bf4f8f588
)

replace (
	golang.org/x/crypto v0.0.0-20180820150726-614d502a4dac => github.com/golang/crypto v0.0.0-20180820150726-614d502a4dac
	golang.org/x/net v0.0.0-20180824152047-4bcd98cce591 => github.com/golang/net v0.0.0-20180824152047-4bcd98cce591
	golang.org/x/sys v0.0.0-20180824143301-4910a1d54f87 => github.com/golang/sys v0.0.0-20180824143301-4910a1d54f87
	golang.org/x/text v0.3.0 => github.com/golang/text v0.3.0
	golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2 => github.com/golang/time v0.0.0-20180412165947-fbb02b2291d2
)

use  `go mod download`  be downloaded no matter what use   `requireor` or  `replace ` but `go mod vendor` some pkg not inside " vendor" , like  "golang.org/x/sys" (the project use all of the above packages)

**Comment by ibalajiarun** [comment]
I have a similar issue. Let say I have a `go.mod` like below, where I want to use my fork of go.etcd.io/etcd at gitlab.com

`module gitlab.com/user/go-raft-kv

go 1.12

replace go.etcd.io/etcd => gitlab.com/user/etcd v0.0.0-20190418142634-07789e37997a

require (
	github.com/gogo/protobuf v1.2.1
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/pkg/errors v0.8.1
	github.com/spf13/pflag v1.0.3
	go.etcd.io/etcd v3.3.12+incompatible
	golang.org/x/net v0.0.0-20190415214537-1da14a5a36f2
	google.golang.org/grpc v1.20.0
)`

My main.go file imports "go.etcd.io/etcd/raft" and uses it. When I `go mod vendor`, go.etcd.io is downloaded into vendor and not 'gitlab.com/user/etcd'. Doesn't vendor respect replace?

**Comment by ibalajiarun** [comment]
My bad. It works, but uses the same module name as the original. That confused me. Sorry about that.
