### ISSUE TITLE
x/tools/cmd/goimports: goimports removes used import, breaks build

### ISSUE THREAD

**Issue by dcelasun** [golang/go#28645]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 linux/amd64
</pre>

`goimports` from [34b416b](https://github.com/golang/tools/commit/34b416bd17b3a33e02879e34237e92c171550ed5).

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/dcelasun/go/bin"
GOCACHE="/home/dcelasun/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dcelasun/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build196516147=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```sh
$ git clone https://github.com/dcelasun/importbug.git $GOPATH/src/github.com/dcelasun/importbug
$ cd $GOPATH/src/github.com/dcelasun/importbug
$ go get -u golang.org/x/tools/cmd/goimports
$ goimports -l -w main.go
$ go build
```
See: https://github.com/dcelasun/importbug

### What did you expect to see?
Successfully build the program.

### What did you see instead?
```sh
$ go build
# github.com/dcelasun/importbug
./main.go:8:14: undefined: fb
```
because goimports removed the `github.com/dcelasun/importbug/go-foobar` import.

**Comment by heschik** [comment]
This would be https://github.com/golang/tools/commit/864069cfd1b106326ae556b3ca5c1d6b94645987. Giving the import an explicit name will keep it from being removed but it's a bad user experience. I'll roll back while I think about it.

**Comment by heschik** [comment]
Fixed in https://github.com/golang/tools/commit/a28dfb48e06b2296b66678872c2cb638f0304f20.
