### ISSUE TITLE
x/tools/cmd/goimports: Goimports removes valid import paths when pkgName != dirName

### ISSUE THREAD

**Issue by VojtechVitek** [golang/go#28646]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
`go get -u -v golang.org/x/tools/cmd/goimports`

As of writing, goimports are on this commit: https://github.com/golang/tools/commit/4ca49954c3f2dca17746a9bd2d3f253c4849d9ee

### Regression reproducer

Please, see a reproducer repo: https://github.com/VojtechVitek/goimports-bug

### Issue
Seems like latest goimports started removing completely valid import paths when package name doesn't match the pkg's directory name.

**Comment by VojtechVitek** [comment]
Probably a duplicate of #28645, which has been submitted while I was writing this down.

**Comment by heschik** [comment]
Yep, should be fixed now. Sorry for the trouble.

**Comment by VojtechVitek** [comment]
Thanks for the quick fix!

**Comment by requilence** [comment]
@heschik Just to make you know, it is still not fixed at `1.11.4`
And I can't find a fix  at [goimports repo](https://github.com/golang/tools/tree/master/cmd/goimports)

**Comment by heschik** [comment]
Most of goimports' code is in x/tools/imports. The bad change was rolled back in https://github.com/golang/tools/commit/a28dfb48e06b2296b66678872c2cb638f0304f20. If you're still having problems, please file a new bug with more detail, ideally a repro case.
