### ISSUE TITLE
cmd/asm: s390x asm doesn't accept syntax for internal constants

### ISSUE THREAD

**Issue by billotosyr** [golang/go#28648]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12 master tip
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
Linux s390x
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="s390x"
GOBIN=""
GOCACHE="/gsa/tlbgsa/home/b/i/billo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/gsa/tlbgsa/home/b/i/billo/work"
GOPROXY=""
GORACE=""
GOROOT="/sandbox/billo/masterellipticfinal/go"
GOTMPDIR=""
GOTOOLDIR="/sandbox/billo/masterellipticfinal/go/pkg/tool/linux_s390x"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build825300130=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Tried to access internal contants in the cpu package with synax like

   MOVB   internal\cpu·S390X·HasVE1(SB), R7

but the just gives me synax errors like:

   expected '(', found \

I believe this works in amd64 assembly

### What did you expect to see?

correct assembly

### What did you see instead?

synax error

**Comment by ianlancetaylor** [comment]
CC @mundaym

**Comment by martisch** [comment]
Have you tried "internal∕cpu·S390X+constant" where '∕' should be a unicode '∕' not an ASCII '/' and constant has to be defined in the package the asm file is in not in internal/cpu?

**Comment by billotosyr** [comment]
Thanks for the tips :-) Another thing I found is that I seem to need to include go_asm.h, otherwise the whole constant offset syntax isn't recognized. I haven't seen this documented.

**Comment by billotosyr** [comment]
Ok, I have this working now. Thanks.
