### ISSUE TITLE
x/build/cmd/coordinator: build dashboard for subrepos is confusing

### ISSUE THREAD

**Issue by matloob** [golang/go#28643]
cc @dmitshur 

The build dashboard for subrepos is a bit hard to read. The the go distribution that's tested against is given as a commit hash, which is sometimes useful but most of the time I care about which version of Go is tested against especially since multiple versions of Go appear in the dashboard.

It's a little hard to tell which version of Go is tested against which version of the subrepo. It might be helpful to combine the rows  for a given version of the subrepo.

**Comment by bradfitz** [comment]
Which page are you talking about?

This one? https://build.golang.org/?repo=golang.org%2fx%2ftools

**Comment by matloob** [comment]
Yeah that's the page.

**Comment by dmitshur** [comment]
Our migration to [LUCI](https://go.dev/wiki/LUCI) should make a meaningful improvement for golang.org/x repo result views.

Using a recent issue #67439 as an example, where CL 546676 introduced a net/http behavior change that broke a test in x/build and CL 586315 fixed it, this can be cleanly deduced from LUCI's "by Go commit" views:

<img width="1169" alt="image" src="https://github.com/golang/go/assets/1924134/e6526bd0-f9d2-4e12-92f7-8bd9167adb31"><br>

(For comparison, the old view shows this as [this](https://github.com/golang/go/assets/1924134/5f830c8f-23bc-4af5-813d-872123bea3d8), with interleaving "ok" rows that are actually results from different release branches.)

I don't anticipate we'll be doing more work on this in the coordinator codebase, so closing this.
