### ISSUE TITLE
x/build: “Gerrit User XXX” displayed instead of actual name in Gerrit messages

### ISSUE THREAD

**Issue by rsc** [golang/go#28663]
https://github.com/golang/go/pull/28659#issuecomment-437027632 says "Message from Gerrit User 5056". This needs to be fixed, and soon.

It's easy to fix - the usual Gerrit REST API ChangeInfo uses the right names. I'm perplexed as to why the maintner feed says these things but at least the bot could re-fetch the actual Gerrit comments directly from Gerrit (only when it needs to post one to GitHub, so fairly low rate) to find out real names.

#28662 means that from Gerrit I can't tell who is writing the CL and this bug means that from GitHub I can't tell who is reviewing the CL. This is not really an acceptable review process.

**Comment by andybons** [comment]
This should take effect on Nov 9 00:00 UTC in that all new comments after that time will have the correct display name.

**Comment by andybons** [comment]
This is now fixed for all new comments.

Sorry for the inconvenience, @rsc.

**Comment by rsc** [comment]
Thanks for the quick fix.
