### ISSUE TITLE
VGO modules internal packages are not recognised

### ISSUE THREAD

**Issue by Macilias** [golang/go#28661]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mniemczyk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mniemczyk/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3k/0437mzfx1qxcc3j5p9pqmytm0000gn/T/go-build743254889=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Try to use own packages within GoLand . 

https://play.golang.org/p/CfJlS2WZQMx

### What did you expect to see?
Hello, world.
Hello from fooHello from foo

and correct syntax highlighting in goland

### What did you see instead?
"can not resolve directory "github.com/you/hello/foo" 
in imports 

here is my go.mod file:
module github.com/you/hello

require rsc.io/quote v1.5.2

**Comment by Macilias** [comment]
actually fixed the problem by enabling the checkbox
[] Enable Go Modules (vgo) integration beneath:
Settings/Go/Go Modul (vgo)

Actually I think its a but that it has not been enabled automatically, since project contains go.mod and go.sum.

**Comment by agnivade** [comment]
That is a bug with GoLand. This bug tracker is for the Go programming language.
