### ISSUE TITLE
gccgo: hugo tests fail with gccgo, works fine with gc

### ISSUE THREAD

**Issue by glaubitz** [golang/go#28669]
Trying to build ```hugo``` with gccgo fails because the testsuite fails with:

```
=== RUN   TestMethodToName
--- FAIL: TestMethodToName (0.00s)
        assertions.go:256: 
                        Error Trace:    templatefuncRegistry_test.go:34
                        Error:          Not equal: 
                                        expected: "$thunk0"
                                        actual  : "thunk0"
                                    
                                        Diff:
                                        --- Expected
                                        +++ Actual
                                        @@ -1 +1 @@
                                        -$thunk0
                                        +thunk0
                        Test:           TestMethodToName
FAIL
FAIL    github.com/gohugoio/hugo/tpl/internal   0.523s
```

Full log available at: https://people.debian.org/~glaubitz/gccgo-logs/hugo_0.47.1-2_amd64.build

**Comment by bradfitz** [comment]
Fragile test making too many assumptions, or something gccgo should strive to match, even if not required?

/cc @spf13 @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Thanks for reporting this.  This is a problem with the test, not with gccgo.  Sent https://github.com/gohugoio/hugo/pull/5423 to fix it.

**Comment by bep** [comment]
This test was originally adjusted to make the Debian build happy, so I guess this is full circle. The test in question is kind of superfluous, as lots of other tests would break if this name mapping construct was broken. But it should go green for Debian now.

**Comment by ianlancetaylor** [comment]
@bep Thanks.
