### ISSUE TITLE
x/build/cmd/gerritbot: github PR bot does not say who wrote CL

### ISSUE THREAD

**Issue by rsc** [golang/go#28662]
I can't see who wrote https://go-review.googlesource.com/c/go/+/148477
unless I open the "Commit message" file entry. 

Can we please get that fixed? 

The best option would be to have Gerrit show the author and
commit lines in the commit message shown on the front page
but since we probably can't make that happen soon,
let's at least make the bot post in its first message
some minimal explanatory text like

	This Gerrit CL corresponds to GitHub PR golang/go#00000.
	
	Author: Jane Gopher <jane@goph.er>

Thanks.

**Comment by bradfitz** [comment]
This is almost a dup of #24837, but this bug has good workarounds in the meantime, as #24837 is a bit idealistic and largely out of our hands.

/cc @andybons @dmitshur @FiloSottile @katiehockman

**Comment by andybons** [comment]
We can use https://gerrit-review.googlesource.com/Documentation/user-upload.html#message to add a message upon upload.
