### ISSUE TITLE
gccgo: snapd doesn't compile with gccgo, builds fine with gc

### ISSUE THREAD

**Issue by glaubitz** [golang/go#28664]
Trying to build ```snapd``` with gccgo fails with:

```
...
github.com/snapcore/snapd/overlord
github.com/snapcore/snapd/overlord/servicestate
github.com/snapcore/snapd/overlord/hookstate/ctlcmd
github.com/snapcore/snapd/polkit
github.com/snapcore/snapd/daemon
# github.com/snapcore/snapd/daemon
src/github.com/snapcore/snapd/daemon/daemon.go:276:40: too many arguments in call to activation.Listeners
        have (bool)
        want ()
go/parser
github.com/snapcore/snapd/i18n/xgettext-go
flag
go/printer
runtime/debug
runtime/trace
testing
gopkg.in/check.v1
github.com/snapcore/snapd/snap/snaptest
github.com/snapcore/snapd/interfaces/ifacetest
github.com/snapcore/snapd/overlord/hookstate/hooktest
github.com/snapcore/snapd/progress/progresstest
github.com/snapcore/snapd/store/storetest
github.com/snapcore/snapd/testutil
...
```

Full log available at: https://people.debian.org/~glaubitz/gccgo-logs/snapd_2.30-5_amd64.build

**Comment by ianlancetaylor** [comment]
I'm not sure what is going on here.  That error message could not come from gccgo.  That is an error message generated by the gc compiler, not the gccgo compiler.  For this kind of case the gccgo compiler would emit an error like

    src/github.com/snapcore/snapd/daemon/daemon.go:276:40: error: too many arguments

followed by a display of the line with a caret pointing to that position.  It would not display the "have" and "want" lines shown above.

For me, that package builds with both gc and gccgo with no trouble, both on tip and on the 2.30 tar in the repo.

Can you double check that this really using gccgo?  Can you give me a recipe that I can use to recreate the problem?  Thanks.
