### ISSUE TITLE
gccgo: etcd-fs doesn't compile with gccgo, builds fine with gc

### ISSUE THREAD

**Issue by glaubitz** [golang/go#28672]
Trying to build ```etcd-fs`` with gccgo fails with:

```
github.com/hanwen/go-fuse/splice
github.com/coreos/go-etcd/etcd
golang.org/x/sys/unix
github.com/hanwen/go-fuse/fuse
github.com/hanwen/go-fuse/fuse/nodefs
github.com/hanwen/go-fuse/fuse/pathfs
github.com/xetorthio/etcd-fs/src/etcdfs
# github.com/xetorthio/etcd-fs/src/etcdfs
src/github.com/xetorthio/etcd-fs/src/etcdfs/file.go:21:10: error: incompatible type for return value 1 (missing method 'GetLk')
   return file
          ^
```

Full log available at: https://people.debian.org/~glaubitz/gccgo-logs/etcd-fs_0.0+git20140621.0.395eacb-4_amd64.build

**Comment by bradfitz** [comment]
It fails with gc in the same way, though.

Everything fails much differently at each of those dependencies' HEAD revisions (so `go get -u` won't reproduce this), but if I `go get -u` and then `git reset --hard $REV` the following to the same as in your logsa,

* 395eacb for etcd-fs, which is recent
* c029b69 for hanwen/go-fuse
* ef5ddc991ddbd51fcdb771c445c63789b5d00f5d for coreos/go-etcd

Then I get the same with gc:

```
bradfitz@gdev:~/src/github.com/xetorthio/etcd-fs/src/etcdfs$ go install .
# github.com/xetorthio/etcd-fs/src/etcdfs
./file.go:21:3: cannot use file (type *etcdFile) as type nodefs.File in return argument:
        *etcdFile does not implement nodefs.File (missing GetLk method)
```

So I'm not sure if there's a bug here?

You're sure that's building with the same set of revisions with the Debian "golang" gc compiler?

/cc @ianlancetaylor @xetorthio @hanwen

**Comment by glaubitz** [comment]
> You're sure that's building with the same set of revisions with the Debian "golang" gc compiler?

Yes. I'll re-test with gc. Just a second, please. The last build with gc on the build infrastructure was 127 days ago, so something might have changed.

**Comment by glaubitz** [comment]
Just a fresh rebuild with ```gc``` and, indeed, it also fails there:

```
github.com/coreos/go-etcd/etcd
github.com/xetorthio/etcd-fs/src/etcdfs
# github.com/xetorthio/etcd-fs/src/etcdfs
src/github.com/xetorthio/etcd-fs/src/etcdfs/file.go:21:3: cannot use file (type *etcdFile) as type nodefs.File in return argument:
        *etcdFile does not implement nodefs.File (missing GetLk method)
```

For reference, the last successful build was in July on the automatic build infrastructure: https://buildd.debian.org/status/fetch.php?pkg=etcd-fs&arch=i386&ver=0.0%2Bgit20140621.0.395eacb-4&stamp=1530781427&raw=0

**Comment by bradfitz** [comment]
Okay, I'll close this bug, as this is a distro issue (finding a set of revisions that's good to ship), not a compiler issue (the two main compilers agree).

**Comment by ianlancetaylor** [comment]
@bradfitz Thanks.
