### ISSUE TITLE
Suddenly go build doesn't respect '// +build ignore' flag

### ISSUE THREAD

**Issue by lnshi** [golang/go#28687]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/leonard/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/leonard/go_projects"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xw/fjl2c85x0psg7nm1sth8y_m40000gn/T/go-build892466275=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Just use the command `env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o attacker main.go` to build one of my single package to executable binary.

But since I don't want to include this package in my production release, so i use the `// +build ignore` to ignore it, only when i need to run above build command i remove the `// +build ignore` flag.

Previously the `// +build ignore` was working as expected, i mean if i run above command with it i will run into error that "the source was ignored.. bla bla", if i want to build it then i need to remove the `// +build ignore`, **but now with the `// +build ignore` there, i still can build it!!!**, totally cannot recall what was changed to cause this.

### What did you expect to see?

With the `// +build ignore` i should not able to build the source.

### What did you see instead?

Even with the `// +build ignore` there i am still able not build the source and roll out the executable binary!

```
// +build ignore

package main

import (
	"flag"
	"fmt"
	"math/rand"
	"runtime"
	"sync"
	"time"
```

**Comment by mvdan** [comment]
I use `// +build ignore` in my projects and it hasn't broken for me. Please provide a full Go program to reproduce this bug, and clear steps to do so.

Also note that you don't need to remove the build ignore line when you do `go build somefile.go`. Files can only be ignored when one is building an entire package; the lines don't take effect when one is specifying what files to build.

**Comment by mvdan** [comment]
Also note that the latest Go version is 1.11, not 1.10. Have you tried that?

**Comment by lnshi** [comment]
oh, then i think my report is misinformation, i remember i always build this package(single go file actually)  with command `env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o attacker main.go`, maybe i remembered wrongly.

when i omit the `main.go` in above command  i am able to see the familiar error i remembered before: `can't load package: bla bla ...: build constraints exclude all Go files bla bla`

I am gonna close this.

Thanks a lot for the clarification.
