### ISSUE TITLE
cmd/go: panic when argument doesn't match any packages

### ISSUE THREAD

**Issue by nicksnyder** [golang/go#28696]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nick/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nick/dev/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l6/djg_zw1j5lgbwz4h5q92lnwr0000gn/T/go-build874216167=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
$ go run notadir/...
go: warning: "notadir/..." matched no packages
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/go/internal/run.runRun(0x195b2e0, 0xc0000a60b0, 0x1, 0x1)
	/usr/local/Cellar/go/1.11.2/libexec/src/cmd/go/internal/run/run.go:88 +0xc01
main.main()
	/usr/local/Cellar/go/1.11.2/libexec/src/cmd/go/main.go:219 +0x7d4
```

### What did you expect to see?

Not a panic.

### What did you see instead?

A panic.

Related to https://github.com/golang/go/issues/8165 ?

**Comment by mark-rushakoff** [comment]
Seems specific to `go run`.  `go test`, `go build`, and `go install` all give errors without panicking.

The panic is reproducible on tip at `go version devel +5e17ce22ec Fri Nov 9 16:11:42 2018 +0000 darwin/amd64`, with what looks like the same stack trace:

```
go: warning: "./x/..." matched no packages
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/go/internal/run.runRun(0x19e6ea0, 0xc0000c4020, 0x1, 0x1)
	/Users/mr/gotip/src/github.com/golang/go/src/cmd/go/internal/run/run.go:88 +0xbbd
main.main()
	/Users/mr/gotip/src/github.com/golang/go/src/cmd/go/main.go:219 +0x8b7
```

**Comment by mark-rushakoff** [comment]
This is a trivial fix. I'll be sending a PR shortly.

**Comment by odeke-em** [comment]
Thanks for reporting this @nicksnyder and for working on it @mark-rushakoff!

This is a new panic in Go1.11.*. On Go1.10, it printed out
```shell
$ go run nonexistent/...
go run: no go files listed
```
and now on Go.1.11, it panics as reported
```shell
$ go run nonexistent/...
go: warning: "nonexistent/..." matched no packages
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/go/internal/run.runRun(0x195d2e0, 0xc0000ae0b0, 0x1, 0x1)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/cmd/go/internal/run/run.go:88 +0xc01
main.main()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/cmd/go/main.go:219 +0x7d4
```

@gopherbot please open a backport tracking issue for 1.11.

**Comment by odeke-em** [comment]
For some reason, Gopherbot opened up a backport for Go1.10, /cc @FiloSottile @dmitshur

**Comment by mark-rushakoff** [comment]
@odeke-em I think that was because you mentioned Go1.10 in the previous behavior early in your comment. Gopherbot's wiki says the release can be anywhere in the comment.

@gopherbot, please remove label NeedsInvestigation.
