### ISSUE TITLE
os: clarify documentation for O_TRUNC

### ISSUE THREAD

**Issue by bcmills** [golang/go#28699]
The comment for `os.O_TRUNC` currently says:
https://github.com/golang/go/blob/78c0e1f81d4052f8ca5a50e4e7c5bb35ddec6519/src/os/file.go#L76

The “if possible” part of that comment is ambiguous: on Linux it seems to mean “if the file is a regular file or symlink to a regular file” (i.e., not a stream like `/dev/stdout`), but it could be “impossible” to truncate the file for other reasons (such as a permission error), and `os.OpenFile` with `os.O_TRUNC` seems to report an error in those cases.

We should drop the “if possible” phrase and instead explicitly document the conditions under which `O_TRUNC` is ignored.

**Comment by bcmills** [comment]
(CC @rsc @robpike @ianlancetaylor)

**Comment by robpike** [comment]
I fear that making the os package document every aspect, for every OS, of the calls it wraps is a Sisyphean endeavor and not worth pursuing.
