### ISSUE TITLE
x/build/cmd/coordinator: some CLs exp subrepo left strange active trybots running

### ISSUE THREAD

**Issue by dmitshur** [golang/go#28714]
A few CLs ([147877](https://golang.org/cl/147877), [147797](https://golang.org/cl/147797), [146197](https://golang.org/cl/146197)) in the exp subrepo started trybots.

They each ended with a trybot run that started, but never finished. E.g.:

> TryBots beginning. Status page: https://farmer.golang.org/try?commit=0d16b4a3

![image](https://user-images.githubusercontent.com/1924134/48303582-d1946680-e4d9-11e8-95f2-a40a98618469.png)

As a result, farmer shows 3 active trybot runs now, with -2 remaining builds each:

![image](https://user-images.githubusercontent.com/1924134/48303596-ebce4480-e4d9-11e8-8d18-04ff24c27d1b.png)

/cc @bradfitz

Reporting this for our reference, since I'm about to redeploy coordinator and we might lose this information.

**Comment by dmitshur** [comment]
The "Builds Remaining" number calculation is clearly wrong. I've noticed it's sometimes wrong even elsewhere, for trybots that succeed properly. E.g., from [this](https://go-review.googlesource.com/c/tools/+/149017/1#message-c9e41a05148c193ecb29626ff81407031e7d68c7) trybot run:

<img width=272px src=https://user-images.githubusercontent.com/1924134/48304929-4d99a900-e4f0-11e8-96e8-3d844a240475.png>

**Comment by bradfitz** [comment]
Fallout from #17626. Specifically from https://go-review.googlesource.com/c/build/+/143538/ ... before that CL the number of builders in a tryset was always equal to the number of try builders. Apparently I missed that we had made that assumption.

Easy enough fix.

**Comment by dmitshur** [comment]
Thanks for diagnosing the issue.
