### ISSUE TITLE
cmd/cgo: don't accept mangled C names in Cgo programs

### ISSUE THREAD

**Issue by wzshiming** [golang/go#28721]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/Users/zsm/go/bin"
GOCACHE="/Users/zsm/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zsm/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6v/7stmg2756wlfk9c_qnv1hnbm0000gn/T/go-build905706456=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

``` go
package test

/*
typedef struct a {
	int i;
} a;

a* A() {
	return NULL;
};
*/
import "C"

type a struct {
	a *_Ctype_struct_a
}

func A() *a {
	i := C.A()
	return &a{i}
}

```

$ `gomobile bind test`

### What did you expect to see?

Building succeeds.

### What did you see instead?

gomobile: /Users/zsm/go/bin/gobind -lang=go,java -outdir=/var/folders/6v/7stmg2756wlfk9c_qnv1hnbm0000gn/T/gomobile-work-058021600 test failed: exit status 1
type-checking package "test" failed (/Users/zsm/go/src/test/main.go:15:5: undeclared name: _Ctype_struct_a)

**Comment by AlexRouSg** [comment]
What happens when you do this instead?
```
type a struct {
	a *C.a
}
```

**Comment by wzshiming** [comment]
@AlexRouSg  Building succeeds.

**Comment by AlexRouSg** [comment]
Any particular reason you're using `a *_Ctype_struct_a`?

**Comment by wzshiming** [comment]
A third-party package I used is like this.
There was no problem with previous use but gomobile-bind does.

Debugging finds this.
` _Ctype_struct_a ` not in Go-struct field is no problem.
Why can't you put a Go-struct field.

**Comment by AlexRouSg** [comment]
cc @eliasnaur

**Comment by eliasnaur** [comment]
I believe the bug is that Go accepts the program, but shouldn't, while go/types correctly rejects the program. _Ctype_struct_a is not a defined type, and the program only builds because of the way Cgo mangles C type names. @ianlancetaylor do you agree? If so, should Go reject such programs?

I believe the correct fix is to change to program to use C.a instead, as suggested by AlexRouSg.

**Comment by eliasnaur** [comment]
Ian, I changed the title to match what I believe is the root cause. Feel free to throw it back to me if I'm mistaken.

**Comment by ianlancetaylor** [comment]
Sorry, somehow I missed this earlier.  I agree: cgo should reject the attempt to use `_Ctype_struct_a`.
