### ISSUE TITLE
cmd/link: go install -buildmode=shared -linkshared std doesn't work as expected

### ISSUE THREAD

**Issue by rezaalavi** [golang/go#28722]
### What version of Go are you using (`go version`)?

<pre>
The problem appears in all versions after 1.9.1 including 1.9.1. All versions before 1.9.1 work as expected.

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go-src"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build001874867=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?

I run "go install -buildmode=shared -linkshared std" to generated a shared library for the std.

I have run the above on all recent go version from 1.6 to 1.11.
Since 1.9.1 the above doesn't work anymore and producses a warning.
As a result we cannot dynamically link our code to std library in any version more than 1.8.7. 

### What did you expect to see?

success without any warning.

### What did you see instead?

/usr/bin/ld: warning: .init_array section has zero size

**Comment by rezaalavi** [comment]
It is the one that comes with Centos 6.
```
GNU ld version 2.20.51.0.2-5.48.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by ianlancetaylor** [comment]
Hmmm, that's an 8 year old linker.  This is just a warning, right?  The program still completes and works?
