### ISSUE TITLE
x/playground: add ability to resize the output box [automatically]

### ISSUE THREAD

**Issue by ysmolski** [golang/go#28734]
On small screens like 11-13" laptop's the output box is somewhat small. I would like to be able to adjust its height. 

Also when output is big, I want to be able to see all of it without scrolling each time after running the program. This would mean to add some controls like buttons on the right or make the edge between code and output boxes draggable.

As alternative solution would be to define the maximum allowed height of the output box and resize it depending on the output as mentioned here https://github.com/golang/go/issues/15163. That might be a pie in the sky though.

I am sure this was raised before but I could not find it.

**Comment by agnivade** [comment]
Are you talking about the embedded playground in golang.org ? 

Then perhaps something similar to the little expander icon at the bottom-right of the text box which you can use to resize the code box. We can apply the same for the output-box.

**Comment by agnivade** [comment]
Ah, you mean like a horizontal expander thing at the border of the yellow and white box ?

**Comment by ysmolsky** [comment]
@agnivade, yes in the case of UI element. But I wonder how badly do we want to resize output box automatically depending on the size of output.

@andybons

**Comment by andybons** [comment]
Seems like a solution could be to allow adjusting the split between the code and output. When you hover over the split point it shows a resize cursor (`cursor: row-resize`) and allows you to adjust it (while not saving between reloads).

**Comment by seankhliao** [comment]
the output box on go.dev/play is resizable
