### ISSUE TITLE
x/net/http2: WINDOW_UPDATE sent rate too high and can't be configured

### ISSUE THREAD

**Issue by crowfrog** [golang/go#28732]
### What version of Go are you using (`go version`)?

golang:1.10.0 linux

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

container: rhel
kubenet:

### What did you do?

Currently golang http2 stack will send WINDOW_UPDATE back when receive a request with data.
It means a client will recevie a response and WINDOW_UPDATE when it send a request with data to golang http2 server.
sent one 'request' package and got two 'reponse' package, that will impact client performance in a high load traffic.
In fact, golang stack use 2^31 as default window size for connection. It is very big and updated too frequently is unnecessary.

### What did you expect to see?

Change this behavior or make it configurable like other language http2 stack.
I think c++/java popular http2 stack have a configurable rate (default is 50%) used for sending WINDOS_UPDATE frame when the rate of left size/total is less than it.

**Comment by bradfitz** [comment]
Definitely room for improvement here. (There might even be a TODO about this in the code, IIRC) But let's not add configurability here.

**Comment by fraenkel** [comment]
The above commit is just the code change without tests. The test changes are coming as are additional tests for the new accounting. But it seems I cannot get to the codereview to mark it as DO NOT SUBMIT since I get 'No issue exists with that id (150197)'

**Comment by louygan** [comment]
I could not find the change in the master.
when will this change merged to master?

**Comment by bcmills** [comment]
Reopening because https://go.dev/cl/432038 (which marked this issue fixed) was reverted.
