### ISSUE TITLE
slice expression with low-index out of range and omitted high index doesn't give "slice bounds out of range" error

### ISSUE THREAD

**Issue by dencoded** [golang/go#28731]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dencoded/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dencoded/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9z/xzkhmlmx63nc49srq6glx6cw0000gn/T/go-build613348640=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
https://play.golang.org/p/GrgeaBAXGkp
This happens only if we specify low-index as len of slice

i.e. this gives proper error:
https://play.golang.org/p/Ax4khdrwotW

### What did you expect to see?
<pre>
panic: runtime error: slice bounds out of range
</pre>

### What did you see instead?
<pre>
len: 1
cap: 1
[]
</pre>

**Comment by dominikh** [comment]
This is working as intended:

> For arrays or strings, the indices are in range if 0 <= low <= high <= len(a), otherwise they are out of range. For slices, the upper index bound is the slice capacity cap(a) rather than the length.

**Comment by dencoded** [comment]
@dominikh well, if it is by design I've learned something new today 👍
