### ISSUE TITLE
spec: documentation of len() in string type unclear

### ISSUE THREAD

**Issue by fabulousduck** [golang/go#28736]
https://github.com/golang/go/blob/f58b02a29c395b5ec28bb548b1fd3ca18e2b3a4f/doc/go_spec.html#L833

The documentation on how specifically `len()` can be used to determine the size of a string type in bytes can be confusing as this would make you expect that `len("go")` would return `16` (like `unsafe.Sizeof("go")` would) but actually gives you `2`

I would like to ask for a better phrasing of how to use `len()` on string type in the docs

**Comment by go101** [comment]
`"go"` has two bytes, so `len("go")` is `2`. The docs is very clear on this. Why confused?

`unsafe.Sizeof(anyStr)` always returns `16`, for every string value occupies 16 bytes in memroy on 64-bit arch.

**Comment by go101** [comment]
Ah, some misunderstanding here.
The doc is really not very clear here.
`(the number of bytes stored in the string)` would be better.
