### ISSUE TITLE
crypto/x509: (*Certificate).Equals panics for nil values

### ISSUE THREAD

**Issue by empijei** [golang/go#28743]
Most methods in Go do not work on `nil` values, and that is perfectly fine, but I feel like `(*T).Equal(*T)` should behave more or less like the `==` operator.

I'm proposing a change that looks like this:
```go
// Current implementation
func (c *Certificate) Equal(other *Certificate) bool {
	return bytes.Equal(c.Raw, other.Raw)
}

// New implementation
func (c *Certificate) Equal(other *Certificate) bool {
	if c == nil || other == nil {
		return c == other
	}
	return bytes.Equal(c.Raw, other.Raw)
}
```

This is analogous to [how the regex package does it](https://golang.org/src/regexp/syntax/regexp.go?s=2563:2601#L53):
```go
func (x *Regexp) Equal(y *Regexp) bool {
	if x == nil || y == nil {
		return x == y
	}
	// [...]
```

**Comment by odeke-em** [comment]
Thank you for this change request @empijei!

I'll kindly page @FiloSottile @rsc

**Comment by odeke-em** [comment]
@empijei would you like to send a CL and a test for this? I could have sent a CL but you've already proposed the fix so please go for it. Thank you.

**Comment by empijei** [comment]
Thanks, I will asap, but I'm currently stuck on #30776. Will probably submit a fix for this in the next days.

**Comment by odeke-em** [comment]
>Thanks, I will asap, but I'm currently stuck on #30776. Will probably submit a fix for this in the next days.

Cool, no rush. However, I don't think you need to be blocked by ./all.bash. If your fix just involves the nil comparisons and also has some tests, you can submit that but also you can run the tests just in crypto/x509.
