### ISSUE TITLE
cmd/go: list -json includes assembly files among CompiledGoFiles

### ISSUE THREAD

**Issue by alandonovan** [golang/go#28749]
```
$ go version
go version devel +a4e958ff2d Mon Nov 12 13:44:06 2018 -0500 linux/amd64
$ go list -json -compiled reflect
{
        "Dir": "/usr/local/google/home/adonovan/goroot/src/reflect",
        "ImportPath": "reflect",
        "Name": "reflect",
...
        "GoFiles": [
                "deepequal.go",
                "makefunc.go",
                "swapper.go",
                "type.go",
                "value.go"
        ],
        "CompiledGoFiles": [
                "deepequal.go",
                "makefunc.go",
                "swapper.go",
                "type.go",
                "value.go",
                "asm_amd64.s"   // !
        ],
        "SFiles": [
                "asm_amd64.s"
        ],
...
```

**Comment by josharian** [comment]
`.cc` files too. This is pretty clearly a bug in cmd/go:

* `cmd/go/internal/work/exec.go`, around line 590:

```go
	var srcfiles []string // .go and non-.go
	srcfiles = append(srcfiles, gofiles...)
	srcfiles = append(srcfiles, sfiles...)
	srcfiles = append(srcfiles, cfiles...)
	srcfiles = append(srcfiles, cxxfiles...)
	b.cacheSrcFiles(a, srcfiles)
```

* `cacheSrcFiles` eventually does: `c.PutBytes(cache.Subkey(a.actionID, "srcfiles"), buf.Bytes())`.

* Later, `loadCachedSrcFiles` does: `list, _, err := c.GetBytes(cache.Subkey(a.actionID, "srcfiles"))` and then `a.Package.CompiledGoFiles = files`.

* This makes its way into the json that cmd/go emits, which go/packages trusts absolutely.

We should make cmd/go filter out non-Go files.

---

There's a comment in the go/packages source code, where it manually skips `.s` files:

```
		// Workaround for https://golang.org/issue/28749.
		// TODO(adonovan): delete before go1.12 release.
```

If we don't fix this for 1.12, we'll have to keep the workaround in go/packages for a long time. And expand it to cover `.cc`, `.c`, `.S`, etc.

I'll send a CL to expand the go/packages workaround, but I think it might be good to know how risky it is to fix this yet in cmd/go.

**Comment by mvdan** [comment]
Hello from the future - I just ran into this :) Would a patch be welcome?

**Comment by bcmills** [comment]
Looking at the fix CL, I believe this bug was introduced in https://go.dev/cl/148904 (ironically, authored by @alandonovan 😅).

**Comment by adonovan** [comment]
Heh, that fellow must be feeling pretty stupid. Thanks for the fix.

**Comment by mvdan** [comment]
Looking forward to deleting my workaround in a year or two :)
