### ISSUE TITLE
runtime: rename GODEBUGCPU=foo=bar to GODEBUG=cpu.foo=bar

### ISSUE THREAD

**Issue by rsc** [golang/go#28757]
We have successfully managed to use a single GODEBUG environment variable for runtime, net, and net/http. It doesn't really make sense to have the runtime add a second. It's not that special. Instead we should add the functionality currently in GODEBUGCPU to GODEBUG, with longer key names.

Go 1.12 intends to document the new cpu controls (see #27218), so we should change this for Go 1.12. (It has never been documented before.)

/cc @martisch @aclements

**Comment by martisch** [comment]
SGTM. I will make the changes to move GODEBUGCPU functionality into GODEBUG for Go 1.12.
