### ISSUE TITLE
cmd/vet: replace with go/analysis driver

### ISSUE THREAD

**Issue by alandonovan** [golang/go#28756]
This is a tracking issue for the task of migrating cmd/vet to the new go/analysis API.

- bring the vet fork up to date w.r.t. the few recent changes in cmd/vet
- ensure that cmd/vet command-line documentation is accurate
- update cmd/vendor, adding a script for this and future updates.
- change cmd/vet/all to use "go vet" instead of "go tool vet",
  and measure any performance impact on the builders.
  This requires investigating all deviations in cmd/vet/all diagnostics.
  The main issue here is github.com/golang/go/issues/27665.
  Most of the other differences result from "go vet" being more precise than "go tool vet".
- replace cmd/vet with a copy of vet-lite's short main.go file.

At that point, "go vet" will use the new driver.

**Comment by alandonovan** [comment]
Update:
- vet fork is up to date
- issue 27665 is fixed
- "go vet" is much slower than "go tool vet"; discussion at https://groups.google.com/d/msg/golang-dev/RitxzrSuuf0/Dj07MnFbAAAJ

**Comment by bcmills** [comment]
@alandonovan, is this landing for 1.12?

**Comment by alandonovan** [comment]
Yes, this issue is now resolved.
