### ISSUE TITLE
go install github.com/minio/mc command failed

### ISSUE THREAD

**Issue by pushpendra65** [golang/go#28758]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
tried to install - go install github.com/minio/mc

#### What did you expect to see?
No error

#### What did you see instead?
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

#### Does this issue reproduce with the latest release (go1.11.2)?
Yes

#### System details

```
go version go1.10 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pushpendra/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pushpendra/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ck/dxkk3h557xqdvqj8rcm82vkr0000gp/T/go-build411800021=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.10 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.10
uname -v: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
lldb --version: lldb-1000.11.37.1
  Swift-4.2
```

**Comment by agnivade** [comment]
This was fixed in 1.11 (https://github.com/golang/go/issues/25908). Are you sure this does not work in 1.11.2 too ?

**Comment by pushpendra65** [comment]
@agnivade I updated from 1.10.0 to 1.11.2. and it is giving the following error with 1.11.2 

# github.com/minio/mc/vendor/github.com/rjeczalik/notify
vendor/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:162:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:163:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal

**Comment by agnivade** [comment]
You probably have an existing installation of minio/mc. Please delete that, and `go get` again. If you see the error again, please file an issue on that repo. This does not look like a Go bug to me, and in any case, is a different issue than the title.

**Comment by mvdan** [comment]
I agree with @agnivade - you should figure this out with the package's upstream, as this doesn't look like a bug in Go itself. We can always reopen this issue, or file a new one, if there is a Go bug to fix after all.

**Comment by AbrarNitk** [comment]
I think this might be come because you are using earlier release, just checkout to 24d4c28aa965795b609e89bb94454e2d7ab1d26d commit hash and compile it again. It will work fine.
