### ISSUE TITLE
regex Windows panic MustCompile/MatchString

### ISSUE THREAD

**Issue by rvjc** [golang/go#28765]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sys\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Sys\User\Go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\sys\AppData\Local\Temp\2\go-build287238718=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

    package main

    import "fmt"
    import "regexp"

    var IsLetter = regexp.MustCompile(`^[a-zA-Z]+$`).MatchString

    func main() {

	    b := IsLetter("abc")
	    fmt.Println(b)
    }

### What did you expect to see?

Works on playground:

    true

### What did you see instead?

On Windows:

    panic: runtime error: slice bounds out of range

    goroutine 1 [running]:
    main.main()
          .../main.go:7 +0xbc

**Comment by mvdan** [comment]
In the file you posted, line 7 is an empty line. The program also seems to run fine on Linux.

**Comment by rvjc** [comment]
I must be going crazy.
I'm pretty sure I double-checked before issuing bug report.

But now I copied and pasted code and it ran successfully.

A possible explanation for original panic:

The original test code was pasted from the web and modified
It's possible there were some unruly characters lingering in the file.
This might explain the "empty line 7" which @mvdan spotted.

Anyway, all is good now.
Sincere apologies for inconveniencing you and thanks for assistance
