### ISSUE TITLE
`go get` command line option parsing b0rken

### ISSUE THREAD

**Issue by wknapik** [golang/go#28775]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
$
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/foo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/foo"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build362629505=/tmp/go-build -gno-record-gcc-switches"
$
</pre></details>

### What did you do?
```
$ go get -vu github.com/google/oauth2l
flag provided but not defined: -vu
usage: go get [-d] [-f] [-t] [-u] [-v] [-fix] [-insecure] [build flags] [packages]
Run 'go help get' for details.
$
```

### What did you expect to see?
Same result as calling `go get -v -u github.com/google/oauth2l`

### What did you see instead?
```
flag provided but not defined: -vu
usage: go get [-d] [-f] [-t] [-u] [-v] [-fix] [-insecure] [build flags] [packages]
Run 'go help get' for details.
```

**Comment by ALTree** [comment]
This is working as intended. From the `flag` package do:
```
The following forms are permitted:

-flag
-flag=x
-flag x  // non-boolean flags only
```

`-ab` means "the flag ab", not "the flags `a` and `b`".

**Comment by mvdan** [comment]
What @ALTree said. The `go` command doesn't use GNU-style flags.

**Comment by wknapik** [comment]
Well, I expected this exact response and was not disappointed.

`ls -a -l` [.](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)
