### ISSUE TITLE
doc: change Interface example to use best practices in "Effective Go"

### ISSUE THREAD

**Issue by benhoyt** [golang/go#28773]
Per [thread](https://groups.google.com/forum/#!topic/golang-dev/3rWjcJAE7zA) on golang-dev, I have a couple of comments about the code example in the [Interfaces section](https://golang.org/doc/effective_go.html#interfaces) of "Effective Go":

    type Sequence []int

    // ... Len, Less, and Swap methods ...

    // Method for printing - sorts the elements before printing.
    func (s Sequence) String() string {
        sort.Sort(s)
        str := "["
        for i, elem := range s {
            if i > 0 {
                str += " "
            }
            str += fmt.Sprint(elem)
        }
        return str + "]"
    }

It seems to me there are a couple of things that aren't good habits in this example, and if that's the case, that we shouldn't be showing them as examples in *Effective* Go:

1) Having a String() method modify the object (by sorting it in place). There's not actually a strict contract that disallows that, but I would definitely not expect that a String() method would modify the object under my feet. If it it's going to format it sorted, it should make a copy of the slice and sort the copy.

2) Appending to a string over and over in a loop. I'm not 100% sure how clever the compiler is, but won't this allocate a new string and copy the bytes each time around the loop, leading to O(N^2) behavior? (Quick test showing N^2 behaviour: https://play.golang.org/p/98e9uMsC384) I usually try to avoid appending to a string inside a loop like this for that reason, and instead append() to a slice of strings or write to a bytes buffer.

**Comment by bcmills** [comment]
>  I would definitely not expect that a String() method would modify the object under my feet.

To amplify that: in general I would expect a `String` method to be safe for concurrent use, in that multiple goroutines can invoke `s.String()` concurrently on the same receiver.

**Comment by bcmills** [comment]
> I usually try to avoid appending to a string inside a loop like this for that reason, and instead append() to a slice of strings or write to a bytes buffer.

As of 1.10, `strings.Builder` is a good default.

**Comment by robpike** [comment]
I would be OK with tweaking the Strings method to be better, but I do not want it to be concerned with all possible considerations and I really don't want to see strings.Builder there, much as I like that facility. See https://github.com/golang/go/issues/28782.

**Comment by benhoyt** [comment]
@robpike Fair enough about not having strings.Builder -- I'm okay with leaving the string `+=` for a simple example like this (particularly when the next section in *Effective Go* gets rid of it completely).

But modifying it by sorting in-place in a `String()` seems really wrong (and this isn't "fixed" below). I don't think that's "being concerned with all possible considerations" -- it rather seems a basic flaw in a `String()` method. Fixing that also wouldn't require any library functions, just the builtin `copy()` or `append()` functions.

**Comment by robpike** [comment]
Yes, the detail about overwriting the receiver should be fixed. The performance point is more nuanced. It is a useful pattern, although today it is a pattern better handled by library code, but then just calling the library means you don't see the pattern.

I will send a CL.
