### ISSUE TITLE
plugin: application complains about missing dll when importing package (Windows 386)

### ISSUE THREAD

**Issue by michael-obermueller** [golang/go#28789]
#### What did you do?
```
package main

import (
	"os"
	"plugin"
)

func main() {
	os.Exit(0)

	_, err := plugin.Open("")
	println(err)
}
```
go build Main.go
run the application

#### What did you expect to see?
No error. I know that Go plugins are not supported in windows but it is possible to import package plugin (stub implementation).

#### What did you see instead?
System Error window: The code execution cannot proceed because .DLL was not found. Reinstalling the program may fix this problem.

#### Does this issue reproduce with the latest release (go1.11.2)?
yes, reproducible with all releases from 1.8 - 1.11.2

#### System details

```
go version go1.11 windows/amd64
GOARCH="386"
GOBIN=""
GOCACHE="C:\Users\michael.obermueller\AppData\Local\go-build"
GOEXE=".exe"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\workspaces\go\workspace"
GOPROXY=""
GORACE=""
GOROOT="C:\workspaces\go\Go"
GOTMPDIR=""
GOTOOLDIR="C:\workspaces\go\Go\pkg\tool\windows_amd64"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
GOROOT/bin/go version: go version go1.11 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
lldb --version: lldb version 6.0.1
gdb --version: GNU gdb (GDB) 7.10.1
```

**Comment by agnivade** [comment]
Please kindly upload the _entire_ code. The current code, will always exit in the first line, not executing anything.

**Comment by alexbrainman** [comment]
> #### What did you expect to see?
> No error. I know that Go plugins are not supported in windows but it is possible to import package plugin (stub implementation).

Issue to track windows plugin implementation is #19282. If windows plugin is not implemented, what is the benefit to be able to import `plugin` package? If there is not benefit, then do not import `plugin` package.

Alex

**Comment by michael-obermueller** [comment]
My Go application is built for multiple platforms. This bug enforces me to define build constraints like `+build !windows`.

**Comment by PeterFeicht** [comment]
Merely importing the `plugin` package without actually using it should still not make the executable crash.

**Comment by alexbrainman** [comment]
> This bug enforces me to define build constraints like `+build !windows`.

I don't see a problem with that. Do you have better suggestion?

> Merely importing the `plugin` package without actually using it should still not make the executable crash.

`plugin` package is broken. If you import the package, you run any `init` function in it.

Alex

**Comment by michael-obermueller** [comment]
> I don't see a problem with that. Do you have better suggestion?
The problem is that it should not be necessary, the plugin package contains 3 files:
plugin
 |__ plugin.go
 |__ plugin_dlopen.go --> +build linux,cgo darwin,cgo
 |__ plugin_stubs.go --> +build !linux,!darwin !cgo

Both files 'plugin_dlopen.go' and 'plugin_stubs.go' define build constraints. The file 'plugin_stubs.go' is used for unsupported OS's like windows --> plugin.Open(...) should return an error (plugin: not implemented). 
This works for windows amd64 but not for 386 which IMHO is a bug.

Michael

**Comment by alexbrainman** [comment]
> This works for windows amd64 but not for 386 which IMHO is a bug.

@michael-obermueller please try https://go-review.googlesource.com/c/go/+/151139
 to see if it fixes your problem.

Thank you.

Alex

**Comment by michael-obermueller** [comment]
Thank you Alex, your change fixes the problem.

Michael

**Comment by alexbrainman** [comment]
> your change fixes the problem.

Thanks for checking. Now we will wait for https://go-review.googlesource.com/c/go/+/151139 to get submitted.

Alex
