### ISSUE TITLE
proposal: include metadata about modules in binaries

### ISSUE THREAD

**Issue by tsaarni** [golang/go#28784]
There are many scanners for finding known vulnerabilities (CVEs).  Typical scanner could be based on e.g. RPM index.

CVEs are reported also about go modules ([see example here](https://snyk.io/vuln?type=golang)) but due to static linking it is difficult to recognize if a given binary has known vulnerability.  

Go compiler could augment the binaries with metadata about included modules and their versions. 
 Implementers of vulnerability scanners could leverage this metadata for introducing support for go binary scanning.

**Comment by myitcv** [comment]
Dup of https://github.com/golang/go/issues/26404

https://go-review.googlesource.com/c/go/+/144220 has just been merged too
