### ISSUE TITLE
x/crypto/openpgp: infinite loop on unknown cipher type / key

### ISSUE THREAD

**Issue by jdevelop** [golang/go#28786]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build954256754=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

A simple test case to illustrate the problem:

```golang
package main

import (
	"bytes"
	"errors"
	"io"
	"io/ioutil"
	"testing"

	"golang.org/x/crypto/openpgp"
)

const (
	pass      = "passwordok"
	wrongPass = "passwordfailed"
	message   = "hello world"
)

var noSymmetric = errors.New("Symmetric not set")

func TestHelloWorld(t *testing.T) {
	var out = bytes.Buffer{}
	var in = bytes.NewReader([]byte(message))
	w, err := openpgp.SymmetricallyEncrypt(&out, []byte(pass), nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = io.Copy(w, in); err != nil {
		t.Fatal(err)
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}

	encryptedSrc := bytes.NewReader(out.Bytes())

	md, err := openpgp.ReadMessage(encryptedSrc, nil, func(keys []openpgp.Key, symmetric bool) ([]byte, error) {
		if !symmetric {
			return nil, noSymmetric
		}
		return []byte(wrongPass), nil
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	content, err := ioutil.ReadAll(md.UnverifiedBody)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != message {
		t.Fatalf("Expected %s actual %s", message, content)
	}
}
```

### What did you expect to see?

An error should be returned from `ReadMessage`

### What did you see instead?

An **infinite** loop.

**Comment by sashabaranov** [comment]
For me solution was to modify prompt function to return key only once, and when called second time return error.

This approach is inspired by openpgp's test suite: https://github.com/golang/crypto/blob/master/openpgp/read_test.go#L258

**Comment by seankhliao** [comment]
openpgp is frozen
