### ISSUE TITLE
x/tools/cmd/godoc: playground "Pop out" link on home page is broken

### ISSUE THREAD

**Issue by alandonovan** [golang/go#28793]
Using Chrome on Linux/X11, visit https://golang.org/.
Click the Pop-out button above the Playground. Nothing happens.
Click the browser' Reload button.
A modal dialog appears, saying "golang.org says server error, try again"

**Comment by opennota** [comment]
Chromium is affected too.

**Comment by andybons** [comment]
Duplicate of #28816

**Comment by opennota** [comment]
> #28793
> Duplicate of #28816

I think it's the other way around.

**Comment by broady** [comment]
Dupe of #28134.
