### ISSUE TITLE
cmd/go: reject module paths containing '@' during 'go mod init'

### ISSUE THREAD

**Issue by bcmills** [golang/go#28803]
Extracted from #28338.

The module path in a `go.mod` file does not contain the version, but users (especially newcomers) may try to `go mod init foo@v0.1.0` or `go mod init foo@latest` anyway.

We should detect that and fail with a helpful error message, just as we reject `pkg@version` syntax in other commands (like `go build`).

**Comment by DemonWav** [comment]
Working link to CL: https://go-review.googlesource.com/c/go/+/150018
