### ISSUE TITLE
cmd/go: go mod edit -module $module replaces empty string

### ISSUE THREAD

**Issue by myitcv** [golang/go#28820]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +8fa789b689 Thu Nov 15 19:27:13 2018 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes - also reproduces with tip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/dev/go"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/dev/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build662390965=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Here is a `cmd/go` testscript test that demonstrates the problem on tip:

```
env GO111MODULE=on

go mod init a.a/b/c
go mod edit -module x.x/y/z
cmpenv go.mod $WORK/go.mod.rename

-- $WORK/go.mod.init --
module a.a/b/c

go $goversion
-- $WORK/go.mod.rename --
module x.x/y/z

go $goversion
```

### What did you expect to see?

Success

### What did you see instead?

```
$ go test cmd/go -run=Script/mod_edit_me
go test proxy starting
go test proxy running at GOPROXY=http://127.0.0.1:45343/mod
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/mod_edit_me (0.04s)
        script_test.go:182:
            > env GO111MODULE=on
            > go mod init a.a/b/c
            [stderr]
            go: creating new go.mod: module a.a/b/c
            > go mod edit -module x.x/y/z
            > cmpenv go.mod $WORK/go.mod.rename
            [diff -go.mod +$WORK/go.mod.rename]
            -module ""
            +module x.x/y/z

             go 1.12

            FAIL: testdata/script/mod_edit_me.txt:5: go.mod and $WORK/go.mod.rename differ

FAIL
FAIL    cmd/go  1.069s
```

@bcmills - I've marked this as 1.12... but please refile as you see fit.

**Comment by oiooj** [comment]
@myitcv Good catch.
