### ISSUE TITLE
cmd/vet: go vet warns about unreachable panics

### ISSUE THREAD

**Issue by jech** [golang/go#28838]
go version go1.11.2 linux/amd64

I like to put panics in places that I know are unreachable.  Go vet complains.

For example, the following code yields an *unreachable code* warning:

```
package main

func main() {
	return
	panic("unreachable")
}
```

```

**Comment by ianlancetaylor** [comment]
I think it's entirely reasonable that a warning about unreachable code warns about unreachable code, even if that code is a call to `panic`.  You can disable the warning with `-unreachable=false`.
