### ISSUE TITLE
os: RemoveAll possible regression with empty path

### ISSUE THREAD

**Issue by mhilton** [golang/go#28830]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +14608976db Thu Nov 15 23:37:20 2018 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No - release 1.11.2 behaves as before

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mhilton/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mhilton/go"
GOPROXY=""
GORACE=""
GOROOT="/home/mhilton/opt/go"
GOTMPDIR=""
GOTOOLDIR="/home/mhilton/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build335628538=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

``` go
package main

import (
	"fmt"
	"os"
)

func main() {
	err := os.RemoveAll("")
	fmt.Printf("%v\n", err)
}
```

### What did you expect to see?
Go 1.11.2 has the output `<nil>` - indicating no error returned

### What did you see instead?
Tip has the output `invalid argument` - indicating syscall.EINVAL

**Comment by rogpeppe** [comment]
Even if it was decided that it's appropriate for os.RemoveAll to return nil, in this case, it should probably return an os.PathError rather than the unwrapped syscall error.

**Comment by ianlancetaylor** [comment]
We should not change this behavior.  Patches welcome.
