### ISSUE TITLE
x/tools/godoc/redirect: offer Gerrit/Rietveld CL disambiguation when needed

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28836]
Go's CL numbers as assigned by Gerrit have started to collide with the lower numbers in the sparse set returned by the old Rietveld code review system we used to use.

Our `https://golang.org/cl/NNNN` handler should render a disambiguation page when the CL exists in both.

/cc @bcmills @dmitshur @andybons @adg

**Comment by aclements** [comment]
Is there any way we could knock out the Rietveld CL numbers from Gerrit's numbering space?

**Comment by andybons** [comment]
> @andybons, could you talk to the Gerrit team about that?

Will do.

**Comment by andybons** [comment]
They can change the number to whatever we want in the future. Where do we want to start at now?

**Comment by bradfitz** [comment]
The problem is the Rietveld numbers were sparse and got very large. We don't want a dozen digits in our CL numbers. That's more painful than the annoyance cost or occasional collisions.

I suppose we could look for the largest early gap.

**Comment by dmitshur** [comment]
golang.org has been redeployed with the [CL 150057](https://golang.org/cl/150057) change applied, so short links like https://golang.org/cl/150057 are correctly pointing to Gerrit CLs now.

**Comment by dmitshur** [comment]
I believe this issue is now fully resolved by [CL 150057](https://golang.org/cl/150057), redeploying golang.org, and @andybons taking measures to prevent future Gerrit CL numbers from overlapping with existing Rietveld CLs. We won't need a CL disambiguation page. Closing to reflect reality (but feel free to re-open if I'm missing something, or there is more follow-up work to be done).

**Comment by bradfitz** [comment]
> and @andybons taking measures to prevent future Gerrit CL numbers from overlapping with existing Rietveld CLs. We won't need a CL disambiguation page.

I'm on that email thread and I haven't gotten any update from the Gerrit team.

Duplicates are still possible. They'll be rare, but possible.

I'd like Rietveld to mark all the numbers in https://go-review.googlesource.com/c/tools/+/150057/5/godoc/redirect/rietveld.go#36 as reserved so they'd never be handed out to us again.

Reopening until we do one of these: a disambiguation page, or modifying Gerrit.

**Comment by bcmills** [comment]
> I'd like Rietveld to mark all the numbers in […] as reserved

Do you mean Gerrit?

**Comment by bcmills** [comment]
Looks like we already missed the window on avoiding collisions:
https://codereview.appspot.com/152078
https://go-review.googlesource.com/c/go/+/152078

**Comment by dmitshur** [comment]
We just hit this again in https://github.com/golang/go/issues/29633 for CL 157099, which exists both in Gerrit and Rietveld. There are 837 more numbers [that follow](https://go-review.googlesource.com/c/tools/+/150057/5/godoc/redirect/rietveld.go#255), so we're going to continue hit the issue for a while. There haven't been any new updates on the Gerrit email thread.

> Our `https://golang.org/cl/NNNN` handler should render a disambiguation page when the CL exists in both.

We can query the Gerrit API to figure out if a Rietveld CL is also a Gerrit CL. I'll implement this and send a CL.

**Comment by dmitshur** [comment]
@gopherbot Please backport to Go 1.11.

**Comment by dmitshur** [comment]
Reopening for deploy of golang.org with the fix applied.

**Comment by dmitshur** [comment]
golang.org has been redeployed with the fix.

For example, https://golang.org/cl/157099 now displays a disambiguation page rather than immediately redirecting to Rietveld CL 157099, since a CL with that number exists in both systems.

**Comment by adg** [comment]
Nicely done.
