### ISSUE TITLE
documentation: highlight deprecated stuff

### ISSUE THREAD

**Issue by cn007b** [golang/go#28833]
Does it make sense to have background color highlight for deprecated stuff,
like [this](https://monosnap.com/file/nQCMbudwGC7Cffhk1uVxCIu9X3NL7T) instead of [this](https://monosnap.com/file/LkYLeFfqAV6L0kPajzgfMhakjrbF5H) because in glans it's possible to not pay attention.

**Comment by bontibon** [comment]
See #17056

**Comment by agnivade** [comment]
Thanks. Closing as duplicate. Please feel free to subscribe to the issue. Thank you.
