### ISSUE TITLE
Iterating slice of values and calling their method with pointer receiver behaves inconsistently

### ISSUE THREAD

**Issue by Kefaise** [golang/go#28844]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kefaise\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\kefaise\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kefaise\AppData\Local\Temp\go-build992843230=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
I tried to call method which use goroutine on all elements of slice. It didn't work, so I tried four different variations:

1. Slice of values, receiver is by pointer
2. Slice of values, receiver is by value
3. Slice of pointers, receiver is by pointer
4. Slice of pointers, receiver is by value

Only _slice of values, receiver is by pointer_ behave inconsistently. I am aware that calling goroutine inside loop requires copy of variables one will use inside it. However this may cause hard to find bugs when one change method to use pointer receiver, or start using goroutines inside method. Moreover goroutine is called in context of method, so one might expect that receiver is stable in closure, when he don't change it.

Program to reproduce this behaviour:
https://play.golang.org/p/DK0IdNnZMk5

### What did you expect to see?
Something similar to
<pre>
Pointer
foo0
foo6
foo2
foo3
foo4
foo5
foo9
foo1
foo7
foo8

bar1
bar2
bar4
bar5
bar0
bar3
bar6
bar7
bar9
bar8

Value
foo0
foo6
foo2
foo3
foo4
foo5
foo9
foo1
foo7
foo8

bar0
bar1
bar2
bar3
bar4
bar5
bar6
bar9
bar8
bar7
</pre>

### What did you see instead?
<pre>
Pointer
foo4
foo4
foo8
foo8
foo8
foo8
foo8
foo9
foo9
foo9

bar1
bar2
bar4
bar5
bar0
bar3
bar6
bar7
bar9
bar8

Value
foo0
foo6
foo2
foo3
foo4
foo5
foo9
foo1
foo7
foo8

bar0
bar1
bar2
bar3
bar4
bar5
bar6
bar9
bar8
bar7
</pre>

**Comment by AlexRouSg** [comment]
This is not a bug.

```
for _, txtValue := range textsValues {
	txtValue.printPointer(&wg)
}
```
Is equivalent to
```
var txtValue textHandler
for i := 0; i < len(textsValues); i++ {
        txtValue = textsValues[i]
	txtValue.printPointer(&wg)
}
```

When you take the pointer of `txtValue `, for the entire loop, it will be the same variable. Thus by the time the goroutine printed the value, it changed to something else as it's further along the loop.

**Comment by mvdan** [comment]
What @AlexRouSg said. There are plenty of articles on this subject online - for example, see https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables.
