### ISSUE TITLE
spec: Representability reversed examples (byte, rune)

### ISSUE THREAD

**Issue by bgadrian** [golang/go#28847]
I think I have found a small problem with the Specs page from the blog.

https://golang.org/ref/spec#Representability

### What did you expect to see?
> 'a'                rune        rune is an alias for int32, and 97 is in the set of 32-bit integers
97                   byte        97 is in the set of byte values
### What did you see instead?

> 'a'                 byte        97 is in the set of byte values
97                  rune        rune is an alias for int32, and 97 is in the set of 32-bit integers

**Comment by robpike** [comment]
The table is saying that `'a'` _can_ be represented by a `byte`, not that its default representation has byte type.

**Comment by bgadrian** [comment]
I understand now, sorry for the confusion.
