### ISSUE TITLE
Getting ERROR "import cycle not allowed" when import package ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [golang/go#28845]
import cycle not allowed
package github.com/abc/abc/a
  imports github.com/abc/abc/b
  imports github.com/abc/abc/a

**Comment by ALTree** [comment]
In Go, cyclic imports are not allowed. If package `a` imports package `b`, `b` cannot import `a`.

If you believe you're *not* doing any cyclic import, and the error you're getting is a compiler bug, please post a code reproducer that can be used to investigate the issue.

Closing here for now, but feel free to comment here if you think this is an actual Go bug, and we'll reopen the issue.

**Comment by Allenyn** [comment]
In Go, not allowing package circular import is too absolute .
