### ISSUE TITLE
Create a go help issue tracker like node.js help

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#28850]
I wasn't sure where to file this ticket, but if Google and the community could create a Golang-Help issue tracker that would be nice:

Here is the node.js repo:
https://github.com/nodejs/node

And here is the node.js help repo:
https://github.com/nodejs/help

I have this question and looking for expert advice:
https://stackoverflow.com/questions/53355954/import-subpackages-with-golang-by-importing-parent-dir

I would be nice to post a question to a help issue tracker.

**Comment by myitcv** [comment]
This is covered in https://github.com/golang/go/issues/23745, so closing this as a dup
