### ISSUE TITLE
x/build/cmd/gerritbot: copy abandon message to PR

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#28855]
When gerritbot closes a PR due to the Gerrit CL being abandoned, it should copy the message of the abandon step. There's often some rationale offered by whoever is abandoning it, and it should be provided to the GitHub user.

This especially happens with new contributors who are not aware of Gerrit, and who might have their CL abandoned for some reason like a proposal being declined. It's not nice to have them see their PR closed without explanation.

For example: https://github.com/golang/go/pull/28851#issuecomment-439705885

**Comment by dmitshur** [comment]
I've deployed and confirmed it works. You can see an example of an abandon message from Gerrit being copied to the original Pull Request here:

https://github.com/golang/scratch/pull/34#issuecomment-456948764

Thank you @oiooj for helping resolve this!
