### ISSUE TITLE
x/tools/cmd/guru: Callers seem broken in Go 1.11.2

### ISSUE THREAD

**Issue by dongfengkuayue** [golang/go#28853]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.2
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/usernameLibrary/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/username/go/src"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/username/go/src/xxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7m/cnr_fyw56jnf9rvr65jhnbnh0000gn/T/go-build227458918=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I typed :GoCallers in vim ,it reported "vim-go: guru: couldn't load packages due to errors: runtime/internal/sys, runtime, runtime/internal/atomic and 1 more".

### What did you expect to see?
the callers of a function.

### What did you see instead?
vim-go: guru: couldn't load packages due to errors: runtime/internal/sys, runtime, runtime/internal/atomic and 1 more

and it seemed to have parsing packages in $GOPATH/pkg/mod/...

**Comment by odeke-em** [comment]
Thank you for filing this bug @dongfengkuayue!

It would be nice to see perhaps the whole error mentioned in 
```
What did you see instead?
vim-go: guru: couldn't load packages due to errors: runtime/internal/sys, runtime, runtime/internal/atomic and 1 more
```

Kindly paging @alandonovan

**Comment by agnivade** [comment]
@dongfengkuayue - Could you mention the exact steps to get the error without vim-go being involved ? It would be great if you can upload a sample repo or show us a file which throws an error which `guru` is executed on it. Thanks.
