### ISSUE TITLE
cmd/compile: missing "slice bounds out of range" runtime panic for stringtobytes conversion of size <=32 unless variable escapes

### ISSUE THREAD

**Issue by RafaelTupynamba** [golang/go#28863]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Linux, Windows, macOS

</pre></details>

### What did you do?

https://play.golang.org/p/npT2x8ieAV4

### What did you expect to see?

panic: runtime error: slice bounds out of range

### What did you see instead?

No panic
Panic only happens if you uncomment last Println

**Comment by odeke-em** [comment]
Thank you for reporting this bug @RafaelTupynamba and welcome to the Go project!

I can reproduce this on Go1.9, Go1.10, Go1.11 and on tip aka Go1.12
```go
package main

import "fmt"

func main() {
	key := []byte("Hello")
	key = key[:16]
	fmt.Println(len(key))
	if false {
		fmt.Println(key)
	}
}
```
with `false` it'll print `16`
but on changing to `true` will rightfully panic on the line `key = key[:16]`

Kindly paging some folks from the compiler crew @randall77 @dr2chase @josharian  @griesemer

**Comment by dominikh** [comment]
Is this https://github.com/golang/go/issues/24163?

**Comment by martisch** [comment]
I do not think there is a spec violation, there is no guarantee how large the slice capacity for "key" will be after the conversion as long as the content fits.
