### ISSUE TITLE
cmd/go: "cannot find main module" when running 'go build' on a .go source file

### ISSUE THREAD

**Issue by greenpau** [golang/go#28867]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.11.2 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
$ go env

GOARCH="amd64"
GOBIN="/root/dev/go/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/dev/go/src/github.com/mholt/caddy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build980719409=/tmp/go-build -gno-record-gcc-switches"

```

### What did you do?

I am compiling `caddy`.

```
unset GO111MODULE
go get github.com/mholt/caddy/caddy
cd $GOPATH/src/github.com/mholt/caddy/
# enable go modules
export GO111MODULE=on
# generates go.mod and go.sum
go mod init
# download detected dependencies
go mod download
# build caddy
cd $GOPATH/src/github.com/mholt/caddy/caddy/
go build -v -x main.go
```

### What did you expect to see?

Successful compilation.

### What did you see instead?

This results in `go` not being able to find standard library modules, i.e. "bufio".

```
WORK=/tmp/go-build483698734
build github.com/mholt/caddy/caddy: cannot find module for path bufio
```

**Comment by mvdan** [comment]
Is your Go installation broken by any chance? What does `go list bufio` print? What if you do `go build main.go`, with a very simple program that imports `bufio`?

**Comment by greenpau** [comment]
> Is your Go installation broken by any chance?

@mvdan, it is unlikely. I took the latest from https://golang.org/dl/. It is just go binary does not look for the modules inside $GOROOT.

```
go list bufio
can't load package: package bufio: unknown import path "bufio": cannot find module providing package bufio
```

**Comment by greenpau** [comment]
@mvdan , specifically `go1.11.2.linux-amd64.tar.gz`

**Comment by mvdan** [comment]
Certainly seems like your install is confused or weird. The command works for me in module mode.

```
$ go env GOMOD
/home/mvdan/src/gunk/go.mod
$ go list bufio
bufio
```

/cc @bcmills

**Comment by greenpau** [comment]
@mvdan , I don't have GOMOD.

```
$ go env GOMOD

$
```

**Comment by greenpau** [comment]
GOMOD is only there if `GO111MODULE` is set.

**Comment by greenpau** [comment]
Here, the issue that `go` does not look for packages in `GOROOT`.

**Comment by mvdan** [comment]
If `go env GOMOD` is empty, you're not in module mode, so this issue should have nothing to do with modules.

Whatever environment you're in, `go list` should work with standard library packages. Have you tried other commands like `go list std` or `go list io`? What about building a simple program, like I explained above?

**Comment by greenpau** [comment]
@mvdan , the below shows the standard library modules. For now, I will just switch back to `1.10.5`.

```
$ go list std
archive/tar
archive/zip
bufio
...
```

**Comment by greenpau** [comment]
@bcmills, try taking a system where go was never present. Downlod the tar.gz file i mentioned above. Unpack it to /usr/local/go ... “tar xvzf” would do it automatically. ADD GOBIN GOROOT GOPATH.

I am not cloning from git. i literally download it, unpacking it, and using it.

**Comment by greenpau** [comment]
@bcmills, i will the entire process shorlty.

**Comment by greenpau** [comment]
@bcmills , @mvdan, it worked now! 😄  The issue was outdated clock.

I resolved the issue by running `ntpdate -s time.nist.gov`. For whatever reason the clock being behind (it is a brand new system) cause the issues above.

I guess one could set a clock to be -1day and return the `go build`. weird ...

**Comment by xiaoyaoyou** [comment]
don't set the $GOROOT to go install path but `{go-install-path}/libexec`, then append $PATH: `$PATH:$GOROOT/bin`

**Comment by aohanhongzhi** [comment]
maybe you should add a file named go.mod  in your project
https://blog.csdn.net/yuexiazhufeng/article/details/84570680
