### ISSUE TITLE
timeout for reverse proxy is not working

### ISSUE THREAD

**Issue by codexc** [golang/go#28876]
### What version of Go are you using (`go version`)?

go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

```
func newCustomerHostReverseProxy(target *url.URL, timeout int64) *httputil.ReverseProxy {
	director := func(req *http.Request) {
		req.URL.Scheme = target.Scheme
		req.URL.Host = target.Host

		if _, ok := req.Header["User-Agent"]; !ok {
			req.Header.Set("User-Agent", "")
		}
	}

	return &httputil.ReverseProxy{
		Director: director,
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout:   2000 * time.Millisecond,
				KeepAlive: 30 * time.Second,
				Deadline:  time.Now().Add(time.Duration(timeout) * time.Millisecond),
				DualStack: true,
			}).DialContext,
			TLSHandshakeTimeout: 10 * time.Second,
		},
	}
}
```

### What did you expect to see?
as the Deadline or Timeout reach,  reverse proxy should abandon the connection with the backend

### What did you see instead?
we let the backend api sleep for 5s before it responds,
no matter how long we set the timeout, the proxy wait for the backend until it responds

**Comment by bradfitz** [comment]
You're configuring how long the TCP dialing to the backend is allowed to take, not the HTTP part after the TCP connection is set up.
