### ISSUE TITLE
math/big: (*Rat).SetString("1234") not the same as big.NewRat(1234, 1)

### ISSUE THREAD

**Issue by damastes** [golang/go#28884]
### What version of Go are you using (`go version`)?
1.11.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?
```
func main() {
	var x, y big.Rat
	
	x = *big.NewRat(123456789, 1)
	y.SetString("123456789")
	
	fmt.Printf("%#v\n", x)
	fmt.Printf("%#v\n", y)
}
```
https://play.golang.org/p/yFKM2k6djNA

### What did you expect to see?
I would expect to see both structures be identical.
```
big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat{}}}
big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat{}}}
```
### What did you see instead?
While the same numerical value, they are different for the purposes of test assertion.
```
big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat{}}}
big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat(nil)}}
```

**Comment by ianlancetaylor** [comment]
As a side note, you should not write `x := *big.NewRat(...)`.  Shallow copies of `*big.Rat` values are not supported.  This will be more clearly documented in the upcoming 1.12 release (https://tip.golang.org/pkg/math/big/#Rat).

To address the main issue, you should compare `*big.Rat` values using the `Cmp` method.  The package makes no promise that values that compare as equal use the same internal representation.
