### ISSUE TITLE
Runtime futex cpu 100%

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#28880]
I found question，cpu is 100%.
go version go1.10.1 linux/amd64
top

41666 zhaoya    20   0  751568  51164  25840 S  99.3  2.4   0:14.36 main 

[zhaoya@localhost libs]$ strace -p 41666
strace: Process 41666 attached
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0xc420416548, FUTEX_WAKE, 1)      = 1
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0
futex(0x207a248, FUTEX_WAIT, 0, NULL)   = 0

[zhaoya@localhost libs]$ gstack 41666
......

Thread 2 (Thread 0x7f001bcc5700 (LWP 41667)):
#0  0x00000000009d0b93 in runtime.futex ()
#1  0x000000000099cf90 in runtime.futexsleep ()
#2  0x00000000020797f0 in runtime.sched ()
#3  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f001e876640 (LWP 41666)):
#0  0x00000000009d0b93 in runtime.futex ()
#1  0x000000000099cf1b in runtime.futexsleep ()
#2  0x000000000207a248 in runtime.m0 ()
#3  0x0000000000000000 in ?? ()
 
but，i don‘t konow cause of the issue.

**Comment by zhaoya881010** [comment]
Thread 1 (Thread 0x7f6009460700 (LWP 41932)):
#0  0x00007f601af60ce3 in select () from /lib64/libc.so.6
#1  0x00007f601a5b6f79 in CSendWorkThread::Run (this=0x7f601a8b1060 <g_SendWorkThread>) at connection_impl.cpp:1316
#2  0x00007f601a563477 in FBASE2::thread_function (pArg=0x7) at ../../../os/thread.cpp:38
#3  0x00007f601b63836d in start_thread () from /lib64/libpthread.so.0
#4  0x00007f601af6ab9f in clone () from /lib64/libc.so.6

**Comment by zhaoya881010** [comment]
41932 zhaoya    20   0 1032272  51644  26612 R 98.3  2.4  10:33.30 main

**Comment by agnivade** [comment]
Hi @zhaoya881010 - Thank you for raising the issue. Unfortunately, this is too little for us to investigate further. 

The issue template is not complete. We do not know what you did, there is no code, we do not know what you expected.

From the looks of it, it seems you do not know either.

I would request you to use the forums at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it is ideal for issues like these.

When you have a more concrete issue which seems like a bug in Go, then please file an issue with the _complete_ issue template. Thank you.
