### ISSUE TITLE
https://golang.org/cl/<gerrit change id> redirector is flaky 

### ISSUE THREAD

**Issue by paulzhol** [golang/go#28889]
Example: https://golang.org/cl/150159 is pointing to https://codereview.appspot.com/150159 (old review system?) instead of https://go-review.googlesource.com/c/go/+/150159.

**Comment by bontibon** [comment]
See #28881 and #28836.

**Comment by bradfitz** [comment]
Duplicate. Fixed already. Needs to be deployed.
