### ISSUE TITLE
x/tools/cmd/present: present tool authentication

### ISSUE THREAD

**Issue by sfmarques** [golang/go#28887]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sergiofm/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sergiofm/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build155955382=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I'm using present tool to create slides and configure my template for the slides.
### What did you expect to see?
Expected to have authentication
### What did you see instead?
It doesn't have authentication

**Comment by ianlancetaylor** [comment]
What kind of authentication?  Why should it be in the present tool itself?  It seems more appropriate to set up your own authentication in a separate program that just forwards to a local present tool.
