### ISSUE TITLE
cmd/cgo: nested structure has too much alignment padding

### ISSUE THREAD

**Issue by kdescoteaux** [golang/go#28896]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 windows/amd64
AND
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

AND 

set GOARCH="amd64"
set GOHOSTARCH="amd64"
set GOHOSTOS="darwin"
set GOOS="darwin"
</pre></details>

### What did you do?
The attached file is a minimal reproducible test case for a complicated set of nested includes in our codebase.  A "packed" structure that ends 'unaligned' is nested into an "unpacked" structure with a subsequent element requiring 8 byte alignment.   

### What did you expect to see?
I expected that only four bytes of padding would be inserted and be visible via fmt.Printf("%+v") resulting in a data structure that matched our external C code.

### What did you see instead?
An extra "invisible" 8 bytes of padding are inserted breaking interoperability

[main.txt](https://github.com/golang/go/files/2601658/main.txt)

**Comment by kdescoteaux** [comment]
Program output
`Unaligned struct requiring padding
sizes: inner = 0x10 outer = 0x20
offsets: elem2 0x8  elem3 0x18
outer dump    {inner:{elem1:<nil> elem2:4294967295} _:[0 0 0 0] elem3:18446744073709551615}
outer hex dump:
00000000  00 00 00 00 00 00 00 00  ff ff ff ff 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  ff ff ff ff ff ff ff ff  |................|

Aligned struct requiring padding
sizes: inner = 0x10 outer = 0x18
offsets: elem2 0x8  elem3 0x10
outer dump    {inner:{elem1:<nil> elem2:4294967295} elem3:18446744073709551615}
outer hex dump:
00000000  00 00 00 00 00 00 00 00  ff ff ff ff 00 00 00 00  |................|
00000010  ff ff ff ff ff ff ff ff                           |........|
`

**Comment by ianlancetaylor** [comment]
There is no way to represent a packed struct in Go, so the bug is that cgo is generating an incorrect struct rather than an error.

Slightly smaller test case.  The two lines should have the same numbers.  On amd64 this program currently prints

```
Go 24 16
C 16 16
```

```Go
package main

import (
	"fmt"
	"unsafe"
)

/*
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#pragma pack(push, _header, 1)

// Should have size of 8 + 4 = 0xc
typedef struct {
	void * elem1;
	uint32_t elem2;
} InnerNotAligned;

// Should have size of 8 + 8 = 0x10
typedef struct {
	void * elem1;
	uint64_t elem2;
} InnerAligned;

#pragma pack(pop, _header)

// Should have size of 0xc + 4 (pad) + 8 = 0x18
typedef struct {
	InnerNotAligned inner;
	// requires ONLY 4 pad bytes to align the next element
	uint64_t elem3;
} OuterNotAligned;

// Should have size of 0x10 + 8 = 0x18
typedef struct {
	InnerAligned inner;
	// requires no padding
	uint64_t elem3;
} OuterAligned;

void printSizes() {
	printf("C %zu %zu\n", offsetof(OuterNotAligned, elem3), offsetof(OuterAligned, elem3));
}
*/
import "C"

func main() {
	var notAligned C.OuterNotAligned
	var aligned C.OuterAligned
	fmt.Printf("Go %d %d\n", unsafe.Offsetof(notAligned.elem3), unsafe.Offsetof(aligned.elem3))
	C.printSizes()
}
```

**Comment by kdescoteaux** [comment]
I can't follow the gopherbot included link, but this is the issue referred to: https://go-review.googlesource.com/c/go/+/150602

**Comment by kdescoteaux** [comment]
Can this be considered for backport to 1.11 ?

**Comment by ianlancetaylor** [comment]
@gopherbot Please open an issue to  backport to 1.11.
