### ISSUE TITLE
cmd/doc: default view does not show methods

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#28906]
<pre>
$ go version
go version devel +14608976db Thu Nov 15 23:37:20 2018 +0000 linux/amd64
</pre>

If I run `go doc strings`, it shows exported functions but not methods:

<details><summary><code>go doc strings</code> Output</summary><br><pre>
% go doc strings
package strings // import "strings"

Package strings implements simple functions to manipulate UTF-8 encoded
strings.

For information about UTF-8 strings in Go, see
https://blog.golang.org/strings.

func Compare(a, b string) int
func Contains(s, substr string) bool
func ContainsAny(s, chars string) bool
func ContainsRune(s string, r rune) bool
func Count(s, substr string) int
func EqualFold(s, t string) bool
func Fields(s string) []string
func FieldsFunc(s string, f func(rune) bool) []string
func HasPrefix(s, prefix string) bool
func HasSuffix(s, suffix string) bool
func Index(s, substr string) int
func IndexAny(s, chars string) int
func IndexByte(s string, c byte) int
func IndexFunc(s string, f func(rune) bool) int
func IndexRune(s string, r rune) int
func Join(a []string, sep string) string
func LastIndex(s, substr string) int
func LastIndexAny(s, chars string) int
func LastIndexByte(s string, c byte) int
func LastIndexFunc(s string, f func(rune) bool) int
func Map(mapping func(rune) rune, s string) string
func Repeat(s string, count int) string
func Replace(s, old, new string, n int) string
func ReplaceAll(s, old, new string) string
func Split(s, sep string) []string
func SplitAfter(s, sep string) []string
func SplitAfterN(s, sep string, n int) []string
func SplitN(s, sep string, n int) []string
func Title(s string) string
func ToLower(s string) string
func ToLowerSpecial(c unicode.SpecialCase, s string) string
func ToTitle(s string) string
func ToTitleSpecial(c unicode.SpecialCase, s string) string
func ToUpper(s string) string
func ToUpperSpecial(c unicode.SpecialCase, s string) string
func Trim(s string, cutset string) string
func TrimFunc(s string, f func(rune) bool) string
func TrimLeft(s string, cutset string) string
func TrimLeftFunc(s string, f func(rune) bool) string
func TrimPrefix(s, prefix string) string
func TrimRight(s string, cutset string) string
func TrimRightFunc(s string, f func(rune) bool) string
func TrimSpace(s string) string
func TrimSuffix(s, suffix string) string
type Builder struct{ ... }
type Reader struct{ ... }
    func NewReader(s string) *Reader
type Replacer struct{ ... }
    func NewReplacer(oldnew ...string) *Replacer

BUG: The rule Title uses for word boundaries does not handle Unicode punctuation properly.
</pre></details>

There is no indication that (for example) Builder has a bunch of unexported methods.

In the package summaries on `godoc.org` and `golang.org/pkg` pages, exported methods are shown (but, like `go doc`, fields, constants and variables are omitted).

Perhaps `go doc` should use the same heuristics as `godoc.org` and include exported methods too.

**Comment by mvdan** [comment]
/cc @robpike as per https://dev.golang.org/owners/.

There's `go doc -all strings`, which does print methods, but it also prints documentation so the output is too large for a quick summary.

It's also interesting that its help line is `-all   show all documentation for package`. Reading that, it seems weird how it affects whether methods are shown as well.

**Comment by FiloSottile** [comment]
+1, I find the default `go doc` view extremely unhelpful on most packages, like `crypto/tls`, because most functionality is implemented in methods.

/cc @dmitshur

**Comment by rsc** [comment]
This was done intentionally in the design of go doc to avoid dumping too much. The default view shows you the top-level names in the package and then you can ask for lower things. I find it nice that go doc crypto/tls fits on one screen. If you want to know about the Conn methods, use go doc crypto/tls.Conn (or just go doc tls.Conn).

Given that go doc has had this design for quite a few releases, we're not going to change it now.

**Comment by ossie-git** [comment]
@rsc I can understand your reasoning.  Would it be possible to at least give the user a hint that there are methods not shown? For example, in the [github.com/patrickmn/go-cache](github.com/patrickmn/go-cache) library, there are dozens of methods.  The default behavior is:

```
$ go doc go-cache
package cache // import "github.com/patrickmn/go-cache"

const NoExpiration time.Duration = -1 ...
type Cache struct{ ... }
    func New(defaultExpiration, cleanupInterval time.Duration) *Cache
    func NewFrom(defaultExpiration, cleanupInterval time.Duration, items map[string]Item) *Cache
type Item struct{ ... }
```

It would be useful if go doc mentioned that there are methods.  For example:

```
$ go doc go-cache
package cache // import "github.com/patrickmn/go-cache"

const NoExpiration time.Duration = -1 ...
type Cache struct{ ... }
    func New(defaultExpiration, cleanupInterval time.Duration) *Cache
    func NewFrom(defaultExpiration, cleanupInterval time.Duration, items map[string]Item) *Cache
    // suppressed 46 methods
type Item struct{ ... }
    // suppressed 1 method
```
