### ISSUE TITLE
x/build/cmd/relui: pkgbuild produces an installer that installs to /usr/local/go/bin/go, no longer in PATH on os X mojave

### ISSUE THREAD

**Issue by b5** [golang/go#28901]
### What version of Go are you using (`go version`)?
go 1.11.2 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/b5/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/b5/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6p/sjn8bct92397mbgwmwwvcb4h0000gn/T/go-build195699704=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Ran the go .pkg installer downloaded from golang.org. Installer completes successfully. I then moved over to the command line & ran: 
```shell
$ which go
go not found
```

### What did you expect to see?
I was _hoping_ to see `/usr/local/go/bin/go`, or for some magic created by `pkgbuild/productbuild` to symlink `/usr/local/go/bin/go` -> `/usr/local/bin/go`. but alas, nope. This problem only seems to exist on os x Mojave (as far as I can tell).

### What did you see instead?
`go not found`

My guess is the fix will land [here](https://github.com/golang/build/blob/790500f5933191797a6638a27127be424f6ae2c2/cmd/release/releaselet.go)

**Comment by agnivade** [comment]
See https://golang.org/doc/install#macos.

You have to restart any existing Terminal sessions for the $PATH changes to take effect. Have you done that ?

**Comment by b5** [comment]
Apologies for the delay, yes I have / did create a new session at the time. $PATH changes are present, the issue is the `go` tool itself isn't available.

**Comment by agnivade** [comment]
If the $PATH changes are present, I fail to see how the go tool isn't available. Can you dump the output of $PATH variable ?

**Comment by dmitshur** [comment]
I spotted this issue only recently, and wanted to follow up here. Also CC @golang/release. (I realize it's from 2018 so it might not be relevant to you or not something you can easily verify now.)

@b5 The macOS Go installer does have a mechanism to make /usr/local/go/bin/go available in $PATH: it writes to a [special directory](https://www.manpagez.com/man/8/path_helper/) `/etc/paths.d` a file with the content `/usr/local/go/bin` (see [buildrelease.go:371](https://cs.opensource.google/go/x/build/+/master:internal/task/buildrelease.go;l=371-373;drc=cc3a690bf817623b6036c0b956468f031c88e650)). If that file (named "go") is present in your /etc/paths.d directory, that means the installer worked as expected. If it's there but `which go` still doesn't find `/usr/local/go/bin/go`, it'd be useful to also know what terminal + shell you're using and if its configuration does something that might override path_helper picking up /etc/paths.d entries. Thanks.

You also mentioned this is only happening on macOS Mojave (10.14). If it's not a problem on newer macOS versions, then this problem won't apply after that macOS version [stops being supported](https://tip.golang.org/doc/go1.21#darwin).
