### ISSUE TITLE
os: TestRemoveAllDot failing on Plan 9

### ISSUE THREAD

**Issue by 0intro** [golang/go#28903]
CL [150497](https://golang.org/cl/150497) enabled TestRemoveAllDot on "noat" (see [removeall_noat.go](https://github.com/golang/go/blob/fe562cebf1/src/os/removeall_noat.go)) systems (including Plan 9).

This test is failing on Plan 9.

```
--- FAIL: TestRemoveAllDot (0.00s)
    removeall_test.go:235: RemoveAll succeed to remove .
FAIL
FAIL	os	2.055s
```

See https://build.golang.org/log/62555ab829ee330629c6189fef3507411e657a55

**Comment by mattn** [comment]
Sorry, OT. Seems that the link /c/150621 does not point to go-review.

**Comment by 0intro** [comment]
I think there is some kind of issue with the golang.org redirect. The direct link works: https://go-review.googlesource.com/c/go/+/150621

**Comment by agnivade** [comment]
redirect issue - https://github.com/golang/go/issues/28836
