### ISSUE TITLE
doc: code.html page assumes GOPATH is not a list

### ISSUE THREAD

**Issue by matthewvcarey1** [golang/go#28905]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/home/matthew/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matthew/go:/usr/share/go1.4/contrib"
GORACE=""
GOROOT="/usr/lib64/go1.4"
GOTOOLDIR="/usr/lib64/go1.4/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
</pre></details>

cat /etc/issue
Welcome to openSUSE Tumbleweed 20181103

### What did you do?

Use the documentation page https://golang.org/doc/code.html to try and set up and use go
to run initial examples

The documentation assumes that the go env GOPATH returns a single path not a list of paths.

go env GOPATH
/home/matthew/go:/usr/share/go1.4/contrib

This means that passages like this do not work.

> To compile and run a simple program, first choose a package path (we'll use github.com/user/hello) > and create a corresponding package directory inside your workspace:
>
> $ mkdir $GOPATH/src/github.com/user/hello

An obvious workaround in my case is to use sed but it would make the documentation page less readable.

$ mkdir $(echo "$GOPATH" | sed 's/:.*//g')src/github.com/user/hello

**Comment by agnivade** [comment]
The documentation explicitly mentions how to set a GOPATH here - https://golang.org/doc/code.html#GOPATH and goes forward with that assumption.

Technically, the documentation is correct in that regard.

Maybe we can add another line saying that GOPATH can have multiple values. But given the fact that we are sunsetting GOPATH, I wouldn't worry about adding further corner cases to it.

**Comment by bradfitz** [comment]
(People who like this bug also like #18119)

**Comment by forskning** [comment]
This is originally (some later modifications added) of what I wanted a Wiki page to look like.

https://nurmi-labs.blogspot.com/p/filetreedoc.html

**Comment by forskning** [comment]
R.C. once wrote about something like $GOROOT/HACKING.md (to match src/runtime/HACKING.md and maybe others), maybe such (circa 2017) consideration should be revisited, as that content could go in such an .md file.

**Comment by bcmills** [comment]
At this point I don't think it's worth the effort to update all of our tutorial content work with multiple-element `GOPATH`s: the use-cases for them are specific to GOPATH mode and will hopefully go away soon anyway (#30228, #4719).
