### ISSUE TITLE
misc/cgo/testshared: TestGoPathShlibGccgo fails on Raspbian/arm32

### ISSUE THREAD

**Issue by pavulon18** [golang/go#28919]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.7.4 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Unknown.  I am trying to compile go1.11.2

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build017079581=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?
git clone https://go.googlesource.com/go
git checkout go1.11.2
cd src
./all.bash

### What did you expect to see?
All passing tests, as per the instructions.

### What did you see instead?
all passing upto this point:

```
##### ../misc/cgo/testshared
--- FAIL: TestGoPathShlibGccgo (0.27s)
    shared_test.go:67: executing go install -installsuffix=5577006791947779410 -compiler=gccgo -buildmode=shared -linkshared depBase failed exit status 1:
        src/depBase/dep.go:8:2: cannot find package "os" in any of:
                /home/jim/golang/go/src/os (from $GOROOT)
                /tmp/testshared432156425/src/os (from $GOPATH)
        src/depBase/dep.go:9:2: cannot find package "reflect" in any of:
                /home/jim/golang/go/src/reflect (from $GOROOT)
                /tmp/testshared432156425/src/reflect (from $GOPATH)
--- FAIL: TestTwoGopathShlibsGccgo (0.05s)
    shared_test.go:67: executing go install -installsuffix=5577006791947779410 -compiler=gccgo -buildmode=shared -linkshared depBase failed exit status 1:
        src/depBase/dep.go:8:2: cannot find package "os" in any of:
                /home/jim/golang/go/src/os (from $GOROOT)
                /tmp/testshared432156425/src/os (from $GOPATH)
        src/depBase/dep.go:9:2: cannot find package "reflect" in any of:
                /home/jim/golang/go/src/reflect (from $GOROOT)
                /tmp/testshared432156425/src/reflect (from $GOPATH)
FAIL
exit status 1
FAIL    _/home/jim/golang/go/misc/cgo/testshared        159.391s
2018/11/21 22:22:53 Failed: exit status 1

##### ../misc/cgo/testplugin
PASS
something
1.5
2018/11/21 22:22:56 FAILED
```

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
It looks like you have gccgo installed but not the gccgo libraries.  Does it work to run `go build -compiler=gccgo hello.go` with some simple hello.go file?

**Comment by pavulon18** [comment]
I followed the instructions listed here and got a working setup installed.  I'm not entirely sure that I can obtain the information you are requesting without removing the working copy.

**Comment by ianlancetaylor** [comment]
If it's working for you, that's fine, and there is nothing for us to do.  Thanks.
