### ISSUE TITLE
git: did master change recently?

### ISSUE THREAD

**Issue by kevinburke** [golang/go#28915]
Just now, I ran "git pull origin master" on `git@github.com:golang/go` and was asked to do a merge commit. It looks like the two parents are ae65615fd8 and 72496e35ce. 

I would have anticipated that the remote master would move in a straight line, eg I would always be able to pull the latest changes and never need to merge in whatever was previously pulled from it. I don't pull from any other source nor do I commit changes to master.

**Comment by adamdecaf** [comment]
Yes, see https://groups.google.com/forum/m/#!topic/golang-dev/8JmYrD3DWY0

**Comment by kevinburke** [comment]
Ah, okay, will post here for those searching for the answer on Google.

> Heads up: we've written the past 6 days of git history for https://github.com/golang/go/issues/28899 (a big binary was checked in 6 days ago)

> If you use "git sync", this doesn't affect you. (I just checked)

> If you don't use git sync, you presumably know how to use git, but this will blow away your local work and get you back on the train:

>          $ git fetch origin master && git reset --hard FETCH_HEAD
