### ISSUE TITLE
syscall/js: Compiler doesn't check implemented type

### ISSUE THREAD

**Issue by sternix** [golang/go#28913]
### What version of Go are you using (`go version`)?

<pre>
$ go version devel +b44cd15464 Tue Nov 20 16:17:17 2018 +0000 freebsd/amd64
</pre>

### Does this issue reproduce with the latest release?
No only master

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="wasm"
GOBIN=""
GOCACHE="/home/sternix/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="js"
GOPATH="/home/sternix/go"
GOPROXY=""
GORACE=""
GOROOT="/home/sternix/src/go"
GOTMPDIR=""
GOTOOLDIR="/home/sternix/src/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build888035731=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
write simple test program

<pre>
package main

import "syscall/js"

type Wrapper interface {
        JSValue() js.Value
}

type x struct {
        js.Value
}

// first check
func newX() Wrapper {
        return &x {}
}

func main() {
        // second check
        var _ Wrapper = newX()
}
</pre>

and compiled with

export GOARCH=wasm GOOS=js
go build -o abc.wasm abc.go 

### What did you expect to see?
with go 1.11.2 i have
./abc.go:13:9: cannot use x literal (type *x) as type Wrapper in return argument:
        *x does not implement Wrapper (missing JSValue method)

### What did you see instead?
go version devel +b44cd15464
i dont have any error
Compiled successfully

**Comment by cherrymui** [comment]
> *x does not implement Wrapper (missing JSValue method)

Why? Type `x` embeds `js.Value`, which does have `JSValue` method.

**Comment by sternix** [comment]
Thanks @cherrymui this is my fault i read 1.11.2 docs

https://golang.org/pkg/syscall/js/

which hasn't Value.JSValue

but tip has  Value.JSValue

https://tip.golang.org/pkg/syscall/js/#Value.JSValue

Thanks for correction.
