### ISSUE TITLE
misc/wasm: Support Go function call javascript Promise function

### ISSUE THREAD

**Issue by crossle** [golang/go#28911]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE=
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

 js.Global().Call(javascript promise function ) how to get the value? no method get a javascript promise or async wait result

**Comment by crossle** [comment]
@neelance Any method on current version?

**Comment by sternix** [comment]
I want native Promise type too, but in golang source tree i find Promise as

https://github.com/golang/go/blob/master/src/net/http/roundtrip_js.go#L91

**Comment by crossle** [comment]
`fatal error: all goroutines are asleep - deadlock!`
If Js call a golang function, it's need a callback get the result, if add a golang call js function on the callback use Await, fatal error

**Comment by crossle** [comment]
The main code is this function, it return called by js function  https://github.com/crossle/libsignal-protocol-go/commit/a88f51843e29e5de124dd9b66a14abf0abea83d8#diff-7ddfb3e035b42cd70649cc33393fe32cR48

**Comment by neelance** [comment]
Please post a concise and easily reproducible example.

**Comment by crossle** [comment]
Clone https://github.com/crossle/libsignal-js-client, run `goexec 'http.ListenAndServe(":8080", http.FileServer(http.Dir(".")))'`,
first click Run Run1 button, and last click Run2 button, it'll call https://github.com/crossle/libsignal-protocol-go/commit/a88f51843e29e5de124dd9b66a14abf0abea83d8#diff-7ddfb3e035b42cd70649cc33393fe32cR48

**Comment by neelance** [comment]
There is no Go code in the repository you linked. This is not a concise example of your issue.

Documentation of https://golang.org/pkg/syscall/js/#NewCallback (already mentioned above):

> As a consequence, if one callback blocks this goroutine, other callbacks will not be processed. A blocking callback should therefore explicitly start a new goroutine.

Did you already consider this?

**Comment by crossle** [comment]
OK, thanks, i have to start a new goroutine

**Comment by crossle** [comment]
But I wanna wait sync function, if have to use go routine I think it useless
