### ISSUE TITLE
reflect  can not write a func into a  interface  func!

### ISSUE THREAD

**Issue by zhuxiujia** [golang/go#28910]
I want to achieve a similar Java dynamic proxy，But golang there is a design flaw.
<pre>
package main
import (
	"reflect"
	"fmt"
)
type A interface {
	Print() string
}
func main() {
	//proxy A interface
	var printFunc = func() string {
		return "hello"
	}
	var a A
	var v = reflect.ValueOf(&a)
	//it code will "panic: reflect: Method on nil interface value"
	// i want to write a func,but it will painc,Method(0) Should be return a reflect.Value,but not!
	var methodValue = v.Elem().Method(0)
	methodValue.Set(reflect.ValueOf(printFunc))
	fmt.Println("proxy interface success")
}
</pre>

**Comment by bradfitz** [comment]
Yeah, what @mvdan said. The reflect package is supposed to let you do things the language can do.
