### ISSUE TITLE
crypto/tls: Client-side certificate doesn't work with tip

### ISSUE THREAD

**Issue by anacrolix** [golang/go#28925]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ae65615 Wed Nov 21 00:10:38 2018 +0000 linux/amd6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

A tls.Config containing a single client-side certificate fails with remote error: unknown certificate on the recent go version. With release (1.11), this doesn't happen. Setting tls max version 1.2 doesn't seem to help. May be related to #28779.

**Comment by agnivade** [comment]
Hi @anacrolix - Can you provide us with a reproducible code sample ? It would help us a lot to quickly debug this issue.

**Comment by anacrolix** [comment]
I suspect the author of recent changes to crypto/tls client-side handshakes will be best equipped. I don't have the time at present to isolate any more than I have above.

**Comment by FiloSottile** [comment]
No need to isolate it further, but I will need more details to debug this. What's the config? What certificate? Is the server public? If the server is a Go server, what config and version?

**Comment by anacrolix** [comment]
```
var (
	confluenceTlsConfig = &tls.Config{
		// InsecureSkipVerify: true,
	}
	confluenceHttpTransport = &http.Transport{
		TLSClientConfig: confluenceTlsConfig,
	}
	confluenceHTTPClient = &http.Client{
		Transport: confluenceHttpTransport,
	}
)

func setPrivateConfluenceTlsConfig() {
	confluenceTlsConfig.ServerName = "localhost"
	// confluenceTlsConfig.MaxVersion = tls.VersionTLS12
	confluenceTlsConfig.RootCAs = func() *x509.CertPool {
		ret := x509.NewCertPool()
		b, err := ioutil.ReadFile("private.pem")
		expect.Nil(err)
		expect.Ok(ret.AppendCertsFromPEM(b))
		return ret
	}()
	confluenceTlsConfig.Certificates = func() []tls.Certificate {
		cert, err := tls.LoadX509KeyPair("private.pem", "private.pem")
		expect.Nil(err)
		return []tls.Certificate{cert}
	}()
}
```
`private.pem` is a self-signed certificate. The server is public, it's a Haskell warp-tls server. If I build the client side (in Go) with 1.11, it works fine. With go +ae65615 it does not. The failing call is a `"golang.org/x/net/websocket".DialConfig` with the above TLS config.

**Comment by FiloSottile** [comment]
Thank you for the extra info! Can you share the address of the server so I can test it?

**Comment by anacrolix** [comment]
You may run it yourself, it's https://github.com/anacrolix/transcoder. I believe you can just do `stack run` from the directory (with stack installed, Haskell entails). I'll also email you the private address of an instance. Thanks.

**Comment by anacrolix** [comment]
This worked, thanks.
