### ISSUE TITLE
x/tools/cmd/goimports: better understanding of failure to update imports

### ISSUE THREAD

**Issue by theckman** [golang/go#28935]
I'm using `goimports` with the `go version go1.11.2 darwin/amd64` toolchain. I've hit a case where `goimports` isn't adding imports when I'd expect it to, and I'm trying to inspect why that is. I am not using modules, and the project is within my `GOPATH`. The import I'm trying to add is also within the GOPATH, and is actually within the same git repo.

Without the import added, the build failure (via `go test .`) is:

```
./case_test.go:13:8: undefined: mockaccounts
```

Once I manually add the import the tests pass just fine. I'm trying to understand what's causing `goimports` to be unsure what package to add. I've tried to look for any packages that have functions with similar methods, to no avail. 

Does anyone know of a good way to figure out why `goimports` isn't adding my import.

**Comment by myitcv** [comment]
@theckman - do you think there is a bug here? If so, please can you complete the issue template with a small repro? The output of `go env` is particularly significant in this case.

Else if this is more of a general question, then please can we move this to another forum: https://github.com/golang/go/wiki/Questions?

Thanks

**Comment by josharian** [comment]
This could be read as a feature request for a verbose flag to goimports.

**Comment by heschik** [comment]
It already has one.

@theckman, please run goimports -v and attach the results.

**Comment by theckman** [comment]
@myitcv it's an internal application, getting a repro ready would require a bit of work. I can maybe focus on that once I've some spare cycles. Sucks because I want to open source it eventually...

This is more of a feature request. I don't know if there's a bug present because `goimports` hasn't given me enough introspection ability. At face-value it's not behaving as expected.

@josharian there is one, but hopefully its output will be more meaningful to @heschik than it has been to me:

```
2018/11/26 11:11:59.230589 fixImports(filename="case_test.go"), abs="/Users/theckman/go/src/stash.corp.netflix.com/core/halp2/poller/cases/case_test.go", srcDir="/Users/theckman/go/src/stash.corp.netflix.com/core/halp2/poller/cases" ...
2018/11/26 11:11:59.231442 importPathToNameGoPathParse("stash.corp.netflix.com/core/halp2/test/mocks", srcDir="/Users/theckman/go/src/stash.corp.netflix.com/core/halp2/poller/cases") = "mocks", <nil>
2018/11/26 11:11:59.235594 scanning /Users/theckman/.gimme/versions/go1.11.2.darwin.amd64/src
2018/11/26 11:11:59.242998 scanned /Users/theckman/.gimme/versions/go1.11.2.darwin.amd64/src
2018/11/26 11:11:59.243031 scanning /Users/theckman/go/src
2018/11/26 11:11:59.243075 open /Users/theckman/go/src/.goimportsignore: no such file or directory
2018/11/26 11:11:59.243097 Error statting ignored directory: stat /Users/theckman/go/src/v: no such file or directory
2018/11/26 11:11:59.243114 Error statting ignored directory: stat /Users/theckman/go/src/mod: no such file or directory
2018/11/26 11:11:59.319635 scanned /Users/theckman/go/src
```

**Comment by theckman** [comment]
Yep, that appears to be it. I don't recall ever having had an issue before with the package name not matching the folder name. Especially because I've used things like `github.com/mitchellh/go-homedir`.

Have I just been lucky?

**Comment by heschik** [comment]
It doesn't need to be an exact match but it does need to contain the package name. go-homedir contains homedir, but mocks/poller/accounts does not contain mockaccounts. (mock/accounts might work today but I wouldn't advise relying on it.)

This is WAI. It's not feasible to load the real package name from every directory in $GOPATH. I suppose we could add something to the log like "looking for directory named mockaccounts" but the real matching rules are pretty complicated.

**Comment by theckman** [comment]
@heschik where is this documented?

**Comment by heschik** [comment]
I'm not aware of anything that would go into this much detail. File a new issue and ask bradfitz, I guess.
