### ISSUE TITLE
cmd/dist: linux/riscv64 listed as supported platform

### ISSUE THREAD

**Issue by vcabbage** [golang/go#28944]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +048c9164a0 Sat Nov 24 23:55:07 2018 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, introduced in 1.11.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

Ran `go tool dist list`

### What did you expect to see?

Only supported GOOS/GOARCH combinations listed.

### What did you see instead?

`linux/riscv64` listed even though it hasn't been fully implemented.

Added in https://golang.org/cl/118618. Appears it may be needed for the development of the RISC-V port but it doesn't seem as though it should be included in `go tool dist list` since that's documented to "list all supported platforms".

**Comment by ALTree** [comment]
Milestoning as 1.13 since the riscv GOARCH was introduced the previous development cycle (1.11), so this `dist list` issue it's not something that needs to be acted upon for the 1.12 release.

It's not clear if `dist list` is supposed to print all the reserved `GOOS/GOARCH` pairs (and in this case it's fine to list `riscv64`), or just the platforms where Go is actually working.

**Comment by tklauser** [comment]
See #27532 for the state of  `riscv64` support. https://golang.org/cl/118618 was already sent so the Go tooling can be used to auto-generate files for `linux/riscv64` in `golang.org/x/sys/unix` (https://golang.org/cl/133735).

**Comment by bradfitz** [comment]
I suppose we could have another `incomplete` map in `dist` alongside the cgo one and then filter out some ports in `dist list`.

**Comment by ncw** [comment]
I discovered this when trying to compile things with go1.12beta1

This problem has broken these tests which use `go tool dist list` to find all the valid architectures to test compilation:

https://github.com/a8m/tree/blob/3cf936ce15d6100c49d9c75f79c220ae7e579599/compileall.sh#L1-L14

So fixing `go tool dist list` to only emit GOOS/GOARCH which can be compiled would get my vote!

**Comment by ncw** [comment]
I decided to work around this problem by running `go tool compile -V` first to see if the architecture was supported before attempting a compile on a given GOOS/GOARCH pair.

https://github.com/a8m/tree/blob/6a0b80129de45f91880d18428b95fab29df91d7e/compileall.sh#L13-L21
