### ISSUE TITLE
x/build/cmd/gopherbot: don't add reviewers if a CL has the wait-release hashtag

### ISSUE THREAD

**Issue by mvdan** [golang/go#28945]
Take for example https://go-review.googlesource.com/c/go/+/151197. I mailed this during the freeze with the `wait-release` hashtag, precisely because I don't want to bother other contributors and reviewers until the tree reopens.

This is futile though, as Gobot proceeds to ping a dozen people. It has happened on a bunch of CLs I've sent this weekend, and I worry I've been spamming people.

I presume that gerritbot should also not assign reviewers to CLs with `DO NOT REVIEW`. I'm not sure if that is implemented already.

/cc @andybons @dmitshur @bradfitz

**Comment by dmitshur** [comment]
What's the reason to close this, is it no longer something that's worth doing?

It seems very easy to implement. The relevant code already has hashtags, so it just needs to check for "wait-release" too:

https://cs.opensource.google/go/x/build/+/master:cmd/gopherbot/gopherbot.go;l=2089-2092;drc=fdf5df99021c2e5844fcab5b78c1423d8c47f1e9 

> [...] should also not assign reviewers to CLs with `DO NOT REVIEW`. I'm not sure if that is implemented already.

This part seems to be done: https://cs.opensource.google/go/x/build/+/master:cmd/gopherbot/gopherbot.go;l=2098-2100;drc=fdf5df99021c2e5844fcab5b78c1423d8c47f1e9.

**Comment by mvdan** [comment]
I tend to close old issues that I don't have strong feelings about and don't seem to be heading anywhere, as a general rule - it's not particular to just Go. Ultimately, this was a suggested change to avoid noise for the team, so it doesn't really affect me much at all.

Happy to keep it open if you still find it a useful suggestion.
