### ISSUE TITLE
unicode: generated comments have redundant information

### ISSUE THREAD

**Issue by wselwood** [golang/go#28954]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?
Looked at the documentation for the Unicode package. The package variables part contains some redundant information in the category descriptions.

https://golang.org/pkg/unicode/#pkg-variables

When I look at the comments there I have to go away and look up what the category descriptions are so  I know which category I need. It would be much better to have the category description included in the comments.

**Comment by wselwood** [comment]
I've made a fix for this. I'll send along a CL shortly.

**Comment by andybons** [comment]
@robpike
