### ISSUE TITLE
net: IPMask docs aren't great

### ISSUE THREAD

**Issue by bradfitz** [golang/go#28957]
The docs for `net.IPMask` say:

https://golang.org/pkg/net/#IPMask

> An IP mask is an IP address.
>
> `type IPMask []byte`

That's, uh, pretty brief.

We should say more because as-is my first reaction would be, "Well, then why don't I juse use an IP address?"

For Go 1.13 at least, but Go 1.12 would be fine too.

/cc @ianlancetaylor @mikioh

**Comment by ianlancetaylor** [comment]
Honestly I'm not sure why we need `IPMask` in the net package at all.  If you don't happen to be writing a router IP masks are uninteresting.

Not that we shouldn't write better docs as long as we have it.

**Comment by viswesr** [comment]
Is the following doc OK for IP Mask ?
> **IPMask**
> IP mask is a bit-mask corresponding to an IP address (to support subnets), a slice of bytes. Functions in this package accept either 4-byte or 16-byte slices as input

I can send a CL if the above doc is fine. Thanks.

**Comment by ianlancetaylor** [comment]
@viswesr Thanks, but I think we can do better.  The docs should be brief and to the point.  What is the point of an `IPMask`?  Why would someone want a value of that type?

**Comment by jdreystadt** [comment]
Looking through the net package, IPMask is the return type for DefaultMask which is a function on the IP type. As a total newbie to Go, but an serious old-timer with TCP/IP, the concept of default masks goes all the way back to the early days of IP, when address allocation was being done with the concept of Class A, Class B and Class C address ranges. This is seriously out of date. But I am sure that this is what this function is about. Consider:

package main

import "fmt"
import "net"

func main() {
	classAIP := net.IP([]byte{40, 40, 1, 1})
	fmt.Println("IP Address ", classAIP.String(), " has default mask of ", classAIP.DefaultMask())
	classBIP := net.IP([]byte{188, 40, 1, 1})
	fmt.Println("IP Address ", classBIP.String(), " has default mask of ", classBIP.DefaultMask())
	classCIP := net.IP([]byte{242, 40, 1, 1})
	fmt.Println("IP Address ", classCIP.String(), " has default mask of ", classCIP.DefaultMask())
}
Result is:
IP Address  40.40.1.1  has default mask of  ff000000
IP Address  188.40.1.1  has default mask of  ffff0000
IP Address  242.40.1.1  has default mask of  ffffff00

I agree that this should be removed, both the type IPMask and the function DefaultMask. This was never useful and refers to concepts no longer in use.

As to documentation for IPMask in the near term, how about

An IPMask is used to determine if a remote IP address is on the same subnet as a local IP address. This is done by doing an XOR of the two IP addresses and then masking the result the IPMask. If the result after the masking is non-zero, then the two IP addresses are in different subnets.
