### ISSUE TITLE
cmd/compile: error line:col information points to wrong function parameter

### ISSUE THREAD

**Issue by yansal** [golang/go#28968]
### Does this issue reproduce with the latest release?
Yes

### What did you do?
https://play.golang.org/p/6PRJL3-x2lO

### What did you expect to see?
An error like `prog.go:8:2: cannot use bad (type func() func()) as type func() in argument to f`

### What did you see instead?
`prog.go:7:4: cannot use bad (type func() func()) as type func() in argument to f`

The compiler error line:col information points to the first argument, but the actual error is the second.

**Comment by ALTree** [comment]
Thanks for the report.

This is essentially a dup of #15459.

**Comment by ALTree** [comment]
(closing as a dup).
