### ISSUE TITLE
math/bits: add Rem32/Rem64

### ISSUE THREAD

**Issue by TuomLarsen** [golang/go#28970]
On current master, [math/bits.Div{32, 64}](https://github.com/golang/go/blob/master/src/math/bits/bits.go) panic when `y <= hi`, i.e. on overflow, as seen in the [https://github.com/golang/go/commit/979d9027aecf265214a6dcc27fe037bfd70355f2](https://github.com/golang/go/commit/979d9027aecf265214a6dcc27fe037bfd70355f2).

However, even if the quotient might not fit in uint{32, 64}, the remainder does. Therefore I would like to kindly ask you to reconsider because sometimes getting the remainder of uint{64, 128} and uint{32, 64} is still useful, for example in modular arithmetic.

Perhaps there could be additional functions just for remainders, such as `Rem64(hi, lo, y uint64) (rem uint64)`.

**Comment by randall77** [comment]
That seems like a reasonable thing to want to have.

I don't think we know how to implement such a thing as an intrinsic.  The instruction x86 would use will trap if the quotient is too big, regardless of whether you use the quotient or not.

**Comment by TuomLarsen** [comment]
In that case, I personally would very much want to keep `math/bits.Div{32, 64}` simple and fast (i.e. as it is now) and perhaps include `Rem{32, 64}` sometime in the future, if desired.

**Comment by randall77** [comment]
Ok, we can decide if we want Rem also (and how to do it, if we do) for 1.13.

Note that you can do `Rem32` yourself using the built-in 64-bit divide.

**Comment by randall77** [comment]
@bmkessler : Very nice.

**Comment by rsc** [comment]
Based on comments above, sounds like decision is keep panicking and leave Rem32/Rem64 for Go 1.13.

Assuming here that Div64 is new in this release, which I think it is.

**Comment by josharian** [comment]
Too late to add new API to 1.13.

**Comment by TuomLarsen** [comment]
Thank you!
