### ISSUE TITLE
I recommend invite .net author Anders Hejlsberg join go team.

### ISSUE THREAD

**Issue by iamybj** [golang/go#28977]
C# is the best comfortable programming language in the world.
All other programming languages have more or less ugly point.
And most of the go team, are lab's researchers, they are not familiar with production software developer's requirements.
Go has borrowed some ideas from C and python, In fact, Go should continue borrow some ideas from C#.
It is 9 years since the born of go, 9 years is not a short time, but go still are not very suitable for software industry.
Lab's researchers work too slow, and sometime too lazy. If some exports who work at real software developing fields join the go team, can speed up your work.

**Comment by dominikh** [comment]
Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions or posting unsubstantiated opinions.
