### ISSUE TITLE
plugin: TestPlugin fails on linux/arm64

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#28982]
linux/arm64 builder is broken

https://build.golang.org/log/2eb7494571c1d6ebc6d8308c6bab8daec7e2a509

with

```
# plugin.test
/workdir/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld.gold: internal error in global, at ../../gold/aarch64.cc:4973
collect2: error: ld returned 1 exit status

ok  	path/filepath	0.083s
FAIL	plugin [build failed]
```

https://go-review.googlesource.com/c/go/+/151478 was suppose to fix the failure, but it did not fix it. I don't see what the problem is.

Need help.

Thank you.

Alex

**Comment by tklauser** [comment]
I think the build constraint is wrong. Currently it is
```go
// +build !nacl !linux,arm64
```
which corresponds to
```
!nacl OR (!linux AND arm64)
```
which is still satisfied by `linux/arm64`.

Instead it should be
```go
// +build !nacl
// +build !linux linux,!arm64
```
which corresponds to
```
!nacl AND (!linux OR (linux AND !arm64))
```
