### ISSUE TITLE
x/tools/cmd/guru: Guru does not detect references of embedded interface's methods

### ISSUE THREAD

**Issue by thakkarparth007** [golang/go#28998]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version g1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/parth/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/parth/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2y/qxwyq2d549n48y7bmv9qpzy40000gn/T/go-build460430045=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I wrote the following code, and used VS Code's "Find all references" on `Walkable` interface's `Walk()` method, and it said "No results". VSCode uses the Guru tool for the find-all-references functionality.
 
```
package main

import "fmt"

// Walkable defines interface to be implemented by things that can Walk
type Walkable interface {
	Walk()
}

// WalkableImpl implemented the Walkable interface
type WalkableImpl struct{}

// Walk allows walking
func (w *WalkableImpl) Walk() {
	fmt.Print("Hi I'm walking")
}

// Human embeds Walkable interface
type Human struct {
	Walkable
	Name string
}

func main() {
	human := Human{
		Walkable: &WalkableImpl{},
		Name:     "Johnny",
	}
	human.Walk()
	fmt.Print("Hello world")
}
```

### What did you expect to see?
I expect to find the `human.Walk()` as a result in the references list.

### What did you see instead?
"No results"

**Comment by thakkarparth007** [comment]
Any updates on this? A lot of code I work with has embedded structs and tracing usages of methods on those structs is impossible currently. :(

**Comment by adonovan** [comment]
guru was deleted in https://github.com/golang/go/issues/65880; closing as obsolete. Incidentally, gopls gets this right.
