### ISSUE TITLE
cmd/compile: 33909 breaks build on s390x

### ISSUE THREAD

**Issue by billotosyr** [golang/go#28990]
### What version of Go are you using (`go version`)?
<pre>
$ go version 1.12 master tip

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
build bot
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="s390x"
GOBIN=""
GOEXE=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/data/golang/go"
GOTOOLDIR="/data/golang/go/pkg/tool/linux_s390x"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build874631313=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?
looked at the build page

### What did you expect to see?

successful build

### What did you see instead?

broken build

https://build.golang.org/log/74215d2fbf0b19a020c16db9f7d52f4cf2869177

issue22200b.go:11: missing error "stack frame too large"
issue22200b.go:17: missing error "stack frame too large"
issue22200b.go:23: missing error "stack frame too large"
Unmatched Errors:
issue22200b.go:13: internal compiler error: 'f3': bad int32 AuxInt value for v30

**Comment by randall77** [comment]
Fixed with CL 151597

**Comment by billotosyr** [comment]
Thank you!
