### ISSUE TITLE
x/mobile: unable to include symbols for App Store submission

### ISSUE THREAD

**Issue by sashabaranov** [golang/go#28997]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ab/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ab/code/et"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4v/80xls6wn4gbc8y1phf9x3908ld03pg/T/go-build963348685=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

After running 
```
gomobile bind -target=ios -o EasyPGP.framework github.com/lastochkanetwork/EasyPGP
```

I've did the following:
1. Added EasyPGP.framework to XCode project
2. Build→Archive
3. Submit build to App Store
4. Set following checkmark

<img width="484" alt="screen shot 2018-11-28 at 22 45 29" src="https://user-images.githubusercontent.com/677093/49204036-59de8c80-f35f-11e8-8089-b487bd2a8d23.png">

5. Got "Symbol tool failed" error message while processing build

<img width="740" alt="screen shot 2018-11-28 at 22 40 00" src="https://user-images.githubusercontent.com/677093/49204057-6f53b680-f35f-11e8-8369-bdc0973049b0.png">

Exclusion of EasyPGP.framework fixed error message. Previous .framework build (from around5 month ago) works just fine.

### What did you expect to see?

Correct build upload

### What did you see instead?

`Symbol tool failed` error message. At the end of the debug log:

```
2018-11-29 06:47:18 +0000  Running /Applications/Xcode.app/Contents/Developer/usr/bin/symbols '-noTextInSOD' '-noDaemon' '-arch' 'all' '-symbolsPackageDir' '/var/folders/4v/80xls6wn4gbc8y1phf9x3908ld03pg/T/XcodeDistPipeline.OCM/Symbols' '/var/folders/4v/80xls6wn4gbc8y1phf9x3908ld03pg/T/XcodeDistPipeline.OCM/sayana.app.dSYM/Contents/Resources/Dwarf/myappname'
2018-11-29 06:47:18 +0000  error: Could not load symbol information for 22B5CECF-8729-324E-96B5-01D56C25DF88.  Symbols file will contain no data.

```

**Comment by sashabaranov** [comment]
Might be related to #25297 #25704 #28517

**Comment by sashabaranov** [comment]
Go 1.10.4 does not cause this such problem

**Comment by zhoujian12** [comment]
I also has this problem in version 1.11.4

**Comment by sashabaranov** [comment]
@eliasnaur without checkbox binary gets uploaded and crash logs arrive without symbols

**Comment by girishkoundinya** [comment]
I am having a similar issue and I use go version go1.11.5 darwin/amd64

**Comment by steeve** [comment]
We just got this issue when migrating to Bazel, so we assumed it was because of that. Apparently it is not.
I'm not sure why Go DWARF attributes would cause this, since they've always been there (admittedly with improvements in go 1.11). https://github.com/golang/go/issues/25297 was for the gradle Crashlytics plugin.

**Comment by steeve** [comment]
Related:
- https://github.com/flutter/flutter/issues/22560

**Comment by steeve** [comment]
Apparently the offending command is:
```
symbols -noTextInSOD -noDaemon -arch all -symbolsPackageDir <PATH TO DSYM> App.app/App
```

**Comment by qmathe** [comment]
For the record, I have the same issue with Go 1.11.5 darwin/amd64. 

In the meantime, my current workaround is to strip all debug symbols by passing `-ldflags="-s -w"` to `go bind`.

**Comment by tmm1** [comment]
>What did you see instead?
>
>Symbol tool failed error message.

This issue has been resolved and I think this issue can be closed.

**Comment by champo** [comment]
@tmm1 how can I try the fix you mention?  I've tried the workaround and it still fails: `gomobile bind  -v -ldflags="-s -w" -target=ios -o mypkg.framework github.com/mypkg/mypkg`

**Comment by tmm1** [comment]
You have to compile and use golang from master so it includes https://github.com/golang/go/commit/3cb92fcba71f9c0d64b3b714fc92870065848345

**Comment by champo** [comment]
I've tried using the latest master and I'm getting the same error. Some things I've checked:
 - Uninstalled my previous golang version to make sure I'm building with the right version
 - symbols after generating the .framework still prints a single `null-uuid` record
 - archiving & upload to app store fails with an "empty symbols table" error
 - rebuilt gomobile using go master
 - adding `-ldflags="-s -w"` to `gomobile bind` fails with the same error

**Comment by steeve** [comment]
@tmm1 I tried to cherry-pick 277609f844ed9254d25e975f7cf202d042beecc6 and 2ae793ed48eaef584e3cdcd7820d5bb891ab1a5f on top of Go 1.11.10, and I get a failure at the symbols test:
```
--- FAIL: TestDWARF (14.77s)
    --- FAIL: TestDWARF/testprog#01 (1.71s)
        dwarf_test.go:86: symbols go.o: parsed as empty
    --- FAIL: TestDWARF/testprogcgo#01 (7.53s)
        dwarf_test.go:86: symbols go.o: parsed as empty
FAIL
FAIL	cmd/link	14.963s```

**Comment by steeve** [comment]
Ok I found out I was missing b56d1bad29abc4e92491c8a66bdca310831b1d8e too

**Comment by tmm1** [comment]
Can this be closed now?

**Comment by steeve** [comment]
I think, no problems on our side anymore.
