### ISSUE TITLE
x/mobile: -classpath 

### ISSUE THREAD

**Issue by log225** [golang/go#29002]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Hi @log225 - Unfortunately, this issue is not clear on the expected action to be taken. Please file a new issue with the _complete_ issue template. Thanks.
