### ISSUE TITLE
go/types: new embedded interface behavior (possible regression)

### ISSUE THREAD

**Issue by ccbrown** [golang/go#29029]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chris/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chris/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x1/md855yzx0lg2yqccxnvnb5lw0000gn/T/go-build287116670=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I type-checked and printed definitions from a package with a test file that embeds a non-test interface into another interface.

### What did you expect to see?

The interface method with the correct receiver type:

```go
func (github.com/ccbrown/go-interface-method-type-bug/thepackage.A).Foo()
```

### What did you see instead?

The receiver type was overwritten based the contents of the test file:

```go
func (interface).Foo()
```

### Demo project

Check out this program: https://github.com/ccbrown/go-interface-method-type-bug

Run `go run main.go`. With Go 1.10, you get the output I would expect. With Go 1.11, you get different output.

This makes tooling such as @dominikh's [unused](https://github.com/dominikh/go-tools) tool break in Go 1.11 for certain cases where tests define interfaces that embed other interfaces.

**Comment by griesemer** [comment]
I can reproduce this. It does look like a regression.

**Comment by griesemer** [comment]
Stand-alone reproducer (no need to use loader): https://play.golang.org/p/6rledUr3Mhx

**Comment by griesemer** [comment]
See comments in CL as to why the suggested diff is correct and also necessary.
