### ISSUE TITLE
build: improve installation of Go on Windows machines

### ISSUE THREAD

**Issue by SetTrend** [golang/go#29056]
### What version of Go are you using (`go version`)?

<pre>go version go1.11.2 windows/amd64</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\***\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\***\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\***\AppData\Local\Temp\go-build824738654=/tmp/go-build -gno-record-gcc-switches</pre></details>

### What did you do?

Failed trying to install **Go** to be able to fix some bugs in [GitLab Runner](https://docs.gitlab.com/runner/).

### What did you expect to see?

I expected to get a fully functional **Go** development environment after [installing **Go** for Windows](https://golang.org/dl/).

### What did you see instead?

- Environment variables missing (`GOROOT_BOOTSTRAP`).
- C compiler not included with the install.
- Microsoft **VC++** not used although installed on the machine.
- Not being able to install **Go** to the correct Windows program files directory (`%ProgramFiles%`).
<br/>

It's a heck of work to get the **GCC** compiler up and running. Why isn't it bundled with **Go**? And why doesn't **Go** utilize an already installed Microsoft **VC++** compiler?

**Comment by ianlancetaylor** [comment]
Thanks for the report.

It's not necessary to set the `GOROOT_BOOTSTRAP` environment variable in order to use Go.  It is only necessary to set it when building Go from source.  If you install binaries, they should not set it.

It is possible to write programs in pure Go.  I don't think it would be appropriate for a Go installation to also install a C compiler.  A C compiler is an optional choice, but it's not required.

Making Go work with MSVC is issue #20982.

I think that leaves one point: installing Go in `%ProgramFiles%`.

**Comment by SetTrend** [comment]
Thanks for enlightening me. You are right. I was stumbling my way through digging into **Go** and ran the `make.bat` file until I learned about `go build` and `go install`.

> It is possible to write programs in pure Go. 

I see. Yet, will these compile into executables to be, well, executable?

One more note: After installing **GCC** I was required to re-install **Go**. So, there is an undesired dependency between **GCC** and **Go**.

**Comment by slrz** [comment]
The Go distribution includes compilers and linkers. You should be able to build programs written in Go and get a native executable for your local OS and architecture. You should also be able to cross-compile Go programs into executables for other architectures and operating systems.

None of this requires a C compiler installed on the system (except when using cgo, of course).

I'm not sure about your other note. Do you mean re-installing the binary distribution or re-compiling the toolchain locally by calling make.ba{t,sh}?

**Comment by forskning** [comment]
pursuant to German language directory naming when running in cmd.exe

ECHO %ProgramFiles%

this does not return a value containing blank spaces, so, extracting go1.11.2.windows-amd64.zip, and from an administrative level cmd.exe CD'ing into go1.11.2.windows-amd64 and running

MOVE go C:\PROGRA~1

should locate the go directory in %ProgramFiles%

https://gitlab.com/gitlab-org/gitlab-runner
https://docs.gitlab.com/runner/development/README.html

**Comment by forskning** [comment]
" ...bundled with Go"

https://www.haskell.org/platform/

I like 'Haskell Platform' on Windows which includes packages from MSYS2/MinGW, but at 200 MB+ would not want to see something similar to be implemented using Golang.

**Comment by SetTrend** [comment]
> I'm not sure about your other note. Do you mean re-installing the binary distribution or re-compiling the toolchain locally by calling make.ba{t,sh}?

Strange, I got an error trying to build GitLab Runner before installing GCC. Then after I installed GCC, I still got an error, until I re-installed Go then.

> Why the Windows preference as a working environment?

My development environment _is_ Windows.

> As VS2017 can install Python and R, wouldn't that be a question better addressed to the Visual Studio developers?

I don't understand your remark in regard to Go.

**Comment by SetTrend** [comment]
> ECHO %ProgramFiles%

```
C:\Users>ECHO %ProgramFiles%
C:\Program Files
```

> MOVE go C:\PROGRA~1

Gee, that would be a dirty hack. Professional programmers should _always_ consider the existence blanks in path segments. On each and every platform.

Plus, on Windows environments, programmers should _always_ consider the directory containing executables (like, e.g., `C:\Pogram Files\GitLab\`) to be read-only as a safety measure against malicius modification while config files should _always_ go to `C:\PogramData\(GitLab\)` and user files should go to `C:\Users\{UserName}\AppData\Roaming\(GitLab\)`). (See [Microsoft programming guidelines, quoted on Wikipedia](https://en.wikipedia.org/wiki/Special_folder).)

In fact, I consider creating a Merge Request for GitLab Runner for Windows to adhere to Microsoft programming guidelines in regard to standard

**Comment by forskning** [comment]
@SetTrend

though I don't represent Microsoft Inc., perhaps their employees as Python coders (feasibly also thier employees as Golang coders), are cognisant of the work being pursued upstream on Visual Studio, consequently derived from that, if Golang were another coding language to add via Visual Studio's installer, then such aforementioned Golang coders, might have an interest in Golang use with the "Microsoft VC++ compiler"

**Comment by forskning** [comment]
C:\>ECHO %ProgramFiles%
C:\Programmer

C:\>MOVE /?
Flytter filer og omdøber filer og mapper.

Sådan flyttes en eller flere filer:
MOVE [/Y | /-Y] [drev:][sti]filnavn1[,...] destination

Sådan omdøbes en mappe:
MOVE [/Y | /-Y] [drev:][sti]mappenavn1 mappenavn2

  [drev:][sti]filnavn1    Angiver placeringen og navnet på filen eller
                          filerne, du vil flytte.
  destination             Angiver den nye placering af filen. Destination
                          kan består af et drevbogstav og et kolon, et
                          mappenavn eller en kombination heraf. Hvis du kun
                          flytter én fil, kan du desuden medtage et filnavn,
                          hvis du vil omdøbe filen, når du flytter den.
  [drev:][sti]mappenavn1  Angiver den mappe, du vil omdøbe.
  mappenavn2              Angiver mappens nye navn.

  /Y                      Undertrykker anmodningen om at bekræfte, at den
                          eksisterende destinationsfil må overskrives.
  /-Y                     Medfører en anmodning om at bekræfte, at en
                          eksisterende destinationsfil må overskrives.

Parameteren /Y må medtages i miljøvariablen COPYCMD. Dette kan
tilsidesættes med /-Y på kommandolinjen. Standard er at bede om
bekræftelse ved overskrivning, medmindre kommandoen MOVE udføres
fra et batchscript.

C:\>

**Comment by forskning** [comment]
Historically a number of coding languages have recommended installing into a path without blank spaces, at minimum it results in that one can (in certain cases) in one's code avoid having to quote paths (which contain blank spaces). 

https://golang.org/doc/install#windows

MSI installer

...By default, the installer puts the Go distribution in c:\Go.

...

Zip archive

...(we suggest c:\Go).

https://nurmi-labs.blogspot.com/2017/05/9pvfs.html

C:\PROGRA~2

is

C:/Program Files (x86)

**Comment by SetTrend** [comment]
@forskning:

Sure, but that was back those days when there were 8.3 file names and no way to automatically test programs against flaws.

But robust programming strategies evolved over time. Today, a common unit test for each function accepting file paths is a path with spaces.
<br/>

Moreover, today, professional environments commonly incorporate corporate wide backup strategies. These involve user files in:
- `ApplicationData`
- `CommonApplicationData`
- `CommonDesktopDirectory`
- `CommonDocuments`
- `CommonMusic`
- `CommonPictures`
- `CommonVideos`
- `DesktopDirectory`
- `Favorites`
- `LocalApplicationData`
- `MyDocuments`
- `MyMusic`
- `MyPictures`
- `MyVideos`
- `Personal`

... yet **no executables** and **no _other_ custom directories**.
<br/>

Last but not least, executables are solely stored in `ProgramFiles` and `ProgramFilesX86`, resp., because Windows is providing automatic and system wide safety measures to protect executables within these directories from modification. Any executable file outside these directories is unsafe and instantly vulnerable to malicious attacks.

So Linux/Apple programmers who don't know about how to safely and robustly program under Windows environments harm any Windows installation. There are only two reasons for doing this: either intentionally or due to lack of knowledge.

**Comment by forskning** [comment]
" ...corporate wide backup strategies"

pertaining to WSL the following entry might be considered

%LOCALAPPDATA%\Lxss\rootfs

**Comment by SetTrend** [comment]
I believe this discussion is heading the wrong direction.

I will be going to re-install Go on another virtual machine and I'll see whether it'll install without flaw and without being required to install GCC first. At this time I believe the error is on my side. But I will see.

Regarding your last comment:

MS GitHub repositories and VS (Code) extensions have no relation to the installation of the Go language, and so, have on relation to this bug report.

In my above mentioned list, `LocalApplicationData` is already included, and hence, `%LOCALAPPDATA%\Lxss\rootfs` is, too.
