### ISSUE TITLE
runtime: TestAbort fails with "panic: BAD: recovered from abort" on windows/arm

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#29050]
windows/arm builder fails

https://build.golang.org/log/dcf35b2e42a6d30ca1d7604ce79d5c50e8071b04

on runtime.TestAbort test with

```
--- FAIL: TestAbort (0.11s)
    crash_test.go:95: testprog Abort exit status: exit status 2
    crash_test.go:652: output contains BAD:
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        	panic: BAD: recovered from abort
        [signal 0xc0000005 code=0x0 addr=0x0 pc=0x3322ac]
```

runtime.TestAbort runs Abort function

https://github.com/golang/go/blob/f70bd914353b2331a48eedb84aceb458982eaac0/src/runtime/testdata/testprog/abort.go#L13-L23

As far as I can tell, process containing Abort is suppose to exit at line 18. But windows/arm seems to continue to line 19.

runtime.abort is just a INT $3 on amd64, but on arm it looks like this

https://github.com/golang/go/blob/f70bd914353b2331a48eedb84aceb458982eaac0/src/runtime/asm_arm.s#L799-L801

Perhaps this code hits exception handler on Windows, where things recover. If that is so, what code should we put into runtime.abort, so it does not recover?

@jordanrh1 please help.

Thank you.

Alex

**Comment by cherrymui** [comment]
On UNIX systems, this just triggers SIGSEGV and the runtime's `isAbort` function checks the faulting PC.
```
func isAbortPC(pc uintptr) bool {
        return pc == funcPC(abort) || ((GOARCH == "arm" || GOARCH == "arm64") && pc == funcPC(abort)+sys.PCQuantum)
}
```

The assembly code seems ok to me, matching the runtime's check.

On Windows, function `isgoexception` in `signal_windows.go`:
```
        // In the case of an abort, the exception IP is one byte after
        // the INT3 (this differs from UNIX OSes).
        if isAbortPC(r.ip() - 1) {
                // Never turn abort into a panic.
                return false
        }
```
I'm not familiar with Windows, but I suspect the `r.ip() - 1` may not work on ARM. Does `r.ip()` point to the next instruction after the faulting instruction? In this case it probably should be `r.ip() -  sys.PCQuantum`.

**Comment by alexbrainman** [comment]
> In this case it probably should be `r.ip() - sys.PCQuantum`

Thank you for finger pointing. Hopefully, I did not misinterpret your explanation https://go-review.googlesource.com/c/go/+/152357


Alex

**Comment by jordanrh1** [comment]
Looks like the fix worked:
```
testprog.exe Abort
Exception 0xc0000005 0x0 0x0 0x26238c
PC=0x26238c

runtime.abort()
/home/jordanrh/go/src/runtime/asm_arm.s:801 +0x4 fp=0x11461f48 sp=0x11461f48 pc=
0x26238c
main.Abort()
/home/jordanrh/go/src/runtime/testdata/testprog/abort.go:21 +0x30 fp=0x11461f54
sp=0x11461f48 pc=0x2c4f6c
main.main()
/home/jordanrh/go/src/runtime/testdata/testprog/main.go:34 +0x158 fp=0x11461fc4
sp=0x11461f54 pc=0x2c886c
runtime.main()
/home/jordanrh/go/src/runtime/proc.go:200 +0x1d4 fp=0x11461fe4 sp=0x11461fc4 pc=
0x23ce3c
runtime.goexit()
/home/jordanrh/go/src/runtime/asm_arm.s:868 +0x4 fp=0x11461fe4 sp=0x11461fe4 pc=
0x2623ec
r0   0x0
r1   0x0
r2   0x11417380
r3   0x300c40
r4   0x114080e0
r5   0x0
r6   0x1141733c
r7   0x1141733c
r8   0x3
r9   0x8
r10  0x114080e0
r11  0x3ba100
r12  0x1
sp   0x11461f48
lr   0x2c4f6c
pc   0x26238c
cpsr 0x600f0010
```

Before the fix:
```
testprog.exe Abort
panic: runtime error: invalid memory address or nil pointer dereference [recover
ed]
panic: BAD: recovered from abort
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xd3236c]

goroutine 1 [running]:
main.Abort.func1()
/home/jordanrh/go/src/runtime/testdata/testprog/abort.go:19 +0x30
panic(0xdb3690, 0xe77cd0)
/home/jordanrh/go/src/runtime/panic.go:513 +0x194
main.Abort()
/home/jordanrh/go/src/runtime/testdata/testprog/abort.go:21 +0x30
main.main()
/home/jordanrh/go/src/runtime/testdata/testprog/main.go:34 +0x158
```

**Comment by alexbrainman** [comment]
> Looks like the fix worked:

Thanks for checking. I will wait for codereview on https://go-review.googlesource.com/c/go/+/152357 now.

Alex
