### ISSUE TITLE
encoding/gob: documentation incomplete(or wrongly implemented)

### ISSUE THREAD

**Issue by JAicewizard** [golang/go#29057]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jaap/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jaap/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jaap/go-projects/templatebuilder/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build816382028=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I implemented the gob.GobEncoder (and gob.GobDecoder) interface(s) using pointer receivers on both ends.

### What did you expect to see?
I expected to see gob calling my encoder and decoder to transmit the data

### What did you see instead?
Gob doesn't use my encoder/decoder.
After debugging I could see that it does recognize that it implements both GobEncoder and GobDecoder, but for some reason doesn't use them.
After removing the * from the Encoder(making it a non-pointer receiver) receiver gob does use my implementation(successfully).

UPDATE:
I know that this is because I pass a non-pointer to enc.Encode() but this is was a bit frustrating.
Maybe just add a note that using a pointer receiver only works with pointer values, while non-pointer receivers work with both pointer and non-pointer receivers.

**Comment by robpike** [comment]
Please show a complete, compact program that illustrates the problem.

**Comment by JAicewizard** [comment]
https://play.golang.org/p/idvKWcdTPiI

By commenting out line 36(BWithPointerData())  you can see that it works when a pointer is given and not vice versa.
I was a bit confused at the time of reporting this, I think a simple warning/comment in the documentation warning about this would have made my day a lot easier, and I expect this will help other people too.

**Comment by robpike** [comment]
This is how Go works. I'm not sure it's the gob's package job to explain the difference between the method sets of pointers and values.

https://golang.org/doc/faq#different_method_sets

**Comment by JAicewizard** [comment]
I think it would be more convenient if there would be a reference to the faq in the gob(and JSON...) documentation.
If you encounter something you can't figure out, you look at the definition(of the interface in this case), not the general faq.
Although I thought it "worked" with JSON, it also doesn't encode with a pointer method, but it does decode using the unmarshal method(unlike gob).

**Comment by agnivade** [comment]
> If you encounter something you can't figure out, you look at the definition(of the interface in this case), not the general faq.

If that "something" is not related to that type, I think that expectation is incorrect. If I am working with encoding/json, and I cannot figure out how slice append work, I do not expect that to be explained in the interface definition. 

Method sets are a design of the programming language itself and not specific to any package. I don't think adding a link to the FAQ just in gob and json, for something that is general to the programming language, is very helpful.

It is clearly documented in the [spec](https://golang.org/ref/spec#Method_sets) and also in the [FAQ](https://golang.org/doc/faq#different_method_sets).

I am going to close this as the original issue title is resolved. There is no issue with encoding/gob. If you feel method sets need to be documented more prominently, please feel free to open an issue with suggestions, and with reasoning explaining why the current documentation is not enough. Thanks.
