### ISSUE TITLE
Permission Denied for `go build`

### ISSUE THREAD

**Issue by laurencedev** [golang/go#29063]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alex/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alex/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build236506413=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
1. Follow the page,https://github.com/golang/go/wiki/Configuring-GoLand-for-WebAssembly,  to set GoLand IDE , this including the compile wasm part configuration in the page.
2. Follow the page, https://tutorialedge.net/golang/go-webassembly-tutorial/, to create a project
3. `Run` output permission denied errors listed in below.

### What did you expect to see?
`
Compilation finished with exit code 0
`
### What did you see instead?
`
go build internal/cpu: mkdir /usr/local/go/pkg/js_wasm: permission denied
go build internal/race: open /usr/local/go/pkg/js_wasm/internal/race.a: no such file or directory
go build runtime/internal/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
go build sync/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
go build runtime/internal/sys: open /usr/local/go/pkg/js_wasm/runtime/internal/sys.a: no such file or directory
`

### Others
There are some issues mentioned the same type of error, like https://github.com/Microsoft/vscode-go/issues/1874 , but the solutions listed there suggests using `go build`. However, here, the error is caused by `go build` command, which confused me.

**Comment by agnivade** [comment]
Hi @laurencedev - errors like these are mostly due to setup issues. This seems to be possibly an issue with GoLand rather than the Go programming language. I would request you to use the [Questions](https://github.com/golang/go/wiki/Questions) wiki page for this; it has a list of good places for asking questions.

**Comment by bcmills** [comment]
What is the `go build` command that GoLand attempts to execute? (There are a couple of other issues that this could be a symptom of, and some of them are fixed at head.)
