### ISSUE TITLE
x/build: PATH changed for aix/ppc64 builder

### ISSUE THREAD

**Issue by Helflym** [golang/go#29078]
`aix/ppc64` builder needs to have `/opt/freeware/bin` in its PATH. This will provide 'OpenSource' version of some programs which are different on AIX like diff. 
PATH should be: 

`PATH=/opt/freeware/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java7_64/jre/bin:/usr/java7_64/bin`

This might resolve [29065](https://github.com/golang/go/issues/29065). 

/cc @dmitshur

**Comment by bradfitz** [comment]
Deployed.
