### ISSUE TITLE
net: incorrect docs on KeepAlive field of Dialer

### ISSUE THREAD

**Issue by mikioh** [golang/go#29089]
### What version of Go are you using (`go version`)?

tip

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

doesn't matter

### What did you do?

Run "go doc net Dialer" and took a look at the output

### What did you expect to see?

At least the docs introduced by #23459 never uses the phrase "keep-alive period" because the existing implementation tries to tweak the keepalive idle and probe intervals, not the entire keepalive period.

### What did you see instead?`

```
// KeepAlive specifies the keep-alive period for an active
// network connection.
// If zero, keep-alives are enabled if supported by the protocol
// and operating system. Network protocols or operating systems
// that do not support keep-alives ignore this field.
// If negative, keep-alives are disabled.
KeepAlive time.Duration
```

FWIW, SetKeepAlivePeriod on TCPConn says:
```
// SetKeepAlivePeriod sets period between keep alives.
func (c *TCPConn) SetKeepAlivePeriod(d time.Duration) error {
```

**Comment by mikioh** [comment]
In addition, I personally prefer implementing KeepAlive as an entire keepalive period rather than idle and probe intervals like CL 107196.

**Comment by bradfitz** [comment]
@mikioh, I thought you were saying that https://github.com/golang/go/commit/5bd7e9c54f946eec95d32762e7e9e1222504bfc1 introduced the wording "keep-alive period" but it does not. It just adds some more words around the existing Dialer.KeepAlive docs.

I'm going to punt this to Go 1.13.
