### ISSUE TITLE
cmd/go: generate panics when go files provided as arguments and modules are on

### ISSUE THREAD

**Issue by SamWhited** [golang/go#29097]
### What version of Go are you using (`go version`)?

(also happens on a non-dirty tree):

<pre>
go version devel +c2412a7681d5 20181204001955 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, 1.11.2 works as expected.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/sam/bin"
GOCACHE="/home/sam/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sam/go"
GOPROXY=""
GORACE=""
GOROOT="/home/sam/Projects/go"
GOTMPDIR=""
GOTOOLDIR="/home/sam/Projects/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sam/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build948663473=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ export GO111MODULE="on"
$ echo "package main" > test.go
$ go generate test.go
 TestmainGo:<nil> Asmflags:[] Gcflags:[] Ldflags:[] Gccgoflags:[]}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x89fea7]

goroutine 1 [running]:
cmd/go/internal/generate.runGenerate(0xe11a40, 0xc0000a8170, 0x1, 0x1)
        /home/sam/Projects/go/src/cmd/go/internal/generate/generate.go:167 +0x117
main.main()
        /home/sam/Projects/go/src/cmd/go/main.go:219 +0x82d
```

### What did you expect to see?

Nothing happens because the file has no generate comment.

### What did you see instead?

`pkg.Module` is nil, so Go generate panics (cmd/go/internal/generate/generate.go:167)

**Comment by agnivade** [comment]
/cc @bcmills 

Tentatively marking as release blocker.

**Comment by jayconrod** [comment]
I looked into this today. I think this started with [CL 148517](https://go-review.googlesource.com/c/148517), which added support for "go get" outside of a module. Several commands including fix, generate, list, run, build either panic or print a stack (via `modload.die`) when run outside of a module.

I have a CL mostly ready that fixes this. However, it's not clear to me that we want to allow all of these commands to run outside of modules. These commands could all do reasonable things (e.g., `go generate test.go`, or `go run hello.go`), but I'm worried about introducing a lot of corner cases without adding much value.

Will discuss with @bcmills tomorrow.

**Comment by SamWhited** [comment]
> when run outside of a module.
>
> I have a CL mostly ready that fixes this. However, it's not clear to me that we want to allow all of these commands to run outside of modules

Note that this also happens within modules. If you add a `go.mod` file to the example in the original post, `go generate test.go` will still panic.

**Comment by bcmills** [comment]
@jayconrod, in general any command should work as long as it (a) does not exist solely for editing the `go.mod` file and (b) does not need the name of the main module to resolve an import path.
