### ISSUE TITLE
cmd/go: go build error.  open C:\Users\...\a.out.exe: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by jcuan** [golang/go#29093]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
windows 10 1803
10.0.17134
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.11.2 windows/amd64
PS D:\code\go> go env
set GOARCH=amd64
set GOBIN=D:\tools\gobin
set GOCACHE=C:\Users\SHEXIA~1\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\code\go
set GOPROXY=
set GORACE=
set GOROOT=D:\tools\go11
set GOTMPDIR=
set GOTOOLDIR=D:\tools\go11\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\SHEXIA~1\AppData\Local\Temp\go-build536614342=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```bash
#build successfully
PS D:\code\go\src> go build -o out.exe .\main.go
#update code, build failed
PS D:\code\go\src> go build -o out.exe .\main.go
open C:\Users\SHEXIA~1\AppData\Local\Temp\go-build047301674\b001\exe\a.out.exe: The process cannot access the file because it is being used by another process.
PS D:\code\go\src> go build -o out.exe .\main.go
open C:\Users\SHEXIA~1\AppData\Local\Temp\go-build838661906\b001\exe\a.out.exe: The process cannot access the file because it is being used by another process.
#wait a few minutes, build successfully again
PS D:\code\go\src> go build -o out.exe .\main.go
```

**Comment by ianlancetaylor** [comment]
Is this repeatable?  What are the contents of main.go?

**Comment by jcuan** [comment]
@ianlancetaylor 

This problem happens every time after I use go build .The Contents of main.go is simple and all my projects have this problem.
```go
package main

import "fmt"

func main() {
    fmt.Println("jcuan")
}
```

**Comment by agnivade** [comment]
> This problem happens every time after I use go build .

That does not seem to match this statement of yours.

> #wait a few minutes, build successfully again

So it looks like some process is possibly using a.out.exe for some time. I don't know what is the `lsof` equivalent in Windows, but are you sure that no process is actually using a.out.exe ?

**Comment by jcuan** [comment]
@agnivade @ianlancetaylor 
> This problem happens every time after I use go build .

I mean I must wait a few minutes in order to build successfully again almost every time after using go build.

Now, I find that maybe it's caused by `vscode/go extension` in vscode. Yesterday, I turn off vscode and use notepad to edit code, which doesn't fix this problem. But today, I rebooted my computer and didn't open vscode before using go build and I didn't encounter this problem again after many tries. Then I opened vscode and this problem appeared again but the probability was very low.

Thank you both~ :grin:

**Comment by whyAtGh** [comment]
[This solution](https://github.com/electron-userland/electron-builder/issues/3666) helps for me. You can try it.
It seems that vscode is the cause of the problem.

**Comment by wusi1027** [comment]
it happens almost every time when using go version >=1.11(I've tried 1.11,1.12,1.13).
but it disappears when using go 1.9 or 1.10.
my env:
windows10, no IDE, just cmd/go build

**Comment by wja513** [comment]
I use goland, right click  the icon and _run as administrator_, may help somebody~~~

Check the temporay directory you can see it not created, so i think maybe a Windows permission problem.
