### ISSUE TITLE
proposal: Go 2:  support memory pool in context or thread for real request. just like ngx_pool_cleanup_t，ngx_pool_t in nginx. it can  reduce gc and avoid lock

### ISSUE THREAD

**Issue by buptbill220** [golang/go#29091]
### What version of Go are you using (`go version`)?

<pre>
$ go version 2

</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ianlancetaylor** [comment]
This is something that can be done outside of the Go standard library.  Let's do it there first, and then see if it is useful.  Closing this proposal.

Note that memory is already allocated from a per-thread cache.  I don't see why using a pool would avoid locks.  I agree that in some cases it might avoid a GC, but only with considerable care in management of the memory allocated from the pool.
