### ISSUE TITLE
cmd/go: `go mod vendor` command cannot copy c and other files to the vendor directory

### ISSUE THREAD

**Issue by vcaesar** [golang/go#29102]
### What version of Go are you using (`go version`)?

<pre>
$ go version: go1.11.2
</pre>

`go mod vendor` command can not copy c and other files to the vendor directory ( #26366 ) , this makes a lot of packages have problems, maybe can add `go mod vendor -a`.

**Comment by ianlancetaylor** [comment]
Can you give an example of what you mean?

**Comment by vcaesar** [comment]
I use `go mod vendor` to use the following package, the `event and hook` directory does not exist:
https://github.com/go-vgo/robotgo/tree/master/vendor/github.com/robotn/gohook

I use `go mod vendor` to use the following package, the `data/dict` directory does not exist:
https://github.com/go-ego/gse/tree/master/data/dict

**Comment by myitcv** [comment]
As you already found @vcaesar this is a dup of #26366
