### ISSUE TITLE
Access is Denied when trying to os.rename a file

### ISSUE THREAD

**Issue by LinkyDev** [golang/go#29106]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\omerd\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\omerd\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\omerd\AppData\Local\Temp\go-build225487594=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

main.go  https://play.golang.org/p/byFvCdNZ6WA
server-config-handler.go https://play.golang.org/p/NT0YNaDCzfh
server-config.json https://play.golang.org/p/f0MMU9F7t6-

Im trying to create an http website server that has the ability to upload files and save them on the server storage

**After troubleshooting for 2hours I believe the problem is somehow connected to the os.Rename permission (Im a new Go programmer so I dont know for sure)**

### What did you expect to see?
Expected to see the newly created file moved to the "/srv/file-storage/testdir/" folder

### What did you see instead?
2018/12/05 02:34:58 test.txt
File created succesffuly
2018/12/05 02:34:58 Wrote 617 bytes.
2018/12/05 02:34:58 rename test.txt /srv/file-storage/testdir/: Access is denied.
2018/12/05 02:34:58 An error occurred while renaming the file directory! ERROR:004
exit status 2

**Comment by LinkyDev** [comment]
> This is very unlikely to be a problem with Go. Are you able to run
> 
> ```
> mv my-new-file /srv/file-storage/testdir/
> ```
> while running as the same user as the Go program?

Tried it on Cmder bash and cmd and same result:
"mv: cannot stat 'new-file': No such file or directory"

**Comment by ianlancetaylor** [comment]
When I wrote `my-new-file` I meant that it would be the name of some real file.

**Comment by LinkyDev** [comment]
> When I wrote `my-new-file` I meant that it would be the name of some real file.

When I try this command: 
"mv test.txt /srv/file-storage/testdir/" its gives me an error - "mv: cannot move 'test.txt' to '/srv/file-storage/testdir/': No such file or directory"

But, when I try "mv test.txt /c/srv/file-storage/testdir/" it moves it with no problem

**Comment by LinkyDev** [comment]
> > When I wrote `my-new-file` I meant that it would be the name of some real file.
> 
> When I try this command:
> "mv test.txt /srv/file-storage/testdir/" its gives me an error - "mv: cannot move 'test.txt' to '/srv/file-storage/testdir/': No such file or directory"
> 
> But, when I try "mv test.txt /c/srv/file-storage/testdir/" it moves it with no problem

I tried changing the "server-directory" to C:/srv/file-storage/testdir or /c/srv/file-storage/testdir but still the same issue

**Comment by LinkyDev** [comment]
I found what was my problem!
I added the filename to the end of the new path: 
err := os.Rename(filename, path+filename)
instead of
err := os.Rename(filename, path)

I dont know how i havent tought about it before but Im glad I did, finally I can go to sleep :)
thank you ian for the help btw

**Comment by ianlancetaylor** [comment]
@LinkyDev Thanks for following up.
