### ISSUE TITLE
builders: misc-vet-vetall flakes: undefined: importer.ForCompiler

### ISSUE THREAD

**Issue by mdempsky** [golang/go#29116]
I've trybotted golang.org/cl/152544 three times, and twice it gave the same misc-vet-vetall failure:

    ##### cmd/vet/all
    # golang.org/x/tools/go/analysis/unitchecker
    ../../gopath/src/golang.org/x/tools/go/analysis/unitchecker/unitchecker112.go:8:24: undefined: importer.ForCompiler
    vet/all: exit status 2

https://storage.googleapis.com/go-build-log/5004c83e/misc-vet-vetall_2594bb0d.log
https://storage.googleapis.com/go-build-log/0ce4e24a/misc-vet-vetall_d4638ddb.log

I'm pretty sure these failures are unrelated to the CL, so maybe the trybot is broken?

/cc @bradfitz

**Comment by ianlancetaylor** [comment]
The `importer.ForCompiler` function was added yesterday in https://golang.org/cl/152258.  The vet test runs `go build golang.org/x/tools/go/analysis/cmd/vet`.  Is it possible that your sources do not have `importer.ForCompiler` but the builder does have an up to date golang.org/x/tools?  That is, do you just need to `git codereview sync`?

**Comment by mdempsky** [comment]
> Is it possible that your sources do not have importer.ForCompiler but the builder does have an up to date golang.org/x/tools?

Oh, yes, I think that's probably it.

PS1 had the failure; PS2 (PS1 rebased at master) did not have it; but then I uploaded PS1 with tweaks (and without rebasing locally) as PS3 and had the failure again.

Thanks, sorry for the noise.
