### ISSUE TITLE
os: Stat() returns inconsistent error on Windows

### ISSUE THREAD

**Issue by Xjs** [golang/go#29119]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jannis.schnitzer\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/Users/jannis.schnitzer
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\tools\msys64\tmp\go-build255706334=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Execute the following program under Windows:

```
package main

import (
        "fmt"
        "os"
)

func main() {
        var err error
        _, err = os.Stat("doesnotexist")
        fmt.Println(err, os.IsNotExist(err))
        _, err = os.Stat("doesnotexist/")
        fmt.Println(err, os.IsNotExist(err))
        _, err = os.Stat("/doesnotexist")
        fmt.Println(err, os.IsNotExist(err))
        _, err = os.Stat("/doesnotexist/")
        fmt.Println(err, os.IsNotExist(err))
}
```

### What did you expect to see?

All four lines should output the same error message. (Like on https://play.golang.org/p/X0RVDSjWRmi)

### What did you see instead?

```
$ go run stat.go
FindFirstFile doesnotexist: The system cannot find the file specified. true
FindFirstFile doesnotexist/: The parameter is incorrect. false
FindFirstFile /doesnotexist: The system cannot find the file specified. true
FindFirstFile /doesnotexist/: The system cannot find the path specified. true
```

The second line (`os.Stat("doesnotexist/")`) produces a different error. Particularly `os.IsNotExist(os.Stat("relative_path_that_doesnt_exist_and_ends_in_a_slash/"))` is unexpectedly `false`.

Linux and macOS behave as expected.

**Comment by cgopalan** [comment]
FYI This does not happen in version 1.10.3
```
λ go version
go version go1.10.3 windows/amd64
```
```
λ go run teststat.go
CreateFile doesnotexist: The system cannot find the file specified. true
CreateFile doesnotexist/: The system cannot find the file specified. true
CreateFile /doesnotexist: The system cannot find the file specified. true
CreateFile /doesnotexist/: The system cannot find the file specified. true
```

**Comment by alexbrainman** [comment]
> FYI This does not happen in version 1.10.3

This does not happen on the tip either (I am using 9be01c2)
```
C:\>u:\test
CreateFile doesnotexist: The system cannot find the file specified. true
CreateFile doesnotexist/: The system cannot find the file specified. true
CreateFile /doesnotexist: The system cannot find the file specified. true
CreateFile /doesnotexist/: The system cannot find the file specified. true

C:\>
```

Alex

**Comment by cgopalan** [comment]
@alexbrainman I just saw that the test i wrote failed. So this is not an issue in the latest master but was only an issue in the 1.11 release?

**Comment by alexbrainman** [comment]
> @alexbrainman I just saw that the test i wrote failed. So this is not an issue in the latest master but was only an issue in the 1.11 release?

This issues does exists in go1.11. But, I believe, it has been fixed on current tip.

Alex

**Comment by cgopalan** [comment]
@alexbrainman oh so should I just close the PR?

**Comment by alexbrainman** [comment]
> @alexbrainman oh so should I just close the PR?

I think your PR is not need. There is no problem here to fix.

Alex

**Comment by cgopalan** [comment]
@alexbrainman ok will close it then. @Xjs seems like this is fixed in `master`.
