### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timchenxiaoyu** [golang/go#29131]
question
```

func det()(result int){
 result = 2
 defer func() {
  result = 1
  }()
 return result
}
```
return 1
BUT

```
func det()(int){
 result := 2
 defer func() {
  result = 1
  }()
 return result
}
```
return 2

why???

**Comment by ianlancetaylor** [comment]
This is not the best place for questions.  Please see https://golang.org/wiki/Questions .

The first example has a named result parameter, the second does not.  If a named result is changed in a defer statement, that changes the result.  If a local variable is changed in a defer statement, that does not affect the result.
