### ISSUE TITLE
net/http: useless string replace operation in Cookie.String

### ISSUE THREAD

**Issue by bronze1man** [golang/go#29135]
* isCookieNameValid do not allow "\r" "\n" appear in the cookie name.
https://github.com/golang/go/blob/master/src/net/http/cookie.go#L168
https://github.com/golang/go/blob/master/src/net/http/http.go#L50
https://github.com/golang/go/blob/master/src/internal/x/net/http/httpguts/httplex.go#L15

* sanitizeCookieName replace "\r" "\n" to "-"
https://github.com/golang/go/blob/master/src/net/http/cookie.go#L172

This replace operation should have no effect.So it can be delete to save cpu time and make code easier to read.

**Comment by mvdan** [comment]
@bronze1man do you plan on sending this as a CL for 1.13? In general it should be fine to send CLs without an issue, unless there's a bug to be tracked. Otherwise, if you don't plan on sending the CL, we can just close this issue.

**Comment by bronze1man** [comment]
Thanks for mention, I just find this bug when i read the source code. 
Sorry, I do not try to  send a CL at when i add the issue. 
I will try to send a CL soon.

**Comment by bradfitz** [comment]
Closing so I can take this over on Gerrit.

**Comment by bradfitz** [comment]
I meant to close the PR.
