### ISSUE TITLE
No 'socketcall' function on FreeBSD (golang.org/x/sys/unix/syscall_freebsd.go)

### ISSUE THREAD

**Issue by yurivict** [golang/go#29158]
```golang.org/x/sys/unix/syscall_freebsd.go``` doesn't have ```socketcall```.
As a result, this project https://github.com/Dreamacro/clash can't be built on FreeBSD.

```
===>  Building for clash-0.10.1
# github.com/Dreamacro/clash/proxy/redir
proxy/redir/tcp_freebsd.go:41:12: undefined: socketcall
proxy/redir/tcp_freebsd.go:41:23: undefined: GETSOCKOPT
```

https://github.com/golang/sys rev.70b957f

**Comment by ianlancetaylor** [comment]
There are only two systems that support `socketcall`: linux-386 and linux-s390.  And it's not an exported function anyhow.  I don't know where tcp_freebsd.go expects to find `socketcall`, but it's not going to come from the golang.org/x/sys/unix package.

**Comment by yurivict** [comment]
Ahh, I see, no such call exists.
