### ISSUE TITLE
x/tools/internal/lsp: rank types higher when completing in return of a function

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29152]
Example:
```go
func foo() <> {}
```

If we trigger completion at the `<>`, we should prioritize suggestions for types, not variables, etc.

**Comment by anjmao** [comment]
If I understood correctly for such example:

```go
var (
	a bool
	b int
)

type aa struct{}
type bb struct{}


func foo() <> {
}
```

structs aa, bb should be prioritized instead of a,b?

The problem I see that for suggestion for `a` returns `a, aa, append`, but `a` and `append` should not be shown as they are not types.

@stamblerre Could you please clarify a bit more why we want to show suggestions for declarations on function return, when I can work on this issue. Thanks.

**Comment by stamblerre** [comment]
Yeah, exactly, you want to show types aa and bb as the first options if you trigger a completion there. The code that does this for other cases is here: https://github.com/golang/tools/blob/b4b6fe2cb82970f144debbe03ecb71e340b15446/internal/lsp/source/completion.go#L548. 

I agree, you wouldn't want to show declarations at all, but I personally prefer ranking completions rather than hiding invalid completions. This can be buggy, particularly if you are working on an invalid piece of Go code, and I think it's better to show all available options to the user, even if they aren't necessarily correct.

**Comment by anjmao** [comment]
I think if possible completion should never suggest invalid options especially in strongly typed languages. If you check other languages like Typescript, C#, Java non of them will suggest declarations, but only types. I also checked GoLand IDE and it handles this case by not suggesting declarations as expected.

Then you writing a function there is no much room for other parts of code to be invalid as they are already declared before. I hardly imagine a case there you define a type with syntax errors and even if you write complete nonsense in that case it's better not to show suggestions at all as GoLand.

**Comment by stamblerre** [comment]
That makes sense, and ultimately I agree that we shouldn't show declarations. I would just prefer that, if you are going to work on this issue, we could start by ranking declarations lower rather than hiding them. 

If there are any bugs in the code, it would be really confusing to users why certain options aren't being shown, and it would be difficult to track down the cause. Anything that relates to the position of the cursor within incomplete code is tricky to debug, but once we are confident that the implementation is working as intended, we can take the extra step of removing invalid suggestion.

**Comment by anjmao** [comment]
@stamblerre Sounds good to me, I could start working on this, but before that I want to clarify one thing.

I tried this example:
```go
func t1Func() {}
type t1String string

func foo() <> {}
```
Under the <> path enclosing helper doesn't return *ast.FuncDecl inside Obj.
```
     0  *ast.Ident {
     1  .  NamePos: /Users/anjmao/s/astpartup/main.go:8:12
     2  .  Name: "t"
     3  .  Obj: nil
     4  }
```

For me this looks like a bug in PathEnclosingInterval, but if it's not a bug I could only traverse the whole file ast and check if it actually contains *ast.FuncDecl in range of current pos.

Thanks.
