### ISSUE TITLE
x/build: windows/arm builder got misconfigured

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#29155]
windows/arm builder looks misconfigured.

From https://build.golang.org/log/4d354f5970ff4e883ec131851af59fcdf1556dbb

```
ERROR: Cannot find C:\Data\Go\bin\go.exe
Set GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.

build failed: make script failed: exit status 1
```

@jordanrh1, please investigate. Thank you.

Alex

**Comment by jordanrh1** [comment]
Hey Alex, I updated the OS on the build machine earlier today and moved some things around. I've since fixed that issue and it's now building successfully:
https://farmer.golang.org/temporarylogs?name=windows-arm&rev=179909f20556262422a8b99c059eacdfcebc48ee&st=0xc425e2a2c0

**Comment by alexbrainman** [comment]
> I updated the OS on the build machine earlier today and moved some things around. I've since fixed that issue and it's now building successfully

SGTM. Thank you.

Lets watch and fix remaining errors.

Alex
