### ISSUE TITLE
x/tools/gopls: send back ranges for parse errors

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29150]
We currently only send the starting position of an error in LSP diagnostics. We should determine the end of the error as well. For type errors, we can just get the length of the identifier. We will need another approach for parse errors.

**Comment by zmb3** [comment]
Happy to take this one, but need some pointers on how to get to the identifier given just the `token.Position` from the error message.  Seems we need to convert to a `token.Pos`, I'm not sure how to convert in that direction.

**Comment by stamblerre** [comment]
@zmb3: I saw your reply and started trying to refactor things to make it easier to fix this bug, and then I got a bit carried away and got through about 3/4 of the fix myself. Did you want to fix this yourself or is it cool if I send out my CL?

**Comment by zmb3** [comment]
No, please go ahead and send your CL. I’m anxious to see what you came up with 😀

**Comment by stamblerre** [comment]
The above CL attempted to address this by using the AST to determine ranges for parse errors. However, this had the unexpected consequence of making the ranges either too large or unintuitive for the user. Most likely, we will want to modify the error ranges based on the type of the error, which will require error codes to allow us to distinguish between the different errors.

**Comment by stamblerre** [comment]
I don't think that this is actually necessary at this point. Until we have error codes or ranges coming back from go/parser, we can't make progress here. Going to close this issue.
