### ISSUE TITLE
doc: can not find document about type/const/var declare reference rule in the package scope and a function scope.

### ISSUE THREAD

**Issue by bronze1man** [golang/go#29168]
Please tell me wrong, if this stuff is already appeared in the document, I just do not find it.

I am writing a tool to find all reference source code of a program. I notice that follow program can not compile:
```golang
package main

import "fmt"

func main(){
	type t1 struct{
		f1 t2
	}
	type t2 struct{
	}
	fmt.Println(&t1{})
}
```
you will get an error `main.go:7:6: undefined: t2`.

But following program can compile:
```golang
package main

import "fmt"

func main(){
	fmt.Println(&t1{})
}

type t1 struct{
	f1 t2
}
type t2 struct{
}
```

So where is the document of type declare order in different scope?Will this behavior change in next golang version?

The best thing I can find is here: https://golang.org/ref/spec#Declarations_and_scope
```
The scope of a constant or variable identifier declared inside a function begins at the end of the ConstSpec or VarSpec (ShortVarDecl for short variable declarations) and ends at the end of the innermost containing block.
The scope of a type identifier declared inside a function begins at the identifier in the TypeSpec and ends at the end of the innermost containing block.
```

But it is not same as the type/const/var reference rule in package scope. It does match the behavior in the function scope.

**Comment by ztkmkoo** [comment]
@bronze1man 
please try
``` go
func main(){
        type t2 struct{
	}

	type t1 struct{
		f1 t2
	}
	
	fmt.Println(&t1{})
}
```

**Comment by bronze1man** [comment]
> please try 
Thanks @ztkmkoo , I know it works.
And I never wrote code that reference another type in a type declare in function scope before today. So I come across this problem only after I start write my reference finder tool.
I just want to know whether this behavior will never change in go1.

**Comment by ianlancetaylor** [comment]
Sorry, I'm not sure what you are asking.  You cite the exact part of the spec that answers your question.  It says "The scope of an identifier denoting a constant, type, variable, or function (but not method) declared at top level (outside any function) is the package block" and "The scope of a type identifier declared inside a function begins at the identifier in the TypeSpec and ends at the end of the innermost containing block."  It seems like those two sentences exactly answer your question.
