### ISSUE TITLE
cmd/asm: reject BSWAPW on amd64

### ISSUE THREAD

**Issue by omion** [golang/go#29167]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes (according to the current amd64enc.s file)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Omion\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Documents\ownCloud\go
set GOPROXY=
set GORACE=
set GOROOT=E:\Programs\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Programs\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Omion\AppData\Local\Temp\go-build669993050=/tmp/go-build -gno-record-gcc-switches</pre></details>

### What did you do?
Use the BSWAPW assembly instruction

### What did you expect to see?
The x86 XCHG instruction

### What did you see instead?
The x86 BSWAP instruction

Essentially, the problem is that the BSWAP instruction is undefined on 16-bit registers. [Intel's architecture programming manual](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) (page 3-112) says to use the XCHG instruction instead.
According to the Go asm testdata file amd64enc.s, the instruction "BSWAPW DX" uses the encoding 0x660fca. 0x66 is a size override and 0x0fca is the BSWAP instruction itself. XCHG exchanges the contents of two registers, which could be the 8-bit DH and DL registers for swapping DX.

**Comment by Quasilyte** [comment]
From the encoder point of view, `660fca` is a valid instruction and it's a BSWAP.
```
./xed -64 -d  '660fca'
660FCA
ICLASS: BSWAP   CATEGORY: DATAXFER   EXTENSION: BASE  IFORM: BSWAP_GPRv   ISA_SET: I486REAL
SHORT: bswap dx
```

It makes sense to emit something like `XCHGB DH, DL` for `BSWAPW DX`, but I remember the shift to more straightforward assembler, when no things MOV->XOR is performed, so it's closer to traditional assemblers.

GAS does not permit BSWAP with 16-bit arguments. Maybe instead of transforming BSWAP into XCHG we can forbid that form as well, forcing programmers to use `XCHGB` directly.

**Comment by omion** [comment]
Regarding breaking backward compatibility, the current form results in undefined behavior per Intel. I don't think changing something from "could do anything" to "does a specific thing" would be an issue for backward compatibility.

I suppose you are right that it's not really the encoding that's the problem. I don't really know much of the terminology, but I meant that it produces an instruction which is not allowed by the documentation. Intel's manual (linked to previously) says BSWAP "Reverses the byte order of a 32-bit or 64-bit (destination) register", and goes on saying to use XCHG for 16-bit.

Since the XCHGB assembly instruction exists I think forbidding BSWAPW completely sounds reasonable. On my computer BSWAPW doesn't do anything, so I doubt there are many people who actually use it.

**Comment by cameron-elliott** [comment]
Even though it looks decided, I would like to add some support and quote the [Intel Architecture Manual](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf#page=214):
[The bold and italics are mine]
> Reverses the byte order of a 32-bit or 64-bit (destination) register. This instruction is provided for converting little-endian values to big-endian format and vice versa. To swap bytes in a word value (16-bit register), use the XCHG instruction. **_When the BSWAP instruction references a 16-bit register, the result is undefined._**

**Comment by Quasilyte** [comment]
CC @cherrymui.

I can send a CL as soon as we decide on the exact action.

**Comment by rsc** [comment]
@quasilyte, let's reject BSWAPW. Thanks.
