### ISSUE TITLE
Please add `good first issue` label 

### ISSUE THREAD

**Issue by Tolsee** [golang/go#29164]
It is always a good idea to involve as more people as possible to the open source projects. I and, I hope, a lot of other people want to get through the iron gate of starting to contribute to open source projects. Adding `good first issue` label to issue tracker and allowing the newcomers to contribute will definitely be a great help for us.

Thanks!

**Comment by Tolsee** [comment]
Thanks! Can you add a description to it and you can close this issue.

**Comment by ALTree** [comment]
Done!
