### ISSUE TITLE
Missing #include in os/user/getgrouplist_darwin.go

### ISSUE THREAD

**Issue by fortuna** [golang/go#29170]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="<HIDDEN>"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="<HIDDEN>"
GOPROXY=""
GORACE=""
GOROOT="<HIDDEN>"
GOTMPDIR=""
GOTOOLDIR="<HIDDEN>"
GCCGO="gccgo"
CC="clang"
CXX="third_party/crosstool/v18/stable/toolchain/bin/x86_64-grtev4-linux-gnu-llvm_driver_is_not_gcc"
CGO_ENABLED="1"
GOMOD="<HIDDEN>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build029286707=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

From a Linux machine, I tried to build https://github.com/Jigsaw-Code/outline-ss-server for darwin amd64, and if failed with the message:
/usr/lib/google-golang/src/os/user/getgrouplist_darwin.go:16:11: warning: implicit declaration of function 'getgrouplist' is invalid in C99 [-Wimplicit-function-declaration]

The builds for Linux and Windows succeeded.

Looking at the golang source code, this is the offending call:
https://github.com/golang/go/blob/master/src/os/user/getgrouplist_darwin.go#L16

I believe the problem is that the C code for Darwin is missing the `#include <grp.h>` for [getgrouplist](http://man7.org/linux/man-pages/man3/getgrouplist.3.html). The [include is present in the unix counterpart](https://github.com/golang/go/blob/033d09493d3dc03fda13801902b6e2e102b9d73c/src/os/user/getgrouplist_unix.go#L13), which builds successfully.

### What did you expect to see?

Successful build

### What did you see instead?

The error above.
It should be an easy fix.

**Comment by ianlancetaylor** [comment]
On MacOS, `getgrouplist` is declared in <unistd.h>.  I suspect that you were using the GNU/Linux compiler when building for MacOS.  You need to use a cross-compiler, and that cross-compiler needs to have access to cross libraries.

Closing because I don't think there is anything to change in the Go tools.
