### ISSUE TITLE
runtime: append does not fail when length overflows

### ISSUE THREAD

**Issue by icza** [golang/go#29190]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/icza/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/icza/gows"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build173735906=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run the following app:

```
package main

import (
	"fmt"
	"math"
)

func main() {
	s := make([]struct{}, math.MaxInt64-2)
	fmt.Println(len(s), cap(s))
	for i := 0; i < 5; i++ {
		s = append(s, struct{}{})
		fmt.Println(len(s), cap(s))
	}
}
```

A slightly modified version is available and reproduces the error on the Go Playground: https://play.golang.org/p/AUKUBmQld_e

On the Playground `math.MaxInt32` is used instead of `math.MaxInt64`.

### What did you expect to see?

A panic saying:

    growslice: cap out of range

### What did you see instead?

The app did not fail. Capacity stops growing when it reaches `MaxInt64` on 64-bit architecture, and `MaxInt32` on 32-bit architectures, but length overflows and becomes negative.

```
9223372036854775805 9223372036854775805
9223372036854775806 9223372036854775806
9223372036854775807 9223372036854775807
-9223372036854775808 9223372036854775807
-9223372036854775807 9223372036854775807
-9223372036854775806 9223372036854775807
```

This is in clear violation of the [Spec: Length and capacity](https://golang.org/ref/spec#Length_and_capacity):

> At any time the following relationship holds:
>     0 <= len(s) <= cap(s)

as length becomes negative (and thus less than 0).

This report originates from this Stackoverflow question: https://stackoverflow.com/questions/53743099/behavior-of-append-when-appending-item-to-a-max-size-slice

**Comment by ianlancetaylor** [comment]
With Go 1.6 and gccgo I get the following crash.  With Go 1.7 and later the program succeeds incorrectly.

I'm going to mark this a release blocker for 1.13, but of course if we have a fix for 1.12 that would be nice.

```
9223372036854775805 9223372036854775805
9223372036854775806 9223372036854775806
9223372036854775807 9223372036854775807
panic: runtime error: growslice: cap out of range

goroutine 1 [running]:
panic
	../../../gccgo3/libgo/go/runtime/panic.go:588
main.main
	/home/iant/foo.go:12
exit status 2
```

**Comment by martisch** [comment]
From a quick look and test I think we can fix the issue by changing the comparison from INT to UINT here:
https://github.com/golang/go/blob/d70b0ece2f208ff99efce87c07f5171617c29a13/src/cmd/compile/internal/gc/ssa.go#L2457

With that change I get:
go run main.go 
9223372036854775805 9223372036854775805
9223372036854775806 9223372036854775806
9223372036854775807 9223372036854775807
panic: runtime error: growslice: cap out of range

goroutine 1 [running]:
main.main()
	/Users/martisch/test/main.go:71 +0x222
exit status 2



The cmd/compile/internal/gc/walk.go append code for appending lists does the same.

**Comment by dgryski** [comment]
> and assuming no one will ever write code appending MaxInt/2 arguments in a single append call - which likely would result in the parser running out of memory first

Does that include `a = append(a, b...)` where `len(b) > MaxInt/2` ?
