### ISSUE TITLE
net/http: TimeoutHandler does not support Pusher interface

### ISSUE THREAD

**Issue by inliquid** [golang/go#29193]
When used as a middleware `http.TimeoutHandler` breaks HTTP/2.0 Server Push mechanism, as its own writer does not support `http.Pusher` interface.

**Comment by Gnouc** [comment]
@inliquid can you give an example code?

**Comment by inliquid** [comment]
1. Set up middleware
```golang
func setupHandler(r *mux.Router) {
	if cfg.ServerUseGzip {
		server.Handler = alice.New(
			loggerMiddleware,
			throttleMiddleware,
			//timeoutMiddleware,  // <-- breaks Push
			compressMiddleWare,
			recoverMiddleware,
			sessionMiddleware,
			authMiddleware,
		).Then(r)
	} else {
		server.Handler = alice.New(
			loggerMiddleware,
			throttleMiddleware,
			//timeoutMiddleware,   // <-- breaks Push
			recoverMiddleware,
			sessionMiddleware,
			authMiddleware,
		).Then(r)
	}
}
```
2. `timeoutMiddleware` returns `http.TimeoutHandler` and is quite simple
```golang
func timeoutMiddleware(next http.Handler) http.Handler {
	return http.TimeoutHandler(next, time.Duration(cfg.ServerHandlerTimeout)*time.Second, http.StatusText(http.StatusServiceUnavailable))
}
```
3. Push something
```golang
	p, ok := w.(http.Pusher)
	if ok {
		if err := p.Push("/assets/css/pure/pure.css", &http.PushOptions{
			//Method: "GET",
			Header: http.Header{
				"Accept-Encoding": []string{"gzip"},
			},
		}); err != nil {
			logger.Error.Println("Error pushing pure.css!")
		}
	}
```
When `timeoutMiddleware` uncommented `ok == false` and `p == nil`

**Comment by Gnouc** [comment]
@inliquid Ah sorry, the example can be more simple by using code from blog. I mis-interpreted the response when trying it.

Can you try above commit if it's fixed for you.

**Comment by inliquid** [comment]
Ok, is there any instruction how to patch and test stdlib with this changes applied?

**Comment by Gnouc** [comment]
@inliquid I think there's no way unless you re-build your `go` binary from source.

**Comment by odeke-em** [comment]
Thank you for filing this bug @inliquid and @Gnouc for the preliminary questions.

@Gnouc in regards to your question in https://github.com/golang/go/issues/29193#issuecomment-447717573
here is a minimal repro to demonstrate this problem https://play.golang.org/p/e6Pr0U_pMCp or inlined below
```go
package main

import (
	"log"
	"net/http"
	"time"
)

func main() {
	hf := http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		rw.Write([]byte("OK"))
	})
	handler := http.TimeoutHandler(hf, 55*time.Second, "Timed out!")
	_, ok := handler.(http.Pusher)
	if !ok {
		log.Fatal("TimeoutHandler does not implement http.Pusher")
	}
	log.Print("TimeoutHandler implements http.Pusher")
}
```
which will print out 
```shell
TimeoutHandler does not implement http.Pusher
```

Thanks @Gnouc for the CL, we shall review it for Go1.13.

@bradfitz might you have a wishlist for interfaces that many of these helpers should implement? If so, let's review collaborate on this.

**Comment by Gnouc** [comment]
@odeke-em In case we have the wishlist, shall we implement in this issue or raise another one?

**Comment by odeke-em** [comment]
@Gnouc great question! So I think we should spin off another issue after we get the wishlist. That way if any rollback needs to be performed, it'll be piecemeal and this CL will stay in solid :)

**Comment by Gnouc** [comment]
@bradfitz can you please take a look?
