### ISSUE TITLE
A rather strange case of potentially faulty compilation result

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#29209]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

The symptom shows up in both go 1.11.2 and go 1.10.4.

### What operating system and processor architecture are you using (`go env`)?

<pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/howard/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/howard/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/howard/go"
GOTMPDIR=""
GOTOOLDIR="/home/howard/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build845145851=/tmp/go-build -gno-record-gcc-switches"
</pre>

### What did you do?

1. Clone github.com:HouzuoGuo/laitos
2. git checkout aea8104ea4aac44dd9afa2b6148a2ec923fc8fc4
3. env CGO_ENABLED=0 go build

Calculate the sha1sum of result executable, on my computer it shows 32326ae652919cc96eaa78e1f0cf94c7dd82ce66

Next, compile the same repository at commit `aea8104ea4aac44dd9afa2b6148a2ec923fc8fc4~1` and recalculate digest, the executable turns out to have remained unchanged, though the commit itself should most definitely result in a change in compiled executable.

Here is the commit on github web: https://github.com/HouzuoGuo/laitos/commit/aea8104ea4aac44dd9afa2b6148a2ec923fc8fc4

**Comment by randall77** [comment]
This is expected.
You only changed dead code with that commit.
The first part of `func (daemon *Daemon) MaintainWindowsIntegrity(out *bytes.Buffer)` checks if the platform is Windows, and if not immediately returns.  That check is a compile time constant. On linux all the following code (including all code changed in the commit referenced) never makes it to the executable.

**Comment by HouzuoGuo** [comment]
thanks, that makes a lot of sense indeed.
