### ISSUE TITLE
panic on range map 

### ISSUE THREAD

**Issue by ZCT** [golang/go#29216]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.9
</pre>

### Does this issue reproduce with the latest release?
can't

</pre></details>

### What did you do?

In my team product enviroment, the core server(written in go) process request  2000 qps/s for half an year.  Today I received a panic alarm(only one),  the panic  stacktrace is like :

```
panic in handler: runtime error: invalid memory address or nil pointer dereference: goroutine 332192160 [running]:
panic(0xdd36c0, 0x14b5180)
       /usr/local/go/src/runtime/panic.go:491 +0x283
metrics.(*MetricsClient).emit(0xc4214b1920, 0x0, 0xf05567, 0xc, 0xd891a0, 0xfb7a30, 0xf0be18, 0x13, 0xc4350955c0, 0x0, ...)
     .../metrics/metrics.go:180 +0x170

```
here is the emit function code:
![image](https://user-images.githubusercontent.com/4023051/49940449-76abc000-ff1a-11e8-8f4b-43f903e4d896.png)

I and my teammate checked that not exist write behavior to the tagkv(map[string]string), only read
## What did you expect to see?

why panic on line 180, which behavior could reproduce this.  It seem's only happen once

**Comment by bradfitz** [comment]
You likely have a data race.

See https://blog.golang.org/race-detector

For questions about Go, see https://golang.org/wiki/Questions.

**Comment by ZCT** [comment]
> You likely have a data race.
> 
> See https://blog.golang.org/race-detector
> 
> For questions about Go, see https://golang.org/wiki/Questions.

thank your reply. I look over this code and use the go race-detector checked, there is no data race. The tagkv is declared and created in the current goroutine, it  can't access from other goroutine. 

I wonder may be the painc stack trace report the wrong line number?  it is possible?
