### ISSUE TITLE
go mod does not work correct

### ISSUE THREAD

**Issue by Dexus** [golang/go#29227]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/josef/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/josef/Dokumente/go:/home/josef/.gvm/pkgsets/go1.11.2/global"
GOPROXY=""
GORACE=""
GOROOT="/home/josef/.gvm/gos/go1.11.2"
GOTMPDIR=""
GOTOOLDIR="/home/josef/.gvm/gos/go1.11.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build124072828=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go mod vendor
go build .
```

in go.sum the package is included and also in den vendor folder
```
github.com/crewjam/errset v0.0.0-20160219153700-f78d65de925c h1:dCJ9oZ0VgnzJHR5BjkSrwkXA1USu483qlxBd0u29P8s=
github.com/crewjam/errset v0.0.0-20160219153700-f78d65de925c/go.mod h1:XhiWL7J86xoqJ8+x2OA+AM2l9skQP2DZ0UOXQYVg7uI=
```

### What did you expect to see?
find the package that used in https://git.deineagentur.com/DeineAgenturUG/go-xmlsec

### What did you see instead?
```
/go/pkg/mod/git.deineagentur.com/!deine!agentur!u!g/go-xmlsec@v0.0.0-20181213193329-d0d888c16029/error.go:8:2: unknown import path "github.com/crewjam/errset": cannot find package
```

**Comment by bcmills** [comment]
Please update the issue description to describe the problem in more specific terms.

Please also provide concrete steps that we can follow to reproduce the problem starting in an empty directory. My attempt, using a `go` binary build from `HEAD`, works as expected:

```
$ go mod init golang.org/issue/scratch
go: creating new go.mod: module golang.org/issue/scratch

$ cat > main.go
package main
import _ "github.com/crewjam/errset"
func main() {}

$ go mod vendor
go: finding github.com/crewjam/errset latest
go: downloading github.com/crewjam/errset v0.0.0-20160219153700-f78d65de925c
go: extracting github.com/crewjam/errset v0.0.0-20160219153700-f78d65de925c

$ go build .

$
```

**Comment by bcmills** [comment]
Ah, the problem is evident from your `go env` output:
```
GOMOD=""
```

You are running in `GOPATH` mode: either you are inside `GOPATH/src`, or you did not first run `go mod init`. To force module mode, set `GO111MODULE=on` in your environment.
