### ISSUE TITLE
cmd/go: directory traversal via curly braces in import paths [Go 1.11]

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29235]
This is a tracking issue for #29231, a security vulnerability fixed in Go 1.11.3.

**Comment by tomislavmitic2012** [comment]
@FiloSottile  You have just broken every one that uses packages such as gobuffalo/pop/ which were gotten previously with ```go get github.com/gobuffalo/pop/...``` the only way to fix it is to downgrade to go 1.11.2. How go you suggest we proceed.

**Comment by tomislavmitic2012** [comment]
Breaking change is here, this totally needs to be reverted https://github.com/golang/go/commit/8954addb3294a5e664a9833354bafa58f163fe8f#diff-5b11f198c631a3d489e1be171853ab7bR40

**Comment by FiloSottile** [comment]
We know it's broken, see #29241. You can run `go get -d github.com/gobuffalo/pop && go get github.com/gobuffalo/pop/...` instead for now. We are not reverting a security fix, but will fix the regression in the upcoming minor release.
