### ISSUE TITLE
cmd/compile: remove badgerbadgerbadger optimization?

### ISSUE THREAD

**Issue by josharian** [golang/go#29242]
From walk.go:

```go
func walkcompareString(n *Node, init *Nodes) *Node {
	// s + "badgerbadgerbadger" == "badgerbadgerbadger"
	if (n.Op == OEQ || n.Op == ONE) && Isconst(n.Right, CTSTR) && n.Left.Op == OADDSTR && n.Left.List.Len() == 2 && Isconst(n.Left.List.Second(), CTSTR) && strlit(n.Right) == strlit(n.Left.List.Second()) {
		r := nod(n.Op, nod(OLEN, n.Left.List.First(), nil), nodintconst(0))
		return finishcompare(n, r, init)
	}

	// cont...
```

I've always been skeptical that anyone writes code that matches this pattern; I'd like to remove it.

Thoughts/objections?

cc @mdempsky @randall77

**Comment by randall77** [comment]
Fine by me. Might want to double-check that the stdlib doesn't have any (except a possible test for this optimization).

**Comment by seebs** [comment]
That is a very common pattern... in bourne shell. Where the idiom is `test "x$foo" != "x"` as a workaround to handle cases where `$foo` might contain something that would be interpreted as a flag by the `test` command's option parser. I've also seen it in Makefiles, I think. I agree that it seems vanishingly unlikely to show up in go.

Also why is the function not called `walkCompareString` with a capital C?

**Comment by mdempsky** [comment]
> Also why is the function not called walkCompareString with a capital C?

It's a subroutine of the vestigially-named `walkcompare` function. We try to toe a balance between adopting current Go conventions and staying consistent with the current archaic code base.

See also #27167.

**Comment by rsc** [comment]
For the record, this was here because of https://groups.google.com/g/golang-nuts/c/7Ks1iq2s7FA/m/rS60bS4aMi4J.
