### ISSUE TITLE
cmd/go: "go get" fails on import path patterns with wildcards ("...")

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29241]
The fix for `cmd/go: remote command execution during "go get -u"` (#29230) as released in Go 1.10.6 and 1.11.3 introduced a regression causing commands like `go get example.com/...` to fail with `invalid import path: malformed import path "example.com/...": double dot` when fetching packages not already present in GOPATH.

See https://github.com/golang/go/issues/29236#issuecomment-447144051

**Comment by jadr2ddude** [comment]
# Looking through the code, I saw the following mistakes that could have caused this error:

Error 1 - `strings.Contains(path, "..")` creates false positives with `something/...`
https://github.com/golang/go/commit/8954addb3294a5e664a9833354bafa58f163fe8f#diff-5b11f198c631a3d489e1be171853ab7bR40

Error 2 - the `...` path would cause this to error too, since it is all `.`
https://github.com/golang/go/commit/8954addb3294a5e664a9833354bafa58f163fe8f#diff-5b11f198c631a3d489e1be171853ab7bR70

# Suggested Fix

Remove the check listed in error 1. In addition to causing false positives, it is rendered unnecessary by the line mentioned in error 2. Leave the line in error 2 unchanged, but add a check that skips this validation for the last element if it exactly matches `...`.

**Comment by jadr2ddude** [comment]
Is someone currently working on this? If not, I can try to create a fix.

**Comment by jadr2ddude** [comment]
In absence of a response, I have started fixing this.

**Comment by FiloSottile** [comment]
Thank you, but I believe @dmitshur and @bcmills are already moving on a fix.

**Comment by jadr2ddude** [comment]
Ok. Thank you for letting me know.

**Comment by willbuckner** [comment]
```
diff --git a/src/cmd/go/internal/get/path.go b/src/cmd/go/internal/get/path.go
index d443bd28a9..2a109d6638 100644
--- a/src/cmd/go/internal/get/path.go
+++ b/src/cmd/go/internal/get/path.go
@@ -41,9 +41,6 @@ func checkPath(path string, fileName bool) error {
        if path == "" {
                return fmt.Errorf("empty string")
        }
-       if strings.Contains(path, "..") {
-               return fmt.Errorf("double dot")
-       }
        if strings.Contains(path, "//") {
                return fmt.Errorf("double slash")
        }
@@ -59,8 +56,10 @@ func checkPath(path string, fileName bool) error {
                        elemStart = i + 1
                }
        }
-       if err := checkElem(path[elemStart:], fileName); err != nil {
-               return err
+       if path[elemStart:] != "..." {
+               if err := checkElem(path[elemStart:], fileName); err != nil {
+                       return err
+               }
        }
        return nil
 }
```

**Comment by bcmills** [comment]
@gopherbot, please backport to 1.11 and 1.10 immediately: this is a major regression.

**Comment by thaJeztah** [comment]
@FiloSottile I noticed that `go list ./...` still works on Go 1.11.3 (and Go 1.10.6). While it's usable as a workaround for this regression (https://github.com/containerd/containerd/pull/2879), wondering if that's actually something that was missed in the patch release (or won't `go list` have the same security issue? I didn't dive deep into the fix that went into those patch releases 😅)

**Comment by thaJeztah** [comment]
@bcmills ah, makes sense, thanks for confirming it's nothing to worry about 👍

**Comment by johan-lejdung** [comment]
Is there any workaround or planned fix for this?

**Comment by ldez** [comment]
The release is already done since 2 days: https://github.com/golang/go/releases/tag/go1.11.4 and https://github.com/golang/go/releases/tag/go1.10.7

**Comment by johan-lejdung** [comment]
Ah thanks! I was looking at the docker images. Do those follow a different release schedule?

**Comment by jadr2ddude** [comment]
@johan-lejdung https://github.com/docker-library/golang/issues/255 - the docker tags are currently in progress
