### ISSUE TITLE
how use SetUnhandledExceptionFilter to golang

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#29250]
i need dump file when app crash on windows，but i don't know how use to golang？

**Comment by ianlancetaylor** [comment]
You are more likely to get an answer to this on a forum.  Please see https://golang.org/wiki/Questions .

**Comment by alexbrainman** [comment]
Perhaps #20498 is related.

Alex

**Comment by andybons** [comment]
Without more information to go off of, there's not much we can do to help, here. Closing.
