### ISSUE TITLE
after setup GO111MODULE=on, how to download a denpendency package  in any directory 

### ISSUE THREAD

**Issue by orange-jacky** [golang/go#29256]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
 i setup export GO111MODULE=off, i can download a denpendency package by go get xxx in anywhere
 i setup export GO111MODULE=on, i can't download a denpendency package by go get xxx in anywhere

after create a tmp directory , and run go mod init tmp,   and go get xxxx, it can download the xxx package
when  i setup export GO111MODULE=on, i wish download a denpendency package by go get xxx in anywhere, can you tell me how to do ?

**Comment by orange-jacky** [comment]
before not use go modules, you can download a library in any directory by running go get xxxx
after using go modules, you must entry a directory which have a go.mod file, than you can run go get xxx download library to $GOPATH/pkg/mod, it's hard than not use go modules.
i want to know that when i setup GO111MODULE=on, how to download a library in any directory without a go.mod file

**Comment by bcmills** [comment]
Please clarify what you mean by “download”. What do you want to do with the package once you've downloaded it?

**Comment by bcmills** [comment]
Use `go1.12beta1`. Both `go get` and `go mod download` should work outside of a module.
