### ISSUE TITLE
cmd/vet: "go vet --shadow" used to work, does not work

### ISSUE THREAD

**Issue by kevinburke** [golang/go#29260]
I have a test runner that calls `go vet --all && go vet --shadow`: https://github.com/kevinburke/go-bindata/blob/master/testdata/Makefile

This test runner breaks on `tip`:

```
$ go vet --shadow
vet: flag "--shadow" not defined
Run "go help vet" for more information
```

I'm not sure if the compatibility guarantee extends to flag arguments, but it's a little frustrating that this program broke and it took some searching to figure out how to fix it. Searching Google yields mostly results that expect "go vet --shadow" to work as previously written.

**Comment by ALTree** [comment]
I suspect this is WAI. See the discussion in #28622, in particular Alan's comment at https://github.com/golang/go/issues/28622#issuecomment-437149031.

**Comment by ianlancetaylor** [comment]
@alandonovan Is there an existing shadow checker somewhere that uses the new framework that people can use?

**Comment by ianlancetaylor** [comment]
Marking for 1.12 because if nothing else this needs to be mentioned in the release notes.

**Comment by alandonovan** [comment]
>  Is there an existing shadow checker somewhere that uses the new framework that people can use?

Yes, see `go help vet`:

```
$ go help vet 
usage: go vet [-n] [-x] [-vettool prog] [build flags] [vet flags] [packages]

Vet runs the Go vet command on the packages named by the import paths.
...
The -vettool=prog flag selects a different analysis tool with alternative
or additional checks.
For example, the 'shadow' analyzer can be built and run using these commands:

  go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
  go vet -vettool=$(which shadow)

...
See also: go fmt, go fix.
```

The reason this checker is not included in the new vet is that it was the sole "experimental" checker, and I didn't think it warranted the introduction of the "experimental" concept to the new API.  If we can improve the heuristics used by 'shadow' to the point where it would no longer be considered experimental then there's no reason not to add it back to the core vet suite.

**Comment by petar-dambovaliev** [comment]
> > Is there an existing shadow checker somewhere that uses the new framework that people can use?
> 
> Yes, see `go help vet`:
> 
> ```
> $ go help vet 
> usage: go vet [-n] [-x] [-vettool prog] [build flags] [vet flags] [packages]
> 
> Vet runs the Go vet command on the packages named by the import paths.
> ...
> The -vettool=prog flag selects a different analysis tool with alternative
> or additional checks.
> For example, the 'shadow' analyzer can be built and run using these commands:
> 
>   go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
>   go vet -vettool=$(which shadow)
> 
> ...
> See also: go fmt, go fix.
> ```
> 
> The reason this checker is not included in the new vet is that it was the sole "experimental" checker, and I didn't think it warranted the introduction of the "experimental" concept to the new API. If we can improve the heuristics used by 'shadow' to the point where it would no longer be considered experimental then there's no reason not to add it back to the core vet suite.

You can come up with many fancy explanations to justify the decision.
The bottom line is that people used that feature and relied on it and it was taken out.
Everything else is noise.

**Comment by mvdan** [comment]
Quick reminder to only comment if you have an idea or constructive feedback. A new issue would probably be better too, as this issue is closed and isn't the best place to discuss.

In any case, personal opinions and criticism don't add to the thread.
