### ISSUE TITLE
cmd/go: TestNewReleaseRebuildsStalePackagesInGOPATH modifies code in GOROOT

### ISSUE THREAD

**Issue by bcmills** [golang/go#29263]
`go test cmd/go` should succeed even if the user cannot write to `GOROOT`, as may be the case if the Go toolchain is provided by a system distribution. (See also #28387.)

Unfortunately, today `TestNewReleaseRebuildsStalePackagesInGOPATH` assumes that it can write to `GOROOT/src`:
https://github.com/golang/go/blob/dbd323bb880ff27fa9b4bdfebf3e5d4828b09678/src/cmd/go/go_test.go#L903

That not only risks a failed write to an unwritable directory, but also makes `go test cmd/go` dangerous to run concurrently with *any* build information, and potentially introduces spurious diffs during testing in development copies of the `go` repository.

**Comment by ianlancetaylor** [comment]
I sent a fix for that test but there are probably others.
