### ISSUE TITLE
go/doc: panic in go/doc.lastComment when parsing an Example_foo with no body

### ISSUE THREAD

**Issue by bcmills** [golang/go#29271]
@alandonovan found this panic in #28044: https://play.golang.org/p/Gs4iMjqFmgu

With this input program:
```go
package p
func Example() {}
func Example_a()
```

`doc.Examples` panics with this stack trace:
```
go/ast.(*BlockStmt).Pos(...)
	/usr/local/go/src/go/ast/ast.go:728
go/doc.lastComment(0x0, 0x0, 0x0, 0x0, 0x15d060, 0x92a)
	/usr/local/go/src/go/doc/example.go:409 +0x6
go/doc.exampleOutput(0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x40e238, 0x0)
	/usr/local/go/src/go/doc/example.go:108 +0x40
go/doc.Examples(0x42bf90, 0x1, 0x1, 0x197480, 0x1e9cb8, 0x0, 0x437580, 0x0)
	/usr/local/go/src/go/doc/example.go:75 +0x320
```

CC @griesemer

**Comment by rcodeb** [comment]
Sorry to barge in, I believe, https://github.com/golang/go/blob/master/src/go/doc/example.go#L389 here there should be a check for the nil body.

**Comment by agnivade** [comment]
Will take a look.

**Comment by rcodeb** [comment]
@agnivade may be return from the function where I pointed in my comment as returning nil will be ok for pointer to file return type.

**Comment by agnivade** [comment]
Please comment on the CL as it will be easier to review there.
