### ISSUE TITLE
go get with triple dot  doesn't work with 1.10.6 and 1.11.3

### ISSUE THREAD

**Issue by Random-Liu** [golang/go#29273]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.6 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yeah, it only happens on latest versions, 1.10.6 and 1.11.3.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/lantaol/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/lantaol/workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build485540701=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go get -d github.com/kubernetes-sigs/cri-tools/...

### What did you expect to see?
The command should succeed.

It succeeds with previous versions, e.g. go 1.11.2.

### What did you see instead?
package github.com/kubernetes-sigs/cri-tools/...: github.com/kubernetes-sigs/cri-tools/...: invalid import path: malformed import path "github.com/kubernetes-sigs/cri-tools/...": double dot

**Comment by ALTree** [comment]
Thanks for the report. 

This is #29241, so I'm closing this in favour of the older thread.

**Comment by Random-Liu** [comment]
@ALTree Thanks for the pointer!
