### ISSUE TITLE
x/build/cmd/gopherbot: close-cherry-pick pass too aggressive

### ISSUE THREAD

**Issue by bradfitz** [golang/go#29270]
Seen on #28673, the gopherbot `close-cherry-pick` pass is too aggressive:

```
2018/12/14 20:05:49 got corpus update after 6.071844875s
close-cherry-pick
        https://golang.org/issue/28673  x/net/http2: Transport is leaking streams on broken Body [1.11 backport]
```

/cc @FiloSottile @dmitshur

**Comment by dmitshur** [comment]
I think it's missing a `|| gi.HasEvent("reopened")` check, to make it not fight humans who might've re-opened the issue. Of course, it will still fight one time (due to #21312), but no more. Will send a CL.

**Comment by dmitshur** [comment]
I've redeployed `gopherbot` with the fix.
