### ISSUE TITLE
cmd/go: go list -e should list a package containing an error if files named on the command line do not exist

### ISSUE THREAD

**Issue by mvdan** [golang/go#29280]
```
$ go version
go version devel +47fb1fbd55 Fri Dec 14 16:18:51 2018 +0000 linux/amd64
$ cd go/src/golang.org/x/tools
$ git show HEAD --no-patch
commit 3c39ce7b61056afe4473b651789da5f89d4aeb20 (HEAD -> master, origin/master, origin/HEAD)
Author: Brad Fitzpatrick <bradfitz@golang.org>
Date:   Fri Dec 14 14:45:46 2018 +0000

    tip: fix, update tip.golang.org
[...]
$ go install ./go/packages/gopackages
$ gopackages missing.go; echo $?
gopackages: go [list -e -json -compiled -test=false -export=false -deps=true -- missing.go]: exit status 1: stat missing.go: no such file or directory
1
$ gopackages -mode syntax missing.go; echo $?
0
```

Seems to me like the `LoadSyntax` mode should error too. Found while porting https://github.com/mvdan/gogrep from `go/loader` to `go/packages`, since some error test cases stopped erroring as expected.

/cc @ianthehat @matloob

**Comment by mvdan** [comment]
Thanks for the quick reply. It sounds to me like most tools out there want to check for most or all errors, and the fact that `Load` returns an error seems to tell that it's enough to check that one. So it can be easy to forget to check each package's `Errors` field.

Perhaps this should be clearer in the docs, e.g. via an example that most static analysis tools should follow.

**Comment by mvdan** [comment]
Here's another bug - missing files in syntax mode produce no command-line-arguments package at all, which seems like a bug to me too:

```
$ gopackages -mode syntax empty.go
Go package "command-line-arguments":
        package
        has complete exported type info
        -:
empty.go:1:1: expected 'package', found 'EOF'
$ gopackages -mode syntax missing.go
```

This is on x/tools 13ba8ad772dfbf0f451b5dd0679e9c5605afc05d and `go version devel +47fb1fbd55 Fri Dec 14 16:18:51 2018 +0000 linux/amd64`.

**Comment by dominikh** [comment]
It should be noted that this issue is (no longer?) limited to LoadSyntax. It occurs in all modes.

```
desktop ~ $ for mode in files imports types syntax allsyntax; do gopackages -mode $mode /does/definitely/not/exist.go; echo $?; done
0
0
0
0
0
```

**Comment by matloob** [comment]
@dominikh I think the 0 exit status is working as intended. In these cases, go/packages should return a package with a non-empty Errors field. Is it not doing that?

**Comment by dominikh** [comment]
@matloob for me, it returns zero packages and no error.

**Comment by mvdan** [comment]
@matloob I think you forgot to repurpose this issue?

**Comment by matloob** [comment]
@mvdan I retitled the issue, sorry about that!
@dominikh Hmm... let me look into that...

**Comment by bcmills** [comment]
@matloob, could you clarify the issue with `cmd/go`? I don't know what an “ad-hoc” package is or what it means for such a thing not to exist.

**Comment by ianthehat** [comment]
An ad-hoc package is the term used throughout the tools for one formed when you pass the go command a list of files.
@matloob means that one or more of the files did not exist, which should result in an error on the package in the output, not go list failing.

**Comment by bcmills** [comment]
@mvdan, this appears to be fixed at head. Can you confirm?

```
~/src/golang.org/x/tools$ go version
go version devel +c49fd86ad9 Fri Dec 6 15:13:20 2019 -0500 linux/amd64

~/src/golang.org/x/tools$ gopackages -mode syntax missing.go
Go package "missing.go":
        package
        has complete exported type info
        -: cannot find module providing package missing.go: unrecognized import path "missing.go": https fetch: Get "https://missing.go/?go-get=1": dial tcp: lookup missing.go on 127.0.0.1:53: no such host
```

CC @jayconrod

**Comment by mvdan** [comment]
Yes, I no longer see this bug - I checked both module mode and GOPATH mode.

There were a number of CLs above, so it's hard to see exactly when this happened. I assume `go list` got a proper fix at some point :)
