### ISSUE TITLE
go module replace does not work

### ISSUE THREAD

**Issue by dapengjun** [golang/go#29299]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

go module replace in go.mod does not work.
![image](https://user-images.githubusercontent.com/9162928/50064345-9cbbb380-01eb-11e9-8644-5a609fa6b95d.png)

### What did you expect to see?
download from github.com/grpc/grpc-go not from google.golang.org/grpc 

### What did you see instead?
download from google.golang.org/grpc , replace does not work

**Comment by oiooj** [comment]
@dapengjun  Add a require for `google.golang.org/grpc`


```
module route

require google.golang.org/grpc v1.17.0

replace google.golang.org/grpc => github.com/grpc/grpc-go v1.17.0

```

**Comment by go101** [comment]
In 1.12, the requirement line will be not needed any more. https://github.com/golang/go/issues/26241

**Comment by dapengjun** [comment]
@oiooj Thank you, It works.
