### ISSUE TITLE
hello.SupportedProtos undefined (type *tls.ClientHelloInfo has no field or method SupportedProtos)

### ISSUE THREAD

**Issue by kumarkeviv** [golang/go#29303]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.7.4 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Yes, its the latest version.

### What operating system and processor architecture are you using (`go env`)?
Operating System : Rasbian 4.14.71-v7+
Processor Architecture: ARM

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build519676947=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
</pre></details>

### What did you do?

I wrote a program which makes an network connection to specified MailServer using IP and checks if the server is up or not. My program is working absolutely fine when I compile the code and run on Windows / Mac machine.

I used the command "go run main.go", I also downloaded all the dependency using "go get -d". Also the GOPATH is set.

### What did you expect to see?
As the application was working fine on windows and mac I am expecting the application to be live on the rasp pi machine and ready to accept the request to perform operation.

### What did you see instead?
But every-time I run the program I get the below error:

```
# golang.org/x/crypto/acme/autocert
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:301: hello.SupportedProtos undefined (type *tls.ClientHelloInfo has no field or method SupportedProtos)
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:311: hello.SignatureSchemes undefined (type *tls.ClientHelloInfo has no field or method SignatureSchemes)
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:314: hello.SignatureSchemes undefined (type *tls.ClientHelloInfo has no field or method SignatureSchemes)
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:315: undefined: tls.SignatureScheme
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:317: undefined: tls.ECDSAWithP256AndSHA256
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:318: undefined: tls.ECDSAWithP384AndSHA384
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:318: undefined: tls.ECDSAWithP521AndSHA512
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:344: undefined: tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
../../go/src/golang.org/x/crypto/acme/autocert/autocert.go:347: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
```

I am stuck on this problem from many days any help would be highly helpful.

**Comment by x1ddos** [comment]
That's quite an old version. The latest is go1.11.4 if I'm not mistaken.

> any help would be highly helpful

Switch to a newer Go version?

**Comment by kumarkeviv** [comment]
@x1ddos That was the issue. Thanks
Closing the issue now.
