### ISSUE TITLE
cmd/compile, cmd/link: relocation target go.builtin.error.Error not defined

### ISSUE THREAD

**Issue by akavel** [golang/go#29304]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

Repro on play.golang.org.

### What did you do?

https://play.golang.org/p/6NvGso5fqRg

```go
package main

import (
	"fmt"
)

func main() {
	var err error
	fmt.Println(error.Error(err))
}
```

### What did you expect to see?
Some understandable/user-friendly error message, pointing to line 9. (Or, actually, maybe this line is actually correct and should compile? Not 100% sure. With go1.9 it seemed to compile correctly and work!)

### What did you see instead?
```
main.main: relocation target go.builtin.error.Error not defined
```

**Comment by bradfitz** [comment]
This worked in Go 1.10 but was broken in Go 1.11.

cmd/compile succeeds but cmd/link fails. Not sure whether cmd/compile output garbage, though.

```
bradfitz@gdev:~$ cat > x.go
package main

import (
        "fmt"
        "reflect"
)

func main() {
        fmt.Println(reflect.TypeOf(error.Error))
}


bradfitz@gdev:~$ GOROOT=$HOME/go1.10 go run x.go
func(error) string

bradfitz@gdev:~$ GOROOT=$HOME/go1.11 go run x.go
# command-line-arguments
go.builtin.error.Error·f: relocation target go.builtin.error.Error not defined

bradfitz@gdev:~$ go run x.go
# command-line-arguments
go.builtin.error.Error·f: relocation target go.builtin.error.Error not defined
```

/cc @griesemer @mdempsky @josharian @cherrymui @heschik @ianlancetaylor

**Comment by bradfitz** [comment]
Probably warrants a backport too.

**Comment by ALTree** [comment]
git bisect points to 80bbad015d2f3f9407873c1657839a8a61d5f433 (cmd/compile: omit unnecessary interface method expression wrappers).

**Comment by griesemer** [comment]
Simpler reproducer:
```Go
package main

func main() {
	_ = error.Error(nil)
}
```

**Comment by bradfitz** [comment]
@gopherbot, please backport to Go 1.11.
