### ISSUE TITLE
cmd/go: get fails to get github.com/mibk/g..

### ISSUE THREAD

**Issue by nkovacs** [golang/go#29302]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. This is a side effect of the security fix in 1.11.3, https://github.com/golang/go/issues/29230.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nkovacs/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nkovacs/progs/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build928219988=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
go get -u github.com/mibk/g..
```

### What did you expect to see?

g.. successfully installed.

### What did you see instead?

package github.com/mibk/g..: github.com/mibk/g..: invalid import path: malformed import path "github.com/mibk/g..": double dot

**Comment by agnivade** [comment]
The fix was made in 1.11.4 (https://github.com/golang/go/issues/29241), which you seem to have. Are you certain there are no conflicting versions of Go installed ?

**Comment by nkovacs** [comment]
I believe the fix in 1.11.4 only fixed `go get github.com/user/repo/...`

**Comment by shuLhan** [comment]
@nkovacs 

I believe "g.." is violating package name [1].  Even if its work with previous Go version, it should not.

[1] https://golang.org/ref/spec#PackageName

**Comment by nkovacs** [comment]
g.. is not the package name though. It's just the repo name. The package name is `main`.

**Comment by agnivade** [comment]
I see. The repo name itself is `g..`.

/cc @bcmills

**Comment by bcmills** [comment]
Sorry, but there are too many ways to play games with leading and trailing dots to produce name collisions on various filesystems, and this particular example appears to be deprecated since Go 1.9 anyway.
