### ISSUE TITLE
x/tools/go/analysis: asmdecl requires incorrect array offsets

### ISSUE THREAD

**Issue by mmcloughlin** [golang/go#29318]
I believe that the `asmdecl` vet check reports incorrect offsets for arrays within recursive structures. See the following reproducer:

https://gist.github.com/mmcloughlin/dfb91a6a97727666b90b8ccb5c0c553d

```
$ go version
go version devel +99e4ddd053 Tue Dec 18 00:13:58 2018 +0000 darwin/amd64
$ go vet
...
./asm_amd64.s:6:1: [amd64] ArrayIndex3: invalid offset s_Array_3+32(FP); expected s_Array_3+24(FP)
```

I suspect the following line is missing `off+`

https://github.com/golang/tools/blob/13ba8ad772dfbf0f451b5dd0679e9c5605afc05d/go/analysis/passes/asmdecl/asmdecl.go#L493

**Comment by mmcloughlin** [comment]
@alandonovan

**Comment by alandonovan** [comment]
@josharian @aclements
