### ISSUE TITLE
time.After lead to mem leak??

### ISSUE THREAD

**Issue by templarzq** [golang/go#29316]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.10.1
</pre>

### Does this issue reproduce with the latest release?

same by go 1.11

### What operating system and processor architecture are you using (`go env`)?
centos 7.2
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS linux
GOARCH amd64
</pre></details>

### What did you do?

```
type ISemaphore interface {
	Acquire() error
	Release() error
}

type implementation struct {
	sem     chan struct{}
	timeout time.Duration
}

func (s *implementation) Release() error {
	select {
	case s.sem <- struct{}{}:
		return nil
		//case <-time.After(s.timeout):
		//	return ErrNoTickets
	}
}

func (s *implementation) Acquire() error {
	select {
	case _ = <-s.sem:
		return nil
		//case <-time.After(s.timeout):
		//	return ErrIllegalRelease
	}

	return nil
}

func NewSemaphore(tickets int, timeout time.Duration) ISemaphore {
	return &implementation{
		sem:     make(chan struct{}, tickets),
		timeout: timeout,
	}
}
```
### What did you expect to see?

use the struct as a custom semaphore

### What did you see instead?

mem leak

**Comment by templarzq** [comment]
mybe this is the cause of issue #29208

**Comment by randall77** [comment]
As much as you can, please post a full program (one with a `main`in it), show the command line you used to run it, and what error you got.

How do you know there is a memory leak?

**Comment by templarzq** [comment]
> 
> 
> As much as you can, please post a full program (one with a `main`in it), show the command line you used to run it, and what error you got.
> 
> How do you know there is a memory leak?

(pprof) top20 -cum
Showing nodes accounting for 64.53GB, 99.94% of 64.57GB total
Dropped 83 nodes (cum <= 0.32GB)
      flat  flat%   sum%        cum   cum%
         0     0%     0%    64.53GB 99.94%  time.After
   61.93GB 95.91% 95.91%    64.53GB 99.94%  time.NewTimer
         0     0% 95.91%    32.34GB 50.08%  ElasticComputeEngine/ComputeTaskHandler/Operations.(*Op_DiscreteRatio).Compute
         0     0% 95.91%    32.34GB 50.08%  ElasticComputeEngine/ComputeTaskHandler/Operations.(*Op_DiscreteRatio).Receive.func1
         0     0% 95.91%    32.34GB 50.08%  ElasticComputeEngine/Interfaces.(*implementation).Release
         0     0% 95.91%    32.20GB 49.86%  ElasticComputeEngine/ComputeTaskHandler/Operations.(*Op_DiscreteRatio).Receive.func2
         0     0% 95.91%    32.20GB 49.86%  ElasticComputeEngine/Interfaces.(*implementation).Acquire
    2.60GB  4.02% 99.94%     2.60GB  4.02%  time.startTimer

**Comment by templarzq** [comment]
when i comment the time.after code , there is no memory leak.

**Comment by templarzq** [comment]
> 
> 
> Note that it's normal for `time.After` to use memory until the deadline expires, even if your program winds up choosing a different case in the select.,

thanks. I set the timeout to a large number,so the used memories have not been released. maybe the memory model here should be changed?

**Comment by mvdan** [comment]
If you want to clean up the timer once you're done with it, you should not be using `time.After`. See the docs at https://golang.org/pkg/time/#After.
