### ISSUE TITLE
x/tools/gopls: handle completion after defer and go statements

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29313]
A `defer` or `go` statement is expected to be followed by an `*ast.CallExpr`. If they are not, the parser treats them as `*ast.BadExpr`s, causing completion to fail. We need to handle this particular case.

Repro:
```go
package main

import "fmt"

func main() {
    defer fmt.<>
}
```
Triggering a completion here will result in lexical completions, rather than the expected selector completions for package "fmt".

**Comment by alindeman** [comment]
I decided to poke at this a bit, but couldn't reproduce it. Is this a short code snippet you have handy that triggers the issue?

**Comment by stamblerre** [comment]
Updated to add a repro. This may be a tough first issue, if this is something you're interested in tackling, just because it will require special handling after a file has been parsed but before it has been type-checked.

**Comment by alindeman** [comment]
@stamblerre Thanks. I'm mostly using anything tagged as lsp as a way to get familiar with the current codebase. I don't want to get in the way yet :) I'll follow along on the CL if you get to it first.

**Comment by myitcv** [comment]
I might have misunderstood https://go-review.googlesource.com/c/tools/+/172974/, but I still don't see completions working for the original example provided in https://github.com/golang/go/issues/29313#issue-391917907

**Comment by stamblerre** [comment]
I'm still working on finishing this because it doesn't work on most cases, but it should work OK for the cases in these tests: https://github.com/golang/tools/blob/master/internal/lsp/testdata/badstmt/badstmt.go.

**Comment by myitcv** [comment]
@stamblerre - not quite sure whether the following is an instance of the same issue? Happy to raise a separate issue if not:

```go
package main

import "playground.com/p"

func main() {
	switch {
	case nil:
		s := new(p.)
	}
}

-- go.mod --
module playground.com

-- p/p.go --
package p

type S struct {
	Name string
	Age  int
}
```

Attempting completion after `s.` in `main.go` does not return any candidates.

**Comment by stamblerre** [comment]
I'd guess it's actually closer to https://github.com/golang/go/issues/31973, but either way, that should definitely work.

**Comment by taigacute** [comment]
@stamblerre  hi , i got same error without `go defer` statements.
![1](https://user-images.githubusercontent.com/41671631/61590672-60bc5700-abef-11e9-8f66-61364e2daac5.png)

**Comment by stamblerre** [comment]
@taigacute: I'm not sure I understand the issue here. Do you mind filing a separate issue with logs?

**Comment by taigacute** [comment]
@stamblerre  same sa #33075

**Comment by stamblerre** [comment]
/cc @flowchartsman

This issue has been partially solved, but still needs a bit of work. I believe @flowchartsman will be investigating this.

**Comment by stamblerre** [comment]
This issue should be fixed now. Thanks @muirrn!

**Comment by gencer** [comment]
@stamblerre, should I do;

```
go get golang.org/x/tools/gopls@master
```
**or**
```
go get golang.org/x/tools/gopls@latest
```

**Comment by stamblerre** [comment]
We haven't made a new release yet, so for now, the fix is only on master.

**Comment by gencer** [comment]
Thanks for the fix. I'll use `master` branch for now.

**Comment by blixenkrone** [comment]
Thank you for the fix @stamblerre! Works perfectly.
