### ISSUE TITLE
doc: document the windows/arm progress in the Go 1.12 release notes

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#29314]
There is a `<!-- TODO -->` placeholder for the windows/arm port status in `doc/go1.12.html`. Please replace it with a brief update, see the previous release notes for tone.

**Comment by FiloSottile** [comment]
Replaced with

> Go's new `windows/arm` port supports running Go on Windows 10 IoT Core on 32-bit ARM chips such as the Raspberry Pi 3.

on @bradfitz suggestion in golang.org/cl/154637.

**Comment by alexbrainman** [comment]
> Replaced with
> 
> > Go's new `windows/arm` port supports running Go on Windows 10 IoT Core on 32-bit ARM chips such as the Raspberry Pi 3.
> 
> on @bradfitz's suggestion in golang.org/cl/154637.

Text LGTM, @FiloSottile. Thank you very much.

Alex
