### ISSUE TITLE
math/cmplx: hyperbolic sinh, cosh and tanh give wrong result for Inf input

### ISSUE THREAD

**Issue by kortschak** [golang/go#29320]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What did you do?

Run the code at https://play.golang.org/p/8dz30xSTLdI.

Notice that [sinh(inf)](https://www.wolframalpha.com/input/?i=sinh(inf*(1%2B1i))) and [cosh(inf)](https://www.wolframalpha.com/input/?i=cosh(inf*(1%2B1i))) are inf, and [tanh(inf)](https://www.wolframalpha.com/input/?i=tanh(inf*(1%2B1i))) is 1.

### What did you expect to see?
```
sinh((+Inf+Infi)) -> (+Inf+Infi)
cosh((+Inf+Infi)) -> (+Inf+Infi)
tanh((+Inf+Infi)) -> (1+0i)
```

### What did you see instead?
```
sinh((+Inf+Infi)) -> (NaN+NaNi)
cosh((+Inf+Infi)) -> (NaN+NaNi)
tanh((+Inf+Infi)) -> (NaN+NaNi)
```

**Comment by kortschak** [comment]
Yes, those seem most reasonable. Note that `cmplx.IsInf(±∞ + iNaN)` is `true`.

**Comment by kortschak** [comment]
See also [`cmplx.Sqrt`](https://play.golang.org/p/CYJ__xVFx_0) which gives `sqrt((+Inf+Infi)) -> (+Inf+NaNi)`. The C99 standard says, "csqrt(x+i∞) returns +∞+i∞, for all x (including NaN)."

So, yes. Others are not consistent with C99 either.

**Comment by kortschak** [comment]
Also `cmplx.Pow` behaves differently to `math.Pow` when raising NaN**0.

https://play.golang.org/p/b5zuzP7j7nk

**Comment by bradfitz** [comment]
As @ianlancetaylor wrote on the revert:

> Reason for revert: The new tests fail at least on s390x and MIPS. This is likely a minor bug in the compiler or runtime. But this point in the release cycle is not the time to debug these details, which are unlikely to be new. Let's try again for 1.15.
