### ISSUE TITLE
runtime/race: FATAL: ThreadSanitizer CHECK failed: ./gotsan.cc on go1.12beta1/tip

### ISSUE THREAD

**Issue by paulmach** [golang/go#29329]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I have reproduced on "tip" on travis-ci ([1](https://travis-ci.org/paulmach/orb/jobs/463572737), [2](https://travis-ci.org/paulmach/orb/jobs/466730340), [3](https://travis-ci.org/paulmach/orb/jobs/469746041)) and locally (osx) using go1.12beta1 installed via [gvm](https://github.com/moovweb/gvm)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pamach/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pamach/.gvm/pkgsets/go1.12beta1/global"
GOPROXY=""
GORACE=""
GOROOT="/Users/pamach/.gvm/gos/go1.12beta1"
GOTMPDIR=""
GOTOOLDIR="/Users/pamach/.gvm/gos/go1.12beta1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jb/mt5nv3rd4p78_3k9gr__gkym0000gp/T/go-build498123624=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. installed gvm to get a post g1.11 build.
2. `gvm install go1.12beta1`
3. `gvm use go1.12beta1`
4. `go get github.com/paulmach/orb`
5. `cd $GOPATH/src/github.com/paulmach/orb/simplify`
6. `go test -race -v .`

### What did you expect to see?

```
PASS
ok  	github.com/paulmach/orb/simplify	0.430s
```

### What did you see instead?
```
=== RUN   TestDouglasPeucker_BenchmarkData
--- PASS: TestDouglasPeucker_BenchmarkData (0.73s)
FATAL: ThreadSanitizer CHECK failed: ./gotsan.cc:6826 "((kBlockMagic)) == ((((u64*)addr)[0]))" (0x6a6cb03abcebc041, 0x109907e)
FAIL	github.com/paulmach/orb/simplify	0.752s
```

**Comment by ianlancetaylor** [comment]
CC @dvyukov

**Comment by ianlancetaylor** [comment]
This appears to be due to an assertion failure in `InternalFree` in compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc.

```C++
  CHECK_EQ(kBlockMagic, ((u64*)addr)[0]);
```

That suggests that memory corruption is occurring somewhere.

**Comment by ianlancetaylor** [comment]
Actually this appears to be a compiler error.  It is compiling a method such that it calls `racefuncexit` but not `racefuncenter`.

**Comment by ianlancetaylor** [comment]
CC @randall77 

Here is a standalone reproducer.  It doesn't crash in the same way, but it does crash with tip.  With 1.11 it succeeds.  The bug is that `main.(*DouglasPeuckerSimplifier).LineString` calls `runtime.racefuncexit` but never calls `runtime.racefuncenter`.  That method inlines a couple of functions, so this may be a bug in mid-stack inlining.

```Go
package main

import (
	"fmt"
)


type LineString []Point
type Point [2]float64

//go:noinline
func benchmarkData() LineString {
	return LineString{{1.0, 2.0}}
}

func (ls LineString) Clone() LineString {
	ps := MultiPoint(ls)
	return LineString(ps.Clone())
}

type MultiPoint []Point

func (mp MultiPoint) Clone() MultiPoint {
	if mp == nil {
		return nil
	}

	points := make([]Point, len(mp))
	copy(points, mp)

	return MultiPoint(points)
}

func F1() {
	cases := []struct {
		threshold float64
		length    int
	}{
		{0.1, 1118},
		{0.5, 257},
		{1.0, 144},
		{1.5, 95},
		{2.0, 71},
		{3.0, 46},
		{4.0, 39},
		{5.0, 33},
	}

	ls := benchmarkData()

	for k := 0; k < 100; k++ {
		for i, tc := range cases {
			r := DouglasPeucker(tc.threshold).LineString(ls.Clone())
			if len(r) == tc.length {
				fmt.Printf("%d: unexpected\n", i)
			}
		}
	}
}

// A DouglasPeuckerSimplifier wraps the DouglasPeucker function.
type DouglasPeuckerSimplifier struct {
	Threshold float64
}

// DouglasPeucker creates a new DouglasPeuckerSimplifier.
func DouglasPeucker(threshold float64) *DouglasPeuckerSimplifier {
	return &DouglasPeuckerSimplifier{
		Threshold: threshold,
	}
}

func (s *DouglasPeuckerSimplifier) LineString(ls LineString) LineString {
	return lineString(s, ls)
}

type simplifier interface {
	simplify(LineString, bool) (LineString, []int)
}

func lineString(s simplifier, ls LineString) LineString {
	return runSimplify(s, ls)
}

func runSimplify(s simplifier, ls LineString) LineString {
	if len(ls) <= 2 {
		return ls
	}
	ls, _ = s.simplify(ls, false)
	return ls
}

func (s *DouglasPeuckerSimplifier) simplify(ls LineString, wim bool) (LineString, []int) {
	return nil, nil
}

func main() {
	F1()
}
```
