### ISSUE TITLE
encoding/json: addErrorContext is not called for errors from UnmarshalJSON

### ISSUE THREAD

**Issue by linniksa** [golang/go#29327]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

run code like this https://play.golang.org/p/NLNoBEmLMwr

### What did you expect to see?

'type'

### What did you see instead?

''

In go 1.10 this code return 'type'

**Comment by bradfitz** [comment]
Seems fixed at tip (in Go 1.12).

```
bradfitz@gdev:~$ GOROOT=$HOME/go1.10 go run x.go
'type'
bradfitz@gdev:~$ GOROOT=$HOME/go1.11 go run x.go
''
bradfitz@gdev:~$ GOROOT=$HOME/go go run x.go
'type'
```

@mvdan, you recall whether this was fixed recently?

Worth a backport to Go 1.11.x?

**Comment by mvdan** [comment]
@bradfitz I'm pretty sure this was https://github.com/golang/go/issues/27464. I suggested a backport there, but forgot to follow up on that. I do think we should backport, as it's a regression in 1.11, even if a small one in an edge case.

**Comment by bradfitz** [comment]
@mvdan, thanks. Want to verify, close this one, and request that gopherbot do the cherry-pick?

**Comment by mvdan** [comment]
Yes, this issue is a duplicate, so we can just backport #27464. Happy to help with the backport itself or its review.

**Comment by mvdan** [comment]
Done the above, so I'm closing this issue as a duplicate.
