### ISSUE TITLE
divide by zero, out put a very big number

### ISSUE THREAD

**Issue by usernameisnull** [golang/go#29330]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.9 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>set GOARCH=amd64
set GOBIN=
set GOEXE=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=D:\代码\golang
set GORACE=
set GOROOT=D:\Go
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-fPIC -m64 -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config</details>

### What did you do?

https://play.golang.org/p/RQcR6hOOyjc

### What did you expect to see?
should panic

### What did you see instead?
with this link, https://play.golang.org/p/RQcR6hOOyjc , I see
322122547237.200012
but on my computer, I see
1383505805528216371200.000000

**Comment by crvv** [comment]
The specification says 
> The result of a floating-point or complex division by zero is not specified beyond the IEEE-754 standard; whether a run-time panic occurs is implementation-specific.

https://golang.org/ref/spec#Arithmetic_operators

What is `3/div` is undefined. It is `+Inf` in this case.

And https://golang.org/ref/spec#Conversions
> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

What is `int(Inf)` is also undefined. It can be different value on different machines.

I don't think this is a bug.

**Comment by randall77** [comment]
I agree, this is expected. I'll close.
If you want to contest what the spec says about such conversions, feel free to reopen.
