### ISSUE TITLE
cmd/vet: internal error: no range for "project"

### ISSUE THREAD

**Issue by bradleyjkemp** [golang/go#29338]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, same error occurs on `go version go1.11.4 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bradleykemp/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bradleykemp/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/r713l1xj6_dcykbx21svs09h0000gp/T/go-build903451123=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Create minimal repro package:
```
vetshadowrepro
├── project
│   └── project.go
└── repro.go
```
repro.go has contents:
```go
package vetshadowrepo

import (
    "vetshadowrepro/project"
)

func Repro() {
    project := &mocks.Project{}
    _ = project
}
```

and project.go has contents:
```go
package mocks

type Project struct{}
```

Running `go tool vet --shadow vetshadowrepro` gives internal error in output:
```
vetshadowrepro/repro.go:8: internal error: no range for "project"
```

### What did you expect to see?
No error because the project variable declaration does not shadow. Seems vet is confused by the import path being different to the package name.

### What did you see instead?
Internal error:
```
vetshadowrepro/repro.go:8: internal error: no range for "project"
```

**Comment by bcmills** [comment]
`go tool vet` will no longer be supported in Go 1.12 (see #28869), and the `-shadow` flag 
was explicitly experimental to begin with:
https://github.com/golang/go/blob/a171e155000d1f40a6e467e56b4af3a237613c1f/src/cmd/vet/shadow.go#L44

The good news is, `go help vet` mentions the `shadow` check explicitly:

> For example, the 'shadow' analyzer can be built and run using these commands:
> ```
> go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
> go vet -vettool=$(which shadow)
> ```

And it seems to work; at the very least it doesn't crash:

```
_gopath/src/vetshadowrepro$ GO111MODULE=off go vet -vettool=$(which shadow) vetshadowrepro/...

_gopath/src/vetshadowrepro$ GO111MODULE=on go vet -vettool=$(which shadow) vetshadowrepro/...
```
