### ISSUE TITLE
cmd/go: improve 'missing $GOPATH' error message when HOME is unset

### ISSUE THREAD

**Issue by bitfield** [golang/go#29341]
With reference to #24064, this is a common occurrence when trying to automate the installation of Go programs with tools such as Puppet. System commands are run in an initially empty environment, so a command like:

```
GO111MODULE=on go get github.com/bitfield/cronrun/cmd/cronrun@v0.3.2
```

fails with this error:

```
missing $GOPATH
```

But this works fine in a 'normal' interactive environment, because GOPATH is inferred from the value of $HOME. What's missing here is not $GOPATH, per se, but $HOME.

Maybe this error message could be improved, along the lines of:

> GOPATH not set; unable to default to '$HOME/go' because HOME is not set either. Please set either GOPATH or HOME.

**Comment by 89z** [comment]
Arg I just hit this. I started a new environment with `os/exec#Cmd.Run` after setting `Cmd.Env`
