### ISSUE TITLE
x/net/http2: missing SETTINGS_HEADER_TABLE_SIZE support

### ISSUE THREAD

**Issue by rs** [golang/go#29356]
There are TODO comments in the code about `SETTINGS_HEADER_TABLE_SIZE ` support. Proper would:
* Give the ability to setup a max table size at http2.Transport and http2.Server
* Send the max table size in the settings frame
* Apply received `SETTINGS_HEADER_TABLE_SIZE` capped by the max table size defined

I have a working implementation. I need to write tests and I will submit it.

Cc @bradfitz

**Comment by rs** [comment]
@katiehockman: all other issues related to `x/net/http2` are prefixed with `x/`. What drove your decision to remove `x/` here?

**Comment by katiehockman** [comment]
Just a mistake. Thanks for letting me know. Updated it.

**Comment by elindsey** [comment]
This patch looked close to landing, but discussion stalled out. I've rebased the patch from CL 155877, addressed the last piece of feedback I saw from Brad (splitting the MaxHeaderTableSize setting into two settings), added an additional test and published as a new CL. 

@neild or @bradfitz if you have time, I'd very much appreciate a review.
