### ISSUE TITLE
cmd/compile: document that TypedArrays are not pinned in memory

### ISSUE THREAD

**Issue by twifkak** [golang/go#29355]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### What version of Node are you using?

<pre>
$ node --version
v10.13.0
</pre>

### Does this issue reproduce with the latest release?
Yes. This occurs at master, as well.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/twifkak/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="//home/twifkak/.go"
GOPROXY=""
GORACE=""
GOROOT="/home/twifkak/usr/opt/go"
GOTMPDIR=""
GOTOOLDIR="/home/twifkak/usr/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build919054145=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Created a js.TypedArray in a Go program running under wasm, and then mutated it in a JS callback.

### What did you expect to see?
The TypedArray would be successfully mutated, which the Go program could subsequently inspect.

### What did you see instead?
In some circumstances, I would get:
```
TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
```
My suspicion is that the GC is moving the underlying byte arrays in times of memory pressure, because the easiest way to trigger this is to decrease the initial heap size, either using [wams](https://github.com/termonio/wams) or by modifying [asm.go](https://go.googlesource.com/go/+/go1.11/src/cmd/link/internal/wasm/asm.go#310).

### Background

I'm doing this to keep a long-running Go-wasm process around and repeatedly call a Go function from JS, without leaking the input/output objects due to lack of cross-heap GC.

The code to reproduce it is at https://github.com/ampproject/amppackager/pull/220 but requires a test file I haven't checked in -- if you're interested in running it, let me know and I'll add one.

Let me know if I'm holding it wrong and there's some simpler way of achieving my goal.

**Comment by twifkak** [comment]
@neelance

**Comment by neelance** [comment]
Hmm, this is unfortunate. Calling `memory.grow` (which may happen at any time) invalidates the existing `ArrayBuffer` for the memory. Since typed arrays are based on this `ArrayBuffer`, they stop working as well.

With the current state of WebAssembly the only solution that I see is to not pass the typed array directly but instead wrap it in a custom helper that can create the correct typed array on demand and the user is not allowed to keep a reference to this typed array. This is quite cumbersome.

The [threads proposal](https://github.com/webassembly/threads/blob/master/proposals/threads/Overview.md) might save us: It used a `SharedArrayBuffer` instead of an `ArrayBuffer` and it seems like [it would never detach](https://github.com/WebAssembly/design/pull/795).

**Comment by twifkak** [comment]
Ah, I was able to get the wrapper approach to work, but boy is it a lot of cruft! Also, will this leak the `TypedArray` pointers over time?

Until the threads proposal lands, would it be possible to create a second, non-growing memory instance to be used as an arena to communicate over?

**Comment by neelance** [comment]
> I was able to get the wrapper approach to work, but boy is it a lot of cruft. Also, will this leak the TypedArray pointers over time?

Depends on your implementation. I'm not sure what you did.

> The threads proposal is indeed interesting. Until the proposal lands, would it be possible to create a second, non-growing memory instance to be used as an arena to communicate over?

I don't see a good way to make this work with Go's memory management.

**Comment by neelance** [comment]
I currently don't see anything worthwhile that we could do prior. You can still use typed arrays right now, you just shouldn't hold a reference to them from JavaScript. For example the way that the `net/http` code is using them is fine.

**Comment by agnivade** [comment]
Does it make sense to add a line of documentation clarifying this ?

**Comment by neelance** [comment]
Sure, why not.
