### ISSUE TITLE
On Docker, golang:latest points to 1.10(.0) and golang:1.11 points to 1.11.1 despite 1.11.4 being out

### ISSUE THREAD

**Issue by HaraldNordgren** [golang/go#29359]
```
 % docker run golang go version
go version go1.10 linux/amd64

 % docker run golang:latest go version
go version go1.10 linux/amd64

 % docker run golang:1.11 go version
go version go1.11.1 linux/amd64
```

**Comment by tklauser** [comment]
The golang Docker images are not provided by the Go project. I think this issue should instead be reported against https://github.com/docker-library/official-images or https://github.com/docker-library/golang which seem to be the source of these images.

**Comment by mvdan** [comment]
What @tklauser said - this seems to be the wrong issue tracker to report the issue to.
