### ISSUE TITLE
time: improve Documentation for Parse for zone offsets

### ISSUE THREAD

**Issue by abraithwaite** [golang/go#29351]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.  Checked master and docs have not changed in tip either.

### What did you do?

https://play.golang.org/p/bvmvzOstarf

Edit: the zone in this should be PST, but the result is the same ^

### What did you expect to see?

I expected to see the timezone offset to be set accordingly.

### What did you see instead?

The timezone numeric offset was not set, despite `Zone()` returning a text zone.

### Proposal

For those unfamiliar with timezones, we are unaware that timezone abbreviations are ambiguous.  The docs make it clear that in order for those textual time zones to be parsed and set an offset, it must be parsed in the context of a location.  However, it's not immediately clear that you _will_ have a problem trying to parse dates with a timezone abbreviation.

I propose adding a simple line: "Timezone abbreviations like "MST" are ambiguous, therefore..." to the docs.

https://github.com/golang/go/blob/84066f1b0b68761a75ce9064f4c412f751ee2168/src/time/format.go#L764-L772

We discovered this during a migration from Javascript, which does set a numeric offset even in the absence of a predefined location (servers location is UTC, but still parses PDT as -07:00)

**Comment by seankhliao** [comment]
looks like this was added.
