### ISSUE TITLE
Reusable tests?

### ISSUE THREAD

**Issue by fduxiao** [golang/go#29365]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xiao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xiao/Work/taskalive"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1p/m4n63lvx1rb45400kq8cq7sr0000gn/T/go-build324983922=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

I'm trying to write several tests about my code, in which I need to initialize the database for each test.
However, in the tests of my sub packages I need the same initialization. 
As suggested in [stackoverflow](https://stackoverflow.com/questions/38712120/golang-how-to-reuse-test-code-in-imported-package), I've tried to move the process to a utils package, but there're still problems. 

I have to import this package from the top package when testing the top package, but there are several utils imported from the top package into the this package. How should I escape from this cycling hell? 
I also try to put the tests for the top package in another package, but I cannot get the coverage report. 

The only way that works is to put these testing utils in the top package, but I cannot have them all covered. Actually that's unnecessary since I never care about what if the database fails to initialize before the test(I handle the failure in my application, not in the setup for the test), but I need to panic the error as some developers may have a wrong config, (which is exactly the uncovered part). 
I know they could be covered, but I don't want to test my tests and I have no way to ignore those lines.

What should I do to reuse tests and gracefully test my code with a precise coverage report?

**Comment by ianlancetaylor** [comment]
You will get much better answers for questions like this if you use a forum.  See https://golang.org/wiki/Questions .

I'm going to close this issue since there is nothing for us to fix, and since I don't have any specific answers for you.
