### ISSUE TITLE
net/rpc: API Call() is not working as expected

### ISSUE THREAD

**Issue by SagarPuneria** [golang/go#29360]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/386
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10, 64 bit

### What did you do?

I am using [client.Call(serviceMethod string, args interface{}, reply interface{})](https://golang.org/pkg/net/rpc/#Client.Call) in my code for implementing HTTP RPC client program, where i have passed reference address of variable in both second parameter args(interface type) and third parameter reply(interface type). So that changes made to the receiver's methods in the DefaultServer get reflected outside the client.Call() method.
[HTTP RPC client example](https://play.golang.org/p/5I-_KYswkGw)
>**Output:**
> arg:"go version is go1.11.3 is not latest"
> reply:"go version is go1.11.4 is latest"

[HTTP RPC server example](https://play.golang.org/p/PrjMSbyDGhT)
>**Output:**
> Inside StringModify

### What did you expect to see?

I expected to see the same string values to args and reply(both are interface type) after successfully calling client.Call(). Since i assigned same value at line number 20 as shown in [HTTP RPC server example](https://play.golang.org/p/PrjMSbyDGhT)

### What did you see instead?
After calling client.Call() args and reply string values are different. I see only reply get modified but not args.

**Comment by SagarPuneria** [comment]
CC @bradfitz

**Comment by as** [comment]
I don't think this is an implementation bug, the documentation says the method should be of the form:

```
func (t *T) MethodName(argType T1, replyType *T2) error
```

I interpret that as `T1` being immutable through the RPC. I would be surprised if `T1` was mutated even when it is a pointer. The `Arith` example uses both arguments as pointer types, perhaps this _suggests_ mutability.

```
	type Arith int

	func (t *Arith) Multiply(args *Args, reply *int) error {
		*reply = args.A * args.B
		return nil
	}

	func (t *Arith) Divide(args *Args, quo *Quotient) error {
		if args.B == 0 {
			return errors.New("divide by zero")
		}
		quo.Quo = args.A / args.B
		quo.Rem = args.A % args.B
		return nil
	}
```

Nowhere in the example is `args` actually modified though. It might be less confusing to make the example have a value type for `args` to make things unambiguous.

**Comment by SagarPuneria** [comment]
@as, thanks for investigating.
