### ISSUE TITLE
x/sys: unix/linux/mksysnum.go is executable as of 2018-12-20

### ISSUE THREAD

**Issue by anthonyfok** [golang/go#29369]
In the recent commit golang/sys@a5c9d58dba9a56f97aaa86f55e638b718c5a6c42 "unix/linux: replace "mksysnum.pl" script with a Go program", it seems that mksysnum.go was inadvertently created with mode 100755 (executable) rather than the normal 100644 mode.

This raised a Lintian `executable-not-elf-or-script` warning while we were updating the x/sys package for Debian:

    W: golang-golang-x-sys-dev: executable-not-elf-or-script usr/share/gocode/src/golang.org/x/sys/unix/linux/mksysnum.go

This is a very minor issue, but I thought you might like to know.

Cheers,
Anthony

**Comment by ALTree** [comment]
Thanks for the report. I sent a change to set mksysnum.go mode to 644.

**Comment by tklauser** [comment]
Thanks for the report and the fix. I missed that during the review of https://golang.org/cl/151377
