### ISSUE TITLE
runtime: TestLockOSThreadExit failing on arm64 builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#29366]
The `TestLockOSThreadExit` is currently failing on the `linux/arm64` builder:

```
--- FAIL: TestLockOSThreadExit (0.03s)
    crash_test.go:95: testprog LockOSThreadAvoidsStatePropagation exit status: exit status 1
    proc_test.go:892: want OK
        , got failed to unshare fs: operation not permitted
        
FAIL
FAIL	runtime	40.468s
```

https://build.golang.org/log/ba97c98ea93fe2e4b4619e38fda345eb43216f97

The failures started at d0f8a7517ab0b33c8e3dd49294800dd6144e4cee (runtime: don't clear lockedExt on locked M when G exits), which slightly changed the test.

cc @mknyszek

**Comment by mknyszek** [comment]
It looks like on linux/arm64 for whatever reason unshare(CLONE_FS) is either unsupported, or just not allowed to be executed by the user running the tests.

If I were to take a wild guess, it might have to do with the way the arm64 builders are containerized. If there's a security issue with enabling unshare, then I'm happy to just disable the test on arm64. It's an easy fix.

cc @bradfitz

**Comment by cherrymui** [comment]
I think it would be good that we skip the test on platforms that doesn't support, maybe by testing kernel configurations or trying a syscall. So users won't see this kind of failures if they have such configurations.

For the concern of actually testing the functionality, I guess we could require the tests *not* to be skipped on certain builders? I.e., something like

```
if unsupported {
  if onCertainBuilder {
    t.Fatalf(...) // the syscall should be supported on this builder
  } else {
    t.Skip(...)
  }
}
```
