### ISSUE TITLE
cmd/go: "unknown revision" error followed by "error loading module requirements"

### ISSUE THREAD

**Issue by liu-xuewen** [golang/go#29374]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
![image](https://user-images.githubusercontent.com/29445066/50326910-b16bb480-0527-11e9-8373-2aac87ef34dc.png)

### What did you expect to see?

resolve this bug? auto skip the missing version of module requirements

**Comment by liu-xuewen** [comment]
![image](https://user-images.githubusercontent.com/29445066/50327168-de6c9700-0528-11e9-81aa-6fb199e5291d.png)
![image](https://user-images.githubusercontent.com/29445066/50327205-05c36400-0529-11e9-9e74-0331427eb429.png)

**Comment by agnivade** [comment]
Hi @liu-xuewen - please kindly fill the complete issue template. We need instructions on how to reproduce this issue. The screenshots have been redacted so we don't know what is going on.

> auto skip the missing version of module requirements

Why do you expect this to be the behavior ? `go build` is supposed to build exactly what is specified in `go.mod`. If there is a mismatch, it should throw an error like shown above.

**Comment by thepudds** [comment]
Hi @liu-xuewen, in addition to the information that @agnivade asked for, some other quick questions:

1. What version of git are you using? Old versions of git can trigger an error like you are seeing.

2. Does a basic example work for you like: https://github.com/golang/go/wiki/Modules#quick-start

3. For diagnostic purposes, you might also want to try with Go 1.12 beta, which in many cases will print better diagnostic error messages. 

     The easiest way to try go1.12beta1 is by using the go command: 
```
$ go get golang.org/dl/go1.12beta1 
$ go1.12beta1 download 
```

**Comment by templarzq** [comment]
same issue....

**Comment by thepudds** [comment]
@templarzq

What version of git are you using? Old versions of git can trigger an error like the one initially reported here. 

Does a basic example work for you like: https://github.com/golang/go/wiki/Modules#quick-start

In any event, this issue has been closed for several months. 

 If you are seeing a problem, probably best to open a new issue.

**Comment by joshmsamuels** [comment]
@thepudds 

I just downloaded git 2.22.0

The basic example worked but my project is giving me the same error. Do you have any other debugging steps
