### ISSUE TITLE
x/tools/internal/lsp: do not complete inside of comments

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29370]
The "." character triggers completion in the LSP, but we should avoid returning completion results when the "." is within a comment.

**Comment by anjmao** [comment]
@stamblerre Hi, as this sounds like lower level priority, could I try to solve this issue? I imagine it could be fixed by checking if . was placed at *ast.Comment node.

**Comment by anjmao** [comment]
@stamblerre Hi, I just made a new PR which fixes all other cases. You could probably reopen this issue so gopherbot can sync it to gerrit.
