### ISSUE TITLE
x/website/internal/dl: expand JSON download mode to optionally return archive and unstable releases also

### ISSUE THREAD

**Issue by johnweldon** [golang/go#29380]
# Issue

The PR that resolved #23746 provided a nice JSON response on the download page https://golang.org/dl/?mode=json

However, this only provides for stable releases.

I would like to consume unstable and archive release metadata as JSON also.

# Proposal

I'd like to modify https://github.com/golang/tools/blob/4d6773f/godoc/dl/server.go#L80-L88 to add a query param to include archive or unstable releases optionally.

I'm thinking `https://golang.org/dl/?mode=json[&include=(all|stable|unstable|archive)]`

When the `include` param is absent, it would default to `stable` which is the current behaviour already.

**Comment by andybons** [comment]
Why not just `all` and `stable` as options? Is there a specific need for the level of granularity you specify?

**Comment by johnweldon** [comment]
All I personally need is `all`.

**Comment by andybons** [comment]
I’m down for an `all` option. We can expand if needed.

**Comment by johnweldon** [comment]
Updated CL: https://go-review.googlesource.com/c/website/+/163741
