### ISSUE TITLE
cmd/go: TestScript/build_runtime_gcflags failing on longtest builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#29395]
The `TestScript` harness is currently broken, causing a failure in the `cmd/go` test suite on the longtest builder. A log:

https://build.golang.org/log/13f2837122b3a012cc7d46fe08e0214ca5ee61fb

The failures started at 00055152d320f60476ca5db1e7da4fc89f94834e (cmd/go: fix -n output in runtime/internal/atomic).

cc @jayconrod

**Comment by mvdan** [comment]
That's when the test script was added. Weirdly enough, the test script passes on my machine.

Also, I think the comment on the test script is wrong. It says "See golang.org/issue/26092.", but that issue seems completely unrelated to the build flags bug.

**Comment by jayconrod** [comment]
This was a misconception on my part. I assumed the tests were using separate caches. This issue could be reproduced by running `go build -gcflags=all=-l std` before running the test.

The test will now creates its own cache directory.

(Also, fixed the issue URL. Thanks for pointing that out.)
