### ISSUE TITLE
Design confusion about interface assignment

### ISSUE THREAD

**Issue by tianxintse** [golang/go#29391]
I think the code bellow should case a compilation error. Because type `*A` didn't implement interface `jump`. Why does Go allow this assignment expression?  Why do we need it? It makes people confused!!! 

By the way, auto referencing and dereferencing are also a bad design. Code should be very clear about our intention!!!

```go
package main

import (
	"fmt"
)

type jump interface {
	modify()
	myPrint()
}

type A struct {
	data int
}

func (m A) myPrint() {
	fmt.Println("data:", m.data)
}

func (m A) modify() {
	m.data += 1
}

func main() {
	var a = A{data: 1}
	var b jump
	b = &a // I think this should case a compilation error
	b.modify()
	b.myPrint()
}
```

**Comment by go101** [comment]
`*A` exactly implements `jump`. The method set of `*A` is always a super set of `A`.
Please read https://go101.org/article/method.html and https://go101.org/article/interface.html for details.

**Comment by agnivade** [comment]
This is WAI as explained above.

For further questions, please take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page. Thanks.
