### ISSUE TITLE
go run inside module includes go files excluded with tags

### ISSUE THREAD

**Issue by leighmcculloch** [golang/go#29405]
### What version of Go are you using (`go version`)?

<pre>go version go1.11.4 linux/amd64</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/home/leighmcculloch/local/bin"
GOCACHE="/home/leighmcculloch/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leighmcculloch/go"
GOPROXY=""
GORACE=""
GOROOT="/home/leighmcculloch/local/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/leighmcculloch/local/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/leighmcculloch/devel/looks.wtf/service/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build662240678=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran `go run .` inside a modules directory, where the module contains two main functions, one which is inside a file that is restricted with a build tag.

Example repository: https://github.com/leighmcculloch/go-issue-29405

### What did you expect to see?

I expected `go run .` to respect the build tags that are set or not set, and to only see a single Go file containing a main function.

### What did you see instead?

When I ran `go run .` it included the Go file containing the second main function, and printed out this error:

```
$ go run .
# test
./script.go:6:6: main redeclared in this block
        previous declaration at ./main.go:5:6
```

**Comment by mvdan** [comment]
Perhaps I'm missing something, but it looks to me like you're just missing a newline. This also explains why `go build` also complains.

```
$ go build
# test
./script.go:6:6: main redeclared in this block
        previous declaration at ./main.go:5:6
$ [edit script.go]
$ git diff
diff --git a/go.mod b/go.mod
index 060e28b..e27256d 100644
--- a/go.mod
+++ b/go.mod
@@ -1 +1,3 @@
 module test
+
+go 1.12
diff --git a/script.go b/script.go
index 973e057..b4bccaa 100644
--- a/script.go
+++ b/script.go
@@ -1,4 +1,5 @@
 // +build script
+
 package main

 import "fmt"
$ go build
$ echo $?
0
```

I ran this on `go version devel +97d5cb24b1 Sat Dec 22 09:37:04 2018 +0000 linux/amd64`, so ignore the `go 1.12` change.

**Comment by leighmcculloch** [comment]
Oh no, not this mistake again. 🤦‍♂️
