### ISSUE TITLE
misc/wasm: unable to pass extra flags like "--no-sandbox" while executing in Electron

### ISSUE THREAD

**Issue by gtd138** [golang/go#29404]
go version 1.11.4
electron is a mudule in node.js. when run wasm_exe in electron，catch error：

```
 Uncaught Error: ENOENT: no such file or directory, open '--no-sandbox'
    at Object.fs.openSync (fs.js:577)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563)
    at wasm_exec.js:424
    at wasm_exec.js:438
```

the code which in wasm_exe.js

```js
 WebAssembly.instantiate(fs.readFileSync(process.argv[2]), go.importObject).then((result) => {
            process.on("exit", (code) => { // Node.js exits if no callback is pending
                if (code === 0 && !go.exited) {
                    // deadlock, make Go print error and stack traces
                    go._callbackShutdown = true;
                    go._inst.exports.run();
                }
            });
            return go.run(result.instance);
        }).catch((err) => {
            throw err;
        });
```

process.argv[2] == "--no-sandbox" not a file!
I have to fix it like this:
        if (process.argv[2] == "--no-sandbox") {
            return;
        }

I don't think it is a good idea. would you please fix it?
[GoWebassembly.zip](https://github.com/golang/go/files/2706495/GoWebassembly.zip)

**Comment by agnivade** [comment]
The nodeJS part of wasm_exec.js is just a simple wrapper to call the wasm binary. Even the usage is `usage: go_js_wasm_exec [wasm binary] [arguments]`. I wonder whether it will be helpful to add complex flag parsing logic into it.

/cc @neelance

**Comment by neelance** [comment]
I don't understand this issue. Why are you passing `--no-sandbox` to `wasm_exec.js`? Is it that you're using `require` with `wasm_exec.js`?

**Comment by gtd138** [comment]
I want to use wasm in electron which integrates the node.js environment. it's catch error when loading *.wasm file.  I'm using  wasm_exec.js to start wasm, but the process.arg[2] would be a flag named "--no-sandbox",  not a file name. so，the follow code catch error:
WebAssembly.instantiate(fs.readFileSync(process.argv[2]) ...

**Comment by neelance** [comment]
You still haven't told me how exactly you're loading `wasm_exec.js`.

**Comment by gtd138** [comment]
loading wasm_exec.js in index.html like this:
<html>

<head>
    <meta http-equiv="Cache-Control" CONTENT="no-cache">
    <meta http-equiv="Pragma" CONTENT="no-cache">
    <meta http-equiv='Cache-Control' content='no-siteapp' />
    <title>go wasm</title>
    <script src="wasm_exec.js"></script>
    <script src="index.js"></script>
</head>

<body>
    <button id="btn">Button</button>
</body>

</html>

and in index.js:

const go = new Go();
let mod, inst;

WebAssembly.instantiateStreaming(
    fetch("main.wasm"), go.importObject
).then(
    (result) => {
        mod = result.module;
        inst = result.instance;
        console.log("init done");
        run();
    }
).catch((err) => {
    console.error(err);
})

async function run() {
    await go.run(inst);
    inst = await WebAssembly.instantiate(mod, go.importObject);
}

**Comment by gtd138** [comment]
the error does not catch using the new wasm_exec.js. But new problems arise.:
index.js:14 LinkError: WebAssembly Instantiation: Import #5 module="go" function="runtime.scheduleCallback" error: function import requires a callable

WebAssembly.instantiateStreaming.then.catch | @ | index.js:14

Do I need a new version compiler?

**Comment by agnivade** [comment]
By "new", if you mean the wasm_exec.js found in the master branch, then you need to use the Go binary compiled using the master branch. Could you try that ? 

You can download and build the Go master branch using [gotip](https://godoc.org/golang.org/dl/gotip).

**Comment by gtd138** [comment]
thanks, I would try it out.

**Comment by gtd138** [comment]
The master tree don't catch the error without changing isNodeJS to  isNodeJS && require.main === module! The error may be only in version 11.1.4.

**Comment by agnivade** [comment]
Did you mean "_with_ changing ..." ?

**Comment by gtd138** [comment]
I mean without changing.I compare the master tree with 1.11.4, there are some differents between them. And the master tree did not catche error any more.

**Comment by agnivade** [comment]
Ah I see. So the master branch does not catch the error by default. Interesting. @neelance - thoughts ?

**Comment by neelance** [comment]
With 1.11 it was
```
const isNodeJS = typeof process !== "undefined";
```
now it is
```
const isNodeJS = global.process && global.process.title === "node";
```
That's probably enough for your case to have `isNodeJS` set to `false`. However, this would also mean that the `os` package won't work.

**Comment by gtd138** [comment]
os package really doesn't work. global.process.title === "". It means I have to import it manually？

**Comment by neelance** [comment]
Yes, in your case the check `global.process.title === "node"` isn't appropriate. We can try to change it to something that works in your case while still trying to not regress on #28364.

**Comment by neelance** [comment]
@gtd138 Could you please give this branch a try? https://github.com/neelance/go/blob/wasm-exec/misc/wasm/wasm_exec.js
I tried to make it adapt to different environments.
@SamWhited Could you do us a favor and try it with your Parcel use case as well?

**Comment by SamWhited** [comment]
> @SamWhited Could you do us a favor and try it with your Parcel use case as well?

I changed how the bundling works and don't have the same problem anymore; it's been a while, so I'm afraid I don't remember what the other problem was or how to reproduce it.

**Comment by gtd138** [comment]
@neelance 
os pack works, but it catches error again:
```
Uncaught Error: ENOENT: no such file or directory, open '--no-sandbox'
    at Object.openSync (fs.js:436)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Object.readFileSync (fs.js:341)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:580)
    at wasm_exec.js:474
    at wasm_exec.js:487
```

**Comment by neelance** [comment]
So this means that `global.require.main === module` is `true` in your case, even if you include it via `<script src="wasm_exec.js"></script>`? Could you please double check? If yes, then we need to find a different way to detect that the script is not called as a standalone executable.

**Comment by gtd138** [comment]
Yes,` global.require.main === module` is true, and I still include it via` <script src="wasm_exec.js"></script>`

**Comment by neelance** [comment]
This is unexpected, but it is JavaScript after all... So maybe we should keep the `global.process.title === "node"`? Do you see a better way to detect Electron?

**Comment by gtd138** [comment]
I found it from Electron's official website. It is  `process.versions['electron'] != "undefined"` or `process.versions.hasOwnProperty('electron') == true`,  if current env is electron.

**Comment by neelance** [comment]
I have updated the branch https://github.com/neelance/go/blob/wasm-exec/misc/wasm/wasm_exec.js. Does this work for you?

**Comment by gtd138** [comment]
It works! The os package works, too. Thanks.

**Comment by neelance** [comment]
Great. I'll create a CL in the next cycle.

**Comment by gtd138** [comment]
Ok. Does it mean it will be supported in 1.12?

**Comment by agnivade** [comment]
No, the next cycle is 1.13. 1.12 is feature frozen.

**Comment by gtd138** [comment]
Ah,I see.
