### ISSUE TITLE
Unmarshal json from json file

### ISSUE THREAD

**Issue by msalcantara** [golang/go#29411]
Is there a way to make unmarshal directly from json file using ecoding/json?
For example:
```
b, err := json.UnmarshalFromFIle("myfile.json")
if err != nil {
    panic(err)
}
fmt.Println(string(b))
```
If not, maybe can be useful to implement some function to do this.

**Comment by mvdan** [comment]
You can do this trivially with `os.Open` along with `json.Decoder`, or `ioutil.ReadFile` and `json.Unmarshal`. I'm sure you can find hundreds of blog posts and articles online that go into more detail.
