### ISSUE TITLE
encoding/gob: mention that Encoder and Decoder are safe for concurrent use

### ISSUE THREAD

**Issue by mostynb** [golang/go#29416]
gob.Encoder and gob.Decoder use mutexes internally to allow concurrent usage, but I couldn't see this mentioned in the package documentation anywhere.  It might be useful to do so.

**Comment by mvdan** [comment]
I always forget if we need to document when named types and methods are safe for concurrent use, or when they're not. We should probably have a wiki page explaining this.

**Comment by mostynb** [comment]
I forget too, and so I default to treating things as unsafe for concurrent use until told otherwise- which seems like the most reasonable response.

If there's general agreement on if/what/how this should be documented, I would be happy to help make this more consistent across the standard library docs.
