### ISSUE TITLE
CGO multiple definition of 'functionNames'

### ISSUE THREAD

**Issue by zhouxunAtSC** [golang/go#29412]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, I change my go version to go1.11.4 linux/amd64, and it still has this problem.

### What operating system and processor architecture are you using (`go env`)?
os: deepin15.8(like Ubuntu)
<details><summary><code>go env</code> Output</summary><br><pre>
x@x:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/x/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build053929605=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I wrote a project 'A' some algorithm depend on <a href="https://github.com/ethereum/go-ethereum">ethereum</a>, and it is cgo. I encapsulate some function using <a href="https://github.com/ethereum/go-ethereum">ethereum's</a> function, and it works, pretty cool.
But when I wrote an another project B, which depend on both <a href="https://github.com/ethereum/go-ethereum">ethereum's</a> and 'A', and it does't work.
I don't know if this will a problem: I use govendor manage my dependences, and I copyed C libs to vendor folder. Project 'A' does not works if I do not copy c libs.

### What did you expect to see?
I add #ifndef and #define in C header files, I expect it compile success and project B runs well.

### What did you see instead?
Compile failed.
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-392511721/000021.o: In function `secp256k1GoPanicIllegal':
/tmp/go-build/_cgo_export.c:22: multiple definition of `secp256k1GoPanicIllegal'
/tmp/go-link-392511721/000017.o:/tmp/go-build/_cgo_export.c:22: first defined here
/tmp/go-link-392511721/000021.o: In function `secp256k1GoPanicError':
/tmp/go-build/_cgo_export.c:39: multiple definition of `secp256k1GoPanicError'
/tmp/go-link-392511721/000017.o:/tmp/go-build/_cgo_export.c:39: first defined here
/tmp/go-link-392511721/000024.o: In function `secp256k1_context_create':
/opt/go/src/github.com/EducationEKT/EKT/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/./libsecp256k1/src/secp256k1.c:58: multiple definition of `secp256k1_context_create'
/tmp/go-link-392511721/000020.o:/opt/go/src/github.com/EducationEKT/ekt-auto-ex/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/./libsecp256k1/src/secp256k1.c:59: first defined here
```

**Comment by ianlancetaylor** [comment]
C does not have a separate namespace per Go package.  In C, all globally visible symbols are visible across the entire program.  You can't copy C code with globally visible symbols from one package to another and then link the two packages together into a single program.  You will have to rename the symbols in one of the copies, or make them static rather than global, or arrange for one copy to refer to the other copy somehow.

Closing because there is nothing we can do to fix this in Go.  For more advice on how to deal with the situation, I recommend that you use a forum; see https://golang.org/wiki/Questions .
