### ISSUE TITLE
cmd/compile: infinite loop in cmd/compile/internal/gc.compileFunctions (darwin/amd64)

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#29418]
From the Android builder. I had to kill the compile process with SIGQUIT:

https://farmer.golang.org/temporarylogs?name=android-arm64-wiko-fever&rev=b32ee0a3c004d4ef79d92bd63200008456da50f3&st=0xc447882b00

Note that the hung process was before running tests, running on the host (darwin/amd64 mac mini).

The infinite loop reminds me of a similar case reported in https://github.com/golang/go/issues/29124:

https://build.golang.org/log/994e945a2a0f4e4ac2efdbabf9c7fedcf402553e

That was for the vet binary but the symptoms were the same: a 100% CPU hung process. Same builder, but a host binary.

**Comment by ianlancetaylor** [comment]
Closing as dup of #29385.
