### ISSUE TITLE
Making a channel nil and doing nothing else does not compile

### ISSUE THREAD

**Issue by ugjka** [golang/go#29414]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ugjka/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ugjka/goworks"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build258837340=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://play.golang.org/p/_5c_ED0YfZi

```go
package main

func main() {
	c := make(chan chan int)
	go func() {
		a := make(chan int)
		c <- a
	}()
	i := <-c
	i = nil
}
```

### What did you expect to see?

program should compile or run

### What did you see instead?
prog.go:13:2: i declared and not used

**Comment by randall77** [comment]
This is how Go works.  For example:
```
package main

func main() {
	x := 0
	x = 0
}
```
gives the error
```
x declared and not used
```

If you want to introduce a use of a variable without really using it, do `_ = i`.

**Comment by ugjka** [comment]
well isn't a channel a reference type? what if i have a code somewhere else that uses the same channel and checks if it is nil?

**Comment by dominikh** [comment]
Your code is not doing that.

Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
