### ISSUE TITLE
You can see the source code of the compiled file.

### ISSUE THREAD

**Issue by Magicskys** [golang/go#29420]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.11
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
Use the tail tool to print files
tail file

### What did you expect to see?
How can I not expose the source code?

### What did you see instead?
When I used tail to print binary files, I exposed the source code.
OS : UNIX/LINUX/MAC OS
use : tail file

**Comment by agnivade** [comment]
> Use the tail tool to print files

Which files ? How do we get such a file ? Please give us _specific_ instructions.

**Comment by Magicskys** [comment]
@agnivade 

> Which files ? How do we get such a file ? Please give us specific instructions.

This is a file of mys. After the tail, I can see the package I imported or some other things.
I am not sure if this is normal, or is there any way to prevent others from seeing this?

If you need this file I can provide you with a temporary file download address. I also found this kind of situation in other documents, maybe you can also test it.

![image](https://user-images.githubusercontent.com/12908806/50441189-7bb63980-0934-11e9-884a-a40023d759b5.png)

**Comment by ALTree** [comment]
This is #19226, and it is expected. 

> Stripping package paths would break runtime.Caller and reflect.Type.PkgPath. I don't think there is any reasonable way that we can do it.

In theory you could use the `-trimpath` flags and the `-w -s` linker flags to somewhat reduce the amount of meta-information included in the binaries (see https://github.com/golang/go/issues/19226#issuecomment-281744266), but AFAIK the use of `-trimpath` is discouraged.

**Comment by agnivade** [comment]
Yes, so in #19226, the user is using `strings` on the binary. But the OP is using `tail`. It is quite impossible to see plain text using just tail on a binary. Hence I was a bit baffled.

**Comment by ALTree** [comment]
> It is quite impossible to see plain text using just tail on a binary. 

I don't think this is completely true; I see a fair amount of plain-text when I `tail` C binaries on my system

**Comment by agnivade** [comment]
Ah you are right ! That is because this is at the end of the file (which I failed to realize contains plain-text data). 

It seems like this is expected as mentioned in #19226. So I am closing this one. Thanks for the clarification @ALTree.

**Comment by Magicskys** [comment]
Thank you very much for your help, thank you. @agnivade @ALTree
