### ISSUE TITLE
x/mobile: 

### ISSUE THREAD

**Issue by mybirthfather** [golang/go#29421]
### What version of Go are you using (`go version`)?

<pre>
$ go version  1.11.1

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by agnivade** [comment]
Empty issue.

**Comment by agnivade** [comment]
Please kindly open a new issue instead of reusing a different issue.
