### ISSUE TITLE
"Access is denied" error when deleting a file under windows even though it has full read/write permissions.

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#29424]
### What version of Go are you using (`go version`)?
go1.11.4 windows/amd64
and
go1.10.7 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\admin\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build345865710=/tmp/go-build -gno-record-gcc-switches

### What did you do?
trying to figure out a failing test under windows.
https://github.com/prometheus/tsdb/pull/343
https://travis-ci.org/prometheus/tsdb/jobs/469980072

db_test.go:939: unexpected error: delete obsolete block 01CZN2YDPBHCHHK160ZCJ4D11W: remove C:\Users\travis\AppData\Local\Temp\test629439161\01CZN2YDPBHCHHK160ZCJ4D11W\chunks\000001: Access is denied.

https://github.com/prometheus/tsdb/pull/343/files#diff-7a117cbfd5485ed35efcbb2995c37aa0R664

I double checked and nothing is locking or accessing the file. It fails every time even when I run it locally.
The file has rw permissions for all users and there is no problem to delete the file manually.

### What did you expect to see?
no error

### What did you see instead?
access is denied error

**Comment by alexbrainman** [comment]
> trying to figure out a failing test under windows.

Why do you think it is a Go bug?

> I double checked and nothing is locking or accessing the file. 

You don't need to have file "locked" to get that error message (I assumed you are trying to delete the file). You will get this error message even if you have file opened by any process.

> The file has rw permissions for all users ...

See my answer above.

> ... and there is no problem to delete the file manually.

What are the exact steps to reproduce that here?

Alex

**Comment by krasi-georgiev** [comment]
After the test fails I can delete the file manually which makes me think that some golang child process is using it.

When the file is not closed before trying to delete it I get a different error message which makes me thinks that it is a golang bug and a windows quirk similar to  https://github.com/golang/go/issues/6266

**Comment by alexbrainman** [comment]
> After the test fails I can delete the file manually which makes me think that some golang child process is using it.

If you can provide small repro here, I will investigate.

Alex

**Comment by krasi-georgiev** [comment]
I know what you are asking, but I think the problem is quite specific to the actual code being tested so can't you  just clone https://github.com/mknapphrt/tsdb/tree/size_based_retention and you can run it on a windows machine to reproduce.

in the meanwhile I will also try to simplify it to show a minimal example to reproduce.

**Comment by alexbrainman** [comment]
> can't you just clone https://github.com/mknapphrt/tsdb/tree/size_based_retention and you can run it on a windows machine to reproduce.

Sorry, but I won't. That repo is too large. And it is simply insecure for me to just run unknown code on my computer.

Alex

**Comment by krasi-georgiev** [comment]
I found the problem. it was indeed a problem in the code itself, but the error message was misleading. In any other case I was getting "file opened error" and this time it was "access denied"
