### ISSUE TITLE
doc: SliceTricks insert recipe should be improved

### ISSUE THREAD

**Issue by udhos** [golang/go#29436]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lab/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lab/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lab/basgo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build676942454=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Tried the example below taken from https://github.com/golang/go/wiki/SliceTricks

```
s = append(s, 0) // 0 works only for numbers
copy(s[i+1:], s[i:])
s[i] = x
```

I think that example should be generalized like this:

```
s = append(s, x) // trick to grow slice, this element x will be overridden by copy() below
copy(s[i+1:], s[i:])
s[i] = x
```

Playground: https://play.golang.org/p/8DtYChNbEL-

### What did you expect to see?

I expected the example to work for non-numeric types.

### What did you see instead?

The example did not work for non-numeric types:

`prog.go:24:12: cannot use 0 (type int) as type struct {} in append`

**Comment by ianlancetaylor** [comment]
Thanks, I edited the page to add a comment.  Appending `x` works but I think that is confusing in a different way.
