### ISSUE TITLE
some questions in "container/list"

### ISSUE THREAD

**Issue by zgjff** [golang/go#29431]
In the corresponding operation of these linked lists, there is no judgment whether the node exists in the list, so there may be has problem.
E.g:
```
// insert inserts e after at, increments l.len, and returns e.
func (l *List) insert(e, at *Element) *Element {
	n := at.next
	at.next = e
	e.prev = at
	e.next = n
	n.prev = e
	e.list = l
	l.len++
	return e
}
```
1: If the at node is not in the list
2: The e node already exists in the list

**Comment by hyangah** [comment]
That is an internal, unexported helper method and its callers are supposed to do those checking.
If you found any specific call path that would violate the assumption, please file an issue (or a patch for fix) with a repro case.
--
In the future, please use one of these communication channels in https://golang.org/help/#help
for asking questions like this.
