### ISSUE TITLE
runtime: consider making "slice bounds out of range" messages more explicit

### ISSUE THREAD

**Issue by soslanco** [golang/go#29435]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/src/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build225702417=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
a := make([]int, 0, 5)
fmt.Println(a[5:])
```

### What did you expect to see?
Result must be same as for the following code:
```
a := make([]int, 5)
fmt.Println(a[5:])
```

### What did you see instead?
Error: "panic: runtime error: slice bounds out of range"

**Comment by mvdan** [comment]
The slice indexes must be within the length of the slice, not its capacity. Please read the spec more carefully: https://golang.org/ref/spec#Slice_expressions

**Comment by soslanco** [comment]
For arrays or strings, the indices are in range if 0 <= low <= high <= len(a), otherwise they are out of range. **For slices, the upper index bound is the slice capacity cap(a) rather than the length.**

**Comment by mvdan** [comment]
Note that it says "upper index bound". You can do:

```
a := make([]int, 0, 5)
fmt.Println(a[:5])
```

That is, you can use a slice expression to extend length up to capacity. But arbitrary slice expressions outside of the length range aren't allowed. Perhaps the spec could be made clearer, but I think it's clear enough as it is. I'll leave that to @griesemer.

**Comment by soslanco** [comment]
1.
low<=high
low = cap(a)
2. why the following code work fine:
	a := make([]int, 0, 5)
	fmt.Println(a[5:5])

**Comment by go101** [comment]
I have an impression that the `low` index in `s[low:high]` must not be larger than `len(s)` for a long time.
I just rechecked Go spec, I was wrong. 

`fmt.Println(a[5:])` should work fine, it is a bug at least since Go SDK 1.8.

**Comment by go101** [comment]
Then one section in [my article](https://go101.org/article/bounds-check-elimination.html) should be wrong. And one SSA optimization in `gc` is too conservative.

**Comment by go101** [comment]
Ah, sorry, it is misunderstanding. The compiler is right.

`fmt.Println(a[5:])` doesn't work for it is equivalent to `fmt.Println(a[5:0])`. :)

**Comment by go101** [comment]
But my former impression for the slice rule was really wrong.

**Comment by soslanco** [comment]
Yep!
A missing low index defaults to zero; **a missing high index defaults to the length of the sliced operand**.

**Comment by mvdan** [comment]
Perhaps the runtime panic message could be a bit more explicit. In particular, the issue here is that we're slicing `[5:0]`, which breaks the `low <= high` property.

Aside from that, I don't see what else there is to do in Go. The program is wrong, and the runtime is right to panic. I'll leave the issue open for now to see if anyone has any opinions on improving the runtime panic messages.

**Comment by josharian** [comment]
> I'll leave the issue open for now to see if anyone has any opinions on improving the runtime panic messages.

I don't think we should change the runtime panic messages, for two reasons:

(1) I'm sure that people are relying on the text of the existing messages in their programs. They shouldn't be, but they are, and it's not worth breaking them.

(2) Adding additional information (such as the bounds involved) has a cost in binary size and execution. With the current ABI, passing bounds to the runtime panic routines requires stack space, which might prevent elimination of the function prolog, which can have a substantive performance cost in hot code. And there's always a binary size impact.

**Comment by mvdan** [comment]
I imagined that would be the case (2), but I wanted to make sure :)

**Comment by soslanco** [comment]
Thanks for all your advice.
