### ISSUE TITLE
path/filepath: EvalSymlinks fails when target is file

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#29449]
### What version of Go are you using (`go version`)?

<pre>
go version devel +d459962967 Fri Dec 28 22:14:11 2018 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

No. This bug is not present in go1.11.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Alex\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\users\alex\dev
set GOPROXY=
set GORACE=
set GOROOT=c:\users\alex\dev\go
set GOTMPDIR=
set GOTOOLDIR=c:\users\alex\dev\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Alex\AppData\Local\Temp\go-build894807034=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I run this test
```go
package main_test

import (
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestNTNamespaceSymlink(t *testing.T) {
	tmpdir, err := ioutil.TempDir("", "TestNTNamespaceSymlink")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpdir)

	tmpfile := filepath.Join(tmpdir, "file")
	err = ioutil.WriteFile(tmpfile, []byte(""), 0666)
	if err != nil {
		t.Fatal(err)
	}

	vol := filepath.VolumeName(tmpdir)
	output, err := exec.Command("cmd", "/c", "mountvol", vol, "/L").CombinedOutput()
	if err != nil {
		t.Fatalf("failed to run mountvol %v /L: %v %q", vol, err, output)
	}
	target := strings.Trim(string(output), " \n\r")
	target = target + tmpfile[3:]

	link := filepath.Join(tmpdir, "link")
	output, err = exec.Command("cmd", "/c", "mklink", link, target).CombinedOutput()
	if err != nil {
		t.Fatalf("failed to run mklink %v %v: %v %q", link, target, err, output)
	}

	got, err := filepath.EvalSymlinks(link)
	if err != nil {
		t.Fatal(err)
	}
	if want := tmpfile; got != want {
		t.Errorf(`EvalSymlinks(%q): got %q, want %q`, link, got, want)
	}
}
```

### What did you expect to see?

I expect the test to PASS.

### What did you see instead?

```
=== RUN   TestNTNamespaceSymlink
--- FAIL: TestNTNamespaceSymlink (0.08s)
    a_test.go:41: The system cannot find the path specified.
FAIL
```

I can make the test pass, if I use commit before b32ee0a3c004d4ef79d92bd63200008456da50f3.

/cc @Gnouc and @ianlancetaylor 

Alex

**Comment by alexbrainman** [comment]
> Can you make sure mklink created a valid link?

Oh, it looks like link to me. If I remove `defer os.RemoveAll(tmpdir)` line, then I can look around and everything:
```
C:\>cd %TMP%

C:\Users\Alex\AppData\Local\Temp>dir
 Volume in drive C has no label.
 Volume Serial Number is 9012-A870

 Directory of C:\Users\Alex\AppData\Local\Temp

29/12/2018  05:43 PM    <DIR>          .
29/12/2018  05:43 PM    <DIR>          ..
29/12/2018  10:16 AM    <DIR>          3548C99F-693C-4805-99DA-8F47DEEEC977
               0 File(s)              0 bytes
               3 Dir(s)  299,225,292,800 bytes free

C:\Users\Alex\AppData\Local\Temp>u:\test
--- FAIL: TestNTNamespaceSymlink (0.09s)
    a_test.go:41: The system cannot find the path specified.
FAIL

C:\Users\Alex\AppData\Local\Temp>dir TestNTNamespaceSymlink535467779
 Volume in drive C has no label.
 Volume Serial Number is 9012-A870

 Directory of C:\Users\Alex\AppData\Local\Temp\TestNTNamespaceSymlink535467779

29/12/2018  05:43 PM    <DIR>          .
29/12/2018  05:43 PM    <DIR>          ..
29/12/2018  05:43 PM                 0 file
29/12/2018  05:43 PM    <SYMLINK>      link [\\?\Volume{ea961e77-0000-0000-0000-501f00000000}\Users\Alex\AppData\Local\Temp\TestNTNamespaceSymlink535467779\file]
               2 File(s)              0 bytes
               2 Dir(s)  299,224,088,576 bytes free

C:\Users\Alex\AppData\Local\Temp>type TestNTNamespaceSymlink535467779\link

C:\Users\Alex\AppData\Local\Temp>
```

> The error message indicate that the error is not syscall.ENOTDIR

The error message is syscall.ENOTDIR.

If you look in $GOPATH/src/syscall/zerrors_windows.go file, you will see that syscall.ENOTDIR is actually Windows ERROR_PATH_NOT_FOUND. And ERROR_PATH_NOT_FOUND error text is `The system cannot find the path specified.` Search for ERROR_PATH_NOT_FOUND in https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

Alex

**Comment by Gnouc** [comment]
@alexbrainman I tested myself, and as I said above, the link generated is invalid. I don't have Go setup environment on Windows, so I build this file and run on VM:

```
package main

import (
	"io/ioutil"
	"log"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	tmpdir, err := ioutil.TempDir("", "TestNTNamespaceSymlink")
	if err != nil {
		log.Fatal(err)
	}
	println(tmpdir)

	tmpfile := filepath.Join(tmpdir, "file")
	err = ioutil.WriteFile(tmpfile, []byte(""), 0666)
	if err != nil {
		log.Fatal(err)
	}

	vol := filepath.VolumeName(tmpdir)
	output, err := exec.Command("cmd", "/c", "mountvol", vol, "/L").CombinedOutput()
	if err != nil {
		log.Fatalf("failed to run mountvol %v /L: %v %q", vol, err, output)
	}
	target := strings.Trim(string(output), " \n\r")
	println(tmpfile)
	target = target + tmpfile[3:]

	link := filepath.Join(tmpdir, "link")
	output, err = exec.Command("cmd", "/c", "mklink", link, target).CombinedOutput()
	if err != nil {
		log.Fatalf("failed to run mklink %v %v: %v %q", link, target, err, output)
	}

	got, err := filepath.EvalSymlinks(link)
	if err != nil {
		log.Fatal(err)
	}
	if want := tmpfile; got != want {
		log.Fatalf(`EvalSymlinks(%q): got %q, want %q`, link, got, want)
	}
}
```

When open explorer, double click to the link, a popup shown, said that missing shortcut.
![screenshot from 2018-12-30 00-39-13](https://user-images.githubusercontent.com/4304764/50540835-a2da6880-0bcb-11e9-8705-d057df645091.png)

**Comment by Gnouc** [comment]
@alexbrainman I think the best way is fixing `evalSymlinksUsingGetFinalPathNameByHandle` to return an error with path like `C;\path\to\existing_file\`. So we can remove `symlinkOrDir` hack.

**Comment by alexbrainman** [comment]
> If yes, then if we remove symlinkOrDir checking, how can we solve problem with C:\path\to\existing_file\ case?

I don't have solution at this moment. Maybe leave Windows out of your https://go-review.googlesource.com/c/go/+/155597 altogether. Maybe revert CL 155597 symlink_windows.go changes and move TestIssue29372 into non Windows test file.

I think we should just revert CL 155597 for now.

Alex

**Comment by Gnouc** [comment]
@alexbrainman I did it in CL 155997, builder failed due to timeout problem

**Comment by Gnouc** [comment]
@ianlancetaylor gentle ping

**Comment by Gnouc** [comment]
@ianlancetaylor With a path like `/path/to/existing_file/`, `walkSymlinks` will process each component of the path, first from `/path`, then `/path/to` and so on.

If any component of the part [is not symlink or directory],(https://github.com/golang/go/blob/master/src/path/filepath/symlink.go#L81) then the part is broken.

Now, on Windows, if `walkSymlinks` return an error, then `evalSymlinksUsingGetFinalPathNameByHandle` is used to check the path again. I'm not sure why we do that (I'm not familiar with Windows), but internally, `evalSymlinksUsingGetFinalPathNameByHandle` uses `GetFinalPathNameByHandle`, which somehow normalize `/path/to/existing_file/` to become `/path/to/existing_file`, and return success.

I just check from cmd and Powershell on Windows, if you did:

```
C:\ ls C:\existing_dir\existing_file\
```

You will get path not found error.

The point is if `walkSymlinks` return syscall.ENOTDIR, then nothing to be done anymore. In case of other errors, using `evalSymlinksUsingGetFinalPathNameByHandle` as before.

**Comment by ianlancetaylor** [comment]
@Gnouc OK, thanks.

Is there some way that we can fix 155997 so that we don't have to add more special cases for Windows?  If we need a special test for "/." (and perhaps "/..") then let's do that.

**Comment by Gnouc** [comment]
@ianlancetaylor 

> Is there some way that we can fix 155997 so that we don't have to add more special cases for Windows?

I don't think there's any other ways, except for checking `walkSymlinks` returns `syscall.ENOTDIR` or not.

If we don't want special cases for Windows, then just left the Windows behavior as before 155597. If we went that way, we must except that `EvalSymlinks("/path/to/existing_file/")` returns error on *nix, but `EvalSymlinks("C:\path\to\existing_file\")` success on Windows.

**Comment by ianlancetaylor** [comment]
Can we simply check explicitly for the cases that make a difference?  Like check for a trailing slash and see whether it is a file?

**Comment by alexbrainman** [comment]
> Can we simply check explicitly for the cases that make a difference? Like check for a trailing slash and see whether it is a file?

Good idea. Here is my attempt https://go-review.googlesource.com/c/go/+/156398

Alex

**Comment by Gnouc** [comment]
@alexbrainman Your CL does the same thing with mine: If error from walkSymlinks is syscall.ENOTDIR, just return, other error is passed to `evalSymlinksUsingGetFinalPathNameByHandle` as before.

Also why named `slashAfterFilePathError` instead of plain syscall.ENOTDIR?

Because `slashAfterFilePathError` error for path like `/path/to/existing_file/foo/bar` looks weird.

**Comment by alexbrainman** [comment]
> @alexbrainman Your CL does the same thing with mine: If error from walkSymlinks is syscall.ENOTDIR, just return, other error is passed to evalSymlinksUsingGetFinalPathNameByHandle as before.

Not quite the same. walkSymlinks returns error

https://go-review.googlesource.com/c/go/+/156398/1/src/path/filepath/symlink.go

on lines 76, 81, 90 and 95. My CL only skips evalSymlinksUsingGetFinalPathNameByHandle when error is returned via line 81 (when we find non-symlink/non-directory, but more path to parse on the right remains). And your CL skips evalSymlinksUsingGetFinalPathNameByHandle also when lines 76 and 95 are hit. Line 76 returns error from os.Lstat. What happens, if that os.Lstat. returns syscall.ENOTDIR? Why should we skip evalSymlinksUsingGetFinalPathNameByHandle , if os.Lstat. returns syscall.ENOTDIR? Same for line 95.

> 
> Also why named slashAfterFilePathError instead of plain syscall.ENOTDIR?

See my description above. Also I would like future code reader (myself) to see, that something special is happening here. I can do this by adding comments in many places. But using unusual name also feels good to me.

> Because slashAfterFilePathError error for path like /path/to/existing_file/foo/bar looks weird.

I want it look weird. Otherwise I will miss tricky logic in this code. If you have better name for slashAfterFilePathError, I am listening.

Alex

**Comment by Gnouc** [comment]
@alexbrainman ah right, LGTM
