### ISSUE TITLE
cmd/gofmt: remove key literal with triple nested map

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#29450]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ht/ky_bwgzs4bd5z1hh02k34x_h0000gn/T/go-build035827831=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Execute `gofmt -s -w main.go` with the below main.go:

```go
package main

var foo = map[bool]map[bool]map[bool]int{
        false: {
                false: map[bool]int{false: 0, true: 1},
                true:  map[bool]int{false: 0, true: 1},
        },
        true: {
                false: {false: 0, true: 1},
                true:  {false: 0, true: 1},
        },
}
```

### What did you expect to see?

main.go should change like below:

```go
package main

var foo = map[bool]map[bool]map[bool]int{
        false: {
                false: {false: 0, true: 1},
                true:  {false: 0, true: 1},
        },
        true: {
                false: {false: 0, true: 1},
                true:  {false: 0, true: 1},
        },
}
```

### What did you see instead?

main.go did not change.

**Comment by agnivade** [comment]
I think this is more of a feature request than a bug.

**Comment by griesemer** [comment]
There are many such code simplifications that we could do (or not do). It's not clear that they should be in gofmt. A separate tool might be the better solution.

**Comment by seankhliao** [comment]
Sounds like this is working as intended
