### ISSUE TITLE
runtime: "inserting span already in treap" runtime crash on linux/s390x

### ISSUE THREAD

**Issue by ALTree** [golang/go#29453]
The `linux/s390x` builder is currently failing during bootstrapping, with the following error:

```
Building Go cmd/dist using /var/buildlet/go-linux-s390x-bootstrap.
Building Go toolchain1 using /var/buildlet/go-linux-s390x-bootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
fatal error: inserting span already in treap
```

full log: https://build.golang.org/log/72ab730cfbb04c82ecbf18e46c9dd99a736a9fd0

This started in 69c2c56453cdea1ad32d50fc82193f06b1b33f93 (cmd/compile,runtime: redo mid-stack inlining tracebacks).

cc @randall77 @aclements

**Comment by FiloSottile** [comment]
@randall77 Thanks for mailing a fix. We are planning on cutting the RC this week, so please submit it as soon as possible.
