### ISSUE TITLE
float64 to uint64 conversion for large numbers

### ISSUE THREAD

**Issue by tehsphinx** [golang/go#29463]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gn/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gn/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gn/Exercism/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8p/1rng6dl524z_7n11hnzj_gfr0000gn/T/go-build252639973=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Printing the following two lines should (roughly) print the same number. I understand that the `float64` to `uint64` will not be exact but it should not be that far off.

```
fmt.Println(uint64(1<<64 - 1))            // prints 18446744073709551615 which is equal to math.MaxUint64
fmt.Println(uint64(math.Pow(2, 64) - 1))  // prints  9223372036854775808 which is off by factor 2
```

### What did you expect to see?

I expected to see similar numbers printed. Because of the float64 precision to be exact up to roughly 2^53 (as was kindly pointed to me on the gopher slack by @as and @theckman) I expect to see some rounding issues -- but not off by factor 2.

### What did you see instead?

The number seems to hit a ceiling at math.MaxInt64. Possibly `float64` is first converted to `int64` before it is converted to `uint64`.

**Comment by randall77** [comment]
In floating point, 2^64-1 is not exactly representable.  When you compute it, you get 2^64 as a result. That conversion is out of range for float64->uint64. The results are implementation-defined in this case.

Try `math.Pow(2,64)-1<<11` which is the largest representable float smaller than 2^64. That works:
```
package main

import (
	"fmt"
	"math"
)

func main() {
	for i := uint(0); i < 14; i++ {
		fmt.Printf("%d %t %d\n",
			i,
			math.Pow(2, 64)-float64(int(1)<<i) == math.Pow(2, 64),
			uint64(math.Pow(2, 64)-float64(int(1)<<i)))
	}
}
```
```
0 true 9223372036854775808
1 true 9223372036854775808
2 true 9223372036854775808
3 true 9223372036854775808
4 true 9223372036854775808
5 true 9223372036854775808
6 true 9223372036854775808
7 true 9223372036854775808
8 true 9223372036854775808
9 true 9223372036854775808
10 true 9223372036854775808
11 false 18446744073709549568
12 false 18446744073709547520
13 false 18446744073709543424
```

**Comment by tehsphinx** [comment]
Ok, got it now. First because we have a rouding issue with float64 precision. Then the value is too large for uint64 (because it was rounded up to 2ˆ64 which is out of range for uint64).
