### ISSUE TITLE
lint: go/ast/commentmap.go has variable named new

### ISSUE THREAD

**Issue by rcoreilly** [golang/go#29465]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

just a minor issue discovered in parsing the code with my own parser: probably not a great idea to use the keyword 'new' for a variable here -- obviously it works but isn't it best practice to avoid such naming conflicts?

<pre>
go/ast/commentmap.go:246:

func (cmap CommentMap) Update(old, new Node) Node {
	if list := cmap[old]; len(list) > 0 {
		delete(cmap, old)
		cmap[new] = append(cmap[new], list...)
	}
	return new
}
</pre>

**Comment by ALTree** [comment]
>  isn't it best practice to avoid such naming conflicts?

In general, yes; but that's not always true.

In this case it's a very very small scope, so there's no chance of confusion. Also the current names (`old` and `new`) are probably the best possible in terms of readability of the code. 

Also, `new` is not a keyword. Spec: 
```
Keywords

The following keywords are reserved and may not be used as identifiers.

break        default      func         interface    select
case         defer        go           map          struct
chan         else         goto         package      switch
const        fallthrough  if           range        type
continue     for          import       return       var
```
https://golang.org/ref/spec#Keywords

This was a precise design choice. 

`new` is a pre-declared identifier, and it's allowed to shadow it. It's not a good idea, except in cases, such as the one above, where 1) the scope is very small and there's no chance of confusion 2) the name used makes sense in the context of the function. AFAIK this is the current consensus about the shadowing of pre-declared identifiers.

**Comment by mvdan** [comment]
I agree with @ALTree - for example, there isn't a clear better option for these names. `oldNode` and `newNode` could be an option, but they make the signature unnecessarily repetitive.

Similar changes have been rejected in the past, for example see: https://go-review.googlesource.com/c/go/+/87663
