### ISSUE TITLE
bug: float64 to uint64 ceils at 2^63

### ISSUE THREAD

**Issue by tehsphinx** [golang/go#29468]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gn/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gn/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gn/Exercism/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8p/1rng6dl524z_7n11hnzj_gfr0000gn/T/go-build252639973=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
func main() {
	var i uint64
	for i = 60; i < 65; i++ {
		i2 := 1 << i
		fmt.Println(i, uint64(float64(i2)-1), uint64(math.Pow(2, float64(i))))
	}
}
```

Output is:

```
60 1152921504606846976 1152921504606846976
61 2305843009213693952 2305843009213693952
62 4611686018427387904 4611686018427387904
63 9223372036854775808 9223372036854775808
64 18446744073709551615 9223372036854775808
```

Why does `uint64(math.Pow(2, float64(i)))` ceil at 2^63? It should ceil at 2^64.

### What did you expect to see?

Last line of output should be `64 18446744073709551615 18446744073709551615` or the second number be off by some digits. **It should not be off by 2^63!**

### What did you see instead?

`uint64(math.Pow(2, float64(64)))` is off by 2^63.

**Comment by randall77** [comment]
This is expected (or at least, allowed by the spec):

> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

2^64 cannot be represented in a `uint64`, so the conversion result is implementation-dependent.
