### ISSUE TITLE
strconv: Atoi documentation is slightly misleading

### ISSUE THREAD

**Issue by awulkan** [golang/go#29461]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.11.4
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Irrelevant.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Look at the documentation here: https://golang.org/src/strconv/atoi.go?s=5013:5045#L192

### What did you expect to see?
An explanation of `strconv.Atoi` that matched what it actually did.

### What did you see instead?
An explanation that is only half true.

`Atoi returns the result of ParseInt(s, 10, 0) converted to type int.`

It appears that `Atoi` doesn't just return the value of `ParseInt(s, 10, 0)`, it only calls `ParseInt` as a last alternative, the "slow path". Without checking the code I was under the belief that I could just replace `Atoi` with `ParseInt` and it would basically run the exact same code.

It appears that the documentation was correct up until this commit:
https://github.com/golang/go/commit/46aa9f5437b000fad3696b0cd9fd97995da16411#diff-cbef0f4cdbfb7c355433bb342a5ef463

**Comment by josharian** [comment]
Genuine question: Why do you care?

**Comment by awulkan** [comment]
@josharian What's the point of having documentation if it's outdated? I don't see why it would be a problem to update it to reflect the current state of the code.

**Comment by ALTree** [comment]
Please note that the point of the documentation is not to describe *the way the function is implemented* under the hood. The only purpose of the documentation associated with the function signature is to explain what the function *does* (in the sense: what will it return when you call it).

So, in this case, the following sentence

> Atoi returns the result of ParseInt(s, 10, 0)

is not telling you that the `Atoi` code, literally, is `return Parseint(...)`. It's just a concise way to explain what the function *does*. Basically, the doc it's telling you that `Atoi` is a shortcut for `ParseInt` calls on base 10 number strings.

IMO the documentation appears "outdated" to you because you're reading it too literally.

**Comment by ALTree** [comment]
Anyway, here's a proposal for a slightly more high-level doc:

> func Atoi(s string) (int, error)
> 
> Atoi interprets the string s as a base 10 integer, and returns its value as an `int` type. It is functionally equivalent to a call to `ParseInt(s, 10, 0)`.

**Comment by awulkan** [comment]
I'm sorry if I was a bit unclear. I never meant that I expected the comment to explain in great details what it did under the hood. I was just a bit surprised when the comment didn't match up with the reality. Afaik the "short path" is a lot faster than the ParseInt path, so there's a performance difference between simply running ParseInt directly.

**Comment by bitfield** [comment]
Your honour, my client's statement never claimed that Atoi necessarily _calls_ ParseInt, merely that it returns the same _result_ as ParseInt. I move for a dismissal on the grounds that the defendant has no case to answer.

**Comment by awulkan** [comment]
@bitfield I didn't come here to argue. If no one else thinks it's an issue then fine, simply don't change it and close this issue.

The documentation does claim that it returns *the result* of ParseInt, not the *same result as* ParseInt though. Which led me to believe that it simply called ParseInt (as it once did).

Right now the documentation does try to explain what happens under the hood, but the documentation got outdated when the commit I linked to was introduced.

**Comment by bitfield** [comment]
> @bitfield I didn't come here to argue. If no one else thinks it's an issue then fine, simply don't change it and close this issue.

It's been fixed!
