### ISSUE TITLE
go/build/build.go: uses keyword rune as a variable name

### ISSUE THREAD

**Issue by rcoreilly** [golang/go#29466]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

just a minor issue discovered in parsing the code with my own parser: probably not a great idea to use the keyword 'rune' for a variable here -- obviously it works but isn't it best practice to avoid such naming conflicts?

go/build/build.go:1546:
<pre>
	for _, rune := range s {
		switch {
		case escaped:
			escaped = false
		case rune == '\\':
			escaped = true
...
</pre>

**Comment by ianlancetaylor** [comment]
Thanks for reporting this but I think it's fine.  This isn't a documentation example, and the code is readable as is.  We don't need to churn the code.
