### ISSUE TITLE
time.After() becomes wildly inaccurate with > 50K goroutines

### ISSUE THREAD

**Issue by diegomontoya** [golang/go#29471]
### What version of Go are you using (`go version`)?

<pre>
go version devel +480373c756 Sun Dec 30 19:36:52 2018 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/diego/.cache/go-build"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build351089516=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
<pre>
func TestNativeTimer(t *testing.T) {
	n := 50000 * 2

	ch := make(chan struct{}, n)

	for i := 0; i < n; i++ {
		go func() {
			defer func() {
				ch <- struct{}{}
			}()

			startT := time.Now().UnixNano()
			select {
			case <-time.After(500 * time.Millisecond):
				diff := (time.Now().UnixNano() - startT) / 1e6
				//allow 10% margin
				if diff > 550 || diff < 450 {
					//fmt.Println("diff > 550 || < 450", diff)
					panic(diff)
				}
			}
		}()
	}

	for i := 0; i < n; i++ {
		<-ch
	}

	t.Log("done")
}
</pre>

### What did you expect to see?
We expect this timer.After(500ms) test to pass even with lots of goroutines. Running test in 8750h cpu with Linux kernel 4.20

### What did you see instead?
When n (# of goroutines) goes above 50K, we see our tests starting to fail given 10% error margin. The code above uses 100K but it fails at 50K too.

**Comment by go101** [comment]
`diff < 450` is possible?

**Comment by diegomontoya** [comment]
@go101 We did not see < 450 but only saw the diff value increase (> 550) dramaltically and non-linearly as the number of goroutines increased.

**Comment by go101** [comment]
All the goroutines will be resumed at almost the same time. CPU cores are not limitless. IMO, 10% error margin is pretty good.

**Comment by go101** [comment]
If you let the main goroutine sleep 20ns between creating each new goroutine, the error quite small.

**Comment by diegomontoya** [comment]
@go101 There are 6 cpu cores on my machine. Even with all 50K goroutines waking up at same time, assuming at most 6 can actually do real work at the same time, 50k/6 is less than 10K goroutines per core doing almost no work and still unable to keep up? 

After waking up, each goroutine just need to write to a fully buffered channel which is fast as it can be with very little lock/allocation required. I would assume this should not overload go or am I mistaken?

I guess my question is whether my test above is actually not a test of timer but of active goroutine switching ceiling due to cpu cores within go?

**Comment by go101** [comment]
> ... less than 10K goroutines per core doing almost no work and still unable to keep up?

I think the answer is yes, though I'm not a Go runtime expert. One lock/unlock is needed to wake a goroutine up and the waken goroutine will send a signal to the channel `ch`, which needs another lock/unlock. The `time.Now()` is also not free.

I changed your code a little. It prints nothing, which means the error margin is smaller than 2%.

```golang
	for i := 0; i < n; i++ {
		time.Sleep(2) // slepp 2ns
		go func() {
			defer func() {
				ch <- struct{}{}
			}()

			startT := time.Now().UnixNano()
			select {
			case <-time.After(500 * time.Millisecond):
				diff := (time.Now().UnixNano() - startT) / 1e6
				//allow 10% margin
				if diff > 510 {
					fmt.Println("diff > 510", diff)
					//panic(diff)
				}
			}
		}()
	}
```

**Comment by diegomontoya** [comment]
@go101 

Based on another test below which tests raw Goroutine mass wakeup, my system with 6 cores can do around 3400-3800 goroutine wakeup/work per millisecond . The value is consistent regardless of the number of goroutines which is set to 5 milion but also tested at 10 million with same result.

At 3.4K/ms, it still makes my original test valid since I am giving 10% margin or 50ms margin of error which translate to 50 * 3400  = 170K goroutine wakeup margin to do work but with my timer test set to n = 100K goroutines total, it fails on my machine which still doesn't make sense. Even if my timer test is set to pultry 50k, it fails.

<pre>
func TestGoRoutinesWakeup(t *testing.T) {
	n := 5000000 * 1

	ch := make(chan struct{}, 0)
	wg := sync.WaitGroup{}

	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {
			select {
			case <-ch:
			}
			wg.Done()
		}()
	}

	start := time.Now().UnixNano()

	//wake up all goroutines
	close(ch)

	//wait for all goroutines to finish work
	wg.Wait()

	diff := (time.Now().UnixNano() - start) / 1e6

	t.Log("diff:", diff, " estimated speed per goroutine wakeup/work per ms:", int64(n)/diff)
}
</pre>

**Comment by nussjustin** [comment]
> doing almost no work

As @go101 explained, "almost no work" is not true. The runtime needs to
* create a time.Time value (which will be send to the goroutine)
* send the time.Time value (which involves locking)
* wake up the goroutine
* create a new time.Time value (which involves 2 syscalls if I remember correctly)
* do the comparison
* unwind the defer stack
* send a value on `ch` (which again involves locking and since all goroutines write to the same channel, this is also creating high contention)
* put the goroutine back into the runtimes goroutine pool
* then schedule the next goroutine
* + some bookkeeping for the timer goroutine(s) which manage the timers

**Comment by diegomontoya** [comment]
@nussjustin 

I have updated my Goroutine wakupe test to use defer to show that defer() is almost free since my test result is still around 3400/ms even with defer.

My goroutine wakeup test demonstrates (if test is correct) that goroutine book keeping is not the bottle neck nor is defer() or channel wakeup. 

<pre>

func TestGoRoutinesWakeup(t *testing.T) {
	n := 5000000 * 1

	ch := make(chan struct{}, 0)
	wg := sync.WaitGroup{}

	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			select {
			case <-ch:
			}
		}()
	}

	start := time.Now().UnixNano()

	//wake up all goroutines
	close(ch)

	//wait for all goroutines to finish work
	wg.Wait()

	diff := (time.Now().UnixNano() - start) / 1e6

	t.Log("diff:", diff, " estimated speed per goroutine wakeup/work per ms:", int64(n)/diff)
}
</pre>

**Comment by diegomontoya** [comment]
@go01. Adding micro delays only avoids the problem. I added a Goroutine wakeup test in post above to show that the my 6 core system is capable of 3400 goroutine wakeups per ms (millisecond) which is more than enough margin (50ms) for the original timer test to not fail.

**Comment by nussjustin** [comment]
Most of the time in your test is spent in scheduling and GC.

Since there is basically no real work the runtime is spending most of its time in scheduling (stealing work, sleeping and yielding to the OS) and GC. The GC has to scan all the stacks which adds overhead to the scheduling and the channel operations (write barriers are turned on and the mutators have to assist the GC).

![image](https://user-images.githubusercontent.com/6443781/50552150-78e97a80-0c8d-11e9-8f18-b0614df11983.png)

![image](https://user-images.githubusercontent.com/6443781/50552161-9c142a00-0c8d-11e9-9946-5caa145fdf14.png)

You can remove most of the overhead by calling `runtime.GC()` after `goWg.Wait()`

![image](https://user-images.githubusercontent.com/6443781/50552183-e1d0f280-0c8d-11e9-866f-5c8179b324bf.png)

**Comment by nussjustin** [comment]
If you profile `TestNativeTimer` you will see that it also spends most of it's time in scheduling and GC (you can use either pprof or, if you are on Linux, perf).

**Comment by diegomontoya** [comment]
@nussjustin 

Thank you for the trace! Should have done this earlier. After disabling GC via 
<pre>//disable GC
debug.SetGCPercent(-1)</pre>

even tests at 5million are now passing. 

Argh.......I will close this issue since you have confirmed it is not timer related.
