### ISSUE TITLE
website: textarea text not legible on https://golang.org/ when using Adwaita Dark gnome theme

### ISSUE THREAD

**Issue by 8i8** [golang/go#29482]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.11.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
The issue is with the website.

### What operating system and processor architecture are you using (`go env`)?
Using debian 9.9 with the gnome 3 settings from the standard tweaks menu and firefox-esr.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I have the advaita dark theme activated which sets the text background default to a dark colour and the foreground text to a light colour, white.
All text area text, particularly the examples and runnable code on the website is unreadable without my changing my OS setup.

### What did you expect to see?
Text.

### What did you see instead?
Nothing, unless selected with the mouse.

### Fix

This can be easily fixed by adding the following css to style.css:

textarea {
	color: #222;
}

I would be very grateful for your attention in this matter, I did take a look for the style sheet but have not managed to find it. Here are two screen shots of the way that the site currently appears in my browser:

![screenshot from 2018-12-31 17-45-44](https://user-images.githubusercontent.com/10634856/50564332-56ef0700-0d24-11e9-81b2-392e4be8e9c6.png)
![screenshot from 2018-12-11 18-27-54](https://user-images.githubusercontent.com/10634856/50564337-5c4c5180-0d24-11e9-9339-f47e960062b2.png)

Thank you for your attention.

Iain Hill.

**Comment by bcmills** [comment]
CC @cnoellekb

**Comment by andybons** [comment]
@8i8 how many other sites are broken for you? If you visit https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea do you see the same issue?

**Comment by 8i8** [comment]
@andybons  Yes that is broken too; There is a surprisingly large percentage of the web, for whome the issue is present. Any website that override only one of the default pair, the textarea background colour or the text itself  is rendered illegible. The user settings are the, user settings (This is OS widgit colour not web specific) . I have stopped using the adwaita dark setting whilst working with the documentation, but this is not ideal.

The issue occurs in firefox but not in chromium, it would appear that the chromium browser has done something to either detect or simply rectify when this occurs.

I personally like the setting, as it keeps the white glare down in what wouldbe low light environments; There is far to much contrast, in any dark theme, when large text areas are #ffffff white.

Thank you for your consideration.

**Comment by 8i8** [comment]
@andybons I have just been investigating the firefox settings and found a force system colours checkbox; This has resolved for the w3schools site but not for golang.org; Still White text on beige.

**Comment by andybons** [comment]
Firefox Quantum (64.0.2 (64-bit)) and Chrome both apply their own default styles to the textarea on golang.org. I don’t believe directly stying the textarea is the right solution. Without knowing how gnome’s skinning works it’s difficult to know the best next step. Given that things were broken for a large part of the web until settings were fiddled with, I’m inclined to believe that something is misconfigured or there’s a bug in gnome’s skinning code.

**Comment by jimmyfrasche** [comment]
@andybons UA stylesheets explicitly set a foreground and background color on form inputs. If you leave both as they are, it doesn't matter what those colors are. If you set both explicitly, it doesn't matter what you set them to. If you set one but not the other, it's possible that the two colors fail to contrast. Even if you don't consider this a bug in godoc, you can consider it a feature as setting an explicit color on the textarea makes the site more robust in the face of the myriad ways UA stylesheets can be altered.

**Comment by andybons** [comment]
@jimmyfrasche you’re right, and given we explicitly set the background color but not foreground it may be that the gnome skinning is altering the UA stylesheet. Is this how gnome skinning works?

**Comment by jimmyfrasche** [comment]
I don't know how the gnome skinning works.

The skin could be replacing the UA stylesheets or installing a custom FF theme or it could be setting some color values in the skin that FF gets reads to compute `-moz-FieldText`, which is the default color for textarea in the default FF UA stylesheet. It could be a bug in the skin, the theme that can contain basically arbitrary JS (hooray?), the interface between gnome skins and FF, or the hypothetically modified UA stylesheet. Possibly some interaction between a mix of those scenarios.

There are a lot of ways for it to have gone wrong but adding something like `textarea { color: inherit; }` would protect against all of those scenarios and more by ensuring that the correct colors are always used.

**Comment by 8i8** [comment]
@andybons Thank you for your kind consideration; After a little investigation of the setup, which has not yet reveled the origin of these styling options; I am lead to believe that they could be set further upstream, maybe the webserver gas a global template for page headers and styling?
In which case I don't think that altering them locally would be the best solution. I see that the Codewalk section of the site is styled locally, it also has a slightly different feel due to this, presumably another author, also that there is a test style.css document in the testing area; How would you recommend that I proceed; I am very to be of willing to help and could well be wrong in my assessment of an apparent solution?

Could I run a test version of the site locally so as to be able to see where the cascading effect of styling are taking effect, or not, as the case may be?

Thank you.

**Comment by 8i8** [comment]
@andybons Hi, I having finally found the correct place for this small modification, to the best of my knowledge it is in the correct place to amend all occurrences of the issue; I have made a pull request:
https://github.com/golang/tools/compare/master...8i8:patch-1
Thank you.
