### ISSUE TITLE
database/sql: DB.Conn violates isolation

### ISSUE THREAD

**Issue by rittneje** [golang/go#29483]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jrittner/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jrittner/go-sqlite3"
GORACE=""
GOROOT="/home/jrittner/go"
GOTMPDIR=""
GOTOOLDIR="/home/jrittner/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build359303402=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```go
	db, err := sql.Open("sqlite3", "file:foo.sqlite?cache=private&mode=rwc")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	_, err = db.Exec("DROP TABLE IF EXISTS src")
	if err != nil {
		panic(err)
	}

	_, err = db.Exec("CREATE TABLE src (id INTEGER NOT NULL PRIMARY KEY, data1 INTEGER, data2 INTEGER);")
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	c, err := db.Conn(ctx)
	if err != nil {
		panic(err)
	}
	defer c.Close()

	tx, err := c.BeginTx(ctx, nil)
	if err != nil {
		panic(err)
	}
	defer tx.Rollback()

	_, err = tx.Exec("INSERT INTO src (id, data1, data2) VALUES (1, 100, 1000)")
	if err != nil {
		panic(err)
	}

	r := c.QueryRowContext(ctx, "SELECT COUNT(*) FROM src LIMIT 1")
	var count int
	if err := r.Scan(&count); err != nil {
		panic(err)
	}

	fmt.Println(count)
```

### What did you expect to see?

I expected to either see an error from `QueryRowContext`/`Scan` that the conn was busy, or a result of 0.

### What did you see instead?

I see a result of 1.

This is because `Conn` allows non-transaction methods to be called while it is in the middle of a transaction. Also, I see no way for a driver to tell the difference between a `Query`/`Exec` that comes from the transaction vs. one that doesn't, so I don't consider this to be a driver issue.

This may be considered "user error" rather than a true bug (since I did force it to use the same conn for both), in which case it might be helpful to mention this in the documentation.

**Comment by rittneje** [comment]
Also of note: it allows you to start multiple transactions on the same conn. Previously this could never happen, so in theory there could be drivers that don't handle this properly.

```go
db, err := sql.Open("sqlite3", "file:foo.sqlite?cache=private&mode=rwc")
if err != nil {
    panic(err)
}

c, err := db.Conn(ctx)
if err != nil {
    panic(err)
}
defer c.Close()

tx1, err := c.BeginTx(ctx, nil)
if err != nil {
    panic(err)
}
defer tx1.Rollback()

// This calls down into driver.Conn.Begin.
tx2, err := c.BeginTx(ctx, nil)
if err != nil {
    panic(err)
}
defer tx2.Rollback()

...
```

**Comment by rittneje** [comment]
I think adding some additional information somewhere is warranted. (My preference would be on `sql.Conn` itself since that's where I'd look for it.) The connection pool concept has been a constant source of issues with SQLite, so at present we effectively disable pooling by doing the following:
```go
db.SetMaxIdleConns(1)
db.SetMaxOpenConns(1)
db.SetConnMaxLifetime(0)
```
 I expected `db.Conn` to result in similar semantics, but obviously it does not.

I still maintain that allowing a second transaction to begin is particularly problematic because you could corrupt a driver that wasn't written to expect that to happen.

**Comment by kardianos** [comment]
If you are using SQLite, you may be interested in https://crawshaw.io/blog/one-process-programming-notes and https://godoc.org/crawshaw.io/sqlite .

The docs for DB.Conn clearly state it opens a database session. I'm not sure what other behavior you would expect. I suppose an explicit conn.Begin() could block all other non-transaction queries until the rollback or commit. But that would seems kinda odd too.

**Comment by rittneje** [comment]
> I suppose an explicit conn.Begin() could block all other non-transaction queries until the rollback or commit.

Yes, this is the behavior I expected, as it matches what happens when you "disable" the connection pool.
