### ISSUE TITLE
time: Sleep(1 * time.Nanosecond) pauses at least 1.9ms on Windows 10 or Windows 7

### ISSUE THREAD

**Issue by destinysync** [golang/go#29485]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\admin\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build968081038=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

[https://play.golang.org/p/zbe1kiCREc0](https://play.golang.org/p/zbe1kiCREc0)

time.Sleep function works correctly on Go Playground and Ubuntu desktop 18.04, but when on Windows 10 or Windows 7, time.Sleep pauses at least 1.9ms

### What did you expect to see?
1ns

### What did you see instead?
1.9951ms

**Comment by 40345839668** [comment]
18.09 Sürüm İşletim sistemi windows10 pro, İşlemci mimarisi İ5 4460 proocesor yapı 17763

**Comment by 40345839668** [comment]
Durma sebebine gelince sanırım macun yerine 300 c. ısıya duyarlı silikon kullandım teksebebi bu olmalı.

**Comment by ianlancetaylor** [comment]
@40345839668 Most people who use this issue tracker can not read Turkish.  Please comment in English.  Thanks.

@destinysync A sleep of one nanosecond is unlikely to work on any system.  A sleep is always going to be limited by the clock frequency of the system.

**Comment by alexbrainman** [comment]
> when on Windows 10 or Windows 7, time.Sleep pauses at least 1.9ms

This is what I see on my Windows computer too.

1ms sleep for time.Sleep(time.Nanosecond) sounds about right for current Windows time.Sleep implementation. If you have suggestion on how to improve the code, you are most welcome.

Alex

**Comment by ianlancetaylor** [comment]
I was imprecise in referring to the clock frequency.  I didn't mean the frequency of the processor.  I meant the frequency of the operating system: how often it does timer interrupts.

It's entirely possible that there is something to be fixed here.  But `time.Sleep(time.Nanosecond)` is unlikely to ever work as you expect.  You should use a different mechanism.  For a nanosecond delay a busy wait is appropriate.  In fact just fetching the current time will most likely take more than one nanosecond.

**Comment by networkimprov** [comment]
@destinysync what does this yield?
```
a := time.Now()
b := <-time.After(1*time.Nanosecond)
fmt.Println(b.Sub(a))
```

**Comment by davecheney** [comment]
@destinysync `time.Sleep` is not specified to sleep for precisely the duration requested, it is specified to sleep for _at least_ the duration requested. The delta between the minimum--the duration you requested--and the observed is implementation and operating system dependent. I don't think there is anything to be fixed here.

**Comment by networkimprov** [comment]
That shows a possible resolution of 100ns (0.0001ms). It may be calling an obsolete Windows API which doesn't support that.

Windows 7 supports 100ns resolution timers:
https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-setwaitabletimerex

Windows 2000 supports 100ns resolution sleep:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kedelayexecutionthread

**Comment by dominikh** [comment]
Related: https://github.com/golang/go/issues/8687

**Comment by 40345839668** [comment]
Auto clock implementation in Turkey 1 hour different works we have to set this summer because it does not have the application

**Comment by networkimprov** [comment]
@alexbrainman @destinysync I suggested changing this issue to be about time.After/NewTimer. If you prefer, I'll open a separate issue regarding resolution of time.NewTimer on Windows; please let me know!

**Comment by alexbrainman** [comment]
> I suggested changing this issue to be about time.After/NewTimer. If you prefer, I'll open a separate issue regarding resolution of time.NewTimer on Windows; please let me know!

I do not know how to fix this issue. Regardless of what description of this issue is.

Alex

**Comment by networkimprov** [comment]
SetWaitableTimer claims 100ns timer resolution; Go currently uses it in the profiler but not elsewhere (that I could find). Would that help with time.NewTimer?

https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-setwaitabletimerex

**Comment by ianlancetaylor** [comment]
Currently `time.Sleep` operates at the scheduling frequency of the operating system.  It is not a high precision timer.  On my laptop `time.Sleep(1 * time.Nanosecond)` sleeps for over 500 nanoseconds.  That's quite a bit better than Windows, but still two orders of magnitude larger than the requested sleep.

The function is documented as "`Sleep` pauses the current goroutine for at least the duration d."  While perhaps it would useful to provide high precision timers in Go, the mechanism will not be `time.Sleep`.  I'm going to close this issue.
