### ISSUE TITLE
strconv: FormatFloat rounding error

### ISSUE THREAD

**Issue by cyberphone** [golang/go#29491]
### What version of Go are you using (`go version`)?

<pre>

go version go1.11.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Anders\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Anders\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Anders\AppData\Local\Temp\go-build2129905
62=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I'm trying to implement a JSON canonicalization scheme requiring numbers to be expressed in the shortest way.  prec -1 seemed like a better alternative than porting V8's solution but unfortunately it seems that the -1 option is broken:

```go
package main

import (
    "strconv"
    "math"
    "fmt"
)

func fpformat(hex string, format byte, precision int, expected string) {
    ieeeU64, err := strconv.ParseUint(hex, 16, 64)
    if err != nil {
        panic(hex)
    }
    ieeeF64 := math.Float64frombits(ieeeU64)
    shortestNumber := strconv.FormatFloat(ieeeF64, format, -1, 64)
    moreDecimals := strconv.FormatFloat(ieeeF64, format, precision, 64)
    plusOneDecimal := strconv.FormatFloat(ieeeF64, format, precision + 1, 64)
    fmt.Printf("\nfloat64hex: %s\n", hex)
    fmt.Printf("   actual using precision[-1]: %s\n", shortestNumber)  // INCORRECT in go1.11.4 windows/amd64
    fmt.Printf(" expected using precision[-1]: %s\n", expected)
    fmt.Printf("   actual using precision[%2d]: %s\n", precision, moreDecimals)
    fmt.Printf("   actual using precision[%2d]: %s\n", precision + 1, plusOneDecimal)
}

func main() {
    fpformat("439babe4b56e8a39", 'f', 0, "498484681984085570")
    fpformat("c4dee27bdef22651", 'g', 17, "-5.8339553793802237e+23")
}
```

### What did you expect to see?

<pre>
float64hex: 439babe4b56e8a39
   actual using precision[-1]: 498484681984085570
 expected using precision[-1]: 498484681984085570
   actual using precision[ 0]: 498484681984085568
   actual using precision[ 1]: 498484681984085568.0

float64hex: c4dee27bdef22651
   actual using precision[-1]: -5.8339553793802237e+23
 expected using precision[-1]: -5.8339553793802237e+23
   actual using precision[17]: -5.8339553793802237e+23
   actual using precision[18]: -5.83395537938022366e+23
</pre>
### What did you see instead?
<pre>
float64hex: 439babe4b56e8a39
   actual using precision[-1]: 498484681984085560
 expected using precision[-1]: 498484681984085570
   actual using precision[ 0]: 498484681984085568
   actual using precision[ 1]: 498484681984085568.0

float64hex: c4dee27bdef22651
   actual using precision[-1]: -5.8339553793802236e+23
 expected using precision[-1]: -5.8339553793802237e+23
   actual using precision[17]: -5.8339553793802237e+23
   actual using precision[18]: -5.83395537938022366e+23
</pre>

**Comment by ALTree** [comment]
I'm not sure I understand what issue you are reporting. The `-1` option for prec is documented as

> The special precision -1 uses the smallest number of digits necessary such that ParseFloat will return f exactly. 

And this seems to hold for both your numbers:

```
package main

import (
	"fmt"
	"math"
	"strconv"
)

func test(num string) {
	n, err := strconv.ParseUint(num, 16, 64)
	if err != nil {
		panic("main")
	}

	f := math.Float64frombits(n)
	s := strconv.FormatFloat(f, 'f', -1, 64)
	g, err := strconv.ParseFloat(s, 64)
	if err != nil {
		panic("main")
	}

	fmt.Printf("%b\n", f)
	fmt.Printf("%b\n", g)
	fmt.Println(f == g)
}

func main() {
	test("439babe4b56e8a39")
	test("c4dee27bdef22651")
}
```

Note how `f` (the number I called `FormatFloat` on with prec -1) and `g` (the number I call `ParseFloat` on) are bit-per-bit equal.

**Comment by cyberphone** [comment]
As you can see in my example using precision 0 for "integers" result in a value which after rounding should give another result while still being compatible with both ParseFloat and V8/EcmaScript.

This is a request rather than a bug.  I did port 2000 lines to .NET but that wasn't a pleasure :(

**Comment by cyberphone** [comment]
Although a bit ugly the following workaround
https://github.com/cyberphone/json-canonicalization/blob/master/go/src/webpki.org/es6numfmt/es6numfmt.go
passes the 100 million test value suite:
https://github.com/cyberphone/json-canonicalization/tree/master/testdata

**Comment by bmkessler** [comment]
I'm not sure if this falls into a proposed change since (as noted above) the documentation only states that precision -1 outputs _one_ of the shortest decimal representations that satisfies the round trip property, but I think the expectation is that the -1 precision output is also correctly rounded to the closest decimal representation to the input.  Note that issue #2625 was resolved to produce the closest decimal.  I believe that closest decimal is what other programming languages typically provide as well.  The bug appears to be in [this section ](https://github.com/golang/go/blob/master/src/strconv/ftoa.go#L305-L307) of roundShortest:
```
// Okay to round up if upper has a different digit and either upper
// is inclusive or upper is bigger than the result of rounding up.
okup := m != u && (inclusive || m+1 < u || i+1 < upper.nd)
```
The round up comparison is byte-by-byte and so incorrectly fails for these inputs:
```
lower: 498484681984085536
d:     498484681984085568
upper: 498484681984085600
```
49848468198408557 < 49848468198408560 so should have `okup == true`
but '7' > '0' in the last digit
```
lower: 583395537938022332891136
d:     583395537938022366445568
upper: 583395537938022400000000
```
58339553793802237 < 58339553793802240 so should have `okup == true`
but '7' > '0' in the last digit

Adding @rsc as the author of the conversion routine.

**Comment by cyberphone** [comment]
The rounding issue also applies to a small set of floating point numbers:
```code
Hex: c4af4eaaa5e19289
g minus -1: 
-7.3922251744542715e+22

g 17:
-7.3922251744542716e+22
```

**Comment by bmkessler** [comment]
That case is also the same issue with byte-wise comparison to '0'
```
lower: 73922251744542711611392
d:     73922251744542715805696
upper: 73922251744542720000000
```
73922251744542716 < 73922251744542720  so should have `okup == true`
but '6' > '0' in the last digit

**Comment by cespare** [comment]
Though this bug has been around for a long time, I also happened to independently discover it a few days ago while implementing Ryu (see https://github.com/golang/go/issues/15672#issuecomment-453806995). I sent a CL though it will have to wait for Go 1.13.

Thanks @bmkessler for the very helpful analysis.

**Comment by cyberphone** [comment]
@cespare I tried the Java version of Ryu on x0000000000000001 and it returned 4.9e-324 which differs from the current Go implementation which returns 5e-324 (which also is compliant with JavaScript).

**Comment by cyberphone** [comment]
@cespare Do you think I should try to run my 100M test suite against your Ryu implementation?

https://github.com/cyberphone/json-canonicalization/tree/master/testdata#es6-numbers

**Comment by ulfjack** [comment]
The Java implementation attempts to follow the specification of Java's Double.toString [1], which says that it must return at least two digits. Out of all two-digit numbers, 4.9e-324 is closest to the exact floating point value in this case, so that's what it returns. The problem described in https://github.com/ulfjack/ryu/issues/83 is that it sometimes doesn't return the closest two-digit number because there's a one-digit number that's shorter. The C implementation doesn't do that, and I have not found any differences between it and Grisu over a fairly large number of tests.

[1] https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#toString(double)
> There must be at least one digit to represent the fractional part

**Comment by ulfjack** [comment]
I updated the README for Ryu, and have a feature request open for the Java implementation to generate shortest output as well at https://github.com/ulfjack/ryu/issues/87. Thanks @cyberphone for bringing this to my attention.

**Comment by remyoudompheng** [comment]
At exponent 64, every 1250th float64 is affected by the issue (and is fixed by the patch)
```
  for k := 0; k < 1000; k++ {
        mant := (36028797018967+10*k)*125 + 62
        f := math.Ldexp(float64(mant), 12)
        t.Logf("%.19e %v", f, f)
  }
```
Output:
```
    fptest_test.go:141: 1.8446744073711357952e+19 1.8446744073711357e+19
    fptest_test.go:141: 1.8446744073716477952e+19 1.8446744073716477e+19
    fptest_test.go:141: 1.8446744073721597952e+19 1.8446744073721597e+19
    fptest_test.go:141: 1.8446744073726717952e+19 1.8446744073726717e+19
    fptest_test.go:141: 1.8446744073731837952e+19 1.8446744073731837e+19
    fptest_test.go:141: 1.8446744073736957952e+19 1.8446744073736957e+19
    fptest_test.go:141: 1.8446744073742077952e+19 1.8446744073742077e+19
```

**Comment by jackhftang** [comment]
Not if it is the same bug, but this one is relatively small. 
```
strconv.FormatFloat(255.255, 'f', 2, 64) 
```
The above output "255.25", but I expect "255.26". 

go version go1.12.1 darwin/amd64

**Comment by remyoudompheng** [comment]
> Not if it is the same bug, but this one is relatively small.
> 
> ```
> strconv.FormatFloat(255.255, 'f', 2, 64) 
> ```
> 
> The above output "255.25", but I expect "255.26".
> 
> go version go1.12.1 darwin/amd64

No, 255.25 is the correct rounding. float64(255.255) is slightly less than the actual 255.255.
```
fmt.Printf("%.18f\n", float64(255.255))
-> 255.254999999999995453
```

**Comment by cyberphone** [comment]
Apparently JavaScript agree:
```
Number.parseFloat("255.255").toPrecision(5)
> "255.25"
```
The rounding is performed at the binary level which is one reason to why floating point is not suitable for monetary amounts
