### ISSUE TITLE
runtime: recived SIGSEGV in runtime.mapiternext

### ISSUE THREAD

**Issue by zct** [golang/go#29496]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.9
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
A local map var, no concurrency. code like this:
![image](https://user-images.githubusercontent.com/4023051/50582541-46629c00-0e9e-11e9-8742-7947cd39eb56.png)

panic in line 17.  It seems happened only once in my server, I can't Find out why 

### What did you see instead?

panic call stack trace:
![image](https://user-images.githubusercontent.com/4023051/50582560-6befa580-0e9e-11e9-8b30-32d1897b56e6.png)

**Comment by odeke-em** [comment]
Thank you for filing this issue @ZCT and welcome to the Go project!

How often can this problem be reproduced? Would it be possible for you to also try Go1.11 or the Go1.12beta*?

I'll kindly page some experts @randall77 @josharian @ianlancetaylor

**Comment by odeke-em** [comment]
Empirically that crash doesn't make sense because we already deferenced `it *hiter` before we hit that line on which it crashed

https://github.com/golang/go/blob/f865b5fefeafaf76ce6ff99e44d41c52cb6b884b/src/runtime/hashmap.go#L789

unless perhaps garbage collection reaped `it` the pointer to the map iterator. For that I'll also page @aclements @RLH

**Comment by ZCT** [comment]
> Thank you for filing this issue @ZCT and welcome to the Go project!
> 
> How often can this problem be reproduced? Would it be possible for you to also try Go1.11 or the Go1.12beta*?
> 
> I'll kindly page some experts @randall77 @josharian @ianlancetaylor

thank you for your kindly reply, It seems can't reproduce. If it happened again, I'll post full stack trace log. My server was stable running for half an year, this is first panic I received. For me, it's looks like a strange behavior in golang

**Comment by agnivade** [comment]
Hello @zct - I would request you to try with the latest 1.12 release and report back if you still see the crash. And just to be sure there are no races, please ensure to run with the -race flag.

**Comment by zct** [comment]
> Hello @zct - I would request you to try with the latest 1.12 release and report back if you still see the crash. And just to be sure there are no races, please ensure to run with the -race flag.
