### ISSUE TITLE
go append function hangs (does not return)

### ISSUE THREAD

**Issue by jvegaseg** [golang/go#29493]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>
also tested in a Mac:
<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/www/html/vozintel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build989127767=/tmp/go-build"
</pre></details>

### What did you do?

Example program where to reproduce the "hang". Let it run during a while (1 or 2 minutes)
<pre>
package main

import (
	"fmt"
	"math/rand"
	"os"
	"os/signal"
	"time"
)

type MetricCpuStatTest struct {
	TimeWhenCalculated int64
	Usage              int
}

func MetricsTest() *MetricCpuStatTest {
	var newData MetricCpuStatTest
	newData.Usage = rand.Intn(100)
	newData.TimeWhenCalculated = time.Now().Unix()

	// Some void operations
	var arr []string
	for i := 0; i < 100; i++ {
		arr = append(arr, "void data void data void data void data")
	}

	return &newData

}

func main() {
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	signal.Notify(c, os.Kill)

	go func() {
		a := 0
		for {
			// DO NOTHING, only for full busy a goroutine
			a = a + 1
			a = a - 1

			// time.Sleep(100 * time.Millisecond)
		}
	}()

	go func() {
		for {
			time.Sleep(100 * time.Millisecond)

			fmt.Printf("Calculating...\n")
			stat := MetricsTest()
			fmt.Printf("New Data: CPU %d\n", stat.Usage)
		}

	}()

	// Block until a signal is received.
	<-c

}

</pre>

### What did you expect to see?
Do not stop, and always return when calling append

### What did you see instead?

It does not returns from function append after running during a while

**Comment by jvegaseg** [comment]
Note: if you uncomment the line

`time.Sleep(100 * time.Millisecond)`

in first goroutine, it does not hangs.

**Comment by ianlancetaylor** [comment]
This doesn't have anything to do with `append`, it's because of your tight loop.  If just want to busy wait, call `runtime.Gosched`.  Closing this issue as a dup of #10958.

**Comment by jvegaseg** [comment]
Adding 
`runtime.GOMAXPROCS(10)`
hangs anyway

This means that we have to insert "runtime.Gosched()" in loops of very busy goroutines to avoid this type of hangs?

Regards,

**Comment by ianlancetaylor** [comment]
Yes.  The bug described in #10958 triggers for code that does a tight loop with no function calls or channel operations.
