### ISSUE TITLE
cmd/compile: new mid-stack inlining tracebacks broke TestNexting

### ISSUE THREAD

**Issue by aclements** [golang/go#29511]
[CL 152537](https://golang.org/cl/152537) broke TestNexting. For example: https://build.golang.org/log/ad327f4df87dc312a4840aa82dccbaf832822120

/cc @dr2chase @randall77

**Comment by dr2chase** [comment]
I suspect the resolution is to just update the comparison files, but I think I want to look at a different plan for assigning statement boundaries for 1.13 because this is not-good.
