### ISSUE TITLE
go mod vendor should add go generate dependencies

### ISSUE THREAD

**Issue by coolaj86** [golang/go#29516]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aj/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/aj/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/aj/github.com/xxx/xxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0g/01vpdjf507z8qk3lvgfnh1hw0000gn/T/go-build639981897=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I have a module which is not a code dependency, but rather a `go generate` dependency:

```
//go:generate go run github.com/UnnoTed/fileb0x b0x.toml
```

I'm trying to add it to my `vendor` directory and have it stay there.

### What did you expect to see?

I'd expect to be able to run `go mod vendor` and have the generate dependencies copied over as well.

### What did you see instead?

Even though I've manually added the go generate dependency into `go.mod` it's not it's not being copied to `vendor` when I run `go mod vendor`. In fact, it's sometimes pruned from `vendor` when I run that.

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/25922 and https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module. `go mod` generally removes (prunes) unused dependencies, so right now you need to keem them as imports somewhere.

**Comment by coolaj86** [comment]
@mvdan Thanks for the quick reply. It's a binary, not a library, so it's not possible even to use `_` to import and ignore. Any other ideas?

**Comment by coolaj86** [comment]
For the benefit of others:

`tools/tools.go`:
```go
// +build ignore

// tools is a dummy package that will be ignored for builds, but included for dependencies
package tools

import (
  _ "example.com/foo/thing"
)
```

```bash
go mod tidy
```

This will cause the utilities to be included in `go.mod` and with `go mod vendor` (after a `go mod tidy` or other command that causes deps to re-evaluate), but they will not be checked (i.e. a binary can be included as a dependency, which is not allowed for a build).
