### ISSUE TITLE
go log lock in High concurrency

### ISSUE THREAD

**Issue by tokingHong** [golang/go#29524]
![image](https://user-images.githubusercontent.com/39825820/50630017-0375f680-0f7a-11e9-8068-57fbb57ea62a.png)
![image](https://user-images.githubusercontent.com/39825820/50630034-20122e80-0f7a-11e9-97a1-40f70d099904.png)

In my project ,too many goroutine made my server no response.When I use pprof to locate the problem,found above.Does it means logger's occure dead lock? Or it was a normal phenomenon in high concurrency?

**Comment by mvdan** [comment]
As you can see, loggers use a lock, so only one goroutine can lock at a time. If you have many cores and cpu-intensive work, you may consider working around the limitation, such as using multiple loggers or having certain critical functions not log at all.

But this isn't a bug in the log package nor in Go, as far as I can see. For questions about Go, see https://golang.org/wiki/Questions.
