### ISSUE TITLE
x/image/font/sfnt: read kerning from GPOS 

### ISSUE THREAD

**Issue by olt** [golang/go#29528]
Most modern fonts like Noto or Roboto do not provide a `kern` table. Instead they use the `GPOS` table for kerning. 

`GPOS` can be quite complex and it also supports y-displacements which is not supported by the current font.Face API. I'm also aware that text shaping is a complex topic and out of scope for `x/image/font/sfnt`. However, Face.Kern is already available in the API for basic kerning and it would be great to be able to use this with (nearly) all fonts, at least for latin scripts.

Would you accept a patch that reads kerning information from `GPOS`, if `kern` is not available? Or is this out of scope already?

/cc @nigeltao

**Comment by nigeltao** [comment]
I'd take a patch that read kerning information from `GPOS`, especially if it didn't involve any new public API.

Longer term, I'd also like public API to expose the `GPOS` table, as that would be needed by text shapers, but that (API design) is a much harder problem, especially without an actual text shaping implementation to shake out any design bugs.
