### ISSUE TITLE
os: clarify meaning of "truncate"

### ISSUE THREAD

**Issue by UlisseMini** [golang/go#29531]
For non-native speakers the term "empty" might be easier to understand
eg change `// truncate regular writable file when opened.` to `// truncate (empty) regular writable file when opened.` in the [O_TRUNC](https://github.com/golang/go/blob/0175064e697d3e072573b32173299b7edbda7360/src/os/file.go#L76) constant

**Comment by bradfitz** [comment]
Sorry, this adds more confusion than it helps: "empty" can be both a verb or an adjective.

Let's leave it as-is. People can look up the word. It's the same word used elsewhere in Unix/POSIX/etc.

**Comment by UlisseMini** [comment]
Alright i understand :)
