### ISSUE TITLE
x/crypto/sha3: add Keccak 512 support

### ISSUE THREAD

**Issue by realdave** [golang/go#29533]
This is an extension of previously accepted proposal #19709 which suggested adding legacy Keccak 256 support.

As mentioned by @karalabe, the 512 variant is also [used by Ethereum](https://github.com/ethereum/go-ethereum/blob/49975264a8d37aa9af1a2b71015059245c0c2e0b/consensus/ethash/algorithm.go#L180). I propose adding a new function (`NewLegacyKeccak512`) to support it.

**Comment by karalabe** [comment]
I already opened a CL 7 months ago https://go-review.googlesource.com/c/crypto/+/125795
