### ISSUE TITLE
x/tools/godoc: non-go file HTML rendering adds a leading tab, which can become visible

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29568]
The [`CONTRIBUTORS`](https://github.com/golang/go/blob/4c3b4dfd798fa24ef33cd0f5c80e4b9857d9849e/CONTRIBUTORS) file does not have any leading whitespace on its lines. However, when viewed at https://golang.org/CONTRIBUTORS, the generated HTML adds leading whitespace (a single tab character):

<img src="https://user-images.githubusercontent.com/1924134/50705014-5fe31f80-1027-11e9-9aa0-e582cd928cb7.png" width=525px>

In most cases the tab character does not show visually up due to the way CSS is used to style content:

<img src="https://user-images.githubusercontent.com/1924134/50705044-77220d00-1027-11e9-8baf-db2e77d58296.png" width=616px>

However, in some cases it becomes highly visible and distracting:

<img src="https://user-images.githubusercontent.com/1924134/50705074-9456db80-1027-11e9-9ea2-0b5c74f3b719.png" width=663px>

This does not affect the plain-text rendering mode of text files (e.g., https://golang.org/CONTRIBUTORS?m=text), only the HTML rendering.

**Comment by dmitshur** [comment]
As noted by @bradfitz, this doesn't seem to affect rendered .go files. There is no leading tab character inserted in HTML on pages like https://golang.org/src/net/http/server.go:

<img src="https://user-images.githubusercontent.com/1924134/50705418-c1f05480-1028-11e9-9f29-bc989807defe.png" width=524px>

It does affect other text files without an extension like https://golang.org/LICENSE, https://golang.org/AUTHORS, and files with non-go extension like https://golang.org/src/make.bash.

**Comment by agnivade** [comment]
The leading tabs were always there. 
`fmt.Fprintf(w, "<span id=\"L%d\" class=\"ln\">%6d</span>\t", line, line)`
Removing `\t` from there fixes it. But I am wondering the `\t` was there for a reason in the first place ?

The CSS change which caused this effect is https://github.com/golang/tools/commit/4bc20fc7916bc21abba37451a6923cffa9a2cd3f#diff-62ab65160863cb8b1bd55a2653402fe4, which was made to fix another tab issue.

Specifically, if I disable these 2 properties from style.css .`ln {` class -

```css
* Ensure 8 characters in the document - which due to floating
* point rendering issues, might have a width of less than 1 each - are 8
* characters wide, so a tab in the 9th position indents properly. See
* https://github.com/webcompat/web-bugs/issues/17530#issuecomment-402675091
* for more information. */
display: inline-block;
width: 8ch;
```

the leading space goes away, although the tab is still there in the html.

/cc @bradfitz @dmitshur @andybons @kevinburke for decision.

**Comment by dmitshur** [comment]
My guess is the tab was used for adding spacing. If no evidence otherwise can be found, I think we should remove it and implement spacing with a margin-right CSS property on `ln` class, if more spacing is needed.

@agnivade Where in the source code is that `fmt.Fprintf` call? Can you confirm that it’s only three when rendering non-.go files, but not when rendering .go ones? It’d be great to learn why that difference exists, if possible.

Thank you for investigating this issue.

**Comment by dmitshur** [comment]
Based on the history of events, I understand the tab character was used to ensure correct spacing. It's no longer needed and actively harmful after the change in https://github.com/golang/tools/commit/4bc20fc7916bc21abba37451a6923cffa9a2cd3f#diff-62ab65160863cb8b1bd55a2653402fe4. For that reason, and also because having it there makes copying the text harder (it includes a leading tab character not present in the source file), we should remove it.

When removing it, please test that various non-.go files render okay and that it doesn't cause any spacing issues. If it does, we should address those with CSS instead of a tab character. But after the change https://github.com/golang/tools/commit/4bc20fc7916bc21abba37451a6923cffa9a2cd3f#diff-62ab65160863cb8b1bd55a2653402fe4, I expect spacing to work well in all cases.

Thanks.

**Comment by agnivade** [comment]
Did some testing on several pages, with both Chrome and FF. Didn't see any issues. Will send the CL.
