### ISSUE TITLE
encoding/xml: documentation for xml start & end elements is redundant

### ISSUE THREAD

**Issue by isomorphisms** [golang/go#29566]
The documentation for encodings/xml/xml.go is repetitive and not helpful. "End returns an EndElement". "EndElement is an EndElement".   So, what is an XML end element?

**Comment by katiehockman** [comment]
@isomorphisms The godoc for [EndElement](https://godoc.org/encoding/xml#EndElement) is "An EndElement represents an XML end element." XML elements are not specific to Go or the encoding/xml package.

For questions about Go, see https://golang.org/wiki/Questions.

I am going to close this issue for now, but please re-open if you don't feel like your issue has been addressed.

**Comment by isomorphisms** [comment]
@katiehockman Thanks Katie. I didn’t have time (nor authority) to change the `godoc` comment for the function. I think it should be improved. The existing docstring violates official recommended go practice (as stated in, iirc, the _Effective Go_ blog).
