### ISSUE TITLE
proposal: math/big: Int.TrailingZeroBits

### ISSUE THREAD

**Issue by TuomLarsen** [golang/go#29578]
Please consider exposing the `nat.trailingZeroBits` method, for example as `Int.TrailingZeroBits`, in addition to [Int.BitLen](https://golang.org/pkg/math/big/#Int.BitLen). Similar to `math.bits`, knowing the [length in bits](https://golang.org/pkg/math/bits/#Len) is as useful as counting number of [trailing zeros](https://golang.org/pkg/math/bits/#TrailingZeros).

**Comment by rsc** [comment]
Seems reasonable; @griesemer agrees.

**Comment by TuomLarsen** [comment]
Thank you!
