### ISSUE TITLE
x/sys/plan9: modify mkall.sh to support amd64,arm zsyscall*.go files generation

### ISSUE THREAD

**Issue by viswesr** [golang/go#29586]
sys/plan9/mkall.sh is out of date. Modify mkall.sh to support generation of zsyscall_plan9_{amd64,arm}.go files. 

I will be implementing the CL related to this issue.

**Comment by julieqiu** [comment]
@viswesr would you be able to provide information on the status of this issue?

**Comment by viswesr** [comment]
@julieqiu I have created  CL https://golang.org/cl/179041 for this issue. Thanks.

@gopherbot remove WaitingForInfo

**Comment by julieqiu** [comment]
thanks for the update!
