### ISSUE TITLE
Question: any future plans to support numeric suffix for short variable declaration?

### ISSUE THREAD

**Issue by stefanos82** [golang/go#29588]
There are times when people need to initialize a variable with a different numeric type than the default one.

For instance, `myval := 1` defaults to type `int` whereas I could possibly want to default to `unsigned 64-bit integer`.

Would it be possible to use something like the following in the future? `myval := 1u64`

Thank you.

**Comment by dominikh** [comment]
What is the advantage of `1u64` over `uint64(1)`?

**Comment by stefanos82** [comment]
Isn't `uint64()` a type cast in the aforementioned example?

**Comment by dominikh** [comment]
Yes. It still has the same effect; `myval := uint64(1)` declares a variable `myval` of type `uint64` and assigns `1` to it.

**Comment by stefanos82** [comment]
Yeah, but wouldn't make sense the compiler infer `myval := 1u64` to something like `var myval uint64 = 1`? It would be a nice thing to have in my opinion.

Yes, I could go with your suggestion, but it's a type cast and not a direct variable declaration. I know it's a minor thing, but...I'm sure others would find something like that quite handy.

I'm not demanding it, I'm just asking whether it's possible to have such useful feature.

If not, then I would use the rest of available options.

**Comment by dominikh** [comment]
You're proposing a purely syntactic change. Both uint64(1) and 1u64 would denote a constant 1 of type uint64. As such, no, it is not likely that a different way of expressing the same thing will be added.

**Comment by stefanos82** [comment]
Thank you very much @dominikh, it's good to know.

Cheers.
