### ISSUE TITLE
x/sys/unix: SYS_IOCTL not defined on Solaris

### ISSUE THREAD

**Issue by dewi-ny-je** [golang/go#29581]
As written in https://github.com/golang/go/issues/11113#issuecomment-131196564 zsysnum_solaris_amd64.go lacks

`SYS_IOCTL          = 54`

and I get a compilation error when calling on Solaris

`unix.SYS_IOCTL`

**Comment by ianlancetaylor** [comment]
In fact none of the system call numbers are currently defined on Solaris.

**Comment by bradfitz** [comment]
System calls are not considered stable ABI on Solaris, so lack of SYS_* constants seems fine.

@dewi-ny-je, what's the real problem, though? SYS_IOCTL not existing is preventing you from doing something else, presumably. What are you trying to compile or do?

**Comment by AttilaFueloep** [comment]
Most probably he refers to what is beeing discussed in https://github.com/Bowery/prompt#8 .

@dewi-ny-je Basicaly on Solaris you have to use `unix.Ioctl{Get,Set}Termios()` and `unix.IoctlGetWinsize()`, not `unix.Syscall()`. So `unix.SYS_IOCT` isn't needed.

**Comment by bradfitz** [comment]
So, nothing to do here then, right?

**Comment by AttilaFueloep** [comment]
Can't speak for @dewi-ny-je , but I think it can be closed.
