### ISSUE TITLE
go/format: Source mishandles parens on malformed input

### ISSUE THREAD

**Issue by josharian** [golang/go#29593]
Found by go-fuzz, unlikely to occur in real code. Very low priority.

```go
func main() {
	in := []byte("g(func()())")
	out, err := format.Source(in)
	if err != nil {
		panic(err)
	}
	fmt.Printf("in : %q\nout: %q\n", in, out)
	return
}
```

Result:

```
in : "g(func()())"
out: "g(func())"
```

Observe the dropped parens pair.

If input is `"g(func()()())"` instead (extra parens pair), the result instead has misplaced parens:

```
in : "g(func()()())"
out: "g((func())())"
```

**Comment by bcmills** [comment]
Compare https://play.golang.org/p/jmef0XQwDn3.

The error in the example source is that the function passed to `g` is missing its FunctionBody, but other than that it seems that `go/format` is correctly parsing `func()()` as the type of a function with empty Parameters and an empty (but parenthesized) Result.

For `g(func()()())`, the initial `func()()` is similarly parsed as a bodiless function, and the parentheses are added to invoke that function with empty Arguments.

**Comment by josharian** [comment]
Thanks, Bryan. Given that observation I’m going to call this one not worth investigating and close it.
