### ISSUE TITLE
cmd/go: after installing via MSI installer, prompt says "go is not a recognized command" #18680

### ISSUE THREAD

**Issue by laurent999** [golang/go#29592]
I had the same issue as the issue # 18680 I noticed that it was solved nl part and was closed. finally i noticed that it is my antivirus that detected go.exe as a torjan and quarantined it. So please first check if it is not your antivirus that prevents the normal execution of go

**Comment by agnivade** [comment]
Your sentence is in the past tense. Could you clarify if it is still an issue for you ?

> So please first check if it is not your antivirus that prevents the normal execution of go

Who is this for ? The Go team or users ?

If you are facing this issue, then please fill the entire issue template.

**Comment by laurent999** [comment]
it's just information for go users. I fixed my problem.
