### ISSUE TITLE
net/url: add URL.ForceFragment like ForceQuery for empty fragments to stringify with '#'

### ISSUE THREAD

**Issue by Gregable** [golang/go#29603]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64
</pre>

### What did you do?

```go
import (
  "fmt"
  "log"
  "net/url"
)

func main() {
    u, err := url.Parse("http://example.com/#")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(u.String())
    fmt.Println(u.Fragment)
}
```

### What did you expect to see?

```
http://example.com/#
#
```

### What did you see instead?

```
http://example.com/

```

### What's the issue?

At first glance, `http://example.com/#` and `http://example.com/` are logically the same URL. This is largely true in the context of a browser navigating to that URL as typed into the URL bar, but they are subtly different in a link. If a user clicks the following link:

```html
<a href="http://example.com/#">foo</a>
```

If the document URL (or `<base href>`) is `http://example.com/` then this click does not cause a navigation - it is a within document link. However, if the link was instead to:

```html
<a href="http://example.com/">foo</a>
```
Then clicking it causes a navigation. A reload really, but still a navigation.

This becomes more of an issue when net/url is used to resolve a relative URL:

```html
<html>
<head>
  <base href="http://example.com/">
</head>
<body>
  <a href="/">reload</a>
  <a href="#">inert</a>
</body>
</html>
```
```go
base, _ = url.Parse("http://example.com/")
nav, _ = base.Parse("/")
local, _ = base.Parse("#")
```

`nav` and `local` are now equal, which means it's not possible to distinguish a document local link and a navigation link.

**Comment by bradfitz** [comment]
In your "What did you expect to see?" section, you expected the value of `u.Fragment` to be `#` but it's documented as:

https://golang.org/pkg/net/url/#URL.Fragment
```go
        Fragment   string    // fragment for references, without '#'
```

So clearly that can't work as you expect.

What we could do perhaps is add `URL.ForceFragment` like we did for https://golang.org/pkg/net/url/#URL.ForceQuery

**Comment by Gregable** [comment]
Right. "What did you expect to see?" is perhaps the wrong phrasing of the question. I'm mostly arguing that the API has no way to distinguish these two cases.

It does look like ForceFragment would be the best API for fixing this.

**Comment by Gregable** [comment]
@bradfitz so he sees my reply.

**Comment by bradfitz** [comment]
I see all replies and saw yours last week. I just had nothing further to add.

We're in the Go 1.12 release freeze right now (https://github.com/golang/go/wiki/Go-Release-Cycle) so this isn't a priority.

**Comment by Gregable** [comment]
No worries, just wanted to check. Cheers.

**Comment by seankhliao** [comment]
seems like nobody else needs this
