### ISSUE TITLE
Unexpected overwrite when appending to the same slice multiple times

### ISSUE THREAD

**Issue by dkrisa** [golang/go#29609]
### What version of Go are you using (`go version`)?

<pre>
go 1.11.1

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
the go playground

### What did you do?

https://play.golang.org/p/3Qa1p552oP-

### What did you expect to see?

In the stdout, I expected to see
Before append, sums[4] is: [[2 2]]
After append, sums[4] is: [[2 2]]

### What did you see instead?
I saw
Before append, sums[4] is: [[2 2]]
After append, sums[4] is: [[2 3]]

As the code is running, it sets the following:
sums[0] = [[]]
sums[2] = append(sums[2], append(sums[0][0], 2)) = [[2]]
sums[3] = append(sums[3], append(sums[0][0], 3)) = [[3]]
sums[4] = append(sums[4], append(sums[2][0], 2)) = [[2,2]]
sums[5] = append(sums[5], append(sums[2][0], 3)) = [[2,3]]   <-- sums[4] is overwritten to [[2,3]]

When it sets sums[5] to [[2, 3]], it simultaneously overwrites sums[4].  I put an if statement at line 21 to verify that the append statement is causing the overwrite.  Go does not seem to realize that that memory is still being referenced in the program.

**Comment by ianlancetaylor** [comment]
That is how appending slices works.  See https://blog.golang/org/slices.
