### ISSUE TITLE
DisableCompression=true not work, the request header still has Accept-Encoding: gzip

### ISSUE THREAD

**Issue by andymacau853** [golang/go#29607]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Project\Go\maas
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=
0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build757481154=/tmp/go-
build -gno-record-gcc-switches
</pre></details>

### What did you do?
I have set DisableCompression=true but not work, the request header still has added Accept-Encoding: gzip, bug??
###
res, err := (&http.Client{
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, netw, addr string) (net.Conn, error) {
				conn, err := net.DialTimeout(netw, addr, time.Duration(job[taskID].HttpConnectTimeout)*time.Millisecond)
				if err != nil {
					return nil, err
				}
				err = conn.SetReadDeadline(time.Now().Add(time.Duration(job[taskID].HttpReadTimeout) * time.Millisecond))
				if err != nil {
					return nil, err
				}
				err = conn.SetWriteDeadline(time.Now().Add(time.Duration(job[taskID].HttpWriteTimeout) * time.Millisecond))
				if err != nil {
					return nil, err
				}
				return conn, nil
			},
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: job[taskID].HttpInsecureSkipVerify,
			},
			DisableCompression: true,
		},
	}).Do(req)
###

### What did you expect to see?
No auto added Accept-Encoding: gzip, then the server will response no gzip content:
GET / HTTP/1.1
Host: www.jobs.af
User-Agent: Go-http-client/1.1

### What did you see instead?
Auto added Accept-Encoding: gzip, it seems that DisableCompression not work.
GET / HTTP/1.1
Host: www.jobs.af
User-Agent: Go-http-client/1.1
**Accept-Encoding: gzip**

**Comment by agnivade** [comment]
Hi @andymacau853- Kindly show us a working code sample which shows this issue. Thanks.

**Comment by agnivade** [comment]
I am unable to reproduce this - 

```go
package main

import (
	"context"
	"io"
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"net/http/httputil"
	"time"
)

func main() {
	helloHandler := func(w http.ResponseWriter, req *http.Request) {
		buf, err := httputil.DumpRequest(req, false)
		if err != nil {
			log.Println(err)
			return
		}
		log.Printf("%s", buf)
		io.WriteString(w, "Hello, world!\n")
	}

	http.HandleFunc("/hello", helloHandler)
	go func() {
		log.Fatal(http.ListenAndServe(":8080", nil))
	}()

	res, err := (&http.Client{
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, netw, addr string) (net.Conn, error) {
				conn, err := net.DialTimeout(netw, addr, time.Duration(1*time.Second))
				if err != nil {
					return nil, err
				}
				err = conn.SetReadDeadline(time.Now().Add(time.Duration(1 * time.Second)))
				if err != nil {
					return nil, err
				}
				err = conn.SetWriteDeadline(time.Now().Add(time.Duration(1 * time.Second)))
				if err != nil {
					return nil, err
				}
				return conn, nil
			},
			DisableCompression: true,
		},
	}).Get("http://localhost:8080/hello")
	if err != nil {
		log.Println(err)
		return
	}
	defer res.Body.Close()
	buf, err := ioutil.ReadAll(res.Body)
	if err != nil {
		log.Println(err)
		return
	}
	log.Printf("%s", buf)

	select {}
}
```

```
2019/01/09 14:59:07 GET /hello HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1

2019/01/09 14:59:07 Hello, world!
^Csignal: interrupt
```

Can you show us the `Request` that you are passing ?
