### ISSUE TITLE
Privacy problem with runtime.LockOSThread()

### ISSUE THREAD

**Issue by johnlarfour** [golang/go#29614]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### What did you do?
If you try to build this code https://play.golang.org/p/FQu_aK57BlS in machine A and execute in machine B, when spit out the error reveals the $HOME of machine A and the path where was build on machine A.
I think there is a privacy problem.

### What did you expect to see?
No privacy problem

### What did you see instead?
Privacy problem

**Comment by ianlancetaylor** [comment]
It really helps if you show us the exact output and explain how it differs from what you expect.

Based on your description, I think the problem may be that the Go tools record the location of the sources in the binary, and report it when generating a stack trace.  That is true.  You can use the compiler's `-trimpath` option to affect this.

Beyond that I think you may be discussing the issues discussed in #16860.

Based on that, closing this issue, but please comment if you disagree.
