### ISSUE TITLE
net: DNS default resolver vs custom resolver behaviors.

### ISSUE THREAD

**Issue by andymacau853** [golang/go#29621]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Project\Go\maas
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=
0 -fdebug-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build757481154=/tmp/go-
build -gno-record-gcc-switches
</pre></details>

### What did you do?
My current PC is not set any DNS server, because I need to test Go's custom resolver, now the code seems not work, the DNS server: 8.8.4.4 is not to use, why?
###
	r := &net.Resolver{
		PreferGo: true,
		Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
			d := net.Dialer{
				Timeout: time.Millisecond * time.Duration(10000),
			}
			return d.DialContext(ctx, "udp", "8.8.4.4:53")
		},
	}
    ip, err := r.LookupIPAddr(context.Background(), host)
###

### What did you expect to see?
The DNS query should use my custom resolver to get IP address, but it seems not work above code.

### What did you see instead?
the error message is "lookup www.xxxxxx.com: no such host"

**Comment by mikioh** [comment]
The docs on the net packages says:
```
On Windows, the resolver always uses C library functions, such as GetAddrInfo and DnsQuery.
```
See https://godoc.org/net. I think it's fine to change this issue to a proposal for enabling the built-in DNS stub resolver even on Windows, although, I'm not a Windows user and have no Windows stuff.

**Comment by andymacau853** [comment]
> The docs on the net packages says:
> 
> ```
> On Windows, the resolver always uses C library functions, such as GetAddrInfo and DnsQuery.
> ```
> See https://godoc.org/net. I think it's fine to change this issue to a proposal for enabling the built-in DNS stub resolver even on Windows, although, I'm not a Windows user and have no Windows stuff.

So do u mean, when i deploy to Linux platform, Is above code work?

**Comment by mikioh** [comment]
@andymacau853,

Please re-title this issue like "proposal: net: enable built-in DNS stub resolver on Windows" if you really want the functionality.
