### ISSUE TITLE
runtime: value copy issue

### ISSUE THREAD

**Issue by sunvim** [golang/go#29626]
### What version of Go are you using (`go version`)?

go 1.10.3  , go 1.10.4 , go 1.11

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

windows 10  x86_64

### What did you do?
package main

import "fmt"

type Person struct {
	Name string
	Age  int
}

func main() {
	m := make(map[string]Person, 2)
	m["1"] = Person{"n1", 11}
	m["2"] = Person{"n2", 12}
	for _, v := range m {
		go output(&v)
	}
	select {}
}

func output(v *Person) {
	fmt.Println(v)
}

### What did you expect to see?

&{n1,11}
&{n2,12}

### What did you see instead?

&{n2 12}
&{n2 12}

**Comment by agnivade** [comment]
Please see - https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

To fix it, use - 

`go func(v Person){output(&v)}(v)`

**Comment by sunvim** [comment]
> Please see - https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables
> 
> To fix it, use -
> 
> `go func(v Person){output(&v)}(v)`

yes, I know how to fix it.

but pass value by this way, the perfermance maybe a bit effect.
