### ISSUE TITLE
net/http/httputil: WebSocket requests do not use ModifyResponse in ReverseProxy

### ISSUE THREAD

**Issue by blixt** [golang/go#29627]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +5efe9a8f11 Wed Jan 9 07:21:16 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No, this is an issue for a merged but unreleased change.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

```go
rproxy := httputil.NewSingleHostReverseProxy(backURL)
rproxy.ModifyResponse = func(resp *http.Response) error {
	resp.Header.Set("X-Important-Header", "HelloWorld")
	return nil
}

req, _ := http.NewRequest("GET", frontendProxy.URL, nil)
req.Header.Set("Connection", "Upgrade")
req.Header.Set("Upgrade", "websocket")

c := frontendProxy.Client()
res, err := c.Do(req)

if res.Header.Get("X-Important-Header") != "HelloWorld" {
	t.Fatalf("missing/invalid custom header; got %#v", res.Header)
}
```

Full runnable test code: https://gist.github.com/blixt/48f4581437eab9863b977ca7dc3001af

### What did you expect to see?

The custom header.

### What did you see instead?

```
--- FAIL: TestReverseProxyWebSocketModifyResponse (0.00s)
    httputil_test.go:67: missing/invalid custom header; got http.Header{"Connection":[]string{"upgrade"}, "Upgrade":[]string{"WebSocket"}}
```

### Remarks

Obviously the `ModifyResponse` function cannot do anything with `Body` so the web socket path would ideally clear the `Body` field in the response, and make sure it's still `nil` after calling `ModifyResponse`.

**Comment by bradfitz** [comment]
Thanks! I'll send a fix for Go 1.12.

/cc @ianlancetaylor @dmitshur
