### ISSUE TITLE
cmd/go: missing result of ReadBuildInfo in init function

### ISSUE THREAD

**Issue by vearutop** [golang/go#29628]
### What version of Go are you using (`go version`)?

<pre>
$ go1.12beta1 version
go version go1.12beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.12beta1 env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/viacheslav.poturaev/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/viacheslav.poturaev/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/viacheslav.poturaev/sdk/go1.12beta1"
GOTMPDIR=""
GOTOOLDIR="/Users/viacheslav.poturaev/sdk/go1.12beta1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lb/j0gz8jln36z4frqkrzmkdb0c0000gp/T/go-build125908091=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I've tried to read build info in app retrieved with `go get`:
```
GO111MODULE=on go1.12beta1 get github.com/vearutop/go-versioning-example@v0.0.1
go: finding github.com/vearutop/go-versioning-example v0.0.1
go: finding go.uber.org/zap v1.3.0
go: finding go.uber.org/atomic v1.3.2
```
Then run `~/go/bin/go-versioning-example`.
Here is a package to reproduce: https://github.com/vearutop/go-versioning-example

`main` package has two files: `main.go` and `version.go`. `version.go` has `// +build go1.12` and `init` function that checks `ReadBuildInfo`.

### What did you expect to see?
```
...some deps info...
2019-01-09T12:06:27.232+0100    INFO    go-versioning-example@v0.0.1/main.go:9    App Version: v0.0.1
```

### What did you see instead?
```
build info not available
2019-01-09T12:06:27.232+0100    INFO    go-versioning-example@v0.0.1/main.go:9    App Version: dev
```

**Comment by vearutop** [comment]
If I change `init()` to `init2()` and call it explicitly from `main()` there is no issue.

**Comment by agnivade** [comment]
https://tip.golang.org/pkg/go/build/#hdr-Build_Constraints

> There are no build tags for beta or minor releases.

I think this is what you are experiencing.

**Comment by vearutop** [comment]
As mentioned in slack #modules this is likely due to `init` execution precedence: https://golang.org/src/cmd/go/internal/modload/build.go#L234.

I've [put](https://github.com/vearutop/go-versioning-example/blob/v0.0.2/version.go#L14) my `init` code in a goroutine and now it works.

```
rm -rf ~/go/bin/go-versioning-example && GO111MODULE=on go1.12beta1 get github.com/vearutop/go-versioning-example@v0.0.2 && ~/go/bin/go-versioning-example
Build info: &{Path:github.com/vearutop/go-versioning-example Main:{Path:github.com/vearutop/go-versioning-example Version:v0.0.2 Sum:h1:KbExDVzJ29tWjzdV3PNHOX6o3f0fR0tnDR1zKNQ+Byg= Replace:<nil>} Deps:[0xc0000f0000 0xc0000f0040]}
2019-01-09T12:58:45.135+0100	INFO	go-versioning-example@v0.0.2/main.go:9	App Version: dev
```
