### ISSUE TITLE
tools/go/packages: must go.sum exist?

### ISSUE THREAD

**Issue by sunliver** [golang/go#29635]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/sunliver/go/bin"
GOCACHE="/Users/sunliver/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sunliver/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sunliver/Documents/gomod-test/package/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/fxzm7n8s0497vkmvnj0qygkr0000gp/T/go-build304816994=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

make sure GO111MODULE=on

1. compile [x/tools/package_test](https://github.com/golang/tools/blob/release-branch.go1.11/go/packages/gopackages/main.go)
2. create a minimal mod package, change root dir to 555 ( rm write permission) and rm go.sum
**make sure your minimal package add at lease one third-party dependence**
3. try use package generated in step1 to visit imports

### What did you see instead?
`
gopackages: go [list -e -json -compiled -test=false -export=false -deps=true -find=false -- gopkg.in/yaml.v2]: exit status 1: go: writing go.sum: open /Users/sunliver/go/pkg/mod/gopkg.in/yaml.v2@v2.2.1/go.sum: permission denied
`

I find this behavior when I try to visit imports under mod cache, but the package only have `go.mod` but miss `go.sum`(eg. [yaml](https://github.com/go-yaml/yaml)).

Q: Currently, is `go.sum` necessary for `x/tools/go/packages` to work?

**Comment by bcmills** [comment]
`go list` should probably not fail if `go.sum` cannot be written. (See #29452.)
