### ISSUE TITLE
os: CL 156379 causes deadlocks on FreeBSD 10.3 builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#29633]
https://golang.org/cl/156379 (which updates #19093) seems to be causing consistent deadlocks in the FreeBSD 10.3 builders:
https://build.golang.org/log/6e053738a50b6d2783d82146712ea469501a63a3
https://build.golang.org/log/dd23083ba54882a43e2d70fcf984722df0191e61
https://build.golang.org/log/6117379f9204b491204d9412db024eb95847248f
https://build.golang.org/log/6087ce300fadc2b1461dffbbfb5171d70fad965f

It is not obvious to me whether this should block the 1.12 release: it seems the 10.3 builders are flaky in general (see #25289). If not, please, remove the release-blocker label.

CC @ianlancetaylor @paulzhol @tklauser

**Comment by ianlancetaylor** [comment]
According to the release notes Go 1.12 should still support FreeBSD 10, so perhaps https://golang.org/cl/156379 was overly optimistic.

**Comment by ianlancetaylor** [comment]
CL link doesn't work due to #28836, see https://go-review.googlesource.com/c/go/+/157099.
