### ISSUE TITLE
os: file operations flaky on dragonfly around CL 156365

### ISSUE THREAD

**Issue by bcmills** [golang/go#29634]
See attached screenshot. The failures seem to start at https://golang.org/cl/156365 (updates #17490), but the Dragonfly builder is a bit flaky so it's hard to say for sure (#25796, #29583).

I sampled some failures, but the only connection I can see is that they all involve file operations.

![jr3qskosgsc](https://user-images.githubusercontent.com/5200974/50910693-5299ac80-13fc-11e9-97b3-7e93571ce834.png)

CC @tklauser @ianlancetaylor @randall77

**Comment by bcmills** [comment]
Provisionally marking as release-blocker, but please remove if appropriate. (Dragonfly is not a first-class port, but it would still be pretty unpleasant to cut a release with a major regression.)

**Comment by tdfbsd** [comment]
I think it's just temporarily gone haywire. I'll fix i when I get a chance.

**Comment by tdfbsd** [comment]
It's OK now; you can close this.

**Comment by ianlancetaylor** [comment]
Thanks!
