### ISSUE TITLE
x/build: add at least one 32-bit longtest builder

### ISSUE THREAD

**Issue by ALTree** [golang/go#29641]
Currently, the only builder that runs ~every test is the `linux-amd64-longtest` builder. It's linux, and it's 64 bit.

There's already an issue for a different OS longtest builder (windows: #26529); but having a 32-bit longtest builder would also be useful. See for example #29555: the `archive/zip` test suite was broken on 32-bit archs and nobody noticed because the bad tests are skipped on short so currently they're not run on any builder.

Filing this as a remainder.

**Comment by bcmills** [comment]
CC @bradfitz @dmitshur
