### ISSUE TITLE
x/net/proxy.go:83: u.Hostname undefined (type *url.URL has no field or method Hostname)

### ISSUE THREAD

**Issue by luqmanhakimpens** [golang/go#29646]
### What version of Go are you using (`go version`)?

<pre>

$ go version
go version go1.7.4 linux/arm 

</pre>

### Does this issue reproduce with the latest release?
yes, i didn't see this issues with earlier version of "x/net/proxy"

### What operating system and processor architecture are you using (`go env`)?

i'm on raspberry-pi zero w

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go-dev"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build783267883=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

</pre></details>

### What did you do?

go get github.com/eclipse/paho.mqtt.golang
# golang.org/x/net/proxy
go-dev/src/golang.org/x/net/proxy/proxy.go:83: u.Hostname undefined (type *url.URL has no field or method Hostname)
go-dev/src/golang.org/x/net/proxy/proxy.go:84: u.Port undefined (type *url.URL has no field or method Port)

go get golang.org/x/net/proxy
# golang.org/x/net/proxy
../src/golang.org/x/net/proxy/proxy.go:83: u.Hostname undefined (type *url.URL has no field or method Hostname)
../src/golang.org/x/net/proxy/proxy.go:84: u.Port undefined (type *url.URL has no field or method Port)

**Comment by Gnouc** [comment]
`[*Url.Hostname()](https://golang.org/pkg/net/url/#URL.Hostname) is only available since go 1.8.

**Comment by mdlayher** [comment]
See above. Closing.

**Comment by luqmanhakimpens** [comment]
thank you, i will update my go version
