### ISSUE TITLE
cmd/go: go get path@version does not work

### ISSUE THREAD

**Issue by jadekler** [golang/go#29659]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/deklerk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/deklerk/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lk/zs4m7sv12mq2vzk_wfn2tfvm00h16k/T/go-build633732581=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
cd /tmp/whatever && unset GOPATH && go get cloud.google.com/go@v0.30.0
```

### What did you expect to see?

Get cloud.google.com/go@v0.30.0

### What did you see instead?

```
$ cd /tmp/whatever && unset GOPATH && go get cloud.google.com/go@v0.30.0
go: cannot use path@version syntax in GOPATH mode
```

**Comment by bcmills** [comment]
Dup of #24250: should work in go1.12beta1 if you set `GO111MODULE=on`.

(If you unset `GOPATH`, it defaults to '$HOME/go`.)

**Comment by jadekler** [comment]
Thanks!
