### ISSUE TITLE
cmd/go: go env should include GO111MODULE

### ISSUE THREAD

**Issue by xiaoxiaoyijian123456** [golang/go#29656]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12beta1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=F:\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\GOPATH
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=E:\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\GOPATH\src\github.com\go-steven\sanle\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\m1358\AppData\Local\Temp\go-build806091146=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I have already set the environment variable GO111MODULE to on, but there's no  GO111MODULE printed in `go env`.
 

### What did you expect to see?
go env should print GO111MODULE in Go1.11/1.12...

### What did you see instead?
No  GO111MODULE printed in `go env`.

**Comment by ALTree** [comment]
`GO111MODULE` is a temporary env variable that was introduced to help ensure a smooth transition to the module system. I believe we never bothered adding this kind of temporary env vars to `go env`.

**Comment by ALTree** [comment]
cc @bcmills for decision since you're asking for 1.12 which is almost done.

**Comment by bcmills** [comment]
Why do you need it from `go env` rather than calling `os.Getenv`?

It would make module-related issues a bit easier to report, but at this point that seems like relatively little gain, and the environment variable hopefully won't be around forever.

**Comment by xiaoxiaoyijian123456** [comment]
OK, it is just a little problem. Close it.

**Comment by shuLhan** [comment]
@bcmills , Ah ... I may have accidentally skip this when searching for issue. My bad.

If I can argue, even its temporary, there are quite long time range before GO111MODULE will be removed (unused).  The next release is still default to auto [1], and until Go 1.13 unsupported (two releases after that) there is about one and half years after that.

Since the change is not that big (one line) [2], maybe temporary adding it to `go env` give more clarity and benefit in issue reporting rather than not.

BTW, thank you for reviewing the CL.

[1] https://github.com/golang/go/issues/31857
[2] https://go-review.googlesource.com/c/go/+/176837

**Comment by bcmills** [comment]
CC @jayconrod

**Comment by jayconrod** [comment]
Why is `go env GO111MODULE` actually needed? If you need to check whether modules are enabled, `go env GOMOD` is a better way to do that.

**Comment by rsc** [comment]
Yes please, if only so it shows up in 'go bug' reports so we can better diagnose problems.
