### ISSUE TITLE
cmd/go: how can I build using -linkshared in a go modules project?

### ISSUE THREAD

**Issue by zylthinking** [golang/go#29651]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zylthinking/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zylthinking/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zylthinking/TSConsole/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build148896868=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

my project tree:
├── code
│   ├── main.go
│   └── sysapi
│       ├── bitmask.go
│       ├── syslog.go
│       └── task.go
├── go.mod
├── go.sum

and I wants to build sysapi into a shared kibrary because  init.so/ test.so depends on it
my step:

1. go install -buildmode=shared -linkshared  std
2. go install -buildmode=shared -linkshared 

### What did you expect to see?

build scuccess

### What did you see instead?
zylthinking@linux ~/TSConsole/code$ ls
main.go  sysapi

zylthinking@linux ~/code$ go build 
zylthinking@linux ~/TSConsole/code$ ls
code  main.go  sysapi

zylthinking@linux:~/TSConsole/code$ rm code

zylthinking@linux ~/code$ go build -buildmode=shared  
no packages to build
zylthinking@linux ~/TSConsole/code$ ls
main.go  sysapi

**Comment by ianlancetaylor** [comment]
As the documentation for `-buildmode=shared` says, "Packages named main are ignored."  That is because it doesn't make sense to build a main package into a shared library.

(You will likely get faster and better answers in a forum; see https://golang.org/wiki/Questions.)
