### ISSUE TITLE
net/http: using DumpResponse without requests

### ISSUE THREAD

**Issue by schmilmo** [golang/go#29658]
Hi,

I'm trying to build a HTTP sniffer.
I used http.ReadResponse as following
```b := bufio.NewReader(h)
res, err := http.ReadResponse(b, nil)
if err == io.EOF || err == io.ErrUnexpectedEOF {
	break
} else if err != nil {
	fmt.printf("HTTP Response error: %s \n", err)
	continue
}
body, err := ioutil.ReadAll(res.Body)
```
but some parts of the response are missing such as the delimiters
I would like to dump the raw response, is it possible to use httputil.DumpResponse?

Samuel

**Comment by bradfitz** [comment]
Nope, those aren't preserved. You'll need to do something lower-level with the net package directly if you need that.

**Comment by schmilmo** [comment]
So is there anyway to get the HTTP message total length when using ReadResponse?

**Comment by bradfitz** [comment]
There are various definitions for "total length". Which do you mean?

**Comment by schmilmo** [comment]
Sum of all TCP payloads that represent the current HTTP message

**Comment by bradfitz** [comment]
Nope, sorry. That isn't tracked. You might be able to recreate a close value, but optional whitespace and such is discarded.
