### ISSUE TITLE
website: /dl/ page shows go1.12beta2 under archived (in addition to under unstable)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29669]
If one visits https://golang.org/dl/, there are 3 sections of downloads:

- Stable versions - https://golang.org/dl/#stable
  - go1.11.4
  - go1.10.7
- Unstable version - https://golang.org/dl/#unstable
  - go1.12beta2
- Archived versions - https://golang.org/dl/#archive
  - Many outdated versions, but also go1.12beta2

As far as I can tell, this feels like a bug. go1.12beta2 shouldn't be listed under archived versions, since it's already listed in one of the other two sections.

Does anyone know what the intended behavior was meant to be? /cc @bradfitz @andybons @broady

**Comment by broady** [comment]
Yeah, no beta/rcs should be under archived, including current betas.
