### ISSUE TITLE
x/tools/go/packages: TestLoadImportsGraph is failing on s390x

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29660]
The `TestLoadImportsGraph` test is failing on s390x on latest x/tools commit (golang/tools@51295c7ec13a7e2fccbbf0c405b35d07ff136e75). It can be seen at https://build.golang.org.

It happens with Go on latest tip (44cf595a7efcd3d7048c745d1d1531696bcb5941), as well as with latest release-branch.go.1.11 (e39e43d7349555501080133bb426f1ead4b3ef97).

```
--- FAIL: TestLoadImportsGraph (1.49s)
    --- FAIL: TestLoadImportsGraph/GOPATH (0.61s)
        packages_test.go:191: golang.org/fake/subdir/d.test.Srcs = [4302876da86a8aae0c1669924daa223cafca60ef49ccaa060ae37e778d18f218-d], want [0.go]
    --- FAIL: TestLoadImportsGraph/Modules (0.89s)
        packages_test.go:191: golang.org/fake/subdir/d.test.Srcs = [4302876da86a8aae0c1669924daa223cafca60ef49ccaa060ae37e778d18f218-d], want [0.go]
FAIL
FAIL	golang.org/x/tools/go/packages	20.935s
```

See full log at https://build.golang.org/log/dae7ea9d26e4fe76c9ccd619842295c09ce5d6e7.

There's a very good chance this is the same issue as #29445 (/cc @mvdan), but this issue is specifically about the s390x failure, which we need to fix for #11811.

**Comment by matloob** [comment]
I'll wait to see if @mvdan's CL fixes this once it's submitted. If not, we'll have to debug it on a s390x machine. (I might get to "hack into a mainframe"!)

**Comment by dmitshur** [comment]
[CL 156977](https://golang.org/cl/156977) has fixed the issue for s390x as well. It must've been using a custom GOCACHE all along, before all the other environments started to as well.

Thank you @mvdan and @matloob!
