### ISSUE TITLE
cmd/go: make -mod=vendor a noop in GOPATH mode

### ISSUE THREAD

**Issue by kardianos** [golang/go#29665]
@bcmills 

Reproduces as of 2018-01-10 at HEAD.

In my build scripts I've added `-mod=vendor` for a project. This works great when outside of GOPATH. On a different computer that still has the source inside GOPATH, I get an error: 
`build flag -mod=vendor only valid when using modules`

This error seems like a mistake. I just want to tell `go` to use the vendor folder. If in GOPATH mode, it will already do that. But go mod mode currently requires a flag. Is there a situation where someone would pass in `-mod=vendor` while in GOPATH mode and it would do something unexpected?

This is a sub-issue of #27227, but perhaps it would be small and simple enough to make it in 1.12.

**Comment by cespare** [comment]
I ran into this as part of looking into https://github.com/golang/go/issues/27227#issuecomment-451617731. One thing I noticed is that if you specify this not via the flag but instead using `GOFLAGS=-mod=vendor`, then it works fine in GOPATH mode.

**Comment by bcmills** [comment]
Given that you can use `GOFLAGS` as a workaround — and given how far into the 1.12 freeze we are — I'd rather not add the `-mod` flag to `GOPATH` mode.

Sorry, but let's wait and address #27227 holistically.
