### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by steelx** [golang/go#29679]
Yes, Im using 64bit version of mingw `mingw-w64-install.exe`

### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ajink\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\ajink\Go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ajink\AppData\Local\Temp\go-build688448478=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
Installed mingw from http://mingw-w64.org/doku.php/download/mingw-builds

Im trying to run `robotgo` example code in go.

### What did you expect to see?

Mouse move

### What did you see instead?

```
go run main.go
# github.com/go-vgo/robotgo/vendor/github.com/robotn/gohook
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

**Comment by mvdan** [comment]
This error doesn't seem to come from Go itself. For example, see https://stackoverflow.com/questions/8861105/gcc-sorry-unimplemented-64-bit-mode-not-compiled-in.

**Comment by ianlancetaylor** [comment]
Closing because this is not a problem with Go and there is nothing we can change to fix it.

**Comment by phucle225** [comment]
![image](https://user-images.githubusercontent.com/31835504/54994046-e6d7e080-4ff5-11e9-84e8-8d4dc39e4dea.png)

**Comment by EgemenP** [comment]
@phucle225 thank you
