### ISSUE TITLE
json.NewDecoder decode `null XXXXX` bug?

### ISSUE THREAD

**Issue by childe** [golang/go#29672]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liujia/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/lib/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j9/37cyszz92cg1xkfc46cl5w5r0000gn/T/go-build837468198=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

func main() {
	s := `null abcdefg hijklml`
	rst := map[string]interface{}{"x": "y"}
	d := json.NewDecoder(strings.NewReader(s))
	err := d.Decode(&rst)
	fmt.Println(err)
	fmt.Println(rst)
}

```

### What did you expect to see?

invalid character 'a' after top-level value

### What did you see instead?

<nil>
map[]

**Comment by dominikh** [comment]
Decode decodes a single value in a stream of JSON-encoded values. `null` is a valid value, and it is correctly separated from the following garbage by whitespace. A second call to Decode would report an error.
