### ISSUE TITLE
proposal: encoding/json: add InputOffset to json decoder

### ISSUE THREAD

**Issue by sheerun** [golang/go#29688]
In similar spirit to https://github.com/golang/go/issues/8484

Use case: I'm trying to index entries in JSON file by their byte offset position to allow random access

I've already created PR with example implementation: https://github.com/golang/go/pull/29686

**Comment by rsc** [comment]
The justification in #8484 for encoding/xml seems just as compelling in encoding/json. Accepted.

(Note that we are in a release freeze and won't start reviewing new contributions until Go 1.13 work begins.)
