### ISSUE TITLE
database/sql: DB.Conn always returns a cached connection

### ISSUE THREAD

**Issue by boekkooi-fresh** [golang/go#29684]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/<>/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/go"
GOPROXY=""
GORACE=""
GOROOT="/home/<>/.goenv/versions/1.11.3"
GOTMPDIR=""
GOTOOLDIR="/home/<>/.goenv/versions/1.11.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build956395453=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When using `sql.DB.Conn()` a bad `sql.ErrBadConn` error was returned because the connections were terminated by the server (using `pg_terminate_backend` on postgres).
This by it self is not a bad thing but seems to not confirm with `sql.DB.ExecContext()` and `sql.DB.PingContext()` which actually kept working by opening a new connection.

While looking at the code I noticed that [sq.DB.ExecContext()](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1421-L1434) did `cachedOrNewConn` and then `alwaysNewConn` to ensure a new connection was available.
The code in [`sql.DB.Conn()`](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1694-L1702) seems to be doing a `cachedOrNewConn` and then `cachedOrNewConn` causing a cached/bad connection to be returned.

Probably this can be fixed by replacing [src/database/sql/sql.go line 1701](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1701): <pre>dc, err = db.conn(ctx, ~cachedOrNewConn~**alwaysNewConn**)" </pre>

### What did you expect to see?

I expected `sql.DB.Conn()` to use the cached connections and otherwise create a new one similar to the rest of the library.

### What did you see instead?

`sql.DB.Conn()` returned a cached/bad connection and did not try to create a new one.

**Comment by bradfitz** [comment]
@gopherbot, please cherry-pick to Go 1.11.

(Daniel, I assume this was a Go 1.11 regression from Go 1.10?)
