### ISSUE TITLE
cmd/doc: indents pre-formatted documentation in functions badly

### ISSUE THREAD

**Issue by segevfiner** [golang/go#29708]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=&lt;snip>\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=&lt;snip>\go
set GOPROXY=
set GORACE=
set GOROOT=&lt;snip>\go
set GOTMPDIR=
set GOTOOLDIR=&lt;snip>\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=&lt;snip>\AppData\Local\Temp\go-build819611282=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1. Save this file as `$GOPATH/hello/hello.go`:
```go
/*
Package hello prints "Hello, World!".

Usage

	hello.Hello()
*/
package hello

import "fmt"

// Hello prints "Hello, World!"
//
// Usage
//
//     hello.Hello()
func Hello() {
	fmt.Println("Hello, World!")
}
```

2. Run:
```cmd
C:\>go doc hello
package hello // import "hello"

Package hello prints "Hello, World!".

Usage

    hello.Hello()

func Hello()

C:\>go doc hello.Hello
func Hello()
    Hello prints "Hello, World!"

    Usage

    hello.Hello()
```

### What did you expect to see?
I expect the second command output to be:
```
C:\>go doc hello.Hello
func Hello()
    Hello prints "Hello, World!"

    Usage

        hello.Hello()
```

### What did you see instead?
The pre-formatted line is indented the same as a normal paragraph.

### Analysis
This is due to the `indent`/`preIndent` arguments used in [src/cmd/doc/pkg.go](https://github.com/golang/go/blob/master/src/cmd/doc/pkg.go)

Note that the signature is as follows:
```go
func ToText(w io.Writer, text string, indent, preIndent string, width int)
```

`indent` is before `preIndent`! it's possible it's mixed up a bit currently in the code, but still given the desired results. Note that editor extensions like `vscode-go` are already parsing the output of `go doc` depending on it's indentation behavior.

In function doc, which is already indented, `preIndent` should be indented with 8 spaces instead of 4 so that it stands out as expected.

**Comment by agnivade** [comment]
The behavior seems to have been always like this.

For package docs, the indent is `""` and preIndent is `indent`, which indents pre-formatted code. But for method docs, both indent and preIndent are `indent`. So everything is at the same level.

Seems to me an inconsistency we should fix. But I wonder if there is some historical reason for this. @robpike  ?
