### ISSUE TITLE
reflect: Value docs and Value.Set panic message are not perfect

### ISSUE THREAD

**Issue by go101** [golang/go#29701]
### What version of Go are you using (`go version`)?

go version go1.12beta2 linux/amd64

### What did you do?

```golang
package main

import "reflect"
import "fmt"

func main() {
	var z reflect.Value
	fmt.Println(z) // <invalid reflect.Value>
}
```

### What did you expect to see?

`<invalid value>` is better than `<invalid reflect.Value>`.

All `reflect.Value` values are valid. It is just that the values represented by some `reflect.Value` values are invalid.

**[update]: the intention of this issue has changed. Now it requests:**
1. correct the docs of `reflect.Value` to

> The zero Value represents no value. Its IsValid method returns false, its Kind method returns Invalid, its String method returns "&lt;invalid reflect.Value&gt;"

~~2. use a better panic message for invalid `reflect.Value.Set` argument~~ (Not right)

~~see https://github.com/golang/go/issues/29701#issuecomment-453731713 for details.~~

=======

~~The design for **the string representation of a valid `reflect.Value` which represents another `reflect.Value` value is like the form `[the-type-of-the-value-represented-by-the-Value-represented-by-the-Value Value]`** is a little weird, but it is not a big problem I think.~~ It is not weird when you get it.

**Comment by ianlancetaylor** [comment]
Making this change at this point is sure to break some existing tests, and the benefit seems quite small.

**Comment by go101** [comment]
It looks the docs of `reflect.Value` clearly states
> The zero Value represents no value. Its IsValid method returns false, its Kind method returns Invalid, its String method returns "&lt;invalid Value&gt;"

**Comment by go101** [comment]
Ah, in the last code example, the `v` and `z` really represent different values. The `v` is `reflect.Value` value which represents another reflect.Value` value.

However, I think the docs may really need to be corrected.

**Comment by go101** [comment]
I also think the string representation of `v` is wrong. It should be `<reflect.Value Value>`, same as the string representation of `y` in the following example:
```golang
package main

import "reflect"
import "fmt"

func main() {
	var z reflect.Value // a zero Value value
	var v = reflect.ValueOf(&z).Elem()
	fmt.Println(v) // <invalid Value>
	fmt.Println(z) // <invalid reflect.Value>
	fmt.Println(v.IsValid()) // false
	
	var y = reflect.ValueOf(&v).Elem()
	fmt.Println(y) // <reflect.Value Value>
}
```

**Comment by go101** [comment]
More:
```golang
package main

import "reflect"
import "fmt"

func main() {
	var z reflect.Value // a zero Value value
	var w = reflect.ValueOf(&z)
	
	var y = reflect.ValueOf(&w).Elem()
	fmt.Println(y.Kind()) // struct
	
	var v = w.Elem()
	fmt.Println(v.Kind()) // struct
	fmt.Println(v) // <invalid Value>
	
	// The two lines should be both panic or both not.
	v.Set(v) // ok
	v.Set(z) // panic: reflect: call of reflect.Value.Set on zero Value
}
```

**Comment by go101** [comment]
Sorry, updated my last two comments.

**Comment by go101** [comment]
closed for some misunderstanding on printing `reflect.Value` values.
