### ISSUE TITLE
cmd/go, cmd/link: support -buildmode=shared on FreeBSD

### ISSUE THREAD

**Issue by kolbycrouch** [golang/go#29715]
Hello. I noticed recently when trying to build a shared copy of std, that cmd/go and cmd/link don't support shared linking on FreeBSD for any architecture.

After simply adding FreeBSD/amd64 to the case in cmd/go/internal/work/init.go and adding a case for FreeBSD in cmd/link/internal/ld/config.go, I was able to get a libstd.so and link a hello world program dynamically. The hello world program worked as well.

I was wondering if there was some known issue with dynamic linking on FreeBSD, or if it was simply overlooked.

**Comment by ianlancetaylor** [comment]
It was most likely simply untested.  Want to send a patch?
