### ISSUE TITLE
question: how to get go code from .aar file

### ISSUE THREAD

**Issue by tonifirnandes** [golang/go#29718]
Dear team,

I have built .aar file from gomobile by command such as = ... gomobile bind -x -v -target=android successfully, thanks for this great tool ...

Then i wanna update my .aar / Go code. Unfortunately, i miss the source code file. Is there anyway, i can extract/get my Go code back again form my .aar file ?.

I have tried to decompile the file by extract .aar and decompiled file classes.jar via jd-gui but i only got unnecessary java file which not my real Go code.

<img width="153" alt="screenshot 2019-01-13 at 18 24 13" src="https://user-images.githubusercontent.com/3122029/51084688-d5a26600-1760-11e9-8b68-8cb47b2371ca.png">

Thanks.

**Comment by upperwal** [comment]
If by "miss the source code file" you meant that you lost it then unfortunately you can't get it back. Your code is compiled and packed into somethinglib.so file which is a shared object file. At best you can get back the assembly code by using some disassembler. What you see here is the JNI binding, some of it generated for GO and the rest for your code.

**Comment by julieqiu** [comment]
A better place to ask this kind of question is golang-nuts. See https://golang.org/wiki/Questions.
