### ISSUE TITLE
text/scanner: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by en-vee** [golang/go#29723]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\neeraj.vaidya\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\neeraj.vaidya\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\NEERAJ~1.VAI\AppData\Local\Temp\go-build083329666=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
- I am using the text/scanner package to tokenize a UTF-8 encoded text file.
- The text file (say `input.conf`) contains the following
```shell
propertyKey1 = "unTerminatedValue
propertyKey2 = "validValue"
```
- In order to trap the error arising from the unterminated string literal, I create an error Handler function and set it into the scan.Error field 
- But when I call scan.TokenText() method to get the most recently scanned Rune, inside the error handler, I get slice index out of bounds panic/error when attempting this on the unterminated string literal.
- Upon debugging, I can see that the scan.TokenText() method tries to return a slice from a byte array 
```
// text/scanner/scanner.go
func (s *Scanner) TokenText() string {
...
...
if s.tokBuf.Len() == 0 {
		// common case: the entire token text is still in srcBuf
		return string(s.srcBuf[s.tokPos:s.tokEnd])
	}
```
- And the value of s.tokPos is greater-than s.tokEnd.
- This probably causes the "index out of bounds" error.

Go PlayGround Link : https://play.golang.org/p/uIUPfT0L2Dx

### What did you expect to see?
I expected that the scan.TokenText() method inside the error handler would return the last scanned token which is the unterminated literal. 

### What did you see instead?
I saw a panic message saying "slice bounds out of range"

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
text/scanner.(*Scanner).TokenText(0x452000, 0x41c660, 0xa89e0, 0x1007)
	/usr/local/go/src/text/scanner/scanner.go:678 +0x260
main.main.func1(0x452000, 0x102196, 0x16, 0x0)
	/tmp/sandbox248235930/main.go:17 +0x40
text/scanner.(*Scanner).error(0x452000, 0x102196, 0x16, 0x1007)
	/usr/local/go/src/text/scanner/scanner.go:327 +0x280
text/scanner.(*Scanner).scanString(0x452000, 0x22, 0x0, 0xef180)
	/usr/local/go/src/text/scanner/scanner.go:476 +0xe0
text/scanner.(*Scanner).Scan(0x452000, 0x13, 0x41c7a8, 0x1)
	/usr/local/go/src/text/scanner/scanner.go:593 +0x440
main.main()
	/tmp/sandbox248235930/main.go:20 +0x280
```

**Comment by Gnouc** [comment]
The document said `s.TokenText()` only valid after calling `s.Scan()`. At the time `s.Error` is called, `s.Scan()` was not finished, so `s.TokenText()` is not valid.
