### ISSUE TITLE
go/doc: doc package converts smart quotes in preformatted blocks

### ISSUE THREAD

**Issue by segevfiner** [golang/go#29730]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +7cbfa55b5d Sat Jan 12 00:27:48 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Git master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="&ltsnip>/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="&ltsnip>/go"
GOPROXY=""
GORACE=""
GOROOT="&ltsnip>/prj/go"
GOTMPDIR=""
GOTOOLDIR="&ltsnip>/prj/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build019133103=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. Save as `smartquotes.go`
```go
package godoctest

// Bar does ``stuff''
//
//     Bar(`` + '')
func Bar(s string) {

}
```
2. Run `go doc Bar` in that package directory.

### What did you expect to see?
```sh
➜ ~/prj/go/bin/go doc Bar
func Bar(s string)
    Bar does “stuff”

    Bar(`` + '')


```

### What did you see instead?
```sh
➜ ~/prj/go/bin/go doc Bar
func Bar(s string)
    Bar does “stuff”

    Bar(“ + ”)


```

The preformatted block has smart quotes converted. 

### Analysis
Smart quotes are converted here: https://github.com/golang/go/blob/4e8aaf6b22557a485cd3af874bf5be2722b07835/src/go/doc/comment.go#L448

But it's explicitly not done in HTML output here: https://github.com/golang/go/blob/4e8aaf6b22557a485cd3af874bf5be2722b07835/src/go/doc/comment.go#L332
By the final `false` argument. So it probably shouldn't be done for the text format too.

**Comment by griesemer** [comment]
I haven't investigated in detail but probably happens in go/doc/comment.go somewhere. This sounds like a good starter problem for somebody to fix.

**Comment by agnivade** [comment]
I made the convertQuotes change, which converts these special quotes to unicode quotes. But we were never checking for preformatted blocks.

For 1.11, it will be - 

```
func Bar(s string)
    Bar does ``stuff''

    Bar(`` + '')
```

For 1.12, it will be - 

```
func Bar(s string)
    Bar does “stuff”

    Bar(” + ”)
```

@griesemer - Are you fine with ignoring these conversions in preformatted blocks ?

**Comment by griesemer** [comment]
@agnivade It makes sense to leave preformatted blocks alone, but I don't have the full picture in my head at the moment. Probably worthwhile making sure we have a plan that doesn't require this changing back and forth in each release.

**Comment by segevfiner** [comment]
Note that the code already *doesn't* convert quotes in the HTML output.
