### ISSUE TITLE
question: net/http: how do I set a timeout for ReadResponse

### ISSUE THREAD

**Issue by schmilmo** [golang/go#29749]
Hi,

I'm using http.ReadResponse for a HTTP sniffer I'm building.
Is there anyway to set a timeout for the like the one set for client.Get()?

Samuel

**Comment by andybons** [comment]
It's hard to answer without seeing code, but you can set various deadlines on a `net.Conn` if you're using one to construct the `bufio.Reader` passed to `ReadResponse`. See https://golang.org/pkg/net/#Conn for more info.

Are you able to share code?
