### ISSUE TITLE
x/tools/cmd/godoc: search bar is visible without -index option

### ISSUE THREAD

**Issue by nhooyr** [golang/go#29741]
See https://github.com/golang/tools/blob/bf090417da8b6150dcfe96795325f5aa78fff718/cmd/godoc/doc.go#L26

Running latest godoc without -index shows:

<img width="1850" alt="screen shot 2019-01-14 at 10 19 02 pm" src="https://user-images.githubusercontent.com/10180857/51156607-66a13c00-184a-11e9-823e-cd39def8aa85.png">

**Comment by seankhliao** [comment]
no longer relevant.
