### ISSUE TITLE
cmd/cgo: syntax error: unexpected semicolon, expecting expression

### ISSUE THREAD

**Issue by calmh** [golang/go#29748]
### What version of Go are you using (`go version`)?

<pre>
$ go1.12beta2 version
go version go1.12beta2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.12beta2 env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jb/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jb/go"
GOPROXY="https://build.kastelo.net/athens"
GORACE=""
GOROOT="/Users/jb/sdk/go1.12beta2"
GOTMPDIR=""
GOTOOLDIR="/Users/jb/sdk/go1.12beta2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0r/vt88n3bd6cz3b7pz29x09pd40000gp/T/go-build241446681=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ go1.12beta2 get github.com/syncthing/notify
# github.com/syncthing/notify
src/github.com/syncthing/notify/watcher_fsevents_cgo.go:51:83: syntax error: unexpected semicolon, expecting expression
```

It builds with Go 1.11.4. The repo doesn't change often, but in case it does, at the time of reporting HEAD is https://github.com/syncthing/notify/commit/4e389ea6c0d84e6195eb585ffaf62c8c143306ae.

`watcher_fsevents_cgo.go:51:83` is the cursor position in the following screenshot. I'm not sure it's pointing at the right place...

<img width="768" alt="screen shot 2019-01-15 at 10 00 59" src="https://user-images.githubusercontent.com/125426/51169589-91bc7780-18ac-11e9-87d8-cde530999b39.png">

There is cgo involved, obviously, with includes and stuff on the `import "C"`...

**Comment by mvdan** [comment]
Potentially a regression, so I'm adding this to the 1.12 milestone. Thanks for reporting.

**Comment by ianlancetaylor** [comment]
Reproduction:

```Go
package p

// typedef struct { char **p; } S;
// static int f(S *p) { return 0; }
import "C"

var V = C.f(&C.S{
	nil,
})
```
