### ISSUE TITLE
cmd/go: load packages in parallel

### ISSUE THREAD

**Issue by jayconrod** [golang/go#29758]
Currently, when the Go command loads a set of packages and their dependencies, it does so on a single goroutine. Tracing shows that most cores are idle when loading packages for a large build, so there's significant performance opportunity here. On the one core that's busy, most of the time is spent in `internal/load.LoadImport` and `internal/load.Package.load` (which are mutually recursive).

One may expect the package loading process to be dominated by I/O, but the files loaded are usually in the kernel file cache, and we do a lot of work in userspace to parse files, extract imports, and apply build constraints. We actually spend very little time in the kernel, at least on Linux (system call overhead is very low).

Based on this information, it seems that we can significantly speed up the package loading process by parallelizing it. This will benefit `go list` in particular, which is heavily used by `golang.org/x/tools/go/packages`. `go build` and other commands may see some improvement, too.

**Comment by jayconrod** [comment]
cc @bcmills

**Comment by myitcv** [comment]
Also just to note https://go-review.googlesource.com/c/tools/+/158097. Chatting with @heschik, ideally `go list -find` would be made sufficiently fast to not require dropping down to `go list -m` and re-building package discovery logic atop that. 

So hopefully this change will go a good step towards that goal.
