### ISSUE TITLE
x/tools/internal/lsp: incorrect completions in global scope

### ISSUE THREAD

**Issue by anjmao** [golang/go#29754]
Currently completion inside global scope returns all universe types and in most cases completions are incorrect. Few examples:

1. 
```go
func  main() {
    fmt.<> // this is ok, suggests all types on fmt package
}

fmt.<> // suggests append, bool, byte etc.
```

2. 
```go
fm<> // suggests make, delete
mak<> // no suggests, but should suggest make?
```

3.

```go
cp<> // suggests panic
panic<> // suggests append, but should suggest panic
```

/cc @stamblerre

**Comment by stamblerre** [comment]
I think this is working as intended, because those are invalid statements on the package level.
If you try writing something like `var x string = fm<>` you would get completions as expected.
