### ISSUE TITLE
database/sql: closing connection due to driver.ErrBadConn hangs (locked)

### ISSUE THREAD

**Issue by mtojek** [golang/go#29765]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
with go1.11.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mtojek/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mtojek/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5l/8vb1435x3t90flqq1tsr_qwrpd3dc4/T/go-build439691674=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

See implementation here: https://github.com/mtojek/go-sqlmock-errbadconn/blob/master/err_bad_conn_test.go

I tried to return driver.ErrBadConn while the INSERT was executed. For ease of testing I used https://github.com/DATA-DOG/go-sqlmock .

### What did you expect to see?

Test case passing.

### What did you see instead?

Test case hanging.

**Comment by mtojek** [comment]
/cc @kardianos 

It looks familiar to the issue reported recently: https://github.com/golang/go/issues/29483

**Comment by kardianos** [comment]
Can you reproduce without SQL mock?

**Comment by mtojek** [comment]
I tried with **go-sql-driver/mysql** (shutdown MySQL server), but it fails with:

[mysql] 2019/01/26 21:43:22 packets.go:36: unexpected EOF

**Comment by mtojek** [comment]
@kardianos 
Don't you think it might be a similar issue to the one I linked above? Just curious...
