### ISSUE TITLE
cmd/go: `go list -m <name>/vN@latest` doesn't error when the vN version doesn't exist

### ISSUE THREAD

**Issue by hyangah** [golang/go#29762]
<pre>
$ GO111MODULE=on GOPATH=$(mktemp -d) go list -json -m golang.org/x/text/v4@latest
go: finding golang.org/x/text/v4 latest
{
	"Path": "golang.org/x/text/v4",
	"Version": "v4.0.0-20181227161524-e6919f6577db",
	"Time": "2018-12-27T16:15:24Z"
}
</pre>

golang.org/x/text/v4 does not exist yet, but `go list` makes up a pseudo-version based on the latest commit in the repo without an error.

Without the `@latest` suffix, go list reports an error, but not because the module is invalid.

<pre>
$ GOPATH=$(mktemp -d) go list -json -m golang.org/x/text/v4
go list -m golang.org/x/text/v4: module "golang.org/x/text/v4" is not a known dependency
</pre>

<pre>
$ go version
go version devel +5fae09b738 Tue Jan 15 23:30:58 2019 +0000 darwin/amd64
</pre>

**Comment by bcmills** [comment]
At head this given a `no matching versions` error. Is that good enough?

```
example.com$ gotip mod init example.com
go: creating new go.mod: module example.com

example.com$ gotip version
go version devel +39d41787 Wed Jul 31 05:45:43 2019 +0000 linux/amd64

example.com$ gotip list -json -m golang.org/x/text/v4@latest
go: finding golang.org/x/text/v4 latest
go list -m golang.org/x/text/v4: no matching versions for query "latest"

example.com$ GOPROXY=direct gotip list -json -m golang.org/x/text/v4@latest
go: finding golang.org/x/text/v4 latest
go list -m golang.org/x/text/v4: no matching versions for query "latest"

example.com$
```

CC @jayconrod
