### ISSUE TITLE
x/net: Can't install golang.org/x/net/publicsuffix

### ISSUE THREAD

**Issue by sb10** [golang/go#29771]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/nfs/users/nfs_s/sb10/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/nfs/users/nfs_s/sb10/go"
GOPROXY=""
GORACE=""
GOROOT="/software/vertres/installs/go"
GOTMPDIR=""
GOTOOLDIR="/software/vertres/installs/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/nfs/users/nfs_s/sb10/src/go/github.com/VertebrateResequencing/wr/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build435748798=/tmp/go-build"
</pre></details>

### What did you do?

```
$ mkdir -p /tmp/scratchpad/publicsuffix-test
$ cd /tmp/scratchpad/publicsuffix-test
$ go mod init example.com/test
$ go get golang.org/x/net/publicsuffix
```

### What did you expect to see?

No error.

### What did you see instead?

```
go: finding golang.org/x/net/publicsuffix latest
go: finding golang.org/x/net latest
go get golang.org/x/net/publicsuffix: no matching versions for query "latest"
```

**Comment by mvdan** [comment]
This succeeds for me on `go version go1.11.4 linux/amd64`. I'd suggest running `go clean -modcache` and trying again, in case you have a corrupted module cache.

**Comment by sb10** [comment]
Thanks, that fixed it. Maybe this issue could be changed to be about better error messaging for corrupt module caches? Anyway, I'll just close it for now.

**Comment by mvdan** [comment]
cc @bcmills, in case he thinks `cmd/go` could do a better job with corrupt module caches.

**Comment by bcmills** [comment]
Our first line of defense against corrupt caches is `go.sum` (and `go mod verify`). Beyond that 1.12 should be a lot less likely to corrupt the cache in the first place.

**Comment by sb10** [comment]
@bcmills I see. Unfortunately, this is a case where this is no go.sum (a new package, or an old one being converted to a module for the first time).

**Comment by bcmills** [comment]
#28802 or #24117 would mitigate that use-case more directly, but still wouldn't help if the module cache itself is corrupted.
