### ISSUE TITLE
crypto/aes: documentation missing

### ISSUE THREAD

**Issue by marigonzes** [golang/go#29787]
### What did you do?
Hi there.
When I accessed the [documentation](https://golang.org/pkg/crypto/aes/) for the crypto/aes package, I expected to see all the exported functions there.
Instead, only NewCipher and the type KeySizeError are present.

### What did you expect to see?
I expected to see all the exported functions in the documentation.

### What did you see instead?
Only NewCipher and the type KeySizeError are shown.

**Comment by agnivade** [comment]
Can you please mention which exported functions are missing ?

**Comment by marigonzes** [comment]
The functions I think are lacking documentation are BlockSize, Encrypt and Decrypt.

**Comment by agnivade** [comment]
I see BlockSize - https://golang.org/pkg/crypto/aes/#pkg-constants.

I don't see any Encrypt and Decrypt functions in the documentation. Even with `m=all` enabled. - https://golang.org/pkg/crypto/aes/?m=all

**Comment by marigonzes** [comment]
Regarding BlockSize, what I meant was the function `func (c *aesCipher) BlockSize() int`, not the equally-named constant.

**Comment by agnivade** [comment]
That is not an exported function. The type `aesCipher` is private. To see all methods, please pass the `m=all` query parameter as shown above. To see more documentation on the `m` variable, please see - https://godoc.org/golang.org/x/tools/cmd/godoc.

Closing as there is no bug here.
