### ISSUE TITLE
net/http/httputil: DumpRequest not showing the body

### ISSUE THREAD

**Issue by hbakhtiyor** [golang/go#29792]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yeah

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bakhtiyor/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/development/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build031651984=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
https://play.golang.org/p/FDNePVPo1in
here's the code which reproduce it

### What did you expect to see?
encoded url values

### What did you see instead?
empty

**Comment by mvdan** [comment]
You need to dump the request before sending it. Otherwise, the body is already fully read, so it's empty. See https://play.golang.org/p/Wq6rIfZMymK. In the future, for questions about Go, see https://golang.org/wiki/Questions.
