### ISSUE TITLE
x/tools/internal/lsp: add tests for constant completion

### ISSUE THREAD

**Issue by stamblerre** [golang/go#29816]
There are currently no tests for completion of constants.

**Comment by agnivade** [comment]
https://github.com/golang/tools/tree/master/internal/lsp

**Comment by stamblerre** [comment]
Thanks @agnivade. Changed the title - sorry, I forgot to note that it's in x/tools.

**Comment by johansja** [comment]
Is this still relevant? Where should I look at to pick up on this?

**Comment by stamblerre** [comment]
Yes it is! Basically we need tests for completion when the item being completed is a constant. For an example of how the test format looks, you can check out https://github.com/golang/tools/blob/master/internal/lsp/testdata/bar/bar.go.in or any of the files in the `testdata` directory. Basically, items that should appear in the results get marked as "item" and then to trigger a completion test, we add the "complete" marker. The testing framework is quite complex, so feel free to ask me any questions on here.
