### ISSUE TITLE
what is problem ?

### ISSUE THREAD

**Issue by CyberTheReape** [golang/go#29815]
hello..  I am learning golang software language ...but I am facing a problem.. i am using go version go1.11.4  in my computer. I'm learning this topic right now "Signed integers".. I have some simple codes in my hand...results on this site do not match the results on the computer (https://play.golang.org/p/mFsmjVk5oc) 

![1](https://user-images.githubusercontent.com/42475284/51406818-41bf0880-1b6b-11e9-8de5-b27c0ec693ef.png)

![2](https://user-images.githubusercontent.com/42475284/51406827-48e61680-1b6b-11e9-8e77-1c256578b38e.png)

play.golang.org >>> size 4
my compter     >>>> size 8 ?????

Is this a golang version error?

**Comment by as** [comment]
No. The play.golang run on the 32 bits system.

**Comment by CyberTheReape** [comment]
In other words, 32-bit system results in different results, 64-bit systems are different results?

My computer 64-bit system

**Comment by ALTree** [comment]
> In other words, 32-bit system results in different results, 64-bit systems are different results?

Yes, as as said, the size of an `int` variable is implementation-specific, and it's *usually* 32-bit on 32-bit systems, and 64-bit on 64 bits system.

Closing here, since your question has been answered.

**Comment by ianlancetaylor** [comment]
Yes, the size of `int` is different on different systems.

**Comment by CyberTheReape** [comment]
Thanks
