### ISSUE TITLE
cmd/compile: -gcflags='all=-N -l'" with Delve and large functions causes compiler error: bvbulkalloc too big

### ISSUE THREAD

**Issue by crimsonalucard** [golang/go#29829]
### What version of Go are you using (`go version`)?

<pre>
$ go version
`go version go1.12beta2 darwin/amd64`
</pre>
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/brianyeh/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/brianyeh/.gvm/pkgsets/go1.12beta2/global"
GOPROXY=""
GORACE=""
GOROOT="/Users/brianyeh/.gvm/gos/go1.12beta2"
GOTMPDIR=""
GOTOOLDIR="/Users/brianyeh/.gvm/gos/go1.12beta2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yn/cq2yhbbd2hx0w17rhtbqd_lh0000gn/T/go-build792381837=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</pre></details>
### What did you do?

ran 
`go build -gcflags='all=-N -l'`
when I run "go build" it works but the above breaks.
Unfortunately I can't provide source code. It's closed source. 

### What did you expect to see?
A binary executable. 

### What did you see instead?
Compiler hangs for 30 minutes before exiting with this error:
```
# github.com/parsable/mothership/vendor/github.com/parsable/thrift-api/v1/thrift_metadata
<autogenerated>:1: internal compiler error: bvbulkalloc too big: nbit=39417 count=567595 nword=1232 siz
e=699277040
```

**Comment by agnivade** [comment]
Does it work with 1.11.4 ?

**Comment by ALTree** [comment]
AFAIK this is likely to be caused by an old and known compiler issue related to liveliness analysis.

If you have a really big map literal in your code, that's likely to be the culprit.

**Comment by ALTree** [comment]
> You guys know about a temporary fix in the mean time?

See https://github.com/golang/go/issues/26560#issuecomment-407276913

> [...] you might try reorganizing your code. Use a slice as the underlying data structure and copy it into a map in an init function. Presumably that code is autogenerated so it might require only a small change to the generator.
