### ISSUE TITLE
.github: use multiple issue templates?

### ISSUE THREAD

**Issue by josharian** [golang/go#29839]
GitHub now supports having multiple issue templates: https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/

We could use this e.g. to have different templates for proposals vs regular issues. On the other hand, it adds another click between golang.org/issue/new and actually typing text. (We have also long discussed a bug filing wizard (bug.golang.org), but that seems to be forgotten/abandoned.)

Thoughts? @dmitshur

**Comment by dmitshur** [comment]
> We could use this e.g. to have different templates for proposals vs regular issues.

Adding a `.github/ISSUE_TEMPLATE/proposal.md` sounds reasonable to me.

> On the other hand, it adds another click between golang.org/issue/new and actually typing text.

I don't understand why that would be, can you elaborate? As I understand, [golang.org/issue/new](https://golang.org/issue/new) would continue to redirect to https://github.com/golang/go/issues/new, which would continue to use the default `.github/ISSUE_TEMPLATE.md` template (we'd have to give the [existing file](https://github.com/golang/go/blob/8e50e48f4ddd434b848240837a02a487d502b3ee/.github/ISSUE_TEMPLATE) an .md extension to not collide with the new directory). From the GitHub blog post:

> Your default ISSUE_TEMPLATE.md files will continue to work as the default when a template isn’t specified in the new issue URL.

To get to the proposal template, one would have to visit https://github.com/golang/go/issues/new?template=proposal.md. We could consider making a shortlink on golang.org for it, for example golang.org/issue/new?template=proposal.md or golang.org/issue/new/proposal.

The [`go bug` command](https://golang.org/cmd/go/#hdr-Start_a_bug_report) is relevant here, but I don't think it needs to support making proposals.

**Comment by josharian** [comment]
> I don't understand why that would be, can you elaborate?

I was wrong. However, it does add an extra step when you are at the GitHub issue page and then click "New issue". To experience it yourself, go e.g. to https://github.com/tensorflow/tensorflow/issues and click "New issue". (And if we wanted that, looks like we could have golang.org/issues/new link to github.com/golang/go/issues/new/choose).

**Comment by dmitshur** [comment]
> However, it does add an extra step when you are at the GitHub issue page and then click "New issue". To experience it yourself, go e.g. to https://github.com/tensorflow/tensorflow/issues and click "New issue".

This is true.

I originally suspected it's because they don't have a default issue template. See the [`.github` directory](https://github.com/tensorflow/tensorflow/tree/ff91cd691027076e6128afbd902d3d38e3672787/.github). If there was a `.github/ISSUE_TEMPLATE.md` default template there, I thought it'd be used by default.

However, that's not the case. It can be seen by clicking "New issue" at https://github.com/gogs/gogs/issues, despite their [`.github` directory](https://github.com/gogs/gogs/tree/5702e4bc2483ab976a1391f7517f5187527d9635/.github) having both a default `ISSUE_TEMPLATE.md`, and two templates in `.github/ISSUE_TEMPLATE` directory.

> And if we wanted that, looks like we could have golang.org/issues/new link to github.com/golang/go/issues/new/choose.

Yep.

**Comment by seankhliao** [comment]
I think this would be more useful now that we also have separate instructions for gopls, pkgsite, and language changes

With an extra `.github/ISSUE_TEMPLATE/config.yml`, we can also control blank issues and add links for questions/security

ref:
- gopls https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#file-an-issue
- pkgsite https://golang.org/s/pkgsite-feedback
- language changes https://github.com/golang/proposal/blob/master/go2-language-changes.md#template

**Comment by dmitshur** [comment]
I think there's a good chance it is worth doing now.

To make progress here, I suggest creating a test repo and experiment there. Once we have something that seems like a net positive change to adopt in the main Go issue tracker, we can do it. But having that test repository to see how it actually works and looks will make it easier to evaluate that step.

**Comment by seankhliao** [comment]
I've created a quick demo with the templates I know about, though a lot of the naming/wording would need work
https://github.com/seankhliao/testrepo-666/issues/new/choose

**Comment by josharian** [comment]
There are lots of little tweaks that I would make, but that looks really promising, @seankhliao. Thanks for putting it together! Let's do it.

**Comment by dmitshur** [comment]
I've made [CL 369154](https://go.dev/cl/369154) that adds special handling of existing `go.dev/issue/new` links for if we need it.
