### ISSUE TITLE
cmd/link: broken binary when code depends on cgo on Darwin

### ISSUE THREAD

**Issue by darkpssngr** [golang/go#29861]
System:
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS 10.14.1 (Mojave)
go version go1.11.4 darwin/amd64
Xcode 8.3; clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin16.4.0

I'm seeing the exact same issue as #12950. Tried both `-ldflags=-s` and `-ldflags=-v` no luck.
But weirdly enough if I wait for 15-20 mins and then try to execute the file it works, not sure what is happening here.

<pre>
package main

import "C" // Delete this line and the binary works.

func main() {
    println("Hello OSX.")
}

</pre>
<pre>
go build -ldflags=-s main.go
~/g/s/test  ./main                                                                                                                                                                
[1]    29457 killed     ./main
 
*wait for 20mins*
~/g/s/test  ./main 
Hello OSX.

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shreyas/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shreyas/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/93/71nm0j9s12d80pxr31r1fph94cw6ph/T/go-build961481238=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by ianlancetaylor** [comment]
You are saying that you can't build any program that uses cgo?  That seems odd; I don't recall seeing anybody else report that problem.  The bit about waiting for 20 minutes doesn't make any sense to me.  Does this happen on more than one machine?

**Comment by darkpssngr** [comment]
I think you are right. I'm seeing logs of the executable being scanned in the AntiVirus. I'll talk to the IT team about this. Thanks closing the issue.

**Comment by darkpssngr** [comment]
just checked the detailed logs. I see this line
`<Info> this file is not signed at all or not signed rightfully, no need to extract signature`
any idea what it means?

**Comment by AlexRouSg** [comment]
See https://en.wikipedia.org/wiki/Code_signing

Usually it means "don't trust this executable" or "do extra checks"

**Comment by darkpssngr** [comment]
Is there something that can be done to get the Antivirus to trust it. like how we need to codesign gdb for it work on mac (https://gist.github.com/hlissner/898b7dfc0a3b63824a70e15cd0180154)

**Comment by AlexRouSg** [comment]
Not sure if signing would change anything tbh. The quickest and surest way is to just tell the antivirus to don't scan this folder or this executable.

**Comment by darkpssngr** [comment]
Okay. I'll check with my IT team then. There seems to be no way for me to add exceptions.

**Comment by agnivade** [comment]
Seems like this is not a Go issue. Closing. 

Feel free to reopen if you see the issue even after disabling the Antivirus.

**Comment by darkpssngr** [comment]
Seems like an issue with the latest version of xcode command line tools. I downgraded the version and it works fine now.
