### ISSUE TITLE
gofmt and goimports conflict to each other on the code style formatting

### ISSUE THREAD

**Issue by lnshi** [golang/go#29863]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 darwin/amd64
</pre>

when i have code like this:
```
var extractAllowedHeadersToModelServerTests = []struct {
	desc                        string
	incomingHeaders             map[string]string
	allowedHeadersToModelServer map[string]struct{}
	expect                      []string
}{
	{
		desc: "Test case: HTTP request no headers allowed",
		incomingHeaders: map[string]string{
			"key_1": "value_1",
		},
		allowedHeadersToModelServer: map[string]struct{}{},
		expect: []string{},
	},
}
```

i tested with `gofmt` it doesn't complain, but with `goimports` it will complain that `.go:1::warning: file is not goimported (goimports)`

then i run the `goimports -w path_to_above_source_file.go`, and find out it is complaining the `expect: []string{},` line, and it formats it to:
```
                incomingHeaders: map[string]string{
			"key_1": "value_1",
		},
		allowedHeadersToModelServer: map[string]struct{}{},
		expect:                      []string{},
```

looks like `gofmt` and `goimports` conflict with each other on the code style formatting?

**Comment by robpike** [comment]
This is almost always due to version skew between gofmt and goimports. Try updating goimports (go get -u golang.org/x/tools/cmd/goimports).

**Comment by lnshi** [comment]
I just updated the go version `go 1.10.3 -> 1.11.4`, and `gofmt` starts complaining also :)

Closing as problem solved.
