### ISSUE TITLE
net/http requests seem to ignore Host headers?  

### ISSUE THREAD

**Issue by toranger** [golang/go#29865]
### What version of Go are you using (`go version`)?
 go1.8.1 linux/amd64

### What did you do?
net/http requests seem to ignore Host headers?  
`package main

import "os"
import "net/http"

func main() {
	req, _ := http.NewRequest("GET", "http://1.2.3.4", nil)	
	// I wish explicitly setting this Host header would take precedence
	req.Header.Set("Host", "www.example.org")
	req.Write(os.Stdout)
}
`

### What did you expect to see?
 I want to send to the stable nginx host, but not change the host header which different from the nginx host.

### What did you see instead?
Example output:
GET / HTTP/1.1
Host: 1.2.3.4
User-Agent: Go http package
Before I go further, am I doing this correctly?

**Comment by agnivade** [comment]
Set the `Host` field in https://golang.org/pkg/net/http/#Request to override the host value in the URL.

**Comment by Gnouc** [comment]
`Host` header is ignored https://github.com/golang/go/blob/cad6d1fef5147d31e94ee83934c8609d3ad150b7/src/net/http/request.go#L92

**Comment by toranger** [comment]
> Set the `Host` field in https://golang.org/pkg/net/http/#Request to override the host value in the URL.
The scene is that I want to send the request with the s3 bucket host such like "BucketName.s3.amazonaws.com" , and send this message to the server which has nginx front which set the location such like "location ~ ^(/test/)(.*)$ ".  
I can change the host header by your way, but can not send to the special program on server

**Comment by toranger** [comment]
> Set the `Host` field in https://golang.org/pkg/net/http/#Request to override the host value in the URL.

Set the Host field in https://golang.org/pkg/net/http/#Request to override the host value in the URL.
The scene is that I want to send the request with the s3 bucket host such like "BucketName.s3.amazonaws.com" , and send this message to the server which has nginx front which set the location such like "location ~ ^(/test/)(.*)$ ".
I can change the host header by your way, but can not send to the special program on server

**Comment by bradfitz** [comment]
What @agnivade said:

https://play.golang.org/p/4W_KJGBa77s

It works.
