### ISSUE TITLE
x/tools/cmd/tip: stopped updating (godoc fails to build due to new dependency that isn't fetched)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29874]
```
go=8d2e65d2/tools=b2f18478: 2019/01/22 16:26:57 installing godoc...
go=8d2e65d2/tools=b2f18478: 2019/01/22 16:26:57 /build/tip/b/gopath/src/golang.org/x/tools/godoc/redirect/redirect.go:22:2: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
        /build/tip/b/go/src/golang.org/x/net/context/ctxhttp (from $GOROOT)
        /build/tip/b/gopath/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
go=8d2e65d2/tools=b2f18478: 2019/01/22 16:26:57 Init failed: go install golang.org/x/tools/cmd/godoc: exit status 1
```

It's because of [CL 157197](https://golang.org/cl/157197), which added a new `golang.org/x/net/context/ctxhttp` dependency to the `golang.org/x/tools/godoc/redirect` package.

/cc @bradfitz @cnoellekb FYI.

**Comment by bradfitz** [comment]
As I wrote on chat:

> looks like godocBuilder's Init needs to also install x/net in addition to x/tools now.
> but really, let's just switch to modules and delete code instead.
> we can use the existing private Athens cache

**Comment by dmitshur** [comment]
> looks like godocBuilder's Init needs to also install x/net in addition to x/tools now.

That's what was done in [CL 158937](https://golang.org/cl/158937) for now.

> let's just switch to modules and delete code instead

Can you elaborate on what you had mind? In what way would modules be used here? Do you mean once the website uses modules itself, or something else?
