### ISSUE TITLE
net/http: method decHostConnCount should not dec counter when somebody is block on connPerHostAvailable

### ISSUE THREAD

**Issue by j2gg0s** [golang/go#29889]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>

### What did you do?
About `net/http/transport.getConn`
When current conn number is greater than MaxConnPerHost, `incHostConnCount` return connPerHostAvailable and caller block on this chan,  but **connPerHostCount will not inc**.
When somebody is block on connPerHostAvailable and one conn be closed, `decHostConnCount` notify and **connPerHostCount dec**.

One Example:

- MaxConnsPerHost is one

Time 1
- ReqA call `getConn` and get connA,  connPerHostCount now is one

Time 2
- ReqB call `getConn` but block on connPerHostAvailable or idleConnCh

Time 3
- ReqA close connA, notify ReqB and dec connPerHostCount
- ReqB notify by idleConnCh and create connB

Time 4
- ReqC call `getConn` and create connC

current two conns exist, but MaxConnsPerHost is one.

### What did you expect to see?
When somebody is block on connPerHostAvailable and one conn be closed, `decHostConnCount` notify and **connPerHostCount don't dec**.

**Comment by j2gg0s** [comment]
Add one unit test to explain what I want to express.
https://github.com/golang/go/pull/29910

**Comment by billybanfield** [comment]
Hey all! We appear to have run into this issue as well. It manifested as MaxConnsPerHost not being respected if concurrently made requests failed and then begin to succeed. Here's a repro demonstrating this behavior: https://github.com/billybanfield/tcpbug/blob/master/tcpbug.go. Happy to provide any additional info needed here.

**Comment by j2gg0s** [comment]
@bradfitz @FiloSottile Need some feedback.

**Comment by rsc** [comment]
MaxConnsPerHost is fairly broken; see #32336. I will try to keep this bug in mind when I develop a fix for the other. Maybe it will be easy to fix both.
