### ISSUE TITLE
cmd/ld: gdb on windows cannot find source code

### ISSUE THREAD

**Issue by tjyang** [golang/go#2988]
<pre>What steps will reproduce the problem?

gdb ./hello.exe

Which compiler are you using (5g, 6g, 8g, gccgo)?

go build 

Which operating system are you using?

win7 64 bit

Which revision are you using?  (hg identify)

hg id
52ba9506bd99 weekly/weekly.2012-02-07

Please provide any additional information below.

$ go build -x hello
WORK=C:\Users\user1\AppData\Local\Temp\go-build887497746
mkdir -p $WORK\hello\_obj\
cd $GOROOT\gocode\src\hello
$GOBIN\tool\8g.exe -o $WORK\hello\_obj\_go_.8 -p hello -I $WORK .\helloworld.go
$GOBIN\tool\pack.exe grc $WORK\hello.a $WORK\hello\_obj\_go_.8
$GOBIN\tool\8l.exe -o $WORK\hello\_obj\a.out.exe -L $WORK $WORK\hello.a
cp $WORK\hello\_obj\a.out.exe hello.exe

USER1@user1-00 /c/goweekly/gocode/src
$ ./hello.exe
Hello, World!

USER1@user1-00 /c/goweekly/gocode/src
$ go version
go version weekly.2012-02-07 +52ba9506bd99

USER1@user1-00 /c/goweekly/gocode/src
$

What is the expected output?

Listing helloworld source codes.

What do you see instead?

USER1@user1-00 /c/goweekly/gocode/src
$ gdb hello.exe
GNU gdb (GDB) 7.2
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;<a href="http://gnu.org/licenses/gpl.html&gt">http://gnu.org/licenses/gpl.html&gt</a>;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;
and &quot;show warranty&quot; for details.
This GDB was configured as &quot;mingw32&quot;.
For bug reporting instructions, please see:
&lt;<a href="http://www.gnu.org/software/gdb/bugs/&gt">http://www.gnu.org/software/gdb/bugs/&gt</a>;...
Reading symbols from c:\goweekly\gocode\src/hello.exe...done.
(gdb) l
1       : No such file or directory.
        in
(gdb) quit</pre>

**Comment by mattn** [comment]
Trying this in latest go.

![](http://go-gyazo.appspot.com/54b7e3866ade4c98.png)
