### ISSUE TITLE
cmd/link: -X not applied if target is the result of a function call

### ISSUE THREAD

**Issue by daenney** [golang/go#29897]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.4
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/daenney/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daenney/Development/go"
GOPROXY=""
GORACE=""
GOROOT="/home/daenney/.asdf/installs/golang/1.11.4/go"
GOTMPDIR=""
GOTOOLDIR="/home/daenney/.asdf/installs/golang/1.11.4/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build378681064=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```go
package main

import (
        "fmt"
        "time"
)

var (
        Version string = "1"
        Time string = time.Unix(0, 0).String()
)

func main() {
        fmt.Println(Version)
        fmt.Println(Time)
}
```

```sh
go build -o main -ldflags "-X main.Version=2 -X main.Time=3" main.go
./main
```

### What did you expect to see?

```
2
3
```

### What did you see instead?

```
2
1970-01-01 01:00:00 +0100 CET
```

**Comment by daenney** [comment]
I'm not sure if this is a bug or a lack of documentation but I couldn't find anything in `go help build` that would explain this.

If I change `Time` to be ` Time string = "0"` the `-ldflags` applies as expected and I end up with `2 3` being printed.

**Comment by ianlancetaylor** [comment]
The docs (https://golang.org/cmd/link) say "This is only effective if the variable is declared in the source code either uninitialized or initialized to a constant string expression. -X will not work if the initializer makes a function call or refers to other variables."  So while this is unfortunate it's a known and documented limitation.

**Comment by daenney** [comment]
Ah, it had not occurred to me to check cmd/link instead. Thanks for the pointer!
