### ISSUE TITLE
cmd/go: go build does not show that git (?) is not installed, instead shows general "cannot find module for path "

### ISSUE THREAD

**Issue by nicknaychov** [golang/go#29891]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/GOprojects"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nickn/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build125501625=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
When you try to enable modules and use go.mod

when you try to run the quick example from https://github.com/golang/go/wiki/Modules
you get 
build github.com/you/hello: cannot find module for path rsc.io/quote

BTW error happens does not matter what modules you try to import. Just decided to give simplest example. 
### What did you expect to see?

you should see clear error that GitHub is not installed on your system.

### What did you see instead?

build github.com/you/hello: cannot find module for path rsc.io/quote

which is quite confusing and general error...
Same can be reproduces on Windows as well.

**Comment by robpike** [comment]
Do you mean git? GitHub is a web site but it is also a desktop UI for talking to GitHub.

**Comment by agnivade** [comment]
This should be fixed in 1.12. Please try with 1.12beta2.

**Comment by nicknaychov** [comment]
yes git

sorry about that

**Comment by nicknaychov** [comment]
Thanks for fixing. I lost couple hours reading manuals and wondering why it does not work, my setup was following all official manuals. But those manuals were not mentioning that you need installed git. Please fix that as well for all newbies. Then I gave up, start swearing and decided to go old way and just use go get. That command showed me that git was missing. Once installed everything was working as in the manuals.

**Comment by agnivade** [comment]
> But those manuals were not mentioning that you need installed git. Please fix that as well for all newbies.

Please open a new issue for that, specifically mentioning which docs you felt were missing. This thread already has a different context. Thanks.
