### ISSUE TITLE
x/vgo: mirror or url rewrite request (feature)

### ISSUE THREAD

**Issue by boxsnake** [golang/go#29917]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=E:\Projects\freat/bin
set GOCACHE=C:\Users\Alex\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Alex\go
set GOPROXY=
set GORACE=
set GOROOT=D:\Programs\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Programs\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Alex\AppData\Local\Temp\go-build844678762=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
* Install `vgo` via `go get github.com/x/vgo`
* Run `vgo get github.com/jinzhu/gorm`
* Since `gorm` depends on package `cloud.google.com/go`, and the repository does not exists now, it failes in getting `gorm`.
* Here is `cloud.google.com/go` mirror on Github: https://github.com/googleapis/google-cloud-go
* Here is the doc on `godoc`: https://godoc.org/cloud.google.com/go
* The go uses package name to detect VCS url. Since the package name is still `cloud.google.com/go`, `vgo` can not found the VCS repo.
----
I hope that mirrors or url rewrite to be added into `vgo` for dealing with such troubling situations.

**Comment by mvdan** [comment]
I'm pretty sure you can just use replace directives for this purpose: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

**Comment by boxsnake** [comment]
@mvdan Thanks. I did not notice that.

`vgo` is almost the first dependency managing tool which makes a go project "really" reproducible. Hope this can be widely used.
