### ISSUE TITLE
net/http: reduce allocations in (Header).clone

### ISSUE THREAD

**Issue by NWilson** [golang/go#29915]
### What version of Go are you using (`go version`)?

`go version go1.11.2 linux/amd64`

### Does this issue reproduce with the latest release?

Yes

### What did you do?

When using net/http's server, and profiling with pprof shows that the "Header.clone" function takes up a lot of allocations (4% of my application's allocations, actually).

### Solution

Could we improve the function to perform fewer allocations!

(NB. Note that Reader.ReadMIMEHeader in net/textproto already uses exactly this same trick, of using  three-argument slicing to build the http.Header using a single `[]string`. So the pattern already exists in the codebase.)

```diff
--- /tmp/header-v1.go   2019-01-24 11:18:01.182761218 +0000
+++ /tmp/header-v2.go   2019-01-24 11:17:42.367569268 +0000
@@ -1,9 +1,17 @@
 func (h Header) clone() Header {
  h2 := make(Header, len(h))
+ sliceLen := 0
+ for _, vv := range h {
+  sliceLen += len(vv)
+ }
+ slice := make([]string, sliceLen)
+ sliceLen = 0
  for k, vv := range h {
-  vv2 := make([]string, len(vv))
+  vv2 := slice[sliceLen:sliceLen+len(vv):sliceLen+len(vv)]
+  sliceLen += len(vv)
   copy(vv2, vv)
   h2[k] = vv2
  }
  return h2
 }
```

**Comment by bradfitz** [comment]
Sounds fine to me. I was actually thinking about this recently when reviewing something else.

Go ahead and send a change.

**Comment by agnivade** [comment]
@NWilson - did you want to send a CL for this ?

**Comment by NWilson** [comment]
Brilliant, thanks so much for putting together the PR!

I maybe would have done it eventually... but I've not contributed to Go before, and I just know from each experience that a first-time patch to a new project takes at least a few hours to learn the ropes and get set up with a new build & code review system, and just didn't have the time to spare.

I'm happy with the CL above, thank you!

**Comment by CAFxX** [comment]
I realized there are at least other two copies of that function in the go tree, so the CL is incomplete-ish (technically one of them -in h2_bundle.go- is bundled, so I can't fix it in the CL).

**Comment by agnivade** [comment]
@NWilson - We accept github PRs now btw. So you don't need to setup gerrit.

**Comment by NWilson** [comment]
Closing, fixed in https://golang.org/cl/166498

**Comment by bradfitz** [comment]
@NWilson, that change hasn't been submitted. Re-opening.

**Comment by NWilson** [comment]
Oops, thanks @bradfitz
