### ISSUE TITLE
time: misleading error message froms Parse for initial element missing leading zeroes

### ISSUE THREAD

**Issue by tredoe** [golang/go#29918]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Parsing the month-day "1-03" with layout "01-02".
https://play.golang.org/p/7bfuFfjG7nJ

### What did you expect to see?
At the last part of the error i=1: cannot parse "1" as "01"

### What did you see instead?
month out of range

**Comment by dmitshur** [comment]
It looks like there are 3 CLs open for review that are all trying to resolve this issue:

- [CL 160338](https://golang.org/cl/160338)
- [CL 160479](https://golang.org/cl/160479)
- [CL 163260](https://golang.org/cl/163260)

To make progress on this issue, those CLs should be reviewed.
