### ISSUE TITLE
spec: define what a function is

### ISSUE THREAD

**Issue by griesemer** [golang/go#2991]
<pre>There's almost no text on what a function actually is. Needs to be expanded.</pre>

**Comment by odeke-em** [comment]
My attempt at defining a function, with short notes before I can submit a CL to see if we are on the same page. Please let me know if this is alright and I can spin up a CL.

#### Notes
- A collection of instructions that execute a procedure.
- defined with keyword `func`.
- scope and definition determined/enclosed in braces `{}`.
- invoked by a starting '(' and a closing ')' and passing any arguments within parentheses. Arguments may be variadic.
- Anonymous or named(but must have a unique name within a scope).
- Must have terminating statement e.g panic, return.
- May take in zero or more typed arguments within the opening '(' and ')'.
- May return zero or more typed arguments.
- May invoke other functions including itself.

### Definition Trial
A function is a collection of instructions defined with a starting keyword `func` defining a scope by braces `{` and `}`, and that may perform operations on data. A function takes zero or more typed arguments that are enclosed within balanced parentheses ie `(` and `)` and may or may not return typed arguments.
A function may or may not have a name after the keyword `func` e.g `func foo() {` or `func() {` and can only be invoked by the function's name or definition site without the preceding keyword `func`, using balanced parentheses to pass in arguments. A function must have a terminating statement that is a `panic` or `return`.
When a function returns a value or more, the values can be received positionally by variable assignment.

**Comment by bradfitz** [comment]
I think this bug is about describing the semantics of functions and not their syntax, which is already [suitable described](https://golang.org/ref/spec#Function_declarations). Let's leave the spec work to @griesemer, @ianlancetaylor, @robpike and @rsc.

**Comment by odeke-em** [comment]
Gotcha. For sure. Thanks for the clarification.

**Comment by robpike** [comment]
I don't think it needs to be explained. In my experience no one has asked about this.

**Comment by bradfitz** [comment]
Closing. We can always reopen if needed.

**Comment by griesemer** [comment]
Just for the record: I do think this deserves some text. Yes, it may be "obvious" but so is the notion of an "array" which is by far a more simple language concept. That said, nobody has asked for it - this was a reminder for myself. Ok to leave closed for now.
