### ISSUE TITLE
time: wrong error message at parsing years

### ISSUE THREAD

**Issue by tredoe** [golang/go#29916]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Parsing the year-month "111-01" with layout "2006-01"

https://play.golang.org/p/maXaDx3GZ-V

### What did you expect to see?

At the last part of the error i=2: cannot parse "111" as "2006"

### What did you see instead?

cannot parse "01" as "2006"

**Comment by bcmills** [comment]
This is quite likely the same underlying problem as #29918. Closing as a duplicate.
