### ISSUE TITLE
proposal: time: add ZeroTime function

### ISSUE THREAD

**Issue by tredoe** [golang/go#29914]
Some times you need to have a Time with value set to zero to be entered at columns where the constraint 'not null' is set.

**Comment by mdlayher** [comment]
Does a `time.Time{}` literal not meet this need?

More information is needed than a single sentence. This proposal doesn't really explain what you're trying to accomplish, what you've already tried, why those workarounds are unacceptable, how common this issue is, etc.

**Comment by tredoe** [comment]
Ok, time.Time{} meets this issue.

https://play.golang.org/p/QEJeKdQ93u1

**Comment by agnivade** [comment]
FYI - This is already documented - 

>The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC. As this time is unlikely to come up in practice, the IsZero method gives a simple way of detecting a time that has not been initialized explicitly.
