### ISSUE TITLE
x/build/cmd/coordinator: version.sh check for custom version fails when upstream isn't set

### ISSUE THREAD

**Issue by dmitshur** [golang/go#29929]
The [`version.sh`](https://github.com/golang/build/blob/96be844d4340c572a9d001c3925032c502cf896e/cmd/coordinator/version.sh) file attempts to append `-$USER-$(date -u +%Y-%m-%dT%H:%M:%SZ)` to the `VERSION` environment variable when the working directory is dirty, or when the current commit doesn't match the remote commit:

```bash
if [ -n "$dirty" ] || [ -n "$(git rev-list '@{upstream}..HEAD')" ]; then
  VERSION=$VERSION-$USER-$(date -u +%Y-%m-%dT%H:%M:%SZ)
fi
```

_(Source: [https://github.com/golang/build/blob/96be844d/cmd/coordinator/version.sh#L12-L14](https://github.com/golang/build/blob/96be844d4340c572a9d001c3925032c502cf896e/cmd/coordinator/version.sh#L12-L14))_

When the current branch doesn't have an upstream set (as can be the case if checking out a CL locally), `git rev-list '@{upstream}..HEAD'` exits with a non-zero exit code:

```
$ git rev-list '@{upstream}..HEAD'
fatal: no upstream configured for branch 'cl-155463'
```

As a result, the version reported at https://farmer.golang.org/ ends up being something like `93bae7b41a9a410dc6ca905034d3a49c59e10390` instead of `93bae7b41a9a410dc6ca905034d3a49c59e10390-dmitshur-2019-01-25T01:16:25Z`.

Pretty harmless, but should be improved, if this can be done without adding significant complexity to the bash file. Help is welcome.

**Comment by dmitshur** [comment]
[CL 159699](https://golang.org/cl/159699) mentioned this issue (without the "golang/go" prefix, that's why it wasn't recognized by @gopherbot).

I don't think this issue is resolved yet. That CL added a check for `git remote -v` output being zero. `git remote -v` would be zero if the repository did not have any remotes. That's not what happens when you checkout a different branch. The branch doesn't have an _upstream_ remote branch that it's tracking.

Consider the following reproduce steps:

```
$ cd /tmp
$ git clone https://go.googlesource.com/build
$ cd build
$ git fetch https://go.googlesource.com/build refs/changes/99/159699/6 && git checkout FETCH_HEAD
$ git checkout -b cl-159699
$ git remote -v
origin	https://go.googlesource.com/build (fetch)
origin	https://go.googlesource.com/build (push)
$ git rev-list '@{upstream}..HEAD'
fatal: no upstream configured for branch 'cl-159699'
```

Note that `git remote -v` still produces non-empty output, yet `git rev-list '@{upstream}..HEAD'` fails.

**Comment by bradfitz** [comment]
Ah! Now I understand this bug. I missed that before and assumed the CL author knew what they were doing more than me and approved the CL because it was at least harmless in the worst case.
