### ISSUE TITLE
x/text: tag a more recent commit

### ISSUE THREAD

**Issue by hyangah** [golang/go#29937]
In module mode, golang.org/x/text picks up more than a year old commit
because its tag, though set before module support, follows semver format.
Providing a tag with a more recent commit will help x/text users transitioning to module mode.

```
$ GOPATH=$(mktemp -d) GO111MODULE=on tipgo list -versions -json -m golang.org/x/text
go: finding golang.org/x/text v0.3.0
{
	"Path": "golang.org/x/text",
	"Version": "v0.3.0",
	"Versions": [
		"v0.1.0",
		"v0.2.0",
		"v0.3.0"
	],
	"Time": "2017-12-14T13:08:43Z"
}
```

**Comment by bcmills** [comment]
CC @mpvl

**Comment by AlekSi** [comment]
v0.3.3 was tagged recently: https://pkg.go.dev/golang.org/x/text@v0.3.3?tab=versions. I think this issue can be closed.

**Comment by mvdan** [comment]
Indeed, @katiehockman tagged a version in June. I'm closing this.
