### ISSUE TITLE
windows vettool

### ISSUE THREAD

**Issue by jcburley** [golang/go#29939]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ianlancetaylor** [comment]
No information.

**Comment by jcburley** [comment]
Sorry -- guess I somehow Submitted that issue!? Started to, then realized I didn't have enough info without access to my Windows machine (was/am on the road, and it's at home).

My problem is that I can't seem to get my build script to work under GNU Bash in Windows, because it tries to use the `shadow` tool with `go tool vet -vettool=`, and the path to `shadow` yields a not-found diagnostic showing its Windows path, not Unix.

When I get home, I'll look into filing a proper Issue.
