### ISSUE TITLE
Panic due 'slice bounds out of range' after upgrading to Go 1.11.4

### ISSUE THREAD

**Issue by renatoaguiar** [golang/go#29942]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, it does.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/renato/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/renato/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007436369=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

After upgrading Go from 1.10.2 to 1.11.4, the following code panics:

<pre>
package main

import "fmt"

func main() {
	ls := []byte{}
	ls = append(ls, 1)
	l := len(ls)
	if l != 1 {
		ls = ls[:l-1]
		return
	}
	ls = ls[:l-1]
	fmt.Println("OK")
}
</pre>

https://play.golang.org/p/Q4vOMt27xKN

(I know the programming logic doesn't make any sense, so please don't ask me any questions regarding what this code is trying to do. I just took an existing production code that started panicking after the Go upgrade and stripped it down until I got the simplest code that still reproduces the issue.)

### What did you expect to see?

OK

### What did you see instead?

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()
        /tmp/slice_bug.go:13 +0x6b
exit status 2

**Comment by randall77** [comment]
This is fixed on tip.
I believe this is #29502.  The backport to 1.11 (#29503) is ready to go with the next point release.
So I think this is all fixed.

**Comment by randall77** [comment]
Hmmm, the fix in #29502 doesn't fix 1.11.4 for this issue. Maybe it is a related issue.
In any case, at least tip is ok.

**Comment by randall77** [comment]
@cherrymui

**Comment by vandewilly** [comment]
This error seems to be related to the commit bdc7d56 that was supposed to fix the issue #28799. After reverting this commit locally, the code provided by @renatoaguiar in this issue works without any panic.

**Comment by randall77** [comment]
@dr2chase

**Comment by dr2chase** [comment]
I agree with @cherrymui.
```
git fetch https://go.googlesource.com/go refs/changes/19/156019/4 && git cherry-pick FETCH_HEAD
go install cmd/compile
cd $b
go clean --cache
go run main.go
```
and it prints "OK", where previously (before cherry-pick and compiler install) it failed.

**Comment by randall77** [comment]
Hmm, don't know what I did wrong then.
I applied the patch manually to 1.11.4. The core of it is just a 1-liner, not sure how I screwed that up.
Maybe install doesn't work right on releases?

In any case, I'll close as a dup.
