### ISSUE TITLE
net/http: FileServer() directory listings cannot be styled

### ISSUE THREAD

**Issue by Russtopia** [golang/go#29945]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/russtopia/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/russtopia/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib64/go1.11.3"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/go1.11.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build777521497=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Developing an app using http.FileServer(), it became apparent by examining the net/http/fs.go dirList() function, which is used by serveFile() to emit HTML listings of directories, that the format/styling of these directory pages is hardcoded, with no facility for callers to apply basic header, footer or link styling to allow consistency with the rest of custom endpoints an application might serve, by http.HandleFunc() etc.

Basic styling allowing applications to override the basic HTTP headers, HTML header, body and footer portions of a served directory listing page would fill a significant gap in the customization facilities of the core http package, such that applications serving custom endpoints as well as bare filesystem trees could have a consistent presentation (eg. vendor backgrounds, alink styling, legal disclaimers when browsing directories, and so on).

### What did you expect to see?
Some facility for applications to apply basic styling to directory pages served by http.FileServer().

### What did you see instead?
Hardcoded &lt;pre&gt;...&lt;/pre&gt; blocks emitted by dirList(), for directory listings, and no control over HTTP headers or alink styles.

**Comment by bradfitz** [comment]
Sorry, but this has already been declined in the past.

If you want a fancy fileserver, feel free to fork net/http's and put it on GitHub and reference it here for others to find.
