### ISSUE TITLE
why use different type of cookie max-age ? 

### ISSUE THREAD

**Issue by Linvas** [golang/go#29957]
go v 1.11.5 

/net/http/cookie.go
line:  31, MaxAge is a int type
```go
type Cookie struct {
	Name  string
	Value string

	Path       string    // optional
	Domain     string    // optional
	Expires    time.Time // optional
	RawExpires string    // for reading cookies only

	// MaxAge=0 means no 'Max-Age' attribute specified.
	// MaxAge<0 means delete cookie now, equivalently 'Max-Age: 0'
	// MaxAge>0 means Max-Age attribute present and given in seconds
	MaxAge   int
	Secure   bool
	HttpOnly bool
	SameSite SameSite
	Raw      string
	Unparsed []string // Raw text of unparsed attribute-value pairs
}
```
MaxAge is a int type, why not use int64 type?????????
but at the same file
line: 203
> b.Write(strconv.AppendInt(buf[:0], int64(c.MaxAge), 10))

why turn it into int64 ????
Is it a design issue ?

**Comment by mvdan** [comment]
MaxAge is a number of seconds. Being signed, that gives us a maximum value of 2147483648, which is roughly 68 years. Do you expect anyone will need cookies that expire in hundreds of years?

The reason the field is converted to int64 is becahse strconv.AppendInt takes an int64. That doesn't imply there's a bug anywhere.

What exacly are you trying to do? If you just think you have found a bug, I'm pretty sure there's none.

**Comment by bradfitz** [comment]
Maybe it should've been a time.Duration. Maybe it should've been an int64. Or maybe int is correct.

In any case, we can't change it now due to https://golang.org/doc/go1compat

But I think an int is reasonable. It's a natural type and gives at least 68 years, as @mvdan mentioned, or much more on 64-bit platforms.
