### ISSUE TITLE
go/build: build.Import doesn't import package if srcDir is provided

### ISSUE THREAD

**Issue by nephe** [golang/go#29952]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/theller/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/theller/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jd/6ps0d4r53hxcbfl_g94kcvhc0000gn/T/go-build812346700=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I was trying to import package by using `( *Context) Import` method from `go/build` package with package name as `path` and parent directory path to package as `srcDir`.
https://play.golang.org/p/HT524Fr32hz

### What did you expect to see?

No error after importing package.

### What did you see instead?

```
cannot find package "httptest" in any of:
	/usr/local/go/src/httptest (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
```

The same applies to packages from GOPATH. 

Current implementation:
https://github.com/golang/go/blob/447965d4e008764a8635df6ca7d5d2e59c6d4229/src/go/build/build.go#L650

I think if `srcDir` is provided it should be used instead of `"src"` constant in Import method.
```
src := "src"
if srcDir != "" {
	if sub, ok := ctxt.hasSubdir(ctxt.GOROOT, srcDir); ok {
		src = sub
	}
}
dir := ctxt.joinPath(ctxt.GOROOT, src, path)
```

**Comment by mvdan** [comment]
Have you tried using https://godoc.org/golang.org/x/tools/go/packages? For most use cases, `go/build` is deprecated in its favor. And you'll also get Go module support.

**Comment by nephe** [comment]
Then I will close it.
