### ISSUE TITLE
net/textproto: ability to skip conversion for canonical format

### ISSUE THREAD

**Issue by molecul** [golang/go#29965]
### What version of Go are you using (`go version`)?

<pre>
go version go1.9.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/projects/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build449725707=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

I want to use ReadMIMEHeader() from net/textproto/reader.go for reading headers on ICAP protocol. So I have a trouble with `key := canonicalMIMEHeaderKey(kv[:endKey])` (line: 496), because ICAP protocol have a case sensitive headers (for ex: ISTag). Please can you add a new flag-variable to ReadMIMEHeader function for skip `canonicalMIMEHeaderKey` conversion.

### What did you expect to see?

Something like this:
`func (r *Reader) ReadMIMEHeader(toCanonical bool) (MIMEHeader, error)`
and
`if toCanonical == true {
      key := canonicalMIMEHeaderKey(kv[:endKey])
}`

### What did you see instead?
`func (r *Reader) ReadMIMEHeader() (MIMEHeader, error)`
and
`key := canonicalMIMEHeaderKey(kv[:endKey])`

**Comment by bcmills** [comment]
> because ICAP protocol have a case sensitive headers (for ex: ISTag)

Do you have a reference for the case-sensitivity of those fields? https://tools.ietf.org/html/rfc3507#section-4.3 seems to indicate that they are case-insensitive.

**Comment by bcmills** [comment]
CC @bradfitz @rsc for `net/textproto`

**Comment by bradfitz** [comment]
I don't think we want to expand this package.

I think it's probably best if you fork it and add whatever you need.

**Comment by molecul** [comment]
Thanks for all, I will fork it. But I think that this request can be implemented as another function (for example `ReadRawHeader`) without using `canonicalMIMEHeaderKey` method.. I think this will be useful and will not affects existing calls of `ReadMIMEHeader` method in other modules. I can make pull request if you want.

**Comment by ALTree** [comment]
It seems like the decision here was not to add the feature, and we're not really waiting for any additional information even if this is labelled as waiting for info. I'm closing this, but feel free to comment if I'm wrong.
