### ISSUE TITLE
x/mobile: stdlibc++ deprecation building issue: flags set but still shows error: clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]

### ISSUE THREAD

**Issue by imWildCat** [golang/go#29969]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

Other version info:
- Xcode: `Version 10.1 (10B61)`
- macOS: `10.14.2 (18C54)`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wildcat/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wildcat/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS="-stdlib=libc++"
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4q/nqwtcbqx7kl9pp0dllbqx4qc0000gn/T/go-build198858859=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Background: I was trying to build a Go library (with C++ source) into objective-c bindings (as .framework).

```bash
$ export CGO_CPPFLAGS="-stdlib=libc++"
$ gomobile bind -target ios github.com/yanyiwu/gojieba
gomobile: darwin-arm: go build -tags ios -buildmode=c-archive -o /var/folders/4q/nqwtcbqx7kl9pp0dllbqx4qc0000gn/T/gomobile-work-251366135/gojieba-arm.a gobind failed: exit status 2
# github.com/yanyiwu/gojieba
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What did you expect to see?

The library can be built as an iOS framework.

### What did you see instead?

The build failed due to `libstdc++` is used even if I set `export CGO_CPPFLAGS="-stdlib=libc++"`.

Without `export CGO_CPPFLAGS="-stdlib=libc++"`, it shows:

```bash
$ export CGO_CPPFLAGS=""
$ gomobile bind -target ios github.com/yanyiwu/gojieba
gomobile: darwin-arm: go build -tags ios -buildmode=c-archive -o /var/folders/4q/nqwtcbqx7kl9pp0dllbqx4qc0000gn/T/gomobile-work-275429029/gojieba-arm.a gobind failed: exit status 2
# github.com/yanyiwu/gojieba
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from jieba.cpp:5:
In file included from ../../../../golang/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
../../../../golang/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:4:10: fatal error: 'algorithm' file not found
```

**Comment by bcmills** [comment]
CC @eliasnaur @hyangah

**Comment by eliasnaur** [comment]
@imWildCat you can use the latest version of gomobile or the -iosversion flag to set a minimum iOS version >= 7.

**Comment by imWildCat** [comment]
Thank you, @eliasnaur ! It works perfectly!
