### ISSUE TITLE
database/sql: Improper error handling.

### ISSUE THREAD

**Issue by SagarPuneria** [golang/go#29975]
#29973 https://github.com/golang/go/blob/66065c3115861c73b8804037a6d9d5986ffa9913/src/database/sql/sql.go#L2729

I think it would be better to refactor error handling code something like this:
`if err := rs.lasterr; err != nil && err != io.EOF {`

**Comment by kardianos** [comment]
Please look at https://bitbucket.org/kardianos/table for the proper way to use NextResultSet. I'm aware of how to use it and the documentation; I wrote it.

**Comment by SagarPuneria** [comment]
@kardianos, let me clear, i am new to database.

The reason behind escalating this issue is that i want to know in which case [NextResultSet](https://golang.org/pkg/database/sql/#Rows.NextResultSet) return true?

I tried all the cases it is always returning false. If so then what is use case of implementing [NextResultSet](https://golang.org/pkg/database/sql/#Rows.NextResultSet)?
Could you please give me at least one case where [NextResultSet](https://golang.org/pkg/database/sql/#Rows.NextResultSet) return true.

Before giving your answer, i would suggest you to do sample program on [NextResultSet](https://golang.org/pkg/database/sql/#Rows.NextResultSet) where it can return true case.

I hope you got my Question.

**Comment by agnivade** [comment]
If you are new to databases and want some clarifications, please take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page to ask questions like these. You will get better and faster answers there. The issue tracker is primarily for bugs and proposals.

**Comment by SagarPuneria** [comment]
@agnivade, I understand your concern. I tried all the cases, [NextResultSet](https://golang.org/pkg/database/sql/#Rows.NextResultSet) is always returning false. If so then it is bug right. So i am in right page for escalating the issue.
