### ISSUE TITLE
Cannot determine module path for source directory 

### ISSUE THREAD

**Issue by roadhub** [golang/go#29974]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
~/code/src/github.com/molen » go env                                                             admin@roadup
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wei/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wei/Code"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g_/2bc1vvrn73qg6n8brh4q9yd40000gn/T/go-build451878900=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
go  mod init

### What did you expect to see?
go: cannot determine module path for source directory /Users/wei/code/src/github.com/molen (outside GOPATH, no import comments)

**Comment by roadhub** [comment]
i had add GO111MODULE=on, but i cannot init a go project by go mod init as the asme.

**Comment by agnivade** [comment]
Since you are outside GOPATH, and there were no import comments, it could not guess the module path. Please supply the module path you want.

https://golang.org/cmd/go/#hdr-Initialize_new_module_in_current_directory.

**Comment by roadhub** [comment]
thanks!  but i think that go should give me more information or this website, not only an error.

> Since you are outside GOPATH, and there were no import comments, it could not guess the module path. Please supply the module path you want.
> 
> https://golang.org/cmd/go/#hdr-Initialize_new_module_in_current_directory.

**Comment by agnivade** [comment]
Perhaps. Feel free to open a new documentation issue in that case.

**Comment by roadhub** [comment]
I add more information and send a pull request for this case.
