### ISSUE TITLE
x/tools/cmd/goimports: does not understand identifiers defined by internal test files

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#29979]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +4b3f04c63b Thu Jan 10 18:15:48 2019 +0000 linux/amd64
</pre>

As of commit 0a99049195aff55f007fc4dfd48e3ec2b4d5f602, goimports does not seem to consider the local package as a candidate for an external test.

Here's a [testscript](https://godoc.org/github.com/rogpeppe/go-internal/cmd/testscript) example that demonstrates the issue:

	exec goimports -w a_test.go
	cmp a_test.go a_test.go-goimports
	
	-- go.mod --
	module example.com/a
	-- a_test.go --
	package a_test
	
	func TestX() {
		a.X()
		a.Y()
	}
	-- a.go --
	package a
	
	func X() {
	}
	-- export_test.go --
	package a
	
	func Y() {
	}
	-- a_test.go-goimports --
	package a_test
	
	import "example.com/a"
	
	func TestX() {
		a.X()
		a.Y()
	}

I would expect running `goimports` on a.go to add an import of `example.com/a`.

**Comment by heschik** [comment]
The test script has a typo -- it's running on `a.go`, not `a_test.go`. Once I fix that it passes on my machine. If it doesn't on yours can you add `-v` and show the output?

**Comment by rogpeppe** [comment]
@heschik Thanks, you're right! I'll have to investigate more. I've got a larger example that definitely fails in this way, but I obviously need to be a bit more careful isolating the circumstances in which it's happening.

**Comment by heschik** [comment]
Ah. Yes. That is unsurprising in retrospect.

@ianthehat: Without looking I'd bet a small sum that it's because of this line in `loadExports`:

https://github.com/golang/tools/blob/cb89afadce946e09f295886d955e7135642e195c/imports/fix.go#L980

It should probably do the same thing as `parseOtherFiles`.

**Comment by ianthehat** [comment]
So I think https://go-review.googlesource.com/c/tools/+/160999 correctly tests the problem, now I just need to fix it...

**Comment by heschik** [comment]
Hmm, I guess this is more complicated than I had initially given it credit for. Perhaps the best thing would be to directly special-case the package under test? Like, in fixImportsDefault, if the filename ends with _test, call loadExports on srcDir in a special mode and add that directly to the candidate list?
