### ISSUE TITLE
x/crypto/argon2: hash differs from C++ implementation

### ISSUE THREAD

**Issue by phifty** [golang/go#29976]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/philipp/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/philipp/go"
GOPROXY=""
GORACE=""
GOROOT="/nix/store/786qm6ljn16g6q913kv6dgzl6yma8i61-go-1.11/share/go"
GOTMPDIR=""
GOTOOLDIR="/nix/store/786qm6ljn16g6q913kv6dgzl6yma8i61-go-1.11/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/philipp/go/src/github.com/simia-tech/crypt/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build759245311=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Generated a Argon2i hash with parameters:
<pre>
type = Argon2i
password = "password" (hex 70617373776f7264)
salt = "longsaltlongsalt" (hex 6c6f6e6773616c746c6f6e6773616c74)
m = 65536
t = 3
p = 1
</pre>

### What did you expect to see?

<pre>
hash = cc3528e2fb0b3c289bb1a25052498fd82600ad5a372b2c6206894f2308b52717 (hex)
</pre>
I generated this hash with the C++ implementation at https://github.com/khovratovich/Argon2 using the same parameters as above. I double-checked all the input parameters and it seems that the implementations differs in some way. I'm not sure which one is correct.

### What did you see instead?

<pre>
hash = 2b6acb7d5a101b5ecbb949f6ea8b5ab135f55815e3afa862e4d65728ac6662bb (hex)
</pre>

**Comment by AlexRouSg** [comment]
The official reference implementation is https://github.com/P-H-C/phc-winner-argon2

Running with the following args: 
`echo -n "password" | ./argon2 longsaltlongsalt -t 3 -m 16 -p 1`
`-m` is `2^N` so `-m 16` == `65536`

Gives the result:

```
Type: Argon2i  
Iterations: 3 
Memory: 65536 KiB
Parallelism: 1                                                                
Hash: 2b6acb7d5a101b5ecbb949f6ea8b5ab135f55815e3afa862e4d65728ac6662bb 
Encoded: $argon2i$v=19$m=65536,t=3,p=1$bG9uZ3NhbHRsb25nc2FsdA$K2rLfVoQG17LuUn26otasTX1WBXjr6hi5NZXKKxmYrs
Verification ok
```

**Comment by phifty** [comment]
Thanks for the hint. It seems than that the other implementation is broken. I'll close the issue.
