### ISSUE TITLE
cmd/vet: update for new number formats

### ISSUE THREAD

**Issue by rsc** [golang/go#29986]
cmd/vet once again lives outside the main tree (sigh).

We need to remember to update the printf checker for
the new formats %#b and %O on integers, %x on float/complex.

**Comment by seh** [comment]
It looks like _vet_'s update for the new octal format verb 'O' would go [here](https://github.com/golang/tools/blob/c161412db0d0912a7438a865c39bdd7edcd20ede/go/analysis/passes/printf/printf.go#L726-L727).

**Comment by michael-schaller** [comment]
As far as I can tell this bug should be fixed.

@rsc, could you double check and mark this bug as fixed?
https://github.com/golang/tools/blob/8b020aee10d2dc97e13b76ce01b59c9b5d4a4d0f/go/analysis/passes/printf/printf.go#L790-L819

**Comment by michael-schaller** [comment]
Also as `%O` was introduced with Go 1.13 should this be included in the next Go 1.13 and 1.14 point releases?

**Comment by ianlancetaylor** [comment]
I don't think this is fixed until we import a new version of the packages into the main sources.

**Comment by ianlancetaylor** [comment]
@gopherbot Open backport issues for 1.13 and 1.14

"go vet" should permit %O in fmt.Printf formats, as the formatting code was added in the 1.13 release.

**Comment by ianlancetaylor** [comment]
@gopherbot Please open backport issues for 1.13 and 1.14

"go vet" should permit %O in fmt.Printf formats, as the formatting code was added in the 1.13 release.

**Comment by michael-schaller** [comment]
@ianlancetaylor note that `%#b` and `%x` support was added in other changes by other people and these changes would need to be cherry picked as well...

The changes in question are:
* [go/analysis/passes/printf: allow # for b flag](https://github.com/golang/tools/commit/288d118ee925162f0c33d4c282bbd08c6ab69cd5)
* [go/analysis/passes/printf: allow %x/%X for float/complex types](https://github.com/golang/tools/commit/04252eccb9d565ac559eee6a62be04f927675aab)

**Comment by ianlancetaylor** [comment]
@michael-schaller True.  At a quick glance it seems like those two are fixed in 1.14, but not in 1.13.

**Comment by michael-schaller** [comment]
@ianlancetaylor please let me know if I can help in some other way with this bug. I'm curious how this is all handled... ;-)

**Comment by dmitshur** [comment]
The version of the golang.org/x/tools module is specified in the src/cmd/go.mod files on the release branches for Go 1.14 and 1.13:

- https://github.com/golang/go/blob/release-branch.go1.14/src/cmd/go.mod#L11
- https://github.com/golang/go/blob/release-branch.go1.13/src/cmd/go.mod#L11

The release branches in golang.org/x/tools should correspond to those pseudo-versions:

- https://github.com/golang/tools/commits/release-branch.go1.14
- https://github.com/golang/tools/commits/release-branch.go1.13

This is already the case for 1.14, but the x/tools release-branch.go1.13 is incorrect (it's many commits ahead) and will need to be reset to match the version selected in https://github.com/golang/go/blob/release-branch.go1.13/src/cmd/go.mod#L11.

Then, it's a matter of backporting the relevant vet fixes to each of the x/tools release branches, and updating the go.mod (and re-running `go mod vendor` as documented [here](https://github.com/golang/go/blob/release-branch.go1.13/src/README.vendor)) accordingly on the main Go release branches.

Given it's quite a bit of mechanics, it's likely a good idea to wait until the backport issues (#39288 and #39287) make progress from their current CherryPickCandidate state before starting the work.

**Comment by dmitshur** [comment]
The backport issues have been approved.

I'll also add release-blocker to this to track the vendor of [CL 235100](https://golang.org/cl/235100) into the main tree.

**Comment by ianlancetaylor** [comment]
@dmitshur Sorry, didn't notice that you had assigned this to yourself.

**Comment by dmitshur** [comment]
@ianlancetaylor That is not a problem. I noticed you've sent the CL thanks to gopherbot's message above just before I started doing any work. I reviewed your CL. Thank you.
