### ISSUE TITLE
os: RemoveAll does not remove directories when ancestor directory lacks permissions

### ISSUE THREAD

**Issue by neild** [golang/go#29983]
This is a regression in Go 1.12 introduced by https://go-review.googlesource.com/c/137442 ("add support for long path names on unix RemoveAll").

```
mkdir -p a/1/x
mkdir -p a/2/x
chmod 0555 a
```

On Go 1.11, `os.RemoveAll("a")` removes `a/1/x` and `a/2/x` and returns "remove a/1: permission denied".
On Go 1.12, `os.RemoveAll("a")` returns "permission denied" and does not remove anything.

**Comment by bradfitz** [comment]
This might be acceptable and just need docs. The current docs in the release notes only says:

> RemoveAll now supports paths longer than 4096 characters on most Unix systems.

And, whoa, we no longer have docs on RemoveAll:

https://tip.golang.org/pkg/os/#RemoveAll

That needs to be fixed too.

**Comment by neild** [comment]
The docs for RemoveAll say:

```
// RemoveAll removes path and any children it contains.
// It removes everything it can but returns the first error
// it encounters. If the path does not exist, RemoveAll
// returns nil (no error).
```

So, not acceptable: RemoveAll no longer removes everything it can.

**Comment by neild** [comment]
The new `RemoveAll` is also skipping the call to `testlog.Open`.

**Comment by neild** [comment]
I'm also dubious about this distinction:

https://go.googlesource.com/go/+/master/src/os/removeall_at.go#132
https://go.googlesource.com/go/+/master/src/os/file_unix.go#207

The older RemoveAll uses `os.Open` to open directories, which includes a Darwin-specific retry loop around `syscall.Open`. The new RemoveAll uses `unix.OpenAt` with no retry loop. Perhaps that retry loop isn't necessary with `OpenAt`, but the lack of any commentary makes me wonder.

**Comment by ianlancetaylor** [comment]
I believe that it's fine to skip the call to `testlog.Open`.  It's only necessary to call `testlog.Open` if a change in the file contents affects whether a test should be cached.  In this case it does not.
