### ISSUE TITLE
add built-in streaming support in Go 2

### ISSUE THREAD

**Issue by mateuszmmeteo** [golang/go#29980]
Currently GO is not designed to be used in streaming processing. If you're touching Kafka there is lot of stuff that needs to be made to process such queue.

Streaming of objects (structs) could be simplified by implementation of universal interface like for example java streams do where lists can be streamed.

This would require that writers accept interfaces and have similar to Java support of .foreach(interface{}).

https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html

Within our example this could look like that:

```
type SomeObject struct {
	FieldA   bool
	FieldB   string
	FieldC   []SomeObject
}

type SomeObjects []SomeObject

func process(objects *SomeObjects) {
	filtered := objects.parallelStream().foreach(func(obj SomeObject) obj {
		if obj.FieldA == true {
			return obj
		} 	
		return nil
	}).GetNotNilOrdered()
}
```

**Comment by ianlancetaylor** [comment]
We are happy to accept proposals for changes in Go 2, but this one needs more work.  I suggest that you discuss this on the golang-nuts mailing list.  For a proposal to be useful, it needs to have specific suggestions for API and a clear explanation of what new features are being added, and at least some discussion of the costs of these features.  Thanks.
