### ISSUE TITLE
xerrors: error returned by xerrors.New() is missing the Format method for detailed formatting

### ISSUE THREAD

**Issue by nhooyr** [golang/go#30036]
See https://github.com/golang/exp/blob/c74c464bbbf2425793dda2a0044770271fc009c7/xerrors/errors.go#L13-L29 which is what xerrors.New returns

and compare to https://github.com/golang/exp/blob/c74c464bbbf2425793dda2a0044770271fc009c7/xerrors/fmt.go#L81 which is what xerrors.Errorf returns

Also, there is another errors package in x/exp https://github.com/golang/exp/tree/master/errors and it looks about the same. Why are there two?

**Comment by mpvl** [comment]
@nhooyr: good catch. Will fix that.

Regarding x/exp/errors vs xerrors:
x/exp/errors is the proposal implementation intended to make it in core. 

The xerrors package is a transition-support package that allows package writers to give support for new-style errors for both pre- and post 1.13 installations or, similarly, allows users that cannot use 1.13 to benefit from these new-style errors.

**Comment by neild** [comment]
https://go-review.googlesource.com/c/xerrors/+/160658
