### ISSUE TITLE
x/net/http2/h2demo: HTTP/1 vs HTTP/2 comparison not working

### ISSUE THREAD

**Issue by nussjustin** [golang/go#30033]
### What did you do?

1. Opened the [Gophertiles page](https://http2.golang.org/gophertiles)
2. Opened the Network Tab in the Chrome Dev Tools
3. Clicked on one [of](http://http2.golang.org/gophertiles?latency=0) [the](http://http2.golang.org/gophertiles?latency=30) [HTTP/1](http://http2.golang.org/gophertiles?latency=200) [links](http://http2.golang.org/gophertiles?latency=1000).

### What did you expect to see?

Requests to the images are done via HTTP/1.X

### What did you see instead?

All requests are sent over HTTP/2.0.

![image](https://user-images.githubusercontent.com/6443781/52038148-95e5c780-2531-11e9-8578-51bb883809d5.png)

It seems like this is broken since [HSTS](https://hstspreload.org/?domain=golang.org) was enabled on golang.org. Since the golang.org domain has HSTS enabled for itself and all subdomains, and is preloaded by browsers, all HTTP requests to http2.golang.org are automatically changed to HTTPS. This leads to all requests being sent over HTTP/2.0.

**Comment by agnivade** [comment]
Hmm .. I had sent the HSTS change. On that CL, we did discuss about subdomains. Maybe this use case of http2 vs http1.1 comparison slipped through.

**Comment by bradfitz** [comment]
Rather than fight HSTS, we can just add an http1.golang.org DNS entry to the same IP and then have the server use the SNI information to determine whether it advertises http2 in ALPN.

/cc @FiloSottile

**Comment by bradfitz** [comment]
I sent the Google-internal DNS CL to add http1.golang.org.
