### ISSUE TITLE
Awkward use of "exception proves the rule" logic in FAQ

### ISSUE THREAD

**Issue by willfaught** [golang/go#30048]
### What version of Go are you using (`go version`)?

https://github.com/golang/go/blob/96d41786c5bd5b3597b6a28a7e8c412c33f15086/doc/go_faq.html#L2309

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

MacOS, Safari.

### What did you do?

Went to https://golang.org/doc/faq.

### What did you expect to see?

Something like:

    Go simplifies things by separating expression and type syntax (using prefix * for pointers being an exception).

### What did you see instead?

    Go mostly separates expression and type syntax and that simplifies things (using prefix * for pointers is an exception that proves the rule).

This seems to be a misunderstanding of what ["the exception proves the rule"](https://en.wikipedia.org/wiki/Exception_that_proves_the_rule) means. There isn't a more general rule we can infer from the fact that the pointer operator and type syntax is the same. This seems to fall under what Wikipedia deems to be a ["serious nonsense"](https://en.wikipedia.org/wiki/Exception_that_proves_the_rule#Serious_nonsense) use of the phrase.

**Comment by robpike** [comment]
It's an idiom and its use here is fine. The language would be improved without prefix *. It is therefore an exception that shows the value of simplification.

**Comment by willfaught** [comment]
I looked through the Wikipedia article again, but I couldn't find the use you're describing, where (if I understand correctly) it means an exception to a rule is a good example for the rule existing. Which use in the article are you thinking of?
