### ISSUE TITLE
encoding/csv: document that Writer is buffered

### ISSUE THREAD

**Issue by bmkessler** [golang/go#30045]
`csv.Writer` is implemented as a `bufio.Writer`, but this isn't clearly documented.  The only place buffering is mentioned is in the `Writer` example and in the `Flush()` method.  This makes it easy for a user to neglect to flush the underlying buffer and check for an error when writing a CSV, which can result in data loss.  I believe the documentation on `csv.Writer` should clearly state that the implementation is buffered and thus must be flushed.  Here is the current documentation:
  
```
// A Writer writes records to a CSV encoded file.
//
// As returned by NewWriter, a Writer writes records terminated by a
// newline and uses ',' as the field delimiter. The exported fields can be
// changed to customize the details before the first call to Write or WriteAll.
//
// Comma is the field delimiter.
//
// If UseCRLF is true, the Writer ends each output line with \r\n instead of \n.
type Writer struct {
	Comma   rune // Field delimiter (set to ',' by NewWriter)
	UseCRLF bool // True to use \r\n as the line terminator
	w       *bufio.Writer
}
```

**Comment by CAFxX** [comment]
Why is the encoder buffered in the first place? It seems a completely unrelated concern...

**Comment by ianlancetaylor** [comment]
Using a buffer is a simple way to pick up convenience methods like `WriteString`, `WriteByte`, `WriteRune`.  Of course it then requires flushing.
