### ISSUE TITLE
go/build: build cache does not properly take AR into account

### ISSUE THREAD

**Issue by benesch** [golang/go#30046]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +faf187fb8e Thu Jan 31 16:55:43 2019 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/benesch/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/benesch/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build519384162=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```AR=gcc-ar go build```

### What did you expect to see?

A successful build using the `gcc-ar` wrapper that supports LTO.

### What did you see instead?

A cached failure using the old value of AR:

```
$ AR=gcc-ar go build
ar: $WORK/b007/_go_.o: plugin needed to handle lto object
```

Dropping the cache first makes the build properly use the specified AR:

```
$ go clean -cache
$ AR=gcc-ar go build
# Success.
```

By my read, https://github.com/golang/go/commit/a063a2284af69d25d4367ff3e7c6da53f37bad03 doesn't interact with the build cache at all, and it probably should.

**Comment by bradfitz** [comment]
We can cherry-pick the fix back to Go 1.12 if the fix happens after Go 1.12 is out. (this alone won't halt the release)

**Comment by benesch** [comment]
Is this bug important enough to warrant inclusion in Go 1.12? I'm using tip so I don't care if this misses 1.12. Regardless, the fix seems simple; see the CL above.

**Comment by benesch** [comment]
Yes, I agree. Though I suspect that there are at least two of us, given that I didn't author a063a22 :)

**Comment by bradfitz** [comment]
Fixed by https://go-review.googlesource.com/c/go/+/160897
