### ISSUE TITLE
Detect OS at Compile time or before(other than BUILD CONSTRAINTS)

### ISSUE THREAD

**Issue by akhilravuri1** [golang/go#30050]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows</summary><br><pre>
$ go env

</pre></details>

### What did you do?

func (r *Rows) ColumnTypeLength(index int) (length int64, ok bool) {
	//ToDo(Akhil):This functions retuns the length of column.
	if runtime.GOOS == "windows" {
		ret := api.SQLColAttribute(r.os.h, api.SQLUSMALLINT(index+1), api.SQL_DESC_LENGTH, api.SQLPOINTER(unsafe.Pointer(nil)), 0, (*api.SQLSMALLINT)(nil), (*api.SQLLEN)(&length))
		if IsError(ret) {
			fmt.Println(ret)
			return 0, false
		}
		return length, true
	} else {
		ret := api.SQLColAttribute(r.os.h, api.SQLUSMALLINT(index+1), api.SQL_DESC_LENGTH, api.SQLPOINTER(unsafe.Pointer(nil)), 0, (*api.SQLSMALLINT)(nil), (api.SQLPOINTER)(unsafe.Pointer(&length)))
		if IsError(ret) {
			fmt.Println(ret)
			return 0, false
		}
		return length, true
	}

}
since the parameter type changes in windows and unix, I was trying to detect the os and run the code.

runtime.GOOS will detect the OS at runtime. I want to detect the OS before the compilation or at the compilation. Like How macros work in c. If it detect at run time I will get an error at the compilation as SQLColAttribute  api(of unix) is not there.

I know about Build Constraints, If I use build constraints I have to specify it at the first line of my file and then I have to make 2 files one for windows and one for unix. But, I want them to be in a single file. 
IS IT POSSIBLE.

### What did you expect to see?
application detecting the os at compile time or before( Other than Build constraints or how to use build constraints in the middle of the code).

### What did you see instead?

Error:
cannot use api.SQLPOINTER(unsafe.Pointer(&length)) (type api.SQLPOINTER) as type *api.SQLLEN in argument to api.SQLColAttribute

**Comment by mvdan** [comment]
> But, I want them to be in a single file. IS IT POSSIBLE

It's not; when a Go file is included in a build, the entirety of it must be type-checked. Go doesn't have a pre-processor nor macros, so you can't exclude part of a file from a build. Not even `if false { ... }` would get you that.

You're asking a question and reporting a compiler error, so I'm going to close the issue as I've given you the answer above. If you have a particular idea on how else this could be implemented, feel free to submit a [proposal](https://github.com/golang/proposal). But note that the Go build system is simple and fast on purpose, and it's unlikely to be changed just for the sake of avoiding one extra file.

**Comment by martisch** [comment]
Note that runtime.GOOS is a compile time constant and does not involve OS detection at program runtime.
