### ISSUE TITLE
wasm error: function import requires a callable in 1.12 beta2

### ISSUE THREAD

**Issue by advanderveer** [golang/go#30052]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12beta2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
It works with go 1.11

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adam/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/adam/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8g/sd7s1zr94f948ds6_q0v3q180000gn/T/go-build940179440=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I followed the wiki article on using web assembly: https://github.com/golang/go/wiki/WebAssembly. i to complete the "Getting Started" part with Go 1.12 when navigating with Chrome 71 to localhost:8080 it shows an error. 

Upgrading to chrome 72 fixes the issue

### What did you expect to see?
I expected it to work and show "Hello, WebAssembly" in the console.

### What did you see instead?
When navigating to the localhost:8080 the developer console shows the following error:

<pre>
(index):1 Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #5 module="go" function="runtime.scheduleTimeoutEvent" error: function import requires a callable
Promise.then (async)
(anonymous) @ (index):7
</pre>

**Comment by agnivade** [comment]
I would be surprised if a simple hello world does not work in Chrome 71 but works in Chrome 72. Are you sure this is not caused by an incorrect wasm_exec.js ?

Please see https://github.com/golang/go/issues/29827.

**Comment by advanderveer** [comment]
I tried it again on my old version of Chrome and it now seems to work fine again, maybe the old wasm_exec.js was still loading from my browsers cache? Hard to say after the fact. Anyway, thank you for the quick response, i'll close this issue!
