### ISSUE TITLE
cmd/go: 'install' succeeds without a main module when given a non-main package 

### ISSUE THREAD

**Issue by mvdan** [golang/go#30053]
https://go-review.googlesource.com/c/go/+/148517 works great, for the most part. I found this behavior, which confused me a bit.

```
$ go version
go version devel +faf187fb8e Thu Jan 31 16:55:43 2019 +0000 linux/amd64
$ export GO111MODULE=on
$ go env GOMOD
/dev/null
$ go install mvdan.cc/xurls/v2
$ echo $?
0
$ go list -f {{.Name}} mvdan.cc/xurls/v2
xurls
```

Sounds to me like this should error; `install` shouldn't behave just like `get -d` when given non-main packages.

Similarly, `go get mvdan.cc/xurls/v2` succeeds, but I presume it should fail. Only `go get -d mvdan.cc/xurls/v2` should succeed.

/cc @bcmills @myitcv

**Comment by mvdan** [comment]
@rogpeppe points out that the root directory is a non-main package with some files, so the commands were actually doing something - presumably filling up the build cache.

However, perhaps there should be a way to globally say "install this binary", which would error if erroneously given non-main packages. I had run the wrong command, and I was confused for a while as to why no binary was being installed.

But perhaps it's just me who has been confused by this :)

**Comment by bcmills** [comment]
We haven't seen many reports of confusion with this so I don't think it's a priority for 1.13, but perhaps we can revisit when folks are more used to `go install` not being a command that is ever particularly useful to run.

**Comment by mvdan** [comment]
I think we could close this issue if we had the command for #30515 error when given non-main packages.

**Comment by mvdan** [comment]
Update - now `go install` always errors outside of a main module, and it's only `go get` that still works.

I think there's less reason to make `go get foo.com/non/main/pkg` error outside of a main module, because of that. Also, it would be weird to force the user to do `go get -d` in that case.

In any case, this issue was about my own confusion, and I no longer find the current situation confusing. Closing.
