### ISSUE TITLE
crypto/x509: certificates with AKID don't chain to parents without SKID

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#30079]
The fix for #29233 broke certificate chains where a certificate has an AKID but the parent doesn't.

These chains are weird (where did the AKID come from if there's no SKID?) and invalid by RFC 5280 (parents MUST have AKID) but they are out there, and as much of the X.509 ecosystem, we need to live with them.

Reported by @abarisani in https://github.com/golang/go/issues/29233#issuecomment-459304095.

In the review @sleevi pointed out that the old code was also subtly broken (if a parent with wrong subject but right AKID and one with right subject but no SKID were available, only the former would be considered, failing to build a chain) but that was a way rarer scenario.

We broke this in a minor (security!) release, which is not good, so we should backport a revert, and fix also the subtle case above in Go 1.13.

**Comment by FiloSottile** [comment]
@gopherbot please open both backport issues. This is a regression introduced in a minor release

**Comment by FiloSottile** [comment]
Short term fix done for Go 1.12, leaving open on Go 1.13 for a more complete fix.

**Comment by dmitshur** [comment]
@FiloSottile Is the short term fix what should be used for backporting purposes, and is it enough to resolve the two backport issues? Or should they wait for full fix before backporting?

**Comment by FiloSottile** [comment]
@dmitshur Yeah, the short term fix is all we need to backport.
