### ISSUE TITLE
cmd/go: go get -v -u github.com/stretchr/testify/assert failing

### ISSUE THREAD

**Issue by shivumm** [golang/go#30073]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.11.5
</pre>

### What operating system and processor architecture are you using (`go env`)?
OSX

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

**# cd .; git clone https://github.com/stretchr/testify /Users/shivakumarmm/Documents/go/src/github.com/stretchr/testify
Cloning into '/Users/shivakumarmm/Documents/go/src/github.com/stretchr/testify'...
ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
package github.com/stretchr/testify/assert: exit status 128**

</pre></details>

### What did you expect to see?

i m expecting to import github.com/stretchr/testify/assert this to local

**Comment by mvdan** [comment]
This is lacking information. Exactly what did you run, what was the output, and what did you expect? You also omitted `go env` entirely.

**Comment by ramintagizade** [comment]
It seems to work on OSX and Windows 10.
