### ISSUE TITLE
x/crypto/openpgp: How to simultaneously sign and encrypt

### ISSUE THREAD

**Issue by Ape** [golang/go#30076]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I tested with the latest master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ape/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ape/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build535261915=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

---

`x/crypto/openpgp` supports encrypting and signing messages, but is it possible to simultaneously sign and encrypt a message? I am mainly interested in symmetric encryption similar to `gpg --sign --symmetric`.

**Comment by viswesr** [comment]
@gopherbot add Question

**Comment by bcmills** [comment]
There is now a `golang-openpgp` mailing list (https://groups.google.com/forum/#!forum/golang-openpgp). Given the relative silence here, you might try that next.
