### ISSUE TITLE
math/cmplx: Pow(0, NaN) panics

### ISSUE THREAD

**Issue by kortschak** [golang/go#30088]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +4b3f04c Thu Jan 10 18:15:48 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE=".../.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="..."
GOPROXY=""
GORACE=""
GOROOT=".../go"
GOTMPDIR=""
GOTOOLDIR=".../go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build317177083=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run the code here: https://play.golang.org/p/yfwQqWxgxup or https://play.golang.org/p/fYLIyw9slsj

https://play.golang.org/p/W6okRxbBrvO also look wrong, but does not panic.

### What did you expect to see?
NaN+NaNi or similar.

### What did you see instead?
```
panic: not reached

goroutine 1 [running]:
math/cmplx.Pow(0x0, 0x0, 0x0, 0x0, 0x1, 0x7ff80000, 0x0, 0x0, 0x434070, 0xeee60, ...)
	/usr/local/go/src/math/cmplx/pow.go:63 +0x3a0
main.main()
	/tmp/sandbox419620258/main.go:10 +0x60
```

**Comment by bcmills** [comment]
CC @griesemer @rsc for `math/cmplx`

**Comment by bcmills** [comment]
Yep, that code is definitely wrong: it assumes that `real(y)` is comparable with `0`.
https://github.com/golang/go/blob/20c110eb2aacd9023bf7340252f14c83cba7abba/src/math/cmplx/pow.go#L52-L62

**Comment by bcmills** [comment]
For comparison, `math.Pow(0, math.NaN())` returns `NaN`: https://play.golang.org/p/GoK_-oL24jN

**Comment by bcmills** [comment]
C defines the error behavior for `cpow` to be equivalent to `cexp(y*clog(x))`.

`math/cmplx` seems to result in `NaN + NaNi` in those cases: https://play.golang.org/p/qTvkddJzCtv
