### ISSUE TITLE
cmd/compile: grammatical mistake in assignment mismatch error

### ISSUE THREAD

**Issue by agnivade** [golang/go#30087]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +faf187fb8e Thu Jan 31 16:55:43 2019 +0000 linux/amd64
</pre>

### What did you do?

```go
package main

func main() {
  var a, b = 1
}
```
On running this,

1.11 gives - 
```
# command-line-arguments
./reserved.go:4:6: assignment mismatch: 2 variables but 1 values
```

tip gives - 
```
./reserved.go:4:6: assignment mismatch: 2 variable but 1 values
```

This was introduced in commit ae9c822f78d5048aa4290b06a5a38f67aaf23dbe

Author: David Heuschmann <heuschmann.d@gmail.com>
Date:   Sat Sep 15 13:04:59 2018 +0200

    cmd/compile: use more specific error message for assignment mismatch
    
    Show a more specifc error message in the form of "%d variables but %v
    returns %d values" if an assignment mismatch occurs with a function
    or method call on the right.
    
    Fixes #27595

Marking as release blocker since this was introduced in 1.12.

/cc @griesemer

**Comment by agnivade** [comment]
I do note that "1 values" was always incorrect. However, since `variables` got changed to `variable`, I think this technically qualifies as a regression.

**Comment by mvdan** [comment]
While this issue makes sense, I wonder if it's worth blocking 1.12 further just for an error typo. I presume the fix could be included in a bugfix release like 1.12.1.

**Comment by andybons** [comment]
@dddent

**Comment by agnivade** [comment]
Was simple enough so I mailed it myself.

**Comment by agnivade** [comment]
Re-milestoned as per @griesemer's comments on the CL.
