### ISSUE TITLE
crypto/x509: offer a useful error when ParsePKCS8PrivateKey/ParseECPrivateKey/ParsePKCS1PrivateKey or ParsePKIXPublicKey/ParsePKCS1PrivateKey are mixed up

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#30094]
When parsing fails in one of these functions, we could check if one of the others would have worked, and offer a helpful error message.

**Comment by arashbina** [comment]
I can work on this.
So if I understand correctly when unmarshalling to one structure if it fails try the counterpart to see if it succeeds and return a descriptive error.

**Comment by FiloSottile** [comment]
Correct. Please add me to the reviewers for the change. Thank you!
