### ISSUE TITLE
x/build/devapp: doesn't make it clear which subrepo a pending CL belongs to

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30096]
On the current [Go Release Dashboard](https://dev.golang.org/release), there's a [Pending CLs section](https://dev.golang.org/release#Pending%20CLs). It groups CLs based on the path prefix in the CL subject:

![image](https://user-images.githubusercontent.com/1924134/52304193-253f1080-2960-11e9-97cc-fba1f238de67.png)

Our [commit message formatting rules](https://golang.org/wiki/CommitMessage#other-repos) instruct people to omit subrepo prefix (like "x/crypto/") from CL subjects, since those are used only in the issue tracker.

However, the current release dashboard doesn't display the subrepo, making it hard to find (correctly formatted) CLs for a given subrepo package. For example, see https://groups.google.com/d/msg/golang-dev/j7w5535aLjA/BuE0P-wkFwAJ for a recent occurrence (/cc @bcmills).

I'd like to make a change to better visualize the subrepo that a given CL affects. Here's the proposed fix:

![image](https://user-images.githubusercontent.com/1924134/52304619-24f34500-2961-11e9-88d3-3c063d2192d2.png)

It was easy to implement by reusing the logic for doing the subject parsing from [gochanges.org](https://gochanges.org).

It also brings a benefit that improperly formatted CL subjects (that don't omit "x/crypto/" prefix) are easier to spot (and fix):

![image](https://user-images.githubusercontent.com/1924134/52304926-dbefc080-2961-11e9-8d0c-bdc29b75fc4c.png)

/cc @bradfitz @andybons @bcmills

**Comment by bradfitz** [comment]
SGTM

**Comment by dmitshur** [comment]
I've sent [CL 161219](https://golang.org/cl/161219) with the fix. It can be previewed on a staging instance at https://dev-staging.golang.org/release#Pending%20CLs.

**Comment by dmitshur** [comment]
This is deployed to https://dev.golang.org/release by now.
