### ISSUE TITLE
cmd/internal/obj/ppc64: T/S bit is being flipped when using extended mnemonics in VSX instructions

### ISSUE THREAD

**Issue by ceseo** [golang/go#30112]
### What version of Go are you using (`go version`)?

<pre>
go1.12
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
linux/ppc64le
linux/ppc64
</pre></details>

### What did you do?

[CL160429](https://go-review.googlesource.com/c/go/+/160429#message-53c995e6697c8d52b83fba50fd3c49a740702d62) uncovered a bug in the assembler, where bit 31 of XX1-form instructions is flipped when using extended mnemonics (FP/VMX registers as arguments, instead of VSX).

### What did you expect to see?

F0-F31 must map into VS0-VS13 and V0-V31 must map into VS32-VS63.

### What did you see instead?

The problem makes FP register arguments become VMX registers (or, in VSX terms, VS0-VS31 into VS32-VS63). This doesn't cause an illegal instruction, but may cause register clobbering.

**Comment by ceseo** [comment]
I have a fix and will submit as soon as the tree reopens.

**Comment by Skarlso** [comment]
Ups, sorry, tagged the wrong issue number. Move along...
