### ISSUE TITLE
x/build/cmd/gopherbot: don’t comment on issues with WIP CLs

### ISSUE THREAD

**Issue by andybons** [golang/go#30113]
A Work-in-Progress CL was created for #29984, and it was attached to the issue. If a change is WIP, it shouldn’t add the CL comment until it’s ready for review.

@rsc @golang/osp-team

**Comment by dmitshur** [comment]
There's not enough information here for me to understand this issue. Could you please clarify.

Per https://golang.org/wiki/CodeReview (and [Interim Code Review and Issue Tracker Conventions](https://groups.google.com/d/msg/golang-dev/YU56eKYiXJg/K1CkXo7Iy0gJ)), we support marking a CL as a work-in-progress by including the text "DO NOT REVIEW" in the commit message.

[CL 160458](https://golang.org/cl/160458), which mentions issue #29984 (I'm not sure if it's the same CL you were referring to) did not include such text, but it used the [Gerrit "WIP" bit](https://gerrit-review.googlesource.com/Documentation/user-upload.html#wip).

Is this issue about adding official support for that Gerrit feature as a way of marking a CL as WIP?

Or is it about gopherbot treating CLs with "DO NOT REVIEW" text in them differently?

**Comment by andybons** [comment]
If a CL is uploaded to Gerrit that is marked at Work in Progress (WIP), then gopherbot shouldn't post a message on the issue saying "golang.org/cl/NNN mentions this issue" until it moves out of WIP mode.

This is not about DO NOT REVIEW text. We can check the bit using https://godoc.org/golang.org/x/build/maintner#GerritCL.WorkInProgress

**Comment by dmitshur** [comment]
Thanks for clarifying.

**Comment by bradfitz** [comment]
> If a CL is uploaded to Gerrit that is marked at Work in Progress (WIP), then gopherbot shouldn't post a message on the issue saying "golang.org/cl/NNN mentions this issue" until it moves out of WIP mode.

Why not?

What does the WIP bit really mean? It obviously doesn't mean "don't advertise this" because otherwise you wouldn't have uploaded it. So why not advertise it more at that point and potentially avoid people wasting redundant effort on the same CL?

**Comment by andybons** [comment]
It _is_ meant to not advertise it (emails are not sent for WIP changes). It was created so that people could upload changes that were not ready for broad review or even just so they could upload it and download it on another computer to continue their work.

Check out https://gerrit-review.googlesource.com/Documentation/intro-user.html#wip for more information

**Comment by andybons** [comment]
Closing in favor of not having duplicate effort in CLs. I didn’t think about that point.
