### ISSUE TITLE
cmd/go: document that GOGCCFLAGS cannot be changed

### ISSUE THREAD

**Issue by ainar-g** [golang/go#30123]
`go env` shows that there exists an environment variable called `GOGCCFLAGS`. But in fact, [users cannot change it,](https://github.com/golang/go/issues/25711#issuecomment-394468963) unlike all other variables. The variable is there only for informational purposes. I think that this is worth documenting in `go help environment` so that users don't get surprised.

**Comment by bcmills** [comment]
Looks like it belongs in this section:
https://github.com/golang/go/blob/91170d7201253616620c78ce961a89a55fb9e732/src/cmd/go/internal/help/helpdoc.go#L586-L598
