### ISSUE TITLE
doc: in ref/mem explicitly use "buffered" when describing the rule for sends on channels

### ISSUE THREAD

**Issue by odeke-em** [golang/go#30120]
Just while studying the memory model at https://golang.org/ref/mem#tmp_7, I noticed a perhaps minor ambiguity in description.

## Problem statement
We say ***"A send on a channel happens before the corresponding receive from that channel completes."*** [1]

and that's correct for buffered channels and the quoted program is guaranteed to print "hello, world"
```go
var c = make(chan int, 10)
var a string

func f() {
	a = "hello, world"
	c <- 0
}

func main() {
	go f()
	<-c
	print(a)
}
```

However for unbuffered channels, we say ***"A receive from an unbuffered channel happens before the send on that channel completes."*** [2]
```go
var c = make(chan int)
var a string

func f() {
	a = "hello, world"
	c <- 0
}

func main() {
	go f()
	<-c
	print(a)
}
```
the receive `<-c` is firstly encountered and will block until a corresponding send completes as we do in `c <- 0` so that program is also guaranteed to print "hello, world" for unbuffered channels.

So while regardless of the first statement, the results are technically the same, it seems odd to vaguely keep a generalization[1] and a dictation[2] thereby alluding to two states existing for unbuffered channels (this is only because a receive has to be matched by a send for unbuffered channels) whereas buffered channels have a capacity to dictate their sends-first hence sends preceding receives.

## Recommendation
My recommendation is that perhaps let's update the first rule to ***"A send on a buffered channel happens before the corresponding receive from that channel completes."*** [1] or perhaps I just need to catch some sleep.

Please feel free to chime in, your ideas/corrections are highly appreciated!

/cc @griesemer @robpike @rsc

**Comment by antong** [comment]
No, I think the doc is correct. Note the difference between *happens* and *completes*.

**Comment by robpike** [comment]
It is correct as written.

**Comment by bcmills** [comment]
Note that _happens-before_, despite the name, is a non-strict order: for unbuffered channels, the send happens before the receive _and_ the receive happens before the send (that is, from the perspective of the memory model they are simultaneous).

**Comment by go101** [comment]
`happens-before` should be a strict order. The docs says _A send on a channel happens before the corresponding receive from that channel **completes**._ The word **completes* is very important here.

For a unbuffered channel, the send and the receive both happens-before the send and the receive from that channel completes, In fact the the completions of the send and the receive are the same event.

**Comment by ianlancetaylor** [comment]
You're using a different meaning of the word "strict."  In mathematic, a "strict order" implies that there is a relationship between all pairs of objects.  That is not true for the happens-before relationship, in which you can have A happens-before C and B happens-before C but there is no happens-before relationship between A and B.

**Comment by go101** [comment]
Yes.

In the description **A send on a channel happens before the corresponding receive from that channel completes.**, there are four events
1. send start (call it A)
1. receive start (call it B)
1. send end/complete (call it C)
1. receive end/complete (call it D)

I agree there is not specified order between A and B. But A and B are both guaranteed to happen before C and D. And in fact, C and D are the same event.

**Comment by go101** [comment]
What I mean is the docs is accurate here.
