### ISSUE TITLE
x/net/html: render function segfaults instead of returning an error

### ISSUE THREAD

**Issue by dj95** [golang/go#30125]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/daniel/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daniel/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build547983775=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I put invalid nodes into the render function in order to test if my error handling is correct.
E.g. with the following code:

<pre>
package main

import (
	"bytes"
	"fmt"
	"io"

	"golang.org/x/net/html"
)

func main() {
	// create a byte buffer
	var buf bytes.Buffer

	// create a writer for the buffer
	w := io.Writer(&buf)

	err := html.Render(w, nil)

	fmt.Printf("%s\n", err)
}
</pre>

a segfault occurs instead of a returned error.

### What did you expect to see?

I expect to see an error returned by the render function

### What did you see instead?

The program crashes with a segmentation fault.

**Comment by dj95** [comment]
The same behaviour occurs, if I try to render a malformed tree of nodes.

**Comment by gjolly** [comment]
I think this could be easily fixed by checking if the pointer is `nil` before any processing in `render1` (`render.go:69`).

**Comment by antong** [comment]
I don't see an issue here. A panic when you pass nil to a function expecting a pointer is business as usual. The standard library also does this all over the place. If a nil pointer *can* be passed (e.g., a `*Config` with nil meaning a default config), then that should be clearly documented.

**Comment by mikioh** [comment]
> The standard library also does this all over the place.

Well, yes and no, depending on the assessment; not simple nilable vs. non-nilable, perhaps from the system fault tolerance point of view.

**Comment by gjolly** [comment]
> The same behaviour occurs, if I try to render a malformed tree of nodes.

@dj95 Could you give an example of a such malformed tree please?

**Comment by antong** [comment]
@dj95, a minimal code example is the perfect bug report! However, the example is perhaps too contrived. How did you end up with a nil node in the first place?

**Comment by bcmills** [comment]
As @antong notes, Go packages conventionally do not check explicitly for `nil` arguments. (If you want to avoid nil-panics, I recommend fuzz-testing your program.)
