### ISSUE TITLE
enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method

### ISSUE THREAD

**Issue by borats** [golang/go#30151]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d5a36531b2 darwin/amd64
</pre>

Could you clarify why do we need to compile `openssl` with weak ciphers enabled in order to run the test?

```
// src/crypto/tls/handshake_test.go
 75         println("***********************************************")
 76         println("")
 77         println("You need to build OpenSSL 1.1.1 from source in order")
 78         println("to update the test data.")
 79         println("")
 80         println("Configure it with:")
 81         println("./Configure enable-weak-ssl-ciphers enable-ssl3 enable-ssl3-method")
 82         println("and then add the apps/ directory at the front of your PATH.")
 83         println("***********************************************")
```

Thanks!

**Comment by FiloSottile** [comment]
In order to test weak ciphers like RC4 and legacy protocols like SSLv3, which are off by default in a Go but still supported.

Note that tests are recorded, so you only need a special OpenSSL if you want to change or make a new recording. Otherwise you don’t need OpenSSL at all.

**Comment by borats** [comment]
Appreciate the explanation there @FiloSottile
