### ISSUE TITLE
dev.boringcrypto: update BoringCrypto module

### ISSUE THREAD

**Issue by akashgiri** [golang/go#30158]
We are exploring the usage of dev.boringcrypto branches for our compliance needs. The current dev.boringcrypto branches refer the older security policy, sp2964.
What are the plans to update the dev.boringcrypto branches to updated security policies (sp3318 is current)?

Older security policy: https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2964.pdf
Current security policy: https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3318.pdf

**Comment by bcmills** [comment]
CC @rsc

**Comment by FiloSottile** [comment]
@agl Can we / should we update the reference to 140sp3318.pdf? AFAIK we have not updated the BoringCrypto module itself. (Should we do that when a new validation comes through?)

**Comment by agl** [comment]
> we have not updated the BoringCrypto module itself. (Should we do that when a new validation comes through?)

Ideally, yes.

> Can we / should we update the reference to 140sp3318.pdf?

The reference should match the BoringCrypto module in use.

**Comment by FiloSottile** [comment]
I'll give this a shot for Go 1.14 then.

**Comment by dorsha** [comment]
Hi @FiloSottile, I see that the new BoringCrypto security policy version sp3318 is planned to be part of Golang 1.15.

Did you replace the implementation of `boringcrypto:SP 800-135 KDF` and `KAS ECC` to use BoringCrypto? We are under going FIPS certification process and we got a request to make them FIPS complaint as well.

Thanks!

**Comment by FiloSottile** [comment]
The new BoringCrypto object has landed in dev.boringcrypto.

@dorsha I'm not sure I understand the question, could you elaborate in a new issue or by email? I'm filippo at golang.

**Comment by agl** [comment]
> Did you replace the implementation of boringcrypto:SP 800-135 KDF and KAS ECC to use BoringCrypto? We are under going FIPS certification process and we got a request to make them FIPS complaint as well.

(I think this is requesting extra patching out from crypto/tls. NIST has weird names for things, but I suspect that the functions in question are probably `CRYPTO_tls1_prf` and `ECDH_compute_key_fips`.)

**Comment by FiloSottile** [comment]
Thanks @agl! @dorsha if that's accurate it's probably something we can look at, please open a new issue with as much detail about the requirement as possible.
