### ISSUE TITLE
doc/install.html: inconsistent slash in Windows directory name

### ISSUE THREAD

**Issue by nobozo** [golang/go#30160]
This is a minor documentation bug report for what appears on

https://golang.org/doc/install?download=go1.11.5.windows-amd64.msi#install

It says

"Next, make the directory src/hello inside your workspace"

It should be

"Next, make the directory src\hello inside your workspace"

The rest of this page uses backslash characters when showing Windows pathnames, so this sentence should also.

**Comment by bcmills** [comment]
The fix goes [here](https://github.com/golang/go/blob/11af3535310ed1f92cb75f523082702988bbd7f6/doc/install.html#L199-L209). Want to send a fix?

(https://golang.org/doc/contribute.html has instructions.)

**Comment by cbynon** [comment]
Can I take this one? I have never submitted a fix before and have been looking for one for ages that is simple so that I can learn the process more so than the actual fix. Thanks.

**Comment by bcmills** [comment]
Go for it.

Note that we're currently [still in the release freeze for Go 1.12](https://groups.google.com/forum/#!topic/golang-dev/jln8MwFpATc), so it might be a week or two before we can merge the fix.

**Comment by cbynon** [comment]
No problem, thanks.

**Comment by andriisoldatenko** [comment]
@cbynon are you still going to make a fix?

**Comment by cbynon** [comment]
Yes, definitely. I'll have it done over the weekend. As this is my first time submitting a fix on github I'm just going through the contribution notes and making sure I'm doing it correctly. Let me know if this is a problem, thanks.
