### ISSUE TITLE
How to load .so file in Linux

### ISSUE THREAD

**Issue by akhilravuri1** [golang/go#30162]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rakhil/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rakhil/go"
GOPROXY=""
GORACE=""
GOROOT="/work/rakhil/go"
GOTMPDIR=""
GOTOOLDIR="/work/rakhil/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build379042172=/tmp/go-build"
</pre></details>

### What did you expect to see?
Load (.so) file

### What did you see instead?
No syscall found in packages.

(I know that it is only for windows. But is there any package for Linux. )

Thanks

**Comment by marcellanz** [comment]
Can you specify what you did under **"What did you do?"**

**Comment by akhilravuri1** [comment]
import "syscall"
import "os"

var (
	mododbc32 = syscall.NewLazyDLL("db2cli64.dll")

	procSQLAllocHandle     = mododbc32.NewProc("SQLAllocHandle")
	procSQLBindCol         = mododbc32.NewProc("SQLBindCol")
	procSQLBindParameter   = mododbc32.NewProc("SQLBindParameter")
	procSQLCloseCursor     = mododbc32.NewProc("SQLCloseCursor")
)


In the above code I have loaded db2cli64.dll and in Linux, it is db2cli64.so so I cannot load it.
So, Is there any other way to load it.

**Comment by AndrusGerman** [comment]
```
package main

import "C"
import (
	"log"

	"github.com/rainycape/dl"
)

func main() {
	lib, err := dl.Open("../lib/server/server.so", 0)
	if err != nil {
		log.Fatalln(err)
	}
	defer lib.Close()
	// printC
	var printC func(d *C.char)
	lib.Sym("PrintTestC", &printC)
	printC(C.CString("Prin Example SO funtion"))
}

```

**Comment by AndrusGerman** [comment]
Please close the issue ;) ... I think that with my answer is enough.

**Comment by akhilravuri1** [comment]
Is there any package that comes GoLang.

**Comment by AndrusGerman** [comment]
I do not know a specific go package for the "linux.so" call. Although "github.com/rainycape/dl" is easier to use than syscall and very light :+1:

**Comment by akhilravuri1** [comment]
Ok. Thanks
