### ISSUE TITLE
net/http: http server Golang does not allow to handle unexpected errors

### ISSUE THREAD

**Issue by arealshadow** [golang/go#30164]
### What version of Go are you using (`go version`)?
1.10.7

<pre>
$ go version
go version go1.10.7 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

When I'll put % to my HTTP server go cause '400 Bad Request'
Example: http://localhost/somerequest%

That's all want to know maybe another mimic error we have?
And how to handle them to my custom messages.

**Comment by agnivade** [comment]
Please mention exactly what you did. And why you expect the 400 response to be a bug.

Regarding your other questions, you will get better answers on any of the [forums](https://github.com/golang/go/wiki/Questions).

**Comment by arealshadow** [comment]
Hello, I want to use m own message to all of http server error of Go like 400 bad requests.

**Comment by agnivade** [comment]
Why can't you wrap your requests in a middleware and use your own message ?
