### ISSUE TITLE
Create multiple http clients with different internet connections

### ISSUE THREAD

**Issue by AndrusGerman** [golang/go#30171]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andrusd/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andrusd/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build501600568=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?
Multiple http requests with different internet connections connected to my server
```
package main

import (
	"net/http"
	"net"
)

func main() {
	//Get By Default network
	GetByDefaultNetwork()
	// Get By Wifi custom network
	httpCustomClient := &http.Client{Network: net.GetNetworkOs("eth1")}
	GetByCustomNetwork(httpCustomClient)
}

// Example custom eth1
func GetByCustomNetwork(custom *http.Client) {
	custom.Get("http:/google.com")
}

// Example default eth0
func GetByDefaultNetwork() {
	http.Get("http://google.com")
}

```

### What did you see instead?

nothing

**Comment by AndrusGerman** [comment]
If this is not possible go. It is possible to add this functionality, since working with servers with multiple connections is common in the cloud

**Comment by renthraysk** [comment]
The code posted doesn't use the custom http.Client.

**Comment by AndrusGerman** [comment]
:+1: @renthraysk  Already solved. The proposal should be better understood

**Comment by bradfitz** [comment]
You can achieve your goals by using an http.Client using an http.Transport that defines the Dial hook(s) with a net.DialTCP and setting the local addr on the dials.

**Comment by AndrusGerman** [comment]
@bradfitz  I had no knowledge of this. Thank you. Now I just have to find where to learn more about this
