### ISSUE TITLE
exp/xerrors: confusing which package to use

### ISSUE THREAD

**Issue by broady** [golang/go#30180]
There are two xerrors packages, x/exp/xerrors and x/xerrors.

Can we get some clarity (preferably in package-level godoc) on which package should be used, and for what purpose?

x/xerrors looks most useful to use right now, for library authors as well as for application developers.

**Comment by ianlancetaylor** [comment]
CC @jba @neild

**Comment by neild** [comment]
Use `golang.org/x/xerrors`.

The one in `exp` was an experiment. It's probably time to delete it to avoid confusion.
