### ISSUE TITLE
database/sql: who wants to be notified about changes / proposals?

### ISSUE THREAD

**Issue by kardianos** [golang/go#30198]
database/sql is in a somewhat unique position in that database/sql and database/sql/driver is really only have the code users interact with.

@methane (of mysql driver) recently raised an issue where they were unaware of a change in database/sql, only now becoming aware of it with the 1.12 rc release.

Without discussing the change in question in this issue ( https://github.com/golang/go/commit/651ddbdb5056ded455f47f9c494c67b389622a47#commitcomment-32283737 ), If there driver maintainers who would like to be notified proposed changes or issues, please let me know what driver you maintain and how you would like to be notified.

If there is interest, I'll make a list and ensure people are notified.

/cc @mjibson @mattn @tgulacsi

**Comment by josharian** [comment]
I would suggest creating a google group for it and then telling folks about it on golang-dev and golang-nuts.

**Comment by kardianos** [comment]
That's a good idea. I've already created https://groups.google.com/forum/#!forum/golang-sql for past purposes, it just hasn't been very popular.

I'll start sending proposals and issues to it. Then if people want to know what's going on, I can point to the list.
