### ISSUE TITLE
Expose the SemVer package publicly

### ISSUE THREAD

**Issue by mohamedattahri** [golang/go#30194]
I’ve worked on more than one project that needed to programmatically configure environments using versioned packages, or simply log which versions are being used for future auditability. Tasks like parsing and comparing SemVer versions were pretty common. 

The implementation used for the Go11 modules [cmd/go/internal/semver](https://github.com/golang/go/blob/47d5a4433513c3870a9994b50ed4fa2af628c742/src/cmd/go/internal/semver/semver.go) seems stable and complete enough to be made public.

I suggest we move the `semver` package one level up so it’s not longer under _internal_.

**Comment by bcmills** [comment]
Dup of #28101.
