### ISSUE TITLE
cmd/go: document that go run supports dir/pkg 

### ISSUE THREAD

**Issue by DmitriyMV** [golang/go#30195]
Francesc Campoy (@campoy) in his [talk](https://speakerdeck.com/campoy/the-state-of-go-feb-2019?slide=26) mentions that Go 1.12 now supports running `go run` on directories and packages. But I didn't find any mentions of it in `tip` release notes. Maybe it should be added there?

**Comment by mvdan** [comment]
https://golang.org/doc/go1.11#run?

Also see:

```
$ go1 version
go version go1.11.5 linux/amd64
$ go1 help run
usage: go run [build flags] [-exec xprog] package [arguments...]

Run compiles and runs the named main Go package.
Typically the package is specified as a list of .go source files,
but it may also be an import path, file system path, or pattern
matching a single known package, as in 'go run .' or 'go run my/cmd'.

[...]
```

**Comment by DmitriyMV** [comment]
Oh. My bad!
