### ISSUE TITLE
x/mobile: some .aar's import and build in android studio but some dont

### ISSUE THREAD

**Issue by mandelmonkey** [golang/go#30192]
### What version of Go are you using (`go version`)?

<pre>
go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/a/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/a/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nv/r_25ssyx3k70hy55hrzghc2c0000gn/T/go-build837618377=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

ran "$GOPATH/bin/gomobile" bind -target=android -tags="android" -v -o "$android_dest" "$package"
and imported the .aar into Android Studio

### What did you expect to see?
Should be able to import via
```
File ➤New ➤New Module ➤Import .JAR or .AAR package
File ➤Project Structure ➤app ➤Dependencies ➤Add Module Dependency

```
Should be able to build

### What did you see instead?
Import did not show as a module but managed to hack by manually importing
After that project fails to build in android studio

```
Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :lndmobile.
 "Unable to resolve dependency for &#39;:app@debug/compileClasspath&#39;: Could not resolve project :lndmobile. 
```

Tried with a basic Hello World gomobile bind and it worked as expected however building this golang app returns the errors above

https://github.com/lightningnetwork/lnd

Here are the tail of the build logs
```
jar: lndmobile/Callback.class
jar: lndmobile/Lndmobile$proxyCallback.class
jar: lndmobile/Lndmobile$proxySendStream.class
jar: lndmobile/Lndmobile.class
jar: lndmobile/SendStream.class
aar: jni/armeabi-v7a/libgojni.so
aar: jni/arm64-v8a/libgojni.so
aar: jni/x86/libgojni.so
aar: jni/x86_64/libgojni.so
aar: R.txt
aar: res/
jar: META-INF/MANIFEST.MF
jar: go/LoadJNI.java
jar: go/Seq.java
jar: go/Universe.java
jar: go/error.java
jar: lndmobile/Callback.java
jar: lndmobile/Lndmobile.java
jar: lndmobile/SendStream.java
```

**Comment by taybart** [comment]
Are you including more than one "class" in this build? I have had weird stuff happen when there is more than one package in the bind.

**Comment by mandelmonkey** [comment]
Well its it no my go app that im building but yes I think it does, looking at the classes.jar file
it has the three classes
jar: lndmobile/Callback.java
jar: lndmobile/Lndmobile.java
jar: lndmobile/SendStream.java

should this be an issue?

**Comment by taybart** [comment]
I would try to boil it down to one and see if that fixes the issue. I think that is a problem but, isolating the issue helps to fix it.

**Comment by mandelmonkey** [comment]
Ill try that, any ideas why gomobile would add multiple classes instead of
just one?

**Comment by taybart** [comment]
Without seeing the code I couldn't tell you, any type that you export can potentially have its own class.

**Comment by bcmills** [comment]
CC @eliasnaur @hyangah

**Comment by eliasnaur** [comment]
What is the exact gomobile command you use? Does it work in a gradle project where you manually add the dependency? For example, you could try to use the "example" project with your .aar file instead of the hello.aar.

**Comment by mandelmonkey** [comment]
@eliasnaur thanks for the reply, I got a new macbook and installed everything from scratch and seems to work now, so im putting it down to do my old macs environment, maybe android sdk wasnt set up correctly
