### ISSUE TITLE
doc: "go tool vet" still mentioned in various parts of documentation

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30199]
In Go 1.12, "go tool vet" is [no longer supported](https://tip.golang.org/doc/go1.12#vet):

>  External tools that use `go tool vet` must be changed to use `go vet`.

However, there are places in the documentation where `go tool vet` is still mentioned as a way of running vet. I'm currently finding two instances:

- https://github.com/golang/go/blob/c75ee696c341cef94b00409b3692f3df82af1c71/doc/install-source.html#L384

- https://github.com/golang/go/blob/c75ee696c341cef94b00409b3692f3df82af1c71/doc/cmd.html#L20-L24

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Well spotted.
