### ISSUE TITLE
syscall/js: no method to convert TypedArrays into slices

### ISSUE THREAD

**Issue by superp00t** [golang/go#30210]
You can convert a Go slice into a TypedArray by using `js.TypedArrayOf(...)`, but there is apparently no way of doing the reverse operation.

You can write a function to `Index()` every byte value in an ArrayBuffer and put them in a byte slice, but this is cumbersome and incurs unacceptable overhead. There should be a function to directly copy the bytes into the Go heap, such as what `js.Value.String()` does.

**Comment by neelance** [comment]
WebAssembly is only able to access typed arrays which are backed by WebAssembly's memory. This does not hold for all typed arrays, so a mapping with direct access to the typed array is not possible. The best solution is to allocate a correctly sized byte slice in Go, pass it to JS with `TypedArrayOf` and then use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set to quickly copy all bytes.

**Comment by superp00t** [comment]
@neelance Thanks a lot, doing that solved my problem.

**Comment by bradfitz** [comment]
I added metadata to this CL before I read the final comment which makes it sounds like this bug is resolved. So, closing. Correct me if that's wrong.
