### ISSUE TITLE
mime/multipart: CreateFormFile defaults content-type to application/octet-stream

### ISSUE THREAD

**Issue by melissafzhang** [golang/go#30218]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.11.5

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/melissazhang/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/melissazhang/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/melissazhang/src/babel-fish/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bx/54d6qfbs7g19jps4b60rnkq00000gp/T/go-build334342869=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
[createFormFile](https://github.com/golang/go/blob/master/src/mime/multipart/writer.go#L145) always defaults content type to application/octet-stream which is not always the case.  

### What did you expect to see?
Should allow you to customize or it should detect the content type

### What did you see instead?
Defaults to application/octet-stream

**Comment by ianlancetaylor** [comment]
You can use `CreatePart` which lets you customize it however you like.  `CreateFormField` is a convenience function.  (And I don't see where `CreateFormField` sets the `Content-Type` at all.)

**Comment by melissafzhang** [comment]
@ianlancetaylor this is where content-type is set https://github.com/golang/go/blob/master/src/mime/multipart/writer.go#L145

**Comment by ianlancetaylor** [comment]
That is `CreateFormFile`.  You filed this bug against `CreateFormField`.

**Comment by melissafzhang** [comment]
@ianlancetaylor nice catch! updated

**Comment by ianlancetaylor** [comment]
OK.  But it's still true that `CreateFormFile` is just a simple wrapper around `CreatePart`.  We can't really change `CreateFormFile` without breaking the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).

**Comment by bradfitz** [comment]
Yeah, I agree with Ian. We can't break compatibility and it's already possible to set other content-types with the other methods.
