### ISSUE TITLE
cmd/go: GOOS=android requires explicitly setting CGO_ENABLED=1

### ISSUE THREAD

**Issue by saleemrashid** [golang/go#30216]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ GOOS=android GOARCH=arm GOARM=7 CC=arm-linux-androideabi-gcc CXX=false go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/saleem/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="android"
GOPATH="/home/saleem/.local/lib/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="7"
CC="arm-linux-androideabi-gcc"
CXX="false"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build669201380=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, World!")
}
```

### What did you expect to see?

The command should succeed without explicitly setting `CGO_ENABLED=1`

### What did you see instead?

Without explicitly setting `CGO_ENABLED` (`go env` shows it defaults to `CGO_ENABLED=0`)

<pre>
$ GOOS=android GOARCH=arm GOARM=7 CC=arm-linux-androideabi-gcc CXX=false go build
/usr/lib/go/pkg/tool/linux_amd64/link: running arm-linux-androideabi-gcc failed: exit status 1
/tmp/go-link-934544495/go.o:go.go:_cgo_init: error: undefined reference to 'x_cgo_init'
/tmp/go-link-934544495/go.o:go.go:_cgo_notify_runtime_init_done: error: undefined reference to 'x_cgo_notify_runtime_init_done'
/tmp/go-link-934544495/go.o:go.go:_cgo_thread_start: error: undefined reference to 'x_cgo_thread_start'
/tmp/go-link-934544495/go.o:go.go:runtime._cgo_setenv: error: undefined reference to 'x_cgo_setenv'
/tmp/go-link-934544495/go.o:go.go:runtime._cgo_unsetenv: error: undefined reference to 'x_cgo_unsetenv'
/tmp/go-link-934544495/go.o:go.go:runtime.cgo_yield: error: undefined reference to '_cgo_yield'
collect2: error: ld returned 1 exit status

</pre>

Explicitly setting `CGO_ENABLED=1` leads to a successful build

<pre>
$ GOOS=android GOARCH=arm GOARM=7 CC=arm-linux-androideabi-gcc CXX=false CGO_ENABLED=1 go build
$ 
</pre>

**Comment by saleemrashid** [comment]
See also #25963

**Comment by bcmills** [comment]
CC @eliasnaur @ianlancetaylor

**Comment by eliasnaur** [comment]
The go tool disables CGO_ENABLED when cross-compiling:
```
$ go env CGO_ENABLED
1
$ GOOS=android go env CGO_ENABLED
0
```

I suppose we could keep CGO_ENABLED when CC or CXX is set?

**Comment by ianlancetaylor** [comment]
It would be nice to figure out when we can safely set `CGO_ENABLED`, but I'm not sure it should be simply because `CC` is set.  We have a corresponding set of bug reports from people who set `CC` to the wrong compiler.  But I don't have a better suggestion.

**Comment by eliasnaur** [comment]
How about keeping CGO_ENABLED for geese that don't support internal linking?

**Comment by rsc** [comment]
We have a very simple rule right now: cgo is disabled for _all_ cross-compiles. We should probably keep that simple rule. People building for Android have needed to set CGO_ENABLED from the start, and they seem to be coping just fine.
