### ISSUE TITLE
spec: should octal escape sequences in string literals accept an "o" prefix?

### ISSUE THREAD

**Issue by josharian** [golang/go#30225]
This is a minor follow-up to #19308; I've started a new issue since that one is long, and this is a corner case.

In the [String literals](https://golang.org/ref/spec#String_literals) section, the spec says:

> The three-digit octal (\nnn) and two-digit hexadecimal (\xnn) escapes represent individual bytes of the resulting string [...] inside a string literal \377 and \xFF represent a single byte of value 0xFF=255

Given that we are moving towards using `0o` for octal integers, and given that hexadecimal escaping in string literals begins `\x`, should string literals also accept a `\o` prefix for octal bytes?

I suspect that so few people use octal byte escape sequences in string literals that it's not worth changing for consistency, but I thought it worth making an explicit decision about.

cc @griesemer @rsc @ianlancetaylor

**Comment by robpike** [comment]
I can't remember even seeing an octal string escape in the while. Everyone uses \x or \u. I don't think it's worthwhile. String literals are complicated enough already.

**Comment by griesemer** [comment]
Agreed. I don't think we should touch string and rune escapes.

**Comment by josharian** [comment]
Great. I'll call this decided; thanks.

**Comment by ianlancetaylor** [comment]
To the best of my knowledge and research ability the only languages that support a string literal octal escape of the form "\oDDD" are Perl (in the form \o{DDD}) and Haskell. Languages like Rust and Swift don't even support the form \DDD that we copied from C, and only support hex (Rust) and Unicode (Rust and Swift) escapes. So I don't see much reason to add "\oDDD" to Go.
