### ISSUE TITLE
x/sys/cpu: cpu_arm64.go:39:22: undefined: HWCap

### ISSUE THREAD

**Issue by karalabe** [golang/go#30237]
We've been hitting compilation issues on iOS arm64 for the past few months. I've just upgraded to the latest code today, but builders are failing with `golang.org/x/sys/cpu/cpu_arm64.go:39:22: undefined: HWCap`. Could anyone look into this?

https://travis-ci.org/ethereum/go-ethereum/jobs/493330332#L1207

**Comment by AlexRouSg** [comment]
Looks like `golang.org/x/sys/cpu` currently only supports Linux on non x86 processors. 

ping @tklauser

**Comment by karalabe** [comment]
Thank you, builders are green again!
