### ISSUE TITLE
cmd/compile: 0.01i != complex(0, 0.01) at compile time

### ISSUE THREAD

**Issue by griesemer** [golang/go#30243]
https://play.golang.org/p/J7WmCozLr4T

Despite the inexact representation of 0.01, both 0.01i and complex(0, 0.01i) should do the same inexact computations. I would expect the compile time comparison to evaluate to true (complex() of compile-time constants returns a compile-time constant, too).

Instead there is a difference of -2.032879e-022i when subtracting the numbers.

Investigate.

(Assigning to me so I don't forget this, but anyone else is welcome to pick this up.)

**Comment by cherrymui** [comment]
FWIW, gccgo evaluates this to true.

**Comment by dpinela** [comment]
`imag(0.01i) - 0.01` evaluates to -2.032879e-022i, as well.
