### ISSUE TITLE
crypto/sha256: memory leak or issue with heap profiler

### ISSUE THREAD

**Issue by ebuchman** [golang/go#30249]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (1.11.5)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

</pre></details>

### What did you do?

```
package main

import (
	"crypto/sha256"
	"fmt"
	"net/http"
	_ "net/http/pprof"
	"runtime"
)

func main() {
	runtime.MemProfileRate = 1
	myFunc()
	runtime.GC()
	fmt.Println(http.ListenAndServe("localhost:7070", nil))
}

func myFunc() {
	sha256.New()
}
```

Then check heap profile: http://localhost:7070/debug/pprof/heap?debug=1

### What did you expect to see?

No entry for `myFunc`

### What did you see instead?

```
0: 0 [1: 128] @ 0x107563d 0x1300102 0x1300061 0x102ee57 0x105ca71
#	0x107563c	crypto/sha256.New+0x2c	/Users/myuser/goRoot/1.11.5/src/crypto/sha256/sha256.go:181
#	0x1300101	main.myFunc+0x21	/Users/myuser/goApps/src/github.com/tendermint/tendermint/pprof/main.go:19
#	0x1300060	main.main+0x30		/Users/myuser/goApps/src/github.com/tendermint/tendermint/pprof/main.go:13
#	0x102ee56	runtime.main+0x206	/Users/myuser/goRoot/1.11.5/src/runtime/proc.go:201
```

Note this issue also holds for sha512, but not for sha1, and not for ripemd160 from x/crypto

**Comment by odeke-em** [comment]
Thank you for filing this issue @ebuchman and welcome to the Go project!

I shall kindly page some runtime folks to take a look: /cc @RLH @aclements

**Comment by davecheney** [comment]
@ebuchman `sha256.New` returns a value boxed inside a `hash.Hash` interface. The value allocated by `sha256.New` has escaped to the heap -- you can verify that with `go build -gcflags=-m`

Why did you expect this code to not allocate a value on the heap? Is it because you are not using the result from `sha256.New`?

**Comment by FiloSottile** [comment]
The confusion might be due to the fact that the heap profile raw format includes all allocated values, live and collected. To see if it's still live after GC, use `go tool pprof -inuse_objects`.

**Comment by rsc** [comment]
There's no leak here. Run this in a loop and you will see that the heap is not growing. The "0: 0" in the raw format means there are none of them live now.
