### ISSUE TITLE
x/tools/cmd/godoc: url flag's response recorder ignores body

### ISSUE THREAD

**Issue by rhysh** [golang/go#30261]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +701f6a27b5 Mon Feb 11 18:18:45 2019 +0000 darwin/amd64
</pre>

I'm comparing the x/tools repo at `release-branch.go1.11` vs `release-branch.go1.12`.

### Does this issue reproduce with the latest release?

Yes, this is broken in `master` of the x/tools repo.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rhys/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rhys/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/zmds5zsn75z1283vtzxyfr5hj7yjq4/T/go-build329945537=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
$ go run golang.org/x/tools/cmd/godoc -url=/ -http=""
```

### What did you expect to see?

I expected to see HTML similar to what's served by the root of https://golang.org/

### What did you see instead?

The command returned no output.

---

I have a fix for this, including regression tests. I'll upload it shortly.

**Comment by dmitshur** [comment]
This is a regression from [CL 141417](https://golang.org/cl/141417), where the `httptest. ResponseRecorder` type was replaced with a custom implementation in order to fix #28138. It wasn't caught because we didn't have a test for the -url flag yet (we will after your CL, thanks for that).

**Comment by rhysh** [comment]
@gopherbot please backport to 1.12
