### ISSUE TITLE
x/net/nettest: Conn.SetDeadline doc comment and test comment conflict

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#30275]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

this is related to documentation

`net.Conn.setDeadline` says:
```
The deadline applies to all future and pending I/O, 
not just the immediately following call to ReadFrom 
or WriteTo
```

This means I can extend previously set deadline to longer period.

but when i look at `nettest.testPresentTimeout` it says:
```
testPresentTimeout tests that a deadline set while there are pending
Read and Write operations immediately times out those operations.
```

if so, `net.Conn.SetDeadline` should say that:
changing timeout will cause any pending I/O calls to timeout

By looking at `nettest.testPresentTimeout` code, I see that it is not extending current deadline. so
test is correct but its doc is wrong. I tried to see if there is any test, which tests extending deadline of 
pending IO, but could not find

for clarification, i checked `net.Pipe` implementation:

any pending `net.pipe.Read` will always timeout on `setDeadline`
any pending `net.pipe.Write` may sometimes timeout on `setDeadline` and sometime not (if `setDeadline` called between for loop iterations

**Comment by mikioh** [comment]
@santhosh-tekuri,

Can you please confirm that the docs you are suggesting are really for the net.Conn interface instead of net.PacketConn interface.

**Comment by santhosh-tekuri** [comment]
what I am suggesting is to correct doc of `nettest.testPresentTimeout`. 
I know it is not part of public api, But who is digging into std lib, this doc comment can confuse

**Comment by santhosh-tekuri** [comment]
the doc of `nettest.testPresentTimeout` should say something like:
```
testPresentTimeout tests that a  past deadline set while there are pending
Read and Write operations immediately times out those operations.
```

**Comment by mikioh** [comment]
Then, feel free to send a CL; the target package is https://godoc.org/github.com/golang/net/nettest.
