### ISSUE TITLE
access: approvers + may-start-trybots

### ISSUE THREAD

**Issue by agnivade** [golang/go#30297]
See https://golang.org/wiki/GerritAccess

Approvers - https://go-review.googlesource.com/#/admin/groups/1005,members
Trybots - https://go-review.googlesource.com/#/admin/groups/1030,members

My gerrit contributions - https://go-review.googlesource.com/q/owner:agniva.quicksilver%2540gmail.com+status:merged

In the past, there have been several occasions where I had to ping a reviewer to merge a CL which had been already approved. This is likely, since the reviewer might have moved on to other reviews after approving a CL. Having access to the merge bit will help me quicken this process and not waste yet another cycle of sending a reminder mail just to merge a CL.

Apart from this, I have been steadily contributing to godoc and go/doc. Having trybots and +2 access will let me triage and review those CLs properly.

Lastly, I would also like to garden the CLs (adding proper hashtags, abandoning a CL which has been discontinued). I believe having +2 access allows one to do this.

I hope my contributions to the Go project since the past couple of years is sufficient to approve this request. Thank you.

/cc @bradfitz @andybons

**Comment by bradfitz** [comment]
Done. Use your new powers responsibly, ask if you have any questions, etc. </standard speech>

Thanks for your continued contributions!

**Comment by agnivade** [comment]
Thanks !
