### ISSUE TITLE
http_proxy contains \r causes proxy error!

### ISSUE THREAD

**Issue by QianChenglong** [golang/go#30293]
Get by proxy issue an error:
![image](https://user-images.githubusercontent.com/1881126/52941271-5af1e980-33a3-11e9-8539-7c783beec74e.png)

![image](https://user-images.githubusercontent.com/1881126/52941259-52011800-33a3-11e9-926c-1b6811fa681c.png)

Find in proxy.go，parses http_proxy incorrectly when http_proxy contains \r\n(Win7)：
![image](https://user-images.githubusercontent.com/1881126/52941499-ef5c4c00-33a3-11e9-8a24-b982dabdf3cd.png)
![image](https://user-images.githubusercontent.com/1881126/52941167-2120e300-33a3-11e9-906d-a6885b0936d0.png)

**Comment by mvdan** [comment]
Please don't paste screenshots, and give a short self-contained program that reproduces this issue.

Assuming you mean the `HTTP_PROXY` environment variable, why would its value even contain a `\r` character?

**Comment by j2gg0s** [comment]
Characters that are allowed in a URI but do not have a reserved 
purpose are called unreserved.  These include uppercase and lowercase 
letters, decimal digits, hyphen, period, underscore, and tilde.

**Comment by bradfitz** [comment]
How did `\r\n` get into your environment variable? Seems like that's the bigger problem.

In any case, this is fixed in Go 1.12 (in that we return a more explicit error earlier) and backported on the Go 1.11 and Go 1.10 branches, though we haven't cut new releases of those yet.

Closing as nothing to do, unless we hear otherwise.

**Comment by QianChenglong** [comment]
I use the [rapidee](http://www.rapidee.com/) to manage my windows env.I copy that env setting from other.In rapidee, can't see any different！
I known the URI contains `\r\n` is invalid.But for robustness, program should not trust any user input .

**Comment by mvdan** [comment]
The `HTTP_PROXY` environment variable should be used as-is. If you're getting newlines in there, you'll have problems with lots of software. You should file a bug with the software that added the newlines.
