### ISSUE TITLE
Crash with STATUS_STACK_BUFFER_OVERRUN on nil pointer dereference (windows)

### ISSUE THREAD

**Issue by 0xd34d10cc** [golang/go#30319]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\d34d10cc\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\development\gopath
set GOPROXY=
set GORACE=
set GOROOT=D:\development\go
set GOTMPDIR=
set GOTOOLDIR=D:\development\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\d34d10cc\AppData\Local\Temp\go-build060979054=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I ran this program:
```
package main

import "log"
import "os"


func main() {
        type Point struct {
                x int
                y int
        }

        var p *Point = nil

        l := log.New(os.Stderr, "", 0)
        l.Println("log msg")

        log.Printf("%v", p.x)
}
```
with `go run main.go` command

### What did you expect to see?
Panic message

### What did you see instead?
```
$ go run ./main.go
log msg
exit status 3221226505
```

**Comment by 0xd34d10cc** [comment]
Disabling CFG (control flow graph) in windows defender settings "resolves" this problem. Not sure where the bug is - in windows defender or in go, or if "bug" even exist. Feel free to close this issue.

**Comment by ianlancetaylor** [comment]
Thanks for following up.  Closing.
