### ISSUE TITLE
fmt: Change (*pp).fmtBool to (*pp).fmtBoolean for consistency

### ISSUE THREAD

**Issue by tomocy** [golang/go#30312]
at fmt/print.go:652
```go
case bool:
    p.fmtBool(f, verb)
```

but seeing the blow, `(*pp).fmtInteger` (not `(*pp).fmtInt`) is found.
So considering the consistency, `(*pp).fmtBool` should be renamed `(*pp).fmtBoolean`

What do you think?

**Comment by ianlancetaylor** [comment]
Thanks, but I don't think it's worth changing.  `fmtInt` is potentially confusing in that it suggests that it only works for the `int` type, whereas of course it works for any integer type.  `fmtBool`, on the other hand, really does work only for the `bool` type.

Also, more generally, there's not much benefit to making minor changes to working code.  It can only break things.  Of course where the code is really unclear it is a good idea to rewrite it to make it easier to understand.  But that is not the case here.
