### ISSUE TITLE
x/crypto/blake2b

### ISSUE THREAD

**Issue by danielhavir** [golang/go#30315]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
macOS HighSierra 10.13.6

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/daniel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
...
</pre></details>

### What did you do?
Use Blake2b as MAC:
https://play.golang.org/p/S0bPQfHgG5K

### What did you expect to see?
Different tags for different messages with a single key.

### What did you see instead?
Same tags for different messages with a single key

**Comment by FiloSottile** [comment]
`Sum` does not take the message as argument, it takes a slice to append the result to. See the `hash.Hash` docs.
