### ISSUE TITLE
proposal: x/net/dns/dnstest: new package and refurbish test cases in net

### ISSUE THREAD

**Issue by mikioh** [golang/go#30323]
This is a proposal to make a package containing helpers for DNS stub resolver testing and to refurbish the DNS test cases in the package net of the standard library, the same as #13295.

Problem: For historical reasons, the package net hasn't been had self-contained, functional test cases for the built-in DNS stub resolver. As a consequence, it has become a normal situation that people modify the code, pray for the luck and face regressions and neglected issues.

Solution: To have enough functional test cases with the support of the dnstest package. The package dnstest implements DNS zone information parsers, DNS transport mocks and DNS recursive server mocks to help construct a bit complicated test cases without relying on external resources, as in, "traverse a tree, stop with NXDOMAIN or transport failure, and return a correct set of records with an appropriate error value even if it's a single name query with multiple concurrent racers; note that the circumstances have a middlebox that throttles concurrent DNS queries to the same name and operate split DNS: some recursive servers are for internal, others are for external and the others are for both."

**Comment by rsc** [comment]
A package named x/net/dns/dnstest seems fine but you haven't said what the API will be. What is the expected API?
