### ISSUE TITLE
time: Weird behavior with RFC3339 parser

### ISSUE THREAD

**Issue by mcandre** [golang/go#30341]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tkmamhf/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tkmamhf/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/tkmamhf/.gvm/gos/go1.11"
GOTMPDIR=""
GOTOOLDIR="/Users/tkmamhf/.gvm/gos/go1.11/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y6/dbk1vvs179nbpfv38j__10b5rsnf87/T/go-build068103498=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am trying to parse some RFC3339 timestamps like `"2020-04-01T12:00:00Z"` with the `time` package.

### What did you expect to see?

Nil error.

### What did you see instead?

The RFC3339 parse string appears to reject zero-valued timezone suffixes `00:00`

### Workaround

I am carefully stripping zero-valued timezone suffixes prior to using `time.Parse()`

**Comment by antong** [comment]
@mcandre , could you provide a minimal example of code that produces the error, preferably as a playground link like https://play.golang.org/p/Biopib2o853, and tell what the actual error you got?

**Comment by iWdGo** [comment]
Details of this issue are probably in #20555 and the error message is as the included [example](https://github.com/golang/go/blob/2396101e0590cb7d77556924249c26af0ccd9eff/src/time/example_test.go#L346) mentions.
