### ISSUE TITLE
lib/pq seems to have data corrupted between calls to scan https://github.com/lib/pq/issues/831

### ISSUE THREAD

**Issue by nlacey** [golang/go#30356]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.11.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> 
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nlacey/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nlacey/gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build255173950=/tmp/go-build -gno-record-gcc-switches"
</summary><br><pre>
</pre></details>

### What did you do?

[test.go.txt](https://github.com/golang/go/files/2895451/test.go.txt)
[table.sql.txt](https://github.com/golang/go/files/2895452/table.sql.txt)

I can use results of an empty interface and sql.RawBytes (as long as I don't call scan again)
Once I call scan again, it seems to some how corrupt the data from the previous call?
Even though I create bran new data for everything.

(Notice the simple string isn't corrupted, but the json data and uuid is)

test.go.txt
table.sql.txt

//create simple test table
CREATE TABLE IF NOT EXISTS test (
id uuid DEFAULT public.uuid_generate_v1() NOT NULL,
name text NOT NULL,
groups text[] NOT NULL,
jsonData jsonb NOT NULL,
PRIMARY KEY (id)
);

insert into test (name,groups,jsonData) values ('hi', array['hello'], '{"test":"s", "b":"c"}');
insert into test (name,groups,jsonData) values ('by', array['gone'], '{"test":"a", "b":"d"}');

package main

import (
"database/sql"
"fmt"

_ "github.com/lib/pq"

)

func main() {
db, err := sql.Open("postgres", "user=postgres")
if err != nil {
fmt.Printf("Invalid postgres connection string")
return
}

if err = db.Ping(); err != nil {
	fmt.Printf("Unable to establish connection to postgresql %+v", err)
	return
}

rows, err := db.Query("select id, name,groups,jsonData from test;")
if err != nil {
	fmt.Printf("Unable to perform query %+v", err)
	return
}

output := make([][]interface{}, 0)

for rows.Next() {
	fmt.Println("Reading record")
	tmpRow := make([]interface{}, 4)
	for index := range tmpRow {
		tmpRow[index] = new(sql.RawBytes)
	}

	err := rows.Scan(tmpRow...)
	if err != nil {
		return
	}

	//Print object inside for loop
	for _, item := range tmpRow {
		fmt.Printf("\tinside loop item = %s  \n", item)
	}

	//Add current record to batch array
	output = append(output, tmpRow)
}

err = rows.Close()
if err != nil {
	fmt.Printf("error closing row %+v", err)
}

err = db.Close()
if err != nil {
	fmt.Printf("error db close %+v", err)
}

//Print object outside for loop
fmt.Println("outside loop items")
for _, dbRow := range output {
	fmt.Printf("\n**records***\n")
	for _, item := range dbRow {
		fmt.Printf("\t %s", item)
	}
}
fmt.Printf("\n Notice uuid, []text, and jsonb data are all corrumpted\n")

}

Output

Reading record
inside loop item = &b5d5cd04-36d1-11e9-a412-08002707b10f
inside loop item = &hi
inside loop item = &{hello}
inside loop item = &{"b": "c", "test": "s"}
Reading record
inside loop item = &c4cd3a0e-36d1-11e9-a412-08002707b10f
inside loop item = &by
inside loop item = &{gone}
inside loop item = &{"b": "d", "test": "a"}
outside loop items

records*
& 2d3a0e-36d1-11e9-a412-08002707b10f &hi &{gone} &"b": "d", "test": "a"}}
records*
& 2d3a0e-36d1-11e9-a412-08002707b10f &by &{gone} &{"b": "d", "test": "a"}
Notice uuid, []text, and jsonb data are all corrumpted

### What did you expect to see?
I've used identical code for simple object types, but for []string or jsonb types it gets corrupted.

### What did you see instead?

I expected the object I stored in an array to be the same after the second call to scan.

-----------------

This may well be a bug in lib/pq?  I've created a ticket there too, but I want to cover my bases just in case this turns into some kind of language bug (garbage collection?).

Thanks!

**Comment by antong** [comment]
The [documentation](https://godoc.org/database/sql#RawBytes) says:

> RawBytes is a byte slice that holds a reference to memory owned by the database itself. After a Scan into a RawBytes, the slice is only valid until the next call to Next, Scan, or Close.

You can copy the values if you need to keep the data.

**Comment by dmitshur** [comment]
> This may well be a bug in lib/pq? I've created a ticket there too, but I want to cover my bases just in case this turns into some kind of language bug (garbage collection?).

It's hard to investigate whether this is a bug in language without a smaller, reproducible test case.

Let's wait on the outcome of lib/pq#831. If it turns out to be a bug in the Go compiler or runtime, we can re-open this issue with more relevant information.

**Comment by nlacey** [comment]
Thanks for the help! How do I copy the value?
I tried the following
func cloneArrayInterface(input []interface{}) []interface{} {
    output := make([]interface{}, len(input))
    for index, val := range input {
        b, ok := val.([]byte)
        if ok {
            c := make([]byte, len(b))
            copy(c, b)
            output[index] = c
        } else {
            fmt.Println("failed to cast")
        }
    }
    return output
}


But I just get a mess of failed to cast?

Thanks

**Comment by nlacey** [comment]
This appear to work for cloning the rawbytes data

func cloneArrayInterface(input []interface{}) []interface{} {
	fmt.Println("cloneArrayInterface, ", len(input))
	output := make([]interface{}, len(input))
	for index, val := range input {
		b, ok := val.(*sql.RawBytes)
		if ok {
			c := make([]byte, len(*b))
			copy(c, *b)
			output[index] = c
		}
	}
	return output
}
