### ISSUE TITLE
encoding/json: Compact escapes U+2028 and U+2029

### ISSUE THREAD

**Issue by PhilipBorgesen** [golang/go#30357]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

https://play.golang.org/p/XvnF676cmhY

### What did you expect to see?

I expected json.Compact to only elide insignificant whitespace as documented, in this case outputting the input untouched.

### What did you see instead?

json.Compact escaped U+2028 and U+2029 inside the string, causing the output to be less compact than the input.

The cause appears to be on line 31 of indent.go (https://golang.org/src/encoding/json/indent.go?s=736:1005#L11) where the escape parameter is missing as a branch condition.

**Comment by dmitshur** [comment]
This may be related to #5836, a security issue, which was fixed by escaping these 2 characters in https://github.com/golang/go/commit/d754647963d41bcd96ea4d12d824f01e8c50f076.

**Comment by PhilipBorgesen** [comment]
It definitively is related; I will argue that escaping Compact input was unintended though.
If Compact were meant to transform the input in this surprising way I would have expected the Indent function to showcase the same behavior, which is not the case:

https://play.golang.org/p/JAydUaEnVwB

I would also have expected that the documentation for Compact would have been updated as it was for HTMLEscape but that neither happened.

**Comment by dmitshur** [comment]
Would you like to reopen this issue, so that it can be investigated?

**Comment by PhilipBorgesen** [comment]
Hi dmitshur

I think I accidentially tapped “Close and comment” instead of “Comment”. I did not mean to close the issue.

Sorry for the inconvenience, I want the issue to be investigated.

**Comment by bcmills** [comment]
CC @rsc @dsnet @bradfitz @mvdan for `encoding/json`.

(Note also https://github.com/tc39/proposal-json-superset, which may mitigate some of the concerns relating to #5836.)

**Comment by bradfitz** [comment]
Perhaps we just add a package comment to encoding/json that says, effectively, that "whenever we say JSON we actually mean JSON that's also valid JavaScript". Then Compact's docs would be correct.

Does that work?

Because I think this is really a documentation omission if anything. I don't think we want to change behavior here.

**Comment by PhilipBorgesen** [comment]
@bradfitz: If we go with such wording as a package comment I would expect Compact to return an error, not to alter the contents silently.

Why do we want Compact to perform this additional escaping? Is it not the purpose and responsibility of the HTMLEscape function?
