### ISSUE TITLE
need information on using a library package that has vendored its dependencies

### ISSUE THREAD

**Issue by vigneshkm** [golang/go#30364]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.9.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Did not check as `vendor` feature is available in my go version (`go1.9.2`) and I just need info about it

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vignesh/go-book/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build956235701=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?
I am having my project at directory `A`, which uses a package from project `B`. Both projects `A` and `B` are accessible through `GOPATH`. Project `B` has vendored some dependencies say package `C` in its vendor directory. 

`B` has an API say `B.Api(param C.Cx)`. The package `C` is vendored by `B`. So, while invoking `B.Api()` from `A`, I got `cannot find package` compilation error. I then moved all the packages vendored by `B` to  `A`'s vendor directory, but then got another compilation error ` cannot use "A.C" literal (type "A.C") as type "B.C" in field value`

To be more precise on my packages A,B and C, A is my project, B is dockers SDK API's for GO and C is  a package vendored by Docker. You could find my code, compilation errors and issue description at 
[https://github.com/moby/moby/issues/38764] , which I had raised before raising the query here.

### What did you expect to see?
package A being able to use package B with its vendored dependencies.

### What did you see instead?
compilation errors

**Comment by bcmills** [comment]
Per the [release policy](https://golang.org/doc/devel/release.html#policy), `go1.9.2` has not been supported for quite some time.

----

That said, this is a fundamental problem with the use of per-package `vendor` directories: vendored packages are rarely vendored at the same version, so we must treat each vendored copy as its own distinct package with a distinct set of types.

This is one of the problems we hope to address with modules: in module mode, the main module computes the version to use for each dependency, and then every package sees that version consistently, so every import path seen in the program indicates one (and only one!) version of the package.
