### ISSUE TITLE
x/perf/benchstat: add -metrics=speed,alloc/op flag

### ISSUE THREAD

**Issue by nigeltao** [golang/go#30368]
`benchstat` reports a number of metrics:
- alloc/op
- speed
- time/GC
- time/op

In my automated reports, I'm only interested in a subset of those, even if the underlying source files provide more than that.

Would you (@aclements) accept a patch so that I can say `benchstat -metrics=speed,alloc/op`?

Right now, I can workaround it with piping `benchstat`'s output through `sed`. It's not that onerous, but if others might find it useful, it's possibly a little cleaner to do it in `benchstat` itself.

**Comment by bcmills** [comment]
CC @josharian

**Comment by josharian** [comment]
Sounds fine to me, but I think this is Austin's call.
