### ISSUE TITLE
Rearrange Go source code according to go mod way

### ISSUE THREAD

**Issue by Allenyn** [golang/go#30375]
Like the title. Rearrange go source codes,  manage by modules

**Comment by mdlayher** [comment]
To clarify, do you mean that the source code of the standard library should be rearranged as Go modules would expect?

I haven't done much work with modules yet, so I'm not sure if this request is reasonable or not, and will defer to the expertise of others.

**Comment by cyantarek** [comment]
Can you elaborate a little bit?

**Comment by agnivade** [comment]
Dup of https://github.com/golang/go/issues/30241 ?

**Comment by Allenyn** [comment]
@mdlayher Yes. I mean "the source code of the standard library should be rearranged as Go modules".

**Comment by Allenyn** [comment]
ok



    


            On 02/25/2019 02:13, Agniva De Sarker wrote: Dup of #30241 ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/golang/go","title":"golang/go","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/golang/go"}},"updates":{"snippets":[{"icon":"PERSON","message":"@agnivade in #30375: Dup of https://github.com/golang/go/issues/30241 ? "}],"action":{"name":"View Issue","url":"https://github.com/golang/go/issues/30375#issuecomment-466801141"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/golang/go/issues/30375#issuecomment-466801141",
"url": "https://github.com/golang/go/issues/30375#issuecomment-466801141",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bcmills** [comment]
> Dup of #30241 ?

Agreed. We might not do the full upgrade behavior of that proposal, but I expect that we'll at least have modules for `std` and `cmd`.
