### ISSUE TITLE
x/website: add a link to Creative Commons Attribution 3.0 License

### ISSUE THREAD

**Issue by perillo** [golang/go#30371]
Currently, the license for documents in `content/static/godoc.html` and `internal/dl/tmpl.go` is in plain text.  I think it should be a link to the license definition, e.g.
https://creativecommons.org/licenses/by/3.0/.

**Comment by dmitshur** [comment]
It's linked in the [README](https://github.com/golang/go/blob/73b803ee532173f64a5d3fb2cd0fbe789d49571e/README.md) and at https://developers.google.com/terms/site-policies#restrictions, so it seems reasonable to link in the footer too.

**Comment by bcmills** [comment]
CC @cnoellekb

**Comment by rhnvrm** [comment]
I would like to take up this issue.

**Comment by dmitshur** [comment]
@rhnvrm Feel free to send a change to the x/website repo. If it's your first time contributing, read over the [Contribution Guide](https://golang.org/doc/contribute.html) for information.

**Comment by rhnvrm** [comment]
@bradfitz @agnivade, thank you for reviewing!
