### ISSUE TITLE
Divide Float64(0) output Inf+

### ISSUE THREAD

**Issue by shou1156226** [golang/go#30387]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build898246176=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

/ You can edit this code!
// Click here and start typing.
package main

import "fmt"

func main() {
        x :=float64(0)
	var times float64=float64(300) / x
	fmt.Printf("Hello, 世界 %v %v\n",x, times )
}

### What did you expect to see?

panic: runtime error: integer divide by zero

### What did you see instead?

Hello, 世界 0 +Inf

**Comment by bcmills** [comment]
This behavior is defined by the IEEE-754 standard for floating-point arithmetic.

(`float64` is not an integer type, so `integer divide by zero` would be inaccurate.)

**Comment by shou1156226** [comment]
> This behavior is defined by the IEEE-754 standard for floating-point arithmetic.
> 
> (`float64` is not an integer type, so `integer divide by zero` would be inaccurate.)

which standard in IEEE-754? Could you tell me ? why is below code run like my expect?
-------------------------------------------------------------
package main

import "fmt"

func main() {
	var times float64=float64(300) / float64(0)
	fmt.Printf("Hello, 世界 %v %v\n",float64(0), times )
}
--------------------------------------------------------------
it output  **prog.go:8:33: division by zero**

**Comment by randall77** [comment]
That last error you're seeing is an error from the compiler. It is illegal to have a divide by zero in a constant expression. From the spec:

> The divisor of a constant division or remainder operation must not be zero

Your original sample was a divide by zero at runtime, for which IEEE-754 applies (and mandates +INF as the result).

I couldn't tell you where in IEEE-754 this spec lives, I don't have a copy handy.

**Comment by shou1156226** [comment]
> That last error you're seeing is an error from the compiler. It is illegal to have a divide by zero in a constant expression. From the spec:
> 
> > The divisor of a constant division or remainder operation must not be zero
> 
> Your original sample was a divide by zero at runtime, for which IEEE-754 applies (and mandates +INF as the result).
> 
> I couldn't tell you where in IEEE-754 this spec lives, I don't have a copy handy.

No matter it is a constant or variable, it shouldn't have the same behavior?

**Comment by randall77** [comment]
Nope.  Constants in Go behave differently.  For instance, they have higher precision and dynamic range than float64 or uint64.  You might want to read the section in the spec on constants.

**Comment by shou1156226** [comment]
> Nope. Constants in Go behave differently. For instance, they have higher precision and dynamic range than float64 or uint64. You might want to read the section in the spec on constants.

but Divide Int is correct, when i have 300/0 or 300/x is the same

**Comment by randall77** [comment]
Integer divide isn't IEEE-754. It will runtime panic on a divide by zero.
You'll notice that `300/0` gives you an error at compile time, and `300/x` when `x==0` gives you an error at run time.  The errors are quite different if you inspect them (e.g. one has a stack trace, one doesn't).

**Comment by shou1156226** [comment]
> Integer divide isn't IEEE-754. It will runtime panic on a divide by zero.
> You'll notice that `300/0` gives you an error at compile time, and `300/x` when `x==0` gives you an error at run time. The errors are quite different if you inspect them (e.g. one has a stack trace, one doesn't).

I read IEEE-754, it says bellow: 
The divideByZero exception shall be signaled (if and only if an exact infinite result is defined for an operation on finite operands). In particular, (the division by zero exception) shall be signaled (if the divisor is zero and the dividend is a finite non-zero number). The default result shall be a correctly signed ∞ (see 8.3).

Golang not define an exact infinite result  for an operation on finite operands ? what does it mean?

**Comment by ianlancetaylor** [comment]
In practice most languages ignore the `divideByZero` exception.  In those languages, including Go, you get the default result of a correctly signed ∞, which is what you are seeing.
