### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#30380]
i use pprof  “-alloc_space ***heap”，found:
flat flat% sum% cum  cum%
22MB 9.17% 88.82% 223.91MB 92.99% ReqMsgDispath
.......
and “list ReqMsgDispath”
......
11.50MB 11.50MB 127:   var len int
.               .               128:  t2api.GetRawData(lpdata,&len,0)

I don't understand why " var len int" used 11M memory.

![image](https://user-images.githubusercontent.com/4704280/53312463-16f56c00-38f0-11e9-9e09-167187702677.png)

golang 1.11 win 32

**Comment by cch123** [comment]
This variable may escape to heap, which will be recycled later.

if you want to locate memory leak, you should use inuse_space.

**Comment by zhaoya881010** [comment]
can i use pprof find cgo memory leek?

**Comment by martisch** [comment]
This does not look like a memory leak. The report is about allocated memory on the heap (which may be garbage collected later). If the variable "len" escapes (which it lokes like in line 128) it needs to be allocated on the heap. The 11M is the sum of allocations profiled.
