### ISSUE TITLE
Panic url.Error (url.go line 28)

### ISSUE THREAD

**Issue by Biter777** [golang/go#30383]
go version 1.11.5

Truble with url.go, line 28:
`func (e *Error) Error() string { return e.Op + " " + e.URL + ": " + e.Err.Error() }`

```
func main() {
	var err error
	var urlErr *url.Error
	err = urlErr
	if err != nil {
		fmt.Println(err.Error())    // panic, because e.Err == nil
	}
}
```

Play: https://play.golang.org/p/TESekBRFKn5

**Comment by martisch** [comment]
err is (*url.Error)(nil) not nil here. This looks working as intended. See: https://golang.org/doc/faq#nil_error

Note that the github golang project does not use the issue tracker for programming questions.
