### ISSUE TITLE
x/playground: upgrade to 1.12

### ISSUE THREAD

**Issue by iporsut** [golang/go#30397]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/weerasak/go/bin"
GOCACHE="/Users/weerasak/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/weerasak/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9k/pvfwqqzn6fqbpwghhrcjkm480000gn/T/go-build282905208=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I run `godoc -play` that distributed with go 1.12 then open `http://localhost:6060/pkg/strings/#ReplaceAll` and run example.

### What did you expect to see?
`moo moo moo`

### What did you see instead?

```
prog.go:9:14: undefined: strings.ReplaceAll
```

**Comment by iporsut** [comment]
The root cause because `godoc` sending example code to compile at `https://play.golang.org/compile` that still use `v1.11.1`.

**Comment by dmitshur** [comment]
Indeed, the playground is still on Go 1.11.1, as https://play.golang.org/p/Ztyu2FJaajl reports.

I'll redeploy it with Go 1.12 now.

**Comment by iporsut** [comment]
I'v checked https://play.golang.org/p/Ztyu2FJaajl it 1.12 now thanks.
