### ISSUE TITLE
fmt: map printing sort does not deterministically sort differing types

### ISSUE THREAD

**Issue by lukechampine** [golang/go#30398]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```go
fmt.Println(map[interface{}]string{
    3: "3",
    "a": "a",
    2: "2",
    "c": "c",
    1: "1",
    "b": "b"
})
```

### What did you expect to see?

```go
1:1 2:2 3:3 a:a b:b c:c
```

### What did you see instead?

Non-deterministic result; differing types always compare to -1, so the result depends on map iteration, which is pseudo-random.

---

It's possible that I'm just misinterpreting the documentation here. The release notes say:

>Interface values compare first by reflect.Type describing the concrete type and then by concrete value as described in the previous rules.

I read this as "values compare first lexicographically by type *name*, then by their concrete value." However, `fmtsort.compare` instead does:
```go
c := compare(reflect.ValueOf(aType), reflect.ValueOf(bType))
if c != 0 {
	return c
}
```
Which results in the `*reflect.rtype` values being compared by their machine addresses. But since `a` and `b` have the same type, their addresses will be equal (not sure if this is always the case), so this `compare` is ineffectual.

I think the correct code implementation would be something like:

```go
aConcreteType := aVal.Elem().Type().String()
bConcreteType := bVal.Elem().Type().String()
c := compare(reflect.ValueOf(aConcreteType), reflect.ValueOf(bConcreteType))
if c != 0 {
	return c
}
```

which produces deterministic output. I'm happy to submit a pull request for this if so desired.

**Comment by odeke-em** [comment]
Thank you @lukechampine for this report!

Kindly paging @robpike @rsc @mvdan.

**Comment by mvdan** [comment]
What does `text/template` do in this scenario? If the template package is deterministic and fmt isn't, that's very likely a bug to fix in fmt.

**Comment by rhnvrm** [comment]
The `text/template` package also is not producing deterministic output:
https://play.golang.org/p/wpbTEx1z9E9

```
package main

import (
	"os"
	"text/template"
)

func main() {
	tmpl := `{{ range $k, $v := . }}Key:{{ $k }}, Value:{{ $v }}, {{ end }}`
	t := template.New("hello")
	mp := map[interface{}]string{
		3:   "3",
		"a": "a",
		2:   "2",
		"c": "c",
		1:   "1",
		"b": "b",
	}

	tt, err := t.Parse(tmpl)
	if err != nil {
		panic(err)
	}

	if err = tt.Execute(os.Stdout, &mp); err != nil {
		panic(err)
	}
}
```

Output: 
```
Key:1, Value:1, Key:2, Value:2, Key:a, Value:a, Key:3, Value:3, Key:b, Value:b, Key:c, Value:c, 
```

**Comment by rhnvrm** [comment]
The result of `go1.12 run` for

```
package main

import (
	"os"
	"text/template"
)

func main() {
	tmpl := `{{ range $k, $v := . }}Key:{{ $k }}, Value:{{ $v }}, {{ end }}`
	t := template.New("hello")
	mp := map[interface{}]string{
		3:   "3",
		"a": "a",
		2:   "2",
		"c": "c",
		1:   "1",
		"b": "b",
	}

	tt, err := t.Parse(tmpl)
	if err != nil {
		panic(err)
	}

	if err = tt.Execute(os.Stdout, &mp); err != nil {
		panic(err)
	}
}
```

`Key:1, Value:1, Key:2, Value:2, Key:a, Value:a, Key:b, Value:b, Key:c, Value:c, Key:3, Value:3`

**Comment by lukechampine** [comment]
@mvdan it looks like `text/template` just calls out to `fmtsort`:

https://github.com/golang/go/blob/b5a68a9e414dc1d412d623f80c54aafe3ada0f14/src/text/template/exec.go#L361-L369

So my proposed fix will also change the behavior of `text/template`.

**Comment by randall77** [comment]
@gopherbot, please open a backport issue for 1.12.
