### ISSUE TITLE
cmd/go: downloaded module missing a source file

### ISSUE THREAD

**Issue by clarkezone** [golang/go#30396]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jamesclarke/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jamesclarke/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jamesclarke/Source/Temp/gotest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/dh9gmlhd00g9qkdsv86pj2dw0000gn/T/go-build486175678=/tmp/go-build -gno-record-gcc-switches -fno-common" 

</pre></details>

### What did you do?

1) Create a new project
2) go mod init gitHub.com/foo/bar
3) create a hello.go file containing:
<pre>
package main

import (
        "golang.org/x/crypto/ssh/terminal"
)

func main() {
        _, err := terminal.MakeRaw(0)
        if err != nil {
                log.Fatal(err)
        }
}
</pre>
4) go build

### What did you expect to see?
Program compiles 

### What did you see instead?
<pre>
go build
# golang.org/x/sys/unix
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12/unix/fcntl_darwin.go:15:42: undefined: Flock_t              
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12/unix/ioctl.go:14:47: undefined: Winsize                     
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12/unix/ioctl.go:25:47: undefined: Termios                     
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12/unix/sockcmsg_unix.go:50:18: undefined: Cmsghdr             
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12/unix/sockcmsg_unix.go:56:9: undefined: Cmsghdr  
</pre>
Tried go get golang.org/x/sys and build still fails

**Comment by bcmills** [comment]
(CC @jayconrod)

All of the missing declarations from that error message come from [`ztypes_darwin_amd64.go`](https://github.com/golang/sys/blob/master/unix/ztypes_darwin_amd64.go), so it sounds like that file is somehow missing from the extracted module.

Were you by any chance using this version of `golang.org/x/sys` with a previous version of the Go toolchain, particularly with concurrent invocations of `go` commands?

If not, please save `$GOPATH/pkg/mod/cache/download/golang.org/x/sys/@v` and tar/zip up `$GOPATH/pkg/mod/golang.org/x/sys@v0.0.0-20190225065934-cc5685c2db12` (for later investigation), and run `go clean -modcache` to see if a fresh copy of the module is corrupted in the same way.

**Comment by bcmills** [comment]
I would be especially interested to know:
a. Are the missing files present in the `.zip` file for that version of the module?
b. Are there any other files present in the `.zip` file but missing from the unzipped copy of the module?

**Comment by clarkezone** [comment]
I have had previous version's of Go installed but no concurrent invocations of go cmd.  The go clean -modcache did fix it, I have the archive if you are interested

**Comment by bcmills** [comment]
Yes, please do attach the archive. (It probably won't have any new clues, but you never know...)

**Comment by clarkezone** [comment]
Here you go

[Archive.zip](https://github.com/golang/go/files/2950311/Archive.zip)

**Comment by seankhliao** [comment]
seems we didn't get any other related reports.
