### ISSUE TITLE
Enhancement: Provide playground examples for all stdlib members

### ISSUE THREAD

**Issue by mcandre** [golang/go#30393]
It's really helpful for newbies to be able to see a working example for a given Go function or variable. Can we expand the existing examples in the go docs to cover more of the standard Go library members?

**Comment by mvdan** [comment]
I think more specific issues would be helpful. What parts of the standard library are lacking examples? If this issue were to track "add more examples", it would probably never be closed.

**Comment by bcmills** [comment]
As @mvdan notes, if you find the examples lacking for any given package, please file a specific issue for that package.
