### ISSUE TITLE
go: github.com/mongodb/mongo-go-driver@v1.0.0: unexpected end of JSON input

### ISSUE THREAD

**Issue by iiinsomnia** [golang/go#30395]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.0
</pre>

```sh
$ go get github.com/mongodb/mongo-go-driver@v1.0.0
go: finding github.com/mongodb/mongo-go-driver v1.0.0
go: github.com/mongodb/mongo-go-driver@v1.0.0: unexpected end of JSON input
go: error loading module requirements
```

**Comment by bcmills** [comment]
Please fill out the rest of the issue template.

**Comment by oiooj** [comment]
@iiinsomnia The repo `github.com/mongodb/mongo-go-driver` doesn't have a `v1.0.0` tag, please try this at this point:

```
go get github.com/mongodb/mongo-go-driver@v1.0.0-rc1
```

And I want to know that do you use a proxy to get deps?

**Comment by iiinsomnia** [comment]
@oiooj It's OK, thks!
