### ISSUE TITLE
net/smtp: SendMail AUTH error with PlainAuth and successful STARTTLS

### ISSUE THREAD

**Issue by imirkin** [golang/go#30403]
See issue #22145 for background. This got merged in go1.11.

It appears that google-apps-for-your-domain SMTP, when connecting on port 25, does not list AUTH even after STARTTLS. The regular gmail smtp does:

$ openssl s_client -starttls smtp -crlf -connect smtp.gmail.com:25
...
EHLO foo.com
250-smtp.gmail.com at your service, [xxx]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
...

but:

$ openssl s_client -starttls smtp -crlf -connect aspmx.l.google.com:25
...
EHLO foo.com
250-mx.google.com at your service, [xxx]
250-SIZE 157286400
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
QUIT
DONE

The latter had been working previous to the change in question, but now, predictably, I'm getting errors about AUTH not being supported. I believe the change originally went in under the "I can't believe that'll happen" banner, but ... believe it :)

**Comment by ianlancetaylor** [comment]
Thanks for the follow-up.  Although the behavior did change, it doesn't seem to have changed unreasonably.  I'm going to close this.
