### ISSUE TITLE
x/build/cmd/gitlock: produces different output depending on host GOOS/GOARCH

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30412]
Running `gitlock` on macOS vs Linux produces different output. It's because it runs `go list -tags=foo -f '{{range .Deps}}{{.}}\n{{end}}' p` to determine dependencies, and `go list` uses the host `GOOS/GOARCH` unless a different one is provided.

That means, for example, running `make update-deps` in x/playground repository produces different output if run on macOS vs Linux.

/cc @bradfitz

**Comment by bradfitz** [comment]
We have an open bug to move to modules anyway and nuke gitlock, so not sure how important this is to fix. I'd say just use Linux for now when using gitlock.

**Comment by dmitshur** [comment]
SGTM.

**Comment by bcmills** [comment]
Closing as Unfortunate. Hopefully we can move over to modules soon.
