### ISSUE TITLE
Panic/Warn, don't silently truncate, copy() when destination buffer is too small

### ISSUE THREAD

**Issue by mcandre** [golang/go#30410]
`copy()` silently ignores the case where destination is too small to contain the values from the source buffer. Can we extend the API to report an error for this, or at least panic()?

**Comment by mvdan** [comment]
This is well documented: https://golang.org/pkg/builtin/#copy

In particular, it returns an int to report the number of bytes copied. You could easily write your checks with that.

We can't change its signature now, as that would be a breaking change. See https://golang.org/doc/go1compat. Feel free to write a Go2 proposal, but I imagine this change is far too small and unimportant to warrant changing the builtin package.

**Comment by mcandre** [comment]
Checking integers is not something the Go ecosystem easily enforces on behalf of the unsuspecting programmer. Checking errors (`errcheck`) is.
