### ISSUE TITLE
cmd/link: TestDWARF acting strangely with t.Parallel()

### ISSUE THREAD

**Issue by Helflym** [golang/go#30429]
### What version of Go are you using (`go version`)?

master after this [commit](https://github.com/golang/go/commit/e609bd373fc9909758b6f4d2403c155e6cf55e23#diff-4037ce56d6783782108efbe27ccf0f7e)

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/chigotc/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chigotc/go/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/chigotc/go/goroot"
GOTMPDIR=""
GOTOOLDIR="/home/chigotc/go/goroot/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
TestDWARF "prog" variable is updated after t.Parallel() in t.Run() function. Therefore, TestDWARF/testprog is actually launching testprogcgo. 
If you remove t.Parallel(), it doesn't occur anymore. 

<pre>
$ go test -v -run TestDWARF
=== RUN   TestDWARF
=== RUN   TestDWARF/testprog
=== PAUSE TestDWARF/testprog
=== RUN   TestDWARF/testprogcgo
=== PAUSE TestDWARF/testprogcgo
=== CONT  TestDWARF/testprog
=== CONT  TestDWARF/testprogcgo
--- PASS: TestDWARF (0.19s)
    --- PASS: TestDWARF/testprogcgo (3.35s)
        dwarf_test.go:48: log before parallel  testprogcgo
        dwarf_test.go:50: log after parallel  testprogcgo
    --- PASS: TestDWARF/testprog (3.35s)
        dwarf_test.go:48: log before parallel  testprog
        dwarf_test.go:50: log after parallel  testprogcgo
=== RUN   TestDWARFiOS
--- SKIP: TestDWARFiOS (0.00s)
    dwarf_test.go:150: skipping on non-darwin/amd64 platform
PASS
ok  	cmd/link	3.545s
</pre>

**Comment by bcmills** [comment]
This also leads to some TryBot failures:
https://build.golang.org/log/eb0a0138624df5b3cc4c7d1199fe3b1c5ed780c8

**Comment by bcmills** [comment]
CC @cherrymui @rsc @mdempsky @ianlancetaylor for `cmd/link`.
