### ISSUE TITLE
strconv.Unquote problem with quote characters

### ISSUE THREAD

**Issue by sharkboy1976** [golang/go#30433]
package main
import (
	"fmt"
	"strconv"
)
func main() {
	s, err := strconv.Unquote("\\"\u003cTest Version=\u00222.0.0\u0022\u003e\\"")
	fmt.Println(s,err)
}
-> invalid syntax

the issue is that when \u0022 is used it doesn't translate to " (same issue for \\"). the example string however works with \u0023 

the result expected is \<Test Version="2.0.0"\>

this can be tried out at https://play.golang.org/

**Comment by robpike** [comment]
The program is invalid because the string literal is illegal: It starts with two double quotes.

Please create a working example of the problem you are trying to demonstrate.

**Comment by robpike** [comment]
It would be best to provide a link to a program demonstrating the issue using the Share button on play.golang.org.

**Comment by sharkboy1976** [comment]
the formatter of github doesnt show the escaped string literals

**Comment by sharkboy1976** [comment]
https://play.golang.org/p/dvcVUu59xzL

**Comment by ianlancetaylor** [comment]
Writing `\u0022` in a string literal is exactly the same as writing `"` in that literal.  The `\u0022` is handled by the compiler.  The string you are passing to `strconv.Unquote` is `"<Test Version="2.0.0">"`, a string with four unquoted `"` characters.  And that string is indeed a syntax error from `Unquote`'s point of view.

Compare to https://play.golang.org/p/cIgxmjv7f4b which works as you expect.
