### ISSUE TITLE
cmd/vet: printf check misses strings that are + together

### ISSUE THREAD

**Issue by imirkin** [golang/go#30436]
With this example put into https://play.golang.org/ (and go1.11), there is no warning. Joining the two strings into 1 results in a warning.

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground %d" + "", 5)
}
```

Some people split long strings, which is where I encountered it.

**Comment by bcmills** [comment]
CC @alandonovan @josharian @mvdan @ianthehat for `cmd/vet`

**Comment by alandonovan** [comment]
Thanks, this is indeed a bug. The checkPrint function in golang.org/x/tools/go/analysis/passes/printf/printf.go looks for ast.BasicLit, which is a relic of the older implementation which could not assumed well-typed syntax trees. Now it's better to look for expressions that are string constants, independent of their syntax, as we do when checking Printf (not Println as in your example).

**Comment by dmitshur** [comment]
This change is finding 3 instances in the Go tree itself:

```
# cmd/cover
cmd/cover/cover.go:43:2: fmt.Fprintln arg list ends with redundant newline
# cmd/vendor/github.com/google/pprof/internal/report
cmd/vendor/github.com/google/pprof/internal/report/source.go:877:2: fmt.Fprintln arg list ends with redundant newline
# cmd/trace
cmd/trace/main.go:69:3: fmt.Fprintln arg list ends with redundant newline
```

Filed #49322 for resolving them.
