### ISSUE TITLE
cmd/vet: false positive in Printf recursive Stringer check with non-matching String() functions

### ISSUE THREAD

**Issue by reillywatson** [golang/go#30441]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### Does this issue reproduce with the latest release?
Yes!

### What operating system and processor architecture are you using (`go env`)?

play.golang.org

### What did you do?

```go
package main

import (
	"fmt"
)

type Foo int
func (f Foo) String() (string, error) {
	return "", fmt.Errorf("%v", f)
}

func main() {
	s, err := Foo(1).String()
	fmt.Println(s, err)
}
```

https://play.golang.org/p/-zpHBBPnetu

### What did you expect to see?

No vet output

### What did you see instead?

prog.go:9:13: Errorf format %v with arg f causes recursive String method call

**Comment by reillywatson** [comment]
https://go-review.googlesource.com/c/tools/+/164217 is a potential fix for this.

**Comment by bcmills** [comment]
CC @alandonovan @josharian @mvdan @ianthehat
