### ISSUE TITLE
cmd/go: error if GOCACHE is set but is not an absolute path

### ISSUE THREAD

**Issue by mileusna** [golang/go#30447]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="on"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mileusna/Dropbox/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3r/3lsskhdx6db_lw1m06qfr62c0000gn/T/go-build512222336=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre># go test</pre>

### What did you expect to see?

Test running

### What did you see instead?

Build error and test failed probably due to new structure for cache directories in 1.12
```
# devgit.ha.rs/mi2/cmd/mnsinfo-api.test
/var/folders/3r/3lsskhdx6db_lw1m06qfr62c0000gn/T/go-build218744920/b001/_testmain.go:10:2: can't open import: "devgit.ha.rs/mi2/cmd/mnsinfo-api": open on/f9/f95617d4d2ff6b243c4e9e04cf4904cdde38953c391e5a9abb6291e18732b096-d: no such file or directory
FAIL	devgit.ha.rs/mi2/cmd/mnsinfo-api [build failed]
Error: Tests failed.
```
Executing `go clean -cache` will fix a problem for a while, but then it starts occurring again.

**Comment by ianlancetaylor** [comment]
Don't set `GOCACHE=on`.  `GOCACHE` should be the path to the cache directory you want to use.  We should probably give an error if `GOCACHE` is set and it is not an absolute path.

**Comment by mileusna** [comment]
Thanks, I was wondering why the hell the tmp directory is named "on". 😂

I have an explanation for this. The story goes that I had this settings on "off", but 1.12 didn't want to compile with GOCACHE="off". I try to delete it from .bash_profile but VSCode haven't picked up that change after several VSCode restarts, so I put it back and set it to "on". Compile started to work and end up with "on/" directory for cache files 😂  but `go test` started to fail.

**Comment by agnivade** [comment]
Also see previous conversation here https://github.com/golang/go/issues/28290.

**Comment by mileusna** [comment]
Now when I know for this issue, I don't mind if it will be relative or absolute path. The off value is history now, so I guess I will never use this env var ever again.

But for transition period like now when I upgraded from 1.11 to 1.12 and moved from "off" to "on" 😆 warning on abs path would save me a lot of wasted time. :)

**Comment by mileusna** [comment]
Does anyone know how can I avoid cache in `go test` now when there is no `GOCACHE=off`?

```
--- PASS: TestObjDef (0.02s)
PASS
ok  	devgit.ha.rs/mi2/cmd/mnsinfo-api	**(cached)**
Success: Tests passed.
```

**Comment by agnivade** [comment]
https://golang.org/cmd/go/#hdr-Test_packages

> The idiomatic way to disable test caching explicitly is to use -count=1.

**Comment by oiooj** [comment]
@gopherbot please backport to 1.12
