### ISSUE TITLE
x/build/maintner: TestForeachRepo is failing on Go tip due to error change

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30442]
With Go 1.12:

```
$ go test -v -run=TestForeachRepo -count=1 golang.org/x/build/maintner
=== RUN   TestForeachRepo
--- PASS: TestForeachRepo (0.00s)
    github_test.go:751: Tested Reviews
PASS
ok  	golang.org/x/build/maintner	0.146s
```

With Go tip (at commit df557fe3ea94ff8888abd6a6ab4cc5d5351d77a6):

```
$ gotip test -v -run=TestForeachRepo -count=1 golang.org/x/build/maintner
=== RUN   TestForeachRepo
--- FAIL: TestForeachRepo (0.00s)
    github_test.go:743: Will Error: ForeachReview errs differ. got: Planned Failure, want: Planned Failure
    github_test.go:743: Will Error Late: ForeachReview errs differ. got: Planned Failure, want: Planned Failure
    github_test.go:751: Tested Reviews
FAIL
FAIL	golang.org/x/build/maintner	0.148s
```

I suspect it's because of https://github.com/golang/go/commit/6be6f114e0d483a233101a67c9644cd72bd3ae7a. It changed the internal representation of the result of `fmt.Errorf`, making it so that `!deep.ReflectEqual` no longer compares favorably in [github_test.go#L742-L744](https://github.com/golang/build/blob/202164ea31fcd61777c9a9cc1f4ababbce8b246d/maintner/github_test.go#L742-L744):

```Go
if !reflect.DeepEqual(tt.wantErr, err) {
	t.Errorf("%s: ForeachReview errs differ. got: %s, want: %s", tt.name, err, tt.wantErr)
}
```

This makes trybots in x/build repo fail, e.g., https://go-review.googlesource.com/c/build/+/163205/2#message-8c683121b60291567babee1aed8cd19a0f83bfc6.

/cc @bradfitz

**Comment by bradfitz** [comment]
We could switch to using https://github.com/google/go-cmp instead of reflect.

**Comment by dmitshur** [comment]
That sounds like a good fix for the issue in x/build/maintner.

**Comment by dmitshur** [comment]
Since it was just two `error` values being compared, and not a more deeply nested struct, I went with a simpler solution for now.
