### ISSUE TITLE
cmd/compile: mips64 instruction UNPREDICTABLE error

### ISSUE THREAD

**Issue by hengwu0** [golang/go#30459]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wuheng/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/wuheng/go"
GORACE=""
GOROOT="/home/wuheng/CrossTools/golang"
GOTMPDIR=""
GOTOOLDIR="/home/wuheng/CrossTools/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build622509133=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<pre>
[wuheng@localhost]$ GOCACHE=off GOARCH=mips64 go build -o A main.go
</pre>
Copy file A to mips64 system level qemu...
<pre>
[wuheng@mips64]$ qemu-system-mips64 -version
QEMU emulator version 2.10.1
</pre>

### What did you expect to see?
In qemu-system-mips64:
<pre>
[wuheng@mips64]$ ./A
0
</pre>

### What did you see instead?
In qemu-system-mips64:
<pre>
[wuheng@mips64]$ ./A
46
</pre>

### My source code main.go

```go
package main

import "fmt"
import "os"

func main() {
	var x byte=os.Args[0][0]
	mask := rune(x) << 31 >> 31
	fmt.Println(mask)
}
```

**Comment by hengwu0** [comment]
I looked the asm of file A, it showed below:
```asm
[wuheng@localhost]$ mips64--gnu-objdump -S A | less
...
       mask := rune(x) << 31 >> 31
   a9558:       00010ff8        dsll    at,at,0x1f
   a955c:       00200821        move    at,at
   a9560:       00010ffb        dsra    at,at,0x1f
...
```
It seemd golang use AADDU instruction to sign-extended to high 32 bits( `00200821` indicate AADDU ), but there is an __UNPREDICTABLE__ in addu explained in MIPS64 ISA. Which showed below:
```
Restrictions:

If either GPR rt or GPR rs does not contain sign-extended 32-bit values (bits 63..31 equal), then the result of the operation is UNPREDICTABLE.

Operation:
if NotWordValue(GPR[rs]) or NotWordValue(GPR[rt]) then
    UNPREDICTABLE
endif
temp ← GPR[rs] + GPR[rt]
GPR[rd] ← sign_extend(temp31..0)
```

I debuged the program A, and I found the high 32 bits are __not equal__ in _at_ register!

**Comment by hengwu0** [comment]
You can replace `addu` with a `sll` instruction with a definite behavior (`sll` will discard the upper 32 bits of the 64 bits, then do sign extensions, with certain behavior). It won't have any UNPREDICTABLE expectation. #30461

**Comment by cherrymui** [comment]
Thanks for the investigation. The MIPS64 port was written according to MIPS III ISA, which, as far as I know, doesn't have such restriction. That said, if the fix works on both old and new MIPS64 machines, I'm ok with it.

**Comment by hengwu0** [comment]
> Thanks for the investigation. The MIPS64 port was written according to MIPS III ISA, which, as far as I know, doesn't have such restriction. That said, if the fix works on both old and new MIPS64 machines, I'm ok with it.

I looked the MIPS III ISA, there is a line of `addu` in the manual: **In 64-bit mode, the operands must be valid sign-extended, 32-bit values.** So it also has the restriction too!!! [Reference here.](http://groups.csail.mit.edu/cag/raw/documents/R4400_Uman_book_Ed2.pdf) I debuged the program A, and I found the high 32 bits are __not equal__ in _at_ register!
Thanks for merging.
