### ISSUE TITLE
x/tools/cmd/gorename: Only work on current directory.

### ISSUE THREAD

**Issue by markvincentcaro** [golang/go#30456]
Currently, the gorename tool is working on the entire GOPATH directory. If your GOPATH contains lots of projects (including third-party libraries like ones from GitHub), it becomes so slow that it is next to unusable.

When developers rename something, they are usually only interested in code inside their current directory.

The proposed solution is to change gorename to only work on code inside the current directory. If this is not possible, then a flag, setting, or environment variable can be added to configure gorename to either work on the entire GOPATH or only on the current directory.

**Comment by markvincentcaro** [comment]
I would like to reference Issue https://github.com/golang/go/issues/10917 to show that we Devs have been asking for this feature since 2015.

**Comment by bcmills** [comment]
CC @ianthehat

**Comment by bcmills** [comment]
GOPATH mode is on its way out. `gorename` in module mode will not depend on the size of your GOPATH; #27571 tracks module mode support.

**Comment by markvincentcaro** [comment]
Hi, @bcmills 

I think this issue should remain Open since Go Modules isn't that widespread yet and most Go Developers are still using classic projects.

Until Go Modules becomes the norm, this issue will affect pretty much everyone not using Modules.

**Comment by bcmills** [comment]
There wouldn't be much point to that. Realistically, nobody is going to update `gorename` until module support is the default: the folks who own the `gorename` tool are already busy implementing module support and `gopls`, and both of those are much higher priority than refactoring things in GOPATH mode.

**Comment by markvincentcaro** [comment]
@bcmills I see, hopefully Go Modules catch on soon then. Currently, a lot of third-party libraries here on GitHub don't support it and break upon `go get` while in Modules mode.
