### ISSUE TITLE
doc: wrong link in release history

### ISSUE THREAD

**Issue by marigonzes** [golang/go#30451]
### What did you do?
I visited the [release history](https://golang.org/doc/devel/release.html) page for the Go language.

### What did you expect to see?
I expected the minor revisions' links to be correct.

### What did you see instead?
Instead, the link to the [go1.6.4 milestone](https://golang.org/doc/devel/release.html#go1.6.minor) does not exist and in its place there is a link to the 1.7.4 milestone.
The same happens with go1.7.6 and go1.5.4.

**Comment by ALTree** [comment]
This seems to be intentional. The 1.6.4 paragraph says:

>  **It contains the same fixes as Go 1.7.4 and was released at the same time.** See the Go 1.7.4 milestone on our issue tracker for details. 

so it links to the 1.7.4 milestone, since it's basically the same thing with the same two patches. While it's true that more recently we link to the two distinct milestone, I doesn't make much difference IMO.

**Comment by marigonzes** [comment]
Yeah, you are right. Somehow I missed the part that states:
> It contains the same fixes as Go 1.7.4 and was released at the same time

:man_facepalming:
I leave it up to you if you think this should be closed or not.

**Comment by agnivade** [comment]
Well, the actual 1.6.4 milestone contains 2 different fixes. Perhaps they should be removed from that milestone then ? https://github.com/golang/go/issues?utf8=%E2%9C%93&q=milestone%3AGo1.6.4

**Comment by ALTree** [comment]
I would leave them, the official link points to 1.7.4 so they won't mislead anyone. OTOH this issue can be closed, since the link is correct.
