### ISSUE TITLE
What is the meaning of  045 五一?

### ISSUE THREAD

**Issue by rc452860** [golang/go#30458]
https://github.com/golang/go/blob/master/doc/gopher/fiveyears.jpg
![image](https://user-images.githubusercontent.com/3949222/53544170-18c56680-3b60-11e9-88ef-12ced605d4e4.png)

**Comment by agnivade** [comment]
Let us keep the questions focused on the Go language specifically. Please feel free to ask around in the various forums in the [Questions](https://github.com/golang/go/wiki/Questions) wiki page
