### ISSUE TITLE
x/mobile: 'gomobile bind -x' fails due to unused '-mno-thumb' argument passed to clang

### ISSUE THREAD

**Issue by ssrlxl** [golang/go#30457]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shaoshengrong/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shaoshengrong/code/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kc/cg92l_vj04n2h70mw6clq22w0000gn/T/go-buil

</pre></details>

### What did you do?
exec : gomobile bind -x
error: clang: error: argument unused during compilation: '-mno-thumb' [-Werror,-Wunused-command-line-argument]

### What did you expect to see?
exec : gomobile bind -x
error: clang: error: argument unused during compilation: '-mno-thumb' [-Werror,-Wunused-command-line-argument]

### What did you see instead?
exec : gomobile bind -x
error: clang: error: argument unused during compilation: '-mno-thumb' [-Werror,-Wunused-command-line-argument]

**Comment by bcmills** [comment]
Possibly related to #30415?

**Comment by bcmills** [comment]
CC @eliasnaur @hyangah

**Comment by eliasnaur** [comment]
I can't reproduce this on my macOS 10.14.1. Do you have NDK version r19b installed as well as run `go get -u golang.org/x/mobile/cmd/...`?
