### ISSUE TITLE
fmt: Regression in fmt.Printf("%d", Error) where Error is an integer type satisfying error

### ISSUE THREAD

**Issue by ncw** [golang/go#30472]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +c2b707bcf1 Thu Feb 28 11:24:52 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ncw/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ncw/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go/go1.12"
GOTMPDIR=""
GOTOOLDIR="/opt/go/go1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build543488653=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Compile and run this program

```go
package main

import (
	"fmt"
)

type Error byte

func (e Error) Error() string {
	return fmt.Sprintf("Error number %d", e)
}

func main() {
	fmt.Printf("Error %d\n", Error(99))
}
```

### What did you expect to see?

```
$ go version
go version go1.12 linux/amd64
$ go run err-bug.go
Error 99
```

### What did you see instead?

```
$ go version
go version devel +c2b707bcf1 Thu Feb 28 11:24:52 2019 +0000 linux/amd64
$ go run err-bug.go
Error %!d(main.Error=99)
```

I used git-bisect to discover that it is caused by 6be6f114e0d483a233101a67c9644cd72bd3ae7a on CL https://go-review.googlesource.com/c/go/+/163559 from #29934

I'm not sure if this is intended?

Cc: @mpvl

**Comment by bradfitz** [comment]
This also broke x/net/idna's tests.

I sent off https://go-review.googlesource.com/c/net/+/164518 but it's a hacky workaround.

**Comment by neild** [comment]
I've got a fix, will send it off when I finish testing it.
