### ISSUE TITLE
x/blog, x/tour, x/talks: deploy with Go 1.11 runtime of App Engine Standard

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30486]
The following services should to be updated to deploy using Go 1.11 runtime of App Engine Standard:

- [ ] x/blog – currently using Go 1.9 runtime; see its [app.yaml#L3](https://github.com/golang/blog/blob/1014ebc2bd8b24516c1692bc1f102f90a1f3ad66/app.yaml#L3)
- [ ] x/tour – currently using Go 1.9 runtime; see its [app.yaml#L3](https://github.com/golang/tour/blob/838ce51196a7e9f9bff83402caf4f678dc0f0d75/app.yaml#L3)
- [x] x/talks – already using Go 1.11 runtime; see its [app.yaml#L2](https://github.com/golang/talks/blob/fb41a9b433bf1d7e71d768e703c81170aa4f282c/app.yaml#L2)

Doing so will make it possible¹ to start using `net/http` package for making HTTP requests (instead of [`google.golang.org/appengine/urlfetch`](https://godoc.org/google.golang.org/appengine/urlfetch) package²) in the [`golang.org/x/tools/playground`](https://godoc.org/golang.org/x/tools/playground) package, and unblock [CL 160837](https://golang.org/cl/160837) from being able to be merged.

Merging that CL will help with golang/go#29981 and https://github.com/golang/lint/issues/436.

/cc @matloob @andybons @bradfitz

¹: https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk
²: https://cloud.google.com/appengine/docs/standard/go/issue-requests

**Comment by bradfitz** [comment]
Or Go 1.12.

**Comment by bradfitz** [comment]
Oh, of App Engine. Maybe they'll have Go 1.12 soon, but yeah, no reason to wait for it.

**Comment by dmitshur** [comment]
I'm close to being able to send a CL to convert x/tour.

I've deployed a test staging instance to https://tour-dot-go-dashboard-dev.appspot.com, if anyone would like to help test it out and report any problems.

**Comment by dmitshur** [comment]
This is done now, all 3 are on Go 1.11 runtime and deployed.
