### ISSUE TITLE
"go clean -modcache" shouldn't need to "find" anything

### ISSUE THREAD

**Issue by vangent** [golang/go#30480]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/rvangent/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/rvangent/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/google-golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/usr/local/google/home/rvangent/go/src/github.com/gohugoio/hugo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build946386746=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ go clean -modcache
```

### What did you expect to see?

My modcache cleaned.

### What did you see instead?

<pre>
$ go clean -modcache
go: finding github.com/bep/gitmap v1.0.0
go: finding github.com/sanity-io/litter v1.1.0
go: finding github.com/cpuguy83/go-md2man v1.0.8
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/bep/debounce v1.2.0
go: finding github.com/spf13/fsync v0.0.0-20170320142552-12a01e648f05
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/BurntSushi/toml v0.0.0-20170626110600-a368813c5e64
go: finding github.com/nicksnyder/go-i18n v1.10.0
go: finding github.com/yosssi/ace v0.0.5
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/disintegration/imaging v1.5.0
go: finding github.com/olekukonko/tablewriter v0.0.0-20180506121414-d4647c9c7a84
go: finding github.com/BurntSushi/locker v0.0.0-20171006230638-a6e239ea1c69
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/jdkato/prose v1.1.0
go: finding github.com/mitchellh/hashstructure v1.0.0
go: finding github.com/alecthomas/chroma v0.6.2
go: finding github.com/alecthomas/assert v0.0.0-20170929043011-405dbfeb8e38
go: finding github.com/eknkc/amber v0.0.0-20171010120322-cdade1c07385
...
</pre>

Why does `go` need to "find" anything in order to clean my cache?

**Comment by bcmills** [comment]
Dup of #28680.
