### ISSUE TITLE
x/build/env/android: fix build for Go 1.11 and Go 1.12?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30485]
Android builds on GCE work as of Go tip.

But they're running & failing on build.golang.org for the 1.11 and 1.12 branches too. They're failing because they lack the exec wrapper.

We could add an exec wrapper in the Dockerfile in /usr/local/bin, though, that builds the exec wrapper & runs it as necessary, making assumptions about the compiler being already built at /goroot/go/bin/go , etc.

Worth it? Or should I disable the Android GCE builders for the older releases?

/cc @eliasnaur @dmitshur

**Comment by eliasnaur** [comment]
I don't care enough about 1.11 and 1.12 testing. Leave them out if you ask me.
