### ISSUE TITLE
memory leak cgo

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#30490]
use " valgrind --leak-check=full --show-leak-kinds=all  ./app",runing one day and stop valgrind. i found memory leak in cgo.
![image](https://user-images.githubusercontent.com/4704280/53609383-b02ec600-3c01-11e9-9bfc-3f2eaf2504bc.png)
![image](https://user-images.githubusercontent.com/4704280/53609390-ba50c480-3c01-11e9-8e26-a96833f77cee.png)
![image](https://user-images.githubusercontent.com/4704280/53609399-c2a8ff80-3c01-11e9-9b43-577469c9430c.png)
![image](https://user-images.githubusercontent.com/4704280/53609410-ce94c180-3c01-11e9-9b00-1bf66a5473b1.png)
![image](https://user-images.githubusercontent.com/4704280/53609415-d5233900-3c01-11e9-8c12-6910186e59b5.png)

i'm app used cgo. version 1.12

**Comment by ianlancetaylor** [comment]
This is exactly what it will look like if your application calls `C.malloc` or `C.CString` and fails to free the resulting memory.  Without more information I don't see any reason to blame cgo here.

**Comment by zhaoya881010** [comment]
@ianlancetaylor  thanks，i check use C.malloc or C.CString.
