### ISSUE TITLE
cmd/go: go list -json should provide an option to set the context to UseAllFiles=true

### ISSUE THREAD

**Issue by nim-nim** [golang/go#30504]
```console
go version go1.12 linux/amd64
```

When preparing a codebase for use on different architectures, for reuse in projects that will set (or not) specific build constrains, you do not want `go list` to filter its output based on the system the preparation steps occurs on. `go list` should have a mode that is independent of the system it runs on (at most, perhaps, restricting the output to a specific OS).

**Comment by mvdan** [comment]
`go list` loads packages, sometimes with type information; for example via flags like `-export`. To properly typecheck or build a package, it's necessary to only load the files for a specific GOOS/GOARCH pair. How would this work?

If you want to list all Go files, you should load all Go files within certain directories, not load entire packages. A package doesn't necessarily include all Go files in a directory, by its own definition.

**Comment by ianlancetaylor** [comment]
Can't you use the `IgnoredGoFiles` field for this?

**Comment by nim-nim** [comment]
I think I haven't tried it yet because 
`UseAllFiles bool   // use files regardless of +build lines, file names`
describes my need, while
`IgnoredGoFiles  []string // .go source files ignored due to build constraints`
is less clear, and probably ignore then de-ignore is too weird for my brain.

Also `IgnoredGoFiles` seems `.go` specific, while `UseAllFiles` is nicely generic.

But if you tell me that's the exact same end-result, sure, I will do it that way.

**Comment by jayconrod** [comment]
I think `IgnoredGoFiles` is what you want. That will contain .go files that would have been in `GoFiles` had `UseAllFiles` been set.

I don't think `go list` can necessarily implement `UseAllFiles` the same way `go/build` does in any case. `go list` loads a dependency graph of packages, and that graph may be significantly altered if build constraints are ignored. For example, you could end up with dependency cycle errors when no dependency cycle exists on any specific platform.

**Comment by nim-nim** [comment]
Ok, thanks for the clarification. I'll try this. Hopefully, it won't hit a corner case no one though of yet.
