### ISSUE TITLE
x/tools: vet brings massive amount of dependencies, errors when building

### ISSUE THREAD

**Issue by ainar-g** [golang/go#30506]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
go version go1.12 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ainar/go"
GOPROXY=""
GORACE=""
GOROOT="/home/ainar/go/go1.11"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ainar/dev/vcf-killer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build449598646=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```sh
$ go get -u golang.org/x/tools/go/analysis/cmd/vet
```

### What did you expect to see?
A few deps, successful build.

### What did you see instead?

<details><summary>A lot.</summary><br><pre>
$ go get -u golang.org/x/tools/go/analysis/cmd/vet
go: finding golang.org/x/tools/go/analysis/cmd/vet latest
go: finding golang.org/x/tools/go/analysis/cmd latest
go: finding golang.org/x/tools/go/analysis latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190228203856-589c23e65e65
go: finding golang.org/x/sync latest
go: finding golang.org/x/net latest
go: finding github.com/golang/protobuf v1.3.0
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: finding google.golang.org/genproto latest
go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
go: finding golang.org/x/exp v0.0.0-20190121172915-509febef88a4
go: finding google.golang.org/grpc v1.19.0
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding golang.org/x/lint latest
go: finding golang.org/x/exp latest
go: finding honnef.co/go/tools latest
go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding google.golang.org/appengine v1.1.0
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding github.com/client9/misspell v0.3.4
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding github.com/golang/mock v1.1.1
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding cloud.google.com/go v0.26.0
go: finding golang.org/x/sys latest
go: finding golang.org/x/oauth2 latest
go: finding cloud.google.com/go v0.34.0
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding github.com/golang/glog latest
go: finding github.com/golang/mock v1.2.0
go: finding cloud.google.com/go v0.36.0
go: finding golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding github.com/google/pprof v0.0.0-20181206194817-3ea8567a2e57
go: finding golang.org/x/tools v0.0.0-20181030000716-a0a13e073c7b
go: finding github.com/googleapis/gax-go/v2 v2.0.3
go: finding github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/google/martian v2.1.0+incompatible
go: finding go.opencensus.io v0.18.0
go: finding golang.org/x/build v0.0.0-20190111050920-041ab4dc3f9d
go: finding golang.org/x/time v0.0.0-20181108054448-85acf8d2951c
go: finding google.golang.org/api v0.1.0
go: finding golang.org/x/time latest
go: finding google.golang.org/grpc v1.17.0
go: finding google.golang.org/grpc v1.16.0
go: finding github.com/google/btree latest
go: finding google.golang.org/genproto v0.0.0-20190201180003-4b09977fb922
go: finding golang.org/x/lint v0.0.0-20180702182130-06c8688daad7
go: finding golang.org/x/net v0.0.0-20181106065722-10aee1819953
go: finding golang.org/x/tools v0.0.0-20180828015842-6cd1fcedba52
go: finding honnef.co/go/tools v0.0.0-20180728063816-88497007e858
go: finding honnef.co/go/tools v0.0.0-20190106161140-3f1c8253044a
go: finding golang.org/x/build latest
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/google/pprof latest
go: finding github.com/coreos/go-systemd v0.0.0-20181012123002-c6f51f82210d
go: finding github.com/shurcooL/htmlg v0.0.0-20170918183704-d01228ac9e50
go: finding go.opencensus.io v0.19.0
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
go: finding github.com/shurcooL/htmlg latest
go: finding github.com/sourcegraph/syntaxhighlight v0.0.0-20170531221838-bd320f5d308e
go: finding github.com/coreos/go-systemd latest
go: finding golang.org/x/crypto v0.0.0-20181030102418-4d3f4d9ffa16
go: finding google.golang.org/api v0.0.0-20180910000450-7ca32eb868bf
go: finding golang.org/x/oauth2 v0.0.0-20181017192945-9dcd33a902f4
go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/shurcooL/issues v0.0.0-20181008053335-6292fdc1e191
go: finding dmitri.shuralyov.com/service/change v0.0.0-20181023043359-a85b471d5412
go: finding github.com/shurcooL/notifications v0.0.0-20181007000457-627ab5aea122
go: finding golang.org/x/crypto latest
go: finding github.com/shurcooL/reactions v0.0.0-20181006231557-f2e0b4ca5b82
go: finding github.com/gregjones/httpcache latest
go: finding github.com/golang/lint v0.0.0-20180702182130-06c8688daad7
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/sourcegraph/syntaxhighlight latest
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/flynn/go-shlex latest
go: finding google.golang.org/appengine v1.3.0
go: finding github.com/shurcooL/issues latest
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: finding github.com/jellevandenhooff/dkim v0.0.0-20150330215556-f50fe3d243e1
go: finding dmitri.shuralyov.com/service/change latest
go: finding github.com/grpc-ecosystem/grpc-gateway v1.5.0
go: finding dmitri.shuralyov.com/state v0.0.0-20180228185332-28bcc343414c
go: finding github.com/shurcooL/notifications latest
go: finding golang.org/x/perf v0.0.0-20180704124530-6e6d33e29852
go: finding github.com/googleapis/gax-go v2.0.0+incompatible
go: finding github.com/golang/lint latest
go: finding google.golang.org/genproto v0.0.0-20181029155118-b69ba1387ce2
go: finding golang.org/x/sys v0.0.0-20181029174526-d69651ed3497
go: finding github.com/shurcooL/gofontwoff v0.0.0-20180329035133-29b52fc0a18d
go: finding github.com/shurcooL/reactions latest
go: finding github.com/google/go-querystring v1.0.0
go: finding github.com/shurcooL/httperror v0.0.0-20170206035902-86b7830d14cc
go: finding github.com/jellevandenhooff/dkim latest
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding dmitri.shuralyov.com/state latest
go: finding github.com/microcosm-cc/bluemonday v1.0.1
go: finding golang.org/x/perf latest
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/shurcooL/gofontwoff latest
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding dmitri.shuralyov.com/html/belt v0.0.0-20180602232347-f7d459c86be0
go: finding github.com/shurcooL/httperror latest
go: finding github.com/sourcegraph/annotate v0.0.0-20160123013949-f4cad6c6324d
go: finding github.com/prometheus/client_model latest
go: finding github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
go: finding github.com/grpc-ecosystem/grpc-gateway v1.7.0
go: finding github.com/googleapis/gax-go v2.0.2+incompatible
go: finding github.com/shurcooL/gopherjslib v0.0.0-20160914041154-feb6d3990c2c
go: finding github.com/microcosm-cc/bluemonday v1.0.2
go: finding grpc.go4.org v0.0.0-20170609214715-11d0a25b4919
go: finding dmitri.shuralyov.com/html/belt latest
go: finding github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/sourcegraph/annotate latest
go: finding github.com/shurcooL/gopherjslib latest
go: finding github.com/shurcooL/home v0.0.0-20181020052607-80b7ffcb30f9
go: finding github.com/shurcooL/issuesapp v0.0.0-20180602232740-048589ce2241
go: finding gopkg.in/inf.v0 v0.9.1
go: finding grpc.go4.org latest
go: finding github.com/shurcooL/httpgzip v0.0.0-20180522190206-b1c53ac65af9
go: finding github.com/beorn7/perks latest
go: finding google.golang.org/grpc v1.14.0
go: finding github.com/tarm/serial latest
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/stretchr/objx v0.1.1
go: finding github.com/google/go-github v17.0.0+incompatible
go: finding github.com/gopherjs/gopherjs latest
go: finding github.com/shurcooL/component v0.0.0-20170202220835-f88ec8f54cc4
go: finding git.apache.org/thrift.git v0.12.0
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/shurcooL/httpgzip latest
go: finding github.com/neelance/astrewrite v0.0.0-20160511093645-99348263ae86
go: finding github.com/shurcooL/users v0.0.0-20180125191416-49c67e49c537
go: finding github.com/shurcooL/webdavfs v0.0.0-20170829043945-18c3829fa133
go: finding github.com/shurcooL/github_flavored_markdown v0.0.0-20181002035957-2122de532470
go: finding github.com/shurcooL/component latest
go: finding cloud.google.com/go v0.31.0
go: finding google.golang.org/api v0.0.0-20181030000543-1d582fd0359e
go: finding github.com/shurcooL/webdavfs latest
go: finding github.com/openzipkin/zipkin-go v0.1.1
go: finding github.com/shurcooL/users latest
go: github.com/golang/lint@v0.0.0-20190227174305-5b3e6a55c961: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/pkg/errors v0.8.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding golang.org/x/sys v0.0.0-20181116152217-5ac8a444bdc5
go: finding google.golang.org/appengine v1.2.0
go: finding dmitri.shuralyov.com/app/changes v0.0.0-20180602232624-0a106ad413e3
go: finding github.com/shurcooL/highlight_go v0.0.0-20181028180052-98c3abbbae20
go: finding sourcegraph.com/sourcegraph/go-diff v0.5.0
go: finding github.com/shurcooL/highlight_diff v0.0.0-20170515013008-09bb4053de1b
go: finding golang.org/x/net v0.0.0-20181029044818-c44066c5c816
go: finding github.com/gliderlabs/ssh v0.1.1
go: finding github.com/shurcooL/events v0.0.0-20181021180414-410e4ca65f48
go: finding github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
go: finding github.com/prometheus/client_golang v0.8.0
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding github.com/shurcooL/octicon v0.0.0-20181028054416-fa4f57f9efb2
go: finding github.com/go-kit/kit v0.8.0
go: finding go4.org v0.0.0-20180809161055-417644f6feb5
go: finding github.com/shurcooL/httpfs v0.0.0-20171119174359-809beceb2371
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding google.golang.org/genproto v0.0.0-20181202183823-bd91e49a0898
go: finding github.com/gogo/protobuf v1.1.1
go: finding github.com/neelance/sourcemap v0.0.0-20151028013722-8c68805598ab
go: finding github.com/ghodss/yaml v1.0.0
go: finding github.com/kr/text v0.1.0
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/kr/pty v1.1.3
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: finding github.com/bradfitz/go-smtpd v0.0.0-20170404230938-deb6d6237625
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/sirupsen/logrus v1.2.0
go: finding gopkg.in/yaml.v2 v2.2.1
go get: error loading module requirements
</pre></details>

**Comment by mvdan** [comment]
See #29935 and #27858; I'd probably consider this to be a duplicate of the second issue. x/tools master only depends on appengine now, which will also go away soon; see its go.mod file.

**Comment by ainar-g** [comment]
If the problem is being worked on, I don't have any problems with closing this issue. Although the

```go get: error loading module requirements```

at the end still seems mysterious.

**Comment by mvdan** [comment]
I imagine the error is because of https://github.com/golang/lint/issues/436:

```
go: github.com/golang/lint@v0.0.0-20190227174305-5b3e6a55c961: parsing go.mod: unexpected module path "golang.org/x/lint"
```

Anyway, I'd expect that the two issues I linked to would fix this issue. I'm not sure if leaving this open in the meantime is a good idea; I'll leave it to you. Perhaps we can close it for now, and reopen if the issue persists after both of those are closed.

**Comment by ainar-g** [comment]
Closing for now.
