### ISSUE TITLE
cmd/go: go list needs a -fmt -json mode like go mod edit

### ISSUE THREAD

**Issue by nim-nim** [golang/go#30503]
```console
$ go version
go version go1.12 linux/amd64
$ go list -json ./...
go: finding github.com/…
…
	fatal: unable to access 'https://github.com/…': Could not resolve host: github.com
```
→ No useful output. I don’t care if some json fields would be better populated with network access, just because you ask json output does not mean you will use every single json field.

Ironically, `go mod edit` does not have this module-induced problem

```console
$ go mod edit -fmt -json go.mod
```
→ just works.

Lastly:

```console
$ GO111MODULE=off go list -json ./...
```
→ works but `GO111MODULE ` is going away and in off mode `go list` does not list the `go.mod` files that could be fed to `go mod edit -fmt -json` for parsing

*`go list -json` needs a pure passive mode that does not change files on disk or attempts to download other things, similar to `go mode edit -json -fmt`*

**Comment by bcmills** [comment]
`-fmt` is the wrong name for the flag, since it's not actually formatting anything.

Beyond that, I think this is a dup of #29452.

**Comment by nim-nim** [comment]
`-fmt` is the wrong name for  `go mode edit` too, it's not really a formatting option, it's a “passive mode no update not internet access no clever anything, just read existing files as they are without changing them and report”
