### ISSUE TITLE
all: don't leave cruft in TMPDIR

### ISSUE THREAD

**Issue by bsiegert** [golang/go#30500]
I am seeing this on the `netbsd-arm-bsiegert` builder, which is a machine on my desk.

### What did you expect to see?

When a given build is finished, I expect the temporary directory to be empty

### What did you see instead?

After a few builds, I see:

 * empty directories named `apidiff_test114645224` (numbers vary, of course)
 * a number of directories named `go-build335909615` and similar. Most are empty, some contain a single file named `-.o`.
 * directories named `go-link-TestDWARF121756209` and similar, containing two files: `testprog.exe` and `testprogcgo.exe`.
 * empty directories named `go-tool-dist-012775550` and similar.
 * directories named `vet_test051740249`, containing a file `testvet.exe`.
 * directories named `proxy-<number>` and containing a tree of downloaded modules, with `.info`, `.mod` and `.zip` files.

While this is not a big deal per se, this means that the temp directory tends to get full, or run out of inodes over a few weeks.

We could either fix the place in the code that leaves these files behind, or maybe make the builder clean up all the remaining temp files after a build, perhaps by creating a subdirectory with the name of the build and then recursively deleting that.

Right now, I added a cronjob to clean out `/var/gobuilder/tmp` but I would rather not have to.

**Comment by ianlancetaylor** [comment]
Some of this is fixed by https://golang.org/cl/163237, awaiting review.

**Comment by bradfitz** [comment]
Thanks for filing. I'll keep this open to track the things to clean up, but the infrastructure side of things is already tracked in #23619.

**Comment by siebenmann** [comment]
Building the current git tip (`devel +45861a64d3`) on a 64-bit x86 Fedora 29 machine, a plain `make.bash` leaves nothing behind in my TMPDIR, but `all.bash` leaves me with the following collection:

````
$ ls -1F
025411735/
cshared177880881/
go-link-TestDWARF249803548/
plugin_test302706659/
vet_test698846110/
````

The all-numeric directory is empty. go-link-TestDWARF contains testprog.exe  testprogcgo.exe; vet_test contains testvet.exe; the other two directories contain directory trees with various files in them.

**Comment by ianlancetaylor** [comment]
I believe that everything mentioned in https://github.com/golang/go/issues/30500#issuecomment-468801088 is now fixed.  Is there anything else to do here?

**Comment by bradfitz** [comment]
Feel free to close. I'll reopen if there are problems when I deploy the build coordinator side of things that validates that we don't regress here.
