### ISSUE TITLE
crypto: document error behavior for Signer.PublicKey & Decrypter.PublicKey

### ISSUE THREAD

**Issue by optnfast** [golang/go#30510]
[crypto.Decrypter](https://golang.org/pkg/crypto/#Decrypter) and the similar crypto.Signer both define `PublicKey()` methods which are supposed to return the public key corresponding to the private key used for decryption/signing.

An implementation of `PublicKey()` that supports nShield HSMs may fail for a couple of reasons:
- if all you have is a private key handle, it is not (usually) possible to recover the public key from it.
- an error may occur while exporting a key.

With this in mind my requests are:

1. Please could the API documentation define what `PublicKey()` should do when an error occurs. Returning `nil` or panicing with an informative message seem like the likely options.
2. If at some time backward compatibility can be broken, please add an additional `error` return value to `PublicKey()`.

**Comment by FiloSottile** [comment]
It should probably panic, letting a nil float around is almost always regrettable. Also, most if not all crypto.Signer users are going to fail because they use the public key type to learn the key type.

**Comment by FiloSottile** [comment]
I tried coming up with some wording for this, but in fact I don't think an implementation of Signer or Decrypter that can't provide the public key will work anywhere. That might have been a mistake, but it's too late to change.

When I had situations like this I wrote wrappers that take the public key from configuration.
