### ISSUE TITLE
misc/android: go_android_exec: no exit code

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30512]
I see some flakes on the android emu builders with:

```
go_android_exec: no exit code: ""
```

**Comment by eliasnaur** [comment]
Seems fixed to me. The only flake I saw since CL 164661 went in was network related:

https://build.golang.org/log/7c988fa28016f51c83989d47665143703a63f701

@bradfitz I'll leave it to you when to enable Android trybots for the main repository.
