### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference | 

### ISSUE THREAD

**Issue by beingsagir** [golang/go#30532]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.5
</pre>

### Does this issue reproduce with the latest release?
Have not checked with 1.12

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sagir/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sagir/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5v/fhcy_j8s0cx8ctzgdgc63sb80000gp/T/go-build384150735=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
<pre>
package main

import(
	"fmt"
	"io/ioutil"
)

type Page struct {
	Title string
	Body []byte
}

func (p *Page) save() error{
	filename := p.Title + ".txt"
	return ioutil.WriteFile(filename, p.Body, 0600)
}

func loadPage(title string) (*Page, error){
	filename := title + ".txt"
	body, err := ioutil.ReadFile(filename)
	if err != nil{
		return nil, err
	}
	return &Page{Title: title, Body: body}, nil
}

func main() {
	p1 := &Page{Title: "TestPage", Body: []byte("This is a sample Page.")}
	p1.save()
	p2, _ := loadPage("TestPage")
	fmt.Println(string(p2.Body))
}

</pre>

### What did you expect to see?

This is a sample Page.

### What did you see instead?

<pre>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1093343]

goroutine 1 [running]:
main.main()
        /Users/sagir/Documents/sandbox/go/go-web-app-basics/wiki.go:31 +0xd3
</pre>

**Comment by ALTree** [comment]
`loadPage` failed for some reason and is returning a `nil` `Page`. 

```
p2, _ := loadPage("TestPage")
```

you are ignoring the error return value here. Don't do that. Assign it to a variable and check it. You'll likely find out that the file cannot be read (maybe a filesystem permission issue), and that's why the returned `Page` is nil.

Closing here, since it doesn't appear to be a Go bug.

**Comment by shuwenhe** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

**Comment by ianlancetaylor** [comment]
@shuwenhe This issue is closed.  If you are trying to report a problem please open a new issue.  Thanks.
