### ISSUE TITLE
decrement operator is not giving appropritate value

### ISSUE THREAD

**Issue by WeirdMagician** [golang/go#30544]
### What version of Go are you using (`go version`)?
go version go1.11.2 windows/amd64

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes replicated in Go playground

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kh2398\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\kh2398\go
set GOPROXY=
set GORACE=
set GOROOT=c:\Go
set GOTMPDIR=
set GOTOOLDIR=c:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\kh2398\AppData\Local\Temp\go-build120941882=/tmp/go-build -gno-record-gcc-switches

go env Output

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
GoLang Learner

https://play.golang.org/p/BGLarSgVfFu
package main

import "fmt"

func main() {

	i := 1.1
	i++
	i--
	i--

	fmt.Println(i)
}

### What did you expect to see?
0.1

### What did you see instead?
0.10000000000000009

**Comment by mvdan** [comment]
This is how floating point numbers work. If you want exact arithmetic, use integers or https://golang.org/pkg/math/big/. Also see other similar questions like https://www.reddit.com/r/golang/comments/7jzwk3/how_can_i_fix_the_floating_point_calculation_here/.
