### ISSUE TITLE
cmd/gofmt: add missing space if any in beginning of comment

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#30540]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.10.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rajag\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\rajag\go
set GORACE=
set GOROOT=C:\Installations\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Installations\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rajag\AppData\Local\Temp\go-build212850038=/tmp/go-bu
ild -gno-record-gcc-switches
</pre></details>

### What did you do?

https://play.golang.org/p/N4WdI_Bjdpq

### What did you expect to see?

space in beginning of comment
~~~go
type employee struct {
	name  string // name
	age   int    // age
	email string // email
}
~~~

### What did you see instead?
~~~go
type employee struct {
	name  string //name
	age   int    //age
	email string // email
}
~~~

**Comment by agnivade** [comment]
A similar proposal here https://github.com/golang/go/issues/27949 which has been rejected. On the same vein, since the language spec does not say anything about what goes inside comments, I don't think gofmt should mess with it.

There are also valid comments like `//go:noescape`, `//go:noinline`, `//go:linkname` which do not have a preceding space.

/cc @griesemer for decision.

**Comment by griesemer** [comment]
What @agnivade said. Also, what about comments such as `//////////` (some people like that) or `//--------` etc.? Where do we draw the line with extra rules?

I agree that it would be nice if gofmt would "clean up" messy comments. In fact it already does try to align stars in comments such as

```Go
/* bla bla bla
 * ...
 * ...
 */
```

but it doesn't always work and it's not clear it was a good idea in the first place. I'm hesitant to interfere more with the contents of comments at this point.

Thanks for the suggestion, but I'd rather not add another somewhat ad-hoc heuristic. There will be just too many exceptions to the rule.

**Comment by santhosh-tekuri** [comment]
I think `//go:noescape, //go:noinline, //go:linkname` inside method and struct fields
are not treated as compiler pragmas. 
in such comments we can add missing space

**Comment by agnivade** [comment]
As @griesemer has already said, there are too many ways this can go wrong. Different people have different preferences for comments. And adding special handling inside method and struct fields would unnecessarily add more complexity.
