### ISSUE TITLE
net/http: add built-in mime type for *.mjs

### ISSUE THREAD

**Issue by dkumor** [golang/go#30547]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/daniel/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daniel/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build067538039=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given a folder with the following files:

index.html:
```html
<html>
<body>
<script type="module" src="test.mjs"></script>
</body>
</html>
```
and test.mjs (see: https://developers.google.com/web/fundamentals/primers/modules)
```js
console.log("hi!");
```
My code serves the above with `http.FileServer`, and I navigate to `/` in my browser, opening `index.html`

### What did you expect to see?

I expected `hi` to be printed in the javascript console

### What did you see instead?

The following error in chrome:
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

This is because `.mjs` is not a recognized mimetype. This can easily be worked around by manually adding `.mjs` to the mime database:
```go
mime.AddExtensionType(".mjs", "application/javascript")
```
Or, technically, one can just use `.js` - but `.mjs` seems to be commonly used.

However, since es modules are a standard, and will become more common in the future, it would be nice to have the mimetype built in.

**Comment by bradfitz** [comment]
Is there an official spec that's proposing standardizing that mime type for that extension? (something more formal that the page you linked)

**Comment by dkumor** [comment]
That's a good question. There is currently a draft starting to take shape towards a special mimetype for `mjs`, but is a work in progress:
https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/

The existing RFC 4329, specifies only `application/javascript` as a valid mimetype for javascript
https://tools.ietf.org/html/rfc4329

This is corroborated by the IANA website, which uses `application/javascript` as the *only* mimetype for javascript.
https://www.iana.org/assignments/media-types/media-types.xhtml


Also useful might be the following notes regarding the mjs extension's mimetype:

- Python merged in `application/javascript` https://bugs.python.org/issue31715
- Node' proposes it to be a "web-compatible javascript mime" https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#321-mime-of-mjs-files
- There are people arguing for `application/javascript+module`, but that is, once again, not formal: https://github.com/tc39/ecma262/issues/322

**Comment by andybons** [comment]
With https://github.com/golang/go/issues/31327 landed perhaps this should go in, too.

**Comment by bradfitz** [comment]
Sure. Send a change. Makes sense to also do it in Go 1.13 to match #31327.

**Comment by andybons** [comment]
Looks like it was already done in https://golang.org/cl/169502

Closing :)

**Comment by dkumor** [comment]
It looks like the mime type added was `text/javascript` in [mime/type.go line 72](https://github.com/golang/go/blob/master/src/mime/type.go#L72), which was obsoleted, and replaced with `application/javascript` in [RFC 4329](https://tools.ietf.org/html/rfc4329). 

It is my understanding the mimetype should therefore be `application/javascript`.
This is corroborated by the IANA website, which uses `application/javascript` as the only mimetype for javascript (https://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by bradfitz** [comment]
@dkumor, I sent a fix. Thanks.
