### ISSUE TITLE
html/template does not support javascript module

### ISSUE THREAD

**Issue by dkumor** [golang/go#30546]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/daniel/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daniel/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build067538039=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
The following code creates an html/template Template, and passes in a struct inside a script tag with type "module" (for reference: https://developers.google.com/web/fundamentals/primers/modules)

```go
package main

import (
	"bytes"
	"fmt"
	"html/template"
)

type mystruct struct {
	Foo string `json:"foo"`
	Bar int    `json:"bar"`
}

func main() {
	b := new(bytes.Buffer)
	tpl := template.Must(template.New("moduletest").Parse(`
	<html>
		<body>
		<script type="module">
			var properties = {{ . }};
		</script>
		</body>
	</html>
	`))
	tpl.Execute(b, mystruct{
		Foo: "Hello World",
		Bar: 42,
	})

	fmt.Printf("%s", b.String())

}

```

### What did you expect to see?

This is the result when I remove `type="module"`, and is what I expected to see:
```html
<html>
	<body>
	<script >
		var properties = {"foo":"Hello World","bar":42};
	</script>
	</body>
</html>
```

### What did you see instead?

```html
<html>
	<body>
	<script type="module">
		var properties = {Hello World 42};
	</script>
	</body>
</html>
```

I considered a pull request adding module to the recognized mime-types for html template, but since modules use import syntax/have other features that might not be handled by the current template code, I decided to hold off.

**Comment by agnivade** [comment]
We already https://go-review.googlesource.com/c/go/+/135417 for this.

**Comment by dkumor** [comment]
oops, my bad - I didn't notice the extra issue tracker.
