### ISSUE TITLE
cmd/go: "install -v" does not reliably print changed package names

### ISSUE THREAD

**Issue by kevinburke** [golang/go#30556]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

I can't reproduce this 100% of the time, but generally, make a change to "github.com/kevinburke/travis/lib/travis.go" - add a package level variable, add a header to NewRequest, add a Do implementation that calls c.Client.Do.

Then recompile with `cd $GOPATH/src/github.com/kevinburke/travis && go install -v ./...`

#### What did you expect to see?

I expect to see `github.com/kevinburke/travis/lib` in the list of changed packages.

#### What did you see instead?

It does not appear in the output.

#### Does this issue reproduce with the latest release (go1.12)?

No

#### System details

```
go version devel +4fb900e9ca Mon Mar 4 01:22:28 2019 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kevin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kevin"
GOPROXY=""
GORACE=""
GOROOT="/Users/kevin/go"
GOTMPDIR=""
GOTOOLDIR="/Users/kevin/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +4fb900e9ca Mon Mar 4 01:22:28 2019 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +4fb900e9ca Mon Mar 4 01:22:28 2019 +0000
uname -v: Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G5019
lldb --version: lldb-1000.11.38.2
  Swift-4.2
```

**Comment by kevinburke** [comment]
Apologies; the first draft of this bug report said "Yes" for "can reproduce with Go 1.12"; the answer is "No" so this is a regression.

**Comment by mvdan** [comment]
Are you by any chance making changes that had been compiled before? If the only non-cached operation is linking a binary, and not compiling any package, I've seen `go install` use my CPU while not printing anything.

**Comment by bcmills** [comment]
CC @jayconrod

**Comment by bcmills** [comment]
What @mvdan said: if you're just making a change, it's possible that the result of the build is already cached. (The Go build cache is content-addressed, so the cache can hit even if the mtime of the inputs has changed.)

**Comment by kevinburke** [comment]
Ohhh man I'm an idiot. I changed my vim-go settings for leader+d from "check if this compiles" to "check if this compiles AND build the package." The reason it was inconsistent was I wasn't rerunning the syntax checker between every build, so sometimes it would appear and sometimes it wouldn't.

Feel free to add a "ProblemBetweenKeyboardAndChair" label.
