### ISSUE TITLE
Escape analysis analogy seems not correct

### ISSUE THREAD

**Issue by ramvasanth** [golang/go#30554]
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rama.moorthy\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\rama.moorthy\
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\RAMA~1.MOO\AppData\Local\Temp\go-build138480882=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

escape analysis says that slice array b is moved to heap , but after printing the address of slice array , its address is adjacent to stack variable i address. 

This is the program

![image](https://user-images.githubusercontent.com/350578/53706900-7a8b1680-3e67-11e9-8bfc-20f19c8f6dd9.png)

https://play.golang.org/p/wGjw7wPQgu9
-->

### What did you expect to see?

i expect to see the address of b should not be adjacent to stack address

### What did you see instead?

![image](https://user-images.githubusercontent.com/350578/53706811-1bc59d00-3e67-11e9-9b23-9adc1bad15b0.png)

**Comment by randall77** [comment]
The address of `b` is a stack address. The first element of the slice is `&b[0]`, not `&b`.
You might want to read https://blog.golang.org/go-slices-usage-and-internals

**Comment by ramvasanth** [comment]
Thanks @randall77 . 

I read the slice internal doc. but still why slice is allocated in stack rather than in heap. escape analysis says it will allocate into heap.

**Comment by randall77** [comment]
The backing store for the slice (the array) is allocated on the heap.  The slice itself (the 3-word structure consisting of pointer to the array, a length, and a capacity) is allocated on the stack.

When the escape analysis says "b escapes to heap", it means that the values in `b` are written to the heap. So anything referenced by `b` must be in the heap also. `b` itself need not be.

If `b` itself needs to be on the heap, escape analysis will say "&b escapes to heap".

**Comment by ramvasanth** [comment]
Hi @randall77 , Yes you are right,  address of b[0] should refer to heap address(lower address in virtual memory). but its not pointing 

address of i --> 0xc00007ff50

address of b[0], and b[1] --> 0xc00005a070,  0xc00005a071

my objective is that i wanna make sure that backing array is pointing to heap memory according to escape analysis.

Thanks.

**Comment by randall77** [comment]
Your assumption that heap addresses are lower in virtual memory is incorrect. Pages of Go heap and pages of goroutine stacks are intermingled.

**Comment by ramvasanth** [comment]
@randall77 , Thanks... that clears all my questions.
