### ISSUE TITLE
doc: Release History doesn't mention 1.11.5

### ISSUE THREAD

**Issue by cespare** [golang/go#30552]
The release history page doesn't list the go1.11.5 minor release:

https://golang.org/doc/devel/release.html#go1.11.minor

However, tip.golang.org has it:

https://tip.golang.org/doc/devel/release.html#go1.11.minor

Does the main website need a redeploy or something?

cc @dmitshur

**Comment by dmitshur** [comment]
Yes, it has been fixed on `master` and backported to `release-branch.go1.12` branch via [CL 164077](https://golang.org/cl/164077), so it'll show up next time golang.org is redeployed.

**Comment by cespare** [comment]
OK, closing this as a duplicate of #30431.

Can you explain why website fixes aren't deployed after they're merged, though?

**Comment by dmitshur** [comment]
> Can you explain why website fixes aren't deployed after they're merged, though?

Fixes tend to come in at varying rates, sometimes many per day. When many fixes come in rapidly, as long as they're just cosmetic or nice-to-have, we tend to batch them and deploy the website once per many fixes. If it's critical or time-sensitive, we deploy sooner.

Missing notes or links about the current release are worth deploying sooner.
