### ISSUE TITLE
os: RemoveAll doesn't remove nested un-readable directories

### ISSUE THREAD

**Issue by cespare** [golang/go#30555]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. It is a new regression in Go 1.12.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/caleb/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/caleb/p/go:/home/caleb"
GOPROXY=""
GORACE=""
GOROOT="/home/caleb/apps/go"
GOTMPDIR=""
GOTOOLDIR="/home/caleb/apps/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0
-fdebug-prefix-map=/tmp/go-build954814215=/tmp/go-build
-gno-record-gcc-switches"
</pre></details>

### What did you do?

os.RemoveAll doesn't remove nested directories if they are read-only. It does work if the top directory (i.e., the argument provided to RemoveAll) is read-only.

[Demo:](https://play.golang.org/p/YxVWdMBTibL)

```
package main

import (
	"log"
	"os"
	"path/filepath"
)

func main() {
	target := filepath.Join("d0", "d1")
	if err := os.MkdirAll(target, 0755); err != nil {
		log.Fatal(err)
	}
	if err := os.Chmod(target, 0300); err != nil {
		log.Fatal(err)
	}
	if err := os.RemoveAll("d0"); err != nil {
		log.Fatal(err)
	}
}
```

### What did you expect to see?

No output; successful execution.

### What did you see instead?

    2019/03/03 18:36:49 openat d1: permission denied

### Notes

This is a regression in Go 1.12. The bug is not present in Go 1.11.5.

The bug was introduced in https://golang.org/cl/146020, which was the fix for #27029.

Before that CL, RemoveAll would unconditionally attempt to call Remove on nested directories.

After that CL, it calls `openat` first and fails.

This regression is similar to (but distinct from) #29983, which was also caused by CL 146020.

cc @ianlancetaylor

**Comment by mvdan** [comment]
I presume this will need a backport into 1.12.1 as well.

/cc @ostenbom

**Comment by ianlancetaylor** [comment]
@gopherbot please open backport to 1.12
