### ISSUE TITLE
site: https://golang.org/doc/install incorrectly lists minumum kernel version for linux/arm as 2.6.23

### ISSUE THREAD

**Issue by davecheney** [golang/go#30559]
https://golang.org/doc/install states that the minimum kernel version for all linux platform is 2.6.23. This is not correct. The minimum for linux/arm is 2.6.27 (possibly 28), however this contradicts information from the wiki, https://github.com/golang/go/wiki/Linux

See #3897

See also https://codereview.appspot.com/7225047/

**Comment by ALTree** [comment]
The minimum requirements page seems to offer an explanation:

> Linux/ARMv5 requires much newer kernels, at least v3.1 (for __kuser_cmpxchg64). 

https://github.com/golang/go/wiki/MinimumRequirements

Not claiming this is correct, just noting this here so if we uniform the docs one way or the other we can update every place at once.

**Comment by davecheney** [comment]
@ALTree see #3897, i'd forgotten that we'd tried to address this yonks ago.

**Comment by odeke-em** [comment]
Kindly paging @cherrymui @benshi001 if y'all have some bandwidth. @davecheney might you be free to help send a CL for this change? Thank you.

**Comment by Windsooon** [comment]
Maybe we can just add [MinimumRequirements](https://github.com/golang/go/wiki/MinimumRequirements) link to https://golang.org/doc/install page so we can fix  #3897 and #30559. For instance:

For other content on installing, you might be interested in:

- Minimum Requirements -- What operating system version you need to run golang.
- Managing Go installations -- How to install multiple versions and uninstall.
- Installing Go from source -- How to check out the sources, build them on your own machine, and run them.

**Comment by seankhliao** [comment]
The wiki page now exists, and the install page no longer lists incorrect information
