### ISSUE TITLE
x/website: https://golang.org/project/ missing Go 1.12

### ISSUE THREAD

**Issue by davecheney** [golang/go#30558]
https://golang.org/project/ is missing a link for Go 1.12.

/cc @andybons @dmitshur

**Comment by dmitshur** [comment]
This has been fixed on `master` and backported to `release-branch.go1.12` branch via [CL 163727](https://golang.org/cl/163727).

It can be seen at https://tip.golang.org/project/. The golang.org website just needs to be redeployed.

**Comment by dmitshur** [comment]
The website is redeployed and this issue is resolved. Thanks for reporting it.
