### ISSUE TITLE
wiki: Improve GerritBot GitHub PR workflow instructions

### ISSUE THREAD

**Issue by bep** [golang/go#30564]
@dmitshur better to track this in it's own issue, than in a random CL review.

I created some noise last night about my first code CL and my struggles with Gerrit -- I spent an hour trying to do a small edit of the commit message, only to see it overwritten by the GerritBot. #24887 talks about this issue.

So, the workaround for me was eventually to edit the first comment in the original **GitHub PR**.

If you read closely on the [wki](https://github.com/golang/go/wiki/GerritBot) you may grasp this information in the FAQ (if you understand the difference between a PR and a CL), but I was looking for a reason why my commit message edits in Gerrit didn't stick (some StackOverflow thread suggested I needed to push a commit button). This was what I looked for in the documentation. 

I suggest 2 changes to the Wiki page above to make this more in the face:

>How does GerritBot determine the final commit message?
>It uses the title and description of the PR to construct the commit message for the Gerrit Change.

To something like:

>How does GerritBot determine the final commit message?
>It uses the title and description (first comment) of the GitHub PR to construct the commit message for the Gerrit Change. Also note that any edits to the commit message must be done in the GitHub PR and not on Gerrit.

And in the workflow, add a bullet saying something like this:

> Any change of the commit message must be done in the title and description (first comment) of the GitHub PR and not on Gerrit.

**Comment by thepudds** [comment]
Hi @bep, thanks for the detailed issue here. 

FWIW, I updated the wiki in an attempt to incorporate your feedback:
https://github.com/golang/go/wiki/GerritBot/_compare/80daba480c8570e7e09695efbf760da3d157d25d...6b1fd1ae2491c172056f8a7d45900e72b5574e0a

A couple of minor notes:
 * I also mentioned people should avoid trying to edit the commit message in git, which I think is another point of confusion for people.
 * I tried to avoid saying "first comment" for the PR description to avoid the small ambiguity around whether the "first comment" is the first thing after the description vs. the description itself.

Does that look like something that would have helped you when you were initially reading it, or perhaps it is unclear after my attempt?
