### ISSUE TITLE
net/http: discrepancies in the MIME Sniffing Spec and the implementation

### ISSUE THREAD

**Issue by kshitij10496** [golang/go#30570]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d71d81c5a2 Mon Mar 4 16:29:25 2019 +0530 darwin/amd64
</pre>

While reading the **MIME Sniffing Spec** and the corresponding implementation in the `net/http` package in `sniff.go`, I found few discrepancies between the two. As, I do not know whether these diffs are intentional or not (though I am curious to know), I thought it best to share my findings so that a conscious decision can be taken.

Here are few suggestions for updating the current implementation in accordance with the spec:
1. **Using _pattern_ rather than _mask_ for assertion and iteration in the [Pattern Matching Algorithm](https://mimesniff.spec.whatwg.org/#pattern-matching-algorithm).**
Currently, we are using `m.mask` instead of `m.pat` at both the places. 
The reason this substitution works is because their lengths are the equal (implicit) in all the currently support MIME signatures, and the logical AND operation: `a & b = c` `=>` `a & c = b`.
_Refer:_ https://github.com/golang/go/blob/d1887676d96daf969d886a4ec13cbad4908d51af/src/net/http/sniff.go#L185-L194

2. **Rename `image/vnd.microsoft.icon` to [`image/x-icon`](https://mimesniff.spec.whatwg.org/#matching-an-image-type-pattern) and add another signature for the same.**
We are using the same signature for `image/vnd.microsoft.icon` instead of `image/x-icon`. This could be a possible bug or a decision that should be documented as a divergence from the spec.
_Refer:_ https://github.com/golang/go/blob/d1887676d96daf969d886a4ec13cbad4908d51af/src/net/http/sniff.go#L93

3. **Using named strings instead of hexadecimal representation in `application/zip` and `application/x-rar-compressed`.**
Reading the source code, I experienced that using human-readable string definition of the signatures is an implicit convention over the mechanistic byte pattern sequences (as it should be!). These are a couple of places which can be changed with the sole purpose of maintaining consistency and improving visual aesthetics. 
_Refer:_ https://github.com/golang/go/blob/d1887676d96daf969d886a4ec13cbad4908d51af/src/net/http/sniff.go#L146-L147

4. **Reordering the `sniffSignatures` according to the section [Identifying a resource with an unknown MIME type](https://mimesniff.spec.whatwg.org/#identifying-a-resource-with-an-unknown-mime-type).**
In the current implementation, the signatures are almost sorted according to the spec, with a few exceptions. For example, matching `video/webm` before `video/mp4`.

**Comment by bradfitz** [comment]
From memory, I don't think any of this is intentional. @odeke-em, you want to handle this? You tend to work on this code most frequently lately.

**Comment by kshitij10496** [comment]
I would be happy to fix this and make my first contribution to the project! 😃

**Comment by odeke-em** [comment]
Thank you for filing this issue @kshitij10496 and welcome to the Go project! Awesome, please go for it and I am looking forward to reviewing your CL.
