### ISSUE TITLE
x/build/devapp: broken link on `reviews` page

### ISSUE THREAD

**Issue by bcmills** [golang/go#30575]
https://dev.golang.org/reviews includes an entry linking to https://go-review.googlesource.com/93515.
The latter link is currently a 404.
Perhaps we need to filter out deleted CLs?

CC @andybons

**Comment by andybons** [comment]
Sigh, yeah a consequence of #22635.

**Comment by andybons** [comment]
Added a list of deleted CLs. This shouldn't show up anymore.
