### ISSUE TITLE
Why not fix path.IsAbs but replace it with filepath.IsAbs?

### ISSUE THREAD

**Issue by huangapple** [golang/go#30587]

**Comment by ianlancetaylor** [comment]
Because `path.IsAbs` and `filepath.IsAbs` are different functions that do different things.

If you want to report a bug, please provide more details about what is wrong.  Tell us exactly what you tried, exactly what happeed, and what you expected to have happen instead.

**Comment by huangapple** [comment]
1 、path.IsAbs  and filepath.IsAbs  both of them commented is 【IsAbs reports whether the path is absolute】
2、 other languages path.IsAbs can work well on windows and linux
3、 Perhaps in many people's habits, path.IsAbs should be filepath. IsAbs， I think it's easy to make mistakes.

**Comment by ianlancetaylor** [comment]
See the first line in the docs at https://golang.org/pkg/path and https://golang.org/pkg/path/filepath.

This is not something we can change now, due to the Go 1 compatibility guarantee (https://golang.org/doc/go1compat).

**Comment by huangapple** [comment]
So here's a pit, but we can't fill in.'😂
