### ISSUE TITLE
go 1.12 not support server2003？

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#30588]
golang 1.12 ，os server2003 32bit

found error：
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll
e specified procedure could not be found.

goroutine 1 [running, locked to thread]:
syscall.(*LazyProc).mustFind(0x2e837940)
        C:/Go/src/syscall/dll_windows.go:287 +0x42
syscall.(*LazyProc).Addr(0x2e837940, 0xde5300)
        C:/Go/src/syscall/dll_windows.go:294 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x688, 0x9, 0x2e855e24
8, 0x3, 0x2e81c048)
        C:/Go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27
os.newFileStatFromGetFileInformationByHandle(0x2e8123f0, 0x30, 0x688, 0x0, 0
123f0, 0x30)
        C:/Go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x2e806cb0, 0x9f2fb4, 0x2e806cb0, 0x0, 0x2e806cb0)
        C:/Go/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x2e8123f0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/io/ioutil/ioutil.go:62 +0xac

it's ok in win7

**Comment by zhaoya881010** [comment]
1.11 not problem in server2003.

**Comment by aaronjheng** [comment]
@zhaoya881010 https://golang.org/doc/install#requirements

**Comment by zhaoya881010** [comment]
@aaronjheng build go source in server 2003?

**Comment by ianlancetaylor** [comment]
We don't support WIndows Server 2003, sorry.  It's a 16 year old OS.  We can only do so much.

**Comment by wanjochan** [comment]
said latest supporting win2k3 is go 1.10.8
