### ISSUE TITLE
malformed module path "Daddyxxx.MS.BMS": invalid char 'D' in first path element

### ISSUE THREAD

**Issue by fmyxyz** [golang/go#30598]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fmy-leaves/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fmy-leaves/Documents/gowork:/Users/fmy-leaves/gopath"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gv/1llmkg217x1bb_jsy0blklfc0000gn/T/go-build434507636=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

when build the project with cmd:
 `GO111MODULE=on  go build `

, and go.mod content is : 
```
module Daddyxxx.MS.BMS

go 1.12

replace (
	Daddyxxx.MS.Common => ../Daddyxxx.MS.Common
        Daddyxxx.MS.Drift => ../Daddyxxx.MS.Drift
	Daddyxxx.MS.Growth => ../Daddyxxx.MS.Growth
)

require (
	github.com/codegangsta/negroni v1.0.0
	github.com/go-sql-driver/mysql v1.4.1
	github.com/golang/protobuf v1.3.0
	github.com/gorilla/mux v1.7.0
	github.com/micro/go-grpc v0.11.0
	github.com/micro/go-micro v0.27.0
	github.com/micro/go-plugins v0.25.0
	github.com/opentracing/opentracing-go v1.0.2
	github.com/pkg/errors v0.8.1
	github.com/upyun/go-sdk v2.1.0+incompatible
	github.com/ylywyn/jpush-api-go-client v0.0.0-20180208091336-d2522f23f3f7
	golang.org/x/crypto v0.0.0-20190227175134-215aa809caaf
	golang.org/x/net v0.0.0-20190227160552-c95aed5357e7
	google.golang.org/grpc v1.19.0
)

```

### What did you see instead?
go: Daddyxxx.MS.BMS@v0.0.0-00010101000000-000000000000: malformed module path "Daddyxxx.MS.BMS": invalid char 'D' in first path element
go: error loading module requirements

**Comment by mvdan** [comment]
Seems like the first element of a module path must be a valid lowercase domain name, excluding non-ascii. In particular:

```
func firstPathOK(r rune) bool {
        return r == '-' || r == '.' ||
                '0' <= r && r <= '9' ||
                'a' <= r && r <= 'z'
}
```

/cc @bcmills

**Comment by bcmills** [comment]
DNS names are [case-insensitive](https://tools.ietf.org/html/rfc4343), but Go import paths (today) are not.

The first portion of a module path is expected to be a valid domain name, since that's what ensures global uniqueness of import paths.

We resolve the mismatch by requiring that the portion of the Go import path that includes the domain name appear in lower case.

**Comment by rsc** [comment]
Yes, sorry, this is an intended restriction on module paths. Use lower-case.

**Comment by fmyxyz** [comment]
thinks , I got it.

**Comment by sudo-suhas** [comment]
I understand why this is an intended restriction but it is making it difficult to adopt Go modules inside [our company](https://www.redbus.in/). We have an instance of Gitlab hosted locally(over HTTP). We have a repo which provides common building blocks for writing Go applications such as error handling and API clients to internal services. I had 'vendored' this earlier using `dep` and for whatever reason, I had to use the import path `XYZ-01.redbus.in/modules/rbgo` to make it work(still the case, see below for more details). But now I cannot migrate to Go modules because of this issue:

```
$ go get -insecure XYZ-01.redbus.in/modules/rbgo
go: finding XYZ-01.redbus.in/modules/rbgo latest
package XYZ-01.redbus.in/modules/rbgo: unknown import path "XYZ-01.redbus.in/modules/rbgo": malformed module path "XYZ-01.redbus.in/modules/rbgo": invalid char 'I' in first path element

$ go get -insecure xyz-01.redbus.in/modules/rbgo
go: finding XYZ-01.redbus.in/modules/rbgo v0.0.0-20190725041006-4a7cd3753cb9
go get xyz-01.redbus.in/modules/rbgo: unrecognized import path "xyz-01.redbus.in/modules/rbgo" (parse http://xyz-01.redbus.in/modules/rbgo?go-get=1: no go-import meta tags (meta tag XYZ-01.redbus.in/modules/rbgo did not match import path xyz-01.redbus.in/modules/rbgo))

$ curl 'http://xyz-01.redbus.in/modules/rbgo?go-get=1'
<html><head><meta name="go-import" content="XYZ-01.redbus.in/modules/rbgo git http://XYZ-01.redbus.in/modules/rbgo.git" /></head></html> 
```

Even if I am able to identify the reason for meta tags to include the domain name as 'XYZ-01', when and if I fix it, it will break existing code. Do you have any suggestions on what I could do?

**Comment by bcmills** [comment]
@sudo-suhas, you will need to update the import paths in the existing code prior to converting to modules.

One way to do that without intermediate breaking changes would be to add a new package at a new import path (say, `xyz-01.redbus.in/modules/rbgo/v2`), then rewrite the package at the previous path (`XYZ-01.redbus.in/modules/rbgo`) to forward all of its top-level declarations to the new path (using type aliases and tiny forwarding functions):

```go
package rbgo // import "XYZ-01.redbus.in/modules/rbgo"

import (
	v2 "xyz-01.redbus.in/modules/rbgo/v2"
)

type T = v2.T

func SomeFunction() *T {
	return v2.SomeFunction()
}

[…]
```

Then you can incrementally update all of the importers to refer directly to the new path, and then finally convert those importers to use modules.
