### ISSUE TITLE
Unpacking of go1.12.linux-amd64.tar.gz with java fails

### ISSUE THREAD

**Issue by krvs-esoptra** [golang/go#30593]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/var/lib/jenkins/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/lib/jenkins/go"
GOPROXY=""
GORACE=""
GOROOT="/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build720322714=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

### What did you do?

Unpack of https://dl.google.com/go/go1.12.linux-amd64.tar.gz  on a Jenkins slave

### What did you expect to see?
go1.12 being installed on the Jenkins slave 

### What did you see instead?
 The unpacking of the golang tar (by a java process) fails due to a couple of filenames in the tar containing non-ascii characters.
Error:
FATAL: Failed to install https://dl.google.com/go/go1.12.linux-amd64.tar.gz to /home/jenkins/jenkins_slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.12
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/jenkins/jenkins_slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.12/go/test/fixedbugs/issue27836.dir/??main.go
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)

Perhaps it is possible to solve the issue by tweaking the startup options of the java process (file.encoding, sun.jnu.encoding, ...) 
But it would be more robust if the tar does not contain filenames with special characters. In earlier versions (e.g. 1.11.5 ) it was not yet the case.

**Comment by agnivade** [comment]
The tar archive is in POSIX format which is the most recent and flexible format. It is perfectly valid to have non-ASCII names in a POSIX format tar archive.

In this case, the UTF-8 filename was needed for a test. So there is nothing much we can do about it. Even if we had light and full versions of the distribution, some version of it _has_ to have this file.

I would suggest you to look into the java process extracting the archive and fixing some encoding attributes that you mentioned.
