### ISSUE TITLE
testing: Test-case name convention

### ISSUE THREAD

**Issue by cn007b** [golang/go#30599]
Does it make sense to have some kind of convention to name test-cases like this: `Test_{StructName}_{MethodName}` for struct's methods and `Test_{FuncName}` for regular functions, so now it's simple to figure out method/function and navigate this test-case through project.

**Comment by mvdan** [comment]
Are you asking a question? If so, see https://github.com/golang/go/wiki/Questions.

If you're suggesting a documentation change somewhere, please clarify what you're proposing.
