### ISSUE TITLE
cmd/go: what is the `go 1.12` statement that `go mod tidy` is generating in my go.mod?

### ISSUE THREAD

**Issue by jadekler** [golang/go#30603]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12rc1 linux/amd64
</pre>

`go mod tidy` generates a go.mod as such:

```
module github.com/googleapis/google-cloud-go-testing

go 1.12

require (
	cloud.google.com/go v0.36.0
	golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
	golang.org/x/tools v0.0.0-20190305160728-f8c04913dfb7
	google.golang.org/api v0.1.0
	honnef.co/go/tools v0.0.0-20190215041234-466a0476246c
)
```

I can guess that `go 1.12` is requiring users to use Go 1.12 or greater, but is this documented in a specification somewhere? Where can I read more about this?

**Comment by bradfitz** [comment]
It's documented at https://golang.org/cmd/go/#hdr-The_go_mod_file

**Comment by ianlancetaylor** [comment]
See also #28221.

**Comment by jadekler** [comment]
Thank you!
