### ISSUE TITLE
text/template, html/template: ParseGlob does not document the pattern syntax

### ISSUE THREAD

**Issue by dmitshur** [golang/go#30608]
Packages [`text/template`](https://godoc.org/text/template) and [`html/template`](https://godoc.org/html/template) have a function named [`ParseGlob`](https://godoc.org/html/template#ParseGlob). They have the same documentation:

```Go
// ParseGlob creates a new Template and parses the template definitions from the
// files identified by the pattern, which must match at least one file. The
// returned template will have the (base) name and (parsed) contents of the
// first file matched by the pattern. ParseGlob is equivalent to calling
// ParseFiles with the list of files matched by the pattern.
//
// When parsing multiple files with the same name in different directories,
// the last one mentioned will be the one that results.
func ParseGlob(pattern string) (*Template, error)
```

The documentation of this function does not specify the rules of what the pattern should be. As a result, users reading the documentation cannot know how to use the function.

Both these packages also have a [`Template.ParseGlob`](https://godoc.org/html/template#Template.ParseGlob) method, which does specify the rules for the pattern:

```Go
// ...
// The pattern is processed by filepath.Glob and must match at least one file.
// ...
```

That information should be copied to the `ParseGlob` function documentation as well.

/cc @julieqiu @cnoellekb

**Comment by empijei** [comment]
This calls [filepath.Glob](https://golang.org/pkg/path/filepath/#Glob) which, in turn, uses [filepath.Match](https://golang.org/pkg/path/filepath/#Match) syntax. 

If we want to document it and make it part of the API I can work on a CL to add it.

/cc @mvdan for the text/template part.

**Comment by mvdan** [comment]
I don't think we can change the behavior now, so we might as well document it. I'd just make a short mention that this follows the semantics of filepath.Glob to find files.

Perhaps we can change both packages at once, too; I imagine the added godoc sentence would be practically the same.

**Comment by dmitshur** [comment]
What do you think about starting off by making the `ParseGlob` function documentation mirror `Template.ParseGlob` method? I.e.:

```diff
 // ParseGlob creates a new Template and parses the template definitions from the
-// files identified by the pattern, which must match at least one file. The
+// files identified by the pattern. The pattern is processed by filepath.Glob
+// and must match at least one file. The
 // returned template will have the (base) name and (parsed) contents of the
 // first file matched by the pattern. ParseGlob is equivalent to calling
 // ParseFiles with the list of files matched by the pattern.
 //
 // When parsing multiple files with the same name in different directories,
 // the last one mentioned will be the one that results.
 func ParseGlob(pattern string) (*Template, error)
```

Perhaps replacing "pattern is processed by filepath.Glob" with "the syntax of the pattern is the same as filepath.Match" to shortcut the hops needed.

I think it's better to continue to refer to `filepath.Match` syntax rather than copy it here, that way people know it's the same syntax, and it can't get out of sync with filepath package.

**Comment by empijei** [comment]
Sounds good to me. If you want to work on it feel free to [send a CL](https://golang.org/doc/contribute.html) with that change on both packages, for all 4 functions. I believe it is better to do this in one change.
