### ISSUE TITLE
filepath.Join returning path as \ instead of / on WINDOWS

### ISSUE THREAD

**Issue by johnbalvin** [golang/go#30616]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\john\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\codigo
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\john\AppData\Local\Temp\go-build799411330=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Join two path on windows

https://play.golang.org/p/5UUQVEXkPiY
```go
package main
import (
	"fmt"
	"path/filepath"
)

func main() {
	var first = "myPath/otherPath"
	var second = "me"
	fmt.Println(filepath.Join(first, second))
}
```

### What did you expect to see?
myPath/otherPath/me

### What did you see instead?
myPath\otherPath\me

### Trace Back
https://golang.org/src/path/filepath/path.go?h=Join#L209
https://golang.org/src/path/filepath/path_windows.go?h=Clean#L175 <- this function uses a constant
https://golang.org/src/path/filepath/path.go?h=Separator#L61 <- constant
https://golang.org/pkg/os/#PathSeparator

joinNonEmpty uses os.PathSeparator, windows return "92" that stands for , \ , that is why it ends up converting to all, /,  to \

### Posible solution
Check separator from input instead of using os.PathSeparator, if there is not a separator, then it could fall back to os.PathSeparator

instead of 

```go
p := Clean(strings.Join(elem, string(Separator)))
```
It should be: 

```go
        var separator string
	for _, path := range elem {
		if strings.Contains(path, "/") {
			separator = "/"
			break
		} else if strings.Contains(path, "\\") {
			separator = "\\"
			break
		}
	}
	if separator == "" {
		separator = string(os.PathSeparator)
	}
	Clean(strings.Join(elem, separator))
```

**Comment by go101** [comment]
This is expected. `path/filepath` package is OS aware. Please use `path.Join` instead.

**Comment by johnbalvin** [comment]
@go101 
thanks, that worked!

**Comment by mattn** [comment]
FYI: Do not use the path package for the physical disk path. If you just want slash-ed separator in the path, you shoud use filepath.ToSlash().
