### ISSUE TITLE
time.Local has trouble in chroot

### ISSUE THREAD

**Issue by tedu** [golang/go#30620]
After chroot, /etc/localtime and other files are not available, causing time.Now() to return UTC times. No biggie, this is expected, but it'd be nice if there were a way to hint that zoneinfo should be loaded before chroot. In C, I would call tzset() to force otherwise lazy initialization to take place.

I'm not clear how to best accomplish this in go. Simple workarounds like calling time.Now() in init() don't seem to dig deep enough. (or get optimized away?) For now, I can call fmt.Sprint(time.Now()) which digs deep enough that subsequent prints have the correct timezone. time.LoadLocation("Local") doesn't seem to work.

See the following code. As root, it prints UTC times. As a user, it prints local time (because chroot fails). Uncomment init line to observe "fix".

```
package main

import (
    "fmt"
    "syscall"
    "time"
)

func init() {
    //fmt.Sprint(time.Now())
}

func main() {
    syscall.Chdir("/tmp")
    syscall.Chroot("/tmp")
    fmt.Println(time.Now())
}

```

**Comment by julieqiu** [comment]
For questions about Go, see https://golang.org/wiki/Questions
