### ISSUE TITLE
runtime, internal/poll: don't ignore error in netpoll

### ISSUE THREAD

**Issue by mikioh** [golang/go#30624]
As mentioned in #30426, there is various underlying stuff that doesn't support event notification mechanisms supported by the package runtime, like epoll, kqueue. The current runtime-integrated network poller is not designed for accommodating such stuff; simply, it covers up an error value of each event in the function runtime.netpoll and expects subsequent, mostly IO, system calls to capture the error state on the underlying stuff. Unfortunately, this is far from perfect if the underlying stuff doesn't return an error in the event registration but returns an error in the event scanning.

It's better to forward an error value on each event of event scanning to poll waiters in the package internet/poll for avoiding unnecessary confusion.

/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment]
What code needs to change?  We already return the error from `runtime_pollOpen`.   I don't know where else we would get an error that is specific to a particular file descriptor.

**Comment by mikioh** [comment]
Just adding a new field to runtime.pollDesc to notify an error state on epoll_pwait or kevent, EPOLLERR in epoll_event.events or EV_ERROR in kevent.flags and kevent.data, and making netpollcheckerr handle the new error value for poll waiters in the package internal/poll might be enough [not tested].
