### ISSUE TITLE
x/mobile: build error after upgrade go to 1.12

### ISSUE THREAD

**Issue by xfxdev** [golang/go#30637]
### What version of Go are you using (`go version`)?

<pre>
go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xfx/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xfx/Development/workspace/project/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cc/l57g5px96sx4b5cnhq6bf2qh0000gn/T/go-build666588749=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
After upgrade go version to 1.12, will failed to build library for ios/android:
`gomobile bind -target=ios golang.org/x/mobile/example/bind/hello`

### What did you expect to see?
Success

### What did you see instead?
gomobile: /Users/xfx/Development/workspace/project/go/bin/gobind -lang=go,objc -outdir=/var/folders/cc/l57g5px96sx4b5cnhq6bf2qh0000gn/T/gomobile-work-547367462 -tags=ios golang.org/x/mobile/example/bind/hello failed: exit status 1
type-checking package "golang.org/x/mobile/example/bind/hello" failed (/Users/xfx/Development/workspace/project/go/src/golang.org/x/mobile/example/bind/hello/hello.go:8:8: could not import fmt (type-checking package "fmt" failed (/usr/local/opt/go/libexec/src/fmt/print.go:9:2: could not import internal/fmtsort (type-checking package "internal/fmtsort" failed (/usr/local/opt/go/libexec/src/internal/fmtsort/sort.go:12:2: could not import reflect (type-checking package "reflect" failed (/usr/local/opt/go/libexec/src/reflect/type.go:19:2: could not import runtime (type-checking package "runtime" failed (/usr/local/opt/go/libexec/src/runtime/mem_bsd.go:16:6: sysAlloc redeclared in this block)))))))))

**Comment by helperShang** [comment]
same error

**Comment by helperShang** [comment]
```
go get -u golang.org/x/mobile/cmd/...
```
build success!

**Comment by odeke-em** [comment]
Thank you for this report @xfxdev and welcome to the Go project! Thank you @helperShang for checking too.
@xfxdev as @helperShang posted in https://github.com/golang/go/issues/30637#issuecomment-470359890 could you try performing the update and try again?

**Comment by xfxdev** [comment]
Thanks @helperShang and @odeke-em, after perform the update, it's ok to build library for iOS. But still failed to build for Android:

gomobile bind -o test.aar -target=android golang.org/x/mobile/example/bind/hello
gomobile: go build -buildmode=c-shared -o=/var/folders/cc/l57g5px96sx4b5cnhq6bf2qh0000gn/T/gomobile-work-701910608/android/src/main/jniLibs/armeabi-v7a/libgojni.so gobind failed: exit status 2
# runtime/cgo
fork/exec /Users/xfx/Development/Android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang: no such file or directory

**Comment by odeke-em** [comment]
Alright, thanks for the update. I shall kindly page @eliasnaur

**Comment by eliasnaur** [comment]
Gomobile requires NDK r19b but didn't detect the NDK version well enough. If you upgrade your NDK, the error should go away.

**Comment by xfxdev** [comment]
@eliasnaur After upgrade the NDK, it works now. Thanks very much!
