### ISSUE TITLE
net/http: Server.Shutdown doc example bug: no exit on error

### ISSUE THREAD

**Issue by justinfx** [golang/go#30641]
It appears the doc example that is provided for `http.Server.Shutdown` has a bug.
https://godoc.org/net/http#Server.Shutdown

The example shows that when the listener returns, it only prints the error as opposed to being fatal. This would cause the process to block on the done channel until SIGINT is actually sent. 

Reproduction of bug:
https://play.golang.org/p/LCSLoMWIMrR

Should the error handling use `log.Fatal`?

**Comment by agnivade** [comment]
Ok, so you are talking about cases where the listener returns on its own without calling `Shutdown` or `Close`, in which case, it won't be an `ErrServerClosed`.

Let's see what @bradfitz says.

**Comment by justinfx** [comment]
That's correct. My included reproduction shows a case where a bad address was provided so the listener fails immediately. But it won't exit because its waiting on the graceful shutdown channel, which never gets touched.

**Comment by agnivade** [comment]
@bradfitz thoughts ?

**Comment by agnivade** [comment]
Fixed with https://github.com/golang/go/commit/04e2e81ecbb6a34863cb46f22d7b8f434c8b852f
