### ISSUE TITLE
x/build: "website", "build" not on dashboard

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30640]
https://build.golang.org/ doesn't have "website" listed.

Is that intentional?

**Comment by dmitshur** [comment]
It might've been intentional when x/website was a work-in-progress, but now that it's the canonical website source, it should be on the dashboard.

**Comment by dmitshur** [comment]
As mentioned in #32626, we should also add x/build subrepo to post-submit builders. /cc @bcmills

Only need limited builders (e.g., linux/amd64 on latest stable release) since it's our internal infrastructure repo, not meant for wide public consumption.

**Comment by dmitshur** [comment]
[CL 207852](https://golang.org/cl/207852) said "Fixes" but https://build.golang.org/ doesn't have x/build repo yet. Re-opening until it shows up so we don't lose track of this.

**Comment by bradfitz** [comment]
I would've just deployed it then but I worried that @cagedmantis has pending CLs that he's deploying right now (e.g. farmer.golang.org says it's at revision `fd0e1d889dc65cd1932ecb09eee047f261226535-amedee-20191119T162811`)

**Comment by dmitshur** [comment]
No worries. I just don't want us to lose track of this.

**Comment by bradfitz** [comment]
It's on there now. I guess gitmirror finally slowly populated the x/build git history into datastore.

**Comment by dmitshur** [comment]
> It's on there now. I guess gitmirror finally slowly populated the x/build git history into datastore.

x/website too. I can't help but feel there must've been another reason why it appeared now and not in any of the last few months.

**Comment by bradfitz** [comment]
@dmitshur, I also restarted gitmirror. And for x/build I manually created a datastore record. (not for x/website, though)

In any case, all this complicated code is being deleted in https://golang.org/cl/208697.
