### ISSUE TITLE
cmd/vet: rangeloop: inspect all go/defer statements prior to a loop back edge

### ISSUE THREAD

**Issue by luhexcp** [golang/go#30649]
Running go vet on this file:
```
package main

import "fmt"

func main() {
	done := make(chan bool)

	values := []string{"a", "b", "c"}
	for _, v := range values {
		go func() {
			fmt.Println(v)
			done <- true
		}()
	}

	for _ = range values {
		<-done
	}
}
```
prints
```
golang_goroutines_and_closures.go:11: loop variable v captured by func literal
```
If I change loop body to this:
```
ok := true
for _, v := range values {
	if ok {
		go func() {
			fmt.Println(v)
			done <- true
		}()
	}
}
```
then go vet prints nothing.

Looking at the vet source code, checkRangeLoop can just judge a go or defer statement for body  to see whether a variable is capture, which means vet will be failed if it exists condition sentence before a go or defer statement

**Comment by bcmills** [comment]
Making `vet` more precise for loop-variable capture is #16520. Marking as duplicate.

**Comment by luhexcp** [comment]
> Making `vet` more precise for loop-variable capture is #16520. Marking as duplicate.

can the question be sovled?

**Comment by alandonovan** [comment]
This is an interesting special case that we could easily extend the check to handle without the full generality of #16520, which is much harder to solve. Specifically: the go/defer statement is still the last statement within the loop body, if we use a slightly more generalized definition of "last" that traverses down into control constructs (such as `if`-statements in this example).

**Comment by thepudds** [comment]
Hi @luhexcp, FYI, I tried implementing an older idea from @alandonovan and sent https://go.dev/cl/452155. With that CL, go vet now complains about your second example that was not flagged before:

```go

func main() {
        done := make(chan bool)

        values := []string{"a", "b", "c"}

        ok := true
        for _, v := range values {
                if ok {
                        go func() {
                                fmt.Println(v) // vet now warns loop variable v captured by func literal
                                done <- true
                        }()
                }
        }

        for _ = range values {
                <-done
        }
}
```
