### ISSUE TITLE
flag: In parseOne (), why (false, ErrHelp) is returned when only "- help" or "- h" is passed as an argument?

### ISSUE THREAD

**Issue by zabio3** [golang/go#30655]
A custom flag.FlagSet returns a distinguished error, ErrHelp, when it sees the -help flag.

Where the code is written

 - https://github.com/golang/go/blob/master/src/flag/flag.go#L926

```

if name == "help" || name == "h" { // special case for nice help message.
	f.usage()
	return false, ErrHelp
}
```

But, If the program is called with the wrong argument, I think that you should return explanation of usage and error.

Therefore, if you pass arguments that only "help" or "h", I think that f.usage () will be executed and (true, nil) will be returned.

I would like to know why it is implemented like this.

**Comment by mvdan** [comment]
See https://golang.org/pkg/flag/#ErrorHandling; it's possible to configure a flagset to return errors. "The user requested the help text" is a kind of error, because the tool shouldn't continue as normal.

In the future, for questions, see https://github.com/golang/go/wiki/Questions.
