### ISSUE TITLE
cmd/go: go build -mod=readonly should disallow go.sum updates

### ISSUE THREAD

**Issue by rsc** [golang/go#30667]
go build -mod=readonly disallows go.mod updates.
It should also disallow go.sum updates.
Maybe it already does; I haven't checked.

**Comment by marwan-at-work** [comment]
can confirm that -mod=readonly does not disallow go.sum updates. 

```
go mod init reproduce 
go get github.com/pkg/errors
echo "" > go.sum
go build -mod=readonly
```
