### ISSUE TITLE
cmd/go: 'go mod init' error in temp directory is vague

### ISSUE THREAD

**Issue by andrewmed** [golang/go#30678]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andy/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andy/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/andy/go"
GOTMPDIR=""
GOTOOLDIR="/home/andy/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556518556=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
init go module in git repository

### What did you expect to see?
go module initialized

### What did you see instead?
go mod does not recognize vcs with three level domains:

<pre>
andy@debian-dev:/tmp/tmp.dFIHBNexOs$ git init
Initialized empty Git repository in /tmp/tmp.dFIHBNexOs/.git/
andy@debian-dev:/tmp/tmp.dFIHBNexOs$ (master) git remote add origin https://git.bar.com/baz
andy@debian-dev:/tmp/tmp.dFIHBNexOs$ (master) git remote -v
origin  https://git.bar.com/baz (fetch)
origin  https://git.bar.com/baz (push)
andy@debian-dev:/tmp/tmp.dFIHBNexOs$ (master) go mod init
go: cannot determine module path for source directory /tmp/tmp.dFIHBNexOs (outside GOPATH, no import comments)
</pre>

**Comment by andybons** [comment]
@bcmills @jayconrod

**Comment by jayconrod** [comment]
`go mod init` can automatically determine the module path (declared in the `go.mod` file) using either the current directory's position within `GOPATH` or using import comments in existing source files. Unfortunately, we can't use git remotes because they are frequently different than the module path.

In this example, the directory where `go mod init` was run is outside `GOPATH`, and there are no source files, so the module needs to be initialized with an explicit path:

```
go mod init git.bar.com/baz
```

We should have a better error message for this though, especially since a lot of people will see this the first time they try modules.

**Comment by andrewmed** [comment]
Oh I see.. I though it tries to pick up vcs remote, used to work with two level domains earlier.
Behaviour Thank you for

**Comment by andrewmed** [comment]
I see. I thought it used to pick up a remote from vcs for two level domains O.K., but I can not reproduce this on the latest release branch anymore. So current behavior seems to be consistent for both two and three level domains. Thanks for comment!

**Comment by jayconrod** [comment]
@andrewmed It looks like it will check if there's a `.git/config` file with the `origin` being something at `github.com` specifically. But it won't try to convert other remotes into a module path, this is just a special case.
