### ISSUE TITLE
Why golang's map iterates slower than slice?

### ISSUE THREAD

**Issue by andyxning** [golang/go#30676]
Why golang's map iterates slower than slice? A reddit is also created: https://www.reddit.com/r/golang/comments/ayoi1q/why_golangs_map_iterates_slower_than_slice/

**Comment by mvdan** [comment]
Communitites like Reddit or golang-nuts is where you should ask these questions; see https://github.com/golang/go/wiki/Questions. I don't see the need to also have a thread here, unless you have a particular idea in mind to speed up map iteration.
