### ISSUE TITLE
fmt, errors: empty messages in the error chain result in ugly messages

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#30683]
<pre>
$ go version
go version devel +ce7534ff06 Fri Mar 8 13:46:43 2019 +0000 linux/amd64
</pre>

### What did you do?

https://play.golang.org/p/ewauxpVAIji

### What did you expect to see?

I would expect to see:

     a: xxxx

### What did you see instead?

Instead we see:

    a: : xxxx

It's not uncommon to want to wrap errors just to record the location without adding any message (adding an annotation at every level can end up with unwieldy messages), so I think a colon separator should only be printed if there's something to print.

**Comment by andybons** [comment]
@robpike

**Comment by jimmyfrasche** [comment]
@jba @neild

**Comment by jba** [comment]
@mpvl

**Comment by adg** [comment]
Is this bug still current? I don't see an `errors.Printer` type in the `errors` package.

**Comment by rogpeppe** [comment]
It seems that the error printing stuff has been removed from errors in tip. I'm not sure what the roadmap is here.

**Comment by neild** [comment]
With the removal of `FormatError`, this is obsolete.
