### ISSUE TITLE
errors: Printer.Printf does not define semantics

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#30682]
<pre>
$ go version
go version devel +91170d7201 Thu Mar 7 15:36:29 2019 +0000 linux/amd64
</pre>

The new errors.Printer interface defines a Printf method, but does not document its semantics.
This means that when implementing Printer, it's not clear what form the format string should take.

Perhaps we should document that the format and args are as documented by fmt.Printf:

	// Printf writes a formatted string. The format and arguments are as defined by fmt.Printf.
	Printf(format string, args ...interface{})

**Comment by andybons** [comment]
@mpvl

**Comment by seankhliao** [comment]
I don't think this made it into an actual release.
