### ISSUE TITLE
cmd/go: trimpath gcflag not trimming anything

### ISSUE THREAD

**Issue by xibz** [golang/go#30696]
### What version of Go are you using (`go version`)?
v1.12.0
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xibz/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xibz/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xibz/firectl/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build920574943=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
<pre>
$ go build -a -o foo -gcflags=-trimpath=/home/xibz -asmflags=-trimpath=/home/xibz
$ strings foo | grep xibz
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/fold.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/extension.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/encode.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/scanner.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/decode.go
</pre>

### What did you expect to see?
<pre>
$ strings foo | grep xibz
</pre>

### What did you see instead?
<pre>
$ strings foo | grep xibz
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/fold.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/extension.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/encode.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/scanner.go
/home/xibz/go/pkg/mod/github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb/internal/json/decode.go
</pre>

**Comment by andybons** [comment]
@ianlancetaylor

**Comment by ianlancetaylor** [comment]
Is there a way that we can recreate what you are seeing?

When I try simple test cases it works as expected for me.

Thanks.

**Comment by xibz** [comment]
@ianlancetaylor - What simple cases are you checking against? I can reproduce this with this code.
```go
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
)

func main() {
	fmt.Println(aws.String("Hello world!"))
}
```
I then build it like so
`go build -a -o main -gcflags=-trimpath=/home/xibz -asmflags=-trimpath=/home/xibz main.go`

**Comment by AlexRouSg** [comment]
Try `go build -a -o main -gcflags=all=-trimpath=/home/xibz -asmflags=all=-trimpath=/home/xibz main.go`

**Comment by xibz** [comment]
@AlexRouSg - That did it! Thanks :). Closing
