### ISSUE TITLE
[Question] riscv64 yocto  golang build issue

### ISSUE THREAD

**Issue by pino-kim** [golang/go#30697]
### What version of Go are you using (`go version`)?
golang 1.11.4

I'm stuck build go at yocto on riscv64.
below is my error log.

<pre>
DEBUG: Executing shell function do_compile
Building Go cmd/dist using /home/pino/workspace/Opensource/RISCV/riscv-yocto-64/build/tmp-glibc/work/riscv64-oe-linux/go/1.11.4-r0/recipe-sysroot-native/usr/lib/go.
Building Go toolchain1 using /home/pino/workspace/Opensource/RISCV/riscv-yocto-64/build/tmp-glibc/work/riscv64-oe-linux/go/1.11.4-r0/recipe-sysroot-native/usr/lib/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building std,cmd for target, linux/riscv64.
-buildmode=pie not supported on linux/riscv64
go tool dist: FAILED: /home/pino/workspace/Opensource/RISCV/riscv-yocto-64/build/tmp-glibc/work/riscv64-oe-linux/go/1.11.4-r0/go/pkg/tool/native_native/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 1
WARNING: /home/pino/workspace/Opensource/RISCV/riscv-yocto-64/build/tmp-glibc/work/riscv64-oe-linux/go/1.11.4-r0/temp/run.do_compile.32308:1 exit 2 from './make.bash --target-only --no-banner'
ERROR: Function failed: do_compile (log file is located at /home/pino/workspace/Opensource/RISCV/riscv-yocto-64/build/tmp-glibc/work/riscv64-oe-linux/go/1.11.4-r0/temp/log.do_compile.32308)
</pre>

So I list some question

1. Golang version 1.11.4 fully support riscv architecture in current upstreaming? 

2. If not there is the working group for golaong work on riscv architecture?

**Comment by ianlancetaylor** [comment]
> Golang version 1.11.4 fully support riscv architecture in current upstreaming?

No.

> If not there is the working group for golaong work on riscv architecture?

See #27532.
