### ISSUE TITLE
possible flaotingpoint precision error

### ISSUE THREAD

**Issue by Komplementariteten** [golang/go#30703]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/Workspace/Github/Go:/Users/me/Library/Golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tc/s70_0jsd3tg2x40vdrp4pyqc0000gn/T/go-build341963323=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Try to add floating numbers and then adding the same number multiplied by -1

https://play.golang.org/p/BOv4eMIXUp3

### What did you expect to see?
Addition resulting in the same number as before
f4 = 5

### What did you see instead?
f4 = 5.000000000000002

**Comment by mvdan** [comment]
See https://github.com/golang/go/issues/30544.

**Comment by ALTree** [comment]
Also see https://floating-point-gui.de/ for an accessible explanation of how floating point arithmetic works. Closing here, since this is not a Go bug.
