### ISSUE TITLE
cmd/go: TestScript/build_acl_windows fails on windows-arm builder

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#30711]
windows-arm builders seems to be broken

https://build.golang.org/log/2579a41ab2b6bafce55876919188aa9933e746d2

with
```
--- FAIL: TestScript (0.08s)
    --- FAIL: TestScript/build_acl_windows (12.53s)
        script_test.go:189: 
            # Create $WORK\guest and give the Guests group full access.
            # Files created within that directory will have different security attributes by default. (3.085s)
            # Build a binary using the guest directory as an intermediate (6.094s)
            # Build the same binary, but write it to the guest directory. (3.162s)
            # Read ACLs for the files. (0.072s)
            > exec powershell -Command 'Get-Acl main.exe | Select -expand AccessToString'
            [stderr]
            S�t�a�r�t�i�n�g� �t�h�e� �C�L�R� �f�a�i�l�e�d� �w�i�t�h� �H�R�E�S�U�L�T� �7�e�.�
�
            �[exit status -65536]
            FAIL: testdata\script\build_acl_windows.txt:20: unexpected command failure
            
FAIL
FAIL	cmd/go	918.021s
```

Probably since https://go-review.googlesource.com/c/go/+/165752 was submitted.

The error message is not very helpful. And I do not have windows-arm computer to debug. @jordanrh1 can you, please, help to debug this? Thank you.

Alternatively, maybe we could revert CL 165752 ? Leaving for @bcmills to decide.

Alex

**Comment by bcmills** [comment]
The difference is probably due to the more restricted environment for script tests. The setup for that environment is here:
https://github.com/golang/go/blob/fd080ea3bcc2b170b787b38ab7920d170ca65682/src/cmd/go/script_test.go#L101-L132

Given the generally shaky state of the windows-arm builder, I'm inclined to add a skip until the test is fixed rather than roll back the change.

**Comment by bcmills** [comment]
Looks like `exec.LookPath` uses the `PATHEXT` variable on Windows. We should probably preserve that.
https://github.com/golang/go/blob/fd080ea3bcc2b170b787b38ab7920d170ca65682/src/os/exec/lp_windows.go#L61

**Comment by alexbrainman** [comment]
> The difference is probably due to the more restricted environment for script tests.

I agree, this could well be the problem here. It just we don't know which environment variable must not be skipped.

> Looks like `exec.LookPath` uses the `PATHEXT` variable on Windows. We should probably preserve that.

I don't see what you you mean by that. script_test.go uses standard os/exec package to implement everything - it should just work. No?

Alex
