### ISSUE TITLE
modules: questions on how to semver libtor

### ISSUE THREAD

**Issue by karalabe** [golang/go#30718]
*This is a meta issue. Feel free to close it if you deem it inappropriate, but I'm curious what the "Go modules" way of solving it is. Also, I'm certain there are other large code bases for which modules are not trivial, so it might be a good pointer for them too.*

---

I'm the author of [github.com/ipsn/go-libtor](https://github.com/ipsn/go-libtor), which is a suite of Go wrappers around Tor and its dependencies (OpenSSL, LibEvent2, ZLib). The package currently mostly works with go modules (apart from `go mod vendor`, which breaks apparently "by design" https://github.com/golang/go/issues/26366).

My question is around versioning the package. The API doesn't change much - if at all - so I could easily release the thing under v1.0.0. Every night I have a cron job that pulls in any upstream changes from `zlib`, `libevent`, `openssl` and `tor` and pushes out a new version if something changed. I could auto-bump v1.0.0 to v1.0.X. This would make `go mod` happy.

The problem is, `libtor` is a wrapper around Tor. As such, dreaming up my own versioning to satisfy `go mod` is an incorrect approach, because the important version number is not that of the Go code, rather the upstream C code.

The upstream code currently is at `0.3.5.8-dev`. How can I incorporate this version number into something that `go mod` likes? Furthermore, even between Tor version bumps, my wrapper can have new releases due to openssl fixes, so realistically my "true version" should be something along the lines of `0.3.5.8.X`.

This 5-component version number is way out of `go mod`-s league, yet this seems the correct number. So, what's the official recommendation of solving this issue? Does `go mod` support version numbers with more than 3 nestings? Does it support version numbers with strings in them?

Thanks

**Comment by bcmills** [comment]
Arguably the version number for your wrapper should indicate the version of the wrapper itself, not the version of the underlying library that it wraps.

Do the underlying C libraries have stable C APIs? If so, perhaps you don't need to list their versions at all.

**Comment by bcmills** [comment]
Actually, I see that the wrappers are not quite structured in the way that I would expect: you're not wrapping a separate `libtor`, you're actually integrating it into the Go library itself. In that case, you probably don't need to track the upstream versions at all: your version number should reflect your module's API, not its dependencies.

If you want the tags to be a bit more descriptive, you could embed the upstream versions as [build metadata](https://semver.org/#spec-item-10). (But I think the `go` command currently drops that metadata anyway.)
