### ISSUE TITLE
x/image/webp: Missing RIFF Chunk Header

### ISSUE THREAD

**Issue by yaput** [golang/go#30712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bluelogic2/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bluelogic2/Desktop/Antonius/Work/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dq/_cn_jltj0058y0n7ds3_65t80000gn/T/go-build699185468=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
	imgData, err := os.Open(filename)
	if err != nil {
		log.Printf("%+v", err)
		return
	}
	image, err := webp.Decode(imgData)
	if err != nil {
		log.Printf("WEBP DECODE : %+v", err)
		return
	}
        ....
```

### What did you expect to see?
Decoded webp

### What did you see instead?
riff: missing RIFF chunk header

**Comment by ALTree** [comment]
Thanks for reporting this.

Can you attach (or give a link to) the image that trigger the issue? It also would be nice to have a complete, runnable reproducer (that includes a main function).

**Comment by yaput** [comment]
Thanks for responding this, here is the [image](https://drive.google.com/open?id=1OQs10672eYlPLhD1R9rR4bgxI9TozC_0) 

and for main function
```
func main(){
	imgData, err := os.Open("343b0a37201220b80909cbebebe8ef21.webp")
	if err != nil {
		log.Printf("%+v", err)
		return
	}
	image, err := webp.Decode(imgData)
	if err != nil {
		log.Printf("WEBP DECODE : %+v", err)
		return
	}
	newImage := resize.Resize(300, 0, image, resize.Lanczos3)
	newFilename := "resized_image/" + strings.Replace(filename, "webp", "jpg", -1)
	os.Create(newFilename)
	newImg, _ := os.Open(newFilename)
	defer newImg.Close()
	// Encode uses a Writer, use a Buffer if you need the raw []byte
	err = jpeg.Encode(newImg, newImage, nil)
	if err != nil {
		log.Printf("%+v", err)
		return
	}       
         
}
```
Maybe the function is not working, cause i change the format from webp to jpeg, but i can't find webp encoder function in webp package, so i just tried to saved the resized image. Thanks a lot

**Comment by antong** [comment]
@yaput , Can you double check that the file contents are what you think they are. I downloaded your file (sha1sum dafb30bfe35c7296052f9279d2368d4e92d509e0) and it decoded fine, without errors.

```
func main() {
        imgData, err := os.Open("343b0a37201220b80909cbebebe8ef21.webp")
        if err != nil {
                fmt.Println(err)
                return
        }
        image, err := webp.Decode(imgData)
        if err != nil {
                fmt.Println(err)
                return
        }
        fmt.Println(image.Bounds())
        // Output:
        // (0,0)-(400,156)
}
```

**Comment by yaput** [comment]
Hi @antong , found something, it is not in the webp package, but maybe i did something wrong when downloaded the image from url with golang. After i tried to download the image from browser, it works. Maybe i will find another round to store the image before resizing it. Thanks!
