### ISSUE TITLE
cmd/go: improve error message when a package does not exist

### ISSUE THREAD

**Issue by perillo** [golang/go#30723]
#### What did you do?

In a simple Go program I have a misspelled package import.
As an example

```go
package main

import "logz"
```

#### What did you expect to see?

The go tool should report an error message with the file, line and column where the error occurred.
As an example:

```
main.go:3:2: cannot find package "logz" in any of:
	/usr/lib/go/src/logz (from $GOROOT)
	/home/manlio/.local/lib/go/src/logz (from $GOPATH)
	/home/manlio/code/src/go/src/logz
```

#### What did you see instead?

```
build xxx: cannot load logz: cannot find module providing package logz
```

There is no additional information; just the module where the problem occurred and the error message.

#### System details

```
go version go1.12 linux/amd64
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/code/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/manlio/code/src/python/app/lci/isosmart.it/go.mod"
GOROOT/bin/go version: go version go1.12 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.12
uname -sr: Linux 4.20.13-arch1-1-ARCH
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.28.
gdb --version: GNU gdb (GDB) 8.2.1
```

**Comment by perillo** [comment]
Of course the expected output should be something like:

```
build xxx: main.go:3:2: cannot load logz: cannot find module providing package logz
```

Thanks.

**Comment by bcmills** [comment]
See also #30661 and #27102.

(CC @jayconrod)

**Comment by manishmshiva** [comment]
Yeah. This looks far better than the original log. I can try and fix this if @jayconrod is busy.

**Comment by jayconrod** [comment]
@manishmshiva You're welcome to take a look. I'm not sure if I'll get to this for a few days.

This error is reported by the build list loading code in src/cmd/go/internal/modload/load.go. Some additional plumbing will be required to store the import positions.

**Comment by bcmills** [comment]
@jayconrod, was this fixed by your import-stack changes?

**Comment by jayconrod** [comment]
I'm not sure when this was fixed, but the output in go1.13beta1 looks good:

```
$ go build ./a
b/b.go:3:8: unknown import path "example.com/logz": cannot find module providing package example.com/logz
```

It's debatable whether `cannot find module providing package` communicates enough information, but #28459 seems more specific to that. The problem in this issue was that we didn't print the location where the error occurred.
